### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by minhcasi** [inspireui/support#1]
The example report for the issue

**Required Info (please complete the following information):**
 - Product: Mstore v3.5.0
 - Your Purchased Code: 3929-3929-3929-3929 (or the screenshot of your purchased)

**Describe the bug**
This is an example of the bug for Mstore

**Screenshots**
![icon](https://user-images.githubusercontent.com/1459805/48247722-faa7ef00-e426-11e8-9324-6fd0fa5c7e88.jpg)

**Additional context**
Please help me to resolve the issue - thank you!

@inspireui/team

**Comment by minhcasi** [comment]
[Solution] - "Couldn't find the binary sh" with yarn

If you are using Window OS, this is the common issues when run yarn install for most of the project, if
you could look in detail error log, you can find the issue "...Couldn't find the binary sh..."
**Root cause**: missing git installing or the PATH is not available from the environment.
**Solution**: follow this detail guide and screenshot - https://hackernoon.com/install-git-on-windows-9acf2a1944f0

**Comment by minhcasi** [comment]
EvaStore Installing issues - https://github.com/inspireui/support/issues/45

**Comment by minhcasi** [comment]
[Beonews] New version 2.9.2 missing FBSDKShareKit.h -  #211

**Comment by thangvo9x** [comment]
[MMV] Fix Unable to Proceed with Payment or 404 Not Found when Checkout
=> Solution: Go to admin page -> Pages menu item -> create a page with Template Name is "Page Custom Template".

**Comment by thangvo9x** [comment]
[MMV] Fix Product Variations not be displayed / can't get it
=>Solution: Go to src/containers/Detail/index.js line 81 => uncomment it and restart the app.

**Comment by Foxxerman** [comment]
And I would like to know also how to set minimum quantity for purchasing?

**Comment by thangvo9x** [comment]
[MMV] Can't find variable: Styles
=>Solution: Replace this file in src/Components/VendorInfo/index.js
p/s: rename .txt -> .js
[index.txt](https://github.com/inspireui/support/files/2854590/index.txt)

**Comment by minhcasi** [comment]
Update latest Expo version could cause VERY SLOW at development mode (as you will get the "require cycle: " warning), and the icons/images load quite slow.


Solution: remove the IF block from node_modules/metro/src/lib/polyfills/require.js (https://gyazo.com/df9e8c80e88d51fed30807b0a369e7e1) - Or, select the build with PRODUCTION MODE to resolve the issues)

**Comment by minhcasi** [comment]
No bundle URL present on new project
[](https://user-images.githubusercontent.com/18483911/38866407-10fd57c8-4241-11e8-929c-055413468617.png)

### Root cause: the simulator could not connect to your node server to get the js bunndle 

### solution
Open hosts file: sudo vim /etc/hosts 
Add three lines:

127.0.0.1 localhost
255.255.255.255 broadcasthost
::1 localhost

**Comment by jhonsonmusic** [comment]
I'm using the Expo version, but when I try to upload the app to the Google store the PlayStore console says that the APK is in 32 bits and does not let it send for review because it only accepts 64-bit apk. What I can do?

**Comment by jhonsonmusic** [comment]
I'm using the Expo version, but when I try to upload the app to the Google store the PlayStore console says that the APK is in 32 bits and does not let it send for review because it only accepts 64-bit apk. What I can do?

**Comment by peterelvis95** [comment]
I try unzipping BuzzApp, I have been encountering issues why are
![APP](https://user-images.githubusercontent.com/53198896/61671970-b1ac7800-ace1-11e9-888d-1a4103df1c2b.JPG)
![app1](https://user-images.githubusercontent.com/53198896/61671973-b40ed200-ace1-11e9-88e3-a169efeeba64.JPG)

 the issues happening and how can I resolve it

**Comment by minhcasi** [comment]
@peterelvis95  - it seems you have the virus on your machine - that download package does not include these file - thanks
