### ISSUE TITLE
Build Failed!! 3.6.3

### ISSUE THREAD

**Issue by anosmx** [inspireui/support#10]
Hi,

I’ve downloaded the new version 3.6.3 and when i build it I get an error.
[Image](https://discuss.spotui.com/uploads/default/optimized/1X/b7d3c15fe99a2f9e26b130d623cc3016f8695fe2_1_1380x982.jpeg)

**Comment by luyx2412** [comment]
Hi anosmx, Please follow the step to fix the issue related XCode 10

1. In your project `cd node_modules/react-native/third-party/glog-0.3.4`
2. Run script `../../scripts/ios-configure-glog.sh`

Thanks

**Comment by anosmx** [comment]
Hi,

Thanks for replying, but I don't know how to perform these steps.
1. I should go to this directory `cd node_modules/react-native/third-party/glog-0.3.4` and then what?
2. What is the terminal command to run this file? I've tried `run ../../scripts/ios-configure-glog.sh` but it didn't work!!


Thanks!
