### ISSUE TITLE
[Mstore pro] - slider name in home erro

### ISSUE THREAD

**Issue by mohamedibrahim89** [inspireui/support#1000]
1. My issue
First issue
every time i try to add label name from cbuilder to slider in home app show without slider name
Second issue 
Can u tell me how to setup mobile app notification in one singal in expo version not in pro version

2. Screenshots
![20190829_083232](https://user-images.githubusercontent.com/35544603/63915950-90a11a80-ca37-11e9-9cd6-487758e32f18.jpg)

**Comment by minhcasi** [comment]
Hi, the name of this label should be the key from common/languages.js file - https://tppr.me/NtJrT

example: featureProducts will not display exactly "featureProducts" it will display "Feature Products"

(By this way it will support the multi languages features when you switch to other language)

The onesignal is not supported for the Expo version yet, you can follow this request feature from - https://expo.canny.io/feature-requests/p/one-signal-push-notification
