### ISSUE TITLE
Fluxstore 1.4.3

### ISSUE THREAD

**Issue by samik9** [inspireui/support#1002]
1. Auto slider does not work with  **"design": "swiper",** only work with _"**default**"_
2. There are some missing translations, the Order Placed and the loading text, I double check it
<img width="483" alt="iPhone Xʀ — 12 4 2019-08-29 03-24-27" src="https://user-images.githubusercontent.com/50071744/63923833-d72d4f80-ca0c-11e9-9e29-e3fd5a2cf10a.png">

![iPhone Xʀ — 12 4 2019-08-29 03-21-36](https://user-images.githubusercontent.com/50071744/63923840-d8f71300-ca0c-11e9-82b2-5681483fa8d3.jpg)

3. If order **failed** or **pending** the screen is the same that **succesfull** order placed 

![iPhone Xʀ — 12 4 2019-08-29 03-30-08](https://user-images.githubusercontent.com/50071744/63924156-65093a80-ca0d-11e9-960c-839c9e9c5e9e.jpg)

4. Whatsapp buttton, does not work

**Comment by minhtruong315** [comment]
@samik9 send me config.json and config.dart file?

**Comment by samik9** [comment]
Hi, please check the files here https://d.pr/f/Z6Uhta

**Comment by minhtruong315** [comment]
@samik9 we fixed issue loading. If you want to change language for Order Placed, you can edit file screens/checkout/success.dart

**Comment by samik9** [comment]
Thank you @minhtruong315 . What about point # 3: 
**If order failed or pending the screen is the same that succesfull order placed**

**Comment by minhtruong315** [comment]
@samik9 if  order failed it will show error. if order pending, the screen is the same successful
