### ISSUE TITLE
[Flutter] - questions about 

### ISSUE THREAD

**Issue by Pars1vaLl** [inspireui/support#1004]
Hi,

My purchase code: https://user-images.githubusercontent.com/45024483/63820143-9af0e500-c961-11e9-8005-114a7ac9e36b.png
I have few questions and hope to your fast respond.

1. I need to set only one language in the App and replace "Languages" button.
![22](https://user-images.githubusercontent.com/45024483/63956596-2c667100-caa0-11e9-939a-1ff9532e760f.jpg)

2. How can I integrate Visa and Mastercard payments in Flusxtore? Is there any tutorials. Will WooCommerce payment method work for the App?
3. How can I remove top Vertical-menu in the App: 
![photo_2019-08-29_20-52-18](https://user-images.githubusercontent.com/45024483/63955919-f2489f80-ca9e-11e9-9aa0-7465d90056a6.jpg)

Thanks=)

**Comment by minhcasi** [comment]
1. you can remove this menu from the setting screen - https://tppr.me/dZxWY

2. We have not tested on visa and mastercard, but it will work the same on your woocommerce site

3. Open the common/config.json file and remove the category config

Thank you!
