### ISSUE TITLE
[Fluxstore 1.4.3] - Issues on customizing the template

### ISSUE THREAD

**Issue by yngwieduane** [inspireui/support#1005]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue
 when I'm changing the config file, in the app is not loading, it only loads the template images and its category id. I want to change this. also the login is not working we cant use this function.

2. Screenshots

![WhatsApp Image 2019-08-29 at 9 11 54 PM (1)](https://user-images.githubusercontent.com/18515128/63961395-c7ac1600-caa1-11e9-913c-1e17ff5be147.jpeg) . This is for the config file that even though we are changing it, still not working

![WhatsApp Image 2019-08-29 at 9 11 54 PM](https://user-images.githubusercontent.com/18515128/63961457-e90d0200-caa1-11e9-938e-736ca122cfdf.jpeg) . This is the error we received when we try to login via facebook. also can we add google login??

![WhatsApp Image 2019-08-29 at 9 11 54 PM (2)](https://user-images.githubusercontent.com/18515128/63961515-06da6700-caa2-11e9-9401-24cb6d29ae27.jpeg) . This error shows when we try to create an account in the app itself.

3. My screenshot of the purchase product or my comment:
![image](https://user-images.githubusercontent.com/18515128/63961673-5e78d280-caa2-11e9-8399-cb6494c5361b.png)

3. Config files (optional)

**Comment by minhtruong315** [comment]
@yngwieduane send me config.json and config.dart file via email: truong@inspireui.com

**Comment by yngwieduane** [comment]
@minhtruong315  I sent it to your email.

**Comment by yngwieduane** [comment]
Do you also have a documentation for customization of the homepage? Like if we are going to add 2 or more sliders?

**Comment by minhtruong315** [comment]
@yngwieduane you can check this document: https://docs.inspireui.com/fluxstore/customization/

**Comment by yngwieduane** [comment]
how about some configuration in firebase and firestore??

**Comment by minhtruong315** [comment]
@yngwieduane did you change facebook id?

**Comment by yngwieduane** [comment]
where can we change that?

**Comment by minhtruong315** [comment]
@yngwieduane can you send me source code via email: truong@inpireui.com
with subject: https://github.com/inspireui/support/issues/1005
i will check your source code
