### ISSUE TITLE
[FluxStore] - Login Problem

### ISSUE THREAD

**Issue by matrixaldy** [inspireui/support#1006]
error when i login, can help me?

![Screen Shot 2019-08-30 at 4 39 10 PM](https://user-images.githubusercontent.com/22363606/64010936-e0b9d300-cb44-11e9-8fd7-a319f7ebaaf2.png)

**Comment by icarofdez** [comment]
Same problem here

**Comment by minhtruong315** [comment]
@matrixaldy can you send me config.dart and config.json file via email: truong@inspireui.com.
with title: https://github.com/inspireui/support/issues/1006

**Comment by matrixaldy** [comment]
the previous problem has resolved. now, this is my new problems
![Screenshot_2019-09-02-15-18-45-525_com enstramedia muslimcollection](https://user-images.githubusercontent.com/22363606/64226428-900df580-cf09-11e9-92bd-0a0ac8f397ed.png)

**Comment by minhtruong315** [comment]
@matrixaldy I checked your config. but i see it is different with our format config. did you change it?
```
  "server": {
    "type": "custom",
    "url": "https://mobile.muslimcollection.id",
    "blog": "http://fluxstore.inspireui.com",
    "forgetPassword": "http://demo.mstore.io/wp-login.php?action=lostpassword"
  },
```
We don't use type: custom in config fluxstore

**Comment by matrixaldy** [comment]
i'm customize my API, built with laravel

**Comment by minhtruong315** [comment]
As the code is customized and change the API that is not required effort to check and investigating, also not include from our support scope, please try your best to resolve the issue
