### ISSUE TITLE
dear 1 issue :how to off test ads  and can,t confrim order 

### ISSUE THREAD

**Issue by tharicode** [inspireui/support#101]
- Product: MStore, ListApp
 - Your Purchased Code: 8c003706-a28e-4be4-bf3f-c1dc86bfb7da

**Describe the bug**
1st issue : how to off ads 

2nd Issue : confirm order button not getting any action 
![123](https://user-images.githubusercontent.com/45279029/50009927-3281f380-ffde-11e8-8a80-a7e4e43b9f4d.PNG)
 
loading and after normally confirm order button have not continue 
 
![456](https://user-images.githubusercontent.com/45279029/50011897-3fedac80-ffe3-11e8-905e-0ba845e79fe1.PNG)

**Comment by minhcasi** [comment]
Fixed on next coming release - thank you!

**Comment by samber91** [comment]
Hi, if you were able to fix your issue, please share with me at jb.ro.corp2018@gmail.com    . I'm having the same issue and i'm desperate in finding some answers. thanks
