### ISSUE TITLE
[my-product] - BeoNews Pro

### ISSUE THREAD

**Issue by paulica40** [inspireui/support#1012]
1. My issue
I am getting this error 

2. Screenshots
https://user-images.githubusercontent.com/54144509/64059838-7e0c1a00-cbcc-11e9-975b-9d6057cbafdf.png

3. My screenshot of the purchase product or my comment:
https://user-images.githubusercontent.com/54144509/64059862-e0fdb100-cbcc-11e9-83ff-8de2aeafd207.png

3. Config files (optional)

**Comment by paulica40** [comment]
what config files do you need?

**Comment by minhcasi** [comment]
Hi @paulica40 - the config that locates from the common folder, file appconfig.json and config.js - thank  you!

**Comment by paulica40** [comment]
Here are the config files


[config.pdf](https://github.com/inspireui/support/files/3563194/config.pdf)
[appconfig.pdf](https://github.com/inspireui/support/files/3563195/appconfig.pdf)

**Comment by paulica40** [comment]
i can scroll the posts in every category, but when i try to view an older post like 15th or 20th, i got the error of scrolltoindex out of range.

**Comment by minhtruong315** [comment]
@paulica40 can you send me which post has error? i checked your config, i see it is working well
