### ISSUE TITLE
[MSTORE -PRO] Checkout page not working

### ISSUE THREAD

**Issue by ItisAhsan** [inspireui/support#1013]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue : 
I have enabled stripe checkout.. and I have created a a page for mstore-checkout with the custom template.. it display's the form but keeps refreshing.. Tried to debug from the browser there was this error in console 

Error: We could not retrieve data from the specified Element.
              Please make sure the Element you are attempting to use is still mounted.

2. Screenshots
![Screenshot_1567265317](https://user-images.githubusercontent.com/12572962/64066139-cb6da300-cc2f-11e9-9066-6b4fd2106dd5.png)

**Comment by ItisAhsan** [comment]
Proof of Purchase
![image](https://user-images.githubusercontent.com/12572962/64066156-f8ba5100-cc2f-11e9-9257-4403d6c111cb.png)

**Comment by minhcasi** [comment]
Thank you @ItisAhsan - could you attach your config files here, we need to debug for investigating on this issue - thank you!

**Comment by ItisAhsan** [comment]
I have emailed the config files at support@inspireui.com

**Comment by minhcasi** [comment]
Noted for checking, thank you!

**Comment by ItisAhsan** [comment]
Hi there.. any update regarding the issue?

**Comment by minhcasi** [comment]
@ItisAhsan 

It seems the issue related to the website config.

Could you try to debug from the website - /mstore-checkout/templates/mstore-checkout-template.php - try to debug this order value after getting the URL from the app side - https://tppr.me/MVYw2 ?

**Comment by leghost** [comment]
please any update regarding this issue?

**Comment by leghost** [comment]
@minhcasi please be more explixite. i'm facing the same problem.

**Comment by ItisAhsan** [comment]
> 
> 
> @ItisAhsan
> 
> It seems the issue related to the website config.
> 
> Could you try to debug from the website - /mstore-checkout/templates/mstore-checkout-template.php - try to debug this order value after getting the URL from the app side - https://tppr.me/MVYw2 ?
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/509124d8882984b18ff448d774fd69606b0c3f56/68747470733a2f2f747070722e73332e616d617a6f6e6177732e636f6d2f75706c6f6164732f34386530323630653235666663393766383362396237333939373030663564642e706e67"><img alt="" height="14" src="/favicon-32x32.png"> tppr.me**[Public Screenshots - Google Chrome_2019-09-03 14-01-56](https://tppr.me/MVYw2)**

I couldn't debug... can you do that for me? I can give you access?

**Comment by ItisAhsan** [comment]
Hi there? can you debug that?

**Comment by minhcasi** [comment]
@ItisAhsan - this could only debug from your website, please follow by these steps:

1. process the checkout from the app at the payment step

2. Get the Order request that having the format: (you can use the react native debugger or install reacttotron - https://github.com/infinitered/reactotron), the link have format .../mstore-checkout?order=xxx

3. The go the wordpress plugin on your site, and var_dump the return data or userId from /mstore-checkout/templates/mstore-checkout-template.php - screenshot https://tppr.me/MVYw2

**Comment by ItisAhsan** [comment]
![Screenshot_2019-09-11 mstore-checkout – Halal Meats](https://user-images.githubusercontent.com/12572962/64689025-fa450e00-d4a6-11e9-80b4-c30dbbc94d66.png)
this is what I got.. I still can't see what's wrong

**Comment by ItisAhsan** [comment]
this was the error in console
![image](https://user-images.githubusercontent.com/12572962/64689084-147eec00-d4a7-11e9-9496-74874228bf56.png)

**Comment by minhcasi** [comment]
Hi could you try to run the wp_enqueue_scripts to remove the touch-keyboard-navigation.js out from the mstore-checkout page, this script causes the broken on this feature

**Comment by ItisAhsan** [comment]
> 
> 
> Hi could you try to run the wp_enqueue_scripts to remove the touch-keyboard-navigation.js out from the mstore-checkout page, this script causes the broken on this feature

no... it's not because of that.. it's because of the error from v3.js ... that is one of the stripe's script.. the touch-keyboard-navigation.js error's just showed when I disabled the activated theme to check if the issue was caused by the theme.. see this console for result after the theme was activated
![image](https://user-images.githubusercontent.com/12572962/64763700-0047f700-d55a-11e9-96e6-6c43efb07db6.png)

**Comment by minhcasi** [comment]
@ItisAhsan - it seems the error is caused by a conflict wordpress plugin on your site, if you would like to refer to the native payment from mstore 3.3 we could share so that you can customize your own component

**Comment by ItisAhsan** [comment]
yes.. please

**Comment by minhcasi** [comment]
hi, please share the email and note this ticket to support@inspireui.com - we will share it privately - thank you!
