### ISSUE TITLE
EvaStore - Varible issues

### ISSUE THREAD

**Issue by lineacoin-project** [inspireui/support#1014]
Hello, 

My store currently has some items with variants and other products without, when the products with variants show on the app its fine, but when the products without variants it shows Default Title can this be blank if there is no variant applied to the product?

Kind Regards

**Comment by minhcasi** [comment]
Hi, could you provide the purchased screenshot and also sharing the screenshot of the issue, thank you!

**Comment by lineacoin-project** [comment]
please see attached
![Capture](https://user-images.githubusercontent.com/6841669/64192230-1840bc00-ce72-11e9-979d-82e412bb4a2f.PNG)
![issue](https://user-images.githubusercontent.com/6841669/64192241-21ca2400-ce72-11e9-82e9-f8a092098ddd.jpg)

**Comment by minhcasi** [comment]
@minhtruong315  please help for checking - thank you!

**Comment by minhtruong315** [comment]
@lineacoin-project can you send me your source code via email: truong@inpireui.com
with subject: https://github.com/inspireui/support/issues/1014

**Comment by minhtruong315** [comment]
@lineacoin-project I checked your config. That product has an attribute. you need to remove it in admin
<img width="484" alt="Screen Shot 2019-09-05 at 09 41 26" src="https://user-images.githubusercontent.com/10402500/64307845-7e882480-cfc1-11e9-8c19-bea8d17af0a1.png">
if you don't want to show attributes in mobile app, you can remove attributes in containers/ProductDetailContainer/index.js
<img width="654" alt="Screen Shot 2019-09-05 at 09 43 55" src="https://user-images.githubusercontent.com/10402500/64307920-c3ac5680-cfc1-11e9-9e58-11cf9f0562d6.png">

**Comment by lineacoin-project** [comment]
Hi, the product on the admin side has no variable, the box is in ticked, I can't remove it as some items do have variables which it works fine for.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by lineacoin-project** [comment]
![Capture](https://user-images.githubusercontent.com/6841669/64316684-74f4c180-cfad-11e9-8549-7bca529ae418.PNG)

**Comment by minhtruong315** [comment]
can you send me account to login to admin panel via email: truong@inspireui.com

**Comment by lineacoin-project** [comment]
Hi, This has been sent.

**Comment by lineacoin-project** [comment]
Hello any update for this ?

**Comment by MamdouhRElNakeeb** [comment]
add this condition at "/ProductDetailsContainer/AnotherAttributes.js" in render function

> if (attrName === DEFAULT_TITLE) return null;

![Screen Shot 2019-09-16 at 1 46 37 AM](https://user-images.githubusercontent.com/16556982/64929238-f6f1af80-d823-11e9-881e-c778a6179acb.png)

**Comment by minhtruong315** [comment]
@lineacoin-project pls reply email

**Comment by lineacoin-project** [comment]
That worked thank you
