### ISSUE TITLE
MStore Pro 3.9.4b Facebook Login Error 

### ISSUE THREAD

**Issue by myothura** [inspireui/support#1016]
I recorded with ios emulator. When i try to login with FB it doesn't advance to next screen. so do you have any idea to fix this one. I also try with your original codecanyo file. But this one is also not working. I already mailed your team. Your team do not respond in 10 day. Please kindly tell me how to fix it? 
 
https://youtu.be/DEcKTmfvLUE

**Comment by minhcasi** [comment]
Thank you for reporting, we could double-check this issue and will update on this ticket

**Comment by concuacon** [comment]
Hello, @myothura can you run project with Xcode and show me log when user login with facebook?

**Comment by myothura** [comment]
Hello , This one is x code error log and video for facebook login error . 

https://youtu.be/NDthTMqktOI ( Video ) 

https://i.ibb.co/MCYfrpB/Screen-Shot-2019-09-05-at-5-41-52-PM.png ( Image ) 

Thanks a lot for care customers

**Comment by concuacon** [comment]
Hi @myothura, it seems this is your config error, u can check this link https://github.com/facebook/react-native-fbsdk/issues/425

**Comment by myothura** [comment]
Hi @concuacon  Follow the facebook/react-native-fbsdk#425

1. Already installed react-native-fbsdk

2. Add following lines to ios/PodFile and execute pod install

    pod 'FBSDKLoginKit'
    pod 'FBSDKShareKit' 

https://i.ibb.co/vzcmrqh/Screen-Shot-2019-09-05-at-8-16-01-PM.png

3. Set Info.plist 

https://i.ibb.co/WyCG1W2/Screen-Shot-2019-09-05-at-8-17-44-PM.png

4. Modify AppDelegate.m

https://i.ibb.co/Lt6L7dS/Screen-Shot-2019-09-05-at-8-19-23-PM.png

5. Modify App.js

https://i.ibb.co/pwnLRLv/Screen-Shot-2019-09-05-at-8-20-22-PM.png 

But not working ..... Please how to fix this error

**Comment by concuacon** [comment]
hmm...., @myothura delete node_modules/ folder and compress your source send me via wetransfer.com 
i'll check, my email tuan@inspireui.com

**Comment by myothura** [comment]
Hello @concuacon  i already send with my facebook login error source code with Wetransfer.com to tuan@inspireui.com . Please kindly check and fix for me thanks a lot elder brother ...  Thanks a lot for customer care...

https://i.ibb.co/mGN10jD/Screen-Shot-2019-09-06-at-2-02-18-PM.png

**Comment by myothura** [comment]
Hello sir, @minhcasi @concuacon  My facebook login error is not working yet . Please kindly fix for me. Thanks

**Comment by minhcasi** [comment]
@myothura - sorry for late response, could you try to remove the mstore-checkout and install this new library will fix the issues - https://wordpress.org/plugins/mstore-api/ - thank you!
