### ISSUE TITLE
[ListApp] UNABLE TO SIGNUP & LOGIN

### ISSUE THREAD

**Issue by shaaanishaan** [inspireui/support#1017]
Problem Details: 
- Signup: Dear I wana signup with new email address but app unable to register NEW USER. After enter NEW User data just show working on but after some seconds it stop and can't show any message.
- Login: As I take data from Website: I just try to login with existing register user on website to login in APP but show following message: "No route was found matching URL and request method" 
Could you please help to solve this matter.

Here is Screenshot show 
- Signup: https://i.paste.pics/6L37P.png
- Login: https://i.paste.pics/6L37C.png
 
Regarding purchase proof here is code last: **9715c7b53c
Purchase Date: 2019-08-20 18:46:28 UTC
If you need Appconfig file, please share your email,

**Comment by minhcasi** [comment]
HI, this issue is caused by missing config for the mstore-check, please check this guide https://docs.inspireui.com/mstore/wordpress-setting/

**Comment by shaaanishaan** [comment]
My dear minhcasi, This case related to ListApp not MStore. I already mentioned details above. Here is more details Mr. Minhcasi, I already have website & I just connect it with ListApp with MyListing theme. As after attachment successful with Website, I am unable to Login and Signup.  Please help in line. Regards

**Comment by shaaanishaan** [comment]
Dear, I am waiting from your side from last 9 days. As from last day here on github & on support & comments on codecanyan, I am waiting for your reply so please take look in this matter & guide me that how can I solve this matter, As I am facing two more problems that I want solution. 
These as under
1. Problem One
Check the attached image 
https://i.paste.pics/6LS2E.png
As I click on 'Explore Tours & Eevent' OR 'Explore Movies' I got like this
https://i.paste.pics/6LS5R.png   & https://i.paste.pics/6LS5V.png
Please guide me that How can I add "Events Category" under "Explore Tours & Events" & "Movies Category" under "Explore Movies"
Please guide as under description

2. Problem Two
Check the attached image
https://i.paste.pics/6LS83.png & https://i.paste.pics/6LS8G.png 
As Show that some Images show related text but some show nothing. Could you please guide me regarding this matter.
Note: All these issues related to the "ListApp" & I am using "MyListing" theme.

Hope to get positive reply from your side. 
Your's

**Comment by minhcasi** [comment]
@shaaanishaan - i've forwarded to the ListApp team for further checking, as you have raised the title and name Mstore that confuse us.

@thangvo9x - pls help for checking

**Comment by shaaanishaan** [comment]
Dear @thangvo9x are you there? Please help to solve this matter. Waiting

**Comment by shaaanishaan** [comment]
Dear @minhcasi  & @thangvo9x I am still waiting for your reply for solution of above mention issues. Please try to solve this matter. Advance Thanks

**Comment by thangvo9x** [comment]
Could you share your AppConfig.json for checking?
The problem second. You must change categoryId in your Theme at Config/Yourtheme and finding this block 
HomeCategories and change it same is id on your website.
