### ISSUE TITLE
[fluxstore] - Category page issue

### ISSUE THREAD

**Issue by ghanchi2000** [inspireui/support#1019]
This is the 3rd ticket i am opening but my issue is not resolving

We have 1000+ categories and in category page we see blank category 

Please connect with us in teamviewer and resolve the issue

Here is email preview, config file keys is in email
https://prnt.sc/p16l4l

**Comment by minhtruong315** [comment]
@ghanchi2000 Did you set CategoriesListLayout in config.dart with these values: sideMenu, column, subCategories

**Comment by ghanchi2000** [comment]
Yes we did it, Not all categories are loading only few are loading.

**Comment by minhtruong315** [comment]
send me your source code via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/1019

**Comment by ghanchi2000** [comment]
email sent to you

**Comment by minhtruong315** [comment]
<img width="599" alt="Screen Shot 2019-09-04 at 18 38 31" src="https://user-images.githubusercontent.com/10402500/64252008-ff084000-cf43-11e9-9f11-94cb1da91736.png">
you need to enable Rest Api in admin panel. 
it worked now
![Uploading Simulator Screen Shot - iPhone X - 2019-09-04 at 18.43.42.png…]()
const CategoriesListLayout = kCategoriesLayout.sideMenu;

**Comment by ghanchi2000** [comment]
Issue is same

card >>> blank category page
sideMenu >>> only few categories are showing
column >>> only few categories are showing
subCategories >>> only few categories are showing
animation >>> blank category page
grid >>> blank category page

**Comment by minhtruong315** [comment]
for card, animation, grid you need to update id for parent categories is 0. because it only show default categories that have id 0

**Comment by ghanchi2000** [comment]
how to update parent category to 0 ?

**Comment by minhtruong315** [comment]
sorry, you need to update category parent to 0

**Comment by ghanchi2000** [comment]
I am still unable to understand, how to update category parent to 0 ? can you please guide me ?

**Comment by ghanchi2000** [comment]
https://www.shopperspk.com/wp-json/wc/v3/products/categories?consumer_key=ck_email&consumer_secret=cs_email&parent=0

in this link 10 categories with parent 0 are listed, then why this app is not showing them ?
check email for keys
