### ISSUE TITLE
[mstore pro] - product images are not loading

### ISSUE THREAD

**Issue by shu006** [inspireui/support#102]
mstore pro
53ac3826-0d28-440b-a310-e306c326a897

Product images are not loading in mstore pro app.

I already installed Better Rest API Featured Image and Regenerate Thumbnails plugin on wordpress. Tried to disable ProductSize in config.js. Still images are not loading.

**Comment by minhcasi** [comment]
Hi, i'm sorry for missing reply, could you help to share your config.js file so that we could help to quick checking
