### ISSUE TITLE
[EvaStore] - Quick Add to cart

### ISSUE THREAD

**Issue by alaaeallam** [inspireui/support#1020]
how to show add to cart icon in the product items like adding the product to wishlist ?

**Comment by minhcasi** [comment]
@alaaeallam pls note
1. provide your purchase screenshot
2. create one ticket with your all issues, pls note that we will not reply the "How to" - as this kind of Customization question that not include on our support scope and require the Technical skills to resolve it, we only support the bug or installing issue from the app.

Thank you!

**Comment by alaaeallam** [comment]
[54111257-evastore-shopify-mobile-store-by-react-native-and-graphql-license.pdf](https://github.com/inspireui/support/files/3573798/54111257-evastore-shopify-mobile-store-by-react-native-and-graphql-license.pdf)

HYG

**Comment by alaaeallam** [comment]
If there any update?

**Comment by alaaeallam** [comment]
Hi,

I'm still having the same issue, many products don't show up in the product list however i found the products only when i'm searching.

also i've another issue that when i'm changing the layout, (from grid mode to list mode for example ) many products don't show up.

**Comment by minhcasi** [comment]
@alaaeallam - could you provide the purchase screenshot from https://codecanyon.net/downloads

and send us your config file so that we could help for checking

**Comment by minhcasi** [comment]
sorry i got your conversation from - https://app.intercom.io/a/apps/xro9xnfd/inbox/inbox/2664005/conversations/23296830565

@concuacon - please help for checking

**Comment by alaaeallam** [comment]
[Config.zip](https://github.com/inspireui/support/files/3600609/Config.zip)

HYG

**Comment by alaaeallam** [comment]
Any news?

**Comment by concuacon** [comment]
> Hi,
> 
> I'm still having the same issue, many products don't show up in the product list however i found the products only when i'm searching.
> 
> also i've another issue that when i'm changing the layout, (from grid mode to list mode for example ) many products don't show up.

you config categoryId is wrong, how can get the products show up the home page.The correct id must look like this "R0lGODlhAQABAIAAAAAAAAAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw=="

**Comment by alaaeallam** [comment]
> > Hi,
> > I'm still having the same issue, many products don't show up in the product list however i found the products only when i'm searching.
> > also i've another issue that when i'm changing the layout, (from grid mode to list mode for example ) many products don't show up.
> 
> you config categoryId is wrong, how can get the products show up the home page.The correct id must look like this "R0lGODlhAQABAIAAAAAAAAAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw=="

Hi,

this what i got from graphiql app
please find the attached 
<img width="1197" alt="Screen Shot 2019-09-16 at 11 53 01 AM" src="https://user-images.githubusercontent.com/10725570/64949142-d6077980-d878-11e9-9695-c07d20f795b5.png">

**Comment by alaaeallam** [comment]
[Config.js.zip](https://github.com/inspireui/support/files/3615887/Config.js.zip)
please check after using the graphql client

**Comment by concuacon** [comment]
> [Config.js.zip](https://github.com/inspireui/support/files/3615887/Config.js.zip)
> please check after using the graphql client

@alaaeallam  this work

**Comment by alaaeallam** [comment]
> > [Config.js.zip](https://github.com/inspireui/support/files/3615887/Config.js.zip)
> > please check after using the graphql client
> 
> @alaaeallam this work

yes but still have the same issue that when i'm changing the layout, (from grid mode to list mode for example ) many products don't show up.

**Comment by alaaeallam** [comment]
if there any news ????

**Comment by alaaeallam** [comment]
> > > [Config.js.zip](https://github.com/inspireui/support/files/3615887/Config.js.zip)
> > > please check after using the graphql client
> > 
> > 
> > @alaaeallam this work
> 
> yes but still have the same issue that when i'm changing the layout, (from grid mode to list mode for example ) many products don't show up.

please support

**Comment by concuacon** [comment]
Hi @alaaeallam can u attach screenshot?? In my code it work.
