### ISSUE TITLE
Fluxstore-1.4.3

### ISSUE THREAD

**Issue by anandnathtiwari** [inspireui/support#1024]
I am using Opencart 3.0.3.2

1. My Issue is App not show Tax(Not Calculate Taxes) and in payment time it book order without going to make payment.

Please guide me.

**Comment by minhcasi** [comment]
Hi @anandnathtiwari  - the tax and payment gateway does not support on current release of the Opencart, we will update it on next v1.5 - thank you!

**Comment by anandnathtiwari** [comment]
tentative days to release v1.5

**Comment by anandnathtiwari** [comment]
Any update ?

**Comment by minhcasi** [comment]
Hi, it will be available in 1-2 weeks - thank you!

**Comment by minhcasi** [comment]
please update 1.5 for new payment gateway support - thank you!
