### ISSUE TITLE
[Fluxstore] - while importing flutter existing project

### ISSUE THREAD

**Issue by sunil1509** [inspireui/support#1025]
1. My issue : - while importing flutter existing project

2. Screenshots
![Screenshot_1](https://user-images.githubusercontent.com/29796497/64253298-9ec0d080-cf3a-11e9-8fce-92538057c167.png)
![Screenshot_2](https://user-images.githubusercontent.com/29796497/64253302-a1bbc100-cf3a-11e9-885c-a07b9f8be8fa.png)

3. My screenshot of the purchase product or my comment: 

3. Config files (optional)

**Comment by minhcasi** [comment]
@sunil1509 - could you share your product purchased screenshot ?
