### ISSUE TITLE
CeStore - WebSocket connection failed

### ISSUE THREAD

**Issue by ahmadyousefdev** [inspireui/support#1028]
1. I uploaded the database and changed my config file to

```
// server.js
const dbHost = process.env.DB_HOST || 'localhost';
const dbPort = process.env.DB_PORT || 27017;
const dbName = process.env.DB_NAME || 'delivercom'; // This is the name of the database
const dbUser = process.env.DB_USER || '';
const dbPass = process.env.DB_PASS || '';

// admin.js
apiBaseUrl: 'http://localhost:3001/api/v1',
apiWebSocketUrl: 'ws://localhost:3001',
developerMode: true
```
The products and everything is loaded, but I can't change anything.
I have this error when I access the web app site and admin
```
WebSocket connection to 'ws://localhost:3001/ws/dashboard?token=null' failed:
```

I tried to access the  and I got this: http://localhost:3001 to see if it retrieves the API
```
{"error":true,"message":"No authorization token was found"}
```

what is the problem ?

**Comment by ahmadyousefdev** [comment]
I got this too before the websocket error :

```
GET http://localhost:3001/api/v1/settings? net::ERR_ABORTED 401 (Unauthorized)
```

Can I get some help here please ? I can't continue..

screenshot of my comment in envato: http://ahmadyousef.me/uploads/cestore.png

**Comment by ahmadyousefdev** [comment]
I installed the app too and ran it, after changing

```
"Cezerin": {
    "url": "http://192.168.1.125:3001"
  }
```

it doesn't retrieve anything.

By the way, the [documentation](https://docs.inspireui.com/cestore) is old and doesn't describe the installation properly.

**Comment by minhcasi** [comment]
@minhtruong315 - pls suggest for this issue

**Comment by minhtruong315** [comment]
@ahmadyousefdev you need to add ```developerMode: true``` to config/server.js

**Comment by ahmadyousefdev** [comment]
Hey thanks that solved it !
