### ISSUE TITLE
Fluxstore

### ISSUE THREAD

**Issue by samik9** [inspireui/support#1030]
Hello team, I changed the theme and the  and followed the advices here #941 but I dont know why is not taking me to the success page of the app, only shows the webview after succes.

Thank you for your time

![ezgif-3-d1d4ba0f6e2b](https://user-images.githubusercontent.com/50071744/64404942-314c9700-d043-11e9-8a6f-c27a3858f1be.gif)

**Comment by minhcasi** [comment]
Hi @samik9 - thank you for reporting, we have noted for fixing this UX on next release

**Comment by luisalexhg** [comment]
> Hi @samik9 - thank you for reporting, we have noted for fixing this UX on next release

When will be the next release?, I too have the same issue. Pls fix it
