### ISSUE TITLE
[EvaStore] - horizontal layout hotfix needed for 1.1.2

### ISSUE THREAD

**Issue by nhblock** [inspireui/support#1031]
1. My issue
Same as https://github.com/inspireui/support/issues/968

2. Screenshots

3. My screenshot of the purchase product or my comment: order ID 108146996

3. Config files (optional)

Please send the hotfix for the horizontal layout like issue #968

**Comment by nhblock** [comment]
![EvaStore purchase receipt](https://user-images.githubusercontent.com/7387991/64468261-1bdd7880-d0e8-11e9-867d-92ebfb274213.jpg)

Here is my proof of purchase from July. @minhcasi @concuacon

**Comment by minhcasi** [comment]
Thank you for the detail, we have noted and will update the patching shortly.
@concuacon

**Comment by nhblock** [comment]
Can you send me the patch now like you did for the other issue?

**Comment by minhcasi** [comment]
Hi @nhblock , please help to download the latest 1.1.3 from https://codecanyon.net/downloads - we have just updated this issue
