### ISSUE TITLE
Magento 3rd Level Category Not Visible in Fluxstore

### ISSUE THREAD

**Issue by tjain90** [inspireui/support#1032]
Categories are not available in Menu. For example:

A>B>C

In Fluxstore till B is available but not C level Menu. Even when i click B no products are available.

---------

**Comment by minhcasi** [comment]
@tjain90 - this could be caused by the issue from Magento API issue, we have noted and will look into the issue

Could you help to share the config of your site for further checking as well - thank you!

**Comment by tjain90** [comment]
[common.zip](https://github.com/inspireui/support/files/3603359/common.zip)
Hi,

Please find attached.
