### ISSUE TITLE
PLEASE HELP!!! gradlew.bat exited abnormally

### ISSUE THREAD

**Issue by sunil1509** [inspireui/support#1034]
1. My issue :- (exception)gradlew.bat exited abnormally

2. Screenshots:- 
![Screenshot_2](https://user-images.githubusercontent.com/29796497/64486448-0896ee00-d24b-11e9-8266-3ac878788018.png)

**Comment by minhcasi** [comment]
@sunil1509 - did you pass the guide from https://flutter.dev/docs/get-started/test-drive ?

Also try to check "flutter doctor"
