### ISSUE TITLE
[FLUXSTORE] - How to hide price ?

### ISSUE THREAD

**Issue by MER24** [inspireui/support#1035]
Hi, I bought the application called FluxStore, but only members need to be able to see the product prices on my site. My site serves as B2B. How can we hide product prices in ?

Item Purchase Code:
79f4448e-bb4d-41f9-a641-cc2822c5843d

**Comment by minhcasi** [comment]
Hi, you can edit the product_card_view to hide the price or add a custom feature to check the visibility base on user login https://tppr.me/NJSsp - thank you!

**Comment by MER24** [comment]
Sorry, my coding skills are weak . Can you share code so that the user doesn't see prices without logging in. (I can pay for extra support)
