### ISSUE TITLE
[BuzzApp] -  CeBuilder Crashes

### ISSUE THREAD

**Issue by Ink9** [inspireui/support#1036]
When i try to add a new elements section to the cebuilder it crashes. 
The cebuilder app turns white blank.

And i have attach a screenshot of the terminal once the cebuilder crash.
<img width="903" alt="Screen Shot 2019-09-10 at 1 26 27 PM" src="https://user-images.githubusercontent.com/2674430/64617035-97d00d00-d3d5-11e9-84f3-2b0b248d584c.png">

**Comment by minhcasi** [comment]
Hi, could you help to share the purchased screenshot, thank you!

**Comment by Ink9** [comment]
<img width="860" alt="purchase" src="https://user-images.githubusercontent.com/2674430/64685533-146af600-d47f-11e9-8b77-2c9252504864.png">

**Comment by minhtruong315** [comment]
@Ink9 we will fix this issue, thanks

**Comment by Ink9** [comment]
Why is this thread close? The Problem is not fixed !

**Comment by minhcasi** [comment]
@Ink9 - could you help to download the latest Cebuilder 0.36 will be fixed the issue - https://github.com/inspireui/cebuilder/releases - thank you!

**Comment by Ink9** [comment]
I have download the latest version, and it's still on working.
