### ISSUE TITLE
[EvaStore] - collection containers not loading all products

### ISSUE THREAD

**Issue by nhblock** [inspireui/support#1037]
1. My issue
The homecontainer horizontal layout works great now and shows all the products in the  collections. However, when you press "Show all", only 2 or 3 of the products in that collection are displayed.

Reactotron traces it to some kind of pagination issue with the ListItem or VerticalList component. Is there a way to turn off the need for pagination and just display all the items on load? I don't have that many products.

2. Screenshots
![image](https://user-images.githubusercontent.com/7387991/64630569-03f14780-d3bb-11e9-834d-ea7263d5f7fc.png)

3. My screenshot of the purchase product or my comment:
![image](https://user-images.githubusercontent.com/7387991/64630146-18811000-d3ba-11e9-9bdf-4c9f95cf9140.png)

3. Config files (optional)

**Comment by concuacon** [comment]
Hello @nhblock can you sent to me your source via wetransfer.com ? 
my email tuan@inspireui.com

**Comment by nhblock** [comment]
Sent, thanks Tuan.
