### ISSUE TITLE
FluxStore-woo 1.4.3 fails to build

### ISSUE THREAD

**Issue by cakebread** [inspireui/support#1039]
1. My issue - Can't run FluxStore with fresh install of flutter. Can run default flutter app.

flutter run
Because every version of flutter_test from sdk depends on path 1.6.4 and fstore depends on path 1.6.2, flutter_test from sdk is forbidden.
So, because fstore depends on flutter_test any from sdk, version solving failed.
Running "flutter pub get" in source...
pub get failed (1)

2. Screenshots

3. My screenshot of the purchase product or my comment:
https://gyazo.com/ec194559a24019730e9c6bba814d5919

3. Config files (optional)
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G95, locale en-US)
    • Flutter version 1.9.1+hotfix.2 at /Users/admin/dev/flutter
    • Framework revision 2d2a1ffec9 (4 days ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/admin/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/admin/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Connected device (1 available)
    • iPhone Xʀ • 45B9FF13-935B-44FC-8B77-502DBEDACDD0 • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

**Comment by cakebread** [comment]
If I change pubspec.yaml to:

   path:  1.6.4

I get this error:

flutter run
Launching lib/main.dart on iPhone Xʀ in debug mode...

Compiler message:
../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_widgets-0.1.5/lib/src/visibility_detector/src/visibility_detector_layer.dart:277:18: Error: This expression has type 'void' and can't be used.
    return super.addToScene(builder, layerOffset);
                 ^
Compiler failed on /Users/admin/dev/FluxStore-woo 1.4.3/source/lib/main.dart
Error launching application on iPhone Xʀ.

**Comment by minhcasi** [comment]
Hi, we will update new patching 1.4.5 to fix these issues on today - thank you!

**Comment by minhcasi** [comment]
please download the latest 1.4.4 for fixing new Flutter 1.9

**Comment by John-Matthew9** [comment]
: /D:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_widgets-0.1.5/lib/src/visibility_detector/src/visibility_detector_layer.dart:277:18: Error: This expression has type ’void’ and can’t be used. return super.addToScene(builder, layerOffset); ^ Compiler failed on H:\FLUTERAPPS\flux_app\lib\main.dart What do you suggest? has anyone faced this error and how can we fix this up
