### ISSUE TITLE
[Beonews] UL and OL list, Table do not work in post details

### ISSUE THREAD

**Issue by tohaitrieu** [inspireui/support#104]
Product: Beonews Pro
Purchased Code: 18f0b387-3f2e-4816-8519-4b1cfee21b63

In Post Detail, UL, OL, Table is not working.

My Website: https://www.tohaitrieu.net

Example table in Web: https://www.tohaitrieu.net/us-dollar-index/

Table does not working in app post detail: https://imgur.com/a/XNv1Ocv

In the same URL, UL list does not work: https://imgur.com/a/rC7e82t

Please check and support me.

Thank for the best native WordPress App.

**Comment by levi-beers** [comment]
What I did was change /App/Components/WebView/index.js and I changed line 55 through line 62 where htmlContent is being sanitized and replaced with

`const htmlContent = this.props.html`

What this does is load your web page with no modification to it. If you'd still like to sanitize the HTML, 
 alternatively, you could add the UL and OL tags to allowedTags. Personally, I use so many various tags that it didn't make much sense to put them all in allowedTags so I removed sanitization completely. Hope this helps.
