### ISSUE TITLE
ListApp Google Map API Android Error

### ISSUE THREAD

**Issue by edzofcit** [inspireui/support#1043]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue

Google maps API Error
Experienced the same problem from the closed issue but can't possibly fix with the suggested solution.

https://github.com/inspireui/support/issues/882

Saw another group but can't find where my AndroidManifest.xml is located.
https://github.com/react-native-community/react-native-maps/issues/2752

Would appreciate any help for this.

P.S. BAsically, everythig works fine using expo client but after apk build and manually install it in the phone, have this problem.

![69850763_1122461198141845_1757083455939674112_n (1)](https://user-images.githubusercontent.com/4536279/64696753-d0551100-d4d1-11e9-950e-24d92132bdbc.jpg)

**Comment by dxpsite** [comment]
example for app.json:
` "android": {
      "package": "com.shardik.somelalalal",
      "versionCode": 8,
      "googleServicesFile": "./release/google-services.json",
      "config": {
        "googleMaps": {
          "apiKey": "AIza*****************************rjBVwT4"
        }
      }
    },`

**Comment by edzofcit** [comment]
> HI. The error was displayed. API Key not found. Have you got an api key?

Yes, configured it via app.json

  "android": {
    "package": "com.listapp.name",
    "versionCode": 6,
    "googleServicesFile": "./release/google-services.json",
    
      "config": { "googleMaps": { "apiKey": "AIzaSyDUWVmYEhmkIPGUO7JE4UWj97*******" } }
    }
}

**Comment by thangvo9x** [comment]
the api Key in your android app in AndroidManifest 
follow steps 
https://medium.com/@samil.mehdiyev/integrating-google-maps-into-react-native-app-on-android-40c984c0e4f2
