### ISSUE TITLE
[Fluxstore] -  getNonce, 404 while try to create new user via Email

### ISSUE THREAD

**Issue by Zeeshan0201** [inspireui/support#1044]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue

2. Screenshots

3. My screenshot of the purchase product or my comment:

3. Config files (optional)

**Comment by minhtruong315** [comment]
@Zeeshan0201 did you install mstore checkout plugin? https://docs.inspireui.com/fluxstore/woocommerce-setup/

**Comment by Zeeshan0201** [comment]
@minhtruong315 can we have any docs available for how to setup sign up/ log in to customization in Fluxstore?

**Comment by Zeeshan0201** [comment]
@minhtruong315 yes I installed  mstore checkout plugin, still getting  getNonce, 404

**Comment by Zeeshan0201** [comment]
@minhtruong315 
not able to find **JSON API**: allows to active the API config for MStoreUser to support registration features. plugin and it's  when I use [JSON API User](https://wordpress.org/plugins/json-api-user/) getting **"status":"error","error":"Unknown controller 'mstore_user'** in nonce response..

![Screenshot from 2019-09-13 17-25-23](https://user-images.githubusercontent.com/45591301/64860681-7d9f6480-d64b-11e9-8333-44b8b4783861.png)

**Comment by minhtruong315** [comment]
@Zeeshan0201 send me your website and admin account via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/1044

**Comment by magedgamaleldin** [comment]
@minhtruong315  would you please share your solution, I'm facing the same issue.

**Comment by Zeeshan0201** [comment]
@magedgamaleldin did you install mstore checkout plugin?

**Comment by Zeeshan0201** [comment]
I already solved this issue..

**Comment by magedgamaleldin** [comment]
Yes

**Comment by Zeeshan0201** [comment]
and can guide you step by step @magedgamaleldin

**Comment by magedgamaleldin** [comment]
Great Thanks much :)

**Comment by Zeeshan0201** [comment]
@magedgamaleldin  are you facing this error? 
 **"status":"error","error":"Unknown controller 'mstore_user' in nonce response..**

**Comment by magedgamaleldin** [comment]
yes

**Comment by magedgamaleldin** [comment]
getNonce, 404 while try to create new user

**Comment by Zeeshan0201** [comment]
@magedgamaleldin wait  I am sending all details in 5 minutes..

**Comment by magedgamaleldin** [comment]
Thanks much Zeeshan :)

**Comment by Zeeshan0201** [comment]
@magedgamaleldin whenever you are using  this API for nonce 
> "$url/api/get_nonce/?controller=mstore_user&method=$method&$isSecure
just replace  **controller=mstore_user** with **controller=user.** and make sure you are suing these latest plugins...
![Screenshot from 2019-09-17 16-55-55](https://user-images.githubusercontent.com/45591301/65037784-09770080-d96c-11e9-80b8-812dd82783fb.png)

**Comment by magedgamaleldin** [comment]
user Or User ?

**Comment by Zeeshan0201** [comment]
![Screenshot from 2019-09-17 16-57-16](https://user-images.githubusercontent.com/45591301/65037858-37f4db80-d96c-11e9-8739-c079dcc44bb2.png)
@magedgamaleldin And kindly active User in setings>Json API

**Comment by Zeeshan0201** [comment]
@magedgamaleldin user like this:- 

> nonce can be created by calling if you are registering user. http://localhost/api/get_nonce/?controller=user&method=register

**Comment by Zeeshan0201** [comment]
@magedgamaleldin everything fine or getting any trouble?

**Comment by magedgamaleldin** [comment]
Frankly, I just tried the same but facing the same issue, I will clean the code and deploy once again,

**Comment by Zeeshan0201** [comment]
@magedgamaleldin please send the snap of error...

**Comment by magedgamaleldin** [comment]
Exception: [error getNonce, 404] same everything

**Comment by Zeeshan0201** [comment]
```
Future getNonce({method = 'register'}) async {
    try {
      http.Response response = await http.get(
          "$url/api/get_nonce/?controller=user&method=$method&$isSecure");
      if (response.statusCode == 200) {
        return convert.jsonDecode(response.body)['nonce'];
      } else {
        throw Exception(['error getNonce', response.statusCode]);
      }
    } catch (e) {
      throw e;
    }
  }
```
check everything once, it's working fine in all of my 5 projects @magedgamaleldin

**Comment by Coinizy1** [comment]
I am getting same error can you help? I am getting 409 not 404
Exception: [error getNonce, 409]
