### ISSUE TITLE
[MSstore] - chechout

### ISSUE THREAD

**Issue by leghost** [inspireui/support#1046]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue

1) When i whant to confirm the order , the confirm order button just show "Loading" and nothing happen.
i tryed the 2 check out solutions present here 
https://docs.inspireui.com/mstore/questions/#404-error-page-when-process-the-payment-
but it still do the same thing.

2) the review take time to be submited and to prompt a message. And after the admin has approved the review, it does not appear ont the app.

2. Screenshots
![WhatsApp Image 2019-09-11 at 19 59 09 (1)](https://user-images.githubusercontent.com/47028114/64722535-f0cf9c00-d4ce-11e9-8d9b-74c7d24da011.jpeg)

![WhatsApp Image 2019-09-11 at 19 59 10](https://user-images.githubusercontent.com/47028114/64722525-eca37e80-d4ce-11e9-8a6c-f7edde3cdb83.jpeg)

3. My screenshot of the purchase product or my comment:
![image](https://user-images.githubusercontent.com/47028114/64722782-70f60180-d4cf-11e9-8804-876adafaf155.png)

3. Config files (optional)

**Comment by concuacon** [comment]
Hi @leghost this hot fix, download and copy to folder Detail, follow path: src/containers/Detail/
[ReviewTab.js.zip](https://github.com/inspireui/support/files/3620681/ReviewTab.js.zip)

**Comment by leghost** [comment]
@concuacon ok thanks

**Comment by leghost** [comment]
@minhcasi hi. no update since  days? please , i can't solve the checkout issue.

**Comment by concuacon** [comment]
@leghost you can try run: rm -rf node_modules/ && yarn && cd ios/ && rm -rf Pods/ && rm -rf Podfile.lock && cd ../ && react-native run-ios

**Comment by leghost** [comment]
@concuacon  please this works on windows os?

**Comment by leghost** [comment]
i'm working on Windows Os and the "rm" is not recognised

**Comment by leghost** [comment]
It's ok i solved the issue. I created the api with only read property then the App war unable to write any data on checkout. thanks
