### ISSUE TITLE
[fluxstore - pro] - Paypal and Stripe pay the opened webview show URL not found on the server 

### ISSUE THREAD

**Issue by MarcHe124** [inspireui/support#1048]
1. My issue

We try to use paypal and stripe pay from app (we already get them working on website changcheng.ca for same server), then the opened webview redirects to some url that cannot be found on the server. Is the payment feature not done yet on opencart? or is the url from a new version of mstore api extension or sth?

The redirected URL: http://changcheng.ca/mstore-checkout/?order=eyJwYXltZW50X21ldGhvZCI6InBwX2V4cHJlc3MiLCJwYXltZW50X21ldGhvZF90aXRsZSI6IlBheVBhbCBFeHByZXNzIENoZWNrb3V0Iiwic2V0X3BhaWQiOnRydWUsImJpbGxpbmciOnsiZmlyc3RfbmFtZSI6InRvbSIsImxhc3RfbmFtZSI6InRvbSIsImFkZHJlc3NfMSI6IjI0NTEgRWFzdCBNYWxsIiwiYWRkcmVzc18yIjoiIiwiY2l0eSI6IkJyaXRpc2ggQ29sdW1iaWEiLCJzdGF0ZSI6IkdyZWF0ZXIgVmFuY291dmVyIiwiY291bnRyeSI6IkNBIiwiZW1haWwiOiJ0ZXN0QHFxcS5jb20iLCJwaG9uZSI6IjEyMzQ1Njc4IiwicG9zdGNvZGUiOiJWNlQgMVo0In0sInNoaXBwaW5nIjp7ImZpcnN0X25hbWUiOiJ0b20iLCJsYXN0X25hbWUiOiJ0b20iLCJhZGRyZXNzXzEiOiIyNDUxIEVhc3QgTWFsbCIsImFkZHJlc3NfMiI6IiIsImNpdHkiOiJCcml0aXNoIENvbHVtYmlhIiwic3RhdGUiOiJHcmVhdGVyIFZhbmNvdXZlciIsImNvdW50cnkiOiJDQSIsImVtYWlsIjoidGVzdEBxcXEuY29tIiwicGhvbmUiOiIxMjM0NTY3OCIsInBvc3Rjb2RlIjoiVjZUIDFaNCJ9LCJsaW5lX2l0ZW1zIjpbeyJwcm9kdWN0X2lkIjo1MCwicXVhbnRpdHkiOjF9XSwiY3VzdG9tZXJfaWQiOjYsInNoaXBwaW5nX2xpbmVzIjpbeyJtZXRob2RfaWQiOiJmbGF0X3JhdGUiLCJtZXRob2RfdGl0bGUiOiJGbGF0IFJhdGUifV0sInRva2VuIjoiIn0=

2. Screenshots
![image](https://user-images.githubusercontent.com/12852794/64755866-73615700-d4e1-11e9-9887-e57dcb7b20d4.png)

3. My screenshot of the purchase product or my comment:
https://user-images.githubusercontent.com/12852794/62389502-d213d800-b514-11e9-8123-e07e2333c2fc.png
![image](https://user-images.githubusercontent.com/12852794/64755930-b4f20200-d4e1-11e9-9276-993148e970d5.png)

**Comment by minhtruong315** [comment]
@MarcHe124 pls send me config.dart and connfig.json file via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/1048

**Comment by MarcHe124** [comment]
@minhtruong315 hi, has it gotten resolved?

**Comment by minhtruong315** [comment]
You haven't sent me config file yet

**Comment by MarcHe124** [comment]
I sent to you from arthurma124@gmail.com to truong@inspireui.com, please double check about two days ago.

**Comment by minhtruong315** [comment]
@MarcHe124 can you send me admin account to login to your website?

**Comment by minhtruong315** [comment]
@MarcHe124 Did you do this? https://github.com/inspireui/support/issues/941#issuecomment-522298815

**Comment by MarcHe124** [comment]
I will try it now. I saw first solution mentioned a plugin mstore-checkout. Is it another plugin for opencart?

**Comment by minhtruong315** [comment]
No. it is for woo commerce

**Comment by MarcHe124** [comment]
we are using opencart3 man, so what solution do you suggest?

**Comment by minhtruong315** [comment]
we already developed payment webview for opencart. it's available next release
