### ISSUE TITLE
[mstore-pro] - Facebook Account Kit is Deprecated 

### ISSUE THREAD

**Issue by harry503** [inspireui/support#1049]
1. Facebook Account Kit is Deprecated
No longer can you Login by SMS. Please remove or change method

2. Screenshots
![Screen Shot 2019-09-12 at 15 49 03](https://user-images.githubusercontent.com/35995317/64769152-fe3f6180-d574-11e9-8e4c-59944a9730a6.png)

**Comment by minhcasi** [comment]
fixed, new 3.9.7 will be available on next week - thanks
