### ISSUE TITLE
[Mstore Multi Vendor] Sign up not working in MStore Multi Vendor - Complete React Native template for WooCommerce

### ISSUE THREAD

**Issue by Sandeep6699** [inspireui/support#105]
**Required Info (please complete the following information):**
 - Product: MStore Multi Vendor - Complete React Native template for WooCommerce
 - Your Purchased Code: 2650646b-3b3d-49b0-a603-ee7dfce3a510
Purchase Date:
2018-10-09 10:18:09 UTC

Username : sandeep6699

(we may not reply if you are not our customer)

**Describe the bug**

I have got success to make a app with your source code. I have installed apk in my android phone. 

While sign up i am getting error " Unknown controller mstrore_user "

**Screenshots**
![1544870824221](https://user-images.githubusercontent.com/45586706/50042389-23578000-0088-11e9-809a-4c3ca988e514.JPEG)

Screenshot is attached. 

**Additional context**

You can download the app from here

**Comment by minhcasi** [comment]
Hi, there is missing this config from the Wordpress, please help to refer to https://docs.mstore.io/basic-app-setting#enable-the-rest-api-controller

We know this is also missing from the document guide, we will update it shortly - thank you!

**Comment by thangvo9x** [comment]
Hi. let us know if it works. Hearing from you. Thanks

**Comment by Sandeep6699** [comment]
Yes 

Thanks a lot !!

Sign up is working now.

**Comment by ZamanGoraya** [comment]
can anyone help me ... to give the mstore checkout plugin witch work as mstoreuser api correctly
...?
