### ISSUE TITLE
[my-product] - mstore opencart

### ISSUE THREAD

**Issue by mikebanson** [inspireui/support#1051]
After installation most products show out of stock. i was asked to send the config file.
[Config.zip](https://github.com/inspireui/support/files/3605622/Config.zip)

**Comment by minhtruong315** [comment]
@mikebanson can you send me AppConfig.json file?

**Comment by mikebanson** [comment]
[AppConfig.zip](https://github.com/inspireui/support/files/3609934/AppConfig.zip)

**Comment by minhtruong315** [comment]
@mikebanson i checked your data, all products return "stock_status":"Out Of Stock",
you need to change stock status in opencart admin site.
<img width="1148" alt="Screen Shot 2019-09-14 at 09 48 03" src="https://user-images.githubusercontent.com/10402500/64902626-ea127600-d6d4-11e9-85b8-cf8a2a02bd7c.png">
