### ISSUE TITLE
[Mstore-Pro 3.9.5] - Android App not working 

### ISSUE THREAD

**Issue by myothura** [inspireui/support#1055]
Hello , Sir  

I would like to inform you. Your Last update: 09/09/2019  reactive native android is not running in react-native run-android ( or ) Via Android Studio. Please kindly fix for us.

Reactive native Error 

https://i.ibb.co/jk7JF9k/Screen-Shot-2019-09-13-at-4-42-00-AM.png

Android studio error 

https://i.ibb.co/4J1k3KQ/Screen-Shot-2019-09-13-at-4-42-50-AM.png

If you not clear i will upload for you with video file 

https://www.youtube.com/watch?v=hkCIZx1YuXk Video file 

Thanks you.

**Comment by concuacon** [comment]
@myothura please check your path android sdk
![Screen-Shot-2019-09-13-at-4-42-00-AM](https://user-images.githubusercontent.com/11958061/64845836-5a69ba80-d635-11e9-95ff-2397f86a0905.png)
and run:
rm -rf node_modules/ && yarn && cd  android/ && ./gradlew clean && cd ../ && react-native run-android
