### ISSUE TITLE
[my-product] - ListApp 

### ISSUE THREAD

**Issue by alimajee** [inspireui/support#1056]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue : I don’t want user to add listing from app . There is + sign at the bottom (middle) of the app. How I can disable that

2. Screenshots

3. My screenshot of the purchase product or my comment:

3. Config files (optional)

**Comment by minhcasi** [comment]
Hi, you can remove these lines from the navigation/index.js file - https://tppr.me/ti6FE
