### ISSUE TITLE
[fluxstore] - shipping method problem - I CAN EDITE

### ISSUE THREAD

**Issue by AlaaKriedy** [inspireui/support#1057]
Hello ,
when I edited my shipping method in WooCommerce , didn't have any change in my app ,
please how can I changed by zone ID for shipping method

**Comment by minhcasi** [comment]
@AlaaKriedy - the current release only support for first zone id, it's not supported for multi-zone so far - you can customize to support multi-zone or complex condition to show the shipping - thank you!

**Comment by luisalexhg** [comment]
> @AlaaKriedy - the current release only support for first zone id, it's not supported for multi-zone so far - you can customize to support multi-zone or complex condition to show the shipping - thank you!

Do you plan to solve this in a later version?, I have the same Issue, always show all shipping methods, I only have activated two, and on the app show three..

**Comment by minhcasi** [comment]
@minhtruong315  - shipping issue

**Comment by minhtruong315** [comment]
@luisalexhg you can try to edit function getShippingMethods in lib/services/woo_commerce.dart
```
@override
  Future<List<ShippingMethod>> getShippingMethods(
      {Address address, String token}) async {
    try {
      var response = await wcApi.getAsync("shipping/zones/1/methods");
      List<ShippingMethod> list = [];
      for (var item in response) {
        list.add(ShippingMethod.fromJson(item));
      }
      return list;
    } catch (e) {
      throw e;
    }
  }
```
you can change to your zone_id

**Comment by luisalexhg** [comment]
Hi @minhtruong315 
I tried but I got this error: https://bit.ly/2mkuzVW
My Code: https://bit.ly/2mpfcM4
My zone id: https://bit.ly/2koI8Dc

**Comment by minhtruong315** [comment]
@luisalexhg can you send me info to login to admin website via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/1057

**Comment by luisalexhg** [comment]
I already sent you access to the website settings. thanks

**Comment by minhtruong315** [comment]
@luisalexhg we will fix this. it's available in next release

**Comment by Senior-Gamal** [comment]
any update about this problem and if you active more shipping method
