### ISSUE TITLE
[BeoNews] AdMob banner overlaps with comments section on BeoNews

### ISSUE THREAD

**Issue by talwinder1508** [inspireui/support#106]
**Describe the bug**
AdMob banner overlaps with the comments section on BeoNews Post Details page

<img width="802" alt="screen shot 2018-12-15 at 10 58 32 am" src="https://user-images.githubusercontent.com/14082839/50046455-7b768e00-0058-11e9-8e22-836623870f48.png">

**Comment by minhcasi** [comment]
Hi thank you for the feedback, we will have a check and update it next version

**Comment by minhcasi** [comment]
Fixed on next version release - thank you!
