### ISSUE TITLE
[fluxstore] - mStoreUser isn't available in Json API setting

### ISSUE THREAD

**Issue by AmjadKhan2k18** [inspireui/support#1060]
1. My issue
 I am integrating wordpress woo with fluxture 1.4.3 when i followed all steps in documentation but when i get into enable enable the MStoreUser i couldn't find it in setting JSON-API settings you can see screenshot
2. Screenshots
![Screenshot 2019-09-14 at 12 13 23 AM](https://user-images.githubusercontent.com/44894621/64894044-253f8580-d692-11e9-8b73-c36762dd260e.png)

3. My screenshot of the purchase product or my comment:
doing it for a client as freelancer
3. Config files (optional)
i only updated this MAP 
const serverConfig = {
  "type": "woo",
  "url": "http://web.net",
  "consumerKey": "ck",
  "consumerSecret": "cs",
  // "blog": "http://fluxstore.inspireui.com",
  // "forgetPassword": "http://demo.mstore.io/wp-login.php?action=lostpassword"
};

**Comment by minhcasi** [comment]
@AmjadKhan2k18 - could you take screenshot of the purchased screenshot from - https://codecanyon.net/downloads and make sure using the latest 1.4.4 - thank you!

**Comment by AmjadKhan2k18** [comment]
> @AmjadKhan2k18 - could you take screenshot of the purchased screenshot from - https://codecanyon.net/downloads and make sure using the latest 1.4.4 - thank you!
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/c5a18223816825ebf6c0fec648742882ecbb6a7b/68747470733a2f2f6173736574732e73686f7066726f6e742e656e7661746f2d7374617469632e636f6d2f696d616765732f6d6574612f6c6f676f732f636f646563616e796f6e2e706e67"><img alt="" height="14" src="https://camo.githubusercontent.com/c75d968dba11187d74e09644791494a4418ce2d8/68747470733a2f2f6173736574732e73686f7066726f6e742e656e7661746f2d7374617469632e636f6d2f69636f6e732f636f646563616e796f6e2e6e65742f66617669636f6e2e69636f"> CodeCanyon**[Buy Plugins & Code from CodeCanyon](https://codecanyon.net/)**Discover 30,079 Plugins, Code and Script for Bootstrap, Javascript, PHP, Wordpress, HTML5 and more. Save time, buy Code on CodeCanyon!

Thanks for response i asked client to send me screenshot and i am using 1.4.3 which he sent me

**Comment by AmjadKhan2k18** [comment]
> @AmjadKhan2k18 - could you take screenshot of the purchased screenshot from - https://codecanyon.net/downloads and make sure using the latest 1.4.4 - thank you!
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/c5a18223816825ebf6c0fec648742882ecbb6a7b/68747470733a2f2f6173736574732e73686f7066726f6e742e656e7661746f2d7374617469632e636f6d2f696d616765732f6d6574612f6c6f676f732f636f646563616e796f6e2e706e67"><img alt="" height="14" src="https://camo.githubusercontent.com/c75d968dba11187d74e09644791494a4418ce2d8/68747470733a2f2f6173736574732e73686f7066726f6e742e656e7661746f2d7374617469632e636f6d2f69636f6e732f636f646563616e796f6e2e6e65742f66617669636f6e2e69636f"> CodeCanyon**[Buy Plugins & Code from CodeCanyon](https://codecanyon.net/)**Discover 30,079 Plugins, Code and Script for Bootstrap, Javascript, PHP, Wordpress, HTML5 and more. Save time, buy Code on CodeCanyon!

i asked him screenshot of purchase but he send me license file is it enough ?

![Screenshot 2019-09-14 at 4 45 53 PM](https://user-images.githubusercontent.com/44894621/64907713-8ce7e600-d70f-11e9-8e71-e87efcb9d9f2.png)

**Comment by AmjadKhan2k18** [comment]
Hello Sir i got screenshot from client

![ff](https://user-images.githubusercontent.com/44894621/64919673-00006380-d7c7-11e9-9adb-894923933e1b.jpg)

**Comment by AmjadKhan2k18** [comment]
i just got latest version from client and now this issue is solved by uploading plugins that come with project Thanks
