### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by emmyprofessional** [inspireui/support#1061]
I bought fluxestore pro and I have no any experience about this product. I need technical support to help me create the application and upload it to app store and google play for $.

**Comment by jssdevindia** [comment]
Visit https://jssdev.wordpress.com/

**Comment by emmyprofessional** [comment]
Hello JSS ,
Thanks for your reply
Can you help me in this app 
https://codecanyon.net/item/fluxstore-the-universal-woocommerce-magento-opencart-mobile-app-by-flutter-framework/24020929
??

**Comment by jssdevindia** [comment]
Yes please visit https://jssdev.wordpress.com and click on live chat for project quote.
