### ISSUE TITLE
[mstore-multivendor] - TypeError

### ISSUE THREAD

**Issue by RajParab** [inspireui/support#1062]
> - I was trying to add the firebase chat but the app is crashing after the splash screen
> - old data is also not working

---------

1.

2. Screenshots
![image](https://user-images.githubusercontent.com/47249678/64912269-6f843d80-d74a-11e9-981d-9c9b84ee50b6.png)

3. 
![image](https://user-images.githubusercontent.com/47249678/64912288-a9554400-d74a-11e9-80cb-662e96650af6.png)

3. 
[Config.zip](https://github.com/inspireui/support/files/3613026/Config.zip)

**Comment by minhcasi** [comment]
noted with checking, thank you!

**Comment by thangvo9x** [comment]
Please share your domain. Its mean the AppConfig.js file. Thanks
