### ISSUE TITLE
[my-product] - FluxNews

### ISSUE THREAD

**Issue by danasugu** [inspireui/support#1064]
Hi!
I am not getting the posts listed. 
![screenshot](https://user-images.githubusercontent.com/12096815/64917932-71c4b700-d79f-11e9-8c48-14933f68a075.png)
![screenshot (1)](https://user-images.githubusercontent.com/12096815/64917933-71c4b700-d79f-11e9-9d7c-74a2c1f34fb4.png)
![Screenshot_1568530447](https://user-images.githubusercontent.com/12096815/64917979-2068f780-d7a0-11e9-87c3-61fadcdf2ad7.png)

**Comment by danasugu** [comment]
Item Purchase Code:
516cdeb7-289e-4bb2-8b7b-113ee65484c7

**Comment by minhcasi** [comment]
@danasugu could you help to share the config files from the project - thank you!

**Comment by danasugu** [comment]
Hi! 
Thanks!
Download link [https://wetransfer.com/downloads/607881f3b41991c08f0074464f06d7b520190916070107/b7b824](url)

**Comment by danasugu** [comment]
@minhtruong315 Would you please check the attached files? What is the problem?

**Comment by danasugu** [comment]
@minhcasi Hi! Thanks for trying to solve my problem bur your attempts are futile. 
@dttrung26 Hi! Could you check the files attached? Where is the problem?

**Comment by minhcasi** [comment]
Hi, sorry for the late response as my guy was off in a few days

Please extract and override the lib/models to fix the issue - https://www.dropbox.com/s/6q34i7ht671249m/blog_news.dart.zip?dl=0

Also, please help to update your rating on our product, thank you!

**Comment by danasugu** [comment]
Thanks, it works now! I updated the rating too. Maybe you could release Version: 1.0.2

**Comment by minhcasi** [comment]
Yes sure, we have new 1.1 coming with more powerful features, Admob, new layouts...

Thank you for your updating the rating!
