### ISSUE TITLE
FluxStore

### ISSUE THREAD

**Issue by sunil1509** [inspireui/support#1065]
Hi All,
I am not getting remaining category. I have more than 2 categories but I am getting only two.
I added all three plugins and passed correct URL, CK and CS.
Please Help!!!
![Capture1](https://user-images.githubusercontent.com/29796497/64921273-deab7180-d7de-11e9-8d7e-50fafd92bd34.JPG)

**Comment by minhcasi** [comment]
Hi, thank you for your contact

1. please provide the purchased screenshot from https://codecanyon.net/downloads
2. And sharing your config file so that we could help for checking (from the common/config.json and config.dart)

**Comment by sunil1509** [comment]
Mr. minhcasi please check your mail I shared mentioned requirements

**Comment by sunil1509** [comment]
Please help me in above mentioned issue.

**Comment by minhcasi** [comment]
Hi @sunil1509 - could i know your email please, as i could not see your name from by inbox - sorry for this inconvenience.

Also, share your config files attache with the email so that we could help for investigating - thank you!

**Comment by sunil1509** [comment]
Hi,
Mr. minhcasi please check your mail I shared mentioned requirements.
My email id:- **sunilkumar63930@gmail.com** and I attached **config file** even **item purchased code**.

**Comment by minhcasi** [comment]
Thank you, verified ok

@minhtruong315  - pls check this config
[common-1.zip](https://github.com/inspireui/support/files/3635726/common-1.zip)

**Comment by sunil1509** [comment]
Ok sir I will check it
Thanks sir

**Comment by minhcasi** [comment]
@sunil1509 - sorry, i mean forward this config for the team to check it, they will reply you when it's ready - thanks

**Comment by sunil1509** [comment]
ok thank you sir

**Comment by sunil1509** [comment]
Hi,
Mr. minhcasi can you help me ?
Why I am getting null response while  login or registration?
and while registration exception coming **unknow controller 'mstore_user'**

**Comment by sunil1509** [comment]
@minhcasi Sir I didn't get any update please check it and let me know when it will be ready ?

**Comment by minhcasi** [comment]
@sunil1509 - pls update latest 1.5 as we have fix some bug relate to this category issues as well

Also replace the mstore-checkout with this plugin - https://wordpress.org/plugins/mstore-api/

**Comment by sunil1509** [comment]
@minhcasi 
Hi,
I replaced mstore-checkout with latest plugin as per you mentioned but still I am getting error. 

When I uploading Mstore API plugin then it is asking to update.

Note:-

1) **Before update Mstore API plugin version 1.1.5** and in this version **I am not getting some latest options like get_points, get_currentUsers_info** but **after update Mstore API plugin changed into version 1.2.0 and in this version I am getting options of get_points, get_currentUsers_info** but that's also showing error.

2) I am **sharing some screenshots** please kindly check it and let me know what's the issue?

**_Mstore API version 1.1.5 (before update)_**

![Mstore_API_before_update_version](https://user-images.githubusercontent.com/29796497/65570277-3c2d8400-df7e-11e9-8bed-4fa610f551f6.png)

**_Mstore API version 1.1.5 options showing:-_**

![options_coming_in_Mstore_API_1 1 5_update](https://user-images.githubusercontent.com/29796497/65570350-726b0380-df7e-11e9-915b-3c54c89b2bef.png)

**_Mstore API version 1.2.0 (after update):-_**

![Mstore_API_after_update_version](https://user-images.githubusercontent.com/29796497/65570383-8dd60e80-df7e-11e9-8ee9-5e0db7c34f5e.png)

**_Mstore API version 1.2.0 options showing:-_**

![options_coming_in_Mstore_API_1 2 0_update](https://user-images.githubusercontent.com/29796497/65570427-afcf9100-df7e-11e9-9ac0-b3068d7fa0d5.png)


**_Tired get_points option and it's in HTTPS but showing error_** 

![tired_get_points_option_and_its_https_but_showing_error](https://user-images.githubusercontent.com/29796497/65570588-3edca900-df7f-11e9-919e-48526433f572.png)


**_Another one:-_**

![tired_get_points_option_but_showing_error](https://user-images.githubusercontent.com/29796497/65570609-5451d300-df7f-11e9-82f5-8b279ad6e424.png)

**Comment by sunil1509** [comment]
@minhcasi Mr.Minhcasi please update something about my issue I am still facing problem.

**Comment by minhtruong315** [comment]
@sunil1509 i check your config. i see it show many categories, what is wrong?
![Simulator Screen Shot - iPhone 11 Pro - 2019-10-02 at 16 39 02](https://user-images.githubusercontent.com/10402500/66034307-35c97a00-e533-11e9-92b9-721573a221cd.png)
