### ISSUE TITLE
[Fluxstore] - I have this message when I signup by facebook account or by sms 

### ISSUE THREAD

**Issue by AlaaKriedy** [inspireui/support#1066]
I have this message when I signup by facebook account or by sms  

1- by facebook account : 
![63961457-e90d0200-caa1-11e9-938e-736ca122cfdf](https://user-images.githubusercontent.com/53983179/64923930-ae1c0580-d7e7-11e9-93a9-3689a8503631.jpg)

2- by SMS 
![Screenshot_20190915-182919](https://user-images.githubusercontent.com/53983179/64924009-96914c80-d7e8-11e9-88ee-7ecb4baf8cb4.png)

I changed facebook ID and every things 

please help me I'll wait you.

**Comment by minhcasi** [comment]
pls try to add the keyhash from your facebook developer - https://tppr.me/6cFAe

**Comment by AlaaKriedy** [comment]
I'm Added but I have same Problem

**Comment by minhcasi** [comment]
HI, this could cause by recent notice from Facebook that they will not support for new Account kit app - https://developers.facebook.com/docs/accountkit/

We've noted as an improvement to replace this feature soon, thank you!

**Comment by minhcasi** [comment]
Updated new SMS Firebase login v1.5.1
