### ISSUE TITLE
[Mstore Pro 3.9.5  ] - itune connect ITMS-90809: Deprecated API Usage

### ISSUE THREAD

**Issue by myothura** [inspireui/support#1067]
Hello ,  The ios app is not accept because of this error . Do you have any idea to fix it ? 
Dear Developer,

We identified one or more issues with a recent delivery for your app, "High Cultured" 1.0 (1). Your delivery was successful, but you may wish to correct the following issues in your next delivery:

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to App Store Connect.

Best regards,

The App Store Team

https://i.ibb.co/mXyLvbr/Screen-Shot-2019-09-16-at-9-12-00-AM.png

**Comment by minhcasi** [comment]
There are some UIWebview are using from these library - FBSDKCoreKit, FirebaseAuth, GoogleMaps, Bolts that cause the warning, but this warning will not impact to your delivery and Appstore still approve it. We will keep an eye to update on these libary when it is release new version - thank you!
