### ISSUE TITLE
[listapp] - Create tag or listing type listing

### ISSUE THREAD

**Issue by mhar92** [inspireui/support#1068]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue
- From this app I manage to show only categories id that I want, but instead showing all the list in that category can you help me to modified it to show all the tags in the category and after user click the tag then all the list in the tag will show up. I use template MyListing
2. Screenshots
![image](https://user-images.githubusercontent.com/32009087/64958194-1be83000-d8c1-11e9-94db-b1a21ae91acb.png)
![image](https://user-images.githubusercontent.com/32009087/64958532-00315980-d8c2-11e9-9056-a61ab5efbe5f.png)
![image](https://user-images.githubusercontent.com/32009087/64958567-12ab9300-d8c2-11e9-9654-5ea49206ea00.png)

3. My screenshot of the purchase product or my comment:
![image](https://user-images.githubusercontent.com/32009087/64958273-4c2fce80-d8c1-11e9-9c54-bb1dc39f4d72.png)

3. Config files (optional)

**Comment by mhar92** [comment]
One more question. I cannot login, I already setup the .htaccess file and when login the error below is shown :
![image](https://user-images.githubusercontent.com/32009087/65002933-b0d24400-d928-11e9-8bc1-f3272a05220e.png)
But when I try using wrong password it seem the connection know the password is wrong you can see image below.
![image](https://user-images.githubusercontent.com/32009087/65002958-d3645d00-d928-11e9-8080-b692dcce7099.png)

Please advise.

**Comment by mhar92** [comment]
> One more question. I cannot login, I already setup the .htaccess file and when login the error below is shown :
> ![image](https://user-images.githubusercontent.com/32009087/65002933-b0d24400-d928-11e9-8bc1-f3272a05220e.png)
> But when I try using wrong password it seem the connection know the password is wrong you can see image below.
> ![image](https://user-images.githubusercontent.com/32009087/65002958-d3645d00-d928-11e9-8080-b692dcce7099.png)
> 
> Please advise.



> One more question. I cannot login, I already setup the .htaccess file and when login the error below is shown :
> ![image](https://user-images.githubusercontent.com/32009087/65002933-b0d24400-d928-11e9-8bc1-f3272a05220e.png)
> But when I try using wrong password it seem the connection know the password is wrong you can see image below.
> ![image](https://user-images.githubusercontent.com/32009087/65002958-d3645d00-d928-11e9-8080-b692dcce7099.png)
> 
> Please advise.

I already solve this by changing userinfo.user.id to userinfo.id. Please advise my first question.

**Comment by thangvo9x** [comment]
Ah huh. I see your problem. But this is out of scope from our supporting. Hope you see.

**Comment by mhar92** [comment]
What do you mean out of scope? Now I get this error whenever I click map icon below.
Please advise. 
![Screenshot_20190919-164418_Expo 1](https://user-images.githubusercontent.com/32009087/65228593-54744d80-dafd-11e9-899b-139abc2794e0.jpg)

**Comment by minhcasi** [comment]
@mhar92  - could you zip your current source and send to support@inspireui.com - we will assign other guy support for this issue - thank you!

@concuacon - please help for assist

**Comment by mhar92** [comment]
> @mhar92 - could you zip your current source and send to [support@inspireui.com](mailto:support@inspireui.com) - we will assign other guy support for this issue - thank you!
> 
> @concuacon - please help for assist

I already send using email hariz92utm@gmail.com
Please take a look. Thanks for your support.

**Comment by mhar92** [comment]
Any update on this?

**Comment by concuacon** [comment]
@mhar92 i'm checking this issue,

**Comment by mhar92** [comment]
Hi can you tell me which file you made changes?
Thanks.

**Comment by concuacon** [comment]
Hi @mhar92 i change file in path: componets/CarouselListing/index.js

**Comment by concuacon** [comment]
You can use image as same we do or you use react-native-vector-icons to add new icon. If not show please check your path to image..

**Comment by mhar92** [comment]
Yes I create my new icon and the path is correct.
On the Common\Image.js i create path :     iconEmail: require('@images/detail/icon-email.png'),
On Container\PostDetail\ListingDetail.js i create <Image style={styles.imageIcon} source={Images.icons.iconEmail} />

but when I replace with other icon it show my icon will become blank.
You can refer from previous file that I send through email.

**Comment by mhar92** [comment]
any update? Are you currently look on this issue?

**Comment by mhar92** [comment]
still no update?

**Comment by minhcasi** [comment]
@mhar92 - sorry for the late response, we will update you on today - thank you!

@concuacon

**Comment by mhar92** [comment]
still waiting...

**Comment by RaptorHck** [comment]
me too..  I have any issue in component news

**Comment by mhar92** [comment]
its been 2 week but still no answer from my last question.

**Comment by thangvo9x** [comment]
Hi. I'm a new supporter. Please brief your question. Could you share the AppConfig file ?
