### ISSUE TITLE
[mstore-pro] - Category Top and SideMenu not implementing paging

### ISSUE THREAD

**Issue by harry503** [inspireui/support#1069]
1. Paging not yet implemented in Top and SideMenu Category
Both the new layout (SideMenu and Top menu) only display 20 results (1st api call), and not implementing paging to display all products.

Please fix so it will display all products when user scroll to the end

2. Screenshots
<img width="415" alt="Screen Shot 2019-09-16 at 22 45 04" src="https://user-images.githubusercontent.com/35995317/64972543-aa65ad00-d8d3-11e9-95b5-a5c916803c43.png">

<img width="410" alt="Screen Shot 2019-09-16 at 22 41 50" src="https://user-images.githubusercontent.com/35995317/64972544-aa65ad00-d8d3-11e9-9bbe-2105f3f9b8b8.png">

**Comment by minhcasi** [comment]
@harry503 - could you verify your purchased product by taking the screenshot from https://codecanyon.net/downloads ?

**Comment by harry503** [comment]
Purchase Code 7c399f31-c465-4f76-ac62-7fa0f04fd615

[image: Screen Shot 2019-09-17 at 10.25.32.png]

**Comment by harry503** [comment]
![Screen Shot 2019-09-17 at 10 25 32](https://user-images.githubusercontent.com/35995317/65009114-ca2dbd00-d935-11e9-8bee-20c56f25cb29.png)

**Comment by concuacon** [comment]
Hi @harry503  please attach your file config (AppConfig.js & Config.js)

**Comment by harry503** [comment]
Do you think because "paging" flag is not set in the AppConfig / config.js?
and you are saying that by default if it's set paging, then it should do
paging?

I was using the default fresh config from the latest one and it's not
paging. I can take a look the config again, but please also make paging can
be used if we choose to use Top / SideMenu. If we use the column then it's
working fine (it will do the paging).

**Comment by minhcasi** [comment]
Thank you, we have noted this feature for next improvement

**Comment by minhcasi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Category Top and SideMenu not implementing paging](https://trello.com/c/WUx0cgft/7-category-top-and-sidemenu-not-implementing-paging)

**Comment by minhcasi** [comment]
we are closing the ticket and move this ticket 'request feature' to our Trello board for easier to keep track, review, and update, also keep a status update  - thank you!
