### ISSUE TITLE
[Mstore Pro] AdMob Issues & Product Variations Not Showing

### ISSUE THREAD

**Issue by levi-beers** [inspireui/support#107]
In the latest Mstore pro (not expo) build uploaded December 14th there are 2 issues I've came across:

#1 AdMob can't be turned off for Android. The video plays at app start and banners appear regardless of what settings you have in config.

#2 Product variations are not showing up in cart. Check main mstore demo as shown in screenshot. The product size and color aren't being shown.

<img width="362" alt="screen shot 2018-12-16 at 2 11 30 am" src="https://user-images.githubusercontent.com/16378407/50051068-9f79b400-00d8-11e9-88dc-9349cb57b344.png">

**Comment by levi-beers** [comment]
Also, variations are not transferring to orders placed in WooCommerce. As you can see on PayPal payment confirmation page, the Color: Blue, Size: Medium dress I selected doesn't transfer those variations. 

<img width="362" alt="screen shot 2018-12-16 at 2 11 30 am" src="https://user-images.githubusercontent.com/16378407/50051218-3136f080-00dc-11e9-9dcd-c595c83fccc5.png">

**Comment by luyx2412** [comment]
Hi levibeer, thanks for your feedback. We will try to improve the issue with next version.
Thanks
