### ISSUE TITLE
[mstore-pro] - Order note does not handle dark theme

### ISSUE THREAD

**Issue by harry503** [inspireui/support#1070]
1. My issue
Fonts on order note are black when the dark theme is selected

2. Screenshots
<img width="420" alt="Screen Shot 2019-09-16 at 22 42 53" src="https://user-images.githubusercontent.com/35995317/64972787-15af7f00-d8d4-11e9-9d15-172bff39c511.png">

**Comment by minhcasi** [comment]
@harry503 - could you verify your purchased product by taking the screenshot from https://codecanyon.net/downloads ?

**Comment by harry503** [comment]
Purchase Code 7c399f31-c465-4f76-ac62-7fa0f04fd615

[image: Screen Shot 2019-09-17 at 10.25.32.png]

**Comment by harry503** [comment]
![Screen Shot 2019-09-17 at 10 25 32](https://user-images.githubusercontent.com/35995317/65009097-baae7400-d935-11e9-9c9a-7c0c614003db.png)

**Comment by minhcasi** [comment]
@harry503  - thank you!

@concuacon - please help for checking this issue

**Comment by concuacon** [comment]
hi @harry503 you download folder to hot fix, follow path: src/containers/
[OrderDetail.zip](https://github.com/inspireui/support/files/3620468/OrderDetail.zip)
