### ISSUE TITLE
[ListApp] - Show distances to places in List View

### ISSUE THREAD

**Issue by dxpsite** [inspireui/support#1072]
---------

1. My issue
Good day, I would like to get information about the distance to the objects in the list, see screenshots. Thank!
2. Screenshots
![Screenshot_1](https://user-images.githubusercontent.com/1510284/65021256-66a48f00-d937-11e9-8cb2-2572827d2c11.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/1510284/65021260-699f7f80-d937-11e9-85cd-831cd4abfb56.jpg)

3. My screenshot of the purchase product or my comment:
![Screenshot_3](https://user-images.githubusercontent.com/1510284/65021473-da469c00-d937-11e9-9991-9f08f604c71b.jpg)

3. Config files (optional)

**Comment by thangvo9x** [comment]
With this case. Please provide me more detail about your website. login at admin dashboard such as cPanel Host for checking. Thanks

**Comment by dxpsite** [comment]
> 
> 
> With this case. Please provide me more detail about your website. login at admin dashboard such as cPanel Host for checking. Thanks

Hi, i sent on your email all info with subj  "[ListApp] - Show distances to places in List View #1072"

**Comment by thangvo9x** [comment]
which email? Please send email thang@inspireui.com help me.

**Comment by dxpsite** [comment]
from dxpsite@gmail.com, i sent yesterday

**Comment by minhcasi** [comment]
@dxpsite - could you help to resend the info to support@inspireui.com?

Sorry for this inconvenience as ThangVo has just left out team. Thank you!

**Comment by dxpsite** [comment]
> 
> 
> @dxpsite - could you help to resend the info to [support@inspireui.com](mailto:support@inspireui.com)?
> 
> Sorry for this inconvenience as ThangVo has just left out team. Thank you!

Ok, sent you by mail
