### ISSUE TITLE
[Mstore-pro] - ListAllscreen page show the Variable from AppConfig.json instead of the Value of variable

### ISSUE THREAD

**Issue by Gmlogy** [inspireui/support#1073]
---------
Mstore:
65ae6467-f067-450f-aa9d-6528a5ba0736

My issue
Hi, when i click " Show All" button it's redirect to a page that showing all products. the issue is in the top of screen i see the variable instead of the value.
for example i have a category named منتجات at Languages.js ( ProductFeatures: "منتجات", ) in Home screen i see the name that i set in Languages file but when i click to go to all category products i see ProductFeatures instead of منتجات , Please how can i solve this issue ?
thank you

2. Screenshots

![sreen1](https://user-images.githubusercontent.com/52473562/65052798-e6941e80-d962-11e9-9056-db1a2b13ad95.png)
![sreen2](https://user-images.githubusercontent.com/52473562/65052799-e72cb500-d962-11e9-9b0c-b842b5aae16f.png)

**Comment by concuacon** [comment]
@Gmlogy 
In file Languages.js add to object ar: {
......,
featureProducts: "منتجات مميزة",
.....
}
