### ISSUE TITLE
[mstore-pro] - Multiple commands produce ... copy command for fonts

### ISSUE THREAD

**Issue by saleebm** [inspireui/support#1075]
1. My issue

Probably just the new Build System. I have xcode-beta
note: Using new build system
note: Planning build
note: Using build description from disk
Build system information
error: Multiple commands produce '/Users/minasaleeb/sites/mstore-pro/ios/build/mstore/Build/Products/Debug-iphonesimulator/mstore.app/Zocial.ttf':
1) Target 'mstore' (project 'mstore') has copy command from '/Users/minasaleeb/sites/mstore-pro/node_modules/react-native-vector-icons/Fonts/Zocial.ttf' to '/Users/minasaleeb/sites/mstore-pro/ios/build/mstore/Build/Products/Debug-iphonesimulator/mstore.app/Zocial.ttf'
2) That command depends on command in Target 'mstore' (project 'mstore'): script phase “[CP] Copy Pods Resources”

... etc for every font file except OpenSans

So I followed the debug protocol, and went to xcode and removed the Copy Pods Resources from the mstore target as suggested. And the app built no problem.

2. Screenshots
![Screen Shot 2019-09-17 at 15 17 03](https://user-images.githubusercontent.com/34875122/65076380-7edbd480-d95e-11e9-879f-40d88062cf6a.jpg)
3. My screenshot of the purchase product or my comment:
![Screen Shot 2019-09-17 at 15 18 37](https://user-images.githubusercontent.com/34875122/65076379-7edbd480-d95e-11e9-8950-cfcc70da4470.jpg)
3. Config files (optional)
not necessary. Built it as-is

**Comment by concuacon** [comment]
Hi @saleebm you try to run: rm -rf node_modules/ && yarn && cd ios/ && rm -rf Pods/ && rm -rf Podfile.lock && pod install && cd ../

**Comment by saleebm** [comment]
> Hi @saleebm you try to run: rm -rf node_modules/ && yarn && cd ios/ && rm -rf Pods/ && rm -rf Podfile.lock && pod install && cd ../

Hi @concuacon, yes I did that first but it still erred. Removing the Copy commands as I stated above was the only way I found to resolve this error during build. 

I also tried to do react-native upgrade —legacy

**Comment by concuacon** [comment]
Hi @saleebm  you try run: rm -rf ~/Library/Developer/Xcode/DerivedData to clear folder DerivedData/ and rebuild
I would like to ask you more, are you using xcode 11? maybe this is the reason if trying to mount the above methods fails, you should downgrade the xcode version to 10.x (recommend 10.2.1)
