### ISSUE TITLE
[Fluxstore 1.4.4] - Magento Products not displaying 

### ISSUE THREAD

**Issue by DrChrispoper** [inspireui/support#1078]
1. My issue
I have just started using Fluxstore 1.4.4 with Magento.
The Categories are loading fine and I successfully logged into my customer account.
But the products are not showing when I select a Category.

2. Screenshots

Categories | Category | Products
------------ | ------------- | -------------
![Simulator Screen Shot - iPhone 11 Pro Max - 2019-09-18 at 11 28 48](https://user-images.githubusercontent.com/1864825/65140985-a3d85200-da07-11e9-9f7b-1ca44cf306d3.png) | ![Simulator Screen Shot - iPhone 11 Pro Max - 2019-09-18 at 11 29 02](https://user-images.githubusercontent.com/1864825/65140996-a89d0600-da07-11e9-90b2-477d33b196fc.png) | ![Simulator Screen Shot - iPhone 11 Pro Max - 2019-09-18 at 11 29 13](https://user-images.githubusercontent.com/1864825/65141000-aaff6000-da07-11e9-98bb-6fcf00c51e57.png)

3. My screenshot of the purchase product or my comment:
![screenshot-codecanyon net-2019 09 18-11-31-37](https://user-images.githubusercontent.com/1864825/65141167-fb76bd80-da07-11e9-8ad5-fb9fa3772121.png)

**Comment by DrChrispoper** [comment]
This is the response from the api call:
```
{"messages":
{"error":
[{"code":500,"message":"Fatal Error: 'Uncaught Error: Cannot instantiate interface Mstore\\ProductsList\\Api\\ProductListInterface in \/opt\/bitnami\/apps\/magento\/htdocs\/vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php:50

Stack trace:

#0 \/opt\/bitnami\/apps\/magento\/htdocs\/vendor\/magento\/framework\/ObjectManager\/ObjectManager.php(70): Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->create('Mstore\\\\Products...')
#1 \/opt\/bitnami\/apps\/magento\/htdocs\/vendor\/magento\/module-webapi\/Controller\/Rest.php(328): Magento\\Framework\\ObjectManager\\ObjectManager->get('Mstore\\\\Products...')
#2 \/opt\/bitnami\/apps\/magento\/htdocs\/vendor\/magento\/module-webapi\/Controller\/Rest.php(239): Magento\\Webapi\\Controller\\Rest->processApiRequest()
#3 \/opt\/bitnami\/apps\/magento\/htdocs\/vendor\/magento\/framework\/Interception\/Interceptor.php(58): Magento\\Webapi\\Controller\\Rest->dispatch(Object(Magento\\Framework\\App\\Request\\Http))
#4 \/opt\/bitnami\/apps\/magento\/htdocs\/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Magento\\Webapi\\Controller\\Rest\\Interceptor' in '\/opt\/bitnami\/apps\/magento\/htdocs\/vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php' on line 50","trace":"Trace is not available."}]}}
```

**Comment by DrChrispoper** [comment]
It's all good. I managed to fix it clearing the Magento cache.

But before I close can you change your docs for the config of Magento?
1. You mention you need to change config.json to add the server settings when it should be config.dart
2. Remind people to clear the cache on Magento after 
`php bin/magento setup:upgrade`
with:
`php bin/magento cache:clean`
`php bin/magento cache:flush`

Thanks.

**Comment by minhtruong315** [comment]
@DrChrispoper i will update our document. thanks
