### ISSUE TITLE
[mstore-opencart]

### ISSUE THREAD

**Issue by mikebanson** [inspireui/support#1079]
user can't login from our domain,
no endpoint for facebook
description still displays the html content
some products from categories doesnt display.
setting shipping address throws warnings
getting shipping methods throws internal server error
any other process which leads to creating an order 
products doesnt display on the front screen

**Comment by minhcasi** [comment]
- could you share the purchased screenshot 

- please don't share the whole source code here

**Comment by mikebanson** [comment]
![WhatsApp Image 2019-09-19 at 09 27 47](https://user-images.githubusercontent.com/39365525/65232563-e6119a00-dac0-11e9-9796-026dba08ede1.jpeg)
![WhatsApp Image 2019-09-19 at 09 35 03(1)](https://user-images.githubusercontent.com/39365525/65232570-e90c8a80-dac0-11e9-90b3-a891f524fef7.jpeg)
![WhatsApp Image 2019-09-19 at 09 25 08](https://user-images.githubusercontent.com/39365525/65232652-06415900-dac1-11e9-9c89-9cf239d865c0.jpeg)

**Comment by mikebanson** [comment]
users cannot login either by the email and pass or by facebook

**Comment by minhcasi** [comment]
@mikebanson - could you attach your config file so that we could help for further checking, thank you!

**Comment by mikebanson** [comment]
[AppConfig.zip](https://github.com/inspireui/support/files/3635706/AppConfig.zip)
[Config.zip](https://github.com/inspireui/support/files/3635707/Config.zip)

i attached the last time, nothing was done.

**Comment by minhcasi** [comment]
@minhtruong315 - is checking

**Comment by mikebanson** [comment]
no response?

**Comment by minhtruong315** [comment]
@mikebanson Did you install mstore api?
https://docs.inspireui.com/mstore-opencart/customization/

**Comment by mikebanson** [comment]
yes i did install it

**Comment by minhtruong315** [comment]
@mikebanson can you share me admin account via email: truong@inspireui.com

**Comment by minhtruong315** [comment]
@mikebanson pls try again. i installed mstore plugin in your website

**Comment by mikebanson** [comment]
hello, i just tried same issue nothing has changed

**Comment by minhtruong315** [comment]
@mikebanson our plugin only support opencart version 3.0 now. can you try to upgrade your website to 3.0

**Comment by mikebanson** [comment]
but one the envato page it says it supports 2.3.0.x. that is why i bought it. otherwise then i have to request a refund
