### ISSUE TITLE
[Mstore+Beonews] Feature Request: Migrate webview to RN community's 'react-native-webview' replacement & option to disable html sanitization

### ISSUE THREAD

**Issue by levi-beers** [inspireui/support#108]
[Mstore Pro & BeoNews Pro] 

#1 Built-in RN WebView is being deprecated and has moved to [its own repository](https://github.com/react-native-community/react-native-webview). It uses the much improved WKHTMLView on iOS making significant improvements when loading large/dynamic pages. The only thing I had to do to switch is install module and change the import call to

`import { WebView } from 'react-native-webview'`

To my knowledge, no fixes are being applied to core's WebView. However, you can see active resolutions to issues in the community's repository.

#2 Option to disable HTML sanitization

In Beonews webview component, you sanitize HTML stripping out tags that aren't found in 'allowedTags'. Often, and especially with page builders like Elementor, people create some complex posts that aren't loading in Beonews webview properly. Their tables, lists and similar features aren't loading because of the HTML being sanitized.

**Comment by minhcasi** [comment]
Thank you @levi-beers we will check the solution for this feature

**Comment by luyx2412** [comment]
Closed and plan in new version!
