### ISSUE TITLE
[Fluxstore 1.4.4] - Null description 

### ISSUE THREAD

**Issue by DrChrispoper** [inspireui/support#1080]
I have products that don't have any descriptions on Magento.
When trying to display them there are errors shown in the screen and in the console:

`'package:flutter_widget_from_html_core/src/core_html_widget.dart': Failed assertion: line 59 pos 16: 'html != null': is not true.`

I have edited this file on line 28:
lib/screens/detail/product_description.dart

from

```
HtmlWidget(
                product.description,
                textStyle: TextStyle(color: Theme.of(context).accentColor),
              ),
```

to

```
HtmlWidget(
                product.description??"No description",
                textStyle: TextStyle(color: Theme.of(context).accentColor),
              ),
```
So that the error is managed. 
I don't know if the issue is magento specific and you can/want to fix it when the description is fetched or at the display with something similar to this.

Thanks

**Comment by minhtruong315** [comment]
@DrChrispoper can you print product.description and send me logs, i think the description is wrong format

**Comment by DrChrispoper** [comment]
The product description is null when there is no description:

<img width="281" alt="Screenshot 2019-09-20 at 12 05 50" src="https://user-images.githubusercontent.com/1864825/65322541-0dd72f80-db9f-11e9-8b64-2f70577d5d6f.png">

When I have a description it has a String with html which is the correct format I believe.

<img width="301" alt="Screenshot 2019-09-20 at 12 08 11" src="https://user-images.githubusercontent.com/1864825/65322699-74f4e400-db9f-11e9-8a57-3805100c1c69.png">

**Comment by minhtruong315** [comment]
@DrChrispoper Can you send me config.dart and config.json file via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/1080

**Comment by minhtruong315** [comment]
@DrChrispoper I sent you solution in email. pls check
