### ISSUE TITLE
[MStore Pro] - Multiple languages

### ISSUE THREAD

**Issue by 9mtm** [inspireui/support#1082]
Hallo,

I have trouble activating multiple languages,
1. My issue

```

Can't find variable: Languages

<unknown>
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false:1061:2691
h
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false:2:1670
<unknown>
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false:808:368
h
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false:2:1670
<unknown>
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false:772:167
h
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false:2:1670
<unknown>
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false:770:139
h
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false:2:1670
<unknown>
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false:760:152
h
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false:2:1670
<unknown>
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false:693:276
h
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false:2:1670
<unknown>
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false:11:67
h
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false:2:1670
d
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false:2:868
global code
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false:1826:4


```

2. Screenshots

https://prnt.sc/p80czj

https://prnt.sc/p80fth

https://prnt.sc/p80dca

https://prnt.sc/p892qy

3. My screenshot of the purchase :

 https://prnt.sc/p8042y

https://expo.io/@orzdi/orzdi

**Comment by minhcasi** [comment]
Hi, the switcher language setting only available from the mstore-pro folder, please try to run it with react-native-cli on this folder - thanks

**Comment by 9mtm** [comment]
Hallo ! :)
I try it but I get this error!

warn Package api-ecommerce has been ignored because it contains invalid configuration. Reason: Cannot find module 'api-ecommerce/package.json'


https://prnt.sc/p87lka


thanks 👍

**Comment by minhcasi** [comment]
hi, you can try to run: yarn remove api-ecommerce
The install it again by: yarn install  api-ecommerce

Also, when run with the mstore-pro please try to install react-native-cli by using: npm install react-naitve-cli -g

ref more from: https://facebook.github.io/react-native/docs/getting-started.html

**Comment by 9mtm** [comment]
i was try but i get that


https://prnt.sc/p9u74u

thank you :)

**Comment by minhcasi** [comment]
oh sorry, it's my mistyping, the correctly one: "npm install react-native-cli -g"

**Comment by 9mtm** [comment]
thank you  👍 and now  get that 

what i i should write to run the app? 

yarn start or expo start

https://prnt.sc/padarq


I did not change the application information to now this is the basic application with api  inspireui

but still, I can't run the app on Mstore Pro 

thank you

**Comment by minhcasi** [comment]
for the mstore-pro run:
<code>
yarn start --reset-cache
react-native run-io 
or: react-native run-android
</code>

**Comment by 9mtm** [comment]
i get that when i run : react-native run-ios and react-native run-android


MacBook-Pro:mstore-pro mohameedalarade$ react-native run-ios
-bash: react-native: **command not found**
MacBook-Pro:mstore-pro mohameedalarade$ react-native run-android
-bash: react-native: **command not found**

**Comment by minhcasi** [comment]
Hi, please try to install by: 
npm install react-native-cli -g

Ref: https://facebook.github.io/react-native/docs/getting-started.html
