### ISSUE TITLE
Fluxstore - installing

### ISSUE THREAD

**Issue by attare026** [inspireui/support#1086]
Running "flutter pub get" in source...                          
Because every version of flutter_test from sdk depends on path 1.6.4 and fstore depends on path 1.6.2, flutter_test from sdk is forbidden.

So, because fstore depends on flutter_test any from sdk, version solving failed.
pub get failed (1)

**Comment by minhcasi** [comment]
Could you share the purchased screenshot from https://codecanyon.net/downloads - thank you!

**Comment by sunil1509** [comment]
go to pubspec.yaml file and change path 
your path 1.6.2 but its required 1.6.4

**Comment by minhcasi** [comment]
@attare026  Try to update the latest 1.5 with new library update as well, thank you!
