### ISSUE TITLE
[mstore-pro] - Developer Console.log() is not printing anything in console

### ISSUE THREAD

**Issue by harry503** [inspireui/support#1087]
1. My issue
I can not see any of the console.log('test') being printed out in the console tab. When I use warn('test') then it will print out just fine. What's wrong with console.log() ? We need to debug when implementing custom logic.

I tries with another app / creating a new react-native app and it's fine / the console.log() is working for another project but not mstore-pro.

Is there any settings to changes? I started to see babel-plugin-transform-remove-console. Is there anything to do with it? how to enable DEV mode so it will print out console.log() ?

I need this because i need to log custom code inside node_modules. I got error when i tried to import and used the warn inside @app/Omni.js 

2. Screenshots
<img width="1087" alt="Screen Shot 2019-09-20 at 07 15 00" src="https://user-images.githubusercontent.com/35995317/65289793-66de9d80-db76-11e9-9e60-1e678c96a391.png">

3. My screenshot of the purchase product or my comment:
Purchase Code 7c399f31-c465-4f76-ac62-7fa0f04fd615

3. Config files (optional)
as-is

**Comment by concuacon** [comment]
hi @harry503 In the constants.js file did you use useReactotron = false?

**Comment by harry503** [comment]
No, reactotron is set to True. and it's working fine in Reactotron. For now, if i have to debug, I have to use reactotron by using "warn()" function.

It's just the console.log that's not working. And I expect the console.log to be working in React Native Debugger (attached previously)

const Constants = {
  RTL: false, // default to set redux. Only use first time
  useReactotron: true,

**Comment by concuacon** [comment]
if you want to use React Native Debugger, you must set useReactotron: false,

**Comment by concuacon** [comment]
@harry503 if use want log with Reactotron, u can use Reactotron.log('conetnt');

**Comment by harry503** [comment]
Ok. you can mark it as closed. Thank you
