### ISSUE TITLE
[beonews] - Can't login / register

### ISSUE THREAD

**Issue by dinhduccuong** [inspireui/support#1089]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------
1. My issue
- beonews pro: can not login / register 
website: chamsocsausinh.info
app code beonews 
2. Screenshots

3. My screenshot of the purchase product or my comment:
KEY: Item Purchase Code:
b5e58b5d-1e67-4699-aece-71b9be34b5ac
3. Config files (optional)

**Comment by minhcasi** [comment]
Thank you for your feedback, we will update the pre-config with the ready set up and share you the detail so that you can refer to the config - thank you!

**Comment by dinhduccuong** [comment]
Hi, any updates. Thanks.

**Comment by minhcasi** [comment]
@dinhduccuong - pls check this link - https://github.com/inspireui/mstore

<blockquote><div><strong><a href="https://github.com/inspireui/mstore">Server Error · GitHub</a></strong></div></blockquote>
