### ISSUE TITLE
[MStore] If you know how to change promotions images in the app please show me how

### ISSUE THREAD

**Issue by samber91** [inspireui/support#109]
**Required Info (please complete the following information):**
 - Product: [e.g. MStore, ListApp]
 - Your Purchased Code: [get from https://codecanyon.net/downloads]
(we may not reply if you are not our customer)

**Describe the bug**

**Screenshots**

**Additional context**
Add any other detail logs about the problem here.
If possible please share your config.js that use for the app setting

**Comment by samber91** [comment]
Purchase code : ad1ac976-3e34-4e40-a473-0985df712891

If you know how to change promotions images in mstore pro please show me how step by step or drop your email by i will contact you . Anybody. Thank you

**Comment by minhcasi** [comment]
Hi @samber91 could you explain what is the promotions images, any screenshot? We guess it is the banner from the HorizonLayout from the config file ?

**Comment by minhcasi** [comment]
Hi, please close the ticket as there is no response - thank you!
