### ISSUE TITLE
[Fluxstore 1.4.4] - Magento Payment support

### ISSUE THREAD

**Issue by DrChrispoper** [inspireui/support#1090]
1. My issue
Hi, I have started using fluxstore with magento 2 but have a question.
What payment methods, if any are supported? 

You have mentioned at this point 
https://github.com/inspireui/support/issues/914#issuecomment-521970132

That Paypal and Stripe are not supported but is are any payment methods supported?

Thanks

**Comment by minhcasi** [comment]
These new payment gateways will be supported on next 1.5: Paypal, razorpay vs tap - thank you!

**Comment by sodhanii** [comment]
Is PayPal supported now?

**Comment by DrChrispoper** [comment]
> Is PayPal supported now?

Yes it is since 1.5
