### ISSUE TITLE
[fluxstore pro] - build error, Undefined symbol

### ISSUE THREAD

**Issue by clickdigitalinteractive** [inspireui/support#1091]
My issue
Getting the following build errors in flutter build ios and xcode 10.3:

Undefined symbol: _UISceneWillEnterForegroundNotification
Undefined symbol: ___isPlatformVersionAtLeast

My screenshot of the purchase product or my comment:
http://tinyurl.com/y6sbcgk8

**Comment by minhcasi** [comment]
Hi, could i know if you pass this guide for the basic Set up on your machine - https://flutter.dev/docs/get-started/test-drive ? Thank you!

**Comment by ToledoNicola** [comment]
> Hi, could i know if you pass this guide for the basic Set up on your machine - https://flutter.dev/docs/get-started/test-drive ? Thank you!
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/b79d5f795eac013611f2dac92850a689fc9d3d46/68747470733a2f2f666c75747465722e6465762f696d616765732f666c75747465722d6c6f676f2d73686172696e672e706e67">**[Test drive](https://flutter.dev/docs/get-started/test-drive)**This page describes how to create a new Flutter app from templates, run it,and experience hot reload after you make changes to the app.Select your development tool of choice for writing, building, and runningFlutter apps.

yes but remain

`
Launching lib/main.dart on iPhone Xʀ in debug mode...
Xcode build done.                                           29,9s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
Xcode's output:
↳
    Undefined symbols for architecture x86_64:
      "_UISceneWillEnterForegroundNotification", referenced from:
          +[ICMBridge load] in Intercom(ICMBridge.o)
      "___isPlatformVersionAtLeast", referenced from:
          -[IntercomSDK_IntercomConversationCollectionViewController insetsForAccessoryView] in Intercom(IntercomConversationCollectionViewController.o)
          +[IntercomSDK_ITBUpload createUploadForMediaAsset:completion:] in Intercom(ITBUpload.o)
          +[IntercomSDK_ITBUpload processImageDataForUpload:mediaAsset:info:imageUploadDataUTI:completion:] in Intercom(ITBUpload.o)
          -[IntercomSDK_IIMInputAccessoryView createConstraints] in Intercom(IIMInputAccessoryView.o)
          -[IntercomSDK_IIMInputButtonContainerView createConstraints] in Intercom(IIMInputButtonContainerView.o)
          -[IntercomSDK_IIMMediaViewController updateCollectionViewContentInsets] in Intercom(IIMMediaViewController.o)
`

**Comment by clickdigitalinteractive** [comment]
Yes I have done that demo, I can get the myapp / runner to build/run on my device no problem, both through terminal with flutter and xcode. When I try fluxstore (without even doing any changes so it's not anything I've done to the code), I get errors. I get the same as the person above...

> Undefined symbols for architecture arm64:
      "_UISceneWillEnterForegroundNotification", referenced from:
          +[ICMBridge load] in Intercom(ICMBridge.o)
      "___isPlatformVersionAtLeast", referenced from:
          -[IntercomSDK_IntercomConversationCollectionViewController
          insetsForAccessoryView] in
          Intercom(IntercomConversationCollectionViewController.o)
          +[IntercomSDK_ITBUpload createUploadForMediaAsset:completion:] in
          Intercom(ITBUpload.o)
          +[IntercomSDK_ITBUpload
          processImageDataForUpload:mediaAsset:info:imageUploadDataUTI:completion:]
          in Intercom(ITBUpload.o)
          -[IntercomSDK_IIMInputAccessoryView createConstraints] in
          Intercom(IIMInputAccessoryView.o)
          -[IntercomSDK_IIMInputButtonContainerView createConstraints] in
          Intercom(IIMInputButtonContainerView.o)
          -[IntercomSDK_IIMMediaViewController updateCollectionViewContentInsets]
          in Intercom(IIMMediaViewController.o)
          -[IntercomSDK_IIMMediaViewController layoutExpandButton] in
          Intercom(IIMMediaViewController.o)
          ...
    ld: symbol(s) not found for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build systemnote: Planning buildnote: Constructing build
    description

> Could not build the precompiled application for the device.

Have you run fluxstore on a mac and xcode? Please let us know how to solve these errors, without being able to run on a mac so I can test on an iphone the code is useless.

**Comment by clickdigitalinteractive** [comment]
The intercom SDK needs to be updated, it is using an old SDK.

**Comment by minhcasi** [comment]
@clickdigitalinteractive @ToledoNicola - as the Intercom Chat library is not stable, we decide to remove it from v1.5

Please also try to update the latest Xcode 11 and iOS 13 and restart the build again
