### ISSUE TITLE
[ListApp] Login - Register | Events | Reviews

### ISSUE THREAD

**Issue by mpapado3** [inspireui/support#1093]
1. My issue

The documentation on how to setup and which files we need to edit is not clear.
While we try to setapp the application I have stepped on below issues:

a. On the WordPress site we don't want to use WooCommerce, but do we have to install it just to use the REST API?
b. I have entered on app.json our facebook APP ID, but I try to use the facebook login on the application it shows the Beonews account? Where else do we have to change the FB APP ID?
c. When I try to create an account with email I get an error "Unknown controller 'mstore user' ".
d. When I try to login with my web created user I get "JWT is not configured properly, please contact the admin.
e. On the WP we have an event and some reviews on a listing, but on the mobile application are not visible, how we can make them appear?

2. Screenshots

3. My screenshot of the purchase product or my comment:

Item ID:22645013
Item Purchase Code:1d234c6c-fad8-410c-9b42-3ba45e1abf50
Purchase Date:2019-09-12 14:06:30 UTC

3. Config files (optional)

**Comment by minhcasi** [comment]
Hi, could you help to share your config files with the screenshot issues so that we investigate?

**Comment by mpapado3** [comment]
I have figured almost everything, only (e) is still not possible

**Comment by mpapado3** [comment]
I have crossed on different issues.

The WP site has reviews on a listing that are not visible on the mobile app.
![mobile](https://user-images.githubusercontent.com/17457738/65831823-1843a880-e2c6-11e9-831b-53ed03523798.png)
![WP](https://user-images.githubusercontent.com/17457738/65831825-18dc3f00-e2c6-11e9-8d46-87c3065c1124.png)

You can check the WP at www.cretapp.gr
And the mobile app at exp://exp.host/@toroloco/cretapp

**Comment by mpapado3** [comment]
I can send you later the AppConfig that I will have access on my PC.
But what I have noticed is that the reviews made from the mobile app are set on comments on WP and the reviews made on Listing application are set as reviews on the theme.

**Comment by thangvo9x** [comment]
Hi bro, I can't understand you mean. could you brief more detail?

**Comment by mpapado3** [comment]
Hi Tio,

the appconfig is below:
```
{
  "Website": {
    "url": "https://cretapp.gr",
    "consumerKey": "ck_7e7c4e9eb80deba8abc681bdb***********",
    "consumerSecret": "cs_d7b576d9a699ffb8a79827133***********"
  },
  "Theme": "classic",
  "MainColor": {
    "tabbarTint": "#f05209",
    "tabbarColor": "#000000",
    "mainColorTheme": "#ff2600",
    "tabbar": "#ebebeb"
  }
}
```

The problem is that the mobile app reviews are actually comments and do not show on WP and the reviews left on WP are not visible on the mobile app.

**Comment by thangvo9x** [comment]
Hi. Could you send me the account to login admin dashboard?
