### ISSUE TITLE
[FluxStore Pro] - Request Feature for Reset password link 

### ISSUE THREAD

**Issue by eduardn1** [inspireui/support#1095]
1. My issue : When you click **Reset password** on your demo App it redirects to the wordpress page ( web view )

Should be more like a popup in the App instead ? 

2. Screenshots : https://prnt.sc/p98ezm

3. My screenshot of the purchase product or my comment: i'm not yet a client, i'm waiting for your response, but i want to support the good development of this.

> - IMPORTANT: We will close the ticket if you could not prove as our customer.
 
if you want you can close this, but i'm here to help 👍

**Comment by minhcasi** [comment]
Thank you for your suggestion, we will improve this UX on next release, maybe find the way to upgrade it smoother - thank you!

**Comment by minhcasi** [comment]
fixed on 1.5.8
