### ISSUE TITLE
[mstore-expo] - Webview on ios not loading 

### ISSUE THREAD

**Issue by khiemhuynh95** [inspireui/support#1098]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue
Webview trên ios ko load dc link sau khi click button BuyNow (nhưng Android thì dc)
2. Screenshots

3. My screenshot of the purchase product or my comment:

3. Config files (optional)

**Comment by minhcasi** [comment]
Issue 2 - https://github.com/inspireui/support/issues/1097 
Issue 3 - https://github.com/inspireui/support/issues/1096

**Comment by concuacon** [comment]
@khiemhuynh95 bạn có thể gửi cho mình xem hình chụp màn hình của vấn đề không?

**Comment by khiemhuynh95** [comment]
Nó ko load ra page web trên ios. Nhưng Android thì chạy bt.
![IMG_2046](https://user-images.githubusercontent.com/15665845/65513854-b1775700-dea1-11e9-8ef7-d4a444f3dd7f.jpg)

**Comment by khiemhuynh95** [comment]
Adding: How to open amazon app after click a link in webview. The default just works for ios

**Comment by minhcasi** [comment]
@khiemhuynh95 - we have tested this issue and it's not a bug, there are some limitations from the React native webview that sometimes it is not working correctly on Android (sometimes due to the website that could not load the Javascript) - we will upgrade to open the whole page as Linking to use the external browser.
