### ISSUE TITLE
[FluxStore Pro] - Currently, CeBuilder hasn’t supported this project yet

### ISSUE THREAD

**Issue by The-Egyptian-Developers** [inspireui/support#1099]
I just buy FluxStore now & I get This message appears when I setup up

    Currently, CeBuilder hasn’t supported this project yet
Thank you

**Comment by minhcasi** [comment]
Hi, the CeBuilder has not yet supported for FluxStore, but we are in middle to develop new amazing FluxBuilder for our Flutter's product, it will be released on next couple of week, we will notify when it is ready - thank you!

**Comment by storchaktitos** [comment]
same situation with BeoNews. 

> 
Currently, CeBuilder hasn’t supported this project yet
> 
when will be ready FluxBuilder ?
