### ISSUE TITLE
BUILD FAILED

### ISSUE THREAD

**Issue by team2s** [inspireui/support#11]
Hello,
Beonews pro
When I execute the command "react-native run-android" the error in attached file displayed. Knowing that I have set up Android development environment and the emulator is running. As well as the AwesomeProject app for environment test is starts properly (attached file)
<img width="307" alt="capture d ecran 2018-11-14 a 22 01 55" src="https://user-images.githubusercontent.com/45049770/48512519-f67e3600-e859-11e8-99a1-6bcee6323e35.png">
<img width="555" alt="capture d ecran 2018-11-14 a 21 59 57" src="https://user-images.githubusercontent.com/45049770/48512520-f67e3600-e859-11e8-82c4-f59b6d995b0d.png">

**Comment by luyx2412** [comment]
Hi team2s, Please provide follow the template report to easier and investigate the issue. https://github.com/inspireui/support/issues/1
Thanks

**Comment by team2s** [comment]
Hello, When I can found this report ?

**Comment by luyx2412** [comment]
HI team2s, Please describe specific follow [this template](https://github.com/inspireui/support/issues/1) Thanks

**Comment by minhcasi** [comment]
Hi syslab, we have got your comment and it's ok without the purchase code. 

Please following this step to run the script:
1- Open the source folder (where content the package.json), and run the script:
yarn install
yarn start --reset-cache
react-native link

2. Open the Android simulator, then run this script:
react-native run-android

Let us know the checking and share the who screenshot if you still have an issue 

Very best!

**Comment by team2s** [comment]
Hello, 
You take a lot of time to answer!
After the execution of the first command as you specified I have the error :

<img width="564" alt="capture d ecran 2018-11-21 a 10 26 41" src="https://user-images.githubusercontent.com/45049770/48831970-599b2b80-ed78-11e8-880d-b2a85050366c.png">

**Comment by minhcasi** [comment]
Hi, could we help to remote your pc via teamviewer today if don't mine ? @luyx2412

**Comment by team2s** [comment]
Can you fix the problem here?

**Comment by minhcasi** [comment]
Hi @team2s, we could help to support remote on your PC to troubleshoot the issue, let us know when you are available - thanks
