### ISSUE TITLE
[Cestore]  Reactotron Debug true throwing error

### ISSUE THREAD

**Issue by souravlahoti** [inspireui/support#110]
Product: [e.g. Cestore - Cezerin]
Your Purchased Code: 22706124

**Describe the issues**
When I set useReactotron: true. I get this error on android only. Below is the attached error:
It works fine on iOS Emulatore

**Screenshots**
<img width="429" alt="screenshot 2018-12-15 at 8 54 58 pm" src="https://user-images.githubusercontent.com/4952640/50072507-6f770180-01fb-11e9-9505-0973da85a2d3.png">

**Additional context**
I am using GenyMotion for android Emulator

**Comment by minhtruong315** [comment]
Hi @souravlahoti I fixed reactotron on android version, you can edit ReactotronConfig.js file like this

```

**Comment by minhtruong315** [comment]
import Reactotron from 'reactotron-react-native'
import { reactotronRedux } from 'reactotron-redux'

console.disableYellowBox = true
console.ignoredYellowBox = ['Warning: `flexWrap: `wrap``'];

const reactotron = Reactotron
  .configure({ host: "192.168.1.7" }) // controls connection & communication settings
  .use(reactotronRedux())
  .connect() // let's connect!
export default reactotron
```
Remember to change host to your ip
thanks
