### ISSUE TITLE
[Fluxstore Pro] - i built the app but it’s not loading catgories or chechout with error format exception : unexpected character at character 1

### ISSUE THREAD

**Issue by mrwonderful2** [inspireui/support#1100]
1. My issue

i built the app but it’s not loading catgories or chechout with error format exception : unexpected character at character 1

2. Screenshots

https://ibb.co/YWKDw1X
https://ibb.co/MByVfBH

**Comment by minhcasi** [comment]
Could you share the config file so that we could try to reproduce the issues?

**Comment by mrwonderful2** [comment]
catgories works fine it was language issue 

checkout now working 
i used Quick Checkout

https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=7382

also i want to make arabic language is default 

and use a custom payment getway 




here is my config  i still test it 

import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:fstore/common/constants.dart';

/// Server config
const serverConfig = {
  "type": "opencart",
  "url": "http://localhost",
  "blog": "http://fluxstore.inspireui.com",
  "forgetPassword": "localhost/index.php?route=account/forgotten"
};

const afterShip = {
  "api": "e2e9bae8-ee39-46a9-a084-781d0139274f",
  "tracking_url": "https://fluxstore.aftership.com"
};

const CategoriesListLayout = kCategoriesLayout.card;

const Payments = {

};


/// The product variant config
const ProductVariantLayout = {
  "color": "color",
  "size": "box",
  "height": "option",
};

const kAdvanceConfig = {
  "DefaultCurrency": {"symbol": "\SAR", "decimalDigits": 2, "symbolBeforeTheNumber": true,"currency": "SAR"},
  "IsRequiredLogin": false,
  "GuestCheckout": true,
  "EnableShipping": true,
  "GridCount": 3,
  "DetailedBlogLayout": kBlogLayout.halfSizeImageType,
  "EnablePointReward": false,
};

/// The Google API Key to support Pick up the Address automatically
/// We recommend to generate both ios and android to restrict by bundle app id
/// The download package is remove these keys, please use your own key
const kGoogleAPIKey = {
  "android": "your-google-api-key",
  "ios": "your-google-api-key"
};

/// use to config the product image height for the product detail
/// height=(percent * width-screen)
/// isHero: support hero animate
const kProductDetail = {
  "height": 0.5,
  "marginTop": 0,
  "isHero": false,
  "safeArea": false,
  "showVideo": true,
  "showThumbnailAtLeast": 3
};

/// config for the chat app
const smartChat = [
  {'app': 'whatsapp://send?phone=84327433006', 'iconData': FontAwesomeIcons.whatsapp},
  {'app': 'tel:8499999999', 'iconData': FontAwesomeIcons.phone},
  {'app': 'sms://8499999999', 'iconData': FontAwesomeIcons.sms},
  {'app': 'firebase', 'iconData': FontAwesomeIcons.google},
  {'app': 'intercome', 'iconData': FontAwesomeIcons.intercom},
];
const String adminEmail = "admininspireui@gmail.com";
const kIntercomAPIKey = {
  'android': 'android_sdk-2c16c0e017a1e7b8d3b73b5a13a56b54cbf535c0',
  'ios': 'ios_sdk-33135e6653b055cec773b7903baff10efee94bc0',
  'appID': 'xro9xnfd'
};


/// the welcome screen data
List onBoardingData = [
  {
    "title": "Welcome to FluxStore",
    "image": "assets/images/fogg-delivery-1.png",
    "desc": "Fluxstore is on the way to serve you. "
  },
  {
    "title": "Connect Surrounding World",
    "image": "assets/images/fogg-uploading-1.png",
    "desc": "See all things happening around you just by a click in your phone. "
        "Fast, convenient and clean."
  },
  {
    "title": "Let's Get Started",
    "image": "fogg-order-completed.png",
    "desc": "Waiting no more, let's see what we get!"
  },
];

const PaypalConfig = {
  "clientId":  "AXFWJm_35Cn29hM6KMJRAbPltKYQcoI7GjzKbTi_v5cV-BQLcL8SbruAUecsn5CA8ryAhri8ubg1nOwn",
  "secret": "EK-dzS13YxV4STnJp7NpyIS9eG2JacspgXgmCHtoexYeZfLTNCMxIqefH5H29pe_hJ4uwlW776IvjfVH",
  "returnUrl": "http://return.example.com",
  "cancelUrl": "http://cancel.example.com"
};


const RazorpayConfig = {
  "keyId": "rzp_test_WHBBYP8YoqmqwB",
  "callbackUrl": "http://example.com"
};

/// Example categories:
/// {23: Category { id: 23  name: Bags}, 24: Category { id: 24  name: Bags},
/// 25: Category { id: 25  name: Blazers}, 208: Category { id: 208  name: Clothing},
/// 26: Category { id: 26  name: Dresses}, 209: Category { id: 209  name: Hoodies},
/// 27: Category { id: 27  name: Jackets}, 28: Category { id: 28  name: Jackets},
/// 29: Category { id: 29  name: Jeans}, 30: Category { id: 30  name: Jeans},
/// 18: Category { id: 18  name: Men}, 210: Category { id: 210  name: Music},
/// 211: Category { id: 211  name: Posters}, 19: Category { id: 19  name: Shirts},
/// 20: Category { id: 20  name: Shoes}, 212: Category { id: 212  name: Singles},
/// 21: Category { id: 21  name: T-Shirts}, 22: Category { id: 22  name: Women}}

**Comment by minhcasi** [comment]
Hi, the Quick Checkout is not ready support from the app, we are going to update new 1.5 to support some native payment - thank you!

Btw, pls try to change to virtual host instead of 'localhost', that causes the Rest API could not be reached

**Comment by mrwonderful2** [comment]
i already fixed the host and catgories

but checkout not working after update to 1.5

https://ibb.co/TMj95b4
https://ibb.co/DRvRrh7



also product option not working

some products imge not working

search not good

**Comment by minhtruong315** [comment]
@mrwonderful2 can you zip source code and send it via my email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/1100

**Comment by mrwonderful2** [comment]
done sir
can you please add hyperpay payment method gate2play alternative name 
hyperpay.com

i will attach you the plugin and sdk

**Comment by minhtruong315** [comment]
@mrwonderful2 i can not access your website. http://192.168.100.119/tomoul2

**Comment by mrwonderful2** [comment]
it's a localhost sir am sorry
i uploaded your api to my store now
please change  to :
https://tomoul.com

**Comment by minhtruong315** [comment]
@mrwonderful2 you need to enable shipping in config.dart file to fix checkout
"EnableShipping": true,

**Comment by mrwonderful2** [comment]
i don't use any shipping method
also i enabled it and i got the same error

if igonerd and swipe right

especially with the payment

**Comment by mrwonderful2** [comment]
Remember to login before checkout.

also i need geust checkout please 
it's so important to me
also hyperpay payment method 


i cannot use this app without all of this .

**Comment by minhtruong315** [comment]
@mrwonderful2 Guest check isn't available now, we will note that and will add them in the future

**Comment by mrwonderful2** [comment]
sir guest checkout aveliabe with the demo

the app is use less to me 
and i pay money for nothing till the future maybe good 


so please help me i need to finish this project

**Comment by minhtruong315** [comment]
demo is woo commerce, it's not opencart

**Comment by mrwonderful2** [comment]
any news
