### ISSUE TITLE
[MStore Pro] - after publish in google play and app store  

### ISSUE THREAD

**Issue by MohammedXAbdo** [inspireui/support#1101]
I uploaded my app to app store and google play
Here are the mistakes
In Apple
Icons never appear
And in Google
When you change the language to Arabic application is closed and does not work again
Is there a solution to these problems?
![64813103-e1b91e80-d5a0-11e9-9651-45e4c7b2a004](https://user-images.githubusercontent.com/24995995/65450175-cf5ea080-de3c-11e9-9e32-73da04ed4b7a.png)
![64813092-dcf46a80-d5a0-11e9-840a-03c3f2eed964](https://user-images.githubusercontent.com/24995995/65450181-d1286400-de3c-11e9-8af4-cc46f209394e.png)

**Comment by minhcasi** [comment]
Could you help to your the app on google so that we could help for checking

**Comment by MohammedXAbdo** [comment]
https://play.google.com/store/apps/details?id=com.mpa.ar5assouq
this is my app on google and, what about the app in the app store

**Comment by concuacon** [comment]
@MohammedXAbdo
"Icons never appear" => i checked this work,
"When you change the language to Arabic application is closed and does not work again" => can you compress your source send me via westranfer (mail tuan@inspireuicom)

**Comment by MohammedXAbdo** [comment]
ok

**Comment by MohammedXAbdo** [comment]
I sent it

**Comment by MohammedXAbdo** [comment]
https://we.tl/t-rBPWcjaxZs

**Comment by minhcasi** [comment]
@MohammedXAbdo - don't share public the source here, sent via email - thanks

**Comment by MohammedXAbdo** [comment]
ok I was sent it

**Comment by MohammedXAbdo** [comment]
Have you fixed the problem

**Comment by minhcasi** [comment]
Yes, we will update new version for this fixing - thanks

**Comment by MohammedXAbdo** [comment]
when you will send to me my source with fixing

**Comment by MohammedXAbdo** [comment]
not answer 😢😢😢

**Comment by MohammedXAbdo** [comment]
hello there

**Comment by minhcasi** [comment]
@MohammedXAbdo - sorry we forgot to notify that this issue is fixed on our latest release 3.9.6 - thank you!
