### ISSUE TITLE
[mstore pro] - The news section is not displayed when you first navigate to the Contact Us section.

### ISSUE THREAD

**Issue by jvarillas** [inspireui/support#1102]
1.- My Problem:
The news section is not shown when you first navigated to the Contact Us or About Us section. Attached in an image when we click on the news section and the Contact Us section appears. It should be noted that this happens when you browse news-Contact Us-news this is the scenario.
![page1](https://user-images.githubusercontent.com/55630741/65467648-8fd98980-de27-11e9-90ea-58a08a2bef53.PNG)
![page2](https://user-images.githubusercontent.com/55630741/65467651-9405a700-de27-11e9-9a63-39865a200d47.PNG)

**Comment by minhcasi** [comment]
note for investigating - thank you!
@concuacon

**Comment by concuacon** [comment]
Hi @jvarillas 

- I would like to send you the attached src.zip file, extract and copy to replace your src folder (remember to change the configuration in AppConfig.json) I will update it to the next version.

[src.zip](https://github.com/inspireui/support/files/3645861/src.zip)

- Issue #1094 "How can I configure the steps at the beginning of the app, to be able to change the background image and where those images are brought from?" => You can change config in src/common/Config.js (follow screenshot) and if you want customize code as you like, you can check in path src/components/AppIntro/index.js 
<img width="764" alt="Screen Shot 2019-09-24 at 2 47 59 PM" src="https://user-images.githubusercontent.com/11958061/65492002-56158b00-deda-11e9-8003-23625f9e3b31.png">
