### ISSUE TITLE
[mflux pro] - symbols showing wrong in blogs

### ISSUE THREAD

**Issue by clickdigitalinteractive** [inspireui/support#1103]
1. My issue
The & symbol is not showing correctly in the blog title.

**Comment by minhcasi** [comment]
Could you share the detailed screenshot purchased code - https://codecanyon.net/downloads

And the issue screenshot so that we could help for checking ?

**Comment by clickdigitalinteractive** [comment]
I've sent my screenshot in previous messages, I am reporting a bug, not a bug to just me but in the code, if you create a blog and have & in the title the & shows as &#038. Creating and uploading a screenshot (2 screenshots - 1 for purchase - I've done already and 1 for the clear bug) is a pain when it is a clear bug.

**Comment by minhcasi** [comment]
Could you try the latest fluxstore 1.5, I believe it was fix :)
