### ISSUE TITLE
Fluxstore Pro- 1.5 

### ISSUE THREAD

**Issue by anandnathtiwari** [inspireui/support#1106]
Dear Support Team,

I have Issue in checkout button. Please see the attached file. Also I want to know the change diffrence in 1.4.4 and 1.5

Thanks
anand nath tiwari
![checkout-button-error](https://user-images.githubusercontent.com/17059651/65568538-e229c000-df77-11e9-9e3c-7307c118f5fd.jpg)

**Comment by minhcasi** [comment]
@anandnathtiwari - could you share the config file so that we could reproduce this issue ?- thank you!

**Comment by anandnathtiwari** [comment]
Config is same as in your example folder. I just copy opencart config files and paste in common folder

**Comment by anandnathtiwari** [comment]
Are you realy work on opencart ? same issue in v 1.5.1 as in v1.5 in opencart . Nothing change, only copy your example opencart config files from example folder to common folder.

Thanks

**Comment by minhtruong315** [comment]
@anandnathtiwari you can try to login first then checkout

**Comment by minhtruong315** [comment]
@anandnathtiwari pls replace cart.dark in screens/cart.dart
[cart.dart.zip](https://github.com/inspireui/support/files/3679204/cart.dart.zip)
