### ISSUE TITLE
need help regarding flux store pro for opencart

### ISSUE THREAD

**Issue by vbmsoftin** [inspireui/support#1107]
--- sir I what can I use In callback url for razorpay

my website address - swebmart.com

thank you

**Comment by minhtruong315** [comment]
@vbmsoftin can you record screen?

**Comment by vbmsoftin** [comment]
Sir i just want to know callback url for razorpay payment gateway 

Thank you

**Comment by vbmsoftin** [comment]
And sir search is also not working

**Comment by minhtruong315** [comment]
you don't need to change callback url

**Comment by vbmsoftin** [comment]
Sir but when user paid for the order then there balance git deducted and app again start asking for payment.

Please mail me your email i wull send you video

**Comment by minhtruong315** [comment]
truong@inspireui.com 
with subject: https://github.com/inspireui/support/issues/1107
