### ISSUE TITLE
[BuzzApp1.3.1] - Error Regarding Media Ace 

### ISSUE THREAD

**Issue by michaelpark716** [inspireui/support#1108]
I get the below error when trying to load a post

Invariant Violation: Invariant Violation: [4083,"RCTImageView",1,{"width":340,"height":"<<NaN>>","overflow":"hidden","resizeMode":"contain","shouldNotifyLoadEvents":false,"src":[{"uri":"https://creators.mypetlife.co.kr/wp-content/plugins/media-ace/includes/lazy-load/images/blank.png"}],"defaultSrc":null,"loadingIndicatorSrc":null}] is not usable as a native method argument

This error is located at:
    in RCTImageView (at Image.android.js:254)
    in Image (at WebView/index.js:89)
    in RCTView (at View.js:45)
    in View (at HTML.js:489)
    in RCTView (at View.js:45)
    in View (at HTML.js:489)
    in RCTView (at View.js:45)
    in View (at HTML.js:521)
    in HTML (at WebView/index.js:131)
    in RCTView (at View.js:45)
    in View (at WebView/index.js:130)
    in Index (at PostDetail.js:59)
    in RCTView (at View.js:45)
    in View (at ScrollView.js:976)
    in RCTScrollView (at ScrollView.js:1115)
    in ScrollView (at PostDetail.js:42)
    in RCTView (at View.js:45)
    in View (at PostDetail.js:40)
    in PostDetail (created by ConnectFunction)
    in ConnectFunction (at PostDetail/index.js:38)
    in RCTView (at View.js:45)
    in View (at PostDetail/index.js:37)
    in RCTView (at View.js:45)
    in View (at VirtualizedList.js:1762)
    in CellRenderer (at VirtualizedList.js:688)
    in AndroidHorizontalScrollContentView (at ScrollView.js:976)
    in AndroidHorizontalScrollView (at ScrollView.js:1115)
    in ScrollView (at VirtualizedList.js:1081)
    in VirtualizedList (at FlatList.js:632)
    in FlatList (at PostDetail/index.js:60)
    in PostDetail (created by ConnectFunction)
    in ConnectFunction (at PostDetailScreen.js:46)
    in PostDetailScreen (at SceneView.js:9)
    in SceneView (at StackViewLayout.tsx:899)
    in RCTView (at View.js:45)
    in View (at StackViewLayout.tsx:898)
    in RCTView (at View.js:45)
    in View (at StackViewLayout.tsx:897)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at StackViewCard.tsx:106)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at screens.native.js:59)
    in Screen (at StackViewCard.tsx:93)
    in Card (at createPointerEventsContainer.tsx:95)
    in Container (at StackViewLayout.tsx:985)
    in RCTView (at View.js:45)
    in View (at screens.native.js:83)
    in ScreenContainer (at StackViewLayout.tsx:394)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at StackViewLayout.tsx:384)
    in PanGestureHandler (at StackViewLayout.tsx:377)
    in StackViewLayout (at withOrientation.js:30)
    in withOrientation (at StackView.tsx:104)
    in RCTView (at View.js:45)
    in View (at Transitioner.tsx:267)
    in Transitioner (at StackView.tsx:41)
    in StackView (at createNavigator.js:80)
    in Navigator (at createKeyboardAwareNavigator.js:12)
    in KeyboardAwareNavigator (at SceneView.js:9)
    in SceneView (at createTabNavigator.js:39)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at BottomNavigation.js:646)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at BottomNavigation.js:631)
    in RCTView (at View.js:45)
    in View (at BottomNavigation.js:615)
    in RCTView (at View.js:45)
    in View (at BottomNavigation.js:611)
    in BottomNavigation (created by Context.Consumer)
    in ThemeProvider (created by Context.Consumer)
    in withTheme(BottomNavigation) (at createMaterialBottomTabNavigator.js:110)
    in BottomNavigationView (at createTabNavigator.js:197)
    in NavigationView (at createNavigator.js:80)
    in Navigator (at createAppContainer.js:430)
    in NavigationContainer (at RootRouter.js:49)
    in RCTView (at View.js:45)
    in View (at RootRouter.js:48)
    in RootRouter (at App.js:81)
    in PersistGate (at App.js:80)
    in Provider (at App.js:79)
    in App (at withExpoRoot.js:20)
    in RootErrorBoundary (at withExpoRoot.js:19)
    in ExpoRootComponent (at renderApplication.js:35)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:98)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:115)
    in AppContainer (at renderApplication.js:34)

This error is located at:
    in NavigationContainer (at RootRouter.js:49)
    in RCTView (at View.js:45)
    in View (at RootRouter.js:48)
    in RootRouter (at App.js:81)
    in PersistGate (at App.js:80)
    in Provider (at App.js:79)
    in App (at withExpoRoot.js:20)
    in RootErrorBoundary (at withExpoRoot.js:19)
    in ExpoRootComponent (at renderApplication.js:35)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:98)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:115)
    in AppContainer (at renderApplication.js:34)
enqueueNativeCall
    C:\Users\user\Buzzapp.1.3.1\Source\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:253:8
fn
    C:\Users\user\Buzzapp.1.3.1\Source\node_modules\react-native\Libraries\BatchedBridge\NativeModules.js:137:8
createInstance
    C:\Users\user\Buzzapp.1.3.1\Source\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:4006:4
completeWork
    C:\Users\user\Buzzapp.1.3.1\Source\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:14437:12
completeUnitOfWork
    C:\Users\user\Buzzapp.1.3.1\Source\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:17094:10
performUnitOfWork
    C:\Users\user\Buzzapp.1.3.1\Source\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:17304:30
workLoop
    C:\Users\user\Buzzapp.1.3.1\Source\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:17316:41
renderRoot
    C:\Users\user\Buzzapp.1.3.1\Source\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:17417:15
performWorkOnRoot
    C:\Users\user\Buzzapp.1.3.1\Source\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:18423:17
performWork
    C:\Users\user\Buzzapp.1.3.1\Source\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:18324:24
performSyncWork
    C:\Users\user\Buzzapp.1.3.1\Source\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:18285:14
requestWork
    C:\Users\user\Buzzapp.1.3.1\Source\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:18169:19
scheduleWork
    C:\Users\user\Buzzapp.1.3.1\Source\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:17969:16
enqueueSetState
    C:\Users\user\Buzzapp.1.3.1\Source\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:6934:17
setState
    C:\Users\user\Buzzapp.1.3.1\Source\node_modules\react\cjs\react.development.js:335:31
<unknown>
    C:\Users\user\Buzzapp.1.3.1\Source\App\Container\PostDetail\index.js:107:20
processNext
    C:\Users\user\Buzzapp.1.3.1\Source\node_modules\react-native\Libraries\Interaction\TaskQueue.js:115:14
_processUpdate
    C:\Users\user\Buzzapp.1.3.1\Source\node_modules\react-native\Libraries\Interaction\InteractionManager.js:202:6
_callTimer
    C:\Users\user\Buzzapp.1.3.1\Source\node_modules\react-native\Libraries\Core\Timers\JSTimers.js:152:14
_callImmediatesPass
    C:\Users\user\Buzzapp.1.3.1\Source\node_modules\react-native\Libraries\Core\Timers\JSTimers.js:200:17
callImmediates
    C:\Users\user\Buzzapp.1.3.1\Source\node_modules\react-native\Libraries\Core\Timers\JSTimers.js:473:30
__callImmediates
    C:\Users\user\Buzzapp.1.3.1\Source\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:337:6
<unknown>
    C:\Users\user\Buzzapp.1.3.1\Source\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:135:6
__guard
    C:\Users\user\Buzzapp.1.3.1\Source\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:314:10
flushedQueue
    C:\Users\user\Buzzapp.1.3.1\Source\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:134:17

**Comment by minhcasi** [comment]
@michaelpark716  could you provide the following info:
1. Purchase code or screenshot to verify your purchase
2. The config files from common folder, we could use this config to reproduce the issues

Very best!

**Comment by michaelpark716** [comment]
I've emailed you. Thank you.
