### ISSUE TITLE
[Fluxstore] I have problem Execution failed for task ':app:compileFlutterBuildDebugArm64'.  with flutter run 

### ISSUE THREAD

**Issue by elgoharyibrahim** [inspireui/support#1109]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue

2. Screenshots

3. My screenshot of the purchase product or my comment:

3. Config files (optional)

**Comment by minhcasi** [comment]
@elgoharyibrahim  - could you able to run the example project successful - https://flutter.dev/docs/get-started/test-drive  ?

**Comment by elgoharyibrahim** [comment]
I can run example project successfully,
but in this project  when run  the error ':app:compileFlutterBuildDebugArm64

**Comment by minhcasi** [comment]
@elgoharyibrahim  - pls make sure to use latest v1.5.1 from https://codecanyon.net/downloads to fix the issue - thank you!
