### ISSUE TITLE
Sample css for a PICKER / DropDown implementation

### ISSUE THREAD

**Issue by souravlahoti** [inspireui/support#111]
Product: [e.g. Cestore - Cezerin]
Your Purchased Code: 22706124

Is there any sample for implementing a drop down in the mobile-ui for react native app.
When I use the default <Picker> UI on android is fine but iOS its getting distorted.

**Comment by minhcasi** [comment]
Hi, you can try some lib like this one - https://github.com/expo/react-native-action-sheet - thank you!
