### ISSUE TITLE
[ListApp] - createStackNavigator deprecated

### ISSUE THREAD

**Issue by dxpsite** [inspireui/support#1110]
1. My issue
Cannot debug via Expo (35.0.0)
2. Screenshots
![Screenshot_1](https://user-images.githubusercontent.com/1510284/65607590-78c8a200-dfb5-11e9-86d8-f4893f53c7fd.jpg)

3. My screenshot of the purchase product or my comment:

3. Config files (optional) package.json:
{
  "name": "Myapp",
  "version": "v0.8.1",
  "description": "Myapp",
  "author": "Shardik",
  "private": true,
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start -c",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "eject": "expo eject",
    "setup": "./scripts/setup.sh",
    "detach": "./scripts/detach.sh",
    "postinstall": "node ./scripts/stfu.js"
  },
  "dependencies": {
    "@appandflow/masonry-list": "^0.4.0",
    "@eva-design/eva": "^1.0.1",
    "@valdio/react-native-scrollable-tabview": "^0.8.11",
    "api-ecommerce": "0.0.29",
    "axios": "0.19.0",
    "base-64": "^0.1.0",
    "crypto-js": "^3.1.9-1",
    "currency-formatter": "1.5.4",
    "emoji-utils": "^1.0.1",
    "expo": "^35.0.0",
    "expo-ads-facebook": "~7.0.0",
    "expo-analytics": "1.0.11",
    "expo-constants": "7.0.0",
    "expo-facebook": "~7.0.0",
    "expo-font": "^7.0.0",
    "expo-linear-gradient": "^7.0.0",
    "expo-localization": "~7.0.0",
    "firebase": "6.3.1",
    "html-entities": "^1.2.1",
    "lodash": "4.17.15",
    "moment": "^2.23.0",
    "oauth-1.0a": "1.0.1",
    "postinstall-postinstall": "^2.0.0",
    "prop-types": "^15.6.0",
    "react": "16.8.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz",
    "react-native-animatable": "1.3.2",
    "react-native-button": "^2.3.0",
    "react-native-calendars": "1.200.0",
    "react-native-dates": "^2.0.4",
    "react-native-dropdownalert": "4.1.0",
    "react-native-gesture-handler": "~1.3.0",
    "react-native-gifted-chat": "0.9.11",
    "react-native-google-places-autocomplete": "^1.3.9",
    "react-native-image-carousel": "0.4.6",
    "react-native-keyboard-aware-scroll-view": "0.8.0",
    "react-native-loading-spinner-overlay": "^1.0.1",
    "react-native-map-link": "2.4.5",
    "react-native-maps": "~0.25.0",
    "react-native-modal-datetime-picker": "7.5.0",
    "react-native-modalbox": "^1.4.2",
    "react-native-onesignal": "3.3.0",
    "react-native-parallax": "^0.3.0",
    "react-native-parallax-scroll-view": "^0.21.3",
    "react-native-progress-bar-animated": "^1.0.6",
    "react-native-reanimated": "~1.2.0",
    "react-native-render-html": "4.1.2",
    "react-native-root-toast": "3.1.2",
    "react-native-screens": "~1.0.0-alpha.23",
    "react-native-scrollable-tab-view": "0.10.0",
    "react-native-slider": "0.11.0",
    "react-native-snap-carousel": "^3.8.0",
    "react-native-star-rating": "^1.1.0",
    "react-native-swipe-list-view": "2.0.0",
    "react-native-swipeout": "^2.3.6",
    "react-native-swiper": "^1.5.14",
    "react-native-tab-view": "^2.7.1",
    "react-native-tag-select": "^2.0.0",
    "react-native-textinput-effects": "0.5.1",
    "react-native-timeago": "^0.4.0",
    "react-native-ui-kitten": "^4.1.1",
    "react-navigation": "^4.0.9",
    "react-redux": "7.1.0",
    "react-timer-mixin": "^0.13.3",
    "redux": "4.0.4",
    "redux-persist": "^5.6.5",
    "redux-thunk": "^2.2.0",
    "sanitize-html": "1.20.1",
    "schedule": "0.4.0",
    "sentry-expo": "~2.0.0",
    "tcomb-form-native": "^0.6.20",
    "urijs": "^1.19.0",
    "url": "^0.11.0",
    "util": "0.12.1",
    "validate.js": "0.13.1",
    "wpapi": "^1.1.2",
    "xdate": "^0.8.2"
  },
  "devDependencies": {
    "@babel/core": "7.5.5",
    "@babel/plugin-proposal-decorators": "^7.4.0",
    "@babel/plugin-transform-runtime": "7.5.5",
    "@babel/preset-env": "7.5.5",
    "babel-jest": "24.8.0",
    "babel-plugin-module-resolver": "3.2.0",
    "babel-polyfill": "^6.26.0",
    "babel-preset-expo": "5.2.0",
    "babel-preset-react-native": "4.0.1",
    "path": "^0.12.7",
    "reactotron-react-native": "3.6.4",
    "reactotron-redux": "3.1.1"
  }
}

**Comment by minhcasi** [comment]
Mark as upgrade feature for next release to compatible with latest Expo 0.35 and navigation.

(please note that current release is not supported expo 0.35 yet, you can keep the default package.json at the moment)

**Comment by dxpsite** [comment]
Окау, i revert back expo-cli with all dependencies, but..
![Screenshot_1](https://user-images.githubusercontent.com/1510284/65724340-d42f8880-e0b8-11e9-9a09-8e321c9d3b20.png)
![Screenshot_2](https://user-images.githubusercontent.com/1510284/65724346-d72a7900-e0b8-11e9-8690-9ba52fd1f97c.png)
What i should do?

**Comment by minhcasi** [comment]
pls try to install the product via: yarn install

As the Cebuilder have some issue with PowerShell on Window.
