### ISSUE TITLE
[Fluxstore Pro] Error while running 

### ISSUE THREAD

**Issue by Chizinski** [inspireui/support#1111]
Configure project :app
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
WARNING: API 'variant.getMergeAssets()' is obsolete and has been replaced with 'variant.getMergeAssetsProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getMergeAssets(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.
WARNING: API 'variantOutput.getProcessResources()' is obsolete and has been replaced with 'variantOutput.getProcessResourcesProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variantOutput.getProcessResources(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.

> Configure project :cloud_firestore

Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':cloud_firestore'.
> Could not open cp_proj remapped class cache for 8qfrvudv6a865kh33g41jm59p (/home/chizinski/.gradle/caches/4.10.2/scripts-remapped/build_aqh0lf6mxaln9g1dcygrp7rfr/8qfrvudv6a865kh33g41jm59p/cp_proj70b1361a260e0ceb212a59c45f680ebd).
   > Could not open cp_proj generic class cache for build file '/home/chizinski/Fluff/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.12.9+4/android/build.gradle' (/home/chizinski/.gradle/caches/4.10.2/scripts/8qfrvudv6a865kh33g41jm59p/cp_proj/cp_proj70b1361a260e0ceb212a59c45f680ebd).
      > Unexpected lock protocol found in lock file. Expected 3, found 0.

* Try:
Finished with error: Please review your Gradle project setup in the android/ folder.
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
  Command: /home/chizinski/Desktop/Test/android/gradlew app:properties

**Comment by minhtruong315** [comment]
@Chizinski can you run command: flutter doctor and show me results
