### ISSUE TITLE
[Fluxstore 1.5] - Magento Products & Prices not showing

### ISSUE THREAD

**Issue by DrChrispoper** [inspireui/support#1115]
1. My issue

This was not an issue in 1.4.4
When watching at the list of products, the prices are shown as 0.00 
I've noticed the issue comes from magento.dart in lib/services
The function 
`  Future<List<Product>> fetchProductsByCategory(      {categoryId, page, minPrice, maxPrice, lang, orderBy, order}) async {`

You have added this line in 1.5

`endPoint += "&searchCriteria[filter_groups][0][filters][2][field]=type_id&searchCriteria[filter_groups][0][filters][2][value]=configurable&searchCriteria[filter_groups][0][filters][2][condition_type]=eq";
`

And the price is no longer being returned for the products.

**Comment by DrChrispoper** [comment]
To add to this, there is also an issue in fetching products in the same file:
The function
`  @override
  Future<List<Product>> fetchProductsLayout({config, lang}) async {`

You added this line in 1.5

`endPoint += "&searchCriteria[filter_groups][0][filters][1][field]=type_id&searchCriteria[filter_groups][0][filters][1][value]=configurable&searchCriteria[filter_groups][0][filters][1][condition_type]=eq";`

And the list of products are no longer being returned.

**Comment by minhtruong315** [comment]
@DrChrispoper can you send me config.json and config.dart file via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/1115

**Comment by DrChrispoper** [comment]
I have sent them for https://github.com/inspireui/support/issues/1125

**Comment by minhtruong315** [comment]
@DrChrispoper i dont see any email. pls send again

**Comment by DrChrispoper** [comment]
I've sent it again. Could I suggest setting up a Slack for your support?

**Comment by minhtruong315** [comment]
@DrChrispoper I checked your website. You dont set price for product configurable in admin. pls update price for those products

**Comment by DrChrispoper** [comment]
@minhtruong315 There were no issues before you added:

`endPoint += "&searchCriteria[filter_groups][0][filters][2][field]=type_id&searchCriteria[filter_groups][0][filters][2][value]=configurable&searchCriteria[filter_groups][0][filters][2][condition_type]=eq";`

Not all my products are configurable but none of the prices are showing when I look at the product list of a category.

**Comment by DrChrispoper** [comment]
Also you closed my other tickets because for some reason you don't use tickets per issue but per person.

So here are the rest of my issues:

Flowing #1123 I decided to test the search function, and have seen a few issues.
I am using Fluxstore 1.5 with Magento.

Issue 1. An exception is thrown if no results come back from the search.
In lib/services/magento.dart
Future<List<Product>> searchProducts({name, page}) async {
If I do a search and no products are found, the body of the response is "" not at the least "items:{}" or something similar. Cause this line to raise an error:
for (var item in convert.jsonDecode(response.body)["items"]) {

This seems more like an issue on the Magento extension side not returning the correct empty list of items.

Issue 2. Searching for a product with no categories.
In lib/services/magento.dart
Product parseProductFromJson(item) {
If a do a search and one of the products do not have a category. An exception is raised here:
product.categoryId = int.parse(categoryIds[0]);

One option would be to fix it on the extension side and not return items that don't have a category.
Or add something as simple as:

    if (categoryIds.length > 0) {
      product.categoryId = int.parse(categoryIds[0]);
    }
However you best prefer to code it.

Thanks.


And 


My issue
I am using Fluxstore 1.5 with Magento.
I have seen an issue (or missing feature?).
If I have a cart with items on my account on Magento they are not shown on Fluxstore.
If I add items to my cart in Fluxstore they will be added to Magento cart when I start the checkout.
If I remove my items from the Fluxstore cart they will not be removed in Magento.
If I checkout on Fluxtore I will pay for all the items that have been added and are on the Magento cart without knowing it.
I hope the explanation helps. If you need more info, I'll be happy to provide.
Thanks for the help.

**The reason I take the time to explain and find an issue is to contribute to the growth of the project. If you prefer, I can keep whatever fixes I make to myself and stop bothering you.**

**Comment by DrChrispoper** [comment]
I've fixed the cart not deleting past items properly if you are interested @minhtruong315 you know where to find me.
