### ISSUE TITLE
[Evastore] - 

### ISSUE THREAD

**Issue by WorkflowAutomation** [inspireui/support#1116]
1. My issue
I tried to connect our shopify to evastore using expo, it's throwing below error. I have raised comment in evastore comments section. They asked me confi.js file. I have attached below. Please solve our issue ASAP.

2. Screenshots
![WhatsApp Image 2019-09-24 at 10 47 50](https://user-images.githubusercontent.com/46641395/65680244-34e8a200-e074-11e9-8ffc-75ee8b506ecb.jpeg)

3. My screenshot of the purchased  product or my comment:
![eva](https://user-images.githubusercontent.com/46641395/65680369-6cefe500-e074-11e9-8a4e-3224e3e2bba3.PNG)

3. Config files (optional)

[config.txt](https://github.com/inspireui/support/files/3657260/config.txt)

**Comment by concuacon** [comment]
@WorkflowAutomation the config file you submitted is the same as our original config and it works, please re-attach your shopify config file(file AppConfig.json & Config.js).

**Comment by WorkflowAutomation** [comment]
PFB attachments.

**Comment by WorkflowAutomation** [comment]
Please solve our issue ASAP. We just set up with Eva store code and Shopify access token and all in appconfig.json. I have attached appconfig.json file in the mail. Error is throwing like the above image. A quick reply is appreciated.

**Comment by minhcasi** [comment]
@concuacon

**Comment by WorkflowAutomation** [comment]
Sorry, I didn't get your point.  What is the meaning of @concuacon? please solve our issue ASAP. We have an urgent requirement with your product.

**Comment by minhcasi** [comment]
Thank you, we will investigate and let you know

**Comment by WorkflowAutomation** [comment]
We are looking forward to your reply.

**Comment by WorkflowAutomation** [comment]
It's been too long still, no one solved our solution.

**Comment by WorkflowAutomation** [comment]
I fixed this issue. no problem.

**Comment by davutj** [comment]
@WorkflowAutomation What was the solution? I am facing with the same error
