### ISSUE TITLE
[my-product] - Fluxstore

### ISSUE THREAD

**Issue by betterend** [inspireui/support#1118]
Hi,

Kindly I'm trying to connect the app but there is an API wrning. That I'm not able get the source of it. I have attached the pictures.
[My store](https://drive.google.com/file/d/1AtQBzD0J2tff-ntxeqfogSOUQBmhQM-r/view?usp=drivesdk) 

[Fluxstore](https://drive.google.com/file/d/1AoRKCUW_Ch9Uu7ZUAaoisS2DkL1Dnndu/view?usp=drivesdk)

**Comment by minhcasi** [comment]
Hi, it's fixed - the fluxstore.inspireui.com

Please try to replace the previous mstore-checkout by install this new plugin - https://wordpress.org/plugins/mstore-api/

**Comment by betterend** [comment]
Hi I have replaced the previous plugin and i'm getting this error


Fatal error: Cannot redeclare registerJsonApiController() (previously declared in /home/flawlfc0/public_html/wp-content/plugins/mstore-api/mstore-api.php:103) in /home/flawlfc0/public_html/wp-content/plugins/mstore-checkout-1.1.7/mstore-checkout.php on line 109
