### ISSUE TITLE
[Cestore] need help to connect React native app with local development server

### ISSUE THREAD

**Issue by souravlahoti** [inspireui/support#112]
Product: [e.g. Cestore - Cezerin]
Your Purchased Code: 22706124

**Describe the issues**
I know we need to change the host name from localhost to some ip or domain name.
I changed my alias of localhost to mlocal.store on my Mac and then tried connecting my local react native app but it shows cannot connect to the server

**Steps**
Open /etc/hosts
127.0.0.1   mlocal.store

In mobile code 
common/Config.js
Cezerin: {
    url: 'http://mlocal.store:3001'
  },

**Additional context**
I am using Mac for my development.

**Comment by minhtruong315** [comment]
Hi @souravlahoti Did you install website successfully? You can use your ip to connect.
for example: 
Cezerin: {
url: 'http://192.168.1.4:3001'
}

**Comment by souravlahoti** [comment]
Yes, I am able to connect to it @minhtruong315. But I am not able to fetch images from the local sever but the images can be seen in the admin portal
<img width="427" alt="screenshot 2018-12-17 at 2 38 32 pm" src="https://user-images.githubusercontent.com/4952640/50077122-79076600-0209-11e9-86b9-35a0dd223634.png">
<img width="427" alt="screenshot 2018-12-17 at 2 38 08 pm" src="https://user-images.githubusercontent.com/4952640/50077150-8cb2cc80-0209-11e9-8d14-8e933dde2efa.png">

**Comment by minhtruong315** [comment]
> Yes, I am able to connect to it @minhtruong315. But I am not able to fetch images from the local sever but the images can be seen in the admin portal
> <img alt="screenshot 2018-12-17 at 2 38 32 pm" width="427" src="https://user-images.githubusercontent.com/4952640/50077122-79076600-0209-11e9-86b9-35a0dd223634.png">
> <img alt="screenshot 2018-12-17 at 2 38 08 pm" width="427" src="https://user-images.githubusercontent.com/4952640/50077150-8cb2cc80-0209-11e9-8d14-8e933dde2efa.png">

Can you try to edit domain in here? https://localhost:3000/admin/settings

**Comment by souravlahoti** [comment]
@minhtruong315 Thanks it worked. For others if your domain is to configured to direct to 3000 port please add domain as http://192.168.56.1:3000
