### ISSUE TITLE
[Mstore-pro] - how to show all categories in CategoriesScreens

### ISSUE THREAD

**Issue by Gmlogy** [inspireui/support#1120]
Mstore:
65ae6467-f067-450f-aa9d-6528a5ba0736

 My issue

Hello team,
i have more than 14 categories, but in CategoriesScreens i see only 12 categories
how can i show all the 14 categories ?
thank you

**Comment by concuacon** [comment]
@Gmlogy can you compress common folder into zip file send me?

**Comment by Gmlogy** [comment]
@concuacon 
[common.zip](https://github.com/inspireui/support/files/3662371/common.zip)

**Comment by concuacon** [comment]
Hi @Gmlogy i added your config, and in the category screen it shows all 14 categories.
![Simulator Screen Shot - iPhone X - 2019-09-30 at 11 10 03](https://user-images.githubusercontent.com/11958061/65849065-02d88800-e373-11e9-899a-434e34564cb3.png)
![Simulator Screen Shot - iPhone X - 2019-09-30 at 11 10 20](https://user-images.githubusercontent.com/11958061/65849067-02d88800-e373-11e9-9fd8-4fecc8731051.png)
![Simulator Screen Shot - iPhone X - 2019-09-30 at 11 10 43](https://user-images.githubusercontent.com/11958061/65849069-03711e80-e373-11e9-8b32-bd4d868f4603.png)
![Simulator Screen Shot - iPhone X - 2019-09-30 at 11 10 54](https://user-images.githubusercontent.com/11958061/65849074-0409b500-e373-11e9-99dc-e68a7a4e4106.png)
