### ISSUE TITLE
[Fluxstore-1.5.0] - Need full support for Coupon Function (Woocommerce)

### ISSUE THREAD

**Issue by Huysophanna** [inspireui/support#1121]
### 1. My issue
-> I have a very **big issue with Coupon** and I hope you can update the full functionality of the Woocommerce Coupon in the next update! I tried to set the **coupon minimum spend and maximum spend**, also other restriction in Woocommerce but all of them doesn't work! As I dive into the "coupon.dart" code (screenshot), I can see **you have implemented only the coupon code and the coupon amount** without any restriction which is really **dangerous for real world usage**, because in Woocommerce Coupon function has alot of restrictions and usage limitation function (screenshot). So I hope you can support **full functionality of Coupon Function**, otherwise, **the coupon can't be used in the real product**. Please consider.

### 2. Screenshots
<img width="766" alt="Screen Shot 2019-09-27 at 5 53 14 PM" src="https://user-images.githubusercontent.com/17026862/65765132-8fa3fb80-e151-11e9-8972-e93b172548f2.png">

**Woocommerce Coupon All Functions Restrictions**
<img width="993" alt="Screen Shot 2019-09-27 at 5 52 57 PM" src="https://user-images.githubusercontent.com/17026862/65765324-2375c780-e152-11e9-91ff-aa80cfbb528d.png">
<img width="993" alt="Screen Shot 2019-09-27 at 5 53 05 PM" src="https://user-images.githubusercontent.com/17026862/65765138-929eec00-e151-11e9-8e8f-52afae6eaec7.png">

### 3. My screenshot of the purchase product or my comment:
<img width="811" alt="Screen Shot 2019-09-27 at 6 10 18 PM" src="https://user-images.githubusercontent.com/17026862/65765307-18bb3280-e152-11e9-87e4-1d5baf322a24.png">

**Comment by minhcasi** [comment]
Noted as a feature request, we will investigate this issue - thank you!

**Comment by minhcasi** [comment]
updated some logic on 1.5.8 (release in 1-2 days) - you can add more logic on this file - https://tppr.me/Z0lIC - thanks
