### ISSUE TITLE
[Mstore-multivendor] - I'm facing lots of issues

### ISSUE THREAD

**Issue by Hamzanisar** [inspireui/support#1122]
Mstore -  Multivendor
dc9807a7-3d89-402d-84fe-6cb908d87f5b

I'm facing lots of issue
there is no documentation to setup mstore multivendor react-native cli, there is only documentation to setup mstore through expo

Issue 1:
settings page is not working 
Setting page giving error TypeError: y.languages.t is not a function

Issue 2:
There is no information to disable facebook button, chat setting and push notification.

Issue 3:
CeBuilder is not working i check package.json file is available everything fine in application folder but when i give path to cebuilder its return error cebuilder not compatible with this application like this.

Issue 4:
There is no documentation to setup wordpress admin panel according to this application actually like when i used your api featured everything work fine but when install wordpress i don't know how to set image as featured 

Issue 5:
after featured slider in application icon appears i want to how icons are working and how its connected with wordpress database mean how i these icon can work what sort of data i need to post on site so icon link work properly

**Comment by minhcasi** [comment]
@Hamzanisar - thank you for reporting, we will keep updating the document for the cli version, it's will be similar to the guide from https://facebook.github.io/react-native/docs/getting-started.html - please help to have a look to this guide in the meantime - very best!

**Comment by Hamzanisar** [comment]
what about other issues

**Comment by minhcasi** [comment]
@Hamzanisar - we have updated latest version for these fixing - let us know your checking - thank you!
