### ISSUE TITLE
[Fluxstore-1.5.1] - Bug with Search Function

### ISSUE THREAD

**Issue by Huysophanna** [inspireui/support#1123]
**1. My issue**
-> Bug with search function when typing words with **SPACE** in search box. For example "**long shirt**" (with a space in between).
Please release a fix as it is also an important features with a bug! 

**2. Screenshots**
<img width="1359" alt="Screen Shot 2019-09-27 at 9 57 10 PM" src="https://user-images.githubusercontent.com/17026862/65780172-5ed4be00-e173-11e9-98b5-3d682c5aab85.png">

3. My screenshot of the purchase product or my comment:
<img width="811" alt="Screen Shot 2019-09-27 at 6 10 18 PM" src="https://user-images.githubusercontent.com/17026862/65780205-7318bb00-e173-11e9-83a7-a6764386a70c.png">

**Comment by DrChrispoper** [comment]
A possibility is to use 

`var encodedName = Uri.encodeFull(name);`

To encode the spaces for URI uses.

**Comment by Huysophanna** [comment]
Still doesn't work! Besides the mistake with encode url, the **error is with the for-each-loop** in response.

**Comment by minhcasi** [comment]
@Huysophanna - thank you for reporting, we will investigate this feature as a high priority and keep an update - very best!

**Comment by minhtruong315** [comment]
@Huysophanna can you send me config.dart and config.json file via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/1123

**Comment by Huysophanna** [comment]
Done! By the way, I didn't change any config yet! It's a bug right from the start, even in your demo app in Appstore! You can try searching "long shirt" or something.

**Comment by minhcasi** [comment]
Fixed at latest 1.5.7 - thank you!
