### ISSUE TITLE
JSON format for products and categories MStore

### ISSUE THREAD

**Issue by mihaelp** [inspireui/support#1124]
Hello!
Please tell me the JSON format for displaying products / categories. I do not need to associate the application with WP.
I would be grateful if someone tells me in which place in the code the application interacts with the categories and products from WP.
Thank you!

**Comment by minhcasi** [comment]
Hi @mihaelp could you help to take the screenshot of the download page from https://codecanyon.net/downloads to verify your purchased - thanks

**Comment by mihaelp** [comment]
![20190928_192510](https://user-images.githubusercontent.com/22062898/65817912-0b6f7800-e226-11e9-9a55-21a9101a8b52.jpg)

**Comment by minhcasi** [comment]
@mihaelp - please check it from the Redux folder - https://tppr.me/VN76S

And from this api - https://github.com/inspireui/api-ecommerce - thanks

**Comment by mihaelp** [comment]
Hello!
There was a problem, a solution that I can find even on the forum.
Error: Unknown controller 'mstore_user'
Please tell me what to do?

[image: screenshotAtUploadCC_1570187575716.png]

вт, 1 окт. 2019 г. в 17:55, Minh Pham <notifications@github.com>:
