### ISSUE TITLE
[my-product] - Fluxstore pro

### ISSUE THREAD

**Issue by vpeace** [inspireui/support#1126]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue
It's taking a long time for building the .apk file from flutter build apk command and I'm not able to get a release build. All I am able to get is a debug build which has a size of 64 MB.
Please Look into this. The release folder is not getting created. Also if possible please provide me with a solution for updating the builds.. since I made the changes in the previous build and then a new update, so I have to do all my changes again. So if you could provide me with a better solution I'll be grateful. You mentioned a patch for updating in the release notes but I wasn't able to locate it in the readme.md file.
2. Screenshots

3. My screenshot of the purchase product or my comment:
![Screenshot 2019-09-28 at 7 46 01 AM](https://user-images.githubusercontent.com/16059464/65810138-12659e80-e1c4-11e9-9b5f-a5188bc54410.png)

3. Config files (optional)

**Comment by minhcasi** [comment]
Hi, please check the #7 guide by using patch file could be help - https://medium.com/@inspireui/announcing-fluxstore-1-5-950e0165cab8

Please check this detailed guide about apk generator - https://flutter.dev/docs/deployment/android

**Comment by vpeace** [comment]
Hi, I've installed the wordpress theme of mstore from here https://github.com/inspireui/mstore
However every link starts with mstore.local, which isn't the link where I have installed this> please could you help me out here

**Comment by minhcasi** [comment]
@vpeace  - this video will help - https://www.youtube.com/watch?v=CEyfZmzBMTw&t=1493s - we share the detail how to change to store.local - thank you!
