### ISSUE TITLE
[Mstore Pro] - CE Builder not working

### ISSUE THREAD

**Issue by PremiumPromotion** [inspireui/support#1127]
Hello,
We purchased MStore PRo and followed all steps, created also the secret keys in Woocommerce and asssigned them in CeBuilder 0.36. However the customize screen is not working, it's loading indefinetely and also the site is not communicating with the app, so that we cannot create the app nor in Android, nor in IOS.
I think it may be an API communication problem. Could you verify please?
Website: https://www.e-piesecamioane.ro (we also tried http without s in CE builder)
Thank you!
Best Regards,
Ionut Marcu
office@premiumpromotion.ro

![print-screen-cebuilder](https://user-images.githubusercontent.com/55909562/65813068-87db6a00-e1d8-11e9-977b-231afeda6d56.png)

**Comment by minhcasi** [comment]
@PremiumPromotion could you try to use the 0.35 or 0.36 release from https://github.com/inspireui/cebuilder/releases

**Comment by PremiumPromotion** [comment]
Hello,


Yes, i tried 0.35 version first, then 0.36 but same problem.







Ionut Marcu - Founder Premium Promotion


Google Ads Certified Partner


Digital Marketer


Mobile: +40722.799.100







On Sat, Sep 28, 2019 at 3:23 PM +0300, "Minh Pham" <notifications@github.com> wrote:












@PremiumPromotion could you try to use the 0.35 or 0.36 release from https://github.com/inspireui/cebuilder/releases

**Comment by minhcasi** [comment]
@PremiumPromotion - sorry for the issues, we just figure out the issue and will update Cebuilder in 1-2 days.

In the meantime please help to run it manually by using this guide - https://facebook.github.io/react-native/docs/getting-started.html - thank you!

**Comment by PremiumPromotion** [comment]
Hello, 


Ok, thank you, we'll wait for the Cebuilder update. 


Thank you. 


Best Regards,





Ionut Marcu - Founder Premium Promotion


Google Ads Certified Partner


Digital Marketer


Mobile: +40722.799.100







On Tue, Oct 1, 2019 at 3:28 PM +0300, "Minh Pham" <notifications@github.com> wrote:












@PremiumPromotion - sorry for the issues, we just figure out the issue and will update Cebuilder in 1-2 days.


In the meantime please help to run it manually by using this guide - https://facebook.github.io/react-native/docs/getting-started.html - thank you!

**Comment by PremiumPromotion** [comment]
Hello,




Unfortunately, Ce Builder blocks after saving values in customize section.


I tried with Expo but you may see in the attach that the app is loading, but categories and products not, it says no route.




I tried with e-piesecamioane.ro and also on another site, but same problem.


I think it is something related to Api.


It is working with e-piesecamioane.ro/wp-json/wc/v1 but not with v2 and if i put products after it generates error.


I tried to install rest api plugin even if i already configured keys in wc.


So could you please what to do?






















Thank you.





Ionut Marcu - Founder Premium Promotion


Google Ads Certified Partner


Digital Marketer


Mobile: +40722.799.100







On Tue, Oct 1, 2019 at 5:34 PM +0300, "Premium Promotion" <office@premiumpromotion.ro> wrote:










Hello, 


Ok, thank you, we'll wait for the Cebuilder update. 


Thank you. 


Best Regards,





Ionut Marcu - Founder Premium Promotion


Google Ads Certified Partner


Digital Marketer


Mobile: +40722.799.100







On Tue, Oct 1, 2019 at 3:28 PM +0300, "Minh Pham" <notifications@github.com> wrote:












@PremiumPromotion - sorry for the issues, we just figure out the issue and will update Cebuilder in 1-2 days.


In the meantime please help to run it manually by using this guide - https://facebook.github.io/react-native/docs/getting-started.html - thank you!

**Comment by concuacon** [comment]
@PremiumPromotion you can add my skype: pvtuan1707, I'll connect remotely to your desktop to check for you.

**Comment by concuacon** [comment]
Hello, @PremiumPromotion I have just released a new version of ceBuilder [0.38.0](https://github.com/inspireui/cebuilder/releases/tag/0.38.0) please delete the old CeBuilder and install the new version.
