### ISSUE TITLE
[ListApp] Problem with integration

### ISSUE THREAD

**Issue by ReneBenavides** [inspireui/support#113]
Required Info (please complete the following information):

Product: ListApp
Your Purchased Code: 872b84ee-73ae-49e6-8201-277d7c95c138

Description
the app crash when I click on any category

![whatsapp image 2018-12-17 at 17 16 25](https://user-images.githubusercontent.com/45953521/50122240-276ad580-0221-11e9-9d70-cbdff16eb578.jpeg)

**Comment by thangvo9x** [comment]
Thanks for your feedback. Send me your Config.

**Comment by ReneBenavides** [comment]
This is my config
[Config.js.zip](https://github.com/inspireui/support/files/2690732/Config.js.zip)

**Comment by thangvo9x** [comment]
Okie. I'll check & reply you ASAP. Thanks

**Comment by thangvo9x** [comment]
Try this source. let me know if it works.
https://we.tl/b-Lagc6Gq0SA
Thanks

**Comment by ReneBenavides** [comment]
Thanks for help, I will try it and inform you.
