### ISSUE TITLE
[Fluxstore] - Requesting features 

### ISSUE THREAD

**Issue by louissaad24** [inspireui/support#1130]
----Forcing the user to update the app
- Why this feature is important? Because if someone published the app and then discovered a bug in the app that can make the user experience bad, or a bug that let the user to take advantage of it ( for example coupons doesnt have restrictions in the app even if you put restrictions in woocommerce, so the user wont update the app and keep taking advantage of this bug) so we have to implement a way to force the user update the app.
- How will it work? i think you have to create a wordpress plugin that you insert in it the app version code, you can enable and disable version codes in the plugin, so when u disable a version code a screen will show in the app forcing the user to update the app with the disable version code.

----Monetization please add the option to choose between facebook or admob native banner.
- Why is it important? it can be a secondary revenue source.
- How will it work? We can choose between admob or facebook to monetize the app.

----Dynamic product detail layout.
- Why this feature is important? It will make the user experience more beautiful and professional.
- How will it work? In my opinion the best way to do it is to add a product variant lets say it will be called "Theme" it can be either "A" or "B" (or even more but lets just say 2 for now)  So lets say i have a T-shit product that has the product variant Theme set to A so when i click the product in the app it will open the product detail page design associated to A, and lets say i have a headphone 🎧 product that has the product variant Theme set to B so when i click the product in the app it will open the product detail page design associated to B.
That my opinion on how to do it, maybe you have a better way to do it!
These are some concepts on what i was saying. 
lets say they clucked on the t-shirt product that has the product variant Theme set to A:
![Screenshot_20190928-161327](https://user-images.githubusercontent.com/55917976/65817005-f3d6c600-e20a-11e9-8613-88eb509e15b7.jpg)
lets say they clicked on the headphones 🎧 that has the product variant Theme set to B:
![IMG_20190928_161741](https://user-images.githubusercontent.com/55917976/65817060-8b3c1900-e20b-11e9-8aa7-376318dd1bd1.jpg)

So my best suggestion to do is to let us create themes easily and associate them with the Theme product variant easily(For example tocreate a theme file that has all the functionality such as the cart and the back arrow button and we can customize all the rest!)

Here is my screenshot that proves that i bought the product!
![Screenshot_20190928-162135](https://user-images.githubusercontent.com/55917976/65817109-13222300-e20c-11e9-8fdf-07028e9dd5d0.jpg)

**Comment by minhcasi** [comment]
Thank you for the great features request, we will review and keep an update

**Comment by minhcasi** [comment]
Added more 2 difference Detail layout at 1.5.8 - https://tppr.me/UrPhR - https://tppr.me/II6We

Other features are still on the backlog

**Comment by louissaad24** [comment]
Amazing work guys, keep on going!

**Comment by minhcasi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [https://github.com/inspireui/support/issues/1130](https://trello.com/c/Q3TEcms6/1-https-githubcom-inspireui-support-issues-1130)

**Comment by minhcasi** [comment]
we are closing the ticket and move this ticket 'request feature' to our Trello board, still keep a status update  - thank you!
