### ISSUE TITLE
[fluxstore] - checkout and my account page error

### ISSUE THREAD

**Issue by attare026** [inspireui/support#1133]
1. My issue
I think I could properly configure can anyone help me how to fix this error.
when I press my account and check out then I will face like this error.

2. Screenshots
![Screenshot_2019-09-29-14-13-11-591_com inspireui fluxstore](https://user-images.githubusercontent.com/34741721/65829101-76bb5780-e2c3-11e9-8fc7-a1940e241bd1.jpg)

3. My screenshot of the purchased product or my comment:
<img width="811" alt="asdf" src="https://i.ibb.co/Nx1q7Cx/asdf.png">

**Comment by minhcasi** [comment]
@attare026 - could you help to zip the whole source or the config file to support@inspireui.com - we will help for checking?

Are you using the latest 1.5.1?

**Comment by minhtruong315** [comment]
@attare026 can you send me config.dart and config.json file via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/1133
