### ISSUE TITLE
Fluxstore -  I could not compile or run for Android, Still I have not tried for iOS but Android has many deprecation and old library that needs to be update

### ISSUE THREAD

**Issue by kamleshgorasiya** [inspireui/support#1134]
I have purchased Fluxstore from https://codecanyon.net/item/fluxstore-the-universal-woocommerce-magento-opencart-mobile-app-by-flutter-framework/24020929---------
I am your 132 order

1. My issue : I could not even compile the project successfully. here is the log.

Launching lib\main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Note: C:\Users\Logwin1\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore-0.12.9+4\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\Logwin1\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore-0.12.9+4\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: C:\Users\Logwin1\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\connectivity-0.4.4\android\src\main\java\io\flutter\plugins\connectivity\ConnectivityPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\Logwin1\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\flutter_webview_plugin-0.3.8\android\src\main\java\com\flutter_webview_plugin\WebviewManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: C:\Users\Logwin1\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\flutter_account_kit-0.7.0\android\src\main\java\com\peerwaya\flutteraccountkit\FlutterAccountKitPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: C:\Users\Logwin1\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\url_launcher-5.1.4\android\src\main\java\io\flutter\plugins\urllauncher\WebViewActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':cloud_firestore:lintClassPath'.
> Could not download lint-gradle.jar (com.android.tools.lint:lint-gradle:26.3.0)
   > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-gradle/26.3.0/lint-gradle-26.3.0.jar'.
      > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-gradle/26.3.0/lint-gradle-26.3.0.jar'.
         > dl.google.com
> Could not download lint.jar (com.android.tools.lint:lint:26.3.0)
   > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint/26.3.0/lint-26.3.0.jar'.
      > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint/26.3.0/lint-26.3.0.jar'.
         > dl.google.com
> Could not download lint-checks.jar (com.android.tools.lint:lint-checks:26.3.0)
   > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-checks/26.3.0/lint-checks-26.3.0.jar'.
      > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-checks/26.3.0/lint-checks-26.3.0.jar'.
         > dl.google.com
> Could not download lint-api.jar (com.android.tools.lint:lint-api:26.3.0)
   > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-api/26.3.0/lint-api-26.3.0.jar'.
      > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-api/26.3.0/lint-api-26.3.0.jar'.
         > dl.google.com
> Could not download intellij-core.jar (com.android.tools.external.com-intellij:intellij-core:26.3.0)
   > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/external/com-intellij/intellij-core/26.3.0/intellij-core-26.3.0.jar'.
      > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/external/com-intellij/intellij-core/26.3.0/intellij-core-26.3.0.jar'.
         > dl.google.com
> Could not download kotlin-compiler.jar (com.android.tools.external.com-intellij:kotlin-compiler:26.3.0)
   > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/external/com-intellij/kotlin-compiler/26.3.0/kotlin-compiler-26.3.0.jar'.
      > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/external/com-intellij/kotlin-compiler/26.3.0/kotlin-compiler-26.3.0.jar'.
         > dl.google.com
> Could not download uast.jar (com.android.tools.external.org-jetbrains:uast:26.3.0)
   > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/external/org-jetbrains/uast/26.3.0/uast-26.3.0.jar'.
      > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/external/org-jetbrains/uast/26.3.0/uast-26.3.0.jar'.
         > dl.google.com
> Could not download groovy-all.jar (org.codehaus.groovy:groovy-all:2.4.15)
   > Could not get resource 'https://jcenter.bintray.com/org/codehaus/groovy/groovy-all/2.4.15/groovy-all-2.4.15.jar'.
      > Could not HEAD 'https://jcenter.bintray.com/org/codehaus/groovy/groovy-all/2.4.15/groovy-all-2.4.15.jar'.
         > jcenter.bintray.com
> Could not download error_prone_annotations.jar (com.google.errorprone:error_prone_annotations:2.1.3)
   > Could not get resource 'https://jcenter.bintray.com/com/google/errorprone/error_prone_annotations/2.1.3/error_prone_annotations-2.1.3.jar'.
      > Could not GET 'https://jcenter.bintray.com/com/google/errorprone/error_prone_annotations/2.1.3/error_prone_annotations-2.1.3.jar'.
         > jcenter.bintray.com

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 15s
Finished with error: Gradle task assembleDebug failed with exit code 1

![image](https://user-images.githubusercontent.com/6419099/65833996-2a3c4000-e2f4-11e9-87d9-0757e709552e.png)

**Comment by minhcasi** [comment]
@kamleshgorasiya could i check if you could run the example "Test Drive" successful - https://flutter.dev/docs/get-started/test-drive ?

**Comment by minhtruong315** [comment]
@kamleshgorasiya can you add my skype: minhtruong315. i will help you check via teamviewer

**Comment by kamleshgorasiya** [comment]
Yes, Sure

**Comment by kamleshgorasiya** [comment]
Which one is yours?

![image](https://user-images.githubusercontent.com/6419099/65935433-b5bdea00-e436-11e9-8430-30a6ac531254.png)

**Comment by minhtruong315** [comment]
@kamleshgorasiya the first

**Comment by minhtruong315** [comment]
duplicate: https://github.com/inspireui/support/issues/1147
