### ISSUE TITLE
[ce-builder] - Beonews theme is not detecting.

### ISSUE THREAD

**Issue by cptiwari20** [inspireui/support#1139]
1. My issue
Unable to select the library
2. Screenshots
![image](https://user-images.githubusercontent.com/33618258/65900816-7959a200-e3d4-11e9-8b6d-cbd68358fa22.png)
3. My screenshot of the purchase product or my comment:

Item Title:
BeoNews Pro - React Native mobile app for Wordpress

Item URL:
https://codecanyon.net/item/beonews-react-native-mobile-app-for-wordpress/19186520

Item ID:
19186520

**Comment by minhcasi** [comment]
@cptiwari20  - note with checking, we will update you in 1-2 days - thank you!

**Comment by concuacon** [comment]
@cptiwari20 Your device needs an environment to run the project, follow link https://facebook.github.io/react-native/docs/getting-started
You can manually install by following these steps:

- npm install && react-native run-ios(ios device) or react-native run-android (android device)
