### ISSUE TITLE
[ListPro] How to connect app with my website?

### ISSUE THREAD

**Issue by embtelsolution** [inspireui/support#114]
**Mandatory Info (please complete the following information):**
 - Product: ListPro - Listing Directory React Native template - ListingPro WP Theme
 - Your Purchased Code: f7712720-bc09-43c5-84c0-79393d25c9b0

**Describe the issues**
I have run the source using expo but i'm not seeing listing from my website but some random listing. not sure from where it is coming.

**Comment by embtelsolution** [comment]
Questions 3: how to generate these?

consumerKey: 'ck_0e3ca960f308cf1a1a08a44bc090dd4744167d78',
    consumerSecret: 'cs_f64148bb849212eebbae70d2262e4e38a330bb59',

**Comment by embtelsolution** [comment]
Question 4: How to build an app for iOS?

I tried following the steps here -> https://inspireui.github.io/listpro/docs/delivery

But now sure where to run expo build:ios command.

**Comment by embtelsolution** [comment]
Question 5: After I login there it is not redirecting anywhere.

After I sign up it's not redirecting anywhere. :(

**Comment by thangvo9x** [comment]
Hi. you can connect to your website in Config.js file in Common folder.(Common/Config.js)
2. Change it in Common/IntroData
3. They are generated in your Website , WooCommerce->Setting->Advanced. and create it
4. you followed right link. in that link, there has a link for publish app to appStore/ gg play
5. Please update latest version, remove app and re-install it again.
