### ISSUE TITLE
[beonews] - Blank page after showing flashscreen iOS.

### ISSUE THREAD

**Issue by outlawcode** [inspireui/support#1140]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue
I have successfully built the app with xcode but when running simulator, after flashscreen, it showing the blank page.

2. Screenshots
https://i.postimg.cc/yN0w43Jf/Screen-Shot-2019-10-01-at-1-29-16-AM.png

3. My screenshot of the purchase product or my comment:
https://i.postimg.cc/xCw50tWM/Screen-Shot-2019-10-01-at-1-30-25-AM.png

3. Config files (optional)

**Comment by minhcasi** [comment]
@outlawcode - could you share the config file so that we could help for checking?

**Comment by outlawcode** [comment]
https://pastebin.com/CJrWz6Wk - App.js

https://pastebin.com/eQNif44W - AppConfig.json

**Comment by outlawcode** [comment]
Hello! 3 days passed!

**Comment by concuacon** [comment]
Hi @outlawcode Please download FBSDK save to path Documents/
https://drive.google.com/file/d/1sj-KQRzeSrpnvfhafgPTQgUhgO5eJhDn/view?usp=sharing
and try steps:
rm -rf node_modules/ && yarn cache clean && yarn && cd ios/ && rm -rf build/ && cd ../ && react-native run-ios
![Simulator Screen Shot - iPhone X - 2019-10-04 at 15 02 49](https://user-images.githubusercontent.com/11958061/66191367-5e2eb100-e6b8-11e9-85a5-fbe7ad125ff7.png)

**Comment by outlawcode** [comment]
Still same.

Can you teamviewer to help me?

**Comment by concuacon** [comment]
yes, sent me your teamviewer id & pass

**Comment by outlawcode** [comment]
1 120 776 053

7c4qt8

**Comment by concuacon** [comment]
Please check our documents: https://docs.inspireui.com/beonews/delivery/

**Comment by outlawcode** [comment]
So I need a paid Apple Developer Account $99?

**Comment by concuacon** [comment]
@outlawcode Yes, you need apple developer account

**Comment by outlawcode** [comment]
So, how to exclude the push notification?

**Comment by concuacon** [comment]
@outlawcode you can follow docs of onesignal: https://documentation.onesignal.com/docs/react-native-sdk-setup

**Comment by outlawcode** [comment]
Can you please guide me? 
Or tell me which file need to delete or something?
Sorry i'm not a coder

**Comment by concuacon** [comment]
@outlawcode You can read their docs more carefully, it's easy to understand and also includes illustrations: https://documentation.onesignal.com/docs/react-native-sdk-setup
or you can watch this playlist video: https://www.youtube.com/watch?v=a6IbOomdRjI&list=PLhPm0UV2CvUAVBR74-AbUzYcEfAHNOajX
