### ISSUE TITLE
[my-product] - 

### ISSUE THREAD

**Issue by spss20** [inspireui/support#1142]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: When I click on add to cart button , it redirects me to website product page rather then adding that particular product in cart. Also login for my woocommerce in app is not working, intead it is working on my website, but in app it says please check your id or password again. Whats happening?

2. Screenshots

3. My screenshot of the purchase product or my comment:![Screenshot (96)](https://user-images.githubusercontent.com/29224720/65937800-988d1980-e43e-11e9-88ca-2523167f38ef.png)

3. Config files (optional)

**Comment by minhtruong315** [comment]
@spss20 did you install mstore api plugin in your website?

**Comment by spss20** [comment]
@minhtruong315 YES SIR, I HAVE INSTALLED PERFECTLY ON MY WOOCOMMERCE

**Comment by minhtruong315** [comment]
@spss20 can you send me info to login admin site, config.dart and config.json file via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/1142
