### ISSUE TITLE
EvaStore Shopify App error

### ISSUE THREAD

**Issue by ameeronline** [inspireui/support#1143]
Hello,
I need help with Eva Store Application.
I purchased a Licence from Envato for Development Purpose. I did setup test store on Shopify and when i got to checkout screen it shows me an error.

Checkout System Disabled: Merchant trial expired.

https://imgur.com/OSB235f

The error is same for your Play Store App demo and even if i changed AppConfig.json file according my shopify Store app credentials. Still the same error. Can I get help?

**Comment by minhcasi** [comment]
Hi, this is not a bug, you can contact Shopify Admin to renews your Merchant and Testing account - thanks
