### ISSUE TITLE
[my-product] - 

### ISSUE THREAD

**Issue by T-venom** [inspireui/support#1144]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue
There are some missing plugins, and I need a detailed step by step installation, please

2. Screenshots
![Screenshot (1)_LI](https://user-images.githubusercontent.com/55971558/65939559-9323d500-e426-11e9-9117-0763f1662c08.jpg)

3. My screenshot of the purchase product or my comment:
![Screenshot (2)](https://user-images.githubusercontent.com/55971558/65939577-9dde6a00-e426-11e9-9c6f-9acd938f0e84.png)
![Screenshot (3)](https://user-images.githubusercontent.com/55971558/65939585-a5057800-e426-11e9-9e80-5beafa7ac60a.png)

3. Config files (optional)

**Comment by concuacon** [comment]
@T-venom Please you try steps install to environment to run project:

- Install chocolatey: https://chocolatey.org/install

- Install Nodejs: https://nodejs.org/en/download/

- Install Yarn: https://yarnpkg.com/lang/en/docs/install/#windows-stable

- Install React Native: https://facebook.github.io/react-native/docs/getting-started

**Comment by T-venom** [comment]
And I added the plug-ins on WordPress and I can't get the JSON. API and I
most of the plugins have issues.

**Comment by concuacon** [comment]
have you active JSON API?
