### ISSUE TITLE
[Fluxstore] login and register error, Overflowed error

### ISSUE THREAD

**Issue by immortal-kid** [inspireui/support#1146]
Hello, I purchased and run the app as it is and it worked, i connected my woocommerce store and run, i got few errors.
(Comment Screenshot---> http://prntscr.com/pd991u)

1. I tried to register and i get this error, i tried to login with an existing account, i it showed me this error (Username and password is correct, still i get that error) Screenshot—> http://prntscr.com/pd81t8

2. i get this overflowed error, for frontTitle sometimes it may be lengthy, is there any way to fix this? i also got that in product page while selecting cart number Screenshot--> http://prntscr.com/pd828z

3.  i don’t want that layouts option in filters and I want to show 3 columns view as the default layout for all product lists. how to do that? Screenshot--> http://prntscr.com/pd82n9

**Comment by minhtruong315** [comment]
@immortal-kid did you install mstore api plugin in website?

**Comment by immortal-kid** [comment]
yes i have installed

**Comment by minhtruong315** [comment]
can you send me admin account via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/1146

**Comment by immortal-kid** [comment]
sent u a mail

**Comment by minhtruong315** [comment]
i dont see. what is your email?

**Comment by immortal-kid** [comment]
i replied to the email which i already received from you, anirudh.5bs@gmail.com

**Comment by minhtruong315** [comment]
i dont see any email with subject #1146

**Comment by immortal-kid** [comment]
see now
