### ISSUE TITLE
FluxStore -  I am getting OpenGL issue in some android devices and in some device it working

### ISSUE THREAD

**Issue by kamleshgorasiya** [inspireui/support#1147]
1. My issue
I am facing Opel GL issue, I don't know why It not working
2. Screenshots
![image](https://user-images.githubusercontent.com/6419099/65946912-cb420c80-e454-11e9-97af-59866996d105.png)

![image](https://user-images.githubusercontent.com/6419099/65946852-ac437a80-e454-11e9-9671-78f864856b99.png)

**Comment by minhtruong315** [comment]
@kamleshgorasiya which devices you can't run app?

**Comment by kamleshgorasiya** [comment]
I am facing an issue with Nokia 2.1 OS version Android P

**Comment by minhcasi** [comment]
@kamleshgorasiya - this is not a bug from the app, please try to use other Android simulators as the Nokida 2.1 simulator could be an issues - thank you!

Our suggestion the Simulator OS from SamSung or Pixel
