### ISSUE TITLE
[flux-store] -loading too slow

### ISSUE THREAD

**Issue by abdallahsaad200** [inspireui/support#1149]
hello recently we have purchased flux store and it working perfectly but there is one issue it loads slowly so it takes alot of time  to show the catagory section 

down bellow is some screenshots 
![Screenshot_20191001-125820](https://user-images.githubusercontent.com/41394626/65953031-c62c8f80-e44b-11e9-83c0-6dde1b36558c.png)

proof of purchasing 
![proof](https://user-images.githubusercontent.com/41394626/65953066-e0666d80-e44b-11e9-8282-cbf6a78ef32e.JPG)

**Comment by minhcasi** [comment]
@abdallahsaad200 - could i confirm it is using latest 1.5.1? The loading speed will also depend on your Website Rest API that take a long time to return the Category API

**Comment by minhcasi** [comment]
There is know issue regarding to mstore - api, please update https://wordpress.org/plugins/mstore-api/ to latest version
