### ISSUE TITLE
Error while building

### ISSUE THREAD

**Issue by mustafamsy** [inspireui/support#115]
**Mandatory Info (please complete the following information):**
 - Product: BeoNews Pro - React Native mobile app for Wordpress
 - Your Purchased Code: 2a6e0632-d77f-4f7a-bb66-b1d5aa869ccd

**Describe the issues**
When I build on iOS using xcode, I get the following error:
error: Build input file cannot be found: '/Users/soso/Documents/my Apps/_Apps/alnoorclub/use this/BeoNews.2.9.0/beonews-pro/node_modules/react-native/third-party/double-conversion-1.1.6/src/fixed-dtoa.cc'

**Screenshots**
https://ibb.co/f14QL68

**Additional context**
I tried the solution given here: https://beonews.inspireui.com/faq-and-troubleshooting#fix-cfbundleidentifier-does-not-exist
But it did not work.

**Comment by levi-beers** [comment]
Follow [this fix](https://github.com/inspireui/support/issues/38#issuecomment-441363876) from @minhcasi

**Comment by mustafamsy** [comment]
@levi-beers Thanks! Solved
