### ISSUE TITLE
[mstore expo] - error to register

### ISSUE THREAD

**Issue by edmi14** [inspireui/support#1150]
![Screenshot_20191001-063525](https://user-images.githubusercontent.com/28486719/65955419-1852be00-e416-11e9-8a7b-3b58daff96b0.png)
When you hit the button sing up The app returns to the splash screen and reopens the app but does not register

**Comment by minhtruong315** [comment]
@edmi14 can you take me screenshot purchase code in codecany?

**Comment by edmi14** [comment]
![Screenshot_2019-10-02 Downloads CodeCanyon](https://user-images.githubusercontent.com/28486719/66079147-8049f700-e531-11e9-935d-2026e7640072.png)

**Comment by minhtruong315** [comment]
send info to login to admin site, AppConfig.json and config.js via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/1150

**Comment by minhtruong315** [comment]
we have spent a half day but could not figure out the issue on this website as could be some conflict plugin or cache issues, please try to using this pre-config site from this link - https://github.com/inspireui/mstore

**Comment by edmi14** [comment]
I have that warning when I upload the app to apple store

Dear Developer,

We identified one or more issues with a recent delivery for your app,
"Tuttis Pizza" 3.6.0 (1). Your delivery was successful, but you may wish to
correct the following issues in your next delivery:

*ITMS-90809: Deprecated API Usage* - Apple will stop accepting submissions
of apps that use UIWebView APIs . See
https://developer.apple.com/documentation/uikit/uiwebview for more
information.

After you’ve corrected the issues, you can use Xcode or Application Loader
to upload a new binary to App Store Connect.

**Comment by minhtruong315** [comment]
@edmi14 it's only warning, You try to submit. I think it will be passed by apple
