### ISSUE TITLE
[fluxstore - homepage customization 

### ISSUE THREAD

**Issue by abdallahsaad200** [inspireui/support#1151]
hello the page is not changing  the banner images 

proof pic
![proof](https://user-images.githubusercontent.com/41394626/65962381-3a256280-e461-11e9-933d-c622558ace2b.JPG)

config file 
[common.zip](https://github.com/inspireui/support/files/3676187/common.zip)

**Comment by minhcasi** [comment]
Hi, could you share your whole screenshot include the username, as we could not verify your purchase? Thank you!
