### ISSUE TITLE
[Fluxstore] - Top categories icons didn't translate to arabic, and new warning shown

### ISSUE THREAD

**Issue by obadaKraishan** [inspireui/support#1155]
Hello,

In my app when i switch between the languages the top category icons text didn't change even if i change the screen and get back to it, and also new waning is shown:

![WhatsApp Image 2019-09-30 at 6 04 56 PM](https://user-images.githubusercontent.com/28910488/66024502-b8831280-e4fc-11e9-8968-62629e1cd27e.jpeg)

Warning: “setCurrentScreen cannot be called with the same class and name”

**Comment by minhcasi** [comment]
@obadaKraishan - could you share your config file from common folder - thanks

**Comment by obadaKraishan** [comment]
Sure..

[config.json.zip](https://github.com/inspireui/support/files/3680205/config.json.zip)

**Comment by minhtruong315** [comment]
@obadaKraishan pls send config.dart file

**Comment by obadaKraishan** [comment]
Yes i used WPML in my website and all categories are translated and asynchronous.

**Comment by minhtruong315** [comment]
can you send me config.dart file

**Comment by obadaKraishan** [comment]
Sure..

[config.dart.zip](https://github.com/inspireui/support/files/3680482/config.dart.zip)

**Comment by obadaKraishan** [comment]
Please any update?

**Comment by obadaKraishan** [comment]
any update!

**Comment by minhtruong315** [comment]
you can change locale value in models/app.dart
String locale = "ar";

**Comment by minhtruong315** [comment]
![Simulator Screen Shot - iPhone 11 Pro - 2019-10-03 at 12 27 08](https://user-images.githubusercontent.com/10402500/66101543-6cf26680-e5d9-11e9-8569-7b3af5751661.png)

[config.json.zip](https://github.com/inspireui/support/files/3684575/config.json.zip)
