### ISSUE TITLE
[mstore multi vender]i have problem in login ... the app is login me only as wonder... even i try with user i'd...

### ISSUE THREAD

**Issue by ZamanGoraya** [inspireui/support#1157]
![Mstore multi vendor](https://user-images.githubusercontent.com/52818458/66105973-35ce8600-e5d6-11e9-864a-afa39e0b3993.PNG)

**Comment by ZamanGoraya** [comment]
i am an employee and my boss bought it...

**Comment by ZamanGoraya** [comment]
![tricells chat](https://user-images.githubusercontent.com/52818458/66106267-dfae1280-e5d6-11e9-9d54-26c255f2d621.PNG)

**Comment by minhcasi** [comment]
Duplicate of #1153

**Comment by ZamanGoraya** [comment]
this is an other problem dear...!

**Comment by ZamanGoraya** [comment]
this is an other problem dear...
