### ISSUE TITLE
[BeoNews] Error while clicking on Featured/Sticky post

### ISSUE THREAD

**Issue by mustafamsy** [inspireui/support#116]
Mandatory Info (please complete the following information):

Product: BeoNews Pro - React Native mobile app for Wordpress
Your Purchased Code: 2a6e0632-d77f-4f7a-bb66-b1d5aa869ccd

**Describe the issues**
When I click on the featured post. I get the following error:
TypeError: undefined is not a function (near '...items.map...')

This error is located at:
    in Indicator (at HeaderDetail/index.js:20)
    in RCTView (at View.js:44)
    in HeaderDetail (at PostDetail/index.js:120)
    in RCTView (at View.js:44)
    in PostDetail (created by Connect(PostDetail))
    in Connect(PostDetail) (at PostDetailScreen.js:72)
    in PostDetailScreen (at SceneView.js:9)
    in SceneView (at createTabNavigator.js:10)
    in RCTView (at View.js:44)
    in RCTView (at View.js:44)
    in ResourceSavingScene (at createBottomTabNavigator.js:76)
    in RCTView (at View.js:44)
    in RCTView (at View.js:44)
    in TabNavigationView (at createTabNavigator.js:140)
    in NavigationView (at createNavigator.js:59)
    in Navigator (at createNavigationContainer.js:376)
    in NavigationContainer (at RootRouter.js:147)
    in RCTView (at View.js:44)
    in RCTSafeAreaView (at SafeAreaView.ios.js:35)
    in SafeAreaView (at RootRouter.js:142)
    in RCTView (at View.js:44)
    in AnimatedComponent (at react-native-drawer/index.js:600)
    in RCTView (at View.js:44)
    in Drawer (at MenuOverlay.js:37)
    in MenuOverlay (at RootRouter.js:202)
    in RootRouter (created by Connect(RootRouter))
    in Connect(RootRouter) (at beonews-pro/index.js:60)
    in PersistGate (at beonews-pro/index.js:59)
    in Provider (at beonews-pro/index.js:58)
    in beonews (at renderApplication.js:34)
    in RCTView (at View.js:44)
    in RCTView (at View.js:44)
    in AppContainer (at renderApplication.js:33)

render
    index.bundle?platform=ios&dev=true&minify=false:207798:52
finishClassComponent
    index.bundle?platform=ios&dev=true&minify=false:19054:43
performUnitOfWork
    index.bundle?platform=ios&dev=true&minify=false:21722:27
workLoop
    index.bundle?platform=ios&dev=true&minify=false:21754:47
renderRoot
    index.bundle?platform=ios&dev=true&minify=false:21817:21
performWorkOnRoot
    index.bundle?platform=ios&dev=true&minify=false:22508:23
performWork
    index.bundle?platform=ios&dev=true&minify=false:22432:30
performSyncWork
    index.bundle?platform=ios&dev=true&minify=false:22407:20
requestWork
    index.bundle?platform=ios&dev=true&minify=false:22305:26
scheduleWork
    index.bundle?platform=ios&dev=true&minify=false:22165:22
enqueueSetState
    index.bundle?platform=ios&dev=true&minify=false:17270:23
setState
    index.bundle?platform=ios&dev=true&minify=false:2685:37
<unknown>
    index.bundle?platform=ios&dev=true&minify=false:190525:26
processNext
    index.bundle?platform=ios&dev=true&minify=false:44739:19
_processUpdate
    index.bundle?platform=ios&dev=true&minify=false:44639:31
_callTimer
    index.bundle?platform=ios&dev=true&minify=false:25625:17
_callImmediatesPass
    index.bundle?platform=ios&dev=true&minify=false:25661:19
callImmediates
    index.bundle?platform=ios&dev=true&minify=false:25880:33
__callImmediates
    index.bundle?platform=ios&dev=true&minify=false:8138:35
<unknown>
    index.bundle?platform=ios&dev=true&minify=false:7975:34
__guard
    index.bundle?platform=ios&dev=true&minify=false:8121:15
flushedQueue
    index.bundle?platform=ios&dev=true&minify=false:7974:21

**Screenshots**
n/a

**Additional context**
n/a

**Comment by mustafamsy** [comment]
Any reason why this is happening?

**Comment by mustafamsy** [comment]
`/** @format */

import Constants from './Constants'

export default {
  /**
   * There are so many choices from the marketplace mobile app, we thank you for choosing us and purchased the BeoNews products, please follow the step bellow to quickly set up your app
   * The detail document from: https://beonews.inspireui.com
   *
   * Step 1: Change your Wordpress site URL
   * Please make sure you have install all the Wordpress plugins - https://beonews.inspireui.com/step-2-installing-wordpress.html
   * On Mac OS, you need to create ~/Documents/FacebookSDK - https://beonews.inspireui.com/beonews-setup.html
   */
  URL: {
    root: 'https://website.net',
  },

  /**
   * Step 2: config image and default layout post
   * HorizonLayout: show the horizontal layout config, show as the default homepage
   *    - Tags: the tag ids from Wordpress blog, it could be set as array [x, x...]
   *    - Categories: the category ids, , it could be set as array [x, x...]
   *    - row: the number of row support on the list, default is one row
   *    - paging: blog per page from swiping, default is false
   *    - layout: support 8 kind of layo Luts: banner, twoColumn, threeColumn, threeColumnHigh, list, listRight, card, flexColumn
   *      (flexColumn is flexible column layout that you can config both width & height)
   * Banner: option to show the banner home page, default visible is true
   * AdvanceLayout: mix layout config for AdvanceMode: card, column, list, banner, twoColumn, threeColumn, listRight
   */
  //
  HorizonLayout: [
    { tags: [19,20,21,22,25,26,54], paging: true, layout: Constants.Layout.column },
    {
      name: 'أخبار',
      categories: [1],
      paging: false,
      layout: Constants.Layout.list,
    },
    {
      name: 'الأخبار الاجتماعية',
      categories: [52],
      paging: false,
      //row: 3,
      layout: Constants.Layout.list,
    },
    {
      name: 'الإعلانات',
      categories: [53],
      paging: true,
      layout: Constants.Layout.list,
    },
    {
      name: 'الصور',
      categories: [43],
      layout: Constants.Layout.twoColumn,
      width: 120,
      height: 250,
    },
    {
      name: 'الفيديو',
      categories: [44],
      paging: true,
      //row: 2,
      layout: Constants.Layout.banner,
    },
  ],
  Banner: {
    visible: true,
    sticky: true,
    tag: [],
    categories: [],
  },
  // The advance layout
  AdvanceLayout: [
    Constants.Layout.list,
    Constants.Layout.list,
    Constants.Layout.list,
    Constants.Layout.list,
    Constants.Layout.list,
  ],

  /**
   * Step 3: Advance config
   * CategoryVideo: config the category id for video page
   *
   * */
  // Category video id from the menu
  CategoryVideo: 44,

  imageCategories: {
    news: require('@images/category/cate1.jpg'),
    photos: require('@images/category/cate2.jpg'),
    videos: require('@images/category/cate3.jpg'),
    community: require('@images/category/cate4.jpg'),
    advs: require('@images/category/cate5.jpg'),
  },

  // Custom page from left menu side
  CustomPages: {
    contact_id: 1646,
    aboutus_id: 760,
  },

  // config for Firebase, use to sync user data across device and favorite post
  Firebase: {
    apiKey: 'xxxxx-xxxxx',
    authDomain: 'xxxxx-xxxxx.firebaseio.com',
    databaseURL: 'https://xxxxx-xxxxx.firebaseio.com',
    storageBucket: 'xxxxx-xxxxx.appspot.com',
    messagingSenderId: 'xxxxx',
    readlaterTable: 'list_readlater',
  },

  // config for log in by Facebook
  Facebook: {
    showAds: false,
    adPlacementID: '',
    logInID: 'xxxxx',
    sizeAds: 'standard', // standard, large
  },

  // config for log in by Google
  Google: {
    analyticId: 'UA-xxxxx-1',
    androidClientId:
      'xxxxx-xxxxx.apps.googleusercontent.com',
    iosClientId:
      'xxxxx-xxxxx.apps.googleusercontent.com',
  },

  // config for log in by Admob
  AdMob: {
    visible: false,
    deviceID: 'pub-xxxxx',
    unitID: 'ca-app-pub-xxxxx/9145196933',
    unitInterstitial: 'ca-app-pub-xxxxx/xxxxx',
    isShowInterstital: true,
  },

  // tab animate
  tabBarAnimate: Constants.Animate.zoomIn,

  // config default for left menu
  LeftMenuStyle: Constants.LeftMenu.small,

  notification: {
    AppId: 'xxxxx-xxxxx-xxxxx-xxxxx-xxxxx',
    NewAppId: 'xxxxx-xxxxx-xxxxx-xxxxx-xxxxx',
  },

  OneSignal: {
    appId: 'xxxxxx-xxxxx-xxxxx-xxxxx-xxxxx'
  },

  // update 18 May
  // showLayoutButton: Ability to show/hide the switch layout button at homescreen
  // homeLayout: default homeLayout UI: Constants.Layout.mansory, Constants.Layout.horizontal
  // showSwitchCategory: show the switch button on categories page
  showLayoutButton: false,
  homeLayout: Constants.Layout.list,
  showSwitchCategory: false,

  // update 18 Sep 
  showAppIntro: true,
  intro: [
    {
      title: 'text text text text text',
      description: 'text text text text text text text text',
      backgroundColor: '#D5E8ED',
      source: require('@images/lottie/loading.json'),
      button: "التالي"
    }, {
      title: 'text',
      description: 'text text text text text text text',
      backgroundColor: '#D6D7DD',
      source: require('@images/lottie/newspaper_animation.json'),
      button: "التالي"
    }, {
      title: 'text',
      description: 'text text text text text text text',
      backgroundColor: '#FFF',
      source: require('@images/lottie/check_animation.json'),
      button: "التالي"
    }, {
      title: 'text',
      description: 'text text texttexttext',
      backgroundColor: '#D6D7DD',
      source: require('@images/lottie/notification.json'),
      button: "التالي"
    }
  ],
}
`

**Comment by mustafamsy** [comment]
@minhcasi any thoughts?

**Comment by minhcasi** [comment]
Hi, the problem on your config the root.url is not correct that it could not load the data to populate from the homepage.

Please make sure the website URL is working.
 
Thank you!

**Comment by mustafamsy** [comment]
You should be able to know that the app works. I just mentioned that the app fails when pressing the featured/sticky post in iOS App. 

I replaced the website URL intentionally for confidentiality reason with dummy website. The app works fine but as I mentioned, the error is only when I press the sticky post in iOS. I hope you understand there is no issue with website URL.

**Comment by minhcasi** [comment]
Fixed on v2.9.2 - thank you!
