### ISSUE TITLE
[Mstore] - Coupons not working

### ISSUE THREAD

**Issue by ItisAhsan** [inspireui/support#1160]
1. My issue : 
Coupon is not working correctly. It displays on user end but it doesn't show discount at the admin panel. Please check and help it's urgent.

2. Screenshots
![Screenshot (6)](https://user-images.githubusercontent.com/12572962/66121970-f44ed280-e5f7-11e9-8579-4d3097bfcbd1.png)
![Screenshot_1570099325](https://user-images.githubusercontent.com/12572962/66121998-06c90c00-e5f8-11e9-990b-b35841a77ddd.png)
![Screenshot_1570099330](https://user-images.githubusercontent.com/12572962/66121999-0761a280-e5f8-11e9-896c-ec27c0f1909d.png)

3. Config files sent to support@inspireui.com

**Comment by ItisAhsan** [comment]
![image](https://user-images.githubusercontent.com/12572962/66122064-3710aa80-e5f8-11e9-8673-e82e15367fe6.png)
proof of purchase

**Comment by minhcasi** [comment]
@ItisAhsan  - please try update the mstore-api to latest 1.3.3 to fix this issue - https://wordpress.org/plugins/mstore-api/ - thank you!

**Comment by ItisAhsan** [comment]
nope updating the plugin didn't help. I have sent you the credentials...

**Comment by minhcasi** [comment]
fixed on 3.9.6 - we will release soon

**Comment by emiliopi** [comment]
I have the same error and it dosent work on 3.9.6
