### ISSUE TITLE
[fluxstore] - splashscreen and other overflow issue

### ISSUE THREAD

**Issue by immortal-kid** [inspireui/support#1161]
1. I changed the splash screen flr line to png file line, but every time when I open the app this blue screen interrupts first and then shows splashscreen. (sent a video to the mail)

2. After logged in I clicked on rate me button, I got this overflowed error again. http://prntscr.com/pebfe1 and those buttons were not working and not visible properly

3. How to change the default preloading symbol to simply circle loading?

4. How to make the slider takes to a particular product? Because most of the time we give offers for particular products and put the banner in slider or banner somewhere in homescreen, is there any way to put particular product on homescreen or link slider by product id?

5. how to add text between these layouts in homescreen (detailed screenshot is attached in mail)

**Comment by immortal-kid** [comment]
(Email with attachments sent with subject #1161 along with my purchase code)

**Comment by minhtruong315** [comment]
1. I will check it
2 The rate function only work on google play, you can test it in debug mode
3. you can change kLoadingWidget in common/constants.dart
4. 5. You can update code in widgets/home/index.dart

**Comment by immortal-kid** [comment]
4,5. I saw the documentation, it is never mentioned on adding products based on product it. Also sliders are linked to categories. I asked how to link it to particular product? You told to edit in widgets/home/index.dart i dont understand where to edit exactly? What to add?

**Comment by minhtruong315** [comment]
Fluxstore only support show products base on category, not productID, if you want to show products base on productID, you must code more features it.

**Comment by immortal-kid** [comment]
and what about splash screen issue? did u look at it?

**Comment by immortal-kid** [comment]
ANY UPDATE ON SPLASH SCREEN ISSUE? DID U CHECK THE MAIL?

**Comment by minhcasi** [comment]
@immortal-kid - confirm blue splash screen is a bug - we will fix on next release - thanks

**Comment by immortal-kid** [comment]
Thanks for the response, i have not yet uploaded my app on playstore yet, shipping option issue and splashscreen bug is stopping me. can u please release the update soon. ?

**Comment by minhtruong315** [comment]
we are publish updates. it will fix your issues. pls wait next update

**Comment by immortal-kid** [comment]
splashscreen bug not fixed in 1.5.5c
