### ISSUE TITLE
[my-product] - fluxstore woocommerce

### ISSUE THREAD

**Issue by Therocky20** [inspireui/support#1162]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue
HI i have problem with displaying products.  Error: FormatException: Unexpected character (at character 1): <br />
2. Screenshots
i can give you my purchase code. i prefer skype  or teamviwer support. my email is ilascum@ymail.com
3. My screenshot of the purchase product or my comment:

3. Config files (optional)

**Comment by Therocky20** [comment]
![themeforestfluxstore](https://user-images.githubusercontent.com/54363592/66195350-b81e7f00-e696-11e9-8c4b-63536065e4d5.jpg)
here is my license. Please add me on skype , add info@resmedia.it on skype

**Comment by minhcasi** [comment]
@Therocky20 - could you attach your config file here so that we could check the issue first - thanks

**Comment by Therocky20** [comment]
[common.zip](https://github.com/inspireui/support/files/3689914/common.zip)

Here it is

**Comment by Therocky20** [comment]
Error: FormatException: Unexpected character (at character 1)
I/flutter ( 5784): <br />
I/flutter ( 5784): ^  

this is the error i can't see the products i have setted the id of the categories but no products is shown. when i go into one of the category i get that error

**Comment by minhtruong315** [comment]
@Therocky20 can you try to turn off the warning in php.ini or disable debug mode in wp-config.php.

<img width="986" alt="Screen Shot 2019-10-07 at 8 12 00 AM" src="https://user-images.githubusercontent.com/10402500/66279212-46367780-e8da-11e9-8515-c267982d888c.png">

**Comment by Therocky20** [comment]
Sure i do it

**Comment by Therocky20** [comment]
I have disabled it but the problem persist

**Comment by Therocky20** [comment]
If you want we can connect with teamviwer and let check you also the wp site but i have disabled it in the wp-config

**Comment by minhtruong315** [comment]
add my skype: minhtruong315

**Comment by Chizinski** [comment]
Kindly Update the solution here

**Comment by Therocky20** [comment]
Hi just download and replace this plugin https://github.com/inspireui/mstore-checkout
