### ISSUE TITLE
[fluxstore] - shipping zones issue

### ISSUE THREAD

**Issue by immortal-kid** [inspireui/support#1163]
1. I have added zones in woocommerce shipping settings. i have limited my store to certain pincodes. Only users in those pincodes can place orders.  I have also set flat rates for some pincodes among them. but fluxstore is showing all options by default globally and its not even taking our zones not even showing our flat rates.

2. After setting up the zones, i'm getting some error in checkout screen.

**Comment by immortal-kid** [comment]
sent u mail with all details and screenshot with subject #1163

**Comment by minhcasi** [comment]
@immortal-kid - the multi-shipping zone is not available on the current version, we have marked as Feature Request for further investigating - thanks

**Comment by immortal-kid** [comment]
Ok, but I've limited my store to some pincodes only, but app is accepting any random pincodes and letting place order. Atleast you could look at this.

Also I've set flat rate 30₹ but app is not even showing this while showing total.

**Comment by immortal-kid** [comment]
Untill this get fixed i can't launch my app. Because I've set flatrate based on pincodes, if that's not working in the app it will be very difficult for us. So is there any way to make checkout page webview with user logged in only?

**Comment by immortal-kid** [comment]
when are u giving the next update fixing shipping zones?
