### ISSUE TITLE
[MStore] Wordpress setting

### ISSUE THREAD

**Issue by abderrahimcloudme** [inspireui/support#1164]
![image](https://user-images.githubusercontent.com/51796320/66141070-0a11c700-e5fb-11e9-94f6-79ce094e994d.png)

When I try to register, I get this error.
I didn’t find MstoreUser in the wordpress setting.

![image](https://user-images.githubusercontent.com/51796320/66140716-80fa9000-e5fa-11e9-9610-bb013609065b.png)

**Comment by minhcasi** [comment]
Could i confirm you are using latest api from - https://wordpress.org/plugins/mstore-api/

**Comment by abderrahimcloudme** [comment]
Hi,
Yes i used the latest version, I uninstall all the plugin from wordpress
and i import them from this exemple (https://github.com/inspireui/mstore/) and
it works.
but now i get this error:

{"status":"error","error":"SSL is not enabled. Either use _https_ or
provide 'insecure' var as insecure=cool to confirm you want to use
http protocol."}

even if i'am using ssl.

Thanks a lot.

**Comment by minhcasi** [comment]
fixed on 3.9.6 - we will release soon in 1-2 days - thank you!

**Comment by minhcasi** [comment]
updated 3.9.6 - pls update the latest plugin https://wordpress.org/plugins/mstore-api/  and enable the option from the Setting / Json API - https://docs.inspireui.com/mstore/wordpress-setting/#enable-the-rest-api-controller-1

- thanks
