### ISSUE TITLE
[ListApp] - Does not display chat option

### ISSUE THREAD

**Issue by hungnguyen9276** [inspireui/support#1166]
Hi,
I configed firebase by followed this https://docs.inspireui.com/listapp/firebase/. I logined however I see no chat option when I enter a listing. how can I fix it?

**Comment by minhcasi** [comment]
pls provide the detail info: your purchase code, screenshot issue.. and open ticket again - thanks

**Comment by hungnguyen9276** [comment]
Here is my purchase code: 2c21e8c4-d8cc-4226-aeba-68cd81289fe6
<img width="306" alt="Screen Shot 2019-10-04 at 17 53 07" src="https://user-images.githubusercontent.com/25025251/66202428-eec4bb80-e6cf-11e9-8383-9417b325e730.png">
