### ISSUE TITLE
[Fluxstore] - Failed register with email

### ISSUE THREAD

**Issue by kazhuyo** [inspireui/support#1167]
1. My issue
I'm trying to register with email, but get this error 

2. Screenshots
<img width="1440" alt="Screen Shot 2019-10-04 at 11 19 16 AM" src="https://user-images.githubusercontent.com/1844792/66180972-2b28f500-e699-11e9-8d15-c1c536cd297a.png">

3. My screenshot of the purchase product or my comment:
<img width="1212" alt="Screen Shot 2019-10-03 at 3 39 09 PM" src="https://user-images.githubusercontent.com/1844792/66180991-3b40d480-e699-11e9-8a07-5aa2b6bf427d.png">

3. Config files (optional)
this line configuration in config.dart

> const serverConfig = {
>   "type": "woo",
>   "url": "http://store.core.id",
>   "consumerKey": "ck_732a6367ea1bffb90c0348a3eea08bf85a47284e",
>   "consumerSecret": "cs_8a5645e1003a6ec56e8255ebeb46b1d7bf822f90",
>   "blog": "http://store.core.id/",
>   "forgetPassword": "http://store.core.id/wp-login.php?action=lostpassword"
> };
>

**Comment by minhtruong315** [comment]
@kazhuyo can you change createUser function in services/woo_commerce.dart
```
 /// Create a New User
  @override
  Future<User> createUser({firstName, lastName, username, password}) async {
    try {
      String niceName = firstName +" "+ lastName;
      var nonce = await getNonce();
      final http.Response response = await http.get(
          "$url/api/mstore_user/register/?insecure=cool&nonce=$nonce&user_email=$username&user_login=$username&username=$username&user_pass=$password&email=$username&user_nicename=$niceName&display_name=$niceName&$isSecure");
      if (response.statusCode == 200) {
        var cookie = convert.jsonDecode(response.body)['cookie'];
        return await this.getUserInfo(cookie);
      } else {
        var message = convert.jsonDecode(response.body)["error"];
        throw Exception(message != null ? message : "Can not create the user.");
      }
    } catch (err) {
      throw err;
    }
  }
```

**Comment by kazhuyo** [comment]
@minhtruong315 thank you, problem solved 👍

**Comment by minhtruong315** [comment]
@kazhuyo can you give us 5* in codecanyon

**Comment by kazhuyo** [comment]
another problem after register, logout and trying to login again, it throw error like this :
<img width="1440" alt="Screen Shot 2019-10-04 at 11 44 42 AM" src="https://user-images.githubusercontent.com/1844792/66182028-662d2780-e69d-11e9-87cf-cf6dd65aef6b.png">

**Comment by minhtruong315** [comment]
@kazhuyo Can you try to enable Email/Password in firebase?
<img width="1262" alt="Screen Shot 2019-10-04 at 11 55 53 AM" src="https://user-images.githubusercontent.com/10402500/66182143-01be9800-e69e-11e9-8a24-0fb0cf0e3843.png">

**Comment by kazhuyo** [comment]
@minhtruong315 I didn't use firebase yet, still default file "GoogleService-Info.plist", I didn't touch that file or replace it.

**Comment by minhtruong315** [comment]
I will check it again

**Comment by minhtruong315** [comment]
https://www.youtube.com/watch?v=3NLP-1KX_Vk
