### ISSUE TITLE
[BeoNews] replace the vidio tab menu with protfolio

### ISSUE THREAD

**Issue by rianseven** [inspireui/support#117]
**Mandatory Info (please complete the following information):**
 - Product: [Beonews]
 - Your Purchased Code: [3fa55ee9-4eab-4612-b32f-11e100c23f46]

how to replace the vidio tab menu with protfolio
banner not showing

**Comment by minhcasi** [comment]
Hi, sorry for a late response

You can replace the video tab by edit the Navigation/index.js and replace the video tab from createBottomTabNavigator 

Please share the detailed screenshot where the banner not showing, if it happens on the Homepage, please check the HorizonLayout from common/config.js
