### ISSUE TITLE
[Flux News] - 

### ISSUE THREAD

**Issue by amit81** [inspireui/support#1172]
Hi,

I have purchased fluxnews, But i am getting an error with our Wordpress blog site when we add your default URL its working perfectly. 

but when i add my URL issue is below 

We are not getting data in app home page. In the category, we are getting listing but when we refresh it will show error: type’_internalLinkedHashMap<sting. dynamic>’ is not a subject of type ‘iterable’
As per your guideline, we all done last time same issue still not short out we get new version but same so please short out

download and active from resource/Wordpress-extension (from the download package) 

![flux 1](https://user-images.githubusercontent.com/11808338/66203677-91783c80-e6c6-11e9-8aa9-9ef109d17695.JPG)
![flux 2](https://user-images.githubusercontent.com/11808338/66203678-91783c80-e6c6-11e9-87d6-9c78adc224c4.JPG)

 

Waiting for your reply Thanks

> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue

2. Screenshots

3. My screenshot of the purchase product or my comment:

3. Config files (optional)

**Comment by minhcasi** [comment]
@amit81 - could you help to share your config file, the common/config.json and config.dart - thank you!

If you installing on local, ref to this video guide: https://www.youtube.com/watch?v=CEyfZmzBMTw&t=1492s

**Comment by amit81** [comment]
[config.zip](https://github.com/inspireui/support/files/3690383/config.zip)
 Hi, 

As per your requirement, please find attachment config file 

Thanks for quick support

**Comment by dttrung26** [comment]
Hi @amit81 ,
would you mind sending us the admin account information of your site via support@inspireui.com. We would like to take a look at your site. 
Nice day,
Trung.

**Comment by minhcasi** [comment]
@amit81 

sent the patching to your email 

Screenshot:
- https://tppr.me/cOnu
- https://tppr.me/QH4Ia
- https://tppr.me/mHA3O (you can change the category image from this file https://tppr.me/eCybA) 
- https://tppr.me/mD2DA 

The root cause of previous issues is wrong category mapping.
