### ISSUE TITLE
[Fluxstore] App Size extending 61 Mb

### ISSUE THREAD

**Issue by spss20** [inspireui/support#1173]
Sir, I checked your demo app for fluxstore which was only of 20 Mb. But when i am building my own fluxstore app. Its size is 61 Mb. Also it is not smooth like your demo app and loads data from server slowly

**Comment by minhcasi** [comment]
Hi, could you share your production app so that we could make and test and give some feedback - thanks

**Comment by spss20** [comment]
https://drive.google.com/file/d/1TYGoYkcBspnyPQf9B8O0VXsXf99OLYBK/view?usp=sharing

I uploade the zip file on google drive because size was too big. Please check it

**Comment by minhcasi** [comment]
got the file

**Comment by minhcasi** [comment]
#1186

**Comment by spss20** [comment]
sir why closed, the issue is not resolved yet, you havent given me any
resoultion, no proper resolution given...
