### ISSUE TITLE
[BeoNews ] - task :react-native-admob:compiledebugjavawithjavac failed

### ISSUE THREAD

**Issue by amit81** [inspireui/support#1174]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue task :react-native-admob:compiledebugjavawithjavac failed

2. Screenshots 

3. My screenshot of the purchase product or my comment:

3. Config files (optional) 

Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

info Starting JS server...
info Building and installing the app on the device (cd android && gradlew.bat app:installDebug)...

> Configure project :react-native-webview
:react-native-webview:reactNativeAndroidRoot C:\Users\Amit Sanghvi\Documents\Beo News\BeoNews.3.0.4\beonews-pro\node_modules\react-native\android

> Configure project :react-native-blur
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

> Configure project :lottie-react-native
publishNonDefault is deprecated and has no effect anymore. All variants are now published.                              <=============
> Task :lottie-react-native:compileDebugJavaWithJavac
Note: C:\Users\Amit Sanghvi\Documents\Beo News\BeoNews.3.0.4\beonews-pro\node_modules\lottie-react-native\src\android\src\main\java\com\airbnb\android\react\lottie\LottieAnimationViewManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :react-native-admob:compileDebugJavaWithJavac FAILED
C:\Users\Amit Sanghvi\Documents\Beo News\BeoNews.3.0.4\beonews-pro\node_modules\react-native-admob\android\src\main\java\com\sbugert\rnadmob\RNAdMobBannerViewManager.java:4: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
C:\Users\Amit Sanghvi\Documents\Beo News\BeoNews.3.0.4\beonews-pro\node_modules\react-native-admob\android\src\main\java\com\sbugert\rnadmob\RNAdMobInterstitialAdModule.java:5: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
C:\Users\Amit Sanghvi\Documents\Beo News\BeoNews.3.0.4\beonews-pro\node_modules\react-native-admob\android\src\main\java\com\sbugert\rnadmob\RNAdMobRewardedVideoAdModule.java:5: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
C:\Users\Amit Sanghvi\Documents\Beo News\BeoNews.3.0.4\beonews-pro\node_modules\react-native-admob\android\src\main\java\com\sbugert\rnadmob\RNPublisherBannerViewManager.java:4: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
C:\Users\Amit Sanghvi\Documents\Beo News\BeoNews.3.0.4\beonews-pro\node_modules\react-native-admob\android\src\main\java\com\sbugert\rnadmob\RNAdMobBannerViewManager.java:119: error: cannot find symbol
    private void sendEvent(String name, @Nullable WritableMap event) {
                                         ^
  symbol:   class Nullable
  location: class ReactAdView
C:\Users\Amit Sanghvi\Documents\Beo News\BeoNews.3.0.4\beonews-pro\node_modules\react-native-admob\android\src\main\java\com\sbugert\rnadmob\RNAdMobBannerViewManager.java:196: error: cannot find symbol
    @Nullable
     ^
  symbol:   class Nullable
  location: class RNAdMobBannerViewManager
C:\Users\Amit Sanghvi\Documents\Beo News\BeoNews.3.0.4\beonews-pro\node_modules\react-native-admob\android\src\main\java\com\sbugert\rnadmob\RNAdMobBannerViewManager.java:254: error: cannot find symbol
    @Nullable
     ^
  symbol:   class Nullable
  location: class RNAdMobBannerViewManager
C:\Users\Amit Sanghvi\Documents\Beo News\BeoNews.3.0.4\beonews-pro\node_modules\react-native-admob\android\src\main\java\com\sbugert\rnadmob\RNAdMobInterstitialAdModule.java:109: error: cannot find symbol
    private void sendEvent(String eventName, @Nullable WritableMap params) {
                                              ^
  symbol:   class Nullable
  location: class RNAdMobInterstitialAdModule
C:\Users\Amit Sanghvi\Documents\Beo News\BeoNews.3.0.4\beonews-pro\node_modules\react-native-admob\android\src\main\java\com\sbugert\rnadmob\RNAdMobRewardedVideoAdModule.java:129: error: cannot find symbol
    private void sendEvent(String eventName, @Nullable WritableMap params) {
                                              ^
  symbol:   class Nullable
  location: class RNAdMobRewardedVideoAdModule
C:\Users\Amit Sanghvi\Documents\Beo News\BeoNews.3.0.4\beonews-pro\node_modules\react-native-admob\android\src\main\java\com\sbugert\rnadmob\RNPublisherBannerViewManager.java:122: error: cannot find symbol
    private void sendEvent(String name, @Nullable WritableMap event) {
                                         ^
  symbol:   class Nullable
  location: class ReactPublisherAdView
C:\Users\Amit Sanghvi\Documents\Beo News\BeoNews.3.0.4\beonews-pro\node_modules\react-native-admob\android\src\main\java\com\sbugert\rnadmob\RNPublisherBannerViewManager.java:229: error: cannot find symbol
    @Nullable
     ^
  symbol:   class Nullable
  location: class RNPublisherBannerViewManager
C:\Users\Amit Sanghvi\Documents\Beo News\BeoNews.3.0.4\beonews-pro\node_modules\react-native-admob\android\src\main\java\com\sbugert\rnadmob\RNPublisherBannerViewManager.java:302: error: cannot find symbol
    @Nullable
     ^
  symbol:   class Nullable
  location: class RNPublisherBannerViewManager
12 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-admob:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 26s
42 actionable tasks: 5 executed, 37 up-to-date
error Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html
error Command failed: gradlew.bat app:installDebug. Run CLI with --verbose flag for more details.
PS C:\Users\Amit Sanghvi\Documents\Beo News\BeoNews.3.0.4\beonews-pro>
![Screenshot (102)](https://user-images.githubusercontent.com/11808338/66228091-3d884a80-e6fc-11e9-86db-7911df4bf2af.png)
![Screenshot (104)](https://user-images.githubusercontent.com/11808338/66228172-71fc0680-e6fc-11e9-965b-4661b41e2347.png)

**Comment by minhcasi** [comment]
noted for investigating

**Comment by concuacon** [comment]
Hi @amit81 use "react-native-admob": "^2.0.0-beta.5", and run by steps:
rm -rf node_modules/ && yarn && cd android && ./gradlew clean && cd ../ (if you use yarn install)
rm -rf node_modules/ && npm install && cd android && ./gradlew clean && cd ../ (if you npm install)

**Comment by amit81** [comment]
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

info Starting JS server...
info Building and installing the app on the device (cd android && gradlew.bat app:installDebug)...

> Configure project :react-native-webview
:react-native-webview:reactNativeAndroidRoot C:\Users\Amit Sanghvi\Documents\Beo News\BeoNews.3.0.4\beonews-pro\node_modules\react-native\android

> Configure project :react-native-blur
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

> Task :lottie-react-native:compileDebugJavaWithJavac
Note: C:\Users\Amit Sanghvi\Documents\Beo News\BeoNews.3.0.4\beonews-pro\node_modules\lottie-react-native\src\android\src\main\java\com\airbnb\android\react\lottie\LottieAnimationViewManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :react-native-admob:compileDebugJavaWithJavac FAILED
C:\Users\Amit Sanghvi\Documents\Beo News\BeoNews.3.0.4\beonews-pro\node_modules\react-native-admob\android\src\main\java\com\sbugert\rnadmob\RNAdMobBannerViewManager.java:4: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
C:\Users\Amit Sanghvi\Documents\Beo News\BeoNews.3.0.4\beonews-pro\node_modules\react-native-admob\android\src\main\java\com\sbugert\rnadmob\RNAdMobInterstitialAdModule.java:5: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
C:\Users\Amit Sanghvi\Documents\Beo News\BeoNews.3.0.4\beonews-pro\node_modules\react-native-admob\android\src\main\java\com\sbugert\rnadmob\RNAdMobRewardedVideoAdModule.java:5: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
C:\Users\Amit Sanghvi\Documents\Beo News\BeoNews.3.0.4\beonews-pro\node_modules\react-native-admob\android\src\main\java\com\sbugert\rnadmob\RNPublisherBannerViewManager.java:4: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
C:\Users\Amit Sanghvi\Documents\Beo News\BeoNews.3.0.4\beonews-pro\node_modules\react-native-admob\android\src\main\java\com\sbugert\rnadmob\RNAdMobBannerViewManager.java:119: error: cannot find symbol
    private void sendEvent(String name, @Nullable WritableMap event) {
                                         ^
  symbol:   class Nullable
  location: class ReactAdView
C:\Users\Amit Sanghvi\Documents\Beo News\BeoNews.3.0.4\beonews-pro\node_modules\react-native-admob\android\src\main\java\com\sbugert\rnadmob\RNAdMobBannerViewManager.java:196: error: cannot find symbol
    @Nullable
     ^
  symbol:   class Nullable
  location: class RNAdMobBannerViewManager
C:\Users\Amit Sanghvi\Documents\Beo News\BeoNews.3.0.4\beonews-pro\node_modules\react-native-admob\android\src\main\java\com\sbugert\rnadmob\RNAdMobBannerViewManager.java:254: error: cannot find symbol
    @Nullable
     ^
  symbol:   class Nullable
  location: class RNAdMobBannerViewManager
C:\Users\Amit Sanghvi\Documents\Beo News\BeoNews.3.0.4\beonews-pro\node_modules\react-native-admob\android\src\main\java\com\sbugert\rnadmob\RNAdMobInterstitialAdModule.java:109: error: cannot find symbol
    private void sendEvent(String eventName, @Nullable WritableMap params) {
                                              ^
  symbol:   class Nullable
  location: class RNAdMobInterstitialAdModule
C:\Users\Amit Sanghvi\Documents\Beo News\BeoNews.3.0.4\beonews-pro\node_modules\react-native-admob\android\src\main\java\com\sbugert\rnadmob\RNAdMobRewardedVideoAdModule.java:129: error: cannot find symbol
    private void sendEvent(String eventName, @Nullable WritableMap params) {
                                              ^
  symbol:   class Nullable
  location: class RNAdMobRewardedVideoAdModule
C:\Users\Amit Sanghvi\Documents\Beo News\BeoNews.3.0.4\beonews-pro\node_modules\react-native-admob\android\src\main\java\com\sbugert\rnadmob\RNPublisherBannerViewManager.java:122: error: cannot find symbol
    private void sendEvent(String name, @Nullable WritableMap event) {
                                         ^
  symbol:   class Nullable
  location: class ReactPublisherAdView
C:\Users\Amit Sanghvi\Documents\Beo News\BeoNews.3.0.4\beonews-pro\node_modules\react-native-admob\android\src\main\java\com\sbugert\rnadmob\RNPublisherBannerViewManager.java:229: error: cannot find symbol
    @Nullable
     ^
  symbol:   class Nullable
  location: class RNPublisherBannerViewManager
C:\Users\Amit Sanghvi\Documents\Beo News\BeoNews.3.0.4\beonews-pro\node_modules\react-native-admob\android\src\main\java\com\sbugert\rnadmob\RNPublisherBannerViewManager.java:302: error: cannot find symbol
    @Nullable
     ^
  symbol:   class Nullable
  location: class RNPublisherBannerViewManager
12 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-admob:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 41s
42 actionable tasks: 35 executed, 7 up-to-date
error Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html
error Command failed: gradlew.bat app:installDebug. Run CLI with --verbose flag for more details.
PS C:\Users\Amit Sanghvi\Documents\Beo News\BeoNews.3.0.4\beonews-pro> npm install react-native-admob@2.0.0-beta.6
npm WARN react-native@0.59.8 requires a peer of react@16.8.3 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Error: EPERM: operation not permitted, rename 'C:\Users\Amit Sanghvi\Documents\Beo News\BeoNews.3.0.4\beonews-pro\node_modules\.staging\fsevents-bc9dd08b\node_modules\needle' -> 'C:\Users\Amit Sanghvi\Documents\Beo News\BeoNews.3.0.4\beonews-pro\node_modules\.staging\needle-fbf8bddf'

npm ERR! path C:\Users\Amit Sanghvi\Documents\Beo News\BeoNews.3.0.4\beonews-pro\node_modules\react-native-admob\android\src\main
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall unlink
npm ERR! Error: EPERM: operation not permitted, unlink 'C:\Users\Amit Sanghvi\Documents\Beo News\BeoNews.3.0.4\beonews-pro\node_modules\react-native-admob\android\src\main'
npm ERR!  { [Error: EPERM: operation not permitted, unlink 'C:\Users\Amit Sanghvi\Documents\Beo News\BeoNews.3.0.4\beonews-pro\node_modules\react-native-admob\android\src\main']
npm ERR!   cause:
npm ERR!    { Error: EPERM: operation not permitted, unlink 'C:\Users\Amit Sanghvi\Documents\Beo News\BeoNews.3.0.4\beonews-pro\node_modules\react-native-admob\android\src\main'
npm ERR!      errno: -4048,
npm ERR!      code: 'EPERM',
npm ERR!      syscall: 'unlink',
npm ERR!      path:
npm ERR!       'C:\\Users\\Amit Sanghvi\\Documents\\Beo News\\BeoNews.3.0.4\\beonews-pro\\node_modules\\react-native-admob\\android\\src\\main' },
npm ERR!   stack:
npm ERR!    'Error: EPERM: operation not permitted, unlink \'C:\\Users\\Amit Sanghvi\\Documents\\Beo News\\BeoNews.3.0.4\\beonews-pro\\node_modules\\react-native-admob\\android\\src\\main\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path:
npm ERR!    'C:\\Users\\Amit Sanghvi\\Documents\\Beo News\\BeoNews.3.0.4\\beonews-pro\\node_modules\\react-native-admob\\android\\src\\main',
npm ERR!   parent: 'beonews-pro' }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Amit Sanghvi\AppData\Roaming\npm-cache\_logs\2019-10-09T11_25_27_823Z-debug.log
PS C:\Users\Amit Sanghvi\Documents\Beo News\BeoNews.3.0.4\beonews-pro>

**Comment by concuacon** [comment]
@amit81 you can follow this link, it helps you fix this issue.
https://github.com/facebook/react-native/issues/25483#issuecomment-508446776

**Comment by inceabdullah** [comment]
> react-native-admob": "^2.0.0-beta.5

you are a king. i have solved after trying migration my project from expo to bare React Native.

Once i had installed normally `yard add react-native-admob` but then i removed it. And `yarn add react-native-admob@^2.0.0-beta.5`
