### ISSUE TITLE
[mstore-pro] - No Loading Indicator during Search + ViewAll to Category Page

### ISSUE THREAD

**Issue by harry503** [inspireui/support#1175]
I'm using the latest version 3.9.5

1. Search in progress with no indicator
Please add loading indicator during search, it's missing from the recent version. I knew that it was exist before. This would help user to understand that a process is being performed.

2. Send user to Category Page with Filter and Sort from Homepage by clicking View All
You have several screen to display products. The one from the homepage if user click "View All"
<img width="401" alt="Screen Shot 2019-10-05 at 07 43 27" src="https://user-images.githubusercontent.com/35995317/66247132-f1f98f00-e743-11e9-8810-ddd5a42342d9.png">

will take you to category without filter page
<img width="408" alt="Screen Shot 2019-10-05 at 07 44 51" src="https://user-images.githubusercontent.com/35995317/66247144-148ba800-e744-11e9-8b3d-bdb47b829ce8.png">

But this system also has a category page with more features, such as filter, and sort.
How can I make it so when user click ViewAll from Home, it would take to the category screen with filter and sort? instead of the basic category page.

Purchase Code: 7c399f31-c465-4f76-ac62-7fa0f04fd615

**Comment by minhcasi** [comment]
@harry503 - noted for investigating - thank you!

**Comment by concuacon** [comment]
@harry503 

- "Search in progress with no indicator

Please add loading indicator during search, it's missing from the recent version. I knew that it was exist before. This would help user to understand that a process is being performed." => i fixed, i'll update next version.

- "Send user to Category Page with Filter and Sort from Homepage by clicking View All
You have several screens to display products. The one from the homepage if user click "View All" => you can edit layout ListAllScreen  (src/navigation/ListAllScreen.js) to the same CategoryScreen (src/navigation/CategoryScreen.js).
