### ISSUE TITLE
[BeoNews ] - Currently, CeBuilder hasn’t supported this project yet

### ISSUE THREAD

**Issue by storchaktitos** [inspireui/support#1176]
BeoNews  - Currently, CeBuilder hasn’t supported this project yet. how to fix it?

**Comment by minhcasi** [comment]
@storchaktitos - could i know which version that you are using for testing.

Please also share your purchased screenshot on https://codecanyon.net/downloads - thank you!

**Comment by storchaktitos** [comment]
Good afternoon. I download CeBuilder 0.37.006.10.2019, 16:31, "Minh Pham" <notifications@github.com>:@storchaktitos - could i know which version that you are using for testing.
Please also share your purchased screenshot on https://codecanyon.net/downloads - thank you!

**Comment by storchaktitos** [comment]
today I downloaded a new version BeoNews.3.0.4 now all good. Thank You
