### ISSUE TITLE
[FluxStore] - Universal

### ISSUE THREAD

**Issue by govindh163** [inspireui/support#1177]
Hey Just I need The answer,
Can I Add my own googleservices.Json file to the Code,and get my User details On my FireBase Account.

Thanks In advance.

**Comment by minhcasi** [comment]
Yes, you can use your own google service file - we have noted on this guide - https://docs.inspireui.com/fluxstore/push-notification/

**Comment by govindh163** [comment]
Can I use the Same "Package name" as Provided in androidManifest.xml as in your FIle?
