### ISSUE TITLE
fluxstore some issu

### ISSUE THREAD

**Issue by Senior-Gamal** [inspireui/support#1178]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

 My issue

we are facing some problems :
- we need to set usa is the default country in shipping or sms country
- sms verication code there is an error when typing .
- we need to select city from a drop down as like the website and the cost of shipping .
- welcome page is not showing.
- we need to remove rating app section .
- we need to remove smartChat section .
- when user sign up has 'mstore' end . we need to edit it also .

 My screenshot of the purchase product or my comment:

![a0](https://user-images.githubusercontent.com/27568540/66254887-0f971a80-e77d-11e9-953f-6a3edf9f4bbd.jpeg)

**Comment by Senior-Gamal** [comment]
any replay about this ????

**Comment by minhtruong315** [comment]
@Senior-Gamal can you send me config.dart, config.json file and account to login to admin site via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/1178

**Comment by Senior-Gamal** [comment]
the mail has been sent

**Comment by kazhuyo** [comment]
@Senior-Gamal 
> 
> My issue
> 
> we are facing some problems :
> 
> * we need to set usa is the default country in shipping or sms country

for shipping country you have to configure your woocommerce in shipping menu.
for sms country you have to open and edit **lib/screens/login_sms/index.dart** and change the code from line 168 with this :

                      InternationalPhoneInput(
                          onPhoneNumberChange: onPhoneNumberChange,
                          // initialPhoneNumber: "",
                          initialSelection: "+62",
                      ),


> * sms verication code there is an error when typing .

please post the error here, did you change app bundle, google firebase config ?

> * we need to select city from a drop down as like the website and the cost of shipping .
> * welcome page is not showing.

for this, which welcome page you mean ? onboard page or what ?

> * we need to remove rating app section .

if you just want to remove their menu, open this file : **lib/screens/settings.dart** and comment or remove lines from 356-377 contain this code :

                      Card(
                        margin: EdgeInsets.only(bottom: 2.0),
                        elevation: 0,
                        child: ListTile(
                          onTap: () {
                            _rateMyApp.showRateDialog(context).then((v) => setState(() {}));
                          },
                          leading: Image.asset(
                            'assets/icons/profile/icon-star.png',
                            width: 24,
                            color: Theme.of(context).accentColor,
                          ),
                          title: Text(S.of(context).rateTheApp, style: TextStyle(fontSize: 16)),
                          trailing: Icon(Icons.arrow_forward_ios, size: 18, color: kGrey600),
                        ),
                      ),
                      Divider(
                        color: Colors.black12,
                        height: 1.0,
                        indent: 75,
                        //endIndent: 20,
                      ),

> * we need to remove smartChat section .

to remove this icon (FAB Menu) open and edit this file **lib/screens/settings.dart** and remove line 78 that contain this code below :

      floatingActionButton: (widget.user.username == config.adminEmail)
          ? FloatingActionButton(
              backgroundColor: Theme.of(context).primaryColor,
              onPressed: () {
                Navigator.push(context,
                    MaterialPageRoute(builder: (context) => ListChat(user: widget.user))); //
              },
              child: Icon(
                Icons.chat,
                size: 22,
              ),
            )
          : SmartChat(user: widget.user),


> * when user sign up has 'mstore' end . we need to edit it also .

mstore is default URL for wordpress setup, you have to rename in using your own domain, or localhost setup.

**Comment by MoradAbdelgaber** [comment]
-- phone login , code input error , when enter a digit pointer should move to the next input as expected 
    , but it is still at the same input. 
    hint => we are using arabic language _ rtl language _ .
-- shipping address problem , we just need one country and when user select city choose from our defined cities 
    as in woocommerce site.
-- app not showing the actual data about shipping cost and payment gateways as like website .

**Comment by minhtruong315** [comment]
I sent you email

**Comment by Senior-Gamal** [comment]
thanks minhtruong315 and i sent replay

**Comment by Senior-Gamal** [comment]
error in setting.dart 

Too many positional arguments: 0 expected, but 1 found.
Try removing the extra positional arguments, or specifying the name for named arguments.

                             NotificationPermissions.requestNotificationPermissions(
                                      const NotificationSettingsIos(
                                          sound: true, badge: true, alert: true))
                                  .then((_) {
                                checkNotificationPermission();
                              });

**Comment by minhtruong315** [comment]
[settings.dart.zip](https://github.com/inspireui/support/files/3706049/settings.dart.zip)
try this file

**Comment by Senior-Gamal** [comment]
the error is not fixed
![setting error](https://user-images.githubusercontent.com/27568540/66502741-2f547880-eac6-11e9-8b47-60642623c1d2.jpg)

**Comment by Senior-Gamal** [comment]
and in app closed the notification is not arrival 
and No notification sound

**Comment by Senior-Gamal** [comment]
issue in coupon a problem with coupon The coupon is recognized but when the invoice appears, the discount is not applied in the application or website But in website works well

I added you in skype
