### ISSUE TITLE
[Mstore] Image sizes 

### ISSUE THREAD

**Issue by smEunus** [inspireui/support#118]
- MStore
 - 8f9c3eb8-e574-46e3-b01d-cb37dd34b676

App performance is too low because of image size.
 If i keep `ProductSize` `true` on `Config.js` image dose not load.
My current setting is....
``` 
ProductSize: {
    enable: false,
    CatalogImages: { width: 300, height: 360 },
    SingleProductImage: { width: 600, height: 720 },
    ProductThumbnails: { width: 180, height: 216 },
  }
```
### Woocommerce shifted their image setting on customizer and customizer has only one field to set image sizes, so the the below image from docs.mstore.io is outdated

<img width="1046" alt="assets_-lh63eujg5iaezihcz4d_-lh6g6vcreoakz_heidy_-lh7b486hssg8qf8kgyf_screen shot 2018-07-11 at 2 12 53 pm" src="https://user-images.githubusercontent.com/23192502/50215117-48136680-03ac-11e9-8a64-25a2b2f80aae.png">

***Better REST API Featured Images*** works fine with posts and pages. But with product there is no rest `better_featured_image` field.  ***Regenerate Thumbnails*** works fine. 

How can i fix this image issues?

**Comment by smEunus** [comment]
Hi, `Constants.Layout.Card` is showing 3 product. Can I increase or decrease the number? A simple hint please .

**Comment by luyx2412** [comment]
Hi @smEunus You can edit in `src/components/HorizonLayout` folder. The folder is describe all types.

Thanks
