### ISSUE TITLE
[FluxStore] - Build an app bundle error

### ISSUE THREAD

**Issue by obadaKraishan** [inspireui/support#1180]
Hello,

when i try to building the app for release it show me this error, i made key.jks and i locate the app directory but it show me same error.

_* What went wrong:                                                      
Execution failed for task ':app:packageReleaseBundle'.                  
> java.util.concurrent.ExecutionException: java.lang.RuntimeException: jarsignerfailed with exit code 1 :
  jarsigner error: java.lang.RuntimeException: keystore load: /Users/Obada_kr/key.jks (No such file or directory)

**Comment by minhcasi** [comment]
Hi, you can change the key path from android.key.properties file - 

example: storeFile=/Users/Obada_kr/key.jks

**Comment by obadaKraishan** [comment]
yeah i did this but still the same!, why you close the issue !!!!!

**Comment by minhcasi** [comment]
@obadaKraishan - could you help to take the screenshot to verify your purchased - https://codecanyon.net/downloads

We will close the ticket if you could not prove as our customer.

**Comment by obadaKraishan** [comment]
sure..

![Screen Shot 2019-10-07 at 9 35 09 AM](https://user-images.githubusercontent.com/28910488/66289611-d62dee80-e8e5-11e9-89bb-b7573128c123.png)
