### ISSUE TITLE
[my-product] - ListPro - Listing Directory React Native template

### ISSUE THREAD

**Issue by anwark** [inspireui/support#1182]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue
I cant see the update  on the app that I did on the website 
2. Screenshots
![jbizList](https://user-images.githubusercontent.com/109449/66264604-fac29180-e825-11e9-9e71-599d98cbe30c.png)
![AppScreen](https://user-images.githubusercontent.com/109449/66264605-fac29180-e825-11e9-8e52-c34985499222.png)
![nodataInApp](https://user-images.githubusercontent.com/109449/66264606-fac29180-e825-11e9-989c-447eac897abb.png)
![Jhalawar_web](https://user-images.githubusercontent.com/109449/66264607-fb5b2800-e825-11e9-8515-794034209cf8.png)

3. My screenshot of the purchased product or my comment:
![ListProBuy](https://user-images.githubusercontent.com/109449/66264600-eaaab200-e825-11e9-936a-4e2646876836.png)
3. Config files (optional)

website is live on - jhalawar.biz

**Comment by minhcasi** [comment]
@anwark  sorry for the inconvenience - could you give us the comment on https://codecanyon.net/item/listpro-listing-directory-react-native-template/22645013 as we could not verify your username on our system purchase

**Comment by anwark** [comment]
Just make a comment on codeden - https://www.screencast.com/t/1hwaD126esdW

**Comment by minhcasi** [comment]
Thank you, it's verified, we will double-check the issue and will let you know - very best!

**Comment by thangvo9x** [comment]
Hi. I can't see your AppConfig file. Please share and brief more your issue. such as Do you have change the category Id on your website

**Comment by anwark** [comment]
Where I can find - AppConfig ?
No, i have not change the category Id on your website please tell me how i can ?

**Comment by anwark** [comment]
Where I can find - AppConfig ?
No, i have not change the category Id on your website please tell me how i can ?

**Comment by thangvo9x** [comment]
in Common folder. AppConfig.js file.

**Comment by anwark** [comment]
[AppConfig.zip](https://github.com/inspireui/support/files/3746262/AppConfig.zip)
Please find file

**Comment by thangvo9x** [comment]
Could u share more detail as which location Id and share more your Classic.js file ? Thanks

**Comment by anwark** [comment]
[Classic.zip](https://github.com/inspireui/support/files/3746295/Classic.zip)
Website live on - https://jhalawar.biz/

**Comment by thangvo9x** [comment]
HI. Could you share your account to admin dashboard?

**Comment by anwark** [comment]
User - jhalawar.biz@gmail.com
Passe - jhalawar!@#$

**Comment by thangvo9x** [comment]
Hi bro. Try again, data was fetched.

**Comment by anwark** [comment]
> Hi bro. Try again, data was fetched.

Can you please tell me what changes you made on server ??

**Comment by anwark** [comment]
> Hi bro. Try again, data was fetched.

there is no image in App - https://expo.io/@jhalawar/listpro
