### ISSUE TITLE
[Fluxstore] - Product not syncing correctly

### ISSUE THREAD

**Issue by EffectiveOG** [inspireui/support#1184]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue
1. Variable product appear to be unavalaible on the app while its not in website 
2. Product description doesnt respect selected language on the app 
3. Some product doesnt  show thumbnails but when you click on a product the image is downloaded 
4. smart chat whatsapp scheme doesnt send the user to whatsapp 
5. multicurrency should work as it doesnt make sens to make an app multilingual without make it multi currency by default, for ex i use USD for paypal to proceed internationnal payment but my default local currency is XAF as cant sell on USD in local context, here is the plugin i use https://codecanyon.net/item/woocommerce-multi-currency/20948446?ref=villatheme
2. Screenshots
![Screen Shot 2019-10-06 at 3 22 16 PM](https://user-images.githubusercontent.com/33296809/66270640-c662cb80-e84d-11e9-92dd-8e98f4766309.png)
![Screen Shot 2019-10-06 at 3 22 03 PM](https://user-images.githubusercontent.com/33296809/66270641-c6fb6200-e84d-11e9-8890-6f96241c0f89.png)
![Screen Shot 2019-10-06 at 3 22 55 PM](https://user-images.githubusercontent.com/33296809/66270642-c6fb6200-e84d-11e9-9b3f-c7b7be97714b.png)
![Screen Shot 2019-10-06 at 3 23 40 PM](https://user-images.githubusercontent.com/33296809/66270644-c793f880-e84d-11e9-9f3b-93ff787ff36d.png)

3. My screenshot of the purchase product or my comment:

3. Config files (optional)
prefer to share by mail

**Comment by minhcasi** [comment]
@EffectiveOG - could you share your purchase screenshot from https://codecanyon.net/downloads - thanks

**Comment by EffectiveOG** [comment]
Viny EMANE NDOLO
p:+24105662424  m: +24107616161a:Akanda, Gabone:nd.emaneviny@gmail.com<mailto:nd.emaneviny@gmail.com>
[http://cdn2.hubspot.net/hubfs/184235/dev_images/signature_app/linkedin_sig.png]<https://www.linkedin.com/in/viny-ndolo-emane/>
________________________________

**Comment by minhtruong315** [comment]
@EffectiveOG 
please send me config.json and admin account via email: truong@inspireui.com

1. Variable product appear to be unavalaible on the app while its not in website
can you send me product name?

smart chat whatsapp scheme doesnt send the user to whatsapp
you must check whatsapp by device

**Comment by minhtruong315** [comment]
@EffectiveOG i received config.json file. But i haven't received admin account.
Please send me admin account to check your site

Variable product appear to be unavalaible on the app while its not in website
can you send me product name?

**Comment by EffectiveOG** [comment]
On 9 Oct 2019, at 11:06, Viny Ndolo Emane <emaneviny@outlook.com> wrote:

﻿You can just reset password with you your email. It has the admin profile.


This one of variable product

[cid:580BD4CF-F791-4FA7-A80E-EDCA64F025A1-L0-001]

On 9 Oct 2019, at 10:39, minhtruong315 <notifications@github.com> wrote:

﻿

@EffectiveOG<https://github.com/EffectiveOG> i received config.json file. But i haven't received admin account.
Please send me admin account to check your site

Variable product appear to be unavalaible on the app while its not in website
can you send me product name?

**Comment by minhtruong315** [comment]
Add my skype: minhtruong315. i will help you check via teamviewer

**Comment by minhtruong315** [comment]
no response

**Comment by EffectiveOG** [comment]
Okay for today, i will call you on Skype.

Best,
On 13 Oct 2019, at 03:47, minhtruong315 <notifications@github.com> wrote:

﻿

no response
