### ISSUE TITLE
[Fluxstore] - Some Error List

### ISSUE THREAD

**Issue by kazhuyo** [inspireui/support#1185]
Found a bug :

- When trying to view order history using "Cash On Delivery" everything work without error. But when trying to view order history using "Payment Gateway" i got this error.

<img width="1440" alt="Screen Shot 2019-10-07 at 10 05 25 AM" src="https://user-images.githubusercontent.com/1844792/66282720-a9c8a100-e8ea-11e9-840d-24d54bf35895.png">

but when testing with postman, all data comes out without problem, here's my postman test :

<img width="1176" alt="Screen Shot 2019-10-07 at 10 07 03 AM" src="https://user-images.githubusercontent.com/1844792/66282912-91a55180-e8eb-11e9-9a25-54672ddfd49f.png">

- Register email or login, will throw an error if using "Special Character" as password, eg !@#$%^&*() here's the error :

<img width="1440" alt="Screen Shot 2019-10-04 at 11 19 16 AM" src="https://user-images.githubusercontent.com/1844792/66282835-2b203380-e8eb-11e9-8cc9-2ee6e362ca51.png">

**Comment by minhcasi** [comment]
@kazhuyo - could you provide your purchased screenshot from https://codecanyon.net/downloads

**Comment by kazhuyo** [comment]
@minhcasi you can in my previous issue #1159

**Comment by minhcasi** [comment]
got it, thank you - could you share your config file so that we could try to reproduce the issue

**Comment by kazhuyo** [comment]
@minhcasi here's the config file.
[config.zip](https://github.com/inspireui/support/files/3700465/config.zip)

**Comment by kazhuyo** [comment]
any update with this error ? @minhcasi

**Comment by minhtruong315** [comment]
@kazhuyo pls replace lib/models/order.dart to fix the error order
[order.dart.zip](https://github.com/inspireui/support/files/3706201/order.dart.zip)

**Comment by kazhuyo** [comment]
thank you, it fixed now 👍

**Comment by minhcasi** [comment]
@kazhuyo - please give us some feedback/rating to this page https://codecanyon.net/downloads if the product is helpful for your business, we are working hard to update more awesome and powerful features on next coming version release. Let us know if you have any feedbacks. Thank you very much! 😊

**Comment by kazhuyo** [comment]
@minhcasi I'm already do that before 💯

**Comment by minhcasi** [comment]
@kazhuyo - thank you, i love you ❤️

**Comment by minhcasi** [comment]
@kazhuyo - could you consider to update our product rating as it is impacted to our business, otherwise - kindly process the refund to save your money and time - thank you!
