### ISSUE TITLE
[FluxStore] - RazorPay Payment Gateway Integration in App Not Working

### ISSUE THREAD

**Issue by spss20** [inspireui/support#1186]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:  Sir razorpay payment gateway in your app is not working, in congif.dart , i have entered razorpay key, also it ask for callback_url in razorpay configurations in config.dart file, i entered random url for callbackurl. When i complete purchase through razorpay, the problem is it redirects to callback url in webview rather then opening native screen saying thanks for your order (just like when i do payment through COD) . Also once the payment is successfull in razorpay, transaction is successfull but i didn't recive order in my woocommerce panel. I think you have problem in api in razorpay native integration. Please check it and fix my problem. I am attaching my config.dart and config.json file.
My base-url is proteinadda.in . I can successfully place order in webiste but giving problem in app.

2. Screenshots

3. My screenshot of the purchase product or my comment:

3. Config files (optional

[common.zip](https://github.com/inspireui/support/files/3695966/common.zip)
extract the zip file and you'll find my config files.
)

**Comment by minhtruong315** [comment]
@spss20 can you send me admin account via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/1186
i wanna check your website

**Comment by spss20** [comment]
i have sent on mail from krishna.pratap1997@gmail.com . Please check

**Comment by spss20** [comment]
????

**Comment by minhtruong315** [comment]
<img width="1094" alt="Screen Shot 2019-10-09 at 2 26 51 PM" src="https://user-images.githubusercontent.com/10402500/66460364-f655dd00-eaa0-11e9-93df-7597d1d9c79e.png">
I checked your config. it show the other in admin. pls check again

**Comment by spss20** [comment]
Sir, i dont know what are you talking about, if you mean to say that i have different url and woocommerce keys in config, for that i have double checked and i conclude that i have exact correct configurations, url is proteinadda.in, woocommerce key, secret is also correct??

**Comment by minhtruong315** [comment]
Also once the payment is successfull in razorpay, transaction is successfull but i didn't recive order in my woocommerce panel.

can you record screen for this issues?

**Comment by spss20** [comment]
wait, sending

**Comment by spss20** [comment]
so here is a video clip showing video while i am placing order in your app.
https://drive.google.com/file/d/1d3-WkXPFhDWW1kXGpY7vDPUH1whqot_B/view?usp=sharing

here is the orders panel in woocommerce.
![Screenshot (99)](https://user-images.githubusercontent.com/29224720/66471536-18ebf400-eaa9-11e9-9ccc-3a5f5f780cb8.png)


when i placed order on razorpay , i clicked on Successfull to make the order successfull, it redirects to https://example.com/ and after couple of millisecond it redirect back to the payment method selection screen. As you can see in screenshot, the last order is placed by you only, my order is not received in woocommerce even when it was successfull by razorpay.


Please check it sir, and try to resolve it asap.
Thanks in advance

**Comment by minhtruong315** [comment]
@spss20 add my skype: minhtruong315. i will help you debug via teamviewer

**Comment by spss20** [comment]
added, accept my req

**Comment by minhtruong315** [comment]
@spss20 can you check on other devices? we'll fix this. it's available in next version

**Comment by spss20** [comment]
Why the issue is closed without a solution, without a resolution

**Comment by spss20** [comment]
plz solve my razorpay integration issue in app

**Comment by minhtruong315** [comment]
https://www.dropbox.com/s/jssaubfwaj4cfki/Untitled.mov?dl=0
i see it's working well?

**Comment by spss20** [comment]
Sir, why are you telling lie, you also knew that it was working on emulator, yeah i accept that, but its not working in real device, You debugged also that day and saw the problem yourself.

**Comment by minhcasi** [comment]
@spss20  - I'm testing on my iphone X and samsung S9, it's working well, what's your device?

Could you able run the Test Drive example on your device as well ?

**Comment by spss20** [comment]
could you connect to me on teamviewer , i'll show you the problem. I am using Xiaomi Redmi Y2

**Comment by minhcasi** [comment]
There are some known crash issues on Redmi on Flutter could be similar to your issues:
- https://github.com/flutter/flutter/issues/36822
- https://github.com/flutter/flutter/issues/31603
- https://github.com/flutter/flutter/issues/18351

We also do some testing on other devices Samsung and Pixel, they works fine

**Comment by spss20** [comment]
wait, let me check

**Comment by spss20** [comment]
I have tested on Xiaomi , Oppo, Vivo, Samsung, Sony devices. Same problem occuring. Please solve it. Connect with me on teamviewer and fix it.

**Comment by minhcasi** [comment]
pls send your final zip project source to support@inspireui.com - I will forward to the team for checking, remote via TV and take a lot of time - thanks

**Comment by spss20** [comment]
see sir, i have debugged index.dart in razorpay and noticed the url's being called in emulator and real device. Following are urls called in emulator :
https://api.razorpay.com/v1/payments/create/checkout
https://api.razorpay.com/v1/gateway/mocksharp/payment?key_id=rzp_test_y0hkKEPneaFJ0e
https://api.razorpay.com/v1/payments/pay_DVXN9EyB7zTYj3/callback/0fb4e065cf8b9f658acc5af8551acb7dc68d96a5/rzp_test_y0hkKEPneaFJ0e?status=authorized&token_recurring_status=rejected
http://example.com/

Following are the url called in real device:
https://api.razorpay.com/v1/gateway/mocksharp/payment?key_id=rzp_test_y0hkKEPneaFJ0e
http://example.com/

which clearly shows that in real devices two urls are not being called. Isn't it strange issue. And these are the only urls which make the value of paymentstatus String "authenticated" but not called in real device , the issue is happening.

I have also cleared the problem , now its your job to solve it asap

**Comment by spss20** [comment]
????????

**Comment by spss20** [comment]
https://drive.google.com/file/d/1xkITJqeax_cvimQKe5XFkJyucbQH2M0W/view?usp=sharing

LINK TO MY PROJECT

**Comment by minhcasi** [comment]
we will investigate and let you know - thanks

**Comment by minhtruong315** [comment]
@spss20 What is the android version you're using?

**Comment by spss20** [comment]
android P

**Comment by minhtruong315** [comment]
Can you try to add this: ```android:usesCleartextTraffic="true"``` to application in AndroidManifest.xml

**Comment by minhtruong315** [comment]
<img width="385" alt="Screen Shot 2019-10-21 at 10 11 02 PM" src="https://user-images.githubusercontent.com/10402500/67218004-d97dba00-f44f-11e9-822f-9afa471f69a5.png">

**Comment by spss20** [comment]
wait, can you ping me on skype?

**Comment by spss20** [comment]
i tried by adding it, still no luck....same thing happening

**Comment by minhtruong315** [comment]
is it working on simulator but not working on devices?

**Comment by spss20** [comment]
i have two simulators, one is "Nexus 5x api 28" , second one is "Pixel 2 Api 28". Both have Android 9.0 installed but it is working in nexus emulator, but gives same problem in Pixel 2 . I dont know why but those two urls which i mentioned that i debugges are not called in Pixel 2 as well as real devices on which i have tested. Please connect to team viewer, I will show you

**Comment by spss20** [comment]
?????its been 15 days and still no resolution give

**Comment by minhcasi** [comment]
@spss20 - we could not find out the root cause for these issues on Android, this could be the Flutter library not compatible with some libraries that using from the pub file.

If you could not use the product so far, we could process the refund for you, thanks

**Comment by spss20** [comment]
ok refund my amount then

**Comment by minhcasi** [comment]
you can submit on this link - https://help.market.envato.com/hc/en-us/articles/202821460-Can-I-Get-A-Refund- - thanks
