### ISSUE TITLE
[MStore Multi Vendor] - 

### ISSUE THREAD

**Issue by mahmoudjameel** [inspireui/support#1187]
we bought Mstore multi vender this week
and we notice that the version of the app that we got did not support multi vender as it suppose
attached is image from the app that we got that (don`t include register as vender in register screen)
notice that Mstore multiple vendors App in App store include register as vender in register screen.
we think that we got the source Code of MStore pro instead of Mstore multi vender.

![multi](https://user-images.githubusercontent.com/26668860/66304621-506e6b00-e906-11e9-9b75-3fa57e0fe324.jpg)
![ourapp](https://user-images.githubusercontent.com/26668860/66304623-506e6b00-e906-11e9-98e4-2205961a85db.jpg)
[Archive.zip](https://github.com/inspireui/support/files/3696725/Archive.zip)
[2.zip](https://github.com/inspireui/support/files/3696732/2.zip)

**Comment by minhcasi** [comment]
@mahmoudjameel  - thank you for your feedbacks, could you help to share your purchased screenshot from - https://codecanyon.net/downloads ?

**Comment by mahmoudjameel** [comment]
this is what you want .؟
![Uploading 72388762_419285978729990_3821108218566803456_n.png…]()

**Comment by mahmoudjameel** [comment]
this is what you want ..?

![72388762_419285978729990_3821108218566803456_n](https://user-images.githubusercontent.com/26668860/66431086-011e5c80-ea24-11e9-9ec8-7110f70cbb39.png)

**Comment by minhcasi** [comment]
@mahmoudjameel  - sorry for late responded,  the Multivendor version will be support for the Vendor, the Mstore Pro is only used for one Vendor - thank you!
