### ISSUE TITLE
[ListApp] - Webview fix

### ISSUE THREAD

**Issue by rodrigofoca** [inspireui/support#1189]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue

Webview wasn't rendering any url, so I figured out WebView was cut from React Native core. That means the way to fix everything was to install react-native-webview from the community and then change all the imports of WebView to from react-native-webview.

You need to do this on your code and upload to code canyon.

Best regards

Rodrigo

**Comment by minhcasi** [comment]
thank you for your feedback, we will investigate and update patching for this issue - very best!
