### ISSUE TITLE
[Mstore multi vendor] - can you please help me … how to start “CLI version ” on vscode in windows…?

### ISSUE THREAD

**Issue by ZamanGoraya** [inspireui/support#1190]
1. [Mstore multi vendor] - can you please help me … how to start “CLI version ” on vscode in windows…?

![CLI issue](https://user-images.githubusercontent.com/52818458/66370173-a865aa00-e9b8-11e9-87aa-f1b31e432a31.PNG)

**Comment by minhcasi** [comment]
Hi, first please setup you basic lib (yarn, node...) base on this guide - https://facebook.github.io/react-native/docs/getting-started.html and try to run the example project (for cli version)

From the cli version folder, you can try with this script: yarn install && yarn start 

It's possible to run via XCode after that

**Comment by ZamanGoraya** [comment]
Thanks bro...! i have done this... but i moved on cli version from expo because of push notification problem... unfortunately i still in the same problem of push notification...

https://github.com/inspireui/support/issues/1153

**Comment by ZamanGoraya** [comment]
@minhcasi please tell me how can i resolve push notification in my android cli version...

**Comment by minhcasi** [comment]
@ZamanGoraya - could you follow this guide - https://github.com/geektimecoil/react-native-onesignal and re-install on the cli version? There are some extra config for the onesignal to make it work

**Comment by minhcasi** [comment]
Btw, could you send the video screenshot to explain more about the issues pls ?

**Comment by ZamanGoraya** [comment]
they do not support the video file... but it is simple... when i enable the push notification then app show me the msg "can't get data from server"...

**Comment by ZamanGoraya** [comment]
@minhcasi have you understand my problem...?

**Comment by ZamanGoraya** [comment]
> @ZamanGoraya - could you follow this guide - https://github.com/geektimecoil/react-native-onesignal and re-install on the cli version? There are some extra config for the onesignal to make it work
> 
> > <img alt="" width="48" src="https://avatars3.githubusercontent.com/u/17333873?s=400&amp;v=4"><img alt="" height="14" src="https://camo.githubusercontent.com/4908d9947135e4536ef61d61512ee575f869bf6f/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e2e69636f"> GitHub**[geektimecoil/react-native-onesignal](https://github.com/geektimecoil/react-native-onesignal)**React Native Library for OneSignal Push Notifications Service - geektimecoil/react-native-onesignal

@minhcasi  i have follow these all notifications but ... the problem is still there...

**Comment by ZamanGoraya** [comment]
> @ZamanGoraya - could you follow this guide - https://github.com/geektimecoil/react-native-onesignal and re-install on the cli version? There are some extra config for the onesignal to make it work
> 
> > <img alt="" width="48" src="https://avatars3.githubusercontent.com/u/17333873?s=400&amp;v=4"><img alt="" height="14" src="https://camo.githubusercontent.com/4908d9947135e4536ef61d61512ee575f869bf6f/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e2e69636f"> GitHub**[geektimecoil/react-native-onesignal](https://github.com/geektimecoil/react-native-onesignal)**React Native Library for OneSignal Push Notifications Service - geektimecoil/react-native-onesignal

@minhcasi  i have follow all these guides but the problem is still there...

**Comment by ZamanGoraya** [comment]
@luyx2412 @vumanhsn97 @minhcasi  Can any body help me...?

**Comment by minhcasi** [comment]
@ZamanGoraya - we have updated latst cli version that compatible with latest Expo 0.35 and RN, please reinstall one-signal on this version to fix the issue - thank you!
