### ISSUE TITLE
[ListApp] - Can not create new listing

### ISSUE THREAD

**Issue by hungnguyen9276** [inspireui/support#1191]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue
I can not create new listing. After I submit I got a message "Sorry, you are not allowed to create post as this user"
2. Screenshots
<img width="295" alt="Screen Shot 2019-10-08 at 15 07 49" src="https://user-images.githubusercontent.com/25025251/66378509-c1cd1d00-e9dd-11e9-889e-45415345a15e.png">

3. My screenshot of the purchase product or my comment:
My purchase code : 2c21e8c4-d8cc-4226-aeba-68cd81289fe6
3. Config files (optional)

**Comment by minhcasi** [comment]
@hungnguyen9276 - could you check if this plugin working on your site - https://wordpress.org/plugins/jwt-authentication-for-wp-rest-api/

**Comment by hungnguyen9276** [comment]
@minhcasi I installed it and it works on my website

**Comment by Hamzanisar** [comment]
@hungnguyen9276  i was facing this issue so on i try hard to fix it now i'm getting error wrong number of segment while posting product

**Comment by minhcasi** [comment]
@Hamzanisar - the segment issue could relate to https://docs.inspireui.com/listapp/troubleshooting/#wrong-segments--message-when-post-new-listing

@hungnguyen9276 - could you share your config file here

**Comment by thangvo9x** [comment]
Hi. Please share your AppConfig file for checking?

**Comment by hungnguyen9276** [comment]
Here is Appconfig.js
<img width="641" alt="Screen Shot 2019-10-18 at 19 06 07" src="https://user-images.githubusercontent.com/25025251/67092814-6b7c8d00-f1da-11e9-95c6-c575e5df2472.png">

**Comment by thangvo9x** [comment]
<img width="500" alt="Screen Shot 2019-10-18 at 8 44 55 PM" src="https://user-images.githubusercontent.com/23457178/67099415-23fcfd80-f1e8-11e9-8e3a-90d0c635d908.png">
The error comes from your server. Please check.

**Comment by hungnguyen9276** [comment]
Can you tell me what is error and how to fix it?

**Comment by thangvo9x** [comment]
Hi bro. Check the role of the user to upload files? only admin/editor role. Thanks

**Comment by hungnguyen9276** [comment]
I get this error when used admin user to create new list

**Comment by thangvo9x** [comment]
Could you share your admin account for login to the dashboard? Thanks, such as I also check your hosting.

**Comment by hungnguyen9276** [comment]
Yes, I can share admin account to you. What is you email?

**Comment by thangvo9x** [comment]
thangvo5969@gmail.com , please

**Comment by thangvo9x** [comment]
Fixed on your website. The error from the server, old plugins.
[](url)
<img width="1165" alt="Screen Shot 2019-10-20 at 8 38 13 PM" src="https://user-images.githubusercontent.com/23457178/67160302-abc64180-f379-11e9-81e9-0999643a6337.png">

**Comment by hungnguyen9276** [comment]
Thanks! Can you tell me which is old plugins and how to fix if got a same error?

**Comment by thangvo9x** [comment]
I have helped you fix it yet.
