### ISSUE TITLE
[CeStore] - Not asking for permissions NOTIFICATIONS

### ISSUE THREAD

**Issue by ahmadyousefdev** [inspireui/support#1192]
1. The cestore app never asks for permission for the notification NOTIFICATIONS,
in this file `src/Router.js` it never asks for the function `Permissions.askAsync(Permissions.NOTIFICATIONS)` on IOS , I guess it's because the expo version is old ? , I tried upgrading `expo-permissions` but with no luck ..
2. I faced another problem a while a go, t**he expo version of this app is not supported anymore in the new xcode simulator**, I had to upgrade the app to `"expo": "^33.0.0"` which needed a lot of work, I think the problem here is the same. I have to upgrade to 
3. Consider updating Cestore please.. It's a great starter app but it's old

**Comment by ahmadyousefdev** [comment]
https://github.com/expo/expo/issues/1354#issuecomment-521992636

**Comment by ahmadyousefdev** [comment]
Never mind for the notification, it turned out that 

> Note:
iOS and Android simulators cannot receive push notifications. To test them out you will need to use a real-life device. Additionally, when calling Permissions.askAsync on the simulator, it will resolve immediately with "undetermined" as the status, regardless of whether you choose to allow or not.

but still, the app needs an upgrade ....

**Comment by minhcasi** [comment]
@ahmadyousefdev  - thank you

We will update new version that compatible with latest expo 0.35

**Comment by minhtruong315** [comment]
@ahmadyousefdev I upgraded expo to version 0.35. It'll be available in some days
