### ISSUE TITLE
[Flux Store Pro] - Not Working on iOS either

### ISSUE THREAD

**Issue by audiojaminc** [inspireui/support#1195]
Hello,
We tried to switch to MAC and run the app but whenever we run it via the iPhone Simulator it gives the following message and breaks the app on file **lib/widgets/payment/paypal/index.dart line 63**:

Exception has occurred.
FlutterError (Scaffold.of() called with a context that does not contain a Scaffold.
No Scaffold ancestor could be found starting from the context that was passed to Scaffold.of(). This usually happens when the context provided is from the same StatefulWidget as that whose build function actually creates the Scaffold widget being sought.
There are several ways to avoid this problem. The simplest is to use a Builder to get a context that is "under" the Scaffold. For an example of this, please see the documentation for Scaffold.of():
  https://api.flutter.dev/flutter/material/Scaffold/of.html
A more efficient solution is to split your build function into several widgets. This introduces a new context from which you can obtain the Scaffold. In this solution, you would have an outer widget that creates the Scaffold populated by instances of your new inner widgets, and then in these inner widgets you would use Scaffold.of().
A less elegant but more expedient solution is assign a GlobalKey to the Scaffold, then use the key.currentState property to obtain the ScaffoldState rather than using the Scaffold.of() function.
The context used was:
  PaypalPayment(dependencies: [InheritedProvider<CartModel>, _InheritedTheme, _LocalizationsScope-[GlobalKey#cae28]], state: PaypalPaymentState#2e090))

How can this be fixed?

Why so many bugs in your app? Why did you sell us a broken product that does not work? That is very scammy work. **Please fix.**

**Comment by minhcasi** [comment]
stop support
