### ISSUE TITLE
[Mstore PRO] - I have some crashes 

### ISSUE THREAD

**Issue by souriahost** [inspireui/support#1197]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. I have some crashes when i click buy now button , change language switcher and when i add to cart from wish list 

2. (1) buy now button crash 
![xostore crashes-1](https://user-images.githubusercontent.com/17759695/66471512-17fc9780-ea94-11e9-90e5-c3e7d3a5e323.png)
![xostore crashes-2](https://user-images.githubusercontent.com/17759695/66471541-264ab380-ea94-11e9-94ff-4231209f1291.png)

![xostore crashes-3](https://user-images.githubusercontent.com/17759695/66472021-12ec1800-ea95-11e9-8c49-6b818cf75fe9.jpg)

(2)change language switcher crash 
![xostore language switcher crash-1](https://user-images.githubusercontent.com/17759695/66472134-43cc4d00-ea95-11e9-9e97-151e96d5725b.png)
![xostore language switcher crash-2](https://user-images.githubusercontent.com/17759695/66472151-4f1f7880-ea95-11e9-9881-c277a93306ab.png)
![xostore language switcher crash-3](https://user-images.githubusercontent.com/17759695/66472167-58104a00-ea95-11e9-952c-9c28908a32fd.png)
![xostore language switcher crash-4](https://user-images.githubusercontent.com/17759695/66472243-7ece8080-ea95-11e9-8010-42cb8ff23847.png)
 
(3) add to cart from wish list crash 

![wish list add to cart crash-1](https://user-images.githubusercontent.com/17759695/66472275-90b02380-ea95-11e9-9731-20a431d6594b.png)
![wish list add to cart crash-2](https://user-images.githubusercontent.com/17759695/66472290-986fc800-ea95-11e9-98ec-0bfeb0b87cae.png)
![wish list add to cart crash-3](https://user-images.githubusercontent.com/17759695/66472310-a02f6c80-ea95-11e9-9935-e6731960334d.png)

3. My screenshot of the purchase product or my comment:
![WhatsApp Image 2019-10-09 at 13 18 52](https://user-images.githubusercontent.com/17759695/66473337-b5a59600-ea97-11e9-81f3-8590282299ee.jpeg)
![WhatsApp Image 2019-10-09 at 13 19 52](https://user-images.githubusercontent.com/17759695/66473350-bc340d80-ea97-11e9-8632-5491a3d29908.jpeg)

3. Config files (optional)

[Config.js.zip](https://github.com/inspireui/support/files/3706802/Config.js.zip)

**Comment by concuacon** [comment]
@souriahost I checked and fix it, can you send me your email? I will send you a new source.

**Comment by souriahost** [comment]
souriahost@gmail.com this is my email thanks

**Comment by souriahost** [comment]
please i am not recieved any new source

**Comment by souriahost** [comment]
any updates , 4 days ago you are gonna to send me files no files  get

**Comment by souriahost** [comment]
hello , any updates ?

**Comment by concuacon** [comment]
@souriahost sorry for late, I sent to your email, pls check and feedback to me.

**Comment by souriahost** [comment]
@concuacon hello mr l received your new source and generated apk from same your source and i had same crashes

**Comment by concuacon** [comment]
@souriahost Can i remote to your desktop to see the problem?

**Comment by souriahost** [comment]
@concuacon yes you can but problem there was in mobile ? can you remote to my phone  ?

**Comment by souriahost** [comment]
[WhatsApp Video 2019-10-17 at 11.23.59.mp4.zip](https://github.com/inspireui/support/files/3738224/WhatsApp.Video.2019-10-17.at.11.23.59.mp4.zip)
@concuacon you can see problems in this video

**Comment by concuacon** [comment]
You can add my skype: pvtuan1707

**Comment by souriahost** [comment]
@concuacon i added you my mohammed faisal

**Comment by souriahost** [comment]
@concuacon i added you my is mohammed faisal
