### ISSUE TITLE
[MStore Multi Vendor] -  I have problem with mstore-user plugin ... i have install mstore checkout plugin but i cannot found this in json api... can anyone help me...?

### ISSUE THREAD

**Issue by ZamanGoraya** [inspireui/support#1198]
![Mstore checkout auther](https://user-images.githubusercontent.com/52818458/66479210-800fa580-eab5-11e9-9a42-ab52f265f0de.PNG)

Problem : 
![Json API](https://user-images.githubusercontent.com/52818458/66479274-a2092800-eab5-11e9-9aac-7c25c537be87.PNG)

![Mstore checkout](https://user-images.githubusercontent.com/52818458/66479276-a2092800-eab5-11e9-8264-8c21d5ce9f4c.PNG)

**Comment by minhcasi** [comment]
@ZamanGoraya - please open the wordpress plugin and rename json-api-master to json-api will fix the issue

**Comment by ZamanGoraya** [comment]
but i have already json-
![json api plugin](https://user-images.githubusercontent.com/52818458/66488128-e18c4000-eac6-11e9-8894-1c8fa9ec924f.PNG)
api... no need to change from json-api-master to json-api

**Comment by ZamanGoraya** [comment]
can you tell me the solution of this problem...?

**Comment by ZamanGoraya** [comment]
@minhcasi thanks for reply... now i have solved this problem...

**Comment by minhcasi** [comment]
@ZamanGoraya - thank you, we're glad that help 👍

**Comment by ZamanGoraya** [comment]
@minhcasi i have solved this problem you are right it was the problem of json-api... thank you for help...
