### ISSUE TITLE
[FluxStore] - Magento 2 Integration ID is not specified or is invalid.

### ISSUE THREAD

**Issue by obadaKraishan** [inspireui/support#1199]
Hi,

When i tried to make new integration to setup Magento API for my application it show me this error.

![Screen Shot 2019-10-09 at 3 51 21 PM](https://user-images.githubusercontent.com/28910488/66483347-8bf76980-eaad-11e9-8cb1-a2ade2d199c8.png)

I went to System -> Extensions -> Integration, then i added (Add New Integration) with the name and password also from API i have selected (All), then (Save) it's shown on the list but when i clicked to (Active) the error appear!

Help me please it's urgent!

Many Thanks.

**Comment by obadaKraishan** [comment]
Also i have purchased the product.

![Screen Shot 2019-10-09 at 4 02 38 PM](https://user-images.githubusercontent.com/28910488/66483712-4be4b680-eaae-11e9-805a-93edccaeaa70.png)

**Comment by minhcasi** [comment]
@obadaKraishan - would you mind to take the screenshot include your username on the top-right of the screen? Thank you !

**Comment by obadaKraishan** [comment]
enough?!

![FAS](https://user-images.githubusercontent.com/28910488/66556112-55c2f400-eb58-11e9-9bd4-d942dec8d638.png)

**Comment by minhcasi** [comment]
Yes, veried - thank you!

I've assigned to the team for checking, @minhtruong315

**Comment by obadaKraishan** [comment]
i don't use skype by whats'app is it okay? +962797701646

**Comment by obadaKraishan** [comment]
Do you have any updates? now after you work it shown the exceptions!

![Screen Shot 2019-10-10 at 3 46 28 PM](https://user-images.githubusercontent.com/28910488/66569904-2a023700-eb75-11e9-8b7a-871af3602a29.png)

**Comment by minhtruong315** [comment]
i only create an integration. but it throw those errors

**Comment by obadaKraishan** [comment]
is there any solve to this issue?

**Comment by minhtruong315** [comment]
you can try to renew your website? I think your website has problem, so it can't add integration

**Comment by minhtruong315** [comment]
no response
