### ISSUE TITLE
change images on homescreen

### ISSUE THREAD

**Issue by samber91** [inspireui/support#12]
How can i change these images please ? there is no mention in the doc and i'm new to expo thanks

images attached
![8b0efe59-10d3-45a6-9516-983237e76fe3](https://user-images.githubusercontent.com/42559522/48530658-9e99fc00-e866-11e8-8615-8426d1823f4a.jpg)
![1628d7b6-a868-490c-8bbb-238bcd3c4848](https://user-images.githubusercontent.com/42559522/48530660-a2c61980-e866-11e8-9963-7d835d3e5ed8.jpg)

**Comment by minhcasi** [comment]
Hi, it's using the feature product image, you can map the Horizontal item to any category or tag ID to display these products - thank you!

**Comment by samber91** [comment]
Can show me remotely please ? I can’t not do it . I tried but i don’t see
what we are talking about. Only 5 mins . Please . I’m launching the app
monday
