### ISSUE TITLE
FluxStore

### ISSUE THREAD

**Issue by 25thammar** [inspireui/support#1202]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue
www.Gamingsrebel.com is the website where the WordPress and woo-commerce is setup. I cloned your repository and did exactly what the docs said  but when I paste the consumer key and secret also change the URL to www.gamingsrebel.com console gives an error 
flutter: Error: type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'Iterable<dynamic>' 
This only happens when I change the server config.
https://gamingsrebel.com/wp-json/wc/v3  is also working 
Please Help me ! I have given you 2 screenshots of common/config.dart and other is of woo-commerce/config.dart
2. Screenshots
<img width="1920" alt="Screenshot 2019-10-09 at 11 33 09 PM" src="https://user-images.githubusercontent.com/49050503/66510101-d13b8b80-eaed-11e9-9dcf-354663d38b92.png">

<img width="1920" alt="Screenshot 2019-10-09 at 11 39 56 PM" src="https://user-images.githubusercontent.com/49050503/66510291-2ecfd800-eaee-11e9-8ac2-7622cfa4969c.png">

3. My screenshot of the purchase product or my comment:
<img width="881" alt="Screenshot 2019-10-09 at 11 36 59 PM" src="https://user-images.githubusercontent.com/49050503/66510042-ba953480-eaed-11e9-838b-b064c8d236f0.png">

3. Config files (optional)

[lib.zip](https://github.com/inspireui/support/files/3708938/lib.zip)

**Comment by minhtruong315** [comment]
@25thammar 
can you try this config
```
  "url": "https://gamingsrebel.com",
  "consumerKey": "ck_c1ac1d0f0428a7e59d61420187e79b17f146a057",
  "consumerSecret": "cs_91418dcd355272212ba2ebc8f993668103a99efb",
```

**Comment by minhcasi** [comment]
stop support as infringe to the license - https://tppr.me/Yu8sc

**Comment by minhcasi** [comment]
stop support as infringe to the license - https://tppr.me/Yu8sc
