### ISSUE TITLE
[fluxstore] - 

### ISSUE THREAD

**Issue by raiedahmed** [inspireui/support#1203]
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...

Compiler message:
lib/screens/settings.dart:190:85: Error: Too many positional arguments: 0 allowed, but 1 found.
Try removing the extra positional arguments.
                              NotificationPermissions.requestNotificationPermissions(
                                                                                    ^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/notification_permissions-0.4.3/lib/notification_permissions.dart:10:35: Context: Found this candidate, but the arguments don't match.
  static Future<PermissionStatus> requestNotificationPermissions(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_widgets-0.1.5/lib/src/visibility_detector/src/visibility_detector_layer.dart:277:18: Error: This expression has type 'void' and can't be used.
    return super.addToScene(builder, layerOffset);
                 ^
Compiler failed on E:\drmazad\lib\main.dart

FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 765

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebugX86'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16s
Finished with error: Gradle task assembleDebug failed with exit code 1

---------
https://4.top4top.net/p_1377ndgnq1.png

https://5.top4top.net/p_1377w213u2.png

https://6.top4top.net/p_1377485rv3.png

**Comment by minhtruong315** [comment]
@raiedahmed can you send me your source code? pls upload to google drive and share private my email: minhtruong315@gmail.com

**Comment by minhtruong315** [comment]
no response
