### ISSUE TITLE
[Beonews Pro ] 

### ISSUE THREAD

**Issue by maahiraanka** [inspireui/support#1204]
Hi , I am getting this error , I am using Mac

error Failed to build iOS project. We ran “xcodebuild” command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening beonews.xcodeproj

BUILD FAILED **
The following commands produced analyzer issues: Analyze /Users/maahir/Downloads/BeoNews.3.0.4/beonews-pro/node_modules/react-native/ReactCommon/jsi/jsi.cpp normal x86_64 Analyze /Users/maahir/Downloads/BeoNews.3.0.4/beonews-pro/node_modules/react-native/ReactCommon/yoga/yoga/Yoga.cpp normal x86_64 Analyze /Users/maahir/Downloads/BeoNews.3.0.4/beonews-pro/node_modules/react-native/React/Base/RCTModuleMethod.mm normal x86_64 (3 commands with analyzer issues)

The following build commands failed: CompileC /Users/maahir/Downloads/BeoNews.3.0.4/beonews-pro/ios/build/beonews/Build/Intermediates.noindex/RNAdMobManager.build/Debug-iphonesimulator/RNAdMobManager.build/Objects-normal/x86_64/RNGADBannerView.o /Users/maahir/Downloads/BeoNews.3.0.4/beonews-pro/node_modules/react-native-admob/ios/RNGADBannerView.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (1 failure) . Run CLI with—verbose flag for more details.

**Comment by concuacon** [comment]
@maahiraanka you try to check your package.json the same image and run by steps:
rm -rf node_modules/ && yarn cache clean && yarn && react-native run-ios 
<img width="306" alt="Screen Shot 2019-10-10 at 1 41 49 PM" src="https://user-images.githubusercontent.com/11958061/66544951-c4597f00-eb63-11e9-80e3-76a8460b55aa.png">

**Comment by maahiraanka** [comment]
I am having issue with GoogleMobileAds in IOS and there are a lot of people have the same issue, how to solve this issue , tried everything , i can't able to get it work .

cleared the cache , and did everything you mention up , and also went thru google and did every solution possible, what  is wrong with this.

**Comment by concuacon** [comment]
@maahiraanka can you send your source to tuan@inspireui.com via wetransfer.com

**Comment by maahiraanka** [comment]
Done please check

**Comment by concuacon** [comment]
@maahiraanka okay, I'll check and feedback to you soon

**Comment by concuacon** [comment]
@maahiraanka please check your mailbox, i sent to you via wetransfer

**Comment by maahiraanka** [comment]
Hello Inspireui/Support


The source you sent what is it ( Pro Version or Lite Version) .

Thanks

**Comment by mariod3w** [comment]
Hello @concuacon, I have the same problem in my MAC, How do i solve it?

Can you help me please.
