### ISSUE TITLE
[FluxStore-Universal] - 

### ISSUE THREAD

**Issue by govindh163** [inspireui/support#1205]
Issues On Firebase SMS auth:
                                  Changed Package name And Integrated Firebase ,enabled sms signin!!
                                   The SMSCode was received and then the code was typed then Pressing the  Verify Button "keeps on loading Forever" It is not going to the HomePage or the "Nextpage",
                                  Of,Course the Mobile number Entered is Stored on Firebase Console,But the Verifypage is not moving forward!!

Issues on Google map:
                              I added my API key,and Enabled the SDK for maps in Console,But Map is not displaying !!!.
                             Of,Course the nearBy Places Works good and showing my nearby places!!

Tried to solve these,
Please Help me to Sort it Out!

Thanks in Advance!!

**Comment by minhcasi** [comment]
@govindh163 - could you check this video guide - https://www.youtube.com/watch?v=3NLP-1KX_Vk&list=PLcF-HiQy-jOJAD8btGgr_CHcUmYyN8GgY&index=9&t=122s

**Comment by govindh163** [comment]
@minhcasi -Yes I had gone thorough But no solution!

**Comment by minhcasi** [comment]
@govindh163 - please check the config from https://pub.dev/packages/place_picker

It could be missing step of download the google-services or something else, also try to run the app on the device to see if it work, sometime it is not displayed on your simulator due to the Google Play Service on Simulator could not enable.

**Comment by govindh163** [comment]
https://user-images.githubusercontent.com/52994786/66696878-86886200-eced-11e9-8cba-d8831bcab9c2.png 
 

I think PlacePicker Works Fine!!,
Let us See!!

Gratefully Thanks for Taking your Time to solve @minhcasi

**Comment by govindh163** [comment]
Self Solved -- mismatching of API key Now the MAps works Good!

**Comment by minhcasi** [comment]
Thank you!

**Comment by minhcasi** [comment]
@govindh163 - please help to us for the review from https://codecanyon.net/downloads - appreciated for your help - very best!
