### ISSUE TITLE
[Flux News ] - Desplay front page as my Website Home Page  

### ISSUE THREAD

**Issue by amit81** [inspireui/support#1207]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:  Display front page as my Website Home Page  

2. Screenshots

3. My screenshot of the purchase product or my comment:

3. Config files (optional)

Dear InspireUI Team 

I want to display App Home page as my Website Home page not to display as a category  type 

please guide current display and my website Display is the latest post. I want to the same display looking  mobile app 

my website is 
https://www.bewithyourself.com

<img width="405" alt="f6cd7c09a312c06fd82a75c69b1834e4" src="https://user-images.githubusercontent.com/11808338/66574546-10231d00-eb92-11e9-8014-70cde5048095.png">

![flux web image](https://user-images.githubusercontent.com/11808338/66574739-5a0c0300-eb92-11e9-8fdf-b3a137606f2e.JPG)

**Comment by minhcasi** [comment]
@amit81  - try to remove the categoryid - https://tppr.me/LHfdN 

It will display all the recent content as default
