### ISSUE TITLE
[List App] - ceBuilder error

### ISSUE THREAD

**Issue by aariasp** [inspireui/support#1209]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue
I have some problem when cebuilder run on expo simulator doesn't run anything just display an error or blank screen.
2. Screenshots
![Image of CeBuilder setup](https://glowit.app/setup.png)
![Image of CeBuilder setup2](https://glowit.app/setup2.png)
![Image of CeBuilder customization](https://glowit.app/customization.png)
![Image of Error Screen](https://glowit.app/error.png)
3. My screenshot of the purchase product or my comment:
![Image of Error Screen](https://glowit.app/compra.png)
3. Config files (optional)

**Comment by concuacon** [comment]
@aariasp You can change the default system language on Settings -> General -> Language & Region to fix issue

**Comment by aariasp** [comment]
There’s no settings menú...

Enviado desde mi iPhone

**Comment by concuacon** [comment]
@aariasp are you sure? 
<img width="435" alt="Screen Shot 2019-10-18 at 2 15 29 PM" src="https://user-images.githubusercontent.com/11958061/67073700-db2a5200-f1b1-11e9-885e-99b85f206cb8.png">
