### ISSUE TITLE
BeoNews - When going from Category List screen to Post list screen, First post doesnt load in right place for Android devices

### ISSUE THREAD

**Issue by talwinder1508** [inspireui/support#121]
- BeoNews

**Describe the bug**
When going from Category List screen to Post list screen, First post doesn't load in the right place for Android devices
<img width="757" alt="category list" src="https://user-images.githubusercontent.com/14082839/50258947-e4426b00-03b6-11e9-8a30-34c79a4b63a2.png">

**Comment by minhcasi** [comment]
Hi, could you provide more detail of your purchased code or screenshot of the purchase - https://help.market.envato.com/hc/en-us/articles/202822600-Where-Is-My-Purchase-Code-

Then, please also share your config.js file then we could help for debugging the issue, please also try with another Android device as it may not support for Android below 6.x
Thank you!
