### ISSUE TITLE
[FluxStore] - dont loading product images 

### ISSUE THREAD

**Issue by almazamangaliev** [inspireui/support#1211]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue

After connecting woocomerce to app i get products but images not loading?

**Comment by minhcasi** [comment]
Pls double check this guide - https://docs.inspireui.com/fluxstore/woocommerce-setup/

And share the purchase screenshot from - https://codecanyon.net/downloads 

(We will reopen ticket after verified purchased) - thank you!
