### ISSUE TITLE
[Fluxstore] - Woocommerce Checkout Template

### ISSUE THREAD

**Issue by kazhuyo** [inspireui/support#1213]
1. My issue
When checkout using payment gateway, mstore-api-template.php didn't write Country Name from Address Select in shipping address, only write isocode country name.

How to fix country name in mstore-api-templates.php?

2. Screenshots
here's the error we get after click the button "Place My Order" button.

<img width="277" alt="Screen Shot 2019-10-11 at 12 26 29 PM" src="https://user-images.githubusercontent.com/1844792/66626827-de5a9680-ec23-11e9-81ac-b6b72c866876.png">

3. My screenshot of the purchase product or my comment:

3. Config files (optional)

**Comment by minhtruong315** [comment]
You can edit shipping_address.dart in screens/checkout
line 300
```
Expanded(
                                child: address.country != null
                                    ? Text(
                                        CountryPickerUtils.getCountryByIsoCode(address.country)
                                            .name,
                                        style: TextStyle(fontSize: 17.0))
                                    : Text(S.of(context).country),
                              )

to 
Expanded(
                                child: address.country != null
                                    ? Text(
                                        address.country,
                                        style: TextStyle(fontSize: 17.0))
                                    : Text(S.of(context).country),
                              )
```

line 421

```
  onValuePicked: (Country country) =>
                      setState(() => address.country = country.isoCode)

to 

  onValuePicked: (Country country) =>
                      setState(() => address.country = country.name)
```

**Comment by kazhuyo** [comment]
Sorry, late reply, yep, i have change like that, thank you... 👍

**Comment by kazhuyo** [comment]
another error when coupon applied :

<img width="277" alt="Screen Shot 2019-10-11 at 3 09 52 PM" src="https://user-images.githubusercontent.com/1844792/66635365-4667a780-ec39-11e9-9b32-904d99d8758a.png">

**Comment by minhtruong315** [comment]
@kazhuyo we fixed coupon. it will be available in next release. thanks

**Comment by minhcasi** [comment]
@kazhuyo - could you consider to update our product rating as it is impacted to our business, otherwise - kindly process the refund to save your money and time - thank you!
