### ISSUE TITLE
API not working

### ISSUE THREAD

**Issue by PremiumPromotion** [inspireui/support#1214]
Hello,
Unfortunately, Ce Builder blocks after saving values in customize section.
I tried with Expo but you may see in the attach that the app is loading, but categories and products not, it says no route.
I tried with e-piesecamioane.ro and also on another site, but same problem.
I think it is something related to Api.

It is working with e-piesecamioane.ro/wp-json/wc/v1 but not with v2 and if i put 'products' after it generates error.

I tried to install rest api plugin even if i already configured keys in wc.
Also tried to install Mstore Pro API plugin, but returns fatal error, not finding some dokan file or something like that.
So could you please what to do to load categories and products in the app when loading by test with Expo? It returns no route. How to communicate by API?

**Comment by concuacon** [comment]
@PremiumPromotion can you attach your config and screenshot??

**Comment by concuacon** [comment]
Hello, @PremiumPromotion I have just released a new version of ceBuilder [0.38.0](https://github.com/inspireui/cebuilder/releases/tag/0.38.0) please delete the old CeBuilder and install the new version. 
Please update api-ecommerce to 0.0.33 to fix this issue => "It is working with e-piesecamioane.ro/wp-json/wc/v1 but not with v2 and if i put 'products' after it generates error."
