### ISSUE TITLE
[Mstore Multi Vendor] - facebook login problem...

### ISSUE THREAD

**Issue by ZamanGoraya** [inspireui/support#1215]
given url is not allowed by the application configuration one or more of the given urls in not allowed by the apps settings. to use this url you must add a native platform in your apps settings

![fb login](https://user-images.githubusercontent.com/52818458/66649830-913ceb80-ec48-11e9-9427-450f454841b1.PNG)

![Screenshot_1570794837](https://user-images.githubusercontent.com/52818458/66649538-df9dba80-ec47-11e9-8a56-08e0c84fea6f.png)

**Comment by minhcasi** [comment]
@ZamanGoraya - Could you check the facebook developer setting?  https://docs.expo.io/versions/latest/sdk/facebook/ - The bundle ID should be matched with your app setting

**Comment by ZamanGoraya** [comment]
@minhcasi thank you...! now i have solve my facebook login problem with your help...
