### ISSUE TITLE
[EVaStore] - Layout-Related Products

### ISSUE THREAD

**Issue by alaaeallam** [inspireui/support#1217]
Hi ,
I've three issues:

1- the related products not working
2- when i'm changing the layout , many products dont show up.
3- products are repeating only for the collection that having more than one page in shopify store.

please find the attached video for more clarification
[EvaStore.mp4.zip](https://github.com/inspireui/support/files/3718900/EvaStore.mp4.zip)

**Comment by minhcasi** [comment]
@alaaeallam - thank you for the video, we will double the issue and let you know

**Comment by minhcasi** [comment]
@alaaeallam - could you help to share your config file as well - thanks

**Comment by alaaeallam** [comment]
[Config.js.zip](https://github.com/inspireui/support/files/3720552/Config.js.zip)


HYG

**Comment by alaaeallam** [comment]
Hello,

any news

**Comment by concuacon** [comment]
@alaaeallam  sorry for the delay, can you send me your AppConfig.json file?

**Comment by alaaeallam** [comment]
[AppConfig.json.zip](https://github.com/inspireui/support/files/3733435/AppConfig.json.zip)

HYG

**Comment by concuacon** [comment]
@alaaeallam I fixed it, I'll update next version, if you want update now, you can send me your email.

**Comment by alaaeallam** [comment]
alaaeallam@gmail.com

**Comment by alaaeallam** [comment]
thank you

**Comment by concuacon** [comment]
@alaaeallam please check mail, I sent it to you via wetransfer.

**Comment by alaaeallam** [comment]
@concuacon  received , thanks for your support.
will check and keep you posted.

**Comment by alaaeallam** [comment]
@concuacon  its working fine thanks

**Comment by concuacon** [comment]
Hi, we're glad that it help, please give us some feedback/rating to this page https://codecanyon.net/downloads if the product is helpful for your business, we are working hard to update more awesome and powerful features on next coming version release. Let us know if you have any feedback. Thank you very much! :blush:
