### ISSUE TITLE
I have a problem when Open CeBuilder 

### ISSUE THREAD

**Issue by Suhaibaj** [inspireui/support#1218]
Hi 

I have a problem when Open CeBuilder 

look to screenshot

![Screen Shot 2019-10-11 at 8 24 31 PM](https://user-images.githubusercontent.com/53709547/66672723-9b221700-ec67-11e9-8c14-8d03c894a9e5.png)

help me please ,
Thanks .

**Comment by minhcasi** [comment]
@Suhaibaj  - from the Setting pls enable this option - https://tppr.me/VlHC3

You can select Allow app downloaded from "Appstore and identified developers" or AnyWhere
