### ISSUE TITLE
[Fluxstore Pro] - Latest version from codecanyon removed

### ISSUE THREAD

**Issue by underscore15** [inspireui/support#1219]
1. Need the download for version 1.5.1 

2. Screenshots
![Screen Shot 2019-10-11 at 9 34 05 PM](https://user-images.githubusercontent.com/56452467/66675859-e4299980-ec6e-11e9-8f76-3d6c637421d5.png)

**Comment by minhcasi** [comment]
@underscore15 - it's hidden by Envato for the quality review, I hope they will enable it again after the review in a few days - thank you!

**Comment by underscore15** [comment]
In that case I need the latest version to download, envato still are hiding it. 
Can you send it by email or shared link ?

**Comment by underscore15** [comment]
In that case I need the latest version to download, envato still are hiding it. 
Can you send it by email or shared link ?
