### ISSUE TITLE
[Fluxstore Pro - Flutter E-commerce Full App] - Authentication Issue

### ISSUE THREAD

**Issue by kumarrahul-rkv** [inspireui/support#1220]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue
When I am trying to log in, It is saying:

`warning: FormatException: Unexpected character (at character 1)
<br />
^`

Consequently, I am not able to login

2. Screenshots

![login](https://user-images.githubusercontent.com/19572222/66695188-09a0bc80-ecdc-11e9-8d5c-ce0724d7e4f6.png)

3. My screenshot of the purchased product or my comment:

![image](https://user-images.githubusercontent.com/19572222/66695203-32c14d00-ecdc-11e9-8982-83951478bfe5.png)

3. Config files (optional)

## Note: You have deleted your products from code canyon.
https://codecanyon.net/item/fluxstore-the-universal-woocommerce-magento-opencart-mobile-app-by-flutter-framework/24020929

**Comment by minhcasi** [comment]
@kumarrahul-rkv  is it possible to share your website admin login to support@inspireui.com - we will help for checking. 
The new version will be available to download soon - thanks

**Comment by kazhuyo** [comment]
@kumarrahul-rkv fluxstore v1.5.1 don't support special character as password, refer this issue #1185 
to solve this problem replace line 411 with this code below and don't forget to update mstore-api plugins in wordpress too :

```
  /// login
  @override
  Future<User> login({username, password}) async {
    var cookieLifeTime = 120960000000;
    try {
      final http.Response response = await http.post(
          "$url/api/mstore_user/generate_auth_cookie/?insecure=cool&$isSecure",
          body: convert.jsonEncode({
            "seconds": cookieLifeTime.toString(),
            "username": username,
            "password": password
          }));

      final body = convert.jsonDecode(response.body);
      if (response.statusCode == 200 && isNotBlank(body['cookie'])) {
        return await this.getUserInfo(body['cookie']);
      } else {
        throw Exception("The username or password is incorrect.");
      }
    } catch (err) {
      throw err;
    }
  }
```

let us know if it's working, thank you...

**Comment by minhtruong315** [comment]
@kumarrahul-rkv pls update mstore-api plugin. then try again

**Comment by minhtruong315** [comment]
no response
