### ISSUE TITLE
[Fluxstore] - Request to add multi vendor support and vendor name search and catalogue page.

### ISSUE THREAD

**Issue by pixelops** [inspireui/support#1221]
Please add multivendor support for woocomerce, search by vendor name, vendor catalogue page with categories, vendor in filters.

**Comment by minhcasi** [comment]
Yes sure, we will release new product support for Fluxstore MV soon this month - thank you!

**Comment by TheRealPlug** [comment]
Is MV support coming in October or November??

**Comment by minhcasi** [comment]
@pixelops  - it's ready for download on this link - https://codecanyon.net/item/fluxstore-multi-vendor-flutter-ecommerce-full-app/25013325 - thank you!
