### ISSUE TITLE
[Mstore Pro] Nothing Happen after click sign up

### ISSUE THREAD

**Issue by panuponj** [inspireui/support#1223]
[Mstore Pro] Nothing Happen after click sign up

**Comment by concuacon** [comment]
@panuponj please check your plugin installed, Check to see if the Mstore API plugin is available? and remember to activate the JSON API plugin
https://wordpress.org/plugins/mstore-api/#reviews

**Comment by minhcasi** [comment]
Also try to update the latest 3.9.6 to fix this issues, make sure to replace the mstore-checkout with latest mstore-api - https://wordpress.org/plugins/mstore-api/
