### ISSUE TITLE
MStore - Shipping

### ISSUE THREAD

**Issue by lancerynearson** [inspireui/support#1224]
Is there anyway at all to have the shipping be more then just a few flat rate options? Can what products are in the cart or the shipping address have any variation on the shipping price?

Thanks

**Comment by minhcasi** [comment]
Hi, the current release only supports for the first zone with multi shipping options, but we are working new feature to support multi zone+shipping (this is quite complex features) - thank you!

**Comment by lancerynearson** [comment]
I can imagine, I have been working on this app for a month, it’s so, so amazing. It’s the best this on code canyon. But I’m at a lose as I waited to the end to do shipping never in a million year thinking it would be so limited, based on how powerful the rest of it is. I have a Nov 1st release date setup, there’s even a lunch party. What should I do? I’m assuming what your working on is a way off? What I really need is weight base shipping, or if there was even an option to have some items free shipping and some items flat rate. I currently do this on the web site having free shipping items be just a digital product. Is there any work around or anything I can do to make the Nov 1st or do I just need to  Except that this all is a complete  fail? Is there anyway to have the webview kick in earlier and have the shipping done on the site. Really just an option?. If you could offer any info on how it works or point me in any direction at all.
