### ISSUE TITLE
mstore expo confirm order , banner and rtl

### ISSUE THREAD

**Issue by bawanehcoder** [inspireui/support#1225]
1. My issue
- after building the application i cannot confirm the order. pressing the confirm button does nothing.

- RTL on the application doesnt work

- banner images 2 columns doesnt work

2. Screenshots

![WhatsApp Image 2019-10-14 at 10 58 35 AM (2)](https://user-images.githubusercontent.com/56534904/66736370-a779c000-ee71-11e9-92c5-a134ae8ec979.jpeg)
![WhatsApp Image 2019-10-14 at 10 58 35 AM (1)](https://user-images.githubusercontent.com/56534904/66736371-a779c000-ee71-11e9-9241-f69decd0b5dc.jpeg)
![WhatsApp Image 2019-10-14 at 10 58 35 AM](https://user-images.githubusercontent.com/56534904/66736372-a779c000-ee71-11e9-940b-cefb2bbe8120.jpeg)
3. My screenshot of the purchase product or my comment:
![image](https://user-images.githubusercontent.com/56534904/66736120-0985f580-ee71-11e9-92ee-82a47be386b1.png)

3. Config files (optional)

**Comment by minhcasi** [comment]
Hi, could you help to check this solution - https://docs.inspireui.com/mstore/questions/#404-error-page-when-process-the-payment- - thank you!

**Comment by minhcasi** [comment]
@bawanehcoder - pls try to update latest 3.9.6 to fix these issues - thank you!
