### ISSUE TITLE
[List App] - Call issue

### ISSUE THREAD

**Issue by sfoulad** [inspireui/support#1227]
Hi,
on iOS when i click call i get the attached error 

how can i fix it ?

Item Purchase Code: 53f5da40-3fee-42cf-bbe1-2f5fae1b6ead

![WhatsApp Image 2019-10-15 at 07 18 01](https://user-images.githubusercontent.com/53208725/66802732-1fa1bd80-ef26-11e9-9569-250a674c5696.jpeg)

**Comment by thangvo9x** [comment]
Hi bro. Could you share your AppConfig for checking? Thanks
