### ISSUE TITLE
[Mstore Multi Vendor] how to enable chat...?

### ISSUE THREAD

**Issue by ZamanGoraya** [inspireui/support#1228]
![Mstore chat problem](https://user-images.githubusercontent.com/52818458/66809135-30fac200-ef46-11e9-982a-42a9363baedc.PNG)

**Comment by minhcasi** [comment]
@ZamanGoraya  - the chat is only displayed when matching with this condition - https://tppr.me/M7f4S - from the detail component - thanks

**Comment by ZamanGoraya** [comment]
but when i do login the chat button is watchable but not clickable... this was my problem... can you help me...?

**Comment by ZamanGoraya** [comment]
@thangvo9x can you help me...? how can i solve this problem...?

**Comment by ZamanGoraya** [comment]
hello...?

**Comment by ZamanGoraya** [comment]
@minhcasi @thangvo9x @luyx2412 @vumanhsn97  The chat icon is not click able how can i solve this problem...?

**Comment by minhcasi** [comment]
@ZamanGoraya - sorry for the detail,  pls share your whole config again, i will send to other teams for checking - thank you!

**Comment by minhcasi** [comment]
@ZamanGoraya - pls try with the latest version and let us know - thank you!
