### ISSUE TITLE
Fluxstore - magento

### ISSUE THREAD

**Issue by kandohi** [inspireui/support#1229]
I'm using on Magento 2.2.5,

when i click on category, the product doesn't show and error with no product found

The payment method of cod and bank transfer are not showing 

Guest Checkout is not working

Orders History is not showing.
kindly check

**Comment by kandohi** [comment]
using fluxpro ecommerce

**Comment by minhcasi** [comment]
@kandohi - could you show your purchase screenshot from https://codecanyon.net/downloads - pls take the screenshot that include your username - thank you!

**Comment by kandohi** [comment]
![image](https://user-images.githubusercontent.com/56577488/66907698-30842900-f023-11e9-8d3e-ed874955fc22.png)

**Comment by minhcasi** [comment]
@kandohi - thank you for the update, could help to share your configs files so that we could check the integration on your website? Thanks

**Comment by minhtruong315** [comment]
@kandohi can you check this solution to fix no product
https://github.com/inspireui/support/issues/1230#issuecomment-542603165

The payment method of cod and bank transfer are not showing
Guest Checkout is not working
Orders History is not showing.
Guest checkout is only available for woo commerce. if you're using magento, you should disable that function
You must login before checkout

**Comment by kandohi** [comment]
where i can share the config files?

**Comment by minhtruong315** [comment]
share via my email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/1229

**Comment by kandohi** [comment]
emailed

**Comment by kandohi** [comment]
payment method of COD and Bank Transfer not working 
and on from version 1.5.6 the home page giver null error

**Comment by minhtruong315** [comment]
Please record screen for checkout. I wanna see your issues

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
