### ISSUE TITLE
ListPro - how to order by listings near your location?

### ISSUE THREAD

**Issue by lpzczar** [inspireui/support#123]
I need the listings ordered by nearby to user. Since they appear ordered according to the recent ones that were added. And we need the near ones to appear.

**Comment by minhcasi** [comment]
Hi, you can refer to the source code from the Map screen, we are loading the nearest Listing on the map, you can use similar approach for the homage page Listing - thank you!

**Comment by lpzczar** [comment]
Could you tell me how to do it step by step? thank u!

**Comment by lpzczar** [comment]
Thank you. I urgently need to solve these problems because we are delaying work a lot.
