### ISSUE TITLE
[Fluxstore] - How to add left menu & Sms sign-up

### ISSUE THREAD

**Issue by Pars1vaLl** [inspireui/support#1231]
Hi team,

Kindly ask you to answer to my questions:
 
 1. Please describe in more details adding of 'Left Menu Side'. https://docs.inspireui.com/fluxstore/home-layout/

2. When user signs up - the list of all countries appears. I would like to remove all countries beside Russia in that list.

Here is my purchase code: https://user-images.githubusercontent.com/45024483/63820143-9af0e500-c961-11e9-8005-114a7ac9e36b.png

Thank you in advance=)

**Comment by minhcasi** [comment]
@Pars1vaLl  - we will update the document to clarify more detail your 2 questions and keep update on this ticket - thank you!

**Comment by Pars1vaLl** [comment]
Hi @minhcasi , could you please tell me how much time it will take? Approximately. 
Or it would be better if you share with me the information here.

Thanks in advance=)

**Comment by minhcasi** [comment]
1. update - https://docs.inspireui.com/fluxstore/home-layout/#drawer-layout-left-menu-side and tip to change any UI layout - https://docs.inspireui.com/fluxstore/useful-tip/

2. Fixed on 1.5.8 by change common/config.dart - DefaultCountry - to limit list of country
