### ISSUE TITLE
[MStore Pro] - FAILURE: Build failed with an exception

### ISSUE THREAD

**Issue by 007asom** [inspireui/support#1232]
Hello
there is an issue with building apk file. I'm working in the file you send it to me here
https://github.com/inspireui/support/issues/1179
The steps I did from here:
https://facebook.github.io/react-native/docs/0.60/signed-apk-android

FAILURE: Build failed with an exception.

* Where:
Script '/Users/xxx/Downloads/mstore-expo/node_modules/@react-native-community/cli-platform-android/native_modules.gradle' line: 229

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not get unknown property 'task' for object of type org.gradle.internal.extensibility.DefaultExtraPropertiesExtension.
---------

1. My issue
FAILURE: Build failed with an exception
2. Screenshots

3. My screenshot of the purchase product or my comment:
https://ibb.co/PNBWpYy
3. Config files (optional)

**Comment by 007asom** [comment]
Hi
I fix the first issue. now there is a new one.

> Task :app:bundleReleaseJsAndAssets FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:bundleReleaseJsAndAssets'.
> A problem occurred starting process 'command '..\..\node_modules\hermesvm\win64-bin\hermes''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 13m 52s

**Comment by concuacon** [comment]
@007asom 
Hello, you try run: cd android/ && ./gradlew clean && cd ../ && react-native run-android
Can you follow link: 
https://github.com/react-native-community/async-storage/issues/49
https://stackoverflow.com/a/52068632/5295046

**Comment by 007asom** [comment]
thank you very much it works now when I used the "react-native run-android". The APK file not working well, it is crashed.

**Comment by concuacon** [comment]
@007asom Please open the android studio and run the app then show me the log in Android Studio.

**Comment by 007asom** [comment]
sorry for opening the case again.
I'm using now the last version of  MStore Pro. It is working fine with ./gradlew assembleDebug.
But still, get the same error when running ./gradlew assembleRelease

> Task :app:bundleReleaseJsAndAssets FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:bundleReleaseJsAndAssets'.
> A problem occurred starting process 'command '..\..\node_modules\hermesvm\win64-bin\hermes''
