### ISSUE TITLE
fluxstore -  error in new Version: 1.5.5

### ISSUE THREAD

**Issue by Senior-Gamal** [inspireui/support#1233]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

 My issue

1 -error in file chat_screen.dart
2 - and in app closed the notification is not arrival
and No notification sound

2. Screenshots
![error](https://user-images.githubusercontent.com/27568540/66866061-d2126880-ef98-11e9-9b1b-3b6f64c30f1d.jpg)

3. My screenshot of the purchase product or my comment:
https://user-images.githubusercontent.com/27568540/66625373-4e512880-ebf4-11e9-9b30-c4a19f7d028d.jpeg

**Comment by minhcasi** [comment]
@Senior-Gamal  - pls help to remove the chat folder or download latest 1.5.5b

"deprecated the Firebase Chat due to cloud_firestore slow running build issue #349, #37582"
