### ISSUE TITLE
[Mstore Multi Vendor] - kindly help me how to generate apk in windows using mstoremv-cli…?

### ISSUE THREAD

**Issue by ZamanGoraya** [inspireui/support#1235]
![apk cli](https://user-images.githubusercontent.com/52818458/66902029-5d334300-f019-11e9-9aa6-fc0b5b2db6cc.PNG)

hy…! kindly help me how to generate apk in windows using mstoremv-cli…?

**Comment by minhcasi** [comment]
Hi, could we know what is your installing issues so far?

**Comment by ZamanGoraya** [comment]
when in send command exp build:android it gives error on build ios.

**Comment by ZamanGoraya** [comment]
![cli apk error](https://user-images.githubusercontent.com/52818458/66954315-9c917c00-f079-11e9-8181-a2858d6cb12e.PNG)

**Comment by ZamanGoraya** [comment]
@minhcasi ...?

**Comment by ZamanGoraya** [comment]
PS F:\native\Bazar3\New\mstore-multi-vendor-v1.3.1\mstore-mv-cli> cd android
PS F:\native\Bazar3\New\mstore-multi-vendor-v1.3.1\mstore-mv-cli\android> ./gradlew bundleRelease

> Configure project :app

Installing unimodules:
 unimodules-core@1.0.0 from F:\native\Bazar3\New\mstore-multi-vendor-v1.3.1\mstore-mv-cli\node_modules\@unimodules\core
 unimodules-react-native-adapter@1.0.2 from F:\native\Bazar3\New\mstore-multi-vendor-v1.3.1\mstore-mv-cli\node_modules\@unimodules\react-native-adapter
 expo-ads-admob@4.0.0 from F:\native\Bazar3\New\mstore-multi-vendor-v1.3.1\mstore-mv-cli\node_modules\expo-ads-admob
 expo-constants@4.0.0 from F:\native\Bazar3\New\mstore-multi-vendor-v1.3.1\mstore-mv-cli\node_modules\expo-constants
 expo-facebook@4.0.0 from F:\native\Bazar3\New\mstore-multi-vendor-v1.3.1\mstore-mv-cli\node_modules\expo-facebook
 expo-file-system@4.0.0 from F:\native\Bazar3\New\mstore-multi-vendor-v1.3.1\mstore-mv-cli\node_modules\expo-file-system
 expo-image-picker@4.0.0 from F:\native\Bazar3\New\mstore-multi-vendor-v1.3.1\mstore-mv-cli\node_modules\expo-image-picker
 expo-linear-gradient@4.0.0 from F:\native\Bazar3\New\mstore-multi-vendor-v1.3.1\mstore-mv-cli\node_modules\expo-linear-gradient
 expo-localization@4.0.0 from F:\native\Bazar3\New\mstore-multi-vendor-v1.3.1\mstore-mv-cli\node_modules\expo-localization
 expo-permissions@4.0.0 from F:\native\Bazar3\New\mstore-multi-vendor-v1.3.1\mstore-mv-cli\node_modules\expo-permissions
 expo-web-browser@4.0.0 from F:\native\Bazar3\New\mstore-multi-vendor-v1.3.1\mstore-mv-cli\node_modules\expo-web-browser
 unimodules-barcode-scanner-interface@1.0.0 from F:\native\Bazar3\New\mstore-multi-vendor-v1.3.1\mstore-mv-cli\node_modules\unimodules-barcode-scanner-interface
 unimodules-camera-interface@1.0.0 from F:\native\Bazar3\New\mstore-multi-vendor-v1.3.1\mstore-mv-cli\node_modules\unimodules-camera-interface
 unimodules-constants-interface@1.0.0 from F:\native\Bazar3\New\mstore-multi-vendor-v1.3.1\mstore-mv-cli\node_modules\unimodules-constants-interface
 unimodules-face-detector-interface@1.0.0 from F:\native\Bazar3\New\mstore-multi-vendor-v1.3.1\mstore-mv-cli\node_modules\unimodules-face-detector-interface
 unimodules-file-system-interface@1.0.0 from F:\native\Bazar3\New\mstore-multi-vendor-v1.3.1\mstore-mv-cli\node_modules\unimodules-file-system-interface
 unimodules-font-interface@1.0.0 from F:\native\Bazar3\New\mstore-multi-vendor-v1.3.1\mstore-mv-cli\node_modules\unimodules-font-interface
 unimodules-image-loader-interface@1.0.0 from F:\native\Bazar3\New\mstore-multi-vendor-v1.3.1\mstore-mv-cli\node_modules\unimodules-image-loader-interface
 unimodules-permissions-interface@1.0.0 from F:\native\Bazar3\New\mstore-multi-vendor-v1.3.1\mstore-mv-cli\node_modules\unimodules-permissions-interface
 unimodules-sensors-interface@1.0.0 from F:\native\Bazar3\New\mstore-multi-vendor-v1.3.1\mstore-mv-cli\node_modules\unimodules-sensors-interface
 unimodules-task-manager-interface@1.0.0 from F:\native\Bazar3\New\mstore-multi-vendor-v1.3.1\mstore-mv-cli\node_modules\unimodules-task-manager-interface
WARNING: The onesignal-gradle-plugin MUST be before com.android.application!
   Please put onesignal-gradle-plugin first OR update to com.android.tools.build:gradle:3.0.0 or newer!
WARNING: The specified Android SDK Build Tools version (28.0.2) is ignored, as it is below the minimum supported version (28.0.3) for Android Gradle Plugin 3.2.1.
Android SDK Build Tools 28.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '28.0.2'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

> Configure project :react-native-vector-icons
WARNING: The specified Android SDK Build Tools version (28.0.2) is ignored, as it is below the minimum supported version (28.0.3) for Android Gradle Plugin 3.2.1.
Android SDK Build Tools 28.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '28.0.2'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

> Configure project :react-native-onesignal
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html 
WARNING: Configuration 'testCompile' is obsolete and has been replaced with 'testImplementation' and 'testApi'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html 
WARNING: Configuration 'testApi' is obsolete and has been replaced with 'testImplementation'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html 
WARNING: The specified Android SDK Build Tools version (28.0.2) is ignored, as it is below the minimum supported version (28.0.3) for Android Gradle Plugin 3.2.1.
Android SDK Build Tools 28.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '28.0.2'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

> Configure project :react-native-gesture-handler
WARNING: The specified Android SDK Build Tools version (28.0.2) is ignored, as it is below the minimum supported version (28.0.3) for Android Gradle Plugin 3.2.1.
Android SDK Build Tools 28.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '28.0.2'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

> Task :app:bundleReleaseJsAndAssets   
warning: the transform cache was reset.
Loading dependency graph, done.

index.js: Cannot find module 'babel-plugin-transform-remove-console' from 'F:\native\Bazar3\New\mstore-multi-vendor-v1.3.1\mstore-mv-cli'

Error: Cannot find module 'babel-plugin-transform-remove-console' from 'F:\native\Bazar3\New\mstore-multi-vendor-v1.3.1\mstore-mv-cli'
    at Function.module.exports [as sync] (F:\native\Bazar3\New\mstore-multi-vendor-v1.3.1\mstore-mv-cli\node_modules\resolve\lib\sync.js:58:15)
    at resolveStandardizedName (F:\native\Bazar3\New\mstore-multi-vendor-v1.3.1\mstore-mv-cli\node_modules\@babel\core\lib\config\files\plugins.js:101:31)
    at resolvePlugin (F:\native\Bazar3\New\mstore-multi-vendor-v1.3.1\mstore-mv-cli\node_modules\@babel\core\lib\config\files\plugins.js:54:10)
    at loadPlugin (F:\native\Bazar3\New\mstore-multi-vendor-v1.3.1\mstore-mv-cli\node_modules\@babel\core\lib\config\files\plugins.js:62:20)
    at createDescriptor (F:\native\Bazar3\New\mstore-multi-vendor-v1.3.1\mstore-mv-cli\node_modules\@babel\core\lib\config\config-descriptors.js:154:9)
    at F:\native\Bazar3\New\mstore-multi-vendor-v1.3.1\mstore-mv-cli\node_modules\@babel\core\lib\config\config-descriptors.js:109:50
    at Array.map (<anonymous>)
    at createDescriptors (F:\native\Bazar3\New\mstore-multi-vendor-v1.3.1\mstore-mv-cli\node_modules\@babel\core\lib\config\config-descriptors.js:109:29)
    at createPluginDescriptors (F:\native\Bazar3\New\mstore-multi-vendor-v1.3.1\mstore-mv-cli\node_modules\@babel\core\lib\config\config-descriptors.js:105:10)


> Task :app:bundleReleaseJsAndAssets FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:bundleReleaseJsAndAssets'.
> Process 'command 'cmd'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 58s
1 actionable task: 1 executed

**Comment by ZamanGoraya** [comment]
i have used an other method "Publishing to Google Play Store" by Generating an upload key and the error was which i upload...

**Comment by ZamanGoraya** [comment]
@minhcasi  can you help me...?

**Comment by minhcasi** [comment]
@ZamanGoraya  - pls help to check this guide - https://docs.expo.io/versions/latest/sdk/google/#deploying-to-a-standalone-app-on-android - thanks
