### ISSUE TITLE
[my-product] - fluxstore woocommerce

### ISSUE THREAD

**Issue by Therocky20** [inspireui/support#1236]
---------

1. My issue - Problems with wire transfer and paypal apis rest. It doens't work on LIVE mode only on SANDBOX

2. Screenshots 

![Screenshot_1571216551](https://user-images.githubusercontent.com/54363592/66909458-17707d80-f00d-11e9-9703-a1eecd703930.png) here is paypal infinite loading
![Screenshot_1571220247](https://user-images.githubusercontent.com/54363592/66909479-20614f00-f00d-11e9-9a47-60f50626a503.png) here is wire transfer problem

i have already purchased the product i can give you the purchase code

**Comment by minhtruong315** [comment]
<img width="338" alt="Screen Shot 2019-10-16 at 5 12 43 PM" src="https://user-images.githubusercontent.com/10402500/66910188-49e3a000-f038-11e9-8c1c-64368e15a3cb.png">
pls update production to true if you wanna use live

**Comment by Therocky20** [comment]
ok thank you. Please check also wire transfer problem

**Comment by minhtruong315** [comment]
do your website work with wire transfer?

**Comment by Therocky20** [comment]
yes of course its all enabled and configured

**Comment by minhtruong315** [comment]
pls record screenshot and send me config.dart file

**Comment by minhtruong315** [comment]
no response

**Comment by Therocky20** [comment]
Sorry for late response it was weekend for us. in 3 Hours i send you all you asked

**Comment by Therocky20** [comment]
Hi please solve me the wire transfer. I send you config files.


[common.zip](https://github.com/inspireui/support/files/3782400/common.zip)
