### ISSUE TITLE
[FluxStore] - Translation not working in Magento!

### ISSUE THREAD

**Issue by obadaKraishan** [inspireui/support#1237]
Hi,

In my APP even if i change the locate language to Arabic and i have added Arabic store view and i have translate all the products but still in the app it shown the english for magento

![Screen Shot 2019-10-16 at 5 22 36 PM](https://user-images.githubusercontent.com/28910488/66928435-09852180-f03a-11e9-95f8-d59682a44acc.png)

![Screen Shot 2019-10-16 at 5 22 53 PM](https://user-images.githubusercontent.com/28910488/66928436-0a1db800-f03a-11e9-94bc-adaa61a0b5f4.png)

![Screen Shot 2019-10-16 at 4 48 44 PM](https://user-images.githubusercontent.com/28910488/66928451-0f7b0280-f03a-11e9-9518-880ab223c798.png)

![Screen Shot 2019-10-16 at 4 49 16 PM](https://user-images.githubusercontent.com/28910488/66928461-143fb680-f03a-11e9-95ab-817754b3b03c.png)

**Comment by minhcasi** [comment]
noted for investigating - thanks

**Comment by minhtruong315** [comment]
The current feature does not support multi language for the Magento yet, due to the limit of Rest API, we will upgrade on later release - thank you!

**Comment by obadaKraishan** [comment]
ohh okay that's the issue, Thank you
