### ISSUE TITLE
Theme Installation Issues.

### ISSUE THREAD

**Issue by VikashMLRS** [inspireui/support#1238]
Try to integrate Theme from following path - eStore-1.3.0\Source\mobile-evastore-theme>expo start
But i get error message : 
Invalid regular expression: /(.*\\__fixtures__\\.*|node_modules[\\\]react[\\\]dist[\\\].*|website\\node_modules\\.*|heapCapture\\bundle\.js|.*\\__tests__\\.*)$/: Unterminated character class

Metro Bundler process exited with code 1
![image](https://user-images.githubusercontent.com/52529480/66940468-a065d400-f062-11e9-904c-bd3bf734c96c.png)

**Comment by minhcasi** [comment]
@VikashMLRS - could you share proof of purchased by take the screenshot from - https://codecanyon.net/downloads - thank you!

**Comment by VikashMLRS** [comment]
![image](https://user-images.githubusercontent.com/52529480/66982625-2f5f0480-f0d4-11e9-8466-5966c5e08515.png)

**Comment by minhtruong315** [comment]
@VikashMLRS can you send me all source code via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/1238

**Comment by minhtruong315** [comment]
no response
