### ISSUE TITLE
[fluxstore] - pincode issue 

### ISSUE THREAD

**Issue by immortal-kid** [inspireui/support#1239]
my purchase http://prntscr.com/pjvdg2

**1**.i have added these http://prntscr.com/pk677m pincodes in shipping zone because we only ship to those places, but in app it is taking any random pincodes and letting place order
Error: http://prntscr.com/pk6970.

**2.** Pincode is limited to 6 digit right? but pincode field is taking any random numbers more than 6 digits http://prntscr.com/pk69qc.

**3.** since my store support to 9 or 10 pincodes for now, can i add them manually as dropdown until u fix this bug?

**4**. **_well, u should give some importance to pincode thing, most of the people who owns eCommerce store wont support shipping globally, so everyone has their own rules set in shipping options, in my case i have limited to pincodes. since the fluxstore app is accepting random pincodes, we may get lot of random fake orders across the world. please fix this. atleast for now tell me how to make pincode dropdown untill u fix this._**

**5.** please support multiple shipping zones

**Comment by minhcasi** [comment]
Thank you for your great feedback, we will investigate a solution to fix on next release, it makes sense to focus for the multi shipping options and allow to config as default country.

Could you share the config files so that we could a have check as well ?

**Comment by immortal-kid** [comment]
until then can u tell me how to add dropdown in pincode field for 7 pincodes?

https://api.flutter.dev/flutter/material/DropdownButton-class.html i saw this link but i couldn't do it. plzzzz

**Comment by immortal-kid** [comment]
for config file, check the mail with subject #1239 fluxstore
