### ISSUE TITLE
[ListPro] Bugs report

### ISSUE THREAD

**Issue by lpzczar** [inspireui/support#124]
**Required Info (please complete the following information):**
 - Product: [List Pro]
 - Your Purchased Code: [ a07721f8-1944-4edb-949d-2733c0f4a33e]
(we may not reply if you are not our customer)

**Describe the bug**
Hi. First of all, thank you very much for reading my email. The reason for my email is to report a couple of errors and request support to solve them.

1. I need the listings ordered by nearby to user. Since they appear ordered according to the recent ones that were added. And we need the near ones to appear.

2. How can we delimit the number of news items that appear on the list? Since 18 and we only want to show 6. This on the home screen.

3. When I select a listing to see its details and I want to share it. Share the description of the listing and what I want to share is the URL of the listing. Help me share only the URL.

4. On the search screen, when selecting some filters such as category or features, the search engine does not work. It only shows "no results".

5. I do not see the rate of the listing in details or in the search lists and on the home screen.

6. How can I change the language of the listing price? Eg. I do not want to appear "inexpensive" I want it to be another value.

7. This is a very delicate mistake I found. When you selected a listing. I see the details as a photo gallery, telephone, address, etc. But its features take a while to load, at the same time as FAQ. But when I select another listing everything is updated, but the features and FAQs are not updated and shows me the values ​​of the previously selected listing. Help me fix it. Please.

8. In the home screen I would like to put in the Banner of the top part images that occupy the whole screen, slide style. I do not want news, or listing post. I want some personalized images with a URL. Is this possible to do?

9. It does not show me the images and it marks me error when opening any listing.

Thank u for your help!…

If you need something to perform tests with pleasure we can provide it…..

**Screenshots**

9.
![whatsapp image 2018-12-20 at 23 14 59](https://user-images.githubusercontent.com/19940455/50326368-99584e80-04af-11e9-87eb-cf417a898d59.jpeg)
![whatsapp image 2018-12-20 at 23 15 00](https://user-images.githubusercontent.com/19940455/50326369-99584e80-04af-11e9-86a3-ae9b3b96667d.jpeg)

**Additional context**

[Config.js.zip](https://github.com/inspireui/support/files/2701631/Config.js.zip)

**Comment by minhcasi** [comment]
Hi, thank you for report detail issue and screenshot, we will check and update later on this ticket - thank you!

**Comment by lpzczar** [comment]
Thank you. I urgently need to solve these problems because we are delaying work a lot.

**Comment by lpzczar** [comment]
Why did they close the case? I still do not receive an answer to my ticket.

**Comment by minhcasi** [comment]
sorry - is it close by mistake ? @thangvo9x 

@lpzczar we are updating new version and will test on your issues and update the status

**Comment by thangvo9x** [comment]
Hi. Sorry for this. We're on holiday. We'll check & reply to you ASAP. 
Thanks

**Comment by lpzczar** [comment]
They closed the case again and did not answer anything. I need an answer and we have been several weeks and do not support me.

**Comment by minhcasi** [comment]
@thangvo9x ?

**Comment by lpzczar** [comment]
I will send an email the specifications we require for support.

**Comment by minhcasi** [comment]
Sorry for the issues @lpzczar - please send to my email support@inspireui.com, you can reach to my Skype for further discussion: minhcasi - thank you!

**Comment by lpzczar** [comment]
We will send the mail, I hope you answer me in detail. Or if you require an extra payment for support just mention it.
