### ISSUE TITLE
[mstore-pro] - How to setup onesignal push notification?

### ISSUE THREAD

**Issue by harry503** [inspireui/support#1240]
1. The instruction in https://docs.inspireui.com/mstore/push-notification/ does not match with the file in 3.9.5

- For IOS, I cannot find anything in AppDelegate.m for self.oneSignal = [[RCTOneSignal alloc] initWithLaunchOptions:launchOptions appId:@ YOUR-APP-ID]

- For Android, I cannot find anything in android/app/build.grade for manifestPlaceholders = [onesignal_app id: "APP_ID ", onesignal_google_project number: "PROJECT_NUMBER "]

So, I only set onesignal in src/comon/Config.js
OneSignal: {
    appId: "892x96xx-7a9b-xxxxxxxxxxxxxxx"
},

I'm asking this because I got few errors in 
![Screen Shot 2019-10-17 at 09 14 06](https://user-images.githubusercontent.com/35995317/66972323-8659df00-f0be-11e9-9c71-74dcafd6ddf5.png)

I just want to make sure that I;m not missing anything. Please also update your documentation (https://docs.inspireui.com/mstore/push-notification)

**Comment by minhcasi** [comment]
@harry503 - the folder ios and android will be available from the mstore-pro

The mstore-expo is support to build with Expo framework - thank you!

**Comment by harry503** [comment]
We are using the Pro version v 3.9.5

But as i mentioned that the current code does not match with the documentation. Line of code that was mentioned in IOS and Android was not found in the android / ios folder.

So, I only set it up in Config.js.

Is it because the setup is changed and you guys made it easier just by putting the app id of the onesingnal in the config file and not need to set any file inside ios / android folder or am i missing something?

**Comment by minhcasi** [comment]
@harry503 - i will double-check with the technical team and will get back with you soon

@concuacon - pls suggestion

**Comment by harry503** [comment]
@concuacon Any update?

**Comment by concuacon** [comment]
@harry503 please check new documents of Onesignaln and use last version of Mstore Pro
https://documentation.onesignal.com/docs/react-native-sdk-setup

**Comment by minhcasi** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days - if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
