### ISSUE TITLE
[Mstore pro] - Cannot build in Xcode 11

### ISSUE THREAD

**Issue by binhetc** [inspireui/support#1241]
Hello,
I tried to build with Xcode 11 but I get that issue:
no such file or directory: '/Users/meocon/Downloads/mstore-3.9.5/mstore-pro/node_modules/react-native/ReactCommon/jsinspector/InspectorInterfaces.cpp'
![Ảnh chụp Màn hình 2019-10-17 lúc 10 36 57](https://user-images.githubusercontent.com/13253563/66976037-a0012380-f0ca-11e9-92af-89e5606463e2.png)

**Comment by concuacon** [comment]
@binhetc 
Hello, you can try to follow by step:

1. In Xcode clean build **Command+Shift+K** and close Xcode.

2. Open terminal cd to project and run: rm -rf node_modules/ && yarn && cd ios/ && rm -rf Pods/ && rm -rf Podfile.lock && pod install && cd ../ 

3. Open Xcode:

- File -> Project/Workspace settings

- Build System: dropdown -> change to Legacy Build system

- Run app.

**Comment by binhetc** [comment]
It works for me, thank you concuacon!

**Comment by concuacon** [comment]
Hi, we're glad that it help, please give us some feedback/rating to this page https://codecanyon.net/downloads if the product is helpful for your business, we are working hard to update more awesome and powerful features on next coming version release. Let us know if you have any feedback. Thank you very much! :blush:
