### ISSUE TITLE
[fluxstore] Cyrillic fonts not correctly showing on home screen

### ISSUE THREAD

**Issue by Ca3aH138** [inspireui/support#1243]
In the app - all connected fonts working fine, russian symbols showing correctly. On home screen product names showing correctly too. But widget heading on home page showing as broken symbols.
I'm connected my config.json file on hosting by config.dart file in app:
![5da7675523692698528549](https://user-images.githubusercontent.com/10209815/66985753-1fd8bf00-f0c6-11e9-94a9-bb2c1ca73b9e.jpeg)
Using default homepage template and added russian heading:
![5da766158e8e0570683361](https://user-images.githubusercontent.com/10209815/66985826-4d256d00-f0c6-11e9-8cb0-9cd3e12bad27.jpeg)
Result:
![5da76689db5b1443824283](https://user-images.githubusercontent.com/10209815/66985841-531b4e00-f0c6-11e9-9f0a-e4ca043a7908.jpeg)
What's i've done wrong? I'm checked config.json charset - it's UTF-8 as in other app files. In 
strings_ru.arb and in i18n.dart files same strings is translated too, but as i know - strings in config.json not required to translate in this files.

Proof of purchase:
![proof](https://user-images.githubusercontent.com/10209815/66986213-1bf96c80-f0c7-11e9-92f6-8875c029b908.PNG)

**Comment by Ca3aH138** [comment]
I'm also tried to write font style for widgets/horizontal/horizontal_list_items.dart and searched for any place, where it can be written - but unsuccessfully

**Comment by Ca3aH138** [comment]
I'm also checked name on english - working fine too, but on russian with any font - broken symbols. Please help me, I need to complete this project for customer...

**Comment by minhcasi** [comment]
@Ca3aH138  - pls edit the font name from common/styles.dart - https://tppr.me/QR7It - We display the header as the Roboto so that not work with Russian as your screenshot.

**Comment by Ca3aH138** [comment]
I tried 4 fonts - unsuccesfully. But then I changed config.json path from hosted to local (lib/common/config.json) - and it's works. So, I will change my hosting-provider. Thanks you for help, my app is ready to publish.

**Comment by minhcasi** [comment]
Thank you, I'm glad that you have resolved the issues, please share your product on the store when it is approved, I will ask the team to give some great rating for your app ;)
