### ISSUE TITLE
[my-product] - Fluxstore Woocommerce version 1.5.5

### ISSUE THREAD

**Issue by Therocky20** [inspireui/support#1245]
---------

1. My issue -  I have problems when i try to run in debug mode the app. 
for the product license i have already some tickets opened i will let see the license in phase of support. 

2. Screenshots - here is the screenshoot
![android](https://user-images.githubusercontent.com/54363592/67074506-912d7600-f189-11e9-8e57-aa4d0b5874e0.jpg)

**Comment by immortal-kid** [comment]
i updated kotlin, after that i ran flutter clean, it fixed

**Comment by Therocky20** [comment]
i solved alone
