### ISSUE TITLE
[MStore Magento] - Version Issue

### ISSUE THREAD

**Issue by wedanbusiness** [inspireui/support#1246]
1. My issue:
Right now I have installed expo 3.3.0. When running this, I get error saying SDK version must at least 33.0.0. Upon checking the package.json and app.json, version is only 32. How can I solve this issue?

2. Screenshots
[https://ibb.co/7bWTYNX](url)

3. My screenshot of the purchase product or my comment:
https://ibb.co/vPhL2rP

**Comment by minhcasi** [comment]
@wedanbusiness  - we will have a check and let you know - thanks

**Comment by minhtruong315** [comment]
@wedanbusiness we will upgrade expo

**Comment by wedanbusiness** [comment]
Thank you. When can you provide the upgraded version? And how can we pull this?

**Comment by minhtruong315** [comment]
@wedanbusiness I upgraded expo to version 0.35. It's available on next some days

**Comment by wedanbusiness** [comment]
Hello @minhtruong315, may we know when and how can we get the upgraded version before closing this issue?
