### ISSUE TITLE
[my-product] - Fluxstore woocommerce 1.5.5 Shipping problems

### ISSUE THREAD

**Issue by Therocky20** [inspireui/support#1247]
---------

1. My issue - I have problem with shipping.

2. Screenshots
![Screenshot_1571393681](https://user-images.githubusercontent.com/54363592/67086429-0193c180-f1a1-11e9-81a2-ac8795263ad8.png)

3. My screenshot of the purchase product or my comment: i will give purchase code

**Comment by Senior-Gamal** [comment]
add the zone shipping id in config.dart ( "ZoneIdShipping": 1 )

**Comment by minhtruong315** [comment]
@Therocky20 send me config.dart, config.json and admin info via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/1247

**Comment by minhtruong315** [comment]
@Senior-Gamal I see your website has 2 zone id for shipping: 2 and 3. Try to change ZoneIdShipping to 2 or 3

**Comment by Therocky20** [comment]
Can you provide me the config file with that edit? At that time i don't know how to write it properly and our developers are too busy. Please attach the config file that i passed you

**Comment by Therocky20** [comment]
Hi please answer me i need the config files with that zone shipping added. I tried to add myself but with no success.

**Comment by minhcasi** [comment]
- screenshot common/config.dart - https://tppr.me/MIbGZ
- the zone id should match with the id when you edit the shipping zone from woocommerce site

**Comment by Therocky20** [comment]
Hi i can't see the image, please check the link

**Comment by Therocky20** [comment]
Hi i saw finally the screenshot. Now how can i add both zones? i need both. It's not casual that i have 2 zones, they are all operatives

**Comment by minhtruong315** [comment]
@Therocky20 
- You need to edit ZoneIdShipping in config.dart like this "ZoneIdShipping": [2, 3],
- Then update getShippingMethods in services/woo_commerce.dart
```
@override
  Future<List<ShippingMethod>> getShippingMethods(
      {Address address, String token}) async {
    try {
      List<ShippingMethod> list = [];
      for (var id in kAdvanceConfig["ZoneIdShipping"]) {
        var response = await wcApi.getAsync("shipping/zones/$id/methods");
        if (response is Map && isNotBlank(response["message"])) {
          throw Exception(response["message"]);
        } else {
          for (var item in response) {
            list.add(ShippingMethod.fromJson(item));
          }
        }
      }
      return list;
    } catch (e) {
      throw e;
    }
  }
```
