### ISSUE TITLE
[MStore Pro] - “cebuilder.sh” can’t be opened 

### ISSUE THREAD

**Issue by Riyashanke** [inspireui/support#1248]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. Sir for PRO version it's showing “cebuilder.sh” can’t be opened because Sandbox is not allowed to open documents in Terminal. So I couldn't test the pro version. Kindly Guide Me Sir That will be very helpful. 

2. <img width="400" alt="cebuilder sh" src="https://user-images.githubusercontent.com/56667597/67094078-a5e12c80-f1d0-11e9-80d9-2a66956a8a51.png">

3. 
<img width="741" alt="purchase proof" src="https://user-images.githubusercontent.com/56667597/67094392-6535e300-f1d1-11e9-8404-cc4ba57719b8.png">

**Comment by minhcasi** [comment]
@concuacon  - pls help for checking this issue - thanks

**Comment by Riyashanke** [comment]
> @concuacon - pls help for checking this issue - thanks
 Sir Kindly help me I couldn't test Mstore Pro version because of this Error. Awaiting for your reply.

**Comment by concuacon** [comment]
Hello, @Riyashanke I have just released a new version of ceBuilder [0.38.0](https://github.com/inspireui/cebuilder/releases/tag/0.38.0) please delete the old CeBuilder and install the new version. 
**Before running ceBuilder please turn off all open terminal**
