### ISSUE TITLE
[Mstore Pro] - Issues in Version: 3.9.6

### ISSUE THREAD

**Issue by Riyashanke** [inspireui/support#1249]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. Sir I tried with your latest version 3.9.6 with the new Mstore API. Good News is all in Mstore Expo version Payment Gateway is now working but there are still some bugs in that like after order completion in the My Order Page if we check our order it shows Shipping Address as blank like ,,,,,,,, this. And if the payment is failed it shows Pending in Status but there is no option to make that payment again. And the bad news is Still no luck in Coupon and review system. But for Mstore PRO version it’s still showing “cebuilder.sh” can’t be opened because Sandbox is not allowed to open documents in Terminal. So I couldn’t test the Mstore Pro Version. Kindly guide me sir that will be very helpful. Am in need of launching this app ASAP, Sir

2. Screenshot Issues of payment completion and order status with no shipping address
![IMG_2742](https://user-images.githubusercontent.com/56667597/67098074-1ab86480-f1d9-11e9-8683-d5ffb7a285a0.PNG)

Screenshot Issues of failed Payment Order and no option for Repayment in order status
![payment failed](https://user-images.githubusercontent.com/56667597/67098207-5eab6980-f1d9-11e9-909d-d261a0b8676a.PNG)

Screenshot Issues for Review Option
![review](https://user-images.githubusercontent.com/56667597/67098292-8bf81780-f1d9-11e9-9c81-6d1d16407803.png)

Screenshot for Coupon Code
![IMG_2745](https://user-images.githubusercontent.com/56667597/67098499-f3ae6280-f1d9-11e9-8a32-3e7ea9dbf2f1.PNG)
![coupon](https://user-images.githubusercontent.com/56667597/67098510-f7da8000-f1d9-11e9-82b0-e73b3c016105.png)

Screenshot for Cebuilder Error in Pro Version for running ios and android 
<img width="400" alt="cebuilder sh" src="https://user-images.githubusercontent.com/56667597/67098596-2b1d0f00-f1da-11e9-9c6c-ec6d0ffd0212.png">

3. Screenshot of the purchase product or my comment:

<img width="629" alt="purchase" src="https://user-images.githubusercontent.com/56667597/67098771-64557f00-f1da-11e9-9ed9-aa6ab62606ee.png">

3. Expo Version Config file 
[Expo Version Config file .zip](https://github.com/inspireui/support/files/3744176/Expo.Version.Config.file.zip)

Pro Version Config Files
[Pro Version Config file.zip](https://github.com/inspireui/support/files/3744183/Pro.Version.Config.file.zip)

**Comment by minhcasi** [comment]
@Riyashanke - thank you for the detail, we will investigate and let you know

**Comment by concuacon** [comment]
Hello, @Riyashanke  

- **Payment completion and order status with no shipping address**
try run: rm -rf node_modules/ && yarn && cd ios && rm -rf Pods/ && rm -rf Podfile.lock && pod install && cd && react-native run-ios 

- **CeBuilder**

I have just released a new version of ceBuilder [0.38.0](https://github.com/inspireui/cebuilder/releases/tag/0.38.0) please delete the old CeBuilder and install the new version. 
Please close all terminal working, before run CeBuilder

**Comment by Riyashanke** [comment]
Hi, @concuacon what about the coupon **code and review options** and **failed Payment Order and no option for Repayment in order status.** 

**Payment completion and order status with no shipping address** in expo version not on the pro version

**Comment by concuacon** [comment]
@Riyashanke i'll check and feedback to you soon.

**Comment by Riyashanke** [comment]
Hi @concuacon Accountkit is not supported by Facebook, So couldn't setup accountkit account (ID) what to do any other options. Kindly guide me

**Comment by concuacon** [comment]
I think there will be no solution, because as mentioned in the fb document
<img width="804" alt="Screen Shot 2019-10-28 at 9 59 42 AM" src="https://user-images.githubusercontent.com/11958061/67650348-3b1db700-f96f-11e9-8fa9-bb396c66e2c6.png">

**Comment by Riyashanke** [comment]
Hi @concuacon,  its little urgent. So kindly help me in solving the issues in Review & Coupon Code, Payment Failure options in Pro and Expo methods. And after testing with Physical Device with iOS (iPhone XR) once we choose FB login it shows open FB App and after completing it redirects to our Shopping (Mstore) App but not Logging In.  But it works when we try to login with our app. Kindly solve this it's little urgent I am planning to launch this app in November 1st Week.

**Comment by concuacon** [comment]
@Riyashanke Have you updated to the latest Mstore Api version?

**Comment by Riyashanke** [comment]
> @Riyashanke Have you updated to the latest Mstore Api version?

Am using the latest API Version only. Kindly help me in solving the issues

**Comment by minhcasi** [comment]
@Riyashanke - could you zip the whole source code and send us again for checking this issue - email: support@inspireui.com

**Comment by minhcasi** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!

**Comment by Riyashanke** [comment]
Hi @minhcasi @concuacon  I have mailed the complete source code through WeTransfer. Kindly check and guide me sir. Please.
