### ISSUE TITLE
[MStore] subcategories not avaliable in mobile app photo

### ISSUE THREAD

**Issue by alaradi2006** [inspireui/support#125]
**Mandatory Info (please complete the following information):**
 - Product: [e.g. MStore, ListApp]
 - Your Purchased Code: [get from https://codecanyon.net/downloads]
(we may not reply if you are not our customer)

**Describe the issues**
i made main category called grocery and made subcategories called
baby world
pet food
dairy products 

in mobile app if i click on grocery it showed all products together 
theres no thumbnail for the subcategories as its diffcult to search between thousands or prodcuts all mixed 

**Screenshots**

**Additional context**
Add any other detail logs about the problem here.

**Comment by alaradi2006** [comment]
in side menu theres subcategories titles but in case you click on grocery shortcut it will take you to all prodcuts together 
it has to be click on grocery then you will see thumbnail photo for baby world , pet food 
then you click on baby world and then you will see all products regarding baby world it has to be like this

**Comment by minhcasi** [comment]
Can you share the screenshot? Thank you!
