### ISSUE TITLE
I'm using CEBuilder latest version. And I choose the folder mstore-mv expo

### ISSUE THREAD

**Issue by simdanonline** [inspireui/support#1250]
I'm using CEBuilder latest version. And I choose the folder mstore-mv expo.
 It shows the Rest API is not working correctly !

Mstore Multi vendor

![mstore-issue](https://user-images.githubusercontent.com/53178201/67104143-5abe1e00-f1be-11e9-85d3-d040ba2ed2f0.png)

**Comment by minhcasi** [comment]
@simdanonline - we will double check the issue and let you know, thank you!

**Comment by minhcasi** [comment]
@simdanonline - could you attache the config files from common folder (common/appconfig.json and config.js) here ?

**Comment by simdanonline** [comment]
https://drive.google.com/drive/folders/1PTfZrfYw7EMIHFtWPc4HSgTwRSfRUFV_?usp=sharing

The files are here

**Comment by simdanonline** [comment]
CEBuilder right now is saying 'Currently, CEbuilder hasn't supported this project yet.'

**Comment by concuacon** [comment]
Hello, @simdanonline I have just released a new version of ceBuilder [0.38.0](https://github.com/inspireui/cebuilder/releases/tag/0.38.0) please delete the old CeBuilder and install the new version. 
It shows the Rest API is not working correctly! => Please change WooCommerce config in file Appconfig.json with your WooCommerce config to fix
