### ISSUE TITLE
[my-product] - 

### ISSUE THREAD

**Issue by simdanonline** [inspireui/support#1251]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue    npm install, after I download from codecanyon, I unzip file, open cmd.exe in the mstore-mv expo folder......it gives error.
npm ERR! code EPERM npm ERR! syscall unlink npm ERR! path C:\Users\wendzreeofficial\Desktop\mstore-mv original\mstore-multi-vendor-v1.3.1\mstore-mv-expo\node_modules\.staging\react-native-72b7d8d7\RNTester\RNTesterIntegrationTests\ReferenceImages\RNTester-js-RNTesterApp.ios\testScrollViewExample_1-iOS10@2x.png npm ERR! errno -4048 npm ERR! Error: EPERM: operation not permitted, unlink ‘C:\Users\wendzreeofficial\Desktop\mstore-mv original\mstore-multi-vendor-v1.3.1\mstore-mv-expo\node_modules\.staging\react-native-72b7d8d7\RNTester\RNTesterIntegrationTests\ReferenceImages\RNTester-js-RNTesterApp.ios\testScrollViewExample_1-iOS10@2x.png‘ npm ERR! [OperationalError: EPERM: operation not permitted, unlink ‘C:\Users\wendzreeofficial\Desktop\mstore-mv original\mstore-multi-vendor-v1.3.1\mstore-mv-expo\node_modules\.staging\react-native-72b7d8d7\RNTester\RNTesterIntegrationTests\ReferenceImages\RNTester-js-RNTesterApp.ios\testScrollViewExample_1-iOS10@2x.png‘] { npm ERR! cause: [Error: EPERM: operation not permitted, unlink ‘C:\Users\wendzreeofficial\Desktop\mstore-mv original\mstore-multi-vendor-v1.3.1\mstore-mv-expo\node_modules\.staging\react-native-72b7d8d7\RNTester\RNTesterIntegrationTests\ReferenceImages\RNTester-js-RNTesterApp.ios\testScrollViewExample_1-iOS10@2x.png‘] { npm ERR! errno: -4048, npm ERR! code: ‘EPERM’, npm ERR! syscall: ‘unlink’, npm ERR! path: ‘C:\\Users\\wendzreeofficial\\Desktop\\mstore-mv original\\mstore-multi-vendor-v1.3.1\\mstore-mv-expo\\node_modules\\.staging\\react-native-72b7d8d7\\RNTester\\RNTesterIntegrationTests\\ReferenceImages\\RNTester-js-RNTesterApp.ios\\testScrollViewExample_1-iOS10@2x.png‘ npm ERR! }, npm ERR! stack: “Error: EPERM: operation not permitted, unlink ‘C:\\Users\\wendzreeofficial\\Desktop\\mstore-mv original\\mstore-multi-vendor-v1.3.1\\mstore-mv-expo\\node_modules\\.staging\\react-native-72b7d8d7\\RNTester\\RNTesterIntegrationTests\\ReferenceImages\\RNTester-js-RNTesterApp.ios\\testScrollViewExample_1-iOS10@2x.png’”, npm ERR! errno: -4048, npm ERR! code: ‘EPERM’, npm ERR! syscall: ‘unlink’, npm ERR! path: ‘C:\\Users\\wendzreeofficial\\Desktop\\mstore-mv original\\mstore-multi-vendor-v1.3.1\\mstore-mv-expo\\node_modules\\.staging\\react-native-72b7d8d7\\RNTester\\RNTesterIntegrationTests\\ReferenceImages\\RNTester-js-RNTesterApp.ios\\testScrollViewExample_1-iOS10@2x.png’, npm ERR! parent: ‘mstore-mv-expo’ npm ERR! } npm ERR! npm ERR! The operation was rejected by your operating system. npm ERR! It’s possible that the file was already in use (by a text editor or antivirus), npm ERR! or that you lack permissions to access it. npm ERR! npm ERR! If you believe this might be a permissions issue, please double-check the npm ERR! permissions of the file and its containing directories, or try running npm ERR! the command again as root/Administrator

2. Screenshots  

3. My screenshot of the purchase product or my comment:
![mstore-issue2](https://user-images.githubusercontent.com/53178201/67104551-0e271280-f1bf-11e9-9db2-9f537e1421bc.png)

3. Config files (optional) 
https://drive.google.com/file/d/1bSDpg-YMr9jeY--GjE9lD2dUmnncBDoe/view?usp=sharing

**Comment by minhcasi** [comment]
@simdanonline - pls try to reinstall nodejs - https://nodejs.org and yarn - https://yarnpkg.com

Then try with this script: yarn install 

Let us know your checking

**Comment by simdanonline** [comment]
Yarn install is successful.
But expo build:android says ---->
Publishing to channel 'default'...
Building iOS bundle
connect ECONNREFUSED 127.0.0.1:19001
Set EXPO_DEBUG=true in your env to view the stack trace.

**Comment by simdanonline** [comment]
I already configure my details.
Did just yarn install.
And then enter expo build:android

**Comment by simdanonline** [comment]
appconfig,json
config.js
package.json

All in this folder

https://drive.google.com/drive/folders/1PTfZrfYw7EMIHFtWPc4HSgTwRSfRUFV_?usp=sharing

**Comment by concuacon** [comment]
@simdanonline thank you for the detail, we will investigate and let you know

**Comment by minhcasi** [comment]
@simdanonline - please help to try with latest version 1.3.2 and let us know if you have any issue, you can also try to run with the Cebuilder - thank you!
