### ISSUE TITLE
Problem fluxstore opencart

### ISSUE THREAD

**Issue by jimnystore** [inspireui/support#1252]
Hi, I have several problems with fluxstore,

1) I try to find something in the app's search engine and it tells me (we found 0 products)

2) The products does not show the main image, it always shows the second image.

3) I try to start section and it shows the following error
Warning: FormatException: Unexpectd character (at character 1) <! DOCTYPE HTML PUBLIC "- // IETF // DTD HTML 2.0 // EN">

4) I am looking for category_items.dart to modify the category and not find it.

**Comment by minhcasi** [comment]
@jimnystore - could you help to share the screenshot of your purchase from - https://codecanyon.net/downloads (include your username+product)

Then share use your config file for checking, pls also make sure you have installed all require plugin - https://docs.inspireui.com/fluxstore/woocommerce-setup/

**Comment by jimnystore** [comment]
purchase
![compra](https://user-images.githubusercontent.com/56736981/67161394-6b8ea100-f330-11e9-82e7-dbbfe9386e41.png)


installed plugin opencart 
![mstore modulo](https://user-images.githubusercontent.com/56736981/67161405-91b44100-f330-11e9-82aa-0cf19c1c6148.png)

**Comment by minhtruong315** [comment]
@jimnystore can you send me config.dart, config.json and admin info via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/1252

**Comment by govindh163** [comment]
Having the Same Issue Here Too!!

**Comment by jimnystore** [comment]
@govindh163 If I test the configuration with https the same error

**Comment by jimnystore** [comment]
@minhtruong315 Hello, mail was sent with the requested data, I await a response. Thank you

**Comment by minhtruong315** [comment]
I checked your website, but i dont know why your website dont work with my extension,

**Comment by kurkuteabhi** [comment]
I have same issue with opencart setup. even i have tried for demo config files form example folder 

![purches](https://user-images.githubusercontent.com/43174699/70368512-7649c900-18d1-11ea-9ddf-f4710b45697f.jpg)
![Screenshot_1575688530](https://user-images.githubusercontent.com/43174699/70368513-777af600-18d1-11ea-91e4-fe83878c03f6.png)
