### ISSUE TITLE
Onesignal does not work !

### ISSUE THREAD

**Issue by erknertn** [inspireui/support#1254]
Although we describe everything as we do, notifications do not come. does not recognize the device. We're not getting any signal. Tested on iOS and android. It was build.

**Comment by minhcasi** [comment]
@erknertn - could you help to take screenshot purchased code from - https://codecanyon.net/downloads

Also let us know what the product that have this issue?

**Comment by erknertn** [comment]
Hi,
Mstore multivendor
Item Purchase Code: 014a35ed-08f8-42b1-bb3c-b746ee7f202a

**Comment by minhcasi** [comment]
Hi @erknertn  - the onesignal is only support for the cli (from the download package you can get this folder) - you can try to re-install this library to cli version - https://github.com/geektimecoil/react-native-onesignal - thanks
