### ISSUE TITLE
[Evastore] - Login page issue

### ISSUE THREAD

**Issue by WorkflowAutomation** [inspireui/support#1255]
1. My issue
 I have connected everything in Evstore with Shopify. Now I would like to place an order, here it is asking me to log in. I have logged in with our frontend store credentials but it is not accepting those, displaying as not registered. Then I have tried to register on that page again I tried to log in, there also it is showing the same message. So please help us what are the credentials we have to use to log in on Evastore template after we connected with Shopify?

**Comment by minhcasi** [comment]
could you help to share the configfiles from common folder (appconfig.json  and the config.js) - thank you!

**Comment by WorkflowAutomation** [comment]
Yeah, Sure.
Appconfig.js-
  "Shopify": {
    "url": "https://weavesmart-com.myshopify.com",
    "graphqlUrl": "https://weavesmart-com.myshopify.com/api/graphql",
    "storeAccessToken": "xxxxxxxxxxxxxxxxxx",
    "shopId": "7433215"
  }
}

config.js-
/** @format */

import Constants from "./Constants";
import Icons from "./Icons";

export default {
  /**
   * Step 1: change to your website shopify graphqlUrl, and storeAccessToken
   * https://help.shopify.com/en/api/custom-storefronts/storefront-api/getting-started
   * Moved AppConfig.json
   */

  // to config custompage
  Wordpress: {
    url: "http://mstore.io",
  },

  /**
     Step 2: Setting Product Images
     - ProductSize: Explode the guide from: update the product display size: https://mstore.gitbooks.io/mstore-manual/content/chapter5.html
     The default config for ProductSize is disable due to some problem config for most of users.
     If you have success config it from the Wordpress site, please enable to speed up the app performance
     - HorizonLayout: Change the HomePage horizontal layout - https://mstore.gitbooks.io/mstore-manual/content/chapter6.html
     */
  ProductSize: {
    enable: false,
    CatalogImages: { width: 300, height: 360 },
    SingleProductImage: { width: 600, height: 720 },
    ProductThumbnails: { width: 180, height: 216 },
  },

  /**
   * Step 3: Setting Home screen, category screen
   * Follow this article to use Graphql https://help.shopify.com/en/api/custom-storefronts/storefront-api/graphql
   * Video tutorial https://www.dropbox.com/s/m4kmp0quh8qplz3/Screen%20Recording%202018-11-05%20at%202.22.21%20PM.mov?dl=0
   */
  SpaceLayout: 15, // setting align right
  /**
   * config home page show
   * - horizontal with multi collection id or
   * - vertical layout with latest product and first product is banner
   */
  HomePage: {
    Horizon: true,
    PageSize: 12,
  },
  HorizonLayout: [
    {
      categoryId: "Z2lkOi8vc2hvcGlmeS9Db2xsZWN0aW9uLzg3NzY2NDMzODQz",
      paging: true,
      layout: Constants.Layout.miniBanner,
    },
    {
      name: "Feature Products",
      categoryId: "Z2lkOi8vc2hvcGlmeS9Db2xsZWN0aW9uLzg5MTUzMjczOTA3",
      layout: Constants.Layout.threeColumn,
    },
    {
      name: "Sarees",
      categoryId: "Z2lkOi8vc2hvcGlmeS9Db2xsZWN0aW9uLzk5ODQxNzAzOTg3",
      layout: Constants.Layout.twoColumn,
    },
    {
      name: "Dresses",
      categoryId: "Z2lkOi8vc2hvcGlmeS9Db2xsZWN0aW9uLzkyNDc3NzE4NTc5",
      layout: Constants.Layout.twoColumnHigh,
    },
    {
      name: "Dupattas",
      categoryId: "Z2lkOi8vc2hvcGlmeS9Db2xsZWN0aW9uLzkzODE5NzMyMDE5",
      layout: Constants.Layout.card,
    },
    {
      name: "News",
      type: "article",
      layoutType: "post", // "post" or "product" is default
      layout: Constants.Layout.threeColumn,
    },
  ],

  CategoryLayout: {
    ListMode: "ListMode",
    GridMode: "GridMode",
    CardMode: "CardMode",
  },

  /**
   * Now we only support Webview payment, so disable this feature
   * In the furture we will try support this feature
   */
  Payments: [
    // {
    //   name: "Cash on Delivery",
    //   imageUrl: require("@images/payment_logo/cash_on_delivery.png"),
    //   enabled: true,
    // },
    // {
    //   type: "card",
    //   name: "Credit Card",
    //   imageUrl: require("@images/payment_logo/credit_card.png"),
    //   enabled: true,
    // },
  ],

  /**
     Step 4: Advance config:
     - showShipping: option to show the list of shipping method
     - showStatusBar: option to show the status bar, it always show iPhoneX
     - LogoImage: The header logo
     - CustomPages: Update the custom page which can be shown from the left side bar (Components/Drawer/index.js)
     - intro: The on boarding intro slider for your app
     - menu: config for left menu side items (isMultiChild: This is new feature from 3.4.5 that show the sub products categories)
     * */
  shipping: {
    visible: true,
    time: {
      free_shipping: "4 - 7 Days",
      flat_rate: "1 - 4 Days",
      local_pickup: "1 - 4 Days",
    },
  },
  showStatusBar: true,
  LogoImage: require("@images/weave_logo.png"),
  CustomPages: { contact_id: 10941 },

  /**
   * Config Menu Side Drawer
   * @param goToScreen 3 Params (routeName, params, isReset = false)
   * BUG: Language can not change when set default value in Config.js ==> pass string to change Languages
   */
  menu: {
    // has child categories
    isMultiChild: true,
    // Unlogged
    listMenuUnlogged: [
      {
        text: "Login",
        routeName: "Login",
        params: {
          isLogout: false,
        },
        icon: Icons.MaterialCommunityIcons.SignIn,
      },
    ],
    // user logged in
    listMenuLogged: [
      {
        text: "Logout",
        routeName: "Login",
        params: {
          isLogout: true,
        },
        icon: Icons.MaterialCommunityIcons.SignOut,
      },
    ],
    // Default List
    listMenu: [
      {
        text: "Shop",
        routeName: "Default",
        icon: Icons.MaterialCommunityIcons.Home,
      },
      {
        text: "About",
        routeName: "CustomPage",
        params: {
          url: "http://inspireui.com",
        },
        icon: Icons.MaterialCommunityIcons.Email,
      },
    ],
  },
};


Quick reply would be appreciated.

**Comment by minhcasi** [comment]
@WorkflowAutomation - could you share the storeAccessToken to support@inspireui.com - as we could not reproduce the issue on our demo site

**Comment by WorkflowAutomation** [comment]
Hello, waiting for your play.

Please solve our issue ASAP. A quick reply would be greatly appreciated.

**Comment by concuacon** [comment]
Hello, @WorkflowAutomation I checked with your config, it works, I can register a new account and login(I have attached the screenshots). You can try again.
<img width="1404" alt="Screen Shot 2019-11-05 at 4 30 03 PM" src="https://user-images.githubusercontent.com/11958061/68195821-2afa7d00-ffea-11e9-9506-4dd57b2f7d2b.png">
