### ISSUE TITLE
[fluxstore] - Registration and sms login

### ISSUE THREAD

**Issue by immortal-kid** [inspireui/support#1256]
my purchase http://prntscr.com/pjvdg2

1. when i after completing registration, it will take to login screen when i enter username and password and login, i get welcome message in snackbar but it will stay in login page only. when i close the app and open again, the it will show settings and all. please fix this

2. when user login with sms, in wp user panel it is showing mstore.io http://prntscr.com/plejgb at the end, can i make it take my domain name instead?

**Comment by minhcasi** [comment]
@immortal-kid - noted with investigating - thank you!

**Comment by kazhuyo** [comment]
@immortal-kid for your question number 2.
you should change that "@mstore.io" in your woocommerce site in directory :
`wp-content/plugins/mstore-api/controllers/MstoreUser.php`

in line 422 change this line :
`                $user_email = $result["phone"]["number"] . "@mstore.io";
`
to 
`                $user_email = $result["phone"]["number"] . "@yourdomain.com";
`

and line 485 
`            $user_email = $json_api->query->phone."@mstore.io";
`
to
`            $user_email = $json_api->query->phone."@yourdomain.com";
`

**Comment by immortal-kid** [comment]
if i make changes in plugin php files, i lose it when i update the plugin, instead u could gv an update making setting it to default domain name for everyone.

**Comment by kazhuyo** [comment]
@immortal-kid yep, it makes sense, it's a requested feature @minhcasi 

- Add ability to configure default domain in fluxstore.

**Comment by minhcasi** [comment]
updated ticket as 'feature request' to upgrade the mstore-api - thank you!

**Comment by immortal-kid** [comment]
any updates on #1244 no response received

**Comment by minhtruong315** [comment]
@immortal-kid Please update mstore-api version to 1.4.6 to change domain name for login sms
