### ISSUE TITLE
MStore Multi Vendor - Vendor list error, Product Images not showing, Categories error

### ISSUE THREAD

**Issue by greatlakesmade** [inspireui/support#1257]
[Config files for support.zip](https://github.com/inspireui/support/files/3746719/Config.files.for.support.zip)
1. a. I am unable to get the vendors to show up. I am using WCFM Marketplace plugin with Rehub theme. How do I get the list of vendors to appear?
    b. Product images do not show up through REST API. Title, Price, Description appears, but no images. UPDATE: Title, price, description are not appearing now. See screenshots below.
    c. Error appears when clicking on any category.

---------

1. My issue

2. Screenshots

3. My screenshot of the purchase product or my comment:

3. Config files (optional)

**Comment by greatlakesmade** [comment]
![My puchase](https://user-images.githubusercontent.com/49296200/67146061-0fa31a00-f255-11e9-9005-c53ea5e57e78.JPG)
Here is my purchase verification

**Comment by greatlakesmade** [comment]
![app_view](https://user-images.githubusercontent.com/49296200/67146288-9bb64100-f257-11e9-92a1-4150f1a1ab06.JPG)
![app_view_2](https://user-images.githubusercontent.com/49296200/67146289-9bb64100-f257-11e9-8e96-f5f38760f144.JPG)
![app_view_after_clicking_on_search_bar_to_find_products](https://user-images.githubusercontent.com/49296200/67146290-9bb64100-f257-11e9-9896-aa91a138bd3b.JPG)
![app_view_after_clicking_vendor](https://user-images.githubusercontent.com/49296200/67146291-9bb64100-f257-11e9-8073-0d6d215eea5c.JPG)
![app_view_cant_get_data_from_server](https://user-images.githubusercontent.com/49296200/67146292-9bb64100-f257-11e9-94d5-90d76bc9c72c.JPG)
Here are all of the screenshots

**Comment by greatlakesmade** [comment]
![app_view_vendor_list_does_not_appear](https://user-images.githubusercontent.com/49296200/67146322-f18ae900-f257-11e9-84f0-f40aec79945f.JPG)

**Comment by greatlakesmade** [comment]
![htaccess_file](https://user-images.githubusercontent.com/49296200/67146439-1764bd80-f259-11e9-863e-633e94728bde.JPG)
![JWT_Key](https://user-images.githubusercontent.com/49296200/67146440-1764bd80-f259-11e9-9396-74fd833556fc.JPG)
Wp-config and htaccess file setup

**Comment by greatlakesmade** [comment]
News/Blog section is working properly:
![app_view_news_is_working](https://user-images.githubusercontent.com/49296200/67146732-edf96100-f25b-11e9-8f1a-deabee1c49ba.JPG)

**Comment by greatlakesmade** [comment]
I just installed "WooCommerce Multivendor Marketplace – REST API" plugin:

https://wordpress.org/plugins/wcfm-marketplace-rest-api/

WCFM Rest API documentation:
https://wclovers.github.io/wcfm-rest-api/#introduction

The result is still the same even with this plugin installed, but maybe this will help resolve the issue?

**Comment by greatlakesmade** [comment]
It's been a week. Following up for any sort of support.

**Comment by minhcasi** [comment]
@greatlakesmade - sorry for lated reponse please try with the latest version v1.3.2 that fixed these issue - let us know your checking, thank you!

**Comment by toufic118284** [comment]
I am having the same problem though I have version 1.3.2.
