### ISSUE TITLE
[MStore Pro] - show all attributes in variation block

### ISSUE THREAD

**Issue by MohsenHaydari** [inspireui/support#1258]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue

2. Screenshots

3. My screenshot of the purchase product or my comment:

3. Config files (optional)

hi 

in product show all attributes and i need to show just variables,

**Comment by minhcasi** [comment]
@MohsenHaydari - could you help to take the screenshot of purchased code from - https://codecanyon.net/downloads

Also, could you explain more about the issue as it not clear enough? Any screenshot issues should be help
