### ISSUE TITLE
[Evastore] - side menu categories

### ISSUE THREAD

**Issue by WorkflowAutomation** [inspireui/support#1261]
1. My issue
Categories in the side menu showing many Shopify collections (Approx. 250). We would like to remove all. We would like to put some selected collections there. For this where we have to modify. Please help with this issue.

2. Screenshots
![cat](https://user-images.githubusercontent.com/46641395/67183986-4d907180-f400-11e9-973d-d5761e83524a.jpeg)

**Comment by minhcasi** [comment]
@WorkflowAutomation - it could customize from containers/DrawerContainer/DrawerMultiChild.js - thanks
