### ISSUE TITLE
[fluxstore] - Product is unavailable error on Single product page

### ISSUE THREAD

**Issue by Dhavalkatrodiya** [inspireui/support#1262]
1. My issue

hi, i am getting this. https://snipboard.io/i3tF51.jpg it says product is unavailable.
this is digital product .https://snipboard.io/mIKTV2.jpg , product is published & working fine on website

3. My screenshot of the purchase product or my comment:
https://snipboard.io/6EgT7k.jpg

3. Config files (optional)
    config. json
    https://codeshare.io/angB8V

    config.dart
    https://codeshare.io/amgBdb

**Comment by minhcasi** [comment]
@Dhavalkatrodiya - thank you for the detail, we will investigate and let you know

**Comment by Dhavalkatrodiya** [comment]
any update?

**Comment by minhtruong315** [comment]
@Dhavalkatrodiya send me config.json, config.dart file and admin account via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/1262

**Comment by minhtruong315** [comment]
no response
