### ISSUE TITLE
[Mstore - Pro] - Archive failed 

### ISSUE THREAD

**Issue by binhetc** [inspireui/support#1264]
Hello,
I added some new image icons for category_icons, I can build it but when I tried to Archive it, I got that issue:
![image](https://user-images.githubusercontent.com/13253563/67257805-d7e7dc80-f4b7-11e9-8582-0a795595f62c.png)
 
Could you please help?

**Comment by binhetc** [comment]
Hello,
I can archive now, but woocommerce products cannot be loaded to app, I already installed all required plugins, could you help me to fix it?
Thank you!

**Comment by concuacon** [comment]
> Hello,
> I can archive now, but woocommerce products cannot be loaded to app, I already installed all required plugins, could you help me to fix it?
> Thank you!

@binhetc can you attach a screenshot for me?

**Comment by binhetc** [comment]
I fixed by upgrade woocommerce to v3 version and change my site to https protocol, thanks for your help!

**Comment by binhetc** [comment]
Could you let me know, how to list all main categories on the left menu and CategoriesLayout?
Thank you

**Comment by binhetc** [comment]
also could you remove UIWebView, I got this email from Apple:
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

**Comment by binhetc** [comment]
Thank you concuacon, I got some issue below, could you please give me some advice?
1. I have 8 categories on the Home page, but only one display category name under icon, 7 are blank.
2. On the left menu of the home page, it can load only three of 8 main categories with some sub categories, it cannot load all sub categories too.
Could you please help?
Thank you!

**Comment by binhetc** [comment]
I got 4.3 Design: Spam Rejected from Apple, could you please give me some advices?

**Comment by concuacon** [comment]
Hello @binhetc I think your problem the same this [link](https://www.buildbox.com/forum/index.php?threads/rejection-from-apple-review-design-spam.11933/)
