### ISSUE TITLE
[fluxstore] - Remove Description, Reviews, Additional info, Ratings & Quantity field from Single product page

### ISSUE THREAD

**Issue by Dhavalkatrodiya** [inspireui/support#1265]
1. My issue
hi, iwant to Remove Description, Reviews, Additional info, Ratings & Quantity field ui from Single product page, how to do that?

2. Screenshots
https://snipboard.io/zyILPY.jpg

3. My screenshot of the purchase product or my comment:
https://snipboard.io/6EgT7k.jpg

3. Config files (optional)
  config. json
  https://codeshare.io/angB8V

  config.dart
  https://codeshare.io/amgBdb

**Comment by minhcasi** [comment]
@Dhavalkatrodiya - try to use the Inspector from Android Studio and remove the widget that you would not display on the app, more ref: https://docs.inspireui.com/fluxstore/useful-tip/#how-to-change-the-ui-quickly
