### ISSUE TITLE
[ ListApp - Listing Directory mobile app by React Native (Expo version) ] - App crashing when try to open any Listing & Unable to Register New User & Login existing Website Register User.

### ISSUE THREAD

**Issue by shaaanishaan** [inspireui/support#1267]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:       **1. Application crashing (restart) when try to open any Listing
                         2. Unable to Register New User & Login existing Website Register User.
                         3. Need to APK version of Android & IOS.**

                           
2. Screenshots:              1. Physical Device Video Recording ( Crashing Issue)
                                     2.1: Sign Up:    Signup & Login Video.zip
[Signup & Login Video.zip](https://github.com/inspireui/support/files/3754571/Signup.Login.Video.zip)

                                     2.2: Login:  No route was found matching the URL and request method. 
![2 2 Login Issue](https://user-images.githubusercontent.com/54396807/67268150-34092b80-f4cd-11e9-9577-51be0237fa21.jpg)

                                     3. My screenshot of the purchase product or my comment: 
                                     1. Item Purchase Code: 8d53b248-5590-****-****-f39715c7b53c 
                                     2. Comment on Product screenshot:  
![Purchase proof](https://user-images.githubusercontent.com/54396807/67267317-77fb3100-f4cb-11e9-86ae-b4a65ecdad77.jpg)

3. Config files (optional)     1. Config win.zip file: 
                                         includes 1. AppConfig.json  2. AppConfig_MyListing.json   3. MyListing.js
[Config files.zip](https://github.com/inspireui/support/files/3754398/Config.files.zip)

**Comment by minhcasi** [comment]
@shaaanishaan  - could you double-check the JWT config from this guide - https://docs.inspireui.com/listapp/getting-started/

**Comment by shaaanishaan** [comment]
Dear @minhcasi Dear I have check all the guide as per your linked documentation & here is proof with screen shoot
1. Configuration successful screenshot
![Screenshot_2019-10-24 https ayshway com](https://user-images.githubusercontent.com/54396807/67490197-48475700-f68c-11e9-9b76-9a059efb96fa.png)


2. Enable the Rest Api controller screenshot
![Screenshot_2019-10-24 JSON API Settings ‹ Ayshway — WordPress](https://user-images.githubusercontent.com/54396807/67490314-788ef580-f68c-11e9-9af8-81e82c2747a4.png)


3. Enable Job Listing API Screenshot
![Screenshot_2019-10-24 WP REST API Controller ‹ Ayshway — WordPress](https://user-images.githubusercontent.com/54396807/67490403-a07e5900-f68c-11e9-8219-98b0cd07bb4f.png)




4. Enable the Rest Api controller Screenshot

![Screenshot_2019-10-24 JSON API Settings ‹ Ayshway — WordPress](https://user-images.githubusercontent.com/54396807/67490769-32866180-f68d-11e9-82c5-bbfec1bd4a6c.png)





5.  App/Common/AppConfig.json* Screenshot

![last](https://user-images.githubusercontent.com/54396807/67490600-e9cea880-f68c-11e9-942a-0d7fccb54896.jpg)




Dear please find all above and if any thing remain then please guide. Waiting for solution!!!

Your Truly
Shaaani

**Comment by shaaanishaan** [comment]
Dear, really disappointed by support side, I have solve the above error after regular 20 hour to consult from internet. 
Now I am facing following issue

[stderr] FAILURE: Build failed with an exception.
[stderr] * What went wrong:
[stderr] Execution failed for task ':app:processReleaseGoogleServices'.
[stderr] > No matching client found for package name 'com.ayshway.ayshwayapp'


![Screenshot_2019-10-27 Expo](https://user-images.githubusercontent.com/54396807/67629818-efe7a380-f89d-11e9-9233-51f0bdcc60c8.png)


Please it's urgent could you help to solve this matter.

Your's Truly
Shaaani

**Comment by minhcasi** [comment]
@shaaanishaan - you can login to the Firebase and redownload the google service file to fix the issue (the bundle id on firebase should match with com.ayshway.ayshwayapp) - thanks

**Comment by shaaanishaan** [comment]
@minhcasi Really thanks, I am trying now but there some issue to connect the app. Be there. I will come back.

**Comment by shaaanishaan** [comment]
Dear, @minhcasi @thangvo9x @luyx2412 
 Please check the issue
 1. After adding Firebase SDK Setup: npm install—save firebae Here is final result: + firebase@7.2.2 added 2269 packages from 686 contributors, removed 1162 packages, updated 39 packages, moved 50 packages and audited 45606 packages in 431.263s found 14 vulnerabilities (12 low, 2 high) run `npm audit fix` to fix them, or `npm audit` for details Even there is Vulnerabilities. 2 is Most Critical.

2. As I run project on Expo for Android Build after Adding Firebase SDK Setup: yarn install && yarn run warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.

Dear, Please provide complete documentation for solving matter. As I am facing this issue to build from last 2 month. You can check my last comments.

Regards Shaaani
![Vulnerability + package lock](https://user-images.githubusercontent.com/54396807/67747055-b784c880-fa49-11e9-912b-148d61144003.jpg)

**Comment by shaaanishaan** [comment]
Dear, @minhcasi @thangvo9x @luyx2412 
 I am these issue to need guide to solve,
1. Unable to Register New User & Login existing Website Register User. SAME PROBLEM AS MENTIONED ABOVE


2. On Application Home page block linked under "CATEGORY ID" here only show the latest one. Where as in Category page all Listing under that category shown.
Note: I have attached the screenshot.

- Homepage block with Tour & Travel Category ID: https://ibb.co/Bc8pq9n
![Screenshot_20191030_154346](https://user-images.githubusercontent.com/54396807/67852047-8382d380-fb2d-11e9-9f05-d38d12823d95.jpg)






- Homepage block with Tour & Travel Category ID (Showing only 1 recent listing): https://ibb.co/dPc8TFB
![Screenshot_20191030_154604](https://user-images.githubusercontent.com/54396807/67852115-a4e3bf80-fb2d-11e9-9095-efb8f4edd4d1.jpg)



- Tour & Travel Category under Category Tab: https://ibb.co/ZHBGqhL
![Screenshot_20191030_154729](https://user-images.githubusercontent.com/54396807/67852135-b036eb00-fb2d-11e9-8349-7908f9ca8e52.jpg)



Please guide me to solve this matter...

Regards 
Shaaani

**Comment by minhcasi** [comment]
@shaaanishaan  - could you zip the current customize source and send to our support email for futher checking - support@inspireui.com - thank you!

**Comment by minhcasi** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!

**Comment by shaaanishaan** [comment]
Dear @minhcasi , Open the Ticket, I am in process so within one hour. I will send the package in zip format.

**Comment by shaaanishaan** [comment]
Dear @minhcasi did you get package on support email?

**Comment by shaaanishaan** [comment]
Dear, I am waiting for your response?

**Comment by shaaanishaan** [comment]
Dear @minhcasi , Now I am using the New Updated Package.. Still facing little Problems ..... as Under

**Comment by shaaanishaan** [comment]
@minhcasi @thangvo9x  Dear I am waiting for your response....

**Comment by minhcasi** [comment]
@concuacon - pls help to check this ticket as a high priority - thank you!

**Comment by shaaanishaan** [comment]
Dear @minhcasi @concuacon I am still waiting for solution and My ticket in on Priority...
If you can't solve the matter. Just refund my money. I am still in problem after buying Expo project and not support from your side. From last 4 month I am waiting for support?????????

Regards

**Comment by minhcasi** [comment]
@concuacon - remind

**Comment by shaaanishaan** [comment]
Dear, I am really disappointed from your side. If you can't solve the matter, Could be please replace my Current License from " ListApp - Listing Directory mobile app by React Native (Expo version) " to New " FluxStore Listing - Directory WooCommerce app by Flutter "????????

Hope you can do this!!

**Comment by minhcasi** [comment]
Yes, it's ok - sorry for the issue - please send the refund request to https://help.market.envato.com/hc/en-us/articles/202821460-Can-I-Get-A-Refund- - thank you!

**Comment by shaaanishaan** [comment]
Dear, As I submit the request for refund and I want to use this with extra amount for FluxStore Listing - Directory WooCommerce app by Flutter.
Hope you understand my situation for refund....

**Comment by minhcasi** [comment]
@shaaanishaan - we have updated your request, thanks
