### ISSUE TITLE
Animated Splashscreen Issue

### ISSUE THREAD

**Issue by ajeets1978** [inspireui/support#1270]
Changed the Splashcreen.flr but still I am seein the fluxstore screen only.

**Comment by minhcasi** [comment]
Duplicate of #1271

Kindly notes:
- Create one ticket for your all issue with detail screenshot
- Share your config file (common/config.json and config.js) so we can reproduce issues.
- Also, make sure to check the document first - https://docs.inspireui.com/fluxstore
