### ISSUE TITLE
Category Issues Drawer Menu - Fluxstore

### ISSUE THREAD

**Issue by ajeets1978** [inspireui/support#1271]
Why does it shows the category under category

Attached is the screen shot.
![CategoryMenuIssue](https://user-images.githubusercontent.com/4997895/67281681-b6204100-f51b-11e9-8e13-a91ad2316191.PNG)

**Comment by minhcasi** [comment]
could you share the config files (common/config.json and config.js) so we can reproduce issues

**Comment by minhtruong315** [comment]
no response
