### ISSUE TITLE
[FluxNews] -  Error: Too many positional arguments on trying to build

### ISSUE THREAD

**Issue by natebeast** [inspireui/support#1273]
Hello, I am getting this error when I am trying to build the app in the iOS simulator on Android Code Studio

Launching lib/main.dart on iPhone 11 Pro Max in debug mode...

Compiler message:
lib/screens/settings.dart:189:70: Error: Too many positional arguments: 0 allowed, but 1 found.
Try removing the extra positional arguments.
                                      .requestNotificationPermissions(
                                                                     ^
../../../.pub-cache/hosted/pub.dartlang.org/notification_permissions-0.4.3/lib/notification_permissions.dart:10:35: Context: Found this candidate, but the arguments don't match.
  static Future<PermissionStatus> requestNotificationPermissions(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Compiler failed on /Downloads/FluxNews.1.1.0/source/lib/main.dart
Error launching application on iPhone 11 Pro Max.

**Comment by minhcasi** [comment]
@natebeast - could you help to share your purchase screenshot from - https://codecanyon.net/downloads - thank you!
