### ISSUE TITLE
fluxerrors

### ISSUE THREAD

**Issue by Arman20022010** [inspireui/support#1274]
Hi
Please can you help me I see these error when I am clicking to show product

> NoSuchMethodError: The getter 'length' was called on null
Receiver: null
Tried calling: length

**Comment by Arman20022010** [comment]
And also Pay on delivery is not working how to fix ? )

**Comment by minhcasi** [comment]
Hi @Arman20022010  - could you share the screenshot of your purchased code from https://codecanyon.net/downloads - thanks

**Comment by Arman20022010** [comment]
<img width="1680" alt="Screen Shot 2019-10-25 at 8 52 43 PM" src="https://user-images.githubusercontent.com/36129818/67589502-9e3dfc80-f769-11e9-8fec-8b05af551279.png">
here it is

**Comment by Arman20022010** [comment]
now can you help me ?)

**Comment by Arman20022010** [comment]
And please can you tell me how to setup stripe and from where to get RedirectUrl ?

**Comment by minhcasi** [comment]
@Arman20022010 - could you help to download the latest version 1.5.6 to fix the issue - thanks

**Comment by Arman20022010** [comment]
please can you tell me how to activate stripe ?
Thanks :)

**Comment by Arman20022010** [comment]
from where can I get redirect url ?
<img width="449" alt="Screen Shot 2019-10-31 at 8 02 50 PM" src="https://user-images.githubusercontent.com/36129818/67964293-76dba980-fc19-11e9-9445-679fbd091f91.png">

**Comment by Arman20022010** [comment]
after adding these things it is only loading and not opening page to pay. How can I fix it ?

**Comment by minhcasi** [comment]
@Arman20022010 - could you send us the config files (common/config.dart and config.json) for investigating?

**Comment by minhtruong315** [comment]
@Arman20022010 we don't support native stripe now. You can use payment webview to work with stripe
About TapConfig, you can ignore RedirectUrl, you dont need to change it

**Comment by Arman20022010** [comment]
Hi Please can you tell me how to use webview stripe ? :)

**Comment by Arman20022010** [comment]
[common.zip](https://github.com/inspireui/support/files/3802644/common.zip)

**Comment by Arman20022010** [comment]
I see Stripe in app but when I am clicking pay with Stripe it only shows loading icon

**Comment by minhtruong315** [comment]
is Stripe working on my website?

**Comment by Arman20022010** [comment]
yes :)

**Comment by Arman20022010** [comment]
<img width="1180" alt="Screen Shot 2019-11-04 at 11 38 07 PM" src="https://user-images.githubusercontent.com/36129818/68152014-4028ca80-ff5c-11e9-9014-0e0323eedd0d.png">
<img width="1210" alt="Screen Shot 2019-11-04 at 11 38 37 PM" src="https://user-images.githubusercontent.com/36129818/68152021-4159f780-ff5c-11e9-9427-cc650149b5cc.png">

**Comment by Arman20022010** [comment]
?

**Comment by Arman20022010** [comment]
And I don't see start screen in new device where is written Welcome to.....

**Comment by minhtruong315** [comment]
@Arman20022010 I'll check your issue now

**Comment by minhtruong315** [comment]
@Arman20022010 can you send me admin account via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/1274

**Comment by Arman20022010** [comment]
done I sent you details
but please be attentive because website is live and working everyday 
Thanks :)

**Comment by minhtruong315** [comment]
![Simulator Screen Shot - iPhone X - 2019-11-11 at 15 03 30](https://user-images.githubusercontent.com/10402500/68570977-74d4de80-0494-11ea-8b2f-05422437df45.png)
I see stripe working well. can you show me issues?

**Comment by Arman20022010** [comment]
Which fluxstore you are using ?

**Comment by Arman20022010** [comment]
I am using Fluxstore WooCommerce - Flutter E-commerce Full App

**Comment by Arman20022010** [comment]
I see only fluxstore loading

**Comment by Arman20022010** [comment]
and nothing is happening after that

**Comment by Arman20022010** [comment]
can you help me please what to do to fix problem ? :)

**Comment by minhcasi** [comment]
Pls update 1.5.8 on tomorrow's release to fix the Payment performance and Stripe issue - thank you!
