### ISSUE TITLE
[Fluxstore] - payment method with insurance

### ISSUE THREAD

**Issue by rodrigoalves1901** [inspireui/support#1275]
I would like to know how do I add the payment method with secure payment in the app? On the site works more in the application does not accept.

https://pagseguro.uol.com.br/#rmcl

![image](https://user-images.githubusercontent.com/43248152/67333599-d38ae600-f4ee-11e9-9465-9013a379cda0.png)

**Comment by minhcasi** [comment]
Hi, it will work same as on your website, pls check this guide for detail config - https://docs.inspireui.com/fluxstore/multi-payment/
