### ISSUE TITLE
Fluxstore errors before release

### ISSUE THREAD

**Issue by n1gmatech** [inspireui/support#1276]
Hello dears, 
I've some pre release errors, kindly need your help.
Purchase - <img width="810" alt="Снимок экрана 2019-10-23 в 12 59 38" src="https://user-images.githubusercontent.com/54979352/67382078-9463a000-f595-11e9-87b4-fc64c44eda80.png">

1. I removed some fields from "screens/checkout/shipping_address.dart", cause we don't use them, as Last name, Country, State and Zip. There are disappear in Application, but when making order "woo_commerce.dart" returns error. In WP side this fields are not required. How can I remove this fields to make order success?

2. I add my country Payment, did all steps several times (created and copied the file), but still white screen returns. By the way, in documents there are some misunderstanding, like - link to install MStore API, but screens and "payment gateway issues" from another plugin (MStore Checkout). Please help to add Payment. 

3. When user register in the APP in the Wordpress there is no Name and Last name, APP doesn't send this information to WP. 

4. If you set to "IsRequiredLogin": true in "config.dart" and then from cart registering in the APP, after submitting registration Login page appear again. Should load Mycart screen.

5. We don't use symbol before number, is set to -  "symbolBeforeTheNumber": false, but in Mycart screen symbol appear before total cost. How to change their places? 

Waiting to hear from you!

**Comment by minhcasi** [comment]
@n1gmatech  - could you attache your detail config files (from common folder).

**Comment by n1gmatech** [comment]
Hello,
Files are attached.

**Comment by minhtruong315** [comment]
@n1gmatech can you send me config.json, config.dart file and admin account via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/1276

**Comment by minhtruong315** [comment]
@n1gmatech 
1. Woo commerce api require those fields when checkout, You can't remove them.
2. Please check again
3. Replace createUser function in services/woo_commerce.dart like this
```
 @override
  Future<User> createUser({firstName, lastName, username, password}) async {
    try {
      String niceName = firstName + " " + lastName;
      var nonce = await getNonce();
      final http.Response response = await http.post(
          "$url/api/mstore_user/register/?insecure=cool&$isSecure",
          body: convert.jsonEncode({
            "nonce": nonce,
            "user_email": username,
            "user_login": username,
            "username": username,
            "first_name": firstName,
            "last_name": lastName,
            "user_pass": password,
            "email": username,
            "user_nicename": niceName,
            "display_name": niceName,
          }));
      if (response.statusCode == 200) {
        var cookie = convert.jsonDecode(response.body)['cookie'];
        return await this.getUserInfo(cookie);
      } else {
        var message = convert.jsonDecode(response.body)["error"];
        throw Exception(message != null ? message : "Can not create the user.");
      }
    } catch (err) {
      throw err;
    }
  }
```
5. Change this in line 495 screens/cart.dart
```
 Text(
                              Tools.getCurrecyFormatted(
                                  widget.model.getTotal()),
                              style: largeAmountStyle,
                            ),
```

**Comment by n1gmatech** [comment]
Hello, 
1) Ok, will leave it. 
2) Still have that problem, white screen loading. Not going to the payment gateway page.  
3) Done. 
4) Will check it later.
5) Done. 

Thanks a lot!

**Comment by minhtruong315** [comment]
no response
