### ISSUE TITLE
[fluxstore] when run this app i have this problem and i test drive is successful 

### ISSUE THREAD

**Issue by elgoharyibrahim** [inspireui/support#1277]
Oops; flutter has exited unexpectedly.
Crash report written to C:\Users\e.ibrahim\Downloads\codecanyon-md7fkeml-fluxstore-the-universal-woocommerce-magento-opencart-mobile-app-by-flutter-framework\FluxStore 1.5.5\source\flutter_03.log; 
Execution failed for task ':app:compileFlutterBuildDebugX86'.
> Process 'command 'C:\Users\e.ibrahim\flutter\bin\flutter.bat'' finished with non-zero exit value 1

**Comment by minhcasi** [comment]
@elgoharyibrahim - could you show us your purchased screenshot from - https://codecanyon.net/downloads - thanks

**Comment by elgoharyibrahim** [comment]
![pay](https://user-images.githubusercontent.com/37834021/67635288-cfcfd880-f8cd-11e9-9f6b-5d3692970a5e.PNG)
this is my purchased screenshot

**Comment by elgoharyibrahim** [comment]
@minhcasi can you help me

**Comment by minhcasi** [comment]
@elgoharyibrahim - could you help to check with latest 1.5.6, we have fixed some build issue on this release - thank you!

**Comment by minhcasi** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days - if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
