### ISSUE TITLE
[my-product] - FluxStore Universal

### ISSUE THREAD

**Issue by govindh163** [inspireui/support#1278]
Can I Add the "CC Avenue" Payment Gateway?
It Was Added in the Website,
And it is Displaying In Payments  Methods Perfectly In App,Then what to do to Integrate it,
If Yes Please Guide Some Starter Tips to Make it Happen!!

**Comment by minhcasi** [comment]
Hi @govindh163 - pls help to check this guide - https://docs.inspireui.com/fluxstore/multi-payment/
