### ISSUE TITLE
[fluxstore] - language, login and signup error

### ISSUE THREAD

**Issue by immortal-kid** [inspireui/support#1279]
my purchase http://prntscr.com/pjvdg2

1. get this error https://prntscr.com/pnhw51 both in login and registration page whenever i try to login or register. sms login is working fine, it is also working fine for 1.5 version but showing that error in 1.5.5c. i have sent a mail along with config details and login details with subject [immortal kid bugs] 

2. whenever i switch the language, close the app and open again, it will change back to English only, this issue is seen in ur demo app also.

**Comment by immortal-kid** [comment]
if i add ur config details(the default one) login and registration working properly, but not working in my site config details and also other site config details.

**Comment by minhtruong315** [comment]
Send me config.dart file and admin account via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/1279

**Comment by immortal-kid** [comment]
sent u a mail, kindly look into it.

and when do we get 1.5.6 update?

**Comment by immortal-kid** [comment]
then i get this https://prntscr.com/pnhw51 error in app 

console in android studio shows this http://prntscr.com/pp84ns

**Comment by immortal-kid** [comment]
it is working fine in 1.5.5 and it is showing error in 1.5.5c, still showing error in 1.5.6 
so its problem with the code itself, please look into it

**Comment by immortal-kid** [comment]
i apologize, i had selected Default customer location to giolocate and it was causing randaom string at the end of url which was causing problem for login and register, i changed it to No location by default, now its working fine.
