### ISSUE TITLE
[Mstore-Pro] can't build

### ISSUE THREAD

**Issue by ItisAhsan** [inspireui/support#1281]
I'm getting this error
i was getting different error tried fixing through this
https://github.com/phonegap/phonegap-plugin-push/issues/2193
apparently pods are not installing correctly and the reason is this
![Screenshot 2019-10-25 04 53 04](https://user-images.githubusercontent.com/12572962/67533440-5f656380-f6e3-11e9-8bae-e815834b920b.png)

![Screenshot 2019-10-25 04 48 56](https://user-images.githubusercontent.com/12572962/67533366-1c0af500-f6e3-11e9-94bd-979405115f14.png)

**Comment by ItisAhsan** [comment]
proof of purchase 
https://www.dropbox.com/s/yakll52tu9umon5/Screenshot%202019-10-25%2004.54.24.png?dl=0

**Comment by minhcasi** [comment]
@ItisAhsan - could you try with this script from the ios folder

pod repo update
pod install 

Then open Xcode to run the project again
