### ISSUE TITLE
[my-product] - 

### ISSUE THREAD

**Issue by jorgencnc** [inspireui/support#1282]
Purchased the product.

Fluxstore WooCommerce - Flutter E-commerce Full AppRegular LicensePurchase code: a93641cb-9717-496d-9932-4288b80428ed | Fluxstore WooCommerce - Flutter E-commerce Full App | Regular License | Purchase code: a93641cb-9717-496d-9932-4288b80428ed |  
-- | -- | -- | -- | --
Fluxstore WooCommerce - Flutter E-commerce Full App
Regular License
Purchase code: a93641cb-9717-496d-9932-4288b80428ed

and now that I open it in visual code and sales error please, there is an installation manual because I got a sales error in all the packages

**Comment by minhcasi** [comment]
Hi, please help to check this document - http://docs.inspireui.com/fluxstore and this official guide from Google - https://flutter.dev/docs/get-started/install

**Comment by minhtruong315** [comment]
no response
