### ISSUE TITLE
[FluxNews] - 

### ISSUE THREAD

**Issue by bakpaorabbit** [inspireui/support#1283]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue : Cannot run fluxnews, all flutter is clear an can test drive. use flutter . use flutter 1.9.1+HotFix.4. This error similiar when run FluxStore 1.5.5, and fix in 1.5.5c.

2. Screenshots : https://prnt.sc/pn55hp

3. My screenshot of the purchase product or my comment : https://prnt.sc/po3gph

3. Config files (optional) : original files from fluxnews 1.1.0

**Comment by minhcasi** [comment]
@bakpaorabbit - I've forwarded to the technical team for checking on the window OS, in the meantime could you try with this solution to clean up the flutter cache:
	flutter clean
	flutter upgrade
	flutter pub get

**Comment by bakpaorabbit** [comment]
hi, still not work.
i have a question, i download in envato, i get version 1.1.0, but it write latest update is version 1.1.2.

**Comment by dttrung26** [comment]
Hi @bakpaorabbit ,

could you please share your screenshots after running those lines "flutter doctor
" and "flutter --version", also the source code of yours. 

Happy coding!

**Comment by bakpaorabbit** [comment]
this is "flutter doctor" & "flutter --version" screenshot : https://prnt.sc/pp305m

how to download version 1.1.2 ? the lastest update on envato written 1.1.2, but what i can download is version 1.1.0
1.1.2 screenshot : https://prnt.sc/pp31j7
1.1.0 download screenshot : https://prnt.sc/pp31ul

thank you so much

**Comment by minhcasi** [comment]
@bakpaorabbit - sorry for the late response - we will update new patching on the next 1-2 days - thank you!

**Comment by dttrung26** [comment]
Hi @bakpaorabbit ,
The version of your fluxnews is completely fine, it's just a mistake in displaying the version of the app, so don't worry.
In addition to that, please download this file, extract and replace your settings.dart in yourfolder/source/lib/screens and please tell me if it works. 
Have a nice day!
[settings.zip](https://github.com/inspireui/support/files/3802623/settings.zip)

**Comment by bakpaorabbit** [comment]
Yeahhh,,, it's work.. i can run fluxnews now.. thanks so muchhh @dttrung26 & @minhcasi

**Comment by minhcasi** [comment]
@bakpaorabbit  - let us know if you have any questions

Please help to give use some rating to http://codecayon.net/downloads if the product is helpful, thank you!
