### ISSUE TITLE
[Fluxstore] - Order History on New version 

### ISSUE THREAD

**Issue by underscore15** [inspireui/support#1284]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: Order History Screen 
Error :

════════ (2) Exception caught by widgets library ═══════════════════════════════════════════════════
The getter 'length' was called on null.
Receiver: null
Tried calling: length

2. Screenshots
![Screen Shot 2019-10-25 at 7 17 33 PM](https://user-images.githubusercontent.com/56452467/67587244-23221980-f75c-11e9-9811-c0db8ecbfb5c.png)

3. My screenshot of the purchase product or my comment:
Comment will be placed for Purchase proof (username: underscore14)

**Comment by minhcasi** [comment]
@underscore15  - could you help to provde the config file with the user login account testing to reproduce this issue on your site ?

**Comment by underscore15** [comment]
Sure will send you an email with config file and user login account to test it

**Comment by minhtruong315** [comment]
@underscore15 send me config.dart, config.json file and admin account via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/1284

**Comment by underscore15** [comment]
Email Sent with details

**Comment by minhtruong315** [comment]
@underscore15 I checked your website, it's working well. Please try this config.dart
[config.dart.zip](https://github.com/inspireui/support/files/3786657/config.dart.zip)
![Simulator Screen Shot - iPhone X - 2019-10-30 at 09 29 43](https://user-images.githubusercontent.com/10402500/67824151-2caed700-faf8-11e9-9bb4-ccb7550d4d6c.png)

**Comment by underscore15** [comment]
Did you try registering? And saw user created?

**Comment by minhtruong315** [comment]
Yes. I register and login, then order

**Comment by underscore15** [comment]
Please check wp-admin/users (no user created) because the order made has no username and that is the issues with ticket 1288

**Comment by minhtruong315** [comment]
<img width="1306" alt="Screen Shot 2019-10-31 at 9 36 29 AM" src="https://user-images.githubusercontent.com/10402500/67914187-f178da80-fbc1-11e9-9caf-36501ede2edc.png">
I see my account is showing on wp-admin/users

**Comment by underscore15** [comment]
Thanks 
Got it working correctly. Will check if any other issues

**Comment by underscore15** [comment]
RE-Opening to not create a new case, Images thumbnails not showing up and categories showing no products
