### ISSUE TITLE
[my-product] - ListPro - Listing Directory React Native template

### ISSUE THREAD

**Issue by anwark** [inspireui/support#1285]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue
The application doesn't load Images from the website 
2. Screenshots
![Screenshot_20191026-150051](https://user-images.githubusercontent.com/109449/67618267-b4e86000-f80a-11e9-842a-41b77e356465.png)
![Screenshot_20191026-150109](https://user-images.githubusercontent.com/109449/67618268-b4e86000-f80a-11e9-97c2-761916ed5a60.png)
![Screenshot_20191026-150136](https://user-images.githubusercontent.com/109449/67618269-b580f680-f80a-11e9-8b17-f2f33f699720.png)
![Screenshot_20191026-150146](https://user-images.githubusercontent.com/109449/67618270-b580f680-f80a-11e9-9e41-6df7c1085bae.png)

3. My screenshot of the purchased product or my comment:
![2019-10-08_1243](https://user-images.githubusercontent.com/109449/67618287-f8db6500-f80a-11e9-8142-761a2823933a.png)

3. Config files (optional)
[AppConfig.zip](https://github.com/inspireui/support/files/3774729/AppConfig.zip)

Application on expo - there is no image in App - https://expo.io/@jhalawar/listpro

**Comment by minhcasi** [comment]
Related ticket #1182

**Comment by minhcasi** [comment]
refunded
