### ISSUE TITLE
[Mstore Pro] RTL changing back after restarting application

### ISSUE THREAD

**Issue by mhdag1** [inspireui/support#1286]
Hello,

I have successfully compiled the application. I have an issue related to RTL.

I have set the application to default to Arabic/RTL on the first run, and that is working correctly. When I switch to the English language, the layout is switching to LTR.

However, when I close the application and launch it again, it is keeping the language in English, but switching the layout to RTL again (so the language is maintained, but the layout is incorrect).

How can I fix that?

My purchase code is 3f0aa14a-c0eb-4aca-8394-7a462e144b25

Regards, Mohammad

**Comment by minhcasi** [comment]
Hi, we will investigate this issue and let you know - thank you for reporting

@concuacon - pls help to check

**Comment by concuacon** [comment]
Hello @mhdag1, you try to follow these steps: 
- Delete app on a device.
- Run: 
  + ios: rm -rf node_modules/ && yarn cache clean && yarn && cd ios/ && rm -rf Podfile.lock && rm -rf Pods/ && pod install && cd ../ && react-native run-ios
  + android: rm -rf node_modules/ && yarn cache clean && yarn && cd android/ && ./gradlew clean && cd ../ && react-native run-android

**Comment by concuacon** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
