### ISSUE TITLE
[Fluxstore] - Shipping Method Error

### ISSUE THREAD

**Issue by rodrigoalves1901** [inspireui/support#1287]
![image](https://user-images.githubusercontent.com/43248152/67619749-6d8fae80-f7cd-11e9-85d3-a093b9322c17.png)

Good morning, I have a problem in the shipping calculation. It does not always calculate comes as rate 0 and on the site it calculates normal. I am using the post office plugin how to solve this problem?

![image](https://user-images.githubusercontent.com/43248152/67619769-c4958380-f7cd-11e9-9994-dfd486737811.png)

![image](https://user-images.githubusercontent.com/43248152/67619787-f1e23180-f7cd-11e9-8e27-b3e3061dabda.png)

**Comment by minhcasi** [comment]
@rodrigoalves1901 - could you help to share the config file from common folder so that we could help for checking, thank you!

**Comment by rodrigoalves1901** [comment]
Good morning, follow below the requested files.

https://transfernow.net/14cwx8b1bbc2

**Comment by rodrigoalves1901** [comment]
Good Morning. Any solution?

**Comment by minhtruong315** [comment]
We will update this issue. Thanks

**Comment by rodrigoalves1901** [comment]
Good afternoon. I received the update files. How do I know what has changed so I don't have to replace my entire project that had already changed?

**Comment by minhtruong315** [comment]
You can search some software to support merge code

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
