### ISSUE TITLE
[Mstore] how to load config.js  from url  with fetch ?

### ISSUE THREAD

**Issue by kiamoz** [inspireui/support#129]
Dear support , I need to load color.js and config.js dynamically from server json . how to do it ?
thank you very much .

**Comment by minhcasi** [comment]
Hi, you can change it to the .json file and fetch from the network, we have marked as the Request feature to investigate the solution to upgrade it on next version release - thank you!

**Comment by kiamoz** [comment]
thank you , but   I need  that  and I  Have  some  question to  do   it by myself ,

for Color.js  it's easer  than  config.js . I  wrote  a function  in confiig.js 

export const response  =  async () => {
  const response = await fetch(state._WEB_SERIVICE_URL+'get_config');
  return response.json();
}

to export  the json , when I want to use it I have to use in .then() block  to access the data ! and I cant use as Color.js (JSON Object) 


another way is I build a color.js in local  files of device then important that , it's better ?

**Comment by luyx2412** [comment]
Hi @kiamoz , Please read the article to understand more about async await and promise. https://medium.com/@bluepnume/learn-about-promises-before-you-start-using-async-await-eb148164a9c8

Thanks

**Comment by kiamoz** [comment]
thank you sir, and just let me know it's possible to load Color.js and export it to use on all pages  with fetch  ?

**Comment by luyx2412** [comment]
Yep of course @kiamoz, but now we do not support load color from api, and we do not have any plan to support this feature. 

Thanks

**Comment by kiamoz** [comment]
Dear @luyx2412  I follow that article and write this function , but when I call getColor() , I expect to get  data without requiring any callback function, but alert says : [Object][Object]


 async function getColor() {
  let respons = await fetch(state._WEB_SERIVICE_URL+'get_config');
  let responseJson = await respons.json();
  //alert((responseJson.main_color));
  return responseJson.main_color;
}

alert(  getColor());


I know that it's not about your product support but if you help me to get the data  I can continue it by myself thank you

**Comment by minhcasi** [comment]
Hi @kiamoz we are checking the solution to move the appConfig.json so the cloud as option so that you can load it dynamic from your website ?

The appConfig.json can be used with the new Cebuilder

How do you thinks about this improvement ?

**Comment by kiamoz** [comment]
hi there , I think so the app should wait for load json first . do you have idea o improve my code above ?

**Comment by luyx2412** [comment]
Hi @kiamoz You can use the redux and theme provider to load from api, after that apply your color with theme provider.

Thanks
