### ISSUE TITLE
[MStore Pro] - Issue in run expo start

### ISSUE THREAD

**Issue by x028** [inspireui/support#1290]
My issue is I get this error after run expo start commend in http://localhost

`
SyntaxError: D:\sidra store\codecanyon-CpL4VNpF-beostore-complete-react-native-template-for-ecommerce\mstore-3.9.6\mstore-expo\src\components\LeftMenu\MenuOverlay.js: Support for the experimental syntax 'decorators-legacy' isn't currently enabled (12:1):

  10 | 
  11 | 
> 12 | @withTheme
     | ^
  13 | class MenuOverlay extends PureComponent {
  14 |   static propTypes = {
  15 |     goToScreen: PropTypes.func,
ERROR
23:27
Building JavaScript bundle: error
`

and you can see the error in the mobile phone [here](url
![photo5310092673815784530](https://user-images.githubusercontent.com/45524078/67641589-016b9280-f914-11e9-8fb9-1577c2f6b449.jpg)
)

**Comment by minhcasi** [comment]
@x028 - could you help to share the proof of purchase product from - by taking the screenshot on https://codecanyon.net/downloads - thanks

**Comment by x028** [comment]
yea of course 

![proof](https://user-images.githubusercontent.com/45524078/67675280-cf981180-f98f-11e9-9d82-d0391951a327.PNG)

**Comment by minhcasi** [comment]
@x028  - could you try to run the project inside the fresh download package (after extraction) as copy the folder to other places could missing from a hidden file that supports to build the product ?

**Comment by concuacon** [comment]
@x028, please follow step run android: 
- delete folder node_modules/
-  reinstall: npm install && cd android/ && ./gradlew clean && cd ../ && react-native run-android

**Comment by minhcasi** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
