### ISSUE TITLE
fluxstore - app store

### ISSUE THREAD

**Issue by Senior-Gamal** [inspireui/support#1291]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------
My issue

Dear Developer,

 We identified one or more issues with a recent delivery for your app,
"My app" 2.0.0 (0.0.2). Please correct the following issues, then upload
again.

 ITMS-90338: NON-PUBLIC API USAGE - The app references non-public
symbols in Frameworks/Flutter.framework/Flutter: _ptrace. If method
names in your source code match the private Apple APIs listed above,
altering your method names will help prevent this app from being flagged
in future submissions. In addition, note that one or more of the above
APIs may be located in a static library that was included with your app.
If so, they must be removed. For further information, visit the
Technical Support Information at
http://developer.apple.com/support/technical/

Though you are not required to fix the following issues, we wanted to
make you aware of them:

 ITMS-90078: MISSING PUSH NOTIFICATION ENTITLEMENT - Your app appears to
register with the Apple Push Notification service, but the app
signature's entitlements do not include the "aps-environment"
entitlement. If your app uses the Apple Push Notification service, make
sure your App ID is enabled for Push Notification in the Provisioning
Portal, and resubmit after signing your app with a Distribution
provisioning profile that includes the "aps-environment" entitlement.
Xcode does not automatically copy the aps-environment entitlement from
provisioning profiles at build time. This behavior is intentional. To
use this entitlement, either enable Push Notifications in the project
editor's Capabilities pane, or manually add the entitlement to your
entitlements file. For more information, see
https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/HandlingRemoteNotifications.html#//apple_ref/doc/uid/TP40008194-CH6-SW1.

 ITMS-90381: TOO MANY SYMBOL FILES - These symbols have no corresponding
slice in any binary [04D9E147-3F20-3C03-8D1F-6290A6726C24.symbols,
0A0307D5-2C6E-3A0C-96E1-5BD115A52DEE.symbols,
10830C14-CE32-39E1-BBBF-2E78A15C13B3.symbols,
1F19BC2D-1D86-313F-ACEA-3B79C899F143.symbols,
40D4751E-C9B6-3ED4-B384-7D0D8DD401D6.symbols,
41DE92BF-D3CB-343E-8C8D-E7308098BB01.symbols,
43B8F637-C5B5-3A95-BE02-78BB2DA46265.symbols,
50B1E386-016E-3B6A-A9FF-C5075D822923.symbols,
54484EA5-7984-3C6C-9F02-AF210F5897EA.symbols,
62491646-8B7A-3453-B65B-B71BBFE3C746.symbols,
66F95050-135E-3502-B87D-2A787AD26375.symbols,
690EF051-7506-3F58-9F7C-FFFCE09542B7.symbols,
7706B160-3D2E-3B24-947F-E2B5C6BFAFF8.symbols,
7DB57AF5-9B4D-36E6-A288-C051B497A618.symbols,
893443B3-7EC8-3B50-8205-E112A4F8A3F4.symbols,
97E83168-3C46-3FCE-BB44-FAC9DFF14D94.symbols,
9F2EFB0E-131C-3F27-9DF0-B3F296C52F2F.symbols,
A0C67FCF-2FAE-3819-9E38-3433CE9625E5.symbols,
A97A6A2C-8BEF-3F14-9956-C7BE74CFE433.symbols,
ADCC1489-1601-3C3E-B3AD-B3907BEC0EF7.symbols,
B38C2164-0280-39EB-8D72-317128D9B3BB.symbols,
BB1B279C-67FF-36AB-8F79-64B4AB17D790.symbols,
C1038327-3EE4-3900-847B-4F62EB67041E.symbols,
C53AE701-9381-33E2-A2A1-34DA6D2BD4F5.symbols,
D2F7DE0E-DEE6-3C09-A1E6-7E29A3E2E205.symbols,
D3282D17-DDA5-3606-9D7E-004BFF0B020D.symbols,
DAEB8657-4560-347A-9EF9-2171ACF45C10.symbols,
E8B2167C-0F72-390A-93E8-FFFA1A91F5CD.symbols,
EC8E8914-17C3-3DF9-8C21-6424D3A738AE.symbols,
EE65FEFC-8628-3F8E-86E0-F72E3E422CDE.symbols,
EED8D0A4-3B00-3785-95EB-1C6A1A1D9BDD.symbols].

Best regards,

The App Store Team

Screenshots
error

My screenshot of the purchase product or my comment:
https://user-images.githubusercontent.com/27568540/66625373-4e512880-ebf4-11e9-9b30-c4a19f7d028d.jpeg

**Comment by minhtruong315** [comment]
Frameworks/Flutter.framework/Flutter: _ptrace
You need to run command: flutter build ios
Then try to archive by xcode

Push notification issue, you can follow this tutorial to check missing configuration
https://medium.com/flutterpub/enabling-firebase-cloud-messaging-push-notifications-with-flutter-39b08f2ed723

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
