### ISSUE TITLE
[Fluxstore-Woocommerce] - Blog problems

### ISSUE THREAD

**Issue by Therocky20** [inspireui/support#1292]
---------

1. My issue : I have problems with blog. It doen't load properly. You can access the blog in the left panel. i used the layout 6. with your blog is all fine, but when i put my website i can't see the posts. I have already setup a blog page in wordpress.

2- Screenshot of purchase: i have already some ticketes opened i will give you code in phase of support if you want.

3. Config files (optional)
[config.zip](https://github.com/inspireui/support/files/3777780/config.zip)

**Comment by minhtruong315** [comment]
I checked your website, it's working well. Please try again, if you have issues, please record screen

![Simulator Screen Shot - iPhone X - 2019-10-31 at 09 23 06](https://user-images.githubusercontent.com/10402500/67913572-1c622f00-fbc0-11e9-9f2d-f4fd0f57c8be.png)
![Simulator Screen Shot - iPhone X - 2019-10-31 at 09 23 18](https://user-images.githubusercontent.com/10402500/67913573-1c622f00-fbc0-11e9-9211-b45c4689354e.png)

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
