### ISSUE TITLE
MStore Pro - Complete React Native template for e-commerce

### ISSUE THREAD

**Issue by nizarklai** [inspireui/support#1293]
my question is i want to change the app to booking item for car rental 
so user can see car with price a day after that hi will book from calendar then hi will checkoout

**Comment by minhcasi** [comment]
Hi @nizarklai - the booking feature is not available for the Mstore Pro app, it needs some customization to support for this feature - thank you!

**Comment by nizarklai** [comment]
as i can see in your ather app there is booking https://codecanyon.net/item/listapp-listing-directory-mobile-app-by-react-native/21456447?s_rank=13
so i want to integrate this booking for the item in checkout that is all sir
