### ISSUE TITLE
fluxstore - version 1.5.6

### ISSUE THREAD

**Issue by Senior-Gamal** [inspireui/support#1294]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------
My issue

1 - in screenshot
2 - how to manage and edit the new Changes
  -  support Custom Page URL, Tag/Feature Products and Banner Items
  - add an option to limit Country when checkout
  -Add Billing and Shipping address auto from website

Screenshots
![1 5](https://user-images.githubusercontent.com/27568540/67667205-fcd7c600-f975-11e9-8829-885e74233f0d.jpg)

My screenshot of the purchase product or my comment:
https://user-images.githubusercontent.com/27568540/66625373-4e512880-ebf4-11e9-9b30-c4a19f7d028d.jpeg

**Comment by minhcasi** [comment]
@Senior-Gamal  - the latest 1.5.6 does not use this widget, could you help to double-check https://tppr.me/icMd9

**Comment by minhcasi** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days - if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!

**Comment by Senior-Gamal** [comment]
any answer about this

2 - how to manage and edit the new Changes

support Custom Page URL, Tag/Feature Products and Banner Items
add an option to limit Country when checkout
-Add Billing and Shipping address auto from website
and
support multi Shipping zone (woocommerce)
Add option to show/hide the Google Map picker
