### ISSUE TITLE
[Feature request fluxstore] - otp before confirming order

### ISSUE THREAD

**Issue by immortal-kid** [inspireui/support#1296]
(a) 1.5.6 version fixed all my previous errors. i just wanted to suggest a feature, similar to sms login in login screen, you could integrate the same in checkout page before placing order, so that only genuine customers will place orders, some random scammers will stay away.  after proceeding review page and before payment page, u could add this otp feature, only those who pass the otp can continue to payment page.

(b) i see you have points system in app, how does it work? is there any plugin to install in WordPress? 

(c) update ur documentation as per 1.5.6

**Comment by minhcasi** [comment]
Thank for your suggestion - noted as feature request

b/ it's compatible with https://woocommerce.com/products/woocommerce-points-and-rewards/ - this is missing part from the document as well

**Comment by minhcasi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [otp before confirming order](https://trello.com/c/qNqwDeQK/6-otp-before-confirming-order)

**Comment by minhcasi** [comment]
we are closing the ticket and move this ticket 'request feature' to our Trello board for easier to keep track, review, and update, also keep a status update  - thank you!
