### ISSUE TITLE
[Fluxstore pro] - Deep link issue in ubuntu and registration issue through email and facebook

### ISSUE THREAD

**Issue by Maksish** [inspireui/support#1297]
Registration issue through email and facebook
![Screenshot_20191029-002327 (1)](https://user-images.githubusercontent.com/31925489/67742306-b51e7080-fa41-11e9-8d73-26292596ae01.jpg)
![Screenshot_20191029-001826 (1)](https://user-images.githubusercontent.com/31925489/67742308-b780ca80-fa41-11e9-8615-a1d98f1d4deb.jpg)

deeplink issue
![Screenshot from 2019-10-29 11-43-41](https://user-images.githubusercontent.com/31925489/67742203-64a71300-fa41-11e9-9559-9ffb99ed5454.png)

![Screenshot_1572329434](https://user-images.githubusercontent.com/31925489/67742150-36293800-fa41-11e9-9155-4cc85ed46639.png)
my product
![Screenshot from 2019-10-29 00-34-00](https://user-images.githubusercontent.com/31925489/67742324-c7001380-fa41-11e9-8d4e-25dede1282db.png)

**Comment by minhcasi** [comment]
@Maksish - could you help to share your config file as well ?

**Comment by Maksish** [comment]
i have mailed u with askmkshaw@gmail.com and maksishshaw100@gmail.com

**Comment by Maksish** [comment]
@minhcasi  SUB MENU NOT SHOWING PRODUCT IN OPENCART

**Comment by minhcasi** [comment]
support via email - pls continuous the loops on your email thread - thanks
