### ISSUE TITLE
[MStore Pro] - Error

### ISSUE THREAD

**Issue by juniortimeline** [inspireui/support#1298]
1. Error while using 3.9.6

2. http://prntscr.com/ppload

3. https://codecanyon.net/comments/23068140

**Comment by minhcasi** [comment]
Hi, please make sure you have passed the basic install guide from - https://facebook.github.io/react-native/docs/getting-started.html - and can run the example project before using the Mstore app.

After install the react-native-cli, try to restart the command line to take effect.

**Comment by juniortimeline** [comment]
> @juniortimeline Try to follow these steps:
> rm -rf node_modules/ && npm install && cd android/ && ./gradlew clean && cd ../ && react-native run-android

@concuacon thanks for response and this is what happened after I apply that command http://prntscr.com/pqt4w9

**Comment by concuacon** [comment]
@juniortimeline 
The power shell does not support '&&' This is not a problem, you can split each command to execute eg:
npm install
android cd
./gradlew clean
cd ../
react-native run-android 
or you can replace '&&' with ';' : rm -rf node_modules/ ; npm install ; cd android/ ; ./gradlew clean ; cd ../ ; react-native run-android

**Comment by juniortimeline** [comment]
> @juniortimeline
> If the power shell does not support '&&' this is not a problem, you can split each command to execute eg:
> npm install
> android cd
> ./gradlew clean
> cd ../
> react-native run-android
> or you can replace '&&' with ';' : rm -rf node_modules/ ; npm install ; cd android/ ; ./gradlew clean ; cd ../ ; react-native run-android

After I run
1. cd android
2. gradlew clean
3. cd ../
4. react-native run-android
this is what happened http://prntscr.com/pr7x1v thank you so much @concuacon and @minhcasi

**Comment by minhcasi** [comment]
Ok cool, let us know if you have any questions :)
