### ISSUE TITLE
[fluxstore 1.5.6] - product list in vertical list view

### ISSUE THREAD

**Issue by immortal-kid** [inspireui/support#1299]
i found one app that showed products in vertical list like this https://prntscr.com/ppt06a is it possible to do it in fluxstore? currently grid view and some other views support, but not this type. this looks simple and neat.
https://prntscr.com/ppt06a

my purchase http://prntscr.com/pjvdg2

**Comment by minhcasi** [comment]
Hi, i could not see the screenshot - https://tppr.me/xMPKW

**Comment by minhtruong315** [comment]
We don't support this layout. but you still add more layout. You need to know flutter to do it

**Comment by immortal-kid** [comment]
yes, i know we can change however we want, i just suggested u that u can add this type of layout in future release.

**Comment by minhtruong315** [comment]
Yes. We'll add it in future. Thanks
