### ISSUE TITLE
[ListApp]Hi, I’ve an issue on maps. It doesn’t works properly because, it have a some loading splash issue. while opening map at first time it has loading into splash screen again reload into homepage. Otherwise, while touch the screen or zooming the map white blank screen will appear. this types of issues are all happening at the first time opening the app. Whenever the app is loaded a fresh the loading flash issue arises, and it works better when the app is launched from memory. When we close the app and try again. similar loading error is coming.

### ISSUE THREAD

**Issue by Pavithran10** [inspireui/support#130]
**Required Info (please complete the following information):**
 - Product: [e.g. MStore, ListApp]
 - Your Purchased Code: [get from https://codecanyon.net/downloads]
(we may not reply if you are not our customer)

**Describe the bug**

**Screenshots**

**Additional context**
Add any other detail logs about the problem here.
If possible please share your config.js that use for the app setting

**Comment by minhcasi** [comment]
Hi, could you help to format the ticket, provide your purchase code, and explain the detail / screenshot - thank you!

**Comment by Pavithran10** [comment]
Can I give purchase code here itself?  Is it not public forum ?

I have attached error video.
[err video.zip](https://github.com/inspireui/support/files/2712465/err.video.zip)
