### ISSUE TITLE
[fluxstore 1.5.6] - major bug in new update. details in config page not reflecting

### ISSUE THREAD

**Issue by immortal-kid** [inspireui/support#1301]
my purchase http://prntscr.com/pjvdg2

Any changes i do in config.json file is not reflecting on app, it is still showingyour default settings, i ran flutter clean, restarted android studio, uploaded config.json to wordpress mstore plugin,  cleared rest cache, site cache still no use

**Comment by minhcasi** [comment]
Hi, this is new Caching method - pls check this guide https://docs.inspireui.com/fluxstore/dynamic-load/#2-caching - it will help to load your app data in 1s on the homepage - https://tppr.me/GB9Bt

To revert back to local config, change isCaching: false from the config.dart

**Comment by immortal-kid** [comment]
in config.dart i changed categories layout to sidemenu but it is not changing in the app, ran flutter clean, cache is disabled only, still not changed.

**Comment by immortal-kid** [comment]
in config.dart i changed categories layout to sidemenu but it is not changing in the app, ran flutter clean, cache is disabled only, still not changed.
