### ISSUE TITLE
[flux-news] - Setup

### ISSUE THREAD

**Issue by fernandadsc** [inspireui/support#1303]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue
I can't install fluxNews. Can someone walk me trough the setup over a video call?  I've managed to install mostly of whats needed but got stuck. 

2. Screenshots

3. My screenshot of the purchase product or my comment:
https://codecanyon.net/item/fluxnews-fluxnews-flutter-mobile-app-for-wordpress/24569377?_ga=2.154797311.616928442.1572433835-1396313198.1568380781

3. Config files (optional)

**Comment by minhcasi** [comment]
could you help to clarify more detail of your issues so that we could help for a suggestion?

Please help to try your best to install Flutter by using the guide from Google - https://flutter.dev/docs - there is a lot of video guide from Youtube to support for this basic install 

After you pass the Test Drive guidline, install the Fluxnews quite simple - thanks

**Comment by bakpaorabbit** [comment]
> 
> 
> > * Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> > * Try to explain your all problems in one ticket, instead of creating multi tickets
> > * After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> > * IMPORTANT: We will close the ticket if you could not prove as our customer.
> 
>     1. My issue
>        I can't install fluxNews. Can someone walk me trough the setup over a video call?  I've managed to install mostly of whats needed but got stuck.
> 
>     2. Screenshots
> 
>     3. My screenshot of the purchase product or my comment:
>        https://codecanyon.net/item/fluxnews-fluxnews-flutter-mobile-app-for-wordpress/24569377?_ga=2.154797311.616928442.1572433835-1396313198.1568380781
> 
>     4. Config files (optional)

maybe we experience the same problem ? , here : https://github.com/inspireui/support/issues/1283

**Comment by dttrung26** [comment]
Hi @fernandadsc ,
could you declare as detailed as possible what trouble on installing you are in? Besides, please make sure that all of your set up for Flutter are perfectly done. Please take a look on https://flutter.dev/docs for Flutter docs.

Cheers!

**Comment by fernandadsc** [comment]
I'm getting this error on Android Studio and also on Xcode / terminal... 

https://www.dropbox.com/s/fqb56hov2zpq0ox/Screenshot%202019-11-02%2022.22.36.png?dl=0
https://www.dropbox.com/s/4x5uxskmwhd5axj/Screenshot%202019-11-02%2022.47.33.png?dl=0

**Comment by fernandadsc** [comment]
hi, just to update: I've managed to solve it by updating the settings like @bakpaorabbit  mentioned from another issue related.
