### ISSUE TITLE
[Fluxstore 1.5.6] - issue can´t start after setup

### ISSUE THREAD

**Issue by EmilianH** [inspireui/support#1304]
Please Help me i can´t start the app!, i made all the settings from the tutorial but crash after the splash screen, i installed in final domain www.mamapp.com.ar and  made 2 categories and in config  file put the category id.

![issue01](https://user-images.githubusercontent.com/57189819/67879805-57128b80-fb1c-11e9-9893-daf552894223.jpg)
![issue01a](https://user-images.githubusercontent.com/57189819/67879806-57128b80-fb1c-11e9-8821-3779ffd8f445.jpg)
[55640809-fluxstore-woocommerce-flutter-ecommerce-full-app-license (2).pdf](https://github.com/inspireui/support/files/3790181/55640809-fluxstore-woocommerce-flutter-ecommerce-full-app-license.2.pdf)
[configfiles.zip](https://github.com/inspireui/support/files/3790212/configfiles.zip)

The following NoSuchMethodError was thrown building MainTabs(dirty, dependencies: [InheritedProvider<UserModel>, MediaQuery, InheritedProvider<AppModel>, InheritedProvider<CartModel>], state: MainTabsState#b40b1): The method ‘[]’ was called on null. Receiver: null Tried calling: [](“Home”)

════════ (2) Exception caught by scheduler library ═════════════════════════════════════════════════ The getter ‘length’ was called on null. Receiver: null Tried calling: length

how can i fix it? i need  to present the app this week, please help asap

thanks a lot

**Comment by minhcasi** [comment]
@EmilianH - pls check solution on this ticket - https://github.com/inspireui/support/issues/1307
