### ISSUE TITLE
[fluxstore 1.5.6] - categories layout cannot change

### ISSUE THREAD

**Issue by immortal-kid** [inspireui/support#1305]
from #1301 

in config.dart i tried changing it categories layout to sidemenu, grid and animation but it is not changing in the app, ran flutter clean, cache is disabled only, still not changed.

**Comment by immortal-kid** [comment]
I'm talking about this https://prntscr.com/pqfqwl

**Comment by minhtruong315** [comment]
We removed changing category layout in config.dart. You can change category in config.json like this
```
 "TabBar": {
    "Home": {
      "isDisplay": true
    },
    "Category": {
      "isDisplay": true,
      "layout": "card"
    },
    "Search": {
      "isDisplay": true
    },
    "Cart": {
      "isDisplay": true
    },
    "Profile": {
      "isDisplay": true
    }
  }
```
