### ISSUE TITLE
FLuxbuilder

### ISSUE THREAD

**Issue by ceschieber** [inspireui/support#1306]
Hello everyone. First of all I would like to thank you for your commitment and dedication to this project. I saw something related in another topic talking about Fluxbuilder. Have a forecast date?

**Comment by minhcasi** [comment]
@ceschieber - we are going to release it on app stores on next week, this app is free for use with all basic feature - thank you!

**Comment by minhcasi** [comment]
![Simulator Screen Shot - iPad Pro (12 9-inch) (3rd generation) - 2019-10-31 at 18 58 56](https://user-images.githubusercontent.com/1459805/67947389-23b42780-fc16-11e9-9252-a1a109902d7c.png)
![Simulator Screen Shot - iPad Pro (12 9-inch) (3rd generation) - 2019-10-31 at 18 59 00](https://user-images.githubusercontent.com/1459805/67947390-23b42780-fc16-11e9-892f-2f077c68a278.png)

**Comment by ceschieber** [comment]
Thank you. I wish you success in development.
