### ISSUE TITLE
[fluxstore demo app lamguage bug]

### ISSUE THREAD

**Issue by immortal-kid** [inspireui/support#1308]
i found this language bug,
i changed to Vietnam language in settings, it was Vietnam language in the app. but when i close the app and open again, it was English,  when i found this bug i checked ur demo app in playstore, even ur demo app had this issue. please look into it, people get annoyed if they want to change language each time.

**Comment by minhcasi** [comment]
ok man, thank you for reporting, we have noted as the bug for fixing on next release

**Comment by minhcasi** [comment]
confirmed this is fixed on the latest version - we will release it soon

**Comment by minhcasi** [comment]
Hi mate, this bug is fixed on latest 1.5.9 - thank you!
