### ISSUE TITLE
[Mstore Multivendor] Facebook Login not  working for Mstore

### ISSUE THREAD

**Issue by cdalsoniii** [inspireui/support#131]
**Required Info (please complete the following information):**
 - Mstore MultiVendor
 - Your Purchased Code: 9421ca90-2f96-48bd-82b8-fe39f4b5c3c0

**Describe the bug**

Greetings,

I am currently experiencing some interesting issues with my attempt to actually accomplish a successful facebook login request. I cannot seem to be able to make a successful

request. At this point the facebook login feature is working correctly in the expo emulator and the request to the facebook authentication server is made correctly. When the authentication

request fails or is not sent at all is on the actual physical device.

I have pulled the logs from the physical device is the the following error:

exponent (libnetwork.dylib) nw_socket_handle_socket_event [C:39] Socket SO_ERROR [61: Connection refused]

Please attach here:

Attached: Screenshots, [Video]

Please let me know if you need any further explanation.

Best,

**Screenshots**
The facebook button simply does not do anything but the login feature works on the emulator. I do not think a screenshot is needed.

**Additional context**
Add any other detail logs about the problem here.
If possible please share your config.js that use for the app setting

**Comment by minhcasi** [comment]
Hi, There is still missing the attached, could you help to upload it to Cloud ?

**Comment by cdalsoniii** [comment]
There are no attachments. The error code is enough.

**Comment by cdalsoniii** [comment]
Any update on this?

**Comment by luyx2412** [comment]
Hi please follow to template, update your attached and Config.js file.

Thanks

**Comment by cdalsoniii** [comment]
![simulator screen shot - iphone x - 2018-12-29 at 06 30 09](https://user-images.githubusercontent.com/8814807/50537828-3f9cf780-0b33-11e9-8ccc-65e5bcab8e0d.png)

![img-0644](https://user-images.githubusercontent.com/8814807/50537945-2301bf00-0b35-11e9-99ed-17f2353005e1.JPG)

![img-0645](https://user-images.githubusercontent.com/8814807/50537946-2301bf00-0b35-11e9-9f99-4b3f94ed83f3.JPG)

One picture in emulator, the one on the actual phone just continually loads and doesnt do anything.

[Config_js.txt](https://github.com/inspireui/support/files/2716313/Config_js.txt)

**Comment by minhcasi** [comment]
Note and fixed, this will be released on this week - thank you!

**Comment by luyx2412** [comment]
Closed and fixed with new version!
