### ISSUE TITLE
[Mstore Pro] - Checkout Webview issues

### ISSUE THREAD

**Issue by yoanb** [inspireui/support#1310]
Hi, I have a problem with the language displayed in the checkout page in the webview. 
My store is configured with the french language but all the fields are in english. Moreover, I have an issue with price’s format. The tag “span class = woocommerce-price-amount amount” appears.
Thanks for feed-back

https://prnt.sc/pqjkx5
http://prnt.sc/pqjjvr
https://prnt.sc/pqjkm7

**Comment by minhcasi** [comment]
@yoanb - could you share your proof purchased screenshot from - https://codecanyon.net/downloads - thank you!

**Comment by yoanb** [comment]
> @yoanb - could you share your proof purchased screenshot from - https://codecanyon.net/downloads - thank you!

Sorry ! this is:
Item Purchase Code:
25b71fd2-d641-4527-a5a0-783f4a3c66e5
Purchase Date:
2019-06-15 12:37:13 UTC

**Comment by minhcasi** [comment]
@yoanb - thank you for the detail

You can try to customize the check out Form from the mstore-api plugins, we use this file to generate the form at the checkout website - https://github.com/inspireui/mstore-api/blob/master/templates/mstore-api-template.php

The problem could cause by some customize payment plugins that show this page
