### ISSUE TITLE
[Mstore Pro] - Splash screen don;t change

### ISSUE THREAD

**Issue by mk4full** [inspireui/support#1311]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue

I upload new splash screen, but it not changed (expo version)

2. Screenshots
https://ibb.co/R4ysvys

3. My screenshot of the purchase product or my comment:

https://ibb.co/9wrv1QN

**Comment by minhcasi** [comment]
Hi, the expo splash screen could be change by update the app.json - https://tppr.me/J9J8I
