### ISSUE TITLE
ITMS-90809: Deprecated API Usage

### ISSUE THREAD

**Issue by erknertn** [inspireui/support#1312]
Hi,
Mstore multivendor
Item Purchase Code: 014a35ed-08f8-42b1-bb3c-b746ee7f202a

How can I solve this problem?

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to App Store Connect.

**Comment by minhcasi** [comment]
Hi, these warning will not impact to the app and you can still release on Appstore - we will maintain some related library and update on next release version - thanks
