### ISSUE TITLE
[mstore pro] - empty screen up to few second after splash

### ISSUE THREAD

**Issue by mk4full** [inspireui/support#1313]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue
Why display empty screen after splash screen upto 5sec ? 

2. Screenshots

https://streamable.com/s/on5hr/pbnkoj

3. My screenshot of the purchase product or my comment:

https://ibb.co/9wrv1QN

3. Config files (optional)

**Comment by minhcasi** [comment]
noted with investigating

**Comment by mk4full** [comment]
When can I expect resolve it?

**Comment by concuacon** [comment]
Hello, @mk4full can you share with me file Config.js and AppConfig.json? On my device, it works fine.

**Comment by mk4full** [comment]
@concuacon here is my files https://gofile.io/?c=F0kRpN

Thanks!

**Comment by concuacon** [comment]
@mk4full ok I'll check and feedback you soon.

**Comment by concuacon** [comment]
Hello @mk4full I checked and it worked fine when you release the app do you switch from "debug" mode to "release"?

**Comment by mk4full** [comment]
@concuacon Thank you.  I don't know sir, how can i check it?

**Comment by concuacon** [comment]
Hello @mk4full 
To do that, navigate to your projects **/ios** directory and open the .xcodeproj file in Xcode. Choose your build target in the Toolbar. Scroll to the bottom and choose "**Edit Scheme...**". Then under Build Configuration, switch from "**Debug**" to "**Release**". Now build your app on your target device and it should be much more performant than before.

**Comment by mk4full** [comment]
@concuacon  problem of empty screen occure in expo verion, there are not see /ios folder

**Comment by concuacon** [comment]
@mk4full 
sorry I thought you were using the cli version, temporarily you edited the App.js file as shown, I will fix this problem in the next version, or you can use the cli version, thank you
