### ISSUE TITLE
[Fluxstore] - Error updating application to 1.5.7

### ISSUE THREAD

**Issue by rodrigoalves1901** [inspireui/support#1314]
Good afternoon. when trying to upgrade to new version 1.5.7 of the following message when leaving splash screen

![image](https://user-images.githubusercontent.com/43248152/67989124-42132680-fc08-11e9-8448-44b052673486.png)

**Comment by minhcasi** [comment]
@rodrigoalves1901 - could i check if you are using the same config file on 1.5.7 or it is customize one, please compare 2 files if you have modified

**Comment by minhcasi** [comment]
#1307 1307

**Comment by minhcasi** [comment]
#1307

**Comment by minhtruong315** [comment]
@rodrigoalves1901 check this comment: https://github.com/inspireui/support/issues/1307#issuecomment-548352113

**Comment by rodrigoalves1901** [comment]
Good morning. I had seen this post do the procedure and continue the error. I didn't just update what was modified I took the whole file and ran it from scratch and the error goes on

![image](https://user-images.githubusercontent.com/43248152/68086130-cd660500-fe1e-11e9-83e5-37ca5fac7ff8.png)

**Comment by minhtruong315** [comment]
You can set isCaching:false in config.dart. Then run again

**Comment by rodrigoalves1901** [comment]
Hello, you can put isCaching: false. But still not solved the problem of delivery for me still calculating zero.

![image](https://user-images.githubusercontent.com/43248152/68138100-63249180-fefe-11e9-9381-441128a12657.png)

**Comment by minhtruong315** [comment]
Did you set cost for that shipping in admin?

**Comment by rodrigoalves1901** [comment]
Good Morning. yes as spoken in the open call # 1287 on the site calculates however in the application no. You said that in the new update would fix only that still does not rise.

![image](https://user-images.githubusercontent.com/43248152/68314368-706f8680-008c-11ea-942f-8453f49dce91.png)

**Comment by minhtruong315** [comment]
send me admin account via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/1314

**Comment by rodrigoalves1901** [comment]
Hello, I already sent the email. Any solution? I have not yet had accurate feedback on this urgent solution as we are standing waiting for this solution.

**Comment by minhtruong315** [comment]
Can you show me where did you set the cost in admin?

**Comment by rodrigoalves1901** [comment]
Yes, follow the video of my site.

https://streamable.com/01v7r

**Comment by rodrigoalves1901** [comment]
Any solution?

**Comment by rodrigoalves1901** [comment]
Any solution? I need urgent!

**Comment by minhtruong315** [comment]
I will check it

**Comment by rodrigoalves1901** [comment]
Thank you!

**Comment by minhtruong315** [comment]
duplicate: https://github.com/inspireui/support/issues/1489#issuecomment-561441749
