### ISSUE TITLE
Fluxstore - cannot change the homescreen layouts

### ISSUE THREAD

**Issue by spinner2009** [inspireui/support#1315]
Hi,

I have just bought the FluxStore app and need your help.

1. My issue
I have configured the latest version (1.5.7 updated on 31.10.2019) on my local laptop in Visual Studio Coe by going through the configuration steps described in the Getting Started doc (https://docs.inspireui.com/fluxstore/getting-started/)

Then I wanted to try the different Home layouts as described in the docs (https://docs.inspireui.com/fluxstore/home-layout/). When I copy paste the content of the lib/example/woocommerce/config_theme6.json file in lib/common/config.json the home screen remains the same to the default one. I have tried flutter clear, hot reload, restarting the session, closing Visual Studio Code and the emulator etc. I am using a Google Pixel 3 emulator.

Can you advise how can I load the different home layout screens?

2. Screenshots
I don't have screenshots. My app loads as if I started it for the first time.

3. My screenshot of the purchase product or my comment:
This is the link from Code Canyon https://codecanyon.net/item/fluxstore-woocommerce-flutter-ecommerce-full-app/24050041/support

3. Config files (optional)

**Comment by minhtruong315** [comment]
@spinner2009 can you show me erorr picture?
you can try this theme
[config_theme6.json.zip](https://github.com/inspireui/support/files/3801223/config_theme6.json.zip)

**Comment by spinner2009** [comment]
Hello,

First of all you app is very nice. Good work on it!

In the meantime I figured out via debuging that the app was loading the config from cache. I have commented out the following lines from app.dart > loadAppConfig

if (serverConfig["type"] == "woo" && kAdvanceConfig['isCaching']) {
        final configCache = await Services().getHomeCache();
        if (configCache != null) {
          appConfig = configCache;
        }
Can you please explain how the caching works? For example, once a homepage gets cached is there anything I need to do to get the cache reset so that I can change to a different layout without commenting the code?

I have few more questions:

1. I cannot find the Custom Animate homepage layout (layout 14 from the documentation, see attachment)

2. On my system Win 10, Visual Studio Code, flutter 1.9.1 hotfix4 I get the error below when trying to open the homepage layouts 17, 18, 19 (the ones with the Magento and Opencart text). I have the Woocommerce version of the app, but I am only interested in the homelayout visuals not the actual Magento or Opencart features.


════════ Exception caught by rendering library ═════════════════════════════════
RenderBox was not laid out: RenderCustomPaint#457ed relayoutBoundary=up2 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1681 pos 12: 'hasSize'
User-created ancestor of the error-causing widget was
    SingleChildScrollView 
lib\…\home\index.dart:89
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
RenderBox was not laid out: RenderRepaintBoundary#748f3 relayoutBoundary=up1 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1681 pos 12: 'hasSize'
User-created ancestor of the error-causing widget was
    Consumer<AppModel> 
lib\screens\home.dart:120
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
RenderBox was not laid out: RenderStack#6f7cf NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1681 pos 12: 'hasSize'

3. I have noticed that the app has code related to several onboarding screens in lib/common/config.dat > onBoardingData. Can you advise how can I leverage the onboarding screens?

Many thanks,
Dan
![custom_animate_app_home_layout](https://user-images.githubusercontent.com/48594963/68085610-f8fae680-fe42-11e9-8d5f-e5b75b4121dd.jpg)

**Comment by minhtruong315** [comment]
You can set isCaching:false in config.dart to disable cache

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
