### ISSUE TITLE
[mstore pro] - custom changes sales percentage and affiliate product 

### ISSUE THREAD

**Issue by mk4full** [inspireui/support#1316]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue

I apologize for next request, but I woud like finished my app. 

a) Is it posiible to set sales precentage field on home layout too? I mean:
here is sales field: https://ibb.co/mJBTkx1
I would like the same filed sales on home: https://ibb.co/rv8gNDv 

b) second issue is an button of affilite product https://ibb.co/KwSRTMt - when you click "buy now" we are direct to internal page on myshop instead direct to external link affiliate shop 

Thank you for help!

3. My screenshot of the purchase product or my comment:

https://ibb.co/9wrv1QN

**Comment by minhcasi** [comment]
@mk4full 

a.  it's possible - we will update on next version as it seems a missing feature 

b. Try to enable the common/config.js to Affiliate: { enable: true } - this config will support for affiliate product types.

**Comment by mk4full** [comment]
thank you for answer. yes I set affiliate: { enable: true }, but in this option we are direct to internal page on myshop instead direct to external link affiliate shop
