### ISSUE TITLE
Fluxstore Pro - Unhandled Exception: FormatException: Unexpected character 

### ISSUE THREAD

**Issue by shrinet** [inspireui/support#1317]
1. My issue - I am getting error of `Unhandled Exception: FormatException: Unexpected character ` in opencart installation. Details error 
`E/flutter ( 2236): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: FormatException: Unexpected character (at character 5981) 
E/flutter ( 2236): ...Electric Robot With 360\u00b0 Rotate, Lights &amp; Music 3+ Ages, <br><span`
In product description there is written as `Electric Robot With 360° Rotate` Please help me.

2. Screenshots https://imgur.com/WtuHDnj

3. My screenshot of the purchase product or my comment: https://imgur.com/LYRsCIQ

3. Config files (optional)

**Comment by minhcasi** [comment]
@shrinet - it seems the issues cause by the data, could you mind to share your config files (common/config.dart and config.json)?

**Comment by shrinet** [comment]
@minhcasi thanks for your reply, yes It is due to json data. There are few non utf-8 characters I think. However I fixed it by adding new line `$result["description"] = htmlentities(stripslashes(utf8_encode($result["description"])));` at `/catalog/controller/extension/mstore/product.php` line number 131. However It results in showing html tags in Description section.

As per your request config files are-


config.dart - https://gist.github.com/shrinet/36588747c114e4cb6fb33f8109ec796f
config.json - https://gist.github.com/shrinet/6bce2aca38506bdcdef92749dbaf4e64

Please suggest

**Comment by minhtruong315** [comment]
@shrinet You can replace this file screens/detail/product_description.dart to fix that error
[product_description.dart.zip](https://github.com/inspireui/support/files/3801236/product_description.dart.zip)

**Comment by shrinet** [comment]
Thanks for your support, I changed the said modification. Its fixed now.......

However I found an error on next stage(on cart page) upon clicking 'Checkout' a warning toast saying 'cannot add items to cart '.

Please suggest,.

**Comment by minhtruong315** [comment]
@shrinet you must login before checkout

**Comment by shrinet** [comment]
no, Its not working after login too....... Please suggest

**Comment by minhtruong315** [comment]
@shrinet I don't why checkout api dont work on your website. I need to debug it on localhost to find the problem. Can u send me your website via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/1317

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
