### ISSUE TITLE
[FluxStore] - No such file or directory import 'package:fstore/screens/detail/FullsizeLayout.dart';

### ISSUE THREAD

**Issue by The-Egyptian-Developers** [inspireui/support#1318]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue
Compiler message:
lib/screens/detail/index.dart:5:8: Error: Error when reading 'lib/screens/detail/FullsizeLayout.dart': No such file or directory
import 'package:fstore/screens/detail/FullsizeLayout.dart';
       ^
lib/screens/detail/index.dart:90:14: Error: Method not found: 'FullsizeLayout'.
      return FullsizeLayout(product: product);
             ^^^^^^^^^^^^^^
Compiler failed on /home/***/Downloads/work/mahgoub/2019/new back/mahgoub app/source/lib/main.dart

FAILURE: Build failed with an exception.

* Where:
Script '/home/***/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 765

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebugX86'.
> Process 'command '/home/***/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s
Finished with error: Gradle task assembleDebug failed with exit code 1

2. Screenshots
https://send.firefox.com/download/fc6ee6111054d34f/#K9AjMOL-Xp4JDPZlzLDp-Q

3. My screenshot of the purchase product or my comment:
https://send.firefox.com/download/14d3d08d2f3fe237/#ivJxygXbctQw3drdF48Epg
3. Config files (optional)

**Comment by minhtruong315** [comment]
@The-Egyptian-Developers you can update ```import 'package:fstore/screens/detail/fullsizeLayout.dart';``` in screens/detail/index.dart

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
