### ISSUE TITLE
[BeoNews] Problem with demo content

### ISSUE THREAD

**Issue by gatewaystudiosuy** [inspireui/support#1319]
My question in codecayon: I change the website data but still bring the demo data, the appconfig.json file generates it correctly.

Your response in codecayon: InspireUI Author

Hi, could you help to share the config file to https://github.com/inspireui/support/issues – we will help for checking, it could be the cache issue on your simulator, please try to restart the app after change the config – thank you!

I attach generated files, renamed to txt to upload them in git

[Config.txt](https://github.com/inspireui/support/files/3800168/Config.txt)

[AppConfig.txt](https://github.com/inspireui/support/files/3800169/AppConfig.txt)

**Comment by gatewaystudiosuy** [comment]
News?

**Comment by minhcasi** [comment]
@gatewaystudiosuy - the problem is you did not change the category id for each config - https://tppr.me/AWvcT

Please check this config - 
[AppConfig.json.txt](https://github.com/inspireui/support/files/3807853/AppConfig.json.txt)

Related doc - https://docs.inspireui.com/beonews/customization/

**Comment by gatewaystudiosuy** [comment]
I still have the problem, do I have to clear some kind of cache in the application or something? I remind you that the generation of the appconfig.json file is done by cebuilder
