### ISSUE TITLE
[Mstore Multivendor] Jest unable to test components

### ISSUE THREAD

**Issue by cdalsoniii** [inspireui/support#132]
**Required Info (please complete the following information):**
 - Product: Mstore Multivendor
 - Your Purchased Code: 9421ca90-2f96-48bd-82b8-fe39f4b5c3c0

Is there any supper for Jest testing? I cannot seem to run Jest tests on any of my components. Even the simple new components fail with the following error:

Jest encountered an unexpected token This usually means that you are trying to import a file which Jest cannot parse, e.g. it’s not plain JavaScript. By default, if Jest sees a Babel config, it will use that to transform your files, ignoring “node_modules”. Here’s what you can do: • To have some of your “node_modules” files transformed, you can specify a custom “transformIgnorePatterns” in your config. • If you need a custom transformation specify a “transform” option in your config. • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the “moduleNameMapper” config option. You’ll find more details and examples of these config options in the docs: https://jestjs.io/docs/en/configuration.html Details:

**Comment by luyx2412** [comment]
Hi @cdalsoniii Now i do not support Jest. And we do not plan using Jest in the future. You can read the document to use Jest https://jestjs.io/docs/en/getting-started in your app. 

Thanks

**Comment by cdalsoniii** [comment]
Ok, if jest is not supported then how are we supposed to implement testing.
