### ISSUE TITLE
[Fluxstore] - Error coming in shipping methods screen, FormtException . Invalid double

### ISSUE THREAD

**Issue by spss20** [inspireui/support#1321]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: In your app new update , this error is coming, it is working fine when consumer key and secret is set to your default mstore site, so i think the problem is in backend of my woocommerce. Can you plz check.

2. Screenshots
![WhatsApp Image 2019-11-02 at 2 11 49 PM](https://user-images.githubusercontent.com/29224720/68068435-c1286c00-fd7a-11e9-877c-07366812e2a2.jpeg)

3. My screenshot of the purchase product or my comment:
![Screenshot (96)](https://user-images.githubusercontent.com/29224720/68068461-05b40780-fd7b-11e9-8c07-7be9d97b2089.png)

3. Config files (optional)

**Comment by minhtruong315** [comment]
@spss20 did you set ZoneIdShipping in config.dart exactly according to your website?

**Comment by spss20** [comment]
i resolved by myself , thank you.

**Comment by atheeblk** [comment]
> i resolved by myself , thank you.

Hey, how did you resolve it? Thanks

**Comment by nizarweb77** [comment]
please what is the solution for it

**Comment by AndresReyesDev** [comment]
> please what is the solution for it

I've the same problem: the problem was one of the Shipping Methods with no value in the cost of it (because it's free), so I put a zero on the cost, save it and problem solved. I hope this helps you..
