### ISSUE TITLE
[fluxstore pro] opencart product options i make an api

### ISSUE THREAD

**Issue by mohmmadmoatz** [inspireui/support#1322]
Hello .. i have been edit the product controller in mstoreapi opencart to make it show the products options

```
 $options = $this->model_catalog_product->getProductOptions($result["product_id"]);

 $opt = array();

  if(count($options) !=0){
        for ($x = 0; $x <= count($options); $x++) {

          
          if($options[$x]['product_option_value']){

            $optvalue =  $options[$x]['product_option_value'];

            for ($i=0; $i <count($optvalue) ; $i++) { 
                if($options[$x]['product_option_value'][$i]['optimage']){
                  $options[$x]['product_option_value'][$i]['optimage'] = $this->model_tool_image->resize($options[$x]['product_option_value'][$i]['optimage'] , 600, 600);
                }else{
                    $options[$x]['product_option_value'][$i]['optimage'] = $this->model_tool_image->resize('placeholder.png', 600, 600);

                }
            }

          }


    }
      }

  $result["opt"] = $options;
```

**Comment by mohmmadmoatz** [comment]
@minhcasi 
@luyx2412 
@vumanhsn97

**Comment by minhcasi** [comment]
@mohmmadmoatz - appreciated for your sharing
@minhtruong315

**Comment by minhtruong315** [comment]
@mohmmadmoatz We dont support product options for opencart now. if you wanna add product options in app, you must edit more UI layout. 
We'll update product options in the future
Thanks

**Comment by minhcasi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [opencart product options](https://trello.com/c/yskKkVZG/5-opencart-product-options)

**Comment by minhcasi** [comment]
we are closing the ticket and move this ticket 'request feature' to our Trello board for easier to keep track, review, and update, also keep a status update  - thank you!
