### ISSUE TITLE
[mstore pro] - error after react-native run-android

### ISSUE THREAD

**Issue by mk4full** [inspireui/support#1323]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue

I was try run pro version, but display error: 

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\saler-app\mstore-3.9.6\mstore-pro\node_modules\@react-native-community\async-storage\android\build.gradle' line: 36

* What went wrong:
A problem occurred evaluating project ':@react-native-community_async-storage'.
> Failed to apply plugin [id 'com.android.library']
   > Could not create plugin of type 'LibraryPlugin'.
      > Could not generate a decorated class for class com.android.build.gradle.LibraryPlugin.
         > com/android/builder/errors/EvalIssueReporter

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s

error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\saler-app\mstore-3.9.6\mstore-pro\node_modules\@react-native-community\async-storage\android\build.gradle' line: 36

* What went wrong:
A problem occurred evaluating project ':@react-native-community_async-storage'.
> Failed to apply plugin [id 'com.android.library']
   > Could not create plugin of type 'LibraryPlugin'.
      > Could not generate a decorated class for class com.android.build.gradle.LibraryPlugin.
         > com/android/builder/errors/EvalIssueReporter

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s

    at checkExecSyncError (child_process.js:621:11)
    at execFileSync (child_process.js:639:15)
    at runOnAllDevices (C:\saler-app\mstore-3.9.6\mstore-pro\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:74:39)
    at buildAndRun (C:\saler-app\mstore-3.9.6\mstore-pro\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:158:41)
    at C:\saler-app\mstore-3.9.6\mstore-pro\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:125:12
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async Command.handleAction (C:\saler-app\mstore-3.9.6\mstore-pro\node_modules\@react-native-community\cli\build\cliEntry.js:160:7)

can U help me?

3. My screenshot of the purchase product or my comment:

https://ibb.co/9wrv1QN

**Comment by concuacon** [comment]
@mk4full  you try clean node_modules and reinstall with a command line: 
yarn; cd android/ ; ./gradlew clean; cd ../; react-native run-android
If it still not work, you can check this link: https://github.com/react-native-community/async-storage/issues/137

**Comment by concuacon** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
