### ISSUE TITLE
[Fluxstore 1.5.7] - issues/bugs

### ISSUE THREAD

**Issue by EmilianH** [inspireui/support#1324]
[55640809-fluxstore-woocommerce-flutter-ecommerce-full-app-license (1).pdf](https://github.com/inspireui/support/files/3801110/55640809-fluxstore-woocommerce-flutter-ecommerce-full-app-license.1.pdf)

**Comment by minhtruong315** [comment]
@EmilianH I see your zone id is 2, but in config.dart is 1
"ZoneIdShipping": [1],
please update ZoneIdShipping in config.dart file

**Comment by EmilianH** [comment]
![shipping-error01](https://user-images.githubusercontent.com/57189819/68093208-067b9500-fe72-11e9-9878-87767a987120.jpg)

I changed the zoneshipping to 2 and the same error remains.

**Comment by EmilianH** [comment]
please help me!!!

**Comment by EmilianH** [comment]
i think the problem is because i not configures MERCADOPAGO that include shipping MERCADOENVIO, please help! i can´t work with the app without full setup

**Comment by EmilianH** [comment]
???

**Comment by minhtruong315** [comment]
send me admin account via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/1324

**Comment by minhtruong315** [comment]
You can try to replace getShippingMethods function in services/woo_commerce.dart file to fix shipping
```
@override
  Future<List<ShippingMethod>> getShippingMethods(
      {Address address, String token}) async {
    try {
      List<ShippingMethod> list = [];
      for (var id in kAdvanceConfig["ZoneIdShipping"]) {
        var response = await wcApi.getAsync("shipping/zones/$id/methods");
        if (response is Map && isNotBlank(response["message"])) {
          throw Exception(response["message"]);
        } else {
          var res = await wcApi.getAsync("shipping/zones/$id/locations");
          if (res is Map && isNotBlank(res["message"])) {
            throw Exception(res["message"]);
          } else {
            List locations = res;
            bool isValid = true;
            bool checkedPostcode = false;
            locations.forEach((o) {
              if (o["type"] == "country" && isValid) {
                isValid = address.country == o["code"];
              }
              if (o["type"] == "postcode" &&
                  ((!checkedPostcode && isValid) ||
                      (checkedPostcode && !isValid))) {
                isValid = address.zipCode == o["code"];
                checkedPostcode = true;
              }
            });
            if (isValid) {
              for (var item in response) {
                list.add(ShippingMethod.fromJson(item));
              }
            }
          }
        }
      }
      return list;
    } catch (e) {
      throw e;
    }
  }
```

**Comment by EmilianH** [comment]
shipment work but cost calculator not working

**Comment by minhcasi** [comment]
http://mamapp.com.ar/ is still blocked access from the country outside, try to enable so we can debug from here - thanks

**Comment by EmilianH** [comment]
I already fixed that issue, but you are closeing my others issues, are not duplicated!!! Please help me with #1387

**Comment by minhcasi** [comment]
@EmilianH - I mean duplicate Thread - kindly create your all feedback in this one ticket support thread, that will help us have better support on your all issues and check one config without extraction to restart the process again when starting investigate a new ticket, hope you can understand - thank you!

**Comment by minhcasi** [comment]
1. The login is permanent and does not automatically go to the main menu after creating a new account.
It only says a welcome message, but remains on the same screen. Which shouldn't work like this. When someone creates an account they would have to show the main screen after creating the account.
---

2. being logged in, every time I start again the app still shows the log in screen.
If the app already knows that I'm logged in, it shouldn't show me the login screen when I start the app, since I'm already logged in.
"isrequieredlogin" is true since I need it that way.
---

3. i change all the com.inpireui.fluxstore from the app, and chaged my DIR, i tried flutter clean, deleting app from emulator etc, but never appear Welcome Screen
thanks

**Comment by minhcasi** [comment]
the team have fixed these 3 issues on latest v1.5.8

**Comment by EmilianH** [comment]
1) The login is permanent and does not automatically go to the main menu after creating a new account. It only says a welcome message, but remains on the same screen. Which shouldn't work like this. When someone creates an account they would have to show the main screen after creating the account. 
![loginbug](https://user-images.githubusercontent.com/57189819/68856789-1d1abb00-06c0-11ea-85b6-94dc6e0fdf45.png)


2)being logged in, every time I start again the app still shows the log in screen.
If the app already knows that I'm logged in, it shouldn't show me the login screen when I start the app, since I'm already logged in.
"isrequieredlogin" is true since I need it that way.

3)i change all the com.inpireui.fluxstore from the app, and chaged my DIR, i tried flutter clean, deleting app from emulator etc, but never appear Welcome Screen
thanks

waiting solution thanks

**Comment by minhcasi** [comment]
@EmilianH - pls help to try with the latest v1.5.8, the team report that fixed these issue - thank you!

**Comment by EmilianH** [comment]
I will try thanks Minh
