### ISSUE TITLE
[fluxstore 1.5.7] - google maps api not working 

### ISSUE THREAD

**Issue by EmilianH** [inspireui/support#1325]
I set the API as the tutorial says, but in Google Cloud, ask for a SHA-1 code from where do I get it?
please help!!! (configured in config.dart and androidmanifiest.xml)

[55640809-fluxstore-woocommerce-flutter-ecommerce-full-app-license (1).pdf](https://github.com/inspireui/support/files/3801165/55640809-fluxstore-woocommerce-flutter-ecommerce-full-app-license.1.pdf)
![mapserror2](https://user-images.githubusercontent.com/57189819/68079283-2e152380-fdc6-11e9-9aa9-9a842d240454.jpg)
![mapserror](https://user-images.githubusercontent.com/57189819/68079248-d2e33100-fdc5-11e9-827c-2abfe74e1537.jpg)
[common.zip](https://github.com/inspireui/support/files/3801157/common.zip)

**Comment by spss20** [comment]
follow https://stackoverflow.com/questions/27609442/how-to-get-the-sha-1-fingerprint-certificate-in-android-studio-for-debug-mode  and you can get sha1 key

**Comment by minhcasi** [comment]
@EmilianH  - there is the guideline on that page as well - https://tppr.me/aeOhg - you can also open for ALL access to make sure the API works, then update restrict rule for the API later - thanks

**Comment by EmilianH** [comment]
i put the sha-1 number and not working,

**Comment by kwesifokuo** [comment]
Go to Google Cloud Console and ENABLE the GEOCODING API in addition to the MAPS API and SDK as well as PLACES API. It took me a while to figure that out. Hope it helps. After I enabled GEOCODING, the places started showing up.

**Comment by wolvsky** [comment]
All Google Maps services are enabled.
Search autocomplete and nearbysearch work, but the map does not show.
I use this key in another app made in ionic and it works.
