### ISSUE TITLE
[MStorePro] - I can't build Apk

### ISSUE THREAD

**Issue by juniortimeline** [inspireui/support#1326]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. I can't build APK and this is the error

2. http://prntscr.com/prva29

3. https://codecanyon.net/comments/23094284

3. Config files (optional)

**Comment by minhcasi** [comment]
@juniortimeline  - could you try to run the app with the Cebuilder to see it can be fixed - https://github.com/inspireui/cebuilder/releases - thank you!

**Comment by juniortimeline** [comment]
> @juniortimeline - could you try to run the app with the Cebuilder to see it can be fixed - https://github.com/inspireui/cebuilder/releases - thank you!
> 
> > <img alt="" width="48" src="https://avatars1.githubusercontent.com/u/29778334?s=400&amp;v=4"><img alt="" height="14" src="https://camo.githubusercontent.com/4908d9947135e4536ef61d61512ee575f869bf6f/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e2e69636f"> GitHub**[inspireui/cebuilder](https://github.com/inspireui/cebuilder)**The assistant tool for build the React native app quickly 🚀🚀🚀 - inspireui/cebuilder

Thanks for response. Since in the beginning ceBuilder is not gonna help with me about this error http://prntscr.com/ps7sd2 after I run the Run Android. ceBuilder is the number one makes me interest that's why I get this product and everything is already happened. Not Working well and until now since I get this MStore Pro I never experience to have an apk build.

For the second chance I learn to do manual and this is related topic https://github.com/inspireui/support/issues/1298#issue-513869006

All I need and important to do is how I build my sign APK and that's the error I found.

Thanks and Regards

**Comment by concuacon** [comment]
Hello @juniortimeline you can check this link to generate apk: https://dev.to/zilurrane/generate-release-mode-apk-for-react-native-project-to-publish-on-playstore-5f78

**Comment by juniortimeline** [comment]
> > * Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> > * Try to explain your all problems in one ticket, instead of creating multi tickets
> > * After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> > * IMPORTANT: We will close the ticket if you could not prove as our customer.
> 
> 1. I can't build APK and this is the error
> 2. http://prntscr.com/prva29
> 3. https://codecanyon.net/comments/23094284
> 4. Config files (optional)

Guys, I'm asking a help for this problem while I build my APK. I'm not asking how I build APK. Thanks.

**Comment by concuacon** [comment]
@juniortimeline 
I showed you how to do it yourself instead of using ceBuilder, why don't you follow the steps I showed you? Or do the steps I show you don't work? Before you want to do application testing, you must be connected to the device,

**Comment by juniortimeline** [comment]
@concuacon kindly please understand that the error is after I run the cd android && ./gradlew assembleRelease. This discussion is about building apk not to develop the app. I'm not using my site here I'm going to use the demo.

Once again ..

After I hit the cd android && ./gradlew assembleRelease  this is the error http://prntscr.com/prva29

Thanks

**Comment by juniortimeline** [comment]
Problem solve. I just disable hermes and now I build my APK successfully.

@minhcasi @concuacon @luyx2412 @vumanhsn97

**Comment by minhcasi** [comment]
Oh, i see - thank you for sharing 

Do you mean disable this herm option - https://facebook.github.io/react-native/docs/hermes/ ?

**Comment by juniortimeline** [comment]
@minhcasi  yes after I disable the hermes I build the apk without any error.
