### ISSUE TITLE
[MStore Magento] - Version Issue  (Reopen for issue #1246)

### ISSUE THREAD

**Issue by wedanbusiness** [inspireui/support#1329]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

My issue:
Same issue with issue# [1246](https://github.com/inspireui/support/issues/1246). Based from the reply of [minhtruong315](https://github.com/minhtruong315): _"I upgraded expo to version 0.35. It's available on next some days"_, may we know when can we have the upgraded version? Also, please don't close the issue while it was not resolved yet.

Screenshots
https://ibb.co/7bWTYNX

My screenshot of the purchase product or my comment:
https://ibb.co/vPhL2rP

**Comment by minhcasi** [comment]
@wedanbusiness - the MStore Magento is available for download and compatible with Expo 0.35 - pls help to check

**Comment by wedanbusiness** [comment]
Thank you @minhcasi. We'll check on this.

**Comment by minhcasi** [comment]
Thank you, pls let us know if you have any further issues by creating new ticket - thank you!
