### ISSUE TITLE
[CeBuilder] when i going to customization i got error (can not get cetegory and tag)

### ISSUE THREAD

**Issue by upandya538** [inspireui/support#133]
**Mandatory Info (please complete the following information):**
 MStore Pro - Complete React Native template for e-commerce	
MStore Pro - Complete React Native template for e-commerce
Regular License
Purchase code: e270ed9b-9841-4ab4-9ca4-dce01ecdd14e

**Describe the issues**
can not get category and tag error cebuilder 

**Screenshots**
![untitled](https://user-images.githubusercontent.com/46165825/50451764-08282280-095c-11e9-8320-8aeb3101f6f8.png)
![untitled1](https://user-images.githubusercontent.com/46165825/50451765-09f1e600-095c-11e9-9d48-2f08745dbb49.png)

**Additional context**
Add any other detail logs about the problem here.

**Comment by minhcasi** [comment]
Hi, could you help to share the config from Setup page here (the website and consumekey..)

**Comment by minhcasi** [comment]
Hi, could you help to check the latest v.0.20, please note it will only work on Expo version and all the plugins is install from the Wordpress site ( https://docs.mstore.io/basic-app-setting#wordpress-plugins-install ) we will update the document for this change – thank you!

**Comment by Lubrig2** [comment]
If your url is https, change it to http.
