### ISSUE TITLE
[MStore Magento] - Errors After Version Upgrade from 32.0.6 to 35.0.0

### ISSUE THREAD

**Issue by wedanbusiness** [inspireui/support#1339]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

My issue:
There were a lot of critical and medium issues after your upgrade of expo from 32.0.6 to 35.0.0 that causes the performance and functionality of the application. Screenshots were just few samples of it. Requesting for the fixes on the dependencies.

Screenshots
https://ibb.co/r4qG89T
https://ibb.co/3yqzkhB
https://ibb.co/sR3qLss
https://ibb.co/dgk28Z4
https://ibb.co/TR7V2GP

My screenshot of the purchase product or my comment:
https://ibb.co/vPhL2rP

**Comment by minhtruong315** [comment]
@wedanbusiness Did you checkout latest source code on codecanyon?

**Comment by wedanbusiness** [comment]
Yes, this is the latest version I downloaded after your updates from 32 to 35.

**Comment by minhtruong315** [comment]
It's only warning. You can ignore it

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
