### ISSUE TITLE
[FluxStoret] - 

### ISSUE THREAD

**Issue by CharanKumar4** [inspireui/support#1340]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue
I am trying to change banner and category in Homepage. But it is not working. Even I put name and category id. Everything is working fine but just Homepage is not working

2. Screenshots
![support2](https://user-images.githubusercontent.com/57438790/68289634-4deb6680-00a8-11ea-8b2e-5486b86c8d07.jpg)
![support3](https://user-images.githubusercontent.com/57438790/68289647-52b01a80-00a8-11ea-9347-e0853886411b.PNG)
![support4](https://user-images.githubusercontent.com/57438790/68289660-5774ce80-00a8-11ea-89dd-dcbca2bcf5a4.PNG)
![support5](https://user-images.githubusercontent.com/57438790/68289714-75423380-00a8-11ea-86a7-50932402ec94.jpg)

3. My screenshot of the purchase product or my comment:

![support](https://user-images.githubusercontent.com/57438790/68289043-44adca00-00a7-11ea-9eec-cad67082af36.PNG)

3. Config files (optional)

[common.zip](https://github.com/inspireui/support/files/3813867/common.zip)

**Comment by CharanKumar4** [comment]
The following assertion was thrown during a scheduler callback:
type 'List<dynamic>' is not a subtype of type 'List<Product>'

**Comment by minhtruong315** [comment]
are there products with category_id 80?

**Comment by CharanKumar4** [comment]
https://ibooks.pk/product-category/college-books/

**Comment by CharanKumar4** [comment]
![Screenshot_2019-11-07-12-34-46-62](https://user-images.githubusercontent.com/57438790/68370313-01626280-015e-11ea-83cb-2bdc41d15d2e.png)
![Screenshot_2019-11-07-12-34-52-13](https://user-images.githubusercontent.com/57438790/68370325-06bfad00-015e-11ea-95df-b43c2a889872.png)
![Screenshot_2019-11-07-12-36-12-12](https://user-images.githubusercontent.com/57438790/68370332-0b846100-015e-11ea-9852-e7059beea353.png)

**Comment by CharanKumar4** [comment]
I try to change banner pic but that doesnt work for me also womens and  mans collection names cannot be changed no products are listed also no homepage layout can be edited

**Comment by CharanKumar4** [comment]
If can come in teamviewer that will be to solve the problem

**Comment by CharanKumar4** [comment]
thanks and how to change this category image
![caterogy](https://user-images.githubusercontent.com/57438790/68474106-65605600-0246-11ea-91ff-0953c50edd82.jpg)

**Comment by minhtruong315** [comment]
You can change it in config.json file
