### ISSUE TITLE
listapp expo

### ISSUE THREAD

**Issue by derinweb** [inspireui/support#1342]
Dear Sir/Madam,

We need installation service for the list app for our listify theme wordpress website, how could you help us please.

Regards,

Derin W. Salih

**Comment by minhcasi** [comment]
Hi Derin, sorry we are not supporting for installing service for the ListApp at this time due to full of capacity, we will contact you when the team is available - thank you!

**Comment by derinweb** [comment]
Hi,

Thank you for your message, we installed every thing as it's described inside the document, plugins and rest api are working correctly, and we install all necessary platforms and application, but we have just an issue, when we want to start the project inside expo, couldn't connect to the emulator to see the app, if you could help us to fix this issue.

Regards,

Derin

**Comment by derinweb** [comment]
Hi,

When I click on (start setup) in customization tab inside CeBuilder after loading the package it will show me this error message below:

[2/4] Fetching packages...
error Couldn't find match for "e7646f0680d509b590b839e567c217590451505b" in "refs/heads/1.0.x,refs/heads/1.1.x,refs/heads/2.0.x,refs/heads/brodybits-introduce-eslint,refs/heads/master,refs/tags/1.0.0,refs/tags/1.1.0,refs/tags/2.0.0,refs/tags/rel/1.0.0,refs/tags/rel/1.1.0,refs/tags/rel/2.0.0" for "https://github.com/apache/cordova-node-xcode.git".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.


how could you help me please to fix this

Thank you

**Comment by derinweb** [comment]
Hi,

I have send the error and still not have any reply please...

**Comment by minhcasi** [comment]
@derinweb - could you try to reinstall the nodejs - 10.x - https://nodejs.org/en/  - there is known issues with the 12.x that cause broken build

I've reopened ticket and assign the team to follow up the issue - thank you!
