### ISSUE TITLE
[FLUXSTORE] - Affiliate link on addtocart button in product page 

### ISSUE THREAD

**Issue by nicolalessi** [inspireui/support#1344]
Hi, I have a problem with FLUXSTORE PRO. I want to use the add to cart button on product detail to open the affiliate link on my product but at the moment, when I click, the product is added to cart. 
I saw on product_variant.dart this piece of code:

void addToCart() {
    final cartModel =Provider.of<CartModel>(context);
    final isExternal =
        product.affiliateUrl != null && product.affiliateUrl.isNotEmpty;
    if (isExternal) {
      Navigator.push(
          context,
          MaterialPageRoute(
              builder: (context) => WebView(
                    url: product.affiliateUrl,
                    title: product.name,
                  )));
      return;
    }

    cartModel.addProductToCart(
        product: product, quantity: quantity, variation: productVariation);
  }

and I don't know why the IF statement don't work at the moment...any advice? 
---------
![WhatsApp Image 2019-11-04 at 13 03 16 (1)](https://user-images.githubusercontent.com/25532101/68341155-261bf300-00e8-11ea-82b2-6f1a2903a414.jpeg)

**Comment by minhcasi** [comment]
@nicolalessi - pls update the product type as the Affiliate link and fill in the product URL to navigate through - https://tppr.me/SadN5

**Comment by nicolalessi** [comment]
Wait, I did it but it doesn't work
