### ISSUE TITLE
[Mstore MV] - 

### ISSUE THREAD

**Issue by simdanonline** [inspireui/support#1345]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue
App build successfully but error when open
2. Screenshots
![Screenshot_20191107-044232_Simdan mall](https://user-images.githubusercontent.com/53178201/68374185-b1c36d00-0144-11ea-81b2-f9debf39e75d.jpg)
![Screenshot_20191107-083517_Simdan mall](https://user-images.githubusercontent.com/53178201/68374206-ba1ba800-0144-11ea-8a2d-e3423df3cd1f.jpg)

3. My screenshot of the purchase product or my comment:

![mstoreberror](https://user-images.githubusercontent.com/53178201/68374279-e0d9de80-0144-11ea-840c-9bc4b511859c.png)

3. Config files (optional)

**Comment by concuacon** [comment]
Hello, @simdanonline try run: 
- npm install -g expo-cli
- rm -rf node_modules/ && yarn && yarn start -c (macOs)
- rm -rf node_modules/ ; yarn ; yarn start -c (window)

**Comment by minhcasi** [comment]
@sa
