### ISSUE TITLE
[beonews pro] - onesignal notifications

### ISSUE THREAD

**Issue by paulica40** [inspireui/support#1346]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue

onesignal issue:

I added this code in functions.php but onesignal doesn't redirect to post.

function onesignal_send_notification_filter($fields, $new_status, $old_status, $post)
{
$fields['isAndroid'] = true;
$fields['isIos'] = true;
$fields['isAnyWeb'] = false;
$fields['isChrome'] = false;
$fields['data'] = array(
"id" => $post->ID,
);
/* Unset the URL to prevent opening the browser when the notification is clicked */
unset($fields['url']);
return $fields;
}
add_filter('onesignal_send_notification', 'onesignal_send_notification_filter', 10, 4);

Unfortunetly, the post is not opening, only the app at home screen. I did all the checking, not sure why?

this is from debug console...the id of the post is coming data id:12265 

Notification received:  {shown: true, payload: {…}, isAppInFocus: true, displayType: 2}
blob:http://localhost:8081/09042be7-e6e1-450a-a2fa-5a68f15cfc8d:110792 Message:  trst5
blob:http://localhost:8081/09042be7-e6e1-450a-a2fa-5a68f15cfc8d:110793 Data:  {id: 12265}
blob:http://localhost:8081/09042be7-e6e1-450a-a2fa-5a68f15cfc8d:110794 isActive:  true
blob:http://localhost:8081/09042be7-e6e1-450a-a2fa-5a68f15cfc8d:110795 openResult:  {notification: {…}, action: {…}}

something to change in here, maybe?:

handleDeepLink = (openResult) => {
    const data = openResult.notification.payload.additionalData
    this.props.setInitialNotification(openResult)
    if (data && data.id) {
      this.props.fetchPostById(data.id).then((post) => {
        this.goToScreen('post', { post })
      })
    } else {
      console.log('notification is invalid data')
    }

purchase code:
029a5bbd-3911-40d1-893f-f6797bc53504

**Comment by paulica40** [comment]
this is from debug console...the id of the post is coming data id:12265 


Notification received:  {shown: true, payload: {…}, isAppInFocus: true, displayType: 2}
blob:http://localhost:8081/09042be7-e6e1-450a-a2fa-5a68f15cfc8d:110792 Message:  trst5
blob:http://localhost:8081/09042be7-e6e1-450a-a2fa-5a68f15cfc8d:110793 Data:  {id: 12265}
blob:http://localhost:8081/09042be7-e6e1-450a-a2fa-5a68f15cfc8d:110794 isActive:  true
blob:http://localhost:8081/09042be7-e6e1-450a-a2fa-5a68f15cfc8d:110795 openResult:  {notification: {…}, action: {…}}


something to change in here, maybe?:

handleDeepLink = (openResult) => {
    const data = openResult.notification.payload.additionalData
    this.props.setInitialNotification(openResult)
    if (data && data.id) {
      this.props.fetchPostById(data.id).then((post) => {
        this.goToScreen('postNewsContent', { post })
      })
    } else {
      console.log('notification is invalid data')
    }

**Comment by paulica40** [comment]
All right, i have figure it out, the code of handleDeepLink in RootRouter.js should be like this

handleDeepLink = (openResult) => {
    const data = openResult.notification.payload.additionalData
    this.props.setInitialNotification(openResult)
    if (data && data.id) {
      this.props.fetchPostById(data.id).then((post) => {
        this.goToScreen('postDetail', { post })
      })
    } else {
      console.log('notification is invalid data')
    }
  }

**Comment by concuacon** [comment]
@paulica40 Congratulations so I will close this issue
