### ISSUE TITLE
[Mstore Pro] - Generate Error APK in Android Studio

### ISSUE THREAD

**Issue by saeidAalizade** [inspireui/support#1349]
1. I can't see the output. 
Error : Process 'command' 'cmd' finished with non-zero exit value 1
Please Help me

2. Screenshots:
![photo_2019-11-09_17-23-37](https://user-images.githubusercontent.com/41091634/68529613-af643d00-0315-11ea-8057-f8440c43fbe8.jpg)

3. My screenshot of the purchase product or my comment:
153bb1ff-3f3e-41cd-a219-da061397aef5

**Comment by minhcasi** [comment]
Hi, could you take the whole screenshot error as this message did not show the root cause of the issue?

**Comment by saeidAalizade** [comment]
Hi 
error me:
![image_2019-11-11_11-41-51](https://user-images.githubusercontent.com/41091634/68975806-78a49000-0809-11ea-9c7d-939237281b17.png)
![image_2019-11-11_11-42-10](https://user-images.githubusercontent.com/41091634/68975807-78a49000-0809-11ea-95c6-df1003d9d87b.png)
![image_2019-11-11_11-42-19](https://user-images.githubusercontent.com/41091634/68975808-78a49000-0809-11ea-8207-8ca03a6eb22d.png)
![image_2019-11-11_11-42-33](https://user-images.githubusercontent.com/41091634/68975810-78a49000-0809-11ea-9782-8eaf2ada99a0.png)
![image_2019-11-11_11-42-43](https://user-images.githubusercontent.com/41091634/68975811-793d2680-0809-11ea-8cd6-30e7edd6d6f2.png)

**Comment by saeidAalizade** [comment]
Please Help Me! 
Thank You
