### ISSUE TITLE
[MStore MultiVendor] how to setup onesignal notification

### ISSUE THREAD

**Issue by alaradi2006** [inspireui/support#135]
**Mandatory Info (please complete the following information):**
 - Product: [e.g. MStore, ListApp]
 - Your Purchased Code: [get from https://codecanyon.net/downloads]
(we may not reply if you are not our customer)

**Describe the issues**

**Screenshots**

**Additional context**
Add any other detail logs about the problem here.
no clear document how to setup onesginal notification

**Comment by minhcasi** [comment]
Noted for update the video guide, it will be similar with - https://www.youtube.com/watch?v=6KRh7fusdIc

**Comment by alaradi2006** [comment]
can you give me more clear guide as i dont understand the video

**Comment by alaradi2006** [comment]
yes please update it as its not clear not a real doc guide

**Comment by thangvo9x** [comment]
Hi. You must have only run "yarn detach", Almost done.

**Comment by alaradi2006** [comment]
Do I have to put any files with original files or just run yarn detach in original files and that’s all

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by ZamanGoraya** [comment]
why npm detach and yarn detach is not running ...? it always show error

can you help me...?]
