### ISSUE TITLE
Fluxstore Multi Vendor - Products not loading

### ISSUE THREAD

**Issue by darana07** [inspireui/support#1350]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. I have done all the steps in the guide to integrate my woocomerce API but the app does not show the products. The app does not show any errors and the android studio console shows me these two messages 
I / flutter (23773): Error: Exception: Invalid signature - the signature provided does not match.
W / FA (23773): setCurrentScreen cannot be called with the same class and name

2. 
![ss1](https://user-images.githubusercontent.com/19784904/68532950-567eaf80-02e9-11ea-9527-e6b541f29a98.jpeg)
![ss2](https://user-images.githubusercontent.com/19784904/68532953-5aaacd00-02e9-11ea-8952-41fdb14ad8d5.jpeg)

3. 
![image](https://user-images.githubusercontent.com/19784904/68532960-86c64e00-02e9-11ea-92e6-d58904a34eb1.png)

3.

**Comment by daav7713** [comment]
Ive already solve it

**Comment by minhtruong315** [comment]
Thanks. let us know if you have any issues

**Comment by daav7713** [comment]
I have an open issue #1367 and no response
