### ISSUE TITLE
[Fluxstore] - Update user account  

### ISSUE THREAD

**Issue by humazed** [inspireui/support#1351]
I know there is no page to edit account and was trying to create it myself but I noticed you are using mstore_user to create the user

is there is a technical reason why you didn't include such an important feature? and are you planning on adding it?

if not can you tell me the api for it and will add it myself.
I was planning on using [JWT Authentication for WP REST API](https://wordpress.org/plugins/jwt-authentication-for-wp-rest-api/) is there a downside of using it?

**Comment by minhcasi** [comment]
@humazed - thank you for the feedback, i've noted as the Feature Request, we could update this important on the next 1.6 - very best!

**Comment by humazed** [comment]
Any Eta when 1.6. Will be out?

**Comment by minhcasi** [comment]
@humazed - could be in 1-2 weeks, we have just released latest 1.5.8 - thanks

**Comment by minhcasi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update user account](https://trello.com/c/4puUGOfc/4-update-user-account)

**Comment by minhcasi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update user account](https://trello.com/c/4puUGOfc/4-update-user-account)

**Comment by minhcasi** [comment]
we are closing the ticket and move this ticket 'request feature' to our Trello board for easier to keep track, review, and update, also keep a status update  - thank you!
