### ISSUE TITLE
listpp expo

### ISSUE THREAD

**Issue by derinweb** [inspireui/support#1354]
Hi,

When I click on (start setup) in customization tab inside CeBuilder after loading the package it will show me this error message below:

[2/4] Fetching packages...
error Couldn't find match for "e7646f0680d509b590b839e567c217590451505b" in "refs/heads/1.0.x,refs/heads/1.1.x,refs/heads/2.0.x,refs/heads/brodybits-introduce-eslint,refs/heads/master,refs/tags/1.0.0,refs/tags/1.1.0,refs/tags/2.0.0,refs/tags/rel/1.0.0,refs/tags/rel/1.1.0,refs/tags/rel/2.0.0" for "https://github.com/apache/cordova-node-xcode.git".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

how could you help me please to fix this

**Comment by minhcasi** [comment]
@derinweb  - could you show your proof of purchase by taking the screenshot from http://codecayon.net/downloads - thanks
