### ISSUE TITLE
[MStore MV] - Problem image picker(?)

### ISSUE THREAD

**Issue by santihabib** [inspireui/support#1355]
Hi
![65076487-7770f700-d96f-11e9-8cd3-ab36f8b04aba](https://user-images.githubusercontent.com/55243343/68544232-e5e69a00-039f-11ea-934d-f59132141cc0.png)
! I am testing the update. When I upload a product, if I press the photo upload button it does nothing. It doesn't open the gallery or anything. I'm testing it as it came, without touching the config file or anything!

**Comment by concuacon** [comment]
Hello, @santihabib I fixed this issue, I will update next version, but if you want the update now, you can give me your email, I send the new source to you. Thanks

**Comment by santihabib** [comment]
@concuacon  yes ples! send me!! shvirtual@gmail.com

**Comment by concuacon** [comment]
I sent it to you via https://wetransfer.com/ Please check your mail.

**Comment by hassanwe** [comment]
@concuacon can you please send it to me?

nusal@me.com
