### ISSUE TITLE
[FluxNews] - Unable to sign-in or register

### ISSUE THREAD

**Issue by TheCellMC** [inspireui/support#1356]
1. My issue
I am unable to sign-in or register using the app. I am running it on an iPhone X running its 13.2, compiled with Xcode.
I installed all the plugins on my wordpress server and set the url in the app's settings. However, every-time I attempt to sign-in, I get this error on my device (see screenshot below).

2. Screenshots
![IMG_4611](https://user-images.githubusercontent.com/12169936/68544616-581da580-03c5-11ea-81b9-69aaccada9dd.PNG)

3. My screenshot of the purchase product or my comment:

![Screenshot 2019-11-10 at 14 25 03](https://user-images.githubusercontent.com/12169936/68544679-fc9fe780-03c5-11ea-842c-51d40a629941.png)

**Comment by minhcasi** [comment]
@TheCellMC - could i confirm if you are using latest Fluxnews 1.1.0 ?

**Comment by TheCellMC** [comment]
I am using the version which I downloaded yesterday from CodeCanyon, version 1.1.0.

**Comment by TheCellMC** [comment]
I did not set up Firebase yet because I do not have an apple developer account. Could that be the root of the issue?

**Comment by minhcasi** [comment]
@TheCellMC - this is could be the problem if you have not setup the Firebase account as the Fluxnews also integrate with Firebase for authentication, pls try to create a new free account and integrate with your app

**Comment by TheCellMC** [comment]
Sorry guys but I still can't get signing-in to work.

**Comment by TheCellMC** [comment]
This is the error I get in my console:
```
I/flutter (21817): login err NoSuchMethodError: The method 'login' was called on null.
I/flutter (21817): Receiver: null
I/flutter (21817): Tried calling: login(password: "xx", username: "xx")
```

**Comment by TheCellMC** [comment]
After some troubleshooting, it appears as if the error is caught from the lib/models/user.dart file, specifically this section:

```
  void login({username, password, Function success, Function fail}) async {
    try {
      loading = true;
      notifyListeners();

      user = await _service.login(
        username: username,
        password: password,
      );

      loggedIn = true;
      saveUser(user);
      success(user);
      loading = false;
      notifyListeners();
    } catch (err) {
      loading = false;
      fail(err.toString());
      print('login err $err');
      print('error in user.dart');
      notifyListeners();
    }
  }
```

I think this line might be where the code fails:

```
      user = await _service.login(
        username: username,
        password: password,
      );
```
