### ISSUE TITLE
[FluxNews] - Pod setup

### ISSUE THREAD

**Issue by socialwarespace** [inspireui/support#1357]
Showing Recent Messages

Build target Runner of project Runner with configuration Debug
error: /Users/socialware/Downloads/fluxnew.1.1.0/source/ios/Flutter/Debug.xcconfig:1: could not find included file 'Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig' in search paths (in target 'Runner' from project 'Runner')
error: /Users/socialware/Downloads/fluxnew.1.1.0/source/ios/Flutter/Debug.xcconfig:1: could not find included file 'Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig' in search paths (in target 'Runner' from project 'Runner')
error: /Users/socialware/Downloads/fluxnew.1.1.0/source/ios/Flutter/Debug.xcconfig:1: could not find included file 'Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig' in search paths (in target 'Runner' from project 'Runner')
error: /Users/socialware/Downloads/fluxnew.1.1.0/source/ios/Flutter/Debug.xcconfig:1: could not find included file 'Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig' in search paths (in target 'Runner' from project 'Runner')
error: /Users/socialware/Downloads/fluxnew.1.1.0/source/ios/Flutter/Debug.xcconfig:1: could not find included file 'Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig' in search paths (in target 'Runner' from project 'Runner')
error: /Users/socialware/Downloads/fluxnew.1.1.0/source/ios/Flutter/Debug.xcconfig:1: could not find included file 'Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig' in search paths (in target 'Runner' from project 'Runner')

running Pod setup

**Comment by minhcasi** [comment]
@socialwarespace - could you help to show your proof of purchase by taking the screenshot from http://codecayon.net/downloads - thank you!

**Comment by socialwarespace** [comment]
@minhcasi https://ibb.co/q9cLYHV

**Comment by minhcasi** [comment]
@socialwarespace - could you try this solution

Go to ios folder, delete the Podfile.lock and Pods folders, then try to run: pod install

Then open Android Studio to build the app again
