### ISSUE TITLE
[Fluxstore] - Register API call returning error 409 

### ISSUE THREAD

**Issue by spinner2009** [inspireui/support#1360]
1. My issue

I have installed MStore API 1.4.7 (latest) as well as JSON API version 2.0 (latest) and tried the register functionality from the app. I can see that both plugins are enabled and the MStoreUser controller is visible in JSON API and active. However when I make a call to the register API endpoint by using a URL such as https://website/api/get_nonce/?controller=mstore_user&method=register I get a 409 error back. Can you advise on the cause? 

I have also tried to install the JSON API plugin that comes in the zip file from codecanyon.net. In that case I get JSON API version 1.1 and MStore API 1.3.6 but the result is the same.

Making API calls to WooCommerce or other Wordpress endpoints works.

2. Screenshots
See attached screenshots with the error code and error message.

3. My screenshot of the purchase product or my comment:
This is the link from Code Canyon https://codecanyon.net/item/fluxstore-woocommerce-flutter-ecommerce-full-app/24050041/support

3. Config files (optional)
![error_409_more_details](https://user-images.githubusercontent.com/48594963/68551942-17984900-0412-11ea-995d-6addf046a66a.jpg)
![error_409](https://user-images.githubusercontent.com/48594963/68551944-1cf59380-0412-11ea-99e5-2caf1434a1d6.jpg)

**Comment by spinner2009** [comment]
One more point. As you can see from my code I have added a header: Map<String,String> headers = {'Content-Type':'application/x-www-form-urlencoded'}; Without it I get another 409 error from Dart saying it can only process body fields that are application/x-www-form-urlencoded.

**Comment by minhtruong315** [comment]
can you send me config.dart file and admin account via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/1360

**Comment by minhcasi** [comment]
there is not any response from this ticket, pls also try to update latest 1.5.8 to fix the issues, let us know if you have further issues by open new ticket - thanks
