### ISSUE TITLE
[MStore Pro] - assembleRelease problem

### ISSUE THREAD

**Issue by 007asom** [inspireui/support#1361]
Hello,

1. My issue
FAILURE: Build failed with an exception

2. Screenshots

3. My screenshot of the purchase product or my comment:
https://ibb.co/PNBWpYy

4. Config files (optional)

regarding the issue in the previous issue.
https://github.com/inspireui/support/issues/1232 

now I'm using fresh code 3.9.6

still, face the same issue. from Windows PowerShell 

`PS D:\Projects\MStorePro\android> ./gradlew assembleRelease                                                                           
> Configure project :react-native-admob
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed soon. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

> Configure project :react-native-webview
:react-native-webview:reactNativeAndroidRoot D:\Projects\MStorePro\node_modules\react-native\android

> Task :react-native-gesture-handler:compileReleaseJavaWithJavac
Note: D:\Projects\MStorePro\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerButtonViewManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :react-native-localization:compileReleaseJavaWithJavac
Note: D:\Projects\MStorePro\node_modules\react-native-localization\android\src\main\java\com\babisoft\ReactNativeLocalization\ReactNativeLocalization.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :react-native-facebook-account-kit:compileReleaseJavaWithJavac
Note: D:\Projects\MStorePro\node_modules\react-native-facebook-account-kit\android\src\main\java\io\underscope\react\fbak\RNAccountKitModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :react-native-fbsdk:compileReleaseJavaWithJavac
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
info Writing bundle output to:, D:\Projects\MStorePro\android\app\build\generated\assets\react\release\index.android.bundle
info Writing sourcemap output to:, D:\Projects\MStorePro\android\app\build\intermediates\sourcemaps\react\release\index.android.bundle.packager.maple with -Xlint:unchecked for details.
info Done writing bundle output
info Done writing sourcemap outputpileReleaseJavaWithJavac
info Copying 112 asset files
info Done copying assets

> Task :app:bundleReleaseJsAndAssets FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:bundleReleaseJsAndAssets'.
> A problem occurred starting process 'command '..\..\node_modules\hermesvm\win64-bin\hermes''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.transform cache was reset.
Loading dependency graph, done.
* Get more help at https://help.gradle.org
> IDLE
BUILD FAILED in 4m 4s
159 actionable tasks: 157 executed, 2 up-to-date`

from the android studio when trying to generate signed bundle / APK

Execute doLast {} action | 67 ms

`org.gradle.process.internal.ExecException: A problem occurred starting process 'command '..\..\node_modules\hermesvm\win64-bin\hermes''
	at org.gradle.process.internal.DefaultExecHandle.execExceptionFor(DefaultExecHandle.java:232)
	at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:209)
	at org.gradle.process.internal.DefaultExecHandle.failed(DefaultExecHandle.java:356)
	at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:86)
	at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:42)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
Caused by: net.rubygrapefruit.platform.NativeException: Could not start '..\..\node_modules\hermesvm\win64-bin\hermes'
	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:27)
	at net.rubygrapefruit.platform.internal.WindowsProcessLauncher.start(WindowsProcessLauncher.java:22)
	at net.rubygrapefruit.platform.internal.WrapperProcessLauncher.start(WrapperProcessLauncher.java:36)
	at org.gradle.process.internal.ExecHandleRunner.startProcess(ExecHandleRunner.java:97)
	at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:70)
	... 7 more
Caused by: java.io.IOException: Cannot run program "..\..\node_modules\hermesvm\win64-bin\hermes" (in directory "D:\Projects\arnnob3960\android\app"): CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:25)
	... 11 more
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 12 more

`

**Comment by concuacon** [comment]
Hello, @007asom Please follow this link, I think it will help you fix this issue.
https://facebook.github.io/react-native/docs/hermes

**Comment by 007asom** [comment]
thank you 
I fix it by following this:
https://github.com/facebook/react-native/issues/25599#issuecomment-532726715

**Comment by 007asom** [comment]
the crash only with Release version

**Comment by concuacon** [comment]
@007asom I'm checking it, I will give you the solution as soon as I find it

**Comment by concuacon** [comment]
@007asom Can you give me a log on Android Studio when the app crashes? I check not to show this case. Thank you.

**Comment by 007asom** [comment]
Hi
when I open it from the android studio, it shows:
`
FAILURE: Build failed with an exception.

* Where:
Script 'D:\Projects\myApp\node_modules\@react-native-community\cli-platform-android\native_modules.gradle' line: 191

* What went wrong:
A problem occurred evaluating settings 'mstore'.
> Unable to determine the current character, it is not a string, number, array, or object
  
  The current character read is 'E' with an int value of 69
  Unable to determine the current character, it is not a string, number, array, or object
  line number 1
  index number 0
  Error: EPERM: operation not permitted, scandir 'D:/Projects/myApp/android/app/build/intermediates/signing_config/debug/out/signing-config.json'    at Object.readdirSync (fs.js:790:3)    at GlobSync._readdir (D:\Projects\myApp\node_modules\glob\sync.js:288:41)    at GlobSync._readdirInGlobStar (D:\Projects\myApp\node_modules\glob\sync.js:267:20)    at GlobSync._readdir (D:\Projects\myApp\node_modules\glob\sync.js:276:17)    at GlobSync._processReaddir (D:\Projects\myApp\node_modules\glob\sync.js:137:22)    at GlobSync._process (D:\Projects\myApp\node_modules\glob\sync.js:132:10)    at GlobSync._processGlobStar (D:\Projects\myApp\node_modules\glob\sync.js:380:10)    at GlobSync._process (D:\Projects\myApp\node_modules\glob\sync.js:130:10)    at GlobSync._processGlobStar (D:\Projects\myApp\node_modules\glob\sync.js:383:10)    at GlobSync._process (D:\Projects\myApp\node_modules\glob\sync.js:130:10)
  ^

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

CONFIGURE FAILED in 1s
Unable to determine the current character, it is not a string, number, array, or object

The current character read is 'E' with an int value of 69
Unable to determine the current character, it is not a string, number, array, or object
line number 1
index number 0
Error: EPERM: operation not permitted, scandir 'D:/Projects/myApp/android/app/build/intermediates/signing_config/debug/out/signing-config.json'    at Object.readdirSync (fs.js:790:3)    at GlobSync._readdir (D:\Projects\myApp\node_modules\glob\sync.js:288:41)    at GlobSync._readdirInGlobStar (D:\Projects\myApp\node_modules\glob\sync.js:267:20)    at GlobSync._readdir (D:\Projects\myApp\node_modules\glob\sync.js:276:17)    at GlobSync._processReaddir (D:\Projects\myApp\node_modules\glob\sync.js:137:22)    at GlobSync._process (D:\Projects\myApp\node_modules\glob\sync.js:132:10)    at GlobSync._processGlobStar (D:\Projects\myApp\node_modules\glob\sync.js:380:10)    at GlobSync._process (D:\Projects\myApp\node_modules\glob\sync.js:130:10)    at GlobSync._processGlobStar (D:\Projects\myApp\node_modules\glob\sync.js:383:10)    at GlobSync._process (D:\Projects\myApp\node_modules\glob\sync.js:130:10)
^
`

**Comment by concuacon** [comment]
Hello, @007asom You can follow to fix https://github.com/react-native-community/cli/issues/591#issuecomment-515264992

**Comment by 007asom** [comment]
I'll try to do it. Thanks

**Comment by 007asom** [comment]
there are a new issues from the apple store team.

Guideline 2.1 - Performance - App Completeness


Your app crashed on iPad running iOS 13.2.3 on WiFi when we:

Tapped Facebook login

We have attached detailed crash logs to help troubleshoot this issue.

Guideline 4.8 - Design - Sign in with Apple


We noticed that your app uses a third-party login service but does not offer Sign in with Apple.

**Comment by concuacon** [comment]
> there are a new issues from the apple store team.
> 
> Guideline 2.1 - Performance - App Completeness
> 
> Your app crashed on iPad running iOS 13.2.3 on WiFi when we:
> 
> Tapped Facebook login
> 
> We have attached detailed crash logs to help troubleshoot this issue.
> 
> Guideline 4.8 - Design - Sign in with Apple
> 
> We noticed that your app uses a third-party login service but does not offer Sign in with Apple.

@007asom 
This is Apple's new policy. If you use a third-party login service, you must always use Apple for Apple to approve for you.

**Comment by 007asom** [comment]
> Hello, @007asom You can follow to fix [react-native-community/cli#591 (comment)](https://github.com/react-native-community/cli/issues/591#issuecomment-515264992)

Hi
Still same problem.

**Comment by minhcasi** [comment]
@007asom - pls note we will add Apple Sign In to fix this problem as this is new policies from Apple - it will be ready in 3.9.7 - thanks
