### ISSUE TITLE
FluxStore login - registration issue 

### ISSUE THREAD

**Issue by MohammedSwefee** [inspireui/support#1362]
1. My issue is that I can't log in or register 

2. Screenshots

![image](https://user-images.githubusercontent.com/34106827/68579441-29670400-0485-11ea-913b-d411a2998602.png)

![image](https://user-images.githubusercontent.com/34106827/68579481-41d71e80-0485-11ea-978e-6485748b809e.png)

if possible contact me on mohammed.thaaer94@gmail.com

**Comment by minhtruong315** [comment]
@MohammedSwefee did you install mstore-api plugin?

**Comment by MohammedSwefee** [comment]
Hi bro,

yes I installed it as below

[image: image.png]

the issue that I can create an account but I can't log in with it,

[image: image.png]



Regards,
Mohammed Thaaer

**Comment by minhtruong315** [comment]
I dont see JSON API plugin
Please read the document again.
https://docs.inspireui.com/fluxstore/woocommerce-setup/
You need install all plugin to work

**Comment by MohammedSwefee** [comment]
It is working fine now, thanks bro

**Comment by ajnaf** [comment]
i have installed all plugins and still have the issue
