### ISSUE TITLE
[FluxNews] - Onboarding not working, can skip forced sign-in

### ISSUE THREAD

**Issue by TheCellMC** [inspireui/support#1363]
1. My issue

I am running into a couple issues with FlexNews:
- The onboarding welcome screen never appears, although this option is clearly available in the `config.dart` file. (config section attached below)
- If I set `IsRequiredLogin` to true, I can still avoid signing-in by pressing the back button at the top left of the app.
- I see many references to a store in the config and code for FluxNews and in its some words of the documentation. For instance on this page you talk about a [Shop](https://docs.inspireui.com/fluxnews/customization/) at one point. My main concern is in the app's code as I believed many lines are entirely unused. Is this normal?

2. My screenshot of the purchase product or my comment:

![Screenshot 2019-11-10 at 14 25 03](https://user-images.githubusercontent.com/12169936/68544679-fc9fe780-03c5-11ea-842c-51d40a629941.png)

3. Config files

Onboarding config in `config.dart`:
```
/// the welcome screen data
List onBoardingData = [
  {
    "title": "Welcome to FluxStore",
    "image": "assets/images/fogg-delivery-1.png",
    "desc": "Fluxstore is on the way to serve you. "
  },
  {
    "title": "Connect Surrounding World",
    "image": "assets/images/fogg-uploading-1.png",
    "desc":
        "See all things happening around you just by a click in your phone. "
            "Fast, convenient and clean."
  },
  {
    "title": "Let's Get Started",
    "image": "fogg-order-completed.png",
    "desc": "Waiting no more, let's see what we get!"
  },
];

```

Note: I am running the latest version of FluxNews (1.1.0) on an iPhone X running iOS 13.2
[UPDATE]: Same issues are present on Android 9 on a Pixel 3XL.

**Comment by minhcasi** [comment]
@TheCellMC - noted with checking, thank you!

**Comment by dttrung26** [comment]
Hi @TheCellMC ,

For the first 2 questions, Welcome Screen and Forcing Login feature will be fixed and updated in the next version due to the large modifications.
For the last one, because the FluxNews was developed and built in the core of FluxStore coding base, you might see some terms and variable names related to Store and Shop.  You therefore don't have to be worry since all of the code are perfectly optimized by technical team. 

Have a nice day!
