### ISSUE TITLE
[Mstore Pro] - Issues in 3.9.6 ( same as github ticket #1249 )

### ISSUE THREAD

**Issue by Riyashanke** [inspireui/support#1364]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. Issues still pending as mentioned in GitHub ticket #1249 I have mailed the complete source code to your mail Id(support@inspireui.com) through WeTransfer. Kindly solve the issues sir Please.

<img width="723" alt="Screenshot of support message" src="https://user-images.githubusercontent.com/56667597/68585563-96d85c00-04a8-11ea-96e8-6e0459ea1967.png">

**Comment by concuacon** [comment]
@Riyashanke Can you send me your website admin account? I need to check your plugin
tuan@inspireui.com

**Comment by Riyashanke** [comment]
@concuacon I have send the details to the mail id you have mentioned tuan@inspireui.com. Kindly have a look. Sir.

**Comment by concuacon** [comment]
@Riyashanke Sorry I don't see your mail.

**Comment by Riyashanke** [comment]
@concuacon I have send the mail once again. Now can you check. Sir.

**Comment by Riyashanke** [comment]
Hi, @concuacon any updates regarding the issues.

**Comment by Riyashanke** [comment]
@concuacon Sir kindly check your mail. Awaiting your reply.

**Comment by Riyashanke** [comment]
Hi @concuacon, 
I have checked the app with the file you send through wetransfer. Still no improvement same issues continues.  
1)Reviews not displaying,
2) coupon not working
3) My order page order price is showing wrong by adding total + shipping amount. But in backend it’s showing correctly. 
4)In Cash on Delivery method order is not confirming the order it’s keep on loading.
5)While choosing payment gateway methods if click the close button in the pop up screen it’s coming directly to the Thank You page and order is made without making a payment.
I have send the screenshots through mail, Kindly check sir

Awaiting your reply

**Comment by concuacon** [comment]
Hi @Riyashanke, I have checked it works,  can you attach a screenshot to my mail? I'll check again.

**Comment by Riyashanke** [comment]
> Hi @Riyashanke, I have checked it works, can you attach a screenshot to my mail? I'll check again.

Sir I have send the mail with screenshots as well as video. Kindly check sir.

**Comment by Riyashanke** [comment]
Hi @concuacon, if review and coupon code is working for you then can you send me the video or screenshot to mail sir. Because for me this 2 issues still continues.

**Comment by concuacon** [comment]
@Riyashanke I have attached video screen recording and new source code to your mail, please check your mailbox.

**Comment by Riyashanke** [comment]
> @Riyashanke I have attached video screen recording and new source code to your mail, please check your mailbox.

Sure @concuacon I’ll let you know

**Comment by Riyashanke** [comment]
> > @Riyashanke I have attached video screen recording and new source code to your mail, please check your mailbox.
> 
> Sure @concuacon I’ll let you know

Hi @concuacon Your new code worked as expected. But still there’s one small issue in the coupon while using payment gateway. I have attached a video link in the mail you can see the video for better understanding other than that everything is perfect sir. Kindly check your mail sir.

**Comment by Riyashanke** [comment]
Hi @concuacon have you checked the mail and the video I have attached. Awaiting your reply.

**Comment by concuacon** [comment]
@Riyashanke Sorry I forgot to answer you, I am stuck in another problem, I will check your issue and respond to you soon.

**Comment by Riyashanke** [comment]
Hi @concuacon I have send the credentials yesterday to your mail is that ok. Did you check sir.

**Comment by Riyashanke** [comment]
Hi @concuacon any updates regarding the issues.
