### ISSUE TITLE
[beonews] - onesignal ios 13

### ISSUE THREAD

**Issue by paulica40** [inspireui/support#1366]
purchase code:
029a5bbd-3911-40d1-893f-f6797bc53504

hy there,

i am using beonews 3.0.4,
 "react": "16.8.6",
 "react-native": "0.59.8",
"react-native-onesignal": "3.2.14",

everything is working great, except onesignal notifications on ios 13, on ios 12 is working and on android.

how to update onesignal? the most recent version is 3.5.0 which supposed to work on ios13.

need some help to configure this in xcode, cause it's kind of diffrent from earlier version:)

any steps i should follow regarding beonews code?

thank you

**Comment by minhcasi** [comment]
@paulica40  - could you double-check the document Onesignal if can help - https://github.com/OneSignal/react-native-onesignal ?

**Comment by paulica40** [comment]
got that working on ios13, jut update react-native-onesignal to version 3.5.0
