### ISSUE TITLE
[fluxstore] - Phone Number Input and Firebase SHA-1

### ISSUE THREAD

**Issue by CharanKumar4** [inspireui/support#1368]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue
SMS Loggin error .
I have watched this guide. still getting error 
 https://docs.inspireui.com/fluxstore/firebase/#sms-login -

2. Screenshots

![16f63c60-677f-414c-90e3-6d27bf09ceca](https://user-images.githubusercontent.com/57438790/68608341-6c9c9380-04d4-11ea-9ba2-9685716691de.jpg)

3. My screenshot of the purchase product or my comment:
![support](https://user-images.githubusercontent.com/57438790/68608243-39f29b00-04d4-11ea-881a-8fd2604a1fe4.PNG)

3. Config files (optional)

**Comment by minhcasi** [comment]
You need to configure the SHA-1 in firebase console.

You can do it very easily using Android Studio tools.

Open Tools -> Firebase in Android Studio.
Click any one of the features, like Authentication or RealtimeDatabase.
Click on the Connect to Firebase and do the required.
or
Add it manually. Check out this guide: https://stackoverflow.com/questions/39144629/how-to-add-sha-1-to-android-application

**Comment by minhcasi** [comment]
Let us know if you have resolved the ticket or reopen it you still have an issue - thanks
