### ISSUE TITLE
ListApp

### ISSUE THREAD

**Issue by reconshield** [inspireui/support#137]
in next update kindly consider this suggestion

1) when updating react native files for bugs troubleshoot, please separate bugs solved files separately.
when you are updating or solve bugs, new errors /bugs appear. Listapp not stable and keep giving errors. most of buyers give up on this template since never-ending bugs.

2) complete video/installation documetation

3) Create live chat support

4) Apps cant use at all. since mylisting theme update and wp/plugins update.

5) Please fully test app before release it.

**Comment by minhcasi** [comment]
Thank you for your suggestion!
