### ISSUE TITLE
[MStore-Pro] - Error

### ISSUE THREAD

**Issue by Jegufull** [inspireui/support#1370]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue

/Users/jeimergutierrez/mstore-3.9.6/mstore-pro/ios/Pods/Target Support Files/Pods-OneSignalNotificationServiceExtension/Pods-OneSignalNotificationServiceExtension.debug.xcconfig: unable to open file (in target "OneSignalNotificationServiceExtension" in project "mstore")

2. Screenshots
<img width="1440" alt="Captura de Pantalla 2019-11-11 a la(s) 5 59 55 p  m" src="https://user-images.githubusercontent.com/47310507/68627948-208a2880-04ad-11ea-977d-ab414c6aa099.png">

3. My screenshot of the purchase product or my comment:
Item Purchase Code:
36e9cfd7-96da-413e-b43f-83ef03bed15b
3. Config files (optional)

**Comment by concuacon** [comment]
Hello, @Jegufull try run steps:
cd ios/ && rm -rf Pods/ && rm -rf Podfile.lock && pod install && cd ../ && react-native run-ios
if it still not work, you can try to follow documents of OneSignal for ios: https://documentation.onesignal.com/docs/react-native-sdk-setup
