### ISSUE TITLE
[BuzzApp] - Articles do not appear in app

### ISSUE THREAD

**Issue by TheCellMC** [inspireui/support#1373]
1. My issue

I'm trying to configure my BuzzApp to load posts from my website but it will not work. I'm entering the url in CeBuilder. If I set the url to http://news.inspireui.com, the posts load correctly, but nothing loads when I set my Wordpress website url: http://bit.ly/2O44W6c (shortened url so I can remove it once the issue is closed).

However, a preview of the posts loads in the Flipboard feature. 
Please could you have a look at this?

**Comment by minhcasi** [comment]
@TheCellMC  - could you help to check this wordpress seting - https://docs.inspireui.com/beonews/wordpress-setting/ - thanks

**Comment by TheCellMC** [comment]
Hi, I've double checked all those settings and it still won't work. The weird thing is that your BeoNews app works with my website. Only BuzzApp refuses to connect, or rather load any content in any screen, except from in the Flipboard.

**Comment by minhcasi** [comment]
@TheCellMC - could you attache the screenshot here - thank you!

**Comment by TheCellMC** [comment]
Sure, no problem. Here are my config files for BuzzApp. As you will be able to see, I only edited the `AppConfig.json` file (WeTransfer download).

https://we.tl/t-vidFLij8cC

I've also emailed you login details for my website to the email address shown on your GitHub profile page (minhcasi@gmail.com) with subject `Issue #1373`.

Thanks

**Comment by minhcasi** [comment]
@TheCellMC - thank you for the detail, I've forward to my team for further checking and let you know - thanks

**Comment by TheCellMC** [comment]
After some more troubleshooting, I found the error.
By default, all of my posts were in the uncategorised category, although this line in the constants.js file prevented them from being shown:

`excludeCategories: [1],`

Anyway, thanks so much for your help

**Comment by minhcasi** [comment]
Thank you, you are welcome :)
