### ISSUE TITLE
 [Mstore multi vendor] + WCFM - Chat platform Firebase or talkjs.com...

### ISSUE THREAD

**Issue by lukasprelovsky** [inspireui/support#1375]
Hi,

    I need setup online chat.
    I find tutorial to setup: https://docs.inspireui.com/mstore-mv/firebase/ 
    This solution working with Firebase. 

    I use multivendor WCFM https://wclovers.com and this software using talkjs.com ..
    see: https://wclovers.com/knowledgebase/wcfm-marketplace-chat-module/

   can it be used in talkjs.com to make it consistent across the web and in the app?

    Purcharse code - 9c050d9d-7583-47a4-a550-2785b43cf91d

Please help me. Thx

**Comment by minhcasi** [comment]
Hi, thank you for suggesting a great idea, I think it's possible to use the Webview to load the talkjs. 

Do you have the example chat on your site so that we could have a check?

**Comment by lukasprelovsky** [comment]
we need to create a chat for each vendor separately so that each vendor can manage their chat.

now use firebase, where is it managed and communicated with customers?

**Comment by minhcasi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Chat platform Firebase or talkjs.com](https://trello.com/c/Zgf3wgaZ/3-chat-platform-firebase-or-talkjscom)

**Comment by minhcasi** [comment]
we are closing the ticket and move this ticket 'request feature' to our Trello board for easier to keep track, review, and update, also keep a status update  - thank you!
