### ISSUE TITLE
[mstore pro] - Invalid or unexpected token

### ISSUE THREAD

**Issue by mk4full** [inspireui/support#1376]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue

I would like build app and ocorred error: https://ibb.co/n618sW5

2. Screenshots

https://ibb.co/n618sW5

3. My screenshot of the purchase product or my comment:

https://ibb.co/9wrv1QN

**Comment by minhcasi** [comment]
Hi from the terminal try this: expo login

And type your expo count, this build script requires your expo account login to validate the store the build

**Comment by mk4full** [comment]
@minhcasi thank you, i occoured one more error - https://ibb.co/zPfxbkm
