### ISSUE TITLE
Mstore Shopify

### ISSUE THREAD

**Issue by 77aram771** [inspireui/support#1377]
Hello I'd like buy Mstore Shopify but this not updated last version Expo!
https://codecanyon.net/item/mstore-shopify-complete-react-native-template-for-ecommerce/20475317
Please you can give me link Mstore Shopify from last version Expo!

**Comment by 77aram771** [comment]
> Hello I'd like buy Mstore Shopify but this not updated last version Expo!
> https://codecanyon.net/item/mstore-shopify-complete-react-native-template-for-ecommerce/20475317
> Please you can give me link Mstore Shopify from last version Expo!

**Comment by minhcasi** [comment]
noted for upgrade new Expo version shortly - thanks

@concuacon

**Comment by 77aram771** [comment]
Thank for answer!

You can tell  when you can upgrade at least an approximate date?

**Comment by concuacon** [comment]
Hello, @77aram771 I will upgrade next week.
