### ISSUE TITLE
[EvaStore] - Custom page is not loading - 1.1.4

### ISSUE THREAD

**Issue by alisa140** [inspireui/support#1378]
1.1 My issue: Custompage is empty. All App web views (custom page) are loading empty white page. This issue started happening in the new version: 1.1.4. I have also build and run the exact fresh copy from Codecanyan and faced the same issue. 
1.2 Screenshots
https://tppr.me/3JBf
https://tppr.me/oNkK1

2.1My issue: The Shipping Method in version 1.1.4 has disappeared from the checkout view. You cannot progress to payement due to an alert "Please select shipping method"
2.2 Screenshots:
https://tppr.me/eQRqA
https://tppr.me/Tdq1E

3.1 My issue: I have enabling QuickCart to allow customers to add products to cart directly from the horizontal layout. this has been achived by setting ShowQuickCart in Common/Constants.js to true. the issue: the app doesn't check inventory level before adding to the cart which results in adding products with zero stock.
Screenshots
out of stock product https://tppr.me/cxPwa
see I can add it through QuickCart: https://tppr.me/wv8J

4. My screenshot of the purchase product or my comment:
https://tppr.me/7dQEu
5. Config files (optional)
not required. the issue is at the baseline.

**Comment by minhcasi** [comment]
@alisa140 - try to create one ticket for your issues that help the team easy focus on your current integration could you zip your current source and send back to support@inspireui.com - thanks

-------

I have enabling QuickCart to allow customers to add products to cart directly from the horizontal layout. this has been achived by setting ShowQuickCart in Common/Constants.js to true. the issue: the app doesn't check inventory level before adding to the cart which results in adding products with zero stock.

The Shipping Method in version 1.1.4 has disappeared from the checkout view. You cannot progress to payement due to an alert "Please select shipping method"

**Comment by concuacon** [comment]
Hello, @alisa140 You can follow the step below:
- Run: expo install react-native-webview
- Search 'WebView' in the project and replace  "**import { WebView } from 'react-native';**" with "**import { WebView } from 'react-native-webview';**"
- Rebuild
I will update the next version. Thank you.

**Comment by alisa140** [comment]
> @alisa140 - try to create one ticket for your issues that help the team easy focus on your current integration could you zip your current source and send back to [support@inspireui.com](mailto:support@inspireui.com) - thanks
> 
> I have enabling QuickCart to allow customers to add products to cart directly from the horizontal layout. this has been achived by setting ShowQuickCart in Common/Constants.js to true. the issue: the app doesn't check inventory level before adding to the cart which results in adding products with zero stock.
> 
> The Shipping Method in version 1.1.4 has disappeared from the checkout view. You cannot progress to payement due to an alert "Please select shipping method"

Thanks. I have consolidated the issues into one ticket as requested. I have emailed you the source code to take a look.

**Comment by concuacon** [comment]
@alisa140 I have answered your mail please check your mailbox.

**Comment by 3rabapp** [comment]
Thanks. I can confirm the Shipping method & WebView issues have been fixed. Thank you very much for your generosity in fixing my project. 

The is one more remaining issue which seems to presist - Adding through QuickCart doesn't check innovatory level #1380 : https://github.com/inspireui/support/issues/1380. I would appreciate if you reopen it for tracking purpose.
