### ISSUE TITLE
[EvaStore] - Shipping method is missing in checkout view 

### ISSUE THREAD

**Issue by alisa140** [inspireui/support#1379]
1. My issue: The Shipping Method in version 1.1.4 has disappeared from the checkout view. You cannot progress to payement due to an alert "Please select shipping method" 

2. Screenshots:
https://tppr.me/eQRqA
https://tppr.me/Tdq1E
3. My screenshot of the purchase product or my comment:
https://tppr.me/7dQEu

3. Config files (optional)
Not required as the issue is in the baseline.

**Comment by minhcasi** [comment]
Duplicate of #1378 - pls note to this ticket
