### ISSUE TITLE
[MStore] What's the best method to EXPORT APK 

### ISSUE THREAD

**Issue by kiamoz** [inspireui/support#138]
it's better to export it through android Stadio  ?  or easier to export it via cammand line  , ( I have OSX )
and if you have video please give me that how to easy export andorid in osx ,. thank you

**Comment by luyx2412** [comment]
Hi @kiamoz The easiest and best method to export APK file is command line. Please follow the document https://facebook.github.io/react-native/docs/signed-apk-android#generating-the-release-apk

Thanks
