### ISSUE TITLE
[Fluxstore] Multi Language Active with OpenCart and checkout

### ISSUE THREAD

**Issue by Sherbi** [inspireui/support#1381]
I have found the way to put the setting on menu of the App but there is another Q? when I change the language every time open the app it was reset to the default language and most change it even when I made it via account setting after register account
and still need to know how can I activate the payment as cash on delivery ?
Thanks a lot for you

**Comment by minhcasi** [comment]
Hi, the restart issue could be a bug, we have note as further investigating and will have an update on next release - thank you!

You can simply enable COD from the Woocommerce side, then it will display on the app

**Comment by Sherbi** [comment]
I work on OpenCart not WooCommerce so how can I make the Arabic is the Default Language in the App 

2nd:  I still need to know how can I activate the payment as cash on delivery ?

**Comment by minhcasi** [comment]
The default language could be changed from model/app.dart - change "en" to "ar" -> we will move this config to the common/config.dart on next release

COD will be enabled automatically on the app when you enable it from the Website.

Let us know if you have any further questions
Thank you!
