### ISSUE TITLE
flux store home page of config.json does not redirect to my website 

### ISSUE THREAD

**Issue by nizarweb77** [inspireui/support#1382]
config.json does not redirect to my website its go to inspiru demo site and category
`  
{
  "HorizonLayout": [
    {
      "layout": "logo",
      "showMenu": true,
      "showSearch": true
    },
    {
      "layout": "category",
      "type": "icon",
      "wrap": false,
      "size": 1.0,
      "radius": 50.0,
      "items": [
        {
          "category": 69,
          "image": "assets/images/toyota.png",
          "colors": [
            "#3CC2BF",
            "#3CC2BF"
          ],
          "originalColor": true
        },
        {
          "category": 69,
          "image": "assets/images/bmw.png",
          "colors": [
            "#3E6AB5",
            "#3E6AB5"
          ],
          "originalColor": true

        },
        {
          "category": 69,
          "image": "assets/images/ford.png",
          "colors": [
            "#53A2CC",
            "#53A2CC"
          ],
          "originalColor": true

        },
        {
          "category": 69,
          "image": "assets/images/chevrolet.png",
          "colors": [
            "#53688A",
            "#53688A"
          ],
          "originalColor": true

        },
        {
          "category": 69,
          "image": "assets/images/hyundai.png",
          "colors": [
            "#43506A",
            "#43506A"
          ],
          "originalColor": true

        },
        {
          "category": 69,
          "image": "assets/images/nissan.png",
          "colors": [
            "#12B58C",
            "#12B58C"
          ],
          "originalColor": true

        }
      ]
    },

    {
      "layout": "header_text",
      "fontSize": 20.0,
      "title": "Choose desired vehicle type. "
    },

    {
      "layout": "bannerImage",
      "isSlider": true,
      "autoPlay": false,
      "showNumber": false,
      "design": "default",
      "showBackGround": true,
      "radius": 2.0,
      "items": [
        {
          "category": 71,
          "image": "http://backend.nizarklai.info/wp-content/uploads/2019/11/specailcar1.png",
          "padding": 15.0
        }

      ]
    },
    {
      "layout": "bannerImage",
      "isSlider": true,
      "autoPlay": false,
      "showNumber": false,
      "design": "default",
      "showBackGround": true,
      "radius": 2.0,
      "items": [
        {
          "category": "69",
          "image": "http://backend.nizarklai.info/wp-content/uploads/2019/11/economycar1-1.png",
          "padding": 15.0
        }
      ]
    },
    {
      "layout": "bannerImage",
      "isSlider": true,
      "autoPlay": false,
      "showNumber": false,
      "design": "default",
      "showBackGround": true,
      "radius": 2.0,
      "items": [
        {
          "category": "70",
          "image": "http://backend.nizarklai.info/wp-content/uploads/2019/11/luxurycar1.png",
          "padding": 15.0
        }
      ]
    }
  ],
  "Setting": {
    "MainColor": "#3FC1BE",
    "ProductListLayout": "list"
  },
  "TabBar": {
    "Home": {
      "isDisplay": true
    },
    "Category": {
      "isDisplay": true
    },
    "Search": {
      "isDisplay": true
    },
    "Cart": {
      "isDisplay": true
    },
    "Profile": {
      "isDisplay": true
    }
  }
}

`

**Comment by minhcasi** [comment]
@nizarweb77 - it's required to change the config.dart to link to your own site - https://docs.inspireui.com/fluxstore/woocommerce-setup/#step-3-setup-fluxstore
