### ISSUE TITLE
[Fluxstore-1.5.7] - How to disable Blog buttom  from side bar menu 

### ISSUE THREAD

**Issue by EmilianH** [inspireui/support#1383]
![compra](https://user-images.githubusercontent.com/57189819/68780602-50544000-0615-11ea-8849-94712b61f7f2.jpg)

i need to disable blog from side bar menu
thanks

---------

1. My issue

2. Screenshots

3. My screenshot of the purchase product or my comment:

3. Config files (optional)

**Comment by minhcasi** [comment]
Use the inspector to update/hide to reach to the widget UI for updating - https://docs.inspireui.com/fluxstore/useful-tip/
