### ISSUE TITLE
[MStore Pro] - 'src' of undefined and “RNCViewPager” was not found

### ISSUE THREAD

**Issue by gokhand** [inspireui/support#1388]
We use mstore-3.9.6 on the site all plugins set up with latest versions including MStore-API is the latest.

react-native-cli: 2.0.1
react-native: 0.60.4

> These 2 issues are in Android on Windows Environment, we have also IOS issues on MacOS I will report later after we finish this Android issues.

**First issue:**
we are facing when we click the categories or sometimes on product (not always but most of the time) it says:

> TypeError: Cannot read property ‘src’ of undefined

We investigate a little bit and we found the route cause:
If the woocommerce product hasn’t got any images it return in the json

> “images”: [],

so that is why your code even some places (I think in 9 file I found) tried to handle with

`typeof product.images[0] !== “undefined”`

which is ok, but most of the views tries to direct use of the product.images[0].src or data.images[0].src etc…and it breaks and we use placeholders if the product hasn’t got any image, so we don’t want to add placeholder images to every single product which hasn’t got any image.

so can you fix this for the general templates and everywhere not just 9 places.

**The second one is this:**
When we click on cart or adding to the cart the error is the following: Invariant Violation: requireNativecomponent: “RNCViewPager” was not found in the UIManager

We also investigate it and it seems ViewPagerAndroid is not part of react-native core anymore. So we have to add to package.json dependencies like this:

> "@react-native-community/viewpager": "^2.0.2",

and we have to install with npm;

> npm i @react-native-community/viewpager

It gave some warning messages but it installed anyway:

> npm WARN @typescript-eslint/eslint-plugin@1.13.0 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
> npm WARN @typescript-eslint/parser@1.13.0 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
> npm WARN eslint-plugin-react@7.12.4 requires a peer of eslint@^3.0.0 || ^4.0.0 || ^5.0.0 but none is installed. You must install peer dependencies yourself.
> npm WARN eslint-plugin-react-native@3.6.0 requires a peer of eslint@^3.17.0 || ^4 || ^5 but none is installed. You must install peer dependencies yourself.
> npm WARN react-native-localization@2.1.6 requires a peer of react-native@^0.41.2 but none is installed. You must install peer dependencies yourself.
> npm WARN react-native-localization@2.1.6 requires a peer of react-native-windows@0.41.0-rc.1 but none is installed. You must install peer dependencies yourself.
> npm WARN react-native-webview@6.11.1 requires a peer of react-native@>=0.57 <0.60 but none is installed. You must install peer dependencies yourself.
> npm WARN styled-components@4.4.1 requires a peer of react-dom@>= 16.3.0 but none is installed. You must install peer dependencies yourself.
> npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
> 
> + @react-native-community/viewpager@2.0.2
> updated 1 package and audited 955409 packages in 18.669s
> found 0 vulnerabilities

 After that when we run react-native run-android it gave this error:

> warn Package react-native-community/viewpager has been ignored because it contains invalid configuration. Reason: Cannot find module 'react-native-community\viewpager\package.json'
> Require stack:
> - \node_modules\react-native\node_modules\@react-native-community\cli\build\tools\config\resolveNodeModuleDir.js
> - \node_modules\react-native\node_modules\@react-native-community\cli\build\tools\releaseChecker\index.js
> - \node_modules\react-native\node_modules\@react-native-community\cli\build\commands\server\runServer.js
> - \node_modules\react-native\node_modules\@react-native-community\cli\build\commands\server\server.js
> - \node_modules\react-native\node_modules\@react-native-community\cli\build\commands\index.js
> - \node_modules\react-native\node_modules\@react-native-community\cli\build\cliEntry.js
> - \node_modules\react-native\node_modules\@react-native-community\cli\build\index.js
> - \node_modules\react-native\cli.js
> - C:\Users\*********\AppData\Roaming\npm\node_modules\react-native-cli\index.js

After these warnings on the device we saw the app is running and that Cart section issue has fixed. 

Maybe you can find the better way to fix this as a package.

Could you please help for these errors.

![image](https://user-images.githubusercontent.com/3597701/68855032-4d208900-06d5-11ea-9410-6dd73dbb95eb.png)

**Comment by minhcasi** [comment]
@concuacon - pls help for checking

**Comment by concuacon** [comment]
Hello, @gokhand 
You can follow these steps:

- Delete folder node_modules/

- Re-install node_modules: npm install

- With this error: "Invariant Violation: requireNativecomponent: “RNCViewPager” was not found in the UIManager" => This is a react-native error, you just need to reload without having to add a new library @react-native-community/viewpager

- When run test on the device, run the command: cd android/;./gradlew clean;cd ../;react-native run-android

**Comment by gokhand** [comment]
I have always do for a clean run: cd android/;./gradlew clean;cd ../;react-native run-android

it is not just for android it is overall new version of the recact-native doesn't have @react-native-community/viewpager , we seems to have add dependencies.

Do you have any feedback about 'src' issue if the image is not exist case ?

**Comment by concuacon** [comment]
@gokhand Can you describe this problem with videos or photos? I tried debugging but didn't see the problem, thank you.

> I have always do for a clean run: cd android/;./gradlew clean;cd ../;react-native run-android
> 
> it is not just for android it is overall new version of the recact-native doesn't have @react-native-community/viewpager , we seems to have add dependencies.
> 
> Do you have any feedback about 'src' issue if the image is not exist case ?

**Comment by gokhand** [comment]
for to see the 'src' issue, you need to delete all images of one product, and see if the json returns 

> “images”: [],

then find and open that specific product from the app (or the list that product in) , and you will see the error.

**Comment by gokhand** [comment]
Have you had any chance to try to replicate the issue?

**Comment by concuacon** [comment]
@gokhand  tomorrow at 14h (GMT+7) can I remote to your device to test it? I tried as you said but still did not see the problem.

**Comment by gokhand** [comment]
Hi @minhcasi can we reopen this ticket, I had busy to arrange a remote connection with @concuacon , can we organize the same time on Wednesday (4th of December) please?

**Comment by minhcasi** [comment]
yes sure @gokhand

**Comment by gokhand** [comment]
@concuacon have you received my email for arrangement for the remote access ?

**Comment by minhcasi** [comment]
@concuacon - pls help for confirming?

**Comment by alexisttt** [comment]
Hello. I was facing the same problem. I have been able to solve the problem with steps bellow. I'm writing them in case some one else faces the same problem. The reason of the problem is the rcn-viewpager not installed automatically.

First delete the app from the device
Delete all the node_modules in the app directory.
Open the terminal in the main directory. Then type commands bellow with the order.

```
yarn install.
yarn add @react-native-community/viewpager
react-native link @react-native-community/viewpager
```
Then just type `react-native run-ios` or `react-native run-android`

**Comment by concuacon** [comment]
@gokhand You just re-install react-native-swiper with the command line:  yarn add react-native-swiper@nightly and re-build your app. Or you can follow the way of @alexisttt
