### ISSUE TITLE
[mstore-mv] - Rest api not working correctly

### ISSUE THREAD

**Issue by dutchessdad2017** [inspireui/support#1389]
1. My issue
I purchased this but it is not working at all. please respond asap thank you
2. Screenshots

3. My screenshot of the purchase product or my comment:
![image](https://user-images.githubusercontent.com/57761425/68865644-29ebde80-06c1-11ea-892e-ac54b1a33b82.png)

3. Config files (optional)

**Comment by minhcasi** [comment]
@dutchessdad2017 - could you help to share the screenshot of current issues so that we can check the root cause?

Also, try with this getting started base on Expo for the basic installing - https://docs.expo.io/versions/latest/get-started/installation/

**Comment by dutchessdad2017** [comment]
![image](https://user-images.githubusercontent.com/57761425/68953053-1a3acb80-078f-11ea-9689-dd57a80df44e.png)

**Comment by dutchessdad2017** [comment]
it has my rest api keys from woocommerce also

**Comment by dutchessdad2017** [comment]
![image](https://user-images.githubusercontent.com/57761425/68953155-52420e80-078f-11ea-9269-1f72b559d98d.png)

**Comment by minhcasi** [comment]
@dutchessdad2017  - pls help to check the consumse key config that could be wrong that cause the app could not connect to your side

https://docs.inspireui.com/mstore-mv/customization/
also double check this config: https://docs.inspireui.com/mstore-mv/getting-started/

**Comment by dutchessdad2017** [comment]
Does not work
