### ISSUE TITLE
[ListApp] clicking on the heart of a post does not update in the other views

### ISSUE THREAD

**Issue by Jeison12** [inspireui/support#139]
Product: ListApp
My Purchased Code: ccded53c-5f90-41ff-8c6a-fac4faae1017

Clicking on the heart of a post does not update in the other views

**Comment by minhcasi** [comment]
Could you share your Expo link so that we could have a quick look - thank you!

**Comment by Jeison12** [comment]
![screenshot_2019-01-06-09-28-37](https://user-images.githubusercontent.com/26725495/50737366-42809380-1196-11e9-84df-17830253cd8b.png)
![screenshot_2019-01-06-09-28-41](https://user-images.githubusercontent.com/26725495/50737367-42809380-1196-11e9-98a6-ab667026a249.png)



Hello, the link of the app is https://expo.io/@inspireui-demo/listapp-mylisting. When entering the details of Z Victoria and when I click on the heart that is at the bottom and return to the beginning, the heart of Z Victoria is not updated even though it has already been added to Bookmarks
