### ISSUE TITLE
[Mstore-MV] - I can't register from the app

### ISSUE THREAD

**Issue by fernandoalfarocode** [inspireui/support#1390]
**I can't register from the app**
---------

1. My issue
Hello, good morning, the problem I have is with Mstore Multivendor (Expo version) since I have followed the documentation (https://docs.inspireui.com/mstore-mv/getting-started/), I can register new users on the website but still I can not register new users in the APP, I would like that I Guidance on what the problem would be.

2. Screenshots
https://ibb.co/vBQKszv
https://ibb.co/rQZt698
https://ibb.co/tCLTkss
https://ibb.co/Jv0JyGw

3. My screenshot of the purchase product or my comment:
https://ibb.co/Jv0sNwv

**Comment by dutchessdad2017** [comment]
fernando how did you get the rest api to work

**Comment by minhcasi** [comment]
@dutchessdad2017  - could you share your config file here as well, we will help for checking the issue - thank you!

**Comment by dutchessdad2017** [comment]
which config file

**Comment by fernandoalfarocode** [comment]
hello, could you help me?

**Comment by fernandoalfarocode** [comment]
Hello, the problem of not being able to register users from the APP has already been solved ...

Now the problem I have is that I cannot post a new product from the APP since it gives me the error specified in the image, since the WFCM - Woocommerce store in Wordpress is uploaded.

Screenshots:
- https://ibb.co/VtGF2V5
- https://ibb.co/7VZ9y2b

**Comment by fernandoalfarocode** [comment]
> fernando how did you get the rest api to work

Hello, Rest API is already integrated in the Worpress core so you should not install that plugin, however, JSON API and MStore Checkout you must manually install them via FTP

**Comment by minhcasi** [comment]
@fernandoalfarocode - pls try to remove/replace old mstore checkout by using this plugins - https://wordpress.org/plugins/mstore-api/

**Comment by fernandoalfarocode** [comment]
> @fernandoalfarocode - pls try to remove/replace old mstore checkout by using this plugins - https://wordpress.org/plugins/mstore-api/
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/ce9a4b698e6f750660b63b4d6001e3c9ee10cdda/68747470733a2f2f70732e772e6f72672f6d73746f72652d6170692f6173736574732f62616e6e65722d373732783235302e706e673f7265763d32313631323137">WordPress.org**[MStore API](https://wordpress.org/plugins/mstore-api/)**Plugin link: https://github.com/inspireui/mstore-api
> > Tags: mstore, react native, mobile plugin
> > Requires at least: 4.0
> > Tested up to: 4.

Hello Minhcasi, I made the change but the old Mstore Checkout plugin is the one that allows me to fix the problem of not being able to register in the app but still the problem persists that I cannot add a new product from the app, the new MStore API plugin makes me fail both ... some other idea of ​​how to fix the problem of not being able to add products from the app?

**Comment by minhcasi** [comment]
@concuacon - pls help to check the login issue - thank you!

**Comment by fernandoalfarocode** [comment]
Hello?

**Comment by vumanhsn97** [comment]
@fernandoalfarocode Replace 2 files in src/services: CustomAPI.js and WPUserAPI.js 
[Archive.zip](https://github.com/inspireui/support/files/3900488/Archive.zip). Make sure you install new plugin Mstore API.

**Comment by fernandoalfarocode** [comment]
This problem was already solved, those components were, thanks for the help ...

I'm going to close

**Comment by minhcasi** [comment]
@fernandoalfarocode - thank you, we are happy that support for your ticket.

Please help us to give the feedback/rating to http://codecayon.net/downloads - that would be great help for the team. Very best!
