### ISSUE TITLE
[FluxNews] - Detailed setup guide

### ISSUE THREAD

**Issue by emmanuelalex** [inspireui/support#1391]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue

Hi Team, 

a. I have change the URL to my blog, but after compiling, the app shows a blank.
b. Is there a more comprehensive guide on setting up categories? I do not understand the numbers 30,40,etc)

2. Screenshots
https://1drv.ms/u/s!AhdrCzdtZsS6hqZAV26_MxyKQElFvQ?e=6kqffD

3. My screenshot of the purchase product or my comment:

https://1drv.ms/u/s!AhdrCzdtZsS6hqY9Uwya2r7GO0GbOg?e=CjoXOa

**Comment by minhcasi** [comment]
Hi, you can find the Category by edit the wordpress category, use this guide - https://voidcoders.com/find-category-id-wordpress/ - thanks
