### ISSUE TITLE
[FluxStore] -  Search does not work (Opencart)

### ISSUE THREAD

**Issue by Moostsv** [inspireui/support#1392]
Opencart search does not work. (config.dart and config.json from the folder ... example \ opencart, the rest is unchanged). 
![search](https://user-images.githubusercontent.com/47337033/68922370-1190c800-0784-11ea-899b-1d0ec35b5dfd.png)

**Comment by Maksish** [comment]
same problem

**Comment by minhcasi** [comment]
@Moostsv - could you share proof of purchased code on http://codecayon.net/downloads  by taking the screenshot include your username - thank you!

**Comment by Maksish** [comment]
I have solved the issue

**Comment by Moostsv** [comment]
https://pastenow.ru/79QV9

**Comment by minhcasi** [comment]
@Moostsv - thank you for resolving it quickly, could you share your solution?

**Comment by Moostsv** [comment]
I did not solve the problem. The question is still relevant.
