### ISSUE TITLE
[FluxStore] - Affiliate products don't work

### ISSUE THREAD

**Issue by mk4full** [inspireui/support#1393]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue

My all store is affiliate products, you can check my site http://bit.ly/2NObGWH, but fluxstore all product display like unavaiable like on movie, I added one new external product - this product can add to basket instead redirect. How can I set affilite store direct to external site? Look my video https://gofile.io/?c=gn8wts

2. Screenshots

https://gofile.io/?c=gn8wts

3. My screenshot of the purchase product or my comment:
https://ibb.co/6XZMBBd

**Comment by vumanhsn97** [comment]
@mk4full  Can you share your config.dart file?

**Comment by mk4full** [comment]
@vumanhsn97 here's https://gofile.io/?c=iijR4V

Thank you

**Comment by mk4full** [comment]
@vumanhsn97 new version 1.8.5 resolve it :D thank you
