### ISSUE TITLE
flux store shipping problem

### ISSUE THREAD

**Issue by nizarweb77** [inspireui/support#1394]
![Screenshot_1573809232](https://user-images.githubusercontent.com/57265062/68931463-dfd22e00-0790-11ea-9d18-424831e8157a.png)

hi please can you  tell me what cause this problem trying to fix also why they are delay to mutch in the support

**Comment by nizarweb77** [comment]
════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during layout:
A RenderFlex overflowed by 133 pixels on the bottom.

User-created ancestor of the error-causing widget was: 
  Consumer<CategoryModel> file:///C:/source0/lib/widgets/backdrop_menu.dart:42:16
The overflowing RenderFlex has an orientation of Axis.vertical.
The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and black striped pattern. This is usually caused by the contents being too big for the RenderFlex.

Consider applying a flex factor (e.g. using an Expanded widget) to force the children of the RenderFlex to fit within the available space instead of being sized to their natural size.
This is considered an error condition because it indicates that there is content that cannot be seen. If the content is legitimately bigger than the available space, consider clipping it with a ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex, like a ListView.

The specific RenderFlex in question is: RenderFlex#0c40f relayoutBoundary=up7 OVERFLOWING
...  needs compositing
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=308.2)
...  size: Size(411.4, 308.2)
...  direction: vertical
...  mainAxisAlignment: start
...  mainAxisSize: max
...  crossAxisAlignment: start
...  textDirection: ltr
...  verticalDirection: down
◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤
════════════════════════════════════════════════════════════════════════════════════════════════════
I/art     ( 3487): Background sticky concurrent mark sweep GC freed 68178(3MB) AllocSpace objects, 9(180KB) LOS objects, 38% free, 5MB/9MB, paused 3.205ms total 177.608ms

**Comment by minhcasi** [comment]
@nizarweb77  - this issue is fixed on next 1.5.8, - it will be available on tomorrow - thanks

**Comment by nizarweb77** [comment]
what about the payment gateway can you pls give us compete answer for this even the payment is not working like cod is not going true

**Comment by nizarweb77** [comment]
BIG THANKS TO YOU issue is fixed just by overwrite the old code of model/shippingmethod.dart to the new code of model/shippingmethod.dart
