### ISSUE TITLE
[MStore] Error to compile

### ISSUE THREAD

**Issue by hakihosting** [inspireui/support#1396]
Purchase code : ac9d522a-a783-4f9c-a882-7dc694488d5d 

Hello i have this error :
![image](https://user-images.githubusercontent.com/47614045/68943654-0ea9cd80-07ac-11ea-9760-dcd166b1c4d4.png)

**Comment by minhcasi** [comment]
@hakihosting - to to ios folder, try to remove Pod folder, .lock file - and run: pod install

Then, clean up the XCode Caching and restart the project again - thanks

**Comment by Jegufull** [comment]
I have the same error, I followed these steps and followed the same error.

<img width="1440" alt="Captura de Pantalla 2019-11-16 a la(s) 2 54 03 p  m" src="https://user-images.githubusercontent.com/47310507/68998510-01aade00-0881-11ea-85b5-54ffb0fec2cb.png">

**Comment by hakihosting** [comment]
same error

**Comment by concuacon** [comment]
@hakihosting  @Jegufull 
Close all terminal working and re-open new terminal try run command: rm -rf node_modules/ && yarn && cd ios/ && rm -rf Pods/ && rm -rf Podfile.lock && pod install && cd ../ && react-native run-ios

**Comment by hakihosting** [comment]
I do your tips  : 

Result : 


** BUILD FAILED **


The following build commands failed:
        CompileC /Users/heyckelneji/Desktop/ChakcwearApp-3.9.6/mstore-pro/ios/build/mstore/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FBSDKLoginKit.build/Objects-normal/x86_64/FBSDKDeviceLoginManagerResult.o FBSDKLoginKit/FBSDKLoginKit/FBSDKLoginKit/FBSDKDeviceLoginManagerResult.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

**Comment by Jegufull** [comment]
I have the same error, I followed these steps and followed the same error:

** BUILD FAILED **

The following build commands failed:
	CompileC /Users/jeimergutierrez/Downloads/mstore-3.9.6/mstore-pro/ios/build/mstore/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FBSDKLoginKit.build/Objects-normal/x86_64/FBSDKDeviceLoginManagerResult.o FBSDKLoginKit/FBSDKLoginKit/FBSDKLoginKit/FBSDKDeviceLoginManagerResult.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

**Comment by hakihosting** [comment]
some news ?

**Comment by concuacon** [comment]
@hakihosting @Jegufull 
Try going into your XCode project settings (File->Project Settings) and change the build system to Legacy Build System.

**Comment by hakihosting** [comment]
Hello i do your tips but still errors : 
![image](https://user-images.githubusercontent.com/47614045/69501628-103f6800-0f07-11ea-80a5-70eed9ed7863.png)

**Comment by concuacon** [comment]
@hakihosting You can try to follow this [link]( https://github.com/react-native-community/react-native-maps/issues/813#issuecomment-366195369)

**Comment by hakihosting** [comment]
same problem 
![image](https://user-images.githubusercontent.com/47614045/69580362-b6a56f00-0fd4-11ea-88fc-11b32f76486a.png)

**Comment by concuacon** [comment]
@hakihosting this link can help you https://github.com/facebook/facebook-ios-sdk/issues/1102#issuecomment-551872120

**Comment by hakihosting** [comment]
Hello ok no i have this error when i do your tricks :  (maybe can we do a skype assistance)

cy_info -Xlinker /Users/heyckelneji/Desktop/ChakcwearApp-3.9.6/mstore-pro/ios/build/mstore/Build/Intermediates.noindex/mstore.build/Debug-iphonesimulator/mstore.build/Objects-normal/x86_64/Chakcwear_dependency_info.dat -o /Users/heyckelneji/Desktop/ChakcwearApp-3.9.6/mstore-pro/ios/build/mstore/Build/Products/Debug-iphonesimulator/Chakcwear.app/Chakcwear
ld: warning: directory not found for option '-L/Users/heyckelneji/Desktop/ChakcwearApp-3.9.6/mstore-pro/ios/build/mstore/Build/Products/Debug-iphonesimulator/yoga'
ld: library not found for -lyoga
clang: error: linker command failed with exit code 1 (use -v to see invocation)


** BUILD FAILED **


The following build commands failed:
        Ld build/mstore/Build/Products/Debug-iphonesimulator/Chakcwear.app/Chakcwear normal x86_64
(1 failure)

**Comment by concuacon** [comment]
@hakihosting my skype: pvtuan1707

**Comment by Jegufull** [comment]
I hace the same error.

**Comment by minhcasi** [comment]
@concuacon  - pls note the solution for this issue after checking - thanks

**Comment by hakihosting** [comment]
Hello why you close the topic , is not solved i have the problem

**Comment by minhcasi** [comment]
@concuacon - pls check
