### ISSUE TITLE
[MSTORE Expo] -   image icons  not show in APK

### ISSUE THREAD

**Issue by kiamoz** [inspireui/support#1397]
Dear support ,  till yesterday , when I export APK , no image shows ( category  icon and   menu bar icons .. )  , also I try to export  your fresh source without any  edit  but not works too !

 here is my APK :
http://atc.avishost.com/frontend/web/apk/ATC-3dc4e9a0c5fa41f0a37bb9f4aa909afa-signed.apk

here is api-ecommerce: i changed it to load from out API not wordpress.
http://atc.avishost.com/frontend/web/apk/api-ecommerce.zip

**Comment by kiamoz** [comment]
<img width="407" alt="Screen Shot 2019-11-15 at 4 55 24 PM" src="https://user-images.githubusercontent.com/10494372/68946643-bcc37080-07c8-11ea-9710-b791f1e6e581.png">
top  icon, ctageory icons , footer  icons not show  !!

**Comment by kiamoz** [comment]
I found the issue ,  EXPO service  block in  my country .  could you please let  me know where can I check with domain that  force to load this assets  ? this assets are in app why  not loading ?

**Comment by minhcasi** [comment]
@kiamoz - pls don't share source code here as this product is not open source

could you help to share your proof of purchased code from http://codecayon.net/downloads by taking your screenshot - thanks

**Comment by kiamoz** [comment]
![Screen Shot 2019-11-16 at 9 38 01 AM](https://user-images.githubusercontent.com/10494372/68988950-cf838700-0854-11ea-904a-de77ae7c283e.png)
[42316561-beostore-complete-react-native-template-for-ecommerce-license.txt](https://github.com/inspireui/support/files/3853867/42316561-beostore-complete-react-native-template-for-ecommerce-license.txt)

**Comment by minhcasi** [comment]
@kiamoz  - is there any log errors on the terminal when you the app, it seems there is issues with loading the static assets file - thanks

**Comment by kiamoz** [comment]
Dear support  , I can't get Error  log  , these icons not load till I connect to VPN , could  you please let me know  how to change location   of this  icons (change  to  load from  web not from src/images)  ?
thanks
