### ISSUE TITLE
[FluxStore] - Sale price and percantage disount

### ISSUE THREAD

**Issue by mk4full** [inspireui/support#1398]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue

Can I ask to create sales price and percentage sales label in list of products and home widgets in new version Fluxstore? Or Can I create it myself now?
 
2. Screenshots

3. My screenshot of the purchase product or my comment:

https://ibb.co/6XZMBBd

3. Config files (optional)

**Comment by minhcasi** [comment]
@mk4full - we will update these features on next release - thanks

In the meantime, you can also use the Inspector to change any UI from the app - https://docs.inspireui.com/fluxstore/useful-tip/#how-to-change-the-ui-quickly

**Comment by minhcasi** [comment]
Fixed on latest Gitlab
