### ISSUE TITLE
RTL Support - Configuration not taking effect

### ISSUE THREAD

**Issue by YazanArafat** [inspireui/support#14]
- Product: MStore Multi Vendor
 - Purchased Code: 91cb0275-e8ea-492d-adf5-29565cba1474

Hello, 

I'm trying to configure the app to support RTL and display a language by changing the DefaultCountry in config.js file, however, there is no effect taken when running the app. I've noticed the comment you wrote in the code -seen below- but didn't understand what does it mean or what do we need to do exactly. 

  // BUG: Language can not change when set default value in Config.js ==> pass string to change Languages
  // NOTE: name is define value --> change field in Language.js

Also, when trying to change the language form the app UI, I suppose its under the settings menu on the navigation menu -shown below- , however that button is not functioning and not routing to anything. It seems like its not connected to a routing function.

**Screenshots**
![image](https://user-images.githubusercontent.com/7161358/48550851-82d13d00-e8dc-11e8-91d5-f366091e35b1.png)

**Additional context**
Attached is the config file
[Config.js.zip](https://github.com/inspireui/support/files/2585125/Config.js.zip)

**Comment by luyx2412** [comment]
Hi @YazanArafat Let me check and reply u soon. Thanks for your waiting.

**Comment by luyx2412** [comment]
Hi @YazanArafat 
1. Now this version **MStore Multi Vendor** do not support Setting in sidemenu which only apply with pro version.
2. With the note in line 29 --> For example: `name: "featureProducts"` you will see this field `featureProducts` in Language.js file and change value to apply show on your app. this is a field name to support multi language. 
3. If you want to change language or RTL. Please change in Constant.js file with `RTL` and `Language` (url<img width="734" alt="screen shot 2018-11-19 at 9 48 51 am" src="https://user-images.githubusercontent.com/8909619/48683553-5f5e0900-ebe0-11e8-9d3b-9b2dc87da53f.png">) 

P/S: With DefaultCountry field in Config.js which only config for Country when handle cart.

Thanks
