### ISSUE TITLE
[mStore] - 

### ISSUE THREAD

**Issue by vkhalids** [inspireui/support#1401]
I have issue regarding registration on the app when i do checkout ...
I made an order
I did checkout
I registerd new account
after that it showed me a message as an unidentified
after  completion it gives me error

please see screen shot
![Screenshot_20191116_164954_host exp exponent](https://user-images.githubusercontent.com/35214886/68994241-c82e9e80-0891-11ea-9175-03d8054f6bcd.jpg)
![Screenshot_20191116_165008_host exp exponent](https://user-images.githubusercontent.com/35214886/68994242-c82e9e80-0891-11ea-9aaf-8c97efbad966.jpg)

> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue

2. Screenshots

3. My screenshot of the purchase product or my comment:

3. Config files (optional)

**Comment by concuacon** [comment]
@vkhalids Give me your email, I will send you a new source. Thank you

**Comment by vkhalids** [comment]
this is my email x4khalid@gmail.com

**Comment by concuacon** [comment]
@vkhalids I sent it to you via wetransfer, please check your mailbox.

**Comment by concuacon** [comment]
@vkhalids Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
