### ISSUE TITLE
[Fluxstore-Multi Vendor] -exception:  invalid access, 'unverifiable nounce' value .use 'get_nounce' core API method method

### ISSUE THREAD

**Issue by incepio-flutter** [inspireui/support#1402]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue
Hello, I have purchased flux store multi vendor because I want an app with multivendor support where different vendors can signup through the app and I am very disappointed that when I build the app on the sign up page I get this exception : "invalid access, 'unverifiable nounce' value .use 'get_nounce' core API method method" and even on the production app of inspireUI on playstore has the same exception. 

2. Screenshots
This app is downloaded from Playstore inspireUI production App! 
![1573914057313](https://user-images.githubusercontent.com/57838430/68995639-be1c9800-08b1-11ea-96ae-f80f23377fb1.JPEG)
I need to upload this app to app store by the end of this month so please help me setting up the multivendor support but first you need to fix your app on playstore, Sign Up page is not working !

3. My screenshot of the purchase product or my comment:
![1573911414962](https://user-images.githubusercontent.com/57838430/68995662-020f9d00-08b2-11ea-9c5a-0fec854f624e.JPEG)

4. Config files (optional)

**Comment by minhcasi** [comment]
@incepio-flutter  - thanks for your feedback, double-check with the highest priority 

@minhtruong315

**Comment by incepio-flutter** [comment]
did you check on it?  please I want to get it up and running

**Comment by minhtruong315** [comment]
@incepio-flutter can you send me config.dart and admin account via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/1402

**Comment by minhtruong315** [comment]
You must install JSON API to work with register, sign in
https://docs.inspireui.com/fluxstore/woocommerce-setup/

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
