### ISSUE TITLE
[BeoNews] - Numerous issues including onboarding not working and scrollToIndex error

### ISSUE THREAD

**Issue by TheCellMC** [inspireui/support#1405]
### My issue

So I'm running into multiple issues with the latest version of BeoNews.

1. Onboarding does not work, I never get the welcome screen when running the app for the first time. Additionally, when building the app as release in Xcode, I get this error:

```
Undefined symbols for architecture arm64:
  "_RCTSetLogFunction", referenced from:
      -[beonewsTests testRendersWelcomeScreen] in beonewsTests.o
ld: symbol(s) not found for architecture arm64
```

I think that might be related. This issue is also present on your BeoFoods app published in the AppStore.

2. On the homepage, when selecting a post in a list, most of the time the first post in the category opens instead of the one selected. This seems to happen when clicking on posts straight after opening the app, however, after playing around a little, this issue temporarily disappears until I reload the app. This issue is also present on your BeoFoods app published in the AppStore.

Sometimes, when running the Xcode debug version of the app, this error appears instead. I believe that it is related:

<details>
  <summary>App crash log (Click to expand) </summary>

 ```
Invariant Violation: scrollToIndex out of range: 3 vs 2

This error is located at:
    in PostDetail (created by ConnectFunction)
    in ConnectFunction (at PostDetailScreen.js:73)
    in PostDetailScreen (at SceneView.js:9)
    in SceneView (at createTabNavigator.js:39)
    in RCTView (at View.js:35)
    in View (at ResourceSavingScene.js:37)
    in RCTView (at View.js:35)
    in View (at ResourceSavingScene.js:26)
    in ResourceSavingScene (at createBottomTabNavigator.js:121)
    in RCTView (at View.js:35)
    in View (at screens.native.js:101)
    in ScreenContainer (at createBottomTabNavigator.js:111)
    in RCTView (at View.js:35)
    in View (at createBottomTabNavigator.js:110)
    in TabNavigationView (at createTabNavigator.js:197)
    in NavigationView (at createNavigator.js:61)
    in Navigator (at createAppContainer.js:429)
    in NavigationContainer (at RootRouter.js:160)
    in RCTView (at View.js:35)
    in View (at RootRouter.js:155)
    in RCTSafeAreaView (at SafeAreaView.js:54)
    in SafeAreaView (at RootRouter.js:154)
    in RCTView (at View.js:35)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at react-native-drawer/index.js:600)
    in RCTView (at View.js:35)
    in View (at react-native-drawer/index.js:587)
    in Drawer (at MenuSmall.js:40)
    in MenuSmall (at RootRouter.js:200)
    in RootRouter (created by ConnectFunction)
    in ConnectFunction (at beonews-pro/index.js:60)
    in PersistGate (at beonews-pro/index.js:59)
    in Provider (at beonews-pro/index.js:58)
    in beonews (at renderApplication.js:40)
    in RCTView (at View.js:35)
    in View (at AppContainer.js:98)
    in RCTView (at View.js:35)
    in View (at AppContainer.js:115)
    in AppContainer (at renderApplication.js:39)

scrollToIndex
    index.bundle?platform=ios&dev=true&minify=false:56895:18
scrollToIndex
    index.bundle?platform=ios&dev=true&minify=false:56506:38
componentWillReceiveProps
    index.bundle?platform=ios&dev=true&minify=false:203044:55
callComponentWillReceiveProps
    index.bundle?platform=ios&dev=true&minify=false:20927:45
updateClassInstance
    index.bundle?platform=ios&dev=true&minify=false:21116:42
updateClassComponent
    index.bundle?platform=ios&dev=true&minify=false:24022:45
invokeGuardedCallbackImpl
    index.bundle?platform=ios&dev=true&minify=false:15441:21
invokeGuardedCallback
    index.bundle?platform=ios&dev=true&minify=false:15537:42
beginWork$$1
    index.bundle?platform=ios&dev=true&minify=false:28469:34
performUnitOfWork
    index.bundle?platform=ios&dev=true&minify=false:27662:30
workLoopSync
    index.bundle?platform=ios&dev=true&minify=false:27644:45
renderRoot
    index.bundle?platform=ios&dev=true&minify=false:27499:29
renderRoot
    [native code]:0
runRootCallback
    index.bundle?platform=ios&dev=true&minify=false:27327:34
runRootCallback
    [native code]:0
flushImmediateQueueImpl
    index.bundle?platform=ios&dev=true&minify=false:19042:36
flushImmediateQueue
    index.bundle?platform=ios&dev=true&minify=false:19027:32
batchedUpdates$1
    index.bundle?platform=ios&dev=true&minify=false:27397:30
batchedUpdates
    index.bundle?platform=ios&dev=true&minify=false:16828:37
_receiveRootNodeIDEvent
    index.bundle?platform=ios&dev=true&minify=false:16885:23
receiveTouches
    index.bundle?platform=ios&dev=true&minify=false:16915:34
__callFunction
    index.bundle?platform=ios&dev=true&minify=false:7985:49
<unknown>
    index.bundle?platform=ios&dev=true&minify=false:7727:31
__guard
    index.bundle?platform=ios&dev=true&minify=false:7939:15
callFunctionReturnFlushedQueue
    index.bundle?platform=ios&dev=true&minify=false:7726:21
callFunctionReturnFlushedQueue
    [native code]:0
```

Here is a video of the error (notice at the start that the wrong post opens, but after playing around a little the issue stops occurring):
https://streamable.com/ipbbp

(you might need to wait a little for the video to load)

</details>

3. This is a feature request

When there is no internet connection, could we have a little red banner with the text "No internet connection" appear?

### Extra info
Proof of purchase: purchase code: 466044ee-d38a-46c8-a3ca-42703bbc6536

Environment info:
Building the app on iMac running macOS Catalina and testing the app on an iPhone X running iOS 13.3. Using the latest version of BeoNews (3.0.5) published on code canyon

**Comment by minhcasi** [comment]
@TheCellMC - thank you for the detail issue - we will investigate on this environment and will keep an update

**Comment by TheCellMC** [comment]
Hey, guys. Could I get an update on this issue? The main issue is the second one. When selecting a post on the home screen or in the categories section, the correct post does not always open. This is the main issue preventing me from publishing this app.

**Comment by concuacon** [comment]
@TheCellMC can you attach the screenshot of the problem?

**Comment by TheCellMC** [comment]
Here is a link to a video of the bug: https://streamable.com/ipbbp
Notice how the correct post does not always open.

**Comment by concuacon** [comment]
@TheCellMC I test with the last version, it works fine.
https://drive.google.com/file/d/1G-oNG5FR47lwhLjmHBxjlGY3bj3qjmlj/view?usp=sharing

**Comment by TheCellMC** [comment]
@concuacon 

Unfortunately, I am still running into this error. Here is a complete explanation of everything I did.
Downloaded BeoNews Pro from codecanyon
Unzipped the file
Opened terminal
Entered the command `cd (path to file)/beonews-pro`
Entered the command `yarn setup`
Entered the command `react-native run-ios`
Opened the BeoNews app in the Simulator.
Clicked on an article.
Noticed that the wrong article opened.

This issue seems to exist when opening the app initially, but goes away after opening an article and trying again. However, after closing the app in the App Switcher, the issue returns.

Here is another video of the issue: https://streamable.com/9b1e3
Could you try force-closing the app and reproducing the steps I took in the video. Notice how the second article would not open initially, but after opening the 3rd one it started to work.

**Comment by TheCellMC** [comment]
Here is the log of when the error occurs:

Invariant Violation: scrollToIndex out of range: 3 vs 2

```
This error is located at:
   in PostDetail (created by ConnectFunction)
   in ConnectFunction (at PostDetailScreen.js:73)
   in PostDetailScreen (at SceneView.js:9)
   in SceneView (at createTabNavigator.js:39)
   in RCTView (at View.js:35)
   in View (at ResourceSavingScene.js:37)
   in RCTView (at View.js:35)
   in View (at ResourceSavingScene.js:26)
   in ResourceSavingScene (at createBottomTabNavigator.js:121)
   in RCTView (at View.js:35)
   in View (at screens.native.js:101)
   in ScreenContainer (at createBottomTabNavigator.js:111)
   in RCTView (at View.js:35)
   in View (at createBottomTabNavigator.js:110)
   in TabNavigationView (at createTabNavigator.js:197)
   in NavigationView (at createNavigator.js:61)
   in Navigator (at createAppContainer.js:429)
   in NavigationContainer (at RootRouter.js:160)
   in RCTView (at View.js:35)
   in View (at RootRouter.js:155)
   in RCTSafeAreaView (at SafeAreaView.js:54)
   in SafeAreaView (at RootRouter.js:154)
   in RCTView (at View.js:35)
   in View (at createAnimatedComponent.js:151)
   in AnimatedComponent (at react-native-drawer/index.js:600)
   in RCTView (at View.js:35)
   in View (at react-native-drawer/index.js:587)
   in Drawer (at MenuSmall.js:40)
   in MenuSmall (at RootRouter.js:200)
   in RootRouter (created by ConnectFunction)
   in ConnectFunction (at beonews-pro/index.js:60)
   in PersistGate (at beonews-pro/index.js:59)
   in Provider (at beonews-pro/index.js:58)
   in beonews (at renderApplication.js:40)
   in RCTView (at View.js:35)
   in View (at AppContainer.js:98)
   in RCTView (at View.js:35)
   in View (at AppContainer.js:115)
   in AppContainer (at renderApplication.js:39)

scrollToIndex
   index.bundle?platform=ios&dev=true&minify=false:56895:18
scrollToIndex
   index.bundle?platform=ios&dev=true&minify=false:56506:38
componentWillReceiveProps
   index.bundle?platform=ios&dev=true&minify=false:203044:55
callComponentWillReceiveProps
   index.bundle?platform=ios&dev=true&minify=false:20927:45
updateClassInstance
   index.bundle?platform=ios&dev=true&minify=false:21116:42
updateClassComponent
   index.bundle?platform=ios&dev=true&minify=false:24022:45
invokeGuardedCallbackImpl
   index.bundle?platform=ios&dev=true&minify=false:15441:21
invokeGuardedCallback
   index.bundle?platform=ios&dev=true&minify=false:15537:42
beginWork$$1
   index.bundle?platform=ios&dev=true&minify=false:28469:34
performUnitOfWork
   index.bundle?platform=ios&dev=true&minify=false:27662:30
workLoopSync
   index.bundle?platform=ios&dev=true&minify=false:27644:45
renderRoot
   index.bundle?platform=ios&dev=true&minify=false:27499:29
renderRoot
   [native code]:0
runRootCallback
   index.bundle?platform=ios&dev=true&minify=false:27327:34
runRootCallback
   [native code]:0
flushImmediateQueueImpl
   index.bundle?platform=ios&dev=true&minify=false:19042:36
flushImmediateQueue
   index.bundle?platform=ios&dev=true&minify=false:19027:32
batchedUpdates$1
   index.bundle?platform=ios&dev=true&minify=false:27397:30
batchedUpdates
   index.bundle?platform=ios&dev=true&minify=false:16828:37
_receiveRootNodeIDEvent
   index.bundle?platform=ios&dev=true&minify=false:16885:23
receiveTouches
   index.bundle?platform=ios&dev=true&minify=false:16915:34
__callFunction
   index.bundle?platform=ios&dev=true&minify=false:7985:49
<unknown>
   index.bundle?platform=ios&dev=true&minify=false:7727:31
__guard
   index.bundle?platform=ios&dev=true&minify=false:7939:15
callFunctionReturnFlushedQueue
   index.bundle?platform=ios&dev=true&minify=false:7726:21
callFunctionReturnFlushedQueue
   [native code]:0
```

**Comment by concuacon** [comment]
@TheCellMC You can test with the BeoNews app expo version it works expected of you.

**Comment by TheCellMC** [comment]
@concuacon So it works with the Expo Version, just not the Pro version.

**Comment by concuacon** [comment]
@TheCellMC I'll update it to the next version.

**Comment by mariod3w** [comment]
Thanks @TheCellMC I have the same issues.

@concuacon @minhcasi Please fix this bug ASAP

We are use PRO VERSION, because we are integrating native functions.

I'm going very wrong with my client because of you. If you do not solve as soon as possible I will give you a very bad rating.

`purchase code: 0ae1e50c-de3f-4014-9b8c-34467df0b630
`

**Comment by minhcasi** [comment]
@mariod3w @TheCellMC - could I know which the Android version that you are testing? Thanks

**Comment by minhcasi** [comment]
Just confirm this is a bug on Android, it's ok with on iOS both Expo and Pro version - the team is working on this issue and will update your shortly as highest priority - thanks

**Comment by mariod3w** [comment]
Android 9

![Screenshot_20191127-075503_Settings](https://user-images.githubusercontent.com/4671301/69729489-0460cb00-10ec-11ea-81ca-913a0295a724.jpg)

![Screenshot_20191127-075513_Settings](https://user-images.githubusercontent.com/4671301/69729515-12165080-10ec-11ea-9ef2-4b64169485c6.jpg)

**Comment by TheCellMC** [comment]
Well I haven’t tested this on Android, but I am experiencing the bug on iOS with BeoNews Pro (expo version works just fine). I am testing it on an iPhone X (both simulated and externally) running iOS 13.2

**Comment by paulica40** [comment]
have the same issue on ios 13, both simulated and externally. if you first try to open an article  formm categories, or from the home page, it opens the wrong article. after opening anoter article, it goes ok, but this is kind of annoying

**Comment by mariod3w** [comment]
Hello @minhcasi @concuacon 

Do you have any news about the update that resolves the errors?

we already overcome our deadline

Thanks.

**Comment by minhcasi** [comment]
We fixed this issue, try the latest 3.0.6 - thanks

**Comment by TheCellMC** [comment]
I can confirm that this issue has been solved, I no longer get the scrollToIndex error. Thanks!

However, the following two issues still need to be addressed:

1. Onboarding does not work, I never get the welcome screen when running the app for the first time. Additionally, when building the app as release in Xcode, I get this error:

```
Undefined symbols for architecture arm64:
  "_RCTSetLogFunction", referenced from:
      -[beonewsTests testRendersWelcomeScreen] in beonewsTests.o
ld: symbol(s) not found for architecture arm64
```
2. This is a feature request

When there is no internet connection, could we have a little red banner with the text "No internet connection" appear?

3. Also, is it possible to show a web view of a post article, instead of trying to only display the text with edited fonts? Some of the fonts look rather weird (mostly lists), and buttons inserted from Wordpress's Gutenberg editor don't appear in the app (they appear as text and the link does not work).

Look at this page for example:
Website on desktop:
![Screenshot 2019-11-28 at 19 36 52](https://user-images.githubusercontent.com/12169936/69827343-49355080-1217-11ea-8a1b-5935d0d932e0.png)

What we see in the app:
![IMG_4C32DC745CCE-1](https://user-images.githubusercontent.com/12169936/69827365-610cd480-1217-11ea-9fbf-1a2f73a0a19d.jpeg)

**Comment by concuacon** [comment]
@TheCellMC  okay, can you give me your skype, I'll remote to check for you.

**Comment by TheCellMC** [comment]
The trouble with trying to organise a Skype is that I live in an entirely different time zone (Europe) so it will be difficult to arrange this.

Could you just point me to how I can customise the fonts in the app?
And is it normal that onboading does not work?

**Comment by minhcasi** [comment]
@TheCellMC  - pls check this detailed guide to add new fonts  - https://medium.com/@kswanie21/custom-fonts-in-react-native-tutorial-for-ios-android-76ceeaa0eb78

@concuacon - pls check the onboarding screens issue

**Comment by TheCellMC** [comment]
@minhcasi So I've discovered another issue. Neither videos, nor the custom pages load with the BeoNews EXPO app (tested on iOS). Could you try on your side using the latest version of BeoNews Expo (I could share a screenshot but all you see is a black image when selecting to play a video (the thumbnail loads with the circle play button, just when clicking on it, the video preview turns black, and a white page when selecting 'Contact' or 'About Us'). I would really like this fixed as QUICKLY as possible, given that it is heavily slowing down my work on this project. I'm encountering this issue with the DEFAULT config (and also when changing it to reflect my website).

**Comment by TheCellMC** [comment]
Here is a video of the 2 bugs:

- Custom pages not loading

- Videos not loading

https://streamable.com/6b7hu

**Comment by TheCellMC** [comment]
In addition, in file `Components/LeftMenu/Base.js`, I see this comment in the code:
```
    // you can also use custom page by using
    // this.goToScreen('customPage', {url: 'http://inspireui.com'});
```
 Based on this comment, I would suppose that it is possible to show any webpage by replacing, for example:
```
  goToAbout = () => {
    this.goToScreen('customPage', {
      url: Config.CustomPages.aboutus_id,
      title: Languages.aboutus,
    })
  }
```
with:
```
  goToAbout = () => {
    this.goToScreen('customPage', {url: 'http://inspireui.com'});
  }
```

However, that still gives my a white page in the app when selecting the About tab.

**Comment by TheCellMC** [comment]
@minhcasi @concuacon Could someone please take a look at this?
