### ISSUE TITLE
[MStorePro] - Signing Up problem

### ISSUE THREAD

**Issue by juniortimeline** [inspireui/support#1406]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. After Sign Up, showing pop up "Welcomeback : undifined" and I check wordpress users list and the user I sign up is not listed.

2. Screenshots

3. https://codecanyon.net/comments/23173559

3. Config files (optional)

**Comment by minhcasi** [comment]
#1407 - issues: After I tap review, Just loading a little bit then not show anything, just blank.

@juniortimeline - pls try to share your attach config file from common/AppConfig.json and config.js - thanks

@concuacon - pls help for checking

**Comment by juniortimeline** [comment]
@minhcasi @concuacon @luyx2412 @vumanhsn97  Thans for quick response here is my AppConfig,json and config.js https://drive.google.com/drive/folders/1NZFV6iLrHpqM7teO-uZlJU-3Jn3t3QJP?usp=sharing

**Comment by juniortimeline** [comment]
> #1407 - issues: After I tap review, Just loading a little bit then not show anything, just blank.
> 
> @juniortimeline - pls try to share your attach config file from common/AppConfig.json and config.js - thanks
> 
> @concuacon - pls help for checking

@minhcasi I already sent to minhcasi@gmail.com I appreciate.

**Comment by concuacon** [comment]
@juniortimeline Download file WPUserAPI.js, replace file WPUserAPI.js in the path (src/services/WPUserAPI.js ) and update Mstore API plugin to the last version. 
[WPUserAPI.js.zip](https://github.com/inspireui/support/files/3862996/WPUserAPI.js.zip)
Hope that help you.

**Comment by juniortimeline** [comment]
> @juniortimeline Download file WPUserAPI.js, replace file WPUserAPI.js in the path (src/services/WPUserAPI.js ) and update Mstore API plugin to the last version.
> [WPUserAPI.js.zip](https://github.com/inspireui/support/files/3862996/WPUserAPI.js.zip)
> Hope that help you.

@concuacon Thank you so much and Sign Up problem is already fix but the review is still not working https://drive.google.com/file/d/15xWFVVyizMybb4SaRoPfFGDnrYDzko2G/view?usp=sharing Thanks and I appreciate.

**Comment by concuacon** [comment]
Hello @juniortimeline 
You need to go to the admin page to approve that rating for it to show.

**Comment by juniortimeline** [comment]
> Hello @juniortimeline
> You need to go to the admin page to approve that rating for it to show.

@concuacon Hi if you watch my screen record have a 2 kinds of problem.

1. Customer can not able to post review
2. Review is blank and even the word of "There is no review this product yet." is not display. Thanks

**Comment by concuacon** [comment]
@juniortimeline 
1. No, I mean you must go to Comments to approve a review, 
2. Give me your email, I send you a new file.
<img width="412" alt="Screen Shot 2019-11-21 at 1 52 51 PM" src="https://user-images.githubusercontent.com/11958061/69314333-75c0f980-0c66-11ea-8a38-48502a70e389.png">

**Comment by juniortimeline** [comment]
> @juniortimeline
> 
> 1. No, I mean you must go to Comments to approve a review,
> 2. Give me your email, I send you a new file.
> 
> <img alt="Screen Shot 2019-11-21 at 1 52 51 PM" width="412" src="https://user-images.githubusercontent.com/11958061/69314333-75c0f980-0c66-11ea-8a38-48502a70e389.png">

Thanks for response and here is my email address juniortimeline@yahoo.com

**Comment by concuacon** [comment]
@juniortimeline I sent it to you via wetransfer, please check your mailbox.

**Comment by juniortimeline** [comment]
> @juniortimeline I sent it to you via wetransfer, please check your mailbox.

@concuacon I appreciate but still not working. I remove my old src folder and I change from your link but review still the same. Thanks

**Comment by paddykily** [comment]
@juniortimeline I'm having the same issue.

**Comment by minhcasi** [comment]
Reopen the ticket for further investigating - thank you!

**Comment by concuacon** [comment]
@juniortimeline Have you approved the comment yet?

**Comment by juniortimeline** [comment]
> @juniortimeline Have you approved the comment yet?

I'm still waiting for update and solution to this issue. The problem is still exist. Thanks

**Comment by concuacon** [comment]
@juniortimeline Please answer me when you add a review do you go to the admin page to approve it as I said? If you do not approve, how can it be displayed?

**Comment by concuacon** [comment]
> @juniortimeline
> 
> 1. No, I mean you must go to Comments to approve a review,
> 2. Give me your email, I send you a new file.
> 
> <img alt="Screen Shot 2019-11-21 at 1 52 51 PM" width="412" src="https://user-images.githubusercontent.com/11958061/69314333-75c0f980-0c66-11ea-8a38-48502a70e389.png">

@juniortimeline

**Comment by juniortimeline** [comment]
> @juniortimeline Please answer me when you add a review do you go to the admin page to approve it as I said? If you do not approve, how can it be displayed?

Yes - http://prntscr.com/q37r2r

**Comment by concuacon** [comment]
@juniortimeline can I remote to desktop to check?

**Comment by concuacon** [comment]
> @juniortimeline
> 
> 1. No, I mean you must go to Comments to approve a review,
> 2. Give me your email, I send you a new file.
> 
> <img alt="Screen Shot 2019-11-21 at 1 52 51 PM" width="412" src="https://user-images.githubusercontent.com/11958061/69314333-75c0f980-0c66-11ea-8a38-48502a70e389.png">

No, Please read again my comment, I don't mean config it in the setting but in the Comments category as the picture I attached, please do as I suggested

**Comment by juniortimeline** [comment]
> > @juniortimeline
> > 
> > 1. No, I mean you must go to Comments to approve a review,
> > 2. Give me your email, I send you a new file.
> > 
> > <img alt="Screen Shot 2019-11-21 at 1 52 51 PM" width="412" src="https://user-images.githubusercontent.com/11958061/69314333-75c0f980-0c66-11ea-8a38-48502a70e389.png">
> 
> No, Please read again my comment, I don't mean config it in the setting but in the Comments category as the picture I attached, please do as I suggested

1. Customer can not able to post review
Review is blank and even the word of "This product don't have any reviews ... yet" is not display. Thanks

**Comment by concuacon** [comment]
I am not saying that customers are entitled to approve the review but you have to go to admin to approve customer reviews to avoid product spam. This is a mechanism of Wordpress, you don't understand what I mean? Why does the same source I send you the customer to use ok and you do not? If so you add me Skype (pvtuan1707), will remote and check for you.

**Comment by minhcasi** [comment]
@juniortimeline - any update on your side, is this resolved?

**Comment by juniortimeline** [comment]
> @juniortimeline - any update on your side, is this resolved?

@minhcasi not yet Im still waiting. Thanks

**Comment by juniortimeline** [comment]
@minhcasi @concuacon @luyx2412 @vumanhsn97  Please follow Up. Thanks

**Comment by minhcasi** [comment]
@concuacon - remind

**Comment by juniortimeline** [comment]
@concuacon kindly please check my message on your skype because I do have a critical error and the way how I run and build my apk now is not working after our teamviewer. Thanks and I appreciate.
