### ISSUE TITLE
[fluxstore] - Build failed

### ISSUE THREAD

**Issue by mk4full** [inspireui/support#1408]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue

Hello, what i did wrong? Thank u for help.

> * What went wrong:

Execution failed for task ':app:validateSigningRelease'.

> Keystore file 'C:\src\FluxStore-woo 1.5.8\source\android\app\Users\admin\Documents\MyProjects\flutter-mstore\certs\key.jks' not found for signing config 'release'.

* Try:

Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full 

> insights.

2. Screenshots

3. My screenshot of the purchase product or my comment:

https://ibb.co/6XZMBBd

**Comment by minhcasi** [comment]
Hi, once you release as the final apk, it's required to create your own key to publish to googel play store - pls check these guide - https://flutter.dev/docs/deployment/android - thanks

**Comment by mk4full** [comment]
@minhcasi Thank you, I would like ask you for next help:

`C:\src\FluxStore-woo 1.5.8\source>flutter build appbundle
'flutter' is not recognized as an internal or external command,
operable program or batch file.
`
