### ISSUE TITLE
[FluxStore] - Blog/posts don't load

### ISSUE THREAD

**Issue by mk4full** [inspireui/support#1409]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue

video: https://gofile.io/?c=oRDSWO Blog/posts don't load

2. Screenshots

video: https://gofile.io/?c=oRDSWO

3. My screenshot of the purchase product or my comment:
https://ibb.co/6XZMBBd

4. Config files (optional)
My cofing.dart here's https://gofile.io/?c=iijR4V

**Comment by minhcasi** [comment]
@mk4full - noted with checking - thanks

**Comment by vumanhsn97** [comment]
@mk4full fixed it on next version
https://tppr.me/HH53R
https://tppr.me/OsKZR

**Comment by minhcasi** [comment]
Fixed on latest 1.5.9 release - thank you!
