### ISSUE TITLE
[MStore Multi Vendor] Facebook Sign up not working correctly in Android Device 

### ISSUE THREAD

**Issue by Sandeep6699** [inspireui/support#141]
Required Info (please complete the following information):

    Product: MStore Multi Vendor - Complete React Native template for WooCommerce
    Your Purchased Code: 2650646b-3b3d-49b0-a603-ee7dfce3a510
    Purchase Date:
    2018-10-09 10:18:09 UTC

Username : sandeep6699

**Describe the bug**
Hi,

I have managed to upload the app on google play store. But facebook login is not able to happen. 

**Screenshots**

https://play.google.com/store/apps/details?id=com.GIG.GlobalIndianGrocers

**Comment by Sandeep6699** [comment]
Any update ?

**Comment by minhcasi** [comment]
Hi @Sandeep6699, this could related to some new policies update from Facebook that require some extra config from the Facebook App

We will check this issue when back to work on Wed, Happy new year :)

**Comment by thangvo9x** [comment]
> Hi @Sandeep6699, this could related to some new policies update from Facebook that require some extra config from the Facebook App
> 
> We will check this issue when back to work on Wed, Happy new year :)

Please refer @Sandeep6699

**Comment by Sandeep6699** [comment]
Any solution for this issue ?

**Comment by thangvo9x** [comment]
Hi. Please screenshot that issue help us. Thanks

**Comment by minhcasi** [comment]
Fixed on latest version v.1.2.0
