### ISSUE TITLE
[MStore Expo] Integrated Paypal is not working

### ISSUE THREAD

**Issue by rmsoftengine** [inspireui/support#1410]
Hello,
when I have added Paypal in my woo-commerce as a payment method, its appearing in the app. However when I click on it next after choosing the paypal as a payment method it shows a white screen and nothing happens..
Could you please help me with this?
Thanks
Rashed

**Comment by rmsoftengine** [comment]
I saw the example in the Video 
https://www.youtube.com/watch?v=MrDq3CqRphY
but where in my file I should set those?
Here is my purchase proof
![image](https://user-images.githubusercontent.com/22434913/69001422-cdadd800-08d5-11ea-998d-3b819a4ecd81.png)

**Comment by minhcasi** [comment]
@rmsoftengine - this video is used for the Fluxstore (Fultter project) - for the payment issue on Mstore, could you help to check if you are using the latest WP mstore-api plugin - https://wordpress.org/plugins/mstore-api/ (pls make sure the old mstore-check should be removed) - thanks

**Comment by dahmsh** [comment]
Peace be upon you have purchased the application and now I want to install it on Apple Astor and Google Play by the technical support for the application and is ready to pay installation fee

**Comment by rmsoftengine** [comment]
Hello @minhcasi  yes I am using latest mstore-api.

![image](https://user-images.githubusercontent.com/22434913/69004875-a70d9280-0911-11ea-8f96-1d67f9249c3c.png)

**Comment by rmsoftengine** [comment]
this is our codebase
https://gitlab.com/ardites/softengine-react-native/tree/dev1.0
you should have access to this branch.

**Comment by rmsoftengine** [comment]
I have also provided WP information in an email support@inspireui.com; ‎
Please help me sort out this as client is waiting for the solution for about 6 weeks now.

Thanks

**Comment by rmsoftengine** [comment]
Any Updates  @minhcasi @concuacon ?

**Comment by rmsoftengine** [comment]
Hello @minhcasi  waiting for over couple of days and with no updates so far.. I am really stuck now. I thought paypal should be working as it is. but looks like its not. Please try to give me an update. Otherwise I have to choose another template which works.
Thanks

**Comment by concuacon** [comment]
Hello @rmsoftengine If you have used the latest mstore-api, just go to Woocommerce -> Settings -> Payment to install PayPal, the video you watch is only for the Fluxstore app.
<img width="500" alt="Screen Shot 2019-11-20 at 11 14 28 AM" src="https://user-images.githubusercontent.com/11958061/69208793-851d4580-0b87-11ea-85cb-7ebba3f50e3a.png">

**Comment by rmsoftengine** [comment]
Hello @concuacon  I think you have not understand the issue or gone through my responses. Does it works for you???? 
I am using latest mstore-api. I am using live paypal account and my site is secure as well. Its been a while since I am struggling with your app. You should be more professional for supporting your product. Please check again and provide me information why its not working from my end.. I have given all my code and access to WP-ADMIN. you just replied the same thing what @minhcasi  told me after 3 day???

**Comment by concuacon** [comment]
@rmsoftengine 
I have checked and mailed to you, the problem is not in the installation of Paypal, nor in our code, but due to the payment process on your side, the user needs to log in to make payment via Paypal as in our demo, currently your code is not required to log in for payment so there is no token and customer id information so it is not possible to generate Paypal method.

**Comment by rmsoftengine** [comment]
Thanks for the information. i am going to test now with force enabling login and will see what happens afterwords.

**Comment by rmsoftengine** [comment]
Hello @minhcasi . Now it make sense. After making the changes it works fine with paypal.
