### ISSUE TITLE
[MStore Opencart - the complete react native e-commerce app] - build error

### ISSUE THREAD

**Issue by motolorar** [inspireui/support#1412]
ERROR
14:52
FATAL ERROR: Ineffective mark-compac
ERROR
14:52
ts near heap limit Allocation failed - JavaScript heap out of memory
ERROR
14:52
 1: 00007FF6BBC6DD8A v8::internal::GCIdleTimeHandler::GCIdleTimeHandler+4506
 2: 00007FF6BBC48886 node::MakeCallback+4534
 3: 00007FF6BBC49200 node_module_register+2032
 4: 00007FF6BBF630DE v8::internal::FatalProcessOutOfMemory+846
 5: 00007FF6BBF6300F v8::internal::FatalProcessOutOfMemory+639
 6: 00007FF6BC149804 v8::internal::Heap::MaxHeapGrowingFactor+9620
 7: 00007FF6BC1407E6 v8::internal::ScavengeJob::operator=+24550
 8: 00007FF6BC13EE3C v8::internal::ScavengeJob::operator=+17980
 9: 00007FF6BC13E305 v8::internal::ScavengeJob::operator=+15109
10: 00007FF6BC147C64 v8::internal::Heap::MaxHeapGrowingFactor+2548
11: 00007FF6BC271B2B v8::internal::Factory::AllocateRawWithImmortalMap+59
12: 00007FF6BC2745DD v8::internal::Factory::NewRawTwoByteString+77
13: 00007FF6BC2B97CB v8::internal::interpreter::BytecodeArrayIterator::done+5579
14: 00007FF6BC10BE29 v8::internal::interpreter::operator<<+54729
15: 00007FF6BC10A0C2 v8::internal::interpreter::operator<<+47202
16: 00007FF6BC1084FD v8::internal::interpreter::operator<<+40093
17: 00007FF6BC108CBE v8::internal::interpreter::operator<<+42078
18: 00007FF6BC10AFDE v8::internal::interpreter::operator<<+51070
19: 00007FF6BC1084FD v8::internal::interpreter::operator<<+40093
20: 00007FF6BC105538 v8::internal::interpreter::operator<<+27864
21: 00007FF6BC333AC6 v8::internal::WasmJs::Install+231750
22: 00007FF6BC3339BB v8::internal::WasmJs::Install+231483
23: 000003127E5DC721

**Comment by motolorar** [comment]
Where can I set up API requests URL?
my localhost url: http://127.0.0.1/opencart

**Comment by motolorar** [comment]
hi,my order detial:
Item ID : 23724703
Item Purchase Code : e50c8390-1ac7-413b-b6e6-80db8a0da690
Can you help me to fix it？

**Comment by minhcasi** [comment]
Hi, it require to set up as a virtual host on your local so that it can be connected from the simulator - pls check this similar guide https://www.youtube.com/watch?v=CEyfZmzBMTw&t=28s

**Comment by motolorar** [comment]
It can't set up as a custom host: http://localhost:8080/opencart?

**Comment by minhcasi** [comment]
@motolorar - it could not as from your simulator it could not reach to this URL - you can try to publish to real IP/hosting and try the connection - thank you! 

Let us know if you have any further issues - very best
