### ISSUE TITLE
[FluxStore] - Search does not work (Opencart)

### ISSUE THREAD

**Issue by Moostsv** [inspireui/support#1413]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: Opencart search does not work. (config.dart and config.json from the folder ... example \ opencart, the rest is unchanged) FluxStore 1.5.8, FluxStore 1.5.7.

2. Screenshots issues: https://pastenow.ru/79S1Q

3. Proof of my purchased: https://pastenow.ru/79QV9

3. Config files (optional)

**Comment by minhtruong315** [comment]
@Moostsv add my skype: minhtruong315. I will help you check via teamviewer

**Comment by minhcasi** [comment]
Closed to move to another support channel - pls reopen if you still have an issue - thank you!
