### ISSUE TITLE
[andalosian-flutter-app] - 

### ISSUE THREAD

**Issue by supportis** [inspireui/support#1414]
Hi
I have installed below module
>>
https://codecanyon.net/item/fluxstore-the-universal-woocommerce-magento-opencart-mobile-app-by-flutter-framework/24020929?_ga=2.60376173.1521471605.1574061651-172578664.1573025053But

on my below magento 2 website
>>
https://agency.andalosian.com

but when compile then getting "Class Magento\Framework\Api\SearchCriteria\CollectionProcessorInterface does not exist" error
>>
https://prnt.sc/pyeik1

So please help me

ThanksFluxstore Pro - Flutter E-commerce Full Apphttps://codecanyon.netأفضل متجر و محل هدايا في مكة و جدة | أندلوسيانhttps://agency.andalosian.comType a message

**Comment by minhcasi** [comment]
Hi, could you help to show your proof of purchased screenshot from http://codecayon.net/downloads - thanks

**Comment by supportis** [comment]
Hi. you can check it here
https://prnt.sc/pz00wd

**Comment by minhtruong315** [comment]
@supportis you can try to fix error on your website. We only support issues on app. We dont sell website

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
