### ISSUE TITLE
[fluxstore] - Skip Address & Review Tab on checkout page

### ISSUE THREAD

**Issue by Dhavalkatrodiya** [inspireui/support#1415]
1. My issue:

hi, i want to skip(disable) Address & Review Tab on checkout page.
my website only sells digital products so address is not required, 
Basically i only want "payment tab" on checkout page.
i can't able to remove them through flutter inspector.

2. Screenshots issues:
https://snipboard.io/eqG3zK.jpg

3. Proof of my purchased:
https://snipboard.io/6EgT7k.jpg

3. Config files (optional)

**Comment by minhcasi** [comment]
@Dhavalkatrodiya - pls try your best with this customization as modify the feature is out of our support scope, remove this address could cause blocking issue as the checkout screen

**Comment by Dhavalkatrodiya** [comment]
which means fluxstore is not made for digital products, right!

digital products wont requires shipping data(address etc.)
since after purchase user can download it right away.

**Comment by Dhavalkatrodiya** [comment]
can you give me the way to do this
https://snipboard.io/21q8Ik.jpg

how can i, go from checkout screen to direct payment screen

bypassing address & review.
plz show me the way

**Comment by minhcasi** [comment]
Ah sorry - I got your idea, the Download Product features is missing - noted for fixing on next 1.5.9 - thank you!

**Comment by Dhavalkatrodiya** [comment]
fantastic, plz make fluxstore fully compatible with digital downloadable products.
& when can i expect v1.5.9 release?

**Comment by minhcasi** [comment]
fixed on latest 1.5.9, we also note the config from this blog - https://medium.com/@inspireui/announcing-fluxstore-1-5-950e0165cab8
