### ISSUE TITLE
[my-product] - FluxStore Universal

### ISSUE THREAD

**Issue by govindh163** [inspireui/support#1416]
1. My issue:Country Is not getting Updated in webview Of checkout,

2. Screenshots issues:

See Here Country Must be India but not Update
 Select Address: https://user-images.githubusercontent.com/52994786/69052743-c7cb0a80-0a2d-11ea-9405-bed98d6910b9.jpg

 Address Image:  https://user-images.githubusercontent.com/52994786/69052534-46737800-0a2d-11ea-9c06-2a576eda0dd9.jpg

 Webview Image: https://user-images.githubusercontent.com/52994786/69052280-aae20780-0a2c-11ea-92e1-52d7a09cbad8.jpg

**Comment by minhcasi** [comment]
@govindh163 - could you help to share the proof of purchase screenshot from - http://codecayon.net/downloads - thanks
