### ISSUE TITLE
[Fluxstore Pro] - Translation issue 

### ISSUE THREAD

**Issue by Alnaggar94** [inspireui/support#1418]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:

I installed Fluxstore with Woocommerce and everything works fine except the translation.
I use English and Arabic language (WPML), The problem is on the home page when I change the language to Arabic it doesn't load the Arabic version of the product name (It show the Arabic version only in category page ). All the addon for WPML are installed:
WPML 
WPML String Translation 
WPML Translation Management 
WooCommerce Multilingual
WPML to WP API

2. Screenshots issues:

Vidoe for the issue ( https://imgur.com/a/HSfLV2j )
screenshots ( https://imgur.com/a/7mzH39U )

3. Proof of my purchased:

https://imgur.com/a/9TsYcIf

3. Config files (optional)
DART:
https://filebin.net/oyk533kunro7ntws/config.dart?t=zdqd0n7h

JASON:
https://filebin.net/lps4jfougsoetgyl/config.json?t=71xt8u7y

**Comment by Alnaggar94** [comment]
Simple  explanation after analyzing:

1. The top category:

I realized that it's manually, I translated the category using WPML and it gives me
The English category id: 29
The Arabic category id: 18
WPML creates different category id for each language but in the config.json there is only one category input meaning if I put the English category id the English category name will show on all languages as the English name no matter what language of the app you choose. 

I'm not a developer but I think you have to separate the category id for each language in config .json so it loads the right category language for the chosen language.

*screenshot for more explaining -  https://imgur.com/OAGIXxv
-----------------------------------------------------------------------------

2. Women and men collection:

When I choose the English language from the app it works fine but when I  change the app language to Arabic the title is empty and it loads the English product names version (I tried also to change the category id to the Arabic version without luck it shows only the English version of the products' names).

screenshots:
English language from the app - https://imgur.com/undefined
Arabic language from the app - https://imgur.com/a/VBmkaUT
------------------------------------------------------------------
summary

WPML creates different category id for each language but in the config.json there is only one category input, It works fine in the category tab the language of the category and product name change according to the chosen language in the app, the problem only in the home page.

It's a serious problem please fix it as soon as possible

**Comment by minhcasi** [comment]
@Alnaggar94 - thank you so much for the detail explain - we have noted as the bug for fixing as high priority - it will be ready in 1.5.9 - very best!

**Comment by Alnaggar94** [comment]
Keep up the good work, there is another translation issue when you place an order there is some translation missing from the i18n.dart file, only English text no other language input, could you please consider this also.

screenshot for easy understanding - https://imgur.com/s05CiK8

**Comment by Alnaggar94** [comment]
It’s 4 days until now, any updates??

**Comment by minhcasi** [comment]
@Alnaggar94 - we are working on the fixing, it will be available on this week v1.5.9 - this need more refactor code so will take us time, not a minor fix - thank you!

**Comment by minhcasi** [comment]
@Alnaggar94 - we have break the config.json to multi-file that match with the languages, please download latest 1.5.9 with this update and let us know if you have any further issues, thank you!
