### ISSUE TITLE
[FluxStore] - sort and filters

### ISSUE THREAD

**Issue by mk4full** [inspireui/support#1419]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
hello, I have different attributes in shop like a "color" or "tag" is it possible to add it to filters?
and another issue, why we are not sort by price and newest etc? It's poor now ;)

3. Proof of my purchased:

https://ibb.co/6XZMBBd

**Comment by minhcasi** [comment]
@mk4full - filter by attribute is quite complicated so that we did not implement it - note as a feature request for next improvement - thanks

**Comment by minhcasi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Sort and filters by Attribute](https://trello.com/c/CWkYkTQT/2-sort-and-filters-by-attribute)

**Comment by minhcasi** [comment]
we are closing the ticket and move this ticket 'request feature' to our Trello board for easier to keep track, review, and update, also keep a status update  - thank you!
