### ISSUE TITLE
BUILD FAILED in 3m 3s Finished with error: Gradle task assembleDebug failed with exit code 1

### ISSUE THREAD

**Issue by Buzzisha** [inspireui/support#1421]
ing a method named 'KoukiconsLowVol'.
        return KoukiconsLowVol(width: width, height: height, color: color);
               ^^^^^^^^^^^^^^^
lib/widgets/koukicons.dart:1516:16: Error: The method 'KoukiconsLowVol2' isn't defined for the class 'KoukIcons'.
 - 'KoukIcons' is from 'package:fstore/widgets/koukicons.dart' ('lib/widgets/koukicons.dart').
Try correcting the name to the name of an existing method, or defining a method named 'KoukiconsLowVol2'.
        return KoukiconsLowVol2(width: width, height: height, color: color);
               ^^^^^^^^^^^^^^^^
lib/widgets/koukicons.dart:1518:16: Error: The method 'KoukiconsMagic' isn't defined for the class 'KoukIcons'.
 - 'KoukIcons' is from 'package:fstore/widgets/koukicons.dart' ('lib/widgets/koukicons.dart').
Try correcting the name to the name of an existing method, or defining a method named 'KoukiconsMagic'.
        return KoukiconsMagic(width: width, height: height, color: color);
               ^^^^^^^^^^^^^^
lib/widgets/koukicons.dart:1520:16: Error: The method 'KoukiconsMagnet1' isn't defined for the class 'KoukIcons'.
 - 'KoukIcons' is from 'package:fstore/widgets/koukicons.dart' ('lib/widgets/koukicons.dart').
Try correcting the name to the name of an existing method, or defining a method named 'KoukiconsMagnet1'.
        return KoukiconsMagnet1(width: width, height: height, color: color);
               ^^^^^^^^^^^^^^^^
lib/widgets/koukicons.dart:1522:16: Error: The method 'KoukiconsMagnet2' isn't defined for the class 'KoukIcons'.
 - 'KoukIcons' is from 'package:fstore/widgets/koukicons.dart' ('lib/widgets/koukicons.dart').
Try correcting the name to the name of an existing method, or defining a method named 'KoukiconsMagnet2'.
        return KoukiconsMagnet2(width: width, height: height, color: color);
               ^^^^^^^^^^^^^^^^
lib/widgets/koukicons.dart:1524:16: Error: The method 'KoukiconsMagnet3' isn't defined for the class 'KoukIcons'.
 - 'KoukIcons' is from 'package:fstore/widgets/koukicons.dart' ('lib/widgets/koukicons.dart').
Try correcting the name to the name of an existing method, or defining a method named 'KoukiconsMagnet3'.
        return KoukiconsMagnet3(width: width, height: height, color: color);
               ^^^^^^^^^^^^^^^^
lib/widgets/koukicons.dart:1526:16: Error: The method 'KoukiconsMakeDecision' isn't defined for the class 'KoukIcons'.
 - 'KoukIcons' is from 'package:fstore/widgets/koukicons.dart' ('lib/widgets/koukicons.dart').
Try correcting the name to the name of an existing method, or defining a method named 'KoukiconsMakeDecision'.
        return KoukiconsMakeDecision(
               ^^^^^^^^^^^^^^^^^^^^^
lib/widgets/koukicons.dart:1529:16: Error: The method 'KoukiconsManager' isn't defined for the class 'KoukIcons'.
 - 'KoukIcons' is from 'package:fstore/widgets/koukicons.dart' ('lib/widgets/koukicons.dart').
Try correcting the name to the name of an existing method, or defining a method named 'KoukiconsManager'.
        return KoukiconsManager(width: width, height: height, color: color);
               ^^^^^^^^^^^^^^^^
lib/widgets/koukicons.dart:1531:16: Error: The method 'KoukiconsMap' isn't defined for the class 'KoukIcons'.
 - 'KoukIcons' is from 'package:fstore/widgets/koukicons.dart' ('lib/widgets/koukicons.dart').
Try correcting the name to the name of an existing method, or defining a method named 'KoukiconsMap'.
        return KoukiconsMap(width: width, height: height, color: color);
               ^^^^^^^^^^^^
lib/widgets/koukicons.dart:1533:16: Error: The method 'KoukiconsMap2' isn't defined for the class 'KoukIcons'.
 - 'KoukIcons' is from 'package:fstore/widgets/koukicons.dart' ('lib/widgets/koukicons.dart').
Try correcting the name to the name of an existing method, or defining a method named 'KoukiconsMap2'.
        return KoukiconsMap2(width: width, height: height, color: color);
               ^^^^^^^^^^^^^
lib/widgets/koukicons.dart:1535:16: Error: The method 'KoukiconsMapLocation' isn't defined for the class 'KoukIcons'.
 - 'KoukIcons' is from 'package:fstore/widgets/koukicons.dart' ('lib/widgets/koukicons.dart').
Try correcting the name to the name of an existing method, or defining a method named 'KoukiconsMapLocation'.
        return KoukiconsMapLocation(width: width, height: height, color: color);
               ^^^^^^^^^^^^^^^^^^^^
lib/widgets/koukicons.dart:1537:16: Error: The method 'KoukiconsMediumPriority' isn't defined for the class 'KoukIcons'.
 - 'KoukIcons' is from 'package:fstore/widgets/koukicons.dart' ('lib/widgets/koukicons.dart').
Try correcting the name to the name of an existing method, or defining a method named 'KoukiconsMediumPriority'.
        return KoukiconsMediumPriority(
               ^^^^^^^^^^^^^^^^^^^^^^^
lib/widgets/koukicons.dart:1540:16: Error: The method 'KoukiconsMedVol' isn't defined for the class 'KoukIcons'.
 - 'KoukIcons' is from 'package:fstore/widgets/koukicons.dart' ('lib/widgets/koukicons.dart').
Try correcting the name to the name of an existing method, or defining a method named 'KoukiconsMedVol'.
        return KoukiconsMedVol(width: width, height: height, color: color);
               ^^^^^^^^^^^^^^^
lib/widgets/koukicons.dart:1542:16: Error: The method 'KoukiconsMedVol2' isn't defined for the class 'KoukIcons'.
 - 'KoukIcons' is from 'package:fstore/widgets/koukicons.dart' ('lib/widgets/koukicons.dart').
Try correcting the name to the name of an existing method, or defining a method named 'KoukiconsMedVol2'.
        return KoukiconsMedVol2(width: width, height: height, color: color);
               ^^^^^^^^^^^^^^^^
lib/widgets/koukicons.dart:1544:16: Error: The method 'KoukiconsMenu' isn't defined for the class 'KoukIcons'.
 - 'KoukIcons' is from 'package:fstore/widgets/koukicons.dart' ('lib/widgets/koukicons.dart').
Try correcting the name to the name of an existing method, or defining a method named 'KoukiconsMenu'.
        return KoukiconsMenu(width: width, height: height, color: color);
               ^^^^^^^^^^^^^
lib/widgets/koukicons.dart:1546:16: Error: The method 'KoukiconsMenu2' isn't defined for the class 'KoukIcons'.
 - 'KoukIcons' is from 'package:fstore/widgets/koukicons.dart' ('lib/widgets/koukicons.dart').
Try correcting the name to the name of an existing method, or defining a method named 'KoukiconsMenu2'.
        return KoukiconsMenu2(width: width, height: height, color: color);
               ^^^^^^^^^^^^^^

Try correcting the name to the name of an existing method, or defining a method named 'Padding'.
      child: Padding(
             ^^^^^^^
lib/screens/detail/review.dart:171:38: Error: Too many positional arguments: 0 allowed, but 1 found.
Try removing the extra positional arguments.
        padding: const EdgeInsets.all(10.0),
                                     ^
lib/screens/detail/review.dart:172:16: Error: The method 'Column' isn't defined for the class '_StateReviews'.
 - '_StateReviews' is from 'package:fstore/screens/detail/review.dart' ('lib/screens/detail/review.dart').
Try correcting the name to the name of an existing method, or defining a method named 'Column'.
        child: Column(
               ^^^^^^
lib/screens/detail/review.dart:173:31: Error: The getter 'CrossAxisAlignment' isn't defined for the class '_StateReviews'.
 - '_StateReviews' is from 'package:fstore/screens/detail/review.dart' ('lib/screens/detail/review.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'CrossAxisAlignment'.
          crossAxisAlignment: CrossAxisAlignment.start,
                              ^^^^^^^^^^^^^^^^^^
lib/screens/detail/review.dart:175:13: Error: The method 'Row' isn't defined for the class '_StateReviews'.
 - '_StateReviews' is from 'package:fstore/screens/detail/review.dart' ('lib/screens/detail/review.dart').
Try correcting the name to the name of an existing method, or defining a method named 'Row'.
            Row(
            ^^^
lib/screens/detail/review.dart:176:34: Error: The getter 'MainAxisAlignment' isn't defined for the class '_StateReviews'.
 - '_StateReviews' is from 'package:fstore/screens/detail/review.dart' ('lib/screens/detail/review.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'MainAxisAlignment'.
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                 ^^^^^^^^^^^^^^^^^
lib/screens/detail/review.dart:178:17: Error: The method 'Text' isn't defined for the class '_StateReviews'.
 - '_StateReviews' is from 'package:fstore/screens/detail/review.dart' ('lib/screens/detail/review.dart').
Try correcting the name to the name of an existing method, or defining a method named 'Text'.
                Text(review.name, style: TextStyle(fontSize: 12, fontWeight: FontWeight.bold)),
                ^^^^
lib/screens/detail/review.dart:178:42: Error: The method 'TextStyle' isn't defined for the class '_StateReviews'.
 - '_StateReviews' is from 'package:fstore/screens/detail/review.dart' ('lib/screens/detail/review.dart').
Try correcting the name to the name of an existing method, or defining a method named 'TextStyle'.
                Text(review.name, style: TextStyle(fontSize: 12, fontWeight: FontWeight.bold)),
                                         ^^^^^^^^^
lib/screens/detail/review.dart:178:78: Error: The getter 'FontWeight' isn't defined for the class '_StateReviews'.
 - '_StateReviews' is from 'package:fstore/screens/detail/review.dart' ('lib/screens/detail/review.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'FontWeight'.
                Text(review.name, style: TextStyle(fontSize: 12, fontWeight: FontWeight.bold)),
                                                                             ^^^^^^^^^^
lib/screens/detail/review.dart:189:13: Error: The method 'SizedBox' isn't defined for the class '_StateReviews'.
 - '_StateReviews' is from 'package:fstore/screens/detail/review.dart' ('lib/screens/detail/review.dart').
Try correcting the name to the name of an existing method, or defining a method named 'SizedBox'.
            SizedBox(height: 10),
            ^^^^^^^^
lib/screens/detail/review.dart:190:13: Error: The method 'Text' isn't defined for the class '_StateReviews'.
 - '_StateReviews' is from 'package:fstore/screens/detail/review.dart' ('lib/screens/detail/review.dart').
Try correcting the name to the name of an existing method, or defining a method named 'Text'.
            Text(review.review, style: TextStyle(color: kGrey600, fontSize: 14)),
            ^^^^
lib/screens/detail/review.dart:190:40: Error: The method 'TextStyle' isn't defined for the class '_StateReviews'.
 - '_StateReviews' is from 'package:fstore/screens/detail/review.dart' ('lib/screens/detail/review.dart').
Try correcting the name to the name of an existing method, or defining a method named 'TextStyle'.
            Text(review.review, style: TextStyle(color: kGrey600, fontSize: 14)),
                                       ^^^^^^^^^
lib/screens/detail/review.dart:191:13: Error: The method 'SizedBox' isn't defined for the class '_StateReviews'.
 - '_StateReviews' is from 'package:fstore/screens/detail/review.dart' ('lib/screens/detail/review.dart').
Try correcting the name to the name of an existing method, or defining a method named 'SizedBox'.
            SizedBox(height: 12),
            ^^^^^^^^
lib/screens/detail/review.dart:192:13: Error: The method 'Text' isn't defined for the class '_StateReviews'.
 - '_StateReviews' is from 'package:fstore/screens/detail/review.dart' ('lib/screens/detail/review.dart').
Try correcting the name to the name of an existing method, or defining a method named 'Text'.
            Text(timeago.format(review.createdAt),
            ^^^^
lib/screens/detail/review.dart:193:24: Error: The method 'TextStyle' isn't defined for the class '_StateReviews'.
 - '_StateReviews' is from 'package:fstore/screens/detail/review.dart' ('lib/screens/detail/review.dart').
Try correcting the name to the name of an existing method, or defining a method named 'TextStyle'.
                style: TextStyle(color: kGrey400, fontSize: 10))
                       ^^^^^^^^^
Compiler failed on C:\src\source\lib\main.dart

FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\Flutter\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 765

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebugX86'.
> Process 'command 'C:\src\Flutter\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 3s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by Sherbi** [comment]
Today I try to Build the new update 1.5.8 and it's the same issue 
![image](https://user-images.githubusercontent.com/2877217/69132284-74ec6400-0abc-11ea-9ec7-4d7ef5bd755f.png)

**Comment by minhcasi** [comment]
@Buzzisha - your build issue is caused by missing the Flutter Path config from Android Studio - pls check this guide - https://docs.inspireui.com/fluxstore/common-question/

@Sherbi - pls share your config file and post as a new ticket - the team will help for checking - thanks

**Comment by minhcasi** [comment]
Please keep update the ticket if you have any issues, also download latest 1.5.9 for the new update - thank you!
