### ISSUE TITLE
How to disable shipping / Create new menu item

### ISSUE THREAD

**Issue by patrickubong** [inspireui/support#1422]
My issues are:

1. Please guide me on how to disable shipping address, my products are virtual. But even when I try to enter some shipping address so I can proceed, it says "There's an issue with the app during request the data" Please I need to disable shipping

2. I want to add a menu that links to my-account dashboard, please provide guide on how to creat webview link to my dashboard:

3. When I do hot reload, it doesnt work for me and when it does, it continues to build with the same features even after I had made several changes. I always have to stop the App build and restart my PC before new changes is reflected in the build

4. I have shortcodes for visual composer and calculated fields form plugins on my page which do not show up, rather they only show the raw codes. Please how do I hide these codes on the App without necessarily deleting disabling the plugins from from my website

This is a great App, please keep it up.

**Comment by minhcasi** [comment]
@patrickubong  - could you help to share the proof purchase screenshot from http://codecayon.net/downloads

Also, share us your config file so that we could help for checking - thanks

**Comment by minhcasi** [comment]
no worries, it's verified - sent to email as well

1. Please disable the shipping from common/config.dart - EnableShipping: false

2. Just use this code when tap to the link
import '../../widgets/webview.dart';
Navigator.push(
    context,
    MaterialPageRoute(
        builder: (context) => WebView(
              url: 'your-account-url',
              title: '',
            )));

3. you can try to re-install and Android Studio and Flutter plugin that support well for hot reload, could be some missing on your PC - pls double check the guide from https://flutter.dev/docs/development/tools/hot-reload

4. Pls check solution to render the shortcode from API before return to the app - https://github.com/WP-API/WP-API/issues/2578

Let us know your checking

**Comment by patrickubong** [comment]
Thanks for your guide so far. You have a great app and your documentations and video is so easy such that a complete novice to Flutter like myself finds it so easy and enjoyable. However, I need a little more resolution to get my app ready for release:

ISSUES:
1. Checkout displays white screen after Payment Gateway selection. I am using the Payment Gateways installed on my woocommerce website 
2. My blog link https://payfarmer.com/farm-news does not display even after entering in the config.dart file
3. Which file do I edit to add About Us and Contact Us links to the Drawer Menu and also in the Settings Menu. The About us will point to a file in within the app while the contact us will be webview to our contact us Page
4. I configured my config.dart to show isCache:true but when I uploaded my config.json, I get blank white screen after app built



My debug app, config.dart and config.json files are attached in this link:

**Comment by minhcasi** [comment]
@patrickubong - could you share the configs file again as we could not get it :)

**Comment by patrickubong** [comment]
Thanks for the previous issue. It was really helpful. Your app is so easy to use and configure even for complete novice.
However, I have encountered some more issues
1. I have disabled Shipping and app works fine but when I get to checkout and select payment gateway, it gives me a blank white screen (my payment gateway is the one integrated on my woocommerce site)
2. When I enable caching through isCache: true and upload my config.json I get a blank white screen and app doesn't load
3. I added my blog page but My blog page https://payfarmer.com/farm-news does not show on the app when built.
4. I also made changes to res/value/settings_en_arb but its not reflecting. I need to change all occurrences of products to investments
5. I want to add About Us and Contact Us link/page on the Drawer Menu and on the Settings page, please advise on the files I need to change 
6. I have added a zipped file to my apk, config.js and config.dart
[Fluxstore config files.zip](https://github.com/inspireui/support/files/3875120/Fluxstore.config.files.zip)

Dropbox link: https://www.dropbox.com/s/gfsk3mxur5s7aeq/Fluxstore%20files.zip?dl=0

**Comment by minhcasi** [comment]
@patrickubong - thank you for the detail issues and kindly words.

I've forward to the team for double check the config and find out the bug, we will keep an update 

Very best!

**Comment by vumanhsn97** [comment]
@patrickubong 
1. This fixed on next version
2. when you enable cache, make sure you upload file look like your config.json file. You can check by url: https://payfarmer.com/wp-json/mstore/v1/cache
3. your blog url is: https://payfarmer.com. Some image in your media require: rest_forbidden so I cant get data image. https://tppr.me/tSUlE
4. Setup plugin wordpress multi language
5. You can add your code in lib/tabbar.dart. Add widget look like this https://tppr.me/8qvXt and navigator to webview or your widget.

**Comment by minhcasi** [comment]
@patrickubong - please try to download the latest version 1.5.9 and let us know if you have any issues, thank you!

**Comment by patrickubong** [comment]
Thank for being so supportive so far. 
You shared this code some days back, for me to add a link for webview to my account dashboard. 

import '../../widgets/webview.dart';
Navigator.push(
context,
MaterialPageRoute(
builder: (context) => WebView(
url: 'https://payfarmer.com/my-account',
title: '',
)));

Please tell me the exact file and the exact line to paste this code that I can have a link in Settings, under Order Details, so that logged in Users can connect to the Webview Dashboard to see their account information. I want to call that webview link **Account Dashboard**

Please also share your skype ID so I can connect to discuss further customization terms.

**Comment by vumanhsn97** [comment]
@patrickubong 
You can pass cookie to webview but webview not saving statement login in next page. So you need to login again in webview to connect your account. I dont know you want to go account dashboard for what. If you want to edit profile, dont worry. We will update it in next version. Thanks!

**Comment by patrickubong** [comment]
Thank you for your prompt reply always. We have a specially customized **My-Accounts Dashboard** as you can see in the photo attached. Profile Edit is fine for the next update but there are options that we added to our dashboard such as Withdraw or Re-Invest, so users need these options to complete transaction. This is why I want to point them to the Dashboard, I dont mind even if they have to log in again at webview, but for now we need it like that. Please help me with the code and guide

![my-account](https://user-images.githubusercontent.com/5703312/69849791-f478f080-127d-11ea-8a16-a3725427fe63.png)

Please give me your Skype or WhatsApp so that we can discuss more customizations for my App.
Thanks.

**Comment by patrickubong** [comment]
Please help me with this information so I can finally build my app for release. Which files do I make changes to, and at what line do I paste this code to add a menu item in the Settings Section and the Menu Link to my Account Dashboard.

import '../../widgets/webview.dart';
Navigator.push(
context,
MaterialPageRoute(
builder: (context) => WebView(
url: 'https://payfarmer.com/my-account',
title: '',
)));

My skype is patrickubong, please lets connect so I can make customization enquiries.

Thanks.

**Comment by vumanhsn97** [comment]
@patrickubong 
Sorry for late! You can add your code at line: https://tppr.me/AsIBd in lib/screens/settings.dart

**Comment by patrickubong** [comment]
Thanks. Everything worked perfectly and I have been able to publish to Google Playstore. Can we discuss customization? How do I reach you?

**Comment by vumanhsn97** [comment]
@patrickubong You can email to support@inspireui.com. Thanks!

**Comment by patrickubong** [comment]
I have sent the mail right away, hope to get reply immediately.
