### ISSUE TITLE
[MStore Expo] Can not register new account

### ISSUE THREAD

**Issue by ptyz030529** [inspireui/support#1425]
1. My issue:
when I register new account in app, I will get “REGISTER ERROR the error message “Cannot create a user with an empty login name.” ???
I have installed "JSON API v2.0" and "Mstore API v1.4.8".

2. Screenshots issues:
![plugin](https://user-images.githubusercontent.com/376845/69167267-a0f4fd00-0b2f-11ea-9cae-47c09b276e89.jpg)
![debug](https://user-images.githubusercontent.com/376845/69167292-ace0bf00-0b2f-11ea-95b9-86f2ff7d36df.png)

**Comment by minhcasi** [comment]
Hi @ptyz030529  - could you help to share the proof of you purchase screenshot from - http://codecayon.net/downloads - thank you!

**Comment by ptyz030529** [comment]
Hi here is my purchased proof

![TIM图片20191120231710](https://user-images.githubusercontent.com/376845/69251198-0a3a4600-0bec-11ea-8f71-00722749143e.png)

**Comment by concuacon** [comment]
Hello @ptyz030529 you can follow this link https://github.com/inspireui/support/issues/1406#issuecomment-555421606

**Comment by ptyz030529** [comment]
@concuacon It‘s ok for me， thank you so much
