### ISSUE TITLE
[Mstore Pro] - Generate Error APK in Android Studio

### ISSUE THREAD

**Issue by saeidAalizade** [inspireui/support#1426]
I can't see the output.
Error : Process 'command' 'cmd' finished with non-zero exit value 1
Please Help me

![68975806-78a49000-0809-11ea-9c7d-939237281b17](https://user-images.githubusercontent.com/41091634/69195493-0e5d5980-0b41-11ea-8db3-b2d13a0298b7.png)
![68975807-78a49000-0809-11ea-95c6-df1003d9d87b](https://user-images.githubusercontent.com/41091634/69195494-10271d00-0b41-11ea-8099-abe673dbb4aa.png)
![68975808-78a49000-0809-11ea-8207-8ca03a6eb22d](https://user-images.githubusercontent.com/41091634/69195495-10bfb380-0b41-11ea-864b-94589bf7f2ec.png)
![68975810-78a49000-0809-11ea-9782-8eaf2ada99a0](https://user-images.githubusercontent.com/41091634/69195496-10bfb380-0b41-11ea-890d-c1135d7c5e04.png)
![68975811-793d2680-0809-11ea-8cd6-30e7edd6d6f2](https://user-images.githubusercontent.com/41091634/69195497-10bfb380-0b41-11ea-8d11-4b4b441c0c22.png)

My screenshot of the purchase product or my comment:
153bb1ff-3f3e-41cd-a219-da061397aef5

**Comment by concuacon** [comment]
Hello @saeidAalizade You try to follow these steps: 

- Delete folder node_modules/

- Re-install: npm install

- Clean build android: cd android/ ; ./gradlew clean ; cd ../

- Run test: react-native run-android --variant=release
**Note: Follow docs of RN to build apk for release:** https://facebook.github.io/react-native/docs/signed-apk-android

**Comment by concuacon** [comment]
Hi, @saeidAalizade  I'm closing this ticket as there is no response after more than 2 days if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
