### ISSUE TITLE
[Fluxstore] - when disabling shipping in the application and you go to checkout in the review screen there is an option that lets you go back to shipping maybe you forgot about it .

### ISSUE THREAD

**Issue by ajnaf** [inspireui/support#1428]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:

2. Screenshots issues:

3. Proof of my purchased:

3. Config files (optional)

**Comment by minhcasi** [comment]
@ajnaf - thanks, we will check this case

**Comment by minhcasi** [comment]
@ajnaf  - pls help to download the latest version 1.5.9, we also upgrade the app to support Downloadable product, let us know if you have any questions

**Comment by ajnaf** [comment]
@minhcasi Thank you very much.
