### ISSUE TITLE
fluxstore can't move betwwen screnn

### ISSUE THREAD

**Issue by nizarweb77** [inspireui/support#1429]
W/FA      ( 3576): setCurrentScreen cannot be called with the same class and name
I/flutter ( 3576): [Product { id: 1105 name: 12554 }, Product { id: 1104 name: 52122112 }, Product { id: 1091 name: Toyota Land Cruiser }]
I/flutter ( 3576): [Product { id: 1105 name: 12554 }, Product { id: 1104 name: 52122112 }, Product { id: 1091 name: Toyota Land Cruiser }]
I/flutter ( 3576): [Product { id: 1105 name: 12554 }, Product { id: 1104 name: 52122112 }, Product { id: 1091 name: Toyota Land Cruiser }]
*************
this is my problem all the screen is blocked i need to force my click so that i can enter inside the screen 
: setCurrentScreen cannot be called with the same class and name

**Comment by minhcasi** [comment]
Hi, could you help to provide more detail info:
1. Screenshot of the issues + your config files, it seems the root cause by missing data config.
2. Proof of your purchased screenshot from http://codecayon.net/downloads 

Thank you!
