### ISSUE TITLE
[my-product] - search and account returns error message

### ISSUE THREAD

**Issue by mbilawisdom** [inspireui/support#1430]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:

2. Screenshots issues:

3. Proof of my purchased:

3. Config files (optional)

**Comment by minhcasi** [comment]
Hi, could you help to provide more detail info:

1. Screenshot of the issues + your config files, it seems the root cause by missing data config.
2. Proof of your purchased screenshot from http://codecayon.net/downloads

Thank you!
