### ISSUE TITLE
[listapp] - app Login try to  connect to mstore_user endpoint  

### ISSUE THREAD

**Issue by Metacowboy** [inspireui/support#1431]
![Screen Shot 2019-11-20 at 19 35 51](https://user-images.githubusercontent.com/1506060/69267276-17940800-0bcd-11ea-9773-93191815df14.jpg)
---------
App Login fail with message 
"cannot read property of 'id' undefined
_________________________________________
#1431 React-Native-debugger
Shows in network debug mode  
status: "error", error: "Unknown controller 'mstore_user'."}
error: "Unknown controller 'mstore_user'."
status: "error"

File : WordpressApi.js
The WP MyListing   don't have any REST controller with mstore_user

**Comment by minhcasi** [comment]
Hi @Metacowboy - pls enable this option to active the mstore_user controller - https://docs.inspireui.com/listapp/getting-started/#enable-the-rest-api-controller - thanks
