### ISSUE TITLE
[MStore Pro] - 15 Attributes show all on the product page instead show only variations

### ISSUE THREAD

**Issue by juniortimeline** [inspireui/support#1432]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: Any solution related to this comment 9 months ago https://codecanyon.net/comments/21573180 because I also facing this issue. 15 Attributes show all on the product page instead show only variations.

2. Screenshots issues: related http://prntscr.com/pzqzi2

3. Proof of my purchased: https://codecanyon.net/comments/23197672

3. Config files (optional)

**Comment by minhcasi** [comment]
@juniortimeline - you can try to filters the attribute list from the detail containers - https://tppr.me/23Ks3

**Comment by juniortimeline** [comment]
> @juniortimeline - you can try to filters the attribute list from the detail containers - https://tppr.me/23Ks3
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/368f22298a8bd191b09aa595b1951031760b5979/68747470733a2f2f747070722e73332e616d617a6f6e6177732e636f6d2f75706c6f6164732f64616637386465623931313662663436333430366430323239613138646239642e706e67"><img alt="" height="14" src="/favicon-32x32.png"> tppr.me**[Public Screenshots - Screenshot_2019-11-21 10-59-51](https://tppr.me/23Ks3)**

@minhcasi Thanks for the response but I did not understand to handle that code. Thanks

**Comment by minhcasi** [comment]
You can filters to pick only some categories you would like display - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter

// only get the attr that have id > 2
var newAttributes =  this.productAttributes.filters( attr => attr.id > 2);
