### ISSUE TITLE
[Mstore Pro] - Login Fails

### ISSUE THREAD

**Issue by priyanka284** [inspireui/support#1435]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: 

Kindly help asap. I cannot log in using the WP user credentials and so cannot proceed with the checkout. When clicked on login, the login screen just shows the spinner and nothing happens. 

I have the updated mstore-api plugin installed still nothing works.

2. Screenshots [issues:] Not applicable

3. Proof of my purchase:
I can email you the purchase key if needed( Kindly provide the email id)

![69214607-6457ee80-0b8d-11ea-8b49-706a1e7239fe](https://user-images.githubusercontent.com/44432949/69319910-1d89f780-0c66-11ea-9684-f5a7c6ee3e53.png)

3. Config files (optional)

**Comment by concuacon** [comment]
Hello, @priyanka284 I fixed it and will release it in the next version next week.

**Comment by priyanka284** [comment]
Hey @concuacon, thanks a lot for your prompt reply. I will be waiting for the new release.

**Comment by concuacon** [comment]
@priyanka284 Thank you.
