### ISSUE TITLE
[fluxstore] - home screen 

### ISSUE THREAD

**Issue by ajnaf** [inspireui/support#1436]
can i change the images on config.json file from the backend can you please tell me how . Thank you.

Proof of my purchased:
![image](https://user-images.githubusercontent.com/31656833/69336421-2c24de80-0c67-11ea-8888-f0cadd91b4f8.png)

**Comment by minhcasi** [comment]
Hi, pls check this guide for related config file - https://docs.inspireui.com/fluxstore/woocommerce-setup/#step-3-setup-fluxstore

**Comment by ajnaf** [comment]
@minhcasi i want to change the image from the backend when the app is on release mode is it possible?

**Comment by ajnaf** [comment]
![75407717_2235883640042378_1855264913677615104_n](https://user-images.githubusercontent.com/31656833/69367326-bb9ab380-0ca0-11ea-802a-232d376dfd1b.jpg)
i want to change these images

**Comment by vumanhsn97** [comment]
@ajnaf If you change image data without changing your url, the images in your home screen will change. But I dont find any website can publish image and change it without changing url. Thanks!

**Comment by minhcasi** [comment]
@ajnaf - you can upload the config.json from the wordpress into mstore-api, also enable the caching from the app, then one you update the banner from config.json it will update the app without uploading to store again.

We are working on new Builder to support config more dymanic and easily - will keep an update

If you have any question, just let us know - thank you!

**Comment by ajnaf** [comment]
@minhcasi i found a plugin in wordpress that was helpfull it lets you change the image while keeping the same url the name of the plugin is : (Enable Media Replace)
