### ISSUE TITLE
SDK Version Issue  & Font File Missing

### ISSUE THREAD

**Issue by khaja25** [inspireui/support#1437]
![WhatsApp Image 2019-11-21 at 6 40 45 PM](https://user-images.githubusercontent.com/58036762/69341727-1c6dc000-0c90-11ea-85c8-39915c322c90.jpeg)
![WhatsApp Image 2019-11-21 at 6 41 25 PM](https://user-images.githubusercontent.com/58036762/69341746-24c5fb00-0c90-11ea-9489-16a6493e6b04.jpeg)

**Comment by khaja25** [comment]
![WhatsApp Image 2019-11-21 at 6 41 11 PM](https://user-images.githubusercontent.com/58036762/69342033-b33a7c80-0c90-11ea-8ede-f5ea66f05d5a.jpeg)

**Comment by minhcasi** [comment]
@khaja25 

Thank you for your reaching. Could you help to share the purchased screenshot from http://codecayon.net/downloads ? Just want to verify your proof of purchase, sorry for any inconvenience - thank you!

**Comment by khaja25** [comment]
![Backandroid](https://user-images.githubusercontent.com/58036762/69539397-63b6c200-0faa-11ea-94c7-2614bc459b51.jpeg)
