### ISSUE TITLE
[Fluxstore] Magento 2 Configurable Products are Getting Displayed Separately.

### ISSUE THREAD

**Issue by Usman1493** [inspireui/support#1438]
I have configurable Products on my Magento 2 Store (lifestock.pk), I want them to display on the basis of mass attribute, but the each simple product is getting displayed separately.. 
Please help me through this,,

**Comment by minhcasi** [comment]
@Usman1493 - could you attach your screenshot issues + config files so that we could check the root cause of the issue - thank you!

**Comment by Usman1493** [comment]
I was able to fix that through changing the Config file. But Now I am facing a new problem. What I am want is to display the attribute of Mass Below each product. I have enabled Configurable Product in the Config file and also changed the product_variant Layout to "mass" in place of size but I don't know why it still shows the error. I am attaching few screenshots for reference. 

![WhatsApp Image 2019-11-24 at 19 10 04](https://user-images.githubusercontent.com/30326249/69533489-ba67d000-0f99-11ea-8cb5-4537be498712.jpeg)

This is my desired layout.

![WhatsApp Image 2019-11-24 at 19 11 40](https://user-images.githubusercontent.com/30326249/69533551-cf446380-0f99-11ea-8c5b-d865033fb244.jpeg)

**Comment by minhtruong315** [comment]
@Usman1493 can you send me config.dart, config.json and admin account via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/1438

**Comment by Usman1493** [comment]
Sure, Please check your email..

**Comment by minhcasi** [comment]
closed to support via email
