### ISSUE TITLE
[Fluxstore-Vendor] - Debugging issues...

### ISSUE THREAD

**Issue by BashBB** [inspireui/support#1439]
1. **My issue is that I can't debug the app on any simulator (iOS and android)!**
Once I debug the following result will show;

`Launching lib/main.dart on iPhone 11 Pro Max in debug mode...

Compiler message:
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-1.1.3/lib/src/cached_network_image_provider.dart:42:24: Error: The method 'CachedNetworkImageProvider.load' has fewer positional arguments than those of overridden method 'ImageProvider.load'.
  ImageStreamCompleter load(CachedNetworkImageProvider key) {
                       ^
../../../Development/flutter/packages/flutter/lib/src/painting/image_provider.dart:403:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(T key, DecoderCallback decode);
                       ^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image_library-0.1.8/lib/src/extended_memory_image_provider.dart:12:24: Error: The method 'ExtendedMemoryImageProvider.load' has fewer positional arguments than those of overridden method 'MemoryImage.load'.
  ImageStreamCompleter load(MemoryImage key) {
                       ^
../../../Development/flutter/packages/flutter/lib/src/painting/image_provider.dart:704:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(MemoryImage key, DecoderCallback decode) {
                       ^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image_library-0.1.8/lib/src/extended_file_image_provider.dart:13:24: Error: The method 'ExtendedFileImageProvider.load' has fewer positional arguments than those of overridden method 'FileImage.load'.
  ImageStreamCompleter load(FileImage key) {
                       ^
../../../Development/flutter/packages/flutter/lib/src/painting/image_provider.dart:636:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(FileImage key, DecoderCallback decode) {
                       ^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image_library-0.1.8/lib/src/extended_asset_bundle_image_provider.dart:35:24: Error: The method 'ExtendedExactAssetImageProvider.load' has fewer positional arguments than those of overridden method 'AssetBundleImageProvider.load'.
  ImageStreamCompleter load(AssetBundleImageKey key) {
                       ^
../../../Development/flutter/packages/flutter/lib/src/painting/image_provider.dart:467:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(AssetBundleImageKey key, DecoderCallback decode) {
                       ^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image_library-0.1.8/lib/src/extended_asset_bundle_image_provider.dart:87:24: Error: The method 'ExtendedAssetImageProvider.load' has fewer positional arguments than those of overridden method 'AssetBundleImageProvider.load'.
  ImageStreamCompleter load(AssetBundleImageKey key) {
                       ^
../../../Development/flutter/packages/flutter/lib/src/painting/image_provider.dart:467:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(AssetBundleImageKey key, DecoderCallback decode) {
                       ^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image_library-0.1.8/lib/src/extended_network_image_provider.dart:62:24: Error: The method 'ExtendedNetworkImageProvider.load' has fewer positional arguments than those of overridden method 'ImageProvider.load'.
  ImageStreamCompleter load(ExtendedNetworkImageProvider key) {
                       ^
../../../Development/flutter/packages/flutter/lib/src/painting/image_provider.dart:403:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(T key, DecoderCallback decode);
                       ^
Exception: Errors during snapshot creation: null

#0      KernelSnapshot.build  (package:flutter_tools/src/build_system/targets/dart.dart:231:7)
<asynchronous suspension>
#1      _BuildInstance._invokeInternal  (package:flutter_tools/src/build_system/build_system.dart:526:25)
<asynchronous suspension>
#2      _BuildInstance.invokeTarget.<anonymous closure>  (package:flutter_tools/src/build_system/build_system.dart:481:35)
#3      new Future.sync  (dart:async/future.dart:224:31)
#4      AsyncMemoizer.runOnce 
package:async/src/async_memoizer.dart:43
#5      _BuildInstance.invokeTarget  (package:flutter_tools/src/build_system/build_system.dart:481:21)
<asynchronous suspension>
<asynchronous suspension>
#6      BuildSystem.build  (package:flutter_tools/src/build_system/build_system.dart:419:36)
#7      buildWithAssemble  (package:flutter_tools/src/bundle.dart:125:48)
#8      BundleBuilder.build  (package:flutter_tools/src/bundle.dart:75:11)
#9      IOSSimulator.sideloadUpdatedAssetsForInstalledApplicationBundle  (package:flutter_tools/src/ios/simulators.dart:460:28)
#10     IOSSimulator._setupUpdatedApplicationBundle  (package:flutter_tools/src/ios/simulators.dart:426:11)
#11     IOSSimulator.startApp  (package:flutter_tools/src/ios/simulators.dart:354:15)
#12     FlutterDevice.runHot  (package:flutter_tools/src/resident_runner.dart:416:54)
#13     _asyncThenWrapperHelper.<anonymous closure>  (dart:async-patch/async_patch.dart:73:64)
#14     _rootRunUnary  (dart:async/zone.dart:1134:38)
#15     _CustomZone.runUnary  (dart:async/zone.dart:1031:19)
#16     _FutureListener.handleValue  (dart:async/future_impl.dart:139:18)
#17     Future._propagateToListeners.handleValueCallback  (dart:async/future_impl.dart:680:45)
#18     Future._propagateToListeners  (dart:async/future_impl.dart:709:32)
#19     Future._completeWithValue  (dart:async/future_impl.dart:524:5)
#20     _AsyncAwaitCompleter.complete  (dart:async-patch/async_patch.dart:32:15)
#21     _completeOnAsyncReturn  (dart:async-patch/async_patch.dart:290:13)
#22     BuildableIOSApp.fromProject `(package:flutter_tools/src/application_package.dart)`

2. Screenshots issues:

![Screen Shot 2019-11-22 at 3 27 20 PM](https://user-images.githubusercontent.com/57771284/69425807-b25f2480-0d3c-11ea-8e27-29162be97643.png)
![Screen Shot 2019-11-22 at 3 27 33 PM](https://user-images.githubusercontent.com/57771284/69425834-bb4ff600-0d3c-11ea-82c9-a4d675305146.png)

3. Proof of my purchased:

![Screen Shot 2019-11-22 at 3 30 05 PM](https://user-images.githubusercontent.com/57771284/69425956-066a0900-0d3d-11ea-8ea4-8f423c18389e.png)

I need to find a solution here please !
I tried to run “flutter clean” and reinstall again but still nothing happened!

**Comment by wolvsky** [comment]
I have the same problem.

**Comment by minhcasi** [comment]
@BashBB @wolvsky - could you send us the output when running: flutter doctor -v

**Comment by HassanChmsdn** [comment]
I have the same problem.

**Comment by BashBB** [comment]
@minhcasi - **following is the output when running:**



`------------------------FluxStore-vendor-1.1-2.0 % flutter doctor -v
[✓] Flutter (Channel dev, v1.12.10, on Mac OS X 10.15.1 19B88, locale en-US)
    • Flutter version 1.12.10 at /Users/bash/Development/flutter
    • Framework revision b6e92003c8 (18 hours ago), 2019-11-22 15:02:20 -0800
    • Engine revision ad14574949
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/bash/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.0.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.40.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • 1ACE83D1-84D9-4BB5-983B-EB35CA563CE9 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-2 (simulator)

• No issues found!`



**Regards,
Bash.**

**Comment by wolvsky** [comment]
I solved the problem for myself. I made 3 changes to work:

- I changed the version of cached_network_image in pubspec.yml:
#cached_network_image: ^1.1.3
cached_network_image: 2.0.0-rc

- I added in pubspec.yml:
dependency_overrides:
  extended_image_library:
    git:
      url: https://github.com/fluttercandies/extended_image_library.git
      ref: dev

- I commented the code block below in the file lib/screens/login_sms/verify.dart (line 191):
/*currentText: (value) {
    if (value != null && value.length == 6) {
      _loginSMS(value, context);
  }
},*/

**Comment by BashBB** [comment]
@wolvsky - That's great, good job.
Unfortunately, I did as you said but still getting the same issue.

**Comment by minhcasi** [comment]
@BashBB - pls use the channel stable by run "flutter channel stable" - this will revert back to Flutter stable v1.9.x - there are some library did not compatible with Dev channel

**Comment by chhotealams** [comment]
flutter clean
reinstall again but still nothing happened!
sir i i done this process .... but error was not gone...

**Comment by saifmuhtar** [comment]
@wolvsky This method is working for me! Thank you : )
