### ISSUE TITLE
ListPro Installation Issue 

### ISSUE THREAD

**Issue by heanglightman** [inspireui/support#144]
**Mandatory Info (please complete the following information):**
 - Product: ListPro 
 - Your Purchased Code: 2c024c05-5c9e-40f9-9f20-92c616eb44ee

**Describe the issues**
The Installation Documentation is not clear enough for newbie like me. I can get Expo Cli up and running but now cannot install Yarn, I definitely a need clearer video instruction on how to install from beginning.

**Comment by minhcasi** [comment]
Hi could you let us know what is your issue when install yarn, you can also check the install guide from https://yarnpkg.com/lang/en/docs/install Thanks
