### ISSUE TITLE
[FluxNews] - Build error

### ISSUE THREAD

**Issue by aldoyh** [inspireui/support#1440]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
I get this error when I build the iOS

Showing Recent Issues
Ignoring file /Users/aldoyh/development/flutter/bin/cache/artifacts/engine/ios-release/Flutter.framework/Flutter, missing required architecture i386 in file /Users/aldoyh/development/flutter/bin/cache/artifacts/engine/ios-release/Flutter.framework/Flutter (3 slices)

2. Screenshots issues:

3. Proof of my purchased:
Item ID:
24569377

Item Purchase Code:
d68d9310-1111-462e-8eff-1d1a09882ba4

Purchase Date:
2019-11-20 23:07:14 UTC

3. Config files (optional)

**Comment by minhcasi** [comment]
Hi @aldoyh - please try the "flutter doctor" and check to see if you have any issue ?

**Comment by minhcasi** [comment]
Hi, I'm closing this ticket as there is no response, kindly reopen or create a new ticket if you still have any issue - very best!
