### ISSUE TITLE
Fluxstore Woocommerce

### ISSUE THREAD

**Issue by Riorich** [inspireui/support#1442]
---------

1. My issue:
I'm new to flutter and I'm getting this error message and cannot compile the app. How could I fix it? Thanks.
**"The named parameter 'currentText' isn't defined.
Try correcting the name to an existing named parameter, or defining a new parameter with this name.**"
2. Screenshots issues:
![2019-11-23 (1)_LI](https://user-images.githubusercontent.com/39195214/69448265-8bc5db80-0d86-11ea-95d1-432ccdabe415.jpg)

3. Proof of my purchased:
Here's my proof of purchase.
![2019-11-23 (2)](https://user-images.githubusercontent.com/39195214/69448314-a5672300-0d86-11ea-9e20-113ff1276098.png)

3. Config files (optional)

**Comment by minhcasi** [comment]
@Riorich - pls try to run "flutter clean" and reinstall the package again - thank you!

**Comment by minhcasi** [comment]
@Riorich - from the pubspec.yaml, please try to update
from pin_code_fields: ^2.0.4 
-> to: pin_code_fields: 2.0.4

**Comment by Riorich** [comment]
Noted and will do accordingly. Thanks.

**Comment by minhcasi** [comment]
Another solution is to update - pin_code_fields: 2.2.0+4

And change to onChanged - function: https://tppr.me/m32Yz

**Comment by minhcasi** [comment]
#1443

**Comment by Riorich** [comment]
Noted and will amend accordingly. Many Thanks.

**Comment by Riorich** [comment]
Many Thanks to you. Fixed and can compile now.
