### ISSUE TITLE
FluxStore WooCommerce Can't compile  1.5.8+1

### ISSUE THREAD

**Issue by cakebread** [inspireui/support#1443]
I've tried all channels (stable, beta, master and dev) and can't compile.
With the stable branch of flutter I get this error:

Resolving dependencies...                                           2.1s
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

Compiler message:
lib/screens/login_sms/verify.dart:191:21: Error: No named parameter with the name 'currentText'.
                    currentText: (value) {
                    ^^^^^^^^^^^
/Users/admin/dev/flutter/.pub-cache/hosted/pub.dartlang.org/pin_code_fields-2.2.0+1/lib/pin_code_fields.dart:84:3: Context: Found this candidate, but the arguments don't match.
  PinCodeTextField({
  ^
Compiler failed on /private/tmp/FluxStore-woo 1.5.8/source/lib/main.dart

FAILURE: Build failed with an exception.

* Where:
Script '/Users/admin/dev/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 765

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebugArm64'.
> Process 'command '/Users/admin/dev/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                        14.7s
Gradle task assembleDebug failed with exit code 1

flutter doctor -v
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.14.6 18G95, locale en-US)
    • Flutter version 1.9.1+hotfix.6 at /Users/admin/dev/flutter
    • Framework revision 68587a0916 (2 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/admin/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/admin/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Connected device (1 available)
    • (redacted) (API 28)

• No issues found!

**Comment by cakebread** [comment]
Proof of purchase:
https://gyazo.com/c2403f489d2546d7524ec400eb3ce20b

**Comment by cakebread** [comment]
Proof of purchase 
https://burgerrecords.com/wp-content/uploads/2019/11/codecanyon.png

**Comment by minhcasi** [comment]
@cakebread please try to open the pubspec.yaml, please try to update
from pin_code_fields: ^2.0.4 
-> to: pin_code_fields: 2.0.4 

Let us know your checking, we are working on a new upgrade to update all the latest pub files - it will be updated in early next week - thank you!

**Comment by minhcasi** [comment]
Another solution is to update - pin_code_fields: 2.2.0+4

And change to onChanged - function: https://tppr.me/m32Yz

Thank you!

**Comment by minhcasi** [comment]
Fixed on latest 1.5.9, please help to download the update and changelog - https://medium.com/@inspireui/announcing-fluxstore-1-5-950e0165cab8 (at the end of the article)
