### ISSUE TITLE
fluxstore - ios

### ISSUE THREAD

**Issue by Senior-Gamal** [inspireui/support#1444]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------
My issue

1 - in screenshot
2 - we are need a clear instructions for integrating Facebook login and sms login for ios

Screenshots
1 5

My screenshot of the purchase product or my comment:
https://user-images.githubusercontent.com/27568540/66625373-4e512880-ebf4-11e9-9b30-c4a19f7d028d.jpeg

**Comment by minhcasi** [comment]
@Senior-Gamal  please check this detailed guide for Facebook Login - https://pub.dev/packages/flutter_facebook_login

The current SMS Login is replaced by new Firebase SMS Login as the Fb Account Kit is stoped support - you can check it from https://docs.inspireui.com/fluxstore/firebase/#sms-login

**Comment by Senior-Gamal** [comment]
error in console after replace app id 
![ios](https://user-images.githubusercontent.com/27568540/69478873-08e16700-0e00-11ea-9cad-6a253a4f5719.jpg)

**Comment by minhcasi** [comment]
copy from #1448
---

1 - I cannot log into the account and show this message ( warning : exception: the username or password is incorrect ) But the account works normally on the site
2 - And when you sign up ( exception : you must include 'username' .var in your request )

My screenshot of the purchase product or my comment:
https://user-images.githubusercontent.com/27568540/66625373-4e512880-ebf4-11e9-9b30-c4a19f7d028d.jpeg
----

@minhtruong315 - please help to suggest for these issues

**Comment by Senior-Gamal** [comment]
i fixed the issue in ticket id #1448 
but the fb login not fixed

**Comment by minhtruong315** [comment]
@Senior-Gamal share me your teamviewer. I will help you check it

**Comment by Senior-Gamal** [comment]
please share me your mail or skype to send teamviewer info

**Comment by minhtruong315** [comment]
my skype: minhtruong315

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
