### ISSUE TITLE
[mstore-pro] - Too slow in showing page and categories 

### ISSUE THREAD

**Issue by momonchi** [inspireui/support#1445]
Hello, I am having trouble with running through react-native run-android, It is too slow opening other page/activity and categories. I already enable the ProductSize, but when I’am routing it is too lag in android. But in the expo It is run smooth, too different user exp.

![image](https://user-images.githubusercontent.com/5693186/69480871-54b6ff00-0e46-11ea-9d74-35406757f96e.png)

**Comment by minhcasi** [comment]
Hi, did you try with real device for testing with Release mode? On debugging of Android will be slow, try to disable the Debug option from simulator as well -  try to use Reactotron instead - https://github.com/infinitered/reactotron/blob/master/docs/installing.md

**Comment by minhcasi** [comment]
Could you help to check with latest 1.5.9, there are some performance improvements

Also check this guide to upgrade the app perforamance -https://docs.inspireui.com/fluxstore/performance/

Let us know if you have any questions, thank you!

**Comment by momonchi** [comment]
Hi @minhcasi thanks for the help.

I run this command, and it run smooth like expo.
react-native run-android --variant=release

thanks again.
