### ISSUE TITLE
[FluxStore Listing] - Starting App

### ISSUE THREAD

**Issue by bobozd** [inspireui/support#1446]
1. My issue: I got this error starting my Fluxstore App

Error: No named parameter with the name 'currentText'.
                    currentText: (value) {

2. Screenshots issues:

![Screen Shot 2019-11-23 at 17 10 08](https://user-images.githubusercontent.com/28021993/69481752-31735c00-0e14-11ea-9da5-3c4e0d081282.png)

3. Proof of my purchased:

![Screen Shot 2019-11-23 at 17 11 44](https://user-images.githubusercontent.com/28021993/69481765-62539100-0e14-11ea-8cfc-6f6029c05b60.png)

**Comment by codingastronaut** [comment]
I also have the same issue, got the latest version from gitlab

**Comment by codingastronaut** [comment]
also worth mentioning that i cant find pin_code_fields: 2.2.0+4

**Comment by Alnaggar94** [comment]
Same issue on macOS, but in windows working fine ?? 

![issue1](https://user-images.githubusercontent.com/49800146/69490180-0e3cc100-0e95-11ea-8923-5e00a982f7df.JPG)

**Comment by minhcasi** [comment]
@bobozd @codingastronaut @Alnaggar94 - pls try this file https://tppr.me/VTGJo

Related solution #1443

**Comment by bobozd** [comment]
this is error I get trying with latest 1.2 version

Xcode's output:
↳
    /Users/borisbozic/AndroidStudioProjects/FluxstoreApp_01/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/GDTCORStorage.m:123:41: error: no known class method for selector 'archivedDataWithRootObject:requiringSecureCoding:error:'
            NSData *data = [NSKeyedArchiver archivedDataWithRootObject:self
                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/borisbozic/AndroidStudioProjects/FluxstoreApp_01/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/GDTCORStorage.m:221:26: error: no known class method for selector 'unarchivedObjectOfClass:fromData:error:'
          [NSKeyedUnarchiver unarchivedObjectOfClass:[GDTCORStorage class] fromData:data error:&error];
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/borisbozic/AndroidStudioProjects/FluxstoreApp_01/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/GDTCORStorage.m:243:39: error: no known class method for selector 'archivedDataWithRootObject:requiringSecureCoding:error:'
          NSData *data = [NSKeyedArchiver archivedDataWithRootObject:self
                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/borisbozic/AndroidStudioProjects/FluxstoreApp_01/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/GDTCORStorage.m:262:37: error: no known class method for selector 'archivedDataWithRootObject:requiringSecureCoding:error:'
        NSData *data = [NSKeyedArchiver archivedDataWithRootObject:self
                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    4 errors generated.
    /Users/borisbozic/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/apple_sign_in-0.1.0/ios/Classes/AppleIDButton.m:9:9: fatal error: 'AuthenticationServices/AuthenticationServices.h' file not found
    #import <AuthenticationServices/AuthenticationServices.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

Could not build the application for the simulator.
Error launching application on iPhone X.

**Comment by minhcasi** [comment]
@bobozd pls try to run "flutter clean" and run the project again.

Also, run "flutter channel stable" to update your flutter to a stable source

Let us know your checking - thanks

**Comment by bobozd** [comment]
I tried what you suggest but I get this

Launching lib/main.dart on iPhone X in debug mode...
Running pod install...
Running Xcode build...
Xcode build done.                                            5.4s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    /Users/borisbozic/AndroidStudioProjects/FluxstoreApp_02/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/GDTCORStorage.m:123:41: error: no known class method for selector 'archivedDataWithRootObject:requiringSecureCoding:error:'
            NSData *data = [NSKeyedArchiver archivedDataWithRootObject:self
                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/borisbozic/AndroidStudioProjects/FluxstoreApp_02/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/GDTCORStorage.m:221:26: error: no known class method for selector 'unarchivedObjectOfClass:fromData:error:'
          [NSKeyedUnarchiver unarchivedObjectOfClass:[GDTCORStorage class] fromData:data error:&error];
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/borisbozic/AndroidStudioProjects/FluxstoreApp_02/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/GDTCORStorage.m:243:39: error: no known class method for selector 'archivedDataWithRootObject:requiringSecureCoding:error:'
          NSData *data = [NSKeyedArchiver archivedDataWithRootObject:self
                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/borisbozic/AndroidStudioProjects/FluxstoreApp_02/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/GDTCORStorage.m:262:37: error: no known class method for selector 'archivedDataWithRootObject:requiringSecureCoding:error:'
        NSData *data = [NSKeyedArchiver archivedDataWithRootObject:self
                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    4 errors generated.

Could not build the application for the simulator.
Error launching application on iPhone X.

**Comment by minhcasi** [comment]
@bobozd - did you run the project from XCode or Android Studio?

Do you have the same error with the Test Drive - https://flutter.dev/docs/get-started/test-drive ?

**Comment by minhcasi** [comment]
@bobozd - pls update to latest fluxlisting and let us know if you have any issues with the checking - thank you!

**Comment by bobozd** [comment]
I got this error while running Flutter Test Drive project

Running Xcode build...
Xcode build done.                                           13.2s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===

/Users/borisbozic/AndroidStudioProjects/flutter_app/ios/Runner/AppDelegate.swift:8:65:
error: 'LaunchOptionsKey' is not a member type of 'UIApplication'
        didFinishLaunchingWithOptions launchOptions:
[UIApplication.LaunchOptionsKey: Any]?

please help
