### ISSUE TITLE
MStore Magento2

### ISSUE THREAD

**Issue by a7medeeuae** [inspireui/support#1447]
![1212556](https://user-images.githubusercontent.com/24714994/69483970-343b7480-0e47-11ea-90bd-664b889288a1.jpg)
i got this erorr when i try to run the app

**Comment by minhcasi** [comment]
Hi, thank you for reaching. Could you help to share the purchased screenshot from http://codecayon.net/downloads ? Just want to verify your proof of purchase, sorry for any inconvenience - thank you!

**Comment by a7medeeuae** [comment]
![216262626](https://user-images.githubusercontent.com/24714994/69574434-857f6b80-0fe1-11ea-97f3-da8507226d41.png)

**Comment by minhcasi** [comment]
@a7medeeuae - sorry for the late response, could you help to reinstall the node js 12.x on this page - https://nodejs.org/en/ - the error seems related to node 13 issue - thank you!

**Comment by a7medeeuae** [comment]
i still get this

  win_delay_load_hook.cc
  z.vcxproj -> C:\Users\MR.Robot\Desktop\CeBuilder\Mstore-magento-1.1\Source\node_modules\grpc\build\Release\\libz.lib
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=C:\\Users\\MR.Robot\\Desktop\\CeBuilder\\Mstore-magento-1.1\\Source\\node_modules\\grpc\\src\\node\\extension_binary\\node-v72-win32-x64-unknown\\grpc_node.node" "--module_name=grpc_node" "--module_path=C:\\Users\\MR.Robot\\Desktop\\CeBuilder\\Mstore-magento-1.1\\Source\\node_modules\\grpc\\src\\node\\extension_binary\\node-v72-win32-x64-unknown" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd C:\Users\MR.Robot\Desktop\CeBuilder\Mstore-magento-1.1\Source\node_modules\grpc
gyp ERR! node -v v12.13.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd build --fallback-to-build --library=static_library --module=C:\Users\MR.Robot\Desktop\CeBuilder\Mstore-magento-1.1\Source\node_modules\grpc\src\node\extension_binary\node-v72-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=C:\Users\MR.Robot\Desktop\CeBuilder\Mstore-magento-1.1\Source\node_modules\grpc\src\node\extension_binary\node-v72-win32-x64-unknown --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\MR.Robot\Desktop\CeBuilder\Mstore-magento-1.1\Source\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
node-pre-gyp ERR! System Windows_NT 10.0.18363
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\MR.Robot\\Desktop\\CeBuilder\\Mstore-magento-1.1\\Source\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd C:\Users\MR.Robot\Desktop\CeBuilder\Mstore-magento-1.1\Source\node_modules\grpc
node-pre-gyp ERR! node -v v12.13.1
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd build --fallback-to-build --library=static_library --module=C:\Users\MR.Robot\Desktop\CeBuilder\Mstore-magento-1.1\Source\node_modules\grpc\src\node\extension_binary\node-v72-win32-x64-unknown\grpc_node.node                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
C:\Users\MR.Robot\Desktop\CeBuilder\Mstore-magento-1.1\Source>
C:\Users\MR.Robot\Desktop\CeBuilder\Mstore-magento-1.1\Source>
C:\Users\MR.Robot\Desktop\CeBuilder\Mstore-magento-1.1\Source>
C:\Users\MR.Robot\Desktop\CeBuilder\Mstore-magento-1.1\Source>

**Comment by a7medeeuae** [comment]
and not working
