### ISSUE TITLE
[fluxstore multi vendor] - upgrade and failed to compile

### ISSUE THREAD

**Issue by ganesha10** [inspireui/support#1449]
1. My issue:
version 1.0.1 always return to main page when a category is clicked. I try to upgrade by using version 1.1.0, however I failed to compile. thanks

2. Screenshots issues:

Compiler message:
lib/screens/login_sms/verify.dart:191:21: Error: No named parameter with the name 'currentText'.
                    currentText: (value) {
                    ^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dartlang.org/pin_code_fields-2.2.1/lib/pin_code_fields.dart:84:3: Context: Found this candidate, but the arguments don't match.
  PinCodeTextField({
  ^
Compiler failed on C:\finergi\flutter\kerja\warga\source\lib\main.dart

FAILURE: Build failed with an exception.

* Where:
Script 'C:\finergi\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 765

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebugArm'.
> Process 'command 'C:\finergi\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 51s
Finished with error: Gradle task assembleDebug failed with exit code 1

3. Proof of my purchased:
![fluxstorepurchase](https://user-images.githubusercontent.com/19354235/69498462-d7a98980-0f1a-11ea-8995-0fb2b7e6ec51.png)

3. Config files (optional)

**Comment by ganesha10** [comment]
I use solution from wolvsky where I changed  the file lib/screens/login_sms/verify.dart (line 191):
from currentText to onChanged. However no change were made to pubspec.yml and now it runs fine on a real device.

**Comment by minhcasi** [comment]
Pls try to change  pubspec.yml to  pin_code_fields: 2.2.0+4 as well 

The root cause is when we set "^2.0.0+4" -> it's auto-upgrade to latest version, the `onChanged` required on the latest version - we will update the new version on today to fix this issues

**Comment by minhcasi** [comment]
#1443

**Comment by minhcasi** [comment]
Please update to latest 1.2.0 for this fixing - thank you!
