### ISSUE TITLE
[MStore Pro - Complete React Native template for e-commerce] - issues after upgrading to sdk version 34

### ISSUE THREAD

**Issue by Pankti16** [inspireui/support#1450]
1. My issue: 
I tried adding ```injectedJavaScript={INJECTEDJAVASCRIPT} javaScriptEnabled={true} setDisplayZoomControls={false}```

to the webview component in src/containers/WebView/WebView.js

But, still zoom is not disabled.

and getting ```Warning: ListView is deprecated and will be removed in a future release. See https://fb.me/nolistview for more information``` such errors in terminal when running setup, since yesterday.

and getting ```Warning: Each child in a list should have a unique “key” prop.%s%s See https://fb.me/react-warning-keys for more information.%s,

Check the render method of `OrderNotes`., , in View (at OrderNotes.js:28)``` since yesterday => There is <View style={styles.noteItem}> code at line 28

2. Screenshots issues:
![orderDetailIssue](https://user-images.githubusercontent.com/28388925/69511499-6099e280-0f66-11ea-8847-4b6a45571351.PNG)
![listViewDeprecated](https://user-images.githubusercontent.com/28388925/69511500-6099e280-0f66-11ea-97ef-47e2b2c829c2.PNG)

3. Proof of my purchased:
[52190056-beostore-complete-react-native-template-for-ecommerce-license.pdf](https://github.com/inspireui/support/files/3884793/52190056-beostore-complete-react-native-template-for-ecommerce-license.pdf)

3. Config files (optional)
[Config.zip](https://github.com/inspireui/support/files/3884804/Config.zip)

**Comment by minhcasi** [comment]
@Pankti16 - noted with investigating and will keep an update about this issue - thank you!

**Comment by Pankti16** [comment]
Also, when I click on favorite icon(heart icon) of a product in category listing, it gets added to the wish list. But, neither favorite icon turns red nor it is removed from the wish list when I press it once more.

**Comment by Pankti16** [comment]
the custom page works fine in android but keeps loading in iOS

![iosCustomPage](https://user-images.githubusercontent.com/28388925/70129620-1969cb00-16a5-11ea-80c1-23e54eefe5f2.PNG)

**Comment by concuacon** [comment]
@Pankti16 Can you give me your email, I send a new source to you.

**Comment by Pankti16** [comment]
yes, sure shahpankti98@gmail.com

**Comment by Pankti16** [comment]
I did not receive an email with source code and why would you close it?

**Comment by minhcasi** [comment]
sorry - i thought he sent you - i will double-check with him

**Comment by Pankti16** [comment]
okay, could you please do it little faster, as it is urgent.

**Comment by minhcasi** [comment]
@Pankti16 - could you help to download and check on latest 3.9.7 - please note that the custom page will not for all of the URL due to the limitation of the WebView that some JS code will not work as the same on the browser and cause the blank page - thank you!

**Comment by Pankti16** [comment]
sure, I will help you to do it. From where can I download it?

**Comment by minhcasi** [comment]
@Pankti16  - sorry for miss your comment - pls download it from http://codecayon.net/downloads and let us know if you have any problem - thanks
