### ISSUE TITLE
[Fluxstore] Shipping Charges issue

### ISSUE THREAD

**Issue by drew1607** [inspireui/support#1452]
Hi I am using Table Rates https://codecanyon.net/item/table-rate-shipping-for-woocommerce/3796656 for handling delivery charges and the app is return 0 rates shipping rates a flat rate is working just fine but we dont use flat rates because our dynamic charge comes from the volumetric weight of the item added to cart then gives it back to the user on checkout. How do I get dynamic rates to show in the app. Please help give direction for us to develop a solution to this

**Comment by drew1607** [comment]
![Screen Shot 2019-11-25 at 14 26 15](https://user-images.githubusercontent.com/26347213/69540630-c2bb0d80-0f8f-11ea-9d7d-e3344a222221.png)
![Screen Shot 2019-11-25 at 14 26 25](https://user-images.githubusercontent.com/26347213/69540631-c353a400-0f8f-11ea-93c3-0aad233789b6.png)
![Screen Shot 2019-11-25 at 14 27 05](https://user-images.githubusercontent.com/26347213/69540632-c353a400-0f8f-11ea-8bed-a28dd07e0ede.png)

[config.dart.zip](https://github.com/inspireui/support/files/3886561/config.dart.zip)

**Comment by minhcasi** [comment]
@drew1607 - as this is the customize plugin that we are not sure to work with the app, but we will try to check and let you know if find out any solution, we will share the detail - thanks

**Comment by drew1607** [comment]
Thank you very much will really be grateful

**Comment by vumanhsn97** [comment]
@drew1607 Can you give me your config.dart, config.json files?

**Comment by drew1607** [comment]
[common.zip](https://github.com/inspireui/support/files/3895556/common.zip)

**Comment by drew1607** [comment]
There you go

**Comment by vumanhsn97** [comment]
@drew1607 
"consumerKey": "ck_b7594bc4391db4b56c635fe6da1072a53ca4535a",
  "consumerSecret": "cs_980b9edb120e15bd2a8b668cacc734f7eca0ba40",
are fluxstore config. Please send me your consumerKey and consumerSecret

**Comment by drew1607** [comment]
@vumanhsn97 , Please see below,
ck_29b2bf7b82722eb63afbc7a6d48457740cbb5c82
cs_0d4ccec9abb5728eaf332e49c3c4ff4eebf0be0a

**Comment by vumanhsn97** [comment]
@drew1607 I research about Table Rate Shipping. I dont find any way to get api shipping methods. When I use woocommerce api, It return data without rules. You can see here: https://griffinzambia.com/wp-json/wc/v2/shipping/zones/7/methods

**Comment by minhcasi** [comment]
@minhtruong315 - investigate the hook to get the shipping rate on this API - https://github.com/inspireui/support/issues/1452

**Comment by minhcasi** [comment]
@drew1607  - could you share the plugin "Table Rate Shipping" to email support@inspireui.com - we need to check the API issue - thanks

**Comment by drew1607** [comment]
Sent via wetransfer

**Comment by minhtruong315** [comment]
@drew1607  we haven't supported this plugin now. I will try to add this plugin to Fluxstore. Thanks for your request

**Comment by lancerynearson** [comment]
I too can't use this app as I fall into the category of people that uses plugins to make shipping happen. I have USPS and some other to make free shipping on some products. Have you guys ever considered just enabling an option to have the shipping selected last on WebView? As you open that anyways just have all checkout fields fallout and let user select shipping then hit pay now. Just an Idea as I understand REST API is limit. I'd love you actually use this app someday.
