### ISSUE TITLE
[mstore pro] - i have problem with coupon 

### ISSUE THREAD

**Issue by hami44** [inspireui/support#1453]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
hi i have problem with Coupon when i set my coupon its work but when i going to next tern payment i see discount but dose not work i dont see total amount finally my order didnt have any coupon discount 
2. Screenshots issues:
![Screenshot_1574675037](https://user-images.githubusercontent.com/58168661/69530646-710c8600-0f83-11ea-8ffe-ecfb0d99c989.png)
![Screenshot_1574675211](https://user-images.githubusercontent.com/58168661/69530659-78cc2a80-0f83-11ea-9c14-39528187b599.png)
![Screenshot_1574675239](https://user-images.githubusercontent.com/58168661/69530668-7ec20b80-0f83-11ea-8e27-7948ce7b5eab.png)
![Screenshot_1574675273](https://user-images.githubusercontent.com/58168661/69530685-8386bf80-0f83-11ea-94d1-a5cf2f017744.png)

3. Proof of my purchased:
![Screen Shot 2019-11-25 at 1 05 32 PM](https://user-images.githubusercontent.com/58168661/69531154-70c0ba80-0f84-11ea-8d6c-ed3407d34b62.png)

3. Config files (optional)

**Comment by hami44** [comment]
@minhcasi why no one respond my issue ?

**Comment by minhcasi** [comment]
@hami44 - thank you for the detail issue - please allow us to reply ticket within 24h

Could you help to attache the config file so that we could help for checking and reproduce the issue

@concuacon 
Thank you!

**Comment by hami44** [comment]
[Config.js.zip](https://github.com/inspireui/support/files/3890830/Config.js.zip)
@minhcasi my config file

**Comment by minhcasi** [comment]
@concuacon - pls help for checking

**Comment by hami44** [comment]
is there any update about my issue ? @concuacon @minhcasi

**Comment by minhcasi** [comment]
@hami44 - confirm this is a bug - we have included from the checklist for the next release on next couple of days.

There will also some bug fix and Apple Sign In + SMS Firebase login on next release

Thank you!

**Comment by hami44** [comment]
@minhcasi hi you said you will release new update on next couple of days after 5 days age 
is there any update on that release ?

**Comment by minhtruong315** [comment]
@hami44 I'm checking your issues

**Comment by minhtruong315** [comment]
You can try to change getCouponInfo function in containers/Cart/Payment/index.js like this
```
getCouponInfo = () => {
    const { couponCode, couponAmount } = this.props;
    if (
      typeof couponCode !== "undefined" &&
      typeof couponAmount !== "undefined" &&
      couponAmount > 0
    ) {
      return [
        {
          "code": couponCode,
          "discount": `${couponAmount}`
        },
      ];
    }
    return [];
  };
```

**Comment by hami44** [comment]
@minhtruong315  i tried this function but i had same problem !!! 
@minhcasi

**Comment by hami44** [comment]
![image](https://user-images.githubusercontent.com/58168661/70059380-bbc87680-15f1-11ea-8ab6-9cf5682d15c0.png)

**Comment by minhtruong315** [comment]
add my skype: minhtruong315
i will help you check it via teamviewer

**Comment by hami44** [comment]
@minhtruong315  i added you cheack your sky

**Comment by minhtruong315** [comment]
supported
