### ISSUE TITLE
[MStore Multi vendor] - I can't upload products - "can not connect from server"

### ISSUE THREAD

**Issue by santihabib** [inspireui/support#1456]
Hi! I'm still having problems, it really doesn't end! Every update they do, the problems continue.
The problem I have in this new version is that when I want to upload a product, it returns the message "can not connect from server". I have already configured all the plugins and verify that my htacces is correct, I do not understand what may be happening! It's been a long time since I bought the script and I still can't use it! Attachment configuration file, etc.
![65076487-7770f700-d96f-11e9-8cd3-ab36f8b04aba (1)](https://user-images.githubusercontent.com/55243343/69545089-d5254f00-0f6f-11ea-80e8-9a3e4710adb3.png)

[AppConfig.txt](https://github.com/inspireui/support/files/3886853/AppConfig.txt)

**Comment by santihabib** [comment]
I'm doing some tests with an application to intercept http responses.
json api message:
"You need to login with a user that has 'edit_posts' capacity"

**Comment by minhcasi** [comment]
@santihabib - thank you for reporting, could you help to share the config file so that we could reproduce the issue on your site?

**Comment by santihabib** [comment]
@minhcasi @concuacon i shared the config file in the first post.

**Comment by santihabib** [comment]
I attach everything here
[AppConfig.txt](https://github.com/inspireui/support/files/3891898/AppConfig.txt)
[Config.txt](https://github.com/inspireui/support/files/3891900/Config.txt)

**Comment by aaronbesson** [comment]
I am having same issue, the image is uploaded, but the post is not created.
"can not connect from server"

**Comment by minhcasi** [comment]
@santihabib - we will check this issue as a high priority and will keep an update - thank you!

**Comment by santihabib** [comment]
please @minhcasi ! don't make me wait until another update! I need once and for all to launch my application to production. thanks!

**Comment by santihabib** [comment]
Update!
--------------
It seems that the problem is in the coockie with which it authenticates ... in the customapi.js file in this section:

const response = await this.getNonceForPost(method);
  const cookieName = await this.generateAuthCookie(user.email, user.password);
  if (typeof response.status !== "undefined" && response.status == "ok") {
    // console.warn(["nonce", response]);
    const nonce = response.nonce;
    const requestUrl = `${
      this.url
    }/api/posts/${method}/?insecure=cool&nonce=${nonce}&title=${title}&email=${
      user.email
    }&username=${user.username}&password=${user.password}&author=${
      user.username
    }&status='draft'&type='product'&meta_input=${JSON.stringify(obj)}&cookie=${
      cookieName.cookie_name
    }&content=${content}&platform=${Platform.OS}`;
    if (method != "create_post") {
      requestUrl += `&id=${product.id}&post_type=product`;
    }
    return this._request(requestUrl);
  }
};

I see that it uses cookiename.cookie_name and that causes me to use the name of the cookie and not the cookie to log in.
I still could not get him to extract the cookie instead of the name, it would be appreciated to be told how.
Anyway, if I do this via postman, I get the post up correctly, but now I face the same old fault again! The product is loaded without image or price or content! just the title!
Anyway, let's go step by step! The first thing I need is that from the app the post is made with the cookie and not with her name!

**Comment by aaronbesson** [comment]
@santihabib - line 361 in WordpressAPI.js

as mentioned i am able to post images and not title etc, i'll take a look

**Comment by vumanhsn97** [comment]
@santihabib 
We will update in next version. You can try to fix by chaging some file. 
- src/redux/ProductRedux.js to 
[ProductRedux.js.zip](https://github.com/inspireui/support/files/3901301/ProductRedux.js.zip)
- src/services/CustomAPI.js and WPUserAPI.js to 
[Archive.zip](https://github.com/inspireui/support/files/3901305/Archive.zip)

Thanks for iusses!

**Comment by santihabib** [comment]
@vumanhsn97 @minhcasi this worked for me !!! Thank you! finally everything works! thanks!
