### ISSUE TITLE
Warning: BackAndroid is deprecated. Please use BackHandler instead

### ISSUE THREAD

**Issue by khaja25** [inspireui/support#1457]
hey there, i am facing issue below 

![Backandroid](https://user-images.githubusercontent.com/58036762/69547499-b6e54080-0fbb-11ea-8144-6e8977e4d8c4.jpeg)

**Comment by minhcasi** [comment]
@khaja25  - could i know this is a report issue for the Mstore product ? Thank you!

**Comment by khaja25** [comment]
yes @minhcasi

**Comment by minhcasi** [comment]
@khaja25 - could you help to take the screenshot from this page http://codecayon.net/downloads - just verify the proof of your purchase from our product - sorry for any inconvenience - thank you!
