### ISSUE TITLE
[fluxstore] - Build failed with an exception.

### ISSUE THREAD

**Issue by mk4full** [inspireui/support#1459]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:

aunching lib\main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

Compiler message:
lib/screens/login_sms/verify.dart:191:21: Error: No named parameter with the name 'currentText'.
                    currentText: (value) {
                    ^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/pin_code_fields-2.2.1/lib/pin_code_fields.dart:84:3: Context: Found this candidate, but the arguments don't match.
  PinCodeTextField({
  ^
Compiler failed on C:\src\FluxStore-woo 1.5.8\source\lib\main.dart

FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 765

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebugX86'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

2. Screenshots issues:
https://ibb.co/6XZMBBd

3. Proof of my purchased:

**Comment by minhcasi** [comment]
@mk4full  this is related to auto-upgrade from the library of pubspec.yaml file, pls try the solution from this ticket - #1449 
We are going update new version shortly to resolve this issue

**Comment by minhcasi** [comment]
Fixed on latest 1.5.9, please help to download the update and changelog - https://medium.com/@inspireui/announcing-fluxstore-1-5-950e0165cab8 (at the end of the article)
