### ISSUE TITLE
[MStore] product image not working in home and i can not change header colors

### ISSUE THREAD

**Issue by hamadatalaat** [inspireui/support#146]
**Mandatory Info (please complete the following information):**
 - Product: Mstore
 - Your Purchased Code: 55668558-c73a-423a-a1c4-20e932089a74
(we may not reply if you are not our customer)

**Describe the issues**
product image not working in home and i can not change header colors or image size and change language menu does not appear

**Screenshots**

**Additional context**
Add any other detail logs about the problem here.

**Comment by minhcasi** [comment]
Hi could you help to check if this solution work - https://docs.mstore.io/advance-customize-app/woocommerce-setting#product-display-sizes

**Comment by hamadatalaat** [comment]
in woocommerce 3.3 they disable this function there is no place showing product images size i had to write images size with a function and still not working too.

**Comment by hamadatalaat** [comment]
and also i asked about language changer and logo size control

**Comment by minhcasi** [comment]
Hi, please use the latest document from https://docs.mstore.io

This ticket is linked to https://github.com/inspireui/support/issues/118 we are checking the best solution to drop the image size - in the meantime you can display the image by update ProductSize > enable: false

**Comment by hamadatalaat** [comment]
thanks for your reply
in this link
https://docs.mstore.io/~/drafts/-LJC5tEPd8BLT3fsljHG/primary/basic-app-setting#wordpress-plugins-install
i can not open what in it tell me "
Restricted access

The access to this page is restricted.

Sign in to an account with required permission

**Comment by luyx2412** [comment]
Hi @hamadatalaat We moved to another domain https://docs.mstore.io/basic-app-setting#wordpress-plugins-install

Thanks
