### ISSUE TITLE
[Fluxstore-1.5.8] - Error: No named parameter with the name 'currentText'.

### ISSUE THREAD

**Issue by EmilianH** [inspireui/support#1460]
---------

1. My issue:

i try to start the app 1.5.8 from zero without changes, and not working

Compiler message:
lib/screens/login_sms/verify.dart:191:21: Error: No named parameter with the name 'currentText'.
                    currentText: (value) {
                    ^^^^^^^^^^^
../../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/pin_code_fields-2.2.1/lib/pin_code_fields.dart:84:3: Context: Found this candidate, but the arguments don't match.
  PinCodeTextField({
  ^
Compiler failed on C:\Users\emi19\Desktop\mamap-1.5.8\source\lib\main.dart

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Flutter\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 765

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebugX86'.
> Process 'command 'C:\Flutter\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 12s
Finished with error: Gradle task assembleDebug failed with exit code 1

2. Screenshots issues:
![image](https://user-images.githubusercontent.com/57189819/69591303-20237e80-0fd1-11ea-8557-7bd78f565e4b.png)

3. Proof of my purchased:
![compra](https://user-images.githubusercontent.com/57189819/69591311-27e32300-0fd1-11ea-9b6e-12ac68f5243c.jpg)

3. Config files (optional)

**Comment by minhcasi** [comment]
@EmilianH this is related to auto-upgrade from the library asseting, pls try the solution from this ticket - #1449 
We are going update new version shortly to resolve this issue

**Comment by minhcasi** [comment]
Fixed on latest 1.5.9, please help to download the update and changelog - https://medium.com/@inspireui/announcing-fluxstore-1-5-950e0165cab8 (at the end of the article)
