### ISSUE TITLE
Mstore Pro] - 

### ISSUE THREAD

**Issue by TarekNour77** [inspireui/support#1461]
I have an error when try the app on my mobile :

![Screenshot_2019-11-26-17-00-32-065_com inspireui mstorepro](https://user-images.githubusercontent.com/58216827/69645573-ce85fd00-107f-11ea-8514-4daf8fd9a40d.png)

![2019-11-26_1907](https://user-images.githubusercontent.com/58216827/69645684-01c88c00-1080-11ea-9a1e-c597f83925b4.png)

**Comment by minhcasi** [comment]
refund
