### ISSUE TITLE
[Fluxstore] - 1.5.9 Compile Error

### ISSUE THREAD

**Issue by Riorich** [inspireui/support#1462]
1. My issue:
I'm getting this error as below when I compiled latest Fluxstore 1.5.9 Woocommerce. I didn't have this kind of error in v 1.5.8. 
**dart:ui/window.dart': Failed assertion: line 281: '<optimized out>': is not true.**

2. Screenshots issues:
![Screenshot_1574782658](https://user-images.githubusercontent.com/39195214/69649360-52011780-109b-11ea-86f3-0c1b79b8b2f6.png)
![2019-11-26 (2)_LI](https://user-images.githubusercontent.com/39195214/69649570-9e4c5780-109b-11ea-81fc-1760bf690221.jpg)

3. Proof of my purchased:
Here is my proof of purchase.
![2019-11-23 (2)](https://user-images.githubusercontent.com/39195214/69649634-b6bc7200-109b-11ea-810b-371772fb9e01.png)

3. Config files (optional)

**Comment by minhcasi** [comment]
@Riorich - could you share the output after run: "flutter doctor"

**Comment by Moostsv** [comment]
I have the same error (Opencart)

**Comment by minhcasi** [comment]
@Riorich @Moostsv 

Please make sure the run the app at stable channel: flutter channel stable

Also, try this scrip with the latest version: flutter clean

Let us know your checking - thanks

**Comment by Moostsv** [comment]
https://snipboard.io/L862Fd.jpg

**Comment by Moostsv** [comment]
https://snipboard.io/I8qxgV.jpg

**Comment by minhcasi** [comment]
@minhtruong315 - pls investigate this issue - thank you!

**Comment by minhtruong315** [comment]
@Moostsv can you share me your teamviewer? It's working on my end

**Comment by minhtruong315** [comment]
[opencart.zip](https://github.com/inspireui/support/files/3899880/opencart.zip)
You only need to change this config to fix the issue
