### ISSUE TITLE
[Fluxstore] - Variable products showing out of stock 

### ISSUE THREAD

**Issue by underscore15** [inspireui/support#1464]
Hello 

1.Still got an issue with variable products in alternative language being out of stock. In main language (English) no issues but alternative languages showing out of stock 

2. In RTL, the smartchat button is off screen 

![Screen Shot 2019-11-26 at 9 27 18 PM](https://user-images.githubusercontent.com/56452467/69661473-8b358980-1093-11ea-8379-f21430beb5d6.png)

3. Can you provide a simple user use for the push notifications. Files to edit and where to place Keys 

4. Remove the Reviews tab from products 

All issues are in 1.5.9
For proof of purchase will place a comment.

**Comment by vumanhsn97** [comment]
1. Can you give me more details. Screenshots, config.dart, config.json files?
2. Fixed it in next version
3. Fluxstore use firebase messaging (https://firebase.google.com/). You need to create apps(one for ios, one for android) and download your google services json. Next step, you need to change google services json file. Run app and make sure your app connect to app in firebase. To push notification, You go to firebase console and create new notification in tab cloud message https://tppr.me/YVYPk
4. To remove reviews, you can delete this code https://tppr.me/uPWiP in lib/screens/detail/product_description.dart

**Comment by underscore15** [comment]
Sent email to minhcasi with subject as TICKET 1464

**Comment by minhcasi** [comment]
@underscore15 - thanks, we got it

**Comment by minhcasi** [comment]
@vumanhsn97 - please help for checking, also forward to your email - thank you!

**Comment by vumanhsn97** [comment]
@underscore15 
fixed in next version
You can fix by replacing files:
- lib/services/woo_commerce.dart to 
[woo_commerce.dart.zip](https://github.com/inspireui/support/files/3911080/woo_commerce.dart.zip)
- lib/widgets/backdrop_menu.dart to 
[backdrop_menu.dart.zip](https://github.com/inspireui/support/files/3911087/backdrop_menu.dart.zip)

Thanks!
