### ISSUE TITLE
Mobile App not Connected into Web

### ISSUE THREAD

**Issue by godofblack** [inspireui/support#1465]
Hey there .,
I install your Application but it's not shown any data ., throw can't get data from server Why ?!
i change the app url in src/common/AppConfig.json
 "Cezerin": {
    "url": "http://192.168.0.112:3001"
  },

But., it's still not working ! Kindly Provide Solution

**Comment by minhcasi** [comment]
Could you help to share the screenshot of purchase screenshot from http://codecayon.net/downloads  it's used to verify your proof of purchase? sorry for any inconvenience - Thank you!

**Comment by godofblack** [comment]
![Screenshot from 2019-11-27 16-58-08](https://user-images.githubusercontent.com/53173319/69719784-3c413000-1137-11ea-930e-dc46805c0998.png)

**Comment by godofblack** [comment]
Hey there ?! Any Update on this issue

**Comment by minhcasi** [comment]
@godofblack - from the mobile app simulator could you connect by the browser with this http://192.168.0.112:3001 ? You can try with the virtual host or upload the app into hosting with accessible IP or the publish domain - thank you!
