### ISSUE TITLE
[Flux Store] - checkout shipping issue 

### ISSUE THREAD

**Issue by MohammedSwefee** [inspireui/support#1466]
My issue is that I can't ship my product. error appears as below screenshots. also, I can't pick my place from map and countries list not shown properly.

Purchase code: 0ec77175-c961-49b0-acb6-d4e5b3f8e8d6

Screenshots:
![photo_2019-11-27_11-54-21](https://user-images.githubusercontent.com/34106827/69710305-37b55100-1110-11ea-800b-33a97d37f119.jpg)
![Annotation 2019-11-27 121503](https://user-images.githubusercontent.com/34106827/69710306-37b55100-1110-11ea-829f-f45febc203cd.png)
![photo_2019-11-27_11-49-46](https://user-images.githubusercontent.com/34106827/69710307-384de780-1110-11ea-94b1-b5a790a7ce04.jpg)
![photo_2019-11-27_11-50-02](https://user-images.githubusercontent.com/34106827/69710308-384de780-1110-11ea-8136-e01b81442135.jpg)
![photo_2019-11-27_11-50-08](https://user-images.githubusercontent.com/34106827/69710309-384de780-1110-11ea-89e7-020c48b64902.jpg)
![photo_2019-11-27_11-50-13](https://user-images.githubusercontent.com/34106827/69710310-384de780-1110-11ea-81c8-629b554d82b0.jpg)

mohammed.thaaer94@gmail.com

**Comment by minhcasi** [comment]
@MohammedSwefee - thank you for reporting

Could you open the common/config.dart and change the value ZoneIdShipping to match with your shipping zone from the Wordpress site ?

The country list and image flag could be changed from DefaultCountry of the same file

**Comment by minhcasi** [comment]
You can check this guide to setup the google api key to enalbe the location picker - https://docs.inspireui.com/fluxstore/firebase/#sms-login

**Comment by MohammedSwefee** [comment]
Dear Minhcasi,

    I tried to create billing account but there is no option to chose Iraq (my country) from the list. is it fine if I chose another country?

**Comment by MohammedSwefee** [comment]
for now, I don't need to use shipping or maps so I turned it off
