### ISSUE TITLE
[listapp]  - Expo desperate code for Expo sdk 35

### ISSUE THREAD

**Issue by Metacowboy** [inspireui/support#1467]
When Open Link with WebBrowser.openBrowserAsync  on ListingDetail.js will crash on the 
new expo Sdk 35

>import { WebBrowser } from 'expo'
//import { WebBrowser } from 'expo'
import * as WebBrowser from 'expo-web-browser'
App/Components/CommentIcons/index.js

-Map link 'Route' will crash
 
same for and many others expo imports 
import { Permissions} from 'expo-permissions'
//import { LinearGradient } from 'expo'
import { LinearGradient } from 'expo-linear-gradient'
...

False Google API Links correct links should be https 
 //`http://maps.googleapis.com/maps/api/geocode/json?address=${
 `https://maps.googleapis.com/maps/api/geocode/json?address=${

Pleas Update 
---------

3. Proof of my purchased: In Other Listapp Post

**Comment by minhcasi** [comment]
@concuacon - pls help for checking

**Comment by concuacon** [comment]
@Metacowboy I updated. Thank you.
