### ISSUE TITLE
[Beonews pro 3.0.4] - sign in or sign up + firebase

### ISSUE THREAD

**Issue by paulica40** [inspireui/support#1468]
using beonews v3.0.4

 1. login issue

i cant sign in or sign up with email and password....instead i manage to conect with facebook just fine.

2. firebase 
 i have this config

  // config for Firebase, use to sync user data across device and favorite post
  Firebase: {
    apiKey: "xxxxxxxxxxxxxxxxxxx",
    authDomain: "xxxxxxxx.firebaseapp.com",
    databaseURL: "https://xxxxxxx.firebaseio.com",
    projectId: "xxxxx",
    storageBucket: "ccibn-15e06.appspot.com",
    messagingSenderId: "1018570638776",
    appId: "1:1018570638776:web:40fe118d72eb63241a7b4d",
    measurementId: "G-NCK60JKGWD",
    readlaterTable: 'list_readlater',
  },

i dont see list_readlater table, it does not configure itself, enything i should do?

**Comment by paulica40** [comment]
purchase code:
029a5bbd-3911-40d1-893f-f6797bc53504

**Comment by minhcasi** [comment]
@paulica40 - could you help to attache the full config file (common/config.js and appconfig.json) - thank you!

**Comment by minhcasi** [comment]
@paulica40 - pls resend the config file so that we could help for checking, you can also send privately to support@inspireui.com - thanks

As there is not conversation I will close the ticket, kindly reopen if you need for any support - very best!
