### ISSUE TITLE
[Mstore pro] Could not connect to development server - Error

### ISSUE THREAD

**Issue by gnam389** [inspireui/support#1472]
How to fix this error. Thank you,
Image: https://i.imgur.com/KzaHB8h.png
![image](https://user-images.githubusercontent.com/20441846/69750936-94e8eb00-1180-11ea-9030-722b76fa38cb.png)

Buyer: giangnam389
E mới mua về hồi sáng, config vào rồi chạy lên nó báo lỗi đỏ như hình vậy là fix làm sao í bác, e chưa dùng lần nào nên ko rõ. cám ơn bác

**Comment by concuacon** [comment]
@gnam389 Bần đọc docs của react-native trước: https://facebook.github.io/react-native/docs/getting-started.html
Bạn có thể làm theo các bước sau:
- xoá thư mục node_modules/
- mở power shell lên và run theo lệnh sau: npm install ; cd android ; ./gradlew clean ; cd ../ ; react-native run-android
