### ISSUE TITLE
[Fluxstore pro] - if connect Opencart server  it stuck while checkout but in woocomerce there is no problem

### ISSUE THREAD

**Issue by Maksish** [inspireui/support#1473]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
 if connect Opencart server  it stuck while checkout but in woocomerce there is no problem
2. Screenshots issues:
![Screenshot_20191128-020820](https://user-images.githubusercontent.com/31925489/69757875-1726de80-1184-11ea-9d74-b06b557e8145.jpg)
![Screenshot_20191128-020822](https://user-images.githubusercontent.com/31925489/69757877-17bf7500-1184-11ea-94a0-46b28309981b.jpg)

3. Proof of my purchased:
![Screenshot from 2019-11-28 02-10-07](https://user-images.githubusercontent.com/31925489/69757918-40476f00-1184-11ea-9e7f-4bf9d726a400.png)

3. Config files (optional)

**Comment by minhtruong315** [comment]
@Maksish Did you install mstore extension? if you installed it, please send me admin info via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/1473

**Comment by Maksish** [comment]
orgom.com/admin
Dreamproject
Ajaykumar1@

**Comment by minhtruong315** [comment]
Please replace screens/cart.dart file to fix this issue
[cart.dart.zip](https://github.com/inspireui/support/files/3903172/cart.dart.zip)
when you switch between opencart and woo commerce. You must logout first.
