### ISSUE TITLE
[mv-store] - I can't leave Reviews or see reviews in the APP 

### ISSUE THREAD

**Issue by fernandoalfarocode** [inspireui/support#1474]
Hello, I have a problem with the configuration of the MV-Store APP (Expo version) since I cannot leave Reviews from the APP nor can I see the ones that already exist, I would like to know if you can help me with this problem, since the MStore-Checkout plugin is installed In Wordpress and the new version MStore-API gives me the same and even more problems so I use the old version.

Thank you in advance for your help.
---------
Screenshots issues:
https://ibb.co/MBSwR52
https://ibb.co/MBSwR52

Using the debug I have noticed that the problem is because the cookie that generates the code is invalid ... maybe with this info they could help me generate the correct cookie to solve the problem of not being able to leave a review

https://ibb.co/7YSS6Mt

Proof of my purchased:
https://ibb.co/Jv0sNwv

**Comment by minhcasi** [comment]
Hello, my problem is that I am trying to use the CLI version of Mstore Multivendor but I cannot start the APP on Android even though I have followed the instructions to apply the following commands specified in the Read me of the project:
yarn install
expo start
react-native run-android

I have the android studio and emulator environment installed and configured.
Thanks beforehand for your attention
Screenshots issues:
The app is built but there is an error building the main activity and the test APP fails
https://ibb.co/7knC1vs
https://ibb.co/27PXsn3

The app fails on the android test 

Note with checking, please help to create your all issues in one ticket to help us focus support better on your issue - thank you!

**Comment by fernandoalfarocode** [comment]
Hello, my message is to confirm that I have solved the problem to add reviews by changing the prop received from the cookie in the review / index component by user.tokenwp ...

https://ibb.co/37WK1yX

But the problem of not being able to see reviews persists, I have been debugging the data obtained in the detail / ReviewTab component and I receive an undefined data from the page even though the product has approved reviews, I was testing the URL generated by the API in the browser and I get data from it but in the APP the same URL stops working and sends me an undefined data, I hope my data is helpful to solve the problem.

Cheers

**Comment by minhtruong315** [comment]
@fernandoalfarocode you can add my skype: minhtruong315. i will help you check it via teamviewer

**Comment by fernandoalfarocode** [comment]
Hello, I do not find your user on Skype but I send you an invitation link to add me, I am contacted at this time onwards.

https://join.skype.com/invite/vAgmrv5xY7HZ

**Comment by minhtruong315** [comment]
@fernandoalfarocode I ping you on the skype. please check

**Comment by minhtruong315** [comment]
supported
