### ISSUE TITLE
[FluxStore] - Blog/posts don't load

### ISSUE THREAD

**Issue by mk4full** [inspireui/support#1475]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:

I am referring to https://github.com/inspireui/support/issues/1409

it still doesn't load my blog, what is wrong?

**Comment by minhtruong315** [comment]
@mk4full You only need change ```"blog": "https://saler.pl/blog",``` to ```"blog": "https://saler.pl",``` in config.dart to load blogs

**Comment by mk4full** [comment]
@minhtruong315  thank u, work :)
