### ISSUE TITLE
[MV-Store-CLI] - I can't start the MStore - MV version CLI project

### ISSUE THREAD

**Issue by fernandoalfarocode** [inspireui/support#1476]
Hello, my problem is that I am trying to use the CLI version of Mstore Multivendor but I cannot start the APP on Android even though I have followed the instructions to apply the following commands specified in the Read me of the project:
yarn install
expo start
react-native run-android

I have the android studio and emulator environment installed and configured.

Thanks beforehand for your attention
---------

Screenshots issues:
The app is built but there is an error building the main activity and the test APP fails
https://ibb.co/7knC1vs
https://ibb.co/27PXsn3

The app fails on the android test phone and stops abruptly
https://ibb.co/zN8TmWx

Proof of my purchased:
https://ibb.co/Jv0sNwv

**Comment by minhcasi** [comment]
Duplicate of #1476

Note with checking, please help to create your all issues in one ticket to help us focus support better on your issue - thank you!
