### ISSUE TITLE
[fluxstore Multivendor] - Invalid Arguments or you must include'username' var in your request when signup or sign in

### ISSUE THREAD

**Issue by incepio-flutter** [inspireui/support#1478]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
when I try to signup my users registers on firebase and dokan vendors but the app gives an exception of invalid arguments and does not take me to next context. I don't know where is the problem I have configured everything your documentation and I am raising this issue 2nd time so please minh casi, minh Pham or InspireUI team take this issue serious and help me. I have purchased a lot of your products and I am a very loyal and old customer of yours.
If i use demo.mstore.io server configuration my users register and signs in too it mean there is something wrong in the Website ! 

2. Screenshots issues:
<img width="1059" alt="Screenshot 2019-11-28 at 4 16 38 AM" src="https://user-images.githubusercontent.com/57838430/69765881-7a6e3c00-1197-11ea-9ef0-261ede62cb4e.png">
<img width="382" alt="Screenshot 2019-11-28 at 4 13 24 AM" src="https://user-images.githubusercontent.com/57838430/69766189-a4742e00-1198-11ea-8436-771580ae0813.png">

<img width="1433" alt="Screenshot 2019-11-28 at 4 12 10 AM" src="https://user-images.githubusercontent.com/57838430/69765888-82c67700-1197-11ea-8c10-ed3999832964.png">
<img width="1440" alt="Screenshot 2019-11-28 at 4 30 21 AM" src="https://user-images.githubusercontent.com/57838430/69765961-cd47f380-1197-11ea-9db3-8dd745e953f3.png">
<img width="1296" alt="Screenshot 2019-11-28 at 4 40 41 AM" src="https://user-images.githubusercontent.com/57838430/69766314-3f6d0800-1199-11ea-8d25-99d84a82908c.png">

3. Proof of my purchased:
![1573911414962](https://user-images.githubusercontent.com/57838430/69765917-a5f12680-1197-11ea-9794-dfc8fe564b70.JPEG)

3. Config files (optional)
I am using the website which you  provided us 
const serverConfig = {
  "type": "dokan",
  "url": "https://gamingsrebel.com",
  "consumerKey": "ck_0bc9e305615d1bab210085bb6180d89279d9978a",
  "consumerSecret": "cs_002a1584191ca2565746af31a843a476dac83f22",
  "blog": "https://gamingsrebel.com",
  "forgetPassword": "http://demo.mstore.io/wp-login.php?action=lostpassword"
};

**Comment by minhtruong315** [comment]
@incepio-flutter can you send me config.dart and admin account via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/1478

**Comment by EffectiveOG** [comment]
same error for me.. + humberger menu isn't in fixed position.

**Comment by minhtruong315** [comment]
@incepio-flutter pls check this solution to fix: https://github.com/Tmeister/wp-api-jwt-auth/issues/59#issuecomment-327149363

**Comment by incepio-flutter** [comment]
Thanks for your reply I am now able to signin and signup through the app but now there are  2 problems 
1st is I can't see upload products tile is user profile. I have configured the .htaccess and wp-config.php  as your docs said
2nd problem is whenever i select country this error pops up " getter country was called on null 
and also please tell me a way that I can apply CRUD opearations on user profile so that he can change his number and other info. 
Once again thanks for reply I will be looking forward to you If you want cpanel access i can provide you that but please make this app able to upload the products.
<img width="526" alt="Screenshot 2019-11-29 at 10 06 54 PM" src="https://user-images.githubusercontent.com/57838430/69883271-35f8b280-12f5-11ea-9022-ab375c9cc253.png">

<img width="419" alt="Screenshot 2019-11-29 at 10 03 36 PM" src="https://user-images.githubusercontent.com/57838430/69883013-1a40dc80-12f4-11ea-8618-eff9eff4e073.png">

<img width="419" alt="Screenshot 2019-11-29 at 10 05 12 PM" src="https://user-images.githubusercontent.com/57838430/69883075-54aa7980-12f4-11ea-9883-3455457a91bf.png">





> @incepio-flutter pls check this solution to fix: [Tmeister/wp-api-jwt-auth#59 (comment)](https://github.com/Tmeister/wp-api-jwt-auth/issues/59#issuecomment-327149363)
> and check question: Could not create new product (Fluxstore Multi Vendor)
> https://docs.inspireui.com/fluxstore/common-question/

**Comment by incepio-flutter** [comment]
Inspire Ui team?

**Comment by minhtruong315** [comment]
@incepio-flutter please check this commend: https://github.com/inspireui/support/issues/1480#issuecomment-559614342

**Comment by incepio-flutter** [comment]
> @incepio-flutter please check this commend: [#1480 (comment)](https://github.com/inspireui/support/issues/1480#issuecomment-559614342)

Thanks @minhtruong315  and please tell me I can't see the upload product after the sign in  or signup ! Please guide me here as well @minhcasi

**Comment by minhtruong315** [comment]
@incepio-flutter I will check them let you know

**Comment by incepio-flutter** [comment]
@minhtruong315  sir have you checked on it?

**Comment by incepio-flutter** [comment]
@minhcasi  Sir I want to Apply CRUD in user profile so that user can update his number and decsription  from the app. can you figure out  a way that I can do this  using wordpress ?

**Comment by minhtruong315** [comment]
@incepio-flutter You can replace fromAuthUser constructor in models/user.dart like this to see upload product
```
User.fromAuthUser(Map<String, dynamic> json, String _cookie) {
    try {
      cookie = _cookie;
      id = json['id'];
      name = json['displayname'];
      username = json['username'];
      firstName = json['firstname'];
      lastName = json['lastname'];
      email = json['email'];
      password = json['password'];
      picture = json['avatar'];
      loggedIn = true;
      var roles = json['role'] as List;
      var role = roles.firstWhere(
          (item) => ((item == 'seller') || (item == 'wcfm_vendor')),
          orElse: () => null);
      if (role != null) {
        isVender = true;
      } else {
        isVender = false;
      }
    } catch (e) {
      print(e.toString());
    }
  }
```

**Comment by incepio-flutter** [comment]
Thank you so much

**Comment by minhtruong315** [comment]
@incepio-flutter let me know if that solution fixed your issue

**Comment by incepio-flutter** [comment]
@minhcasi  and @minhtruong315  you guys  are love ! 
I am some issues and a update request for fluxstore multivendor. Here are the list of problems which I am facing right now 

**1.   Under shipping after checkout there is an exception "Resource doesnot exist"
2 I want to apply CRUD functionality so that user can update his/her information (phone number, address, short description from the app and then we can preview is under store_detail/contact.dart currently I have to enter data manually enter addition information from the wordpress/wp-admin but I want that I can update it from the app I don't want to use firebase please guide me if I am wrong @minhcasi. if you can release an update everyone will be thankful to you guys !!!!!!! 
3 I have 2 websites first is gamingsrebel.com and other is sjsbazar.com so at gamingsrebel.com I can upload product  but if I use restAPI of sjsbazar.com I can't upload product I can send you the video if you want to**  
this is the terminal report while uploading a product from app the website is sjsbazar.com
I/flutter ( 8569): https://sjsbazar.com/wp-content/uploads/2019/12/IMG_20191119_001925.png
I/flutter ( 8569): {code: woocommerce_product_image_upload_error, message: Error getting remote image https://sjsbazar.com/wp-content/uploads/2019/12/IMG_20191119_001925.png. Error: Not Found, data: {status: 400}}
I/flutter ( 8569): NoSuchMethodError: The getter 'length' was called on null.
I/flutter ( 8569): Receiver: null
I/flutter ( 8569): Tried calling: length
I/com.icepio.sou( 8569): Background young concurrent copying GC freed 42412(1903KB) AllocSpace objects, 20(2020KB) LOS objects, 48% free, 4232KB/8263KB, paused 5.056ms total 173.127ms
D/EGL_emulation( 8569): eglMakeCurrent: 0xdcfa9200: ver 3 0 (tinfo 0xbe09a6d0)

<img width="376" alt="dasdsadsadsad" src="https://user-images.githubusercontent.com/57838430/70374114-3276b400-1911-11ea-881d-633b73670e65.png">

<img width="376" alt="rewrww" src="https://user-images.githubusercontent.com/57838430/70374433-d4979b80-1913-11ea-98e6-1ab5f73e2ad9.png">
<img width="376" alt="rerr" src="https://user-images.githubusercontent.com/57838430/70374435-d82b2280-1913-11ea-87b5-f790cce28f4e.png">

**Comment by incepio-flutter** [comment]
@minhcasi  @minhcasi  there is one more problem when use vertical layout in config.json 
problem is in widget/vertical/index.dart
<img width="376" alt="Screenshot 2019-12-08 at 12 23 54 AM" src="https://user-images.githubusercontent.com/57838430/70380243-c53b4100-1959-11ea-943e-b30c23055a41.png">

**Comment by minhcasi** [comment]
@incepio-flutter - thank you for your suggestion 
- The dynamic shipping/zone is fixed on the latest version, will be available on next release
- the team is working on a new version that allows editing their profile info, it will be available soon

Please note about the license, when you integrate more website and delivery to app store, kindly purchase new Regular License for each website.

Very best!

**Comment by incepio-flutter** [comment]
@minhcasi  thank you so much if you are already working on the update. 
but for now how can i make shipping possible?

**Comment by minhtruong315** [comment]
@incepio-flutter you can try to replace getShippingMethods function on services/woo_commerce.dart like this
```
@override
  Future<List<ShippingMethod>> getShippingMethods(
      {Address address, String token}) async {
    try {
      List<ShippingMethod> list = [];
      var response = await wcApi.getAsync("shipping/zones");
      if (response is Map && isNotBlank(response["message"])) {
        throw Exception(response["message"]);
      } else {
        for (var zone in response) {
          final id = zone["id"];
          var response = await wcApi.getAsync("shipping/zones/$id/methods");
          if (response is Map && isNotBlank(response["message"])) {
            throw Exception(response["message"]);
          } else {
            var res = await wcApi.getAsync("shipping/zones/$id/locations");
            if (res is Map && isNotBlank(res["message"])) {
              throw Exception(res["message"]);
            } else {
              List locations = res;
              bool isValid = true;
              bool checkedPostcode = false;
              locations.forEach((o) {
                if (o["type"] == "country" && isValid) {
                  isValid = address.country == o["code"];
                }
                if (o["type"] == "postcode" &&
                    ((!checkedPostcode && isValid) ||
                        (checkedPostcode && !isValid))) {
                  isValid = address.zipCode == o["code"];
                  checkedPostcode = true;
                }
              });
              if (isValid) {
                for (var item in response) {
                  list.add(ShippingMethod.fromJson(item));
                }
              }
            }
          }
        }
      }
      return list;
    } catch (e) {
      //This error exception is about your Rest API is not config correctly so that not return the correct JSON format, please double check the document from this link https://docs.inspireui.com/fluxstore/woocommerce-setup/
      throw e;
    }
  }
```

**Comment by incepio-flutter** [comment]
is that it ? i can't move to next context on the button pressed . 

<img width="498" alt="Screenshot 2019-12-09 at 3 33 33 PM" src="https://user-images.githubusercontent.com/57838430/70428881-464d2200-1a99-11ea-87fe-243a84a5e351.png">

**Comment by minhtruong315** [comment]
Can you show me shipping setting in admin? Did you enter country, zip code correctly?

**Comment by incepio-flutter** [comment]
@minhtruong315  can i send you wp-admin account? 
I entered country, zip correctly

**Comment by minhtruong315** [comment]
This is my email: truong@inspireui.com
Please send me admin account with subject: https://github.com/inspireui/support/issues/1478

**Comment by incepio-flutter** [comment]
@minhtruong315  sir I am configuring my website will send you admin/pass soon. In the meantime please tell me why the shipping is not working. If you can list the name of plugins which are required and if any change in codebase  is required please let me know @minhcasi  I really need your help sir in the shipping, payments.
@minhcasi 
@minhtruong315 
looking forward to your reply;

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
