### ISSUE TITLE
[Fluxstore Pro] -  issues with the new version 1.5.9

### ISSUE THREAD

**Issue by Alnaggar94** [inspireui/support#1480]
- Issue No1:

When I click the country in the shipping information it shows a red screen with an error.

Screenshots of the issue:

Screenshots - https://imgur.com/4PgKLBP
Vidoe for the issue - https://imgur.com/OPg25cf
------------------------------------------------------------
- Issue No2:

When I add products to the cart the display name has a position issue in the Arabic language (RTL).

Screenshots of the issue - https://imgur.com/DICJvVx
------------------------------------------------------------

- Proof of my purchased:

https://imgur.com/a/9TsYcIf

- Config files (optional)

Config.dart - https://filebin.net/becvkrj8hww0zj70/config.dart?t=zsbmottl

Config.json - https://filebin.net/yawilsdcvbq0cdiy/config.json?t=k20muw5l
Config_ar.json - https://filebin.net/9v2zm8kiu7b5d6bi/config_ar.json?t=k3ydcajw

**Comment by minhtruong315** [comment]
You need to replace these files to fix issues
- screens/checkout/shipping_address.dart
- widgets/cart_item.dart
[Archive.zip](https://github.com/inspireui/support/files/3903148/Archive.zip)
