### ISSUE TITLE
[my-product] - Invalid VCS root mapping

### ISSUE THREAD

**Issue by nseven7** [inspireui/support#1481]
1. Invalid VCS root mapping 
2. ![333](https://user-images.githubusercontent.com/57550221/69808634-f6fa2c80-1222-11ea-9cae-fe12cc36f3bd.PNG)
3.
![3242](https://user-images.githubusercontent.com/57550221/69808690-185b1880-1223-11ea-9e0a-8bad859fbb1d.PNG)

**Comment by nseven7** [comment]
For the Invalid VCS root mapping error you can fix it by deleting the vcs.xml file located in the .idea folder of your project and then rebuild your project.

This helped me

**Comment by minhcasi** [comment]
@nseven7 - thank you for your sharing, We've noted for remove this folder when creating the download package - very best!
