### ISSUE TITLE
[FluxStore] - '_positions.isNotEmpty': ScrollController not attached to any scroll views.

### ISSUE THREAD

**Issue by hanyelbanna** [inspireui/support#1482]
Failed assertion: line 110 pos 12: '_positions.isNotEmpty': ScrollController not attached to any scroll views.

widgets/home/banner/banner_slider_items.dart:40:21)

widgets/home/banner/banner_slider_items.dart:43:23)

**Comment by hanyelbanna** [comment]
package:flutter_swiper/flutter_swiper.dart

**Comment by minhcasi** [comment]
Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads  it's used to verify your proof of purchase? sorry for any inconvenience - Thank you!

**Comment by hanyelbanna** [comment]
<img width="813" alt="Screen Shot 2019-11-29 at 8 41 44 AM" src="https://user-images.githubusercontent.com/22920591/69846153-3b69e480-1284-11ea-984a-89d8a9e36f09.png">

**Comment by minhcasi** [comment]
@hanyelbanna - sorry for the late response, could I know your username on Envato as I could get your detail from the screenshot?

Also, run this script to check your flutter setting "flutter channel stable" and "flutter clean"
Send us your "flutter doctor -v"

Make sure to download the latest version as well

**Comment by hanyelbanna** [comment]
username: hanyelbana

flutter doctor -v

[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.1 19B88, locale en-SA)
    • Flutter version 1.9.1+hotfix.6 at /Users/hany/Developer/flutter
    • Framework revision 68587a0916 (3 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/hany/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Users/hany/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/191.5977832/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Users/hany/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/191.5977832/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)



Also in AndroidManifest.xml
I get these errors:

<img width="391" alt="Screen Shot 2019-12-02 at 1 20 27 PM" src="https://user-images.githubusercontent.com/22920591/69951592-94e14600-1506-11ea-9438-65ca03301aaf.png">

<img width="462" alt="Screen Shot 2019-12-02 at 1 20 48 PM" src="https://user-images.githubusercontent.com/22920591/69951609-9b6fbd80-1506-11ea-86ef-80bb67a91325.png">


And when I try to correct @string/api_key as example requested from Android Studio .. it creates a new strings.xml file inside lib/res/values ... how can I make it points to android/app/src/main/res/values  ??

Thanks

**Comment by minhtruong315** [comment]
@hanyelbanna can you send me your source code via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/1482

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
