### ISSUE TITLE
[FluxStore Pro] - I am facing a Payment Method Problem on my Fluxstore App

### ISSUE THREAD

**Issue by Usman1493** [inspireui/support#1483]
I have disabled all the payment options in the config file.. Still it shows me this error at the payment screen.
How can I resolve this. I only want to display the Cash on Delivery Option..
A Screenshot of the error is as follows.

https://prnt.sc/q3hfmb

**Comment by minhcasi** [comment]
Could you help to share the screenshot of purchase screenshot from http://codecayon.net/downloads  it's used to verify your proof of purchase? sorry for any inconvenience - Thank you!

**Comment by Usman1493** [comment]
No Problem, here is the screenshot from the downloads section.

![download proof](https://user-images.githubusercontent.com/30326249/69847290-7ece4e00-1298-11ea-9a86-92a780f00d3c.PNG)

**Comment by Usman1493** [comment]
Any update regarding this?

**Comment by UTimung** [comment]
i also disabled COD on some shipping zone

but app showing COD in every shipping zone

**Comment by minhcasi** [comment]
@minhtruong315 - could you update the patching for this issue - thanks

**Comment by minhtruong315** [comment]
@Usman1493 can you send me config.dart file and admin info via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/1483

**Comment by minhtruong315** [comment]
@Usman1493 Disable Shipping only work with woo commerce. Magento and Opencart must EnableShipping

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!

**Comment by Usman1493** [comment]
I have enabled the Shipping but the error is still getting reproduced.

I have sent the email with my config.dat file to truong@inspireui.com

Please reopen this issue

**Comment by Usman1493** [comment]
I enabled the Shipping method but the error is still getting reproduced.
I have sent you an email with my config.dat file.

**Comment by minhtruong315** [comment]
pls update the latest source code on codecanyon and try again

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
