### ISSUE TITLE
FluxStore

### ISSUE THREAD

**Issue by MrrHak** [inspireui/support#1484]
---------

My issue: is error at Home page when I use VerticalLayout for display recent product.

[config.zip](https://github.com/inspireui/support/files/3903971/config.zip)

![verticleLayout-issue](https://user-images.githubusercontent.com/42771980/69847971-3f5d2d00-12ab-11ea-8b12-ff2527d7363d.png)

![purchased proof](https://user-images.githubusercontent.com/42771980/69847977-4421e100-12ab-11ea-8886-f733e218502f.png)

**Comment by minhcasi** [comment]
@MrrHak - could you try to check the download version as we have refactored the config.json to multi-file to support for multi-language -> the new name should be like -> "name": "Recent Collection"

**Comment by MrrHak** [comment]
I use your latest version source code and it's already implement multi-language with name "Recent Collections" you will sell it in my config.json file I use you original "config_theme10.json" it still error please check it. Thanks

**Comment by minhcasi** [comment]
@MrrHak - we got the root cause issue.

@minhtruong315 - please update new config_theme10.json to match with new refactor of the config - and also another related theme - thank you!

**Comment by MrrHak** [comment]
sorry  I don't understand please give me more details

**Comment by minhtruong315** [comment]
@MrrHak I will update all config.json on theme. We changed multilanguage for config file.

**Comment by MrrHak** [comment]
When this update available for download?

**Comment by minhtruong315** [comment]
[woocommerce.zip](https://github.com/inspireui/support/files/3908350/woocommerce.zip)
I updated config.json on theme. Please use it

**Comment by MrrHak** [comment]
Yes, Thank you
