### ISSUE TITLE
[FluxStore] -  Shipping method shows zero

### ISSUE THREAD

**Issue by UTimung** [inspireui/support#1485]
Shipping method shows zero

If add 5$ in flat rate cost Shipping method show correct amount

But if add 5* [qty] Than in shipping method page It shows error, “Format exception invalid double 5 *[qty]

If i leave blank in flat rate cost

And add the shipping amount in shipping class

Than the app will show zero shipping charge

![Screenshot_20191129-122121](https://user-images.githubusercontent.com/18107447/69849640-4f710e80-12a3-11ea-96bb-b82ea4f69e11.png)

![Screenshot_20191129-122203~2](https://user-images.githubusercontent.com/18107447/69849654-5861e000-12a3-11ea-9812-19ba82826ea5.png)

**Comment by minhcasi** [comment]
@UTimung - could you help to attach your config files here (common/config.dart and conifg.json) so that we could help for checking - thank you!

**Comment by UTimung** [comment]
config dart https://drive.google.com/open?id=1po7-Fj5bpH2IXci9ZEAcUBz4LL4u3qqU

config.json  https://drive.google.com/open?id=1AsMpw5hLRFkc-6uIyPz1Yh417K5vhsRI

**Comment by UTimung** [comment]
Waiting

**Comment by UTimung** [comment]
Why not responding?

**Comment by minhcasi** [comment]
@minhtruong315 - pls help for checking - thanks

**Comment by UTimung** [comment]
Help please

**Comment by minhtruong315** [comment]
@UTimung can you send me admin account via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/1485

**Comment by UTimung** [comment]
I sent you an email, please check

**Comment by minhtruong315** [comment]
[Archive.zip](https://github.com/inspireui/support/files/3909010/Archive.zip)
@UTimung please replace these files to fix shipping cost issues

**Comment by UTimung** [comment]
Hello
In app shipping costs are now showing

But the shipping cost data are not sending to woocommerce

It shows shipping ZERO in woocommerce order details

![Screenshot_20191202-114559~2](https://user-images.githubusercontent.com/18107447/69936233-32377c80-14fd-11ea-86ea-89dc9d34a6e8.png)
![Screenshot_20191202-121159~2](https://user-images.githubusercontent.com/18107447/69936251-3f546b80-14fd-11ea-8c07-80a97bd48511.png)

**Comment by minhtruong315** [comment]
supported.
