### ISSUE TITLE
[Fluxstore Pro] - Translation fields missing 

### ISSUE THREAD

**Issue by Alnaggar94** [inspireui/support#1486]
1. My issue:

1. The following translation fields are missing (see screenshots)

2. In the Sign-in screen (Arabic language RTL) the "Reset" text supposed to be on the opposite side. (see screenshots) - https://imgur.com/xx0cN2h

2. Screenshots issues:

* Coupon section - https://imgur.com/a/Yy3eG8R
* After placing an order - https://imgur.com/bU9vMLa
* Welcome screen (I changed the default language to Arabic) -  https://imgur.com/a/lw1OjLL
3. Proof of my purchased:

   https://imgur.com/a/9TsYcIf

3. Config files (optional)

   Config.dart - https://filebin.net/becvkrj8hww0zj70/config.dart?t=zsbmottl

   Config.json - https://filebin.net/yawilsdcvbq0cdiy/config.json?t=k20muw5l
   Config_ar.json - https://filebin.net/9v2zm8kiu7b5d6bi/config_ar.json?t=k3ydcajw

**Comment by minhcasi** [comment]
@minhtruong315 - pls help for checking this issue - thanks

**Comment by minhtruong315** [comment]
@Alnaggar94 I will fix these issues. thanks

**Comment by minhtruong315** [comment]
I updated all language issues. It will be available in next release

**Comment by Alnaggar94** [comment]
@minhtruong315 Thank you so much for your helping, Also there is a translation missing in the login with SMS screen :

![tempsnip](https://user-images.githubusercontent.com/49800146/69962730-a97e0800-151f-11ea-952f-fe6457b30209.jpg)

When you will release the new update? Is it gonna take a long time?

**Comment by Alnaggar94** [comment]
Also, there is a translation missing in the sign-up screen 

![Capture](https://user-images.githubusercontent.com/49800146/70143017-97c96b80-16ab-11ea-88e8-cb7ac14c4b28.JPG)

**Comment by minhtruong315** [comment]
Yes. I updated all. You can update it when we release new version. There are more changes so I can't tell you how to fix it
