### ISSUE TITLE
[Fluxstore] - error in shipping method

### ISSUE THREAD

**Issue by rodrigoalves1901** [inspireui/support#1489]
Hello. I upgraded to the new version and the following message appears. There is an issue with the app during request the date.
I made a video demonstrating the wordpress error and configuration.

https://streamable.com/llq61

**Comment by UTimung** [comment]
Same problem

**Comment by kurkuteabhi** [comment]
**### I also have same issue with app**

![purches](https://user-images.githubusercontent.com/43174699/69886311-5e89a800-1307-11ea-8638-6592999962b8.jpg)
![Screenshot_20191128-152302](https://user-images.githubusercontent.com/43174699/69886313-5f223e80-1307-11ea-9ec1-2447715dca1d.png)

**Comment by UTimung** [comment]
For Red text error
You have to enter shipping method ID in config.dart

**Comment by rodrigoalves1901** [comment]
Mine is configured this way, it should appear.

"ZoneIdShipping": [1, 2],

**Comment by UTimung** [comment]
You have to replace the [1,2]
To your shipping method id

**Comment by rodrigoalves1901** [comment]
Now it's gone, you can't leave [1,2] if you only have 1 shipping method, as I had only one shipping method and i just left [1] and it worked. But he does not calculate the freight of the post office is still coming reset.

![image](https://user-images.githubusercontent.com/43248152/69887831-5574e880-12bf-11ea-8840-42aaead539e6.png)

**Comment by UTimung** [comment]
For me also Same problem

![Screenshot_20191129-122121](https://user-images.githubusercontent.com/18107447/69894399-46d11480-1345-11ea-8e04-65abf70fe171.png)

**Comment by minhcasi** [comment]
Related ticket #1485

The team is checking and will keep an update - thank you!

**Comment by UTimung** [comment]
Waiting

**Comment by minhcasi** [comment]
Related to #1452

**Comment by UTimung** [comment]
but i'm not using any table rate plugin #1452

**Comment by minhtruong315** [comment]
@rodrigoalves1901  You can replace getShippingMethods function in services/woo_commerce.dart file to fix this issue
```
@override
  Future<List<ShippingMethod>> getShippingMethods(
      {Address address, String token}) async {
    try {
      List<ShippingMethod> list = [];
      var response = await wcApi.getAsync("shipping/zones");
      if (response is Map && isNotBlank(response["message"])) {
        throw Exception(response["message"]);
      } else {
        for (var zone in response) {
          final id = zone["id"];
          var response = await wcApi.getAsync("shipping/zones/$id/methods");
          if (response is Map && isNotBlank(response["message"])) {
            throw Exception(response["message"]);
          } else {
            var res = await wcApi.getAsync("shipping/zones/$id/locations");
            if (res is Map && isNotBlank(res["message"])) {
              throw Exception(res["message"]);
            } else {
              List locations = res;
              bool isValid = true;
              bool checkedPostcode = false;
              locations.forEach((o) {
                if (o["type"] == "country" && isValid) {
                  isValid = address.country == o["code"];
                }
                if (o["type"] == "postcode" &&
                    ((!checkedPostcode && isValid) ||
                        (checkedPostcode && !isValid))) {
                  isValid = address.zipCode == o["code"];
                  checkedPostcode = true;
                }
              });
              if (isValid) {
                for (var item in response) {
                  list.add(ShippingMethod.fromJson(item));
                }
              }
            }
          }
        }
      }
      return list;
    } catch (e) {
      //This error exception is about your Rest API is not config correctly so that not return the correct JSON format, please double check the document from this link https://docs.inspireui.com/fluxstore/woocommerce-setup/
      throw e;
    }
  }
```

**Comment by UTimung** [comment]
> @rodrigoalves1901 You can replace getShippingMethods function in services/woo_commerce.dart file to fix this issue
> 
> ```
> @override
>   Future<List<ShippingMethod>> getShippingMethods(
>       {Address address, String token}) async {
>     try {
>       List<ShippingMethod> list = [];
>       var response = await wcApi.getAsync("shipping/zones");
>       if (response is Map && isNotBlank(response["message"])) {
>         throw Exception(response["message"]);
>       } else {
>         for (var zone in response) {
>           final id = zone["id"];
>           var response = await wcApi.getAsync("shipping/zones/$id/methods");
>           if (response is Map && isNotBlank(response["message"])) {
>             throw Exception(response["message"]);
>           } else {
>             var res = await wcApi.getAsync("shipping/zones/$id/locations");
>             if (res is Map && isNotBlank(res["message"])) {
>               throw Exception(res["message"]);
>             } else {
>               List locations = res;
>               bool isValid = true;
>               bool checkedPostcode = false;
>               locations.forEach((o) {
>                 if (o["type"] == "country" && isValid) {
>                   isValid = address.country == o["code"];
>                 }
>                 if (o["type"] == "postcode" &&
>                     ((!checkedPostcode && isValid) ||
>                         (checkedPostcode && !isValid))) {
>                   isValid = address.zipCode == o["code"];
>                   checkedPostcode = true;
>                 }
>               });
>               if (isValid) {
>                 for (var item in response) {
>                   list.add(ShippingMethod.fromJson(item));
>                 }
>               }
>             }
>           }
>         }
>       }
>       return list;
>     } catch (e) {
>       //This error exception is about your Rest API is not config correctly so that not return the correct JSON format, please double check the document from this link https://docs.inspireui.com/fluxstore/woocommerce-setup/
>       throw e;
>     }
>   }
> ```

after replace,
Still showing zero

**Comment by minhtruong315** [comment]
That solution only fix for issues of @rodrigoalves1901. not you.
Can you send me admin info website to email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/1489
I need to check your website first

**Comment by rodrigoalves1901** [comment]
Good Morning. No effect on code modification. Still remains zero. 
I passed the site access in the email.

**Comment by minhtruong315** [comment]
I dont see any email. Can you send me admin info via my email?

**Comment by rodrigoalves1901** [comment]
sent to truong@inspireui.com

**Comment by minhtruong315** [comment]
I see you installed plugin Claudio Sanches - Correios for WooCommerce
for shipping. But we haven't supported this plugin yet.

**Comment by rodrigoalves1901** [comment]
More in Brazil we use the delivery method of the post office. How I will do? If it doesn't work the app doesn't work for me.
