### ISSUE TITLE
[BeoNews] Can I change to categories order?

### ISSUE THREAD

**Issue by HoYeongSong** [inspireui/support#149]
Product: Beonews pro
Your Purchased Code: 9f64a72f-f65c-4ecb-89ab-c109e7863821
we may not reply if you are not our customer)

I want to change categories order to reverse. For example, [1-2-3] => [3-2-1].

and When I write korean in search component. It has some bug like screenshot.

Help me please!

<img width="297" alt="2019-01-02 11 02 49" src="https://user-images.githubusercontent.com/38429067/50578514-7bf78d00-0e7e-11e9-9d3c-3657fea3d963.png">

<img width="190" alt="2019-01-02 11 02 39" src="https://user-images.githubusercontent.com/38429067/50578516-8580f500-0e7e-11e9-918f-ea1411f3d421.png">

**Comment by luyx2412** [comment]
Hi @HoYeongSong , You can based on the article RTL to reverse https://facebook.github.io/react-native/blog/2016/08/19/right-to-left-support-for-react-native-apps.

- In App.js file
  ```
Import { I18nManager } from "react-native"

ComponentDidMount() {
 I18nManager.forceRTL(true);
}
```

Thanks

**Comment by luyx2412** [comment]
Hi @HoYeongSong The easiest way to reverse your category list is reverse `categories` value https://www.geeksforgeeks.org/javascript-array-prototype-reverse/

In `Container/Category/index.js` --> in `renderContent` function you will see `categories`. Using the reserve function look like the article to reverse your category.

<img width="664" alt="screen shot 2019-01-05 at 8 55 03 pm" src="https://user-images.githubusercontent.com/8909619/50725199-a53d4500-112c-11e9-8b7a-fd3d8d8d09f1.png">
Thanks
