### ISSUE TITLE
[MStore Pro] How to install Wordpress demo MStore and Sync with MStore Pro apk

### ISSUE THREAD

**Issue by antixirus** [inspireui/support#1490]
Somebody can help me? Im new buyer MStore Pro...
Sorry for my bad english

**Comment by minhcasi** [comment]
Hi, please help to check this video to install the mstore demo - https://www.youtube.com/watch?v=CEyfZmzBMTw&t=1337s (this product fluxstore is not related to mstore but the demo website installing is the same) - thank you!
