### ISSUE TITLE
User Registration Giving error

### ISSUE THREAD

**Issue by pixelpromote** [inspireui/support#1491]
User Registration API giving error "Cannot create user with empty login name
![1575094743568000_1822735147](https://user-images.githubusercontent.com/58021725/69896902-59aa1000-136a-11ea-94a6-fd0cec88c32f.png)
![1575093717026000_1822735147](https://user-images.githubusercontent.com/58021725/69896907-6a5a8600-136a-11ea-9722-03a9768608a2.png)

"

**Comment by concuacon** [comment]
@pixelpromote Please follow this link https://github.com/inspireui/support/issues/1406#issuecomment-555421606 I think it will help you

**Comment by pixelpromote** [comment]
Great it worked! Now the issue is that only username is being stored in the database but not the email id. How t fix this?

**Comment by minhcasi** [comment]
@concuacon
