### ISSUE TITLE
[fluxstore] - Razorpay not Working

### ISSUE THREAD

**Issue by Dhavalkatrodiya** [inspireui/support#1492]
My issue:

hi,  when i select razorpay & place my order, nothing happens just loading icon appears(see screenshot)

    Screenshots issues:
    https://snipboard.io/53Z6Fv.jpg

    Proof of my purchased:
    https://snipboard.io/6EgT7k.jpg

    Config files (optional)
.dart
https://codeshare.io/aJBOOX

.json
https://codeshare.io/2B4EEx

**Comment by minhtruong315** [comment]
@Dhavalkatrodiya Can you send me config.dart and admin account via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/1492

**Comment by Dhavalkatrodiya** [comment]
ok

**Comment by Dhavalkatrodiya** [comment]
mail has been sent

**Comment by Dhavalkatrodiya** [comment]
Note: This is digital download website, it doesn’t have any shipping method, user purchase an item & download it right away.

**Comment by minhtruong315** [comment]
We dont support business like your website.
