### ISSUE TITLE
[Cestore] - SwipeRow doesn't close after delete

### ISSUE THREAD

**Issue by ahmadyousefdev** [inspireui/support#1493]
1. My issue:

In `src/containers/Cart/MyCart/index.js` swipeRow doesn't close after deleting an item and continues the next item. I want the delete button to be hidden after deleting the item. I don't want it to continue to the next item. Is this possible ?

Thanks!

2. Screenshots issues:

![clickable](https://user-images.githubusercontent.com/19305025/69901950-22068c80-1399-11ea-930f-5a382a69923d.gif)

3. Proof of my purchased:  _(Should I paste my Purchase Code here ?)_

**Comment by ahmadyousefdev** [comment]
There is this [solution](https://github.com/jemise111/react-native-swipe-list-view/issues/364) , but I didn't know how to implement it. Can you help me guys? Thanks!

**Comment by minhcasi** [comment]
@ahmadyousefdev - this could be the bug of the current version, let me forward to my team for checking and they will let you know - thank you!

**Comment by minhtruong315** [comment]
@ahmadyousefdev I checked on my source code. it's working well. can you share me your teamviewer? i will help you check it

**Comment by ahmadyousefdev** [comment]
@minhtruong315 , actually the screenshot in the first comment is from [your app on google play](https://play.google.com/store/apps/details?id=com.inspireui.cestore&hl=en) . The code in my application for the page `src/containers/Cart/MyCart/index.js` is the same as in your original app code `CeStore-1.3.0` ..

I even upgraded `react-native-swipe-list-view` to `^2.0.6` but with no luck.

I would love to give you teamviewer but please read my comment above, if I have something wrong please tell me so I don't waste your precious time :)

_ps, if there is nothing wrong, how can I send you the teamviewer , on email maybe?_

**Comment by minhtruong315** [comment]
@ahmadyousefdev You can fix it at containers/Cart/MyCart/index.js
change key={`cart${index}`} to key={item.product.id}

**Comment by ahmadyousefdev** [comment]
That fixed it! .. Thank you so much

Great Support as always!
