### ISSUE TITLE
[my-product] - Flux store

### ISSUE THREAD

**Issue by nseven7** [inspireui/support#1494]
1. Even After replacing the logo.png in the asset file, still I see only Fluxstore logos.
The icon has changed, but the logo and color are not

**Comment by minhcasi** [comment]
@nseven7 - could you help to take the screenshot of this issue, and also share the proof of your purchase from http://codecayon.net/downloads - thank you!

**Comment by nseven7** [comment]
![1](https://user-images.githubusercontent.com/57550221/69911048-67d25c00-1450-11ea-8e53-dfb18bdb156d.PNG)
![2](https://user-images.githubusercontent.com/57550221/69911049-6d2fa680-1450-11ea-982e-a3e40f2d21f1.PNG)
![3](https://user-images.githubusercontent.com/57550221/69911050-71f45a80-1450-11ea-84e6-76f35140e95b.PNG)
![3242](https://user-images.githubusercontent.com/57550221/69911051-7ae52c00-1450-11ea-8753-51650649cdd2.PNG)

**Comment by minhcasi** [comment]
@vumanhsn97 - pls help for suggestion

**Comment by vumanhsn97** [comment]
@nseven7 Not found your issue! You can run cmd: "flutter clean" before run app

**Comment by minhcasi** [comment]
@nseven7 - as there is no response on this ticket, we assume you have resolved the issue, please let us know if you have any further issue by creating a new ticket - very best!
