### ISSUE TITLE
fluxstore failed to build ios

### ISSUE THREAD

**Issue by nizarweb77** [inspireui/support#1495]
7347f2d1-d5aa-4bc0-b6f3-0e2cf237c3de - 1 Nov 2019
************************************************************
i have tried many time to build the ios in imac but its failed many time 

2019-11-30 14:22:28.131 xcodebuild[39373:456543] Malformed bundle does not contain an identifier at /Library/Developer/CoreSimulator/Profiles/Runtimes/watchOS 4.1.simruntime
    2019-11-30 14:22:28.133 xcodebuild[39373:456543] Malformed bundle does not contain an identifier at /Library/Developer/CoreSimulator/Profiles/Runtimes/tvOS 11.1.simruntime
    2019-11-30 14:22:28.133 xcodebuild[39373:456543] Malformed bundle does not contain an identifier at /Library/Developer/CoreSimulator/Profiles/Runtimes/watchOS 4.0.simruntime
    2019-11-30 14:22:28.139 xcodebuild[39373:456543] Malformed bundle does not contain an identifier at /Library/Developer/CoreSimulator/Profiles/Runtimes/tvOS 11.0.simruntime
    2019-11-30 14:22:28.327 xcodebuild[39373:456540] Malformed bundle does not contain an identifier at /Library/Developer/CoreSimulator/Profiles/Runtimes/watchOS 4.1.simruntime
    2019-11-30 14:22:28.328 xcodebuild[39373:456540] Malformed bundle does not contain an identifier at /Library/Developer/CoreSimulator/Profiles/Runtimes/tvOS 11.1.simruntime
    2019-11-30 14:22:28.329 xcodebuild[39373:456540] Malformed bundle does not contain an identifier at /Library/Developer/CoreSimulator/Profiles/Runtimes/watchOS 4.0.simruntime
    2019-11-30 14:22:28.335 xcodebuild[39373:456540] Malformed bundle does not contain an identifier at /Library/Developer/CoreSimulator/Profiles/Runtimes/tvOS 11.0.simruntime
    ** BUILD FAILED **

Xcode's output:
↳
    In file included from /Users/user161080/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/uni_links-0.2.0/ios/Classes/UniLinksPlugin.m:1:
    /Users/user161080/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/uni_links-0.2.0/ios/Classes/UniLinksPlugin.h:4:4: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
    + (instancetype)sharedInstance;
       ^
    /Users/user161080/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/uni_links-0.2.0/ios/Classes/UniLinksPlugin.h:4:4: note: insert '_Nullable' if the pointer may be null
    + (instancetype)sharedInstance;
       ^
                    _Nullable
    /Users/user161080/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/uni_links-0.2.0/ios/Classes/UniLinksPlugin.h:4:4: note: insert '_Nonnull' if the pointer should never be null
    + (instancetype)sharedInstance;
       ^
                    _Nonnull
    /Users/user161080/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/uni_links-0.2.0/ios/Classes/UniLinksPlugin.h:7:33: warning: block pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
          restorationHandler:(void (^)(NSArray *_Nullable))restorationHandler;
                                    ^
    /Users/user161080/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/uni_links-0.2.0/ios/Classes/UniLinksPlugin.h:7:33: note: insert '_Nullable' if the block pointer may be null
          restorationHandler:(void (^)(NSArray *_Nullable))restorationHandler;
                                    ^
                                     _Nullable
    /Users/user161080/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/uni_links-0.2.0/ios/Classes/UniLinksPlugin.h:7:33: note: insert '_Nonnull' if the block pointer should never be null
          restorationHandler:(void (^)(NSArray *_Nullable))restorationHandler;
                                    ^
                                     _Nonnull
    2 warnings generated.
    In file included from /Users/user161080/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/uni_links-0.2.0/ios/Classes/UniLinksPlugin.m:1:
    /Users/user161080/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/uni_links-0.2.0/ios/Classes/UniLinksPlugin.h:4:4: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
    + (instancetype)sharedInstance;
       ^
    /Users/user161080/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/uni_links-0.2.0/ios/Classes/UniLinksPlugin.h:4:4: note: insert '_Nullable' if the pointer may be null
    + (instancetype)sharedInstance;
       ^
                    _Nullable
    /Users/user161080/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/uni_links-0.2.0/ios/Classes/UniLinksPlugin.h:4:4: note: insert '_Nonnull' if the pointer should never be null
    + (instancetype)sharedInstance;
       ^
                    _Nonnull
    /Users/user161080/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/uni_links-0.2.0/ios/Classes/UniLinksPlugin.h:7:33: warning: block pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
          restorationHandler:(void (^)(NSArray *_Nullable))restorationHandler;
                                    ^
    /Users/user161080/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/uni_links-0.2.0/ios/Classes/UniLinksPlugin.h:7:33: note: insert '_Nullable' if the block pointer may be null
          restorationHandler:(void (^)(NSArray *_Nullable))restorationHandler;
                                    ^
                                     _Nullable
    /Users/user161080/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/uni_links-0.2.0/ios/Classes/UniLinksPlugin.h:7:33: note: insert '_Nonnull' if the block pointer should never be null
          restorationHandler:(void (^)(NSArray *_Nullable))restorationHandler;
                                    ^
                                     _Nonnull
    2 warnings generated.
    /Users/user161080/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0.4.0/ios/Classes/RateMyAppPlugin.m:15:30: warning: 'requestReview' is only available on iOS 10.3 or newer [-Wunguarded-availability]
        [SKStoreReviewController requestReview];
                                 ^~~~~~~~~~~~~~
    In module 'StoreKit' imported from /Users/user161080/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0.4.0/ios/Classes/RateMyAppPlugin.m:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/System/Library/Frameworks/StoreKit.framework/Headers/SKStoreReviewController.h:22:1: note: 'requestReview' has been marked as being introduced in iOS 10.3 here, but the deployment target is iOS 8.0.0
    + (void)requestReview API_AVAILABLE(ios(10.3), macos(10.14)) __TVOS_PROHIBITED;
    ^
    /Users/user161080/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0.4.0/ios/Classes/RateMyAppPlugin.m:15:30: note: enclose 'requestReview' in an @available check to silence this warning
        [SKStoreReviewController requestReview];
                                 ^~~~~~~~~~~~~~
    /Users/user161080/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0.4.0/ios/Classes/RateMyAppPlugin.m:15:6: warning: 'SKStoreReviewController' is only

**Comment by minhcasi** [comment]
@nizarweb77 - could you try to run "flutter doctor -v" and send us the result?

**Comment by nizarweb77** [comment]
Users/user161080/Desktop/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, v1.9.1+hotfix.5, on Mac OS X 10.14.6 18G1012, locale en)
    • Flutter version 1.9.1+hotfix.5 at /Users/user161080/Desktop/flutter
    • Framework revision 1aedbb1835 (6 weeks ago), 2019-10-17 08:37:27 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[!] Android toolchain - develop for Android devices (Android SDK version 26.0.1)
    • Android SDK at /usr/local/Caskroom/android-sdk/3859397,26.0.1
    • Android NDK location not configured (optional; useful for native profiling support)
    ✗ Flutter requires Android SDK 28 and the Android BuildTools 28.0.3
      To update using sdkmanager, run:
        "/usr/local/Caskroom/android-sdk/3859397,26.0.1/tools/bin/sdkmanager" "platforms;android-28" "build-tools;28.0.3"
      or visit https://flutter.dev/setup/#android-setup for detailed instructions.
    ✗ Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    ✗ Xcode requires additional components to be installed in order to run.
      Launch Xcode and install additional required components when prompted.
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Community Edition (version 2018.2.6)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.39.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Connected device
    ! No devices available

! Doctor found issues in 5 categories.
Process finished with exit code 0

**Comment by nizarweb77** [comment]
really the build ios give me hard time
note : i already have ios developer account and i have also imac 
will be nice if you make video in how we can publish to app store and build the app alos setup the fiirebase this is will be helpful to all your customer

**Comment by minhcasi** [comment]
Hi, you need to resolve these error from the tool to run the project, try to open XCode:

✗ Xcode requires additional components to be installed in order to run.
Launch Xcode and install additional required components when prompted.


Pls try to use this guide and make sure you can run the Test Drive successful - https://flutter.dev/docs/get-started/test-drive

**Comment by nizarweb77** [comment]
you guys never help with proper solution really bad suppppport

**Comment by nizarweb77** [comment]
all the time go and read this and never give solution

**Comment by minhcasi** [comment]
ok, we could help for teamviewer remote to help fix on your PC - let us know when you are available - thanks

**Comment by minhcasi** [comment]
@minhtruong315 - pls help for this issue

**Comment by minhtruong315** [comment]
@nizarweb77 add my skype: minhtruong315
i will help you check via teamviewer

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!

**Comment by nizarweb77** [comment]
sorry for the late sir 
this is my rdp imac 
https://mega.nz/#!ZcoTAIrQ!-zFIfCz0HdPAGHEVxVmgtRhVLrdNyrGOwYgFId-8hxQ
you will find the user name and the password my rdb have high connection will be fast for you and strong rdp .
i have put my work in android studio alerday 
so my problem is the firebase for android not working i alerday add  to the android folder and for the ios i put the .plist file of the firebase in the desktop please fix for me with the build problem 
i will appreciate what you will do sir

**Comment by minhcasi** [comment]
#1544

**Comment by netdreamland** [comment]
I have same issue on the latest 1.5.9, may I know how to fix this?
