### ISSUE TITLE
[FluxStore-WooCommerce] - Gradle Problem

### ISSUE THREAD

**Issue by Madraka** [inspireui/support#1498]
Hi, i have gradle problem

Launching lib\main.dart on SM G960F in debug mode...
Initializing gradle...
Resolving dependencies...
* Error running Gradle:
ProcessException: Process "C:\src\market2\android\gradlew.bat" exited abnormally:

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\src\market2\android\app\build.gradle' line: 81

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not find method testImplementation() for arguments [junit:junit:4.12] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUİLD FAILED in 5s
  Command: C:\src\market2\android\gradlew.bat app:properties

Finished with error: Please review your Gradle project setup in the android/ folder.

---------

1. My issue:
Gradle error
2. Screenshots issues:

3. Proof of my purchased:

3. Config files (optional)

**Comment by minhcasi** [comment]
Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads  it's used to verify your proof of purchase? sorry for any inconvenience - Thank you!

Also, make sure you can pass this Test Drive guide - https://flutter.dev/docs/get-started/test-drive
