### ISSUE TITLE
[ASKED] I Can't Customization MStore Pro App with CE Builder, the spesific (Run Android Setup)

### ISSUE THREAD

**Issue by antixirus** [inspireui/support#1499]
Hallo Sir, can you help me, to install and configure the CE Builder for MStore Pro, All Required Plugins is Good, but error :( Need Video tutorial
*Text Error*
Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

Remove-Item : A parameter cannot be found that matches parameter name 'rf'.
At C:\Users\ASUS\Downloads\codecanyon-u5KBuUQB-beostore-complete-react-native-template-for-ecommerce\mstore-3.9.6\mstor
e-pro\scripts\cebuilder.ps1:2 char:4
+ rm -rf node_modules/
+    ~~~
    + CategoryInfo          : InvalidArgument: (:) [Remove-Item], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand

npm WARN deprecated superagent@4.1.0: Please note that v5.0.1+ of superagent removes User-Agent header by default, therefore you may need to add it yourself (e.g. GitHub blocks requests without a User-Agent header).  This notice will go away with v5.0.2+ once it is released.
npm WARN deprecated core-js@2.6.10: core-js@<3.0 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated fsevents@1.2.9: One of your dependencies needs to upgrade to fsevents v2: 1) Proper nodejs v10+ support 2) No more fetching binaries from AWS, smaller package size
npm WARN deprecated core-js@1.2.7: core-js@<3.0 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/inspireui/react-native-admob.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ASUS\AppData\Roaming\npm-cache\_logs\2019-12-01T16_30_42_303Z-debug.log

FAILURE: Build failed with an exception.

* Where:
Settings file 'C:\Users\ASUS\Downloads\codecanyon-u5KBuUQB-beostore-complete-react-native-template-for-ecommerce\mstore-3.9.6\mstore-pro\android\settings.gradle' line: 2

* What went wrong:
A problem occurred evaluating settings 'mstore'.
> Could not read script 'C:\Users\ASUS\Downloads\codecanyon-u5KBuUQB-beostore-complete-react-native-template-for-ecommerce\mstore-3.9.6\mstore-pro\node_modules\@react-native-community\cli-platform-android\native_modules.gradle' as it does not exist.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
react-native : The term 'react-native' is not recognized as the name of a cmdlet, function, script file, or operable pr
ogram. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\ASUS\Downloads\codecanyon-u5KBuUQB-beostore-complete-react-native-template-for-ecommerce\mstore-3.9.6\mstor
e-pro\scripts\cebuilder.ps1:7 char:1
+ react-native run-android
+ ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (react-native:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 

> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:

2. Screenshots issues:

3. Proof of my purchased:

3. Config files (optional)

**Comment by minhcasi** [comment]
Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads  it's used to verify your proof of purchase? sorry for any inconvenience - Thank you!

**Comment by antixirus** [comment]
![Screenshot_2019-12-02 Downloads CodeCanyon](https://user-images.githubusercontent.com/57300649/69958848-3b920a80-1538-11ea-8f26-f82d5f8aa274.png)

Purchase Download

**Comment by minhtruong315** [comment]
@antixirus add my skype: minhtruong315@gmail.com i will help you check via teamviewer

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
