### ISSUE TITLE
[Flux-Store] -  on cash delivery 

### ISSUE THREAD

**Issue by MohammedSwefee** [inspireui/support#1500]
Dears,

the issue is that I get an error message when i tried to use on cash delivery method

![image](https://user-images.githubusercontent.com/34106827/69917412-c27eae80-1476-11ea-847b-c978d4161bcc.png)

Config.dat as below:

[config.zip](https://github.com/inspireui/support/files/3908478/config.zip)
[payment.zip](https://github.com/inspireui/support/files/3908480/payment.zip)

mohammed.thaaer94@gmail.com

**Comment by minhcasi** [comment]
Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads  it's used to verify your proof of purchase? sorry for any inconvenience - Thank you!

**Comment by MohammedSwefee** [comment]
![photo_2019-12-02_10-50-53](https://user-images.githubusercontent.com/34106827/69949770-336ba800-1503-11ea-91b4-01c3b961304b.jpg)

**Comment by minhcasi** [comment]
@minhtruong315 - pls help for checking

**Comment by minhtruong315** [comment]
@MohammedSwefee you can replace getPaymentMethods function in services/woo_commerce.dart like this
```
@override
  Future<List<PaymentMethod>> getPaymentMethods(
      {Address address, ShippingMethod shippingMethod, String token}) async {
    try {
      print(shippingMethod.toString());
      var response = await wcApi.getAsync("payment_gateways");
      if (response is Map && isNotBlank(response["message"])) {
        throw Exception(response["message"]);
      } else {
        List<PaymentMethod> list = [];
        for (var item in response) {
          bool isAllowed = false;
          if (item["settings"]["enable_for_methods"] != null &&
              kAdvanceConfig["EnableShipping"]) {
            List allowedShipping =
                item["settings"]["enable_for_methods"]["value"];
            allowedShipping.forEach((shipping) {
              if (shipping ==
                  "${shippingMethod.methodId}:${shippingMethod.id}") {
                isAllowed = true;
              }
            });
          } else {
            isAllowed = true;
          }
          if (item["enabled"] && isAllowed) {
            list.add(PaymentMethod.fromJson(item));
          }
        }
        return list;
      }
    } catch (e) {
      //This error exception is about your Rest API is not config correctly so that not return the correct JSON format, please double check the document from this link https://docs.inspireui.com/fluxstore/woocommerce-setup/
      throw e;
    }
  }
```

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!

**Comment by MohammedSwefee** [comment]
Dear  Minh, 
I repaced getPaymentMethods function as you mentioned but the same issue still appear

also, I tried to run the new version 1.5.9 but a face this issue below
![Annotation 2019-12-02 130345](https://user-images.githubusercontent.com/34106827/70350224-5ab1d480-1877-11ea-8d3e-dd2571cfcf5d.png)
