### ISSUE TITLE
[Flux-Store] -  Instagram, blog loading issue

### ISSUE THREAD

**Issue by MohammedSwefee** [inspireui/support#1502]
Dears,

Kindly advice ho to hide Instagram and blog from home screen as I don't need to show it
(I use theme 9 )

![Annotation 2019-12-02 130345](https://user-images.githubusercontent.com/34106827/69950296-3d41db00-1504-11ea-8a22-20aafea66228.png)

Purchase code: 0ec77175-c961-49b0-acb6-d4e5b3f8e8d6

**Comment by minhtruong315** [comment]
@MohammedSwefee I dont understand your issues. if you use theme 9, it will not have blog and instagram.

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
