### ISSUE TITLE
[fluxstore] - Digital Download website 

### ISSUE THREAD

**Issue by Dhavalkatrodiya** [inspireui/support#1503]
---------

1. My issue:
Hi, i have Digital Download website, where user purchase an design & then download it.
how ever there is no download history option (just like order history), where user can download the design they had purchased.

2. Screenshots issues:
https://snipboard.io/LA1fW0.jpg

3. Proof of my purchased:
https://snipboard.io/6EgT7k.jpg

3. Config files (optional)

**Comment by minhcasi** [comment]
@vumanhsn97 - we will upgrade this feature to add the download link option from the My Order - not sure if it works - just do more investigate - thanks

**Comment by minhcasi** [comment]
moved to trello board - https://trello.com/c/0K2FQbnN/10-digital-download-feature

**Comment by Dhavalkatrodiya** [comment]
make full support of woocommerce digital product feature.
example : when user select any digital product, & he make payment, after successful payment he should redirected to page, where he can download that digital product.
