### ISSUE TITLE
Design Loaded but Data Not Shown in Application

### ISSUE THREAD

**Issue by godofblack** [inspireui/support#1504]
![4b6bc796-5e63-47aa-8392-cad059fab410](https://user-images.githubusercontent.com/53173319/69960238-f74e3c80-152e-11ea-8a44-fba839cf145b.jpeg)
Why this issue shown

**Comment by minhcasi** [comment]
Hi, could you help to share the proof of purchase code by taking the screenshot from - http://codecayon.net/downloads - thank you!
