### ISSUE TITLE
Mstore pro user registration issue

### ISSUE THREAD

**Issue by ahmadfmoustafa** [inspireui/support#1505]
Hello, 
I have a problem with user registration via Mstore pro app when I fill the registration form in the app and after a click on the register button, nothing happened and the user can't register.

after checked the api> mstore register and click on it, this message is shown {"status":"error","error":"You must include 'username' var in your request. "}

what is the issue, and how can I solve it?

**Comment by minhcasi** [comment]
Hi, could you help to share the proof of purchase code by taking the screenshot from - http://codecayon.net/downloads - thank you!

**Comment by abouzeidroy** [comment]
I have the same problem , u purchased yesterday, same problem You must include 'username' var in your request.

Purchase code: ac5bfa48-8c10-43cf-81f8-59c1d913cb56

**Comment by ahmadfmoustafa** [comment]
Item Purchase Code: caa242e3-a613-4bb4-b44a-dc2a4c906e67
![screencapture-codecanyon-net-downloads-2019-12-03-23_00_07](https://user-images.githubusercontent.com/47982175/70089520-ebdb3e00-1620-11ea-83e9-e5bdb408e509.png)

**Comment by abouzeidroy** [comment]
Also, Problem 2
In your demo app:
If no user login, i am inside shopping cart -> i click "next step", i go to sign in or sign up page to finish the order (Perfect!!)

In my downloaded purchased app:
If no user login, i am inside shopping cart -> i click "next step", i go to "Your shipping details" page!! And if we continue, the app crash! No i don't want this, i want to go to sign in / sign up page directly, not "your shipping details" page (exactly like in the demo page)

How can i fix this please

Thank you

**Comment by minhcasi** [comment]
@concuacon - please help for investigating this issue - thank you!

**Comment by abouzeidroy** [comment]
Also, everytime i try to sign up a user, i got 'Weclome back, undefined'.
I saw in another article that we have to replace WPUserAPI.js in src -> services.
I replace
Now no error Welcome back, undefined showing
But when you click on sign up button, nothing happen, user still not signed up
Thank you for helping

this is my whatsapp number if you can help: 0096171884898 maybe with skype or teamviewer
thanks

**Comment by minhtruong315** [comment]
add my skype: minhtruong315. i will help you check via teamviewer

**Comment by minhtruong315** [comment]
support via skype
