### ISSUE TITLE
[fluxstore] - I cant continue to shipping

### ISSUE THREAD

**Issue by anakilang99** [inspireui/support#1506]
1. My issue:
I cant continue to shipping.. it show this error:

2. Screenshots issues:
https://prnt.sc/q5ioun

3. Proof of my purchased:
https://prnt.sc/q5iolc

3. Config files (optional)

**Comment by minhtruong315** [comment]
@anakilang99 can you send me config.dart file and admin account via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/1506

**Comment by minhtruong315** [comment]
@anakilang99 please try this comment https://github.com/inspireui/support/issues/1489#issuecomment-560120167

**Comment by anakilang99** [comment]
<img width="321" alt="Screen Shot 2019-12-05 at 20 06 26" src="https://user-images.githubusercontent.com/58469385/70237975-e43fa480-179a-11ea-9af6-71bfcbfa60ec.png">

still error.. :(

**Comment by anakilang99** [comment]
@minhtruong315

**Comment by minhtruong315** [comment]
@anakilang99 can you send me config.dart file and admin account via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/1506

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
I reply your email. But i haven't recevied response
