### ISSUE TITLE
Fluxstore Pro  - Flutter_test Issue

### ISSUE THREAD

**Issue by sarzali07** [inspireui/support#1508]
![issue]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
Resolving dependencies...
Because fstore depends on flutter_test any from sdk which doesn't exist (the Flutter SDK is not available), version solving failed.

Flutter users should run `flutter pub get` instead of `pub get`.
Process finished with exit code 69

2. Screenshots issues:
(https://user-images.githubusercontent.com/10739321/70054793-04842d80-15fa-11ea-8264-504ca50aa4b1.png)
3. Proof of my purchased:

3. Config files (optional)

**Comment by minhcasi** [comment]
@sarzali07  - could you help to check this flutter sdk config for the project, pls check this common issue/solution here - https://docs.inspireui.com/fluxstore/common-question/

**Comment by sarzali07** [comment]
ERROR: [TAG] Failed to resolve variable '${junit.version}'
ERROR: [TAG] Failed to resolve variable '${animal.sniffer.version}'

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
> No matching client found for package name 'com.sarfarazlaghari.electrocity'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 39s
Finished with error: Gradle task assembleDebug failed with exit code 1


These error now showing

**Comment by sarzali07** [comment]
After deleting .gradle folder I manage to install over android device but I fot list of errors 
![processed](https://user-images.githubusercontent.com/10739321/70125838-7a8ba180-1699-11ea-978e-a30ad1c0b3f0.jpeg)

**Comment by sarzali07** [comment]
After changing as per doc 
1.1 Change the app name: Done
1.2 Change the app Bundle ID: Done
Firebase : Done replace google .json file


Error reading dependency file D:\opencartapplication\electrocity\build\app\intermediates\flutter\debug\android-arm\snapshot_blob.bin.d: java.lang.ArrayIndexOutOfBoundsException: 1
Error reading dependency file D:\opencartapplication\electrocity\build\app\intermediates\flutter\debug\android-arm\snapshot_blob.bin.d: java.lang.ArrayIndexOutOfBoundsException: 1

Compiler message:
Error: Could not resolve the package 'electrocity' in 'package:electrocity/common/constants.dart'.
Error: Could not resolve the package 'electrocity' in 'package:electrocity/screens/login_sms/index.dart'.
Error: Could not resolve the package 'electrocity' in 'package:electrocity/screens/home.dart'.
lib/common/config.dart:2:8: Error: Not found: 'package:electrocity/common/constants.dart'
import 'package:electrocity/common/constants.dart';
       ^
lib/screens/login.dart:4:8: Error: Not found: 'package:electrocity/screens/login_sms/index.dart'
import 'package:electrocity/screens/login_sms/index.dart';
       ^
lib/widgets/webview.dart:2:8: Error: Not found: 'package:electrocity/common/constants.dart'
import 'package:electrocity/common/constants.dart';
       ^
Error: Could not resolve the package 'electrocity' in 'package:electrocity/common/tools.dart'.
lib/tabbar.dart:17:8: Error: Not found: 'package:electrocity/screens/home.dart'
import 'package:electrocity/screens/home.dart';
       ^
Error: Could not resolve the package 'electrocity' in 'package:electrocity/widgets/product/product_variant.dart'.
lib/screens/cart.dart:4:8: Error: Not found: 'package:electrocity/common/tools.dart'
import 'package:electrocity/common/tools.dart';
       ^
lib/widgets/cart_item.dart:8:8: Error: Not found: 'package:electrocity/widgets/product/product_variant.dart'
import 'package:electrocity/widgets/product/product_variant.dart';
       ^
lib/screens/detail/index.dart:2:8: Error: Not found: 'package:electrocity/common/constants.dart'
import 'package:electrocity/common/constants.dart';
       ^
Error: Could not resolve the package 'fstore' in 'package:fstore/common/tools.dart'.
lib/screens/detail/themes/halfSizeImageType.dart:6:8: Error: Not found: 'package:electrocity/common/tools.dart'
import 'package:electrocity/common/tools.dart';
       ^
lib/screens/detail/themes/fullSizeImageType.dart:6:8: Error: Not found: 'package:fstore/common/tools.dart'
import 'package:fstore/common/tools.dart';
       ^
Error: Could not resolve the package 'electrocity' in 'package:electrocity/widgets/image_galery.dart'.
Error: Could not resolve the package 'fstore' in 'package:fstore/widgets/image_galery.dart'.
lib/screens/detail/image_feature.dart:7:8: Error: Not found: 'package:electrocity/widgets/image_galery.dart'
import 'package:electrocity/widgets/image_galery.dart';
       ^
lib/screens/detail/product_galery.dart:2:8: Error: Not found: 'package:fstore/widgets/image_galery.dart'
import 'package:fstore/widgets/image_galery.dart';
       ^
lib/common/config.dart:18:30: Error: Getter not found: 'kCategoriesLayout'.
const CategoriesListLayout = kCategoriesLayout.card;
                             ^^^^^^^^^^^^^^^^^
lib/common/config.dart:44:25: Error: Getter not found: 'kBlogLayout'.
  "DetailedBlogLayout": kBlogLayout.halfSizeImageType,
                        ^^^^^^^^^^^
lib/common/config.dart:75:29: Error: Getter not found: 'kProductLayout'.
const ProductDetailLayout = kProductLayout.simpleType;
                            ^^^^^^^^^^^^^^
lib/screens/login.dart:169:49: Error: Method not found: 'LoginSMS'.
        MaterialPageRoute(builder: (context) => LoginSMS()),
                                                ^^^^^^^^
lib/screens/login.dart:169:49: Error: The method 'LoginSMS' isn't defined for the class '_LoginPageState'.
 - '_LoginPageState' is from 'package:Electrocity/screens/login.dart' ('lib/screens/login.dart').
Try correcting the name to the name of an existing method, or defining a method named 'LoginSMS'.
        MaterialPageRoute(builder: (context) => LoginSMS()),
                                                ^^^^^^^^
lib/tabbar.dart:60:16: Error: Method not found: 'HomeScreen'.
        return HomeScreen();
               ^^^^^^^^^^
lib/tabbar.dart:60:16: Error: The method 'HomeScreen' isn't defined for the class 'MainTabsState'.
 - 'MainTabsState' is from 'package:Electrocity/tabbar.dart' ('lib/tabbar.dart').
Try correcting the name to the name of an existing method, or defining a method named 'HomeScreen'.
        return HomeScreen();
               ^^^^^^^^^^
lib/widgets/webview.dart:44:13: Error: Method not found: 'kLoadingWidget'.
            kLoadingWidget(context),
            ^^^^^^^^^^^^^^
lib/widgets/webview.dart:44:13: Error: The method 'kLoadingWidget' isn't defined for the class '_WebViewState'.
 - '_WebViewState' is from 'package:Electrocity/widgets/webview.dart' ('lib/widgets/webview.dart').
Try correcting the name to the name of an existing method, or defining a method named 'kLoadingWidget'.
            kLoadingWidget(context),
            ^^^^^^^^^^^^^^
lib/screens/cart.dart:488:31: Error: Getter not found: 'Tools'.
                              Tools.getCurrecyFormatted(widget.model.getTotal()),
                              ^^^^^
lib/screens/cart.dart:488:31: Error: The getter 'Tools' isn't defined for the class '_ShoppingCartSummaryState'.
 - '_ShoppingCartSummaryState' is from 'package:Electrocity/screens/cart.dart' ('lib/screens/cart.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Tools'.
                              Tools.getCurrecyFormatted(widget.model.getTotal()),
                              ^^^^^
lib/widgets/cart_item.dart:87:36: Error: Method not found: 'QuantitySelection'.
                            child: QuantitySelection(
                                   ^^^^^^^^^^^^^^^^^
lib/widgets/cart_item.dart:87:36: Error: The method 'QuantitySelection' isn't defined for the class 'ShoppingCartRow'.
 - 'ShoppingCartRow' is from 'package:Electrocity/widgets/cart_item.dart' ('lib/widgets/cart_item.dart').
Try correcting the name to the name of an existing method, or defining a method named 'QuantitySelection'.
                            child: QuantitySelection(
                                   ^^^^^^^^^^^^^^^^^
lib/screens/detail/index.dart:72:50: Error: Getter not found: 'kProductLayout'.
    var layoutType = kProductDetail['layout'] ?? kProductLayout.simpleType;
                                                 ^^^^^^^^^^^^^^
lib/screens/detail/index.dart:75:12: Error: Getter not found: 'kProductLayout'.
      case kProductLayout.halfSizeImageType:
           ^^^^^^^^^^^^^^
lib/screens/detail/index.dart:77:12: Error: Getter not found: 'kProductLayout'.
      case kProductLayout.fullSizeImageType:
           ^^^^^^^^^^^^^^
lib/screens/detail/index.dart:72:50: Error: The getter 'kProductLayout' isn't defined for the class 'Detail'.
 - 'Detail' is from 'package:Electrocity/screens/detail/index.dart' ('lib/screens/detail/index.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'kProductLayout'.
    var layoutType = kProductDetail['layout'] ?? kProductLayout.simpleType;
                                                 ^^^^^^^^^^^^^^
lib/screens/detail/themes/fullSizeImageType.dart:56:23: Error: Getter not found: 'kSize'.
                size: kSize.medium,
                      ^^^^^
lib/screens/detail/themes/fullSizeImageType.dart:53:22: Error: Getter not found: 'Tools'.
              child: Tools.image(
                     ^^^^^
lib/screens/detail/themes/fullSizeImageType.dart:53:22: Error: The getter 'Tools' isn't defined for the class '_FullSizeLayoutState'.
 - '_FullSizeLayoutState' is from 'package:Electrocity/screens/detail/themes/fullSizeImageType.dart' ('lib/screens/detail/themes/fullSizeImageType.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Tools'.
              child: Tools.image(
                     ^^^^^
lib/screens/detail/themes/fullSizeImageType.dart:56:23: Error: The getter 'kSize' isn't defined for the class '_FullSizeLayoutState'.
 - '_FullSizeLayoutState' is from 'package:Electrocity/screens/detail/themes/fullSizeImageType.dart' ('lib/screens/detail/themes/fullSizeImageType.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'kSize'.
                size: kSize.medium,
                      ^^^^^
lib/screens/detail/themes/halfSizeImageType.dart:72:23: Error: Getter not found: 'kSize'.
                size: kSize.medium,
                      ^^^^^
lib/screens/detail/themes/halfSizeImageType.dart:69:22: Error: Getter not found: 'Tools'.
              child: Tools.image(
                     ^^^^^
lib/screens/detail/themes/halfSizeImageType.dart:69:22: Error: The getter 'Tools' isn't defined for the class '_HalfSizeLayoutState'.
 - '_HalfSizeLayoutState' is from 'package:Electrocity/screens/detail/themes/halfSizeImageType.dart' ('lib/screens/detail/themes/halfSizeImageType.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Tools'.
              child: Tools.image(
                     ^^^^^
lib/screens/detail/themes/halfSizeImageType.dart:72:23: Error: The getter 'kSize' isn't defined for the class '_HalfSizeLayoutState'.
 - '_HalfSizeLayoutState' is from 'package:Electrocity/screens/detail/themes/halfSizeImageType.dart' ('lib/screens/detail/themes/halfSizeImageType.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'kSize'.
                size: kSize.medium,
                      ^^^^^
lib/screens/detail/image_feature.dart:27:20: Error: Method not found: 'ImageGalery'.
            return ImageGalery(images: product.images, index: index);
                   ^^^^^^^^^^^
lib/screens/detail/image_feature.dart:27:20: Error: The method 'ImageGalery' isn't defined for the class 'ImageFeature'.
 - 'ImageFeature' is from 'package:Electrocity/screens/detail/image_feature.dart' ('lib/screens/detail/image_feature.dart').
Try correcting the name to the name of an existing method, or defining a method named 'ImageGalery'.
            return ImageGalery(images: product.images, index: index);
                   ^^^^^^^^^^^
lib/screens/detail/product_galery.dart:27:18: Error: Method not found: 'ImageGalery'.
          return ImageGalery(images: product.images, index: index);
                 ^^^^^^^^^^^
lib/screens/detail/product_galery.dart:27:18: Error: The method 'ImageGalery' isn't defined for the class 'ProductGalery'.
 - 'ProductGalery' is from 'package:Electrocity/screens/detail/product_galery.dart' ('lib/screens/detail/product_galery.dart').
Try correcting the name to the name of an existing method, or defining a method named 'ImageGalery'.
          return ImageGalery(images: product.images, index: index);
                 ^^^^^^^^^^^
U
nhandled exception:
FileSystemExcepti
on(uri=org-dartlang-untranslatable-uri:package%3Aelectrocity%2Fcommon%2Fconstants.dart; message=StandardFileSystem only supports file:* and data:* URIs)
#0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:33:7)
#1      asFileUri (package:vm/kernel_front_end.dart:5
78:37)
<asynchronous suspension>
#2      writeDepfile (package
:vm/kernel_front_end.dart:755:21)
<asynchronous suspension
>
#3      FrontendCompiler.compile (package:vm
/frontend_server.dart:407:15)
<asynchronous sus
pension>
#4      _FlutterFrontendCompiler.compile 
(package:frontend_server/server.dart:29:22)
<asynchro
nous suspension>
#5      starter (package:frontend_s
erver/server.dart:127:27)
<asynchronous suspension
>
#6      main (file:///C:/b/s/w/ir/k/src/flutter/
frontend_server/bin/starter.dart:8:30)
<asynchrono
us suspension>
#7      _startIsolate.<anonymous c
losure> (dart:isolate-patch/isolate_patch.dart:30
3:32)
#8      _RawReceivePortImpl._handleMessage 
(dart:isolate-patch/isolate_patch.dart:172:12)

Compiler failed on D:\opencartapplication\electrocity\lib\main.dart

FAILURE: Build failed with an exception.

* Where:
Script 'D:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 765

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebugArm'.
> Process 'command 'D:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 32s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by sarzali07** [comment]
Now only showing Error reading dependency file D:\opencartapplication\electrocity\build\app\intermediates\flutter\debug\android-arm\snapshot_blob.bin.d: java.lang.ArrayIndexOutOfBoundsException: 1
Error reading dependency file D:\opencartapplication\electrocity\build\app\intermediates\flutter\debug\android-arm\snapshot_blob.bin.d: java.lang.ArrayIndexOutOfBoundsException: 1

Above errors

**Comment by sarzali07** [comment]
Now situation do not know mean above from my knowledge

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:packageDebug'.
> Failed to obtain compression information for entry

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 38s
Finished with error: Gradle task assembleDebug failed with exit code 1

Regards

**Comment by sarzali07** [comment]
Finally I manage to install app over android device but 

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building Consumer<AppModel>(dirty, dependencies: [InheritedProvider<AppModel>]):
'dart:ui/window.dart': Failed assertion: line 281: '<optimized out>': is not true.

and also result is 

(https://user-images.githubusercontent.com/10739321/70125838-7a8ba180-1699-11ea-978e-a30ad1c0b3f0.jpeg)

**Comment by sarzali07** [comment]
I tries much but can not reslove this issue

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building Consumer(dirty, dependencies: [InheritedProvider]):
'dart:ui/window.dart': Failed assertion: line 281: '': is not true.

and also result is

(https://user-images.githubusercontent.com/10739321/70125838-7a8ba180-1699-11ea-978e-a30ad1c0b3f0.jpeg)

Regards

**Comment by sarzali07** [comment]
Kindly give me some time so that we can finish this.

After installing flutter from 

 git clone -b master https://github.com/flutter/flutter.git


I got below errors.
Compiler message:
/C:/Users/Sarz/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/cached_network_image-1.1.3/lib/src/cached_network_image_provider.dart:42:24: Error: The method 'CachedNetworkImageProvider.load' has fewer positional arguments than those of overridden method 'ImageProvider.load'.
  ImageStreamCompleter load(CachedNetworkImageProvider key) {
                       ^
/D:/flutter/packages/flutter/lib/src/painting/image_provider.dart:403:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(T key, DecoderCallback decode);
                       ^
/C:/Users/Sarz/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/extended_image_library-0.1.8/lib/src/extended_memory_image_provider.dart:12:24: Error: The method 'ExtendedMemoryImageProvider.load' has fewer positional arguments than those of overridden method 'MemoryImage.load'.
  ImageStreamCompleter load(MemoryImage key) {
                       ^
/D:/flutter/packages/flutter/lib/src/painting/image_provider.dart:704:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(MemoryImage key, DecoderCallback decode) {
                       ^
/C:/Users/Sarz/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/extended_image_library-0.1.8/lib/src/extended_file_image_provider.dart:13:24: Error: The method 'ExtendedFileImageProvider.load' has fewer positional arguments than those of overridden method 'FileImage.load'.
  ImageStreamCompleter load(FileImage key) {
                       ^
/D:/flutter/packages/flutter/lib/src/painting/image_provider.dart:636:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(FileImage key, DecoderCallback decode) {
                       ^
/C:/Users/Sarz/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/extended_image_library-0.1.8/lib/src/extended_asset_bundle_image_provider.dart:35:24: Error: The method 'ExtendedExactAssetImageProvider.load' has fewer positional arguments than those of overridden method 'AssetBundleImageProvider.load'.
  ImageStreamCompleter load(AssetBundleImageKey key) {
                       ^
/D:/flutter/packages/flutter/lib/src/painting/image_provider.dart:467:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(AssetBundleImageKey key, DecoderCallback decode) {
                       ^
/C:/Users/Sarz/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/extended_image_library-0.1.8/lib/src/extended_asset_bundle_image_provider.dart:87:24: Error: The method 'ExtendedAssetImageProvider.load' has fewer positional arguments than those of overridden method 'AssetBundleImageProvider.load'.
  ImageStreamCompleter load(AssetBundleImageKey key) {
                       ^
/D:/flutter/packages/flutter/lib/src/painting/image_provider.dart:467:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(AssetBundleImageKey key, DecoderCallback decode) {
                       ^
/C:/Users/Sarz/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/extended_image_library-0.1.8/lib/src/extended_network_image_provider.dart:62:24: Error: The method 'ExtendedNetworkImageProvider.load' has fewer positional arguments than those of overridden method 'ImageProvider.load'.
  ImageStreamCompleter load(ExtendedNetworkImageProvider key) {
                       ^
/D:/flutter/packages/flutter/lib/src/painting/image_provider.dart:403:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(T key, DecoderCallback decode);
                       ^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'D:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 776

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'D:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 49s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by minhcasi** [comment]
Hi, could you try to run "flutter doctor -v" and send us the result 

Also make sure you run the flutter with channel stable by running "flutter channel stable"

**Comment by minhtruong315** [comment]
@sarzali07 can you send me your source code via email: truong@inspireui.com
with subject:  https://github.com/inspireui/support/issues/1508

**Comment by sarzali07** [comment]
> Hi, could you try to run "flutter doctor -v" and send us the result
> 
> Also make sure you run the flutter with channel stable by running "flutter channel stable"

C:\Users\Sarz>flutter --version
Flutter 1.9.1+hotfix.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 68587a0916 (3 months ago) • 2019-09-13 19:46:58 -0700
Engine • revision b863200c37
Tools • Dart 2.5.0

C:\Users\Sarz>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.9.1+hotfix.6, on Microsoft Windows [Version 10.0.15063], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[√] VS Code (version 1.40.2)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

C:\Users\Sarz>flutter doctor -v
[√] Flutter (Channel stable, v1.9.1+hotfix.6, on Microsoft Windows [Version 10.0.15063], locale en-US)
    • Flutter version 1.9.1+hotfix.6 at D:\flutter
    • Framework revision 68587a0916 (3 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at D:\iTAG\EDrive\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.40.2)
    • VS Code at C:\Users\Sarz\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.6.0

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

C:\Users\Sarz>flutter channel stable
Switching to flutter channel 'stable'...
git: From https://github.com/flutter/flutter
git:    e70236e36..4f54e46f5  beta              -> origin/beta
git:    1946fc4da..37f9c5411  dev               -> origin/dev
git:    ed36fe5dd..d01de941b  master            -> origin/master
git:  * [new branch]          v1.12.13-hotfixes -> origin/v1.12.13-hotfixes
git:  * [new tag]             v1.12.13+hotfix.2 -> v1.12.13+hotfix.2
git:  * [new tag]             v1.12.16          -> v1.12.16
git:  * [new tag]             v1.10.15          -> v1.10.15
git:  * [new tag]             v1.10.16          -> v1.10.16
git:  * [new tag]             v1.11.0           -> v1.11.0
git:  * [new tag]             v1.12.0           -> v1.12.0
git:  * [new tag]             v1.12.1           -> v1.12.1
git:  * [new tag]             v1.12.10          -> v1.12.10
git:  * [new tag]             v1.12.11          -> v1.12.11
git:  * [new tag]             v1.12.12          -> v1.12.12
git:  * [new tag]             v1.12.13          -> v1.12.13
git:  * [new tag]             v1.12.13+hotfix.1 -> v1.12.13+hotfix.1
git:  * [new tag]             v1.12.14          -> v1.12.14
git:  * [new tag]             v1.12.15          -> v1.12.15
git:  * [new tag]             v1.12.2           -> v1.12.2
git:  * [new tag]             v1.12.3           -> v1.12.3
git:  * [new tag]             v1.12.4           -> v1.12.4
git:  * [new tag]             v1.12.5           -> v1.12.5
git:  * [new tag]             v1.12.6           -> v1.12.6
git:  * [new tag]             v1.12.7           -> v1.12.7
git:  * [new tag]             v1.12.8           -> v1.12.8
git:  * [new tag]             v1.12.9           -> v1.12.9
git: Your branch is up to date with 'origin/stable'.
git: Already on 'stable'

**Comment by sarzali07** [comment]
> @sarzali07 can you send me your source code via email: [truong@inspireui.com](mailto:truong@inspireui.com)
> with subject: #1508

Email send along with code via dropbox. kindly let me know step by step what was issue plz.

**Comment by minhtruong315** [comment]
@sarzali07 I dont see code on your email. pls send me again

**Comment by sarzali07** [comment]
> @sarzali07 I dont see code on your email. pls send me again

@sarzali07 can you send me your source code via email: truong@inspireui.com
with subject: #1508

Email send along with code via dropbox. kindly let me know step by step what was issue plz.

Dear at least read complete message I shared again on truong@inspireui.com email via dropbox.

**Comment by minhtruong315** [comment]
send me the link

**Comment by sarzali07** [comment]
Already sent kindly confirm you received

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by minhtruong315** [comment]
I dont see any email. Why can't you send me link source code via my email?

**Comment by sarzali07** [comment]
Sorry but are you kidding me you reply after 20 hours and said you did not receivr any.

https://www.dropbox.com/s/7zmvlzfk1mgh9of/electrocity.rar?dl=0
Here is link
Do not work with stupidity send me your skype or whatsapp id

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by minhtruong315** [comment]
You can't send public source code

**Comment by minhcasi** [comment]
@sarzali07 - just confirm we got the source code - the team will have a check and keep an update - thank you for your patient

**Comment by minhtruong315** [comment]
[Archive.zip](https://github.com/inspireui/support/files/3953971/Archive.zip)
try to replace config.dart and config.json then run again

**Comment by sarzali07** [comment]
Hi

I install over android device screenshots and video sent on skype. While checkout not working. Product page not working. product images not showing

**Comment by minhtruong315** [comment]
I will check it

**Comment by minhtruong315** [comment]
[mstore.ocmod.zip](https://github.com/inspireui/support/files/3954652/mstore.ocmod.zip)
try install mstore extension again in your website

**Comment by sarzali07** [comment]
checkout still not working after uploading zip

**Comment by sarzali07** [comment]
Hi any update on checkout??

**Comment by minhcasi** [comment]
@sarzali07 - could you update to the latest Fluxstore 1.6 and send us the detail issue of the Checkout issue? Thanks

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
