### ISSUE TITLE
[FluxStore multivendor] - 

### ISSUE THREAD

**Issue by mohjacksi** [inspireui/support#1509]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
I cannot create a user from my application
2. Screenshots issues:
https://tppr.me/b8QcJ
3. Proof of my purchased:
https://tppr.me/Zi2np

**Comment by minhcasi** [comment]
@mohjacksi - pls check this guide to fix this issue, there is the missing plugin config - https://docs.inspireui.com/fluxstore/multi-vendor/#setup-mstore-api-plugin

**Comment by mohjacksi** [comment]
I'm getting {"status":"ok","controller":"mstore_user","method":"register","nonce":"22664867a2"}

**Comment by mohjacksi** [comment]
Then I'm getting this error for login and sign up with email
https://tppr.me/wA18V
but when I sign up with email the user created! but don't login in

**Comment by incepio-flutter** [comment]
I had the same problem. You need to place this in .htaccess file 
 RewriteEngine on
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule ^(.*) - [E=HTTP_AUTHORIZATION:%1]

and  this line on the top of wp-config.php 
define('JWT_AUTH_SECRET_KEY', 'your-top-secrect-key');
after doing this you will not recieve invalid augrments exception but make sure you have all plugins installed mstore api, JWT, JSON.

**Comment by mohjacksi** [comment]
@incepio-flutter ok but where to get "your-top-secrect-key"

**Comment by mohjacksi** [comment]
And I just update the config files from dokan to mach my website (WCFM)
Then now I get https://tppr.me/GZQW1

**Comment by incepio-flutter** [comment]
<img width="312" alt="Screenshot 2019-12-05 at 2 40 23 AM" src="https://user-images.githubusercontent.com/57838430/70183929-9a0de300-1708-11ea-983e-78c85cf5a132.png">
@mohjacksi  Under config.php 
if nothing happens then  try changing in wp-content/plugins/jwt-authentication-for-wp-rest-api/public/class-jwt-auth-public.php:

if (!$secret_key) {
by

if ($secret_key === false) {
Put define('JWT_AUTH_SECRET_KEY', 'your-top-secrect-key'); wherever you what but before require_once(ABSPATH . 'wp-settings.php');

**Comment by minhcasi** [comment]
@mohjacksi - let us know if could able resolve the issue, please reopen the ticket if it does not work - thank you!

**Comment by maghassan** [comment]
Hello, I can't see my products for vendors.
