### ISSUE TITLE
ListPro api connection to listingpro wordpress site

### ISSUE THREAD

**Issue by tthamel** [inspireui/support#151]
I am having issues connecting the wordpress site to the listPro app.

in the documentation you say to enable job_listing in the Rest API section of wordpress

on my wordpress i do not have job_listing, only listing, so i activated that.

when i go into config.js and enter in the root website and the api endpoint i dont get my content loading but the demo content.

**Comment by thangvo9x** [comment]
Please send you Config file, such as your email. We'll config it && send it. Thanks
