### ISSUE TITLE
[my-product] - 

### ISSUE THREAD

**Issue by mohjacksi** [inspireui/support#1510]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
No stores appear in the application!
2. Screenshots issues:
https://tppr.me/BMcYB
3. Proof of my purchased:
https://tppr.me/Zi2np

**Comment by incepio-flutter** [comment]
Your dokan or wfcm plugin have a problem i think .

**Comment by mohjacksi** [comment]
OK, I'll reinstall the whole WP on my website!

**Comment by mohjacksi** [comment]
I don't have any problems with the wfcm plugin :(

**Comment by mohjacksi** [comment]
Also when click on
https://tppr.me/xWJiE

I get  

https://tppr.me/SY1ip

**Comment by minhcasi** [comment]
@mohjacksi - did you update the category id to match with your id, it can be config from the common/config.json

Also, double-check the require plugin from https://docs.inspireui.com/fluxstore/multi-vendor/

 - thank you!

**Comment by incepio-flutter** [comment]
@mohjacksi 
<img width="1111" alt="Screenshot 2019-12-04 at 3 28 05 PM" src="https://user-images.githubusercontent.com/57838430/70134886-ba0eb980-16aa-11ea-8544-056f70f47e8b.png">

**Comment by mohjacksi** [comment]
Ok thank you! but now I get the store name but when I click on it there is no products appear!
and I'm sure that I have products with this vendor
 https://tppr.me/pRrEm
https://tppr.me/ty9UZ

**Comment by minhcasi** [comment]
@mohjacksi - could you help to attache your config here (common/config.dart and config.json) - thank you!
