### ISSUE TITLE
[Fluxstore 1.5.9] - sing in not working in this version

### ISSUE THREAD

**Issue by EmilianH** [inspireui/support#1512]
---------

1. My issue: in fluxstore 1.5.9 sing in not working, , in version 1.5.7 the sing in work perfect with the same setup

2. Screenshots issues:
![image](https://user-images.githubusercontent.com/57189819/70100320-1cff4280-1610-11ea-80e0-8143f78fc929.png)

3. Proof of my purchased:
![compra](https://user-images.githubusercontent.com/57189819/70100433-76677180-1610-11ea-8b0e-1a5f61f5e950.jpg)

3. Config files (optional)
[common.zip](https://github.com/inspireui/support/files/3919287/common.zip)

**Comment by minhcasi** [comment]
@vumanhsn97 - please help for investigating this issue - thank you!

**Comment by EmilianH** [comment]
Please help me, I bought the app 2 months ago and I still can't make it work, a new bug always appears

**Comment by vumanhsn97** [comment]
@EmilianH Did you install mstore api plugin?
http://mamapp.com.ar/api/get_nonce/?controller=mstore_user&method=register&insecure=cool

http://demo.mstore.io/api/get_nonce/?controller=mstore_user&method=register&insecure=cool

**Comment by EmilianH** [comment]
Yes i have intalles but im using mstore api from previews version of flexstore 1.5.7

**Comment by vumanhsn97** [comment]
@EmilianH 
Can you share your admin account?
My email is manh@inspireui.com

**Comment by vumanhsn97** [comment]
@EmilianH I cant load your website!!! https://tppr.me/mnQXv

**Comment by EmilianH** [comment]
Please send me the ip and i call to my webhosting to enable

**Comment by vumanhsn97** [comment]
@EmilianH My ip is 113.172.245.36

**Comment by EmilianH** [comment]
@vumanhsn97 is already activated the ip and the country, try in 20 minutes please

**Comment by incepio-flutter** [comment]
please guide me also I am getting the same get nounce error

**Comment by EmilianH** [comment]
My friend could you see the page?

**Comment by incepio-flutter** [comment]
if you are having trouble regarding images first check to regenerate thumbnails if everything is fine then after creating the category there is cat id in the url paste it in the config.json

**Comment by incepio-flutter** [comment]
have to cleared that nounce error @EmilianH

**Comment by EmilianH** [comment]
sorry the messsage is for @vumanhsn97 could you check the web? thanks

**Comment by vumanhsn97** [comment]
@EmilianH Fixed. Loss word api https://tppr.me/T557y

@incepio-flutter You can check your issue in image. If it not working, please send me your config.json, config.dart and account login!

Thanks!

**Comment by EmilianH** [comment]
@vumanhsn97 thank you my friend, i have anothe issue

without  login the payment checkout doesn´t work only appear a blank page, and if i login appear correctly the woocommerce checkout, how to fix that? thanks!

**Comment by vumanhsn97** [comment]
@EmilianH Not found your issue. Can you share your video record?

**Comment by EmilianH** [comment]
@vumanhsn97 yes watch it, without login BLANK PAGE y  and logged in is fine

[Rec001.zip](https://github.com/inspireui/support/files/3930627/Rec001.zip)

**Comment by vumanhsn97** [comment]
@EmilianH You can setup login before checkout by setting GestCheckout = false in config.dart like image https://tppr.me/RTgMR

**Comment by incepio-flutter** [comment]
@vumanhsn97  sir API base is  sjsbazar.com/api 
can you please have a look at my WP setup should I send you admin account ?
email name please?

**Comment by vumanhsn97** [comment]
@incepio-flutter 
You can send a mail to vumanhsn97@gmail.com

**Comment by incepio-flutter** [comment]
@vumanhsn97 I have solved the signup problem, now I am facing shipping problem
https://github.com/inspireui/support/issues/1478 please checkout the last comment

**Comment by minhcasi** [comment]
@EmilianH - please try to update the app to the latest version 1.6, there is some bug fix and compatible with Flutter 1.12 - Detail changelog will be updated from https://medium.com/@inspireui/announcing-fluxstore-1-6-337efff1791f - thank you!
