### ISSUE TITLE
[MStore Pro] The development server returned response error code: 500

### ISSUE THREAD

**Issue by antixirus** [inspireui/support#1513]
![Capture](https://user-images.githubusercontent.com/57300649/70106856-54eda080-1677-11ea-8228-7d2a84af9a72.PNG)

Somebody can help me to solve this problem? Please..

**Comment by minhcasi** [comment]
It seems the adb is not working, please check to start this script:

yarn install && yarn start
react-native run-android

Also, check this guide and make sure you can run the Example project
https://facebook.github.io/react-native/docs/getting-started

**Comment by minhcasi** [comment]
@antixirus - please let us know if you could resolve the issue, and reopen the ticket if you need any support from the team - thank you!
