### ISSUE TITLE
Fluxstore Pro: Multiple Issue

### ISSUE THREAD

**Issue by jpmishra1010** [inspireui/support#1516]
I faced several issues with this app. Please help me out.
1. Products thumbnail is not loading.
2. Categories page is not working.
3. Categories and subcategories in a drawer.
4. When moving to checkout, it's throwing FormatException: Unexpected end of input(at character even when I made enableshipping: true.
5. I'm not able to change the app icon.

Please help me out asap as I have to deliver this app.
![proof](https://user-images.githubusercontent.com/32157980/70114217-a864ec00-1681-11ea-81f4-93caaff35e21.PNG)

![Screenshot_20191204-015139](https://user-images.githubusercontent.com/32157980/70114139-718ed600-1681-11ea-8dcb-cf29c6b1f9d4.jpg)
![Screenshot_20191204-092907](https://user-images.githubusercontent.com/32157980/70114140-718ed600-1681-11ea-938a-0dcf09d77926.jpg)
![Screenshot_20191204-092917](https://user-images.githubusercontent.com/32157980/70114141-72276c80-1681-11ea-94a4-57affc99ff17.jpg)
![Screenshot_20191204-102825](https://user-images.githubusercontent.com/32157980/70114142-72276c80-1681-11ea-80bd-a018c858a2bd.jpg)

Note: I have attached purchase proof.

**Comment by minhcasi** [comment]
@jpmishra1010 - could you share the config files so that we could help for checking - thank you!

**Comment by jpmishra1010** [comment]
I have an issue my laptop. I have sent it for repairing. Please do not close this ticket. I will upload it day after tomorrow. Hope you will cooperate.

**Comment by minhcasi** [comment]
@jpmishra1010 - please try to update the app to the latest version 1.6, there is some bug fix and compatible with Flutter 1.12 - Detail changelog will be updated from https://medium.com/@inspireui/announcing-fluxstore-1-6-337efff1791f - thank you!

**Comment by jpmishra1010** [comment]
Still, the issue has not been resolved. I am attaching
[config.zip](https://github.com/inspireui/support/files/3964261/config.zip)

 config file. Please have a look.

**Comment by vumanhsn97** [comment]
@jpmishra1010 
Change your file in lib/models/product.dart to 
[product.dart.zip](https://github.com/inspireui/support/files/3976860/product.dart.zip)

**Comment by jpmishra1010** [comment]
![Screenshot_20191218-161805](https://user-images.githubusercontent.com/32157980/71080058-6b851300-21b2-11ea-87df-7f6119227c73.jpg)
![Screenshot_20191217-232100](https://user-images.githubusercontent.com/32157980/71080073-72ac2100-21b2-11ea-85d3-3835cbb60018.jpg)

Please help me with these issues. 
1. All the images are not loading. 
2. Price of the product is visible in the cart. 
3. No shipping method is available. Even when it is available on the website. 
![Screenshot_20191218-161757](https://user-images.githubusercontent.com/32157980/71080043-64f69b80-21b2-11ea-9bed-4ef9838ff55e.jpg)

**Comment by vumanhsn97** [comment]
@jpmishra1010 
Image loading ok!!! https://tppr.me/uBeN7

**Comment by jpmishra1010** [comment]
Yes after applying the updating product file. Now please look rest of the issues. I have to deliver this project asap.

**Comment by vumanhsn97** [comment]
@jpmishra1010 
to fix price: Change code in lib/widgets/cart_item.dart https://tppr.me/A5JBj

**Comment by jpmishra1010** [comment]
Thank you so much for replying so quickly. And what about shipping method issue?

**Comment by jpmishra1010** [comment]
Please help me with the above issue and how to add taxes in the cart?

**Comment by vumanhsn97** [comment]
@jpmishra1010 We not support shipping by weight. Sorry

**Comment by jpmishra1010** [comment]
Is there any way to do that? I took an order from my client and its urgent. 
2 more thing I need help with:
1. How to add taxes in the cart?
2. I want to add payu money as a payment gateway.

**Comment by jpmishra1010** [comment]
Please someone help me with this.

**Comment by minhcasi** [comment]
@jpmishra1010 - sorry as this feature is kind of advanced features that need some customization - pls try your best!

**Comment by jpmishra1010** [comment]
Its my humble request to help me with the shipping option. Its never that it doesn't support multiple shipping option. What's the use of this app if I can't deliver it??

**Comment by jpmishra1010** [comment]
Even after updating the app. Shipping options are not showing. 
![Screenshot_20200111-051606](https://user-images.githubusercontent.com/32157980/72194138-8144cb80-3432-11ea-88cc-0f0b93ae4bac.jpg)
