### ISSUE TITLE
[listapp] - says no simulator but its installed 

### ISSUE THREAD

**Issue by befreeman5** [inspireui/support#1519]
I keep getting errors saying simulator not installed but it is installed. solution? https://imgur.com/a/m0NbB9l

**Comment by minhcasi** [comment]
@befreeman5 - could you help to create 1 ticket for your all questions/issues ? Thanks

**Comment by befreeman5** [comment]
why? takes longer to create new tickets instead of just answering. very annoying when developers do this.
