### ISSUE TITLE
Source Code Bug

### ISSUE THREAD

**Issue by GWA-AG** [inspireui/support#1523]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
I am attempting to build an app utilizing FluxNews... I have encountered a bug where fstore requires a minimum of ^1.0.8 extended_image_library, however, extended_image_library is currently bugged in Flutter SDK. Please either create a patch or inform me how to modify exisitng files to allow for either dev branches (1.0.9) or a lower threshold value (<1.0.7) for fstore to be utilized in unison with  extended_image_library.

Thanks in advance!

2. Screenshots of issues:

Output (Bare)
![image](https://user-images.githubusercontent.com/39661910/70120518-cce9a580-163a-11ea-9f59-7f715ae1a3c5.png)

Output(with Workaround)
![image](https://user-images.githubusercontent.com/39661910/70120601-fe627100-163a-11ea-9a49-60cbac9454ab.png)

Proof of Bug:
![image](https://user-images.githubusercontent.com/39661910/70120695-2b168880-163b-11ea-9bd7-9f82944e0ce5.png)

Link-
https://github.com/fluttercandies/extended_image/issues/80

3. Proof of my purchase:

![image](https://user-images.githubusercontent.com/39661910/70121291-47ff8b80-163c-11ea-8247-cc742ce08a1a.png)

**Comment by minhcasi** [comment]
@GWA-AG - could you send us the result from "flutter doctor -v" - thanks
