### ISSUE TITLE
[Mstore Pro] - Unable To Load Script. Make Sure Youre Either running a metro server (run react-native start

### ISSUE THREAD

**Issue by Mezardan** [inspireui/support#1524]
Hi. I purchased Mstore Pro software. On Windows 10. Android studio I did the installation. I installed Nodjs, pyhthon27, choco and jdk 8 via cmd.

https://prnt.sc/q60kg8

android studio I get the error like the following when running the application on the emulator. I have been trying to solve the problem from Github and other sources for 3 days, but I couldn't find a solution.

You can be sure in the project folder. I uninstalled Npm at least 10 times on my computer. Every time I run the npm install command in the project folder I get the wrong screen like this.
I couldn't solve my problem because React-native was installed problematic.

Can you help me in this case?

`PS C:\Users\new\Desktop\mstore-pro> npm install
npm WARN deprecated fsevents@1.2.9: One of your dependencies needs to upgrade to fsevents v2: 1) Proper nodejs v10+ support 2) No more fetching binaries from AWS, smaller package size

> postinstall-postinstall@2.0.0 postinstall C:\Users\new\Desktop\mstore-pro\node_modules\postinstall-postinstall
> node ./run.js

'yarn' is not recognized as an internal or external command,
operable program or batch file.
child_process.js:660
    throw err;
    ^

Error: Command failed: yarn run postinstall
'yarn' is not recognized as an internal or external command,
operable program or batch file.

    at checkExecSyncError (child_process.js:621:11)
    at execSync (child_process.js:657:15)
    at Object.<anonymous> (C:\Users\new\Desktop\mstore-pro\node_modules\postinstall-postinstall\run.js:14:5)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11 {
  status: 1,
  signal: null,
  output: [
    null,
    <Buffer >,
    <Buffer 27 79 61 72 6e 27 20 69 73 20 6e 6f 74 20 72 65 63 6f 67 6e 69 7a 65 64 20 61 73 20 61 6e 20 69 6e 74 65 72 6e 61 6c 20 6f 72 20 65 78 74 65 72 6e 61 ... 45 more bytes>
  ],
  pid: 15212,
  stdout: <Buffer >,
  stderr: <Buffer 27 79 61 72 6e 27 20 69 73 20 6e 6f 74 20 72 65 63 6f 67 6e 69 7a 65 64 20 61 73 20 61 6e 20 69 6e 74 65 72 6e 61 6c 20 6f 72 20 65 78 74 65 72 6e 61 ... 45 more bytes>
}
npm WARN @typescript-eslint/eslint-plugin@1.13.0 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @typescript-eslint/parser@1.13.0 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-react@7.12.4 requires a peer of eslint@^3.0.0 || ^4.0.0 || ^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-react-native@3.6.0 requires a peer of eslint@^3.17.0 || ^4 || ^5 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-localization@2.1.6 requires a peer of react-native@^0.41.2 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-localization@2.1.6 requires a peer of react-native-windows@0.41.0-rc.1 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-webview@6.11.1 requires a peer of react-native@>=0.57 <0.60 but none is installed. You must install peer dependencies yourself.
npm WARN styled-components@4.4.1 requires a peer of react-dom@>= 16.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! postinstall-postinstall@2.0.0 postinstall: `node ./run.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the postinstall-postinstall@2.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\new\AppData\Roaming\npm-cache\_logs\2019-12-04T10_33_19_204Z-debug.log`

In addition package.json
`{
  "name": "mstore",
  "version": "3.9.6",
  "description": "React Native mobile app for WooCommerce",
  "author": "InspireUI",
  "private": true,
  "scripts": {
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint .",
    "build:ios": "node node_modules/react-native/local-cli/cli.js bundle --entry-file='index.js' --bundle-output='./ios/mstore/main.jsbundle' --dev=false --platform='ios' --assets-dest='./ios'",
    "setup": "./scripts/setup.sh",
    "setup:android": "./scripts/setup_android.sh",
    "reset": "./scripts/reset.sh",
    "postinstall": "patch-package && npx jetify"
  },
  "dependencies": {
    "@babel/plugin-proposal-class-properties": "^7.5.5",
    "@babel/plugin-proposal-decorators": "^7.4.4",
    "@react-native-community/async-storage": "^1.5.1",
    "@react-native-community/netinfo": "^4.1.3",
    "api-ecommerce": "0.0.33",
    "babel-plugin-transform-remove-console": "^6.9.4",
    "base-64": "^0.1.0",
    "currency-formatter": "^1.5.4",
    "html-entities": "^1.2.1",
    "jetifier": "^1.6.3",
    "lodash": "^4.17.15",
    "moment": "^2.24.0",
    "npm": "^6.13.2",
    "oauth-1.0a": "^2.2.6",
    "patch-package": "^6.1.2",
    "postinstall-postinstall": "^2.0.0",
    "react": "16.8.6",
    "react-native": "0.60.4",
    "react-native-admob": "https://github.com/inspireui/react-native-admob.git#master",
    "react-native-animatable": "^1.3.2",
    "react-native-app-intro-slider": "^3.0.0",
    "react-native-clean-form": "^0.5.0",
    "react-native-collapsible": "^1.4.0",
    "react-native-country-picker-modal": "0.8.0",
    "react-native-drawer": "https://github.com/inspireui/react-native-drawer.git",
    "react-native-facebook-account-kit": "^2.1.0",
    "react-native-fbsdk": "https://github.com/facebook/react-native-fbsdk.git#master",
    "react-native-fluid-slider": "^1.0.2",
    "react-native-gesture-handler": "^1.3.0",
    "react-native-image-zoom-viewer": "^2.2.26",
    "react-native-keyboard-aware-scroll-view": "^0.8.0",
    "react-native-linear-gradient": "^2.5.5",
    "react-native-localization": "^2.1.4",
    "react-native-masked-text": "^1.12.4",
    "react-native-modalbox": "^1.7.1",
    "react-native-onesignal": "https://github.com/inspireui/react-native-onesignal.git",
    "react-native-paper": "^2.16.0",
    "react-native-radio-buttons": "^1.0.0",
    "react-native-render-html": "^4.1.2",
    "react-native-restart": "^0.0.13",
    "react-native-scrollable-tab-view": "happypancake/react-native-scrollable-tab-view#master",
    "react-native-snap-carousel": "^3.8.0",
    "react-native-star-rating": "^1.1.0",
    "react-native-swipe-list-view": "^2.0.0",
    "react-native-swiper": "^1.5.14",
    "react-native-vector-icons": "^6.6.0",
    "react-native-webview": "^6.3.1",
    "react-navigation": "^3.11.1",
    "react-redux": "^7.1.0",
    "redux": "^4.0.4",
    "redux-actions": "^2.6.5",
    "redux-persist": "^5.10.0",
    "redux-thunk": "^2.3.0",
    "reselect": "^4.0.0",
    "tcomb-form-native": "^0.6.20",
    "typescript": "^3.7.3",
    "urijs": "^1.19.1",
    "url": "^0.11.0",
    "url-parse": "^1.4.7",
    "util": "^0.12.1",
    "uuid": "^3.3.2",
    "validate.js": "^0.13.1",
    "wpapi": "^1.2.1"
  },
  "devDependencies": {
    "@babel/core": "7.6.2",
    "@babel/runtime": "7.6.2",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "24.9.0",
    "eslint": "6.5.1",
    "jest": "24.9.0",
    "metro-react-native-babel-preset": "0.56.0",
    "react-test-renderer": "16.10.2",
    "reactotron-react-native": "4.0.2",
    "reactotron-redux": "3.1.2"
  },
  "jest": {
    "preset": "react-native",
    "setupFiles": [
      "./node_modules/react-native-gesture-handler/jestSetup.js"
    ]
  }
}
`

3. Proof of my purchased:

Regular License
--
Purchase code: 646b8569-562c-4375-a1dd-cb0c1c62c597

**Comment by minhcasi** [comment]
@Mezardan - pls try to install yarn library to fix the issue - https://yarnpkg.com/ - thank you!

**Comment by Mezardan** [comment]
Hi. I solved the problem via Android Studio. But I started Mstore Expo with Cbuilder.   

My first problem,   https://prnt.sc/q7yhc0 .   I just want the dimensions here. However, all product features in the woocommerce variant section are visible.      


https://prnt.sc/q7yjra .   My site is completely smooth.

https://prnt.sc/q7ykh2 .

https://prnt.sc/q7ykwu .   These options are already in the feature section. Not selectable Variant.

https://prnt.sc/q7yntr




The other problem is. The payment occurs on the screen. woocommerce APIs, although not correctly configured. The following error occurs.

https://prnt.sc/q7yook . Paypal and Stripe payment methods. It gives the same error.

**Comment by minhcasi** [comment]
@Mezardan - could you help to share the config files (common/config.js and appconfig.json) so that we could help for reproduce and check the issue - thanks

**Comment by Mezardan** [comment]
Hi. Same product varianten problem. I live in Fluxstore Pro. The Confing.js files for the two applications are as follows. If Requested. FluxStore I can also share the purchase code.

**FluxStore Confing.js**

`{
  "HorizonLayout": [
    {
      "layout": "logo",
      "showMenu": true,
      "showSearch": true
    },
    {
      "layout": "category",
      "type": "icon",
      "wrap": false,
      "size": 1.0,
      "radius": 50.0,
      "items": [
        {
          "category": 18,
          "image": "https://user-images.githubusercontent.com/1459805/62820029-2e679f00-bb88-11e9-80de-fdf115cfd942.png",
          "colors": [
            "#3CC2BF",
            "#3CC2BF"
          ],
          "originalColor": false
        },
        {
          "category": 22,
          "image": "assets/icons/categories/ic_dress.png",
          "colors": [
            "#3E6AB5",
            "#3E6AB5"
          ]
        },
        {
          "category": 208,
          "image": "assets/icons/categories/ic_shorts.png",
          "colors": [
            "#53A2CC",
            "#53A2CC"
          ]
        },
        {
          "category": 211,
          "image": "assets/icons/categories/ic_glasses.png",
          "colors": [
            "#53688A",
            "#53688A"
          ]
        },
        {
          "category": 210,
          "image": "assets/icons/categories/ic_tie.png",
          "colors": [
            "#43506A",
            "#43506A"
          ]
        },
        {
          "category": 210,
          "image": "assets/icons/categories/ic_panties.png",
          "colors": [
            "#12B58C",
            "#12B58C"
          ]
        }
      ]
    },
    {
      "layout": "bannerImage",
      "isSlider": true,
      "autoPlay": false,
      "showNumber": false,
      "design": "default",
      "showBackGround": true,
      "radius": 2.0,
      "items": [
        {
          "category": 146,
          "image": "https://user-images.githubusercontent.com/1459805/59846818-12672e80-938b-11e9-8184-5f7bfe66f1a2.png",
          "padding": 15.0
        },
        {
          "category": 148,
          "image": "https://user-images.githubusercontent.com/1459805/60091575-1f12ca80-976f-11e9-962c-bdccff60d143.png",
          "padding": 15.0
        },
        {
          "product": 163,
          "image": "https://user-images.githubusercontent.com/1459805/60091808-a19b8a00-976f-11e9-9cc7-576ca05c2442.png",
          "padding": 15.0
        }
      ]
    },
    {
      "layout": "bannerImage",
      "items": [
        {
          "url": "https://www.modensee.de",
          "image": "https://user-images.githubusercontent.com/1459805/59846820-12672e80-938b-11e9-8fa6-b331b7db331d.png",
          "padding": 5.0
        }
      ]
    },
    {
      "layout": "bannerImage",
      "items": [
        {
          "category": 165,
          "image": "https://user-images.githubusercontent.com/1459805/59846823-12ffc500-938b-11e9-8d93-65ead3d6b1dd.png",
          "padding": 5.0
        },
        {
          "category": 199,
          "image": "https://user-images.githubusercontent.com/1459805/59846824-12ffc500-938b-11e9-8d5a-fc42cb1b7658.png",
          "padding": 5.0,
          "featured": true
        }
      ]
    },
    {
      "name": "Recent View",
      "layout": "recentView"
    },
    {
      "name": "Damenbekleidung",
      "image": "",
      "layout": "threeColumn",
      "category": 146,
      "isSnapping": true
    },
    {
      "name": "Kleider",
      "image": "",
      "layout": "twoColumn",
      "category": 199,
      "isSnapping": true
    },
    {
      "name": "Our Blog Posts",
      "layout": "blog"
    },
    {
      "name": "New Collections",
      "layout": "staggered",
      "limit": 20,
      "category": 29
    }
  ],
  "Setting": {
    "MainColor": "#3FC1BE",
    "ProductListLayout": "list"
  },
  "TabBar": [
    {
      "layout": "home",
      "icon": "assets/icons/tabs/icon-home.png"
    },
    {
      "layout": "category",
      "categoryLayout": "card",
      "icon": "assets/icons/tabs/icon-category.png"
    },
    {
      "layout": "search",
      "icon": "assets/icons/tabs/icon-search.png"
    },
    {
      "layout": "cart",
      "icon": "assets/icons/tabs/icon-cart2.png"
    },
    {
      "layout": "profile",
      "icon": "assets/icons/tabs/icon-user.png"
    }
  ]
}`

Same time. Product colors in Fluxstore application. Can I show thumbnail images, not color.
https://prnt.sc/q8q0rl


Appear in the application.   : https://prnt.sc/q8q1ux

Mstore 
Confing.js

`{
  "WooCommerce": {
    "url": "http://demo.mstore.io",
    "consumerKey": "ck_b7594bc4391db4b56c635fe6da1072a53ca4535a",
    "consumerSecret": "cs_980b9edb120e15bd2a8b668cacc734f7eca0ba40"
  },
  "HorizonLayout": [
    {
      "layout": "circleCategory"
    },
    {
      "layout": "bannerHigh",
      "categoryOrTag": 273,
      "tag": 273
    },
    {
      "layout": "bannerImage",
      "categoryOrTag": 23,
      "imageBanner": "https://user-images.githubusercontent.com/1459805/60091808-a19b8a00-976f-11e9-9cc7-576ca05c2442.png",
      "category": 23
    },
    {
      "name": "featureProducts",
      "image": "",
      "layout": "threeColumn",
      "categoryOrTag": 26,
      "category": 26
    },
    {
      "name": "manCollections",
      "layout": "twoColumn",
      "categoryOrTag": 21,
      "tag": 21
    },
    {
      "name": "News",
      "layout": "Blog",
      "categoryOrTag": 21,
      "tag": 21
    }
  ],
  "MainColor": "#3FC1BE"
}`

Mstore 
Confing.js
/** @format */

import Images from "./Images";
import Constants from "./Constants";
import Icons from "./Icons";

export default {
  /**
   * Step 1: change to your website URL and the wooCommerce API consumeKey
   * Moved to AppConfig.json
   */

  /**
     Step 2: Setting Product Images
     - ProductSize: Explode the guide from: update the product display size: https://mstore.gitbooks.io/mstore-manual/content/chapter5.html
     The default config for ProductSize is disable due to some problem config for most of users.
     If you have success config it from the Wordpress site, please enable to speed up the app performance
     - HorizonLayout: Change the HomePage horizontal layout - https://mstore.gitbooks.io/mstore-manual/content/chapter6.html
       Update Oct 06 2018: add new type of categories
       NOTE: name is define value --> change field in Language.js
       Moved to AppConfig.json
     */
  ProductSize: {
    enable: true,
  },

  HomeCategories: [
    {
      category: 18,
      image: require("@images/categories_icon/ic_shorts.png"),
      colors: ["#4facfe", "#00f2fe"],
    },
    {
      category: 21,
      image: require("@images/categories_icon/ic_tshirt.png"),
      colors: ["#43e97b", "#38f9d7"],
    },
    {
      category: 208,
      image: require("@images/categories_icon/ic_panties.png"),
      colors: ["#fa709a", "#fee140"],
    },
    {
      category: 26,
      image: require("@images/categories_icon/ic_dress.png"),
      colors: ["#7F00FF", "#E100FF"],
    },
    {
      category: 24,
      image: require("@images/categories_icon/ic_glasses.png"),
      colors: ["#30cfd0", "#330867"],
    },
    // {
    //   category: 211,
    //   image: require("@images/categories_icon/ic_socks.png"),
    //   colors: ["#c471f5", "#fa71cd"],
    // },
    // {
    //   category: 212,
    //   image: require("@images/categories_icon/ic_shoes.png"),
    //   colors: ["#2af598", "#009efd"],
    // },
    // {
    //   category: 210,
    //   image: require("@images/categories_icon/ic_woman_shoes.png"),
    //   colors: ["#f43b47", "#453a94"],
    // },
  ],
  /**
     step 3: Config image for the Payment Gateway
     Notes:
     - Only the image list here will be shown on the app but it should match with the key id from the WooCommerce Website config
     - It's flexible way to control list of your payment as well
     Ex. if you would like to show only cod then just put one cod image in the list
     * */
  Payments: {
    cod: require("@images/payment_logo/cash_on_delivery.png"),
    paypal: require("@images/payment_logo/PayPal.png"),
    stripe: require("@images/payment_logo/stripe.png"),
  },

  /**
     Step 4: Advance config:
     - showShipping: option to show the list of shipping method
     - showStatusBar: option to show the status bar, it always show iPhoneX
     - LogoImage: The header logo
     - LogoWithText: The Logo use for sign up form
     - LogoLoading: The loading icon logo
     - appFacebookId: The app facebook ID, use for Facebook login
     - CustomPages: Update the custom page which can be shown from the left side bar (Components/Drawer/index.js)
     - WebPages: This could be the id of your blog post or the full URL which point to any Webpage (responsive mobile is required on the web page)
     - intro: The on boarding intro slider for your app
     - menu: config for left menu side items (isMultiChild: This is new feature from 3.4.5 that show the sub products categories)
     * */
  shipping: {
    visible: true,
    zoneId: 1, // depend on your woocommerce
    time: {
      free_shipping: "4 - 7 Days",
      flat_rate: "1 - 4 Days",
      local_pickup: "1 - 4 Days",
    },
  },
  showStatusBar: true,
  LogoImage: require("@images/logo-main.png"),
  LogoWithText: require("@images/logo_with_text.png"),
  LogoLoading: require("@images/logo.png"),

  showAdmobAds: false,
  AdMob: {
    deviceID: "pub-2101182411274198",
    rewarded: "ca-app-pub-2101182411274198/5096259336",
    interstitial: "ca-app-pub-2101182411274198/8930161243",
    banner: "ca-app-pub-2101182411274198/4100506392",
  },
  appFacebookId: "422035778152242",
  CustomPages: { contact_id: 10941 },
  WebPages: { marketing: "http://inspireui.com" },

  intro: [
    {
      key: "page1",
      title: "Welcome to MStore!",
      text: "Get the hottest fashion by trend and season right on your pocket.",
      icon: "ios-basket",
      colors: ["#0FF0B3", "#036ED9"],
    },
    {
      key: "page2",
      title: "Secure Payment",
      text: "All your payment infomation is top safety and protected",
      icon: "ios-card",
      colors: ["#13f1fc", "#0470dc"],
    },
    {
      key: "page3",
      title: "High Performance",
      text: "Saving your value time and buy product with ease",
      icon: "ios-finger-print",
      colors: ["#b1ea4d", "#459522"],
    },
  ],

  /**
   * Config For Left Menu Side Drawer
   * @param goToScreen 3 Params (routeName, params, isReset = false)
   * BUG: Language can not change when set default value in Config.js ==> pass string to change Languages
   */
  menu: {
    // has child categories
    isMultiChild: true,
    // Unlogged
    listMenuUnlogged: [
      {
        text: "Login",
        routeName: "LoginScreen",
        params: {
          isLogout: false,
        },
        icon: Icons.MaterialCommunityIcons.SignIn,
      },
    ],
    // user logged in
    listMenuLogged: [
      {
        text: "Logout",
        routeName: "LoginScreen",
        params: {
          isLogout: true,
        },
        icon: Icons.MaterialCommunityIcons.SignOut,
      },
    ],
    // Default List
    listMenu: [
      {
        text: "Shop",
        routeName: "Home",
        icon: Icons.MaterialCommunityIcons.Home,
      },
      {
        text: "News",
        routeName: "NewsScreen",
        icon: Icons.MaterialCommunityIcons.News,
      },
      {
        text: "contactus",
        routeName: "CustomPage",
        params: {
          id: 10941,
          title: "contactus",
        },
        icon: Icons.MaterialCommunityIcons.Pin,
      },
      {
        text: "About",
        routeName: "CustomPage",
        params: {
          url: "http://inspireui.com/about/",
        },
        icon: Icons.MaterialCommunityIcons.Email,
      },
    ],
  },

  // define menu for profile tab
  ProfileSettings: [
    {
      label: "WishList",
      routeName: "WishListScreen",
    },
    {
      label: "MyOrder",
      routeName: "MyOrders",
    },
    {
      label: "Address",
      routeName: "Address",
    },
    {
      label: "Currency",
      isActionSheet: true,
    },
    // only support mstore pro
    // {
    //   label: "Languages",
    //   routeName: "SettingScreen",
    // },
    {
      label: "PushNotification",
    },
    {
      label: "DarkTheme",
    },
    {
      label: "contactus",
      routeName: "CustomPage",
      params: {
        id: 10941,
        title: "contactus",
      },
    },
    {
      label: "Privacy",
      routeName: "CustomPage",
      params: {
        url: "https://inspireui.com/privacy",
      },
    },
    {
      label: "termCondition",
      routeName: "CustomPage",
      params: {
        url: "https://inspireui.com/term-of-service",
      },
    },
    {
      label: "About",
      routeName: "CustomPage",
      params: {
        url: "http://inspireui.com",
      },
    },
  ],

  // Homepage Layout setting
  layouts: [
    {
      layout: Constants.Layout.card,
      image: Images.icons.iconCard,
      text: "cardView",
    },
    {
      layout: Constants.Layout.simple,
      image: Images.icons.iconRight,
      text: "simpleView",
    },
    {
      layout: Constants.Layout.twoColumn,
      image: Images.icons.iconColumn,
      text: "twoColumnView",
    },
    {
      layout: Constants.Layout.threeColumn,
      image: Images.icons.iconThree,
      text: "threeColumnView",
    },
    {
      layout: Constants.Layout.horizon,
      image: Images.icons.iconHorizal,
      text: "horizontal",
    },
    {
      layout: Constants.Layout.advance,
      image: Images.icons.iconAdvance,
      text: "advanceView",
    },
  ],

  // Default theme loading, this could able to change from the user profile (reserve feature)
  Theme: {
    isDark: false,
  },

  // new list category design
  CategoriesLayout: Constants.CategoriesLayout.card,

  // WARNING: Currently when you change DefaultCurrency, please uninstall your app and reinstall again. The redux saved store.
  DefaultCurrency: {
    symbol: "$",
    name: "US Dollar",
    code: "USD",
    name_plural: "US dollars",
    decimal: ".",
    thousand: ",",
    precision: 2,
    format: "%s%v", // %s is the symbol and %v is the value
  },

  DefaultCountry: {
    code: "en",
    RTL: false,
    language: "English",
    countryCode: "US",
    hideCountryList: false, // when this option is try we will hide the country list from the checkout page, default select by the above 'countryCode'
  },

  /**
   * Config notification onesignal, only effect for the Pro version
   */
  OneSignal: {
    appId: "43948a3d-da03-4e1a-aaf4-cb38f0d9ca51",
  },
  /**
   * Login required
   */
  Login: {
    RequiredLogin: false, // required before using the app
    AnonymousCheckout: false, // required before checkout or checkout anonymous
  },

  Layout: {
    HideHomeLogo: false,
    HideLayoutModal: false
  },

  Affiliate: { enable: false }
};

**Comment by minhcasi** [comment]
Hi @Mezardan - i'm sorry that not understand you idea here? Do you mean the variant has the same issues on both Mstore and Fluxstore ? Could i know which one do you prefer to fix?

**Comment by minhcasi** [comment]
Also, try to include the config as txt file as once you paste the whole config here, it's mixed with your questions and not easy to read

**Comment by Mezardan** [comment]
Hi. At first I started editing Mstore. Subsequently, I switched to the more advanced version of Fluxstore.

Let's continue our problem with Fluxstore Pro.

The First Problem: As on the Product Page, that is, under my product. I just want to show Color and Size.

https://prnt.sc/qa2u5d   Red arrow with marked ones. What to do on the product page.  

The product features marked with yellow. Woocommerce product settings are off as in this link.

https://prnt.sc/qa2vxy  

This is how the Product appears on my site. Other product features marked with yellow, which appear in the application, are off as in the link.

https://prnt.sc/qa2x6r



https://prnt.sc/qa2ybg   In this case it should only appear in the Color application. But in practice all product features appear. That's my problem.

**Comment by minhcasi** [comment]
@Mezardan - pls try to use the Inspector to customize the customize base on your requirement, it quite easy with the Flutter - https://docs.inspireui.com/fluxstore/useful-tip/

Also, update the app to the latest version 1.6, there is some bug fix and compatible with Flutter 1.12 - Detail changelog will be updated from https://medium.com/@inspireui/announcing-fluxstore-1-6-337efff1791f - thank you!

**Comment by Mezardan** [comment]
Hi. I have updated to the latest versions of Flutter and Fluxstore.    
But my problem is not solved.

I tried to understand the problem with Flutter Inspector. But I don't know why.  
In the screenshot below, you can see that the Problem persists.
https://prnt.sc/qav0sx  

In addition. The file Product Variant.dart and Config.dart in the Android folder are attached.

https://www.modensee.de/product_variant.dart
https://www.modensee.de/config.dart

**Comment by minhcasi** [comment]
@Mezardan - could you help to send you current customize source code to support@inspireui.com - i will 
help for checking - thank you!

**Comment by Mezardan** [comment]
@minhcasi   Hi. I sent you an e-mail.

**Comment by minhcasi** [comment]
@Mezardan - confirmed i got it

@vumanhsn97 - pls help to investigating this feature request.
We only show the variant if check this option - https://tppr.me/ZHuYu - other attribute should be hide.

**Comment by vumanhsn97** [comment]
@Mezardan 
Quickly fix: Change lines code in lib/models/product.dart https://tppr.me/cf0cO
