### ISSUE TITLE
[Fluxstore WooCommerce - Flutter E-commerce App] - Version: 1.5.8--- Sign In with Google 

### ISSUE THREAD

**Issue by itej7** [inspireui/support#1525]
1. My issue:
We need Google sign in for this app. Kindly let us know if you have already implemented it.

2. Proof of my purchased:
Product Purchase code: c2f1abaf-6ebe-4c07-875d-050022ba2a14 - 14 Oct 2019 REGULAR LICENSE

**Comment by minhcasi** [comment]
@itej7 - this feature will be added to our next update 1.6 - thanks

**Comment by itej7** [comment]
@minhcasi : Thanks for the update!
