### ISSUE TITLE
Invarient Violation

### ISSUE THREAD

**Issue by khaja25** [inspireui/support#1528]
Hey there , In App when i open the categories  the blow issue happend i need a solution for that

![issuef](https://user-images.githubusercontent.com/58036762/70150550-3071e280-16d0-11ea-9855-4096461c0945.jpeg)

**Comment by khaja25** [comment]
![buy](https://user-images.githubusercontent.com/58036762/70151892-39fc4a00-16d2-11ea-905f-ef5657087f69.jpeg)

**Comment by minhtruong315** [comment]
@khaja25 can you send me AppConfig.json?

**Comment by khaja25** [comment]
[AppConfig.txt](https://github.com/inspireui/support/files/3930655/AppConfig.txt)

This is my AppConfig.json file

**Comment by khaja25** [comment]
![issue2](https://user-images.githubusercontent.com/58036762/70329813-3a2b4f80-1862-11ea-9223-6f1b14410e58.jpeg)
![issue1](https://user-images.githubusercontent.com/58036762/70329820-3e576d00-1862-11ea-8851-e31207e02312.jpeg)

Hey there, I Have a issue on whatever the catagories  i load first 10 product image only displayed...need solution for it..

**Comment by minhtruong315** [comment]
@khaja25 You're using server in localhost
```"Cezerin": {
    "url": "http://192.168.0.119:3001"
  },
```
Please up your website to hosting and send me the url

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
