### ISSUE TITLE
FluxStore MultiVendor V1.2.0 - SplashScreen not working 

### ISSUE THREAD

**Issue by daav7713** [inspireui/support#1529]
---------

1. My issue: If I run the application with the splashscreen by default everything works fine, but if I change it for a custom one it stays locked and does not change to the home screen of the app, it remains on the splashscreen. And if i put and static splashscreen it shows Fluxstore logo not the static image.

2. Screenshots issues:

3. Proof of my purchased:
![image](https://user-images.githubusercontent.com/15809768/70157114-9764ac80-167a-11ea-8b3c-94b8b1988c15.png)

3. Config files (optional)

constants.dart

//const kSplashScreen = "assets/images/splashscreen.flr";
const kSplashScreen = "assets/images/mycircle.flr";
//const kSplashScreen = "assets/images/splashscreen.png";

**Comment by minhcasi** [comment]
@daav7713 - when you update the mycircle.flr please try to match the name from the Animation tab from 2dimensions

- https://tppr.me/ryJUg

**Comment by daav7713** [comment]
Hi, I change the value of startAnimation 'fluxstore' to 'mycircle' as I understand that you suggest me and it didn't work.

**Comment by daav7713** [comment]
Also if I comment the flare animation and leave the static image (png), the app not show the static image and istead shows app logo, but in the top shows a little la el that says bug
![Screenshot_20191205-083240](https://user-images.githubusercontent.com/15809768/70244297-c55cf600-1739-11ea-8e68-ec7f833728db.png)

**Comment by minhcasi** [comment]
@daav7713 - could you share the source of mycircle animate then we will help for checking

Regarding the current splash static only load the logo image - you can customize this widget to load the whole splash Image, we may upgrade the splash screen more easy to use to support both Logo or whole splash screen on next release as it seems not smooth integration 

Very best!

**Comment by daav7713** [comment]
This is the file. its a simple "animation".
https://drive.google.com/file/d/1kKTNxK4qbDQaSD42JwUckfkfVxsFO-RP/view?usp=sharing

With version 1.0.1 the change of the animation work fine with that same file.

**Comment by minhcasi** [comment]
@daav7713 - could you help to share the source file as we could not check the animation setting from the final flr file ?

**Comment by daav7713** [comment]
Wich source file do you need?

**Comment by daav7713** [comment]
Its there any news? splash screen still gives me bugs :(

**Comment by minhcasi** [comment]
Hi mean the xx.flr2d format as the one you have sent is final export file (.flr file type) - thanks

**Comment by daav7713** [comment]
https://drive.google.com/file/d/1TNFF0l3yyBXruW7MRRk3rG_OmxEwuDcS/view?usp=sharing 

Thats the .flr2d file

**Comment by vumanhsn97** [comment]
@daav7713 
https://tppr.me/DqGy2
Dont find your error. Make sure you export file type json

**Comment by daav7713** [comment]
the splashscreen appears to me also, the error is that stays in the splashscreen and does not go to the main screen of the app, iit remains as locked.

**Comment by vumanhsn97** [comment]
@daav7713 Hm...! You need to search key "animations" in .flr file https://tppr.me/RGzl and change startAnimation in lib/app.dart https://tppr.me/8ksIO look like your file .flr :))
