### ISSUE TITLE
[BeoNews] pro cannot install. Please help

### ISSUE THREAD

**Issue by trappat** [inspireui/support#153]
**Mandatory Info (please complete the following information):**
 - Product: BeoNews Pro
 - Your Purchased Code: bb904f63-d575-4586-9afd-b7d283e357ff

**Describe the issues**
When I open in the simulator that the app gives me problems . I ran through xCode and terminal and neither work. I cant even test the default app settings. Image below

I've tried everything in the documentation! Yarn install, npm install, clear cache, Everything! This is getting frustrating that its taking so much work and bugs to even run the default app. 

**Screenshots**
https://ibb.co/GHYfvFf

**Additional context**
Add any other detail logs about the problem here.

**Comment by minhcasi** [comment]
Hi, we could help to remote via teamviewer to help to resolve it quickly - please share the account from 9am-4pm GMT+7 from Mon-Fri - thank you!

**Comment by trappat** [comment]
> Hi, we could help to remote via teamviewer to help to resolve it quickly - please share the account from 9am-4pm GMT+7 from Mon-Fri - thank you!

Im ready when you are. Whats your skype or can you add me on skype "thetrappat" so we can communicate

**Comment by trappat** [comment]
Im ready when you are. Whats your skype or can you add me on skype
"thetrappat" so we can communicate

**Comment by minhcasi** [comment]
added you Skype, move this conversion to Skype - thank you!
