### ISSUE TITLE
[listapp] - multiple issues

### ISSUE THREAD

**Issue by befreeman5** [inspireui/support#1530]
1. where do I find the code that goes into Cebuilder Delivery tab?
2. do you have to update the app every time you add new content to the website?
3.  any extra steps on the Wordpress plugins after installing & activating them? Anything you have to do extra to them?
4. do I need to change these settings? https://imgur.com/a/u31y4so it’s not clear on what to do. any other settings need to be changed in the plugins?

**Comment by minhcasi** [comment]
@befreeman5 - thank you for the questions

1. you can find it from the app.json - this file is used to config the info for bundle app, you can also check this guide - https://docs.expo.io/versions/latest/workflow/configuration/

2. Every time you update the content, it will update to the app ( i mean the Listing data, blog...)

3. After setup the wordpress site, you can use the CeBuilder to config the app, or use our document to customize the app - http://docs.inspireui.com/listapp

4. It's is optional, you can change to your own firebase, please check the document guide as well
