### ISSUE TITLE
Cebuilder dosen't work after all settings tried, windows 10

### ISSUE THREAD

**Issue by onlineosman** [inspireui/support#1531]
Please provide us the video guide with 3.8 Version of MStore pro for windows, tried every thing but couldn't setup.
![PP](https://user-images.githubusercontent.com/34172061/70164529-c1e65200-16da-11ea-95c5-60a682510c94.png)

**Comment by onlineosman** [comment]
![error](https://user-images.githubusercontent.com/34172061/70164612-ec380f80-16da-11ea-92c0-0382475b0f8a.png)

**Comment by minhcasi** [comment]
@concuacon - pls help for suggestion - thanks

**Comment by minhtruong315** [comment]
@onlineosman add my skype: minhtruong315@gmail.com. I will help you check it via skype

**Comment by onlineosman** [comment]
HI Added to live: minhtruong315

**Comment by minhtruong315** [comment]
I dont see your skype. pls give me your skype

**Comment by onlineosman** [comment]
my id: onlineosman@live.com (OR) osmanmustafa

**Comment by minhtruong315** [comment]
supported.
