### ISSUE TITLE
[Mstore pro] - Please help in plugins in wp 

### ISSUE THREAD

**Issue by momonchi** [inspireui/support#1532]
Can anyone share your wordpress full setup? I'am stuck in check out from my app, it is always crash when in delivery tab. If there's a chance to achieve this like of store http://demo.mstore.io/

please help. thanks in advance.

---------

![image](https://user-images.githubusercontent.com/5693186/70172226-3507bc80-170b-11ea-88c8-904c2a112063.png)

**Comment by minhcasi** [comment]
@momonchi  - could you check this WP site, we have cloned it from demo.mstore.io - https://github.com/inspireui/mstore

**Comment by momonchi** [comment]
Do I need to follow this? https://github.com/inspireui/support/issues/38#issuecomment-441363940

**Comment by minhcasi** [comment]
@momonchi - no, the latest mstore-api https://wordpress.org/plugins/mstore-api/ will handle this setting so you do not need for that setting :)

**Comment by momonchi** [comment]
@minhcasi alright, thanks. I will create clean wp through this https://github.com/inspireui/mstore.

**Comment by momonchi** [comment]
![image](https://user-images.githubusercontent.com/5693186/70318418-fda82580-185a-11ea-82c4-6c993f7b13e9.png)

this is what I get when I resume to payment

**Comment by momonchi** [comment]
How to resolve this html text in order ? 

![image](https://user-images.githubusercontent.com/5693186/70370725-ba56c100-1905-11ea-93ed-8b55ea55ad1c.png)

**Comment by Q8hma** [comment]
have same bug and when i open the site to clock checkout to go the page for the payment why not direct ?

thanks

**Comment by minhcasi** [comment]
@minhtruong315 - pls help to check the mstore-api plugin that could impact to this issue - thank you!

**Comment by minhtruong315** [comment]
@momonchi @Q8hma pls update the latest version for Mstore Api plugin to fix this issue

**Comment by momonchi** [comment]
> @momonchi @Q8hma pls update the latest version for Mstore Api plugin to fix this issue

thank you. It is fixed now. :)

**Comment by momonchi** [comment]
Would you try the registration by sign up page? After update It doesn't work well.

**Comment by minhtruong315** [comment]
Can you record screen?

**Comment by Q8hma** [comment]
> @momonchi @Q8hma pls update the latest version for Mstore Api plugin to fix this issue

thnx its work now but the register not get the email after i update "WPUserAPI.js"

**Comment by minhtruong315** [comment]
What do you update?

**Comment by Q8hma** [comment]
> 
> 
> What do you update?

like this commented https://github.com/inspireui/support/issues/1406#issuecomment-555421606

**Comment by minhtruong315** [comment]
@momonchi send me your source code via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/1532

**Comment by Q8hma** [comment]
> @momonchi send me your source code via email: [truong@inspireui.com](mailto:truong@inspireui.com)
> with subject: #1532

```
/**
 * Created by InspireUI on 01/03/2017.
 * An API for JSON API Auth Word Press plugin.
 * https://wordpress.org/plugins/json-api-auth/
 *
 * @format
 */

import { AppConfig } from "@common";
import { request, error } from "./../Omni";

const url = AppConfig.WooCommerce.url;
const isSecured = url.startsWith("https");
const secure = isSecured ? "" : "&insecure=cool";
const cookieLifeTime = 120960000000;

const WPUserAPI = {
  login: async (username, password) => {
    const _url = `${url}/api/mstore_user/generate_auth_cookie/?second=${cookieLifeTime}&username=${username}&password=${password}${secure}`;
    return await request(_url);
  },
  loginFacebook: async (token) => {
    const _url = `${url}/api/mstore_user/fb_connect/?second=${cookieLifeTime}&access_token=${token}${secure}`;
    return await request(_url);
  },
  loginSMS: async (token) => {
    const _url = `${url}/api/mstore_user/sms_login/?access_token=${token}${secure}`;
    return await request(_url);
  },

  register: async ({
    username,
    email,
    firstName,
    lastName,
    password = undefined,
  }) => {
    try {
      const nonce = await WPUserAPI.getNonce();
      const _url =
        `${`${url}/api/mstore_user/register/?` +
        `username=${username}` +
        `&user_login=${username}` +
        `&email=${email}` +
        `&display_name=${`${firstName}+${lastName}`}` +
        `&first_name=${firstName}` +
        `&last_name=${lastName}`}${
        password ? `&user_pass=${password}` : ""
        }&nonce=${nonce}` + `&notify=both${secure}`;
      return await request(_url);
    } catch (err) {
      error(err);
      return { error: err };
    }
  },
  getNonce: async () => {
    const _url = `${url}/api/get_nonce/?controller=mstore_user&method=register`;
    const json = await request(_url);
    return json && json.nonce;
  },
};

export default WPUserAPI;
```

**Comment by Q8hma** [comment]
or you need full code source ???

**Comment by minhtruong315** [comment]
yes

**Comment by minhcasi** [comment]
@Q8hma @minhtruong315 - could you help the status on this ticket - thanks

**Comment by minhtruong315** [comment]
@Q8hma pls send me your source code?

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
