### ISSUE TITLE
BeoNews null is not an object 

### ISSUE THREAD

**Issue by bao-1986** [inspireui/support#1533]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: 
1. I installed a plugin called Category Featured Image, I upload an image, all the app posts had the same featured image.
2. I deleted the plugin, but the app did not return the old images. 
3. I deleted the image from wordpress. now I am stuck with this error. 

 

2. Screenshots issues:

3. Proof of my purchased:

3. Config files (optional)

**Comment by minhcasi** [comment]
@bao-1986 - please help to install this plugin - https://wordpress.org/plugins/better-rest-api-featured-images/ 

We also noted the require plugin from the document - https://docs.inspireui.com/beonews/wordpress-setting/

**Comment by bao-1986** [comment]
problem solved after I restored all my wordpress. the plugin Category Featured Image caused damage i think. all of this happened because i was trying to change these category default photos. can you tell me from where I change them? 
![1575556447(1)](https://user-images.githubusercontent.com/58382254/70244965-4a82f200-17b0-11ea-9d30-1e55c1164585.jpg)

**Comment by bao-1986** [comment]
they appear like this from the first startup of the app. default

**Comment by dermayank** [comment]
I have installed all the plugins but still getting "The rest api is not working correctly!" error.

**Comment by minhcasi** [comment]
@bao-1986 - could you change the Category Image from the wordpress site when editing the category, there is the section to upload new image

@dermayank - we have updated on your 1547 ticket

**Comment by bao-1986** [comment]
@minhcasi category image meed a plugin right?
Can you print screen the section you are talking about. Thank you !

**Comment by minhcasi** [comment]
@bao-1986 - sorry i missed the woocommerce setting one - for Wordpress site it is not available and you need to create the mapping image from the config file, please check this guide - https://docs.inspireui.com/beonews/customization/#change-the-category-images

**Comment by bao-1986** [comment]
I did not change them because the old one are existed and not showin😁, ok i will try to update them

**Comment by bao-1986** [comment]
Can you help me with this issue also , my total issues are two only until now and you guys did a good job . https://github.com/inspireui/support/issues/1556
