### ISSUE TITLE
[FluxListing] - Blog 

### ISSUE THREAD

**Issue by lancerynearson** [inspireui/support#1534]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
Blog is broken in newest version of the app. Even on your demo in the PlayStore
2. Screenshots issues:
![IMG_0813](https://user-images.githubusercontent.com/51379820/70183700-3e196f00-16b4-11ea-90a3-05e652e3b514.jpg)

3. Proof of my purchased:
![shot](https://user-images.githubusercontent.com/51379820/70183528-fa266a00-16b3-11ea-9480-94046b904725.png)

3. Config files (optional)

**Comment by minhcasi** [comment]
@minhtruong315 - please help for the investigating - thank you!

**Comment by minhtruong315** [comment]
ok. I will check

**Comment by minhtruong315** [comment]
![IMG_85FACAEA663A-1](https://user-images.githubusercontent.com/10402500/70490820-08e8a300-1b32-11ea-9491-d65ce65e261b.jpeg)
I checked app in google play. It's working well on my phone. please check again

**Comment by lancerynearson** [comment]
Wrong Blog... check the blog from the side menu or add the blog to the home screen.

**Comment by lancerynearson** [comment]
Any update ?

**Comment by minhcasi** [comment]
@concuacon - pls help to check this test case "check the blog from the side menu or add the blog to the home screen."

**Comment by minhtruong315** [comment]
You can replace widgets/blog folder like this
[blog.zip](https://github.com/inspireui/support/files/3987264/blog.zip)
And change widgets/home/horizontal/blog_list_items.dart like this
[blog_list_items.dart.zip](https://github.com/inspireui/support/files/3987267/blog_list_items.dart.zip)

**Comment by minhtruong315** [comment]
[config.json.zip](https://github.com/inspireui/support/files/3987312/config.json.zip)
You can use this config.json to see blog at home screen
