### ISSUE TITLE
Need help for fluxstore

### ISSUE THREAD

**Issue by arthenterprises** [inspireui/support#1536]
Hello,
purchased fluxstore from code canyon but I can't Integrate so please help for making app.

**Comment by minhcasi** [comment]
@arthenterprises - please share the screenshot of the issues so that we could help with checking - thank you!

**Comment by arthenterprises** [comment]
I can't make it my app with woocommerce, can you please access and check error.

**Comment by minhcasi** [comment]
@arthenterprises - could you help to share your config file so that we could help for checking.

Following detail document could be helpful for your first set up the app:
http://docs.inspireui.com/fluxstore
https://www.youtube.com/inspireui

**Comment by arthenterprises** [comment]
Do you need Cpanel Details or anything else???
I want to make app for www.mayankjewels.in

**Comment by arthenterprises** [comment]
sdk issue

**Comment by arthenterprises** [comment]
can be possible to check my issue on an urgent basis, last 12 days I am just posting issue and purchased note.

**Comment by minh-inspireui** [comment]
Hi @arthenterprises - we did not request your provide the purchase code and could recognize the username on the website. We request the "screenshot of the issues"  or your config file (common/config.dart and conifg.json) so that the team could help for checking.

**Comment by arthenterprises** [comment]
How to find config file (common/config.dart and conifg.json)??

**Comment by minhcasi** [comment]
https://docs.inspireui.com/fluxstore/woocommerce-setup/#step-3-setup-fluxstore - it's from the project lib folder - just follow this config and setting then you can set up the app successful

**Comment by arthenterprises** [comment]
give me a few minutes, I will check again.

**Comment by arthenterprises** [comment]
Need help in the android studio.
confiq.dart & confiq.json file also show error in android studio.

**Comment by minhcasi** [comment]
Hi, pls make sure you install the Flutter plugin for Android Studio, pls check https://flutter.dev/docs/get-started/editor

**Comment by arthenterprises** [comment]
flutter plugins installed. but problem with dart.
can you please check direct access, so I can try to complete fast.

**Comment by minhcasi** [comment]
@arthenterprises - let us know when you are online today from 9:00am to 5:00pm GMT+7 - we could help for direct access to help you install it quickly - thanks

**Comment by minhcasi** [comment]
supported - let us know if you have any further support issue - thank you so much for your rating feedback 😊

**Comment by arthenterprises** [comment]
Need help for build Apk to submit Google playstore.

**Comment by minhcasi** [comment]
@arthenterprises - pls try your best with this document guide - https://flutter.dev/docs/deployment/android or our video https://www.youtube.com/watch?v=-4e6eC_zBk4&t=2s

**Comment by arthenterprises** [comment]
Sorry, I can't complete it without help. please help to complete the
application.

**Comment by arthenterprises** [comment]
please connect again on team viewer.

**Comment by minhcasi** [comment]
@arthenterprises - please help to try your best with with above document guide to generate final apk as this will take your time with this job.

We're sorry that could not help for generate your final apk build, we usually charge very high cost for the delivery service but also stop support right now (due to the team is full with other project).

Hope you can understand our case and spend time to check the Flutter document from Google for generate app, we are here to give any support comment if you have an issues

Happy coding !
