### ISSUE TITLE
I did not find the MainActivity.java file in Fluxstore 1.5.9

### ISSUE THREAD

**Issue by masngun** [inspireui/support#1537]
Hello, I followed the tutorial in youtube , (Setup WooCommerce On DigitalOcean (Flutter E-Commerce App In 10 Minutes, Ep. 05). I didn't find the **inspiration/fluxstore** folder in the **app/src/main/com/** directory

![image](https://user-images.githubusercontent.com/45061610/70203609-0102ba80-1750-11ea-8c18-b489d4d325ec.png)

**Comment by minhcasi** [comment]
Hi, please change the Kolint file  - https://tppr.me/ZxKoQ - we have updated it to support the Kolint and compatible with later Flutter 1.9 - thanks
