### ISSUE TITLE
Fluxstore App for Woocommerce

### ISSUE THREAD

**Issue by ukveda** [inspireui/support#1538]
Hello,
Just purchased Fluxstore WooCommerce - Flutter E-commerce Full App when I tried to upload it on my wordpress dashboard through Pluging - Add New - Upload Plugin, after uploading 100% it gives error "503 - Service unavailable - The server is temporarily busy, try again later! please find the attached screenshot.
![screencapture-khadibrand-in-wp-admin-update-php-2019-12-05-15_03_23](https://user-images.githubusercontent.com/58551104/70224981-2b666f00-1774-11ea-8b79-2b4f3aa35cf5.png)

**Comment by minhcasi** [comment]
@ukveda - could you able to login to the File Manager or FTP of your hosting and remove the plugins that you have just uploaded, could I know which the product that caused this issue?

Please note that the requirement for plugins is PHP 7.x.

Let us know your checking, thank you!

**Comment by minhcasi** [comment]
Let us know if you still have the issue and reopen the ticket - thanks

**Comment by ukveda** [comment]
> @ukveda - could you able to login to the File Manager or FTP of your hosting and remove the plugins that you have just uploaded, could I know which the product that caused this issue?
> 
> Please note that the requirement for plugins is PHP 7.x.
> 
> Let us know your checking, thank you!

How to remove the plugin,

**Comment by minhcasi** [comment]
@ukveda - just remove mstore-api folder from wp-contents/plugins from your hosting - if there is any related plugins cause the issues, try to remove it as well

**Comment by minhcasi** [comment]
Then enable the debug mode from the wp-config.php file from your wordpress site to check the root cause issue.

Please also note that the required PHP version is 7.x, on the 5.x or 6.x could be have an issues

**Comment by ukveda** [comment]
> @ukveda - just remove mstore-api folder from wp-contents/plugins from your hosting - if there is any related plugins cause the issues, try to remove it as well

there is no such folder in that location, I tried uploading the zip file again from my wordpress dashboard - plugin - add new - uploaded the fluxstore app package zip file. Same result 503 Service Unavailable. Is this the right step to upload this package.

**Comment by ukveda** [comment]
There is no reply from your end...
