### ISSUE TITLE
Fluxstore - Payment

### ISSUE THREAD

**Issue by almazamangaliev** [inspireui/support#1539]
1. My issue:
 I add payment method to woocommerce, it is displayed in the application!
 But after select this payment method i get white screen
2. Screenshots issues:
![image](https://user-images.githubusercontent.com/44086148/70232871-5793e700-1798-11ea-957d-43d8021c2c74.png)

3. Proof of my purchased:
c8100480-deab-4cf8-a2fc-61dc313dcf52
3. Config files (optional)

**Comment by minhcasi** [comment]
@almazamangaliev - could you check this guide - https://docs.inspireui.com/fluxstore/multi-payment/#404-error-page

Also, try to enable the debug mode from wp_config.php from your website so see the return detail error log.

Let us know your checking, thank you!

**Comment by minhcasi** [comment]
@almazamangaliev  - let us know if still have an issue and reopen the ticket - thanks
