### ISSUE TITLE
[CeStore] RazorPay Integration

### ISSUE THREAD

**Issue by souravlahoti** [inspireui/support#154]
purchase code is 22706124
CeStore - React Native App

Do we have support for RazorPay integration on the mobile app side?
RazorPay library  does not support expo. As per their Documentation below:-

The react native plugin is wrapper around native SDK, so it doesn't work with the tools like expo which doesn't support native modules.

**Comment by minhcasi** [comment]
Hi sorry the CeStore is not ready support for RazorPay - we will add this request to our backlog - thank you!

**Comment by sankar2389** [comment]
@minhcasi We already integrated Razorpay gateway in Cezerin & Web Client. All we need is support for expo Mobile Client (like this https://www.youtube.com/watch?v=uTxvwgG9M3s). Please guide us.


![screen shot 2019-01-05 at 9 50 11 am](https://user-images.githubusercontent.com/10666209/50720311-9aed5d80-10d0-11e9-97e8-612b6c8c10f5.png)
![screen shot 2019-01-05 at 9 51 07 am](https://user-images.githubusercontent.com/10666209/50720312-9b85f400-10d0-11e9-981b-10789d4f630b.png)
![screen shot 2019-01-05 at 9 51 30 am](https://user-images.githubusercontent.com/10666209/50720313-9b85f400-10d0-11e9-8ba5-33b9b18b2a62.png)
![screen shot 2019-01-05 at 9 52 18 am](https://user-images.githubusercontent.com/10666209/50720314-9c1e8a80-10d0-11e9-8df2-cf89410aa9d8.png)
![screen shot 2019-01-05 at 9 52 45 am](https://user-images.githubusercontent.com/10666209/50720315-9c1e8a80-10d0-11e9-9d19-56958b767510.png)
![screen shot 2019-01-05 at 9 52 56 am](https://user-images.githubusercontent.com/10666209/50720316-9cb72100-10d0-11e9-8fcf-97980da80cf6.png)
![screen shot 2019-01-05 at 9 53 31 am](https://user-images.githubusercontent.com/10666209/50720317-9cb72100-10d0-11e9-8ae0-7db0de1e80f4.png)

**Comment by minhcasi** [comment]
Noted for further investigating - https://app.intercom.io/a/apps/xro9xnfd/inbox/inbox/2664005/conversations/20235840234

**Comment by sankar2389** [comment]
Added Sourav +

**Comment by sankar2389** [comment]
@Minh from InspireUI <Minh@inspireui.intercom-mail.com> Have you checked
the source code? Can you guide us to integrate RazorPay in expo (CeStore
Mobile version) ?

**Comment by sankar2389** [comment]
@minhcasi Any updates Bro?

**Comment by minhcasi** [comment]
@sankar2389 we are still working on this integration and need more time - thank you!

**Comment by minhcasi** [comment]
fixed on v.1.3 - please download the latest - thanks
