### ISSUE TITLE
[fluxstore] - how to set other payment method / payment webview?

### ISSUE THREAD

**Issue by anakilang99** [inspireui/support#1540]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:

Hi, I want to use other payment method ipay99, its already running on my website. how to integrate it with fluxstore? thanks

2. Screenshots issues:
-

3. Proof of my purchased:
same customer here https://github.com/inspireui/support/issues/1506

3. Config files (optional)

**Comment by minhcasi** [comment]
@anakilang99 - could you try with this guide fro the payment setting - https://docs.inspireui.com/fluxstore/multi-payment/#404-error-page - thank you!
