### ISSUE TITLE
[FluxStore] - Razorpay callbackurl issue

### ISSUE THREAD

**Issue by UTimung** [inspireui/support#1541]
i add razorpay testkey both in woocommerce and in app config.dart

in website its working well
but in fluxstore app, after purchased its opening webview of the callbackurl example.com
instead it should show Thank you order confirm page in the app

purchase code #1485

**Comment by minhcasi** [comment]
@minhtruong315 - pls help for checking

**Comment by minhtruong315** [comment]
@UTimung Can you send me config.dart file and admin account via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/1541

**Comment by UTimung** [comment]
i sent you an email, please check

**Comment by minhtruong315** [comment]
https://gofile.io/?c=zfwtHG
I see it's working well. Can you record screen?

**Comment by UTimung** [comment]
Here is screen recorder video
Please check in real device not emulator
And order id also not showing while payment

Check the difference through Website & app

Video link
https://drive.google.com/file/d/19uHtGbS4eURedtBx-_SF0j20mWyAx03v/view?usp=drivesdk

https://drive.google.com/file/d/1A-ULdEV7e-5JvJffA4skjFTVjBHRx3OE/view?usp=drivesdk

https://drive.google.com/file/d/1A2Dj03Y7nQJl_bDCoi3d-ySNDsYleeG-/view?usp=drivesdk

**Comment by minhtruong315** [comment]
Please replace payment.dart in screens/checkout/payment.dart
[payment.dart.zip](https://github.com/inspireui/support/files/3934356/payment.dart.zip)

**Comment by UTimung** [comment]
after replace i got 3 error

the name parameters currency isn't defined

currency: cartModel.currency),

**Comment by minhtruong315** [comment]
@UTimung I added multi currency to release next version. Can you send me your payment.dart before?

**Comment by UTimung** [comment]
here is my payment.dart

**Comment by minhtruong315** [comment]
I dont see. pls zip and resend it

**Comment by UTimung** [comment]
here is the file in zip

**Comment by minhtruong315** [comment]
how to see it https://tppr.me/jee4T?

**Comment by UTimung** [comment]
Payment.dart in Google drive link

https://drive.google.com/file/d/1AElhnw5KCpQy5-Z-7sgEX9JFHxpTxTI_/view?usp=drivesdk

**Comment by minhtruong315** [comment]
[payment.dart.zip](https://github.com/inspireui/support/files/3934894/payment.dart.zip)
try this

**Comment by UTimung** [comment]
i replace payment.dart again
still same problem

**Comment by UTimung** [comment]
Please fix it as soon as possible

**Comment by minhtruong315** [comment]
@UTimung send me source code via my email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/1541

**Comment by UTimung** [comment]
i sent you the source code please check

**Comment by UTimung** [comment]
Please fix as soon as possible

**Comment by minhtruong315** [comment]
I am checking

**Comment by minhtruong315** [comment]
I checked your source code, it's working well. Can you record screen your issues?

**Comment by UTimung** [comment]
Here is the video
And please check on real device not on emulator

https://drive.google.com/file/d/19uHtGbS4eURedtBx-_SF0j20mWyAx03v/view?usp=drivesdk

**Comment by minhtruong315** [comment]
[index.dart.zip](https://github.com/inspireui/support/files/3942758/index.dart.zip)
Please replace index.dart in widgets/payment/razorpay/index.js to fix this issue

**Comment by UTimung** [comment]
It didn't fix the issue Sir

Its opening example.com

**Comment by minhcasi** [comment]
@UTimung - could you clarify more what mean "opening example.com" - is it happened after the purchased?

@minhtruong315 - pls check to replace the solution by using this official library could be helped - https://razorpay.com/docs/payment-gateway/flutter-integration/ - just my suggestion

Thanks

**Comment by minhtruong315** [comment]
@UTimung can you record screen after replace above file? I checked on your source, it’s working well

**Comment by UTimung** [comment]
After purchased via Razorpay
It shows 2 options
1) Success
2) Failure

I click on SUCCESS and it open "example.com"

**Comment by UTimung** [comment]
After replace of rozorpay/index.dart

Still same problem like above screen recorder video

**Comment by minhtruong315** [comment]
@UTimung i will record screen and let you see

**Comment by UTimung** [comment]
I tested on Android studio AVD manager also
But there also same problem

**Comment by phcaraujo** [comment]
please mercado pago integration!!

**Comment by UTimung** [comment]
Please fix, through TeamViewer

**Comment by minhtruong315** [comment]
Please replace index.dart in widgets/payment/razorpay/index.js
[index.dart.zip](https://github.com/inspireui/support/files/3949082/index.dart.zip)

it's working on my phone
https://gofile.io/?c=VGtAri

**Comment by UTimung** [comment]
The above file fix the issue
Now next problem is, on woocommerce , its showing PENDING PAYMENT, after
purchased via Razorpay

**Comment by minhtruong315** [comment]
https://tppr.me/sQs1q
change this to true

**Comment by UTimung** [comment]
So Razorpay test key only accept

 4111 1111 1111 1111 credit debit card
Not real card number ? Why?

Or real card wil work only on live key of Razorpay

**Comment by minhtruong315** [comment]
yes. you must change live key to test real card

**Comment by UTimung** [comment]
I changed paid=true
Still showing pending payment

**Comment by UTimung** [comment]
Did you check

**Comment by minhtruong315** [comment]
change createOrder function in screens/checkout/payment.dart like this
```
void createOrder({paid = false}) async {
    final LocalStorage storage = new LocalStorage('data_order');
    var listOrder = [];
    bool isLoggedIn = Provider.of<UserModel>(context).loggedIn;

    widget.onLoading(true);
    final cartModel = Provider.of<CartModel>(context);
    final userModel = Provider.of<UserModel>(context);
    try {
      final order = await Services()
          .createOrder(cartModel: cartModel, user: userModel, paid: paid);
      widget.onLoading(false);
      if (!isLoggedIn) {
        var items = storage.getItem('orders');
        if (items != null) {
          listOrder = items;
        }
        listOrder.add(order.toOrderJson(cartModel, null));
        storage.setItem('orders', listOrder);
      }
      widget.onFinish(order);
    } catch (err) {
      widget.onLoading(false);

      final snackBar = SnackBar(
        content: Text(err.toString()),
      );
      Scaffold.of(context).showSnackBar(snackBar);
    }
  }
```

**Comment by UTimung** [comment]
Helo
Now ok order status is processing

But after purchased
I click on FAILURE
And it shows order successful
I think it should say order fail

**Comment by UTimung** [comment]
And i change Razorpay test key to live key

After purchased
It goes back to checkout payment page
And the amount are deducted from my real card,
I can see the amount in Razorpay website also

But in woocommerce order are not receive

**Comment by minhcasi** [comment]
@minhtruong315 - please help for updating with this issue - thank you!

**Comment by minhtruong315** [comment]
@UTimung can u record screen? I don't understand your issues

**Comment by UTimung** [comment]
I replaced Razorpay test key to LIVE key

Now whenever i purchased through Razorpay (LIVE KEY)
The order are not showing in woocommerce

But transaction amount are showing in Razorpay website dashboard

**Comment by minhtruong315** [comment]
@UTimung Are the order showing in woo commerce for debug key?

**Comment by UTimung** [comment]
Yes order are showing in woocommerce  with TEST KEY

But not with LIVE KEY

**Comment by minhtruong315** [comment]
Please install this lib https://pub.dev/packages/razorpay_flutter#-installing-tab-
then replace screens/checkout/payment.dart file like this
[payment.dart.zip](https://github.com/inspireui/support/files/3981027/payment.dart.zip)

**Comment by UTimung** [comment]
after replaced above payment.dart
it shows 6 error
like paymentfailurerespone undefine etc

**Comment by minhtruong315** [comment]
did you install this lib  https://pub.dev/packages/razorpay_flutter#-installing-tab-
I see it's working
![Simulator Screen Shot - iPhone 11 - 2019-12-21 at 10 12 43](https://user-images.githubusercontent.com/10402500/71302180-cac56c00-23da-11ea-96e3-006be3f63e5c.png)

**Comment by UTimung** [comment]
I don't know how to install the lib
The instructions in the website are not for beginner

**Comment by minhtruong315** [comment]
https://tppr.me/ch3ci

**Comment by UTimung** [comment]
Thank you
now LIVE KEY working
but order status showing COMPLETED
it should be processing

**Comment by minhtruong315** [comment]
@UTimung You can remove this line ```if (paid) params["status"] = "completed";``` in models/order.dart
line about 175

**Comment by UTimung** [comment]
Now ok

And can you hide Shipping formula [qty]x50

I want to show actual amount
https://drive.google.com/file/d/1EQTrAoXhkj77e97ICXcBt1bE2GWksqx1/view?usp=drivesdk
