### ISSUE TITLE
[Fluxstore] No such file or directory after uploading the latest package to wordpress website

### ISSUE THREAD

**Issue by Coinizy1** [inspireui/support#1542]
Warning: include_once(/homepages/40/d778442569/htdocs/clickandbuilds/UsdVault/wp-content/plugins/mstore-api/controllers/MStoreDokan.php): failed to open stream: No such file or directory in /homepages/40/d778442569/htdocs/clickandbuilds/UsdVault/wp-content/plugins/mstore-api/mstore-api.php on line 49

Warning: include_once(): Failed opening '/homepages/40/d778442569/htdocs/clickandbuilds/UsdVault/wp-content/plugins/mstore-api/controllers/MStoreDokan.php' for inclusion (include_path='.:/usr/lib/php7.3') in /homepages/40/d778442569/htdocs/clickandbuilds/UsdVault/wp-content/plugins/mstore-api/mstore-api.php on line 49

My php 7.3

**Comment by Coinizy1** [comment]
*** UPDATE ***** 
the wordpress folder i uploaded was from my zip file which i got after purchasing the Fluxtore.
i copied the code and made a new file from this url
https://github.com/inspireui/mstore-api/blob/master/mstore-api.php
is it correct what i did or not?

**Comment by Coinizy1** [comment]
and do i have this file?
Thank you for choosing InspireUI products.

This setting help to speed up the mobile app performance (only available for Fluxstore), upload the config.json from the common folder:

i bought this package:
https://codecanyon.net/item/fluxstore-woocommerce-flutter-ecommerce-full-app/24050041

**Comment by minhcasi** [comment]
@Coinizy1 - could you help to download directly the latest version from this plugin URL - https://wordpress.org/plugins/mstore-api/

**Comment by minhcasi** [comment]
Let us know if you still have the issue - thank you!

**Comment by Coinizy1** [comment]
now i am getting an other error in your previous update "1.5.9" there was a extension called json api which doesnt have file called "mstore-api.php"
but now on latest update "1.5.9b" there is a file "mstore-api.php" in json-api folder now that file is conflicting with the mstore api plugin and only one plugin can be used like i am seeing two mstore api plugins in my plugins folder and one of them is active (which i downloaded from github) and the other one is deactivated once i activate it it automatically deactivates the json api too.
can you please send me links of all 4 plugins for wordpress?
Thanks
