### ISSUE TITLE
[Fluxstore Woocommerce] - Getting Check out Error

### ISSUE THREAD

**Issue by Riorich** [inspireui/support#1545]
---------

1. My issue:

I got this error when I proceed to check out and cannot proceed.
I/flutter ( 5744): Another exception was thrown: Failed assertion: boolean expression must not be null

2. Screenshots issues:
![Screenshot_1575620005](https://user-images.githubusercontent.com/39195214/70313177-7dc29100-1843-11ea-841c-2f9fe41d2e7e.png)

3. Proof of my purchased:
![2019-11-23 (2)](https://user-images.githubusercontent.com/39195214/70313261-a6e32180-1843-11ea-9b3d-dffba078e4c0.png)

3. Config files (optional)

**Comment by minhcasi** [comment]
@Riorich - could you help to share the config file (common/config.dart and config.json) so that we could help for checking the issues - thank you!

**Comment by Riorich** [comment]
please kindly help to check my config.dart and config.json.
[common.zip](https://github.com/inspireui/support/files/3935205/common.zip)

**Comment by minhcasi** [comment]
@minhtruong315 - pls help for suggestion on this issue - thank you!

**Comment by minhtruong315** [comment]
@Riorich can you send me admin account via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/1545

**Comment by Riorich** [comment]
@minhtruong315 Just sent. Look forward your assistance. Thanks.

**Comment by minhtruong315** [comment]
@Riorich I checked your config. It's working on my source code. can you record screen? I wanna see your issues

**Comment by Riorich** [comment]
@minhtruong315 now I can solve it by adding boolean expression in Config.dart file. Many thanks for your assistance.
