### ISSUE TITLE
[BeoNews] - Help with installing Beonews. "The rest API is not working correctly!"

### ISSUE THREAD

**Issue by dermayank** [inspireui/support#1547]
I recently purchased the BeoNews from the Envato market. When I proceeded with the installation and followed the steps as mentioned in the documentation, I am facing an error named "The rest API is not working correctly!". I have installed all the plugins as mentioned in the documentation. 

I already raised a GitHub issue but nobody responded to me there. Please provide some solution ASAP as this issue hindering our production.

I have attached the error and purchase proof as to the screenshot below.

Purchase Proof:
![Screenshot from 2019-12-04 10-30-36](https://user-images.githubusercontent.com/24271097/70367093-ddac4c80-18c2-11ea-8758-31a4387577dc.png)

The error I'm facing
![Screenshot from 2019-12-04 10-49-05](https://user-images.githubusercontent.com/24271097/70367094-ddac4c80-18c2-11ea-810d-94279707fde5.png)

All plugins are installed as mentioned on the docummentation.
![Screenshot from 2019-12-07 07-15-15](https://user-images.githubusercontent.com/24271097/70367095-de44e300-18c2-11ea-9f48-3f189b5cfca8.png)
![Screenshot from 2019-12-07 07-15-22](https://user-images.githubusercontent.com/24271097/70367096-de44e300-18c2-11ea-8431-2a6a9f3f0020.png)

**Comment by minhcasi** [comment]
@dermayank  - please help to check your Wordpress API as could be some restrict plugins that cause the API could not accessible 
https://triprethink.com/wp-json/wp/v2/posts

It would have the result like - http://news.inspireui.com/wp-json/wp/v2/posts
