### ISSUE TITLE
Mstore Pro 

### ISSUE THREAD

**Issue by vaibhavaparashar** [inspireui/support#1549]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: I am setup your mstore pro app through Cebuilder but after running script powershell failed to build.. i didnt understood what is the means of error.. please check it out and let me know how to resolve this error.

2. issue screenshot or error code
`Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

Remove-Item : A parameter cannot be found that matches parameter name 'rf'.
At G:\THEME FOREST\CODECANYON\Android App
Maker\mstore-3.9.6\mstore-pro\scripts\cebuilder.ps1:2 char:4
+ rm -rf node_modules/
+    ~~~
    + CategoryInfo          : InvalidArgument: (:) [Remove-Item], ParameterBin
   dingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Comm
   ands.RemoveItemCommand

> postinstall-postinstall@2.0.0 postinstall G:\THEME FOREST\CODECANYON\Android A
pp Maker\mstore-3.9.6\mstore-pro\node_modules\postinstall-postinstall
> node ./run.js

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.yarnpkg.com/jetify - Not found
npm ERR! 404
npm ERR! 404  'jetify@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HP\AppData\Roaming\npm-cache\_logs\2019-12-07T06_51_51_637
Z-debug.log
Install for [ 'jetify@latest' ] failed with code 1
error Command failed with exit code 1.
child_process.js:642
    throw err;
    ^

Error: Command failed: yarn run postinstall
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.yarnpkg.com/jetify - Not found
npm ERR! 404
npm ERR! 404  'jetify@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HP\AppData\Roaming\npm-cache\_logs\2019-12-07T06_51_51_637
Z-debug.log
Install for [ 'jetify@latest' ] failed with code 1
error Command failed with exit code 1.

←[90m    at checkExecSyncError (child_process.js:603:11)←[39m
←[90m    at execSync (child_process.js:639:15)←[39m
    at Object.<anonymous> (G:\THEME FOREST\CODECANYON\Android App Maker\mstore-3
.9.6\mstore-pro\node_modules\←[4mpostinstall-postinstall←[24m\run.js:14:5)
←[90m    at Module._compile (internal/modules/cjs/loader.js:971:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1011:1
0)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:822:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:730:14)←[39m
←[90m    at Function.Module.runMain (internal/modules/cjs/loader.js:1051:12)←[39
m
←[90m    at internal/main/run_main_module.js:16:11←[39m {
  status: ←[33m1←[39m,
  signal: ←[1mnull←[22m,
  output: [
    ←[1mnull←[22m,
    <Buffer 79 61 72 6e 20 72 75 6e 20 76 31 2e 31 39 2e 32 0a 24 20 70 61 74 63
 68 2d 70 61 63 6b 61 67 65 20 26 26 20 6e 70 78 20 6a 65 74 69 66 79 0a 70 61 7
4 ... 151 more bytes>,
    <Buffer 6e 70 6d 20 45 52 52 21 20 63 6f 64 65 20 45 34 30 34 0a 6e 70 6d 20
 45 52 52 21 20 34 30 34 20 4e 6f 74 20 46 6f 75 6e 64 20 2d 20 47 45 54 20 68 7
4 ... 552 more bytes>
  ],
  pid: ←[33m6124←[39m,
  stdout: <Buffer 79 61 72 6e 20 72 75 6e 20 76 31 2e 31 39 2e 32 0a 24 20 70 61
 74 63 68 2d 70 61 63 6b 61 67 65 20 26 26 20 6e 70 78 20 6a 65 74 69 66 79 0a 7
0 61 74 ... 151 more bytes>,
  stderr: <Buffer 6e 70 6d 20 45 52 52 21 20 63 6f 64 65 20 45 34 30 34 0a 6e 70
 6d 20 45 52 52 21 20 34 30 34 20 4e 6f 74 20 46 6f 75 6e 64 20 2d 20 47 45 54 2
0 68 74 ... 552 more bytes>
}
npm WARN enoent ENOENT: no such file or directory, open 'G:\THEME FOREST\CODECAN
YON\Android App Maker\mstore-3.9.6\mstore-pro\node_modules\@babel\plugin-syntax-
optional-catch-binding\node_modules\@babel\core\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'G:\THEME FOREST\CODECAN
YON\Android App Maker\mstore-3.9.6\mstore-pro\node_modules\@babel\plugin-syntax-
typescript\node_modules\@babel\core\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'G:\THEME FOREST\CODECAN
YON\Android App Maker\mstore-3.9.6\mstore-pro\node_modules\@babel\plugin-syntax-
nullish-coalescing-operator\node_modules\@babel\core\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'G:\THEME FOREST\CODECAN
YON\Android App Maker\mstore-3.9.6\mstore-pro\node_modules\@babel\plugin-syntax-
jsx\node_modules\@babel\core\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'G:\THEME FOREST\CODECAN
YON\Android App Maker\mstore-3.9.6\mstore-pro\node_modules\@babel\plugin-syntax-
optional-chaining\node_modules\@babel\core\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'G:\THEME FOREST\CODECAN
YON\Android App Maker\mstore-3.9.6\mstore-pro\node_modules\os-locale\node_module
s\cross-spawn\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'G:\THEME FOREST\CODECAN
YON\Android App Maker\mstore-3.9.6\mstore-pro\node_modules\protobufjs\node_modul
es\yargs\package.json'
npm WARN @typescript-eslint/eslint-plugin@1.13.0 requires a peer of eslint@^5.0.
0 but none is installed. You must install peer dependencies yourself.
npm WARN @typescript-eslint/parser@1.13.0 requires a peer of eslint@^5.0.0 but n
one is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-react@7.12.4 requires a peer of eslint@^3.0.0 || ^4.0.0 |
| ^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-react-native@3.6.0 requires a peer of eslint@^3.17.0 || ^
4 || ^5 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-localization@2.1.6 requires a peer of react-native@^0.41.2
 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-localization@2.1.6 requires a peer of react-native-windows
@0.41.0-rc.1 but none is installed. You must install peer dependencies yourself.

npm WARN react-native-webview@6.11.1 requires a peer of react-native@>=0.57 <0.6
0 but none is installed. You must install peer dependencies yourself.
npm WARN styled-components@4.4.1 requires a peer of react-dom@>= 16.3.0 but none
 is installed. You must install peer dependencies yourself.
npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev ||
 >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta |
| >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dep
endencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! postinstall-postinstall@2.0.0 postinstall: `node ./run.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the postinstall-postinstall@2.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HP\AppData\Roaming\npm-cache\_logs\2019-12-07T06_52_32_132
Z-debug.log

> Configure project :@react-native-community_async-storage
Observed package id 'system-images;android-28;google_apis;x86' in inconsistent l
ocation 'C:\Users\HP\AppData\Local\Android\Sdk\.temp\PackageOperation02' (Expect
ed 'C:\Users\HP\AppData\Local\Android\Sdk\system-images\android-28\google_apis\x
86')
Observed package id 'extras;intel;Hardware_Accelerated_Execution_Manager' in inc
onsistent location 'C:\Users\HP\AppData\Local\Android\Sdk\.temp\PackageOperation
04' (Expected 'C:\Users\HP\AppData\Local\Android\Sdk\extras\intel\Hardware_Accel
erated_Execution_Manager')

> Configure project :react-native-admob
WARNING: Configuration 'compile' is obsolete and has been replaced with 'impleme
ntation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.androi
d.com/r/tools/update-dependency-configurations.html

> Configure project :react-native-webview
:react-native-webview:reactNativeAndroidRoot G:\THEME FOREST\CODECANYON\Android
App Maker\mstore-3.9.6\mstore-pro\node_modules\react-native\android

BUILD SUCCESSFUL in 10m 27s
13 actionable tasks: 13 executed
warn Package postinstall-postinstall has been ignored because it contains invali
d configuration. Reason: Cannot find module 'postinstall-postinstall\package.jso
n'
Require stack:
- G:\THEME FOREST\CODECANYON\Android App Maker\mstore-3.9.6\mstore-pro\node_modu
les\react-native\node_modules\@react-native-community\cli\build\tools\config\res
olveNodeModuleDir.js
- G:\THEME FOREST\CODECANYON\Android App Maker\mstore-3.9.6\mstore-pro\node_modu
les\react-native\node_modules\@react-native-community\cli\build\tools\releaseChe
cker\index.js
- G:\THEME FOREST\CODECANYON\Android App Maker\mstore-3.9.6\mstore-pro\node_modu
les\react-native\node_modules\@react-native-community\cli\build\commands\server\
runServer.js
- G:\THEME FOREST\CODECANYON\Android App Maker\mstore-3.9.6\mstore-pro\node_modu
les\react-native\node_modules\@react-native-community\cli\build\commands\server\
server.js
- G:\THEME FOREST\CODECANYON\Android App Maker\mstore-3.9.6\mstore-pro\node_modu
les\react-native\node_modules\@react-native-community\cli\build\commands\index.j
s
- G:\THEME FOREST\CODECANYON\Android App Maker\mstore-3.9.6\mstore-pro\node_modu
les\react-native\node_modules\@react-native-community\cli\build\cliEntry.js
- G:\THEME FOREST\CODECANYON\Android App Maker\mstore-3.9.6\mstore-pro\node_modu
les\react-native\node_modules\@react-native-community\cli\build\index.js
- G:\THEME FOREST\CODECANYON\Android App Maker\mstore-3.9.6\mstore-pro\node_modu
les\react-native\cli.js
- C:\Users\HP\AppData\Roaming\npm\node_modules\react-native-cli\index.js
info Running jetifier to migrate libraries to AndroidX. You can disable it using
 "--no-jetifier" flag.
Jetifier found 1055 file(s) to forward-jetify. Using 4 workers...
info Starting JS server...
info Installing the app...

> Configure project :@react-native-community_async-storage
Observed package id 'system-images;android-28;google_apis;x86' in inconsistent l
ocation 'C:\Users\HP\AppData\Local\Android\Sdk\.temp\PackageOperation02' (Expect
ed 'C:\Users\HP\AppData\Local\Android\Sdk\system-images\android-28\google_apis\x
86')
Observed package id 'extras;intel;Hardware_Accelerated_Execution_Manager' in inc
onsistent location 'C:\Users\HP\AppData\Local\Android\Sdk\.temp\PackageOperation
04' (Expected 'C:\Users\HP\AppData\Local\Android\Sdk\extras\intel\Hardware_Accel
erated_Execution_Manager')

> Configure project :react-native-admob
WARNING: Configuration 'compile' is obsolete and has been replaced with 'impleme
ntation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.androi
d.com/r/tools/update-dependency-configurations.html

> Configure project :react-native-webview
:react-native-webview:reactNativeAndroidRoot G:\THEME FOREST\CODECANYON\Android
App Maker\mstore-3.9.6\mstore-pro\node_modules\react-native\android

> Task :react-native-onesignal:bundleLibResDebug FAILED

Deprecated Gradle features were used in this build, making it incompatible with
Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:comm
and_line_warnings
233 actionable tasks: 4 executed, 229 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-onesignal:bundleLibResDebug'.
> 1 exception was raised by workers:
  java.nio.file.AccessDeniedException: G:\THEME FOREST\CODECANYON\Android App Ma
ker\mstore-3.9.6\mstore-pro\node_modules\react-native-onesignal\android\build\in
termediates\library_java_res\debug\res.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4m 48s

error Failed to install the app. Make sure you have the Android development envi
ronment set up: https://facebook.github.io/react-native/docs/getting-started.htm
l#android-development-environment. Run CLI with --verbose flag for more details.

Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8
081

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-onesignal:bundleLibResDebug'.
> 1 exception was raised by workers:
  java.nio.file.AccessDeniedException: G:\THEME FOREST\CODECANYON\Android App Ma
ker\mstore-3.9.6\mstore-pro\node_modules\react-native-onesignal\android\build\in
termediates\library_java_res\debug\res.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4m 48s

    at checkExecSyncError (child_process.js:603:11)
    at execFileSync (child_process.js:621:15)
    at runOnAllDevices (G:\THEME FOREST\CODECANYON\Android App Maker\mstore-3.9.
6\mstore-pro\node_modules\@react-native-community\cli-platform-android\build\com
mands\runAndroid\runOnAllDevices.js:74:39)
    at buildAndRun (G:\THEME FOREST\CODECANYON\Android App Maker\mstore-3.9.6\ms
tore-pro\node_modules\@react-native-community\cli-platform-android\build\command
s\runAndroid\index.js:158:41)
    at G:\THEME FOREST\CODECANYON\Android App Maker\mstore-3.9.6\mstore-pro\node
_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\
index.js:125:12
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Command.handleAction (G:\THEME FOREST\CODECANYON\Android App Maker\
mstore-3.9.6\mstore-pro\node_modules\react-native\node_modules\@react-native-com
munity\cli\build\cliEntry.js:160:7)
PS G:\THEME FOREST\CODECANYON\Android App Maker\mstore-3.9.6\mstore-pro>
`
![1](https://user-images.githubusercontent.com/6870646/70371888-af4c6280-18fe-11ea-9ab0-20c7d0279bf4.jpg)
![2](https://user-images.githubusercontent.com/6870646/70371889-afe4f900-18fe-11ea-9f65-a9f6a63db9c0.png)
![3](https://user-images.githubusercontent.com/6870646/70371890-afe4f900-18fe-11ea-8bfa-38eb7050019e.jpg)
![4](https://user-images.githubusercontent.com/6870646/70371892-b07d8f80-18fe-11ea-8b81-6857667d033b.jpg)
![5](https://user-images.githubusercontent.com/6870646/70371893-b07d8f80-18fe-11ea-81b8-e14515a4757b.jpg)

3. Proof of my purchased: 

screenshot:
![purchase screenshot](https://user-images.githubusercontent.com/6870646/70371938-2e419b00-18ff-11ea-8fac-761b46fda70e.jpg)

purchase item code: 011a05cf-cfa5-4395-97b8-3fb4773526e5

3. Config files (optional)

**Comment by minhtruong315** [comment]
@vaibhavaparashar add my skype: minhtruong315
i will help you check via teamviewer

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
