### ISSUE TITLE
[MStore PRO & Expo] Product Variations Not Working At All

### ISSUE THREAD

**Issue by levi-beers** [inspireui/support#155]
In the last few versions of Mstore (3.6.4, 3.6.5 & 3.6.6 -- the latest uploaded 27-Dec), product variations do not show up in cart after you add a product or in the WooCommerce order. You can replicate this issue on the MStore demo app. Try to purchase a "Medium - Short Sleeve Shirt Dress". The size doesn't show up in cart or on the order page -- it used to. 

This is a huge core feature of WooCommerce and I've had to take my app off the app store because of the issue, when will this be resolved?

**Comment by minhcasi** [comment]
marked as bug for the fixing - thanks @levi-beers

**Comment by theleolife** [comment]
Hi @minhcasi I have the same bug on Cestore App MStore last app version, users can choose variation on product screen but variations are not being controlling by stock available or even this doesn't show up in cart or on the order page as @levi-beers  already said, even in my admin cezering backend variations doesn't show up on the orders details.

**Comment by luyx2412** [comment]
Planned with new version. Thanks for your feedbacks.
