### ISSUE TITLE
[BeoNews] - Welcome Screen and Dark Mode

### ISSUE THREAD

**Issue by TheCellMC** [inspireui/support#1550]
### My issue

So I'm running into multiple issues with the latest version of BeoNews PRO.

1. Onboarding does not work, I never get the welcome screen when running the app for the first time. Additionally, when building the app as release in Xcode, I get this error:
```
Undefined symbols for architecture arm64:
  "_RCTSetLogFunction", referenced from:
      -[beonewsTests testRendersWelcomeScreen] in beonewsTests.o
ld: symbol(s) not found for architecture arm64
```
I think that might be related. This issue is also present on your BeoFoods app published in the AppStore.

2. Secondly, would it be possible to add support for Dark Mode in BeoNews pro? This would be an amazing feature to have.

**Comment by minhcasi** [comment]
@TheCellMC - thank you for reporting the onboarding issue, it could be some recent update that causes the issue - i will work with the team and keep an update

Also check the dark mode solution as well - very best!

**Comment by concuacon** [comment]
@TheCellMC you can follow this link to fix issue release with Xcode 
https://stackoverflow.com/a/52541765/5295046

**Comment by TheCellMC** [comment]
Thank you @concuacon, I have already bypassed this issue by disabling "Dead Code Stripping", however that is only a workaround and not an actual solution to the problem:

Why is onboarding not working? 

Please could you have a look into this issue. I would really like to have the onboarding screen function, but it does not in the latest release.

**Comment by minhcasi** [comment]
@concuacon ?

**Comment by minhcasi** [comment]
@TheCellMC - we will check the onboarding issue and upgrade on next release - thank you!

**Comment by luyx2412** [comment]
Fixed on next release!
