### ISSUE TITLE
M-store expo-build android app not working

### ISSUE THREAD

**Issue by Jenarath** [inspireui/support#1551]
M-store expo-build android .apk app not working
 
Success finish run on console  "build expo:android"
but when install .apk  on android real device app stuck and not working. run on simulator is working
I need to build android file .apk publish to play store. help me please ! thank you so much
<img width="419" alt="Screen Shot 2562-12-07 at 21 31 51" src="https://user-images.githubusercontent.com/25680869/70376221-34546d80-1939-11ea-9f6d-8ecc43795746.png">
<img width="251" alt="Screen Shot 2562-12-07 at 21 35 52" src="https://user-images.githubusercontent.com/25680869/70376245-71206480-1939-11ea-8f5e-bc9386faccec.png">

----------------------------------------
Proof of  my purchase

Purchase code: 806daf5e-4fd0-4820-9f58-a6cd11e95ce7

<img width="528" alt="Screen Shot 2562-12-07 at 21 29 25" src="https://user-images.githubusercontent.com/25680869/70376274-c2305880-1939-11ea-903d-62873d338585.png">

--------------------
Config file

App.js  app.json  package.json
[config.zip](https://github.com/inspireui/support/files/3935159/config.zip)

**Comment by Jenarath** [comment]
Proof of  my purchase

Purchase code: 806daf5e-4fd0-4820-9f58-a6cd11e95ce7

<img width="528" alt="Screen Shot 2562-12-07 at 21 29 25" src="https://user-images.githubusercontent.com/25680869/70376274-c2305880-1939-11ea-903d-62873d338585.png">

**Comment by Jenarath** [comment]
Config file

App.js  app.json  package.json
[config.zip](https://github.com/inspireui/support/files/3935159/config.zip)

**Comment by Jenarath** [comment]
I try build M-Store expo your app not working same but can run on simulator

![689](https://user-images.githubusercontent.com/25680869/70377171-c792a080-1943-11ea-8765-ffe0722188c8.jpg)

**Comment by minhcasi** [comment]
@Jenarath - noted with checking with the team

@concuacon - could you give some suggestion to fix this issue - thank you!

**Comment by concuacon** [comment]
@Jenarath You can try:
npm install -g expo-cli
rmdir -rf node_modules/ 
npm install
expo start -c

**Comment by Jenarath** [comment]
@concuacon 
I try it. run on simulator working but can't run file .apk

**Comment by Jenarath** [comment]
@concuacon
I try it again ! So cool ;) 
can rum file .apk on android device 
thank you so much 

![S__21372930](https://user-images.githubusercontent.com/25680869/70557228-f19ec980-1bb4-11ea-9508-67989fe58978.jpg)

**Comment by concuacon** [comment]
Hi, @Jenarath we're glad that it help, please give us some feedback/rating to this page https://codecanyon.net/downloads if the product is helpful for your business, we are working hard to update more awesome and powerful features on next coming version release. Let us know if you have any feedback. Thank you very much! :blush:
