### ISSUE TITLE
[Flux Store Multi Vendors - v1.2 ] - [Bug] Error with Vertical Layout

### ISSUE THREAD

**Issue by HassanChmsdn** [inspireui/support#1552]
**BUG IN FLUXSTORE V1.2**
**Error**
After updating FluxStore MultiVendors from 1.1 to  1.2, I tried to Edit the **config.json** file to include Vertical Layout:
<img width="850" alt="Screenshot 2019-12-07 at 17 25 27" src="https://user-images.githubusercontent.com/921709/70377611-a8c9e500-1916-11ea-8803-8c4ddb40c5dc.png">

and this have thrown an Error after restarting the Application in the Home page as follows:
<img width="413" alt="Screenshot 2019-12-07 at 17 27 44" src="https://user-images.githubusercontent.com/921709/70377636-e9c1f980-1916-11ea-8b05-859335583360.png">

**Solution**
After debugging and checking the differences between the previous version and this one, I found that there is a variable which is removed by mistake from the **vertical.dart** file and I have fixed my error by adding the following:
<img width="724" alt="Screenshot 2019-12-07 at 17 31 04" src="https://user-images.githubusercontent.com/921709/70377674-5e953380-1917-11ea-81c9-caaf70d13299.png">

**Please consider this solution in the next release!** @minhcasi

**Comment by incepio-flutter** [comment]
I have same error 
<img width="376" alt="Screenshot 2019-12-08 at 12 23 54 AM" src="https://user-images.githubusercontent.com/57838430/70380297-848ff780-195a-11ea-8521-bdc3a0bffb6e.png">

**Comment by HassanChmsdn** [comment]
@incepio-flutter as I mentioned in my issue if the error is because of your usage of vertical layout in the config.json file.. you should follow my solution, as it really works for me, and I think it is a **bug** in v1.2 of fluxstore, @minhcasi !
<img width="724" alt="Screenshot 2019-12-07 at 17 31 04" src="https://user-images.githubusercontent.com/921709/70382011-185ec500-1955-11ea-8fb3-66aef3bb8bf2.png">

**Comment by incepio-flutter** [comment]
@HassanChmsdn  thank you so much !

**Comment by HassanChmsdn** [comment]
> @HassanChmsdn thank you so much!

It might also happen in other files with the same missing variable, just track it to check where to it exactly, because I have also faced it when using **product_list_layout.dart** file as well!

**Comment by HassanChmsdn** [comment]
@minhcasi I have requested for the gitlab code of fluxstore project, I hope you can give me access to fork the project and fix this issue!

**Comment by minhcasi** [comment]
@HassanChmsdn - please also note that there is some an important update from the config.json file "config.json file to support multi-languages (config_xx.json)" - we have break the previous config to multi-files support for each language, the new "name" should be a text, instead of an Object - pls try to update the config and let me know.

The team is checking the Gitlab request for every 2-3 days and will update you soon

**Comment by HassanChmsdn** [comment]
> @HassanChmsdn - please also note that there is some an important update from the config.json file "config.json file to support multi-languages (config_xx.json)" - we have break the previous config to multi-files support for each language, the new "name" should be a text, instead of an Object - pls try to update the config and let me know.
> 
> The team is checking the Gitlab request for every 2-3 days and will update you soon

Yes That true, I have also noticed that as well, we need to change the name of "**config.json**" into **config_en.json** beside the other config_xx.json files for supporting multi-languages

**Comment by minhcasi** [comment]
@HassanChmsdn - no - you can use the config.json for the default language 

Let us know if you have any further issue - thank you!

**Comment by HassanChmsdn** [comment]
> @HassanChmsdn - no - you can use the config.json for the default language
> 
> Let us know if you have any further issue - thank you!

No thanks, that's all, the issue with the vertical layout was fixed by adding the variable in the file, as well as for the product_list_layout file, as mentioned above. 
I think it should be labeled as a bug too also in this version of fluxstore.

**Comment by minhcasi** [comment]
Yes sure, we are working on new update with the latest Flutter and will update shortly - thank you!
