### ISSUE TITLE
Creating an account

### ISSUE THREAD

**Issue by samik9** [inspireui/support#1553]
Hello, when creating a account is not possible due this error  
![SM G950F 2019-12-07 17-39-47](https://user-images.githubusercontent.com/50071744/70381472-c435ef80-1918-11ea-989a-50031227a4dc.jpg)

**Comment by incepio-flutter** [comment]
Install json api, dokan lite, JWT,mstore api . 
https://github.com/inspireui/support/issues/1478 follow this issue it will help you

**Comment by minhtruong315** [comment]
@incepio-flutter can you send me config.dart file?

**Comment by samik9** [comment]
Hello this is my  config.dart https://d.pr/f/LjSZsB 

Also even i have an account already i says wrong username or password, but everything is correct

**Comment by minhtruong315** [comment]
@samik9 i checked your config. it's working on my source code. Can you send me your source code via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/1553

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
