### ISSUE TITLE
Fluxstore theme error and stripe(again) issue

### ISSUE THREAD

**Issue by Arman20022010** [inspireui/support#1554]
Hi
see these error in my flux store app and you told me that stripe will be fixed in 1.5.9 but it is not fixed 
<img width="435" alt="fddddd" src="https://user-images.githubusercontent.com/36129818/70385153-d9f0f680-19a4-11ea-801e-209b4a7073a8.png">

**Comment by minhcasi** [comment]
@Arman20022010 - could i know what is the stripe issue that you are mention about? Thanks

@minhtruong315 - this could be about the theme config .json - pls link the solution on previous ticket

**Comment by minhtruong315** [comment]
[example.zip](https://github.com/inspireui/support/files/3937833/example.zip)
You can try this example to fix your issue.

**Comment by Arman20022010** [comment]
Hi
I have problem with stripe its just loading nothing else here is main.dart
[config.dart.zip](https://github.com/inspireui/support/files/3967287/config.dart.zip)

**Comment by Arman20022010** [comment]
config.dart*

**Comment by minhcasi** [comment]
Hi @Arman20022010 - could you have a check if you have installed the mstore-api plugin - https://docs.inspireui.com/fluxstore/multi-payment/

**Comment by Arman20022010** [comment]
I check I have it

**Comment by Arman20022010** [comment]
checked*

**Comment by minhtruong315** [comment]
@Arman20022010 Hi, could you help to share the admin access via email: truong@inspireui.com with subject: https://github.com/inspireui/support/issues/1554. so that we could check the website/plugin config that cause the integration issues - thank you

**Comment by Arman20022010** [comment]
Done

**Comment by Arman20022010** [comment]
can I use PayPal Checkout in App ? if yes do I need to add something else beside then ClientID and secret

**Comment by Arman20022010** [comment]
and please can I add PayPal Checkout in app ?

**Comment by Arman20022010** [comment]
please can you tell me how to fix this error
![Simulator Screen Shot - iPhone Xs - 2019-12-20 at 00 15 14](https://user-images.githubusercontent.com/36129818/71206455-028ac180-22be-11ea-8aac-840e80ac4510.png)

**Comment by minhcasi** [comment]
@Arman20022010  - this could be related to the product data that not compatible with latest version update - @minhtruong315 - pls help for checking

**Comment by minhtruong315** [comment]
@Arman20022010 please replace screens/detail/product_title.dart file like this
[product_title.dart.zip](https://github.com/inspireui/support/files/3991007/product_title.dart.zip)

**Comment by Arman20022010** [comment]
And have you checked the Stripe issue ?
And Can I use PayPal Checkout in App ?
I send you details by email to login to website

**Comment by minhtruong315** [comment]
[config.dart.zip](https://github.com/inspireui/support/files/3991128/config.dart.zip)
I used this config. It's working with stripe and paypal
![Simulator Screen Shot - iPhone 11 - 2019-12-21 at 13 22 36](https://user-images.githubusercontent.com/10402500/71304244-bd1ddf80-23f6-11ea-9d7a-9b8a69e6235f.png)
![Simulator Screen Shot - iPhone 11 - 2019-12-21 at 13 34 23](https://user-images.githubusercontent.com/10402500/71304245-bd1ddf80-23f6-11ea-9164-66131574ab55.png)

**Comment by Arman20022010** [comment]
I don't really understand why it is not working in my app 😔

**Comment by Arman20022010** [comment]
please I am sending you my app all files please can you check it 🙏🏻
I think its problem in my app 😔
https://drive.google.com/file/d/1A-ShVI16TvLk4PV_QA09D1sRRn_XHkkD/view?usp=sharing

**Comment by minhcasi** [comment]
@Arman20022010 - pls dont share the whold source here - thank you!

**Comment by Arman20022010** [comment]
ok I am sending to your mail I will add ticket number

**Comment by Arman20022010** [comment]
email*

**Comment by Arman20022010** [comment]
I got FluxStore Pro version it has same problem

**Comment by Arman20022010** [comment]
let me send you my pro version source code to your email
I send you yesterday Basic version but now I am sending you Pro version

**Comment by minhtruong315** [comment]
@Arman20022010 did you use my config? 
You need to follow this guide to generate API keys correctly
https://docs.inspireui.com/fluxstore/woocommerce-setup/

**Comment by Arman20022010** [comment]
Oh I have fixed that
Thank you:)
