### ISSUE TITLE
[Fluxstore Pro] - Category list icons not showing as designed

### ISSUE THREAD

**Issue by Alnaggar94** [inspireui/support#1555]
1. My issue:

I designed icons for the category list using photoshop but when they show in the app it shows different? I want to display it as it designed normal .png not with widget customization, how can I do that?

2. Screenshots issues:

The icon I  designed  - https://imgur.com/a/1WpTxqP
The icon in the app - https://imgur.com/a/tVeW8TB

3. Proof of my purchased:

https://imgur.com/a/9TsYcIf

3. Config files (optional)

Config.dart - https://filebin.net/becvkrj8hww0zj70/config.dart?t=zsbmottl

Config.json - https://filebin.net/yawilsdcvbq0cdiy/config.json?t=k20muw5l
Config_ar.json - https://filebin.net/9v2zm8kiu7b5d6bi/config_ar.json?t=k3ydcajw

**Comment by minhtruong315** [comment]
@Alnaggar94 I can't download your config https://tppr.me/cGd7
send me again. and icon png

**Comment by Alnaggar94** [comment]
I re-uploaded with dropbox:

icon - https://www.dropbox.com/s/j0dsog4mbvcsjub/77.png?dl=0
----------------

Config.dart - https://www.dropbox.com/s/4fmc6djvx4to92n/config.dart?dl=0

Config.json - https://www.dropbox.com/s/g1ypq9ys36hvmsy/config.json?dl=0
Config_ar.json - https://www.dropbox.com/s/ss57v0o7h8651sa/config_ar.json?dl=0

**Comment by minhtruong315** [comment]
@Alnaggar94 I dont understand your issue.
i see your icon 
![77](https://user-images.githubusercontent.com/10402500/70408041-581ecd00-1a79-11ea-884d-99085683c55a.png)
when add it to app, it will show https://tppr.me/fKqRp
what is the wrong?

**Comment by Alnaggar94** [comment]
@minhtruong315 sorry I uploaded the wrong icon this is the icon I want to show 
![4](https://user-images.githubusercontent.com/49800146/70487110-50a50580-1b05-11ea-9f81-bf79869cdc93.png)
yellow background and black color for the shape

**Comment by minhtruong315** [comment]
@Alnaggar94 You can replace widgets/home/category/category_icon_items.dart
[category_icon_items.dart.zip](https://github.com/inspireui/support/files/3942901/category_icon_items.dart.zip)
Then update category item in  config.json like this 
```{
          "category": 20,
          "image": "assets/icons/categories/77.png",
          "originalColor": true,
          "backgroundColor": "#f3cf71",
          "border": false,
          "colors": [
            "#f3cf71",
            "#f3cf71"
          ]
        },
```

**Comment by Alnaggar94** [comment]
@minhtruong315 Thank you so much, It worked perfectly.

**Comment by Alnaggar94** [comment]
@minhtruong315 - It was working with the previous version but doesn't work with v1.6.3 anymore
