### ISSUE TITLE
Beo News: Rotation bug

### ISSUE THREAD

**Issue by bao-1986** [inspireui/support#1556]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
when we view the post if the  device is rotated: 
1) app exits to splash screen.
2) the post does not go full screen,  unless we reload the app with keeping the device on same position.

possible solutions:
1) make the post rotation full screen (current screen should have one post)
OR 
2)  how to deactivate device rotation from the app: i tried  to  android:screenOrientation="portrait" using in AndroidMainfest.xml .. But it does not work.  

please guide to solve it. thanks 

2. Screenshots issues:

3. Proof of my purchased:

3. Config files (optional)

**Comment by bao-1986** [comment]
https://www.dropbox.com/home/Photos?preview=rotate+bug.jpg

**Comment by bao-1986** [comment]
https://www.dropbox.com/s/pup381u8j864az5/rotate%20bug.jpg?dl=0

**Comment by minhcasi** [comment]
Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads  it's used to verify your proof of purchase? sorry for any inconvenience - Thank you!

**Comment by bao-1986** [comment]
https://github.com/inspireui/support/issues/1497

**Comment by minhcasi** [comment]
@bao-1986 - sorry for the inconvenience - that why we suggest creating 1 ticket for all issue for each user that prevent the missing request :)

Could you help quick take the screenshot of the issue and resend the config file so that we could reproduce for fixing ?

**Comment by bao-1986** [comment]
@minhcasi 
[Config.zip](https://github.com/inspireui/support/files/3946397/Config.zip)

Screenshot 
https://www.dropbox.com/s/pup381u8j864az5/rotate%20bug.jpg?dl=0

**Comment by bao-1986** [comment]
when it is rotating inside the app, the post is not going fullscreen .. it is divided

**Comment by bao-1986** [comment]
@minhcasi  admob Bug 
the ads are not showing in real device. only showing in emulator.
there is something missing in your configuration.. 
1)  I used my adunits ()
2) I used google formal testing units (same problem)
  AdMob: {
    visible: true,
    deviceID: '6612F2AEECD2A4ADBD699CFC349AB01A',
        unitID: 'ca-app-pub-3940256099942544/6300978111', //test
   unitInterstitial: 'ca-app-pub-3940256099942544/1033173712', //test 
    isShowInterstital: true,
  },


![xmladmob ](https://user-images.githubusercontent.com/58382254/70636994-72230000-1c71-11ea-8393-22f8cbf6175d.jpg)

**Comment by minhcasi** [comment]
@bao-1986  - pls try to lock the rotating feature to prevent the user change orientation - this detail guide could help - https://medium.com/react-native-training/react-native-portrait-device-orientation-9bcdeeac0b03

**Comment by bao-1986** [comment]
![image](https://user-images.githubusercontent.com/58382254/70712751-76a5f200-1d1f-11ea-81e2-ac063ed89bfd.png)
as the link says ... but still rotating

**Comment by minhcasi** [comment]
@bao-1986 - sorry for late response -  did you try on real device or simulator - pls note that on the simulator the sensor is not working so that it may not work correctly :)

**Comment by bao-1986** [comment]
I tried both .. it is not working.. still rotating

**Comment by bao-1986** [comment]
I do not know what is the maximum supported size  ..

**Comment by minhcasi** [comment]
@concuacon - could you give some suggestions? Thanks

**Comment by concuacon** [comment]
@bao-1986 you can try to follow this link, I think that helps you
https://stackoverflow.com/a/38689905/5295046
***After changing the configuration you need to do the following to ensure:
- Delete old app
- Clean gradle: cd android; ./gradlew clean; cd ..
- react-native run-android

**Comment by bao-1986** [comment]
1) Xml changes: 
 deleted the |orientation|
added android:screenOrientation="portrait"

2)Delete old app
3) cd android; ./gradlew clean

4)npm cache clean  --force
5)delete node_ module
6)npm install
7)npm start --reset-cache
8) react-native run-android

please test the solution, it did not work for me, Still rotating in emulator and real device.

**Comment by bao-1986** [comment]
1) I also added 
import android.content.pm.ActivityInfo;
setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT);
===> to splashactivity.java

2) replaced android:orientation="vertical"  to  android:screenOrientation="portrait" 
===> launch_screen.xml 

also did not work.

**Comment by minhcasi** [comment]
@concuacon - pls help for checking

**Comment by concuacon** [comment]
@bao-1986 If still not work, you can try to use this package https://github.com/wonday/react-native-orientation-locker ( I tested it work for me)

**Comment by bao-1986** [comment]
Yes brother this package forced 

BUT  all the dimension are broken inside the whole app! 

I found it is an exiting opened issue in "wonday/react-native-orientation-locker" from June 2019. 


https://www.dropbox.com/s/02jikonxmxgh9yg/Photo%2026-12-2019%2C%2012%2051%2017%20AM.jpg?dl=0

**Comment by bao-1986** [comment]
https://www.dropbox.com/s/n44p23lk5h9wv31/Photo%2026-12-2019%2C%2012%2051%2022%20AM.jpg?dl=0

**Comment by bao-1986** [comment]
Hi brother 
it have been solved by Xml changes::
deleted the |orientation| => android:configChanges="keyboard|keyboardHidden|screenSize"
added android:screenOrientation="portrait" to the three activities as the photo 

![1a1d7b85e7227002f99fa41ad731bc9](https://user-images.githubusercontent.com/58382254/71449701-9b717f00-278d-11ea-96e5-8db569f69410.png)

**Comment by bao-1986** [comment]
you can test it and put it in the next update

**Comment by bao-1986** [comment]
also maybe this one had an effect + to what I have modified in xml .... 
I am not sure 

import android.content.pm.ActivityInfo;
setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT);
===> to splashactivity.java

**Comment by concuacon** [comment]
@bao-1986 Thank you so much, I will consider your suggestion.

**Comment by bao-1986** [comment]
you are welcome
