### ISSUE TITLE
[CeStore] Can't get data from server

### ISSUE THREAD

**Issue by hyongshu** [inspireui/support#1557]
![Simulator Screen Shot - iPhone 11 Pro Max - 2019-12-09 at 14 39 57](https://user-images.githubusercontent.com/25469808/70416544-e2732b00-1a91-11ea-92f9-ce4ce07746cd.png)

I run server already. but mobile can't get data from server.

**Comment by minhcasi** [comment]
Could you help to share the screenshot of the purchase screenshot from https://codecayon.net/downloads  it's used to verify your proof of purchase? sorry for any inconvenience - Thank you!
