### ISSUE TITLE
[Fluxstore WooCommerce - Flutter E-commerce App] - Version: 1.5.8----Searching address from google maps not working

### ISSUE THREAD

**Issue by itej7** [inspireui/support#1559]
Hi InspireUI Team,

My issue: We are unable to get an address from google maps in Fluxstore WooCommerce - Flutter E-commerce App.

The map is not loading. We have also inserted our own Google API key. Kindly help us.

Waiting for your revert.

Thanks & Regards,
Tejas Patil

**Comment by itej7** [comment]
@minhcasi : Please check and update at earliest.

**Comment by itej7** [comment]
Dear Team,

Please update us as we need to finalize our application for playstore and appstore.

**Comment by minhcasi** [comment]
@itej7 - could i check if you have download the google service file to match with your new bundle id - https://docs.inspireui.com/fluxstore/firebase/ ?

#1558 -  Also, please help to create 1 ticket for your issues that help us focus and understand more on your issues, create multi-ticket will take your time and our time to check and verify purchase - thank you!
