### ISSUE TITLE
[MStore Pro & Expo 3.6.6] (Fix Included) Customer data (address, email, phone, etc) not automatically populating the Mstore checkout page when user logs in.

### ISSUE THREAD

**Issue by levi-beers** [inspireui/support#156]
The customer data stored in Wordpress/WooCommerce, specifically the customers address, phone, email and other fields are not populating the Mstore checkout page as it used to. The fields show up with no data even though there is data stored in WooCommerce for the specific user. 

<img width="354" alt="screen shot 2019-01-04 at 9 38 48 pm" src="https://user-images.githubusercontent.com/16378407/50719386-4e226c00-1069-11e9-9311-5a0570b4618f.png">

**Comment by levi-beers** [comment]
Reactotron shows the following
<img width="954" alt="screen shot 2019-01-04 at 9 44 01 pm" src="https://user-images.githubusercontent.com/16378407/50719449-eb7da000-1069-11e9-8d43-6719dec6b72c.png">

**Comment by levi-beers** [comment]
It looks like AddressRedux.js on line 32+ is hard coding the address, state and other info to "" (null).

**Comment by luyx2412** [comment]
Hi @levi-beers Thanks for your feedback. We will update with next version.
