### ISSUE TITLE
[my-product] - Fluxstore Pro

### ISSUE THREAD

**Issue by LembarkSolutions** [inspireui/support#1561]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: register is not working getting error. 

2. Screenshots issues: https://prnt.sc/q8b3h1

3. Proof of my purchased: https://prnt.sc/q8b2pj

3. Config files (optional)

**Comment by incepio-flutter** [comment]
https://github.com/inspireui/support/issues/1478 following this issue might solve your problem

**Comment by LembarkSolutions** [comment]
thank you above issue solve.

please let me know below questions answer.

1. Where we can see **aftership** **tracking** info inside ios/android app? 

2.If Order payment method is COD then it status should “Processing” instead of “Pending payment” after successfully placed order.

**Comment by incepio-flutter** [comment]
can you please upload screenshots of your problem?

**Comment by LembarkSolutions** [comment]
I am not able see aftership tracking , Which screen I should send you?

below is log.

E/flutter ( 7574): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: RangeError (index): Invalid value: Only valid value is 0: 1
E/flutter ( 7574): #0      List.[] (dart:core-patch/growable_array.dart:147:60)
E/flutter ( 7574): #1      new AfterShip.fromJson (package:fstore/models/aftership.dart:8:64)
E/flutter ( 7574): #2      WooCommerce.getAllTracking (package:fstore/services/woo_commerce.dart:600:22)
E/flutter ( 7574): <asynchronous suspension>
E/flutter ( 7574): #3      Services.getAllTracking (package:fstore/services/index.dart:337:25)
E/flutter ( 7574): <asynchronous suspension>
E/flutter ( 7574): #4      _OrderDetailState.getTracking (package:fstore/screens/order_detail.dart:40:14)
E/flutter ( 7574): #5      _OrderDetailState.initState (package:fstore/screens/order_detail.dart:34:5)
E/flutter ( 7574): #6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4068:58)
E/flutter ( 7574): #7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
E/flutter ( 7574): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter ( 7574): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter ( 7574): #10     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
E/flutter ( 7574): #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter ( 7574): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter ( 7574): #13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
E/flutter ( 7574): #14     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
E/flutter ( 7574): #15     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
E/flutter ( 7574): #16     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
E/flutter ( 7574): #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter ( 7574): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter ( 7574): #19     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
E/flutter ( 7574): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter ( 7574): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter ( 7574): #22     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
E/flutter ( 7574): #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter ( 7574): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter ( 7574): #25     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
E/flutter ( 7574): #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter ( 7574): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter ( 7574): #28     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
E/flutter ( 7574): #29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter ( 7574): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter ( 7574): #31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
E/flutter ( 7574): #32     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
E/flutter ( 7574): #33     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
E/flutter ( 7574): #34     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
E/flutter ( 7574): #35     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
E/flutter ( 7574): #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter ( 7574): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter ( 7574): #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
E/flutter ( 7574): #39     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
E/flutter ( 7574): #40     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
E/flutter ( 7574): #41     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
E/flutter ( 7574): #42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter ( 7574): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter ( 7574): #44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
E/flutter ( 7574): #45     Element.rebuild (package:flutter/src/widgets/framework.dart:
V/FA      ( 7574): Inactivity, disconnecting from the service

**Comment by minhcasi** [comment]
@LembarkSolutions - could we check if you have installed this plugin - https://wordpress.org/plugins/aftership-woocommerce-tracking/ - thanks

**Comment by LembarkSolutions** [comment]
Aftership Plugin already installed there and I have also add few tracking code for testing.

**Comment by minhcasi** [comment]
@LembarkSolutions - could you share your config file here so that we could have a check (common/config.dart and config.json) - thank you!

**Comment by LembarkSolutions** [comment]
@minhcasi please check your skype I have share there. hoping hear from you asap. thank you

**Comment by minhcasi** [comment]
@LembarkSolutions - could you help forward the config to this email manh@inspireui.com? Thanks

**Comment by LembarkSolutions** [comment]
@minhcasi  please check your mail.

**Comment by LembarkSolutions** [comment]
Please @vumanhsn97 let me know Is this issue resolved?

**Comment by LembarkSolutions** [comment]
Thank you
