### ISSUE TITLE
After Building the App image not loaded in App running local images displayed

### ISSUE THREAD

**Issue by khaja25** [inspireui/support#1562]
---------

1. My issue:
while build  Andriod App, product image not loaded in App 

2. Screenshots issues:
![imagenotload1](https://user-images.githubusercontent.com/58036762/70439407-f597f200-1ab5-11ea-9d7a-7d85381f8e00.jpeg)
![imgnotload2](https://user-images.githubusercontent.com/58036762/70439419-f9c40f80-1ab5-11ea-9e6e-0832ba03bbdb.jpeg)

3. Proof of my purchased:
![download](https://user-images.githubusercontent.com/58036762/70439471-1e1fec00-1ab6-11ea-903a-a70cf7e67fe2.jpeg)

3. Config files (optional)

**Comment by minhcasi** [comment]
@khaja25 - note with checking - thanks

Could you share your config file as well ?

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
