### ISSUE TITLE
[beonews] - TypeError: null is not an object (evaluating 'post.better_.... 

### ISSUE THREAD

**Issue by lukas76** [inspireui/support#1563]
1. My issue: TypeError: null is not an object (evaluating 'post.better_featured_image.media_details')

This error is located at:
    in CardLayout (at PostLayout/index.js:22)
    in PostLayout (at PostList/index.js:84)
  
--
This error comes up the moment after loading the javascript bundle. None of the app truly loads other than the splashpage when loading the app using expo. 

2. Screenshots issues: https://puu.sh/ENx8V/c7a140698b.png

3. Proof of my purchased: Item Purchase Code:
2437415e-de8f-4819-b981-0d0e3c53ac07

https://puu.sh/ENxby/fd1ea9af8e.png

3. Config files (optional)

Thanks for the help, I appreciate it.

**Comment by lukas76** [comment]
To be clear I already have this plugin installed. https://wordpress.org/plugins/better-rest-api-featured-images/

**Comment by minhcasi** [comment]
@lukas76 - could you help to share your config file here ?

**Comment by lukas76** [comment]
[AppConfig.json.txt](https://github.com/inspireui/support/files/3945169/AppConfig.json.txt)

**Comment by minhcasi** [comment]
@concuacon - please help for checking

**Comment by lukas76** [comment]
There anyway to get speedier help with this issue? 

I have a programmer beginning work tonight and this issue isn't something that he needs to be working on.

**Comment by bao-1986** [comment]
I saw your issue accidentally, can you resize you featured image to the size Dimensions: 510 by 369 pixels, and post it .jpg not png. I think it will work.

**Comment by bao-1986** [comment]
I do not know what should be the best size for the featured image. I hope you will get an answer and tell me as well :D

**Comment by lukas76** [comment]
That fixed it, thank you.

**Comment by concuacon** [comment]
@bao-1986 Thank you.
