### ISSUE TITLE
[BeoNews] - Animation when opening article and clicking on description does not open article

### ISSUE THREAD

**Issue by TheCellMC** [inspireui/support#1564]
### My issues:

- When clicking on an article from the home page on BeoNews pro, the article opens instantly without any animation. This makes seem as if it was some sort of bug. Would it be possible for the article to open with some sort of animation?

- If I press on the description of an article, the article does not open. I have to press on the title or the image for it to open. See the following screenshot for the zone which does not open the article if selected:

![IMG_0F680E948333-1](https://user-images.githubusercontent.com/12169936/70460434-95ee1680-1ab6-11ea-9ebd-cddbc4c0e834.jpeg)

Thanks!

**Comment by minhcasi** [comment]
@concuacon - pls help to improve this UX - thank you!

**Comment by luyx2412** [comment]
Fixed in next version.
