### ISSUE TITLE
[listapp] What are these errors and how do you fix?

### ISSUE THREAD

**Issue by befreeman5** [inspireui/support#1565]
https://imgur.com/a/VyiyPM9
<img width="1136" alt="Screen Shot 2019-12-09 at 11 43 02 AM" src="https://user-images.githubusercontent.com/58203308/70467007-43dad000-1a79-11ea-94fa-a0a34794e951.png">
<img width="1118" alt="Screen Shot 2019-12-09 at 11 42 49 AM" src="https://user-images.githubusercontent.com/58203308/70467008-43dad000-1a79-11ea-89ba-06097f901ae2.png">
<img width="1166" alt="Screen Shot 2019-12-09 at 11 42 20 AM" src="https://user-images.githubusercontent.com/58203308/70467010-43dad000-1a79-11ea-92aa-716e830dbcaf.png">

**Comment by minhcasi** [comment]
@befreeman5 - we could help for remoting via TeamViewer to support you to fix this issue, do you available from 9:00am - 5:00PM GMT+7 ? Thanks

**Comment by befreeman5** [comment]
I’d love help with remote! I’m free anytime. How’s 10am your time? Let me know what I need to do and I’m ready to jump on asap! Thanks!

**Comment by minhcasi** [comment]
Hi, could I know if you are available now, or the next 2-3 hours? Thank you!

**Comment by befreeman5** [comment]
for some reason I don't get GitHub notifications. can you email when you're free? brianfreeman@outlook.com thanks! i'm free whenever

**Comment by minhcasi** [comment]
@befreeman5 - pls add this Skype contact pvtuan1707 and request him for support installing Expo on your PC - please note that we will not help for customization or config your site as it will take more integration time - thank you!

**Comment by minhcasi** [comment]
@concuacon  - pls help for checking

**Comment by befreeman5** [comment]
Still waiting..

**Comment by minhtruong315** [comment]
@befreeman5 pls add my skype: minhtruong315
I'll help u check issues via teamviewer
Thanks

**Comment by minhtruong315** [comment]
Hi @befreeman5 I see your website is using Salient template. It's not valid for our listing app. We have supported these themes: https://tppr.me/KWrn0
please look, thanks

**Comment by befreeman5** [comment]
My theme is listable. It’s a multi site. You’re looking at the wrong website

On Dec 25, 2019, at 12:24 AM, minhtruong315 <notifications@github.com> wrote:

﻿

Hi @befreeman5<https://github.com/befreeman5> I see your website is using Salient template. It's not valid for our listing app. We have supported these themes: https://tppr.me/KWrn0
please look, thanks

**Comment by minhcasi** [comment]
@befreeman5 the current Listapp is not working with the multi-site as the API is not compatible - kindly process the refund it could not use the product - thank you!

**Comment by befreeman5** [comment]
someone else from your support says it works fine. I'm not sure why multisite would be an issue

________________________________
