### ISSUE TITLE
[my-product] -mstore expo 

### ISSUE THREAD

**Issue by basemslama** [inspireui/support#1567]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: i cant install expo , no links working

2. Screenshots issues:
![xxxxxxxxxxxxx](https://user-images.githubusercontent.com/58700788/70470367-892beb80-1ad3-11ea-9e60-5fc256cb3853.jpg)

3. Proof of my purchased: 42c17a46-7f2a-497d-87c5-166c5b2fbc31

3. Config files (optional)

**Comment by minhcasi** [comment]
@basemslama - could you help to install the Expo manually from this link - http://expo.io/tools  - on Window this issue could happen sometime due to the permission that the app could process installing automatically - thank you!
