### ISSUE TITLE
[EvaStore] - TypeError: undefined is not an object (evaluating '_services.GraphqlAPI.getProductsByCollection({         categoryId: categoryId       }).then')

### ISSUE THREAD

**Issue by davutj** [inspireui/support#1568]
1. My issue:
    Same error as #1116 
    Happened after pushing the code to git repository 
2. Screenshots issues:
   
<img width="370" alt="Screen Shot 2019-12-09 at 19 10 35" src="https://user-images.githubusercontent.com/27011602/70491950-a5219400-1ab7-11ea-907a-c1e43b9e9a5a.png">

3. Proof of my purchased:
    Purchased by another team member can not reach him at the moment
<img width="882" alt="Screen Shot 2019-12-09 at 19 12 33" src="https://user-images.githubusercontent.com/27011602/70492130-34c74280-1ab8-11ea-9c4b-1fa208d956de.png">

3. Config files (optional)
    Same as yours

**Comment by minhcasi** [comment]
@davutj - it ok for the verify purchased if you could give the comment on https://codecanyon.net/item/evastore-shopify-mobile-store-by-react-native-and-graphql/22715163 - thank you!

**Comment by davutj** [comment]
<img width="620" alt="Screen Shot 2019-12-10 at 14 32 11" src="https://user-images.githubusercontent.com/27011602/70574839-e5d1e980-1b59-11ea-9048-d76b33b40ea6.png">

Here is the proof

**Comment by minhcasi** [comment]
Thank you, please help us to create one ticket for your all issue that help us to understand more on the issue and provide better support.

As we can see you can fetch the product on the latest ticket #1575

**Comment by davutj** [comment]
[EvaStore] - TypeError: undefined is not an object (evaluating '_services.GraphqlAPI.getProductsByCollection({ categoryId: categoryId }).then') <- This happens when I copy files to another directory. Is there any reason @minhcasi? I copy hidden files too.
