### ISSUE TITLE
Fluxstore customization 

### ISSUE THREAD

**Issue by alqumairi94** [inspireui/support#1569]
I have bought fluxstore and now want to customize it because my website is mainly a news website and the woocommerce is only one part of it. so, i want to make it news app and have one tab go to the shop page. 

Thanks

**Comment by minhcasi** [comment]
Hi @alqumairi94 - thank you for the contact, could you help to clarify more detail requirement which the features that you would like to customize, if you could take the screenshot it should be great. Please send privately your detail to support@inspireui.com
