### ISSUE TITLE
[ListApp] Cache Issues & Login Issues

### ISSUE THREAD

**Issue by menzer2015** [inspireui/support#157]
**Required Info (please complete the following information):**
 - Product: ListApp - MyListing
 - Your Purchased Code: 1d8d4ae7-****-44fa-****-a869**764**83

(we may not reply if you are not our customer)

**Describe the bug**

Hi guys, fantastic plugin, but I have an issue, when I login using my WP account it asks for me to enter my details again and then logs in after the second time (I am  not sure if this is because it is logging into firebase and WP)

My next issue is caching issues, once logged in and on the profile page, there s a section called My Listings that will list all items I have posted via myListings if I log out and log back in as another users sometimes the items of the last person logged in displays and sometimes nothing at all.

How can I fix this issue please

**Screenshots**

**Additional context**
Add any other detail logs about the problem here.
If possible please share your config.js that use for the app setting

**Comment by thangvo9x** [comment]
Hi. Fixed in the next version . Thanks

**Comment by jaksatomovic** [comment]
@thangvo9x  i have the same cache issue
