### ISSUE TITLE
[my-product] - 

### ISSUE THREAD

**Issue by bhallaramdhatarwal** [inspireui/support#1570]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: I have facing some issues into flutter application during checkout in open-cart as well as magneto.

I have add some product into cart but when i try to checkout that time can't process forward and loader is showing continuously.

So can you help me to complete checkout process and done complete task.

2. Screenshots issues:
![Screenshot_20191210-184009](https://user-images.githubusercontent.com/58734495/70532255-acf73c00-1b7c-11ea-8a74-50d24d21dc72.jpg)

3. Proof of my purchased: ccdec22e-845a-4851-b065-2375e3b9cd37

3. Config files (optional)

[config.zip](https://github.com/inspireui/support/files/3944949/config.zip)

**Comment by minhcasi** [comment]
@minhtruong315 - pls help for checking

**Comment by minhtruong315** [comment]
@bhallaramdhatarwal you need to disable GuestCheckout in config.dart. It's not working on magento and opencart

**Comment by bhallaramdhatarwal** [comment]
@minhtruong315 but I have already login. but It's not working on opencart and magento. I am test Android build.

**Comment by minhtruong315** [comment]
send me your source code via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/1570

**Comment by minhtruong315** [comment]
@bhallaramdhatarwal pls update the latest source code.
