### ISSUE TITLE
fluxstore pro

### ISSUE THREAD

**Issue by AhmedAlDaw** [inspireui/support#1571]
1.hi, i have a problem with Arabic search get all products but English search get searched products

![c92028cd-bc90-40a8-aac0-9d147240a31d](https://user-images.githubusercontent.com/49566808/70535779-7c7ab800-1b12-11ea-9cd6-3f5c58734855.jpg)
![61b189a8-f385-476e-9f24-a6745bce8cf6](https://user-images.githubusercontent.com/49566808/70535780-7c7ab800-1b12-11ea-855e-ffec93674ab8.jpg)

![flx](https://user-images.githubusercontent.com/49566808/70535947-c4014400-1b12-11ea-93eb-681cfb1955bc.png)

**Comment by minhcasi** [comment]
@minhtruong315 - pls help for checking

**Comment by minhtruong315** [comment]
@AhmedAlDaw send me config.dart file and admin account via email:truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/1571

**Comment by minhcasi** [comment]
Hi, could you share the admin access so that we could check the website or WPML plugin config that causes the integration issues, also attache your current source code to truong@inspireui.com and note the issue related to this ticket so that he can help for checking - thank you
