### ISSUE TITLE
MStore Magento

### ISSUE THREAD

**Issue by a7medeeuae** [inspireui/support#1572]
i still get this

win_delay_load_hook.cc
z.vcxproj -> C:\Users\MR.Robot\Desktop\CeBuilder\Mstore-magento-1.1\Source\node_modules\grpc\build\Release\libz.lib
gyp ERR! build error
gyp ERR! stack Error: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe failed with exit code: 1
gyp ERR! stack at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack at ChildProcess.emit (events.js:210:5)
gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=C:\Users\MR.Robot\Desktop\CeBuilder\Mstore-magento-1.1\Source\node_modules\grpc\src\node\extension_binary\node-v72-win32-x64-unknown\grpc_node.node" "--module_name=grpc_node" "--module_path=C:\Users\MR.Robot\Desktop\CeBuilder\Mstore-magento-1.1\Source\node_modules\grpc\src\node\extension_binary\node-v72-win32-x64-unknown" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd C:\Users\MR.Robot\Desktop\CeBuilder\Mstore-magento-1.1\Source\node_modules\grpc
gyp ERR! node -v v12.13.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd build --fallback-to-build --library=static_library --module=C:\Users\MR.Robot\Desktop\CeBuilder\Mstore-magento-1.1\Source\node_modules\grpc\src\node\extension_binary\node-v72-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=C:\Users\MR.Robot\Desktop\CeBuilder\Mstore-magento-1.1\Source\node_modules\grpc\src\node\extension_binary\node-v72-win32-x64-unknown --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
node-pre-gyp ERR! stack at ChildProcess. (C:\Users\MR.Robot\Desktop\CeBuilder\Mstore-magento-1.1\Source\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack at ChildProcess.emit (events.js:210:5)
node-pre-gyp ERR! stack at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
node-pre-gyp ERR! System Windows_NT 10.0.18363
node-pre-gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Users\MR.Robot\Desktop\CeBuilder\Mstore-magento-1.1\Source\node_modules\node-pre-gyp\bin\node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd C:\Users\MR.Robot\Desktop\CeBuilder\Mstore-magento-1.1\Source\node_modules\grpc
node-pre-gyp ERR! node -v v12.13.1
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd build --fallback-to-build --library=static_library --module=C:\Users\MR.Robot\Desktop\CeBuilder\Mstore-magento-1.1\Source\node_modules\grpc\src\node\extension_binary\node-v72-win32-x64-unknown\grpc_node.node
C:\Users\MR.Robot\Desktop\CeBuilder\Mstore-magento-1.1\Source>
C:\Users\MR.Robot\Desktop\CeBuilder\Mstore-magento-1.1\Source>
C:\Users\MR.Robot\Desktop\CeBuilder\Mstore-magento-1.1\Source>
C:\Users\MR.Robot\Desktop\CeBuilder\Mstore-magento-1.1\Source>

![image](https://user-images.githubusercontent.com/24714994/70536637-8fc06e80-1b78-11ea-8c20-74952c7c4c64.png)

**Comment by minhcasi** [comment]
@minhtruong315 - pls help for checking

**Comment by minhtruong315** [comment]
@a7medeeuae which node version are u using? if your node version is 13, you need to downgrade to 10

**Comment by a7medeeuae** [comment]
i will try

**Comment by a7medeeuae** [comment]
warning "api-ecommerce > firebase > @firebase/performance > @firebase/installations > @firebase/installations-types@0.1.0" has unmet peer dependency "@firebase/app-types@0.x".
warning " > create-react-context@0.2.3" has unmet peer dependency "prop-types@^15.0.0".
warning "babel-jest > babel-preset-jest > @babel/plugin-syntax-object-rest-spread@7.7.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "react-instantsearch > react-instantsearch-dom@5.7.0" has unmet peer dependency "react-dom@>= 15.3.0 < 17".
warning "react-instantsearch > react-instantsearch-core > algoliasearch-helper@2.28.0" has unmet peer dependency "algoliasearch@>= 3.1 < 4".
warning "react-native > metro-react-native-babel-transformer@0.51.0" has unmet peer dependency "@babel/core@*".
warning "react-native > @react-native-community/cli > metro-react-native-babel-transformer@0.51.1" has unmet peer dependency "@babel/core@*".
warning "react-native-clean-form > styled-components@4.4.1" has unmet peer dependency "react-dom@>= 16.3.0".
warning " > react-native-localization@2.1.6" has incorrect peer dependency "react-native@^0.41.2".
warning " > react-native-localization@2.1.6" has unmet peer dependency "react-native-windows@0.41.0-rc.1".
warning " > react-native-paper@2.15.0" has unmet peer dependency "react-native-vector-icons@*".
warning " > react-native-radio-buttons@1.0.0" has unmet peer dependency "prop-types@>=15.5.0".
warning " > react-native-render-html@4.1.2" has unmet peer dependency "prop-types@>=15.5.10".
warning " > react-native-svg-uri@1.2.3" has incorrect peer dependency "react-native-svg@^5.3.0".
warning " > react-native-swipe-list-view@1.5.3" has unmet peer dependency "prop-types@>=15.5.0".
warning " > babel-jest@24.6.0" has unmet peer dependency "@babel/core@^7.0.0".
warning "babel-jest > babel-preset-jest@24.9.0" has unmet peer dependency "@babel/core@^7.0.0".
warning " > reactotron-redux@3.1.0" has unmet peer dependency "reactotron-core-client@^2.5.0".
[4/4] Building fresh packages...
$ patch-package
patch-package 6.2.0
Applying patches...
No patch files found
Done in 152.17s.

C:\Users\MR.Robot\Desktop\CeBuilder\Mstore-magento-1.1\Source>

**Comment by a7medeeuae** [comment]
yarn cache v1.19.1
success Cleared cache.
Done in 11.16s.
yarn install v1.19.1
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "win32" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "api-ecommerce > firebase > @firebase/database@0.3.20" has unmet peer dependency "@firebase/app-types@0.x".
warning "api-ecommerce > firebase > @firebase/firestore@1.2.2" has unmet peer dependency "@firebase/app-types@0.x".
warning "api-ecommerce > firebase > @firebase/functions@0.4.6" has unmet peer dependency "@firebase/app-types@0.x".
warning "api-ecommerce > firebase > @firebase/messaging@0.3.19" has unmet peer dependency "@firebase/app-types@0.x".
warning "api-ecommerce > firebase > @firebase/performance@0.2.1" has unmet peer dependency "@firebase/app-types@0.x".
warning "api-ecommerce > firebase > @firebase/storage@0.2.15" has unmet peer dependency "@firebase/app-types@0.x".
warning "api-ecommerce > firebase > @firebase/auth > @firebase/auth-types@0.6.1" has unmet peer dependency "@firebase/app-types@0.x".
warning "api-ecommerce > firebase > @firebase/auth > @firebase/auth-types@0.6.1" has unmet peer dependency "@firebase/util@0.x".
warning "api-ecommerce > firebase > @firebase/database > @firebase/database-types@0.3.11" has unmet peer dependency "@firebase/app-types@0.x".
warning "api-ecommerce > firebase > @firebase/firestore > @firebase/firestore-types@1.2.1" has unmet peer dependency "@firebase/app-types@0.x".
warning "api-ecommerce > firebase > @firebase/functions > @firebase/messaging-types@0.2.11" has unmet peer dependency "@firebase/app-types@0.x".
warning "api-ecommerce > firebase > @firebase/performance > @firebase/installations@0.1.0" has unmet peer dependency "@firebase/app-types@0.x".
warning "api-ecommerce > firebase > @firebase/storage > @firebase/storage-types@0.2.11" has unmet peer dependency "@firebase/app-types@0.x".
warning "api-ecommerce > firebase > @firebase/storage > @firebase/storage-types@0.2.11" has unmet peer dependency "@firebase/util@0.x".
warning "api-ecommerce > firebase > @firebase/performance > @firebase/installations > @firebase/installations-types@0.1.0" has unmet peer dependency "@firebase/app-types@0.x".
warning " > create-react-context@0.2.3" has unmet peer dependency "prop-types@^15.0.0".
warning "babel-jest > babel-preset-jest > @babel/plugin-syntax-object-rest-spread@7.7.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "react-instantsearch > react-instantsearch-dom@5.7.0" has unmet peer dependency "react-dom@>= 15.3.0 < 17".
warning "react-instantsearch > react-instantsearch-core > algoliasearch-helper@2.28.0" has unmet peer dependency "algoliasearch@>= 3.1 < 4".
warning "react-native > metro-react-native-babel-transformer@0.51.0" has unmet peer dependency "@babel/core@*".
warning "react-native > @react-native-community/cli > metro-react-native-babel-transformer@0.51.1" has unmet peer dependency "@babel/core@*".
warning "react-native-clean-form > styled-components@4.4.1" has unmet peer dependency "react-dom@>= 16.3.0".
warning " > react-native-localization@2.1.6" has incorrect peer dependency "react-native@^0.41.2".
warning " > react-native-localization@2.1.6" has unmet peer dependency "react-native-windows@0.41.0-rc.1".
warning " > react-native-paper@2.15.0" has unmet peer dependency "react-native-vector-icons@*".
warning " > react-native-radio-buttons@1.0.0" has unmet peer dependency "prop-types@>=15.5.0".
warning " > react-native-render-html@4.1.2" has unmet peer dependency "prop-types@>=15.5.10".
warning " > react-native-svg-uri@1.2.3" has incorrect peer dependency "react-native-svg@^5.3.0".
warning " > react-native-swipe-list-view@1.5.3" has unmet peer dependency "prop-types@>=15.5.0".
warning " > babel-jest@24.6.0" has unmet peer dependency "@babel/core@^7.0.0".
warning "babel-jest > babel-preset-jest@24.9.0" has unmet peer dependency "@babel/core@^7.0.0".
warning " > reactotron-redux@3.1.0" has unmet peer dependency "reactotron-core-client@^2.5.0".
[4/4] Building fresh packages...
$ patch-package
patch-package 6.2.0
Applying patches...
No patch files found
Done in 152.17s.

C:\Users\MR.Robot\Desktop\CeBuilder\Mstore-magento-1.1\Source>

**Comment by minhtruong315** [comment]
@a7medeeuae did u run project successfully?

**Comment by a7medeeuae** [comment]
not working

**Comment by minhtruong315** [comment]
can u record screen?

**Comment by a7medeeuae** [comment]
ok

**Comment by a7medeeuae** [comment]
![1](https://user-images.githubusercontent.com/24714994/70812175-8e917a80-1de0-11ea-96c9-9e7ea8253816.jpg)
![2](https://user-images.githubusercontent.com/24714994/70812176-8e917a80-1de0-11ea-84dd-e423c22de139.jpg)

https://www.dropbox.com/s/9eghw79r39y26b9/bandicam%202019-12-13%2019-34-51-924.mp4?dl=0

**Comment by a7medeeuae** [comment]
???????

**Comment by minhtruong315** [comment]
you need to run this command to start app.
```
expo start
```

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
