### ISSUE TITLE
[Fluxstore 1.5.9] - Error Please Kindly Fix for me 

### ISSUE THREAD

**Issue by myothura** [inspireui/support#1573]
Thanks a lot for Quick Respond . @vumanhsn97 @minhcasi

I have another error . Please :P

1st Error is this https://tppr.me/WBj5y ( This error occur When i Sing Up . The update Mstore Api already install & config . https://tppr.me/vNf4e

2 rd I check Out with guest check out . The country is working fine .
This error occur when i click country box https://tppr.me/nENpI . ( When i login with phone number )

Cannot get profile when the login with Facebook login. and My order TAB get error
This error . https://tppr.me/1pRpV - My order tab is working fine when login with SMS login
4th Error is When i login with SMS . I have point in Woocommerce point and reward in 150 point . But
My point Tab showing ( 0 ) Point . https://tppr.me/hYzFJ

5th How to use my point when the customer make check out the products?

Thanks

Very Very Thanks you @vumanhsn97 You are the best Thanks

**Comment by incepio-flutter** [comment]
for your first error follow this issue https://github.com/inspireui/support/issues/1478
for your second error replace these files 
screens/checkout/shipping_address.dart
widgets/cart_item.dart
[Archive (1).zip](https://github.com/inspireui/support/files/3946477/Archive.1.zip)

**Comment by myothura** [comment]
@incepio-flutter  Thanks you . Now my 2nd error is working yet thanks you .

@vumanhsn97  @minhcasi  Please kindly fix for me another error .

**Comment by vumanhsn97** [comment]
For 1st error, you can check https://github.com/inspireui/support/issues/1512

**Comment by myothura** [comment]
@vumanhsn97  1st error already make everything from #1512  But not working 
https://tppr.me/yTBDX 

I already send my wordpress admin usernmae and password to vumanhsn97@gmail.com Thanks. 

Please kindly tell me how to fix another error . 

I urgently need to release to app store. Big Thanks @vumanhsn97  @minhcasi

**Comment by vumanhsn97** [comment]
@myothura Not found your bug. it's working https://tppr.me/nCCcq
https://tppr.me/m6Asx

Please check again!

**Comment by myothura** [comment]
@vumanhsn97  This error still occur in my app. How to fix it? 
See my screen record video. Please  
https://youtu.be/jdhFSO1CE3g 

The error video will be available soon https://tppr.me/XKa5n Thanks 

Can you send for me your update source code please.  Thanks for kindly check for me.

**Comment by vumanhsn97** [comment]
@myothura Sent it!. Please check your email!

**Comment by myothura** [comment]
Got it Thanks a lot @vumanhsn97

**Comment by myothura** [comment]
@vumanhsn97  Hello i already test with your new source cod. It's very awesome . But The signup error and point not get error . I don't know why ? Anyway it's ok . * I think this depend on country .  

Now my error is Cannot get profile when the login with Facebook login. and My order TAB get error
This error . https://tppr.me/1pRpV - My order tab is working fine when login with SMS login.

Please kindly check the video. 
https://youtu.be/1wffrTst0QE

When i login with sms . I got profile and working fin order .
and point event not seen please check video please .
https://youtu.be/fGOP7wmUE8A

**Comment by Coinizy1** [comment]
> @myothura Not found your bug. it's working https://tppr.me/nCCcq
> https://tppr.me/m6Asx
> 
> Please check again!
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/a079c67f2516217275e6f3c327963a905eebc7bc/68747470733a2f2f747070722e73332e616d617a6f6e6177732e636f6d2f75706c6f6164732f31366239396537646264353432346661373263653564336362666439303563632e706e67"><img alt="" height="14" src="/favicon-32x32.png"> tppr.me**[Public - Simulator_2019-12-11 11-12-03](https://tppr.me/nCCcq)**
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/f7db452e47acd639bfdefa1ce0a9bb9ce4888359/68747470733a2f2f747070722e73332e616d617a6f6e6177732e636f6d2f75706c6f6164732f63363163323163316531616562356232366135326132626334616137613533632e706e67"><img alt="" height="14" src="/favicon-32x32.png"> tppr.me**[Public - Simulator_2019-12-11 11-15-55](https://tppr.me/m6Asx)**
How you solved it bro? i am getting getnonce 409 error i tried JWT method, i tried .htaccess i tried everything man ;(

**Comment by Coinizy1** [comment]
> @vumanhsn97 Hello i already test with your new source cod. It's very awesome . But The signup error and point not get error . I don't know why ? Anyway it's ok . * I think this depend on country .
> 
> Now my error is Cannot get profile when the login with Facebook login. and My order TAB get error
> This error . https://tppr.me/1pRpV - My order tab is working fine when login with SMS login.
> 
> Please kindly check the video.
> https://youtu.be/1wffrTst0QE
> 
> When i login with sms . I got profile and working fin order .
> and point event not seen please check video please .
> https://youtu.be/fGOP7wmUE8A
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/3b161248b2106b546982156bdf33b41afa3d43c6/68747470733a2f2f747070722e73332e616d617a6f6e6177732e636f6d2f75706c6f6164732f65383565383238323031343034356439393262336161323333343064366661392e706e67"><img alt="" height="14" src="/favicon-32x32.png"> tppr.me**[Public Screenshots - Simulator_2019-12-10 22-20-09](https://tppr.me/1pRpV)**
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/58d5dda55271aa76a18842d62a7a77e4d053a90f/68747470733a2f2f692e7974696d672e636f6d2f76692f31776666725473743051452f6d617872657364656661756c742e6a7067"><img alt="" height="14" src="/yts/img/favicon_144-vfliLAfaB.png"> YouTube**[Order error](https://www.youtube.com/watch?v=1wffrTst0QE)**
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/68312eed602f1514fc5753f3e753f849348a61cb/68747470733a2f2f692e7974696d672e636f6d2f76692f66474f5037776d554538412f687164656661756c742e6a7067"><img alt="" height="14" src="/yts/img/favicon_144-vfliLAfaB.png"> YouTube**[Login with sms](https://www.youtube.com/watch?v=fGOP7wmUE8A)**

Bro how you solved this error? i am getting same 409 error wtf  :(
