### ISSUE TITLE
[fluxstore] - error fultter build apk

### ISSUE THREAD

**Issue by phcaraujo** [inspireui/support#1574]
`You are building a fat APK that includes binaries for android-arm, android-arm64.
If you are deploying the app to the Play Store, it's recommended to use app bundles or split the APK to reduce the APK size.
    To generate an app bundle, run:
        flutter build appbundle --target-platform android-arm,android-arm64
        Learn more on: https://developer.android.com/guide/app-bundle
    To split the APKs per ABI, run:
        flutter build apk --target-platform android-arm,android-arm64 --split-per-abi
        Learn more on:  https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split
Initializing gradle...                                              4,3s
Resolving dependencies...                                          24,1s
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Running Gradle task 'assembleRelease'...                                
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.12.11\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.12.11\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\connectivity-0.4.5+6\android\src\main\java\io\flutter\plugins\connectivity\ConnectivityBroadcastReceiver.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.        
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use unchecked or unsafe operations.      
Note: Recompile with -Xlint:unchecked for details.
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-5.2.7\android\src\main\java\io\flutter\plugins\urllauncher\WebViewActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.        
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:validateSigningRelease'.
> Keystore file 'C:\Users\Administrador\Desktop\Projetos Flutter\codecanyon-vz25PXSu-fluxstore-woocommerce-flutter-ecommerce-full-app\source\android\app\Users\admin\Documents\MyProjects\flutter-mstore\certs\key.jks' not found for signing config 'release'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7m 3s
Running Gradle task 'assembleRelease'...
Running Gradle task 'assembleRelease'... Done                     425,5s (!)
Gradle task assembleRelease failed with exit code 1`

![Sem título](https://user-images.githubusercontent.com/20992411/70547213-47d92180-1b4f-11ea-827a-10fa0d6c9a67.jpg)

**Comment by phcaraujo** [comment]
License
![license](https://user-images.githubusercontent.com/20992411/70550330-5970f800-1b54-11ea-97db-fd0a546f8747.jpg)

**Comment by phcaraujo** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processReleaseGoogleServices'.
> No matching client found for package name 'com.inspireui.fluxstore'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9m 15s
Running Gradle task 'assembleRelease'...
Running Gradle task 'assembleRelease'... Done                     558,4s (!)
Gradle task assembleRelease failed with exit code 1

**Comment by phcaraujo** [comment]
I tried to create a project with zero, but without success

![erro builde](https://user-images.githubusercontent.com/20992411/70556763-46642500-1b60-11ea-9af1-3a4ecb04934c.jpg)

**Comment by vumanhsn97** [comment]
@phcaraujo Can you send me your resource to vumanhsn97@gmail.com?

**Comment by phcaraujo** [comment]
> @phcaraujo Can you send me your resource to [vumanhsn97@gmail.com](mailto:vumanhsn97@gmail.com)?

already solved, changed the key.properties

**Comment by saifmuhtar** [comment]
@phcaraujo 
I'm facing a same problem. How do you change key.properties?
