### ISSUE TITLE
[EvaStore] - MiniBanner (Top section in home page) is not showing up in bigger devices like (iPhone 11 pro max)

### ISSUE THREAD

**Issue by davutj** [inspireui/support#1575]
1. My issue:
MiniBanner (Top section in home page) is not showing up in bigger devices like (iPhone 11 pro max)
2. Screenshots issues:
<img width="511" alt="Screen Shot 2019-12-10 at 16 53 46" src="https://user-images.githubusercontent.com/27011602/70581911-a6ad9380-1b6d-11ea-9279-3cd8e03c7f3f.png">

3. Proof of my purchased:
db599935-bd55-4757-a7c0-fe067f73c256

3. Config files (optional)

**Comment by minhcasi** [comment]
@davutj - could you help to share your config file so that we could help for checking, it could cause by your missing config - thanks

**Comment by davutj** [comment]
`
/** @format */

import Constants from "./Constants";
import Icons from "./Icons";

export default {
  /**
   * Step 1: change to your website shopify graphqlUrl, and storeAccessToken
   * https://help.shopify.com/en/api/custom-storefronts/storefront-api/getting-started
   * Moved AppConfig.json
   */

  // to config custompage
  Wordpress: {
    url: "",
  },

  /**
     Step 2: Setting Product Images
     - ProductSize: Explode the guide from: update the product display size: https://mstore.gitbooks.io/mstore-manual/content/chapter5.html
     The default config for ProductSize is disable due to some problem config for most of users.
     If you have success config it from the Wordpress site, please enable to speed up the app performance
     - HorizonLayout: Change the HomePage horizontal layout - https://mstore.gitbooks.io/mstore-manual/content/chapter6.html
     */
  ProductSize: {
    enable: false,
    CatalogImages: { width: 300, height: 360 },
    SingleProductImage: { width: 600, height: 720 },
    ProductThumbnails: { width: 180, height: 216 },
  },

  /**
   * Step 3: Setting Home screen, category screen
   * Follow this article to use Graphql https://help.shopify.com/en/api/custom-storefronts/storefront-api/graphql
   * Video tutorial https://www.dropbox.com/s/m4kmp0quh8qplz3/Screen%20Recording%202018-11-05%20at%202.22.21%20PM.mov?dl=0
   */
  SpaceLayout: 15, // setting align right
  /**
   * config home page show
   * - horizontal with multi collection id or
   * - vertical layout with latest product and first product is banner
   */
  HomePage: {
    Horizon: true,
    PageSize: 12,
  },
  HorizonLayout: [
    {
      categoryId: "Z2lkOi8vc2hvcGlmeS9Db2xsZWN0aW9uLzQ0NDg5MjkzOA==",
      paging: true,
      layout: Constants.Layout.miniBanner,
    },
    {
      name: "Feature Products",
      categoryId: "Z2lkOi8vc2hvcGlmeS9Db2xsZWN0aW9uLzEzNTk1NDEwNDQyMg==",
      layout: Constants.Layout.threeColumn,
    },
    {
      name: "The Outlet",
      categoryId: "Z2lkOi8vc2hvcGlmeS9Db2xsZWN0aW9uLzEzNTk1NDEzNzE5MA==",
      layout: Constants.Layout.twoColumn,
    },
    {
      name: "Woman",
      categoryId: "Z2lkOi8vc2hvcGlmeS9Db2xsZWN0aW9uLzEzNjkxMDg2NDQ4Ng==",
      layout: Constants.Layout.twoColumnHigh,
    },
    {
      name: "Louis Vuitton",
      categoryId: "Z2lkOi8vc2hvcGlmeS9Db2xsZWN0aW9uLzE1NDY3NjM2MzM2Ng==",
      layout: Constants.Layout.card,
    },
    {
      name: "News",
      type: "article",
      layoutType: "post", // "post" or "product" is default
      layout: Constants.Layout.threeColumn,
    },
  ],

  CategoryLayout: {
    ListMode: "ListMode",
    GridMode: "GridMode",
    CardMode: "CardMode",
  },

  /**
   * Now we only support Webview payment, so disable this feature
   * In the furture we will try support this feature
   */
  Payments: [
    // {
    //   name: "Cash on Delivery",
    //   imageUrl: require("@images/payment_logo/cash_on_delivery.png"),
    //   enabled: true,
    // },
    // {
    //   type: "card",
    //   name: "Credit Card",
    //   imageUrl: require("@images/payment_logo/credit_card.png"),
    //   enabled: true,
    // },
  ],

  /**
     Step 4: Advance config:
     - showShipping: option to show the list of shipping method
     - showStatusBar: option to show the status bar, it always show iPhoneX
     - LogoImage: The header logo
     - CustomPages: Update the custom page which can be shown from the left side bar (Components/Drawer/index.js)
     - intro: The on boarding intro slider for your app
     - menu: config for left menu side items (isMultiChild: This is new feature from 3.4.5 that show the sub products categories)
     * */
  shipping: {
    visible: true,
    time: {
      free_shipping: "4 - 7 Days",
      flat_rate: "1 - 4 Days",
      local_pickup: "1 - 4 Days",
    },
  },
  showStatusBar: true,
  LogoImage: require("@images/jebwa-logo.png"),
  CustomPages: { contact_id: 10941 },

  /**
   * Config Menu Side Drawer
   * @param goToScreen 3 Params (routeName, params, isReset = false)
   * BUG: Language can not change when set default value in Config.js ==> pass string to change Languages
   */
  menu: {
    // has child categories
    isMultiChild: true,
    // Unlogged
    listMenuUnlogged: [
      {
        text: "Login",
        routeName: "Login",
        params: {
          isLogout: false,
        },
        icon: Icons.MaterialCommunityIcons.SignIn,
      },
    ],
    // user logged in
    listMenuLogged: [
      {
        text: "Logout",
        routeName: "Login",
        params: {
          isLogout: true,
        },
        icon: Icons.MaterialCommunityIcons.SignOut,
      },
    ],
    // Default List
    listMenu: [
      {
        text: "Shop",
        routeName: "Default",
        icon: Icons.MaterialCommunityIcons.Home,
      },
      {
        text: "About",
        routeName: "CustomPage",
        params: {
          url: "https://jebwa.com/pages/sustainable-luxury",
        },
        icon: Icons.MaterialCommunityIcons.Email,
      },
    ],
  },
};
`

**Comment by davutj** [comment]
[config.txt](https://github.com/inspireui/support/files/3948741/config.txt)

**Comment by davutj** [comment]
Solved by changing Device.js from:
const isIphoneX =
   Platform.OS === "ios" &&
   !Platform.isPad &&
   !Platform.isTVOS &&
  (height === 812 || width === 812);

toThis:

const isIphoneXOrAbove =
  Platform.OS === 'ios' &&
  !Platform.isPad &&
  !Platform.isTVOS &&
  ((height === 812 || width === 812) || (height === 896 || width === 896))

export default {
  isIphoneXOrAbove,
  ToolbarHeight: isIphoneXOrAbove ? 37 : 0,
};

And replaced all isIphoneX inside the project to isIphoneXOrAbove

**Comment by davutj** [comment]
Sometimes I can not see shipping methods 

<img width="511" alt="Screen Shot 2019-12-11 at 15 04 43" src="https://user-images.githubusercontent.com/27011602/70668235-de791180-1c27-11ea-88af-7ac8b82fcb41.png">
<img width="511" alt="Screen Shot 2019-12-11 at 15 04 48" src="https://user-images.githubusercontent.com/27011602/70668236-df11a800-1c27-11ea-9771-b088f2818755.png">

How can I solve these?

**Comment by davutj** [comment]
#1568 this bug still exists in android devices
