### ISSUE TITLE
[EvaStore] - Payment screen doesn't show saved cards 

### ISSUE THREAD

**Issue by davutj** [inspireui/support#1576]
1. My issue:
   I can't see my saved cards in payment screen which i can see in website
2. Screenshots issues:
<img width="511" alt="Screen Shot 2019-12-10 at 16 57 22" src="https://user-images.githubusercontent.com/27011602/70582097-289dbc80-1b6e-11ea-9f73-6c86ab105ed0.png">

3. Proof of my purchased:
db599935-bd55-4757-a7c0-fe067f73c256
3. Config files (optional)

**Comment by davutj** [comment]
Also the payment screen is different than the one I see in website

![WhatsApp Image 2019-12-10 at 4 36 26 PM](https://user-images.githubusercontent.com/27011602/70582207-8a5e2680-1b6e-11ea-9623-4b7eaa9dd5a8.jpeg)

**Comment by davutj** [comment]
Also payment screen is different than the one I see in website:
Here is what i see in website
![WhatsApp Image 2019-12-10 at 4 36 26 PM](https://user-images.githubusercontent.com/27011602/70582308-e7f27300-1b6e-11ea-9ff4-ed34ec1f96e3.jpeg)

**Comment by minhcasi** [comment]
@davutj the payment will be difference on the website when you try to process payment mobile on web as well? The Shopify have customized it to fix responsive - this is not a bug - thank you!

**Comment by davutj** [comment]
What about saved credit cards?
