### ISSUE TITLE
Checkout problem

### ISSUE THREAD

**Issue by phcaraujo** [inspireui/support#1577]
Shipping Method

"There is an issue with the app during request the data please contact admin for fixing the issues. Exeption: Recurso inexistente."

PayPal WooCommerce its configured

![Sem título](https://user-images.githubusercontent.com/20992411/70584643-906cfb00-1ba0-11ea-8009-4531d376fbdd.jpg)

clientId e Secret too

**Comment by minhcasi** [comment]
Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads  it's used to verify your proof of purchase? sorry for any inconvenience 

Also, help to share the issue on mobile so that we could have a check - thanks

**Comment by phcaraujo** [comment]
![download](https://user-images.githubusercontent.com/20992411/70586791-e0e75700-1ba6-11ea-970f-74cee5a0e54b.png)

  "DefaultPhoneISOCode": "+55",
  "DefaultCountryISOCode": "BRA"

const List DefaultCountry = [
  {
    "name": "Brazil",
    "iosCode": "BR",
    "icon": "https://cdn.webshopapp.com/shops/94414/files/52123490/flag-of-brazil.jpg"
  }
];

**Comment by phcaraujo** [comment]
![01](https://user-images.githubusercontent.com/20992411/70587089-c82b7100-1ba7-11ea-86f2-4ff1fdb741dd.jpg)
![02](https://user-images.githubusercontent.com/20992411/70587091-c8c40780-1ba7-11ea-903f-a65e861951e0.jpg)
![03](https://user-images.githubusercontent.com/20992411/70587092-c8c40780-1ba7-11ea-886c-28e9f0c8e352.jpg)

**Comment by incepio-flutter** [comment]
you can try to replace getShippingMethods function on services/woo_commerce.dart like this

@override
  Future<List<ShippingMethod>> getShippingMethods(
      {Address address, String token}) async {
    try {
      List<ShippingMethod> list = [];
      var response = await wcApi.getAsync("shipping/zones");
      if (response is Map && isNotBlank(response["message"])) {
        throw Exception(response["message"]);
      } else {
        for (var zone in response) {
          final id = zone["id"];
          var response = await wcApi.getAsync("shipping/zones/$id/methods");
          if (response is Map && isNotBlank(response["message"])) {
            throw Exception(response["message"]);
          } else {
            var res = await wcApi.getAsync("shipping/zones/$id/locations");
            if (res is Map && isNotBlank(res["message"])) {
              throw Exception(res["message"]);
            } else {
              List locations = res;
              bool isValid = true;
              bool checkedPostcode = false;
              locations.forEach((o) {
                if (o["type"] == "country" && isValid) {
                  isValid = address.country == o["code"];
                }
                if (o["type"] == "postcode" &&
                    ((!checkedPostcode && isValid) ||
                        (checkedPostcode && !isValid))) {
                  isValid = address.zipCode == o["code"];
                  checkedPostcode = true;
                }
              });
              if (isValid) {
                for (var item in response) {
                  list.add(ShippingMethod.fromJson(item));
                }
              }
            }
          }
        }
      }
      return list;
    } catch (e) {
      //This error exception is about your Rest API is not config correctly so that not return the correct JSON format, please double check the document from this link https://docs.inspireui.com/fluxstore/woocommerce-setup/
      throw e;
    }
  }

also add shipping zone, payment methods in woocommerce dashboard

**Comment by phcaraujo** [comment]
> you can try to replace getShippingMethods function on services/woo_commerce.dart like this
> 
> @override
> Future<List> getShippingMethods(
> {Address address, String token}) async {
> try {
> List list = [];
> var response = await wcApi.getAsync("shipping/zones");
> if (response is Map && isNotBlank(response["message"])) {
> throw Exception(response["message"]);
> } else {
> for (var zone in response) {
> final id = zone["id"];
> var response = await wcApi.getAsync("shipping/zones/$id/methods");
> if (response is Map && isNotBlank(response["message"])) {
> throw Exception(response["message"]);
> } else {
> var res = await wcApi.getAsync("shipping/zones/$id/locations");
> if (res is Map && isNotBlank(res["message"])) {
> throw Exception(res["message"]);
> } else {
> List locations = res;
> bool isValid = true;
> bool checkedPostcode = false;
> locations.forEach((o) {
> if (o["type"] == "country" && isValid) {
> isValid = address.country == o["code"];
> }
> if (o["type"] == "postcode" &&
> ((!checkedPostcode && isValid) ||
> (checkedPostcode && !isValid))) {
> isValid = address.zipCode == o["code"];
> checkedPostcode = true;
> }
> });
> if (isValid) {
> for (var item in response) {
> list.add(ShippingMethod.fromJson(item));
> }
> }
> }
> }
> }
> }
> return list;
> } catch (e) {
> //This error exception is about your Rest API is not config correctly so that not return the correct JSON format, please double check the document from this link https://docs.inspireui.com/fluxstore/woocommerce-setup/
> throw e;
> }
> }
> 
> also add shipping zone, payment methods in woocommerce dashboard
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/1d558b97f234c93d69c700738dea9d43e3669697/687474703a2f2f67686f73742e6c6f63616c3a383030302f696d616765732f6d6574612f47686f73742d446f63732e6a7067">InspireUI Document**[FluxStore - Universal mobile commerce Flutter app for Magento, WooCommerce and Opencart](http://ghost.local:8000/fluxstore/woocommerce-setup/)**Fluxstore is universal app that fully integration with the Woocommerce, Mangeto and Opencart

Error compile

{ "resource": "/C:/Users/Administrador/Desktop/Projetos Flutter/codecanyon/source/lib/services/woo_commerce.dart", "owner": "dart", "code": "invalid_override", "severity": 8, "message": "'WooCommerce.getShippingMethods' ('Future<List<dynamic>> Function({address: Address, token: String})') isn't a valid override of 'BaseServices.getShippingMethods' ('getShippingMethods').", "source": "dart", "startLineNumber": 297, "startColumn": 3, "endLineNumber": 297, "endColumn": 1871, "tags": [] }

**Comment by phcaraujo** [comment]
address store
![shipping zone](https://user-images.githubusercontent.com/20992411/70640140-4294d900-1c1a-11ea-8d69-bb7e070ed926.jpg)

shipping  zone
![shipping zone 2](https://user-images.githubusercontent.com/20992411/70640138-4294d900-1c1a-11ea-88c5-35829a3c301e.jpg)

checkout paypal
![checkou](https://user-images.githubusercontent.com/20992411/70640136-41fc4280-1c1a-11ea-9c16-d261e18b9af7.jpg)

**Comment by phcaraujo** [comment]
not work

Em qua., 11 de dez. de 2019 às 10:26, incepio-flutter <
notifications@github.com> escreveu:

**Comment by phcaraujo** [comment]
Now another problem
Without me making any code modifications

![error](https://user-images.githubusercontent.com/20992411/70665929-62dd8b80-1c4c-11ea-99aa-c5487580a3f6.jpg)

**Comment by phcaraujo** [comment]
One mistake after another, complicated.

![erro - cloudfirestore](https://user-images.githubusercontent.com/20992411/70667506-cddc9180-1c4f-11ea-92a2-bb646af78d15.jpg)

**Comment by phcaraujo** [comment]
I was able to solve by reinstalling JAVA JRE and SDK.

I still have the same shipping mistake!
Following is the image of the settings.

![ship](https://user-images.githubusercontent.com/20992411/70671904-7133a380-1c5c-11ea-9555-1872ccc04741.png)

### **config.dart**

"EnableShipping": true,
[...]
"ZoneIdShipping": [2],
[...]
const List DefaultCountry = [
  {
    "name": "Brasil",
    "iosCode": "BR",
    "icon": "https://cdn.webshopapp.com/shops/94414/files/52123490/flag-of-brazil.jpg"
  }
];

**Comment by phcaraujo** [comment]
Flutter returns me 2 api urls which are methods and locations

### **methods (yellow)**

https://www.dropestore.com/wp-json/wc/v3/shipping/zones/2/methods?consumer_key=ck_eac89afafdfcf776992b2ef3f2159f43e0e43ec4&consumer_secret=cs_474402820c39938820eec33d9c8b36cad559d0ce

### **locations (red)**

https://www.dropestore.com/wp-json/wc/v3/shipping/zones/2/locations?consumer_key=ck_eac89afafdfcf776992b2ef3f2159f43e0e43ec4&consumer_secret=cs_474402820c39938820eec33d9c8b36cad559d0ce

![json](https://user-images.githubusercontent.com/20992411/70681904-d480fe00-1c7b-11ea-8ec7-7b3d6e1aaa79.png)

### **methods its ok (i think)**

![methods](https://user-images.githubusercontent.com/20992411/70681899-cdf28680-1c7b-11ea-92d9-86ed140c5e47.png)

### **location returns empty**

![location](https://user-images.githubusercontent.com/20992411/70681989-232e9800-1c7c-11ea-8066-904145c91359.png)

### **my app is blank on shipping**

![erro](https://user-images.githubusercontent.com/20992411/70681934-f4182680-1c7b-11ea-877f-924ba2a523ec.jpg)

### **delivery areas on wordpress**

Brasil (location) and PAC (method)
![shipping zone](https://user-images.githubusercontent.com/20992411/70682053-52dda000-1c7c-11ea-939d-0d1306d695c9.png)

### **what do I do?**

**Comment by phcaraujo** [comment]
help?????

**Comment by minhcasi** [comment]
@minhtruong315  - pls help for investigating this issue - thank you!

**Comment by phcaraujo** [comment]
really? two days for a response from someone from support? @minhcasi @minhtruong315

**Comment by minhtruong315** [comment]
@phcaraujo send me config.dart file and admin account via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/1577

**Comment by phcaraujo** [comment]
> @phcaraujo send me config.dart file and admin account via email: [truong@inspireui.com](mailto:truong@inspireui.com)
> with subject: #1577

sent.

**Comment by PolarisSoftDev** [comment]
Hello, Minhcasi
I faced to same problem. I checked the part of source code. 

address.country is empty in getShippingMethods.

**Comment by PolarisSoftDev** [comment]
_openCountryPickerDialog method is not used.

**Comment by PolarisSoftDev** [comment]
At last, I solved the problem.

I added following code snippet in shipping_address.dart file.

  @override
  Widget build(BuildContext context) {
    **_if (DefaultCountry.length == 1){
      address.country = DefaultCountry[0]['iosCode'];
    }_**
    return address == null
        ? Container()
        : Column( ... );
}

**Comment by minhtruong315** [comment]
@phcaraujo You need to replace models/cart.dart file
[cart.dart.zip](https://github.com/inspireui/support/files/3962997/cart.dart.zip)
Change DefaultCountryISOCode in common/config.dart like this
DefaultCountryISOCode: "BR"

**Comment by phcaraujo** [comment]
> @phcaraujo You need to replace models/cart.dart file
> [cart.dart.zip](https://github.com/inspireui/support/files/3962997/cart.dart.zip)
> Change DefaultCountryISOCode in common/config.dart like this
> DefaultCountryISOCode: "BR"

not work
![Sem título](https://user-images.githubusercontent.com/20992411/70837953-c26e9f00-1de4-11ea-8248-51d5e7db8fa0.jpg)

**Comment by phcaraujo** [comment]
> At last, I solved the problem.
> 
> I added following code snippet in shipping_address.dart file.
> 
> @override
> Widget build(BuildContext context) {
> **_if (DefaultCountry.length == 1){ address.country = DefaultCountry[0]['iosCode']; }_**
> return address == null
> ? Container()
> : Column( ... );
> }
> 
> @ Oleksandr Palievev

it worked, thank you!
can you help me with another problem?

@minhcasi @minhtruong315 @PolarisSoftDev 

i set up paypal as per the documentation https://docs.inspireui.com/fluxstore/multi-payment/

app configuration ClientID and Secret

![sandbox](https://user-images.githubusercontent.com/20992411/70839151-32335880-1dea-11ea-9943-fa73f8c96bd2.png)

account Sandbox

![sandbox api](https://user-images.githubusercontent.com/20992411/70839197-5a22bc00-1dea-11ea-8348-de04be14f237.png)

wp configuration
(Enable PayPal sandbox (enabled))

![sandbox wp](https://user-images.githubusercontent.com/20992411/70839203-6149ca00-1dea-11ea-9edc-bb2d28c80bba.png)

if "production": true in config.dart
return error (Invalid argument)

![erro2](https://user-images.githubusercontent.com/20992411/70839246-8fc7a500-1dea-11ea-8791-ca24275afa16.jpg)

if "production": false in config.dart
return error (Alguns dados informados estão incorretos. Tente novamente)
even if the paypal account email and password are correct

![erro1](https://user-images.githubusercontent.com/20992411/70839275-b980cc00-1dea-11ea-994d-36aeb452ec56.jpg)

**Comment by minhcasi** [comment]
please also try to update the app to the latest version 1.6, there is some bug fix and compatible with Flutter 1.12 - Detail changelog will be updated from https://medium.com/@inspireui/announcing-fluxstore-1-6-337efff1791f - thank you!

**Comment by phcaraujo** [comment]
Product page not work in Fluxstore 1.6

![04d139ed-f01f-4498-be23-82f1be64ce56](https://user-images.githubusercontent.com/20992411/70851551-5daf5500-1e75-11ea-91a1-041b8d7bb746.jpg)

![error](https://user-images.githubusercontent.com/20992411/70851568-87687c00-1e75-11ea-9e2a-b7765ee6a625.png)

**Comment by phcaraujo** [comment]
config.dart fluxstore 1.6
product page not work.

Em sáb., 14 de dez. de 2019 às 09:10, Minh Pham <notifications@github.com>
escreveu:

**Comment by phcaraujo** [comment]
i sent config.dart back to the @minhtruong315

**Comment by phcaraujo** [comment]
will anyone help?

@minhcasi @minhtruong315

**Comment by incepio-flutter** [comment]
@phcaraujo  try wraping it in an expandable Widget .

**Comment by minhtruong315** [comment]
[product_title.dart.zip](https://github.com/inspireui/support/files/3970648/product_title.dart.zip)
pls replace screens/detail/product_title.dart to fix that issue

**Comment by PolarisSoftDev** [comment]
Hello,

I have a problem with paypal integration.

![Screenshot_2](https://user-images.githubusercontent.com/53799370/70953932-daa81d80-2073-11ea-832f-ce98724bba50.png)

I checked it in website.

![Screenshot_3](https://user-images.githubusercontent.com/53799370/70953975-0a572580-2074-11ea-84e9-92f1c4170f19.png)

When I click "Proceed to checkout" button, it opens this url (https://tiabo.co/mstore-checkout/).
But it doesn't work.

https://tiabo.co/checkout/
I think it opens this url. But I can't fix the issue.

Please help me.

**Comment by PolarisSoftDev** [comment]
Hi, Phcaraujo

Is it work fine with paypal now?

**Comment by phcaraujo** [comment]
> Hi, Phcaraujo
> 
> Is it work fine with paypal now?

Yes, but i have error generating apk now #1625

**Comment by minhtruong315** [comment]
ok. I will check it.
