### ISSUE TITLE
ListPro - Fluxstore no loading images

### ISSUE THREAD

**Issue by Cubymercado** [inspireui/support#1578]
**1.** 
Hi there, just wondering what’s happening with the app – it does not run properly with listing pro Wordpress theme, not even with the test demo data. 
Images don’t show at all on the app.
MSstore plugin can not be installed on Wordpress either. Error on line 21 on PHP file.

Would highly appreciate your help. Thanks

**2.** 
![Simulator Screen Shot - iPhone 11 Pro - 2019-12-11 at 13 21 41](https://user-images.githubusercontent.com/14897346/70593777-3e1bf080-1c19-11ea-80c0-3deaec4f8aef.png)
![Simulator Screen Shot - iPhone 11 Pro - 2019-12-11 at 13 21 44](https://user-images.githubusercontent.com/14897346/70593778-3e1bf080-1c19-11ea-9f20-c8b689a9c61e.png)

**3.**
<img width="803" alt="Screenshot 2019-12-11 at 1 18 52 PM" src="https://user-images.githubusercontent.com/14897346/70593641-c9e14d00-1c18-11ea-92ee-0538e71068d6.png">

**4.** JSON
{
  "HorizonLayout": [
    {
      "layout": "logo",
      "hideLogo": true
    },
    {
      "layout": "header_search",
      "radius": 3.0,
      "text": {
        "en": "Search for a product",
        "ab": "بلوق وظائف",
        "vi": "Tìm kiếm"
      }
    },

    {
      "layout": "header_text",
      "fontSize": 20.0,
      "padding": 20.0,
      "height": 0.1,
      "title": "What can we help you find?"
    },

    {
      "layout": "category",
      "type": "image",
      "size": 1.0,
      "radius": 50.0,
      "items": [
        {
          "category": 14,
          "showText": true,
          "name": "Automotive"
        },
        {
          "category": 27,
          "showText": true,
          "name": "Real Estate"
        },
        {
          "category": 29,
          "showText": true,
          "name": "Restaurant"
        },
        {
          "category": 23,
          "showText": true,
          "name": "Sales"
        },
        {
          "category": 31,
          "showText": true,
          "name": "Services"
        },
        {
          "category": 32,
          "showText": true,
          "name": "Shopping"
        }
      ]
    },
    {
      "name": {
        "en": "Most Visited Places",
        "ar": "Most Visited Places"
      },
      "description": {
        "en": "A selection of homes verified for quality and design",
        "ar": "مجموعة مختارة من المنازل التحقق من الجودة والتصميم"
      },
      "layout": "twoColumn",
      "category": 40
    }
  ],
  "Setting": {
    "MainColor": "#FA9200",
    "ProductListLayout": "list"
  },
  "TabBar": [
    {
      "layout": "home",
      "icon": "assets/icons/tabs/icon-home.png"
    },
    {
      "layout": "category",
      "categoryLayout": "card",
      "icon": "assets/icons/tabs/icon-category.png"
    },
    {
      "layout": "search",
      "icon": "assets/icons/tabs/icon-search.png"
    },
    {
      "layout": "profile",
      "icon": "assets/icons/tabs/icon-user.png"
    }
  ]
}

**Comment by minhcasi** [comment]
@Cubymercado - could you help to share the config.dart file as well - you can also email private to truong@inspireui.com - we will help for checking and get back you shortly - very best!

**Comment by minhcasi** [comment]
Also, mark as high priory ticket support as well as you are our most valuable customer - pls help to share your config file soon 🤴

**Comment by Cubymercado** [comment]
Thanks mate appreciate it, I will email you the dart file soon

**Comment by minhcasi** [comment]
@Cubymercado @minhtruong315 - please help to update the status on this ticket - thank you!

**Comment by parveenkrraina** [comment]
I am also facing the same isuue, images are not loading. Installed the thubmnail generator and generated the thumbnail, but still its not loading the images. From the console I can see the URL its hitting ans while browsing it, its showing the images and when I open the URL in the browser, images are available, but not in the app.

![Snag_96805eb](https://user-images.githubusercontent.com/41342012/71073622-bef16400-21a6-11ea-8fa1-b69486f9b28b.png)
![Snag_968ab43](https://user-images.githubusercontent.com/41342012/71073681-d7fa1500-21a6-11ea-99af-5ee47f1c9b7c.png)
@minhcasi
