### ISSUE TITLE
[Fluxstore Pro] - SMS Login issue when building ios app

### ISSUE THREAD

**Issue by Alnaggar94** [inspireui/support#1579]
1. My issue:

Hello, I followed the video in your youtube channel on how to setup SMS Login by Firebase Auth, It's working fine in the android simulator and real android device,  but in ios can't build the app it shows me failed to build with the following error (see screenshot) 

2. Screenshots issues:

screenshot - https://imgur.com/bAhQpAR

3. Proof of my purchased:

https://imgur.com/a/9TsYcIf

3. Config files (optional)

Config.dart - https://www.dropbox.com/s/72t930zc26wlg9m/config.dart?dl=0

Config.json - https://www.dropbox.com/s/gkfym2audyj0vvy/config.json?dl=0
Config_ar.json - https://www.dropbox.com/s/x8m73j714ou9x3d/config_ar.json?dl=0

**Comment by minhcasi** [comment]
@minhtruong315 - pls help for a suggestion

**Comment by minhtruong315** [comment]
@Alnaggar94 add my skype: minhtruong315
I will help u check via teamviewer

**Comment by Alnaggar94** [comment]
@minhtruong315  I added you in skype my skype id : alnaggar.saleh

**Comment by Alnaggar94** [comment]
It's been 5 days without any reply? please reply to me on skype or here.

**Comment by minhcasi** [comment]
@Alnaggar94 - let me check with Truong, thank you for your patient 

@minhtruong315  - please help for checking

**Comment by minhtruong315** [comment]
@Alnaggar94 I replied on skype

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!

**Comment by minhtruong315** [comment]
supported
