### ISSUE TITLE
CeBuilder error on building android app 

### ISSUE THREAD

**Issue by jig0009** [inspireui/support#158]
**Mandatory Info (please complete the following information):**
 - Product: [e.g. MStore]
 - Your Purchased Code: [e270ed9b-9841-4ab4-9ca4-dce01ecdd14e]

**Describe the issues**
CeBuilder error on building android app 

[20:51:30] Making sure project is set up correctly...
|[20:51:30] Error: Missing app.json. See https://docs.expo.io/
/[20:51:31] There is an error with your project. See above logs for information.
[20:51:31] Set EXPO_DEBUG=true in your env to view the stack trace.

app.json file already on project help me out 
*Screenshots**
https://mega.nz/#!enwAHYYb!gJgEJIGKHLZHYnwrKdZjL-XBQbSXMQMOyKA7Gx0xdi4

**Additional context**
Add any other detail logs about the problem here.

**Comment by minhtruong315** [comment]
Hi @jig0009 I find that your folder name have space, please change it. "mstore new" to "mstore_new"

**Comment by minhtruong315** [comment]
Hi @jig0009 you can try to make source code to C disk, then try again

**Comment by jig0009** [comment]
building android app error show me enter apple id but i'm trying to build an android app

https://mega.nz/#!q3hUwChJ!DZpHNtW994UQ1SsnGoQCmoCOkr8no1bw9ty3Lyavq3E

**Comment by Lubrig2** [comment]
Yes. Please tell us how to build only android app when we haven't apple dev ID.

**Comment by minhcasi** [comment]
Fixed on v.0.26.1 - thank you!
