### ISSUE TITLE
Required Opencart Config files

### ISSUE THREAD

**Issue by piyushjainpc** [inspireui/support#1581]
Dear Team,
Files included in the package for opencart config are not working. Kindly recheck and give me the updated files to solve the issue.

**Comment by minhcasi** [comment]
@minhtruong315 - could be related to our new update on config language - pls help for checking

**Comment by minhtruong315** [comment]
[opencart.zip](https://github.com/inspireui/support/files/3954666/opencart.zip)
try this config

**Comment by piyushjainpc** [comment]
![Screenshot 2019-12-13 at 11 09 12 PM](https://user-images.githubusercontent.com/31863908/70820094-ceb32600-1dfd-11ea-81c2-f837d8512bc6.png)
Kindly check the error and give me best solution for the same.

**Comment by minhtruong315** [comment]
@piyushjainpc pls zip source code and send it via my email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/1581

**Comment by minhtruong315** [comment]
@piyushjainpc pls update the latest source code. thanks

**Comment by piyushjainpc** [comment]
Hi I have updated the same but still it is not working...
