### ISSUE TITLE
[Fluxstore woocomerce] - 

### ISSUE THREAD

**Issue by codingastronaut** [inspireui/support#1582]
1. My issue:

a)is there other layout except for the default blog layout for the blog section?
b)featured image on blog post blurry
c)how to embed videos from youtube or  and mp3 into blog post

3. Proof of my purchased:

![Annotation 2019-11-21 050939](https://user-images.githubusercontent.com/17095995/70619030-74a33c80-1c14-11ea-9431-f7235b8c79b7.jpg)

3. Config files (optional)

**Comment by codingastronaut** [comment]
please i need response asap if you can. thanks

**Comment by codingastronaut** [comment]
@minhcasi

**Comment by codingastronaut** [comment]
hello, please i need a reply as soon as possible, sorry for the multiple messages, its very urgent @minhcasi @luyx2412 @vumanhsn97

**Comment by codingastronaut** [comment]
hello? please help me out here @minhcasi @luyx2412 @vumanhsn97

**Comment by minhcasi** [comment]
a)is there other layout except for the default blog layout for the blog section? - no at current release 

b)featured image on blog post blurry - you can use the Inspector to know the image widget and increase the image size to the large one - https://docs.inspireui.com/fluxstore/useful-tip/

c)how to embed videos from youtube or and mp3 into blog post - try to embed via iframe, but we are not sure if it works, the team is working on new video features and keep an update on next release

**Comment by minhcasi** [comment]
please try to update the app to the latest version 1.6, there is some bug fix and compatible with Flutter 1.12 - Detail changelog will be updated from https://medium.com/@inspireui/announcing-fluxstore-1-6-337efff1791f - thank you!
