### ISSUE TITLE
Code not compile

### ISSUE THREAD

**Issue by kishor-navale** [inspireui/support#1583]
Hi, I purchased Fluxstore them for our product but I not able to run it, it give errors while compiling,  what should I do now? where can I get help. 

![Screenshot from 2019-12-04 19-01-06](https://user-images.githubusercontent.com/58774845/70620682-e93ea100-1c3d-11ea-8e98-f2567c8caa44.png)

**Comment by kishor-navale** [comment]
Launching lib/main.dart on Redmi Note 5 Pro in debug mode...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

Compiler message:
../../../../Public/Program%20Files/flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-1.1.3/lib/src/cached_network_image_provider.dart:42:24: Error: The method 'CachedNetworkImageProvider.load' has fewer positional arguments than those of overridden method 'ImageProvider.load'.
  ImageStreamCompleter load(CachedNetworkImageProvider key) {
                       ^
../../../../Public/Program%20Files/flutter/packages/flutter/lib/src/painting/image_provider.dart:403:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(T key, DecoderCallback decode);
                       ^
../../../../Public/Program%20Files/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image_library-0.1.8/lib/src/extended_memory_image_provider.dart:12:24: Error: The method 'ExtendedMemoryImageProvider.load' has fewer positional arguments than those of overridden method 'MemoryImage.load'.
  ImageStreamCompleter load(MemoryImage key) {
                       ^
../../../../Public/Program%20Files/flutter/packages/flutter/lib/src/painting/image_provider.dart:704:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(MemoryImage key, DecoderCallback decode) {
                       ^
../../../../Public/Program%20Files/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image_library-0.1.8/lib/src/extended_file_image_provider.dart:13:24: Error: The method 'ExtendedFileImageProvider.load' has fewer positional arguments than those of overridden method 'FileImage.load'.
  ImageStreamCompleter load(FileImage key) {
                       ^
../../../../Public/Program%20Files/flutter/packages/flutter/lib/src/painting/image_provider.dart:636:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(FileImage key, DecoderCallback decode) {
                       ^
../../../../Public/Program%20Files/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image_library-0.1.8/lib/src/extended_asset_bundle_image_provider.dart:35:24: Error: The method 'ExtendedExactAssetImageProvider.load' has fewer positional arguments than those of overridden method 'AssetBundleImageProvider.load'.
  ImageStreamCompleter load(AssetBundleImageKey key) {
                       ^
../../../../Public/Program%20Files/flutter/packages/flutter/lib/src/painting/image_provider.dart:467:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(AssetBundleImageKey key, DecoderCallback decode) {
                       ^
../../../../Public/Program%20Files/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image_library-0.1.8/lib/src/extended_asset_bundle_image_provider.dart:87:24: Error: The method 'ExtendedAssetImageProvider.load' has fewer positional arguments than those of overridden method 'AssetBundleImageProvider.load'.
  ImageStreamCompleter load(AssetBundleImageKey key) {
                       ^
../../../../Public/Program%20Files/flutter/packages/flutter/lib/src/painting/image_provider.dart:467:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(AssetBundleImageKey key, DecoderCallback decode) {
                       ^
../../../../Public/Program%20Files/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image_library-0.1.8/lib/src/extended_network_image_provider.dart:62:24: Error: The method 'ExtendedNetworkImageProvider.load' has fewer positional arguments than those of overridden method 'ImageProvider.load'.
  ImageStreamCompleter load(ExtendedNetworkImageProvider key) {
                       ^
../../../../Public/Program%20Files/flutter/packages/flutter/lib/src/painting/image_provider.dart:403:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(T key, DecoderCallback decode);
                       ^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script '/home/kishor/Public/Program Files/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 776

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/home/kishor/Public/Program Files/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org

BUILD FAILED in 1m 28s
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by incepio-flutter** [comment]
have you tried flutter doctor and flutter upgrade in terminal?

**Comment by kishor-navale** [comment]
Yes I did.

**Comment by kishor-navale** [comment]
I have tried flutter doctor and flutter upgrade in terminal, but same error it gave...?

**Comment by kishor-navale** [comment]
Can you help?

**Comment by incepio-flutter** [comment]
try to change min and target sdk versions this might solve your problem

**Comment by minhcasi** [comment]
@kishor-navale - pls try to use Android Studio and there is the SDK config as this common issues guide - https://docs.inspireui.com/fluxstore/common-question/

Also, try to run "flutter clean" and reinstall the project.

Let us know your checking - thanks

**Comment by minhcasi** [comment]
Please try to update the app to the latest version 1.6, there is some bug fix and compatible with Flutter 1.12 - Detail changelog will be updated from https://medium.com/@inspireui/announcing-fluxstore-1-6-337efff1791f - thank you!
