### ISSUE TITLE
Fluxstore Pro Opencart not working

### ISSUE THREAD

**Issue by kurkuteabhi** [inspireui/support#1584]
I am starting opencart based app but getting issue as show in screenshot. I have also tried your demo web for demo purpose config.dart and config.json is as it is from example folder 
---------

![purches](https://user-images.githubusercontent.com/43174699/70621221-18094700-1c3f-11ea-8ab9-81f8246c9a39.jpg)
![Screenshot_1575688530](https://user-images.githubusercontent.com/43174699/70621222-18094700-1c3f-11ea-8faa-aceb564a3764.png)

**Comment by minhcasi** [comment]
@minhtruong315 - please help for checking

**Comment by minhtruong315** [comment]
[opencart.zip](https://github.com/inspireui/support/files/3954661/opencart.zip)
try this config

**Comment by kurkuteabhi** [comment]
**After updating config file and Flutter package** 

Running "flutter pub get" in source...                             67.7s
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
I/flutter ( 5194): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 5194): The following assertion was thrown building Consumer<AppModel>(dirty, dependencies:
I/flutter ( 5194): [InheritedProvider<AppModel>]):
I/flutter ( 5194): 'dart:ui/window.dart': Failed assertion: line 281: '<optimized out>': is not true.
I/flutter ( 5194): 
I/flutter ( 5194): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 5194): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 5194): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 5194):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter ( 5194): 
I/flutter ( 5194): User-created ancestor of the error-causing widget was:
I/flutter ( 5194):   InheritedProvider<AppModel>
I/flutter ( 5194):   file:///C:/src/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/provider-3.1.0+1/lib/src/listenable_provider.dart:86:12
I/flutter ( 5194): 
I/flutter ( 5194): When the exception was thrown, this was the stack:
I/flutter ( 5194): #2      new Locale (dart:ui/window.dart:281:15)
I/flutter ( 5194): #3      AppState.build.<anonymous closure> (package:fstore/app.dart:183:27)
I/flutter ( 5194): #4      Consumer.build (package:provider/src/consumer.dart:180:12)
I/flutter ( 5194): #5      StatelessElement.build (package:flutter/src/widgets/framework.dart:4009:28)
I/flutter ( 5194): #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3941:15)
I/flutter ( 5194): #7      Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
I/flutter ( 5194): #8      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2348:33)
I/flutter ( 5194): #9      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:760:20)
I/flutter ( 5194): #10     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:280:5)
I/flutter ( 5194): #11     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1033:15)
I/flutter ( 5194): #12     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:975:9)
I/flutter ( 5194): #13     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:891:5)
I/flutter ( 5194): #17     _invoke (dart:ui/hooks.dart:249:10)
I/flutter ( 5194): #18     _drawFrame (dart:ui/hooks.dart:207:3)
I/flutter ( 5194): (elided 5 frames from class _AssertionError and package dart:async)
I/flutter ( 5194): 
I/flutter ( 5194): ════════════════════════════════════════════════════════════════════════════════════════════════════
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

Compiler message:
../Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-1.1.3/lib/src/cached_network_image_provider.dart:42:24: Error: The method 'CachedNetworkImageProvider.load' has fewer positional arguments than those of overridden method 'ImageProvider.load'.
  ImageStreamCompleter load(CachedNetworkImageProvider key) {
                       ^
../Flutter/flutter/packages/flutter/lib/src/painting/image_provider.dart:403:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(T key, DecoderCallback decode);
                       ^
../Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image_library-0.1.8/lib/src/extended_memory_image_provider.dart:12:24: Error: The method 'ExtendedMemoryImageProvider.load' has fewer positional arguments than those of overridden method 'MemoryImage.load'.
  ImageStreamCompleter load(MemoryImage key) {
                       ^
../Flutter/flutter/packages/flutter/lib/src/painting/image_provider.dart:704:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(MemoryImage key, DecoderCallback decode) {
                       ^
../Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image_library-0.1.8/lib/src/extended_file_image_provider.dart:13:24: Error: The method 'ExtendedFileImageProvider.load' has fewer positional arguments than those of overridden method 'FileImage.load'.
  ImageStreamCompleter load(FileImage key) {
                       ^
../Flutter/flutter/packages/flutter/lib/src/painting/image_provider.dart:636:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(FileImage key, DecoderCallback decode) {
                       ^
../Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image_library-0.1.8/lib/src/extended_asset_bundle_image_provider.dart:35:24: Error: The method 'ExtendedExactAssetImageProvider.load' has fewer positional arguments than those of overridden method 'AssetBundleImageProvider.load'.
  ImageStreamCompleter load(AssetBundleImageKey key) {
                       ^
../Flutter/flutter/packages/flutter/lib/src/painting/image_provider.dart:467:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(AssetBundleImageKey key, DecoderCallback decode) {
                       ^
../Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image_library-0.1.8/lib/src/extended_asset_bundle_image_provider.dart:87:24: Error: The method 'ExtendedAssetImageProvider.load' has fewer positional arguments than those of overridden method 'AssetBundleImageProvider.load'.
  ImageStreamCompleter load(AssetBundleImageKey key) {
                       ^
../Flutter/flutter/packages/flutter/lib/src/painting/image_provider.dart:467:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(AssetBundleImageKey key, DecoderCallback decode) {
                       ^
../Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image_library-0.1.8/lib/src/extended_network_image_provider.dart:62:24: Error: The method 'ExtendedNetworkImageProvider.load' has fewer positional arguments than those of overridden method 'ImageProvider.load'.
  ImageStreamCompleter load(ExtendedNetworkImageProvider key) {
                       ^
../Flutter/flutter/packages/flutter/lib/src/painting/image_provider.dart:403:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(T key, DecoderCallback decode);
                       ^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\Flutter\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 780

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\Flutter\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 52s
Finished with error: Gradle task assembleDebug failed with exit code 1
![Annotation 2019-12-12 193957](https://user-images.githubusercontent.com/43174699/70718985-42c6ce80-1d17-11ea-9d46-f4410e1e2820.jpg)

**Comment by minhtruong315** [comment]
[pubspec.yaml.zip](https://github.com/inspireui/support/files/3958200/pubspec.yaml.zip)
try this

**Comment by kurkuteabhi** [comment]
Thanks for your great help. Now app is running on Your Demo OpenCart as well as fresh OC installation at https://ezmarts.in . but i have more three issues with app as below 
1) Opencart Categories not loading 
(refer screenshot)

2) Error while checkout as `FormatException: Unexpected end of input (at character 1) ^ `
(refer screenshot)

3) app stuck at splash-screen with my own flare animation, animation available https://rive.app/a/kurkute.abhi/files/flare/e-zmart/preview 
static PNG splash-screen work fine

![Screenshot_1576254454](https://user-images.githubusercontent.com/43174699/70818291-55193900-1df9-11ea-96c9-4e27377ad3ce.png)
![Screenshot_1576255905](https://user-images.githubusercontent.com/43174699/70818294-55b1cf80-1df9-11ea-9b89-a31c9e0880ba.png)

**Comment by kurkuteabhi** [comment]
Thanks for your great help. Now app is running on Your Demo OpenCart as well as fresh OC installation at https://ezmarts.in . but i have more three issues with app as below 
1) Opencart Categories not loading 
(refer screenshot)

2) Error while checkout as `FormatException: Unexpected end of input (at character 1) ^ `
(refer screenshot)

3) app stuck at splash-screen with my own flare animation, animation available https://rive.app/a/kurkute.abhi/files/flare/e-zmart/preview 
static PNG splash-screen work fine

![Screenshot_1576254454](https://user-images.githubusercontent.com/43174699/70818291-55193900-1df9-11ea-96c9-4e27377ad3ce.png)
![Screenshot_1576255905](https://user-images.githubusercontent.com/43174699/70818294-55b1cf80-1df9-11ea-9b89-a31c9e0880ba.png)

**Comment by minhcasi** [comment]
Please try to update the app to the latest version 1.6, there is some bug fix and compatible with Flutter 1.12 - Detail changelog will be updated from https://medium.com/@inspireui/announcing-fluxstore-1-6-337efff1791f - thank you!

**Comment by KhanJahanzaib** [comment]
Hey Sir.I have added the mstore extension in my store http://dikaken.com/shop/, How ever it not working .kindly guide me
