### ISSUE TITLE
[Fluxstore Pro] - FCM Push Notification not received when app is closed

### ISSUE THREAD

**Issue by shafirmubarak** [inspireui/support#1585]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: FCM Push Notification not received when app is closed. But it's working fine when the app is in background.

2. Screenshots issues: N/A

3. Proof of my purchased: 
![image](https://user-images.githubusercontent.com/53738841/70626905-468d1f00-1c4b-11ea-9913-65efb1f7c186.png)
 

3. Config files (optional)

Kindly help with this and do the needful.

**Comment by minhcasi** [comment]
@minhtruong315 - please help for checking - thank you!

**Comment by shafirmubarak** [comment]
Can someone please help on this ?

**Comment by minhtruong315** [comment]
I will fix this case. Then send you the solution

**Comment by minhcasi** [comment]
Please try to update the app to the latest version 1.6, there is some bug fix and compatible with Flutter 1.12 - Detail changelog will be updated from https://medium.com/@inspireui/announcing-fluxstore-1-6-337efff1791f - thank you!

**Comment by shafirmubarak** [comment]
@minhcasi  , thanks for getting back on this. Could you please help with the exact change related to this specific issue. Am asking because i have bit of customization on older version so am afraid I can't directly upgrade to 1.6. So if you could suggest / outline the changes related to enabling the push notification when App is terminated. I will update the same in my code. Much appreciated. Thanks!
