### ISSUE TITLE
[MStore Pro] - crash with arabic language

### ISSUE THREAD

**Issue by 007asom** [inspireui/support#1586]
---------

1. My issue:
crash when switching language.
2. Screenshots issues:

3. Proof of my purchased:
https://ibb.co/PNBWpYy
3. Config files (optional)

Hi
I still face a problem when I change the language to Arabic. the crash only with the Release version.
this is the error log.
https://github.com/inspireui/support/issues/1361#issuecomment-557778148
this is the solution you give it to me, but still the same problem. 
https://github.com/inspireui/support/issues/1361#issuecomment-558083359

**Comment by minhcasi** [comment]
@007asom - could I have a check if you are using the latest Mstore version?

**Comment by 007asom** [comment]
> @007asom - could I have a check if you are using the latest Mstore version?

yes

**Comment by 007asom** [comment]
Hello
Do you need any other information?

**Comment by minhcasi** [comment]
move to #1586
