### ISSUE TITLE
[BeoNews] - Can't run the app after completing the prerequisite setup

### ISSUE THREAD

**Issue by dermayank** [inspireui/support#1587]
I have followed all the initial setup step of beonews. 
On running react-native run-android this is the error I'm getting

![Screenshot from 2019-12-12 11-50-28](https://user-images.githubusercontent.com/24271097/70687617-bd6efa00-1cd5-11ea-9379-1be44d0930ec.png)

I have even set the path to SDK:
![Screenshot from 2019-12-12 11-04-50](https://user-images.githubusercontent.com/24271097/70685495-9d3c3c80-1ccf-11ea-9c4e-b096d78375d5.png)

My purchase proof
![Screenshot from 2019-12-04 10-30-36](https://user-images.githubusercontent.com/24271097/70646149-549f6780-1c6c-11ea-85ae-1d5192217f0c.png)

**Comment by minhcasi** [comment]
@concuacon - pls help for suggest on this issue

**Comment by dermayank** [comment]
@minhcasi  this is the step where it is failing a lot of time.
