### ISSUE TITLE
[MStore] install

### ISSUE THREAD

**Issue by antixirus** [inspireui/support#1588]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: Can't add item to cart, no action if i click icon cart

2. Screenshots issues:don't have it because no error message appears, but the basket icon can't be pushed

3. Proof of my purchased:
![Capture](https://user-images.githubusercontent.com/57300649/70672853-124d4900-1cb3-11ea-875d-30d8323b1800.PNG)

3. Config files (optional)

**Comment by minhcasi** [comment]
Hi, could you share the screenshot from the terminal when you run the app?

You can also try to run the Mstore app with CeBuilder tools - http://inspireui.com/

**Comment by antixirus** [comment]
I think i stop develop the app sir, and change to Fluxstore MV next monday
