### ISSUE TITLE
Fluxstore - Flutter

### ISSUE THREAD

**Issue by Sourabhgoyal** [inspireui/support#1590]
1. My issue:
The checkout process is not working in opencart.
We have tried both guest checkout and existing user checkout.It just hangs and loads forever
2. Screenshots issues:
![screenshot](https://user-images.githubusercontent.com/11677061/70703621-7fce9900-1cf6-11ea-824f-8676325ad7aa.jpg)

3. Proof of my purchased:
ccdec22e-845a-4851-b065-2375e3b9cd37
3. Config files (optional)

**Comment by minhtruong315** [comment]
@Sourabhgoyal can you send me your source code via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/1590

**Comment by minhtruong315** [comment]
@Sourabhgoyal pls download the latest source code to fix this issue

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
