### ISSUE TITLE
[Fluxstore] - Getting issue error for running / building app

### ISSUE THREAD

**Issue by spikyeagle** [inspireui/support#1591]
Purchased code: bcbdf121-ee89-4d06-b6af-ffea672ad985

Compiler message:
/C:/Users/DELL/flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-1.1.3/lib/src/cached_network_image_provider.dart:42:24: Error: The method 'CachedNetworkImageProvider.load' has fewer positional arguments than those of overridden method 'ImageProvider.load'.
  ImageStreamCompleter load(CachedNetworkImageProvider key) {
                       ^
/C:/Users/DELL/flutter/packages/flutter/lib/src/painting/image_provider.dart:403:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(T key, DecoderCallback decode);
                       ^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\DELL\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 780

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\Users\DELL\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 39s
Finished with error: Gradle task assembleDebug failed with exit code 1

(( Flutter doctor -v ))
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.535], locale en-US)
    • Flutter version 1.12.13+hotfix.5 at C:\Users\DELL\flutter
    • Framework revision 27321ebbad (34 hours ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\DELL\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!

**Comment by minhtruong315** [comment]
[pubspec.yaml.zip](https://github.com/inspireui/support/files/3958555/pubspec.yaml.zip)
pls update packages again

**Comment by spikyeagle** [comment]
Running "flutter pub get" in source...                          
CreateProcessW failed 32

The process cannot access the file because it is being used by another process.



  Command: C:\Users\DELL\flutter\bin\cache\dart-sdk\lib\_internal\pub\asset\7zip\7za.exe e data.tar.gz
pub get failed (1;   Command: C:\Users\DELL\flutter\bin\cache\dart-sdk\lib\_internal\pub\asset\7zip\7za.exe e data.tar.gz)


! still error cannot !

**Comment by minhtruong315** [comment]
add my skype: minhtruong315
I will help u check via teamviewer

**Comment by minhcasi** [comment]
@spikyeagle  - please try to update the app to the latest version 1.6, there is some bug fix and compatible with Flutter 1.12 - Detail changelog will be updated from https://medium.com/@inspireui/announcing-fluxstore-1-6-337efff1791f - thank you!

**Comment by spikyeagle** [comment]
not working ! and cannot be build ! now its really over to wait 7 days support very bad

**Comment by minhcasi** [comment]
@spikyeagle - could you share your latest detail error so that we could help for checking?

Could you run "flutter doctor -v" and check if there is any error? Please make sure to update your Flutter to the latest version by run "flutter upgrade"

If you are not happy with the product so far, we could refund the purchased - thank you for your patient

**Comment by minhtruong315** [comment]
@spikyeagle did you add my skype? I dont see any request on the skype

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!

**Comment by minhtruong315** [comment]
supported

**Comment by minhcasi** [comment]
@spikyeagle - any result input?

**Comment by minhtruong315** [comment]
I'm sorry for closing issue by accidence as i've supported the similar ticket 1579 successful but close this wrong issue - i've contacted you on Skype again for supporting

**Comment by spikyeagle** [comment]
Big drama lol ! all team liars and refuse to help

**Comment by minhcasi** [comment]
@spikyeagle - if we refused to help there will no-reply above comment, you can submit a refund to save your money and time instead of comment negative words

**Comment by wiktoriasobczyk** [comment]
I have the same problem :(
