### ISSUE TITLE
[fluxstore] Listeo issue

### ISSUE THREAD

**Issue by buliservice** [inspireui/support#1592]
Hi,

The app doesn't show images because there is no full image url in the listing api.

As you can see here: https://wp2.perfectlawyer.co.uk/wp-json/wp/v2/listing

The demo listings have full image urls, while the new listings don't.

So that means that when someone submits a new listing doesn't show the full image url.

It would be great if you could help me with this issue. Thanks a lot.

**Comment by minhcasi** [comment]
Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads  it's used to verify your proof of purchase? sorry for any inconvenience - Thank you!

**Comment by buliservice** [comment]
hi,

please find attached the screenshot.

**Comment by minhcasi** [comment]
@buliservice - sorry it seems you have forgot attache the file :)

**Comment by buliservice** [comment]
![2FE0CB15-05A1-4E7A-8FDE-21B81DDB62BA](https://user-images.githubusercontent.com/58818767/70907735-8a907300-2001-11ea-82e5-5b6717b9d409.png)

hi, sorry it is attached now. Thanks

**Comment by minhcasi** [comment]
@buliservice - could i check if you have install this plugin to latest one - https://wordpress.org/plugins/listapp-mobile-manager/

Then it will work as the same on our demo http://listeo.inspireui.com/wp-json/wp/v2/listing

**Comment by buliservice** [comment]
Hi Minh,


I installed the plugin, nothing changed.

Can you add a new listing on your demo? With the demo content it works for
me too. But when I add a new listing it doesn’t.

Regards,

Tamas

**Comment by minhcasi** [comment]
@buliservice - sorry for the late response, is it possible to share your admin login so that we could help for checking the integration, it seems there is missing some config but we could figure out, pls send to support@inspireui.com and manh@inspireui.com - thank you!

**Comment by vumanhsn97** [comment]
@buliservice 
Change files:
- lib/models/product.dart to 
[product.dart.zip](https://github.com/inspireui/support/files/3993842/product.dart.zip)
- lib/services/listing.dart to 
[listing.dart.zip](https://github.com/inspireui/support/files/3993844/listing.dart.zip)

**Comment by buliservice** [comment]
Thank you very much. It works.

vumanhsn97 <notifications@github.com> ezt írta (időpont: 2019. dec. 23., H,
6:13):

**Comment by minhcasi** [comment]
@buliservice We're glad that it help for resolving the issue. Kindly help us to give some feedback & rating to - http://codecayon.net/downloads

I hope you have success with the app, and if you have any more issues don't hesitate to add new ticket support - thank you!
