### ISSUE TITLE
[Mstore Pro] - Shipping Based Weight & Currency Plugin

### ISSUE THREAD

**Issue by Q8hma** [inspireui/support#1593]
1. My issue:
hello , is it support Shipping Based Weight and Currency based on the site and plugin not only in app like the US dollars not like English pounds or Kuwaiti dinar it have rate 

thanks

3. Proof of my purchased:  ca4abfe5-d915-4226-b092-90a7b3057723

**Comment by minhcasi** [comment]
Hi, thank you for your question - it may not support, as this is kind of advanced features, you can to customize it to meet with your business logic - very best!
