### ISSUE TITLE
[Fluxstore] Jerky scrolling, unable to achieve smooth 60 fps experience

### ISSUE THREAD

**Issue by aiac** [inspireui/support#1594]
Do you plan to optimize Fluxstore? There is no way to achive 60 fps, scrolling through product list is jerky no matter what image sizes we use. Profiller shows max 35 fps on OnePlus 6T.

**Comment by minhcasi** [comment]
Hi, you can try to use Profiler on the Physical Device as on simulator it is the difference - https://flutter.dev/docs/perf/rendering/ui-performance

Performance is our most concern so that we always upgrade it for each release, thank you 😊
