### ISSUE TITLE
 Fluxstore Pro - Build error

### ISSUE THREAD

**Issue by rajeshtr** [inspireui/support#1595]
Build error:

Running Gradle task 'assembleRelease'... registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection) registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection) registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection) Compiler message: ../../../../flutter/.pub-cache/hosted/pub.dartlang.org/extended_image_library-0.1.9/lib/src/extended_network_image_provider.dart:63:41: Error: Type 'DecoderCallback' not found. ExtendedNetworkImageProvider key, DecoderCallback decode) { ^^^^^^^^^^^^^^^ ../../../../flutter/.pub-cache/hosted/pub.dartlang.org/extended_image_library-0.1.9/lib/src/extended_network_image_provider.dart:87:41: Error: Type 'DecoderCallback' not found. ExtendedNetworkImageProvider key, DecoderCallback decode) async { ^^^^^^^^^^^^^^^ ../../../../flutter/.pub-cache/hosted/pub.dartlang.org/extended_image_library-0.1.9/lib/src/extended_image_provider.dart:14:23: Error: Type 'DecoderCallback' not found. Uint8List data, DecoderCallback decode) async { ^^^^^^^^^^^^^^^ ../../../../flutter/.pub-cache/hosted/pub.dartlang.org/extended_image_library-0.1.9/lib/src/extended_memory_image_provider.dart:12:46: Error: Type 'DecoderCallback' not found. ImageStreamCompleter load(MemoryImage key, DecoderCallback decode) { ^^^^^^^^^^^^^^^
../../../../flutter/.pub-cache/hosted/pub.dartlang.org/extended_image_library-0.1.9/lib/src/extended_memory_image_provider.dart:19:48: Error: Type 'DecoderCallback' not found. Future<ui.Codec> _loadAsync(MemoryImage key, DecoderCallback decode) { ^^^^^^^^^^^^^^^ ../../../../flutter/.pub-cache/hosted/pub.dartlang.org/extended_image_library-0.1.9/lib/src/extended_file_image_provider.dart:13:44: Error: Type 'DecoderCallback' not found. ImageStreamCompleter load(FileImage key, DecoderCallback decode) { ^^^^^^^^^^^^^^^ ../../../../flutter/.pub-cache/hosted/pub.dartlang.org/extended_image_library-0.1.9/lib/src/extended_file_image_provider.dart:23:46: Error: Type 'DecoderCallback' not found. Future<ui.Codec> _loadAsync(FileImage key, DecoderCallback decode) async { ^^^^^^^^^^^^^^^ ../../../../flutter/.pub-cache/hosted/pub.dartlang.org/extended_image_library-0.1.9/lib/src/extended_asset_bundle_image_provider.dart:35:54: Error: Type 'DecoderCallback' not found. ImageStreamCompleter load(AssetBundleImageKey key, DecoderCallback decode) { ^^^^^^^^^^^^^^^ ../../../../flutter/.pub-cache/hosted/pub.dartlang.org/extended_image_library-0.1.9/lib/src/extended_asset_bundle_image_provider.dart:52:32: Error: Type 'DecoderCallback' not found. AssetBundleImageKey key, DecoderCallback decode) async { ^^^^^^^^^^^^^^^ ../../../../flutter/.pub-cache/hosted/pub.dartlang.org/extended_image_library-0.1.9/lib/src/extended_asset_bundle_image_provider.dart:88:54: Error: Type 'DecoderCallback' not found. ImageStreamCompleter load(AssetBundleImageKey key, DecoderCallback decode) { ^^^^^^^^^^^^^^^ ../../../../flutter/.pub-cache/hosted/pub.dartlang.org/extended_image_library-0.1.9/lib/src/extended_asset_bundle_image_provider.dart:105:32: Error: Type 'DecoderCallback' not found. AssetBundleImageKey key, DecoderCallback decode) async { ^^^^^^^^^^^^^^^ ../../../../flutter/.pub-cache/hosted/pub.dartlang.org/extended_image_library-0.1.9/lib/src/extended_memory_image_provider.dart:12:24: Error: The method 'ExtendedMemoryImageProvider.load' has more required arguments than those of overridden method 'MemoryImage.load'. ImageStreamCompleter load(MemoryImage key, DecoderCallback decode) { ^ ../../../../flutter/packages/flutter/lib/src/painting/image_provider.dart:596:24: Context: This is the overridden method ('load'). ImageStreamCompleter load(MemoryImage key) { ^ ../../../../flutter/.pub-cache/hosted/pub.dartlang.org/extended_image_library-0.1.9/lib/src/extended_file_image_provider.dart:13:24: Error: The method 'ExtendedFileImageProvider.load' has more required arguments than those of overridden method 'FileImage.load'. ImageStreamCompleter load(FileImage key, DecoderCallback decode) { ^ ../../../../flutter/packages/flutter/lib/src/painting/image_provider.dart:528:24: Context: This is the overridden method ('load'). ImageStreamCompleter load(FileImage key) { ^ ../../../../flutter/.pub-cache/hosted/pub.dartlang.org/extended_image_library-0.1.9/lib/src/extended_asset_bundle_image_provider.dart:35:24: Error: The method 'ExtendedExactAssetImageProvider.load' has more required arguments than those of overridden method 'AssetBundleImageProvider.load'. ImageStreamCompleter load(AssetBundleImageKey key, DecoderCallback decode) { ^
../../../../flutter/.pub-cache/hosted/pub.dartlang.org/extended_image_library-0.1.9/lib/src/extended_network_image_provider.dart:62:24: Error: The method 'ExtendedNetworkImageProvider.load' has more required arguments than those of overridden method 'ImageProvider.load'. ImageStreamCompleter load( ^ ../../../../flutter/packages/flutter/lib/src/painting/image_provider.dart:383:24: Context: This is the overridden method ('load'). ImageStreamCompleter load(T key); ^ ../../../../flutter/.pub-cache/hosted/pub.dartlang.org/extended_image_library-0.1.9/lib/src/extended_network_image_provider.dart:63:41: Error: 'DecoderCallback' isn't a type. ExtendedNetworkImageProvider key, DecoderCallback decode) { ^^^^^^^^^^^^^^^ ../../../../flutter/.pub-cache/hosted/pub.dartlang.org/extended_image_library-0.1.9/lib/src/extended_network_image_provider.dart:87:41: Error: 'DecoderCallback' isn't a type. ExtendedNetworkImageProvider key, DecoderCallback decode) async { ^^^^^^^^^^^^^^^ ../../../../flutter/.pub-cache/hosted/pub.dartlang.org/extended_image_library-0.1.9/lib/src/extended_image_provider.dart:14:23: Error: 'DecoderCallback' isn't a type. Uint8List data, DecoderCallback decode) async { ^^^^^^^^^^^^^^^ ../../../../flutter/.pub-cache/hosted/pub.dartlang.org/extended_image_library-0.1.9/lib/src/extended_memory_image_provider.dart:12:46: Error: 'DecoderCallback' isn't a type. ImageStreamCompleter load(MemoryImage key, DecoderCallback decode) { ^^^^^^^^^^^^^^^ ../../../../flutter/.pub-cache/hosted/pub.dartlang.org/extended_image_library-0.1.9/lib/src/extended_memory_image_provider.dart:19:48: Error: 'DecoderCallback' isn't a type. Future<ui.Codec> _loadAsync(MemoryImage key, DecoderCallback decode) { ^^^^^^^^^^^^^^^ ../../../../flutter/.pub-cache/hosted/pub.dartlang.org/extended_image_library-0.1.9/lib/src/extended_file_image_provider.dart:13:44: Error: 'DecoderCallback' isn't a type. ImageStreamCompleter load(FileImage key, DecoderCallback decode) { ^^^^^^^^^^^^^^^ ../../../../flutter/.pub-cache/hosted/pub.dartlang.org/extended_image_library-0.1.9/lib/src/extended_file_image_provider.dart:23:46: Error: 'DecoderCallback' isn't a type. Future<ui.Codec> _loadAsync(FileImage key, DecoderCallback decode) async { ^^^^^^^^^^^^^^^ ../../../../flutter/.pub-cache/hosted/pub.dartlang.org/extended_image_library-0.1.9/lib/src/extended_asset_bundle_image_provider.dart:35:54: Error: 'DecoderCallback' isn't a type. ImageStreamCompleter load(AssetBundleImageKey key, DecoderCallback decode) { ^^^^^^^^^^^^^^^ ../../../../flutter/.pub-cache/hosted/pub.dartlang.org/extended_image_library-0.1.9/lib/src/extended_asset_bundle_image_provider.dart:52:32: Error: 'DecoderCallback' isn't a type. AssetBundleImageKey key, DecoderCallback decode) async { ^^^^^^^^^^^^^^^ ../../../../flutter/.pub-cache/hosted/pub.dartlang.org/extended_image_library-0.1.9/lib/src/extended_asset_bundle_image_provider.dart:88:54: Error: 'DecoderCallback' isn't a type. ImageStreamCompleter load(AssetBundleImageKey key, DecoderCallback decode) {
---------

1. My issue:

2. Screenshots issues:

3. Proof of my purchased:

3. Config files (optional)

**Comment by rajeshtr** [comment]
(https://user-images.githubusercontent.com/2477682/70735464-56346280-1d34-11ea-8801-cb8b25ac85e0.PNG)

**Comment by rajeshtr** [comment]
![Image_20191212_1803121539224128451868024](https://user-images.githubusercontent.com/2477682/70735699-bdeaad80-1d34-11ea-8962-8dd79401acdf.jpg)
![Image_20191212_1827416287426187440211623](https://user-images.githubusercontent.com/2477682/70735700-bdeaad80-1d34-11ea-986a-7d382763a82e.jpg)

**Comment by rajeshtr** [comment]
![Capture](https://user-images.githubusercontent.com/2477682/70735742-d22eaa80-1d34-11ea-8024-e6e3fdc6619d.PNG)

**Comment by minhcasi** [comment]
Note with checking, thank you!

@minhtruong315 - could be related to the latest Flutter 1.12 - thanks

**Comment by minhtruong315** [comment]
https://github.com/inspireui/support/issues/1591#issuecomment-565261329
check this solution

**Comment by rajeshtr** [comment]
Still Getting a warning , how do we resolve it ?

registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

**Comment by minhcasi** [comment]
@rajeshtr  - please try to update the app to the latest version 1.6, there is some bug fix and compatible with Flutter 1.12 - Detail changelog will be updated from https://medium.com/@inspireui/announcing-fluxstore-1-6-337efff1791f - thank you!

**Comment by rajeshtr** [comment]
flutter build apk
You are building a fat APK that includes binaries for android-arm,
android-arm64, android-x64.
If you are deploying the app to the Play Store, it's recommended to use app
bundles or split the APK to reduce the APK size.
    To generate an app bundle, run:
        flutter build appbundle --target-platform
        android-arm,android-arm64,android-x64
        Learn more on: https://developer.android.com/guide/app-bundle
    To split the APKs per ABI, run:
        flutter build apk --target-platform
        android-arm,android-arm64,android-x64 --split-per-abi
        Learn more on:
        https://developer.android.com/studio/build/configure-apk-splits#configur
        e-abi-split
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Running Gradle task 'assembleRelease'...                                
Note: /home/vinu/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.4.2+1/android/src/main/java/io/flutter/plugins/firebase/core/FirebaseCorePlugin.java uses or overrides a deprecated API.
Running Gradle task 'assembleRelease'...                                        Note: Recompile with -Xlint:deprecation for details.            
Running Gradle task 'assembleRelease'...                                        Note: /home/vinu/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.12.11/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java uses or overrides a deprecated API.
Running Gradle task 'assembleRelease'...                                        Note: Recompile with -Xlint:deprecation for details.            
Running Gradle task 'assembleRelease'...                                        Note: /home/vinu/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.12.11/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java uses unchecked or unsafe operations.
Running Gradle task 'assembleRelease'...                                        Note: Recompile with -Xlint:unchecked for details.              
Running Gradle task 'assembleRelease'...                                        Note: Some input files use or override a deprecated API.        
Running Gradle task 'assembleRelease'...                                        Note: Recompile with -Xlint:deprecation for details.            
Running Gradle task 'assembleRelease'...                                        Note: /home/vinu/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_analytics-5.0.6/android/src/main/java/io/flutter/plugins/firebaseanalytics/FirebaseAnalyticsPlugin.java uses or overrides a deprecated API.
Running Gradle task 'assembleRelease'...                                        Note: Recompile with -Xlint:deprecation for details.            
Running Gradle task 'assembleRelease'...                                        Note: Some input files use or override a deprecated API.        
Running Gradle task 'assembleRelease'...                                        Note: Recompile with -Xlint:deprecation for details.            
Running Gradle task 'assembleRelease'...                                        Note: Some input files use unchecked or unsafe operations.      
Running Gradle task 'assembleRelease'...                                        Note: Recompile with -Xlint:unchecked for details.              
Running Gradle task 'assembleRelease'...                                        Note: Some input files use unchecked or unsafe operations.      
Running Gradle task 'assembleRelease'...                                        Note: Recompile with -Xlint:unchecked for details.              
Running Gradle task 'assembleRelease'...                                        Note: /home/vinu/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.5.1/android/src/main/java/io/flutter/plugins/pathprovider/PathProviderPlugin.java uses or overrides a deprecated API.
Running Gradle task 'assembleRelease'...                                        Note: Recompile with -Xlint:deprecation for details.            
Running Gradle task 'assembleRelease'...                                        /home/vinu/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.4+8/android/src/main/java/io/flutter/plugins/sharedpreferences/SharedPreferencesPlugin.java:25: warning: [deprecation] getFlutterEngine() in FlutterPluginBinding has been deprecated
Running Gradle task 'assembleRelease'...                                            setupChannel(binding.getFlutterEngine().getDartExecutor(), binding.getApplicationContext());
Running Gradle task 'assembleRelease'...                                                                ^                                       
Running Gradle task 'assembleRelease'...                                        1 warning                                                       
Running Gradle task 'assembleRelease'...                                        Note: /home/vinu/flutter/.pub-cache/hosted/pub.dartlang.org/share-0.6.3+4/android/src/main/java/io/flutter/plugins/share/SharePlugin.java uses or overrides a deprecated API.
Running Gradle task 'assembleRelease'...                                        Note: Recompile with -Xlint:deprecation for details.            
Running Gradle task 'assembleRelease'...                                        Note: Some input files use or override a deprecated API.        
Running Gradle task 'assembleRelease'...                                        Note: Recompile with -Xlint:deprecation for details.            
Running Gradle task 'assembleRelease'...                                        Note: /home/vinu/flutter/.pub-cache/hosted/pub.dartlang.org/video_player-0.10.4+1/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayerPlugin.java uses or overrides a deprecated API.
Running Gradle task 'assembleRelease'...                                        Note: Recompile with -Xlint:deprecation for details.            
Running Gradle task 'assembleRelease'...                                        Note: Some input files use or override a deprecated API.        
Running Gradle task 'assembleRelease'...                                        Note: Recompile with -Xlint:deprecation for details.            
Running Gradle task 'assembleRelease'...                                        Removed unused resources: Binary resource data reduced from 613KB to 602KB: Removed 1%
Running Gradle task 'assembleRelease'...                                                                                                        
Running Gradle task 'assembleRelease'...                                        FAILURE: Build failed with an exception.                        
Running Gradle task 'assembleRelease'...                                                                                                        
Running Gradle task 'assembleRelease'...                                        * What went wrong:                                              
Running Gradle task 'assembleRelease'...                                        Execution failed for task ':device_apps:verifyReleaseResources'.
Running Gradle task 'assembleRelease'...                                        > java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
Running Gradle task 'assembleRelease'...                                          /home/vinu/shared/cusstomerapp/build/device_apps/intermediates/res/merged/release/values/values.xml:236: error: resource android:attr/fontVariationSettings not found.
Running Gradle task 'assembleRelease'...                                          /home/vinu/shared/cusstomerapp/build/device_apps/intermediates/res/merged/release/values/values.xml:237: error: resource android:attr/ttcIndex not found.
Running Gradle task 'assembleRelease'...                                          error: failed linking references.                             
Running Gradle task 'assembleRelease'...                                                                                                        
Running Gradle task 'assembleRelease'...                                                                                                        
Running Gradle task 'assembleRelease'...                                        * Try:                                                          
Running Gradle task 'assembleRelease'...                                        Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
Running Gradle task 'assembleRelease'...                                                                                                        
Running Gradle task 'assembleRelease'...                                        * Get more help at https://help.gradle.org                      
Running Gradle task 'assembleRelease'...                                                                                                        
Running Gradle task 'assembleRelease'...                                        BUILD FAILED in 56m 32s                                         
Running Gradle task 'assembleRelease'...                                                                                           
Running Gradle task 'assembleRelease'... Done                    3400.4s (!)
Gradle task assembleRelease failed with exit code 1

**Comment by rajeshtr** [comment]
Happens when trying to build the apk

**Comment by minhcasi** [comment]
@minhtruong315 - pls try to reproduce by generating apk

**Comment by minhtruong315** [comment]
I'm checking

**Comment by minhtruong315** [comment]
@rajeshtr try to replace pubspec.yaml 
[pubspec.yaml.zip](https://github.com/inspireui/support/files/3991058/pubspec.yaml.zip)
Then add ```googleServices { disableVersionCheck = true }``` at the bottom of android/app/build.gradle
<img width="1303" alt="Screen Shot 2019-12-21 at 11 27 15 AM" src="https://user-images.githubusercontent.com/10402500/71303016-5e039f00-23e5-11ea-93da-6480feb8d61d.png">
