### ISSUE TITLE
Fluxstore Vendor

### ISSUE THREAD

**Issue by saifmuhtar** [inspireui/support#1598]
Hi InspireUI,
I got this error when I click green RUN button to run Fluxstore-vendor:
===================================================

Launching lib\main.dart on AOSP on IA Emulator in debug mode...
Running Gradle task 'assembleDebug'...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

Compiler message:
../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/cached_network_image-1.1.3/lib/src/cached_network_image_provider.dart:42:24: Error: The method 'CachedNetworkImageProvider.load' has fewer positional arguments than those of overridden method 'ImageProvider.load'.
  ImageStreamCompleter load(CachedNetworkImageProvider key) {
                       ^
/C:/src/flutter/flutter/packages/flutter/lib/src/painting/image_provider.dart:403:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(T key, DecoderCallback decode);
                       ^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 780

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\flutter\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 6s
Finished with error: Gradle task assembleDebug failed with exit code 1

========================================================
I already copy the folder and paste to another location & delete the build folder. 
But this error keep coming.
Thank you for your support.

This is my purchase code:
![FireShot Capture 009 - Support for Fluxstore Multi Vendor - Flutter E-commerce Full App_ - codecanyon net](https://user-images.githubusercontent.com/34681804/70761735-3da26780-1d89-11ea-8622-c7cec7526558.png)

**Comment by minhcasi** [comment]
@saifmuhtar - could you help to update the pubspec.yaml and change this value   

From: cached_network_image: 1.1.3
To:   cached_network_image: 2.0.0-rc.1

Then update the package and restart again, this issue is caused by latest Flutter 1.12 update, we will update new version update on next couple of days - thank you!

**Comment by saifmuhtar** [comment]
@minhcasi Now it's working smoothly. Thank you so much for your great support.

**Comment by saifmuhtar** [comment]
😃

**Comment by minhcasi** [comment]
@saifmuhtar you are very welcome, let us know if you need any support from the team

Please also help us to give feedback/rating to http://codecayon.net/downloads - thank you very much!
