### ISSUE TITLE
[BeoNews] - Error while running BeoNews 

### ISSUE THREAD

**Issue by dermayank** [inspireui/support#1599]
I followed all the steps and now when I'm trying to run the app it is showing the following error after the app execution is complete and the app is installed in the emulator.

![Screenshot from 2019-12-13 12-23-51](https://user-images.githubusercontent.com/24271097/70776694-cd550f80-1da3-11ea-92cd-769860a4982f.png)

Proof of my purchase
![Screenshot from 2019-12-04 10-30-36](https://user-images.githubusercontent.com/24271097/70776717-dcd45880-1da3-11ea-8911-d4318e625889.png)

Also, the Name of app while opening and in the menubar is BeoNews, not the TripRethink.

**Comment by minhcasi** [comment]
Hi @dermayank - could i check if could run the Example app success from https://facebook.github.io/react-native/docs/getting-started - it seems the bridge problem (adb) from your seting

**Comment by dermayank** [comment]
okay sure let me try and connect back.

**Comment by minhcasi** [comment]
@dermayank - let us know if you have any further issues - thank you!
