### ISSUE TITLE
ListApp 1.5.3 run simulator error.

### ISSUE THREAD

**Issue by namtrik** [inspireui/support#16]
- Product: ListApp
 - My Purchased Code: ccded53c-5f90-41ff-8c6a-fac4faae1017

Hello, after running "expo start" and wanting to run in the android simulator this error appears.

<img width="992" alt="captura de pantalla 2018-11-15 a la s 2 56 24 p m" src="https://user-images.githubusercontent.com/44480034/48578484-bcf40c00-e8e7-11e8-8c86-de31d37c833f.png">

Thanks

**Comment by thangvo9x** [comment]
Hi . You run it on the android simulator ? remove node_modules folder and run yarn again. seem your app is missing some libraries -> this error is appeared .

**Comment by minhcasi** [comment]
@namtrik please try to reinstall the git and set the PATH on window, this something related to yarn issue could not download the git URL
https://github.com/yarnpkg/yarn/issues/3102
https://github.com/yarnpkg/yarn/issues/2083

**Comment by minhcasi** [comment]
Please reopen if you still could not fix the issue - thank you!
