### ISSUE TITLE
[ListApp] Clicking on the heart of a post does not update in the other views

### ISSUE THREAD

**Issue by Jeison12** [inspireui/support#160]
Product: ListApp
My Purchased Code: ccded53c-5f90-41ff-8c6a-fac4faae1017

![screenshot_2019-01-06-09-28-41](https://user-images.githubusercontent.com/26725495/50737406-deaa9a80-1196-11e9-8805-cee052c37136.png)

![screenshot_2019-01-06-09-28-37](https://user-images.githubusercontent.com/26725495/50737420-08fc5800-1197-11e9-9c53-071755cafa9b.png)

Hello, the link of the app is https://expo.io/@inspireui-demo/listapp-mylisting. When entering the details of Z Victoria and when I click on the heart that is at the bottom and return to the beginning, the heart of Z Victoria is not updated even though it has already been added to Bookmarks

**Comment by tthamel** [comment]
is this happening on the demo app or your personal app?

**Comment by thangvo9x** [comment]
Hi @tthamel .Thanks for your value feedback. We've record & fix it in the next update.
Thanks .Good day

**Comment by thangvo9x** [comment]
Hi. We've fixed urgent it . published again. Thanks for your feedback.
