### ISSUE TITLE
[MSTORE] -  IOS 

### ISSUE THREAD

**Issue by kiamoz** [inspireui/support#1600]
App Store Connect
 
Dear Developer,

We identified one or more issues with a recent delivery for your app, "atcservices" 3.7.0 (1). Your delivery was successful, but you may wish to correct the following issues in your next delivery:

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

After you’ve corrected the issues, you can upload a new binary to App Store Connect.

Best regards,

The App Store Team

**Comment by minhcasi** [comment]
@kiamoz - Apple still allow you to pass the review due to UIWebView issue, we have the problem before but it will be ok - thanks
