### ISSUE TITLE
Unable to Connect To Firebase in Fluxstore Vendor

### ISSUE THREAD

**Issue by HarrySmith01** [inspireui/support#1601]
WHenever I am trying to connect to firebase I am getting  below error:

Firebase: Could not find the Android Application module. Only Android Application Modules can be connected to Firebase online projects. Create a new Android Application Module or create/import a different Android Studio project.

You can check below attachment too

https://ibb.co/rQQzBSg

**Comment by minhcasi** [comment]
@HarrySmith01 - could I check if you have registered your Android app on Firebase, also try to re-download the google service file again - this detailed blog could help for Firebase setting - https://medium.com/flutterpub/enabling-firebase-cloud-messaging-push-notifications-with-flutter-39b08f2ed723

**Comment by minhcasi** [comment]
#1602

**Comment by minhcasi** [comment]
I'm closed #1602 and move to this ticket for easier to support, pls keep update your image checking on this ticket 

If it does not work, pls share your config file here - thanks

**Comment by HarrySmith01** [comment]
I have tried it but still it is not working.

**Comment by minhcasi** [comment]
@HarrySmith01 - could i confirm if you download the google service that is matched with your bundle id?

Could you add my email minhcasi@gmail.com to your firebase for checking? Thanks

**Comment by HarrySmith01** [comment]
Done.
I have provided the access

    On Monday, 16 December, 2019, 5:22:15 pm IST, Minh Pham <notifications@github.com> wrote:  
 
 
@HarrySmith01 - could i confirm if you download the google service that is matched with your bundle id?

Could you add my email minhcasi@gmail.com to your firebase for checking? Thanks

**Comment by HarrySmith01** [comment]
I have added you in Firebase account

**Comment by minhcasi** [comment]
@HarrySmith01 - sorry I did not get the invitation - could you help to send more to vumanhsn97@gmail.com ? 

@vumanhsn97 - pls help for suggestion

**Comment by HarrySmith01** [comment]
Done


sent new invitation

**Comment by vumanhsn97** [comment]
@HarrySmith01 Please follow this toturial https://docs.inspireui.com/fluxstore/firebase/
