### ISSUE TITLE
Fluxstore Vendor is not fetching all products image.

### ISSUE THREAD

**Issue by HarrySmith01** [inspireui/support#1602]
![Screenshot_20191213-153558](https://user-images.githubusercontent.com/58846483/70792119-8e808300-1dbe-11ea-96df-95f060526f42.jpg)

I have just build the app and found that it is fetching images for the very few products same you can see in attachment too.

also i have already regenerated thumbnails.

And not just thumbnails but product gallery images are also being fetched for very few products.

**Comment by minhcasi** [comment]
@HarrySmith01 - is these missing image products have the **feature image** setting?

**Comment by minhcasi** [comment]
move to #1601

**Comment by HarrySmith01** [comment]
It's looks like I have got it fixed.

you can close this ticket for now.
