### ISSUE TITLE
Flexstore Vendor - Unable to Login with  Email

### ISSUE THREAD

**Issue by HarrySmith01** [inspireui/support#1603]
Login With email:

Whenever I try to login with email it is giving error "Warning: Invalid argument(s)"

**Comment by minhcasi** [comment]
move to #1601 - pls help to create you all issues into one ticket that help the team  support better on your ticket - thanks

**Comment by HarrySmith01** [comment]
I see. Sure.

I though 1 ticket for all issue may create confusion that is why I created new ticket.
