### ISSUE TITLE
[Fluxstore 1.9.5b] -  Order History Error

### ISSUE THREAD

**Issue by myothura** [inspireui/support#1605]
Hello , 

   I'am not nothing config in your codecanyo source file.

1. I edit only Enable Point and Reward 

2. Login with facebook .

3. I would like to know what is this error https://tppr.me/aLeDp

4. I Running with Android This error occur https://tppr.me/aLeDp

I check My order history . I fond this error . 

Plase Kindly check and fix this error  Thanks Team 

https://tppr.me/Nwm36

**Comment by minhcasi** [comment]
@myothura - pls download latest 1.6 to fix this issue on Flutter 1.12 - thanks
