### ISSUE TITLE
The following assertion was thrown building Consumer<AppModel>(dirty, dependencies: [InheritedProvider<AppModel>]): 'dart:ui/window.dart': Failed assertion: line 284: '<optimized out>': is not true.

### ISSUE THREAD

**Issue by VM8198** [inspireui/support#1607]
My issue: I am getting this error after cloning the flux store app and run on the first time

**Comment by huntelar10** [comment]
i get same issue

**Comment by minhcasi** [comment]
@VM8198 @huntelar10 

Could i check if you could able run the Test Drive successful - https://flutter.dev/docs/get-started/test-drive ?

**Comment by michaelbrinkworth** [comment]
was this solved because i am facing the same problem
