### ISSUE TITLE
[FluxStore - Woocommerece 1.5.9b] - Not able to apply any demo

### ISSUE THREAD

**Issue by Coinizy1** [inspireui/support#1609]
1. My issue:
I am not to use any demo i followed the tutorial correctly it works on basic config.json but it is not working with any other demo
2. Screenshots issues:
type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'String'
The relevant error-causing widget was: 
  VerticalLayout file:///C:/Users/Jazzy/Desktop/FluxStore-woo%201.5.9b/source/lib/widgets/home/index.dart:111:15
![Screenshot_20191215-041756](https://user-images.githubusercontent.com/31903098/70855760-04d1d200-1ef2-11ea-9021-79d1137b0ae9.jpg)

3. Proof of my purchased:
![Screenshot_5](https://user-images.githubusercontent.com/31903098/70855762-0a2f1c80-1ef2-11ea-9f83-07a43275a3c8.png)

3. Config files (optional)
{
  "Background": {
    "height": 0.3,
    "image": "https://trello-attachments.s3.amazonaws.com/5d70b58f08cb0676848fc5e5/1200x675/52fbab8f4ae9e62a7aa3a0d86a0829e6/2792283.jpg"
  },
  "HorizonLayout": [
    {
      "layout": "logo",
      "hideLogo": true
    },
    {
      "layout": "header_text",
      "fontSize": 23.0,
      "height": 0.13,
      "padding": 30.0,
      "rotate": [
        "WooCommerce",
        "Magento",
        "Opencart"
      ],
      "type": "fade"
    },
    {
      "layout": "header_search",
      "text": {
        "en": "Search for a product",
        "ab": "بلوق وظائف",
        "vi": "Tìm kiếm"
      }
    },
    {
      "layout": "category",
      "type": "image",
      "wrap": false,
      "showText": true,
      "items": [
        {
          "category": 211,
          "image": "https://image.shutterstock.com/image-photo/two-shiny-fresh-roasted-coffee-260nw-562127497.jpg"
        },
        {
          "category": 208,
          "image": "https://image.shutterstock.com/image-photo/cup-coffee-260nw-507740677.jpg"
        },
        {
          "category": 22,
          "image": "https://image.shutterstock.com/image-vector/coffee-beans-realistic-set-showing-260nw-637947457.jpg"
        },
        {
          "image": "https://image.shutterstock.com/image-photo/coffee-cup-assortment-top-view-260nw-159200423.jpg",
          "category": 22
        },
        {
          "image": "https://image.shutterstock.com/image-photo/cappuccino-latte-frothy-foam-blue-260nw-531118738.jpg",
          "category": 22
        }
      ]
    }
  ],
  "VerticalLayout": {
    "layout": "list",
    "name": {
      "en": "Recent Collections",
      "ab": "مجموعات الرجل",
      "vi": "Bộ sưu tập gần "
    }
  },
  "Setting": {
    "MainColor": "#3FC1BE",
    "ProductListLayout": "list"
  },
  "TabBar": [
    {
      "layout": "home",
      "icon": "assets/icons/tabs/icon-home.png"
    },
    {
      "layout": "category",
      "categoryLayout": "card",
      "icon": "assets/icons/tabs/icon-category.png"
    },
    {
      "layout": "search",
      "icon": "assets/icons/tabs/icon-search.png"
    },
    {
      "layout": "cart",
      "icon": "assets/icons/tabs/icon-cart2.png"
    },
    {
      "layout": "profile",
      "icon": "assets/icons/tabs/icon-user.png"
    }
  ]
}

**Comment by minhcasi** [comment]
@Coinizy1 - could i confirm if you are using latest version 1.6 that released on yesterday ? Thank you!
