### ISSUE TITLE
[Mstore-Pro] - I can't register from the app

### ISSUE THREAD

**Issue by zjw93615** [inspireui/support#1610]
1. My issue:
Hello, good morning, the problem I have is that I can register new users on the website but I can not register new users in the APP. Could you please provide guidance on what the problem would be?

2. Screenshots issues:
https://ibb.co/7tjMMNp
https://ibb.co/8MLB1RK
https://ibb.co/rxmJJdg

3. Proof of my purchased:
https://ibb.co/wYMx5Bc

3. Config files (optional)
I think this issue is similar to fernando (https://github.com/inspireui/support/issues/1390), but he is using Mstore - MV so I cannot solve my problem with his solution.

**Comment by minhcasi** [comment]
@concuacon - please help for checking - thank you!

**Comment by zjw93615** [comment]
@concuacon Hello, could you provide me guidance to fix this issue?

**Comment by zjw93615** [comment]
I have already fixed this problem, thanks.

**Comment by Tayeb-Ali** [comment]
> I have already fixed this problem, thanks.

Pls how do that ..?
i have same issus
