### ISSUE TITLE
[FluxStore 1.6.0] - Multi Language Issue , Category Layout Issue , Filter & Sign in by SMS Help

### ISSUE THREAD

**Issue by siyashamsudeen** [inspireui/support#1611]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:

A . Im having issues with the multi language features . when i run the app and switch the language to arabic - the home screen does not change to the config_ar.json layout . it still loads all products in english . but when i go to the categories and browse the products , there it comes in the arabic translation . So here what is the point of having additional config file for arabic ?

Having the language selected as Arabic , if i do a hot restart of the source code then the app loads in the arabic config layout . I totally dont understand the point . its pretty sure that once i publish the app only one of the version works AND i believe whenever the language switch happens the homescreen theme is suppose to change automatically which is not happening . 

Please see the below screenshots

My Normal Home Screen when app is runs. 

<img width="267" alt="Screen Shot 2019-12-15 at 4 33 17 AM" src="https://user-images.githubusercontent.com/57159602/70856488-7d875d00-1ef7-11ea-9bdd-91837a4c830c.png">

When i switch to Arabic Language

Home Screen loads everything in english:

<img width="253" alt="Screen Shot 2019-12-15 at 4 33 41 AM" src="https://user-images.githubusercontent.com/57159602/70856497-97c13b00-1ef7-11ea-8a1d-0a8d12db6fbf.png">

But the cateogry page and the product browsing in that is translated:

<img width="254" alt="Screen Shot 2019-12-15 at 4 34 09 AM" src="https://user-images.githubusercontent.com/57159602/70856503-b6273680-1ef7-11ea-8b19-ce8721d9577e.png">
<img width="266" alt="Screen Shot 2019-12-15 at 4 34 24 AM" src="https://user-images.githubusercontent.com/57159602/70856504-b6bfcd00-1ef7-11ea-9e89-cea6f4af7ea5.png">

After Hot Restart of the source code ( Keeping Language set to Arabic in the previous run )

<img width="273" alt="Screen Shot 2019-12-15 at 4 44 55 AM" src="https://user-images.githubusercontent.com/57159602/70856556-6ac15800-1ef8-11ea-8d94-2ad74d497cff.png">

B. I changed the category tab layout to "subCategory" in my config file but it is giving all errors as below

<img width="1439" alt="Screen Shot 2019-12-15 at 5 19 35 AM" src="https://user-images.githubusercontent.com/57159602/70856713-123f8a00-1efb-11ea-9316-f11b791717e0.png">

And in sideMenu, Grid Layout categories are not coming in hierarchal order. 

<img width="266" alt="Screen Shot 2019-12-15 at 5 29 38 AM" src="https://user-images.githubusercontent.com/57159602/70856761-ee307880-1efb-11ea-86d5-f3cb0886b8dd.png">
 

C. In Filter how do i add other attributes such as filter by gender, color, type etc ?

D. how do i setup the Facebook Sign In, SMS Sign in , Google Sign in and Apple sign in ?
i dont see any reference to these in the documentation guide except a video tut for sms sign in . 
 - is sms sign in provided by Facebook or Firebase ? im quite confused in this part as well . 
 -Currently when i do facebook sign in it gives reference of fluxstore ? where are the settings for this ?

2. Screenshots issues:
Already given above

3. Proof of my purchased:
previously added comment regarding the first issue
<img width="650" alt="Screen Shot 2019-12-15 at 5 24 40 AM" src="https://user-images.githubusercontent.com/57159602/70856765-07d1c000-1efc-11ea-8b28-f90fdecd5c27.png">

downloads page
<img width="1319" alt="Screen Shot 2019-12-15 at 5 25 00 AM" src="https://user-images.githubusercontent.com/57159602/70856767-0d2f0a80-1efc-11ea-8aa5-55f5aab2ae93.png">

3. Config files (optional)

Config.dart - http://finefair.le-pearl.com/app-files/config.dart
Config.json - http://finefair.le-pearl.com/app-files/config.json

In addition to this following the this ticket i will be sending an email with wp login access to 

minh@inspireui.com
truong@inspireui.com,
support@inspireui.com

with subject as this ticket number. 

Im really struggling to finish the app and publish it . hence please help me to fix this asap. 
its been really long i purchased the product and still havent been able to finish the edits.

**Comment by siyashamsudeen** [comment]
Im still waiting for a response. please help

**Comment by minhtruong315** [comment]
@siyashamsudeen pls download the latest source code then try again

**Comment by siyashamsudeen** [comment]
Hello, after waiting a long time i wasn't expecting this reply . Im already using the latest source code 1.6.0 . 

And i have addressed multiple issues, i didnt get reply to any of it : this is very disappointing . 

Please see the title of this issue itselr , it is mentioned fluxstore 1.6.0 . 

Please help. 

Thank You ,

**Comment by minhcasi** [comment]
@siyashamsudeen - noted for investigating, sorry for the confusing comment.

**Comment by siyashamsudeen** [comment]
Im still waiting for a response to these issues . i haven't yet got a solution to any of the issues addressed in this ticket.  please help

**Comment by minhtruong315** [comment]
To fix arabic language. you need to change changeLanguage function in models/app.dart like this
```
void changeLanguage(String country, BuildContext context) async {
    try {
      SharedPreferences prefs = await SharedPreferences.getInstance();
      locale = country;
      Provider.of<CategoryModel>(context).getCategories(lang: country);
      await prefs.setString("language", country);
      await loadAppConfig();
      notifyListeners();
    } catch (err) {}
  }
```

**Comment by minhtruong315** [comment]
To fix sms login. you need to follow this document https://docs.inspireui.com/fluxstore/firebase/

**Comment by minhcasi** [comment]
#1624

**Comment by minhtruong315** [comment]
supported

**Comment by siyashamsudeen** [comment]
Issues are still not resolved please help. 

Thanks for helping with the language issue but other issues such as SMS Login, Maps , Filters, Fb google logins are still not sorted . Please help.

**Comment by siyashamsudeen** [comment]
Hello, im still waiting for a solution on this . please help
