### ISSUE TITLE
[MStore Multi Vendor - Complete React Native template for WooCommerce] - Can't load data from server.

### ISSUE THREAD

**Issue by psaisheela** [inspireui/support#1612]
1. My issue: 
Once the app loads, it is unable to display the products and gives 'can't load data from server', while on CeBuilder under the customization tab, i could see the categories. 

![Screenshot_2019-12-15-09-28-32-593_host exp exponent](https://user-images.githubusercontent.com/52187042/70857912-7ffcad80-1f1d-11ea-948c-728bacbf86b7.png)

Proof of my purchase:
![image](https://user-images.githubusercontent.com/52187042/70857936-01ecd680-1f1e-11ea-91a6-28e86ddaa1fd.png)

Config files: 

[AppConfig.txt](https://github.com/inspireui/support/files/3964582/AppConfig.txt)

[Config.txt](https://github.com/inspireui/support/files/3964590/Config.txt)

**Comment by minhcasi** [comment]
@psaisheela - from the wordpress side could help to check if all the plugins are installed base on this guide - https://docs.inspireui.com/mstore/wordpress-setting/ - thank you!

**Comment by psaisheela** [comment]
all the plugins are active and i have already compared it with the guide.

**Comment by vumanhsn97** [comment]
@psaisheela https://tppr.me/656zB it's working! Please remove expo app https://tppr.me/PWlym and run again

**Comment by psaisheela** [comment]
Do you mean to say we should delete the expo app? Do you want us to reinstall it or run the build every time?

**Comment by vumanhsn97** [comment]
Nope. Try to remove expo app and reinstall once time. If it's not working, zip and send your app to vumanhsn97@gmail.com. I will check for you
