### ISSUE TITLE
[Fluxstore Listing] - Error building application on VS Code

### ISSUE THREAD

**Issue by tcalvinsaveme** [inspireui/support#1613]
Purchase code: 37675588-c0d5-45ab-b426-d168f8e996be

Compiler message:
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-1.1.3/lib/src/cached_network_image_provider.dart:42:24: Error: The method 'CachedNetworkImageProvider.load' has fewer positional arguments than those of overridden method 'ImageProvider.load'.
  ImageStreamCompleter load(CachedNetworkImageProvider key) {
                       ^
/C:/flutter/packages/flutter/lib/src/painting/image_provider.dart:403:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(T key, DecoderCallback decode);
                       ^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 780

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.       

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 43s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                       164.7s (!)
Gradle task assembleDebug failed with exit code 1

Flutter Doctor found no issues.

**Comment by minhcasi** [comment]
@tcalvinsaveme - could you help to update the pubspec.yaml and change this value   

From: cached_network_image: 1.1.3
To:   cached_network_image: 2.0.0-rc.1

Then update the package and restart again, this issue is caused by latest Flutter 1.12 update, we will update new version update on next couple of days - thank you!

**Comment by tcalvinsaveme** [comment]
Thank you it worked.
