### ISSUE TITLE
[ListApp] - after build, app crash/restart when click detail product

### ISSUE THREAD

**Issue by SimiPrambos** [inspireui/support#1614]
1. My issue:
I was setup my own wordpress with MyHome theme.. on debug mode, app was launch normally. but when i build to apk, app crash or restart when clicked on product detail..
so i try to build from original source and same issue

2. Screenshots issues:

3. Proof of my purchased:
![Screen Shot 2019-12-15 at 21 00 57](https://user-images.githubusercontent.com/24631149/70863802-76eff880-1f7e-11ea-8619-ce3257c5ed5d.png)

3. Config files (optional)

**Comment by minhcasi** [comment]
@SimiPrambos - could you help to share your config files so that we could help for checking?

**Comment by SimiPrambos** [comment]
Thanks, I was fix this issue by adding google maps config in app.json
ref [Expo MapView Configuration](https://docs.expo.io/versions/v35.0.0/sdk/map-view/#configuration)
