### ISSUE TITLE
[CeStore 1.3.0] - Expo Deprecated & CeBuilder API not working correctly

### ISSUE THREAD

**Issue by guiaramos** [inspireui/support#1615]
1. My issue:
- Expo says it supports only version 33
- CeBuilder setup fails and says the following: The Rest API is not working correctly !

2. Screenshots issues:
![Screen Shot 2019-12-16 at 4 40 09 PM](https://user-images.githubusercontent.com/49703106/70888066-cbe54a80-2022-11ea-92b8-bfebec50a09a.png)
<img width="1032" alt="Screen Shot 2019-12-16 at 12 06 49 PM" src="https://user-images.githubusercontent.com/49703106/70876336-9d547900-1ffc-11ea-87c9-7841781f555a.png">

I am using MongoDB via docker -> (localhost:27027)
and I need the app version of the CeStore.

3. Proof of my purchased:
<img width="1316" alt="Screen Shot 2019-12-16 at 12 07 42 PM" src="https://user-images.githubusercontent.com/49703106/70876352-aba29500-1ffc-11ea-9c9f-bdf532ea9275.png">

3. Config files (optional)

**Comment by guiaramos** [comment]
Note: I am not using Wordpress API. I have to use MongoDB.

**Comment by minhcasi** [comment]
Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads  it's used to verify your proof of purchase? sorry for any inconvenience - Thank you!

**Comment by guiaramos** [comment]
@minhcasi the screenshot is at the end of the post, on the item 3.

**Comment by guiaramos** [comment]
When using expo upgrade I got the following error:
![Screen Shot 2019-12-16 at 4 50 14 PM](https://user-images.githubusercontent.com/49703106/70888633-26cb7180-2024-11ea-8fed-2c2dd82170d8.png)
![Screen Shot 2019-12-16 at 4 50 12 PM](https://user-images.githubusercontent.com/49703106/70888642-292dcb80-2024-11ea-806a-ef8a2530da11.png)

**Comment by minhcasi** [comment]
@guiaramos - sorry I miss your screenshot - the current CeStore is only working with the Cestore website that include from the download package, as i can see from the cebuilder it connect to newbizstart.com which is not base on Cestore web

**Comment by guiaramos** [comment]
Ok, thanks, about the upgrade of the expo, how should I proceed with that?

**Comment by guiaramos** [comment]
Any answer?

**Comment by minhcasi** [comment]
@guiaramos - pls help to check this guide - https://docs.inspireui.com/cestore/getting-started/#2-cestore-website - thanks

**Comment by guiaramos** [comment]
> @guiaramos - pls help to check this guide - https://docs.inspireui.com/cestore/getting-started/#2-cestore-website - thanks
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/1d558b97f234c93d69c700738dea9d43e3669697/687474703a2f2f67686f73742e6c6f63616c3a383030302f696d616765732f6d6574612f47686f73742d446f63732e6a7067">InspireUI Document**[CeStore - ReactJS web app & React Native mobile app for e-commerce](http://ghost.local:8000/cestore/getting-started/)**React Native currently creates vibrant wave in mobile application development. “Write once, Run anywhere”, then you can effectively produce mobile app across all platforms including iOS & Android by one language with “Native effect”.

@minhcasi the expo version of the app is 30 but expo app supports 33 - 36. That's why the error is happening , is there any intention to update the app version? Because now I am unable to use it.

**Comment by guiaramos** [comment]
@minhcasi  - Any answer?

**Comment by minhcasi** [comment]
@minhtruong315 - pls help for investigating

**Comment by minhtruong315** [comment]
@guiaramos can u send me app.json file via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/1615

**Comment by minhtruong315** [comment]
Hi @guiaramos, Please send me app.json file via my email. I'll help u check this issues. Thanks

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
