### ISSUE TITLE
[fluxstore] - SMS registration Country list

### ISSUE THREAD

**Issue by netdreamland** [inspireui/support#1616]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
We just only allow certain country to register thru SMS, however it seems it's not configurable on the list of country.
2. Screenshots issues:
<img width="339" alt="image" src="https://user-images.githubusercontent.com/12180247/70888854-36df5300-201c-11ea-97ea-41a0eddc557b.png">

3. Proof of my purchased:
![image](https://user-images.githubusercontent.com/12180247/70888597-b0c30c80-201b-11ea-9764-bce292ceb37b.png)

**Comment by minhcasi** [comment]
@netdreamland - you can customize the country lib by copy the folder to the product widget and remove some country that you don't want to display 

We may upgrade to this lib for easier to search - https://pub.dev/packages/country_code_picker
