### ISSUE TITLE
Installation issue  - fluxstore pro

### ISSUE THREAD

**Issue by masthan8** [inspireui/support#1617]
Trying to setup the app and every time i am getting some certificate issue, please check the screenshot and help me resolve this issue.

https://imgur.com/tbgcDWz

**Comment by incepio-flutter** [comment]
your image is not loading

**Comment by masthan8** [comment]
![tbgcDWz - Imgur](https://user-images.githubusercontent.com/43437325/70896331-8ebc9080-2001-11ea-9d25-87315159104b.jpg)

**Comment by masthan8** [comment]
hi pls check the image now

**Comment by incepio-flutter** [comment]
change the name of source folder and also the path of source folder

**Comment by minhcasi** [comment]
you can run "flutter clean" and also try to remove the .grade folder from android folder - thanks

**Comment by masthan8** [comment]
Hi bro, 

Changed the source and path of the project folder, ran flutter clean and also removed the .gradle folder, but still some error occurs. Please check the image here.

![Annotation 2019-12-18 115049](https://user-images.githubusercontent.com/43437325/71071639-08818500-218e-11ea-9671-c8679c0e6fbc.jpg)

**Comment by minhcasi** [comment]
@masthan8 - pls try to download latest Fluxstore 1.6 for this fixing 

Also, update the flutter to latest "flutter upgrade" and use the channel stable by running "flutter channel stable"
