### ISSUE TITLE
mstore pro - installation issue with packages download

### ISSUE THREAD

**Issue by masthan8** [inspireui/support#1618]
The app compile has some error and i have attached screenshts of it, pls check and help to resolve those

https://imgur.com/faXJcHD 

https://imgur.com/wGsLBR3

**Comment by masthan8** [comment]
![app issue 4](https://user-images.githubusercontent.com/43437325/70898159-2ff91600-2005-11ea-81d8-e3a1ee263461.jpg)

**Comment by masthan8** [comment]
hi this is the error after a clean installation...

**Comment by concuacon** [comment]
Hello, @masthan8 You can try with this step:
* Mstore Pro version
- Delete node_modules/ and re-install: npm install
- cd android; \.gradle clean; cd ..
- react-native run-andrioid
* Mstore Expo version:
- Delete node_modules and re-install: npm install
- npm install -g expo-cli
- expo start -c
**### Remember to check Android path**
