### ISSUE TITLE
[Flux-Store Multi Vendor] - Image provider.dart is causing the problem 

### ISSUE THREAD

**Issue by incepio-flutter** [inspireui/support#1619]
---------

**1. My issue:**
Things were going fine but I think after the release of new flutter update 1.12 some packages are not working fine after I downloaded the new updated version of fluxstore multivendor 1.2.0  I got this compiler message  I google the error and found out that changing   to  cached_network_image: ^2.0.0-rc.1 will solve me problem instead it reduced some errors in compiler but it didn't fully solved the problem!
@minhcasi Please help me here as well I will me thankful to you! 

Compiler message:
../../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-1.1.3/lib/src/cached_network_image_provider.dart:42:24: Error: The method 'CachedNetworkImageProvider.load' has fewer positional arguments than those of overridden method 'ImageProvider.load'.
  ImageStreamCompleter load(CachedNetworkImageProvider key) {
                       ^
../../../Documents/flutter/packages/flutter/lib/src/painting/image_provider.dart:403:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(T key, DecoderCallback decode);
                       ^
../../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image_library-0.1.8/lib/src/extended_memory_image_provider.dart:12:24: Error: The method 'ExtendedMemoryImageProvider.load' has fewer positional arguments than those of overridden method 'MemoryImage.load'.
  ImageStreamCompleter load(MemoryImage key) {
                       ^
../../../Documents/flutter/packages/flutter/lib/src/painting/image_provider.dart:704:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(MemoryImage key, DecoderCallback decode) {
                       ^
../../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image_library-0.1.8/lib/src/extended_file_image_provider.dart:13:24: Error: The method 'ExtendedFileImageProvider.load' has fewer positional arguments than those of overridden method 'FileImage.load'.
  ImageStreamCompleter load(FileImage key) {
                       ^
../../../Documents/flutter/packages/flutter/lib/src/painting/image_provider.dart:636:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(FileImage key, DecoderCallback decode) {
                       ^
../../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image_library-0.1.8/lib/src/extended_asset_bundle_image_provider.dart:35:24: Error: The method 'ExtendedExactAssetImageProvider.load' has fewer positional arguments than those of overridden method 'AssetBundleImageProvider.load'.
  ImageStreamCompleter load(AssetBundleImageKey key) {
                       ^
../../../Documents/flutter/packages/flutter/lib/src/painting/image_provider.dart:467:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(AssetBundleImageKey key, DecoderCallback decode) {
                       ^
../../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image_library-0.1.8/lib/src/extended_asset_bundle_image_provider.dart:87:24: Error: The method 'ExtendedAssetImageProvider.load' has fewer positional arguments than those of overridden method 'AssetBundleImageProvider.load'.
  ImageStreamCompleter load(AssetBundleImageKey key) {
                       ^
../../../Documents/flutter/packages/flutter/lib/src/painting/image_provider.dart:467:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(AssetBundleImageKey key, DecoderCallback decode) {
                       ^
../../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image_library-0.1.8/lib/src/extended_network_image_provider.dart:62:24: Error: The method 'ExtendedNetworkImageProvider.load' has fewer positional arguments than those of overridden method 'ImageProvider.load'.
  ImageStreamCompleter load(ExtendedNetworkImageProvider key) {
                       ^
../../../Documents/flutter/packages/flutter/lib/src/painting/image_provider.dart:403:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(T key, DecoderCallback decode);
                       ^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script '/Users/Ammar/Documents/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 780

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/Ammar/Documents/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 21s
Finished with error: Gradle task assembleDebug failed with exit code 1

2. Screenshots issues:
**before changing to cached_network_image: ^2.0.0-rc.1**
<img width="1443" alt="Screenshot 2019-12-16 at 1 04 47 PM" src="https://user-images.githubusercontent.com/57838430/70889531-a6494880-2004-11ea-8059-9bd96afd0157.png">
**after chaning to cached_network_image: ^2.0.0-rc.1**
<img width="1443" alt="Screenshot 2019-12-16 at 1 11 23 PM" src="https://user-images.githubusercontent.com/57838430/70889932-92eaad00-2005-11ea-95dd-2394d7a1726b.png">

3. Proof of my purchased:

3. Config files (optional)

**Comment by minhcasi** [comment]
Hi, please help to download the latest 1.2.0b to fix this issue - very best!
