### ISSUE TITLE
[Mstore Pro] - update user profile and login via sms?

### ISSUE THREAD

**Issue by Q8hma** [inspireui/support#1620]
is there way to let the user update his profile or any update is coming soon? 
and what about login via sms ?? when it will work after facebook close the door ?

thnx

3. Proof of my purchased: ca4abfe5-d915-4226-b092-90a7b3057723

**Comment by minhcasi** [comment]
Hi, we are going to release new Firebase SMS Login, hope it will be ready on this week

Other Editable profile will also implement and update soon - thank you!

**Comment by Q8hma** [comment]
thnx i hope you will do Editable user profile and address soon because we need it fast
