### ISSUE TITLE
[MStore-Pro] - I cannot start the CLI version of MS-Store

### ISSUE THREAD

**Issue by fernandoalfarocode** [inspireui/support#1621]
Hello, my problem is that I am trying to use the CLI version of Mstore Multivendor but I cannot start the APP on Android even though I have followed the instructions to apply the following commands specified in the Read me of the project:
yarn install
expo start
react-native run-android

I have the android studio and emulator environment installed and configured.
Thanks beforehand for your attention

Screenshots issues:
The app is built but there is an error building the main activity and the test APP fails
https://ibb.co/7knC1vs
https://ibb.co/27PXsn3

The app fails on the android test

**Comment by Haniel5** [comment]
Please help to share the proof of purchased screenshot from http://codecayon.net/downloads to save time and quick response. Thank you

**Comment by fernandoalfarocode** [comment]
Proof of purchase
![image](https://user-images.githubusercontent.com/11746905/70952464-ec65d280-202b-11ea-9ad9-7418ab865cfc.png)

**Comment by minhcasi** [comment]
@fernandoalfarocode - could i check if you could able to run the cli from the example app - https://facebook.github.io/react-native/docs/getting-started ?

**Comment by fernandoalfarocode** [comment]
It is only with the MStore CLI code that it fails me
![image](https://user-images.githubusercontent.com/11746905/71009534-00ebae80-20b0-11ea-87f7-11755ae3f442.png)

**Comment by fernandoalfarocode** [comment]
MStore CLI: Error Main activity not exist

![image](https://user-images.githubusercontent.com/11746905/71011446-0696c380-20b3-11ea-9c14-a1849a21e4ab.png)

**Comment by minhcasi** [comment]
@concuacon - pls give some suggestion - thank you!

**Comment by fernandoalfarocode** [comment]
Hello?

**Comment by concuacon** [comment]
@fernandoalfarocode if you run MStore Pro version, you try by these step:
- Clean gradle : cd android; \.gradlew clean; cd ../
- Re-build: react-native run-android

**Comment by fernandoalfarocode** [comment]
Perform the steps you told me but still generates error in the Main activity when doing build
![image](https://user-images.githubusercontent.com/11746905/71480233-ae9c4300-27bd-11ea-8ca2-352e60b7ed5d.png)

**Comment by fernandoalfarocode** [comment]
I have already tried to rebuild everything clean by downloading the source code again from envato market but it still generates the error despite this

**Comment by concuacon** [comment]
@fernandoalfarocode 
okay maybe I understand your problem, I think you should watch this video before starting (apply for Expo version)
https://www.youtube.com/watch?v=wVu4KK464SU
For Mstore Pro Cli version: https://stackoverflow.com/a/55016869/5295046
