### ISSUE TITLE
[MSTORE MV] - Issues with Uploads and Payments.

### ISSUE THREAD

**Issue by jadanjohnson** [inspireui/support#1623]
I've been having a few configuration challenges. 

**1. Variations from store not displaying**

I've repeated these steps multiple times to absolutely no success.  The variation in this case is 'Size'. 

<img width="360" alt="Converse ERX Impress High Top" src="https://user-images.githubusercontent.com/45473639/70940763-0d70f800-2019-11ea-8c4c-131a855ac395.png">

**2. Error message shows for all custom images I've uploaded.**
For instance I tried manually replacing the Splash screen in the src folder and this is what I received.

<img width="1024" alt="Screen Shot 2019-12-16 at 3 35 56 PM" src="https://user-images.githubusercontent.com/45473639/70941149-d4855300-2019-11ea-891a-504bc042eb04.png">

**3. Product Upload**
The image upload on the product page doesn't work. It doesn't click. Not sure how to resolve this. 
Additionally would it be possibly to have the vendor select the category and enter a custom field for product condition (eg. New or Used)?. 

**4. Custom Registration Field.** 
Is it possible to add custom fields to the registration form and can I default register as a vendor?. 

**5. How do you customize and link the circle categories to the right category?**

**6. I've tried change the categories menu style however It doesn't seem to work. 

I've posted a comment on Themeforest.

**Comment by Haniel5** [comment]
Please help to share the proof of purchased screenshot from http://codecayon.net/downloads to save time and quick response. Thank you

**Comment by jadanjohnson** [comment]
<img width="733" alt="Screen Shot 2019-12-16 at 6 36 34 PM" src="https://user-images.githubusercontent.com/45473639/70952032-0ce55b00-2033-11ea-8603-96f6ff38f99a.png">

**Comment by vumanhsn97** [comment]
@jadanjohnson 
1. Fixed it in next version
2. Make sure your file replace same name 'splash_creen.png'. Make sure you run app again
3. Not found your issue. Select category will update in future
4. No options
5. You need to change category id in src/common/config.js https://tppr.me/gDDRx. You can get your categories id in yourwebsiteurl/wp-json/wc/v2/products/categories look like http://demo.mstore.io/wp-json/wc/v2/products/categories

**Comment by jadanjohnson** [comment]
Thank you for your response. Could you please provide a timeline for this update? 

Also I've found some other glitches -- 

1) Image upload for vendors uploading products does not work. 
1a) Stripe also doesn't work.  I've included a screen-record [ https://streamable.com/woenz ] 

2) Currently it is not possible for users to change their profile image from the app. 

3) Any workaround -- It's super important for us to know that the person using our app is a student (we typically ask for a copy of their student ID and confirm their schools). 

4) All our users can 'buy and sell' so can we default registration status as Vendor. It's the default setting on our WordPress but on the app they have to select the register as a vendor option on the app. That's a bit counterintuitive.

**Comment by vumanhsn97** [comment]
@jadanjohnson 
1. It's working well. Can you share your AppConfig.json file?
2. App not support for edit user
3. Noway
4. You can change line code in src/containers/SignUp/index.js https://tppr.me/XWhTJ and https://tppr.me/LVR8p

**Comment by jadanjohnson** [comment]
I've attached.

**Comment by jadanjohnson** [comment]
Can I email the app config -- not allowing upload here. 

...and i'd really love to know the timeline for variations to work :) and for some of the custom features i'm asking for is that something i can perhaps hire a developer to integrate or do you guys offer a service?

**Comment by vumanhsn97** [comment]
@jadanjohnson You can email to vumanhsn97@gmail.com

**Comment by jadanjohnson** [comment]
Sent.

**Comment by jadanjohnson** [comment]
ANY FOLLOW UP ON THIS @vumanhsn97 ?

**Comment by inspireui-support** [comment]
fixed on next release - thank you!
