### ISSUE TITLE
[FluxStore 1.6.0] - Maps Location Address Issue , SMS Login Issue & Where to configure Other Login Methods

### ISSUE THREAD

**Issue by siyashamsudeen** [inspireui/support#1624]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:

A . In the address selection , im able to search the location but the selected location does not get marked or pinned on the map . whichever location i select it shows as unnamed location and it doesnt get filled to the address fields. i mentioned about this issue earlier as well and the support said i have to try on real device . i did try on real device now but it is still the same issue. 

Please see the below screenshot

<img width="600" alt="Screen Shot 2019-12-17 at 1 21 19 AM" src="https://user-images.githubusercontent.com/57159602/70944230-14752600-206c-11ea-9398-daf9cd4aa8c1.jpeg">

I have enabled all APIs required for the maps and have used the same API key on the configs, yet it is still the same. 

<img width="600" alt="Screen Shot 2019-12-17 at 1 21 19 AM" src="https://user-images.githubusercontent.com/57159602/70944037-b34d5280-206b-11ea-9f60-5eb55906c544.png">

B. SMS Login is not working - I did configure the firebase account , i created android app and placed the google file on the folder .
but when i try to do the sms login im getting the below error . I tried this on a real device and same error i get . 

<img width="600" alt="Screen Shot 2019-12-17 at 1 13 27 AM" src="https://user-images.githubusercontent.com/57159602/70948663-60789880-2075-11ea-8a5b-2a6c15a78175.png">
<img width="469" alt="Screen Shot 2019-12-17 at 1 14 31 AM" src="https://user-images.githubusercontent.com/57159602/70948664-61112f00-2075-11ea-9a2d-65cff7e872c3.png">

![Screenshot_1576534696](https://user-images.githubusercontent.com/57159602/70948147-3d011e00-2074-11ea-990b-ef3faff90495.png)

I've had added a test number in firebase console . and when i enter this test number it works and gets logged in which means the app can communicate with the firebase server successfully . 

<img width="979" alt="Screen Shot 2019-12-17 at 2 07 58 AM" src="https://user-images.githubusercontent.com/57159602/70948246-720d7080-2074-11ea-9dc8-a9bd53d8617f.png">

<img width="979" alt="Screen Shot 2019-12-17 at 2 07 58 AM" src="https://user-images.githubusercontent.com/57159602/70948251-76398e00-2074-11ea-8160-6089b686df3d.png">

<img width="1379" alt="Screen Shot 2019-12-17 at 2 07 26 AM" src="https://user-images.githubusercontent.com/57159602/70948264-7d609c00-2074-11ea-99c5-5495de6ef953.png">

C. Please tell me where and how can i configure Facebook Sign In , Google Sign In & Apple Sign in . i dont see any documentation or guide for these . 

Please provide a solution to these at the earliest 
 

2. Screenshots issues:

3. Proof of my purchased:

Downloads page 
<img width="1392" alt="Screen Shot 2019-12-14 at 12 26 07 AM" src="https://user-images.githubusercontent.com/57159602/70948488-fc55d480-2074-11ea-9dce-1e0c7a57352c.png">

Previously added comment screenshot

<img width="614" alt="Screen Shot 2019-12-13 at 1 50 50 AM" src="https://user-images.githubusercontent.com/57159602/70948454-ef38e580-2074-11ea-856d-40b4c6c22f6f.png">

3. Config files (optional)

Config.dart - http://finefair.le-pearl.com/app-files/config.dart
Config.json - http://finefair.le-pearl.com/app-files/config.json

the admin account details is sent to your email for another ticket. ticket # 1611

**Comment by minhtruong315** [comment]
To fix sms issues.
For android, Open project on firebase console. Then move to Settings/General. You need to upload SHA key to firebase project. You can follow this guide to generate SHA key https://developers.google.com/android/guides/client-auth
![Simulator Screen Shot - iPhone 11 - 2019-12-16 at 08 40 28](https://user-images.githubusercontent.com/10402500/70960459-a8b5ac00-20b1-11ea-9206-3b5302fff4ed.png)

**Comment by siyashamsudeen** [comment]
I added the SHA1 and SHA256 code but yet it is not working . Still giving the same errors . 

Kindly also update me on the Maps issues . Please help.

**Comment by Alnaggar94** [comment]
I have the same issue with Maps Location and it's not working even in your demo app (Fluxstore), It doesn't show anything just blank 

![5556](https://user-images.githubusercontent.com/49800146/71323187-8c66a480-24e1-11ea-90cb-9388ac0425e7.JPG)

**Comment by minhtruong315** [comment]
https://docs.inspireui.com/fluxstore/firebase/
please follow this guide to load map

**Comment by minhtruong315** [comment]
@siyashamsudeen please check my comment to fix sms login https://github.com/inspireui/support/issues/1624#issuecomment-566354675

You can follow by the guide to config social login
https://pub.dev/packages/flutter_facebook_login
this for facebook login.
https://pub.dev/packages/google_sign_in
this for google sign in
about apple sign in. it's having issues when run on real device. I will update it on next release

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
