### ISSUE TITLE
[Evastore] - product search crashes the app 

### ISSUE THREAD

**Issue by alisa140** [inspireui/support#1626]
My issues
1-  I launch the app for one of my clients and we found an issue that caueses the app to crash when ever we search using certain terms, such us: coconut oil, عنب

Screenshots:
https://tppr.me/Ls8rU
https://tppr.me/Qv4cs

My screenshot of the purchase product or my comment:
https://tppr.me/7dQEu

Config files (optional)
I have emailed you my source code

2- The Shipping Method disappears from the checkout view. You cannot progress to payement due to an alert "Please select shipping method". However, it appears if you modify your shipping address and save again. 

2. Screenshots:
https://tppr.me/eQRqA
https://tppr.me/Tdq1E
3. My screenshot of the purchase product or my comment:
https://tppr.me/7dQEu

3. Config files (optional)
I have emailed you my source code

**Comment by alisa140** [comment]
Gentlmen, any update on the issue?

**Comment by minhcasi** [comment]
@concuacon - pls help for checking as high priority (related to the email from alisa140) - thank you!

**Comment by alisa140** [comment]
the for the priority. let me know if I can be of any help

**Comment by concuacon** [comment]
@alisa140 Hello, 
1. You can download this file and replace it with your ProductItemContainer.js file
[ProductItemContainer.js.zip](https://github.com/inspireui/support/files/3993952/ProductItemContainer.js.zip)
2. In the file index.js (src / containers / CartContainer / MyCartMyCart / index.js) have you checked the _onPress function to see if the Shipping method has loaded?

**Comment by concuacon** [comment]
Hi, @alisa140  I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
