### ISSUE TITLE
[my-product] - 

### ISSUE THREAD

**Issue by waleedart** [inspireui/support#1627]
Hi, I followed steps in this URL: https://facebook.github.io/react-native/docs/getting-started.html ?

but i can't build the apk for android, attached screenshots.
![1](https://user-images.githubusercontent.com/357004/70970998-54aec580-20b9-11ea-90db-f936a8fc0c22.PNG)
![2](https://user-images.githubusercontent.com/357004/70970999-55475c00-20b9-11ea-8dbe-b892d4f421bc.PNG)

**Comment by vumanhsn97** [comment]
@waleedart It is working well. Please follow this toturial https://docs.expo.io/versions/latest/distribution/building-standalone-apps/
