### ISSUE TITLE
FluxStore1.6.0 :: Issue on Payment Methods

### ISSUE THREAD

**Issue by RahulDevCodiant** [inspireui/support#1629]
[payment_methods_response.txt](https://github.com/inspireui/support/files/3972119/payment_methods_response.txt)

The attached text file contains response of payment-methods. I am facing some issue while retrieving payment methods : 

'There is an issue with the app during request the data, please contact admin for fixing the issues'
![payment_error](https://user-images.githubusercontent.com/55129490/70976993-fd1d5380-20d2-11ea-81e8-fd14a5816afe.jpg)

**Comment by minhcasi** [comment]
Duplicate of #1630
