### ISSUE TITLE
Pre sales questions

### ISSUE THREAD

**Issue by Buuy** [inspireui/support#163]
Hi there, I'd like some presales questions answering please. 

1. Back-end - Powered by WP? 
2. Do I need to install the Dolkan Plugin?
3. Link to the iOS Version on CodeCanyon?
4. Can I set the commission we take in the back end? 
5. What exactly to you get after purchase - what files etc?
6. How to change splash screen, logo, colours, homepage icon etc of the app?
7. What about getting the .apk / de-bug files etc to upload to the playstore and the appstore?? - Where are these generated? 
8. Images of items on the demo app not appearing?
9. How does a new user join via the app - there is nothing clear on the app?? 
10. What about setting it all up - can you do this?
11. Is the app - when live - like Amazon?
12. Can the user add product via mobile or only website or both?
13. What about updates from you - how do we update the files for the apps??
14. Social Login - Facebook, Twitter etc via App - is this on the app for new users? 

- Justin

**Comment by Buuy** [comment]
Hello - 13 hours still no reply???

**Comment by thangvo9x** [comment]
Hi. Please provide your purchase code.

**Comment by Buuy** [comment]
These are Presales questions - Sorry I should of said.

**Comment by Buuy** [comment]
Hello - ??????

**Comment by minhcasi** [comment]
Hi, thank you for your all questions:

Back-end - Powered by WP? - YES
Do I need to install the Dolkan Plugin? YES
Link to the iOS Version on CodeCanyon? https://expo.io/@inspireui-demo/mstore-multivendor (you can use Expo account for testing on iOS inspireui-demo / inspireui
Can I set the commission we take in the back end? It will depends on the web template that you select
What exactly to you get after purchase - what files etc? The full react native source code - https://facebook.github.io/react-native/docs/getting-started.html - pls also note that the Web template should purchase separately 
How to change splash screen, logo, colours, homepage icon etc of the app? you can use our App builder - https://inspireui.com
What about getting the .apk / de-bug files etc to upload to the playstore and the appstore?? - Where are these generated? - you can use app builder for delivery
Images of items on the demo app not appearing? Please download latest demo
How does a new user join via the app - there is nothing clear on the app?? - There is the Logins screen that user can register 
What about setting it all up - can you do this? - No, the customize and set up is not included from our support scope
Is the app - when live - like Amazon? Not sure what you mean on this question
Can the user add product via mobile or only website or both? No, only web
What about updates from you - how do we update the files for the apps?? Not sure what you mean
Social Login - Facebook, Twitter etc via App - is this on the app for new users? Pls check the demo, facebook is support

**Comment by Buuy** [comment]
Hello 

I have some further questions. 

1. Does the app act like Amazon - a marketplace / different sellers etc?

2. Web / Theme template - ? Included or have to buy?

3. When you release an update - how do we update?

4. Please list what I need to download i.e. Wordpress, Dokan and anything else to make apps - Please list with URL's 

5. Windows app create?

6. Amazon app create?

7. Where create content for "About Us" / "Contact Us" / "News" etc - in WP backend?

8. Can admin create new pages for content? 

9. Master Admin panel - ?

10. Category create?
