### ISSUE TITLE
FluxStore 1.6.0 payment method issues

### ISSUE THREAD

**Issue by Abhiv66** [inspireui/support#1630]
1. My issue: I m facing issues on payment method its showing Can not get payment methods, Screenshot is attached below please support as soons as possible.
2. Screenshots issues:
![Screenshot_2019-12-17-15-02-15-373_com inspireui fluxstore](https://user-images.githubusercontent.com/58973413/70983607-057b8b80-20df-11ea-9fb1-0f38e90135eb.jpg)

3.Proof of purchase:
![img](https://user-images.githubusercontent.com/58973413/70984328-4627d480-20e0-11ea-8e46-2b076775e8c9.png)

**Comment by minhcasi** [comment]
@minhtruong315  - please help for checking - thank you!

**Comment by Abhiv66** [comment]
Please help and reply as soon as possible can't work without payment gateway issue

**Comment by minhtruong315** [comment]
@Abhiv66 can u send me config.dart file?

**Comment by Abhiv66** [comment]
yeah i have sent it to truong@inspireui.com please reply and solve this problem

**Comment by Abhiv66** [comment]
@minhcasi  @minhtruong315 when u will solve my issues may i know ? i m facing lot of issues in code revert as soon as possible

**Comment by minhcasi** [comment]
@Abhiv66 - try to send your whole source code and Admin login to truong@inspireui.com - we will help for checking.

Pls notice that on Magento some payment could may not work well that we could not support (as the limitation from Magento API)

- thanks

**Comment by minhcasi** [comment]
Also send to support@inspireui.com - thanks

**Comment by Abhiv66** [comment]
I have sent to email with source code and admin to both support@inspireui.com and  truong@inspireui.com revert and solve the issue right now please its too urgent can't wait anymore now

**Comment by Abhiv66** [comment]
and how can you say this Pls notice that on Magento some payment could may not work well that we could not support (as the limitation from Magento API)   is COD,Razorpay not supported then how can you write that magento is supportable with this FluxStore Pro 1.6.1 @minhcasi

**Comment by minhtruong315** [comment]
You can follow this comment to add razorpay payment
https://github.com/inspireui/support/issues/1541#issuecomment-567266615

**Comment by Abhiv66** [comment]
I checked this method  right now that you mentioned is not working i checked it perfectly 3 times please tell me perfect solution right now do not delay it please my business is getting hampering totally and product not launched yet due to payment issues and product options. revert soon

**Comment by minhtruong315** [comment]
@Abhiv66 please replace models/address.dart like this to fix issue payment gateway
[address.dart.zip](https://github.com/inspireui/support/files/3990985/address.dart.zip)

**Comment by Abhiv66** [comment]
I replaced but first tell me how can you close this ticket @minhcasi and @minhtruong315  ? my issues are not completely solved.

**Comment by minhtruong315** [comment]
send me config.dart file

**Comment by Abhiv66** [comment]
@minhtruong315  sent you in an email check pls

**Comment by Abhiv66** [comment]
Will you revert me now ? @minhtruong315

**Comment by minhtruong315** [comment]
@Abhiv66 I dont see your email. pls send config.dart file via email: truong@inspireui.com with subject: https://github.com/inspireui/support/issues/1630

**Comment by Abhiv66** [comment]
what the hell you making this type of excuse to delaying the issues i sent you email and you have also replied me on that can u give me issue ticket.Check your mail i am sending now again on  truong@inspireui.com

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response in email after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
https://tppr.me/zppif

**Comment by Abhiv66** [comment]
First tell when u did'nt responded for sunday then should we have taken any action ? open this ticket right now else i will make 100 of tickets with my issues already you hampered our product so don't talk this way okay @minhtruong315 @minhcasi 
@minhtruong315  co-ordinate with your team what is happening with this #1630 ticket and my all issues are not solved then how can you close my ticket ? did you solved payment issue ? did you solved cart issue ? did you solved all my issues i sent you on email ?

Remember if we take any actions you have to give refund and also have to bear our losses that we ha ve had due to delay in launching product. so don't close my tickets until the all issues are solved thankyou
