### ISSUE TITLE
FluxStore 1.6.0 payment methods not showing

### ISSUE THREAD

**Issue by itej7** [inspireui/support#1632]
1. My issue: I m facing issues on payment method its showing Can not get payment methods, Screenshot is attached below please support as soon as possible.

2. Screenshots issues:
![screen1](https://user-images.githubusercontent.com/50324759/71000017-9151df80-2100-11ea-9201-b5dbd7733611.png)

3. Proof of my purchased:
Product Purchase code: c2f1abaf-6ebe-4c07-875d-050022ba2a14 - 14 Oct 2019 REGULAR LICENSE

**Comment by minhcasi** [comment]
@minhtruong315 - please help for checking

**Comment by minhtruong315** [comment]
@itej7 can you send me config.dart file?

**Comment by itej7** [comment]
@minhtruong315 -- Please find below config files.
[Fluxstore 1.6.0 config files.zip](https://github.com/inspireui/support/files/3977217/Fluxstore.1.6.0.config.files.zip)

**Comment by itej7** [comment]
@minhtruong315  Also find below link of screen recorder.

https://drive.google.com/open?id=1r2QPZNuip68saToxUlCPTkKN6YcCPtQc

**Comment by itej7** [comment]
@minhtruong315 : We have 1. replaced payment.dart in screens/checkout/payment.dart and 2. replaced index.dart in widgets/payment/razorpay/index.dart but we are still not able to redirect to order confirmation page once the payment is done through razorpay.

[index.dart.zip](https://github.com/inspireui/support/files/3978263/index.dart.zip)
[payment.dart.zip](https://github.com/inspireui/support/files/3978264/payment.dart.zip)

Please see the output of screen recorder as well. 
https://drive.google.com/open?id=1rejuXKOXGBWx5SKGtOc4UMRh6ioPwoXR

**Comment by minhtruong315** [comment]
https://github.com/inspireui/support/issues/1541#issuecomment-567266615
try this solution - thanks

**Comment by itej7** [comment]
@minhtruong315 :  we are trying this solution. Please dont close this ticket.
