### ISSUE TITLE
[fluxstore] - how to make archive for Apple appstore submission

### ISSUE THREAD

**Issue by netdreamland** [inspireui/support#1633]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: I have almost finished the configuration and tested the app on simulator with Android Studio. Now I would like to upload to appstore for test flight, however it could not build archive by Xcode.

Is there alternative way to build archive or fix for Xcode?

2. Screenshots issues:
![image](https://user-images.githubusercontent.com/12180247/71016956-d7269c00-2130-11ea-9e4d-6e6082239831.png)

3. Proof of my purchased:
![image](https://user-images.githubusercontent.com/12180247/71017340-6764e100-2131-11ea-8f2a-efa54291d209.png)

3. Config files (optional)

**Comment by minhcasi** [comment]
@netdreamland - did you run the "flutter build ios" before archive by XCode?

Please discover more detail from https://flutter.dev/docs/deployment/ios - thank you!

**Comment by johnsonyick** [comment]
hi @minhcasi the answer is Yes
i did also try **flutter build ios --release** but no way to archive

**Comment by minhcasi** [comment]
@johnsonyick pls try these following solutions:

1. Run "flutter clean" to clean up the cache
2. Update the latest flutter to latest "flutter upgrade" and use the channel stable by running "flutter channel stable"
3. remove the Pod folder and Podfile from ios folder, then run "pod install" again.
4. Try to run the project by using Android Studio as our document guide

Let us know your checking - thank you!

**Comment by johnsonyick** [comment]
hi @minhcasi 
Thanks for your suggestion.
i have no problem with running with android, but please refer to the question, i am going to submit to App Store, it could not be signed and upload without Xcode.
So does it mean the app i purchased could not publish to AppStore?

**Comment by johnsonyick** [comment]
hi there
any one could answer my question?

**Comment by minhcasi** [comment]
@johnsonyick - sorry for the latest response, please help to check this guide for Appstore delivery - https://www.youtube.com/watch?v=dR04ArAhxd4&t=1s

The publish on appstore is quite easier than on google play, you only need to change the bunndle id + app name + register the Team Name with your Developer Account

**Comment by netdreamland** [comment]
okay! i will figure out how to fix it, thanks!
