### ISSUE TITLE
[MStore Pro] - Two problems with RTL in the Arabic interface

### ISSUE THREAD

**Issue by vip6009** [inspireui/support#1634]
1. My issue:
A- There is a problem with the ordering detail right-aligned.
B- A problem with writing on pictures in the Arabic language starts from half of the image and the rest of the sentence disappears.

2. Screenshots issues:
![01](https://user-images.githubusercontent.com/38435683/71019948-fce97c00-2103-11ea-872e-0e7763a9b658.jpg)

![02](https://user-images.githubusercontent.com/38435683/71019949-fd821280-2103-11ea-8947-fccd7836877e.jpg)

3. Proof of my purchased:
Purchase code: 75b6618e-****-****-bea2-b19bdf10bb7e
![00](https://user-images.githubusercontent.com/38435683/71020370-d6781080-2104-11ea-84fb-ac008ed54f2b.jpg)

**Comment by minhcasi** [comment]
@concuacon - please help to check the issue - thank you!

**Comment by concuacon** [comment]
@vip6009 I checked CSS and fix it, you download new file, replace and re-build 
- Replace file in src/components/HorizonLayout/styles.js
[style.js.zip](https://github.com/inspireui/support/files/3994753/style.js.zip)
- Replace file in src/containers/OrderDetail/styles.js
[styles.js.zip](https://github.com/inspireui/support/files/3994750/styles.js.zip)
- Replace file src/components/ConfirmCheckout/styles.js
[styles.js.zip](https://github.com/inspireui/support/files/3994755/styles.js.zip)

**Comment by concuacon** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
