### ISSUE TITLE
[BeoNews] - Can't create the app and get it running  

### ISSUE THREAD

**Issue by dermayank** [inspireui/support#1636]
It's been two weeks since I have been working on the Beonews project, but I still cannot the get app in running state.
I have been receiving the following errors:

sometimes this:
![Screenshot from 2019-12-13 12-23-51](https://user-images.githubusercontent.com/24271097/71061429-facbff80-218d-11ea-8adb-6e644befabf6.png)

and sometimes this:
![Screenshot from 2019-12-14 12-48-38](https://user-images.githubusercontent.com/24271097/71061522-38308d00-218e-11ea-98ff-599d999e7a31.png)
I have updated the react-native version to that of javascript in package.json file.

I have followed all the general steps:
1) Quick Setup
2) Getting Started
3) Wordpress Setting(not enabled the One Signal)

Now, I have the following questions including the above issues:

1) Is it mandatory to follow all the steps that are mentioned in Customization sections or Genera steps are sufficient enough to get the app in running the state?
2) Is it necessary to install and enable one signal push notification?
3) I installed the latest Cebuiled and in the customization section, it didn't show me the preview images.

I have attached my package.json file below:
https://easyupload.io/xq3ovu

Please provide me some solution ASAP as we are already running late.

Proof of purchase
https://user-images.githubusercontent.com/24271097/70776717-dcd45880-1da3-11ea-8911-d4318e625889.png

**Comment by minhcasi** [comment]
@concuacon - please help for checking - thank you!

**Comment by concuacon** [comment]
hello, @dermayank I sent you a new source to your mail joshimayank456@gmail.com please check your mailbox.

**Comment by dermayank** [comment]
Thanks. It's working now.
