### ISSUE TITLE
[fluxstorelisting] - requested access to gitlab almost 2 weeks ago

### ISSUE THREAD

**Issue by codingastronaut** [inspireui/support#1637]
> I have requested access to gitlab for fluxstorelisting almost 2 weeks ago, still without access to the project on gitlab, I've waited very long, please can it be sent to my email (promiseemekaigbokwe[at]gmail.com)

Proof of purchase:  https://i.imgur.com/SMeqtuH.jpg

Please it's very important.

**Comment by codingastronaut** [comment]
i just requested again, still waiting for a response.

**Comment by minhcasi** [comment]
Thanks, got your request, i will update soon

**Comment by codingastronaut** [comment]
I haven't still gotten access to the project I would like to start work on it soon please

**Comment by codingastronaut** [comment]
Im so sorry it's not flux news it's flux listing

**Comment by codingastronaut** [comment]
do you guys have a skype or facebook for faster response?
response on GitHub is too slow, please

**Comment by codingastronaut** [comment]
Hello guys @minhcasi @luyx2412 @vumanhsn97  it's been almost a full day, any luck?

**Comment by minhcasi** [comment]
@codingastronaut - sorry for the late response - we have update the request, there will be new coming update will be updated shortly on next couple of day - thank you!

**Comment by codingastronaut** [comment]
okay, but could you give me access to the gitlab, so i can at least show my client something?

**Comment by codingastronaut** [comment]
codecanyon is blocking downloads in my country

**Comment by Amitjeypore** [comment]
Hi, Please accept my Gitlab request to update my app, have submitted few days ago.
