### ISSUE TITLE
[FluxNews] - Categories and images not showing and other issues

### ISSUE THREAD

**Issue by Cri00** [inspireui/support#1638]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: 

Regarding the menu:
- the burger menu does not include all categories from the blog.
- the main screen when launching the app does not contain all categories.
- under the category screen there not shown all categories.
- not all images are loaded when opening the app.
- cannot modify the order of the blog categories.

2. Screenshots issues:

![Annotation 2019-12-15 193839](https://user-images.githubusercontent.com/6515758/71081616-3d92d500-2198-11ea-9e9d-f194ad8c82e5.png)
![Annotation 2019-12-15 1936402](https://user-images.githubusercontent.com/6515758/71081617-3d92d500-2198-11ea-826d-e698ea963553.png)
![Annotation 2019-12-15 193608](https://user-images.githubusercontent.com/6515758/71081618-3d92d500-2198-11ea-885a-ea269df04e80.png)
![Annotation 2019-12-15 193640](https://user-images.githubusercontent.com/6515758/71081619-3d92d500-2198-11ea-9dbd-6e746ba02269.png)
![Annotation 2019-12-15 193931](https://user-images.githubusercontent.com/6515758/71081621-3e2b6b80-2198-11ea-9cf3-a2a7bdb347fa.png)

3. Proof of my purchased:

![Capture](https://user-images.githubusercontent.com/6515758/71081683-66b36580-2198-11ea-9f85-25402785f37c.PNG)

4. Config files (optional)

https://wetransfer.com/downloads/c6d0eef8b6ffba72aa86fc428b17beb120191218111959/be6329722ceb823fa41784487d45b41f20191218112000/641851

**Comment by incepio-flutter** [comment]
have you install regenerate thumbnail plugin ?

**Comment by Cri00** [comment]
I will reinstall, but please help us with the rest of the issues too.

**Comment by incepio-flutter** [comment]
kindly post the other issues in a proper manner like 
1 
2 
3

**Comment by Cri00** [comment]
1. The burger menu does not include all categories from the blog.
2. The main screen when launching the app does not contain all categories.
3. Under the category screen there not shown all categories.
4. Cannot modify the order of the blog categories.

**Comment by minhcasi** [comment]
@Cri00 - pls help to check the document guide from https://docs.inspireui.com/fluxnews/getting-started/ to check if you install all the plugins correctly.

The app will use the Post Feature Image to display the image, pls make sure to attach it from the post and run the Regenerate image as a document guide to optimizing the images

Let us know your checking - thanks

**Comment by dttrung26** [comment]
Close due to inactivity. Feel free to re-open if you are still facing this issue. 
Many thanks,
Trung.
