### ISSUE TITLE
[MStore Multi Vendor - Complete React Native template for WooCommerce] - feature image not showing

### ISSUE THREAD

**Issue by waleedart** [inspireui/support#1639]
Hi, feature image not showing, i installed the plugin and made generating for the thumbnails but still now showing, just showing white.

**Comment by minhcasi** [comment]
@waleedart - could you help to attach your config file so that we could help for checking - thanks

**Comment by parveenkrraina** [comment]
Hi I am also facing the same issue.
![Snag_10508ef9](https://user-images.githubusercontent.com/41342012/71195767-9d7e9e00-22b4-11ea-822a-f3731ed5f9b5.png)
![Snag_1050b676](https://user-images.githubusercontent.com/41342012/71195779-a2dbe880-22b4-11ea-8a06-9fd04d5a8e61.png)
![Snag_1050e3ff](https://user-images.githubusercontent.com/41342012/71195791-a96a6000-22b4-11ea-8686-7806f7d4cf57.png)
Please fix ASAP

**Comment by vumanhsn97** [comment]
@parveenkrraina Can you share your config.dart file?

**Comment by waleedart** [comment]
> @waleedart - could you help to attach your config file so that we could help for checking - thanks
I can't upload the file i will copy and past  here

{
  "WooCommerce": {
    "url": "http://elsaghah.club/",
    "consumerKey": "ck_30b38066a5348686b9d37ad3a3f432d50a4ddba6",
    "consumerSecret": "cs_b96d21732b84f1eeac5478b61870ff6dd8f74004",
    "isWCFM": true
  },
  "HorizonLayout": [
    {
      "name": "Accessories",
      "layout": 13,
      "categoryOrTag": 115,
      "featured": true
    },
    {
      "name": "Accessories",
      "layout": 6,
      "categoryOrTag": 115,
      "featured": true
    },
    {
      "name": "Accessories",
      "image": "",
      "layout": 6,
      "categoryOrTag": 115,
      "featured": true
    },
    {
      "name": "Accessories",
      "image": "",
      "layout": 2,
      "categoryOrTag": 115,
      "featured": true
    },
    {
      "name": "Accessories",
      "image": "",
      "layout": 8,
      "categoryOrTag": 115,
      "featured": true
    }
  ],
  "MainColor": "#00BCD4"
}

**Comment by parveenkrraina** [comment]
> @parveenkrraina Can you share your config.dart file?

Thanks.

I was able to fix.

**Comment by waleedart** [comment]
Please i changed the woo-commerce key to below:

{
"WooCommerce": {
 "url": "http://elsaghah.club/",
"consumerKey": "ck_4d151c80bd2fa95ea9b2e96e0850375b2074efb5",
"consumerSecret": "cs_fe630b57f00ee356f6dc5f2887e1ad70718a0326",
"isWCFM": true
},
"HorizonLayout": [
{
"name": "Accessories",
"layout": 13,
"categoryOrTag": 115,
"featured": true
},
{
"name": "Accessories",
"layout": 6,
"categoryOrTag": 115,
"featured": true
},
{
"name": "Accessories",
"image": "",
"layout": 6,
"categoryOrTag": 115,
"featured": true
},
{
"name": "Accessories",
"image": "",
"layout": 2,
"categoryOrTag": 115,
"featured": true
},
{
"name": "Accessories",
"image": "",
"layout": 8,
"categoryOrTag": 115,
"featured": true
}
],
"MainColor": "#00BCD4"
}

**Comment by waleedart** [comment]
Hi, any news about my issue, it takes too long time.

**Comment by vumanhsn97** [comment]
https://tppr.me/9Hb8b
Every thing work fine. Please check again

**Comment by PHPJunior** [comment]
Same Issue
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-01-04 at 01 46 13](https://user-images.githubusercontent.com/13845077/71743927-26403100-2e94-11ea-8e5a-ebded66f8ff7.png)
