### ISSUE TITLE
[Listapp] events are not updated

### ISSUE THREAD

**Issue by paniri** [inspireui/support#164]
Hi,
I have Mylist theme and Lispapp,
My events do not appear in my app, only the event from the demo site.

There seems to be no synchronization of events between the WordPress site and Listapp

(I changed the root to my website url, Rows titles do change with Listapp manger..but not the content)

Thanks

**Comment by thangvo9x** [comment]
Hi, Please provide your purchase code.
Thanks

**Comment by paniri** [comment]
![screenshot_20190108-141619_expo 1](https://user-images.githubusercontent.com/33451257/50830412-6ab3f200-1350-11e9-8d6a-28117c995f8c.jpg)
![screenshot_20190108-141629_expo 1](https://user-images.githubusercontent.com/33451257/50830428-743d5a00-1350-11e9-854c-aba88f15dc20.jpg)

**Comment by thangvo9x** [comment]
Hi. I don't still receive your Config.js file. your mean is the images not displayed, huh ? 
Thanks

**Comment by paniri** [comment]
App cannot display listings at all(my list theme), it can show only the news..

I tried almost anything, thanks for your help
 
config file:
https://drive.google.com/file/d/1G-iW7l-N3UdX18HYx6RHhMESJzJNpINm/view?usp=sharing

**Comment by thangvo9x** [comment]
Hi, please let me know your email.

**Comment by paniri** [comment]
I also sent a meassge to the email support:

paniri@gmail.com

**Comment by jabirismail** [comment]
Hi Paniri,
Even I had the same issue, It is because expo is caching the old data.
You can uninstall and re install expo and try.After doing this it cleared old demo data for me but my actual data is loading now..

**Comment by thangvo9x** [comment]
@paniri . let me know if it works. Thanks
