### ISSUE TITLE
[my-product] - Fluxstore

### ISSUE THREAD

**Issue by ukveda** [inspireui/support#1640]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: uable to install the fluxstore zip file on my woocommerce dashboard, please provide proper way to install it.

2. Screenshots issues: 
![screencapture-khadibrand-in-wp-admin-update-php-2019-12-05-15_03_23](https://user-images.githubusercontent.com/58551104/71158554-28867680-226a-11ea-8fbb-40292d69bef2.png)

3. Proof of my purchased: 580c8e49-f3bf-423c-a6c4-9dcdcbed4851

3. Config files (optional)

**Comment by minhcasi** [comment]
@ukveda - could you help to check this guide for the installing guide - http://docs.inspireui.com/fluxstore

Could you able to run the website so far? It seems the screenshot is related to your website issue - thanks

**Comment by ukveda** [comment]
There is no issue with the website, it is live and running properly as it is an e-commerce website we properly check and maintain it.

**Comment by minhcasi** [comment]
@ukveda  - pls share more detail about the issues + your app config files, as the screenshot provide is from your website that there is no clue for us with the helping - thank you!
