### ISSUE TITLE
Mstore pro App not create through cebuilder or android studio

### ISSUE THREAD

**Issue by vaibhavaparashar** [inspireui/support#1641]
I am tryin to start expo or mstore pro to build app but some error show i didn't know how to solve this error i am attaching error please solve my issue

in expo when use command expo start window open and after 2sec window is black nad console show this error

C:\Users\abc\Documents\mstore-3.9.6\mstore-expo>expo start
Starting project at C:\Users\abc\Documents\mstore-3.9.6\mstore-expo
Expo DevTools is running at http://localhost:19002
Opening DevTools in the browser... (press shift-d to disable)
Error: Problem validating fields in app.json. See https://docs.expo.io/versions/
v35.0.0/workflow/configuration/
 • Field: ios.bundleIdentifier - 'ios.bundleIdentifier' should be a iOS bundle i
dentifier notation unique name for your app. For example, host.exp.exponent, whe
re exp.host is our domain and Expo is our app..
error Invalid regular expression: /(.*\\__fixtures__\\.*|node_modules[\\\]react[
\\\]dist[\\\].*|website\\node_modules\\.*|heapCapture\\bundle\.js|.*\\__tests__\
\.*)$/: Unterminated character class. Run CLI with --verbose flag for more detai
ls.

Metro Bundler process exited with code 1
Set EXPO_DEBUG=true in your env to view the stack trace.

![image](https://user-images.githubusercontent.com/6870646/71158528-f8eb5600-21f8-11ea-81d7-fc6118fd3ff8.png)

i am set EXPO_DEBUG=true but error is not resolve.

and also try to build mstore pro error show 

![image](https://user-images.githubusercontent.com/6870646/71159028-d0179080-21f9-11ea-82ce-21382ecdc96f.png)
 
please help me 

Item Purchase Code:
011a05cf-cfa5-4395-97b8-3fb4773526e5

![image](https://user-images.githubusercontent.com/6870646/71159214-14a32c00-21fa-11ea-836f-b067522e7450.png)

**Comment by minhcasi** [comment]
@concuacon - please help for checking - thanks

**Comment by vaibhavaparashar** [comment]
> @concuacon - please help for checking - thanks

which type of help

**Comment by vaibhavaparashar** [comment]
please update asap cause i want to upload app on google play

**Comment by concuacon** [comment]
@vaibhavaparashar  
Have you read through the docs of Expo? 
Have you installed Android Studio? 
can you show me your app.json file?
ios.bundleIdentifier you are using my if you do not build the ios app please delete it.
This issue seems to be because you have not installed Android studio

**Comment by vaibhavaparashar** [comment]
i read documentation and also i have android studio, i sent you mstore expo app.json in zip format 
[app.zip](https://github.com/inspireui/support/files/3995867/app.zip)

and mstore pro app.jso file in zip format
[app.zip](https://github.com/inspireui/support/files/3995870/app.zip)

**Comment by concuacon** [comment]
@vaibhavaparashar 
If you use the Expo version just to build android, you must delete all ios settings and re-build.

**Comment by vaibhavaparashar** [comment]
i am using both expo and pro version, if i am using expo version then how to delete ios settings did you mean delete ios folder from expo folder.

**Comment by concuacon** [comment]
@vaibhavaparashar No, expo version haven't folder ios, I mean ios settings in app.json file. You are leaving the bundle id empty, which prevents you from building

**Comment by vaibhavaparashar** [comment]
> @vaibhavaparashar No, expo version haven't folder ios, I mean ios settings in app.json file. You are leaving the bundle id empty, which prevents you from building

Ok i'll try

**Comment by concuacon** [comment]
@vaibhavaparashar it works?

**Comment by vaibhavaparashar** [comment]
> @vaibhavaparashar it works?

Not properly work, some issue show which is solved by me but always metro run mstore app while i am upload my logo and other things, after that i am trying mstore pro in android studio but error show.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> C:\Users\abc\Documents\mstore-3.9.6\mstore-pro\android\app\src\main\res\values
\styles.xml:8:5: Error: Content is not allowed in trailing section.

i want to make apk for android not build from expo or pro.

**Comment by vaibhavaparashar** [comment]
i will send you working video what is exactly problem occur.

**Comment by vaibhavaparashar** [comment]
This Video link what exactly problem i am facing.

https://youtu.be/Z_IHbgh8GJA

I want to create mstore pro not expo

**Comment by concuacon** [comment]
@vaibhavaparashar 
For Mstore Pro : 
- Delete node_modules/
- open cmd in the path of folder Mstore re-install node_module: yarn install
- clean Gradle: cd android; ./gradlew clean; cd ../
- Build: react-native run-android

**Comment by vaibhavaparashar** [comment]
> @vaibhavaparashar
> For Mstore Pro :
> 
> * Delete node_modules/
> * Open cmd in the path of folder Mstore re-install node_module: yarn install
> * Clean Gradle: cd android; ./gradlew clean; cd ../
> * Build: react-native run-android

Okay I'll try and let you know

**Comment by vaibhavaparashar** [comment]
![image](https://user-images.githubusercontent.com/6870646/71515283-59147480-2857-11ea-8627-19500e8996b2.png)

**Comment by vaibhavaparashar** [comment]
How much time you want to solve my problem if you not able to resolve my problem then clear to me. Thanks

**Comment by minhcasi** [comment]
@vaibhavaparashar - pls try your best to run the example project from this guide https://facebook.github.io/react-native/docs/getting-started - this setup is to make sure your all libraries install correctly 

If it works well then try to download the latest version 3.9.7 and use our document for the installing - https://docs.inspireui.com/mstore/getting-started/

**Comment by vaibhavaparashar** [comment]
> @vaibhavaparashar - pls try your best to run the example project from this guide https://facebook.github.io/react-native/docs/getting-started - this setup is to make sure your all libraries install correctly
> 
> If it works well then try to download the latest version 3.9.7 and use our document for the installing - https://docs.inspireui.com/mstore/getting-started/
> 
> > <img alt="" width="48" src="/react-native/img/favicon.ico">**[Getting Started · React Native](https://facebook.github.io/react-native/)**This page will help you install and build your first React Native app. If you already have React Native installed, you can skip ahead to the [Tutorial](/react-native/docs/tutorial).
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/1d558b97f234c93d69c700738dea9d43e3669697/687474703a2f2f67686f73742e6c6f63616c3a383030302f696d616765732f6d6574612f47686f73742d446f63732e6a7067">InspireUI Document**[MStore Pro - Complete React Native template for e-commerce](http://ghost.local:8000/mstore/getting-started/)**Professional Mobile Store Solution for your business – supports to convert your current WooCommerce website to mobile store app easily

I also check all documentation but gradle is not working and also download new version of mstore pro.

![image](https://user-images.githubusercontent.com/6870646/71659039-e3972100-2cfa-11ea-9653-e8178f1ea78a.png)

![image](https://user-images.githubusercontent.com/6870646/71659045-eb56c580-2cfa-11ea-9116-864559c9d13c.png)

**Comment by minhcasi** [comment]
@vaibhavaparashar - sorry for missing your ticket - could i confirm if your window is 64bit, it sometimes has a problem with window OS.

@luyx2412 - do you have any suggestion

**Comment by luyx2412** [comment]
Hi @vaibhavaparashar Please open your Android studio and config your Android development. I saw your issues related the Android studio could not download library. This is some guide how to configure React native on Window https://shift.infinite.red/getting-started-with-react-native-development-on-windows-90d85a72ae65?gi=df48fef3d959

**Comment by luyx2412** [comment]
Feel free to reopen the issue.
