### ISSUE TITLE
Flutterstore - loader text keep showing

### ISSUE THREAD

**Issue by axebelk** [inspireui/support#1642]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
In home page loading text is keep showing. I used the config_theme3.json file.
2. Screenshots issues:
![image](https://user-images.githubusercontent.com/47109263/71181587-71562380-229a-11ea-83c1-ddc02b93f733.png)

3. Proof of my purchased:

3. Config files (optional)

**Comment by vumanhsn97** [comment]
@axebelk Quickly fix: Change your file in lib/widgets/home/vertical/printerest_layout.dart to 
[pinterest_layout.dart.zip](https://github.com/inspireui/support/files/3986728/pinterest_layout.dart.zip)

**Comment by axebelk** [comment]
Given quick fix is fixed the issue
