### ISSUE TITLE
ListApp 1.7 - Error while installing 

### ISSUE THREAD

**Issue by hatrednuow** [inspireui/support#1643]
---------

1. My issue: grpc error while installing

2. Screenshots issues:
![image](https://user-images.githubusercontent.com/3086835/71185222-9902b700-22ad-11ea-9ea2-c0fee2d379c2.png)

3. Proof of my purchased:
will email the purchased code
3. Config files (optional)

**Comment by minhcasi** [comment]
Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads  it's used to verify your proof of purchase? sorry for any inconvenience - Thank you!

**Comment by hatrednuow** [comment]
![photo_2019-12-20 10 24 53](https://user-images.githubusercontent.com/3086835/71227831-072d9500-2313-11ea-921c-a6e09574417d.jpeg)
Here the screenshot

**Comment by hatrednuow** [comment]
now, how to fix this error?

**Comment by hatrednuow** [comment]
![image](https://user-images.githubusercontent.com/3086835/71228313-6049f880-2314-11ea-9ee3-435a9a83507e.png)

**Comment by minhcasi** [comment]
@hatrednuow - please help reinstall nodejs 12.x to fix the issue - http://nodejs.org/

**Comment by hatrednuow** [comment]
Not working either, screenshot attached in github support page, please tell
me or can you update your app to your lates version of dependencies and
others things tonmake it works?

Thanks & Regards

**Comment by minhcasi** [comment]
@hatrednuow - sorry for the late response - please help to update latest 1.7.5 that fix most of the version of latest Expo version - thank you for your patient
