### ISSUE TITLE
[FluxStore Pro][Android] - Two applications on the same device (noob question)

### ISSUE THREAD

**Issue by VenyaminBlubinest** [inspireui/support#1644]
1. My issue:
I have two applications of Flux Store Pro (1.6).

The first one is connected to a Wordpress site (woocomerce).

The second is connected to a Magento 2 site.

When I install & run an application, it always replaces the other.
(because both have the same name and package)

What package files do I need to change to be independent applications?

Thanks for your time

2. Proof of my purchased:
![image](https://user-images.githubusercontent.com/51170169/71186883-beb3a000-225c-11ea-801d-79810ef4d3d9.png)

**Comment by minhcasi** [comment]
@VenyaminBlubinest - thank for the question, i think it is possible to change the bundle id should be fine, pls check this guide - https://docs.inspireui.com/fluxstore/customization/

Do you see any error when run both? Also try to replace fstore from pubspec.yaml and 'package:fstore/' from the import.

Let us know your checking, thank you!
