### ISSUE TITLE
[MStore] - User register problem (Welcome undefined)

### ISSUE THREAD

**Issue by w3bit** [inspireui/support#1645]
1. My issue:
When a user registers at the app, after sending signup form, it shows a toast message "Welcome, undefined", and new user doesn't exist at wordpress user list.

2. Screenshots issues:
![image](https://user-images.githubusercontent.com/457608/71194240-d44ab900-22a0-11ea-8ada-facc38f95b1d.png)

3. Proof of my purchased:
![screenshot-codecanyon net-2019 12 19-20_40_57](https://user-images.githubusercontent.com/457608/71194032-6d2d0480-22a0-11ea-99cc-70a243fbd0c5.png)

**Comment by minhcasi** [comment]
@concuacon - please help for checking - thank you!

**Comment by waleedart** [comment]
I had also the same problem, i spent two days searching without any solution, please help me and other in this issue.

**Comment by concuacon** [comment]
@w3bit @waleedart 
- Please update the latest Mstore-api.
- Download thisWPUserAPI.js file and replace the old file then rebuild the application
[WPUserAPI.js.zip](https://github.com/inspireui/support/files/3994472/WPUserAPI.js.zip)

**Comment by w3bit** [comment]
It's ok now. Thanks.
