### ISSUE TITLE
Not getting better support If can't solve issue,Initiate my refund any how

### ISSUE THREAD

**Issue by Abhiv66** [inspireui/support#1647]
1. My issue:
#1630 #1646 #1635 not solved......Please if it can't be solved then i will take actions on it 
 

2. Screenshots issues:
Already given in tickets mentioned

3. Proof of my purchased:
Already given in tickets mentioned

4. Config files (optional)
Already sent email

**Comment by minhcasi** [comment]
Duplicate of #1630

Btw, you can submit this link if not happy with the product - https://help.market.envato.com/hc/en-us/articles/202821460-Can-I-Get-A-Refund- - thanks
