### ISSUE TITLE
[BeoNews] AdMob isn't working! 

### ISSUE THREAD

**Issue by HoYeongSong** [inspireui/support#165]
Product: Beonews pro
Your Purchased Code: 9f64a72f-f65c-4ecb-89ab-c109e7863821

export default class Index extends Component {
  componentWillUnmount() {
    AdMobInterstitial.removeAllListeners();
  }

  componentDidMount() {
    Config.AdMob.isShowInterstitial && setTimeout(this.showInterstitial, 3000);
  }

  showInterstital() {
    AdMobInterstitial.showAd(error => error && log(error));
  }

  interstitialDidClose() {
    AdMobInterstitial.requestAd(error => error && log(error));
  }

I don't know why admob isn't working! help me please.

**Comment by luyx2412** [comment]
Hi @HoYeongSong Can you provide me your full code file? And please read the document https://github.com/sbugert/react-native-admob/ to use the `AdMobInterstitial `.

Thanks

**Comment by HoYeongSong** [comment]
> Hi @HoYeongSong Can you provide me your full code file? And please read the document https://github.com/sbugert/react-native-admob/ to use the `AdMobInterstitial `.
> 
> Thanks

Sure. I read the document about react-native-admob. This is my AdMob code. I want to add AdMobInterstitial after Apploading. Can you help me?

"use strict";
import React, { Component } from "react";
import { View, TouchableHighlight, Text } from "react-native";
import css from "./style";
import { Constants, Config, log } from "@common";
import { AdMobBanner, AdMobInterstitial } from "expo";
// import { Config } from "rx";

export default class Index extends Component {
  componentWillUnmount() {
    AdMobInterstitial.removeAllListeners();
  }

  // componentDidMount() {
  //   Config.AdMob.isShowInterstitial && setTimeout(this.showInterstitial, 3000);
  // }

  showInterstital() {
    AdMobInterstitial.showAd(error => error && log(error));
  }

  interstitialDidClose() {
    AdMobInterstitial.requestAd(error => error && log(error));
  }

  render() {
    return (
      <View style={css.body}>
        <AdMobBanner
          ref={component => (this._root = component)}
          bannerSize={"fullBanner"}
          testDeviceIDs={[Config.AdMob.deviceID]}
          adUnitID={Config.AdMob.unitID}
        />
      </View>
    );
  }
}

**Comment by luyx2412** [comment]
Hi @HoYeongSong I prepared your code. 
```
"use strict";
import React, { Component } from "react";
import { View, TouchableHighlight, Text } from "react-native";
import css from "./style";
import { Constants, Config, log } from "@common";
import { AdMobBanner, AdMobInterstitial } from "expo";
// import { Config } from "rx";

export default class Index extends Component {
componentDidMount() {
if (Config.AdMob.isShowInterstitial) {
    AdMobInterstitial.setAdUnitID(Config.AdMob.interstitial);
    if (__DEV__) {
      AdMobInterstitial.setTestDevices([AdMobInterstitial.simulatorId]);
     }
     AdMobInterstitial.requestAd().then(() => AdMobInterstitial.showAd());
}
 }

componentWillUnmount() {
AdMobInterstitial.removeAllListeners();
}

interstitialDidClose() {
AdMobInterstitial.requestAd(error => error && log(error));
}

render() {
return (

<AdMobBanner
ref={component => (this._root = component)}
bannerSize={"fullBanner"}
testDeviceIDs={[Config.AdMob.deviceID]}
adUnitID={Config.AdMob.unitID}
/>

);
}
}```

Thanks
