### ISSUE TITLE
[my-product] - Unable to disable blog from config.json for opencart. Kindly help me to update the code to do the needful.

### ISSUE THREAD

**Issue by piyushjainpc** [inspireui/support#1651]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:

2. Screenshots issues:

3. Proof of my purchased:

3. Config files (optional)

**Comment by piyushjainpc** [comment]
Unable to disable blog from config.json for opencart. Kindly help me to update the code to do the needful. #1651

**Comment by minhcasi** [comment]
ould you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads  it's used to verify your proof of purchase? sorry for any inconvenience - Thank you!

**Comment by piyushjainpc** [comment]
Hi Please find the attachment as you required.

**Comment by minhcasi** [comment]
@minhtruong315 - pls help for investigating

**Comment by minhtruong315** [comment]
@piyushjainpc can u send me config.dart file?

**Comment by minhtruong315** [comment]
Hi @piyushjainpc can u send me config.dart file. I'll help u check this issue. thanks

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!

**Comment by piyushjainpc** [comment]
Are you made…? I was sent you all files but you was not replied on the same. Kindly recheck and send me the best solution.
