### ISSUE TITLE
[MStore-MV] - Cannot Publish New Listing

### ISSUE THREAD

**Issue by hrhseyin** [inspireui/support#1652]
**What is my item purchase code : 5b393afa-0cda-46bc-aa6b-6f467aba49ce**

**Product Release** : MStore-MV version 1.3.2 
**Path to buggy component** "..mstore-mv-expo/src/components/SelectImage.Js"
___
**appConfig** :{ Url is not https
                    Use WCFM true } //no any additional configuration
__
**Environments that tested**
Expo Client 2.14.0 Physical Android Device and Simulator Tested
Expo Client 2.14.1 Physical Apple iPhone and Simulator Tested

**Expected Behavior** : Ask for permission, if the status granted connect to ExpoImagePicker bridge

**What happens** : Nothing. Not asking for permission or imagePicker, not allow to navigate next screen.
__

_I have written custom component that asks for permission and picks image to imageUri._

**What happens with my custom SelectImage.Js** : Allows to navigate next screen. Allows to write Product Description. 

**What if I try to publish listing :** After a few "2xx status" (successful) api responses, I get that error "Wrong segment" errors without any "4xx" error codes. Then product wouldn't be published.

**Tested with these user roles** : "Admin, Editor, Vendor"

**JSON API** :: {mstore_user activated
                     posts activated}

**ServerSide environment** : Siteground StartUp plan Wordpress Hosting. (Nginx)
                                            Mysql Database (Apache)

**Did I configured JWT Plugin properly ?** : Yes // i configured .htaccess file, and wp-config.php file

**What was the WordPress Version :** 5.3.1

**Did I check mod headers ?** : Yes

**is all the plugins up the date ?** : Yes

**did I configured permalinks?**: Yes

**what is the default registration role:** Vendor

**Should vendor accounts need to be activated over Admin:** No

**Has anyone can register:** Yes

**Am I using HTTP or HTTPS**: Http, I don't force connections to be HTTPS

**Did I test with HTTPS connection?** : Yes

**How can you support me:**  Helping me edit my app working without these kind of issues

**What is my item purchase code : 5b393afa-0cda-46bc-aa6b-6f467aba49ce**

**Comment by minhcasi** [comment]
@hrhseyin - could share the customize file so that we could help for checking - thanks

**Comment by hrhseyin** [comment]
> @hrhseyin - could share the customize file so that we could help for checking - thanks
```

/** @format */

import React, { PureComponent } from "react";
import { View, Text, TouchableOpacity, Image } from "react-native";
import { Images, Languages } from "@common";
import styles from "./style";
import { ImagePicker, Permissions } from "@expo";

class SelectImage extends PureComponent {
  state = {
    imageUri: "",
  };
  componentDidMount() {
    this.showPicker();
  }
  render() {
    let { style, required } = this.props;
    let { imageUri } = this.state;
    return (
      <View style={[styles.container, style]}>
        <Text style={styles.title}>{Languages.selectTheImage}</Text>
        <TouchableOpacity
          style={[styles.imgWrap, required && styles.required]}
          activeOpacity={0.75}
          onPress={this.showPicker}>
          {imageUri != "" && (
            <Image source={{ uri: imageUri }} style={styles.image} />
          )}
          <Image source={Images.icons.iconCamera} style={styles.icon} />
        </TouchableOpacity>
      </View>
    );
  }

  showPicker = async () => {
    let result = await ImagePicker.launchImageLibraryAsync({
      mediaTypes: ImagePicker.MediaTypeOptions.All,
      allowsEditing: true,
      aspect: [4, 3],
      quality: 1
    });

    console.log(result);

    if (!result.cancelled) {
      this.setState({ imageUri: result.uri });
      this.props.onSelectImage(result.uri);
    }
  };
}

export default SelectImage;

```

**Comment by hrhseyin** [comment]
https://pazaryerimodeli.com/wp-json/wp/v2/media
Status Code
401
Method
POST
Duration (ms)
175392


request headers 
accept
application/json, text/plain, */*
content-disposition
attachment; filename=9C8EBEA0-A528-41C1-A3B9-AEB6DBA41B1E.jpg.png
authorization
Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvcGF6YXJ5ZXJpbW9kZWxpLmNvbSIsImlhdCI6MTU3Njg0MTMxMCwibmJmIjoxNTc2ODQxMzEwLCJleHAiOjE1Nzc0NDYxMTAsImRhdGEiOnsidXNlciI6eyJpZCI6IjEifX19.UyF57JPhdZzUqND5kDzlpPp9YR59cKIlndYYxDOjOOM

**Comment by hrhseyin** [comment]
account created by app
username vendor@vendor.com
password : password

This account shown wordpress dashboard with "no user role"
This account shown WCFM dashboard as store vendor.

I installed wordpress 5.1.4 (supported with JWT plugin)
i installed all plugins needed.
I installed WooCommerce and WCFM

**Comment by hrhseyin** [comment]
No need to customize selectimage file anymore. I successfully made one. 

Now there is only 1 issue. 

Product image is uploading. Thats okay.

Post Method create_post is not working.  It responses **You need to login with a user that has 'edit_posts' capacity.**

Do not ask for my user role. I tried with all of the user roles. 

I checked all user roles capabilities.  

I am sure that user role already has  **'edit_posts'** capacity.

It seems like the problem is with API.

**Check for WCFM**
src/redux/ProductRedux.js
src/services/CustomAPI.js
src/services/WPUserAPI.js

I am using WCFM plugin. Not Dokan.

**Comment by hrhseyin** [comment]
For 5 days nobody support here even I show my billing prove.

I solve these kind of problems. I write my custom Publish page, custom wordpress API controller, custom user role plugin, custom Redux and custom selectImage component. and I am writing custom files to make application working without any issues. Now publishing new product is working with all my custom files and plugins, but not with your files.

**If you don't have product working with WCFM properly. You must write it in code canyon.** There are too much issues. I am almost editing all of the application to make it working properly.

**Comment by muratakgoz** [comment]
Hi ı have same problem. can you help me please?

**Comment by hrhseyin** [comment]
> Hi ı have same problem. can you help me please?

Hello Murat, This product is not working accurately with wordpress backend. We hard coded both  all the react back-end services and our server backend services. What kinda support do you wish from us ?
