### ISSUE TITLE
[Flutterstore] - Can't build release apk or aab and some other issues

### ISSUE THREAD

**Issue by axebelk** [inspireui/support#1653]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
## 1. I can't make release build - which is serious issue.

```
FAILURE: Build failed with an exception.



* What went wrong:

Execution failed for task ':device_apps:verifyReleaseResources'.

> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade

   > Android resource linking failed

     /Users/HP/.gradle/caches/transforms-2/files-2.1/4f0b44f7f428d6290dab406d040ef57b/core-1.0.0/res/values/values.xml:57:5-88:25: AAPT: error: resource android:attr/fontVariationSettings not found.



     /Users/HP/.gradle/caches/transforms-2/files-2.1/4f0b44f7f428d6290dab406d040ef57b/core-1.0.0/res/values/values.xml:57:5-88:25: AAPT: error: resource android:attr/ttcIndex not found.





* Try:

Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.



* Get more help at https://help.gradle.org



BUILD FAILED in 3m 27s
Running Gradle task 'assembleRelease'...                          209.6s (!)
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
✏️  Creating `android/settings_aar.gradle`...                       32ms
✓ `android/settings_aar.gradle` created successfully.
Building plugin apple_sign_in...
Running Gradle task 'assembleAarRelease'...                        22.5s
Starting a Gradle Daemon (subsequent builds will be faster)
WARNING: The option setting 'android.enableR8=true' is experimental and unsupported.
The current default is 'false'
Consider disabling R8 by removing 'android.enableR8=true' from your gradle.properties before publishing your app.


FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'apple_sign_in'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 19s

The plugin apple_sign_in could not be built due to the issue above.
Process finished with exit code 1
```
## 3. In account page smart chat icons click not working properly, it means If I click the icon it clicked About us page.

2. Screenshots issues:
![image](https://user-images.githubusercontent.com/47109263/71247235-55a45900-233e-11ea-87f8-88b29ea57068.png)

3. Proof of my purchased:

3. Config files (optional)

**Comment by phcaraujo** [comment]
I already posted the problem about error generating APK and they did nothing.
Nice support #1625

**Comment by axebelk** [comment]
If nothing happened I am going to ask a refund. and will see some other solution.

**Comment by minhcasi** [comment]
Relate ticket #1625 

Thank you for the issue, note as a high priority for patching this issue

**Comment by minhtruong315** [comment]
Check this comment to fix generate apk
https://github.com/inspireui/support/issues/1595#issuecomment-568151511

**Comment by axebelk** [comment]
If I build aab then it is working. So building issue is not emergency now. So fix the other 2 issues. 
1. Price is not showing 
2. Smartchat button issue

**Comment by minhtruong315** [comment]
@axebelk send me config.dart file

**Comment by axebelk** [comment]
> @axebelk send me config.dart file

I just make a private repo and added you as contributor, As I concerned to send confidential files here. 
Check it out : https://github.com/axebelk/Config-Dart-file-For-fixes

**Comment by axebelk** [comment]
Still you can't fix then kindly refund my money

**Comment by minhtruong315** [comment]
Hi @axebelk 
1. I checked your config.dart file. https://tppr.me/rSyIk . it's showing the price in cart. Please check again. if still same error. Please add my skype: minhtruong315 I'll help check issue price via teamviewer.
2. Can u tell me detail smartchat button issue. https://tppr.me/SU0Y

Thanks

**Comment by axebelk** [comment]
It's not working in my end.

**Comment by axebelk** [comment]
> Hi @axebelk
> 
> 1. I checked your config.dart file. https://tppr.me/rSyIk . it's showing the price in cart. Please check again. if still same error. Please add my skype: minhtruong315 I'll help check issue price via teamviewer.
> 2. Can u tell me detail smartchat button issue. https://tppr.me/SU0Y
> 
> Thanks
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/9a7bb020fe9d3a70a3df8b119f3d92b1abaae796/68747470733a2f2f747070722e73332e616d617a6f6e6177732e636f6d2f75706c6f6164732f34613566666535643061613662646631333462383333663266366535353038382e706e67"><img alt="" height="14" src="/favicon-32x32.png"> tppr.me**[Public - player_2019-12-24 05-35-28](https://tppr.me/rSyIk)**
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/92971df5ebd6a34e14a19b7008cbbccb872ff734/68747470733a2f2f747070722e73332e616d617a6f6e6177732e636f6d2f75706c6f6164732f30346362346363656639613062353962653463323964363233663732633564642e706e67"><img alt="" height="14" src="/favicon-32x32.png"> tppr.me**[Public - player_2019-12-24 05-36-40](https://tppr.me/SU0Y)**

Connect with me on skype : https://join.skype.com/invite/hpEI2U2kY3jd I am waiting to discuss with you
