### ISSUE TITLE
[Fluxstore 1.6.0 woo] - help extra needed

### ISSUE THREAD

**Issue by Coinizy1** [inspireui/support#1656]
1. My issue:
i want to return only one category data for HorizonMenu (animation) i actually want to place animation layout in home page so whenever i put HorizonMenu it returns all the categories and sub categories too can you help so it returns on needed category?

2. Screenshots issues:

3. Proof of my purchased:
provided proof in ticket 1648
3. Config files (optional)
import 'package:flutter/material.dart';
import '../../models/category.dart';
import 'package:provider/provider.dart';
import 'menu_card.dart';

class MyHorizonMenu extends StatefulWidget {

  final int categoryId;
// jazzy

  MyHorizonMenu({this.categoryId});

  // jazzy
  @override
  _StateMyHorizonMenu createState() => _StateMyHorizonMenu();
}

class _StateMyHorizonMenu extends State<MyHorizonMenu>{

  Future<List<Category>> getCategory() async {
    final categories = Provider.of<CategoryModel>(context).categories;
    return categories.where((item) => item.parent == 0).toList();
  }

  List getChildrenOfCategory(List<Category> categories, Category category) {
    var children = categories.where((o) => o.parent == category.id).toList();
    return children;
  }

  @override
  Widget build(BuildContext context) {
    final categories = Provider.of<CategoryModel>(context).categories;

    return FutureBuilder<List<Category>>(
      future: getCategory(),
      builder: (context, snaphost){
        if (snaphost.hasData) {
          return Column(
              children: List.generate(snaphost.data.length, (index){
                return MenuCard(getChildrenOfCategory(categories, snaphost.data[index]), snaphost.data[index]);
              })
          );
        }
        return Container();
      },
    );
  }
}
code help needed i just want to return the selected cateogry items as animation layout

**Comment by minhcasi** [comment]
@minhtruong315 - pls also help for checking the issue from #1657 and  #1659

**Comment by Coinizy1** [comment]
Everything is working now except reviews. i can give review from app but it is not showing or saving the review why

**Comment by Coinizy1** [comment]
![Screenshot_20191223-002632_Skype](https://user-images.githubusercontent.com/31903098/71326322-e768bd80-251a-11ea-842e-cda07e93ff38.jpg)
Not building apk because of apple sign in as it says cannot make settings_aar.bundle file
Cant give reviews it is not showing in the app or the website.

**Comment by minhtruong315** [comment]
Did you approve reviews in admin panel?

**Comment by Coinizy1** [comment]
I dont see any review there at all
It will be shown in comments? Or product page? In wordpress dashboard?

**Comment by minhtruong315** [comment]
in wordpress dashboard. Can u send me admin account to login to wordpress dashboard via email: truong@inspireui.com with subject: https://github.com/inspireui/support/issues/1656

**Comment by Coinizy1** [comment]
sent.
check please

**Comment by minhtruong315** [comment]
I replied. pls check your email

**Comment by minhtruong315** [comment]
supported
