### ISSUE TITLE
[FluxStore MV] - Exception: You need to Login to Checkout

### ISSUE THREAD

**Issue by antixirus** [inspireui/support#1658]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
I can't regis new member from the App to Checkout my product
2. Screenshots issues:
![gambar](https://user-images.githubusercontent.com/57300649/71302931-00bb1e00-23e4-11ea-9f21-f18c7665fcba.png)

3. Proof of my purchased:
![gambar](https://user-images.githubusercontent.com/57300649/71302937-116b9400-23e4-11ea-879f-73e2eb055e21.png)

3. Config files (optional)

const kAdvanceConfig = {
  "DefaultLanguage": "en",
  "DefaultCurrency": {
    "symbol": "Rp ",
    "decimalDigits": 2,
    "symbolBeforeTheNumber": true,
    "currency": "IDR"
  },
  "IsRequiredLogin": false,
  "GuestCheckout": true,
  "EnableShipping": true,
  "EnableAddress": true,
  "EnableReview": true,
  "GridCount": 3,
  "DetailedBlogLayout": kBlogLayout.halfSizeImageType,
  "EnablePointReward": false,
  "DefaultPhoneISOCode": "+84",
  "DefaultCountryISOCode": "VN",
  "EnableRating": true,
  "EnableSmartChat": true,
  "ZoneIdShipping": [1, 0],
  "hideOutOfStock": true,
  'allowSearchingAddress': true,
  "isCaching": false,
  "OnBoardOnlyShowFirstTime": true,
  "EnableConfigurableProduct": false, //for magento
  "EnableAttributesConfigurableProduct": ["color", "size"], //for magento
  "EnableAttributesLabelConfigurableProduct": ["color", "size"] //for magento
};

/// The Google API Key to support Pick up the Address automatically
/// We recommend to generate both ios and android to restrict by bundle app id
/// The download package is remove these keys, please use your own key
const kGoogleAPIKey = {
  "android": "your-google-api-key",
  "ios": "your-google-api-key"
};

/// use to config the product image height for the product detail
/// height=(percent * width-screen)
/// isHero: support hero animate
const kProductDetail = {
  "height": 0.5,
  "marginTop": 0,
  "isHero": false,
  "safeArea": false,
  "showVideo": true,
  "showThumbnailAtLeast": 3,
  "layout": kProductLayout.simpleType

**Comment by antixirus** [comment]
Please reply..

**Comment by vumanhsn97** [comment]
@antixirus Can you share more detail? (Video record). I cant find your issue

**Comment by antixirus** [comment]
https://drive.google.com/open?id=1gruNpqlz3HzDsHwyDh5RpXzUd-gqz6LP

Video sir, please help me..

**Comment by parveenkrraina** [comment]
I am also facing the same issue after the checkout only buffering on Emulator, but when I tried running it on physical device getting the error:
Webpage not available

The webpage at https://mysite.com/mstore-checkout/?order=hjadhjd76gdshhdsaghHJHGDFYhjsdfh686q84qr
could not loaded because: net: ERR_TOO_MANY_REDIRECTS

**Comment by antixirus** [comment]
@parveenkrraina My checkout webpage is available sir.. i use demo wordpress from InspireUI

**Comment by vumanhsn97** [comment]
@antixirus 
- add line code in lib/models/user.dart https://tppr.me/H0ECs
- update mstore api plugin in your website to new version 1.5.6

**Comment by antixirus** [comment]
@vumanhsn97 i try first sir.. thankyou

**Comment by antixirus** [comment]
@vumanhsn97 nothing happen sir, error again, Can you help me by Team Viewer?

**Comment by antixirus** [comment]
![gambar](https://user-images.githubusercontent.com/57300649/71371691-945b3d00-25e4-11ea-8c69-7b881801ffb5.png)

**Comment by antixirus** [comment]
Invalid Argument @vumanhsn97

**Comment by vumanhsn97** [comment]
@antixirus 
Try to change file in lib/models/user.dart to 
[user.dart.zip](https://github.com/inspireui/support/files/3996984/user.dart.zip)

**Comment by antixirus** [comment]
> 
> 
> @antixirus
> Try to change file in lib/models/user.dart to
> [user.dart.zip](https://github.com/inspireui/support/files/3996984/user.dart.zip)

Same sir, Invalid Arguments, please help me, i need you help sir..

**Comment by vumanhsn97** [comment]
@antixirus you can send your teamview id to vumanhsn97@gmail.com(Skype)

**Comment by antixirus** [comment]
Fixed! Close

**Comment by Maczidane** [comment]
Please you said this issue is fixed and closed but you didnt explain how you fix it for that user. We have the same problem too

**Comment by vumanhsn97** [comment]
@Maczidane This issue fixed on next version

**Comment by Maczidane** [comment]
which version please?

**Comment by Maczidane** [comment]
This issue is slowing me down. please help

**Comment by Maczidane** [comment]
> @Maczidane This issue fixed on next version

Please help fast
