### ISSUE TITLE
FluxStore 1.6.0  [Magento 2] Various Issues Why my ticket closed #1630 ? 

### ISSUE THREAD

**Issue by Abhiv66** [inspireui/support#1660]
First of all i would like to tell you that,We are not looking for any development or functionality increasement in this app,We just want the app runnable / workable mode with showcased features and you do not have rights to close any tickets without all problem being solved.

1. My issues:
1.Custom options not showing in the app.
2.Category images not showing in the app.
3.After payment successful comebacks to the payment screen and showing the error mentioned in screen shot

2. Screenshots issues:
![Screenshot_2019-12-21-11-26-58-033_com inspireui fluxstore](https://user-images.githubusercontent.com/58973413/71303905-24329880-23e5-11ea-9e4d-65dd585c717b.jpg)
![Screenshot_2019-12-21-11-24-10-214_com inspireui fluxstore](https://user-images.githubusercontent.com/58973413/71303909-28f74c80-23e5-11ea-9f5b-c1ae16ef72e6.jpg)
![Screenshot_2019-12-21-11-25-43-842_com inspireui fluxstore](https://user-images.githubusercontent.com/58973413/71303912-30b6f100-23e5-11ea-9dd3-3b755c08786b.jpg)

3. Proof of my purchased:
#1630 

Revert solutions right now to my issues really all things getting hampered

**Comment by minhcasi** [comment]
#1630
