### ISSUE TITLE
Mstore Pro magento 

### ISSUE THREAD

**Issue by a7medeeuae** [inspireui/support#1661]
Couldn't start project on Android: Error running adb: No Android device found. Please connect a device and follow the instructions here to enable USB debugging:
https://developer.android.com/studio/run/device.html#developer-device-options. If you are using Genymotion go to Settings -> ADB, select "Use custom Android SDK tools", and point it at your Android SDK directory.

**Comment by minhcasi** [comment]
Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads  it's used to verify your proof of purchase? sorry for any inconvenience - Thank you!

**Comment by a7medeeuae** [comment]
![69574434-857f6b80-0fe1-11ea-97f3-da8507226d41](https://user-images.githubusercontent.com/24714994/71417413-a38ec900-267e-11ea-8540-7fe698720651.png)

**Comment by a7medeeuae** [comment]
hello

**Comment by a7medeeuae** [comment]
![1](https://user-images.githubusercontent.com/24714994/71476732-0065bd00-2800-11ea-9d08-f81b9aa419ef.jpg)
![2](https://user-images.githubusercontent.com/24714994/71476733-0065bd00-2800-11ea-81aa-4aeb2dc08404.jpg)

**Comment by a7medeeuae** [comment]
i have other problem now 

no data showing in the apk

**Comment by a7medeeuae** [comment]
and its no products showing

**Comment by a7medeeuae** [comment]
helllo ???????

**Comment by minhcasi** [comment]
@minhtruong315 - please help for checking

**Comment by minhtruong315** [comment]
@a7medeeuae add my skype: minhtruong315
I'll help u check it via teamviewer

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
