### ISSUE TITLE
[Fluxstore] - How to config category "sideMenu"

### ISSUE THREAD

**Issue by MrrHak** [inspireui/support#1662]
1. My issue: I want to config category "sideMenu" to show only list of parent categories. currently it's show all categories and I don't want like this.
![Screenshot_1576928875](https://user-images.githubusercontent.com/42771980/71307642-80b4a880-2423-11ea-9645-822c1c7b4bc6.png)

proof:
![Screenshot (454)](https://user-images.githubusercontent.com/42771980/71307657-a6da4880-2423-11ea-8738-16051cbd64f0.png)

**Comment by minhcasi** [comment]
@vumanhsn97 - pls help for suggestion the solution - we may set the parent category as default on left sidebar instead of showing all category

**Comment by vumanhsn97** [comment]
@MrrHak Change your file in lib/screens/categories/side_menu.dart to 
[side_menu.dart.zip](https://github.com/inspireui/support/files/3993632/side_menu.dart.zip)

**Comment by MrrHak** [comment]
Yes Thanks you

**Comment by MrrHak** [comment]
Category list work well but not show product in the category
![Screenshot_1577084817](https://user-images.githubusercontent.com/42771980/71341827-86c69880-258d-11ea-8087-426496a70380.png)

**Comment by vumanhsn97** [comment]
@MrrHak 
Can you share your website url?

**Comment by MrrHak** [comment]
Here is my site: https://tenhh.com

**Comment by vumanhsn97** [comment]
@MrrHak Send your config.dart, config.json and account login to vumanhsn97@gmail.com. I will check for you

**Comment by rioadetya** [comment]
i have the same problem. I hope it will be solved soon

**Comment by vumanhsn97** [comment]
@MrrHak Change this file in lib/screens/categories/side_menu.dart to 
[side_menu.dart.zip](https://github.com/inspireui/support/files/4012352/side_menu.dart.zip)
