### ISSUE TITLE
[Mstore pro] - i want to add forget password when user forget his password 

### ISSUE THREAD

**Issue by hami44** [inspireui/support#1663]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
i want to add forget password when user forget his password 

2. Screenshots issues:
![image](https://user-images.githubusercontent.com/58168661/71308769-8c976f00-2411-11ea-91c6-06bcaf536fbc.png)

3. Proof of my purchased:
![image](https://user-images.githubusercontent.com/58168661/71308751-40e4c580-2411-11ea-9f63-4dcad33d5cb4.png)

3. Config files (optional)

**Comment by hami44** [comment]
@minhcasi

**Comment by minhcasi** [comment]
@hami44 - you can try the simple method by open as Webview and load the URL http://your-domain/wp-login.php?action=lostpassword

Example: http://demo.mstore.io/wp-login.php?action=lostpassword

**Comment by hami44** [comment]
it is not professional method to open webview, it is useful and no reason to not exist in this version , so could you please add it in next update or that is not in your plan  @minhcasi @vumanhsn97 @luyx2412
