### ISSUE TITLE
[fluexstore] -  opencard

### ISSUE THREAD

**Issue by mo7amademad** [inspireui/support#1664]
how to fix this problem !!
https://drive.google.com/file/d/1ObD9aqkLpttT9DjYVK2EyH5OPtUleR7w/view?usp=sharing

https://drive.google.com/file/d/12ivzL225IFuSJf4FmtS-afaws5N65uk9/view?usp=sharing

help me pleas and how to change first splash screen !!!!

**Comment by minhcasi** [comment]
Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads  it's used to verify your proof of purchase? sorry for any inconvenience - Thank you!

**Comment by mo7amademad** [comment]
https://drive.google.com/file/d/1UwUXQG4YdPZvwe3g1R7qzzm-Nipn_afo/view?usp=sharing

**Comment by mo7amademad** [comment]
please help me !!

**Comment by minhcasi** [comment]
@mo7amademad - i'm sorry for the missing your ticket, could you help to share your config file here please

@minhtruong315 - pls help for checking

**Comment by mo7amademad** [comment]
config.json ?

**Comment by minhcasi** [comment]
it's common/config.json and config.dart- thank you!

**Comment by mo7amademad** [comment]
im already remove all file and reinstall, 
and creat new keystore
But I faced a new problem in build apk
https://drive.google.com/file/d/1hPQJbGj2_eroIBcuBokWryDu582GcFEv/view?usp=sharing

**Comment by minhtruong315** [comment]
@mo7amademad add my skype: minhtruong315
i'll help u check via teamviewer

**Comment by mo7amademad** [comment]
okay

**Comment by minhtruong315** [comment]
@mo7amademad pls update the latest source code on codeanyon to fix this
