### ISSUE TITLE
[Mstore Pro] - Error: Command failed: ./gradlew build -x lint

### ISSUE THREAD

**Issue by alexisttt** [inspireui/support#1665]
1. My issue:
Hi. I was trying to install the app to my phone. I have install the requirements according to the guide of React Native and Mstore Pro. After pre requirements i have opened the terminal in the folder. And typed yarn install. It worked as it should after it i have typed react-native run-android --deviceId xxxxxxxxxx. And it started to install the app. But it failed with the error bellow. I have already tried to add ( android {    lintOptions {         abortOnError false    }} ) in the build.gradle  as suggested solution on stackoverflow, but nothing changed.  Waiting for your help. Thanks...

Os: Ubuntu 16.04 Gnome
node: v12.14.0

 Task :app:bundleReleaseJsAndAssets FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:bundleReleaseJsAndAssets'.
> Process 'command 'node'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1m 26s
355 actionable tasks: 2 executed, 353 up-to-date
error Failed to build the app. Run CLI with --verbose flag for more details.
Error: Command failed: ./gradlew build -x lint
    at makeError (/home/alex/React Native Projects/mstore-pro/node_modules/execa/index.js:174:9)
    at Function.module.exports.sync (/home/alex/React Native Projects/mstore-pro/node_modules/execa/index.js:338:15)
    at buildApk (/home/alex/React Native Projects/mstore-pro/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:190:22)
    at runOnSpecificDevice (/home/alex/React Native Projects/mstore-pro/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:171:7)
    at buildAndRun (/home/alex/React Native Projects/mstore-pro/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:156:12)
    at /home/alex/React Native Projects/mstore-pro/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:125:12
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Command.handleAction (/home/alex/React Native Projects/mstore-pro/node_modules/@react-native-community/cli/build/cliEntry.js:160:7)

2. Screenshots issues:
![Screenshot from 2019-12-21 22-48-55](https://user-images.githubusercontent.com/45356673/71313017-1e1fd480-2444-11ea-8993-2c8e719cc300.png)

3. Proof of my purchased:
![Screenshot from 2019-12-21 22-50-48](https://user-images.githubusercontent.com/45356673/71313053-67702400-2444-11ea-8138-8162fa0d8a5b.png)

3. Config files (optional)
I haven't changed any file.

**Comment by minhcasi** [comment]
@concuacon - pls help for suggesting solution

**Comment by concuacon** [comment]
@alexisttt I think you don't add android { lintOptions { abortOnError false }}, you can follow below step:
- Delete node_modules/
- yarn install
- cd android
- ./gradlew clean
- cd ../
- Connect real device android to your desktop run: react-native run-android

**Comment by alexisttt** [comment]
Hello the steps above fixed the problem. Thanks for your help.

**Comment by alexisttt** [comment]
Please do not close the topic without getting the confirmation, it's just rude. I have followed the steps you suggested and they did not help. I have been able to solve it with reinstalling the node. After reinstalling it worked.

**Comment by minhcasi** [comment]
you can reopen the ticket if it does not fix - the reason i closed ticket as saw your confirm email - https://tppr.me/VEFQZ - thanks

**Comment by alexisttt** [comment]
Yes first i thought it fixed but i gave other errors. So i deleted it. Sorry for misunderstanding.
