### ISSUE TITLE
[Mstore Pro] - News Screen is blank

### ISSUE THREAD

**Issue by JeffZhu1122** [inspireui/support#1667]
### **SOLVED!!! But another issue**
1. My issue:
`Looking for JS files in
   /Users/jeff/Desktop/APP/mstore-3.9.6/mstore-pro 

Loading dependency graph, done.
error: bundling failed: Error: Unable to resolve module `@react-native-community/viewpager` from `/Users/jeff/Desktop/APP/mstore-3.9.6/mstore-pro/node_modules/react-native-scrollable-tab-view/index.js`: Module `@react-native-community/viewpager` does not exist in the Haste module map

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.
  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.
    at ModuleResolver.resolveDependency (/Users/jeff/Desktop/APP/mstore-3.9.6/mstore-pro/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:183:15)
    at ResolutionRequest.resolveDependency (/Users/jeff/Desktop/APP/mstore-3.9.6/mstore-pro/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (/Users/jeff/Desktop/APP/mstore-3.9.6/mstore-pro/node_modules/metro/src/node-haste/DependencyGraph.js:283:16)
    at Object.resolve (/Users/jeff/Desktop/APP/mstore-3.9.6/mstore-pro/node_modules/metro/src/lib/transformHelpers.js:264:42)
    at dependencies.map.result (/Users/jeff/Desktop/APP/mstore-3.9.6/mstore-pro/node_modules/metro/src/DeltaBundler/traverseDependencies.js:399:31)
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/jeff/Desktop/APP/mstore-3.9.6/mstore-pro/node_modules/metro/src/DeltaBundler/traverseDependencies.js:396:18)
    at /Users/jeff/Desktop/APP/mstore-3.9.6/mstore-pro/node_modules/metro/src/DeltaBundler/traverseDependencies.js:269:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/jeff/Desktop/APP/mstore-3.9.6/mstore-pro/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)
 BUNDLE  [ios, dev] ./index.js ▓▓▓▓▓▓▓▓▓░░░░░░░ 58.5% (1328/1736), failed.`
2. Screenshots issues:
![Screenshots](https://i.ibb.co/pQJkVDN/2019-12-2219-54-18.png)
3. Proof of my purchased:
![purchased](https://i.ibb.co/8DpQKyQ/2019-12-2219-56-33.png)

**Comment by JeffZhu1122** [comment]
I have solved this by 

yarn add @react-native-community/viewpager
react-native link @react-native-community/viewpager

But there is another issue:
The NewsScreen is blank as shown
![Screenshots](https://i.postimg.cc/RhYq0F4F/2019-12-2221-43-40.png)

**Comment by minhcasi** [comment]
Noted with investigating - thank you!

**Comment by JeffZhu1122** [comment]
Is there any progress related to the blank NewsScreen

**Comment by minhcasi** [comment]
confirmed this is fix on latest 3.9.7 - we will update this new version in this week - thanks

**Comment by JeffZhu1122** [comment]
The NewsScreen is still blank  after using version 3.9.7.
Is there any woocommerce version required since I found the following error from the debug tool:

<div class="woocommerce"><div class="woocommerce-notices-wrapper"><br />
<b>Fatal error</b>: Uncaught Error: Call to a member function get() on null in /www/wwwroot/flower.immartonline.com/wp-content/plugins/woocommerce/includes/wc-notice-functions.php:131
Stack trace:
#0 /www/wwwroot/flower.immartonline.com/wp-content/plugins/woocommerce/includes/wc-template-functions.php(3632): wc_print_notices()
#1 /www/wwwroot/flower.immartonline.com/wp-includes/class-wp-hook.php(288): woocommerce_output_all_notices('')
#2 /www/wwwroot/flower.immartonline.com/wp-includes/class-wp-hook.php(312): WP_Hook-&gt;apply_filters('', Array)
#3 /www/wwwroot/flower.immartonline.com/wp-includes/plugin.php(478): WP_Hook-&gt;do_action(Array)
#4 /www/wwwroot/flower.immartonline.com/wp-content/themes/woodmart/woocommerce/myaccount/form-login.php(45): do_action('woocommerce_bef...')
#5 /www/wwwroot/flower.immartonline.com/wp-content/plugins/woocommerce/includes/wc-core-functions.php(249): include('/www/wwwroot/fl...')
#6 /www/wwwroot/flower.immartonline.com/wp-content/plugins/woo-wallet/includes/class-woo-wallet-frontend.php(693): wc_ge in <b>/www/wwwroot/flower.immartonline.com/wp-content/plugins/woocommerce/includes/wc-notice-functions.php</b> on line <b>131</b><br />

I m now using woocommerce 3.8.1
