### ISSUE TITLE
[Fluxstore Pro] -  Auto fill address from map issue

### ISSUE THREAD

**Issue by Alnaggar94** [inspireui/support#1668]
1. My issue:
The Auto fill address from the map doesn't work probably, It shows me wrong location (different country) with unnamed location and when I press "Tap to select this location" nothing happens.

2. Screenshots issues:
screenshot - https://imgur.com/a/FDTy0a9

3. Proof of my purchased:
https://imgur.com/a/9TsYcIf

**Comment by minhcasi** [comment]
@Alnaggar94 - could you help to check if you have replaced your google map API key - https://docs.inspireui.com/fluxstore/firebase/

Also, try to test on the real device, on the ios simulator - it may not work well
