### ISSUE TITLE
[ListApp] all website crush after updating Listapp manager to the new version 1.4.1

### ISSUE THREAD

**Issue by paniri** [inspireui/support#167]
My all website crush after updating to the newest version 1.4.1

Warning: require_once(/homepages/14/d750391768/htdocs/clickandbuilds/attendy/wp-content/plugins/listapp-mobile-manager//controllers/rename-media.php): failed to open stream: No such file or directory in /homepages/14/d750391768/htdocs/clickandbuilds/attendy/wp-content/plugins/listapp-mobile-manager/listapp-manager.php on line 103

Fatal error: require_once(): Failed opening required '/homepages/14/d750391768/htdocs/clickandbuilds/attendy/wp-content/plugins/listapp-mobile-manager//controllers/rename-media.php' (include_path='.:/usr/lib/php7.0') in /homepages/14/d750391768/htdocs/clickandbuilds/attendy/wp-content/plugins/listapp-mobile-manager/listapp-manager.php on line 103

**Comment by reconshield** [comment]
yes..we also facing same issue.just disable new update..use the old one.. but still cant see listing thumbnails

**Comment by thangvo9x** [comment]
Hi. You can update new version plugin. We're so sorry we've missed a file when update.
Thanks
