### ISSUE TITLE
Fluxstore: checkout error

### ISSUE THREAD

**Issue by parveenkrraina** [inspireui/support#1670]
I am facing the issue during the checkout, after the checkout only buffering with white screen on Emulator, but when I tried running it on physical device getting the error:
Webpage not available

The webpage at https://mysite.com/mstore-checkout/?order=hjadhjd76gdshhdsaghHJHGDFYhjsdfh686q84qr
could not loaded because: net: ERR_TOO_MANY_REDIRECTS

**mstore-checkout page is available on my woocomerce with template as Msotre without parent**
Request you to fix it ASAP.

![Snag_9b7b5c2](https://user-images.githubusercontent.com/41342012/71345898-92658f80-258c-11ea-872e-af98c15c1076.png)

**Comment by minhcasi** [comment]
@parveenkrraina - could you share the screenshot that contains your username please, also share your config site so that we could help for checking - thank you!

**Comment by parveenkrraina** [comment]
please share your email id

**Comment by parveenkrraina** [comment]
![Snag_df8ea3f](https://user-images.githubusercontent.com/41342012/71393482-c3989b00-2632-11ea-99d4-bf95c568b308.png)

**Comment by parveenkrraina** [comment]
@minhcasi I have not received any update from your side till now. config.json and config.dart attached.
Please fix the issue ASAP

[config.zip](https://github.com/inspireui/support/files/4001925/config.zip)

**Comment by minhcasi** [comment]
@minhtruong315  - please help for checking - thank you!

**Comment by parveenkrraina** [comment]
@minhtruong315 I waiting for you at the earliest. Thanks.

**Comment by parveenkrraina** [comment]
@minhcasi / @minhtruong315  your app has many small bugs

- After making changes in the config file to hide the out of stock products, it still shows the products

![Snag_d393c1e](https://user-images.githubusercontent.com/41342012/71486713-ad125f80-283d-11ea-9172-1004ebf20960.png)

- In Cart the product price is always 0
![Snag_d3a507c](https://user-images.githubusercontent.com/41342012/71486736-d6cb8680-283d-11ea-9737-4cc7c476322f.png)

- In home screen offer price and sale price is same, but when you open the product it shows the correct values
![Snag_d3b3fec](https://user-images.githubusercontent.com/41342012/71486767-fbbff980-283d-11ea-8f1c-d59544b8bc2d.png)
![Snag_d3b6a29](https://user-images.githubusercontent.com/41342012/71486772-01b5da80-283e-11ea-874e-51181ca95ed9.png)

- How to hardcode COD charges in the app

- Payment webview is not opening in the app always shared the relevant details and waiting for your response. I am getting out of time. Please fix these issues ASAP.
Looking for a quick resolution of these issues.

**Comment by minhtruong315** [comment]
@parveenkrraina Pls add my skype: minhtruong315
I will help u check it via teamviewer

**Comment by parveenkrraina** [comment]
Please connect over skype, waiting for you

**Comment by minhtruong315** [comment]
@parveenkrraina please replace these files to fix price and out of stock. 
- common/tools.dart
- services/woo_commerce.dart
- widgets/product/product_cart_view.dart

[product_card_view.dart.zip](https://github.com/inspireui/support/files/4006618/product_card_view.dart.zip)
[woo_commerce.dart.zip](https://github.com/inspireui/support/files/4006616/woo_commerce.dart.zip)
[tools.dart.zip](https://github.com/inspireui/support/files/4006615/tools.dart.zip)

About payment, it's working well now. please check again

**Comment by parveenkrraina** [comment]
@minhtruong315 getting multiple errors:
Compiler message:
lib/common/tools.dart:17:24: Error: Unexpected token ';'.
const bool kIsWeb=true;;
                       ^
lib/services/woo_commerce.dart:282:63: Error: No named parameter with the name 'version'.
          await wcApi.getAsync("products/$productId/reviews", version: 2);
                                                              ^^^^^^^
lib/services/woo_commerce.dart:301:66: Error: No named parameter with the name 'version'.
      await wcApi.postAsync("products/$productId/reviews", data, version: 2);
                                                                 ^^^^^^^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.
                                                                        
FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 780

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 53s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                        54.9s
Gradle task assembleDebug failed with exit code 1

**Comment by parveenkrraina** [comment]
@minhcasi @minhtruong315 @luyx2412 @trunghieuvn  My problem is not resolved till now..

**Comment by minhcasi** [comment]
@parveenkrraina - sorry for the issue we are going to update new release today for this fixing - thank you!

**Comment by parveenkrraina** [comment]
that's great to know.

**Comment by parveenkrraina** [comment]
Not received the update e

**Comment by parveenkrraina** [comment]
@minhcasi @minhtruong315 @luyx2412 @trunghieuvn after upgrading the app getting the error in product description:
![product_description](https://user-images.githubusercontent.com/41342012/71644741-76cc5880-2cf3-11ea-8be7-1291e6b7843d.jpg)

Checkout page for other payment gateways like payumoney still showing the same error no update on this:
![checkout](https://user-images.githubusercontent.com/41342012/71644744-89df2880-2cf3-11ea-963c-0ae1f89e1c32.jpg)

rest of the issues regarding the pricing are all fixed.

Its taking a lot of time to fix the checkout issue. Please help to get it fixed.

**Comment by minhcasi** [comment]
@minhtruong315 - pls help for checking

**Comment by minhtruong315** [comment]
@parveenkrraina send me admin account again. I can't login to admin panel by old account.

**Comment by parveenkrraina** [comment]
try now with same details

**Comment by minhtruong315** [comment]
@minhcasi help me check payment gateway issue. Thanks

**Comment by parveenkrraina** [comment]
Hi @minhcasi thanks. Please get it resolved ASAP

**Comment by minhcasi** [comment]
@parveenkrraina - it is possible to access the FTP to edit the file? We need to debug from the Wordpress mstore-api as it seems the problem caused by server setting - pls send to support@inspireui.com

Please note that this is a quite complex issue that takes us time to investigate and debug, thanks for your patient

**Comment by parveenkrraina** [comment]
shared

**Comment by parveenkrraina** [comment]
I hope you are able to login to the FTP account.

**Comment by parveenkrraina** [comment]
any update?

**Comment by trunghieuvn** [comment]
@parveenkrraina  hello, 
a issue 
![image](https://user-images.githubusercontent.com/19247680/72088384-a1925e80-333c-11ea-81f6-5b0047441f6e.png)
you try add in AndroidManifest.xml 
please check permission
```
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
````
and add 
```
        android:usesCleartextTraffic="true"
```

same as here
![image](https://user-images.githubusercontent.com/19247680/72088453-c8509500-333c-11ea-90cc-416975ab892a.png)

**Comment by parveenkrraina** [comment]
@trunghieuvn after adding the suggested code, still getting the same error

**Comment by parveenkrraina** [comment]
will anybody update me on this? This problem is having the highest priority.

**Comment by minhcasi** [comment]
![image_2020_01_16T04_47_48_251Z](https://user-images.githubusercontent.com/1459805/72496043-fbbe8280-385a-11ea-9227-6985da816f0a.png)

@parveenkrraina - this is kind of integration server issue that cause some issues during the check out, actually this take us a lot of time for reproduce and checking, we're very sad to get your bad rating - kindly update the rating so that could continues with the checking, otherwise we may give up on this issue - thank you!

**Comment by parveenkrraina** [comment]
I will update the review, but get it resolved ASAP.

**Comment by minhcasi** [comment]
Thank you for your update, could you help to update the write access to FTP so that we could debug the plugin issue, it will not impact to the app current function  - https://tppr.me/wCeyo

**Comment by minhcasi** [comment]
We could not edit this file from wordpress site neither, pls resolve it ASAP so that we could continuous checking - thanks

**Comment by parveenkrraina** [comment]
its editable, its working fine. The account that I shared with you is the admin account of WordPress. Please check.

**Comment by minhcasi** [comment]
hi, it's not worked, example when you try to add this line for debugging - https://tppr.me/9EfSd - the wp notice save successful but when refreshing the page - it reset to previous file

**Comment by parveenkrraina** [comment]
Its fixed now
Reason: It was not saving because MStore API Plugin as active, when I deactivated it and added the required code it works. Than re-activated. Hope it will work for you as well.

**Comment by minhcasi** [comment]
@parveenkrraina - we confirm this is a bug when integrating with your site, there is the limited from the site queryString that some params input is cut before sending to the server that causes the page is empty, the team is working hard to resolve this issues by upgrading new payment and also fix this security, pls bear with us in 1-2 days to update this fixing.

We will upload into the gitlab after it is fixed, thank you for your patient.

**Comment by parveenkrraina** [comment]
@minhcasi  thanks for the update.

**Comment by parveenkrraina** [comment]
hi @minhcasi  any update?

**Comment by minhcasi** [comment]
@parveenkrraina we are working hard on this issue to experience, we will update as soon as we can - thank you for your patient so far

**Comment by parveenkrraina** [comment]
@minhcasi is my issue resolved in the 1.6.3 update released yesterday

**Comment by inspireui-support** [comment]
sorry not yet - we are still working on this issue - thank you!

**Comment by parveenkrraina** [comment]
@inspireui-support  guys its a very long delay, Please update

**Comment by minhtruong315** [comment]
https://tppr.me/yexac
Finally, we have fixed the issues - it will be updated new release today

**Comment by inspireui-support** [comment]
@parveenkrraina - pls replace this file https://www.dropbox.com/s/vc40nffi370aol6/payment_webview.dart?dl=0 to `screens/checkout/`

And also update the mstore-api to latest version to fix the issue - thanks

**Comment by parveenkrraina** [comment]
@inspireui-support - can you please send me the complete project on which you worked to resolve my issue.
