### ISSUE TITLE
can't build signed APK

### ISSUE THREAD

**Issue by VM8198** [inspireui/support#1671]
I am not able to build the signed APK after doing some changes

It throws this error
`FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':device_apps:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     C:\Users\Rao\.gradle\caches\transforms-2\files-2.1\4f0b44f7f428d6290dab406d040ef57b\core-1.0.0\res\values\values.xml:57:5-88:25: AAPT: error: resource android:attr/fontVariationSettings not found.

     C:\Users\Rao\.gradle\caches\transforms-2\files-2.1\4f0b44f7f428d6290dab406d040ef57b\core-1.0.0\res\values\values.xml:57:5-88:25: AAPT: error: resource android:attr/ttcIndex not found.`

I am having compileSdkVersion 28

Please help...

**Comment by VM8198** [comment]
I am able to solve the issue by changing the pubspec.yaml file as below

`name: fstore
description: Mobile commerce app by Flutter

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.6.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  logs:
    git: https://github.com/pq/logs
  flutter:
    sdk: flutter
  http: 0.12.0+2
  html_unescape: 1.0.1+3
  provider: 3.2.0
  after_layout: 1.0.7+2
  font_awesome_flutter: 8.5.0
  path: 1.6.4
  vector_math: 2.0.8
  carousel_pro: 1.0.0
  flutter_widget_from_html_core: 0.2.4+4
  configurable_expansion_tile: 1.0.0
  timeago: 2.0.22
  share: 0.6.3+5
  validate: 1.7.0
  country_pickers: 1.1.0
  shared_preferences: ^0.5.6
  firebase_messaging: 6.0.9
  firebase_analytics: 5.0.9
  transparent_image: 1.0.0
  pull_to_refresh: 1.5.7
  localstorage: 3.0.1+4
  notification_permissions: 0.4.3
  flare_splash_screen: 3.0.0
  rate_my_app: 0.4.0
  flutter_range_slider: 1.4.0
  page_indicator: 0.3.0
  extended_image: 0.6.8
  flutter_screenutil: 0.7.0
  fluttertoast: 3.1.3
  intro_slider: 2.2.8
  url_launcher: 5.4.1
  firebase_core: 0.4.3+1
  firebase_auth: 0.15.3
  firestore_ui: 1.7.2
  flutter_webview_plugin: 0.3.10
  connectivity: 0.4.6+1
  random_string: 2.0.0
  google_maps_flutter: 0.5.21+15
  place_picker: 0.9.11
  cached_network_image: 2.0.0-rc.1
  image_picker: 0.6.2+3
  fab_circular_menu: 0.1.3
  uuid: 2.0.4
  uni_links: 0.2.0
  flutter_staggered_grid_view: 0.3.0
  device_apps: 1.0.9
  auto_size_text: 2.1.0
  koukicons: 2.0.2
  lazy_load_scrollview: 1.0.1
  flutter_swiper: 1.1.6
  flutter_widgets: 0.1.7+1
  video_player: 0.10.5
  flutter_spinkit: 4.1.1+1
  percent_indicator: 2.1.1+1
  animated_text_kit: 1.3.1
  wave: 0.0.8
  http_auth: 0.2.7
  firebase_admob: ^0.9.0+10
  facebook_audience_network: ^0.4.0
  international_phone_input: 1.0.2
  pin_code_fields: 2.3.0+3
  cupertino_icons: 0.1.3
  flutter_facebook_login: 3.0.0
  webview_flutter: 0.3.18+1
  rubber: 0.4.0
  flutter_localizations:
    sdk: flutter
  carousel_slider: 1.3.1
  custom_splash: 0.0.2
  apple_sign_in: 0.1.0
  google_sign_in: 4.1.1
  google_fonts: ^0.2.0
  onesignal_flutter: ^2.3.1
  flutter_statusbarcolor: ^0.2.3
  app_settings: 3.0.0+1
  shimmer: ^1.0.1

dev_dependencies:
  flutter_launcher_icons: 0.7.4
  flutter_test:
    sdk: flutter

dependency_overrides:
  html: ^0.13.3

# Run this script to generate the app icon: flutter pub pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - lib/common/
    - assets/icons/categories/
    - assets/icons/tabs/
    - assets/icons/profile/
    - assets/icons/payment/
    - assets/icons/
    - assets/images/
    - assets/images/country/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
`

**Comment by smohapatra200** [comment]
what changes did you particularly do in the pubspec.yaml to solve the issue. I am having the same issue.
