### ISSUE TITLE
Opencart Checkout Issue Fluxstore

### ISSUE THREAD

**Issue by kurkuteabhi** [inspireui/support#1673]
Continue to my previous issue #[1584 ](https://github.com/inspireui/support/issues/1584) i have Updated to 1.6, but my issue not resolved. Demo Opencart work fine. but our fresh Opencart installation is not working properly. there are not other or theme installed except **mstore.ocmod.zip**. 

**what working** 
1. Registration & Login
2. Product load at Home Page only
3. Search function

**Not Working**
1.  Category not loading
2. Checkout 
3. Flare animation
4. Request link to privacy policy while new user registration Page with checkbox

![home_screen](https://user-images.githubusercontent.com/43174699/71368858-13de1180-25cf-11ea-802f-35f1a7b23ebd.jpg)
![category_lotloading](https://user-images.githubusercontent.com/43174699/71368862-1476a800-25cf-11ea-85c1-6edc7c5ef487.jpg)
![checkout_eeror](https://user-images.githubusercontent.com/43174699/71368863-15a7d500-25cf-11ea-8d25-78dc13fd8fe4.jpg)
![drowing_category_not_loading](https://user-images.githubusercontent.com/43174699/71368865-16406b80-25cf-11ea-8710-88dee94828a8.jpg)

**Comment by minhcasi** [comment]
@minhtruong315 - could you help to zip our demo package and share for @kurkuteabhi 

We may include it on next release - thanks

**Comment by minhtruong315** [comment]
@kurkuteabhi can u give me your email?

**Comment by kurkuteabhi** [comment]
kurkute.abhi@gmail.com

**Comment by minhtruong315** [comment]
I sent you an email. Please check it

**Comment by minhtruong315** [comment]
@kurkuteabhi let me know when you install new website.

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
