### ISSUE TITLE
[MStore EXPO] - 

### ISSUE THREAD

**Issue by kiamoz** [inspireui/support#1674]
Hi there,here is json ( I changed wp to my own script ) but in search result, images not show !
which file should be edit to show image well ?
thanks a lot    

![Screen Shot 2019-12-22 at 6 05 09 PM](https://user-images.githubusercontent.com/10494372/71370900-a0370700-25c4-11ea-88f6-74e295a33080.png)
![1](https://user-images.githubusercontent.com/10494372/71370906-a6c57e80-25c4-11ea-91eb-b46de7081662.jpg)

**Comment by minhcasi** [comment]
@minhtruong315 - please help for checking  this issue and also help for #1675 and #1676

Thank you!

**Comment by minhtruong315** [comment]
@kiamoz can u send me AppConfig.json file?

**Comment by minhtruong315** [comment]
Hi @kiamoz can u send me AppConfig.json file?

**Comment by kiamoz** [comment]
Yes Sure  , I send my full source to truong@inspireui.com
[AppConfig.json.zip](https://github.com/inspireui/support/files/4001499/AppConfig.json.zip)

**Comment by kiamoz** [comment]
just let me know where is the file source for this page and the  check the image att, or maybe my json is  incorrect .

**Comment by minhtruong315** [comment]
@kiamoz add my skype: minhtruong315
I'll help u check it via teamviewer.
Thanks

**Comment by kiamoz** [comment]
I solve this issue but I add him in skype  for  other  issued

**Comment by minhcasi** [comment]
oki, pls also download latest 3.9.7 for latest fixing - thanks
