### ISSUE TITLE
[MStore expo] - custom page not show 

### ISSUE THREAD

**Issue by kiamoz** [inspireui/support#1675]
check it out the screenshots , custom page  not show !
<img width="449" alt="Screen Shot 2019-12-23 at 9 13 52 PM" src="https://user-images.githubusercontent.com/10494372/71372275-25241f80-25c9-11ea-9921-ce513b8397d5.png">
<img width="551" alt="Screen Shot 2019-12-23 at 9 13 05 PM" src="https://user-images.githubusercontent.com/10494372/71372278-26554c80-25c9-11ea-94b6-adcdce437e1d.png">
<img width="545" alt="Screen Shot 2019-12-23 at 9 12 59 PM" src="https://user-images.githubusercontent.com/10494372/71372279-26554c80-25c9-11ea-92f3-098882c9ff81.png">

**Comment by minhcasi** [comment]
moved to #1674

Please help to create one ticket for your all issues - thanks
