### ISSUE TITLE
[mstore EXPO] -  RTL not work

### ISSUE THREAD

**Issue by kiamoz** [inspireui/support#1676]
Hi there , I'm your old customer , and now in new ver I can't use RTL layout , when I change it notting happened also I clear app in simulation .
thanks .

<img width="469" alt="Screen Shot 2019-12-23 at 9 17 01 PM" src="https://user-images.githubusercontent.com/10494372/71372418-949a0f00-25c9-11ea-84c1-81966fc7f98d.png">

I sent my src file to you email  support@inspireui.com

**Comment by minhcasi** [comment]
moved to #1674

Please help to create one ticket for your all issues - thanks

**Comment by minhtruong315** [comment]
I replied. please check your email

**Comment by kiamoz** [comment]
I sent the full source , but I change the api-ecommerce , you wont see the content .. just check ten RTL issue and its not Pro its EXPO !

**Comment by minhcasi** [comment]
@kiamoz - confirm it is fixed on latest 3.9.7 - thanks

**Comment by kiamoz** [comment]
not fixed ! @minhcasi
