### ISSUE TITLE
[FluxStore MV] - I Can't release my Apk on Android Studio

### ISSUE THREAD

**Issue by antixirus** [inspireui/support#1677]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
I Can't release my APK, Notice error in screenshot

2. Screenshots issues:
![gambar](https://user-images.githubusercontent.com/57300649/71397685-cefabf00-2650-11ea-846f-517e70b7ac03.png)

3. Proof of my purchased:
![gambar](https://user-images.githubusercontent.com/57300649/71397752-fce00380-2650-11ea-848d-52d9d7cb3b1e.png)

3. Config files (optional)

FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Transformation hasn't been executed yet                                 
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 4s                                                      
Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                       4,9s
Gradle task assembleRelease failed with exit code 1

**Comment by minhtruong315** [comment]
please ping me on the skype when you're online. Thanks

**Comment by minhtruong315** [comment]
Supported
