### ISSUE TITLE
[my-product] - Fluxstore Multivendor

### ISSUE THREAD

**Issue by Maczidane** [inspireui/support#1678]
1. My issue:

Error at checkout : Exception You need to login to checkout.

I am already login to app so why do i keep getting these issues. Please help

![Screenshot_2019-12-24-11-54-45](https://user-images.githubusercontent.com/29797896/71410383-5b9f8000-2645-11ea-8abd-d794770b04f2.png)

2. Screenshots issues:

![Screenshot_2019-12-24-11-54-45](https://user-images.githubusercontent.com/29797896/71410383-5b9f8000-2645-11ea-8abd-d794770b04f2.png)

3. Proof of my purchased:

![Screenshot 2019-12-24 at 6 00 42 PM](https://user-images.githubusercontent.com/29797896/71410462-a1f4df00-2645-11ea-8d95-9ea4f03626ab.png)

3. Config files (optional)

**Comment by vumanhsn97** [comment]
@Maczidane Follow this issue https://github.com/inspireui/support/issues/1658

**Comment by Maczidane** [comment]
Please i need a fix to my issue

**Comment by vumanhsn97** [comment]
@Maczidane Send account login, config.dart, config.json, website url to vumanhsn97@gmail.com. I will check for you

**Comment by Maczidane** [comment]
> @Maczidane Send account login, config.dart, config.json, website url to [vumanhsn97@gmail.com](mailto:vumanhsn97@gmail.com). I will check for you

Its sent, please check your mail

**Comment by vumanhsn97** [comment]
@Maczidane It work well! You can waiting for next version update. Or you can download link resource in your mail. Check it!!! :))
