### ISSUE TITLE
Fluxstore Pro - Issue with shipping method

### ISSUE THREAD

**Issue by jpmishra1010** [inspireui/support#1680]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: Its my humble request to help me with the shipping option. Its never that it doesn't support multiple shipping option. What's the use of this app if I can't deliver it??
![Screenshot_20191217-232100](https://user-images.githubusercontent.com/32157980/71415787-86a8c480-2683-11ea-91f2-e5e5eeb68233.jpg)

![Screenshot_20191224-193025_Chrome](https://user-images.githubusercontent.com/32157980/71416097-0d11d600-2685-11ea-8d3e-05aa3f7bcf84.jpg)

**Comment by jpmishra1010** [comment]
Is there anyone who could help me out?

**Comment by jpmishra1010** [comment]
???? Why aren't you replying? I paid for this app

**Comment by minhcasi** [comment]
@jpmishra1010 - sorry as we have some holiday break - could you share your current config files as well?

@minhtruong315 - please help for checking this issue

**Comment by minhtruong315** [comment]
Hi @jpmishra1010 can u send me config.dart file
I'll help u check your issues
Thanks

**Comment by jpmishra1010** [comment]
[Config.zip](https://github.com/inspireui/support/files/4011944/Config.zip)

**Comment by jpmishra1010** [comment]
Any update?

**Comment by minhcasi** [comment]
@jpmishra1010 - could you try with the latest release 1.6.1 - the team confirm to fix the shipping issue on this release - thank you!

**Comment by minhcasi** [comment]
Let us know if still have the problem and reopen the ticket - thanks

**Comment by jpmishra1010** [comment]
Even after updating the app. Facing same issue.
![Screenshot_20200111-051606](https://user-images.githubusercontent.com/32157980/72194164-99b4e600-3432-11ea-8bf1-40a1ff808da3.jpg)

**Comment by minhcasi** [comment]
@jpmishra1010  - pls try the latest one 1.6.2 - the screenshot look seem the old version - thank you!

**Comment by jpmishra1010** [comment]
I encountered one more issue. Here whenever I try to search anything it gives no product result. 
Please help me with both the things. 

![Screenshot_20200111-200950](https://user-images.githubusercontent.com/32157980/72205944-8e9f9b80-34ae-11ea-8774-a7220c4e453f.jpg)

**Comment by jpmishra1010** [comment]
I am still waiting for a response. Why are you delaying it?

**Comment by jpmishra1010** [comment]
I am losing my client and I am not getting support from you guys. Its almost a month for the same issue. How can I get a refund?

**Comment by minhcasi** [comment]
@jpmishra1010 - you can submit on this link https://help.market.envato.com/hc/en-us/articles/202821460-Can-I-Get-A-Refund- - thanks

**Comment by jpmishra1010** [comment]
You are helping everyone except me. Why? I will lose my client please help me with this. Please.. @minhcasi @minhtruong315 @vumanhsn97 @luyx2412
