### ISSUE TITLE
[Mstore pro ] -  i have problem with Multi Currency in app 

### ISSUE THREAD

**Issue by hami44** [inspireui/support#1681]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
i have problem with Multi Currency in app when i change the currency i dont have any action ! 
it still with default currncy 
2. Screenshots issues:
![image](https://user-images.githubusercontent.com/58168661/71416046-dda49e80-266f-11ea-8d6f-2231a8d7e09a.png)
![image](https://user-images.githubusercontent.com/58168661/71416061-f01ed800-266f-11ea-831f-c75cd4687ad0.png)
![image](https://user-images.githubusercontent.com/58168661/71416110-29574800-2670-11ea-8f24-72f4d11fe499.png)
![image](https://user-images.githubusercontent.com/58168661/71416118-3411dd00-2670-11ea-8b1a-dd536f3afc1e.png)

3. Proof of my purchased:
![image](https://user-images.githubusercontent.com/58168661/71416139-48ee7080-2670-11ea-9e69-c90a479d78a7.png)

3. Config files (optional)

**Comment by hami44** [comment]
@minhcasi

**Comment by minhtruong315** [comment]
@hami44 pls add my skype: minhtruong315. I'll help you check it via teamviewer

**Comment by minhcasi** [comment]
@hami44 - pls download latest 3.9.7 that included the multi current switching - thanks
