### ISSUE TITLE
[Mstore Shopify-1.5.2] - Problem with setup and installation on Mac

### ISSUE THREAD

**Issue by amiteshsah** [inspireui/support#1682]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
SDK Version issue.

**The experience you requested uses Expo SDK v(null), but this copy of Expo Client requires at least v33.0.0. The author should update their experience toa newer Expo SDK Version.** 

I followed the get started approach mentioned in the following documentation link. 
[](https://docs.inspireui.com/mstore-shopify/getting-started/)

Also, there were lots of errors when I ran the yarn install such as build error, stack error, etc.
_gyp ERR! node -v v12.13.0
gyp ERR!  node-gyp -v v5.0.5
node-gyp -vgyp  v5.0.5
ERR! gypnot ok 
 ERR! not ok 
node-pre-gyp ERR! build error_ 

2. Screenshots issues:
<img width="300" alt="Screen Shot 2019-12-24 at 12 03 02 PM" src="https://user-images.githubusercontent.com/18745883/71421050-76262900-2646-11ea-94e0-5587ad819a0c.png">

![image](https://user-images.githubusercontent.com/18745883/71421891-d7043000-264b-11ea-87ca-3ae65d1584aa.png)

3. Proof of my purchased:
Date: 22 Dec 2019
Item Purchase Code: 0d419f94-e477-454f-8293-c0b72759ee32

3. Config files (optional)

**Comment by amiteshsah** [comment]
Can you please provide any update on this issue?

**Comment by minhcasi** [comment]
@amiteshsah - pls help to download the latest 1.5.3 to fix the Expo issue - thanks
