### ISSUE TITLE
[my-product] - MS Store - Getting product ascending(it should be descending )

### ISSUE THREAD

**Issue by khiemhuynh95** [inspireui/support#1683]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
My MS-Store getting product in the ascending order while it should be descending. I may mess up somewhere. Any reference I should look at to fix this problem? Thanks

2. Screenshots issues:

3. Proof of my purchased:

3. Config files (optional)

**Comment by minhcasi** [comment]
@khiemhuynh95 - could you share the screenshot issues + config files so that we could help for checking? Thank you!

**Comment by khiemhuynh95** [comment]
Hi, here are my config files
https://github.com/khiemhuynh95/mstore-issues

screenshot: The left-most product is the oldest, while I need it the newest.
![Screenshot_20191225-165851316](https://user-images.githubusercontent.com/15665845/71451288-f37d9680-2737-11ea-9126-ee5a5c012774.jpg)

**Comment by minhcasi** [comment]
@khiemhuynh95 - pls try with latest 3.9.7 for the fixing - thank you!

**Comment by khiemhuynh95** [comment]
3.9.6 fixed it
