### ISSUE TITLE
 FluxStore Listing - Directory app by Flutter

### ISSUE THREAD

**Issue by najeebalnasser** [inspireui/support#1685]
hello there,
I have a problem with installing the listapp mobile manager. I will attach a screen shots.
![listapp](https://user-images.githubusercontent.com/59208318/71446722-148db980-272f-11ea-9054-f61800fb53a0.PNG)
![products](https://user-images.githubusercontent.com/59208318/71446723-148db980-272f-11ea-8175-553cbb41af18.PNG)

---------

**Comment by minhcasi** [comment]
@najeebalnasser - please help to disable the Mstore API (if you have installed) or Mstore Checkout - we only use the ListApp Mobile Manager for FluxListing - thank you!

**Comment by najeebalnasser** [comment]
thanks a lot Minhcasi. my issue with the plugin was solved.

**Comment by minhcasi** [comment]
@najeebalnasser -  We're glad that it help for resolving the issue. Kindly help us to give some feedback & rating to - http://codecayon.net/downloads

I hope you have success with the app, and if you have any more issues don't hesitate to add new ticket support - thank you!
