### ISSUE TITLE
[Mstore Pro] - Invalid Username / Email (Cannot sign in or up)

### ISSUE THREAD

**Issue by alexisttt** [inspireui/support#1687]
1. My issue:
I cannot login via my app or sign up. When i try to login i get the error bellow. When i try to sign up it looks like it's working and redirects it to home page but there is not any user in the wordpress. Also it states in redirect moment as welcome undefined. 

I have installed the app required as stated in the guide and also customized the config file as suggested. I can see the products in the website. I can also add them to cart. And search them. If you would like i can forward the config files to your email or provide you more information you would like.
Waiting for your help... Many thanks...

2. Screenshots issues:

![photo_2019-12-26_00-29-52](https://user-images.githubusercontent.com/45356673/71450728-6e66a180-2778-11ea-8830-d18b1d57dbb6.jpg)

3. Proof of my purchased:

[https://user-images.githubusercontent.com/45356673/71313053-67702400-2444-11ea-8138-8162fa0d8a5b.png](url)

3. Config files (optional)

Stars added purposely because of privacy and security concerns. Site and key are valid and right

![Screenshot from 2019-12-26 00-42-52](https://user-images.githubusercontent.com/45356673/71450742-b4236a00-2778-11ea-9b45-f1ea9f6f6899.png)

**Comment by minhcasi** [comment]
@alexisttt - note with checking - thank you!

**Comment by alexisttt** [comment]
Sorry for the missing the title field. Thanks, waiting for it

**Comment by alexisttt** [comment]
Dear @minhtruong315 solved the problem. Thanks for the help.
