### ISSUE TITLE
[Fluxstore MW] My images are hosted elsewhere.

### ISSUE THREAD

**Issue by SB-Engineering** [inspireui/support#1688]
Dear @minhcasi ,

My images are hosted elsewhere. How may i bypass the image regeneration? I have over 25k existing products on my store in which i cannot regenerate the images of.

Can you please help me with bypassing this process? There must be another way then downloading images of 25k products onto my server and regenerating them.
Proof of purchase

![image](https://user-images.githubusercontent.com/59212578/71451311-9949f900-276a-11ea-9222-a436985d5cca.png)

Thank you very much in advance

**Comment by minhcasi** [comment]
@SB-Engineering - it's possible to use the default image without compression for your product - do you use any plugins to compress the image to optimize your website loading?

**Comment by SB-Engineering** [comment]
Hi Minh Pham Sir,

Dont have any compression going on but all my product images are external images.

Here is an example:
https://www.sebuys.com/shop/mens-original-adidas-trefoil-fleece-hoodie-fleece-sweatshirt-pullover-jumper/

if you click on the image itself, you can see that the link is an external link.
It will be a big issue to download all these images/import products again(25K products).

What can i do in this case? 

Thank you very much in advance Sir

**Comment by SB-Engineering** [comment]
Can you please help me with this situation? My images are not appearing on the app.

**Comment by SB-Engineering** [comment]
@minhcasi can you please look into my issue sir.

**Comment by minhcasi** [comment]
@SB-Engineering - from the common/tools.dart - pls try to remove this line of code - https://tppr.me/5HTjd - it will load the full url as default - thank you!

**Comment by SB-Engineering** [comment]
Hi Sir @minhcasi 

Thanks for the reply. I tried the fix. It doent works. Images are **not** loading still.

![image](https://user-images.githubusercontent.com/59212578/71521664-93166280-28b9-11ea-81ee-eecc9f2ff504.png)

Have also seen this in the console log when clicking on a single product.

I/flutter ( 6707): Exception: No route was found matching the URL and request method
E/flutter ( 6707): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The method '[]' was called on null.
E/flutter ( 6707): Receiver: null
E/flutter ( 6707): Tried calling: []("src")
E/flutter ( 6707): #0      WooCommerce.getProductVariations (package:fstore/services/woo_commerce.dart:291:7)
E/flutter ( 6707): <asynchronous suspension>
E/flutter ( 6707): #1      Services.getProductVariations (package:fstore/services/index.dart:213:25)
E/flutter ( 6707): <asynchronous suspension>
E/flutter ( 6707): #2      StateProductVariant.getProductVariantions (package:fstore/screens/detail/product_variant.dart:35:20)
E/flutter ( 6707): #3      StateProductVariant.initState (package:fstore/screens/detail/product_variant.dart:103:7)
E/flutter ( 6707): #4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4428:58)
E/flutter ( 6707): #5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4274:5)
E/flutter ( 6707): #6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3269:14)
E/flutter ( 6707): #7      MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5627:32)
E/flutter ( 6707): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3269:14)
E/flutter ( 6707): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:3063:12)
E/flutter ( 6707): #10     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5518:14)
E/flutter ( 6707): #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3269:14)
E/flutter ( 6707): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:3063:12)
E/flutter ( 6707): #13     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5518:14)
E/flutter ( 6707): #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3269:14)
E/flutter ( 6707): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:3063:12)
E/flutter ( 6707): #16     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5518:14)
E/flutter ( 6707): #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3269:14)
E/flutter ( 6707): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:3063:12)
E/flutter ( 6707): #19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4316:16)
E/flutter ( 6707): #20     Element.rebuild (package:flutter/src/widgets/framework.dart:4020:5)
E/flutter ( 6707): #21     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4279:5)
E/flutter ( 6707): #22     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4274:5)
E/flutter ( 6707): #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3269:14)
E/flutter ( 6707): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:3063:12)
E/flutter ( 6707): #25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4316:16)
E/flutter ( 6707): #26     Element.rebuild (package:flutter/src/widgets/framework.dart:4020:5)
E/flutter ( 6707): #27     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4279:5)
E/flutter ( 6707): #28     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4274:5)
E/flutter ( 6707): #29     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:4690:11)
E/flutter ( 6707): #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3269:14)
E/flutter ( 6707): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:3063:12)
E/flutter ( 6707): #32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4316:16)
E/flutter ( 6707): #33     Element.rebuild (package:flutter/src/widgets/framework.dart:4020:5)
E/flutter ( 6707): #34     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4279:5)
E/flutter ( 6707): #35     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4454:11)
E/flutter ( 6707): #36     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4274:5)
E/flutter ( 6707): #37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3269:14)
E/flutter ( 6707): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:3063:12)
E/flutter ( 6707): #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4316:16)
E/flutter ( 6707): #40     Element.rebuild (package:flutter/src/widgets/framework.dart:4020:5)
E/flutter ( 6707): #41     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4279:5)
E/flutter ( 6707): #42     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4274:5)
E/flutter ( 6707): #43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3269:14)
E/flutter ( 6707): #44     Element.updateChild (package:flutter/src/wi
I/flutter ( 6707): RangeError (index): Invalid value: Valid value range is empty: 0
I/chatty  ( 6707): uid=10134(com.inspireui.fluxstore.vendor) Thread-4 identical 18 lines
I/flutter ( 6707): RangeError (index): Invalid value: Valid value range is empty: 0



**Can you please provide a fix as soon as you can.**

**Comment by minhcasi** [comment]
@SB-Engineering - please help to share your config file here - we will check for fixing this issue - thank you!

**Comment by SB-Engineering** [comment]
![image](https://user-images.githubusercontent.com/59212578/71544282-29f42500-2975-11ea-8611-42f76f49e72c.png)

**Comment by SB-Engineering** [comment]
@minhcasi @vumanhsn97  check it out. Also you closed this issue - 1699 and told me to mention all my issues together. So let me mention that issue again. 

As per your guide, when i comment the flr splashscreen and comment out the png splash screen, it reloads in debug mode.

This only happens with the static splash screen. My custom one that i made or your default template one as seen in screenshot attached.
https://user-images.githubusercontent.com/59212578/71536778-085e5380-290b-11ea-9ba0-c852abad390e.png

You said this problem will go in production mode but how do i test my static splashscreen before uploading to production? When i add any static one, the app loads in debug mode and a debug splash screen is loaded (not one i set). Anyway please solve the image issue first, before the splash screen one.

Can you please treat it as high priority.
Thanks,

**Comment by SB-Engineering** [comment]
Here is my updated config.

I had to change it just now because of security reasons. 
![image](https://user-images.githubusercontent.com/59212578/71557349-cfbe9700-2a3c-11ea-845a-234d739adccb.png)

Where is the update on my issues? @minhcasi @vumanhsn97

**Comment by SB-Engineering** [comment]
@minhcasi waiting for 4 days. @vumanhsn97

**Comment by vumanhsn97** [comment]
@SB-Engineering Can you send your config.dart and admin account to vumanhsn97@gmail.com?

**Comment by SB-Engineering** [comment]
@minhcasi @vumanhsn97  I just sent it. Please give me an update.

**Comment by SB-Engineering** [comment]
@vumanhsn97 @minhcasi  Gave you a reply to your reply. Please give me an update.

**Comment by inspireui-support** [comment]
@SB-Engineering - please help to update to latest 1.6.3 for the fixing 

Thank you for your patience, let us know if you have any further issues.
