### ISSUE TITLE
[Mstore Pro] - New Payment Gateway Issue

### ISSUE THREAD

**Issue by alexisttt** [inspireui/support#1689]
1. My issue:
Hello again. I have a working website and a payment gateway (paytr). Which both works fine in the web. I have followed the steps on the video tutorial and also the guide for setting the new payment gateway. Everything looks fine until choosing the gateway and trying to make a payment. App opens a web view like it should. But nothing loads to the page or happens. It just stay blank. (It stayed for ten minutes like that, can be seen in the screenshots) When i check my website i don't see any order or order attempts. I can make an order through website (with paytr payment gateway) and it works. To test the app i activated cash on delivery option. And it works perfectly. I can place an order with it.

Before opening the ticket i have checked the support section, and cannot fine any solutions for the problem. I also find a question answered by you in this [link.](https://docs.inspireui.com/mstore/questions/#404-error-page-when-process-the-payment-)  But everythiny said was already like that. If you need any more information i can pass it to you via e-mail.
Payment Gateway: Paytr (It's a turkish payment gateway firm)

Waiting for your help. Many thanks... 
 
2. Screenshots issues:
![photo_2019-12-26_11-52-18](https://user-images.githubusercontent.com/45356673/71468210-3db55500-27d6-11ea-9e52-45eafa514b45.jpg)
![photo_2019-12-26_11-51-01](https://user-images.githubusercontent.com/45356673/71468213-4017af00-27d6-11ea-803b-94a3d18f58c5.jpg)
![photo_2019-12-26_11-51-01 (2)](https://user-images.githubusercontent.com/45356673/71468215-41e17280-27d6-11ea-8112-e06dd90cb7f1.jpg)

3. Proof of my purchased:
[proff](https://user-images.githubusercontent.com/45356673/71313053-67702400-2444-11ea-8138-8162fa0d8a5b.png)

3. Config files (optional)
![Screenshot from 2019-12-26 11-59-59](https://user-images.githubusercontent.com/45356673/71468523-5114f000-27d7-11ea-9b33-e11db9aa36cd.png)

**Comment by minhtruong315** [comment]
@alexisttt can you send me full source code and admin account to login to your website via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/1689

**Comment by alexisttt** [comment]
Hi I'm currently away of working desk. I'll be sending them on Monday morning (Vietnam time). I'll remind you from here when I send it. Thanks for your understanding.

**Comment by minhtruong315** [comment]
ok. thanks

**Comment by alexisttt** [comment]
I just mailed you. Waiting for your reply. Many Thanks

**Comment by minhtruong315** [comment]
ok. let me check

**Comment by minhtruong315** [comment]
I replied on email. pls check

**Comment by alexisttt** [comment]
Thanks for quick answer. Just relied back via email. please check

**Comment by minhtruong315** [comment]
supported
