### ISSUE TITLE
[MStore, CESTORE App] Recovery password

### ISSUE THREAD

**Issue by theleolife** [inspireui/support#169]
**Required Info (please complete the following information):**
 - Product: [e.g. MStore, ListApp]
 - Your Purchased Code: [get from https://codecanyon.net/downloads]
(we may not reply if you are not our customer)

App Cestore how customers can recovery password on the app? I could not find anything about on the app or web version.

**Comment by minhtruong315** [comment]
Hi @theleolife Thank you for your suggestion, we have noted for investigating

**Comment by minhcasi** [comment]
Noted - https://github.com/inspireui/support/projects/6
