### ISSUE TITLE
[FLUXSTORE 1.6] - EXAMPLE THEMES NOT WORKING.

### ISSUE THREAD

**Issue by rioadetya** [inspireui/support#1690]
1. My issue:
theme 4 , 5, 15 not working.
category layout when i set wrap = true http://prntscr.com/qcuz7t showing error like this. http://prntscr.com/qcuzut
i want to make category looks like this http://prntscr.com/qcv07g

please fix it ASAP.

2. Screenshots issues:
http://prntscr.com/qcuzut

3. Proof of my purchased:
623d60f6-69ea-4c79-9afb-5254d6049c68

Date: 09 Dec 2019
Invoice No: IVIP35543938
Order No: 116954158

**Comment by vumanhsn97** [comment]
@rioadetya 
Change your file in lib/widgets/home/category/category_icon_items.dart to 
[category_icon_items.dart.zip](https://github.com/inspireui/support/files/4003953/category_icon_items.dart.zip)

**Comment by rioadetya** [comment]
config_theme4.json = working
config_theme5.json = still not working http://prntscr.com/qgae81

**Comment by minhcasi** [comment]
fixed on latest 1.6.1 - it will be ready for download today - thanks
