### ISSUE TITLE
[Fluxstore App] - Version: 1.6.0---- Unable to build release APK....top Priority issue

### ISSUE THREAD

**Issue by itej7** [inspireui/support#1691]
Hi InspireUI Team,

1. My issue: We are getting below error in Fluxstore WooCommerce - Flutter E-commerce App while trying to build signed APK through flutter build APK command. Please take this on priority as we are not able to get release APK for our app and hence are unable to launch the app on Playstore and Appstore for last 5 days. Kindly look into this and update us as early as possible.

Console Output for your reference:

D:\AndroidStudioProjects\FluxStore-woo 1.6.0\source>flutter build apk
You are building a fat APK that includes binaries for android-arm, android-arm64, android-x64.
If you are deploying the app to the Play Store, it's recommended to use app bundles or split the APK to reduce the APK size.
    To generate an app bundle, run:
        flutter build appbundle --target-platform android-arm,android-arm64,android-x64
        Learn more on: https://developer.android.com/guide/app-bundle
    To split the APKs per ABI, run:
        flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
        Learn more on:  https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split
Running Gradle task 'assembleRelease'...

FAILURE: Build failed with an exception.

* What went wrong:

Execution failed for task ':device_apps:verifyReleaseResources'.

> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade

   > Android resource linking failed

     C:\Users\Quantic6\.gradle\caches\transforms-2\files-2.1\4f0b44f7f428d6290dab406d040ef57b\core-1.0.0\res\values\values.xml:57:5-88:25: AAPT: error: resource android:attr/fontVariationSettings
not found.

     C:\Users\Quantic6\.gradle\caches\transforms-2\files-2.1\4f0b44f7f428d6290dab406d040ef57b\core-1.0.0\res\values\values.xml:57:5-88:25: AAPT: error: resource android:attr/ttcIndex not found.

* Try:

Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5m 54s
Running Gradle task 'assembleRelease'...                          356.6s (!)
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin apple_sign_in...
Running Gradle task 'assembleAarRelease'...                        61.1s
√ Built build\app\outputs\repo.
Building plugin cloud_firestore...
Running Gradle task 'assembleAarRelease'...
The plugin cloud_firestore could not be built due to the issue above.

2. Screenshots issues:

![image](https://user-images.githubusercontent.com/50324759/71476044-0d3ade80-2809-11ea-8294-3d26d9a3b5e3.png)

3. Proof of my purchase:

Product Purchase code: c2f1abaf-6ebe-4c07-875d-050022ba2a14 - 14 Oct 2019 REGULAR LICENSE

**Comment by minhcasi** [comment]
@minhtruong315 - please help for checking

**Comment by minhtruong315** [comment]
@itej7 Add my skype: minhtruong315
I'll help u check via teamviewer. Thanks

**Comment by itej7** [comment]
@minhtruong315 : I have messaged you on skype with issue number. Please reply

**Comment by itej7** [comment]
@minhtruong315 : After teamviewer session we are able to build release APK. Thanks for your support!! much Appreciated !!!!!!!! Kindly close this ticket

**Comment by mayankgirdhar** [comment]
am also getting same issue how to solve it.

**Comment by mohamedahmedhassan00** [comment]
i also have a same issue
