### ISSUE TITLE
(Listapp) it’s been a month with no help 

### ISSUE THREAD

**Issue by befreeman5** [inspireui/support#1692]
I keep getting assigned to people that don’t even work on listapp or I give my details to then they go home for lunch and never return. This is the weirdest support I’ve ever received. Still so many errors and this app doesn’t work

**Comment by minhcasi** [comment]
@befreeman5 the current Listapp is not working with the multi-site as the API is not compatible - kindly process the refund it could not use the product - thank you!

**Comment by befreeman5** [comment]
it does work with multi site. why would this be an issue?
