### ISSUE TITLE
(listapp) multisite works fine. your support staff keeps looking in the wrong place 

### ISSUE THREAD

**Issue by befreeman5** [inspireui/support#1693]
im watching them on TeamViewer look in the wrong place every time. how do I get proper support? its crazy how frustrating this is. real support shouldn't take this long.

**Comment by minhcasi** [comment]
Hi, sorry for the issues, as we investigate so far the Rest API will not work well on multisite so that you will get integrate with the app, that's why they could have a check the issue - very best!

**Comment by befreeman5** [comment]
https://www.google.com/search?q=rest+api+multisite&ie=UTF-8&oe=UTF-8&hl=en&client=safari

Everything says that rest api works with multi site
