### ISSUE TITLE
Mstore - Bug SlideItem

### ISSUE THREAD

**Issue by Jenarath** [inspireui/support#1694]
1. Mstore - Bug SlideItem 
Folder components -> SlideItem
Error :  scrollToIndex 
How to solve it ?

2. Screenshots issues:

![738](https://user-images.githubusercontent.com/25680869/71512089-52254a80-28c7-11ea-9071-ed5a913e660a.jpg)

3. Proof of my purchased:
<img width="520" alt="Screen Shot 2562-12-27 at 16 38 44" src="https://user-images.githubusercontent.com/25680869/71512074-3f127a80-28c7-11ea-9ad1-fd98302bc62b.png">

4. File folder components -> SlideItem -> index.js
file index.js in folder SlideItem
[index.js.zip](https://github.com/inspireui/support/files/4004914/index.js.zip)

**Comment by minhcasi** [comment]
@Jenarath - confirm this issue is fixed on the latest 3.9.7 - we will update it on 2-3 days - thank you!
