### ISSUE TITLE
[MStore Pro] - Product Images not loading & Sign Up & login not working

### ISSUE THREAD

**Issue by AbdelhalimEmaraCreativeEagles** [inspireui/support#1695]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: 
After setting up the appconfig and config as descriped in the docs app not showing product images in any view, app configured with CBuilder and AppConfig.js 

second issue is login and signup it always send empty username and email to wordpress and user is not created 

2. Screenshots issues: 
![IMG_5984](https://user-images.githubusercontent.com/58397536/71515491-c817ba80-28a3-11ea-8741-0b094eb977a5.PNG)
![IMG_5983](https://user-images.githubusercontent.com/58397536/71515493-c8b05100-28a3-11ea-8c77-22cd5881bcc2.PNG)
![IMG_5982](https://user-images.githubusercontent.com/58397536/71515494-c8b05100-28a3-11ea-8f7b-95734fe55d91.PNG)
![IMG_5981](https://user-images.githubusercontent.com/58397536/71515495-c8b05100-28a3-11ea-90dd-90e961b11948.PNG)
![IMG_5980](https://user-images.githubusercontent.com/58397536/71515496-c8b05100-28a3-11ea-9402-71de4f74dcd4.PNG)
![IMG_5979](https://user-images.githubusercontent.com/58397536/71515497-c948e780-28a3-11ea-8857-e2bc4b80c744.PNG)

3. Proof of my purchased:

<img width="819" alt="Bildschirmfoto 2019-12-27 um 12 25 02" src="https://user-images.githubusercontent.com/58397536/71515551-1e84f900-28a4-11ea-9c5c-fc4643d4d7b8.png">

3. Config files (optional)

**Comment by AbdelhalimEmaraCreativeEagles** [comment]
<img width="1552" alt="Bildschirmfoto 2019-12-27 um 12 28 03" src="https://user-images.githubusercontent.com/58397536/71515612-63a92b00-28a4-11ea-8292-bcea86c045c6.png">

**Comment by minhcasi** [comment]
@AbdelhalimEmaraCreativeEagles - confirm this is fixed on the latest version 3.9.7 - we will update in 1-2 days - thank you!
