### ISSUE TITLE
[Beonews] - Shortcodes used inside wordpress blog post are not displayed in the app 

### ISSUE THREAD

**Issue by dermayank** [inspireui/support#1697]
We are using shortcodes inside a blog post on our WordPress website and they are being displayed there but inside the app on expanding the post, the shortcodes are not working instead it is blank.
Ex:
This is how the blog appears on the website 
![Screenshot from 2019-12-27 16-55-50](https://user-images.githubusercontent.com/24271097/71515652-64ed4e80-28ca-11ea-9fdb-7c0487adf665.png)

But this is how it is appearing in the app
![Screenshot_2019-12-27-16-51-09-56](https://user-images.githubusercontent.com/24271097/71515962-47b97f80-28cc-11ea-9cb4-ade387ccaa52.png)

Proof of purchase
![Screenshot from 2019-12-04 10-30-36](https://user-images.githubusercontent.com/24271097/71515787-56536700-28cb-11ea-9d43-b13676068513.png)

P.S. Please provide the solution on time.

**Comment by minhcasi** [comment]
@dermayank - you can try to edit the functions.php and add the function to RestAPI - it means render the shortcode from return JSON - example solution https://github.com/WP-API/WP-API/issues/2578

**Comment by dermayank** [comment]
@minhcasi What function do I need the add to functions.php and the RestAPI? Can you please provide the code regarding the same?

**Comment by minhcasi** [comment]
@dermayank - try this one by update the functions.php from your theme folder

add_action( 'rest_api_init', function ()
{
   register_rest_field(
          'page',
          'content',
          array(
                 'get_callback'    => 'compasshb_do_shortcodes',
                 'update_callback' => null,
                 'schema'          => null,
          )
       );
});

function compasshb_do_shortcodes( $object, $field_name, $request )
{
   WPBMap::addAllMappedShortcodes(); // This does all the work

   global $post;
   $post = get_post ($object['id']);
   $output['rendered'] = apply_filters( 'the_content', $post->post_content );

   return $output;
}

**Comment by triprethink** [comment]
I tried pasting these lines at the bottom of the function.php file of newspaper theme, but it didn't work.

**Comment by dermayank** [comment]
yes, even I tried pasting these lines at the bottom of the function.php file but it didn't work.

**Comment by minhcasi** [comment]
@dermayank - could you clarify which the shortcode from which plugins that you are using, elementor/ Visual composer or the Shortcode from WP...?

The above solution may not work complete for all plugins but you got the idea
