### ISSUE TITLE
[fluxstore mv] - username required and foreach method

### ISSUE THREAD

**Issue by ganesha10** [inspireui/support#1698]
1. My issue:
I tried using wclovers.mstore.io with wcfm config
console message:
`E/flutter (24985): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
E/flutter (24985): If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.`

and another issue
`
════════ (2) Exception caught by widgets library ═══════════════════════════════════════════════════
type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'String'
The relevant error-causing widget was: 
  FutureBuilder<List<Product>> file:///C:/finergi/kerja/flwkc02/lib/widgets/home/product_list_layout.dart:144:12
════════════════════════════════════════════════════════════════════════════════════════════════════`

when I tried to register an account, there is a popup message that it requires username 

then I tried on my own website
but when I tried to register an account or sign in, there is alway error 
nosuchmethoderror: the method 'foreach" ....

2. Screenshots issues:
this is the error when using your demo site
![username](https://user-images.githubusercontent.com/19354235/71535069-c8609600-2935-11ea-9264-38db895c4c5a.jpeg)

this is the error when using my own site
![errorforeach](https://user-images.githubusercontent.com/19354235/71535011-4ec8a800-2935-11ea-934e-b75c771c4cdc.jpeg)

3. Proof of my purchased:
![fluxstorepurchasedec](https://user-images.githubusercontent.com/19354235/71534430-5be39800-2931-11ea-8218-38705d254b5f.png)

3. Config files (optional)

**Comment by minhcasi** [comment]
@ganesha10 - note with checking - thank you!

**Comment by minhtruong315** [comment]
@ganesha10 can u send me config.dart file and admin account via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/1698
