### ISSUE TITLE
[Fluxstore MV] - Static Splash Screen comes up as debug mode.

### ISSUE THREAD

**Issue by SB-Engineering** [inspireui/support#1699]
1. My issue:
Hi Sir,

As per your guide, when i comment the flr splashscreen and comment out the png splash screen, it reloads in debug mode. 

This only happens with the static splash screen. My custom one that i made or your default template one as seen in screenshot attached.

2. Screenshots issues:
![image](https://user-images.githubusercontent.com/59212578/71536778-085e5380-290b-11ea-9ba0-c852abad390e.png)

3. Proof of my purchased:
https://user-images.githubusercontent.com/59212578/71451311-9949f900-276a-11ea-9222-a436985d5cca.png

Can you also take a look at **1688** as thats an urgent issue.

Thank you in advance.

**Comment by minhcasi** [comment]
@SB-Engineering - there is no problem with this debug mode status as it will remove when you release as a production app

This small issue also fixes on the latest source as well.

Please help us to raise one ticket for your all issue - that help us support you better with more focus on all issues - very best!

**Comment by SB-Engineering** [comment]
But how can i test my splash screen? It doenst come up When this debug mode is active.
