### ISSUE TITLE
[my-product] - mstore-expo  Default Product name (Which came along with this app) is working, as i am renaming its getting blank

### ISSUE THREAD

**Issue by onlineosman** [inspireui/support#1700]
Hi, 
Default Product name (Which came along with this app) is working, as i am renaming its getting blank, 

images attached.
![ERRORNAME](https://user-images.githubusercontent.com/34172061/71537313-c4cc0f80-2933-11ea-89c4-4610b18f196a.png)

**Comment by minhcasi** [comment]
Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads  it's used to verify your proof of purchase? sorry for any inconvenience - Thank you!

**Comment by onlineosman** [comment]
![Purchase proof for technical support](https://user-images.githubusercontent.com/34172061/71543715-b6134600-298f-11ea-8db4-947ca4938fbf.png)

**Comment by minhcasi** [comment]
@onlineosman - you can try to rename from the language file https://tppr.me/Vwjhn - as it is support to load multi-language

**Comment by onlineosman** [comment]
Working Thanks!
