### ISSUE TITLE
[Mstore Pro] - Feature request (terms & conditions - mail confirmation)

### ISSUE THREAD

**Issue by alexisttt** [inspireui/support#1702]
Hello. I have been trying the app and I think it is missing some features. For example terms and conditions check box. User must be check this box to order or it should not let user to continue. If there is not a check box or it does not save the information about it. It is punishable according to my country's rules. 

And other thing is mail confirmation. When I create an order from website I receive an email about it. But when I do it in the app I don't receive anything about it. It would be a nice touch thanks. 

Proof of my purchased:

[Proff](https://user-images.githubusercontent.com/45356673/71313053-67702400-2444-11ea-8138-8162fa0d8a5b.png)

**Comment by minhcasi** [comment]
@alexisttt - you can try to add the confirm option checkout box base on your business requirement. 

There is some option confirm from woocommerce for push email notify when purchase, please check this setting - https://docs.woocommerce.com/document/email-faq/ 

Thank you!

**Comment by alexisttt** [comment]
@minhcasi Thanks. I will be looking into the docs you shared. I'm trying to add the confirm box but it would be nice if it is default. Also could you point me some docs for adding the check box. I will appreciate it.

 And another suggestion i have is adding a separate billing section. Customers might have a different billing address then the delivery address. Like in the woocommerce website. Many thanks

**Comment by minhcasi** [comment]
@alexisttt - you can prefer some checkbox example here
https://reactnativeexample.com/tag/checkbox/
or https://snack.expo.io/@inspire/2d2720

**Comment by alexisttt** [comment]
@minhcasi  Thank you very much
