### ISSUE TITLE
[Fluxstore App] - Version: 1.6.0----Unable to fetch address fields from Google map during product checkout

### ISSUE THREAD

**Issue by itej7** [inspireui/support#1703]
Hi InspireUI Team,

My issue: We are not able to fetch address fields from google map while doing product checkout.
Kindly look into this on priority and assist us.

screenrecorder output of issue:

https://drive.google.com/open?id=1u2U8hgotUjsdb5tdT7zHNzpLXN-Pp21X

Proof of my purchase:
Product Purchase code: c2f1abaf-6ebe-4c07-875d-050022ba2a14 - 14 Oct 2019 REGULAR LICENSE

**Comment by minhcasi** [comment]
@itej7 - could i check if you change your own google map api key and download the google service to your project - https://docs.inspireui.com/fluxstore/firebase/ ?

**Comment by itej7** [comment]
@minhcasi : we have created our own Google map api key and also enabled all map services still it is not working. We are able to see the map and the location but it doesn't get filled in the address fields. Kindly look into this and assist us

**Comment by itej7** [comment]
@minhcasi : Kindly update us as early as possible.

**Comment by itej7** [comment]
@minhcasi : Can you please updates us as we are about to launch our app on playstore.

**Comment by minhcasi** [comment]
@minhtruong315  - pls help for checking

**Comment by itej7** [comment]
@minhtruong315 : Please take remote now. I have messaged you on skype.

**Comment by minhcasi** [comment]
moved to another support channel

**Comment by itej7** [comment]
@minhcasi : Can you please tell me why this ticket is closed? I have not yet received any solution.
Please check and update us.

**Comment by minhcasi** [comment]
@minhtruong315 - pls keep an update - thank you!

**Comment by itej7** [comment]
@minhtruong315 - I have sent an email  to you through my personal email ID: patiltejas02@gmail.com
Please check.

**Comment by minhtruong315** [comment]
@itej7 Please replace this file widgets/place_picker.dart then try again
[place_picker.dart.zip](https://github.com/inspireui/support/files/4018059/place_picker.dart.zip)

**Comment by itej7** [comment]
@minhtruong315 : I have replaced this new file in our App project but it is still not working. I have put the correct google map key both in AndroidManifest and config.dart file and also enabled all services.

Below link of screen recorded video

https://drive.google.com/open?id=1vFIDKKNlOo_4iLNojvq1pCaiKCO-wnvV

**Comment by itej7** [comment]
@minhtruong315 -- Can you please update me on this or let me know the status of this issue?

**Comment by minhtruong315** [comment]
supported.

**Comment by Elshaden** [comment]
I am getting exactly the same issue here, did you find a solution????
