### ISSUE TITLE
[my-product] - #1570

### ISSUE THREAD

**Issue by bhallaramdhatarwal** [inspireui/support#1704]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:

2. Screenshots issues:

3. Proof of my purchased:

3. Config files (optional)

**Comment by bhallaramdhatarwal** [comment]
My issue is : When i try to pay by using Razor pay but it's not complete and call back url problem and don't generate order Id & also not completed order 

![WhatsApp Image 2019-12-28 at 7 02 49 PM](https://user-images.githubusercontent.com/58734495/71544378-c386fb00-29a4-11ea-8170-db64762b4889.jpeg)

Proof of my purchased: ccdec22e-845a-4851-b065-2375e3b9cd37

**Comment by minhtruong315** [comment]
https://github.com/inspireui/support/issues/1541#issuecomment-567266615
@bhallaramdhatarwal check this solution

**Comment by bhallaramdhatarwal** [comment]
@minhtruong315 this not my solution because my problem in open-cart during make payment its complete done in test mode but when call back time it's show above screen short error. what i require to changes in call back process for successfully payment process.

Thanks

**Comment by minhtruong315** [comment]
@bhallaramdhatarwal add my skype: minhtruong315
I'll help u check it via teamviewer

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!

**Comment by bhallaramdhatarwal** [comment]
Please Reopen and help me "Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!" I was on holidays for new year celebration so that why i wasn't reply you. Now can you resolve me problem

**Comment by bhallaramdhatarwal** [comment]
@minhtruong315 please accept my request on skype : bhallaram74

**Comment by trunghieuvn** [comment]
Hi @bhallaramdhatarwal , please open AndroidManifest.xml
and add:
```
android:usesCleartextTraffic="true"
        android:supportsRtl="true"
```
Same as here:
<img width="675" alt="Screen Shot 2020-01-04 at 1 03 18 PM" src="https://user-images.githubusercontent.com/19247680/71760586-954c7280-2ef2-11ea-80b1-aa14020b0f2e.png">

**Comment by bhallaramdhatarwal** [comment]
@trunghieuvn @minhtruong315  

Hello 

I want to pay by using Razor Pay in flutter. When i try to pay by using Razor pay that time after success full test transaction It will call back URL need I little bit confuse about call back URL because call back URL is used into web site not in mobile application.

Thanks in Advance

**Comment by minhcasi** [comment]
@bhallaramdhatarwal - just let the default call back as the config that will not impact the payment process - we will remove this call back URL setting on the next release - thank you!

**Comment by minhtruong315** [comment]
@bhallaramdhatarwal pls update the latest source code in codecanyon to fix this issue. Then let me know your result. Thanks

**Comment by bhallaramdhatarwal** [comment]
@minhtruong315 Please give me some time for updating my code with updated source code. I will update you soon

**Comment by minhtruong315** [comment]
Are you using Fluxstore or Fluxstore MV? if you're using Fluxstore. You can update it now.

**Comment by bhallaramdhatarwal** [comment]
@minhtruong315 Thank you help. It's resolve problem.
