### ISSUE TITLE
Mstore- Issues with Attributes (Showing Size in Colours)

### ISSUE THREAD

**Issue by onlineosman** [inspireui/support#1706]
![Error Attributes](https://user-images.githubusercontent.com/34172061/71551799-f06cf980-2a08-11ea-9984-42390a0a58ee.png)

![Purchase proof for technical support](https://user-images.githubusercontent.com/34172061/71551795-ce737700-2a08-11ea-96e3-255231f81e32.png)

**Comment by minhcasi** [comment]
@onlineosman - it seems the website is using a custom variant plugin that could cause the issues - you can try to debug the issues from containers/Detail/index.js

There is the productAttributeColor field from common/constants.js file to identify the color properties.

Please try to use our pre-config site for reference to the issue - http://github.com/inspireui/mstore

**Comment by onlineosman** [comment]
We are using Dropping Shipping Plugin which automatically import's colors and sizes and we cannot change from woocommerce as it is it's default.

**Comment by onlineosman** [comment]
Tried deactivating variant plugins still same

**Comment by minhcasi** [comment]
@onlineosman - it may not work with these plugins as it is not compatible with default Woocommerce API, but you can try to customize the detail screen to meet your requirement - thanks
