### ISSUE TITLE
[Fluxstore Pro] - error when building release APK

### ISSUE THREAD

**Issue by Alnaggar94** [inspireui/support#1707]
1. My issue:
Hello, I was able to build release APK using the key store. and I didn't edit anything so far now when I try to build it, it shows me an error (see the screenshot)

2. Screenshots issues:

https://imgur.com/a/BQDi7cc

3. Proof of my purchased:

https://imgur.com/a/9TsYcIf

3. Config files (optional)

**Comment by minhtruong315** [comment]
@Alnaggar94 Add my skype: minhtruong315
I will help u check it via teamviewer
Thanks

**Comment by minhtruong315** [comment]
supported
