### ISSUE TITLE
[Fluxstore Pro] - Issue with the price of product in homepage and some issue while loading new category

### ISSUE THREAD

**Issue by masthan8** [inspireui/support#1709]
1. My issue:

a) The products that is being displayed in the homepage is showing the normal price as the sale price but inside product page its displaying properly. Please let me know how to fix that. 

b) There is some error being displayed whenever a category is accessed. Please check the screenshot attached,

2. Screenshots issues:

![image](https://user-images.githubusercontent.com/43437325/71558108-7d8f6d00-2a60-11ea-967a-db866837d9c5.png)

![image](https://user-images.githubusercontent.com/43437325/71558134-bdeeeb00-2a60-11ea-9493-de6bc35952a7.png)

3. Proof of my purchased:

![image](https://user-images.githubusercontent.com/43437325/71558113-85e7a800-2a60-11ea-84db-352d9393da5b.png)

3. Config files (optional)

**Comment by minhcasi** [comment]
move to #1708

@masthan8 - try to create on tickets and comments your all issues in one that helps us focus to support your ticket issue rather than create multiple one - also share your config file so that we could help for checking - thanks
