### ISSUE TITLE
[BeoNews] Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'. It will be removed at the end of 2018.

### ISSUE THREAD

**Issue by system112** [inspireui/support#171]
**Mandatory Info (please complete the following information):**
 - Product: BeonewsPro
 - Your Purchased Code: d7867c89-f1aa-4138-8fbd-cfe4ef495cd3

**Describe the issues**
I have a problem when rebuilding the project

**Screenshots**
https://system112.org/Screen%20Shot%202019-01-09%20at%2014.24.24.png

**Comment by levi-beers** [comment]
^ I second this request. While it doesn't necessarily break the build operation, it will when these are deprecated.

**Comment by minhcasi** [comment]
Noted for released on v.2.9.2
