### ISSUE TITLE
FluxStore Listing - Directory

### ISSUE THREAD

**Issue by najeebalnasser** [inspireui/support#1712]
hello there,
I am doing well with my Flutter app so far but I have this problem; I have no images for my listings & I can't open any listing from the app.
can you help me with this issue?
thanks a lot

![Capture](https://user-images.githubusercontent.com/59208318/71564147-bfda9d80-2aa4-11ea-97da-53d6bbd4978a.PNG)
? 
![fluxlisting](https://user-images.githubusercontent.com/59208318/71564128-53f83500-2aa4-11ea-8731-4b16f3abf169.JPG)

**Comment by minhcasi** [comment]
@najeebalnasser - i've sent the issue to the team for checking and will let you know

Could you attach your config file here so that we could have a check

**Comment by najeebalnasser** [comment]
hello there,
I wish you a happy new year full of success.
here is the config file that you asked for
thanks a lot

**Comment by minhcasi** [comment]
@najeebalnasser - wishes you had a great holiday and a happy new year!

Would you mind to attach the config file again as we could not get from the previous comment - https://tppr.me/1qEDU  - thank you!

**Comment by najeebalnasser** [comment]
hello,
sorry for being away! this is the config file
thanks a lot

[config.zip](https://github.com/inspireui/support/files/4026375/config.zip)

**Comment by minhcasi** [comment]
@najeebalnasser - i've forwarded to the team for checking

In the meantime could you help to checking following solution:
- active the Listapp Manager instead of Mstore API - https://vi.wordpress.org/plugins/listapp-mobile-manager/
- check the image render base on this guide- https://docs.inspireui.com/fluxstore/performance/#2-image-optimization

**Comment by philipvu30** [comment]
Hi najeebalnasser,

Sorry for late response, I have investigated and solved your issue with the listing. But it seems there is something wrong with your site so it cannot load the images for a specific category. 

Would you mind if I ask for your site's admin and password? You can send them privately to this email: toan@inspireui.com so I can assist you with your app asap. Thank you for your patience.

**Comment by philipvu30** [comment]
Hi najeebalnasser,

Thank you for your patience, I have modified your site and the config files, and it is running smoothly on my phone. I have included the files, instruction images and proof of the app is working below.

Feel free to ask me any question if you are in trouble. Have a nice day :)

config: [config_tejwaal.zip](https://github.com/inspireui/support/files/4095637/config_tejwaal.zip)
