### ISSUE TITLE
[FluxStore] - Shipping method

### ISSUE THREAD

**Issue by UTimung** [inspireui/support#1713]
Please help me to hide shipping class calculation formula 100*[qty]

I want to show only amount, not the formula
![Screenshot_20191223-135419](https://user-images.githubusercontent.com/18107447/71566040-3d6cd080-2ada-11ea-8507-8cff0fe92195.png)

![Screenshot_20191129-122203~2](https://user-images.githubusercontent.com/18107447/71566070-5ecdbc80-2ada-11ea-9654-c2b241b7dd11.png)

**Comment by vumanhsn97** [comment]
@UTimung 
Can you share config.dart, config.json files?

**Comment by UTimung** [comment]
here is my config.dart https://drive.google.com/open?id=1iCMZGLPoYQllk_jPCSgPZMZAGiXErCwI

config.json https://drive.google.com/open?id=1sl1YbkK1qSwnsVSMh9K6osI7ZsB3cZNf

**Comment by minhcasi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Advance Shipping Method](https://trello.com/c/MNgAtts6/12-advance-shipping-method)

**Comment by minhcasi** [comment]
move to Feature Request board
