### ISSUE TITLE
[mstore] - event on search  result  when click on back

### ISSUE THREAD

**Issue by kiamoz** [inspireui/support#1714]
hello every one ,
we I click on a product  on search result and then back from detailView , search screen clear but  loading still rouned ... 
is  any way to keep search result or remove loading ( I need the back event from detailView to search page )

thanks a lot

**Comment by minhcasi** [comment]
@kiamoz - could i confirm it is a bug from the latest version?

**Comment by kiamoz** [comment]
yes  but not check 3.7.9  yet , I chnaged on 3.7.6

**Comment by minhcasi** [comment]
@kiamoz - pls try with latest on for stable version - thank you!
