### ISSUE TITLE
[Fluxstore Pro] - Color attribute issue

### ISSUE THREAD

**Issue by Alnaggar94** [inspireui/support#1716]
1. My issue:

The problem is If I translate the attribute Color to Arabic or other languages it doesn't show the colors as a color circle it shows the color name instead

2. Screenshots issues:

If it's in English (it's show color circle fine):

![b3](https://user-images.githubusercontent.com/49800146/71573490-3901e100-2af5-11ea-895d-f5564a37dbaf.JPG)

If I changed it to Arabic or other languages it shows the color name instead :

![b2](https://user-images.githubusercontent.com/49800146/71573571-9bf37800-2af5-11ea-81b3-cf3182b168ce.JPG)

3. Proof of my purchased:

https://imgur.com/a/9TsYcIf

**Comment by Alnaggar94** [comment]
More Explaining :
I even tried to translate it using WooCommerce Multilingual -> Attributes  ->, It works fine in the website (English showing "Color" and Arabic showing "اللون") but in the app, it shows only in English "Color" and if I changed the Attributes name "Color" itself from Color  > to any other language or 
 other words it won't show the circle colors only names of color. 

So basically the translations for Attributes not working with WPML, It supposed to load the language of Attributes from WPML.

Please see what you can do about it as this really a big problem.

**Comment by Alnaggar94** [comment]
@minhcasi  @dttrung26  It's been 9 days without any reply regards the issue??

**Comment by minhcasi** [comment]
@Alnaggar94 - sorry for late response as i missed the email notification on this ticket

You can try to edit this file: https://tppr.me/WyycB

and hard code the condition to show the type as color, 
ex:  type: attr.name == 'اللون' ? 'color' : ProductVariantLayout[attr.name.toLowerCase()] ?? 'box',

**Comment by Alnaggar94** [comment]
@minhcasi -  It's partially worked,  It prints the attribute name itself  (for example If the attribute name is Color it will show it in all app language as "Color" and if I change it to "اللون" it will show it in all language as "اللون") In the website it shows "Color" in English version and "اللون" in Arabic version, I translate it with WPML but in the app it doesn't load the translation from WPML for attributes names, It shows the original name of the attribute in all app language.

**Comment by minhcasi** [comment]
@Alnaggar94 - could you help to zip the config file and send back us for checking, this could be the case that we have not changed the attribute as multi language

**Comment by Alnaggar94** [comment]
Yes, It doesn't sync the variations and products name from WPML.

Config.dart - https://www.dropbox.com/s/ekfsmyqbkrdcj5g/config.dart?dl=0

Config.json - https://www.dropbox.com/s/kivg4s25wiknhaj/config.json?dl=0
Config_ar.json - https://www.dropbox.com/s/9osfs1axaalydbw/config_ar.json?dl=0

**Comment by Alnaggar94** [comment]
@minhcasi  @vumanhsn97

**Comment by vumanhsn97** [comment]
@Alnaggar94 This bug is your website have same data in 2 languages. You can check api https://hawaml.com/wp-json/wc/v2/products?lang=en compare to https://hawaml.com/wp-json/wc/v2/products?lang=ar. In website https://tppr.me/ypyjk compare to https://tppr.me/2AydA

**Comment by Alnaggar94** [comment]
@vumanhsn97 - No it's not my website, I have removed all the products and create one test product you can check again (see the screen shots)


English website:

![en](https://user-images.githubusercontent.com/49800146/72114355-52582800-3354-11ea-9d83-b20c2d0d4222.JPG)



Arabic websites :

![ar](https://user-images.githubusercontent.com/49800146/72114343-48362980-3354-11ea-9b51-6b967e035291.JPG)


------------------

- *English app:

![app en](https://user-images.githubusercontent.com/49800146/72114389-6c920600-3354-11ea-81cf-5951e42acbc0.JPG)


- *Arabic app :

(Here is supposed to be Arabic like the website but it prints the original value of the attribute not the value from WPML like the website)

![app ar](https://user-images.githubusercontent.com/49800146/72114379-61d77100-3354-11ea-8210-67b133d3d940.JPG)



-----------------------------------

Translation through WPML setting:

![color setting](https://user-images.githubusercontent.com/49800146/72114433-8a5f6b00-3354-11ea-9d42-b997afabd968.JPG)

**Comment by vumanhsn97** [comment]
@Alnaggar94 Please check your website. You can see
- This is api your product "dress" in "ar" language: https://hawaml.com/wp-json/wc/v2/products/4292?lang=ar. You can click to "permalink" to see it. This return attribute name "English" https://tppr.me/IdCDb
- This is api your product "dress" in "en" language: https://hawaml.com/wp-json/wc/v2/products/4331?lang=en

Fluxstore app get data from api and show it same datas return.
Thanks!

**Comment by Alnaggar94** [comment]
@vumanhsn97 
That's what I was trying to explain, It shows the attribute name itself, I translate it through WPML and it works fine in the website if I change the language to English it will show "Color" if I changed it to Arabic it will show "اللون", but in the app it shows the main attribute name only. It supposed to load the variation names from WPML like when loading the products names and categories names.

![gggg](https://user-images.githubusercontent.com/49800146/72121610-a1aa5280-336c-11ea-8c90-1ce0f0c5d5e5.JPG)

**Comment by Alnaggar94** [comment]
@vumanhsn97 
try yourself :
https://hawaml.com/en/product/dress/
Try to change language from English to Arabic and the variation will change according to the language chosen. but in the app it shows only the original attribute name.

**Comment by vumanhsn97** [comment]
@Alnaggar94 I know.  It show correct in your website but api not correct. We just working with api. You can see 2 api above. It show attribute same name in 2 languages

**Comment by Alnaggar94** [comment]
How do I make it correct and show the right attribute for each language? Is there anything I can do to correct it?

**Comment by Alnaggar94** [comment]
@vumanhsn97 - I didn't hear back from you?

**Comment by Alnaggar94** [comment]
@minhcasi @vumanhsn97 Any Updates ??

**Comment by minhcasi** [comment]
@Alnaggar94 - we are working on this new update, it will include on next 1.6.3 

@vumanhsn97 - we could try to map the attribute by using slug, instead of name - ex: https://tppr.me/WyycB

**Comment by minhcasi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add API to translate the Attribute](https://trello.com/c/qY36MGGT/13-add-api-to-translate-the-attribute)

**Comment by minhcasi** [comment]
Move to the backlog as new request feature - https://trello.com/c/qY36MGGT/13-add-api-to-translate-the-attribute#

**Comment by Alnaggar94** [comment]
@minhcasi 
It's been more than a month and this problem not solved, and it doesn't get solved in the v1.6.3.
This is a real issue as everything gets translated when changing the language except the attribute!!

**Comment by Alnaggar94** [comment]
@minhcasi - any update?? it's been more than 3 months, This is a main feature it should be done since long time as everything get translate except the attribute this is a bug not a feature request.

**Comment by minhcasi** [comment]
Hi @Alnaggar94 - it will be include on next 1.6.5 that release on this week - thanks

**Comment by Alnaggar94** [comment]
Hi @minhcasi - it's been too long and it's not solving in the last version 1.6.6b, you mentioned that you have added the API to translate the attribute in the update changelog but it still not working.

----
Website:

![p1](https://user-images.githubusercontent.com/49800146/79054153-37df6480-7c4b-11ea-9172-00e71acab835.jpg)


App:

![p2](https://user-images.githubusercontent.com/49800146/79054160-47f74400-7c4b-11ea-9e1f-5fb3679f2b85.jpg)

Woocommerce Multilingual:

![wp](https://user-images.githubusercontent.com/49800146/79054177-74ab5b80-7c4b-11ea-9aef-341813f79385.JPG)

----
Note: I have updated the last Mstore API, I even did it many times in fresh WP installation with latest Fluxstore 1.6.6b.

**Comment by minhcasi** [comment]
Hi, the Multi-Language for Product attribute is not supported via WPML Rest API so that we have moved to the config file - https://tppr.me/RVpSK - it mean you need to update it manually from the app that matches with your website. As this field is quite persisted from the web/app so there are not issues, this approach also helps to speed up the app.
