### ISSUE TITLE
[Fluxstore Pro] -  Huge bug when adding variations in variable product

### ISSUE THREAD

**Issue by Alnaggar94** [inspireui/support#1718]
1. My issue:

When I add different variations to a product (Ex. different price for a particular size,  Different quantity for a particular color  ) It shows error (see screenshots).

2. Screenshots issues:

![n55](https://user-images.githubusercontent.com/49800146/71574673-da3f6600-2afa-11ea-94e4-d81fe40a9683.JPG)

3. Proof of my purchased:

https://imgur.com/a/9TsYcIf

3. Config files (optional)

**Comment by minhcasi** [comment]
@Alnaggar94 - could you share the config files so that we could help for checking - thanks

**Comment by Alnaggar94** [comment]
Config.dart - https://www.dropbox.com/s/175c66mr9ax23gc/config.dart?dl=0

Config.json - https://www.dropbox.com/s/azbbuwflj89ynx1/config.json?dl=0
Config_ar.json - https://www.dropbox.com/s/sted88bbtt1aq15/config_ar.json?dl=0

**Comment by minhcasi** [comment]
@minhtruong315

**Comment by Alnaggar94** [comment]
1.6.1 update: I just tried the new update and the variations gone on all products!?

![m1](https://user-images.githubusercontent.com/49800146/71657576-909c8880-2d51-11ea-9309-0c0f051476ae.JPG)

**Comment by Alnaggar94** [comment]
@minhtruong315 @minhcasi  any update?? this is a main function the app basically unusable with this problem!!

**Comment by minhtruong315** [comment]
Hi @Alnaggar94 replace models/product.dart file like this 
[product.dart.zip](https://github.com/inspireui/support/files/4031021/product.dart.zip)

**Comment by Alnaggar94** [comment]
@minhtruong315  It shows error after replacing the file 

![hhjj](https://user-images.githubusercontent.com/49800146/71916380-da8cd080-318e-11ea-9825-ef983c1b4089.JPG)

**Comment by minhtruong315** [comment]
supported
