### ISSUE TITLE
[ListApp 1.7.4] - Error

### ISSUE THREAD

**Issue by phisakel** [inspireui/support#1719]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
Error 
2. Screenshots issues:
![Simulator Screen Shot - iPhone 11 Pro Max - 2019-12-30 at 11 57 18](https://user-images.githubusercontent.com/4129573/71577201-e24bd580-2afb-11ea-8211-fd5a6db0ac4f.png)

3. Proof of my purchased:

ListApp - Listing Directory mobile app by React NativeRegular LicensePurchase code: a97a950d-a0ae-49b8-9b80-43e21d51540b | ListApp - Listing Directory mobile app by React Native | Regular License | Purchase code: a97a950d-a0ae-49b8-9b80-43e21d51540b |  
-- | -- | -- | -- | --
ListApp - Listing Directory mobile app by React Native
Regular License
Purchase code: a97a950d-a0ae-49b8-9b80-43e21d51540b

3. Config files (optional)

**Comment by minhcasi** [comment]
@phisakel - note with checking, could you share your config file here as well?

**Comment by phisakel** [comment]
{
  "expo": {
    "name": "Modern Talking fans",
    "description": "React Native app for Listing Directory, demo website: http://mylisting.inspireui.com. Download app from \nhttps://shrtm.nu/MOeZ",
    "slug": "listapp-mylisting",
    "privacy": "public",
    "sdkVersion": "35.0.0",
    "platforms": [
      "ios",
      "android"
    ],
    "version": "1.8.1",
    "orientation": "portrait",
    "icon": "assets/icon.png",
    "splash": {
      "image": "assets/splash.png",
      "resizeMode": "cover"
    },
    "ios": {
      "supportsTablet": true,
      "bundleIdentifier": "com.inspireui.listapplisting",
      "infoPlist": {
        "NSLocationWhenInUseUsageDescription": "Your current location will be displayed on the map and used for directions"
      },
      "loadJSInBackgroundExperimental": true,
      "buildNumber": "2"
    },
    "android": {
      "package": "com.inspireui.listapp.mylisting",
      "versionCode": 8,
      "googleServicesFile": "./release/google-services.json"
    },
    "facebookAppId": "1809822172592320",
    "facebookDisplayName": "beoNews",
    "updates": {
      "checkAutomatically": "ON_LOAD",
      "fallbackToCacheTimeout": 0
    }
  }
}

**Comment by minhcasi** [comment]
@phisakel - sorry for late response - wishes you had a great holiday

Could you share the config files from common/appconfig.json and config.js file so that we could help for checking - thank you!

**Comment by phisakel** [comment]
I am on vacation but I created a listapp using the CeBuilder app with the default settings. Have not written any code

**Comment by minhcasi** [comment]
@phisakel  - sorry for the late response - please help to update latest 1.7.5 that fix most of the version of latest Expo version - thank you for your patient
