### ISSUE TITLE
[ Fluxstore WooCommerce - Flutter E-commerce Full App - CodeCanyon Item for Sale Fluxstore WooCommerce - Flutter E-commerce Full App] - 

### ISSUE THREAD

**Issue by nelson243** [inspireui/support#1720]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:

2. Screenshots issues:

3. Proof of my purchased:

3. Config files (optional)

**Comment by nelson243** [comment]
I need help installing Fluxstore. I have a vps and a website fully running with woocommerce. I already installed Android Studio and Flutter what's next is there any pdf documentation as the video don't really help novice like me because more steps are skipped.  I don't know where to start from now
![flux](https://user-images.githubusercontent.com/13100267/71579538-5b97f800-2afd-11ea-932e-6673fa78b6b6.png)

**Comment by minhcasi** [comment]
@nelson243  - pls check this guide for the installing - https://www.youtube.com/watch?v=Q8Q3ywiiV9g&t=433s

**Comment by nelson243** [comment]
So i installed Flutter on android studio but when i tried to run the fluxstore project it's says that the flutter version is not compatible with the flutter version. which flutter version is compatible with fluxstore ?

**Comment by nelson243** [comment]
<img width="519" alt="flutter-versus" src="https://user-images.githubusercontent.com/13100267/71616165-20590000-2bb5-11ea-9fa8-345ecd94a91e.png">
Last time the error was i should put versus 1.10 now it's versus 1.12.13 so what is the best version for last fluxstore ?

**Comment by nelson243** [comment]
<img width="585" alt="flux" src="https://user-images.githubusercontent.com/13100267/71621746-6cb23900-2bd1-11ea-9a26-98d9b6e0dc3b.png">
I installed successfully now i tried to replace fluxstore by my app name and i'm getting this error.
P.S : it's my first time to work on Android Studio

**Comment by nelson243** [comment]
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="net.gracim.gracim">
    
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    
    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="gracim"
        android:icon="@mipmap/launcher_icon">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            
            <meta-data
                android:name="io.flutter.app.android.SplashScreenUntilFirstFrame"
                android:value="true" />
            <meta-data android:name="com.google.android.geo.API_KEY"
                android:value="your-google-api-key-here"/>
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
            <intent-filter>
                <action android:name="FLUTTER_NOTIFICATION_CLICK" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
            <intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.BROWSABLE"/>
                <data android:scheme="http" android:host="www.gracim.net" />

            </intent-filter>
            <intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.BROWSABLE"/>
                <data android:scheme="gracim" android:host="gracim.net" android:pathPrefix=""/>
            </intent-filter>


        </activity>
        <meta-data
            android:name="com.facebook.sdk.ApplicationId"
            android:value="@string/fb_app_id" />
        <meta-data
            android:name="com.facebook.accountkit.ApplicationName"
            android:value="@string/app_name" />
        <meta-data
            android:name="com.facebook.accountkit.ClientToken"
            android:value="@string/ak_client_token" />
        <meta-data
            android:name="com.google.android.geo.API_KEY"
            android:value="@string/api_key"/>
        <meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="@string/admob_api"/>
    </application>
</manifest>

**Comment by nelson243** [comment]
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="net.gracim.gracim">
    
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    
    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="gracim"
        android:icon="@mipmap/launcher_icon">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            
            <meta-data
                android:name="io.flutter.app.android.SplashScreenUntilFirstFrame"
                android:value="true" />
            <meta-data android:name="com.google.android.geo.API_KEY"
                android:value="your-google-api-key-here"/>
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
            <intent-filter>
                <action android:name="FLUTTER_NOTIFICATION_CLICK" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
            <intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.BROWSABLE"/>
                <data android:scheme="http" android:host="www.gracim.net" />

            </intent-filter>
            <intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.BROWSABLE"/>
                <data android:scheme="gracim" android:host="gracim.net" android:pathPrefix=""/>
            </intent-filter>


        </activity>
        <meta-data
            android:name="com.facebook.sdk.ApplicationId"
            android:value="@string/fb_app_id" />
        <meta-data
            android:name="com.facebook.accountkit.ApplicationName"
            android:value="@string/app_name" />
        <meta-data
            android:name="com.facebook.accountkit.ClientToken"
            android:value="@string/ak_client_token" />
        <meta-data
            android:name="com.google.android.geo.API_KEY"
            android:value="@string/api_key"/>
        <meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="@string/admob_api"/>
    </application>
</manifest>

**Comment by nelson243** [comment]
Please check if i made something wrong here trying to change

**Comment by minhcasi** [comment]
@nelson243 - pls try to run "flutter upgrade --force" to update to latest Flutter 1.12 - thank you!

**Comment by minhcasi** [comment]
Also, pls try download the fluxstore v1.6.1 - thank you!

**Comment by nelson243** [comment]
I have the latest version of both flutter and fluxstore. I successfulled run the demo app but when i tried to change data to connect with my site i got the error mentioned i should not the app id?

**Comment by nelson243** [comment]
* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Overlay manifest:package attribute declared at AndroidManifest.xml:2:5-38 value=(com.inspireui.fluxstore)
  	has a different value=(net.gracim.gracim) declared in main manifest at AndroidManifest.xml:2:5-32
  	Suggestion: remove the overlay declaration at AndroidManifest.xml 	and place it in the build.gradle:
  		flavorName {
  			applicationId = "com.inspireui.fluxstore"
  		}
Help me please !

**Comment by minhcasi** [comment]
@nelson243 - pls help to change your own bundle id name base on this guide - https://docs.inspireui.com/fluxstore/customization/#1-app-nameicon-bundle-id

**Comment by nelson243** [comment]
Hello i solved the issue. Now i change the app-icon okay. But the logo and the splashscreen is not changing and also i change the customer key and secret key with my website url but i'm still getting fluxstore data? what to do ? can someone reply ??

**Comment by nelson243** [comment]
<img width="827" alt="fluxs" src="https://user-images.githubusercontent.com/13100267/71825168-8e149880-309b-11ea-8153-fcd50d4ddee9.png">
I changed the package name using the link you gave but now the logo it's still fluxstore and the splashscreen doesn't appear anymore. I replace the default logo and splashscreen with my own in the directory assets/images so why the fluxstore is till coming ? and also why the data from my website is not synced as i already changed the url and the keys as well?? Thanks for your reply

**Comment by nelson243** [comment]
Can you please explain why my website is not synced with the app please ? The api is working fine
Url of my website https://gracim.net/

**Comment by nelson243** [comment]
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
√ Built build\app\outputs\apk\debug\app-debug.apk.
Syncing files to device Android SDK built for x86...
I/flutter ( 4298): http://demo.mstore.io/wp-json/wc/v3/products/categories?lang=en&oauth_consumer_key=ck_b7594bc4391db4b56c635fe6da1072a53ca4535a&oauth_nonce=eulzbrbjbm&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1578389328&oauth_token=&oauth_version=1.0&per_page=100&oauth_signature=wQj9q5VfZBOcZRE4i5T0CX8Vjxo%3D
I/flutter ( 4298): http://demo.mstore.io/wp-json/wc/v3/products?category=26&lang=en&oauth_consumer_key=ck_b7594bc4391db4b56c635fe6da1072a53ca4535a&oauth_nonce=flxaqhswzf&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1578389328&oauth_token=&oauth_version=1.0&status=publish&stockstatus=instock&oauth_signature=ATHdFJIiPA7aqr5KfJbjHwFQfss%3D
I/flutter ( 4298): http://demo.mstore.io/wp-json/wc/v3/products?category=21&lang=en&oauth_consumer_key=ck_b7594bc4391db4b56c635fe6da1072a53ca4535a&oauth_nonce=hbidzlonjl&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1578389328&oauth_token=&oauth_version=1.0&status=publish&stockstatus=instock&oauth_signature=NbtJqR21HqUPz5C5a1HO%2BFchl%2FQ%3D
I/flutter ( 4298): http://demo.mstore.io/wp-json/wc/v3/products?category=29&lang=en&oauth_consumer_key=ck_b7594bc4391db4b56c635fe6da1072a53ca4535a&oauth_nonce=egpviivjvz&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1578389328&oauth_token=&oauth_version=1.0&per_page=20&status=publish&stockstatus=instock&oauth_signature=n5QZpPLXCjI6fNgb36SZxXpY%2FY0%3D
I/flutter ( 4298): 19
I/flutter ( 4298): products?status=publish&lang=en&per_page=10&page=1&category=211
I/flutter ( 4298): http://demo.mstore.io/wp-json/wc/v3/products?category=211&lang=en&oauth_consumer_key=ck_b7594bc4391db4b56c635fe6da1072a53ca4535a&oauth_nonce=vgljppltpq&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1578392033&oauth_token=&oauth_version=1.0&page=1&per_page=10&status=publish&oauth_signature=%2B8nuFQUjqx%2B%2B7P%2Fx0%2BmL8p4HNog%3D
I/flutter ( 4298): item id: 9361
I/flutter ( 4298): products?status=publish&lang=en&per_page=10&page=1&category=0
I/flutter ( 4298): http://demo.mstore.io/wp-json/wc/v3/products?category=0&lang=en&oauth_consumer_key=ck_b7594bc4391db4b56c635fe6da1072a53ca4535a&oauth_nonce=sckepdskdh&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1578392042&oauth_token=&oauth_version=1.0&page=1&per_page=10&status=publish&oauth_signature=59SyLJQGIW64POYGL5U05oYHDKs%3D
I/flutter ( 4298): http://demo.mstore.io/wp-json/wc/v3/coupons?oauth_consumer_key=ck_b7594bc4391db4b56c635fe6da1072a53ca4535a&oauth_nonce=tilgbaigkr&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1578392098&oauth_token=&oauth_version=1.0&oauth_signature=LTsWESYHJjl6obTA6Ggfpoz0AbA%3D
I/flutter ( 4298): {id: 12433, code: 10d, amount: 10.00, date_created: 2018-03-28T15:36:17, date_created_gmt: 2018-03-28T08:36:17, date_modified: 2019-11-15T18:57:18, date_modified_gmt: 2019-11-15T11:57:18, discount_type: fixed_product, description: Hello, this is your coupons message, date_expires: null, date_expires_gmt: null, usage_count: 9, individual_use: false, product_ids: [], excluded_product_ids: [], usage_limit: null, usage_limit_per_user: null, limit_usage_to_x_items: null, free_shipping: false, product_categories: [], excluded_product_categories: [], exclude_sale_items: false, minimum_amount: 200.00, maximum_amount: 0.00, email_restrictions: [], used_by: [minhcasi@gmail.com, 74, 5208, 5208, 5208, 5208, 5208, 5208, 5208], meta_data: [{id: 103376, key: _vc_post_settings, value: {vc_grid_id: []}}, {id: 103397, key: slide_template, value: default}], _links: {self: [{href: http://demo.mstore.io/wp-json/wc/v3/coupons/12433}], collection: [{href: http://demo.mstore.io/wp-json/wc/v3/coupons}]}}
I/flutter ( 4298): {id: 11864, code: test, amount: 30.00, date_created: 2017-11-07T06:46:28, date_created_gmt: 2017-11-06T23:46:28, date_modified: 2019-12-03T06:40:52, date_modified_gmt: 2019-12-02T23:40:52, discount_type: percent, description: , date_expires: null, date_expires_gmt: null, usage_count: 22, individual_use: false, product_ids: [], excluded_product_ids: [], usage_limit: null, usage_limit_per_user: null, limit_usage_to_x_items: null, free_shipping: false, product_categories: [], excluded_product_categories: [], exclude_sale_items: false, minimum_amount: 0.00, maximum_amount: 0.00, email_restrictions: [], used_by: [393, 1547, 1621, 1676, 1247, 2429, 2494, 4952, 5159, 393, 393, 393, 393, 393, 393, 393, 393, 5846, 5846, 5846, 5860, 5860], meta_data: [{id: 79884, key: _vc_post_settings, value: {vc_grid_id: []}}, {id: 79905, key: slide_template, value: default}], _links: {self: [{href: http://demo.mstore.io/wp-json/wc/v3/coupons/11864}], collection: [{href: http://demo.mstore.io/wp-json/wc/v3/coupons}]}}
I/flutter ( 4298): {id: 11843, code: blackf, amount: 40.00, date_created: 2017-11-04T10:39:10, date_created_gmt: 2017-11-04T03:39:10, date_modified: 2017-11-20T21:23:50, date_modified_gmt: 2017-11-20T14:23:50, discount_type: percent, description: Black friday event, date_expires: null, date_expires_gmt: null, usage_count: 0, individual_use: false, product_ids: [], excluded_product_ids: [], usage_limit: null, usage_limit_per_user: null, limit_usage_to_x_items: null, free_shipping: true, product_categories: [], excluded_product_categories: [], exclude_sale_items: false, minimum_amount: 0.00, maximum_amount: 0.00, email_restrictions: [], used_by: [], meta_data: [{id: 79024, key: _vc_post_settings, value: {vc_grid_id: []}}, {id: 79045, key: slide_template, value: default}], _links: {self: [{href: http://demo.mstore.io/wp-json/wc/v3/coupons/11843}], collection: [{href: http://demo.mstore.io/wp-json/wc/v3/coupons}]}}
I/flutter ( 4298): {id: 10021, code: halfprice, amount: 50.00, date_created: 2016-11-12T10:44:40, date_created_gmt: 2016-11-12T03:44:40, date_modified: 2016-11-12T10:44:40, date_modified_gmt: 2016-11-12T03:44:40, discount_type: percent, description: , date_expires: null, date_expires_gmt: null, usage_count: 0, individual_use: true, product_ids: [], excluded_product_ids: [], usage_limit: null, usage_limit_per_user: 1, limit_usage_to_x_items: null, free_shipping: false, product_categories: [], excluded_product_categories: [], exclude_sale_items: false, minimum_amount: 0.00, maximum_amount: 0.00, email_restrictions: [], used_by: [], meta_data: [{id: 12692, key: _vc_post_settings, value: {vc_grid_id: []}}, {id: 12711, key: slide_template, value: default}], _links: {self: [{href: http://demo.mstore.io/wp-json/wc/v3/coupons/10021}], collection: [{href: http://demo.mstore.io/wp-json/wc/v3/coupons}]}}
I/flutter ( 4298): products?status=publish&lang=en&per_page=10&page=1&category=0
I/flutter ( 4298): http://demo.mstore.io/wp-json/wc/v3/products?category=0&lang=en&oauth_consumer_key=ck_b7594bc4391db4b56c635fe6da1072a53ca4535a&oauth_nonce=sjvookxtvn&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1578392140&oauth_token=&oauth_version=1.0&page=1&per_page=10&status=publish&oauth_signature=qKhqwAXCOuiYNp%2Bq3Z%2F0g%2FPN%2BZA%3D
I/flutter ( 4298): products?status=publish&lang=en&per_page=10&page=1&category=0
I/flutter ( 4298): http://demo.mstore.io/wp-json/wc/v3/products?category=0&lang=en&oauth_consumer_key=ck_b7594bc4391db4b56c635fe6da1072a53ca4535a&oauth_nonce=hrgezizhtq&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1578392158&oauth_token=&oauth_version=1.0&page=1&per_page=10&status=publish&oauth_signature=NQV7XPV1syi97cXvZ1uPzJG%2FjMs%3D
I/flutter ( 4298): http://demo.mstore.io/wp-json/wc/v3/products/categories?lang=en&oauth_consumer_key=ck_b7594bc4391db4b56c635fe6da1072a53ca4535a&oauth_nonce=mxzhereitz&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1578392182&oauth_token=&oauth_version=1.0&per_page=100&oauth_signature=Ix6hHI%2FGnOtiLEsCRbZBnNgkF4c%3D
I/flutter ( 4298): http://demo.mstore.io/wp-json/wc/v3/products?category=26&lang=en&oauth_consumer_key=ck_b7594bc4391db4b56c635fe6da1072a53ca4535a&oauth_nonce=tewlbynxfk&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1578392182&oauth_token=&oauth_version=1.0&status=publish&stockstatus=instock&oauth_signature=5MhxhT%2Fkgc%2FLeC9DZxwptNrzy4s%3D
I/flutter ( 4298): http://demo.mstore.io/wp-json/wc/v3/products?category=21&lang=en&oauth_consumer_key=ck_b7594bc4391db4b56c635fe6da1072a53ca4535a&oauth_nonce=wbzpximdyh&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1578392182&oauth_token=&oauth_version=1.0&status=publish&stockstatus=instock&oauth_signature=ROcQ7LOxa2%2FwXMBlC6yOPSy0bJs%3D
I/flutter ( 4298): http://demo.mstore.io/wp-json/wc/v3/products?category=29&lang=en&oauth_consumer_key=ck_b7594bc4391db4b56c635fe6da1072a53ca4535a&oauth_nonce=cmnaupopxu&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1578392182&oauth_token=&oauth_version=1.0&per_page=20&status=publish&stockstatus=instock&oauth_signature=%2BMmlmjgmGYb8DfJe5uJU659K6hI%3D
I/flutter ( 4298): 19

Why it's still syncing to demo.mstore.io

**Comment by nelson243** [comment]
'package:flutter/src/widgets/title.dart': Failed assertion: line 24 pos 15: 'color != null && color.alpha == 0xFF': is not true. 
I'm getting this error when building the app. What's the fix ?

**Comment by minhcasi** [comment]
@nelson243 - could you zip the source and send back us for checking - support@inspireui.com

**Comment by nelson243** [comment]
Thanks Email sent to support with my source code

**Comment by minhcasi** [comment]
Fix on the latest 1.6.3 - let us know if you have any issues - thank you!
