### ISSUE TITLE
[FluxNews] - Login Error

### ISSUE THREAD

**Issue by amitash** [inspireui/support#1722]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: 
I/flutter ( 5279): NoSuchMethodError: The method 'loginFacebook' was called on null.
I/flutter ( 5279): Receiver: null
I/flutter ( 5279): Tried calling: loginFacebook(token: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")

I/flutter ( 5279): login err NoSuchMethodError: The method 'login' was called on null.
I/flutter ( 5279): Receiver: null
I/flutter ( 5279): Tried calling: login(password: "xxxxxxxxxxx", username: "xxxxxxxx")

2. Screenshots issues:

3. Proof of my purchased:
![Capture](https://user-images.githubusercontent.com/1684664/71587933-f6093300-2b1f-11ea-9378-bf9d62d34310.PNG)

3. Config files (optional)

**Comment by minhcasi** [comment]
@dttrung26 - pls help to provide some solution

**Comment by amitash** [comment]
I would like to add to this that comments also do not work.

It looks like everything that depends on UserModel does not work. I noticed that the code which contains Provider.of<UserModel> does not work.

════════ Exception caught by gesture ═════════════════════════════════
The following NoSuchMethodError was thrown while handling a gesture:
The getter 'name' was called on null.
Receiver: null
Tried calling: name

When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      _CommentInputState.sendComment (package:fromtbot/widgets/blog/comments/comment_text_field.dart:24:33)
#2      _CommentInputState.build.<anonymous closure> (package:fromtbot/widgets/blog/comments/comment_text_field.dart:71:15)
#3      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#4      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
...
Handler: "onTap"
Recognizer: TapGestureRecognizer#1765e
  debugOwner: GestureDetector
  state: ready
  won arena
  finalPosition: Offset(372.6, 444.2)
  finalLocalPosition: Offset(20.1, 13.4)
  button: 1
  sent tap down
═══════════════════════════════════════════════════════════════

**Comment by amitash** [comment]
Still struggling with this issue. Could this be due to my WordPress or server setup? MStore plugin? I am getting helpless.

**Comment by amitash** [comment]
This also happens in new v1.2, no changes to source. Straight from Gitlab. Does the login work for your guys?

**Comment by minhcasi** [comment]
@amitash - let us have a check and let you know - thank you for your patient

**Comment by amitash** [comment]
I think it is because of `services/index.dart`, the following code
`class Services implements BaseServices {
  BaseServices serviceApi = WooCommerce();

  static final Services _instance = Services._internal(); // directly declared services here

  factory Services() => _instance;

  Services._internal();

//  void setAppConfig(appConfig) {
//    switch (appConfig["type"]) {
//      default:
//        WooCommerce().appConfig(appConfig);
//        serviceApi = WooCommerce();
//    }
//  }`

The `void setAppConfig` returns null, so I just commented it out and directly declared `static final Services _instance = Services._internal();`

And also in `services/woo_commerce.dart`, void appConfig url returns null. So I directly declared my url.

`Map<String, dynamic> configCache;
  WooCommerceAPI wcApi;
//  String isSecure;
//  String url;
  String isSecure = '';
  String url = 'https://mydomain.com';
  List<Category> categories = [];

//  void appConfig(appConfig) {
//    wcApi = WooCommerceAPI(appConfig["url"], appConfig["consumerKey"],
//        appConfig["consumerSecret"]);
//    isSecure = appConfig["url"].indexOf('https') != -1 ? '' : '&insecure=cool';
//    url = appConfig["url"];
//    print(url);
//  }
`
Then, login works. Why do you think appConfig returns null??

**Comment by amitash** [comment]
So??

**Comment by minhcasi** [comment]
@amitash - there is some recent update of the Plugins API that break the login features, please bear with us for this issue as we will upgrade the mstore-api and remove dependency on json-api plugins - we will keep the solution update on next couple of day - thank you!

**Comment by minhcasi** [comment]
fix login/registation on latest 1.2.1 - thank you!
