### ISSUE TITLE
flux store apple reject my app because of sign in apple 

### ISSUE THREAD

**Issue by nizarweb77** [inspireui/support#1723]
i got this message form apple 
From: Apple
4. 8 Design: Sign in with Apple
Thank you for resubmitting your application. Upon further review, we found the following issue:

Guideline 4.8 - Design - Sign in with Apple

We noticed that your app uses a third-party login service but does not offer Sign in with Apple.

Next Steps

To resolve this issue, please revise your app to offer Sign in with Apple as an equivalent login option.
*i see that flux store v 1.6.0 have sign in apple option but how i can integrate the option code in my old version v1.5.8*
![{0F68468F-94AF-4502-B851-5EF028CDDBF9} png](https://user-images.githubusercontent.com/57265062/71602099-d93c2200-2b56-11ea-8e47-5db47b2a3ffd.jpg)

Purchase codes
****Authors may ask you for a purchase code to verify that you’ve purchased this item.

7347f2d1-d5aa-4bc0-b6f3-0e2cf237c3de - 1 Nov 2019 REGULAR LICENSE****

**Comment by minhcasi** [comment]
@nizarweb77 - we don't have the auto solution for upgrading new version so far, the best way is using the tools like SourceTree and compares the file changed - https://www.sourcetreeapp.com/ -  thank you
