### ISSUE TITLE
[MStore Pro v3.9.6] - Android Built successfully but freezed with msg "Unable to dispatch touch to JS as the catalyst instance has not been attached"   

### ISSUE THREAD

**Issue by khiemhuynh95** [inspireui/support#1724]
1. My issue:
 I downloaded the latest version v3.9.6, then tried to build on Android Studio. It runs but froze at Splash screen with error msg: "Unable to dispatch touch to JS as the catalyst instance has not been." The same message appears if you touch on it. I included the screenshot. Plus: I made no changes to the project folder. OS: Windows 10
2. Screenshots issues:
https://github.com/khiemhuynh95/mstore-issues/blob/master/Untitled.png
3. Proof of my purchased:

3. Config files (optional)

**Comment by minhcasi** [comment]
@khiemhuynh95  - note with checking - thanks

**Comment by minhcasi** [comment]
moved to #1683
