### ISSUE TITLE
[FluxStore 1.6.0] -  I can't open the app

### ISSUE THREAD

**Issue by luisalexhg** [inspireui/support#1725]
Product purchased: https://bit.ly/2lPLMGB

ERROR: I can't open the app on simulator...

Before I updated to 1.6.0 , I Continue having errors with shipping method selected. I registered it on  https://github.com/inspireui/support/issues/1071 

![Captura de Pantalla 2019-12-30 a la(s) 21 28 14](https://user-images.githubusercontent.com/28818275/71607952-7f822a80-2b4b-11ea-8526-5d5dca866a0e.png)

**Comment by minhcasi** [comment]
@luisalexhg - did you try to run "flutter clean" - pls make sure to run "flutter upgrade" as the latest 1.6 is required flutter 1.2.x - thanks

**Comment by luisalexhg** [comment]
![Captura de Pantalla 2019-12-31 a la(s) 09 33 55](https://user-images.githubusercontent.com/28818275/71624466-bc343d00-2bb0-11ea-828e-cb3035726efb.png)

check ticket and open it again pls #1071

**Comment by minhcasi** [comment]
@luisalexhg - sorry for missing on this issue, we have a similar issue that related to the Pod library, pls check this solution
- go to ios remove the Pods folder, Podfile and Podfile.lock
- run: pod repo update
- run: pod install

Then go to Android Studio to run the project again, let us know your checking

**Comment by luisalexhg** [comment]
I updated the latest version 1.6.1 and I still have errors to run the application, every time they perform an update something has to fail, it is uncomfortable to be waiting, days or weeks to correct it again, and for months I asked them to correct the erorr of ticket #1071, which already deleted it, which is pity, I am very disgusted with this product, what bothers me most is that I request that they open the ticket again and they ignored and deleted it, I bought 2 of their Mstore and FluxStore solutions, and I am sorry that this product does not work for me.

The ticket that I would eliminate was where months ago I was requesting that the error of the shipping method that failed to calculate the total be resolved, but they were not interested and deleted.

![Captura de Pantalla 2020-01-09 a la(s) 13 07 21](https://user-images.githubusercontent.com/28818275/72092769-03bd7600-32e1-11ea-86c8-1e5c1e0d06e0.png)

![Captura de Pantalla 2020-01-09 a la(s) 12 58 45](https://user-images.githubusercontent.com/28818275/72092197-d4f2d000-32df-11ea-94f4-f854465cb5ba.png)

Sincerely it is very annoying to have to wait a long time for an update and that the errors are not solved, it does not work as the product mentions, I bought the product in October and so far I can not get the application in its 100% functionality, they are almost 4 months but I can not do anything, it is money to the water, I will have to request a refund since they are not fulfilling what they are selling ...

I want my money back!

**Comment by minhcasi** [comment]
@luisalexhg - you can submit this link https://help.market.envato.com/hc/en-us/articles/202821460-Can-I-Get-A-Refund- - thanks

**Comment by luisalexhg** [comment]
@minhcasi - I just sent the request.
