### ISSUE TITLE
[Fluxstore] - Checkout  

### ISSUE THREAD

**Issue by qassam123** [inspireui/support#1726]
---------

1. My issue: When confirm the checkout, it showing an error message and not getting the success page is says "connection closed before full header recived"
. Screenshots issues: https://imgur.com/b08vIYS

3. Proof of my purchased: https://imgur.com/ZZNp1ub

3. Config files (optional)

**Comment by minhcasi** [comment]
@qassam123 - note with improvement

@vumanhsn97 - pls try to hide the message on this case

**Comment by qassam123** [comment]
to make it Clear the order sent to woo commerce and it appear in orders .
but the app dosent count it as order 
and this is a screenshot of the error in code : https://imgur.com/ETTt7yZ

**Comment by vumanhsn97** [comment]
@qassam123 Can you share your video record?

**Comment by qassam123** [comment]
Vedio record : https://youtu.be/62Bvxgw4gAs
android pie 28 api level emulator 
and i've tested it on real device s10+ pie and its the same issue

**Comment by qassam123** [comment]
the issue was from the hosting !! 
Closed !
