### ISSUE TITLE
[FLUXSTORE] - Razorpay not working

### ISSUE THREAD

**Issue by shreyas-shriyan** [inspireui/support#1727]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: App comes again to the payment page after completing payment with razorpay. Ihave attached my config files

2. Screenshots issues:

3. Proof of my purchased:
<img width="1178" alt="Screenshot at Dec 31 16-32-46" src="https://user-images.githubusercontent.com/51715896/71619753-e7884d80-2beb-11ea-84b9-3634b7cce639.png">

3. Config files (optional)
https://github.com/shreyas-shriyan/pariconfig

**Comment by UTimung** [comment]
follow my ticket #1541
they already fixed the issue

**Comment by minhcasi** [comment]
@shreyas-shriyan - pls download the latest 1.6.1 for fixing - thanks
