### ISSUE TITLE
[mstore Pro] - I cant register new users within the app and the thumbnails are not shown

### ISSUE THREAD

**Issue by khalidsharif** [inspireui/support#1728]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
 I cant register new users within the app and the thumbnails are not shown
2. Screenshots issues:
https://ibb.co/1vV07kk
https://ibb.co/w7BhMCr
https://ibb.co/k61ZnJP
3. Proof of my purchased:
https://ibb.co/0BHYGhf
3. Config files (optional)

**Comment by khalidsharif** [comment]
The thumbnails issues resolved by regenerating them. Now I need to resolve the registration issue.
Why I cannot register from the App

**Comment by minhcasi** [comment]
@khalidsharif - could you use the latest version + update mstore-api to latest - thanks

**Comment by khalidsharif** [comment]
I found the answer here:
https://github.com/inspireui/support/issues/1645#issuecomment-568427421

thanks

**Comment by minhcasi** [comment]
@khalidsharif - thank you!

**Comment by Tayeb-Ali** [comment]
how you fix it >
with me signup button not showing up..?

**Comment by Tayeb-Ali** [comment]
> @khalidsharif - thank you!

how you fix it >
with me signup button not showing up..?
