### ISSUE TITLE
fluxstore mv type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'String'

### ISSUE THREAD

**Issue by yassiney120** [inspireui/support#1733]
hi , 
---------

1. My issue:
when i change template of home screen i got this error
type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'String'
2. Screenshots issues:
https://ibb.co/vZ8bLtY
3. Proof of my purchased:
https://ibb.co/XsskN38
3. Config files (optional)

**Comment by incepio-flutter** [comment]
@yassiney120  see if you have this variable declared in widgets/home/vertical.dart below the build method if it isn't declared then paste this     

> final locale = Provider.of<AppModel>(context).locale; remember to import required file 
 or replace this file will hopefully solve the problem > widgets/home/vertical.dart
[vertical.dart.zip](https://github.com/inspireui/support/files/4013889/vertical.dart.zip)

**Comment by yassiney120** [comment]
thank you for your reply but problem was not solved can i send you my teamviewer

**Comment by yassiney120** [comment]
thank you probleme solved also in lib/common/config.json 

"VerticalLayout":  is missing from template n 14

  "VerticalLayout": {
    "layout": "default",
    "name": {
      "en": "Recent Collections",
      "ab": "مجموعات الرجل",
      "vi": "Bộ sưu tập gần "
    }
  },

**Comment by yassiney120** [comment]
Thank you but still not working can i give you my teamviewer to fix it


Best regards

Le mer. 1 janv. 2020 à 12:24, incepio-flutter <notifications@github.com> a
écrit :

**Comment by yassiney120** [comment]
thank you problem solved
