### ISSUE TITLE
[{code: rest_forbidden, message: Sorry, you are not allowed to do that., data: {status: 401}}]

### ISSUE THREAD

**Issue by VM8198** [inspireui/support#1734]
I am getting this error in blogs images

in ````models/blog.dart````
```
if (imageFeature == null) {
      var imgMedia = json['_embedded']['wp:featuredmedia'];
      if (imgMedia != null &&
          imgMedia[0]['media_details']["sizes"]["large"] != null) {
        imageFeature =
            imgMedia[0]['media_details']["sizes"]["large"]['source_url'];
      }
    }

```
The error is lying here because i am able to get the blogs but the images of blogs are not displaying..
I got this error after logging ````imgMedia```` in the console

````[{code: rest_forbidden, message: Sorry, you are not allowed to do that., data: {status: 401}}]````

**Comment by minhcasi** [comment]
Hi, could you share your config file so that we could help with checking?

Alos, could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads  it's used to verify your proof of purchase? sorry for any inconvenience - Thank you!
