### ISSUE TITLE
Flux Store M2 - 1-Shipping Method not showing up (Log shows me that the Http request to get Shipping Methods is returning "[ ]") 

### ISSUE THREAD

**Issue by Usman1493** [inspireui/support#1735]
https://vimeo.com/user87541308/review/382269093/33910e8fba

Watch this video.... 

Please note that, This happens, when an order is placed for the second time with the same email...

**Comment by minhcasi** [comment]
@Usman1493 - could you share the video as public - we could not see it https://tppr.me/Clto7

**Comment by Usman1493** [comment]
https://vimeo.com/382269093

Here it is...

**Comment by Usman1493** [comment]
Any progress on this?

**Comment by minhcasi** [comment]
@Usman1493 - could you attache the config files here for further investigating, could we check if you are using latest Fluxstore 1.6.x

@minhtruong315 - pls help for investigating

**Comment by Usman1493** [comment]
[config.zip](https://github.com/inspireui/support/files/4025453/config.zip)

Here is the latest config.dart file..
Yes, we are using the latest version of flux store..

**Comment by minhtruong315** [comment]
Hi @Usman1493 I see you're using old source code. Please update the latest version on codecanyon then try again. I checked your config in my end. it's working well. Thanks
![Simulator Screen Shot - iPhone 11 - 2020-01-07 at 09 19 11](https://user-images.githubusercontent.com/10402500/71863309-0aa48700-312f-11ea-8c12-a257affce636.png)
