### ISSUE TITLE
[Mstore Pro 3.9.7] - How to setup Firebase SMS login & Apple Login

### ISSUE THREAD

**Issue by Riyashanke** [inspireui/support#1737]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------
I have updated the latest in Mstore Pro 3.9.7. 
How to setup Firebase SMS login & Apple Login. I have checked the documents there’s no topic regarding this two module  Kindly guide me sir. 

Proof of purchase

![](https://user-images.githubusercontent.com/56667597/67098771-64557f00-f1da-11e9-9ed9-aa6ab62606ee.png)

**Comment by minhcasi** [comment]
@minhtruong315 - please help for checking

**Comment by minhtruong315** [comment]
@Riyashanke add my skype: minhtruong315
I will help u check it via teamviewer. Thanks

**Comment by minhtruong315** [comment]
supported
