### ISSUE TITLE
[fluxstore 1.6.0] - ITEM DISCOUNT ERROR & CART PRICE ERROR

### ISSUE THREAD

**Issue by rioadetya** [inspireui/support#1739]
how come..? you've missed the important things..
please fix it asap..

1. My issue:
- item with discount = show the same price between the discount price and the regular price
- my cart = Price does not appear ( 0 )

2. Screenshots issues:
http://prntscr.com/qi9smd - show the same price between the discount price and the regular price
http://prntscr.com/qi9u9f - Item Price does not appear ( 0 )

3. Proof of my purchased:
http://prntscr.com/qi9w8f
3. Config files (optional)
config.json
http://prntscr.com/qi9s9i

**Comment by minhcasi** [comment]
@rioadetya - note with checking - thank you!

**Comment by rioadetya** [comment]
no update?

**Comment by vumanhsn97** [comment]
@rioadetya Can you share your config.dart file?

**Comment by rioadetya** [comment]
https://pastebin.com/4YAg3Zyh

please don't waste time

**Comment by vumanhsn97** [comment]
@rioadetya This is not config.dart file! Please send again, like it https://tppr.me/iGhxo

**Comment by rioadetya** [comment]
sorry wrong url. 
https://pastebin.com/GsdcwWXD

**Comment by vumanhsn97** [comment]
@rioadetya 
- Replace code in lib/widgets/cart_item.dart look like https://tppr.me/CGN2r to fix my cart
- Replace file in lib/widgets/product/product_card_view.dart and lib/common/tools.dart to 
[Archive.zip](https://github.com/inspireui/support/files/4024956/Archive.zip)

**Comment by rioadetya** [comment]
tools.dart
http://prntscr.com/qk9bap

what should i do?

**Comment by rioadetya** [comment]
i just founded a new problem.
when item discount added to cart. item chart show the regular price not discount price

pls see my screenshot
product lists - https://prnt.sc/qk9s9p
mycart - https://prnt.sc/qk9sh8 (show regular price. it must be show discount price)

**Comment by vumanhsn97** [comment]
@rioadetya can you upload screenshot product detail?

**Comment by rioadetya** [comment]
product detail - http://prntscr.com/qkcidy
product lists - https://prnt.sc/qkchrc

**Comment by rioadetya** [comment]
no update?

**Comment by vumanhsn97** [comment]
@rioadetya Update in next version or you can change code in
- lib/common/tools.dart to https://tppr.me/cpHCV
- lib/models/cart.dart to https://tppr.me/cv18s
- lib/widgets/cart_item.dart to https://tppr.me/j2RWt

**Comment by rioadetya** [comment]
it works now. thanks.
