### ISSUE TITLE
[Listapp] myListing New Version

### ISSUE THREAD

**Issue by reconshield** [inspireui/support#174]
Purchase code: 23ee6c94-1eb8-4ffd-842f-7600d97f41d0 

Listapp is not compatible with latest vesion of MyListing. We cant see thumbnails images and listing description correctly. all gone blank..waiting for new update. can tell us when we can get it? thanks!

**Comment by thangvo9x** [comment]
Hi. You must set a featured image. or follow by steps
1. install plugin Regenerate Thumbnails 
2. update plugin ListApp Mobile Manager
3. Run generate all thumbnail.
We've optimized for loading all images on the app
Thanks.

**Comment by reconshield** [comment]
i did thumbnails plugins..but its still same.. and cant see listing description too
![simulator screen shot - iphone x - 2019-01-10 at 10 38 34](https://user-images.githubusercontent.com/25501496/50942571-15005680-14c4-11e9-9f2d-adae44b15fd1.png)
![Uploading Simulator Screen Shot - iPhone X - 2019-01-10 at 10.38.43.png…]()

**Comment by reconshield** [comment]
![simulator screen shot - iphone x - 2019-01-10 at 10 38 43](https://user-images.githubusercontent.com/25501496/50942573-1762b080-14c4-11e9-95bb-d47354e5eb01.png)

**Comment by reconshield** [comment]
i just download fresh code from codecanyon and run it..without change config file..its show same in demo version..
![simulator screen shot - iphone x - 2019-01-10 at 10 38 34](https://user-images.githubusercontent.com/25501496/50943277-c0120f80-14c6-11e9-98cf-dbebbe860700.png)

**Comment by thangvo9x** [comment]
Hi. Kindly dont' define issues such as "not compatible"... We've update plugin ListApp Mobile Manager(LMM) for integrateing with new version ListApp 1.6, This could be images not displayed. 
v1.6 preparing to release
Thanks

**Comment by reconshield** [comment]
ok....hoping new version release soon..thanks
