### ISSUE TITLE
[FLUXSTORE MV] - HAVE SOME PROBLEMS.

### ISSUE THREAD

**Issue by antixirus** [inspireui/support#1740]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
I have some problems
- I have entered the Google Maps API Key, but Maps does not appear.

- On the cart menu, when I swipe left, a checkout menu appears, without any items being added to the cart.

- I have changed the background photo in the application, but it has not changed.

- I uploaded the item using a Vendor account, but the price did not appear.

- Accounts are always logged out, and must be re-entered if they are not used more than 1 day

2. Screenshots issues:
![gambar](https://user-images.githubusercontent.com/57300649/71649728-9ab78a80-2d43-11ea-8ead-094604e1ce30.png)

3. Proof of my purchased:
![gambar](https://user-images.githubusercontent.com/57300649/71649734-a3a85c00-2d43-11ea-964e-794c4bca611c.png)

3. Config files (optional)

I hope Mr. Nguyễn Minh Trường and then Mr. Vu Van Manh can help me to solve this problems..

**Comment by minhcasi** [comment]
@antixirus - thank you for the detailed feedback, we will have a check and let you know.

Appreciated for your help with the rating ❤️

**Comment by antixirus** [comment]
@minhcasi Hehe, oke sir, Oke sir, I can't wait for the Update sir..
