### ISSUE TITLE
[Fluxstore] - 1.6.1 issue

### ISSUE THREAD

**Issue by Senior-Gamal** [inspireui/support#1742]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

-. My issue:
1- issue in the cart is not apper in the product page
2 -cant select the defult shipping from code ( "ZoneIdShipping":) and hide other shipping zone
3 -problem in the arabic language in the home screen 
4 -how can to change the about us page url
5 - how to use Web beta version

-. Proof of my purchased:
![000000](https://user-images.githubusercontent.com/27568540/71651886-b6159c00-2d29-11ea-9892-41ad518dc615.jpeg)

**Comment by minhcasi** [comment]
@Senior-Gamal - could you make sure it is using latest Fluxstore app, v1.6.1 ?

Please share your config files as well - thank you!

**Comment by Alnaggar94** [comment]
same issue "1- issue in the cart does not appear in the product page"

1.6.0 it works fine:

![cart2](https://user-images.githubusercontent.com/49800146/71716284-3cfb6f00-2e25-11ea-8ef2-66425370d5fc.JPG)


1.6.1 not showing the cart : 

![cart4](https://user-images.githubusercontent.com/49800146/71716382-9d8aac00-2e25-11ea-8136-6786cccbc46a.JPG)

**Comment by Senior-Gamal** [comment]
> @Senior-Gamal - could you make sure it is using latest Fluxstore app, v1.6.1 ?
> 
> Please share your config files as well - thank you!

yes iam sure is 1.6.1 and i use the config.dart default + add "ZoneIdShipping": only

**Comment by Senior-Gamal** [comment]
any replay ?

**Comment by minhcasi** [comment]
@Senior-Gamal - pls help to check this solution from https://github.com/inspireui/support/issues/1759

**Comment by Senior-Gamal** [comment]
not fixed after comment the line 
can you send the simpletype.dart after edit and work
and another question
2 -cant select the defult shipping from code ( "ZoneIdShipping":) and hide other shipping zone
3 -problem in the arabic language in the home screen
4 -how can to change the about us page url
5 - how to use Web beta version

**Comment by Senior-Gamal** [comment]
and how to change fstore from iphone in fb login ?
![fstore fb](https://user-images.githubusercontent.com/27568540/71928632-94d90380-31a0-11ea-82ee-5575fd692cda.jpg)

**Comment by minhcasi** [comment]
@Senior-Gamal - you can change it from info.plist by open the XCode - https://tppr.me/TbDN8

**Comment by Senior-Gamal** [comment]
> not fixed after comment the line
> can you send the simpletype.dart after edit and work
> and another question
> 2 -cant select the defult shipping from code ( "ZoneIdShipping":) and hide other shipping zone
> 3 -problem in the arabic language in the home screen
> 4 -how can to change the about us page url
> 5 - how to use Web beta version

and this issues ?

**Comment by minhcasi** [comment]
moved to #1823
