### ISSUE TITLE
[FluxStore MV] - Xcode couldn't find any iOS App Development provisioning profiles matching

### ISSUE THREAD

**Issue by saifmuhtar** [inspireui/support#1744]
saifstudio@Saifs-MacBook-Air flutter-mstore % flutter clean
Cleaning Xcode workspace...                                        13.5s
Deleting build...                                                    3ms
Deleting .dart_tool...                                               6ms
saifstudio@Saifs-MacBook-Air flutter-mstore % flutter build ios
Building com.inspireui.mstore.flutter for device (ios-release)...
 
Automatically signing iOS for device deployment using specified development team in Xcode project: S9RPAM8224
 
Running pod install...                                             15.6s
Running Xcode build...                                                  
                                                   
Xcode build done.                                           20.5s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    note: Using new build system
    note: Planning build
    note: Constructing build description
    error: No profiles for 'com.inspireui.mstore.flutter' were found: Xcode couldn't find any iOS App Development provisioning profiles matching
    'com.inspireui.mstore.flutter'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to
    xcodebuild. (in target 'Runner' from project 'Runner')

Encountered error while building for device.
saifstudio@Saifs-MacBook-Air flutter-mstore % flutter clean
Cleaning Xcode workspace...                                         9.9s
Deleting build...                                                    1ms
saifstudio@Saifs-MacBook-Air flutter-mstore % flutter build ios
Building com.inspireui.mstore.flutter for device (ios-release)...
 
Automatically signing iOS for device deployment using specified development team in Xcode project: S9RPAM8224
 
Running pod install...                                             15.0s
Running Xcode build...                                                  
                                                   
Xcode build done.                                           19.9s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    note: Using new build system
    note: Planning build
    note: Constructing build description
    error: No profiles for 'com.inspireui.mstore.flutter' were found: Xcode couldn't find any iOS App Development provisioning profiles matching
    'com.inspireui.mstore.flutter'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to
    xcodebuild. (in target 'Runner' from project 'Runner')

Encountered error while building for device.
saifstudio@Saifs-MacBook-Air flutter-mstore % 

![Screenshot 2020-01-02 at 2 45 57 PM](https://user-images.githubusercontent.com/34681804/71654809-a66c7680-2d6e-11ea-8e3f-666a19df01de.png)

This is my licence:
![Screenshot 2019-12-24 at 6 00 42 PM](https://user-images.githubusercontent.com/34681804/71654822-b71cec80-2d6e-11ea-8433-74ac001129a6.png)

**Comment by saifmuhtar** [comment]
@minhcasi 
I got error when I try to build ios.
Please have a lot on this issue.
Thank you.

**Comment by saifmuhtar** [comment]
@minhcasi 
I found a solution for this issue.
I use this command to create a key:

keytool -genkey -v -keystore flutter_release_apk.jks -alias alias_name -keyalg RSA -keysize 2048 -validity 10000

Then I match the created key with key.properties file.
I start to enjoy doing app development. All the issue that appear is like a puzzle for you to solve it.
I hope I'm helping other people who facing the same issue.

**Comment by minhcasi** [comment]
Thank you so much for sharing, we will keep update with the document for this issue :)

**Comment by serragnoli** [comment]
Hi @saifmuhtar.
I've got the same problem. But I can only find a `key.properties` file inside `android` directory. Can you expand a little more on your solution please?

**Comment by mauriciozuniga** [comment]
If anyone got here for the same problem, the right and easiest way to fix it is just to open the project in Xcode, select the correct team, profile and provisioning team, and the re-run the flutter build iOS command...
