### ISSUE TITLE
[fluxstore] - downloaded 1.6.1 and got issues on oneSignal plugin 

### ISSUE THREAD

**Issue by netdreamland** [inspireui/support#1745]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: downloaded, unzipped, configured and then `flutter build ios` and `flutter run` on simulator

2. Screenshots issues: 
<img width="1207" alt="image" src="https://user-images.githubusercontent.com/12180247/71677983-02f78200-2dbf-11ea-9f2f-63bf1cc68abe.png">

3. Proof of my purchased:
<img width="799" alt="image" src="https://user-images.githubusercontent.com/12180247/71678071-33d7b700-2dbf-11ea-92e2-33586bff99fe.png">

3. Config files (optional)

**Comment by minhcasi** [comment]
@netdreamland - could you try to delete the ios/Pods folder + podfile + podfile.lock

Then, go to ios folder and  run "pod repo update" and "pod install"

**Comment by netdreamland** [comment]
sorry my late
the answer does not work, finally i removed all related object/functions and make it work
