### ISSUE TITLE
Flux store register and sign in issues

### ISSUE THREAD

**Issue by netappzone** [inspireui/support#1746]
I can not register new users as well as sign in using email and password. 

![Screenshot_20200102_181801_com huawei himovie overseas](https://user-images.githubusercontent.com/33864849/71681275-85b31980-2d8c-11ea-8500-ca23905f2ede.jpg)

**Comment by minhtruong315** [comment]
@netappzone  can u send me admin account via email: truong@inspireui.com
with subject: #1746
I want to check your website

**Comment by netappzone** [comment]
I have sent the mail but yet to get and feedback from you

**Comment by minhtruong315** [comment]
@netappzone I'm fixing Mstore Api plugin. I will let u know when done. Thanks

**Comment by aiac** [comment]
Got the same problem here. Any updates?

**Comment by minhtruong315** [comment]
@netappzone @aiac add my skype: minhtruong315
I will help u check it via teamviewer
Thanks

**Comment by minhtruong315** [comment]
You dont message me on skype. We update MStore Api, it will fix your issue. We will release soon. then you can check again. thanks

**Comment by saioufe** [comment]
have you solved the problem ??????????????????

**Comment by netappzone** [comment]
Please, I updated mstore api and I couldn't login to the app again. Please
help fix this issue.
