### ISSUE TITLE
Sign in with Apple error

### ISSUE THREAD

**Issue by Arman20022010** [inspireui/support#1747]
Puchase ID: b0b375d7-81e7-4776-83a5-4fb1f7c993fd
Hi I have problem with sign in with Apple.
Its shows this 
![Simulator Screen Shot - iPhone 11 - 2020-01-02 at 23 21 46](https://user-images.githubusercontent.com/36129818/71688191-cfb1f480-2db8-11ea-9b14-d0845f9f97a9.png)

**Comment by minhtruong315** [comment]
@Arman20022010 Add my skype: minhtruong315
I will help u check it via teamviewer

**Comment by Arman20022010** [comment]
okay :)

**Comment by minhtruong315** [comment]
supported

**Comment by minhtruong315** [comment]
HI, we're glad that it help, please give us some feedback/rating to this page https://codecanyon.net/downloads if the product is helpful for your business, we are working hard to update more awesome and powerful features on next coming version release. Let us know if you have any feedback. Thank you very much! :blush:
