### ISSUE TITLE
Cannot use Mstore-Pro for Push Notification. Ticket: #1741

### ISSUE THREAD

**Issue by onlineosman** [inspireui/support#1748]
Dear Sir,
As referrence to this ticket. #1741, I cannot use Mstore-Expo, tried installing from support department. Is there any other solution for Push Notification to work with?

![Skype Suport](https://user-images.githubusercontent.com/34172061/71688671-b78ea500-2db9-11ea-894f-af0bb434ec2f.png)

**Comment by onlineosman** [comment]
![Purchase proof for technical support](https://user-images.githubusercontent.com/34172061/71688706-cd9c6580-2db9-11ea-91a1-f848d5d0344d.png)

**Comment by minhcasi** [comment]
@onlineosman - you can check this guide for handle push notification for Expo version - https://docs.expo.io/versions/latest/guides/push-notifications/ - thanks
