### ISSUE TITLE
Fluxstore Multi Vendor - Can't register,login and Product image for WCFM

### ISSUE THREAD

**Issue by tozgan** [inspireui/support#1749]
I bought it for WCFM. But it doesn't work properly.
I have read all the corrections written here.
WCFM vendor login fails.
WCFM does not list products.
Not fully compatible with WCFM.
![wcfm](https://user-images.githubusercontent.com/20979207/71713403-94e0a880-2e1a-11ea-8ec2-dce404bf865e.PNG)

**Comment by minhcasi** [comment]
@tozgan - could you help to share your config files - thank you!

**Comment by tozgan** [comment]
[config.zip](https://github.com/inspireui/support/files/4019109/config.zip)

**Comment by tozgan** [comment]
can you help me please?

**Comment by minhcasi** [comment]
@minhtruong315 - pls help for checking

**Comment by minhtruong315** [comment]
Hi @tozgan we're having issues with the latest WCFM plugin. I'm fixing it. Then will send u update

**Comment by tozgan** [comment]
@minhtruong315 
OK wcfm is faulty.
I work with woo.
Checkout does not work at this time.
exception: you need to login to checkout
it gives an error.
My mstore api plugin is up to date.
json api plugin attached
jwt api attached
Can you please be very urgent?

**Comment by minhtruong315** [comment]
@tozgan add my skype: minhtruong315
I will help u check it via teamviewer.
Thanks

**Comment by JeffryHandani** [comment]
May I know if any update regarding WCFM ?

**Comment by minhtruong315** [comment]
@tozgan @JeffryHandani  We released new version for fluxstore mv. It's working well for WCFM. Please update in codecanyon and update MStore Api plugin as well. Thanks
