### ISSUE TITLE
[MStore] Remove Test Ad

### ISSUE THREAD

**Issue by sashaba** [inspireui/support#175]
Hello Support
I've been trying to remove the test app pop up from my app but it seen impossible, I messed up the app, removing libraries and files...
which file do I have to modify to remove the ad?

Thanks

**Comment by luyx2412** [comment]
Hi @sashaba Please provide your information app. 

Thanks

**Comment by sashaba** [comment]
Hi Lucy!

MStore Pro.
Latest version. 

Thank you.

**Comment by luyx2412** [comment]
Haha don't worry about this. So how's about your issue?

**Comment by sashaba** [comment]
Hello @luyx2412  the Test Ad pop up was removed, thank you, would you please tell me how to remove the Ad located at the bottom of the home page and at the beginning of Collections pages( when you click "show All" from home Layouts). 
Thank you.
