### ISSUE TITLE
[fluxstore-mv] - i can't login and registration from app 

### ISSUE THREAD

**Issue by yassiney120** [inspireui/support#1750]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
login and registration nor working
2. Screenshots issues:

3. Proof of my purchased:
https://ibb.co/wYmMMJm
3. Config files (optional)
https://drive.google.com/drive/folders/1rUJwLykjL_DSWXdyoPSQ6oo0wXTXrhAO?usp=sharing

**Comment by minhcasi** [comment]
@yassiney120 - note with checking - thanks

**Comment by yassiney120** [comment]
please this issues also https://github.com/inspireui/support/issues/1736

**Comment by minhtruong315** [comment]
@yassiney120 can u send me admin account via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/1750
I want to check your website

**Comment by yassiney120** [comment]
I send you email thank you

Le sam. 4 janv. 2020 à 14:10, minhtruong315 <notifications@github.com> a
écrit :

**Comment by yassiney120** [comment]
Any news

**Comment by minhcasi** [comment]
refunded

**Comment by yassiney120** [comment]
you can't solve the problem ? i waiting for 4 days no answer for that i request refund because what i will do with app
