### ISSUE TITLE
[FluxStore MV] - Question about multi vendor?

### ISSUE THREAD

**Issue by Coinizy1** [inspireui/support#1751]
I have a simple question about FluxStore Multi vendor app.
This app has payment method right? if someones buy a stuff from any store payment will go to my paypal email? and then i would have to manually transfer the payment to the seller?
thanks

**Comment by minhcasi** [comment]
@Coinizy1 - yes - it will depend on the Dokan/WFCM plugins setting on your backend site, set up the commission, withdraw... thank you!

Pls check more detail from:
https://wedevs.com/docs/dokan/withdraw/payment-withdraw/
https://wclovers.com/knowledgebase/wcfm-marketplace-withdrawal/
