### ISSUE TITLE
Cant get app to run for the 1st time

### ISSUE THREAD

**Issue by Levis-Matola** [inspireui/support#1752]
Hello...
i just finished the test drive for the flutter app and it went smoothly but im now trying to run fluxstore 1.5.9 and im getting the following stream of errors and warnings.

**NOTE:** 
I dint but the code myself. Our boss bought it and passed it to us. Her email and purchase codeare as follows:
asofia.capela@gmail.com
f97b9acf-e3d4-4feb-8125-866421f694b4

**ISSUE:**

Launching lib\main.dart on SM A750GN in debug mode...
Running Gradle task 'assembleDebug'...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

Compiler message:
../../../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/cached_network_image-1.1.3/lib/src/cached_network_image_provider.dart:42:24: Error: The method 'CachedNetworkImageProvider.load' has fewer positional arguments than those of overridden method 'ImageProvider.load'.
  ImageStreamCompleter load(CachedNetworkImageProvider key) {
                       ^
../../../../flutter/packages/flutter/lib/src/painting/image_provider.dart:403:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(T key, DecoderCallback decode);
                       ^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\AND\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 801

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\Users\AND\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 38s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by minhcasi** [comment]
@Levis-Matola - pls ask him to send you latest version 1.6.1 to fix this issue, this issue is caused by latest Flutter not compatible with the app.
