### ISSUE TITLE
[MStore Pro 3.9.7] - Could not connect to the development server.

### ISSUE THREAD

**Issue by juniortimeline** [inspireui/support#1753]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: Could not connect to the development server.

2. Screenshots issues: https://prnt.sc/qj0k61

3. Proof of my purchased: https://codecanyon.net/comments/23432146

3. Config files (optional)

**Comment by minhcasi** [comment]
@juniortimeline - this document will help - https://facebook.github.io/react-native/docs/running-on-device#method-1-using-adb-reverse-recommended - thank you!

**Comment by juniortimeline** [comment]
@minhcasi thank you so much. Also please let me know which node version compatible on 3.9.7

**Comment by minhcasi** [comment]
Please use 12.x - you can try to reinstall by download it from http://nodejs.org/
