### ISSUE TITLE
[my-product] - fluxstore multivendor

### ISSUE THREAD

**Issue by rgbufferchime** [inspireui/support#1756]
does not loads in android studio..i set upp the environment correctly but when i open this project it fails to build 

sc:
![Capture](https://user-images.githubusercontent.com/43860635/71776688-f68c4880-2fbb-11ea-9831-ac21f2e999b2.PNG)

proof of purchase:
![Capture2](https://user-images.githubusercontent.com/43860635/71776699-16237100-2fbc-11ea-9d5b-27c638e04d62.PNG)

**Comment by minhcasi** [comment]
@rgbufferchime - this is caused by missing config from Flutter, could i check if you could able run the Test Drive successful - https://flutter.dev/docs/get-started/test-drive - thanks

**Comment by rgbufferchime** [comment]
I have already tested that sir.. It runs fine.. Also as i mentioned.. When i put opencart details in config. Dart it loads the categories and products.i did that to check that too.. But i am having issues when i am using wordpress woocomerce.. Then no product loads in the app
