### ISSUE TITLE
The plugin cloud_firestore could not be built due to the issue above

### ISSUE THREAD

**Issue by hssan** [inspireui/support#1757]
Hi 
Ive opened a fresh copy of your app in android and when click run iget this error

Screenshots issues:
![1](https://user-images.githubusercontent.com/11776498/71776971-05fa9a00-2f9a-11ea-858e-1aaab53c9a3b.png)
![2](https://user-images.githubusercontent.com/11776498/71776972-06933080-2f9a-11ea-9581-56c94bc4be60.png)

3. Proof of my purchased:
![Capture](https://user-images.githubusercontent.com/11776498/71776973-06933080-2f9a-11ea-8e78-d36d81bfad08.PNG)

**Comment by minhcasi** [comment]
@dttrung26 - pls help for a suggestion

**Comment by dttrung26** [comment]
Hi @hssan , could you please send me your whole project folder after deleting /build folder for investigating?

**Comment by hssan** [comment]
hi @dttrung26 
i just downloaded  the last update from code canyon and run it without any modifications 
PS the update 1.5.9 works perfectly

**Comment by dttrung26** [comment]
Hi @hssan ,
As I checked so far, fluxstore still runs smoothly with the latest version. 
Could you try to show me your screen running "flutter doctor" and update C runtime lib at https://support.microsoft.com/en-us/help/2999226/update-for-universal-c-runtime-in-windows. Please tell me if it works.

**Comment by dttrung26** [comment]
Closed due to inactivity. Feel free to reopen if you still face this issue.
