### ISSUE TITLE
[FluxStore 1.6.1-Woocommerce] - No notification/alert when adding product to cart. Bottomsheet add to cart not updated.

### ISSUE THREAD

**Issue by IamJAX** [inspireui/support#1759]
1. My issue:
No indication/alert when a product is added to the cart from a single product page. 

The BottomSheet Add to cart is also NOT updated when the product is added to the cart from a single product page. It will be updated only after visiting cart.

2. Screenshots issues:

3. Proof of my purchased:
Adding comment on codecanyon

**Comment by IamJAX** [comment]
Here is a video of the issue
https://imgur.com/a/DkSkPFT

**Comment by zahmed84** [comment]
I am also facing the same issue.... please help to resolve it.

**Comment by Isodie** [comment]
Yes I noticed it in Demo app form PlayStore

**Comment by minhcasi** [comment]
@zahmed84 @Isodie - confirm this is a bug - pls comment this line of code to fix the issue - https://tppr.me/nWAdx

We've fixed it from latest code and will be released the patching soon - thank you!

**Comment by IamJAX** [comment]
Comment out that one line fixes the issue. Thanks
