### ISSUE TITLE
[Beonews] failed to update project files

### ISSUE THREAD

**Issue by comnarty** [inspireui/support#176]
I tried it in ubuntu and WIN10, after running yarn install and open the app in Android Studio couldn't find src/common and other folder from inside the studio, however when tried to update the files with code editor nothing change?? 
Only work with expo

**Comment by thangvo9x** [comment]
Hi, Which product were you bought?

**Comment by comnarty** [comment]
Beonews

**Comment by minhcasi** [comment]
Hi, could you help to share the screenshot of the detail issues - thank you!

**Comment by minhcasi** [comment]
Hi, there is no response from this ticket so that we will close it, please re-open when you have the update - thank you!
