### ISSUE TITLE
Fluxstore Listing build issue

### ISSUE THREAD

**Issue by xcheong81** [inspireui/support#1760]
trying the run in ios simulator and this is the error i'm facing

Xcode's output:
↳
    In file included from /Users/xavier/app/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_facebook_login-3.0.0/ios/Classes/FacebookLoginPlugin.m:3:
    In file included from /Users/xavier/app/besthotel-flutter/ios/Pods/Headers/Private/FBSDKLoginKit/FBSDKLoginKit.h:27:
    /Users/xavier/app/besthotel-flutter/ios/Pods/Headers/Private/FBSDKLoginKit/FBSDKLoginButton.h:24:9: fatal error: module 'FBSDKCoreKit' not found
    @import FBSDKCoreKit;
     ~~~~~~~^~~~~~~~~~~~
    1 error generated.

Could not build the application for the simulator.
Error launching application on iPhone 11 Pro Max.

**Comment by trunghieuvn** [comment]
you try command
```
flutter clean
```
delete folder ios/Pods
run command: (cd folder ios) 
```
pod install
```
