### ISSUE TITLE
FLuxStore 1.6.1 Failed to build

### ISSUE THREAD

**Issue by Isodie** [inspireui/support#1762]
Item Purchase Code:
5b81a1f1-b6f8-41d7-a4a8-169532748691

<img width="1009" alt="Screenshot 2020-01-05 at 7 25 28 PM" src="https://user-images.githubusercontent.com/14618403/71781175-b2b43600-2ff1-11ea-87c5-74f817ef9f42.png">

**Comment by incepio-flutter** [comment]
if you build for IOS you can delete the pods folder and podfile and podfile.lock and update the cocoapods by going into IOS directory of your source folder you got from codecanyon.
