### ISSUE TITLE
fluxstore woocommerce 

### ISSUE THREAD

**Issue by mohamedhosni250** [inspireui/support#1763]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------
![WhatsApp Image 2020-01-02 at 6 26 41 PM(1)](https://user-images.githubusercontent.com/51167046/71781501-4842cc00-2fd8-11ea-98e1-0771cda61229.jpeg)
![WhatsApp Image 2020-01-02 at 6 26 41 PM](https://user-images.githubusercontent.com/51167046/71781502-48db6280-2fd8-11ea-82f5-420837aae206.jpeg)
![WhatsApp Image 2020-01-05 at 3 01 38 PM](https://user-images.githubusercontent.com/51167046/71781503-48db6280-2fd8-11ea-92c2-11baddb69604.jpeg)
![WhatsApp Image 2020-01-05 at 4 23 38 PM](https://user-images.githubusercontent.com/51167046/71781504-48db6280-2fd8-11ea-8b07-5f255b1b0faa.jpeg)
![WhatsApp Image 2020-01-05 at 4 23 46 PM](https://user-images.githubusercontent.com/51167046/71781505-4973f900-2fd8-11ea-8f75-479cddceefdf.jpeg)
![WhatsApp Image 2020-01-05 at 4 24 03 PM](https://user-images.githubusercontent.com/51167046/71781506-4973f900-2fd8-11ea-80a5-ed91666cee26.jpeg)
![WhatsApp Image 2020-01-05 at 4 34 21 PM](https://user-images.githubusercontent.com/51167046/71781596-462d3d00-2fd9-11ea-8e00-6eafacbca56b.jpeg)

1 - I have problem with shipping page, my WordPress website has “add custom state” plugin, and I set shipping 2 method class for 1 custom state in flux store app it shown all method together for all state and doesn’t show my custom state I need to be the same form in my website even it will be web view …. you can check my checkout page from here https://www.winkishop.com/checkout/ custom stat under country select box  
2 - when I choose my payment method with plugin Its Migs in wordpress it shown 404 error screen check screenshot in attach files
3 - if possible i need all checkout page webview to avoid this errors

**Comment by minhtruong315** [comment]
Hi @mohamedhosni250 can u send me config files and admin account via email: truong@inspireui.com with subject: https://github.com/inspireui/support/issues/1763. I will help u check the issue. Thanks

**Comment by mohamedhosni250** [comment]
Done

**Comment by mohamedhosni250** [comment]
any news ? @minhtruong315

**Comment by minhtruong315** [comment]
@mohamedhosni250 add my skype: minhtruong315
I will help u check it via teamviewer. thanks

**Comment by minhtruong315** [comment]
You haven't messaged me on skype. Please check your issue on next release. We'll release fluxstore soon. Thanks

**Comment by mohamedhosni250** [comment]
i have messaged you in skype check you skype plz

>
