### ISSUE TITLE
Nosuchmethoderror: the getter is called on null  Flutter

### ISSUE THREAD

**Issue by Mehtab1322** [inspireui/support#1766]
Hello Sir!
  I have issue in navigating to a new page using 
"      Navigator.push(context,
             MaterialPageRoute(builder: (context) => ProductsPage()));"
I face the error 
Nosuchmethoderror: the getter is called on null 

How can i discuss my issues while developing fluxstore app? Is there any support for chat or something else? 
 Please help me. Thanks in advance

**Comment by minhcasi** [comment]
Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads  it's used to verify your proof of purchase? sorry for any inconvenience - Thank you!

**Comment by RiadhVet** [comment]
Same issue

**Comment by PrakashNaidu2662** [comment]
Even I am facing the Same Issue
