### ISSUE TITLE
[FluxStore MV] - Issues ( shipping methode , cart widget,wishlist in home page)

### ISSUE THREAD

**Issue by yassiney120** [inspireui/support#1768]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------
big thank to all inspireui team 
1. My issue:
1-my product not showing in the menu
2-shipping method showing all normaly it should be filtred by zip code
3-widget cart not showing in home page , single product page 
4-add to wishlist not showing in home page
5-order historique showing error
thank you for your help
2. Screenshots issues:
https://ibb.co/6DckHCQ
https://ibb.co/5vQfnDy
https://ibb.co/bQb3vF0
https://ibb.co/SwHXrJM
https://ibb.co/YdsHvVr
3. Proof of my purchased:
https://ibb.co/4Z4L8GB
3. Config files (optional)

**Comment by minhtruong315** [comment]
supported
