### ISSUE TITLE
[mstore] Unable to Ship to

### ISSUE THREAD

**Issue by hellogossh** [inspireui/support#177]
**Required Info (please complete the following information):**
 - Product: [MStore]
 - Your Purchased Code: [8636fad5-9c9b-45c9-99fd-9d0fa473fa3e]
(we may not reply if you are not our customer)

**Describe the bug**
Just keep getting the same message "Unable to Ship to [Country] Please enter an alternative shipping address" each time I register as a new customer via the app. Can you please help with this.

Just to let you know I previously had success checking out but for some reason I now have this issue. I have set up different environments to test etc, but always get the same error.

**Screenshots**
![simulator screen shot - iphone xs - 2019-01-11 at 16 18 22](https://user-images.githubusercontent.com/46603475/51045973-c8e50d00-15bc-11e9-835c-6725b69382c2.png)

**Comment by sashaba** [comment]
Same error, I was about to post an issue about this. somebody please help to fix this asap. my app is not accepting any orders because of this error message. "Unfortunately we do not ship to the United states, please enter an alternative shipping address"

**Comment by luyx2412** [comment]
Hi @hellogossh and @sashaba Please send to my email luyxtran264@gmail.com your account and website information. I would like to check your config, and investigate to improve the app.

Thanks

**Comment by luyx2412** [comment]
Hi there, i just found causing the issue is `countryCode`. You can set hard code about your country shipping.
![image](https://user-images.githubusercontent.com/8909619/51294129-27d6d600-1a44-11e9-9c8d-830f1d49ba49.png)

We will try fix the issue in next version. Thanks

**Comment by sashaba** [comment]
where we find this file?

**Comment by luyx2412** [comment]
Hi @sashaba the file is `src/containers/Cart/Payment/index` line 126 and 140.

Thanks

**Comment by sashaba** [comment]
Hi @luyx2412 didn't work. 
when I set the country to "US" the billing state is broken and the state field disappeared from the page.

![pic3](https://user-images.githubusercontent.com/40736543/51416182-605ed880-1b46-11e9-9607-ba6dc4e5f094.jpg)

No State field.

![pic4](https://user-images.githubusercontent.com/40736543/51416319-f2ff7780-1b46-11e9-9ab7-f02e5f0ac42d.jpg)

**Comment by sashaba** [comment]
This issue isn’t fixed in the latest update, I updated my whole app today and Still can’t complete checkout. Same error message.

**Comment by hellogossh** [comment]
Yes - I had the same issue. But the App for me is only available in one country to download, so setting "hideCountryList" to true in the config works for me.
