### ISSUE TITLE
[ListApp] - (1.7.4) error at startup 

### ISSUE THREAD

**Issue by essamsalah** [inspireui/support#1770]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
I just downloaded the latest version, have latest node/expo installed, open CeBuilder and point to my folder and click run setup. nothing works, screenshot below from the console output

I can't start the app.

2. Screenshots issues:

![image](https://user-images.githubusercontent.com/3326831/71853374-42d6a600-30ec-11ea-9551-571adcbaeb3f.png)

3. Proof of my purchased:
5142f522-1735-4d4e-945d-1b0b31267dbf

3. Config files (optional)

**Comment by minhcasi** [comment]
@essamsalah - from the terminal could you try to run "expo start" - it will open the Expo from browser and  from there - you can trigger the ios device
