### ISSUE TITLE
[fluxnews] - IOS simulation error 

### ISSUE THREAD

**Issue by mwu11358** [inspireui/support#1771]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.
Licensor's Author Username:
InspireUI

Item Purchase Code:
f3d20994-ae18-423f-a068-20e84dbc936c

Purchase Date:
2019-12-04 00:52:23 UTC---------

1. My issue:
No SuchMethodError: The getter 'imageFeature' was called on Null. Receiver: null Tried Calling: imageFeature S
2. Screenshots issues:

![Screen Shot 2020-01-06 at 9 11 40 PM](https://user-images.githubusercontent.com/56764599/71862971-6dfbce00-30c9-11ea-8438-800840530c17.png)

3. Config files (optional)
fluxnews demo under category show card file list

**Comment by dttrung26** [comment]
Hi @mwu11358 ,
would you mind sending me your /lib/common folder for checking please. 
Have a nice day,
Trung.

**Comment by mwu11358** [comment]
Thanks for your help. the attachment is zip for lib/common.

**Comment by dttrung26** [comment]
Hi @mwu11358 , 
I'm so sorry for such a late response. Could you please double-check the common folder because so far, I don't see any attachment. 
Cheers,
Trung.

**Comment by minhcasi** [comment]
fixed on latest 1.2.1 - thank you!
