### ISSUE TITLE
There is no forgot password screen to recover the user password?

### ISSUE THREAD

**Issue by inimist** [inspireui/support#1772]
There is no forgot password screen to recover the user password

---------

1. My issue: 
How I can enable the  forgot password functionality 

2. Proof of my purchased:
![Screenshot at Jan 03 15-33-38](https://user-images.githubusercontent.com/447618/71873276-cc19c700-3144-11ea-9899-5c01d12c38b8.png)

**Comment by minhcasi** [comment]
@inimist - you can try to add the Linking to open as webview to the forgot password link, example: http://demo.mstore.io/wp-login.php?action=lostpassword - thanks

**Comment by minhcasi** [comment]
moved to #1773 - pls help to create one ticket for all issues - thank you!
