### ISSUE TITLE
[MStore Pro] - Push Notification does not opened in the app (One Signal)

### ISSUE THREAD

**Issue by alexisttt** [inspireui/support#1774]
1. My issue:
Hello. I have configured the app like the guide. Until the guide does not contain necessary steps. And i have setup the onesignal push notifications. And it's working. When i send a notification. It arrives to the devices. But when i click to open it it opens in the browser instead of the app. I have tried to send the notification from woocommerce panel. Also from the onesignal panel and i still get the same result. I have tried to add app:// to url in onesignal panel before sending. This time i can send the notification and user recived it. When i clicked it, it opened in the app. But not the page it should open. Instead it loads the main page of the app.

In the settings. I did not added this line bellow because there it was not in the android/app/build.gradle. 
`manifestPlaceholders = [onesignal_app id: "APP_ID ", onesignal_google_project number: "PROJECT_NUMBER "]`

Instead i configured firebase account because of onesignal keeps it mandatory. 
 
How can i solve my issue? Is there any thing i can do? Waiting for your help thanks.

I'm using mstore pro-3.9.6

2. Proof of my purchased:

[Proof](https://user-images.githubusercontent.com/45356673/71313053-67702400-2444-11ea-8138-8162fa0d8a5b.pngl)

**Comment by minhcasi** [comment]
@alexisttt - could you try with the latest version as we have fixed this issue

**Comment by alexisttt** [comment]
Dear Minh. Thank you for guiding me. I didn't wanted to use because I had couple of problems and dear Trying helped and solved for me. Right now I don't have time to customize all the app but I will try a couple of weeks later when I'm available. Until then I'm closing the issue. If I face another problem or solve it I'll update it. Thanks again
