### ISSUE TITLE
FluxStore listing 1.2.0 Need Help

### ISSUE THREAD

**Issue by anatoliacreative** [inspireui/support#1775]
I did everything right. I watched the videos. I installed the “Source” folder in different places and tried again. but I never succeeded.
I deleted the Build folder. I installed the “source” folder in different places. I did everything right. I try everyhing.

```
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\src\flutter\source\android\app\build.gradle' line: 74

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not find method testImplementation() for arguments [junit:junit:4.12] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BU�LD FAILED in 0s
Finished with error: Gradle task assembleDebug failed with exit code 1
```
REPLY: Follow this solution https://stackoverflow.com/questions/52590101/could-not-find-method-testimplementation-for-arguments-junitjunit4-12
ME: I'm sorry I couldn't figure it out. I could not. I try but same error. How do I it? How can I fix?

**Comment by anatoliacreative** [comment]
I changed the system language. I use Windows in English. now I get different error.

```
Compiler message:
../flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-1.1.3/lib/src/cached_network_image_provider.dart:42:24: Error: The method 'CachedNetworkImageProvider.load' has fewer positional arguments than those of overridden method 'ImageProvider.load'.
  ImageStreamCompleter load(CachedNetworkImageProvider key) {
                       ^
../flutter/packages/flutter/lib/src/painting/image_provider.dart:403:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(T key, DecoderCallback decode);
                       ^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 780

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 21s
Finished with error: Gradle task assembleDebug failed with exit code 1
```

**Comment by minhcasi** [comment]
Hi, pls try to run "flutter upgrade" to update your Flutter to the latest version as the loading issue from CachedNetworkImageProvider seems to related of out-date flutter version

**Comment by minhcasi** [comment]
@anatoliacreative - try to check this solution as well https://github.com/inspireui/support/issues/1613

**Comment by anatoliacreative** [comment]
https://github.com/inspireui/support/issues/1613#issuecomment-565782808

Yes working now. thanks.

**Comment by anatoliacreative** [comment]
I need the complete setup video for LISTEO. I cannot link app content to my website. I could not link the application to my own website. I’m trying it for the first time. And I fail. Thanks. King Regards.

**Comment by minhcasi** [comment]
@anatoliacreative - sorry this is missing image - https://docs.inspireui.com/static/364e5cd4848638c2ad12481c6dc2931b/0ecb7/enable_listing_api.png - we also update the document

**Comment by anatoliacreative** [comment]
I need the complete setup video for LISTEO

**Comment by minhcasi** [comment]
@minhtruong315  - pls help to create a new video for the installing - thank you!

**Comment by anatoliacreative** [comment]
video please :).  i need help

**Comment by anatoliacreative** [comment]
https://ibb.co/mBJ4tqY
I cannot run the application. I tried all the instructions. I have tried several times. I think I'm making a mistake. I need a full setup video.

**Comment by inspireui-support** [comment]
@anatoliacreative - could you help to download the latest release today to fix the issue - thank you!
