### ISSUE TITLE
BuzzApp - problem when build

### ISSUE THREAD

**Issue by caldemation** [inspireui/support#1776]
C:\Users\Fran\AppData\Local\Programs\CeBuilder>expo build:android --clear-credentials
Project at path C:\Users\Fran\AppData\Local\Programs\CeBuilder does not contain a valid app.json.
Set EXPO_DEBUG=true in your env to view the stack trace.
- Making sure project is set up correctly...

------------------------------------------------
I look this problem when i try to build (ios and android) BuzzApp in CeBuilder.

**Comment by minhcasi** [comment]
Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads  it's used to verify your proof of purchase? sorry for any inconvenience - Thank you!

**Comment by caldemation** [comment]
![d89e3830d7a3683ffb8c3250ef9757ff](https://user-images.githubusercontent.com/59631213/71979366-d52a9700-321d-11ea-8bf7-b46fe073ce3e.png)

**Comment by minhcasi** [comment]
@minhtruong315 - pls help for checking

**Comment by caldemation** [comment]
Pls I need help quickly

**Comment by caldemation** [comment]
I've been waiting for 5 days. If I do not receive an answer soon I will request the money back. Thanks.

**Comment by minhtruong315** [comment]
@caldemation add my skype: minhtruong315
I will help u check via teamviewer
thanks

**Comment by minhtruong315** [comment]
You haven't messaged me on skype.

**Comment by caldemation** [comment]
Hello, sorry, I've been traveling, I add you on skype.
