### ISSUE TITLE
[Mstore] - Mstore expo

### ISSUE THREAD

**Issue by sanlalex** [inspireui/support#1778]
Hi i have a problem with new member registration on app! It not not working. Please support Thanks!
in Attachement common/appconfig.json and config.js

[common.zip](https://github.com/inspireui/support/files/4034416/common.zip)

![proff mstore](https://user-images.githubusercontent.com/33254426/71965332-5cb0df80-31f7-11ea-8a65-80ebb9cf5e21.PNG)

**Comment by minhtruong315** [comment]
@sanlalex add my skype: minhtruong315
I will help u check via teamviewer
Thanks

**Comment by sanlalex** [comment]
Ok i had you my skype *live:yiyayo07**

**Comment by minhtruong315** [comment]
I messaged you on skype. We'll check it via skype. thanks
