### ISSUE TITLE
[MStore Pro] Guest Checkout or remove mandatory login to checkout

### ISSUE THREAD

**Issue by sashaba** [inspireui/support#178]
**Mandatory Info (please complete the following information):**
 - Product: Mstore pro.
 - Your Purchased Code: 4bb2fd9b-4a08-4e19-9c74-fc95f51533e7

Hello Support team.
Would you please help me to remove the mandatory login at checkout, or enable guest checkout. 
Thank you.

**Comment by minhcasi** [comment]
Noted for updating by adding new extra config - thank you!

**Comment by luyx2412** [comment]
Updated new version.
