### ISSUE TITLE
Choose Address and other problems

### ISSUE THREAD

**Issue by ramazansavas53** [inspireui/support#1780]
Hi,
 
I purchased your fluxstore product, I installed my opencart system, but the registered addresses do not appear in the select address section.
 
flutter: NoSuchMethodError: The getter 'billing' was called on null.

And

const List DefaultCountry get an error

![IMG_9153](https://user-images.githubusercontent.com/42416142/71983113-21360580-3237-11ea-9d74-2d9d35db9d90.PNG)

click on the black screen remains.

3) The basket does not appear on the product page.

**Comment by minhcasi** [comment]
Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads  it's used to verify your proof of purchase? sorry for any inconvenience - Thank you!

**Comment by ramazansavas53** [comment]
[image: Ekran Resmi 2020-01-09 13.51.41.png]

Minh Pham <notifications@github.com>, 9 Oca 2020 Per, 05:03 tarihinde şunu
yazdı:

**Comment by minhcasi** [comment]
@ramazansavas53 - sorry for late response, please help to share the image again as we could not get it - thank you!
