### ISSUE TITLE
Errors Building APK for Beonews Pro

### ISSUE THREAD

**Issue by Octo3010cl** [inspireui/support#1783]
Good Day
We are experiencing errors when building our apk for our beonews app.
Here are the errors returned when after attempting to assemble our project.
![Screen Shot 2020-01-08 at 2 33 22 PM](https://user-images.githubusercontent.com/59663558/72005375-dc54a380-3223-11ea-8735-edc41f92d517.png)
![Screen Shot 2020-01-08 at 2 31 31 PM](https://user-images.githubusercontent.com/59663558/72005378-df4f9400-3223-11ea-81dd-1a8185f9abc1.png)

**Comment by minhcasi** [comment]
Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads  it's used to verify your proof of purchase? sorry for any inconvenience - Thank you!

**Comment by Octo3010cl** [comment]
Hey, we sorted out this issue, so its okay~
