### ISSUE TITLE
can't login

### ISSUE THREAD

**Issue by csoftech** [inspireui/support#1784]
warning:format exception: unexpected character (at character 1)<!Doctype html >^ 

I can't login getting above error with latest version.

**Comment by minhcasi** [comment]
moved to #1785

**Comment by RiadhVet** [comment]
Same issue

**Comment by RiadhVet** [comment]
This didn't work for me. Still the same error
    add codes in lib/models/product.dart to https://tppr.me/1bech and https://tppr.me/swKTf
    replace this code in lib/screens/detail/additional_information.dart to https://tppr.me/nkw1Y

**Comment by RiadhVet** [comment]
> 
> 
> warning:format exception: unexpected character (at character 1)<!Doctype html >^
> 
> I can't login getting above error with latest version.

did you manage to fix this ?

**Comment by csoftech** [comment]
still the same error, code written in last screenshot ihttps://tppr.me/nkw1Y s already there I have downlaoded 1.6.2
