### ISSUE TITLE
Fluxstore WooCommerce - Flutter E-commerce Full App

### ISSUE THREAD

**Issue by roziseth01** [inspireui/support#1786]
1. My issue: 
Failed assertion: boolean expression must not be null
When i  click the item in products, it iwll shows this screen.

2. Screenshots issues:
![Screenshot 2020-01-09 at 7 42 00 AM](https://user-images.githubusercontent.com/59671391/72025612-9fd08880-32b3-11ea-9b7a-50936661ff15.png)

3. Proof of my purchased:
![Screenshot 2020-01-09 at 7 40 07 AM](https://user-images.githubusercontent.com/59671391/72025624-ad860e00-32b3-11ea-8fb3-87ddb6f77fb2.png)

3. Config files (optional)
[Archive.zip](https://github.com/inspireui/support/files/4037891/Archive.zip)

**Comment by roziseth01** [comment]
Additional issue; all of Home function for categories not displaying any product. When i click the link generated by; it shows this value. 

{"code":"woocommerce_rest_authentication_error","message":"Invalid nonce - nonce has already been used.","data":{"status":401}}

some was ok, some generated boolean issue. 
1) i havent do any upgrade on the woocommerce or plugin
2) flutter get dependencies has been upgrade
3) rest api using the supplied with master file. none was changed.

**Comment by roziseth01** [comment]
got any update?

**Comment by vumanhsn97** [comment]
@roziseth01 Can you share your video record? I can't check localhost server

**Comment by roziseth01** [comment]
> @roziseth01 Can you share your video record? I can't check localhost server
> Try to change this code in lib/models/product.dart https://tppr.me/NsvEg and https://tppr.me/HbVr8

still the same. What you need? possible to remote in? to check?
it seems if we click on the product details, it will come out this issue. 

I have add the "?? false" to both 'on_sale' & 'in_stock'

**Comment by vumanhsn97** [comment]
@roziseth01 Can you share video record bug with console log error?

**Comment by roziseth01** [comment]
ill try now.

**Comment by roziseth01** [comment]
here's the link

https://drive.google.com/file/d/1uMYzfoZRrWwbN8vGiWpyMO6HuUPP0Dog/view?usp=sharing

**Comment by vumanhsn97** [comment]
@roziseth01 Do you have teamview?

**Comment by roziseth01** [comment]
yes i have shall i mail to you the iD or can paste here?

**Comment by roziseth01** [comment]
════════ (4) Exception caught by widgets library ═══════════════════════════════════════════════════
The method '*' was called on null.
Receiver: null
Tried calling: *(1.2)
The relevant error-causing widget was: 
  BlogItemView file:///Users/xxxxxxxxxx/FluxStore-woo%201.6.1/source/lib/widgets/home/horizontal/blog_list_items.dart:53:13

i think this was the issue. it keep saying the :

return LayoutBuilder(
      builder: (context, constraints) {
       if (blogs.length == 0) return Column(
          children: <Widget>[
            _buildHeader(context, null),
            BlogItemView(posts: emptyPosts, index: 0),
            BlogItemView(posts: emptyPosts, index: 1),
            BlogItemView(posts: emptyPosts, index: 2),
          ],
        );

**Comment by roziseth01** [comment]
hi, i have updated the code to 1.6.2. Seems the red screen issues gone. However, we got another bugs. Ill post later.

**Comment by roziseth01** [comment]
our issue, since 1.6.1 we cannot compile the code for ANDROID. how to resolve this?

**Comment by vumanhsn97** [comment]
Can you show more detail?

**Comment by epkim** [comment]
I am using version 1.6.2.
Received status code 403 from server: Forbidden

LOG

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve com.google.android.gms:play-services-location:[15.0.0, 16.0.0).
     Required by:
         project :app > com.onesignal:OneSignal:3.12.4
      > Failed to list versions for com.google.android.gms:play-services-location.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/google/android/gms/play-services-location/maven-metadata.xml.
            > Could not get resource 'https://jcenter.bintray.com/com/google/android/gms/play-services-location/maven-metadata.xml'.
               > Could not GET 'https://jcenter.bintray.com/com/google/android/gms/play-services-location/maven-metadata.xml'. Received status code 403 from server: Forbidden

**Comment by roziseth01** [comment]
> our issue, since 1.6.1 we cannot compile the code for ANDROID. how to resolve this?



> Can you show more detail?

It showing the gradle crash. At first it shows there is no permission. Then we chmod+x gradlew. After that it keep saying the gradle build fail.  It doesnt have error for IOs. Its only for android. Please assists to resolve this as we plan to go live soon as we can.

**Comment by vumanhsn97** [comment]
try to run cmd
chmod a+rx android/gradlew

**Comment by roziseth01** [comment]
> try to run cmd
> chmod a+rx android/gradlew

i have tried. still error.

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run

## exception

ProcessException: ProcessException: Operation not permitted
  Command: /Users/xxxxxx/Desktop/FluxStore-woo 1.6.2/source/android/gradlew -q -Ptarget=/Users/fakhrulrozi.seth/Desktop/FluxStore-woo 1.6.2/source/lib/main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root -Ptarget-platform=android-x86 assembleDebug

```
#0      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:431:29)
<asynchronous suspension>
#1      buildGradleApp (package:flutter_tools/src/android/gradle.dart:364:35)
#2      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
#3      buildGradleApp (package:flutter_tools/src/android/gradle.dart:218:28)
#4      _AndroidBuilderImpl.buildApk (package:flutter_tools/src/android/android_builder.dart:97:13)
#5      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
#6      _AndroidBuilderImpl.buildApk (package:flutter_tools/src/android/android_builder.dart:91:24)
#7      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:522:28)
#8      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#9      _rootRunUnary (dart:async/zone.dart:1134:38)
#10     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#11     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#12     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#13     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#14     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#15     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#16     _rootRun (dart:async/zone.dart:1126:13)
#17     _CustomZone.run (dart:async/zone.dart:1023:19)
#18     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#19     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#20     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#22     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale en-MY)
    [32m•[39m Flutter version 1.12.13+hotfix.5 at /Users/fakhrulrozi.seth/development/flutter
    [32m•[39m Framework revision 27321ebbad (5 weeks ago), 2019-12-10 18:15:01 -0800
    [32m•[39m Engine revision 2994f7e1e6
    [32m•[39m Dart version 2.7.0

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    [32m•[39m Android SDK at /Users/fakhrulrozi.seth/Library/Android/sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-29, build-tools 29.0.2
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 11.3)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 11.3, Build version 11C29
    [32m•[39m CocoaPods version 1.8.4

[32m[✓][39m Android Studio (version 3.5)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin version 42.1.1
    [32m•[39m Dart plugin version 191.8593
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[32m[✓][39m VS Code (version 1.41.1)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.7.1

[32m[✓][39m Connected device (1 available)
    [32m•[39m Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

[32m•[39m No issues found!
```

**Comment by roziseth01** [comment]
i just dont know what happened and where to check, becoz i ran all my other projects for ANDROID its working well. except for this. Please assists

**Comment by vumanhsn97** [comment]
@roziseth01 Try to run
flutter clean

**Comment by roziseth01** [comment]
guys. manage to resolve the issue

xattr -d com.apple.quarantine android/gradlew

refer this:
https://github.com/flutter/flutter/issues/41486

**Comment by roziseth01** [comment]
lot of issue popup:
1) login now not working at all. 1.6.1 working well
2) blog got issue not displaying data. return null /

**Comment by vumanhsn97** [comment]
@roziseth01 Can you share more detail?

**Comment by mansoor88** [comment]
I load the project successfully in Android studio. But unable to run in emulator
