### ISSUE TITLE
Sign up by phone

### ISSUE THREAD

**Issue by abouzeidroy** [inspireui/support#1787]
Hello.
Item Purchase Code:
ac5bfa48-8c10-43cf-81f8-59c1d913cb56

Question: how can i activate the sign up by phone number feature for my users.
Pls send step by step process
Thank u

**Comment by minhcasi** [comment]
@abouzeidroy - could i know which the product that you mention on this question? This guide could be related https://docs.inspireui.com/fluxstore/firebase/#sms-login

**Comment by abouzeidroy** [comment]
Mstore Pro

**Comment by abouzeidroy** [comment]
![IMG_9734](https://user-images.githubusercontent.com/36563543/72076116-b7ccfa00-32fd-11ea-9b23-9bb1deafbd87.PNG)

Problem number 2: i was using your woocommerce template, everything was working perfectly with my Mstore app. I removed your test products from woocommerce and uploaded my real products. Now i have the error you can see in the photo. app i crashing now

**Comment by abouzeidroy** [comment]
I found this page for sms login explanation: https://docs.inspireui.com/mstore/facebook-setting/
You say inside this to:
To use this feature please make sure update the Mstore Checkout plugin to latest 1.1.5 (download here) 

I download all the folder, and installed mstore-checkout plugin but i got this error in wordpress:


Fatal error: Cannot redeclare registerJsonApiController() (previously declared in /home/forge/mstoremasterbackend.mediaedgeagency.com/wp-content/plugins/mstore-api/mstore-api.php:153) in /home/forge/mstoremasterbackend.mediaedgeagency.com/wp-content/plugins/mstore-checkout/mstore-checkout.php on line 109

Please tell me the solution

**Comment by abouzeidroy** [comment]
Also,
when i click on the square to change the homelayout, i have an error

![1](https://user-images.githubusercontent.com/36563543/72101541-9d127980-332d-11ea-857d-dbb09d4b83da.png)
![Screen Shot 2020-01-09 at 10 12 41 PM](https://user-images.githubusercontent.com/36563543/72101542-9dab1000-332d-11ea-9267-24456f4d4c96.png)


Please answer all my 3 questions above, this is the summary:

Question 1: For sms activation, mstore-checkout plugin is giving fatal error when i install it
Question 2: When i import my products with woocommerce csv, i have an error in the app
Question 3: When i try to switch homelayout i have a modal error.

All screenshots and explanations are up, you can check

thank you

**Comment by abouzeidroy** [comment]
@minhcasi hello, pls answer my questions

**Comment by minhcasi** [comment]
@abouzeidroy  - sorry for late response, could you help to share the config so that we could help for checking - thank you!
