### ISSUE TITLE
[FluxStore Listing] - Images would not show up on the App

### ISSUE THREAD

**Issue by tastemeitaste** [inspireui/support#1788]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: Images would not show up on the app, and the images also would not load.

2. Screenshots issues:
![problem screenshot](https://user-images.githubusercontent.com/58832278/72039034-66b6fa80-3258-11ea-9ddc-df10934c693b.jpg)

3. Proof of my purchased: 

![prove of purchase](https://user-images.githubusercontent.com/58832278/72039038-6a4a8180-3258-11ea-8f48-0ece37f87fa3.jpg)

3. Config files (optional)

[config.zip](https://github.com/inspireui/support/files/4038640/config.zip)

**Comment by minhcasi** [comment]
@tastemeitaste - could you help to check this guide to fix the image issues - https://docs.inspireui.com/fluxstore/performance/#2-image-optimization

**Comment by tastemeitaste** [comment]
I try it before it's the same

**Comment by tastemeitaste** [comment]
I try this method before it's the same

**Comment by tastemeitaste** [comment]
can anyone help me with this issue? I get stuck for a while

**Comment by vuthanhtoan30** [comment]
Hi tastemeitaste,

Sorry for late response, it seems you are using old version of config.json file. I have included the new one below. Please replace it and let's see if it helps. 
Also please fill in your consumerKey and consumerSecret in your config.dart file. You can refer to this doc [get Consumer Key](https://docs.woocommerce.com/document/woocommerce-rest-api/) to get those.

Thank you for your patience.

config.json: [config.zip](https://github.com/inspireui/support/files/4089024/config.zip)
