### ISSUE TITLE
"See all" failure

### ISSUE THREAD

**Issue by kalakgl** [inspireui/support#1789]
I get this error, when I click "see all" links:
https://imgur.com/a/bKOjvpf

**CONFIG.JSON:**
`{
  "HorizonLayout": [
    {
      "layout": "logo",
      "showMenu": false
    },
    {
      "layout" : "header_text",
      "padding": 20.0,
      "fontSize": 30.0,
      "isSafeArea": false,
      "title" : "Nutaarsiassat - Nyheder"
    },
    {
      "layout" : "largeCardHorizontalListItems",
      "imageBorder": 20.0,
      "category": 2
    },

    {
      "layout" : "sliderBlogList",
      "type" :"imageOnTheRight",
      "imageBorder": 3.0,
      "name": {
        "en": "Event",
        "da": "Begivenhed"
      },
      "category": 14
    },
    {
      "layout" : "sliderBlogList",
      "type" :"imageOnTheRight",
      "imageBorder": 3.0,
      "name": {
        "en": "Tournament",
        "da": "Turnering"
      },
      "category": 3
    },
    {
      "layout" : "sliderBlogList",
      "type" :"imageOnTheRight",
      "imageBorder": 3.0,
      "name": {
        "en": "Training",
        "da": "TrÃ¦ningstider"
      },
      "category": 15
    },
    {
      "layout" : "sliderBlogList",
      "type" :"imageOnTheRight",
      "imageBorder": 3.0,
      "name": {
        "en": "Hearings",
        "da": "HÃ¸rringer"
      },
      "category": 16
    }
  ],

  "Setting": {
    "MainColor": "#3FC1BE",
    "ProductListLayout": "list"
  }
}
`

**Comment by minhcasi** [comment]
Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads  it's used to verify your proof of purchase? sorry for any inconvenience - Thank you!

**Comment by kalakgl** [comment]
https://imgur.com/a/0lUj0l7

**Comment by kalakgl** [comment]
Any answer for this?
Can't use this package, if this error is not fixed.

**Comment by dttrung26** [comment]
Good morning @kalakgl ,
sorry for such a late response! Could you please send me your /lib/ common folder and your website admin access via trung@inspireui.com for investigating? 
Nice day!

**Comment by kalakgl** [comment]
Thank you, I just send an email.

**Comment by minhcasi** [comment]
fixed on latest 1.2.1 - thank you!
