### ISSUE TITLE
[MStore Pro RN WooCommerce] - Cant submit review 

### ISSUE THREAD

**Issue by PHPJunior** [inspireui/support#1790]
Hello, im getting these errors
- chat not working
- not showing reviews
- cant submit review
![Screen Shot 2020-01-09 at 17 39 43](https://user-images.githubusercontent.com/13845077/72064388-257f2300-330a-11ea-9879-1f7b741cfb32.png)
![a](https://user-images.githubusercontent.com/13845077/72064399-2dd75e00-330a-11ea-865b-e51a49206afd.png)
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-01-09 at 17 37 16](https://user-images.githubusercontent.com/13845077/72064401-2e6ff480-330a-11ea-865b-88c855c24021.jpg)

**Comment by inimist** [comment]
I am getting same issue if I login role by the vendor.

**Comment by PHPJunior** [comment]
any update?

**Comment by inimist** [comment]
any update for this issue?

**Comment by luyx2412** [comment]
Hi @inimist Sorry about reply late. Let me investigate and reply you soon.

Thanks.

**Comment by luyx2412** [comment]
Hi @inimist and @PHPJunior Can you send me the Config.js and AppConfig.json?

Thanks

**Comment by luyx2412** [comment]
Hi @PHPJunior and @inimist 
- The review still show normal, please check your review in wordpress website
- in `src/containers/Detail/ProductDetail_Style.js` line 266 (Fixed next version) . Please replace `buttonChat` and `imageButtonChat` with
`  buttonChat: {
    position: "absolute",
    bottom: 60,
    right: 5,
    zIndex: 9999,
  },
  imageButtonChat: {
    width: 32,
    height: 32,
    resizeMode: "contain",
  },`
- We will check the plugin user which could not work for post comment.

Thanks

**Comment by luyx2412** [comment]
Feel free reopen the issue
