### ISSUE TITLE
[FLUXSTORE WOOCOMMERCE 1.6.0] - SHIPPING TAB ERROR, RESET PASSWORD NOT WORKING

### ISSUE THREAD

**Issue by rioadetya** [inspireui/support#1793]
please fix it asap..

1. My issue:
- SHIPPING TAB ERROR
- RESET PASSWORD NOT WORKING (not working in your demo too)

2. Screenshots issues:
reset password - http://prntscr.com/qllzng
shipping tab - http://prntscr.com/qlm0et

3. Proof of my purchased:
http://prntscr.com/qi9w8f

4. Config files (optional)
config.json - http://prntscr.com/qi9s9i
config.dart - https://pastebin.com/GsdcwWXD

**Comment by minhcasi** [comment]
note as high priority for checking - thank you for your feedback

**Comment by bakpaorabbit** [comment]
@rioadetya untuk pasar indonesia dengan plugin perhitungan ongkos kirim dimana data alamat (kota & kecamatan) menggunakan dropdown ?

**Comment by rioadetya** [comment]
Betul menggunakan dropdown, http://prntscr.com/qm4omf

**Comment by bakpaorabbit** [comment]
@rioadetya sudah ane test fluxstore belum work gan untuk pasar indo yang pakai plugin ongkir. dropdown kota dan kecamatan gak ada / gak bisa di checkout mstore nya. Terus shippingnya gak bekerja untuk narik data dari klo pembeli sudah isi data billing dropdown tadi. Lebih ke ongkos kirim yang statis, seperti Flatrate, Free Shipping, Local Pickup.

**Comment by rioadetya** [comment]
@bakpaorabbit bagus di screenshot doang nih app wkwkwk pusing gw...

**Comment by bakpaorabbit** [comment]
@rioadetya settingnya emang agak ribet sih soalnya gak ada admin panel buat kustom banner dllnya. lebih cocok buat pasar luar ini sama yang flat rate, misal agan jualan buat daerah jakarta dan sekitarnya aja. ane pake yang laen sih, emang udah pake sebelum beli ini, buat testing doang. coba dah cek :
https://play.google.com/store/apps/details?id=com.rabbit.bakpaorabbit

**Comment by rioadetya** [comment]
@bakpaorabbit itu pake ChiyaS**p ya... itu shipping pake apa? epeken?

**Comment by bakpaorabbit** [comment]
@rioadetya iya ane pake itu lebih enak deploynya, ongkir pake wpbisnis, plus add on multistep checkout dari authornya. payment pake ipaymu dan duitku sama zooperwoo auto confirm.

**Comment by rioadetya** [comment]
@minhcasi how?

**Comment by rioadetya** [comment]
reset password works in 1.6.2
shipping tab still error

**Comment by rioadetya** [comment]
why closed?
