### ISSUE TITLE
[cestore react native] - expo version is not compatible with expo app

### ISSUE THREAD

**Issue by arovillard** [inspireui/support#1794]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
when trying to compile the react native project from the "mobile-evastore-theme" expo throws an error about the sdk 30 not being valid, minimum should be 33. I manually changed the expo version to 33 but this creates other issues from incompatible npm packages. Please I need a solution to this right away as I'm fully blocked.

2. Screenshots issues:
![Screenshot (Jan 9, 2020 9_54_03 PM)](https://user-images.githubusercontent.com/6244437/72129351-c5e53f80-332a-11ea-84e3-2d278e2646fe.png)

3. Proof of my purchased:
![Screen Shot 2020-01-09 at 9 50 15 PM](https://user-images.githubusercontent.com/6244437/72129367-d4335b80-332a-11ea-84e2-d17027672ec6.png)

3. Config files (optional)

**Comment by arovillard** [comment]
From what I've seen on other closed `cestore` tickets, I did expo update and I was able to get passed this SDK issue screen, however some packages now have broken dependencies such as:
```Unable to resolve "EventEmitter" from "src/Omni.js"```

**Comment by arovillard** [comment]
Also to add more context, I have the cestore web successfully running, I can access the store front and also the api and see it working on localhost:3001. I need a response ASAP regarding the react native, even if it is to know that someone is looking into this and when I would have an answer.

**Comment by arovillard** [comment]
@minhcasi when am I going to get a response? it's been 4 days since I opened this ticket.

**Comment by minhtruong315** [comment]
@arovillard add my skype: minhtruong315
I will help u check via teamviewer
Thanks

**Comment by arovillard** [comment]
I have added you, please accept the invite. my user name is live:arovillard

**Comment by arovillard** [comment]
I am still not getting helped with this, why is the support for your products so bad?

**Comment by minhtruong315** [comment]
supported
