### ISSUE TITLE
[FluxStore][FluxListing] - FluxListing does not show WooCommerce products

### ISSUE THREAD

**Issue by VenyaminBlubinest** [inspireui/support#1795]
**1. My issue:**
First of all, thank you very much for your help in previous matters (even in the most newbies).

We have FluxStore and FluxListing licenses, I have managed to integrate FluxStore with WooCoomerce in the past (with your help).

Now, entering FluxListing, I read the documentation that is compatible with MyListing for Wordpress. After which I made the respective configuration and brings the "Listings" of MyListing as "Products" of FluxListing.

My problem is the following:
FluxListing says it is compatible with MyListing.
MyListing on the other hand says that it is 100% compatible with woocomerce products.
When integrating MyListing with WooCoomerce Products, these are displayed in wordpress inside the "Listing" of MyListing but not shown in FluxListing.
In FluxListing you only see the listing without the associated products (visible in the Wordpress / MyListing listing)

Thanks for your time :)

**2. Screenshots issues:**
"Listing" by MyListing
![image](https://user-images.githubusercontent.com/51170169/72130301-e4adfb00-3357-11ea-9996-7c36ea9dfa8f.png)

associated products
![image](https://user-images.githubusercontent.com/51170169/72130325-f42d4400-3357-11ea-90d0-121602dde0d1.png)

FluxListing shows Listing but does not show associated products
![image](https://user-images.githubusercontent.com/51170169/72130424-40788400-3358-11ea-9480-5042d63d6e2f.png)

![image](https://user-images.githubusercontent.com/51170169/72130447-538b5400-3358-11ea-89b6-e9bd8ed9cf8e.png)

![image](https://user-images.githubusercontent.com/51170169/72130455-58e89e80-3358-11ea-8e1c-0feade700775.png)

**3. Proof of my purchased:**
![image](https://user-images.githubusercontent.com/51170169/72130592-c72d6100-3358-11ea-9023-7325e2efec85.png)

**Comment by minhtruong315** [comment]
@VenyaminBlubinest  add my skype: minhtruong315
I will help u check via teamviewer
Thanks

**Comment by minhtruong315** [comment]
You've messaged me on skype. We will release next update soon, then you can check again

**Comment by MohammedXAbdo** [comment]
how were they help you to solve this problem
