### ISSUE TITLE
[my-product] - fluxstore pro coupon apply issue

### ISSUE THREAD

**Issue by mayankgirdhar** [inspireui/support#1797]
---------

1. My issue:
Hey when we apply fix cart coupon its applying multiple of item added in cart
like fixed cart discount is 50 and in cart there are two items then total discount is applying 100
also if we apply coupon its not adding discount in order showing in woocommerce dashboard and customer app order history.

2. Screenshots issues:
https://ibb.co/QDP13k9
https://ibb.co/db1wfyr
3. Proof of my purchased:
https://ibb.co/47kbd6H
3. Config files (optional)

**Comment by minhcasi** [comment]
@mayankgirdhar - could you share the config files here? Thank you!

**Comment by mayankgirdhar** [comment]
config.dart or config.json?

**Comment by mayankgirdhar** [comment]
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import '../common/constants.dart';

/// Server config
const serverConfig = {
  "type": "woo",
  "url": "https://www.example.com",
  "consumerKey": "",
  "consumerSecret": "",
  "blog": "https://www.example.com",
  "forgetPassword": "https://www.example.com/wp-login.php?action=lostpassword"
};
const afterShip = {
  "api": "e2e9bae8-ee39-46a9-a084-781d0139274f",
  "tracking_url": "https://fluxstore.aftership.com"
};

const Payments = {
  "paypal": "assets/icons/payment/paypal.png",
  "stripe": "assets/icons/payment/stripe.png",
  "razorpay": "assets/icons/payment/razorpay.png",
};

/// The product variant config
const ProductVariantLayout = {
  "color": "color",
  "size": "box",
  "height": "option",
};


/// This option is determine hide some components for web
var kWebHidden = true;

const kAdvanceConfig = {
  "DefaultLanguage": "en",
  "DefaultCurrency": {
    "symbol": "\₹",
    "decimalDigits": 2,
    "symbolBeforeTheNumber": true,
    "currency": "INR"
  },
  "IsRequiredLogin": false,
  "GuestCheckout": true,
  "EnableShipping": false,
  "EnableAddress": true,
  "EnableReview": true,
  "GridCount": 3,
  "DetailedBlogLayout": kBlogLayout.halfSizeImageType,
  "EnablePointReward": true,
  "DefaultPhoneISOCode": "+91",
  "DefaultCountryISOCode": "IN",
  "EnableRating": true,
  "EnableSmartChat": true,
  "hideOutOfStock": true,
  'allowSearchingAddress': true,
  "isCaching": false,
  "OnBoardOnlyShowFirstTime": true,
  "EnableConfigurableProduct": false, //for magento
  "EnableAttributesConfigurableProduct": ["color", "size"], //for magento
  "EnableAttributesLabelConfigurableProduct": ["color", "size"], //for magento,
  "EnableAdvertisement": true,
  "Currencies": [
    {
      "symbol": "\₹",
      "decimalDigits": 2,
      "symbolBeforeTheNumber": true,
      "currency": "INR"
    }
  ]
};

/// The Google API Key to support Pick up the Address automatically
/// We recommend to generate both ios and android to restrict by bundle app id
/// The download package is remove these keys, please use your own key
const kGoogleAPIKey = {
  "android": "",
  "ios": "",
  "web": ""
};

const kOneSignalKey = {
  'appID': "",
};

/// use to config the product image height for the product detail
/// height=(percent * width-screen)
/// isHero: support hero animate
const kProductDetail = {
  "height": 0.5,
  "marginTop": 0,
  "isHero": true,
  "safeArea": false,
  "showVideo": true,
  "showThumbnailAtLeast": 3,
  "layout": kProductLayout.simpleType
};

/// config for the chat app
const smartChat = [
  
];
const String adminEmail = "organicshala1@gmail.com";

/// the welcome screen data
List onBoardingData = [
  {
    "title": "Welcome to Example",
    "image": "assets/images/walkthrough-2.png",
    "desc": "Example is on the way to serve you. "
  },
  {
    "title": "Eat Best Quality Products",
    "image": "assets/images/walkthrough-1.png",
    "desc": "example Delivers Best Quality Products. "
  },
  {
    "title": "Let's Get Started",
    "image": "assets/images/walkthrough-3.png",
    "desc": "Waiting no more, let's see what we get!"
  }
];

const PaypalConfig = {};

const RazorpayConfig = {
  "keyId": "",
  "paymentMethodId": "razorpay",
  "enabled": true
};

const TapConfig = {};

// Limit the country list from Billing Address
const List DefaultCountry = [];
//const List DefaultCountry = [
//  {
//    "name": "Vietnam",
//    "iosCode": "VN",
//    "icon": "https://cdn.britannica.com/41/4041-004-A06CBD63/Flag-Vietnam.jpg"
//  },
//  {
//    "name": "India",
//    "iosCode": "IN",
//    "icon":
//        "https://upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/1200px-Flag_of_India.svg.png"
//  },
//  {"name": "Austria", "iosCode": "AT", "icon": ""},
//];

const kAdConfig = {
  "enable": false,
  "type": kAdType.facebookNative,
  
};

**Comment by minhcasi** [comment]
@mayankgirdhar - pls help to share the real config file as we could not debug with https://www.example.com domain - thanks

**Comment by mayankgirdhar** [comment]
I have mailed you with subject config dart for issue #1797

**Comment by mayankgirdhar** [comment]
Am still waiting for your reply

**Comment by minhtruong315** [comment]
@mayankgirdhar please update fluxstore version 1.6.3 and update MStore Api plugin to the latest version. Thanks
