### ISSUE TITLE
Issue with Sign Up/Sign In on Beonews Pro App

### ISSUE THREAD

**Issue by Octo3010cl** [inspireui/support#1798]
1. My issue:
Good Day,
My issue is that I am unable to Sign Up or Sign in using the Beonews Pro App. Trying to Sign up just kicks me out of the window, and trying to Sign In with an existing account from my wordpress site just gives me the message 'Invalid email/password', regardless of what I enter.

2. Screenshots issues:
![Screen Shot 2020-01-10 at 11 38 27 AM](https://user-images.githubusercontent.com/59663558/72165370-bce18600-339d-11ea-8096-dfd44beacb4e.png)

3. Proof of my purchased:
![Screen Shot 2020-01-10 at 11 35 43 AM](https://user-images.githubusercontent.com/59663558/72165387-c4089400-339d-11ea-8750-fdcf29c0e750.png)

3. Config files (optional)
[ConfigFiles.zip](https://github.com/inspireui/support/files/4046403/ConfigFiles.zip)

**Comment by luyx2412** [comment]
Hi @Octo3010cl Are you install plugin in document https://docs.inspireui.com/beonews/wordpress-setting/? Because i did not see about authentication plugin to login or register user.

Thanks

**Comment by luyx2412** [comment]
Feel free reopen the issue.

**Comment by GHO5TMEDO** [comment]
I have the same error, all plugins installed.
