### ISSUE TITLE
[FLUXSTORE WOOCOMMERCE 1.6.1] - shipping prices issue

### ISSUE THREAD

**Issue by sfoulad** [inspireui/support#1799]
1- when I change the country still I’m seeing all the shipping methods , do you have explanation how to use multi-zone ?

I have added “ZoneIdShipping”: [1, 2], but still same issue

2- when I place order before the payment gateway I get billing address page , how can I hide it ?

3- Shipping , flat rate Advanced Costs not working

I’m using the below

10 + ( 2 * [qty] )

More info :

https://docs.woocommerce.com/document/flat-rate-shipping/

**Comment by sfoulad** [comment]
We need to hide billing address before going to payment gateway 

https://ibb.co/vJtn8Wm

**Comment by minhtruong315** [comment]
@sfoulad  add my skype: minhtruong315
I will help u check via teamviewer
Thanks

**Comment by minhtruong315** [comment]
You've not responsed me on skype. We will release updates soon. Then you can check again
