### ISSUE TITLE
Listpro

### ISSUE THREAD

**Issue by shubhamt619** [inspireui/support#180]
The app stops on clicking listings...please check.

**Comment by luyx2412** [comment]
Hi @shubhamt619 Please provide your purchase code. 

Thanks

**Comment by shubhamt619** [comment]
db055d4e-cd4e-4411-b654-21589bab86a0

**Comment by shubhamt619** [comment]
Are you there ? ? ?

**Comment by thangvo9x** [comment]
Hi. Please share your Config.js file such as your email.

**Comment by shubhamt619** [comment]
Please provide me with your mail id.I will add you to git repo.

**Comment by thangvo9x** [comment]
thang@inspireui.com

**Comment by shubhamt619** [comment]
Please check GitHub, I added you

**Comment by shubhamt619** [comment]
Also, Please pull from master again, I pushed the latest changes.

**Comment by shubhamt619** [comment]
Thank you for the commit, I am testing it now on devices. The Side Menu is not Showing Any Menu Items, Please solve it or tell me how to...

**Comment by shubhamt619** [comment]
Facebook Login is working but the normal login is not still working. The normal Login Button Shows Facebook Icon when clicked on the Facebook Login Button.


![whatsapp image 2019-01-13 at 1 37 34 pm](https://user-images.githubusercontent.com/12027792/51103928-7ef16680-180a-11e9-944b-d0bed80c1278.jpeg)
![whatsapp image 2019-01-14 at 2 40 35 pm](https://user-images.githubusercontent.com/12027792/51103930-7ef16680-180a-11e9-8b71-b5e06230e465.jpeg)

**Comment by shubhamt619** [comment]
Login is still not working

>

**Comment by shubhamt619** [comment]
Hello ! ! ! !
Are you there ??

**Comment by thangvo9x** [comment]
This login is coming from config on your website with the plugin JWT .
Please refer steps by document here:
https://wordpress.org/plugins/jwt-authentication-for-wp-rest-api/
Thanks for contact !

**Comment by shubhamt619** [comment]
What is the solution ? ? ?
I read but i don't understand

>

**Comment by shubhamt619** [comment]
App is stopping on click of any Listing.

**Comment by thangvo9x** [comment]
Please update the latest version

**Comment by thangvo9x** [comment]
Please check latest version

**Comment by shubhamt619** [comment]
The App is stil Stopping ? ? ?
What is taking so long to resolve this issue ? ??

**Comment by thangvo9x** [comment]
Hi. We've commit the latest version , please pull it.

**Comment by shubhamt619** [comment]
Did you check if it's stopping ?

**Comment by shubhamt619** [comment]
The latest version is 4days before...when did you commit ?

**Comment by shubhamt619** [comment]
The app is still stopping on click of Listing..

**Comment by minhcasi** [comment]
@shubhamt619 can you provide the screenshot of "The app is still stopping on click of Listing..", which the content cause crashing?

**Comment by shubhamt619** [comment]
Please re opern this....Right now !

**Comment by shubhamt619** [comment]
I'm uploading latest build soon.

**Comment by thangvo9x** [comment]
hi @shubhamt619  How about your problem ?

**Comment by shubhamt619** [comment]
Give me few hours

**Comment by thangvo9x** [comment]
How ? @shubhamt619
