### ISSUE TITLE
Listapp for MyListing Theme - SUpport Template MyListing - MyHome Throwing Numerous error when run on phone using expo

### ISSUE THREAD

**Issue by visheshtennis** [inspireui/support#1802]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: Support Template MyListing (My Home) is throwing numerous error while running using expo and CE Builder. I am attaching screenshots for ready reference.

I am not sure how to resolve it. I am a newbie. Just trying my hands on it. It's already been more than a month since I bought. And I am yet struggling to launch our app. Looking forward to an early response. Thanks.

2. Screenshots issues:
![WhatsApp Image 2020-01-11 at 11 19 28 AM (6)](https://user-images.githubusercontent.com/16410810/72199610-72770c80-3464-11ea-86a7-5e4b321a6cdf.jpeg)
![WhatsApp Image 2020-01-11 at 11 19 28 AM (5)](https://user-
![WhatsApp Image 2020-01-11 at 11 19 28 AM (1)](https://user-images.githubusercontent.com/16410810/72199620-8f134480-3464-11ea-94f0-34a129a8d42e.jpeg)
![WhatsApp Image 2020-01-11 at 11 19 28 AM (2)](https://user-images.githubusercontent.com/16410810/72199621-8f134480-3464-11ea-980b-7c308ee123a2.jpeg)
![WhatsApp Image 2020-01-11 at 11 19 28 AM (3)](https://user-images.githubusercontent.com/16410810/72199622-8f134480-3464-11ea-863f-72489f3512b8.jpeg)
![WhatsApp Image 2020-01-11 at 11 19 28 AM (4)](https://user-images.githubusercontent.com/16410810/72199623-8fabdb00-3464-11ea-9358-572b5889bb7c.jpeg)
![WhatsApp Image 2020-01-11 at 11 19 28 AM (5)](https://user-images.githubusercontent.com/16410810/72199625-8fabdb00-3464-11ea-9f20-5378bc39ffd7.jpeg)
![WhatsApp Image 2020-01-11 at 11 19 28 AM (6)](https://user-images.githubusercontent.com/16410810/72199626-8fabdb00-3464-11ea-9453-53c32e0ef2e4.jpeg)
![WhatsApp Image 2020-01-11 at 11 19 28 AM](https://user-images.githubusercontent.com/16410810/72199627-90447180-3464-11ea-9fbb-de378469dbc2.jpeg)
![WhatsApp Image 2020-01-11 at 11 19 29 AM (1)](https://user-images.githubusercontent.com/16410810/72199628-90447180-3464-11ea-88dc-cf0ef1a4ef7c.jpeg)
![WhatsApp Image 2020-01-11 at 11 19 29 AM (2)](https://user-images.githubusercontent.com/16410810/72199629-90447180-3464-11ea-9d5f-492e2dfbd612.jpeg)
![WhatsApp Image 2020-01-11 at 11 19 29 AM](https://user-images.githubusercontent.com/16410810/72199630-90447180-3464-11ea-9ce8-76b8742b0ab3.jpeg)

images.githubusercontent.com/16410810/72199612-76a32a00-3464-11ea-905b-13fc0121e7e3.jpeg)

3. Proof of my purchased: 
![Screenshot 2020-01-11 at 11 23 30 AM](https://user-images.githubusercontent.com/16410810/72199643-d00b5900-3464-11ea-8148-342fbcc5260f.png)

3. Config files (optional)

**Comment by minhcasi** [comment]
@visheshtennis - could you help to share the config file so that we could help for checking - thank you!

**Comment by visheshtennis** [comment]
Hey. The error has now been changed. I am attaching new error screenshot and important seemingly files in a zipped file.

We were able to get the APK if we keep the package name same as default (inspireui.mylist.....). But google doesn't allow us to upload it on app store. So, when we change the package name. Then we get errors when we click on Build Android App in CE Builder. We keep the package name - propertyyy.com generally.

Could you please help us get it resolved. It's been more than 1 month since our purchase and yet we weren't able to launch the app.

Thanks in advance.

[Archive.zip](https://github.com/inspireui/support/files/4071160/Archive.zip)
![7a34c32c-09d2-4bde-99a7-d6c3b461222e](https://user-images.githubusercontent.com/16410810/72525760-e6614c80-388a-11ea-848d-a1b376e604d1.jpg)

**Comment by minhcasi** [comment]
@visheshtennis - this cause the mismatch the bundle id of the app and the one that you config on Firebase, pls help to check this guide https://docs.inspireui.com/listapp/firebase/ or https://docs.expo.io/versions/latest/guides/using-firebase/

**Comment by visheshtennis** [comment]
Thanks for your constant support. I am finally able to publish and download the APK of 49.5 MB Size from the expo website. But I am facing trouble uploading it on google platform since it is giving a warning "Unoptimized APK" 

Warning:
This APK results in unused code and resources being sent to users. Your app could be smaller if you used the Android App Bundle. By not optimizing your app for device configurations, your app is larger to download and install on users' devices than it needs to be. Larger apps see lower install success rates and take up storage on users' devices.

Resolution:
Use the Android App Bundle to automatically optimize for device configurations, or manage it yourself with multiple APKs.


And Google is also not showing the button to publish the same. Could you please help me with publishing the app on Google play store? (Screenshot Attached)

![Screenshot 2020-01-27 at 12 03 40 AM](https://user-images.githubusercontent.com/16410810/73139863-7b88f000-4098-11ea-86e5-64e6608dc8c4.png)

I can share the admin credentials if you want.
