### ISSUE TITLE
Mstore-Expo showing same Rates even after chainging Currency Updated Version 3.9.7

### ISSUE THREAD

**Issue by onlineosman** [inspireui/support#1804]
![Showing same rates](https://user-images.githubusercontent.com/34172061/72206201-6a3ec180-34a4-11ea-84c6-9477d3e53352.png)

![Purchase proof for technical support](https://user-images.githubusercontent.com/34172061/72206211-83477280-34a4-11ea-861a-42350e277e3c.png)

**Comment by minhcasi** [comment]
@onlineosman - the Currency Switcher is only compatible with the WPML feature

https://wpml.org/documentation/related-projects/woocommerce-multilingual/multi-currency-support-woocommerce/

**Comment by onlineosman** [comment]
Fine, if i wan't to disable this feature! i already purchased woo commerce currency switcher, How can i disable multi-currency and keep only one Currency?

**Comment by minhcasi** [comment]
@onlineosman you can edit from common/config.dart and set only 1 value for default current - https://tppr.me/JFZVn instead of adding multi one - thank you!

**Comment by minhcasi** [comment]
or remove this line from the screens/settings.dart
