### ISSUE TITLE
[fluxstore] - 1.6.2 error in zone

### ISSUE THREAD

**Issue by ramyragab1** [inspireui/support#1805]
1. My issue: woocomerce shipping  zone not show & and i have multi city how can link city to zone 
for ex 
i have city1 shiping cost 10$ 
city2 shiping cost 15$ 
city3 shiping cost 20$ 
how i link if user type city1 and i want to show shiping cost 10$

3. Proof of my purchased: https://www.dropbox.com/s/hk4b3zm5sq7dhu0/Screen%20Shot%202020-01-11%20at%205.02.03%20PM.png?dl=0

3. Config files (optional)
https://www.dropbox.com/s/runql9nb0imopwn/config.dart?dl=0

**Comment by Senior-Gamal** [comment]
i have the same problem

**Comment by minhtruong315** [comment]
@ramyragab1 Add my skype: minhtruong315
I will help u check it via teamviewer
Thanks

**Comment by ramyragab1** [comment]
> @ramyragab1 Add my skype: minhtruong315
> I will help u check it via teamviewer
> Thanks

ok iwill add you

**Comment by minhtruong315** [comment]
@ramyragab1 I dont see you message me on skype.

**Comment by minhtruong315** [comment]
The shipping methods based on country and zip code. it's not based on city.

**Comment by ramyragab1** [comment]
i now add you in skype 
but we didnt use zip code in egypt 
can i auto fill when i use map adress and i will add zip code in woocomerce
