### ISSUE TITLE
[EXPO  MSTORE] -  V 3.9.7 (latest) SyntaxError:/src/components/LogoSpinner/index.js:

### ISSUE THREAD

**Issue by kiamoz** [inspireui/support#1806]
😢😢😢😢

SyntaxError: /Users/kiamoz/Documents/atc6/src/components/LogoSpinner/index.js: Support for the experimental syntax 'decorators-legacy' isn't currently enabled (10:1):

   8 | import { Config, withTheme } from "@common";
   9 | 
> 10 | @withTheme
     | ^
  11 | class LogoSpinner extends React.Component {
  12 |   constructor(props) {
  13 |     super(props);

<img width="1107" alt="Screen Shot 2020-01-11 at 7 51 06 PM" src="https://user-images.githubusercontent.com/10494372/72207204-f7d1df80-34ab-11ea-97d2-f6ebf58486ec.png">

**Comment by luyx2412** [comment]
Hi @kiamoz Please provide the screenshot your purchase on Evanto market.

Thanks

**Comment by kiamoz** [comment]
hello I'm old one . 
[42316561-beostore-complete-react-native-template-for-ecommerce-license.pdf](https://github.com/inspireui/support/files/4052241/42316561-beostore-complete-react-native-template-for-ecommerce-license.pdf)

**Comment by kiamoz** [comment]
just help me  please it's last ver

**Comment by luyx2412** [comment]
Hi @kiamoz Can you clean the project and reinstall the library. Maybe some caches cause this problem.

P/S: Feel free to reopen the issue.

Thanks.

**Comment by kiamoz** [comment]
nothing changed !

I install new one 
Unable to resolve "reactotron-react-native" from "src/store/configureStore.js"

after install reactotron , @luyx2412  get same err , did you test last ver ?

**Comment by luyx2412** [comment]
Hi @kiamoz Please make sure you reinstall with `yarn install`, follow your issue related did not install library. Or you can use `yarn add reactotron-react-native`

Thanks

**Comment by kiamoz** [comment]
Yarn work with expo , or its just for Pro ? @luyx2412  thanks

**Comment by luyx2412** [comment]
Yarn is library management of javascript which look like npm. https://yarnpkg.com/lang/en/. So you can use yarn both expo and Pro.

**Comment by kiamoz** [comment]
![Screen Shot 2020-01-14 at 9 16 27 PM](https://user-images.githubusercontent.com/10494372/72368351-26052880-3713-11ea-8533-98103c6ef378.png)

what happen next ? @luyx2412

**Comment by kiamoz** [comment]
@luyx2412  it's works thanks
