### ISSUE TITLE
[mstore-3.9.7] - "react-native run-android"  OneSignal Error

### ISSUE THREAD

**Issue by dogaisik** [inspireui/support#1808]
Task :app:processDebugManifest FAILED

C:\Users\user\Desktop\example android\mstore-3.9.7\mstore-pro\android\app\src\
debug\AndroidManifest.xml Error:
        Attribute meta-data#onesignal_app_id@value at AndroidManifest.xml requir
es a placeholder substitution but no value for <onesignal_app_id> is provided.
C:\Users\user\Desktop\example android\mstore-3.9.7\mstore-pro\android\app\src\
debug\AndroidManifest.xml Error:
        Attribute meta-data#onesignal_google_project_number@value at AndroidMani
fest.xml requires a placeholder substitution but no value for <onesignal_google_project_number> is provided.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.

when ı type "react-native run-android" command to run app on android device, ı got this error. 

![proof_of_my_purchase](https://user-images.githubusercontent.com/59788191/72217782-ecca8e00-3543-11ea-9209-0b708bf507cb.PNG)

**Comment by luyx2412** [comment]
Hi @dogaisik Can you send me more detail issue? Maybe take screenshot or send me the log file.

Thanks

**Comment by dogaisik** [comment]
[error_log.txt](https://github.com/inspireui/support/files/4054511/error_log.txt)

**Comment by luyx2412** [comment]
Hi @dogaisik i saw the message about `Attribute meta-data#onesignal_google_project_number@value at AndroidManifest.xml requires a placeholder substitution but no value for <onesignal_google_project_number> is provided.` So you lack of one signal config, please read the docuemnt https://docs.inspireui.com/mstore/push-notification/ to config one signal.

P/S: Feel free to reopen the issue.

Thank.
