### ISSUE TITLE
[Fluxstore MV] - ADD PRODUCT

### ISSUE THREAD

**Issue by yassiney120** [inspireui/support#1809]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
I cant add product
2. Screenshots issues:

https://ibb.co/dDRd4jb

3. Proof of my purchased:

https://ibb.co/4Z4L8GB

3. Config files (optional)

**Comment by incepio-flutter** [comment]
f

**Comment by yassiney120** [comment]
Hi, any news

**Comment by minhcasi** [comment]
@minhtruong315  - please help for investigating - thank you!

**Comment by minhtruong315** [comment]
@yassiney120  Add my skype: minhtruong315
I will help u check it via teamviewer
Thanks

**Comment by yassiney120** [comment]
Thank you for your reply i just send you my teamviewer it will be available for 24/24h 
From live:.cid.914f9e76a183d9d4
Email: mohdar@fleure.ma

**Comment by yassiney120** [comment]
Im waiting your confirmation

**Comment by minhtruong315** [comment]
supported
