### ISSUE TITLE
[BeoNews] app loaded indefinitely when we attempted to log in with Facebook on ios

### ISSUE THREAD

**Issue by mustymx** [inspireui/support#181]
Purchased Code: 1b52b00e-c084-4e29-bac7-13383204401d

config.js:
  // config for log in by Facebook
  Facebook: {
    showAds: false,
    adPlacementID: '',
    logInID: '513825405780342',
    sizeAds: 'standard', // standard, large
  },

![cargafalla](https://user-images.githubusercontent.com/16863247/51076993-6bf16180-1665-11e9-82b2-c46877683288.png)

**Comment by mustymx** [comment]
some answer?

**Comment by minhcasi** [comment]
Hi, sorry for the delay - we are working on the issue and this issue is kind of hard to reproduce - we will update in 1-2 days, thank you! @luyx2412

**Comment by luyx2412** [comment]
Hi @mustymx Which Beonews version do you use? (Expo or Pro)

Thanks

**Comment by mustymx** [comment]
I use Pro version


> Hi, sorry for the delay - we are working on the issue and this issue is kind of hard to reproduce - we will update in 1-2 days, thank you! @luyx2412 
your beofoods demo app has the same issue in iOS

**Comment by minhcasi** [comment]
To fix this issues go to RCTFBSDK.xcodeproj then build settings->framework search paths. And change ~/Documents/FacebookSDK to $(HOME)/Documents/FacebookSDK

<img width="1199" alt="screen shot 2019-01-24 at 7 06 25 pm" src="https://user-images.githubusercontent.com/1459805/51677183-50923900-200b-11e9-85fc-78ec63d2dbb3.png">
