### ISSUE TITLE
Problem linking FLUX NEWS to my wordpress website 

### ISSUE THREAD

**Issue by sharkcrypto92** [inspireui/support#1811]
on this page 
https://docs.inspireui.com/fluxnews/getting-started/

5. Setup FluxNews
After config your website with above plugins then it's time to connect it with the FluxNews app.

Open lib/common/config.dart and change the info from serverConfig section:

`/// Server config
const serverConfig = {
  "url": "http://news.inspireui.com",
  "forgetPassword": "http://news.inspireui.com/wp-login.php?action=lostpassword"
};`

i added my website links + i uploaded the plugins 

but when i load the app doesnt shows my website posts

**Comment by minhcasi** [comment]
Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads  it's used to verify your proof of purchase? sorry for any inconvenience - Thank you!

**Comment by sharkcrypto92** [comment]
sure https://ibb.co/J2N5GwT

**Comment by sharkcrypto92** [comment]
ARE YOU GOING TO GUIDE ME  ?

**Comment by dttrung26** [comment]
Hi @sharkcrypto92 ,
would you mind sending me your /lib/common folder as well as administrator access to your website to take a look? Thank you for your patient and co-operation!
Have a nice day btw!

**Comment by sharkcrypto92** [comment]
sure thats the folder zip 
https://easyupload.io/cfp44y

and my worpress admin panel is 

username : admin
password : Saad556070

http://alriadey.com/wp-admin

**Comment by sharkcrypto92** [comment]
can you please delete my information of my website when you see it i dont want it to show to public

**Comment by dttrung26** [comment]
Hi @sharkcrypto92 , 
could you please send me your admin access via trung@inspireui.com? I lost your previous message. Sorry for any inconvenience may cause.

**Comment by sharkcrypto92** [comment]
sent

**Comment by sharkcrypto92** [comment]
am waiting for reply to guide me

**Comment by sharkcrypto92** [comment]
i bought this app because no need for coding knowledge if your going to take so long for respond or not replying to me let me know i ve been waiting for 2 days so far

**Comment by sharkcrypto92** [comment]
The demo app on google play is broken too

**Comment by minhcasi** [comment]
hi, it's working it my testing, could i know if you are using the latest version on google play - pls try to remove and reinstall the app again - thank you!

**Comment by sharkcrypto92** [comment]
you kept me waiting all that long and respond for your Demo app ???

i want refund for my app i dont want this kind of support its waste time to me its worthless

**Comment by sharkcrypto92** [comment]
the app not showing my post my website is for news not for products 

it shows cat names and no post

**Comment by sharkcrypto92** [comment]
> [trung@inspireui.com](mailto:trung@inspireui.com)

i have sent emails to you and no responds

**Comment by minhcasi** [comment]
@sharkcrypto92 - sorry for the issue, you could refund on this link if could not use the product - https://help.market.envato.com/hc/en-us/articles/202821460-Can-I-Get-A-Refund- - thank you!

**Comment by sharkcrypto92** [comment]
> @sharkcrypto92 - sorry for the issue, you could refund on this link if could not use the product - https://help.market.envato.com/hc/en-us/articles/202821460-Can-I-Get-A-Refund- - thank you!
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/443a6d8797ad7ce5ef6058b89b52b36e16159254/68747470733a2f2f7468656d652e7a646173736574732e636f6d2f7468656d655f6173736574732f3437303439302f306661636133623030643936306165373762643239343435363838613061343365313437353164372e737667">Envato Market Help Center**[Envato Market Help Center](https://help.market.envato.com)**Envato Market is a collection of themed marketplaces, where creatives sell digital assets to help bring your ideas to life. Visit our dedicated Help Center for Envato Market.

i dont want refund if you going to help me with this app howcome i will use it if its not working with me

**Comment by minhcasi** [comment]
@sharkcrypto92 - send patching to your email 

Hi, there are some reasons that cause hidden from the categories API http://alriadey.com/wp-json/wp/v2/categories - if you could fix this endpoint then the app will work as normal
