### ISSUE TITLE
[BeoNews] - Unable to render custom script 

### ISSUE THREAD

**Issue by dermayank** [inspireui/support#1812]
What we are trying to achieve is to show/display the content of a custom script on the Beonews app homepage.
Ex:
![Screenshot from 2020-01-12 22-08-14](https://user-images.githubusercontent.com/24271097/72222195-2f15be80-3588-11ea-9555-cbc233af6b28.png)

Here we are using a script provided by hotels combined to show the hotel booking options on the basis of the dates.
_This is an example script:_ `<script src="https://sbhc.portalhc.com/171373/searchbox/475520"></script>`

_**What we basically want to know is  whether there's any component which can render custom script or how to display custom scripts like above in the app.**_

Proof of purchase:
![Screenshot from 2019-12-04 10-30-36](https://user-images.githubusercontent.com/24271097/72222255-acd9ca00-3588-11ea-9ca1-007e44b0c4e6.png)

**Comment by minhcasi** [comment]
@dermayank - you can try to write you own Webview to display these script and HTML code via iframe 

i'm not sure if this component could be help - https://github.com/archriss/react-native-render-html
