### ISSUE TITLE
[fluxstore] - issues and requests

### ISSUE THREAD

**Issue by ajnaf** [inspireui/support#1813]
My issue: 
first issue is the review doesn't work on latest update.
second : i want to get the shipping methods based on the shipping zone not country or postcode.
third : i want to add new fields to the checkout i used  a plugin called checkout manager it works fine on the word press i want to know how to add the fields to the api .
forth : i want notifications for the orders .

**Comment by minhcasi** [comment]
Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads  it's used to verify your proof of purchase? sorry for any inconvenience - Thank you!

**Comment by ajnaf** [comment]
![image](https://user-images.githubusercontent.com/31656833/72237538-8137fd80-35e3-11ea-8706-8b8b62fe0751.png)

**Comment by ajnaf** [comment]
@minhtruong315  i solved first and second

**Comment by minhcasi** [comment]
@ajnaf  - the #3 and #4 issues is an advanced feature that we the current release is not ready to support - if you have any solution please suggest us

**Comment by minhcasi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Notify when updating Order](https://trello.com/c/kp4rqktm/11-notify-when-updating-order)

**Comment by minhcasi** [comment]
moved to the Feature request board
