### ISSUE TITLE
[Mstore Pro] Banner sale

### ISSUE THREAD

**Issue by winchai** [inspireui/support#1814]
How banner sale work? how do i set countdown timer in app? theres no reference in your documentation
![image](https://user-images.githubusercontent.com/58699787/72232410-9c126e00-35f3-11ea-85c2-9dc596246843.png)

**Comment by luyx2412** [comment]
Hi @winchai Currently we did not have banner document. We will improve document later. So i will support you config the banner sale. You mean you want to set time slide in banner?

**Comment by winchai** [comment]
![image](https://user-images.githubusercontent.com/58699787/72311878-bfebb780-36b8-11ea-9cac-39c0bb8786d1.png)

yes i want to make it so that the flash sale have time countdown , just like what you guys advertise

**Comment by winchai** [comment]
hi @luyx2412 , can you help me with this?
here is my config and app config
https://github.com/inspireui/support/files/4062781/common.zip

**Comment by luyx2412** [comment]
Hi @winchai 
This is an example AppConfig.json to open banner sale. 
[AppConfig.json.zip](https://github.com/inspireui/support/files/4082311/AppConfig.json.zip)

P/S: Feel free to reopen the issue.

Thanks
