### ISSUE TITLE
[fluxstore] - Connection between (fluxstore) and my (woo-commerce) website

### ISSUE THREAD

**Issue by limitlessfirm** [inspireui/support#1815]
1. My issue: I can't make Connection between (fluxstore) and my (woo-commerce) website 

The videos in your channel different of your website documentation and i saw error when i made that 

please give me steps to make Connection between (fluxstore) and my (woo-commerce) website
![screenshot](https://user-images.githubusercontent.com/59250639/72236863-27cecf00-35e1-11ea-9241-a01a3b10c28f.JPG)

**Comment by minhcasi** [comment]
@limitlessfirm - pls check this video guide for the detail - https://www.youtube.com/watch?v=Q8Q3ywiiV9g&t=527s

What you need to do is change the common/config.dart file - update the URL to link to your website (please note your website should install some required plugins as clarify from video and document https://docs.inspireui.com/fluxstore/woocommerce-setup )
