### ISSUE TITLE
Fluxstore opencart error

### ISSUE THREAD

**Issue by epkim** [inspireui/support#1817]
1. My issue:
  Log -> Failed assertion: boolean expression must not be null
  When i click the item in products, it iwll shows this screen.

2. Screenshots issues:
![Screenshot_2020-01-13-21-38-09](https://user-images.githubusercontent.com/35923457/72256947-c98c0580-364d-11ea-9f66-efede3c294bc.png)

3. Proof of my purchased:
![1](https://user-images.githubusercontent.com/35923457/72257347-c9403a00-364e-11ea-976e-eb72bef20d7a.png)

3. Config files (optional)
[common.zip](https://github.com/inspireui/support/files/4053601/common.zip)

**Comment by vumanhsn97** [comment]
Please check in the last version. I don't find your problem 
![Simulator Screen Shot - iPhone 11 Pro - 2020-01-14 at 09 51 54](https://user-images.githubusercontent.com/39208623/72310171-a6943c80-36b3-11ea-82e2-0697c7af51c9.png)

**Comment by epkim** [comment]
@vumanhsn97 What version of flutter do you use?

**Comment by vumanhsn97** [comment]
@epkim stable version 1.12.13+hotfix.5

**Comment by epkim** [comment]
It doesn't work.

Can you provide those files?

I beg you.

**Comment by vumanhsn97** [comment]
@epkim You just download new version in envato
