### ISSUE TITLE
FluxStore Listing - Conflict between the puguins ListApp Mobile Manager and Mstore API

### ISSUE THREAD

**Issue by danimmg** [inspireui/support#1819]
Cannot be enabled together as it gives error

Fatal error: Cannot redeclare registerJsonApiController() (previously declared in /var/www/clients/client0/web27/web/wp-content/plugins/json-api/mstore-api.php:104) in /var/www/clients/client0/web27/web/wp-content/plugins/listapp-mobile-manager/listapp-manager.php on line 226

![Proof of my purchased](https://user-images.githubusercontent.com/59834619/72276202-2cf64300-360e-11ea-8ce9-f00b90551aba.jpg)

**Comment by minhcasi** [comment]
@danimmg - pls only use the ListApp Mobile Manager plugin, the mstore-api is not required for FluxstoreListing

**Comment by codingastronaut** [comment]
but it is requred, because you cant sign in without the mstore api
and you cant activate the api without the plugin, please help
