### ISSUE TITLE
FluxStore Listing - fluxstore-api-2

### ISSUE THREAD

**Issue by danimmg** [inspireui/support#1820]
In the manual you are asked to enable this in the wordpress menu but there is no such option

Enable listing api
Go to Tools / REST API Controller and enable listing.
fluxstore-api-2

![error](https://user-images.githubusercontent.com/59834619/72276586-05ec4100-360f-11ea-94f7-7f6513dcea78.jpg)
![Proof of my purchased](https://user-images.githubusercontent.com/59834619/72276587-05ec4100-360f-11ea-8b52-fd186d550ac0.jpg)

**Comment by minhcasi** [comment]
pls hep to create one ticket for your all issues, that will help us check all for one time, instead of creating multi one - thank you!

@vumanhsn97 - pls also check the issues from #1821 #1822

**Comment by vumanhsn97** [comment]
@danimmg Can you send your website url and account login to vumanhsn97@gmail.com?

**Comment by danimmg** [comment]
Hello
I already sent the credentials to your email
Thanks for your help and patience but I still can not show the ads and categories in the app, already called everything in the menu wp rest api controller and already put the categories in config dart and json

I don't understand why the site is not communicating with the app
The error still appears:
type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'String'

Thanks

**Comment by danimmg** [comment]
Hello
You are now showing categories and images but when you click on categories you do not show ads in that category
![Capture15-01-2020-10 28 10](https://user-images.githubusercontent.com/59834619/72441349-48d22400-3789-11ea-9d3b-bc3e27833002.jpg)
![Capture15-01-2020-10 28 33](https://user-images.githubusercontent.com/59834619/72441351-48d22400-3789-11ea-99c8-00853b1718dc.jpg)
![Capture15-01-2020-10 29 22](https://user-images.githubusercontent.com/59834619/72441352-48d22400-3789-11ea-82e3-85f45e29db55.jpg)

**Comment by danimmg** [comment]
[lib.zip](https://github.com/inspireui/support/files/4066339/lib.zip)

Folder lib

**Comment by codingastronaut** [comment]
i also have the same issue, i cant find the mstore user under the json api

**Comment by vumanhsn97** [comment]
@codingastronaut Can you share your account and website to vumanhsn97@gmail.com?

**Comment by danimmg** [comment]
I can't enable blogging on the app homepage.

The page has the code
-------------------------------------
  {
      "name": {
        "en": "Blog",
        "ar": "???? ?????",
        "vi": "Tìm ki?m"
      },
      "layout": "blog"
    },
---------------------------------------------------
What I have to do to enable and show posts

**Comment by vumanhsn97** [comment]
@danimmg 
from version 1.6.0. We update config.json so you need to change to {
"name": "This is name of blog layout",
"layout": "blog"
}
