### ISSUE TITLE
FluxStore Listing - app does not communicate with website

### ISSUE THREAD

**Issue by danimmg** [inspireui/support#1821]
I perfectly followed the guidelines
https://docs.inspireui.com/fluxstore/config/

https://www.youtube.com/watch?v=y55AqAEEp8M&list=PLcF-HiQy-OJAD8btGgr_CHcUmYyN8GgY&index=10

https://www.youtube.com/watch?v=abMi8JYurpM&list=PLcF-HiQy-jOJAD8btGgr_CHcUmYyN8GgY&index=11

But the app can't communicate with the website, doesn't show ads and categories
![Capture11-01-2020-09 40 51](https://user-images.githubusercontent.com/59834619/72276963-d4c04080-360f-11ea-91fc-7bcf263e4f00.jpg)
![Capture11-01-2020-09 41 01](https://user-images.githubusercontent.com/59834619/72276964-d558d700-360f-11ea-83eb-54b559426763.jpg)
![Proof of my purchased](https://user-images.githubusercontent.com/59834619/72276965-d558d700-360f-11ea-8fa5-a10a68665daa.jpg)

**Comment by minhcasi** [comment]
moved to #1820 - pls hep to create one ticket for your all issues, that will help us check all for one time, instead of creating multi one - thank you!
