### ISSUE TITLE
[fluxstore] - apple login button

### ISSUE THREAD

**Issue by raiedahmed** [inspireui/support#1822]
Guideline 4.0 – Design

We noticed an issue in your app that contributes to a lower quality user experience than Apple users expect:

- Your app uses Sign in with Apple as a login option but still does not use Sign in with Apple button design, branding and/or user interface elements appropriately as described in the Sign in With Apple Human Interface Guidelines.

Next Steps

To resolve this issue, please revise your app to address all instances of this type of issue.

Resources

For information on improving and enhancing your app:

- Watch the video The Ingredients of Great Apps to understand the basics of great apps. - Watch the video iPhone and iPad User Interface Design for practical design tips. - Watch iOS Development Videos to learn about programming and design tips. - Review the iOS Human Interface Guidelines and ensure that your app’s interface and design adhere to these guidelines.

Please see attached screenshots for details.

https://ibb.co/GkZsqMk

**Comment by raiedahmed** [comment]
Purchase app

https://ibb.co/8XVC0gk

**Comment by minhcasi** [comment]
moved to #1820 - pls hep to create one ticket for your all issues, that will help us check all for one time, instead of creating multi one - thank you!

**Comment by raiedahmed** [comment]
My app
Fluxstore 
Not fluxstore listing

**Comment by minhcasi** [comment]
pls note that we will redesign the apple-sign in button on next 1.6.3  - thank you!
