### ISSUE TITLE
flux store -1.6.2 issue

### ISSUE THREAD

**Issue by Senior-Gamal** [inspireui/support#1823]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
Could you declare clear steps to setup google sign in method , please ? We are getting this error "platfromException(sign_in_failed , com.google.android.gms.common.api.ApiException : 10: , null )" .we also need to enable orders page for guest users to see there orders if they are not authenticated
thanks for your time

2. Screenshots issues:
![1](https://user-images.githubusercontent.com/27568540/72286553-07892980-364e-11ea-8a86-1cd69d16ecfc.png)
![2](https://user-images.githubusercontent.com/27568540/72286554-0821c000-364e-11ea-91be-c8bfda775f56.png)

3. Proof of my purchased:
https://user-images.githubusercontent.com/27568540/71651886-b6159c00-2d29-11ea-9892-41ad518dc615.jpeg
3. Config files (optional)

**Comment by Senior-Gamal** [comment]
another issue in product page 
![3](https://user-images.githubusercontent.com/27568540/72334688-67bbb200-36c6-11ea-975b-bf0603014f59.jpeg)

**Comment by minhcasi** [comment]
@Senior-Gamal - could you help to check some document config here if is there missing - https://pub.dev/packages/google_sign_in

**Comment by Senior-Gamal** [comment]
> another issue in product page
> ![3](https://user-images.githubusercontent.com/27568540/72334688-67bbb200-36c6-11ea-975b-bf0603014f59.jpeg)

and the issue ?

**Comment by minhtruong315** [comment]
@Senior-Gamal  Add my skype: minhtruong315
I will help u check it via teamviewer
Thanks

**Comment by roziseth01** [comment]
guys, i have the same issue. cant you just post the solution here?

**Comment by minhtruong315** [comment]
replace screens/detail/review.dart to fix issue product page
[review.dart.zip](https://github.com/inspireui/support/files/4082841/review.dart.zip)

**Comment by roziseth01** [comment]
Hi,
Juz check you can review and post. But when u open back you review it comes
this issue.
