### ISSUE TITLE
BeoNews Pro - React Native Version Mismatch

### ISSUE THREAD

**Issue by julianurrahmani** [inspireui/support#1824]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

**1. My issue:**

I always get this error **"React Native version mismatch"** after running **react-native run-android**. I didn't change any configuration in your files (BeoNews Pro). After extracting the zip file, I only changed the _sdk_ location on **local.propertise** to my own location before run it. I have tried to reset cache in project folder with this code **"yarn cache-clean",** removed the node_modules and rebuilt it with "**yarn install".**  I also tried to open the project into Android Studio, but I still got the error.

**2. Screenshots issues:**

![Screenshot_1578950066](https://user-images.githubusercontent.com/39922187/72293160-e34d3d00-368d-11ea-84ef-7d5afb6fc3b5.png)

![Screenshot (189)](https://user-images.githubusercontent.com/39922187/72293185-f3651c80-368d-11ea-8dc9-0762a56452ee.png)

**3. Proof of my purchased:**

![Screenshot (188)](https://user-images.githubusercontent.com/39922187/72293222-037cfc00-368e-11ea-8b67-1aada2d78e14.png)

**3. Config files (optional)**
-

**Comment by luyx2412** [comment]
Hi @julianurrahmani Because the latest version is React native 0.61.5. So you can try the guide to clean your project https://brucelefebvre.com/blog/2019/09/30/react-native-version-mismatch/.

P/S: Feel free to reopen the issue.

Thanks
