### ISSUE TITLE
[Mstore Pro] Firebase SMS Login Configuration

### ISSUE THREAD

**Issue by winchai** [inspireui/support#1825]
how to apply new Firebase SMS login update? i downloaded google-service.json and put it in android app root folder and looks like nothing happen

**Comment by minhcasi** [comment]
noted for updating new document - thanks

**Comment by winchai** [comment]
so when you guys updating your document? or you can guide me here , i'm waiting for you guys everyday

![image](https://user-images.githubusercontent.com/58699787/72493216-c150e780-3852-11ea-9510-9b688d65d128.png)
