### ISSUE TITLE
[Mstore Pro] App Error when changing Layout

### ISSUE THREAD

**Issue by winchai** [inspireui/support#1827]
Hi theres an error when changing layout
the app was working fine when at the start
![image](https://user-images.githubusercontent.com/58699787/72314251-bcf4c500-36c0-11ea-8190-f11a5b97a215.png)

but when i change the layout to 6 available layout
![image](https://user-images.githubusercontent.com/58699787/72314264-ce3dd180-36c0-11ea-8918-e399f8b86331.png)

this error came out
![image](https://user-images.githubusercontent.com/58699787/72314282-e4e42880-36c0-11ea-8ca5-c532bb24bc12.png)

please help

**Comment by minhcasi** [comment]
Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads  it's used to verify your proof of purchase? sorry for any inconvenience - Thank you!

**Comment by winchai** [comment]
![image](https://user-images.githubusercontent.com/58699787/72362318-8b621500-3725-11ea-974c-85632ef1893f.png)

**Comment by minhcasi** [comment]
@winchai - could you help to share the config file as well, we will help for checking - thank you!

**Comment by winchai** [comment]
[common.zip](https://github.com/inspireui/support/files/4062781/common.zip)
thats mine app config and config file as well

**Comment by luyx2412** [comment]
Hi @winchai 
We will fix in next version. So you can replace the code to fix the issue.
In `src/components/PostLayout/index.js` line 44. And replace `      imageURL =
        typeof data.images !== "undefined"
          ? getProductImage(data.images[0].src, image_width)
          : "";` to `      imageURL =
        data.images && data.images.length
          ? getProductImage(data.images[0].src, image_width)
          : "";`

P/S: Feel free to reopen the issue.

Thanks
