### ISSUE TITLE
[Fluxstore-MV] - Payment Page Turns Blank

### ISSUE THREAD

**Issue by saifmuhtar** [inspireui/support#1828]
I'm using ToyyibPay as my woocommerce's payment gateway. And it's running smoothly on the website. 
But I'm having trouble on mobile app. 
After I clicked PLACE MY ORDER button on the checkout, it will turns into blank page. 
Please refer the attachment below:
![Screenshot_20200114_173648_com inspireui fluxstore midnight](https://user-images.githubusercontent.com/34681804/72332976-f72c8980-36f5-11ea-9a97-2c011a78cb36.jpg)

This blank page should appear the payment gateway page:
![Screenshot_20200114_173632_com inspireui fluxstore midnight](https://user-images.githubusercontent.com/34681804/72333001-03184b80-36f6-11ea-866f-0b0a69f3fba4.jpg)

This is proof of purchase:

![Screenshot_20200114_174336_com android chrome](https://user-images.githubusercontent.com/34681804/72332982-fc89d400-36f5-11ea-9307-f8c418404111.jpg)

**Comment by minhcasi** [comment]
@saifmuhtar - thank you for reporting, could you help share the config files from common folder so that we could help for debugger - if it could not be public pls send to support@inspireui.com and truong@inspireui.com

@minhtruong315 - pls help for checking the issue with high priority - thank you!

**Comment by saifmuhtar** [comment]
@minhcasi @minhtruong315 
I sent the config files via email. Please check it.
Thank you.

**Comment by minhtruong315** [comment]
@saifmuhtar  Add my skype: minhtruong315
I will help u check it via teamviewer
Thanks

**Comment by saifmuhtar** [comment]
@minhtruong315 Noted.

**Comment by minhtruong315** [comment]
supported

**Comment by saifmuhtar** [comment]
I'm developing a multi vendor website. To have this great product is very helpful to me.
This great products also comes with an EXCELLENT customer support from InspireUI team, @minhcasi  especially thanks to Nguyen Minh Truong, @minhtruong315 
I need to integrate a new local payment gateway with MStore. This is a difficult task and take several days to solve. But they are so passion to give the best support to their customer and I'm so thankful to them.
Please keep your awesome job and I hope a great future for all of you.
Highly Recommended, 5 Stars! 🌟🌟🌟🌟🌟

![Screenshot 2020-01-17 at 4 32 21 PM](https://user-images.githubusercontent.com/34681804/72596441-fc344780-3946-11ea-8876-b43f1072219c.png)
