### ISSUE TITLE
| App Cestore | Push Notification not sending

### ISSUE THREAD

**Issue by theleolife** [inspireui/support#183]
**Required Info (please complete the following information):**
 - Product: [e.g. MStore, ListApp]
 - Your Purchased Code: [get from https://codecanyon.net/downloads]
(we may not reply if you are not our customer)

 I published App Cestore android for test notification but it seems not sending notification, it is shows up 504 (Gateway Time-out) like from image below

![screen shot 2019-01-13 at 18 02 41](https://user-images.githubusercontent.com/3028163/51090072-91619680-175d-11e9-8625-932bcd9ae5bf.png)

**Comment by minhcasi** [comment]
fixed on v.1.3 - please download the latest - thanks
