### ISSUE TITLE
[MStore Pro] - App is too slow also 2 pages got crashed.

### ISSUE THREAD

**Issue by Hayko1994** [inspireui/support#1830]
There are several issues that I am getting in this project.
1. The contact page is not opening at all
2. The performance of the app is too poor. It takes almost a half-minute to take any action. Is it because of development mode or I should change something in the config?
3. After placing API details Home page look like this:

![82025050_624216255003365_7602319863150804992_n](https://user-images.githubusercontent.com/22639899/72343947-867f7000-36e9-11ea-8e25-8dad6c1f221b.png)

As you see the first column is inside the top bar and the header image slider is not visible at all.
From where can I bring back that header image slider that's visible in your Demo and fix that first column-style issue? 

Here are the images that prove I bought the template.
![screenshot-codecanyon net-2020 01 (1)](https://user-images.githubusercontent.com/22639899/72344125-ec6bf780-36e9-11ea-9731-0b108522a735.png)
![screenshot-codecanyon net-2020 01](https://user-images.githubusercontent.com/22639899/72344127-ec6bf780-36e9-11ea-8918-eb4e2089d4b8.png)

**Comment by minhcasi** [comment]
@Hayko1994 - could i know your username on Envato or please give the comment on https://codecanyon.net/item/beostore-complete-react-native-template-for-ecommerce/17010642 - thank you !

**Comment by Hayko1994** [comment]
@minhcasi just wrote a comment there and username is Hayko94

**Comment by luyx2412** [comment]
Hi @Hayko1994 
So can you take a screenshot your evanto account?

Thanks

**Comment by minhcasi** [comment]
https://tppr.me/y71N1 verified purchase - thank you!

**Comment by Hayko1994** [comment]
@minhcasi so how can these issues be fixed?

**Comment by Hayko1994** [comment]
@luyx2412  @minhcasi so how can these issues be fixed?

**Comment by minhcasi** [comment]
@Hayko1994 - is it possible to zip your source and send back us for checking - pls send to support@inspireui.com - with subject related to this ticket - thank you for your patient

**Comment by Hayko1994** [comment]
@minhcasi I sent project few days ago. Are there any updates for these issues?

**Comment by luyx2412** [comment]
Hi @Hayko1994 Please send your source to luyxtrab264@gmail.com

Thanks

**Comment by luyx2412** [comment]
Hi @Hayko1994 
- You can replace your contact in `src/common/Config.js` line 190 
![image](https://user-images.githubusercontent.com/8909619/73663531-59aeef00-46d0-11ea-8ac4-20c3904b57f5.png)
- In next version we will improve performance and add slider in home page

P/S: Feel free to reopen the issue.

Thanks
