### ISSUE TITLE
[Fluxstore AndroidManifest Error] - 

### ISSUE THREAD

**Issue by Saifahmad99** [inspireui/support#1831]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: There is an error in my Android Manifest Page i cant run the app. 

2. Screenshots issues:
![Screenshot (22)](https://user-images.githubusercontent.com/59877416/72353324-e71ea500-3709-11ea-847f-9cbf5fd78fd1.png)

3. Proof of my purchased:
[IVIP35448475.pdf](https://github.com/inspireui/support/files/4059681/IVIP35448475.pdf)

3. Config files (optional)

**Comment by minhcasi** [comment]
@trunghieuvn - pls help for checking

**Comment by Saifahmad99** [comment]
I dont understand what you said could you please describe.

**Comment by Saifahmad99** [comment]
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.celkart.store">
    
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.SEND_SMS"/>
    
    <application
        android:name="com.celkart.store.MainActivity"
        android:label="Celkart Store"
        android:icon="@mipmap/launcher_icon">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            
            <meta-data
                android:name="io.flutter.app.android.SplashScreenUntilFirstFrame"
                android:value="true" />
            <meta-data android:name="com.google.android.geo.API_KEY"
                android:value="your-google-api-key-here"/>
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
            <intent-filter>
                <action android:name="FLUTTER_NOTIFICATION_CLICK" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
            <intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.BROWSABLE"/>
                <data android:scheme="http" android:host="demo.mstore.io"  android:pathPrefix=""/>

            </intent-filter>
            <intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.BROWSABLE"/>
                <data android:scheme="fluxstore" android:host="inspireui.com" android:pathPrefix=""/>
            </intent-filter>


        </activity>
        <meta-data
            android:name="com.facebook.sdk.ApplicationId"
            android:value="@string/fb_app_id" />
        <meta-data
            android:name="com.facebook.accountkit.ApplicationName"
            android:value="@string/app_name" />
        <meta-data
            android:name="com.facebook.accountkit.ClientToken"
            android:value="@string/ak_client_token" />
        <meta-data
            android:name="com.google.android.geo.API_KEY"
            android:value="@string/api_key"/>
        <meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="@string/admob_api"/>
    </application>
</manifest>

**Comment by Saifahmad99** [comment]
This is my code

**Comment by minhcasi** [comment]
@Saifahmad99 - I'm sorry for the late response on this ticket as my guy has been off - pls help to check the guide for change the bundle id on Android base on this guide - https://docs.inspireui.com/fluxstore/customization/#1-app-nameicon-bundle-id

1.2 Change the app Bundle ID:
Android app: Search on android folder and replace the following file - https://tppr.me/bWCvp

android/app/build.gradle
android/app/src/main/AndroidManifest.xml
android/app/src/main/kotlin/com/inspireui/fluxstore/MainActivity.kt
Rename the folder android/app/src/main/kotlin/com/inspireui/fluxstore to your own bundle name, example: if you bunndle id is com.ins.flux, it will be android/app/src/main/kotlin/com/ins/flux
Please note that the file android/app/google-services.json should be changed to match your new bundle id. Otherwise the app will crash.

Also share us the "flutter doctor -v" on your window

**Comment by Saifahmad99** [comment]
i've done everything but still getting those error you can see the screenshots the read read area please help me and also can we connect on skype thanks

**Comment by minhcasi** [comment]
@Saifahmad99 - pls zip your source and send back to support@inspireui.com for checking - thanks

**Comment by minhcasi** [comment]
Also download latest 1.6.3 for fixing - thanks
