### ISSUE TITLE
[Fluxstore] - iOS Distribution issue

### ISSUE THREAD

**Issue by AndresReyesDev** [inspireui/support#1832]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:

I'm having trouble signing the iOS application. While the Android app is already up and running and on the Play Store, the iOS app I couldn't launch because I can't understand the signing process.

I'm stuck on the certificates, profiles and provisioning part. Is it possible to get a tutorial on all the steps to go into production on the App Store?

I explain: which certificates, profiles and provisioning have to be created and in what order, and finally what changes have to be made in xCode to move it to production and to be able to distribute the application. It would be very useful since I've spent 2 days lost trying to find out how to do it.

2. Screenshots issues:

<img width="989" alt="Screen Shot 2020-01-14 at 12 12 07" src="https://user-images.githubusercontent.com/5054870/72356023-48715480-36c7-11ea-9a38-a8475140982b.png">

3. Proof of my purchased:

<img width="1347" alt="Screen Shot 2020-01-14 at 12 14 58" src="https://user-images.githubusercontent.com/5054870/72356154-840c1e80-36c7-11ea-8747-c816a085071a.png">

3. Config files (optional)

**Comment by AndresReyesDev** [comment]
Hi, could someone take my support request, please? Only this step remains to distribute the iOS application and I'm stuck.  I appreciate your help.

**Comment by minhcasi** [comment]
@AndresReyesDev sorry for late response, please help to check this video to clarify the setting on appstore delivery - https://www.youtube.com/watch?v=-4e6eC_zBk4

**Comment by AndresReyesDev** [comment]
Thank you so much! Work like a charm…

**Comment by minhcasi** [comment]
@AndresReyesDev - thank you for confirm - we are glad that it helps.

Please help to share your final app if it is success publish to Appstore, also help us give rating/feedback to http://codecayon.net/downloads - appreciated for your help!
