### ISSUE TITLE
ListPro - Listing Directory React Native template

### ISSUE THREAD

**Issue by vipzinho** [inspireui/support#1833]
I bought the plugin to have an application from my site, but did not know that would have to understand programming.

I can not install the app. It gives error in all plugins and I have no idea what to do.

I wonder how you can help me.

**Comment by minhcasi** [comment]
Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads  it's used to verify your proof of purchase? sorry for any inconvenience - Thank you!
