### ISSUE TITLE
[mstore expo error 400] - 

### ISSUE THREAD

**Issue by kiamoz** [inspireui/support#1834]
I have  this error suddenly  from right now  ,  do you have idea  to fix  it ? I update my cli to  last-ver  
<img width="1139" alt="Screen Shot 2020-01-14 at 11 19 32 PM" src="https://user-images.githubusercontent.com/10494372/72379433-a6825400-3728-11ea-8e18-9f195560f2b8.png">

**Comment by luyx2412** [comment]
Hi @kiamoz Can you send me your Config.js and AppConfig.json?

Thanks

**Comment by kiamoz** [comment]
I cant run any init expo app  too , 

[Archive.zip](https://github.com/inspireui/support/files/4063088/Archive.zip)

**Comment by kiamoz** [comment]
@luyx2412  check it out please thanks

**Comment by luyx2412** [comment]
Hi @kiamoz 
You can reinstall old version expo based on this comment to fix the issue https://github.com/expo/expo-cli/issues/1069#issuecomment-538513937

P/S: Feel free to reopen the issue.

Thanks
