### ISSUE TITLE
[Fluxstore Multi Vendor - Flutter E-commerce Full App ] - Sign up not working 

### ISSUE THREAD

**Issue by Yaser81** [inspireui/support#1835]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
Sign up is not working

2. Screenshots issues:

https://drive.google.com/open?id=1XukdZn17HM0G56pFbsxFVg4NAWGPvVB7
but when I debugged my fluxstores multi vendor codes with VScode and I have  the  following error
https://drive.google.com/open?id=1BDBvCQ1oD8c1Ngsg4h0ASZI5l0KwTrAZ
which is 
body:"{"status":"error","error":"Invalid access, unverifiable 'nonce' value. Use the 'get_nonce' Cstatus":"error","error":"Invalid access, unverifiable 'nonce' value. Use the 'get_nonce' Core API method. "}"

although I installed all required plugins  
- MStore API latest version
- JSON API 
- wp jwt authentication plugin 
I did all required configuration for all like enable wp rest ap, and generate keys .. etc
I tested sign up a new user on my my website using MStore API using Postman tool and it worked well like the following 
   1- first I got wp_nonce  as the following figure
           https://drive.google.com/open?id=1CIWPSGCc7scw7vdv5hxcHtzGwI2pP-Yx
2- I created a new user as the following figure
            https://drive.google.com/open?id=1cDYo8Av9qZra7ffCDf1hC0WHtJpScHt1
3. Proof of my purchased:
https://drive.google.com/open?id=1-p2l8xDhgPXJp6kdNfNP-y65pCmuledy

3. Config files (optional)
would you please help me to fix my flexstore app issues in signing  up

**Comment by minhtruong315** [comment]
@Yaser81  Add my skype: minhtruong315
I will help u check it via teamviewer
Thanks

**Comment by Yaser81** [comment]
I can't find your skype   minhtruong315 , would you please add my skype: yaserco.yaserco

**Comment by minhtruong315** [comment]
I add your skype

**Comment by minhtruong315** [comment]
supported

**Comment by Yaser81** [comment]
Ok thanks

**Comment by Yaser81** [comment]
the problem solved 👍 
thank you @minhtruong315

**Comment by khaliqdadmohmand** [comment]
flutx store multi vendor login has issue.. how to solve it
