### ISSUE TITLE
Mstore Expo - Webview Payment Issues.

### ISSUE THREAD

**Issue by mooidev** [inspireui/support#1836]
Hi There,

I've picked up two issues on the Webview payment functionality. Has anyone experienced the same issues?

1. When I first login to the App, I place an order and choose to pay by Credit Card (webview) but it doesn't connect to the Payment Gateway, the screen just hangs. I then go and pay via Cash on Delivery and the order is placed. I then place another order and choose to pay via Credit Card and it connects fine. Its almost as if the payment gateway hasn’t been initialized?

2. I placed an order and paid via Credit Card (webview). I then placed a second order and clicked to pay via Credit Card, but instead of completing the order I clicked on the Close Button on the screen, and it completed the order without any payment, which puts the order into the My Order section as Pending Payment. It seems like its caching the payment for the next order? Or not clearing the OrderID after a successful credit card payment?

Many Thanks.

**Comment by luyx2412** [comment]
HI @mooidev 
Can you send me the screenshot about your evanto account to download source code?

Thanks

**Comment by mooidev** [comment]
Here you go..



Brad Corden
brad@mooidev.com
+27842888001

**Comment by luyx2412** [comment]
Hi @mooidev 
I did not see anything, please send the screenshot again.

Thanks

**Comment by mooidev** [comment]
![mstore-pop](https://user-images.githubusercontent.com/16415185/72589258-61fee000-3903-11ea-970d-1b975ef02703.jpg)

**Comment by luyx2412** [comment]
Hi @mooidev 
Please send me the AppConfig.json and Config.js file. Let me investigate and reply you soon.

Thanks

**Comment by mooidev** [comment]
Here you go..

Brad Corden
brad@mooidev.com
+27842888001

**Comment by luyx2412** [comment]
Hi @mooidev 
Can you send me again, i did not see your attach.

Thanks

**Comment by mooidev** [comment]
I've renamed the extentions to .txt 

[AppConfig.txt](https://github.com/inspireui/support/files/4082440/AppConfig.txt)

[Config.txt](https://github.com/inspireui/support/files/4082442/Config.txt)

**Comment by mooidev** [comment]
Hi Guys,

Any idea on how to fix the issues I'm having? 

Many Thanks,

Brad.

**Comment by mooidev** [comment]
Hi Guys,

Any idea on how to fix the issues I'm having?

Many Thanks,

Brad.

**Comment by luyx2412** [comment]
Hi @mooidev We just come back the working. Let me investigate and reply you soon.

Thanks

**Comment by luyx2412** [comment]
Hi @mooidev I just checked your Config,txt, please send me your specific website.

Thanks
