### ISSUE TITLE
FluxStore Listing

### ISSUE THREAD

**Issue by ErolaEvents** [inspireui/support#1837]
Good I have different problems.

1- Images are not seen.

2 - The listeo products do not come out

3 - When I change the category data, an error appears in red on the app.

I have followed the documents but I don't understand very well. I have tried a bit of everything and I don't know if wordpress is well configured or not, among other things, I have just started and I have not had more than errors of all kinds, first did not start with the images, after seeing how to fix that error , now the photos are not seen, not all categories appear in the menu, if I try to add others that I have on the web, an error appears in red and the section is not visible.

Thanks

![Capture](https://user-images.githubusercontent.com/59916756/72428331-bb450300-378d-11ea-8a3e-55584b393782.jpg)

![Capture 01](https://user-images.githubusercontent.com/59916756/72427983-19251b00-378d-11ea-83b8-8f7d5b528e25.jpg)
![Capture 02](https://user-images.githubusercontent.com/59916756/72427984-19251b00-378d-11ea-8214-fada31743c42.jpg)
![Capture 03](https://user-images.githubusercontent.com/59916756/72427986-19bdb180-378d-11ea-8d0a-792a4c90170b.jpg)
![Capture 04](https://user-images.githubusercontent.com/59916756/72427988-19bdb180-378d-11ea-9dcd-23f7f9fdf5e6.jpg)

> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:

2. Screenshots issues:

3. Proof of my purchased:

3. Config files (optional)

**Comment by ErolaEvents** [comment]
![Capture](https://user-images.githubusercontent.com/59916756/72428435-f5160980-378d-11ea-9b68-e0d1db356b6a.jpg)

When category is ok i have this error too.

**Comment by ramyragab1** [comment]
in config.dart 
add cat id in this part 
 const kCategoryImages = {
  51: "assets/images/categories/teesh.png",
  52: "assets/images/categories/kidss.jpg",
  56: "assets/images/categories/helthyy.png",
  50: "assets/images/categories/facee.png",
  54: "assets/images/categories/bone.png",
  60: "assets/images/categories/eayy.png",
  53: "assets/images/categories/mokhh.png",
  55: "assets/images/categories/nsaa.png"
};

  51 ,56 this no is cat id from wordpress 
and path is imge path 
try this and will fix error

**Comment by philipvu30** [comment]
Hi @ErolaEvents,

I am your new assistant. Do your issues still occur? Please give me confirmation otherwise I will close this as solved. Thank you for your understanding :)
