### ISSUE TITLE
How can display the different price according to user role ?

### ISSUE THREAD

**Issue by inimist** [inspireui/support#1838]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: 
         How I can display different prices for users and vendors.

2. Screenshots issues:

![Screenshot_2020-01-15-17-47-18-38_f73b71075b1de7323614b647fe394240](https://user-images.githubusercontent.com/447618/72433706-f102df80-37bf-11ea-9d18-2fadddcae813.png)

3. Proof of my purchased:

![Screenshot at Jan 03 15-33-38](https://user-images.githubusercontent.com/447618/72433732-fbbd7480-37bf-11ea-8cbf-f934cf825201.png)

**Comment by inimist** [comment]
@luyx2412  Is there any update for this issue?

**Comment by luyx2412** [comment]
Hi @inimist 
Sorry this is new customization that is not included from our support scope, you can edit this file`src/containers/Detail/index.js` based on your user role and add your own business logic to support for this feature.

![image](https://user-images.githubusercontent.com/8909619/72658304-9943be80-39e1-11ea-8159-bd653773823f.png)

Thanks
