### ISSUE TITLE
[FluxStore Listing] - Images and Category would not show up on the App

### ISSUE THREAD

**Issue by tastemeitaste** [inspireui/support#1839]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: My  Images would not show up on the app, and the images also would not load. I already try all the methods I can find still can't solve it and I'm waiting for help for while but no one is replying also I previous purchase another product from yours and still didn't get any answer answer after I post the issue.

2. Screenshots issues:
![scre](https://user-images.githubusercontent.com/58832278/72456611-f849dd80-37ff-11ea-9214-f9940db43692.jpg)

3. Proof of my purchased:
![pro](https://user-images.githubusercontent.com/58832278/72456661-18799c80-3800-11ea-88f4-e85d9fc9ebb7.jpg)

3. Config files (optional)
[config.zip](https://github.com/inspireui/support/files/4066320/config.zip)

**Comment by vuthanhtoan30** [comment]
Hi tastemeitaste, 

Sorry I wasn't able to get back to you sooner. As I have inspected your configuration files, I found out 2 problems.
1. You left the "consumerKey" and "consumerSecret" empty in the config.dart. Please refer to this link to get those keys: https://docs.woocommerce.com/document/woocommerce-rest-api/
2. Your config.json file is an old version. I have included new version in the attachment file below.

Again I apologize for the inconvenience. Please feel free to ask if you have any questions. Thank you.

Config files: [config.zip](https://github.com/inspireui/support/files/4084980/config.zip)

**Comment by tastemeitaste** [comment]
hi I still have this issue
![2](https://user-images.githubusercontent.com/58832278/72962852-799d0380-3df0-11ea-9830-6c56d3427e81.png)
![註解 2020-01-23 144402](https://user-images.githubusercontent.com/58832278/72962860-7e61b780-3df0-11ea-9cd5-fd5b51ccc200.png)
