### ISSUE TITLE
[ListApp] FAQ - Common Installing issues with solutions 

### ISSUE THREAD

**Issue by thangvo9x** [inspireui/support#184]
Can not get the Listing image.

Solution: https://inspireui.github.io/listapp/docs/setup#step-3-config-the-image

**Comment by thangvo9x** [comment]
Empty image when update to latest version.
=> Solutions : 
You must run Regenerate Thumbnail Plugins to re-generate thumbnail images.
link : https://wordpress.org/plugins/regenerate-thumbnails/

**Comment by thangvo9x** [comment]
Featured images not be displayed  on your app .
=> Solution : Run Regenerate Thumbnails plugins here
https://wordpress.org/plugins/regenerate-thumbnails/

**Comment by thangvo9x** [comment]
Don't display price on your app . 
Solution: Go to App/Containers/PostDetail/ListingDetail.js 
remove this block
<img width="580" alt="remove-price" src="https://user-images.githubusercontent.com/23457178/52546415-8861f480-2df1-11e9-89e2-d4256c0cce5b.png">

**Comment by thangvo9x** [comment]
Problem props.onPress is not a function 
=>Solution: Replace this file to folder App/Components/Button/
P/s: And REMEMBER that replace *.txt -> *.js
[Button.txt](https://github.com/inspireui/support/files/2849865/Button.txt)

**Comment by thangvo9x** [comment]
Categories screen can't get images.
=>Solution: Comment line 112 at App/Containers/Categories/index.js

**Comment by bobozd** [comment]
With removing this code from above 29EUR text goes away only inside listing itself.
But on the main app page with all listings listed this text still exist.
Please help.

![screen shot 2019-02-12 at 09 59 35](https://user-images.githubusercontent.com/28021993/52623592-fb7c7100-2eac-11e9-96d4-5595d5c785db.png)
![screen shot 2019-02-12 at 09 59 45](https://user-images.githubusercontent.com/28021993/52623593-fb7c7100-2eac-11e9-95f3-dcc60f484429.png)

**Comment by thangvo9x** [comment]
Go to components/PostLayout/Colum/index.js 
remove this block 
<img width="576" alt="block" src="https://user-images.githubusercontent.com/23457178/52623794-c3425600-2edf-11e9-86ca-406055651304.png">

**Comment by bobozd** [comment]
that's it. thanks so much.

**Comment by thangvo9x** [comment]
Change App Icon Facebook Login 
=>Solution: Go to Common/Config/yourtheme(mylisting,...) find section Facebook && logInID && change to your app facebook id
Thanks

**Comment by thangvo9x** [comment]
How to add a new language.
=> Solution: Refer to this video here 
https://we.tl/t-5v7ZTPQt4u

**Comment by thangvo9x** [comment]
Fix the error Feature Image Not Display
 => Go to Common/ folder and replace this file 
[Tools.txt](https://github.com/inspireui/support/files/3211127/Tools.txt)
P/S: CHANGE from .txt -> .js

**Comment by git-palace** [comment]
Categories doesn't work.
![2019-07-11_09h53_02](https://user-images.githubusercontent.com/25261362/61069923-4057f580-a3c2-11e9-9bd7-d605954e47f9.png)

**Comment by edzofcit** [comment]
Error when Logging in via Listapp app. 

Error Display - undefined is not an object(evaluating 'v.user.id')

**Comment by dxpsite** [comment]
> 
> 
> How to remove the “+” from app. I don’t want user to add listing from app. Thanks

go to App/Navigation/index.js and comment that block:
  **postNewListing: {
      screen: postNewListingStack,
      navigationOptions: {
        header: null,
        tabBarIcon: ({ tintColor }) => (
          <TabBarIcon
            iconStatic={Images.PlusIcon}
            cssView={styles.plusIconView}
            css={styles.plusIcon}
            tintColor={Color.tabbarTint}
          />
        ),
      },
    },**

**Comment by caseylessard** [comment]
Categories don't appear in Map List or in Categories section. I can get an individual category to show if I want in the home, but not a list of categories.
