### ISSUE TITLE
MStore Pro - 2 line category text not center on the icon

### ISSUE THREAD

**Issue by juniortimeline** [inspireui/support#1840]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: 2 line category text not center on the icon

2. Screenshots issues: https://prntscr.com/qo8a1y

3. Proof of my purchased: https://codecanyon.net/comments/23500724

3. Config files (optional)

**Comment by luyx2412** [comment]
Hi @juniortimeline 
You can add more style in `src/components/HorizonList/Categories/Item/styles.js` line 27 look like the screenshot.
![image](https://user-images.githubusercontent.com/8909619/72494350-28bc6680-3856-11ea-8687-ec2f483cbc9d.png)

P/S: Feel free to reopen the issue.

Thanks

**Comment by juniortimeline** [comment]
> Hi @juniortimeline
> You can add more style in `src/components/HorizonList/Categories/Item/styles.js` line 27 look like the screenshot.
> ![image](https://user-images.githubusercontent.com/8909619/72494350-28bc6680-3856-11ea-8687-ec2f483cbc9d.png)
> 
> P/S: Feel free to reopen the issue.
> 
> Thanks

@luyx2412  thank you so much and I appreciate.

**Comment by juniortimeline** [comment]
Hi @luyx2412 it is possible to change as a PNG image the icon from Intro https://prnt.sc/qomtin

Thanks

**Comment by juniortimeline** [comment]
Hi @luyx2412 also app automatically close after confirming the order please check my screen record https://drive.google.com/file/d/1-JVRGKvtDk1BmfZ0nTZH9zWNQc6AbHfW/view?usp=sharing

**Comment by luyx2412** [comment]
> Hi @luyx2412 also app automatically close after confirming the order please check my screen record https://drive.google.com/file/d/1-JVRGKvtDk1BmfZ0nTZH9zWNQc6AbHfW/view?usp=sharing
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/6fd1044924d8a6d6907e02d89f67498eaefd4c8f/68747470733a2f2f73736c2e677374617469632e636f6d2f646f63732f646f636c6973742f696d616765732f69636f6e5f31345f766964656f5f66617669636f6e2e69636f">Google Drive**[Confirm Order App Close.mp4](https://drive.google.com/file/d/1-JVRGKvtDk1BmfZ0nTZH9zWNQc6AbHfW/view?usp=sharing&usp=embed_facebook)**

HI @juniortimeline Please send me your Appconfig.json and Config.js file. 

Thanks

**Comment by luyx2412** [comment]
I will close this ticket, please create new ticket with each question.

Thanks

**Comment by juniortimeline** [comment]
> > Hi @luyx2412 it is possible to change as a PNG image the icon from Intro https://prnt.sc/qomtin
> > Thanks
> > > <img alt="" width="48" src="https://camo.githubusercontent.com/e5dd01fb24c1c1fd244dca0620b1e6491a165160/68747470733a2f2f696d6167652e70726e747363722e636f6d2f696d6167652f4c302d474d5554755375713345656853374d344b34772e706e67">Lightshot**[Screenshot](https://prnt.sc/qomtin)**Captured with Lightshot
> 
> Hi you can do it, please see in `src/components/AppIntro/index.js` in `_renderItem` and replace `Ionicons` with `Image` components
> ![image](https://user-images.githubusercontent.com/8909619/72717505-b37ac980-3ba6-11ea-95af-b9ffda3db0ca.png)
> 
> Thanks
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/e5dd01fb24c1c1fd244dca0620b1e6491a165160/68747470733a2f2f696d6167652e70726e747363722e636f6d2f696d6167652f4c302d474d5554755375713345656853374d344b34772e706e67">Lightshot**[Screenshot](https://prnt.sc/qomtin)**Captured with Lightshot

Hi Thanks. Could you please share the code I can replace for this? I appreciate.
