### ISSUE TITLE
[Mstore Pro] - How to setup Firebase SMS Login and Sign in with Apple

### ISSUE THREAD

**Issue by binhetc** [inspireui/support#1842]
1. My issue: Cannot login with Firebase SMS Login and Sign in with Apple

2. Screenshots issues:
![Ảnh chụp Màn hình 2020-01-16 lúc 11 35 31](https://user-images.githubusercontent.com/13253563/72493841-b13a0780-3854-11ea-9698-f889794ae8da.png)

3. Proof of my purchased:
![Ảnh chụp Màn hình 2020-01-16 lúc 11 31 44](https://user-images.githubusercontent.com/13253563/72493508-dda15400-3853-11ea-9fc3-a0d17e01b3f0.png)

3. Config files (optional)

I tested in my real app also.

**Comment by luyx2412** [comment]
Hi @binhetc 
- Are use your firebase config? So can you check your GoogleService-Info.plist, and config firebase to login sms https://invertase.io/oss/react-native-firebase/v6/auth/phone-auth
- With login apple id. Please make sure following the document https://github.com/ton44079/react-native-apple-authentication#ios-1.

I just checked MStore Pro, and everything worked normal.
Thanks

**Comment by luyx2412** [comment]
Feel free reopen this issue.

**Comment by binhetc** [comment]
Hello lux2412,
I did some way as document you sent, but it does not work, so could you give me a remote support, I have TeamViewer in my Mac.
Best regards,
Binh Dinh

**Comment by luyx2412** [comment]
Hi @binhetc 
Are you setup the firebase in mobile application? 
https://medium.com/xcblog/get-started-with-firebase-for-ios-apps-32a5dc850a28
https://firebase.google.com/docs/ios/setup
Because the first you need setup your firebase integrate with iOS or Android. 

Thanks
