### ISSUE TITLE
[Fluxstore for Woocommerce] - App does not show all subcategories from woocommerce backend

### ISSUE THREAD

**Issue by zahmed84** [inspireui/support#1843]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:

There is a bug in your app. In fact some of the subcategories are now showing under parent categories. I checked your store website demo and compared it with your App demo which also has the same problem.

These are screenshots from your app demo and woocommerce backend.
![mstore-woocommerce on localhost](https://user-images.githubusercontent.com/58950301/72494717-92cd0f80-3846-11ea-9920-592305c41dee.PNG)
![WhatsApp Image 2020-01-16 at 9 11 58 AM](https://user-images.githubusercontent.com/58950301/72494781-c314ae00-3846-11ea-97f1-76cd52d03d41.jpeg)

The same issue i am facing in my App. Some of the subCategories are not showing in the App i built.

Here is my screenshot issue:
![Category Page](https://user-images.githubusercontent.com/58950301/72495310-281cd380-3848-11ea-9fe9-10b309bbe1e8.PNG)

Please let me know how to resolve this bug in your app. Your help in this regard will be much appreciated.

3. Proof of my purchased:

![Proof of Purchase](https://user-images.githubusercontent.com/58950301/72495398-64503400-3848-11ea-8145-56f0c48d8185.PNG)

3. Config files (optional)

**Comment by minhcasi** [comment]
@zahmed84 can u send me full source code via email: truong@inspireui.com. Thanks

**Comment by minhcasi** [comment]
@minhtruong315 - pls help followup this ticket - https://tppr.me/pIAks - thank you!

**Comment by minhtruong315** [comment]
@zahmed84 add my skype: minhtruong315
I'll help u check it

**Comment by inspireui-support** [comment]
Please open the services/woo_commerce.dart and update this function to fix the issue
```
@override
  Future<List<Category>> getCategories({lang}) async {
    try {
      List<Category> list = [];

      for(int i = 1; i<10; i++) {
        var cat = await wcApi.getAsync('products/categories?lang=$lang&per_page=100&page=$i');

        print('products/categories?lang=$lang&per_page=100&page=$i');

        if (cat is Map && isNotBlank(cat["message"])) {
          throw Exception(cat["message"]);
        } else {
          for (var item in cat) {
            final cate = Category.fromJson(item);
            if (cate.id != null) {
              list.add(cate);
            }
          }
        }
      }
      printLog("[WooCommerce] getCategories Categorys length:${list.length}");
      return list;
    } catch (e) {
      return categories;
      //throw e;
    }
  }
```

This will also fix on next release, thank you for your patience
