### ISSUE TITLE
FLUX

### ISSUE THREAD

**Issue by bobozd** [inspireui/support#1845]
Hi I can not start flux under andoridstudio. 
when I run flutter doctor I got this error.

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[!] Xcode - develop for iOS and macOS (Xcode 9.2)
    ✗ Flutter requires a minimum Xcode version of 10.2.0.
      Download the latest version or update via the Mac App Store.
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.40.1)
[!] Connected device
    ! No devices available

Is it even possible to run it under High Sierra ? I can get Xcode 9.2 only on HS...

**Comment by minhcasi** [comment]
@bobozd - please try to update the Xcode to the latest version that compatible with Flutter and iOS 13
