### ISSUE TITLE
[FLUXSTORE MV] - SMS Login can't working in Play Store, after release.

### ISSUE THREAD

**Issue by antixirus** [inspireui/support#1846]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
Im create APK from Fluxstore MV and iam release the app as a Beta Version in Google Play Store (Basic for Android), and when im try login with SMS Login, show error. Im attach Screenshots below.
When im try in Emulator device, SMS Login is working well.
2. Screenshots issues:
https://drive.google.com/open?id=1poqz-awHzj7MzDD-lVmhmU2peLfGCvCc
3. Proof of my purchased:
![gambar](https://user-images.githubusercontent.com/57300649/72507061-bfe4e680-3875-11ea-8764-3ec4d422411f.png)

3. Config files (optional)

**Comment by minhcasi** [comment]
![picturemessage_vwhpdlkn 113](https://user-images.githubusercontent.com/1459805/72709681-039e5f80-3b98-11ea-9152-07a32073fe43.png)

Please go to the Google Play store and copy the SHA-1 key and past to your Firebase setting:
![picturemessage_z5wkjdfi puh](https://user-images.githubusercontent.com/1459805/72709959-90e1b400-3b98-11ea-958f-60f4bc86fb98.png)
