### ISSUE TITLE
[Mstore Pro] Out of Stock item was showing and Error when clicked

### ISSUE THREAD

**Issue by winchai** [inspireui/support#1847]
![image](https://user-images.githubusercontent.com/58699787/72518694-72be4000-3888-11ea-914a-59980399cae0.png)

Hi there's an out of stock item showing called ocean classical and when clicked on it this error came out
![image](https://user-images.githubusercontent.com/58699787/72518760-8e294b00-3888-11ea-9034-d04b985b5f1a.png)

![image](https://user-images.githubusercontent.com/58699787/72518827-b0bb6400-3888-11ea-9101-04ca9b59296a.png)

here is my app config and config file
https://github.com/inspireui/support/files/4062781/common.zip

**Comment by minhcasi** [comment]
please help to post this ticket to  #1841
