### ISSUE TITLE
[Mstore Pro] Error when opening subcategory

### ISSUE THREAD

**Issue by winchai** [inspireui/support#1848]
Hi 
![image](https://user-images.githubusercontent.com/58699787/72519169-68e90c80-3889-11ea-9f2a-12f5fe7cc6c1.png)

there's an error when i click on subcategory called springbed here

![image](https://user-images.githubusercontent.com/58699787/72519306-a9488a80-3889-11ea-9d4c-faf10c1486d0.png)

![image](https://user-images.githubusercontent.com/58699787/72519255-97ff7e00-3889-11ea-8b2d-03ab4e941e10.png)

here is my config and app config 
https://github.com/inspireui/support/files/4062781/common.zip

thanks

**Comment by minhcasi** [comment]
please help to post this ticket to  #1841
