### ISSUE TITLE
[LISTAPP] - error

### ISSUE THREAD

**Issue by bobozd** [inspireui/support#1849]
---------

1. My issue: Hi, I got this error when after running expo start

2. Screenshots issues: ![Screen Shot 2020-01-16 at 12 27 10](https://user-images.githubusercontent.com/28021993/72522830-d764a500-385e-11ea-9444-8533f47a922c.png)
![Screen Shot 2020-01-16 at 13 02 54](https://user-images.githubusercontent.com/28021993/72523673-979ebd00-3860-11ea-953a-134a28fe4c1a.png)

3. Proof of my purchased: 

4. Config files (optional)[config.zip](https://github.com/inspireui/support/files/4071002/config.zip)

**Comment by minhcasi** [comment]
@bobozd - pls try this script to reinstall this plugin

yarn remove api-ecommerce
yarn install api-ecommerce
