### ISSUE TITLE
[MStore Pro - change theme problem

### ISSUE THREAD

**Issue by superben2010** [inspireui/support#1851]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:  when I changed the theme from 
   CategoriesLayout: Constants.CategoriesLayout.card to CategoriesLayout: Constants.CategoriesLayout.sideMenu in /src/common/config.js, it showed undefined is not an object (evaluating 'currency.code') . I did not change anything, it just is the default source code. and it is not react native cli version.

2. Screenshots issues:
<img width="405" alt="image" src="https://user-images.githubusercontent.com/3927634/72536195-cceae100-3847-11ea-981d-f7afb888ad6e.png">

3. Proof of my purchased:
<img width="1022" alt="image" src="https://user-images.githubusercontent.com/3927634/72536247-e4c26500-3847-11ea-97c7-80f88f673121.png">

3. Config files (optional)

**Comment by luyx2412** [comment]
Hi @superben2010 
I just fixed the issue, please replace in `src/components/ProductPrice` folder 
[ProductPrice.zip](https://github.com/inspireui/support/files/4079930/ProductPrice.zip)

And `src/common/Tools.js` 
[Tools.js.zip](https://github.com/inspireui/support/files/4079931/Tools.js.zip)

P/S: Fixed in next releaase, and feel free reopen the issue.

Thanks
