### ISSUE TITLE
[Mstore Pro] Duplicate item was shown in category

### ISSUE THREAD

**Issue by winchai** [inspireui/support#1854]
Hi 

![image](https://user-images.githubusercontent.com/58699787/72582948-08081580-3917-11ea-8309-4134c7289548.png)

theres a bug that list duplicate product , so i will explain how to access this bug

first access chair category from side menu and show all
![Screenshot_20200117-110034_Raja Furniture](https://user-images.githubusercontent.com/58699787/72583367-a8ab0500-3918-11ea-9d39-78c64750d1b0.jpg)

![Screenshot_20200117-110308_Raja Furniture](https://user-images.githubusercontent.com/58699787/72583462-00497080-3919-11ea-887a-6c3b8d86890e.jpg)

and then access the chair category from list category
![Screenshot_20200117-110128_Raja Furniture](https://user-images.githubusercontent.com/58699787/72583406-ca0bf100-3918-11ea-85f4-9cdcbd357482.jpg)

the product shown was duplicate from 3 to 6

![Screenshot_20200117-110137_Raja Furniture](https://user-images.githubusercontent.com/58699787/72583423-ddb75780-3918-11ea-82a6-f4f77240862a.jpg)

my config and app config
https://github.com/inspireui/support/files/4062781/common.zip

can you help me solve this ? thanks

**Comment by winchai** [comment]
And please see this issue too
https://github.com/inspireui/support/issues/1814

**Comment by luyx2412** [comment]
Hi @winchai 

Because you did not add image for the category or the product, so the category and product image will show default. You should be add image for both it.

P/S: Feel free to reopen the issue.

Thanks
