### ISSUE TITLE
fluxstore

### ISSUE THREAD

**Issue by Saifahmad99** [inspireui/support#1855]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:  I don'
![Screenshot (32)](https://user-images.githubusercontent.com/59877416/72588520-97fd8d80-391e-11ea-9dad-b8e20db64c1b.png)
t know what this step says

404 error page
Once enabling the mstore-api plugin, the payment gateway may not work as the default. To fix the error when clicking Process payment, following these steps:

1. Update the Mstore API to latest version: https://wordpress.org/plugins/mstore-api/

2. Copy the plugins/mstore-api/templates/mstore-api-template.php file to your current Wordpress template folder (example: wp-content/themes/your-template-name)

3. Go back to Wordpress Admin dashboard, create a page, name it "mstore-api", and remember don't set any parent page for it, then set page template to "Mstore Checkout".

2. Screenshots issues:
![Screenshot (31)](https://user-images.githubusercontent.com/59877416/72588528-a055c880-391e-11ea-9966-c82c4a631587.png)

3. Proof of my purchased:
![Screenshot (32)](https://user-images.githubusercontent.com/59877416/72588550-ae0b4e00-391e-11ea-9db0-e0b4a8334172.png)

3. Config files (optional)

**Comment by minhtruong315** [comment]
@Saifahmad99 add my skype: minhtruong315. I will help u check this issue. thanks

**Comment by minhtruong315** [comment]
supported via skype
