### ISSUE TITLE
[FLUXSTOR MV] -  SUSPECT PICTURE  AND ERROR AFTER LOGIN FIRST TIME

### ISSUE THREAD

**Issue by yassiney120** [inspireui/support#1856]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
1- I REMARK SUSPECT PICTURE IN CATEGORY AND ORDER HISTORY  SCREEN A 
2- AFTER LOGIN FIRST TIME O GOT ERROR IN SCREENSHOT B
2. Screenshots issues:
A- https://ibb.co/b63W9rz
B - https://ibb.co/6n8HY6z
3. Proof of my purchased:
https://ibb.co/XsskN38
3. Config files (optional)
https://drive.google.com/drive/folders/1DK6jjtF5i-2BKXig8W0TsKWcuD01CViW?usp=sharing

**Comment by yassiney120** [comment]
hi, Inspirui Team any news about this issues

**Comment by minhtruong315** [comment]
@yassiney120 add my skype: minhtruong315
I will help u check it. Thanks

**Comment by yassiney120** [comment]
Thank you

Le lun. 20 janv. 2020 à 07:24, minhtruong315 <notifications@github.com> a
écrit :

**Comment by minhtruong315** [comment]
supported via skype
