### ISSUE TITLE
[MStore Pro] - can’t get data from server

### ISSUE THREAD

**Issue by 007asom** [inspireui/support#1857]
My issue:
can’t get data from server
Screenshots issues:

Proof of my purchased:
https://ibb.co/PNBWpYy

Config files (optional)

Hello
I face a problem after changing the hosting server.
 I get this error “can’t get data from server” in CeBuilder The Rest API is not working correctly ! Wordpress Plugins install https://docs.inspireui.com/mstore/wordpress-setting/

**Comment by minhcasi** [comment]
@007asom could i check if you have installed all the required plugin - https://docs.inspireui.com/mstore/wordpress-setting/ - thank you!

**Comment by 007asom** [comment]
These is the plugins I've installed. 
https://ibb.co/xYDXkQw

**Comment by minhcasi** [comment]
@007asom - could you share your config file from common folder so that we could help for checking (file common/config.js and AppConfig.json) - thank you!

**Comment by 007asom** [comment]
can you please give me your email?

**Comment by luyx2412** [comment]
luyxtran264@gmail.com

**Comment by 007asom** [comment]
I sent it on the same subject.

**Comment by 007asom** [comment]
any update, please?

**Comment by luyx2412** [comment]
HI @007asom please resend via luyxtran264@gmail.com. I did not receive your email.

Thanks

**Comment by 007asom** [comment]
Ok, I sent it again.

**Comment by luyx2412** [comment]
Hi @007asom
- The first please change woocommerce url is `http://m7lwa.com`
![image](https://user-images.githubusercontent.com/8909619/73592784-70b6db00-4530-11ea-8524-32e089c09121.png)
- The second i checked your config, something was wrong related install plugin. Can you recheck with the document https://docs.inspireui.com/mstore/wordpress-setting/#permalink-url-setting or please check your woocommerce signature, because the error response is `Invalid signature - provided signature does not match.`

Thanks

**Comment by 007asom** [comment]
do you mean move it to subfolder? 

the second step configured well.

**Comment by 007asom** [comment]
Thanks for reply.
Can you tell me what did you mean in first point?
I changed it to https, and move it to subfolder.

**Comment by luyx2412** [comment]
Hi @007asom You mean your app still could not get from the server?

Thanks

**Comment by 007asom** [comment]
Hi
Yes, still can't get data from server

**Comment by luyx2412** [comment]
Hi @007asom Please create new `cosumerKey` and `consumerSecret` and recheck again.

Thanks

**Comment by 007asom** [comment]
Hello
the problem not solved yet. 
https://www.dropbox.com/s/y3280ze1q30yi8z/WhatsApp%20Video%202020-02-10%20at%2005.53.15.mp4?dl=0
the config file and appconfig.josn is the original.

it is not working  only with Release version "./gradlew assembleRelease" 

it works fine when running it by using "react-native run-android "

**Comment by luyx2412** [comment]
Hi @007asom I could not get data from server in debug mode, so can you send me your admin account via luyxtran264@gmail.com? or please check again your `cosumerKey` and `consumerSecret`

Thanks

**Comment by 007asom** [comment]
It happened with your cosumerKey and consumerSecret

**Comment by 007asom** [comment]
I sent the information for you

**Comment by luyx2412** [comment]
Hi @007asom I did not see your email, can you check again? Or can you invite me to your admin dashboard luyxtran264@gmail.com

Thanks

**Comment by 007asom** [comment]
Done
I sent it again.

**Comment by luyx2412** [comment]
Hi @007asom I just updated AppConfig.json and send via your email. Please check and try this file. Everything worked normal.

P/S: Feel free to reopen the issue.

Thanks

**Comment by 007asom** [comment]
Hello
I replied on your email. I replaced the config file with the one you sent. Still same issues.

**Comment by 007asom** [comment]
Hello
Can you guide me to fix this problem. It still not solved.

**Comment by 007asom** [comment]
it works on android version 8.1.0, but not working on version 9.

**Comment by luyx2412** [comment]
Hi @007asom Please make sure your website is `https` which will fix this issue.

Thanks
