### ISSUE TITLE
Failed assertion: boolean expression must not be null

### ISSUE THREAD

**Issue by rizwan3d** [inspireui/support#1858]
1. My issue:

Failed assertion: boolean expression must not be null
When i click the item in products, it will shows this error.

**Console output:**
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building Detail:
Failed assertion: boolean expression must not be null

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  Detail file:///D:/Projects/FluxStore%201.6.2/source/lib/widgets/product/product_card_view.dart:84:18
When the exception was thrown, this was the stack: 
#0      _SimpleLayoutState.initState (package:fstore/screens/detail/themes/simpleType.dart:50:18)
#1      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4355:58)
#2      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#3      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#4      Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
Already tested:
https://github.com/inspireui/support/issues/1786#issuecomment-572931445

2. Screenshots issues:

![image](https://user-images.githubusercontent.com/10514337/72635428-a67b9180-397e-11ea-8669-590e957289a5.png)

3. Proof of my purchased:
![image](https://user-images.githubusercontent.com/10514337/72635199-19383d00-397e-11ea-8fbc-cf9806ed5271.png)

3. Config files (optional)
Copied form lib/example/magento 
      Changed serverConfig
      Added `var kLayoutWeb = true;`

**Comment by rizwan3d** [comment]
Hi, Mr, @minhcasi & @minhtruong315  there is any chance get my problem solve.

**Comment by minhcasi** [comment]
Sorry for the late response as the team has not worked on Weekend for checking.

We also approve your refund request btw - thanks

**Comment by rizwan3d** [comment]
If you can sove this problem i will bye again.

**Comment by minhcasi** [comment]
Yes sure - pls zip your common file and send us for investigating the issue, it could be related to the data issue - thank you!

**Comment by rizwan3d** [comment]
please provide me your email or will you you to my private repository .

**Comment by rizwan3d** [comment]
@minhcasi please Solve my problem.

**Comment by minhcasi** [comment]
Hi, pls download the latest 1.6.3 - thank you!

**Comment by rizwan3d** [comment]
Does it required to update Plugins on website

**Comment by inspireui-support** [comment]
@rizwan3d - pls update to latest mstore-api 2.0.3 as well

**Comment by inspireui-support** [comment]
@rizwan3d i'm closing this ticket as the refund process has been approved, let us know when you purchased the product again - happy coding!
