### ISSUE TITLE
[Fluxstore] - How to change text in the ui

### ISSUE THREAD

**Issue by shreyas-shriyan** [inspireui/support#1859]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: 
a) how to change text in ui ? for ex: continue to shipping > continue to ship .
b) Png and gif not working in splash screen.
c) Review column overflowing in latest version 1.6.2

2. Screenshots issues:

3. Proof of my purchased:
<img width="1178" alt="71619753-e7884d80-2beb-11ea-84b9-3634b7cce639" src="https://user-images.githubusercontent.com/51715896/72647995-e69f3c00-399f-11ea-9fdc-3d917bfab640.png">

3. Config files (optional)

**Comment by minhcasi** [comment]
@shreyas-shriyan - you can change the text ui by using the inspector - https://docs.inspireui.com/fluxstore/useful-tip/

@minhtruong315 - pls fix the issues b and c

**Comment by shreyas-shriyan** [comment]
d) bottom overflow on [you might also like]
![WhatsApp Image 2020-01-18 at 1 44 49 PM](https://user-images.githubusercontent.com/51715896/72660845-4bd34b80-39f9-11ea-9a80-6e2be497abb3.jpeg)

**Comment by shreyas-shriyan** [comment]
getting this issue even after regenerating images the proper way

**Comment by minhtruong315** [comment]
@shreyas-shriyan can u send me config.dart file

**Comment by shreyas-shriyan** [comment]
https://github.com/shreyas-shriyan/pariconfig

**Comment by shreyas-shriyan** [comment]
any updates?

**Comment by shreyas-shriyan** [comment]
To change text in UI you can edit i18n.dart in the generated folder
