### ISSUE TITLE
Flux-Listing 

### ISSUE THREAD

**Issue by bobozd** [inspireui/support#1860]
Hi, I started default fluxstore via android studio but I have this error and app is not connected to my website, default content showed inside the app

error:
Performing hot reload...
Syncing files to device AOSP on IA Emulator...

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building CategoryItem(dirty, dependencies: [InheritedProvider<CategoryModel>, MediaQuery]):
'package:flutter/src/painting/image_resolution.dart': Failed assertion: line 134 pos 15: 'assetName != null': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  CategoryItem file:///home/bobo/Desktop/RenderizeApp/from_flux/app_01/lib/widgets/home/category/category_image_items.dart:134:17
When the exception was thrown, this was the stack: 
#2      new AssetImage (package:flutter/src/painting/image_resolution.dart:134:15)
#3      new Image.asset (package:flutter/src/widgets/image.dart:571:12)
#4      CategoryItem.build (package:fstore/widgets/home/category/category_image_items.dart:38:19)
#5      StatelessElement.build (package:flutter/src/widgets/framework.dart:4392:28)
#6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4324:15)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (2) Exception caught by widgets library ═══════════════════════════════════════════════════
'package:flutter/src/painting/image_resolution.dart': Failed assertion: line 134 pos 15: 'assetName != null': is not true.
The relevant error-causing widget was: 
  CategoryItem file:///home/bobo/Desktop/RenderizeApp/from_flux/app_01/lib/widgets/home/category/category_image_items.dart:134:17
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (3) Exception caught by widgets library ═══════════════════════════════════════════════════
'package:flutter/src/painting/image_resolution.dart': Failed assertion: line 134 pos 15: 'assetName != null': is not true.
The relevant error-causing widget was: 
  CategoryItem file:///home/bobo/Desktop/RenderizeApp/from_flux/app_01/lib/widgets/home/category/category_image_items.dart:134:17
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (4) Exception caught by widgets library ═══════════════════════════════════════════════════
'package:flutter/src/painting/image_resolution.dart': Failed assertion: line 134 pos 15: 'assetName != null': is not true.
The relevant error-causing widget was: 
  CategoryItem file:///home/bobo/Desktop/RenderizeApp/from_flux/app_01/lib/widgets/home/category/category_image_items.dart:134:17
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (5) Exception caught by widgets library ═══════════════════════════════════════════════════
'package:flutter/src/painting/image_resolution.dart': Failed assertion: line 134 pos 15: 'assetName != null': is not true.
The relevant error-causing widget was: 
  CategoryItem file:///home/bobo/Desktop/RenderizeApp/from_flux/app_01/lib/widgets/home/category/category_image_items.dart:134:17
════════════════════════════════════════════════════════════════════════════════════════════════════
Reloaded 0 of 2025 libraries in 1,023ms.

SCREENSHOT:
https://drive.google.com/file/d/1LToNzBooFgK9LCG1ihblzxmueNamcKEZ/view?usp=sharing

**Comment by minhcasi** [comment]
@bobozd - could you help to attache the config file - thanks

**Comment by bobozd** [comment]
here is my config
[config.zip](https://github.com/inspireui/support/files/4080183/config.zip)

**Comment by vuthanhtoan30** [comment]
Hi bobozd, 

Sorry I wasn't able to get back to you sooner. As I have inspected your configuration files, it seems you haven't enable job_listing_category on your wordpress site. Also your config files are old versions. Please follow the instruction below and replace the new files I have included.

Again I apologize for the inconvenience. Please feel free to ask if you have any questions. Thank you.

config files:  [config.zip](https://github.com/inspireui/support/files/4085670/config.zip)

job_listing_category: [job_listing_category.zip](https://github.com/inspireui/support/files/4085673/job_listing_category.zip)

**Comment by bobozd** [comment]
I setup new clean
