### ISSUE TITLE
[Fluxstore-MV] - Shop Button at Sidemenu & Blog View Issue

### ISSUE THREAD

**Issue by saifmuhtar** [inspireui/support#1862]
Hi InspireUI,
I'm facing 2 issues:
1) Shop Button at the side menu is not working
2) After I click Blog button at side menu, blank page is appeared.

For you reference, I attached here the config file and blog_view file.

Thank you

===============
Attachment:
[Archive.zip](https://github.com/inspireui/support/files/4079661/Archive.zip)

=================
Proof of purchase:
![72332982-fc89d400-36f5-11ea-9307-f8c418404111](https://user-images.githubusercontent.com/34681804/72653606-abfcca00-39c6-11ea-81b1-b4672e74a955.jpg)

**Comment by saifmuhtar** [comment]
This error appear on blog page:

![Screenshot_1579333763](https://user-images.githubusercontent.com/34681804/72660542-6c57d180-3a0a-11ea-922e-447ab87bc71b.png)

**Comment by minhtruong315** [comment]
@saifmuhtar add my skype: minhtruong315@gmail.com
I will help u check this issue

**Comment by saifmuhtar** [comment]
@minhtruong315 I'm waiting for your support. Thank you.

**Comment by saifmuhtar** [comment]
I think that I have a similar issue like on this post:
https://github.com/inspireui/support/issues/1865

**Comment by minhtruong315** [comment]
supported

**Comment by saifmuhtar** [comment]
@minhtruong315 @minhcasi 
Thank you so much for your great support 🌟🌟🌟🌟🌟
