### ISSUE TITLE
[Flux-Pro] - v1.6.2 Unable to update profile

### ISSUE THREAD

**Issue by imhafeez** [inspireui/support#1864]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
Update profile is not working. It keeps on loading and gives error message 500. internal server error

2. Screenshots issues:

3. Proof of my purchased:
1ae3aea7-20c0-43ee-b350-c79e42c6e5ee

3. Config files (optional)

**Comment by imhafeez** [comment]
it throughs exception 

 [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Exception: Can not updte user infor

**Comment by minhcasi** [comment]
@imhafeez - could you share your config file so that we could help for checking - thank you!

**Comment by imhafeez** [comment]
@minhcasi I have emailed you the config files.

There is one more issue regarding cache. Please see my email with attached screenshot.

Thanks

**Comment by minhcasi** [comment]
noted with checking - thank you!

**Comment by vumanhsn97** [comment]
@imhafeez What is your mstore api version? Can you send your website admin to vumanhsn97@gmail.com

**Comment by imhafeez** [comment]
Sorry i can't share website admin with you as its my client website. I guess i am using the version with release 1.6.0.
Is it something related to the MStore api? the profile update? because its not working on your fluxstore demo as well.

the cache issue i can try with updated version.

**Comment by imhafeez** [comment]
This appears while activating latest mstore-api

<img width="1134" alt="Screenshot 2020-01-20 at 8 13 47 PM" src="https://user-images.githubusercontent.com/21155655/72741852-4ed16600-3bca-11ea-87b8-83d252d1e9ef.png">

**Comment by imhafeez** [comment]
any update on this? @minhcasi @vumanhsn97

**Comment by imhafeez** [comment]
<img width="592" alt="Screenshot 2020-01-21 at 9 02 39 PM" src="https://user-images.githubusercontent.com/21155655/72821345-3462bf80-3c92-11ea-958e-99bf7258078f.png">

Update profile is fine now. just change the message. 
Please resolve the cache issue

**Comment by minhcasi** [comment]
@imhafeez - sorry we missed your ticket on the latest release, we will include it on next 1.6.4 - thank you for your patient -

**Comment by imhafeez** [comment]
@minhcasi I really need cache issue fixed. i was terribly waiting for your release.

**Comment by imhafeez** [comment]
@minhcasi All other issues resolve including cache. I have updated the source code and the backend api. update profile still didn't work. I don't know why. It keeps on loading. Please help me with this. 
Thanks
