### ISSUE TITLE
[Fluxstore] BlogItemView Error

### ISSUE THREAD

**Issue by Saifahmad99** [inspireui/support#1865]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: Can't run the app always showing
 ════════ (2) Exception caught by widgets library═══════════════════════════════════════════════════
The method '*' was called on null.
Receiver: null
Tried calling: *(1.2)
The relevant error-causing widget was: 
  BlogItemView file:///C:/Users/User/Downloads/codecanyon-b0vlFpMP-fluxstore-woocommerce-flutter-ecommerce-full-app/FluxStore-woo%201.6.1/source/lib/widgets/home/horizontal/blog_list_items.dart:73:34

my blog_list_items.dart code as follow

import 'dart:async';

import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

import '../../../common/config.dart';
import '../../../models/app.dart';
import '../../../models/blog.dart';
import '../../../screens/blogs.dart';
import '../../../widgets/blog/blog_view.dart';
import '../../../widgets/home/header/header_view.dart';

class BlogListItems extends StatefulWidget {
  final config;

  BlogListItems({this.config});

  @override
  _BlogListItemsState createState() => _BlogListItemsState();
}

class _BlogListItemsState extends State<BlogListItems> {
  Future<List<Blog>> _fetchBlogs;

  @override
  void initState() {
    _fetchBlogs = getBlogs(); // only create the future once.
    super.initState();
  }

  Future<List<Blog>> getBlogs() async {
    List<Blog> blogs = [];
    var _jsons = await Blog.getBlogs(url: serverConfig['blog'], page: 1);
    for (var item in _jsons) {
      blogs.add(Blog.fromJson(item));
    }
    return blogs;
  }

  Widget _buildHeader(context, blogs) {
    final locale = Provider.of<AppModel>(context).locale;
    if (widget.config.containsKey("name")) {
      var showSeeAllLink =
          widget.config['layout'] != "instagram" && blogs != null;
      return HeaderView(
        headerText: widget.config["name"][locale] ?? '',
        showSeeAll: showSeeAllLink,
        callback: () => {
          Navigator.push(
            context,
            MaterialPageRoute(
              builder: (context) => BlogScreen(),
            ),
          )
        },
      );
    }
    return Container();
  }

  @override
  Widget build(BuildContext context) {
    var screenWidth = MediaQuery.of(context).size.width;

    return Column(
      children: <Widget>[
        FutureBuilder<List<Blog>>(
          future: _fetchBlogs,
          builder: (context, snapshot) {
            switch (snapshot.connectionState) {
              case ConnectionState.none:
              case ConnectionState.active:
              case ConnectionState.waiting:
                return Column(
                  children: <Widget>[
                    _buildHeader(context, null),
//                    BlogItemView(posts: emptyPosts, index: 0),
//                    BlogItemView(posts: emptyPosts, index: 1),
//                    BlogItemView(posts: emptyPosts, index: 2),
                  ],
                );
                break;
              case ConnectionState.done:
              default:
                if (snapshot.hasError) {
                  return Container();
                } else {
                  List<Blog> blogs = snapshot.data;
                  int length = blogs.length;
                  return Column(
                    children: <Widget>[
                      _buildHeader(context, blogs),
                      Container(
                        width: screenWidth,
                        height: screenWidth * 0.6,
                        color: Theme.of(context).cardColor.withOpacity(0.85),
                        padding: EdgeInsets.only(top: 8.0),
                        child: PageView(
                          children: [
                            for (var i = 0; i < length; i = i + 3)
                              Column(
                                children: <Widget>[
                                  blogs[i] != null
                                      ? Expanded(
                                    child: BlogItemView(
                                        posts: blogs, index: i),
                                  )
                                      : Expanded(
                                    child: Container(),
                                  ),
                                  i + 1 < length
                                      ? Expanded(
                                    child: BlogItemView(
                                        posts: blogs, index: i + 1),
                                  )
                                      : Expanded(
                                    child: Container(),
                                  ),
                                  i + 2 < length
                                      ? Expanded(
                                    child: BlogItemView(
                                        posts: blogs, index: i + 2),
                                  )
                                      : Expanded(
                                    child: Container(),
                                  ),
                                ],
                              )
                          ],
                        ),
                      ),
                    ],
                  );
                }
            }
          },
        ),
      ],
    );
  }
}

2. Screenshots issues:
![Screenshot (36)](https://user-images.githubusercontent.com/59877416/72663945-299ff480-3a1e-11ea-98e7-1c0c44245081.png)

3. Proof of my purchased:
![Screenshot (32)](https://user-images.githubusercontent.com/59877416/72663953-3886a700-3a1e-11ea-9745-e2c85977d9de.png)

3. Config files (optional)

**Comment by minhcasi** [comment]
@Saifahmad99 - could i know if you are using VS Code? Pls also try Android Studio to see if it is ok?

**Comment by Saifahmad99** [comment]
no i'm using Android Studio But Still Having this error please help me.

**Comment by minhcasi** [comment]
@minhtruong315 - pls help for checking

**Comment by Saifahmad99** [comment]
hello is there any update?

**Comment by minhtruong315** [comment]
@Saifahmad99 add my skype: minhtruong315
I'll help u check it

**Comment by minhtruong315** [comment]
supported via skype
