### ISSUE TITLE
[Flux Store Multi Vendors] - Customising config.json MainColor field according to Theme

### ISSUE THREAD

**Issue by HassanChmsdn** [inspireui/support#1866]
1. **My issue:**
I have noticed that the MainColor of the app is applied from the config.json [Setting][MainColor] in app.dart, after trying to edit this field depending on dynamic theme i have created, it seems that the changes are not applied, but getting the basic colors from flutter.
2. **Screenshots issues:**
Here is My Method building the theme in the app.dart:
<img width="975" alt="Screenshot 2020-01-18 at 14 07 47" src="https://user-images.githubusercontent.com/921709/72664288-56dbab00-39fc-11ea-9134-e39df8bb02ca.png">

I have changed the primary color as follows according to the new theme i have initiated in the styles.dart as you can see in the second image:
<img width="932" alt="Screenshot 2020-01-18 at 14 08 20" src="https://user-images.githubusercontent.com/921709/72664311-9e623700-39fc-11ea-8e74-7f5fda29485a.png">
<img width="852" alt="Screenshot 2020-01-18 at 14 08 46" src="https://user-images.githubusercontent.com/921709/72664320-b89c1500-39fc-11ea-8ce4-6697bb61a914.png">

But unfortunately the primaryColor was not considered in this case and it was shown as the basic blue color in flutter theme :
<img width="419" alt="Screenshot 2020-01-18 at 14 10 24" src="https://user-images.githubusercontent.com/921709/72664325-c9e52180-39fc-11ea-8c87-d5d08ef59f2d.png">
<img width="409" alt="Screenshot 2020-01-18 at 14 10 30" src="https://user-images.githubusercontent.com/921709/72664632-868cb200-3a00-11ea-9e03-af4ea3eee2ec.png">

and in some fields of the App Using Theme.of(context).primaryColor it is not set as defined in style.dart according to Theme declaration, but its somehow considered as what was defined in the config.json file.

3. Proof of my purchased:
Item purchased code: d1141eb5-edf3-4bcc-844b-112677d6f489
Date : 2019-11-21 21:15:50 UTC

** Any Explanation Please **

**Comment by minhcasi** [comment]
@HassanChmsdn - could you zip the common folder and send back us for checking, it could be had a minor bug on this setting we need to have a check - thank you!

**Comment by HassanChmsdn** [comment]
> @HassanChmsdn - could you zip the common folder and send back us for checking, it could be had a minor bug on this setting we need to have a check - thank you!

@minhcasi here is the zipped folder I'm not sure if it is fine attaching it like this.

[common copy.zip](https://github.com/inspireui/support/files/4082505/common.copy.zip)

**Comment by minhcasi** [comment]
@vumanhsn97 - pls help for checking

**Comment by vumanhsn97** [comment]
@HassanChmsdn Please remove "primaryColor: Theme.of(context).primaryColor" https://tppr.me/hr8Rc. Just this code:
buildLuxuryLightTheme().copyWith();

**Comment by HassanChmsdn** [comment]
> @HassanChmsdn Please remove "primaryColor: Theme.of(context).primaryColor" https://tppr.me/hr8Rc. Just this code:
> buildLuxuryLightTheme().copyWith();
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/bbc8c26d8187e23cfbd509a8cfb52b88a993e063/68747470733a2f2f747070722e73332e616d617a6f6e6177732e636f6d2f75706c6f6164732f63336637623564633537353233656234643434656333646664373631646562662e706e67"><img alt="" height="14" src="/favicon-32x32.png"> tppr.me**[Public - Screenshot_2020-01-20 16-32-14](https://tppr.me/hr8Rc)**

Great Thanks, It fixed the problem!
