### ISSUE TITLE
question about Installations BeoNews.3.0.6

### ISSUE THREAD

**Issue by humamalhilal** [inspireui/support#1867]
Hello
He has trouble installing beo newsa 3.0.6
I will attach photos to you
![Annotation 2020-01-18 174058](https://user-images.githubusercontent.com/11793138/72666361-0d01bd80-3a1a-11ea-83db-99073825ec16.png)
![Annotation 2020-01-18 174120](https://user-images.githubusercontent.com/11793138/72666362-0d01bd80-3a1a-11ea-8824-6f435173b0e5.png)
![Annotation 2020-01-18 174145](https://user-images.githubusercontent.com/11793138/72666363-0d01bd80-3a1a-11ea-8a86-950bd7d12817.png)

**Comment by luyx2412** [comment]
Hi @humamalhilal Can you send me the screenshot purchased?

Thanks

**Comment by luyx2412** [comment]
Hi @humamalhilal I saw your CEO's email.
Please install expo-client follow the document https://expo.io/tools#cli.

Thanks
