### ISSUE TITLE
[mstore  EXPO] - change onPress on BannerHigh 

### ISSUE THREAD

**Issue by kiamoz** [inspireui/support#1868]
Dear support , I would like to change onPress on BannerHigh  and change from PostView()  to cutsome  navigate ...

I used :
```
const { navigate } = this.props.navigation;
..
..
onPress={() =>  navigate('yourcomponent') }
```

bu I get  Error on undefined is not an object ('this.props.navigation.navigate') 
I would like this navigate to category Screen ..

**Comment by minhcasi** [comment]
@kiamoz pls try your best with this customization by checking the guide on https://reactnavigation.org/

This is a kind of technical issue regarding to customize that will not include from our support scope, hope you can understand - thank you!
