### ISSUE TITLE
[FluxStore] Product Variation doesn't show all images

### ISSUE THREAD

**Issue by Mohamed20884** [inspireui/support#1869]
When selecting a product variation the images do not all change with regard to the variation only the featured image changes however when clicking on it the gallery shows up with the original product images not the variation. Also was wondering why pinch to zoom does not work in the gallery.

Thanks

**Comment by minhcasi** [comment]
Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads  it's used to verify your proof of purchase? sorry for any inconvenience - Thank you!

**Comment by Mohamed20884** [comment]
<img width="1280" alt="Screen Shot 2020-01-19 at 1 10 59 PM" src="https://user-images.githubusercontent.com/6944543/72679979-522afb80-3abd-11ea-942a-117deaadad5f.png">

**Comment by minhcasi** [comment]
@Mohamed20884 - thank you - please zip your common folder and send back us for further investigating - thank you!

**Comment by Mohamed20884** [comment]
[common.zip](https://github.com/inspireui/support/files/4086599/common.zip)

**Comment by minhcasi** [comment]
@Mohamed20884 - could you help to download the latest 1.6.3 - the team notify include some product fixing on this release - let us know your checking, thank you!

**Comment by Mohamed20884** [comment]
@minhcasi I just tried but the same problem is here for the variation images

**Comment by Mohamed20884** [comment]
@minhcasi  @inspireui-support  any update regarding solving this

**Comment by philipvu30** [comment]
Hi @Mohamed20884 ,

Would you mind if I ask for images regarding to your issues? Because I have copied the files you gave but it seems there is no data about your website. Thank you for your understanding :)

**Comment by Mohamed20884** [comment]
![Screenshot_20200130-161512](https://user-images.githubusercontent.com/6944543/73482047-b2674a80-43a5-11ea-988f-05476462483c.jpg)
![Screenshot_20200130-161453](https://user-images.githubusercontent.com/6944543/73482076-bbf0b280-43a5-11ea-91fe-d1ecf6cd3d10.jpg)
![Screenshot_20200130-161458](https://user-images.githubusercontent.com/6944543/73482096-c317c080-43a5-11ea-9ddd-7f181efb89f5.jpg)
![Screenshot_20200130-161503](https://user-images.githubusercontent.com/6944543/73482117-c9a63800-43a5-11ea-9bb3-99947e037bb6.jpg)

**Comment by Mohamed20884** [comment]
@philipvu30 as you can see from the images above when selecting the color only the featured image changes and not the rest of the images also if you see the last image the background image is blue shirt but when I clicked on it the zoomed image is the original white shirt

**Comment by philipvu30** [comment]
Hi Mohamed20884,

I assume this is a missing feature rather than a bug . Currently this app is only supporting in changing the feature image(the big one) regarding to the variation and shows only the primary product's images in the gallery. 
I will forward this issue to the technical team for future update. Thank you and have a nice day :)

**Comment by Mohamed20884** [comment]
Hi @philipvu30 ,

Can you guide me how to update this as I need it now so that I can complete setup and launch app.

Thanks

**Comment by philipvu30** [comment]
Hi @Mohamed20884 ,

I am sorry. There is nothing I can do right now to help you because this feature has not been implemented. I have not received information about the release date yet but I believe it will be included in the next update. 

Again, I apologize for this inconvenience and thank you for your understanding.

**Comment by minhcasi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Upgrade Product Image Variant](https://trello.com/c/XtIC83KM/18-upgrade-product-image-variant)

**Comment by inspireui-support** [comment]
moved to the backlog of investigating

**Comment by Mohamed20884** [comment]
@minhcasi Any update regarding this request

**Comment by Mohamed20884** [comment]
@philipvu30 Any update regarding this request
