### ISSUE TITLE
[MStore Pro] Unable to load script from assets

### ISSUE THREAD

**Issue by jig0009** [inspireui/support#187]
Product: [e.g. MStore]
Your Purchased Code: [e270ed9b-9841-4ab4-9ca4-dce01ecdd14e]

**Describe the issues**
 i'have a red screen (Unable to load script from assets 'index.android.bundle'. Make sure your bundle is packaged correctly ) in mstore-pro version 

**Screenshots**
https://mega.nz/#!uiJgAIrJ!CZI5ce3_W4HWiijxDyAvdzMkZYeASi_2ulNmv990VFc

**Additional context**
Add any other detail logs about the problem here.

**Comment by luyx2412** [comment]
HI @jig0009 Please follow the article to fix the issue https://medium.com/@adityasingh_32512/solved-unable-to-load-script-from-assets-index-android-bundle-bdc5e3a3d5ff

Thanks

**Comment by minhcasi** [comment]
Hi @jig0009 - you can also refer to these solutions - https://github.com/inspireui/support/issues/38 - thank you!
