### ISSUE TITLE
[FLUX NEWS] - I get Error flutter (25609)

### ISSUE THREAD

**Issue by sharkcrypto92** [inspireui/support#1870]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
when i run the app on Vcode dont see my Cats and posts its showing api working but Flutter gives me this issue 
E/flutter (25609): Once you have called dispose() on a CategoryModel, it can no longer be used.
2. Screenshots issues:
https://ibb.co/7pSMPB8
3. Proof of my purchased:

3. Config files (optional)

**Comment by sharkcrypto92** [comment]
this is lib files

**Comment by sharkcrypto92** [comment]
https://workupload.com/file/uREUnKF9

**Comment by minhcasi** [comment]
move to #1861 - pls create one ticket for your all issues

Also don't share the code public here - thanks
