### ISSUE TITLE
[FluxstoreMv] - errors on xcode 

### ISSUE THREAD

**Issue by yassiney120** [inspireui/support#1871]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
I got this erros during testing ios app
2. Screenshots issues:

https://ibb.co/4TDZ67g

3. Proof of my purchased:

https://ibb.co/4Z4L8GB

3. Config files (optional)

**Comment by minhcasi** [comment]
@yassiney120 - pls try to remove the ios/Pods, Podfile and Podfile.lock 

Then run "pod install" to reinstall the project  - thank you!

**Comment by yassiney120** [comment]
THANK YOU
