### ISSUE TITLE
[FluxStore v1.6.2] - UI Issue on Ads display 

### ISSUE THREAD

**Issue by imhafeez** [inspireui/support#1872]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
The top close and back buttons overlaps the status bar. unable to go out. while display ads.

2. Screenshots issues:
<img width="835" alt="bug" src="https://user-images.githubusercontent.com/21155655/72681144-806f0200-3ae2-11ea-936d-df062c2b9d2f.png">

3. Proof of my purchased:
1ae3aea7-20c0-43ee-b350-c79e42c6e5ee
3. Config files (optional)

**Comment by minhcasi** [comment]
This is fixed on the latest 1.6.3 - this version will be released in the next couple of day - thank you!
