### ISSUE TITLE
[listapp] - questions

### ISSUE THREAD

**Issue by bobozd** [inspireui/support#1873]
1. My issue: where can I change background color under intro section of IntroData.js

**Comment by bobozd** [comment]
2. where I can change color of the map icon at the bottom left of listing card  ?
![Screenshot from 2020-01-19 20-38-55](https://user-images.githubusercontent.com/28021993/72687208-ed42c600-3afb-11ea-8575-f83a061d0761.png)

**Comment by bobozd** [comment]
9. How to change colors of green circle under push notification and color of green circle with number of favorite items at the bottom-right ?
![Screenshot from 2020-01-19 23-30-49](https://user-images.githubusercontent.com/28021993/72689652-fd669f80-3b13-11ea-86da-785c2a699845.png)

**Comment by bobozd** [comment]
what's this error:

Require cycle: App/Components/index.js -> App/Components/BannerImage/index.js -> App/Components/index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
- node_modules/expo/build/environment/muteWarnings.fx.js:18:23 in warn
- node_modules/metro/src/lib/polyfills/require.js:118:8 in metroRequire
- node_modules/react-native-google-places-autocomplete/GooglePlacesAutocomplete.js:446:27 in _requestNearby
- node_modules/metro/src/lib/polyfills/require.js:322:6 in loadModuleImplementation
* http://192.168.0.25:19001/node_modules/expo/AppEntry.bundle?platform=android&dev=true&minify=false&hot=false:192884:57 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:322:6 in loadModuleImplementation
* http://192.168.0.25:19001/node_modules/expo/AppEntry.bundle?platform=android&dev=true&minify=false&hot=false:192451:32 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:322:6 in loadModuleImplementation
* http://192.168.0.25:19001/node_modules/expo/AppEntry.bundle?platform=android&dev=true&minify=false&hot=false:123560:55 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:322:6 in loadModuleImplementation
- node_modules/expo/AppEntry.js:5:0 in <global>
- node_modules/metro/src/lib/polyfills/require.js:322:6 in loadModuleImplementation
- node_modules/metro/src/lib/polyfills/require.js:201:45 in guardedLoadModule
* App/Components/LeftMenu/MenuAndroid.js:7:0 in <global>

**Comment by minhcasi** [comment]
pls ignore the waring cycle as it is not impact to the app.

Please also rename the API listing category /job_listing_category - screenshot: https://tppr.me/2TtK1

ex: http://mylisting.inspireui.com/wp-json/wp/v2/job_listing_category

**Comment by bobozd** [comment]
enabled
![screen_10](https://user-images.githubusercontent.com/28021993/72798605-bd063f00-3c43-11ea-97fa-7a3822cc572c.jpg)

**Comment by minhcasi** [comment]
@bobozd - could you zip the source and send back us for checking - support@inspireui.com - thanks
