### ISSUE TITLE
[Mstore EXPO ] - RTL issue   , not work  although change lang to Ar, clearing and uninstalling app and cache 

### ISSUE THREAD

**Issue by kiamoz** [inspireui/support#1874]
[Mstore EXPO ] - RTL issue   , not work  although change  lang to Ar, clearing and uninstalling app and cache ! , 
I open several tickets for this issue  but every time you close any  ticket  and  said  sometimes  wrong !

**Comment by kiamoz** [comment]
could you please connect me with  teamviwer   tomorrow ?

**Comment by luyx2412** [comment]
Hi @kiamoz You can reopen the ticket. And sorry my mistake about wrong Mstore version Pro and Expo.
This is a code to fix RTL in `src/Router.js` line 41. Replace `ComponentDidMount` function with
`componentWillMount() {
    const { language } = this.props;

    // init wooworker
    WooWorker.init({
      url: AppConfig.WooCommerce.url,
      consumerKey: AppConfig.WooCommerce.consumerKey,
      consumerSecret: AppConfig.WooCommerce.consumerSecret,
      wp_api: true,
      version: "wc/v3",
      queryStringAuth: true,
      language: language.lang,
    });

    NetInfo.fetch().then((state) => {
      this.props.updateConnectionStatus(state.type !== "none");
      this.setState({ loading: false });
    });

    I18nManager.forceRTL(language.lang === "ar");
  }`

P/S: And feel free reopen this ticket.

Thanks

**Comment by kiamoz** [comment]
![Screen Shot 2020-01-20 at 1 32 07 PM](https://user-images.githubusercontent.com/10494372/72717478-5290c880-3b89-11ea-8dda-7ea40888bf6c.png)
![Screen Shot 2020-01-20 at 1 33 13 PM](https://user-images.githubusercontent.com/10494372/72717536-6dfbd380-3b89-11ea-9680-1de5df492f8c.png)
@luyx2412  help me please its so far I have this issue ...

**Comment by luyx2412** [comment]
@kiamoz Please send me your teamviewer and password.

Thanks

**Comment by kiamoz** [comment]
@luyx2412  here you are thanks : 256 077 121
mzf327

**Comment by luyx2412** [comment]
HI @kiamoz I am updating my teamviewer, please install reactotron before remote.

Thanks

**Comment by kiamoz** [comment]
@luyx2412   and so I sure lang not set becouse Ar lang not set for home  HomeCategories_AR:
![Screen Shot 2020-01-20 at 1 42 29 PM](https://user-images.githubusercontent.com/10494372/72718215-bcf63880-3b8a-11ea-901b-e09a3a6ea2bd.png)

**Comment by kiamoz** [comment]
@luyx2412  reactotron stepped already

**Comment by kiamoz** [comment]
@luyx2412  TeamViewer 15.1.3937 is currently the newest version available. I'm newest

**Comment by kiamoz** [comment]
its says incompatible  ver ! @luyx2412

**Comment by kiamoz** [comment]
@luyx2412  new pass : qan316

**Comment by kiamoz** [comment]
@luyx2412  Thank you for your Help its works ;)

**Comment by luyx2412** [comment]
Hi @kiamoz you are welcome, and please rate 5 stars in codecanyon :D

Thanks
