### ISSUE TITLE
[Fluxstore - Woo] -  TR characters are not loaded in some places in the application.

### ISSUE THREAD

**Issue by sketchuprzr** [inspireui/support#1875]
1. My issue:

Turkish characters are not loaded in some places in the application. Some characters such as "Ş, İ, Ü, Ğ" are not loaded in the application, in some places. There is an example of this on the main page number 9. I installed Custom Language, but the problem still persists. How can I solve it?

2. Screenshots issues:

![image](https://user-images.githubusercontent.com/60021696/72689856-1298f980-3b27-11ea-95ae-82d45edf4878.png)

![image](https://user-images.githubusercontent.com/60021696/72689861-1cbaf800-3b27-11ea-8ead-3c5000efb6f8.png)

![image](https://user-images.githubusercontent.com/60021696/72689902-84714300-3b27-11ea-9d42-ab71aa2a88c2.png)

3. Proof of my purchased:

![image](https://user-images.githubusercontent.com/60021696/72689791-77a01f80-3b26-11ea-95a1-aeb34530d2c3.png)

3. Config files (optional)
[config.zip](https://github.com/inspireui/support/files/4083816/config.zip)

**Comment by minhcasi** [comment]
@sketchuprzr - the latest fluxstore is using Google Font library - pls check this guide https://medium.com/@inspireui/announcing-fluxstore-1-6-337efff1791f and https://pub.dev/packages/google_fonts

**Comment by sketchuprzr** [comment]
Hello, I'm still waiting for the solution. Please help me.

**Comment by minhcasi** [comment]
@sketchuprzr - it seems the issues related to Rest API that they don't support multi-language status.

You can try this solution:
create the mapping status from config file:

```
const kOrderStatus = {
    'en': [ 'processing': "Processing"....  ]
   'tr': ['processing" ,"Turkey processing', ...
};
```

From the Order language you can pick the current lang code by using
const lang = Provider.of<AppModel>(context, listen: false).locale;
kOrderStatus[lang]['processing'] ...

```

**Comment by sketchuprzr** [comment]
Where do I add this?

**Comment by inspireui-support** [comment]
`
lib/common/config.dart
lib/screens/order_detail.dart
`

Pls help to open one ticket for your conversation to help us focus to support all issues better - thanks

Moved to #1907

**Comment by sketchuprzr** [comment]
config.dart
![image](https://user-images.githubusercontent.com/60021696/73080448-e4286f00-3ed6-11ea-801b-5857e518395e.png)

order detail screen
![image](https://user-images.githubusercontent.com/60021696/73080461-eab6e680-3ed6-11ea-9de4-44dc1e290884.png)

When I add it this way, it doesn't work.

![image](https://user-images.githubusercontent.com/60021696/73080506-fbfff300-3ed6-11ea-9f39-7d95766f3fc8.png)


----------------------------

### **I get an error when I add it the way you say**

![image](https://user-images.githubusercontent.com/60021696/73080554-11751d00-3ed7-11ea-8297-f038daf08975.png)

![image](https://user-images.githubusercontent.com/60021696/73080607-281b7400-3ed7-11ea-936d-e6c8a8de5291.png)
