### ISSUE TITLE
Fluxstore WooCommerce - Flutter E-com -SMS OTP 1.6.2

### ISSUE THREAD

**Issue by roziseth01** [inspireui/support#1877]
Hi Guys,

1) My question/problem
I have an OTP plugin enable in wordpress. Can i use the plugin in flutter? i mean in your registration page, as i saw it using the FIREBASE. 
-  firebase with SMS userid using phone number + SMS
- i need the registration as normal wordpress registration, and phone number for verification.

If you can advise, please advise.
2) Screenshot
![Screenshot 2020-01-20 at 3 04 38 PM](https://user-images.githubusercontent.com/59671391/72705353-3fd0c080-3b96-11ea-914e-04ac97377bff.png)

3) Proof of my purchased:
![image](https://user-images.githubusercontent.com/59671391/72705409-57a84480-3b96-11ea-8a05-577ea1911aaa.png)

**Comment by minhcasi** [comment]
@roziseth01 - it's possible to integrate with OPT by customizing the mstore-api plugin - we may consider to add it on next release

Could i know which WP plugin you are using to support for this feature?

**Comment by roziseth01** [comment]
I find out that the OTP from miniorange easy to config n straight fwd. however there is limitation on config such as custom setting was under pro version. Ill look for others and keep u guys posted.

Regards
Fakhrul Rozi Seth

**Comment by minhcasi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [OPT login](https://trello.com/c/9JScybz3/15-opt-login)

**Comment by minhcasi** [comment]
move to Trello backlog - https://trello.com/c/9JScybz3/15-opt-login

**Comment by roziseth01** [comment]
Hi did u guys have a paid support? I need the features for SMS...
