### ISSUE TITLE
FluxListing

### ISSUE THREAD

**Issue by bobozd** [inspireui/support#1878]
Hello,

when I change url to my website under config.dart data is not loaded from my site. Please help.
![Screenshot from 2020-01-20 10-16-30](https://user-images.githubusercontent.com/28021993/72714143-83afcf80-3b6e-11ea-9236-33d257f8b404.png)
![Screenshot from 2020-01-20 10-17-06](https://user-images.githubusercontent.com/28021993/72714161-8b6f7400-3b6e-11ea-9789-e65dbf77599f.png)

**Comment by minhcasi** [comment]
@bobozd - pls share your config file and the screenshot of the purchase screenshot from http://codecayon.net/downloads - thanks

**Comment by minhcasi** [comment]
moved to #1885
