### ISSUE TITLE
After login refresh home screen 

### ISSUE THREAD

**Issue by inimist** [inspireui/support#1879]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

 When I see the app as a guest user price is different, and when I logged in as a different user role price is different but after the login, the home screen doesn't reload to update prices, I have to manually reload the screen to see price changes.   So How I can refresh the app after login automatically?   

  **Proof of my purchased:**
 
![Screenshot at Jan 03 15-33-38](https://user-images.githubusercontent.com/447618/72716689-a8b93800-3b98-11ea-9b35-fe69e1d56fbf.png)

**Comment by minhcasi** [comment]
Hi Mohit, we got a lot of your spam questions on our email/ticket regarding the customization, pls try your best google before asking the question.

Also, contact your Client mj_brainstack request us for further supporting - thank you for your understanding
