### ISSUE TITLE
App Documentation link is not working

### ISSUE THREAD

**Issue by samber91** [inspireui/support#188]
Hi, mstore multivendor documentation link is not working. may i have it please ? thank you

**Comment by samber91** [comment]
Also, can i a video explaining how to configure chat function and clothing features as XL, L , S and color please ? thank you

**Comment by luyx2412** [comment]
Hi @samber91 this is the document mstore-multivendor https://inspireui.github.io/mstore-mv/docs/introduce

Thanks
