### ISSUE TITLE
[MStore] - Login does not work (Loading but nothing happens)

### ISSUE THREAD

**Issue by C4l4ver4** [inspireui/support#1880]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
I have bought the MStore EXPO app and enabled the "RequiredLogin: true". When I enter my credentials, the app loads, stop loading and stays on the login screen. Nothing else happens.

Also, when registering, the app sends the info to Wordpress and Wordpress creates the user BUT the app says "Welcome Undefined" and then redirects to cart and throws error: "Try to get frame out of range index NaN".

2. Screenshots issues:

3. Proof of my purchased:
https://ibb.co/mR7d1TG

3. Config files (optional)

**Comment by minhcasi** [comment]
Hi dear, pls post the comment on this link to verify the purchase again as we could not see your user name - https://codecanyon.net/item/beostore-complete-react-native-template-for-ecommerce/17010642

Also, create your all issues to one ticket - thank you!

**Comment by C4l4ver4** [comment]
I commented as "Chrisklovitz"

**Comment by C4l4ver4** [comment]
Also, from closed #1881 : 
My issue:
My client has a plugin that hides the prices if the user is not logged in. It displays "Login to buy". If the plugin is activated, the app says: "Sorry, cannot list resources".
Do you have an easy solution to display "Login to buy" if the user is not logged in, please?

**Comment by minhcasi** [comment]
Could you zip your common folder from the mobile app and show us the URL of your website regarding to this issue  - thanks

**Comment by C4l4ver4** [comment]
Yes can you please send me an email to do this? Because I do not want to display it publicly, thank you

**Comment by C4l4ver4** [comment]
Can we please move to Skype because the time it takes for you to answer is ridiculous, this should work out of the box. No I don't want to put a zip out there with my personal informations and website url, I'll give it to you via skype. Thank you

**Comment by minhcasi** [comment]
pls send to support@inspireui.com - thanks

**Comment by C4l4ver4** [comment]
Email sent

**Comment by minhcasi** [comment]
Hi, thank you for the detail and email. It seems you need to customize the Rest API to support these features, also customize the product card view to support display the Pricing. 

As this is kind of advance customize and required a lot of change that is not included from out support scope, please try your best with this custom work.

Let us know if you need any questions.

**Comment by C4l4ver4** [comment]
I'm sorry but HELL NO. How dare you closing this? The login of your app does not work. It is not because of anything about my wordpress. It is because YOUR LOGIN DOES NOT WORK. Give me a fix because your code is broken.

**Comment by C4l4ver4** [comment]
I gave you a 1 star review for taking me slightly and I am asking for a full refund. This is unacceptable. Also, I reported you to Codecanyon for fraud and will request for a ban of your account.
