### ISSUE TITLE
[MStore] - Error if prices are not shown

### ISSUE THREAD

**Issue by C4l4ver4** [inspireui/support#1881]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
My client has a plugin that hides the prices if the user is not logged in. It displays "Login to buy". If the plugin is activated, the app says: "Sorry, cannot list resources". 

Do you have an easy solution to display "Login to buy" if the user is not logged in, please?

2. Screenshots issues:

3. Proof of my purchased:
https://ibb.co/mR7d1TG

3. Config files (optional)

**Comment by minhcasi** [comment]
pls move to ticket #1881
