### ISSUE TITLE
[MStore] - How to add custom fields to Registration/Sign UP?

### ISSUE THREAD

**Issue by C4l4ver4** [inspireui/support#1882]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
I would like to add the following custom fields to the registration: 

- Business Name (optional)
- A.B.N if applicable (optional)
- Select Your State* (from list already made: 9 choices)
- Mobile Phone Number*

How to do this?

2. Screenshots issues:

3. Proof of my purchased:
https://ibb.co/mR7d1TG

3. Config files (optional)

**Comment by minhcasi** [comment]
Hi, these custom fields may not work with the default WooCommerce Rest API - thank you!

pls move to ticket #1880
