### ISSUE TITLE
[FluxNews] - How to put wordpress pages (not post) into the app

### ISSUE THREAD

**Issue by emmanuelalex** [inspireui/support#1883]
Hi,
I can link posts by their category ids into the app, but how to i put pages into the app?

**Comment by minhcasi** [comment]
Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads  it's used to verify your proof of purchase? sorry for any inconvenience - Thank you!

**Comment by emmanuelalex** [comment]
![image](https://user-images.githubusercontent.com/4994251/72732825-8ee81700-3bd1-11ea-81c5-7515be267624.png)

**Comment by emmanuelalex** [comment]
Hi

**Comment by minhcasi** [comment]
@emmanuelalex  sorry for the late response 

You can update the common/config.json and add category to load posts, for multi-category you can use the tag ID, it does not support multi ID on the current release.

The Page could be load via Webview, example

```
 Navigator.push(
                                      context,
                                      MaterialPageRoute(
                                          builder: (context) => WebView(
                                              url:
                                                  "https://inspireui.com/about",
                                              title: "About Us")))
```
