### ISSUE TITLE
CeBuilder

### ISSUE THREAD

**Issue by vila00** [inspireui/support#1884]
I installed CeBuilder on Mac OS MOJAVE 10.14.6, but when starting it gives this error: https://prnt.sc/qq7msr. What should I do?

Process:               CeBuilder [1574]
Path:                  /Applications/CeBuilder.app/Contents/MacOS/CeBuilder
Identifier:            org.develar.ElectronReact
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           CeBuilder [1574]
User ID:               501

Date/Time:             2020-01-20 10:54:51.871 -0100
OS Version:            Mac OS X 10.14.6 (18G2022)
Report Version:        12
Anonymous UUID:        4FA7B1EA-74F7-9BA4-9E0D-02136835E772

Sleep/Wake UUID:       6C633CC8-8ABD-4C62-9D0F-20AA2779F4F8

Time Awake Since Boot: 16000 seconds
Time Since Wake:       1600 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1

kernel messages:

VM Regions Near 0 (cr2):
--> 
    __TEXT                 0000000108815000-0000000108816000 [    4K] r-x/rwx SM=COW  

Thread 0 Crashed:
0                                 	0x0000000116420000 _dyld_start + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x00007ffee73eaba8
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x0000000116420000  rfl: 0x0000000000000200  cr2: 0x0000000000000000
  
Logical CPU:     0
Error Code:      0x00000000
Trap Number:     0

Binary Images:
       0x108815000 -        0x108815ffb + (0) <6E272AEB-51ED-363B-B2D0-1E8B0C094EDF> 
       0x11641f000 -        0x11648970f + (655.1.1) <B3D9DDCB-5AA7-3674-9608-16B5AA4AA494> 

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 9852
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=608K resident=0K(0%) swapped_out_or_unallocated=608K(100%)
Writable regions: Total=8400K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8400K(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8192K        1 
__DATA                             232K        3 
__LINKEDIT                         176K        2 
__TEXT                             432K        2 
shared memory                        8K        2 
===========                     =======  ======= 
TOTAL                             64.8M       11 

Model: iMac19,2, BootROM 1037.60.50.0.0, 6 processors, Intel Core i5, 3 GHz, 16 GB, SMC 2.47f2
Graphics: kHW_AMDRadeonPro560XItem, Radeon Pro 560X, spdisplays_pcie_device, 4 GB
Memory Module: BANK 0/ChannelA-DIMM0, 8 GB, DDR4, 2667 MHz, Micron, 8ATF1G64HZ-2G6E3
Memory Module: BANK 2/ChannelB-DIMM0, 8 GB, DDR4, 2667 MHz, Micron, 8ATF1G64HZ-2G6E3
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x7BF), wl0: Oct 23 2019 08:32:36 version 9.137.11.0.32.6.36 FWID 01-671ec60c
Bluetooth: Version 6.0.14d3, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: APPLE HDD HTS541010A9E632, 1 TB
USB Device: USB 3.1 Bus
USB Device: Elements 10A8
USB Device: FaceTime HD Camera (Built-in)
Thunderbolt Bus: iMac, Apple Inc., 42.1

**Comment by minhcasi** [comment]
Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads  it's used to verify your proof of purchase? sorry for any inconvenience - Thank you!

**Comment by vila00** [comment]
CARLOS MIRANDA 

Av. São Vicente, Palmarejo - 7002 PRAIA Telefone: 354-28-48

Email: carlos@hostkriolo.cv www.hostkriolo.cv 

 

“As mensagens electrónicas têm o mesmo valor de que as em suporte papel, tendo, em principio, o mesmo tratamento quer pela Adminstração Pública quer pelos particulares.” - Artº 4º da Lei da Modernização Administrativa (Lei nº 39/IV/2004 de 2 de Fevereiro

AVISO DE CONFIDENCIALIDADE:

Esta mensagem, assim como os ficheiros eventualmente anexos, é confidencial e reservada apenas ao conhecimento da(s) pessoa(s) nela indicada(s) como destinatária(s). Se não é o seu destinatário, ou se lhe foi enviada por erro, solicitamos que não faça qualquer uso do respectivo conteúdo e proceda à sua destruição, notificando o remetente.

LIMITAÇÃO DE RESPONSABILIDADE:

A segurança da transmissão de informação por via electrónica não pode ser garantida pelo remetente, o qual, em consequência, não se responsabiliza por qualquer facto susceptível de afectar a sua integridade.

CONFIDENTIALITY NOTICE:

This message, as well as existing attached files, is confidential and intended exclusively for the individual(s) named as addressees. If you are not the intended recipient, or if it was sent to you by error, you are kindly requested not to make any use of its contents and to proceed to the destruction of the message, thereby notifying the sender.

DISCLAIMER:

The sender of this message can not ensure the security of its electronical transmission and consequently does not accept liability for any fact which may interfere with the integrity of its content. 

 

 

De: Minh Pham <notifications@github.com>
Responder A: inspireui/support <reply@reply.github.com>
Data: segunda-feira, 20 de janeiro de 2020, 11:59
Para: inspireui/support <support@noreply.github.com>
Cc: Carlos Miranda <carlos@hostkriolo.cv>, Author <author@noreply.github.com>
Assunto: Re: [inspireui/support] CeBuilder (#1884)

 

Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads it's used to verify your proof of purchase? sorry for any inconvenience - Thank you!

**Comment by inspireui-support** [comment]
@vila00 - pls help to update the Cebuilder to 0.39 to fix the issue on Mac OS

Feel free to reopen the ticket if you have any issue - very best!
