### ISSUE TITLE
[FLusListing] - help

### ISSUE THREAD

**Issue by bobozd** [inspireui/support#1885]
**My issue:**

I run it seccesfully on my adnroid emulator. Thanks!
I got some errorrs like this:
1. When I click on SEE ALL I got some erros with this log:
════════ (292) Exception caught by widgets library ═════════════════════════════════════════════════
The getter 'priceRange' was called on null.
Receiver: null
Tried calling: priceRange
The relevant error-causing widget was: 
  ProductCard file:///C:/Users/...App_01/lib/widgets/home/product_list_layout.dart:119:15

![screen_1](https://user-images.githubusercontent.com/28021993/72726027-a0a4cc80-3b87-11ea-8146-0ce7d293194d.jpg)
![screen_2](https://user-images.githubusercontent.com/28021993/72726036-a4385380-3b87-11ea-8101-d9ceb5802605.jpg)
![screen_3](https://user-images.githubusercontent.com/28021993/72726148-ecf00c80-3b87-11ea-8786-b46875e9dace.jpg)

**NOTE:
I do not want any price range to be included in website and inside flux app. I need to remove this completely !**

2. When click on one listing there is eeror on the bottom? ...Error. NoSuchMethodError ...
![screen_4](https://user-images.githubusercontent.com/28021993/72726720-56bce600-3b89-11ea-9f26-e87c00fb9d1f.jpg)

**Config files (optional)**
[config.zip](https://github.com/inspireui/support/files/4086121/config.zip)

**Comment by vuthanhtoan30** [comment]
Hi bobozd,

It seems you have not enabled job_listing_categories on your site yet. Also are you using the config files I sent you yesterday or you have made new ones? Because the file "config.json" in the config.zip file above is still the same as the one you gave me the other day.

Please make sure that you have enabled  job_listing_categories and replace the files I gave you so I can help you asap. Thank you for your patient.

enable job_listing_categories: 
[job_listing_category.zip](https://github.com/inspireui/support/files/4088982/job_listing_category.zip)

**Comment by bobozd** [comment]
Hi, I replaced config files you send me on email, but problems still the same.Error logs and few screenshots attached.
════════ (130) Exception caught by widgets library ═════════════════════════════════════════════════
The getter 'priceRange' was called on null.
Receiver: null
Tried calling: priceRange
The relevant error-causing widget was: 
  ProductCard file:///C:/Users/Studio%20GRiD/AndroidStudioProjects/Renderize_FlutterApp_01/lib/widgets/product/product_list.dart:138:34
════════════════════════════════

ERROR LOGS:
[error_logs.txt](https://github.com/inspireui/support/files/4090502/error_logs.txt)

SCREENS:
![screen_5](https://user-images.githubusercontent.com/28021993/72796762-30a64d00-3c40-11ea-9902-1d7445ae2758.jpg)
![screen_6](https://user-images.githubusercontent.com/28021993/72796773-3439d400-3c40-11ea-849e-4b419cd55035.jpg)
![screen_7](https://user-images.githubusercontent.com/28021993/72796777-369c2e00-3c40-11ea-8555-81f47311c80c.jpg)

**Comment by philipvu30** [comment]
Hi bobozd,

Would you mind if I ask for your username and password for your site so I could help you check what is wrong?

Please send them privately to this email: toan@inspireui.com. Thank you for your understanding and have a nice day :)

**Comment by bobozd** [comment]
Hello,  yes please take a look. here is your access data:
user: SupportApp
pass: tmNVwtKyY3J&pnJRpzssl%hn

IMPORTANT:
Yesterday I receive email hrom wordpress about instability caused by
Listapp plugin. Now I'm pretty sure building my app is related to that.
here is what I receive:

Since WordPress 5.2 there is a built-in feature that detects when a plugin
or theme causes a fatal error on your site, and notifies you with this
automated email.
In this case, WordPress caught an error with one of your plugins, ListApp
Mobile Manager.
First, visit your website (https://renderize.net/) and check for any
visible issues. Next, visit the page where the error was caught (
https://renderize.net/wp-admin/post.php) and check for any visible issues.
Please contact your host for assistance with investigating this issue
further.

If your site appears broken and you can't access your dashboard normally,
WordPress now has a special "recovery mode". This lets you safely login to
your dashboard and investigate further.
https://renderize.net/renderize-entrance/?action=enter_recovery_mode&rm_token=hdLPbc20wUYnSWaCycICh9&rm_key=WrJyFiDdsaSlFKW7hOENLE
To keep your site safe, this link will expire in 1 day. Don't worry about
that, though: a new link will be emailed to you if the error occurs again
after it expires.

When seeking help with this issue, you may be asked for some of the
following information:
WordPress version 5.3.2
Current theme: Renderize (version 1.0)
Current plugin: ListApp Mobile Manager (version 1.6.0)
PHP version 7.2.26-1+0~20191218.33+debian9~1.gbpb5a34b

**Comment by bobozd** [comment]
Hello, any progress?

**Comment by bobozd** [comment]
> Hi bobozd,
> 
> Would you mind if I ask for your username and password for your site so I could help you check what is wrong?
> 
> Please send them privately to this email: [toan@inspireui.com](mailto:toan@inspireui.com). Thank you for your understanding and have a nice day :)

I send it 3 days ago, any progress ???

**Comment by philipvu30** [comment]
Hi bobozd,

Due to Lunar New Year celebration, our team is currently on vacation and will be back on next Thursday. And for your issue, we are really sorry because the theme's update recently changed some properties so it causes minor bugs in your app. It will be solved in the next update of the app. Thank you for your understanding.

**Comment by bobozd** [comment]
Thanks for reply, when do you plan new app update?

**Comment by philipvu30** [comment]
Hi bobozd,

I have tested your site with the upcoming update and not found any error yet.
Currently I have not received any confirmation about the release date. But it might be released in the next few days. 
As we are back in working, feel free to ask any question if you are in trouble. Thank you for your patience.

Here is the result after testing your site: 
[bobozd.zip](https://github.com/inspireui/support/files/4132120/bobozd.zip)
