### ISSUE TITLE
[FluxStore] SMS registration country flag

### ISSUE THREAD

**Issue by Pars1vaLl** [inspireui/support#1889]
Hi team,

 1. In SMS registretion field while choosing country code '+7' - the flag of Kazakhstan appears next to number. Although Russian code is also '+7'. So how can we change flag of Kazakhstan to flag of Russia.

 2. Our app is heavy, about 80MB for Android. I noticed that your demo app is only 16 MB. How can we achieve same results as you? 

Purchase Code: http://prntscr.com/qqeel1

Thank you

**Comment by minhcasi** [comment]
@Pars1vaLl 

1- we will change to this lib for better UX - it could fix your issue - https://pub.dev/packages/country_pickers

2. Follow this guide to generate the abb file https://flutter.dev/docs/deployment/android

**Comment by minhcasi** [comment]
We have tried new library but the current one is a more stable and powerful feature with validating, pls try to customize base on your requirement for the flag of Kazakhstan - thank you!
