### ISSUE TITLE
[MStore Pro] - App automatically close after confirming the order

### ISSUE THREAD

**Issue by juniortimeline** [inspireui/support#1890]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: App automatically close after confirming the order

2. Screenshots issues: https://drive.google.com/file/d/1-JVRGKvtDk1BmfZ0nTZH9zWNQc6AbHfW/view

3. Proof of my purchased: https://codecanyon.net/comments/23526940

3. Config files (optional)

**Comment by minhcasi** [comment]
@juniortimeline could you zip the source and share to support@inspireui.com - thanks

**Comment by juniortimeline** [comment]
> @juniortimeline could you zip the source and share to [support@inspireui.com](mailto:support@inspireui.com) - thanks

@minhcasi Already sent. Thank You.

**Comment by juniortimeline** [comment]
Same issue using EXPO.
After "Confirm Order" here is the error message on the screen

TypeError: undefined is not an object (evaluating 'list[_this.state.selectedIndex].id')

PaymentOptions#nextStep
    F:\User\ProjectFolder\Project\EXPO\src\containers\Cart\Payment\index.js:90:20
TouchableOpacity.props.onPress
    F:\User\ProjectFolder\Project\EXPO\src\components\Button\Button.js:106:13
createReactClass$argument_0.touchableHandlePress
    F:\User\ProjectFolder\Project\EXPO\node_modules\react-native\Libraries\Components\Touchable\TouchableOpacity.js:264:45
touchableHandlePress
    [native code]:0
TouchableMixin._performSideEffectsForTransition
    F:\User\ProjectFolder\Project\EXPO\node_modules\react-native\Libraries\Components\Touchable\Touchable.js:880:34
_performSideEffectsForTransition
    [native code]:0
TouchableMixin._receiveSignal
    F:\User\ProjectFolder\Project\EXPO\node_modules\react-native\Libraries\Components\Touchable\Touchable.js:779:44
_receiveSignal
    [native code]:0
TouchableMixin.touchableHandleResponderRelease
    F:\User\ProjectFolder\Project\EXPO\node_modules\react-native\Libraries\Components\Touchable\Touchable.js:490:24
touchableHandleResponderRelease
    [native code]:0
invokeGuardedCallbackImpl
    F:\User\ProjectFolder\Project\EXPO\node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:307:15
invokeGuardedCallback
    F:\User\ProjectFolder\Project\EXPO\node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:531:36
invokeGuardedCallbackAndCatchFirstError
    F:\User\ProjectFolder\Project\EXPO\node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:555:30
executeDispatch
    F:\User\ProjectFolder\Project\EXPO\node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:722:42
executeDispatchesInOrder
    F:\User\ProjectFolder\Project\EXPO\node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:744:20
executeDispatchesAndRelease
    F:\User\ProjectFolder\Project\EXPO\node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:907:29
forEach
    [native code]:0
forEachAccumulated
    F:\User\ProjectFolder\Project\EXPO\node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:887:16
runEventsInBatch
    F:\User\ProjectFolder\Project\EXPO\node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:932:21
runExtractedPluginEventsInBatch
    F:\User\ProjectFolder\Project\EXPO\node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:1096:19
batchedUpdates$argument_0
    F:\User\ProjectFolder\Project\EXPO\node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:2796:6
batchedUpdates$1
    F:\User\ProjectFolder\Project\EXPO\node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:18791:14
batchedUpdates
    F:\User\ProjectFolder\Project\EXPO\node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:2709:30
batchedUpdates$argument_0
    F:\User\ProjectFolder\Project\EXPO\node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:2794:17
receiveTouches
    F:\User\ProjectFolder\Project\EXPO\node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:2870:28
__callFunction
    F:\User\ProjectFolder\Project\EXPO\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:436:47
__guard$argument_0
    F:\User\ProjectFolder\Project\EXPO\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:111:26
__guard
    F:\User\ProjectFolder\Project\EXPO\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:384:10
__guard$argument_0
    F:\User\ProjectFolder\Project\EXPO\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:110:17
callFunctionReturnFlushedQueue
    [native code]:0

**Comment by luyx2412** [comment]
Hi @juniortimeline Please send your Config.js and AppConfig.json via luyxtran264@gmail.com

Thanks

**Comment by juniortimeline** [comment]
> > @juniortimeline could you zip the source and share to [support@inspireui.com](mailto:support@inspireui.com) - thanks
> 
> @minhcasi Already sent. Thank You.

@luyx2412

**Comment by juniortimeline** [comment]
@minhcasi @luyx2412 @inspireui-support @trunghieuvn  Follow Up Please. Thank You

**Comment by luyx2412** [comment]
Hi @juniortimeline Can you send again your config via luyxtran264@gmail.com and mention your issue in subject email.

Thanks

**Comment by juniortimeline** [comment]
@luyx2412 I already sent. Thank You

**Comment by tarik-amaterasu** [comment]
well, im not sure. but it seems you haven't add any payment method on wordpress that's the reason                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
a 0 index in empty list can return undefined 
2nd, it's weird seeing this part list[_this.state.selectedIndex].id 
could you check ~/src/containers/cart/payment/index.js line:90 
it should be this way 
payment_method: list[this.state.selectedIndex].id,

**Comment by luyx2412** [comment]
Hi @juniortimeline I just checked your code, please make sure you installed payment in your admin. Follow the video guide to install payment. https://docs.inspireui.com/mstore/multi-payments/
to open your payment gateway.

![image](https://user-images.githubusercontent.com/8909619/73951711-86614180-4930-11ea-8545-da685f5ae755.png)

Thanks

**Comment by juniortimeline** [comment]
> Hi @juniortimeline I just checked your code, please make sure you installed payment in your admin. Follow the video guide to install payment. https://docs.inspireui.com/mstore/multi-payments/
> to open your payment gateway.
> 
> ![image](https://user-images.githubusercontent.com/8909619/73951758-a1cc4c80-4930-11ea-9fab-b0332e0a1a6a.png)
> 
> Thanks
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/abde6bed5239ae865239febe2feb2d96ddc2b838/687474703a2f2f646f63732e696e737069726575692e636f6d2f696d616765732f6d6574612f47686f73742d446f63732e6a7067">InspireUI Document**[MStore Pro - Complete React Native template for e-commerce](http://docs.inspireui.com/mstore/multi-payments/)**Professional Mobile Store Solution for your business – supports to convert your current WooCommerce website to mobile store app easily

@luyx2412 Thank You so much and I appreciate your help.
