### ISSUE TITLE
[ListApp] - job_listing type null

### ISSUE THREAD

**Issue by Lucisu** [inspireui/support#1891]
1. My issue:
Hello! I'm trying to setup ListApp, following the doc: "https://docs.inspireui.com/listpro/getting-started".
But, appears that the plugin ListApp Mobile Manager it's broken.

When they call parent cronstructor with "job_listing" as parameter, in
```www/wp-content/plugins/listapp-mobile-manager/rest-api/class.api.fields.php```, the custom post type it's not initialised yet, so throws a error saying "name" propriety can't be accesed, because it is null in "www/wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php"

**Full error:**
Notice: Trying to get property 'name' of non-object in /home/user/public_html/wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php on line 45

**Technical Details**

Server LiteSpeed
Wordpress version: 5.3.2
PHP version: 7.3.8
ListingPro version: 2.5.3
ListApp Mobile Manager :1.6.0

3. Proof of my purchased:
Will be posted a comment in product page.

**Comment by minhcasi** [comment]
@Lucisu - could you help to zip the common folder and send back us for investigating the issue - thank you!

**Comment by minhcasi** [comment]
@Lucisu - also check if you have turned on the setting from https://tppr.me/2TtK1

**Comment by Lucisu** [comment]
Follow the file + some screenshots. About the Listing option, it's enabled :/

Thank you!

[Common+Screenshots.zip](https://github.com/inspireui/support/files/4089080/Common%2BScreenshots.zip)

**Comment by inspireui-support** [comment]
closed as request refund - thank you!
