### ISSUE TITLE
[MStore Pro] - Referral & reward system ("Feature Request " ) 

### ISSUE THREAD

**Issue by Riyashanke** [inspireui/support#1893]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. Actually your app is too good, but there are some features it will make perfect for e-commerce app. So in the next update kindly add a Referral option as well as Reward option to app. Particularly Referral Program is very important for an E-commerce app. So for the next update kindly add this options that will be very useful as well as helpful. 

3. Proof of my purchased:
https://user-images.githubusercontent.com/56667597/67098771-64557f00-f1da-11e9-9ed9-aa6ab62606ee.png

**Comment by minhcasi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Referral & reward system](https://trello.com/c/7TR02msB/14-referral-reward-system)

**Comment by minhcasi** [comment]
@Riyashanke - thank you so much for your request, i've moved to our backlog for the team investigating - thank you!
