### ISSUE TITLE
[FluxStore] - i have problem with file dart

### ISSUE THREAD

**Issue by DiouriMed** [inspireui/support#1894]
Hi,
I have problem with file dart

<img width="1440" alt="Capture d’écran 2020-01-21 à 09 51 49" src="https://user-images.githubusercontent.com/40725296/72789454-1cf4e980-3c34-11ea-9a5f-18384b9e3ace.png">
<img width="1440" alt="Capture d’écran 2020-01-21 à 09 38 03" src="https://user-images.githubusercontent.com/40725296/72789456-1cf4e980-3c34-11ea-997f-a9e2ed687bde.png">
<img width="1440" alt="Capture d’écran 2020-01-21 à 09 56 57" src="https://user-images.githubusercontent.com/40725296/72789634-680efc80-3c34-11ea-8cee-cc8bf038847e.png">

**Comment by DiouriMed** [comment]
/Users/diourimed/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale fr-MA)
    • Flutter version 1.12.13+hotfix.5 at /Users/diourimed/flutter
    • Framework revision 27321ebbad (6 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/diourimed/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (2 available)
    • AOSP on IA Emulator • emulator-5554                        • android-x86 • Android 9 (API 28) (emulator)
    • iPhone 11 Pro Max   • EC9EC360-BD99-4432-95E5-48AF206542E4 • ios         • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

! Doctor found issues in 1 category.
Process finished with exit code 0

**Comment by DiouriMed** [comment]
requests a response as soon as possible.

**Comment by DiouriMed** [comment]
Launching lib/main.dart on AOSP on IA Emulator in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/diourimed/Downloads/mobile/FluxStore-vendor-1.6.2/source/android/build.gradle' line: 31

* What went wrong:
A problem occurred evaluating root project 'android'.
> A problem occurred configuring project ':app'.
   > Could not resolve all artifacts for configuration ':app:classpath'.
      > Could not resolve gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.12.1, 0.99.99].
        Required by:
            project :app
         > Could not resolve gradle.plugin.com.onesignal:onesignal-gradle-plugin:0.12.6.
            > Could not get resource 'https://plugins.gradle.org/m2/gradle/plugin/com/onesignal/onesignal-gradle-plugin/0.12.6/onesignal-gradle-plugin-0.12.6.pom'.
               > Could not GET 'https://plugins-artifacts.gradle.org/gradle.plugin.com.onesignal/onesignal-gradle-plugin/0.12.6/9dd3a967b58ff131a5c778042cdd2f965e99067c98c1b7ffd1adc552b7107522/onesignal-gradle-plugin-0.12.6.pom'.
                  > plugins-artifacts.gradle.org: nodename nor servname provided, or not known

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 39s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by inspireui-support** [comment]
@DiouriMed - could you help to update latest Fluxstore 1.6.3 that includes some bug fix and resolve build issues - thank you!

**Comment by minhtruong315** [comment]
@DiouriMed add my skype: minhtruong315
I'll help u check it

**Comment by inspireui-support** [comment]
@DiouriMed - pls try with latest 1.6.3 from the http://codecayon.net/downloads to fix the issue

You can also remove the folder flutter_assets and reinstall again - let us know if you have any further issues, thank you!

**Comment by DiouriMed** [comment]
Le ven. 31 janv. 2020 à 08:16, InspireUI Team <notifications@github.com> a
écrit :

**Comment by DiouriMed** [comment]
Yes I see new version
But tell me how to change the app icon
Because when add code on terminal are not work
The Arabic language is not available on a copy 1.6.3


Le ven. 31 janv. 2020 à 14:27, Mohammed Diouri <diouri.meed@gmail.com> a
écrit :
