### ISSUE TITLE
[Fluxstore Pro - Woo] - Categories are not loaded into the application

### ISSUE THREAD

**Issue by j-violet** [inspireui/support#1895]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
Categories are not loaded into the application

2. Screenshots issues:
![Issue-CategoriesNotLoadedt](https://user-images.githubusercontent.com/60133298/72795187-c4dbd880-3c6f-11ea-9097-403f35fd30d3.png)

3. Proof of my purchased:
![Proof-JepunV](https://user-images.githubusercontent.com/60133298/72795212-cdccaa00-3c6f-11ea-8f6d-1b6bc4d1015b.png)

4. Config files (optional)
[config.dart.txt](https://github.com/inspireui/support/files/4090421/config.dart.txt)

**Comment by j-violet** [comment]
Config files (reuploaded the correct one)
[config.dart-reuploaded.txt](https://github.com/inspireui/support/files/4090545/config.dart-reuploaded.txt)

**Comment by minhcasi** [comment]
@j-violet - pls try to change the category id to match with your category id from the Woocommerce site - thank you!

**Comment by j-violet** [comment]
Thanks @minhcasi that solved the problem. 
Another problem is that blog content are not loaded
![image](https://user-images.githubusercontent.com/60133298/72811942-37aa7b00-3c93-11ea-9a51-5eec625073ae.png)

**Comment by j-violet** [comment]
The blog content already solved. So I closed this ticket. Thanks
