### ISSUE TITLE
[EvaStore] - customization issues

### ISSUE THREAD

**Issue by BMehdii** [inspireui/support#1897]
1. My issue: when I open the simulator and try to make some changes in the code nothing happens after reloading the app...
If you can help me to start customizing the app, I already change all the URLs on AppConfig.jason but I can't see any changes

2. Screenshots issues: 

<img width="1280" alt="Screen Shot 2020-01-21 at 1 53 41 PM" src="https://user-images.githubusercontent.com/60139508/72806984-aae1cc00-3c56-11ea-8421-fafdf4db941c.png">
<img width="1280" alt="Screen Shot 2020-01-21 at 1 54 20 PM" src="https://user-images.githubusercontent.com/60139508/72806985-aae1cc00-3c56-11ea-86aa-3c2f623ac5e6.png">
<img width="1280" alt="Screen Shot 2020-01-21 at 1 55 18 PM" src="https://user-images.githubusercontent.com/60139508/72806986-ab7a6280-3c56-11ea-830c-d0e64d8dd69c.png">

3. Proof of my purchased:
<img width="1280" alt="purchase-proof" src="https://user-images.githubusercontent.com/60139508/72807006-b7662480-3c56-11ea-8f9b-f23ae2919345.png">

**Comment by minhcasi** [comment]
@BMehdii - pls edit it from appconfig.json

also check this guide for more detail https://docs.inspireui.com/evastore/getting-started/

**Comment by BMehdii** [comment]
I have read this guide and I have already edited the appconfig.json file as I mentioned earlier ... but nothing happened

**Comment by BMehdii** [comment]
@minhcasi please check your email

**Comment by BMehdii** [comment]
issue fixed, I had to delete the cache on the simulator.
