### ISSUE TITLE
[fluxstore] -i have issue login with apple login and sms and PayPal integrate error , woocommerce

### ISSUE THREAD

**Issue by huntelar10** [inspireui/support#1898]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
- login with facebook, google,email working fine
1- but apple login and sms not working.
2-  PayPal not working also.
2. Screenshots issues:
https://drive.google.com/drive/folders/1v7aZ3IPhGybWCeZ4YYm3pdD5XGLYrt0t?usp=sharing
3. Proof of my purchased:
https://drive.google.com/file/d/1vLR_j_5lfEe239dGGfPgcAoYGgcIFreV/view?usp=sharing
3. Config files (optional)

**Comment by huntelar10** [comment]
Version: 1.6.2

**Comment by huntelar10** [comment]
@minhcasi @minhtruong315

**Comment by huntelar10** [comment]
guys if have documents for apple login and way to fix PayPal issues , even charge me by hourly rate . my client waiting me

**Comment by huntelar10** [comment]
one more issue , in iOS , when submit the order , and press back to store , screen will be black 

2020-01-23 20:35:41.825177+0400 Runner[8015:2613603] Can't end BackgroundTask: no background task exists with identifier 29 (0x1d), or it may have already been ended. Break in UIApplicationEndBackgroundTaskError() to debug.

**Comment by minhtruong315** [comment]
@huntelar10 add my skype: minhtruong315
I'll help u check it

**Comment by saioufe** [comment]
can someone help me  , i can't make the google login or fb login or email login to work ???

**Comment by huntelar10** [comment]
@minhtruong315 hello dear any help for my issue ?

**Comment by minhtruong315** [comment]
@huntelar10 I checked your source code. it's working well for apple sign in
https://gofile.io/?c=waAMvs

**Comment by minhtruong315** [comment]
@huntelar10 how are your issues?

**Comment by minhtruong315** [comment]
supported via skype
