### ISSUE TITLE
BUILD FAILS

### ISSUE THREAD

**Issue by Ibrahimmohammedevuti** [inspireui/support#1899]
am having the following errors, please help me resolve it.
![1](https://user-images.githubusercontent.com/38354564/72822727-067a7c80-3c8c-11ea-96be-8efccce86a48.JPG)
![2](https://user-images.githubusercontent.com/38354564/72822730-07131300-3c8c-11ea-8ec2-2e2df8e4c11a.JPG)
![3](https://user-images.githubusercontent.com/38354564/72822731-07131300-3c8c-11ea-85cb-dabe6130d82f.JPG)

**Comment by minhcasi** [comment]
Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads  it's used to verify your proof of purchase? sorry for any inconvenience - Thank you!

**Comment by Ibrahimmohammedevuti** [comment]
ok here is the screenshot of my download page, but i had to cancel out my username for security reasons thank you.
![mstore proof](https://user-images.githubusercontent.com/38354564/72868600-eb475580-3cfb-11ea-8d64-27102348982a.jpg)

**Comment by minhcasi** [comment]
@Ibrahimmohammedevuti - could you download the nodejs 12.x to fix the issue - https://nodejs.org/en/

**Comment by Ibrahimmohammedevuti** [comment]
ok, am installing node 12 now, i will let you know of any errors once am through

**Comment by Ibrahimmohammedevuti** [comment]
i am still having some errors, i have installed the node 12 and run the android setup, but buid fails with the following errors.
![4](https://user-images.githubusercontent.com/38354564/72921707-36e21980-3d65-11ea-9483-fabd4cb9295a.JPG)
![5](https://user-images.githubusercontent.com/38354564/72921708-36e21980-3d65-11ea-9e24-60e8f5446aec.JPG)
![6](https://user-images.githubusercontent.com/38354564/72921709-377ab000-3d65-11ea-924e-8e8fd4eee93b.JPG)

**Comment by luyx2412** [comment]
Hi @Ibrahimmohammedevuti Please switch to Node 10 which is stable than 12.

Thanks

**Comment by Ibrahimmohammedevuti** [comment]
you meam i should reinstall android studio

**Comment by Ibrahimmohammedevuti** [comment]
i just installed node 10 and android studio, but am still having the following errors, i need to deliver this app on monday.
![7](https://user-images.githubusercontent.com/38354564/72996013-56378000-3e13-11ea-9f71-d2c48f2ad2d8.JPG)
![8](https://user-images.githubusercontent.com/38354564/72996014-56378000-3e13-11ea-8a93-b78b07f03c80.JPG)

**Comment by inspireui-support** [comment]
@Ibrahimmohammedevuti - could you check if you can able to run the Example project base on this guide - https://facebook.github.io/react-native/docs/getting-started (this is the basic setup for the React Native framework) - it seems the issues are related to your Android SDK on your PC - thank you!
