### ISSUE TITLE
Problems with ListApp 1.5.2

### ISSUE THREAD

**Issue by ZamsiteZambia** [inspireui/support#19]
ListApp
d9ed43ef-7eb4-42be-b1ee-713b1c84b9f6

I tried to run ListApp1.5.2 on PC using yarn, CLI and js node but am having a 'npm install' issue whenever I try 'expo start'. However it keeps on showing dependency issues.

![yarn install error](https://user-images.githubusercontent.com/45100245/48625958-4cb5bb00-e9b9-11e8-9b15-c8bbf2ed864c.png)
![yarn install error 2](https://user-images.githubusercontent.com/45100245/48625973-563f2300-e9b9-11e8-9039-b389f349b6e8.png)

**Required Info (please complete the following information):**
 - Product: 
 - Your Purchased Code:
Get from https://codecanyon.net/downloads, we may not reply if you are not our customer.

**Describe the bug**

**Screenshots**

**Additional context**
Add any other detail logs about the problem here.
If possible please share your config.js that use for the app setting

#minhcasi

**Comment by thangvo9x** [comment]
Hi . Follow above image, I recognized, your pc seem, yarn isn't installed correctly.
Please try install yarn again with the message " successfully" and try it again.
Thanks for your choice from our product. Goodluck !

**Comment by ZamsiteZambia** [comment]
Hi thangvo9x

I have installed yarn with 'success', but when the project opens in Expo CLI, I get a error from 'BlurView'...
![blurview error](https://user-images.githubusercontent.com/45100245/48754478-6fd2ba00-ec9a-11e8-8159-23bde66ef720.png)

Regards

**Comment by minhcasi** [comment]
Hi @ZamsiteZambia please try to select LAN to see if can be fixed, and make sure you have already run the Android Simulator before click to run the Android emulator 

Please reopen if you still could not fix the issue - thank you!
