### ISSUE TITLE
[Listapp] Post Listing Issue

### ISSUE THREAD

**Issue by reconshield** [inspireui/support#190]
Purchase code: 23ee6c94-1eb8-4ffd-842f-7600d97f41d0 |

new update version working good.only have 2 issue.

1) when click booking from listing page.i get error..

2) when summit listing. listing type not listing.i still can continue post it..but in the end getting error. i have add woocommerce keys correctly.
![simulator screen shot - iphone x - 2019-01-17 at 10 28 58](https://user-images.githubusercontent.com/25501496/51299334-1650f680-1a63-11e9-99fc-25b0fa36e13b.png)

![simulator screen shot - iphone x - 2019-01-17 at 10 28 58](https://user-images.githubusercontent.com/25501496/51299232-a2165300-1a62-11e9-8c87-99f4763030a2.png)

**Comment by thangvo9x** [comment]
Hi, You can check by this yourdomain/wp-json/wp/v2/job_listing . it has key "link_to_product"

**Comment by reconshield** [comment]
Yes..i can see wp-json list..

**Comment by reconshield** [comment]
problem solved.
