### ISSUE TITLE
[Fluxstore - Woo] - Onesignal, I can not enter the product page with notification

### ISSUE THREAD

**Issue by sketchuprzr** [inspireui/support#1900]
1. My issue:

Hello,

I made the Onesignal settings. But with the notification I sent, I want the app to open the product window I sent. How can I do that?

When I send the notification, it just opens the app. It does not go to the product page.

My test product url : pratikbakkal.com/product/pantene-sampuan-onarici-ve-koruyucu-bakim-360-ml/

2. Screenshots issues:

![image](https://user-images.githubusercontent.com/60021696/72826147-5ad02d00-3c89-11ea-85b2-f7167caea4aa.png)

![image](https://user-images.githubusercontent.com/60021696/72826183-6cb1d000-3c89-11ea-90b3-ba6c9b506bd9.png)

When clicked the notification

![image](https://user-images.githubusercontent.com/60021696/72826298-9f5bc880-3c89-11ea-8a12-185227414f8a.png)

3. Proof of my purchased:

![image](https://user-images.githubusercontent.com/60021696/72826354-b8647980-3c89-11ea-878e-536b71c965c1.png)

**Comment by minhcasi** [comment]
@sketchuprzr - the deep link for product push notification via one signal is not supported - it's only supported for Blog type, example once you create a new Post and post notify, you can open the Blog from the app - use for notifying to you user about promotion or news...
