### ISSUE TITLE
[Fluxstore] - Email and payment questions

### ISSUE THREAD

**Issue by Pars1vaLl** [inspireui/support#1901]
Hi team, I have few questions. Hope you can help me as soon as possible.

 1. I noticed that in your demo-app, users receive email from you with order details. How can I do the same for my App. And is it possible to SMS instead of email?

 2. Here is scenario: If user purchases more then 'X' $ - free delivery appears in his 'Delivery method' and 'Paid delivery' disappears. How can I reach it?

![FullSizeRender-22-01-20-12-33-1](https://user-images.githubusercontent.com/45024483/72845732-13659300-3cc1-11ea-94e8-43ef9c2e03a4.jpg)

 3.  Could you please explain more about 'Points'? How does it work? 

 4. Is it possible to remove flags all countries except one from this list?                                                                                                              
![FullSizeRender-22-01-20-12-33](https://user-images.githubusercontent.com/45024483/72845746-18c2dd80-3cc1-11ea-9956-0ba82968a8ca.jpg)

3. Proof of my purchased: http://prntscr.com/qqeel1

Thank you)

**Comment by minhcasi** [comment]
@Pars1vaLl - thank you for the suggestion, the notification order will be updated on the latest 1.6.3 as we also improve the code and mstore-api plugin

The shipping is an advanced feature and not generic for most of the site so that we may not include from the release :)
