### ISSUE TITLE
 this giving this error as soon as I opened the file in android studio

### ISSUE THREAD

**Issue by diwebde** [inspireui/support#1902]
<img width="1158" alt="Captura de ecrã 2020-01-22, às 11 34 37" src="https://user-images.githubusercontent.com/12473230/72903503-15a10f00-3d0c-11ea-869e-c9cd775a0d4a.png">

**Comment by diwebde** [comment]
<img width="1280" alt="Captura de ecrã 2020-01-22, às 11 57 34" src="https://user-images.githubusercontent.com/12473230/72904908-6580d580-3d0e-11ea-8f7e-f22e68e803ab.png">

**Comment by trunghieuvn** [comment]
please Use channel stable and
<img width="617" alt="Screen Shot 2020-01-22 at 11 41 15 PM" src="https://user-images.githubusercontent.com/19247680/72914076-af9aa300-3d70-11ea-81c2-ffa704ed8c62.png">
 update flutter version Latest

**Comment by diwebde** [comment]
<img width="1185" alt="Captura de ecrã 2020-01-22, às 16 09 27" src="https://user-images.githubusercontent.com/12473230/72925519-9a525400-3d31-11ea-8b72-bcbe6488942b.png">

**Comment by minhcasi** [comment]
@diwebde - try to install the lib by clicking this button - https://tppr.me/m6NoA 

then try to run "flutter clean" if there is still an issue and click the green (play button) to reintall the app.

Also try to run the example project successful before start to use Fluxstore - https://flutter.dev/docs/get-started/test-drive - this guide will help to install all required library for Flutter app

**Comment by diwebde** [comment]
The example project was successfully executed.
Error installing the library

<img width="1206" alt="Captura de ecrã 2020-01-23, às 10 44 07" src="https://user-images.githubusercontent.com/12473230/72989582-501eb080-3dcd-11ea-8268-bdf229f73db3.png">

**Comment by diwebde** [comment]
Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
Running Xcode build...
Xcode build done.                                           16,5s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    /Users/diegocpc/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.15.3+1/ios/Classes/FLTFirebaseAuthPlugin.m:493:38: error: no known class method for selector 'credentialWithProviderID:IDToken:rawNonce:accessToken:'
          credential = [FIROAuthProvider credentialWithProviderID:provider
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/diegocpc/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.15.3+1/ios/Classes/FLTFirebaseAuthPlugin.m:502:38: error: no known class method for selector 'credentialWithProviderID:IDToken:rawNonce:'
          credential = [FIROAuthProvider credentialWithProviderID:provider
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    2 errors generated.
    /Users/diegocpc/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_admob-0.9.0+10/ios/Classes/FLTMobileAd.m:40:17: warning: 'configureWithApplicationID:' is deprecated: Use [GADMobileAds.sharedInstance startWithCompletionHandler:] [-Wdeprecated-declarations]
      [GADMobileAds configureWithApplicationID:appId];
                    ^
    In module 'GoogleMobileAds' imported from /Users/diegocpc/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_admob-0.9.0+10/ios/Classes/FLTMobileAd.h:6:
    /Users/diegocpc/AndroidStudioProjects/flux/source/ios/Pods/Google-Mobile-Ads-SDK/Frameworks/GoogleMobileAdsFramework-Current/GoogleMobileAds.framework/Headers/GADMobileAds.h:74:5: note: 'configureWithApplicationID:' has been explicitly marked deprecated here
        GAD_DEPRECATED_MSG_ATTRIBUTE("Use [GADMobileAds.sharedInstance startWithCompletionHandler:]");
        ^
    In module 'GoogleMobileAds' imported from /Users/diegocpc/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_admob-0.9.0+10/ios/Classes/FLTMobileAd.h:6:
    /Users/diegocpc/AndroidStudioProjects/flux/source/ios/Pods/Google-Mobile-Ads-SDK/Frameworks/GoogleMobileAdsFramework-Current/GoogleMobileAds.framework/Headers/GoogleMobileAdsDefines.h:25:56: note: expanded from macro 'GAD_DEPRECATED_MSG_ATTRIBUTE'
    #define GAD_DEPRECATED_MSG_ATTRIBUTE(s) __attribute__((deprecated(s)))
                                                           ^
    /Users/diegocpc/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_admob-0.9.0+10/ios/Classes/FLTMobileAd.m:98:79: warning: implicit conversion loses integer precision: 'FLTMobileAdStatus' to 'int' [-Wshorten-64-to-32]
      NSString *statusString = (NSString *)statusToString[[NSNumber numberWithInt:_status]];
                                                          ~                       ^~~~~~~
    2 warnings generated.
    note: Using new build system
    note: Planning build
    note: Constructing build description
    warning: Mapping architecture armv7 to i386. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'image_picker' from project 'Pods')
    warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'image_picker' from project 'Pods')

Could not build the application for the simulator.
Error launching application on iPhone 11 Pro Max.

**Comment by diwebde** [comment]
Now you're giving this error

Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
Running Xcode build...
Xcode build done.                                           16,5s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    /Users/diegocpc/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.15.3+1/ios/Classes/FLTFirebaseAuthPlugin.m:493:38: error: no known class method for selector 'credentialWithProviderID:IDToken:rawNonce:accessToken:'
          credential = [FIROAuthProvider credentialWithProviderID:provider
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/diegocpc/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.15.3+1/ios/Classes/FLTFirebaseAuthPlugin.m:502:38: error: no known class method for selector 'credentialWithProviderID:IDToken:rawNonce:'
          credential = [FIROAuthProvider credentialWithProviderID:provider
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    2 errors generated.
    /Users/diegocpc/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_admob-0.9.0+10/ios/Classes/FLTMobileAd.m:40:17: warning: 'configureWithApplicationID:' is deprecated: Use [GADMobileAds.sharedInstance startWithCompletionHandler:] [-Wdeprecated-declarations]
      [GADMobileAds configureWithApplicationID:appId];
                    ^
    In module 'GoogleMobileAds' imported from /Users/diegocpc/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_admob-0.9.0+10/ios/Classes/FLTMobileAd.h:6:
    /Users/diegocpc/AndroidStudioProjects/flux/source/ios/Pods/Google-Mobile-Ads-SDK/Frameworks/GoogleMobileAdsFramework-Current/GoogleMobileAds.framework/Headers/GADMobileAds.h:74:5: note: 'configureWithApplicationID:' has been explicitly marked deprecated here
        GAD_DEPRECATED_MSG_ATTRIBUTE("Use [GADMobileAds.sharedInstance startWithCompletionHandler:]");
        ^
    In module 'GoogleMobileAds' imported from /Users/diegocpc/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_admob-0.9.0+10/ios/Classes/FLTMobileAd.h:6:
    /Users/diegocpc/AndroidStudioProjects/flux/source/ios/Pods/Google-Mobile-Ads-SDK/Frameworks/GoogleMobileAdsFramework-Current/GoogleMobileAds.framework/Headers/GoogleMobileAdsDefines.h:25:56: note: expanded from macro 'GAD_DEPRECATED_MSG_ATTRIBUTE'
    #define GAD_DEPRECATED_MSG_ATTRIBUTE(s) __attribute__((deprecated(s)))
                                                           ^
    /Users/diegocpc/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_admob-0.9.0+10/ios/Classes/FLTMobileAd.m:98:79: warning: implicit conversion loses integer precision: 'FLTMobileAdStatus' to 'int' [-Wshorten-64-to-32]
      NSString *statusString = (NSString *)statusToString[[NSNumber numberWithInt:_status]];
                                                          ~                       ^~~~~~~
    2 warnings generated.
    note: Using new build system
    note: Planning build
    note: Constructing build description
    warning: Mapping architecture armv7 to i386. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'image_picker' from project 'Pods')
    warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'image_picker' from project 'Pods')

Could not build the application for the simulator.
Error launching application on iPhone 11 Pro Max.

**Comment by diwebde** [comment]
<img width="1240" alt="Captura de ecrã 2020-01-23, às 15 34 33" src="https://user-images.githubusercontent.com/12473230/73012868-eff03480-3df5-11ea-9c68-989bb0bc773c.png">

On Android it appears like this!

**Comment by inspireui-support** [comment]
@diwebde try to use channel stable or beta - the channel dev will not ready for use

`
flutter channel stable
`

**Comment by diwebde** [comment]
How to remove the translation?
and use without translation?

**Comment by diwebde** [comment]
add currency from brazil ?

**Comment by diwebde** [comment]
<img width="1113" alt="Captura de ecrã 2020-01-30, às 19 28 29" src="https://user-images.githubusercontent.com/12473230/73496155-b93a9100-4396-11ea-812a-6b915aacc821.png">

**Comment by inspireui-support** [comment]
@Saifahmad99 - it seems the permission issue on your site, please try to run
```
chmod a+rx android/gradlew
```

**Comment by diwebde** [comment]
I/flutter ( 9672): [Fluxstore][wocommerce_api][08:12:50.282424] getAsync START [endPoint:flutter/cache] url:http://clinicaenderma.com/wp-json/wc/v2/flutter/cache?oauth_consumer_key=ck_037c8c615adb5bb4358b5f0ce90bc364fa8ba1e4&oauth_nonce=twjezfkzid&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1580469170&oauth_token=&oauth_version=1.0&oauth_signature=fVIBgMnsiCkxftcM1XN1ZmTIywA%3D
I/flutter ( 9672): [Fluxstore][AppState] init mobile modules ..
I/flutter ( 9672): [Fluxstore][AppState] register modules .. DONE
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/diegocpc/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.4.3+2/android/src/main/java/io/flutter/plugins/firebase/core/FirebaseCorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/diegocpc/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/device_apps-1.0.9/android/src/main/java/fr/g123k/deviceapps/DeviceAppsPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/diegocpc/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.12.11/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/diegocpc/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.12.11/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: /Users/diegocpc/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_admob-0.9.0+10/android/src/main/java/io/flutter/plugins/firebaseadmob/AdRequestBuilderFactory.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/diegocpc/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_analytics-5.0.9/android/src/main/java/io/flutter/plugins/firebaseanalytics/FirebaseAnalyticsPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/diegocpc/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_database-3.1.1/android/src/main/java/io/flutter/plugins/firebase/database/FirebaseDatabasePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/diegocpc/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-6.0.9/android/src/main/java/io/flutter/plugins/firebasemessaging/FirebaseMessagingPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: /Users/diegocpc/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.5.1/android/src/main/java/io/flutter/plugins/pathprovider/PathProviderPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/diegocpc/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/share-0.6.3+5/android/src/main/java/io/flutter/plugins/share/SharePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/Users/diegocpc/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.6+1/android/src/main/java/io/flutter/plugins/sharedpreferences/SharedPreferencesPlugin.java:25: warning: [deprecation] getFlutterEngine() in FlutterPluginBinding has been deprecated
    setupChannel(binding.getFlutterEngine().getDartExecutor(), binding.getApplicationContext());
                        ^
1 warning
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/diegocpc/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/video_player-0.10.5+1/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayerPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
✓ Built build/app/outputs/apk/debug/app-debug.apk.
<img width="1224" alt="Captura de ecrã 2020-01-31, às 08 28 06" src="https://user-images.githubusercontent.com/12473230/73536483-bf675680-4404-11ea-9a1a-249d2ee9b210.png">

**Comment by inspireui-support** [comment]
@diwebde - pls try to use the latest 1.6.3 to fix the issue - thank you!

**Comment by diwebde** [comment]
Sorry, I didn't understand the solution above!

**Comment by diwebde** [comment]
<img width="1189" alt="Captura de ecrã 2020-02-02, às 23 18 56" src="https://user-images.githubusercontent.com/12473230/73620877-94eae880-4612-11ea-940b-20913a1a4144.png">
I made the changes in the Change the app Bundle ID and on android continues like this? on ios runs my normal file!

**Comment by inspireui-support** [comment]
it seems the Android Studio on your machine could not reach the internet - could you try to open the browser on simular and test the connection ?
