### ISSUE TITLE
[FluxPro 1.6.3] - Plugin installation error

### ISSUE THREAD

**Issue by imhafeez** [inspireui/support#1903]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
Plugin cannot be activated. Please see the attached screenshot
2. Screenshots issues:
<img width="1144" alt="Screenshot 2020-01-22 at 7 54 49 PM" src="https://user-images.githubusercontent.com/21155655/72904954-87e81280-3d51-11ea-80bb-2aeb43c76632.png">

3. Proof of my purchased:
Extended License: 1ae3aea7-20c0-43ee-b350-c79e42c6e5ee
3. Config files (optional)

**Comment by imhafeez** [comment]
I did resolve this by removing **??** on line 130 and 171 of FlutterVendor.php

**Comment by minhcasi** [comment]
@imhafeez - pls try to keep original mstore-api instead of renaming the plugin that will cause the issue - thanks

**Comment by imhafeez** [comment]
I tried installation from direct Wordpress plugins as well. May something with my Wordpress or php version. any how I fixed with removing "??"

**Comment by imhafeez** [comment]
Please see the exception on installing Mstore API form Wordpress plugin. without renaming

<img width="1139" alt="Screenshot 2020-01-23 at 10 23 40 PM" src="https://user-images.githubusercontent.com/21155655/73007855-17afbe80-3e2f-11ea-8796-2e1d89bcf5fa.png">
