### ISSUE TITLE
[Fluxstore-Woo] - Only 100 categories are imported - Error

### ISSUE THREAD

**Issue by sketchuprzr** [inspireui/support#1905]
1. My issue:

In Woocommerce, there are more than 100 categories on my website. There are 10 main categories / 90 subcategories / 50+ 3rd category.

The app only includes 100 categories. How can I solve this?

The information is available below.

**According to the application, if the json file contains 100 categories, it should open the next page and pull information from there. This should continue like this.

There are 100 categories on page 1 on my site, but the application does not attract other pages.**

2. Screenshots issues:

![image](https://user-images.githubusercontent.com/60021696/72933659-36507f80-3d73-11ea-88b0-1922d96cc3ae.png)

![image](https://user-images.githubusercontent.com/60021696/72924101-5e36e780-3d61-11ea-860a-ae068d9b1015.png)

![image](https://user-images.githubusercontent.com/60021696/72924111-65f68c00-3d61-11ea-9bda-be853757a22a.png)

![image](https://user-images.githubusercontent.com/60021696/72924122-6ee75d80-3d61-11ea-9c48-4c0cfac6f338.png)

https://developer.wordpress.org/rest-api/using-the-rest-api/pagination/

**Here is the continuation of the page "Page=2, Page=3". But the app doesn't pull this page.**

![image](https://user-images.githubusercontent.com/60021696/72924409-ee752c80-3d61-11ea-92c8-1f4140c8fbd6.png)

3. Proof of my purchased:

![image](https://user-images.githubusercontent.com/60021696/72924027-36478400-3d61-11ea-8efd-d1312f8b7158.png)

**Comment by minhcasi** [comment]
Hi, the current Card+sub chile categories menu will not support more than 100 categories as this is also the maximum limit from WooCommerce Rest API.

We suggest using other category screen layout like the Gird, two Columns - thank you!
