### ISSUE TITLE
[Fluxstore] - Free Shipping with minimum amount

### ISSUE THREAD

**Issue by AndresReyesDev** [inspireui/support#1906]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:

I have a free shipping method with a minimum amount restriction which is not being respected by the application. Everything else works fine except this small but important detail.

2. Screenshots issues:
Cart Amount:
<img width="491" alt="Screen Shot 2020-01-22 at 23 34 39" src="https://user-images.githubusercontent.com/5054870/72952167-c7bdf280-3d6f-11ea-95d9-e61e36207d16.png">

Shipping Methods:
<img width="491" alt="Screen Shot 2020-01-22 at 23 33 07" src="https://user-images.githubusercontent.com/5054870/72952080-8d545580-3d6f-11ea-91fa-7a51eeb43683.png">

Woocommerce Configuration:
<img width="1460" alt="Screen Shot 2020-01-22 at 23 33 32" src="https://user-images.githubusercontent.com/5054870/72952129-af4dd800-3d6f-11ea-9dce-1c8dd90aa877.png">

3. Proof of my purchased:
<img width="1347" alt="Screen Shot 2020-01-14 at 12 14 58" src="https://user-images.githubusercontent.com/5054870/72952074-8594b100-3d6f-11ea-951d-b90cbc75c1cb.png">

3. Config files (optional)

**Comment by inspireui-support** [comment]
Update as feature request for next improvement - thank you!

**Comment by AndresReyesDev** [comment]
When will this update come out? Is there a temporary patch for this feature? This is critical for the business model since the application falls in the final purchase.

**Comment by inspireui-support** [comment]
@AndresReyesDev - you can try to customize the Shipping logic from this file https://tppr.me/dCYwS

By getting the total card from Provider and add the condition to show FreeShipping or not.

**Comment by inspireui-support** [comment]
You can zip the source and send back to our team email support@inspireui.com for fixing this issue (we will back after the holiday) - support@inspireui.com

Move this ticket to Trello backlog for review and upgrading

**Comment by minhcasi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Advance Shipping Method](https://trello.com/c/MNgAtts6/12-advance-shipping-method)

**Comment by AndresReyesDev** [comment]
Hi, I haven't heard anything about this, when will it go into production? Thank you very much in advance.

**Comment by inspireui-tech** [comment]
@AndresReyesDev - please help to use the latest 1.6.4 for this feature upgrade

More detail: https://medium.com/@inspireui/announcing-fluxstore-1-6-337efff1791f
Topic: 13. Migration guide for Fluxstore 1.6.4
