### ISSUE TITLE
[Fluxstore - Woo] - Category problem 

### ISSUE THREAD

**Issue by sketchuprzr** [inspireui/support#1907]
1. My issue:
Hello again,

In this article, I will state both a problem I had and a complaint about FLUXSTORE producers.

**First of all, I will express my problem.**
As I said in article # 1905;
The application loads only 1 page category. It does not load other pages. It is a problem! because on the coding page, if there are 100 categories on a page (json), it says that it should continue from page 2. For example here;

![image](https://user-images.githubusercontent.com/60021696/72953484-564d6680-3da6-11ea-96f3-c4e335eda6f5.png)

There are 220 categories on my site. Wordpress says it will publish a maximum of 100 categories on a page. It does not say that it will only publish 100 categories. It only publishes other categories on different pages. "like page = 2, page = 3"

It is not a solution that you say, it is as if it is to be rid of.
Because it is very unreasonable. I am not trying to edit the page, what I mean is; The application does not load all categories! Not indexed.

I guess you don't understand what I'm saying, I tried it for you, I'll show it here.

![image](https://user-images.githubusercontent.com/60021696/72954151-7d0c9c80-3da8-11ea-8491-47b6a34923a6.png)
![image](https://user-images.githubusercontent.com/60021696/72954183-9877a780-3da8-11ea-92ec-e3f99fb6c092.png)

As you can see in this picture, I loaded the "grid" category page.
And there is nothing changing in the app because it just loads "page = 1". So it loads only 100 categories. It needs to load the remaining pages but does not. This does not only apply to the category page, but to the categories found all over the app.

![image](https://user-images.githubusercontent.com/60021696/72954147-77af5200-3da8-11ea-8908-b9268baf92c5.png)

As it appears here, only 100 categories were uploaded.

The first article of the problem is here;
https://github.com/inspireui/support/issues/1905

**Comment by minhcasi** [comment]
@sketchuprzr - you can customize the limit of rest API to more than 100 records by using this guide by update the function.php

https://ishan.co/wp-rest-api-more-than-100-results
https://wpscholar.com/blog/increasing-the-max-results-returned-from-the-wordpress-rest-api/

Using paging will not work on the category screen, hope this resolve your issue - thank you!

**Comment by minhcasi** [comment]
We're sorry for closing your ticket without confirmed, we will help for resolving this issue until it is solved - thank you for your patient 😊

**Comment by sketchuprzr** [comment]
Hi

The code found below is /wp-includes/funcitions.php

and

/wp-content/themes/mytheme/funcitions.php

I added it in.

But nothing changed.

`add_filter( 'rest_post_collection_params', function ( $params, WP_Post_Type $post_type ) {
	if ( 'post' === $post_type->name && isset( $params['per_page'] ) ) {
		$params['per_page']['maximum'] = 200;
	}

	return $params;
}, 10, 2 );`

![image](https://user-images.githubusercontent.com/60021696/72989522-752c1700-3dff-11ea-8938-4d4bd67bc654.png)

**Comment by inspireui-support** [comment]
@minhtruong315 - pls check the solution to remove the limit amount from category rest api by upgrading the mstore-api - thanks

**Comment by inspireui-support** [comment]
#1843

**Comment by sketchuprzr** [comment]
@inspireui-support @minhcasi 
I did not solve this problem as you said. The steps you said did not help me.
I pulled 3 pages that I needed, with the help of a friend.
The code I applied is as follows;

![image](https://user-images.githubusercontent.com/60021696/73080163-72502580-3ed6-11ea-86d7-fc6f1d7222e9.png)

------------------------------------------------------------------

![image](https://user-images.githubusercontent.com/60021696/73080192-7c722400-3ed6-11ea-8b9c-c455bda808fe.png)

![image](https://user-images.githubusercontent.com/60021696/73080206-83993200-3ed6-11ea-9ffb-b7c36279efe9.png)

![image](https://user-images.githubusercontent.com/60021696/73080234-8b58d680-3ed6-11ea-85ba-94ce3e4e89d1.png)

**Comment by sketchuprzr** [comment]
> Files:
> 
> `lib/common/config.dart`
> 
> `lib/screens/order_detail.dart`
> 
> Pls help to open one ticket for your conversation to help us focus to support all issues better - thanks
> 
> Moved to #1907

config.dart
![image](https://user-images.githubusercontent.com/60021696/73080448-e4286f00-3ed6-11ea-801b-5857e518395e.png)

order detail screen
![image](https://user-images.githubusercontent.com/60021696/73080461-eab6e680-3ed6-11ea-9de4-44dc1e290884.png)

When I add it this way, it doesn't work.

![image](https://user-images.githubusercontent.com/60021696/73080506-fbfff300-3ed6-11ea-9f39-7d95766f3fc8.png)


----------------------------

### **I get an error when I add it the way you say**

![image](https://user-images.githubusercontent.com/60021696/73080554-11751d00-3ed7-11ea-8297-f038daf08975.png)

![image](https://user-images.githubusercontent.com/60021696/73080607-281b7400-3ed7-11ea-936d-e6c8a8de5291.png)

**Comment by inspireui-support** [comment]
pls try this similar code - https://tppr.me/6FpE2

**Comment by sketchuprzr** [comment]
I tried this way.
It did not work

![image](https://user-images.githubusercontent.com/60021696/73085293-83516480-3edf-11ea-8dc3-90a1a3fbdcd6.png)

![image](https://user-images.githubusercontent.com/60021696/73085300-864c5500-3edf-11ea-9283-015522cc561b.png)

![image](https://user-images.githubusercontent.com/60021696/73085310-89474580-3edf-11ea-9ff2-3ebaed270320.png)

---------------------

![image](https://user-images.githubusercontent.com/60021696/73085318-93694400-3edf-11ea-8f03-a972bda4f6af.png)

![image](https://user-images.githubusercontent.com/60021696/73085338-9bc17f00-3edf-11ea-9997-b7111ab2dd0e.png)

![image](https://user-images.githubusercontent.com/60021696/73085357-9fed9c80-3edf-11ea-884b-9e0abc4e9179.png)

**Comment by sketchuprzr** [comment]
It takes this information from api.
In Api, the shipping options appear in Turkish, but the order status appears in English. I think we need to solve this in api.

![image](https://user-images.githubusercontent.com/60021696/73085716-315d0e80-3ee0-11ea-898b-7f82fa00cb01.png)

**Comment by minhtruong315** [comment]
@sketchuprzr add my skype: minhtruong315
I'll help u check it

**Comment by zahmed84** [comment]
Thank you so much @sketchuprzr, I applied your refined code and it solved the Categories issue: Thanks again, you are great.

![Woocommerce dart code replacement](https://user-images.githubusercontent.com/58950301/73137631-0e676180-407c-11ea-90bf-e91fbbb6ebee.png)

**Comment by sketchuprzr** [comment]
Thank you @zahmed84 . But I am still waiting for an answer for the other problem. But there hasn't been any help yet. I haven't received any support from any of the problems I wrote here by the inspireui team yet. I took care of most of myself somehow. I am still waiting for an answer for my other problems.

**Comment by inspireui-support** [comment]
@sketchuprzr - could you help to zip your current source and send to support@inspireui.com - we will help for checking the process status issue - thanks

**Comment by sketchuprzr** [comment]
Hi @inspireui-support  ,
you did not add the terms found in the order status as strings. so these situations are not attached to language pages.
For example, the word "processing" is not a language, it is just a term.

I solved this with a few lines of code. no problem. I will share articles about its solution soon.

I briefly solved all the problems I wrote up to this day. I haven't got a clear solution from you yet.

**### Also ; The essential features of a shopping program are not in your application. These are big problems. And the main problems. First of all, you have to solve them.**

For example;
The user does not know how much stock a product has. And he can buy as much as he wants. If I have 5 of a product, the user can order 100, and my stock is set to -95.

Another example;
The order notes section, included in the order status, is an executive section. People shouldn't see this. the information contained therein is the order notes section developed for managers. Special information can be found here. This is not the right feature.

Another example;
a user can add this product to the basket repeatedly by pressing the "add to cart" button on a product page. This is not true. After selecting the desired amount, you can add it to the basket only once, and update the number of pieces again from the basket page. And this number should not exceed the stock amount.
When pressing the "add to cart" button a second time, the application should give an error. this can be a modalbox. For example this way;
"The product is already added to your cart, you can fix it from the cart page"

**Comment by minhcasi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Checkout UX upgrade](https://trello.com/c/iqKZ3zgd/17-checkout-ux-upgrade)

**Comment by inspireui-support** [comment]
@sketchuprzr - appreciated for your detail example, we have moved this ticket to our public Trello backlog for the team review and upgrade.

Let us know if you have any further issues, thank you so much for your great effort to resolve the problem so far.
