### ISSUE TITLE
[FluxStore Listing] - Images and Category would not show up on the App 

### ISSUE THREAD

**Issue by tastemeitaste** [inspireui/support#1908]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
Previus have some issue with image no show after you send me the config.zip file the issue still can't fix can you help me login to see whats going one with my site or code ? Thank you very much
2. Screenshots issues:
before:
![problem](https://user-images.githubusercontent.com/58832278/72963081-3a22e700-3df1-11ea-9a9b-dd671a49cc7c.jpg)

now:
![註解 2020-01-23 144402](https://user-images.githubusercontent.com/58832278/72963044-1a8bbe80-3df1-11ea-9eba-c7545d4f3524.png)
![2](https://user-images.githubusercontent.com/58832278/72963045-1b245500-3df1-11ea-9f93-729de82f6e08.png)

3. Proof of my purchased:
![prove](https://user-images.githubusercontent.com/58832278/72963057-27a8ad80-3df1-11ea-8e08-8dd2bc39175c.jpg)

3. Config files (optional)
before :

[config (1).zip](https://github.com/inspireui/support/files/4101720/config.1.zip)
after the one u send me:

[config.zip](https://github.com/inspireui/support/files/4101727/config.zip)

**Comment by sfeken15** [comment]
Were you able to resolve this? I am having the same issue.

**Comment by inspireui-support** [comment]
@tastemeitaste @sfeken15 - pls help to download the latest release today to fix the issue - thank you!
