### ISSUE TITLE
Fluxstore Pro 1.6.3 Address fild is removed in update

### ISSUE THREAD

**Issue by kurkuteabhi** [inspireui/support#1909]
I have updated app to latest 1.6.3 and I have noticed that customer or sipping address step is missing please guide.

 ![Shipping](https://user-images.githubusercontent.com/43174699/72970893-8b7da700-3dee-11ea-9475-9ebe1ccc5a30.gif)

![purches](https://user-images.githubusercontent.com/43174699/72971031-deeff500-3dee-11ea-9204-f8fe04c6c585.jpg)

**Comment by minhcasi** [comment]
@kurkuteabhi - pls update these value to true - https://tppr.me/6fiGA
