### ISSUE TITLE
[Mstore Pro Stripe Payment Issue]

### ISSUE THREAD

**Issue by hammadhassan** [inspireui/support#191]
Product: [MStore]
Purchase Code: f20afe4a-778e-4089-bcb2-7ec1bb4ed49b

When i select stripe payment & select any country & using test card number to test stripe payment. It keep displaying we do not ship to your country (United States, Netherlands, United Kingdom, Pakistan, Vietnam etc)

Please check this issue & let me know how can i customize stripe payment plugin or setting to use stripe payment method.

Thanks.

Have a good day.

**Comment by minhcasi** [comment]
Hi @hammadhassan, please download latest v3.6.7 to fix this issue 

If it still happens please reopen the ticket - thank you!

**Comment by hammadhassan** [comment]
Okay. I will check & let you know.

Thanks,

Have a great day.
