### ISSUE TITLE
[Flux-Pro 1.6.3] - Still can't update profile with latest Mstore-api 

### ISSUE THREAD

**Issue by imhafeez** [inspireui/support#1912]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
Update profile exception
 ```
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Exception: Can not updte user infor

E/flutter ( 6682): #0      WooCommerce.updateUserInfo 
package:fstore/services/woo_commerce.dart:589
E/flutter ( 6682): <asynchronous suspension>

E/flutter ( 6682): #7      GestureArenaManager.sweep 
package:flutter/…/gestures/arena.dart:156
E/flutter ( 6682): #8      GestureBinding.handleEvent 
package:flutter/…/gestures/binding.dart:222
E/flutter ( 6682): #9      GestureBinding.dispatchEvent 
package:flutter/…/gestures/binding.dart:198
E/flutter ( 6682): #10     GestureBinding._handlePointerEvent 
package:flutter/…/gestures/binding.dart:156
E/flutter ( 6682): #11     GestureBinding._flushPointerEventQueue 
package:flutter/…/gestures/binding.dart:102
E/flutter ( 6682): #12     GestureBinding._handlePointerDataPacket 
package:flutter/…/gestures/binding.dart:86
E/flutter ( 6682): #13     _rootRunUnary  (dart:async/zone.dart:1138:13)
E/flutter ( 6682): #14     _CustomZone.runUnary  (dart:async/zone.dart:1031:19)
E/flutter ( 6682): #15     _CustomZone.runUnaryGuarded  (dart:async/zone.dart:933:7)
E/flutter ( 6682): #16     _invoke1  (dart:ui/hooks.dart:273:10)
E/flutter ( 6682): #17     _dispatchPointerDataPacket  (dart:ui/hooks.dart:182:5)
E/flutter ( 6682):
```

2. Screenshots issues:
![Screenshot_1579798509](https://user-images.githubusercontent.com/21155655/73005651-1ed4cd80-3e2b-11ea-91db-c6f653867be5.png)

3. Proof of my purchased:

3. Config files (optional)

**Comment by imhafeez** [comment]
<img width="709" alt="Screenshot 2020-01-23 at 10 01 18 PM" src="https://user-images.githubusercontent.com/21155655/73006137-f00b2700-3e2b-11ea-8344-dc7e7c61dc86.png">

**Comment by imhafeez** [comment]
{"code":"rest_no_route","message":"No route was found matching the URL and request method","data":{"status":404}}

**Comment by minhcasi** [comment]
@imhafeez - pls update the mstore-api to latest vervion - https://wordpress.org/plugins/mstore-api/

**Comment by imhafeez** [comment]
I am using v2.0.2. I guess the api didn't find path for `wp-json/api/flutter_user/update_user_profile/?insecure=coo` is anything related to configuration?

**Comment by imhafeez** [comment]
Update profile issue is on ticket https://github.com/inspireui/support/issues/1913 as well.

**Comment by imhafeez** [comment]
<img width="1062" alt="Screenshot 2020-01-24 at 11 10 00 PM" src="https://user-images.githubusercontent.com/21155655/73092584-b6efb700-3efe-11ea-9633-d55112e0b5dc.png">

**Comment by inspireui-support** [comment]
@imhafeez - could you zip your current source and send us for checking - support@inspireui.com? I will ask the team to have a check when they are around during the holiday - thank you for your patience

**Comment by siyashamsudeen** [comment]
Im having the same issue addressed in https://github.com/inspireui/support/issues/1913 and havent received solution yet . please help . really in need of your help. 

thank you

**Comment by imhafeez** [comment]
@inspireui-support Actually the problem is in the routes. You can see the attached image there is no route define for `update_user_profile` that's why it gives error. 

This happens with the cache as well. I have uploaded the config.json file to the Mstore API on the admin but it says in the app "no file has been uploaded"

Please check the routes of the backend Mstore API and update. 

Thanks


<img width="299" alt="Screenshot 2020-01-29 at 11 35 47 PM" src="https://user-images.githubusercontent.com/21155655/73386137-2ba46600-42f0-11ea-97d0-1ce6ffa3fc3a.png">

**Comment by inspireui-support** [comment]
@minhtruong315 - pls update the mstore-api for this issue

**Comment by minhtruong315** [comment]
@imhafeez can u try to update MStore Api plugin. I just fix that error. Thanks

**Comment by imhafeez** [comment]
@minhtruong315 Is this fix include the cache as well? because when i upload my config.json file and enable cache within the app it says no file has been uploaded.

**Comment by inspireui-support** [comment]
@imhafeez - could you zip your current common folder and share us for further checking?

**Comment by imhafeez** [comment]
I have updated the latest Mstore API Version 2.0.7. and upload config.json. It still says no config found. please see the attached screenshots
<img width="786" alt="Screenshot 2020-02-01 at 5 41 37 PM" src="https://user-images.githubusercontent.com/21155655/73592420-1ca1fb80-451c-11ea-8afe-5b5e2cbd5f77.png">

<img width="1151" alt="Screenshot 2020-02-01 at 5 53 00 PM" src="https://user-images.githubusercontent.com/21155655/73592427-2cb9db00-451c-11ea-9d08-8b3f4caf7c20.png">

**Comment by minhtruong315** [comment]
@imhafeez pls update mstore-api plugin version 2.1.1, then upload config.json again.
