### ISSUE TITLE
[FluxStore 1.6.3] - Multiple Issues - Profile Update , Products Not Loading in Arabic Language in Vertical Layout , Sign in Methods, Splash Page

### ISSUE THREAD

**Issue by siyashamsudeen** [inspireui/support#1913]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:

Issue No 1:

In vertical layout when i add the RecentView or Recent Collection . in arabic language it shows English products only . it doesnt show the arabic ones . as i showed you in the screenshots even the request is going to fetch products in lang=ar .

After i switched to arabic language it still loads products in English in home screen . For the recent collection section . 

![A5112F63-3E12-4E87-B067-92DC4A08701D](https://user-images.githubusercontent.com/57159602/73029410-e6e08100-3e50-11ea-9ebc-2e6f090a02ee.jpg)

After i switched to arabic language it still loads products in English in home screen . For the recent collection section . 

![09100544-AB0D-41F8-B7CB-05B7CF1B8F23](https://user-images.githubusercontent.com/57159602/73029411-eba53500-3e50-11ea-8f26-6717aef0ad73.jpeg)

![image_2020_01_23T21_31_47_219Z](https://user-images.githubusercontent.com/57159602/73029462-fd86d800-3e50-11ea-9d36-b2517824d544.png)

These ones loads arabic product may be because i have explicitly mentioned arabic products categories
![image_2020_01_23T21_33_06_384Z](https://user-images.githubusercontent.com/57159602/73029516-17c0b600-3e51-11ea-9c36-3b87928f2cc6.png)
![image_2020_01_23T21_34_13_535Z](https://user-images.githubusercontent.com/57159602/73029518-17c0b600-3e51-11ea-9f54-50ab4f104e58.png)

Issue No 2 : in version 1.6.3 - after i changed splash screen to constant image . it loads logo not the splashscreen image which i have mentioned on the constants.dart

![image_2020_01_23T21_35_32_672Z](https://user-images.githubusercontent.com/57159602/73029574-3757de80-3e51-11ea-8988-b0cf373c2125.png)

But it loads logo in splash screen not this image

Issue No 3: When updating user profile this error is coming 

![image_2020_01_23T21_50_21_524Z](https://user-images.githubusercontent.com/57159602/73029610-4ccd0880-3e51-11ea-8885-1f82a9e53382.png)
![image_2020_01_23T21_50_52_068Z](https://user-images.githubusercontent.com/57159602/73029612-4d659f00-3e51-11ea-87d7-210271af8542.png)

Issue No: 4

There are no documentation to configure , Facebook , Google & Apple Sign In . 

Please help to provide any links for these . im really confused seeing different guides on firebase and facebook . 

Is this the guide to follow for facebook login ? https://firebase.google.com/docs/auth/android/facebook-login

Or this - https://pub.dev/packages/flutter_facebook_login

Which is the correct one ? currently when i click it goes to fluxstore app . in the source code which file i should go and edit . can you help with this

Issue No 5: This is not an issue but a major doubt clarification . on your latest few releases it says that there is a web version released. i really dont understand how this is accessed . how to host the web files? how to preview it . dont see any of its traces on the documentation . 

Kindly help for the above issues. 

2. Screenshots issues:

3. Proof of my purchased:

![image](https://user-images.githubusercontent.com/57159602/73029720-800f9780-3e51-11ea-97a2-492f42041686.png)

3. Config files (optional)

**Comment by minhcasi** [comment]
@siyashamsudeen - we are working on the ticket and will update you shortly - thank you!

**Comment by siyashamsudeen** [comment]
Still awaiting for your reply . please help to resolve. 

Also still havent got a proper documentation to configure apple sign in . having hard time on this . please help

**Comment by inspireui-support** [comment]
Dear customer ❤️

As the Lunar New Year Holiday, 🎁 our team will be off 5 days from 24/01/2020 to 28/01/2020, during this time we may not always support the new ticket (we will try our best to support current ticket).

Sorry for any inconvenience and wishes you have a great holiday time 😊 !!!

**Comment by Saifahmad99** [comment]
I have the same problem with the splash screen. I also updated the splash screen link but it always shows the logo on the splash screen.

**Comment by inspireui-support** [comment]
@minhtruong315 - pls help for investigating the Apple Sign In from #1928 on this ticket as well

**Comment by minhtruong315** [comment]
@siyashamsudeen for update profile. can u try to update MStore Api plugin. I just fix that error. Thanks

**Comment by Saifahmad99** [comment]
what about the splash screen problem?

**Comment by siyashamsudeen** [comment]
@minhtruong315  The push notification and apple sign in error were not mentioned in this ticket . 
that is why another ticket was created . 

Apple sign in issue is really major as that is why im stuck at not being able to upload to app store. please help

My current issues are :


1. Apple Sign in not working – error comes after returning from successful authentication from apple servers .

2. Push Notification Not Working or not receiving in both ios and android apps . in earlier version it used to work in android but not any more .

3. Profile Update not working

4. Facebook Login not working in release apk in android

5. Splash page doesnt load the image i have mentioned on ksplash instead it loads the logo .

6. Products doesnt load in arabic in vertical layout .

Above issues are mentioned in 2 tickets

https://github.com/inspireui/support/issues/1913 
https://github.com/inspireui/support/issues/1928

i already sent you my latest source code as well and i received your mail acknowledgement on receiving it

Please help .

**Comment by minhtruong315** [comment]
Profile Update not working
Did you update MStore Api plugin?

**Comment by siyashamsudeen** [comment]
okay im double checking now .

**Comment by siyashamsudeen** [comment]
i updated the mstore plugin and now it keeps giving Enter your Password Error despite i entered the password

![image](https://user-images.githubusercontent.com/57159602/73434008-62659500-435f-11ea-9771-a38f1b64e304.png)

**Comment by minhtruong315** [comment]
You need to replace this file screens/user_update.dart to fix update profile
[user_update.dart.zip](https://github.com/inspireui/support/files/4133311/user_update.dart.zip)

**Comment by minhtruong315** [comment]
supported via skype
