### ISSUE TITLE
FluxStore Listing - Links social networks 

### ISSUE THREAD

**Issue by danimmg** [inspireui/support#1914]
Hello

We really need tutorial videos teaching how to configure the FluxStore Listing many users are having the same doubts and the manuals provided are not working properly.
I would like to ask the following questions:

**01 - Fields**
I'm not able to show some fields from the listings in the application, for example

totalReview
facebook
twitter
youtube
instagram
skype
whatsapp
tagLine
regularPrice
verified

**02 - Fields**
I would like to use the website for real estate as well, as I can show the fields in the application:

_price	
_swimming-pool	
_beds	
_rooms	
_bathrooms	
_area	

**03 -  Social networks**
It is impossible to show the listing's social networks in the application using the mylisting template

![Capture23-01-2020-19 51 17](https://user-images.githubusercontent.com/59834619/73031981-6c960980-3e1c-11ea-830c-44f57f8bd209.jpg)
![social](https://user-images.githubusercontent.com/59834619/73031983-6c960980-3e1c-11ea-85e6-bf1a98855c7e.jpg)

**04 -  Show tags instead of categories.**
for example in the code below how it would look to show tags instead of categories
-------------------------------------------------- -----------

{
      "layout": "bannerImage",
      "isSlider": true,
      "items": [
        {
          "category": 21,
          "image": "https://user-images.githubusercontent.com/1459805/59846818-12672e80-938b-11e9-8184-5f7bfe66f1a2.png",
          "padding": 15.0
        },
        {
          "category": 23,
          "image": "https://user-images.githubusercontent.com/1459805/60091575-1f12ca80-976f-11e9-962c-bdccff60d143.png",
          "padding": 15.0
        },
        {
          "category": 21,
          "image": "https://user-images.githubusercontent.com/1459805/60091808-a19b8a00-976f-11e9-9cc7-576ca05c2442.png",
          "padding": 15.0
        }
      ]
    }

------------------

{
  "layout": "category",
  "type": "image",
  "size": 1.0,
  "radius": 50.0,
  "items": [
    {
      "category": 108,
      "showText": true,
      "name": "Arquitetos e Decoradores"
    },
    {
      "category": 127,
      "showText": true,
      "name": "Engenheiros"
    },
    {
      "category": 125,
      "showText": true,
      "name": "Paisagistas"
    },
    {
      "category": 154,
      "showText": true,
      "name": "Designers e Artistas plásticos"
    },
    {
      "category": 126,
      "showText": true,
      "name": "Light designers"
    }
  ]
},

**05 -  Work hours**
I need the working hours registered in the listing to be shown in the app

**06 -  Video**
I need it to be showing in the app the video registered in the listing

**07 - Category images**
After the update the images of the categories no longer show

![Capture04-02-2020-07 17 50](https://user-images.githubusercontent.com/59834619/73737054-a1f5fd80-4720-11ea-87f8-db4ff10f340b.jpg)

**08 - common folder version 1.3**

[common.zip](https://github.com/inspireui/support/files/4152734/common.zip)

**09 - Documentation with errors**

Users who follow the documentation will not be able to work, it contains several errors, proof of this is the large number of users who follow the documentation and cannot complete the steps

https://docs.inspireui.com/fluxstore/listing-directory/

**10 - Video tutorial**

I have already asked the support a few times to prepare videos for all templates with the correct configuration but until today this has not been provided

**11 -  Change the app Bundle ID**
Is it necessary to perform this procedure? because there is no such folder: kotlin
https://docs.inspireui.com/fluxstore/customization/#12-change-the-app-bundle-id

Rename the folder android/app/src/main/kotlin/com/inspireui/fluxstore to your own bundle name, example: if you bunndle id is com.ins.flux, it will be android/app/src/main/kotlin/com/ins/flux
Please note that the file android/app/google-services.json should be changed to match your new bundle id. Otherwise the app will crash.

after I performed this modification correctly it generated an error
![Capture04-02-2020-17 40 01](https://user-images.githubusercontent.com/59834619/73786160-7ce0a980-4777-11ea-898f-1b9f65c11cd1.jpg)

12 - **Translation**
Some words and phrases I can't translate:
![Capture04-02-2020-20 26 30](https://user-images.githubusercontent.com/59834619/73797535-16678580-478f-11ea-8085-c754c7831fa8.jpg)
![Capture04-02-2020-20 27 21](https://user-images.githubusercontent.com/59834619/73797536-18314900-478f-11ea-9b55-c29755397f02.jpg)

Loading ...
days a go

**Comment by minhcasi** [comment]
@danimmg - could you zip and share the common folder so that we could help for checking - thanks

**Comment by danimmg** [comment]
[common.zip](https://github.com/inspireui/support/files/4106483/common.zip)

**Comment by danimmg** [comment]
Good Morning
Attached is the common folder.

I have other doubts.

1. How do I place an external link on the example banners: http://google.com?
2. What company hours can the application show?
Thanks

**Comment by danimmg** [comment]
I believe that some files are in the wrong way

import 'package:**fstore**/common/constants.dart';

**Comment by inspireui-support** [comment]
@danimmg - could you help to use the latest version that release today, we have fix some issues

**Comment by vumanhsn97** [comment]
@danimmg 
1. Fields
change code in lib/models/listing.dart to https://tppr.me/qsk1n
price not show because your product dont have price
2. to upgrade your product please contract to admin. Not support
3. show in issue 1: https://tppr.me/CVIeW
4. to upgrade your product please contract to admin. Not support
5. to upgrade your product please contract to admin. Not support
6. to upgrade your product please contract to admin. Not support
7, 8, 9, 10, 11, 12. supported in email please check source code: https://tppr.me/L8tP4

**Comment by danimmg** [comment]
Hello

**About items:** 7, 8, 9, 10, 11, 12. supported in email please check source code: https://tppr.me/L8tP4

You sent me your source code but I'm not going to work with it because the right thing is for me to work with the file I download from the codecanyon website and this code coming from codecanyon must be correct to work with the mylisting website
How will I search the folder you sent me line by line for changes?
------------------------------------------------------------------------------------------------------
 **1 -Fields**   price not show because your product dont have price

I created a price field and inserted it into the ProductDataMapping
But it doesn't show the price
![Capture05-02-2020-08 57](https://user-images.githubusercontent.com/59834619/73841343-27e57780-47f9-11ea-8113-8beadcd12579.jpg)

**Comment by danimmg** [comment]
Two more bugs found and not mentioned in the documentation

**1 - For the app to communicate with the site, you need to rename wp-json**

http://site.com/wp-json/wp/v2/job_listing
**for**
http://site.com/wp-json/wp/v2/listing

**2 - To show the images of the category, the following line must be changed**

lib/models/category.dart 
line 53 

this.image = image;
**for**
this.image = url + '/wp-content/uploads/' + image[0]["file"];

**Comment by inspireui-support** [comment]
Hi if your website is base on MyListing template then this config is correct
```
const serverConfig = {
"type": "mylisting",
...
```

**Comment by minhtruong315** [comment]
@danimmg add my skype: minhtruong315
I will help check issues

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
