### ISSUE TITLE
Product Categories from WooCommerce Not showing.

### ISSUE THREAD

**Issue by Varun24041993** [inspireui/support#1916]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
My issue is that some product categories from my WooCommerce is not showing in my Mstore Pro. Please Let me know how can I show all the product categories in my app, how can I configure the api to show product categories which are not showing. I tried making new categories but it also is not showing in my app. It seems like the json data that I am receiving does not update.
 
2. Screenshots issues:
This Screenshot shows the product categories on my website:
![product_cat](https://user-images.githubusercontent.com/56767455/73041567-080e9500-3e84-11ea-8818-4cde9ab07b36.png)

This Screenshot shows the product categories displaying on my App:
![product_cat_app](https://user-images.githubusercontent.com/56767455/73041671-5885f280-3e84-11ea-86cf-2d2295de4fa8.png)

As you can see some main categories which are in my website (Frozen Food, Baby Care) are not showing in app and I have tried to create new categories but the new categories also don't show in the app.

I have installed all the required plugins as stated, I even deleted and installed again all the plugins. Also I tried creating and connecting new REST api key but nothing has worked for me.

3. Proof of my purchased:
![Screenshot 2020-01-24 at 8 25 07 AM](https://user-images.githubusercontent.com/56767455/73041321-14462280-3e83-11ea-9cf4-5c8bd4bf10ff.png)

3. Config files (optional)

**Comment by inspireui-support** [comment]
@Varun24041993 - pls zip the common folder and send us for checking (we will back for work after the Holiday) thank you!

**Comment by Varun24041993** [comment]
Hi as requested here is my common.zip file. Thanks, look forward for an answer ASAP.

[common.zip](https://github.com/inspireui/support/files/4110873/common.zip)

**Comment by zahmed84** [comment]
I am also facing same issue.... Some parent categories and subcategories are missing in the App.... @inspireui-support Please fix this issue as early as possible. This is major bug and need to to be fixed immediately. I have fully complied my app and only waiting for this bug to be fixed.... Thanks

**Comment by zahmed84** [comment]
Same issue exist in their Fluxstore Woocommerce App....

**Comment by Varun24041993** [comment]
> Same issue exist in their Fluxstore Woocommerce App....

Hi Zahmed84 have you been able to find any solutions for this issue lately?

**Comment by Varun24041993** [comment]
> @Varun24041993 - pls zip the common folder and send us for checking (we will back for work after the Holiday) thank you!

Hey. Are you back from weekend ? I need assistance on the product immediately. Please revert back asap.

**Comment by Varun24041993** [comment]
Hey. @inspireui-support Are you back from weekend ? I need assistance on the product immediately. Please revert back asap.

**Comment by Varun24041993** [comment]
Hi @luyx2412 Just To be clear the problem I am facing is that whenever I add New Categories and products To my Wordpress panel It is Not Shown there But If I edit the already showing categories(For Example is I change the name of any category in my Wordpress panel which is already showing in the Mstore) the changes are reflected even if I change the pricing of any product immediately the changes are reflected there but adding new categories are not showing in Mstore. It would be great if we can share screen so that I will explain and show you what's happening there.

**Comment by Varun24041993** [comment]
HI @inspireui-support  @luyx2412  it has been quite a while now since you return from holiday still this is no reply from your end. I am in urgent need of your support. Please reply ASAP.

**Comment by luyx2412** [comment]
Hi @Varun24041993 Please send me your wordpress account via luyxtran264@gmail.com

Thanks

**Comment by Varun24041993** [comment]
Hi @luyx2412 details are sent by my mail account with subject : Mail From @Varun24041993 regarding wordpress account detail.

**Comment by luyx2412** [comment]
Hi @Varun24041993 
Sorry about reply you late. 
I just checked your issues. The issue related `per_page`, because your categories has more than 100 items, so the api will response not full categories. 
You need load next page categories `page=2` look like the image and merge all categories
![image](https://user-images.githubusercontent.com/8909619/73666718-d09ab680-46d5-11ea-95df-3d7287a3bd52.png)

We will improve the issue in next version.

P/S: Feel free to reopen the issue.

Thanks
