### ISSUE TITLE
Fluxstore Listing failed

### ISSUE THREAD

**Issue by Bingo2000** [inspireui/support#1917]
** BUILD FAILED **
Xcode's output:
↳
    In file included from /Users/ingo/STUFF/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_facebook_login-3.0.0/ios/Classes/FacebookLoginPlugin.m:3:
    In file included from /Users/ingo/STUFF/Flutter/source/ios/Pods/Headers/Private/FBSDKLoginKit/FBSDKLoginKit.h:27:
    /Users/ingo/STUFF/Flutter/source/ios/Pods/Headers/Private/FBSDKLoginKit/FBSDKLoginButton.h:36:9: fatal error: module 'FBSDKCoreKit' not found
    @import FBSDKCoreKit;
     ~~~~~~~^~~~~~~~~~~~
    1 error generated.

![fluxstore_listing](https://user-images.githubusercontent.com/13098762/73053760-e8c63680-3e88-11ea-8571-cd277b6cce5b.jpg)

**Comment by inspireui-support** [comment]
@Bingo2000 - pls try following solution

Remove the ios/Pods folder, Podfile and Podfile.lock

Then try this script:

```
flutter clean
flutter channel stable
flutter upgrade --force
```

**Comment by Bingo2000** [comment]
Now:

Ausnahme aufgetreten.
FlutterError (ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
If you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.)

AND:
Ausnahme aufgetreten.
FlutterError (ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
If you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.)
Launching lib/main.dart on iPhone 11 in debug mode...
Warning: Podfile is out of date
  This can cause a mismatched version of Flutter to be embedded in your app, which may result in App Store submission rejection or crashes.
  If you have local Podfile edits you would like to keep, see https://github.com/flutter/flutter/issues/24641 for instructions.
To regenerate the Podfile, run:
  rm ios/Podfile

Xcode build done.                                           403,0s
	path: satisfied (Path is satisfied), interface: en0
Configuring the default Firebase app...

	path: satisfied (Path is satisfied), interface: en0
Configured the default Firebase app __FIRAPP_DEFAULT.
	path: satisfied (Path is satisfied), interface: en0
https://firebase.google.com/docs/cloud-messaging/ios/client#method_swizzling_in_firebase_messaging
to ensure proper integration.
	[C1.1 30DCA56D-41EE-4538-8E09-7E00F3E45BBD 2a01:c22:b40a:8600:8c91:3556:1d11:53e1.52906<->2a03:2880:f03f:12:face:b00c:0:2.443]
	Connected Path: satisfied (Path is satisfied), interface: en0
	Duration: 1.060s, DNS @0.003s took 0.038s, TCP @0.046s took 0.019s, TLS took 0.223s
	bytes in/out: 4402/1320, packets in/out: 8/10, rtt: 0.015s, retransmitted packets: 0, out-of-order packets: 0
	[C2.1 8DCA1AD5-8F93-49DF-8496-0E164C4556E3 2a01:c22:b40a:8600:8c91:3556:1d11:53e1.52907<->2a03:2880:f03f:12:face:b00c:0:2.443]
	Connected Path: satisfied (Path is satisfied), interface: en0
	Duration: 1.098s, DNS @0.004s took 0.032s, TCP @0.046s took 0.087s, TLS took 0.351s
	bytes in/out: 4627/1361, packets in/out: 8/10, rtt: 0.020s, retransmitted packets: 1, out-of-order packets: 0
	[C4.1 1A973A7B-2CA9-44E3-836C-5E15093CC15C 2a01:c22:b40a:8600:8c91:3556:1d11:53e1.52914<->2a03:2880:f03f:12:face:b00c:0:2.443]
	Connected Path: satisfied (Path is satisfied), interface: en0
	Duration: 0.441s, DNS @0.001s took 0.027s, TCP @0.032s took 0.018s, TLS took 0.265s
	bytes in/out: 4435/963, packets in/out: 8/9, rtt: 0.019s, retransmitted packets: 1, out-of-order packets: 0
	[C6.1 84B59EBE-C73F-4B57-A451-9014771422DC 2a01:c22:b40a:8600:8c91:3556:1d11:53e1.52916<->2a03:2880:f03f:12:face:b00c:0:2.443]
	Connected Path: satisfied (Path is satisfied), interface: en0
	Duration: 0.440s, DNS @0.001s took 0.020s, TCP @0.047s took 0.062s, TLS took 0.078s
	bytes in/out: 3917/1569, packets in/out: 8/9, rtt: 0.016s, retransmitted packets: 0, out-of-order packets: 0
	[C5.1 D8B9B27D-82A9-42B9-9212-00361AF03FD5 2a01:c22:b40a:8600:8c91:3556:1d11:53e1.52915<->2a03:2880:f03f:12:face:b00c:0:2.443]
	Connected Path: satisfied (Path is satisfied), interface: en0
	Duration: 0.478s, DNS @0.007s took 0.023s, TCP @0.058s took 0.024s, TLS took 0.093s
	bytes in/out: 3918/1401, packets in/out: 8/11, rtt: 0.019s, retransmitted packets: 1, out-of-order packets: 0
	[C9.1 4EAD7248-DE81-4C44-A4DC-643A4EDA8CF8 2a01:c22:b40a:8600:8c91:3556:1d11:53e1.52930<->2a00:1450:4001:808::200e.443]
	Connected Path: satisfied (Path is satisfied), interface: en0
	Duration: 0.142s, DNS @0.002s took 0.006s, TCP @0.010s took 0.024s, TLS took 0.061s
	bytes in/out: 4560/1015, packets in/out: 8/9, rtt: 0.021s, retransmitted packets: 0, out-of-order packets: 0
	[C10.1 F1EC3789-4E64-44D3-B5F9-DFD883382DFA 2a01:c22:b40a:8600:8c91:3556:1d11:53e1.52931<->2a00:1450:4001:808::200e.443]
	Connected Path: satisfied (Path is satisfied), interface: en0
	Duration: 0.150s, DNS @0.000s took 0.008s, TCP @0.010s took 0.021s, TLS took 0.083s
	bytes in/out: 4243/1526, packets in/out: 8/10, rtt: 0.019s, retransmitted packets: 0, out-of-order packets: 0

**Comment by inspireui-support** [comment]
@Bingo2000 - we could not reproduce this issue on your side, could you try to run "flutter doctor -v" and send us the result.

----

As the Lunar New Year Holiday, 🎁 our team will be off 5 days from 24/01/2020 to 28/01/2020, during this time we may not always support the new ticket (we will try our best to support current ticket).
Sorry for any inconvenience and wishes you have a great holiday time 😊 !!!

**Comment by Bingo2000** [comment]
Ingo-Laptop-3:Visual Code ingo$ flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale de-DE)
    • Flutter version 1.12.13+hotfix.5 at /Users/ingo/STUFF/Flutter/flutter
    • Framework revision 27321ebbad (7 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/ingo/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.0.beta.2

[!] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.



After running iOs Debug:

![Bildschirmfoto 2020-01-27 um 08 54 33](https://user-images.githubusercontent.com/13098762/73157955-d5aea300-40e2-11ea-9e1b-2f9e0854eaad.jpg)

Debug Console

Launching lib/main.dart on iPhone 11 in debug mode...
Xcode build done.                                           74,5s
	path: satisfied (Path is satisfied), interface: en0
Configuring the default Firebase app...
	path: satisfied (Path is satisfied), interface: en0
Configured the default Firebase app __FIRAPP_DEFAULT.
	path: satisfied (Path is satisfied), interface: en0
https://firebase.google.com/docs/cloud-messaging/ios/client#method_swizzling_in_firebase_messaging
to ensure proper integration.
	[C1.1 24D95F28-DAED-43CA-A3EE-B4777A63D7CD 192.168.179.141:49829<->157.240.27.18:443]
	Connected Path: satisfied (Path is satisfied), interface: en0
	Duration: 0.428s, DNS @0.003s took 0.017s, TCP @0.026s took 0.015s, TLS took 0.055s
	bytes in/out: 4624/1330, packets in/out: 8/9, rtt: 0.015s, retransmitted packets: 0, out-of-order packets: 0
	[C2.1 8B7872E8-4187-4DE8-A9F2-205AD4DCDA7C 192.168.179.141:49830<->157.240.27.18:443]
	Connected Path: satisfied (Path is satisfied), interface: en0
	Duration: 0.431s, DNS @0.000s took 0.016s, TCP @0.021s took 0.018s, TLS took 0.058s
	bytes in/out: 4402/1351, packets in/out: 8/11, rtt: 0.017s, retransmitted packets: 1, out-of-order packets: 0
	[C3.1 CE8896BC-27F7-4C4E-B1B5-1AFF49BAE5D6 192.168.179.141:49832<->157.240.27.18:443]
	Connected Path: satisfied (Path is satisfied), interface: en0
	Duration: 0.421s, DNS @0.001s took 0.008s, TCP @0.012s took 0.020s, TLS took 0.286s
	bytes in/out: 4442/1232, packets in/out: 8/9, rtt: 0.017s, retransmitted packets: 1, out-of-order packets: 0
	[C4.1 EC6C7622-7187-4AA0-B776-F989F127048E 192.168.179.141:49833<->157.240.27.18:443]
	Connected Path: satisfied (Path is satisfied), interface: en0
	Duration: 0.445s, DNS @0.000s took 0.006s, TCP @0.009s took 0.213s, TLS took 0.151s
	bytes in/out: 4410/932, packets in/out: 8/8, rtt: 0.016s, retransmitted packets: 0, out-of-order packets: 0
	[C5.1 2D90289A-4F12-4624-AFF3-530EA84DF3F6 192.168.179.141:49834<->157.240.27.18:443]
	Connected Path: satisfied (Path is satisfied), interface: en0
	Duration: 0.328s, DNS @0.001s took 0.017s, TCP @0.022s took 0.063s, TLS took 0.052s
	bytes in/out: 3915/1467, packets in/out: 8/9, rtt: 0.015s, retransmitted packets: 0, out-of-order packets: 0
	[C6.1 ED9BBAFD-C4DC-4C2E-97E8-2D107F4BE95B 192.168.179.141:49848<->216.58.205.238:443]

**Comment by Bingo2000** [comment]
Solved the last issue with:
void main() async {
  **WidgetsFlutterBinding.ensureInitialized();**
  Provider.debugCheckInvalidValueType = null;

  SystemChrome.setPreferredOrientations(
      [DeviceOrientation.portraitUp, DeviceOrientation.portraitDown]);

  runApp(App());
}
described here.:

https://stackoverflow.com/questions/57689492/flutter-unhandled-exception-servicesbinding-defaultbinarymessenger-was-accesse

App works now!!

**Comment by inspireui-support** [comment]
Thank you for the confirm
