### ISSUE TITLE
[Fluxstore 1.6.3] - Can't start the app 

### ISSUE THREAD

**Issue by vuln3r** [inspireui/support#1918]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: I can't start the app at all. I thought first it is something that happens during my setup but also on fresh download happens the same.

The only thing I changed is config.dart

`I/flutter (13826):   MainTabs-[LabeledGlobalKey<MainTabsState>#9c53a homePageKey]
I/flutter (13826):   
lib/app.dart:219
I/flutter (13826):
I/flutter (13826): When the exception was thrown, this was the stack:
I/flutter (13826): #0      MainTabsState.renderTabbar.<anonymous closure> 
package:fstore/tabbar.dart:308
I/flutter (13826): #1      List.forEach  (dart:core-patch/growable_array.dart:285:8)
I/flutter (13826): #2      MainTabsState.renderTabbar 
package:fstore/tabbar.dart:292
I/flutter (13826): #3      MainTabsState.renderBody 
package:fstore/tabbar.dart:270
I/flutter (13826): #4      MainTabsState.build 
package:fstore/tabbar.dart:176
I/flutter (13826): #5      StatefulElement.build 
package:flutter/…/widgets/framework.dart:4334
I/flutter (13826): #6      ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:4223
I/flutter (13826): #7      Element.rebuild 
package:flutter/…/widgets/framework.dart:3947
I/flutter (13826): #8      BuildOwner.buildScope 
package:flutter/…/widgets/framework.dart:2432
I/flutter (13826): #9      WidgetsBinding.drawFrame 
package:flutter/…/widgets/binding.dart:773
I/flutter (13826): #10     RendererBinding._handlePersistentFrameCallback 
package:flutter/…/rendering/binding.dart:283
I/flutter (13826): #11     SchedulerBinding._invokeFrameCallback 
package:flutter/…/scheduler/binding.dart:1102
I/flutter (13826): #12     SchedulerBinding.handleDrawFrame 
package:flutter/…/scheduler/binding.dart:1041
I/flutter (13826): #13     SchedulerBinding._handleDrawFrame 
package:flutter/…/scheduler/binding.dart:957
I/flutter (13826): #17     _invoke  (dart:ui/hooks.dart:259:10)
I/flutter (13826): #18     _drawFrame  (dart:ui/hooks.dart:217:3)
I/flutter (13826): (elided 3 frames from package dart:async)
I/flutter (13826):
I/flutter (13826): ════════════════════════════════════════════════════════════════════════════════════════════════════`

2. Screenshots issues:
![image](https://user-images.githubusercontent.com/13506241/73056411-3e054680-3e8f-11ea-85a4-6538c340c691.png)

![image](https://user-images.githubusercontent.com/13506241/73056045-66d90c00-3e8e-11ea-85b7-e33594fecd23.png)

3. Proof of my purchased:
![image](https://user-images.githubusercontent.com/13506241/73055991-4446f300-3e8e-11ea-9127-9de572d114b0.png)

**Comment by inspireui-support** [comment]
@vuln3r 
Could you try to run  this script:
```
flutter clean
flutter channel stable
flutter upgrade --force
```

**Comment by vuln3r** [comment]
I

> @vuln3r
> Could you try to run this script:
> 
> ```
> flutter clean
> flutter channel stable
> flutter upgrade --force
> ```
I tried that but I get onboarding screen on a fresh install and after onboarding the same red screen and same error...

I'm also getting notes like here:
![image](https://user-images.githubusercontent.com/13506241/73090884-89dcdd80-3ed9-11ea-860f-01fbc8bb43e3.png)

and the error:
![image](https://user-images.githubusercontent.com/13506241/73090943-a8db6f80-3ed9-11ea-91f2-5bae4c1dde77.png)

I tried it on the iPhone to build with XCode instead of VC but the same thing :( I don't know what I did wrong...

**Comment by inspireui-support** [comment]
@vuln3r - pls try to zip the source and send back to support@inspireui.com - thank you!

**Comment by vuln3r** [comment]
thank you for the response.. but it is 1.1 GB big.. I can't mail it 😂

**Comment by inspireui-support** [comment]
You can try to run "flutter clean" + remove ios/Pods folder  - then upload privately to https://wetransfer.com/
