### ISSUE TITLE
[MMV] Confirm order not responding- Mstore multivendor

### ISSUE THREAD

**Issue by samber91** [inspireui/support#192]
Hi. When i hit the button confirm order, nothing happens. I followed all the instructions but nothing to do.
Psssss. it was working fine on previous versions of the mstore multivendor app
I need help urgently please. thanks

**Comment by thangvo9x** [comment]
Hi. Please give us your purchase code.

**Comment by samber91** [comment]
Purchase code :  ad1ac976-3e34-4e40-a473-0985df712891  . Please i need help urgently. i'm lauching my business tomorrow. thanks

**Comment by thangvo9x** [comment]
Hi. Please prove AppConfig.json help me. We'll check help you. Thanks

**Comment by minhcasi** [comment]
@thangvo9x

**Comment by minhcasi** [comment]
Hi @samber91 - could you download the latest version released today - it will be fix this issue, please reopen it don't work with your site - thanks

**Comment by samber91** [comment]
Okay Minh. I will try and let you know. Thanks
