### ISSUE TITLE
Fluxstore - Couple of issues

### ISSUE THREAD

**Issue by csoftech** [inspireui/support#1921]
Hello,

I have installed latest version released yesterday.

**PROFILE PAGE**
I am trying to update profile as I registered/login via SMS.

Issue no.1)  I am unable to update any information there, circle keeps on looping once I click on update button.

Issue no. 2 ) Upload profile pic takes to Gravtar which is weird. People either should be able to upload the image or this option shouldn't be there, it feels odd and fishy if someone is taken to third party website. I have never seen this happening on any app I have used till date.

**WHATSAPP|SMS|TEL**
1) I  added whatsapp number in config file but that didn't bring the WhatsApp option anywhere on the app.
2) SMS & Mobile number also added but those options are no where visible.

Please reply with solution on all above.

**Comment by inspireui-support** [comment]
Noted for checking - we will back to work after the holiday on next week - thank you!

**Comment by csoftech** [comment]
I hope you had a good time in your holidays. 

Can please look into above issues?

**Comment by philipvu30** [comment]
Hi @csoftech,

Would you mind sending me the common folder and give me some pictures about your issues? It would be easier for me to help you with those provided information. Thank you.

**Comment by csoftech** [comment]
Hi,

I noticed you have fixed updating information on profile page , SMS WHATSAPP shortcut.

GRAVTAR link is still there

Upon updating info it is updating password as well, I tried adding website URL to the profile.

**Comment by philipvu30** [comment]
Hi csoftech,

Have you solved your problems yet? Feel free to ask me any question if needed.
