### ISSUE TITLE
[Fluxstore - Woo] - Some missing and problems with the order process

### ISSUE THREAD

**Issue by sketchuprzr** [inspireui/support#1922]
1. My issue:

Hello,

Order errors in Woocommerce do not appear in the application. When I say order, payment options are not available.
It does not show any error messages.

An example error message is available here;

![image](https://user-images.githubusercontent.com/60021696/73084107-6a47b400-3edd-11ea-98e3-707acd06fe55.png)

From the product in this picture, each user can purchase a maximum of 1 at a time.
here I tried to buy 5 pieces. And the error message came. I can add a maximum of 1 to the cart.

For example in shipping options;
"pay at delivery"
In order to use the option, it is necessary to order at least 75 TL.

If the order amount is less than 75 TL, the payment option is not opened at the door.

However, in the application, all shipping options appear regardless of the order amount.

As shown in the picture

![image](https://user-images.githubusercontent.com/60021696/73084306-c579a680-3edd-11ea-811a-bcbf7458a5da.png)

this product is under 75 TL, there is no option to pay at the door.

![image](https://user-images.githubusercontent.com/60021696/73084344-d62a1c80-3edd-11ea-90f1-b5171b58c643.png)

![image](https://user-images.githubusercontent.com/60021696/73084377-e5a96580-3edd-11ea-8963-7483522a5a17.png)

This product is under the amount of 75 TL, there should be no option to pay at the door.

![image](https://user-images.githubusercontent.com/60021696/73084497-1ee1d580-3ede-11ea-910a-d1f0a12f62a6.png)

If I come to the payment page by selecting the payment delivery option at the door with free delivery of the product below 75 TL, the payment options do not appear.

This is normal.

When you order under 75 TL on our website,
payment at the door
You need to pay 3 TL.

If the order amount is 75 TL or more, the free shipping option appears.

**Comment by zahmed84** [comment]
Yes I am also facing the above shipping issue... @inspireui-support please fix this bug.

**Comment by inspireui-support** [comment]
As the Lunar New Year Holiday, 🎁 our team will be off 5 days from 24/01/2020 to 28/01/2020, during this time we may not always support the new ticket (we will try our best to support current ticket).
Sorry for any inconvenience and wishes you have a great holiday time 😊 !!!

**Comment by inspireui-support** [comment]
Hi, we could add the new Logic to check the minimum Total cart to show the "Free Shipping Flat" on the next release.

**Comment by sketchuprzr** [comment]
Merhaba,
bu özellik woocommerce gönderim seçeneklerinde mevcut.
ücretsiz gönderim için koşul ekleyebiliyorsunuz.

![image](https://user-images.githubusercontent.com/60021696/73459545-1aa73380-4388-11ea-9f60-cf7388d84cfd.png)

For the prefix "free shipping" option here;
minimum amount: 75
I chose as.

![image](https://user-images.githubusercontent.com/60021696/73459567-2a267c80-4388-11ea-90b0-3c267b510029.png)

Thus, if the order amount is not 75, free shipping option is not active.

**Comment by sketchuprzr** [comment]
So when does the next release arrive? @inspireui-support 
because this is a very important issue.

**Comment by inspireui-support** [comment]
We are working on this upgrade, it will be available next week - thank you!

**Comment by minhcasi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Shipping UX upgrade](https://trello.com/c/IxZ5QHEW/19-shipping-ux-upgrade)

**Comment by inspireui-tech** [comment]
@sketchuprzr - we have upgraded to latest 1.6.4 to support for these features - please check more detail from - https://medium.com/@inspireui/announcing-fluxstore-1-6-337efff1791f

Please check the MinFreeShippingCost config - thank you!
