### ISSUE TITLE
[FluxStore - SMS and point questions

### ISSUE THREAD

**Issue by Pars1vaLl** [inspireui/support#1924]
Hi team,

 1. I noticed that in your demo-app, users receive email from you with order details. How can I do the same for my App. And is it possible to SMS instead of email?

2.Could you please explain more about 'Points'? How does it work?

Proof of my purchased: http://prntscr.com/qqeel1

Thank you)

**Comment by inspireui-support** [comment]
Dear customer ❤️

As the Lunar New Year Holiday, 🎁 our team will be off 5 days from 24/01/2020 to 28/01/2020, during this time we may not always support the new ticket (we will try our best to support current ticket).

Sorry for any inconvenience and wishes you have a great holiday time 😊 !!!

**Comment by minhtruong315** [comment]
Hi @Pars1vaLl Could you confirm if your website could send email when user register on the website? You can update the latest fluxstore and mstore-api plugin to active the Order notify feature

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
