### ISSUE TITLE
[EvaStore] - My Shopify Store is not connecting to the app. 

### ISSUE THREAD

**Issue by p156069** [inspireui/support#1925]
1. I tried connecting my Shopify store with the app but nothing happened. It keeps loading the default store which comes with it when you buy.

2. I am going to list the screenshot of Config file and show you that i have configured it according to the video tutorial of EvaStore which you guys have made.

3. And one thing i noticed is strange that i followed your video to get the the Product categories ID from shopify but my id's Format is different from what you got in the video.

**PROOFS**

**1. AppConfig.json**
https://i.ibb.co/BZXnvpg/Screenshot-2.png

**2. Config.js**
Screenshot 1:
https://i.ibb.co/Tr2xx3s/Screenshot-3.png
Screenshot 2:
https://i.ibb.co/fYTRXny/Screenshot-4.png

**3. APP SCREESHOT(Still running default store)**
https://i.ibb.co/zVrgBp6/Whats-App-Image-2020-01-25-at-4-15-30-PM.jpg

**Purchase Proof:**
https://i.ibb.co/M1SMGY2/Screenshot-5.png

**Comment by inspireui-support** [comment]
Dear customer ❤️

As the Lunar New Year Holiday, 🎁 our team will be off 5 days from 24/01/2020 to 28/01/2020, during this time we may not always support the new ticket (we will try our best to support current ticket).

Sorry for any inconvenience and wishes you have a great holiday time 😊 !!!

**Comment by luyx2412** [comment]
Hi @p156069 Your category id is wrong, please make sure getting your right category id. The video guided specific how to get category id.

Thanks
