### ISSUE TITLE
[my-product] - Mstore 3.9.7 - Cebuilder error after installation in windows

### ISSUE THREAD

**Issue by adminmaccus** [inspireui/support#1926]
1. **My issue**: Sir, I had purchased mstore pro for woocommerce previous week. My purchase code is d9225293-9f21-40e4-b5ba-0de3ff69d37b from code canyon. I followed the tutorial and installed cebuilder and the necessary softwares till the step 2 in setup  of cebuilder application goes green.  
    1) I get the consumer and secret key from wordpress and enter in cebuilder. Then i load the 
       project MSTORE PRO, go to the second step and found step 2 is all good. then i click on **RUN ANDROID 
       SETUP** button. It shows me with errors which im unable to rectify. The screen shot is attached 
       along with this.
  
    2) I tried to load the folder MSTORE EXPO folder in cebuilder and press the start button in step 2 
       it take me to a command prompt. There also i found too many errors which i cannot clear. 
         Kindly help me run the project   and get android and ios app. You can find the screenshots  
         attached. If possible to take teamviewr or anydesk connection it will be better. Thankyou
        
![cebuilder-1](https://user-images.githubusercontent.com/60291435/73121982-aee45580-3f98-11ea-88c1-07dd94e27328.JPG)
![cebuilder2](https://user-images.githubusercontent.com/60291435/73121984-aee45580-3f98-11ea-98bb-f34e42a367cf.jpg)

       
![ExproRun](https://user-images.githubusercontent.com/60291435/73121959-53b26300-3f98-11ea-8965-d3055015a22a.JPG)
![MstoreProRunAndroidClick](https://user-images.githubusercontent.com/60291435/73121960-53b26300-3f98-11ea-9263-6d5220488abb.JPG)
![Purchase](https://user-images.githubusercontent.com/60291435/73121994-d2a79b80-3f98-11ea-845b-741f2fd9d81c.JPG)

**Comment by inspireui-support** [comment]
Dear customer ❤️

As the Lunar New Year Holiday, 🎁 our team will be off 5 days from 24/01/2020 to 28/01/2020, during this time we may not always support the new ticket (we will try our best to support current ticket).

Sorry for any inconvenience and wishes you have a great holiday time 😊 !!!

**Comment by adminmaccus** [comment]
Sir, can anyone tell me how to proceed. Please. Am really stuck here and new in this platform. Any kind of support to run the app will be greatly helpful.

**Comment by inspireui-support** [comment]
@adminmaccus - could you help to update the latest CeBuilder 0.39 to see if it works - thank you!

**Comment by adminmaccus** [comment]
Sir, i tried to install  0.39 in my windows pc. When i click run as administrator,  nothing happens. Later i check the downloaded file, its only 528kb. What should i do. Am not able to install or mound dmg file also. Please do support asap.

**Comment by adminmaccus** [comment]
Sir, since i am unable to install in windows, i tried mac. I can see the app via expo in android phone. But there are other problems like, i cannot see any item pictures in the app. But in website there are pictures for the products. Kindly help me with windows and fix this issue

**Comment by inspireui-support** [comment]
@adminmaccus - could you check this guide that related to the image optimize - https://docs.inspireui.com/mstore/woo-setting/#product-display-sizes - thank you!

**Comment by itspathanofficial** [comment]
@adminmaccus contact me on whatsapp +919636315123
