### ISSUE TITLE
[Fluxstore App] - Version: 1.6.3---- Unable to run app on ios simulator (Xcode)

### ISSUE THREAD

**Issue by itej7** [inspireui/support#1927]
Hi InspireUI Team,

My issue: We are not able to run this app on ios simulator. We are getting below errors while trying to run on Mac:

Xcode's output:
CocoaPods requires your terminal to be using UTF-8 encoding.
    Consider adding the following to ~/.profile:

    export LANG=en_US.UTF-8

Proof of my purchase:
Product Purchase code: c2f1abaf-6ebe-4c07-875d-050022ba2a14 - 14 Oct 2019 REGULAR LICENSE

**Comment by inspireui-support** [comment]
Dear customer ❤️

As the Lunar New Year Holiday, 🎁 our team will be off 5 days from 24/01/2020 to 28/01/2020, during this time we may not always support the new ticket (we will try our best to support current ticket).

Sorry for any inconvenience and wishes you have a great holiday time 😊 !!!

**Comment by inspireui-support** [comment]
@itej7 - pls try to edit your profile file on mac
```
vim ~/.profile
```

or if you are using zsh
```
~/.zshrc
```


and add this line
```
export LANG=en_US.UTF-8
```

screenshot:
https://tppr.me/gzAVR
