### ISSUE TITLE
[FluxStore 1.6.3] - Apple Sign In Not Working , iOS Push Notification Not Working , 

### ISSUE THREAD

**Issue by siyashamsudeen** [inspireui/support#1928]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:

A . Apple Sign In Not Working:

I have been struggling to configure Apple Sign In as there are no proper documentation given anywhere . 

I did enable Apple Sign in in my Apple Developer Profile
Enabled Apple Sign in Firebase Authentication Methods ( I Dont know if this was needed but yet i did it )

![image](https://user-images.githubusercontent.com/57159602/73124179-c11ebd80-3fb1-11ea-82fb-12b7331618b4.png)

![image](https://user-images.githubusercontent.com/57159602/73124183-caa82580-3fb1-11ea-8b83-187c56f963af.png)

You can see the service enabled in the above screenshots 

Initially i have been getting authorization error . but now it shows authorized but after the login it gives an error : Warning: Error . as below:

![WhatsApp Image 2020-01-25 at 5 22 12 PM](https://user-images.githubusercontent.com/57159602/73124203-18bd2900-3fb2-11ea-9f1b-7a8622c8c517.jpeg)
![WhatsApp Image 2020-01-25 at 5 22 59 PM](https://user-images.githubusercontent.com/57159602/73124204-1955bf80-3fb2-11ea-98b9-9b1bf2e365db.jpeg)

Below is the error log from xcode:

![image](https://user-images.githubusercontent.com/57159602/73124241-8406fb00-3fb2-11ea-9b49-8bc55eab3543.png)

B: iOs Push Notification Not Working:

I did all as mentioned in the documentation. you can see in the above screenshots that push notification is also enabled . 

The APN Key is added to the firebase console as well . 

![image](https://user-images.githubusercontent.com/57159602/73124311-828a0280-3fb3-11ea-9b39-facb39ea1107.png)

But the physical device and simulator both i tried . but i cant receive any push notification . 
i dont understand how else to test as well. 

Please help on these above issues. 

have been struggling since many days now . need to get this sorted some how and get the app published. please help

2. Screenshots issues:

3. Proof of my purchased:

![image](https://user-images.githubusercontent.com/57159602/73124379-283d7180-3fb4-11ea-9f47-521cb1a849b1.png)

3. Config files (optional)

**Comment by inspireui-support** [comment]
Dear customer ❤️

As the Lunar New Year Holiday, 🎁 our team will be off 5 days from 24/01/2020 to 28/01/2020, during this time we may not always support the new ticket (we will try our best to support current ticket).

Sorry for any inconvenience and wishes you have a great holiday time 😊 !!!

**Comment by inspireui-support** [comment]
move to #1913

Pls help to post one ticket for your all issue next time that helps us focus on your all issues - thank you!
