### ISSUE TITLE
nothing is working !!!!

### ISSUE THREAD

**Issue by saioufe** [inspireui/support#1929]
please make good documentation , i cant get anything working , no sms login , no google login , no fbLogin 

you should make docs for each one of them ?????

**Comment by inspireui-support** [comment]
Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads  it's used to verify your proof of purchase? sorry for any inconvenience - Thank you!

**Comment by saioufe** [comment]
![Untitled](https://user-images.githubusercontent.com/32012762/73131979-79397e00-4025-11ea-9a2f-293d8679dccd.png)
