### ISSUE TITLE
[ListPro] won't work

### ISSUE THREAD

**Issue by Igorowytsch** [inspireui/support#193]
Hi
I have several bugs which I'm not able to manage. Maybe you can help me to better understand.
My coding skills are around 0, thought ListPro is made for people like me, especially with CeBuilder.

- Homepage shows your Restaurant content and mine together and somehow mixed.
- I get some errors (red screen) on my iPhone, for example: TypeError: undefined is not an object (evaluating 'c.lenghth'
- In categories my listings aren't shown any image
- My listings don't show any information I added like website or phone number

Just some examples, would really love to use ListPro if anyhow possible.

Thanks a lot
Igor

**Comment by thangvo9x** [comment]
Hi. Please provide us your purchase code.

**Comment by Igorowytsch** [comment]
Hi there

Herewith the purchase code:  34ec0643-e187-4f74-9060-94601b1c8375

Best regards
Igor

**Comment by thangvo9x** [comment]
Hi. can you give me your AppConfig.json to email thang@inspireui.com. Thanks

**Comment by Igorowytsch** [comment]
Hi Thang

I just did from igor.ilak(at)gmx.ch

Regards
Igor

**Comment by thangvo9x** [comment]
Hi. I don't understand you, please.

**Comment by Igorowytsch** [comment]
I sent you yesterday the files from the mail mentioned above.

**Comment by thangvo9x** [comment]
I still don't received it yet. igor.ilak@gmx.ch. this email is yours , plz ?

**Comment by Igorowytsch** [comment]
I sent it again. Now working?

Am 25.01.2019 um 03:54 schrieb thangvo9x <notifications@github.com>:

I still don't received it yet. igor.ilak@gmx.ch. this email is yours , plz ?

**Comment by thangvo9x** [comment]
Hi. I have been it already. I still can't connect to you? Please update consumerKey such as consumerSecret in your AppConfig.json, and change categoryListingId such as tags... to see that changed.
 Thanks

**Comment by thangvo9x** [comment]
Hi.cosnumerKey and consumerSecret => You can get it at Woocommerce->Settings->advanced -> Rest API & create it. 
change categoryListimgId => in Classic.js in Config folder. Thanks

**Comment by Igorowytsch** [comment]
Why is this one closed now?

**Comment by minhcasi** [comment]
As we don’t see your reply, kindly reopen it if you still have an issue, thanks

**Comment by Igorowytsch** [comment]
I can‘t answer immediately if I didn‘t find time to test. How can I reopen it, or can I just write here again?

**Comment by Igorowytsch** [comment]
Hi there

Unfortunately I tried to change the things mentioned above, nothing changed.
Hopefully you can help me.

consumer key: ck_6c6aeaf1d036edcd174274895677e827632c774e
consumer secret: cs_27fa00fe6259d7020662930fdb68d414bada7b76
I have only one category which has ID 29, you are talking about the Listingpro category, right?

Thanks a lot

**Comment by minhcasi** [comment]
@thangvo9x

**Comment by thangvo9x** [comment]
Hi. Waiting response from @Igorowytsch
