### ISSUE TITLE
[MStore Pro] Payments Methods doesn't work

### ISSUE THREAD

**Issue by gonzalobarria** [inspireui/support#1931]
I cannot pay any product, in this case with PayPal. When opens the webview it appears a form from wordpress without any button.

Step before #1
https://ibb.co/g6Q2tWx

In Webview
https://ibb.co/6F0ftgC

My purchase code is; ef682cd6-d8bd-403b-82a6-d63b87caa4a7

**Comment by inspireui-support** [comment]
Dear customer ❤️

As the Lunar New Year Holiday, 🎁 our team will be off 5 days from 24/01/2020 to 28/01/2020, during this time we may not always support the new ticket (we will try our best to support current ticket).

Sorry for any inconvenience and wishes you have a great holiday time 😊 !!!

**Comment by gonzalobarria** [comment]
I'll be waiting your help

**Comment by jsaristizabal** [comment]
I have the same problem, please fix it fast. I cant to use the app.

**Comment by jsaristizabal** [comment]
This is a really big problem since the application cannot be launched. It is totally useless. @inspireui-support #

**Comment by inspireui-support** [comment]
@gonzalobarria - could you zip your common folder and send us for investigating this issue - thank you!

**Comment by gonzalobarria** [comment]
> @gonzalobarria - could you zip your common folder and send us for investigating this issue - thank you!

Here is the common folder... https://drive.google.com/open?id=100B2pVfIraphAWRX8WQWtVvdAhwGnBCP

**Comment by jsaristizabal** [comment]
I waiting for the solution too, thanx.

**Comment by gonzalobarria** [comment]
I just update the mstorepro plugin for wordpress and Paypal is working now, but Stripe doesn't... Is it always too buggy this app?

**Comment by gonzalobarria** [comment]
I'm sorry, it appears the Paypal window, I can login and pay, but it looks awful, and when I press "Return to Merchant", it came back to Thanks page of Woocommerce, not a page of the app. Is it this way that this work?

**Comment by jsaristizabal** [comment]
@gonzalobarria If true, when the application goes to the payment page, it shows the page completely without styles.
![Captura de Pantalla 2020-01-31 a la(s) 8 56 59 p  m](https://user-images.githubusercontent.com/29686082/73585247-6a135f80-446d-11ea-8672-7800099e54b1.png)

**Comment by jsaristizabal** [comment]
There is another problem and it is when the payment form is filled in and the keyboard appears, when the keyboard is closed the screen is lowered and stuck.
![Captura de Pantalla 2020-01-31 a la(s) 8 57 42 p  m](https://user-images.githubusercontent.com/29686082/73585282-afd02800-446d-11ea-964c-de53337b0224.png)

**Comment by gonzalobarria** [comment]
@jsaristizabal @inspireui-support it is exactly the same issue for me, is it possible to fix this soon?... Also Stripe please

**Comment by gonzalobarria** [comment]
Is there some news? , I don't hear nothing from you guys. If you cannot fix this I want a total refund. The app is useless with these issues.

**Comment by luyx2412** [comment]
Hi @gonzalobarria and @jsaristizabal 
Sorry about reply you late. I just investigated the issue.
Please add 3 new props in Modal `coverScreen`, `position="top"`, `keyboardTopOffset={0}` in `src/containers/Cart/index.js` line 122 look like the screenshot to fix the issue.
![image](https://user-images.githubusercontent.com/8909619/73670263-7f8dc100-46db-11ea-9625-bb59b9fa2fc3.png)

P/S: Feel free to reopen the issue.

Thanks

**Comment by jsaristizabal** [comment]
@gonzalobarria @inspireui-support They fixed the problem of the modal that was downloaded with the keyboard, but not that of the page without styles. I am going to open a new case to solve that because it is already closed.
![Captura de Pantalla 2020-01-31 a la(s) 8 56 59 p  m](https://user-images.githubusercontent.com/29686082/73763956-30c64280-4740-11ea-8f45-d50f17ea6cd4.png)

**Comment by gonzalobarria** [comment]
@luyx2412 I don't know how to reopen this issue because I just update your wordpress plugin and i added your configuration, and now nothing happen. I press Confirm Order, thw modal opens but now is blank, nothing happen, Paypal or Stripe, nothing happen. I need to do something else?

**Comment by luyx2412** [comment]
Hi @jsaristizabal and @gonzalobarria  Please open new issue.

Thanks
