### ISSUE TITLE
[FluxListing] - Unable to connect to MyListing site.

### ISSUE THREAD

**Issue by sfeken15** [inspireui/support#1932]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: I am trying to connect to my MyListing site. I've done everything up to this page https://docs.inspireui.com/fluxstore/customization/ and installed all of the plugins to my WordPress site.

I am unable to connect with categories easily, connect to my blog or anything else really.

Is there documentation or a video specifically for MyLiisting and GLux Listing?

2. Screenshots issues:

3. Proof of my purchased: 
![image](https://user-images.githubusercontent.com/60324276/73140034-e6efa500-4039-11ea-9032-2802e4cfc858.png)

3. Config files (optional)

**Comment by inspireui-support** [comment]
Dear customer ❤️

As the Lunar New Year Holiday, 🎁 our team will be off 5 days from 24/01/2020 to 28/01/2020, during this time we may not always support the new ticket (we will try our best to support current ticket).

Sorry for any inconvenience and wishes you have a great holiday time 😊 !!!
