### ISSUE TITLE
[FluxLisiting] - How to change home page layout?

### ISSUE THREAD

**Issue by sfeken15** [inspireui/support#1933]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: There is no documentation on how to change the layout of the home screen or any other screen in FluxListing.  It isn't the same as the documented flux store. There are different files.Is there any help with this? Thanks.  

2. Screenshots issues: 

3. Proof of my purchased: 
![image](https://user-images.githubusercontent.com/60324276/73140982-82861300-4044-11ea-93cc-2435dc333785.png)

3. Config files (optional)

**Comment by inspireui-support** [comment]
Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads  it's used to verify your proof of purchase? sorry for any inconvenience - Thank you!

**Comment by inspireui-support** [comment]
As the Lunar New Year Holiday, 🎁 our team will be off 5 days from 24/01/2020 to 28/01/2020, during this time we may not always support the new ticket (we will try our best to support current ticket).

Sorry for any inconvenience and wishes you have a great holiday time 😊 !!!

**Comment by sfeken15** [comment]
Ok, thank you. I figure out the home screen design.
