### ISSUE TITLE
Fluxstore multivendor 

### ISSUE THREAD

**Issue by rgbufferchime** [inspireui/support#1934]
1. My issue:ok so here is my problem...i did everything according to the instructions in the documentation but the categories and other products wont load in the app when i am connecting to woocommerce wordpress site......however it loads when i try using opencart....but i dont want to use opencart...i checked on postman also but there the response is showing...however when i install all the plugins especially JWT Authentication for WP-API it starts showing some error in postman telling some authentication issue....but in niether case i am able to connect my wordpress site to my app.

2. Screenshots issues:
![Capture](https://user-images.githubusercontent.com/43860635/73142647-27d9cf00-40b7-11ea-8ba1-b5a96757bb66.PNG)
![Capture2](https://user-images.githubusercontent.com/43860635/73142648-28726580-40b7-11ea-9489-5ed4f644b78f.PNG)
![Capture3](https://user-images.githubusercontent.com/43860635/73142650-28726580-40b7-11ea-9219-eef2a890c8ae.PNG)

3. Proof of my purchased:
![Captureffh](https://user-images.githubusercontent.com/43860635/73142661-5192f600-40b7-11ea-8cfb-d459d2492dd3.PNG)

3. Config files (optional)

**Comment by inspireui-support** [comment]
Dear customer ❤️

As the Lunar New Year Holiday, 🎁 our team will be off 5 days from 24/01/2020 to 28/01/2020, during this time we may not always support the new ticket (we will try our best to support current ticket).

Sorry for any inconvenience and wishes you have a great holiday time 😊 !!!

**Comment by rgbufferchime** [comment]
By when can i expect it to be resolved

**Comment by minhtruong315** [comment]
@rgbufferchime We released new version for fluxstore mv. It's working well for WCFM and Dokan. Please update in codecanyon and update MStore Api plugin as well. Thanks

**Comment by rgbufferchime** [comment]
i updated it...now a new problem occured..now i see stores and products iside that...but still categories sectio is blank and also i cant see products directly
