### ISSUE TITLE
[Fluxstore-MV] - Place Order Button is not appearing

### ISSUE THREAD

**Issue by saifmuhtar** [inspireui/support#1935]
1. My issue:

I'm using webview payment. When I want to make a payment on my Fluxstore app, the Place Button is not appearing and shows like an error on that area.

2. Screenshots issues:

![Screenshot_20200127_060432_com saifstudio mjfmall](https://user-images.githubusercontent.com/34681804/73145186-10b2d580-40e7-11ea-901e-a3d09eef8194.jpg)

3. Proof of my purchased:

![72332982-fc89d400-36f5-11ea-9307-f8c418404111](https://user-images.githubusercontent.com/34681804/73145140-c598c280-40e6-11ea-8bc6-3ce0ba55321d.jpg)

3. Config files (optional):
Please contact me via Skype saifmuhtar@gmail.com

**Comment by inspireui-support** [comment]
@saifmuhtar - added your skype

**Comment by minhtruong315** [comment]
@saifmuhtar Please update MStore Api plugin to fix this issue. Thanks
