### ISSUE TITLE
[Fluxnews] - Disable Ads

### ISSUE THREAD

**Issue by aldoyh** [inspireui/support#1936]
Hello,
I simply want to disable all ads to be displayed or to need/use any Ads Services for now temporarily to be enabled later on.

**Comment by inspireui-support** [comment]
Hi, pls update the common/config.dart file - there is the option to disable the Ads.

Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads  it's used to verify your proof of purchase? sorry for any inconvenience - Thank you!

**Comment by aldoyh** [comment]
Here's my proof of purchase:
https://www.dropbox.com/s/m2m8m0wdv870wp7/Screenshot%202020-01-29%2008.56.06.png?dl=0


But where may I find that option? I found the keys at the bottom of the file but nothing is saying disable.
```

const kAdConfig = {
  "type": "",
  // ----------------- Facebook Ads  -------------- //

  "hasdedIdTestingDevice": "3f06ede0-3b68-4cdb-a639-1b1007cedd31",
  "bannerPlacementId": "430258564493822_489007588618919",
  "interstitialPlacementId": "430258564493822_489092398610438",
  "nativePlacementId": "430258564493822_489092738610404",
  "nativeBannerPlacementId": "430258564493822_489092925277052",

  // ------------------ Google Admob  -------------- //

  "androidAppId": "ca-app-pub-2101182411274198~7554000316",
  "androidUnitBanner": "ca-app-pub-2101182411274198/2054261627",
  "androidUnitInterstitial": "ca-app-pub-2101182411274198/7197727340",
  "androidUnitReward": "ca-app-pub-2101182411274198/5498660536",
  "iosAppId": "ca-app-pub-2101182411274198~6923444927",
  "iosUnitBanner": "ca-app-pub-2101182411274198/5418791562",
  "iosUnitInterstitial": "ca-app-pub-2101182411274198/9218413691",
  "iosUnitReward": "ca-app-pub-2101182411274198/9026842008",
  "waitingTimeToDisplayInterstitial": 10,
  "waitingTimeToDisplayReward": 10,
};
```

Another issue came up too, I can't get normal articles to be shown upon a blog view and it's really frustrating! Your demo App on Google's Play also not working properly! as shown here:

![Screenshot_20200129_085232_com inspireui fnews](https://user-images.githubusercontent.com/5215449/73331735-da579080-4275-11ea-8eac-faf6cce15fe8.jpg)
![Screenshot_20200129_085223_com inspireui fnews](https://user-images.githubusercontent.com/5215449/73331736-daf02700-4275-11ea-9844-4cb1385ace4c.jpg)


What's even more frustrating is when I read 5 minutes to have it ready, but I'm trying since **July 2019**!!!!

**Comment by aldoyh** [comment]
The above Screenshots were taken from the Demo App on Google's Play.

Now, I've replaced the config.json with the original config_ar.json and when the Blog renders it's showing this error:

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-01-29 at 09 53 38](https://user-images.githubusercontent.com/5215449/73335778-53101a00-4281-11ea-9232-4ef3f61a854e.png)


here's the code generating this error without any modification from me:
The Categories ID only changed to match my content.

```

    {
      "name": "عرض الأخيرة",
      "layout": "recentView"
    },
    {
      "name": "مجموعات المرأة",
      "image": "",
      "layout": "threeColumn",
      "category": 80,
      "isSnapping": true
    },
    {
      "name": "مجموعات الرجل",
      "image": "",
      "layout": "twoColumn",
      "category": 82,
      "isSnapping": true
    },
    {
      "name": "بلوق وظائف",
      "layout": "blog"
    },
    {
      "name": "مجموعات الرجل",
      "layout": "staggered",
      "limit": 20,
      "category": 29
    }

```

**Comment by dttrung26** [comment]
Hi @aldoyh ,
please send me your /lib/common folder and admin access to your website via trung@inspireui.com. Nice day!

**Comment by aldoyh** [comment]
Thank you so much for your great support.
Access sent. 

[common.zip](https://github.com/inspireui/support/files/4143478/common.zip)

**Comment by dttrung26** [comment]
Hi @aldoyh ,
so far as I checked, things still run fine with your common folder. Make sure all of your flutter and editor installation are perfectly done. 
![image](https://user-images.githubusercontent.com/32586676/73625399-37d54e00-4677-11ea-81e7-5b1704d03467.png)
![image](https://user-images.githubusercontent.com/32586676/73625406-415eb600-4677-11ea-816f-0c4c52bb7d56.png)
For the advertisement disability, it will be updated in the next version. Thank you very much for notifying us. 
Have a nice day sir,
Trung.

**Comment by aldoyh** [comment]
Affirmative, thank you so much for the amazing work and great support I definitely admire the project but many steps along the way are not mentioned and I keep guessing which then creates incompatible modules.

**Comment by dttrung26** [comment]
Greetings sir @aldoyh ,

I have to admit that there is a lack of our documents for users, we are working on improving that. Please stay tuned with us. Btw, if you are still encountering any issues, please feel free to notify us. 

Happy coding,
Trung.
