### ISSUE TITLE
[FLUXSTORE MV] - ARABIC LANGUAGE 

### ISSUE THREAD

**Issue by yassiney120** [inspireui/support#1937]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
Hi , please arabic language not working on fluxstore mv
2. Screenshots issues:

3. Proof of my purchased:

https://ibb.co/wYmMMJm

3. Config files (optional)

**Comment by inspireui-support** [comment]
@yassiney120 - could you share the screenshot issue and your common folder? Our team will have a check after the holiday - thank you!

**Comment by yassiney120** [comment]
Video issues:
https://drive.google.com/file/d/15Vdjp7newSrHOp0c1rEhu8iHHFqdSESB/view?usp=sharing
common file :
https://drive.google.com/file/d/1VYda-2JxkFTaJvFK5YWrX_XQUWTQm1r9/view?usp=sharing

thank you

**Comment by minhtruong315** [comment]
@yassiney120 you need to update Fluxstore MV 1.6.3
Then 
You need to replace this file screens/language.dart to fix arabic language
[language.dart.zip](https://github.com/inspireui/support/files/4133329/language.dart.zip)

**Comment by yassiney120** [comment]
thank you mr truong for reply 
but still ican't switch to arabic language

thank you

**Comment by minhtruong315** [comment]
supported via teamviewer
