### ISSUE TITLE
my listing

### ISSUE THREAD

**Issue by salmaMohamed610** [inspireui/support#1938]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:

2. Screenshots issues:

3. Proof of my purchased:

3. Config files (optional)

**Comment by salmaMohamed610** [comment]
sign up loading without any response ,login and facebook login don't work 
![Screenshot_1580112640](https://user-images.githubusercontent.com/60310512/73158763-802bc380-40ed-11ea-864b-53e186ca3d93.png)
![Screenshot_1580112717](https://user-images.githubusercontent.com/60310512/73158764-802bc380-40ed-11ea-91cd-ab8e5d26ac89.png)

**Comment by inspireui-support** [comment]
Hi,

As the Lunar New Year Holiday, 🎁 our team will be off 5 days from 24/01/2020 to 28/01/2020, during this time we may not always support the new ticket (we will try our best to support current ticket).

Sorry for any inconvenience and wishes you have a great holiday time 😊 !!!

**Comment by inspireui-support** [comment]
@salmaMohamed610 - could you help to attache the common folder here so that we could help for checking

**Comment by salmaMohamed610** [comment]
> @salmaMohamed610 - could you help to attache the common folder here so that we could help for checking


[https://bitbucket.org/salma610_bahnasy/sahlan/src/master/App/Common/](url)

**Comment by inspireui-support** [comment]
@salmaMohamed610 - could you set the project as private and zip the common folder only ?

**Comment by inspireui-support** [comment]
Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads  it's used to verify your proof of purchase? sorry for any inconvenience - Thank you!
