### ISSUE TITLE
[my-product] - Fluxstore Pro - Flutter E-commerce Full App

### ISSUE THREAD

**Issue by jijonj** [inspireui/support#1939]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: I am getting an error on app build, I tried uploading config.json from lib/common to the mstore api.

2. Screenshots issues: https://imgur.com/a/3Dl75Ta

3. Proof of my purchased: https://imgur.com/a/3Dl75Ta

3. Config files (optional)

**Comment by inspireui-support** [comment]
Dear customer ❤️

As the Lunar New Year Holiday, 🎁 our team will be off 5 days from 24/01/2020 to 28/01/2020, during this time we may not always support the new ticket (we will try our best to support current ticket).

Sorry for any inconvenience and wishes you have a great holiday time 😊 !!!

**Comment by dttrung26** [comment]
Good afternoon @jijonj ,
could you please send me your /lib/common folder for checking? Many thanks in advance.

**Comment by jijonj** [comment]
[common.zip](https://github.com/inspireui/support/files/4132788/common.zip)

**Comment by dttrung26** [comment]
Hi @jijonj , 
please send me your whole project after deleting /build folder because there are some modifications in your current project. Thanks.

**Comment by jijonj** [comment]
all the files except /build folder
https://drive.google.com/open?id=1WJzJ63xk511VUb_f58V6ed9cz75LrX-t

**Comment by dttrung26** [comment]
Hi @jijonj , 
try to run this folder and please tell me if it works : https://www.dropbox.com/s/732nfk7qci261u6/test_customer.rar?dl=0 
Nice day!

**Comment by jijonj** [comment]
it says its incomplete the archive is incomplete

**Comment by jijonj** [comment]
its not working full of errors
I copied the build folder to it as well but still not resolved

**Comment by jijonj** [comment]
mostly undefined name s

**Comment by dttrung26** [comment]
Hi @jijonj ,  could you please send me the error screenshot, may I ask?

**Comment by jijonj** [comment]
<img width="999" alt="Screenshot 2020-01-30 at 3 09 21 PM" src="https://user-images.githubusercontent.com/20769924/73437607-a7df8d80-4372-11ea-9373-c61bc5873531.png">

**Comment by jijonj** [comment]
maybe if you give me the full code it might work
<img width="454" alt="Screenshot 2020-01-30 at 3 12 24 PM" src="https://user-images.githubusercontent.com/20769924/73437830-13295f80-4373-11ea-9d67-9cfa83449448.png">

**Comment by jijonj** [comment]
<img width="458" alt="Screenshot 2020-01-30 at 3 13 13 PM" src="https://user-images.githubusercontent.com/20769924/73437913-318f5b00-4373-11ea-9938-40ba3d207ebf.png">

**Comment by dttrung26** [comment]
Sir, what I sent you was full code already. Please try to download this one: https://drive.google.com/file/d/1PEcFh4VoAOOcO0hEEPxqqwPtfWuMlJT1/view?usp=sharing 
Remember to run "packages get" inside pubspec.yaml file before running app. Many thanks.

**Comment by jijonj** [comment]
the code ran but has the same error config file not uploaded
<img width="1440" alt="Screenshot 2020-01-31 at 11 41 16 AM" src="https://user-images.githubusercontent.com/20769924/73516602-f9dded00-441e-11ea-8405-d3617a7112f8.png">

**Comment by jijonj** [comment]
I am getting the error while debugging with vs code
When I run the app otherwise the error is not present

**Comment by jijonj** [comment]
Inorder to customize I need to debug but then the error

**Comment by dttrung26** [comment]
Here are some recommendations: 
- Please make sure your REST API is set up correctly, follow this: https://docs.inspireui.com/fluxstore/woocommerce-setup/ 
- If VS Code still can't let you debug, please try to switch to another editor, Android Studio is an example, follow this: https://docs.inspireui.com/fluxstore/getting-started/
According to the last time I checked, everything still runs fine. Therefore, the risk is more likely to be in your editor sir.

**Comment by jijonj** [comment]
I shifted to android Studio and the problem is gone.
I think the problem was with the caching. 
Is there a way to clean cache in vs code

THanks a lot for your support

**Comment by jijonj** [comment]
A new issue there is that updating profile is not working

**Comment by inspireui-support** [comment]
@jijonj - the profile update will be fixed on the next release.

You can run "flutter clean" to try to clean caching on VS Code

You can also get the patching on this issue - thank you!
