### ISSUE TITLE
POD error while building ios

### ISSUE THREAD

**Issue by hmdkarimi** [inspireui/support#194]
i  started new project in version 3.6.7 (pro)
after install dependencies and libraries with "yarn setup" command, i get these error in ios build in xcode
i tried to remove pod files and install it again but it doesn't work

diff: /Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

**Comment by minhcasi** [comment]
HI, please check the latest solution: https://github.com/inspireui/support/issues/38

try to install latest cocoapods will fix the issue: sudo gem install cocoapods -v 1.6.0.beta.2
