### ISSUE TITLE
[FluxNews] - Images are not showing after installing Regenerate Thumbnails Plugin.

### ISSUE THREAD

**Issue by AatiqUrRehman** [inspireui/support#1940]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. images that needs to come from backend are not showing on mobile side even after Regenerating all available images Thumbnails.

2. https://imgur.com/a887iTW, https://imgur.com/ejU1Ahw

3. https://imgur.com/uRAZhkG

3. Config files (optional)

**Comment by inspireui-support** [comment]
Hi,

As the Lunar New Year Holiday, 🎁 our team will be off 5 days from 24/01/2020 to 28/01/2020, during this time we may not always support the new ticket (we will try our best to support current ticket).

Sorry for any inconvenience and wishes you have a great holiday time 😊 !!!

**Comment by dttrung26** [comment]
Hi @AatiqUrRehman ,
please send me your /lib/common folder as well as your website admin access via trung@inspireui.com. Many thanks!
