### ISSUE TITLE
Fluxlisting error after changing default config

### ISSUE THREAD

**Issue by Bingo2000** [inspireui/support#1941]
After change form default Config to no picture are shown and the error appers:

const serverConfig = {
  "type": "mylisting",
  "url": "http://mylisting.inspireui.com",
  "blog": "http://mylisting.inspireui.com",
  "consumerKey": "ck_0e7d6d841d5d0c952e92d827abb529674f25f8f5",
  "consumerSecret": "cs_7811cbea91c2ff24999627fc1d61a1371d6a918f",
  "forgetPassword":
      "http://mylisting.inspireui.com/wp-login.php?action=lostpassword"
};

_TypeError (type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'Iterable<dynamic>')

<img width="1113" alt="Bildschirmfoto 2020-01-28 um 09 58 59" src="https://user-images.githubusercontent.com/13098762/73249508-51792000-41b5-11ea-8845-05a27f9b8552.png">

**Comment by inspireui-support** [comment]
Noted with check on the example demo for MyListing - thank you for your feedback

**Comment by inspireui-support** [comment]
moved to #1967
