### ISSUE TITLE
[Fluxstore Listing] - How to add map with listing

### ISSUE THREAD

**Issue by Bingo2000** [inspireui/support#1942]
How can I  add a map with listings

<img width="421" alt="Bildschirmfoto 2020-01-28 um 11 00 22" src="https://user-images.githubusercontent.com/13098762/73253749-65c11b00-41bd-11ea-8946-06c4e031d419.png">

**Comment by inspireui-support** [comment]
You can add config the Listing with Long/Lat from the Wordpress then it will appear from the app map view + use your own Google-map-api key https://cloud.google.com/maps-platform/

Please help to post one ticket for all issues, moved this one to #1941
