### ISSUE TITLE
I Need setup service

### ISSUE THREAD

**Issue by samornreality2** [inspireui/support#1943]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: I'm newbie I don't understand the code and I want to upload to App store and playstore. So How much is setup cost?

2. Screenshots issues:

3. Proof of my purchased: 
![image](https://user-images.githubusercontent.com/9336214/73260626-e18e8800-41fc-11ea-8b0d-7166dacfa3ff.png)

3. Config files (optional)

**Comment by inspireui-support** [comment]
@samornreality2 - pls help to send your website info to our support email support@inspireui.com - our team will have a check and get back you soon - thanks

**Comment by samornreality2** [comment]
I have email to you please check.
