### ISSUE TITLE
[Flux Listing] - How to change single listing view

### ISSUE THREAD

**Issue by Bingo2000** [inspireui/support#1944]
How can I change single listing view:
![single_view](https://user-images.githubusercontent.com/13098762/73261793-17b41380-41cd-11ea-9f66-68fbd758ad78.jpg)

https://user-images.githubusercontent.com/13098762/73253749-65c11b00-41bd-11ea-8946-06c4e031d419.png

**Comment by inspireui-support** [comment]
Please open `lib/common/config.dart`, edit in the kProductDetail section.

```
"layout": kProductLayout.fullSizeImageType,
```

Please help to post one ticket for all issues, moved this one to #1941
