### ISSUE TITLE
Email register problem 

### ISSUE THREAD

**Issue by saioufe** [inspireui/support#1945]
### 1. My issue:
i was trying to get the user to register by email but every time i fill the form and press register by email an error show up , not the Json data 
i have follow the fluxStore docs and enabled the Rest Api in wordpress and made a key and everything , but when i send a request to the sever to register 

BTW : the sign up in facebook and google and sms is working very good just the email is not working 

this is the error :
`<script>
	document.cookie = "humans_21909=1"; document.location.reload(true)
</script>`

it suppose to be an **Json** data .

### 2. Screenshots issues:
![Screenshot_1580216592](https://user-images.githubusercontent.com/32012762/73266312-ba798b80-41e7-11ea-9d39-971a79c72f8d.png)

### 3. Proof of my purchased:
i have purchased the pro FluxStore this is my purchase proof 
![Untitled](https://user-images.githubusercontent.com/32012762/73262200-b09f5a80-41de-11ea-8da0-d8ca3027cc8b.png)

### config files
[Config.zip](https://github.com/inspireui/support/files/4122522/Config.zip)

**Comment by inspireui-support** [comment]
@saioufe - pls hep to use the latest Fluxstore 1.6.3, and install only mstore-api (we have remove the json-api on this release so that we don't need the setting as the documentation, we will update this guide shortly)

We have also noted some change on this link https://medium.com/@inspireui/announcing-fluxstore-1-6-337efff1791f

**Comment by saioufe** [comment]
how can i update the FluxStore only after i downloaded the files what should i do ??
should i change the project or what 

THANKS 

> @saioufe - pls hep to use the latest Fluxstore 1.6.3, and install only mstore-api (we have remove the json-api on this release so that we don't need the setting as the documentation, we will update this guide shortly)
> 
> We have also noted some change on this link https://medium.com/@inspireui/announcing-fluxstore-1-6-337efff1791f
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/1f55d85bfc898e06f175857fb52934c71284d708/68747470733a2f2f6d69726f2e6d656469756d2e636f6d2f6d61782f313230302f312a7577347776547456575f44434261536b4f6c47786d512e6a706567"><img alt="" height="14" src="https://camo.githubusercontent.com/a1c598ee8610a8cdb0e8bdbf112f3f1c77af25cb/68747470733a2f2f63646e2d7374617469632d312e6d656469756d2e636f6d2f5f2f66702f69636f6e732f66617669636f6e2d72656272616e642d6d656469756d2e33593678705a2d3046536457446e504d3368534249412e69636f"> Medium**[Announcing Fluxstore 1.6](https://medium.com/@inspireui/announcing-fluxstore-1-6-337efff1791f)**Latest update 14/12/2019

**Comment by saioufe** [comment]
it WORKED thanks man i really appreciated
