### ISSUE TITLE
[Flux Listin] - where to add google maps api key?

### ISSUE THREAD

**Issue by Bingo2000** [inspireui/support#1946]
https://user-images.githubusercontent.com/13098762/73053760-e8c63680-3e88-11ea-8571-cd277b6cce5b.jpg

where can I add google maps api key?

**Comment by saioufe** [comment]
in the common/config.dart 

![Untitled1](https://user-images.githubusercontent.com/32012762/73282650-04bc3600-4203-11ea-9dd7-1c278e611966.png)

**Comment by inspireui-support** [comment]
@Bingo2000 - pls check the similar guide for google map api from https://docs.inspireui.com/fluxstore/firebase/#address-filling-via-google-map

Please help to post one ticket for all issues, moved this one to #1941
