### ISSUE TITLE
[MStore Pro] - Shpping Calculation Issue

### ISSUE THREAD

**Issue by gokhand** [inspireui/support#1948]
We have set special Zone for the shipping , in our application, it is set as zoneid:3 . But the zone definitions even it has 30 and above it should have catch “free shipping” it is still showing flat rate. We are not using any plugin, default shipping zones. Is there any clear explanation about shipping settings, config file is not enought for explain and helpful.

I wrote that on the discussion page "https://codecanyon.net/item/beostore-complete-react-native-template-for-ecommerce/17010642/comments?page=109&filter=all#comment_23567125"

You have asked me to put common folder in a zip file and send it. Where can I send privately the zipped folder to check by you?

Thanks

---------

1. My issue:

2. Screenshots issues:

3. Proof of my purchased:

3. Config files (optional)

**Comment by inspireui-support** [comment]
@gokhand - pls send private file to support@inspireui.com and luyxtran264@gmail.com - thank you!

**Comment by gokhand** [comment]
I have sent the email with the information, btw I changed the zoneId to 1 to not make any confusion.

**Comment by luyx2412** [comment]
Hi @gokhand Please send your Config.js and AppConfig.json to luyxtran264@gmail.com

Thanks

**Comment by gokhand** [comment]
The email has sent about the files.
Thanks

**Comment by luyx2412** [comment]
Hi @gokhand 
You can edit zoneId in `src/common/Config.js` line 119
![image](https://user-images.githubusercontent.com/8909619/73670657-34c07900-46dc-11ea-82b7-ae1c1318114e.png)

P/S: Feel free to reopen the issue.

Thanks

**Comment by gokhand** [comment]
Hi,

I intentionally changed to 1 to check by you easily.
I know that area for zoneid 3  and how to change.

I changed to zoneid:1 and my Woocommerce site to handle zone id :1 .

You can check if the price higher than 40, it should be free of charge.
But it is not handling this, this is the issue.

Can you please check again.

Thanks

**Comment by gokhand** [comment]
Can you please reopen the ticket @inspireui-support ?

Thanks

**Comment by luyx2412** [comment]
Hi @gokhand Currently we did not support this feature. You can filter with price higher than 40 and charge free for this price in `src/redux/CartRedux.js` line 349 with `getPrice` function 
![image](https://user-images.githubusercontent.com/8909619/73806619-8f50f680-47fc-11ea-8676-a6dbfa477f5f.png)

P/S: Feel free to reopen the issue. And Noted for next version.

Thanks
