### ISSUE TITLE
[fluxestore] - sigin apple error

### ISSUE THREAD

**Issue by raiedahmed** [inspireui/support#1949]
Problem in sigin apple
![865CC7BA-A036-485A-BFCA-F90845CBEEC5](https://user-images.githubusercontent.com/41026234/73306745-81600c00-4225-11ea-88d7-e25349d8eb69.jpeg)
![9FE848FE-4665-41D0-BC46-EB069D240B58](https://user-images.githubusercontent.com/41026234/73306747-81600c00-4225-11ea-8f5e-26a4c9387d5d.jpeg)
![5CC241C5-0EF4-42DC-93D8-856CDFB83262](https://user-images.githubusercontent.com/41026234/73306748-81600c00-4225-11ea-8a24-1f4aec2b3ab9.png)
![C2E09299-0936-4986-BEE2-1D90287518AA](https://user-images.githubusercontent.com/41026234/73306749-81f8a280-4225-11ea-8383-6414f3eaa8d4.png)

**Comment by siyashamsudeen** [comment]
Im Having the same issue and have addressed the same in ticket https://github.com/inspireui/support/issues/1928

Still havent received solution to this. please help . 
i want to submit to appstore and dont want disapproval . please help . 

ios push notification also not working for me which is mentioned in the ticket

**Comment by minhtruong315** [comment]
@raiedahmed can u add me to your firebase? minhtruong315@gmail.com
I will check your config

**Comment by inspireui-support** [comment]
@raiedahmed - i've reviewed your app and have some feedbacks

The apple sign in is working ok, see this video https://www.dropbox.com/s/2q408jenjuola5d/RPReplay_Final1580301398.MP4?dl=0

But there are some data issues that Apple will reject your app as the data is not filled completely:
![IMG_3359](https://user-images.githubusercontent.com/58776791/73431791-c85c1780-4373-11ea-9c28-0e5eebeeee28.PNG)
![IMG_3360](https://user-images.githubusercontent.com/58776791/73431792-c85c1780-4373-11ea-90e0-a44d3d78ed3f.PNG)
![IMG_3361](https://user-images.githubusercontent.com/58776791/73431794-c8f4ae00-4373-11ea-8494-6d86819d3bde.PNG)

So try to add more data and test all the images products and submit to the AppStore again.

**Comment by raiedahmed** [comment]
Apple send problem for sigin 
![BEB68115-7FD4-41F9-AE0E-06224C1EBF68](https://user-images.githubusercontent.com/41026234/73437221-9d160000-4354-11ea-8b70-fa490b2d33b0.jpeg)

Error show after sigin apple

Note: app work in my mobile

**Comment by raiedahmed** [comment]
Apple's login works for me and works for you as well, but a problem appears during the review, which is the reason for the problem

**Comment by siyashamsudeen** [comment]
Apple sign in doesnt work for me . the error you mentioned is what i get when i try to do the apple login for my code . 

please see the below screens

![IMG_0007](https://user-images.githubusercontent.com/57159602/73439958-f0467d80-4369-11ea-9e55-5090f41a11f5.PNG)
![IMG_0008](https://user-images.githubusercontent.com/57159602/73439959-f0467d80-4369-11ea-8436-06b19e98a52a.PNG)
![IMG_0009](https://user-images.githubusercontent.com/57159602/73439962-f0df1400-4369-11ea-93d5-706a9584f4a7.JPG)
![IMG_0010](https://user-images.githubusercontent.com/57159602/73439963-f0df1400-4369-11ea-8cbd-44a9d0957737.PNG)
<img width="1017" alt="Screen Shot 2020-01-30 at 2 05 26 PM" src="https://user-images.githubusercontent.com/57159602/73439994-fccad600-4369-11ea-967b-a867dc68242b.png">
<img width="1344" alt="Screen Shot 2020-01-30 at 2 05 50 PM" src="https://user-images.githubusercontent.com/57159602/73439996-fccad600-4369-11ea-89a3-7f3789789557.png">

**Comment by raiedahmed** [comment]
@siyashamsudeen 
Enable database realtime

**Comment by siyashamsudeen** [comment]
can you advise where exactly i have to make this change ? you mean on firebase ?

**Comment by siyashamsudeen** [comment]
Thank you so much . it worked ! This is a brilliant help .

**Comment by raiedahmed** [comment]
@siyashamsudeen you are welcome

**Comment by raiedahmed** [comment]
Apple's login works for me and works for you as well, but a problem appears during the review, which is the reason for the problem

**Comment by siyashamsudeen** [comment]
@raiedahmed , seeing your issue im also quite afraid now. 
Well can you provide me your personal contact as i think it would be better if we can collaborate in our app publishing process. 

Thanks

**Comment by raiedahmed** [comment]
Facebook.com/raiedelghoul

**Comment by minhtruong315** [comment]
@raiedahmed Apple rejected your app because they can't login by apple sign in.
You only need to enable database realtime and set permission read/write is true. Then submit again to apple store. Thanks

**Comment by Senior-Gamal** [comment]
i have the same issue and enable database realtime read and write iam using 1.6.3 because 1.6.3 more issues

**Comment by papaya1986** [comment]
here too 1.6.4 apple showing wrror message ..done all 
1.apple sign in enabled xcode
2.apple sign in enabled firebase
3.but showing error
