### ISSUE TITLE
How to Show Related Products On DetailsSreen ?

### ISSUE THREAD

**Issue by imranshad** [inspireui/support#195]
I am willing to show related products products on DetailsScreen below the reviews. ProductRelated Tag is already available but not working i don't know why ?

**Comment by thangvo9x** [comment]
Hi. Please provide your purchase code. Thanks

**Comment by imranshad** [comment]
Here can I share code publicly ?

**Comment by minhcasi** [comment]
Hi @imranshad sorry for closing the issue as the supporting to customize the project is not included from our support scope, please spend your time to play around the function and customize the source code - thank you!

**Comment by imranshad** [comment]
>           Hi. Please provide your purchase code. Thanks
Hi, Did you have any solution ? Please mention
