### ISSUE TITLE
[Fluxstore Listing] - How to connect MyListing site 

### ISSUE THREAD

**Issue by sfeken15** [inspireui/support#1950]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:  

1. How to use "MyListing cover image" as the listing preview image? (rather than pulling the featured image)

2. How to select which information is displayed on listing?
3. How do you fix the category screen? (See image)
4. How do you fix red square? (See image)
5. How do you edit the side menu items? (See image)

2. Screenshots issues:
![Screenshot_1580285001](https://user-images.githubusercontent.com/60324276/73338586-91371a80-423c-11ea-9ebb-df6ffb9dc80c.png)
![Screenshot_1580285027](https://user-images.githubusercontent.com/60324276/73338587-91cfb100-423c-11ea-9005-0d4e137d465b.png)
![Screenshot_1580285599](https://user-images.githubusercontent.com/60324276/73338769-ef63fd80-423c-11ea-8214-c8965049db18.png)
![Screenshot_1580286086](https://user-images.githubusercontent.com/60324276/73339338-2ab2fc00-423e-11ea-8cdd-7a9619e970e2.png)

3. Proof of my purchased:
![Capture](https://user-images.githubusercontent.com/60324276/73339012-639ea100-423d-11ea-909e-843193516155.PNG)

3. Config files (optional)

**Comment by codingastronaut** [comment]
i also have the same issues, please revert

**Comment by inspireui-support** [comment]
@sfeken15 - please help to zip the common folder and share here so that we could help for checking

**Comment by sfeken15** [comment]
Okay. Here is my common folder. Thank you for helping!

[common.zip](https://github.com/inspireui/support/files/4132044/common.zip)

**Comment by sfeken15** [comment]
Any updates on this? Thanks.

**Comment by michaelbrinkworth** [comment]
did they get back to you? im from hypley not inspireui btw haha

**Comment by sfeken15** [comment]
@michaelbrinkworth havent heard anything yet

**Comment by sfeken15** [comment]
@inspireui-support Are there any updates on this?

**Comment by philipvu30** [comment]
Hi sfeken15,

I apologize for the late response. Would you mind sending me your website'a username and password? I need to make sure if the configuration is correct. You can send them privately through this email: toan@inspireui.com. Thank you.

**Comment by sfeken15** [comment]
@philipvu30 No problem. Sending it now.

**Comment by philipvu30** [comment]
Hi @sfeken15,

I am sorry to bother you but I was unable to login with the account you sent me yesterday. Could you please send it back? Thank you

**Comment by sfeken15** [comment]
@philipvu30 resent

**Comment by philipvu30** [comment]
Hi @sfeken15 ,

Please upgrade your app to the newest version and replace your common folder to this attachment: 
[common.zip](https://github.com/inspireui/support/files/4163720/common.zip)

For further questions, please contact me through Skype for faster support. Thank you.

My skype: vuthanhtoan30@gmail.com

**Comment by sfeken15** [comment]
@philipvu30 Thank you for the help! That seems to fix alot of things. 

Does the ListApp wordpress plugin control anything with this Fluxstore Listing App?

**Comment by philipvu30** [comment]
Hi @sfeken15 ,

It helps to communicate between your app and website. It does not have any impact on Fluxstore Listing App. 
We will release a builder for users to customize their layout in the future. 

Is there anything else I can help you with? Otherwise I will mark this as solved.
