### ISSUE TITLE
[Mstore-Pro] - ** BUILD FAILED ** Lastest version of Mstore-Pro

### ISSUE THREAD

**Issue by SuperXonic** [inspireui/support#1951]
Hello InspireUI Team,
I bought the Mstore-Pro code and This is my purchase screenshot & I can provide my purchase code later if you want.

<img width="772" alt="Screen Shot 2020-01-29 at 3 20 23 PM" src="https://user-images.githubusercontent.com/52225482/73339252-ef024b80-42aa-11ea-968b-d5ee85d0d73d.png">

This is the error message after i try to build and Test the app

** BUILD FAILED **

The following build commands failed:
	CompileC /Volumes/DATA/mstore-3.9.7/mstore-pro\ copy/ios/build/mstore/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNReanimated.build/Objects-normal/x86_64/REACallFuncNode.o /Volumes/ Dev/mstore-3.9.7/mstore-pro\ copy/node_modules/react-native-reanimated/ios/Nodes/REACallFuncNode.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Volumes/ Dev/mstore-3.9.7/mstore-pro\ copy/ios/build/mstore/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNReanimated.build/Objects-normal/x86_64/REAAlwaysNode.o /Volumes/ Dev/mstore-3.9.7/mstore-pro\ copy/node_modules/react-native-reanimated/ios/Nodes/REAAlwaysNode.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Volumes/ Dev/mstore-3.9.7/mstore-pro\ copy/ios/build/mstore/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNReanimated.build/Objects-normal/x86_64/REAClockNodes.o /Volumes/ Dev/mstore-3.9.7/mstore-pro\ copy/node_modules/react-native-reanimated/ios/Nodes/REAClockNodes.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Volumes/ Dev/mstore-3.9.7/mstore-pro\ copy/ios/build/mstore/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNReanimated.build/Objects-normal/x86_64/REABezierNode.o /Volumes/ Dev/mstore-3.9.7/mstore-pro\ copy/node_modules/react-native-reanimated/ios/Nodes/REABezierNode.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(4 failures)

How can i fix this issue?

I really love your products and i bought a fews already.
Thank you so much for your support & time.
best regards

**Comment by inspireui-support** [comment]
@SuperXonic - could you give the comment on this link to verify your username again please - https://codecanyon.net/item/beostore-complete-react-native-template-for-ecommerce/17010642 - thank you!

**Comment by SuperXonic** [comment]
It works now.

- Go to ios folder and remove the Pod folder, Podfile.lock
- Run: pod repo update
- Run: pod install

From the mstore-pro folder, run:
- yarn install && yarn start --reset-cache
- Run: react-native run-ios
