### ISSUE TITLE
[MStore Pro] - Live app issue [urgent]

### ISSUE THREAD

**Issue by Pankti16** [inspireui/support#1952]
1. My issue:
When installing from the play store, I can successfully log in using Facebook(but showing my old logo everywhere). After that, if I log out it the option to log in with Facebook is not available(but showing a new logo everywhere). 

2. Playstore link: [Visionary Pirate](https://play.google.com/store/apps/details?id=com.visionarypirate)

Proof of my purchased:
[52190056-beostore-complete-react-native-template-for-ecommerce-license.pdf](https://github.com/inspireui/support/files/4127068/52190056-beostore-complete-react-native-template-for-ecommerce-license.pdf)

Config files (optional)
[Config.zip](https://github.com/inspireui/support/files/4127070/Config.zip)

**Comment by luyx2412** [comment]
Hi @Pankti16 Please make sure you changed `live mode` in your facebook app. https://developers.facebook.com/blog/post/2019/09/23/live-mode-for-production-use/

P/S: Feel free to reopen the issue.

Thanks

**Comment by Pankti16** [comment]
Live mode is on already.

**Comment by luyx2412** [comment]
Hi @Pankti16 Please follow the comment to fix your issue https://stackoverflow.com/a/56765362

P/S: Feel free to reopen the issue.

Thanks
