### ISSUE TITLE
[EvaStore] - console.log doesn't show in react-native-debugger / expo 

### ISSUE THREAD

**Issue by satyavh** [inspireui/support#1953]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:

I'm running the app `yarn start` which starts expo, and I can successfully run the store in the ios Simulator. I enable remote debugging in the simulator, and add a console.log statement to for example Title.js line 22, like this:

```
    const isOnSale = selectedVariant
      ? selectedVariant.onSale
      : product.onSale;

    console.log('selectedVariant', selectedVariant);
```

Nothing is being logged in the remote debugger.
The remote debugger doesn't show anything. Not the component structure, nothing happens. According to the expo docs that should happen almost automatically.

Is there some magic setting?

2. Screenshots issues:
n/a

3. Proof of my purchased:
1bbf5cf2-76d7-4abd-ba4f-c09b61ff3f86

**Comment by luyx2412** [comment]
Hi @satyavh Please open `Debug JS remote` to see your console log https://facebook.github.io/react-native/docs/debugging, Because react-native-debugger only work with debug mode https://github.com/jhen0409/react-native-debugger/blob/master/docs/debugger-integration.md#debugger-integration

P/S: Feel free to reopen the issue.

Thanks

**Comment by satyavh** [comment]
Yes I did enable Debug JS remote, both from simulator and from expo iOS.
React-native-debuger opens browser window in Chrome, says it's connected to a debugging session. But no logs show up.

Could there be a mismatch between expo versions?
