### ISSUE TITLE
[Flux Listing] - What are the other strings to use instead of "kProductLayout.listingSimpleType"

### ISSUE THREAD

**Issue by Bingo2000** [inspireui/support#1955]
How can I change single listing view:

What are the other strings to use instead of
"kProductLayout.listingSimpleType"

![BingoEnvato](https://user-images.githubusercontent.com/13098762/73359978-46e88480-42a2-11ea-87ca-9c626ab55f44.jpg)

**Comment by inspireui-support** [comment]
@Bingo2000 - if you are using the IDE tools like Android Studio or VS Code, when typing kProductLayout. it will auto-show the list enum for the list. 

Also, pls help to read the document before rasing new ticket to save our time, we have noted it on the document already - https://tppr.me/NbnxB - https://docs.inspireui.com/fluxstore/home-layout/#category-layout
