### ISSUE TITLE
[my-product] -BeoNews Pro

### ISSUE THREAD

**Issue by gmldigital2019** [inspireui/support#1956]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:

2. Screenshots issues:

3. Proof of my purchased:

3. Config files (optional)
Good Day, 
We purchased the Beo News application and while we have followed all the documentation we still have many issues with outdated code etc. Please see a live link to comprehend our questions and issues below. 
https://appetize.io/app/c8740qfkc1zep3v9rxw0c79j2m?device=nexus5&scale=75&orientation=portrait&osVersion=8.1

1) Home Layout- We were not able to implement a continuous scroll unless we chose our main view as the combo view option, however, this removed our top slider with recent stories. 

2) Only one of our ad spot works and the user needs to scroll to the bottom of all the content to view it. 

3) The Category Page, we want to adjust this page to only show specific categories but did not see the option to do this, also were not able to turn on the switch that allows a different view for this section. 

4) Email sign up and commenting- We followed the instructions sent to us but still did not reive the email to register, users were created but they were not showing up in our wordpress backend. Also, when we tried to sign in to the app it did not work.

Below is a screenshot of our purchase from you guys and code to verify we are customers of your product. Also, if possible kindly state the best communication options to resolve these issues since Github has proven difficult for our developers to et a response.  
![image](https://user-images.githubusercontent.com/60437057/73369561-2c55e180-4289-11ea-902a-b689529dd3d0.png)

Purchase Code: 8be3e9e9-5fc2-4207-8cc2-cb99d978981d

**Comment by inspireui-support** [comment]
@gmldigital2019 - could you zip the current source and send it back to support@inspireui.com for further investigation - thank you!

**Comment by gmldigital2019** [comment]
I emailed to support but I am not getting a response, I emailed them prior to this ticket and still have not gotten any feedback.

**Comment by gmldigital2019** [comment]
Good Day Still no feedback.

**Comment by inspireui-support** [comment]
@gmldigital2019 - sorry for the delay as i have missed you email from our Junk email, we will have a check and let you know - thank you!

**Comment by gmldigital2019** [comment]
Good Day, any feedback?

**Comment by luyx2412** [comment]
Hi @gmldigital2019 Sorry about reply you late, can you send me your Config.js?

Thanks

**Comment by gmldigital2019** [comment]
Can you send me your email?

**Comment by gmldigital2019** [comment]
Good Day, I sent you the email yesterday to your gmail from jenna-marie.preudhomme@guardian.co.tt. Can you kindly review I need to give an update on to my project team.

**Comment by luyx2412** [comment]
Hi @gmldigital2019 I saw your email, let me check and reply you soon.

Thanks
