### ISSUE TITLE
[ListApp] App Not Working ListApp

### ISSUE THREAD

**Issue by thespottedrabit** [inspireui/support#196]
Hello, I tried to use CeBuilder to run ListApp and it is not pulling information from my site. Please see screenshots from the Expo build.

Also the My Listing theme supports shops in listings, I dont see that here in ListApp...?

![50236813_2105121696249331_3077766958653898752_n](https://user-images.githubusercontent.com/13178140/51444426-a0dc6480-1cb4-11e9-88df-a3ddd8e155f3.png)
![50853114_281433225874365_6445565044397703168_n](https://user-images.githubusercontent.com/13178140/51444427-a0dc6480-1cb4-11e9-817f-7c9ac7d121c3.png)
![50550880_750917048634706_2969964267366776832_n](https://user-images.githubusercontent.com/13178140/51444428-a0dc6480-1cb4-11e9-9297-dcff4f975ca2.png)
![50788445_503251550198238_7022572112246210560_n](https://user-images.githubusercontent.com/13178140/51444429-a0dc6480-1cb4-11e9-8e2e-d2f63f758e3f.png)

**Comment by thangvo9x** [comment]
Hi. Please provide us your purchase code. Thanks

**Comment by thespottedrabit** [comment]
I don't know where to find that. Please see the screenshots below. Thank
you.

**Comment by thangvo9x** [comment]
https://codecanyon.net/downloads Please refer

**Comment by thespottedrabit** [comment]
Licensor's Author Username: InspireUI
Licensee: monique gowie
Item Title: ListApp - Listing Directory mobile app by React Native
Item URL:
https://codecanyon.net/item/listapp-listing-directory-mobile-app-by-react-native/21456447

Item ID: 21456447
Item Purchase Code: d8e3e06f-3447-4914-82e7-e55ac10bb234
Purchase Date: 2019-01-18 06:45:21 UTC


<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by thangvo9x** [comment]
Hi. Please send your AppConfig.json file such as your MyListing.js in Config folder to us to email thang@inspireui.com

**Comment by thespottedrabit** [comment]
Hello??

**Comment by zukosanti** [comment]
hey guys was this issue solved??????

**Comment by thespottedrabit** [comment]
Hello, I dont know what files those are?? Can someone help I thought this was a one-click install but its not.....
