### ISSUE TITLE
[Fluxstore] - Build Failed With an Exception

### ISSUE THREAD

**Issue by Saifahmad99** [inspireui/support#1960]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: When I run the command flutter build appbundle it shows error Build Failed With an Exception This is my build.gradle Code

buildscript {
    repositories {
        // ...
        maven { url 'https://plugins.gradle.org/m2/' } // Gradle Plugin Portal
    }
    dependencies {
        // ...
        // OneSignal-Gradle-Plugin
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.12.1, 0.99.99]'
    }
}

apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {

android {
    compileSdkVersion 28

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.celkart.store"
        minSdkVersion 19
        targetSdkVersion 28
        versionCode 1
        versionName 1.0
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
        resConfigs "en"
    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
        }
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.release
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
    implementation 'com.google.firebase:firebase-core:16.0.9'
    implementation 'com.google.android.gms:play-services-auth:16.0.0'
    implementation 'com.google.firebase:firebase-auth:18.1.0'
    implementation 'com.android.support:multidex:1.0.3'
    implementation 'com.google.firebase:firebase-storage:18.1.0'
    implementation 'com.google.firebase:firebase-ads:17.2.0'
    implementation 'com.facebook.android:facebook-android-sdk:[5,6)'
    implementation 'com.onesignal:OneSignal:[3.11.2, 3.99.99]'
}

2. Screenshots issues:
![Screenshot (46)](https://user-images.githubusercontent.com/59877416/73424593-49f07d00-4355-11ea-9f29-451b33b02188.png)

3. Proof of my purchased:
![Screenshot (32)](https://user-images.githubusercontent.com/59877416/73424607-54ab1200-4355-11ea-9763-4567de0b18dc.png)

3. Config files (optional)

**Comment by inspireui-support** [comment]
@Saifahmad99 - could you take the screenshot of build issue?

**Comment by Saifahmad99** [comment]
![Screenshot (49)](https://user-images.githubusercontent.com/59877416/73460205-1ab22e00-439e-11ea-83ab-06fd4d2bf406.png)

**Comment by Saifahmad99** [comment]
Please help with........

**Comment by inspireui-support** [comment]
@Saifahmad99 - could you help to run this script

```
flutter channel stable
flutter upgrade --force
```

Also help to run the Test Drive example first to make sure all the library are ready to run with Flutter - https://flutter.dev/docs/get-started/test-drive?tab=vscode

**Comment by Saifahmad99** [comment]
I've already run both commands and got nothing still there is an error
Also my app was working fine earlier but maybe after changing the key password and path in key.properties now I can't also run the debug.

**Comment by Saifahmad99** [comment]
Hello is anyone there we have a serious issue here and trying to find the solution.

**Comment by inspireui-support** [comment]
Hi @minhtruong315 - pls help to support @Saifahmad99 via teamviewer - thank you!

**Comment by Saifahmad99** [comment]
Please be quick to just let you know I am using the latest version 1.6.3

**Comment by minhtruong315** [comment]
supported
