### ISSUE TITLE
[Fluxstore-Listing] - No Blog view

### ISSUE THREAD

**Issue by Bingo2000** [inspireui/support#1961]
Followed the manual and insert this in cinfig.json:
{
      "name": {
        "en": "Blog Posts"
      "layout": "blog"
    },
but only a blank, white area is shown on homepage.
When clicking the "Blog-Link in the drawer I got the following errors:

![no_blog](https://user-images.githubusercontent.com/13098762/73431658-35a28500-4341-11ea-8cac-892654e99a2b.jpg)

![BingoEnvato](https://user-images.githubusercontent.com/13098762/73431692-4c48dc00-4341-11ea-9614-547344c19c90.jpg)

**Comment by inspireui-support** [comment]
@Bingo2000 - would you mind to move this issue to ticket #1941

Please make sure to update the plugins as guideline https://docs.inspireui.com/fluxstore/listing-directory/
Also, please share your common folder so that we could help with checking,

**Comment by Bingo2000** [comment]
Installed and activated the plugin in WP.
Please see site URL in: config_vanagogo.dart
in common:
[common.zip](https://github.com/inspireui/support/files/4134510/common.zip)
