### ISSUE TITLE
how to enable url link in post

### ISSUE THREAD

**Issue by roziseth01** [inspireui/support#1962]
Hi,

My issue:
1) Link or page refresh/redirect not functioning in wordpress post
2) Link disable in wordpress post.

Screenshots issues:
![Screenshot_20200130-161730](https://user-images.githubusercontent.com/59671391/73431768-2260db00-437c-11ea-829c-be05a6101506.jpg)

Proof of my purchased:
Screenshot 2020-01-09 at 7 40 07 AM
![image](https://user-images.githubusercontent.com/59671391/73431509-8c2cb500-437b-11ea-955c-a29cb9a60f80.png)

**Comment by dttrung26** [comment]
Good morning @roziseth01 ,
please send me your /lib/common folder for checking. Have a nice day btw xD

**Comment by roziseth01** [comment]
[common.zip](https://github.com/inspireui/support/files/4139422/common.zip)
hi,
as requested.

**Comment by roziseth01** [comment]
so how?

**Comment by dttrung26** [comment]
Hi there, it seems like you are using the old version Fluxstore. Please double-check whether or not you are using version 1.6.3. 

Best!
