### ISSUE TITLE
Fluxstore Multi Vendor - Flutter E-commerce Full App

### ISSUE THREAD

**Issue by tahirmirji** [inspireui/support#1963]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
Getting errors in ios>Flutter>App.framework?flutter_assets>lib>common>constants.dart as stated below:

`Target of URI doesn't exist: './screens/blogs.dart'.
Try creating the file referenced by the URI, or Try using a URI for a file that does exist.dart(uri_does_not_exist)`

2. Screenshots issues:
![constant dart](https://user-images.githubusercontent.com/34068623/73436055-cbed9f80-436f-11ea-8b4e-3e367b5434a9.png)

3. Proof of my purchased:
![order](https://user-images.githubusercontent.com/34068623/73436082-d871f800-436f-11ea-8688-fcc07a73940c.png)

30 Jan 2020 
Order ID: 119596941
 Fluxstore Multi Vendor - Flutter E-commerce Full App (Regular License)
Invoice: IVIP36275155 
$51.00

3. Config files (optional)
all other things are followed as per the instruction.

**Comment by inspireui-support** [comment]
@tahirmirji - could you try with the latest 1.6.3 - it seems your screenshot is taken from the old version - thank you!

**Comment by tahirmirji** [comment]
@inspireui-support  - 
**1)       I did not get you, which version must be latest:** 

**My present versions are as follow:**

```
C:\Users>dart --version
Dart VM version: 2.7.0 (Mon Dec 2 20:10:59 2019 +0100) on "windows_x64"

```

```
C:\Users\>flutter --version
Flutter 1.12.13+hotfix.7 ΓÇó channel stable ΓÇó
https://github.com/flutter/flutter.git
Framework ΓÇó revision 9f5ff2306b (4 days ago) ΓÇó 2020-01-26 22:38:26 -0800
Engine ΓÇó revision a67792536c
Tools ΓÇó Dart 2.7.0
```

```
visual studio code
C:\Users\>code --version
1.41.1
```

please specify which version to update.

2) Where to update firebase configs there is no code blueprint/tree anywhere in documentations like:
![tree](https://user-images.githubusercontent.com/34068623/73516504-9f449100-441e-11ea-9bd5-181d55ae2e1e.png)

please help in configuring firebase it is a much-needed feature for my purchase intention, fast response expected as per ratings.


Thank you in advance.

**Comment by inspireui-support** [comment]
Hi @tahirmirji - i mean the latest Fluxstore version that could be downloaded from http://codecayon.net/downloads - thank you!

**Comment by tahirmirji** [comment]
**Not able to know how edit will you please help me edit?**

**Comment by inspireui-support** [comment]
Sorry for late response, i mean download the latest code 1.6.3 and reinstall the project again will be fixed the issue - let us know your checking - thank you!
