### ISSUE TITLE
Questions before buying regarding FluxStore Listing and FluxStore MultiVendor

### ISSUE THREAD

**Issue by Pz23112604** [inspireui/support#1964]
Hi I own a listeo wordpress page.

I want to bring this one to iOS and Android.

My end customers shall be able to download it for free and book my services in the app.

What do I need? 2 times the regular licence?

Regarding Fluxstore Multi Vendor:
I saw your Fluxstore Multi Vendor. Is it app only? Is it possible to set up services, event tickets, etc. as products instead of physical products?

Thanks for answering. KR, Philipp

**Comment by inspireui-support** [comment]
Hi, thank you for the email, the 1 regular license for FluxStore Listing will be met your requirements, delivery for both Appstore and Google Play store.

It's possible to use Fluxstore Multi Vendor for setup services, event tickets... for multi-purpose

**Comment by Pz23112604** [comment]
ok thx. one more thing. in the multivendor one, are vendors paid immediatly or goes all the money to me and I have to distribute?
