### ISSUE TITLE
[Fluxstore Listing] - Changing name or Bundle ID fails

### ISSUE THREAD

**Issue by Bingo2000** [inspireui/support#1965]
Changing name or BundleID, described here:

https://docs.inspireui.com/fluxstore/customization/

fails with:

![change_name](https://user-images.githubusercontent.com/13098762/73444310-a43f0d00-4358-11ea-95e8-17d946829b76.jpg)

String in in ios/Runner/Info.plist is a variable.
Where can I set the value for this?
```
<key>CFBundleDisplayName</key>
	<string>Fluxstore</string>
```
in ios/Runner/Info.plist is

```
<key>CFBundleDisplayName</key>
	<string>$(PRODUCT_NAME)</string>
```

**Comment by inspireui-support** [comment]
Hi, you can simply open the XCode and change the app name - https://tppr.me/AaoM0

**Comment by Bingo2000** [comment]
Does not work. After changing and flutter clean Debug-Console shows:

`Launching lib/main.dart on iPhone 8 in debug mode...
Xcode build done.                                           61,4s
Could not find the built application bundle at build/ios/iphonesimulator/Runner.app.
Error launching application on iPhone 8.
Exited (sigterm)`

Before (worked) :

![before](https://user-images.githubusercontent.com/13098762/73522311-5b469180-4408-11ea-9ae4-3d861efb2871.jpg)

After (shows error in Debug-Console):

![after](https://user-images.githubusercontent.com/13098762/73522312-5b469180-4408-11ea-9bcb-a029610c9f8b.jpg)
