### ISSUE TITLE
[FluxStore] how to use deep linking to show products

### ISSUE THREAD

**Issue by Mohamed20884** [inspireui/support#1966]
Hi

I would like to ask how to use deep linking implemented in the project to show the product page for the woocommerce backend products.

Thanks

**Comment by inspireui-support** [comment]
Hi, it's possible to open the deep link for open the product, you can get this guide to get the idea - https://docs.inspireui.com/fluxstore/customization/#9-deeplink - thank you!

**Comment by Mohamed20884** [comment]
Hi

I tried this and was able to load the 404 page from the example however when I used a link from a product on my site it did not take me to the product page in the app but to the home screen of the app. please let me know what should be done to get the desired result.

Thanks

**Comment by Mohamed20884** [comment]
@inspireui-support

**Comment by gonzalovvt** [comment]
Any response, i was looking for a solution for deeplink to a vendor page in multi vendor app..
