### ISSUE TITLE
[beonews-pro] - Updating react-native from 0.60.4 to 0.61.4 error

### ISSUE THREAD

**Issue by Cod3Guy** [inspireui/support#1968]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:

I tried to update react-native from 0.60.4 to 0.61.4, because I need it to be integrated with other react-native libraries which only available in version 0.61.4. It shows multiple errors. Can you provide guideline on how to upgrade it to react-native 0.61.4, or is there any version of beonews-pro that support RN 0.61?

2. Screenshots issues:

<img width="446" alt="Screenshot 2020-01-30 at 10 35 34 PM" src="https://user-images.githubusercontent.com/10850622/73459031-278c4d00-43b1-11ea-9cdd-477989ef9cf0.png">

3. Proof of my purchased:

77105d26-b9ad-416f-883b-16af6a48cab3

3. Config files (optional)

**Comment by inspireui-support** [comment]
@Cod3Guy - we will upgrade a new RN on next release 

In the meantime, you can check the detail Changelog for the fixing - https://github.com/react-native-community/releases/blob/master/CHANGELOG.md

Thank you!

**Comment by luyx2412** [comment]
Updated next version
