### ISSUE TITLE
[Beonews] Fixing errors in beonews 

### ISSUE THREAD

**Issue by hadi13** [inspireui/support#197]
1-how to change categories photos

2-how to add videos to video page (added category number but not working)

3-back button is not showing sometimes.

4-how to remove the navigation top bar.

5-how to change the style of left menu?

6- comments are not all received to WP admin.
![dfb423c6-0358-4e8a-a902-0bf594f71376](https://user-images.githubusercontent.com/2642454/51456763-f02b9f00-1d5f-11e9-8c99-f700d40dfa15.jpeg)

**Comment by minhcasi** [comment]
Can you send your config.js file here

Note: as your questions are included some customization code that not include from the support licenses so that we will only provide a solution and may not detail

Thank you!

**Comment by hadi13** [comment]
@minhcasi

find my config.js attached,

what is the customization I've requested?

[config.txt](https://github.com/inspireui/support/files/2777924/config.txt)

**Comment by hadi13** [comment]
Still waiting?!

**Comment by minhcasi** [comment]
1 - photo is using for all cate, you can custom this file Redux/actions/PostActions.js - the fetchPhotos to add the category id to limit the list

2. Chage the CategoryVideo: 34, from config.js file - see our URL for the example of video - http://news.inspireui.com/an-excellent-one-pan-protein-packed-power-pasta/

3. we will have a check as it could be a bug.

4. remove this https://gyazo.com/4a8259bfdf580f19975e2782ff92a951

5. customize the components/leftmenu

6. it only loads the publish comments

Please note that we may not support the question "how to" as this kind of customization stuff and require your developer skill to customize the app that not include from our support scope (https://codecanyon.net/page/item_support_policy), any issues or bug are welcome to report for fixing, hope you can understand.

**Comment by hadi13** [comment]
ok, still the below is not solved,

1 - photo is using for all cate, you can custom this file Redux/actions/PostActions.js - the fetchPhotos to add the category id to limit the list>>>>> **where can I change the photos?**



6-it only loads the publish comments >>> the comments are sent from the app but I can not see them on the WP admin panel. see attached my function.php file 
[functions.txt](https://github.com/inspireui/support/files/2779672/functions.txt)

**Comment by hadi13** [comment]
Please provide me with the latest pro version for Android & IOS ASAP
