### ISSUE TITLE
Can't approve envato account

### ISSUE THREAD

**Issue by mariablomberg** [inspireui/support#1970]
Nothing happens when i press Approve. 
When I press 'deny', I get the error-code: {"error":"access_denied","error_description":"User denied the access to the resource"}

Purchase code: 56c14546-d8ea-4024-9a11-20c549cda35a

**Comment by mariablomberg** [comment]
<img width="1030" alt="Screen Shot 2020-01-30 at 17 40 10" src="https://user-images.githubusercontent.com/44641181/73470337-04997300-4388-11ea-9750-abe57809cffe.png">

**Comment by minhtruong315** [comment]
@mariablomberg add my skype: minhtruong315
I will help u check

**Comment by minhtruong315** [comment]
https://github.com/inspireui/support/issues/1972
