### ISSUE TITLE
[EvaStore] - console.log doesn't show in react-native-debugger / expo

### ISSUE THREAD

**Issue by satyavh** [inspireui/support#1971]
Reopening issue #1953 

1. My issue:

I'm running the app `yarn start` which starts expo, and I can successfully run the store in the ios Simulator and on a phone. I enable remote debugging in the simulator (`Debug JS remote`), and add a console.log statement to for example Title.js line 22, like this:

```
    const isOnSale = selectedVariant
      ? selectedVariant.onSale
      : product.onSale;

    console.log('selectedVariant', selectedVariant);
```
I did enable `Debug JS remote` both from simulator and from expo iOS. React-native-debuger opens browser window in Chrome, says it's connected to a debugging session. But no logs show up.

The stand-alone react-native-debugger doesn't show anything either. Not the component structure, nothing happens. According to the expo docs that should happen almost automatically.

Is there some magic setting? Could there be a mismatch between expo versions? 

2. Screenshots issues:
ProductDetailsContainer/Title.js - Line 22, adding console.log
![Screenshot 2020-01-30 at 20 30 32](https://user-images.githubusercontent.com/3264269/73483256-66b1a280-439f-11ea-82f3-b81548b677d6.png)

Going to a view that renders Title.js
![Screenshot 2020-01-30 at 20 32 21](https://user-images.githubusercontent.com/3264269/73483421-b1331f00-439f-11ea-91c9-8febbacbd60a.png)

Console.log doesn't show in debugger, even though debugging session is connected
All the console.logs that were already in the template do not show!
<img width="1358" alt="Screenshot 2020-01-30 at 20 29 23" src="https://user-images.githubusercontent.com/3264269/73483156-47b31080-439f-11ea-949d-73f00a9c1c7b.png">

React-native-debugger (0.10.6) standalone app, never connects on default port 19001
![Screenshot 2020-01-30 at 20 31 25](https://user-images.githubusercontent.com/3264269/73483337-8943bb80-439f-11ea-85d6-6a6697a0a560.png)

3. Proof of my purchased:
1bbf5cf2-76d7-4abd-ba4f-c09b61ff3f86

**Comment by luyx2412** [comment]
Hi @satyavh Please open new port `19001` based on the image. Because the expo only connected with port `19001`
![image](https://user-images.githubusercontent.com/8909619/73564241-b6709680-4491-11ea-9625-8c741d6c4160.png)

P/S: Feel free to reopen the issue.

Thanks

**Comment by satyavh** [comment]
You are not reading my issue, for the 2nd time already.

I have found the problem - caused by you - so the question is why you are shipping code that has console.log disabled by default in the native debugger.

**Comment by hussainimdad004** [comment]
@satyavh I'm having same issue. 
Could you please let me know you resolve this issue.
