### ISSUE TITLE
Fluxstore multivendor 

### ISSUE THREAD

**Issue by rgbufferchime** [inspireui/support#1972]
1. My issue: Firstly please dont close the issue before getting a confirmation please.now, As per your instructions i updated the app source as well as mstore plugin in my wordpress yesterday.I am using dokan there.Earlier neither my categories nor my stores where showing up in the app, but after your update ,**stores show up and products inside that show**.
**But, categories are still not showing and also search is not working for any product.**

2. Screenshots issues:
![search](https://user-images.githubusercontent.com/43860635/73496806-66d19280-43df-11ea-8aa3-defdf7d63b89.PNG)
![store](https://user-images.githubusercontent.com/43860635/73496808-66d19280-43df-11ea-94bd-4c7dc719d371.PNG)
![s](https://user-images.githubusercontent.com/43860635/73496809-66d19280-43df-11ea-91d8-772f5e31ff33.PNG)
![Capturegh](https://user-images.githubusercontent.com/43860635/73496810-676a2900-43df-11ea-892e-bf2203fc67ca.PNG)
![jkl](https://user-images.githubusercontent.com/43860635/73496811-676a2900-43df-11ea-913e-617d679354a7.PNG)

3. Proof of my purchased:

![73142661-5192f600-40b7-11ea-8cfb-d459d2492dd3](https://user-images.githubusercontent.com/43860635/73496853-7cdf5300-43df-11ea-8425-1a89320b8d3d.png)

3. Config files (optional)
![hjklhhh](https://user-images.githubusercontent.com/43860635/73497060-e8c1bb80-43df-11ea-91ff-f50237cd6ddd.PNG)

**Comment by minhtruong315** [comment]
@rgbufferchime send me config.dart and config.json file

**Comment by rgbufferchime** [comment]
@minhtruong315 here they are



[common.zip](https://github.com/inspireui/support/files/4142477/common.zip)

**Comment by minhtruong315** [comment]
@rgbufferchime I checked your config. I see it's showing categories.
https://tppr.me/WhUkt
The categories screen only shows category has parent is zero and that category must have products

**Comment by minhtruong315** [comment]
@rgbufferchime search is working https://tppr.me/Vyk4b
Did you download source code 1.6.3 in codecanyon?
I'm using this your config
[config.dart.zip](https://github.com/inspireui/support/files/4143449/config.dart.zip)

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
