### ISSUE TITLE
mstore - Adding an item to cart does not update number of items for product in Cart View

### ISSUE THREAD

**Issue by inimist** [inspireui/support#1974]
1. My issue:

I am using Mstore. 

There is an issue with quantity in cart. When user adds an item to cart the item count at top right corner is updated file. However the number of items in the input field next to product is not updated and it keeps showing it as 1 (one)

Attaching screenshots:

2. Screenshots issues:

![cart](https://user-images.githubusercontent.com/447618/73525665-aaef8200-4435-11ea-8113-2574a66a6f2e.gif)
![add to cart](https://user-images.githubusercontent.com/447618/73525703-bc388e80-4435-11ea-9166-e1247de2cad8.png)
![cart](https://user-images.githubusercontent.com/447618/73525727-c3f83300-4435-11ea-9ef9-fae40eb179fa.png)

3. Proof of my purchased:

![Proof](https://user-images.githubusercontent.com/447618/73525756-d1152200-4435-11ea-907b-328741347251.png)

3. Config files (optional)
NA

**Comment by luyx2412** [comment]
Hi @inimist Can you send me the Config.js and AppConfig.json file?

Thanks

**Comment by inimist** [comment]
[common.zip](https://github.com/inspireui/support/files/4146281/common.zip)

Please find the attachments.

Thanks!

**Comment by luyx2412** [comment]
Hi @inimist 
Please replace `src/redux/CartRedux.js` with this file to fix the issue.
[CartRedux.js.zip](https://github.com/inspireui/support/files/4148999/CartRedux.js.zip)

P/S: Feel free to reopen the issue.

Thanks
