### ISSUE TITLE
[Fluxstore] - razorpay not working in release builds

### ISSUE THREAD

**Issue by shreyas-shriyan** [inspireui/support#1975]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
razorpay not working in release builds , razorpay works on debug builds but crashes the app on release builds
2. Screenshots issues:

3. Proof of my purchased:
<img width="1178" alt="sssss" src="https://user-images.githubusercontent.com/51715896/73544237-c02cd680-445e-11ea-8bcf-eea73cc470de.png">

3. Config files (optional)
https://github.com/shreyas-shriyan/pariconfig

**Comment by minhtruong315** [comment]
@shreyas-shriyan can u take me screenshot for address checkout?

**Comment by shreyas-shriyan** [comment]
solved it by adding progaurd rules in the build file according to razorpay instructions
