### ISSUE TITLE
[MStore Magento] - The Rest API is not working correctly

### ISSUE THREAD

**Issue by nagg-glotelho** [inspireui/support#1976]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.\

---------

1. My issue: 
The Rest API is not working correctly while trying to install MStore with CeBuilder. Please provide the correct access token for http://magento2.mstore.io to test the MStore or let me know how to create my own token with magento

2. Screenshots issues: 
<img width="1280" alt="Screen Shot 2020-01-31 at 16 27 00" src="https://user-images.githubusercontent.com/60516034/73556305-7983b000-444f-11ea-9b2c-2027e9823f8c.png">

3. Proof of my purchased:
<img width="1280" alt="Screen Shot 2020-01-31 at 17 33 37" src="https://user-images.githubusercontent.com/60516034/73556511-e0a16480-444f-11ea-8edc-238a173b5dbf.png">

3. Config files (optional)

**Comment by minhtruong315** [comment]
@nagg-glotelho pls update accessToken: 7r5x3cae1dm3bcx6rbeyvnagxl6afxpo in AppConfig.json then try again

**Comment by nagg-glotelho** [comment]
Ok thank you.
Please how can I create my own Magento  Access Token ?

**Comment by RashVenkat6795** [comment]
After adding the appropriate access token and website url 
is it working ?
Please help i am also facing the same issue
