### ISSUE TITLE
[FluxStore Woo only] - Variants now showing, Can't give and see review

### ISSUE THREAD

**Issue by Coinizy1** [inspireui/support#1977]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
On FluxStore 1.6.0 i was able to give and see review after a person of yours come to my team viewer and repaired it for me. 
Also, i was able to see the variants on the app's product page now i am not able to see the variants i dont know why nothing is changed on the website i am trying 1.6.3 FluxStore Woo version.

2. Screenshots issues:
See i cannot give review and no variant is showing whereas both products have variants on website:
![Screenshot_20200131-232600](https://user-images.githubusercontent.com/31903098/73564444-6093f280-4481-11ea-9133-6d9d02f95994.jpg)
![Screenshot_20200131-232709](https://user-images.githubusercontent.com/31903098/73564446-612c8900-4481-11ea-96b0-52005bc9c871.jpg)
![Screenshot_20200131-232615](https://user-images.githubusercontent.com/31903098/73564447-612c8900-4481-11ea-8691-a12aee828955.jpg)

3. Proof of my purchased:
![Screenshot_5](https://user-images.githubusercontent.com/31903098/73564210-e3687d80-4480-11ea-92dc-ffb0230817dd.png)

3. Config files (optional)

**Comment by inspireui-support** [comment]
@Coinizy1 - as we could not see your username on Codecayon, could you help to post the comment from https://codecanyon.net/item/fluxstore-woocommerce-flutter-ecommerce-full-app/24050041 - than  you!

**Comment by Coinizy1** [comment]
![image](https://user-images.githubusercontent.com/31903098/73590778-3a656580-4508-11ea-8caa-e9be2eceee1f.png)
Done please help me my app is in production.

**Comment by inspireui-support** [comment]
Thank you, it's verified - could you help to zip the common folder so that we could check and reproduce the issue from our side - thank you!

**Comment by minhtruong315** [comment]
@Coinizy1 can u download the latest version 1.6.3 then check again

**Comment by Coinizy1** [comment]
I already have version 1.6.3 installed. i am sending the full source code
without build folder also my wordpress admin panel please share an email.
thanks

**Comment by Coinizy1** [comment]
Also, tell me which is the best wordpress theme you suggest for this app. like if there is any specific theme you guys have tested it on and build it.
thanks my app is in production please help fast.
thanks

**Comment by minhtruong315** [comment]
@Coinizy1 pls send full source code and admin account via my email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/1977

**Comment by Coinizy1** [comment]
Please check your email.
Thanks

**Comment by minhtruong315** [comment]
@Coinizy1 Replace file screens/detail/review.dart to fix review
https://tppr.me/FqXKx
[review.dart.zip](https://github.com/inspireui/support/files/4163176/review.dart.zip)

**Comment by minhtruong315** [comment]
You need to enable this to show variants https://tppr.me/fsHDF
https://tppr.me/qkqHk
