### ISSUE TITLE
Fluxstore Multi Vendor - Flutter E-commerce Full App || Stores Not Showing || Shipping Gives Error

### ISSUE THREAD

**Issue by SHAIKH-SOHARAB** [inspireui/support#1978]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
 i)   Stores not showing. Shows Error
ii)   Shipping Gives Error.

2. Screenshots issues:
![Stores Not Showing](https://user-images.githubusercontent.com/58981673/73587990-f0b95280-44e8-11ea-91d0-21bddee33bf0.jpeg)
![Shipping Error](https://user-images.githubusercontent.com/58981673/73587991-f0b95280-44e8-11ea-9b98-9c4f938b4cba.jpeg)

3. Proof of my purchased:
![Fluxstore Multi Vendor Bought](https://user-images.githubusercontent.com/58981673/73587984-d67f7480-44e8-11ea-82ff-2ffd42d87944.png)

3. Config files (optional)

**Comment by minhtruong315** [comment]
@SHAIKH-SOHARAB can u send me config file?

**Comment by SHAIKH-SOHARAB** [comment]
[config.zip](https://github.com/inspireui/support/files/4146458/config.zip)

**Comment by minhtruong315** [comment]
@SHAIKH-SOHARAB You updated wrong serverConfig in config.dart
```
const serverConfig = {
  "type": "woo",
  "url": "https://www.sanztar.com",
  "consumerKey": "ck_e3bc74795cd3815baf5326deba6d32d6b21bdabe",
  "consumerSecret": "cs_0b36529ad5f8e399dc8a2f3056fa2d48bcdc0557",
  "blog": "https://www.sanztar.com",
  "forgetPassword": "https://www.sanztar.com/wp-login.php?action=lostpassword"
};
```
You're using Fluxstore MV, it only supports type: dokan or wcfm

**Comment by SHAIKH-SOHARAB** [comment]
okay .,I have changed the type to "wcfm" also added username/password mentioned in your common/example/WCFM.
I am getting blank screen after running app, its not showing any error while compiling.

**Comment by minhtruong315** [comment]
@SHAIKH-SOHARAB are you using Fluxstore MV version 1.6.3?

**Comment by SHAIKH-SOHARAB** [comment]
Yes.

**Comment by SHAIKH-SOHARAB** [comment]
What is the status?
Do you need something?
I don't understand the issue.
How to solve the problem?

**Comment by minhtruong315** [comment]
@SHAIKH-SOHARAB Add my akype: minhtruong315
I'll help u check it

**Comment by SHAIKH-SOHARAB** [comment]
I have added you.
Please accept the invitation.

**Comment by minhtruong315** [comment]
I don't see you. pls ping me on the skype

**Comment by SHAIKH-SOHARAB** [comment]
I have already ping you

**Comment by minhtruong315** [comment]
what is your skype?

**Comment by SHAIKH-SOHARAB** [comment]
ssoharab147@outlook.com

**Comment by minhtruong315** [comment]
I messaged you on the skype. please accept
