### ISSUE TITLE
Fluxstore Pro-Flutter E-commerce Full App.. Unable to install dependancies in Android studio

### ISSUE THREAD

**Issue by oskaa** [inspireui/support#1982]

**Comment by oskaa** [comment]
After importing source into the android studio, i hit get dependencies but after it comes back with error 0 and also the file pubspec.yaml gets locked.
![Screen Shot 2020-02-02 at 3 47 57 AM](https://user-images.githubusercontent.com/6002320/73600819-4f291400-456f-11ea-8b1f-af5feccfcda3.png)

**Comment by oskaa** [comment]
![Screen Shot 2020-02-02 at 4 27 33 AM](https://user-images.githubusercontent.com/6002320/73601148-a6ca7e00-4575-11ea-9e2b-9ef651fdcb04.png)
Flutter is installed and working fine on my laptop.

**Comment by oskaa** [comment]
![Screen Shot 2020-02-02 at 4 33 36 AM](https://user-images.githubusercontent.com/6002320/73601157-c497e300-4575-11ea-9dad-072abd1df3de.png)
this is before i ran Get dependencies

**Comment by oskaa** [comment]
![Screen Shot 2020-02-02 at 4 36 26 AM](https://user-images.githubusercontent.com/6002320/73601164-e09b8480-4575-11ea-8385-76e97f50ef48.png)
 After running Get dependencies

**Comment by michaelbrinkworth** [comment]
did you go to preferences and set a flutter path?

**Comment by inspireui-support** [comment]
@oskaa pls try to use this script to reset to channel stable:
```
flutter channel stable
flutter update --force
flutter packages get
```

Then restart the Android Studio to run the project again

**Comment by oskaa** [comment]
> @oskaa pls try to use this script to reset to channel stable:
> 
> ```
> flutter channel stable
> flutter update --force
> flutter packages get
> ```
> 
> Then restart the Android Studio to run the project again
![Screen Shot 2020-02-02 at 10 13 18 PM](https://user-images.githubusercontent.com/6002320/73614410-37599a80-4618-11ea-99f9-4afca0079e5a.png)

After following the above instructions this is what i get

**Comment by inspireui-support** [comment]
@oskaa - try to run "flutter clean"  - select the simulator and press the Play green button - thank you!
