### ISSUE TITLE
Flux store profile update 

### ISSUE THREAD

**Issue by raiedahmed** [inspireui/support#1983]
![D213E9CF-CF5D-42A7-B5B8-42ACC5175713](https://user-images.githubusercontent.com/41026234/73602387-1c394d00-457c-11ea-83cd-ab2da525a659.png)
![25D07F54-908D-4B78-A5F7-9E9BFF84AD99](https://user-images.githubusercontent.com/41026234/73602388-1c394d00-457c-11ea-9295-f81d9b847604.png)
![9FB34685-84B8-4AE1-A4A2-B2DDCEF0771C](https://user-images.githubusercontent.com/41026234/73602406-4985fb00-457c-11ea-9a93-99606872d4ce.png)

**Comment by Senior-Gamal** [comment]
hello @raiedahmed  Did you solve the login problem from apple ?
If you solve the problem, please send your number or email to contact you

**Comment by altawfer** [comment]
facebook.com/raiedelghoul

**Comment by raiedahmed** [comment]
How fix the problem

**Comment by raiedahmed** [comment]
![E9C1828F-D155-4F81-9A06-F466613552E0](https://user-images.githubusercontent.com/41026234/73608198-8bd52980-45c8-11ea-99a4-91649635323f.jpeg)

**Comment by Senior-Gamal** [comment]
@raiedahmed please check the other message in fb

**Comment by minhtruong315** [comment]
@raiedahmed download the latest version 1.6.3 in codecanyon. Then update MStore Api plugin. 
Replace screens/user_update.dart file like this
[user_update.dart.zip](https://github.com/inspireui/support/files/4145757/user_update.dart.zip)
