### ISSUE TITLE
MStore Multi Vendor - Complete React Native template for WooCommerce] -  Error building app using Expo & Wizard

### ISSUE THREAD

**Issue by afrojuju** [inspireui/support#1984]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:

2. Screenshots issues:

3. Proof of my purchased:

3. Config files (optional)

-------------

Hello,

I am having an issue with using expo and your wizard. after setting up app when I run app I get a blank screen with the following error message.

Unable to resolve module `react-native-screens` from `/Users/username/Downloads/mstore-multi-vendor-v1.3.2 2/mishuri-expo/node_modules/react-navigation-tabs/src/navigators/createBottomTabNavigator.js`: Module `react-native-screens` does not exist in the Haste module map

This might be related to https://github.com/facebook/react-native/issues/4968 To resolve try the following: 
1. Clear watchman watches: `watchman watch-del-all`. 
2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`. 
3. Reset Metro Bundler cache: `rm rf /tmp/metro-bundler-cache` or `npm start——reset-cache`. 
4. Remove haste cache: `rm rf /tmp/haste-map-react-native-packager`. 
Packager URL http://127.0.0.1:19001/node_modules/expo/AppEntry.bundle?dev=false&minify=true&hot=false&platform=ios returned unexpected code 500. Please open your project in the Expo app and see if there are any errors. Also scroll up and make sure there were no errors or warnings when opening your project.

Purchase Proof
Item Purchase Code:
b6d2e01d-d70f-4309-9936-7971df9ed3a6

Attached config files

Thanks 
[common.zip](https://github.com/inspireui/support/files/4143649/common.zip)

**Comment by inspireui-support** [comment]
verified purchased - https://tppr.me/codNw

@luyx2412  - please help for a suggestion

**Comment by luyx2412** [comment]
Hi @afrojuju Can you send your project via luyxtran264@gmail.com?

Thanks
