### ISSUE TITLE
[Fluxstore] - Products images not appear

### ISSUE THREAD

**Issue by limitlessfirm** [inspireui/support#1986]
![Products images not appear-001](https://user-images.githubusercontent.com/59250639/73611710-3e1ee800-45ed-11ea-832e-e55e830c543f.JPG)
![screenshot](https://user-images.githubusercontent.com/59250639/73611711-3e1ee800-45ed-11ea-9810-551bf908a431.JPG)

> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: Products images not appear

2. Screenshots issues: https://ibb.co/NsWxf9k

3. Proof of my purchased: https://ibb.co/R4ymJhS

3. Config files (optional)

**Comment by minhtruong315** [comment]
@limitlessfirm Did u install this plugin?
https://wordpress.org/plugins/regenerate-thumbnails/

**Comment by limitlessfirm** [comment]
Yes, i installed (Regenerate Thumbnails) but the images for products still not appear
and i see this message in android studio (I/flutter ( 4692): Exception: Could not instantiate image codec.)

**Comment by minhtruong315** [comment]
can u send me config files and admin account via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/1986

**Comment by minhtruong315** [comment]
supported

**Comment by thimiradulakshitha** [comment]
I have got the same issue. how can I solve this?

**Comment by mansoor88** [comment]
facing same issue. Need support in this matter.

**Comment by brygom** [comment]
Same issue! please let me know-how i can fix it! plis!

**Comment by mansoor88** [comment]
> Same issue! please let me know-how i can fix it! plis!

install the regenerate thumbnail plugin and do regenerate all. They will start showing.

**Comment by limitlessfirm** [comment]
Thanks

**Comment by scarymob** [comment]
I'm experiencing the same. I downloaded the regenerate images plugin and ran it, no luck.

**Comment by brygom** [comment]
Hello @scarymob , this works for me: https://github.com/inspireui/support/issues/3710#event-3451532542
