### ISSUE TITLE
[Fluxstore Listing] - 

### ISSUE THREAD

**Issue by Bingo2000** [inspireui/support#1987]
Installed the latest update and could successfully connect to myListing installation
But when trying to open a listing I get the errors shown in the screenshot:
![error](https://user-images.githubusercontent.com/13098762/73612995-66104a80-45f1-11ea-8fc5-052ff9628041.jpg)
![BingoEnvato](https://user-images.githubusercontent.com/13098762/73613000-6dcfef00-45f1-11ea-99a9-303bec8f23a7.jpg)

**Comment by inspireui-support** [comment]
could you share your common folder so that we could help for checking

**Comment by Bingo2000** [comment]
You will find the common folder attached. Have two separate (Android, Ios) Google Map API, but have overridden (with xxxxxx) them in attached file.
[common.zip](https://github.com/inspireui/support/files/4146834/common.zip)

**Comment by Bingo2000** [comment]
Hi Guys,

you should be more carefully. I found two bugs:
First
in: lib/example/mylisting/config.dart
Path is wrong:
`import '**../../**common/constants.dart';`

must be:
`import '**../**common/constants.dart';`

**AND**
lib/example/mylisting/config.dart
 `"rating": "listing_data.**listeo**-avg-rating", 

is wrong for MyListing. Therefore opening a listing view with MyListing hangs.
I have outcommented this and listing view works.

Please give me the right string association for MyListing Ratings.

Hope, i could help you with this a little bit!!!

**Comment by Bingo2000** [comment]
[Fluxstore Listing] - No Map shown with my Listing 

https://user-images.githubusercontent.com/13098762/73613256-12ebc700-45f4-11ea-8d2e-fe9b138a679b.jpg

```
flutter: err when parsed json MyListing type 'List<dynamic>' is not a subtype of type 'Map<dynamic, dynamic>'
flutter: err at getProductRecents func NoSuchMethodError: The getter 'iterator' was called on null.
Receiver: null
Tried calling: iterator
flutter: NoSuchMethodError: The getter 'iterator' was called on null.
Receiver: null
Tried calling: iterator
```

**Comment by Bingo2000** [comment]
MyListing listing single view only works. with `"layout": kProductLayout.listingFullSizeImageType,`
and out commented:
``"rating": "listing_data.listeo-avg-rating",`
but does not work with:
`"layout": kProductLayout.listingHalfSizeImageType`

Further bug is in `lib/example/mylisting/config.dart`:

`"lng": "listing_data.geolocation_lng",`
must be for MyListing:
`"lng": "listing_data.geolocation_long",`

**Comment by Bingo2000** [comment]
Question:
Found this in lib/screens/detail/listing/product_map.dart
`var googleMapsApiKey = 'XXXXXXXX';

    var mapURL = new Uri(
        scheme: 'https',
        host: 'maps.googleapis.com',
        port: 443,
        path: '/maps/api/staticmap',
        queryParameters: {
          'size': '800x600',
          'center':
              '${defaultLocation['latitude']},${defaultLocation['longitude']}',
          'zoom': '13',
          'maptype': 'roadmap',
          'markers':
              'color:red|label:C|${widget.product.listing.lat},${widget.product.listing.long}',
          'key': '$googleMapsApiKey'
        });`

What is this for?

**Comment by Bingo2000** [comment]
Added this to config.json:

`{ "name": { "de": "Blog" }, "layout": "blog" },`

Result:

![blog_error](https://user-images.githubusercontent.com/13098762/73662989-0b342d00-469d-11ea-8d25-41982b9a0215.jpg)

**Comment by Bingo2000** [comment]
Where can I change then drawer Icon?

![drawer_icon](https://user-images.githubusercontent.com/13098762/73731254-74b54980-4738-11ea-8d04-552f3d7a1b35.jpg)

**Comment by Bingo2000** [comment]
Map Listing does not work:

`flutter: err when parsed json MyListing type 'List<dynamic>' is not a subtype of type 'Map<dynamic, dynamic>'
flutter: err at getProductRecents func NoSuchMethodError: The getter 'iterator' was called on null.
Receiver: null
Tried calling: iterator
flutter: err when parsed json MyListing type 'List<dynamic>' is not a subtype of type 'Map<dynamic, dynamic>'
flutter: err at getProductRecents func NoSuchMethodError: The getter 'iterator' was called on null.
Receiver: null
Tried calling: iterator
flutter: NoSuchMethodError: The getter 'iterator' was called on null.
Receiver: null
Tried calling: iterator
flutter: err when parsed json MyListing type 'List<dynamic>' is not a subtype of type 'Map<dynamic, dynamic>'
flutter: err at getProductRecents func NoSuchMethodError: The getter 'iterator' was called on null.
Receiver: null
Tried calling: iterator`

**Comment by Bingo2000** [comment]
For your information:
listinghalfSizeImageType does not work with:

` ProductRelated(
                        product: widget.product,
                      ), ` 
![error](https://user-images.githubusercontent.com/13098762/73737423-e7c3bd80-4742-11ea-811f-6bd6a6a1e470.jpg)

out commented it works:

![no_error](https://user-images.githubusercontent.com/13098762/73737523-16419880-4743-11ea-9cb8-91d8ed750f89.jpg)

**Comment by Bingo2000** [comment]
Adress rendered twice:

![twice](https://user-images.githubusercontent.com/13098762/73737761-89e3a580-4743-11ea-9b33-22a07936fb58.jpg)

**Comment by Bingo2000** [comment]
No Map rendered:


<img width="271" alt="Bildschirmfoto 2020-02-04 um 11 41 04" src="https://user-images.githubusercontent.com/13098762/73737956-d333f500-4743-11ea-86d9-7bcf5344a921.png">

**Comment by Bingo2000** [comment]
Solved Doubbled adress entry with deleting:

` if (isNotBlank(product.listing.location)) {
      list.add(InfoItem(
        icon: Icons.location_on,
        title: product.listing.location,
      ));
    }`

in
lib/screens/detail/listing/product_title_short.dart

**Comment by youngtet** [comment]
hello i'm having issues with the same product, i'm getting an error when viewing the categories section... do you know how to solve this?
![Screenshot_1580725091](https://user-images.githubusercontent.com/60430933/73773912-5f2f2800-4716-11ea-982b-2392fefb014d.png)

**Comment by danimmg** [comment]
> 
> 
> Installed the latest update and could successfully connect to myListing installation
> But when trying to open a listing I get the errors shown in the screenshot:
> ![error](https://user-images.githubusercontent.com/13098762/73612995-66104a80-45f1-11ea-8fc5-052ff9628041.jpg)
> ![BingoEnvato](https://user-images.githubusercontent.com/13098762/73613000-6dcfef00-45f1-11ea-99a9-303bec8f23a7.jpg)

Hello
Bingo I am having enormous difficulties with the mylisting template in some aspects I am making progress but in others I am lost, how about we exchange experiences to solve the errors, because the InspireUI support is falling short

My email:
daniel_mgarcia@hotmail.com

**Comment by philipvu30** [comment]
Hi @danimmg ,

It seems you have not created consumer key and consumer secret. Please refer to this [DOC](https://docs.woocommerce.com/document/woocommerce-rest-api/) to get those.

If you don't mind, I also need access to your site for further modification. Please make a support account and send it privately to this email: toan@inspireui.com

For further assistance, please contact me through Skype: vuthanhtoan30@gmail.com

**Comment by Bingo2000** [comment]
Hi you have to out comment/delete entry of
lib/example/mylisting/config.dart:
"rating": "listing_data.*listeo*-avg-rating", in line 224

As you see the this is a reference to Listeo template.

you should use the instead:

"rating": "listing_data._case27_average_rating",


Am Di., 4. Feb. 2020 um 19:21 Uhr schrieb youngtet <notifications@github.com

**Comment by philipvu30** [comment]
Have you solved your issue yet? @Bingo2000

**Comment by Bingo2000** [comment]
Hi created Wocommerce - Key and secret adde those to config.dart, but none of the issues were cleared.

**Comment by philipvu30** [comment]
Hi @Bingo2000 ,

Would you mind if I ask for a support account for your website? Please send it privately to this email: toan@inspireui.com so I can help you asap. I need to make sure everything is correct and please include your common folder in the email. Thank you for your understanding.

**Comment by philipvu30** [comment]
Hi @Bingo2000 ,
I already sent you the solution and instruction through mail. Please check and give me a confirmation if it works. Thank you

**Comment by Bingo2000** [comment]
Got error with Androi simulator:

```
FlutterError (setState() called after dispose(): _BlogListState#d5377(lifecycle state: defunct, not mounted)
This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().)
```
![Bildschirmfoto 2020-02-21 um 13 24 57](https://user-images.githubusercontent.com/13098762/75034526-aacf2900-54ad-11ea-8154-a95977482486.jpg)

**Comment by Bingo2000** [comment]
Facebook Login error on android. Works with iOs.
![Bildschirmfoto 2020-02-21 um 13 29 03](https://user-images.githubusercontent.com/13098762/75034790-4496d600-54ae-11ea-9385-4583d8dcf1f6.jpg)

**Comment by Bingo2000** [comment]
Default font is shown in iOs-App, but not with android:
 ```
- family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat-600.ttf
        - asset: assets/fonts/montserrat-500.ttf
        - asset: assets/fonts/montserrat-400.ttf
        - asset: assets/fonts/montserrat-300.ttf
        - asset: assets/fonts/montserrat-200.ttf
```
