### ISSUE TITLE
[Fluxstore Listing] - No Map shown with my Listing

### ISSUE THREAD

**Issue by Bingo2000** [inspireui/support#1988]
![map_error](https://user-images.githubusercontent.com/13098762/73613256-12ebc700-45f4-11ea-8d2e-fe9b138a679b.jpg)

```
lfutter: err when parsed json MyListing type 'List<dynamic>' is not a subtype of type 'Map<dynamic, dynamic>'
flutter: err at getProductRecents func NoSuchMethodError: The getter 'iterator' was called on null.
Receiver: null
Tried calling: iterator
flutter: NoSuchMethodError: The getter 'iterator' was called on null.
Receiver: null
Tried calling: iterator
```

**Comment by inspireui-support** [comment]
First, pls create one ticket for your all issues, and share your common folder so that we could help for checking, move to #1987

**Comment by Bingo2000** [comment]
Added this to config.json:

`{
      "name": {
        "de": "Blog"
      },
      "layout": "blog"
    },`

Result:

![blog_error](https://user-images.githubusercontent.com/13098762/73662908-e8a21400-469c-11ea-9355-1ecc26d80715.jpg)

**Comment by youngtet** [comment]
@Bingo2000 did you manage to solve this?
