### ISSUE TITLE
[MStore Pro] - How can i add Drop-down list

### ISSUE THREAD

**Issue by MohammedXAbdo** [inspireui/support#1989]
i need to add Drop-down list in custom filed ( state ) i  need to make customer chose one of Drop-down list sate in address bill by using woo custom filed   in my WordPress site 
![Screen Shot 2020-02-02 at 10 13 37 PM](https://user-images.githubusercontent.com/24995995/73614651-cd39f900-4609-11ea-8d77-e60a60ff8f09.png)

**Comment by inspireui-support** [comment]
@MohammedXAbdo - thank you for the questions, we are not sure the solution for this feature, but we will investigate and could add this on later release - marked and 'feature request'

**Comment by minhcasi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Load Dynamic State](https://trello.com/c/zDG0rtCw/20-load-dynamic-state)
