### ISSUE TITLE
[Fluxnews] - Latest Update 1.2.2

### ISSUE THREAD

**Issue by aldoyh** [inspireui/support#1990]
The latest update 1.2.2 looks awesome! But may I get the exact changes?
Because I've done lots of customization and trying to avoid repetition. 

Thank you.

**Comment by aldoyh** [comment]
Also, in Android, do we allow the Gradle update to 3.5.3 and the dependencies to the latest version?

**Comment by inspireui-support** [comment]
Hi, you can request our GitLab to get the detail file changed and compare with the previous version - https://docs.google.com/forms/d/e/1FAIpQLSeuBqUkScy42V7KKhfNPj0fl581anrB1mWkbMa3p2WQt7fhfw/viewform 

Yes, we recommend to update to compatible with the latest flutter version - thank you!
