### ISSUE TITLE
MStore Pro - Complete React Native template for e-commerce

### ISSUE THREAD

**Issue by johnnyvanrensburg** [inspireui/support#1991]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: keep getting this error if I run cmd expo strat" Some of your project's dependencies are not compatible with currently installed expo package version:
 - react-native-webview - expected version range: 7.4.3 - actual version installed: 8.0.1
Your project may not work correctly until you install the correct versions of the packages"
To install the correct versions of these packages, please run: expo install [package-name ...] I have tried for 16 hours to try and resolve this but have been failing over and over. I am feeling so tired. Thought that this would be easy. It's been a nightmare. I just need help please. 

2. Screenshots issues:

3. Proof of my purchased:
![Screenshot_20200203-032850_Gmail](https://user-images.githubusercontent.com/60583426/73619293-70ecce80-4635-11ea-8ab9-21b7d6e4b902.jpg)

Date: 23 Jan 2020
Invoice No: IVIP36183549
Order No: 119262442

3. Config files (optional)

**Comment by johnnyvanrensburg** [comment]
Still no support 13 hours later

**Comment by luyx2412** [comment]
Hi @johnnyvanrensburg 
Sorry about reply you late. You can remove the `react-native-webview` library and follow the expo document to add new library. https://docs.expo.io/versions/latest/sdk/webview/

Thanks

**Comment by johnnyvanrensburg** [comment]
I am very new at this. Bit more explanation. I am a fast learner

**Comment by johnnyvanrensburg** [comment]
Problem solved. That you. Will let you know if I need any other help
