### ISSUE TITLE
Fluxstore listing issue

### ISSUE THREAD

**Issue by michaelbrinkworth** [inspireui/support#1992]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:

2. Screenshots issues:

3. Proof of my purchased:

3. Config files (optional)

![Screen Shot 2020-02-03 at 9 03 39 am](https://user-images.githubusercontent.com/55236695/73619817-97812880-467a-11ea-9a4c-671e045824f7.png)

**Comment by inspireui-support** [comment]
Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads  it's used to verify your proof of purchase? sorry for any inconvenience - Thank you!

**Comment by michaelbrinkworth** [comment]
https://github.com/inspireui/support/issues/1981

**Comment by michaelbrinkworth** [comment]
did you get my message?

**Comment by inspireui-support** [comment]
we got it - thank you!

Could you zip the common folder and share us for investigating - thanks

**Comment by michaelbrinkworth** [comment]
[common copy.zip](https://github.com/inspireui/support/files/4151422/common.copy.zip)

**Comment by michaelbrinkworth** [comment]
![Screen Shot 2020-02-04 at 2 58 30 pm](https://user-images.githubusercontent.com/55236695/73715217-f1f3b500-475e-11ea-97e8-7a81f42b0d5b.png)


Why is there so many bugs in the code?

**Comment by michaelbrinkworth** [comment]
hi minh

**Comment by michaelbrinkworth** [comment]
?

**Comment by michaelbrinkworth** [comment]
@minhtruong315

**Comment by michaelbrinkworth** [comment]
Hello

**Comment by minhtruong315** [comment]
@michaelbrinkworth add my skype: minhtruong315
I'll help u check issues

**Comment by minhtruong315** [comment]
I messaged you on the skype. Please reply

**Comment by michaelbrinkworth** [comment]
<img width="320" alt="Screen Shot 2020-06-06 at 7 35 20 am" src="https://user-images.githubusercontent.com/55236695/83927075-17f19a80-a7cf-11ea-9281-95542447309f.png">


How to solve this
