### ISSUE TITLE
[Fluxstore-MV] - NoSuchMethodError was thrown building ExtendedImage

### ISSUE THREAD

**Issue by saifmuhtar** [inspireui/support#1993]
1. My issue:

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building ExtendedImage(dirty, dependencies: [_LocalizationsScope-[GlobalKey#40819], Directionality, MediaQuery], state: _ExtendedImageState#687d5(stream: ImageStream#6d7b2(MultiFrameImageStreamCompleter#a591d, unresolved, 1 listener), pixels: null)):
The method '*' was called on null.
Receiver: null
Tried calling: *(1.2)

The relevant error-causing widget was: 
  ExtendedImage file:///Volumes/StudioSSD/Project/mjfatonah/mjfatonah-1.6.3/lib/common/tools.dart:129:26
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      Tools.image.<anonymous closure> (package:fstore/common/tools.dart:154:72)
#2      _ExtendedImageState.build (package:extended_image/src/extended_image.dart:823:24)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4334:27)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4223:15)

2. Screenshots issues:

![Screenshot_1580698101](https://user-images.githubusercontent.com/34681804/73621918-e1fea700-4672-11ea-8cc6-1d8c7f8f889b.png)

3. Proof of my purchased:

![72332982-fc89d400-36f5-11ea-9307-f8c418404111](https://user-images.githubusercontent.com/34681804/73621971-14100900-4673-11ea-9986-1b070aeba0ab.jpg)

Please contact me via Skype saifmuhtar@gmail.com

**Comment by minhtruong315** [comment]
replace this file screens/stores.dart to fix
[stores.dart.zip](https://github.com/inspireui/support/files/4146361/stores.dart.zip)

**Comment by saifmuhtar** [comment]
@minhtruong315 Thank you for your fast support.
