### ISSUE TITLE
[FLUXSTORE MV] - Can't open App after Upload config.json to website now.sh

### ISSUE THREAD

**Issue by antixirus** [inspireui/support#1994]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
I can't open my app after im upload my config to now.sh. im follow the tutorial App Performance to use Dynamic Loading. https://docs.inspireui.com/fluxstore/performance/
2. Screenshots issues:
![gambar](https://user-images.githubusercontent.com/57300649/73623208-bf6a8f00-466e-11ea-9928-78238e1135bd.png)
 
![gambar](https://user-images.githubusercontent.com/57300649/73623220-cabdba80-466e-11ea-88df-262bb005b3f9.png)

3. Proof of my purchased:
![gambar](https://user-images.githubusercontent.com/57300649/73623313-1b351800-466f-11ea-8894-36f0e7f7f97d.png)

3. Config files (optional)
{
  "Background": {
    "height": 0.3,
    "color": "#fbb110",
    "image": "https://sangkek.co.id/wp-content/uploads/2020/01/FLASH-BANNER.jpg"
  },
  "HorizonLayout": [
    {
      "layout": "logo",
      "hideLogo": true
    },
    {
      "layout": "header_text",
      "fontSize": 23.0,
      "height": 0.10,
      "padding": 10.0,
      "rotate": [
        ""
      ],
      "type": "fade"
    },
    {
      "layout": "header_search",
      "text": "Lagi butuh apa hari ini?"
    },
    {
      "layout": "bannerImage",
      "isSlider": true,
      "autoPlay": true,
      "showNumber": false,
      "design": "default",
      "showBackGround": true,
      "radius": 2.0,
      "height": 0.15,
      "items": [
        {
          "category": 81,
          "image": "https://sangkek.co.id/wp-content/uploads/2020/01/GRATIS-ONGKIR1.jpg",
          "padding": 15.0
        },
        {
          "category": 81,
          "image": "https://sangkek.co.id/wp-content/uploads/2020/01/FLASH-SALE.png",
          "padding": 15.0
        },
        {
          "category": 60,
          "image": "https://sangkek.co.id/wp-content/uploads/2020/01/FLASH-SALE-CABE.jpg",
          "padding": 15.0
        },
        {
          "category": 82,
          "image": "https://sangkek.co.id/wp-content/uploads/2020/01/RESERVASI.png",
          "padding": 15.0
        },
        {
          "category": 77,
          "image": "https://sangkek.co.id/wp-content/uploads/2020/01/ROTI-GEDANG.jpg",
          "padding": 15.0
        },
        {
          "category": 110,
          "image": "https://sangkek.co.id/wp-content/uploads/2020/01/MAKAN-SIANG.jpg",
          "padding": 15.0
        }
      ]
    },
    {
      "layout": "category",
      "type": "icon",
      "wrap": true,
      "size": 1.2,
      "radius": 50.0,
      "noBackground": true,
      "columns": 4,
      "padding": 10.0,
      "items": [
        {
          "category": 52,
          "image": "https://sangkek.co.id/wp-content/uploads/2020/01/cate11.png",
          "colors": [
            "#3CC2BF",
            "#3CC2BF"
          ],
          "originalColor": true
        },
        {
          "category": 79,
          "image": "https://sangkek.co.id/wp-content/uploads/2020/01/cate22.png",
          "colors": [
            "#3E6AB5",
            "#3E6AB5"
          ],
          "originalColor": true
        },
        {
          "category": 56,
          "image": "https://sangkek.co.id/wp-content/uploads/2020/01/cate33.png",
          "colors": [
            "#53A2CC",
            "#53A2CC"
          ],
          "originalColor": true
        },
        {
          "category": 57,
          "image": "https://sangkek.co.id/wp-content/uploads/2020/01/cate44.png",
          "colors": [
            "#53688A",
            "#53688A"
          ],
          "originalColor": true
        },
        {
          "category": 77,
          "image": "https://sangkek.co.id/wp-content/uploads/2020/01/cate55.png",
          "colors": [
            "#53688A",
            "#53688A"
          ],
          "originalColor": true
        },
        {
          "category": 82,
          "image": "https://sangkek.co.id/wp-content/uploads/2020/01/cate99.png",
          "colors": [
            "#53688A",
            "#53688A"
          ],
          "originalColor": true
        },
        {
          "category": 57,
          "image": "https://sangkek.co.id/wp-content/uploads/2020/02/oppo.png",
          "colors": [
            "#53688A",
            "#53688A"
          ],
          "originalColor": true
        },
        {
          "category": 57,
          "image": "https://sangkek.co.id/wp-content/uploads/2020/02/samsung1.png",
          "colors": [
            "#53688A",
            "#53688A"
          ],
          "originalColor": true
        }
      ]
    },
    {
      "name": "Terakhir dilihat",
      "layout": "recentView"
    },
    {
      "name": "Promo Bulan Ini",
      "image": "",
      "layout": "threeColumn",
      "isSnapping": true,
      "category": 85
    },
    {
      "name": "Makan cuma 10rb",
      "image": "",
      "layout": "threeColumn",
      "isSnapping": true,
      "category": 110
    },
    {
      "layout": "bannerImage",
      "items": [
        {
          "url": "https://www.instagram.com/sangkek.id/",
          "image": "https://sangkek.co.id/wp-content/uploads/2020/01/Follow-Sangkek.jpg",
          "padding": 5.0
        },
        {
          "url": "https://www.instagram.com/sangkek.id/",
          "image": "https://sangkek.co.id/wp-content/uploads/2020/01/Free-Delivery.jpg",
          "padding": 5.0,
          "featured": true
        }
      ]
    },
    {
      "name": "Blog",
      "layout": "blog"
    }

  ],
  "Setting": {
    "MainColor": "#fbb110",
    "ProductListLayout": "list"
  },
  "TabBar": [
    {
      "layout": "home",
      "icon": "assets/icons/tabs/icon-home.png"
    },
    {
      "layout": "category",
      "categoryLayout": "card",
      "icon": "assets/icons/tabs/icon-category.png"
    },
    {
      "layout": "search",
      "icon": "assets/icons/tabs/icon-search.png"
    },
    {
      "layout": "cart",
      "icon": "assets/icons/tabs/icon-cart2.png"
    },
    {
      "layout": "profile",
      "icon": "assets/icons/tabs/icon-user.png"
    }
  ]
}

**Comment by inspireui-support** [comment]
could you zip your common folder here 

Also, try to run "now" only

**Comment by antixirus** [comment]
@inspireui-support @vumanhsn97 
[common.zip](https://github.com/inspireui/support/files/4151565/common.zip)

**Comment by inspireui-support** [comment]
@antixirus - pls try to use https://surge.sh/ instead of now (the latest version now has some issue and they change the config, we could figure out the problem so far)

Try to run this script
```
npm install --global surge
surge
```

The result will be similar to http://warm-metal.surge.sh/config.json
