### ISSUE TITLE
[fluxstore] - Wallet payment 

### ISSUE THREAD

**Issue by Dhavalkatrodiya** [inspireui/support#1996]
My issue:
 hi, how can i add terawallet payment for purchasing products?

    Screenshots issues:
    https://snipboard.io/LA1fW0.jpg

    Proof of my purchased:
    https://snipboard.io/6EgT7k.jpg

    Config files (optional)

**Comment by inspireui-support** [comment]
Hi, we are not sure with this plugin integration, need do more investigating the API

Update as change request for further improvement - thank you!

**Comment by minhcasi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Wallet Payment](https://trello.com/c/D3VPRw42/21-wallet-payment)

**Comment by themeix** [comment]
That would be great, if you add that feature
