### ISSUE TITLE
[fluxstore - woo] - Feature Request

### ISSUE THREAD

**Issue by sketchuprzr** [inspireui/support#1999]
### 1)
I am requesting a new feature. This is an important and beautiful thing.
For changes to the app;
For the Play store and appstore (ios), 
### "New update is available. Please update the application to run the application"
I request a warning screen feature. A feature that will automatically detect our updates from the firebase or app store & play store and give this warning.

**Comment by sketchuprzr** [comment]
In the "registration" screen;
Details of the "I want to be a member" section are missing. Every shopping site has a "privacy & policy" page. the user has the right to read them.
A redirect is required for this in the "registration" screen. This can be a webview or text screen.

For example;
![image](https://user-images.githubusercontent.com/60021696/73694333-e2398980-46e8-11ea-89cb-a33b266179cf.png)

**Comment by sketchuprzr** [comment]
I request json (**lottie**) animation on the Splash Screen screen.

### For example;
![Untitled Project](https://user-images.githubusercontent.com/60021696/73694936-24af9600-46ea-11ea-992a-66c29a657689.gif)
### Here ;
https://lottiefiles.com/share/ybDCvD

**Comment by sketchuprzr** [comment]
In widgets, we can only do placement by category ID.

For example, we put a widget on the home page and write the category id to it.

I want to add a product id as a link to the slide screen. For example, when the user clicks on the slide on the slide screen, they should go to the page of the product I selected.

**Comment by inspireui-support** [comment]
@sketchuprzr - thank you so much for the request.

1-2-3. will update on next release
4. The Flutter is not supporting well for Lotties, they recommend to use Flare instead, you can get the default example Flare animation from the splash screen and make a similar demo on other screens :)
5. This feature is already supported please check the banner_items.dart
```
url: link to website URL
product: link to product ID
category: link to category ID
tab: link to tab menu
screen: link to screen 
```

**Comment by lancerynearson** [comment]
Is there a way to add the link to tab menu feature to "Fluxstore Listing" not just the store version.

**Comment by sketchuprzr** [comment]
@inspireui-support 
I want to edit the "price" table in the product filtering section.
In this filter;
There is a price option of "100, 200, 300 ... 1000".
I want to change this. for example ;
I want to fix it as "5, 10, 15, 20 .. 100".

![image](https://user-images.githubusercontent.com/60021696/73769837-6e50bd00-478c-11ea-94a3-5d3903baee05.png)

**Comment by sketchuprzr** [comment]
I took a look at 2dimension for flare animation. And I realized that it was a very stupid system.
The interface is disgusting and useless.
I also do not have information about flare. Why are you using a system that nobody knows?
json animations are used worldwide, why did you choose flare animation while a great program like after effect stops? Can your staff not use after effects?
I can say that I am not satisfied in this regard at all. I don't want to use a system I never knew. I want to say once again that "rive.app" is disgusting. Because I did not understand anything from its interface, it is a very stupid system.

**Comment by sketchuprzr** [comment]
@inspireui-support 
I request an update for the "add to cart" button on the product page.

Problem;
When the button is clicked, the product is added to each basket page for each click.
 
Regulatory proposal;
a window should appear when the button is pressed "Added to Cart!" and the button should change.
The changing button should be the following; "Go to the Card"

**Comment by zahmed84** [comment]
@sketchuprzr
I think the popup text i.e. "added to Cart" must be shown when a user click on Add to Cart Button.
But the other option to change the Button to "Go to Cart" is not preferable because the would not be able to change the quantity on single product page unless he goes to Cart Page.

@inspireui-support 
Please fix the error on Cart page as highlighted in issue #2025. This is very important.

**Comment by kvt0012** [comment]
Dear sir, 
Request 1,2 will be updated on the next release 
About request 3, we will ask the other customers whether they need it or not and update it later if they need. 
Request 4 : The version on flutter is not stable on ios device, so we will update it later. 
Thanks for your issue, 
Having a nice day.
