### ISSUE TITLE
Listapp 1.5.1 Not stable and crash

### ISSUE THREAD

**Issue by reconshield** [inspireui/support#2]
Product: Listapp
 Purchase code: 23ee6c94-1eb8-4ffd-842f-7600d97f41d0

**Describe the bug**
1) in  ios when choose date for booking, app crash..i attached screenshot

2) Fb login not working in ios and android

3) Listing in Map view cant scroll .

4) Logout button not working in ios and android

5) Bottom Menu icons, back button not appear in ios simulator. but i cant see when upload app to expo.i have reset simulator but its show same thing.

6) Map view listing cant scroll

7) when choose booking date, app crash in ios and android ( see attachment )

8) chat giving error ( see attachment)

**Screenshots**
![simulator screen shot - iphone x - 2018-11-09 at 13 05 10 1](https://user-images.githubusercontent.com/25501496/48249111-e2d76780-e434-11e8-9547-e1b05840099a.png)
![simulator screen shot - iphone x - 2018-11-09 at 13 11 21](https://user-images.githubusercontent.com/25501496/48249116-e4a12b00-e434-11e8-8a6b-6f6f434322b8.png)

**Comment by minhcasi** [comment]
Fixed on v1.5.2
