### ISSUE TITLE
[mStore Pro Shipping & Stripe Payment issue]

### ISSUE THREAD

**Issue by hammadhassan** [inspireui/support#200]
Product: [MStore]
Purchase Code: f20afe4a-778e-4089-bcb2-7ec1bb4ed49b

I have three issues.

**1st [Shipping Zone]**
I did config my app shipping zone to 2 & also hard coded my Country to Netherlands but on checkout page shipping method is not displaying. 
![shipping](https://user-images.githubusercontent.com/5791268/51496927-66bdb080-1de3-11e9-8e60-13d86c64fe48.PNG)

**2nd [Country List Text not Displaying]**
When i select country list text is not displaying on Android version. May be the text color is white or light grey. Please try to fix this. 
![country list](https://user-images.githubusercontent.com/5791268/51496952-7c32da80-1de3-11e9-8707-fc19006c3160.PNG)

**3 [Cash on Deliver & Stripe Payment Issue]**
When ever i update my config file according to my site. Cash on Delivery icon is not displaying on checkout page + stripe payment is also not displaying now.
It only display to method. 1 is Band Transfer with Stripe Ideal Logo & the second 1 is blank but when i click it display Paypal.
![payment](https://user-images.githubusercontent.com/5791268/51496985-8d7be700-1de3-11e9-9cae-dc900118a13a.PNG)

Please check & guide me to fix this issue ASAP.

Thanks,

Have a great day.

**Comment by luyx2412** [comment]
Hi @hammadhassan Thanks for your feedback

1. You can use the `hideCountryList` in Config.js file, because now you just ship to Netherland. We fixed the issue in new version.
2. Let me check the issue and update in new version.
3. Can you debug with Reactotron or react-native-debugger check the api response? Maybe something was wrong with api.

Thanks

**Comment by hammadhassan** [comment]
Okay. I will check.

But what about the Stripe Payment issue. Cash on Delivery is not displaying on checkout page & Shipping Method is also not displaying.
