### ISSUE TITLE
Fluxstore Problem: Exception caught by widgets library: type 'int' is not a subtype of type 'double'

### ISSUE THREAD

**Issue by habou98** [inspireui/support#2001]
════════ Exception caught by widgets library ═══════════════════════════════
The following assertion was thrown building MainTabs-[LabeledGlobalKey<MainTabsState>#f550c homePageKey](dirty, dependencies: [MediaQuery, _DefaultInheritedProviderScope<AppModel>, _InheritedTheme, _DefaultInheritedProviderScope<CartModel>, _LocalizationsScope-[GlobalKey#08d3f], _FocusMarker], state: MainTabsState#36fec(ticker inactive)):
type 'int' is not a subtype of type 'double'

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  MainTabs-[LabeledGlobalKey<MainTabsState>#f550c homePageKey] file:///C:/Users/AGA-05/Desktop/FluxStore%201.6.3/source/lib/route.dart:92:32
When the exception was thrown, this was the stack: 
#0      MainTabsState.renderTabbar.<anonymous closure> (package:fstore/tabbar.dart:308:39)
#1      List.forEach (dart:core-patch/growable_array.dart:285:8)
#2      MainTabsState.renderTabbar (package:fstore/tabbar.dart:292:13)
#3      MainTabsState.renderBody (package:fstore/tabbar.dart:270:27)
#4      MainTabsState.build (package:fstore/tabbar.dart:176:16)
...
══════════════════════════════════════════════════════════════
![Capture](https://user-images.githubusercontent.com/60615357/73665133-e772e600-46a0-11ea-835e-55b8aeeb0b06.PNG)

**Comment by inspireui-support** [comment]
@habou98 - please try to override this common/tabbar.dart to fix the issue - https://www.dropbox.com/s/ihterp8hiqjk8kk/tabbar.dart?dl=0 - thank you!

**Comment by habou98** [comment]
Thank you for your help.

**Comment by CodeIncognite** [comment]
Same issue Occurs ....Please help to solved out
