### ISSUE TITLE
[FLUXSTORE MV] - Unable to build release APK

### ISSUE THREAD

**Issue by yassiney120** [inspireui/support#2002]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
Unable to build release APK
2. Screenshots issues:
https://ibb.co/9qtK7Jt
3. Proof of my purchased:
https://ibb.co/wYmMMJm

**Comment by minhtruong315** [comment]
https://flutter.dev/docs/deployment/android
did you check this guide?

**Comment by yassiney120** [comment]
Yes

Le mar. 4 févr. 2020 à 07:44, minhtruong315 <notifications@github.com> a
écrit :

**Comment by yassiney120** [comment]
Yes documentation and  video from inspirui

**Comment by yassiney120** [comment]
If you have time can you check my teamviewer

Le mar. 4 févr. 2020 à 09:36, yassine mohdar <mohdarifim1@gmail.com> a
écrit :

**Comment by minhtruong315** [comment]
supported
