### ISSUE TITLE
Fluxstore I don't see gallery images

### ISSUE THREAD

**Issue by csoftech** [inspireui/support#2003]
Hi,

I don't see gallery images & colour options just like in your demo.

I think I would give up on your app right now , may be I will buy it again in future once it is more mature and stable. I noticed you're doing good in support but there is long way to go, keep it up! 

Please suggest how do I ask for refund?

Regards,
Shyam

**Comment by inspireui-support** [comment]
Hi, you can submit here - https://help.market.envato.com/hc/en-us/articles/202821460-Can-I-Get-A-Refund- - thanks

**Comment by csoftech** [comment]
thanks, can please accept refund request?
