### ISSUE TITLE
[fluxstore-listing app] - Error

### ISSUE THREAD

**Issue by bobozd** [inspireui/support#2004]
1. My issue: 

I got this eeror while I'm trying to build the app with latest flux update:

Compiler message:
Error: Invalid package URI 'package:/common/constants.dart':
  Invalid argument (packageUri): Package URIs must not start with a '/': Instance of '_SimpleUri'.
lib/common/config.dart:2:8: Error: Not found: 'package:/common/constants.dart'
import '../../common/constants.dart';
       ^
lib/common/config.dart:93:25: Error: Getter not found: 'kBlogLayout'.
  "DetailedBlogLayout": kBlogLayout.halfSizeImageType,
                        ^^^^^^^^^^^
lib/common/config.dart:124:13: Error: Getter not found: 'kProductLayout'.
  "layout": kProductLayout.listingSimpleType
            ^^^^^^^^^^^^^^
U
nhandled exception:
FileSystemException(uri=org-dartlang-untranslatable-uri:package%3A%2Fcommon%2Fconstants.
dart; message=StandardFileSystem only supports file:* and data:* URIs)
#0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:33:7)
#1      asFileUri (package:vm/kernel_front_end.dart:604:37)
<asynchronous suspension>
#2      writ
eDepfile (package:vm/kernel_front_end.dart:799:21)
<asynchronous suspension>
#3      FrontendCompiler.compile 
(package:frontend_server/frontend_server.dart:472:15)
<asynchronous suspension>
#4      _FlutterFrontendCompiler.compile
 (package:flutter_frontend_server/server.dart:38:22)
#5      starter (package:flutter_frontend_server/se
rver.dart:149:27)
#6      main (file:///C:/b/s/w/ir/cache/builder/src/flutter/
flutter_frontend_server/bin/starter.dart:8:30)
#7      _startIsolate.<anonymo
us closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#8      _RawReceiv
ePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\Studio GRiD\Development\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 780

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\Users\Studio GRiD\Development\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s
Finished with error: Gradle task assembleDebug failed with exit code 1

3. Config files (optional)

[configfiles.zip](https://github.com/inspireui/support/files/4152265/configfiles.zip)

**Comment by inspireui-support** [comment]
@bobozd pls try to edit the common/config.dart to fix the issue (remove the ..) - thanks
```
import '../common/constants.dart';
```

**Comment by bobozd** [comment]
removing ../ solves my first problem.
Now, it runs up but it's not connected to my mylisting site...

![error_1](https://user-images.githubusercontent.com/28021993/73925209-fc808c80-48cd-11ea-8019-a894666476dc.jpg)

**Comment by bobozd** [comment]
EDIT:

I change categoriy numbers related to one from my website and it works no fine without errors.
some questions:

1. I want to change word "No. products" under cateogry title. What file I need to edit?
![question_1](https://user-images.githubusercontent.com/28021993/73926677-47030880-48d0-11ea-852a-a164b3960c9e.jpg)

**Comment by bobozd** [comment]
5. How is possible to edit this part of code so when you click on image it links you to specific url address outside from main templete. My plan is to link to our sponors websites with this part of code

{
      "layout": "bannerImage",
      "isSlider": true,
      "autoPlay": false,
      "showNumber": false,
      "design": "default",
      "showBackGround": true,
      "radius": 10.0,
      "height": 0.5,
      "items": [
        {
          "category": 73,
          "image": "https://trello-attachments.s3.amazonaws.com/5dd3a1ccf77d834e86dfd29a/1100x1292/7beb8a56f7db49bc0e147ec5040deb50/travel2.jpg",
          "padding": 20.0
        },
        {
          "product": 436,
          "image": "https://trello-attachments.s3.amazonaws.com/5dd3a1ccf77d834e86dfd29a/1100x1292/19369c86e6873fc2493da1e397fa6e27/travel3.jpg",
          "padding": 20.0
        },
        {
          "category": 51,
          "image": "https://trello-attachments.s3.amazonaws.com/5dd3a1ccf77d834e86dfd29a/1160x1362/4a1f8758322c3f5dc862c5bf7a9c5af3/travel5.jpg",
          "padding": 20.0
        }
      ]
    },

**Comment by philipvu30** [comment]
Hi @bobozd ,

About your issues, please refer to the instructions below:
1. 
![1](https://user-images.githubusercontent.com/54442328/74005204-b6e5c180-49aa-11ea-82af-bd7e438f6bbd.PNG)
2. 
![2](https://user-images.githubusercontent.com/54442328/74005235-ce24af00-49aa-11ea-98dc-525cfa159b20.PNG)
3. 
![3](https://user-images.githubusercontent.com/54442328/74005242-d41a9000-49aa-11ea-8088-c8806f97e7da.PNG)
4. I have checked and tested your site and did not encounter that problem. It should change the text regarding to your category's title. Did you upgrade to the latest version?
5.
![5](https://user-images.githubusercontent.com/54442328/74005364-265bb100-49ab-11ea-98cd-ceb36d6b6366.PNG)
6. Please refer to this [tutorial](https://www.youtube.com/watch?v=47keBFllFvQ) to install flutter and its plugins on Android Studio. Then connect your phone to your pc/laptop and test it the same way as you did with emulator.

**Comment by bobozd** [comment]
7. Where I can find all possible layout options, to test it all how it looks?
![question_5](https://user-images.githubusercontent.com/28021993/74016268-6f533b80-4992-11ea-9dec-ee836fa477a9.jpg)

**Comment by philipvu30** [comment]
Hi bobozd, 

Would you mind sending me the config.dart and config.json files that you are currently using? Itt would be easier for me  if I have those files. Thank you

**Comment by bobozd** [comment]
send me your email

**Comment by philipvu30** [comment]
@bobozd  toan@inspireui.com

**Comment by bobozd** [comment]
I send you files. please fix asap.

**Comment by philipvu30** [comment]
**7.** Here's the list: twoColumn | threeColumn | fourColumn | recentView | card
**8.** Already fixed. Check your email for the new files (if you leave the price empty, it will not show up)
**9.** Please navigate to lib/common/config.json and add the blog section under Tabbar

![9](https://user-images.githubusercontent.com/54442328/74309196-bd09e280-4d9c-11ea-9643-04e1b87cabc1.PNG)

**10.** 
**For the upper image**: please navigate to lib/widgets/home/header/**header_view**.dart

![10-1](https://user-images.githubusercontent.com/54442328/74309521-7ec0f300-4d9d-11ea-99a8-e98b32ff9eab.PNG)

**For the below image**: please navigate to lib/widgets/home/**product_list_layout**.dart

![10-2](https://user-images.githubusercontent.com/54442328/74309534-8b454b80-4d9d-11ea-8485-53d00cb26f24.PNG)

**11.** Please navigate to lib/app.dart and replace the highlighted term to for example Colors.pink

![11](https://user-images.githubusercontent.com/54442328/74309708-fc84fe80-4d9d-11ea-8d65-c08838d8ca08.PNG)

**12.** Navigate to lib/screens/detail/listing/themes/fullSizeImageType.dart and make changes to these number according to your taste.

![12-1](https://user-images.githubusercontent.com/54442328/74309840-4ec61f80-4d9e-11ea-8c96-eb8d8ce61e86.PNG)
![12-2](https://user-images.githubusercontent.com/54442328/74309847-508fe300-4d9e-11ea-90c5-b5e23fe3e90a.PNG)

**13.** Currently our app does not support it. Maybe we will implement it in the future.
**14.** Could you provide the images exactly where you want to change?
**15.** Currently investigating.

Please note that these are changes according to your taste. If you update the app in the future, you have to make change to these files again. Check your email for the new files. Thank you and have a great day.

**Comment by philipvu30** [comment]
As I have not received any information from you for awhile, I will mark this as closed. Thank you for using our product :)
