### ISSUE TITLE
[MStore ] - Sign-up & login not working

### ISSUE THREAD

**Issue by p156069** [inspireui/support#2005]
> 
---------

1. My issue:

- The users signup and login is not working. I have configured the wordpress according to the app but still it's not working. I have even tried the WP rest api that i have created on POSTMAN its working there, but on APP it's not working.

I am going to attach some screenshot below, for your understanding. 

P.S: I have even tried connecting Facebook APP for the facebook direct login, It is also not working.
Going to attach it's screenshots as well.

2. Screenshots issues:

**path: src/services/WPUSerAPI.js**
https://i.ibb.co/fvGNTRd/Screenshot-2.png

**wordpress rest api**
https://i.ibb.co/8dQ6DVS/Screenshot-3.png

**AppConfig.js**
https://i.ibb.co/4ttZwwd/Screenshot-4.png

**FOR FACEBOOK NOW**
Config.js
https://i.ibb.co/NLJQ4gG/Screenshot-5.png

Facebook App:
https://i.ibb.co/dD11s6p/Screenshot-6.png

3. Proof of my purchased:
https://i.ibb.co/kKLvmyy/Screenshot-1.png
3. Config files (optional)

**Comment by p156069** [comment]
**user can neither signup from Facebook nor from Signup Screen.**

**Comment by luyx2412** [comment]
Hi @p156069 Please change live mode for your facebook and make sure installation facebookhttps://docs.inspireui.com/mstore/facebook-setting/

Thanks

**Comment by p156069** [comment]
Still not working. Even the Signup Screen is also not working.

**Config.js**
https://i.ibb.co/3f5DtkP/Screenshot-1.png

**Facebook App**
https://i.ibb.co/5rTTq6P/Screenshot-3.png

**Comment by tarik-amaterasu** [comment]
i've faced this problem before and i guess the problem is cookieLifeTime causing a problem at wordpress side and it expect a value between 0 and 59 instead of 120..... 

try set cookieLifetime = 59 in src/services/WPUSerAPI.js
i guess it gonna work

**Comment by p156069** [comment]
@luyx2412 @tarik-amaterasu  **NOT WORKING.**  Very Bad Support Experience. Looks like the whole code is depreciated and not updated till date.

Please TELL ME HOW TO FIX THIS PROBLEM. Do you event test your app when you sell it? Im sure NOT!

**Comment by luyx2412** [comment]
Hi @p156069 Please send your AppConfig.json and Config.js via luyxtran264@gmail.com

Thanks

**Comment by p156069** [comment]
Email sent!!! Check Inbox:

https://i.ibb.co/1Z6Mt6T/Screenshot-2.png

**Comment by tarik-amaterasu** [comment]
> @luyx2412 @tarik-amaterasu **NOT WORKING.** Very Bad Support Experience. Looks like the whole code is depreciated and not updated till date.
> 
> Please TELL ME HOW TO FIX THIS PROBLEM. Do you event test your app when you sell it? Im sure NOT!

------------------------------------------------------
Hi, I'm not a support member , 
however, send me next information to this email "ta.amatera@gmail.com" and i will cooperate with you to solve your problem
- src/services/WPUSerAPI.js
- a valid username and password for a customer

**Comment by luyx2412** [comment]
Hi @p156069 Sorry about reply you late. You can zip files and send on github.

Thanks

**Comment by luyx2412** [comment]
Hi @tarik-amaterasu Thanks for your support.

**Comment by youngtet** [comment]
hello @luyx2412 i have same issue on fluxstore listing app... havent gotten any support in a week now..could u please check it out, ticket #1998

**Comment by luyx2412** [comment]
HI @p156069 Sorry about reply you late. Can you describe your error? Because React native and Flutter is different.

Thanks
