### ISSUE TITLE
[fluxstore] -login not work in ipad

### ISSUE THREAD

**Issue by raiedahmed** [inspireui/support#2007]
![C0CC3676-870B-4AA8-849F-B537F0F345B8](https://user-images.githubusercontent.com/41026234/73739998-ff557300-474f-11ea-9732-66268e143693.png)
![C987E171-7F91-4D63-AE1A-AAF515B47AE0](https://user-images.githubusercontent.com/41026234/73739999-ffee0980-474f-11ea-925a-8991e32256cd.png)

**Comment by raiedahmed** [comment]
![2671E7BF-B412-41C5-B8E4-9798FE7DFFBC](https://user-images.githubusercontent.com/41026234/73767719-7acf1880-4780-11ea-8bf0-e091a3f0871c.png)

**Comment by raiedahmed** [comment]
iPad version 
Not login

**Comment by trunghieuvn** [comment]
To fix this problem you need to do the following:

In file `lib/screens/settings.dart`
- Add `bool loggedIn = Provider.of<UserModel>(context).loggedIn;` in the build function.
- Edit function onTap 

```
onTap: () {
    if(loggedIn){
      Provider.of<UserModel>(context, listen: false).logout();
    }else{
      Navigator.pushNamed(context, "/login");
    }
},
```

- Edit title:

```
title: Text(
  loggedIn ? S.of(context).logout : S.of(context).login,  
  style: TextStyle(fontSize: 16),
),
```

![image](https://user-images.githubusercontent.com/19247680/73808443-82370600-4802-11ea-8c38-8f7ff67dbcf2.png)

**Comment by inspireui-support** [comment]
Fixed on next release, pls use the patching as above comment
