### ISSUE TITLE
[fluxstore] -  how to set up stripe payment

### ISSUE THREAD

**Issue by SottoMonte** [inspireui/support#2008]
Hi I tried to search inside config the way to set the stripe payment but I have not found anything, how should I do to make the stripe payment method work?

Code: codecanyon-sLQX6DaF-fluxstore-woocommerce-flutter-ecommerce-full-app

**Comment by inspireui-support** [comment]
Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads  it's used to verify your proof of purchase? sorry for any inconvenience - Thank you!

**Comment by emiliodallatorre** [comment]
+1, I'm also looking for this answer.
It'd be a serious lack of functionality.
