### ISSUE TITLE
[my-listingApp] - sign up login 

### ISSUE THREAD

**Issue by salmaMohamed610** [inspireui/support#2009]
1. My issue:
login ,facebook login and sign up not work 
2. Screenshots issues:
facebook login error
https://imgur.com/gallery/CBw8k0G
sign up 
https://imgur.com/a/V2TL9Eb
login in
https://imgur.com/a/CwxACZm

3. Config files (optional)
{
  "Website": {
    "url": "http://sahlan.xyz/",
    "consumerKey": "ck_1375161dcfe4f036f755dff3147027f2c4ba6af9",
    "consumerSecret": "cs_ff1c646b1fb14e800337afd9c2087d88942af129"
  },
  "Theme": "myListing",
  "MainColor": {
    "tabbarTint": "#00B2BC",
    "tabbarColor": "#D5D8DE",
    "mainColorTheme": "#00B2BC",
    "tabbar": "#fff"
  }
}

**Comment by salmaMohamed610** [comment]
![Screenshot_1580816012](https://user-images.githubusercontent.com/60310512/73744145-dbe2f600-4758-11ea-87a2-c9d2d4771fdc.png)
![Screenshot_1580816408](https://user-images.githubusercontent.com/60310512/73744146-dbe2f600-4758-11ea-8a62-68763425f95e.png)
![Screenshot_1580816537](https://user-images.githubusercontent.com/60310512/73744147-dc7b8c80-4758-11ea-9e8a-12893c0530a0.png)

**Comment by inspireui-support** [comment]
Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads  it's used to verify your proof of purchase? sorry for any inconvenience - Thank you!
