### ISSUE TITLE
[FluxStore] Shipping Plugin Feature Request

### ISSUE THREAD

**Issue by Mohamed20884** [inspireui/support#2010]
Hi,

I was wondering if you can add support for https://www.pluginhive.com/product/woocommerce-table-rate-shipping-pro-plugin/ or send me a guide on how to access the data from it to get the shipping cost based on city, as right now when I go to the shipping in the checkout it only shows me free shipping and not the rules added in the plugin.

Thanks

**Comment by inspireui-support** [comment]
Hi, you can check to see if you can able get the detail shipping info from this plugins via Rest API ?
