### ISSUE TITLE
MStore Pro - Payment Styles

### ISSUE THREAD

**Issue by jsaristizabal** [inspireui/support#2011]
@inspireui-support @luyx2412 

when the application goes to the payment page, it shows the page completely without styles.

---------

1. My issue:

2. Screenshots issues:
![Captura de Pantalla 2020-01-31 a la(s) 8 56 59 p  m](https://user-images.githubusercontent.com/29686082/73765731-f4e0ac80-4742-11ea-8e63-1a4f36d51ec5.png)

3. Proof of my purchased:

Item Purchase Code:
60b455a1-c467-4362-8fed-a3f976531151

3. Config files (optional)

**Comment by inspireui-support** [comment]
Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads  it's used to verify your proof of purchase? sorry for any inconvenience - Thank you!

**Comment by jsaristizabal** [comment]
@inspireui-support 
![Captura de Pantalla 2020-02-04 a la(s) 9 27 00 p  m](https://user-images.githubusercontent.com/29686082/73805595-1bc7ce80-4795-11ea-819f-1283903a3119.png)

**Comment by inspireui-support** [comment]
noted for fixing through the mstore-api - thank you!

**Comment by gonzalobarria** [comment]
@jsaristizabal now I have a blank screen when I press Confirm Order. Do you have the same issue?, Did you update the wordpress plugin?

**Comment by inspireui-support** [comment]
@minhtruong315 - pls hep to check the API issue

**Comment by minhtruong315** [comment]
@jsaristizabal can u send me full source code via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/2011

**Comment by momonchi** [comment]
i am experiencing this issue, I can't proceed payment only cod.

**Comment by jsaristizabal** [comment]
Hello, I still have the same problem even updating the plugin in the latest version and also updating the latest version of the application. and I have realized that the problem is not of the code that I have but of the application as such. Try it by choosing Stripe as the payment method and this error will happen to you. @inspireui-support @minhtruong315 
![Captura de Pantalla 2020-02-17 a la(s) 6 30 42 a  m](https://user-images.githubusercontent.com/29686082/74650712-4d0aac00-5150-11ea-9073-41195acbdd99.png)
![Captura de Pantalla 2020-02-17 a la(s) 6 30 31 a  m](https://user-images.githubusercontent.com/29686082/74650715-4ed46f80-5150-11ea-8191-2121a4265520.png)
