### ISSUE TITLE
Fix Menu + some other issues

### ISSUE THREAD

**Issue by tamzidsaleh** [inspireui/support#2012]
1. Logout on Sidebar Menu doesn't work at all. ( login takes to login page, but logout does nothing)

![image](https://user-images.githubusercontent.com/48500953/73787203-f9e64000-47c4-11ea-8d13-f647b36787a1.png)

2. the Categories in sidemenu only works on 'weblayout'. why is that? if I remove the line [ if (kLayoutWeb) ] then it shows the cateogry only but doesn't take me to categories page. how to Fix this?

![image](https://user-images.githubusercontent.com/48500953/73787314-3fa30880-47c5-11ea-950d-6034b7937a72.png)

3. I would like to add some WebView pages on Sidebar menu (like about us on setting page). how do I do that? help me giving the codes please

![image](https://user-images.githubusercontent.com/48500953/73787336-4e89bb00-47c5-11ea-98e3-599061c751ce.png)

4. About the category, I don't have any child categories.. so, my categories on Menu shows the same category as child as Duplicate and only clickable on child... So, I want to disable the child option, but have main category clickable only.

![image](https://user-images.githubusercontent.com/48500953/73787378-5d706d80-47c5-11ea-82ab-cf9f9aaf8d06.png)

5. In the checkout page, I am currently using Molli Payment. but it doesn't work ( https://wordpress.org/plugins/mollie-payments-for-woocommerce/ ).. This plugin has option to select different payment method, so when I select bank, a list of bank comes as dropdown.. but, in my case, it doesn't come. So I can't checkout at all.

![image](https://user-images.githubusercontent.com/48500953/73787523-afb18e80-47c5-11ea-8398-beac6375d37a.png)

Mollie also have a flutter solution, this might help you to fix the problem: https://wordpress.org/plugins/mollie-payments-for-woocommerce/

6. I would like to remove 'stores' tab from category page.. because I will not show any stores. so how do I remove that and have the 'Categories' as header title?

![image](https://user-images.githubusercontent.com/48500953/73787578-c952d600-47c5-11ea-908e-fdca9db64a16.png)

7. Icons in bottom bar doesn't change: 
![image](https://user-images.githubusercontent.com/48500953/73787791-2ea6c700-47c6-11ea-9bcf-5a245e5c81ec.png)

but check my folder, I have updated them with the new color.

Note: I didn't change any URL/link for these tabs. I just simply replaced the icons with same name with my icons. So it should work by default.. but I still see the default colors.

![image](https://user-images.githubusercontent.com/48500953/73787878-4b42ff00-47c6-11ea-8c2e-87f10f55d45b.png)

8. And last, how do I apply Gradient colors all over my app for backgrounds or text colors?

These are the current 8 issues that I have facing. I am expecting quick and prompt support from you. 

Thanks for making such a nice template.

This is the screenshot of my app purchase:
![image](https://user-images.githubusercontent.com/48500953/73787691-00c18280-47c6-11ea-817a-998de0750fcd.png)

**Comment by inspireui-support** [comment]
@tamzidsaleh - thank you for the detailed feedback, would you mind to add the comment on this link https://codecanyon.net/item/fluxstore-multi-vendor-flutter-ecommerce-full-app/25013325 as I could not see your  Envato username - thank you!

**Comment by tamzidsaleh** [comment]
Here's is the full screenshot of my account with username: 
![image](https://user-images.githubusercontent.com/48500953/73812036-8d3f6580-4805-11ea-8191-756ef4c6f71f.png)

it's difficult to comment on envato with all those screenshots. that's why I open the ticket here.

**Comment by minhtruong315** [comment]
[menu.dart.zip](https://github.com/inspireui/support/files/4169574/menu.dart.zip)
replace menu.dart to fix logout issue

**Comment by minhtruong315** [comment]
You must edit code to change tabbar icon
https://tppr.me/B0HpE

**Comment by tamzidsaleh** [comment]
What about the Payment system and others? Are you going to update me on those or not?

**Comment by inspireui-support** [comment]
@tamzidsaleh - sorry for the late response - the Bank option could not work complete with Molli when integrating with the app, did you try other options work well with the testing

**Comment by tamzidsaleh** [comment]
Yes, not only bank, all the payment system with Mollie doesn't work at all.

**Comment by minhtruong315** [comment]
@tamzidsaleh can u send me full source code via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/2012

**Comment by tamzidsaleh** [comment]
@minhtruong315 Email is sent with source code. Please update me asap. I have been waiting for many days.

**Comment by minhtruong315** [comment]
@tamzidsaleh I'm so sorry for deplay.  can u add my skype: minhtruong315
I'll help u check issues quickly.

**Comment by minhtruong315** [comment]
pls ping me on the skype
