### ISSUE TITLE
[FluxStore] - Change tab programmatically

### ISSUE THREAD

**Issue by sbeff** [inspireui/support#2013]
Hi,
how can I change the selected tab by pressing a menu tile? I tried to change it via Provider:
`Provider.of<AppModel>(context, listen: false).navigateTab(1);`
But I received this error:
`The method 'call' was called on null.`
Thanks

**Comment by inspireui-support** [comment]
Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads  it's used to verify your proof of purchase? sorry for any inconvenience - Thank you!

**Comment by sbeff** [comment]
Sorry, I was in hurry. Here is the screenshot of the purchase via email.

![Purchase confirmation](https://user-images.githubusercontent.com/15926323/73830326-caefbe80-4804-11ea-87f4-0b5837c4f814.jpg)

Thanks.

**Comment by inspireui-support** [comment]
@sbeff - you can try this function - https://tppr.me/vVnTL

We have similar feature from the banner image - thank you!
