### ISSUE TITLE
[Fluxstore - Woo] - Stock quantity problem "This is important"

### ISSUE THREAD

**Issue by sketchuprzr** [inspireui/support#2014]
My issue:

### This is important

The application offers the opportunity to place orders regardless of the number of stocks. The problem for this store. Because we cannot sell more than the number of stocks.

The app needs to check the stock count and not be able to order more than this number.

I made some arrangements for this.

I pulled the information from the store page via API.

_The information I have taken;_
**1- Stock quantity "stok"
2- Maximum number of orders "maxQuantitiy"**

(Note: The maximum number of orders is the number we apply to the products with the woocommerce plugin "[WooCommerce Max Quantity.](https://woocommerce.com/products/minmax-quantities/)" A user can only buy "x" from one product at a time. If we do not enter any numbers, he can buy 60.)

Just what needs to be done;

**"Using this information;**
**1) The user can only purchase a product for the amount of stock.**
**2) User can get maximum "maximum_allowed_quantity" from a product."**

![image](https://user-images.githubusercontent.com/60021696/73797208-732f6400-47c0-11ea-9238-e32eb2397ebd.png)

### File;
**source\lib\models**
[product dart - MODELS.zip](https://github.com/inspireui/support/files/4156695/product.dart.-.MODELS.zip)

**Comment by inspireui-support** [comment]
@sketchuprzr - appreciate for your help with the detail suggestion 

@minhtruong315 - please help to upgrade this feature

**Comment by zahmed84** [comment]
@sketchuprzr Thanks for highlighting this upgrade. This is an important upgrade to be included.

**Comment by sketchuprzr** [comment]
will anything be done about this? @minhtruong315 @inspireui-support

**Comment by kvt0012** [comment]
Hello sir, 
You can follow this instruction and set up for your app 
Thanks for your issue 
Have a good day

**Comment by sketchuprzr** [comment]
@kvt0012 
the link you sent me, the wordpress installation of the plugin 
I already know that.
Either you are kidding me or you don't know anything about it.
@inspireui-support @minhtruong315 
It's been almost 10 days, And I cannot see the slightest improvement in this regard.
Do you evaluate important issues in this way?
I've already done half of what needs to be done.
Why haven't I received a solution from any of the problems I wrote here so far?

**Comment by inspireui-support** [comment]
@kvt0012 

Sorry that the comment misunderstand your idea.

We confirm the #1 issue is fixed by the team, it will be ready in version 1.6.4 that will be released on next week.

The #2 is marked as a new feature request, as this is depending on extra plugin (https://woocommerce.com/products/minmax-quantities/) that not support from the WooCommerce API so that we may support it, the suggest to use https://docs.woocommerce.com/document/minmax-quantities/ - how do you think?

**Comment by sketchuprzr** [comment]
you didn't understand the event
There is no such thing as 1 and 2. 
Both are interrelated.
Stock and minimum stock are the same thread.
As you can see in the file and photo that I already sent,I put the stock and minimum stock information into practice.
You will only process these two data. This is something that should be.
A user should not order more than the number of stocks.
A user should not order more than the maximum number of stocks.
This is not a feature this is nothing extra!
This is something found on woocommerce sdk  
Even if this plugin is not available, on the product editing screen; As with the "single sale" option, the person can buy a maximum of 1 product.
Think of it as a problem, not an additional feature, and fix it as soon as possible.

### Because this is a very important issue in shopping systems.

**Comment by inspireui-support** [comment]
Thank you for the input, I will discuss with the team and also upgrade on next release - thank you!

**Comment by sketchuprzr** [comment]
It is about the solution of this problem. When will the update come? @inspireui-support

**Comment by sketchuprzr** [comment]
I am looking forward to this this week. This is really important. I've been waiting for about 20 days. I hope everything will be fine. :) Thanks

**Comment by inspireui-tech** [comment]
@sketchuprzr - we have upgraded to latest 1.6.4 to support for these features -  please check more detail from - https://medium.com/@inspireui/announcing-fluxstore-1-6-337efff1791f

Please note that maxAllowQuantity should config from the config as the API is not ready support - 

Let us know your input - thank you!
