### ISSUE TITLE
[FluxStore Woocommerce] - Theme and Colors

### ISSUE THREAD

**Issue by eduardopechir** [inspireui/support#2015]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:        Preview is not updated when changing theme (any theme)

2. Screenshots issues:         
<img width="1131" alt="Captura de Pantalla 2020-02-04 a la(s) 17 53 50" src="https://user-images.githubusercontent.com/60676647/73798180-b3b6bf80-4777-11ea-9d5f-8383eea428cd.png">

3. Proof of my purchased:     
<img width="1280" alt="Captura de Pantalla 2020-02-04 a la(s) 17 57 18" src="https://user-images.githubusercontent.com/60676647/73798260-e95ba880-4777-11ea-8846-e22e68aec7a3.png">

3. Config files (optional)

**Comment by inspireui-support** [comment]
@eduardopechir - could you try to check if the common/config.dart disable caching:
```
isCaching: false
```

**Comment by eduardopechir** [comment]
always is true

<img width="1280" alt="Captura de Pantalla 2020-02-04 a la(s) 20 09 32" src="https://user-images.githubusercontent.com/60676647/73804785-87f10500-478a-11ea-8f45-609c68adb201.png">

**Comment by Blunnyn** [comment]
same problem, did you fix it?

**Comment by eduardopechir** [comment]
Hi.
No breakthrough
I really believe that FluxStore is a great project, but we need more help from developers.
I need help!

**Comment by eduardopechir** [comment]
Now I have this error message
<img width="1198" alt="Captura de Pantalla 2020-02-07 a la(s) 14 51 35" src="https://user-images.githubusercontent.com/60676647/74065002-85282700-49b9-11ea-9329-030aeff24d2c.png">

**Comment by eduardopechir** [comment]
Ok, I found a solution. Upload the Config.json file through the MStore API plugin on my Woocommerce site. Each update, if I want to see it reflected in the simulator, I have to re-upload the updated Config.json file with the MStore API plugin.
Developers Does it always have to be this way?
<img width="1280" alt="Captura de Pantalla 2020-02-07 a la(s) 15 21 06" src="https://user-images.githubusercontent.com/60676647/74067115-17322e80-49be-11ea-8aa0-f4857687170f.png">

**Comment by inspireui-support** [comment]
@eduardopechir - pls try to use this guide https://docs.inspireui.com/fluxstore/performance/

Once you would like to reset the UI, upload new config.json and clear and clean up the Cache Rest API plugin
