### ISSUE TITLE
[Fluxstore - Multivendor] - Sign in error using firebase

### ISSUE THREAD

**Issue by mdwasim1340** [inspireui/support#2016]
I'm getting errors while signing in. 
1. While signing in with email and password it show jwt authentication error.
![Screenshot_20200204-215432__01](https://user-images.githubusercontent.com/60678774/73813822-36a73c80-47af-11ea-8974-4745efe7a962.jpg)
2. In case of sms - no sms is send to the users phone.
3. Gmail sign in is also not working - showing Warning there is an issue with the app during request the data.
![Screenshot_20200204-215611](https://user-images.githubusercontent.com/60678774/73813843-44f55880-47af-11ea-8f09-e2c69b1c5c6f.jpg)

Also when I try to build the app, app is successfully build but while installing it says corrupted - cannot install. 

My purchase download screenshot is here
![abc](https://user-images.githubusercontent.com/60678774/73813961-a3223b80-47af-11ea-944f-9628aff8069e.jpg)

Please also find my attached zipped filed for config common folder
[common.zip](https://github.com/inspireui/support/files/4157612/common.zip)

**Comment by minhtruong315** [comment]
@mdwasim1340 I checked your config. Login is working well. https://tppr.me/zDbhu
can u send me full source code via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/2016

**Comment by mdwasim1340** [comment]
Hello, friend I've already send you email with the full source code 3 days ago, please check it.

**Comment by minhtruong315** [comment]
[services.zip](https://github.com/inspireui/support/files/4181530/services.zip)
replace services folder and ios/Runner/AppDelegate.swift then try again. It's working on iOS
[AppDelegate.swift.zip](https://github.com/inspireui/support/files/4181532/AppDelegate.swift.zip)

**Comment by mdwasim1340** [comment]
I'm trying to build it on Android first. Will this work on Android as well?

**Comment by minhtruong315** [comment]
I'm trying on iOS. it's working on iOS. Can u try it on android?

**Comment by mdwasim1340** [comment]
It didn't work. Now I can't even open the app as well.

**Comment by mdwasim1340** [comment]
Can you give me the link of full code that has worked.

**Comment by mdwasim1340** [comment]
Could you please help? how much time does it take for you to give the working code? I'm waiting for more than 12 days already.

**Comment by inspireui-support** [comment]
@mdwasim1340 - sorry for late response as my team missed your comments - as reporting there is no problem with the source and from your config file, is there any custom code that you break the chain?

Kindly update your rating or process the refund if you could not use the product so far - https://help.market.envato.com/hc/en-us/articles/202821460-Can-I-Get-A-Refund- - thank you!

**Comment by mdwasim1340** [comment]
How did you closed the case without solving it???
Please check the video I've attached.
Could you please help me to solve it. 
![2020-02-18_8-49-10](https://user-images.githubusercontent.com/60678774/74742059-f5417300-522b-11ea-9d26-dd016d98c6f4.gif)

**Comment by minhtruong315** [comment]
@mdwasim1340 add my skype: minhtruong315
I'll help u check issues quickly.
thanks

**Comment by mdwasim1340** [comment]
I tried to connect to Skype but no reply. Please check your Skype for my message and give me a time when we can chat.

**Comment by minhtruong315** [comment]
![Image from iOS](https://user-images.githubusercontent.com/10402500/75124963-22d36400-56e5-11ea-8e2b-9eaf1a71b0cd.png)
I
Hi, we could not see your Skype invite, could i know your Skype ID?

**Comment by gurutos** [comment]
Good day Support team, 

i have the same problem, could you solve it? 

Thanks and Regards,
PMontes.

**Comment by minhtruong315** [comment]
I have already supported you to resolve your issues. And we only support default shipping methods on woo commerce, dont support other plugin.

**Comment by gurutos** [comment]
hello @minhtruong315 ,

 i think your confusing me because you havent support me, im waiting for your support, 

thanks and Regards,
PaoMontes
