### ISSUE TITLE
[Fluxstore] - I want to change the items in top menu

### ISSUE THREAD

**Issue by limitlessfirm** [inspireui/support#2017]
---------

1. My issue: how I can change the items in top menu

2. Screenshots issues:
![top-menu](https://user-images.githubusercontent.com/59250639/73817391-77c14000-47f3-11ea-8dd1-d239dc9983c3.JPG)

3. Proof of my purchased:
![screenshot](https://user-images.githubusercontent.com/59250639/73817402-7e4fb780-47f3-11ea-8a8d-f10190b633fe.JPG)

3. Config files (optional)

**Comment by inspireui-support** [comment]
@limitlessfirm - pls try to use the Inspector to customize any UI from the app - https://docs.inspireui.com/fluxstore/useful-tip/#how-to-change-the-ui-quickly - thanks

**Comment by limitlessfirm** [comment]
Which file in the source have to edit with (Inspector)to customize the menu items
