### ISSUE TITLE
[Fluxstore Pro] - question before purchase for magento environments 

### ISSUE THREAD

**Issue by scne** [inspireui/support#2019]
Hi there,

I would by this product but I've some practical questions because I'm actually using magento 2.3 CE for my e-commerce:
1. all new customer are recorded into my magento engine: is it possible to store these profiles in order that each of them belonging to a specific customer group?
2. in magento I can set a specific price for each client group. Your system is able to get these kind of prices?

Best

**Comment by inspireui-support** [comment]
Hi @scne - these features are not available and need some customize to make it work, the example you can custom the API base on user login to load the product pricing... Thank you!

**Comment by scne** [comment]
Hi there, can I edit code in order to customize it for these features (if I'll buy your product obviously)? For instance I know how edit  magento basic API call to get specific price based on customer group or how store customer into a specific customer group, based on this skill I'll edit your basic code to match my constraints.
