### ISSUE TITLE
Cebuilder doesnt support this project yet

### ISSUE THREAD

**Issue by hachikaru** [inspireui/support#202]
**Mandatory Info (please complete the following information):**
 - Product: [ ListApp]
 - My Purchased Code: [45c7c7ac-5a00-40a2-af23-8111ef3e5d28]

**My  issues**
I tried to install the listapp through CeBuilder but i get a pop up that it does not support this product yet and i need to set it up asap. I need your help

**Comment by minhcasi** [comment]
Hi, could i confirm that you open the folder where content the package.json file ?

**Comment by minhcasi** [comment]
https://app.intercom.io/a/apps/xro9xnfd/inbox/inbox/2664005/conversations/20517538888

**Comment by hachikaru** [comment]
ok i have chosen the source ...am setting it up from windows 10 .if i click on run setup command line shows what should i enter

**Comment by minhcasi** [comment]
Hi, could you help to download the latest v.0.26.1 - thank you!

**Comment by hachikaru** [comment]
latest v.0.26.1 ? version of which app ..the Cebuilder ? am just stuck dont know what to do next

**Comment by minhcasi** [comment]
Hi, it's the CeBuilder from http://inspireui.com - thanks

**Comment by SAVICTOR** [comment]
install yarn https://yarnpkg.com/lang/en/docs/install/
install git https://git-scm.com/download/win

**Comment by SAVICTOR** [comment]
> After installing the latest version of Cebuilder i ran thesetup and got the errors below
> C:\Users\Oscar\Desktop\ListApp 1.6.1\Source>expo start
> 'expo' is not recognized as an internal or external command,
> operable program or batch file.
> 
> C:\Users\Oscar\Desktop\ListApp 1.6.1\Source>yarn install
> 'yarn' is not recognized as an internal or external command,
> operable program or batch file.
> 
> C:\Users\Oscar\Desktop\ListApp 1.6.1\Source>npm install
> npm ERR! code ENOGIT
> npm ERR! Error while executing:
> npm ERR! undefined ls-remote -h -t ssh://git@github.com/expo/vector-icons.git
> npm ERR!
> npm ERR! undefined
> npm ERR! No git binary found in $PATH
> npm ERR!
> npm ERR! Failed using git.
> npm ERR! Please check if you have git installed and in your PATH.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! C:\Users\Oscar\AppData\Roaming\npm-cache_logs\2019-01-25T21_15_08_307Z-debug.log

install yarn https://yarnpkg.com/lang/en/docs/install/
install git https://git-scm.com/download/win

**Comment by minhtruong315** [comment]
Hi @hachikaru Did you install all tools?
<img width="1028" alt="screen shot 2019-01-27 at 4 55 45 pm" src="https://user-images.githubusercontent.com/10402500/51799541-a60d5680-2254-11e9-8f81-193a81af4bcb.png">

**Comment by hachikaru** [comment]
i have done all but still cant build app ....
error shows Set EXPO_DEBUG=true in your env to view the stack trace.
and what simulator should i use to test it

this is the error 
 Would you like to upload a keystore or have us generate one for you?
If you don't know what this means, let us handle it! :)
 false
[15:40:38] Unable to find an existing Expo CLI instance for this directory, starting a new one...
[15:41:41] Starting Metro Bundler on port 19001.
[15:41:45] Publishing to channel 'default'...
[15:42:00] Building iOS bundle
[15:43:41] Unable to resolve module `api-ecommerce` from `C:\Users\Oscar\Desktop\ListApp\Source\App.js`: Module `api-ecommerce` does not exist in the Haste module map
[15:43:41]
[15:43:41] This might be related to https://github.com/facebook/react-native/issues/4968
[15:43:41] To resolve try the following:
[15:43:41]   1. Clear watchman watches: `watchman watch-del-all`.
[15:43:41]   2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
[15:43:41]   3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.
[15:43:41]   4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.
[15:43:41] Unable to resolve "api-ecommerce" from "App.js"
[15:43:44] Cannot read property 'status' of undefined
[15:43:44] Set EXPO_DEBUG=true in your env to view the stack trace.
Building JavaScript bundle [=

**Comment by minhtruong315** [comment]
Hi @hachikaru , Can you add my skype? I will help you check via teamview
my skype is : minhtruong315@gmail.com

**Comment by hachikaru** [comment]
that would be perfect please can i know the time GMT that will work for you since our tie aint same

**Comment by hachikaru** [comment]
i sent you a message via skype please i need your help asap i need to launch the app this monday

**Comment by minhtruong315** [comment]
Hi @hachikaru I don't see messages you sent. Please check again

**Comment by hachikaru** [comment]
i did my skype username is +2348080476828 and the issue am getting is that i should set Expo true in my environment how do i go about it and how do i get the apk

**Comment by minhcasi** [comment]
@minhtruong315 will contact you - thanks
