### ISSUE TITLE
[my-product] - 

### ISSUE THREAD

**Issue by mariablomberg** [inspireui/support#2020]
1. My issue:
Nothing happens when i press Approve.
When I press 'deny', I get the error-code: {"error":"access_denied","error_description":"User denied the access to the resource"}

2. Screenshots issues:
See image below

3. Proof of my purchased:
Purchase code: 56c14546-d8ea-4024-9a11-20c549cda35a

**Comment by mariablomberg** [comment]
<img width="1030" alt="Screen Shot 2020-01-30 at 17 40 10" src="https://user-images.githubusercontent.com/44641181/73853613-77e03080-4831-11ea-816e-143b8cd45672.png">

**Comment by minhtruong315** [comment]
supported
