### ISSUE TITLE
Multi Vendor Fluxstore - WCFM Not Working

### ISSUE THREAD

**Issue by juancamilocanal** [inspireui/support#2021]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: - When using my user and admin on the dart config the multivendor plugin is not working. The screen goes blank after the splash screen.

- There is no padding on top so logo, menu and search cant be seen.

- App Icons are not being generated (even though I followed all instructions)

- Where can I change the icons and color for menu and search on the homesecreen?

- Logout is not working on menu, only in "My Account" tab

- I cant change the image in the third onboarding screen. It will not change if I edit the config file: 
/// the welcome screen data
List onBoardingData = [

- Where Can I change the image of the blue lemon in My account?

2. Screenshots issues: 
![image](https://user-images.githubusercontent.com/818225/73864938-76524080-4810-11ea-8433-589a8dc96e47.png)

3. Proof of my purchased: 
![image](https://user-images.githubusercontent.com/818225/73864886-5de22600-4810-11ea-9b73-e210a7f61f6b.png)

3. Config files (optional): This should be shared confidentially, it contains passwords and API keys

**Comment by juancamilocanal** [comment]
Also thumbnails are not showing on product detail screen:

![IMG_20200205_231039](https://user-images.githubusercontent.com/818225/73905370-12aa3080-486d-11ea-83bf-b37f4ef33652.jpg)

**Comment by inspireui-support** [comment]
@juancamilocanal - could you mind to post a comment on this product to verify the proof of purchased - https://codecanyon.net/item/fluxstore-multi-vendor-flutter-ecommerce-full-app/25013325 - as i could get your username on above screenshot - thank you!

**Comment by inspireui-support** [comment]
verified purchased - 

@minhtruong315 - please help for supporting

**Comment by juancamilocanal** [comment]
Hi. Please help. Purchase proof is on the first message

**Comment by juancamilocanal** [comment]
![Screenshot_2020-02-06-08-59-18-171_com android chrome](https://user-images.githubusercontent.com/818225/73943586-fd5df200-48be-11ea-85d1-f2b857de0e97.jpg)

**Comment by vwakehub** [comment]
i am also getting Same Problem 

i have changed some setting in config .json file and its not showing  up after hot rebooting too ,
also on latest product page products are not showing up until i select any sort of filter 

my username on codecanyon is Vwake07 and bought Fluxtore MV today !!

**Comment by minhtruong315** [comment]
@juancamilocanal can u send me config files via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/2021

**Comment by juancamilocanal** [comment]
Sent. Y just forwarded them again because you already had them. Let me know if you got them.

**Comment by minhtruong315** [comment]
@juancamilocanal i replied all via your email. pls check

**Comment by minhtruong315** [comment]
@juancamilocanal how arew your issues?
