### ISSUE TITLE
[EvaStore] - Help needed

### ISSUE THREAD

**Issue by BMehdii** [inspireui/support#2022]
1. My issues: 
- In some products, I don't have variants, how can I hide this " Default Title "? 

![unnamed-7](https://user-images.githubusercontent.com/60139508/73869207-30b26980-484a-11ea-9f95-86259380d762.png)

-  I changed the URL in config.js to my about page URL, but it still doesn't load  ( i got a blank screen )

![unnamed-8](https://user-images.githubusercontent.com/60139508/73869273-5475af80-484a-11ea-8252-f726551a4865.png)

- How can i change the background image for each collection so i don't have the same image repeated
<img width="308" alt="Screen Shot 2020-02-05 at 7 13 22 PM" src="https://user-images.githubusercontent.com/60139508/73870001-981ce900-484b-11ea-9a68-cef7ab3e2c17.png">

thanks in advance

2. Proof of my purchased:

<img width="1280" alt="Screen Shot 2020-01-24 at 7 48 18 PM" src="https://user-images.githubusercontent.com/60139508/73869363-6d7e6080-484a-11ea-8274-266a9d79f04b.png">

**Comment by luyx2412** [comment]
Hi @BMehdii 
- Please filter with title `Default title` in `src/containers/ProductDetailContainer/Title.js`  line 30 
![image](https://user-images.githubusercontent.com/8909619/73949344-dfc77180-492c-11ea-8d6c-bb8aafa8299d.png)
- Please send me your about us url, and make sure this url is available.
- Please follow the screenshot to change collection image
<img width="569" alt="Teampaper Snap_2020-02-06 22-08-56@2x" src="https://user-images.githubusercontent.com/8909619/73949728-6714e500-492d-11ea-9815-1c98956a399f.png">
![image](https://user-images.githubusercontent.com/8909619/73949740-68dea880-492d-11ea-801e-331043b37878.png)

Thanks

**Comment by BMehdii** [comment]
Thanks for your help..
here is my about us url : https://daniacosmetics.com/pages/dania-cosmetics

**Comment by luyx2412** [comment]
HI @BMehdii can you send me your Config.js file?

Thanks
