### ISSUE TITLE
[Fluxstore Woocommerce] - Some bugs highlighted in App

### ISSUE THREAD

**Issue by zahmed84** [inspireui/support#2025]
First of All i would like give my regards to whole Inspireui Team for creating this wonderful app. I have already published this App on Playstore but there are some bugs in the App which are very necessary to be fixed.

**1. The most important bug is about Cart Page.**
When items are added in Cart and from cart page we change the quantity of any item, before checkout we close the app and reopen it then the cart page gives the error. please see the below screenshot.
![Screenshot_20200206-121900](https://user-images.githubusercontent.com/58950301/73914422-170d3280-48db-11ea-842a-84739fe9ff9f.jpg)

**2. Second bug is about Login Page**
When we click on "Rate the App" on Login Page. It gives three option i.e. "Rate", "May be Later", "No Thanks". In fact when we tap on these options, nothing happens. See below Screen shot.
![Screenshot_20200206-121221](https://user-images.githubusercontent.com/58950301/73915303-df06ef00-48dc-11ea-9999-e1d4c284af2e.jpg)

**3. Third bug is about checkout page**
When someone login through SMS, then after going to checkout page it automatically fills Name field with mobile number and fills the email address like "03216548576@domain.com" which i think must be black when any user sign in through SMS. See below screen shot.
![Screenshot_20200206-124452](https://user-images.githubusercontent.com/58950301/73916200-cac3f180-48de-11ea-92d4-4b791e7e3a7e.jpg)

Please try to fix the above issued in your coming update.

Thanks

**Comment by zahmed84** [comment]
Hey what about the above issues, will you resolve these issue in your coming update?

I have noticed another issue on Search page i.e. when we search a product which has discounted price it shows only regular price with product. My suggestion is that the discounted product must show both prices (regular price and sale price) on Search page.

![Screenshot_20200213-183941](https://user-images.githubusercontent.com/58950301/74441003-e86df980-4e90-11ea-9ed0-f7c22d8e8a1b.jpg)

**Comment by kvt0012** [comment]
Sorry for late, sir 
I've already fixed the first and second problem, it will appear on next version if having any changes. 
About the third problem, we think it should be appeared to recognize which account we use before customer change it. 

About your next problem, I checked on my application and this feature has already had on our app. 
 As picture below. 
![image](https://user-images.githubusercontent.com/49152325/74514929-1f4f1880-4f40-11ea-86c6-41e9f687a21c.png)

So can you check your config file, maybe it has some error when calling api 
Thank you ,
Have a good day.
