### ISSUE TITLE
ce builder not working

### ISSUE THREAD

**Issue by alazar-aklilu** [inspireui/support#2026]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
i think there is something wrong with my ce builder for mstore multivendor, 1. it does not show all the categories in my woocommerce store, 2. it is not the same as the ones shown in the documentations
2. Screenshots issues:
i have attached on markdown
3. Proof of my purchased:
i have attached on markdown
3. Config files (optional)

**Comment by minhtruong315** [comment]
@alazar-aklilu thanks for your report. We're having issues with cebuilder now. We'll release the new version as soon as possible.

**Comment by minhtruong315** [comment]
@alazar-aklilu can u send me full source code via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/2026

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
