### ISSUE TITLE
[FluxNews] Login in app

### ISSUE THREAD

**Issue by Lacenlot** [inspireui/support#2027]
Hey, i have a problem to login in the app, it's about connection refused on android emulator and same in real device.

Print error:
https://ibb.co/yq33d2R

**Comment by inspireui-support** [comment]
Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads  it's used to verify your proof of purchase? sorry for any inconvenience - Thank you!

**Comment by Lacenlot** [comment]
screenshot of the purschase:

https://user-images.githubusercontent.com/54359491/74236545-34157d00-4cb0-11ea-8c23-0690ff5fb9f3.png
