### ISSUE TITLE
[MV-FluxStore-Dokan] - Changes to Config.json Not Showing Up in Hot Reboot 

### ISSUE THREAD

**Issue by vwakehub** [inspireui/support#2028]
---------

1. My issue: 

     1.Changes to Config.json Not Showing Up in Hot Reboot
   

2. Screenshots issues:
    
     1.
![Capture2](https://user-images.githubusercontent.com/59481921/73946383-d97cc980-491b-11ea-9cc7-4bac111d0e09.PNG)

  

3. Proof of my purchased:
    
![Capture](https://user-images.githubusercontent.com/59481921/73946137-72f7ab80-491b-11ea-9af3-0eb50ab5a7c6.PNG)

3. Config files (optional)

**Comment by vwakehub** [comment]
Also one More Problem , When Product Page Load for first time ,the top of the Photo Of Product take time load it look damn wierd , Check the Attached Video .

https://drive.google.com/open?id=1F1GnSvQhoIW2NIH_Id7ZyLffh1jxbwSz

**Comment by yassiney120** [comment]
me too if there is any solution please share it with me thank you   (the top of the Photo Of Product take time load)

**Comment by inspireui-support** [comment]
@vwakehub - thank you for well spot on the issue, we will investigate this issue and keep an update - thank you!

**Comment by minhtruong315** [comment]
@vwakehub you need to edit config_en.json. if you're using English language

**Comment by vwakehub** [comment]
@minhtruong315  its working now !! Thanks 

Also help me in fixing 2nd issue .

--------, When Product Page Load for first time ,the top of the Photo Of Product take time load it look damn wierd , Check the Attached Video .

https://drive.google.com/open?id=1F1GnSvQhoIW2NIH_Id7ZyLffh1jxbwSz

**Comment by vwakehub** [comment]
@minhtruong315 

I have added you.
Please accept the invitation.

**Comment by minhtruong315** [comment]
Replace screens/detail/image_feature.dart to fix product image
[image_feature.dart.zip](https://github.com/inspireui/support/files/4169717/image_feature.dart.zip)
