### ISSUE TITLE
[Fluxstore-MV] - SMS & Google login Error

### ISSUE THREAD

**Issue by saifmuhtar** [inspireui/support#2029]
1. My issue:
SMS & Google login Error
I checked my SHA1 and it's correct. 

2. Screenshots issues:
SMS login Error
![1580721234339](https://user-images.githubusercontent.com/34681804/73950896-b3fdb900-4937-11ea-8c9d-24a7f3127ffd.JPEG)

Google login Error
![1580721242853](https://user-images.githubusercontent.com/34681804/73950918-bcee8a80-4937-11ea-9c54-e537897c51fa.JPEG)

3. Proof of my purchased:
![72332982-fc89d400-36f5-11ea-9307-f8c418404111](https://user-images.githubusercontent.com/34681804/73951198-27072f80-4938-11ea-98f8-9a514428f664.jpg)

Please contact me via Skype saifmuhtar@gmail.com

**Comment by minhtruong315** [comment]
I don't find you on the skype. can u add my skype: minhtruong315

**Comment by saifmuhtar** [comment]
@minhtruong315 I managed to solve this issue. 
My mistake is at debug SHA-1 key.
I should use release SHA-1key and place it on firebase.
Now my app is totally working 🥳🥳🥳🥳🥳
