### ISSUE TITLE
[CeStore] The mobile app is not send email confirm after order finished

### ISSUE THREAD

**Issue by dunguyenn** [inspireui/support#203]
Dear support,

The mobile app is not send email confirm after order finished. Please help check and give me advise for fix.

Thanks, Du

**Comment by minhtruong315** [comment]
Hi @dunguyenn, I will fix this issue on next version.
Thanks

**Comment by dunguyenn** [comment]
Dear Minh,
Thank you for your support, how i can get update for fix this problem please? 
Du
