### ISSUE TITLE
[FLUXSTORE MV] -  NOTIFICATION FIREBASE & MESSAGE TO VENDOR

### ISSUE THREAD

**Issue by yassiney120** [inspireui/support#2030]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
- notification by firbase it's not showing on android device ( real and emulator)
-send message to vendor come empty 
2. Screenshots issues:
https://drive.google.com/file/d/1ob80Ms7J6smfev3dMBxbpReUKNWananC/view?usp=sharing

https://ibb.co/LtdSVzS
https://ibb.co/Y3zW4mR

Proof of my purchased:
https://ibb.co/XsskN38
3. Config files (optional)

**Comment by minhtruong315** [comment]
supported via skype

**Comment by raysernick** [comment]
hello @minhtruong315 how i can config this?
my vendor or me can't receive notification
