### ISSUE TITLE
[FluxStore] Deep Linking Products

### ISSUE THREAD

**Issue by Mohamed20884** [inspireui/support#2031]
Hi

I tried the deep linking shown in the documentation and was able to load the 404 page from the example however when I used a link from a product on my site it did not take me to the product page in the app but to the home screen of the app. please let me know what should be done to get the desired result.

Thanks

**Comment by inspireui-support** [comment]
Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads  it's used to verify your proof of purchase? sorry for any inconvenience - Thank you!

**Comment by Mohamed20884** [comment]
<img width="1280" alt="Screen Shot 2020-01-19 at 1 10 59 PM" src="https://user-images.githubusercontent.com/6944543/73995212-97c24200-4960-11ea-8ee5-657d5cce5f66.png">

**Comment by inspireui-support** [comment]
@trunghieuvn - could you suggest a solution for this issue

**Comment by Mohamed20884** [comment]
@inspireui-support @trunghieuvn  any update regarding this

**Comment by Mohamed20884** [comment]
@trunghieuvn  ?

**Comment by inspireui-tech** [comment]
@Mohamed20884 - we are sorry that missed your comment, would you mind to check more on this library document to check if there is missing config from your setting - https://pub.dev/packages/uni_links - we are using this library to support for the deep link - thank you!

**Comment by minhcasi** [comment]
@Mohamed20884 - sorry for the late response on this ticket - could you help to check this library guide to see if you have a missing config for the deep link feature -  https://pub.dev/packages/uni_links and

**Comment by Mohamed20884** [comment]
I will check the library can you send me an example link to view a product using the example site

**Comment by Senior-Gamal** [comment]
any update about deep link ?
