### ISSUE TITLE
Followed your video guide but showing error on Android Studio

### ISSUE THREAD

**Issue by ukveda** [inspireui/support#2032]
1. My issue:

Hello,
I followed your video setup guide,
https://www.youtube.com/watch?v=y55AqAEEp8M&t=28s

After adding "Android Virtual Device" I played the icon as per shown on video at 12:34, Virtual mobile screen opened. Then I clicked green play icon on Android studio, then launching started in console section and after few minutes it gave ERROR.
"BUILD FAILED
Finished with error: Gradle task assembleDebug failed with exit code 1

Why this error showed up as I followed exactly the same guidelines which you showed in video?

Please reply ASAP

2. Screenshots issues:
![Error Screen Shot](https://user-images.githubusercontent.com/58551104/73957466-6760b080-492c-11ea-8105-826842f44905.png)

3. Proof of my purchased: 580c8e49-f3bf-423c-a6c4-9dcdcbed4851

3. Config files (optional)

**Comment by inspireui-support** [comment]
@ukveda - you can try to run "flutter doctor" to check if there is any issue with the flutter

Also, double check your setting by using this guide https://flutter.dev/docs/get-started/install/windows
