### ISSUE TITLE
[Fluxstore Pro - 

### ISSUE THREAD

**Issue by Maksish** [inspireui/support#2033]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
SHIPPING METHOD ISSUE IN MAGENTO
2. Screenshots issues:
![Screenshot_1581007979](https://user-images.githubusercontent.com/31925489/73960150-5e71de00-4930-11ea-9d57-aa9b6f4202ea.png)

3. Proof of my purchased:
![Screenshot from 2020-02-06 22-31-37](https://user-images.githubusercontent.com/31925489/73960203-76496200-4930-11ea-8609-1b8aac4cde24.png)

3. Config files (optional)
[config.zip](https://github.com/inspireui/support/files/4166559/config.zip)

**Comment by minhtruong315** [comment]
@Maksish I checked your config. it's working well on my end
https://tppr.me/PVZ33
https://tppr.me/sj1cX
