### ISSUE TITLE
mstore-api is giving error while activating

### ISSUE THREAD

**Issue by asachin16** [inspireui/support#2034]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: mstore-api plugin is giving following error while activating

Plugin could not be activated because it triggered a fatal error.

Parse error: syntax error, unexpected '?' in /home4/umwj1575/public_html/stage.agonlocks.online/wp-content/plugins/mstore-api/controllers/FlutterVendor.php on line 130

2. Screenshots issues:

<img width="1231" alt="Screenshot 2020-02-06 at 10 02 52 PM" src="https://user-images.githubusercontent.com/6480091/73960147-5dd94780-4930-11ea-8717-d2c98bf13d40.png">

3. Proof of my purchased:

<img width="589" alt="Screenshot 2020-02-06 at 10 31 33 PM" src="https://user-images.githubusercontent.com/6480091/73960266-91b46d00-4930-11ea-8632-c27ee79b1186.png">

3. Config files (optional)

**Comment by asachin16** [comment]
<img width="1427" alt="Screenshot 2020-02-06 at 10 36 23 PM" src="https://user-images.githubusercontent.com/6480091/73960559-2919c000-4931-11ea-99db-6629261e5de9.png">

**Comment by inspireui-support** [comment]
@asachin16 - could i check if you have installed the latest mstore-api library - https://wordpress.org/plugins/mstore-api/ - thank you!

**Comment by asachin16** [comment]
<img width="1263" alt="Screenshot 2020-02-07 at 9 14 27 AM" src="https://user-images.githubusercontent.com/6480091/73999319-678f9900-498a-11ea-905a-73b2bf1a1812.png">

Attaching screenshot from my Wordpress plugins

**Comment by inspireui-support** [comment]
@minhtruong315 - please help for checking the API plugin issue

**Comment by minhtruong315** [comment]
@asachin16 can u send me account to login to admin panel your website via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/2034

**Comment by asachin16** [comment]
Hi,

I think this issue was because of the PHP version. Now, It has been activated after updating the PHP version. 

Thanks anyway
