### ISSUE TITLE
[Flux News] 

### ISSUE THREAD

**Issue by boktoday** [inspireui/support#2036]
Thanks for your reply on CodeCanyon last night. I made the purchase right away for Flux News. 

1. I have successfully installed it via Andriod Studio and managed to run your out of the box set up via the emulator. All worked fine.  Support docs look very helpful to configure and I am doing so now for other features. 

2. As I mentioned in my comment, I am using LearnDash LMS (https://www.learndash.com/) with Salient theme (https://themeforest.net/item/salient-responsive-multipurpose-theme/4363266) and wish to display course categories and the associated lessons (posts) and not the blog posts as currently configured. 

3. As you suggested, I have installed the two plugins you recommended for rest api and as you can see in the attached image, I have activated the WP REST API Controller Settings for all the LMS fields. 

4. Please advise as to what I need to do next and in what files to make this work. Hot reload did not change anything yet. 

Thanks. 

FluxNews - Flutter mobile app for Wordpress
Regular License
Purchase code: code: 9bb--------------------------3bf

![lms-tax-labels-help](https://user-images.githubusercontent.com/6969447/73980252-f6e57e00-4983-11ea-9947-64d153ff6011.jpg)

**Comment by inspireui-support** [comment]
@boktoday - please try to customize the services/wordpress.dart and some files from the model folder.

example: update the category by changing this code - https://tppr.me/ZYXms and remapping  json the Category model.

Please try your best with the customization, if you could not do we could help to create the medium blog to explain detail with the example code.

**Comment by boktoday** [comment]
Thanks for that pointer. Yeah. No luck. I think I need a bit more detail. I think I need to change the code in wordpress.dart 

https://workfresh.me/wp-admin/edit-tags.php?taxonomy=**ld_course_category**&post_type=**sfwd-courses**

Any more clues?

**Comment by boktoday** [comment]
If I just change is shown in your screengrab I get error. error: Undefined name 'ld_lesson_category'. (undefined_identifier at [fstore] lib\services\wordpress.dart:88)

**Comment by boktoday** [comment]
Okay. I've done some more digging. Because I want this app to enable people to have to login and see their course on WordPress via this app, maybe I don't need all these categories and posts functionality?

I probably just need the mydomain.com/courses page to load first where home is and in the tab bar menu (drawer menu) be shown how to make those menu items navigate to the pages I want them to in Wordpress. 

Hope that makes sense and maybe you can assist me with how I might do this in the various files. 

Thank you.

**Comment by boktoday** [comment]
Also, how might I temp set the onboarding screens to show while testing?

**Comment by inspireui-support** [comment]
@boktoday - could you zip your common file to my email support and clarify more which features you would like to custom the app - email: support@inspireui.com

We could highlight some important files need to be changed from the UI and send back the final code, we may write a tutorial code on our Medium as this kind of interesting section to extend the Fluxnews to LMS (with extra plugins and customization)

(This is our extra free offer for some special integration so please give us some time for the team update the guide). Very best!

**Comment by boktoday** [comment]
Thank you @inspireui-support. I will email you as suggested and I also was thinking that documenting the Learn dash thing on Medium or even making a new app for the top two popular Wordpress LMS plugins would be another good product for you perhaps. 

I'll be in touch.

**Comment by inspireui-support** [comment]
Thank you, please send detail the email and also note about this ticket - very best!

**Comment by alessandropuricelli** [comment]
I'm evaluating to buy Fluxstore Pro.
Do you succeed to integrate Learndash to flutter?

My website configuration is this:
Woocommerce + Memberships + Subscriptions + Learndash

I want to create an app to get access to Learndash courses only to people with an active Woocommerce membership or subscription.

Is it possible, in your opinion?

**Comment by boktoday** [comment]
Hi Alessandro. I've not tried this yet. I've just come back from overseas. I will let you know my thoughts soon.

**Comment by distil112** [comment]
Have any of you tried SuperNova Studios?

**Comment by distil112** [comment]
@boktoday Do you succeed to integrate Learndash to flutter?

**Comment by distil112** [comment]
> I'm evaluating to buy Fluxstore Pro.
> Do you succeed to integrate Learndash to flutter?
> 
> My website configuration is this:
> Woocommerce + Memberships + Subscriptions + Learndash
> 
> I want to create an app to get access to Learndash courses only to people with an active Woocommerce membership or subscription.
> 
> Is it possible, in your opinion?

@alessandropuricelli Did you end up purchasing and working with Learndash?

**Comment by gustavosilva-gss** [comment]
> @boktoday Do you succeed to integrate Learndash to flutter?

Did you find anything new on using learnsah and flutter?

**Comment by boktoday** [comment]
Hi all. I haven't attempted this or followed through with the developers. I will but what I see as the issue is the way that Flux News has its only blog post layouts and Learn Dash has so much in the display of learning objects I wonder if this would work. I will aim to contact the developers in the coming weeks. Busy with COVID-19 projects right now.
