### ISSUE TITLE
Fluxstore User Registration and Login Exception

### ISSUE THREAD

**Issue by shan9971** [inspireui/support#2037]
Hi,
My Fluxstore APP shows an "Exception: No Route was found matching the Request URL and Method" but user is created in wordpress can you please guide me about this?

![Screenshot_1581024859](https://user-images.githubusercontent.com/60758566/73980636-78bcb380-4952-11ea-8a27-de3add763776.png)

**Comment by inspireui-support** [comment]
Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads  it's used to verify your proof of purchase? sorry for any inconvenience - Thank you!

**Comment by shan9971** [comment]
![PURCHASE](https://user-images.githubusercontent.com/60758566/74053701-2d5fdf00-49fe-11ea-9ec8-885a4e3ba4bc.jpg)
Purchase Proof

**Comment by inspireui-support** [comment]
@minhtruong315 - please help for checking

**Comment by inspireui-support** [comment]
@shan9971 - could you take the proof purchase from http://codecayon.net/downloads  again as you screenshot issue is taken by the Fluxstore Multi Vendor ?

**Comment by shan9971** [comment]
![PROOF](https://user-images.githubusercontent.com/60758566/74138258-19d99180-4c13-11ea-8d64-ec0bb55f9a4f.png)

**Comment by minhtruong315** [comment]
@shan9971 did you upgrade MStore Api plugin to the latest version?

**Comment by shan9971** [comment]
No, I am not using Latest as this just remove JSON API and I want to use JSON API in my APP

**Comment by minhtruong315** [comment]
@shan9971 We updated Fluxstore by the latest MStore Api plugin. so you need to update MStore Api to work. You still can install the latest MStore Api and JSON Api together

**Comment by shan9971** [comment]
OK Thanks
I am thinking about buying Fluxstore Pro is there any difference in Fluxstore and Fluxstore Pro?

**Comment by Brdnn** [comment]
@shan9971 is your issue fixed? I am still facing the same issue after update to latest MStore Api plugin.

**Comment by inspireui-support** [comment]
@shan9971 - the fluxstore pro is support more Magento and Opencart framework.

@Brdnn  - pls update the latest fluxstore and mstore-api to fix the login problem

Let us know if you have any extra issues - thank you!
