### ISSUE TITLE
[Fluxstore - Listing] - Build Stopping Error

### ISSUE THREAD

**Issue by DayneLinx** [inspireui/support#2039]
1. My issue:
I have a build stopping error. I have the latest dependencies and copy of the App. 
<img width="2101" alt="Screenshot 2020-02-05 at 20 36 50" src="https://user-images.githubusercontent.com/23277612/73992620-96d0e680-4947-11ea-9c9e-25481eb00618.png">
![Screenshot 2019-12-13 at 10 23 47](https://user-images.githubusercontent.com/23277612/73992639-a3553f00-4947-11ea-85a7-84c7335f5ce2.png)

2. Screenshots issues:
https://drive.google.com/open?id=1sVyCaH6B7W84MH3xhwt0K4OntF_Gpq3Q
3. Proof of my purchased:
https://drive.google.com/open?id=1vZ8ffMVbLVqk0qtfT6peMnWIWakEDD2j
3. Config files (optional)

**Comment by inspireui-support** [comment]
@DayneLinx - we could not see the screenshot, could you drag the image as the attachment on this ticket - thanks

**Comment by DayneLinx** [comment]
No Problem. Please find them attached. I attached them before but I don't know what happened why they were not visible.

<img width="2101" alt="Screenshot 2020-02-05 at 20 36 50" src="https://user-images.githubusercontent.com/23277612/74028877-57d07e80-49a3-11ea-8776-86d8d094a51b.png">
<img width="806" alt="Screenshot 2019-12-02 at 18 53 48" src="https://user-images.githubusercontent.com/23277612/74028985-8c443a80-49a3-11ea-8c19-ee0a948bbe7c.png">

**Comment by inspireui-support** [comment]
@DayneLinx - could i check if you could able run the example smoothly from this guide - https://flutter.dev/docs/get-started/test-drive?tab=vscode

Also check this script to clean cache:
```
flutter clean
```

And use stable flutter:
```
flutter channel stable
flutter upgrade --force
```

Let us know your checking 😊

**Comment by DayneLinx** [comment]
The test drive works perfectly fine. I am still encountering this issue. 
<img width="3052" alt="Screenshot 2020-02-09 at 14 50 06" src="https://user-images.githubusercontent.com/23277612/74104317-8e48fd80-4b4b-11ea-8791-ff784f87378f.png">

**Comment by DayneLinx** [comment]
Figured out the issue. It will have to be added to the next update probably. It was a change in the latest version of Flutter

>   WidgetsFlutterBinding.ensureInitialized(); 

`void main() {
  // add this, and it should be the first line in main method
  WidgetsFlutterBinding.ensureInitialized(); 

  // rest of your app code
  runApp(
    MaterialApp(...),
  );
}`

**Comment by inspireui-support** [comment]
@DayneLinx - thank you so much for your sharing, I've reported to the technical team for checking and keep update this fixing on next release - very best 😊
