### ISSUE TITLE
[FLUXLISTING] - error: Target of URI doesn't exist: '../../common/constants.dart'. (uri_does_not_exist at [fstore] lib\common\config.dart:2)

### ISSUE THREAD

**Issue by macbethm** [inspireui/support#2040]
Hi 

I get attached error Please help

![Downloads](https://user-images.githubusercontent.com/53470387/74004486-f00c3a80-4986-11ea-96fc-a118a73e69de.JPG)
![error](https://user-images.githubusercontent.com/53470387/74004490-f3072b00-4986-11ea-889b-657b6e0686ca.JPG)

**Comment by inspireui-support** [comment]
@macbethm - please try to change 
```
import '../common/constants.dart'
```

(remove .../)

**Comment by macbethm** [comment]
Thanks, do u normally take your time to test before releasing these apps?

**Comment by inspireui-support** [comment]
@macbethm - yes we have the QC team to take care these things

Actually we may consider changing the example build file to txt on later release as it could be breaking the whole build if we keep the import '../common' from the example folder.

**Comment by macbethm** [comment]
Hi,

This is very annoying for sure, and thus why i asked you if you normally
test ur apps. You updated this app and i thought you fixed everything for
listingpro but still bellow issues exist


   - No Social links shown on detail listing (Even if the listing has
   social links, it does display them)
   - The Claimed badge - not displayed
   - Number of reviews not displayed
   - Signing in with facebook it is just loading and it wont finish
   - Instead of showing Listing features it shows tags
   - No price range is shown
   - It does not show the featured badge on listing
   - No reviews count displayed
    BIZYCITI 01.zip
   <https://drive.google.com/file/d/121KVBZk5wVtdYqgvKPJ7llkkgeHxzjfR/view?usp=drive_web>

Please help to fix these issues

**Comment by Winsima** [comment]
Same errors here..
