### ISSUE TITLE
[fluxstore] - putting products in home

### ISSUE THREAD

**Issue by Saifahmad99** [inspireui/support#2041]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: I want to add my categories product on home screen. Just like you have men and women in your demo app.

2. Screenshots issues:
![Screenshot (52)](https://user-images.githubusercontent.com/59877416/74019072-02a16680-49bd-11ea-87d8-a08f61c2f826.png)
![Screenshot_2020-01-23-19-05-35-260_com celkart store](https://user-images.githubusercontent.com/59877416/74019102-0e8d2880-49bd-11ea-82f7-49404d33f027.jpg)

3. Proof of my purchased:
![Screenshot (32)](https://user-images.githubusercontent.com/59877416/74019153-29f83380-49bd-11ea-8e61-5d1657eaf84a.png)

3. Config files (optional)

**Comment by Saifahmad99** [comment]
MY CINFIG.JSON FILE



{
  "HorizonLayout": [
    {
      "layout": "logo",
      "showMenu": true,
      "showSearch": true
    },
    {
      "layout": "bannerImage",
      "items": [
        {
          "image": "https://www.celkart.com/wp-content/uploads/2020/01/Grand-Opening-SALE.png",
          "padding": 0.0
        }
      ]
    },
    {
      "layout": "bannerImage",
      "items": [
        {
          "image": "https://www.celkart.com/wp-content/uploads/2020/01/ApglH1580114991-scaled.jpg",
          "padding": 0.0
        }
      ]
    },
    {
      "layout": "bannerImage",
      "items": [
        {
          "url": "https://www.celkart.com/free-delivery",
          "image": "https://www.celkart.com/wp-content/uploads/2020/01/free-delivery-on-all-orders.png",
          "padding": 0.0
        }
      ]
    },
    {
      "layout": "bannerImage",
      "items": [
        {
          "image": "https://www.celkart.com/wp-content/uploads/2020/01/OUR-BRAND.png",
          "padding": 0.0
        }
      ]
    },
    {
      "layout": "bannerImage",
      "items": [
        {
          "url": "https://www.celkart.com/micronic",
          "image": "https://www.celkart.com/wp-content/uploads/2019/11/Micronocfinal.png",
          "padding": 0.0
        }
      ]
    },
    {
      "layout": "bannerImage",
      "items": [
        {
          "image": "https://www.celkart.com/wp-content/uploads/2020/01/FIX-YOUR-PHONE-2.png",
          "padding": 0.0
        }
      ]
    },
    {
      "layout": "bannerImage",
      "items": [
        {
          "url": "https://www.celkart.com/fix-your-phone/",
          "image": "https://www.celkart.com/wp-content/uploads/2020/01/SXfly1580117371-1-scaled.jpg",
          "padding": 0.0
        }
      ]
    },
    {
      "layout": "bannerImage",
      "items": [
        {
          "url": "https://www.celkart.com",
          "image": "https://www.celkart.com/wp-content/uploads/2020/01/1657-scaled.jpg",
          "padding": 0.0
        }
      ]
    },
    {
      "layout": "bannerImage",
      "items": [
        {
          "image": "https://www.celkart.com/wp-content/uploads/2020/01/DESIGN-YOUR-OWN-PHONE-CASE-2.png",
          "padding": 0.0
        }
      ]
    },
    {
      "layout": "bannerImage",
      "items": [
        {
          "url": "https://www.celkart.com/Design-phone-case",
          "image": "https://www.celkart.com/wp-content/uploads/2020/01/w2XZ31580118044.png",
          "padding": 0.0
        }
      ]
    },
    {
      "layout": "bannerImage",
      "items": [
        {
          "url": "https://www.celkart.com/fast-delivery",
          "image": "https://www.celkart.com/wp-content/uploads/2020/01/Delivery-in-less-than.png",
          "padding": 0.0
        }
      ]
    },
    {
      "layout": "bannerImage",
      "items": [
        {
          "image": "https://www.celkart.com/wp-content/uploads/2020/01/COMING-SOON-2.png",
          "padding": 0.0
        }
      ]
    },
    {
      "layout": "bannerImage",
      "items": [
        {
          "url": "https://www.celkart.com",
          "image": "https://www.celkart.com/wp-content/uploads/2019/12/silver-iphone-x-with-airpods-788946.jpg",
          "padding": 0.0
        }
      ]
    },
    {
      "layout": "bannerImage",
      "items": [
        {
          "url": "https://www.celkart.com",
          "image": "https://www.celkart.com/wp-content/uploads/2019/12/oneplus-smartphone-black-and-white-sim-63690-4.jpg",
          "padding": 0.0
        }
      ]
    },
    {
      "layout": "bannerImage",
      "items": [
        {
          "url": "https://www.celkart.com/easy-returns",
          "image": "https://www.celkart.com/wp-content/uploads/2020/01/Easy-Returns.png",
          "padding": 0.0
        }
      ]
    },
    {
      "name": "Recent View",
      "layout": "recentView"
    },
    {
      "name": "Products",
      "layout": "twoColumn"
    },
    {
      "name": "Screen Guards",
      "image": "   ",
      "layout": "twoColumn",
      "category": 5,
      "isSnapping": true
    },
    {
      "name": "Pendrives",
      "image": "",
      "layout": "twoColumn",
      "category": 21,
      "isSnapping": true
    },
    {
      "name": "Our Blog Posts",
      "layout": "blog"
    },
    {
      "name": "New Comers",
      "layout": "staggered",
      "limit": 20,
      "category": 29
    }
  ],
  "Setting": {
    "MainColor": "#000000",
    "ProductListLayout": "list"
  },
  "TabBar": [
    {
      "layout": "home",
      "label": "Home",
      "icon": "assets/icons/tabs/icon-home.png"
    },
    {
      "layout": "category",
      "label": "Category",
      "categoryLayout": "card",
      "icon": "assets/icons/tabs/icon-category.png"
    },
    {
      "layout": "search",
      "label": "Search",
      "icon": "assets/icons/tabs/icon-search.png"
    },
    {
      "layout": "cart",
      "label": "Cart",
      "icon": "assets/icons/tabs/icon-cart2.png"
    },
    {
      "layout": "profile",
      "label": "Setting",
      "icon": "assets/icons/tabs/icon-user.png"
    }
  ]
}

- 

1.

**Comment by inspireui-support** [comment]
@Saifahmad99 - could i check if the category id is matched with your category from the woocommerce side, for example: 
```
{
"name": "Screen Guards",
"image": " ",
"layout": "twoColumn",
"category": 5,
"isSnapping": true
},
```

Id #5 should be the same as on your website. Also made sure the config.dart is updated with the URL and the keys are updated correctly. For more detail please check http://docs.inspireui.com/fluxstore

**Comment by Saifahmad99** [comment]
How do I choose what id it has in woocommerce?

**Comment by Saifahmad99** [comment]
And why the plugin shows this when I try to upload my config_en.json?
![Screenshot (57)](https://user-images.githubusercontent.com/59877416/74081041-751f4e80-4a70-11ea-9bdd-90bf9d1e93a3.png)

**Comment by inspireui-support** [comment]
@Saifahmad99 - could I check if it is happening on the latest mstore-api, this could cause by the permission or something else, we will double check it?

**Comment by Saifahmad99** [comment]
ya I updated to the latest version of mstore API still getting those

**Comment by inspireui-support** [comment]
@minhtruong315 - please help to check the mstore-api issue

**Comment by minhtruong315** [comment]
@Saifahmad99 I messaged you on the skype. pls check

**Comment by Saifahmad99** [comment]
1. Splash screen
2. Facebook login
