### ISSUE TITLE
Fluxstore Multivendor Dokan

### ISSUE THREAD

**Issue by vwakehub** [inspireui/support#2042]
---------

1. My issue:
          1. do outofstock item are not showup in app bydefault ?
          2. Shipping not working Properly .
          3. Search not Working Properly
          4.Street Address is not imported when Auto Address Picker used (Also Google Map is not 
             Showing up , Only Address text is showing )
          5. i am using a snippet on woocommerce , so that user can't place order if the cart value is 
                 less than 99inr and also its show a message on cart page , is it possible that you add 
                some code so that user can't go forward from my cart page if the value is less than 99rs  ( 
                 its important)

3. Proof of my purchased:
![Capture](https://user-images.githubusercontent.com/59481921/74019146-2795d980-49bd-11ea-97a5-fdfd80daa97e.PNG)

**Comment by vwakehub** [comment]
Also plz add me in your private gitlab group my mail id is vivek.arora981@gmail.com

**Comment by inspireui-support** [comment]
@vwakehub - sorry for the late response, could you zip the common folder and share us for checking - also explain more detail screenshot for the issues #1 -> #4 so that we could reproduce the issue - thank you!

**Comment by vwakehub** [comment]
#1 Product in not showing in 2nd Category in App , but same category showing products on site 
    
here is the video of app - https://drive.google.com/open?id=1Rh-r516WUxxD6YVp30ZADP8p3Ya3ie9z

here is the screenshot of same category on site  -
![Print Services Archives - Ozoo](https://user-images.githubusercontent.com/59481921/74239267-8466fc00-4cfd-11ea-92e6-2235637290f2.png)



#2. i am not using any extra plugin for shipping just wocommerce bydefault setting 
        here are condition m using on sites
         if some1 place order below inr 499 they will charged flat 49rs for shipping 
         but if some 1 place order above rs 499 there will be freeshipping means 0rs
 but in app on shipping page it shows both options , even if the cart value is below 499rs

here is the video link -  https://drive.google.com/open?id=16gh8_BhpkZvk--Tp1odLnxChy0_qyeDk

here is the screen shot of site  -  
![shipping problem](https://user-images.githubusercontent.com/59481921/74239625-3b637780-4cfe-11ea-9f5e-7412aac29d62.png)


#3 searching is not working as it have to be  , i searched same keyword on site and app

on site its showing perfect result look at this - 
![search on site ](https://user-images.githubusercontent.com/59481921/74239813-a14fff00-4cfe-11ea-998e-0ed301b02b06.PNG)

but in app its not working look at this video - https://drive.google.com/open?id=110FDvY2ofdtso82uhCit6CGW6Kwk9rVl




-------and also this one is very important too------------
5. i am using a snippet on woocommerce , so that user can't place order if the cart value is
less than 99inr and also its show a message on cart page , is it possible that you add
some code so that user can't go forward from my cart page if the value is less than 99rs 
like this on website  - 
![csali](https://user-images.githubusercontent.com/59481921/74240393-e7f22900-4cff-11ea-965f-be2a3d3bd174.png)

--------------------------
i have talked about it with @minhtruong315  he said that you will provide this feature in future update and if i want it right now the i have to contact support@inspireui.com his boss if @inspireui-support  you are boss then please tell me how can i do this ?

**Comment by vwakehub** [comment]
also i have shared (https://github.com/vwakehub/ozooflutter) my private repo with you , i dont want to share comman folder zip in public

**Comment by minhtruong315** [comment]
1. do outofstock item are not showup in app bydefault ?
https://tppr.me/KY2w0
I see it's showing

**Comment by minhtruong315** [comment]
2. Shipping not working Properly .
[shipping.mov.zip](https://github.com/inspireui/support/files/4193219/shipping.mov.zip)
I see it's showing

**Comment by minhtruong315** [comment]
[product.mov.zip](https://github.com/inspireui/support/files/4193232/product.mov.zip)
products are showing

**Comment by vwakehub** [comment]
plz don't close tickets like , atleast you can ask that everything fixed or not !!

**Comment by vwakehub** [comment]
After changing code with the files you provided 
Print Product are showing , but every other product is out of stock 
![WhatsApp Image 2020-02-13 at 9 46 52 PM](https://user-images.githubusercontent.com/59481921/74454922-9d60e000-4eaa-11ea-892f-aad3d6cbdacf.jpeg)


also in dark theme cart icon is not matching with ui

![WhatsApp Image 2020-02-13 at 9 46 46 PM](https://user-images.githubusercontent.com/59481921/74455006-b9fd1800-4eaa-11ea-9c53-2e0888ea888e.jpeg)

**Comment by vwakehub** [comment]
@minhtruong315  

Please give reply on skype !!.
