### ISSUE TITLE
[MStore Pro] - Payments Methods doesn't work

### ISSUE THREAD

**Issue by gonzalobarria** [inspireui/support#2043]
1. My issue: I cannot pay any product, when I press Confirm Order opens a blank window. I have 4 gateways, Paypal, Stripe, Authorize.net and Conekta and noone works. I put the same issue 12 days ago and I don't have a answer yet! You ask me to open a new one without solve the oldest one. Further now I cannot login with user and password in the app to pay.  I WANT MY MONEY BACK

2. Screenshots issues: 
https://ibb.co/fQYNkY7

3. Proof of my purchased:
https://ibb.co/2ZKf2Lm

3. Config files (optional)

**Comment by inspireui-support** [comment]
Hi pls submit this link - https://help.market.envato.com/hc/en-us/articles/202821460-Can-I-Get-A-Refund- - thanks
