### ISSUE TITLE
[MSTORE EXPO] - loading custom font

### ISSUE THREAD

**Issue by kiamoz** [inspireui/support#2044]
fontFamily "SBOLD" is not a system font and has not been loaded through Font.loadAsync.

- If you intended to use a system font, make sure you typed the name correctly and that it is supported by your device operating system.

- If this is a custom font, be sure to load it with Font.loadAsync.

thanks in advance .

**Comment by kiamoz** [comment]
here is 
![Screen Shot 2020-02-07 at 6 19 06 PM](https://user-images.githubusercontent.com/10494372/74039238-bcf19780-49d6-11ea-85aa-1f4c4aa6907e.png)

**Comment by luyx2412** [comment]
HI @kiamoz Can you send me the screenshot error? And please make sure uninstall and reinstall expo app again to load assets. You can read the document to understand more https://docs.expo.io/versions/latest/guides/using-custom-fonts/

Thanks.

**Comment by kiamoz** [comment]
I just use  as your code , just add new one as like as  screen shot , no error , just in reactrtron see this log ,  could you connect me in teamviwer as like as last time ? @luyx2412  
thanks

**Comment by luyx2412** [comment]
Hi @kiamoz sorry about reply you late. Can you send me specific error log? And i could not connect via teamviewer right now.

Thanks

**Comment by kiamoz** [comment]
@luyx2412 font not  embeded in expo ! :(
<img width="726" alt="Screen Shot 2020-02-11 at 8 25 37 PM" src="https://user-images.githubusercontent.com/10494372/74259204-c481ab00-4d0c-11ea-914b-589bb309e24e.png">

**Comment by luyx2412** [comment]
Hi @kiamoz Can you send me your AppConfig.json and Config.js file?

Thanks

**Comment by kiamoz** [comment]
[Archive.zip](https://github.com/inspireui/support/files/4189948/Archive.zip)
 @luyx2412   Here you go, thanks .
