### ISSUE TITLE
[MS Store Opencart ] -  Size (option) 

### ISSUE THREAD

**Issue by valik1702** [inspireui/support#2045]
I need to show the product sizes (from option in opencart), is there any feature in the application ?  how to do this?

**Comment by inspireui-support** [comment]
Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads  it's used to verify your proof of purchase? sorry for any inconvenience - Thank you!

**Comment by valik1702** [comment]
Yes, please https://dropmefiles.com/nzaOZ  I need to show the product sizes (from option in opencart) https://dropmefiles.com/D6YUN

**Comment by inspireui-support** [comment]
Sorry we could not read the file - could you mind to drag the file here - thank you!

**Comment by valik1702** [comment]
Yes, please  I need to show the product sizes (from option in opencart) is there any feature in the application ? how to do this? 
![options1](https://user-images.githubusercontent.com/60794998/74369308-7389b980-4dd5-11ea-987f-c1b1231477b4.png)
![options](https://user-images.githubusercontent.com/60794998/74369315-74bae680-4dd5-11ea-9790-9d8d2d7c79ab.png)
![codecanyon](https://user-images.githubusercontent.com/60794998/74369316-75537d00-4dd5-11ea-8222-41cb897db340.png)

**Comment by inspireui-support** [comment]
@valik1702 - I've checked with the team and they report the product option is not available on the current release, you can customize the app to display this feature - thank you!

**Comment by dahmsh** [comment]
Does it work on size and size options currently in the latest version?
This characteristic is very necessary and important
