### ISSUE TITLE
[my-product] - Fluxstore Multi Vendor - Flutter E-commerce Full App

### ISSUE THREAD

**Issue by nucl123** [inspireui/support#2046]
Purchase : https://prnt.sc/qz5qoi

Hi,
we followed the tutorial exactly and opened the source code folder in android studio, setup flutter, dart , path etc.. was able to run a sample hello world app in device as well as simulator,
but whenever we try to open the fluxstore project, it is stuck at 

Running Gradle task 'assembleDebug'...

have been trying since 2 - 3 hrs.. 
we tried package get, and it exited with code 0
Running "flutter pub get" in source...                              2.5s
Process finished with exit code 0

 checked the path of flutter and dart sdk, and tried what ever all that was found online.. without any luck.

please help, as we need to solve the issue asap to submit the prototype to client with in next 12 hrs..

thanks in advance.

> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:

2. Screenshots issues:

3. Proof of my purchased:

3. Config files (optional)

**Comment by inspireui-support** [comment]
@nucl123 - sorry for the late response as we could not online over the weekend, could I check if you could run the app so far? Thank you!

**Comment by minhtruong315** [comment]
@nucl123 add my skype: minhtruong315
I'll help u run app via teamviewer
Thanks

**Comment by nucl123** [comment]
Hi
Thanks for the reply,
we will text you soon,

**Comment by nucl123** [comment]
Hi we have been trying to contact over skype, there are 3 contacts found by searching this id, but none replied. which is your id? please check it and reply, we have to fix this issue very urgently.
thanks
![fluxstore](https://user-images.githubusercontent.com/51371138/75038607-bdeef280-54c7-11ea-8b18-1c9c5bcdbc26.PNG)

**Comment by minhtruong315** [comment]
I messaged on the skype. pls reply

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!

**Comment by mamunag8** [comment]
Please accept my skype id rezamm.bd
