### ISSUE TITLE
Connect website to tools

### ISSUE THREAD

**Issue by mariablomberg** [inspireui/support#2047]
1. My issue:
CeBuilder didn't work for me so I did setup through expo. I have all the things working but don't know how to create a project that's connected to my actual website edible.co2diet.org and not a blank template. 

2. Screenshots issues:
--

3. Proof of my purchased:
56c14546-d8ea-4024-9a11-20c549cda35a

**Comment by minhtruong315** [comment]
[AppConfig.json.zip](https://github.com/inspireui/support/files/4181518/AppConfig.json.zip)
try this file then run again
