### ISSUE TITLE
[FLux news] - The app is slow and not stable 

### ISSUE THREAD

**Issue by sharkcrypto92** [inspireui/support#2048]
1. Hello Team i have released the app and once i run it in my andorid phone loading takes while and then when i post new post i try to pull reload not showing the new post i have to close the app and re open it to i can see it 

and sometime categories appear randomly upon reloading 

do you know how to speed it ? because thats will affect on users for sure 
![WhatsApp Image 2020-02-08 at 12 24 34](https://user-images.githubusercontent.com/42117836/74082893-95024280-4a6f-11ea-923f-1509eea302d9.jpeg)
 

2. Screenshots issues:

3. Proof of my purchased:

3. Config files (optional)

**Comment by inspireui-support** [comment]
@sharkcrypto92 - pls check this guide - https://docs.inspireui.com/fluxstore/performance/

Could you share website as well, most of the performance issues will cause by your hosting and heavey image loading

**Comment by sharkcrypto92** [comment]
Step 3: Go to Fluxstore project folder lib/common/config.dart, update "isCaching": true (this value is set from kAdvanceConfig). Then rebuild the app and enjoy new Super-Speed app.

there is no isCaching in fluxnews config.dart 

and my website is alriadey.com i talked to host they said its fast and issue from the app

**Comment by inspireui-support** [comment]
could you zip the common folder and send us for further investigating - thanks

**Comment by sharkcrypto92** [comment]
https://workupload.com/file/HRjY6ZAd


note : i added the  "isCaching": true
under : kAdvanceConfig

**Comment by sharkcrypto92** [comment]
anything new ?

**Comment by dttrung26** [comment]
Hi @sharkcrypto92 , could I download your app to test? So far so good, your common folder still suits well with FluxNews. For furthur assistance, contact me via skype dttrung.ityu.
