### ISSUE TITLE
[MStore] Checkout Page - Invalid authentication cookie

### ISSUE THREAD

**Issue by fthkrtl35** [inspireui/support#205]
**Mandatory Info (please complete the following information):**
 - Product: MStore
 - Your Purchased Code: 8e06cc57-6afe-441f-9acb-a8adb1a77f3c

**Describe the issues**
When the application opens the webview for the payment page with the credit card, I get a blank page. It also warns that "Invalid authentication cookie. Please try to login again."
Tried this solution but not working, also AnonymousCheckout is true
https://docs.mstore.io/faq-and-troubleshooting#404-error-page-when-process-the-payment

**Comment by minhcasi** [comment]
Noted for investigating - thanks

**Comment by SAVICTOR** [comment]
i have this problem too. 
Regular LicensePurchase code: ed1b502c-bf88-463b-a2b3-141448ce8a20
Invalid authentication cookie on checkout 
and also when uploading products

**Comment by SAVICTOR** [comment]
But it works when i use facebook login, been slowing me down.  I hope for a quick reply. Thanks mate

**Comment by fthkrtl35** [comment]
Can you give us information about the next update date

**Comment by luyx2412** [comment]
Hi @fthkrtl35 We are planning new version, and update ASAP. 

Thanks

**Comment by AbdullahNabta** [comment]
I am having the same problem what do it do for now?

**Comment by rf1804** [comment]
Same issue

**Comment by rf1804** [comment]
@luyx2412 any updates?

**Comment by sashaba** [comment]
Same issue here with anonymous checkout true.

**Comment by cybdom** [comment]
I have the same issue, Invalid authentication cookie HELP
