### ISSUE TITLE
mv-mstore -  Issues with registering users throgh the app

### ISSUE THREAD

**Issue by khalidsharif** [inspireui/support#2050]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:

Unable to create new users/vendors from the app itself 
*Note: Dokan plugins installed in the WordPress backend
2. Screenshots issues:
https://vimeo.com/390259698
3. Proof of my purchased:
https://ibb.co/d40dKnD
3. Config files (optional)

**Comment by Tayeb-Ali** [comment]
same issues

**Comment by inspireui-support** [comment]
@khalidsharif - could you help to zip the common folder and attache here so that we could help for checking - thank you!

**Comment by khalidsharif** [comment]
here is the common folder
https://www.dropbox.com/s/ck3nr9wfr9dy1jw/common.zip?dl=0

**Comment by Tayeb-Ali** [comment]
Hello.
I have found the problem, In src\services\WPUserAPI Class.
Because this getNonce function does not work, and it returns "undefined".
I am working now to find a solution

**Comment by Tayeb-Ali** [comment]
> Hello.
> I have found the problem, In src\services\WPUserAPI Class.
> Because this getNonce function does not work, and it returns "undefined".
> I am working now to find a solution

Sorry this issues from host check php V and mod_security.

**Comment by khalidsharif** [comment]
> > Hello.
> > I have found the problem, In src\services\WPUserAPI Class.
> > Because this getNonce function does not work, and it returns "undefined".
> > I am working now to find a solution
> 
> Sorry this issues from host check php V and mod_security.

Tayeb, you mean we have to make changes within php.ini ?!

**Comment by Tayeb-Ali** [comment]
> > > Hello.
> > > I have found the problem, In src\services\WPUserAPI Class.
> > > Because this getNonce function does not work, and it returns "undefined".
> > > I am working now to find a solution
> > 
> > 
> > Sorry this issues from host check php V and mod_security.
> 
> Tayeb, you mean we have to make changes within php.ini ?!

no 
update to 7.1 or a pouf . 
check security mod in host .
clear cache and cookies  .
it work 
may you want run in dev mode and 
print some of test message to check the problem.
like 
alert(jsone) in  src\services\WPUserAPI .

**Comment by luyx2412** [comment]
Hi @khalidsharif We will upload new version which fixed the issue tomorrow.

Thanks
