### ISSUE TITLE
Cannot setup fluxstore multivendor app and change or edit theme

### ISSUE THREAD

**Issue by Rakiborv** [inspireui/support#2051]
Hi,
I have tried alot of ways available online and also looked in to solutions from other issues in this supports but its not working for me.

I have changed the config.json with theme config_theme10.json and several other theme codes, and so on etc but it would still run with the basic theme. It is almost like its hard coded. I have also tried uploading the config.json file in the mstore api and cleared the wp_REST_cache. Still keeps showing the same demo theme. I can't find out which file the page details are being pulled from. Similarly for splashscreen. I have designed a different splashscreen but only my logo is showing up.

Also, for my multivendor I have followed the guide doc and setup WCFM, connected my woocommerce site, but cannot seem to create new vendor stores or add and manage product from the app. Please help me on this. My vendors need to manage their store from the app.

Screenshot of Issue: The theme that never changes.
![Screenshot_2020-02-10-09-30-26-844_com paikaribazaar store](https://user-images.githubusercontent.com/22408797/74119194-aae74300-4be8-11ea-920c-f59e0ddeb376.jpg)

Screenshot of wrong splashscreen :
![Screenshot_2020-02-10-09-30-09-277_com paikaribazaar store](https://user-images.githubusercontent.com/22408797/74119255-e124c280-4be8-11ea-86fd-444fb947ab04.jpg)

common config file zip:
[common.zip](https://github.com/inspireui/support/files/4178832/common.zip)

proof of purchase:
![image](https://user-images.githubusercontent.com/22408797/74119325-25b05e00-4be9-11ea-829c-c318c3bd2ed7.png)

**Comment by inspireui-support** [comment]
@Rakiborv - could you zip the common folder and send to minhtruong315@gmail.com - we will help for checking the integration on your site - thank you!

**Comment by minhtruong315** [comment]
@Rakiborv you should change config_en.json if you're using default English language.
Did you try to sign up but it don't work?

**Comment by Rakiborv** [comment]
Hi thanks for looking into this and for your
quick response. The default language was set as english in the source code
from the beginning its not like I changed it. Also I dont want to use the
default language as english, there will be 3 languages mostly used based on
my target locations. What should I do to make the theme change dependent on
the config.json just like the videos I saw on the internet?

**Comment by Rakiborv** [comment]
Also if I want to sign up just as a vendor and tick the register as a
vendor option, It says please agree with our terms, but there is not terms
and conditions option to select. If I want to just create an account as a
normal user and tick the first option only then it works, for vendor also I
have to tick both to register successfully. But its not exactly accurate.

**Comment by minhtruong315** [comment]
@Rakiborv if you have two languages English and Arabic in your app. you need 2 config json files config_en.json and config_ar.json. You must to edit these json files. you don't need to edit config.json file

**Comment by Rakiborv** [comment]
Hi thanks a lot the help , theme change by changing the language config
json files worked.

I have been able to change theme. I need help setting up  WCFM to the app
successfully, i have looked into the docs and also wcfm docs. I have
installed the wcfm rest api plugin, all the required plugins, entered the
consumer and secret key  on the woocommerce. I cannot create or setup new
store, or manage store profile like name and logo from the app and see it
the stores section.

I have also changes the category ids in the theme to my categories but
clicking on the see all shows zero products.

Would it be possible to include a wallet, sales amount and store
Personalization features like logo, Store name, and store report in your
future releases. Thank you so much for all your help.

**Comment by inspireui-support** [comment]
@Rakiborv - thank you for the feedback, we will consider upgrading more feature for the Vendor function on later releases - very best!

**Comment by stickypages** [comment]
> Also if I want to sign up just as a vendor and tick the register as a vendor option, It says please agree with our terms, but there is not terms and conditions option to select. If I want to just create an account as a normal user and tick the first option only then it works, for vendor also I have to tick both to register successfully. But its not exactly accurate.


I too have this issue.
