### ISSUE TITLE
Problem in New Version 1.6.3 Fluxstore WooCommerce - Flutter E-commerce Full App 

### ISSUE THREAD

**Issue by RKDArora** [inspireui/support#2052]
Sir,

I download the new version 1.6.3

I got the following issues with Magento-

1. Logout not working from main left side menu.
2. order history blank black screen when press back.
3. not able to place final order at last. It giving error at attached in file. When I checked at website the order is placed but adding into cart again and again.
i.e. cart not empty due to error received "unexpected error (at character 1)....".

Thanks

Rajesh

**Comment by inspireui-support** [comment]
Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads  it's used to verify your proof of purchase? sorry for any inconvenience - Thank you!

**Comment by RKDArora** [comment]
Sir,

PFA purchase proof.

Thanks

**Comment by inspireui-support** [comment]
Could you drag the screenshot here as I could not see it - thank you for your patience - very best!

**Comment by RKDArora** [comment]
Sir,

PFA.

Thanks

**Comment by inspireui-support** [comment]
Hi, we could not get the attache image, could you drag it again - thanks

**Comment by RKDArora** [comment]
Sir,

PFA.

Thanks
