### ISSUE TITLE
[FLUXLISTING] - Listingpro not working as expected

### ISSUE THREAD

**Issue by macbethm** [inspireui/support#2053]
This is very annoying for sure, and thus why i asked you if you normally test ur apps. You updated this app and i thought you fixed everything for listingpro but still bellow issues exist

No Social links shown on detail listing (Even if the listing has social links, it does display them)
The Claimed badge - not displayed
Number of reviews not displayed
Signing in with facebook it is just loading and it wont finish
Instead of showing Listing features it shows tags
No price range is shown
It does not show the featured badge on listing
No reviews count displayed

Please help to fix these issues

![image](https://user-images.githubusercontent.com/53470387/74128022-3d89e100-4bed-11ea-86ad-8d699d1cae58.png)

**Comment by philipvu30** [comment]
Hi @macbethm ,

I am truly sorry for any inconvenience we have caused. 
Would you please send me a support account for your website and the common folder to this email: toan@inspireui.com. I'll assist you on fixing your issues asap I receive those. Thank you for your understanding.

**Comment by macbethm** [comment]
Thanks for the quick response, i have sent an email already @philipvu30

**Comment by philipvu30** [comment]
I received the files. Thank you @macbethm

**Comment by philipvu30** [comment]
Hi @macbethm,

The folder you sent me does not have what I need. Please send me the common folder only or just these 2 files: config.dart and config.json. Thank you

**Comment by macbethm** [comment]
file shared

**Comment by macbethm** [comment]
Are you working on it ?

**Comment by philipvu30** [comment]
@macbethm yeah already on it.

**Comment by philipvu30** [comment]
Hi @macbethm ,
Did the file I give you solved your issues? Is there anything else I can help you with? Otherwise I'll mark this as Closed.

You can contact me through Skype: vuthanhtoan30
