### ISSUE TITLE
[Fluxstore - multi vendors] Duplicate GlobalKey detected in widget tree.

### ISSUE THREAD

**Issue by abd096** [inspireui/support#2054]
hello,

i am having the following issue every time i do login or register in the app:

Error screenshot: https://prnt.sc/r03bym
Purchase code: https://prnt.sc/r03dpe

Error message:

════════ (2) Exception caught by widgets library ═══════════════════════════════════════════════════
Multiple widgets used the same GlobalKey.
The relevant error-causing widget was: 
  MaterialApp file:///C:/Users/abd_0/Documents/ABD/Design/Projects/Min%20Aldar/FluxStore-vendor-1.6.3/source/lib/app.dart:268:20
════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (30496): [Fluxstore][AppState] build
I/flutter (30496): [Fluxstore][Tabbar] build
I/flutter (30496): [Fluxstore][Home] build

════════ (3) Exception caught by widgets library ═══════════════════════════════════════════════════
Multiple widgets used the same GlobalKey.
The relevant error-causing widget was: 
  MaterialApp file:///C:/Users/abd_0/Documents/ABD/Design/Projects/Min%20Aldar/FluxStore-vendor-1.6.3/source/lib/app.dart:268:20
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (4) Exception caught by widgets library ═══════════════════════════════════════════════════
Duplicate GlobalKey detected in widget tree.
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by trunghieuvn** [comment]
hello @abd096 
please provided step reproduce bug?

**Comment by abd096** [comment]
hello, 

i am sorry but how am i getting it?

**Comment by abd096** [comment]
actually i already posted the error as well as a screenshot of it

**Comment by trunghieuvn** [comment]
Hello, you can try changing this line of code in `lib/tabbar.dart`

from:
```
static final GlobalKey<MainTabsState> keyNavigationTabbar = GlobalKey(debugLabel: 'homePageKey');
```
to:
```
static final GlobalKey<MainTabsState> keyNavigationTabbar = GlobalKey<MainTabsState>();
```

![image](https://user-images.githubusercontent.com/19247680/74408626-864cce80-4e67-11ea-9adb-5efca39edf7a.png)

**Comment by abd096** [comment]
i did change it but still giving error:

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown while finalizing the widget tree:
Duplicate GlobalKey detected in widget tree.

The following GlobalKey was specified multiple times in the widget tree. This will lead to parts of the widget tree being truncated unexpectedly, because the second time a key is seen, the previous instance is moved to the new location. The key was:
- [LabeledGlobalKey<MainTabsState>#488d0]
This was determined by noticing that after the widget with the above global key was moved out of its previous parent, that previous parent never updated during this frame, meaning that it either did not update at all or updated before the widget was moved, in either case implying that it still thinks that it should have a child with that global key.
The specific parent that did not update after having one or more children forcibly removed due to GlobalKey reparenting is:
- Semantics(container: false, properties: SemanticsProperties, label: null, value: null, hint: null, hintOverrides: null, renderObject: RenderSemanticsAnnotations#7392d NEEDS-PAINT)
A GlobalKey can only be specified on one widget at a time in the widget tree.
When the exception was thrown, this was the stack: 
#0      BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:2578:15)
#1      BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:2603:8)
#2      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:775:18)
#3      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
#4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (26388): token: fucJnvlc_Fg:APA91bGMA0xL1qj5J0DRn3gOQArPuU1wt4IhuLVxsDblG8xxJKXl6HZ30TZzMeBHD7qUEhXLrz_1Aaulos2yEpJYEc_JChwh0NVnDBgkl3vsii_KNCGgsknku0dmLwG6fxubqPPJwACC
I/flutter (26388): [Fluxstore][Tabbar] build
I/flutter (26388): [Fluxstore][AppState] build
I/flutter (26388): [Fluxstore][Tabbar] build

════════ (2) Exception caught by widgets library ═══════════════════════════════════════════════════
Multiple widgets used the same GlobalKey.
The relevant error-causing widget was: 
  MaterialApp file:///C:/Users/abd_0/Documents/ABD/Design/Projects/Min%20Aldar/FluxStore-vendor-1.6.3/source/lib/app.dart:268:20
════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (26388): [Fluxstore][Home] build

════════ (3) Exception caught by widgets library ═══════════════════════════════════════════════════
Duplicate GlobalKey detected in widget tree.
════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (26388): [Fluxstore][AppState] build
I/flutter (26388): [Fluxstore][Tabbar] build

════════ (4) Exception caught by widgets library ═══════════════════════════════════════════════════
Multiple widgets used the same GlobalKey.
The relevant error-causing widget was: 
  MaterialApp file:///C:/Users/abd_0/Documents/ABD/Design/Projects/Min%20Aldar/FluxStore-vendor-1.6.3/source/lib/app.dart:268:20
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by trunghieuvn** [comment]
Please send me 2 files `lib/app.dart` and `lib/tabbar.dart`

**Comment by abd096** [comment]
[app.zip](https://github.com/inspireui/support/files/4197073/app.zip)

here they are

**Comment by trunghieuvn** [comment]
Hello, please send me file `lib/screens/home.dart` for me to check. Thanks.

**Comment by saidbakkou** [comment]
[my app.zip](https://github.com/inspireui/support/files/4204066/my.app.zip)

**Comment by saidbakkou** [comment]
[my app2.zip](https://github.com/inspireui/support/files/4204073/my.app2.zip)

**Comment by abd096** [comment]
[home.zip](https://github.com/inspireui/support/files/4204618/home.zip)
here it is, home.dart

**Comment by trunghieuvn** [comment]
You can try the Rename Key here:

![image](https://user-images.githubusercontent.com/19247680/74620997-a7fecc00-516d-11ea-8e85-1f0d082bbab9.png)

file `tabbar.dart` , in funtion `tabView`.

**Comment by abd096** [comment]
i did it but it is actually the same 

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown while finalizing the widget tree:
Duplicate GlobalKey detected in widget tree.

The following GlobalKey was specified multiple times in the widget tree. This will lead to parts of the widget tree being truncated unexpectedly, because the second time a key is seen, the previous instance is moved to the new location. The key was:
- [LabeledGlobalKey<MainTabsState>#b414f]
This was determined by noticing that after the widget with the above global key was moved out of its previous parent, that previous parent never updated during this frame, meaning that it either did not update at all or updated before the widget was moved, in either case implying that it still thinks that it should have a child with that global key.
The specific parent that did not update after having one or more children forcibly removed due to GlobalKey reparenting is:
- Semantics(container: false, properties: SemanticsProperties, label: null, value: null, hint: null, hintOverrides: null, renderObject: RenderSemanticsAnnotations#79aa6 NEEDS-PAINT)
A GlobalKey can only be specified on one widget at a time in the widget tree.
When the exception was thrown, this was the stack: 
#0      BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:2578:15)
#1      BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:2603:8)
#2      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:775:18)
#3      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
#4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (15281): token: fWQd8AfFv4g:APA91bFTKfhr5WhFIqBZU9BeWFYaN24pFFmRyDMbhk5JxU-G49jbEEsCKStuF4IGwCIcef2gkcp6Y0fRstV86SWLRfXGRkcJeZRqtb5jO4-6H5LKF_7GENsRMyh03as5TiXbBlZwXGHb
I/flutter (15281): [Fluxstore][AppState] build
I/flutter (15281): [Fluxstore][Tabbar] build

════════ (2) Exception caught by widgets library ═══════════════════════════════════════════════════
Multiple widgets used the same GlobalKey.
The relevant error-causing widget was: 
  MaterialApp file:///C:/Users/abd_0/Documents/ABD/Design/Projects/Min%20Aldar/FluxStore-vendor-1.6.3/source/lib/app.dart:268:20
════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (15281): [Fluxstore][AppState] build
I/flutter (15281): [Fluxstore][Tabbar] build
I/flutter (15281): [Fluxstore][Home] build

════════ (3) Exception caught by widgets library ═══════════════════════════════════════════════════
Multiple widgets used the same GlobalKey.
The relevant error-causing widget was: 
  MaterialApp file:///C:/Users/abd_0/Documents/ABD/Design/Projects/Min%20Aldar/FluxStore-vendor-1.6.3/source/lib/app.dart:268:20
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (4) Exception caught by widgets library ═══════════════════════════════════════════════════
Duplicate GlobalKey detected in widget tree.
════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (15281): screenName /home
I/flutter (15281): [Fluxstore][Tabbar] build
I/flutter (15281): [Fluxstore][Home] build
I/flutter (15281): [Fluxstore][Tabbar] build

**Comment by trunghieuvn** [comment]
Did you run the app and it immediately crashed or did you open any screen? Please let me know the exact steps for generating the error.

For example:

Run app -> Open category screen will see this error.

**Comment by abd096** [comment]
app run perfectly but when i do login or register and then login the error comes.

1- login screen 

2- register a new customer screen

**Comment by trunghieuvn** [comment]
Hi. Please provide the version of WooCommerce Fluxstore you are using.

**Comment by abd096** [comment]
hello,

wordpress: 5.3.2
woocommerce: 3.9.2
Fluxstore: 2.1.5

**Comment by mohafouad** [comment]
> app run perfectly but when i do login or register and then login the error comes.
> 
> 1- login screen
> 
> 2- register a new customer screen

same problem with me

**Comment by trunghieuvn** [comment]
i try reproduce but i can't do it.
please help me provice steps reproduce or video reproduce bug. I will fix bug easier

**Comment by saidbakkou** [comment]
yo guys i just commnted this line on my tabbar.dart and it works 
 // MainTabs({Key key}) : super(key: keyNavigationTabbar);

**Comment by trunghieuvn** [comment]
Because the code above redirects navigabar tabs. Try to fix it like this:

![image](https://user-images.githubusercontent.com/19247680/74658311-91379400-51c4-11ea-81ac-d5c64eca273b.png)

**Comment by mohafouad** [comment]
same problem :(

**Comment by abd096** [comment]
> yo guys i just commnted this line on my tabbar.dart and it works
> // MainTabs({Key key}) : super(key: keyNavigationTabbar);

this works for me @trunghieuvn but changing the code as you mentioned, didnt work!

**Comment by abd096** [comment]
i am having another issue now, after i submit the order it goes to success page then this error comes in the console: 

screenshot : https://prnt.sc/r41ati


════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building:
'package:fstore/widgets/product/product_bottom_sheet.dart': Failed assertion: line 476 pos 12: 'product != null': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

**Comment by trunghieuvn** [comment]
With error ` Duplicate GlobalKey detected in widget tree`, please make the following changes to correct this error:
1.  in `lib/tabbar.dart' remove `keyNavigationTabbar`
![image](https://user-images.githubusercontent.com/19247680/74800369-cac3e880-5305-11ea-97c7-1fce41a2de32.png)

2. in `app.dart' insert `keyHomePage ` and use in function `renderFirstScreen`

![image](https://user-images.githubusercontent.com/19247680/74800401-e9c27a80-5305-11ea-8752-31824c131e30.png)

3. Edit code in page use old key 
![image](https://user-images.githubusercontent.com/19247680/74800457-18405580-5306-11ea-8954-ef834345576b.png)

![image](https://user-images.githubusercontent.com/19247680/74800468-21c9bd80-5306-11ea-9a52-7a7af6f8665c.png)

**Comment by abd096** [comment]
ok thats perfect @trunghieuvn it is working good now.

Can you please help me with the other issue ?

**Comment by trunghieuvn** [comment]
> ok thats perfect @trunghieuvn it is working good now.
> 




Sorry, but this way is not perfect. It may also affect some push route issues. To be able to better manage the route that is not affected by the global key, you can edit it in the following way:

1. Add  class `MainTabControlDelegate` before class `MainTabs` in file `lib/tabbar.dart`

```
...


class MainTabControlDelegate {
  Function(String nameTab) changeTab;
  Function(int index) tabAnimateTo;

  static MainTabControlDelegate _instance;
  static MainTabControlDelegate getInstance() {
    if (_instance == null) {
      _instance = MainTabControlDelegate._();
    }
    return _instance;
  }

  MainTabControlDelegate._();
}

class MainTabs extends StatefulWid ...

```

2. Remove `keyNavigationTabbar` and define function of `MainTabControlDelegate` in functiong `initState`

![image](https://user-images.githubusercontent.com/19247680/74807874-1c776d80-531c-11ea-876c-9846b3b72ddc.png)

3. Edit code in page use old key

![image](https://user-images.githubusercontent.com/19247680/74807950-4cbf0c00-531c-11ea-89cd-ac5d07348799.png)

![image](https://user-images.githubusercontent.com/19247680/74807962-56487400-531c-11ea-82dc-3e3fc48a6f15.png)

------
 
> Can you please help me with the other issue ?

Okay, but I need some more info on this. You can send your source or video steps to create that error so I can easily help you solve this problem.
You can send the necessary information to me by email: hieu.trantrung1204@gmail.com

**Comment by inspireui-tech** [comment]
@abd096 - pls also update to latest 1.6.4 to fix the issue - thank you!
