### ISSUE TITLE
[Fluxstore Listing] - MyListing theme - A couple of troubleshooting questions 

### ISSUE THREAD

**Issue by sfeken15** [inspireui/support#2056]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: 

1. How can we change the top status bar color?
2. How can we change the listing featured image to the MyListing cover image rather than the gallery images?
   - For Example: if (_gallery.length > 0) product.imageFeature = _gallery[0];
3. Is there a way to add a secondary wishlist screen and wishlist icon to each listing? Such as Wishlist and Favorites?
4. On the come screen - Under each category, It says "products" where can I change that term?
5. Are there a list of layouts or screens to choose from for the TabBar and can we link to an external website? I want to add the wishlist to the tabbar and link to the full website.

Thank you for the help!

2. Screenshots issues:

3. Proof of my purchased: 
![image](https://user-images.githubusercontent.com/60324276/74184068-b861f480-4c0b-11ea-9c17-e0b19068131b.png)

3. Config files (optional)

**Comment by philipvu30** [comment]
Hi @sfeken15,

Sorry for late response. As for your issues, you could see the solutions below. Thank you.

1. Change the term "Theme.of(context).accentColor" to "Colors.***". (*** as your color for example: Colors.pink)

![1](https://user-images.githubusercontent.com/54442328/74296838-91283600-4d77-11ea-94fa-7fe9ac9ce3f9.PNG)

2 and 3. Currently the app does not support this kind of changes. We will take note of these features and they might be implemented in the future.

4. Do you mean the screen after clicking See all? If that is the case, you have to change that in 
	- Firstly navigate to lib/generated/i18n.dart -> String get products => "Products" and change the text of "Products". Please note that if you are using language other than English, for example Arabic, you have to navigate to String get products => "منتجات" and change the term in the double quotes.
	- Secondly navigate to res/values/strings_en.arb -> "products" : "Products" and change the second term i.e. "Products". The language rule is also applied for this one, but instead of strings_en.arb you have to navigate to strings_ar.arb

5. I am not quite sure I get what you meant, could you provide an image?

**Comment by sfeken15** [comment]
Thank you!

1 is completed!
2 and 3 completed.
4. Thank you. I have changed a lot of terms now. However, I still have one I can't figure out. See screenshot.
5. In reference to linking to a website.  See screenshots. 

Thank you!

![text80](https://user-images.githubusercontent.com/60324276/74390013-9b712100-4dc5-11ea-90af-d8db46835b33.png)
![text81](https://user-images.githubusercontent.com/60324276/74390018-a035d500-4dc5-11ea-8606-b7a261d8ee12.png)
![path57](https://user-images.githubusercontent.com/60324276/74390102-dd9a6280-4dc5-11ea-9e14-a23e9d8fa9ec.png)

**Comment by sfeken15** [comment]
@philipvu30 See the screenshots, thank you for the help!

**Comment by philipvu30** [comment]
@sfeken15 
1. For the wishlist layout, we are currently not supporting it. 
2. Could you please send me the config.dart and config.json? Thank you

**Comment by sfeken15** [comment]
@philipvu30 

Okay thank you.

Yes I added them to the code. Do the custom menu options need to be added to the config files somehow?

Here are the config.dart and json files.

Thank you!

[config.zip](https://github.com/inspireui/support/files/4196894/config.zip)

**Comment by philipvu30** [comment]
Hi @sfeken15 ,
1. The reason why the number of product does not show up is because the api limits just 100 categories per page. And the ones that don't have the number of product are not included in the page. If you want to change it, then add me on Skype I'll show you how. Because we won't implement this in the future.
2. Also for the link to website part, our app currently doesn't support it.

For further questions, please contact me via Skype: vuthanhtoan30 or email: philipvu@inspireui.com. Thank you
