### ISSUE TITLE
[Fluxstore] - Which file in the source can edit with (Inspector)to customize the   top menu items

### ISSUE THREAD

**Issue by limitlessfirm** [inspireui/support#2057]
1. My issue: Which file in the source can edit with (Inspector)to customize the top menu items ?

2. Screenshots issues:
![top-menu](https://user-images.githubusercontent.com/59250639/74184415-6f339400-4c4f-11ea-8d4c-2ff61a7f3a9c.JPG)

3. Proof of my purchased:
![screenshot](https://user-images.githubusercontent.com/59250639/74184426-75c20b80-4c4f-11ea-88bb-b682693bad18.JPG)

3. Config files (optional)

**Comment by inspireui-support** [comment]
@limitlessfirm - this is the Drawer widget, you can customize at the tabbar.dart - thank you!

**Comment by inspireui-support** [comment]
The Inspector is default plugin from Flutter when you use the Android Studio

**Comment by limitlessfirm** [comment]
I removed (padding) from  (tabbar-version-animate.dart) and (tabbar-version-static.dart) but the items in menu still appear
![top-menu-2](https://user-images.githubusercontent.com/59250639/74237212-b2d3df80-4cdb-11ea-965c-7ad80fcfcd29.JPG)


code removed:
            Padding(
              padding: const EdgeInsets.only(left: 15.0),
              child: Column(
                children: <Widget>[
                  ListTile(
                    leading: Icon(Icons.shopping_basket, size: 20),
                    title: Text(S.of(context).shop),
                    onTap: () {
                      Navigator.pushReplacementNamed(context, "/home");
                    },
                  ),
                  ListTile(
                    leading: Icon(FontAwesomeIcons.wordpress, size: 20),
                    title: Text(S.of(context).blog),
                    onTap: () {
                      Navigator.pushNamed(context, "/blogs");
                    },
                  ),
                  ListTile(
                    leading: Icon(FontAwesomeIcons.heart, size: 20),
                    title: Text(S.of(context).myWishList),
                    onTap: () {
                      Navigator.pushNamed(context, "/wishlist");
                    },
                  ),
                  ListTile(
                    leading: Icon(Icons.exit_to_app, size: 20),
                    title: loggedIn ? Text(S.of(context).logout) : Text(S.of(context).login),
                    onTap: () {
                      loggedIn
                          ? Provider.of<UserModel>(context, listen: false).logout()
                          : Navigator.pushNamed(context, "/login");
                    },
                  ),
                ],
              ),
            )
