### ISSUE TITLE
Connect website to tool (BeoNews Pro )

### ISSUE THREAD

**Issue by nahuelbourdichon** [inspireui/support#2059]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
Hello, I'm having an issue to connected my site https://www.maspuntos.com.ar . I follow the manual https://docs.inspireui.com/beonews/quick-setup/ , but doesn't have enought information , so the c builder didn't connect to my web. apart of that , I would like to get a full manual because fro example i don't know how can i get my consumerKey or consumerSecret.
2. Screenshots issues:
![image](https://user-images.githubusercontent.com/16769047/74197123-85385900-4c3d-11ea-89ad-fd49c022e2d1.png)
and this other is tab customization , it show me a blank site 
![image](https://user-images.githubusercontent.com/16769047/74197199-b4e76100-4c3d-11ea-9570-e2d5bd8bf3c3.png)

3. Proof of my purchased:

BeoNews Pro - React Native mobile app for Wordpress
--
Regular License
Purchase code: 56938ebc-ee61-4e64-963b-1afd80b5b33c

3. Config files (optional)

Regards,
Nahuel

**Comment by nahuelbourdichon** [comment]
Hello To add information I created the consumerKey and  consumerSecret, but it is for Woocommerce  I don't know if it ok..
I add to AppConfig.json this code 
{
  "Website": {
    "url": "https://maspuntos.com.ar",
     "consumerKey": "ck_0abb03e4f37d7058d887913f76a5bc54638xxxxx",
     "consumerSecret": "cs_e7f8a497e83e07c5d706f3249b38e0f38exxxx"
  },
  "Theme": "pharmacy",
  "MainColor": {
    "tabbarTint": "#00B2BC",
    "tabbarColor": "#D5D8DE",
    "mainColorTheme": "#00B2BC",
    "tabbar": "#fff"
  }
}
and doesn't work  it keeps  loading
![image](https://user-images.githubusercontent.com/16769047/74207364-0b649780-4c5e-11ea-8a74-335b4a592bf3.png)

thanks

**Comment by minhtruong315** [comment]
@nahuelbourdichon BeoNews don't need customerKey and customerSecret. But i can't access your website. is it working?

**Comment by nahuelbourdichon** [comment]
yes it ,is working https://www.maspuntos.com.ar/  ,so I need to remove the   customerKey and customerSecret, apart of that , i'm going to check because i believe i set the web to deny allow ip different from Argentina

**Comment by nahuelbourdichon** [comment]
i have not blocked any ip, so you should be available to see my web

**Comment by nahuelbourdichon** [comment]
Sorry do you have some new?
I tried to connect to my site with Ce builder and continue seeing nothing like this image https://user-images.githubusercontent.com/16769047/74197199-b4e76100-4c3d-11ea-9570-e2d5bd8bf3c3.png

I try a lot of thing, but it continue not working
thanks

**Comment by inspireui-support** [comment]
@nahuelbourdichon - sorry for late response, could you help to update the latest cebuilder 0.40 - https://github.com/inspireui/cebuilder/releases there is an issue with the previous that break the API connection - thank you for your patience

**Comment by nahuelbourdichon** [comment]
Hello again sorry, but now the new version doesn't save my project path..
thanks  
![image](https://user-images.githubusercontent.com/16769047/74597449-79ce9e80-503e-11ea-88be-74b04e5bf578.png)

thanks

**Comment by minhtruong315** [comment]
@nahuelbourdichon add my skype: minhtruong315
I'll help u check via teamviewer

**Comment by nahuelbourdichon** [comment]
yes please tell me what is your zone time ? I sent you a private message but i'm not sure if is your account...
thanks

**Comment by minhtruong315** [comment]
@nahuelbourdichon https://tppr.me/wl1OC this is my account. my time zone is +7

**Comment by nahuelbourdichon** [comment]
Hello Are you online ? please can you contact me by skype live:nahuel.bourdichon

**Comment by nahuelbourdichon** [comment]
https://join.skype.com/invite/sLry4Gw1E11P

**Comment by nahuelbourdichon** [comment]
It did not closed i'm continue having the same issue

**Comment by minhtruong315** [comment]
@nahuelbourdichon BeoNews doesn't support BeoNews, it only supports news website. if you want to make shopping app, you should buy MStore

**Comment by inspireui-tech** [comment]
@nahuelbourdichon - please also try to use latest cebuilder - https://github.com/inspireui/cebuilder/releases  or you could also install manually by using this guide https://facebook.github.io/react-native/docs/getting-started

Also note that the BeoNews will be compatible as the Blog app, but it could not support the e-commerce business like the Mstore app - let us know if you have any further issue - thank you!
