### ISSUE TITLE
FluxNews - Ads not showing 

### ISSUE THREAD

**Issue by eikliw** [inspireui/support#2060]
Issues

1. **Default title name of "Blogs"**
How do I change the default displayed page tile of "Blogs", to something else like "Recipes"? see screenshot
<img width="337" alt="Screen Shot 2020-02-10 at 6 06 51 PM" src="https://user-images.githubusercontent.com/11740613/74198881-99c22480-4c30-11ea-92a8-8923e6751fbb.png">

2. **Share URL**
How do I change sharing URL from default "news.inspireui.com/" to mine?
![IMG_820774AFC1E2-1](https://user-images.githubusercontent.com/11740613/74199014-f32a5380-4c30-11ea-832b-f3ef91e22b1d.jpeg)

3. **Ads not displaying**
Ads are not displaying at all. i've attached my common folder 
[common.zip](https://github.com/inspireui/support/files/4183501/common.zip)

I was instructed to open this ticket on codecanyon:
<img width="628" alt="Screen Shot 2020-02-10 at 6 16 47 PM" src="https://user-images.githubusercontent.com/11740613/74199219-92e7e180-4c31-11ea-9820-07f9398152cb.png">

I was able to get all the sign ons working, and I removed the SMS login option. So now its just the issues above. 

Thanks!

> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:

2. Screenshots issues:

3. Proof of my purchased:

3. Config files (optional)
[common.zip](https://github.com/inspireui/support/files/4183477/common.zip)

**Comment by dttrung26** [comment]
Hi @eikliw ,
So sorry for taking so long in replying your issue. 
For the first 2 issues, they will be fixed in the next update 1.3. Thank you so much for notifying us about those issues. 
For the last one, please replace my file into your config.dart located at/lib/common and kindly tell me if it works. 
[config.zip](https://github.com/inspireui/support/files/4196286/config.zip)
Have a great day,
Trung.

**Comment by eikliw** [comment]
how do i enable two ad types? I would like to have both an interstitial and a banner.

thanks

**Comment by eikliw** [comment]
And when is 1.3 expected to release?

**Comment by dttrung26** [comment]
Hi @eikliw ,
Unfortunately, you could be able to enable 1 type at the time sir. And the 1.3 version will be released in next week. Stay tuned. 
Happy coding!

**Comment by eikliw** [comment]
Thanks for update. 

How much would you charge to add that customization? Just two ad types. Do you do that?
