### ISSUE TITLE
[Fluxstore] - Which file and code can edit in the source to customize the top menu items

### ISSUE THREAD

**Issue by limitlessfirm** [inspireui/support#2064]
---------

1. My issue: I removed (top menu) from (tabbar-version-animate.dart) and (tabbar-version-static.dart) but the items in menu still appear

From these files -
lib\example\tabbar-version-animate.darts
lib\example\tabbar-version-static.dart

I removed this code:
            Padding(
              padding: const EdgeInsets.only(left: 15.0),
              child: Column(
                children: <Widget>[
                  ListTile(
                    leading: Icon(Icons.shopping_basket, size: 20),
                    title: Text(S.of(context).shop),
                    onTap: () {
                      Navigator.pushReplacementNamed(context, "/home");
                    },
                  ),
                  ListTile(
                    leading: Icon(FontAwesomeIcons.wordpress, size: 20),
                    title: Text(S.of(context).blog),
                    onTap: () {
                      Navigator.pushNamed(context, "/blogs");
                    },
                  ),
                  ListTile(
                    leading: Icon(FontAwesomeIcons.heart, size: 20),
                    title: Text(S.of(context).myWishList),
                    onTap: () {
                      Navigator.pushNamed(context, "/wishlist");
                    },
                  ),
                  ListTile(
                    leading: Icon(Icons.exit_to_app, size: 20),
                    title: loggedIn ? Text(S.of(context).logout) : Text(S.of(context).login),
                    onTap: () {
                      loggedIn
                          ? Provider.of<UserModel>(context, listen: false).logout()
                          : Navigator.pushNamed(context, "/login");
                    },
                  ),
                ],
              ),
            )

2. Screenshots issues:
![top-menu-2](https://user-images.githubusercontent.com/59250639/74237474-4e655000-4cdc-11ea-8c37-7056a9a409a6.JPG)

3. Proof of my purchased:
![screenshot](https://user-images.githubusercontent.com/59250639/74237480-51f8d700-4cdc-11ea-91ae-99bfd458f1b4.JPG)

3. Config files (optional)

**Comment by trunghieuvn** [comment]
Hello, If you want to delete the above features, please delete in `lib/menu.dart` file. Delete the following code:

![image](https://user-images.githubusercontent.com/19247680/74406434-3ae3f180-4e62-11ea-91cf-8569e24aafec.png)

**Comment by limitlessfirm** [comment]
Thanks
