### ISSUE TITLE
[my-product] - Mstore pro

### ISSUE THREAD

**Issue by bthedevine** [inspireui/support#2065]
Hello there, i have bought your msstore pro app for my woocomerce shop. I have installed it as in the guide on youtube but something not correct. I am having this problem here: 

Windows PowerShell
Copyright (C) Microsoft Corporation. Tutti i diritti sono riservati.

Remove-Item : Impossibile trovare un parametro corrispondente al nome 'rf'.
In C:\Users\computer\Desktop\mstore-3.9.7\mstore-pro\scripts\cebuilder.ps1:2 car:4
+ rm -rf node_modules/
+    ~~~
    + CategoryInfo          : InvalidArgument: (:) [Remove-Item], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand

npm WARN deprecated crypto-js@3.2.0: Critical
npm WARN deprecated superagent@4.1.0: Please note that v5.0.1+ of superagent removes User-Agent header by default, therefore you may need to add it yourself (e.g. GitHub blocks requests without a User-Agent header).  This notice will go away with v5.0.2+ once it is released.
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated core-js@1.2.7: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/ton44079/react-native-apple-authentication.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\computer\AppData\Roaming\npm-cache\_logs\2020-02-11T16_09_07_062Z-debug.log

ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.
react-native : Termine 'react-native' non riconosciuto come nome di cmdlet, funzione, programma eseguibile o file
script. Controllare l'ortografia del nome o verificare che il percorso sia incluso e corretto, quindi riprovare.
In C:\Users\computer\Desktop\mstore-3.9.7\mstore-pro\scripts\cebuilder.ps1:7 car:1
+ react-native run-android
+ ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (react-native:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\computer\Desktop\mstore-3.9.7\mstore-pro>

http://prntscr.com/r0tciu screenshot of the window. 
How can i resolve it and move forward to make the app?

Envato downloads screen: http://prntscr.com/r0td7b

If i should restart, please send me if there's a guide or a video i can check to do.

**Comment by luyx2412** [comment]
Hi @bthedevine Please use Cebuilder to install your app https://github.com/inspireui/cebuilder/releases and this is some videos guide to install cebuilder and install mstore pro via cebuilder https://www.youtube.com/results?search_query=cebuilder

Thanks
