### ISSUE TITLE
[MStore Multi Vendorf] - Unable to resolve 'react-native-screns' from "node_modules/react-navigation-stack/lib/modules/views/Stackview/StackViewCard.js

### ISSUE THREAD

**Issue by opnchaudhary** [inspireui/support#2066]
1. My issue:
I simply followed the steps in the documentation and Readme.md file. When I try to run the app in iOS simulator I get the following issue. 

2. Screenshots issues:
![Simulator_Screen_Shot_iPhone_11](https://user-images.githubusercontent.com/1230345/74269424-94003800-4d31-11ea-9099-f17d7668c27e.png)

3. Proof of my purchased:
![purchase_proof](https://user-images.githubusercontent.com/1230345/74269340-6dda9800-4d31-11ea-8327-3fa922f0dee8.png)

3. Config files (optional)

**Comment by luyx2412** [comment]
Hi @opnchaudhary we fixed the issue in next version. Or you can quick fix `yarn remove react-native-screens` and reinstall with expo `expo install react-native-screens`. https://docs.expo.io/versions/latest/sdk/screens/#installation

Thanks

**Comment by opnchaudhary** [comment]
Thanks
Now I get this.
![react-project-issue](https://user-images.githubusercontent.com/1230345/74502941-670d7a00-4f17-11ea-864e-75b5a6d0ee88.png)

**Comment by luyx2412** [comment]
Hi @opnchaudhary Please update latest version to fix your issue.

Thanks
