### ISSUE TITLE
[FluxStore Pro] - Splash Screen Issue

### ISSUE THREAD

**Issue by PolarisSoftDev** [inspireui/support#2067]
I used splash image with .png in previous version.
But in the v1.6.3, splash image with .png doesn't appear with full screen. Please update this with image file

**Comment by Alnaggar94** [comment]
@minhtruong315 @inspireui-support 
I have the same problem when I change the splash screen to image (PNG,Gif...etc) it doesn't work it shows logo instead.

![Captdddddure](https://user-images.githubusercontent.com/49800146/74414028-a2de0c00-4e51-11ea-8624-792122223bce.JPG)

**Comment by minhtruong315** [comment]
@PolarisSoftDev can u send me lib/app.dart file?

**Comment by PolarisSoftDev** [comment]
Yes, I am sending you lib/app.dart file.

[app.zip](https://github.com/inspireui/support/files/4211750/app.zip)

**Comment by minhtruong315** [comment]
[app.dart.zip](https://github.com/inspireui/support/files/4212460/app.dart.zip)
replace this app.dart then try again

**Comment by PolarisSoftDev** [comment]
Thanks,
Can I get both fade and scale transitions at the same time in the splash screen as the old version?

**Comment by minhtruong315** [comment]
We have support 3 splash screen types: flr, png (full image), and logo icon
What do you want to use now?

**Comment by PolarisSoftDev** [comment]
I mean png file (full screen). splash screen like version 1.5.8.

**Comment by minhtruong315** [comment]
https://github.com/inspireui/support/issues/2067#issuecomment-586864270
you can use app.dart file to support full screen png

**Comment by PolarisSoftDev** [comment]
Thanks for your solution!
