### ISSUE TITLE
[Fluxstore - Multi vendor] -  Row dimension change

### ISSUE THREAD

**Issue by nucl123** [inspireui/support#2069]
Purchase : https://prnt.sc/qz5qoi
Hi
1. We need to re arrange the row as shown in this screenshot,
https://prnt.sc/r0x9hv

So far we had tried by editing the row value to .2 [default was .4], etc..  also tried by editing values of related widgets etc, but without success...
what would be the easiest way to rearrange this row and also to control these image dimensions ?

2. How can we disable some home page elements - like blog , etc..?

Best Regards

> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:

2. Screenshots issues:

3. Proof of my purchased:

3. Config files (optional)

**Comment by inspireui-support** [comment]
@nucl123 - thank you for the questions
1. You can add the columns config like this code, we have made some example from the Fluxstore Pro but did have chanced update for Fluxstore MV :)
```
    "layout": "category",
      "type": "icon",
      "wrap": true,
      "size": 1.2,
      "radius": 9.0,
      "background": "#FFFFFF",
      "columns": 2,
      "shadow": 20.0,
      "border": 0.5,
      "padding": 0.0,
      "items": [...
```

2. Try to update the config.json to remove the Blog section

**Comment by nucl123** [comment]
![Capture](https://user-images.githubusercontent.com/51371138/74335643-b33cab00-4dad-11ea-8603-95227ddfb198.PNG)

That doesn't help, in fact we have tried the same before contacting you also.

**Comment by nucl123** [comment]
we need it 2x2 as shown here,https://prnt.sc/r0x9hv also need to control the size of these images.
currently its too small to be even visible

**Comment by inspireui-support** [comment]
@nucl123  - feel free to customize the category icon widget as your requirement - thanks

**Comment by nucl123** [comment]
can you please tell which specific file to edit?

**Comment by inspireui-support** [comment]
@nucl123 - pls try to use the Inspector - https://docs.inspireui.com/fluxstore/useful-tip/#how-to-change-the-ui-quickly
