### ISSUE TITLE
[FluxStore] - Home Page Design

### ISSUE THREAD

**Issue by eduardopechir** [inspireui/support#2070]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: I am using demo 6, but after the banners I want to add 2 new categories in card view, blog and Instagram Tag

2. Screenshots issues:
![Uploading Captura de Pantalla 2020-02-11 a la(s) 16.36.31.png…]()
<img width="92" alt="Captura de Pantalla 2020-02-11 a la(s) 16 21 05" src="https://user-images.githubusercontent.com/60676647/74286176-d6ebec80-4cec-11ea-813e-54c6d6f99a69.png">
<img width="349" alt="Captura de Pantalla 2020-02-11 a la(s) 16 19 39" src="https://user-images.githubusercontent.com/60676647/74286189-dd7a6400-4cec-11ea-8455-6f63d7772056.png">

3. Proof of my purchased:
![Uploading Captura de Pantalla 2020-02-10 a la(s) 14.08.49.png…]()

3. Config files (optional)

**Comment by kvt0012** [comment]
Hello sir, 
If you want to duplicate categories, you can copy as this picture 
![image](https://user-images.githubusercontent.com/49152325/74498539-7f7b9580-4f13-11ea-9700-76a8a6855405.png)
and paste it after the last
![image](https://user-images.githubusercontent.com/49152325/74498612-b8b40580-4f13-11ea-97b2-fc2c34e206e3.png)
Like this 
![image](https://user-images.githubusercontent.com/49152325/74498650-dda87880-4f13-11ea-88e1-ce8187ba4e40.png)

You will have 2 more categories 
![image](https://user-images.githubusercontent.com/49152325/74498666-ec8f2b00-4f13-11ea-9bfe-58b64d952b3b.png)

Thanks for your issues 
Have a good day

**Comment by eduardopechir** [comment]
Hello, sorry for taking a while to respond, I was traveling and without a Wi-Fi connection.
Thanks for your reply, what I need is in addition to adding the categories, adding the blog section, instagram. Also product categories but in the form of cards. I'm sure you can help me. Best regards.
