### ISSUE TITLE
[BuzzApp] - Problem with WPBakery Page Builder

### ISSUE THREAD

**Issue by caldemation** [inspireui/support#2071]
![38fb9134c749fa5db0650d5c016374a2](https://user-images.githubusercontent.com/59631213/74290343-dcb7f100-4d31-11ea-8ae7-258bb776ccbc.png)

I have a template with Bimber, but when you create the application with BuzzApp, the content you created with WPBakery Page Builder does not appear correctly.

**Comment by inspireui-support** [comment]
@caldemation - you can customize the Rest API to display short code for VC - https://github.com/WP-API/WP-API/issues/2578

Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads  it's used to verify your proof of purchase? sorry for any inconvenience - Thank you!
