### ISSUE TITLE
[FLUXSTORE MV] -  SOME ISSUES ABOUT NOTIF AND CHAT (IOS & ANDROID )

### ISSUE THREAD

**Issue by yassiney120** [inspireui/support#2072]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
on android : 
- notification received ( but showing empty on  notify Messages )
on ios : 
notification not received ( but showing on notify Messages ) 
chat : not working
login by sms : app crash ( close ) 

PLEASE FROM WHERE I CAN CHANGE APP INFO FOR FACEBOOK LOGIN

THANK YOU
2. Screenshots issues:
android : 
https://drive.google.com/file/d/14n0U7p7TXqnaGCdW-PZE33Shn7laGj-1/view?usp=sharing
ios : 
https://drive.google.com/file/d/1TrsRsFCKiZau4kN4j8OoogTcr5uy3ZUF/view?usp=sharing
3. Proof of my purchased:
https://ibb.co/XsskN38
3. Config files (optional)

**Comment by yassiney120** [comment]
Application crash solved by @minhtruong315 
I solve 
Chat issues on ios
Login by sms ios 

Still not solved issues :
Ios : 
Notification on ios
Login by apple ios
Login facebook
Android : 
Sms notify messages emty on android
Login facebook

**Comment by inspireui-support** [comment]
@yassiney120 - sorry for the late response - could I know if you could able to resolve the issues 

@minhtruong315 - pls help to follow up - thanks

**Comment by yassiney120** [comment]
hi, yes mr truong he help me to solve all the issues  still only notification on ios im waiting new version 
thank you

**Comment by yassiney120** [comment]
Big thank to Mr @minhtruong315  all issues fixed
