### ISSUE TITLE
[FluxNews] - iFrame embed code not working

### ISSUE THREAD

**Issue by rkmitdadm** [inspireui/support#2073]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:

Hi, we tried YouTube and Soundcloud embed code but not working. Below is the iFrame code. Which is nicely displayed in the word press site.

<iframe src=”https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/943707373&color= 23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true” width=”100 ” height=”300” frameborder=”no” scrolling=”no”></iframe>

<iframe src=”https://www.youtube.com/embed/5z1A3oC_oRc” width=”560” height=”315” frameborder=”0” allowfullscreen=”allowfullscreen”></iframe>

2. Screenshots issues:
https://rkmath.d.pr/lvZqX6
3. Proof of my purchased:
https://rkmath.d.pr/M2o6vO

**Comment by inspireui-support** [comment]
@rkmitdadm - pls share your common zilp file is ok, don't share full source here pls

**Comment by rkmitdadm** [comment]
[common.zip](https://github.com/inspireui/support/files/4196935/common.zip)
pls find the common zip file

**Comment by inspireui-support** [comment]
@rkmitdadm - note with investigating

@dttrung26 - pls try to use the https://pub.dev/packages/flutter_widget_from_html replace the existing one to support the iframe inside the post content

**Comment by dttrung26** [comment]
Hi @rkmitdadm ,
so far as I checked, Youtube embedded code is still working fine and unfortunately, we don't support Soundcloud embedded code at the moment. Please double-check to make sure your code is embedded correctly. 
Many thanks!
Trung.

**Comment by dttrung26** [comment]
Closed due to user inactivity. Feel free to re-open this ticker if you are still facing this issue.
Best!
