### ISSUE TITLE
Beo news

### ISSUE THREAD

**Issue by gmldigital2019** [inspireui/support#2074]
I have been trying to get feedback on this forum and the person assigned to my ticket has not given proper feedback in 16 days.

**Comment by inspireui-support** [comment]
Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads  it's used to verify your proof of purchase? sorry for any inconvenience - Thank you!

**Comment by gmldigital2019** [comment]
Good Day,
Please find the attached.

[Image]

[Image]



Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by inspireui-support** [comment]
Sorry, could you drag it again, it seems there are some problem

**Comment by gmldigital2019** [comment]
[Image]

[Image]



Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by gmldigital2019** [comment]
![Screenshot_20200212_095408_com google android apps docs](https://user-images.githubusercontent.com/60437057/74394986-7b9d2580-4de4-11ea-9931-2f70bd028ffc.jpg)
![Screenshot_20200212_095329_com android chrome](https://user-images.githubusercontent.com/60437057/74394987-7c35bc00-4de4-11ea-9d85-ce6bc77419d7.jpg)

**Comment by gmldigital2019** [comment]
![Screenshot_20200212_095329_com android chrome](https://user-images.githubusercontent.com/60437057/74395052-ab4c2d80-4de4-11ea-9e71-a46c902cc9fb.jpg)

**Comment by inspireui-support** [comment]
@gmldigital2019 - would you mind to let us know the detail screenshot issue so that i can assign to the team for checking, thank you for your patience - very best!

**Comment by gmldigital2019** [comment]
Home Layout- We were not able to implement a continuous scroll unless we chose our main view as the combo view option, however, this removed our top slider with recent stories.

Only one of our ad spot works and the user needs to scroll to the bottom of all the content to view it.

The Category Page, we want to adjust this page to only show specific categories but did not see the option to do this, also were not able to turn on the switch that allows a different view for this section.

Email sign up and commenting- We followed the instructions sent to us but still did not reive the email to register, users were created but they were not showing up in our wordpress backend. Also, when we tried to sign in to the app it did not work.

**Comment by luyx2412** [comment]
Hi @gmldigital2019 Sorry about reply you late. Can you send me the AppConfig.json and Config.js file?

Thanks.

**Comment by luyx2412** [comment]
Hi @gmldigital2019 Sorry i saw your Config file. 
- Please follow the comment to fix scroll https://github.com/inspireui/support/issues/2038#issuecomment-587577188 home screen
-The cateogory page could not support specific categories.
- "The sign up and comment" when you sign up, the wordpress will not send the email to confirm, so when you sign up success. Please sign in with this account.

Thanks

**Comment by gmldigital2019** [comment]
Hi, 
Not sure I understand the last point.

**Comment by luyx2412** [comment]
Hi @gmldigital2019 Sorry about miss your issues.
- With the Ad, we have `Admob` component in `Container/PostDetail/PostDetail.js` which is example using the Ad, you can use the Ad anywhere when use this component.
- You can filter the categories in `Container/Category/index.js`  in line `79`, this is the example code to filter categories.
![image](https://user-images.githubusercontent.com/8909619/75688787-b05d1800-5cd2-11ea-8722-29b5815609a5.png)

Thanks
