### ISSUE TITLE
[my-product] - FluxStore - Universal mobile commerce Flutter app for Woocommerce

### ISSUE THREAD

**Issue by nelson243** [inspireui/support#2075]
![Screenshot_1581508901](https://user-images.githubusercontent.com/13100267/74333675-bb3e2000-4d98-11ea-9ebe-98c67ad40186.png)
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: I created my app with Fluxstore 1.6.0 it's working fine and the issue was with the payment gateways i was able to run only paypal other payments from my website was not working.  Now i installed the version 1.6.3 i didn't do anything on it yet but when i run it i'm getting the error attached help please

2. Screenshots issues:
![Screenshot_1581508901](https://user-images.githubusercontent.com/13100267/74334053-74045f00-4d99-11ea-8add-f9063dcd011a.png)

3. Proof of my purchased:
![flux](https://user-images.githubusercontent.com/13100267/74334166-b3cb4680-4d99-11ea-95d9-371dfda2a46d.png)

3. Config files (optional)

**Comment by inspireui-support** [comment]
@nelson243 - pls help to fix by this solution https://github.com/inspireui/support/issues/2001

We will also update the new version on this week

**Comment by nelson243** [comment]
So this error is not only coming from me ??
The following assertion was thrown building MainTabs-[LabeledGlobalKey<MainTabsState>#c6146 homePageKey](dirty, dependencies: [MediaQuery, _DefaultInheritedProviderScope<AppModel>, _InheritedTheme, _DefaultInheritedProviderScope<CartModel>, _LocalizationsScope-[GlobalKey#b9883], _FocusMarker], state: MainTabsState#05777(ticker inactive)):
type 'int' is not a subtype of type 'double'

**Comment by nelson243** [comment]
I replaced with the downloaded tabbar but i'm still getting the same error 
<img width="242" alt="fbfdbdfnd" src="https://user-images.githubusercontent.com/13100267/74339157-c8144100-4da3-11ea-82a9-42e269a47f6c.png">
