### ISSUE TITLE
[FluxStore] - Shipping class cost issue 

### ISSUE THREAD

**Issue by UTimung** [inspireui/support#2076]
last time you guys said that you will fix shipping class cost issue in next update

but in this new version again shipping charges showing zero

**Comment by inspireui-support** [comment]
@UTimung - could you reopen the previous ticket and comment the ticket here (regarding the shipping issue) - thank you!

**Comment by UTimung** [comment]
The previous ticket was #1485
But now it shows THE ISSUE WAS DELETED

**Comment by inspireui-support** [comment]
@UTimung - sorry for the issue as we have removed some close tickets to protect user information. 

Could i know if your Shipping issues similar to this ticket https://github.com/inspireui/support/issues/1922 ? The team is also working on this improvement to upgrade the feature for Shipping

**Comment by UTimung** [comment]
![73084377-e5a96580-3edd-11ea-8963-7483522a5a17](https://user-images.githubusercontent.com/18107447/74513316-4d2c6100-4f30-11ea-8b92-e2f9515268f5.png)

Yes same

Your app shows only FLAT RATE cost
Not SHIPPING CLASS cost
That's why showing ZERO

**Comment by UTimung** [comment]
![Screenshot_20200214-135133~2](https://user-images.githubusercontent.com/18107447/74513805-684ba080-4f31-11ea-9b98-c3ff5ce67c98.png)

Check this

i used only Shipping class cost
And your app couldn't detect it

**Comment by inspireui-support** [comment]
@kvt0012 - please help for investigating

**Comment by UTimung** [comment]
Upto how many days i have to wait?

**Comment by inspireui-support** [comment]
@UTimung - the team is working on this issue, they will release new version on this week - thank you!

**Comment by kvt0012** [comment]
Thanks for your issue, sir 
We fixed it and it will be released on the next version. 
Thank you
