### ISSUE TITLE
error cebuilder ''No sale belonging to the current user found''

### ISSUE THREAD

**Issue by hirande** [inspireui/support#2077]
Hello, I couldn't use the software I bought years ago. I don't have enough software knowledge. but thanks to the 'cebuilder' software, I saw that it was installed very easily, but I am faced with a problem like this. error cebuilder ''No sale belonging to the current user found'' 
I bought the application on February 14, 2017 at 16:58. I added an invoice. and I took a screenshot as proof, I was going to discard the credit card I bought, but it expired 2 years ago. If this is not enough, there are all the emails I have talked to you so far.
[invoices.zip](https://github.com/inspireui/support/files/4195804/invoices.zip)
![Ekran Alıntısı](https://user-images.githubusercontent.com/19289751/74388755-48bb5780-4e0d-11ea-88e2-6ed1d82f7445.JPG)

**Comment by inspireui-support** [comment]
@hirande - we suggest to setup the react native framework with this guide first as it is quite simple at this this time - https://facebook.github.io/react-native/docs/getting-started - it will make sure your Android SDK is installed correctly

The cebuilder could not compatible with the beostore but you can try to use to setup some basic library for it.
