### ISSUE TITLE
FluxStore Pro : Multiple widgets used the same GlobalKey.

### ISSUE THREAD

**Issue by saidbakkou** [inspireui/support#2080]
i changed the connection code of my database from firebase  to sql  (for login/signup) ... it was working fine but now when i press login button i find this error in the picture bellow ..then when i try to refresh the app i findthe login is done coreectly .. thanks in advance
![dsds](https://user-images.githubusercontent.com/59389664/74418807-3e1eb380-4e49-11ea-81fd-b1ab59c9de6c.PNG)

**Comment by inspireui-support** [comment]
Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads  it's used to verify your proof of purchase? sorry for any inconvenience - Thank you!

**Comment by saidbakkou** [comment]
![86183753_197529808291854_4776660982191620096_n](https://user-images.githubusercontent.com/59389664/74429077-8befe780-4e5a-11ea-8b9d-c42691661f75.jpg)

**Comment by inspireui-support** [comment]
@trunghieuvn  - this could be related to the ticket - https://github.com/inspireui/support/issues/2054

**Comment by trunghieuvn** [comment]
You can try the Rename Key here:

![image](https://user-images.githubusercontent.com/19247680/74620997-a7fecc00-516d-11ea-8e85-1f0d082bbab9.png)

file `tabbar.dart` , in funtion `tabView`.

**Comment by saidbakkou** [comment]
@trunghieuvn    i ve made those changes  but i still get the same problem :(  .. signup is working properly i had this problem when i tried to login (with mysql DB)  even if it was working before and i didn t any changes after that could be the reason  ... btw i have the Version 1.6.3 of the template

**Comment by saidbakkou** [comment]
and when i pressed the refresh button bellow i find the login is done  so i guess 
![Capturesd](https://user-images.githubusercontent.com/59389664/74638015-6ec55c80-516b-11ea-9452-20134cff06ca.PNG)
thats not a problem from my login code

**Comment by mohafouad** [comment]
same problem with me :(

**Comment by trunghieuvn** [comment]
Try editing the following code:

![image](https://user-images.githubusercontent.com/19247680/74699722-03938d00-5234-11ea-9082-27117c54c229.png)

**Comment by mohafouad** [comment]
same problem :(

**Comment by trunghieuvn** [comment]
Hi @mohafouad ! Please take a video of the steps to create the error and send me the source code via email `hieu.trantrung1204@gmail.com` so I can easily handle this error.

**Comment by kenngigz** [comment]
same problem

**Comment by trunghieuvn** [comment]
Please make the following changes to correct this error:
1.  in `lib/tabbar.dart' remove `keyNavigationTabbar`
![image](https://user-images.githubusercontent.com/19247680/74800369-cac3e880-5305-11ea-97c7-1fce41a2de32.png)

2. in `app.dart' insert `keyHomePage ` and use in function `renderFirstScreen`

![image](https://user-images.githubusercontent.com/19247680/74800401-e9c27a80-5305-11ea-8752-31824c131e30.png)

3. Edit code in page use old key 
![image](https://user-images.githubusercontent.com/19247680/74800457-18405580-5306-11ea-8954-ef834345576b.png)

![image](https://user-images.githubusercontent.com/19247680/74800468-21c9bd80-5306-11ea-9a52-7a7af6f8665c.png)

**Comment by dasdev** [comment]
i am getting this issue what i should do bcz it's not understable. give the codes that i can copy to change
