### ISSUE TITLE
FluxNews - Menu icon does not appear

### ISSUE THREAD

**Issue by danimmg** [inspireui/support#2081]
**1 - I need to change the menu icon and not the logo**
https://github.com/inspireui/support/issues/2035

![01](https://user-images.githubusercontent.com/59834619/74424009-f8a1bc80-4e2f-11ea-9afb-a5e40622d666.jpg)

**2 - Translation**
https://github.com/inspireui/support/issues/2055
Please I need to deliver the project and I cannot wait for the new version, please send me the correction
I'm not able to translate these terms

![74176424-68d4f600-4c16-11ea-8852-be4a42c9526f](https://user-images.githubusercontent.com/59834619/74424427-b2009200-4e30-11ea-9e1c-37e5419ae1bf.jpg)
![74176440-71c5c780-4c16-11ea-9bdf-83d29cfba09f](https://user-images.githubusercontent.com/59834619/74424429-b2992880-4e30-11ea-9666-23161cc4efd0.jpg)

Thanks

**Comment by dttrung26** [comment]
Hi @danimmg ,
Drawer Icon is fixed by hard coding. However, if you still want to change it, you can do it by going to logo.dart file located at /lib/widgets/blog, at line 17 change `Icons.blur_on,` into your customized icon. 
Best,
Trung.
