### ISSUE TITLE
Fluxstore-Woocommerce

### ISSUE THREAD

**Issue by ukveda** [inspireui/support#2082]
1. My issue: Run flutter doctor and it found 2 issues, how to resolve. Screen shot attached

2. Screenshots issues: 
![Flutter Doctor Error](https://user-images.githubusercontent.com/58551104/74427036-6bd12000-4e7c-11ea-9916-d7648119711e.png)

3. Proof of my purchased: 580c8e49-f3bf-423c-a6c4-9dcdcbed4851

3. Config files (optional)

**Comment by ukveda** [comment]
Updated Screenshot  -   
![Error Screen Shot-1](https://user-images.githubusercontent.com/58551104/74434098-b3a97480-4e87-11ea-91e8-aaf4de72227f.png)

**Comment by inspireui-support** [comment]
Hi try to run:
```
flutter doctor --android-licenses
```
