### ISSUE TITLE
mstore

### ISSUE THREAD

**Issue by MustafaAlkhazraji** [inspireui/support#2083]
1. My issue:

Unable to get data from Server on release android on several devices like OPPO Find X + Crash on purchase after put items to Wish List

I tried the latest version you have uploaded! 3.9.8

2. Screenshots issues:
![Screenshot_2020-01-08-16-29-52-58](https://user-images.githubusercontent.com/47216627/74436451-88b72480-4e77-11ea-8db0-ee1fadc33928.png)
![Simulator Screen Shot - iPhone 11 - 2020-01-08 at 16 24 38](https://user-images.githubusercontent.com/47216627/74436460-8ce34200-4e77-11ea-9f6a-4deefe687641.png)

3. Proof of my purchased:
![Screen Shot 2020-02-13 at 3 46 43 PM](https://user-images.githubusercontent.com/47216627/74436813-214da480-4e78-11ea-8353-c8fcbbb8f683.png)

**Comment by luyx2412** [comment]
Hi @MustafaAlkhazraji Can you send me your AppConfig.json and Config.js?

Thanks
