### ISSUE TITLE
FluxStore 1.6.3 - Woocommerce] Variable products prices not displaying properly

### ISSUE THREAD

**Issue by Lokeswara-betha** [inspireui/support#2084]
1. My issue:
 In WooCommerce  , it's displaying dropdown for the variable products , but in the application it it showing variable product price as 0 and not showing any dropdown.

2. Screenshots issues:
![unnamed](https://user-images.githubusercontent.com/60268240/74437453-26b5e980-4e8e-11ea-94ae-72deea6d63f4.png)

3. Config files (optional)

**Comment by inspireui-support** [comment]
Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads  it's used to verify your proof of purchase? sorry for any inconvenience - Thank you!

**Comment by Lokeswara-betha** [comment]
![Screenshot_2020-02-14-22-17-53-591_com google android gm](https://user-images.githubusercontent.com/60268240/74625732-55c0a980-5173-11ea-8497-421d5143ac47.jpg)
