### ISSUE TITLE
[listapp] - Facebook Login return Firebase Error  

### ISSUE THREAD

**Issue by Metacowboy** [inspireui/support#2085]
If User try to login via Facebook following error Screen shows up (firebase ?) 
 
Login for registered WP user works. 

done so far 
-Facebook app and Login details setup and green. 
-Firebase setup and api Keys & Rules  allow read & write

Item ID:
22645013

Item Purchase Code:
a3f43ded-f77d-4436-bd69-641199ffc9c4

Purchase Date:
2019-08-06 17:04:48 UTC

![AppError_LoginFAcebook](https://user-images.githubusercontent.com/1506060/74439307-4dfbbf00-4e6c-11ea-96d4-8fba65f7e70c.jpg)

**Comment by inspireui-support** [comment]
@Metacowboy - could you try to set up the firebase as the following document - https://docs.expo.io/versions/latest/guides/using-firebase/ - thank you!

**Comment by Metacowboy** [comment]
Thank you , 
This Stackoverflow pointed me to the right direction 
https://stackoverflow.com/questions/54072206/requests-for-referrer-are-blocked-when-trying-to-sign-in-anonymously-to-firebase

it was a restricted Oauth key to domain https referrer only.
Why Error blocked : domain PERMISSION_DENIED 
shows up 

Now the Key is unrestricted and unprotected and it works (selected Restriction -)
but the Google console allow restriction for Keys to android apps and IOS apps with package name
 
Question 1 ) Since we run IOS AND android app how to setup 
your app the 2 google Oauth keys for firestore?

Question 2) 
What are the correct firestore rules SingUp Read_later and  database schema for your app in production mode ? 

See in the screenshots

![Screen Shot 2020-02-14 at 16 30 14](https://user-images.githubusercontent.com/1506060/74544736-ef0b7800-4f47-11ea-9263-bca7117a3eb3.jpg)
![Screen Shot 2020-02-14 at 16 27 10](https://user-images.githubusercontent.com/1506060/74544743-f2066880-4f47-11ea-9512-424dba0d2f34.jpg)

**Comment by inspireui-support** [comment]
@Metacowboy - thank you for the sharing, let me discuss with the team and keep upgrade some documentation for this feature - thank you!

**Comment by themeix** [comment]
> @Metacowboy - thank you for the sharing, let me discuss with the team and keep upgrade some documentation for this feature - thank you!

I am also waiting for the docs about facebook login
