### ISSUE TITLE
#2042  ticket closed , without fixing issue ticket #2042

### ISSUE THREAD

**Issue by vwakehub** [inspireui/support#2088]
After changing code with the files you @minhtruong315 provided
Print Product are showing , but every other product is out of stock
![WhatsApp Image 2020-02-13 at 9 46 52 PM](https://user-images.githubusercontent.com/59481921/74494321-b6917d00-4efa-11ea-9c9f-84cb7ea51c77.jpeg)

also in dark theme cart icon is not matching with ui
![WhatsApp Image 2020-02-13 at 9 46 46 PM](https://user-images.githubusercontent.com/59481921/74494351-d3c64b80-4efa-11ea-9506-54dc67eac6c6.jpeg)

**Comment by inspireui-support** [comment]
@minhtruong315 - please help to investigate this impact issue - thank you!

**Comment by vwakehub** [comment]
@minhtruong315 Please !!

**Comment by minhtruong315** [comment]
[product.dart.zip](https://github.com/inspireui/support/files/4207940/product.dart.zip)
[product_card_view.dart.zip](https://github.com/inspireui/support/files/4207941/product_card_view.dart.zip)
Replace these files
models/product.dart
widgets/product/product_card_view.dart

**Comment by vwakehub** [comment]
thanks these bug fixed !!
