### ISSUE TITLE
Flux News

### ISSUE THREAD

**Issue by Alqumairi** [inspireui/support#2089]
In the dark mode , the font color is not clear at all

![Screenshot_1581666371](https://user-images.githubusercontent.com/37410069/74511552-34787700-4f41-11ea-9676-bffe5ab51e63.png)
![Screenshot_1581666359](https://user-images.githubusercontent.com/37410069/74511555-35a9a400-4f41-11ea-9f6a-4eed95f67593.png)

Please advise me how to fix it i need to submit the app today to play store

**Comment by inspireui-support** [comment]
Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads  it's used to verify your proof of purchase? sorry for any inconvenience - Thank you!

**Comment by Alqumairi** [comment]
![Annotation 2020-02-14 162740](https://user-images.githubusercontent.com/37410069/74514125-f0887080-4f46-11ea-8699-8dbb061f5559.png)

**Comment by inspireui-support** [comment]
@Alqumairi - thank you, let me double-check with the team and keep an update - very best

**Comment by dttrung26** [comment]
Support via skype and fix in v1.3. 
Best!

**Comment by zemeister23** [comment]
for me too this bug
<img src="https://i.ibb.co/CscXCLV/asdasd.png">

Please help mee!!!!!!.
i dont have skype. Ive whatsapp +998973873723
