### ISSUE TITLE
[mstore RTL] -  RTL fixed but in new ver not

### ISSUE THREAD

**Issue by kiamoz** [inspireui/support#2090]
Dear support , in this ver RTL went wrong ..
You fixed it with teamviwer in redux but I forget to save the files..
could you please re connect me today ?
just fix RTL  in redux .

**Comment by kiamoz** [comment]
@luyx2412 Help me again  please

**Comment by inspireui-support** [comment]
Duplicate of #2044

**Comment by kiamoz** [comment]
it's not duplicated ! , 2 other things ! RTL and fonts !
