### ISSUE TITLE
Problem in New Version 1.6.3 Fluxstore WooCommerce - Flutter E-commerce Full App 

### ISSUE THREAD

**Issue by RKDArora** [inspireui/support#2091]
Sir,

I download the new version 1.6.3

I got the following issues with Magento-

    Logout not working from main left side menu.
    order history blank black screen when press back.
    not able to place final order at last. It giving error at attached in file. When I checked at website the order is placed but adding into cart again and again.
    i.e. cart not empty due to error received "unexpected error (at character 1)....".

Thanks

Rajesh
![Screenshot_20200207-075242](https://user-images.githubusercontent.com/50474559/74544801-c39b8400-4f6d-11ea-9556-520738301930.png)

**Comment by inspireui-support** [comment]
Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads  it's used to verify your proof of purchase? sorry for any inconvenience - Thank you!
