### ISSUE TITLE
[FluxListing] - WooCommerce performance 

### ISSUE THREAD

**Issue by mohachouch** [inspireui/support#2092]
Hello,

I am working on a project with multiple vendors.

What is the maximum number that the WooCommerce server can support.

Regards,

**Comment by inspireui-support** [comment]
hi, it will depend on your server capacity as the app only connect via Rest API endpoint to the server-side, there is no problem with the mobile app performance

**Comment by mohachouch** [comment]
Thank you for your reply.

What is the difference between Listeo, MyListing & Listing Pro?

What is the most efficient for a multi-seller application.

Thanks
