### ISSUE TITLE
[mv-mstore] - bugs in the new release 1.3.3 for the wishlist 

### ISSUE THREAD

**Issue by khalidsharif** [inspireui/support#2093]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

the latest release 1.3.3 has a bug when I click the wishlist menu

https://ibb.co/Qbw8rsJ

**Comment by inspireui-support** [comment]
Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads  it's used to verify your proof of purchase? sorry for any inconvenience - Thank you!

**Comment by khalidsharif** [comment]
> Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads it's used to verify your proof of purchase? sorry for any inconvenience - Thank you!
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/c5a18223816825ebf6c0fec648742882ecbb6a7b/68747470733a2f2f6173736574732e73686f7066726f6e742e656e7661746f2d7374617469632e636f6d2f696d616765732f6d6574612f6c6f676f732f636f646563616e796f6e2e706e67"><img alt="" height="14" src="https://camo.githubusercontent.com/c75d968dba11187d74e09644791494a4418ce2d8/68747470733a2f2f6173736574732e73686f7066726f6e742e656e7661746f2d7374617469632e636f6d2f69636f6e732f636f646563616e796f6e2e6e65742f66617669636f6e2e69636f"> CodeCanyon**[Buy Plugins & Code from CodeCanyon](https://codecanyon.net/)**Discover 32,275 Plugins, Code and Script for Bootstrap, Javascript, PHP, Wordpress, HTML5 and more. Save time, buy Code on CodeCanyon!

https://ibb.co/d40dKnD

**Comment by luyx2412** [comment]
Hi @khalidsharif In `src/containers/WishList/index.js` line 23 please remove this line follow the screenshot 
![image](https://user-images.githubusercontent.com/8909619/74621076-0166fb00-516e-11ea-9f5d-275677c6e1b9.png)

Thanks

**Comment by khalidsharif** [comment]
> Hi @khalidsharif In `src/containers/WishList/index.js` line 23 please remove this line follow the screenshot
> ![image](https://user-images.githubusercontent.com/8909619/74621076-0166fb00-516e-11ea-9f5d-275677c6e1b9.png)
> 
> Thanks

Perfect, now it's working without issues.
