### ISSUE TITLE
[Fluxstore] - change screen comes before Welcome screen

### ISSUE THREAD

**Issue by limitlessfirm** [inspireui/support#2094]
---------

1. My issue: When i run the code i see (Fluxstore) logo image before welcome screen and i want to change it to my logo

2. Screenshots issues:
![first-welcome](https://user-images.githubusercontent.com/59250639/74566303-dddc5e80-4f7b-11ea-8229-3d8fbca5c7f2.JPG)

3. Proof of my purchased:
![screenshot](https://user-images.githubusercontent.com/59250639/74566314-e2a11280-4f7b-11ea-8f3b-6824931904b6.JPG)

3. Config files (optional)

**Comment by themeix** [comment]
It need to change spashscreen.flr file i think but how to edit that?

**Comment by inspireui-support** [comment]
@themeix - pls try to check this guide - https://docs.inspireui.com/fluxstore/customization/#2-logo-splash-screen - thank you!
