### ISSUE TITLE
Fluxstore Pro can't connect to magento store

### ISSUE THREAD

**Issue by hssinaman** [inspireui/support#2099]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
Hi,
we have configured Fluxstore Pro for our magento store ( magento 2.3.1) and we it cant't connect with website even we follow all steps of your documentation and also the products can't be displayed as your demo 

2. Screenshots issues:
![1 - problem](https://user-images.githubusercontent.com/61097607/74596437-88718180-504f-11ea-942b-ceae18bf3e9b.jpeg)
![2- config](https://user-images.githubusercontent.com/61097607/74596438-8a3b4500-504f-11ea-97ea-23dc1fe97492.jpeg)
![3- the same on the admin](https://user-images.githubusercontent.com/61097607/74596439-8b6c7200-504f-11ea-8879-cf654fa602d6.jpeg)
![4- access -token](https://user-images.githubusercontent.com/61097607/74596440-8c050880-504f-11ea-9d77-45d2c94f37d3.jpeg)
![4- access-token_2](https://user-images.githubusercontent.com/61097607/74596442-8c9d9f00-504f-11ea-9145-b8da2f47619f.jpeg)
![5](https://user-images.githubusercontent.com/61097607/74596443-8c9d9f00-504f-11ea-90b0-d4065ef4a790.jpeg)

3. Proof of my purchased:
![proof](https://user-images.githubusercontent.com/61097607/74596467-d4bcc180-504f-11ea-992e-b5fb1ab6ec23.png)

3. Config files (optional)
![2- config](https://user-images.githubusercontent.com/61097607/74596473-e43c0a80-504f-11ea-8c31-4242d1c4cd86.jpeg)

**Comment by hssinaman** [comment]
![Screenshot_20200216_075946_com android chrome](https://user-images.githubusercontent.com/61097607/74600508-05721a80-5093-11ea-9003-f9c4631cb178.jpg)

**Comment by hssinaman** [comment]
We need your help urgent please!

**Comment by hssinaman** [comment]
We are still waiting for your asap help please

**Comment by minhtruong315** [comment]
Hi @hssinaman can u send me admin account to login to your website via email: truong@inspireui.com
with subject: 2099

**Comment by hssinaman** [comment]
the issue isn't fixed and we still can't connect Fluxstore to our magento website and we can't display products
as we mentioned above its urgent but no solution till now

**Comment by hssinaman** [comment]
Can you resolve the issue ?

**Comment by inspireui-support** [comment]
@minhtruong315 - please help for checking with high priority - thank you!

**Comment by minhtruong315** [comment]
supported

**Comment by jacob-arlington** [comment]
I have Same issue, Could you please help, category load and when i click its say no product.
magnento 2.3.3

**Comment by hssinaman** [comment]
i have sent the source code to the support and they fixed it

**Comment by jacob-arlington** [comment]
which one? magneto or android part?

**Comment by hssinaman** [comment]
Android

**Comment by hssinaman** [comment]
Fluxstore code source
