### ISSUE TITLE
Build Failed 3.6.3

### ISSUE THREAD

**Issue by anosmx** [inspireui/support#21]
Hi anosmx, Please follow the step to fix the issue related XCode 10.

1. In your project `cd node_modules/react-native/third-party/glog-0.3.4`
2. Run script `../../scripts/ios-configure-glog.sh`

Thanks

_Originally posted by @luyx2412 in https://github.com/inspireui/support/issues/10#issuecomment-438891588_

**Comment by anosmx** [comment]
Hi,

Regarding my previous issue, I don't know how to perform these steps.

1. I should go to this directory cd node_modules/react-native/third-party/glog-0.3.4 and then what?
2. What is the terminal command to run this file? I've tried run ../../scripts/ios-configure-glog.sh but it didn't work!!

Thanks!

**Comment by luyx2412** [comment]
Hi can you take me the screenshot?

**Comment by minhcasi** [comment]
Hi, could you try to unzip and override this folder https://www.dropbox.com/s/ghlmwttzbf4mkkg/third-party.zip?dl=0  to this path node_modules/react-native/

This cause by your third-party cache from react native

Thanks

**Comment by anosmx** [comment]
Hi,

Still did not work!! Here is a screen shot. [Pic](https://discuss.spotui.com/uploads/default/original/1X/4ccca29b08c426921aaac0d9383464d9963bfde4.jpeg)

**Comment by luyx2412** [comment]
Hi this solution applied with me. So please follow this article https://github.com/facebook/react-native/issues/19529#issuecomment-428838520 to fix the issue. Thanks
