### ISSUE TITLE
mstore multivendor app issues. expo version

### ISSUE THREAD

**Issue by alazar-aklilu** [inspireui/support#2101]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: there are a couple of issues on my mstore -multivendor app i used expo version i have read all the docs diligently but i need your support please reply as soon as possible  
a. the app shows a sale price of $0.00 under the real price on the products even though i haven't added any sale variable in it
b. i wan't to remove facebook login how do i do that
c. the app is slow is there any way i can improve performance
d. login and registration doesn't work on the app when i try to, it restarts the app
e. push notifications are not working 
f. the categories tab only shows half the categories in my store
g. the vendors tab is not showing anything
h. i can't see the reviews in the products page
i. in the products page the vendor section has empty fields
j. i don't want login to be required for checkout

2. Screenshots issues:
issue a
![issue a](https://user-images.githubusercontent.com/60713664/74604752-e2b32680-50d1-11ea-86c5-055bb96bf476.jpg)
issue g
![issue g](https://user-images.githubusercontent.com/60713664/74604767-0e361100-50d2-11ea-86fb-0e64fa7ccab2.jpg)
issue i
![issue i](https://user-images.githubusercontent.com/60713664/74604773-227a0e00-50d2-11ea-8189-f8b378c2bb17.jpg)

3. Proof of my purchased:
![confirm](https://user-images.githubusercontent.com/60713664/74604733-aaabe380-50d1-11ea-9e28-de307ace1a51.png)

3. Config files (optional)
src/common/
[Config.txt](https://github.com/inspireui/support/files/4209742/Config.txt)

**Comment by alazar-aklilu** [comment]
[Config& appconfig.zip](https://github.com/inspireui/support/files/4209765/Config.appconfig.zip)
here is a zip of the config and appconfig files in src/common

**Comment by alazar-aklilu** [comment]
there also is another issue most of the time the app does not load and the category screen shows a can't get data from server message
![Screenshot_20200216-160039_Brundo Shopping](https://user-images.githubusercontent.com/60713664/74605141-40e20880-50d6-11ea-9032-900c5ca05006.jpg)

**Comment by alazar-aklilu** [comment]
i am also experiencing another problem the whole app started to crash
![Screenshot_20200216-160826_Samsung Experience Home](https://user-images.githubusercontent.com/60713664/74605348-6d971f80-50d8-11ea-8882-5a54a3160aac.jpg)

**Comment by luyx2412** [comment]
Hi @alazar-aklilu Please give me the MStore MV version?

Thanks

**Comment by alazar-aklilu** [comment]
mstore multivendor v1.3.2

Sent from Yahoo Mail on Android 
 
  On Tue, 18 Feb 2020 at 5:47 am, luyx2412<notifications@github.com> wrote:   
Hi @alazar-aklilu Please give me the MStore MV version?

Thanks

**Comment by luyx2412** [comment]
Hi @alazar-aklilu Please update latest version mstore multivendor v1.3.3 to fix the issues.

Thanks

**Comment by alazar-aklilu** [comment]
that is the version i bought. how do i update 
Sent from Yahoo Mail on Android 
 
  On Sun, 23 Feb 2020 at 12:51 pm, luyx2412<notifications@github.com> wrote:   
Hi @alazar-aklilu Please update latest version mstore multivendor v1.3.3 to fix the issues.

Thanks

**Comment by luyx2412** [comment]
Hi @alazar-aklilu Please go to https://codecanyon.net/downloads url to download latest version.

Thanks

**Comment by alazar-aklilu** [comment]
Hi, i installed the latest version and there are issues that still exist
a. i wan't to remove facebook login how do i do that
b. push notifications are not working
c. the categories tab only shows half the categories in my store
d. the vendors tab is not showing anything
e. review is not working
f. in the products page the vendor section has empty fields
g. i don't want login to be required for checkout
h. when trying to add product and error "sorry, you are not allowed to create posts as this user' shows
i. checkout is not completed in the app it redirects to the mobile site. is there anyway i can fix this

**for issue h**
![Screenshot_20200307-153426_Brundo_Shopping 1](https://user-images.githubusercontent.com/60713664/76144084-d47f7700-608d-11ea-8af1-c8f41f83ff6a.jpg)
