### ISSUE TITLE
[Fluxstore] - How to remove other languages except english and how to add new language? 

### ISSUE THREAD

**Issue by themeix** [inspireui/support#2102]
1. My issue:

In that app there has ar, en, es, ja, vi, zh language. I want to keep just English and i want to add a new language. What is the steps for that?

2. Screenshots issues:
N/A

3. Proof of my purchased:
https://raw.githubusercontent.com/themeix/temp/master/screenshot-589.png

3. Config files (optional)
Here is the source/lib/common folder, https://we.tl/t-QR5s2cS4Gl

**Comment by aldoyh** [comment]
I've had so much complications in regards to this issue while adding an Arabic version, make sure you keep the current .arb files as reference, then install Flutter Intl
Then from the Menu -> Add language

Now you need to go through all phrases to check if it's compliant with the new syntax.

**Comment by themeix** [comment]
i already did that myself. But i want to know the actual process. Coz it was really time-consuming for me to edit  **lib/generated/i18n.dart file** 
So that topic should include in docs
