### ISSUE TITLE
FluxStore 1.6.3 - Woocommerce] Razor pay crashes in release build

### ISSUE THREAD

**Issue by Lokeswara-betha** [inspireui/support#2103]
1. My issue:
Razorpay working properly in debug mode but when I try to do payment in release build, app crashes it self.
2. Screenshots issues:

3. Proof of my purchased:
![Screenshot_2020-02-14-22-17-53-591_com google android gm](https://user-images.githubusercontent.com/60268240/74625917-f6af6480-5173-11ea-8fb3-8562c1a3797a.jpg)

3. Config files (optional)

**Comment by minhtruong315** [comment]
@Lokeswara-betha if you want to build apk. You can try to add these https://tppr.me/wnfXK
https://razorpay.com/docs/payment-gateway/android-integration/standard/

**Comment by Lokeswara-betha** [comment]
still facing the same issue even after adding the pro guard rules

**Comment by minhtruong315** [comment]
send me your full source code via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/2103
I'll help u check
