### ISSUE TITLE
[FluxStore Listing] - Questions before purchasing Flutter template to work with existing Listeo Wordpress website

### ISSUE THREAD

**Issue by themarveldev** [inspireui/support#2106]
I have an existing website of my client(https://queroau.xyz/)  made using Listeo WordPress theme (https://themeforest.net/item/listeo-directory-listings-wordpress-theme/23239259)

Questions
1. Does it supports central authentication scheme example. Same username/password will work on mobile app (Android & iOS) and WordPress web as well?

2. Does mobile app supports all the WordPress website features?

3. Does it work with firebase authentication?

4. Does it support firebase push notifications as well?

Thanking you in advance for the reply.

**Comment by inspireui-support** [comment]
Hi, thank you for the question, the answers are yes for 1, 3, 4

2. It may not fully feature as listeo, but you can could our demo to get more about the detail feature

Let us know if you have any further queries
