### ISSUE TITLE
[mv-mstore] - whrere to change the left menu background color ? 

### ISSUE THREAD

**Issue by khalidsharif** [inspireui/support#2107]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
I tried to update the style.js under mstore-mv-expo\src\components\LeftMenu to update the left menu background. however, I think it doesn't make any changes 

3. Proof of my purchased:
https://ibb.co/d40dKnD
3. Config files (optional)

**Comment by luyx2412** [comment]
Hi @khalidsharif You can edit in `src/components/Drawer/DrawerMultiChild/index.js`

Thanks

**Comment by khalidsharif** [comment]
I made changes in line 30 but not taking effect!!!
`  static defaultProps = {
    backgroundMenu: "#0863a0",
    colorTextMenu: isDark ? Theme.dark.colors.text : Theme.light.colors.text,
  };`

**Comment by luyx2412** [comment]
Hi @khalidsharif Sorry about that. You can changed in `src/components/Drawer/DrawerMultiChild/index.js`line 221 follow the screenshot.

![image](https://user-images.githubusercontent.com/8909619/74900424-530fbf80-53d2-11ea-8f9a-8d40ab8b16a1.png)

Thanks

**Comment by khalidsharif** [comment]
thanks
