### ISSUE TITLE
[my-product] - FluxStore-woo 1.6.3

### ISSUE THREAD

**Issue by nelson243** [inspireui/support#2108]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: The api is already working as my products are already synced but all the changes made to the config.json doesn't take effect even after so many flutter clean, hot reload, complete restart ....
![Screenshot_1581931544](https://user-images.githubusercontent.com/13100267/74641051-e9dd4180-5170-11ea-82cc-516f19ae02da.png)

2. Screenshots issues:
![Screenshot_1581931484](https://user-images.githubusercontent.com/13100267/74641180-2872fc00-5171-11ea-833f-cf20b446722b.png)
![Screenshot_1581931544](https://user-images.githubusercontent.com/13100267/74641192-2f017380-5171-11ea-8781-3bf5dc90031f.png)

3. Proof of my purchased:
![flux](https://user-images.githubusercontent.com/13100267/74641237-3d4f8f80-5171-11ea-8380-6d7dd4711a2a.png)

3. Config files (optional)
 },
    {
      "layout": "bannerImage",
      "isSlider": true,
      "autoPlay": false,
      "showNumber": false,
      "design": "default",
      "showBackGround": true,
      "radius": 2.0,
      "items": [
        {
          "category": 28,
          "image": "https://gracim.net/wp-content/uploads/2020/01/slider3.jpg",
          "padding": 15.0
        },
        {
          "category": 29,
          "image": "https://gracim.net/wp-content/uploads/2020/01/slider1.jpg",
          "padding": 15.0
        },
        {
          "product": 30,
          "image": "https://gracim.net/wp-content/uploads/2020/01/slider2.jpg",
          "padding": 15.0
        }
      ]
    },
    {
      "layout": "bannerImage",
      "items": [
        {
          "url": "https://gracim.net",
          "image": "https://gracim.net/wp-content/uploads/2020/01/image-mixte.jpg",
          "padding": 5.0
        }

**Comment by inspireui-support** [comment]
Hi, could you share the screenshot of the issues and post to our ticket support - https://github.com/inspireui/support/issues please. Our technical team will take a look and get back you shortly.

**Comment by nelson243** [comment]
Here the screenshot i changed the mail color, banners, logo but still it's not working 
<img width="501" alt="issues" src="https://user-images.githubusercontent.com/13100267/74655971-975e4e00-518d-11ea-9762-7a86432b5c9b.png">

**Comment by dured007** [comment]
If you're using multilanguage, you need to edit configen.json not config.json
if you're only using one language, you need to remove the other configxx files and then edit config.json and it should work.

**Comment by nelson243** [comment]
> If you're using multilanguage, you need to edit configen.json not config.json
> if you're only using one language, you need to remove the other configxx files and then edit config.json and it should work.

Thanks it's solved my problem when i edited the configen.json . I have a question if i need to add also french language what is the process ?

**Comment by inspireui-support** [comment]
you can make new config_fr.json for Fench, and follow this guide to config the language screen https://docs.inspireui.com/fluxstore/multi-language/ - thank you!
