### ISSUE TITLE
[mstore vendor] -  New Version error

### ISSUE THREAD

**Issue by muratakgoz** [inspireui/support#2109]
when I enter the product in the new version
1.I get the error "sorry, you are not allowed to create a post on behalf of this user."
![88c9486c-891f-4ce6-baa3-6e958f1b4243](https://user-images.githubusercontent.com/22097767/74643987-a68dcd80-5186-11ea-9b43-e2989be8ec02.jpg)
I sent my user information to luyxtran264 mail address.
2. Stores are not visible on the vendor page.
![a79af2f2-e05f-4fdd-a37b-a280b29b456a](https://user-images.githubusercontent.com/22097767/74644325-2caa1400-5187-11ea-8b73-262d2d8d2968.jpg)
3. When the store logs in, the products registered in my products are not displayed.
![2aa435dc-825d-4039-989d-c027c85c0548](https://user-images.githubusercontent.com/22097767/74644496-67ac4780-5187-11ea-82a9-6d0a524a2144.jpg)

**Comment by inspireui-support** [comment]
Hi, could you share the screenshot of the issues and post to our ticket support - https://github.com/inspireui/support/issues please. Our technical team will take a look and get back you shortly.

**Comment by inspireui-support** [comment]
@muratakgoz - could you zip the common folder and send us for checking 

- thank you!

**Comment by muratakgoz** [comment]
do you give mail?

**Comment by muratakgoz** [comment]
[common.zip](https://github.com/inspireui/support/files/4219701/common.zip)

**Comment by muratakgoz** [comment]
how are we doing

**Comment by muratakgoz** [comment]
why don't you help?

**Comment by muratakgoz** [comment]
why dont you answer me??? SO URGENT PROBLEM. YOUR APP DOESNT WORK. THAT IS ENOUGH

**Comment by inspireui-support** [comment]
sorry for the issue - we have updated your refund request
