### ISSUE TITLE
[Beonews] New version 2.9.2 missing FBSDKShareKit.h

### ISSUE THREAD

**Issue by hungnguyen9276** [inspireui/support#211]
**Mandatory Info (please complete the following information):**
 - Product: [Beonews]
 - Your Purchased Code: 2b7fa788-ea4d-4d1c-bb3a-4bf22a499783

**Describe the issues**
New version 2.9.2 missing FBSDKShareKit.h. Project only run on android and get errors when I try to run ios

**Screenshots**
<img width="1279" alt="screen shot 2019-01-25 at 20 22 38" src="https://user-images.githubusercontent.com/25025251/51748512-3d509d80-20df-11e9-8461-d037437d60fa.png">

**Additional context**
Add any other detail logs about the problem here.

**Comment by hadi13** [comment]
fixed and got another error 
<img width="441" alt="screen shot 2019-01-28 at 12 22 08 pm" src="https://user-images.githubusercontent.com/2642454/51826133-60559a00-22f7-11e9-85c9-521a5dfb2dfc.png">
