### ISSUE TITLE
FluxNews - Translation error

### ISSUE THREAD

**Issue by danimmg** [inspireui/support#2113]
It is the 3 ticket that is closed without having solved my problem: 

https://github.com/inspireui/support/issues/2055
https://github.com/inspireui/support/issues/2081

As I mentioned I need to translate these terms to deliver the project that is late, please send the correction to me.
![74424427-b2009200-4e30-11ea-9e1c-37e5419ae1bf](https://user-images.githubusercontent.com/59834619/74652849-b648ea00-5165-11ea-836b-e19308862974.jpg)
![74424429-b2992880-4e30-11ea-9666-23161cc4efd0](https://user-images.githubusercontent.com/59834619/74652855-b77a1700-5165-11ea-8a45-f014da00e4ca.jpg)

**Comment by dttrung26** [comment]
Hi @danimmg ,
I was so careless that did not pay attention to this bug on your previous reports. This will be fixed in v1.3 which will be released tomorrow. So sorry for delaying your app release. 
Nice day,
Trung.
