### ISSUE TITLE
[Fluxstore] -  How to change the left side menu icon?

### ISSUE THREAD

**Issue by themeix** [inspireui/support#2114]
1. My issue:
How to change the menu icon to a regular humburger icon?
2. Screenshots issues:
https://raw.githubusercontent.com/themeix/temp/master/screenshot_595.png
3. Proof of my purchased:
https://raw.githubusercontent.com/themeix/temp/master/screenshot-589.png
3. Config files (optional)

**Comment by inspireui-support** [comment]
@themeix - pls try to use Inspector to change any UI from the app - https://docs.inspireui.com/fluxstore/useful-tip/#how-to-change-the-ui-quickly - thanks
