### ISSUE TITLE
Fluxstore 

### ISSUE THREAD

**Issue by arslan9999** [inspireui/support#2116]
Hi,
Yesterday I just purchased Fluxstore I seems to look fine till now but when I Register Account Display just went black and when I close app and open it again it opens using that registered account
![Screenshot_1581943902](https://user-images.githubusercontent.com/50184064/74655812-cdf89080-51ae-11ea-8f27-1ac90ed91ae1.png)
Purchase Proof:
![image](https://user-images.githubusercontent.com/50184064/74655896-fa141180-51ae-11ea-99f3-50b758e0636f.png)

**Comment by inspireui-support** [comment]
@arslan9999 - could you check the debug log from Android studio so see if there are any log issues 

@kvt0012 - please help for investigating this test case

**Comment by arslan9999** [comment]
Android Studio Output:
`I/BiChannelGoogleApi(19499): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@2b2094c`

`I/flutter (19499): [Fluxstore][Resistration] PlatformException(ERROR_INVALID_EMAIL, The email address is badly formatted., null)`

`I/zygote  (19499): Background concurrent copying GC freed 65445(3MB) AllocSpace objects, 20(1040KB) LOS objects, 50% free, 3MB/6MB, paused 7.529ms total 59.950ms`

**Comment by kvt0012** [comment]
Dear sir, 
Please help me make your problem clearly. Do you config any file on our source? 
Thank you

**Comment by arslan9999** [comment]
No I just opened APP on Android Studio and changed Name and Woocommerce Keys and run it

**Comment by kvt0012** [comment]
Thanks sir, 
Can you send us your common folder, we will check it for you. 
Thank you

**Comment by arslan9999** [comment]
Here you go, I have my Common Folder
[common.zip](https://github.com/inspireui/support/files/4225159/common.zip)

**Comment by kvt0012** [comment]
I'll check your problem but with my device, it's just black at the moment ( it is loading). 
Please tell me which simulator you use for test this app? Thank you

**Comment by arslan9999** [comment]
I checked it on Pixel 3 XL 8.1 and on physical hardware I checked with Samsung Galaxy S7 Edge 8.0

**Comment by kvt0012** [comment]
I'll check on Pixel 3 XL 8.1 and it takes a little bit longer to access to app as well as sign up, maybe that I test on the new release of this app. We'll upload the new release on this week. Until that, you can try a version 9.0 of android, I usually use it and it runs more stable.

**Comment by arslan9999** [comment]
OK, and can you please tell me location of side menu config file?

**Comment by kvt0012** [comment]
You can check this guide, we write all on this, if you have any question please tell us 
https://docs.inspireui.com/fluxstore/home-layout/
