### ISSUE TITLE
[Fluxstore Pro] - Prices don't change according to the variations (app bug)

### ISSUE THREAD

**Issue by Alnaggar94** [inspireui/support#2119]
1. My issue:

There is a bug in the app, the prices don't change according to the variations, for example, the product "A" has 3 variations (1 piece= $10 / 12 pieces=$100 / 24 pieces=$180) it works fine in the website, but in the app it doesn't show the price according to the chosen variations it shows random variation price and stick to it even if you choose different variation the price remains the same. 

2. Screenshots issues:

Here it works fine in the website - http://arabicpharmacy.com/product/air-wick-f-matic-refill-rose-250ml/?lang=en

![x3](https://user-images.githubusercontent.com/49800146/74664907-b1108d00-51af-11ea-8305-8828ecff03a3.JPG)

![x4](https://user-images.githubusercontent.com/49800146/74664918-b7066e00-51af-11ea-8019-218a8f9a00eb.JPG)

but in the app: 
(It's supposed to be $180 but it show $10 )
![x1](https://user-images.githubusercontent.com/49800146/74665142-20867c80-51b0-11ea-96a2-ae49939f8eb3.JPG)

![x2](https://user-images.githubusercontent.com/49800146/74665046-f46afb80-51af-11ea-9645-a9995ef48dcc.JPG)

3. Proof of my purchased:

https://www.dropbox.com/s/a72d73tka8rsa90/Capture.JPG?dl=0

3. Config files (optional)

Config.dar:
https://www.dropbox.com/s/3iwgl7e6gidqhsj/config.dart?dl=0

Config_en.json:
https://www.dropbox.com/s/8tkz3ss53g51h52/config_en.json?dl=0

**Comment by Alnaggar94** [comment]
@minhcasi @minhtruong315 - After doing many tests I found out the problem happing in the English language and work fine when I change the language to Arabic (My default language in WordPress is Arabic and I translate content with WPML to English).

see this short video more explaining - https://imgur.com/P5j19TF

**Comment by minhtruong315** [comment]
@Alnaggar94 Can u send me full source code via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/2119

**Comment by Alnaggar94** [comment]
@minhtruong315 I sent it to your Email.

**Comment by Alnaggar94** [comment]
@minhcasi @minhtruong315 - Any update ??

**Comment by inspireui-support** [comment]
@minhtruong315 - pls also investigating the issue 2184 - thank you!

**Comment by minhtruong315** [comment]
@Alnaggar94 I messaged you on the skype. Please check. Thanks

**Comment by minhtruong315** [comment]
[product.mov.zip](https://github.com/inspireui/support/files/4247450/product.mov.zip)
@Alnaggar94 I checked your website. but i see the price doesn't change when change variant

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
