### ISSUE TITLE
[ListPro] ListApp Manager plugin warning issue

### ISSUE THREAD

**Issue by chad-the-first** [inspireui/support#212]
- Product: [ListPro]
 - Your Purchased Code: 65e47917-78fa-4b8e-97ec-80bf8345f72a

**Describe the bug**
the app can't populate the listing from my website. www.cataloglebnen/wordpress
i just changed the website url and the category id in config.

i do get this msg when i open my listing in wordpress:
Warning: array_map(): Argument #2 should be an array in /home2/chadwebdev/cataloglebnen.com/wordpress/wp-content/plugins/listapp-mobile-manager/rest-api/class.api.fields.php on line 314
Warning: array_filter() expects parameter 1 to be array, null given in /home2/chadwebdev/cataloglebnen.com/wordpress/wp-content/plugins/listapp-mobile-manager/rest-api/class.api.fields.php on line 314

**Screenshots**
![sketch1](https://user-images.githubusercontent.com/17035853/51750115-c2c15700-20b9-11e9-9a58-9bd19a6d08f0.png)
I enabled listings in rest-api

![sketch2](https://user-images.githubusercontent.com/17035853/51750201-fdc38a80-20b9-11e9-86f6-34aef8b339c6.png)
this is what i see when the app opens  

![sketch3](https://user-images.githubusercontent.com/17035853/51750352-86422b00-20ba-11e9-866d-09d65e7ebdc4.png)
and i get this error when i click on the black banner.

**Comment by minhcasi** [comment]
Hi, could you try to disable the Debug mode from wp-config.js file to disable the warning message from php log ?

@thangvo9x - try to fix the array_filter and array_map issues - http://www.cataloglebnen.com/wordpress/wp-json/wp/v2/listing

**Comment by chad-the-first** [comment]
Debug mode is already disabled. 
@thangvo9x - any suggestion on how to fix this issue from the listapp-mobile-manager plugin?

**Comment by thangvo9x** [comment]
Hi. Thanks for your purchase. Can you share your admin help me, plz?

**Comment by chad-the-first** [comment]
Hi @thangvo9x i made an editor user for the wordpress website, u can check the credentials in your email.

**Comment by thangvo9x** [comment]
some problems is occuring on your website. 
http://cataloglebnen.com/wordpress

**Comment by thangvo9x** [comment]
I can't login or set password. check screenshot. How about your problem ? 
http://prntscr.com/men85h
Thanks

**Comment by thangvo9x** [comment]
@chad-the-first

**Comment by chad-the-first** [comment]
i sent the email again to thang@inspireui.com you can check by searching for chad-the-first in the subject of the email.

**Comment by chad-the-first** [comment]
@thangvo9x

**Comment by chad-the-first** [comment]
@thangvo9x I'm still waiting your help so I can develop the application.
