### ISSUE TITLE
[Fluxstore] - Facebook account login not working for Live APP

### ISSUE THREAD

**Issue by themeix** [inspireui/support#2121]
1. My issue:
I am getting the following error. Screenshot attached. My app live on play store but getting an error while trying to login via Facebook. 

Can you tell me where i will find the settings for hashkey or what actually need to do? Any video would be appreciated or any docs.

2. Screenshots issues:
https://raw.githubusercontent.com/themeix/temp/master/f.jpg
3. Proof of my purchased:
https://raw.githubusercontent.com/themeix/temp/master/screenshot-589.png

4. Config files (optional)
Not need

**Comment by inspireui-support** [comment]
@themeix - one can go the link from Facebook app admin and add and hash key from Google Play console, select Release management / App signing - copy the hash key and past to facebook admin.

You may need to do the same for Firebase config as well to fix the SMS login.

Kindly post to the same ticket for your issue on #2097 to help to team easily follow up on your all issues - thank you!

**Comment by themeix** [comment]
I just sent you a email. 
Subject : 
[Fluxstore] Webview not working for checkout

Please reply there, I am stuck on that project for these bugs.
