### ISSUE TITLE
[Fluxstore] - Order Note not working 

### ISSUE THREAD

**Issue by themeix** [inspireui/support#2123]
My issue:
If i place order form App the customer note is not working.

Screenshots issues:
https://i.postimg.cc/8zqBLFB1/screenshot-597.png

Proof of my purchased:
https://raw.githubusercontent.com/themeix/temp/master/screenshot-589.png

Config files (optional)

**Comment by inspireui-support** [comment]
@themeix - would you mind to share the admin login to support@inspireui.com so that we could help for investigating - thank you!

**Comment by themeix** [comment]
I shared the admin login and github repo access to 
hieu.trantrung1204@gmail.com
Please check it there

**Comment by inspireui-support** [comment]
@themeix - pls noted and moved this issue to the ticket - #2097 - thank  you!
