### ISSUE TITLE
[FluxStore] - Where Arabic Language in FluxStore

### ISSUE THREAD

**Issue by limitlessfirm** [inspireui/support#2124]
---------

1. My issue: where Arabic Language in new release of FluxStore 

and how i can delete or disable another language like japans

2. Screenshots issues:
![arabic](https://user-images.githubusercontent.com/59250639/74686998-d1eed780-51db-11ea-8395-a2b3f3b15f6e.JPG)

3. Proof of my purchased:
![screenshot](https://user-images.githubusercontent.com/59250639/74687008-d9ae7c00-51db-11ea-9028-0c1305a06f58.JPG)

3. Config files (optional)

**Comment by inspireui-support** [comment]
@limitlessfirm - sorry for the issue - we will get it back on next release 

In the meantime, you can update this attach file (rename the language.dart.txt to language.dart)

Thank you!
[language.dart.txt](https://github.com/inspireui/support/files/4217104/language.dart.txt)

**Comment by Senior-Gamal** [comment]
hello
you can edit language list from 
source/lib/screens/language.dart
