### ISSUE TITLE
[Mstore Pro]

### ISSUE THREAD

**Issue by m00ndoggy** [inspireui/support#2125]
I have purchased Mstore Pro and installed CeBuilder. I have installed all packages needed. Watched the youtube videos. When I am selecting the project folder with the package.json inside, nothing happens. 

https://prnt.sc/r3sbjt

**Comment by inspireui-support** [comment]
@m00ndoggy - could you take the screenshot after select folder - https://tppr.me/JsqhL

Also try to move the project folder to C: drive to see if can be fixed - thanks

**Comment by m00ndoggy** [comment]
After I press "select folder" that box is not filled with any path. It remains blank.

**Comment by m00ndoggy** [comment]
https://prnt.sc/r4568k

This is how it looks after i select the folder. I have moved it to C:

**Comment by m00ndoggy** [comment]
I have bought FluxStore first just to find out that it doesnt work and chat support said that only MStore Pro works with CeBuilder. Now I see that doesnt work too... At least you should have some refund policy  or fix this bugs please.

**Comment by napoleon2121** [comment]
i hav the same exact problem with CeBuilder.

**Comment by m00ndoggy** [comment]
If i have installed cebuilder 3.8, its doing this. At least it loaded my path

https://prnt.sc/r53oiw

**Comment by m00ndoggy** [comment]
UPDATE: CeBuilder 3.8 loaded mstore expo but not Mstore PRO

**Comment by napoleon2121** [comment]
at Mstre pro it gives me this error..

![image](https://user-images.githubusercontent.com/4322518/74932654-05ec1780-53eb-11ea-8246-eff608d00799.png)

**Comment by m00ndoggy** [comment]
Another error https://prnt.sc/r5a61r   I am getting tired

**Comment by m00ndoggy** [comment]
https://prnt.sc/r5achm Tried using the youtube tutorial. After i enter "expo start" command, it opens for 2 seconds and after that i get this error

**Comment by inspireui-support** [comment]
@m00ndoggy your expo-cli seems not using the latest version please try to run
```
npm install expo-cli -g
```
