### ISSUE TITLE
Fluxstore Can't build when we change the package name  

### ISSUE THREAD

**Issue by hssinaman** [inspireui/support#2126]
---------

1. My issue:  Fluxstore can't build the app when we change your original package name to our new package name  

2. Screenshots issues:
![package name](https://user-images.githubusercontent.com/61097607/74703176-a0423480-520c-11ea-89e4-08b345b22288.png)

3. Proof of my purchased:
![purchase proof](https://user-images.githubusercontent.com/61097607/74703187-ae905080-520c-11ea-9a52-9ea861226354.jpg)

3. Config files (optional)

**Comment by minhtruong315** [comment]
@hssinaman did you follow this guide to change package name?
https://docs.inspireui.com/fluxstore/customization/

**Comment by hssinaman** [comment]
we are trying the guid now 
we will let you know if the issue is fixed 
thank you

**Comment by hssinaman** [comment]
We just try following it
We will let you know if the issue is solved

**Comment by hssinaman** [comment]
the issue has been fixed 
thank you
