### ISSUE TITLE
Fluxstore - 33 Errors - 5 Android 21 General 6 Internationalization 7 JSON 15 XML

### ISSUE THREAD

**Issue by gurutos** [inspireui/support#2128]
Good Day Support Team,

1. My issue:
Im working with windows and android studio. 

Following the video ( Install Fluxstore on Windows ) I open an existing project, i got dependencies and execute flutter doctor returning everything ok(check).
 
Then at the top of menu i Clic ( analyze - inspect code ), but im getting 33 issues. 

Can you please let me know if this is "normal"? 

Errors details: 
![image](https://user-images.githubusercontent.com/61175861/74706987-7a099e00-51e6-11ea-9bb1-c8e4fec20e70.png)

![image](https://user-images.githubusercontent.com/61175861/74707008-8aba1400-51e6-11ea-946a-86115a71dd46.png)

![image](https://user-images.githubusercontent.com/61175861/74707035-9e657a80-51e6-11ea-8725-b9c4fdf525df.png)

**2. Screenshots issues:**
![image](https://user-images.githubusercontent.com/61175861/74706360-afad8780-51e4-11ea-896f-ab2b25ad7ef9.png)

**3. Proof of my purchased:**
![image](https://user-images.githubusercontent.com/61175861/74705746-f7cbaa80-51e2-11ea-899d-1a459b11e835.png)

Thanks and Regards,

**Comment by inspireui-support** [comment]
Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads  it's used to verify your proof of purchase? sorry for any inconvenience - please include your Envato username on the screenshot - Thank you!

**Comment by gurutos** [comment]
Hello Support Team,

Next its the image with the purchased

![image](https://user-images.githubusercontent.com/61175861/74761989-00f06200-524b-11ea-86cd-638578b62da2.png)

Thanks and Regards,

**Comment by gurutos** [comment]
Good day support team,

Can you tell me why did you closed this without an answer?

Thanks and Regards,
