### ISSUE TITLE
Mstore Pro not working payments getway

### ISSUE THREAD

**Issue by mdyunus24bd** [inspireui/support#2129]
1. My issue:

- Apps not working for Payment Getway, my Website there a Direct Bank transfer & paypal Express checkout(Credit/debit card payment & paypal ).How to set a payment .

- not Show a Image on apps how to set a Image on Payments Method image.

- i cilck a confrim order go direct my website Checkout page.

- product image not loading

- category not loading 

- 

2. Screenshots issues:
https://prntscr.com/r3vefb
https://prntscr.com/r3ve1y
https://prntscr.com/r3vdmp
https://prntscr.com/r3vdj5
https://prntscr.com/r3vdgx
https://prntscr.com/r3vdgx
https://prntscr.com/r3vddb

3. Proof of my purchased:

Purchase code: 14ff322a-3ecb-4362-a8b1-d6b0c4d27675

3. Config files 
https://github.com/mdyunus24bd/file

**Comment by mdyunus24bd** [comment]
I don't understand

**Comment by luyx2412** [comment]
Hi @mdyunus24bd Sorry about reply you late. 
Please make sure you installed your wordpress and mobile config follow the document https://docs.inspireui.com/mstore/getting-started/

Thanks

**Comment by minhcasi** [comment]
@mdyunus24bd - pls let us know if you could run the project so far, also make sure to update the latest mstore-api - https://wordpress.org/plugins/mstore-api/

Feel free to reopen the ticket if the issues still happened - very best!
