### ISSUE TITLE
[MStore] App not loading

### ISSUE THREAD

**Issue by netappzone** [inspireui/support#213]
**Required Info (please complete the following information):**
 - Product: [e.g. MStore, ListApp]
 - Your Purchased Code: [get from https://codecanyon.net/downloads]
(we may not reply if you are not our customer)

**Describe the bug**

**Screenshots**

**Additional context**
Add any other detail logs about the problem here.
If possible please share your config.js that use for the app setting

I am using MStore Pro and this is the screenshot of the error.
![image](https://user-images.githubusercontent.com/33864849/51763132-0a53dd00-20d2-11e9-8e74-a992a6b4bd1e.png)

**Comment by minhcasi** [comment]
Hi, could you help to run `yarn setup` from the project download folder (please don't try to copy to another folder as you could miss some hidden file, such as .babelrc):
