### ISSUE TITLE
[Fluxstore MV app] - A non-null String must be provided to a Text widget.

### ISSUE THREAD

**Issue by kenngigz** [inspireui/support#2131]
════════ (6) Exception caught by widgets library ═══════════════════════════════════════════════════
A non-null String must be provided to a Text widget.
'package:flutter/src/widgets/text.dart':
Failed assertion: line 285 pos 10: 'data != null'
The relevant error-causing widget was: 
  InfoItem file:///C:/Users/quizzer/Downloads/flutter_windows_v1.12.13+hotfix.7-stable/gwgom/FluxStore-vendor-1.6.3/source/lib/screens/store_detail/contact.dart:42:11

![Capture 3](https://user-images.githubusercontent.com/57593885/74715775-35a9ec80-523e-11ea-8298-c9db3de1b9f5.PNG)
![Capture 4](https://user-images.githubusercontent.com/57593885/74715778-36db1980-523e-11ea-9c20-4944123f6eff.PNG)
![Capture 5](https://user-images.githubusercontent.com/57593885/74715779-3773b000-523e-11ea-9cbe-9adc125695ee.PNG)
![capture 2](https://user-images.githubusercontent.com/57593885/74715781-380c4680-523e-11ea-820e-ddb0d72ca9d7.PNG)
![Capture](https://user-images.githubusercontent.com/57593885/74733309-1cfcff00-525d-11ea-8673-ce6d166004f1.PNG)

**Comment by inspireui-support** [comment]
@kenngigz - pls help to take the screenshot purchase include your username - thank you!

**Comment by kenngigz** [comment]
just updated

**Comment by minhtruong315** [comment]
@kenngigz can u send me config files?

**Comment by kenngigz** [comment]
[ezyzip.zip](https://github.com/inspireui/support/files/4228954/ezyzip.zip)

**Comment by kvt0012** [comment]
Dear sir, 
Can you send me the whole project ?  
Thank you

**Comment by inspireui-tech** [comment]
@kenngigz - pls note that we could not reproduce the issue, also try to use the latest version for the fixing
