### ISSUE TITLE
FluxStore 1.6.3 - Woocommerce] Variable products prices not displaying properly 

### ISSUE THREAD

**Issue by Lokeswara-betha** [inspireui/support#2133]
My issue:
In WooCommerce , it's displaying dropdown for the variable products , but in the application it it showing variable product price as 0 and not showing any dropdown.

Screenshots issues:

![74437453-26b5e980-4e8e-11ea-94ae-72deea6d63f4](https://user-images.githubusercontent.com/60268240/74719323-ce019a80-5259-11ea-8714-12755930498d.png)

Proof of purchase:

![74625732-55c0a980-5173-11ea-8497-421d5143ac47](https://user-images.githubusercontent.com/60268240/74719377-e8d40f00-5259-11ea-830c-184e86a4cb69.jpg)

**Comment by inspireui-support** [comment]
@Lokeswara-betha - could you zip the common folder that we could help for checking - thank you!

**Comment by Lokeswara-betha** [comment]
I'll upload it in  google drive and share with you. Is that ok?

**Comment by Lokeswara-betha** [comment]
[common.zip](https://github.com/inspireui/support/files/4220885/common.zip)
I have attached common folder

**Comment by kvt0012** [comment]
Dear sir, 
I'll check your problem and I figure out that your product on mobile phone and product on your website in your picture is 2 different products. One is Basmathi and the another is barnyard 
And I'll check the barnyard and on our app store and it is displayed the price like this. 
![image](https://user-images.githubusercontent.com/49152325/75003346-02fc3000-549a-11ea-8d7e-20654b2f4dcc.png)

Thanks for your issue.

**Comment by Lokeswara-betha** [comment]
Yes , But it is not displaying the drop down to select the weights.

**Comment by Alnaggar94** [comment]
@kvt0012 @inspireui-support -  This issue same as my problem https://github.com/inspireui/support/issues/2119 it gets closed without any solution !!

**Comment by kvt0012** [comment]
@Lokeswara-betha  
Dear sir, this feature is still not available on this store, so we will try to do this on the future.

**Comment by kvt0012** [comment]
@Alnaggar94  
Dear sir, I check and it is not closed, you can comment to boost it up and my brother will help you fix it. 
Thank you.
