### ISSUE TITLE
Rejected by Apple App Store

### ISSUE THREAD

**Issue by Royce77** [inspireui/support#2136]
Hi there, I submitted my app [EVA STORE] and was rejected due to the checkout page not loading. Is this a known issue and can you please assist me?

"We discovered one or more bugs in your app when reviewed on iPad running iOS 13.3.1 on Wi-Fi.

Specifically, we noticed that the loading indicator spun indefinitely upon checkout."

screenshot: https://iosapps-ssl.itunes.apple.com/itunes-assets/Purple114/v4/0d/15/ec/0d15ec5a-7c01-d0fc-7095-bebc4bf07293/attachment-9414603645959710093Screenshot-0216-174516.png?accessKey=1582275909_7799040531208958287_rgZfF7yIHOY70t8IvqeTksSzTLlRmd4fphSRYA6FP9ZvA3PCfAzgEkeyQa5H3kWZU03DloPvT%2BTJJb7B%2B7fwF8tRYmrG0GC9axVwVyOKUUKT8bSozRSft7RPtQWtuhBeY3%2FEzNhJYDRDUGI4gDWl2zSdsYQdQZ9GnqvSwLdHByg4HdVGB5a0V%2BcJkHtma4rByjzS%2FFaNdD8UAp8bErZaXQ%3D%3D

**Comment by inspireui-support** [comment]
Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads  it's used to verify your proof of purchase? sorry for any inconvenience - Thank you!

**Comment by Royce77** [comment]
Hi There,

Please see attached.

Thanks.

**Comment by Royce77** [comment]
I believe this to be a WebView issue. As no external ink pages work (About us) etc.

**Comment by Royce77** [comment]
Yes, works perfectly on the web. 
I even downloaded a latest version of Eva Store with all your store and none of your links or checkout works.
