### ISSUE TITLE
[MStore-Pro] Temporary Checkout option

### ISSUE THREAD

**Issue by sashaba** [inspireui/support#214]
Hello
so, I'm still struggling with checkout on my app, I haven't been able to fix the issue with the error message "unfortunately we do not ship to xxx country";  so I was wondering if there is a way to disable MstoreCheckout temporally. I can try to add PayPal SDK to the app natively as unique payment method while this issue is resolve.  I don't mind having just one payment method as long as it works properly.

**Comment by sashaba** [comment]
It seem  fixed now.
thank you.

**Comment by minhcasi** [comment]
Thank you, could you share your solutions?

**Comment by sashaba** [comment]
Still not working, I installed a different payment gateway plugin on my website and it worked at first, but now the error came back. Still no solution to this. 

I think the issue is with the new woocommerce API not updated on mstore-checkout.

**Comment by sashaba** [comment]
Another thing I noted, is :

After we select payment method on the app and confirm order, if the webview fetch only the country code (US) the order go thru, but if the whole country name is displayed the error appears.

To explain better:

If the app auto fill only the country code on the checkout webview the order is susessfull.  But if the full country name is auto filled the error appears.
