### ISSUE TITLE
[MStore Pro] - HomePage "tag" id related banners crashes

### ISSUE THREAD

**Issue by gokhand** [inspireui/support#2140]
The issue:
On the homepage, if you use banner versions of the homepage like "2-Banner Image.json", the banner images section shows on the homepage and when you clicked the second banner it is working well, it lists the items.

But if you select any other product category on the left menu and returned to the homepage, the same banner when you clicked is not working and eventually crashed. When I checked the JSON file again, this is happening if the banner has "tag" instead of "category". If it has category id it is going through, if it has tag id unfortunately it crashes.

![image](https://user-images.githubusercontent.com/3597701/74747997-b88f6f00-525f-11ea-9f81-09a0f1d13987.png)

Could you please check?
Thanks

Proof of purchase previously opened on discussion page "https://codecanyon.net/item/beostore-complete-react-native-template-for-ecommerce/17010642/comments?page=109&filter=all#comment_23567125" and the issue in here: "https://github.com/inspireui/support/issues/1948"

**Comment by luyx2412** [comment]
Hi @gokhand can you send me Config.js and AppConfig.json ?

Thanks

**Comment by gokhand** [comment]
Hi,

You can test at least your latest 3.9.8 version to see the error.

I used in your version just use "2-Banner Image.json" from the AppConfig theme folder and replace on AppConfig.json file. So basically in this way you will see the banner version of your app.

Here you can see a video that your app with your settings I mentioned above:
[mstore-crash-test.mov.zip](https://github.com/inspireui/support/files/4229932/mstore-crash-test.mov.zip)

On the left banner as I said it is using category id, the second one is using tag id.
It will give you a clue to identify the issue I think.

Thanks

**Comment by gokhand** [comment]
Is there any update on this, if you need extra info please let me know.

**Comment by luyx2412** [comment]
Hi @gokhand Please send me 2-Banner Image.json and Config.js to investigate about it.

Thanks

**Comment by gokhand** [comment]
Don’t you have your mstore 3.9.8 ?
The screen capture video and all configs are your mstore 3.9.8 release. You can just open your release and use “2-Banner Image.json" from the AppConfig theme folder and replace on AppConfig.json file , then you will see the error. I can send my own settings but you can also see from your 3.9.8 release the error is there. 

Please let me know if you really needed that files, you should already have it.

Thanks

**Comment by gokhand** [comment]
I have sent the files to your email.

Thanks

**Comment by luyx2412** [comment]
Hi @gokhand i just checked the latest version which everything worked normal. Can you describe more about your issue?

Thanks

**Comment by gokhand** [comment]
Hi, id you watched the video that I take , it shows the issue on the app.
This is exactly what I am experiencing the issue.
The video of the issue:
https://github.com/inspireui/support/files/4229932/mstore-crash-test.mov.zip

**Comment by luyx2412** [comment]
Hi @gokhand 
- The first please change your `imageBanner` with specific url image look like the screen shot
![image](https://user-images.githubusercontent.com/8909619/75687092-daf9a180-5ccf-11ea-8bbe-0db1fd1fc324.png)
- And i just tested your AppConfig.json which worked normal. 
![image](https://user-images.githubusercontent.com/8909619/75687301-2d3ac280-5cd0-11ea-8a0d-580c8d27e957.png)

So are you still happen the issue?

Thanks
