### ISSUE TITLE
final step at renaming folders[mstorepro] - 

### ISSUE THREAD

**Issue by napoleon2121** [inspireui/support#2143]
Hi again. i did all the config as the tutorial sais .exaclty as it sais it.

here is my last error i get.
someone help plz. i am stuck !!!

![image](https://user-images.githubusercontent.com/4322518/74788480-865f2b00-52ba-11ea-96ea-4234b25155a3.png)

**Comment by inspireui-support** [comment]
Duplicate of #2125 
- pls move the conversation to 2125
