### ISSUE TITLE
[FluxStore-MV] - Release App Turns Blank After Login Using Email

### ISSUE THREAD

**Issue by saifmuhtar** [inspireui/support#2144]
1. My issue: 
After I login using email on **release version**, the app turns blank. While when I login using email on **debug version**, error notification is appear.

2. Screenshots issues:

![Screenshot_1582069212](https://user-images.githubusercontent.com/34681804/74787978-76ac0a80-52eb-11ea-949b-8903d22fed32.png)

3. Proof of my purchased:

![72332982-fc89d400-36f5-11ea-9307-f8c418404111](https://user-images.githubusercontent.com/34681804/74788013-90e5e880-52eb-11ea-8bc7-538d80c98d23.jpg)

4. APK Release:
https://we.tl/t-iQXSH2Cto4

Thank you.

**Comment by inspireui-support** [comment]
We have fixed on the latest version - it will be release tomorrow - thanks

**Comment by saifmuhtar** [comment]
Thank you for your fast response. 👍🏻😃

**Comment by inspireui-tech** [comment]
@saifmuhtar - please help to use the latest release 1.6.4 to fix this issue, let us know if you have any further issue ☺️ - thank you!
