### ISSUE TITLE
[FLUXSTORE] - APP NO LONGER DISPLAYS PRODUCTS

### ISSUE THREAD

**Issue by patrickubong** [inspireui/support#2149]
My App was working perfectly until recently when it stopped displaying products or anything from the backend to the App. I have checked everything within my own knowledge but cant find any solution. Please help.
Credentials for backend has been sent to your email

App links on Stores
https://play.google.com/store/apps/details?id=com.delefresh.payfarmer&hl=en
https://apps.apple.com/in/app/payfarmer/id1495802801

Screenshot of Payment
![fluxstore purchase](https://user-images.githubusercontent.com/5703312/74814011-a44a8100-52f6-11ea-902e-bcc90bb48b95.png)

**Comment by minhtruong315** [comment]
@patrickubong is it working on your source code but don't work on app in store?

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
