### ISSUE TITLE
[CEbuilder] - Error when running CEbuilder for MSTORE

### ISSUE THREAD

**Issue by banchyman** [inspireui/support#215]
![screenshot_1](https://user-images.githubusercontent.com/47045593/51779091-f0a5aa80-2150-11e9-9660-53a3c848b836.jpg)
**Required Info (please complete the following information):**
 - Product: [e.g. MStore, ListApp]
 - Your Purchased Code: [get from https://codecanyon.net/downloads]
(we may not reply if you are not our customer)

**Describe the bug**

**Screenshots**

**Additional context**
Add any other detail logs about the problem here.
If possible please share your config.js that use for the app setting

**Comment by SAVICTOR** [comment]
Have you installed expo?

**Comment by minhtruong315** [comment]
Hi @banchyman, Did you install all tools?
<img width="1028" alt="screen shot 2019-01-27 at 4 55 45 pm" src="https://user-images.githubusercontent.com/10402500/51799535-8c6c0f00-2254-11e9-9f1b-0b137d35e04c.png">

**Comment by banchyman** [comment]
I do not, where do I download it for windows 10?

Kind Regards
Jesse & Bec

Contact:
Email: bristleup@live.com.au
Mobile: 0427312312


________________________________

**Comment by wcreativo** [comment]
I have all tools installed buy I have the same issue

**Comment by minhtruong315** [comment]
@wcreativo which cebuilder version is you using?

**Comment by wcreativo** [comment]
0.3

**Comment by minhtruong315** [comment]
can you share me teamviewer? I will help you check it

**Comment by wcreativo** [comment]
sure
1 212 874 060
pass: v14ka8
my domain is ubigo.com.co

**Comment by minhtruong315** [comment]
done
