### ISSUE TITLE
[Fluxstore Listing] - App freezes when loading further blog posts

### ISSUE THREAD

**Issue by Bingo2000** [inspireui/support#2150]
When Refreshing Blog Listing app freezes with different errorr:

![Bildschirmfoto 2020-02-19 um 11 05 42](https://user-images.githubusercontent.com/13098762/74828115-d5cf4680-530e-11ea-8637-44bbc976e546.jpg)
![Bildschirmfoto 2020-02-19 um 11 05 55](https://user-images.githubusercontent.com/13098762/74828119-d962cd80-530e-11ea-8817-688c324b4a63.jpg)

![BingoEnvato](https://user-images.githubusercontent.com/13098762/74827996-9dc80380-530e-11ea-8164-4bfd188cf90d.jpg)

**Comment by philipvu30** [comment]
Hi @Bingo2000 ,
Please replace this file in lib/widgets/blog/blog_list_view.dart
[blog_list_view.zip](https://github.com/inspireui/support/files/4229904/blog_list_view.zip)
Hope it will solve your problem. Thank you

**Comment by Bingo2000** [comment]
Hi,

thank you. That works!

An other issue
I want to change the route to the blog view , which is taken with the link in bottom bar,
because this route leads to a card view, but I want to show the blog_list_view with this link.

Where is the route defind an where can I edit bottom bar code?

Thanks

 Ingo


> Am 20.02.2020 um 10:37 schrieb philipvu30 <notifications@github.com>:
> 
> Hi @Bingo2000 <https://github.com/Bingo2000> ,
> Please replace this file in lib/widgets/blog/blog_list_view.dart
> blog_list_view.zip <https://github.com/inspireui/support/files/4229904/blog_list_view.zip>
> Hope it will solve your problem. Thank you


INGO HAECK | SÜRTHER FELDALLEE 14 | 50999 KÖLN
TEL: +49 (0) 221 / 204 294 50
MOBIL: +49 (0) 176 / 260 180 82
INGO.HAECK@GMAIL.COM





BARYTAGE FOTOGRAFIE PORTOLIO <https://barytage.de/>

**Comment by philipvu30** [comment]
Hi @Bingo2000 ,

Please post only bugs, errors or wanted features on the github. As the issue above is your preferred customization, please contact me through Skype. Thank you.
