### ISSUE TITLE
[my-product] - webview payment white blank 

### ISSUE THREAD

**Issue by azamcsc** [inspireui/support#2154]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
when checkout for payment webview it turn blank, already install plugin as tuto here https://docs.inspireui.com/fluxstore/multi-payment/ , im paste url order generate by app to browser..it show fine..but not when open in webview in apps..

2. Screenshots issues:

3. Proof of my purchased:
Item Purchase Code:
9ae2b573-8a1a-4c28-9d87-9bf514fb31bc
3. Config files (optional)

**Comment by inspireui-support** [comment]
@azamcsc - could you help to share the common folder so that we could help for checking - thank you!

**Comment by inspireui-tech** [comment]
@azamcsc - I'm sorry for missing your comment, could you help to update the latest release 1.6.4 and re-check the payment issue - thank you!

**Comment by minhcasi** [comment]
@azamcsc - could you share the common+config folder so that we could help for checking - thank you!
