### ISSUE TITLE
[Fluxstore 1.6.3] - Error in adding new language

### ISSUE THREAD

**Issue by nelson243** [inspireui/support#2155]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: I add french as new language but whenever i click on the language tabs i'm getting the following error : A non-null String must be provided to a Text widget.
'package:flutter/src/widgets/text.dart':
Failed assertion: line 285 pos 10: 'data != null'
The relevant error-causing widget was: 
  Language file:///C:/Users/VAIO/Music/FluxStore-woo%201.6.3/source/lib/screens/settings.dart:336:86

2. Screenshots issues:
![Screenshot_1582131967](https://user-images.githubusercontent.com/13100267/74908867-45990c00-53b7-11ea-932f-de14776dcde2.png)

3. Proof of my purchased:
![flux](https://user-images.githubusercontent.com/13100267/74908904-619cad80-53b7-11ea-9fa3-7e1ca86af873.png)

3. Config files (optional)
Error in text dart :  
data != null,
         'A non-null String must be provided to a Text widget.',
error in settings.dart
                                onTap: () {
                                Navigator.push(
                                    context, MaterialPageRoute(builder: (context) => Language()));
                              },

**Comment by kvt0012** [comment]
Dear sir, 
Please tell me which files you config to add a new language, sir ? 
Thank you

**Comment by nelson243** [comment]
I followed the tutorial on this link : https://docs.inspireui.com/fluxstore/multi-language/
So I add anew language french and now i'm getting error when i want to switch to Language to test. 
so i can say i18n.dart,language.dart and the new language added strings_fr.arb

**Comment by kvt0012** [comment]
About the multi-language, i18n is no longer supported so we change the another one and it will be released on next version.
Thanks for your issue

**Comment by nelson243** [comment]
So when the next version will be released ? so what if need only one language french how to proceed to avoid the actual error and have everything in french ?

**Comment by kvt0012** [comment]
We expect to release it on this week. 
If you want everything on French, first you must translate the version of it on .arb file, you can refer the English file to do this. 
And next step you change the code as guide above.
