### ISSUE TITLE
login error for email in fluxstore multi vendor app.

### ISSUE THREAD

**Issue by dasdev** [inspireui/support#2156]
when i am going to log in from the app with the correct username and password the app saying it's incorrect please help to solve the problem. showing this massage : warning: exception: the username or password is incorrect. also have crash issue. unable to change splashscreen it's little bit complex
![scrent prove](https://user-images.githubusercontent.com/34004057/74914379-5a41c800-53e8-11ea-85af-63f2c755193f.png)

![IMG_20200220_133213 1](https://user-images.githubusercontent.com/34004057/74912851-7859f900-53e5-11ea-8905-f6f7043d784c.jpg)

**Comment by kvt0012** [comment]
Dear sir, can you give me your user name and password you use to sign in on the app? 
Thank you

**Comment by ohhodas** [comment]
need help about login error. store category email image error and also need
help about changing bundle id it's not clear in the doc there it's said
com.inspireui.fluxstore. but i have id of com.inspireui.fluxstore.vendor.
so it's confusing kindly give me some screen short and how to rename
folder, from studio or from file explorer?. also need help about ssh1 how
to create it. kindly give video of it will help me to do that please.

**Comment by ohhodas** [comment]
i have solve the login issue but now i am having problem with changing bundle id. why i am not getting help please kindly help me to solve this issue.

**Comment by ohhodas** [comment]
Sir please kindly help me am in big trouble need urgent help

**Comment by kvt0012** [comment]
Dear sir, 
Please try this for your issue 
https://docs.inspireui.com/fluxstore/customization/#1-app-nameicon-bundle-id

**Comment by ohhodas** [comment]
Sir am trying this for last 4days but unable to do so I have requested you.
Can run on your I'd but when I am changing it to com.shopzun.ecom.vendor
getting error . I have posted on github please check it.

**Comment by kvt0012** [comment]
Oh can you send me your source file ? I'll check it for you 
My email : vinhkhiemt135@gmail.com 
Thank you

**Comment by ohhodas** [comment]
Should I delete build folder or not before send to you?

**Comment by kvt0012** [comment]
Yeah, thanks for your enthusiastic

**Comment by ohhodas** [comment]
Sir kindly reply if u have got the source file

**Comment by kvt0012** [comment]
Yeah, I've already received  your source file

**Comment by kvt0012** [comment]
This error displays because your version of grandle is too old. Please update version of it. 
Secondly, you should remove intl: 0.16.0 because it's too old now. Btw, you can use like this. 
![image](https://user-images.githubusercontent.com/49152325/75137337-ec640c00-5719-11ea-9c03-7835ac78af47.png)

Thank you

**Comment by ohhodas** [comment]
i have the latest version of android studio. and where i get flutter_
![pakage id issue](https://user-images.githubusercontent.com/34004057/75141893-ecfba300-5717-11ea-8a83-a5811325842b.png)
intl:?

**Comment by ohhodas** [comment]
give some screen short or instruction please.

**Comment by kvt0012** [comment]
> i have the latest version of android studio. and where i get flutter_intl:?
> 
> ![pakage id issue](https://user-images.githubusercontent.com/34004057/75141893-ecfba300-5717-11ea-8a83-a5811325842b.png)
> 
> you said i can use this link but there is no link in your reply please check.

You can check file pubspec.yaml to add this.

**Comment by kvt0012** [comment]
You can check pubspec.yaml here 
![image](https://user-images.githubusercontent.com/49152325/75146121-f6dbd100-572c-11ea-9b46-aeb1f2f6b0a6.png)

And you can add it like below: 
![image](https://user-images.githubusercontent.com/49152325/75146162-12df7280-572d-11ea-8a58-b2c04fe9b350.png)
And delete itln :0.16.0 as this: 
![image](https://user-images.githubusercontent.com/49152325/75146252-428e7a80-572d-11ea-943f-de4a861b3eaf.png)

**Comment by ohhodas** [comment]
how to update gradle version please tell

**Comment by dasdev** [comment]
hello kindly reply please.

**Comment by kvt0012** [comment]
Prerequisites
Gradle runs on all major operating systems and requires only a Java JDK or JRE version 8 or higher to be installed. To check, run java -version:
$ java -version
**Step1,** 
Click on this link to download the grandle 6.2.1 
https://gradle.org/next-steps/?version=6.2.1&format=all
**Step 2,**
Create a new directory C:\Gradle with File Explorer.

Open a second File Explorer window and go to the directory where the Gradle distribution was downloaded. Double-click the ZIP archive to expose the content. Drag the content folder gradle-6.2.1 to your newly created C:\Gradle folder.

Alternatively you can unpack the Gradle distribution ZIP into C:\Gradle using an archiver tool of your choice.

**Step 3,** 
In File Explorer right-click on the This PC (or Computer) icon, then click Properties -> Advanced System Settings -> Environmental Variables.

Under System Variables select Path, then click Edit. Add an entry for C:\Gradle\gradle-6.2.1\bin. Click OK to save.

**Step 4,** 

Open a console (or a Windows command prompt) and run gradle -v to run gradle and display the version, e.g.:

$ gradle -v

------------------------------------------------------------
Gradle 6.2.1

**Comment by dasdev** [comment]
HeHe thanks i have already done this. kindly tell me how to publish on play store and how to get ssh1 i mean private key. please tell me simple process which is easy. kindly give example or screenshorts that will help me, and budle id changed successfully thanks for that.

**Comment by kvt0012** [comment]
https://docs.inspireui.com/fluxstore/delivery/ 
Here you are

**Comment by inspireui-tech** [comment]
@dasdev - also try to check the SSH1 config on this link - https://www.youtube.com/watch?v=C_9mk_MmvOQ - thanks

**Comment by kvt0012** [comment]
I think you's already fixed your problem, so I will close this issue 
Have a good day.
