### ISSUE TITLE
Content in category view- Listapp

### ISSUE THREAD

**Issue by mariablomberg** [inspireui/support#2158]
I have a MyListing theme and have used ListApp to make an app. On my mylsiting page, I can write custom information for each category, example: https://edible.co2diet.org/inlaggning. The same page looks like screenshot in app (see comment).  Is it possible to make the custom text show in the app too?

**Comment by mariablomberg** [comment]
<img width="475" alt="Screenshot 2020-02-20 at 10 58 54" src="https://user-images.githubusercontent.com/44641181/74923408-05df1e00-53d1-11ea-9ccc-174263f8b2a3.png">

**Comment by inspireui-support** [comment]
@mariablomberg - it's possible to map more fields to display like your requirement.

You can also try to enable more API endpoint from the "WP REST API Controller" plugin

**Comment by mariablomberg** [comment]
Thanks. But I don't get it to work. And I can find no documentation on what to do. 

The rest API seems to work somehow. When I toggle some things, they change or break. But I don't know how to do things such as adding another field etc.

**Comment by mariablomberg** [comment]
I have followed and done the instructions here: 
https://wordpress.org/plugins/jwt-authentication-for-wp-rest-api/#description

It also looks right (from what I can see) when going to http://edible.co2diet.org/wp-json

**Comment by mariablomberg** [comment]
I have re-installed and redone the things regarding .htacces and wp-config. 

Also, I can't create new user but I can sign in on an existing user.

**Comment by mariablomberg** [comment]
Is it possible to get help with this issue?

**Comment by mariablomberg** [comment]
Hello?

**Comment by mariablomberg** [comment]
Hi @minhcasi - do you think you can help me with this?

I thought the problem might have been having everything on a subdomain edible.co2diet.org so I moved everything to ätbar.com which translates to  xn--tbar-koa.com 

I updated the appconfig with the new website but it still doesn't work.

**Comment by mariablomberg** [comment]
@minhcasi

**Comment by mariablomberg** [comment]
I posted this 14 days ago and have been trying to get in touch 10 times. I have read all your manuals and followed them to the point. I have redone everything and even got a new web-host. What should I do to be helped? @minhcasi

**Comment by mariablomberg** [comment]
@minhcasi @luyx2412 @trunghieuvn @vumanhsn97

**Comment by minhcasi** [comment]
@mariablomberg - sorry for the late response as  we have some problem with the Coronavirus on the city - could you help to share the common folder again so that we could help for investigating the issue - thank you!

**Comment by mariablomberg** [comment]
@minhcasi 
Thank you for reaching out!!! 

Hope you are all OK with the corona. Just shared the commons folder through dropbox with your gmail minhcasi@gmail.com. Here is a link for viewing https://www.dropbox.com/sh/azkbmk1as3qroyt/AAA98D9RNh7IRzpjAtBb63fwa?dl=0

**Comment by mariablomberg** [comment]
Hi @minhcasi  - have you found anything?

**Comment by mariablomberg** [comment]
Does this look OK for example; http://xn--tbar-koa.com/wp-json/jwt-auth/v1

**Comment by mariablomberg** [comment]
FYI: I have changed website name from  https://edible.co2diet.org/ to  http://xn--tbar-koa.com

**Comment by mariablomberg** [comment]
Also, I don't know if this has anything to do with the problem, but this is the only view I can get in the ListApp plugin. It worked before moving website


![image](https://user-images.githubusercontent.com/44641181/76418510-0a2ea380-639f-11ea-8d65-9a1128211905.png)

**Comment by mariablomberg** [comment]
@minhcasi  - have you looked at this?

**Comment by mariablomberg** [comment]
I would very much appreciate information, even if it's that you haven't had time to look at it.

**Comment by mariablomberg** [comment]
@minhcasi Hello?

**Comment by minhcasi** [comment]
@mariablomberg - sorry for the late response, our team is checking the issue and will get back to you shortly - thank you!

**Comment by luyx2412** [comment]
Hi @mariablomberg Can you describe about your issues?

Thanks

**Comment by mariablomberg** [comment]
Thanks for getting back to me @minhcasi. 

My issue is basically that what I do in the Rest API-controller doesn't come through to the app. 
For example: I have a landing page for each category but that doesn't show in the app. I have more fields for each listing but that doesn't show in the app. 

I think my API endpoints are OK from what I can see. But somehow it doesn't get picked up when simulating the app. Maybe it's something super basic that I haven't done but I have really tried to follow the instruction. 

Also, I can't create a new user in the simulation of the app. But that's maybe because it's a simulation. 

Happy to give you the sign in details to the website. 

All the best

**Comment by mariablomberg** [comment]
Also, I get error code when going to the contact page in the menu. I don't know if this is connected. 
 
![image](https://user-images.githubusercontent.com/44641181/76702849-7fff7b80-66cd-11ea-8029-4b09bb7fba93.png)

**Comment by mariablomberg** [comment]
I don't know if it's relevant but it didn't work to install Listapp using CeBuilder. So I got help to install through the terminal.

**Comment by mariablomberg** [comment]
Do you understand the problem @luyx2412?

**Comment by mariablomberg** [comment]
hi @luyx2412  - Please get back to me.

**Comment by luyx2412** [comment]
Hi @mariablomberg Sorry about reply you late. Please read the document about the `Webview` components and replace this Webview with Webview expo https://docs.expo.io/versions/latest/sdk/webview/

Thanks

**Comment by mariablomberg** [comment]
@luyx2412 Thanks for getting back!

So I added the imports to the WebView.js file and tried different exports but it doesn't change anything. Also did a bit of reading but don't understand how this will (for example) add the custom fields that I have to the app. 

I will keep on reading but could we perhaps talk through skype and I share my screen?

**Comment by mariablomberg** [comment]
My skypename is maria_blomberg_

**Comment by luyx2412** [comment]
Hi @mariablomberg Sorry about reply you late. Please read the document carefully. And give me specific issue if you have any problems.

Thanks

**Comment by mariablomberg** [comment]
OK, i have tried to read but can't find the solution to below. 

1. How do I get the content on the page http://xn--tbar-koa.com/inlaggning/ to the category page for "inlaggning" (see problem 1). 

2. How do I add content to the "Contact" and "About" page? (see problem 2)

3. On mylisting, I have custom list fields such as "hitta" and "äta". How do I add them to the app? Right now, you can only see "Description" (see problem 3)

![image](https://user-images.githubusercontent.com/44641181/77454314-a4a7d180-6df8-11ea-8ebd-511531aa2adb.png)

**Comment by mariablomberg** [comment]
Same pic as above but better solution and white background

![image](https://user-images.githubusercontent.com/44641181/77454563-fb151000-6df8-11ea-99bb-8db5f373a41d.png)

**Comment by mariablomberg** [comment]
Hi again, I have been trying to get this right by reading the documentation and trying different things. I need help plz

**Comment by mariablomberg** [comment]
Updated

![image](https://user-images.githubusercontent.com/44641181/77544737-b9906d80-6ea9-11ea-9f33-e619281e2345.png)

**Comment by mariablomberg** [comment]
@luyx2412

**Comment by mariablomberg** [comment]
Please, can you help?

**Comment by mariablomberg** [comment]
@luyx2412, what do you think?

**Comment by luyx2412** [comment]
Hi @mariablomberg Sorry about reply you late.
- In `App/Container/Category/index.js` --> in Flatlist component, you can add `ListHeaderComponent` to show header in flatlist. 
![image](https://user-images.githubusercontent.com/8909619/77815803-56444c80-70f0-11ea-9f0b-9bc8a89a6d8d.png)
https://reactnative.dev/docs/flatlist#listheadercomponent
- Are use Listapp expo? If you use expo version. Please read the document to use webview https://docs.expo.io/versions/latest/sdk/webview/
- in `App/Components/Detail/ListingData/index.js` --> line 31. You can add more field in this line 
![image](https://user-images.githubusercontent.com/8909619/77815914-33fefe80-70f1-11ea-9479-18b18cc79954.png)

Thanks

**Comment by mariablomberg** [comment]
Thank you!!!! 
I will try and get back to you
