### ISSUE TITLE
Really Big Problem with the payment modal

### ISSUE THREAD

**Issue by jsaristizabal** [inspireui/support#2160]
Hello, I still have the same problem even updating the plugin in the latest version and also updating the latest version of the application. and I have realized that the problem is not of the code that I have but of the application as such. Try it by choosing Stripe as the payment method and this error will happen to you.

![Captura de Pantalla 2020-02-19 a la(s) 1 21 27 p  m](https://user-images.githubusercontent.com/29686082/74931985-cdc6e380-53ae-11ea-847d-dc4dd6fc0887.png)
![Captura de Pantalla 2020-02-17 a la(s) 6 30 31 a  m](https://user-images.githubusercontent.com/29686082/74931991-d0293d80-53ae-11ea-9c7d-037d79c296cb.png)
![Captura de Pantalla 2020-02-17 a la(s) 6 30 42 a  m](https://user-images.githubusercontent.com/29686082/74931993-d0c1d400-53ae-11ea-8c0a-74bdf1a36647.png)

**Comment by inspireui-support** [comment]
closed as could not provide the proof purchased - related #2132
