### ISSUE TITLE
[FluxStore 1.6.4] - App Got Rejected by Appstore due to multiple issues in IPad 

### ISSUE THREAD

**Issue by siyashamsudeen** [inspireui/support#2161]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:

My app got rejected by Apple due to multiple issues when running on IPad running ios 13.3.1 on WiFi .
Following to that when i run my app on ipad i realized there are so many issues to be resolved

Below are the issues they mentioned:

A. There is no Back button when on a single product screen . ( there is a close button on iphone view but not in Ipad when i personally checked )

![image](https://user-images.githubusercontent.com/57159602/74937459-8750a380-5405-11ea-94bb-026e2ddd9efb.png)
![attachment-17549361965556325799Screenshot-0220-101146 (1)](https://user-images.githubusercontent.com/57159602/74937499-9fc0be00-5405-11ea-82fe-d4f339b414ad.png)

B. App Displays a Login Button when the user is already logged in to an account.

![attachment-5911920368745039390Screenshot-0220-101538](https://user-images.githubusercontent.com/57159602/74937609-d0085c80-5405-11ea-96ec-a35228efbfbe.png)

C. Place Holder Content Issue
![image](https://user-images.githubusercontent.com/57159602/74937649-eadad100-5405-11ea-84d2-e316fff92557.png)

![attachment-17775008925118457603Screenshot-0220-102136](https://user-images.githubusercontent.com/57159602/74937689-0219be80-5406-11ea-9958-c2127909af53.png)

Is this due to dummy content on blog or are there more to be changed ?

D. some of the times i make a login i see a crash kind of error, this is not observed all the times but most of the times this error comes on the screen. 

<img width="596" alt="Screen Shot 2020-02-20 at 5 07 46 PM" src="https://user-images.githubusercontent.com/57159602/74937783-37bea780-5406-11ea-869f-4e7bb595f73d.png">

E. Apple Push Notification not working . Despite having all the configuration set . yet im not getting push notification on the device . 

XCode Setting

![image](https://user-images.githubusercontent.com/57159602/74937985-9b48d500-5406-11ea-9dea-aaf1e2d58689.png)

APN Key Page in Apple Developer Account:

![image](https://user-images.githubusercontent.com/57159602/74938063-c3383880-5406-11ea-8ea2-f38a78f72040.png)

APN Key Uploaded in Firebase :

![image](https://user-images.githubusercontent.com/57159602/74938120-d5b27200-5406-11ea-8afd-a3cf93a6de9b.png)

When sending a test message firebase also counts correctly the potentially eligible users which means app is communicating with firebase . but not receiving the push notification . what is the reason ?

RealTime Database is also enabled : 

![image](https://user-images.githubusercontent.com/57159602/74938225-072b3d80-5407-11ea-9839-b7df86cdee32.png)

And in One Signal - it shows the below:

![image](https://user-images.githubusercontent.com/57159602/74938710-f4fdcf00-5407-11ea-9b3c-4b6b5ecde734.png)

F. This issue was addressed earlier as well but still not resolved:

Products not loading in arabic language in vertical layout . it loads in english itself when the language is set to Arabic . 

in Horizontal layout , yes it fetches products in lang arabic . but in Vertical Layout even when the language is switched to Arabic it loads products in Lang English. 

Dear Team, please help to provide a solution to all the above at the earliest so that i can get my app live. 

Thank You
Regards,

2. Screenshots issues:

3. Proof of my purchased:

![image](https://user-images.githubusercontent.com/57159602/74938419-66894d80-5407-11ea-944b-2176d0c98b07.png)

3. Config files (optional)

**Comment by inspireui-support** [comment]
@siyashamsudeen - as this project already customize, could you zip the source send back support@inspireui.com for further checking

Please notice that the A and B issues are fixed on the latest code.

thank you!

**Comment by siyashamsudeen** [comment]
Can you please send the fix files for A & B. 
For me to configure the full app again with new source code ( update )  it would take another couple if days . If you can send fix files it would be a great help . 

And where is the latest code available ? Please advise.

The source code file size is heavier now. I will send the source code in email shortly. 

Thank You

**Comment by siyashamsudeen** [comment]
I have send the email with source code uploaded using Google Drive.  - Subject " #2161 "

Please acknowledge if you received the email. the file size is around 900 mb.

Thank You
Regards.

**Comment by inspireui-support** [comment]
@minhtruong315 - pls help to check the email

**Comment by siyashamsudeen** [comment]
Still awaiting for a solution on this . 
Please help to provide the fix files .

**Comment by siyashamsudeen** [comment]
Still looking for a solution ! Please help.. i have been waiting many days now for a solution so that i can resubmit for review in the appstore again. 

Please help.

**Comment by minhtruong315** [comment]
@siyashamsudeen sorry for delay. I messaged u on the skype. please check. thanks

**Comment by minhtruong315** [comment]
@siyashamsudeen I checked your source code. it has more issues. we fixed many issues on new version. we will release the new version today. Then u can check again

**Comment by inspireui-tech** [comment]
@siyashamsudeen - please help to use and update the code from v1.6.4 to fix these issues, we understand that there was some modified code that will take your time to review that latest version, as the project was modified and customized we could not go deeply for the investigate.

Please try your best to replace the existing model/widgets/screens folder and compare the file modifies, you can also review the file change from Gitlab to compare the update

**Comment by siyashamsudeen** [comment]
Hello, 

I checked the app with new version . 

IPad Issues are resolved . 
Arabic Product in Vertical Layout Issue also resolved but 

**Language switching has become worse now than before .** 

When i switch to arabic it doesnt change the screen to arabic immediately which was happening perfectly in the previous version . 

And after switching to arabic it doesnt load the homescreen layout (config_ar.json) of Arabic instead it is loading the same of english . 

And how do i remove the unwanted languages ? From Screens/Language.dart?

Please help to resolve the issue . I have been waiting for a proper solution since many days now. please help. 

The below is same config file of english not arabic specifc. 

<img width="579" alt="Screen Shot 2020-02-26 at 3 08 53 PM" src="https://user-images.githubusercontent.com/57159602/75340397-dc7c3180-58ab-11ea-9223-1a64382f8fb3.png">

The below is the screenshot of how config_ar.json is :

![image](https://user-images.githubusercontent.com/57159602/75340475-fe75b400-58ab-11ea-885f-1769c24ecfb3.png)

**Comment by minhtruong315** [comment]
@siyashamsudeen I will check it then let u know

**Comment by minhtruong315** [comment]
[app.dart.zip](https://github.com/inspireui/support/files/4259210/app.dart.zip)
- replace models/app.dart to fix arabic language.
- if you wanna remove languages, you need to edit code on screens/language.dart
- when change language, it need to request some api to refresh data by language, so you need to wait some time to change.

**Comment by siyashamsudeen** [comment]
Thanks for the fix . I shall try this asap . 

In the previous version it was perfect there was not time delay for the language to switch . Why is it there now ? Can we not make it how it was before . Isn't that much better ? 

Issue: Blog is giving blank screen . I updated the mstore api plugin in wordpress still the app is giving blank screen when blog is clicked on the new version . The new version is giving new issues :( . 

Please help to fix this.

**Comment by siyashamsudeen** [comment]
I checked the App.dart file but it is having errors:

![image](https://user-images.githubusercontent.com/57159602/75416746-9fb24800-5948-11ea-988b-4e7d416ee354.png)

**Comment by minhtruong315** [comment]
remove that error line

**Comment by siyashamsudeen** [comment]
I did that . I realized that the change is path to the config file as the folder has changed now . 

Still Language doesn't change instantly as in the previous version . Is it not possible to make it like in the previous version ? . 

The Blog issue is still not resolved . It shows blank screen .

**Comment by minhtruong315** [comment]
I messaged u on skype. will discuss on skype

**Comment by siyashamsudeen** [comment]
On Skype im still waiting for response and get a solution . please help . 

i sent screen record video , source code in email and Anydesk access . please help to fix . 

1. White screen before the splash page is too long .
2. After Language Change Category Page is not loading in Arabic
3. Blog show empty screen - if you swipe down and refresh then blog items appears. 
4. if you click any where on the empty blog screen then the error screen comes

<img width="360" alt="Screen Shot 2020-02-27 at 4 36 21 PM" src="https://user-images.githubusercontent.com/57159602/75535957-c5b21800-5a2e-11ea-9bb3-99e7f011285c.png">
