### ISSUE TITLE
[Fluxstore] - the payment methods displayed but no't working 

### ISSUE THREAD

**Issue by hssinaman** [inspireui/support#2162]
---------

1. My issue:
Hi, 
We have some payments methods are enabled from magento admin and working fine on website but are no't working on Fluxstore we can only see the payments methods and if we select any method and we press next 
 then the order will be placed without displaying the options of this payment.. 

2. Screenshots issues:

3. Proof of my purchased:
![74719629-b106a080-5234-11ea-9358-ee77096677a7](https://user-images.githubusercontent.com/61097607/74973164-4071a680-5423-11ea-9b0f-2f4bd6e6b407.png)

3. Config files (optional)

**Comment by inspireui-support** [comment]
2. shipping issue  - https://tppr.me/cOF5R

3. registration issue - https://tppr.me/VSH7f

@minhtruong315 - please help for checking

**Comment by hssinaman** [comment]
Can you help please?

**Comment by minhtruong315** [comment]
@hssinaman We're working on payment website magento. it'll support all payment methods. We only support Tap, Razorpay and Payment now. Other payment methods don't support now.

**Comment by hssinaman** [comment]
Can you help to implement it please? 
Because there is no meaning of using the app without payment methods.. How the users can place order then if the payment is not working..!!!
Also can you fix the other 2 issues please?
=> login / registration issue 
=> shipping issue

**Comment by hssinaman** [comment]
No reply till now.. 
Can you help please

**Comment by inspireui-support** [comment]
@hssinaman we are trying our best to add more features for Magento on next release as integration with Magento is quite complex to update the API - thank you for your patience

**Comment by minhtruong315** [comment]
@hssinaman did you install MStore extension? https://tppr.me/aMIeh

**Comment by minhtruong315** [comment]
supported via skype
