### ISSUE TITLE
[Fluxstore] - registration/login not working correctly

### ISSUE THREAD

**Issue by hssinaman** [inspireui/support#2163]
1. My issue:
Hi, 
The registration isn't working correctly, you fill all required information and you save account and when you try to login it show you an alert says that your email is already used or your account is disabled temporarily.. 

2. Screenshots issues:

3. Proof of my purchased:
![74719629-b106a080-5234-11ea-9358-ee77096677a7](https://user-images.githubusercontent.com/61097607/74973686-25ebfd00-5424-11ea-8a62-8c1bff10c187.png)

3. Config files (optional)

**Comment by inspireui-support** [comment]
moved to #2162

please create 1 ticket for your all issues
