### ISSUE TITLE
[Fluxstore pro] - payments page goes blank 

### ISSUE THREAD

**Issue by dured007** [inspireui/support#2164]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
I have two issues: 

The first with the shipping address - the postcode section only allows you to enter numbers but in the UK, the postcode (zip code) contains numbers and letters. 

The second when going to payment page, the web view payment ways such as stripe don't work, it shows a white blank page. Same as this issue:
https://github.com/inspireui/support/issues/1828

Proof of my purchased:

![ScreenHunter_310 Feb  20 20 13](https://user-images.githubusercontent.com/39766449/74974683-9c393100-541d-11ea-9dd9-60dd5479cae3.jpg)

3. Config files (optional)

**Comment by dured007** [comment]
3 days and no replays!!

**Comment by philipvu30** [comment]
Hi @dured007 ,

Sorry for the late response. We are going to update new code within today.
Please be patient and download the new update when it's available. Thank you

**Comment by dured007** [comment]
Hi @philipvu30 

I'm still having both issues even after the update. 

I did this step
"404 error page
Once enabling the mstore-api plugin, the payment gateway may not work as the default. To fix the error when clicking Process payment, following these steps:

Update the Mstore API to latest version: https://wordpress.org/plugins/mstore-api/

Copy the plugins/mstore-api/templates/mstore-api-template.php file to your current Wordpress template folder (example: wp-content/themes/your-template-name)

Go back to Wordpress Admin dashboard, create a page, name it "mstore-api", and remember don't set any parent page for it, then set page template to "Mstore Checkout"."

But when I created the new page there is no template called Mstore Checkout, there is one called mstore-api. Would that matter?

**Comment by inspireui-tech** [comment]
@dured007 - could you zip the common and config folder, then attach here for further investigation, if you could share the screenshot detail that would be great - thank you!

**Comment by dured007** [comment]
[lib.zip](https://github.com/inspireui/support/files/4253302/lib.zip)

Please find attached a copy of the common and config folders.

**Comment by minhtruong315** [comment]
"GuestCheckout": false,
  "EnableShipping": true,
  "EnableAddress": true,
@dured007 You need to disable guest checkout and enable address and shipping to support payment webview.

**Comment by dured007** [comment]
@minhtruong315  Thank you, I'll try to do that and let you know. 
What about the other issue? The postcode (zip-code) only allows to enter numbers and I need to enter letters.

**Comment by dured007** [comment]
Thank you I solved the zip-code thing by changing keyboardType: TextInputType.number, to keyboardType: TextInputType.text. in shipping_address.dart

but back to the webview payment, it only directs people to the English payment page. Can it be depending on the language? for example, if the user is using the app in Arabic, the webview payment can take them to an Arabic payment page which I already have on my site.

**Comment by minhtruong315** [comment]
@dured007 we don't support that now.

**Comment by dured007** [comment]
Hi @minhtruong315 
I have another issue with the search function, it works in English but it doesn't in Arabic. It doesn't show any items in Arabic. 
In English it shows a maximum of 50, can we change it to make it more? 
And how can I fix it so it works when searching in Arabic?

**Comment by dured007** [comment]
it's been 3 days! any answer? 
@minhtruong315

**Comment by minhcasi** [comment]
@dured007 - i suspect the search could be the bug, could you help to take the screenshot of this issue so that we could try to reproduce the issues, the team is working on the new feature to upgrade the search UX on next release

**Comment by minhtruong315** [comment]
@dured007 sorry for delay. I fixed Arabic on search function. but it edit a lot of files. can u give your email. I will send you changed files. Thanks

**Comment by dured007** [comment]
That's great, thank you @minhtruong315 
Please send it to this email dored963@gmail.com

**Comment by minhtruong315** [comment]
I sent you email. please check

**Comment by minhtruong315** [comment]
@dured007 I sent u updates on the email. please check and let me know. Thanks
