### ISSUE TITLE
Fluxstore Multivendor - Vendor banners don't work

### ISSUE THREAD

**Issue by marknestor261** [inspireui/support#2165]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: The vendor banners on website are not working in the app, there's only default banner for every vendor.

2. Screenshots issues:
![Screenshot_20200221-011639](https://user-images.githubusercontent.com/46901102/74985128-e6cfa300-5447-11ea-84d9-7c62738a64cc.png)
![Screenshot_20200221-011652](https://user-images.githubusercontent.com/46901102/74985133-e8996680-5447-11ea-95b7-659804e0d555.png)

3. Proof of my purchased:
![Screenshot_20200110-021020](https://user-images.githubusercontent.com/46901102/74985207-0c5cac80-5448-11ea-8b31-ec38bd0338e6.png)

3. Config files (optional)

**Comment by inspireui-support** [comment]
@marknestor261 - could you go to the banner account and upload the image banner to display it on the app, could you zip the common folder for investigating?

Please help to raise 1 ticket for your all issues, kindly move to #2159
