### ISSUE TITLE
[FluxStore Woocommerce] - Ticket #2070 

### ISSUE THREAD

**Issue by eduardopechir** [inspireui/support#2166]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: Reply of ticket #2070 Hello, sorry for taking a while to respond, I was traveling and without a Wi-Fi connection.
Thanks for your reply, what I need is in addition to adding the categories, adding the blog section, instagram. Also product categories but in the form of cards. I'm sure you can help me. Best regards.

2. Screenshots issues: 
<img width="92" alt="74286176-d6ebec80-4cec-11ea-813e-54c6d6f99a69" src="https://user-images.githubusercontent.com/60676647/74988143-aa2d8880-5402-11ea-98b0-3851da599458.png">

3. Proof of my purchased: 
<img width="1280" alt="Captura de Pantalla 2020-02-04 a la(s) 17 57 18" src="https://user-images.githubusercontent.com/60676647/74988181-c2050c80-5402-11ea-8fe2-203ae3ac5946.png">

3. Config files (optional)

**Comment by kvt0012** [comment]
Dear sir, 
Please check on this tutorial, it will help you.
https://docs.inspireui.com/fluxstore/home-layout/
Thank you
