### ISSUE TITLE
[Fluxstore] - shipping charges showing zero

### ISSUE THREAD

**Issue by hssinaman** [inspireui/support#2167]
1. My issue:
shipping charges showing zero but in our magento store we made 99

2. Screenshots issues:
![Screenshot_20200221_011018_com wmw aljazierah](https://user-images.githubusercontent.com/61097607/74991828-6315b680-5447-11ea-94d2-4f8902a1833b.jpg)

3. Proof of my purchased:
![74719629-b106a080-5234-11ea-9358-ee77096677a7](https://user-images.githubusercontent.com/61097607/74991857-7de82b00-5447-11ea-883c-2a511be5b18b.png)

3. Config files (optional)

**Comment by inspireui-support** [comment]
move to #2167 

please create one ticket for your all issue
