### ISSUE TITLE
[Fluxstore MV] - Logout button not working

### ISSUE THREAD

**Issue by kenngigz** [inspireui/support#2168]
![Purchase proof](https://user-images.githubusercontent.com/57593885/75003679-b6a0f800-5479-11ea-8288-77c050ff76c3.PNG)
![logout button error](https://user-images.githubusercontent.com/57593885/75003681-b7d22500-5479-11ea-9acd-828fb98243d4.png)
![logout button error2](https://user-images.githubusercontent.com/57593885/75003685-b86abb80-5479-11ea-81d9-3f0447f348df.PNG)
![logout code](https://user-images.githubusercontent.com/57593885/75003686-b9035200-5479-11ea-9892-16e19520e901.PNG)
[logout config files.txt](https://github.com/inspireui/support/files/4234216/logout.config.files.txt)

**Comment by inspireui-support** [comment]
@minhtruong315 - pls help for checking and include on next release - thank you!

**Comment by inspireui-support** [comment]
@kenngigz - could you share the common zip folder so that we could reproduce your issues

Please move the ticket #2169 on this thread for easy follow up (comments your all issues on one ticket) - thank you!

**Comment by minhtruong315** [comment]
@kenngigz can u send me lib/menu.dart file

**Comment by inspireui-support** [comment]
This issue is fixed on the latest 1.6.4 - it will be released tomorrow - thank you!
