### ISSUE TITLE
[Fluxstore MV] - Blog post error "The method '*' was called on null. Receiver: null Tried calling: *(1.2)"

### ISSUE THREAD

**Issue by kenngigz** [inspireui/support#2169]
![Purchase proof](https://user-images.githubusercontent.com/57593885/75003939-9b82b800-547a-11ea-87a4-a99baa0243d9.PNG)
![blog error 2](https://user-images.githubusercontent.com/57593885/75003940-9d4c7b80-547a-11ea-8902-49682b2a43e3.PNG)
![blog error code](https://user-images.githubusercontent.com/57593885/75003941-9de51200-547a-11ea-8166-5c81b6931616.PNG)
![blog error](https://user-images.githubusercontent.com/57593885/75003942-9de51200-547a-11ea-8c00-7cc816c97e16.png)
[blog post config files.txt](https://github.com/inspireui/support/files/4234226/blog.post.config.files.txt)

**Comment by inspireui-support** [comment]
@minhtruong315 - pls help for checking and include on next release - thank you!

**Comment by inspireui-support** [comment]
pls move to #2168

**Comment by UTimung** [comment]
Same problem
![Screenshot_20200227-231216](https://user-images.githubusercontent.com/18107447/75470879-5fd67980-59b7-11ea-8ccb-c08c759049a5.png)
