### ISSUE TITLE
[MStore] Could not get unknown property 'mergeResourcesProvider'

### ISSUE THREAD

**Issue by smmb313** [inspireui/support#217]
**Mandatory Info (please complete the following information):**
 - Product: MStore Pro
 - Your Purchased Code: 23ee29e0-2fb9-433e-807b-37744e5b655b

**Describe the issues**
Error:FAILURE: Build failed with an exception.

* Where:
Script 'C:\***\mstore-3.6.4\mstore-pro\node_modules\react-native\react.gradle' line: 95

* What went wrong:
A problem occurred configuring project ':app'.
> Could not get unknown property 'mergeResourcesProvider' for object of type com.android.build.gradle.internal.api.ApplicationVariantImpl.

BUILD FAILED in 16s

**Screenshots**
![android studio](https://user-images.githubusercontent.com/30038740/51803445-8ed96380-226a-11e9-9b24-9a32dfdd84db.png)

**Comment by minhcasi** [comment]
Hi, we have noted this issue for further investigating.

Could we check if you have already run the Example project successful base on this guide - https://facebook.github.io/react-native/docs/getting-started.html (just to make sure you can setup already library correctly to run the app)

**Comment by minhcasi** [comment]
I'
