### ISSUE TITLE
[Fluxstore] - Vendor messaging/calling not working, error; "A non-null String must be provided to a Text widget."

### ISSUE THREAD

**Issue by kenngigz** [inspireui/support#2170]
![vendor messaging calling code](https://user-images.githubusercontent.com/57593885/75004300-b99ce800-547b-11ea-8d4f-d4af64e9ef15.PNG)
![vendor messaging calling error](https://user-images.githubusercontent.com/57593885/75004303-bb66ab80-547b-11ea-838b-babf8dc38ce7.PNG)
![capture 2](https://user-images.githubusercontent.com/57593885/75004306-bbff4200-547b-11ea-83d7-626005436ddd.PNG)
![messagingcall error](https://user-images.githubusercontent.com/57593885/75004307-bc97d880-547b-11ea-9022-535e3601d6f8.png)
[vendor messaging ,calling contact.dart config file.txt](https://github.com/inspireui/support/files/4234240/vendor.messaging.calling.contact.dart.config.file.txt)
![Purchase proof](https://user-images.githubusercontent.com/57593885/75004313-be619c00-547b-11ea-9276-69955799782f.PNG)
[vendor calling;messaging text.dart config file.txt](https://github.com/inspireui/support/files/4234241/vendor.calling.messaging.text.dart.config.file.txt)
![vendor messaging calling code 2](https://user-images.githubusercontent.com/57593885/75004315-befa3280-547b-11ea-8e7d-fa8812d5c7d2.PNG)

**Comment by inspireui-support** [comment]
moved to #2168
