### ISSUE TITLE
[Fluxstore MV] - Order history Error; "The method '+' was called on null. Receiver: null Tried calling: +(", ")"

### ISSUE THREAD

**Issue by kenngigz** [inspireui/support#2171]
![order history error](https://user-images.githubusercontent.com/57593885/75004506-7131fa00-547c-11ea-8703-b1fc0f7d7cc3.png)
![order istory error2](https://user-images.githubusercontent.com/57593885/75004509-72632700-547c-11ea-8f6e-f136a4b84186.png)
![Purchase proof](https://user-images.githubusercontent.com/57593885/75004510-72fbbd80-547c-11ea-93c5-38739ba85896.PNG)
[order history, orders.dart config file.txt](https://github.com/inspireui/support/files/4234263/order.history.orders.dart.config.file.txt)
![order history code](https://user-images.githubusercontent.com/57593885/75004511-742cea80-547c-11ea-85db-34b612426498.PNG)
![order history error 2](https://user-images.githubusercontent.com/57593885/75004512-74c58100-547c-11ea-9d43-b75e9f8bdc95.PNG)

**Comment by inspireui-support** [comment]
moved to #2168
