### ISSUE TITLE
[List App] - Google shows error of Unoptimized APK when uploading on google

### ISSUE THREAD

**Issue by visheshtennis** [inspireui/support#2173]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:

Thanks for your constant support. I am finally able to publish and download the APK of 49.5 MB Size from the expo website. But I am facing trouble uploading it on google platform since it is giving a warning "Unoptimized APK"

Warning:
This APK results in unused code and resources being sent to users. Your app could be smaller if you used the Android App Bundle. By not optimizing your app for device configurations, your app is larger to download and install on users' devices than it needs to be. Larger apps see lower install success rates and take up storage on users' devices.

Resolution:
Use the Android App Bundle to automatically optimize for device configurations, or manage it yourself with multiple APKs.

And Google is also not showing the button to publish the same. Could you please help me with publishing the app on Google play store? (Screenshot Attached)

2. Screenshots issues:

![73139863-7b88f000-4098-11ea-86e5-64e6608dc8c4](https://user-images.githubusercontent.com/16410810/75011440-aa329480-54a5-11ea-85e2-87bcf0746973.png)

3. Proof of my purchased:
![72199643-d00b5900-3464-11ea-8148-342fbcc5260f](https://user-images.githubusercontent.com/16410810/75011550-ee259980-54a5-11ea-8b66-e42c440f16be.png)

![](https://user-images.githubusercontent.com/16410810/72199643-d00b5900-3464-11ea-8148-342fbcc5260f.png)

**Comment by inspireui-support** [comment]
@visheshtennis - could you zip the source to support@inspireui.com so that we could investigate the build (you can also share private by using https://wetransfer.com) - thank you!

**Comment by visheshtennis** [comment]
Done sir. Please let me know if you need any other thing.

-Vishesh, propertyyy.com

**Comment by visheshtennis** [comment]
Hey. I have already emailed the source file of the same. Could you please check it.

**Comment by minhcasi** [comment]
@visheshtennis - i'm sorry for the latest response as we have some issue with the react-native team - we could help you to release via teamview with free cost - please share your Skype contact for quick response - thank you!

**Comment by visheshtennis** [comment]
Great. Thank you so much.

I am available. My skype is

vishesh_tennis

Waiting for your reply on the same.

-Vishesh Rai Buffett
Propertyyy.com

**Comment by minhtruong315** [comment]
Hi @visheshtennis I messaged you on the skype. please check

**Comment by minhtruong315** [comment]
supported via skype
