### ISSUE TITLE
[Fluxstore-Woocommerce] - Payment Page Turns Blank

### ISSUE THREAD

**Issue by nelson243** [inspireui/support#2174]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: I have customs payment gateways in my website in addition to paypal but when i'm inb checkout page all the payments gateways lead to a blank page except for Paypal. Help me please to solve the problem. It's the same issue as ticket #1828

2. Screenshots issues:
![Screenshot_1578738842](https://user-images.githubusercontent.com/13100267/75013260-2916d580-5484-11ea-8567-97eb6f9dc77b.png)

3. Proof of my purchased:
![flux](https://user-images.githubusercontent.com/13100267/75013607-e6a1c880-5484-11ea-98ad-3498a9051b9d.png)

3. Config files (optional)

**Comment by minhtruong315** [comment]
@nelson243 can send me admin account to login to your website? I want check your website first. please send it via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/2174

**Comment by nelson243** [comment]
sure no problem i'm sending right now

**Comment by nelson243** [comment]
If you guys also can help i need to replace japanese language by french. 

First of all i change the flag OK

I changed the content of string_ja.arb OK

I changed also the content of config_ja to english 

But still i’m getting japanese language when i tried to choose can you guys tell me the steps to follow ? we speak french here so it’s a must for my app.

Really thanks for the support 

 





Nelson Mbembe
Directeur Technique


email: nelsonmbembe@gracim.net
mobile: 081 107 1700


Gracim, 11, Avenue Massamba Q. Basoko, Commune de Ngaliema


 <https://web.facebook.com/nelson.mbembe.5?_rdc=1&_rdr>   <https://twitter.com/nelsondu243>   <https://www.linkedin.com/in/nelson-mbembe-3859a89a>  

 <http://www.gracim.net/> www.gracim.net

 

 

De : minhtruong315 <notifications@github.com> 
Envoyé : mardi 25 février 2020 01:44
À : inspireui/support <support@noreply.github.com>
Cc : nelson243 <nelsonmbembe@gracim.net>; Mention <mention@noreply.github.com>
Objet : Re: [inspireui/support] [Fluxstore-Woocommerce] - Payment Page Turns Blank (#2174)

 

@nelson243 <https://github.com/nelson243>  can send me admin account to login to your website? I want check your website first. please send it via email: truong@inspireui.com <mailto:truong@inspireui.com> 
with subject: #2174 <https://github.com/inspireui/support/issues/2174>

**Comment by minhtruong315** [comment]
@nelson243 You must disable GuestCheckout and enable Address and Shipping to support payment webview on config.dart

"GuestCheckout": false,
  "EnableShipping": true,
  "EnableAddress": true,

**Comment by nelson243** [comment]
Okay thanks let me try and confirm to you

**Comment by nelson243** [comment]
It's working thanks for the support
