### ISSUE TITLE
Mstore - Problem when shows payment page

### ISSUE THREAD

**Issue by jsaristizabal** [inspireui/support#2175]
1. My issue:

@inspireui-support @minhcasi @luyx2412 @trunghieuvn @vumanhsn97  Hello, I still have the same problem as when I choose the payment gateway loads the modal of the page but for about 4 seconds it shows the page without styles (It looks horrible and nothing professional) even updating the complement in the latest version and also updating the The latest version of the application, I realized that the problem is not the modified code I have, but the application as such. Try it by choosing Stripe as the payment method and this error will occur, sometimes you do not even make the payment and give an error with red letters (As it appears in one of the images below) notifying that the process has failed.

2. Screenshots issues:

![Captura de Pantalla 2020-02-19 a la(s) 1 21 42 p  m](https://user-images.githubusercontent.com/29686082/75031756-fd402380-5474-11ea-95af-213803dc2686.png)
![Captura de Pantalla 2020-02-17 a la(s) 6 30 42 a  m](https://user-images.githubusercontent.com/29686082/75031763-fe715080-5474-11ea-95e6-afda5cb8fa4c.png)
![Captura de Pantalla 2020-02-17 a la(s) 6 30 31 a  m](https://user-images.githubusercontent.com/29686082/75031765-ffa27d80-5474-11ea-84e4-23e0b385ef89.png)

3. Proof of my purchased:

Item Purchase Code:
60b455a1-c467-4362-8fed-a3f976531151

![73805595-1bc7ce80-4795-11ea-819f-1283903a3119](https://user-images.githubusercontent.com/29686082/75031675-c8cc6780-5474-11ea-8198-895f93a6bf65.png)

3. Config files (optional)

The problem is in the original code and exactly the same problem happens even without changing any of the code.

**Comment by inspireui-support** [comment]
@jsaristizabal - noted with investigating, could you share the common zip folder so that we could reproduce the issue - thank you

**Comment by jsaristizabal** [comment]
@inspireui-support I already tested the problem with the original code that one downloads in themeforest without making any changes and it happens exactly the same by selecting the Stripe option.

**Comment by minhtruong315** [comment]
@jsaristizabal add my skype: minhtruong315
I'll help u check it

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
