### ISSUE TITLE
DatabaseConnectionIssue-FluxstorePro

### ISSUE THREAD

**Issue by saidbakkou** [inspireui/support#2176]
hello ... ijust tried to sognup or login with my sql database  (itried on server and on localhost aswell) but i got this probblem always and nothing function..  my connection code is correct  because this was working 2days ago and now it s not :(
![Capture](https://user-images.githubusercontent.com/59389664/75035341-896f3c80-54af-11ea-85d4-7df6094228a9.PNG)
![86183753_197529808291854_4776660982191620096_n](https://user-images.githubusercontent.com/59389664/75035350-8ecc8700-54af-11ea-93c9-5878cc7c4cb2.jpg)

**Comment by inspireui-support** [comment]
@saidbakkou - could you confirm to run this example successful - https://flutter.dev/docs/get-started/test-drive?tab=vscode ? It seems there is an issue with your Flutter setting - thanks
