### ISSUE TITLE
[Fluxstore MultiVendor] - Unable to set up

### ISSUE THREAD

**Issue by lyion92** [inspireui/support#2177]
[config.dart.zip](https://github.com/inspireui/support/files/4237905/config.dart.zip)

> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: 
a. I am using WCFM and i have copy the 2 files from lib/example/wcfm to the "common folder" and type in my api key. However, once i press the hot restart, the screen is blank

2. Screenshots issues:
<img width="1440" alt="截屏2020-02-22上午4 23 51" src="https://user-images.githubusercontent.com/23446063/75068976-2e7b2b00-552b-11ea-9007-80a833d87e17.png">

3. Proof of my purchased:
<img width="1440" alt="截屏2020-02-22上午4 20 21" src="https://user-images.githubusercontent.com/23446063/75068891-07bcf480-552b-11ea-9044-7581c24a1c8a.png">

3. Config files (optional)

[config.dart.zip](https://github.com/inspireui/support/files/4237908/config.dart.zip)

**Comment by mamunag8** [comment]
How to use ….... demo file from lib/examples/dokan ? please make a video tutorial details for Dokan setup with my/example site.
![flux](https://user-images.githubusercontent.com/33388253/75093121-38dc0a00-55a9-11ea-905d-4077d045d8be.JPG)

**Comment by inspireui-support** [comment]
@lyion92 - the team is checking and will get back you on today - thank you!

**Comment by minhtruong315** [comment]
@lyion92 add my skype: minhtruong315
I'll help u check it

**Comment by lyion92** [comment]
Done


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by lyion92** [comment]
I still haven't get any support yet

**Comment by minhtruong315** [comment]
{"code":"woocommerce_rest_authentication_error","message":"Invalid signature - provided signature does not match.","data":{"status":401}}

You created wrong customerKey and secretKey. you should follow this guide
https://docs.inspireui.com/fluxstore/woocommerce-setup/

**Comment by minhtruong315** [comment]
supported via skype

**Comment by waelkalesh** [comment]
same 

> {"code":"woocommerce_rest_authentication_error","message":"Invalid signature - provided signature does not match.","data":{"status":401}}
> 
> You created wrong customerKey and secretKey. you should follow this guide
> https://docs.inspireui.com/fluxstore/woocommerce-setup/

i have same problem support please
