### ISSUE TITLE
[Fluxstore - Woo] -  Translation of some terms

### ISSUE THREAD

**Issue by sketchuprzr** [inspireui/support#2178]
Hello,
As I mentioned in the picture below,
I want to translate "Pull up Load more" or "Loading" into a different language.
How can I do it?

Ss)
![image](https://user-images.githubusercontent.com/60021696/75075789-a3d90280-550f-11ea-972c-edd332f42d16.png)

**Comment by inspireui-support** [comment]
https://pub.dev/packages/pull_to_refresh - try to use 
```
 localeResolutionCallback:
                (Locale locale, Iterable<Locale> supportedLocales) {
              //print("change language");
              return locale;
            },
```

**Comment by sketchuprzr** [comment]
I'm sorry, I'm not very good about coding. How am I going to try this? @inspireui-support

**Comment by inspireui-support** [comment]
@sketchuprzr - we will request the team keep this update as well - thank you!

**Comment by inspireui-support** [comment]
@kvt0012 - pls check this feature request

**Comment by kvt0012** [comment]
You can add this code on file **product_list.dart**, on **return SmartRefrehser** 
footer: CustomFooter(
        builder: (BuildContext context, LoadStatus mode) {
          Widget body;
          if (mode == LoadStatus.idle) {
            body = Text("Pull up Load more");
          } else if (mode == LoadStatus.loading) {
            body = CupertinoActivityIndicator();
          } else if (mode == LoadStatus.failed) {
            body = Text("Load Failed!Click retry!");
          } else if (mode == LoadStatus.canLoading) {
            body = Text("Release to load more");
          } else {
            body = Text("No more Data");
          }
          return Container(
            height: 55.0,
            child: Center(child: body),
          );
        },
      ),
Like this. And change to your language
![image](https://user-images.githubusercontent.com/49152325/75144762-3fde5600-572a-11ea-92ce-5bd2d1276272.png)
