### ISSUE TITLE
ListApp - Listing Directory Mobile App Error

### ISSUE THREAD

**Issue by webbosolutions** [inspireui/support#2180]
1. My issue:Error on setup the app

2. Screenshots issues:
![87150895_828638734275061_4609326028387516416_n](https://user-images.githubusercontent.com/48894929/75088653-e83cc080-5558-11ea-8d68-7d68ca2e9969.jpg)

3. Proof of my purchased:
![4556999](https://user-images.githubusercontent.com/48894929/75088645-cd6a4c00-5558-11ea-9f82-46bc781ffe62.JPG)

Sincerely

**Comment by inspireui-support** [comment]
@webbosolutions - could you help to take the screenshot include your username or you could add the comment on this link - https://codecanyon.net/item/listapp-listing-directory-mobile-app-by-react-native/21456447 - thank you!

**Comment by webbosolutions** [comment]
![56655498](https://user-images.githubusercontent.com/48894929/75110531-ee559e80-5637-11ea-9819-be8c408a60af.JPG)

**Comment by inspireui-support** [comment]
@webbosolutions - you could try this solution react-navigation/react-navigation#6594 - thank you!

**Comment by webbosolutions** [comment]
thanks it solved

**Comment by chuniversity** [comment]
What was the answer?
