### ISSUE TITLE
[Fluxstore MultiVendor] - video tutorial 

### ISSUE THREAD

**Issue by mamunag8** [inspireui/support#2182]
---------

1. My issue:

Please make a video tutorial for beginner, how to setup/use this APP (From download to use in phone[Android] for any website) please give every step in details. please do it.

How to use ….... demo file from lib/examples/dokan ? please make a video tutorial details for Dokan setup with my/example site.

2. Screenshots issues:
![dokan](https://user-images.githubusercontent.com/33388253/75093313-a0468980-55aa-11ea-9404-caa355d77f5e.JPG)

3. Proof of my purchased:
![flux](https://user-images.githubusercontent.com/33388253/75093103-12b66a00-55a9-11ea-9c9f-9098dabb6354.JPG)

3. Config files (optional)

**Comment by mamunag8** [comment]
![store](https://user-images.githubusercontent.com/33388253/75094414-f3253e80-55b4-11ea-8dab-d741339e5997.JPG)

**Comment by minhtruong315** [comment]
@mamunag8 send me common folder. I will help u check

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!

**Comment by mamunag8** [comment]
Please accept my skype id rezamm.bd
