### ISSUE TITLE
[Flux Store Multi Vendors] - Customizing webview widget appbar background

### ISSUE THREAD

**Issue by HassanChmsdn** [inspireui/support#2183]
1. My issue:
I am not. able to change the background color of the webview appbar, I'm not sure if the webview widget is loaded before the app built since I have used: `backgroundColor: Theme.of(context).backgroundColor.withOpacity(0.8)` and it was loading the backgroundColor from the flutter theme not as modified in my style.dart file, so basically my theme changes had no effect on the webview widget.

as I can see that webview.dart file has two configurations for the scaffold and the appbar but both background colors are not applying my theme colors.

**Any Help how can I change the webview appbar from the default flutter blue color**

2. Screenshots issues:
![Simulator Screen Shot - iPhone 11 Pro - 2020-02-23 at 01 38 44](https://user-images.githubusercontent.com/921709/75101464-457a5580-55dd-11ea-88d1-cd3f3ae1b7c5.png)

3. Proof of my purchased:
Item purchased code: d1141eb5-edf3-4bcc-844b-112677d6f489
Date : 2019-11-21 21:15:50 UTC

**Comment by kvt0012** [comment]
Dear sir, 
If you want to change the color of the appbar on webview, the easiest way is you can come to the file webview.dart ( Directory : lib/widgets/webview.dart) and change the color as below: 
![image](https://user-images.githubusercontent.com/49152325/75126651-937e7e80-56ed-11ea-85d5-0c33bef74ae5.png)


Thank you

**Comment by HassanChmsdn** [comment]
Dear @kvt0012, 

yes I know where to change the color of it, my issue is about using `Theme.of(context).backgroundColor.withOpacity(0.8)`, my custom theme colors are not applicable to the webview AppBar background, as I mentioned in the issue above, and I am not sure why or how to make it work.

Thank you

**Comment by kvt0012** [comment]
I got it. 
Can you send me your config file ? Thank you

**Comment by HassanChmsdn** [comment]
> I got it.
> Can you send me your config file? Thank you


[styles.dart.zip](https://github.com/inspireui/support/files/4250266/styles.dart.zip)
[CONFIG.json.zip](https://github.com/inspireui/support/files/4250267/CONFIG.json.zip)

**Comment by kvt0012** [comment]
You can edit it on file styles.dart with backgroundColor property. We divide into 2 kinds of color: color of dark theme and light theme.

**Comment by HassanChmsdn** [comment]
> You can edit it on file styles.dart with backgroundColor property. We divide into 2 kinds of color: color of dark theme and light theme.

Dear @kvt0012 im not sure if you have read my issue.. i know i can edit the styles.dart, i already used Theme.of(context).backgroundColor.withOpacity(0.8) that should be loaded from the style.dart, but only the webview is not rendering the color from style.dart this code has no effect, the colors are applied from the default flutter colors which is weird!

**Comment by kvt0012** [comment]
> > You can edit it on file styles.dart with backgroundColor property. We divide into 2 kinds of color: color of dark theme and light theme.
> 
> Dear @kvt0012 im not sure if you have read my issue.. i know i can edit the styles.dart, i already used Theme.of(context).backgroundColor.withOpacity(0.8) that should be loaded from the style.dart, but only the webview is not rendering the color from style.dart this code has no effect, the colors are applied from the default flutter colors which is weird!

I'm so sorry, because when I test it changed on my device, maybe that your version is old,  so please download the newest version and test again. 
Thank you

**Comment by HassanChmsdn** [comment]
@kvt0012 You mean by old version of the app or webview_flutter?

**Comment by kvt0012** [comment]
> @kvt0012 You mean by old version of the app or webview_flutter?

I mean that maybe you run on the old version, please upgrade to the newest. 
Thank you

**Comment by HassanChmsdn** [comment]
@kvt0012 ok, it seems that is fixed in the new version, unfortunately, I have customized a lot I need to check how can add the changes properly, any ideas?

**Comment by kvt0012** [comment]
Dear sir, 
We are really sorry that we can't help you on this case because it is out of our support scope. By the way, we can support to you requesting to our gitlab and you can compare the change between our newer version and yours to fix your problem. 
Thank you

**Comment by HassanChmsdn** [comment]
> Dear sir,
> We are really sorry that we can't help you on this case because it is out of our support scope. By the way, we can support to you requesting to our gitlab and you can compare the change between our newer version and yours to fix your problem.
> Thank you

Yes it seems that it is the only way, thanks anyways.
