### ISSUE TITLE
Mstore pro payment Getway not working 

### ISSUE THREAD

**Issue by mdyunus24bd** [inspireui/support#2185]
days ago
My issue:
Apps not working for Payment Getway, my Website there a Direct Bank transfer & paypal Express checkout(Credit/debit card payment & paypal ).How to set a payment .

not Show a Image on apps how to set a Image on Payments Method image.

i cilck a confrim order go direct my website Checkout page.

product image not loading

category not loading
Please how to setup

Screenshots issues:
https://prntscr.com/r3vefb
https://prntscr.com/r3ve1y
https://prntscr.com/r3vdmp
https://prntscr.com/r3vdj5
https://prntscr.com/r3vdgx
https://prntscr.com/r3vdgx
https://prntscr.com/r3vddb

Proof of my purchased:

Purchase code: 14ff322a-3ecb-4362-a8b1-d6b0c4d27675

Config files
https://github.com/mdyunus24bd/file

**Comment by minhtruong315** [comment]
@mdyunus24bd send me full source code via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/2185

**Comment by minhtruong315** [comment]
support via email
