### ISSUE TITLE
[my-product] - Discussion on Fluxstore WooCommerce - Flutter E-commerce Full App:   

### ISSUE THREAD

**Issue by gridsapps** [inspireui/support#2186]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:  i was following all the steps as well and add more packages after trying to open this app in my vc but i face one problem which is generated_plugin_registrant.dart lib Unused import:dart.ui ....so how can i fix that to run this app as well

2. Screenshots issues: https://prnt.sc/r6e7qv.       

3. Proof of my purchased: My Purchase codes:   90463e06-552b-4004-adb7-10bfa409537f 

3. Config files (optional) 
my account in codecanyon: https://prnt.sc/r6e8pi

**Comment by gridsapps** [comment]
my proof:  
https://prnt.sc/r6e8pi

**Comment by inspireui-support** [comment]
@gridsapps - this warning does not impact to the app as this is auto-generate file by flutter - thank you!
