### ISSUE TITLE
[EvaStore] - WebView issue on current release.

### ISSUE THREAD

**Issue by Royce77** [inspireui/support#2187]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: External links and checkout page does not work. I even downloaded a fresh version of EvaStore using your default store and could not get any links to load or the checkout payment page to display any content vis WebView. I believe this to be a React Native WebView issue.

2. Screenshots issues: https://iosapps-ssl.itunes.apple.com/itunes-assets/Purple114/v4/0d/15/ec/0d15ec5a-7c01-d0fc-7095-bebc4bf07293/attachment-9414603645959710093Screenshot-0216-174516.png?accessKey=1582275909_7799040531208958287_rgZfF7yIHOY70t8IvqeTksSzTLlRmd4fphSRYA6FP9ZvA3PCfAzgEkeyQa5H3kWZU03DloPvT%2BTJJb7B%2B7fwF8tRYmrG0GC9axVwVyOKUUKT8bSozRSft7RPtQWtuhBeY3%2FEzNhJYDRDUGI4gDWl2zSdsYQdQZ9GnqvSwLdHByg4HdVGB5a0V%2BcJkHtma4rByjzS%2FFaNdD8UAp8bErZaXQ%3D%3D

3. Proof of my purchased: https://user-images.githubusercontent.com/28791859/74805439-be329680-52eb-11ea-94b8-33777c00ea4f.png

3. Config files (optional)

**Comment by luyx2412** [comment]
HI @Royce77 Please send the screenshot again, i could not see anything. 

Thanks
