### ISSUE TITLE
[Fluxstore - Woo] - Order information does not reach

### ISSUE THREAD

**Issue by sketchuprzr** [inspireui/support#2189]
Hi 
When ordering in the application , After typing in the address information,Information written in the "Note" section on the review page, "Note" does not appear on the order information page in the woocommerce order panel.

**Comment by kvt0012** [comment]
Dear sir, 
You want to display the address on review screen, don't you ? 
Thank you.

**Comment by sketchuprzr** [comment]
Hello,
I receive the order details.
For example "products, phone number, address information".
But when ordering, the customer can leave a note in the "Note" section when he reaches the "review" page after entering the address information. But this order note he left did not reach me.

**Comment by sketchuprzr** [comment]
By the way, when will the update come? For about a month, "this week" has been informed. But there is no update yet. @inspireui-support

**Comment by kvt0012** [comment]
> Hello,
> I receive the order details.
> For example "products, phone number, address information".
> But when ordering, the customer can leave a note in the "Note" section when he reaches the "review" page after entering the address information. But this order note he left did not reach me.

Thanks for your idea, we'll discuss with our team and update it later.

**Comment by kvt0012** [comment]
> By the way, when will the update come? For about a month, "this week" has been informed. But there is no update yet. @inspireui-support

We also expect to release it soon but the issues are raised everyday, so to serve customer better, we'll update as much as possible and takes it to the new release. Sorry for your inconvenience.

**Comment by themeix** [comment]
Today we got the new release but still Order note bug not resolved..  Order not text area box data not passing to the webview checkout and also not working for cash on delivery method too.

Without that bug fixing we area unable to use the app.. Please take that issue seriously.. Facing trouble for that.

**Comment by sketchuprzr** [comment]
The "https://docs.inspireui.com/fluxstore" Website is not working..

**Comment by kvt0012** [comment]
> The "https://docs.inspireui.com/fluxstore" Website is not working.. @inspireui-tech

![image](https://user-images.githubusercontent.com/49152325/75325363-48aa6580-58ab-11ea-91b6-fbf8f79c84fb.png)

You click on advanced and proceed it, you will be able to access.
