### ISSUE TITLE
[BeoNews] Help in custom

### ISSUE THREAD

**Issue by lpzczar** [inspireui/support#219]
help!

Purchase code: a935fd39-69e1-4768-bd83-d5e30451f909
BeoNews

1) How do I remove the side menu? I know it's on RootRouter.js, but what lines of code should I remove?

2)how do I replace the photo tab menu with url custom?

3)How to change color and add button in toolbar header? Like this...
http://www.digitalsnd.com.mx/wp-content/uploads/2019/01/S1.png

**Comment by lpzczar** [comment]
???

**Comment by luyx2412** [comment]
Hi @lpzczar 
1. In RootRouter.js file please remove or comment code from 187 --> 229 line. And replace with `this.renderContent()` look like the photo 
![image](https://user-images.githubusercontent.com/8909619/52026380-4061e880-253a-11e9-9877-a5a23a20d214.png)

2. In `App/Navigation/index.js` file from 77 line you can see the `tabBarIcon`, Each menu tab bar will have `TabBarIcon` component. You can replace with `Image` component look like the photo
![2019-01-31_09-28-16](https://user-images.githubusercontent.com/8909619/52026535-c9791f80-253a-11e9-9d71-aeaa118e57c4.png)

3. You can change the color or add toolbar header based on the document, 
Each screen have Parent file. For example: Home screen have `HomeScreen` file, and have `navigationOptions` which you can custom the header or something like that in the document. https://reactnavigation.org/docs/en/stack-navigator.html#headerright
![image](https://user-images.githubusercontent.com/8909619/52026591-fdecdb80-253a-11e9-9c9f-8e2155ac1531.png)

Thanks
