### ISSUE TITLE
[mv-mstore - I cant pick and select the country in the shipping page!! 

### ISSUE THREAD

**Issue by khalidsharif** [inspireui/support#2190]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
Now another issue with the shipping field

I can pick the country but it doesnt get selected!! 
latest version 1.3.3 expo

. Screenshots issues:
https://ibb.co/cktfNyr

. Proof of my purchased:
https://ibb.co/d40dKnD

**Comment by luyx2412** [comment]
Hi @khalidsharif can u send me the AppConfig.json and Config.js file?

Thanks

**Comment by khalidsharif** [comment]
here you go

https://easyupload.io/rwylxb
https://easyupload.io/b7abt5

BTW, maybe the issue is related to the expo version or node version ?! because I upgraded expo to the latest expo-cli and the node to the latest also!

**Comment by khalidsharif** [comment]
I also tried using your demo in the latest edition ...but I got the same issue.

**Comment by luyx2412** [comment]
HI @khalidsharif Maybe related the latest expo version. So can you screenshot about it? I could access your url.

Thanks

**Comment by khalidsharif** [comment]
Yes it is related to the latest expo .. I tried the older version of the app which is 1.3.2 ..and did get this issue ..but the older version has login problems.

here is my expo version 
https://ibb.co/NWh9DPK

Now what shall I do.. you will release a fix ?

**Comment by khalidsharif** [comment]
https://expo.io/@ikhalidsharif/mstore-multivendor

**Comment by luyx2412** [comment]
Hi @khalidsharif Can you send me the AppConfig.json and Config.js file?

Thanks

**Comment by khalidsharif** [comment]
> Hi @khalidsharif Can you send me the AppConfig.json and Config.js file?
> 
> Thanks

https://yadi.sk/d/61Qc8uXfDFcgRg

**Comment by luyx2412** [comment]
Hi @khalidsharif Please replace `src/containers/Cart/Delivery/index.js` with this file to fix the issue.
[index.js.zip](https://github.com/inspireui/support/files/4275926/index.js.zip)

P/S: Feel free to reopen the issue.

Thanks

**Comment by khalidsharif** [comment]
> Hi @khalidsharif Please replace `src/containers/Cart/Delivery/index.js` with this file to fix the issue.
> [index.js.zip](https://github.com/inspireui/support/files/4275926/index.js.zip)
> 
> P/S: Feel free to reopen the issue.
> 
> Thanks

thanks,,, now the location issue is resolved.
In the payment page.. the Cash on Delivery has an issue also.. nothing happens when I click on the Cash on Delivery button. its enabled in both website and config.js ... I have to open a new ticket for this issue ?

**Comment by luyx2412** [comment]
Hi @khalidsharif When you select COD, after that you need click button "Confirm checkout" to continue.

Thanks

**Comment by khalidsharif** [comment]
See this video screen Luyx
https://drive.google.com/file/d/1EHVSm5Up5ONGXtp-ZmYfD4GJx7JR8E__/view?usp=sharing

my country code is BH !! why its not processing the cod method ?!

**Comment by luyx2412** [comment]
Hi @khalidsharif I just tested your config, and the issue related `woocommerce_rest_authentication_error ` please check again your woocommerce config and please follow the document to install library https://docs.inspireui.com/mstore.

Thanks

**Comment by khalidsharif** [comment]
I am using the litespeed server from digital ocean, the app is working and pulling information and SSL is already configured.

I followed the guidline provided. How I can debug the woocommerce configuration to make sure that COD is working?

Note, there is also another weired issue, the app now is already deployed in apple app store. I can use the custom payment methd using iPhone 7. while in iPhone X, the following issue I always get the error message " We cannot ship to yuo country !!"

**Comment by luyx2412** [comment]
Hi @khalidsharif You can use reactotron to debug your api https://docs.inspireui.com/mstore-mv/development/

Thanks
