### ISSUE TITLE
[fluxStore-OpenCart] 

### ISSUE THREAD

**Issue by khaledsalama32** [inspireui/support#2191]
---------

1. My issue:
connect my FluxStore To OpenCart
please send the suitable 

config.dart
config.json

for OpenCart 

because My source not included by this files 

note :: we buy  Fluxstore WooCommerce - Flutter E-commerce Full App 

note :: I can not find mStore ext in the folder which uses in add languages ( Arabic ) which belong OpenCart.

2. Screenshots issues:

3. Proof of my purchased:
9e83ec40-8414-4b23-960d-0b69d207dd89
3. Config files (optional)

**Comment by inspireui-support** [comment]
Hi, the Fluxstore Woocommerce does not include the Opencart integration, pls check this product: https://codecanyon.net/item/fluxstore-the-universal-woocommerce-magento-opencart-mobile-app-by-flutter-framework/24020929

**Comment by khaledsalama32** [comment]
Please send me an explanation of fluxstore  and how to link fluxstore with Word Press and woocommerce
