### ISSUE TITLE
[FluxStore] - How to Remove SmartChat Widget?

### ISSUE THREAD

**Issue by saifmuhtar** [inspireui/support#2192]
1. My issue: **How to Remove SmartChat Widget?**

2. Screenshots issues:
![Screenshot 2020-02-24 at 7 13 47 AM](https://user-images.githubusercontent.com/34681804/75122100-3f67a000-56d5-11ea-96fe-8636502c7326.png)

3. Proof of my purchased:
![72332982-fc89d400-36f5-11ea-9307-f8c418404111](https://user-images.githubusercontent.com/34681804/75122076-1b0bc380-56d5-11ea-88fa-62ef0daff99a.jpg)

**Comment by inspireui-support** [comment]
@saifmuhtar - pls try to use the Inspector - https://docs.inspireui.com/fluxstore/useful-tip/#how-to-change-the-ui-quickly

Or disable the Smartchat from common/config.dart file - thank you!
