### ISSUE TITLE
Fluxstore Multi Vendor] - remove the recently viewed and blog section from home page

### ISSUE THREAD

**Issue by abd096** [inspireui/support#2194]
Hello, 

how can i remove the recently viewed and blog section from home page ? 

and i want to remove the "X" close icon in the floating cart

**Comment by inspireui-support** [comment]
Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads  it's used to verify your proof of purchase? sorry for any inconvenience - Thank you!

**Comment by inspireui-support** [comment]
Btw, the recent product could be config from common/config.json - and the icon could remove by using the Inspector - https://docs.inspireui.com/fluxstore/useful-tip/#how-to-change-the-ui-quickly - thank you!
