### ISSUE TITLE
FluxStorePro - Connection with SQL Database Problems

### ISSUE THREAD

**Issue by saidbakkou** [inspireui/support#2195]
Hello, 
 How can i disable JsonFile exist on the template already( as  local database) .. and replace it with SQL database only (my database) .. beacuse i noticed that my data (  signup fro ex) it s registred on both of these (json and my database) !
![86183753_197529808291854_4776660982191620096_n](https://user-images.githubusercontent.com/59389664/75171966-cac05000-572c-11ea-993d-4e65830c4ed5.jpg)

**Comment by inspireui-support** [comment]
@saidbakkou - thank you for the question, sorry that we could not answer this question as we don't have experience to connect with the SQL database from Flutter, but we suggest to use this solution to implement your idea - https://flutter.dev/docs/cookbook/persistence/sqlite - very best!
