### ISSUE TITLE
Question about operation. Flux Store App[my-product] - 

### ISSUE THREAD

**Issue by luislamoss** [inspireui/support#2196]
Sorry for my question, maybe it's dumb for most, but hey.

1) When buying the app does it already work fully? Or is it just the front and should the backend be tested?

2) Does the app have a control panel (web) where I can see purchases made, products, add or delete categories etc?

Please your answer, I am very interested in this product.

**Comment by inspireui-support** [comment]
Hi, thank you very much for the questions

1. It's the full app that works perfectly for the e-commerce app, you need to set up the Woocommerce as the backend site to manage the product.

2. The app don't have the control panel, but we are going to release new Fluxbuilder to help to customize the app super easy 

Very best!
InspireUI
