### ISSUE TITLE
[FLUXSTORE] - 

### ISSUE THREAD

**Issue by khaledsalama32** [inspireui/support#2197]
1. My issue:
I want to make direction of app from LTR  TO  RTL  ؟
i have fluxstor ecommerce  
2. Screenshots issues:

3. Proof of my purchased:
 9e83ec40-8414-4b23-960d-0b69d207dd89

3. Config files (optional)

**Comment by inspireui-support** [comment]
@khaledsalama32 - just try to update the Arabic language as default - https://docs.inspireui.com/fluxstore/multi-language/#how-to-set-a-language-as-the-default-language
