### ISSUE TITLE
Fluxstore - issues under inspect code before customize.

### ISSUE THREAD

**Issue by gurutos** [inspireui/support#2198]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
I follow the doc ( https://docs.inspireui.com/fluxstore/getting-started/ ) i complete installing the theme Fluxstore successfully, i make the flutter test app, all the steps,

Im starting at this part: https://docs.inspireui.com/fluxstore/multi-vendor/

But first i want to check why the theme is having all this issues: i press analyze - inspect code and this is the result:

2. Screenshots issues:

![image](https://user-images.githubusercontent.com/61175861/75200955-2abaf480-5735-11ea-820b-a3bb2e057be1.png)

![image](https://user-images.githubusercontent.com/61175861/75200979-39091080-5735-11ea-85f5-e89972c44692.png)

3. Proof of my purchased:

![image](https://user-images.githubusercontent.com/61175861/75201095-871e1400-5735-11ea-8095-804ba469b826.png)

i try to unistalling everything and installing again 3 times, but im having the same issues, 

Thanks in advance,

Thanks and Regards,
PMontes.

**Comment by inspireui-support** [comment]
@gurutos - could I know if you set up the example Flutter successful - https://flutter.dev/docs/get-started/test-drive

Please note that the compliance from Flutter will be difference from native app

**Comment by inspireui-tech** [comment]
@gurutos - thank you for the feedback, could you help to check the basic example from Test Drive to see if it is the same issue - https://flutter.dev/docs/get-started/test-drive ?

Please note that the compliance on flutter could be different, please also make sure to install the Flutter plugin on Android Studio and fix all issues from 'flutter doctor'

Let us know your checking - thank you!

**Comment by gurutos** [comment]
Hello Good Night Support Team,

Can someone please help me with this issues?

Thanks and Regards, 
PMontes.

**Comment by gurutos** [comment]
Hello Good Day Support Team,

Can we check this issues?

Thanks in advance,
Pao Montes.

**Comment by minhcasi** [comment]
@gurutos - could you help to try with the basic example from https://flutter.dev/docs/get-started/test-drive ?

This guide will help to check your all config issues - thank you!

**Comment by gurutos** [comment]
Good Day Minhcasi, 

Yes i create the new app without problems, i run the app it and change the number, i complete all the guide until the part to add to the website, 

Im waiting for youre support.

Let me know if there is another doubt, or should we talk by skype to check it?

Thanks and Regards,
Pao Montes.

**Comment by minhcasi** [comment]
@gurutos - pls share your Skype ID 

@minhtruong315 - pls help for checking

**Comment by gurutos** [comment]
Good Day Minhcasi,

My skype its paolamontesp, @minhtruong315 just reply here when your ready, i will be pending to connect,

Thanks and Regards,

**Comment by gurutos** [comment]
hello @minhtruong315

please let me know if we can connect tomorrow to skype,

thanks and regards,

**Comment by gurutos** [comment]
hello @minhtruong315 and team,

can we connect?

thanks and regards,
Pao Montes.

**Comment by minhcasi** [comment]
@minhtruong315

**Comment by minhtruong315** [comment]
hi @gurutos sorry for delay. can u send me your skype? I will help check your issues via skype. Thanks

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
