### ISSUE TITLE
CFBundleIdentifier", Does Not Exist"

### ISSUE THREAD

**Issue by hammadhassan** [inspireui/support#22]
- Product: [MStore]
 - Purchase Code: f20afe4a-778e-4089-bcb2-7ec1bb4ed49b
Unable to run app on MAC.

Following error keep coming after i set schema using docs.mstore.io troubleshooting page.
**Error**
[`Failed to install the requested application
The bundle identifier of the application could not be determined.
Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
Print: Entry, ":CFBundleIdentifier", Does Not Exist`

`Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/mstore.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist`

`Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/mstore.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist`

`    at checkExecSyncError (child_process.js:611:11)
    at Object.execFileSync (child_process.js:629:13)
    at Promise.then (/Users/epic/Desktop/mstore/mstore-3.6.3/mstore-pro/node_modules/react-native/local-cli/runIOS/runIOS.js:208:5)`]

Please help to fix this issue.

**Comment by anosmx** [comment]
Hi,

Here is how to fix it. [Link](https://docs.mstore.io/faq-and-troubleshooting#fix-cfbundleidentifier-does-not-exist)

**Comment by hammadhassan** [comment]
I did use steps showing in the page. But i still got same error every time.

Could you please give any other solution?
