### ISSUE TITLE
[Fluxstore - Woocommerce] - Profile Update Problem

### ISSUE THREAD

**Issue by amitiitd999** [inspireui/support#2202]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:

Profile update is not working. When button is pressed, nothing happens.
Below is my 'POST' request for profile update.

I/flutter (29058): Url :: https://amit999.com/wp-json/api/flutter_user/update_user_profile/?insecure=coo I/flutter (29058): json :: {user_id: 2, user_pass: 123456, display_name: User One, user_email: user1@yopmail.com, user_nicename: user-one, user_url: http://go-getter} I/flutter (29058): response Error :: {"code":"rest_no_route","message":"No route was found matching the URL and request method","data":{"status":404}}

According to response issues is might be for route existence on the server.
Please guild me for above error.

2. Screenshots issues:

3. Proof of my purchased: Please find attached
![Capture](https://user-images.githubusercontent.com/61449147/75223687-04e12e80-57cd-11ea-9be7-17725ec54f0d.JPG)

3. Config files (optional)

**Comment by inspireui-tech** [comment]
@amitiitd999 - it seems your website not working - https://amit999.com/ ?

**Comment by inspireui-tech** [comment]
https://tppr.me/aEapG

**Comment by amitiitd999** [comment]
We have changed our website now. New website our app is connecting to is https://republicofchicken.in/

**Comment by minhcasi** [comment]
@amitiitd999 - could you zip the common/config folder then share us for checking - also try to update to latest 1.6.4 for the stable version - thank you!
