### ISSUE TITLE
[my-product] - fluxstore mv

### ISSUE THREAD

**Issue by nouffer** [inspireui/support#2203]
[my-product] - I recently bought multi vendor app, I am getting an error formatexception unexpected charecter 1, when both registering or login, please help me overcome this, I made all changes as document says, my site uses https, when use http on login it says wrong username and password

**Comment by inspireui-tech** [comment]
Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads  it's used to verify your proof of purchase? sorry for any inconvenience - Thank you!

**Comment by nouffer** [comment]
HI,

This is my download page screenshot

Thank you
MNouffer

**Comment by inspireui-tech** [comment]
@nouffer - pls upload again as we could not see it

**Comment by minhcasi** [comment]
@nouffer - could you share the screenshot proof purchase again, please

I will reopen the ticket after it is updated - very best!

**Comment by nouffer** [comment]
I couldnt attach the files here
