### ISSUE TITLE
[Mstore Magento] - 

### ISSUE THREAD

**Issue by taryaalo** [inspireui/support#2205]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
products image not lodes just tumble image lode only in home page.
categories image not loaded .
2. Screenshots issues:
![Screenshot_20200225-153717_Expo](https://user-images.githubusercontent.com/26363734/75252589-affde200-57e5-11ea-8270-dd453ae5cb1c.jpg)
![Screenshot_20200225-153727_Expo](https://user-images.githubusercontent.com/26363734/75252591-b12f0f00-57e5-11ea-8678-91d51c747501.jpg)
![Screenshot_20200225-153742_Expo](https://user-images.githubusercontent.com/26363734/75252592-b12f0f00-57e5-11ea-9d71-210a295fd8cc.jpg)
![Screenshot_20200225-153748_Expo](https://user-images.githubusercontent.com/26363734/75252595-b1c7a580-57e5-11ea-8842-27364dbd6966.jpg)
![Screenshot_20200225-153752_Expo](https://user-images.githubusercontent.com/26363734/75252598-b2603c00-57e5-11ea-8aee-f205e64b773b.jpg)

3. Proof of my purchased:
![Capture](https://user-images.githubusercontent.com/26363734/75252831-1b47b400-57e6-11ea-9057-4e2320979361.PNG)

3. Config files (optional)

**Comment by inspireui-tech** [comment]
@taryaalo - Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads  it's used to verify your proof of purchase? sorry for any inconvenience - Thank you!

Also try to update the Cebuilder to latest version

**Comment by taryaalo** [comment]
![Capture](https://user-images.githubusercontent.com/26363734/75329648-a2e5ff00-5888-11ea-8982-7d495a66eefd.PNG)

**Comment by minhtruong315** [comment]
@taryaalo can u send me full your source code via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/2205

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
