### ISSUE TITLE
Fluxstore WooCommerce Login Error

### ISSUE THREAD

**Issue by amolsaini** [inspireui/support#2207]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: Login Error via email

2. Screenshots issues:  
![error](https://user-images.githubusercontent.com/61465898/75258372-5f4daf80-580c-11ea-8246-1de17522fbb0.jpg)

3. Proof of my purchased: 
![purchase](https://user-images.githubusercontent.com/61465898/75258573-ae93e000-580c-11ea-89fd-a93f1a05967e.jpg)

I am getting this error again and again i have tried guide many time. Please let me know how to fix this

**Comment by inspireui-tech** [comment]
@amolsaini - could you share your common and config zip folder? Also, try to update to latest 1.6.4 release - thanks

**Comment by kvt0012** [comment]
Can you provide your username and password you use to access to this app? 
Thank you

**Comment by kvt0012** [comment]
I'll check and your email is not existed on our database, so please check again or try to sign up the another one. 
Thank you.

**Comment by amolsaini** [comment]
The error is on my app build

**Comment by kvt0012** [comment]
> The error is on my app build

How can it be ?
