### ISSUE TITLE
[FluxStore - 1.6.4] - UI issues on Product detail page

### ISSUE THREAD

**Issue by imhafeez** [inspireui/support#2208]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:

2. Screenshots issues:
![Screenshot_1582642777](https://user-images.githubusercontent.com/21155655/75259315-a25a5380-5809-11ea-86ff-35b165e230da.png)
![Screenshot_1582642771](https://user-images.githubusercontent.com/21155655/75259322-a6867100-5809-11ea-98ab-15863b2ddc14.png)

3. Proof of my purchased:
1ae3aea7-20c0-43ee-b350-c79e42c6e5ee

3. Config files (optional)

**Comment by imhafeez** [comment]
1. It happens when ads are showing. The Chat/Contact button overlaps with the cart widget.
2. When you tap on the cart the page overlaps with the status bar

**Comment by inspireui-tech** [comment]
@imhafeez -  could you share your common and config zip folder? Thank you!

**Comment by kvt0012** [comment]
Dear sir, 
You can go to file config.dart and edit EnableAdvertisement to false and the advertisement is hidden. 
Like below: 
![image](https://user-images.githubusercontent.com/49152325/75407221-09c8ee00-5945-11ea-9895-530cba221d93.png)

**Comment by imhafeez** [comment]
@kvt0012 I need to Enable Advertisements in my app. I know its fine white ad banner is hidden. I reported this issue before. but the Support team close it and claimed it we have fix it.

**Comment by kvt0012** [comment]
> @kvt0012 I need to Enable Advertisements in my app. I know its fine white ad banner is hidden. I reported this issue before. but the Support team close it and claimed it we have fix it.

So which position you want this advertisement displayed, sir ? 
And please send me your config, thanks

**Comment by imhafeez** [comment]
Please see the screenshots. And read my 1st comment. I have reported two issues. Please fix that.

**Comment by kvt0012** [comment]
Dear sir, 
Please send me your config file. 
Thank you

**Comment by imhafeez** [comment]
@kvt0012 Sent to vumanhsn97@gmail.com. Please check

**Comment by kvt0012** [comment]
> @kvt0012 Sent to [vumanhsn97@gmail.com](mailto:vumanhsn97@gmail.com). Please check

My email is vinhkhiemt135@gmail.com
Vũ Mạnh is my colleague, please send them to me, thank you

**Comment by imhafeez** [comment]
@kvt0012 Sent

**Comment by kvt0012** [comment]
What is your email ? I have many inboxes, so I can't find it, please tell me. 
Thank you.

**Comment by imhafeez** [comment]
imhafeez.ahmed@gmail.com

**Comment by kvt0012** [comment]
I'll check and maybe your version is not newest, so please make sure that you upgrade on newest version. Thank you

**Comment by imhafeez** [comment]
@kvt0012 How can you say that. Look at the top title of this issue. It says FluxStore - 1.6.4. the version i have. which has been released on 25th Feb. I have posted this issue before. It the support team says its fixed i guess two versions before. But it still the same. And it is simple. any one can reproduce it. Just enable ads and on the product detail page. then tap on the card. you will see that. you cannot go back . all the top buttons are overlapped with the status bar.

and its been 8 days. you didn't even see that. you keep telling me send me the config etc. or i have not the updated version. from the screenshots i attached. its that simple.

@minhcasi

**Comment by minhcasi** [comment]
@imhafeez - sorry for misunderstanding your point, could I know which the Android device version you are using for testing? We are working on new release 1.6.5 on next couple of days and will include the patching for this issue

**Comment by imhafeez** [comment]
@minhcasi Its the same on any version. Even on iPhone. On android you can go back on device back button but you will be completely stuck on the iPhone. as there is no device back button. and app back button overlaps with the status bar. 
1. Enable Ads
2. add some products to the cart.
3. Go to product detail page
4. Tap on cart from the product detail page. 

you got stuck!!!!

**Comment by minhcasi** [comment]
@dttrung26 - pls help to investigate this issue

**Comment by dttrung26** [comment]
Good afternoon @imhafeez ,
please kindly download attached files below and replace as following instruction: 
 + replace cart.dart into ../lib/screens/cart.dart
 + repleace simpleType.dart into ../lib/screens/detail/themes/simpleType.dart 
[Config imhafreez - customer bug.zip](https://github.com/inspireui/support/files/4311126/Config.imhafreez.-.customer.bug.zip)

Please inform me if you still get trouble. 
Have a nice day!

**Comment by minhcasi** [comment]
@imhafeez - pls let us know if you could fix the issues by above solution, we also update this patching on lastest release - feel free to reopen the ticket if you have any issues - thank you!

**Comment by imhafeez** [comment]
Thank you @minhcasi. I'll update here on this thread ASAP.
Thanks @dttrung26

**Comment by imhafeez** [comment]
Its not fixed @minhcasi @dttrung26 

### **Android screenshots**

![Screenshot_1584111119](https://user-images.githubusercontent.com/21155655/76632260-c08fb580-6564-11ea-830b-dab6d92afc82.png)

![Screenshot_1584111080](https://user-images.githubusercontent.com/21155655/76632263-c71e2d00-6564-11ea-8b1c-75e1ee61219d.png)

### **iPhone screenshots**

![Simulator Screen Shot - iPhone Xʀ - 2020-03-13 at 19 44 10](https://user-images.githubusercontent.com/21155655/76632298-d69d7600-6564-11ea-8e85-40cd248ee39e.png)
![Simulator Screen Shot - iPhone Xʀ - 2020-03-13 at 19 43 52](https://user-images.githubusercontent.com/21155655/76632313-dac99380-6564-11ea-9658-ded81c87f49f.png)

**Comment by dttrung26** [comment]
Hi @imhafeez , 
please leave your skype here so that I can contact and do teamview in your development environment. 
Many thanks.
Trung.

**Comment by minhcasi** [comment]
@imhafeez - Please also download the latest release Fluxstore 1.6.5 release 

We also note the detail changelogs from this blog -https://medium.com/@inspireui/announcing-fluxstore-1-6-337efff1791f  - thank you!

**Comment by imhafeez** [comment]
> Hi @imhafeez ,
> please leave your skype here so that I can contact and do teamview in your development environment.
> Many thanks.
> Trung.

my skype is **hafeez.moha** You can add me. I'll contact you so that we can debug it.
Thanks

**Comment by imhafeez** [comment]
> @imhafeez - Please also download the latest release Fluxstore 1.6.5 release
> 
> We also note the detail changelogs from this blog -https://medium.com/@inspireui/announcing-fluxstore-1-6-337efff1791f - thank you!
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/1f55d85bfc898e06f175857fb52934c71284d708/68747470733a2f2f6d69726f2e6d656469756d2e636f6d2f6d61782f313230302f312a7577347776547456575f44434261536b4f6c47786d512e6a706567"><img alt="" height="14" src="https://camo.githubusercontent.com/a1c598ee8610a8cdb0e8bdbf112f3f1c77af25cb/68747470733a2f2f63646e2d7374617469632d312e6d656469756d2e636f6d2f5f2f66702f69636f6e732f66617669636f6e2d72656272616e642d6d656469756d2e33593678705a2d3046536457446e504d3368534249412e69636f"> Medium**[Announcing Fluxstore 1.6](https://medium.com/@inspireui/announcing-fluxstore-1-6-337efff1791f)**Latest update 14/12/2019

Sure @minhcasi . I will download the latest build. Thanks

**Comment by dttrung26** [comment]
Hi @imhafeez , could you add my Skpye: dttrung.ityu please 'cause I can't find yours. Many thanks.

**Comment by minhcasi** [comment]
@imhafeez - please confirm if the issues are resolved with your site? Thank you!

**Comment by imhafeez** [comment]
Not yet. I am working with @dttrung26 via Skype. I'll update there once resolved. Thanks

**Comment by dttrung26** [comment]
Solved via skype.
