### ISSUE TITLE
[Fluxstore-Listing] Incorrect Figma file

### ISSUE THREAD

**Issue by mohachouch** [inspireui/support#2209]
1. My issue:

The Figma file is incorrect in the Fluxstore listing directory. It's the same of the Fluxstore multivendor app.

2. Screenshots issues:

<img width="344" alt="image" src="https://user-images.githubusercontent.com/25939826/75274236-c8c8c080-5802-11ea-9ad2-10c8a6df295d.png">

3. Proof of my purchased:

<img width="656" alt="image" src="https://user-images.githubusercontent.com/25939826/75274285-e007ae00-5802-11ea-814a-64eccb54c9b3.png">

**Comment by inspireui-tech** [comment]
@mohachouch - it's using the same core library and design system - you can try to take the screenshot of Listing by applying from the Example folder (Flutter Code) - thank you!
