### ISSUE TITLE
[ListPro] Error

### ISSUE THREAD

**Issue by jaksatomovic** [inspireui/support#221]
**Mandatory Info (please complete the following information):**
 - Product: [ListPro]
 - Your Purchased Code: [e52cfbdd-f79e-4946-ae15-0daadc94fdfa]
(we may not reply if you are not our customer)

Hi upon installing app via CeBuilder or Manually i get red screen error saying:
null is not an object(evaluating't.better_featured_image.source_url')

**Comment by thangvo9x** [comment]
Hi. First, Thanks for your purchase. Please give me your info admin for checking
email thang@inspireui.com and subject your id issue is 221 to record. Thanks

**Comment by jaksatomovic** [comment]
This is mobile app...i dont have any admin..i just tried to run with default settings

**Comment by thangvo9x** [comment]
fixed
