### ISSUE TITLE
[MStore MultiVendor] - Last update problems with install yarn

### ISSUE THREAD

**Issue by flapron** [inspireui/support#2210]
1. My issue:
Since the last update of the multivendor app I'm facing problems with "yarn install"

2. Screenshots issues:
![image](https://user-images.githubusercontent.com/61477774/75288265-4947eb00-581c-11ea-9366-28413b32b380.png)

3. Proof of my purchased:
![image](https://user-images.githubusercontent.com/61477774/75287900-88297100-581b-11ea-85fe-e029087ddaac.png)

3. Config files (optional)

**Comment by inspireui-tech** [comment]
@flapron - pls try to install yarn to fix this problem - https://yarnpkg.com

**Comment by flapron** [comment]
Hi,

Its about the error above. Yarn was installed at that moment. (Later I did a uninstall so thats why it says yarn isnt installed)

**Comment by luyx2412** [comment]
Hi @flapron Please reinstall `yarn` or you can use `npm install` to install package.

Thanks
