### ISSUE TITLE
[Fluxnews] [Crash] when using Dynamic Homepage Layout Setting

### ISSUE THREAD

**Issue by wilwe-yj** [inspireui/support#2211]
When I change 

const kAppConfig = 'https://json-inspire-ui.inspire.now.sh/config.json ';

my apps crash 
![Screenshot 2020-02-26 at 7 59 42 AM](https://user-images.githubusercontent.com/59247200/75298716-39f18d80-586e-11ea-82a6-6cdde7beb053.png)

 

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
**The following NoSuchMethodError was thrown building Consumer<AppModel>(dirty, dependencies: [InheritedProvider<AppModel>]):
The method '[]' was called on null.
Receiver: null
Tried calling: []("MainColor")**

The relevant error-causing widget was: 
  Consumer<AppModel> file:///Users/wilwe/development/TTHapps/ride_lah/lib/app.dart:158:14
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      AppState.build.<anonymous closure> (package:ride_lah/app.dart:209:53)
#2      Consumer.build (package:provider/src/consumer.dart:180:12)
#3      StatelessElement.build (package:flutter/src/widgets/framework.dart:4291:28)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4223:15)

**Comment by inspireui-tech** [comment]
@wilwe-yj - please try to upload your new own config.json file to fix the problem, the file content should be the same as the common/config.json from the project folder

example try this one - http://fluxnews.surge.sh/config.json

**Comment by wilwe-yj** [comment]
cause the one I added is with a woo-commerce server if follow this then the product page is not going to happen d rite?
