### ISSUE TITLE
[Fluxstore] - minor ui bugs

### ISSUE THREAD

**Issue by fluttergamer** [inspireui/support#2212]
1.) my issue: minor ui bugs. To improve user experience.

2.) screenshot issue: 
![b503c673-b9b6-4995-a88b-b04fedec858a](https://user-images.githubusercontent.com/61487819/75312983-7afd9800-5896-11ea-8469-a1535442f2d5.jpeg)
2.1 - Cannot see the back arrow button in dark mode and hardly can view the middle text as well.
<br />

![fea8237c-befa-43f7-a743-0b68af655912](https://user-images.githubusercontent.com/61487819/75313090-cadc5f00-5896-11ea-9f89-6fbf0dc7262a.jpeg)
2.2 - After cleared the search text...the text still remains there...should be removed after exit the search page.
<br />

![8aa09799-7b58-4ba7-9f85-7aaa5071ae79](https://user-images.githubusercontent.com/61487819/75313022-9c5e8400-5896-11ea-8329-5d91dce07dfe.jpeg)
2.3 - Put some debounce/delay to the search bar...don't straight away type the first letter then search instantly...and the input text cannot view in dark theme mode...it appears to be white in colour same as the background.
<br />

![6e03968a-fb8b-4d39-a103-ea7cbc6cdc28](https://user-images.githubusercontent.com/61487819/75313305-771e4580-5897-11ea-83ad-e1f0e6bd2b37.jpeg)
2.4 - the star rating wont update after putting it.
<br />

![20f9cb21-43e2-4d12-b0f7-6df2acae20b3](https://user-images.githubusercontent.com/61487819/75313333-8b624280-5897-11ea-9111-865012593bc3.jpeg)
2.5 - while loading, the splash screen stucked there for awhile. Not looking very nice.
<br />

![84825dea-20e7-4584-b066-94086a2e64bd](https://user-images.githubusercontent.com/61487819/75314385-8e126700-589a-11ea-9521-f5ab404d9372.jpeg)
2.6 - Is it possible to change the loading screen to use shimmer effect instead. Recommended.
<br />

![4df80af5-3cb7-4452-8758-93d83162e87d](https://user-images.githubusercontent.com/61487819/75315917-f400ed80-589e-11ea-9f30-f373b99473a1.jpeg)
![bf53f52f-4eb9-4b03-a6d6-4314f206ad2a](https://user-images.githubusercontent.com/61487819/75316013-2e6a8a80-589f-11ea-9b4f-8281ffb7056d.jpeg)
2.7 - if search only found one result. After that, you clicked the map icon, there will be duplicated  card for the whole horizontal list view. Should shows only one card instead of many same card.
<br />

![25d8b55f-8939-4dc6-bfb8-e74eec2bc3ce](https://user-images.githubusercontent.com/61487819/75317628-7095cb00-58a3-11ea-8623-6613c9cd717c.jpeg)
2.8 - UI not responsive to landscape mode.
<br />

3.) proof of my purchased: 
398351fa-34ba-4cd5-a15f-a5a0a937f003

**Comment by fluttergamer** [comment]
Item Purchase Code:
398351fa-34ba-4cd5-a15f-a5a0a937f003

**Comment by minhcasi** [comment]
@fluttergamer - thank you for your the suggestion, we will investigate and keep an upgrade - very best!

**Comment by minhcasi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fluxlisting UI Uprade](https://trello.com/c/TxBmiDWX/25-fluxlisting-ui-uprade)

**Comment by minhcasi** [comment]
moved to backlogs
