### ISSUE TITLE
[Fluxnews] Sign in with Apple Button - AppStore Rejected

### ISSUE THREAD

**Issue by aldoyh** [inspireui/support#2213]
Hello,
The button was working but then stopped and I don't know how to Open this issue again:

https://github.com/inspireui/support/issues/1995

Your help is needed, thanks in advance.

**Comment by minhcasi** [comment]
@dttrung26 - pls help to suggest this issue - thank you!

**Comment by dttrung26** [comment]
Hi @aldoyh , 
could you please send me issue  screenshots in specific here? Many thanks!

**Comment by aldoyh** [comment]
Sorry dear, I don't have any errors showing because it's happening with AppStore testing, but it's working on my simulator which is why I'm asking for feedback here, if you may allow me:

https://github.com/inspireui/support/issues/2282
