### ISSUE TITLE
[fluxstore] - UI issue for Product Carousel 

### ISSUE THREAD

**Issue by themeix** [inspireui/support#2214]
1. My issue:
I am facing 2 issues in that app. Here are the details :
**1 Product Carousel ( threeColumn) layout UI has a serious problem. When i scroll it, Full product not showing there and its going to the off  screen.
Example : https://i.postimg.cc/vHYQXJ3f/screenshot-619.png
https://i.postimg.cc/qR4Y4TtG/screenshot-620.png

2. Screenshots issues:

3. Proof of my purchased:
https://raw.githubusercontent.com/themeix/temp/master/screenshot-589.png

3. Config files (optional)

**Comment by themeix** [comment]
I fixed the **2 

Please answer for First issue

**Comment by minhcasi** [comment]
@themeix - pls update the isSnapping: false to fix the issue - thanks
