### ISSUE TITLE
[my-product] - 

### ISSUE THREAD

**Issue by vishal5173** [inspireui/support#2215]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: After Installing "Mstore Expo - Complete React Native template for WooCommerce" and running i am getting following error:
warn Package api-ecommerce has been ignored because it contains invalid configuration. Reason: Cannot find module 'api-ecommerce\package.json'.

I also tried installing api-commerce package using Yarn (yarn add api-ecommerce) but it is showing command failed.

2. Screenshots issues: (https://prnt.sc/r7urya)

3. Proof of my purchased: Registered email id: info@lovzme.com

3. Config files (optional)

**Comment by minhcasi** [comment]
@vishal5173 - could you help to take the screenshot purchased from http://codecayon.net/downloads as we could not verify via email - sorry for any inconvenience - very best
