### ISSUE TITLE
[Fluxstore Woo-commerce] - Paypal issue

### ISSUE THREAD

**Issue by LucAmidei** [inspireui/support#2218]
1. My issue: PayPal login doesn't work. When I try to log into PayPal I get a validation error (I'm sure that email and password are both correct).

2. Screenshots issues: 
![WhatsApp Image 2020-02-25 at 15 56 45](https://user-images.githubusercontent.com/15093864/75350617-1c8ce580-58a7-11ea-9aef-f2f02f886ce5.jpeg)

3. Proof of my purchased: 
![acquisto fluxstore](https://user-images.githubusercontent.com/15093864/75350757-52ca6500-58a7-11ea-9a48-72f468b43119.png)

**Comment by minhcasi** [comment]
@LucAmidei - could you translate the error? Please note that the paypal is support both Sandbox and Live mode, please also check the key to match with these setting - thanks

**Comment by LucAmidei** [comment]
It says "some of your info isn't correct. Please try again", while I'm sure about that username/password combination. I downloaded the Fluxstore app from the PlayStore and I get the same error

**Comment by minhcasi** [comment]
@minhtruong315 - pls help for investigating - thank you!

**Comment by minhtruong315** [comment]
@LucAmidei I'm so sorry for delay. I will check our app. I can help check the issue remotely. can u send me your skype?

**Comment by LucAmidei** [comment]
amidei.luca@hotmail.it

**Comment by minhtruong315** [comment]
I messaged you on the skype. please check

**Comment by minhcasi** [comment]
@LucAmidei - let me know if you have any feedback - thank you!
