### ISSUE TITLE
[ListApp] - Important Issue 

### ISSUE THREAD

**Issue by smsmalex** [inspireui/support#222]
**Mandatory Info (please complete the following information):**
 - Product: [ListApp]
 - Your Purchased Code: 4058cc9b-4525-4f66-ae1c-ed34dabe03bf
- Theme: MyListing

**Describe the issues**
Hello sir
I have many problems with the App
I kept reading all the problems that everyone faces either here or on the comments page.
Without finding a solution to my problems:

**Even though I have installed the necessary Plugins completely and even the paid Plugins without merit.**

- 1- The booking button does not work and restarts the application again, even the problem in your trial version.
- 2- Heart button to add to Favorites re-run the application again.
- 3- In your trial version even if the booking button works successfully, the booking date does not appear and takes you to the next step.
- 4- I did not find a good document explaining to the user how to add a product or learning clearly.
**Finally:**
Do you help me install and produce the application as in your pictures? How much will it cost me?

**Comment by thangvo9x** [comment]
Hi. Can you give me your AppConfig.json such as your template in Config folder, plz?
thang@inspireui.com. subject with your id issue is 222.
Thanks

**Comment by smsmalex** [comment]
Sent to you

**Comment by smsmalex** [comment]
Any news??

**Comment by minhcasi** [comment]
@thangvo9x

**Comment by thangvo9x** [comment]
I received your mail but your account can't login. i'm waiting from you for another account. I have been it already. I'm checking it.

**Comment by smsmalex** [comment]
> I received your mail but your account can't login. i'm waiting from you for another account. I have been it already. I'm checking it.

i sent to you another account by mail from 2 hours
and i test it from 3 devices and login successfully 
i dont know what wrong with you??
and sent to you new mail again 
wait you
Regards

**Comment by thangvo9x** [comment]
@smsmalex .

**Comment by smsmalex** [comment]
i will check it
thanks

**Comment by smsmalex** [comment]
after check the new source code the error is gone
but
Before I bought the application I saw some features in the pictures and this encouraged me to buy it.
And even when I bought Wright pictures in the photo folder with these possibilities, but I did not find enough explanation to activate and operate those possibilities
I want to link the application to my site as in the pictures Tamam and all the possibilities
Even the bottom icons do not match the images in the application
What I lack of additions is that I have followed your entire explanation without a concrete result
Do you sell the application and ask for extra money each give us the full code as in the pictures ??
If that is what is required to output for the same result as the application in the images
Because I see this as misleading for customers
Wait for the full response to resolve these problems before making a decision to continue with you or not
For information:
If you arrive for the result as the photos there will be a great cooperation between us because we are a company in France and we have a lot of customers
We own a lot of ideas and we will send them to your company
Believe me and our future ideas with more than your imagination
Greetings

**Comment by minhcasi** [comment]
Hi, sorry for the late and confusion communication above. The package we provide is the latest version with full functionalities - no misleading, as there are some extra screen and enhancement come up with new update so that we have to change the bottom navigations. 

Could you let us know which the pictures that we have missing from the download? Then we could revise the Ads banner or refactor the navigation again

**Comment by smsmalex** [comment]
thank for your fast response
first pic is
https://inspireui.com/wp-content/uploads/2018/11/listapp.png
the main image at codcanyon 
second
in the screenshot folder as example picture name (Simulator Screen Shot - iPhone 7 - 2018-02-21 at 13.21.08)
i see reserve button and another one is booking now 
how can i get these features in my app?
i install all necessary plugins in my wp
how can i get app like your picure??
regards

**Comment by smsmalex** [comment]
and when i try to book something there are miss start time date error

**Comment by thangvo9x** [comment]
Okie @sms. We'll check the source again. Thanks for your value feedback.

**Comment by smsmalex** [comment]
its to long time
whats new??

**Comment by minhcasi** [comment]
Hi @smsmalex - we're sorry for the delay as the team is having the Tet holiday in this whole week, they will back to work on next week - thank you!

**Comment by smsmalex** [comment]
> Hi @smsmalex - we're sorry for the delay as the team is having the Tet holiday in this whole week, they will back to work on next week - thank you!

Ok Happy New Year :)

**Comment by smsmalex** [comment]
i ask to refund my amount for next reason
1- Two weeks so far I have to try my problem without a result.
2-The images in the application do not match the codes they sell
3- I think you could not solve the problem by proof that you asked to replace files in the source again without result
4- Any comment I write, you review and hide it and this is misleading
you ignores all my messages and replies to the latest messages from my message and this is clear in the comments of the product
So
Please refund my amount in Envato


Regards

**Comment by minhcasi** [comment]
Kindly refund from this link - https://help.market.envato.com/hc/en-us/articles/202821460-Can-I-Get-A-Refund- - thanks
