### ISSUE TITLE
fluxstore pro

### ISSUE THREAD

**Issue by mattia9055** [inspireui/support#2222]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: when i edit config.dart  "isCaching": true,"   recent collection not working  

2. Screenshots issues:  http://tarekelsallab.com/app/PM.jpeg

3. Proof of my purchased:a c45bad8-8c8c-4ae3-908a-90d2b2d2ad22 - 30 Jan 2020

3. Config files (optional)

**Comment by minhcasi** [comment]
@mattia9055 - could I check if you have uploaded the common.json file to the mstore-api plugin setting (from the Wordpress site) - thank you!

**Comment by mattia9055** [comment]
I was upload many times but still not working

**Comment by minhcasi** [comment]
@mattia9055 - pls zip your common and config folder here - we will help for checking - thank you!

**Comment by mattia9055** [comment]
[common.zip](https://github.com/inspireui/support/files/4274424/common.zip)
that is

**Comment by kvt0012** [comment]
please send me your whole project, I cannot run with your common file, thank you

**Comment by minhcasi** [comment]
@mattia9055 - pls hep to resend your project to vinhkhiemt135@gmail.com and reopen the ticket - thank you!
