### ISSUE TITLE
[Fluxstore] - Rate this app is no't working

### ISSUE THREAD

**Issue by hssinaman** [inspireui/support#2224]
1. My issue:
Hi, 
Rate this app is no't working can you fix it please? 
2. Screenshots issues:
![Screenshot_20200227_013108](https://user-images.githubusercontent.com/61097607/75400941-f4ca6b80-5900-11ea-9534-0d32c13ba24c.jpg)

3. Proof of my purchased:
![Screenshot_20200225_153005_com android chrome](https://user-images.githubusercontent.com/61097607/75400837-ab7a1c00-5900-11ea-962c-4a536a018fc7.jpg)

3. Config files (optional)

**Comment by kvt0012** [comment]
Do you upgrade to the newest version ? Check your version again please 
Thank you

**Comment by hssinaman** [comment]
Ok i will check in the updated version 
thanks

**Comment by kvt0012** [comment]
Ok, and I think it works for you now. So I will close this issue. 
Thank you
