### ISSUE TITLE
Fluxstore - Firebase login. 

### ISSUE THREAD

**Issue by gurutos** [inspireui/support#2225]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
Hello Support Team,

I have issues trying to connect Firebase:

I follow this guide: https://docs.inspireui.com/fluxstore/customization/
Android app: Search on android folder and replace the following file - https://tppr.me/bWCvp
android/app/build.gradle
android/app/src/main/AndroidManifest.xml
android/app/src/main/kotlin/com/inspireui/fluxstore/MainActivity.kt
Rename the folder android/app/src/main/kotlin/com/inspireui/fluxstore to your own bundle name, example: if you bunndle id is com.ins.flux, it will be android/app/src/main/kotlin/com/ins/flux
Please note that the file android/app/google-services.json should be changed to match your new bundle id. Otherwise the app will crash.

but when i verify the installation it cant make the connection:

2. Screenshots issues:

![image](https://user-images.githubusercontent.com/61175861/75410998-bd9d8f80-58eb-11ea-8119-177f4eda0f75.png)

3. Proof of my purchased:
![image](https://user-images.githubusercontent.com/61175861/75411458-4a951880-58ed-11ea-9b16-94b31ce7f779.png)

3. Config files (optional)

**Comment by kvt0012** [comment]
Do you uninstall your app and reinstall it again ?

**Comment by gurutos** [comment]
Hello Kvt0012, 

Yes, i remove it and reinstall again 3 times, its there a process to do it right?

Thanks and Regards,
PMontes

**Comment by kvt0012** [comment]
Yeah, you can follow this guide and video to do this. 
https://firebase.google.com/docs/android/setup

**Comment by gurutos** [comment]
Good Day Support Team!!

Yes i also check that guide, 

i think its a general error because it doesn't let me do simple things, 

can you support me at skype?

Thanks in advance,
Pao Montes.

**Comment by dured007** [comment]
After changing google-services.json file
go the terminal (you should be in the app source folder )and run "flutter clean"
uninstall your app, reinstall it and it should work

**Comment by gurutos** [comment]
Good day dured,

Ok i try it, but firebase dont give a proper connection, 

Can you assist this case by skype?

Thanks and Regards,
Pao Montes.

**Comment by minhcasi** [comment]
@gurutos - pls move the comment to #2198

**Comment by gurutos** [comment]
hello minhcasi,

please dont close our issues without support, 

the other issue its different,

Thaks and Regards,
PaoMontes
