### ISSUE TITLE
Fluxstore - Categories issue. 

### ISSUE THREAD

**Issue by gurutos** [inspireui/support#2226]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:

Good Day Support Team,
I have the next issue, i integrate with my website following this guide: https://docs.inspireui.com/fluxstore/woocommerce-setup/

I can visualize the stores and the products of the stores, but when i try to see the categories they are not showing, i got the number of the categories and past it to the banner image part, number of categorie but they are not showing:

2. Screenshots issues:

![image](https://user-images.githubusercontent.com/61175861/75411909-e410fa00-58ee-11ea-8ba4-2b5ae9f6f32a.png)

3. Proof of my purchased:
![image](https://user-images.githubusercontent.com/61175861/75411952-099e0380-58ef-11ea-9911-bee18c491264.png)

3. Config files (optional)

**Comment by gurutos** [comment]
Good Day Team,

any news? 

thanks in advance, 
Paola Montes.

**Comment by gurutos** [comment]
Hello Team,

do you have any news?

Thanks and Regards,

**Comment by minhtruong315** [comment]
@gurutos can u send me config.dart file

**Comment by gurutos** [comment]
hello minhtruong315,

i have 2 more issues that where assigned to you, can we check all 3? i already send you my skype, its paolamontesp,

let me know please when can we connect?

thanks and regards,
Pao Montes.

**Comment by minhcasi** [comment]
@gurutos - move to #2198 - kindly move to one ticket for your all issue that helps the team support you better - thank you for your understanding
