### ISSUE TITLE
[FluxStore Pro] - Null assertion on product detail view

### ISSUE THREAD

**Issue by Pankti16** [inspireui/support#2228]
1. My issue: Getting a null assertion on the product detail view.
App crashes on the following, there is no log or crash report regarding it:
- do nothing for 2 minutes and app crash.
- click on WhatsApp in live chat.
- click on login under the login profile.
- click on homepage banners
It is crashing on doing anything so I could not test much.

Fluxtore version: 1.6.4
currently working with an opencart website.

2. Screenshots issues: 
![photo6251388181832378743](https://user-images.githubusercontent.com/28388925/75423886-a8654700-5965-11ea-8b64-886da551d275.jpg)

3. Proof of my purchased: 
[57524828-fluxstore-the-universal-woocommerce-magento-opencart-mobile-app-by-flutter-framework-license.pdf](https://github.com/inspireui/support/files/4260264/57524828-fluxstore-the-universal-woocommerce-magento-opencart-mobile-app-by-flutter-framework-license.pdf)

3. Config files (optional) : [config.zip](https://github.com/inspireui/support/files/4260273/config.zip)

**Comment by kvt0012** [comment]
Dear sir, 
Can you send me your config file? 
Thank you

**Comment by kvt0012** [comment]
Dear sir, 
Firstly, please edit your config file, change layout to this 
![image](https://user-images.githubusercontent.com/49152325/75429487-757a7d80-597c-11ea-913b-5a396abbdf08.png)

Your original 
![image](https://user-images.githubusercontent.com/49152325/75429532-84f9c680-597c-11ea-86ce-903d3eabe5c6.png)

It raised error.

**Comment by Pankti16** [comment]
example/opencart/config.dart.txt file had the following

```
const kProductDetail = {
  "height": 0.5,
  "marginTop": 0,
  "isHero": false,
  "safeArea": false,
  "showVideo": true,
  "showThumbnailAtLeast": 3,
  "layout": kProductLayout.simpleType
};
```
and to fix the error I added 

```
enum kProductLayout {
  simpleType,
  fullSizeImageType,
  halfSizeImageType,
  oneQuarterImageType
}
```
in my constants.dart file

I have also attached the config.dart.txt file from opencart example
[config.dart.txt](https://github.com/inspireui/support/files/4260671/config.dart.txt)

**Comment by kvt0012** [comment]
Ok I'll check it and I think because you've not set up yet, so it raises error. 
Did you try with our default setting ? Is it normal ? 
Thank you

**Comment by Pankti16** [comment]
It is the same with the default settings.

**Comment by kvt0012** [comment]
Your config file you sent me is different and I can't load anything from your api, so it leads to the error. 
Please follow the docs and set up again. 
Thank you 
Here is our doc : https://docs.inspireui.com/

**Comment by Pankti16** [comment]
I did follow the docs and copied config.dart.txt to my lib/common/config.dart as stated in the docs.
Below is the screenshot I have attached. App also crash with three-finger gesture. 
![photo6251300409880717711](https://user-images.githubusercontent.com/28388925/75434879-39ddb480-5978-11ea-8f6a-3ffb2feeaff0.jpg)

**Comment by kvt0012** [comment]
I'll test and everything is ok 
so which emulator you use ?

**Comment by Pankti16** [comment]
I am testing on a real device.

**Comment by kvt0012** [comment]
So which is your model ?

**Comment by Pankti16** [comment]
Redmi 5A

**Comment by kvt0012** [comment]
I'm sorry we don't have this device or similar to test. 
I test on real device is Vsmart live,it's normal.

**Comment by kvt0012** [comment]
If you can, please change the device and test again, thank you

**Comment by Pankti16** [comment]
Sure, let me try with a different device.

**Comment by Pankti16** [comment]
Login is working well with Redmi Note 3. But I still can not understand for it to not work with Redmi 5A. Apart from this, it is still crashing with the following:
- Click on the product.
- Click on homepage banners (I have set category id on banners as was in default JSON).

**Comment by kvt0012** [comment]
> Login is working well with Redmi Note 3. But I still can not understand for it to not work with Redmi 5A. Apart from this, it is still crashing with the following:
> 
> * Click on the product.
> * Click on homepage banners (I have set category id on banners as was in default JSON).

I don't know how it works on redmi because I can't have a device to test. 
Our app is run well on Huawei but with Redmi it has several things is not right. I think because they develop the other OS powered by Android so it has different things. But not only our app, but also I think here is the common situation of flutter app. Sorry for your inconvenience

**Comment by Pankti16** [comment]
So, let me try with another device then.

**Comment by kvt0012** [comment]
> So, let me try with another device then. But this should not happen right?

Yes, we're just heard about redmi problem, not other brand.

**Comment by Pankti16** [comment]
I am sorry but I also tried on Samsung Galaxy J3 Pro not working. And I can not request my users to change their phone for using my app. Could you please help me fix the issue.

**Comment by kvt0012** [comment]
Which error do you meet on J3 pro ? Are they same ?

**Comment by Pankti16** [comment]
Yes they are same.

**Comment by Pankti16** [comment]
Could you help me via anydesk or teamviewer session? In case if there is an installation error. I have followed all the steps as per documentation.

**Comment by kvt0012** [comment]
Oh when I scroll down and see this. 
![image](https://user-images.githubusercontent.com/49152325/75641136-d4384380-5c69-11ea-8a9a-c2d54691b572.png)

The file must be .dart, not .dart.txt because .dart is the file of dart language.

**Comment by Pankti16** [comment]
The file in example folder is .dart.txt not for the lib folder. The file name is config.dart in the lib folder.

**Comment by kvt0012** [comment]
Ok, so to make the problem clearly, can you record the video to describe your problem? 
Thank you

**Comment by Pankti16** [comment]
Would you be able to come to a remote session via anydesk or teamviewer?

**Comment by kvt0012** [comment]
Ok, I will support you throughout skype, please give me your skype, thank you

**Comment by Pankti16** [comment]
Sure, my skype name is live:.cid.d08a75cfbf15215e

**Comment by Pankti16** [comment]
Could you please help us as early as possible as this is an urgent task for us to achieve. Our further tasks are lined up after achieving this.

Thank You

**Comment by kvt0012** [comment]
Ok support on Skype

**Comment by Pankti16** [comment]
The issue is not solved yet. Eventhough why the issue is closed?

**Comment by kvt0012** [comment]
Yeah I send the solution on your skype, thank you

**Comment by Pankti16** [comment]
Okay, but could you provide docs for opencart instead of wordpress, thank you.

**Comment by kvt0012** [comment]
@minhtruong315  I'll check and problem is about opencart api, please help him fix it, thank you.

**Comment by minhtruong315** [comment]
@Pankti16 I messaged you on the skype. please relay. thanks

**Comment by minhtruong315** [comment]
@Pankti16 try to use this url ```https://www.mayloz.com``` then run again

**Comment by Pankti16** [comment]
But, what if want to use `https://www.mayloz.in` url?

**Comment by minhtruong315** [comment]
Did you install Mstore extension on https://www.mayloz.in ?

**Comment by Pankti16** [comment]
Yes, it is installed.

**Comment by minhtruong315** [comment]
take me screenshot?

**Comment by Pankti16** [comment]
![ssMstore](https://user-images.githubusercontent.com/28388925/76191853-4b3f8000-6206-11ea-8fa0-0a1b185b3f21.PNG)

**Comment by minhtruong315** [comment]
https://tppr.me/qbY8s did you click this button to refresh?

**Comment by Pankti16** [comment]
Yes, I did click on it.

**Comment by minhtruong315** [comment]
Send me admin account for  https://www.mayloz.in via the skype?

**Comment by Pankti16** [comment]
Sent you the details.

**Comment by minhtruong315** [comment]
I can't open this site https://www.mayloz.in. it always redirect to https://www.mayloz.com

**Comment by Pankti16** [comment]
Try using VPN.

**Comment by minhtruong315** [comment]
i dont have VPN

**Comment by Pankti16** [comment]
You may see it via anydesk on our device, then.
