### ISSUE TITLE
[Mstore-Multi vendor] -  I installed the latest version but I get 3 errors.

### ISSUE THREAD

**Issue by muratakgoz** [inspireui/support#2229]
![Ekran Resmi 2020-02-26 19 36 16](https://user-images.githubusercontent.com/22097767/75429017-2b80a000-595a-11ea-9f2c-b7fa405d8c31.png)
Facebook login stays in loop and won't open

![6f854fb3-87a2-4950-bdf2-09f98382ec83](https://user-images.githubusercontent.com/22097767/75429118-50751300-595a-11ea-9a11-dfba8b6d4ea0.jpg)

I tried as jwt and editor at product entry but it gives this error.
![5ec3218d-b019-4454-b607-2002e2498c0b](https://user-images.githubusercontent.com/22097767/75429231-831f0b80-595a-11ea-80f2-7fa89a2776f7.jpg)

When I try to buy a product, the country selection is distorted on the screen and it does not.

![436d9940-27cb-4363-a7c6-ed6e112aefd6](https://user-images.githubusercontent.com/22097767/75429312-a0ec7080-595a-11ea-97a0-ca9b526cdb3a.jpg
[common.zip](https://github.com/inspireui/support/files/4260604/common.zip)

**Comment by minhcasi** [comment]
sorry we already approved your refund, please try to purchase again if you continue to use the product - thanks
