### ISSUE TITLE
ListApp is not getting Featured Image for single Listing using Listify theme.

### ISSUE THREAD

**Issue by QDemNark** [inspireui/support#223]
**Required Info (please complete the following information):**
 - Product: [e.g. MStore, ListApp]
 - Your Purchased Code: [get from https://codecanyon.net/downloads]
(we may not reply if you are not our customer)

**Describe the bug**

**Screenshots**

**Additional context**
Add any other detail logs about the problem here.
If possible please share your config.js that use for the app setting

**Comment by QDemNark** [comment]
Hi
Why is all Featured Images being shown on the front page but not when I click on the specific listing?

**Comment by minhcasi** [comment]
Hi, @QDemNark - we are not sure to understand your idea  - could you share the screenshot - thank you!

**Comment by QDemNark** [comment]
Hi Minh

Thanks so much for your mail.

Featured Images are visible when displayed in the overview. Example at Front Page and Related Post etc.
Please see 2 attached jpg files.

However, Featured Images are not visible when viewing single Listings.
Please see attached jpg file for Single Listing.

*Please note that I am using Listify theme.


Best regards
Qais Wardag
https://www.myself.dk



________________________________
Fra: Minh Pham <notifications@github.com>
Sendt: 29. januar 2019 13:40
Til: inspireui/support
Cc: QDemNark; Mention
Emne: Re: [inspireui/support] ListApp is not getting Featured Image for single Listing using Listify theme. (#223)


Hi, @QDemNark<https://github.com/QDemNark> - we are not sure to understand your idea - could you share the screenshot - thank you!

**Comment by thangvo9x** [comment]
Hi. ListApp using Feature Image to display listing. when clicking each listing. it'll using gallery_images.
Thanks

**Comment by QDemNark** [comment]
Hi thanks you your mail.

How can I use Feature Image to display on each listing (single listing).
* Witch file do I have to change and can you provide any code?

Best Regards
Qais
Myself.dk<http://Myself.dk>

Den 30. jan. 2019 kl. 08.12 skrev thangvo9x <notifications@github.com<mailto:notifications@github.com>>:


Hi. ListApp using Feature Image to display listing. when clicking each listing. it'll using gallery_images.
Thanks

**Comment by thangvo9x** [comment]
Hi. You can set it at section "Gallery Images", It was been beside sections "cover image, logo image..."
Thanks

**Comment by QDemNark** [comment]
Hi
Ok, but do you mean in WordPress Backend - > Specific Plugin settings or a File in Folder Source?
If you mean a File in Folder Source, then which file?

Best regards
Qais Wardag
https://www.myself.d<https://www.myself.dk>k



________________________________
Fra: thangvo9x <notifications@github.com>
Sendt: 31. januar 2019 09:49
Til: inspireui/support
Cc: QDemNark; Mention
Emne: Re: [inspireui/support] ListApp is not getting Featured Image for single Listing using Listify theme. (#223)


Hi. You can set it at section "Gallery Images", It was been beside sections "cover image, logo image..."
Thanks

**Comment by thangvo9x** [comment]
Hi. Please refer this image. 
https://gyazo.com/5e83524d33cab0e8fd94931555d9c45d
Thanks

**Comment by thangvo9x** [comment]
Hi. you can run the plugin https://vi.wordpress.org/plugins/regenerate-thumbnails/
The app default is getting feature image from your website. 
Thanks

**Comment by thangvo9x** [comment]
The app is getting featured image for display front page. We've only use Listing Gallery for display image (single listing). you must edit code if you want to using feature image. you can go to App/Components/Detail/Header/index.js
and edit it. Thanks
