### ISSUE TITLE
[Fluxstore WooCommerce] - Profile Update Not Working

### ISSUE THREAD

**Issue by themeix** [inspireui/support#2230]
Profile Update is not working. There have several bugs on that page.
1. It does not allows me to update page without Password change if there have password field empty. If user logged in by facebook, gmail then password field remains empty and update button is not working without adding password.
2. If i fill up all the information then i am getting the following error. https://i.postimg.cc/wB8P3Zw1/screenshot-625.png
So it totally not working.

Please fix that.

2. Screenshots issues:
https://i.postimg.cc/wB8P3Zw1/screenshot-625.png
3. Proof of my purchased:
https://raw.githubusercontent.com/themeix/temp/master/screenshot-589.png
3. Config files (optional)

**Comment by minhcasi** [comment]
@kvt0012 - pls help for investigating - thank you!

**Comment by kvt0012** [comment]
Please send me your config file,sir 
Thank you

**Comment by themeix** [comment]
I am sending you the config file in skype. 
So this ticket should belong 2 issues.

1. Profile Update feature not working
2. All Paginated products not showing in the Category page.

**Comment by themeix** [comment]
I sent you access to my repository, https://github.com/themeix/bazarfix-app2/

**Comment by kvt0012** [comment]
I'll check it and it works well on our app, so please update on newest version.
Thank you

**Comment by minhtruong315** [comment]
[lib.zip](https://github.com/inspireui/support/files/4274646/lib.zip)
@themeix replace these files to fix update profile

**Comment by themeix** [comment]
Still not working, https://screencast-o-matic.com/watch/cYeecnxenq

**Comment by minhcasi** [comment]
move to #2217 - hi man, please try to raise your all issues to the same ticket, instead of spam on multi one - thank you for your understanding
