### ISSUE TITLE
[my-product] - mstore ReactNative 

### ISSUE THREAD

**Issue by Aashir-334** [inspireui/support#2232]
1. My issue:
IOS CartStack->cartScreen->MyCart: After on  next press the behaviour is next button is hide and still on MyCart Stepper ,
2. Screenshots issues:
![Simulator Screen Shot - iPhone 11 - 2020-02-27 at 16 14 42](https://user-images.githubusercontent.com/37038463/75440182-1bc68300-597d-11ea-9ae3-97b0bb1f1626.png)
![Simulator Screen Shot - iPhone 11 - 2020-02-27 at 16 19 48](https://user-images.githubusercontent.com/37038463/75440184-1d904680-597d-11ea-943b-e93150dc30e5.png)

3. Proof of my purchased:
[55992492-mstore-magento-the-complete-react-native-app-for-magento-2-license.pdf](https://github.com/inspireui/support/files/4261297/55992492-mstore-magento-the-complete-react-native-app-for-magento-2-license.pdf)

**Comment by minhtruong315** [comment]
@Aashir-334 let me check

**Comment by Aashir-334** [comment]
Ok please check it asap because i want to app live today

**Comment by minhtruong315** [comment]
@Aashir-334 I can't reproduce your issue. can u record screen?

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
