### ISSUE TITLE
[Fluxstore Woocommerce] - Search should work from Title and SKU, Tag 

### ISSUE THREAD

**Issue by themeix** [inspireui/support#2233]
Here is a request for that app. Currently, it just working with Title for the search option. But it should work from SKU, Tag also. Coz its very important for local stores where products are popular with local language and english as well.

For example, One product Title is "Onion" which is good for title
But some people said that as "Piyaj" So store owner can be add that in sku 

In depth and accurate search is very important for a store 

So how can i add the SKU in search key? So user can search by sku too

2. Screenshots issues:
N/A
3. Proof of my purchased:
https://raw.githubusercontent.com/themeix/temp/master/screenshot-589.png
3. Config files (optional)
N/A

**Comment by minhcasi** [comment]
sku search is not available - note as a feature request - thank you!

**Comment by minhcasi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [SKU Search](https://trello.com/c/KtgemiU3/22-sku-search)

**Comment by minhcasi** [comment]
move to the backlog for next integration -we may improve the search with the attribute as well
