### ISSUE TITLE
[fluxstore] - error when make login in app

### ISSUE THREAD

**Issue by limitlessfirm** [inspireui/support#2237]
---------

1. My issue:error when make login in app

2. Screenshots issues:
![login](https://user-images.githubusercontent.com/59250639/75483773-30703e80-59b0-11ea-949b-b5777b899a8a.JPG)

3. Proof of my purchased:
![screenshot](https://user-images.githubusercontent.com/59250639/75483801-36661f80-59b0-11ea-8c1a-d735cd73e0bb.JPG)

3. Config files (optional)

**Comment by minhcasi** [comment]
@limitlessfirm - pls go to your google play and copy the SHA key - https://tppr.me/Rj6uc
Then paste to the Firebase to fix this issue - https://tppr.me/xDTz6

This is a common problem that we will also update the video to explain more detail - @kvt0012

**Comment by nelson243** [comment]
> @limitlessfirm - pls go to your google play and copy the SHA key - https://tppr.me/Rj6uc
> Then paste to the Firebase to fix this issue - https://tppr.me/xDTz6
> 
> This is a common problem that we will also update the video to explain more detail - @kvt0012
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/45934f1ff78354503a80ecdff2595c270fa29369/68747470733a2f2f747070722e73332e616d617a6f6e6177732e636f6d2f75706c6f6164732f31663761633064643963613666663565646164626165653535306435396135622e706e67"><img alt="" height="14" src="/favicon-32x32.png"> tppr.me**[Public - Google Chrome_2020-02-28 10-31-12](https://tppr.me/Rj6uc)**
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/47788b18dc18d601e16217d3a0d900f0ba517e9a/68747470733a2f2f747070722e73332e616d617a6f6e6177732e636f6d2f75706c6f6164732f37336661316532393562323763663337323435326463373836313339313462662e706e67"><img alt="" height="14" src="/favicon-32x32.png"> tppr.me**[Public - Google Chrome_2020-02-28 10-32-22](https://tppr.me/xDTz6)**

So to get the Sha key i need to create a developper account first ? I'm having the same issue

**Comment by minhcasi** [comment]
@nelson243 - or you can follow this guide https://www.youtube.com/watch?v=C_9mk_MmvOQ
