### ISSUE TITLE
Fluxstore

### ISSUE THREAD

**Issue by kalakgl** [inspireui/support#2239]
Error on iOS and android: Compiler message: lib/widgets/home/banner/banner_map.dart:44:23: Error: A value of type ‘PermissionStatus’ can’t be assigned to a variable of type ‘bool’. – ‘PermissionStatus’ is from ‘package:location/location.dart’ (’../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/location-2.5.3/lib/location.dart’). _permission = await _locationService.requestPermission();

<img width="1536" alt="Skærmbillede 2020-02-27 kl  20 02 10" src="https://user-images.githubusercontent.com/12363496/75495016-4ecc3f00-599c-11ea-92bc-07a2654d36a7.png">

**Comment by minhcasi** [comment]
Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads  it's used to verify your proof of purchase? sorry for any inconvenience - Thank you!

**Comment by kalakgl** [comment]
![purchase_proof](https://user-images.githubusercontent.com/12363496/75548709-b02bf680-5a0c-11ea-884a-b1cca77b20c5.jpg)

**Comment by minhcasi** [comment]
@kalakgl pls try this script to enable the stable version from flutter, it seems the issue from the library
```
flutter channel stable
flutter upgrade --force
```
Go to ios folder and remove Pods folder, Podfile and Podfile.lock
Then reinstall the project from android studio

**Comment by kalakgl** [comment]
Your solution did not helped.

But this did:
Change line 23: (i believe it was something like: bool _permission = true;) in:
PermissionStatus _permission = PermissionStatus.GRANTED;
and line 46 in:
if (_permission == PermissionStatus.GRANTED) {

**Comment by minhcasi** [comment]
@kalakgl - thank you so much for your sharing 

@philipvu30 - pls help to update to the latest source - thank you!

**Comment by philipvu30** [comment]
Hi @kalakgl ,
Apologies for the delayed response. Would you mind including your common folder and the log of command "flutter doctor -v"? I will help me understand better your problem. Thank you.

**Comment by csu6** [comment]
Hi
I have the same error. So what is the solution please ?

**Comment by Hyla96** [comment]
> Your solution did not helped.
> 
> But this did:
> Change line 23: (i believe it was something like: bool _permission = true;) in:
> PermissionStatus _permission = PermissionStatus.GRANTED;
> and line 46 in:
> if (_permission == PermissionStatus.GRANTED) {

Thi doesn't make any sense to be hones, that boolean operation will always be true.

Change line 23 to:

`_permission = await _locationService.requestPermission() == PermissionStatus.GRANTED ? true : false;`

It will return true if the _localService.requestPermission() returns GRANTED, false otherwise

**Comment by Hyla96** [comment]
@philipvu30 it should be updated in the source code aswell

**Comment by kalakgl** [comment]
Still the same error on the latest package.
Update and deleted the pod folder etc.
XCode made new pod file installation, but it still crash with the same error.

**Comment by philipvu30** [comment]
Hi @kalakgl 

Have you tried to change it to this?

_permission = (await _locationService.requestPermission()) as bool;
