### ISSUE TITLE
cebuilder not working

### ISSUE THREAD

**Issue by maltamap** [inspireui/support#224]
i don't appreciate being used as your tester. my time is valuable. it seems you keep putting out broken software and letting us figure it out. it is very disrespectful. please notify me when things are working properly so i can create an app. If things are working please provide actual instructions on how to use the tool properly.

**Comment by minhcasi** [comment]
Hi what is your issue with the Cebuilder?

We have the video guide on this playlist - https://www.youtube.com/playlist?list=PLcF-HiQy-jOKVI23G0ppKoSaTA-gwCAew - does it help for your installing ?

**Comment by maltamap** [comment]
Instead something opening when i hit run set up, nothing happens.

Here is what is displayed in the terminal.


C:\Users\User1\AppData\Local\Programs\electron-react-boilerplate>cd "C:\Users\Us
er1\Downloads\codecanyon-22645013-listpro-listing-directory-react-native-templat
e (2)\ListPro 1.2.1\Source"

C:\Users\User1\Downloads\codecanyon-22645013-listpro-listing-directory-react-nat
ive-template (2)\ListPro 1.2.1\Source>rmdir /s /q $TMPDIR/react-*
Invalid switch - "react-*".

C:\Users\User1\Downloads\codecanyon-22645013-listpro-listing-directory-react-nat
ive-template (2)\ListPro 1.2.1\Source>rmdir /s /q node_modules
node_modules\REEFFD~1\example\ios\build\Build\INTERM~1\RCTACT~1.BUI\DEBUG-~1\RCT
ACT~1.BUI\STATIC~1\RCTACT~1\RCTACT~1\normal\x86_64\RCTActionSheetManager.plist -
 The file name is too long.
node_modules\REEFFD~1\example\ios\build\Build\INTERM~1\RCTGEO~1.BUI\DEBUG-~1\RCT
GEO~1.BUI\STATIC~1\RCTGEO~1\RCTGEO~1\normal\x86_64\RCTLocationObserver.plist - T
he file name is too long.
node_modules\REEFFD~1\example\ios\build\Build\INTERM~1\RCTIMA~1.BUI\DEBUG-~1\RCT
IMA~1.BUI\STATIC~1\RCTImage\RCTImage\normal\x86_64\RCTGIFImageDecoder.plist - Th
e file name is too long.
node_modules\REEFFD~1\example\ios\build\Build\INTERM~1\RCTIMA~1.BUI\DEBUG-~1\RCT
IMA~1.BUI\STATIC~1\RCTImage\RCTImage\normal\x86_64\RCTImageBlurUtils.plist - The
 file name is too long.
node_modules\REEFFD~1\example\ios\build\Build\INTERM~1\RCTIMA~1.BUI\DEBUG-~1\RCT
IMA~1.BUI\STATIC~1\RCTImage\RCTImage\normal\x86_64\RCTImageCache.plist - The fil
e name is too long.
node_modules\REEFFD~1\example\ios\build\Build\INTERM~1\RCTIMA~1.BUI\DEBUG-~1\RCT
IMA~1.BUI\STATIC~1\RCTImage\RCTImage\normal\x86_64\RCTImageEditingManager.plist
- The file name is too long.
node_modules\REEFFD~1\example\ios\build\Build\INTERM~1\RCTIMA~1.BUI\DEBUG-~1\RCT
IMA~1.BUI\STATIC~1\RCTImage\RCTImage\normal\x86_64\RCTImageLoader.plist - The fi
le name is too long.
node_modules\REEFFD~1\example\ios\build\Build\INTERM~1\RCTIMA~1.BUI\DEBUG-~1\RCT
IMA~1.BUI\STATIC~1\RCTImage\RCTImage\normal\x86_64\RCTImageStoreManager.plist -
The file name is too long.
node_modules\REEFFD~1\example\ios\build\Build\INTERM~1\RCTIMA~1.BUI\DEBUG-~1\RCT
IMA~1.BUI\STATIC~1\RCTImage\RCTImage\normal\x86_64\RCTImageUtils.plist - The fil
e name is too long.
node_modules\REEFFD~1\example\ios\build\Build\INTERM~1\RCTIMA~1.BUI\DEBUG-~1\RCT
IMA~1.BUI\STATIC~1\RCTImage\RCTImage\normal\x86_64\RCTImageView.plist - The file
 name is too long.
node_modules\REEFFD~1\example\ios\build\Build\INTERM~1\RCTIMA~1.BUI\DEBUG-~1\RCT
IMA~1.BUI\STATIC~1\RCTImage\RCTImage\normal\x86_64\RCTImageViewManager.plist - T
he file name is too long.
node_modules\REEFFD~1\example\ios\build\Build\INTERM~1\RCTIMA~1.BUI\DEBUG-~1\RCT
IMA~1.BUI\STATIC~1\RCTImage\RCTImage\normal\x86_64\RCTLocalAssetImageLoader.plis
t - The file name is too long.
node_modules\REEFFD~1\example\ios\build\Build\INTERM~1\RCTIMA~1.BUI\DEBUG-~1\RCT
IMA~1.BUI\STATIC~1\RCTImage\RCTImage\normal\x86_64\RCTResizeMode.plist - The fil
e name is too long.
node_modules\REEFFD~1\example\ios\build\Build\INTERM~1\RCTNET~1.BUI\DEBUG-~1\RCT
NET~1.BUI\STATIC~1\RCTNET~1\RCTNET~1\normal\x86_64\RCTDataRequestHandler.plist -
 The file name is too long.
node_modules\REEFFD~1\example\ios\build\Build\INTERM~1\RCTNET~1.BUI\DEBUG-~1\RCT
NET~1.BUI\STATIC~1\RCTNET~1\RCTNET~1\normal\x86_64\RCTFileRequestHandler.plist -
 The file name is too long.
node_modules\REEFFD~1\example\ios\build\Build\INTERM~1\RCTNET~1.BUI\DEBUG-~1\RCT
NET~1.BUI\STATIC~1\RCTNET~1\RCTNET~1\normal\x86_64\RCTHTTPRequestHandler.plist -
 The file name is too long.
node_modules\REEFFD~1\example\ios\build\Build\INTERM~1\RCTNET~1.BUI\DEBUG-~1\RCT
NET~1.BUI\STATIC~1\RCTNET~1\RCTNET~1\normal\x86_64\RCTNetInfo.plist - The file n
ame is too long.
node_modules\REEFFD~1\example\ios\build\Build\INTERM~1\RCTNET~1.BUI\DEBUG-~1\RCT
NET~1.BUI\STATIC~1\RCTNET~1\RCTNET~1\normal\x86_64\RCTNetworking.plist - The fil
e name is too long.
node_modules\REEFFD~1\example\ios\build\Build\INTERM~1\RCTNET~1.BUI\DEBUG-~1\RCT
NET~1.BUI\STATIC~1\RCTNET~1\RCTNET~1\normal\x86_64\RCTNetworkTask.plist - The fi
le name is too long.
node_modules\REEFFD~1\example\ios\build\Build\INTERM~1\RCTVIB~1.BUI\DEBUG-~1\RCT
VIB~1.BUI\STATIC~1\RCTVIB~1\RCTVIB~1\normal\x86_64\RCTVibration.plist - The file
 name is too long.

C:\Users\User1\Downloads\codecanyon-22645013-listpro-listing-directory-react-nat
ive-template (2)\ListPro 1.2.1\Source>del package-lock.json
Could Not Find C:\Users\User1\Downloads\codecanyon-22645013-listpro-listing-dire
ctory-react-native-template (2)\ListPro 1.2.1\Source\package-lock.json

C:\Users\User1\Downloads\codecanyon-22645013-listpro-listing-directory-react-nat
ive-template (2)\ListPro 1.2.1\Source>del yarn-error.log
Could Not Find C:\Users\User1\Downloads\codecanyon-22645013-listpro-listing-dire
ctory-react-native-template (2)\ListPro 1.2.1\Source\yarn-error.log

C:\Users\User1\Downloads\codecanyon-22645013-listpro-listing-directory-react-nat
ive-template (2)\ListPro 1.2.1\Source>yarn
yarn install v1.13.0
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.7: The platform "win32" is incompatible with this module.
info "fsevents@1.2.7" is an optional dependency and failed compatibility check.
Excluding it from installation.
[3/4] Linking dependencies...
warning "api-ecommerce > firebase > @firebase/database@0.3.11" has unmet peer de
pendency "@firebase/app-types@0.x".
warning "api-ecommerce > firebase > @firebase/firestore@1.0.1" has unmet peer de
pendency "@firebase/app-types@0.x".
warning "api-ecommerce > firebase > @firebase/functions@0.3.6" has unmet peer de
pendency "@firebase/app-types@0.x".
warning "api-ecommerce > firebase > @firebase/messaging@0.3.10" has unmet peer d
ependency "@firebase/app-types@0.x".
warning "api-ecommerce > firebase > @firebase/storage@0.2.7" has unmet peer depe
ndency "@firebase/app-types@0.x".
warning "api-ecommerce > firebase > @firebase/auth > @firebase/auth-types@0.5.1"
 has unmet peer dependency "@firebase/app-types@0.x".
warning "api-ecommerce > firebase > @firebase/auth > @firebase/auth-types@0.5.1"
 has unmet peer dependency "@firebase/util@0.x".
warning "api-ecommerce > firebase > @firebase/database > @firebase/database-type
s@0.3.4" has unmet peer dependency "@firebase/app-types@0.x".
warning "api-ecommerce > firebase > @firebase/firestore > @firebase/firestore-ty
pes@1.0.1" has unmet peer dependency "@firebase/app-types@0.x".
warning "api-ecommerce > firebase > @firebase/functions > @firebase/messaging-ty
pes@0.2.4" has unmet peer dependency "@firebase/app-types@0.x".
warning "api-ecommerce > firebase > @firebase/storage > @firebase/storage-types@
0.2.4" has unmet peer dependency "@firebase/app-types@0.x".
warning "api-ecommerce > firebase > @firebase/storage > @firebase/storage-types@
0.2.4" has unmet peer dependency "@firebase/util@0.x".
warning "expo > expo-background-fetch@1.0.0" has unmet peer dependency "expo-tas
k-manager-interface@~1.0.0".
warning "expo > expo-constants@2.0.1" has incorrect peer dependency "expo@~32.0.
1".
warning "expo > expo-google-sign-in@2.0.0" has incorrect peer dependency "react-
native@^0.55.4".
warning "expo > expo-location@2.0.1" has unmet peer dependency "expo-task-manage
r-interface@~1.0.0".
warning "expo > react-native-reanimated@1.0.0-alpha.11" has incorrect peer depen
dency "react@16.0.0-alpha.6".
warning "expo > react-native-reanimated@1.0.0-alpha.11" has incorrect peer depen
dency "react-native@^0.44.1".
warning "expo > expo-asset > url-loader@1.1.2" has unmet peer dependency "webpac
k@^3.0.0 || ^4.0.0".
warning "firebase > @firebase/database@0.3.9" has unmet peer dependency "@fireba
se/app-types@0.x".
warning "firebase > @firebase/firestore@0.9.3" has unmet peer dependency "@fireb
ase/app-types@0.x".
warning "firebase > @firebase/functions@0.3.4" has unmet peer dependency "@fireb
ase/app-types@0.x".
warning "firebase > @firebase/messaging@0.3.8" has unmet peer dependency "@fireb
ase/app-types@0.x".
warning "firebase > @firebase/storage@0.2.5" has unmet peer dependency "@firebas
e/app-types@0.x".
warning "firebase > @firebase/auth > @firebase/auth-types@0.5.0" has unmet peer
dependency "@firebase/app-types@0.x".
warning "firebase > @firebase/database > @firebase/database-types@0.3.2" has unm
et peer dependency "@firebase/app-types@0.x".
warning "firebase > @firebase/firestore > @firebase/firestore-types@0.8.0" has u
nmet peer dependency "@firebase/app-types@0.x".
warning "firebase > @firebase/functions > @firebase/messaging-types@0.2.3" has u
nmet peer dependency "@firebase/app-types@0.x".
warning "firebase > @firebase/storage > @firebase/storage-types@0.2.3" has unmet
 peer dependency "@firebase/app-types@0.x".
warning " > react-native@0.57.1" has incorrect peer dependency "react@16.5.0".
warning " > react-native-dates@2.0.4" has incorrect peer dependency "react@^15.3
.2".
warning " > react-native-dates@2.0.4" has incorrect peer dependency "react-nativ
e@^0.35.0".
warning "react-navigation > react-navigation-drawer@1.0.5" has unmet peer depend
ency "react-native-gesture-handler@^1.0.0".
warning "react-navigation > react-navigation-drawer@1.0.5" has unmet peer depend
ency "react-native-screens@^1.0.0 || ^1.0.0-alpha".
warning "react-navigation > react-navigation-stack@1.0.6" has unmet peer depende
ncy "react-native-gesture-handler@^1.0.0".
warning "react-navigation > react-navigation-stack@1.0.6" has unmet peer depende
ncy "react-native-screens@^1.0.0 || ^1.0.0-alpha".
warning "react-navigation > react-navigation-tabs@1.0.2" has unmet peer dependen
cy "react-native-screens@^1.0.0 || ^1.0.0-alpha".
warning " > babel-jest@23.6.0" has unmet peer dependency "babel-core@^6.0.0 || ^
7.0.0-0".
[4/4] Building fresh packages...
Done in 123.78s.

C:\Users\User1\Downloads\codecanyon-22645013-listpro-listing-directory-react-nat
ive-template (2)\ListPro 1.2.1\Source>
