### ISSUE TITLE
STEP 2 - No plugins are installed

### ISSUE THREAD

**Issue by yuvalarviv1122** [inspireui/support#2240]
Hey, I'm trying to build the app using the Cebuilder but on Step 2 its says I have only "Powershell" Install and all others are not.
Please help me so I can make the app working.

**Comment by minhcasi** [comment]
Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads  it's used to verify your proof of purchase? sorry for any inconvenience - Thank you!
