### ISSUE TITLE
[FluxStore 1.6.4] - Blog Not Working, White Screen Before Splash Page & Language Switching Issue - New Version Issues

### ISSUE THREAD

**Issue by siyashamsudeen** [inspireui/support#2242]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:

All these issues mentioning now are new issues that has come in the new version 1.6.4. these issues were not seen in the previous versions . im attaching two screen record videos to show Previous version & New Version Differences and issues.

Previous Version:

https://drive.google.com/file/d/1Q4WIA2XspOHGiyIPS-euFUXIXzcqfqIt/view?usp=sharing

New Version Version
https://drive.google.com/file/d/1XWxAUK72wgMk5qm4rP4wPE5swK3_4Svt/view?usp=sharing

On Skype im still waiting for response and get a solution . please help .

i sent screen record video , source code in email and Anydesk access . please help to fix .

**A . White screen before the splash page is too long .**

**B. After Language Change Category Page is not loading in Arabic**

The below screenshot is after language change . but in previous version this was working perfectly. 

Please help to fix this asap

![image](https://user-images.githubusercontent.com/57159602/75537993-525dd580-5a31-11ea-97f5-ea39b8584b20.png)

**C. Blog show empty screen - if you swipe down and refresh then blog items appears.**

![image](https://user-images.githubusercontent.com/57159602/75537506-b2a04780-5a30-11ea-8bcd-a6db3b3c0223.png)

![image](https://user-images.githubusercontent.com/57159602/75537419-8f759800-5a30-11ea-8816-1bc3f1ce1938.png)

**D. if you click any where on the empty blog screen then the error screen comes**

2. Screenshots issues:

3. Proof of my purchased:

![image](https://user-images.githubusercontent.com/57159602/75538071-7ae5cf80-5a31-11ea-9a30-fcc17a42f60a.png)

3. Config files (optional)

**Comment by minhtruong315** [comment]
@siyashamsudeen 
A . White screen before the splash page is too long .
I can't reproduce your issue. I see it's working fast. You can see below video
[splashscreen.mov.zip](https://github.com/inspireui/support/files/4267261/splashscreen.mov.zip)

B. After Language Change Category Page is not loading in Arabic
You can open models/app.dart file, find loadAppConfig function. and change
```String path = "lib/common/config_$locale.json";```
to
```String path = "lib/config/config_$locale.json";```

C. Blog show empty screen - if you swipe down and refresh then blog items appears.
D. if you click any where on the empty blog screen then the error screen comes
You can replace these files: widgets/blog/blog_list_view.dart and widgets/blog/blog_view.dart
[Archive.zip](https://github.com/inspireui/support/files/4267278/Archive.zip)

**Comment by siyashamsudeen** [comment]
B: Regarding the category not loading in Arabic - already the string path is correctly configured to the config folder . it is already this `String path = "lib/config/config_$locale.json";`

<img width="519" alt="Screen Shot 2020-02-29 at 4 56 13 AM" src="https://user-images.githubusercontent.com/57159602/75598120-f5a2ff00-5ab2-11ea-83e7-df726ea178bb.png">


the home screen is correct but the category page is not loading in Arabic rest everything is fine . 
the previous version did not have this issue . 

<img width="368" alt="Screen Shot 2020-02-29 at 5 17 16 AM" src="https://user-images.githubusercontent.com/57159602/75598117-f045b480-5ab2-11ea-8ec2-bc41d21bb884.png">


If you close the app and open again then it loads in Arabic . Its something related to caching or feels like that . when the app restarts only category screen changes its langauge otherwise it doesn't change .

C: Blog - now automatically refreshes when clicked on blog button and it appears resolve the issue but to notify you , in the previous version even that was not there . as you click the blog , blog items used to appear without the need of refresh or any loading time . 

Please helpt to fix this asap

**Comment by minhtruong315** [comment]
@siyashamsudeen send me models/app.dart file

**Comment by siyashamsudeen** [comment]
Please find the modes/app.dart here
[app.dart.zip](https://github.com/inspireui/support/files/4269774/app.dart.zip)

**Comment by minhtruong315** [comment]
```
 Future<bool> changeLanguage(String country, BuildContext context) async {
    try {
      SharedPreferences prefs = await SharedPreferences.getInstance();
      locale = country;
      await Provider.of<CategoryModel>(context, listen: false).getCategories(lang: country);
      await prefs.setString("language", country);
      await loadAppConfig();
      notifyListeners();
      return true;
    } catch (err) {
      return false;
    }
  }
```
replace this function in models/app.dart to fix category

**Comment by minhtruong315** [comment]
```
Future<List<Blog>> _getBlogs() async {
    List<Blog> blogs = [];
    var _jsons = await Blog.getBlogs(url: serverConfig['blog'] ?? serverConfig['url'], page: _page);
    for (var item in _jsons) {
      blogs.add(Blog.fromJson(item));
    }
    if (blogs.isNotEmpty) {
      Provider.of<BlogModel>(context, listen: false).addBlogs(blogs);
    }
    return blogs;
  }
```
replace this function in widgets/blog/blog_list_view.dart
to fix blog

**Comment by siyashamsudeen** [comment]
After replacing the code for Category - category loads in arabic but language switching is not instant . it takes few seconds to update the language . 

In the previous version language switching or changing happens instantly and category page had no issues . please see the screen record video i shared of the previous version . 

In this version when category page is fixed language switching is not instant.  and when language switching is instant then category screen is not loading in arabic unless app is restarted. 

For Blog fix you provided im getting error in code :

<img width="547" alt="Screen Shot 2020-02-29 at 5 34 31 AM" src="https://user-images.githubusercontent.com/57159602/75598607-77e0f280-5ab6-11ea-84fc-14abf722bda3.png">

**Comment by minhtruong315** [comment]
import this to widgets/blog/blog_list_view.dart
import 'package:provider/provider.dart';

about category, u must wait to get category by language.

**Comment by siyashamsudeen** [comment]
About category - why is it not possible to make like how it was in the previous version where language changes instantly every screen . even category page it was changing instantly in the previous version but why it is not possible in this version . 

Blog- that doesn't make any change - the first time blog opens it first shows refreshing and then the blog items appears. but in previous version it used to come instantly .

**Comment by minhtruong315** [comment]
change this function in models/app.dart
```
Future<bool> changeLanguage(String country, BuildContext context) async {
    try {
      SharedPreferences prefs = await SharedPreferences.getInstance();
      locale = country;
      await prefs.setString("language", country);
      await loadAppConfig();
      notifyListeners();
      await Provider.of<CategoryModel>(context, listen: false).getCategories(lang: country);
      return true;
    } catch (err) {
      return false;
    }
  }
```
replace models/blog.dart
[blog.dart.zip](https://github.com/inspireui/support/files/4270007/blog.dart.zip)
