### ISSUE TITLE
Fluxstore Pro - Flutter E-commerce Full App

### ISSUE THREAD

**Issue by ranapiyush1986** [inspireui/support#2243]
> - 1- how to make home page slider dynamic and manage using wp rest api
> - 2- below banner images , can we make that section customizable like increase or decrease number of banners as per our usage
> - 3- if we take your latest update , is our customization flush out ? if yes then whats the best way to do this without losing our customized code.
> - 4- can we customize Login module as per need or is there any built-in feature .
we just needed login module like .. Enter Mobile number then check if user already register ask for password , if not then ask for name,email ,password then submit and OTP verification and create account. can you help me in this way.
![Screenshot_5](https://user-images.githubusercontent.com/18486814/75575075-777c3380-5a85-11ea-9d5e-824a671df4ea.png)

**Comment by minhcasi** [comment]
@ranapiyush1986 - sorry for the late response 

1- 2 - pls refer more the config on this guide https://docs.inspireui.com/fluxstore/home-layout/#banner-slider-image + you can use this guide to upload the conifg.json to the mstore-api to update the app dynamically - https://docs.inspireui.com/fluxstore/performance/#1-caching-to-improve-app-performance

3- we recommend to change the config from the common folder, if you have customized other files like widget / screens, then make sure backup these files to override for next upgrade

4- you can use the Inspector to customize any UI from the app - https://docs.inspireui.com/fluxstore/useful-tip/#how-to-change-the-ui-quickly

**Comment by ranapiyush1986** [comment]
Plz click on this API : 
https://bit.ly/3cy4AAf

I am not able to find this api in mstore. But it's used in flutter app - WordPress 
Issue : update profile not working.
