### ISSUE TITLE
[Fluxstore 1.6.3] - Do not ship to country 

### ISSUE THREAD

**Issue by ramzwatcher** [inspireui/support#2244]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: 

a) Shipping to country not working

b) We are using snippets to customize shipping fee based on orders size
that will auto select users shipping: 
$300 would be free shipping, 
$100 - $300  will be $8 
Below $100 will be $10
Current code as attached. 

2. Screenshots issues: 
https://drive.google.com/open?id=108jL4i_3Cvn64xFEdJnQsChMyZpNjQai
https://drive.google.com/open?id=1nI5synoS546ewohv8w4Eri5bjIvxYlgf

3. Proof of my purchased:
https://drive.google.com/open?id=1MZWhZaQTZpr1PtIdkM-q8i0T_5lr5ub1

3. Config files (optional):

Flutter country config:
https://drive.google.com/open?id=1zxsdEG_GHrSyd9-YIwfQeI64joxBJ_RU

Shipping snippets:
https://drive.google.com/open?id=1BBJBIgVpIgXmpQlOGLCQe-TQSjW_5pf6

Thanks!

**Comment by kvt0012** [comment]
I think that issue is on your woocomerce setting. Please check that

**Comment by kvt0012** [comment]
You can access to woocomerce --> setting --> shipping and edit it.
