### ISSUE TITLE
[MStore Pro] - cannot run android

### ISSUE THREAD

**Issue by 007asom** [inspireui/support#2245]
hello
I download the last version 3.9.8 and face this problem:

after run npm install and use react-native run-android

```
react-native : The term 'react-native' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ react-native run-android
+ ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (react-native:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

when open it on android studio: 
`Compilation is not supported for following modules: @react-native-community_netinfo, android-@react-native-community_netinfo, android-@react-native-community_viewpager, @react-native-community_viewpager, android-@react-native-community_async-storage, @react-native-firebase_auth, @react-native-firebase_app, @react-native-community_async-storage, android-react-native-admob, android-@react-native-firebase_auth, android-@react-native-firebase_app, android-react-native-community_async-storage, android-react-native-apple-authentication, android-react-native-facebook-account-kit, android-react-native-linear-gradient, android-react-native-fbsdk, android-react-native-localization, android-react-native-gesture-handler, android-react-native-onesignal, android-react-native-reanimated, android-react-native-screens, android-react-native-restart, android-react-native-vector-icons, android-react-native-webview, react-native-admob-android-react-native-admob, react-native-admob, react-native-apple-authentication, react-native-apple-authentication-android-react-native-apple-authentication, react-native-community_async-storage, react-native-community_netinfo, react-native-community_viewpager, react-native-facebook-account-kit, react-native-fbsdk, react-native-facebook-account-kit-android-react-native-facebook-account-kit, react-native-fbsdk-android-react-native-fbsdk, react-native-firebase_app, react-native-firebase_auth, react-native-gesture-handler, react-native-gesture-handler-android-react-native-gesture-handler, react-native-localization-android-react-native-localization, react-native-linear-gradient-android-react-native-linear-gradient, react-native-linear-gradient, react-native-localization, react-native-onesignal, react-native-onesignal-android-react-native-onesignal, react-native-reanimated, react-native-reanimated-android-react-native-reanimated, react-native-restart, react-native-restart-android-react-native-restart, react-native-screens, react-native-vector-icons-android-react-native-vector-icons, react-native-screens-android-react-native-screens, react-native-vector-icons, react-native-webview-android-react-native-webview, react-native-webview. Unfortunately you can't have non-Gradle Java modules and Android-Gradle modules in one project.`

I update the tools and android studio too

https://ibb.co/CK8ht0j

2. Screenshots issues:

3. Proof of my purchased:
https://ibb.co/PNBWpYy

3. Config files (optional)
config and appConfig are the original files.

**Comment by luyx2412** [comment]
Hi @007asom Please follow the ticket to fix your issue.

Thanks

**Comment by 007asom** [comment]
thanks for responding.
waiting for your reply

> Hi @007asom Please follow the ticket to fix your issue.
> 
> Thanks

**Comment by luyx2412** [comment]
Hi @007asom Sorry my mistake, this is the ticket to fix your issue https://github.com/facebook/react-native/issues/9342

Thanks

**Comment by 007asom** [comment]
> Hi @007asom Sorry my mistake, this is the ticket to fix your issue [facebook/react-native#9342](https://github.com/facebook/react-native/issues/9342)
> 
> Thanks

thank you again. it works and installs the apk file, but the js file not loading, it loads the splash screen only. I run npm install again with same issue.

**Comment by luyx2412** [comment]
HI @007asom can you switch to `yarn` to install easier?

Thanks

**Comment by 007asom** [comment]
> HI @007asom can you switch to `yarn` to install easier?
> 
> Thanks

thank you
it works with yarn.
