### ISSUE TITLE
FluxStorePro - Insert Data Issue

### ISSUE THREAD

**Issue by saidbakkou** [inspireui/support#2246]
Hello ,
   i have a problem with inserting data (signin & signup) i find that it s registered in my database and on a JsonFile  too.. my question is where can i find this file on the code and how to disable it so i can work with my database only !
    thank u in advance 
![86183753_197529808291854_4776660982191620096_n](https://user-images.githubusercontent.com/59389664/75606688-a3340380-5aef-11ea-8a84-47057aca53d2.jpg)

**Comment by minhcasi** [comment]
@saidbakkou - you can try to use the Inspector to change the UI - https://docs.inspireui.com/fluxstore/useful-tip/#how-to-change-the-ui-quickly

the API could be changed from the services folder, and logic data should be changed from model folder.
