### ISSUE TITLE
Unable to install all plugins on cebuilder

### ISSUE THREAD

**Issue by Donbuffy** [inspireui/support#2247]
Hello, purchased the beonews script of codecayon, since i made the purchase i haven't been able to use it cos my cebuilder doesn't have all the required plugins and i dunno how to go about it, i have tried using powershell to install yarn but i can't seem to find how to fix the expo, i need assistance asap. see screenshot for more info. 
![Cebuilder snip](https://user-images.githubusercontent.com/61636442/75615654-ee2d3580-5b46-11ea-842e-b8f68535f293.png)

**Comment by minhcasi** [comment]
@Donbuffy - could you help to try to expo install via this guide - https://docs.expo.io/versions/latest/get-started/installation/ - thank you!
