### ISSUE TITLE
Issue with Checkout & Blog

### ISSUE THREAD

**Issue by equationsinc** [inspireui/support#2248]
Hi,

We are having issues with the checkout, and the blog. How can we contact you directly? Email would be much more preferable or chat.

The blog issue is similar to case #2234 - "Blog list are showing, But when i open any blog it shows red page with errors."

Can I send all my files to your email vinhkhiemt135@gmail.com

Waiting

@minhcasi @kvt0012

**Comment by minhcasi** [comment]
Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads  it's used to verify your proof of purchase? sorry for any inconvenience 

Please send to the email to both support@inspireui.com and  vinhkhiemt135@gmail.com - thank you!

- Thank you!

**Comment by equationsinc** [comment]
Hi,

Attached is the screenshot.

Please use this email to contact me henceforth and not github.

I need immediate response to this issues, as I bought 2 templates, and I am working on 5 projects now.

I would be glad to forward you one of the 5 projects, so that you solve the blog and Paypal issue, as the 5 projects all have the same issues.

Finally, apart from Paypal issue, I also have issues with other payment mediums, i.e, none of my payment mediums are working, regardless of the fact that they are working perfectly well on my website.


I really need an URGENT response to this, and I would not mind paying extra just to have you completely resolve all my issues 100% perfectly and very QUICKLY.
Waiting.


Thanks.
Henry Skull
CEO

Equations INC

**Comment by equationsinc** [comment]
> Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads it's used to verify your proof of purchase? sorry for any inconvenience
> 
> Please send to the email to both [support@inspireui.com](mailto:support@inspireui.com) and [vinhkhiemt135@gmail.com](mailto:vinhkhiemt135@gmail.com) - thank you!
> 
> * Thank you!
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/c5a18223816825ebf6c0fec648742882ecbb6a7b/68747470733a2f2f6173736574732e73686f7066726f6e742e656e7661746f2d7374617469632e636f6d2f696d616765732f6d6574612f6c6f676f732f636f646563616e796f6e2e706e67"><img alt="" height="14" src="https://camo.githubusercontent.com/c75d968dba11187d74e09644791494a4418ce2d8/68747470733a2f2f6173736574732e73686f7066726f6e742e656e7661746f2d7374617469632e636f6d2f69636f6e732f636f646563616e796f6e2e6e65742f66617669636f6e2e69636f"> CodeCanyon**[Buy Plugins & Code from CodeCanyon](https://codecanyon.net/)**Discover 32,445 Plugins, Code and Script for Bootstrap, Javascript, PHP, Wordpress, HTML5 and more. Save time, buy Code on CodeCanyon!

Sent to your emails. Please confirm via email, and continue all future correspondences via email.

Thanks
