### ISSUE TITLE
[MStore MV] Product variant

### ISSUE THREAD

**Issue by minhcasi** [inspireui/support#225]
Check the issue from - https://codecanyon.net/item/mstore-multi-vendor-complete-react-native-template-for-ecommerce/22278924/comments?page=11&filter=all#comment_21327797

**Comment by thangvo9x** [comment]
Hi. I checked your issue. you can fix by go to src/containers/Detail/index.js
go to line 81 , uncomment this.getProductAttribute(this.props.product);
it'll work. Thanks 
![sandisk](https://user-images.githubusercontent.com/23457178/51957527-9709ec80-247e-11e9-87a5-e8161b14ea7b.png)
