### ISSUE TITLE
[fluxstore-woocommerce] - 

### ISSUE THREAD

**Issue by khaledsalama32** [inspireui/support#2250]
[android.zip](https://github.com/inspireui/support/files/4271744/android.zip)
---------

1. My issue:
There is no connection between my site and the application
I have done everything required of me and the application is running and the default products demo appears but when I change the links from the config file it does not show the sections and products that are on my site woordpress -woocommerce 
note:  Categories and products are not visible in the application.
In the attachments there are Android files and a lib folder. Please check and modify them so that the application works well with me. Thank you

2. Screenshots issues:
![Screenshot_٢٠٢٠٠٣٠١-١٤٤٧٤٥](https://user-images.githubusercontent.com/61389531/75625320-262b8b80-5bce-11ea-93d7-a3da6c3599e0.png)
![2020-03-01](https://user-images.githubusercontent.com/61389531/75625325-2c216c80-5bce-11ea-85ba-cad443346660.png)

3. Proof of my purchased:
9e83ec40-8414-4b23-960d-0b69d207dd89
3. Config files (optional)

const serverConfig = {
  "type": "woo",
  "url": "http://khaledalsalama.com/",
  "consumerKey": "ck_2e1164fe3f4d623b3b1c33b7a085a30f20d61525",
  "consumerSecret": "ck_2e1164fe3f4d623b3b1c33b7a085a30f20d61525",
  "blog": "http://khaledalsalama.com/",
  "forgetPassword": "http://khaledalsalama.com/wp-login.php?action=lostpassword"
};

const afterShip = {
  "api": "e2e9bae8-ee39-46a9-a084-781d0139274f",
  "tracking_url": "https://fluxstore.aftership.com"
};

**Comment by khaledsalama32** [comment]
Please answer me .

**Comment by khaledsalama32** [comment]
please tel me what  i have to do !!

**Comment by khaledsalama32** [comment]
Pls said  what have i do ??

**Comment by whitejello** [comment]
yup it happen to me also when first compile the apps. after the second compile will be back to normal. anyone know how to solve this?

**Comment by kvt0012** [comment]
Do you follow all our instruction here ? 
https://docs.inspireui.com/fluxstore
Thank you

**Comment by khaledsalama32** [comment]
yes i do all instruction .   I got very tired

**Comment by khaledsalama32** [comment]
@minhcasi
I am very tired of this problem

**Comment by khaledsalama32** [comment]
> 
> 
> Do you follow all our instruction here ?
> https://docs.inspireui.com/fluxstore
> Thank you
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/abde6bed5239ae865239febe2feb2d96ddc2b838/687474703a2f2f646f63732e696e737069726575692e636f6d2f696d616765732f6d6574612f47686f73742d446f63732e6a7067">InspireUI Document**[FluxStore - Universal mobile commerce Flutter app for Magento, WooCommerce and Opencart](http://docs.inspireui.com/fluxstore/)**Fluxstore is universal app that fully integration with the Woocommerce, Mangeto and Opencart

yes i Do all instruction ,  I am very tired of this problem

**Comment by kvt0012** [comment]
Please follow all of it. 
https://docs.inspireui.com/fluxstore/config/
I see that our app cannot request to your server throughout api.

**Comment by kvt0012** [comment]
> yup it happen to me also when first compile the apps. after the second compile will be back to normal. anyone know how to solve this?

You should use terminal command 
flutter clean 
and rebuild your app, thank you

**Comment by khaledsalama32** [comment]
const serverConfig = {
"type": "woo",
"url": "http://khaledalsalama.com/",
"consumerKey": "ck_2e1164fe3f4d623b3b1c33b7a085a30f20d61525",
"consumerSecret": "ck_2e1164fe3f4d623b3b1c33b7a085a30f20d61525",
"blog": "http://khaledalsalama.com/",
"forgetPassword": "http://khaledalsalama.com/wp-login.php?action=lostpassword"
};
--------------

Set up const serverConfig you did correctly
I will make other settings later
Now I just want to make an app link with woocommerce only
And if the connection is made between them. I will change other settings
What concerns me now is to make a link between the application andwoocommerce only
* Do I have to change all that is in the file of config ... in order to contact ...
?

**Comment by kvt0012** [comment]
Did you edit file config_en.json ?

**Comment by kvt0012** [comment]
and remember to edit woocomerce api 
https://docs.inspireui.com/fluxstore/woocommerce-setup/ 
thank you

**Comment by khaledsalama32** [comment]
> 
> 
> Did you edit file config_en.json ?

ehs

> 
> 
> Did you edit file config_en.json ?

Why am I editing this file?
I don't need to modify it now
I just want to make sure that products and sections appear inside the app
And when I'm sure of that. I will edit a file config_en.json

**Comment by khaledsalama32** [comment]
> 
> 
> and remember to edit woocomerce api
> https://docs.inspireui.com/fluxstore/woocommerce-setup/
> thank you
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/abde6bed5239ae865239febe2feb2d96ddc2b838/687474703a2f2f646f63732e696e737069726575692e636f6d2f696d616765732f6d6574612f47686f73742d446f63732e6a7067">InspireUI Document**[FluxStore - Universal mobile commerce Flutter app for Magento, WooCommerce and Opencart](http://docs.inspireui.com/fluxstore/woocommerce-setup/)**Fluxstore is universal app that fully integration with the Woocommerce, Mangeto and Opencart

The package that I have is 	
Fluxstore Flutter e-commerce mobile app full ) 
Not
teacher, my problem in woowcommerce link to fluxstore app
I did all the required steps and did not work with me

**Comment by kvt0012** [comment]
> > and remember to edit woocomerce api
> > https://docs.inspireui.com/fluxstore/woocommerce-setup/
> > thank you
> > > <img alt="" width="48" src="https://camo.githubusercontent.com/abde6bed5239ae865239febe2feb2d96ddc2b838/687474703a2f2f646f63732e696e737069726575692e636f6d2f696d616765732f6d6574612f47686f73742d446f63732e6a7067">InspireUI Document**[FluxStore - Universal mobile commerce Flutter app for Magento, WooCommerce and Opencart](http://docs.inspireui.com/fluxstore/woocommerce-setup/)**Fluxstore is universal app that fully integration with the Woocommerce, Mangeto and Opencart
> 
> The package that I have is
> Fluxstore Flutter e-commerce mobile app full )
> Not
> teacher, my problem in woowcommerce link to fluxstore app
> I did all the required steps and did not work with me
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/abde6bed5239ae865239febe2feb2d96ddc2b838/687474703a2f2f646f63732e696e737069726575692e636f6d2f696d616765732f6d6574612f47686f73742d446f63732e6a7067">InspireUI Document**[FluxStore - Universal mobile commerce Flutter app for Magento, WooCommerce and Opencart](http://docs.inspireui.com/fluxstore/woocommerce-setup/)**Fluxstore is universal app that fully integration with the Woocommerce, Mangeto and Opencart

Ok, so please edit your woocomerce api 
https://docs.inspireui.com/fluxstore/woocommerce-setup/
Thank you

**Comment by khaledsalama32** [comment]
please  send to me  mstore-api  

i can not download from website

**Comment by khaledsalama32** [comment]
> 
> 
> > > and remember to edit woocomerce api
> > > https://docs.inspireui.com/fluxstore/woocommerce-setup/
> > > thank you
> > > > <img alt="" width="48" src="https://camo.githubusercontent.com/abde6bed5239ae865239febe2feb2d96ddc2b838/687474703a2f2f646f63732e696e737069726575692e636f6d2f696d616765732f6d6574612f47686f73742d446f63732e6a7067">InspireUI Document**[FluxStore - Universal mobile commerce Flutter app for Magento, WooCommerce and Opencart](http://docs.inspireui.com/fluxstore/woocommerce-setup/)**Fluxstore is universal app that fully integration with the Woocommerce, Mangeto and Opencart
> > 
> > 
> > The package that I have is
> > Fluxstore Flutter e-commerce mobile app full )
> > Not
> > teacher, my problem in woowcommerce link to fluxstore app
> > I did all the required steps and did not work with me
> > > <img alt="" width="48" src="https://camo.githubusercontent.com/abde6bed5239ae865239febe2feb2d96ddc2b838/687474703a2f2f646f63732e696e737069726575692e636f6d2f696d616765732f6d6574612f47686f73742d446f63732e6a7067">InspireUI Document**[FluxStore - Universal mobile commerce Flutter app for Magento, WooCommerce and Opencart](http://docs.inspireui.com/fluxstore/woocommerce-setup/)**Fluxstore is universal app that fully integration with the Woocommerce, Mangeto and Opencart
> 
> Ok, so please make sure that you edit your woocomerce api
> https://docs.inspireui.com/fluxstore/woocommerce-setup/
> Thank you
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/abde6bed5239ae865239febe2feb2d96ddc2b838/687474703a2f2f646f63732e696e737069726575692e636f6d2f696d616765732f6d6574612f47686f73742d446f63732e6a7067">InspireUI Document**[FluxStore - Universal mobile commerce Flutter app for Magento, WooCommerce and Opencart](http://docs.inspireui.com/fluxstore/woocommerce-setup/)**Fluxstore is universal app that fully integration with the Woocommerce, Mangeto and Opencart

please send to me mstore-api

i can not download from website

**Comment by kvt0012** [comment]
We set on default is mstore api, you can find it on common folder.

**Comment by minhcasi** [comment]
@khaledsalama32 - it's available to download at this link - https://wordpress.org/plugins/mstore-api/ - thank you!
