### ISSUE TITLE
[fluxstore] - error when upload app release

### ISSUE THREAD

**Issue by limitlessfirm** [inspireui/support#2251]
---------

1. My issue: [fluxstore] - error when upload app release

2. Screenshots issues:
![Capture](https://user-images.githubusercontent.com/59250639/75626010-583bee00-5bcc-11ea-899d-176c55aa2c4c.JPG)

3. Proof of my purchased:
![screenshot](https://user-images.githubusercontent.com/59250639/75626016-5e31cf00-5bcc-11ea-8921-e9c3eba014ce.JPG)

3. Config files (optional)

**Comment by minhcasi** [comment]
@limitlessfirm - You should be changing your versionCode and versionName in android/app/build.gradle:
```
android {
    defaultConfig {
        versionCode xx
        versionName "xx"
```
