### ISSUE TITLE
Mstore Pro - payment gateway issue

### ISSUE THREAD

**Issue by adminmaccus** [inspireui/support#2252]
Sir, I had already purchase MStore Pro from code canyone.  Below you can find purchase details. 
![Capture](https://user-images.githubusercontent.com/60291435/75628357-aca59480-5bf1-11ea-9242-face0a2f39bf.JPG)

Sir, as mentioned in the product description, mstore pro support almost all payment gateways. 1) Currently the store is located in UAE and my woocommerce store is running a payment gateway called 'TELR'. Will you please tell me how to bring TELR  payment gateway to mstore app. I find tutorials for paypal and stripe only. Kindly help me with this issue. It has been around 45 days i purchased the application and i cannot do integrate payment gateway.  

 Also i would like to tell you that, many issues are solved in the latest update.  Kindly help me solve this. Thankyou

**Comment by minhcasi** [comment]
@adminmaccus - could i know your username on Envato pls - thank you!

**Comment by adminmaccus** [comment]
adminmaccus is the username




Maccus Enterprise Computer Systems Designing Est. 







On Mon, Mar 2, 2020 at 10:36 AM +0400, "Minh Pham" <notifications@github.com> wrote:












@adminmaccus - could i know your username on Envato pls - thank you!

**Comment by adminmaccus** [comment]
Sorry, it the username was maccusadmin, i   attach the email copy along with this.
![Capture](https://user-images.githubusercontent.com/60291435/75675849-76275280-5ca1-11ea-905e-53b11ea8b607.JPG)

**Comment by adminmaccus** [comment]
Sir, will youbplease fix my issue ?? Its very late already. Any help from your side will be highly appreciated. thankyou

**Comment by minhcasi** [comment]
@adminmaccus - thank you for the update

Could you try to install the TELR payment on the website, the app will be connected to your website via Webview - let have a check and let us know - thank you!

**Comment by minhcasi** [comment]
Also share your common folder so that we could try to reproduce on our side, if you have any issues screenshot please attache as well - thanks

**Comment by adminmaccus** [comment]
The TELR payment gateway is already installed in the website and it works fine. But in the mobile app it doesnt. Some webview error is showing. Which folder should i share with you sir ? 




Maccus Enterprise Computer Systems Designing Est. 







On Wed, Mar 4, 2020 at 7:55 AM +0400, "Minh Pham" <notifications@github.com> wrote:












Also share your common folder so that we could try to reproduce on our side, if you have any issues screenshot please attache as well - thanks

**Comment by adminmaccus** [comment]
Sir, i had attached a screen recording and screenshot of the error along with this. If necessary i can add the credentials of my woocommerce website also along with this. please do the needfull. In the checkout page next to cash on delivery there is a blank space. when i click there , i hope its goin to TELR payment gateway page. But there happens the error. Please help me. And i didnt understand about the common folder which have to be shared. please tell me which and how, i will do that.
[Screen_Recording_20200304-202056_1_1.zip](https://github.com/inspireui/support/files/4288507/Screen_Recording_20200304-202056_1_1.zip)
![Screenshot_20200304-201659_Expo 1](https://user-images.githubusercontent.com/60291435/75902238-25f2f080-5e59-11ea-8754-3ff4934ccfdd.jpg)

**Comment by adminmaccus** [comment]
@luyx2412  sir, will you please provide me support ? Am stuck for weeks now. Kindly help. There are upcomming projects which need your platform to work with. Thankyou

**Comment by luyx2412** [comment]
Hi @adminmaccus Sorry about reply you late. Please use this library to replace `Webview` https://github.com/react-native-community/react-native-webview/

Thanks

**Comment by adminmaccus** [comment]
hi @luyx2412  sir, im using cebuilder in macbook for the mstore expo project. Will you please tell me how to implement the webview. As i am new to this, i dont know excatly. Please explain the steps to proceed. I had gone through the read me file in the git. It doesnt give me any idea.  I will upload my source code here as zip file if you prefer. Or else please tell me how to use webview.

**Comment by luyx2412** [comment]
Hi @adminmaccus If you use mstore expo project, please use `Webview` of expo. This is document https://docs.expo.io/versions/latest/sdk/webview/

Thanks

**Comment by adminmaccus** [comment]
Please dont close the thread. My macbook is send for repair and will get back in 3 days. Will get back you at the earliest. Thankyou

**Comment by luyx2412** [comment]
Hi @adminmaccus Ok

**Comment by minhcasi** [comment]
@adminmaccus - how is your laptop? 🤩

**Comment by adminmaccus** [comment]
Sir.. i just got the laptop yesterday




Maccus Enterprise Computer Systems Designing Est. 







On Tue, Mar 24, 2020 at 1:58 PM +0400, "Minh Pham" <notifications@github.com> wrote:















Closed #2252.

**Comment by adminmaccus** [comment]
Can you please reopen it. My issue is not yet resolved. Please




On Tue, Mar 24, 2020 at 1:58 PM +0400, "Minh Pham" <notifications@github.com> wrote:















Closed #2252.
