### ISSUE TITLE
Error in "flutter pub run flutter_launcher_icons:main"

### ISSUE THREAD

**Issue by EdelcioBatista** [inspireui/support#2253]
Hi.

I am trying to change the logo as per the guidelines of "https://docs.inspireui.com/fluxstore/customization/" and after executing the command "flutter pub run flutter_launcher_icons: main" error returns:
"
In the .dart_tool / package_config.json file found, please run "pub get" first.

Starting with Dart 2.7 this file configures the resolution of package import URIs. Running "pub get" will generate this file.
pub finished with exit code 65
"
I'm using VS CODE in Linux Ubuntu

Can you help me?

Proof of purchase:
6b4b9df0-0ac5-472b-8e05-7a7f32b607cf

Thank you.

**Comment by minhcasi** [comment]
@EdelcioBatista - could you try to run this script
```
flutter pub get
flutter pub run flutter_launcher_icons:main
```

Also refer to this guide - https://pub.dev/packages/flutter_launcher_icons - thank you!
