### ISSUE TITLE
1.6.4 Category screen issue, CacheManager 'Unsupported scheme', category image not displaying with error

### ISSUE THREAD

**Issue by interiorone** [inspireui/support#2254]
Item Purchase Code:
xxxxxxxx-60eb-4913-8672-72931e36f12b

I can email you if you require full code.

flutter uptodated , flutter doctor >>> no issues.

Followed all starter guide and still no image, done website thumb regenerate 
Tried Image format : JPG, JPEG, PNG ( ALL NOT WORKING ) PLEASE HELP !!!!!

Error message : 

I/flutter (19946): CacheManager: Failed to download file from //i3.wp.com/interiorone.co.nz/wp-content/uploads/2019/07/Traveline.jpg with error:
I/flutter (19946): Invalid argument(s): Unsupported scheme '' in URI //i3.wp.com/interiorone.co.nz/wp-content/uploads/2019/07/Traveline.jpg

![11583106182_ pic_hd](https://user-images.githubusercontent.com/59524812/75636417-6f89e280-5c83-11ea-9565-89fef0750a72.jpg)

**Comment by minhcasi** [comment]
@interiorone - could you zip your common and config file so that we could help for checking - thank you!

**Comment by interiorone** [comment]
Hi there,

Attached files for you to view.
Thank you.



Kind regards,

Dylan Chan
Your Friendly Customer Service Team

E. info@interiorone.co.nz
P. 09 527 1602
M. 021 990 110
W. www.interiorone.co.nz

**Comment by minhcasi** [comment]
@interiorone - we could not get the screenshot 

Could you help to quickly take the screenshot from http://codecayon.net/downloads as we could not verify the purchase code - thank you!

**Comment by interiorone** [comment]
Kind regards,

Dylan Chan
Your Friendly Customer Service Team

E. info@interiorone.co.nz
P. 09 527 1602
M. 021 990 110
W. www.interiorone.co.nz

**Comment by minhcasi** [comment]
sorry we could not see the screenshot - thanks

**Comment by interiorone** [comment]
<img width="1440" alt="Screen Shot 2020-03-03 at 11 22 53 PM" src="https://user-images.githubusercontent.com/59524812/75936997-8c731f80-5ee8-11ea-9137-6da20a7c7d8d.png">

Can you reopen??

**Comment by interiorone** [comment]
Hi there,

I have reattached , can you reopen the problem??

Kind regards,

Dylan Chan
Your Friendly Customer Service Team

E. info@interiorone.co.nz
P. 09 527 1602
M. 021 990 110
W. www.interiorone.co.nz
