### ISSUE TITLE
Scrolling Error On Home Page

### ISSUE THREAD

**Issue by Varun24041993** [inspireui/support#2255]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
I have added several categories using multiple layout on my home page. So my problem is that if I add icons exceeding a certain limit of numbers on home page then at the last when i scroll up or down it itself starts scrolling as if the app has some glitch in it. I have uploaded the video showing the error in action as you can see this is an app for online grocery website and if I scroll past the "Snacks and branded food" category it is clear in the video that the app is itself scrolling up and down cluelessly as if there is some kind of glitch in the app.

2. Screenshots issues:
This is actually a video of screen on google drive I have uploaded:
https://drive.google.com/file/d/1vdqkiAejjGU9NZuZ-jfMSKpAftZ-N9_-/view?usp=sharing

3. Proof of my purchased:
![Screenshot 2020-03-02 at 4 24 21 AM](https://user-images.githubusercontent.com/56767455/75636524-7e51a480-5c45-11ea-8de6-be86817041bd.png)

3. Config files (optional)

**Comment by luyx2412** [comment]
Hi @Varun24041993 We will improve this issue in next version. You can based on the repo https://github.com/filipemerker/flatlist-performance-tips to improve the performance , specially using the `getItemLayout ` to fix this issue.

Thanks

**Comment by luyx2412** [comment]
- With cateogies menu i answered you, it related the pagination. We did not support this feature in current version, and will support it in next version.
- With the search product screen. Please replace `src/common/Tools.js` with this file.
[Tools.js.zip](https://github.com/inspireui/support/files/4276058/Tools.js.zip)

Thanks

**Comment by Varun24041993** [comment]
Hi Tried your solution for replacing the tools.js file but it threw this error
![Screenshot 2020-03-03 at 5 43 19 AM](https://user-images.githubusercontent.com/56767455/75730151-0e5d2000-5d12-11ea-804e-ebc043a5b459.png)

I have cleared the cache and also reinstalled the node modules as suggested in the error log also performed all the other steps given but the problem is not resolved.

Also as soon as i provide it with the old tools.js file the error is gone but in search page the problem is still the same

**Comment by luyx2412** [comment]
Hi @Varun24041993 Please install library first before continue. Using `yarn install` or `yarn add @react-native-community/async-storage` to fix the issue.

Thanks

**Comment by Varun24041993** [comment]
Hi after installing the source I got this error again:
Error: [@RNC/AsyncStorage]: NativeModule: AsyncStorage is null.

Then I searched for its solution and solution was pretty straight forward. For use in Expo, In the tools.js file we have to import AsyncStorage by:
import { AsyncStorage } from 'react-native';
INSTEAD OF 
import AsyncStorage from "@react-native-community/async-storage";

and this worked for me, now the search problem is solved I think.

For this issue of FlatList and categories pagination error:
I am eagerly waiting for the update because of it I have to delay my plans of launching it on App Store and Play Store. 
Can you please provide me with an expected date for update to fix both the problems so that I can Align my work accordingly ?

I also am facing problem in connecting to facebook login, I have used all the docs solutions but I cannot login via expo, Here is the video of fb login problem:
https://drive.google.com/file/d/1dDaNzryXuyOCmY-hdt7TdUkxYBHIDlHp/view?usp=sharing

Also please let me know how I can show login via phone number option as it is not showing in my login screen.

**Comment by luyx2412** [comment]
Hi @Varun24041993 In Home screen, please limit your product load more which cause scroll issue. And it will help you improve the bad performance app.

P/S: We will improve this issue in nextweek.

Thanks

**Comment by Varun24041993** [comment]
Hi @luyx2412 thanks for this.
I just uploaded my app on IOS store and this was the response from app store.
![WhatsApp Image 2020-03-08 at 5 31 33 PM](https://user-images.githubusercontent.com/56767455/76182395-c5620b80-61ea-11ea-99be-a33e43482c09.jpeg)

I searched for this issue and the solution came out to be using WKWEBVIEW instead of UIWEBVIEW Please help me with this.

and there is one more issue in your template. If I go to add new address there I am not able to make the country default to US and there is no option to hide the country scrolling list also. Even if I add new address and fill all the details still it says to choose a country and it wont allow me to add new address. I have made an video of this error please visit this gmail drive video link to see the error.

https://drive.google.com/file/d/1zyegzeHuKuiCmLiadsETgrRM8pA0Lrf2/view?usp=sharing

**Comment by luyx2412** [comment]
Hi @Varun24041993 It just warning of Apple, your app still can uploading to the store. Or you can read the article to fix it https://medium.com/@NumberShapes/uiwebview-app-store-submission-kickback-issue-bb07d77a902

Thanks

**Comment by Varun24041993** [comment]
Hi @luyx2412 it is clearly mentioned in the mail from apple that they will stop supporting UIWebView from April 2020 which is about a month from now so you will surely have to change it. AnyWays I will try the solution you told me but let me remind you that I am using EXPO mstrore pro version are the steps same on EXPO as well as described in medium.com?

Also please give me solution for the choose country error shown in video above as this is some kind of bug in the Mstore Pro App.

**Comment by luyx2412** [comment]
Hi @Varun24041993 You can use `useWebkit` to remove the message, please follow the document expo to fix the issue https://docs.expo.io/versions/v35.0.0/react-native/webview/.
- In `src/containers/Cart/Delivery/index.js` replace the file with this attach to fix the issue.
[index.js.zip](https://github.com/inspireui/support/files/4313078/index.js.zip)

Thanks

**Comment by Varun24041993** [comment]
Hi @luyx2412 Tried the index.js file but the problem is still the same for adding new address part.

**Comment by Varun24041993** [comment]
HI @luyx2412  any updates ??

**Comment by luyx2412** [comment]
Hi @Varun24041993 Can you send me your project, i will fix and re-send for you. Please send via luyxtran264@gmail.com

Thanks

**Comment by Varun24041993** [comment]
Hi @luyx2412 Please check your mail I have send it through info@techamericalive.com id.

**Comment by Varun24041993** [comment]
Hi @luyx2412 Have you received the files on your mail account ?

**Comment by luyx2412** [comment]
Hi @Varun24041993 This is a file to fix select country. Please replace this file in `src/containers/Cart/Delivery/index.js`
[index.js.zip](https://github.com/inspireui/support/files/4369788/index.js.zip)

Thanks

**Comment by Varun24041993** [comment]
HI @luyx2412 I have tried your file again but neither the country is changing in adding new address. The problem is exactly the same as before.

**Comment by Varun24041993** [comment]
Hi @luyx2412 there is also an issue with api-ecommerce/node_modules/grpc
I have updated my node to latest but the node modules in your api-ecommerce is using the old version so even after trying several time it shows an error :

Failed to execute 'node-gyp build --fallback-to-build --library=static_library --module=/Users/mac/Desktop/App_new_update/mstore-3.9.8/mstore-expo/node_modules/api-ecommerce/node_modules/grpc/src/node/extension_binary/node-v79-darwin-x64-unknown/grpc_node.node --module_name=grpc_node --module_path=/Users/mac/Desktop/App_new_update/mstore-3.9.8/mstore-expo/node_modules/api-ecommerce/node_modules/gr

**Comment by luyx2412** [comment]
Hi @Varun24041993 
- Please uninstall your app and reinstall again. And make sure you opened the `hideCountryList: true` in Config.js file.
- You can switch old node, please use nvm to manage your node version https://github.com/nvm-sh/nvm

Thanks

**Comment by Varun24041993** [comment]
@luyx2412  Alright I will definitely perform these steps and let you know the result also if I am using earlier version of node isn't this something of a security issue here and will you update the api-ecommerce to latest node in future.

Also is there any update regarding the scroll issue and about the next update realise from MStore?

**Comment by Varun24041993** [comment]
Hi @luyx2412  I have uninstalled and installed the node_modules and I have fallen back to previous node module and tried everything but adding address is still not possible in this can you have an Skype session so that I can show you this problem you can email me your Skype id. We have been on this issue for a long Time please help me with this.

**Comment by Varun24041993** [comment]
Hi @luyx2412 I even tried to add address on your store pro with default REST api configurations but turns out that even there the same error exists and we were not able to add the address there also.

**Comment by luyx2412** [comment]
Hi @Varun24041993 Can you send me the video about the issue? I just tested again your config and everything worked normal.

Thanks

**Comment by Varun24041993** [comment]
Hi @luyx2412 alright I will send you the video again today. Thank You

**Comment by Varun24041993** [comment]
Hi @luyx2412 Here is the Video of the error first I have shown you the code for index.js file you have sent me. You can see that If I change the country the country still remains the same as I wanted it to be US only but still it shows the list of countries also I have make country list to false in the config.js file.

https://drive.google.com/file/d/1HK0q93UefMmbAqGAXvbe8NkOLHsOUh4c/view?usp=sharing

I also wanted to clear one thing in the Wordpress panel we can edit the billing details but we cannot add more billing address list so will this panel edit my existing billing address or will it try to add new billing address in Wordpress panel also for the shipping details will the shipping details be added here or not.

**Comment by luyx2412** [comment]
Hi @Varun24041993 Please uninstall your expo and reinstall again. Maybe some issues related cache. This is the video about your project. Please check again with new file `src/containers/Cart/Delivery/index.js` 
[index.js.zip](https://github.com/inspireui/support/files/4419315/index.js.zip)

https://drive.google.com/file/d/1a-KwdrpFGWqicQN2xTwKhnTS5-kHtOVc/view?usp=sharing

Thanks
