### ISSUE TITLE
Facebook Login not configured on mstore using expo for testing

### ISSUE THREAD

**Issue by Varun24041993** [inspireui/support#2256]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
I have read the docs and tried all that was written to connect my facebook login to expo in testing face I have already successfully connect facebook login to website but in my app even after doing all the configurations when i click login via facebook it doesn't redirect or do anything just nothing is done by app on clicking on it.

2. Screenshots issues:
This is a video link from google docs:
https://drive.google.com/file/d/1dDaNzryXuyOCmY-hdt7TdUkxYBHIDlHp/view?usp=sharing

3. Proof of my purchased:
![Screenshot 2020-03-02 at 4 24 21 AM](https://user-images.githubusercontent.com/56767455/75636672-b6a5b280-5c46-11ea-88b6-a0e367a0d19e.png)

3. Config files (optional)

**Comment by minhcasi** [comment]
moved to ticket #2255 

Please help to note the issue at the same ticket - thank you!
