### ISSUE TITLE
Some Product Categories From Website Not Showing In App Menu

### ISSUE THREAD

**Issue by Varun24041993** [inspireui/support#2257]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
This is my previous issue on github regarding this issue:
(https://github.com/inspireui/support/issues/1916#)
As promised by your team the next update should have fixed the error but after the next app update my problem still remains as some of the product categories from my website is not shown in my App menu. Please help me fix it as your new update has already being launched in the market.

2. Screenshots issues:
My Previous github error:
(https://github.com/inspireui/support/issues/1916#)

3. Proof of my purchased:
![Screenshot 2020-03-02 at 4 24 21 AM](https://user-images.githubusercontent.com/56767455/75636880-9f67c480-5c48-11ea-9f98-f386cdbd87df.png)

3. Config files (optional)

**Comment by minhcasi** [comment]
moved to ticket #2255 

Please help to note the issue at the same ticket - thank you!
