### ISSUE TITLE
Error shown when searching for product on search page

### ISSUE THREAD

**Issue by Varun24041993** [inspireui/support#2258]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
When I tried to search some product name on my app search page it shows me a list of error screenshot is included below. The redux state then saves the error and if i try to restart the app again or reload it and then click on the search page again then again the error is shown on the search page as the state is saved by redux according to me.

2. Screenshots issues:
![Screenshot 2020-03-02 at 4 36 10 AM](https://user-images.githubusercontent.com/56767455/75636955-287efb80-5c49-11ea-9440-ff73fe77c209.png)

![Screenshot 2020-03-02 at 4 36 35 AM](https://user-images.githubusercontent.com/56767455/75636962-2cab1900-5c49-11ea-9a79-749a62aa66b6.png)

3. Proof of my purchased:
![Screenshot 2020-03-02 at 4 24 21 AM](https://user-images.githubusercontent.com/56767455/75636973-3896db00-5c49-11ea-9cbd-a4c4a9a31782.png)

3. Config files (optional)

**Comment by minhcasi** [comment]
moved to ticket #2255

Please help to note the issue at the same ticket - thank you!
