### ISSUE TITLE
Scrolling Error If I link category id to icons on home page that is not available or is delete on website.

### ISSUE THREAD

**Issue by Varun24041993** [inspireui/support#2259]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
I have added some icons on home page and i have linked these icon to product categories from website. But if the product category id is not available due to some reason from the website then it shows a list of errors (screenshot is included below). I think if the category id is not available from website then it should show a blank page instead of showing a list of errors as it does in some case but in some case it shows the list of errors.

2. Screenshots issues:
![Screenshot 2020-03-01 at 8 42 45 PM](https://user-images.githubusercontent.com/56767455/75637078-0174f980-5c4a-11ea-8b4e-f7138b5b22ff.png)
![Screenshot 2020-03-01 at 8 43 01 PM](https://user-images.githubusercontent.com/56767455/75637082-05a11700-5c4a-11ea-89be-4a8dfad57fb6.png)
![Screenshot 2020-03-01 at 8 43 18 PM](https://user-images.githubusercontent.com/56767455/75637083-0639ad80-5c4a-11ea-883f-800dcb500228.png)
![Screenshot 2020-03-01 at 8 43 35 PM](https://user-images.githubusercontent.com/56767455/75637086-06d24400-5c4a-11ea-93bc-90c967cdfa8e.png)

3. Proof of my purchased:
![Screenshot 2020-03-02 at 4 24 21 AM](https://user-images.githubusercontent.com/56767455/75637098-16518d00-5c4a-11ea-9b4b-b29ee5c62713.png)

3. Config files (optional)

**Comment by minhcasi** [comment]
@Varun24041993 - pls try to correct the category id as the config.json not always change the red screen is shown for debug mode - we will think about the solution later

Man, please try to update one ticket your all issues, please don't spam ticket here - thanks
