### ISSUE TITLE
Permission denied when running CEBuilder

### ISSUE THREAD

**Issue by aviontech** [inspireui/support#226]
From Comments reply;

On Mac OS, just try to login as the Administrator.
Ran terminal then sudo < path / CEBuilder >, still hits same error

One thing: please check if the Tools libraries are all check.
Yes, all green.

Second, please update the 0.26.2 from – http://inspireui.com
Done, same error.

Please see screenshot attached.
<img width="697" alt="screenshot 2019-01-29 at 1 19 36 am" src="https://user-images.githubusercontent.com/22040990/51855038-3dfb6500-2367-11e9-8e38-be0034ae6bf2.png">

Please help. This is really an awesome product.

**Comment by minhtruong315** [comment]
Hi @aviontech Can you add my skype so that I can help you via teamview?
my skype: minhtruong315@gmail.com
Thanks

**Comment by aviontech** [comment]
Hi 

Tried to add you but cant find contacts. 
Can you add me instead? minjun.soo (ID)

**Comment by aviontech** [comment]
Hi 

Anyone there? Please assist :-) Thanks!

**Comment by minhtruong315** [comment]
@aviontech I don't your contact. pls share me your contact
