### ISSUE TITLE
login Via SMS button not shown in App.

### ISSUE THREAD

**Issue by Varun24041993** [inspireui/support#2260]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
Please help me to show the login via SMS button on the login screen of the App as I don't have any idea how the Button will be visible on the login screen also please provide me instructions to connect it to function via Account Kit as your documentation is old and incomplete inspite of your App being updated recently for using this SMS function as it has no documentation shown for login in the your docs.inspireu website.

2. Screenshots issues:
(None)

3. Proof of my purchased:
![Screenshot 2020-03-02 at 4 24 21 AM](https://user-images.githubusercontent.com/56767455/75637171-a68fd200-5c4a-11ea-8cbf-6b086f8bb613.png)

3. Config files (optional)

**Comment by minhcasi** [comment]
@Varun24041993 - note with an update - thank you!
