### ISSUE TITLE
[Fluxstore Woocommerce] - App Order Label in Order page

### ISSUE THREAD

**Issue by themeix** [inspireui/support#2261]
1. My issue:
As a store owner i am missing a feature in that app. There have no way to know, how the user placing order by using app or direct website. So if there had any Small text label [App Order] in order page inside customer note or anywhere. That would be great i think. It just  a simple fix in msore-api plugin. 

I hope you will add it. So we can identify our customer use app or not and we can offer special offer to app customers next time. 

2. Screenshots issues (required):

3. Proof of my purchased (required):
https://raw.githubusercontent.com/themeix/temp/master/screenshot-589.png
4. Config files (required)
N/A

**Comment by minhcasi** [comment]
@themeix - thank you for good suggestion 

@kvt0012 - pls automatically  add the content [mobile-note] from the checkout

**Comment by minhcasi** [comment]
move to #2217 - hi man, please try to raise your all issues to the same ticket, instead of spam on multi one - thank you for your understanding
