### ISSUE TITLE
[fluxstore] - Splash Screen

### ISSUE THREAD

**Issue by Saifahmad99** [inspireui/support#2262]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: Splash Screen Position is not in the centre

2. Screenshots issues (required):
![WhatsApp Image 2020-03-02 at 12 15 13 PM](https://user-images.githubusercontent.com/59877416/75651846-99410a80-5c7f-11ea-8d3e-b49f29b5a8c3.jpeg)

3. Proof of my purchased (required):
![Screenshot (32)](https://user-images.githubusercontent.com/59877416/75651944-de653c80-5c7f-11ea-9f52-61174cc674e7.png)

3. Config files (required)

**Comment by minhcasi** [comment]
@Saifahmad99 - could you help to attache your splash screen image here so that we could have a check - thanks

**Comment by Saifahmad99** [comment]
![Logo 25_b](https://user-images.githubusercontent.com/59877416/75847232-9f142880-5e04-11ea-8f04-984c01b2e5df.png)

**Comment by Saifahmad99** [comment]
This is the image file please help me quickly.

**Comment by minhcasi** [comment]
Hi @Saifahmad99 - this is not a but, try to resize the image width x height to: 828 x 1792 like the attachment to fix the issue - thanks

![splashscreen](https://user-images.githubusercontent.com/1459805/75945766-c08d1700-5ecd-11ea-9756-abb209e59822.png)
