### ISSUE TITLE
Magento 2 setup racative mstore on local

### ISSUE THREAD

**Issue by kingboyno1** [inspireui/support#2263]
We face the probelm:
1.	Unzip the file
2.	Setup magento extension/mstore to M2 app folder
3.upgrade and flushing the cache
4.	Setup the unzip file to setup NPM.
4.	 Set local testing enviroment Magento API.
5.	Download CeBuider.
6.	Follow the instruction to setup and get the below results：
“The Rest API is not working correctly !”
<img width="1024" alt="2" src="https://user-images.githubusercontent.com/39088495/75665838-c2798f00-5caf-11ea-8fae-a3dde8400696.png">

Purchase code purchase from "codecanyon.net" but don't found the purchase key. But for my id is kingboyno1

**Comment by minhtruong315** [comment]
@kingboyno1 You can edit accessToken in AppConfig.json by this: ```7r5x3cae1dm3bcx6rbeyvnagxl6afxpo```
Then try again

**Comment by kingboyno1** [comment]
ok Tks.
For now we also face the problem still blank page.&nbsp;
see we submit&nbsp;https://github.com/inspireui/support/issues/2278
also you can see enclosed , Is cbuild have bug or?
Can you proivde the latest version?


Best Regards


&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------

**Comment by 234146326** [comment]
#2278

**Comment by minhtruong315** [comment]
@234146326 what is CeBuilder version that you're using?

**Comment by 234146326** [comment]
> @kingboyno1 You can edit accessToken in AppConfig.json by this: `7r5x3cae1dm3bcx6rbeyvnagxl6afxpo`
> Then try again

Version: **_0.39.0_**
<img width="817" alt="11" src="https://user-images.githubusercontent.com/17285770/75863410-5deb3b00-5e3b-11ea-9dc8-ff6a8165dd1a.png">

**Comment by kingboyno1** [comment]
version 0.39.0




&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------

**Comment by 234146326** [comment]
@minhtruong315 Hello, are you helping us solve the problem?

**Comment by minhcasi** [comment]
@234146326 - could you help to download the latest 0.40.1 - thank you!

**Comment by 234146326** [comment]
@minhcasi  This new version cannot detect the environment。
![image](https://user-images.githubusercontent.com/17285770/76140465-a00fb900-6095-11ea-9037-d5d896920b88.png)

**Comment by minhtruong315** [comment]
@kingboyno1 @234146326 please use the latest version then check again. @234146326 you need to click Install All

**Comment by kingboyno1** [comment]
Do you have skype? So we can talk by skype? Seems still not working




&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------

**Comment by minhtruong315** [comment]
@kingboyno1 add my skype: minhtruong315

**Comment by kingboyno1** [comment]
Noted and Tks.&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------

**Comment by minhtruong315** [comment]
I messaged you on the skype. please response. thanks

**Comment by kingboyno1** [comment]
Hi ,
Ok will reply it. My skype&nbsp;live:jerryxuying




&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------

**Comment by 234146326** [comment]
Run through Expo-cli and give up cebuilder. This is the best solution.


<img width="1465" alt="11" src="https://user-images.githubusercontent.com/17285770/76784783-35762000-67ef-11ea-93cf-ef77ab1c32b9.png">

**Comment by minhtruong315** [comment]
@kingboyno1 how about your issue?

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!

**Comment by RashVenkat6795** [comment]
@kingboyno1 
Is the issue resolved ?

@minhtruong315 @234146326 @minhcasi 
I'm facing similar issue. I did install the latest ce builder tool & added the accesstoken. But when i try to run the app. Getting can't get data from Server.

Proof of my purchase 
![Screenshot 2020-04-30 at 7 39 58 PM](https://user-images.githubusercontent.com/26426904/80720602-c3e1ff00-8b1a-11ea-911e-6f32eeead1d0.png)

**Comment by 234146326** [comment]
> @kingboyno1
> Is the issue resolved ?
> 
> @minhtruong315 @234146326 @minhcasi
> I'm facing similar issue. I did install the latest ce builder tool & added the accesstoken. But when i try to run the app. Getting can't get data from Server.
> 
> Proof of my purchase
> ![Screenshot 2020-04-30 at 7 39 58 PM](https://user-images.githubusercontent.com/26426904/80720602-c3e1ff00-8b1a-11ea-911e-6f32eeead1d0.png)

https://github.com/inspireui/support/issues/2263#issuecomment-599668356
