### ISSUE TITLE
[EvaStore] - Loggin isnt work 

### ISSUE THREAD

**Issue by jpakkal** [inspireui/support#2265]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: When I try to create a new paid user, only the message appears the user or email is incorrect, but im creating a new user.
Thanks for you help

2. Screenshots issues (required):

![image](https://user-images.githubusercontent.com/39502780/75705868-dc03e200-5c81-11ea-9a30-48250b63b098.png)

3. Proof of my purchased (required):
![image](https://user-images.githubusercontent.com/39502780/75706088-3dc44c00-5c82-11ea-9637-59f914437d61.png)

3. Config files (required)
/** @format */

import Constants from "./Constants";
import Icons from "./Icons";

export default {
  /**
   * Step 1: change to your website shopify graphqlUrl, and storeAccessToken
   * https://help.shopify.com/en/api/custom-storefronts/storefront-api/getting-started
   * Moved AppConfig.json
   */

  // to config custompage
  Wordpress: {
    url: "http://mstore.io",
  },

  /**
     Step 2: Setting Product Images
     - ProductSize: Explode the guide from: update the product display size: https://mstore.gitbooks.io/mstore-manual/content/chapter5.html
     The default config for ProductSize is disable due to some problem config for most of users.
     If you have success config it from the Wordpress site, please enable to speed up the app performance
     - HorizonLayout: Change the HomePage horizontal layout - https://mstore.gitbooks.io/mstore-manual/content/chapter6.html
     */
  ProductSize: {
    enable: false,
    CatalogImages: { width: 300, height: 960 },
    SingleProductImage: { width: 1200, height: 1440 },
    ProductThumbnails: { width: 180, height: 216 },
  },

  /**
   * Step 3: Setting Home screen, category screen
   * Follow this article to use Graphql https://help.shopify.com/en/api/custom-storefronts/storefront-api/graphql
   * Video tutorial https://www.dropbox.com/s/m4kmp0quh8qplz3/Screen%20Recording%202018-11-05%20at%202.22.21%20PM.mov?dl=0
   */
  SpaceLayout: 30, // setting align right
  /**
   * config home page show
   * - horizontal with multi collection id or
   * - vertical layout with latest product and first product is banner
   */
  HomePage: {
    Horizon: true,
    PageSize: 12,
  },
  HorizonLayout: [
    {
      categoryId: "Z2lkOi8vc2hvcGlmeS9Db2xsZWN0aW9uLzEzNzc5MjI1ODE0NA==",
      paging: true,
      layout: Constants.Layout.miniBanner,
    },
    {
      name: "Lo más vendido",
      categoryId: "Z2lkOi8vc2hvcGlmeS9Db2xsZWN0aW9uLzEyNzUxNjk2NzAwOA==",
      layout: Constants.Layout.threeColumn,
    },
    {
      name: "Nuevos",
      categoryId: "Z2lkOi8vc2hvcGlmeS9Db2xsZWN0aW9uLzEyNzUxNzAzMjU0NA==",
      layout: Constants.Layout.twoColumn,
    },
    {
      name: "Faldas",
      categoryId: "Z2lkOi8vc2hvcGlmeS9Db2xsZWN0aW9uLzEzNzc5MjI1ODE0NA==",
      layout: Constants.Layout.twoColumnHigh,
    },
    {
      name: "Básicos",
      categoryId: "Z2lkOi8vc2hvcGlmeS9Db2xsZWN0aW9uLzEzNzc5MjM4OTIxNg==",
      layout: Constants.Layout.card,
    },
    //{
    //  name: "News",
    //  type: "article",
    //  layoutType: "post", // "post" or "product" is default
    //  layout: Constants.Layout.threeColumn,
    //},
  ],

  CategoryLayout: {
    ListMode: "ListMode",
    GridMode: "GridMode",
    CardMode: "CardMode",
  },

  /**
   * Now we only support Webview payment, so disable this feature
   * In the furture we will try support this feature
   */
  Payments: [
    // {
    //   name: "Cash on Delivery",
    //   imageUrl: require("@images/payment_logo/cash_on_delivery.png"),
    //   enabled: true,
    // },
    // {
    //   type: "card",
    //   name: "Credit Card",
    //   imageUrl: require("@images/payment_logo/credit_card.png"),
    //   enabled: true,
    // },
  ],

  /**
     Step 4: Advance config:
     - showShipping: option to show the list of shipping method
     - showStatusBar: option to show the status bar, it always show iPhoneX
     - LogoImage: The header logo
     - CustomPages: Update the custom page which can be shown from the left side bar (Components/Drawer/index.js)
     - intro: The on boarding intro slider for your app
     - menu: config for left menu side items (isMultiChild: This is new feature from 3.4.5 that show the sub products categories)
     * */
  shipping: {
    visible: true,
    time: {
      free_shipping: "4 - 7 Days",
      flat_rate: "1 - 4 Days",
      local_pickup: "1 - 4 Days",
    },
  },
  showStatusBar: true,
  LogoImage: require("@images/logo.png"),
  CustomPages: { contact_id: 10941 },

  /**
   * Config Menu Side Drawer
   * @param goToScreen 3 Params (routeName, params, isReset = false)
   * BUG: Language can not change when set default value in Config.js ==> pass string to change Languages
   */
  menu: {
    // has child categories
    isMultiChild: true,
    // Unlogged
    listMenuUnlogged: [
      {
        text: "Login",
        routeName: "Login",
        params: {
          isLogout: false,
        },
        icon: Icons.MaterialCommunityIcons.SignIn,
      },
    ],
    // user logged in
    listMenuLogged: [
      {
        text: "Logout",
        routeName: "Login",
        params: {
          isLogout: true,
        },
        icon: Icons.MaterialCommunityIcons.SignOut,
      },
    ],
    // Default List
    listMenu: [
      {
        text: "Shop",
        routeName: "Default",
        icon: Icons.MaterialCommunityIcons.Home,
      },
      //{
      //  text: "About",
      //  routeName: "CustomPage",
      //  params: {
      //    url: "http://inspireui.com",
      //  },
      //  icon: Icons.MaterialCommunityIcons.Email,
      //},
    ],
  },
};

Package Json >>>>>

{
  "name": "NewMe",
  "description": "NewMe",
  "author": "Colectivo Digital",
  "version": "2.1.0",
  "private": true,
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "postinstall": "rndebugger-open"
  },
  "dependencies": {
    "@callstack/react-theme-provider": "^1.0.7",
    "@expo/vector-icons": "^10.0.1",
    "babel-plugin-add-shopify-header": "^1.0.6",
    "babel-plugin-graphql-js-client-transform": "^1.1.1",
    "babel-preset-shopify": "16.6.0",
    "base-64": "0.1.0",
    "color": "^3.0.0",
    "currency-formatter": "1.5.3",
    "expo": "35.0.0",
    "expo-ads-facebook": "~7.0.0",
    "expo-asset": "~7.0.0",
    "expo-av": "~7.0.0",
    "expo-constants": "~7.0.0",
    "expo-facebook": "~7.0.0",
    "expo-font": "~7.0.0",
    "expo-google-app-auth": "^7.0.0",
    "expo-linear-gradient": "~7.0.0",
    "expo-web-browser": "~7.0.0",
    "graphql-js-client": "0.9.2",
    "html-entities": "1.2.1",
    "lodash": "4.17.11",
    "moment": "2.23.0",
    "oauth-1.0a": "1.0.1",
    "react": "16.8.3",
    "react-dom": "^16.8.6",
    "react-native": "https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz",
    "react-native-animatable": "^1.3.2",
    "react-native-app-intro-slider": "^3.0.0",
    "react-native-collapsible": "1.4.0",
    "react-native-credit-card": "https://github.com/inspireui/react-native-credit-card.git",
    "react-native-dialog": "^5.6.0",
    "react-native-drawer": "https://github.com/luyx2412/react-native-drawer.git",
    "react-native-gesture-handler": "~1.3.0",
    "react-native-modalbox": "^1.7.1",
    "react-native-parallax": "0.3.0",
    "react-native-radio-buttons": "1.0.0",
    "react-native-render-html": "^4.1.1",
    "react-native-safe-area-view": "^0.14.6",
    "react-native-screens": "~1.0.0-alpha.23",
    "react-native-scrollable-tab-view": "^0.10.0",
    "react-native-snap-carousel": "^3.8.0",
    "react-native-star-rating": "1.1.0",
    "react-navigation": "^3.11.0",
    "react-redux": "6.0.0",
    "redux": "4.0.1",
    "redux-persist": "5.10.0",
    "redux-thunk": "2.3.0",
    "reselect": "4.0.0",
    "tcomb-form-native": "0.6.20",
    "urijs": "1.19.1",
    "url": "0.11.0",
    "url-parse": "1.4.4",
    "util": "0.11.1",
    "uuid": "3.3.2",
    "validate.js": "0.12.0",
    "wpapi": "1.1.2"
  },
  "devDependencies": {
    "@babel/core": "^7.5.5",
    "@babel/plugin-proposal-decorators": "^7.4.4",
    "babel-plugin-transform-remove-console": "^6.9.4",
    "babel-preset-expo": "^5.1.0",
    "jest-expo": "^33.0.0",
    "react-native-debugger-open": "0.3.24",
    "reactotron-react-native": "^2.1.0",
    "reactotron-redux": "^2.1.0"
  }
}

**Comment by jpakkal** [comment]
I realized that if I click on loggin and click on another point, the loggin is generated correctly, how can I solve it? And when I try to make the payment the screen stays frozen and does not advance to be able to choose payment method.

![image](https://user-images.githubusercontent.com/39502780/75727144-d91ce780-5ca9-11ea-8a76-35d2d6d2be17.png)

**Comment by luyx2412** [comment]
Hi @jpakkal Please send me the AppConfig.json file.

Thanks

**Comment by jpakkal** [comment]
Hi @luyx2412 my file

[AppConfig.json.zip](https://github.com/inspireui/support/files/4282073/AppConfig.json.zip)

**Comment by jpakkal** [comment]
@luyx2412 I make some proves and only detect the delay in expo from IOS in Android works fine.

**Comment by luyx2412** [comment]
Hi @jpakkal You meat the Android app still work normal, only iOS did not work?

**Comment by jpakkal** [comment]
Hi @luyx2412, its correct in Android works fine but  in IOS the app stay freeze in the last screen of checkout, the app is available in app store i cant complete a sale.

**Comment by jpakkal** [comment]
*but i cant complete a sale

**Comment by luyx2412** [comment]
Hi @jpakkal You meant the webview was freeze? I think you should be login before checkout on iOS. And can you describe more about it or send me the screenshot.

Thanks
