### ISSUE TITLE
[fluxstore-woocommerce] - 

### ISSUE THREAD

**Issue by khaledsalama32** [inspireui/support#2266]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
when i try run app with my mobile show me this : 

2. Screenshots issues (required):

![2020-03-02 (3)](https://user-images.githubusercontent.com/61389531/75709255-6163b280-5cd3-11ea-9257-f474565bfa20.png)
![2020-03-02 (4)](https://user-images.githubusercontent.com/61389531/75709258-632d7600-5cd3-11ea-9be7-d87708bab2ea.png)
![2020-03-02 (5)](https://user-images.githubusercontent.com/61389531/75709260-645ea300-5cd3-11ea-865f-d180e38bc565.png)
![2020-03-02](https://user-images.githubusercontent.com/61389531/75709263-64f73980-5cd3-11ea-9236-249815192081.png)
![2020-03-02 (1)](https://user-images.githubusercontent.com/61389531/75709265-658fd000-5cd3-11ea-94e7-494e4e471022.png)
![2020-03-02 (2)](https://user-images.githubusercontent.com/61389531/75709267-66286680-5cd3-11ea-8758-a6f4420073cf.png)

3. Proof of my purchased (required):
9e83ec40-8414-4b23-960d-0b69d207dd89 
3. Config files (required)
[config.zip](https://github.com/inspireui/support/files/4277467/config.zip)

**Comment by minhcasi** [comment]
@khaledsalama32 - could i check if you could run this guide example guide smoothly? - https://flutter.dev/docs/get-started/test-drive ? Thank you!
