### ISSUE TITLE
Fluxstore - 33 Errors - 5 Android 21 General 6 Internationalization 7 JSON 15 XML Issue closed #2128

### ISSUE THREAD

**Issue by gurutos** [inspireui/support#2267]
Good Day Support Team,

I have created this issue 2 times and have been closed without solving or comments:

The last one number is #2128 

i wait for 14 days ago and also i ask yesterday for an update,

--------------------------------------------------------------------------------------------------------------

My issue:
Im working with windows and android studio.
Following the video ( Install Fluxstore on Windows ) I open an existing project, i got dependencies and execute flutter doctor returning everything ok(check).

Then at the top of menu i Clic ( analyze - inspect code ), but im getting 33 issues.

Can you please let me know if this is "normal"?

Errors details:
https://user-images.githubusercontent.com/61175861/74706987-7a099e00-51e6-11ea-9bb1-c8e4fec20e70.png

https://user-images.githubusercontent.com/61175861/74707008-8aba1400-51e6-11ea-946a-86115a71dd46.png

https://user-images.githubusercontent.com/61175861/74707035-9e657a80-51e6-11ea-8725-b9c4fdf525df.png

2. Screenshots issues:

https://user-images.githubusercontent.com/61175861/74706360-afad8780-51e4-11ea-896f-ab2b25ad7ef9.png

3. Proof of my purchased:
https://user-images.githubusercontent.com/61175861/74761989-00f06200-524b-11ea-86cd-638578b62da2.png

Thanks and Regards,
Pao Montes.

**Comment by minhcasi** [comment]
@gurutos - this is normal from Flutter project 

You can check the "Dart Analysis" from the bottom of the Android Studio (after installed the Flutter plugin),  this is important to check the code convention and error from Flutter project

More detail explain on this link https://github.com/flutter/flutter/wiki/Using-the-Dart-analyzer

Let us know if you have any questions.

**Comment by gurutos** [comment]
Hello Minhcasi,

Thanks for your link, i check dart analysis and its ok!

i have a question, so this errors will be in every phase of the project? when we release this app this errors arent going to be problems?

Thanks and Regards,
Pao Montes.

**Comment by minhcasi** [comment]
Yes, confirm these are kind of warning checking from the Editor that not impact to the Flutter project - thank you!

**Comment by gurutos** [comment]
ok minhcasi, thanks for your support, i will ignore that errors.
Thanks and Regards,
Pao Montes.

**Comment by minhcasi** [comment]
@gurutos - could i check if you are the same user on this ticket https://github.com/inspireui/support/issues/2381 - or someone copy of your verify purchase screenshot?
