### ISSUE TITLE
Logo and splash screen do not change

### ISSUE THREAD

**Issue by EdelcioBatista** [inspireui/support#2268]
Hello,

I'm trying to change the Logo and the splash screen, according to the instructions in "https://docs.inspireui.com/fluxstore/customization/#2-logo-splash-screen" but nothing happens.

I also tried to change the "about us" and nothing happened !!!

No mistake but the change does not happen on my phone.

I already uninstalled and installed the app and it didn't work.

I'm using VS CODE in Linux Ubuntu

Can you help me?

Proof of purchase:
6b4b9df0-0ac5-472b-8e05-7a7f32b607cf

Thank you.

Thanks

**Comment by kvt0012** [comment]
Please make sure that you run flutter clean before rebuild, thank you

**Comment by mansoor88** [comment]
I changed the logo and splash screen. Both are working fine in emulator but giving issues when running apk on device. The default splash screen appears on device not the one which i put it.
