### ISSUE TITLE
[FluxStore] - web view payment 

### ISSUE THREAD

**Issue by abd096** [inspireui/support#2269]
Hello,

I am having issue with the payment page.

When it loads the web view payment getaway for the first time, it return back to website checkout page and says "we cant proceed your order" so i have to press back on the app and try to pay again so it goes to payment getaway and i can make the payment.

This issue happens only for every first time i install the app and use it.

Purchase code: https://prnt.sc/r03dpe

**Comment by themeix** [comment]
Yes.. I am also getting that error for the first time when user go to the checkout.
https://i.postimg.cc/wjMKT24B/screenshot-628.png

**Comment by minhtruong315** [comment]
@abd096 can u send me config.dart file?

**Comment by abd096** [comment]
here it is


[config.zip](https://github.com/inspireui/support/files/4286263/config.zip)

**Comment by minhtruong315** [comment]
@abd096 I can't get shipping methods on your site. can u send me admin account via email: truong@inspireui.com with subject: https://github.com/inspireui/support/issues/2269

**Comment by abd096** [comment]
i sent it already, but the WP is Arabic, please let me if i can support whit it.

One more thing, i can get the shipping method on my app i dont have problem with it

**Comment by minhtruong315** [comment]
[payment.mov.zip](https://github.com/inspireui/support/files/4286792/payment.mov.zip)
I see it's working well. can u record screen?

**Comment by abd096** [comment]
it is showing in the record you sent, one you pressed on "Place My Order" it went to MStore API page then to website checkout page with red error on the top saying, "We were unable to process your order, please try again". 

So you had to scroll down and press on "Proceed to Telr"

If you try one more time to place an order, the above error wont show and it will go direct to Telr page

**Comment by abd096** [comment]
Hello @minhtruong315 

Have you checked the issue ?

**Comment by minhtruong315** [comment]
@abd096 you see on my record. I can press on "Proceed to Telr". can u record screen?

**Comment by abd096** [comment]
@minhtruong315 yes i see on your record and if i make a record it will show the same but my issues is not pressing on "Proceed to Telr" or not, i will explain to you again:

- For the first time i use the app the following happens:

On mobile app checkout page and after i choose 'Pay by Card" the app will open webview and goes to MStore checkout page then to woocommerce checkout page (on woocommecer checkout page an error saying "We were unable to process your order, please try again") will come.

So you have to scroll down and press on "Proceed to Telr" to open the payment getaway page and make the payment.


- For the secound and third times you open the app and follow, the following happens:

On mobile app checkout page and after i choose 'Pay by Card" the app will open webview and goes to MStore checkout page then go directly and without any errors from woocommerce to payment getaway page where i can put my card info and proceed with the payment.

And this is the proper transmission.


So we have in here two cases, the first one is wrong and the secound one is correct, where the secound case happens only and after the first happens.

**Comment by abd096** [comment]
@themeix are you still having the same issue as well?

**Comment by abd096** [comment]
@minhtruong315 is it cleared for you now ?

**Comment by themeix** [comment]
it happened for me only for the first time when app installed and using web view payment

**Comment by abd096** [comment]
@themeix as same as me, did you find anyway ti fix it?

**Comment by minhtruong315** [comment]
@abd096 send me admin account via email: truong@inspireui.com with subject: https://github.com/inspireui/support/issues/2269

**Comment by abd096** [comment]
I sent it to you @minhtruong315 please check

**Comment by abd096** [comment]
Hi man @minhtruong315 please i need a solution for it, i am lunching the app really soon

**Comment by abd096** [comment]
Hello, @minhtruong315 can you provide a paid service to solve the issue ?

**Comment by minhcasi** [comment]
Hi, we are going to release new version that include the fixed on payment on this week, please keep an update and let us know - thank you!

**Comment by abd096** [comment]
Ok @minhcasi thanks

**Comment by minhtruong315** [comment]
@abd096 pls download the latest version then check again. and let me know your results. thanks

**Comment by abd096** [comment]
Hello @minhtruong315 i just tested it, it is still the same as before. the issue is not resolved

**Comment by minhtruong315** [comment]
Do you want me to disable auto submit on payment webview?

**Comment by abd096** [comment]
@minhtruong315 what does that mean ?

**Comment by minhtruong315** [comment]
@abd096 I fixed it. can u send me full source code via my email: truong@inspireui.com with subject: https://github.com/inspireui/support/issues/2269
I will update on your source code.

**Comment by minhtruong315** [comment]
I sent you updates on the email. please check and let me know. thanks

**Comment by abd096** [comment]
Hello @minhtruong315 , how are you?
Thank you for the update but unfortunately, it didn't work.
I used the attached source code and updated AStore API but It seems now is giving the same error on MStore API page instead of woocommerce checkout page.

**Comment by minhtruong315** [comment]
supported via email

**Comment by Pankaj-Sakariya** [comment]
Hi @minhtruong315 
I'm also facing same issue, can you please elaborate what you have done to resolve this?
I have a valid license of FluxStore. Kindly guide us.
