### ISSUE TITLE
EVASTORE - Homepage editting not working

### ISSUE THREAD

**Issue by cakerake** [inspireui/support#227]
Product : EVA Store
Code : 9db31c14-a813-4d8c-8bc1-afdc6da180ec

I have updated config.js to include my shop's api and it works okay

when i try to add categoryID - it also works
but category names do not update even if i change it
the first banner area doesnt change if i change category id

the size/template of the 1-2-3 product categories dont change either

can you please help?

ive tried refreshiong the app many times but nothing updates

**Comment by luyx2412** [comment]
Hi @cakerake Are you uninstall and reinstall app again? And can you provide me your Evastore version?

Thanks

**Comment by cakerake** [comment]
I have the latest version
  

  
What should I uninstall? Expo on my iPhone? That’s where I’m testing it   
  
  

  
  
>

**Comment by luyx2412** [comment]
Hi @cakerake You can uninstall Expo and reinstall Expo again on your iPhone.

Thanks
