### ISSUE TITLE
[Fluxstore WooCommerce] - Order Note still not working

### ISSUE THREAD

**Issue by themeix** [inspireui/support#2270]
1. My issue:
Customer Note / Order Note not working for the app. Please check that issue.  I already shared my github repo access to that email, vinhkhiemt135@gmail.com

He showed that your mstore demo server is working fine but in my live server its not working. So please investigate that bug

2. Screenshots issues (required):
https://i.postimg.cc/Pf1TBS0s/screenshot-627.png

3. Proof of my purchased (required):
https://raw.githubusercontent.com/themeix/temp/master/screenshot-589.png

3. Config files (required)

**Comment by minhcasi** [comment]
move to #2217 - hi man, please try to raise your all issues to the same ticket, instead of spam on multi one - thank you for your understanding
