### ISSUE TITLE
[i want buy this app ] - 

### ISSUE THREAD

**Issue by khaledsalama32** [inspireui/support#2271]
1. My issue:
Hello, how are you
I want to buy a source code application
This is exactly the same this  (  https://play.google.com/store/apps/details?id=kuwait.yahaal  ) 
This app is made by you
Can you tell me what his name is or send me the application link in order to buy it and thank you

2. Screenshots issues (required):
3. Proof of my purchased (required):
9e83ec40-8414-4b23-960d-0b69d207dd89
3. Config files (required)

**Comment by khaledsalama32** [comment]
@minhcasi    Hello, how are you
I want to buy a source code application
This is exactly the same this ( https://play.google.com/store/apps/details?id=kuwait.yahaal )
This app is made by you
Can you tell me what his name is or send me the application link in order to buy it and thank you

**Comment by minhcasi** [comment]
@khaledsalama32 - please check this product - https://codecanyon.net/item/fluxstore-the-universal-woocommerce-magento-opencart-mobile-app-by-flutter-framework/24020929

It seems that app is customized from our customer but is use our original Fluxstore for the customization

**Comment by khaledsalama32** [comment]
That is mein , he is using the fluxstore pro application and has modified it.
I just want the application in the example :https://play.google.com/store/apps/details?id=kuwait.yahaal
Is the application in the link is an application (fluxstore pro )
