### ISSUE TITLE
Fluxstore listing app installation

### ISSUE THREAD

**Issue by pwcreativemarketing** [inspireui/support#2272]
Hello support,

I have the Listingpro Wordpress theme & the Fluxstore listing app template for Flutter.

I am following the YouTube tutorial - https://www.youtube.com/watch?v=FWhgiji7Z-Q

But I am having issues. I am up to 0:40 on the video. I am using Android Studio and I have received this message/....

Launching lib/main.dart on iPhone in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: S9RPAM8224
Running Xcode build...
Xcode build done.                                            5.2s
Failed to build iOS app
Error output from Xcode build:
↳
    2020-03-03 13:41:30.638 xcodebuild[50294:3968378]  DTDeviceKit: deviceType from 56427da3008957f2fa3429cb1220a4fe5109827e was NULL
    2020-03-03 13:41:30.780 xcodebuild[50294:3968382]  DTDeviceKit: deviceType from 56427da3008957f2fa3429cb1220a4fe5109827e was NULL
    ** BUILD FAILED **

Xcode's output:
↳
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    Code Signing Error: No profiles for 'com.inspireui.mstore.flutter' were found:  Xcode couldn't find any iOS App Development provisioning profiles matching 'com.inspireui.mstore.flutter'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild.
    Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 13.2'
    Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 13.2'
    Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 13.2'

Could not build the precompiled application for the device.

Error launching application on iPhone.

(I have also attached screenshot)

Please can you help me with the set up of this template. I thought it was going to be an easy process considering it says 'Build the Fluxstore listing app in 5 minutes'

Thank you

<img width="1440" alt="Screenshot 2020-03-03 at 13 51 29" src="https://user-images.githubusercontent.com/61735638/75777383-2fdffb00-5d56-11ea-8e9f-19d87b454bf4.png">

---------

1. My issue:

2. Screenshots issues (required):

3. Proof of my purchased (required):

3. Config files (required)

**Comment by philipvu30** [comment]
Hi @pwcreativemarketing ,
Thank you for purchasing our product. Please follow the instruction below to solve your problem.
1. Please open the project with the xcode tool. You can find it in the ios folder as the following image
<img width="762" alt="1" src="https://user-images.githubusercontent.com/54442328/75839419-5efc7800-5dfb-11ea-888f-6d01664eca43.png">

2. Please navigate to the general tab, then make sure everything is the same as the image except for the "team" section. Here you need an apple account(free also ok) and assign it to the project.
<img width="1141" alt="2" src="https://user-images.githubusercontent.com/54442328/75839542-9ec35f80-5dfb-11ea-991a-6e050b8d6c57.png">

**Comment by pwcreativemarketing** [comment]
Hello,

That did not work. Please see attached errors.

Is there something I have missed? 

Thank you for your help

<img width="1440" alt="Screenshot 2020-03-04 at 08 18 24" src="https://user-images.githubusercontent.com/61735638/75854539-c3fea080-5df0-11ea-815b-ca1d732775e4.png">

<img width="1440" alt="Screenshot 2020-03-04 at 08 16 34" src="https://user-images.githubusercontent.com/61735638/75854474-9d406a00-5df0-11ea-8f04-07c0fd874ce0.png">

**Comment by philipvu30** [comment]
Hi @pwcreativemarketing ,
Please replace this file 
[banner_map.zip](https://github.com/inspireui/support/files/4285802/banner_map.zip) 
in lib/widgets/home/banner/banner_map.dart
And make sure you have changed icon, app name, bundle id according to this doc: [Change bundle ID](https://docs.inspireui.com/fluxstore/customization/).
Thank you

**Comment by pwcreativemarketing** [comment]
Hello,

Its still showing messages. I'm not sure how to replace the file properly or set up using android studio. I do not have developer experience. 

Do you have an alternative way? Can you install for me?

**Comment by philipvu30** [comment]
Sure. Please contact me on Skype: vuthanhtoan30

**Comment by pwcreativemarketing** [comment]
Great :) Thank you. I have just sent you a Skype message.
