### ISSUE TITLE
[fluxStore magento] - 

### ISSUE THREAD

**Issue by taryaalo** [inspireui/support#2273]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
i have issue when start the project 
Running "flutter pub get" in source...                          
Because flutter_widgets <0.1.6-dev.1 depends on intl ^0.15.2 and fstore depends on intl 0.16.1, flutter_widgets <0.1.6-dev.1 is forbidden.

2. Screenshots issues (required):

![Capture1](https://user-images.githubusercontent.com/26363734/75791935-f919dd00-5d75-11ea-843d-55cf670b203f.PNG)

![Capture2](https://user-images.githubusercontent.com/26363734/75792034-151d7e80-5d76-11ea-9762-f24cb935654c.PNG)

3. Proof of my purchased (required):
![Capture](https://user-images.githubusercontent.com/26363734/75791806-c839a800-5d75-11ea-8d58-968220377ee3.PNG)

3. Config files (required)

**Comment by minhcasi** [comment]
@taryaalo - pls try to update the pubspec.yaml and change this code: `flutter_widgets: 0.1.11`

Also update the flutter to the stable channel, using dev channel is not recommended 
```
flutter channel stable
flutter update
```
