### ISSUE TITLE
[FluxStore-woo 1.6.4] - mstore-api This plugin has been closed

### ISSUE THREAD

**Issue by EdelcioBatista** [inspireui/support#2274]
Hi.

I am in "8. Currency Switcher" ( https://docs.inspireui.com/fluxstore/customization/ ).

In "https://wordpress.org/plugins/mstore-api/": 

This plugin has been closed as of February 21, 2020 and is not available for download. This closure is temporary, pending a full review.

Can you help me?

Proof of purchase:
6b4b9df0-0ac5-472b-8e05-7a7f32b607cf

Thank you.

**Comment by dured007** [comment]
Hi @EdelcioBatista 

I'm not from the support team but the plugin is available in the file you get when downloading the source code files.

Also, it's available on https://wordpress.org/plugins/mstore-api/ 
it was under review but it's available to download now.

**Comment by minhcasi** [comment]
@EdelcioBatista - it's backed now after pass the security checking from Wordpress team - https://wordpress.org/plugins/mstore-api/

**Comment by itspathanofficial** [comment]
> Hi.
> 
> I am in "8. Currency Switcher" ( https://docs.inspireui.com/fluxstore/customization/ ).
> 
> In "https://wordpress.org/plugins/mstore-api/":
> 
> This plugin has been closed as of February 21, 2020 and is not available for download. This closure is temporary, pending a full review.
> 
> Can you help me?
> 
> Proof of purchase:
> 6b4b9df0-0ac5-472b-8e05-7a7f32b607cf
> 
> Thank you.

Are selling your mstore api plugin? I want to buy it.
