### ISSUE TITLE
Issue with RazorPay

### ISSUE THREAD

**Issue by masabi89** [inspireui/support#2275]
hi, I'm having trouble running the app on the iOS simulator, even my iphone, using Android Studio. When I run the code, it show some errors. I've attached a screenshot of it.

<img width="1003" alt="Screen Shot 2020-03-03 at 21 52 47" src="https://user-images.githubusercontent.com/61755671/75809463-db5e6f00-5d99-11ea-8020-0d16fc17a62e.png">
<img width="575" alt="Screen Shot 2020-03-03 at 21 47 57" src="https://user-images.githubusercontent.com/61755671/75809475-df8a8c80-5d99-11ea-8f8a-6579123a060c.png">

**Comment by minhtruong315** [comment]
@masabi89 Do you have AnyDesk? I will access your mac to check

**Comment by masabi89** [comment]
yes I do, what's the best time to contact ?

**Comment by masabi89** [comment]
can you contact me on a.masabi [at] hotmail.com, so we can arrange a time, thanks

**Comment by minhcasi** [comment]
@minhtruong315 - pls keep the update - thanks

**Comment by minhtruong315** [comment]
@masabi89 can u add my skype: minhtruong315. I will help u check it remotely. Thanks

**Comment by minhcasi** [comment]
@masabi89  - let me know if you have any feedback - thank you!
