### ISSUE TITLE
[FluxStore-woo 1.6.4] - Deeplink

### ISSUE THREAD

**Issue by EdelcioBatista** [inspireui/support#2276]
Hi,

About Deep Link:

I am following the instructions, see:

"
edelcio@inspiron:~$ **adb shell 'am start -W -a android.intent.action.VIEW -c android.intent.category.BROWSABLE -d "fluxstore://inspireui.com/400" '**

Command 'adb' not found, but can be installed with:

sudo apt install adb

**edelcio@inspiron:~$ sudo apt install adb**
"

after:

"
**edelcio@inspiron:~$ adb shell 'am start -W -a android.intent.action.VIEW -c android.intent.category.BROWSABLE -d "fluxstore://inspireui.com/400" '**
adb server version (41) doesn't match this client (39); killing...
ADB server didn't ACK
Full server startup log: /tmp/adb.1000.log
Server had pid: 18517
--- adb starting (pid 18517) ---
adb I 03-03 16:25:17 18517 18517 main.cpp:57] Android Debug Bridge version 1.0.39
adb I 03-03 16:25:17 18517 18517 main.cpp:57] Version 1:8.1.0+r23-5~18.04
adb I 03-03 16:25:17 18517 18517 main.cpp:57] Installed as /usr/lib/android-sdk/platform-tools/adb
adb I 03-03 16:25:17 18517 18517 main.cpp:57] 
adb I 03-03 16:25:17  5019  5019 transport.cpp:980] kicking transport 0x7fc1d0011d30 H1AZB600E826FW5
adb I 03-03 16:25:17  5019  5019 transport.cpp:358] BlockingConnectionAdapter(H1AZB600E826FW5): stopping
adb I 03-03 16:25:17  5019  9579 transport.cpp:286] H1AZB600E826FW5: read failed: Invalid argument
adb I 03-03 16:25:17  5019  9579 transport.cpp:695] H1AZB600E826FW5: connection terminated: read failed
adb I 03-03 16:25:17  5019  5019 transport.cpp:376] BlockingConnectionAdapter(H1AZB600E826FW5): stopped
adb I 03-03 16:25:17 18517 18517 adb_auth_host.cpp:416] adb_auth_init...
adb I 03-03 16:25:18 18517 18517 adb_auth_host.cpp:174] read_key_file '/home/edelcio/.android/adbkey'...
adb I 03-03 16:25:18 18517 18517 adb_auth_host.cpp:391] adb_auth_inotify_init...
adb I 03-03 16:25:18 18517 18517 adb_auth_host.cpp:467] Calling send_auth_response
adb server killed by remote request

*** failed to start daemon
error: cannot connect to daemon**
"

Can you help me?

Proof of purchase:
6b4b9df0-0ac5-472b-8e05-7a7f32b607cf

Thank you.

**Comment by kvt0012** [comment]
it means that your adb (android debug bridge)  has a problem, if you use Android Studio, go to file -->setting --> sdk --> sdk tool and reinstall sdk-platform. 
Btw if it's not successful, please search it on google, they have a lot of guides. 
Thank you

**Comment by EdelcioBatista** [comment]
Hi.

I'm using VS CODE.

How do you do it in VS CODE?

Tks

Em ter., 3 de mar. de 2020 às 23:33, kvt0012 <notifications@github.com>
escreveu:

**Comment by kvt0012** [comment]
You can download Android Debug Bridge on website of android studio and setting directory to this file.

**Comment by minhcasi** [comment]
@EdelcioBatista - VS is the same with Android studio if the "adb server" is running 

Also check this guide if it is useful - https://pub.dev/packages/uni_links 

Pls reopen the ticket if you still have any problem - thank you!
