### ISSUE TITLE
CeBuilder runs unstable on Mac OS  -【 Purchased Mstore Magento 2 】

### ISSUE THREAD

**Issue by 234146326** [inspireui/support#2278]
> - I keep installing Cebuilder repeatedly but I still can't log in to my account
---------
So:

1. I have been trying to unpack your latest version of Cebuilder, sorry, the file is corrupted.Can you give me a stable installation version of the stable Cebuilder.Alternatively, provide a solution that does not use CeBuilder.

**Comment by 234146326** [comment]
![Uploading image.png…]()

**Comment by 234146326** [comment]
This question is ridiculous, can technical support reply quickly? @Doan Tan Trung  @minhcasi

**Comment by 234146326** [comment]
<img width="1055" alt="11" src="https://user-images.githubusercontent.com/17285770/75861355-3b0b5780-5e38-11ea-96ae-0db1235ce492.png">

**Comment by minhcasi** [comment]
@234146326 - we will check the issue, in the meantime, you could try to verify by pasting the purchase code to skip the Login verify

**Comment by 234146326** [comment]
@minhcasi  Where to get the purchase code, please share the index.Thank you.

**Comment by 234146326** [comment]
@minhcasi enavto where to get the purchase code? I can't found it?

**Comment by minhcasi** [comment]
@234146326 - pls check this link https://help.market.envato.com/hc/en-us/articles/202822600-Where-Is-My-Purchase-Code-

**Comment by minhcasi** [comment]
Also try to update to latet 0.40.1 version - thank you!

**Comment by 234146326** [comment]
![image](https://user-images.githubusercontent.com/17285770/76140411-2d9ed900-6095-11ea-9019-a011df09a137.png)
@minhcasi  This new version cannot detect the environment。
