### ISSUE TITLE
[FluxStore Pro] - iOS build simulator

### ISSUE THREAD

**Issue by Pankti16** [inspireui/support#2279]
1. I am unable to run the app on ios simulator.

2. Screenshots issues (required): 
![Issue](https://user-images.githubusercontent.com/28388925/75857041-8cf1b480-5e1b-11ea-9864-0778c0b95cea.PNG)

3. Proof of my purchased (required):
[57524828-fluxstore-the-universal-woocommerce-magento-opencart-mobile-app-by-flutter-framework-license.pdf](https://github.com/inspireui/support/files/4285958/57524828-fluxstore-the-universal-woocommerce-magento-opencart-mobile-app-by-flutter-framework-license.pdf)

3. Config files (required)
[config.zip](https://github.com/inspireui/support/files/4285959/config.zip)

**Comment by minhcasi** [comment]
@Pankti16 - could you try this solution to clean up the cache - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1 - thank you!

**Comment by Pankti16** [comment]
Yes, I tried, but the issue still persists, thank you.

**Comment by minhcasi** [comment]
@Pankti16 - could you send us your result from 'flutter doctor' ?

**Comment by Pankti16** [comment]
It has only one error, No Connected Devices!

**Comment by minhcasi** [comment]
@Pankti16 - instead of running from XCode, could you try to run from Android Studio by clicking the build (green arrow button) - running flutter app will require to run some script to update the pub lib, pod cache... that does not handle from XCode (you could run with VS Code as well)

**Comment by Pankti16** [comment]
Okay, let you know after I try it.

**Comment by Pankti16** [comment]
There is some issue with our OS, will re-open it when it is fixed, thank you.
