### ISSUE TITLE
[ListApp] Play icon on listing places and login problem (with photos)

### ISSUE THREAD

**Issue by jacobspn** [inspireui/support#228]
- Product: [ListApp - Mylisting theme]
 - Your Purchased Code: c40eb757-33b1-4a6c-943e-ed3777feb9fc

i can only see a "play" icon where listings should be displayed.
![0](https://user-images.githubusercontent.com/44866712/51878949-e0b8e100-2371-11e9-8bfc-ee96537a4f4f.png)

and when i clik on it i have this error:
![1](https://user-images.githubusercontent.com/44866712/51879193-b0be0d80-2372-11e9-9656-0a34a0193d99.png)

I also get this error trying to login:
![2](https://user-images.githubusercontent.com/44866712/51878957-e6aec200-2371-11e9-8159-a83f8e7f2c90.png)

**Comment by thangvo9x** [comment]
@jacobspn

**Comment by jacobspn** [comment]
i followed the steps before y posted this message i also realised that i dont have the Auth option to activate in JSON API settigs

![captura](https://user-images.githubusercontent.com/44866712/51987304-7784bb00-24a2-11e9-96d4-94a3ce811dd5.PNG)

I sent you an email with the files you need and also access to my wordpress. Thanks for your time and help.

**Comment by jacobspn** [comment]
@thangvo9x

**Comment by thangvo9x** [comment]
Hi. I received your email. Please wait for me to testing && integrating. 
Thanks

**Comment by thangvo9x** [comment]
Hi. I checked your source. Please update your Config with MyListing.js in it. or simple, you can using ceBuilder at https://inspireui.com/
Thanks

**Comment by jacobspn** [comment]
Im not sure what you mean with "update your Config with MyListing.js in it"
You mean to just copy the content of MyListing.js in my Confij.json file?

**Comment by jacobspn** [comment]
this is the structure i have

![captura png2](https://user-images.githubusercontent.com/44866712/52095665-2a990580-25c4-11e9-9836-f99048c2302a.PNG)

I have done the installation with cbuilder and everything was configured.

**Comment by thangvo9x** [comment]
Yes. My mean is you must have change categoryListingId in MyListing.js with name horizontalLayout

**Comment by jacobspn** [comment]
okey i solve problem but then i realised cover image was missig:

![screenshot_2019-02-02-22-48-23-500_com inspireui listapp mylisting](https://user-images.githubusercontent.com/44866712/52169718-66a3a600-273d-11e9-889b-23cc353b675e.png)

Then i discovered that i can solve it by adding the feature image each listing:

![5](https://user-images.githubusercontent.com/44866712/52169721-702d0e00-273d-11e9-9cdf-fe9d4f0f3418.PNG)

But also i reaised that is stupid, cos only admin can add featured image to lisitngs... that means that if user upload a listing to the web or app, main image will be missing and i tosolve it, i have to manually upload one for it. is it right? cos seems to be like this

- When im looking a single listing on app and press the heart to add to my favorites app stops
- When trying to opload a isting after finish 1st step and go to second, app stops
- when on my profile it doesnt get the listing i have uploaded and appear to be 0 listing (but ihave 18)
-map doesnt display listing
- if i go to category section after press a category with 13 listings nothing appear

Any help pls

**Comment by jacobspn** [comment]
i solve problems with map and some others, seem that when a lisitng has a review it cant be displayed on the app. Can you help me with some issues pls? @thangvo9x

**Comment by thangvo9x** [comment]
Yes. The reviews can't be displayed on your app? i'll check it. @jacobspn

**Comment by thangvo9x** [comment]
Hi, you can approve that comment to display it.
