### ISSUE TITLE
Fluxstore Multilanguage Error

### ISSUE THREAD

**Issue by ahmetozcan9211** [inspireui/support#2280]
Hi. i have an issue about adding language. i follow your guide and add new language file with named intl_tr.arb for turkish language.when i save my file Flutter intl working with theese errors. help me pls

here is log:

```
INFO: No @@locale or _locale field found in intl_ar, assuming 'ar' based on the file name.
INFO: No @@locale or _locale field found in intl_en, assuming 'en' based on the file name.
INFO: No @@locale or _locale field found in intl_es, assuming 'es' based on the file name.
INFO: No @@locale or _locale field found in intl_ja, assuming 'ja' based on the file name.
INFO: No @@locale or _locale field found in intl_tr, assuming 'tr' based on the file name.
ERROR: Failed to generate localization files.
pub finished with exit code 2
Process finished with exit code 2
```

**Comment by minhcasi** [comment]
Hi, thank you for the feedback. Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads it's used to verify your proof of purchase? sorry for any inconvenience - Thank you!

**Comment by ahmetozcan9211** [comment]
Here my screenshot. If you want i can add my purchase code 
![IMG-20200305-WA0015](https://user-images.githubusercontent.com/9422532/75962323-9b4fd700-5ed4-11ea-8e45-3004ffe545eb.jpg)

**Comment by ahmetozcan9211** [comment]
> Hi, thank you for the feedback. Could you help to share the screenshot of the purchase screenshot from [http://codecayon.net/downloads it's](http://codecayon.net/downloads%C2%A0it's) used to verify your proof of purchase? sorry for any inconvenience - Thank you!

**Comment by minhcasi** [comment]
@ahmetozcan9211 - pls check the 13.2 guide to update the plugin to fix the issue - https://medium.com/@inspireui/announcing-fluxstore-1-6-337efff1791f

**Comment by ahmetozcan9211** [comment]
really? did you read my message? i already said to you "i floow to guide and create file to lib/l10n folder for turkish language with named intl_tr. i have latest flutter intl plugin. but when i add language file  it isnt generate messages_tr.dart or another thing. here is details log for i sent for dart git issue. check it pls
https://github.com/dart-lang/intl/issues/267 

and i adding screen shot here. you can see i create my  langugae translation. 
![Adsız](https://user-images.githubusercontent.com/9422532/76068783-dae4f480-5fa2-11ea-80cc-a10267bf0597.png)

and my logcat for translate below: 

i cant generate locale files
here is my command output is below
```
flutter --no-color pub global run intl_utils:generate


INFO: No @@locale or _locale field found in intl_ar, assuming 'ar' based on the file name.
INFO: No @@locale or _locale field found in intl_en, assuming 'en' based on the file name.
INFO: No @@locale or _locale field found in intl_es, assuming 'es' based on the file name.
INFO: No @@locale or _locale field found in intl_ja, assuming 'ja' based on the file name.
INFO: No @@locale or _locale field found in intl_tr, assuming 'tr' based on the file name.
ERROR: Failed to generate localization files.
pub finished with exit code 2
Process finished with exit code 2
```

and here is with verbose
```
flutter --no-color pub global run intl_utils:generate -v

INFO: No @@locale or _locale field found in intl_ar, assuming 'ar' based on the file name.
INFO: No @@locale or _locale field found in intl_en, assuming 'en' based on the file name.
INFO: No @@locale or _locale field found in intl_es, assuming 'es' based on the file name.
INFO: No @@locale or _locale field found in intl_ja, assuming 'ja' based on the file name.
INFO: No @@locale or _locale field found in intl_tr, assuming 'tr' based on the file name.
ERROR: Failed to generate localization files.
pub finished with exit code 2

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      _DefaultPub.interactively (package:flutter_tools/src/dart/pub.dart:323:7)
<asynchronous suspension>
#2      PackagesForwardCommand.runCommand (package:flutter_tools/src/commands/packages.dart:241:15)
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:615:18)
#4      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#5      _rootRunUnary (dart:async/zone.dart:1134:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#9      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#10     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#11     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#12     _rootRun (dart:async/zone.dart:1126:13)
#13     _CustomZone.run (dart:async/zone.dart:1023:19)
#14     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#18     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```


C:\Users\4ahme\Desktop\1\source>flutter doctor -v
```
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18362.356], locale tr-TR)
    • Flutter version 1.12.13+hotfix.8 at C:\flutter
    • Framework revision 0b8abb4724 (3 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\4ahme\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.42.1)
    • VS Code at C:\Users\4ahme\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1
```


> @ahmetozcan9211 - pls check the 13.2 guide to update the plugin to fix the issue - https://medium.com/@inspireui/announcing-fluxstore-1-6-337efff1791f
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/1f55d85bfc898e06f175857fb52934c71284d708/68747470733a2f2f6d69726f2e6d656469756d2e636f6d2f6d61782f313230302f312a7577347776547456575f44434261536b4f6c47786d512e6a706567"><img alt="" height="14" src="https://camo.githubusercontent.com/a1c598ee8610a8cdb0e8bdbf112f3f1c77af25cb/68747470733a2f2f63646e2d7374617469632d312e6d656469756d2e636f6d2f5f2f66702f69636f6e732f66617669636f6e2d72656272616e642d6d656469756d2e33593678705a2d3046536457446e504d3368534249412e69636f"> Medium**[Announcing Fluxstore 1.6](https://medium.com/@inspireui/announcing-fluxstore-1-6-337efff1791f)**Latest update 14/12/2019

**Comment by minhcasi** [comment]
@ahmetozcan9211 - note with investigating 

@trunghieuvn - pls check this issue

**Comment by trunghieuvn** [comment]
This error is caused by the same keyword or an arb file format error. 
To check the arb file for accuracy, please follow these steps:

Step 1: Open the .arb file to check with Visual Code
Step 2: In the bottom right corner, choose change format (as shown in the following picture, the current format is doing FlanText)
Step 3: Find and select JSON format

![image](https://user-images.githubusercontent.com/19247680/76187449-f3a21400-6207-11ea-8e3c-ef383baec066.png)

Step 4: check the file. You can find bugs quickly by looking at the preview feature (to the right of the visual code), with a yellow dash indicating duplicate data, a red dash indicating an error.

![image](https://user-images.githubusercontent.com/19247680/76187571-41b71780-6208-11ea-8c40-db8051f7c952.png)

**Comment by minhcasi** [comment]
@ahmetozcan9211 - would you mind sharing this language file so that we will include it as officially from the app - we are working on a new script to help to add/remove language easier - thank you!

**Comment by sketchuprzr** [comment]
I applied the edit. Currently worked. Thank you. I will review the application in detail and return again.

You can give me your skype address.

We do not prefer skype in Europe.
In Western Europe, Discdord is generally used for such situations. I can recommend it to you.

I downloaded skype right now. I just had to use it for you.
