### ISSUE TITLE
Update Profile not working - flutter - wordpress

### ISSUE THREAD

**Issue by ranapiyush1986** [inspireui/support#2281]
> - Plz click on this API :
https://bit.ly/3cy4AAf

I am not able to find this api in mstore. But it's used in flutter app - WordPress
Issue : update profile not working.

![75575075-777c3380-5a85-11ea-9d5e-824a671df4ea](https://user-images.githubusercontent.com/18486814/75869695-f4b1fa80-5e2f-11ea-8563-717aa594e12f.png)

---------

1. My issue:

2. Screenshots issues (required):

3. Proof of my purchased (required):

3. Config files (required)

**Comment by minhcasi** [comment]
@ranapiyush1986 - could I know if you have updated the mstore-api library to latest version  https://wordpress.org/plugins/mstore-api/ - thank you!
