### ISSUE TITLE
[Fluxnews] Need feedback on production App

### ISSUE THREAD

**Issue by aldoyh** [inspireui/support#2282]
Hello guys,

Just wanted to share my new born App in live stores.. great experience with Fluxnews!!
I specifically need to test "Sign in with Apple".

We Horse Racing 
https://onelink.to/wehorseracing 

One issue remains, I've completely lost the fonts style and couldn't find it anywhere!?

**Comment by minhcasi** [comment]
Hi, it's located from common/styles.dart

**Comment by minhcasi** [comment]
Congratulation to delivery to Appstore successful, our team will have a look and give you some 5* rating on Appstore ;)

**Comment by aldoyh** [comment]
Hello, I can't find it, can you please guide me to line number?

[styles.dart.zip](https://github.com/inspireui/support/files/4306984/styles.dart.zip)

**Comment by aldoyh** [comment]
One is the "Sign in with Apple" working with anyone from your team?
