### ISSUE TITLE
[FluxStore] - New version products issue

### ISSUE THREAD

**Issue by UTimung** [inspireui/support#2283]
soo much problems in new version

in products horizontal slider if click on SEE ALL

all products are not showing
in some category it shows only 7 -10 products  maximum

previous version works well
but new version more bugs

**Comment by themeix** [comment]
I found a solution for that in my app. 
https://i.postimg.cc/Bn55Zdjx/screenshot-632.png
onesale and featured endpoint causing that issue

**Comment by minhcasi** [comment]
moved to email support - we are checking the source sent from email and let you know - thanks

**Comment by trunghieuvn** [comment]
Please check the list of categories using the API with the following url:

```
https://example.com/wp-json/wc/v2/products/categories?exclude=311&per_page=100&page=1&consumer_key=[consumer_key]&consumer_secret=[consumer_secret]
```

Then check in the config_en.json file the configuration parameters for the category ID.
When you run the app with our config, the result should look like this:

```
For `Woman Collections` category ID is 22
For `Man Collections` category ID is 21
For `New Collections` category ID is 29
```
