### ISSUE TITLE
FluxStorePro - Error After Splash Screen

### ISSUE THREAD

**Issue by saidbakkou** [inspireui/support#2284]
didn t change anything on the code from yesterday and today i got this issue could u help please !
![fef](https://user-images.githubusercontent.com/59389664/75897604-1a8fcd00-5e39-11ea-96ad-d91a0afba7ee.png)

**Comment by minhcasi** [comment]
Hi, thank you for the feedback. Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads it's used to verify your proof of purchase? sorry for any inconvenience - Thank you!

**Comment by saidbakkou** [comment]
![86183753_197529808291854_4776660982191620096_n](https://user-images.githubusercontent.com/59389664/75968768-36917e00-5ece-11ea-960d-21b0fad53778.jpg)

**Comment by saidbakkou** [comment]
@minhcasi

**Comment by trunghieuvn** [comment]
@saidbakkou sai
please send me file config.dart and config_en.json use from you

**Comment by saidbakkou** [comment]
@trunghieuvn  i didn t made any changes yet on those files

**Comment by saidbakkou** [comment]
[here is the files.zip](https://github.com/inspireui/support/files/4293647/here.is.the.files.zip)
 @trunghieuvn  i didn t made any changes yet on these files !

**Comment by trunghieuvn** [comment]
Hi @saidbakkou , to fix this error, please change `throw e;` to `return null;`.

![image](https://user-images.githubusercontent.com/19247680/76182476-9e5e0680-61f7-11ea-9a0e-84ae6c4f0ae8.png)
