### ISSUE TITLE
Can't Install Chocolatey for installing MStore Pro

### ISSUE THREAD

**Issue by ario99-ap** [inspireui/support#2285]
Hello,

I have a difficulties to install chocolatey both by using cmd or powershell. It always showing error such as “method invocation exception” which use to complete the tools required. How to fix it, so i can complete the tools required by the app ?

![1](https://user-images.githubusercontent.com/61795267/75898023-17620480-5e6c-11ea-8b85-91df5e7e8087.png)
![2](https://user-images.githubusercontent.com/61795267/75898044-1d57e580-5e6c-11ea-9232-a05995a8bbf9.png)

**Comment by ario99-ap** [comment]
Hello,

Please help me to fix this problem so i can install the apps.

![3](https://user-images.githubusercontent.com/61795267/75898432-9f480e80-5e6c-11ea-9c91-0a8c5621b28d.png)

**Comment by ario99-ap** [comment]
![1](https://user-images.githubusercontent.com/61795267/75900695-e388de00-5e6f-11ea-8355-11befaaa7723.png)

**Comment by minhcasi** [comment]
@ario99-ap - could you help to install it manually on this link https://chocolatey.org/docs/installation - thank you!
