### ISSUE TITLE
[Fluxstore Woo-commerce] Affiliate Compatible Error !

### ISSUE THREAD

**Issue by peter2411** [inspireui/support#2286]
My issue:

my store contains a affiliate products , my app was using "FluxStore-woo 1.4.3" and it was working fine and the webview was correctly showing the webpage after click add to cart , now when i trying to update the app with fluxstore "Version: 1.6.4" with the same "Server config" when i click on add to cart it's continue to complete purchase via the app !!

Proof of my purchased :

https://prnt.sc/rbkq5b

**Comment by minhcasi** [comment]
@peter2411 - could you help to attache your common and config folder to that we could help for checking - thank you!

**Comment by minhcasi** [comment]
pls let us know if you have any feedback and reopen the ticket  - thank you!
