### ISSUE TITLE
Fluxstore MV questions

### ISSUE THREAD

**Issue by HumerCode** [inspireui/support#2287]
Hi, i have few questions for now, please respond.

1) I purchased version 1.6.3 , now there is 1.6.4, how to update to new version?? i dont want to start over again modifying files, and later new version will come out so it is time consuming, to again modify settings,icons,pictures,json and else.
Do you have solution? over GIT maybe? if yes how to?

2) How to replace YOUR spinner,on pull refresh, so i want to insert my spinner in app,not your logo.
I'm talking about spinner that comes when switching from categories or blog or else...

MY code of purchase (I will cut some last numbers):
3773b257-5a04-4b17-9c21-e092cbed****

**Comment by minhcasi** [comment]
@HumerCode - could you help to quick take screenshot from http://codecayon.net/downloads - we could not verify the purchase without complete number :)

**Comment by HumerCode** [comment]
He
![1](https://user-images.githubusercontent.com/46302866/75943680-f9a99500-5e95-11ea-9ed2-7ad68cfe4573.png)
re you go.

**Comment by antixirus** [comment]
I need answer

**Comment by antixirus** [comment]
Same question with me

**Comment by HumerCode** [comment]
Any updates?

**Comment by minhcasi** [comment]
@HumerCode - pls send this request to access to the git repo to track the file change for each version upgrade - https://docs.google.com/forms/d/e/1FAIpQLSeuBqUkScy42V7KKhfNPj0fl581anrB1mWkbMa3p2WQt7fhfw/viewform

The spinkit could be change dfrom common/constants.dart file: 

<img width="830" alt="Screen Shot 2020-03-06 at 14 17 50" src="https://user-images.githubusercontent.com/1459805/76061060-459f2b80-5fb5-11ea-88f9-7fe6e181d2e9.png">

**Comment by HumerCode** [comment]
Ok, submitted info.

**Comment by minhcasi** [comment]
Thank you, the team will be sorted our quickly the invitation today - thank you!
