### ISSUE TITLE
[Fluxstore - Woo] - Onesignal İOS Problem "apns" 

### ISSUE THREAD

**Issue by sketchuprzr** [inspireui/support#2288]
![image](https://user-images.githubusercontent.com/60021696/75934481-ae8b8400-5e8d-11ea-9069-1b6dfd021aea.png)

With Xcode, we released the application as texfly.

I made all the certificates. But despite the user coming to onesginal, such an error is displayed.

How can I solve this?

App for ios version : 10.2

![image](https://user-images.githubusercontent.com/60021696/75934582-f3171f80-5e8d-11ea-875a-26f6122d5140.png)

**Comment by minhcasi** [comment]
@sketchuprzr - could you help to move your all issues to this ticket  #2294 - thank you!
