### ISSUE TITLE
[Fluxstore Woocommerce] - There is an error while checkout in shipping method

### ISSUE THREAD

**Issue by Justnopeople** [inspireui/support#2289]
There is an error while checkout in shipping method

![image](https://user-images.githubusercontent.com/49190031/75943749-75243a00-5ec8-11ea-8752-094b2f93a7a3.png)

i think this happening because i have additional plugin for get price specific in my country and get good price from several couriers, and i need the solution about this. What must i do?
Only this is my problem for the whole everything is fine.

Proof of my purchased :
![image](https://user-images.githubusercontent.com/49190031/75944181-9a657800-5ec9-11ea-96d5-419c61c6da0b.png)

**Comment by minhcasi** [comment]
@Justnopeople - could i know which the plugin that you installed for the shipping feature - please note that it may not work on app as the default Fluxstore only support for the original WooCommerce Rest API - adding more plugin need to customize the API to make it work - thank you!
