### ISSUE TITLE
[MStore] Product Variation and Product Search and Product Category issue.

### ISSUE THREAD

**Issue by Ghostfring** [inspireui/support#229]
**Required Info (please complete the following information):**
 - Product: MStore
 - Your Purchased Code: e93d8750-3488-4b31-8c06-030c95a8c83f

Bug 1

On the product page, all my products are having too many attributes to select from (which are not suppose to be there). In the below Image you can find that all the additional information/specification about my products are also beings displayed as a variation selector. I would want to rectify that but I am unable to find where to edit it

![screenshot_2019-01-29-10-47-44-98](https://user-images.githubusercontent.com/47133512/51886851-77f45780-23b7-11e9-977b-be6672e88a76.png)

Bug 2

Here you can find when I try to search for rings, I am getting the results for watches instead.

![screenshot_2019-01-29-10-51-30-13](https://user-images.githubusercontent.com/47133512/51886863-817dbf80-23b7-11e9-98bc-57763f09fa67.png)

Bug 3

I have 3 levels of category i.e. Parent Category, sub-category of the Parent Category and sub-category of the sub-category. But in the side menu and category selector on catalog page I can only find 2 levels of category i.e. Parent Category and the sub-category of the Parent Category.

![screenshot_2019-01-29-11-13-47-44](https://user-images.githubusercontent.com/47133512/51886868-86db0a00-23b7-11e9-8fd8-5d3dcfc4c894.png)

I have spent tireless amount of time in trying to figure it out that where do I need to make changes but I couldn't I would kindly request for some help here

**Comment by luyx2412** [comment]
Hi @Ghostfring 
- You can edit the variant in `src/containers/Detail/index.js` line 556 `attribute.options` is the list variant.
![2019-01-29_22-03-32](https://user-images.githubusercontent.com/8909619/51917356-f67de300-2411-11e9-8036-2bc388224944.png)

- You can use the Reactotron or react-native-debugger in `Constants.js` file. I suggest you use Reactotron which is easier than react-native-debugger. https://github.com/infinitered/reactotron
![2019-01-29_22-05-59](https://user-images.githubusercontent.com/8909619/51917432-1f9e7380-2412-11e9-8c79-a5b23f8f11b5.png)

- Currently we did not support sub-category, you can edit in `src/components/Drawer/DrawerMultiChild/index.js` file.

Thanks

**Comment by vishu-mangla** [comment]
i am also getting all attribute on screen. 
let say i have 10 attribute out of which i only use 2 attribute for variation.
only that 2 attribute should be show on screen instead on all.
in my website it showing only 2 attribute but in app it showing all
please help me
and also when i run it though expo in android emulator and when i shake ,it does not show option of menu.
i want to live reload and debug things
but shaking does not do anything
in my other projects shaking is working but not working on mstore
