### ISSUE TITLE
[FLUXSTORE MV] - Error after edit Config.json

### ISSUE THREAD

**Issue by antixirus** [inspireui/support#2290]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: Error after im update config.json

2. Screenshots issues (required):
![gambar](https://user-images.githubusercontent.com/57300649/75945427-cafae100-5ecc-11ea-88d2-aabccc73eeb0.png)

3. Proof of my purchased (required):
![gambar](https://user-images.githubusercontent.com/57300649/75945500-ff6e9d00-5ecc-11ea-8363-ca2f718d4542.png)

3. Config files (required)
{
  "Background": {
    "height": 0.3,
    "color": "#fbb110",
    "image": "https://sangkek.co.id/wp-content/uploads/2020/01/FLASH-BANNER.jpg"
  },
  "HorizonLayout": [
    {
      "layout": "logo",
      "showMenu": true,
      "showSearch": true,
      "hideLogo": true,
      "isSafeArea": true
    },
    {
      "layout": "header_text",
      "fontSize": 23.0,
      "height": 0.11,
      "padding": 30.0,
      "rotate": [
        ""
      ],
      "type": "fade"
    },
    {
      "layout": "header_search",
      "text": "Lagi butuh apa hari ini?"
    },
    {
      "layout": "bannerImage",
      "isSlider": true,
      "autoPlay": false,
      "showNumber": false,
      "design": "default",
      "showBackGround": true,
      "radius": 2.0,
      "height": 0.15,
      "items": [
        {
          "category": 81,
          "image": "https://sangkek.co.id/wp-content/uploads/2020/01/GRATIS-ONGKIR1.jpg",
          "padding": 15.0
        },
        {
          "category": 81,
          "image": "https://sangkek.co.id/wp-content/uploads/2020/01/FLASH-SALE.png",
          "padding": 15.0
        },
        {
          "category": 60,
          "image": "https://sangkek.co.id/wp-content/uploads/2020/01/FLASH-SALE-CABE.jpg",
          "padding": 15.0
        },
        {
          "category": 82,
          "image": "https://sangkek.co.id/wp-content/uploads/2020/01/RESERVASI.png",
          "padding": 15.0
        },
        {
          "category": 77,
          "image": "https://sangkek.co.id/wp-content/uploads/2020/01/ROTI-GEDANG.jpg",
          "padding": 15.0
        },
        {
          "category": 110,
          "image": "https://sangkek.co.id/wp-content/uploads/2020/01/MAKAN-SIANG.jpg",
          "padding": 15.0
        }
      ]
    },
    {
      "layout": "category",
      "type": "icon",
      "wrap": true,
      "size": 1.2,
      "radius": 50.0,
      "noBackground": true,
      "columns": 4,
      "padding": 10.0,
      "items": [
        {
          "category": 52,
          "image": "https://sangkek.co.id/wp-content/uploads/2020/01/cate11.png",
          "colors": [
            "#3CC2BF",
            "#3CC2BF"
          ],
          "originalColor": true
        },
        {
          "category": 79,
          "image": "https://sangkek.co.id/wp-content/uploads/2020/01/cate22.png",
          "colors": [
            "#3E6AB5",
            "#3E6AB5"
          ],
          "originalColor": true
        },
        {
          "category": 56,
          "image": "https://sangkek.co.id/wp-content/uploads/2020/01/cate33.png",
          "colors": [
            "#53A2CC",
            "#53A2CC"
          ],
          "originalColor": true
        },
        {
          "category": 57,
          "image": "https://sangkek.co.id/wp-content/uploads/2020/01/cate44.png",
          "colors": [
            "#53688A",
            "#53688A"
          ],
          "originalColor": true
        },
        {
          "category": 77,
          "image": "https://sangkek.co.id/wp-content/uploads/2020/01/cate55.png",
          "colors": [
            "#43506A",
            "#43506A"
          ],
          "originalColor": true
        },
        {
          "category": 82,
          "image": "https://sangkek.co.id/wp-content/uploads/2020/01/cate99.png",
          "colors": [
            "#12B58C",
            "#12B58C"
          ],
          "originalColor": true
        },
        {
          "category": 113,
          "image": "https://sangkek.co.id/wp-content/uploads/2020/02/samsung1.png",
          "colors": [
            "#3CC2BF",
            "#3CC2BF"
          ],
          "originalColor": true
        },
        {
          "category": 73,
          "image": "https://sangkek.co.id/wp-content/uploads/2020/02/oppo.png",
          "colors": [
            "#3E6AB5",
            "#3E6AB5"
          ],
          "originalColor": true
        }
      ]
    },
    {
      "name": "Terakhir Dilihat",
      "layout": "recentView"
    },
    {
      "name": "Promo Bulan Ini",
      "image": "",
      "layout": "threeColumn",
      "isSnapping": true,
      "category": 85
    },
    {
      "name": "Makan cuma 10rb",
      "image": "",
      "layout": "threeColumn",
      "isSnapping": true,
      "category": 110
    },
    {
      "layout": "bannerImage",
      "items": [
        {
          "url": "https://www.instagram.com/sangkek.id/",
          "image": "https://sangkek.co.id/wp-content/uploads/2020/01/Follow-Sangkek.jpg",
          "padding": 5.0
        },
        {
          "url": "https://www.instagram.com/sangkek.id/",
          "image": "https://sangkek.co.id/wp-content/uploads/2020/01/Free-Delivery.jpg",
          "padding": 5.0,
          "featured": true
        }
      ]
    },
    {
      "name": "Artikel",
      "layout": "blog"
    }
  ],
  "Setting": {
    "MainColor": "#fbb110",
    "ProductListLayout": "list"
  },
  "TabBar": [
    {
      "layout": "home",
      "icon": "assets/icons/tabs/icon-home.png"
    },
    {
      "layout": "category",
      "categoryLayout": "card",
      "icon": "assets/icons/tabs/icon-category.png"
    },
    {
      "layout": "search",
      "icon": "assets/icons/tabs/icon-search.png"
    },
    {
      "layout": "cart",
      "icon": "assets/icons/tabs/icon-cart2.png"
    },
    {
      "layout": "profile",
      "icon": "assets/icons/tabs/icon-user.png"
    }
  ]
}

**Comment by minhtruong315** [comment]
@antixirus can u send me config.json and config.dart file?

**Comment by antixirus** [comment]
@minhtruong315 Yes, sure sir, you can check in Skype

**Comment by minhtruong315** [comment]
I run your config. it's working well
https://tppr.me/YwTka
Did you edit config_en.json?

**Comment by antixirus** [comment]
But in my computer just Blank Screen.

Can you help me in Team Viewer sir?

**Comment by minhtruong315** [comment]
I messaged you on the skype

**Comment by antixirus** [comment]
Great service @minhtruong315 Issue Closed!
