### ISSUE TITLE
[fluxstore] - color not appear for products - all colors appear white

### ISSUE THREAD

**Issue by limitlessfirm** [inspireui/support#2291]
1. My issue: color not appear for products - all colors appear white

2. Screenshots issues (required):
<img width="270" alt="color-002" src="https://user-images.githubusercontent.com/59250639/75952771-5b7af680-5eb8-11ea-8963-8cea3a41761f.png">

3. Proof of my purchased (required):
![screenshot](https://user-images.githubusercontent.com/59250639/75952781-646bc800-5eb8-11ea-8ceb-95fdfa7dd4f8.JPG)

3. Config files (required)

**Comment by minhcasi** [comment]
@limitlessfirm - could you help to attache your common/config folder so that we could investigate this issue - thanks

**Comment by limitlessfirm** [comment]
Common folder
[common.zip](https://github.com/inspireui/support/files/4301434/common.zip)

**Comment by limitlessfirm** [comment]
i didn't receive answer until now

**Comment by minhcasi** [comment]
@limitlessfirm - we are checking the issue and will let you know - thank you!

**Comment by philipvu30** [comment]
Hi @limitlessfirm ,

The product that you showed has 3 colors 
![image](https://user-images.githubusercontent.com/54442328/76195515-0b36c800-621b-11ea-8e40-af213f3d9f00.png)
In the constants.dart file you haven't added those colors. 
![image](https://user-images.githubusercontent.com/54442328/76195681-6e285f00-621b-11ea-8cbf-76b7fd3e2950.png)
If those colors are not specified then it'll display white instead.
