### ISSUE TITLE
[my-product] - Cbuild 0.40.0 zip package is broken

### ISSUE THREAD

**Issue by kingboyno1** [inspireui/support#2292]
Trying to download Cbuild 0.40.0 for mac version. But Mac version zip package is broken.
Maybe you have to repackage again.

My purchase code:
71d7ce1f-1183-40a7-81f8-0476689baa70

**Comment by talalibdah** [comment]
Same issue

**Comment by minhcasi** [comment]
@kingboyno1 @talalibdah - thank you for the feedback - we will update the new patching today

**Comment by minhcasi** [comment]
Hi, pls update to latest 40.0.1 to fix the issue - https://github.com/inspireui/cebuilder/releases/tag/0.40.1 - thank you!
