### ISSUE TITLE
[Fluxstore - Woo] - App Store Rejected! / Template problem

### ISSUE THREAD

**Issue by sketchuprzr** [inspireui/support#2294]
Hello. According to the application settings, the category page is set to "card". This is also the case.

However, on a screen with ipad resolution and size, this template is broken. And the navigation bar is not visible.

Therefore, the application has not been approved in the Appstore.

How can I fix this?

### "Must be"
Nexus 6 - 1440 x 2560 px - 560 Dpi - 5.96"
![nexus 6-2](https://user-images.githubusercontent.com/60021696/76004002-e3ddb380-5f19-11ea-84e3-7d79cf7b30ea.gif)

"The faulty one"
### Custom "Like ipad" - 2048 x 2732 px - hdpi - 12.9"
![ipad](https://user-images.githubusercontent.com/60021696/76003898-c4468b00-5f19-11ea-90f9-c3599c6f14c7.gif)
-----------------------------------------------------------------------------------------

### App store:

> From Apple
2. 1 Performance: App Completeness
2. 3 Performance: Accurate Metadata
Guideline 2.1 - Performance - App Completeness

We discovered one or more bugs in your app when reviewed on iPad running iOS 13.3.1 on Wi-Fi.

Specifically, your app did not render the correct prices, nor images for products listed. We attempted several times.

Next Steps

To resolve this issue, please run your app on a device to identify any issues, then revise and resubmit your app for review.

If we misunderstood the intended behavior of your app, please reply to this message in Resolution Center to provide information on how these features were intended to work.

For new apps, uninstall all previous versions of your app from a device, then install and follow the steps to reproduce the issue. For updates, install the new version as an update to the previous version, then follow the steps to reproduce the issue.

Resources

For information about testing your app and preparing it for review, please see Technical Note TN2431: App Testing Guide.

For a networking overview, please review About Networking.

Guideline 2.3.3 - Performance - Accurate Metadata

We noticed that your screenshots do not sufficiently reflect your app in use.

Specifically, the majority of your screenshots do not display the actual app in use.

It would be appropriate to add more screenshots that show the app in use.

Please note that login/splash screen are not considered the app in use.

Next Steps

To resolve this issue, please revise your screenshots to ensure that they accurately reflect the app in use on the supported devices. For example, a gaming app should feature screenshots that capture actual gameplay from within the app. Marketing or promotional materials that do not reflect the UI of the app are not appropriate for screenshots.

The iPhone screenshots should reflect use on iPhone devices.

The iPad screenshots should reflect use on iPad devices.

App Store screenshots should accurately communicate your app’s value and functionality. Use text and overlay images to highlight your app’s user experience, not obscure it. Make sure app UI and product images match the corresponding device type in App Store Connect. This helps users understand your app and makes for a positive App Store experience.

Resources

For resources on creating great screenshots for the App Store, you may want to review the App Store Product Page information available on the Apple Developer website.

Please ensure you have made any screenshot modifications using Media Manager. You should confirm your app looks and behaves identically in all languages and on all supported devices. Learn more about uploading app previews and screenshots in App Store Connect Help.

Please see attached screenshots for details.
-----------------------------------------------------------------------------------------
![image](https://iosapps-ssl.itunes.apple.com/itunes-assets/Purple124/v4/f5/30/6a/f5306a6c-8831-441f-0a78-003a0236b7a2/attachment-865431701928990209Screenshot-0305-135157.png?accessKey=1583685517_3776261723646244490_QxBlSwO8yxRb994RfX1buu%2B%2BlMicfsSRLXmz1Ln4WTknv6HYONn%2Fee%2BOnBR1KrcuGkO96mv6m6w%2BjPywPSY3Ib%2BP4PSCzTY0FOcaySR8ncEMIsT5b3ie%2BG9MMHZ5U2G843N%2F2VEiTBC%2FqkKBLko6%2BpAhcROPQ7HmzuhIH50EGdjjqFiR12mRJcO6VHO31m7vb5ijjRqf4C0PGXf985HH8Q%3D%3D)
![image](https://iosapps-ssl.itunes.apple.com/itunes-assets/Purple114/v4/e4/99/79/e49979b8-6776-3252-4cac-cacb25f0c651/attachment-17870568024341030496Screenshot-0305-135153.png?accessKey=1583685517_3367447252905767301_wWdL1EPd12DCAA3uniPxLXgPYkS9xgTe5XKkZtzoLrAIb%2BntiGyp%2BEcyp9paC4tOuxjd96gJK%2F6lu1X0RpY77zeK5FsjLRn%2F4C2%2F%2Fob%2BBp9OPdfNOF5cvG0wKimzpJ16yqsbLmDQ3taKlmcLH5qIbaNooIvVHsfS9bIHUFPtUHfuqzgGvwvmgYdrc%2BHZ3IqWRyGbjOQgtsS6amGmn6NCCKL37jQEjOUorYBKMqlxsUc%3D)
![image](https://iosapps-ssl.itunes.apple.com/itunes-assets/Purple114/v4/a7/54/a7/a754a731-6cd6-72ba-0e71-0c5fc0b6c16b/attachment-10187226985930693121Screenshot-0305-134600.png?accessKey=1583685517_8553276610739640062_jKkQ4Efm%2F%2FcbuZKgMEY9TtPgoZrMc4NdndqdjoVWLP%2FShhode8Whm8Z%2FRwdKhIDVIDX44QYHv6Tp3utapoa5JSG8zwcBzNwXe4efpNgVlH%2FJlR1DH63l%2FI6uGqkBs02%2B1eTg1oT5pz%2BCD2AhxCqLkPpzYYTRVHBooS3YAnk182IIjg33x9ig5rJhxEm1HXaH6MoZl2NdX2CJGIGbsAHSnoOeCd3hrOZAjVuDqTamR4g%3D)
![image](https://iosapps-ssl.itunes.apple.com/itunes-assets/Purple124/v4/67/88/ce/6788ce57-3a9a-e2cf-370e-30c3c5779c01/attachment-1892886465007955927Screenshot-0305-135117.png?accessKey=1583685517_4797495530344570202_dsYdoQPn6Js49vJiu467jIcBpwEV%2FVDafym7i9QBHO%2BZRLkhOBRi7h%2FC55QtZ5LC8pM5Ezp7KfsW7lNpYA2KbVDUN%2BFSVcqUZgG3DTxz56uHWB9aAYpp%2FFqKbJSXqDMrM%2F3ApdVT0Ebmk0a4lhBlJbAUIUnYBt8Yjw17ViSfKQikEaWMlrvKj6ah%2FndRtI6L%2Bh0ItF5YpiXKFicSDK88Pg%3D%3D)
![image](https://iosapps-ssl.itunes.apple.com/itunes-assets/Purple124/v4/45/b4/47/45b447b5-5c87-d8d0-98e3-f6ee1459718d/attachment-7339048257599243525Screenshot-0305-134554.png?accessKey=1583685517_3108203972212648140_Nmurmc7l81NvScoVOVzzgjBqLFldFgxGu1MW3c09Skywp7piFckUCXPWOmZut7tXYlNyCGN4RGl7K4%2Bjq3wWgq5OjxZvHxgF%2Ft7SYE2erMfQat%2Fq6MqNk%2FBR%2Bm1WGl4BMnG5e%2BF%2FX2WQG8xOJ4WZrdM8Dgw00A1NfORl1ri66bKBnydXVoz3qKGtRl3gtNiMLulC6c53Q3gNnm%2BVcl7xug%3D%3D)
![image](https://iosapps-ssl.itunes.apple.com/itunes-assets/Purple114/v4/fa/f4/6d/faf46db5-5005-448f-6aa0-5c815eb3df73/attachment-10676798515908830736Screenshot-0305-135222.png?accessKey=1583685517_8443243489824770001_LDpLLSsBzrPFFd8uohWDsoK0hvJN8XjHjJsqe%2FqJnLY6VioPNz%2FkZ8AQjlecgcD%2FfihgsZH%2FA6nIp%2FbLDIatD01eReNMdqrS7NQJT0d32Seb%2FwZOZ3I5GTLKT8aClLolYKJDcMyrV0kEivpDotiMvLFGKmNVbYp236n56Aq46yVxgFp2Oa8gnYJUOjxldLZt%2BDCn%2BkY7mbEM8yCBodPze4Mro4Q%2BquaUrFdemfjOel0%3D)
![image](https://iosapps-ssl.itunes.apple.com/itunes-assets/Purple124/v4/ad/1d/59/ad1d59da-6d20-fd9f-bd9c-ef37daf25e90/attachment-9153143412808509474Screenshot-0305-134604.png?accessKey=1583685517_8858268254695030673_lQrMXYaMN7pu2MRvut0dTXb4NGvZZ%2FRn7uSXBAiEpPTmZ1TtkOVIP8ZoFwCmi6xHgNSMM%2Fg%2BII6vT7OAh3LKgaNTg0Lz02y031dzSQsqz8D20iruarCYqgjngce37X01ifYZoXVXmmuWdZf9iaPQy7qfqg3WxgXt8zKbJ6fQrmuNm9sQPT3YQzSpZuBjp6WhCA4Tb77zvt8ftruokr0VJw%3D%3D)

**Comment by minhcasi** [comment]
1. Try to improve the Product list by update the mstore-api to latest https://wordpress.org/plugins/mstore-api/ and use v1.6.4 to apply the caching for this widget

2. Noted for fixing the Card View on product list - @trunghieuvn 

Please note that Apple recent review all app quite strictly and careful

**Comment by sketchuprzr** [comment]
[Fluxstore - Woo] - Onesignal İOS Problem "apns" #2288

![image](https://user-images.githubusercontent.com/60021696/75934481-ae8b8400-5e8d-11ea-9069-1b6dfd021aea.png)

With Xcode, we released the application as texfly.

I made all the certificates. But despite the user coming to onesginal, such an error is displayed.

How can I solve this?

App for ios version : 10.2

![image](https://user-images.githubusercontent.com/60021696/75934582-f3171f80-5e8d-11ea-875a-26f6122d5140.png)

**Comment by sketchuprzr** [comment]
@minhcasi 
Why don't you try to understand my problem? What I asked you is not "cache". Also, the mstore plugin is installed and updated. This is not the problem. I organized the category page theme as "card". But a different category theme appears in ipad resolution.
That's all!

Also, in the ipad resolution, the navbar at the bottom does not appear.

Finally, you directed the Other problem here. But you didn't even answer him. In addition, both problems were not resolved, but you closed the subject.

You have answered almost every subject I have written so far, but you have not found a solution for any of them.
Is inspireui sure you can help people?

**Comment by sketchuprzr** [comment]
Again, as always, I solved the Problem. I got help from a friend and fixed the problem.
I activated the mobile view for all resolutions.

solution:

![image](https://user-images.githubusercontent.com/60021696/76124846-a73eb480-600c-11ea-95da-b846fc2f9f56.png)
![image](https://user-images.githubusercontent.com/60021696/76124854-a9a10e80-600c-11ea-9b1c-8574b0f30972.png)
![image](https://user-images.githubusercontent.com/60021696/76124861-ad349580-600c-11ea-9076-fa1cd6c86edd.png)
![image](https://user-images.githubusercontent.com/60021696/76124870-b1f94980-600c-11ea-9c1a-51fcd39af6f8.png)
![image](https://user-images.githubusercontent.com/60021696/76124883-b6256700-600c-11ea-9b1e-35e61056ee62.png)
![image](https://user-images.githubusercontent.com/60021696/76124894-ba518480-600c-11ea-88d2-434bbec3da78.png)

### I leave the onesignal problem to you. 
"[Fluxstore - Woo] - Onesignal İOS Problem "apns" #2288 

I'm sure you won't be able to solve it in time either, or others will solve it before you.

**Comment by minhcasi** [comment]
@sketchuprzr - you are the super start ⭐️

Please download the latest release Fluxstore 1.6.5 release - we also fixed the Onesignal message issues, categories issues, shippings issues

I'm closing the ticket and move the conversation to #2227 - thanks
