### ISSUE TITLE
[Fluxstore-WooCommerce] - [Navigation] 

### ISSUE THREAD

**Issue by iamar1k92** [inspireui/support#2295]
1. My issue:
(1) - Please give me solution, how the app will correctly get the old price from the website. It is getting the discounted price right but didn't getting original price.

(2) - There is huge problem that when i try to navigate to home screen, it doesn't go to home screen because you have used navigator.pop(context) which actually goes back to previous screen, it should go back to home screen.
 
2. Screenshots issues (required):
(1) (https://user-images.githubusercontent.com/58983166/76002296-345c0d80-5f28-11ea-870f-39460934c8de.jpg

**Comment by minhcasi** [comment]
@iamar1k92 - thank you for the feedback regarding to the navigation, could i know which is the screen regarding to this issue?

 Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads it's used to verify your proof of purchase? sorry for any inconvenience - Thank you!

**Comment by iamar1k92** [comment]
Problem 1 was fixed by updating to latest update of fluxstore.


Problem 2 is about the navigation to Home Screen. There are several buttons where it should redirect to home page. 

1. Like in side drawer menu, There is Home button; it should route to home page, But you have used navigator.pop(context), which actually going to previous page, not going to home page. **It will go to home page if the previous page is home page.** 
2.While in order success page. Back to shop has same mechanism, **it doesn't return to home screen.**
![Uploading IMG-20200305-WA0032.jpg…]()
3.While in My Wishlist. Start shopping button has also same mechanism. **It should return to home screen**. 
![IMG-20200305-WA0037](https://user-images.githubusercontent.com/58983166/76128256-9ea6a800-6025-11ea-93a0-964bbf2909c8.jpg)


Suggestion or Query: Is there any auto-filling for OTP? or it will be featuring in upcoming releases?

**Comment by minhcasi** [comment]
Thank you for the detail feedback, we will investigate and let you know

**Comment by kvt0012** [comment]
Dear sir, about problem 2, we'll ask our customers about this and they like on this way, so we modify it as this. 
Thanks for your issue.

**Comment by minhcasi** [comment]
@iamar1k92 - this bug is fixed on latest build that will be released in 1-2 days

Solution: fix by this screenshot https://tppr.me/hwySJ

**Comment by iamar1k92** [comment]
How to update to 1.6.5?

**Comment by kvt0012** [comment]
Did you buy our app, sir ?

**Comment by iamar1k92** [comment]
@kvt0012 yes i have.
