### ISSUE TITLE
1.6.4 Category screen issue, CacheManager 'Unsupported scheme', category image not displaying with error

### ISSUE THREAD

**Issue by interiorone** [inspireui/support#2296]
RE: #2254 old post.

This problem needs to fix.

![11583106182_ pic_hd](https://user-images.githubusercontent.com/59524812/76023655-6a33dd00-5f8e-11ea-9338-ddf1aaa99919.jpg)
<img width="1440" alt="Screen Shot 2020-03-03 at 11 22 53 PM" src="https://user-images.githubusercontent.com/59524812/76023660-6c963700-5f8e-11ea-9a85-4e725e6a53a2.png">

**Comment by minhcasi** [comment]
@interiorone - could you help to zip your common/config file here for further investigating - thank you!

**Comment by interiorone** [comment]
Kind regards,

Dylan Chan
Your Friendly Customer Service Team

E. info@interiorone.co.nz
P. 09 527 1602
M. 021 990 110
W. www.interiorone.co.nz

**Comment by minhcasi** [comment]
@interiorone - please help send to support@inspireui.com or you could also attache here - thank you!

**Comment by kvt0012** [comment]
Please send me your file, I'll check for you, thank you

**Comment by interiorone** [comment]
here is the file



Kind regards,

Dylan Chan
Your Friendly Customer Service Team

E. info@interiorone.co.nz
P. 09 527 1602
M. 021 990 110
W. www.interiorone.co.nz

**Comment by interiorone** [comment]
Hi there,

any update of the issue yet??

thank you.


Kind regards,

Dylan Chan
Your Friendly Customer Service Team

E. info@interiorone.co.nz
P. 09 527 1602
M. 021 990 110
W. www.interiorone.co.nz

**Comment by kvt0012** [comment]
Dear sir, please kinda send to me your whole project because my files and you are too different, thank you

**Comment by minhcasi** [comment]
@interiorone - please also download the latest release Fluxstore 1.6.5

We also note the detail changelogs from this blog -https://medium.com/@inspireui/announcing-fluxstore-1-6-337efff1791f - thank you!

**Comment by interiorone** [comment]
Hi can you reopen? I have the full files to send you thank you.
