### ISSUE TITLE
[FLUXSTORE MV] - FormatException while login or registration

### ISSUE THREAD

**Issue by Kaysman** [inspireui/support#2297]
1. My issue: While i try to login or sign up, i receive the following error: FormatException: Unexpected character (at character 1) <html>

2. Screenshots issues (required): 
![photo_2020-03-05_22-47-02](https://user-images.githubusercontent.com/42100908/76028611-43948880-5f33-11ea-894b-2aee75e98f61.jpg)

3. Proof of my purchased (required):
![Schermata da 2020-03-05 22-37-48](https://user-images.githubusercontent.com/42100908/76028457-ee587700-5f32-11ea-8c5d-b0c2b07de3d6.png)

3. Config files (required)
[config.txt](https://github.com/inspireui/support/files/4295296/config.txt)

**Comment by netappzone** [comment]
Please, i am facing exactly the same issue. it was working fine before until i updated Mstore api. please i need this solve as soon as possible

**Comment by Kaysman** [comment]
> Please, i am facing exactly the same issue. it was working fine before until i updated Mstore api. please i need this solve as soon as possible

I tried to do the downgrade of Mstore api, but it still doesn't work

**Comment by Kaysman** [comment]
Please @minhcasi @minhtruong315 let us know something... if you can't solve this, give us a refund

**Comment by minhtruong315** [comment]
@Kaysman send me config.dart file and admin account to login to your website via email: truong@inspireui.com with subject: https://github.com/inspireui/support/issues/2297
I'll help u check it. Thanks

**Comment by minhtruong315** [comment]
@Kaysman your project is Fluxstore MV, so we only support type: dokan and wcfm. You set wrong type. please check again
https://tppr.me/SAfwT

**Comment by Kaysman** [comment]
There is the same issue setting type with dokan or wcfm

**Comment by minhtruong315** [comment]
I sent you config on the email. please check

**Comment by Kaysman** [comment]
Now it's work. Thanks.

**Comment by minhcasi** [comment]
we're glad that it help, please give us some feedback/rating to this page https://codecanyon.net/downloads  if the product is helpful for your business, we are working hard to update more awesome and powerful features on next coming version release. Let us know if you have any feedback. Thank you very much!
