### ISSUE TITLE
[Fluxstore WooCommerce] - sales price, error in product page, sub-sub-categories

### ISSUE THREAD

**Issue by mk4full** [inspireui/support#2298]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
1. Disapper sale price - https://imgur.com/Wt5wiBa
2. error - https://imgur.com/IwKXUHE
3. subsubcategories - https://imgur.com/6xnoVUQ
4. blog is empty - https://imgur.com/Qbofo6e

2. Proof of my purchased (required):
https://imgur.com/s0CYDE5

**Comment by minhcasi** [comment]
@mk4full - could you help to zip your common/config file here so that we could help for checking - thank you!

**Comment by mk4full** [comment]
@minhcasi sure https://easyupload.io/blu92i

**Comment by minhtruong315** [comment]
Hi @mk4full I can't download config files. https://tppr.me/t1BBo

**Comment by mk4full** [comment]
@minhtruong315 sorry, pleace check this https://drive.google.com/file/d/1Tjt2XSdTazl5wRMIvPBIESIaHPFLpqjK/view?usp=sharing

**Comment by minhcasi** [comment]
@minhtruong315 - pls update this ticket status

**Comment by minhcasi** [comment]
@mk4full - please also download the latest release Fluxstore 1.6.5

We also note the detail changelogs from this blog -https://medium.com/@inspireui/announcing-fluxstore-1-6-337efff1791f - thank you!

**Comment by minhtruong315** [comment]
@mk4full please check your app on Fluxstore 1.6.5 and let me know the result

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
