### ISSUE TITLE
[FluxStore Listing] - build issues with the latest flutter stable sdk

### ISSUE THREAD

**Issue by khalidsharif** [inspireui/support#2299]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:

ERROR: [TAG] Failed to resolve variable '${junit.version}'
ERROR: [TAG] Failed to resolve variable '${animal.sniffer.version}'
When  I try to build the project I get this issue

2. Screenshots issues (required):
<img width="1169" alt="Screen Shot 2020-03-06 at 1 34 51 PM" src="https://user-images.githubusercontent.com/50369621/76076552-25b93900-5fb0-11ea-8fa9-b1e82f2b47dc.png">
3. Proof of my purchased (required):
<img width="326" alt="Screen Shot 2020-03-06 at 1 36 12 PM" src="https://user-images.githubusercontent.com/50369621/76076672-54cfaa80-5fb0-11ea-83b8-a85d702a599f.png">

3. Config files (required)

<img width="539" alt="Screen Shot 2020-03-06 at 1 43 23 PM" src="https://user-images.githubusercontent.com/50369621/76076728-76c92d00-5fb0-11ea-899b-11b93ae768ef.png">

**Comment by khalidsharif** [comment]
@philipvu30 @minhcasi anyone here to support ?

**Comment by philipvu30** [comment]
Closed as supporting via Skype.
