### ISSUE TITLE
[ListApp] - update compatible header for Android device 

### ISSUE THREAD

**Issue by absmugz** [inspireui/support#23]
**Required Info (please complete the following information):**
 - Product: 
 - Your Purchased Code:
Get from https://codecanyon.net/downloads, we may not reply if you are not our customer.

**Describe the bug**

**Screenshots**

**Additional context**
Add any other detail logs about the problem here.
If possible please share your config.js that use for the app setting

#minhcasi
![screenshot 2018-11-18 at 13 45 21](https://user-images.githubusercontent.com/2528692/48671965-79dca780-eb38-11e8-91df-dd7ce63923d3.png)
![screenshot 2018-11-15 at 22 30 46](https://user-images.githubusercontent.com/2528692/48671972-8bbe4a80-eb38-11e8-9b20-88b8135bce88.png)

**Comment by minhcasi** [comment]
Did you update the expo-cli to latest version and also the Expo client from simulator ?

Try this script:
npm install expo-cli -g

And remove the Expo Client from Expo, Delete node_modules folder and reinstall again

Let us know your checking, thanks!

**Comment by minhcasi** [comment]
Please reopen if you still could not fix the issue - thank you!

**Comment by absmugz** [comment]
Can you please push all content down by about 20pixels for new devices or more maybe 30 pixels? just tested the new ListPro – really cool only feature lacking is support for new devices…this is also an issue on ListPro
![87645_1-1](https://user-images.githubusercontent.com/2528692/48780697-2eb2c800-ece3-11e8-990a-c8ecdac0e90a.jpg)
![87645_1-2](https://user-images.githubusercontent.com/2528692/48780698-2eb2c800-ece3-11e8-96c7-9d62552aab3e.jpg)

**Comment by minhcasi** [comment]
Noted for improving on next milestone = 3.6.4
