### ISSUE TITLE
[BeoNews] App doesn't redirect to post

### ISSUE THREAD

**Issue by hungnguyen9276** [inspireui/support#230]
**Required Info (please complete the following information):**
 - Product: [BeoNews]
 - Your Purchased Code: 2b7fa788-ea4d-4d1c-bb3a-4bf22a499783

**Describe the bug**
When OneSignal push notification to mobile app, the app redirect to home page instead redirect to post.

**Comment by minhcasi** [comment]
Hi, could i check if you have update the Wordpress site base on this guide - https://beonews.inspireui.com/advance-customize/push-notification#install-wordpress-plugin ?

**Comment by hungnguyen9276** [comment]
Yes, I did it, app get notification well however when I touch to notification, the app redirect to home page instead go to the post in notification.
