### ISSUE TITLE
[Fluxstore Pro] - FormatException while login or registration

### ISSUE THREAD

**Issue by netappzone** [inspireui/support#2300]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:

2. Screenshots issues (required):

3. Proof of my purchased (required):

3. Config files (required)

Please i am facing the above issue while registering. Also, none of the login platform works and it started when i update MStore api

**Comment by minhcasi** [comment]
Hi, thank you for the feedback. Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads it's used to verify your proof of purchase? sorry for any inconvenience - Thank you!

**Comment by netappzone** [comment]
This is the a purchase screenshot

**Comment by minhcasi** [comment]
sorry we could not read it, please attache again - thank you!

**Comment by netappzone** [comment]
Please, I really don't understand what you can't read. This is like the
third time you will be working on this login function. My email address is
netappzone@gmail.com and the site is igreenmall.com

**Comment by netappzone** [comment]
Purchase code
