### ISSUE TITLE
[my-product] - Fluxstore

### ISSUE THREAD

**Issue by elienaj** [inspireui/support#2301]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------
Hello Team,
1. My issue:
issue 1 -> cant send review text 
issue 2 -> how can I replace the loader with another loader?
issue 3 -> after registration, we didn't receive any alert that  your registration has been successfully completed OR Please confirm your email and once done,
 the login page open again we need to go back one more time to check the settings screen, and if we logged out, we cannot log in again until we activate the user from the admin

2. Screenshots issues (required):
issue 1 -> https://user-images.githubusercontent.com/61785293/76091659-ae42d400-5fc6-11ea-959c-9578d632644d.jpg
issue 2 ->  https://user-images.githubusercontent.com/61785293/76092542-39709980-5fc8-11ea-8885-0db5d7447e18.png
issue 3 -> https://user-images.githubusercontent.com/61785293/76096008-fe716480-5fcd-11ea-9657-5c310571fb58.jpg

3. Proof of my purchased (required):

https://user-images.githubusercontent.com/61785293/76091166-b2babd00-5fc5-11ea-8859-89ca36d6760e.png

3. Config files (required)
[config_en.json.zip](https://github.com/inspireui/support/files/4298717/config_en.json.zip)

**Comment by elienaj** [comment]
issue 4 -> cant edit product quantity from checkout review 
![issue4](https://user-images.githubusercontent.com/61785293/76100108-cd486280-5fd4-11ea-87c1-ac19846cf5a5.png)

**Comment by minhtruong315** [comment]
@elienaj can u send me full source code via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/2301

**Comment by elienaj** [comment]
Hello,
Please follow the below link to download the full source code.
https://we.tl/t-3sluAANDYm
one more issue, on the website we have implemented AREEBA payment gateway. it's not working on the apps please check it aswell.

USER: elie.h.najem@gmail.com
pass:   111111

**Comment by elienaj** [comment]
hello @minhtruong315 any good news?

**Comment by minhcasi** [comment]
@minhtruong315 - pls update the status on this ticket - thanks

**Comment by minhcasi** [comment]
@elienaj  - please also download the latest release Fluxstore 1.6.5

We also note the detail changelogs from this blog -https://medium.com/@inspireui/announcing-fluxstore-1-6-337efff1791f - thank you!

**Comment by elienaj** [comment]
Hello @minhtruong315 <https://github.com/minhtruong315>,
please send me the link to download latest release Fluxstore 1.6.5.


please check below :

Elies-iMac:~ elienajem$ flutter --version
Flutter 1.12.13+hotfix.8 • channel stable •
https://github.com/flutter/flutter.git
Framework • revision 0b8abb4724 (5 weeks ago) • 2020-02-11 11:44:36 -0800
Engine • revision e1e6ced81d
Tools • Dart 2.7.0

**Comment by minhtruong315** [comment]
@elienaj you can download here https://codecanyon.net/downloads

**Comment by minhtruong315** [comment]
@elienaj how?

**Comment by elienaj** [comment]
hello @minhtruong315 checking it

**Comment by minhtruong315** [comment]
let me know if you have any issues.

**Comment by elienaj** [comment]
Hello,
trying to run the new update FluxStore 1.6.6b, I'm getting Registered as a
Git root, but no Git repositories were found there
can you help?
