### ISSUE TITLE
[MStore-API , Fluxstore] - Update profile API not working 

### ISSUE THREAD

**Issue by Lokeswara-betha** [inspireui/support#2304]
HI Team,

When I try to update profile from app, I am getting below response.

**The site is experiencing technical difficulties. Please check your site admin email inbox for instructions.**

I checked in my word press plugin panel, there also it shows the same.

screenshot:

![image](https://user-images.githubusercontent.com/60268240/76141190-d7776900-6087-11ea-9f4d-eddca6495df9.png)

**Comment by minhcasi** [comment]
@Lokeswara-betha - the updating Profile is fixed on the latest code, we will release the new version on early next week - thank you!
