### ISSUE TITLE
[Fluxstore WooCommerce] - Where is firebase folder came from (Integration)❓

### ISSUE THREAD

**Issue by talalibdah** [inspireui/support#2305]
1. My issue:
I'm following this tutorial to setup firebase chat and messaging: 
https://docs.inspireui.com/fluxstore/firebase/

But a step involving importing a folder called Firebase that includes functions and other files you used in the tutorial does not exist. I cannot find it. May you help? 

2. Screenshots issues (required):
https://docs.inspireui.com/static/d568c87ab57ce81172c3714663f59306/aee4e/firebase_function.png

May you help?

**Comment by minhcasi** [comment]
[firebase.zip](https://github.com/inspireui/support/files/4302794/firebase.zip) - could you try this file  - thank you!
