### ISSUE TITLE
[FluxStore] -  Razorpay app crash

### ISSUE THREAD

**Issue by UTimung** [inspireui/support#2306]
In debug apk, Razorpay payment works perfectly

But in release apk, when choose Razorpay as payment method, the app crash

**Comment by minhcasi** [comment]
@UTimung - could you zip the current source and send us for investigating - support@inspireui.com - thank you!

**Comment by minhcasi** [comment]
Duplicate of #2303

**Comment by UTimung** [comment]
> @UTimung - could you zip the current source and send us for investigating - [support@inspireui.com](mailto:support@inspireui.com) - thank you!

i sent you an email with current source code
 please check
