### ISSUE TITLE
Mstore mv - issues on expo version

### ISSUE THREAD

**Issue by alazar-aklilu** [inspireui/support#2307]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.
---------

1. My issue:
Hi, i installed the latest version (1.3.3) and there are issues that still exist
a. i wan't to remove facebook login how do i do that
b. push notifications are not working
c. the categories tab only shows half the categories in my store
d. the vendors tab is not showing anything
e. review is not working
f. in the products page the vendor section has empty fields
g. i don't want login to be required for checkout
h. when trying to add product and error "sorry, you are not allowed to create posts as this user' shows
i. checkout is not completed in the app it redirects to the mobile site. is there anyway i can fix this
Thank you very much 
2. Screenshots issues (required):
![74604767-0e361100-50d2-11ea-86fb-0e64fa7ccab2](https://user-images.githubusercontent.com/60713664/76144133-6edfba80-608e-11ea-8f23-4853f05ef608.jpg)
![74604773-227a0e00-50d2-11ea-8189-f8b378c2bb17](https://user-images.githubusercontent.com/60713664/76144134-730bd800-608e-11ea-972d-bb90151b190d.jpg)
![76144084-d47f7700-608d-11ea-8af1-c8f41f83ff6a](https://user-images.githubusercontent.com/60713664/76144148-874fd500-608e-11ea-9f35-a058fbf19eab.jpg)
![Screenshot_20200307-152659_Brundo_Shopping 2](https://user-images.githubusercontent.com/60713664/76144211-0e04b200-608f-11ea-80ba-5c1bc9cb2eb3.jpg)

3. Proof of my purchased (required):
![74604733-aaabe380-50d1-11ea-9e28-de307ace1a51](https://user-images.githubusercontent.com/60713664/76144149-8cad1f80-608e-11ea-9050-478c6f43d3d2.png)

3. Config files (required)

[Config.zip](https://github.com/inspireui/support/files/4301836/Config.zip)

**Comment by alazar-aklilu** [comment]
I would like to add that you have an amazing product at hand and to keep on pushing the boundaries. big ups and i'm so thankful. if there is anyplace i can testify i'm more than willing

**Comment by minhcasi** [comment]
@alazar-aklilu - thank you so much for your detailed feedback and encourage - we will have a check and let you know

**Comment by alazar-aklilu** [comment]
you are welcome and thank you. I'm a little bit behind on schedule so i am desperate for your help

Sent from Yahoo Mail on Android 
 
  On Sun, 8 Mar 2020 at 6:15 am, Minh Pham<notifications@github.com> wrote:   
@alazar-aklilu - thank you so much for your detailed feedback and encourage - we will have a check and let you know

**Comment by luyx2412** [comment]
Hi @alazar-aklilu 
- You want to remove facebook?
- Please make sure you configured push notification https://docs.inspireui.com/mstore/push-notification/
- You meant your categories only show 50% items in your store?
- You need add vendors store in your dashboard website.
- Please make sure the product existed reviews.
- I saw the vendor section in the product screen still show in your photo.
- You need add login to can checkout, we did not remove this feature. Or you can config in your dashboard website with anonymous checkout.
- Because your account could not create vendor, you can create or change roles in your dashboard website.
- The checkout payment is webview which will show your website link to complete checkout.

Thanks

**Comment by alazar-aklilu** [comment]
●yes i want to remove facebook login●okay i will look into the push notification docs.●no i have 12 categories only 7 are shown.●i have 52 vendors on my wcfm website they don't appear on the app●there are reviews but i cannot add new reviews using the app●no the vendors are not seen only the tab exists ●anonymous checkout works on my website not on my app though it requires checkout how do i remove it. ●i tried it with a vendor account i created with the app and also with a wcfm store vendor account that works on the website but not on the app ●i hope you update it and make it in app. i looks ugly and nothing professional
Sent from Yahoo Mail on Android 
 
  On Sun, 8 Mar 2020 at 2:33 pm, luyx2412<notifications@github.com> wrote:   
Hi @alazar-aklilu
   
   - You want to remove facebook?
   - Please make sure you configured push notification https://docs.inspireui.com/mstore/push-notification/
   - You meant your categories only show 50% items in your store?
   - You need add vendors store in your dashboard website.
   - Please make sure the product existed reviews.
   - I saw the vendor section in the product screen still show in your photo.
   - You need add login to can checkout, we did not remove this feature. Or you can config in your dashboard website with anonymous checkout.
   - Because your account could not create vendor, you can create or change roles in your dashboard website.
   - The checkout payment is webview which will show your website link to complete checkout.

Thanks

**Comment by luyx2412** [comment]
Hi @alazar-aklilu 
- In login screen you can hide facebook `src/containers/Login/index.js` line 253
![image](https://user-images.githubusercontent.com/8909619/76427009-606f0700-63de-11ea-9dd6-21ca56ca5bf5.png)
- Please using reactotron to debug your categories response. https://docs.inspireui.com/mstore-mv/development/
- If you want to add review, please make sure these account role can add it.
- Recheck account
- If you want to hide login before checkout, please comment code look like the screenshot in `src/containers/Cart/index.js` line 79
![image](https://user-images.githubusercontent.com/8909619/76427346-c52a6180-63de-11ea-9709-ca2726d20d4b.png)
- Can you send me your website information and account via luyxtran264@gmail.com

Thanks

**Comment by alazar-aklilu** [comment]
hi, i haven't had any help on my issue after one of the tech support team asked me to send him via email there hasn't been any reply https://github.com/inspireui/support/issues/2307


Sent from Yahoo Mail on Android 
 
  On Sun, 8 Mar 2020 at 12:15 pm, Alazar Aklilu<alazar.aklilu@yahoo.com> wrote:   you are welcome and thank you. I'm a little bit behind on schedule so i am desperate for your help

Sent from Yahoo Mail on Android 
 
  On Sun, 8 Mar 2020 at 6:15 am, Minh Pham<notifications@github.com> wrote:   
@alazar-aklilu - thank you so much for your detailed feedback and encourage - we will have a check and let you know

**Comment by alazar-aklilu** [comment]
Anyone. Can you complete my support please

**Comment by alazar-aklilu** [comment]
okay thanks. its been months now since i purchased mstore mv. these issues are the only ones left towards the perfect App

Sent from Yahoo Mail on Android 
 
  On Thu, 26 Mar 2020 at 7:30 am, Minh Pham<notifications@github.com> wrote:   


Reopened #2307.

**Comment by luyx2412** [comment]
Hi @alazar-aklilu How can i help you about your issue? Please give me specific and screenshot to understand easider.

Thanks

**Comment by alazar-aklilu** [comment]
i have provided all info above you asked me to email you website info but nothing 

Sent from Yahoo Mail on Android 
 
  On Sat, 28 Mar 2020 at 8:15 am, luyx2412<notifications@github.com> wrote:   


Hi @alazar-aklilu How can i help you about your issue? Please give me specific and screenshot to understand easider.

Thanks

**Comment by alazar-aklilu** [comment]
Hi, i installed the latest version (1.3.3) and there are issues that still exist
a. push notifications are not working
b. the categories tab only shows half the categories in my store
c. the vendors tab is not showing anything
d. review is not working
e. in the products page the vendor section has empty fields
f. i don't want login to be required for checkout
g. when trying to add product and error "sorry, you are not allowed to create posts as this user' shows
h. checkout is not completed in the app it redirects to the mobile site. is there anyway i can fix this
Thank you very much. we have had this conversation previously please take a look at the top comments in this issue

**Comment by luyx2412** [comment]
HI @alazar-aklilu Sorry about reply late and miss your email. Can you send me via luyxtran264@gmail.com. And please make sure you did follow the document. https://docs.inspireui.com/mstore-mv

Thanks

**Comment by alazar-aklilu** [comment]
hi, i have sent you an email 4 days ago. any progress?

**Comment by luyx2412** [comment]
Hi @alazar-aklilu I am investigating your issue. Sorry about reply you late.

Thanks

**Comment by alazar-aklilu** [comment]
Hi, is there any progress?

**Comment by luyx2412** [comment]
Hi @alazar-aklilu I just tested your config.
- Please add your onesignal key to Config.js file 
![image](https://user-images.githubusercontent.com/8909619/79298200-9ede7100-7f0a-11ea-978d-ee0a88f1b148.png)

- The default get categories will not get empty categories. In `src/services/WooWorker.js` --> line 25 --> change `hide_empty: true` --> `hide_empty: false`
![image](https://user-images.githubusercontent.com/8909619/79298296-f2e95580-7f0a-11ea-8418-1ec60f0464c7.png)

- You installed missing dokan plugin, please read the document to install it and add vendor. So th vendor tab could not show anything. https://docs.inspireui.com/mstore-mv/getting-started/
![image](https://user-images.githubusercontent.com/8909619/79298602-cda91700-7f0b-11ea-9ea6-4ef71ce4c1b1.png)
![image](https://user-images.githubusercontent.com/8909619/79298666-fe894c00-7f0b-11ea-8c7e-ce67fd31945a.png)

- Please make sure your product have review 
![image](https://user-images.githubusercontent.com/8909619/79298777-52943080-7f0c-11ea-96e2-4f01678a9bff.png)

- You need install dokan plugin to have vendor in your product.

- Can you describe this issue? You want to create product in the app?

- Currently we just support payment via webview, so this is not issue. 

Thanks

**Comment by alazar-aklilu** [comment]
sorry i replied late i was working on another project. 
1. I don't use dokan i use wcfm,2. yes i want to add products on the app with the + button 



Sent from Yahoo Mail on Android 
 
  On Wed, 15 Apr 2020 at 7:31 am, luyx2412<notifications@github.com> wrote:   


Hi @alazar-aklilu I just tested your config.
   
   -    
Please add your onesignal key to Config.js file   


   -    
The default get categories will not get empty categories. In src/services/WooWorker.js --> line 25 --> change hide_empty: true --> hide_empty: false   


   -    
You installed missing dokan plugin, please read the document to install it and add vendor. So th vendor tab could not show anything. https://docs.inspireui.com/mstore-mv/getting-started/   
   


   -    
Please make sure your product have review   


   -    
You need install dokan plugin to have vendor in your product.

   -    
Can you describe this issue? You want to create product in the app?

   -    
Currently we just support payment via webview, so this is not issue.


Thanks

InspireUI DocumentMStore Multi Vendor - Complete React Native template for WooCommerceYou are shop-owners of physical stores with high-traffic consumers and think to go digital. Or you are online shop-owners with E-Commerce websites. Both of you want to maximize sale opportunities. You are developers who are challenged to develop store mobile application in a shorter time. You question how can MStore help. Here are your answers.

**Comment by alazar-aklilu** [comment]
sorry i replied late i was working on another project. 

1. I don't use dokan i use wcfm,
2. yes i want to add products on the app with the + button 

will the checkout page be fixed or will it not be updated in the future?
