### ISSUE TITLE
FormatException on registration and login

### ISSUE THREAD

**Issue by jdhartwell** [inspireui/support#2308]
I'm getting the following error on registration and login. Account is created, but cannot login.

FormatException: Unexpected character
(at character 1)

<img width="317" alt="Screen Shot 2020-03-07 at 9 07 24 AM" src="https://user-images.githubusercontent.com/1307588/76146795-1b03b000-6053-11ea-9483-8b51960c013b.png">

I've sent common folder and proof of purchase. Thanks.

**Comment by minhcasi** [comment]
Hi, thank you for the feedback. Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads it's used to verify your proof of purchase? sorry for any inconvenience - Thank you!

**Comment by jdhartwell** [comment]
<img width="1066" alt="Screen Shot 2020-03-07 at 10 47 48 PM" src="https://user-images.githubusercontent.com/1307588/76157403-bc2b4e80-60c5-11ea-8c68-8f6ac4613430.png">

Indeed, thanks.

**Comment by minhcasi** [comment]
@jdhartwell - thank you for quick response, could you help to check following solution:

- Update the app to latest 1.6.4 
- Update the latest mstore-api API from this link https://wordpress.org/plugins/mstore-api/

Also, please share your common and config folder to that we could help to check the integration on your site. You can also check the integration by using this free builder tool - http://fluxbuilder.com/ 

Let us know your checking, thank you!

**Comment by jdhartwell** [comment]
Still having the same issue, still getting the FormatException error when trying to register and login. I checked the integration with fluxbuilder, seems it’s connected correctly (see attached)?

What’s next?

**Comment by minhcasi** [comment]
@jdhartwell - would you mind to attach the config folder here so that i can have a check? i could not see your config file from previous comments - thank you!

**Comment by jdhartwell** [comment]
Thanks. Attached is the config and common folder from 1.6.4. Also, I notice on the upgrade notes that the JSON-API plugin is no longer need. When I deleted it and upgraded the Store-API, I began to get the following error messages.

Trying to get property 'query' of non-object in /wp-content/plugins/mstore-api/mstore-api.php on line 177

Notice: Trying to get property 'cookie' of non-object in /wp-content/plugins/mstore-api/mstore-api.php on line 177

Warning: Cannot modify header information - headers already sent by (output started at /wp-content/plugins/mstore-api/mstore-api.php:177) in /wp-includes/functions.php on line 6029

Warning: Cannot modify header information - headers already sent by (output started at /wp-content/plugins/mstore-api/mstore-api.php:177) in /wp-admin/includes/misc.php on line 1252

Warning: Cannot modify header information - headers already sent by (output started at /wp-content/plugins/mstore-api/mstore-api.php:177) in /wp-admin/admin-header.php on line 9

**Comment by minhcasi** [comment]
@jdhartwell - pls try to disable the warning and notice from web server or update wp-config.php (change debug to false)

**Comment by twhittakerdev** [comment]
> I'm getting the following error on registration and login. Account is created, but cannot login.
> 
> FormatException: Unexpected character
> (at character 1)
> 
> <img alt="Screen Shot 2020-03-07 at 9 07 24 AM" width="317" src="https://user-images.githubusercontent.com/1307588/76146795-1b03b000-6053-11ea-9483-8b51960c013b.png">
> 
> I've sent common folder and proof of purchase. Thanks.

im having the same issue, all plugins are updated and using the fluxbuilder which pass all avlidated settings

**Comment by opooletech** [comment]
We have the Same Issue please help and update me what the issue in login and signup

**Comment by jinuem** [comment]
Same issue i am facing.
