### ISSUE TITLE
[FLUXSTORE-WOOCOMERCE V-1.6.4] - Multiple Issue

### ISSUE THREAD

**Issue by papaya1986** [inspireui/support#2309]
![proof](https://user-images.githubusercontent.com/47878412/76153383-4c32bd80-60f1-11ea-8bf7-3f0cec8ab378.JPG)

ISSUE 1

**1.COUPON CODE NOT WORKING ADDED THE CODE BACKEND BUT APP SAYING AS FOLLOWS**

![WhatsApp Image 2020-03-08 at 3 56 40 AM](https://user-images.githubusercontent.com/47878412/76153397-7dab8900-60f1-11ea-9b11-968cc67e753f.jpeg)

ISSUE 2

SHIPPING COMPLETELY NOT WORKING 

showing all the shipping method free delivery,paid delivery all 
example if user spends 1000 shipping is free but it's not calculating and showing the flat rate and all methods.
![WhatsApp Image 2020-03-08 at 3 57 56 AM](https://user-images.githubusercontent.com/47878412/76153431-f3aff000-60f1-11ea-9f1f-32b9ce193841.jpeg)

![WhatsApp Image 2020-03-08 at 3 57 38 AM](https://user-images.githubusercontent.com/47878412/76153412-bea39d80-60f1-11ea-92a0-eb4a0c043ff2.jpeg)

ISSUE 3 
I am using config.dart Country ISO code =QA (QATAR)
when am in review order am seeing bellow error 

![WhatsApp Image 2020-03-08 at 3 56 12 AM (1)](https://user-images.githubusercontent.com/47878412/76153427-eabf1e80-60f1-11ea-9190-fa35b9814083.jpeg)

**Comment by papaya1986** [comment]
coupon code is working need to enter coupon code lower case

**Comment by philipvu30** [comment]
Hi @papaya1986 ,

The issue with the coupon has been fixed. We will include the fix in the next update of our app.

Thank you for your patience.
