### ISSUE TITLE
[BeoNews] Category selection

### ISSUE THREAD

**Issue by hadi13** [inspireui/support#231]
**Required Info (please complete the following information):**
 - Product: [Beonews]
 - Your Purchased Code: [14cf2889-4560-4e19-98c2-5134c9e6d044]
(we may not reply if you are not our customer)

**Describe the bug**
where can I find this in the app code and hide it?
and I tried to change the photos for the categories with no success.
**Screenshots**
<img width="311" alt="screen shot 2019-01-29 at 10 05 38 am" src="https://user-images.githubusercontent.com/2642454/51890719-dc121e00-23ad-11e9-80d2-419bb10da142.png">

**Comment by luyx2412** [comment]
HI @hadi13 
- in Config.js file you will see `showSwitchCategory: true`, please change the value `showSwitchCategory: false` which will hide this option.
- in Containter/Category/index.js line 79 follow the photo, you can edit the image in this line.
![2019-01-29_21-55-48](https://user-images.githubusercontent.com/8909619/51916941-f7624500-2410-11e9-93a7-e7a60383b435.png)

Thanks

**Comment by hadi13** [comment]
I mean the photos for the categories, how to change them?

**Comment by luyx2412** [comment]
Hi @hadi13 You can change your photos of the categories in your website wordpress admin. 

Thanks
