### ISSUE TITLE
Fluxstore - Coupon code is not applied

### ISSUE THREAD

**Issue by AbdallaSamy** [inspireui/support#2311]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
Coupon code is applied on the app only but not reflecting in woocommerce dashboard (but when i receive the order on woocommerce admin the discount is not applied) I can only see the code is registered in woocommerce but no discount applied.

2. Screenshots issues (required):
![IMG_6215](https://user-images.githubusercontent.com/33021725/76163215-b7b27480-615d-11ea-8726-79d6ad9e48a4.PNG)
![IMG_6214](https://user-images.githubusercontent.com/33021725/76163217-bbde9200-615d-11ea-9ea2-565d8f459717.PNG)

3. Proof of my purchased (required):
<img width="1053" alt="Screen Shot 2020-03-08 at 4 55 06 PM" src="https://user-images.githubusercontent.com/33021725/76163222-c9941780-615d-11ea-8a93-67b61b7a4942.png">

3. Config files (required)
[common.zip](https://github.com/inspireui/support/files/4303219/common.zip)

**Comment by minhcasi** [comment]
Related to #2309

**Comment by AbdallaSamy** [comment]
Actually it’s not related to 2309. The coupon code is accepted in the app but not applied in backend. Please read the issue carefully. 

Regards,
Abdallah

**Comment by philipvu30** [comment]
Hi @AbdallaSamy ,
This issue has already been fixed, please wait for the next update from us. Thank you for your patience.

**Comment by minhcasi** [comment]
@AbdallaSamy  - please download the latest release Fluxstore 1.6.5

We also note the detail changelogs from this blog -https://medium.com/@inspireui/announcing-fluxstore-1-6-337efff1791f - thank you!
