### ISSUE TITLE
[Fluxstore WooCommerce] Changed translation keys are not showing after rebuild

### ISSUE THREAD

**Issue by talalibdah** [inspireui/support#2313]
Hello team, 

I changed several translation keys values, but when I rebuilt the app bundle, I still see old translation keys values displayed in the app. I ran flutter clean the build but also no luck. same applies to app icon as well.

May you help?

**Comment by minhcasi** [comment]
@talalibdah - pls check the migration guide from #13 and check the Android Studio plugin - https://medium.com/@inspireui/announcing-fluxstore-1-6-337efff1791f

he new language files are moved from res/values folder to lib/l10n folder, please try to install a new Android Studio Flutter Intl plugin as the previous flutter-i18n plugin is stoped support.

**Comment by talalibdah** [comment]
@minhcasi I edited the translation keys in lib/l10n folder, but the generated build still has the old translation keys displayed
