### ISSUE TITLE
[FluxBuilder] Cannot sort screen items by drag/drop 

### ISSUE THREAD

**Issue by talalibdah** [inspireui/support#2314]
I'm using FluxBuilder but the app screens items cannot be sorted. I tried to drag one item and change its sorting but with no luck. I have latest FluxBuilder version. 

Thank you

**Comment by minhcasi** [comment]
@talalibdah - pls help to move the Fluxbuilder to https://github.com/inspireui/fluxbuilder/issues - also help us provide some screenshot issue - thank you!
