### ISSUE TITLE
[Fluxstore - intial value problem] - 

### ISSUE THREAD

**Issue by khaledsalama32** [inspireui/support#2316]
1. My issue:
What is problem 
when i go checkout 
show me this wrong :

( error in expention initial value provided is not supported ) 
 
2. Screenshots issues (required):
![Screenshot_٢٠٢٠٠٣٠٩-١٠٢٥٢٩](https://user-images.githubusercontent.com/61389531/76191428-60111900-61f0-11ea-90d0-6bd95bdacc79.png)

3. Proof of my purchased (required):
Purchase code: 9e83ec40-8414-4b23-960d-0b69d207dd89

![we](https://user-images.githubusercontent.com/61389531/76239303-63cd8b80-6242-11ea-9677-acb5b244fc32.png)
3. Config files (required)

**Comment by khaledsalama32** [comment]
@minhcasi

**Comment by khaledsalama32** [comment]
please any one help me !!!

**Comment by khaledsalama32** [comment]
@minhcasi  please see my problem

**Comment by minhcasi** [comment]
@khaledsalama32 - could you zip you common and config file so that we could help for checking this issue - thank you!

**Comment by khaledsalama32** [comment]
[common.zip](https://github.com/inspireui/support/files/4311047/common.zip)

Prefer this is files
Please tell me where is the error and thank you

**Comment by khaledsalama32** [comment]
@minhcasi   I have sent you the required files

**Comment by minhcasi** [comment]
@kvt0012  - please help for supporting - thank you!

**Comment by kvt0012** [comment]
Dear sir, 
Firstly, we've already had a class ImageConstant on our project, so if you want to modify something, please find image_constants.dart and edit it. It usually on common/constants/image_constants.dart

**Comment by kvt0012** [comment]
Secondly, I'll check and this exception arises because your country's iso code is not supported now on our store, so if you want to modify it, please follow this guide.
https://docs.inspireui.com/fluxstore/multi-language/ 
Thank you

**Comment by kvt0012** [comment]
Secondly, I'll check and this exception arises because your country's iso code is not supported now on our store, so please tell me which country you use this app,sir ? Thank you

**Comment by khaledsalama32** [comment]
I use code  of  kuwait 
how i can to get code of kuwait in app ?

**Comment by kvt0012** [comment]
On Kuwait, our iso code is as this 
 Country(
    isoCode: "KW",
    phoneCode: "965",
    name: "Kuwait",
    iso3Code: "KWT",

Please check for your config, thank you

**Comment by khaledsalama32** [comment]
Thank you 
Please tel me what is the symbol currency of kuwait ?

**Comment by khaledsalama32** [comment]
did i can use this symbol for currency kuwait     " د.ك"

**Comment by minhcasi** [comment]
@khaledsalama32 - the currency could by change on this setting https://tppr.me/8jFJ3 - thank you!
