### ISSUE TITLE
[Fluxstore-woocommerce  65 megabyte] - 

### ISSUE THREAD

**Issue by khaledsalama32** [inspireui/support#2317]
1. My issue:
Why when I export the application by androidstudio.
Get a big 65 mega byte apk file.
File size after export should be less than 10MB

2. Screenshots issues (required):

3. Proof of my purchased (required):
9e83ec40-8414-4b23-960d-0b69d207dd89
3. Config files (required)

**Comment by khaledsalama32** [comment]
@minhcasi   please help me

**Comment by minhcasi** [comment]
@khaledsalama32 - our demo app is only 16MB - https://tppr.me/eIyK7 (this is the default package that you have downloaded)

You can try to optimize the package by using compress files and remove some asset files - try to use this guide for more detail - https://flutter.dev/docs/deployment/android
