### ISSUE TITLE
[Fluxstore] - Homepage doesn't change with config_* for multilanguage

### ISSUE THREAD

**Issue by ahmetozcan9211** [inspireui/support#2318]
i want change homepage by language. but it isn't work. language changing but homepage didn't change.
for example when I choose Arabian language I want use config_ar.json file for woman collection, mens collection etc.. help me pls. 

here is my screen shot for license
![75962323-9b4fd700-5ed4-11ea-8e45-3004ffe545eb](https://user-images.githubusercontent.com/9422532/76247666-f8d78100-6250-11ea-906d-fa2c59020ed9.jpg)

**Comment by minhcasi** [comment]
@ahmetozcan9211 - could you make sure the Rest API is working well on your site, pls try to quick check by seeing the categories screen is loaded data

Also, share use the common / config file to check the issue - thank you!

**Comment by ahmetozcan9211** [comment]
> @ahmetozcan9211 - could you make sure the Rest API is working well on your site, pls try to quick check by seeing the categories screen is loaded data
> 
> Also, share use the common / config file to check the issue - thank you!

Did you mean?
"for language code rest api must working?"
Yes it is working. For example for arabian language i can access api with language tag /ar adding to my rest api url. Thank you for reply.

**Comment by kvt0012** [comment]
Dear sir, 
Please follow on this guide, especially on the third guide, I think it will fix your problem 
https://docs.inspireui.com/fluxstore/multi-language/ 
Thank you

**Comment by ahmetozcan9211** [comment]
> Dear sir,
> Please follow on this guide, especially on the third guide, I think it will fix your problem
> https://docs.inspireui.com/fluxstore/multi-language/
> Thank you
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/c1f5c35bdee2cf5a71b0e35ef38becdf8ec89d72/68747470733a2f2f646f63732e696e737069726575692e636f6d2f696d616765732f6d6574612f47686f73742d446f63732e6a7067">InspireUI Document**[FluxStore - Universal mobile commerce Flutter app for Magento, WooCommerce and Opencart](https://docs.inspireui.com/fluxstore/multi-language/)**Fluxstore is universal app that fully integration with the Woocommerce, Mangeto and Opencart

Thank you for reply. I mean that i can translate products no problem about this. But when i Change language my home Page didnt translate. I mean "Woman collection, men collection text didnt translate like my language config. For example in my english config file (config_en.json) it is declared as woman collection, in my turkish language file (config_tr.json) it is declared as" kadınlara özel". When i Change language english to turkish everything is Fine (product infos, sizes, colors...etc) but in my home Page "woman collection" didnt translate to "kadınlara özel"

**Comment by kvt0012** [comment]
Dear sir, please take screenshot to make your problem clearly, thank you

**Comment by minhcasi** [comment]
@ahmetozcan9211   - please download the latest release Fluxstore 1.6.5 to fix this issue

We also note the detail changelogs from this blog -https://medium.com/@inspireui/announcing-fluxstore-1-6-337efff1791f - thank you!
