### ISSUE TITLE
Fluxstore Pro - Flutter E-commerce Full App- Nedd to add some Fields 

### ISSUE THREAD

**Issue by nahuelbourdichon** [inspireui/support#2319]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
I need to add some fields in check out and registration views 
2. Screenshots issues (required):
In the checkout or pay method I need to add a pick up store 
![image](https://user-images.githubusercontent.com/16769047/76271462-5b338000-6257-11ea-955d-6f87d7c85c11.png)

on the registration view or update profile I need add two fields (Card Number and National ID)

![image](https://user-images.githubusercontent.com/16769047/76271687-05aba300-6258-11ea-8496-18f3dbf3add7.png)

please can you give me a hand to find the file that I need to modify to get this fields.
Thanks 
3. Proof of my purchased (required):
Purchase code: da1a5937-640f-4126-b363-1f918d00885a
3. Config files (required)

**Comment by minhcasi** [comment]
@nahuelbourdichon - we will help to suggest for this feature as it seems the common problem from other users

Could you help to share your common / config file so that we could check the generic solution to fix it?

Very best!

**Comment by nahuelbourdichon** [comment]
Thank you.  atteached!!!
[common-config.zip](https://github.com/inspireui/support/files/4310049/common-config.zip)

**Comment by nahuelbourdichon** [comment]
Hello about the fields value that i want to get  how can I do that ?
![image](https://user-images.githubusercontent.com/16769047/76484214-e3508b80-63f7-11ea-9ad8-76ecc33b05ea.png)


thanks

**Comment by minhcasi** [comment]
The meta_data is the array List so you need to use the loop syntax - https://dart.dev/guides/language/language-tour#lists

**Comment by nahuelbourdichon** [comment]
please can you give me an example 
thanks

**Comment by minhcasi** [comment]
@nahuelbourdichon - we have added some similar code from the release v1.6.5 - https://tppr.me/2vC40 - thank you!
