### ISSUE TITLE
MSTORE PRO - CEBUILDER not working

### ISSUE THREAD

**Issue by cakerake** [inspireui/support#232]
Product : MSTORE PRO - CEBUILDER
Purchase Code : ff5f8923-6693-4e04-b338-d84f9115958a

I'm trying to run cebuilder

i unzipped files > ran yarn setup > entered the location of project folder > the icon keeps spinning nothing happens

what do i do?

**Comment by minhcasi** [comment]
First could you check to see if all the libraries are installed from Tools ?

Could you share the screenshot of the Setup screen ?

**Comment by cakerake** [comment]
here is cebuilder

![image](https://user-images.githubusercontent.com/22143254/51909775-3e3f4300-23ef-11e9-9b5a-a807b38646b9.png)


here is tools page

![image](https://user-images.githubusercontent.com/22143254/51909788-45fee780-23ef-11e9-9acd-672d1539738c.png)


can you please help

**Comment by KIRANNAIR1** [comment]
I have purchased BuzzAPp, i am also facing similar issue with CEBUILDER on Windows10 , ICON keep spinning , nothing happens thereafter .
