### ISSUE TITLE
[FluxStore_vnedor-1.6.4] - web support

### ISSUE THREAD

**Issue by Jesserhee** [inspireui/support#2320]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: I bought this seeing it supports web but I tried and the plugins are not working on web. Is there a way to solve this?

2. Screenshots issues (required):
<img width="1049" alt="스크린샷 2020-03-10 오후 4 45 30" src="https://user-images.githubusercontent.com/5944039/76290434-8f0db480-62ee-11ea-9b74-8168ea556a07.png">

3. Proof of my purchased (required):
<img width="1414" alt="codecanyon_groovelee" src="https://user-images.githubusercontent.com/5944039/76290499-a64ca200-62ee-11ea-9a1c-6f7a2c0391db.png">

3. Config files (required)
name: fstore
description: Mobile commerce app by Flutter

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.6.3+32

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  logs:
    git: https://github.com/pq/logs
  flutter:
    sdk: flutter
  http: 0.12.0+4
  html_unescape: 1.0.1+3
  provider: 4.0.4
  after_layout: 1.0.7+2
  font_awesome_flutter: 8.5.0
  path: 1.6.4
  vector_math: 2.0.8
  carousel_pro: 1.0.0
  flutter_widget_from_html_core: 0.3.2+1
  configurable_expansion_tile: 1.0.0
  timeago: 2.0.26
  share: 0.6.3+5
  validate: 1.7.0
  country_pickers: 1.1.0
  shared_preferences: 0.5.6+1
  firebase_messaging: 6.0.9
  firebase_analytics: 5.0.11
  transparent_image: 1.0.0
  pull_to_refresh: 1.5.8
  localstorage: 3.0.1+4
  notification_permissions: 0.4.4
  flare_splash_screen: 3.0.1
  rate_my_app: 0.5.0+3
  flutter_range_slider: 1.4.0
  page_indicator: 0.3.0
  extended_image: 0.7.1
  flutter_screenutil: 1.0.2
  fluttertoast: 3.1.3
  intro_slider: 2.2.9
  url_launcher: 5.4.1
  firebase_core: 0.4.4
  firebase_auth: 0.15.4
  firestore_ui: 1.7.2
  flutter_webview_plugin: 0.3.10+1
  connectivity: 0.4.6+2
  random_string: 2.0.1
  google_maps_flutter: 0.5.23+1
  place_picker: 0.9.11
  cached_network_image: 2.0.0
  image_picker: 0.6.3+1
  fab_circular_menu: 0.1.4
  uuid: 2.0.4
  uni_links: 0.2.0
  flutter_staggered_grid_view: 0.3.0
  device_apps: 1.0.9
  auto_size_text: 2.1.0
  koukicons: 2.0.2
  lazy_load_scrollview: 1.0.1
  flutter_swiper: 1.1.6
  flutter_widgets: 0.1.11
  video_player: 0.10.7
  flutter_spinkit: 4.1.1+1
  percent_indicator: 2.1.1+1
  animated_text_kit: 2.0.0
  wave: 0.0.8
  http_auth: 0.2.9
  firebase_admob: ^0.9.0+10
  facebook_audience_network: ^0.4.0
  international_phone_input: 1.0.2
  pin_code_fields: 2.3.0+3
  cupertino_icons: 0.1.3
  flutter_facebook_login: 3.0.0
  webview_flutter: 0.3.19+7
  rubber: 0.4.0
  flutter_localizations:
    sdk: flutter
  carousel_slider: 1.4.1
  custom_splash: 0.0.2
  apple_sign_in: 0.1.0
  google_sign_in: 4.1.1
  google_fonts: 0.3.9
  onesignal_flutter: 2.3.3
  flutter_statusbarcolor: 0.2.3
  app_settings: 3.0.0+1
  razorpay_flutter: 1.1.2
  shimmer: 1.0.1
  animated_splash: 1.0.0
  firebase_database: 3.1.1
  event_bus: 1.1.1
  launch_review: 2.0.0
  country_code_picker: 1.2.4
  edge_alert: 0.0.1

dev_dependencies:
  flutter_launcher_icons: 0.7.4
  flutter_test:
    sdk: flutter
  pedantic: 1.8.0+1 # Analysis
  build_runner: 1.8.0
  build_web_compilers: 2.8.0

# Run this script to generate the app icon: flutter pub pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - lib/common/
    - assets/icons/categories/
    - assets/icons/tabs/
    - assets/icons/profile/
    - assets/icons/payment/
    - assets/images/
    - assets/images/country/
    - assets/images/favicon/
    - assets/html/
    - assets/images/background/
  fonts:
    - family: MaterialIcons
      fonts:
        - asset: assets/fonts/MaterialIcons.ttf
    - family: Entypo
      fonts:
        - asset: assets/fonts/Entypo.ttf
    - family: FontAwesome
      fonts:
        - asset: assets/fonts/FontAwesome.ttf
    - family: MaterialCommunityIcons
      fonts:
        - asset: assets/fonts/MaterialCommunityIcons.ttf
    - family: Feather
      fonts:
        - asset: assets/fonts/Feather.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
flutter_intl:
  enabled: true

**Comment by minhcasi** [comment]
@Jesserhee try to run this script
```
flutter channel beta
flutter upgrade --force
flutter config --enable-web
```

Then open the android studio and select the web option to run the project

**Comment by Jesserhee** [comment]
thank you for the prompt reply

I already tried this. --force does not make further changes.

I shows dependency error as below.
(it works fine with apps but I think not support web with these dependencies and I hope you can change this part to comply with web version to work)

<img width="1042" alt="스크린샷 2020-03-11 오전 9 17 55" src="https://user-images.githubusercontent.com/5944039/76370261-9fb73c80-6379-11ea-98fa-421a92df2aa9.png">

**Comment by minhcasi** [comment]
@Jesserhee - could you try to clean up the cache  by running "flutter clean" and try to run the Web from Android studio

<img width="792" alt="Screen Shot 2020-03-11 at 11 00 22" src="https://user-images.githubusercontent.com/1459805/76381262-83ba9780-6387-11ea-9eef-6999ce8b1ec7.png">

**Comment by Jesserhee** [comment]
Thank you! Minh I was able to run using Android Studio.
But it shows socket error?
Is there a way to solve this? Thanks

<img width="1679" alt="스크린샷 2020-03-11 오후 2 39 15" src="https://user-images.githubusercontent.com/5944039/76385887-43b6dd00-63a6-11ea-938e-eb2643bbca63.png">

**Comment by minhcasi** [comment]
@Jesserhee - sorry that i missed your comment, could i follow up if you could run the web app so far? Thanks
