### ISSUE TITLE
Multi Vendor Fluxstore

### ISSUE THREAD

**Issue by ayroop** [inspireui/support#2324]
Dear Inspireui

My issues with fluxstore multi vendor 1.4.6 :
1- Signup problem with default wordpress and google(Also there are not any documentation)

Error Log  :

I/BiChannelGoogleApi(13343): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@a8cb13c
W/DynamiteModule(13343): Local module descriptor class for com.google.firebase.auth not found.
I/FirebaseAuth(13343): [FirebaseAuth:] Preparing to create service connection to gms implementation
W/luxstore.vendo(13343): Accessing hidden method Ldalvik/system/CloseGuard;->close()V (light greylist, linking)

2-Sign in problem (with google) Default wordpress work fine. I have also done any setting on firebase sign in method and I copied google setting service .json in project.

3- I login to the app by default wordpress sign in which is already sign up on wordpress website as a vendor  after login when I change theme in dark mode the app will crash. Screenshot >> 0002.jpg

4-Az a vendor user in My product when I touch read more app start loading product for more then its show repeated product which are already show in top. Screentshot >> 0003.jpg

5-In dark-mode  Signup page are not clear just the signup button visible . Where can I edit this page to fix the colors? screenshot >> 0004.jpg

6- In Setting page I change the Blue Picture but when I scroll down its again back to the Blue color. Where should I edit this color? I checked style.dart but there is not in there to fix. 

 7- I want put some additional value under the product price with json. Which file in project should I edit it? Its very simple : this is the link of json : http://earnit.ae/wp-json/product_earning/v1/award?product_award=# 

8- When I change the language to Arabic if I use slider in homepage it gives me error and not loaded.

9- I need to loaded app theme by default as a  dark mode instead of light mode please help to do it.
 10- What is a firebase function in resource folder ? Where should I use it ? There is no documentation on your web sit about it.

I attach all necessary file and screenshots in zip file below.

[problemlist.zip](https://github.com/inspireui/support/files/4311561/problemlist.zip)

![Screenshot_2020-03-10 Downloads CodeCanyon](https://user-images.githubusercontent.com/57954298/76301021-4f32d700-62c6-11ea-8b92-63b76620456a.png)

![Screenshot_2020-03-10 Support for Fluxstore Multi Vendor - Flutter E-commerce Full App(1)](https://user-images.githubusercontent.com/57954298/76301126-738eb380-62c6-11ea-92f3-01a3fad4a8e6.png)

**Comment by minhcasi** [comment]
@kvt0012 - please help for investigating - thank you!

**Comment by hamidah** [comment]
Many are not available on the documentation or the demo wordpress site.
Guys, what do you do for host the web? dokan, Woocommerce? WCFM ? My wcfm not working and there aren't any guide to setup the wordpress site. to working with fluxstore

**Comment by kvt0012** [comment]
> Many are not available on the documentation or the demo wordpress site.
> Guys, what website do you used for host the data? dokan, Woocommerce? WCFM ? My wcfm not working and there aren't any guide to setup the wordpress site. to working with fluxstore

Dear sir, we install on many platforms as Woocomerce, Wordpress, OpenCart, Magento,...

**Comment by kvt0012** [comment]
Dear sir, please send me your whole project because the my other file is different with you. 
Thank you

**Comment by ayroop** [comment]
I sent whole project to your email. 
And also there is other issue in real device after creaet APK to test app, I make Enable Chat to false, but when user login it's still show in some page like Product page . And there is other issues that I'll write later.

**Comment by kvt0012** [comment]
Ok, I've already received and check it now. Thank you

**Comment by kvt0012** [comment]
About sign in problem with Goole, please follow this guide : 
https://docs.inspireui.com/fluxstore/sign-in/ 

About problem 3, I cannot see your image file, please send me your screenshot again, thank you

**Comment by ayroop** [comment]
There is no problem with sign in with wordpress users , My problem is about sign up in app this link https://docs.inspireui.com/fluxstore/sign-in/ is about sign in that I've already done in project.
screen shot of sign up problem :
![Untitled-1 (3)](https://user-images.githubusercontent.com/57954298/76608714-c82c6b80-651e-11ea-8fbd-08c7e9da900d.jpg)

 Screen shot problem 3 : 
![0002](https://user-images.githubusercontent.com/57954298/76608570-88658400-651e-11ea-97cd-cfb17ba779c5.jpg)

**Comment by kvt0012** [comment]
About problem 2, I think that because you use a character is not Latin character, so it raises this exception. I'll sign up and it is still available with special character.

**Comment by kvt0012** [comment]
About problem 3, which categories do you load, I'll load baby sitting and carpet cleaning, it's normal

**Comment by minhcasi** [comment]
@ayroop - could you help to take the whole screenshot from http://codecayon.net/downloads as we could not verify your purchase code? Thank you!

**Comment by kvt0012** [comment]
About problem 5, you can edit it on style.dart 
About problem 6, please take me your screenshot, thank you 
About problem 8, please take me your screenshot, thank you

**Comment by ayroop** [comment]
![Screenshot_2020-03-13 Support for Fluxstore Multi Vendor - Flutter E-commerce Full App](https://user-images.githubusercontent.com/57954298/76611340-03309e00-6523-11ea-8a75-afe45a1d163b.png)

**Comment by ayroop** [comment]
6: before scroll
![01](https://user-images.githubusercontent.com/57954298/76611798-be593700-6523-11ea-8990-197f6c2e6883.jpg)
7:After Scroll
![02](https://user-images.githubusercontent.com/57954298/76611805-c022fa80-6523-11ea-8856-1d331cec5a38.jpg)
8:
![Untitled-4](https://user-images.githubusercontent.com/57954298/76611917-f2345c80-6523-11ea-87d5-7df88f9caeb6.jpg)

**Comment by ayroop** [comment]
In problem 2 my characters are English

**Comment by ayroop** [comment]
Please consider this error for sign up in app:
I/BiChannelGoogleApi(13343): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@a8cb13c
W/DynamiteModule(13343): Local module descriptor class for com.google.firebase.auth not found.
I/FirebaseAuth(13343): [FirebaseAuth:] Preparing to create service connection to gms implementation
W/luxstore.vendo(13343): Accessing hidden method Ldalvik/system/CloseGuard;->close()V (light greylist, linking)

**Comment by ayroop** [comment]
There is no padding in a long texts in vendor page text header  I want it become justify and centered
![002](https://user-images.githubusercontent.com/57954298/76613005-01b4a500-6526-11ea-9ed2-e9760e747362.jpg)

**Comment by kvt0012** [comment]
About problem 2, please send me your password you use, thank you

**Comment by ayroop** [comment]
I use : @Pedram2123

**Comment by ayroop** [comment]
No solutions?!

**Comment by minhcasi** [comment]
@kvt0012 - please help to follow up the issues

**Comment by kvt0012** [comment]
Sorry for inconvenice, please tell me your email, sir. 
Thank you

**Comment by ayroop** [comment]
pooriya2008@gmail.com

**Comment by kvt0012** [comment]
I'm sorry,sir. I cannot search any source file with this email, please tell
me the another one. Thank you

**Comment by kvt0012** [comment]
I'm sorry,sir. I cannot search any source file with this email, please tell me the another one. Thank you

**Comment by ayroop** [comment]
pooriya@live.com

**Comment by kvt0012** [comment]
About problem 2, I'll check and your password is accepted, so I think please show me your email that you use to assign this, thank you

**Comment by kvt0012** [comment]
6 and 7, I'll test and it doesn't have any problem, sir 
![image](https://user-images.githubusercontent.com/49152325/76821067-7eee5b80-683f-11ea-9700-0ff4091c0e6c.png)
![image](https://user-images.githubusercontent.com/49152325/76821097-8f9ed180-683f-11ea-9929-8bc065ee9aed.png)

**Comment by kvt0012** [comment]
About problem 8, which file do you use ? I'll check and your hompage is different 
![image](https://user-images.githubusercontent.com/49152325/76821245-f328ff00-683f-11ea-92ce-56e9f31c7d37.png)


Thanks for your issue

**Comment by ayroop** [comment]
> 
> 
> There is no padding in a long texts in vendor page text header I want it become justify and centered
> ![002](https://user-images.githubusercontent.com/57954298/76613005-01b4a500-6526-11ea-9ed2-e9760e747362.jpg)

Can you fix this problem?

**Comment by ayroop** [comment]
Still I have problem with sign up : I want yo create account give me this error : 
![Untitled-1 (3)](https://user-images.githubusercontent.com/57954298/76858902-fed8ed80-6860-11ea-8040-54e3ca977c79.jpg)
And if I want sign up as a vendor I received this message : Please agree with our terms

**Comment by kvt0012** [comment]
Sure, you can configure the size of text

**Comment by ayroop** [comment]
Why you close issue? Sign UUUUP not working in your app !!! You need more Screen Shot?
