### ISSUE TITLE
[ Fluxstore Multi Vendor - Flutter E-commerce Full App] - Information about bank payment

### ISSUE THREAD

**Issue by unaluslusoy** [inspireui/support#2325]
After receiving the answer to this question, I will upload the necessary files.

Adding payment infrastructure. iyzico payment infrastructure to integrate with existing infrastructure we need help outside of the turkey.

Our iyzico plugin is active in woocommers.
iyzico developer page:

https://dev.iyzipay.com/en

I would like you to give information about this subject.

[Purchase link](https://nimbusweb.me/s/share/3918948/6ur4mbzywwglww1z1vg3)

**Comment by minhcasi** [comment]
@unaluslusoy - pls share your common/config folder here so that we could help for testing - thank you!

**Comment by unaluslusoy** [comment]
I will share the file you requested during the day.

**Comment by unaluslusoy** [comment]
common/config folder zip
[config.zip](https://github.com/inspireui/support/files/4312553/config.zip)

**Comment by minhcasi** [comment]
@minhtruong315 - please help for investigating - thank you!

**Comment by kvt0012** [comment]
Dear sir, Sorry for inconvenience but outside external plugin is out of our supporting scope. 
Thank you.

**Comment by unaluslusoy** [comment]
Hello, in the application details, there is information about the addition of payment infrastructure about the payment infrastructure. Paying attention to this matter, we purchased the application.

**Comment by unaluslusoy** [comment]
plug-ins you use the existing payment infrastructure, Turkey is unfortunately no services. For this reason, we have requested support from you. My request is that you help me in this regard. Payment infrastructure application

**Comment by unaluslusoy** [comment]
I want to have iyzico payment infrastructure integration for a fee. Could you please help me?
