### ISSUE TITLE
FluxStore Shopify - App not run on Android Studio Emulator.

### ISSUE THREAD

**Issue by samornreality2** [inspireui/support#2326]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: Can't run Shopify app on Android Studio Emulator

2. Screenshots issues (required):
Here is a video error show: https://youtu.be/akSmIB-dg78  
Here is code error: 
[Run error file.txt](https://github.com/inspireui/support/files/4312258/Run.error.file.txt)
[Dart Analysis.txt](https://github.com/inspireui/support/files/4312261/Dart.Analysis.txt)

![image](https://user-images.githubusercontent.com/9336214/76308205-dac75a80-62fc-11ea-9f4b-3baf8cf59875.png)

3. Proof of my purchased (required):
![Downloads   CodeCanyon](https://user-images.githubusercontent.com/9336214/76308139-ba979b80-62fc-11ea-8d84-d07946e2c893.png)

3. Config files (required)
https://drive.google.com/file/d/1e8q8BIxGePOHqp2A_xalCUIE9mFlJ4_A/view?usp=sharing

**Comment by luyx2412** [comment]
Hi @samornreality2 Please make sure you installed dart and flutter. Because i saw the error when run Android Studio.
![image](https://user-images.githubusercontent.com/8909619/76376780-c5dddc00-637b-11ea-8a16-d5be1a37c39e.png)
This is the document how to install flutter and dart https://flutter.dev/docs/get-started/install/windows

Thanks

**Comment by samornreality2** [comment]
Hi Luyx, is this correct installed?
![image](https://user-images.githubusercontent.com/9336214/76377770-5a493e00-637e-11ea-9cfc-fb927bb38008.png)

**Comment by samornreality2** [comment]
I found this error, does it matter? 10:53 AM	Invalid VCS root mapping
					The directory <Project> is registered as a Git root, but no Git repositories were found there.
					Configure...
![Untitled-1](https://user-images.githubusercontent.com/9336214/76380978-da73a180-6386-11ea-98d8-2e8249870a97.jpg)

**Comment by samornreality2** [comment]
Hi Luyx, here is a new video for reference what I was error: https://youtu.be/eoLQtoFrHag

Warning! This package referenced a Flutter repository via the .packages file that is no longer available. The repository from which the 'flutter' tool is currently executing will be used instead.
  running Flutter tool: C:\src\flutter\flutter
  previous reference  : C:\src\flutter\fluxstore-shopify\source\Users\minh\Data\Projects\flutter\flutter
This can happen if you deleted or moved your copy of the Flutter repository, or if it was on a volume that is no longer mounted or has been mounted at a different location. 
Please check your system path to verify that you are running the expected version (run 'flutter --version' to see which flutter is on your path).

**Comment by luyx2412** [comment]
Hi @samornreality2 I just saw your video, you add location flutter wrong place. 
![image](https://user-images.githubusercontent.com/8909619/76429859-33bcee80-63e2-11ea-8ca3-dbb775bbddbd.png)
You can see the article to fix your issue. https://github.com/flutter/flutter/issues/39885

Thanks

**Comment by samornreality2** [comment]
Hi Luyx, please give me time for checking this. I will inform you if it's will help to fix or not.
Best wish,

**Comment by samornreality2** [comment]
Hi Luyx, Which is the correct place for flutter according to your project?

**Comment by luyx2412** [comment]
Hi @samornreality2 sorry about reply you late.
You worked with example flutter, so you also work normal with this project. But you added wrong location flutter folder. So please check again your flutter location and navigate to right location look like the screenshot.

![image](https://user-images.githubusercontent.com/8909619/76638507-1d986500-657f-11ea-9724-3e94e79ea665.png)


Thanks

**Comment by samornreality2** [comment]
Dear Luyx,
I have tried it many times but still, the fact couldn't fix it.
Here is what if found: https://youtu.be/q9Fc0QmHZao

![error android studio](https://user-images.githubusercontent.com/9336214/76705467-cd520c00-6712-11ea-8a67-1535e1d68171.jpg)

Please help😰

**Comment by minhcasi** [comment]
@samornreality2 - could i check if you can run the example project from flutter - https://flutter.dev/docs/get-started/test-drive ?

It seems there is any issues with your Flutter set up

**Comment by minhcasi** [comment]
Try this script to clean up the cache:
```
flutter clean
```

Then restart the app with Android Studio

**Comment by minhcasi** [comment]
We also note some tips here - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1
