### ISSUE TITLE
Some pictures of posts are not displayed

### ISSUE THREAD

**Issue by abdoshy97** [inspireui/support#2327]
Some pictures of posts are not displayed
Sectional images are not displayed. I want to view or replace them
I want to change the writing direction from right to left

**Comment by minhcasi** [comment]
Hi, thank you for the feedback. Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads it's used to verify your proof of purchase? sorry for any inconvenience - Thank you!

**Comment by abdoshy97** [comment]
[https://drive.google.com/open?id=1Ep_Sj_E6BgpdCasFbkrFTbUjzVjm-0L2](url)
[https://drive.google.com/open?id=1Ex3ZJOejrBUA3-rLHikDh3Y7__DWd4yw](url)
These are pictures confirming my ownership of the code. I hope you will answer my question

**Comment by minhcasi** [comment]
@abdoshy97 - could you check if you have follow these step to update the image - https://docs.inspireui.com/fluxnews/getting-started/#4-install-requires-plugins

Also, please share your common file so that we could check for the issues, the RTL will be enabled by default if you change to the Arabic language - thank you!

**Comment by abdoshy97** [comment]
I am sure that I have done all the steps correctly and I have solved all the problems, but the pictures of the consultations are part, and another part is not visible. I will attach a picture for you.
![Screenshot_1583851698](https://user-images.githubusercontent.com/45370310/76677502-1ce3eb00-65e0-11ea-9767-4916cfc24237.png)

**Comment by minhcasi** [comment]
@dttrung26 - please help for investigating - thank you!

**Comment by dttrung26** [comment]
Hi @abdoshy97 , 
Kindly send me your common folder and admin access to your website via trung@inspireui, may I ask?
Many thanks!

**Comment by abdoshy97** [comment]
@dttrung26  I have sent you the file my email Abdoshy97@gmail.com

**Comment by dttrung26** [comment]
Support via mail.
