### ISSUE TITLE
mstore - Date on top left remains in English

### ISSUE THREAD

**Issue by inimist** [inspireui/support#2329]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: Date should be changed in Arabic Left to right.

2. Screenshots issues (required):   
![Screenshot_2020-03-11-12-39-20-96_f73b71075b1de7323614b647fe394240](https://user-images.githubusercontent.com/447618/76391461-95a33700-6395-11ea-9449-8fde74a15b52.png)

3. Proof of my purchased (required):  
![73525756-d1152200-4435-11ea-907b-328741347251](https://user-images.githubusercontent.com/447618/76391545-b9ff1380-6395-11ea-9b41-8658b529a9df.png)

3. Config files (required)

**Comment by luyx2412** [comment]
Hi @inimist in `src/components/HorizonList/styles.js` line 121 please replace `headerDate` with 
`  headerDate: {
    fontSize: 15,
    paddingTop: 5,
    marginBottom: 0,
    fontWeight: '400',
    opacity: 0.8,
    fontFamily: Constants.fontFamily,
    paddingHorizontal: 20,
    textAlign: "left"
  },`
![image](https://user-images.githubusercontent.com/8909619/76429366-8649db00-63e1-11ea-863b-efe9b02daa11.png)

Thanks

**Comment by inimist** [comment]
Hello, @luyx2412 I am reopening this issue.  
this is not working. the issue is when I switch this Arabic the date on the top left remains English. 
In the English date, should on the Left side in the English language and in the Arabic date should Right in the Arabic language. 
![Screenshot (19)](https://user-images.githubusercontent.com/447618/76828623-6b46f300-6847-11ea-8ba0-8f8618106635.png)
