### ISSUE TITLE
[MStore]: CeBuilder not working,  Can not get Categories and Tags

### ISSUE THREAD

**Issue by mkashifrazzaq11** [inspireui/support#233]
- Product:  MStore Pro - Complete React Native template for e-commerce
 - Your Purchased Code: f8d919b7-3308-4d8c-a454-6b2685fbae9c

When I run the project with Expo Start command my project is running fine. but I want to run it with CeBuilder when I click on customization tab, I got error "can not get categories and tags."

![cebuilder 1](https://user-images.githubusercontent.com/5534583/51908637-303bf300-23ec-11e9-8e61-7c38ba63780c.JPG)

![cebuilder2](https://user-images.githubusercontent.com/5534583/51908673-4649b380-23ec-11e9-8405-230677b74e1b.JPG)

**Comment by billiemead** [comment]
I get the exact same error and as of yet no solution.

**Comment by minhcasi** [comment]
Hi @mkashifrazzaq11 and @billiemead  - could you try to download the latest Cebuilder v0.26.2, you screenshot looks like the old version 

This issue is related to the space issue on the product PATH which already fixed - thanks

**Comment by mkashifrazzaq11** [comment]
Yes, I also checked on v0.26.2 version but still got the error.

**Comment by minhtruong315** [comment]
Hi @mkashifrazzaq11 Can you add my skype? I will help you check via teamview
my skype is minhtruong315@gmail.com

**Comment by Relimer-Technologies** [comment]
Hi, @minhtruong315 I am also facing the same problem for the M Store Pro... Can you please help me...?

**Comment by Relimer-Technologies** [comment]
> Hi @Relimer-Technologies Did you add my skype? pls ping me on my skype, I will help you check via teamview

I have added you in skype and even ping you

**Comment by minhtruong315** [comment]
Hi @Relimer-Technologies , Can you add my skype me again? my skype is minhtruong315

**Comment by minhtruong315** [comment]
@Relimer-Technologies resolved this issues. Pls enable WooCommerce Api
https://docs.woocommerce.com/document/woocommerce-rest-api/

**Comment by apisithb** [comment]
Hey I have problem like this please help me

**Comment by mkashifrazzaq11** [comment]
enter the website address like http:// not https://
