### ISSUE TITLE
FluxStore Listing

### ISSUE THREAD

**Issue by mrizwanmmc** [inspireui/support#2330]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.
![01](https://user-images.githubusercontent.com/10098991/76393466-70162d80-6395-11ea-9492-1a3db00fda71.png)
![02](https://user-images.githubusercontent.com/10098991/76393558-989e2780-6395-11ea-94aa-4125f6be4398.png)

Please check error see screenshot
---------

1. My issue:

2. Screenshots issues (required):

3. Proof of my purchased (required):

3. Config files (required)

**Comment by philipvu30** [comment]
Hi @mrizwanmmc ,

Thank you for purchasing our app. Would you mind including the common folder and the log for the command "flutter doctor -v"?

**Comment by mrizwanmmc** [comment]
Please see attached 

![screenshot](https://user-images.githubusercontent.com/10098991/76675111-f0c46c00-65d7-11ea-9f30-27b7f43a59e3.jpg)
[common.zip](https://github.com/inspireui/support/files/4332293/common.zip)

**Comment by philipvu30** [comment]
Hi @mrizwanmmc ,

My apologies for the late response. Has your issue been fixed? If not, please change your flutter channel from stable -> master. Thank you.
