### ISSUE TITLE
1.6.4 IOS didn't work

### ISSUE THREAD

**Issue by emresutuna** [inspireui/support#2331]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

No mather what we do we are getting the error below on ios with white screen after first splashscreen; (no problem with android)

![Ekran Resmi 2020-03-11 10 58 06](https://user-images.githubusercontent.com/35627584/76397646-85d32500-638c-11ea-8e8e-79683f7a7812.png)
![Ekran Resmi 2020-03-11 10 58 18](https://user-images.githubusercontent.com/35627584/76397658-8a97d900-638c-11ea-8876-b521ab273f76.png)
![Ekran Resmi 2020-03-11 10 58 34](https://user-images.githubusercontent.com/35627584/76397662-8bc90600-638c-11ea-8c58-359e3f32c61f.png)
![Ekran Resmi 2020-03-11 10 59 05](https://user-images.githubusercontent.com/35627584/76397664-8c619c80-638c-11ea-8e38-cd8cf38406af.png)
![Ekran Resmi 2020-03-11 10 59 19](https://user-images.githubusercontent.com/35627584/76397665-8cfa3300-638c-11ea-99c1-7cd7030c588a.png)
![Ekran Resmi 2020-03-11 11 58 22](https://user-images.githubusercontent.com/35627584/76399453-acdf2600-638f-11ea-9523-0a1f3d1a4e93.png)
App is waiting here !(value.isLoading)
1. My issue:

2. Screenshots issues (required):

3. Proof of my purchased (required):

3. Config files (required)

**Comment by minhcasi** [comment]
Hi, thank you for the feedback. Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads it's used to verify your proof of purchase? sorry for any inconvenience - Thank you!

**Comment by emresutuna** [comment]
![WhatsApp Image 2020-03-12 at 10 50 34](https://user-images.githubusercontent.com/35627584/76499375-a57f5180-644f-11ea-93f7-c87a31193913.jpeg)

**Comment by emresutuna** [comment]
[config.zip](https://github.com/inspireui/support/files/4323056/config.zip)
config

**Comment by emresutuna** [comment]
[config.zip](https://github.com/inspireui/support/files/4323259/config.zip)
config

**Comment by minhcasi** [comment]
@trunghieuvn - pls help to investigate the splash screen issue - thank you!

**Comment by trunghieuvn** [comment]
you run in emulator or device??
@emresutuna Have you changed any native project ?
example: bundle id, api key, GoogleService-Info.plist ??
I see in logs. native iOS crash because incorrect bundle id iOS different with GoogleService-Info.plist

please check here
![image](https://user-images.githubusercontent.com/19247680/76599976-a93ad300-6538-11ea-85c3-7c5215f3d9a8.png)

**Comment by emresutuna** [comment]
I tried both but nothing changed. Even If I get googleservice-info.plist from my personel firebase account (as com.xxx.xx) and rearrenge the IOS Bundle Id the white screen problem did not change.Should I implement my own firebase account or leave It as It is


![Ekran Resmi 2020-03-13 11 00 05](https://user-images.githubusercontent.com/35627584/76601637-623de500-651a-11ea-9b31-757dcd02036d.png)
![Ekran Resmi 2020-03-13 11 00 14](https://user-images.githubusercontent.com/35627584/76601647-68cc5c80-651a-11ea-9e28-0ce48cd4620a.png)
![Ekran Resmi 2020-03-13 11 00 22](https://user-images.githubusercontent.com/35627584/76601653-6b2eb680-651a-11ea-8171-2ff6d1ba1255.png)

**Comment by emresutuna** [comment]
This is default 1.6.4 app. 
![Ekran Resmi 2020-03-13 11 51 45](https://user-images.githubusercontent.com/35627584/76605318-5bff3700-6521-11ea-8b16-083f0c80f2f9.png)
![Ekran Resmi 2020-03-13 11 51 57](https://user-images.githubusercontent.com/35627584/76605329-5f92be00-6521-11ea-9c63-ccdc3f8e11cc.png)
![Ekran Resmi 2020-03-13 11 52 19](https://user-images.githubusercontent.com/35627584/76605334-602b5480-6521-11ea-8e5c-ec6c9eb6f689.png)
![Ekran Resmi 2020-03-13 11 52 24](https://user-images.githubusercontent.com/35627584/76605344-63bedb80-6521-11ea-8aae-b8b1f3200d6c.png)
![Ekran Resmi 2020-03-13 11 52 33](https://user-images.githubusercontent.com/35627584/76605359-68838f80-6521-11ea-84d9-ddf8964ea7a1.png)
![Ekran Resmi 2020-03-13 11 52 41](https://user-images.githubusercontent.com/35627584/76605373-6d484380-6521-11ea-80a2-364d29275c95.png)

**Comment by minhcasi** [comment]
@emresutuna pls try following solutions

1. Make sure you can run this example for ios - https://flutter.dev/docs/get-started/test-drive

2. Run 'flutter doctor' to check if there is any issues

3. Run the Fluxstore app from Android Studio, by using the the guide #1, instead of running directly from XCode

**Comment by minhcasi** [comment]
Let us know if you could resolve the project so far, free free to reopen the ticket - thank you!
