### ISSUE TITLE
[Fluxstore Pro - Universal Mobile] - IOS App Can't Build/Run

### ISSUE THREAD

**Issue by thesanjaythakkar** [inspireui/support#2332]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:

Receiving Error on flutter run ios. on pod install.

2. Screenshots issues (required):

![Screenshot 2020-03-11 at 7 11 17 PM](https://user-images.githubusercontent.com/19760004/76423154-5a702a80-63cc-11ea-8fed-6b61669342ed.png)
![Screenshot 2020-03-11 at 7 11 04 PM](https://user-images.githubusercontent.com/19760004/76423165-5e03b180-63cc-11ea-8f92-b52b6ff4818c.png)

3. Proof of my purchased (required):

![Screenshot 2020-03-11 at 7 17 26 PM](https://user-images.githubusercontent.com/19760004/76423552-fef26c80-63cc-11ea-85c5-5fe188f87733.png)

![Screenshot 2020-03-11 at 7 15 49 PM](https://user-images.githubusercontent.com/19760004/76423451-d5394580-63cc-11ea-8c3f-05d820cbcd53.png)

3. Config files (required)

![Screenshot 2020-03-11 at 7 14 40 PM](https://user-images.githubusercontent.com/19760004/76423321-95725e00-63cc-11ea-9410-a2402086b926.png)

**Comment by minhcasi** [comment]
Hi, thank you for the feedback. Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads it's used to verify your proof of purchase? sorry for any inconvenience - Thank you!

**Comment by minhcasi** [comment]
@thesanjaythakkar - could you help to try this solution to clean up the cache - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1 - thank you!

**Comment by thesanjaythakkar** [comment]
> @thesanjaythakkar - could you help to try this solution to clean up the cache - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1 - thank you!
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/0aeb324a3445c618a67c0140da8216d28af304fa/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f696d616765732f6d6f64756c65732f67697374732f676973742d6f672d696d6167652e706e67"><img alt="" height="14" src="https://camo.githubusercontent.com/4908d9947135e4536ef61d61512ee575f869bf6f/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e2e69636f"> Gist**[How to clear Flutter's Build cache?](https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1)**How to clear Flutter's Build cache? GitHub Gist: instantly share code, notes, and snippets.

Yes I tried the same, but didn't worked still.

**Comment by minhcasi** [comment]
@thesanjaythakkar - pls note that you could not run the build for ios on Window 

You can check the guide from this link https://flutter.dev/docs/get-started/test-drive to set up basic environment for Flutter on window

**Comment by thesanjaythakkar** [comment]
> @thesanjaythakkar - pls note that you could not run the build for ios on Window
> 
> You can check the guide from this link https://flutter.dev/docs/get-started/test-drive to set up basic environment for Flutter on window
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/b79d5f795eac013611f2dac92850a689fc9d3d46/68747470733a2f2f666c75747465722e6465762f696d616765732f666c75747465722d6c6f676f2d73686172696e672e706e67">**[Test drive](https://flutter.dev/docs/get-started/test-drive)**How to create a templated Flutter app and use hot reload.

I know I'm trying to run in VS Code and with IOS Simulator.

**Comment by minhcasi** [comment]
@thesanjaythakkar - pls try this solution to clean cache on Mac - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

**Comment by thesanjaythakkar** [comment]
> @thesanjaythakkar - pls try this solution to clean cache on Mac - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/0aeb324a3445c618a67c0140da8216d28af304fa/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f696d616765732f6d6f64756c65732f67697374732f676973742d6f672d696d6167652e706e67"><img alt="" height="14" src="https://camo.githubusercontent.com/4908d9947135e4536ef61d61512ee575f869bf6f/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e2e69636f"> Gist**[How to clear Flutter's Build cache?](https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1)**How to clear Flutter's Build cache? GitHub Gist: instantly share code, notes, and snippets.

Tried the same, same error again and again.

**Comment by minhcasi** [comment]
@philipvu30 - pls help to investigate this issue - thank you!

**Comment by thesanjaythakkar** [comment]
@philipvu30 can you please check screenshot and draw me any solution to build in ios. i have gone through all these steps which are drafted in doc and mentioned here by @minhcasi . Thanks

**Comment by minhcasi** [comment]
@thesanjaythakkar - could you help to check this solution

File > Workspace Settings and update to New Builder System

<img width="1053" alt="Screen Shot 2020-03-20 at 13 57 54" src="https://user-images.githubusercontent.com/1459805/77142479-cd576080-6ab2-11ea-86b2-f3d6aeab4d91.png">

**Comment by thesanjaythakkar** [comment]
@minhcasi 

![Screenshot 2020-03-20 at 1 25 26 PM](https://user-images.githubusercontent.com/19760004/77145367-515b1980-6aae-11ea-94d2-b1aa57c20ab2.png)

Please note that the error i'm receiving is while it comes to `pod install`

**Comment by minhcasi** [comment]
@thesanjaythakkar - we will update new patching today so that you can try the new build project and let us know if you can fix it - thanks

**Comment by thesanjaythakkar** [comment]
@minhcasi ok will be waiting for it

**Comment by minhcasi** [comment]
The latest hot fix is available download on gitlab - thank you!

You can submit here if have not access to the source - https://docs.google.com/forms/d/e/1FAIpQLSeuBqUkScy42V7KKhfNPj0fl581anrB1mWkbMa3p2WQt7fhfw/viewform

**Comment by minhcasi** [comment]
Please also update to 1.6.5c and let us know your checking.

Also, try to clean up the flutter cache by using some solutions from - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

**Comment by thesanjaythakkar** [comment]
It only worked when I updated to 1.6.5c and flutter beta.
