### ISSUE TITLE
Mstore Expo Facbook Login

### ISSUE THREAD

**Issue by johnnyvanrensburg** [inspireui/support#2333]
![Screenshot_20200312-032730_Chrome](https://user-images.githubusercontent.com/60583426/76478519-97aadb80-6411-11ea-977f-3c4ece809ab1.jpg)
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: I have gone through the expo document and have set up my Facebook developer side correctly.. I just dont understand how to and where to change things on the expo app for it to work to login to Facebook. All my sign ups and logins are working except Facebook. Please dont refer me back to expo docs. Cause I tried everything but dont seem to understand. I have done everthing but can not grasp the Facebook login section for expo
 
When I run expo facbook hases it gives me a error. Please can someone help me
2. Screenshots issues (required):

3. Proof of my purchased (required):
![Screenshot_20200312-032730_Chrome](https://user-images.githubusercontent.com/60583426/76478542-aabdab80-6411-11ea-8259-03f6a80d913d.jpg)

3. Config files (required)

**Comment by luyx2412** [comment]
Hi @johnnyvanrensburg This is a document how to config facebook expo. https://docs.expo.io/versions/latest/sdk/facebook/

Thanks

**Comment by Varun24041993** [comment]
Hi @johnnyvanrensburg  I was facing the same issue for Expo. You also need to add this to "facebookScheme": "fb<Your ID>",(Example => "fb1234567890" ) under EXPO.
Also if this is still not working then in the  services/FacebookAPI.js file use this complete code instead of the original code just change this (Please Make a backup of original code Just in case):


/*Starts Below*/

import { Facebook } from "@expo";

import { Config } from "@common";
import { toast, log } from "@app/Omni";

class FacebookAPI {
  async login() {
    try {
      await Facebook.initializeAsync('<Your ID>');  
      const {
        type,
        token,
        expires,
        permissions,
        declinedPermissions,
      } = await Facebook.logInWithReadPermissionsAsync({
        permissions: ['public_profile'],
      });

      if (type === 'success') {
        // Get the user's name using Facebook's Graph API
        const response = await fetch(`https://graph.facebook.com/me?access_token=${token}`);

        return token;

        //Alert.alert('Logged in!', `Hi ${(await response.json()).name}!`);
      } else {
        // type === 'cancel'
        return null;
      }
    } catch ({ message }) {
      alert(`Facebook Login Error: ${message}`);
    }
  }

  logout() {
    Facebook.logOut();
  }

  async getAccessToken() {
    return await Facebook.getCurrentFacebook();
  }

  async shareLink(link, desc) {
    const shareLinkContent = {
      contentType: "link",
      contentUrl: link,
      contentDescription: desc,
    };
    try {
      const canShow = await Facebook.canShow(shareLinkContent);
      if (canShow) {
        const result = await Facebook.show(shareLinkContent);
        if (!result.isCancelled) {
          toast("Post shared");
          log(`Share a post with id: ${result.postId}`);
        }
      }
    } catch (error) {
      toast("An error occurred. Please try again later");
      error(`Share post fail with error: ${error}`);
    }
  }
}

export default new FacebookAPI();

**Comment by johnnyvanrensburg** [comment]
> Hi @johnnyvanrensburg This is a document how to config facebook expo. https://docs.expo.io/versions/latest/sdk/facebook/
> 
> Thanks
> 
> > **[Facebook - Expo Documentation](https://docs.expo.io/versions/latest/sdk/facebook/)**

this is the kinda reply I said does not help and you still refer me to it. You not helping really unprofessional

**Comment by johnnyvanrensburg** [comment]
> Hi @johnnyvanrensburg This is a document how to config facebook expo. https://docs.expo.io/versions/latest/sdk/facebook/
> 
> Thanks
> 
> > **[Facebook - Expo Documentation](https://docs.expo.io/versions/latest/sdk/facebook/)**

this part is not work 
Android standalone app
Build your standalone app for Android.
Run expo fetch:android:hashes.
Copy Facebook Key Hash and paste it as an additional key hash in your Facebook developer page pictured above.

**Comment by Varun24041993** [comment]
Hi @johnnyvanrensburg you need to understand that if you are using expo you dont need to do these steps. Please read the Docs carefully. Just Add the facebook ID given by facebook in both places mentioned and also change the code if giving app ID does not get the job done.

**Comment by johnnyvanrensburg** [comment]
@Varun24041993 Where is both places. Please show me the path. I would appreciate it

**Comment by johnnyvanrensburg** [comment]
> > Hi @johnnyvanrensburg This is a document how to config facebook expo. https://docs.expo.io/versions/latest/sdk/facebook/
> > Thanks
> > > **[Facebook - Expo Documentation](https://docs.expo.io/versions/latest/sdk/facebook/)**
> 
> this part is not work
> Android standalone app
> Build your standalone app for Android.
> Run expo fetch:android:hashes.
> Copy Facebook Key Hash and paste it as an additional key hash in your Facebook developer page pictured above.
> 
> > **[Facebook - Expo Documentation](https://docs.expo.io/versions/latest/sdk/facebook/)**
 This part Run expo fetch:android:hashes. is NOT working. Says Error Keytool not found

**Comment by johnnyvanrensburg** [comment]
> Hi @johnnyvanrensburg you need to understand that if you are using expo you dont need to do these steps. Please read the Docs carefully. Just Add the facebook ID given by facebook in both places mentioned and also change the code if giving app ID does not get the job done.

@Varun24041993 Where is both places. Please show me the path. I would appreciate it

**Comment by johnnyvanrensburg** [comment]
> xpo fetch:android:hashes.

C:\Users\Rocco Stefano\Desktop\mstore-3.9.7\mstore-expo>expo fetch:android:hashes
'keytool' is not recognized as an internal or external command,
operable program or batch file.

keytool exited with non-zero code: 1
Set EXPO_DEBUG=true in your env to view the stack trace.

**Comment by luyx2412** [comment]
Hi @johnnyvanrensburg Please follow the comment to fix your issue https://stackoverflow.com/a/6211931/6622971

Thanks
