### ISSUE TITLE
[Fluxstore] - OnBoarding Feature

### ISSUE THREAD

**Issue by Saifahmad99** [inspireui/support#2334]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: How do I Disable On-Boarding Feature.

2. Screenshots issues (required):

3. Proof of my purchased (required):
![Screenshot (32)](https://user-images.githubusercontent.com/59877416/76488205-c85b3700-644a-11ea-930c-7fec6f19d17a.png)

3. Config files (required)

**Comment by minhcasi** [comment]
@Saifahmad99 - pls remove this line https://tppr.me/c6VB2 from the source/app.dart
