### ISSUE TITLE
[MStore Pro] -  sms registration error

### ISSUE THREAD

**Issue by 007asom** [inspireui/support#2335]
1. My issue:
Hello
I have some issues in android and ios
1st in android I didn't get the sms code it asks me to try again.
same in ios.
2nd in ios the same issue with sms and the application is not suitable for the screen. I need to scroll up or down.
2. Screenshots issues (required):

3. Proof of my purchased:
https://ibb.co/PNBWpYy
3. Config files (required)

**Comment by luyx2412** [comment]
Hi @007asom Can you send me specific screenshot about the issue?

Thanks

**Comment by 007asom** [comment]
This is from android. 
https://ibb.co/PjdMcN6

This is from iPhone sign in with Apple needs me to scroll down. 
https://ibb.co/s1YFMRh

**Comment by luyx2412** [comment]
Hi @007asom 
- Please make sure you configured right document about sms for Android on firebase.
- You can make the button or spacing is smaller to suitable your phone.

Thanks

**Comment by 007asom** [comment]
I'll check.
How to make spacing smaller?

**Comment by luyx2412** [comment]
HI @007asom You can edit in `src/containers/Login/index.js` and `src/containers/Login/styles.js` is style file of screen. Maybe you should be remove Image logo to improve this screen.

![image](https://user-images.githubusercontent.com/8909619/76699239-2a7f9a80-66de-11ea-8541-e90943206566.png)

Thanks

**Comment by 007asom** [comment]
thank you
