### ISSUE TITLE
[my-product] - 

### ISSUE THREAD

**Issue by ideas24** [inspireui/support#2337]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:

2. Screenshots issues (required):

3. Proof of my purchased (required):

3. Config files (required)

1. I am having an issue with Fluxstore Multivendor - Vendor Chat. I have completed all firebase functions setup but I keep getting the blank screen.
2. In the Categories section, Parent Category with Sub Categories throws error no products. For example, I have a Parent category called Crude Drugs with subcategories Analgesics, Laxative, Tonic. When I link a banner to the main parent category, that is Crude Drugs, it throws No Products error. But linking a banner to the subcategories shows their respective products.
3. I am using Codemagic to build the apps. I don't have a Mac or Xcode. Android builds successfully but I have an issue with iOS build - Xcode build error. I have linked iOS Automatic provisioning with my apple developer account. Please how do I edit my iOS folder to get the error-free build? Thanks.

PROOF OF PURCHASE
![proof-of-purchase](https://user-images.githubusercontent.com/34719083/76509397-e4110e00-6447-11ea-99d7-05b08d0a0b39.PNG)

**Comment by minhcasi** [comment]
@ideas24 - could you help to zip the common & config folder so that we could help for checking the categories issues

Also, share the detail screenshot / log from Codemagic - thanks

**Comment by ideas24** [comment]
Issue not resolved why is it closed? I have resolved the iOS build. Vendor Chat is still showing a blank screen. I will forward my common folder to your email and videocast of the blank screen.

**Comment by ideas24** [comment]
Please check your email @minhcasi

**Comment by minhcasi** [comment]
@ideas24 - it's closed becaused there is not reponse form the ticket - we have got your sharing config and will have a check - thank you!

**Comment by minhtruong315** [comment]
@ideas24 I sent you the email. pls check

**Comment by ideas24** [comment]
@minhtruong315 email seen. I have added you to my Firebase account. Kindly check your email. Thanks

**Comment by minhtruong315** [comment]
@ideas24 I checked your source code. There is a store in your website https://tppr.me/B70xq, but that store doesn't email, so you can't chat with that store. please update email for stores then try again.
- woo commerce api allows to get products by category id, so when you pass parent category, it will get products by parent category, it don't get all products in child catetory

**Comment by ideas24** [comment]
@minhtruong315 Alright I will check and give you feedback. Thank You

**Comment by minhtruong315** [comment]
@ideas24 you can update email for store here https://tppr.me/DN2yo

**Comment by ideas24** [comment]
@minhtruong315 Alright thanks. I will update asap

**Comment by minhtruong315** [comment]
HI, we're glad that it help, please give us some feedback/rating to this page https://codecanyon.net/downloads if the product is helpful for your business, we are working hard to update more awesome and powerful features on next coming version release. Let us know if you have any feedback. Thank you very much!

**Comment by ideas24** [comment]
@minhtruong315 Thanks for the great support. Issue fixed!
