### ISSUE TITLE
FluxStore Multi Vendor

### ISSUE THREAD

**Issue by dcpl888** [inspireui/support#2339]
When we run FluxStore Multi Vendor in Android Studio, error message occurred: adb: failed to install E:\MStore\build\app\outputs\apk\app.apk: Error launching application on AOSP on IA Emulator.  Please advise.

**Comment by kvt0012** [comment]
Dear sir, this error describe that Android Studio cannot launch Emulator Device. 
Please press Crt+Shift+A and search AVD manager, open it first and run again. 
Thank you
