### ISSUE TITLE
Mstore  - App Crash When Click on Filter

### ISSUE THREAD

**Issue by inimist** [inspireui/support#2340]
1. My issue:     
**App Crash When Click on Category Name**	
_**Home > Click any Category > Click Top Left > App Crash**_

2. Screenshots issues (required):
![2](https://user-images.githubusercontent.com/447618/76593784-3f610000-651d-11ea-9a9b-6476297f6129.png)
![1 (1)](https://user-images.githubusercontent.com/447618/76593806-4ab42b80-651d-11ea-8c2a-de4060460a13.png)
![Screenshot_2020-03-13-11-27-22-80_f73b71075b1de7323614b647fe394240](https://user-images.githubusercontent.com/447618/76593930-aa123b80-651d-11ea-80fb-f91caebaf7d9.png)

3. Proof of my purchased (required):
![73525756-d1152200-4435-11ea-907b-328741347251](https://user-images.githubusercontent.com/447618/76593847-6cadae00-651d-11ea-82e2-48be4ef926f3.png)

3. Config files (required)

**Comment by luyx2412** [comment]
Hi @inimist Can you send me the AppConfig.json and Config.js file?

Thanks

**Comment by inimist** [comment]
[common.zip](https://github.com/inspireui/support/files/4332290/common.zip)
Please find attachment.

**Comment by luyx2412** [comment]
HI @inimist in `src/containers/SubCategoryPicker/index.js` please replace this file 
[index.js.zip](https://github.com/inspireui/support/files/4334057/index.js.zip) to fix your issue.

Thankss

**Comment by inimist** [comment]
Thanks, @luyx2412 Now working fine.
