### ISSUE TITLE
Fluxstore Shopify - blog crashing

### ISSUE THREAD

**Issue by jungo19** [inspireui/support#2341]
Blog keep crashing when I select my blog individual post.

fluxstore error in nosuchmethoderror:  the method '*' was called on null

> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
Blog keep crashing when I select my blog individual post.

2. Screenshots issues (required):
![IMG_0424](https://user-images.githubusercontent.com/59526344/76594341-19544500-64b6-11ea-8341-3cbead81edff.PNG)
![IMG_0423](https://user-images.githubusercontent.com/59526344/76594349-1e18f900-64b6-11ea-858d-a68e1e22dc4a.PNG)
![IMG_0422](https://user-images.githubusercontent.com/59526344/76594354-2113e980-64b6-11ea-8d70-5e6d172e83e8.PNG)

3. Proof of my purchased (required):
<img width="804" alt="image" src="https://user-images.githubusercontent.com/59526344/76594508-954e8d00-64b6-11ea-8fcd-0b7f260417df.png">

3. Config files (required)

/// Server config
const serverConfig = {
  "type": "shopify",
  "url": "https://hearts-bio-inc.myshopify.com/",
  "accessToken": deleted
  "blog": "https://koraful.com", //Your website woocommerce. You can remove this line if it same url
  "forgetPassword": "https://heartsbio.com/account/login?checkout_url=https%3A%2F%2Fheartsbio.com%2F26118783061%2Fcheckouts%2Fb9d748c58dbd1eaa1b0951d20947a930%3Fkey%3D72bc3c1c0d17c298cedbe3b8236d1f97%26step%3Dcontact_information#recover"
};

**Comment by luyx2412** [comment]
Hi @jungo19 We will update blog with shopify in next version. Currently we used wordpress website to handle blog, so can you check blog api in your wordpress website?

Thanks

**Comment by jungo19** [comment]
I want to use Shopify blog instead of wordpress to make my job easier.

**Comment by jungo19** [comment]
I have this error too when I use Android studio for iOS 
Could not find the built application bundle at build/ios/iphonesimulator/Runner.app

**Comment by jungo19** [comment]
> Hi @jungo19 We will update blog with shopify in next version. Currently we used wordpress website to handle blog, so can you check blog api in your wordpress website?
> 
> Thanks

I have this error too when I use Android studio for iOS
Could not find the built application bundle at build/ios/iphonesimulator/Runner.app

**Comment by luyx2412** [comment]
Hi @jungo19 Please follow the ticket to fix your issue. https://github.com/flutter/flutter/issues/25370

Thanks
