### ISSUE TITLE
FluxStore multi vendor - On checkout 

### ISSUE THREAD

**Issue by Shiru-kun** [inspireui/support#2342]
when im about to place my order on checkout and complete the order it redirects me to my own website instead. 
 
![WhatsApp Image 2020-03-12 at 16 02 19 (1)](https://user-images.githubusercontent.com/54008441/76596259-5c3e0900-6506-11ea-8009-03832e163abf.jpeg)

![WhatsApp Image 2020-03-12 at 16 02 19](https://user-images.githubusercontent.com/54008441/76596300-737cf680-6506-11ea-8aaa-ef293dfc3d84.jpeg)

![WhatsApp Image 2020-03-12 at 16 02 18](https://user-images.githubusercontent.com/54008441/76596309-7972d780-6506-11ea-94fd-1f4f6b326348.jpeg)

**Comment by kvt0012** [comment]
Dear sir, please send me your config file, thank you

**Comment by Shiru-kun** [comment]
[config_file.zip](https://github.com/inspireui/support/files/4328476/config_file.zip)

**Comment by Shiru-kun** [comment]
one more thing because it redirects to my own site, it doesnt update the cart

**Comment by kvt0012** [comment]
Please send me your whole project via email : vinhkhiemt135@gmaill.com 
Thank you

**Comment by Shiru-kun** [comment]
I already send it

**Comment by kvt0012** [comment]
Sorry for inconvenience, please tell me your email again, sir.
Thank you

**Comment by Shiru-kun** [comment]
focasdk@gmail.com

**Comment by kvt0012** [comment]
I'll check and your api is not working well 
![image](https://user-images.githubusercontent.com/49152325/76833928-d2bc6d00-685e-11ea-853a-285dcb35a096.png)
Can you check again your  api? Thank you 
https://docs.inspireui.com/fluxstore/woocommerce-setup/

**Comment by Shiru-kun** [comment]
sorry my website was not working properly so restore it 
there is the new keys 
ck_c957854eadb876850216b6c2cbe5130b762bedd4 consumer key 
cs_47020330b1c0d75bad42cd790038d781bb600ce8  consumer secret 
https://krolyccloneapp.kinsta.cloud/   website

**Comment by kvt0012** [comment]
Ok sir, btw if you don't mind you can send it to my email for keeping your key. 
I'll check now.

**Comment by Shiru-kun** [comment]
sorry for take long to answer you 
i dont get why, im with this problem i just left the offline payment online... 
bank transfer and check...

**Comment by Shiru-kun** [comment]
there is my account to my website
https://krolyccloneapp.kinsta.cloud/minha-conta/
focas
62(kBUieC3mkq#Ka97v$5Dth


kvt0012 <notifications@github.com> escreveu no dia sexta, 20/03/2020 à(s)
05:28:

**Comment by kvt0012** [comment]
Dear sir, please follow and check it here, thank you 
https://docs.inspireui.com/fluxstore/multi-payment/

**Comment by Shiru-kun** [comment]
I’m doing it in has followed in docs. 
But 1st. about the template is showing Mstore API not mstore checkout. 
With this template (msstore-api) 
configured 
The app stops loading after place order with others payment types 
It only works good with cash delivery payment type. 

Focas Kandulo 
+258 844218050

**Comment by kvt0012** [comment]
Dear sir, about MStore api, please check whether update on new release .
https://wordpress.org/plugins/mstore-api/ 
About payment, @minhtruong315 Brother, can you check payment problem for him, thank you

**Comment by Shiru-kun** [comment]
Thank u, Btw about the mstore api I updated it 
but when I select Other payment type I got a blank screen and non happens 


Focas Kandulo 
+258 844218050

**Comment by Shiru-kun** [comment]
hello
im still with the problem 
can u guys help me with this

**Comment by Shiru-kun** [comment]
I updated mstore api 
but when I select Other payment type I got a blank screen and non happens

**Comment by Shiru-kun** [comment]
it works with the cash delivery but others payment types takes me to a blank screen and non happens
