### ISSUE TITLE
Fluxstore Multi Vendor - Checkout Page

### ISSUE THREAD

**Issue by tozgan** [inspireui/support#2343]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: Hi
I use Fluxstore Multi Vendor - Flutter E-commerce Full App.
I'm using the wcfm plugin on my page.
I always get 404 error on the checkout page.
I did all of the support, but the error continues.
Please can you help?

2. Screenshots issues (required): https://ibb.co/TqfXffj

3. Proof of my purchased (required): https://ibb.co/KwfKXWF

3. Config files (required)
[Arşiv.zip](https://github.com/inspireui/support/files/4328628/Arsiv.zip)

**Comment by minhcasi** [comment]
@minhtruong315 - pls update the issue - thanks

**Comment by minhtruong315** [comment]
@tozgan can u send me admin account to login to your website via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/2343

**Comment by tozgan** [comment]
https://www.allkaria.com/panel

Allkaria

ESfVd&zggiW1@jQZtm


Thank you for your help.
I bought all of your app, I am trying with all of them.

________________________________
Gönderen: minhtruong315 <notifications@github.com>
Gönderildi: 16 Mart 2020 Pazartesi 02:52
Kime: inspireui/support <support@noreply.github.com>
Bilgi: tozgan <tozgan@hotmail.com>; Mention <mention@noreply.github.com>
Konu: Re: [inspireui/support] Fluxstore Multi Vendor - Checkout Page (#2343)


@tozgan<https://github.com/tozgan> can u send me admin account to login to your website via email: truong@inspireui.com<mailto:truong@inspireui.com>
with subject: #2343<https://github.com/inspireui/support/issues/2343>

**Comment by minhtruong315** [comment]
@tozgan can u change English language?

**Comment by tozgan** [comment]
minhtruong315 
I did.
Ready

**Comment by minhtruong315** [comment]
@tozgan can u resend admin account via my email: truong@inspireui.com with subject: https://github.com/inspireui/support/issues/2343

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
