### ISSUE TITLE
[my-product] - mstore-pro

### ISSUE THREAD

**Issue by asachin16** [inspireui/support#2344]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: The server is giving 404 while registering a user. Also not able to see logs while debugging and not able to connect to Reactotron

2. Screenshots issues (required):
<img width="1680" alt="Screenshot 2020-03-13 at 5 02 36 PM" src="https://user-images.githubusercontent.com/6480091/76617533-7f8ba700-654c-11ea-9ccb-edc2e086b9cb.png">

3. Proof of my purchased (required):
<img width="1427" alt="73960559-2919c000-4931-11ea-99db-6629261e5de9 (1)" src="https://user-images.githubusercontent.com/6480091/76617125-9978ba00-654b-11ea-999e-2629939b8efc.png">

3. Config files (required)

**Comment by luyx2412** [comment]
Hi @asachin16 We removed get_nonce api, so can you check register again without debug?

Thanks

**Comment by asachin16** [comment]
@luyx2412 It worked while running the app without debug.  

I have a few more questions:

- I am not able to find "Forgot Password functionality"

- Where the address of the customer has been saved on Woocommerce

- Can you tell me how can I add more attributes to the customer table?

- Why is register API not working on debug mode.

- Why "console.log" is not logging anything console while debugging

**Comment by luyx2412** [comment]
Hi @asachin16 
- Currently we did not support "Forgot password" feature. We noted and will update in next version.
- You can see in your wordpress website. 
![image](https://user-images.githubusercontent.com/8909619/76699468-54d25780-66e0-11ea-855f-5b0737c0bb60.png)

- Sorry, i don't understand what you mean.
- You can debug with reactotron to reduce performance and see your log. This is the document https://docs.inspireui.com/mstore/project-structure/ 
- If you want to see the console.log in debug mode. Please read the document https://docs.inspireui.com/mstore/project-structure/
![image](https://user-images.githubusercontent.com/8909619/76699514-a549b500-66e0-11ea-9dc3-89cb0a775406.png)


Thanks
