### ISSUE TITLE
Fluxstore MultiVendor - Google signin not working 

### ISSUE THREAD

**Issue by daav7713** [inspireui/support#2346]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
Google signin isn't working. I follow the steps in the docs but shows me this error:
platformexception(sign_in failed com.google.android.gms.common.api.apiexception 10 null)

2. Screenshots issues (required):
![image](https://user-images.githubusercontent.com/15809768/76629886-ad4cfd80-6504-11ea-8ef8-d254adad3f75.png)

3. Proof of my purchased (required):
![image](https://user-images.githubusercontent.com/15809768/76629928-c655ae80-6504-11ea-90bc-7732b4ce62ec.png)

3. Config files (required)

**Comment by minhcasi** [comment]
@daav7713 - could i check if you have update the bundle ID and download the google service file to your project?

Could you help to double-check the guide from this link https://pub.dev/packages/google_sign_in - thank you!

**Comment by daav7713** [comment]
I, yes i have updated the bundle id and dowload the google file from firebase. Also done all the steps in that suggest here https://pub.dev/packages/google_sign_in

**Comment by minhcasi** [comment]
@kvt0012 - could you help to check this issue - thank you!

**Comment by kvt0012** [comment]
Dear sir, please follow our guide here to fix your problem 
https://docs.inspireui.com/fluxstore/sign-in/ 
Thank you

**Comment by daav7713** [comment]
Hi, i already done that and keeps the same error.

**Comment by kvt0012** [comment]
Went to this page (https://console.developers.google.com/apis/credentials)
Do not forget to select your project on the list (top left). Then go on "Oauth consent screen" 
 Filled the application logo and the application homepage link and aplication privacy policy link (with the project.firebaseapp.com) and saved.
![image](https://user-images.githubusercontent.com/49152325/77137320-f8848480-6a9f-11ea-891d-79cf28af4f36.png)

**Comment by daav7713** [comment]
Hi, i also have done that :/

**Comment by daav7713** [comment]
an still not working

**Comment by kvt0012** [comment]
Dear sir, can you send me your project via my email 
khiem@inspireui.com 
or priority, please send it to my personal email : vinhkhiemt135@gmail.com.
After you send it, please comment your email you use to send me here and I'll check it, thank you

**Comment by daav7713** [comment]
hello, ok i already sent you the project, my email its daav713@gmail.com.
 Thank you for your help

**Comment by kvt0012** [comment]
dear sir, do you check the other sign in like apple sign in, facebook sign in or phone sign in ?

**Comment by kvt0012** [comment]
If you don't mind please add me to your google and I will help you fix it, thank you

**Comment by daav7713** [comment]
Hi, the facebook signin its working fine, the phone sigin in not, and the normal signin its also working fine.
Ok i will give you access to this vinhkhiemt135@gmail.com email.

Thank you for your help

**Comment by kvt0012** [comment]
How about your google console, sir ? Thank you

**Comment by daav7713** [comment]
Hi, sorry to comment in this closed issue after a while, i leave the project for a little so i didnt see that the issue was closed, i wasnt able to solve the issue, is there any clue to help me with this problem, oi would really apreciate. thank you
