### ISSUE TITLE
[Fluxstore pro] - console  garbled, and can't get data from REST API

### ISSUE THREAD

**Issue by xuzhijvn** [inspireui/support#2348]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:

I have tow issues:

First, an error occurs when I run the project, and the error message is garbled. So, How can I fix it.

Second, The app can't get any data from REST API (woocommerce)

2. Screenshots issues (required):

[console.log](https://transfer.midrive.io/en/download.html?id=74d24504-4b38-4c56-9038-92acb573ee64)

When I copy the request to chrome, I get json like this：

request: 

`http://106.53.24.153/wp-json/wc/v2/products?category=57&featured=0&lang=en&oauth_consumer_key=ck_e221c2619465ff57ffebe2a23c257b3b22d456e8&oauth_nonce=faiumhvmpj&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1584235566&oauth_token=&oauth_version=1.0&on_sale=0&page=1&per_page=10&status=publish&oauth_signature=pemH6Q1bnshFPx9LcOLGSD9kchA%3D`

respose: 

`{"code":"woocommerce_rest_authentication_error","message":"Invalid signature - provided signature does not match.","data":{"status":401}}`

[chrome_access.png](https://transfer.midrive.io/en/download.html?id=da495ac5-dd56-423d-97e9-2ac033bb2a97)

3. Proof of my purchased (required):
![image](https://user-images.githubusercontent.com/20964259/76675516-33487180-65f5-11ea-9f2c-1db91d00bf6b.png)

3. Config files (required)

**I only changed the 'serverConfig' configuration**
[serverConfig](https://transfer.midrive.io/en/download.html?id=3d6c7201-64e5-4190-acc8-ac76c08d2c2c)

`const serverConfig = {
  "type": "woo",
  "url": "http://106.53.24.153",
  "consumerKey": "ck_e221c2619465ff57ffebe2a23c257b3b22d456e8",
  "consumerSecret": "cs_e59b14931b23172b399969f66328ad095cd3e803",
  "blog": "http://106.53.24.153", //Your website woocommerce. You can remove this line if it same url
  "forgetPassword": "http://106.53.24.153/wp-login.php?action=lostpassword"
};`

**Comment by minhcasi** [comment]
@xuzhijvn could you check if the consumese key and secrectkey are config correctly from your Wordpress site?

Also, try to turn off the debug mode from wp-config.php - if the REST API returns some warning message then the JSON format from API will not work correctly - thanks

**Comment by xuzhijvn** [comment]
> @xuzhijvn could you check if the consumese key and secrectkey are config correctly from your Wordpress site?
> 
> Also, try to turn off the debug mode from wp-config.php - if the REST API returns some warning message then the JSON format from API will not work correctly - thanks

I am sure the consumerKey and consumerSecret is correct.

![image](https://user-images.githubusercontent.com/20964259/76699490-e04fe680-66e8-11ea-983b-f3f59acb1f65.png)

![image](https://user-images.githubusercontent.com/20964259/76699512-02496900-66e9-11ea-8bf6-43467ded3a09.png)

And I found that the REST API works without consumerKey and consumerSecret, the request maybe like this:

`http://106.53.24.153/wp-json/wc/v2/products?category=57&featured=0&lang=en&on_sale=0&page=1&per_page=10&status=publish`

**Comment by minhcasi** [comment]
@xuzhijvn   - please download the latest release Fluxstore 1.6.5 and update the mstore-api to latest one - https://wordpress.org/plugins/mstore-api/ (we also include the wordpress demo from the download package)

We also note the detail changelogs from this blog -https://medium.com/@inspireui/announcing-fluxstore-1-6-337efff1791f - thank you!

**Comment by xuzhijvn** [comment]
> @xuzhijvn - please download the latest release Fluxstore 1.6.5 and update the mstore-api to latest one - https://wordpress.org/plugins/mstore-api/ (we also include the wordpress demo from the download package)
> 
> We also note the detail changelogs from this blog -https://medium.com/@inspireui/announcing-fluxstore-1-6-337efff1791f - thank you!
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/ce9a4b698e6f750660b63b4d6001e3c9ee10cdda/68747470733a2f2f70732e772e6f72672f6d73746f72652d6170692f6173736574732f62616e6e65722d373732783235302e706e673f7265763d32313631323137">WordPress.org**[MStore API](https://wordpress.org/plugins/mstore-api/)**The plugin is used for config the Mstore/FluxStore mobile and support RestAPI to connect to the app.
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/1f55d85bfc898e06f175857fb52934c71284d708/68747470733a2f2f6d69726f2e6d656469756d2e636f6d2f6d61782f313230302f312a7577347776547456575f44434261536b4f6c47786d512e6a706567"><img alt="" height="14" src="https://camo.githubusercontent.com/a1c598ee8610a8cdb0e8bdbf112f3f1c77af25cb/68747470733a2f2f63646e2d7374617469632d312e6d656469756d2e636f6d2f5f2f66702f69636f6e732f66617669636f6e2d72656272616e642d6d656469756d2e33593678705a2d3046536457446e504d3368534249412e69636f"> Medium**[Announcing Fluxstore 1.6](https://medium.com/@inspireui/announcing-fluxstore-1-6-337efff1791f)**Latest update 14/12/2019

Still can't access the REST API

![image](https://user-images.githubusercontent.com/20964259/76723791-7e908a80-6783-11ea-9ae8-63c8395dda4f.png)

![image](https://user-images.githubusercontent.com/20964259/76723805-8ea86a00-6783-11ea-8db5-e0012af9e6b0.png)

**Comment by xuzhijvn** [comment]
> @xuzhijvn - please download the latest release Fluxstore 1.6.5 and update the mstore-api to latest one - https://wordpress.org/plugins/mstore-api/ (we also include the wordpress demo from the download package)
> 
> We also note the detail changelogs from this blog -https://medium.com/@inspireui/announcing-fluxstore-1-6-337efff1791f - thank you!
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/ce9a4b698e6f750660b63b4d6001e3c9ee10cdda/68747470733a2f2f70732e772e6f72672f6d73746f72652d6170692f6173736574732f62616e6e65722d373732783235302e706e673f7265763d32313631323137">WordPress.org**[MStore API](https://wordpress.org/plugins/mstore-api/)**The plugin is used for config the Mstore/FluxStore mobile and support RestAPI to connect to the app.
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/1f55d85bfc898e06f175857fb52934c71284d708/68747470733a2f2f6d69726f2e6d656469756d2e636f6d2f6d61782f313230302f312a7577347776547456575f44434261536b4f6c47786d512e6a706567"><img alt="" height="14" src="https://camo.githubusercontent.com/a1c598ee8610a8cdb0e8bdbf112f3f1c77af25cb/68747470733a2f2f63646e2d7374617469632d312e6d656469756d2e636f6d2f5f2f66702f69636f6e732f66617669636f6e2d72656272616e642d6d656469756d2e33593678705a2d3046536457446e504d3368534249412e69636f"> Medium**[Announcing Fluxstore 1.6](https://medium.com/@inspireui/announcing-fluxstore-1-6-337efff1791f)**Latest update 14/12/2019

I found the error, It was a bad configuration of try_files in nginx.

So, only the first issues left, why the console log is garbled??

**Comment by kvt0012** [comment]
Can you send me your config file and screenshot about your problem? Thank you

**Comment by xuzhijvn** [comment]
> Can you send me your config file and screenshot about your problem? Thank you

Now, my problem only is console log garbled left, all config file is deflaut.
![image](https://user-images.githubusercontent.com/20964259/76846176-11602080-687b-11ea-800d-e1023ee8714b.png)

**Comment by kvt0012** [comment]
I think it's normal and your app will be installed, no matter about it. 
Thank you
