### ISSUE TITLE
[MMV] CAN NOT GET DATA FROM SERVER -MMV

### ISSUE THREAD

**Issue by samber91** [inspireui/support#235]
purchase code ad1ac976-3e34-4e40-a473-0985df712891

Hi i still have the problem of placing the order.  the images don't load either. i need help 
**Message : can not get data from server**

![img_9094](https://user-images.githubusercontent.com/42559522/51947077-98410800-23f1-11e9-8116-5eabeef6b13e.JPG)
![img_9093](https://user-images.githubusercontent.com/42559522/51947082-9d05bc00-23f1-11e9-8f8a-5ef63755c3fa.JPG)

**Comment by aviontech** [comment]
Hi

Am experiencing same issue with latest version. Cant load product images and occasionally get the error "Cant get data from Server".

Clicking / navigating around for a while the app crashes.
Please help.

**Comment by minhcasi** [comment]
Noted for investigating this issue - thank you!

@thangvo9x

**Comment by aviontech** [comment]
Hi 

Is this issue fixed?

**Comment by samber91** [comment]
No

**Comment by samber91** [comment]
No

**Comment by minhcasi** [comment]
@samber91 and @aviontech  - could you help to share your appconfig.json and the config.js file here, it works fine with our testing, and rarely happen with the slow network - if would be great if you could share your config for our debugging 

@thangvo9x please check this critical bug seriously - thanks

**Comment by samber91** [comment]
Or try with this one . previous version of mmv . same problem 

[Config.js.zip](https://github.com/inspireui/support/files/2824120/Config.js.zip)

**Comment by minhcasi** [comment]
It seems ok with our first testing on your sites (see below screenshot), could you try to remove the Expo app on your simulator and reinstall the package again - thanks

![simulator screen shot - iphone x - 2019-02-02 at 13 09 45](https://user-images.githubusercontent.com/1459805/52160655-5b745a00-26ec-11e9-8027-7893a71fa7dc.png)
![simulator screen shot - iphone x - 2019-02-02 at 13 10 06](https://user-images.githubusercontent.com/1459805/52160656-5b745a00-26ec-11e9-8fe4-ec93e55eaff2.png)
![simulator screen shot - iphone x - 2019-02-02 at 13 12 26](https://user-images.githubusercontent.com/1459805/52160657-5b745a00-26ec-11e9-8084-71aaefaf8969.png)

**Comment by samber91** [comment]
i'm using my android phone and iphone as simulators. so you want me to reinstall expo on my phones ?

**Comment by samber91** [comment]
Try to place order several times and let me know please , thanks

**Comment by minhcasi** [comment]
Yes, try to reinstall expo on your phone and make sure your phone could able connect to the internet

We do the second regression test and it looks ok with your config, we will check in few hours to test to see if the session is expired.

**Comment by samber91** [comment]
I have wifi at home and my internet is okay. I don’t really know why it is
acting like this on my side .
Hmmm okay i will do as you say and get back to you. Thank you for your hard
work. Please , try to place order many times and we will see. Thanks

**Comment by minhcasi** [comment]
Thank you @samber91 for replying, I'm trying to reproduce but it still no luck to find out, you can see there are many success COD order from my testing, I'm still keep the debug session on my Mac and will try on tomorrow to see if it is happen the issue -  thank you

**Comment by aviontech** [comment]
Still cant load. Where are the images loaded from? i can see new items (product tile / price and etc) loaded  from my linked Wordpress (Electro site) but the **images just wont load** with this latest version. Previously was working fine.

Please try here is my files : appconfig.json and config.js
[files.zip](https://github.com/inspireui/support/files/2825159/files.zip)

**Comment by minhcasi** [comment]
@aviontech could you try to update the mstore-check and regenerate image thumbnail again - https://inspireui.github.io/mstore-mv/docs/configwordpress - the new version come with new image optimize since version 1.2 to compatible with latest Woocommerce and Wordpress 5.0 - thank you!

**Comment by codingastronaut** [comment]
hello, im getting the issue "cant get data from server" on Mstore MV
