### ISSUE TITLE
flux store background 

### ISSUE THREAD

**Issue by mattia9055** [inspireui/support#2350]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: how to add background in home screen  with
 
2. Screenshots issues (required):

3. Proof of my purchased (required):a c45bad8-8c8c-4ae3-908a-90d2b2d2ad22 - 30 Jan 2020

3. Config files (required)

**Comment by minhcasi** [comment]
@mattia9055 - you can try to use the example theme from #18 or #20 - 

```
  "Background": {
    "height": 0.4,
    "color": "#FFC008",
    "image": "https://trello-attachments.s3.amazonaws.com/5d29325d2000ef2fad36345f/5d70b35963165534acdcea0e/e132ca446b9b3c7809de20c9a1715d49/background.gif"
  },
```
