### ISSUE TITLE
Fluxstore Pro - Issue with login page 

### ISSUE THREAD

**Issue by annaraiders** [inspireui/support#2352]
1. My issue: 
    In google login if i don't press any account for login it shows exception error.
    Update Profile is not working.

![screenshot-codecanyon net-2020 03 14-18_17_26](https://user-images.githubusercontent.com/20554668/76682234-3016ab00-6620-11ea-9286-a80069e68561.png)
![Screenshot_20200314-181203](https://user-images.githubusercontent.com/20554668/76682265-884dad00-6620-11ea-95f8-3863d242f901.jpg)
![Screenshot_20200314-181042](https://user-images.githubusercontent.com/20554668/76682266-88e64380-6620-11ea-8508-f907b0aff892.jpg)

**Comment by minhcasi** [comment]
@annaraiders - could you check if you the mstore-api is update to latest - https://wordpress.org/plugins/mstore-api/
