### ISSUE TITLE
[Fluxstore-Multivendor] - coupons are not applied

### ISSUE THREAD

**Issue by sparkmobi** [inspireui/support#2353]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
trying to apply a coupon while checking out everything works fine , until i clicked on order history and i found that the order placed with the old price (without any discount) and without passing the coupon code in the API request
2. Screenshots issues (required):
first image with the code applied successfully
https://ibb.co/WntCLc4
second image the order created without any coupon(discount) 
https://ibb.co/FzzfhRW
3. Proof of my purchased (required):
https://ibb.co/mzFkC2q
3. Config files (required)

[common.zip](https://github.com/inspireui/support/files/4333820/common.zip)

**Comment by minhtruong315** [comment]
@sparkmobi can u send me config files? and account to login on your app. I want to see your orders. Thanks

**Comment by sparkmobi** [comment]
@minhtruong315 here is the common http://pawholic.com/shop/common.rar

a demo account
client@demo.com
pass 123123

**Comment by minhtruong315** [comment]
@sparkmobi can u zip common folder? I'm using mac os, i can't extract rar file. Thanks

**Comment by sparkmobi** [comment]
@minhtruong315 http://pawholic.com/shop/common.zip

**Comment by minhtruong315** [comment]
@sparkmobi I signed in by your account: client@demo.com but i dont see any orders
https://tppr.me/8nMiT

**Comment by sparkmobi** [comment]
@minhtruong315 thats what i am getting from my end https://ibb.co/y8fPBwJ

By the way it doesnt matter if u user my config, You can try this on your own demo app 

and you will find that you just have the same issue just login to your wp-admin and create a percentage discount coupon and apply it in your app, after that chech your order history you will find that NO DISCOUNT occurs, 

if you cant make that from your end then make a new order using my config and use this coupon code "off" while ordering after that open the order history you will see the old price without any discount

**Comment by minhtruong315** [comment]
@sparkmobi Thanks for your response. I will check it

**Comment by sparkmobi** [comment]
@minhtruong315 you are welcome, any updates?

**Comment by minhtruong315** [comment]
Hi @sparkmobi sorry for delay. You can replace models/coupon.dart file then try again. it's working well on our site 
[coupon.dart.zip](https://github.com/inspireui/support/files/4384741/coupon.dart.zip)

**Comment by sparkmobi** [comment]
@minhtruong315 Thanks for your response. i check it and it works now, i will close this issue ticket.
