### ISSUE TITLE
i dont see strip configuration

### ISSUE THREAD

**Issue by ammadeyyy** [inspireui/support#2354]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: where can i find stripe configuration?

2. Screenshots issues (required): how to take screenshot if i am unable to find where to enter stripe details?

3. Proof of my purchased (required): order number 122094730

3. Config files (required)

**Comment by minhcasi** [comment]
@ammadeyyy - could we check if you have installed some extra plugin for woocommerce, example https://wordpress.org/plugins/woocommerce-gateway-stripe/?

**Comment by ammadeyyy** [comment]
stripe is working on website, from your app its redirecting to website is that how it works?

**Comment by minhcasi** [comment]
@ammadeyyy - could you share the common and config folder, we will help for checking - thank you!

**Comment by minhcasi** [comment]
@ammadeyyy - pls move the conversation to #2355 - thank you!
