### ISSUE TITLE
fluxstore how to configure login

### ISSUE THREAD

**Issue by ammadeyyy** [inspireui/support#2355]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: having difficult to configure login, facebook, google, sms, attached error and config file

2. Screenshots issues (required): 
[common.zip](https://github.com/inspireui/support/files/4334286/common.zip)
![Capture](https://user-images.githubusercontent.com/62202402/76702592-ad0f5680-66ec-11ea-96c0-a9b40550e1a2.JPG)

3. Proof of my purchased (required): invoice 122094730

3. Config files (required) attached

**Comment by minhcasi** [comment]
@ammadeyyy - could you help to take the screenshot from http://codecayon.net/downloads as we could not verify your invoice number

**Comment by ammadeyyy** [comment]
Item Purchase Code:
2fbc0fd3-16b8-465c-ab80-22397b75cc2b

**Comment by kvt0012** [comment]
> Item Purchase Code:
> 2fbc0fd3-16b8-465c-ab80-22397b75cc2b

Dear sir, if you don't mind please take screenshot your invoice from http://codecayon.net/downloads 
it will help us check easier, thank you

**Comment by ammadeyyy** [comment]
when upload here its on public, everyone can see it

**Comment by minhcasi** [comment]
@ammadeyyy - I'm sorry that the team misunderstand the verify process, it's ok with your purchase as we can see your comment on Codecayon 

Do you mind to update the rating so that we could continue to check your issue as a high priority, or we could also process a refund if you are not happy with the product so far? 

Thank you for your time

**Comment by minhcasi** [comment]
@kvt0012 - pls try to use the above common file and investigate the issue - thank you

**Comment by kvt0012** [comment]
Sorry for your inconvenience, get back to your problem, you can check this guide to configure your app. 
https://docs.inspireui.com/fluxstore/sign-in/ 

Thanks for your kind.

**Comment by kvt0012** [comment]
Dear sir,
I think this error raises because your app cannot connect to Google and Firebase, so please follow on **1.Google Sign In** on the guide to set up your app. I think you can fix your problem. 
About SMS, please follow  **3. SMS Sign in** to fix your problem, thanks for your issue.

**Comment by minhcasi** [comment]
@ammadeyyy - please help to update your config from the google, let us know if you have any issues

**Comment by minhcasi** [comment]
@ammadeyyy - please keep the update on this ticket, as there is no response - we will close the ticket, please let us know if you have any extra support - thank you!
