### ISSUE TITLE
[fluxstore-FAILURE: Build failed with an exception]

### ISSUE THREAD

**Issue by khaledsalama32** [inspireui/support#2357]
1. My issue:
after run my app this is show me

FAILURE: Build failed with an exception.

    What went wrong:
    Execution failed for task ':app:processDebugGoogleServices'.

    No matching client found for package name 'com.facekuwait.teknetstore'

    Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

    Get more help at https://help.gradle.org

BUILD FAILED in 13m 32s
Finished with error: Gradle task assembleDebug failed with exit code 1
![2020-03-14 (12)](https://user-images.githubusercontent.com/61389531/76704075-94e90880-66e7-11ea-9f09-317993c103e2.png)

2. Screenshots issues (required):
![2020-03-15](https://user-images.githubusercontent.com/61389531/76704072-8f8bbe00-66e7-11ea-92b2-c2919e972b4d.png)

3. Proof of my purchased (required):
 9e83ec40-8414-4b23-960d-0b69d207dd89
3. Config files (required)

**Comment by khaledsalama32** [comment]
please look to this  @minhcasi

**Comment by khaledsalama32** [comment]
and show me this message when i try build apk 

=================================================
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
> No matching client found for package name 'com.facekuwait.teknetstore'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10m 2s
150 actionable tasks: 6 executed, 144 up-to-date

**Comment by khaledsalama32** [comment]
hello sir @minhcasi

**Comment by khaledsalama32** [comment]
any one help me ?

**Comment by minhcasi** [comment]
@khaledsalama32 - there is an issue when you change the bundle id, could you help to double check this guide - https://docs.inspireui.com/fluxstore/customization/#1-app-nameicon-bundle-id ? Thanks

**Comment by minhcasi** [comment]
You can also zip the project folder and send via https://wetransfer.com/ to support@inspireui.com and toan@inspireui.com - thanks

**Comment by karmelcorn** [comment]
I needed to also update the bundle iD in these two files
android/app/src/debug/AndroidManifest.xml
android/app/src/profile/AndroidManifest.xml

maybe the doc https://docs.inspireui.com/fluxstore/delivery-android/ can be updated to reflect that.
