### ISSUE TITLE
fluxstore  -  1.6.5 Coupon

### ISSUE THREAD

**Issue by Senior-Gamal** [inspireui/support#2358]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
the Coupon field is not show ?!! 
2. Screenshots issues (required):
![Screenshot_1584286207](https://user-images.githubusercontent.com/27568540/76704585-a54ab480-66e2-11ea-8015-4ad59109ed38.png)

3. Proof of my purchased (required):
https://user-images.githubusercontent.com/27568540/71651886-b6159c00-2d29-11ea-9892-41ad518dc615.jpeg
3. Config files (required)
default

**Comment by minhcasi** [comment]
Hi, please override this file patching to lib/screens/cart.dart - we will update new patch today - thanks

[cart.dart.txt](https://github.com/inspireui/support/files/4335847/cart.dart.txt)
