### ISSUE TITLE
[Fluxstore WooCommerce - Flutter E-commerce Full App] - Error in Login Screen

### ISSUE THREAD

**Issue by buddiezweb** [inspireui/support#2359]
1. My issue:
This error shows and doesn't login 
2. Screenshots issues (required):
[Issues URL](https://snipboard.io/xTfQ0v.jpg)
3. Proof of my purchased (required):
[Purchased URL](https://prnt.sc/rgp9xp)
3. Config files (required)

[config_en.zip](https://github.com/inspireui/support/files/4334424/config_en.zip)
[config.zip](https://github.com/inspireui/support/files/4334431/config.zip)

**Comment by themeix** [comment]
Which version you are using? 1.6.4 or 1.6.5?

**Comment by minhcasi** [comment]
@buddiezweb - pls try to disable the debug: false from the wp-config.php and make sure the Rest API on your Woocommerce is working fine

**Comment by buddiezweb** [comment]
I had a plugin which verifies through OTP every time user tries to login and now when is disabled it. Its working.
