### ISSUE TITLE
[Fluxstore] -  List layout for the product in Homepage

### ISSUE THREAD

**Issue by themeix** [inspireui/support#2360]
1. My issue:
How to use that list layout for the categorized product in homepage? I found carousel with custom column settings but how to add list layout for any category in homepage?
 
2. Screenshots issues (required):
https://i.postimg.cc/rFXbv466/screenshot-642.png
https://i.postimg.cc/2yzWZTbR/screenshot-643.png
3. Proof of my purchased (required):
https://raw.githubusercontent.com/themeix/temp/master/screenshot-589.png
3. Config files (required)
N/A

**Comment by minhcasi** [comment]
@themeix - this layout type is not available for the product on homepage, we will update it on later release - thanks

**Comment by themeix** [comment]
Yes.. that is a nice layout.. it should be added in homepage / category

**Comment by themeix** [comment]
Installed new version yesterday and i can see new issue and also the old issue not fixed ( Profile Update issue ) 
https://i.postimg.cc/0NH3ND75/screenshot-640.png
#2230
That is not working.. I did not change anything.. everything on download package and its not working

Quantity selection not working in cart page
https://i.postimg.cc/Z5CZ7ZPC/screenshot-641.png

**Comment by themeix** [comment]
@minhcasi @philipvu30 Can you guys please respond quickly for my issues?
1. Profile update still not working in new version
2. Copon is missing
3. Quantity field not working in cart / order review page
4. Unable to process order issue in checkout webview.

**Comment by minhcasi** [comment]
@themeix - could you help to share the screenshot for these issues, also include your common/config file, try to download the 1.6.5b to fix the coupon missing issue

**Comment by themeix** [comment]
ok i will do that today..

**Comment by minhcasi** [comment]
This layout is fixed on latest 1.6.6

**Comment by themeix** [comment]
Profile update issue, Quantity issue not fixed in 1.6.6
https://screencast-o-matic.com/watch/cYeYoLyhxK
Please open that issue again to discuss and resolve that.. I dont want to create new ticket. Trying to get help you from last few weeks but still not resolved my issue.. Please give me High priority for that issue..
01) Profile update not working
02) Quantity field not working.
03) Webview not loading.

**Comment by themeix** [comment]
22 days ago i reported that issue and never been fixed it for me. I am very upset.
https://github.com/inspireui/support/issues/2230

**Comment by themeix** [comment]
No one replying here! Strange!

**Comment by minhcasi** [comment]
@themeix - pls download latest 1.6.6 that release today - thanks
