### ISSUE TITLE
[FlixStore Magento] - 

### ISSUE THREAD

**Issue by taryaalo** [inspireui/support#2361]
1. My issue:
hi i just use your documentation its amazing.
i complete my app 
i had only two issue
1 image on category tap not loaded
![Screenshot_20200315-222210](https://user-images.githubusercontent.com/26363734/76709986-29656200-670c-11ea-80fc-17a5ad9abf3b.jpg)

2 payment method not showing i just need for now cash on devilry
![Screenshot_20200315-222159]
  

please check it  
2. Screenshots issues (required):

![Screenshot_20200315-222159](https://user-images.githubusercontent.com/26363734/76710063-d6d87580-670c-11ea-8204-894e135699fd.jpg)
![Screenshot_20200315-222210](https://user-images.githubusercontent.com/26363734/76710067-e2c43780-670c-11ea-8147-039bf42e0555.jpg)

3. Proof of my purchased (required):
![cap](https://user-images.githubusercontent.com/26363734/76710051-c45e3c00-670c-11ea-992d-1d0693267c4c.png)

3. Config files (required)

**Comment by minhtruong315** [comment]
@taryaalo can u send me config files

**Comment by taryaalo** [comment]
[config.dart.txt](https://github.com/inspireui/support/files/4339039/config.dart.txt)
this is the dart file and json file 
[config_en.json.txt](https://github.com/inspireui/support/files/4339046/config_en.json.txt)

**Comment by minhtruong315** [comment]
Hi @taryaalo can u send me the category has image?

**Comment by minhtruong315** [comment]
@taryaalo can u take me screenshot for your address https://tppr.me/90cha . I want to check payment issue

**Comment by taryaalo** [comment]
Hi
I release the app in beta mode on Google play.  You can download it
https://play.google.com/store/apps/details?id=com.nmclibya.tedbeshabeta

**Comment by minhtruong315** [comment]
@taryaalo No. I only want to check your source code. please send me your address to get shipping methods

**Comment by taryaalo** [comment]
I already sent it

**Comment by taryaalo** [comment]
Is there any updates for my issue?

**Comment by minhtruong315** [comment]
@taryaalo Can u take me screenshot for address in your app?

**Comment by taryaalo** [comment]
![Screenshot_20200317-083503](https://user-images.githubusercontent.com/26363734/77147456-f289a600-6a95-11ea-8ac2-bebfb6ed1a0b.jpg)
This is the screenshot .

**Comment by minhtruong315** [comment]
https://tppr.me/nhP0B
I see it's working well on your config

**Comment by taryaalo** [comment]
Yes ,
I fix it ,
I found issue in shipping methods. We use a custome shipping matrix
method.  I just enabled taple rate shopping method.
Thanks

**Comment by minhtruong315** [comment]
Hi @taryaalo We only support default shipping methods. we will research and add it in the future. Thanks
