### ISSUE TITLE
[Fluxstore - Woo] - SOLVED FROM #2358

### ISSUE THREAD

**Issue by sketchuprzr** [inspireui/support#2362]
There is no coupon code adding section in the cart page.

![image](https://user-images.githubusercontent.com/60021696/76712255-021c8e00-6728-11ea-9abb-1252cee4f38c.png)

**Comment by minhcasi** [comment]
@sketchuprzr - pls use the patching on his ticket - we will fix it today - #2358

**Comment by minhcasi** [comment]
We have uploaded the patching to codecanyon - thank you!
