### ISSUE TITLE
[Fluxstore - Woo] -  There is a problem with applying the Coupon Code.

### ISSUE THREAD

**Issue by sketchuprzr** [inspireui/support#2363]
There is a problem with applying the Coupon Code.

Woocommerce coupon features are as follows;

1) Discount percentage
2) Fixed basket discount
3) Fixed product discount

And these can be limited.

For example,
1) Usage limit per coupon
2) Limit usage to X items
3) Usage limit per user

The problem is;

There is no problem in applying the percentage of discount in the application.
However, features 2 and 3 (Fixed product and fixed basket discount) work incorrectly.

For example, in the fixed basket coupon;
Amount "x" is deducted from the total price.
However, the application applies a discount for each product once. If there are 3 items in the basket, it counts the coupon 3 times.

For example, in the fixed product coupon;
A campaign should be implemented for each selected product & products. However, the application applies a discount of "x" for each product, no matter how many products are in the basket.

There is another feature available in coupons. if it is;
1) Minimum basket amount
2) Maximum basket amount

These features are working. But if these criteria are not met, "Error: voucher code invalid" warning is displayed.

Instead of this error, it would be more correct to get a message saying "minimum or maximum amount is not met".

Upper case and lower case problem in coupon code entry is fixed.

I detected the problems in the coupon application and collected them here.

Thank you.

**Comment by sketchuprzr** [comment]
A feature that comes in at 1.6.5,

Located in the filter option

"Attributes" and "Tags"
attracts up to 10 items to the app.

It doesn't show more than 10 items.


![image](https://user-images.githubusercontent.com/60021696/76746108-011b4900-6788-11ea-9dc9-c23d74ef087f.png)

Thanks

**Comment by minhcasi** [comment]
@sketchuprzr - thank you for the detail feedback, we will discuss with the team about these features - very best!

**Comment by minhcasi** [comment]
related #2376 for new patching 1.6.5

**Comment by minhcasi** [comment]
please move conversation to #2374
