### ISSUE TITLE
[MStore Pro] - crash on iPhone

### ISSUE THREAD

**Issue by 007asom** [inspireui/support#2364]
1- My issue:
Hello
I have a problem with ios version 12. 
It closed after loading splash screen. 
It works fine with last ios version. 
2- Screenshots issues (required):

3- Proof of my purchased:
https://ibb.co/PNBWpYy

4- Config files (required)

**Comment by luyx2412** [comment]
HI @007asom Can you send me the log file? which help me investigate easier.

Thanks

**Comment by binhetc** [comment]
I have a problem with ios version 12 too, just let you know to test with latest version
