### ISSUE TITLE
Fluxstore checkout webview error. can not place order 

### ISSUE THREAD

**Issue by ahmetozcan9211** [inspireui/support#2365]
hi i have an error about checkout api. when I click checkout webview is opening and I have an error "can not place order". after getting error I can order manually on webview but it isn't happening automaticly. help me pls.

here is my screenshot about error:
![Simulator Screen Shot - iPhone 8 Plus - 2020-03-16 at 15 32 07](https://user-images.githubusercontent.com/9422532/76758747-67f62d80-679b-11ea-949d-a2f0460e7409.png)

 and here is screen recording video:
https://drive.google.com/file/d/1d1dP88MnqFemqz1xJxtR91FAdk_xqNPO/view?usp=sharing

and here is proof my purchase

![76247666-f8d78100-6250-11ea-906d-fa2c59020ed9](https://user-images.githubusercontent.com/9422532/76758816-89571980-679b-11ea-9df5-6be4064c1393.jpg)

here is my config.dart and config_tr.json files

[Archive.zip](https://github.com/inspireui/support/files/4338228/Archive.zip)

and I will send my admin account detail for website. to your mail address :
 truong@inspireui.com 
with subject: #2365

**Comment by minhcasi** [comment]
@minhtruong315 - please help to investigate this issue as a high priority - thank you!

**Comment by ahmetozcan9211** [comment]
Hey. I still waiting for problems solve

**Comment by minhtruong315** [comment]
@ahmetozcan9211 let me check on our site

**Comment by ahmetozcan9211** [comment]
> @ahmetozcan9211 let me check on our site

okey i am waiting. I send you mail before about my admin info

**Comment by ahmetozcan9211** [comment]
> @ahmetozcan9211 let me check on our site

I am still waiting for reply

**Comment by ahmetozcan9211** [comment]
@minhcasi

**Comment by minhtruong315** [comment]
@ahmetozcan9211 can u send me full source code via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/2365
I will update on your source code to fix this issue

**Comment by ahmetozcan9211** [comment]
> @ahmetozcan9211 can u send me full source code via email: [truong@inspireui.com](mailto:truong@inspireui.com)
> with subject: #2365
> I will update on your source code to fix this issue

i sent it

**Comment by ahmetozcan9211** [comment]
> @ahmetozcan9211 can u send me full source code via email: [truong@inspireui.com](mailto:truong@inspireui.com)
> with subject: #2365
> I will update on your source code to fix this issue

I try latest Version. 1.6.5c it is still same issue

**Comment by minhtruong315** [comment]
@ahmetozcan9211 I sent you the email. pls check. thanks

**Comment by ahmetozcan9211** [comment]
> @ahmetozcan9211 I sent you the email. pls check. thanks

ty for reply. I sent admin info as reply. check it pls. thnx again

**Comment by minhtruong315** [comment]
https://tppr.me/uzyAb
I checked your website. it needs state code to process checkout. so you need to input state code in address (for example: TR01, TR02....) to work with payment webview. it's better if you make customize code at state field. it should dropdown to choose state.

**Comment by ahmetozcan9211** [comment]
> https://tppr.me/uzyAb
> I checked your website. it needs state code to process checkout. so you need to input state code in address (for example: TR01, TR02....) to work with payment webview. it's better if you make customize code at state field. it should dropdown to choose state.
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/cefacc86a313cf8111672c5003d3c0419d3b6798/68747470733a2f2f747070722e73332e616d617a6f6e6177732e636f6d2f75706c6f6164732f34656137663632316436616664633539633365343533366165356563336665392e706e67"><img alt="" height="14" src="/favicon-32x32.png"> tppr.me**[Public Screenshots - Simulator_2020-03-25 10-21-30](https://tppr.me/uzyAb)**

ty for reply and review. which one is must be drop down? app side or server side?

**Comment by ahmetozcan9211** [comment]
> https://tppr.me/uzyAb
> I checked your website. it needs state code to process checkout. so you need to input state code in address (for example: TR01, TR02....) to work with payment webview. it's better if you make customize code at state field. it should dropdown to choose state.
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/cefacc86a313cf8111672c5003d3c0419d3b6798/68747470733a2f2f747070722e73332e616d617a6f6e6177732e636f6d2f75706c6f6164732f34656137663632316436616664633539633365343533366165356563336665392e706e67"><img alt="" height="14" src="/favicon-32x32.png"> tppr.me**[Public Screenshots - Simulator_2020-03-25 10-21-30](https://tppr.me/uzyAb)**

ty again for your reply. I added to dropdown state selector to my website. and I try with write TR01 to in my app. it selected right state but still same issue. can you check it?

**Comment by minhtruong315** [comment]
copy state_tr.json to config/states folder
replace common/tools.dart and screens/checkout/shipping_address.dart
[Archive.zip](https://github.com/inspireui/support/files/4384348/Archive.zip)

**Comment by minhtruong315** [comment]
As per our checking, the multi payment feature from Fluxstore could not compatible with your site due to the conflict of "https://taqe.co.uk/checkout" existing on the site - it is possible to change this page ?

**Comment by ahmetozcan9211** [comment]
> As per our checking, the multi payment feature from Fluxstore could not compatible with your site due to the conflict of "https://taqe.co.uk/checkout" existing on the site - it is possible to change this page ?
> 
> > **[Sepet – Taqe](https://taqe.co.uk/checkout)**
> 
> otherwise, we suggest to use the native payment from Paypal / Stripe or Razopay

ty for reply. I will try. wait pls

**Comment by hamidah** [comment]
Is there any tutorial or documentatioon about webview checkout? im getting frustated for Fluxstore MV to get Shiiping Cost for earch Vendor, it is done  one website, but for FLuxstore it doesn't work.

Friend suggest to use webview, but how to do webview checkout?

**Comment by minhtruong315** [comment]
Hi @ahmetozcan9211 Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!

**Comment by ahmetozcan9211** [comment]
thank you so much @minhtruong315 solved my problem. best team ever
