### ISSUE TITLE
Check out doesn't work and sometimes it turns out black screen.

### ISSUE THREAD

**Issue by jungo19** [inspireui/support#2366]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:Check out doesn't work and sometimes it turns out black screen.

2. Screenshots issues (required):
![IMG_0457](https://user-images.githubusercontent.com/59526344/76815272-64be6a00-67ba-11ea-9fc6-e09e3599f0b8.PNG)

3. Proof of my purchased (required):
<img width="781" alt="image" src="https://user-images.githubusercontent.com/59526344/76815313-861f5600-67ba-11ea-8d8f-aded570b4409.png">

3. Config files (required)

**Comment by minhcasi** [comment]
@jungo19 - could you help to share your common and config folder so that we could reproduce the issue on your site? Thanks

**Comment by jungo19** [comment]
I only have common folder instead config folder. how can I share the folder? I have payment information too. is it secure to share here?

**Comment by minhcasi** [comment]
Hi, please send to support@inspireu.com and luyxtran264@gmail.com - thank you!

**Comment by jungo19** [comment]
Hi

Check out is still not working.

Joseph
