### ISSUE TITLE
[Fluxstore woocommerce] - Category screen shows only 10 Products 

### ISSUE THREAD

**Issue by buddiezweb** [inspireui/support#2368]
---------

1. My issue:
When i click on any category only 10 products are shown and when i click on see all it shows no product but there are products.

2. Screenshots issues (required):
![Error](https://user-images.githubusercontent.com/8961536/76837534-bcabae00-6858-11ea-9ca0-4fef36fd68fe.jpeg)

3. Proof of my purchased (required):
![Purchase Proof](https://user-images.githubusercontent.com/8961536/76837403-82421100-6858-11ea-82d3-b1d18747ab11.PNG)

3. Config files (required)
[Red Antz.zip](https://github.com/inspireui/support/files/4342348/Red.Antz.zip)

**Comment by sketchuprzr** [comment]
@buddiezweb 
@minhcasi 

This issue is related to filters. You can see more different products appear by using the "Featured", "on sale", "date" filters.

To solve this problem, you should wait for the inspireui team to add "all" to the filters.

I solved this problem by closing the filters.

**Comment by trunghieuvn** [comment]
I cannot access your website. Please check again, it causes the application to call the API to error.
Please fix it so I can check your issue. 
Thanks.

![image](https://user-images.githubusercontent.com/19247680/76923996-95f88080-6907-11ea-91be-23d343ad7425.png)

![image](https://user-images.githubusercontent.com/19247680/76924202-351d7800-6908-11ea-8236-3993e997e070.png)

**Comment by buddiezweb** [comment]
The website is live and working. 

![Website](https://user-images.githubusercontent.com/8961536/76925648-1d41f600-6900-11ea-8a9f-abe84b98238e.PNG)

**Comment by minhcasi** [comment]
@buddiezweb - could you double check the hosting if deni access from some countries, i could not reach to your website for checking neither - screenshot https://tppr.me/z2ihi

**Comment by buddiezweb** [comment]
Please share your ip address so i could unblock it.

**Comment by minhcasi** [comment]
i'm not sure, we are from Vietnam (Ho Chi Minh city and Da Nang)

not sure if this is right 113.172.xx.xx

Why don't you open for all access ?

**Comment by sketchuprzr** [comment]
Hello @buddiezweb ,

view :  https://github.com/inspireui/support/issues/2374#issuecomment-601727944 on "3)"

Try this solution
