### ISSUE TITLE
Fluxstore - How to translate errors? 

### ISSUE THREAD

**Issue by ahmetozcan9211** [inspireui/support#2369]
hi i want translate errors. for example  "username already exist"," e-mail already in use". I want translate by app language. how can I do this? 

example screen shots

![IMG_8830](https://user-images.githubusercontent.com/9422532/76839612-dc39db00-6846-11ea-96ea-cf5b7aff2cf4.PNG)
![IMG_8831](https://user-images.githubusercontent.com/9422532/76839628-e0fe8f00-6846-11ea-81e6-a7701d091462.PNG)

here my license screenshot

![76247666-f8d78100-6250-11ea-906d-fa2c59020ed9](https://user-images.githubusercontent.com/9422532/76839664-f4a9f580-6846-11ea-8099-4d467dabed65.jpg)

thank you.
---------

**Comment by minhcasi** [comment]
@ahmetozcan9211 - it seems that is the error message from the server-side - https://tppr.me/FnNe1, but you can try to check the switch/case and return as your new language - thank you!

**Comment by sketchuprzr** [comment]
Merhaba ahmet @ahmetozcan9211 ,
çeviri işlemlerinde bazı metinler bu uygulamada i10 veya i18 e eklenmemiş. bunları manuel olarak düzeltmen gerekiyor. 
senin için bu gösterdiklerini nasıl düzeltebileceğini yazacağım.

### For: "The username or password incorrect."

![image](https://user-images.githubusercontent.com/60021696/76855104-73ac2780-6861-11ea-9374-244d0e814fd5.png)

and

![image](https://user-images.githubusercontent.com/60021696/76855152-91798c80-6861-11ea-915a-391e957c8b9d.png)

### For : "Error"

![image](https://user-images.githubusercontent.com/60021696/76855170-a0603f00-6861-11ea-961f-3449f48c5c76.png)

and

![image](https://user-images.githubusercontent.com/60021696/76855193-ab1ad400-6861-11ea-9869-34b271d02107.png)

and 

![image](https://user-images.githubusercontent.com/60021696/76855203-b2da7880-6861-11ea-84f9-86eeb9fca687.png)

**Comment by ahmetozcan9211** [comment]
> @ahmetozcan9211
> [TR]
> Merhaba ahmet ,
> çeviri işlemlerinde bazı metinler bu uygulamada i10 veya i18 e eklenmemiş. bunları manuel olarak düzeltmen gerekiyor.
> senin için bu gösterdiklerini nasıl düzeltebileceğini yazacağım.
> 
> [EN]
> Hello Ahmet ,
> Some texts are not added to i10 or i18 in this application in translation processes. you need to fix them manually.
> I will write how you can fix this for you.
> 
> ### For: "The username or password incorrect."
> ![image](https://user-images.githubusercontent.com/60021696/76855104-73ac2780-6861-11ea-9374-244d0e814fd5.png)
> 
> and
> 
> ![image](https://user-images.githubusercontent.com/60021696/76855152-91798c80-6861-11ea-915a-391e957c8b9d.png)
> 
> ### For : "Error"
> ![image](https://user-images.githubusercontent.com/60021696/76855170-a0603f00-6861-11ea-961f-3449f48c5c76.png)
> 
> and
> 
> ![image](https://user-images.githubusercontent.com/60021696/76855193-ab1ad400-6861-11ea-9869-34b271d02107.png)
> 
> and
> 
> ![image](https://user-images.githubusercontent.com/60021696/76855203-b2da7880-6861-11ea-84f9-86eeb9fca687.png)
> 
> Problem Solved ;)

Thank you for reply. I want translate errors by language. My app include 2 languages. So for example when it is english i want show english error. When it is turkish i want show turkish error. I try translate it with l10n.dart file with adding New translations but i when i try adding to s.of.(context).error1 it is giving error like that "you cant declare strings in json file"

**Comment by sketchuprzr** [comment]
To do this, follow a few steps.

1 First add the term you want to add to all languages ​​in the i10 folder (english and languages ​​you want to use)

Note: "// ADD TODO" will not be. I added this as an example.

![image](https://user-images.githubusercontent.com/60021696/76881849-ce0dae00-688a-11ea-9a66-d43607c7d100.png)

2) Where you want to use these terms later, edit the text "x" in this way

[S.of (context). + Term]

![image](https://user-images.githubusercontent.com/60021696/76881886-e1b91480-688a-11ea-8990-691703600bdf.png)
 
To;

![image](https://user-images.githubusercontent.com/60021696/76881918-ed0c4000-688a-11ea-8cfe-b7b35ff8b4d5.png)


3) Then check that the file you added the language contains i10dart package. if not, add this;
( import '../../generated/l10n.dart'; )

![image](https://user-images.githubusercontent.com/60021696/76881958-00b7a680-688b-11ea-9746-195da7d81757.png)


4) then run the application, "dart analys" can detect the problem. this problem will disappear when running the application.

![image](https://user-images.githubusercontent.com/60021696/76881980-08774b00-688b-11ea-8a28-504cbf928fd5.png)

after the running application;

![image](https://user-images.githubusercontent.com/60021696/76882191-5ab86c00-688b-11ea-990c-569011225375.png)

![image](https://user-images.githubusercontent.com/60021696/76882216-62781080-688b-11ea-862c-0b892b35ec81.png)
