### ISSUE TITLE
MStore - app should start with Arabic version

### ISSUE THREAD

**Issue by inimist** [inspireui/support#2370]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: The app should start with the Arabic version. I have set the ` // set language for the App Language: "ar" `  in  `src\common\Constants.js`  but this is not working.

2. Screenshots issues (required): 

3. Proof of my purchased (required):  
![73525756-d1152200-4435-11ea-907b-328741347251](https://user-images.githubusercontent.com/447618/76841762-3f376c00-685f-11ea-8be2-bc6953a9c709.png)

3. Config files (required)

[common (1).zip](https://github.com/inspireui/support/files/4342575/common.1.zip)

**Comment by luyx2412** [comment]
Hi @inimist Please uninstall expo app and reinstall again. Because the app cached storage with English language first. 

Thanks

**Comment by inimist** [comment]
Hi, @luyx2412  I uninstalled and reinstalled again. the app still getting the same issue.
is there another way to set the Arabic language default.

**Comment by inimist** [comment]
Hi @luyx2412  Can you please tell how I can load the app default Arabic language/

**Comment by luyx2412** [comment]
Hi @inimist Can you send me the AppConfig.json and Config.js file?

Thanks

**Comment by inimist** [comment]
Hi, @luyx2412  Please Find the attachments. 
[common.zip](https://github.com/inspireui/support/files/4367730/common.zip)
Thanks

**Comment by luyx2412** [comment]
Hi @inimist 
I just tested your config which worked normal. So please check again or send me the screenshot.
![image](https://user-images.githubusercontent.com/8909619/77443267-8b654c00-6e1d-11ea-9b25-32db37f30fb4.png)

Thanks

**Comment by inimist** [comment]
Hi, @luyx2412 app is starting in Arabic but  `RTL: true, `  is not working.

**Comment by luyx2412** [comment]
Hi @inimist Please follow the comment to add RTL expo version https://stackoverflow.com/a/58446878/6622971

Thanks
