### ISSUE TITLE
[FluxStore-Multi-Vendor] - Problem at checkout

### ISSUE THREAD

**Issue by unaluslusoy** [inspireui/support#2371]
1. My issue:
The bank does not perform the transaction when I select the transfer option in the payment stage and click the complete transaction button.

2. Screenshots issues (required): 
![image](https://user-images.githubusercontent.com/31100257/76842610-94698280-684b-11ea-86ab-44ddb663b65c.png)

3. Proof of my purchased (required):https://nimbusweb.me/s/share/3918948/6ur4mbzywwglww1z1vg3

3. Config files (required)
[config.zip](https://github.com/inspireui/support/files/4342621/config.zip)

**Comment by unaluslusoy** [comment]
https://youtu.be/tcjqTdr7ZJA

In the video link I shared above, I get an error in the payment section. Shipping method settings are available on the site. But I get the Choose a shipping method warning. Can you give information about the subject.

**Comment by minhtruong315** [comment]
@unaluslusoy Thanks for your response. I'm checking payment webview on our site. I will let you know later

**Comment by minhtruong315** [comment]
@unaluslusoy Can u send me full source code via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/2371
I will help you fix your issue

**Comment by minhtruong315** [comment]
I sent you the email. please check

**Comment by unaluslusoy** [comment]
I have reviewed your mail. I have responded about the subject.

**Comment by minhtruong315** [comment]
supported via email

**Comment by ykarapanca** [comment]
@unaluslusoy  Selamlar. Bende iyzicoyu woocommerce e bağlamama rağmen fluxstore da problem yaşıyorum. Siz çözdüyseniz yardımcı olurmusunuz acaba? Teşekkürler.

**Comment by unaluslusoy** [comment]
@ykarapanca üzerinde çalışmam devam ediyor.

**Comment by ykarapanca** [comment]
@unaluslusoy tamamdır. Bende uğraşmaya başladım. bir yere varabilirseniz bilgi verirseniz sevinirim. Yapabilirsem bende veririm:) teşekkürler
