### ISSUE TITLE
[Fluxstore - Woo] - 1.6.5 To be edited features

### ISSUE THREAD

**Issue by sketchuprzr** [inspireui/support#2376]
In this topic, I will write all the issues that need to be edited for 1.6.5.

### 1) Solved
The newly added tawk.to chat feature opens via webview. but when the keyboard is active, webview doesn't shrink.

Ss;
![tawkto](https://user-images.githubusercontent.com/60021696/76856033-79a30800-6863-11ea-8536-baea5245d188.gif)

**Comment by trunghieuvn** [comment]
Hi @sketchuprzr , to fix this error, open the file `lib/widgets/smartchat.dart` and add `resizeToAvoidBottomInset: true` to `WebviewScaffold`.

![image](https://user-images.githubusercontent.com/19247680/76922258-be31b080-6902-11ea-992b-9729e53a791b.png)

**Comment by sketchuprzr** [comment]
Hello @trunghieuvn 
Thanks for solution. I will try this solution.

### 2) Onesignal Pushnotification does not work in iOS version.
There is another big problem I want to share right now.
Onesignal Pushnotification does not work in iOS version. And I couldn't see a detailed explanation for the onesignal ios installation in docs.inspireui.

![image](https://user-images.githubusercontent.com/60021696/76946460-1d002580-6915-11ea-8b06-2e5d98c8acd7.png)

Such a problem occurs when I do like the onesignal sdk installation guide. Please can you verify that onesignalpushnotification works in ios version and share a detailed explanation here?

Android is not a problem. But ios is also a problem.

**Comment by minhcasi** [comment]
@sketchuprzr - the latest version is available on gitlab, please have a check and let us know - thank you!

Please note that we will remove the onesignal from this release due to the unstable of the library that cause user's config issues 

Please move conversation to #2374

- thank you!
