### ISSUE TITLE
[my-product] - 

### ISSUE THREAD

**Issue by zawwinhtunn** [inspireui/support#2377]
https://github.com/zawwinhtunn/zawwin.git 
this is my commom/config file.Please help me .I cannot change my website link in android studio.only show products from http://dokan.mstore.io/.please fix my issue

**Comment by minhcasi** [comment]
Hi, thank you for the feedback. Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads it's used to verify your proof of purchase?

Sorry for any inconvenience, we will reopen the ticket when it is verified, thank you!

**Comment by zawwinhtunn** [comment]
This is my purchease screen shot sir. My app  cannot login with google and
facebook. I filled google api and facebook api keys. But only show error Waning
thereis an issue with the app during request the data,please contact admin
for fixing the issues PlatformException
(sign_in_failed,com.google.android.gms.common.api.AplException:10,null).please
fix my issue.

**Comment by minhcasi** [comment]
@zawwinhtunn - please help to drag the image again as we could not see the image - thank you!

**Comment by zawwinhtunn** [comment]
Are you see sir?

**Comment by zawwinhtunn** [comment]
Hello sir
