### ISSUE TITLE
When registering user from app it is not working, is any custom configuration required for this i am using multi-hosting domain for wordpress site.

### ISSUE THREAD

**Issue by digant201** [inspireui/support#2379]
wordpress nonce not generating.
getting this "You must include 'nonce' var in your request. Use the 'get_nonce' Core API method."

**Comment by sketchuprzr** [comment]
Why did you write such a long title?

It is better to write the name of the application you bought in the title and the title of the problem briefly.

**Comment by minhcasi** [comment]
@digant201 - thank you for the feedback
Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads it's used to verify your proof of purchase? 

Sorry for any inconvenience, we will reopen the ticket when it is verified, thank you!

**Comment by digant201** [comment]
Hello,

          Ok i got it. But why i wrote it because that is the my main issue
that i don't know about what server requirement should be fulfilled for
your app and that is not mentioned in any documentation. firstly i wrote it
in the mail but you said add these issue on github.
