### ISSUE TITLE
ListApp is does not working fine and After intergrated to changing our root path of our website and woocommerce key same problems occurs.

### ISSUE THREAD

**Issue by Pavithran10** [inspireui/support#238]
**Mandatory Info (please complete the following information):**
Product:[ListApp]
Version:1.5.3b
Theme: Listing

**Describe the issues**
1.We are facing many issue and error in Listapp application after installing the app.
2.And then same problems occurs while changed the root of the our website and woocommerce key in config.js file we got the errors.

**Screenshots**

**Additional context**

**Comment by minhcasi** [comment]
duplicate with #239
