### ISSUE TITLE
Product review not displaying in product review tab when added some custom review from admin panel not showing in product page in app    here is i got from debugger

### ISSUE THREAD

**Issue by digant201** [inspireui/support#2380]
http://192.168.0.105/wp-json/wc/v3/products/141/reviews/?oauth_consumer_key=&oauth_nonce=&oauth_signature_method=HMAC-SHA256&oauth_timestamp=&oauth_version=1.0&lang=en&oauth_signature=

   this url is showing this in debugger

	Status Code
	404
	Method
	GET
	Duration (ms)
	205
	code:rest_no_route
	message:No route was found matching the URL and request method
	status:404

**Comment by sketchuprzr** [comment]
Why did you write such a long title?

It is better to write the name of the application you bought in the title and the title of the problem briefly.

**Comment by minhcasi** [comment]
@digant201 - thank you for the feedback. 
Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads it's used to verify your proof of purchase? 

Sorry for any inconvenience, we will reopen the ticket when it is verified, thank you!

**Comment by digant201** [comment]
[image: Downloads CodeCanyon.png]

**Comment by digant201** [comment]
You didn't reply on my previous email, as you requested to send app
purchase screenshoot.

i sent it.

Didn't you get it ?

Do you have any other verification process i will do it.

You didn't answer yet.

**Comment by digant201** [comment]
![unnamed](https://user-images.githubusercontent.com/62238856/77823455-53158480-7121-11ea-9f27-10ef26c0ca0a.png)
