### ISSUE TITLE
[Fluxstore Multi Vendor] - Create Product not working when adding images through Flutter App

### ISSUE THREAD

**Issue by sumitaneja007** [inspireui/support#2381]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: Create Product not working when adding images through Flutter App. While when I'm not adding images during creating a product, it is working fine.

2. Screenshots issues (required):  
![WhatsApp Image 2020-03-18 at 1 28 50 AM](https://user-images.githubusercontent.com/53478001/76896527-fd86df80-68b7-11ea-89ac-57f654a63003.jpeg)

3. Proof of my purchased (required):  
![theme](https://user-images.githubusercontent.com/53478001/76896539-037cc080-68b8-11ea-825d-298653105f76.jpeg)

3. Config files (required)  
[config.zip](https://github.com/inspireui/support/files/4345584/config.zip)

**Comment by minhcasi** [comment]
Closed as duplicate verify the purchase with #2267

Please help to post your comment on this page https://codecanyon.net/item/fluxstore-multi-vendor-flutter-ecommerce-full-app/25013325 to help verify your purchase again - thanks
