### ISSUE TITLE
[Fluxstore] - when i change language to Chinese not appear

### ISSUE THREAD

**Issue by limitlessfirm** [inspireui/support#2382]
1. My issue: When i change language to Chinese not appear and the espain language appear instead of Chinese

2. Screenshots issues (required):
![Capture](https://user-images.githubusercontent.com/59250639/76898558-9c9edd80-689e-11ea-97c0-b834ec7de1a8.JPG)

3. Proof of my purchased (required):
![screenshot](https://user-images.githubusercontent.com/59250639/76898573-a32d5500-689e-11ea-8879-a7261a428887.JPG)

3. Config files (required)

**Comment by minhcasi** [comment]
@limitlessfirm - could i confirm if you are using the latest 1.6.5? Thank you!

**Comment by limitlessfirm** [comment]
when i used latest version 1.6.5 the Chinese language working but in Arabic language the product color not appear 
<img width="270" alt="color-002" src="https://user-images.githubusercontent.com/59250639/77032789-1376cc00-69ae-11ea-8b4c-0a11c6a377c5.png">

**Comment by minhcasi** [comment]
Hi, you can add the config on this files for other languages (this setting is use for multi attributes)

<img width="993" alt="Screen Shot 2020-03-20 at 19 57 08" src="https://user-images.githubusercontent.com/1459805/77165488-fc86c580-6ae4-11ea-8843-f4e93c720a1a.png">
