### ISSUE TITLE
[FluxStore-woo 1.6.4] - Gradle does not have execution permission.

### ISSUE THREAD

**Issue by EdelcioBatista** [inspireui/support#2383]
HI.

I run new version [FluxStore-woo 1.6.4]  and I have new problem:

Launching lib/main.dart on ASUS Z012DC in debug mode...
[!] Gradle does not have execution permission.
    You should change the ownership of the project directory to your user, or move the project to a directory with execute permissions.
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

Can you help me?

Proof of purchase:
6b4b9df0-0ac5-472b-8e05-7a7f32b607cf

Thank you.

**Comment by minhcasi** [comment]
@EdelcioBatista - please try to move your project to C folder (on window) or run this script (on MacOS or linux)
```
chmod a+rx android/gradlew
```

**Comment by minhcasi** [comment]
Let us know if you could fix the issues, you can reopen the ticket it need any extra support -  thank you!
