### ISSUE TITLE
[Flux Store Woocommerce] - Variable product price doesn't update for some products

### ISSUE THREAD

**Issue by anazareth559** [inspireui/support#2384]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:

For some products like this: https://jainsusa.com/store/4e-jain-spin-clean-filter/  
the variable product pricing is not getting updated on the mobile app. It works for some products but for the above product the variable pricing is wrong in the app. 

2. Screenshots issues (required):

<img width="960" alt="Screen Shot 2020-03-17 at 9 26 10 PM" src="https://user-images.githubusercontent.com/48661656/76925228-f9e26100-6895-11ea-8dd7-45e2b1e23b11.png">

<img width="91" alt="Screen Shot 2020-03-17 at 9 26 05 PM" src="https://user-images.githubusercontent.com/48661656/76925243-01a20580-6896-11ea-9667-72d4b56cc891.png">

3. Proof of my purchased (required):
<img width="791" alt="Screen Shot 2020-03-17 at 9 28 14 PM" src="https://user-images.githubusercontent.com/48661656/76925302-3d3ccf80-6896-11ea-861b-3afe8dcc8441.png">

<img width="958" alt="Screen Shot 2020-03-17 at 9 28 03 PM" src="https://user-images.githubusercontent.com/48661656/76925306-40d05680-6896-11ea-9e0c-1dcf2c152cfb.png">

3. Config files (required)

[config-files.zip](https://github.com/inspireui/support/files/4346938/config-files.zip)

**Comment by anazareth559** [comment]
Here is the app screenshot

<img width="345" alt="Screen Shot 2020-03-17 at 9 25 22 PM" src="https://user-images.githubusercontent.com/48661656/76925499-edaad380-6896-11ea-8293-bd840bb70936.png">

**Comment by minhcasi** [comment]
@anazareth559 - sorry we could not verify your purchase, could you help to give a comment on this product https://codecanyon.net/item/fluxstore-woocommerce-flutter-ecommerce-full-app/24050041 - thank you!

**Comment by anazareth559** [comment]
<img width="667" alt="Screen Shot 2020-03-18 at 7 33 14 AM" src="https://user-images.githubusercontent.com/48661656/76971757-d8f82b00-68ea-11ea-9de7-776a8e412094.png">

Here is my purchase code: a32e2b8a-f37c-4fbd-9542-cf88f960c667

**Comment by minhcasi** [comment]
Verified, we will investigate the issue and let you know - thank you!

**Comment by philipvu30** [comment]
Hi @anazareth559 
Could you please check your product detail configuration on this page again? Because it does not show the correct prices according to your site. You can check them here. 

![image](https://user-images.githubusercontent.com/54442328/77153483-6777d280-6acc-11ea-8d46-e6773dcc8309.png)

If you are not sure you have configured them right or not, please send me images of your product configuration. Or you can create a support account for your site and send it to this email: toan@inspireui.com. I'll help you check later. Thank you

**Comment by minhcasi** [comment]
@anazareth559 please help to keep updated on this ticket, you can reopen the issue if there is any extra problem - thank you!
