### ISSUE TITLE
[fluxstore woocommerce] -  Bugs and feature request

### ISSUE THREAD

**Issue by immortal-kid** [inspireui/support#2385]
Purchase: http://prntscr.com/re4bzl

1. (Bug) I tried to change the stock quantity from checkout screen and in review screen, it's not working. i cannot select number in dropdown.

2. (Bug) I gave  EnableReview to false in config.dart and also disabled review in woocommerce settings, but review is still showing. Seems like that option is not working. (I removed review option manually in each page)

3. (Feature request) login with OTP is fine, but you could have added an otp screen after checkout and before placing order, this could stop lot of fake orders. Think about it once.

4. (Feature Missing) there are 4 different category layouts http://prntscr.com/rib42a , in version 1.5.5 you had given an option in config.dart page to change these layouts in const CategoriesListLayout = kCategoriesLayout.sideMenu;. Later that option was removed, now there is now way to change the layouts. Add this back.

4. (View request) http://prntscr.com/rib5wh This screenshot is from some other app. Usually ecommerce stores doesn't have to be always grid view, you could add a list view like this http://prntscr.com/rib5wh . This is very useful view.  (I know if we know flutter we can do it ourselves, but not everyone who bought the script is aware of flutter customization)

**Comment by minhcasi** [comment]
@immortal-kid we will check the issue 1 and 2, also investigate opt feature on 3

The setting on 4 is moved to the config.json, it could be set under the tabbar (category screen section)

We could not read the screenshot you have share, please help to attach to this ticket - thank you!

**Comment by immortal-kid** [comment]
![871f0667-d0fc-4e92-9574-ef549d412315](https://user-images.githubusercontent.com/10250665/77223502-30182d00-6b83-11ea-89d1-9440eea5a4ad.jpg)

(View request) This screenshot is from some other app. Usually ecommerce stores doesn't have to be always grid view, you could add a list view like this. This is very useful view. (I know if we know flutter we can do it ourselves, but not everyone who bought the script is aware of flutter customization)

**Comment by minhcasi** [comment]
@immortal-kid - please check the latest release 1.6.5c that include and listview and fixed the issues - thank you!

**Comment by immortal-kid** [comment]
given any thoughts on otp feature to confirm orders?

**Comment by minhtruong315** [comment]
Hi @immortal-kid we dont support otp screen when checkout now.

**Comment by immortal-kid** [comment]
i know, i suggest it as feature request, this feature will prevent lot of fake orders. Think about it

**Comment by minhtruong315** [comment]
Yes. Thanks. we will research and add it in the future.
