### ISSUE TITLE
whein I log in with google and facebook  .show error

### ISSUE THREAD

**Issue by zawwinhtunn** [inspireui/support#2386]
this is my commom/config file
https://github.com/zawwinhtunn/zawwin.git

whein I log in with google .show this error

Waning thereis an issue with the app during request the data,please contact admin for fixing the issues PlatformException (sign_in_failed,com.google.android.gms.common.api.AplException:10,null)

please help me how can I fix

**Comment by minhcasi** [comment]
Hi, thank you for the feedback. Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads it's used to verify your proof of purchase? 
Sorry for any inconvenience, we will reopen the ticket when it is verified, thank you!

**Comment by zawwinhtunn** [comment]
https://github.com/zawwinhtunn/zawwin/blob/master/Capture1.PNG

this is my  purchase screenshot

**Comment by minhcasi** [comment]
@zawwinhtunn - could you double-check the setting from https://docs.inspireui.com/fluxstore/sign-in/ - thank you!
