### ISSUE TITLE
Mstore -  Date on top left remains in English 

### ISSUE THREAD

**Issue by inimist** [inspireui/support#2387]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:   https://github.com/inspireui/support/issues/2329

2. Screenshots issues (required):  
![76828623-6b46f300-6847-11ea-8ba0-8f8618106635](https://user-images.githubusercontent.com/447618/76964940-8306a000-6949-11ea-9dac-fad3a80f1dc9.png)

It should be convert be like الأربعاء 11 مارس

3. Proof of my purchased (required):
![73525756-d1152200-4435-11ea-907b-328741347251](https://user-images.githubusercontent.com/447618/76964872-65d1d180-6949-11ea-9687-d2b778d05d0a.png)

3. Config files (required)
[common (1).zip](https://github.com/inspireui/support/files/4349157/common.1.zip)

**Comment by minhcasi** [comment]
@inimist - the date-time format is not yet supported multi-language - we have noted as a feature request for next improvement - thank you!

**Comment by minhcasi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Date on top left remains in English](https://trello.com/c/0vxpfjjO/24-date-on-top-left-remains-in-english)

**Comment by minhcasi** [comment]
moved to backlog
