### ISSUE TITLE
[FluxStore Magento] - issue in new version 1.6.5 can't add product in to cart

### ISSUE THREAD

**Issue by taryaalo** [inspireui/support#2388]
1. My issue:
i try to implement the new version 1.6.5 but i get an error to add a product to cart i get this error in a terminal 
"Failed assertion: boolean expression must not be null"
 Evan wen i use your default data and configuration without any editing 

2. Screenshots issues (required):
![Screenshot_20200318-161732](https://user-images.githubusercontent.com/26363734/76971041-58aae780-6935-11ea-95a8-abf571688cb9.jpg)
![error](https://user-images.githubusercontent.com/26363734/76971140-78421000-6935-11ea-8621-43c6fa51138d.PNG)

3. Proof of my purchased (required):
![cap](https://user-images.githubusercontent.com/26363734/76971232-96a80b80-6935-11ea-9e30-90fc17df62d2.png)

3. Config files (required)

[config.dart.txt](https://github.com/inspireui/support/files/4349492/config.dart.txt)

**Comment by midotaha** [comment]
**### I have the same problem after config url with my site , i cant to add any product to cart**

![FluxStore](https://user-images.githubusercontent.com/19406537/77124344-ac135780-6a53-11ea-8941-0286a99b8bab.png)

**Comment by minhtruong315** [comment]
@taryaalo @midotaha replace models/cart.dart and try again
[cart.dart.zip](https://github.com/inspireui/support/files/4358422/cart.dart.zip)

**Comment by minhcasi** [comment]
latest hotfix is also available on gitlab.

you can also submit on this link to access to the source https://docs.google.com/forms/d/e/1FAIpQLSeuBqUkScy42V7KKhfNPj0fl581anrB1mWkbMa3p2WQt7fhfw/viewform

Thank you!
