### ISSUE TITLE
[BeoNews Pro] - 

### ISSUE THREAD

**Issue by nerfenoff** [inspireui/support#2389]
1. My issue:
In CeBuilder, the first step throws the error " Currently, CeBuilder hasn't supported this project yet.". I tried to choose expo.
https://prnt.sc/rihlk8

You can specify the folder "beonews-pro" and it seems to work. But the result is the following error:
![F01i2hv0h4s](https://user-images.githubusercontent.com/28098608/76980714-96fed180-694a-11ea-814d-4ed0e9bb335b.jpg)

2. Screenshots issues:
I chose a folder "beonews-expo"
https://prnt.sc/rihn1l

3. Proof of my purchased:
purchase code
https://prnt.sc/rihsxa

https://prnt.sc/rivblf
4. Config files (required)
expo
[package.txt](https://github.com/inspireui/support/files/4349907/package.txt)
pro
[package.txt](https://github.com/inspireui/support/files/4349962/package.txt)

**Comment by minhtruong315** [comment]
@nerfenoff add my skype: minhtruong315
I will help u check via remote

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!

**Comment by shah0203** [comment]
hi, I  bought Fluxstore WooCommerce, which folder should I install? I'm getting an error message: Currently, CeBuilder hasn't supported this project yet. Thanks
