### ISSUE TITLE
[ListApp] Some more internal features issue occur 

### ISSUE THREAD

**Issue by Pavithran10** [inspireui/support#239]
**Mandatory Info (please complete the following information):**
Product:[ListApp]
Version:1.5.3b
Theme: Listing

**Describe the issues**
1.All feature are realoadiing in the home page that means in home page it redirect to booking page and then once again reloading into flash screen.
2.This same issue occur in the map also. while opening map at first time it has loading into splash screen again reload into homepage. Otherwise, while touch the screen or zooming the map white blank screen will appear.

**Screenshots**
[err video.zip](https://github.com/inspireui/support/files/2815882/err.video.zip)

**Additional context**

**Comment by minhcasi** [comment]
Hi could you share the config.js file and AppConfig.json - thank you!

**Comment by Pavithran10** [comment]
Can I give purchase code here itself? Is it not public forum ?

**Comment by Pavithran10** [comment]
I'm attached the ListApp config.js and AppConfig.json in below zip.
[project js files.zip](https://github.com/inspireui/support/files/2816360/project.js.files.zip)

**Comment by thangvo9x** [comment]
Okie. i'll check it and response to you. Thanks

**Comment by Pavithran10** [comment]
Thanks, i'll check it and reply

**Comment by Pavithran10** [comment]
Thanks,ListApp new version is working fine.But some feature error is there.

In that new version of ListApp application in tabmenubar category list cover image not appear. I've attached image below.
![err1](https://user-images.githubusercontent.com/46148046/52052673-21387a80-257d-11e9-8897-9460c9bcfe54.png)

**Comment by Pavithran10** [comment]
In that before issue small different is there. That is in the category cover images is only not appearing in list view format. But image support in grid view properly. 

![err2](https://user-images.githubusercontent.com/46148046/52054547-eafdf980-2582-11e9-9cc4-5310a8170e65.png)

**Comment by Pavithran10** [comment]
Regenerate image plugin is not avaiable, regenerate thumbnails plugin is there. what want to do. second options  containers/Categories/index.js line 112 is also that code line not available. otherwise if you just send the that plugin link.

**Comment by Pavithran10** [comment]
Hi, I need another help while selecting each categories list item its redirect to booking page in that page favourites and share icon while clicking it showing the error msg. I've attached that booking page and error page in below link
[error pages.zip](https://github.com/inspireui/support/files/2820440/error.pages.zip)

**Comment by thangvo9x** [comment]
Hi. you can try update content each pos for content in its.

**Comment by Pavithran10** [comment]
Thanks for your reply. what want to i need to update mylisting theme or all over the listapp

**Comment by thangvo9x** [comment]
https://github.com/inspireui/support/issues/253
