### ISSUE TITLE
[Fluxstore Woocommerce] - Variation Options only show 8 variations

### ISSUE THREAD

**Issue by buddiezweb** [inspireui/support#2392]
1. My issue:
In the App i have set color variation as option and it only shows 8 options but there are 80 options

2. Screenshots issues (required):
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-03-19 at 16 27 47](https://user-images.githubusercontent.com/8961536/77060500-ac353800-69fe-11ea-87cd-3b092d252fc1.png)

3. Proof of my purchased (required):
![Screenshot 2020-03-19 at 4 29 26 PM](https://user-images.githubusercontent.com/8961536/77060603-d686f580-69fe-11ea-8891-0181be3b8297.png)

3. Config files (required)

[config.dart.zip](https://github.com/inspireui/support/files/4354068/config.dart.zip)
[config_en.json.zip](https://github.com/inspireui/support/files/4354074/config_en.json.zip)

**Comment by philipvu30** [comment]
Hi @buddiezweb 
Have you configured the constant.dart file? Please add more colors according to your site as the image below. You can find it here: lib/common/constants.dart. Thank you.

![image](https://user-images.githubusercontent.com/54442328/77154136-b2deb080-6acd-11ea-8d01-62858d259914.png)

**Comment by buddiezweb** [comment]
But for the color variation there are code number like 1 to 80 not the color itself.

**Comment by philipvu30** [comment]
Hi @buddiezweb,
I couldn't understand what you are struggling with. Please provide an image of your issue. Thank you.

**Comment by buddiezweb** [comment]
![](https://user-images.githubusercontent.com/8961536/77060500-ac353800-69fe-11ea-87cd-3b092d252fc1.png)
 1 to 16 are the color code shown but there are 80 different color code but only show this and cant scroll down.

**Comment by philipvu30** [comment]
Hi @buddiezweb ,

Your site couldn't load so I cannot test the api. Is there something wrong? Also please update your app to our latest update. Thank you

**Comment by philipvu30** [comment]
Closed due to no response.
