### ISSUE TITLE
I got an issue after past the code for opencart

### ISSUE THREAD

**Issue by MoahmmedSB** [inspireui/support#2393]
Hi there,

I have copied the opencart. dart from the sample file, but after I did that I got a lot of issues on more than one file

**Comment by MoahmmedSB** [comment]
<img width="1792" alt="‏لقطة الشاشة ٢٠٢٠-٠٣-١٩ في ٣ ٤٠ ٤٨ م" src="https://user-images.githubusercontent.com/62385560/77068981-9a509680-69f8-11ea-909e-9cb91fcc5baa.png">

**Comment by MoahmmedSB** [comment]
error line 101

**Comment by minhcasi** [comment]
@MoahmmedSB - please change to   "layout": "simpleType",

Or you can use the same config.dart but only change the serverConfig section

We will also fix this issue on next release - thank you!
