### ISSUE TITLE
[fluxstore] - side menu icon  

### ISSUE THREAD

**Issue by mattia9055** [inspireui/support#2394]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: how i can change side menu icon 

2. Screenshots issues (required):
![1_SNa0LFUV_99XWT-oIHh9Ig](https://user-images.githubusercontent.com/61138288/77070511-07f9c400-69f3-11ea-8519-26cc3bb036de.png)

3. Proof of my purchased (required): - verified

3. Config files (required)

**Comment by minhcasi** [comment]
@mattia9055 - pls help to check this guide https://docs.inspireui.com/fluxstore/customization/#1-how-to-customize-any-ui-from-app - thank you!
