### ISSUE TITLE
[Fluxstore MV] - Gen run debug on Android Emulator

### ISSUE THREAD

**Issue by antixirus** [inspireui/support#2395]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: I can't run debug on Android Emulator

2. Screenshots issues (required):
![gambar](https://user-images.githubusercontent.com/57300649/77117709-239db280-6a65-11ea-97a9-1e899b2158b4.png)

3. Proof of my purchased (required):
![gambar](https://user-images.githubusercontent.com/57300649/77117746-331cfb80-6a65-11ea-948b-023b2a360339.png)

3. Config files (required)
{
  "Background": {
    "height": 0.3,
    "color": "#fbb110",
    "image": "https://sangkek.co.id/wp-content/uploads/2020/01/FLASH-BANNER.jpg"
  },
  "HorizonLayout": [
    {
      "layout": "logo",
      "showMenu": true,
      "showSearch": false
    },
    {
      "layout": "header_text",
      "fontSize": 23.0,
      "height": 0.11,
      "padding": 30.0,
      "rotate": [
        ""
      ],
      "type": "fade"
    },
    {
      "layout": "header_search",
      "text": "Lagi butuh apa hari ini?"
    },
    {
      "layout": "bannerImage",
      "isSlider": true,
      "autoPlay": true,
      "showNumber": false,
      "design": "default",
      "showBackGround": true,
      "radius": 2.0,
      "height": 0.15,
      "items": [
        {
          "category": 81,
          "image": "https://sangkek.co.id/wp-content/uploads/2020/01/GRATIS-ONGKIR1.jpg",
          "padding": 15.0
        },
        {
          "category": 81,
          "image": "https://sangkek.co.id/wp-content/uploads/2020/01/FLASH-SALE.png",
          "padding": 15.0
        },
        {
          "category": 60,
          "image": "https://sangkek.co.id/wp-content/uploads/2020/01/FLASH-SALE-CABE.jpg",
          "padding": 15.0
        },
        {
          "category": 82,
          "image": "https://sangkek.co.id/wp-content/uploads/2020/01/RESERVASI.png",
          "padding": 15.0
        },
        {
          "category": 77,
          "image": "https://sangkek.co.id/wp-content/uploads/2020/01/ROTI-GEDANG.jpg",
          "padding": 15.0
        },
        {
          "category": 110,
          "image": "https://sangkek.co.id/wp-content/uploads/2020/01/MAKAN-SIANG.jpg",
          "padding": 15.0
        }
      ]
    },
    {
      "layout": "category",
      "type": "icon",
      "wrap": true,
      "size": 1.2,
      "radius": 50.0,
      "noBackground": true,
      "columns": 4,
      "padding": 10.0,
      "items": [
        {
          "category": 52,
          "image": "https://sangkek.co.id/wp-content/uploads/2020/01/cate11.png",
          "colors": [
            "#3CC2BF",
            "#3CC2BF"
          ],
          "originalColor": true
        },
        {
          "category": 79,
          "image": "https://sangkek.co.id/wp-content/uploads/2020/01/cate22.png",
          "colors": [
            "#3E6AB5",
            "#3E6AB5"
          ],
          "originalColor": true
        },
        {
          "category": 56,
          "image": "https://sangkek.co.id/wp-content/uploads/2020/01/cate33.png",
          "colors": [
            "#53A2CC",
            "#53A2CC"
          ],
          "originalColor": true
        },
        {
          "category": 57,
          "image": "https://sangkek.co.id/wp-content/uploads/2020/01/cate44.png",
          "colors": [
            "#53688A",
            "#53688A"
          ],
          "originalColor": true
        },
        {
          "category": 77,
          "image": "https://sangkek.co.id/wp-content/uploads/2020/01/cate55.png",
          "colors": [
            "#53688A",
            "#53688A"
          ],
          "originalColor": true
        },
        {
          "category": 82,
          "image": "https://sangkek.co.id/wp-content/uploads/2020/01/cate99.png",
          "colors": [
            "#53688A",
            "#53688A"
          ],
          "originalColor": true
        },
        {
          "category": 113,
          "image": "https://sangkek.co.id/wp-content/uploads/2020/02/samsung1.png",
          "colors": [
            "#53688A",
            "#53688A"
          ],
          "originalColor": true
        },
        {
          "category": 117,
          "image": "https://sangkek.co.id/wp-content/uploads/2020/02/gift.png",
          "colors": [
            "#53688A",
            "#53688A"
          ],
          "originalColor": true
        },
        {
          "category": 118,
          "image": "https://sangkek.co.id/wp-content/uploads/2020/03/dapursangkek.png",
          "colors": [
            "#53688A",
            "#53688A"
          ],
          "originalColor": true
        },
        {
          "category": 119,
          "image": "https://sangkek.co.id/wp-content/uploads/2020/03/davieandco.png",
          "colors": [
            "#53688A",
            "#53688A"
          ],
          "originalColor": true
        }
      ]
    },
    {
      "name": "Terakhir dilihat",
      "layout": "recentView"
    },
    {
      "name": "Promo Bulan Ini",
      "image": "",
      "layout": "threeColumn",
      "isSnapping": true,
      "category": 85
    },
    {
      "name": "Makan cuma 10rb",
      "image": "",
      "layout": "threeColumn",
      "isSnapping": true,
      "category": 110
    },
    {
      "layout": "bannerImage",
      "items": [
        {
          "url": "https://www.instagram.com/sangkek.id/",
          "image": "https://sangkek.co.id/wp-content/uploads/2020/01/Follow-Sangkek.jpg",
          "padding": 5.0
        },
        {
          "url": "https://www.instagram.com/sangkek.id/",
          "image": "https://sangkek.co.id/wp-content/uploads/2020/01/Free-Delivery.jpg",
          "padding": 5.0,
          "featured": true
        }
      ]
    },
    {
      "name": "Artikel",
      "layout": "blog"
    }
  ],
  "Setting": {
    "MainColor": "#fbb110",
    "ProductListLayout": "list"
  },
  "TabBar": [
    {
      "layout": "home",
      "icon": "assets/icons/tabs/icon-home.png"
    },
    {
      "layout": "category",
      "categoryLayout": "card",
      "icon": "assets/icons/tabs/icon-category.png"
    },
    {
      "layout": "search",
      "icon": "assets/icons/tabs/icon-search.png"
    },
    {
      "layout": "cart",
      "icon": "assets/icons/tabs/icon-cart2.png"
    },
    {
      "layout": "profile",
      "icon": "assets/icons/tabs/icon-user.png"
    }
  ]
}

**Comment by antixirus** [comment]
@minhtruong315

**Comment by nahuelbourdichon** [comment]
I'm having the same issue,
Thanks

**Comment by softcomsas** [comment]
I'm having the same issue,
Thanks

![evato](https://user-images.githubusercontent.com/38671293/77121308-a567ee80-6a19-11ea-96c7-d93b81b125b2.png)

**Comment by midotaha** [comment]
**### Hi 
Also i have the same problem**

![FluxStore](https://user-images.githubusercontent.com/19406537/77124059-e7615680-6a52-11ea-8056-d750c20e896b.png)

**Comment by minhcasi** [comment]
Hi, we are trying to reproduce this issue and will update solution shortly - thank you!

@trunghieuvn

**Comment by minhcasi** [comment]
Updating onesignal in app/build.gradle seems to fix it

dependencies {
   // (OLD) implementation 'com.onesignal:OneSignal:3.11.4, 3.99.99'
    implementation 'com.onesignal:OneSignal:3.12.7'
}

-----

Integrate with the Onesignal is painful as it is not quite stable, we will consider to remove this feature on next release 1.6.6 to prevent these problems, you can try to integrate by your own - thank you!

**Comment by antixirus** [comment]
@minhcasi Will this affect the applications that have been launched? Like on Play Store or App Store?

**Comment by antixirus** [comment]
@minhcasi And I think, I found a bug in the Fluxstore MV, in the cart, when im swipe right, the order section will appear, so indirectly, we can place an order without having to order even one item. Can you solve it sir?

**Comment by minhcasi** [comment]
@antixirus - this is only build issue form Onesignal that not effect to the app on production, we will check the swipe right issue on Fluxstore MV - thank you!

**Comment by antixirus** [comment]
@minhcasi Thank you sir, and one question before im close the issue, how to im configure my config to surge? Because when im try upload my config in surge, and change the link of config to surge link, my app can't Response the config

Check the picture.

![gambar](https://user-images.githubusercontent.com/57300649/77144085-8881f880-6ab7-11ea-9c3d-f457409fbe14.png)

**Comment by minhcasi** [comment]
@antixirus - try to update the config.json to your Wordpress site via mstore-api and enable the caching option - the app will work better by this approach (using cloud for the config.json is old solution)

**Comment by minhcasi** [comment]
latest hot fix is available download on gitlab - thank you!
