### ISSUE TITLE
Fluxstore Pro - FAILURE: Build failed with an exception

### ISSUE THREAD

**Issue by jahnkit** [inspireui/support#2396]
Hi,
When I try to launch the application with Android Studio I receive this error every time, I still followed the video.
Can you help me please thank you

Issue:
![ISSUE](https://user-images.githubusercontent.com/23610159/77128178-70768e80-6a4f-11ea-8740-56522c95484f.PNG)

Proof of my purchased:
![purchase code](https://user-images.githubusercontent.com/23610159/77128186-78363300-6a4f-11ea-9fe9-3f6980525e27.PNG)

Config files (required)
What is the configuration file?

**Comment by minhcasi** [comment]
Duplicate of #2395
