### ISSUE TITLE
[FluxStore 1.6.5] - OneSignal Error

### ISSUE THREAD

**Issue by saifmuhtar** [inspireui/support#2397]
1. My issue:

This code is fine yesterday. But when I run it today, it give me these errors:

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not find any matches for com.onesignal:OneSignal:[3.11.2,3.99.99] as no versions of com.onesignal:OneSignal are available.
     Required by:
         project :app
   > Could not find any matches for com.onesignal:OneSignal:[3.11.2,3.99.99] as no versions of com.onesignal:OneSignal are available.
     Required by:
         project :app > project :onesignal_flutter

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 25s
Finished with error: Gradle task assembleDebug failed with exit code 1

2. Screenshots issues (required):

![Screenshot 2020-03-20 at 10 03 06 AM](https://user-images.githubusercontent.com/34681804/77130221-08956780-6a92-11ea-85c4-0aae8cdcdea9.png)

3. Proof of my purchased (required):

![purchase](https://user-images.githubusercontent.com/34681804/77130313-6629b400-6a92-11ea-9cbf-1e109d0bf209.jpg)

4. Config files (required)

[config.dart.zip](https://github.com/inspireui/support/files/4357631/config.dart.zip)

Thank you for your support 🙏🏻

**Comment by minhcasi** [comment]
@saifmuhtar - please move the conversation to #2395 - it seems the issue form onesignal library
