### ISSUE TITLE
MStore Pro - ceBuilder Issue

### ISSUE THREAD

**Issue by CloudExpressTeam** [inspireui/support#2398]
When we've to save the new product settings via ceBuilder, there's a blank white screen!

Also, if we need to save as Android or IOS app it takes longer then fail to save the product

**Comment by minhcasi** [comment]
Hi, thank you for the feedback. Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads it's used to verify your proof of purchase? 
Sorry for any inconvenience, we will reopen the ticket when it is verified, thank you!

**Comment by CloudExpressTeam** [comment]
Hello, It's one of our clients who need us to set up the app
I can send you the purchase code he provided us with!

**Comment by minhcasi** [comment]
Oki thanks, please share the purchase code - thanks

**Comment by CloudExpressTeam** [comment]
I sent i to your Gmail account << minhcasi@gmail.com >> right now
please check and reply here

**Comment by CloudExpressTeam** [comment]
@minhcasi 
Hi Bro, Can you help please??

**Comment by minhcasi** [comment]
@CloudExpressTeam - it's verified - thank you!

Could i know if you are testing the Cebuilder on which OS (mac or window), it's possible please share the screenshot issues when you run on the Cebuilder - thank you!

**Comment by CloudExpressTeam** [comment]
Windows, Sir

Here are screenshots for CeBuilder
https://i.imgur.com/iXkBWLz.png

The issue is here when build android package
https://i.imgur.com/lBjQEKI.png

**Comment by CloudExpressTeam** [comment]
Please put our ticket in consideration

We need to solve the problem ASAP

**Comment by minhtruong315** [comment]
@CloudExpressTeam add my skype: minhtruong315. I will help you check it via remote

**Comment by CloudExpressTeam** [comment]
Why closed??
we haven't solved this yet!

is this guy belong to your team? minhtruong315

**Comment by minhcasi** [comment]
@minhtruong315 - please continuous follow up the issue - thank you!

**Comment by CloudExpressTeam** [comment]
ceBuilder always crash on build android or IOS app

**Comment by minhtruong315** [comment]
@CloudExpressTeam i dont see any response from you on the skype https://tppr.me/7HNY5

**Comment by CloudExpressTeam** [comment]
@minhcasi here the confirmation of the purchase code
