### ISSUE TITLE
FLUXSTORE PRO - 

### ISSUE THREAD

**Issue by sashincodes** [inspireui/support#2399]
1. My issue: 
Hi i have purchase this app and still cant to figure out what seems to be the issue, I have succesfully intergrated it with WooCommerce and can see all my products, shipping methods, and payment gateways however. My shipping method does not update like my website where free shipping is chosen automatically after a certain amount. My payment gateway shows up and when clicking to process the payment i am stuck at a white screen. PLEASE HELP ASAP

2. Screenshots issues (required):
![WhatsApp Image 2020-03-20 at 10 59 27](https://user-images.githubusercontent.com/62413077/77149385-21098000-6a9a-11ea-8316-a0f4cb7b58fc.jpeg)
![WhatsApp Image 2020-03-20 at 10 59 50](https://user-images.githubusercontent.com/62413077/77149389-223aad00-6a9a-11ea-8f26-f7927f25f46c.jpeg)
![WhatsApp Image 2020-03-20 at 11 00 04](https://user-images.githubusercontent.com/62413077/77149390-236bda00-6a9a-11ea-8386-bc060ff82b81.jpeg)

3. Proof of my purchased (required):
![image](https://user-images.githubusercontent.com/62413077/77149260-d982f400-6a99-11ea-970b-05351054959b.png)

3. Config files (required)

**Comment by minhcasi** [comment]
@sashincodes - could you try to update the latest one 1.6.5, it seems you are using the old one that could cause the issue - thanks

**Comment by sashincodes** [comment]
Hi I have tried with updating it and I get the same error
