### ISSUE TITLE
i dont know how to start 

### ISSUE THREAD

**Issue by alaradi2006** [inspireui/support#24]
**Mandatory Info (please complete the following information):**
 - Product: [e.g. MStore, ListApp]
 - Your Purchased Code: [get from https://codecanyon.net/downloads]
(we may not reply if you are not our customer)
a9c6782d-8c5d-4811-8c4a-2ccc9d6be005
**Describe the issues**
i download xde expo plus all software 
i dont know how to get things started to start mstore project
i just need some guide to help me to start working on mstore to make it running for my dokan stores
**Screenshots**

**Additional context**
Add any other detail logs about the problem here.

**Comment by reconshield** [comment]
i think you should refer to documentation.dont skip any installation steps

**Comment by reconshield** [comment]
yes..using mac or win? send me ur skype

**Comment by minhcasi** [comment]
@alaradi2006 could you take the whole screenshot please

**Comment by minhcasi** [comment]
Please reopen if you still could not fix the issue - thank you!

**Comment by alaradi2006** [comment]
yes stilll have the problem will send you screenshot

________________________________

**Comment by alaradi2006** [comment]
![1](https://user-images.githubusercontent.com/45144621/48776854-01b1e580-ece2-11e8-939c-6d47aaf99df7.jpg)

**Comment by alaradi2006** [comment]
i just opened expo then opened mstore folder
