### ISSUE TITLE
[MStore Pro Shipping Issue]

### ISSUE THREAD

**Issue by hammadhassan** [inspireui/support#240]
Product: [MStore]
Purchase Code: f20afe4a-778e-4089-bcb2-7ec1bb4ed49b

[Shipping Zone]
I did config my app shipping zone to 2 & also hard coded my Country to Netherlands but on checkout page shipping method is not displaying.

![image](https://user-images.githubusercontent.com/5791268/52044718-a06d8480-2564-11e9-8f52-69726004329a.png)

Config file is attached. Please check & help me to fix it.

[Config-3.6.7.txt](https://github.com/inspireui/support/files/2816497/Config-3.6.7.txt)

**Comment by luyx2412** [comment]
Hi @hammadhassan Can you invite me to your wordpress admin which help check your zone id?

Thanks

**Comment by hammadhassan** [comment]
Yes sure. Give me you email address. i will send you credentials of my wordpress site.

**Comment by luyx2412** [comment]
Hi luyxtran264@gmail.com

**Comment by luyx2412** [comment]
HI @hammadhassan we just came back our work. Let me check and reply you soon. 

Thanks

**Comment by luyx2412** [comment]
HI @hammadhassan Please download MStore Pro new version 3.6.8 which fixed your issue.

Thanks

**Comment by hammadhassan** [comment]
any update regarding this issue @luyx2412 ?

**Comment by luyx2412** [comment]
Hi @hammadhassan please download latest version Mstore Pro to fix your issue. Currently your version is 3.6.7, and the latest version is 3.6.8.

Thanks.

**Comment by hammadhassan** [comment]
okay. Thanks.
