### ISSUE TITLE
FluxStore Pro

### ISSUE THREAD

**Issue by MoahmmedSB** [inspireui/support#2401]
Hi there,

I have configured my application successfully, but there is one issue which will stop all client form purchasing.

the issues
1. The application keeps crashing when I open any product
2. can not add any item to the cart
3. application keeps crashing when I open categories 

I think its something related to the images sizes 

Also, you can test it from you end
URL: https://alqannas-store.com/

I have installed the module

**Comment by minhcasi** [comment]
@MoahmmedSB  - Hi, thank you for the feedback. Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads it's used to verify your proof of purchase? 
Sorry for any inconvenience, we will reopen the ticket when it is verified, thank you!

**Comment by MoahmmedSB** [comment]
Sure here is it
![B41587DE-07AB-422D-8D57-D1759AB3D48F](https://user-images.githubusercontent.com/62385560/77155754-0f7ea300-6aaf-11ea-9fe8-e1b130e1ba06.png)

**Comment by minhcasi** [comment]
@MoahmmedSB - thank you for quick response, please help to share the common and config folder so that we could reproduce the issue

**Comment by MoahmmedSB** [comment]
[Archive.zip](https://github.com/inspireui/support/files/4359046/Archive.zip)

**Comment by MoahmmedSB** [comment]
Sorry I forgot to change the url 
Please correct it to
https://alqannas-store.com/

**Comment by MoahmmedSB** [comment]
Hello is there any updates?

**Comment by philipvu30** [comment]
Hi @MoahmmedSB ,

I have tested your config, and everything seems fine to me. Have you updated the app to the latest version (1.6.5)?

If the issues persist after updated, please contact me via 
Skype live:vuthanhtoan30
Email: philipvu@inspireui.com
