### ISSUE TITLE
[Fluxstore] - new version new issue

### ISSUE THREAD

**Issue by ahmetozcan9211** [inspireui/support#2402]
there is a "buy now" button in new version. but when i use buy now button i can't go back.

**Comment by minhcasi** [comment]
latest hot fix is available download on gitlab - thank you!

You can submit here if have not access to the source - https://docs.google.com/forms/d/e/1FAIpQLSeuBqUkScy42V7KKhfNPj0fl581anrB1mWkbMa3p2WQt7fhfw/viewform
