### ISSUE TITLE
[Beonews] - Search Function 

### ISSUE THREAD

**Issue by kevlict** [inspireui/support#2403]
My issue: Unable to search non-English Post

Hello.

My post are mainly Chinese and when I use Beonews app to search my post, it could not show any search results. My I ask how can this be fixed?

Thanks
Kevin

**Comment by minhcasi** [comment]
Hi, thank you for the feedback. Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads it's used to verify your proof of purchase? 
Sorry for any inconvenience, we will reopen the ticket when it is verified, thank you!

**Comment by kevlict** [comment]
![278AA11D-31E8-4892-AC7D-E5328967F721](https://user-images.githubusercontent.com/54314498/77216975-ac961600-6b59-11ea-952a-e74d46b9ad65.png)

Thanks! Please reopen.

**Comment by kevlict** [comment]
Thanks.

I have already uploaded.

「Minh Pham <notifications@github.com>」在 2020年3月21日 週六，上午9:46 寫道：

**Comment by kevlict** [comment]
Thanks

I have already uploaded

「Minh Pham <notifications@github.com>」在 2020年3月21日 週六，上午9:46 寫道：
