### ISSUE TITLE
[my-product] - Dear Sir 

### ISSUE THREAD

**Issue by opooletech** [inspireui/support#2404]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
11:57 PM	Gradle sync failed: Could not read script 'C:\Eanarkali Application\Flluter\codecanyon-8j6VX50a-fluxstore-multi-vendor-flutter-ecommerce-full-app\FluxStore-vendor-1.6.4\source\android\app\Users\minh\Data\Projects\flutter\flutter\packages\flutter_tools\gradle\flutter.gradle' as it does not exist.
					Consult IDE log for more details (Help | Show Log) (2 s 883 ms)
2. Screenshots issues (required):
![image](https://user-images.githubusercontent.com/8824264/77197937-da526f00-6b07-11ea-8850-6810375c179f.png)

3. Proof of my purchased (required):
Purchase codes
Authors may ask you for a purchase code to verify that you’ve purchased this item.

3c020c9f-182d-4cdc-b7e8-088ca3ca7270 - 12 Mar 2020 REGULAR LICENSE
3. Config files (required)

**Comment by minhcasi** [comment]
@opooletech - thank you for the feedbacks, could you help to check following solutions:

1. Try to run the example project to check you flutter setup - https://flutter.dev/docs/get-started/test-drive

2. Try to clean up the flutter cache by using some solutions from - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

**Comment by opooletech** [comment]
Still Face The issue please help

 What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not find any matches for com.onesignal:OneSignal:[3.11.2,3.99.99] as no versions of com.onesignal:OneSignal are available.
     Required by:
         project :app
   > Could not find any matches for com.onesignal:OneSignal:[3.11.2,3.99.99] as no versions of com.onesignal:OneSignal are available.
     Required by:
         project :app > project :onesignal_flutter

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 35s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by opooletech** [comment]
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not find any matches for com.onesignal:OneSignal:[3.11.2,3.99.99] as no versions of com.onesignal:OneSignal are available.
     Required by:
         project :app
   > Could not find any matches for com.onesignal:OneSignal:[3.11.2,3.99.99] as no versions of com.onesignal:OneSignal are available.
     Required by:
         project :app > project :onesignal_flutter

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 27s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by minhcasi** [comment]
@opooletech - please check this solution to fix the issues https://github.com/inspireui/support/issues/2408

We may consider removing the Onesignal on next release due to it's not the stable library, the new version will be ready in 1-2 days - thank you!
