### ISSUE TITLE
[fluxstore pro] - 1.6.5c stack at launch

### ISSUE THREAD

**Issue by ahmetozcan9211** [inspireui/support#2405]
I download latest flux store but it is stuck on white screen when start

**Comment by minhcasi** [comment]
@ahmetozcan9211 - could you try to clean the cache by using this solution https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1 

Also pls help to raise 1 ticket for your all issues that help the support could follow up your update, kindly move conversation to #2365 - thanks
