### ISSUE TITLE
opencart site extension/module is not working after installing your plugin on our live opencart site

### ISSUE THREAD

**Issue by dipamtechextensor** [inspireui/support#2407]
We had purchased your plugin and it is working properly in our live site

         We also had integrated your plugin API on the mobile and it is too working properly. The thing/issue is after installing your plug-in, our site functionality is not working now.

Please find below SS :
https://www.screencast.com/t/nRPsxy7AtA

Would you/your team please reply on dipam.parmar@techextensor.com to get our site details.?

Also find below video for the same.
Awaiting for your quick reply.
Thank You.

**Comment by minhcasi** [comment]
Hi, thank you for the feedback. Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads it's used to verify your proof of purchase? 
Sorry for any inconvenience, we will reopen the ticket when it is verified, thank you!
