### ISSUE TITLE
[ListPro] - Unable to resolve asset

### ISSUE THREAD

**Issue by mohamedsaad1** [inspireui/support#241]
**Mandatory Info (please complete the following information):**
 - Product: [ListPro]
 - Purchased Code: [9bd506b3-9159-4da2-b1aa-a2a6a76ea337]

**Describe the issues*
i got this message while running the app /; Unable to resolve asset "./assets/icons/app-icon.png" from "icon" in your app/exp.json.
what should i do to solve it ??﻿

**Screenshots**

<img width="572" alt="screen shot 2019-01-29 at 7 24 12 pm" src="https://user-images.githubusercontent.com/42296346/52051932-b0ce3100-255d-11e9-81c9-d6b5e32d5a0b.png">

**Comment by minhcasi** [comment]
Hi, it seems ok with our testing, could you try to update the latest expo version: npm install expo

and also remove the Expo app client from your simulator.

Let us know your checking, thank you!

**Comment by thangvo9x** [comment]
@mohamedsaad1

**Comment by mohamedsaad1** [comment]
Unfortunately, you tried more than once and the same error still exists

Is there another way to run the app?

I hope there is a better explanation and consideration that not all of us have the same experience.

**Comment by thangvo9x** [comment]
Hi. Can you send me your project with the zip file for checking, plz?

**Comment by mohamedsaad1** [comment]
please send to me another e-mail address,
because when I try to send the file, I get this message
Message too large
Your message couldn't be delivered to *support@noreply.github.com* because
it exceeds the size limit. Try reducing the message size and resending.

**Comment by thangvo9x** [comment]
thang@inspireui.com noted with your id issue.
