### ISSUE TITLE
Exception caught by widgets library

### ISSUE THREAD

**Issue by ysnsyhn** [inspireui/support#2410]
Hey I get an error in Shipping Tab.

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════ The following NoSuchMethodError was thrown building Consumer<ShippingMethodModel>(dirty, dependencies: [_LocalizationsScope-[GlobalKey#81e14], _DefaultInheritedProviderScope<ShippingMethodModel>, _InheritedTheme]): The method ’>’ was called on null. Receiver: null Tried calling: >(0.0)

The relevant error-causing widget was: Consumer<ShippingMethodModel> file:///Users/yasinseyhan/Documents/AppAtolyesiWorkspace/FlutterProjects/HoneyHard/lib/screens/checkout/shipping_method.dart:47:18 When the exception was thrown, this was the stack: #0 Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5) #1 _ShippingMethodsState.build.<anonymous closure> (package:fstore/screens/checkout/shipping_method.dart:99:75) #2 Consumer.buildWithChild (package:provider/src/consumer.dart:175:12) #3 SingleChildStatelessWidget.build (package:nested/nested.dart:260:41) #4 StatelessElement.build (package:flutter/src/widgets/framework.dart:4291:28) ... ════════════════════════════════════════════════════════════════════════════════════════════════════

How to solve this.

the website url is : www.honeyhard.com
<img width="452" alt="Screen Shot 2020-03-21 at 16 36 18" src="https://user-images.githubusercontent.com/9936311/77227909-ae30ff80-6b94-11ea-8c45-fafc58a80898.png">
<img width="368" alt="Screen Shot 2020-03-21 at 16 50 54" src="https://user-images.githubusercontent.com/9936311/77227911-b25d1d00-6b94-11ea-8984-945e6a36a7cb.png">
![Screenshot_1584797747](https://user-images.githubusercontent.com/9936311/77227912-b2f5b380-6b94-11ea-8364-0ffb86c0810b.png)

**Comment by minhcasi** [comment]
Hi, thank you for the feedback. Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads it's used to verify your proof of purchase? 
Sorry for any inconvenience, we will reopen the ticket when it is verified, thank you!

**Comment by ysnsyhn** [comment]
<img width="1316" alt="Screen Shot 2020-03-23 at 03 24 04" src="https://user-images.githubusercontent.com/9936311/77268075-cf3d4180-6cb5-11ea-9892-150c6dbb367f.png">
<img width="787" alt="Screen Shot 2020-03-23 at 03 24 12" src="https://user-images.githubusercontent.com/9936311/77268080-d2d0c880-6cb5-11ea-8f5d-fb0b2de6a935.png">

**Comment by minhcasi** [comment]
@ysnsyhn - could you help to share the common and config folder to that we could help to check this issue - thanks

**Comment by ysnsyhn** [comment]
[Archive.zip](https://github.com/inspireui/support/files/4375354/Archive.zip)
@kvt0012 - a also send the keys over mail to you

**Comment by kvt0012** [comment]
Your email is ail@appatolyesi.com , is it correct, sir

**Comment by ysnsyhn** [comment]
Yes its correct

**Comment by ysnsyhn** [comment]
@kvt0012  How long will it take??? Im still waiting for the solution for a few days

**Comment by minhcasi** [comment]
@kvt0012 - please keep update on this ticket - thank you!

**Comment by philipvu30** [comment]
Hi @ysnsyhn ,

It seems you have sent me a wrong config because there is no content on the page.
Would you mind checking again? Thank you.

**Comment by ysnsyhn** [comment]
@philipvu30 I retried it on another webpage with The7 theme. But I still get the same error .
The webpage url is https://www.slimfitlife.net
[Archive 2.zip](https://github.com/inspireui/support/files/4387563/Archive.2.zip)
 I added the common and config folders.
Can you pls share an email with me that I can send you the keys

**Comment by philipvu30** [comment]
My email: philipvu@inspireui.com

**Comment by ysnsyhn** [comment]
@philipvu30 I get delivery error for this email. Already tried with 3 different mails

**Comment by philipvu30** [comment]
> @philipvu30 I get delivery error for this email. Already tried with 3 different mails

Well, please send it to this email instead: toan@inspireui.com.

**Comment by ysnsyhn** [comment]
sent

**Comment by ysnsyhn** [comment]
@philipvu30 did you check it

**Comment by minhcasi** [comment]
@ysnsyhn - is it possible to share the admin login so that we could check the plugins setting on your site? Please also share to support@inspireui.com and toan@inspireui.com 

Sorry for some delay on the ticket as we have some problem with the CoV-9 virus issues that impact to the team availability - thank you for your patience

**Comment by ysnsyhn** [comment]
@minhcasi I've sent the email with needed information.

**Comment by minhcasi** [comment]
Noted with checking, thank you!

**Comment by minhcasi** [comment]
Could you have a check if this plugin cause the issue - https://tppr.me/p9YQv ?

**Comment by ysnsyhn** [comment]
@minhcasi I deactivated both of them and tried again but nothing changed. The result gives the same error.

**Comment by philipvu30** [comment]
Hi @ysnsyhn 

Please replace these files:
[shipping_method.zip](https://github.com/inspireui/support/files/4401842/shipping_method.zip)
[shipping_method.zip](https://github.com/inspireui/support/files/4401851/shipping_method.zip)

 in **lib/screens/checkout/shipping_method.dart** and **lib/models/shipping_method.dart**

**Comment by philipvu30** [comment]
Hi @ysnsyhn ,

Due to an error with the free shipping method during checkout, please use these files instead of those above. Thank you

lib/screens/checkout/shipping_method.dart
[shipping_method.zip](https://github.com/inspireui/support/files/4402134/shipping_method.zip)
lib/models/shipping_method.dart
[shipping_method.zip](https://github.com/inspireui/support/files/4402137/shipping_method.zip)

**Comment by ysnsyhn** [comment]
Hey thanks it worked. But you forgot adding import '../../common/styles.dart'; in the screens file.

One more thing is that it does not sync the shipping addresses. I do not sell the product to TURKEY but it is still visible in the country list of the app. Is there a way to configure it?

**Comment by philipvu30** [comment]
Hi @ysnsyhn ,

Customer of undesired countries should be informed when they make payment on the last step. Would you mind testing it with the turkey address?

**Comment by ysnsyhn** [comment]
It works nice. Thanks a lot for your interest and help.

**Comment by minhcasi** [comment]
Dear @ysnsyhn, we're glad that it helps.

If the product is helpful for your business, please give us some feedback/ratings on this page https://codecanyon.net/downloads. We are working hard to update more awesome and powerful features on next coming version release. Let us know if you have any feedback. Thank you very much!
