### ISSUE TITLE
[FluxStore Pro] - Some questions

### ISSUE THREAD

**Issue by bikostudio** [inspireui/support#2411]
Hi,

I have purchased FluxStore Pro and I have some questions:

1-      I want to make the slider banner auto play to be in loop not to jump to the first slider. How to do that?

3- How to modify the height of the slider banner?

2-      How to Make the top section which contains (Menu – Logo – Search) to be sticky when scrolling down?

Thank you for your time

Best regards,

**Comment by qorane099** [comment]
same question

**Comment by minhcasi** [comment]
1. add autoPlay: true (from the config file, under banner setting)
2. add upHeight: xx - to customize advance, edit this file - https://tppr.me/Xbmw2
3. This feature is not available and need some customize the home page UI, we will investigate to upgrade it later, you can try to use this guide https://www.youtube.com/watch?v=R9C5KMJKluE

Let us know if you have any questions
Thank you!

**Comment by bikostudio** [comment]
thank you minhcasi  i will try to follow the steps and will feedback.
