### ISSUE TITLE
[Fluxstore pro] - Getting website data

### ISSUE THREAD

**Issue by qorane099** [inspireui/support#2412]
I did downloaded required plugins e.g Mstore API and  Regenerate Thumbnails,
then l did Enable REST API, and Generated API keys, l also did Setup the Renerate Image plugin.

after doing all above l did edit config.dart file and replaced old details to my website details e.g consumerKey, consumerSecret, blog, Url. l also edited config.json and config.en.json. then l did edited categories and added my store categories IDs.

after doing all above required details, the app is running well and even it generates vendors store names but l am not getting categories or anything else.

please what am l missing????

prove of my purchase attached!!
![IMG_20200322_005709](https://user-images.githubusercontent.com/39888242/77235233-1ce47c00-6bda-11ea-9fd6-8cedfedfa1c5.jpg)

**Comment by kvt0012** [comment]
Dear sir, do you follow our instruction here ? If not yet please try it, maybe it can hrlp you a little bit. 
https://docs.inspireui.com/fluxstore
Thank you
