### ISSUE TITLE
[MStore Pro] MStore Checkout Problem

### ISSUE THREAD

**Issue by kaycklbr** [inspireui/support#2413]
Hi, The Mstore Pro in app is ok, but when open the webview with page of checkout it's open a page with title "Billing details" and the button of payment in the end of the page. I want to open the page of payment and not this page, someone help me?

**Comment by minhcasi** [comment]
Hi, thank you for the feedback. Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads it's used to verify your proof of purchase? 
Sorry for any inconvenience, we will reopen the ticket when it is verified, thank you!

**Comment by kaycklbr** [comment]
![Capturar](https://user-images.githubusercontent.com/37295815/77253710-c3606980-6c3a-11ea-8f21-29244238b252.PNG)

Done

**Comment by luyx2412** [comment]
Hi @kaycklbr You need complete the billing detail before payment. So you can not replace this screen with another screen.

Thanks

**Comment by kaycklbr** [comment]
Hi @luyx2412, I completed the billing detail in address screen, but the billing number don't appear to insert number.

**Comment by luyx2412** [comment]
Hi @kaycklbr Can you send me the screenshot to understand easier?

Thanks
