### ISSUE TITLE
facebook login error

### ISSUE THREAD

**Issue by zawwinhtunn** [inspireui/support#2416]
I have already change google_services.json file .google and sms login are well work .but when I log in with facebook .still error "Warning ,there is an issue with the app during request the data ,please contact the admin for fixing the issue.Platform Exception (Error_Accout_Exist_With_Different_Credential, An Account Already Exist with the same email adress but diffent sign in Credential .Sign in using provider associated with this email adress."

this is my error screen shot 

https://github.com/zawwinhtunn/zawwin/blob/master/Capture.PNG

this is my fluxstore multivendor purcheased screen shot
https://github.com/zawwinhtunn/zawwin/blob/master/Capture1.PNG?raw=true

**Comment by zawwinhtunn** [comment]
Hello

**Comment by kvt0012** [comment]
Dear sir, you can work around this by using the --enable-software-rendering flag in flutter run command or by disabling hardware acceleration in the emulator ( on AVD manager)

**Comment by zawwinhtunn** [comment]
Thank you for your reply .I have already disabled hardware acceleration in emulator .But still show error.can you please check with team viewer for my issue or anything video guide or documents.

respectively

**Comment by kvt0012** [comment]
Maybe I think this problem comes from Android Studio and Flutter and it comes from many reasons. 
So if you've already disabled hardware acceleration, please try other solutions as: 
+ Run flutter doctor on command line to check whether it has problems? 
+Use flag --enable-software-rendering in flutter run 
Thank you

**Comment by zawwinhtunn** [comment]
I dont understand sir 
how it is 
+Use flag --enable-software-rendering in flutter run.

please documents guides for this

**Comment by kvt0012** [comment]
![image](https://user-images.githubusercontent.com/49152325/77713757-d04dd600-7009-11ea-85a0-8fc1503f784b.png)
 
You use like this on terminal on Android studio 
![image](https://user-images.githubusercontent.com/49152325/77713822-fb382a00-7009-11ea-84bc-017ed442460d.png)

**Comment by zawwinhtunn** [comment]
Sir .I have already run like this .But still error .I sent
screenshot.Please check me .

**Comment by zawwinhtunn** [comment]
hello sir .In my address filled pannel ,already  get country and states
with dropdown box .How can I get city lists also like this dropdown box .
please help me .

**Comment by kvt0012** [comment]
> Sir .I have already run like this .But still error .I sent screenshot.Please check me . screen shot link : https://github.com/zawwinhtunn/zawwin/blob/master/123.PNG

Dear sir, please try command flutter clean and run it again, thank you

**Comment by kvt0012** [comment]
> hello sir .In my address filled pannel ,already get country and states with dropdown box .How can I get city lists also like this dropdown box . please help me . screenshot link : https://github.com/zawwinhtunn/zawwin/blob/master/dropdownbox%20_not%20show.PNG

You can choose select address and select it on Google Map, that's available way. 
If you want to create select dropbox, you need to add your plugin and code by yourself because it's out of our supporting scope, sorry about that.
