### ISSUE TITLE
[Fluxstore] -  Multiple Important Issue ( URGENT )

### ISSUE THREAD

**Issue by themeix** [inspireui/support#2417]
Profile update issue, Quantity issue not fixed in 1.6.6
https://screencast-o-matic.com/watch/cYeYoLyhxK
Please open that issue again to discuss and resolve that.. I dont want to create new ticket. Trying to get help you from last few weeks but still not resolved my issue.. Please give me High priority for that issue..

1) Profile update not working
2) Quantity field not working.
3) Webview not loading.

2. Screenshots issues (required):
https://screencast-o-matic.com/watch/cYeYoLyhxK

3. Proof of my purchased (required):
https://raw.githubusercontent.com/themeix/temp/master/screenshot-589.png
3. Config files (required)
https://we.tl/t-q6wqvH7ES3

I am not sure why you closed my old ticket without resolve the issues.

**Comment by philipvu30** [comment]
Hi @themeix ,

My apologies for the late response. Your issues might be fixed by tomorrow. For further questions, you can contact me via Skype live:vuthanhtoan30 for faster support. Thank you for using our product.

**Comment by philipvu30** [comment]
All issues have been fixed and customer contacted via Skype. Closed.
