### ISSUE TITLE
[FluxStore 1.6.5c] - Shipping Rate is not working

### ISSUE THREAD

**Issue by saifmuhtar** [inspireui/support#2418]
1. My issue:
I'm using Royal Mail to send my products. It's working fine on website but it's not working on app. The app always shows the amount is 0.

2. Screenshots issues (required):
![Screenshot_1584872066](https://user-images.githubusercontent.com/34681804/77247318-e0149580-6c6a-11ea-891d-f980ff6d8de6.png)

3. Proof of my purchased (required):
![73951198-27072f80-4938-11ea-98f8-9a514428f664](https://user-images.githubusercontent.com/34681804/77247355-308bf300-6c6b-11ea-8c9e-f366ce39fd2f.jpg)

4. Config files (required)
[config.dart.zip](https://github.com/inspireui/support/files/4365021/config.dart.zip)

Thank you for your help.

**Comment by minhtruong315** [comment]
Hi @saifmuhtar Fluxstore only supports for default shipping methods in woo commerce. it doesn't support shipping methods plugin

**Comment by saifmuhtar** [comment]
Okay. Thank you for your support.
