### ISSUE TITLE
Too many errors - FluxStore

### ISSUE THREAD

**Issue by paginaswebagency** [inspireui/support#2420]
Hello.
I did all  the steps that you say in the docs, but when i am in androitstudio and i try to debug the app to see the demo it show too  many errors.. 

can you please help me with that as soon as posible ?

I send the screenshot

![app-error](https://user-images.githubusercontent.com/62504696/77248959-ae201680-6c0b-11ea-8fe0-40e0b3f9649e.jpg)

**Comment by paginaswebagency** [comment]
and this error apear in console when i try to debug de app in androitstudio


Error on line 1, column 1 of ..\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_swiper-1.1.6\pubspec.yaml: Unexpected character.
  ╷
1 │                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
  │ ^
  ╵
pub get failed (65;   ╵)

**Comment by minhcasi** [comment]
Hi, thank you for the feedback. Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads it's used to verify your proof of purchase? 
Sorry for any inconvenience, we will reopen the ticket when it is verified, thank you!

**Comment by paginaswebagency** [comment]
Hello. 
this is the purchase screenshot
![purchase](https://user-images.githubusercontent.com/62504696/77280661-eae32080-6c92-11ea-8581-2353368f859d.jpg)


And this is the same error i told you before, this is what i open it form  00_MEnu or 01_Menu from the app files on source folder.
![error2](https://user-images.githubusercontent.com/62504696/77280870-883e5480-6c93-11ea-836b-4e53b1fbc9a7.jpg)

PLEASEE , I NEED YOUR HELP AS SOON AS POSSIBLE.

THANKS

**Comment by minhcasi** [comment]
@paginaswebagency - the android studio is missing Flutter config please check this setting https://tppr.me/EGuBd

You can try to run the example project here to make sure all the library are installed - https://flutter.dev/docs/get-started/test-drive

**Comment by paginaswebagency** [comment]
No, what type of answer is this ????
is not that... I CAN RUN THE EXAMPLE PROJECT WITH OUT PROBLEM.

The problem is with your app, do you see the images i send you before ????
se second image is not in androit studio, please check the problem give some minutes to solve, is not what you say.

**Comment by minhcasi** [comment]
@paginaswebagency

Try this script to clean up the cache - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

If you could not use the product so far we could process refund - thank you!

**Comment by minhcasi** [comment]
See this video could be help

https://www.youtube.com/watch?v=abMi8JYurpM&list=PLcF-HiQy-jOJAD8btGgr_CHcUmYyN8GgY&index=8

https://www.youtube.com/watch?v=y55AqAEEp8M&list=PLcF-HiQy-jOJAD8btGgr_CHcUmYyN8GgY&index=7

**Comment by minhcasi** [comment]
@paginaswebagency - please confirm if you could run the project - thank you!
