### ISSUE TITLE
[Fluxstore] - Language, Background color, 

### ISSUE THREAD

**Issue by qorane099** [inspireui/support#2422]
1. Please l need to know, which files d l have to edit if l need to change background color.
2. I need to delete or disable all language in the app apart from English, also l need to add two langauge, please how can l do that,
![IMG_20200322_005709](https://user-images.githubusercontent.com/39888242/77251439-5c5fa680-6c74-11ea-93a5-d1fdf258ea87.jpg)

**Comment by philipvu30** [comment]
Hi @qorane099 ,

Sorry for the late response.
1. Navigate to this file: lib/common/styles.dart. There will be 2 methods called: buildLightTheme and buildDarkTheme. Please change the attribute: backgroundColor of those methods to your preferred colors.
2. You can change/add/remove languages in these files. Remember you have to modify all these files:
   - lib/common/tools.dart -> getLanguagesList
   - lib/l10n
   - lib/generated/l10n.dart -> supportedLocales
   - lib/generated/intl
   - lib/config

**Comment by qorane099** [comment]
Thank you, l have successfully changed backgroud color but

in this file: lib/common/tools.dart

there is no getlanguages as you mention.

please give me detailed info about which files to edit in order to add/change/remove languages.

thank you

**Comment by philipvu30** [comment]
Hi @qorane099 ,

Please contact me via Skype live:vuthanhtoan30, I will give you instructions on changing the language.

**Comment by qorane099** [comment]
I did contact you through skype, please consider and call me, l am 2 to 3 issue that you help in couple of minutes thank you

**Comment by minhcasi** [comment]
@qorane099  - would you mind sharing this language file so that we will include it as officially from the app - we are working on a new script to help to add/remove language easier - thank you!

**Comment by qorane099** [comment]
Dear Inspireui/Support,

This is two translated files.

somali and kiswahili.
Somali is language from Somalia and kiswahili is language from Kenya.


appreciated your help🙏🙏


thank you

**Comment by minhcasi** [comment]
@qorane099 - please help to send again as i could read it - please help to send it to my email minh@inspireui.co - i will include all these languages on later release - very best!

**Comment by qorane099** [comment]
Brother,

The languages l will send you, but please consider my issue, l sent you
several tickets about the issue of app crashing.

Please consider, l even sent you a special support ticket.

9121948906
