### ISSUE TITLE
[Fluxstore Pro] - some issue {1- with checkout , 2- Extract or Build APK.... }

### ISSUE THREAD

**Issue by midotaha** [inspireui/support#2423]
**Hi Dear 
**Greetings!! , 
I have 2 issue as i mention at title , 
1- After i linked source code to my web store  , and success to log-in to test account i added some products to cart when i want to complete the order and click on checkout i got this message {FormtaExcpetion:Unexpected end of  input(at character1)} when i use Arabic interface ,if i used English interface Nothing happen nothing move , don't move to the next page Stucked at the same page >>> you can check screenshot for this issue** 
![Screenshot (23)](https://user-images.githubusercontent.com/19406537/77250763-1b0ecd00-6c5b-11ea-81ae-663cc4ae815d.png)

**2-when i change interface to English , Products name Still Arabic not changed to English** 

**3-when i want to build APK or Bundle i got error i don't where or how can i solve it  you can check** 
![Screenshot (24)](https://user-images.githubusercontent.com/19406537/77250775-2b26ac80-6c5b-11ea-8daa-41f32cf31a10.png)
![Screenshot (25)](https://user-images.githubusercontent.com/19406537/77250776-2cf07000-6c5b-11ea-80fa-5e09790aa7ef.png)
![Screenshot (26)](https://user-images.githubusercontent.com/19406537/77250777-2eba3380-6c5b-11ea-881f-bcbfcdcd8887.png)

4- if i want to shown category name 
![Screenshot (27)](https://user-images.githubusercontent.com/19406537/77251646-98890c00-6c60-11ea-9cc0-42273697d2f5.png)

Also you can check my config.dart file i think it's fine state also i find 2 errors at error_log 
{**1- PHP Parse error:  syntax error, unexpected 'empty' (T_EMPTY), expecting identifier (T_STRING) in /home/............./public_html/catalog/controller/extension/mstore/cart.php on line 66 

2- ......../public_html/catalog/controller/extension/mstore/category.php on line 33}**
[config.zip](https://github.com/inspireui/support/files/4365293/config.zip)

Note :- if there any accurate document this will be very useful to help us for studying this  source code 

**final this my proof** 
![FluxStore](https://user-images.githubusercontent.com/19406537/77250808-5b6e4b00-6c5b-11ea-9e17-fac32e2df7d3.png)

**Many thanks for you 
Ahmed Taha**

**Comment by trunghieuvn** [comment]
Sorry but I cannot reproduce this error on my source code to check. 
You can give me permission on your source code so I can easily handle the error. 
My email: hieu.trantrung1204@gmail.com
Thanks.

**Comment by midotaha** [comment]
alharamin.zip
<https://drive.google.com/file/d/1W_m39ilpB_70p0AtlI7x1r3NBcaCTnG6/view?usp=drive_web>
*Hi Inspireui/Support*
*Greetings!! *
I have some issues , *when i** spoke to you on GetHub Support* * , and
i attach source code i working on it , also if i want to change package
name i got error only package name working is "*package
="com.inspireui.fluxstore">*", also i can't Build APK OR BUNDLE for test
App ,*
*1- After i linked source code to my web store , and success to log-in to
test account i added some products to cart when i want to complete the
order and click on checkout i got this message {FormtaExcpetion:Unexpected
end of input(at character1)} when i use Arabic interface ,if i used English
interface Nothing happen nothing move , don't move to the next page Stucked
at the same page >>> you can check screenshot for this issue*

*2-when i change interface to English , Products name Still Arabic not
changed to English*


*3-when i want to build APK or Bundle i got error i don't where or how can
i solve it you can check4-**if i want to *shown* category name <**what** can
i do?>*

*Many Thanks for you *

*Ahmed Taha *

**Comment by midotaha** [comment]
**Hi Dear , Greetings!!
i sent to you that source i work on it . but i didn't get final answer or the steps should i do it , concisely 
1- i want fix checkout cart.
2-how can i make new {key.properties , key-debug.properties , and mstore.keystore } because this step make me stuck to build APK for test. every time trying to build APK i can't , i got this error**
![Screenshot (29)](https://user-images.githubusercontent.com/19406537/77827855-164d8b80-7129-11ea-8e78-69aa6b7509ff.png)

**3-i need to add some properties LIKE wight or Liter measure for example ?**

**Comment by minhcasi** [comment]
@trunghieuvn - pls follow up the ticket

@midotaha - regarding the #2 issues - please double this guide https://docs.inspireui.com/fluxstore/delivery/

#3 the product attribute could be show dynamic on app when you edit a product as Variable

**Comment by trunghieuvn** [comment]
Hello @midotaha, 

I checked mail but i don't see source. can you please give me access source git or send for me file .zip source from you.

Have a nice day
thanks

**Comment by midotaha** [comment]
**Hi Dear 
Greetings !!
1- i need to add some properties LIKE wight or Liter measure for example ? i can't to reach to file where can i edit it can you tell me the path to this file . many thanks for you**

**Comment by trunghieuvn** [comment]
you can access in wordpress admin and add product Attribute when edit product detail (woocommerce) 
app will auto load it.
thanks

**Comment by midotaha** [comment]
Hi Dear , and good morning , I'm not using WordPress Sir , I'm using opencart
Many thanks for you

**Comment by minhcasi** [comment]
@midotaha - the product options for Opencart cart is not available from current release - we are working on new release on 1.6.6 (could be ready in 1-2 week) - thank you!
