### ISSUE TITLE
[Fluxstore multi vendor] -  Stores Not Showing 

### ISSUE THREAD

**Issue by Khaledio** [inspireui/support#2425]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:

hi 

i use the WCFM plugin and the stores does not show in the app . 

any souloution please ?

2. Screenshots issues (required):
![2](https://user-images.githubusercontent.com/62360836/77297218-30f5af80-6ca6-11ea-8b07-064c31694b5b.png)

3. Proof of my purchased (required):
![1](https://user-images.githubusercontent.com/62360836/77297231-3652fa00-6ca6-11ea-9625-59893593a073.png)

3. Config files (required)

[config.zip](https://github.com/inspireui/support/files/4368061/config.zip)

**Comment by minhtruong315** [comment]
@Khaledio can u send me config.dart file via email truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/2425
I need to know username and password for your admin to check
Thanks

**Comment by Khaledio** [comment]
@mi

> 
> 
> @Khaledio can u send me config.dart file via email [truong@inspireui.com](mailto:truong@inspireui.com)
> with subject: #2425
> I need to know username and password for your admin to check
> Thanks

 i send the config.dart file to your email
Thanks

**Comment by minhtruong315** [comment]
Hi @Khaledio I see your website is missing JWT Authentication plugin. you need to install this plugin
https://vi.wordpress.org/plugins/jwt-authentication-for-wp-rest-api/
remember to config this https://tppr.me/JllFI

**Comment by Khaledio** [comment]
thank you @minhtruong315 ..i'll install it and try.

**Comment by Khaledio** [comment]
@minhtruong315 hi 
i install this plugin butt it stiil the same problem

**Comment by minhtruong315** [comment]
Did you config this https://tppr.me/JllFI?

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!

**Comment by Khaledio** [comment]
Hi sir thank you for replaying me and i am sorry that i didn't réponse to
your solution ... i ll try and thanks again

Le mer. 1 avr. 2020 à 02:57, minhtruong315 <notifications@github.com> a
écrit :
