### ISSUE TITLE
[FluxStore Pro] -  Error consulting Woocommerce shipping methods

### ISSUE THREAD

**Issue by irxcloud** [inspireui/support#2426]
1. My issue:

Good morning, how are you? I am having a problem checking out. When I consult Woocommerce's delivery methods, I get an error that doesn't allow me to proceed with the purchase. I've tried everything, even the Woocommerce settings, configured Vietnam as the main region with code 700000 as recommended in one of the problems I found here. But nothing I did helped. My version of the WC is the same as the downloaded package. The version of FluxStore is the most recent.

2. Screenshots issues (required):

Error Screenshot
![error](https://user-images.githubusercontent.com/30660353/77314113-ccf1dc00-6ce3-11ea-8aaf-ab683b8315ed.jpeg)

Woocommerce Shipping Methods Config
![woocommerce](https://user-images.githubusercontent.com/30660353/77314145-da0ecb00-6ce3-11ea-9db0-688a5281c7d8.JPG)

3. Proof of my purchased (required):

![codecanyon](https://user-images.githubusercontent.com/30660353/77431351-59230280-6dbb-11ea-8280-685ec53e6a92.JPG)

3. Config files (required)

My pubspec.yaml

name: fstore
description: Mobile commerce app by Flutter

version: 1.6.5+33

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  logs:
    git: https://github.com/pq/logs
  flutter:
    sdk: flutter
  http: 0.12.0+4
  html_unescape: 1.0.1+3
  provider: 4.0.4
  after_layout: 1.0.7+2
  font_awesome_flutter: 8.7.0
  path: 1.6.4
  vector_math: 2.0.8
  carousel_pro: 1.0.0
  flutter_widget_from_html: 0.3.2+1
  configurable_expansion_tile: 1.0.0
  timeago: 2.0.26
  share: 0.6.3+6
  validate: 1.7.0
  country_pickers: 1.1.0
  shared_preferences: 0.5.6+3
  firebase_messaging: 6.0.12
  firebase_analytics: 5.0.11
  transparent_image: 1.0.0
  pull_to_refresh: 1.5.8
  localstorage: 3.0.1+4
  notification_permissions: 0.4.4
  flare_splash_screen: 3.0.1
  rate_my_app: 0.6.0+2
  page_indicator: 0.3.0
  extended_image: 0.7.1
  intro_slider: 2.2.9
  url_launcher: 5.4.2
  firebase_core: 0.4.4 
  firebase_auth: 0.15.3
  flutter_webview_plugin: 0.3.10+1
  connectivity: 0.4.8+2
  random_string: 2.0.1
  google_maps_flutter: 0.5.24+1
  place_picker: 0.9.11
  cached_network_image: 2.0.0
  image_picker: 0.6.3+4
  uuid: 2.0.4
  uni_links: 0.2.0
  flutter_staggered_grid_view: 0.3.0
  device_apps: 1.0.9
  auto_size_text: 2.1.0
  koukicons: 2.0.2
  flutter_swiper: 1.1.6
  flutter_widgets: 0.1.11
  video_player: 0.10.8+1
  flutter_spinkit: 4.1.2
  percent_indicator: 2.1.1+1
  animated_text_kit: 2.0.0
  wave: 0.0.8
  http_auth: 0.2.9
  firebase_admob: 0.9.1
  facebook_audience_network: 0.5.0
  pin_code_fields: 2.4.0
  flutter_facebook_login: 3.0.0
  webview_flutter: 0.3.19+9
  rubber: 0.4.0
  flutter_localizations:
    sdk: flutter
  custom_splash: 0.0.2
  apple_sign_in: 0.1.0
  google_sign_in: 4.1.4
  google_fonts: 0.3.9
  onesignal_flutter: 2.3.4
  flutter_statusbarcolor: 0.2.3
  app_settings: 3.0.1
  razorpay_flutter: 1.1.2
  animated_splash: 1.0.0
  firebase_database: 3.1.3
  event_bus: 1.1.1
  country_code_picker: 1.3.6
  flutter_typeahead: 1.8.0
  flash: 1.2.0

dev_dependencies:
  flutter_launcher_icons: 0.7.4
  flutter_test:
    sdk: flutter
  pedantic: 1.8.0+1 # Analysis

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - lib/config/
    - lib/config/mocks/
    - lib/config/states/
    - assets/icons/categories/
    - assets/icons/tabs/
    - assets/icons/profile/
    - assets/icons/payment/
    - assets/images/
    - assets/images/country/
    - assets/images/favicon/
    - assets/html/
    - assets/images/background/
  fonts:
    - family: MaterialIcons
      fonts:
        - asset: assets/fonts/MaterialIcons.ttf
    - family: Entypo
      fonts:
        - asset: assets/fonts/Entypo.ttf
    - family: FontAwesome
      fonts:
        - asset: assets/fonts/FontAwesome.ttf
    - family: MaterialCommunityIcons
      fonts:
        - asset: assets/fonts/MaterialCommunityIcons.ttf
    - family: Feather
      fonts:
        - asset: assets/fonts/Feather.ttf

 flutter_intl:
  enabled: true

**Comment by minhcasi** [comment]
@irxcloud - could you help to take the verify screenshot that includes your username - thank you!

**Comment by irxcloud** [comment]
Good morning, I don't know if I understand what you mean. I updated the printscreen proving the purchase. If it is the screen print of the app, with the user logged in, I can send it too, but I managed to log in on only one device, on other devices I can't register users, it returns me a similar error.

**Comment by irxcloud** [comment]
![abd567d9-b684-46ae-bbd8-ba3efecbcd56](https://user-images.githubusercontent.com/30660353/77433023-97b9bc80-6dbd-11ea-9329-9d28b0852277.jpg)

**Comment by irxcloud** [comment]
I updated to the latest version I found today on Codecanyon and the error persists:

![WhatsApp Image 2020-03-24 at 18 35 23](https://user-images.githubusercontent.com/30660353/77479579-d3c14180-6dfe-11ea-84b2-3268c3996d51.jpeg)

**Comment by minhcasi** [comment]
@philipvu30 - please help for investigating the issue - thank you!

**Comment by philipvu30** [comment]
Hi @irxcloud ,

Please send me the config files (the config.dart and all the config_xx.json).

You can send them to me via
Skype: vuthanhtoan30
Email: philipvu@inspireui.com / toan@inspireui.com

Thank you!

**Comment by irxcloud** [comment]
I just sent the requested files. I'm waiting. Thanks!

**Comment by philipvu30** [comment]
Hi @irxcloud ,

We'll update the new version on the weekend. Please also remember to update your mstore-api plugin along with it.

**Comment by irxcloud** [comment]
I was waiting for the update for this weekend, I entered the codecanyon and did not find a new version. Could you tell me anything about it?

**Comment by minhcasi** [comment]
@irxcloud - pls share your email - we will send patching to your source as the new delivery package need to add more features on next release so that we delay the release in few days - thanks

**Comment by philipvu30** [comment]
Sent fixed solution via Skype.

**Comment by irxcloud** [comment]
Thanks for the fix. I will update the project and returns the results. Thanks!

**Comment by irxcloud** [comment]
Good morning, how are you? In relation to the reported problem, I did all the update passed by Skeype as instructed, but without success, I don't even know what else to do. I've been trying for a long time and nothing, I'm almost giving up and asking for a refund. I can't register users in the application, in my network it works normally, but in some networks it doesn't work, it always returns the same error: <script> document.cookie = "humans_21909 = 1"; document.location.reload (true) </script>. The built-in user is now able to log in, before he was not even able to log in, but now after he has been updated he is logging in, but does not register a new user. The strangest thing is that on some Wi-Fi networks it works and on others it doesn't, even from the same ISP.

I am now trying to see with the hosting provider if there can be some block there, but my account is for resale, it would not be for blocking. I'm also installing on a VPS account, let's see if I'm successful. But the problem really seems to be in your API. Didn't you guys have any user control or anything? Aren't other customers having the same problem? I even thought about contacting someone who bought your app to see if it is in the same configuration and exchange some information. Can you test the API of my website that is in the email sent? There I even put the Wordpress username and password.

As I said, I don't know what I'm doing, and the worst thing is that I urgently need it. I will try one more time. Can you help me?

**Comment by philipvu30** [comment]
Hi @irxcloud ,

I have sent you the new source code. Please check and confirm if it works. Thanks

**Comment by irxcloud** [comment]
Hi,

I did the update using the new source code you gave me, but it didn't work. In the code you passed I didn't see any changes regarding cookies, just updates regarding products. I kindly ask you to analyze this problem better. I'm waiting. Thanks!
