### ISSUE TITLE
Fluxstore Pro - Wocommerce - Products not visible on Category Page & Unable to proceed after shipping

### ISSUE THREAD

**Issue by tjain90** [inspireui/support#2427]
---------

1. My issue: Woocommerce Products not visible on Category Page & not able to proceed after shipping. When category page is clicked it first shows some schema then no product is shown.
Similarly, We are able to proceed to checkout till address , post then app is unable to proceed to payment.

2. Screenshots issues (required): Attached
![Category Page (2)](https://user-images.githubusercontent.com/6376301/77328626-ccd4f900-6d42-11ea-8a7c-edde9f6e6e8e.jpg)
![category page](https://user-images.githubusercontent.com/6376301/77328632-ce062600-6d42-11ea-887b-96f6e326efa1.jpg)

3. Proof of my purchased (required):  tjain90@gmail.com from Themeforest

3. Config files (required)
[common.zip](https://github.com/inspireui/support/files/4370199/common.zip)

**Comment by tjain90** [comment]
Hi is there any update on above ticket ?

**Comment by minhcasi** [comment]
@trunghieuvn - please investigate the issue - thanks

**Comment by tjain90** [comment]
@trunghieuvn can you consider on priority. shipping is not loaded in app. customer cannot proceed in shopping is true.

**Comment by Jegufull** [comment]
I have the previous version, give me your email and I will send it to you.

**Comment by minhcasi** [comment]
@trunghieuvn - please help to update this ticket today - thank you!

**Comment by minhtruong315** [comment]
@tjain90 You can replace services/woo_commerce.dart to fix product
[woo_commerce.dart.zip](https://github.com/inspireui/support/files/4384854/woo_commerce.dart.zip)

**Comment by minhtruong315** [comment]
@tjain90 checkout is working well. Are u using the latest version Fluxstore? 
[payment.mov.zip](https://github.com/inspireui/support/files/4384905/payment.mov.zip)

**Comment by tjain90** [comment]
@minhtruong315 Checkout is working fine now. 

1. Shipping class was missing. But I cannot save any address and use them again. It throws no error and nothing happens on checkout.
2. Shipping method load takes huge time to get loaded. is there any way to make it fast.

**For Products on category pages:**
Woocommerce service file you have shared throws an error of kpayment attribute. I have used old one only but I can see product can seen when you sort them by sale, if you select featured or date it shows no product. Kindly find snapshot below:
![Screenshot_20200326-212627](https://user-images.githubusercontent.com/6376301/77668660-b11f5c00-6fa9-11ea-82cd-2f6411167b3b.jpg)
![Screenshot_20200326-212638](https://user-images.githubusercontent.com/6376301/77668664-b381b600-6fa9-11ea-9016-9d5bfc13637b.jpg)
![Screenshot_20200326-212645](https://user-images.githubusercontent.com/6376301/77668678-b9779700-6fa9-11ea-9884-0a098d5f383b.jpg)

**Comment by minhtruong315** [comment]
@tjain90 can u record video for checkout flow? I wanna see shipping error

**Comment by aishema2000** [comment]
This issue seems strange. I have tried both dokan and WCFM nothing work. The app shows "No Product". I tried both fluxstore-vendor version 1.6.5 and 1.6.4 and I have same results. For now, my only hope is to see a solution from support. I will be waiting. Have a nice night.

**Comment by sketchuprzr** [comment]
I have mentioned this problem before. "All" should be added to the filtering section. The problem is in the json links. We have closed all filters in order to use the application properly.

Also, the app does not show all products. To solve this problem, you can check out solution "3" in this comment;
https://github.com/inspireui/support/issues/2374#issuecomment-601727944

**Comment by tjain90** [comment]
@sketchuprzr  i have updated products to 10 per page. But Order By is bounding products to be shown on screen. How I can remove this completely or solve this.
You have mentioned "We have closed all filters in order to use the application properly." so how can i remove from my end ?

**Comment by tjain90** [comment]
Also post having 10 products per page, there is no option for lode more or see all products on category page ?

**Comment by sketchuprzr** [comment]
To disable the "on sale" and "featured" Filters, you can delete the places I have marked in the images below. The inspireui team can add "all" filtering and use it until it defaults.

![image](https://user-images.githubusercontent.com/60021696/77837757-926dc080-7175-11ea-9a84-d1df3e43187e.png)

![image](https://user-images.githubusercontent.com/60021696/77837760-96014780-7175-11ea-8e18-ed7f2d4c05d6.png)

![image](https://user-images.githubusercontent.com/60021696/77837765-9d285580-7175-11ea-93fb-8d12b5d2707d.png)

![image](https://user-images.githubusercontent.com/60021696/77837773-a3b6cd00-7175-11ea-9e33-8fc1acf6ce3e.png)

![image](https://user-images.githubusercontent.com/60021696/77837779-a87b8100-7175-11ea-9930-dcca434660a0.png)

![image](https://user-images.githubusercontent.com/60021696/77837781-b0d3bc00-7175-11ea-90b4-bd28ce8c2179.png)

![image](https://user-images.githubusercontent.com/60021696/77837792-f1333a00-7175-11ea-9119-d2e0c365c32e.png)

![image](https://user-images.githubusercontent.com/60021696/77837796-fd1efc00-7175-11ea-9d30-59dd7e1a3591.png)

![image](https://user-images.githubusercontent.com/60021696/77837813-1162f900-7176-11ea-901a-bdba3bad058d.png)

![image](https://user-images.githubusercontent.com/60021696/77837817-188a0700-7176-11ea-99d1-4c065402be36.png)

![image](https://user-images.githubusercontent.com/60021696/77837822-23449c00-7176-11ea-92e3-87d6f6e397af.png)

![image](https://user-images.githubusercontent.com/60021696/77837842-5f77fc80-7176-11ea-9c28-d91d9562b912.png)

![image](https://user-images.githubusercontent.com/60021696/77837844-656ddd80-7176-11ea-829e-af0c90f5348f.png)

**Comment by minhtruong315** [comment]
@tjain90 Do you have any on_sale or featured products on your website?

**Comment by tjain90** [comment]
Yes @minhtruong315  most of the products are in sale. Is ther any other way that i can show all ?

**Comment by sketchuprzr** [comment]
As I said, the urls called by the filters are incorrect. so it doesn't load all the products. The default "date" filter should be changed to "all" and show all products without any filter. In addition, "sale" and "featured" can be used. But "date" is problematic. It does not show all the products.

I deleted all these "featured" and "onsale" filters to be able to use the application temporarily. Only in this way was I able to view all products.

**Comment by minhcasi** [comment]
@trunghieuvn - pls review and update the fixing for product filters

**Comment by tjain90** [comment]
@sketchuprzr  Thanks It works. Temporary fix works fine. At least app is not showing blank page.
Although filter at the top is not working because we have deleted its functionality. 
Hope this will be fixed in upcoming release by dev team.

**Comment by trunghieuvn** [comment]
You can try editing in the following way. This will help you search all products when choosing Sort by Date.

![image](https://user-images.githubusercontent.com/19247680/77989696-9e11e080-7349-11ea-9ea9-1442b4a3b896.png)

Find and delete `featured ??= 0;` and `onSale ??= 0;`  in `lib/services/woo_commerce.dart` file

**Comment by sketchuprzr** [comment]
> You can try editing in the following way. This will help you search all products when choosing Sort by Date.
> 
> ![image](https://user-images.githubusercontent.com/19247680/77990049-7f601980-734a-11ea-9647-2c4cfa8f43b9.png)
> 
> Find and delete `featured ??= 0;` and `onSale ??= 0;` in `lib/services/woo_commerce.dart` file

Not working :/

**Comment by trunghieuvn** [comment]
To get data like this picture, what did you call the api url? Please give me the url which returns the result as shown so I can check. Thanks.

![image](https://user-images.githubusercontent.com/19247680/78002882-0c629d00-7362-11ea-82e9-1c4fc0408605.png)

**Comment by trunghieuvn** [comment]
Please send me 2 files `lib/screens/products/products.dart` and `lib/services/woo_commerce.dart` after you have edited my way. 
Thanks.

**Comment by sketchuprzr** [comment]
_lib/screens/products.dart 
lib/services/woo_commerce.dart_

these files are attached "source files.zip".

when clicked "date" filter , URL ;
 https://www.pratikbakkal.com/wp-json/wc/v2/products?status=publish&lang=&per_page=10&page=1&category=358&orderby=date&order=desc&consumer_key=....

when clicked "on sale" filter, URL;
https://www.pratikbakkal.com/wp-json/wc/v2/products?status=publish&lang=&per_page=10&page=1&category=358&orderby=date&order=desc&consumer_key=....

[soruce files.zip](https://github.com/inspireui/support/files/4408597/soruce.files.zip)

**Comment by trunghieuvn** [comment]
> _lib/screens/products.dart lib/services/woo_commerce.dart_
> 
> these files are attached "source files.zip".
> 
> when clicked "date" filter , URL ;
> https://www.pratikbakkal.com/wp-json/wc/v2/products?status=publish&lang=&per_page=10&page=1&category=358&orderby=date&order=desc&consumer_key=....
> ![image](https://user-images.githubusercontent.com/60021696/78019614-afaeb480-7358-11ea-982e-9d0a3933dc33.png)
> 
> when clicked "on sale" filter, URL;
> https://www.pratikbakkal.com/wp-json/wc/v2/products?status=publish&lang=&per_page=10&page=1&category=358&orderby=date&order=desc&consumer_key=....
> ![image](https://user-images.githubusercontent.com/60021696/78019621-b2110e80-7358-11ea-94e7-92661c24c005.png)
> 
> [soruce files.zip](https://github.com/inspireui/support/files/4408597/soruce.files.zip)

Are these actions you perform on mobile apps? In your example, I don't see the difference in the called url in the case of 'clicked date filter' and 'clicked sale filter'.

What version of FluxStore are you using? Please provide me the config app file.
Thanks very much.

**Comment by sketchuprzr** [comment]
Give me your email address, I will send the application folder as is. @trunghieuvn

**Comment by trunghieuvn** [comment]
Thanks! 
My email is `hieu.trantrung1204@gmail.com`

**Comment by sketchuprzr** [comment]
Hello @trunghieuvn ,
I shared the file with you on drive.

Thank you.

**Comment by trunghieuvn** [comment]
I have received,
I am investigating the cause and proceeding to handle

**Comment by trunghieuvn** [comment]
@sketchuprzr  I have issue when run app. please add skype me i will discuss. 
skype: trunghieu-it@hotmail.com

**Comment by trunghieuvn** [comment]
i don't know native language now 
![2427](https://user-images.githubusercontent.com/19247680/78124886-85cdbe80-743a-11ea-83a8-a83d5c56609d.png)

**Comment by trunghieuvn** [comment]
Hi @sketchuprzr , please provide the link config app which displays the full data, I cannot build the app with the current config link.

`https://raw.githubusercontent.com/sketchuprzr/pratik/master/config3.json`

![image](https://user-images.githubusercontent.com/19247680/78127092-c3801680-743d-11ea-83eb-36d8a0fa6877.png)




> i don't know native language now
> ![2427](https://user-images.githubusercontent.com/19247680/78124886-85cdbe80-743a-11ea-83a8-a83d5c56609d.png)

**Comment by sketchuprzr** [comment]
Oh , so sorry ..
You came across such a page because our store is in maintenance.
There he says "stay home" against the corona virus :).

You can redirect the config path to one of the config files.

**Comment by tjain90** [comment]
> You can try editing in the following way. This will help you search all products when choosing Sort by Date.
> 
> ![image](https://user-images.githubusercontent.com/19247680/77990049-7f601980-734a-11ea-9647-2c4cfa8f43b9.png)
> 
> Find and delete `featured ??= 0;` and `onSale ??= 0;` in `lib/services/woo_commerce.dart` file

Hi @trunghieuvn , Thanks this approach worked fine in my case.

**Comment by trunghieuvn** [comment]
> > You can try editing in the following way. This will help you search all products when choosing Sort by Date.
> > ![image](https://user-images.githubusercontent.com/19247680/77990049-7f601980-734a-11ea-9647-2c4cfa8f43b9.png)
> > Find and delete `featured ??= 0;` and `onSale ??= 0;` in `lib/services/woo_commerce.dart` file
> 
> Hi @trunghieuvn , Thanks this approach worked fine in my case.

Hi @tjain90  , I am very happy to have helped you.

Hi @sketchuprzr , I see your code is missing featured and onSale parameters, can you try adding them?

![image](https://user-images.githubusercontent.com/19247680/78263985-d291c200-752c-11ea-88a0-fcd7e6efcbf6.png)

I have tried adding them, and edited a few here

The result is :

- In the case of `Default` and sorting as` Date`, the output is complete.
 + Link API that applications call: 

`https://www.pratikbakkal.com/wp-json/wc/v2/products?status=publish&lang=&per_page=10&page=1&category=321&orderby=date&order=desc&consumer_key=ck_23a...&consumer_secret=cs_389...`

![image](https://user-images.githubusercontent.com/19247680/78265096-323c9d00-752e-11ea-9431-a19642f41ad7.png)


- In case of sorting by featured, there is no result. It seems that the server has no data.
 + Link API that the app calls: 

`https://www.pratikbakkal.com/wp-json/wc/v2/products?status=publish&lang=&per_page=10&page=1&category=321&orderby=date&order=desc&featured=true&on_sale=false&consumer_key=ck_23a...&consumer_secret=cs_389...`

![image](https://user-images.githubusercontent.com/19247680/78265129-3c5e9b80-752e-11ea-8a3f-86faa0c70d9e.png)

- In case of sorting by Sale, the result is full.
 + Link API that the app calls: 

`https://www.pratikbakkal.com/wp-json/wc/v2/products?status=publish&lang=&per_page=10&page=1&category=321&orderby=date&order=desc&featured=false&on_sale=true&consumer_key=ck_23a...&consumer_secret=cs_389...`

![image](https://user-images.githubusercontent.com/19247680/78265165-484a5d80-752e-11ea-98e2-c6c8ab799ccc.png)

Hi @sketchuprzr ,  Please check again. 
Thanks.

**Comment by sketchuprzr** [comment]
Hi @trunghieuvn 
Thank you for the solution. I will test this as soon as possible.

**Comment by sketchuprzr** [comment]
#2564
