### ISSUE TITLE
[beonews-pro] - Setting login/sign in screen to be default page than HomeScreen

### ISSUE THREAD

**Issue by Cod3Guy** [inspireui/support#2428]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: I would like to secure the Apps with login screen, however, the apps launch landing screen is the "HomeScreen". How to configure the login screen to be default landing page on the first time apps launch?

2. Screenshots issues (required):
<img width="370" alt="Screenshot 2020-03-23 at 11 21 46 PM" src="https://user-images.githubusercontent.com/10850622/77332510-192d3280-6d5d-11ea-9caa-b4aba80256fd.png">

3. Proof of my purchased (required):
**Date:** 26 Jan 2020 
**Invoice No:** IVIP36220468 
**Order No:** 119399406
**Purchase code:** 77105d26-b9ad-416f-883b-16af6a48cab3

3. Config files (required)

[Common.zip](https://github.com/inspireui/support/files/4370298/Common.zip)

**Comment by minhcasi** [comment]
Hi, from the common/config.dart, you can update `IsRequiredLogin: true`

Let us know if you have any question, feel free to reopen or create a new ticket - thank you!

**Comment by Cod3Guy** [comment]
Hi, I tried to find the config.dart file, is not exist in BeoNews project. Are u referring to config.js?However there is no such field as "IsRequiredLogin"

<img width="374" alt="Screenshot 2020-03-24 at 12 40 18 PM" src="https://user-images.githubusercontent.com/10850622/77388983-b2476200-6dcc-11ea-856d-2212b32661ec.png">
