### ISSUE TITLE
MStore Pro - Give Error CeBuilder

### ISSUE THREAD

**Issue by san2pedro** [inspireui/support#2429]
Give me error when try open project 
Screenshot
[https://prnt.sc/rla8g2](url)

**Comment by minhcasi** [comment]
Hi, thank you for the feedback. Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads it's used to verify your proof of purchase? 
Sorry for any inconvenience, we will reopen the ticket when it is verified, thank you!

**Comment by san2pedro** [comment]
https://prnt.sc/rlw90m
