### ISSUE TITLE
[MSTORE-MV] Products added via app show even though they r drafts in website

### ISSUE THREAD

**Issue by kaiser2** [inspireui/support#243]
Hi

When a vendor adds products from the app, by default all vendor products are set as draft.
Now they shouldn't show on the front side unless an admin approves them

Also they show a 0.00 price unless admin approves them .

this needs a quick fix.

Also how to enhance first load speed and how to get rid of those default icons and posts that show on first load

Thanks

**Comment by thangvo9x** [comment]
Hi. We'll set default status is draft. you can change it by code.
