### ISSUE TITLE
General questions about editing the app

### ISSUE THREAD

**Issue by spetsglaz** [inspireui/support#2430]
---------

1. My issue: Hello, i would like to change the instagram items from fetching hashtag pictures to userprofile picture.
I would like to know how to change the blue orange settings picture, also how to change the position and size of the top text. For example change the position of the "Category" text to be more centered and bigger.

How do i find these files and how do i edit them? thank you.

2. Screenshots issues (required):

3. Proof of my purchased (required):
- verified by InspireUI ⭐️

3. Config files (required)

**Comment by minhcasi** [comment]
Hi, we will check the Instagram profile feature on later releases

To change the Setting image, please try to use the Inspector to change any UI from the app - https://docs.inspireui.com/fluxstore/customization/#1-how-to-customize-any-ui-from-app

**Comment by spetsglaz** [comment]
Hi what's the latest version of flutter compatible with fluxstore?

**Comment by minhcasi** [comment]
you can run the app with Flutter stable channel (latest version) - thank you!

**Comment by minhcasi** [comment]
Let us know if you have any question, feel free to reopen the ticket :)

**Comment by spetsglaz** [comment]
Hello again, i would like to change the whole background from the standard white color to a picture, how would i be able to do this? And is it possible to change the icons from the side bar menu, example of icons i would like to change : Icon(FontAwesomeIcons.wordpress or Icons.blur_on. Thank you for the help :)
