### ISSUE TITLE
[my-product] - 

### ISSUE THREAD

**Issue by kardotinambunan12** [inspireui/support#2431]
I have a problem when creating a product from the gallery on version 1.6.4 fluxstore "type (httpexceptio) => null is not a subtype of type (dynamic) => dynamic"
 can you give me a solution? thanks

**Comment by minhcasi** [comment]
Hi, thank you for the feedback. Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads it's used to verify your proof of purchase? 
Sorry for any inconvenience, we will reopen the ticket when it is verified, thank you!

**Comment by kardotinambunan12** [comment]
Sorry, there was no proof of purchase from me, my boss happened to buy
the Fluxstore product and I changed it to suit our company's needs.


Pada tanggal Sel, 24 Mar 2020 pukul 16.26 Minh Pham <
notifications@github.com> menulis:

**Comment by kardotinambunan12** [comment]
![IMG_20200327_160421](https://user-images.githubusercontent.com/61267127/77740469-e37e9700-7045-11ea-8e21-f8d82a534661.jpg)

Sorry for disturbing you. and this is proof of payment I made on the codecanyo site.

**Comment by kardotinambunan12** [comment]
![bukti](https://user-images.githubusercontent.com/61267127/77874164-5b330880-7276-11ea-9f7f-c13edc78887b.png)

I think this is what you need
