### ISSUE TITLE
[FluxStore] - IOS App Can't Build/Run - no such module google maps

### ISSUE THREAD

**Issue by saifmuhtar** [inspireui/support#2432]
1. My issue:

swift compiler error: no such module google maps

2. Screenshots issues (required):
![Screenshot 2020-03-24 at 3 54 43 PM](https://user-images.githubusercontent.com/34681804/77401658-47a41f80-6de8-11ea-8ff0-6305452526aa.png)

3. Proof of my purchased (required):
![73951198-27072f80-4938-11ea-98f8-9a514428f664](https://user-images.githubusercontent.com/34681804/77401675-4d9a0080-6de8-11ea-9dd7-9bf9df029b10.jpg)

3. Config files (required)
skype: saifmuhtar@gmail.com

**Comment by minhcasi** [comment]
@saifmuhtar - could you try to clean the cache - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

**Comment by saifmuhtar** [comment]
Yes, after I clean the cache now it's working.
Thank you.
