### ISSUE TITLE
[my-product] - unable to import figma file

### ISSUE THREAD

**Issue by molhamstein** [inspireui/support#2433]
1. My issue:
i"m unable to open the figma design files 
I have tried to import the file to figma online and it failed 
then i installed figma Mac edition on my Mac and the import failed too
please find below a screen show of the error message i got when tried to import the file 
the loading spinner kept spinning for a couple of minutes then i got this message in the screenshot

2. Screenshots issues (required):
<img width="1280" alt="Screen Shot 2020-03-24 at 12 21 02 PM" src="https://user-images.githubusercontent.com/5015054/77414827-4401a000-6dca-11ea-9b3c-6c9cbc0a0b3e.png">

3. Proof of my purchased (required):
<img width="815" alt="Screen Shot 2020-03-24 at 12 20 23 PM" src="https://user-images.githubusercontent.com/5015054/77415181-becabb00-6dca-11ea-89e4-54f8ba3c6196.png">

3. Config files (required)
there is no special config done, I'm trying to import the .fig file after extracting the zip file

**Comment by minhcasi** [comment]
it's working fine - https://tppr.me/VHtEp

you can share the email then i can add to the design workspace - thanks

**Comment by molhamstein** [comment]
I appreciate that 
here is my email 
fatherboard1@gmail.com

many thanks :)

**Comment by minhcasi** [comment]
shared - https://tppr.me/EE8lP 

Please clone to your own file

we're glad that it help, please give us some feedback/rating to this page https://codecanyon.net/downloads  if the product is helpful for your business, we are working hard to update more awesome and powerful features on next coming version release. Let us know if you have any feedback. Thank you very much!
