### ISSUE TITLE
[Fluxstore Pro ] -  White screen after launching the iOS app but working fine on Android

### ISSUE THREAD

**Issue by HarshalDewangan** [inspireui/support#2434]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: I have made successfully flux store for the android app with your flux store pro source code, but when I try to make the same for iOS,  it builds the app but when launching in iOS emulator the app shows a white screen instead and nothing works after that. I don't understand why is this happening I tried your old solutions found in the comment sections but nothing is working for me. Please help me to fix this. There is something showing about Facebook in logs when I checked it, see the attachments.
 

2. Screenshots issues (required): 

![3d531b0b-910c-46a6-949c-824000e060de](https://user-images.githubusercontent.com/52627887/77414800-900f0d80-6de7-11ea-9636-26e94eca5cd0.jpg)

3. Proof of my purchased (required):

![Screenshot (208)](https://user-images.githubusercontent.com/52627887/77414903-b6cd4400-6de7-11ea-90fc-5bc1b6757f01.png)

3. Config files (required) :

[config.zip](https://github.com/inspireui/support/files/4374652/config.zip)

system log : 
[system log.txt](https://github.com/inspireui/support/files/4374663/system.log.txt)

**Comment by minhcasi** [comment]
could you try to clean the cache by using this solution - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

**Comment by HarshalDewangan** [comment]
I tried this one but nothing is working for me I think the Facebook SDK is having some problem on iOS please tell me how to fix it. Check this section. tell me what to put here. I don't want to show any ads in my app. 

![dc35eb8e-7092-4c3c-9b5c-f7efb0b364d6](https://user-images.githubusercontent.com/52627887/77454267-4ee62000-6e1e-11ea-9c7b-2c33878f4d93.jpg)

**Comment by minhcasi** [comment]
@HarshalDewangan - could you try to run the simulator on iphone X or XS, it could be the iOS issue on your out-date iphone-8 simulator - thank you!

**Comment by HarshalDewangan** [comment]
I tried that too, but that is also not working for me. 
I tried running it on all the simulators.

**Comment by minhcasi** [comment]
@minhtruong315 - please help to support this issue

**Comment by saifmuhtar** [comment]
@minhtruong315 I'm also facing the same issue.

**Comment by HarshalDewangan** [comment]
Yes, let me know if anyone is able to fix this issue, flux store pro developers should make a full solution article for this and post it here in case if anyone needs it

**Comment by minhtruong315** [comment]
try this https://www.dropbox.com/s/a69c33gxzfs83dq/splash.mov?dl=0
then run again

**Comment by saifmuhtar** [comment]
> try this https://www.dropbox.com/s/a69c33gxzfs83dq/splash.mov?dl=0
> then run again
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/841a30d270f8e3d335b9ea9ff3319779785b0578/68747470733a2f2f7777772e64726f70626f782e636f6d2f74656d705f7468756d625f66726f6d5f746f6b656e2f732f61363963333367787a6673383364713f70726573657276655f7472616e73706172656e63793d46616c73652673697a653d3132303078313230302673697a655f6d6f64653d34">Dropbox**[splash.mov](https://www.dropbox.com/s/a69c33gxzfs83dq/splash.mov?dl=0)**Shared with Dropbox

@minhtruong315 
I tried this method, but it's still not working.
It gave me this error:

Xcode's output:
↳
    /Volumes/StudioSSD/Project/footballsouvenir/footballsouvenir-1.6.5c/ios/Runner/AppDelegate.swift:3:8: error: no such module 'GoogleMaps'
    import GoogleMaps
           ^
    note: Using new build system
    note: Planning build
    note: Constructing build description

Could not build the application for the simulator.
Error launching application on iPhone 11 Pro.

**Comment by minhtruong315** [comment]
@HarshalDewangan how about your issue? I gave you the solution, but You haven't responsed the result yet

**Comment by ahmetozcan9211** [comment]
> @HarshalDewangan how about your issue? I gave you the solution, but You haven't responsed the result yet



> > * Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> > * Try to explain your all problems in one ticket, instead of creating multi tickets.
> > * After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> > * IMPORTANT: We will close the ticket if you could not prove as our customer.
> 
> 1. My issue: I have made successfully flux store for the android app with your flux store pro source code, but when I try to make the same for iOS,  it builds the app but when launching in iOS emulator the app shows a white screen instead and nothing works after that. I don't understand why is this happening I tried your old solutions found in the comment sections but nothing is working for me. Please help me to fix this. There is something showing about Facebook in logs when I checked it, see the attachments.
> 2. Screenshots issues (required):
> 
> ![3d531b0b-910c-46a6-949c-824000e060de](https://user-images.githubusercontent.com/52627887/77414800-900f0d80-6de7-11ea-9636-26e94eca5cd0.jpg)
> 
> 1. Proof of my purchased (required):
> 
> ![Screenshot (208)](https://user-images.githubusercontent.com/52627887/77414903-b6cd4400-6de7-11ea-90fc-5bc1b6757f01.png)
> 
> 1. Config files (required) :
> 
> [config.zip](https://github.com/inspireui/support/files/4374652/config.zip)
> 
> system log :
> [system log.txt](https://github.com/inspireui/support/files/4374663/system.log.txt)



> @minhtruong315 I'm also facing the same issue.



> @minhtruong315 - please help to support this issue

you can solve problem by apply 4. step. (not need another ones) only apple 4. step. it will be work. ty

**Comment by HarshalDewangan** [comment]
I will try this and let you know if this works for me, also I updated the mstore api plugin to latest version now, and my server was having some issue that it was blocking some request from apple webkit so I scanned it and found some threats there so that could be the problem but i will also try this and let you know if this fix my issue or not

**Comment by minhcasi** [comment]
@HarshalDewangan @saifmuhtar - also try this solution on latest XCode 11.4  - https://flutter.dev/docs/development/ios-project-migration

**Comment by minhcasi** [comment]
Please try the load update 1.6.6 to fix the issues, let us know if you have any questions - thank you!
