### ISSUE TITLE
[Fluxstore MV] - CustomMenu on SideMenu

### ISSUE THREAD

**Issue by ideas24** [inspireui/support#2435]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
I want to create a custom menu on the Sidemenu that will be linked to a webview. I have tried all my best but I can not get it to work.

2. Screenshots issues (required):

3. Proof of my purchased (required):

![proof-of-purchase](https://user-images.githubusercontent.com/34719083/77415429-6390cc80-6dba-11ea-80a9-7fbc3d37328b.PNG)

3. Config files (required)

**Comment by ideas24** [comment]
@minhcasi and @kvt0012 please assist me on the issue. No response in days

**Comment by kvt0012** [comment]
Which screen you need to customize side menu, sir ?
Thank you

**Comment by ideas24** [comment]
@kvt0012 The menu.dart screen. Where there is a blog, Shop, Home and By Categories. I will like to add my custom menu say "Services" which when clicked will link to a webpage. Something similar to the "About Us" in settings.dart file.
Thank You. Kindly assist me Asap

**Comment by minhcasi** [comment]
@ideas24 - pls use this code from lib/menu.dart - https://tppr.me/VmfLV

Code: 

```
import 'widgets/common/webview.dart';
....
ListTile(
                  leading: const Icon(
                    Icons.public,
                    size: 20,
                  ),
                  title: Text('Custom Page'),
                  onTap: () {
                    Navigator.push(
                        context,
                        MaterialPageRoute(
                            builder: (context) => WebView(
                                url: "https://inspireui.com/about",
                                title: "About Us")));
                  },
                ),
```

**Comment by ideas24** [comment]
@minhcasi thank you. I am trying it out. Please respond to my email on the Vendor Store error after update. Thanks
