### ISSUE TITLE
[my-product] - Mstore Checkoutpage

### ISSUE THREAD

**Issue by tozgan** [inspireui/support#2436]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
Hi
Checkout page

         add_filter('woocommerce_checkout_fields', array( $this, 'ilce_alaninin_tanimlanmasi_ve_oncelik_siralamalari' ), 9999);

        add_filter('woocommerce_checkout_fields', array( $this, 'odeme_alanlarinin_son_siralama_kontrolu' ), 10000);

        add_filter('woocommerce_default_address_fields', array( $this, 'adres_alanlari_oncelik_siralamalari' ), 9999);

        add_action('woocommerce_before_checkout_billing_form', array( $this, 'secili_ilce_bilgileri' ) );

I want to run the plugin https://wordpress.org/plugins/intense-turkiye-il-ilce-eklentisi-for-woocommerce
2. Screenshots issues (required): 

3. Proof of my purchased (required): https://ibb.co/g47Fk2W

3. Config files (required)

**Comment by minhcasi** [comment]
@tozgan you can try to add these function to the functions.php inside the folder theme - thank you!

**Comment by tozgan** [comment]
this is not working

**Comment by minhcasi** [comment]
@tozgan - please try your best with the customization as this is kind of advance customization:

1. you need to research how to include to the Rest API to display these field, it could be include from the meta_data

2. Check some extra plugin that supports via API - https://wordpress.org/plugins/rest-api-custom-fields/

This is as far as we could help with the suggestion for this customization - thanks
