### ISSUE TITLE
[beonews-pro] - How to configure AppIntro for beonews-pro

### ISSUE THREAD

**Issue by Cod3Guy** [inspireui/support#2437]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: How to configure AppIntro for beonews-pro. There are "Config.showAppIntro" at RootRouter.js file, however I got "pages.map" error

2. Screenshots issues (required): 
<img width="367" alt="Screenshot 2020-03-24 at 11 09 50 PM" src="https://user-images.githubusercontent.com/10850622/77441683-adae9800-6e24-11ea-9c3e-09137af0ba41.png">

3. Proof of my purchased (required): 
**Date**: 26 Jan 2020
**Invoice No**: IVIP36220468
**Order No**: 119399406
**Purchase code**: 77105d26-b9ad-416f-883b-16af6a48cab3

3. Config files (required)
[Config.js.zip](https://github.com/inspireui/support/files/4376060/Config.js.zip)

**Comment by luyx2412** [comment]
Hi @Cod3Guy This is 2 files to fix your issue. We will update in next version.
- Replace this file in `App/Common/Config.js`  [Config.js.zip](https://github.com/inspireui/support/files/4396640/Config.js.zip)
- Replace this file in `App/Components/AppIntro/index.js`  [index.js.zip](https://github.com/inspireui/support/files/4396641/index.js.zip)

Thanks
