### ISSUE TITLE
[FluxStore Pro] - All My Peoblems And Requests

### ISSUE THREAD

**Issue by bikostudio** [inspireui/support#2439]
Hi guys,
I decided to collect all my Problems and Requests in one ticket as most of my problems not solved until now may be due to the mess.

I'm Using :
WordPress Woocommerce (Latest Version)
FluxStore Pro 1.6.5c
Mstore API Plugin  (Latest Version)

**====  PROBLEMS =================================**

**Problem 1 | Error in cart 
Status: Not solved yet** 

Error in cart after closing the app and reopen it again.
 
![2020-04-01_073703](https://user-images.githubusercontent.com/62074493/78114168-1edfe380-7401-11ea-9378-42472191060a.jpg)

----------------------------------------------------------------------------------
**Problem 2 | Profile Update Not Working
Status: solved ** 

Profile Update Not Working + Spilling Mistakes 
![11111](https://user-images.githubusercontent.com/62074493/77919079-03f45e80-729d-11ea-805b-70c27709fe25.jpg)
 
-----------------------------------------------------------------------------------
**Problem 3 | Problem adding new quantities
Status: solved ** 

Problem adding new quantities from the Cart Page.
 
![2020-03-24_211042](https://user-images.githubusercontent.com/62074493/77919125-140c3e00-729d-11ea-8d94-543eea7c15b1.jpg)

===============================================

**====  REQUESTS =================================**

**Request 1 | 
Status: Not Answered** 

I want to add a Company and a Mobile fields to the registration form also to be added to the WordPress profile as well.
What I did till now:
-	Added new stings for the both Company and Mobile fields. In file : lib\generated\l10n.dart
-	Added a new fields for both in file : lib\screens\registration.dart 
What I need to do next?
![2020-03-30_143626](https://user-images.githubusercontent.com/62074493/77919343-59c90680-729d-11ea-9fb9-619d3f5abcee.jpg)
![2020-03-30_143657](https://user-images.githubusercontent.com/62074493/77919359-5df52400-729d-11ea-8fd9-e87da710bf6c.jpg)

=============================================================
Please I need more detailed steps with codes as I don't have coding skills.

Thank you for your time and help

**Comment by minhcasi** [comment]
Hi, thank you for the feedback. Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads it's used to verify your proof of purchase? 
Sorry for any inconvenience, we will reopen the ticket when it is verified, thank you!

**Comment by bikostudio** [comment]
sure
![2020-03-25_091758](https://user-images.githubusercontent.com/62074493/77511359-96e66080-6e79-11ea-8e21-5c55627a04b3.jpg)

**Comment by bikostudio** [comment]
I have many problems beside this one and I will collect them all in one post. but i need to solve this problem for now please. thank you for your time.

**Comment by philipvu30** [comment]
Hi @bikostudio ,

Would you mind sending me your config files (config.dart and all the config_xx.json)? Thank you

**Comment by bikostudio** [comment]
Ok bro. This is the files you need.



Also I have some questions if you can help me with:

1- Product short description not shown

2- How to sort categories in a custom order?

3- How to change the splash screen background color?

4- How to add new fields ( Company – phone )  in registration page?



Thank you for your time

**Comment by bikostudio** [comment]
I sent files to support@inspireui.com also

**Comment by philipvu30** [comment]
Hi @bikostudio ,

Please update to the latest version of the app (1.6.5).
- Issue 2 and 4: We currently are not supporting these features. We will consider implementing them in the future.
- Please change it here: lib/app.dart
![image](https://user-images.githubusercontent.com/54442328/77729616-b0caa380-7031-11ea-83ff-d3266d170068.png)

**Comment by bikostudio** [comment]
1- I'm using the latest 1.6.5c and still having problem in adding new quantities from the cart screen.
2- Also the background color not changed. 
3- png splash screen not full screen.
![2020-03-28_113208](https://user-images.githubusercontent.com/62074493/77820116-8b4ca100-70e8-11ea-8ced-7badb79a5b60.jpg)

**Comment by philipvu30** [comment]
Hi @bikostudio ,

Would you mind sending me your email? I'll send you the fixed files. Thank you

**Comment by bikostudio** [comment]
Thank you @philipvu30 for your help. 
For background I changed it in and change the path to your image here: lib/common/constants/images.dart as you said. thanks

For quantity issue here is an email you can send me files to : egymido78@yahoo.com
Thank you for your time

**Comment by bikostudio** [comment]
Also I have a new Cart Error ...
After adding items to cart and open the cart page every this is working fine. But when I close the app and reopen is again and open the Cart I find this error. 

![index](https://user-images.githubusercontent.com/62074493/77896280-52dbcd00-7278-11ea-9d38-c4269b0acac2.jpg)

**Comment by philipvu30** [comment]
I sent you the lib folder. Please replace it and let see if the issues still persist. Thank you

**Comment by bikostudio** [comment]
> 
> 
> I sent you the lib folder. Please replace it and let see if the issues still persist. Thank you

thank you bro. Please see also the latest problem with the cart and updating profile not working

thank you for fast respond and help

**Comment by bikostudio** [comment]
> 
> 
> I sent you the lib folder. Please replace it and let see if the issues still persist. Thank you

I replaced the lib folder and it stuck in splash screen. Please send me only the files you modified to modify them manually.  Thank you

**Comment by philipvu30** [comment]
Hi @bikostudio ,

Please contact me on Skype: vuthanhtoan30. Thank you

**Comment by bikostudio** [comment]
> 
> 
> Hi @bikostudio ,
> 
> Please contact me on Skype: vuthanhtoan30. Thank you

I would love to but I have Skype connection problems in my area so it will not be helpful. 

Any other way please?

thank you

**Comment by bikostudio** [comment]
Hi,

1- I have problem with updating profile information I got this ( Expetion: can not updt user infor)
2- How to display the header with logo and search button and the menu button in all pages?

I'm using latest 1.6.5c + the api plugin is undated too.

thank you for your time

**Comment by philipvu30** [comment]
Hi @bikostudio ,

All of those issues have been fixed with the lib folder I sent you. 

I've already tested it with your config and it was running smoothly. Would you mind take a screenshot of your "stuck in splash screen" problem? Thank you

**Comment by bikostudio** [comment]
Ok, I will try again and will share the screenshot. Thank you for your help and time

**Comment by bikostudio** [comment]
> 
> 
> Hi @bikostudio ,
> 
> All of those issues have been fixed with the lib folder I sent you.
> 
> I've already tested it with your config and it was running smoothly. Would you mind take a screenshot of your "stuck in splash screen" problem? Thank you

![2020-03-30_203253](https://user-images.githubusercontent.com/62074493/77948507-cf48cd00-72c5-11ea-984e-6d90f7cf68ef.jpg)



=================== log ===

Launching lib\main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
√ Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...
D/        (31071): HostConnection::get() New Host Connection established 0x8675a240, tid 31128
D/EGL_emulation(31071): eglCreateContext: 0x98b29220: maj 3 min 0 rcv 3
Debug service listening on ws://127.0.0.1:58698/jmJfgKyEHgs=/ws
Syncing files to device Android SDK built for x86...
D/EGL_emulation(31071): eglMakeCurrent: 0x98b29220: ver 3 0 (tinfo 0x8561ea00)
I/zygote  (31071): Do partial code cache collection, code=60KB, data=41KB
I/zygote  (31071): After code cache collection, code=60KB, data=41KB
I/zygote  (31071): Increasing code cache capacity to 256KB
I/zygote  (31071): Background concurrent copying GC freed 49055(4MB) AllocSpace objects, 31(10MB) LOS objects, 49% free, 2008KB/3MB, paused 2.206ms total 160.061ms
I/zygote  (31071): Background concurrent copying GC freed 18992(1442KB) AllocSpace objects, 4(76KB) LOS objects, 49% free, 3MB/7MB, paused 5.451ms total 82.732ms
D/EGL_emulation(31071): eglMakeCurrent: 0x98b27540: ver 3 0 (tinfo 0x7e7b1610)
I/flutter (31071): [Fluxstore][App] splash screen
W/cr_CrashFileManager(31071): /data/user/0/com.bikostudio.technomed/cache/WebView/Crash Reports does not exist or is not a directory
D/EGL_emulation(31071): eglMakeCurrent: 0x98b29220: ver 3 0 (tinfo 0x8561ea00)
E/flutter (31071): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Unable to load asset: assets/images/splashscreen.flr
E/flutter (31071): #0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:221:7)
E/flutter (31071): <asynchronous suspension>
E/flutter (31071): #1      AssetFlare.load (package:flare_flutter/provider/asset_flare.dart:26:40)
E/flutter (31071): #2      FlareCacheAsset.load (package:flare_flutter/flare_cache_asset.dart:30:19)
E/flutter (31071): #3      Cache.getAsset (package:flare_flutter/cache.dart:58:11)
E/flutter (31071): #4      cachedActor (package:flare_flutter/flare_cache.dart:27:12)
E/flutter (31071): #5      FlareRenderBox.loadFlare (package:flare_flutter/flare_render_box.dart:308:35)
E/flutter (31071): #6      FlareActorRenderObject.coldLoad (package:flare_flutter/flare_actor.dart:369:20)
E/flutter (31071): #7      FlareRenderBox.load (package:flare_flutter/flare_render_box.dart:258:7)
E/flutter (31071): #8      FlareRenderBox.attach (package:flare_flutter/flare_render_box.dart:104:7)
E/flutter (31071): #9      AbstractNode.adoptChild (package:flutter/src/foundation/node.dart:132:13)
E/flutter (31071): #10     RenderObject.adoptChild (package:flutter/src/rendering/object.dart:1238:11)
E/flutter (31071): #11     RenderObjectWithChildMixin.child= (package:flutter/src/rendering/object.dart:2905:7)
E/flutter (31071): #12     SingleChildRenderObjectElement.insertChildRenderObject (package:flutter/src/widgets/framework.dart:5460:18)
E/flutter (31071): #13     RenderObjectElement.attachRenderObject (package:flutter/src/widgets/framework.dart:5295:35)
E/flutter (31071): #14     RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5058:5)
E/flutter (31071): #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (31071): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (31071): #17     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter (31071): #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (31071): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (31071): #20     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter (31071): #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (31071): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (31071): #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter (31071): #24     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter (31071): #25     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
E/flutter (31071): #26     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter (31071): #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (31071): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (31071): #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter (31071): #30     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter (31071): #31     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
E/flutter (31071): #32     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
E/flutter (31071): #33     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter (31071): #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (31071): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (31071): #36     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter (31071): #37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (31071): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (31071): #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter (31071): #40     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter (31071): #41     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
E/flutter (31071): #42     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter (31071): #43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (31071): #44     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (31071): #45     ComponentElement.performRebuild (package:flutter/src/widgets/framework.da
I/zygote  (31071): Background concurrent copying GC freed 66849(2MB) AllocSpace objects, 0(0B) LOS objects, 49% free, 2MB/4MB, paused 1.196ms total 107.804ms
I/flutter (31071): [Fluxstore][App] splash screen
I/zygote  (31071): Background concurrent copying GC freed 55172(2MB) AllocSpace objects, 0(0B) LOS objects, 50% free, 2MB/4MB, paused 2.663ms total 101.809ms

======

I will resend the lib folder i used before you send me yours. I will send it to email : support@inspireui.com

**Comment by philipvu30** [comment]
Hi @bikostudio 

Did you forget to change the image path?

**Comment by bikostudio** [comment]
> 
> 
> Hi @bikostudio
> 
> Did you forget to change the image path?

Hi @philipvu30   the lib folder you sent has the file :  lib\common\constants.dart 

is empty and when I try to add code from the previous constants.dart  I was use before it is not working too.

Please, send me the modifications only as codes with files names and I will do it manually. 

thank you for your time.

**Comment by philipvu30** [comment]
Hi @bikostudio ,

Sorry, I forgot to remind you, the lib folder I sent you yesterday is the new one and has not released yet. So the folder structure is a bit different from the old one.

**Comment by bikostudio** [comment]
Problem 4 | Firebase Notifications
Status: Not solved yet

I have created a Firebase account with all settings by following your tutorial : https://docs.inspireui.com/fluxstore/firebase/ 

I can send test notifications to the test device now but when I tap on the notification on my phone it open the application. And not save in Notify Messages page in the App.

How to redirect user to   Notify Messages page  after tapping on the notification?

![2020-03-31_115054](https://user-images.githubusercontent.com/62074493/78013926-79b50480-7347-11ea-9c73-6c33adfb857c.jpg)

![2020-03-31_115110](https://user-images.githubusercontent.com/62074493/78013948-8174a900-7347-11ea-87a6-24c3ac50deee.jpg)

![2020-03-31_115436](https://user-images.githubusercontent.com/62074493/78013978-8d606b00-7347-11ea-9229-dc4749cfa02a.jpg)

![index3](https://user-images.githubusercontent.com/62074493/78014008-97826980-7347-11ea-83dd-df57f09f40ee.jpg)

![index2](https://user-images.githubusercontent.com/62074493/78014020-9c471d80-7347-11ea-94c0-333b57a694ea.jpg)

**Comment by bikostudio** [comment]
> 
> 
> Hi @bikostudio ,
> 
> Sorry, I forgot to remind you, the lib folder I sent you yesterday is the new one and has not released yet. So the folder structure is a bit different from the old one.

Hi @philipvu30 No problem bro, thank you for reminding me. So where the file that I can change the images path?

thank you

**Comment by philipvu30** [comment]
Hi @bikostudio ,

You can change the image in lib/common/constants/images.dart.

May I ask if all the issues above have been fixed except the "Firebase Notification"?

**Comment by bikostudio** [comment]
> 
> 
> Hi @bikostudio ,
> 
> You can change the image in lib/common/constants/images.dart.
> 
> May I ask if all the issues above have been fixed except the "Firebase Notification"?

Hi @philipvu30  thank you. I will try and will feedback for problems solved.

thank you for your time and help

**Comment by bikostudio** [comment]
Hi @philipvu30  

Here is the solved problems :

Problem 2 | Profile Update Not Working = Solved
Problem 3 | Problem adding new quantities = Solved 

Problems still:
Problem 1 | Error in cart



Problem 5 (New) | 


When I add or edit or delete a product and go to opened app and scroll down to refresh the home , the  product's changings   not shown. I have to close the app and reopen it again to show the changes.  


![2020-04-01_093456](https://user-images.githubusercontent.com/62074493/78114717-fd332c00-7401-11ea-8aed-15ae13c7420a.jpg)

=========

What about my Request 1 |

I want to add a Company and a Mobile fields to the registration form also to be added to the WordPress profile as well?

Thank you for your time

**Comment by bikostudio** [comment]
### PS : **The** cart problem is always with the first added item only

![index9](https://user-images.githubusercontent.com/62074493/78149142-eeff0300-7435-11ea-97de-3ce455380b80.jpg)

**Comment by philipvu30** [comment]
Hi,

Please update to the latest version 1.6.6 and see if the cart issue still persists.
On your first request, we currently don't support implementing additional features.
Problem 5: That's how the app works. Not all features support real-time update. We'll consider to add it in the future. Thanks for pointing out.

**Comment by bikostudio** [comment]
> 
> 
> Hi,
> 
> Please update to the latest version 1.6.6 and see if the cart issue still persists.
> On your first request, we currently don't support implementing additional features.
> Problem 5: That's how the app works. Not all features support real-time update. We'll consider adding it in the future. Thanks for pointing out.

Thank you @philipvu30 
I will update and see.

what about the Problem 4? 
Problem 4 | Firebase Notifications

I have created a Firebase account with all settings by following your tutorial : https://docs.inspireui.com/fluxstore/firebase/

I can send test notifications to the test device now but when I tap on the notification on my phone it open the application. And not save in Notify Messages page in the App.

How to redirect user to Notify Messages page after tapping on the notification?

thank you for your help

**Comment by bikostudio** [comment]
> 
> 
> Hi,
> 
> Please update to the latest version 1.6.6 and see if the cart issue still persists.
> On your first request, we currently don't support implementing additional features.
> Problem 5: That's how the app works. Not all features support real-time update. We'll consider adding it in the future. Thanks for pointing out.

@philipvu30  The downloadable version on codecanyon.net is 1.6.5c not 1.6.6.

**Comment by philipvu30** [comment]
Hi,

You can download the new version once you receive an email from us.

**Comment by minhcasi** [comment]
@bikostudio - the latest 1.6.6 is ready for downloading, please help to update and let us know if you have any issues, feel free to reopen the ticket - thank you!

**Comment by bikostudio** [comment]
> 
> 
> @bikostudio - the latest 1.6.6 is ready for downloading, please help to update and let us know if you have any issues, feel free to reopen the ticket - thank you!

Hi @philipvu30  @minhcasi ,

I did the update to 1.6.6 and the app keep crashing " App has stopped"

I did all the steps to modify files as the 1.6.5c .

any ideas? 
thank you for your help

**Comment by bikostudio** [comment]
Hi,

I'm having problem with building the app. It stuck here

[image: 2020-04-04_174759.jpg]

error: The method 'getLanguagesList' isn't defined for the class
'_LanguageState'. (undefined_method at [fstore]
lib\screens\language.dart:39)
error: The name 'RouteList' is defined in the libraries
'package:fstore/common/constants/route_constants.dart' and
'package:fstore/common/constants/routes.dart (via
package:fstore/common/constants.dart)'. (ambiguous_import at [fstore]
lib\screens\login_sms\index.dart:174)
error: Undefined name 'kTeal400'. (undefined_identifier at [fstore]
lib\screens\onboard_screen.dart:37)
error: Undefined name 'kTeal400'. (undefined_identifier at [fstore]
lib\screens\onboard_screen.dart:45)
error: Undefined name 'kTeal400'. (undefined_identifier at [fstore]
lib\screens\onboard_screen.dart:50)
error: Undefined name 'kGrey900'. (undefined_identifier at [fstore]
lib\screens\onboard_screen.dart:74)
error: Undefined name 'kGrey600'. (undefined_identifier at [fstore]
lib\screens\onboard_screen.dart:80)
error: Undefined name 'kGrey900'. (undefined_identifier at [fstore]
lib\screens\onboard_screen.dart:100)
error: Undefined name 'kGrey900'. (undefined_identifier at [fstore]
lib\screens\onboard_screen.dart:101)
error: The method 'setStatusBarWhiteForeground' isn't defined for the class
'SettingScreenState'. (undefined_method at [fstore]
lib\screens\settings.dart:109)
error: The getter 'password' isn't defined for the class 'User'.
(undefined_getter at [fstore] lib\screens\user_update.dart:38)
error: The getter 'password' isn't defined for the class 'User'.
(undefined_getter at [fstore] lib\screens\user_update.dart:39)
error: Undefined name 'kGrey400'. (undefined_identifier at [fstore]
lib\screens\wishlist.dart:75)
error: Undefined name 'kGrey200'. (undefined_identifier at [fstore]
lib\screens\wishlist.dart:77)
error: Undefined name 'kGrey900'. (undefined_identifier at [fstore]
lib\screens\wishlist.dart:130)
error: Undefined name 'kGrey200'. (undefined_identifier at [fstore]
lib\screens\wishlist.dart:157)
error: Undefined name 'kGrey400'. (undefined_identifier at [fstore]
lib\screens\wishlist.dart:158)
error: Undefined name 'kGrey400'. (undefined_identifier at [fstore]
lib\screens\wishlist.dart:234)
error: Undefined name 'kGrey200'. (undefined_identifier at [fstore]
lib\screens\wishlist.dart:257)
error: The getter 'currentAttr' isn't defined for the class
'FilterAttributeModel'. (undefined_getter at [fstore]
lib\widgets\backdrop_menu.dart:302)
error: The getter 'currentAttr' isn't defined for the class
'FilterAttributeModel'. (undefined_getter at [fstore]
lib\widgets\backdrop_menu.dart:309)
error: Undefined name 'kColorNameToHex'. (undefined_identifier at [fstore]
lib\widgets\cart_item.dart:45)
info: Unused import:
'package:font_awesome_flutter/font_awesome_flutter.dart'. (unused_import at
[fstore] lib\menu.dart:4)
info: Unused import: 'common/config.dart'. (unused_import at [fstore]
lib\menu.dart:7)
info: The value of the local variable 'loggedIn' isn't used.
(unused_local_variable at [fstore] lib\menu.dart:28)
info: Unused import: '../common/config.dart'. (unused_import at [fstore]
lib\screens\language.dart:4)
info: Unused import: '../common/styles.dart'. (unused_import at [fstore]
lib\screens\onboard_screen.dart:8)
info: Unused import: '../common/styles.dart'. (unused_import at [fstore]
lib\screens\settings.dart:10)
info: Unused import: '../common/tools.dart'. (unused_import at [fstore]
lib\screens\settings.dart:11)
info: Unused import: 'currencies.dart'. (unused_import at [fstore]
lib\screens\settings\settings.dart:19)
info: The declaration '_loginFacebook' isn't referenced. (unused_element at
[fstore] lib\screens\users\login.dart:119)
info: The declaration '_loginSMS' isn't referenced. (unused_element at
[fstore] lib\screens\users\login.dart:216)
info: The declaration '_loginGoogle' isn't referenced. (unused_element at
[fstore] lib\screens\users\login.dart:234)
info: Unused import: '../common/styles.dart'. (unused_import at [fstore]
lib\screens\wishlist.dart:4)
info: Unused import: '../common/styles.dart'. (unused_import at [fstore]
lib\widgets\cart_item.dart:6)
