### ISSUE TITLE
[ListApp] Featured Images Missing - mylisting theme

### ISSUE THREAD

**Issue by bobozd** [inspireui/support#244]
I try to build my app with latest CeBuilder on OSX.
It seams all work fine except Feature Image of any listing not showed or loaded.
Please check my video link

**Screenshots**
https://drive.google.com/file/d/1DZCYbwNDrLW9bP-iQeCc6FofSOmrsVdC/view?usp=sharing

**Comment by reconshield** [comment]
if u update mylisting theme. featured image will disapear. check all your listing post.make sure featured image is set. Listapp featured image working fine in mylisting. check your image resizer and image resolution setting ( can find from Listapp Documentation )

**Comment by thangvo9x** [comment]
You can refer solution here
 https://github.com/inspireui/support/issues/184#issuecomment-462216200
