### ISSUE TITLE
Fluxlist doesn't work!. Help please.

### ISSUE THREAD

**Issue by master736** [inspireui/support#2440]
My environment works.
I tested with flutter doctor.
And I ran another project from you (fluxstore) and it runs fine.
This one does not. Here's the error message.
<img width="1656" alt="Screen Shot 2020-03-24 at 5 57 47 PM" src="https://user-images.githubusercontent.com/40126918/77490765-0e27e000-6df9-11ea-90d3-ee6148e01789.png">

**Comment by minhcasi** [comment]
Hi, thank you for the feedback. Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads it's used to verify your proof of purchase? 
Sorry for any inconvenience, we will reopen the ticket when it is verified, thank you!

**Comment by master736** [comment]
Sure.

**Comment by master736** [comment]
Hey man I replied to your email. And send the picture but here it is again
![Screenshot (13)](https://user-images.githubusercontent.com/40126918/77621297-66dea200-6ef9-11ea-8650-8a256a07befc.png)

**Comment by master736** [comment]
> Hi, thank you for the feedback. Could you help to share the screenshot of the purchase screenshot from [http://codecayon.net/downloads it's](http://codecayon.net/downloads%C2%A0it's) used to verify your proof of purchase?
> Sorry for any inconvenience, we will reopen the ticket when it is verified, thank you!

![Screenshot (13)](https://user-images.githubusercontent.com/40126918/77621342-79f17200-6ef9-11ea-8c85-112950f3331a.png)
