### ISSUE TITLE
[MStore-Expo] - Infinite scrolling at Home page

### ISSUE THREAD

**Issue by tl3308** [inspireui/support#2443]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: In home page when I select list view and scroll down (to refresh data) more than 10 times, it will keep on refreshing products and loading already loaded products

2. Screenshots issues (required):
![Screenshot_20200325_105900_hk com tova mstore 1](https://user-images.githubusercontent.com/696268/77498618-06b11700-6e8b-11ea-8325-9cfa18836b7f.jpg)

3. Proof of my purchased (required):
![image](https://user-images.githubusercontent.com/696268/77498634-12044280-6e8b-11ea-8bee-8da3d936226d.png)

3. Config files (required)
Not modified

**Comment by minhcasi** [comment]
@tl3308 - please help to post the issues to - #2442
