### ISSUE TITLE
[FluxStore-MV] product Variation not Show

### ISSUE THREAD

**Issue by mdyunus24bd** [inspireui/support#2444]
product Variation not Show not show
.

![Annotation 2020-03-24 215444](https://user-images.githubusercontent.com/56026816/77499605-00f80900-6e6c-11ea-847c-aa05a74cf467.jpg)

@
![Screenshot_20200325-074203](https://user-images.githubusercontent.com/56026816/77499667-2a189980-6e6c-11ea-985c-eacb506e8615.png)

**Comment by philipvu30** [comment]
Hi @mdyunus24bd ,

Please send me your config files (config.dart and all the config_xx.json). Thank you

**Comment by mdyunus24bd** [comment]
https://drive.google.com/open?id=13lTMm-kpoyLXHngKktcIQ4xlyDDDmLI8

https://drive.google.com/open?id=1kMXHwcvReXoY78ErGQRmqYTEGx0fFKAe

see this file

**Comment by mdyunus24bd** [comment]
**My Payment Getway Not Working**

1- my PayPal Express checkout plugin not access on your apps
 2- I setup a my   Paypal Sandbox  API but not show my API. Show your test Api  name. not access 
3- Paypal Live API not working

please how to config my payment getaway  I using Paypal express checkout plugin by Card Payment & Paypal.

see this scereenshort
https://prntscr.com/rmbun2
https://prntscr.com/rmbujr
https://prntscr.com/rmbuca

Screenshot_20200325-074203

**Comment by minhcasi** [comment]
@philipvu30 - please help to follow up the ticket - thank you!

**Comment by philipvu30** [comment]
Hi @mdyunus24bd ,

Sorry for the late response. It seems your website is down at the moment.

Please send me a DM via Skype: vuthanhtoan30 / email: toan@inspireui.com when it is online so I can help you asap. 

Thanks

**Comment by mdyunus24bd** [comment]
i send a email check it

**Comment by mdyunus24bd** [comment]
I call you don't receive it.

**Comment by minhcasi** [comment]
@philipvu30 - please help to check as high priority

**Comment by mdyunus24bd** [comment]
see this video = https://drive.google.com/file/d/1LiHt2YfjJ280jjeCTNZ6BsyqLJzF6nAL/view
your new version is the same problems.
not show product Variation  &  price.
2nd- not working payment getaway Paypal Express Checkout plugin

**Comment by philipvu30** [comment]
Hi @mdyunus24bd,

Sorry for not picking up calls, but please understand that I'm not always at my work-space, and you called me when it was late in my time-zone.

Now back to your issues:
 - Variations issue: Please follow this ticket's solution [2476](https://github.com/inspireui/support/issues/2476)
 
 - Have you updated Mstore_Api plugin to the latest version? If you haven't, please do so. Otherwise, I could not test your paypal payment issue. Also I did look into Woocommerce payment settings but did not find the Paypal express payment method. Am I missing something?

**Comment by mdyunus24bd** [comment]
![Annotation 2020-04-06 211407](https://user-images.githubusercontent.com/56026816/78585859-9b345580-784b-11ea-899d-2e6e53d7443d.jpg)
 I have a Mstore Api plugin latest version .you check it and solve this payment problems

**Comment by mdyunus24bd** [comment]
not run apps on mobile see this error 

Compiler message:
lib/models/product.dart:10:8: Error: Error when reading 'lib/services/helper/magento.dart': The system cannot find the file specified.

import '../services/helper/magento.dart';
       ^
lib/models/product.dart:560:22: Error: The getter 'MagentoHelper' isn't defined for the class 'ProductVariation'.
 - 'ProductVariation' is from 'package:fstore/models/product.dart' ('lib/models/product.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'MagentoHelper'.
    final imageUrl = MagentoHelper.getCustomAttribute(
                     ^^^^^^^^^^^^^
lib/models/product.dart:563:9: Error: The getter 'MagentoHelper' isn't defined for the class 'ProductVariation'.
 - 'ProductVariation' is from 'package:fstore/models/product.dart' ('lib/models/product.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'MagentoHelper'.
        MagentoHelper.getProductImageUrlByName(serverConfig["url"], imageUrl);
        ^^^^^^^^^^^^^
lib/models/product.dart:566:19: Error: The getter 'MagentoHelper' isn't defined for the class 'ProductVariation'.
 - 'ProductVariation' is from 'package:fstore/models/product.dart' ('lib/models/product.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'MagentoHelper'.
    final color = MagentoHelper.getCustomAttribute(
                  ^^^^^^^^^^^^^
lib/models/product.dart:568:18: Error: The getter 'MagentoHelper' isn't defined for the class 'ProductVariation'.
 - 'ProductVariation' is from 'package:fstore/models/product.dart' ('lib/models/product.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'MagentoHelper'.
    final size = MagentoHelper.getCustomAttribute(
                 ^^^^^^^^^^^^^
lib/services/dokan.dart:117:19: Error: The setter 'storeId' isn't defined for the class 'Product'.
 - 'Product' is from 'package:fstore/models/product.dart' ('lib/models/product.dart').
Try correcting the name to the name of an existing setter, or defining a setter or field named 'storeId'.
          product.storeId = "$storeId";
                  ^^^^^^^
lib/services/wcfm.dart:117:19: Error: The setter 'storeId' isn't defined for the class 'Product'.
 - 'Product' is from 'package:fstore/models/product.dart' ('lib/models/product.dart').
Try correcting the name to the name of an existing setter, or defining a setter or field named 'storeId'.
          product.storeId = "$storeId";
                  ^^^^^^^
lib/vendor/products/create_product_screen.dart:58:10: Error: The method 'createProduct' isn't defined for the class 'ProductModel'.
 - 'ProductModel' is from 'package:fstore/models/product.dart' ('lib/models/product.dart').
Try correcting the name to the name of an existing method, or defining a method named 'createProduct'.
        .createProduct(
         ^^^^^^^^^^^^^
lib/services/woo_commerce.dart:232:23: Error: The setter 'storeId' isn't defined for the class 'Product'.
 - 'Product' is from 'package:fstore/models/product.dart' ('lib/models/product.dart').
Try correcting the name to the name of an existing setter, or defining a setter or field named 'storeId'.
              product.storeId = '${item['store']['id']}';
                      ^^^^^^^
lib/vendor/vendor_info.dart:23:60: Error: The getter 'storeId' isn't defined for the class 'Product'.
 - 'Product' is from 'package:fstore/models/product.dart' ('lib/models/product.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'storeId'.
      store = await Services().getStoreInfo(widget.product.storeId);
                                                           ^^^^^^^

Compiler message:
lib/models/product.dart:10:8: Error: Error when reading 'lib/services/helper/magento.dart': The system cannot find the file specified.

import '../services/helper/magento.dart';
       ^
lib/models/product.dart:560:22: Error: The getter 'MagentoHelper' isn't defined for the class 'ProductVariation'.
 - 'ProductVariation' is from 'package:fstore/models/product.dart' ('lib/models/product.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'MagentoHelper'.
    final imageUrl = MagentoHelper.getCustomAttribute(
                     ^^^^^^^^^^^^^
lib/models/product.dart:563:9: Error: The getter 'MagentoHelper' isn't defined for the class 'ProductVariation'.
 - 'ProductVariation' is from 'package:fstore/models/product.dart' ('lib/models/product.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'MagentoHelper'.
        MagentoHelper.getProductImageUrlByName(serverConfig["url"], imageUrl);
        ^^^^^^^^^^^^^
lib/models/product.dart:566:19: Error: The getter 'MagentoHelper' isn't defined for the class 'ProductVariation'.
 - 'ProductVariation' is from 'package:fstore/models/product.dart' ('lib/models/product.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'MagentoHelper'.
    final color = MagentoHelper.getCustomAttribute(
                  ^^^^^^^^^^^^^
lib/models/product.dart:568:18: Error: The getter 'MagentoHelper' isn't defined for the class 'ProductVariation'.
 - 'ProductVariation' is from 'package:fstore/models/product.dart' ('lib/models/product.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'MagentoHelper'.
    final size = MagentoHelper.getCustomAttribute(
                 ^^^^^^^^^^^^^
lib/services/dokan.dart:117:19: Error: The setter 'storeId' isn't defined for the class 'Product'.
 - 'Product' is from 'package:fstore/models/product.dart' ('lib/models/product.dart').
Try correcting the name to the name of an existing setter, or defining a setter or field named 'storeId'.
          product.storeId = "$storeId";
                  ^^^^^^^
lib/services/wcfm.dart:117:19: Error: The setter 'storeId' isn't defined for the class 'Product'.
 - 'Product' is from 'package:fstore/models/product.dart' ('lib/models/product.dart').
Try correcting the name to the name of an existing setter, or defining a setter or field named 'storeId'.
          product.storeId = "$storeId";
                  ^^^^^^^
lib/vendor/products/create_product_screen.dart:58:10: Error: The method 'createProduct' isn't defined for the class 'ProductModel'.
 - 'ProductModel' is from 'package:fstore/models/product.dart' ('lib/models/product.dart').
Try correcting the name to the name of an existing method, or defining a method named 'createProduct'.
        .createProduct(
         ^^^^^^^^^^^^^
lib/services/woo_commerce.dart:232:23: Error: The setter 'storeId' isn't defined for the class 'Product'.
 - 'Product' is from 'package:fstore/models/product.dart' ('lib/models/product.dart').
Try correcting the name to the name of an existing setter, or defining a setter or field named 'storeId'.
              product.storeId = '${item['store']['id']}';
                      ^^^^^^^
lib/vendor/vendor_info.dart:23:60: Error: The getter 'storeId' isn't defined for the class 'Product'.
 - 'Product' is from 'package:fstore/models/product.dart' ('lib/models/product.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'storeId'.
      store = await Services().getStoreInfo(widget.product.storeId);
                                                           ^^^^^^^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

**Comment by mdyunus24bd** [comment]
please you first check it is working well or not. after giving a information . you have my woocommerce API  please check you first. if you need my WP Admin panel access to say us.

please solve this problem

**Comment by philipvu30** [comment]
Hi mdyunus24bd,

My apologies that I did not mention that you just need to check these 2 options on your site as you have already downloaded the latest version.

![image](https://user-images.githubusercontent.com/54442328/78333379-ee8c7680-75b3-11ea-97e4-37b411a92f9d.png)

**Comment by mdyunus24bd** [comment]
**Every Color Not show** 

     

![Annotation 2020-04-07 123952](https://user-images.githubusercontent.com/56026816/78648486-1558ee80-78cd-11ea-90cf-a62395ba9561.jpg)


**I select color & Size and click  BUY NOW See this Error Massage**

![Annotation 2020-04-07 124043](https://user-images.githubusercontent.com/56026816/78648461-0f630d80-78cd-11ea-93a9-03e34cc91688.jpg)

![Annotation 2020-04-07 122808](https://user-images.githubusercontent.com/56026816/78648493-1be76600-78cd-11ea-9f08-6cc32146d800.jpg)

**My Paypal Express Checkout Plugin payment getaway not working. I click this getaway and click Place my Order see Blank page not loading payment getaway.**


![Annotation 2020-04-07 124316](https://user-images.githubusercontent.com/56026816/78649489-8f3da780-78ce-11ea-9b45-443db1b3fcdd.jpg)
![Annotation 2020-04-07 124512](https://user-images.githubusercontent.com/56026816/78649508-949af200-78ce-11ea-9f2a-dee5c692fd37.jpg)

**Comment by philipvu30** [comment]
Hi,

Image 1 + 2 + 3: You need to config your colors of your products in this file: lib/common/constants/colors.dart (kNameToHex). 
![image](https://user-images.githubusercontent.com/54442328/78760051-c5e8f000-79aa-11ea-95d3-361adeaf17f7.png)


Image 4 + 5:  Please remove this code in lib/common/config/payments.dart. Use only paypalconfig

![image](https://user-images.githubusercontent.com/54442328/78760140-e9ac3600-79aa-11ea-9081-4600f73971b2.png)

![image](https://user-images.githubusercontent.com/54442328/78759982-a94cb800-79aa-11ea-896c-d07df166f4d0.png)

**Comment by mdyunus24bd** [comment]
![Annotation 2020-04-09 085624](https://user-images.githubusercontent.com/56026816/78859797-84efea80-7a41-11ea-8449-c3ca25fa1739.jpg)


i Use  paypalconfig but not working  see blank page

**Comment by philipvu30** [comment]
Hi,

Please contact me via Skype if you are online now, I'll help you via TeamViewer.

**Comment by mdyunus24bd** [comment]
![Annotation 2020-04-09 105859](https://user-images.githubusercontent.com/56026816/78878580-ab268200-7a63-11ea-8ac2-aa0731c35d29.jpg)
![Annotation 2020-04-09 105931](https://user-images.githubusercontent.com/56026816/78878614-b8437100-7a63-11ea-80fb-2b8ac41eba6d.jpg)


**Check this issue selected not same**

**Comment by philipvu30** [comment]
Received the mail.
