### ISSUE TITLE
hi 

### ISSUE THREAD

**Issue by fekrasolution** [inspireui/support#2445]
A problem occurred configuring root project 'android'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve com.google.gms:google-services:4.3.2.
     Required by:
         project :
      > Could not resolve com.google.gms:google-services:4.3.2.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/google/gms/google-services/4.3.2/google-services-4.3.2.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/com/google/gms/google-services/4.3.2/google-services-4.3.2.pom'.
               > dl.google.com
      > Could not resolve com.google.gms:google-services:4.3.2.
         > Could not get resource 'https://jcenter.bintray.com/com/google/gms/google-services/4.3.2/google-services-4.3.2.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/google/gms/google-services/4.3.2/google-services-4.3.2.pom'.
               > jcenter.bintray.com
      > Could not resolve com.google.gms:google-services:4.3.2.
         > Could not get resource 'http://storage.googleapis.com/r8-releases/raw/com/google/gms/google-services/4.3.2/google-services-4.3.2.pom'.
            > Could not GET 'http://storage.googleapis.com/r8-releases/raw/com/google/gms/google-services/4.3.2/google-services-4.3.2.pom'.
               > Connect to storage.googleapis.com:80 [storage.googleapis.com/2a00:1450:4006:80a:0:0:0:2010] failed: No route to host (connect failed)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 21s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by minhcasi** [comment]
Hi, thank you for the feedback. Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads it's used to verify your proof of purchase? 
Sorry for any inconvenience, we will reopen the ticket when it is verified, thank you!

**Comment by fekrasolution** [comment]
![Screen Shot 2020-03-25 at 4 22 27 PM](https://user-images.githubusercontent.com/52893412/77546748-fd3ca480-6eb4-11ea-93e1-6125e7c4befd.png)

**Comment by fekrasolution** [comment]
???????

**Comment by fekrasolution** [comment]
[57727148-fluxstore-the-universal-woocommerce-magento-opencart-mobile-app-by-flutter-framework-license.txt](https://github.com/inspireui/support/files/4384119/57727148-fluxstore-the-universal-woocommerce-magento-opencart-mobile-app-by-flutter-framework-license.txt)

**Comment by fekrasolution** [comment]
please help me this is the purchase that i downlode

**Comment by minhcasi** [comment]
verified - we will follow up on ticket #2449
