### ISSUE TITLE
Fluxstore MV Payment getway not working

### ISSUE THREAD

**Issue by mdyunus24bd** [inspireui/support#2446]
1- my PayPal Express checkout plugin not access on your apps
 2- I setup a my   Paypal Sandbox  API but not show my API. Show your test Api  name. not access 
3- Paypal Live API not working

please how to config my payment getaway  I using Paypal express checkout plugin by Card Payment & Paypal.

see this scereenshort
https://prntscr.com/rmbun2
https://prntscr.com/rmbujr
https://prntscr.com/rmbuca

[Screenshot_20200325-074203](https://user-images.githubusercontent.com/56026816/77499667-2a189980-6e6c-11ea-985c-eacb506e8615.png)

**Comment by minhcasi** [comment]
move to #2444

@mdyunus24bd - please help to move your all issues to the same ticket support so that the Technical support will focus on your integration issues 
 - thank you!
