### ISSUE TITLE
a lot of errors! Tutorials doesn't work correctly for me!

### ISSUE THREAD

**Issue by Pascalnhuis** [inspireui/support#2447]
I followed the tutorial, but when I want to test the app I will get:

 margin: const EdgeInsets.only(right: 15),
                                          ^^^^
lib/screens/search/widgets/filters/filter_search_category.dart:85:44: Error: Method not found: 'EdgeInsets.symmetric'.
                            padding: const EdgeInsets.symmetric(
                                           ^^^^^^^^^
lib/screens/search/widgets/filters/filter_search_category.dart:51:21: Error: The getter 'Provider' isn't defined for the class '_FilderSearchCategoryState'.
 - '_FilderSearchCategoryState' is from 'package:fstore/screens/search/widgets/filters/filter_search_category.dart' ('lib/screens/search/widgets/filters/filter_search_category.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Provider'.
    var Categorys = Provider.of<CategoryModel>(context);
                    ^^^^^^^^
lib/screens/search/widgets/filters/filter_search_category.dart:54:22: Error: The getter 'Colors' isn't defined for the class '_FilderSearchCategoryState'.
 - '_FilderSearchCategoryState' is from 'package:fstore/screens/search/widgets/filters/filter_search_category.dart' ('lib/screens/search/widgets/filters/filter_search_category.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Colors'.
        isSelected ? Colors.white : Theme.of(context).accentColor;
                     ^^^^^^
lib/screens/search/widgets/filters/filter_search_category.dart:54:37: Error: The getter 'Theme' isn't defined for the class '_FilderSearchCategoryState'.
 - '_FilderSearchCategoryState' is from 'package:fstore/screens/search/widgets/filters/filter_search_category.dart' ('lib/screens/search/widgets/filters/filter_search_category.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Theme'.
        isSelected ? Colors.white : Theme.of(context).accentColor;
                                    ^^^^^
lib/screens/search/widgets/filters/filter_search_category.dart:57:11: Error: The getter 'Theme' isn't defined for the class '_FilderSearchCategoryState'.
 - '_FilderSearchCategoryState' is from 'package:fstore/screens/search/widgets/filters/filter_search_category.dart' ('lib/screens/search/widgets/filters/filter_search_category.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Theme'.
        ? Theme.of(context).primaryColor
          ^^^^^
lib/screens/search/widgets/filters/filter_search_category.dart:58:11: Error: The getter 'Theme' isn't defined for the class '_FilderSearchCategoryState'.
 - '_FilderSearchCategoryState' is from 'package:fstore/screens/search/widgets/filters/filter_search_category.dart' ('lib/screens/search/widgets/filters/filter_search_category.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Theme'.
        : Theme.of(context).primaryColorLight;
          ^^^^^
lib/screens/search/widgets/filters/filter_search_category.dart:60:12: Error: The getter 'ListenableProvider' isn't defined for the class '_FilderSearchCategoryState'.
 - '_FilderSearchCategoryState' is from 'package:fstore/screens/search/widgets/filters/filter_search_category.dart' ('lib/screens/search/widgets/filters/filter_search_category.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'ListenableProvider'.
    return ListenableProvider.value(
           ^^^^^^^^^^^^^^^^^^
lib/screens/search/widgets/filters/filter_search_category.dart:62:14: Error: The method 'Consumer' isn't defined for the class '_FilderSearchCategoryState'.
 - '_FilderSearchCategoryState' is from 'package:fstore/screens/search/widgets/filters/filter_search_category.dart' ('lib/screens/search/widgets/filters/filter_search_category.dart').
Try correcting the name to the name of an existing method, or defining a method named 'Consumer'.
      child: Consumer<CategoryModel>(builder: (context, value, child) {
             ^^^^^^^^
lib/screens/search/widgets/filters/filter_search_category.dart:64:18: Error: The method 'Center' isn't defined for the class '_FilderSearchCategoryState'.
 - '_FilderSearchCategoryState' is from 'package:fstore/screens/search/widgets/filters/filter_search_category.dart' ('lib/screens/search/widgets/filters/filter_search_category.dart').
Try correcting the name to the name of an existing method, or defining a method named 'Center'.
          return Center(child: kLoadingWidget(context));
                 ^^^^^^
lib/screens/search/widgets/filters/filter_search_category.dart:66:16: Error: The method 'Container' isn't defined for the class '_FilderSearchCategoryState'.
 - '_FilderSearchCategoryState' is from 'package:fstore/screens/search/widgets/filters/filter_search_category.dart' ('lib/screens/search/widgets/filters/filter_search_category.dart').
Try correcting the name to the name of an existing method, or defining a method named 'Container'.
        return Container(
               ^^^^^^^^^
lib/screens/search/widgets/filters/filter_search_category.dart:68:18: Error: The method 'Center' isn't defined for the class '_FilderSearchCategoryState'.
 - '_FilderSearchCategoryState' is from 'package:fstore/screens/search/widgets/filters/filter_search_category.dart' ('lib/screens/search/widgets/filters/filter_search_category.dart').
Try correcting the name to the name of an existing method, or defining a method named 'Center'.
          child: Center(
                 ^^^^^^
lib/screens/search/widgets/filters/filter_search_category.dart:69:20: Error: The method 'SingleChildScrollView' isn't defined for the class '_FilderSearchCategoryState'.
 - '_FilderSearchCategoryState' is from 'package:fstore/screens/search/widgets/filters/filter_search_category.dart' ('lib/screens/search/widgets/filters/filter_search_category.dart').
Try correcting the name to the name of an existing method, or defining a method named 'SingleChildScrollView'.
            child: SingleChildScrollView(
                   ^^^^^^^^^^^^^^^^^^^^^
lib/screens/search/widgets/filters/filter_search_category.dart:70:32: Error: The getter 'Axis' isn't defined for the class '_FilderSearchCategoryState'.
 - '_FilderSearchCategoryState' is from 'package:fstore/screens/search/widgets/filters/filter_search_category.dart' ('lib/screens/search/widgets/filters/filter_search_category.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Axis'.
              scrollDirection: Axis.horizontal,
                               ^^^^

Please note that I have a lot of errors more, but I can't show them because of the limited characters here.

Please help!

**Comment by Pascalnhuis** [comment]
![chrome_Avhl08Qkmp](https://user-images.githubusercontent.com/62649032/77532464-31a06880-6e95-11ea-8633-5ba4958c8f2f.png)

**Comment by minhcasi** [comment]
@Pascalnhuis - on Android Studio, did you run open the pubspec.yaml file and select - "Packages get"

https://tppr.me/mukmJ

**Comment by Pascalnhuis** [comment]
Hi! I found the problem. Flutter wasn't installed right. The old version isnt work anymore for me.

Thanks! :)

**Comment by Pascalnhuis** [comment]
Ooh I have removed my license screenshot. I am affraid for stealing licenses by other peoples.

**Comment by minhcasi** [comment]
@Pascalnhuis - thank you for the confirm

Let us know if you have any further issues - very best!
