### ISSUE TITLE
[my-product] - 

### ISSUE THREAD

**Issue by fekrasolution** [inspireui/support#2449]
A problem occurred configuring root project 'android'.

Could not resolve all artifacts for configuration ':classpath'.
Could not resolve com.google.gms:google-services:4.3.2.
Required by:
project :
> Could not resolve com.google.gms:google-services:4.3.2.
> Could not get resource 'https://dl.google.com/dl/android/maven2/com/google/gms/google-services/4.3.2/google-services-4.3.2.pom'.
> Could not GET 'https://dl.google.com/dl/android/maven2/com/google/gms/google-services/4.3.2/google-services-4.3.2.pom'.
> dl.google.com
> Could not resolve com.google.gms:google-services:4.3.2.
> Could not get resource 'https://jcenter.bintray.com/com/google/gms/google-services/4.3.2/google-services-4.3.2.pom'.
> Could not GET 'https://jcenter.bintray.com/com/google/gms/google-services/4.3.2/google-services-4.3.2.pom'.
> jcenter.bintray.com
> Could not resolve com.google.gms:google-services:4.3.2.
> Could not get resource 'http://storage.googleapis.com/r8-releases/raw/com/google/gms/google-services/4.3.2/google-services-4.3.2.pom'.
> Could not GET 'http://storage.googleapis.com/r8-releases/raw/com/google/gms/google-services/4.3.2/google-services-4.3.2.pom'.
> Connect to storage.googleapis.com:80 [storage.googleapis.com/2a00:1450:4006:80a:0:0:0:2010] failed: No route to host (connect failed)

Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

Get more help at https://help.gradle.org

BUILD FAILED in 21s
Finished with error: Gradle task assembleDebug failed with exit code 1

@minhcasi
 
Collaborator
minhcasi commented 16 hours ago
Hi, thank you for the feedback. Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads it's used to verify your proof of purchase?
Sorry for any inconvenience, we will reopen the ticket when it is verified, thank you!

**Comment by minhcasi** [comment]
@fekrasolution 

1. First could i check if you resolve the issue when running "flutter doctor" ?

2. Please make sure you have passed the basic installing from https://flutter.dev/docs/get-started/test-drive 

3. Try to runt the project from Android Studio, update the pubspec and show us screenshot issue

**Comment by fekrasolution** [comment]
![Screen Shot 2020-03-26 at 6 07 01 AM](https://user-images.githubusercontent.com/52893412/77609446-ad97c080-6f28-11ea-8402-11a7cced70a1.png)
![Uploading Screen Shot 2020-03-26 at 6.06.49 AM.png…]()

**Comment by fekrasolution** [comment]
![Screen Shot 2020-03-26 at 6 06 49 AM](https://user-images.githubusercontent.com/52893412/77609519-e172e600-6f28-11ea-9fb9-a7d1afd3a9b5.png)

**Comment by minhcasi** [comment]
@philipvu30 - please help to support for this issue, also note solution to our common issue document

**Comment by philipvu30** [comment]
Hi @fekrasolution ,

Please contact me via Skype: vuthanhtoan30. Thank you

**Comment by Haniel5** [comment]
@philipvu30 please help to note the solution to fix this issue, so that i can update the document with common issues - thank you :)
