### ISSUE TITLE
[FluxStore-woo 1.6.5c] - Affiliate Compatible Error

### ISSUE THREAD

**Issue by peter2411** [inspireui/support#2450]
1. My issue : 
my store contains a affiliate products , my app was using "FluxStore-woo 1.4.3" and it was working fine and the webview was correctly showing the webpage after click add to cart , now when i trying to update the app with fluxstore "FluxStore-woo 1.6.5c" with the same "Server config" when i click on add to cart it's continue to complete purchase via the app !!

Proof of my purchased :

https://prnt.sc/rmxcno

Screenshots :

https://prnt.sc/rmxd4c
https://prnt.sc/rmxdae

Config files : 
[config.zip](https://github.com/inspireui/support/files/4384975/config.zip)

**Comment by philipvu30** [comment]
Hi @peter2411 ,

Would you mind checking your product's affiliate link? Because I have checked the products showed above and they are missing the affiliate url. Thank you.
![image](https://user-images.githubusercontent.com/54442328/77623834-67b41a00-6f73-11ea-8334-0d1983239f40.png)

**Comment by peter2411** [comment]
Hello,
I have checked it and updated the affiliate URL , you can check again and the external URL will show up .. but the problem still exist .


![screen1](https://user-images.githubusercontent.com/53765946/77685882-ca71d980-6fa4-11ea-8a71-8d5e6e346ceb.jpg)

even with default config "mstore.io" External/Affiliate product .

![screen2](https://user-images.githubusercontent.com/53765946/77685967-ef664c80-6fa4-11ea-9287-6852c3282310.jpg)

also in your release app on store "External/Affiliate product is "out of stock" so i can't try the option

**Comment by philipvu30** [comment]
Hi @peter2411 ,

Please replace this file in this path lib/screens/detail/product_variant.dart
[product_variant.zip](https://github.com/inspireui/support/files/4391407/product_variant.zip)
