### ISSUE TITLE
[my-product] - cannot enter purchase code and publish 

### ISSUE THREAD

**Issue by offersdaily** [inspireui/support#2451]
1.Is there any plugin for wordpress,
2. I tried 

InspireUI AUTHOR

about 3 hours ago Flag
you can download on this link – https://apps.apple.com/vn/app/fluxbuilder/id1500753204?mt=12 – thanks

![image](https://user-images.githubusercontent.com/62690257/77620976-79e38780-6f76-11ea-9012-402dd7cef3c8.png)

but unable to publish and keep on loading after submitting code 

---------

1. My issue:

2. Screenshots issues (required):

3. Proof of my purchased (required):

3. Config files (required)

**Comment by minhcasi** [comment]
@offersdaily - could you help to send your purchase key and website to our private email support@inspireui.com - we will check the DB and let you know - thank you!

**Comment by minhcasi** [comment]
moved to email conversation - thanks
