### ISSUE TITLE
[my-product] - 

### ISSUE THREAD

**Issue by macahamed** [inspireui/support#2452]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: how to run in ios simulator

2. Screenshots issues (required):![Screen Shot 2020-03-26 at 3 22 10 PM](https://user-images.githubusercontent.com/62641104/77641614-c1b5df00-6f75-11ea-9648-ca13d6002f9e.png)

3. Proof of my purchased (required):![Screen Shot 2020-03-26 at 3 24 15 PM](https://user-images.githubusercontent.com/62641104/77641721-f45fd780-6f75-11ea-8738-70c594890d19.png)

3. Config files (required)

**Comment by minhcasi** [comment]
@macahamed - pls check the document guide - https://docs.inspireui.com/fluxstore/getting-started/

You can open ios from android studio 

<img width="668" alt="Screen Shot 2020-03-26 at 19 27 08" src="https://user-images.githubusercontent.com/1459805/77646789-ca1f1180-6f97-11ea-8039-0e823db78ba0.png">

**Comment by macahamed** [comment]
if i ask any doubt always send this document? i do use this document only but showing error? again again send this document

**Comment by macahamed** [comment]
![Screen Shot 2020-03-26 at 4 14 01 PM](https://user-images.githubusercontent.com/62641104/77648365-799cb980-6f81-11ea-8808-9815e656ac5c.png)terminal is showing error

**Comment by macahamed** [comment]
i follow your video only, give me the proper solution?????

**Comment by minhcasi** [comment]
@macahamed - please help to read the document more carefully, the error show that you have not set up the flutter Path correctly so that it could not recognize from the script, this is common issue - please check this guide https://flutter.dev/docs/get-started/install/macos#update-your-path 

You can check the result with this script 'flutter -v' - see screenshot https://tppr.me/IZJ35

**Comment by macahamed** [comment]
Please send the video for creating flutter sdk, i didn't understand your document
