### ISSUE TITLE
Unable to verify firebase installation in Android device 

### ISSUE THREAD

**Issue by monikamishra-54** [inspireui/support#2454]
1) Unable to verify firebase installation if i'm skiping this step again error occurred in google sign in.
2) Screenshot issue.
3) Proof of my purchase.
Thanks in advance
![Screenshot_1](https://user-images.githubusercontent.com/58734760/77646618-e8324500-6f8a-11ea-9607-d7ee54c620c1.png)
![Screenshot_2](https://user-images.githubusercontent.com/58734760/77646724-1a43a700-6f8b-11ea-8bc8-04b1605a71cb.png)
![image_2020_03_26T12_28_04_889Z](https://user-images.githubusercontent.com/58734760/77646972-9ccc6680-6f8b-11ea-96dd-b6d75f41def6.png)

**Comment by minhcasi** [comment]
@monikamishra-54 - would you mind to take the proof of purchase include your username - thank you!

**Comment by monikamishra-54** [comment]
username: royalsoni
![image](https://user-images.githubusercontent.com/58734760/77722959-178d9400-7015-11ea-8b91-41f02b175a1e.png)

**Comment by minhcasi** [comment]
@monikamishra-54 - could I check if you downloaded the google service file to the project?

Please help to check more on this guide https://docs.inspireui.com/fluxstore/sign-in/

**Comment by monikamishra-54** [comment]
![Screenshot_json](https://user-images.githubusercontent.com/58734760/78234772-444e1980-74f5-11ea-9be7-c3130472fbb0.png)

**Comment by tjain90** [comment]
Hi Team, I am also facing similar issue.

**Comment by monikamishra-54** [comment]
@tjain90  I solved this issue by changing in build.gradle file
I think by default app is building in released mode, so i commented the following code

/* signingConfigs {
        release {
            if (System.getenv()["CI"]) { // CI=true is exported by Codemagic
                storeFile file(System.getenv()["FCI_BUILD_DIR"] + "/key.jks")
                storePassword System.getenv()["FCI_KEYSTORE_PASSWORD"]
                keyAlias System.getenv()["FCI_KEY_ALIAS"]
                keyPassword System.getenv()["FCI_KEY_PASSWORD"]
            } else {
                 keyAlias keystorePropertiesRelease['keyAlias']
                keyPassword keystorePropertiesRelease['keyPassword']
                storeFile file(keystorePropertiesRelease['storeFile'])
                storePassword keystorePropertiesRelease['storePassword']
            }
        }
        
        debug {
            keyAlias keystorePropertiesDebug['keyAlias']
            keyPassword keystorePropertiesDebug['keyPassword']
            storeFile file(keystorePropertiesDebug['storeFile'])
            storePassword keystorePropertiesDebug['storePassword']
        }
    }*/

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
           // signingConfig signingConfigs.release
         // change release to debug
            signingConfig signingConfigs.debug
        }

        /*debug {
            signingConfig signingConfigs.debug
        }*/
    }

Unstall and re-install again.  Hope it works for you
