### ISSUE TITLE
[Fluxstore-mv] - Failed assertion: boolean expression must not be null

### ISSUE THREAD

**Issue by kenngigz** [inspireui/support#2456]
Hi! I downloaded the updated version but have an error. I can't open a store, I get the above error. Attached are screenshots of the error and config files
![purchase](https://user-images.githubusercontent.com/57593885/77652141-dcd91c80-6f7e-11ea-8571-d42b85140662.png)
![store error](https://user-images.githubusercontent.com/57593885/77652147-de0a4980-6f7e-11ea-9779-1747636fd5b1.JPG)
![vendor_route dart](https://user-images.githubusercontent.com/57593885/77652150-df3b7680-6f7e-11ea-8efa-345e36633c70.JPG)

**Comment by kenngigz** [comment]
![Screenshot_2020-03-26-12-51-49](https://user-images.githubusercontent.com/57593885/77652931-19594800-6f80-11ea-9d82-1f61d2897a89.png)

**Comment by HumerCode** [comment]
Same here..cant visit vendor store-

**Comment by minhtruong315** [comment]
@kenngigz can u send me config files

**Comment by kenngigz** [comment]
[config.dart.txt](https://github.com/inspireui/support/files/4392971/config.dart.txt)

**Comment by minhtruong315** [comment]
let me check

**Comment by minhtruong315** [comment]
@kenngigz replace vendor/store_detail/store_detail_screen.dart file then try again
[store_detail_screen.dart.zip](https://github.com/inspireui/support/files/4406698/store_detail_screen.dart.zip)

**Comment by kenngigz** [comment]
Thank you! It worked
