### ISSUE TITLE
[my-product] - Firebase Notification Problem

### ISSUE THREAD

**Issue by emresutuna** [inspireui/support#2457]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:

2. Screenshots issues (required):

3. Proof of my purchased (required):

3. Config files (required)

**Comment by emresutuna** [comment]
https://docs.inspireui.com/fluxstore/firebase/ I tried this documentation but didn't working

**Comment by minhcasi** [comment]
Hi, thank you for the feedback. Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads it's used to verify your proof of purchase? 
Sorry for any inconvenience, we will reopen the ticket when it is verified, thank you!

**Comment by emresutuna** [comment]
![WhatsApp Image 2020-03-12 at 10 50 34](https://user-images.githubusercontent.com/35627584/77747222-57617500-702f-11ea-8755-953c1ff4a4d2.jpeg)

**Comment by minhcasi** [comment]
@emresutuna - could you explain more about the issue?

The push notification will only work on the real device, on the simulator it will not work

**Comment by TqwaAlTurki** [comment]
> @emresutuna - could you explain more about the issue?
> 
> The push notification will only work on the real device, on the simulator it will not work

I Tried to activate push notification via OneSignal and it did work on a simulator, now i tried to activate notification via Firebase i followed the instruction in the documentation and still nothing happened. PS: i'm using android simulator.
