### ISSUE TITLE
Fluxstore MultiVendor

### ISSUE THREAD

**Issue by aishema2000** [inspireui/support#2458]
1. My issue:

I have connected fluxstore to my woocommerce website but and changed the categories ID in the json file to match my categories but the app shows no product (Please note there is only one vendor for the moment).
But if I use Fluxbuilder, everything seems ok!! FluxBuilder list my products very nice, But unfortunately, It does not allow me to download the jSon file.

2. Screenshots issues (required):

Category listing: https://ibb.co/vYMB3Z5

Fluxbuilder publish issue: https://ibb.co/qYdNwQg

3. Proof of my purchased (required):
https://ibb.co/dW6z3Zh

3. Config files (required)

[config_files.zip](https://github.com/inspireui/support/files/4388237/config_files.zip)

**Comment by minhcasi** [comment]
@aishema2000 - note with investigating

@vumanhsn97 - this issue could be related to https://github.com/inspireui/support/issues/2427

**Comment by aishema2000** [comment]
Before asking support I saw this to ticket your are mentioning I downloaded the given files but they were not working giving several errors. Please, What can I do to have my app working?????

**Comment by aishema2000** [comment]
I am going to uninstall everything and re-install from scratch as per documentation then I will tell you the output. Thanks.

**Comment by aishema2000** [comment]
For my website theme, I also use same theme as http://dokan.mstore.io/ should I activate this theme before installing fluxstore?

**Comment by aishema2000** [comment]
CAn you please guide me how to install Dokan and integrate with fluxstore multivendor? Should I by dokan pro? Dokan free plugin can work? Please provide guidance. Thank you

**Comment by vumanhsn97** [comment]
@aishema2000 You can follow this guide: https://docs.inspireui.com/fluxstore/multi-vendor/
using dokan free plugin

**Comment by aishema2000** [comment]
I am configuring Dokan, How do I use this example files lib/examples/dokan? It is not clear on the documentation, Do I have to copy them and place them under common and config folders? I am a bit confused here. Thanks

**Comment by vumanhsn97** [comment]
@aishema2000 You can follow this document https://docs.inspireui.com/fluxstore/home-layout/

**Comment by aishema2000** [comment]
Up to now I can not display products using both dokan or wcfm. All plugins are installed as per documentation. Also this screenshot shiws the error I get when I open the blog post
![error11](https://user-images.githubusercontent.com/15066381/77819168-5ee15680-70e1-11ea-9e7c-991bbbcedb1c.PNG)

**Comment by aishema2000** [comment]
I am still struggling to list the products using wcfm, but still in vain. I highly request your support to have my app running, Attached is the error message I am getting using Visual Code. PLEASE HELP!
![jwt error](https://user-images.githubusercontent.com/15066381/77821087-141b0b00-70f0-11ea-92e8-4e520161f4de.PNG)

**Comment by aishema2000** [comment]
> I am still struggling to list the products using wcfm, but still in vain. I highly request your support to have my app running, Attached is the error message I am getting using Visual Code. PLEASE HELP!
> ![jwt error](https://user-images.githubusercontent.com/15066381/77821087-141b0b00-70f0-11ea-92e8-4e520161f4de.PNG)

SOLUTION FOUND: the server url needed to use https instead of http.

**Comment by aishema2000** [comment]
> Up to now I can not display products using both dokan or wcfm. All plugins are installed as per documentation. Also this screenshot shiws the error I get when I open the blog post
> ![error11](https://user-images.githubusercontent.com/15066381/77819168-5ee15680-70e1-11ea-9e7c-991bbbcedb1c.PNG)

SOLUTION FOUND: The post must have a featured image otherwise it will give the error.

**Comment by minhcasi** [comment]
@aishema2000 - thank you for your note from the solution - we will update this document

**Comment by minhcasi** [comment]
@Haniel5
