### ISSUE TITLE
[FluxStore-WooCommerce] Variable 

### ISSUE THREAD

**Issue by amolsaini** [inspireui/support#2460]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: Please let me know how to fix this 

 ════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during layout:
A RenderFlex overflowed by 177 pixels on the bottom.

The relevant error-causing widget was: 
  Column file:///C:/scr/source/lib/widgets/product/product_variant.dart:135:18
The overflowing RenderFlex has an orientation of Axis.vertical.
The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and black striped pattern. This is usually caused by the contents being too big for the RenderFlex.

Consider applying a flex factor (e.g. using an Expanded widget) to force the children of the RenderFlex to fit within the available space instead of being sized to their natural size.
This is considered an error condition because it indicates that there is content that cannot be seen. If the content is legitimately bigger than the available space, consider clipping it with a ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex, like a ListView.

The specific RenderFlex in question is: RenderFlex#09ebb relayoutBoundary=up4 OVERFLOWING
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=411.4, 0.0<=h<=384.4)
...  size: Size(411.4, 384.4)
...  direction: vertical
...  mainAxisAlignment: start
...  mainAxisSize: min
...  crossAxisAlignment: center
...  verticalDirection: down
◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤

2. Screenshots issues (required):   
![issue](https://user-images.githubusercontent.com/61465898/77678186-c949a800-6fb6-11ea-8313-fa12bde74949.jpg)

3. Proof of my purchased (required):  
![purchase](https://user-images.githubusercontent.com/61465898/77678298-f302cf00-6fb6-11ea-930f-597a6c8c7aa2.jpg)

3. Config files (required)   product_variation.dart

import 'package:flutter/material.dart';

import '../../common/constants.dart';
import '../../common/styles.dart';
import '../../common/tools.dart';
import '../../generated/l10n.dart';

enum VariantLayout { inline, dropdown }

class BasicSelection extends StatelessWidget {
  final List<String> options;
  final String value;
  final String title;
  final String type;
  final Function onChanged;
  final VariantLayout layout;

  BasicSelection(
      {@required this.options, @required this.title, @required this.value, this.type, this.layout, this.onChanged});

  @override
  Widget build(BuildContext context) {
    Color primaryColor = Theme.of(context).primaryColor;

    if (type == "option") {
      return OptionSelection(
        options: options,
        value: value,
        title: title,
        onChanged: onChanged,
      );
    }

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      mainAxisSize: MainAxisSize.max,
      mainAxisAlignment: MainAxisAlignment.start,
      children: <Widget>[
        Row(
          children: <Widget>[
            Expanded(
              child: Padding(
                child: Text(
                  "${title[0].toUpperCase()}${title.substring(1)}",
                  style: TextStyle(fontWeight: FontWeight.bold, fontSize: 18),
                ),
                padding: const EdgeInsets.only(bottom: 10),
              ),
            ),
          ],
        ),
        Wrap(
          spacing: 0.0,
          runSpacing: 12.0,
          children: <Widget>[
            for (var item in options)
              Container(
                //height: type == "color" ? 26 : 30,
                child: AnimatedContainer(
                  duration: Duration(milliseconds: 300),
                  curve: Curves.easeIn,
                  margin: EdgeInsets.only(right: 15.0),
                  decoration: type == "color"
                      ? BoxDecoration(
                          color: item == value
                              ? HexColor(kColorNameToHex[item.toLowerCase()] ?? "#ffffff")
                              : HexColor(kColorNameToHex[item.toLowerCase()] ?? "#ffffff").withOpacity(0.6),
                          borderRadius: BorderRadius.circular(25),
                          border: Border.all(
                            width: 1.0,
                            color: Theme.of(context).accentColor.withOpacity(0.3),
                          ),
                        )
                      : BoxDecoration(
                          color: item == value ? primaryColor : Colors.transparent,
                          borderRadius: BorderRadius.circular(5.0),
                          border: Border.all(
                            color: Theme.of(context).accentColor.withOpacity(0.3),
                          ),
                        ),
                  child: InkWell(
                    splashColor: Colors.transparent,
                    highlightColor: Colors.transparent,
                    onTap: () {
                      onChanged(item);
                    },
                    child: type == "color"
                        ? SizedBox(
                            height: 25,
                            width: 25,
                            child: item == value
                                ? Icon(
                                    Icons.check,
                                    color: Colors.white,
                                    size: 16,
                                  )
                                : Container(),
                          )
                        : Container(
                            padding: const EdgeInsets.only(left: 10.0, right: 10.0),
                            child: Padding(
                              child: Text(
                                item,
                                style: TextStyle(
                                  color: item == value ? Colors.white : Theme.of(context).accentColor,
                                  fontSize: 14,
                                ),
                              ),
                              padding: const EdgeInsets.only(top: 5, bottom: 5),
                            ),
                          ),
                  ),
                ),
              )
          ],
        ),
      ],
    );
  }
}

class OptionSelection extends StatelessWidget {
  final List<String> options;
  final String value;
  final String title;
  final Function onChanged;
  final VariantLayout layout;

  OptionSelection({@required this.options, @required this.value, this.title, this.layout, this.onChanged});

  showOptions(context) {
    showModalBottomSheet(
        context: context,
        builder: (BuildContext context) {
          return Column(
            mainAxisSize: MainAxisSize.min,
            children: <Widget>[
              for (final option in options)
                ListTile(
                    onTap: () {
                      onChanged(option);
                      Navigator.pop(context);
                    },
                    title: Text(option, textAlign: TextAlign.center)),
              Container(
                height: 1,
                decoration: BoxDecoration(color: kGrey200),
              ),
              ListTile(
                title: Text(
                  S.of(context).selectTheSize,
                  textAlign: TextAlign.center,
                ),
              ),
            ],
          );
        });
  }

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () => showOptions(context),
      child: Container(
        height: 42,
        child: Padding(
          padding: const EdgeInsets.symmetric(horizontal: 2.0),
          child: Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              Expanded(
                child: Text("${title[0].toUpperCase()}${title.substring(1)}",
                    style: TextStyle(fontWeight: FontWeight.bold, fontSize: 18)),
              ),
              Text(
                value,
                style: TextStyle(
                  color: Theme.of(context).accentColor,
                  fontSize: 13,
                ),
              ),
              SizedBox(width: 5),
              Icon(Icons.keyboard_arrow_down, size: 16, color: kGrey600)
            ],
          ),
        ),
      ),
    );
  }
}

class ColorSelection extends StatelessWidget {
  final List<String> options;
  final String value;
  final Function onChanged;
  final VariantLayout layout;

  ColorSelection({@required this.options, @required this.value, this.layout, this.onChanged});

  @override
  Widget build(BuildContext context) {
    if (layout == VariantLayout.dropdown) {
      return GestureDetector(
        onTap: () => showOptions(context),
        child: Container(
          decoration: BoxDecoration(border: Border.all(width: 1.0, color: kGrey200)),
          height: 42,
          child: Padding(
            padding: const EdgeInsets.symmetric(horizontal: 10.0),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
                Expanded(
                  child: Text(S.of(context).color, style: TextStyle(fontWeight: FontWeight.bold, fontSize: 14)),
                ),
                Container(
                    height: 20,
                    width: 20,
                    decoration: BoxDecoration(
                        color: kColorNameToHex[value.toLowerCase()] != null
                            ? HexColor(kColorNameToHex[value.toLowerCase()])
                            : Colors.transparent)),
                SizedBox(width: 5),
                Icon(Icons.keyboard_arrow_down, size: 16, color: kGrey600)
              ],
            ),
          ),
        ),
      );
    }

    return Container(
      height: 25,
      child: SingleChildScrollView(
        scrollDirection: Axis.horizontal,
        child: Row(
          children: <Widget>[
            Center(
              child: Text(
                S.of(context).color,
                style: TextStyle(fontWeight: FontWeight.bold, fontSize: 14),
              ),
            ),
            SizedBox(
              width: 15.0,
            ),
            for (var item in options)
              AnimatedContainer(
                  duration: Duration(milliseconds: 300),
                  curve: Curves.easeIn,
                  margin: EdgeInsets.only(right: 20.0),
                  decoration: BoxDecoration(
                    color: item == value
                        ? HexColor(kColorNameToHex[item.toLowerCase()])
                        : HexColor(kColorNameToHex[item.toLowerCase()]).withOpacity(0.6),
                    borderRadius: BorderRadius.circular(20.0),
                    border: Border.all(width: 1.0, color: Theme.of(context).accentColor.withOpacity(0.5)),
                  ),
                  child: InkWell(
                    splashColor: Colors.transparent,
                    highlightColor: Colors.transparent,
                    onTap: () {
                      onChanged(item);
                    },
                    child: SizedBox(
                      height: 25,
                      width: 25,
                      child: item == value
                          ? Icon(
                              Icons.check,
                              color: Colors.white,
                              size: 16,
                            )
                          : Container(),
                    ),
                  )),
          ],
        ),
      ),
    );
  }

  void showOptions(context) {
    showModalBottomSheet(
        context: context,
        builder: (BuildContext context) {
          return Column(
            mainAxisSize: MainAxisSize.min,
            children: <Widget>[
              for (final option in options)
                ListTile(
                  onTap: () {
                    onChanged(option);
                    Navigator.pop(context);
                  },
                  title: Center(
                    child: Container(
                      width: 30,
                      height: 30,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(3.0),
                        border: Border.all(width: 1.0, color: Theme.of(context).accentColor),
                        color: HexColor(kColorNameToHex[option.toLowerCase()]),
                      ),
                    ),
                  ),
                ),
              Container(
                height: 1,
                decoration: BoxDecoration(color: kGrey200),
              ),
              ListTile(
                title: Text(
                  S.of(context).selectTheColor,
                  textAlign: TextAlign.center,
                ),
              ),
            ],
          );
        });
  }
}

class QuantitySelection extends StatelessWidget {
  final int limitSelectQuantity;
  final int value;
  final double width;
  final double height;
  final Function onChanged;
  final Color color;

  QuantitySelection(
      {@required this.value,
      this.width = 80.0,
      this.height = 42.0,
      this.limitSelectQuantity = 100,
      @required this.color,
      this.onChanged});

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () {
        if (onChanged != null) {
          showOptions(context);
        }
      },
      child: Container(
        decoration: BoxDecoration(border: Border.all(width: 1.0, color: kGrey200)),
        height: height,
        width: width,
        child: Padding(
          padding: const EdgeInsets.symmetric(horizontal: 10.0),
          child: Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              Expanded(
                child: Center(
                  child: Text(
                    value.toString(),
                    style: TextStyle(fontSize: 14, color: color),
                  ),
                ),
              ),
              Icon(Icons.keyboard_arrow_down, size: 16, color: kGrey600)
            ],
          ),
        ),
      ),
    );
  }

  void showOptions(context) {
    showModalBottomSheet(
        context: context,
        builder: (BuildContext context) {
          return Column(
            mainAxisSize: MainAxisSize.min,
            children: <Widget>[
              Expanded(
                child: SingleChildScrollView(
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    children: <Widget>[
                      for (int option = 1; option <= limitSelectQuantity; option++)
                        ListTile(
                            onTap: () {
                              onChanged(option);
                              Navigator.pop(context);
                            },
                            title: Text(
                              option.toString(),
                              textAlign: TextAlign.center,
                            )),
                    ],
                  ),
                ),
              ),
              Container(
                height: 1,
                decoration: BoxDecoration(color: kGrey200),
              ),
              ListTile(
                title: Text(
                  S.of(context).selectTheQuantity,
                  textAlign: TextAlign.center,
                ),
              ),
            ],
          );
        });
  }
}

**Comment by philipvu30** [comment]
Hi @amolsaini ,

Please send the files: config.dart and all the config_xxx.json to this email: toan@inspireui.com. Thank you

**Comment by amolsaini** [comment]
Hi philipvu30 

Email Send

Regards

**Comment by amolsaini** [comment]
hi philipvu30

Any Update

Regards'
Amol Saini

**Comment by philipvu30** [comment]
Hi @amolsaini ,

We are investigating this issue. I'll let you know as soon as this issue has been fixed. Thank you

**Comment by amolsaini** [comment]
Hi philipvu30

No Problem Take your time

Regards'
Amol

**Comment by philipvu30** [comment]
Hi @amolsaini ,

It seems you are using the older version. Please update your app to the latest version and see if your issue still persist. Thank you

**Comment by amolsaini** [comment]
hi

I am sure i am using version 1.6.5c version.

Please let me know what to do now ?

Thanks
Regards
Amol Saini

**Comment by amolsaini** [comment]
Hi

I can confirm that i have latest 1.6.5c version and i tried a new build again and the issue is there.

Thanks
Regards'
Amol Saini

**Comment by philipvu30** [comment]
Hi @amolsaini ,

My apologies, new version will be updated in a few days. We need to give it a final test before releasing. 
Also I have tested your config files with new version and no issue was found.

**Comment by amolsaini** [comment]
Hi philipvu30

Thank you for the update. No problem i will wait. Its going to be long journey for me now.

Regards'
Amol Saini

**Comment by amolsaini** [comment]
Hi 

I have share something on email. Please do check it.

Thanks
Amol Saini

**Comment by philipvu30** [comment]
Hi @amolsaini ,

I can confirm that issue has been fixed. Thank you for your concern.

**Comment by philipvu30** [comment]
Hi @amolsaini ,

I sent you the new source code via email. Please check and confirm if it works. Thanks

**Comment by amolsaini** [comment]
Hi the issue is still not fixed

**Comment by amolsaini** [comment]
Hello 

Please don't close the case. Without confirmation from my side.

Thank You

**Comment by amolsaini** [comment]
![error](https://user-images.githubusercontent.com/61465898/78332306-6bfcba80-75a5-11ea-8f92-3e9616161a8c.jpg)

**Comment by amolsaini** [comment]
![error2](https://user-images.githubusercontent.com/61465898/78332410-99496880-75a5-11ea-8b4f-b5b8d5d2601e.jpg)

**Comment by philipvu30** [comment]
Hi @amolsaini ,

Sorry for closing the case without your confirmation. We usually close the comment after 2 days with no response from user. 

Please contact me via Skype: vuthanhtoan30. I'll help you through TeamViewer. Thanks
