### ISSUE TITLE
[FluxNews] - iframe isn't displaying correctly. I have an embedded video

### ISSUE THREAD

**Issue by davidsondoodle** [inspireui/support#2461]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
When I put an iframe into my wordpress site, it displays properly on the site, but not in the app. I've changed to a completely fresh install, so I was able to get this to at least make a connection to the wordpress.
http://davidsondesigner.com/StateChamps/

2. Screenshots issues (required):
<img width="343" alt="image" src="https://user-images.githubusercontent.com/50459114/77680029-c07eb500-6f69-11ea-9c82-cd325489cd27.png">
<img width="340" alt="image" src="https://user-images.githubusercontent.com/50459114/77680396-43077480-6f6a-11ea-8588-dab208866a59.png">

3. Proof of my purchased (required):
<img width="1143" alt="image" src="https://user-images.githubusercontent.com/50459114/77680634-9ed1fd80-6f6a-11ea-9e84-2a539b9311b4.png">

3. Config files (required)
[ProblemConfigFiles.zip](https://github.com/inspireui/support/files/4389019/ProblemConfigFiles.zip)

**Comment by dttrung26** [comment]
Morning @davidsondoodle ,
could you please leave me your skype id. I'll reach you for further assistance. 
Nice day!

**Comment by davidsondoodle** [comment]
My Skype id is davidsondoodle@gmail.com

**Comment by dttrung26** [comment]
Support via skype.
