### ISSUE TITLE
[ms-store] - Additional fields opencart

### ISSUE THREAD

**Issue by jaroslav009** [inspireui/support#2462]
1. How i can create customer in opencart with additional fields through api - AppConfig.Opencart.url + "/index.php?route=extension/mstore/account/register"

![Знімок екрана 2020-03-26 о 20 30 41](https://user-images.githubusercontent.com/33982583/77683441-0d31b280-6fa1-11ea-93c3-be3e65ba80ae.png)

**Comment by minhcasi** [comment]
Hi, thank you for the feedback. Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads it's used to verify your proof of purchase? 
Sorry for any inconvenience, we will reopen the ticket when it is verified, thank you!

**Comment by jaroslav009** [comment]
![Знімок екрана 2020-03-27 о 09 46 22](https://user-images.githubusercontent.com/33982583/77733619-e068b400-700f-11ea-85a8-c83af0d51c92.png)

**Comment by jaroslav009** [comment]
can you help me?

**Comment by minhcasi** [comment]
@minhtruong315 - could you suggestion solution for this customize

**Comment by minhtruong315** [comment]
@jaroslav009 it need to edit code for MStore extension as well.

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
