### ISSUE TITLE
[Fluxstore Multi Vendor] - Build failed after Xcode update 

### ISSUE THREAD

**Issue by HassanChmsdn** [inspireui/support#2463]
---------

1. My issue:
After updating Xcode I am not able to build my app again

2. Screenshots issues (required):
![Screenshot 2020-03-26 at 21 28 56](https://user-images.githubusercontent.com/921709/77693553-d3fd4080-6fa8-11ea-8bc6-474f7591471e.png)

3. Proof of my purchased (required):
Item purchased code: d1141eb5-edf3-4bcc-844b-112677d6f489
Date : 2019-11-21 21:15:50 UTC

3. Config files (required)

**Comment by minhcasi** [comment]
@HassanChmsdn - this is the cache issue, please check this solution https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

**Comment by HassanChmsdn** [comment]
> @HassanChmsdn - this is the cache issue, please check this solution https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/0aeb324a3445c618a67c0140da8216d28af304fa/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f696d616765732f6d6f64756c65732f67697374732f676973742d6f672d696d6167652e706e67"><img alt="" height="14" src="https://camo.githubusercontent.com/4908d9947135e4536ef61d61512ee575f869bf6f/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e2e69636f"> Gist**[How to clear Flutter's Build cache?](https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1)**How to clear Flutter's Build cache? GitHub Gist: instantly share code, notes, and snippets.

**Still failing to build after running flutter clean, deleting the pubspec.lock and rebuilding**

`Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
 
Running pod install...                                             29.8s
Running Xcode build...                                                  
                                                   
Xcode build done.                                           32.6s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    /Users/hassanchamseddine/Documents/github/flutter/.pub-cache/hosted/pub.dartlang.org/razorpay_flut
    ter-1.1.2/ios/Classes/RazorpayDelegate.swift:4:42: error:
    'RazorpayPaymentCompletionProtocolWithData' is unavailable: cannot find Swift declaration for this
    protocol
    public class RazorpayDelegate: NSObject, RazorpayPaymentCompletionProtocolWithData,
    ExternalWalletSelectionProtocol {
                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Razorpay.RazorpayPaymentCompletionProtocolWithData:2:17: note:
    'RazorpayPaymentCompletionProtocolWithData' has been explicitly marked unavailable here
    public protocol RazorpayPaymentCompletionProtocolWithData {
                    ^
    /Users/hassanchamseddine/Documents/github/flutter/.pub-cache/hosted/pub.dartlang.org/razorpay_flut
    ter-1.1.2/ios/Classes/RazorpayDelegate.swift:4:85: error: 'ExternalWalletSelectionProtocol' is
    unavailable: cannot find Swift declaration for this protocol
    public class RazorpayDelegate: NSObject, RazorpayPaymentCompletionProtocolWithData,
    ExternalWalletSelectionProtocol {
                                                                                        ^~~~~~~~~~~~~~
                                                                                        ~~~~~~~~~~~~~~
                                                                                        ~~~
    Razorpay.ExternalWalletSelectionProtocol:2:17: note: 'ExternalWalletSelectionProtocol' has been
    explicitly marked unavailable here
    public protocol ExternalWalletSelectionProtocol {
                    ^
    /Users/hassanchamseddine/Documents/github/flutter/.pub-cache/hosted/pub.dartlang.org/razorpay_flut
    ter-1.1.2/ios/Classes/RazorpayDelegate.swift:57:24: error: 'Razorpay' is unavailable: cannot find
    Swift declaration for this class
            let razorpay = Razorpay.initWithKey(key ?? "", andDelegateWithData: self)
                           ^~~~~~~~
    Razorpay.Razorpay:2:14: note: 'Razorpay' has been explicitly marked unavailable here
    public class Razorpay : NSObject {
                 ^
    /Users/hassanchamseddine/Documents/github/flutter/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0
    .5.0+3/ios/Classes/RateMyAppPlugin.m:15:30: warning: 'requestReview' is only available on iOS 10.3
    or newer [-Wunguarded-availability]
        [SKStoreReviewController requestReview];
                                 ^~~~~~~~~~~~~~
    In module 'StoreKit' imported from
    /Users/hassanchamseddine/Documents/github/flutter/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0
    .5.0+3/ios/Classes/RateMyAppPlugin.m:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhon
    eSimulator13.4.sdk/System/Library/Frameworks/StoreKit.framework/Headers/SKStoreReviewController.h:
    22:1: note: 'requestReview' has been marked as being introduced in iOS 10.3 here, but the
    deployment target is iOS 8.0.0
    + (void)requestReview API_AVAILABLE(ios(10.3), macos(10.14)) API_UNAVAILABLE(watchos)
    __TVOS_PROHIBITED;
    ^
    /Users/hassanchamseddine/Documents/github/flutter/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0
    .5.0+3/ios/Classes/RateMyAppPlugin.m:15:30: note: enclose 'requestReview' in an @available check
    to silence this warning
        [SKStoreReviewController requestReview];
                                 ^~~~~~~~~~~~~~
    /Users/hassanchamseddine/Documents/github/flutter/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0
    .5.0+3/ios/Classes/RateMyAppPlugin.m:15:6: warning: 'SKStoreReviewController' is only available on
    iOS 10.3 or newer [-Wunguarded-availability]
        [SKStoreReviewController requestReview];
         ^~~~~~~~~~~~~~~~~~~~~~~
    In module 'StoreKit' imported from
    /Users/hassanchamseddine/Documents/github/flutter/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0
    .5.0+3/ios/Classes/RateMyAppPlugin.m:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhon
    eSimulator13.4.sdk/System/Library/Frameworks/StoreKit.framework/Headers/SKStoreReviewController.h:
    14:110: note: 'SKStoreReviewController' has been marked as being introduced in iOS 10.3 here, but
    the deployment target is iOS 8.0.0
    SK_EXTERN_CLASS API_AVAILABLE(ios(10.3), macos(10.14)) API_UNAVAILABLE(watchos) __TVOS_PROHIBITED
    @interface SKStoreReviewController : NSObject
                                                                                                                 ^
    /Users/hassanchamseddine/Documents/github/flutter/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0
    .5.0+3/ios/Classes/RateMyAppPlugin.m:15:6: note: enclose 'SKStoreReviewController' in an
    @available check to silence this warning
        [SKStoreReviewController requestReview];
         ^~~~~~~~~~~~~~~~~~~~~~~
    2 warnings generated.
    Command CompileSwift failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
    warning: Mapping architecture armv7 to i386. Ensure that this target's Architectures and Valid
    Architectures build settings are configured correctly for the iOS Simulator platform. (in target
    'image_picker' from project 'Pods')
    warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid
    Architectures build settings are configured correctly for the iOS Simulator platform. (in target
    'image_picker' from project 'Pods')

Could not build the application for the simulator.
Error launching application on iPhone 11 Pro Max.`

**Comment by taryaalo** [comment]
even me i got the same issue i try with Xcode and Android studio i do every thing but i can't make it work

**Comment by minhcasi** [comment]
@taryaalo - please check solution from https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

@HassanChmsdn - thank you for sharing your solution

**Comment by HassanChmsdn** [comment]
@minhcasi the extra command was only related to the proposed solution of cleaning flutter cache, but for this issue it was still the same.

**What I did to make it work**:
I had to downgrade Xcode from 11.14 to 11.13.1 following this link:
https://medium.com/@tseboho/how-to-downgrade-xcode-4359df5158d5

I guess its an issue in flutter or some dependencies incompatibility with the new Xcode version.
