### ISSUE TITLE
[FluxNews] - I have many things that need clarification

### ISSUE THREAD

**Issue by haidarsalim** [inspireui/support#2466]
1-
![11111](https://user-images.githubusercontent.com/54249914/77753678-09eb0500-703b-11ea-8ed4-fcc36ab30c34.JPG)
 The first problem is customizing the home page
I would like to view this category how to do it
http://baytaltatbiqat.com/category/ios/
http://baytaltatbiqat.com/category/android/

2-
Open links on the external browser

3-
![22222](https://user-images.githubusercontent.com/54249914/77753961-7f56d580-703b-11ea-94f5-ebc3105ff2bd.JPG)
Where can I find these words to modify them?

4-
Show menu button

5-
![444](https://user-images.githubusercontent.com/54249914/77754598-a8c43100-703c-11ea-9e1e-c18f6f9d5cfb.JPG)
Can you change the category to post_tag ?
How do I add additional buttons such as the Contact Us page

-----

![3333](https://user-images.githubusercontent.com/54249914/77755166-bd54f900-703d-11ea-98c9-5f56f90e7227.JPG)

**Comment by minhcasi** [comment]
@haidarsalim 

1. fist you need to get the ID of these categories and change the config.json file from the common folder - https://docs.inspireui.com/fluxnews/customization/

2. fix on next release

3. please check this guide - https://docs.inspireui.com/fluxnews/multi-language/ - you can also use the Inspector tool for customize - https://www.youtube.com/watch?v=JIcmJNT9DNI&t=809s

4. not sure what you mean?

5. This Drawer could be changed from the tabbar.dart -  the Tag menu feature is not available

Let us know if you have any questions, thank you!

**Comment by dttrung26** [comment]
@haidarsalim
Please kindly confirm your issue state and feel free to reopen this ticket if you still experience this issue again.
