### ISSUE TITLE
Pods folder is missing BeoNews.3.0.6

### ISSUE THREAD

**Issue by rxlp** [inspireui/support#2467]
Pods folder is missing on  BeoNews.3.0.6 

![Schermata 2020-03-27 alle 13 54 47](https://user-images.githubusercontent.com/50889285/77758065-a230bc00-7032-11ea-85d2-1977d7cd9f02.png)

**Comment by minhcasi** [comment]
Hi, thank you for the feedback. Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads it's used to verify your proof of purchase? 
Sorry for any inconvenience, we will reopen the ticket when it is verified, thank you!

**Comment by rxlp** [comment]
Item Purchase Code:
2a15b7b9-89be-4b20-ad85-db5f8e9791cd

**Comment by rxlp** [comment]
nervemind
