### ISSUE TITLE
[FluxStore] Failed to build iOS app RazorPay Issue

### ISSUE THREAD

**Issue by taryaalo** [inspireui/support#2468]
1. My issue:
i can't build iOS thy get me an issue with RazorPay, the android version is work fine but the iOS can't run , even i try with new mac and fresh installation and withe you clean code without any editing. and i try run with AndroidS ,Xcode and CM sam issue

2. Screenshots issues (required):

![Screen Shot 2020-03-27 at 3 08 18 PM](https://user-images.githubusercontent.com/26363734/77759430-62230680-703d-11ea-8e24-b92b4ba030bb.png)
![Screen Shot 2020-03-27 at 3 10 24 PM](https://user-images.githubusercontent.com/26363734/77759439-67805100-703d-11ea-9514-b4faaacde9c7.png)
![Uploading Screen Shot 2020-03-27 at 3.12.02 PM.png…]()

3. Proof of my purchased (required):
![Screen Shot 2020-03-27 at 3 00 43 PM](https://user-images.githubusercontent.com/26363734/77759499-75ce6d00-703d-11ea-8504-7b3ab2c21f90.png)

3. Config files (required)

**Comment by ridingthespine** [comment]
Same issue here.  Trying to remove Razorpay altogether

**Comment by ridingthespine** [comment]
Builds fine when I remove Razorpay altogether.
Also have to switch to flutter master b/c I can't get it to work using the flutter stable version

**Comment by taryaalo** [comment]
@ridingthespine i already switch to flutter master, and i will now tray to remove Razorpay . thanks bro for your help

**Comment by minhtruong315** [comment]
@taryaalo you can try to remove ios/Pods folder and ios/Podfile, ios/Podfile.lock file then run again

**Comment by taryaalo** [comment]
thanks, i did it its work but i now stack on this error 
Command PhaseScriptExecution failed with a nonzero exit code
![Screen Shot 2020-03-28 at 5 01 48 PM](https://user-images.githubusercontent.com/26363734/77826066-e6e15380-7115-11ea-85b3-b154ae18cfbb.png)

**Comment by minhtruong315** [comment]
@taryaalo I will check

**Comment by taryaalo** [comment]
i remove the RazorPay i do't need it & remove ios/Pods folder and ios/Podfile, ios/Podfile.lock file then i run it again and its build but show me only white page nothing is loading ,

**Comment by minhcasi** [comment]
@taryaalo - please check this XCode migration you are using latest XCode 11.4 - https://flutter.dev/docs/development/ios-project-migration

the Razorpay issue is having this issue "https://github.com/razorpay/razorpay-flutter/issues/57" - we will remove this integration next release as it is not quite stable

**Comment by antonduong** [comment]
I still have this problem as well.

**Comment by saifmuhtar** [comment]
> @taryaalo - please check this XCode migration you are using latest XCode 11.4 - https://flutter.dev/docs/development/ios-project-migration
> 
> the Razorpay issue is having this issue "[razorpay/razorpay-flutter#57](https://github.com/razorpay/razorpay-flutter/issues/57)" - we will remove this integration next release as it is not quite stable
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/b79d5f795eac013611f2dac92850a689fc9d3d46/68747470733a2f2f666c75747465722e6465762f696d616765732f666c75747465722d6c6f676f2d73686172696e672e706e67">**[Xcode 11.4 Support](https://flutter.dev/docs/development/ios-project-migration)**How to migrate existing Flutter iOS projects to Xcode 11.4.

@minhcasi I cannot release iPhone app because of this Razorpay issue. Please remove Razorpay from FluxStore. I'm waiting for your next FluxStore release.

**Comment by minhcasi** [comment]
@saifmuhtar - we will upload new version to remove Razorpay tomorrow - thank you!

**Comment by saifmuhtar** [comment]
@minhcasi Thank you so much for your great support 🙏🏻😃

**Comment by minhcasi** [comment]
@saifmuhtar - it's ready for downloading the new version - thank you!
