### ISSUE TITLE
[FluxStore Listing]JSON Parser error

### ISSUE THREAD

**Issue by Hyla96** [inspireui/support#2469]
You should change

```
const ProductDataMapping = {
  "lng": "listing_data.geolocation_lng",
};
```

to 

```
const ProductDataMapping = {
  "lng": "listing_data.geolocation_long",
};
```

For MyListing theme, otherwise it will always return error when showing on maps.

**Comment by minhcasi** [comment]
@Hyla96 - thank you for your sharing

@philipvu30 - please update our source code

**Comment by philipvu30** [comment]
Updated
