### ISSUE TITLE
[FluxStore Listing]MyListing no category error

### ISSUE THREAD

**Issue by Hyla96** [inspireui/support#2470]
To replicate:
-> MyListing theme;
-> Create a Listing type ExampleA
-> Create a Listing under ExampleA without a specified category
-> Try to open the application
-> Lists containing Listing ExampleA crash

Why it does so:

`Product.fromListingJson(Map<String, dynamic> json) { ... }`
crashes at line

`pureTaxonomies = Tools.getValueByKey(json, ProductDataMapping["pureTaxonomies"]);`

because list is empty (length == 0 ).

Temporary fix: Just choose a category.

When I understood that the category was the problem I just went on, but It should be fixed.

**Comment by minhcasi** [comment]
Thank you for your feedback, we have noted for checking and will update the source
