### ISSUE TITLE
[Fluxstore - Woo] - What is this "Server Config Mock" and "Mocks" Folder & Blog problem

### ISSUE THREAD

**Issue by sketchuprzr** [inspireui/support#2471]
![image](https://user-images.githubusercontent.com/60021696/77815558-0c963a80-70cd-11ea-967f-683a5f870005.png)
.

Except this ,
I added a blog to the tabbar section. And I wrote my website to url. But it doesn't display my blog posts. It displays a different blog post.

![image](https://user-images.githubusercontent.com/60021696/77815580-4404e700-70cd-11ea-964d-09c1564795ab.png)
![image](https://user-images.githubusercontent.com/60021696/77815584-48c99b00-70cd-11ea-9215-518170ed2253.png)

**Comment by minhcasi** [comment]
@sketchuprzr - it's using for writing unit test purpose, please ignore that setting 

To make it work you need to set another values url, consumse key to blank ""
