### ISSUE TITLE
BeoNews Pro:Expected org.gradle.api.artifacts.result.ResolvedDependencyResult but found org.gradle.api.internal.artifacts.result.DefaultUnresolvedDependencyResult

### ISSUE THREAD

**Issue by zemeister23** [inspireui/support#2472]
i have error in android studio.
<img src="https://i.imgur.com/55Pq562.png">

**Comment by zemeister23** [comment]
<img src="https://i.imgur.com/55Pq562.png">

**Comment by minhcasi** [comment]
Hi, thank you for the feedback. could you format the title and give more detail about the ticket?

Also, could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads it's used to verify your proof of purchase? 
Sorry for any inconvenience, we will reopen the ticket when it is verified, thank you!
