### ISSUE TITLE
[fluxstore pro] - image upload on product page

### ISSUE THREAD

**Issue by tjain90** [inspireui/support#2473]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: i want to my customer to upload image when they purchase any Personalized product. My app mainly sells photo printed gifts and I need any plugin or code that can help customer to upload image when they place an order 

3. Proof of my purchased (required): tjain90@gmail.com from themeforest

**Comment by minhcasi** [comment]
Marked and request features 

Could we know which the uploading image plugin you are using from the woocommerce site ?

**Comment by minhcasi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Custom Checkout - uploading image](https://trello.com/c/jpAOpidK/26-custom-checkout-uploading-image)

**Comment by minhcasi** [comment]
move to the backlog for investigating
