### ISSUE TITLE
Fluxstore multivendor payment

### ISSUE THREAD

**Issue by Shiru-kun** [inspireui/support#2474]
Im having problems with payments methods in my app
when i do a payment with  cash delivery it works properly but 
when i try to select other method like bank transfer , or other it shows blank screen
can u guys help me with this?

**Comment by minhcasi** [comment]
Hi, thank you for the feedback. Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads it's used to verify your proof of purchase? 
Sorry for any inconvenience, we will reopen the ticket when it is verified, thank you!

**Comment by Shiru-kun** [comment]
here!!!

![invoice](https://user-images.githubusercontent.com/54008441/77845369-abdf2e80-71ae-11ea-948d-b8cf9ede65d2.jpeg)

**Comment by minhcasi** [comment]
@Shiru-kun - please also share your common and config folder so that we could reproduce the issue - thank you!

**Comment by Shiru-kun** [comment]
[config.zip](https://github.com/inspireui/support/files/4398596/config.zip)

**Comment by Shiru-kun** [comment]
can u give your email so i can send the project? this file is too big

**Comment by minhtruong315** [comment]
@Shiru-kun can u upload your source code to google drive and add my email: minhtruong315@gmail.com
I will help u update payment webview on your source code.

**Comment by minhtruong315** [comment]
Hi @Shiru-kun I checked your source code. it's old version. pls update the latest version 1.6.5 https://codecanyon.net/item/fluxstore-multi-vendor-flutter-ecommerce-full-app/25013325

**Comment by Shiru-kun** [comment]
hello, i need to buy it again? how can i update the source?

**Comment by Shiru-kun** [comment]
I need to download the app again right?

**Comment by minhtruong315** [comment]
yes. @Shiru-kun

**Comment by Shiru-kun** [comment]
I updated to 1.6.5 downloaded the flutter dependencies and added the keys in my app, but now I can’t see my products , categories shows null message 

Focas Kandulo 
+258 844218050

**Comment by minhtruong315** [comment]
@Shiru-kun send me full your source code

**Comment by Shiru-kun** [comment]
check your email

minhtruong315 <notifications@github.com> escreveu no dia quinta, 2/04/2020
à(s) 04:42:

**Comment by minhtruong315** [comment]
Hi @Shiru-kun We added one page checkout in version 1.6.6. You can try to use that to fix your payment issues

**Comment by Shiru-kun** [comment]
I didn’t get, 
One more page, 
U mean I need to update the app to 1.6.6 ?  
Focas Kandulo 
+258 844218050

**Comment by Shiru-kun** [comment]
Ooooh there is a new version
I’lol download and test it.. 

Focas Kandulo 
+258 844218050

**Comment by minhtruong315** [comment]
@Shiru-kun let me know the result when you updated the latest version. thanks

**Comment by Shiru-kun** [comment]
Im getting this when i look for products and categories
Im missing something?

**Comment by minhtruong315** [comment]
@Shiru-kun you're using fluxstore MV, it only supports dokan and wcfm. but you're making with type: woo. 
```
const serverConfig = {
  "type": "woo",
  "url": "https://staging-krolyccloneapp.kinsta.cloud/",
  "consumerKey": "ck_3a47df06afb11a45f40845694d62378f23b532b3",
  "consumerSecret": "cs_8caa444cde83b2b7dcdb373212aa0a5d66a7bc8b",
  "blog": "https://staging-krolyccloneapp.kinsta.cloud/blog",
  "forgetPassword": "https://staging-krolyccloneapp.kinsta.cloud/a-minha-conta"
};
```

**Comment by Shiru-kun** [comment]
okay i will change to dokan and let you know

minhtruong315 <notifications@github.com> escreveu no dia sábado, 11/04/2020
à(s) 01:37:

**Comment by Shiru-kun** [comment]
i changed to dokan and did some updates, but im having troubles with Sms login before the checkout, i already followed the docs to configure it (in firebase console and added the .json file in android/app )  but its still loading in that screen , what im missin?

**Comment by minhtruong315** [comment]
@Shiru-kun can you record screen?

**Comment by Shiru-kun** [comment]
I just updated and  login sms is working. But now i got
 This ... when im on a payment

**Comment by Shiru-kun** [comment]
When i try to register a user
I got this

**Comment by Shiru-kun** [comment]
@keizershaquil

**Comment by minhtruong315** [comment]
@Shiru-kun You need to update MStore Api plugin and active purchase code to use MStore Api

**Comment by Shiru-kun** [comment]
Ok
Im going to test
And let u known

**Comment by Shiru-kun** [comment]
i updated and added the purchase code  
look: 
![Screenshot from 2020-04-14 08-36-59](https://user-images.githubusercontent.com/54008441/79193684-687df480-7e2b-11ea-9594-352aecfeb207.png)
![Screenshot from 2020-04-14 08-37-54](https://user-images.githubusercontent.com/54008441/79193699-6f0c6c00-7e2b-11ea-99b8-add2cdadb85d.png)

 but i still cant login or place a order( after a sms login)

![Screenshot_20200414-082910](https://user-images.githubusercontent.com/54008441/79193778-98c59300-7e2b-11ea-8f21-e08ab7d3d723.jpg)

![Screenshot_20200414-083330](https://user-images.githubusercontent.com/54008441/79193785-9e22dd80-7e2b-11ea-91f6-c990cb9ea6fb.jpg)

**Comment by Shiru-kun** [comment]
Now i can login, register an user... 
And now i can place a order using the webview. 
But there is a few things bothering me
1. The products from cart arent cleaned after the order. 
2. There is way to place order without a webview?

**Comment by minhtruong315** [comment]
@Shiru-kun 
1. can u record screen?
2. we supports some native payment gateways: COD, Paypal, Razorpay and Tap.

**Comment by Shiru-kun** [comment]
i selected this products 
![image](https://user-images.githubusercontent.com/54008441/79315646-8880e700-7f03-11ea-8422-75070de8b61e.png)

![Screenshot_20200415-101937](https://user-images.githubusercontent.com/54008441/79315569-68e9be80-7f03-11ea-8f8c-4cb150c114f4.jpg)

then i choose this payment method  
![image](https://user-images.githubusercontent.com/54008441/79315741-a8b0a600-7f03-11ea-87c7-629221919e52.png)


then i got this webview  thats says that my order was received 
![image](https://user-images.githubusercontent.com/54008441/79315869-df86bc00-7f03-11ea-8372-fb7ed04ea97c.png)

 and i can go back to history to see it 
![image](https://user-images.githubusercontent.com/54008441/79316094-25438480-7f04-11ea-9c9d-2ef01b52e354.png)

but the same products still in the cart 
![image](https://user-images.githubusercontent.com/54008441/79316287-6c317a00-7f04-11ea-9f68-552fee3be556.png)

**Comment by minhtruong315** [comment]
@Shiru-kun send me screens/checkout/payment_webview.dart file

**Comment by Shiru-kun** [comment]
[payment_webview.zip](https://github.com/inspireui/support/files/4498713/payment_webview.zip)

**Comment by minhtruong315** [comment]
[payment_webview.dart.zip](https://github.com/inspireui/support/files/4498727/payment_webview.dart.zip)
replace this file then try again

**Comment by Shiru-kun** [comment]
It didnt change

**Comment by minhtruong315** [comment]
send me config.dart file

**Comment by Shiru-kun** [comment]
I was in rush i didnt test it well. 
Its working !!!!!
Now i see the success order page after place a order on the webview... 
 after that it shows a page to go back to shopping page and it cleans the cart as i wish, 
But it takes a bit longer... its normal?

**Comment by Shiru-kun** [comment]
I got a doubt 
When u guys launch an update 
I always need to customize the new version...
There is a way   i can just need to pull your updates to my project?

**Comment by minhtruong315** [comment]
You need learn the git to merge source code.
