### ISSUE TITLE
[EvaStore] - Customization Not Showing Up

### ISSUE THREAD

**Issue by denny-dang** [inspireui/support#2475]
1. My issue:
Hello,  I have a problem with displaying the mobile application on iPhones through Expo. On androids, I'm able to display the changes I make in Config.js but it is not reflected through simulations on iPhones. Also, there are some weird bugs in which I can't modify the shop name in 
Constant.js and some products aren't displaying properly with the layout I choose.

2. Screenshots issues (required):
![image](https://user-images.githubusercontent.com/52182574/77838211-9d4d3480-7126-11ea-9935-c5cbf85de530.png)

3. Proof of my purchased (required):
![image](https://user-images.githubusercontent.com/52182574/77837985-565e3f80-7124-11ea-928e-4c16c61253dd.png)

3. Config files (required):
/**
   * Step 3: Setting Home screen, category screen
   * Follow this article to use Graphql https://help.shopify.com/en/api/custom-storefronts/storefront-api/graphql
   * Video tutorial https://www.dropbox.com/s/m4kmp0quh8qplz3/Screen%20Recording%202018-11-05%20at%202.22.21%20PM.mov?dl=0
   */
  SpaceLayout: 15, // setting align right
  /**
   * config home page show
   * - horizontal with multi collection id or
   * - vertical layout with latest product and first product is banner
   */
  HomePage: {
    Horizon: true,
    PageSize: 12,
  },
  HorizonLayout: [
    // {
    //   categoryId: "Z2lkOi8vc2hvcGlmeS9Db2xsZWN0aW9uLzQyMTg1ODM4MQ==",
    //   paging: true,
    //   layout: Constants.Layout.miniBanner,
    // },

    {
      name: "Jitter-less Coffee",
      categoryId: "Z2lkOi8vc2hvcGlmeS9Db2xsZWN0aW9uLzE1NDgyMTQ5Mjc4OQ==",
      layout: Constants.Layout.card,
    },
    {
      name: "Apparel & Accessories",
      categoryId: "Z2lkOi8vc2hvcGlmeS9Db2xsZWN0aW9uLzE1NDgyMTM5NDQ4NQ==",
      layout: Constants.Layout.twoColumn,
    },
  ],

  CategoryLayout: {
    ListMode: "ListMode",
    GridMode: "GridMode",
    CardMode: "CardMode",
  },

**Comment by luyx2412** [comment]
Hi @denny-dang Because we used persist store which cache your config. So you need uninstall expo app and reinstall again to update new Config.

Thanks
