### ISSUE TITLE
[Fluxstore-Woocommerce] - Out of stock variation is selectable

### ISSUE THREAD

**Issue by luigiwidmore** [inspireui/support#2476]
1. My issue

An out of stock variation of a product can be selected, but when Add to cart or Buy now is pressed, the first available size is actually sent to checkout.

Out of stock variation should be highlighted in app and the Add to cart and Buy now buttons should be disabled.

2. Screenshots

http://prntscr.com/ron3mg
This is the product configured in woocommerce

3. Proof of buying

http://prntscr.com/ron95h

**Comment by philipvu30** [comment]
Hi @luigiwidmore ,

May I ask what is your email? I'll send you the solution. Thank you

**Comment by luigiwidmore** [comment]
Hello @philipvu30,

My email is my username at gmail dot com.

Regards

**Comment by philipvu30** [comment]
Hi @luigiwidmore ,

I'm sorry I was mistaken about your issue with another. Would you mind sending me the config.dart and your modified config_**.json to this email: toan@inspireui.com. Thank you

**Comment by philipvu30** [comment]
Hi @luigiwidmore ,

I received your files. I'll let you know when it has been fixed.

**Comment by luigiwidmore** [comment]
Hey @philipvu30 

I appreciate your help.
Please let me know how can i get access to gitlab repo to be able to merge your fix without losing my changes.

**Comment by philipvu30** [comment]
Hi @luigiwidmore ,

Please replace these 2 files in lib/models 
[cart.zip](https://github.com/inspireui/support/files/4407876/cart.zip)
[product.zip](https://github.com/inspireui/support/files/4407877/product.zip)

and this one in lib/screens/detail
[product_variant.zip](https://github.com/inspireui/support/files/4407880/product_variant.zip)

It should fixed the issue above. Thank you

**Comment by luigiwidmore** [comment]
Hey, 

Thank you very much. I will try and let you know.
Any chance i can get access to the Gitlab Repository so i can manage the changes using GIT?

Thanks

**Comment by philipvu30** [comment]
Hi @luigiwidmore ,

I'm sorry I can't give you access to our company's git repository. However, we do have a git repository for customer. Have you had the access to that repository yet?

**Comment by luigiwidmore** [comment]
Hi @philipvu30 ,

Not the company's git repository, just any repo where i can pull the latest changes.
I don't have access to any git repo regarding this project.

Thanks

**Comment by philipvu30** [comment]
Hi @luigiwidmore ,

Please submit your request to access our GitLab Repository here: [Request Form](https://docs.google.com/forms/d/e/1FAIpQLSeuBqUkScy42V7KKhfNPj0fl581anrB1mWkbMa3p2WQt7fhfw/viewform). Thank you

**Comment by luigiwidmore** [comment]
Hey @philipvu30,

I requested access thru the request form.. 

Thanks

**Comment by luigiwidmore** [comment]
Hey @philipvu30 ,

> Please replace these 2 files in lib/models

I do not have "product.dart" and "cart.dart" in **lib/models** folder.

Also in the attached product_variant.dart i have this on line 16 : 
import '../../widgets/common/webview.dart';
File that gives me an error because the file does not exist in my codebase.

Thanks

**Comment by philipvu30** [comment]
Hi @luigiwidmore ,

I sent you the new source code via email. Please check and confirm if it works. Thank you.

**Comment by luigiwidmore** [comment]
Hey @philipvu30,

The source code provided by email does not compile at all. 
There are a lot of **getter not found** and **method not found** errors.
I've tried to use "Compare with" option from Android Studio and there are way to many differences between the version downloaded from Codecanyon and the email version.

Are there any other methods to provide updates and patches for this codebase?

Regards

**Comment by luigiwidmore** [comment]
Hey, i managed to get the latest changes by using "Compare with" only on /lib/ folder, but the problem i was telling you about is still happening.

I'm going to attach a video to illustrate the problem.
Context : 
For this product, i only have one remaining pair, a Size 38.
If i select Size 35 and click "Add to Cart", the Size 38 is added to cart istead, as seen in the attached video.
![record](https://user-images.githubusercontent.com/7034048/78322885-ad2aa580-7578-11ea-9872-8889585f9a82.gif)

The expected behaviour would be that even before adding to cart, the sizes that are out of stock should not be selectable, otherwise the users will be confused.
Here's a screenshot from the website : 
![image](https://user-images.githubusercontent.com/7034048/78322965-085c9800-7579-11ea-9a81-92765f3ec8bf.png)

Please advise on how can that be achieved.
Regards

**Comment by philipvu30** [comment]
Hello,

Please make sure that product has checked these 2 options. Thanks

![image](https://user-images.githubusercontent.com/54442328/78333379-ee8c7680-75b3-11ea-97e4-37b411a92f9d.png)

**Comment by luigiwidmore** [comment]
Hello @philipvu30 ,

All the products have both checkbox checked : 
![image](https://user-images.githubusercontent.com/7034048/78338453-80d45080-759b-11ea-87e0-be077e6936e2.png)

**Comment by philipvu30** [comment]
Hi,

I don't know why you have checked those options but it still shows the "visible" attribute = false.
![image](https://user-images.githubusercontent.com/54442328/78341451-edfadc80-75c1-11ea-8d48-8b2c5e8b8f0b.png)

So for your case please remove this term in lib/services/woo_commerce.dart

![image](https://user-images.githubusercontent.com/54442328/78341385-d0c60e00-75c1-11ea-88e3-06234254ab3e.png)

Thanks
