### ISSUE TITLE
FluxStore -  Address Pick and Shared Address across accounts

### ISSUE THREAD

**Issue by kimisan87** [inspireui/support#2477]
1. My issue:
-cant pick address from list of address 
-user address is shared across accounts that logged in 

2. Screenshots issues (required):https://prnt.sc/roqcxr

3. Proof of my purchased (required): https://prnt.sc/roqcfb
3. Config files (required) : Fluxstore Pro intergration with OpenCart

**Comment by minhtruong315** [comment]
[choose_address.dart.zip](https://github.com/inspireui/support/files/4400322/choose_address.dart.zip)
you can try to replace screens/checkout/choose_address.dart.dart then run again

**Comment by kimisan87** [comment]
@minhtruong315 tq its working now for the same address across account just foundout that the address is saved locally per phone tq for your hard work

**Comment by robaa1418** [comment]
I solved by edit in choose_addess.dart 
in Widget build(BuildContext context) 
line 297
  Provider.of<CartModel>(context, listen: 
false).setAddress(listAddress[index]);
just set the listen to false and after that set address

**Comment by minhcasi** [comment]
@kimisan87 - fix the choose_address will fix the issue - https://tppr.me/TOXM3 - thank you!
