### ISSUE TITLE
[fluxnew] - Problem customizing the home page

### ISSUE THREAD

**Issue by haidarsalim** [inspireui/support#2480]
I have a problem customizing the home page
When I modify config.json A red color error occurs as in the attached image
I used fluxbuilder to do that
When I modify config_ar.json Any change does not happen
![123456](https://user-images.githubusercontent.com/54249914/77855368-ac041c00-71f8-11ea-8217-6831ef1981c7.JPG)

[config.zip](https://github.com/inspireui/support/files/4399329/config.zip)
https://baytaltatbiqat.com/

---------
Performing hot restart...
Syncing files to device Android SDK built for x86...
E/AccessibilityBridge(16190): VirtualView node must not be the root node.
Restarted application in 3,052ms.
W/FA      (16190): setCurrentScreen cannot be called with the same class and name

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building HorizontalSliderList(dirty, dependencies: [InheritedProvider<RecentModel>, InheritedProvider<AppModel>], state: _HorizontalSliderListState#74452):
type 'int' is not a subtype of type 'double'

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  HorizontalSliderList file:///C:/Users/haida/Desktop/source/lib/widgets/blog/index.dart:56:16
When the exception was thrown, this was the stack: 
#0      _HorizontalSliderListState.build (package:fstore/widgets/blog/horizontal/slider_list.dart:53:18)
#1      StatefulElement.build (package:flutter/src/widgets/framework.dart:4334:27)
#2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4223:15)
#3      Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#4      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (2) Exception caught by widgets library ═══════════════════════════════════════════════════
type 'int' is not a subtype of type 'double'
The relevant error-causing widget was: 
  HorizontalSliderList file:///C:/Users/haida/Desktop/source/lib/widgets/blog/index.dart:56:16
════════════════════════════════════════════════════════════════════════════════════════════════════
W/FA      (16190): setCurrentScreen cannot be called with the same class and name

════════ (3) Exception caught by widgets library ═══════════════════════════════════════════════════
type 'int' is not a subtype of type 'double'
The relevant error-causing widget was: 
  HorizontalSliderList file:///C:/Users/haida/Desktop/source/lib/widgets/blog/index.dart:56:16
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (4) Exception caught by widgets library ═══════════════════════════════════════════════════
type 'int' is not a subtype of type 'double'
The relevant error-causing widget was: 
  HorizontalSliderList file:///C:/Users/haida/Desktop/source/lib/widgets/blog/index.dart:56:16
════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (16190): [Category { id: 42  name: آيفون - آيباد}, Category { id: 43  name: أندرويد}, Category { id: 36  name: تقنية}, Category { id: 1  name: عام}, Category { id: 37  name: منوعات}]
E/flutter (16190): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: A CategoryModel was used after being disposed.
E/flutter (16190): Once you have called dispose() on a CategoryModel, it can no longer be used.
E/flutter (16190): #0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:105:9)
E/flutter (16190): #1      ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:111:6)
E/flutter (16190): #2      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:200:12)
E/flutter (16190): #3      CategoryModel.getCategories (package:fstore/models/category.dart:29:7)
E/flutter (16190): <asynchronous suspension>
E/flutter (16190): #4      HomeScreenState.afterFirstLayout (package:fstore/screens/home.dart:110:41)
E/flutter (16190): #5      AfterLayoutMixin.initState.<anonymous closure> (package:after_layout/after_layout.dart:10:38)
E/flutter (16190): #6      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
E/flutter (16190): #7      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1049:9)
E/flutter (16190): #8      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:957:5)
E/flutter (16190): #9      _rootRun (dart:async/zone.dart:1126:13)
E/flutter (16190): #10     _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter (16190): #11     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
E/flutter (16190): #12     _invoke (dart:ui/hooks.dart:259:10)
E/flutter (16190): #13     _drawFrame (dart:ui/hooks.dart:217:3)
E/flutter (16190): 
I/flutter (16190): [Category { id: 42  name: آيفون - آيباد}, Category { id: 43  name: أندرويد}, Category { id: 36  name: تقنية}, Category { id: 1  name: عام}, Category { id: 37  name: منوعات}]

════════ (5) Exception caught by widgets library ═══════════════════════════════════════════════════
type 'int' is not a subtype of type 'double'
The relevant error-causing widget was: 
  HorizontalSliderList file:///C:/Users/haida/Desktop/source/lib/widgets/blog/index.dart:56:16
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by dttrung26** [comment]
Hi @haidarsalim , 
this problem will be solved in the next 1.3 FluxNews update. So sorry for any inconvenience may cause. 
Happy coding!

**Comment by haidarsalim** [comment]
This is funny. Do I need an update to work on the application?

**Comment by dttrung26** [comment]
Yes, of course you do. You will get an notification when we update a new version on codecayon. 
I do hope you could understand the situation that instead of fixing this bug individually, we need to update the situation for our world wide user, including you sir.
Have a wonderful day!
