### ISSUE TITLE
[Fluxstore] - xcode build issue

### ISSUE THREAD

**Issue by khalidsharif** [inspireui/support#2481]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
I am able to build the app with android simulator but with iOS it has error related to firebase pod I guess.

note: I als tried with pod install ...but still same issue

2. Screenshots issues (required):

<img width="1481" alt="Screen Shot 2020-03-29 at 10 47 58 PM" src="https://user-images.githubusercontent.com/50369621/77858976-60a93800-720f-11ea-90a6-23ff335e6138.png">

3. Proof of my purchased (required):
<img width="885" alt="Screen Shot 2020-03-29 at 10 49 31 PM" src="https://user-images.githubusercontent.com/50369621/77859009-8fbfa980-720f-11ea-8361-1d13561501c6.png">

3. Config files (required)
I am using the demo confi files provided

**Comment by minhcasi** [comment]
@khalidsharif - could you check solution on this link https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

Also, try to run the app from Android Studio instead of running from XCode

**Comment by khalidsharif** [comment]
I tried the solution provided. still same error.

here is my environment.

<img width="965" alt="Screen Shot 2020-03-30 at 11 15 07 AM" src="https://user-images.githubusercontent.com/50369621/77890164-b9acb680-7277-11ea-8a27-b1669c9af552.png">
<img width="1100" alt="Screen Shot 2020-03-30 at 11 15 26 AM" src="https://user-images.githubusercontent.com/50369621/77890192-c4674b80-7277-11ea-9f94-53c1b11eca27.png">

**Comment by minhcasi** [comment]
@khalidsharif  - please check this XCode migration you are using latest XCode 11.4 - https://flutter.dev/docs/development/ios-project-migration

**Comment by khalidsharif** [comment]
I tried the suggested solution. the file structrue is different ..the solution didnt work.
Now I tried with downradingg the xcode. I am able to build and install the app with xcode 11.3.1 but when I open the app I get a blank screen!!

**Comment by khalidsharif** [comment]
I dont think its related to the xCode version because I have other flutter apps working without problems

**Comment by khalidsharif** [comment]
Where I can dwnload older versions ?

**Comment by minhcasi** [comment]
pls submit to our gitlab - https://codecanyon.net/item/fluxstore-woocommerce-flutter-ecommerce-full-app/24050041

We will also upload new release on tomorrow to fix the Razorpay issue - thank you!

**Comment by khalidsharif** [comment]
I have submitted the form t get an older version.
Thanks.

**Comment by minhcasi** [comment]
@khalidsharif - it's ready for download on gitlab and codecayon - thank you!

**Comment by khalidsharif** [comment]
Great, now working on xCode without problems 
thanks
