### ISSUE TITLE
[Fluxstore-MV] - Stores Vendor Error after update to 1.6.5

### ISSUE THREAD

**Issue by ideas24** [inspireui/support#2482]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
Under the Stores' tab, when you click on a Vendor, it throws a red Error screen with the text "Error in Failed assertion: boolean expression must not be null"
This error started showing after updating to 1.6.5. Please help me fix.

2. Screenshots issues (required):
![boolean-error](https://user-images.githubusercontent.com/34719083/77868599-c0b1d580-7233-11ea-908f-f19c5b9d70d0.jpg)

3. Proof of my purchased (required):
![image](https://user-images.githubusercontent.com/34719083/77868302-a0cde200-7232-11ea-9f83-0f06098a7631.png)

3. Config files (required)

**Comment by minhcasi** [comment]
@ideas24 - pls don't create duplicate ticket support - you already sent us the email - thanks

**Comment by ideas24** [comment]
@minhcasi sorry my bad. I have forward my source to your mail.
