### ISSUE TITLE
FLUXSTORE MULTI VENDOR Version 1,6,4

### ISSUE THREAD

**Issue by kardotinambunan12** [inspireui/support#2483]
![bukti](https://user-images.githubusercontent.com/61267127/77874455-2bd0cb80-7277-11ea-918a-ef007c90d732.png)

#createproduct
i have a problem FLUXSTORE MULTI VENDOR FLUTTER E_COMMERCE VERSION 1.6.4 where in the create product section the  notif "type'(httpexception)=>null" is not a sub type of type "(dynamic)=>dynamic" appears and does not send to the product seell.

#image
![Uploading Screenshot_20200323_132741 (1).png…]()

anyone can help ? . thanks

**Comment by minhcasi** [comment]
@kardotinambunan12 - could you try to use the latest 1.6.5 - thanks

**Comment by kardotinambunan12** [comment]
hi @Minh Pham
i've tried the newest version(1.6.5) but gota same error, the product
images is successfully posted and saved in media. but product not create or
saved. with error message like this.
the first image error due to using our server, and the second image error
using the default server application.
can help me overcome this problem. thanks

Pada tanggal Sen, 30 Mar 2020 pukul 19.53 Minh Pham <
notifications@github.com> menulis:

**Comment by minhcasi** [comment]
@kardotinambunan12 - please share your common and config folder here - we will help for checking

**Comment by kardotinambunan12** [comment]
I have attached the folder. and thanks for helping.

Pada tanggal Kam, 2 Apr 2020 pukul 19.49 Minh Pham <notifications@github.com>
menulis:

**Comment by kardotinambunan12** [comment]
The config at the bottom is a config from our server.

Pada tanggal Jum, 3 Apr 2020 pukul 08.53 Kardo Tinambunan <
kardotinambunan12@gmail.com> menulis:

**Comment by kardotinambunan12** [comment]
Pada tanggal Jum, 3 Apr 2020 pukul 09.36 Kardo Tinambunan <
kardotinambunan12@gmail.com> menulis:

**Comment by kardotinambunan12** [comment]
[Uploading common.rar…]()
