### ISSUE TITLE
[FluxShop Pro] - Profile Update not working + want to display header in all pages 

### ISSUE THREAD

**Issue by bikostudio** [inspireui/support#2485]
Hi, 

1- I have problem with updating profile information I got this ( Expetion: can not updt user infor)
2- How to display the header with logo and search button and the menu button in all pages?

I'm using latest 1.6.5c + the api plugin is undated too.

thank you for your time

**Comment by minhcasi** [comment]
@bikostudio - please help to raise this issue to the same ticket #2439 - thank you!

Stay safe out there 👍

**Comment by bikostudio** [comment]
I have updated my ticket with problems and requests under title ( [FluxStore
Pro] - All My Peoblems And Requests #2439
