### ISSUE TITLE
[my-product] - floxnew.1.2.2

### ISSUE THREAD

**Issue by mbatm** [inspireui/support#2486]
1. My issue:
- there is no side menu shown..
- i cannot change fonts or adapting to turkish fonts.
- my app dont show white background at news detail.
- at opening page, news not  shorrting  by new.. i cannot solve it
- i want to translate all my app to turkish. so, i create a new  strings_tr.arp document and translate all of it. but i dont know how can i set this.

2. Screenshots issues (required):
![image](https://user-images.githubusercontent.com/62890007/77925678-d237c380-72ad-11ea-97f2-927caa51ee21.png)
![image](https://user-images.githubusercontent.com/62890007/77925686-d663e100-72ad-11ea-9096-6fa26d88ad76.png)

3. Proof of my purchased (required):
![Uploading image.png…]()

3. Config files (required)

**Comment by dttrung26** [comment]
Hi @mbatm ,
please leave me your skype, I'll reach you for assistance. 
Have a nice day!

**Comment by mbatm** [comment]
+905353792894  my skype

Doan Tan Trung <notifications@github.com>, 31 Mar 2020 Sal, 04:41 tarihinde
şunu yazdı:

**Comment by mbatm** [comment]
https://join.skype.com/invite/jWtXlY6X7U04


31 Mar 2020 Sal, saat 04:41 tarihinde Doan Tan Trung <
notifications@github.com> şunu yazdı:

**Comment by dttrung26** [comment]
Close due to no response from user. Feel free to reopen this ticket again.
