### ISSUE TITLE
[FluxStore -WooCommerce] - Issue with the Coupon Code

### ISSUE THREAD

**Issue by Lokeswara-betha** [inspireui/support#2487]
HI , I am facing issue with the coupon code.

At the time of added coupon , it working fine. But in generated order it is not showing discounted amount.
Screen shot After coupon is added.
![Screenshot_2020-03-30-20-02-29-503_com app nutplanet](https://user-images.githubusercontent.com/60268240/77926280-93146d00-72c3-11ea-9f9b-cb1e71e98ab2.jpg)
Screen shot After  placing Order:

![Screenshot_2020-03-30-20-05-39-542_com app nutplanet](https://user-images.githubusercontent.com/60268240/77926348-a6bfd380-72c3-11ea-9608-a2e9ee391187.jpg)

As you can see , original amount is not reflecting on order.
Proof of purchase:
![74719377-e8d40f00-5259-11ea-830c-184e86a4cb69](https://user-images.githubusercontent.com/60268240/77926044-429d0f80-72c3-11ea-8307-b972a41de057.jpg)

**Comment by philipvu30** [comment]
Hi @Lokeswara-betha ,

May I ask what version of fluxstore are you using? This issue has already been fixed and it should be included in the latest patch. If possible, please send your config.dart and your modified config_xx.json to this email: toan@inspireui.com. Thank you.

**Comment by Lokeswara-betha** [comment]
Please verity your email , I sent to both files with #2487 subject

**Comment by philipvu30** [comment]
Hi @Lokeswara-betha ,

I received your files. I'll let you know when it has been fixed.

**Comment by philipvu30** [comment]
Hi @Lokeswara-betha ,

New version will be released in a few days. I have tested your config files with the new version and no issue was found. 
Thank you for your patience.

**Comment by philipvu30** [comment]
Hi @Lokeswara-betha ,

I sent you the new source code via email. Please check and confirm if it works. Thanks

**Comment by Lokeswara-betha** [comment]
HI , 

I am getting below error while running project.

![unnamed](https://user-images.githubusercontent.com/60268240/78229388-8d01d480-74ed-11ea-9fb6-be423506bdc2.png)

**Comment by philipvu30** [comment]
Hello,

Could you try to replace the new lib folder and pubspec.yaml file to your old working project? Thanks

**Comment by Lokeswara-betha** [comment]
Still same error coming , Recently I have changed my system , from that time on words I am not able to run old app also in my new system.  It showing the same error that i mentioned in above comments.

Please help to me get out from this situation. I am not able to do any changes for my existing app now.

**Comment by philipvu30** [comment]
Hi @Lokeswara-betha ,

Please contact me via Skype: vuthanhtoan30. I'll help you through TeamViewer. 

Thanks

**Comment by Pascalnhuis** [comment]
Also here it doesn't work well for me. Coupon Code works fine in cart, but when someone want to pay, the discount is lost and he need to pay the full amount. How to fix that? Thanks! :)
