### ISSUE TITLE
Fluxstore Pro - XBuild error code 

### ISSUE THREAD

**Issue by Rileyjrjohns** [inspireui/support#2488]
1. My issue:

I encounter an issue when i launch flutter run on IOS simulator. Build return an error with architectures. I've tried to clean flutter, but error still the same.. i've tried on another mac with brand new flutter config and it's not working too.. 

Thanks for your help !

2. Screenshots issues (required):

![Capture d’écran 2020-03-30 à 17 08 10](https://user-images.githubusercontent.com/58285390/77929361-d9f56900-72a9-11ea-9171-b73bb5407abb.png)

3. Proof of my purchased (required):

![Capture d’écran 2020-03-30 à 17 10 28](https://user-images.githubusercontent.com/58285390/77929406-eaa5df00-72a9-11ea-8028-7a1e18b5c27c.png)

3. Config files (required)

![Capture d’écran 2020-03-30 à 17 10 45](https://user-images.githubusercontent.com/58285390/77929425-f1345680-72a9-11ea-9f0f-f35adfb4fe53.png)

**Comment by philipvu30** [comment]
Same issue as [ticket 2481](https://github.com/inspireui/support/issues/2481). Please follow up this one for solution. Thank you.

**Comment by Rileyjrjohns** [comment]
I already do all the step... That doesn't help =/

**Comment by minhcasi** [comment]
@Rileyjrjohns - please check this XCode migration you are using latest XCode 11.4 - https://flutter.dev/docs/development/ios-project-migration

**Comment by Rileyjrjohns** [comment]
Hello @minhcasi,

I deal with the bug by fully removing the Razorpay that seem to be outdated in the project configuration. 

After that i got another bug with white screen on IOS that i solve by migrate ios project and import 2 package on the folder. Everything work for now... Having 2 major bug in first launch is quite confusing, and asking for help and be closed too =/ thanks for your answer, you could consider as solved with Razorpay removal...

**Comment by robert-stevens** [comment]
@Rileyjrjohns 

I have the same problem as you, also getting a white screen.

Could you point me in the right direction?

**Comment by Rileyjrjohns** [comment]
@robert-stevens  

Of course you have to flutter clean then open ios folder of your project in xCode

then in general -> Frameworks, Libraries and embedded content click "+" ADD file and choose in the IOS folder -> flutter -> App.framework and Flutter.framework

![Capture d’écran 2020-04-03 à 13 05 41](https://user-images.githubusercontent.com/58285390/78354505-3effd600-75ac-11ea-9bca-fec056d7b4b0.png)
![Capture d’écran 2020-04-03 à 13 06 02](https://user-images.githubusercontent.com/58285390/78354508-41fac680-75ac-11ea-8036-47a7555a78a7.png)
![Capture d’écran 2020-04-03 à 13 06 42](https://user-images.githubusercontent.com/58285390/78354511-432bf380-75ac-11ea-9c4e-447e4267d606.png)
