### ISSUE TITLE
[Fluxstore Pro] - How to hide mstore-api page until opening payment page on webview payment

### ISSUE THREAD

**Issue by ahmetozcan9211** [inspireui/support#2490]
**I can't use any native payment method in my country (in Turkey). so i want hide mstoreapi page until redirect to my website payment page at payment_webview. it isn't looks good. how can I do this.**

**here is screen shots:**

**here is my payment selector screen:**

![Simulator Screen Shot - iPhone 8 Plus - 2020-03-30 at 22 59 46](https://user-images.githubusercontent.com/9422532/77956301-556f0e80-72da-11ea-8619-7f4204ee853c.png)

**and here is mstoreapi landing page (I want hide this)**

![Simulator Screen Shot - iPhone 8 Plus - 2020-03-30 at 23 00 15](https://user-images.githubusercontent.com/9422532/77956378-70da1980-72da-11ea-9c88-83cd837f4d88.png)

**and I want redirect here without show mstore api page.**

![Simulator Screen Shot - iPhone 8 Plus - 2020-03-30 at 23 00 30](https://user-images.githubusercontent.com/9422532/77956428-88b19d80-72da-11ea-829c-177d05c1a768.png)

**Here is my license screenshot**

![Screen Shot 2020-03-30 at 23 03 49](https://user-images.githubusercontent.com/9422532/77956557-c1ea0d80-72da-11ea-8b6a-f4ecaa97d799.png)

**Comment by minhtruong315** [comment]
@ahmetozcan9211 do you want to hide payment webview after place order successfully?

**Comment by ahmetozcan9211** [comment]
no I want hide this screen.
![Simulator Screen Shot - iPhone 8 Plus - 2020-03-30 at 23 00 15](https://user-images.githubusercontent.com/9422532/77997246-bc6ee080-7337-11ea-9a07-01055d9cd1ba.png)

i see this screen before my payment page. so I want this screen until loading next page

**Comment by ahmetozcan9211** [comment]
i want show loading indicator until payment page loading

**Comment by ahmetozcan9211** [comment]
@minhtruong315

**Comment by minhtruong315** [comment]
@ahmetozcan9211 it can't. payment webview must open checkout page then auto place order. so you need to  wait to process the order

**Comment by minhtruong315** [comment]
@ahmetozcan9211 I can make it show loading while process order
