### ISSUE TITLE
Fluxstore WooCommerce - Blog Post

### ISSUE THREAD

**Issue by antonduong** [inspireui/support#2491]
1. My issue:
Title posts load but when selected an error message pops up. Old posts work but new posts does not. Tried to replace file from #2338 but the error still shows.

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building HalfImageType(dirty, dependencies: [MediaQuery], state: _HalfImageTypeState#6baee):
The method '*' was called on null.
Receiver: null
Tried calling: *(1.2)

The relevant error-causing widget was: 
  HalfImageType file:///Users/AD_2020/AD_App/Sunny/Core/source/lib/widgets/blog/blog_view.dart:28:16
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      Tools.image (package:fstore/common/tools.dart:92:35)
#2      _HalfImageTypeState.build (package:fstore/widgets/blog/detailed_blog_half_image.dart:27:30)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4334:27)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4223:15)
...
2. Screenshots issues (required):
<img width="392" alt="Screen" src="https://user-images.githubusercontent.com/7991864/77955601-74e84600-729e-11ea-8cfd-6c71f7d7d285.png">

3. Proof of my purchased (required):
<img width="1087" alt="proof" src="https://user-images.githubusercontent.com/7991864/77956418-d8bf3e80-729f-11ea-9e0b-ca3eabe87760.png">

3. Config files (required)

**Comment by trunghieuvn** [comment]
@antonduong  please help me share common and config in sourc. 
and steps reproduce isssue? 
thanks

**Comment by antonduong** [comment]
On my wordpress, I created a new post. On the virtual device, when I access the blog page from the menu, it lists all the posts but when I select it, the Null Error message comes up.
[common.zip](https://github.com/inspireui/support/files/4406814/common.zip)
[config.zip](https://github.com/inspireui/support/files/4406815/config.zip)

**Comment by trunghieuvn** [comment]
To fix this error, please add the following code to the file `lib/common/tools.dart`

```
 if (height == null && width == null) {
      width = 200;
 }
```

![image](https://user-images.githubusercontent.com/19247680/77999861-8e9c9280-735d-11ea-82b8-89202695fec2.png)

**Comment by antonduong** [comment]
It seems like it only works when this edit is done during a hot reload. When rebuilding with the new edit, this is what shows up on the screen.

<img width="1576" alt="imageerrror" src="https://user-images.githubusercontent.com/7991864/78032365-e540a700-7332-11ea-96a6-e451856f7741.png">

**Comment by trunghieuvn** [comment]
The error in the image is because the url image is null. But in the code, I checked the null of the url image
Please check if there is any case that the url is equal to null?
You can search in source with keyword `ExtendedImage.network`, put log nearby, if so please try checking null and return another url or other result.

**Comment by antonduong** [comment]
Got it. Thank you @trunghieuvn

**Comment by trunghieuvn** [comment]
@antonduong Nice to help you]  . Please help me close the ticket and if you feel satisfied please give me 5 stars https://codecanyon.net/downloads .
Thank you very much.

**Comment by antonduong** [comment]
Sure. Thank you!
