### ISSUE TITLE
[Fluxstore Multivendor] - Stores page

### ISSUE THREAD

**Issue by marknestor261** [inspireui/support#2492]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: Hello, i am using wcfm and my stores banners do not sync in the app at all. Yet vendors have banners and logos on website. 
PS: I got the latest update, but issue wasn't resolved, also solution in previous ticket #2165 did not work.

2. Screenshots issues (required):
![74985128-e6cfa300-5447-11ea-84d9-7c62738a64cc](https://user-images.githubusercontent.com/46901102/77957417-1f328e80-72dc-11ea-867b-96ebb34b35aa.png)

3. Proof of my purchased (required):
![code-canyon](https://user-images.githubusercontent.com/46901102/77957595-66208400-72dc-11ea-9cbc-400b91e08bfc.PNG)

3. Config files (required):
![code-canyon](https://user-images.githubusercontent.com/46901102/77957683-87817000-72dc-11ea-970a-1ba1c52a772a.PNG)

**Comment by marknestor261** [comment]
Sorry about the mistake. Here are the config files
[lib.zip](https://github.com/inspireui/support/files/4405227/lib.zip)

**Comment by minhcasi** [comment]
@marknestor261 - pls comment this issues to the same of your ticket #2448
