### ISSUE TITLE
Fluxlist doesn't work!. Help please.

### ISSUE THREAD

**Issue by master736** [inspireui/support#2493]
My environment works.
I tested with flutter doctor.
And I ran another project from you (fluxstore) and it runs fine.
This one does not. Here's the error message.
<img width="1656" alt="77490765-0e27e000-6df9-11ea-90d3-ee6148e01789" src="https://user-images.githubusercontent.com/40126918/77977322-41b0b180-72b4-11ea-9e44-2cf11f2020b3.png">

**Comment by master736** [comment]
![Screenshot (13)](https://user-images.githubusercontent.com/40126918/77977348-53925480-72b4-11ea-96e6-aae52a30034e.png)

**Comment by minhcasi** [comment]
@master736   - please check this XCode migration you are using latest XCode 11.4 - https://flutter.dev/docs/development/ios-project-migration
