### ISSUE TITLE
Fluxstore Woocommerce 1.6.5c

### ISSUE THREAD

**Issue by gugan7** [inspireui/support#2494]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: IOS build is blank when using Fluxstore Woocommerce 1.6.5c . I built with original source code without any modification. Code can be deploy to IOS simulator but screen is showing blank page once Fluxstore App is launch. I have try remove Pods folder, Podfile and fodfile.lock but its still same . Android build is working fine for me.

2. Screenshots issues (required):
![image](https://user-images.githubusercontent.com/42231641/77977398-30a68580-7332-11ea-871f-7fe297f39644.png)

3. Proof of my purchased (required):
![image](https://user-images.githubusercontent.com/42231641/77977477-5e8bca00-7332-11ea-9999-058f1fa5bf4f.png)

3. Config files (required)

**Comment by minhcasi** [comment]
@gugan7 - please check this XCode migration issue from latest XCode 11.4 - https://flutter.dev/docs/development/ios-project-migration

**Comment by gugan7** [comment]
Hi i'm using XCode Version 11.3.1 (11C504) and i don't see those files there.

![image](https://user-images.githubusercontent.com/42231641/77984815-38bbf080-7345-11ea-8307-eb2a111f5de1.png)

**Comment by Rileyjrjohns** [comment]
Hi, Update XCODE and perform migration ;)

**Comment by Isodie** [comment]
Hi, 
how did you fixed?

**Comment by gugan7** [comment]
xcode 11.4 needs minimum of macOS 10.15.2  which doesn't support my mac yet. I'm trying other ways to solve this.

**Comment by minhcasi** [comment]
@gugan7 - you can try to clean cache, i've noted some solution here - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

**Comment by minhcasi** [comment]
@gugan7 - please update the latest 1.6.6 to fix build issue, we also note the detail on this changelog blog - https://medium.com/@inspireui/announcing-fluxstore-1-6-337efff1791f - thank you!
