### ISSUE TITLE
[FLUXSTORE MV] - Can't login after change App Bundle

### ISSUE THREAD

**Issue by antixirus** [inspireui/support#2495]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
Im change app bundle to my app bundle, but after im change it, i can't login in my app. Stuck in login. Please help

2. Screenshots issues (required):
![gambar](https://user-images.githubusercontent.com/57300649/77980800-6ea3a980-7332-11ea-8934-9bfb9df7997c.png)

3. Proof of my purchased (required):
![gambar](https://user-images.githubusercontent.com/57300649/77981025-0acdb080-7333-11ea-9d5d-4242cbd8feb5.png)

3. Config files (required)

**Comment by kvt0012** [comment]
Which do you use to sign in, sir? 
Google, fb, or something else, thank you

**Comment by antixirus** [comment]
@kvt0012 Im use email and password for Sign in sir

**Comment by antixirus** [comment]
Do you have Skype sir? I will contact you in Skype sir

**Comment by kvt0012** [comment]
please send me your config and version you use, sir, I will support to you. Thank you

**Comment by kvt0012** [comment]
You can use my email to find me, but I don't usually support via Skype, sorry for this inconvenience.

**Comment by antixirus** [comment]
@kvt0012 Done sir, please check your email. Im send you fully source of my project, because if im just send my config to you, maybe the app can run normal.

**Comment by antixirus** [comment]
@kvt0012 How? Have you checked?

**Comment by kvt0012** [comment]
Ok sir, I will checknow
Btw, We're sorry that because of Covid-19, so it affects to our team availability, so sorry for inconvenice.

**Comment by kvt0012** [comment]
i'll check and it's normal,sir 
![image](https://user-images.githubusercontent.com/49152325/78323410-efb1a980-759b-11ea-9c29-384649c120a9.png)

**Comment by kvt0012** [comment]
And I'll check and you run on our old version, please update it for more convenience, thank you

**Comment by antixirus** [comment]
@kvt0012 What the old version sir? Im use Fluxstore MV 1.6.5 sir

**Comment by kvt0012** [comment]
Oh ok, sir, you config too much so I miss some features.

**Comment by kvt0012** [comment]
@minhtruong315 Dear btother, he has the problem with open cart api, please help him fix it, thank you :D

**Comment by minhtruong315** [comment]
@antixirus I messaged you on the skype

**Comment by antixirus** [comment]
@minhtruong315 Yes, I have replied, sir

**Comment by minhtruong315** [comment]
@antixirus please update version 1.6.6 then check again
