### ISSUE TITLE
ListPro - The demo install does not work.

### ISSUE THREAD

**Issue by leonmktg** [inspireui/support#2496]
The sections that are pre-built are not displaying properly. I've tried to decipher the issue but can't seem to find the problem. Thanks for any help you can send my way!

<img width="435" alt="Screen Shot 2020-03-30 at 10 26 31 PM" src="https://user-images.githubusercontent.com/62923357/77991562-80109580-72e1-11ea-8ae4-66da42979219.png">

<img width="435" alt="Screen Shot 2020-03-30 at 10 26 18 PM" src="https://user-images.githubusercontent.com/62923357/77991560-7b4be180-72e1-11ea-85b9-630d1ecfcab9.png">

<img width="433" alt="Screen Shot 2020-03-30 at 10 25 50 PM" src="https://user-images.githubusercontent.com/62923357/77991552-738c3d00-72e1-11ea-9a2c-eda3dc62563a.png">

**Comment by minhcasi** [comment]
Hi, thank you for the feedback. Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads it's used to verify your proof of purchase? 
Sorry for any inconvenience, we will reopen the ticket when it is verified, thank you!

**Comment by leonmktg** [comment]
<img width="1680" alt="Screen Shot 2020-03-31 at 5 59 05 AM" src="https://user-images.githubusercontent.com/62923357/78023949-c8957680-7314-11ea-9749-45dba8ba899a.png">

**Comment by leonmktg** [comment]
Now i am getting this error:

INFO
06:06
Booting device in iOS simulator...
INFO
06:06
Opening exp://127.0.0.1:19000 in iOS simulator
ERROR
06:07
While resolving module `@assets/icons/app-icon.png`, the Haste package `@assets` was found. However the module `icons/app-icon.png` could not be found within the package. Indeed, none of these files exist:

  * `app-icon.png`
  * `/Users/mannyleon/Documents/Marketing/Clients/Visita Teziutlán/App/ListPro 1.3.5/source/assets/icons/app-icon.png/index(.native||.ios.expo.ts|.native.expo.ts|.expo.ts|.ios.expo.tsx|.native.expo.tsx|.expo.tsx|.ios.expo.js|.native.expo.js|.expo.js|.ios.expo.jsx|.native.expo.jsx|.expo.jsx|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.wasm|.native.wasm|.wasm)`
ERROR
06:07
Building JavaScript bundle: error

**Comment by leonmktg** [comment]
I fixed everything above but im still having a few display issues. 

1) When you go to the second section of the horizontal categories section. Some of them dont have titles. 
2) the banner images dont go to their respective categories. 

visitateziutlan.com

**Comment by leonmktg** [comment]
Now this!
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-01 at 16 40 19](https://user-images.githubusercontent.com/62923357/78193586-1656cf80-7438-11ea-9d68-ed4b156338c7.png)


When do you guys respond? I dont think it should take this long to get a response. Ive already sent my screenshot verification.

**Comment by minhcasi** [comment]
@leonmktg - this is cache from Expo app, try to remove the Expo SDK app and rebuild the app again

**Comment by leonmktg** [comment]
Ok, so how do i do this? how do i remove the expo SDK app? You should send instructions when telling someone to try something. Thank you

**Comment by luyx2412** [comment]
Hi @leonmktg You can uninstall expo app and click "Run on iOS simulator" or "Run on Android emulator" which will install expo app again and clear cache.
![image](https://user-images.githubusercontent.com/8909619/78420881-81ddae80-767d-11ea-8f58-80e2fda390d8.png)

Thanks

**Comment by leonmktg** [comment]
Now im getting this error

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-04 at 18 47 42](https://user-images.githubusercontent.com/62923357/78464361-bfeec880-76a5-11ea-9c9b-7dec98aea0c5.png)

**Comment by leonmktg** [comment]
What can be done about this SDK version. It says the author should update their experience to a newer expo sdk version.

**Comment by minhcasi** [comment]
@leonmktg - we are working on the update to the latest Expo version, the new release will be updated on the next couple of days - thank you!

**Comment by leonmktg** [comment]
when will the new version be out? I have to get this project going. Thank you!

**Comment by luyx2412** [comment]
HI @leonmktg We just updated new version to fix some issues and latest library. We will mention you on envato about it.

Thanks
