### ISSUE TITLE
[mstore-pro] Expo - products images not showing up, manual link not working

### ISSUE THREAD

**Issue by oikim** [inspireui/support#2497]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
I have keyed in the URL, API key and secret key - all is well connected, however, the product images are not shown or displayed in the products. Categories seem to be displaying well on both Android and iOS. Also, the logo_with_text.png is not showing up in iOS. It appears to be fine in Android. Also, the login with password to WooCommerce is not working and there is error of "No route was found matching the URL and request method" Kindly advise. Thank you. 

I had also tried to goto the link for manual, but it is no more available https://mstore.gitbooks.io/mstore-manual/content/chapter5.html. Kindly advise. 

2. Screenshots issues (required):
![image](https://user-images.githubusercontent.com/32124092/77998075-120cb280-7363-11ea-9edb-6785b96db923.png)

3. Proof of my purchased (required):
<img width="1055" alt="Screenshot 2020-03-31 at 3 04 26 PM" src="https://user-images.githubusercontent.com/32124092/77996864-05875a80-7361-11ea-8b50-5266235a0b33.png">

3. Config files (required)

**Comment by luyx2412** [comment]
Hi @oikim You can read the document in this link. https://docs.inspireui.com/mstore

Thanks

**Comment by oikim** [comment]
Noted with thanks. Seems like the api did the trick. Will read others from the manual. Will come back if there are further problems. 

Besides, can you advise if there is upgrade on this module as I see a lot of errors like following: 

 Expo  Press ? to show a list of all available commands.
Logs for your project will appear below. Press Ctrl+C to exit.
Finished building JavaScript bundle in 17683ms.

Require cycle: src/common/index.js -> src/common/Tools.js -> src/common/index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
- node_modules/expo/build/environment/muteWarnings.fx.js:18:23 in warn
- node_modules/metro/src/lib/polyfills/require.js:118:8 in metroRequire
* http://192.168.1.74:19001/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:165735:28 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:322:6 in loadModuleImplementation
* http://192.168.1.74:19001/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:137602:51 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:322:6 in loadModuleImplementation
* http://192.168.1.74:19001/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:136565:28 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:322:6 in loadModuleImplementation
* http://192.168.1.74:19001/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:136474:30 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:322:6 in loadModuleImplementation
* http://192.168.1.74:19001/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:134479:51 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:322:6 in loadModuleImplementation
* http://192.168.1.74:19001/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:123940:59 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:322:6 in loadModuleImplementation
- node_modules/expo/AppEntry.js:5:0 in <global>
- node_modules/metro/src/lib/polyfills/require.js:322:6 in loadModuleImplementation
- node_modules/metro/src/lib/polyfills/require.js:201:45 in guardedLoadModule
* http://192.168.1.74:19001/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:294433:4 in global code

Require cycle: src/store/configureStore.js -> src/redux/index.js -> src/redux/CountryRedux.js -> src/services/CountryWorker.js -> src/Omni.js -> src/store/configureStore.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
- node_modules/expo/build/environment/muteWarnings.fx.js:18:23 in warn
- node_modules/metro/src/lib/polyfills/require.js:118:8 in metroRequire
* http://192.168.1.74:19001/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:195004:59 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:322:6 in loadModuleImplementation
* http://192.168.1.74:19001/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:194941:26 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:322:6 in loadModuleImplementation
* http://192.168.1.74:19001/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:194841:58 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:322:6 in loadModuleImplementation
* http://192.168.1.74:19001/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:136496:34 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:322:6 in loadModuleImplementation
* http://192.168.1.74:19001/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:134479:51 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:322:6 in loadModuleImplementation
* http://192.168.1.74:19001/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:123940:59 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:322:6 in loadModuleImplementation
- node_modules/expo/AppEntry.js:5:0 in <global>
- node_modules/metro/src/lib/polyfills/require.js:322:6 in loadModuleImplementation
- node_modules/metro/src/lib/polyfills/require.js:201:45 in guardedLoadModule
* http://192.168.1.74:19001/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:294433:4 in global code

Require cycle: src/Omni.js -> src/services/FacebookAPI.js -> src/Omni.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
- node_modules/expo/build/environment/muteWarnings.fx.js:18:23 in warn
- node_modules/metro/src/lib/polyfills/require.js:118:8 in metroRequire
* http://192.168.1.74:19001/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:199207:26 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:322:6 in loadModuleImplementation
* http://192.168.1.74:19001/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:195018:57 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:322:6 in loadModuleImplementation
* http://192.168.1.74:19001/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:194941:26 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:322:6 in loadModuleImplementation
* http://192.168.1.74:19001/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:194841:58 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:322:6 in loadModuleImplementation
* http://192.168.1.74:19001/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:136496:34 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:322:6 in loadModuleImplementation
* http://192.168.1.74:19001/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:134479:51 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:322:6 in loadModuleImplementation
* http://192.168.1.74:19001/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:123940:59 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:322:6 in loadModuleImplementation
- node_modules/expo/AppEntry.js:5:0 in <global>
- node_modules/metro/src/lib/polyfills/require.js:322:6 in loadModuleImplementation
- node_modules/metro/src/lib/polyfills/require.js:201:45 in guardedLoadModule
* http://192.168.1.74:19001/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:294433:4 in global code

**Comment by luyx2412** [comment]
Hi @oikim This is warning to restructure the code. We will improve in next version. You can do it yourself. Are use expo version?

Thanks

**Comment by oikim** [comment]
Hi @luyx2412 , we use expo --**version 3.17.11**

**Still there is long waiting time between splash screen and home screen? I check connection on WooCommerce is no issue.** 

**Can you point to us how to "restructure the code"?** 

**Now I got new error which is stuck here in RED screen.** 

TypeError: undefined is not an object (evaluating 'data.images[0].src')

This error is located at:
    in PostLayout (at PostList/index.js:75)
    in RCTView (at FlatList.js:650)
    in RCTView (at VirtualizedList.js:1925)
    in CellRenderer (at VirtualizedList.js:767)
    in RCTView (at VirtualizedList.js:1156)
    in VirtualizedList (at FlatList.js:676)
    in FlatList (at PostList/index.js:164)
    in PostList (created by Context.Consumer)
    in ThemedComponent (created by withTheme(PostList))
    in withTheme(PostList) (created by ConnectFunction)
    in ConnectFunction (at HList.js:224)
    in RCTView (at HList.js:189)
    in HorizonList (created by Context.Consumer)
    in ThemedComponent (created by withTheme(HorizonList))
    in withTheme(HorizonList) (at HorizonList/index.js:110)
    in RCTView (at VirtualizedList.js:1925)
    in CellRenderer (at VirtualizedList.js:767)
    in RCTScrollContentView (at ScrollView.js:1038)
    in RCTScrollView (at ScrollView.js:1151)
    in ScrollView (at VirtualizedList.js:1183)
    in VirtualizedList (at FlatList.js:676)
    in FlatList (at createAnimatedComponent.js:151)
    in AnimatedComponent (at HorizonList/index.js:152)
    in HorizonList (created by Context.Consumer)
    in ThemedComponent (created by withTheme(HorizonList))
    in withTheme(HorizonList) (created by Context.Consumer)
    in withNavigation(withTheme(HorizonList)) (created by ConnectFunction)
    in ConnectFunction (at Home/index.js:54)
    in RCTView (at Home/index.js:52)
    in Home (created by ConnectFunction)
    in ConnectFunction (created by Context.Consumer)
    in ThemedComponent (created by withTheme(Connect(Home)))
    in withTheme(Connect(Home)) (at HomeScreen.js:72)
    in HomeScreen (created by Context.Consumer)
    in ThemedComponent (created by withTheme(HomeScreen))
    in withTheme(HomeScreen) (created by SceneView)
    in SceneView (at StackViewLayout.tsx:900)
    in RCTView (at createAnimatedComponent.js:151)
    in AnimatedComponent (at StackViewCard.tsx:106)
    in RCTView (at createAnimatedComponent.js:151)
    in AnimatedComponent (at screens.native.js:100)
    in Screen (at StackViewCard.tsx:93)
    in Card (at createPointerEventsContainer.tsx:95)
    in Container (at StackViewLayout.tsx:975)
    in RCTView (at screens.native.js:131)
    in ScreenContainer (at StackViewLayout.tsx:384)
    in RCTView (at createAnimatedComponent.js:151)
    in AnimatedComponent (at StackViewLayout.tsx:374)
    in PanGestureHandler (at StackViewLayout.tsx:367)
    in StackViewLayout (created by withOrientation)
    in withOrientation (at StackView.tsx:104)
    in RCTView (at Transitioner.tsx:267)
    in Transitioner (at StackView.tsx:41)
    in StackView (created by Navigator)
    in Navigator (created by KeyboardAwareNavigator)
    in KeyboardAwareNavigator (created by SceneView)
    in SceneView (created by TabNavigationView)
    in RCTView (created by ResourceSavingScene)
    in RCTView (created by ResourceSavingScene)
    in ResourceSavingScene (created by TabNavigationView)
    in RCTView (at screens.native.js:131)
    in ScreenContainer (created by TabNavigationView)
    in RCTView (created by TabNavigationView)
    in TabNavigationView (created by NavigationView)
    in NavigationView (created by Navigator)
    in Navigator (created by NavigationContainer)
    in NavigationContainer (at Router.js:122)
    in RCTView (at Router.js:111)
    in RCTView (at createAnimatedComponent.js:151)
    in AnimatedComponent (at react-native-drawer/index.js:713)
    in RCTView (at react-native-drawer/index.js:700)
    in Drawer (at MenuOverlay.js:37)
    in MenuOverlay (created by Context.Consumer)
    in ThemedComponent (created by withTheme(MenuOverlay))
    in withTheme(MenuOverlay) (created by ConnectFunction)
    in ConnectFunction (at Router.js:108)
    in ThemeProvider (at Router.js:107)
    in Router (created by ConnectFunction)
    in ConnectFunction (at App.js:101)
    in PersistGate (at App.js:100)
    in Provider (at App.js:99)
    in App (at withExpoRoot.js:26)

**Comment by luyx2412** [comment]
Hi @oikim we will update and restructure code in next version. Or you can switch to use React native original version which will faster than expo version.

Thanks
