### ISSUE TITLE
Issues while building the Fluxstore App for Opencart Site. 

### ISSUE THREAD

**Issue by pustakmandi-developer** [inspireui/support#2498]
Hello Team,

There are following issues coming while building the Fluxstore App with Opencart Site. 

1. Product Layout type is not getting accepted for Opencart
2. Language is not getting resolved
3. Getting following errors:
4:59	Load Settings
			Cannot load settings from file 'C:\Users\Vipul.Madhani\.pub-cache\hosted\pub.dartlang.org\video_player_web-0.1.2+1\android\video_player_web.iml': File C:\Users\Vipul.Madhani\.pub-cache\hosted\pub.dartlang.org\video_player_web-0.1.2+1\android\video_player_web.iml does not exist
			Please correct the file content

14:59	Load Settings
			Cannot load settings from file 'C:\Users\Vipul.Madhani\.pub-cache\hosted\pub.dartlang.org\wakelock-0.1.3+4\android\wakelock.iml': File C:\Users\Vipul.Madhani\.pub-cache\hosted\pub.dartlang.org\wakelock-0.1.3+4\android\wakelock.iml does not exist
			Please correct the file content

Attaching the images to show more the the issues. 

![WhatsApp Image 2020-03-31 at 3 07 14 PM](https://user-images.githubusercontent.com/56787208/78012193-42a01c80-7362-11ea-80dd-827465886ab4.jpeg)
![WhatsApp Image 2020-03-31 at 3 07 14 PM (1)](https://user-images.githubusercontent.com/56787208/78012206-459b0d00-7362-11ea-891e-e1afcf2899f3.jpeg)
![Issue 1](https://user-images.githubusercontent.com/56787208/78012241-5186cf00-7362-11ea-80d2-5542efb6452b.png)
![Issue 2](https://user-images.githubusercontent.com/56787208/78012246-52b7fc00-7362-11ea-98af-2e55804a0145.png)
![Issue 3](https://user-images.githubusercontent.com/56787208/78012247-53509280-7362-11ea-95f6-9180c8cf4bd6.png)

**Comment by minhcasi** [comment]
Hi, thank you for the feedback. Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads it's used to verify your proof of purchase? 
Sorry for any inconvenience, we will reopen the ticket when it is verified, thank you!

**Comment by pustakmandi-developer** [comment]
![image](https://user-images.githubusercontent.com/56787208/78021325-a6314680-7370-11ea-8cac-b03a62e74174.png)

**Comment by pustakmandi-developer** [comment]
Waiting for update. Its been 17 hours.

**Comment by pustakmandi-developer** [comment]
ANyone there. Its bee 2 days.

**Comment by minhcasi** [comment]
@pustakmandi-developer - sorry for the late response as we could not see your latest comment 

We will release new version on tomorrow to fix the config on Opencart, it seems the team using missing config, you can try to keep the original config.dart and only replace the serverConfig section with new Opencart setting - thank you!

**Comment by pustakmandi-developer** [comment]
SUre. WIll wait on same. Also i wanted to know how to set up Git repository. Everytime you release new version I have to discard old one. How can i launch app and whenever new version comes, then update accordingly. Please guide.

**Comment by minhcasi** [comment]
@pustakmandi-developer - please update the latest 1.6.6 to fix build issue - thank you!

You can set up the local git by using some git command or using the Source Tree - some document here could be helped - https://help.github.com/en/github/importing-your-projects-to-github/adding-an-existing-project-to-github-using-the-command-line

Let us know if you have any questions ☺️

**Comment by pustakmandi-developer** [comment]
I will upload the project. But how can i compare the changes in that. Please guide.
