### ISSUE TITLE
[FluxStore-MV] -  Multipayment checkout

### ISSUE THREAD

**Issue by marknestor261** [inspireui/support#2499]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: Hello. Multipayment checkout on my app loads the checkout form but can't checkout. Checkout button is not there. Just a round blue button that doesn't work.

2. Screenshots issues (required):
![Screenshot_20200331-134842](https://user-images.githubusercontent.com/46901102/78019087-bc7ed880-7357-11ea-8c87-9a3f0dc460c6.png)

3. Proof of my purchased (required):
![Screenshot_20200331-140010](https://user-images.githubusercontent.com/46901102/78019244-010a7400-7358-11ea-802f-3b5ff1f349e2.png)

3. Config files (required)

**Comment by marknestor261** [comment]
Also store name in product description is not working. Can't see the store name.

**Comment by minhtruong315** [comment]
@marknestor261 send me full your source code via email: truong@inspireui.com with subject: 2499
and admin account as well

**Comment by marknestor261** [comment]
Hello @minhtruong315 i have sent the source code and admin credentials to your email truong@inspireui.com. Please check

**Comment by minhtruong315** [comment]
@marknestor261 pls update the version 1.6.6 then try again and let me know the result
