### ISSUE TITLE
console log issue 

### ISSUE THREAD

**Issue by kiamoz** [inspireui/support#25]
Dear support , in mstore pro ver 

![screen shot 2018-11-19 at 2 32 23 pm](https://user-images.githubusercontent.com/10494372/48703226-5123e300-ec08-11e8-95be-d1133cc76c87.png)
![screen shot 2018-11-19 at 2 32 35 pm](https://user-images.githubusercontent.com/10494372/48703228-51bc7980-ec08-11e8-97cb-dc7337382f77.png)

nothing chnage to see log in chorome !

**Comment by luyx2412** [comment]
Hi @kiamoz Please check in Constants.js file change field `useReactotron: true` to open Reactotron.
 Thanks

**Comment by kiamoz** [comment]
Dear support I just want to disable useReactotron , I just use console.log az normally

**Comment by kiamoz** [comment]
and after set false the useReactotron I got this  error 
<img width="656" alt="screen shot 2018-11-20 at 8 21 52 am" src="https://user-images.githubusercontent.com/10494372/48752220-6139d200-ec9d-11e8-8130-5b6df79312da.png">

**Comment by luyx2412** [comment]
Hi @kiamoz Please uninstall app on your simulator device and install again. I just test which working normal. And please follow the document https://facebook.github.io/react-native/docs/debugging#chrome-developer-tools. If debugger-ui do not open. Open manual with url http://localhost:8081/debugger-ui/ .Thanks

**Comment by kiamoz** [comment]
nothing changed ! I clear all content and setting in simulator , it's still connect to Reacttotron !
see the screen shot
![screen shot 2018-11-20 at 10 43 49 am](https://user-images.githubusercontent.com/10494372/48757249-57ba6500-ecb1-11e8-9197-923e4584a1e8.png)

**Comment by kiamoz** [comment]
yes thank you 
256 077 121
5248
