### ISSUE TITLE
[FluxStore-Woocommerce] Question about editing

### ISSUE THREAD

**Issue by spetsglaz** [inspireui/support#2501]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your 
1. My issue:

 i would like to change the whole background from the standard white color to a picture, how would i be able to do this? And is it possible to change the icons from the side bar menu, example of icons i would like to change : Icon(FontAwesomeIcons.wordpress or Icons.blur_on. Thank you for the help :)

2. Screenshots issues (required):

3. Proof of my purchased (required):
5bf0aaa7-fbf8-46f5-bc29-ea204a02772b

3. Config files (required)

**Comment by philipvu30** [comment]
Hi @spetsglaz ,

May I ask what FluxStore version are you using? Pro/Woo or MultiVendor?

**Comment by spetsglaz** [comment]
Hello, I am using FluxStore woo-1.6.5

<img width="356" alt="Skärmavbild 2020-04-01 kl  18 31 12" src="https://user-images.githubusercontent.com/62562826/78162772-a8b29f80-7447-11ea-9b86-97b1b68a0614.png">

I would love to know how to change the icons in the color red, to change the white background in the pink( and the shirt,tie,bag etc. icons) and how to change the white background in the blue 

Thank you :)

**Comment by minhcasi** [comment]
@spetsglaz - please try to use the Inspector from Android Studio, you can change it super easy with this tool, for more info - please check out - https://docs.inspireui.com/fluxstore/customization/#1-how-to-customize-any-ui-from-app
