### ISSUE TITLE
[FluxStore-MV] white screen

### ISSUE THREAD

**Issue by spetsglaz** [inspireui/support#2503]
1. My issue:
Hello, when i open my app it is all white, i followed all the instructions but still managed to get this error. This is a ASAP inquiry.

2. Screenshots issues (required):

3. Proof of my purchased (required):
ec7f9b1c-0996-4c71-8a53-1bd4f2159511

3. Config files (required)

**Comment by trunghieuvn** [comment]
please provide version you use?
and can send for me screenshot or video issue?
thanks

**Comment by spetsglaz** [comment]
My version : Fluxstore vendor 1.6.5

<img width="354" alt="Skärmavbild 2020-04-01 kl  18 24 19" src="https://user-images.githubusercontent.com/62562826/78161729-342b3100-7446-11ea-9fe1-ce1ebe772b8f.png">

It works with the android emulator but not with the ios simulator
How do i send you the required folders?

**Comment by trunghieuvn** [comment]
i see issue, i investigate and i will reply for you.

**Comment by trunghieuvn** [comment]
To fix this error please follow these steps:

Step 1: remove the `build folder`

![image](https://user-images.githubusercontent.com/19247680/78330328-f5b08600-75ad-11ea-928e-5f73713229cd.png)

Step 2: call `flutter clean`
Step 3: Go to the ios folder in the project, open the file `Runner.xcworkspace` with xcode.
Step 4: Select Runner -> Build Phase -> Thin Binary

![image](https://user-images.githubusercontent.com/19247680/78330238-b5e99e80-75ad-11ea-9bea-33dac1ea309c.png)

Step 5: Modify Thin Binary to:

```
/bin/sh "$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" embed
/bin/sh "$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" thin
```

![image](https://user-images.githubusercontent.com/19247680/78330210-a702ec00-75ad-11ea-9e32-3f7542f0b8ef.png)

Step 6: Run Build in Xcode

**Comment by minhcasi** [comment]
@spetsglaz - please use the latest 1.6.6 version will be fixed the issue - thank you!
