### ISSUE TITLE
error Expo

### ISSUE THREAD

**Issue by bakerkabaha** [inspireui/support#2504]
![5e7749e4a1a04](https://user-images.githubusercontent.com/60016194/78064124-eeb12a00-7399-11ea-8f35-ea779a0d6cbe.jpg)

**Comment by minhcasi** [comment]
Hi, thank you for the feedback. Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads it's used to verify your proof of purchase? 
Sorry for any inconvenience, we will reopen the ticket when it is verified, thank you!
