### ISSUE TITLE
[FluxNews] - Can´t get any post

### ISSUE THREAD

**Issue by patriciocifuentes** [inspireui/support#2505]
1. My issue:
    I think already connect with my wordpress site ( https://educandog.xpresivo.in ) because take the name that i change in config.json. Already (of course ) install the plugins. But the app don't show any post that i have in the website, in the page of categories shows a error.

2. Screenshots issues (required):
   
<img width="1680" alt="error-nomuestra" src="https://user-images.githubusercontent.com/488461/78069403-4a0df880-7357-11ea-90e2-71d4f6d6620b.png">

<img width="1680" alt="error-texto" src="https://user-images.githubusercontent.com/488461/78069436-572ae780-7357-11ea-84c7-d23ac3de6fa9.png">

3. Proof of my purchased (required):
    
<img width="1680" alt="comprado" src="https://user-images.githubusercontent.com/488461/78069339-29de3980-7357-11ea-8e54-eb9ae5b95c15.png">

3. Config files (required)
    
[modified-files.zip](https://github.com/inspireui/support/files/4411277/modified-files.zip)

**Comment by patriciocifuentes** [comment]
I am willing to change the WordPress theme if necessary, could you tell me which one to use to guarantee the operation?

**Comment by patriciocifuentes** [comment]
I answer myself: the WordPress permalink (Settings> Permalinks) must be the active option "Post name"; just work with this option.

Put these instructions in your documents because not all people who buy your product have to know this and thus not waste their time looking everywhere for something so minimal

**Comment by minhcasi** [comment]
@patriciocifuentes - appreciated for your help and sharing - we will update the document for this section

**Comment by minhcasi** [comment]
it's updated - thank you
