### ISSUE TITLE
[Fluxstore Pro] Payment page problem.

### ISSUE THREAD

**Issue by unaluslusoy** [inspireui/support#2506]
The application does not operate on mstore-api on the payment page. I followed the instructions described in the documentation section. I tried to explain the problem we had as a video.` 
[Video](https://youtu.be/p8b-P--YukM)

**Comment by unaluslusoy** [comment]
> The application does not operate on mstore-api on the payment page. I followed the instructions described in the documentation section. I tried to explain the problem we had as a video.` 
> [Video](https://youtu.be/p8b-P--YukM)

Purchase image:https://trello-attachments.s3.amazonaws.com/5873ef061fda2b7f05ffc772/5e83e48a784762838ad54af4/40b0dcb049cde1b27841302d62c74c65/Screenshot_2020-04-01-03-45-11-771_com.android.chrome.jpg

**Comment by alicankarakus** [comment]
üstad problemi çözebilirsen haber verirsen sevinirim.  buradan takip ediyorum bende. Ödeme sistemiyle alakalı sanırım bizden yana bir problem olacak. Paypal gibi bir ödeme sistemi dışında Türkiye'de kullanılan hiç bir ödeme sistemi içerde çalışmayı desteklemiyor. Oturup yazmak gerekecek sanırım mesela iyzico için. 

Woocommerce mi opencart mı kullanıyorsun

**Comment by unaluslusoy** [comment]
Merhaba Alican Bey,
Woocommerce kurulum gerçekleştirdim. Ama söyle bir yöntem ile iyzico
problemi çözülebilir diye düşünüyorum. Webview mantığı ile ödeme
alınabilir. Bu hususta biraz kastırmayı düşünüyorum. yoksa dediğiniz gibi
uygulama mantığına uygun iyzico entegrasyonu gerekebilir.



[image: Logo] <https://timeon.digital/>
Ünal USLUSOY
IT & Web Devoloper | TimeOn Digital
m: +90 505 115 3408
p: +90 850 840 9693
e: unaluslusoy@todestek.net
Cevizli Mahallesi, Hukukçular Towers, Mustafa Kemal Cd. D:A Blok No:33,
34865 Kartal/İstanbul
timeon.digital
[image: linkedin icon]
<https://tr.linkedin.com/in/%C3%BCnal-uslusoy-a818306a>


alicankarakus <notifications@github.com>, 2 Nis 2020 Per, 17:38 tarihinde
şunu yazdı:

**Comment by alicankarakus** [comment]
Cevabınız için teşekkürler. Webview mantığı burada işimize yaramayacak gibi gözüküyor. Dart dilinde bir geliştirme sağlanarak Türkiye'deki ilklerden birisi olunabilir ve bu nakite çok rahat dönüştürülebilir.

**Comment by unaluslusoy** [comment]
Rica ederim. Webview mantığını söyle düşündüm, uygulama mstore.api
üzerinden kişinin sipariş bilgilerini alıyor. Yani uygulama ile
haberleşmeyi sağlayan kısım o. İçindeki kodları inceledim Bu kısımı iyzico
ile haberleştirirsek konu çözülür sanırım. Önce çözülmesi gereken kısım
ödeme kısmındaki yönlendirdiği sayfa o kısmı çözebilirler diğer aşamaya
geçmiş olacağız inşallah.

dilerseniz bana bu mail adresinden ulaşabilirsiniz :unaluslusoy@todestek.net

alicankarakus <notifications@github.com>, 2 Nis 2020 Per, 20:40 tarihinde
şunu yazdı:

**Comment by alicankarakus** [comment]
Ben iyzico ile iletişime geçtim. Dart ile alakalı hiç bir düşünceleri yok. Geliştirme planlarında yok. Ekstra bir destek yok. İletişimdeki adam dart ile alakalı hiç birşey bile bilmiyor..

**Comment by minhcasi** [comment]
Hi, do you guys could figure out any solutions so far 😅

Please update the latest 1.6.6 to see if it can be fixed, we also note the detail on this changelog blog - https://medium.com/@inspireui/announcing-fluxstore-1-6-337efff1791f - thank you!

**Comment by unaluslusoy** [comment]
I'm doing the update now. I will examine and give information.

**Comment by unaluslusoy** [comment]
Hello @minhcasi,

Application tested the current version. Below is the vided link of the problem parts.
Issue 1: When you choose Bank Eft payment and continue, the screen remains.
Problem 2: I get some errors in darts analytics. There were no such errors in the previous version.

I would like you to make a quick return on the subject. I don't want to waste a lot of time on this project. Thank you.

[Video Link](https://youtu.be/S0i2DxL9B2s)

**Comment by minhcasi** [comment]
@unaluslusoy - please help to try the new Payment webview from latest 1.6.6b - thank you!

**Comment by unaluslusoy** [comment]
@minhcasi - Hello, I couldn't understand well what you asked for. Can you give more detailed information? I'd like to help. thank you!

**Comment by minhtruong315** [comment]
@unaluslusoy send me full your source code via email: truong@inspireui.com with subject: https://github.com/inspireui/support/issues/2506
I will help u check the issue

**Comment by minhtruong315** [comment]
@unaluslusoy I can't order on your website. can u fix it?

**Comment by unaluslusoy** [comment]
@minhtruong315 Would you like me to correct your website order page?

**Comment by unaluslusoy** [comment]
@minhtruong315  - order page previous = [orders] Update = [order] Current version is as in the photo. I can share admin information.

![image](https://user-images.githubusercontent.com/31100257/78552711-a7e78800-7810-11ea-82e0-56d821eb8665.png)

**Comment by unaluslusoy** [comment]
@minhtruong315 - Hello Can you give information about the latest situation?

**Comment by minhtruong315** [comment]
@unaluslusoy I checked your source code. it's working well with payment webview. please look the video
https://www.dropbox.com/s/ahwdycijb4w7asf/checkout.mov?dl=0
I sent you updates to your email to fix errors in darts analytics

**Comment by unaluslusoy** [comment]
@minhtruong315 -Thank you. I will review and return.

**Comment by unaluslusoy** [comment]
@minhtruong315- Thanks for darts analytics. I have mentioned below regarding another problem.

Issue 1: I get a username and password error on the Application Login screen. In the web page management section, user is added but cannot login
Issue 2: I get an error on the user registration screen. (message comes out because I have no trace.)

I shared the image about the registration screen.


![image](https://user-images.githubusercontent.com/31100257/79042962-a9e08b00-7c04-11ea-9570-b1f3a0737729.png)

**Comment by minhtruong315** [comment]
@unaluslusoy can u translate the Exception message? I don't understand your language.

**Comment by unaluslusoy** [comment]
@minhtruong315 - Error message on the screen: sorry, you are not allowed to do this.

I ask you to look at the error from Android Studio Terminal. There is a warning about the method.

**Comment by minhtruong315** [comment]
@unaluslusoy check this solution https://github.com/inspireui/support/issues/2690#issuecomment-612721558

**Comment by unaluslusoy** [comment]
> bu çözümü #2690 @unaluslusoy kontrol [edin (yorum)](https://github.com/inspireui/support/issues/2690#issuecomment-612721558)

@minhtruong315 -The link you shared provided a solution to my problem. thank you.

**Comment by unaluslusoy** [comment]
@minhtruong315 - I added the files you sent. I did the test, but the problem persists.

I am using the latest version of Flutter SDK.

![image](https://user-images.githubusercontent.com/31100257/79225961-3d64c680-7e66-11ea-8708-d7a332877d9d.png)

**Comment by minhtruong315** [comment]
@unaluslusoy you can try to clean project then run again
https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

**Comment by unaluslusoy** [comment]
@minhtruong315 -I followed the methods you recommended. But nothing changed. The problem I mentioned continues.

**Comment by minhtruong315** [comment]
@unaluslusoy add my skype: minhtruong315
I will you run the project

**Comment by unaluslusoy** [comment]
@minhtruong315 - I added Skype.

**Comment by minhtruong315** [comment]
I dont see. pls ping me on the skype

**Comment by atakancelik** [comment]
Hi, did you find any solution ?
