### ISSUE TITLE
[Fluxstore Woocommerce] - Issue with homepage product images, Variable Products, Blog

### ISSUE THREAD

**Issue by gabe72** [inspireui/support#2507]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:

2. Screenshots issues (required):

3. Proof of my purchased (required):

3. Config files (required)

**1)My Issue**

1) Variable products the options don't show
2) Product Images on the homepage, not all are shown, Product images are shown when going into a product
3) Blog is throwing error on click
4) On every product page Sale100%  Badge is showing and doesn't show list price

**2) SCreenshot ISSUes**
![image](https://user-images.githubusercontent.com/42904245/78091125-b5a0a600-73e9-11ea-9d2c-5fb9ebf11ecf.png)
Not all images showing on Home

![image](https://user-images.githubusercontent.com/42904245/78091188-d0731a80-73e9-11ea-87c9-cc4bc22c243a.png)
Images are there when entering product page, only 1 or 2 don't show

![image](https://user-images.githubusercontent.com/42904245/78091300-07e1c700-73ea-11ea-9cd6-731993b52f5c.png)
This is a variable product but I cant see the options to select

![image](https://user-images.githubusercontent.com/42904245/78091385-424b6400-73ea-11ea-8e55-4936a1c4bbe9.png)
In your Docs the below image throws error on box invalid int assigned

![image](https://user-images.githubusercontent.com/42904245/78091434-6a3ac780-73ea-11ea-89f6-9c379dc23bdd.png)
Blog Error

**3)Proof Of Purchase**

![image](https://user-images.githubusercontent.com/42904245/78090623-41b1ce00-73e8-11ea-8e89-a29ba7c1616f.png)

**4) Config FIle**
I am using the default one, attached below

{
  "HorizonLayout": [
    {
      "layout": "logo",
      "showMenu": true,
      "showSearch": true
    },
    {
      "layout": "category",
      "type": "icon",
      "wrap": false,
      "size": 1.0,
      "radius": 50.0,
      "items": [
        {
          "category": 95,
          "image": "https://user-images.githubusercontent.com/1459805/62820029-2e679f00-bb88-11e9-80de-fdf115cfd942.png",
          "colors": [
            "#3CC2BF",
            "#3CC2BF"
          ],
          "originalColor": false
        },
        {
          "category": 109,
          "image": "assets/icons/categories/ic_dress.png",
          "colors": [
            "#3E6AB5",
            "#3E6AB5"
          ]
        },
        {
          "category": 90,
          "image": "assets/icons/categories/ic_shorts.png",
          "colors": [
            "#53A2CC",
            "#53A2CC"
          ]
        },
        {
          "category": 186,
          "image": "assets/icons/categories/ic_glasses.png",
          "colors": [
            "#53688A",
            "#53688A"
          ]
        },
        {
          "category": 29,
          "image": "assets/icons/categories/ic_tie.png",
          "colors": [
            "#43506A",
            "#43506A"
          ]
        },
        {
          "category": 30,
          "image": "assets/icons/categories/ic_panties.png",
          "colors": [
            "#12B58C",
            "#12B58C"
          ]
        }
      ]
    },
    {
      "layout": "bannerImage",
      "isSlider": true,
      "autoPlay": false,
      "showNumber": false,
      "design": "default",
      "showBackGround": true,
      "radius": 2.0,
      "items": [
        {
          "category": 95,
          "image": "https://user-images.githubusercontent.com/1459805/59846818-12672e80-938b-11e9-8184-5f7bfe66f1a2.png",
          "padding": 15.0
        },
        {
          "category": 109,
          "image": "https://user-images.githubusercontent.com/1459805/60091575-1f12ca80-976f-11e9-962c-bdccff60d143.png",
          "padding": 15.0
        },
        {
          "product": 90,
          "image": "https://user-images.githubusercontent.com/1459805/60091808-a19b8a00-976f-11e9-9cc7-576ca05c2442.png",
          "padding": 15.0
        }
      ]
    },
    {
      "layout": "bannerImage",
      "items": [
        {
          "url": "https://inspireui.com",
          "image": "https://user-images.githubusercontent.com/1459805/59846820-12672e80-938b-11e9-8fa6-b331b7db331d.png",
          "padding": 5.0
        }
      ]
    },
    {
      "layout": "bannerImage",
      "items": [
        {
          "category": 18,
          "image": "https://user-images.githubusercontent.com/1459805/59846823-12ffc500-938b-11e9-8d93-65ead3d6b1dd.png",
          "padding": 5.0
        },
        {
          "category": 23,
          "image": "https://user-images.githubusercontent.com/1459805/59846824-12ffc500-938b-11e9-8d5a-fc42cb1b7658.png",
          "padding": 5.0,
          "featured": true
        }
      ]
    },
    {
      "name": "Recent View",
      "layout": "recentView"
    },
    {
      "name": "Woman Collections",
      "image": "",
      "layout": "threeColumn",
      "category": 95,
      "isSnapping": true
    },
    {
      "name": "Man Collections",
      "image": "",
      "layout": "twoColumn",
      "category": 109,
      "isSnapping": true
    },
    {
      "name": "Kids Collections",
      "layout": "listTile",
      "category": 90
    },
    {
      "name": "Our Blog Posts",
      "layout": "blog"
    },
    {
      "name": "New Collections",
      "layout": "staggered",
      "limit": 20,
      "category": 29
    }
  ],
  "Setting": {
    "MainColor": "#fab3a3",
    "ProductListLayout": "list"
  },
  "TabBar": [
    {
      "layout": "home",
      "label": "Home",
      "icon": "assets/icons/tabs/icon-home.png"
    },
    {
      "layout": "category",
      "label": "Category",
      "categoryLayout": "card",
      "icon": "assets/icons/tabs/icon-category.png"
    },
    {
      "layout": "search",
      "label": "Search",
      "icon": "assets/icons/tabs/icon-search.png"
    },
    {
      "layout": "cart",
      "label": "Cart",
      "icon": "assets/icons/tabs/icon-cart2.png"
    },
    {
      "layout": "profile",
      "label": "Setting",
      "icon": "assets/icons/tabs/icon-user.png"
    }
  ],
  "searchSuggestion": [
    "man",
    "dress",
    "Stitch",
    "ma"
  ]
}

**Comment by philipvu30** [comment]
Hi @gabe72 ,

Please send your config.dart (consumer key + secret key included) to this email: toan@inspireui.com

Thank you.

**Comment by gabe72** [comment]
Hi @philipvu30 
Thanks for your reply, I have sent the mail.

**Comment by philipvu30** [comment]
Hi @gabe72 ,
Issue 1: 
- Please make sure you have checked these 2 options.
![image](https://user-images.githubusercontent.com/54442328/78120381-0e952c00-7434-11ea-9f5b-bb778244d55e.png)

Issue 2: 
- Because some images do not show up or exist, so the app cannot load the image. Please consider changing or checking your image url.
![image](https://user-images.githubusercontent.com/54442328/78120153-aa726800-7433-11ea-9064-4bb36d25483d.png)

Issue 3 and 4: Currently investigating. I'll let you know when it's done.

Thanks.

**Comment by gabe72** [comment]
Hi there, Relating Issue 2 is that all the images which have error they are available in jpg format not jpeg is there a way this can be done?

**Comment by philipvu30** [comment]
> Hi there,
> So my images are first minified by ewww image compressor plugin and then goes to jetpack servers for hosting.
> The issue 2 in which all the images have error they are available in jpg format, not jpeg is there a way the images can be fetched in jpg?

Hi @gabe72 ,

I sent the new lib folder via email. Please update your source code and pubspec.yaml
It should fixed these issues:  3 and 4.
If I change all incoming images from jpeg -> jpg then there will be some images not show up.

**Comment by gabe72** [comment]
Hi i just tested issue 4 still persists and for issue 1 i enabled it for 1 product and on that product its till not showing variants

**Comment by gabe72** [comment]
So relating to my images issue not showing can we change the image used to be any of these under as see for every image these ones are generated

![image](https://user-images.githubusercontent.com/42904245/78203437-96227f80-74b4-11ea-8a5b-8dd0f1df3eae.png)

**Comment by gabe72** [comment]
Hi @philipvu30 any update of the same?

**Comment by philipvu30** [comment]
Hi,

I have tried everything but if I change all image to jpg or jpeg then some will not be shown.
Have you installed this plugin and used it?
![image](https://user-images.githubusercontent.com/54442328/78355110-5a340b00-75d7-11ea-974a-24f7384e1c9f.png)

**Comment by gabe72** [comment]
Hi,

I updated the same only the blog was solved rest still persist

**Comment by minhcasi** [comment]
@gabe72 - could you try to download latest version 1.6.6 - thanks

**Comment by gabe72** [comment]
Hi @minhcasi So many issues got sorted via the update. 
However, in the images there is still an issue, is there a way I can get only jpg images, not jpeg!
As I tested I have all images in all sizes in jpg

**Comment by minhcasi** [comment]
I'm sorry for the build issue, please help to download the latest 1.6.6b, please help to update this package to fix some build issue as well.

**Comment by gabe72** [comment]
Hi @minhcasi so the issues i had were fixed with the release of the build. However I am having an issue with some images for the products. So in the android studio it  shows underneath screenshot

![image](https://user-images.githubusercontent.com/42904245/78503895-25ff4c80-7787-11ea-8f12-85a4514df750.png)


However, if you take all the URLs under which are shown in the screenshot

https://i2.wp.com/gashena.com/wp-content/uploads/2019/08/0-9c1134-medium.jpeg?fit=600%2C600&ssl=1

https://i0.wp.com/gashena.com/wp-content/uploads/2019/12/0-81bd77-medium.jpeg?fit=800%2C800&ssl=1.

https://i0.wp.com/gashena.com/wp-content/uploads/2019/12/0-81bd77-medium.jpeg?fit=800%2C800&ssl=1.

They will show error however if you remove **"-medium"** the images are fine.
Eg:-
https://i0.wp.com/gashena.com/wp-content/uploads/2019/12/0-81bd77.jpeg?fit=800%2C800&ssl=1
So is there a way to remove this **"-meduim"** from the image URL? 
As I am sure its coming from the APP config files. As my website has each image in any size you want.

**Comment by philipvu30** [comment]
As I have said, your images is not consistent.

Here is the file I have modified to replace all jpeg -> jpg.


[tools.zip](https://github.com/inspireui/support/files/4435778/tools.zip)

**Comment by gabe72** [comment]
Hi @philipvu30 

Thanks for the response,
I replaced the tools.dart and all pictures for all products show. But for a few products after adding to the cart. the images don't come. 
and for as my previous message, I think you didn't understand fully. Please see the screenshots below.

![image](https://user-images.githubusercontent.com/42904245/78522959-c3d93280-77ec-11ea-8eff-0ce19f90654e.png)

**If there is a way to remove this "-medium" from the image URL it will solve all issues and wouldn't need fetching jpg images only.**

**Comment by philipvu30** [comment]
Hi,

You could try this file as I have modified it according to your suggestion

[tools.zip](https://github.com/inspireui/support/files/4435857/tools.zip)

**Comment by gabe72** [comment]
Hi @philipvu30 

Thanks for the quick response, this setting works perfectly no image is giving errors :).

Thanks a ton. 

Just have a Few Questions 
Q1) How can I maintain this same setting, even after you release updates?
Q2) How to set colors for variants?
![image](https://user-images.githubusercontent.com/42904245/78524107-9c846480-77f0-11ea-863f-fece3431f218.png)

Q3) How to change the max limit of price filter? Right now it's only 1000
![image](https://user-images.githubusercontent.com/42904245/78524140-b7ef6f80-77f0-11ea-9e24-7a4490e6933a.png)

**Comment by philipvu30** [comment]
Hi @gabe72 ,

Question 1: Please submit to this form, we'll give you access to our GitLab, then you will find out which files are modified in the update. [Form](https://docs.google.com/forms/d/e/1FAIpQLSeuBqUkScy42V7KKhfNPj0fl581anrB1mWkbMa3p2WQt7fhfw/viewform)

Question 2: You can add colors for variation in this file lib/common/constants/colors.dart

![image](https://user-images.githubusercontent.com/54442328/78524980-ecb6f300-77ff-11ea-8e0e-a4275fc92892.png)

If you are happy with my support, please consider rating us on your download page. Thank you.

**Comment by gabe72** [comment]
hi @philipvu30 
Thanks for the help. Really appreciate it, Left a feedback.
Also I Submitted the form in Question1 thanks

**Comment by gabe72** [comment]
Hi @philipvu30  @minhcasi 
While setting up firebase account The documentation given doesn't have the required files.
So I am following the video linked under
https://www.youtube.com/watch?v=C_9mk_MmvOQ&feature=emb_logo

However at 04:09 Min you are using a firebase folder from where to get this folder?

**Comment by philipvu30** [comment]
Hi,

Here is the requested [folder](https://github.com/inspireui/support/files/4441953/firebase.zip). Sorry we did not include it.

**Comment by philipvu30** [comment]
Closed as no response.
