### ISSUE TITLE
Fluxstore 1.6.5c Blank Screen on debug

### ISSUE THREAD

**Issue by Isodie** [inspireui/support#2508]
Purchase code 
5b81a1f1-b6f8-41d7-a4a8-169532748691

Hi I downloaded Latest 1.6.5c
added to vscode and ran debug on ios simulator
and there just blank white screen with following bug in debug console.

Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
Xcode build done.                                           22.9s
	path: satisfied (Path is satisfied), interface: en0
Failed to find assets path for "Frameworks/App.framework/flutter_assets"
Configuring the default Firebase app...
	path: satisfied (Path is satisfied), interface: en0
	path: satisfied (Path is satisfied), interface: en0
Configured the default Firebase app __FIRAPP_DEFAULT.
[VERBOSE-2:engine.cc(127)] Engine run configuration was invalid.
[VERBOSE-2:shell.cc(437)] Could not launch engine with configuration.
	path: satisfied (Path is satisfied), interface: en0
    "currentDataServiceDescriptorChanged:",
    "carrierBundleChange:",
    "cellChanged:cell:",
    "connectionStateChanged:connection:dataConnectionStatusInfo:",
    "signalStrengthChanged:info:"
)
    "currentDataServiceDescriptorChanged:",
    "carrierBundleChange:",
    "cellChanged:cell:",
    "connectionStateChanged:connection:dataConnectionStatusInfo:",
    "signalStrengthChanged:info:"
)
    "currentDataServiceDescriptorChanged:",
    "carrierBundleChange:",
    "cellChanged:cell:",
    "connectionStateChanged:connection:dataConnectionStatusInfo:",
    "signalStrengthChanged:info:"
)
    "currentDataServiceDescriptorChanged:",
    "carrierBundleChange:",
    "cellChanged:cell:",
    "connectionStateChanged:connection:dataConnectionStatusInfo:",
    "signalStrengthChanged:info:"
)
	[C2.1 D1520899-9F0E-4563-B314-A66A029C83A7 2402:3a80:150b:f38a:1146:1bf6:43ff:7b02.61124<->2a03:2880:f02f:f:face:b00c:0:2.443]
	Connected Path: satisfied (Path is satisfied), interface: en0
	Duration: 0.456s, DNS @0.000s took 0.116s, TCP @0.117s took 0.042s, TLS took 0.076s
	bytes in/out: 4254/971, packets in/out: 8/8, rtt: 0.046s, retransmitted packets: 0, out-of-order packets: 0
	[C1.1 F1088559-FDEF-43FA-9D46-F03D79E085B7 2402:3a80:150b:f38a:1146:1bf6:43ff:7b02.61123<->2a03:2880:f02f:f:face:b00c:0:2.443]
	Connected Path: satisfied (Path is satisfied), interface: en0
	Duration: 0.468s, DNS @0.001s took 0.116s, TCP @0.118s took 0.041s, TLS took 0.075s
	bytes in/out: 4478/1201, packets in/out: 8/8, rtt: 0.046s, retransmitted packets: 0, out-of-order packets: 0
	[C3.1 1CDF44C6-534E-4F3D-AAEB-CD4D74E4F5CB 2402:3a80:150b:f38a:1146:1bf6:43ff:7b02.61150<->2404:6800:4009:80c::200a.443]
	Connected Path: satisfied (Path is satisfied), interface: en0
	Duration: 1343.849s, DNS @0.000s took 0.422s, TCP @0.423s took 0.040s, TLS took 0.109s
	bytes in/out: 4381/1522, packets in/out: 9/11, rtt: 0.040s, retransmitted packets: 0, out-of-order packets: 0

**Comment by wishie** [comment]
I get the same error when trying to build for iOS.

**Comment by minhcasi** [comment]
@wishie @Isodie - could you try to clean cache by using this guide - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

If you are using XCode 11.4 - pls check this migration guide - https://flutter.dev/docs/development/ios-project-migration

Thank you!

**Comment by EmreCaliskan1** [comment]
I get the same error when trying to build for iOS. using XCode 11.4

**Comment by wishie** [comment]
> @wishie @Isodie - could you try to clean cache by using this guide - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1
> 
> If you are using XCode 11.4 - pls check this migration guide - https://flutter.dev/docs/development/ios-project-migration
> 
> Thank you!

I am using Xcode 11.3 currently.

**Comment by minhcasi** [comment]
@all - it could be the RazorPay library issue - we will upload new release on early morning - thank you!

**Comment by Isodie** [comment]
@minhcasi  Its works fine on android simulator and device.
I have found another bug related to paging on product listing page.
Go to category page and select any subcategory who has more then 10 product.
Now scroll down till all products are loaded with that subcategory then select another subcategory from Appbar. After loading first 10 product next 10 products will not be loaded.

It seem page parameter in not reseted when new subcategory is selected from Appbar.

**Comment by wishie** [comment]
> @ALL - it could be the RazorPay library issue - we will upload new release on early morning - thank you!

Now that you mention it, I did have to comment out a few lines in the iOS build, just to get it to compile.. those lines were related to 'RazorPay'

`public func open(options: Dictionary<String, Any>, result: @escaping FlutterResult) {

        self.pendingResult = result

        let key = options["key"] as? String

        //let razorpay = Razorpay.initWithKey(key ?? "", andDelegateWithData: self)
        //razorpay.setExternalWalletSelectionDelegate(self)

        //razorpay.open(options)

    }`

in RazorpayDelegate.swift

**Comment by minhcasi** [comment]
@Isodie @wishie please help to download the latest version 1.6.6 to fix the build issue - we also note some detail here - https://medium.com/@inspireui/announcing-fluxstore-1-6-337efff1791f
