### ISSUE TITLE
I HAVE A BIG PROBLEM! FOR OPENCART INSTALL

### ISSUE THREAD

**Issue by alicankarakus** [inspireui/support#2509]
Hi !

I have a problem and i don't know how can i fix this. 
This problem is: "I want to use this app with opencart. But I was unable to integrate with Opencart. I watched the installation video but it didn't work. I added test information for opencart. I wanted to use it with test information first. Then I will enter my own information. But I get the following errors .. And I don't know how to do it."

Compiler message:
lib/common/config.dart:96:13: Error: Getter not found: 'kProductLayout'.
  "layout": kProductLayout.simpleType
            ^^^^^^^^^^^^^^
lib/services/helper/magento.dart:53:44: Error: Method not found: 'getLanguagesList'.
    List<Map<String, dynamic>> languages = getLanguagesList();
                                           ^^^^^^^^^^^^^^^^
lib/screens/settings.dart:52:29: Error: Getter not found: 'kStoreIdentifier'.
      googlePlayIdentifier: kStoreIdentifier['android'],
                            ^^^^^^^^^^^^^^^^
lib/screens/settings.dart:53:27: Error: Getter not found: 'kStoreIdentifier'.
      appStoreIdentifier: kStoreIdentifier['ios']);
                          ^^^^^^^^^^^^^^^^
lib/screens/language.dart:39:44: Error: The method 'getLanguagesList' isn't defined for the class '_LanguageState'.
 - '_LanguageState' is from 'package:fstore/screens/language.dart' ('lib/screens/language.dart').
Try correcting the name to the name of an existing method, or defining a method named 'getLanguagesList'.
    List<Map<String, dynamic>> languages = getLanguagesList(context);
                                           ^^^^^^^^^^^^^^^^
lib/screens/detail/product_variant.dart:379:23: Error: The getter 'kProductVariantLanguage' isn't defined for the class 'StateProductVariant'.
 - 'StateProductVariant' is from 'package:fstore/screens/detail/product_variant.dart' ('lib/screens/detail/product_variant.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'kProductVariantLanguage'.
              title: (kProductVariantLanguage[lang] != null &&
                      ^^^^^^^^^^^^^^^^^^^^^^^
lib/screens/detail/product_variant.dart:380:23: Error: The getter 'kProductVariantLanguage' isn't defined for the class 'StateProductVariant'.
 - 'StateProductVariant' is from 'package:fstore/screens/detail/product_variant.dart' ('lib/screens/detail/product_variant.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'kProductVariantLanguage'.
                      kProductVariantLanguage[lang][attr.name.toLowerCase()] !=
                      ^^^^^^^^^^^^^^^^^^^^^^^
lib/screens/detail/product_variant.dart:382:21: Error: The getter 'kProductVariantLanguage' isn't defined for the class 'StateProductVariant'.
 - 'StateProductVariant' is from 'package:fstore/screens/detail/product_variant.dart' ('lib/screens/detail/product_variant.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'kProductVariantLanguage'.
                  ? kProductVariantLanguage[lang][attr.name.toLowerCase()]
                    ^^^^^^^^^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 780

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\flutter\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 17s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by minhcasi** [comment]
Hi, thank you for the feedback. Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads it's used to verify your proof of purchase? 
Sorry for any inconvenience, we will reopen the ticket when it is verified, thank you!

**Comment by minhcasi** [comment]
please help to download the latest version 1.6.6 to fix the build issue - we also note some detail here - https://medium.com/@inspireui/announcing-fluxstore-1-6-337efff1791f
