### ISSUE TITLE
Execution failed for task ’:app:validateSigningRelease’.

### ISSUE THREAD

**Issue by farhaanabdulla** [inspireui/support#2510]
Hi i can’t build apk im having the below issue please kindly can you help

Execution failed for task ’:app:validateSigningRelease’.

Keystore file ‘C:\Users\User\Desktop\source\android\app\key.jks’ not found for signing config ‘release’.

**Comment by minhcasi** [comment]
Hi, thank you for the feedback. Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads it's used to verify your proof of purchase? 
Sorry for any inconvenience, we will reopen the ticket when it is verified, thank you!

**Comment by farhaanabdulla** [comment]
![Capture](https://user-images.githubusercontent.com/35699210/78234799-b8ce8b80-74e8-11ea-9c5d-2190366cbf1e.JPG)

**Comment by farhaanabdulla** [comment]
Here is my purchase proof, please treat it as urgent thanks

**Comment by minhcasi** [comment]
@farhaanabdulla - pls follow this link to generate the key - https://flutter.dev/docs/deployment/android

**Comment by minhcasi** [comment]
please help to download the latest version 1.6.6 to fix the build issue - we also note some detail here - https://medium.com/@inspireui/announcing-fluxstore-1-6-337efff1791f

Also, try to create your own key and save for every time publishes the app to google play store -thanks

Let us know if you have any question

**Comment by nahuelbourdichon** [comment]
Hello I have de same issue

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:validateSigningRelease'.
> Keystore file 'C:\src\MasPuntos_v1.7.4\FluxStore 1.7.4\source\android\app\Users\Nahuel\key.jks' not found for signing config 'release'.
I'm using version 1.7.4
