### ISSUE TITLE
Fluxstore listing - how to show operational hours

### ISSUE THREAD

**Issue by cschng96** [inspireui/support#2511]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: how to show operational hours

2. Screenshots issues (required): none

3. Proof of my purchased (required): 
<img width="856" alt="Screen Shot 2020-04-01 at 6 59 35 PM" src="https://user-images.githubusercontent.com/51393098/78129944-fa105e00-744a-11ea-9910-e19bd2be70b5.png">

3. Config files (required)
none

**Comment by minhcasi** [comment]
@cschng96 - could you help to share your common folder so that we could help for checking - thank you!

**Comment by cschng96** [comment]
Sorry!
I did not correct the ticket title. My issue is how to show operational hours of listings.
[common.zip](https://github.com/inspireui/support/files/4419082/common.zip)

**Comment by cschng96** [comment]
I have move this content to ticket #2522
