### ISSUE TITLE
Fluxstore Pro ios build failed - Razorpay and other related build issues

### ISSUE THREAD

**Issue by mel-c** [inspireui/support#2512]
My issue: Cannot build iOs version due to error related to Module 'Razorpay' has no member named 'initWithKey'

Error: Module 'Razorpay' has no member named 'initWithKey'

Steps to reproduce:
1. Open FluxStore 1.6.5c/source/ios/Runner.xcworkspace in Xcode and change the bundle identifier & Team
2. Open FluxStore 1.6.5c/source using Android Studio -> Import project
3. flutter clean --> Invalidate caches & restart --> rebuild
4. select device (Physical device) and click run. iOs installation will not complete due to error
5. Open Runner.workspace in Xcode and try to install to physical device. iOs build failed due to error related to razorpay.

Screenshots issues (required):

<img width="1036" alt="Screen Shot 2020-04-01 at 9 51 53 PM" src="https://user-images.githubusercontent.com/11792370/78145166-220bbb80-7463-11ea-83a2-0e81ec121858.png">

Xcode's output:
↳
    In file included from /Users/Xxxxxx/FlutterProjects/flutter/.pub-cache/hosted/pub.dartlang.org/uni_links-0.2.0/ios/Classes/UniLinksPlugin.m:1:
    /Users/Xxxxxx/FlutterProjects/flutter/.pub-cache/hosted/pub.dartlang.org/uni_links-0.2.0/ios/Classes/UniLinksPlugin.h:4:4: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
    + (instancetype)sharedInstance;
       ^
    /Users/Xxxxxx/FlutterProjects/flutter/.pub-cache/hosted/pub.dartlang.org/uni_links-0.2.0/ios/Classes/UniLinksPlugin.h:4:4: note: insert '_Nullable' if the pointer may be null
    + (instancetype)sharedInstance;
       ^
                    _Nullable 
    /Users/Xxxxxx/FlutterProjects/flutter/.pub-cache/hosted/pub.dartlang.org/uni_links-0.2.0/ios/Classes/UniLinksPlugin.h:4:4: note: insert '_Nonnull' if the pointer should never be null
    + (instancetype)sharedInstance;
       ^
                    _Nonnull 
    /Users/Xxxxxx/FlutterProjects/flutter/.pub-cache/hosted/pub.dartlang.org/uni_links-0.2.0/ios/Classes/UniLinksPlugin.h:7:33: warning: block pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
          restorationHandler:(void (^)(NSArray *_Nullable))restorationHandler;
                                    ^
    /Users/Xxxxxx/FlutterProjects/flutter/.pub-cache/hosted/pub.dartlang.org/uni_links-0.2.0/ios/Classes/UniLinksPlugin.h:7:33: note: insert '_Nullable' if the block pointer may be null
          restorationHandler:(void (^)(NSArray *_Nullable))restorationHandler;
                                    ^
                                     _Nullable
    /Users/Xxxxxx/FlutterProjects/flutter/.pub-cache/hosted/pub.dartlang.org/uni_links-0.2.0/ios/Classes/UniLinksPlugin.h:7:33: note: insert '_Nonnull' if the block pointer should never be null
          restorationHandler:(void (^)(NSArray *_Nullable))restorationHandler;
                                    ^
                                     _Nonnull
    2 warnings generated.
    /Users/Xxxxxx/FlutterProjects/flutter/.pub-cache/hosted/pub.dartlang.org/razorpay_flutter-1.1.2/ios/Classes/RazorpayDelegate.swift:57:24: error: module 'Razorpay' has no member named 'initWithKey'
            let razorpay = Razorpay.initWithKey(key ?? "", andDelegateWithData: self)
                           ^~~~~~~~ ~~~~~~~~~~~
    /Users/Xxxxxx/FlutterProjects/flutter/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0.6.0+2/ios/Classes/RateMyAppPlugin.m:15:30: warning: 'requestReview' is only available on iOS 10.3 or newer [-Wunguarded-availability]
        [SKStoreReviewController requestReview];
                                 ^~~~~~~~~~~~~~
    In module 'StoreKit' imported from /Users/Xxxxxx/FlutterProjects/flutter/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0.6.0+2/ios/Classes/RateMyAppPlugin.m:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.4.sdk/System/Library/Frameworks/StoreKit.framework/Headers/SKStoreReviewController.h:22:1: note: 'requestReview' has been marked as being introduced in iOS 10.3 here, but the deployment target is iOS 8.0.0
    + (void)requestReview API_AVAILABLE(ios(10.3), macos(10.14)) API_UNAVAILABLE(watchos) __TVOS_PROHIBITED;
    ^
    /Users/Xxxxxx/FlutterProjects/flutter/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0.6.0+2/ios/Classes/RateMyAppPlugin.m:15:30: note: enclose 'requestReview' in an @available check to silence this warning
        [SKStoreReviewController requestReview];
                                 ^~~~~~~~~~~~~~
    /Users/Xxxxxx/FlutterProjects/flutter/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0.6.0+2/ios/Classes/RateMyAppPlugin.m:15:6: warning: 'SKStoreReviewController' is only available on iOS 10.3 or newer [-Wunguarded-availability]
        [SKStoreReviewController requestReview];
         ^~~~~~~~~~~~~~~~~~~~~~~
    In module 'StoreKit' imported from /Users/Xxxxxx/FlutterProjects/flutter/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0.6.0+2/ios/Classes/RateMyAppPlugin.m:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.4.sdk/System/Library/Frameworks/StoreKit.framework/Headers/SKStoreReviewController.h:14:110: note: 'SKStoreReviewController' has been marked as being introduced in iOS 10.3 here, but the deployment target is iOS 8.0.0
    SK_EXTERN_CLASS API_AVAILABLE(ios(10.3), macos(10.14)) API_UNAVAILABLE(watchos) __TVOS_PROHIBITED @interface SKStoreReviewController : NSObject
                                                                                                                 ^
    /Users/Xxxxxx/FlutterProjects/flutter/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0.6.0+2/ios/Classes/RateMyAppPlugin.m:15:6: note: enclose 'SKStoreReviewController' in an @available check to silence this warning
        [SKStoreReviewController requestReview];
         ^~~~~~~~~~~~~~~~~~~~~~~
    2 warnings generated.
    Command CompileSwift failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

Could not build the precompiled application for the device.

Error launching application on Xxxxxx’s iPhone.

Proof of my purchased (required):
<img width="1036" alt="Screen Shot 2020-04-01 at 9 49 25 PM" src="https://user-images.githubusercontent.com/11792370/78144895-cd684080-7462-11ea-8384-b32c608ac5da.png">

Config files (required)
none

**Comment by minhcasi** [comment]
@mel-c - could you help to give us the comment on this link to verify your purchase again - https://codecanyon.net/item/fluxstore-the-universal-woocommerce-magento-opencart-mobile-app-by-flutter-framework/24020929

We will update new patching for razorpay in 1-2 days as they have a problem with the latest release version - thank you!

**Comment by mel-c** [comment]
Hi, I posted a comment in your comment section regarding the issue i
submitted in https://github.com/inspireui/support/issues/2512

**Comment by minhcasi** [comment]
@mel-c - please help to download the latest version 1.6.6 to fix the build issue - we also note some detail here - https://medium.com/@inspireui/announcing-fluxstore-1-6-337efff1791f
