### ISSUE TITLE
FluxStore WooCommerce - iOS Build Failure

### ISSUE THREAD

**Issue by robert-stevens** [inspireui/support#2513]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:

Can't build iOS, errors:

> Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
> Running Xcode build...                                          
> 
> Compiler message:
> 
> /Users/user/.pub-cache/hosted/pub.dartlang.org/extended_image-0.7.1/lib/src/gest
> ure/extended_image_slide_page_route.dart:333:9: Error: No named parameter with
> the name 'animation'.
> 
>         animation: animation,
> 
>         ^^^^^^^^^
> 
> /Users/user/flutter/packages/flutter/lib/src/cupertino/route.dart:435:3:
> Context: Found this candidate, but the arguments don't match.
> 
>   CupertinoFullscreenDialogTransition({
> 
>   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Xcode build done.                                           25,1s
> Failed to build iOS app
> Error output from Xcode build:
> ↳
>     ** BUILD FAILED **
> 
> 
> Xcode's output:
> ↳
>     In file included from
>     /Users/user/.pub-cache/hosted/pub.dartlang.org/uni_links-0.2.0/ios/Classes/U
>     niLinksPlugin.m:1:
>     /Users/user/.pub-cache/hosted/pub.dartlang.org/uni_links-0.2.0/ios/Classes/U
>     niLinksPlugin.h:4:4: warning: pointer is missing a nullability type
>     specifier (_Nonnull, _Nullable, or _Null_unspecified)
>     [-Wnullability-completeness]
>     + (instancetype)sharedInstance;
>        ^
>     /Users/user/.pub-cache/hosted/pub.dartlang.org/uni_links-0.2.0/ios/Classes/U
>     niLinksPlugin.h:4:4: note: insert '_Nullable' if the pointer may be null
>     + (instancetype)sharedInstance;
>        ^
>                     _Nullable 
>     /Users/user/.pub-cache/hosted/pub.dartlang.org/uni_links-0.2.0/ios/Classes/U
>     niLinksPlugin.h:4:4: note: insert '_Nonnull' if the pointer should never be
>     null
>     + (instancetype)sharedInstance;
>        ^
>                     _Nonnull 
>     /Users/user/.pub-cache/hosted/pub.dartlang.org/uni_links-0.2.0/ios/Classes/U
>     niLinksPlugin.h:7:33: warning: block pointer is missing a nullability type
>     specifier (_Nonnull, _Nullable, or _Null_unspecified)
>     [-Wnullability-completeness]
>           restorationHandler:(void (^)(NSArray *_Nullable))restorationHandler;
>                                     ^
>     /Users/user/.pub-cache/hosted/pub.dartlang.org/uni_links-0.2.0/ios/Classes/U
>     niLinksPlugin.h:7:33: note: insert '_Nullable' if the block pointer may be
>     null
>           restorationHandler:(void (^)(NSArray *_Nullable))restorationHandler;
>                                     ^
>                                      _Nullable
>     /Users/user/.pub-cache/hosted/pub.dartlang.org/uni_links-0.2.0/ios/Classes/U
>     niLinksPlugin.h:7:33: note: insert '_Nonnull' if the block pointer should
>     never be null
>           restorationHandler:(void (^)(NSArray *_Nullable))restorationHandler;
>                                     ^
>                                      _Nonnull
>     2 warnings generated.
>     /Users/user/.pub-cache/hosted/pub.dartlang.org/razorpay_flutter-1.1.2/ios/Cl
>     asses/RazorpayDelegate.swift:57:24: error: module 'Razorpay' has no member
>     named 'initWithKey'
>             let razorpay = Razorpay.initWithKey(key ?? "", andDelegateWithData:
>             self)
>                            ^~~~~~~~ ~~~~~~~~~~~
>     /Users/user/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0.6.0+2/ios/Class
>     es/RateMyAppPlugin.m:15:30: warning: 'requestReview' is only available on
>     iOS 10.3 or newer [-Wunguarded-availability]
>         [SKStoreReviewController requestReview];
>                                  ^~~~~~~~~~~~~~
>     In module 'StoreKit' imported from
>     /Users/user/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0.6.0+2/ios/Class
>     es/RateMyAppPlugin.m:2:
>     /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platfor
>     m/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/StoreKit.
>     framework/Headers/SKStoreReviewController.h:22:1: note: 'requestReview' has
>     been marked as being introduced in iOS 10.3 here, but the deployment target
>     is iOS 8.0.0
>     + (void)requestReview API_AVAILABLE(ios(10.3), macos(10.14))
>     __TVOS_PROHIBITED;
>     ^
>     /Users/user/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0.6.0+2/ios/Class
>     es/RateMyAppPlugin.m:15:30: note: enclose 'requestReview' in an @available
>     check to silence this warning
>         [SKStoreReviewController requestReview];
>                                  ^~~~~~~~~~~~~~
>     /Users/user/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0.6.0+2/ios/Class
>     es/RateMyAppPlugin.m:15:6: warning: 'SKStoreReviewController' is only
>     available on iOS 10.3 or newer [-Wunguarded-availability]
>         [SKStoreReviewController requestReview];
>          ^~~~~~~~~~~~~~~~~~~~~~~
>     In module 'StoreKit' imported from
>     /Users/user/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0.6.0+2/ios/Class
>     es/RateMyAppPlugin.m:2:
>     /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platfor
>     m/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/StoreKit.
>     framework/Headers/SKStoreReviewController.h:14:85: note:
>     'SKStoreReviewController' has been marked as being introduced in iOS 10.3
>     here, but the deployment target is iOS 8.0.0
>     SK_EXTERN_CLASS API_AVAILABLE(ios(10.3), macos(10.14)) __TVOS_PROHIBITED
>     @interface SKStoreReviewController : NSObject
>                                                                                         ^
>     /Users/user/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0.6.0+2/ios/Class
>     es/RateMyAppPlugin.m:15:6: note: enclose 'SKStoreReviewController' in an
>     @available check to silence this warning
>         [SKStoreReviewController requestReview];
>          ^~~~~~~~~~~~~~~~~~~~~~~
>     2 warnings generated.
>     Command CompileSwift failed with a nonzero exit code
>     note: Using new build system
>     note: Planning build
>     note: Constructing build description
>     warning: Mapping architecture armv7 to i386. Ensure that this target's
>     Architectures and Valid Architectures build settings are configured
>     correctly for the iOS Simulator platform. (in target 'image_picker' from
>     project 'Pods')
>     warning: Mapping architecture arm64 to x86_64. Ensure that this target's
>     Architectures and Valid Architectures build settings are configured
>     correctly for the iOS Simulator platform. (in target 'image_picker' from
>     project 'Pods')
> 
> Could not build the application for the simulator.
> Error launching application on iPhone 11 Pro Max.

**Flutter Doctor:**

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.16.4-pre.52, on Mac OS X 10.15.3 19D76, locale
    en-ZA)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.43.2)
[✓] Connected device (1 available)

2. Screenshots issues (required):

N/a

3. Proof of my purchased (required):

b68f55ac-44fa-4ca9-b544-61e13172e594
![Downloads___ThemeForest](https://user-images.githubusercontent.com/32265535/78146338-531fc800-7432-11ea-99cc-1851926022a1.png)

3. Config files (required)

N/a

**Comment by robert-stevens** [comment]
I have did the following:

flutter clean
flutter build ios
flutter run ios

Issue persists, and error now is:

> 
> Users-MBP:source user$ flutter run
> Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
> Running pod install...                                          
> 
> Compiler message:
> 
> /Users/user/.pub-cache/hosted/pub.dartlang.org/extended_image-0.7.1/lib/src/gest
> ure/extended_image_slide_page_route.dart:333:9: Error: No named parameter with
> the name 'animation'.
> 
>         animation: animation,
> 
>         ^^^^^^^^^
> 
> /Users/user/flutter/packages/flutter/lib/src/cupertino/route.dart:435:3:
> Context: Found this candidate, but the arguments don't match.
> 
>   CupertinoFullscreenDialogTransition({
> 
>   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Running pod install...                                             14,4s
> Running Xcode build...                                          
> Xcode build done.                                           29,4s
> Failed to build iOS app
> Error output from Xcode build:
> ↳
>     ** BUILD FAILED **
> 
> 
> Xcode's output:
> ↳
>     In file included from
>     /Users/user/.pub-cache/hosted/pub.dartlang.org/uni_links-0.2.0/ios/Classes/U
>     niLinksPlugin.m:1:
>     /Users/user/.pub-cache/hosted/pub.dartlang.org/uni_links-0.2.0/ios/Classes/U
>     niLinksPlugin.h:4:4: warning: pointer is missing a nullability type
>     specifier (_Nonnull, _Nullable, or _Null_unspecified)
>     [-Wnullability-completeness]
>     + (instancetype)sharedInstance;
>        ^
>     /Users/user/.pub-cache/hosted/pub.dartlang.org/uni_links-0.2.0/ios/Classes/U
>     niLinksPlugin.h:4:4: note: insert '_Nullable' if the pointer may be null
>     + (instancetype)sharedInstance;
>        ^
>                     _Nullable 
>     /Users/user/.pub-cache/hosted/pub.dartlang.org/uni_links-0.2.0/ios/Classes/U
>     niLinksPlugin.h:4:4: note: insert '_Nonnull' if the pointer should never be
>     null
>     + (instancetype)sharedInstance;
>        ^
>                     _Nonnull 
>     /Users/user/.pub-cache/hosted/pub.dartlang.org/uni_links-0.2.0/ios/Classes/U
>     niLinksPlugin.h:7:33: warning: block pointer is missing a nullability type
>     specifier (_Nonnull, _Nullable, or _Null_unspecified)
>     [-Wnullability-completeness]
>           restorationHandler:(void (^)(NSArray *_Nullable))restorationHandler;
>                                     ^
>     /Users/user/.pub-cache/hosted/pub.dartlang.org/uni_links-0.2.0/ios/Classes/U
>     niLinksPlugin.h:7:33: note: insert '_Nullable' if the block pointer may be
>     null
>           restorationHandler:(void (^)(NSArray *_Nullable))restorationHandler;
>                                     ^
>                                      _Nullable
>     /Users/user/.pub-cache/hosted/pub.dartlang.org/uni_links-0.2.0/ios/Classes/U
>     niLinksPlugin.h:7:33: note: insert '_Nonnull' if the block pointer should
>     never be null
>           restorationHandler:(void (^)(NSArray *_Nullable))restorationHandler;
>                                     ^
>                                      _Nonnull
>     2 warnings generated.
>     /Users/user/.pub-cache/hosted/pub.dartlang.org/razorpay_flutter-1.1.2/ios/Cl
>     asses/RazorpayDelegate.swift:57:24: error: module 'Razorpay' has no member
>     named 'initWithKey'
>             let razorpay = Razorpay.initWithKey(key ?? "", andDelegateWithData:
>             self)
>                            ^~~~~~~~ ~~~~~~~~~~~
>     /Users/user/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0.6.0+2/ios/Class
>     es/RateMyAppPlugin.m:15:30: warning: 'requestReview' is only available on
>     iOS 10.3 or newer [-Wunguarded-availability]
>         [SKStoreReviewController requestReview];
>                                  ^~~~~~~~~~~~~~
>     In module 'StoreKit' imported from
>     /Users/user/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0.6.0+2/ios/Class
>     es/RateMyAppPlugin.m:2:
>     /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platfor
>     m/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/StoreKit.
>     framework/Headers/SKStoreReviewController.h:22:1: note: 'requestReview' has
>     been marked as being introduced in iOS 10.3 here, but the deployment target
>     is iOS 8.0.0
>     + (void)requestReview API_AVAILABLE(ios(10.3), macos(10.14))
>     __TVOS_PROHIBITED;
>     ^
>     /Users/user/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0.6.0+2/ios/Class
>     es/RateMyAppPlugin.m:15:30: note: enclose 'requestReview' in an @available
>     check to silence this warning
>         [SKStoreReviewController requestReview];
>                                  ^~~~~~~~~~~~~~
>     /Users/user/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0.6.0+2/ios/Class
>     es/RateMyAppPlugin.m:15:6: warning: 'SKStoreReviewController' is only
>     available on iOS 10.3 or newer [-Wunguarded-availability]
>         [SKStoreReviewController requestReview];
>          ^~~~~~~~~~~~~~~~~~~~~~~
>     In module 'StoreKit' imported from
>     /Users/user/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0.6.0+2/ios/Class
>     es/RateMyAppPlugin.m:2:
>     /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platfor
>     m/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/StoreKit.
>     framework/Headers/SKStoreReviewController.h:14:85: note:
>     'SKStoreReviewController' has been marked as being introduced in iOS 10.3
>     here, but the deployment target is iOS 8.0.0
>     SK_EXTERN_CLASS API_AVAILABLE(ios(10.3), macos(10.14)) __TVOS_PROHIBITED
>     @interface SKStoreReviewController : NSObject
>                                                                                         ^
>     /Users/user/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0.6.0+2/ios/Class
>     es/RateMyAppPlugin.m:15:6: note: enclose 'SKStoreReviewController' in an
>     @available check to silence this warning
>         [SKStoreReviewController requestReview];
>          ^~~~~~~~~~~~~~~~~~~~~~~
>     2 warnings generated.
>     Command CompileSwift failed with a nonzero exit code
>     note: Using new build system
>     note: Planning build
>     note: Constructing build description
>     warning: Mapping architecture armv7 to i386. Ensure that this target's
>     Architectures and Valid Architectures build settings are configured
>     correctly for the iOS Simulator platform. (in target 'image_picker' from
>     project 'Pods')
>     warning: Mapping architecture arm64 to x86_64. Ensure that this target's
>     Architectures and Valid Architectures build settings are configured
>     correctly for the iOS Simulator platform. (in target 'image_picker' from
>     project 'Pods')
> 
> Could not build the application for the simulator.
> Error launching application on iPhone 11 Pro Max.
>

**Comment by antonduong** [comment]
This is happening to a few others as well. It has something to do with Razorpay and the new version of Xcode 11.4. Some of the others removed it but other problem arise. We're all waiting for the next update on the fix. Hopefully one of the dev guys can help us fix this.

**Comment by robert-stevens** [comment]
@antonduong thanks, but I removing RazorPay and I am only using 11.3.1 and still no luck.

**Comment by minhcasi** [comment]
@robert-stevens - could you try to clean cache - i've noted the guide here - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

**Comment by robert-stevens** [comment]
@minhcasi 

It's building now, but I have a WSOD:

![Screenshot 2020-04-03 at 12 33 01](https://user-images.githubusercontent.com/32265535/78351563-4a043780-75a7-11ea-9e45-c6d6e56fbc20.png)

With no errors, please assist.

To get it building I did:

* Switch to Flutter Stable
* Removed Razor Pay
* Flutter clean

**Comment by robert-stevens** [comment]
I performed a Hot Reload and got the following errors:

> 
> Initializing hot reload...                                      Error 105 received from application: Isolate must be runnable
> Hot reload received invalid response: {code: 105, message: Isolate must be
> runnable, data: {request: {method: _reloadSources, params: {pause: false,
> rootLibUri:
> file:///Users/user/Library/Developer/CoreSimulator/Devices/3051A35E-5F25-47C0-86
> BE-F85BF8A59E73/data/Containers/Data/Application/A5EC4686-DB3C-4865-A523-8940C2C
> 7CB83/tmp/sourceZj2jK5/source/lib/main.dart.incremental.dill, packagesUri:
> file:///Users/user/Library/Developer/CoreSimulator/Devices/3051A35E-5F25-47C0-86
> BE-F85BF8A59E73/data/Containers/Data/Application/A5EC4686-DB3C-4865-A523-8940C2C
> 7CB83/tmp/sourceZj2jK5/source/.packages, isolateId: isolates/1979836439779935}},
> details: Isolate must be runnable before this request is made.}}

**Comment by robert-stevens** [comment]
When running it and after xCode finishes the build, I get the following:

> Xcode build done.                                           106,0s
> 	path: satisfied (Path is satisfied), interface: en1
> Failed to find assets path for "Frameworks/App.framework/flutter_assets"
> Configuring the default Firebase app...
> 	path: satisfied (Path is satisfied), interface: en1
> 	path: satisfied (Path is satisfied), interface: en1
> 	path: satisfied (Path is satisfied), interface: en1
> Configured the default Firebase app __FIRAPP_DEFAULT.
> [VERBOSE-2:engine.cc(127)] Engine run configuration was invalid.
> [VERBOSE-2:shell.cc(437)] Could not launch engine with configuration.
> 	path: satisfied (Path is satisfied), interface: en1
>     "currentDataServiceDescriptorChanged:",
>     "carrierBundleChange:",
>     "cellChanged:cell:",
>     "connectionStateChanged:connection:dataConnectionStatusInfo:",
>     "signalStrengthChanged:info:"
> )
>     "currentDataServiceDescriptorChanged:",
>     "carrierBundleChange:",
>     "cellChanged:cell:",
>     "connectionStateChanged:connection:dataConnectionStatusInfo:",
>     "signalStrengthChanged:info:"
> )
>     "currentDataServiceDescriptorChanged:",
>     "carrierBundleChange:",
>     "cellChanged:cell:",
>     "connectionStateChanged:connection:dataConnectionStatusInfo:",
>     "signalStrengthChanged:info:"
> )
>     "currentDataServiceDescriptorChanged:",
>     "carrierBundleChange:",
>     "cellChanged:cell:",
>     "connectionStateChanged:connection:dataConnectionStatusInfo:",
>     "signalStrengthChanged:info:"
> )

**Comment by minhcasi** [comment]
@robert-stevens - please help to download the latest version 1.6.6 to fix the build issue - we also note some detail here - https://medium.com/@inspireui/announcing-fluxstore-1-6-337efff1791f
