### ISSUE TITLE
[FluxNews] -  Hide specific categories in the app

### ISSUE THREAD

**Issue by ernandozatariano** [inspireui/support#2514]
Hi! Tks for the great product and code!

I have a simple question, but i can’t find in another support channels or in oficial app documentation.

1) Can in hide specific categories in the  app? How i do that?

Tks again!

**Comment by minhcasi** [comment]
@ernandozatariano - you can try to add the exclude from services file - https://tppr.me/am1FQ

ex: getAsync("categories?per_page=20&hide_empty=0&exclude=10")

Let us know if you have any questions ☺️
