### ISSUE TITLE
Couldn't read file LocalFile

### ISSUE THREAD

**Issue by redamakarem** [inspireui/support#2515]
Hello,
I purchased FluxStore yesterday but unable to run it yet. I keep getting the following error:
Running "flutter pub get" in source...                             56.4s
Couldn't read file LocalFile: 'C:\Users\GeneralSenses\Desktop\Dev\flutter_windows_v1.12.13+hotfix.8-stable\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.6\android\src\main\kotlin\io\flutter\plugins\flutter_plugin_android_lifecycle\FlutterAndroidLifecyclePlugin.kt' even though it exists.
I am able to create and run other flutter projects. I also cleared the cache and tried to update and re-install flutter with no success yet
flutter doctor output:
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18362.720], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 3.6)
[!] IntelliJ IDEA Ultimate Edition (version 2019.1)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.43.2)
[√] Connected device (1 available)

Please help me get the app running.
Thanks

**Comment by nobakhtvip** [comment]
please help me for this error
