### ISSUE TITLE
UIWebView  Deprecated

### ISSUE THREAD

**Issue by inimist** [inspireui/support#2516]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:

App Store Connect
Dear Developer,
      We identified one or more issues with a recent delivery for your app, "World Sweets" 1.3.1 (1). Your delivery was successful, but you may wish to correct the following issues in your next delivery:
      ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of new apps that use UIWebView APIs starting from April 2020. See 
      https://developer.apple.com/documentation/uikit/uiwebview for more information.
     After you’ve corrected the issues, you can upload a new binary to App Store Connect.
Best regards,
The App Store Team

2. Screenshots issues (required):

3. Proof of my purchased (required):
![76964872-65d1d180-6949-11ea-9687-d2b778d05d0a](https://user-images.githubusercontent.com/447618/78156015-d0abfe00-745b-11ea-9a3d-69a1fd3fdb5e.png)

3. Config files (required)

**Comment by ernandozatariano** [comment]
Hi, webview is really deprecated. You can use the newest WKWebView object. 

Take a look at https://developer.apple.com/documentation/webkit/wkwebview

**Comment by inimist** [comment]
Hi @luyx2412, can you please tell me what I can use in the place of WebView, or provide the patch to fix this issue.
Thanks

**Comment by luyx2412** [comment]
HI @inimist The first please update latest version `react-native-webview` and follow the comment to fix your issue. https://github.com/react-native-community/react-native-webview/issues/819

Thanks

**Comment by inimist** [comment]
Hi @luyx2412 I have got the solution, this is working fine.
https://stackoverflow.com/questions/59233149/solving-uiwebview-deprecation-warning-by-app-store-on-react-native-expo?answertab=votes#tab-top  we just need to add the `useWebKit={true}`  with `<webview`  module
Thanks :)
