### ISSUE TITLE
[fluxstore-WooCommerce1.6c] - Address Choose Problem

### ISSUE THREAD

**Issue by Madraka** [inspireui/support#2517]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: Address choose problem and saved.  Name, surname etc not loading

2. Screenshots issues (required): https://ibb.co/7WkXfwx
https://ibb.co/CQykntL

3. Proof of my purchased (required):

3. Config files (required)

**Comment by minhcasi** [comment]
Hi, thank you for the feedback. Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads it's used to verify your proof of purchase? 
Sorry for any inconvenience, we will reopen the ticket when it is verified, thank you!

**Comment by Madraka** [comment]
https://ibb.co/bbKCKf7

**Comment by minhcasi** [comment]
@Madraka - thank you for quick feedback, we got your verified - pls also share your common and config folder so that we could try to reproduce the issue on your site

@trunghieuvn - please check the address filling issue

**Comment by minhcasi** [comment]
@Madraka  - Please provide the detail config file and reopen the ticket - thank you!
