### ISSUE TITLE
[Mstore Pro - getting errors on running setup 

### ISSUE THREAD

**Issue by malibate** [inspireui/support#2518]
---------

1. My issue:
My CEbuilder doesn't have home layout;
and when i run setup i get errors

2. Screenshots issues (required):

![Capture2](https://user-images.githubusercontent.com/45195047/78180666-c5f96500-746b-11ea-8fe0-0969f3531749.PNG)
![Capture3](https://user-images.githubusercontent.com/45195047/78180676-c85bbf00-746b-11ea-891d-8f8b0af5f59b.PNG)
![Capture](https://user-images.githubusercontent.com/45195047/78180685-c98cec00-746b-11ea-94af-c5e1640914be.PNG)

3. Proof of my purchased (required):

![Screenshot_2020-04-01 Downloads CodeCanyon](https://user-images.githubusercontent.com/45195047/78180873-15d82c00-746c-11ea-9f53-fa50d10509c7.png)

3. Config files (required)

**Comment by malibate** [comment]
![Capture4](https://user-images.githubusercontent.com/45195047/78244373-203b0a00-74ee-11ea-8d8b-424d231fed07.PNG)

**Comment by minhcasi** [comment]
@malibate - could you help to install the nodejs 10.x to fix the problem - https://nodejs.org/dist/latest-v10.x/

**Comment by malibate** [comment]
it worked!

**Comment by malibate** [comment]
I managed to Customize and run setup using ceBuilder, but the customization doesn't reflect on the application, it still comes Mstore and its data;
I would like to have my store data into the App

**Comment by malibate** [comment]
@minhcasi 
I managed to Customize and run setup using ceBuilder, but the customization doesn't reflect on the application, it still comes Mstore and its data;
I would like to have my store data into the App

**Comment by minhcasi** [comment]
@malibate - could you help to share the screenshot and appconfig.json so that we could try to reproduce the issue - thank you!

**Comment by malibate** [comment]
{
  "WooCommerce": {
    "url": "http://rahisimarket.com",
    "consumerKey": "ck_4bb7f1503138b0bec3fc5cc439ed6c35630e42c5",
    "consumerSecret": "cs_a3a872fa13946adfc6ab49164cc7da8f65e2a4e0"
  },
  "HorizonLayout": [
    {
      "layout": "circleCategory"
    },
    {
      "layout": "bannerHigh",
      "categoryOrTag": 273,
      "tag": 273
    },
    {
      "layout": "bannerImage",
      "categoryOrTag": 23,
      "imageBanner": "https://user-images.githubusercontent.com/1459805/60091808-a19b8a00-976f-11e9-9cc7-576ca05c2442.png",
      "category": 23
    },
    {
      "name": "featureProducts",
      "image": "",
      "layout": "threeColumn",
      "categoryOrTag": 26,
      "category": 26
    },
    {
      "name": "News",
      "layout": "Blog",
      "categoryOrTag": 21,
      "tag": 21
    }
  ],
  "MainColor": "#3FC1BE"
}

**Comment by Haniel5** [comment]
@minhcasi

**Comment by minhcasi** [comment]
@malibate - could you try to clean cache from your PC that could be fixed the issue - https://gist.github.com/minhcasi/cff0b1519217c06f4fb7986c2d044c5e - let us know your checking - thanks

**Comment by malibate** [comment]
I'm unable to complete the setup due to lots of errors on the process and
my client wants the project live the soonest;

so what is the cost for you to do the configuration and installation? I
will see if i can afford

**Comment by minhcasi** [comment]
@malibate - we have a check on our window or macbook - it's working fine - could you have double check 2 solutions

1. use cebuilder with the nodejs 10.x - https://nodejs.org/dist/latest-v10.x/

2. Use this guide manually without using cebuilder - https://reactnative.dev/docs/environment-setup - then you need to customize manually by using VS Code

Let us know your checking - thank you!

**Comment by malibate** [comment]
**FIRST SOLUTION:**
I have used nodejs 10.x
![cebuilder](https://user-images.githubusercontent.com/45195047/78884664-0193c080-7a64-11ea-8c29-486fe767957b.PNG)

and configured everything followed by running the setup;
though when you click save the screen goes white and i dont get a place to change the home layout as most of manuals illustrates. 

![cebuilder2](https://user-images.githubusercontent.com/45195047/78884765-212ae900-7a64-11ea-9849-02cb0a9e2be0.PNG)

when I run setup i get errors as depicted 
![cmd](https://user-images.githubusercontent.com/45195047/78884880-50d9f100-7a64-11ea-9c32-415d35ab35a6.PNG)
![cmd2](https://user-images.githubusercontent.com/45195047/78884890-533c4b00-7a64-11ea-88a8-76bae0a0653d.PNG)


**THE SECOND SOLUTION:**
Can you help me where to customize manually, as in where to edit so as to link with my website

**Comment by luyx2412** [comment]
Hi @malibate We will update next version to fix the issues soon. So can you setup with original? This is a document https://docs.inspireui.com/mstore

Thanks

**Comment by malibate** [comment]
managed to run the project but the App crushes once it starts to display the home page with the below errors


![IMG_8164](https://user-images.githubusercontent.com/45195047/79219493-0dfc8c80-7e5b-11ea-8d6c-d7830244397d.PNG)
![IMG_8165](https://user-images.githubusercontent.com/45195047/79219495-0fc65000-7e5b-11ea-8364-a6a81e709819.PNG)
![IMG_8166](https://user-images.githubusercontent.com/45195047/79219501-11901380-7e5b-11ea-9ce0-789f5aef4640.PNG)

**Comment by luyx2412** [comment]
Hi @malibate Can you share specific issue? i just tested your config, and everything worked normal.

![image](https://user-images.githubusercontent.com/8909619/79297003-1ad6ba00-7f07-11ea-9590-d6b898c2bfbc.png)

Thanks

**Comment by malibate** [comment]
After being unable to use expo to run the my project using cebuilder,
i used pro version and ran using genymotion;

my store still doesn't synchronize, even categories still come of the mstore,

and i get error of invalid signature as seen on the screenshot

![rahusu](https://user-images.githubusercontent.com/45195047/79881192-93eb7b00-83f9-11ea-87ee-05b8aaff086b.PNG)
![rahis](https://user-images.githubusercontent.com/45195047/79881198-951ca800-83f9-11ea-9d51-876d240c316b.PNG)
