### ISSUE TITLE
cebuilder first step freezing

### ISSUE THREAD

**Issue by fashionhubksa** [inspireui/support#2519]
hello I just bought the Mstore pro for my woocommerce store, i followed the videos but unfortunately, the Cebuilder is being kept circling in the first step and i couldn't solve this.

---------

1. My issue: in step 1 when i select the project folder firstly i get this message  -TypeError: Cannot read property 'url' of undefined-  when i press ok i found the folder path is placed correctly, also i am not allowed to type my path. Then the cebuilder starts circling endlessly as shown in the pics below.

2. Screenshots issues (required): windows 10
![1](https://user-images.githubusercontent.com/63024636/78198927-e1c43180-7492-11ea-8180-87c86d5447bd.png)
![2](https://user-images.githubusercontent.com/63024636/78198943-e983d600-7492-11ea-9757-263955c43537.png)

3. Proof of my purchased (required): 
![pur](https://user-images.githubusercontent.com/63024636/78200017-ffdf6100-7495-11ea-9daf-86129b812c23.png)

4. Config files (required) : nothing changed yet, step 1 didn't even start, all is the same as the default.

your prompt action is highly appreciated
best regards

**Comment by fashionhubksa** [comment]
Any replies @minhtruong315 ??

**Comment by fashionhubksa** [comment]
Why there's no reply for 2 days!!!!!!??

**Comment by minhcasi** [comment]
@fashionhubksa - sorry for the late response as our react native team have an issue with the CoV9 on the city, i'm updating the ticket as high priority to ask the team focus on checking - thank you for your patience

**Comment by luyx2412** [comment]
Hi @fashionhubksa Can you send me your AppConfig.json? Let me investigate with cebuilder.

Thanks

**Comment by fashionhubksa** [comment]
Hi the file is default as downloaded, not modified or anything happened, i am still stuck in the first step as shown in the pics.

**Comment by fashionhubksa** [comment]
@luyx2412 any replies?

**Comment by luyx2412** [comment]
HI @fashionhubksa We will update in next version. So can you move to original setup? this is a document to setup original https://docs.inspireui.com/mstore.

Thanks

**Comment by fashionhubksa** [comment]
What about the current problem?? Should i wait for the next release? What if that happened while i am using your service? Should i wait for new release! I think this doesn't make sense for a reliable business. I need a solution please.

**Comment by fashionhubksa** [comment]
I bought it specifically for cebuilder, if it's not working i will ask for refund unfortunately.  As the original method is available for all apps, which i currently use.

**Comment by fashionhubksa** [comment]
is this how the "priority" issue is treated? at least 2 days for a response? i can' rely on your service in the business, i already issued a refund request, please respond asap. thanks.

**Comment by fashionhubksa** [comment]
What happened to close my request??

**Comment by minhcasi** [comment]
@fashionhubksa - as we have updated your refund request - thanks

**Comment by fashionhubksa** [comment]
Thanks
