### ISSUE TITLE
[BeoNews] Home showing different post details - fix customize

### ISSUE THREAD

**Issue by hadi13** [inspireui/support#252]
In beonews, when I click on a post it shows another one
I have this issue on Android only using expo 

Product: [Beonews]
Your Purchased Code: 2b7fa788-ea4d-4d1c-bb3a-4bf22a499783

**Comment by hadi13** [comment]
Any answer?

**Comment by minhcasi** [comment]
Hi, could you share the screenshot please, it's confused with the bug description, please also share your config file - thank you!

Just update that we received your ticket and the team will back to check on Monday (after the Tet holiday), sorry for the delay - thank you!

**Comment by hadi13** [comment]
check this apk [https://ufile.io/kekb5](https://ufile.io/kekb5) and see how app is behaving, although I set it to RTL, but it is showing LTR, and when you click on post and the you go back and click on another post it shows the post you clicked first,

**Comment by hadi13** [comment]
also there is an issue with new regeneration or logging in

**Comment by hadi13** [comment]
moreover, comments are not delivered to admin panel ???

**Comment by minhcasi** [comment]
Hi, could you send the screenshot of the issues looks like as we could not use your sharing apk - thanks

**Comment by hadi13** [comment]
The issue will be shown by image, I will send you my expo project and check, when you click on post first time it shows post details ok, but nect time it shows different

**Comment by hadi13** [comment]
Check this video 
https://drive.google.com/file/d/1TQ-0f-phKNNiJf5OlNH73AtW-If-GOjE/view?usp=drivesdk

**Comment by minhcasi** [comment]
ok, share us your expo link, the google link above is locked - thanks

**Comment by hadi13** [comment]
it is here
https://drive.google.com/file/d/11k92feUH5gUsa9ArEj5JFLuavUafXI1I/view?usp=sharing

**Comment by minhcasi** [comment]
downloaded - we will have a check - thanks

**Comment by hadi13** [comment]
check also issue with new regeneration or logging in
issue with comments not delivered to admin panel ???

**Comment by hadi13** [comment]
Any updates?

**Comment by hadi13** [comment]
Guys please reply, I really need the solution asap

**Comment by minhcasi** [comment]
Hi, our team is checking your issues, they will get back on tomorrow - thanks

**Comment by hadi13** [comment]
Still??!

**Comment by minhcasi** [comment]
Hi @hadi13 looks like you guys change a lot of files that caused the issues - see the screenshot list of file change - https://gyazo.com/dd7f78c6947b9a4f7bd73167208f66b8

As this project was modified and most of the feature has been changed that will not include from our support scope

The solution, try to compare with the fresh download to find out the issue by yourself - thanks

**Comment by hadi13** [comment]
for sure I will change as what I want, I bought the project for this reason, and your support team should solve the issues if any

**Comment by minhcasi** [comment]
Yes, you can customize base on business and make sure the customize will not cause the issue. As per our investigate, there was some custom navigate index from the post detail that causes the issue.

Please try to compare the change as our solution to fix the issue, or you can try with our fresh demo that not having this issues, we only guaranty and support to fix any bug from with a non-customize project

Very best!

**Comment by hadi13** [comment]
please I am struggling with this issue, I will pay you for this fix, please fix it and will pay your efforts

**Comment by minhcasi** [comment]
okay, give us a time to check and get back on early next week - thank you!

**Comment by hadi13** [comment]
ohhhh, next week!! please I waiting now 2 weeks for this issue to be resolved !? please I need it urgent

**Comment by minhcasi** [comment]
Are you ok if we check on Monday as the team is off over the weekend? Thanks

**Comment by hadi13** [comment]
I am ok if you can solve it in the next couple of hours please, this issue is stopping me from publishing my app

**Comment by hadi13** [comment]
Expect to have a reply from you today

**Comment by minhcasi** [comment]
@hadi13  pls try to override this file to the container/PostDetail/index.js file will fix the issue on Android - https://www.dropbox.com/s/csdsrysay9ud26d/index.js?dl=0

There was mess up the PostDetail from your code that we do not understand your logic behind, try to just show single post instead will be fixed the issues, the horizontal scroll effect from Flatlist is also having the buggy issue at current version - thanks

**Comment by hadi13** [comment]
ok it is fixed, 
but I have another issue since the first time, the comments are not delivered to the WP admin?

**Comment by hadi13** [comment]
You can use this 
Admin panel http://hhz20.co/KHN/wp-login.php

Login
user
aTaue@pXtvMuGZ%D#dYZ*63D

Moreover the issue for showing different post still there when I scroll down and open old posts

**Comment by hadi13** [comment]
guys I am using your fresh copy without any changes and I have issues on the related posts, when I click sometimes it does not show anything and sometimes it open different post 

please check
