### ISSUE TITLE
[beonews-pro] - How to display login page after apps has been logout?

### ISSUE THREAD

**Issue by Cod3Guy** [inspireui/support#2520]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: I have set "RequiredLogin"= true in the Config.js, after I logged out, kill the apps and reopen the apps again, it still route back to the HomeScreen instead of Login screen. How to handle the login session for this beonews apps?

2. Screenshots issues (required):
<img width="365" alt="Screenshot 2020-04-02 at 12 16 54 PM" src="https://user-images.githubusercontent.com/10850622/78210190-01337c80-74dc-11ea-9c49-37b9d96b575d.png">

3. Proof of my purchased (required): 
Date: 26 Jan 2020
Invoice No: IVIP36220468
Order No: 119399406
Purchase code: 77105d26-b9ad-416f-883b-16af6a48cab3

3. Config files (required)

[Config.js 2.zip](https://github.com/inspireui/support/files/4418856/Config.js.2.zip)

**Comment by minhcasi** [comment]
@luyx2412 - please help for investigating - thank you!

**Comment by luyx2412** [comment]
HI @Cod3Guy I just tested the config and everything worked normal. Can you give me the beonews version. Or can you debug log in `App/RootRouter.js` line 85 follow the screenshot to check your `isLoggedIn` variable.
![image](https://user-images.githubusercontent.com/8909619/78420697-b05a8a00-767b-11ea-88c2-82f5aaa34a42.png)

Thanks

**Comment by Cod3Guy** [comment]
Hi, I'm using BeoNew version 3.0.6 Pro, and I have logged "isLoggedIn" as per your request.
I get the same value even after log out and open the apps again

`Luyx::RootRouter->componentDidMount->isLoggedIn {"displayName": "admin", "email": "admin@gmail.com", "jwtToken": "wordpressLoggined.token", "photoURL": "admin", "userId": "admin"}`

Issue still the same even after I logged out and open the apps again, it still route back to home screen

Thanks

**Comment by luyx2412** [comment]
Hi @Cod3Guy Can you send me your project via luyxtran264@gmail.com?

Thanks

**Comment by Cod3Guy** [comment]
Hi Inspireui/Support,

Please find the attached file for the code.
Just additional info, I have made some changes on UserModal.prototype.login in
UserModal.js to hardcode some of the login, as I wanted to use my own login
system.
 beonews-pro.zip
<https://drive.google.com/file/d/1V792YrHPTY7mWudSN5L_Yb2IoOwvO64M/view?usp=drive_web>


Regards,
Win Hong

**Comment by luyx2412** [comment]
Hi @Cod3Guy Please do not share link in this ticket. Please send via my email the source code or your personal information.

I downloaded your source code and will investigate your issue.

Thanks

**Comment by luyx2412** [comment]
Hi @Cod3Guy Can you share me the account to login your app?  to investigate easier? Please send me via luyxtran264@gmail.com

Thanks
