### ISSUE TITLE
[FluxNews] - How to show a page or post instead category

### ISSUE THREAD

**Issue by patriciocifuentes** [inspireui/support#2521]
---------

1. My issue: 
- Hi i need to know how to show instead a category a page post from my wordpress, this is because i need to show a "Who we are" page. I try to change the category number by post number; but i get one of uncategorized blog post.
Please your help.

2. Screenshots issues (required):
<img width="1680" alt="Screen Shot 2020-04-01 at 23 17 42" src="https://user-images.githubusercontent.com/488461/78213186-1c1bd780-746f-11ea-8a9b-b116d624637b.png">

3. Proof of my purchased (required):
<img width="1680" alt="comprado" src="https://user-images.githubusercontent.com/488461/78213202-2ccc4d80-746f-11ea-8ea2-83389493a1db.png">

3. Config files (required)
[Archive.zip](https://github.com/inspireui/support/files/4419016/Archive.zip)

**Comment by patriciocifuentes** [comment]
Ok, i don't receive a response yet, i hope you help me ASAP; but i have another question more, how can i add a image as background in the "left menu side"

<img width="1680" alt="Screen Shot 2020-04-02 at 22 34 35" src="https://user-images.githubusercontent.com/488461/78324532-2ce15180-7532-11ea-96cf-082c376c1a7f.png">

**Comment by minhcasi** [comment]
@patriciocifuentes - the left menu could be customized from tabbar.dart file

**Comment by minhcasi** [comment]
This script could support to show the page "who we are" from webview 

import 'widgets/common/webview.dart';
....
ListTile(
                  leading: const Icon(
                    Icons.public,
                    size: 20,
                  ),
                  title: Text('Custom Page'),
                  onTap: () {
                    Navigator.push(
                        context,
                        MaterialPageRoute(
                            builder: (context) => WebView(
                                url: "https://inspireui.com/who-we-are",
                                title: "About Us")));
                  },
                ),

**Comment by graphicdestination** [comment]
What if we have 50 pages, we can't keep writing views for all the 50 pages, why this is not coming from API, in BeoNews all the pages are pulled via API, why not in flutter????????

**Comment by graphicdestination** [comment]
How do we pull page contents using IDs??????  Can that be done?????

**Comment by minhcasi** [comment]
Confirm to add new Feature allow loading page via API - will also note to document as well - thanks

**Comment by dttrung26** [comment]
This request will be added in FluxNews in the next patch. Thanks for your report!

**Comment by graphicdestination** [comment]
Thanks for the update, really appreciate it.

**Comment by graphicdestination** [comment]
Any ETA when the new version of the code will be pushed out?  Also any ETA
of the new Flux Builder?

**Comment by graphicdestination** [comment]
Hello.  Any ETA when the new version of the code will be pushed out?  Also
any ETA of the new Flux Builder?
