### ISSUE TITLE
[FluxStore Listing] - Short questions

### ISSUE THREAD

**Issue by cschng96** [inspireui/support#2523]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: I have attached and arranged the screenshots for each issue. 
a. First screenshot. How to find my forget password URL of my website? I am using ListingPro for my website theme.
b. Second screenshot. In the demo, there is a blog button where we can see the blog. How to make that exists in my app? I have circled the section in my second screenshot. And, how to add string below the logo? e.g. below the search logo, I want to add the string "search".
c. Third screenshot. How to hide the email address and the widget? I have draw arrows for both. And, when I log in and submit a review, it did not successfully submit. The review does not show on both apps and my website. Also, for each listing, there are couples of images but in the app, it can only show image for each listing. 

2. Screenshots issues (required):
a. <img width="319" alt="Screen Shot 2020-04-02 at 2 01 18 PM" src="https://user-images.githubusercontent.com/51393098/78216603-d3a2ff00-74ec-11ea-90ba-677628bb57f1.png">
b. <img width="313" alt="Screen Shot 2020-04-02 at 2 02 33 PM" src="https://user-images.githubusercontent.com/51393098/78216609-d56cc280-74ec-11ea-90fe-e207abd412bb.png">
c. <img width="327" alt="Screen Shot 2020-04-02 at 2 03 08 PM" src="https://user-images.githubusercontent.com/51393098/78216614-d7cf1c80-74ec-11ea-9bc0-72d0c837640e.png">

3. Proof of my purchased (required):
<img width="856" alt="Screen Shot 2020-04-01 at 6 59 35 PM" src="https://user-images.githubusercontent.com/51393098/78216667-f03f3700-74ec-11ea-9ba6-115eeb519b22.png">

3. Config files (required)
[lib.zip](https://github.com/inspireui/support/files/4419188/lib.zip)

**Comment by minhcasi** [comment]
@cschng96 - please help to move the content to your same ticket #2522 - thank you!

**Comment by cschng96** [comment]
done. Thank you!
