### ISSUE TITLE
 error on rub in emulators - Unable to resolve "./vendor/react-native-vector-icons/glyphmaps/MaterialCommunityIcons.json" from "src/Expo/vector-icons/MaterialCommunityIcons.js" Failed building JavaScript bundle.

### ISSUE THREAD

**Issue by areejQ** [inspireui/support#2524]
error on rub in emulators -
 Unable to resolve "./vendor/react-native-vector-icons/glyphmaps/MaterialCommunityIcons.json" from "src/Expo/vector-icons/MaterialCommunityIcons.js" Failed building JavaScript bundle.

**Comment by minhcasi** [comment]
Hi, thank you for the feedback. Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads it's used to verify your proof of purchase? 
Sorry for any inconvenience, we will reopen the ticket when it is verified, thank you!
