### ISSUE TITLE
[Fluxstore] - 

### ISSUE THREAD

**Issue by Saifahmad99** [inspireui/support#2525]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: Cant run app

2. Screenshots issues (required):
![Screenshot (95)](https://user-images.githubusercontent.com/59877416/78225430-ce8f8100-74e7-11ea-8209-659f56f35f8e.png)

3. Proof of my purchased (required):
![Screenshot (80)](https://user-images.githubusercontent.com/59877416/78225448-dd763380-74e7-11ea-89b6-11884f0333a4.png)

3. Config files (required)

**Comment by minhcasi** [comment]
@Saifahmad99 - please double-check the Flutter SDK path setting on Android Studio - https://tppr.me/pt05q

Also clean up the cache https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

**Comment by Saifahmad99** [comment]
![Screenshot (96)](https://user-images.githubusercontent.com/59877416/78261380-cb62b800-751c-11ea-9c3a-12f9069721da.png)
this came when i tried to run the flutter clean

**Comment by minhcasi** [comment]
@Saifahmad99 -  please help to download the latest version 1.6.6 to fix the build issue - we also note some detail here - https://medium.com/@inspireui/announcing-fluxstore-1-6-337efff1791f
