### ISSUE TITLE
wocomerce- plugin having lot of issues

### ISSUE THREAD

**Issue by nachinazar** [inspireui/support#2527]
We are facing the following issues :-

1.	If cart is empty – should not go to the payment page (disable swipe)
2.	Guest payment- is not working
3.	Google sign-, profile pic is not coming 
4.	Arabic translation – if we disable cache it will work properly other wise main Arabic translation file not working
5.	Product - see all -no working
6.	category page – swipe down- Loading icon is not hiding

**Comment by minhcasi** [comment]
Hi, thank you for the feedback. Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads it's used to verify your proof of purchase? 
Sorry for any inconvenience, we will reopen the ticket when it is verified, thank you!
