### ISSUE TITLE
Mstore-MV The product image is stretching

### ISSUE THREAD

**Issue by inimist** [inspireui/support#2528]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: The product image is stretching. in the Home screen and the ProductRow screen.

2. Screenshots issues (required):  
![Screenshot_2020-04-02-14-45-14-49_f73b71075b1de7323614b647fe394240](https://user-images.githubusercontent.com/447618/78232178-7d848a80-74f1-11ea-9e98-c5e5818effc2.jpg)
 
![Screenshot_2020-04-02-14-54-09-05_f73b71075b1de7323614b647fe394240](https://user-images.githubusercontent.com/447618/78232421-d9e7aa00-74f1-11ea-8c04-07cf99d87a3a.jpg)

3. Proof of my purchased (required):

![76964872-65d1d180-6949-11ea-9687-d2b778d05d0a](https://user-images.githubusercontent.com/447618/78232217-8d03d380-74f1-11ea-924b-c898ee310d13.png)

3. Config files (required) : 
[common.zip](https://github.com/inspireui/support/files/4420030/common.zip)

**Comment by luyx2412** [comment]
Hi @inimist In `src/containers/Category/ProductRow.js` line 178 which is the style of ImageCache component --> please add `resizeMode: "contain"` to fix your issue.
![image](https://user-images.githubusercontent.com/8909619/78420445-6f617600-7679-11ea-9960-61828d0f18d7.png)
And this is a document about the Image with `resizeMode` https://reactnative.dev/docs/image#style

Thanks

**Comment by inimist** [comment]
Hey @luyx2412, I already have used the property but this is still not working
![image](https://user-images.githubusercontent.com/447618/78420627-6cad5380-766e-11ea-8b15-3c776a0b326f.png)
.

**Comment by luyx2412** [comment]
HI @inimist In each image style please add `resizeMode: "contain"` to fix the issue. Because currently i don't know you used what's type layout. Please see the screenshot.

![image](https://user-images.githubusercontent.com/8909619/78682802-a86b4600-7918-11ea-8166-1ff3784ae3ab.png)

Thanks
