### ISSUE TITLE
Product Price & Options

### ISSUE THREAD

**Issue by alicankarakus** [inspireui/support#2529]
How can i display special price and options? 

![options](https://user-images.githubusercontent.com/6725793/78238559-6475dc80-74e5-11ea-9850-865bdacf4c29.PNG)
![order](https://user-images.githubusercontent.com/6725793/78238564-66d83680-74e5-11ea-939b-26ae399e1add.PNG)
![mobile](https://user-images.githubusercontent.com/6725793/78238656-7fe0e780-74e5-11ea-8fd5-27c15fd263a8.PNG)

**Comment by alicankarakus** [comment]
And i have a new problem. 

How can i add payment method? We have a different payment method. But i have an api key and secret key. 

but how can i install this app i don't know...

**Comment by kvt0012** [comment]
Dear sir, if it's available on your api, you can fetch it on this.

**Comment by kvt0012** [comment]
Dear sir, can you use the extra plugin? Thanks

**Comment by alicankarakus** [comment]
"Dear sir, if it's available on your api, you can fetch it on this."
Yeah it's available bu it is not working. redirecting to the shopping page again.


"Dear sir, can you use the extra plugin? Thanks" 
Yeah i'm using options module. For (*) (/) (=) (+%) (-%) (=%) not just (+) and (-)

**Comment by alicankarakus** [comment]
Hey again. 
I changed url for without options module. But it is still not wirking.

**Comment by alicankarakus** [comment]
Your demo url and this problem !

![hata](https://user-images.githubusercontent.com/6725793/78334698-e8d36880-7594-11ea-9d81-f74933bdf7ec.PNG)

**Comment by alicankarakus** [comment]
new update and still problem. no options no special prices

**Comment by kvt0012** [comment]
@minhtruong315  Dear brother, can you help him with open-cart api? 
Thank you :D

**Comment by alicankarakus** [comment]
heyy

**Comment by minhcasi** [comment]
@alicankarakus - we are working on new update of Opencart, it will be available soon (also fix this pricing issue) - thank you!

@minhtruong315 - pls investigating

**Comment by minhtruong315** [comment]
@alicankarakus send me config files to check pricing issue. Thanks

**Comment by alicankarakus** [comment]
@minhtruong315 you don't need it. Only your demo work should work stably. After that i can change all of project. But it doesn't work literally.

**Comment by minhtruong315** [comment]
@alicankarakus I fixed this issue. it'll be available in next release. Thanks for your report

**Comment by harrisbaitalrayan** [comment]
Hi guys, I also faced this issue with options and special price in opencart. Can you please advice when the new release will be available ?
