### ISSUE TITLE
[ListApp] Featured icons not working while clicking its occurs error - mylisting theme

### ISSUE THREAD

**Issue by Pavithran10** [inspireui/support#253]
**Mandatory Info (please complete the following information):**
Product:[ListApp]
Version:1.6.1
Theme: MyListing

**Describe the issues**
I need help while selecting each categories list item its redirect to booking page in that page favourites and share icon while clicking it showing the error msg. I've attached that booking page and error page in below link

**Screenshots**
[error pages.zip](https://github.com/inspireui/support/files/2826756/error.pages.zip)

**Additional context**

**Comment by Pavithran10** [comment]
Anybody is there? I didn't get any solution for this error....

**Comment by Pavithran10** [comment]
hi, I need a help. please, check my error.

**Comment by Pavithran10** [comment]
sry, I checked your comment.

**Comment by Pavithran10** [comment]
hi, In booking categories list page favourite icon is not working. it shows error.
![list booking1](https://user-images.githubusercontent.com/46148046/52546508-fa344100-2de5-11e9-81a0-ca8b0dd60541.jpg)
![favourites icon err](https://user-images.githubusercontent.com/46148046/52546512-ff918b80-2de5-11e9-987b-606229335c70.png)

**Comment by thangvo9x** [comment]
Hi. This is a bug . We'll update it ASAP. Thanks for your value feedback.

**Comment by thangvo9x** [comment]
Try this way 
https://github.com/inspireui/support/issues/184#issuecomment-462219650
Thanks

**Comment by Pavithran10** [comment]
I checked your link. In that i need to changed that button.txt code into button.js page

**Comment by thangvo9x** [comment]
It'll fix the error "props.onPress is not a function" when clicking on heart button.
