### ISSUE TITLE
[Fluxstore Woo] - I cant change language to Turkish

### ISSUE THREAD

**Issue by ykarapanca** [inspireui/support#2530]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
I cant change the language to Turkish. . I have followed up every instruction but i guess im doing something wrong. Please help me out with this. 
2. Screenshots issues (required):
![image](https://user-images.githubusercontent.com/58140554/78257249-466aa500-7502-11ea-96d2-e3bc41874d9d.png)
![image](https://user-images.githubusercontent.com/58140554/78257300-597d7500-7502-11ea-9827-b3ceed89d0f0.png)

3. Proof of my purchased (required):
![image](https://user-images.githubusercontent.com/58140554/78257418-79ad3400-7502-11ea-95d4-be97edb8af40.png)

3. Config files (required)
- removed

**Comment by minhcasi** [comment]
@ykarapanca - please help us to share only the common and config folder here, don't share the whole lib folder  :)

**Comment by ykarapanca** [comment]
You are right:) But i have managed to do this by changing one of the default languages:)

**Comment by minhcasi** [comment]
@ykarapanca - would you mind sharing this language file so that we will include it as officially from the app - we are working on a new script to help to add/remove language easier - thank you!

**Comment by ykarapanca** [comment]
Sure why not:) 
[lang_tr.zip](https://github.com/inspireui/support/files/4468819/lang_tr.zip)

**Comment by minhcasi** [comment]
Appreciated for your help
