### ISSUE TITLE
[fluxstore]- Unable to connect to firebase

### ISSUE THREAD

**Issue by tjain90** [inspireui/support#2531]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: I have done all the settings mentioned on document. But i am unable to use my firebase in signup, push notification, etc

2. Screenshots issues (required):

3. Proof of my purchased (required): tjain90@gmail.com from themeforest

3. Config files (required)

**Comment by minhcasi** [comment]
@tjain90 - could you help to check this detailed guide - https://docs.inspireui.com/fluxstore/sign-in/ - thank you!

**Comment by tjain90** [comment]
> @tjain90 - could you help to check this detailed guide - https://docs.inspireui.com/fluxstore/sign-in/ - thank you!

Hi Team. I have already checked and configured as instructed. 
Attached Screen shot of error i am getting.
![Screenshot_20200403-083639](https://user-images.githubusercontent.com/6376301/78320572-642e1d80-7587-11ea-9c57-974c835b7b8b.jpg)

**Comment by minhcasi** [comment]
@tjain90 - please read the link above, there is the section to guide how to fix the SHA issue - https://tppr.me/XRtTV 

You can also see this video guide - https://www.youtube.com/watch?v=C_9mk_MmvOQ&t=73s

**Comment by tjain90** [comment]
@minhcasi I have done all the settings. 
it was working fine when I uploaded on Google Play and then used sha key provided by play stote and updated that key to firebase console. but when we have downloaded Google services file from firebase and updated on app then it stopped working. you can check live app available on  play store in the name of Indidecor

now it is showing an error with "invalid api" or wrong authentication.
