### ISSUE TITLE
App crashing, new collection and latest product data

### ISSUE THREAD

**Issue by qorane099** [inspireui/support#2533]
l did config all files correctly and l was getting website data.

1. the app started to crash today and shows nothing, no catogories and no data.

before today the app was fine and it was showing catogories data.

please see screenshot attached.

2. l was getting 
![IMG_20200322_005709](https://user-images.githubusercontent.com/39888242/78263083-1f6e9c00-751f-11ea-9344-0b3c2e68396d.jpg)
![Uploading IMG_20200402_185743.jpg…]()

catogories fine but when l try to implement new collection and latest product no data is showing.

**Comment by minhcasi** [comment]
@qorane099 - could you help to share the common / config folder - we will help for checking - thanks

**Comment by qorane099** [comment]
where can l send you

**Comment by trunghieuvn** [comment]
Hi @qorane099 , You can compress the folder into a zip file and send it here.

**Comment by minhcasi** [comment]
@qorane099 - please drag the zip to share here and reopen this ticket - thanks
