### ISSUE TITLE
[Fluxstore Pro] - Need Help with New Language

### ISSUE THREAD

**Issue by san2pedro** [inspireui/support#2534]
Hey Need Help With Add New Language Hebrew .
And Add RTL and Make Main Language.
auto generation work but dont understand:

> Create a new Language setting from the Profile screen by cloning new Card Widget from lib/screens/language.dart (make sure to create a new language flag image and save to assets/images/country).

![Screenshot_2](https://user-images.githubusercontent.com/13208693/78265452-1ffe3700-750d-11ea-887d-55fad6f76c70.png)
![121212](https://user-images.githubusercontent.com/13208693/78265461-21c7fa80-750d-11ea-8acb-c4339665975c.png)
![123123123](https://user-images.githubusercontent.com/13208693/78265464-21c7fa80-750d-11ea-917e-9817c8ba0ab8.png)
![25235235](https://user-images.githubusercontent.com/13208693/78265466-22609100-750d-11ea-8562-57f8c39f36a1.png)
![Screenshot_1](https://user-images.githubusercontent.com/13208693/78265470-22609100-750d-11ea-853f-8f601806bc5f.png)

**Comment by san2pedro** [comment]
any help can send me via email  punk4web@gmail.com

**Comment by minhcasi** [comment]
@san2pedro - please read the guide from this plugin you will understand more about Flutter Intl plugin - https://plugins.jetbrains.com/plugin/13666-flutter-intl - thank you!

**Comment by minhcasi** [comment]
@san2pedro - would you mind sharing this language file so that we will include it as officially from the app - we are working on a new script to help to add/remove language easier - thank you!

**Comment by san2pedro** [comment]
Will send you have 60% complete but you have mistake Doc.


пн, 13 апр. 2020 г., 04:48 Minh Pham <notifications@github.com>:
