### ISSUE TITLE
IOS Notification can't display 

### ISSUE THREAD

**Issue by emresutuna** [inspireui/support#2535]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
Push Notification didn't display in notification bar but displayed onResume in app.
![WhatsApp Image 2020-03-12 at 10 50 34 (1)](https://user-images.githubusercontent.com/35627584/78265691-78cdcf80-750d-11ea-84b8-f78fec12049e.jpeg)

2. Screenshots issues (required):

3. Proof of my purchased (required):

3. Config files (required)

**Comment by minhcasi** [comment]
@emresutuna - could i know which push notification you are using (Firebase or Onesignal) ?

**Comment by emresutuna** [comment]
I tried for firebase.

**Comment by minhcasi** [comment]
@trunghieuvn - please help to investigate this issue, it could relate to #2549 - we could make a new video to guide step by step of setting up push notification

**Comment by sketchuprzr** [comment]
I have this problem. There is no problem on Android. Firebase Push Notification is working incorrectly on iOS too.
There is no notification when the application is in the background. But when the app is open, notification is coming.

**Comment by emresutuna** [comment]
I tried firebase and onesignal but the problem is the same.(Firebase)There is no notification when the application is in the background. But when the app is open, notification is coming.
(OneSignal)Can't receiving notification.

**Comment by sketchuprzr** [comment]
#2564

**Comment by trunghieuvn** [comment]
Hi @sketchuprzr , I will close this ticket and focus on supporting the [#2564](https://github.com/inspireui/support/issues/2564) ticket
