### ISSUE TITLE
Fluxstore 1.6.5c - Related to paging on products listing page.

### ISSUE THREAD

**Issue by Isodie** [inspireui/support#2536]
Purchase code
5b81a1f1-b6f8-41d7-a4a8-169532748691

Bug related to paging on products listing page.

_How to reproduce bug._

I am referring to demo app.
Go to category page and select  Men -> Shirts(12 items).
Now scroll down till all products are loaded within that subcategory then select "Jeans man(24 items)" from Appbar on same page. After loading first 10 items next items will not be loaded even though it has 24 items.

It seem page parameter in not reseted when new subcategory is selected from Appbar.
Also can you please change number of items loaded from 10 to 20.

**Comment by trunghieuvn** [comment]
Hi @Isodie 
, could you help to share the common/config folder. We will help for checking. Thanks

**Comment by Isodie** [comment]
I am using demo app configs.
check this video I have reproduced bug.
https://photos.app.goo.gl/LaZfFxbveqwKwUCB7

**Comment by trunghieuvn** [comment]
To fix this error please follow these steps:

Step 1: remove the variable `_page` in the file` lib/widgets/product/product_list.dart`

![image](https://user-images.githubusercontent.com/19247680/78332351-137fea00-75b2-11ea-950b-81fac3ddbeab.png)

Step 2:  Add the variable `_page` (default value is 1)
![image](https://user-images.githubusercontent.com/19247680/78333353-e2081e00-75b3-11ea-8f6f-7944c9311634.png)

 to the`lib/screens/products/products.dart` file at:
- function `onRefresh`

![image](https://user-images.githubusercontent.com/19247680/78333266-b2f1ac80-75b3-11ea-9180-a9d32703a821.png)

- function `onLoadMore` (old: `void onLoadMore(page)` -> new: `void onLoadMore()`)

![image](https://user-images.githubusercontent.com/19247680/78333236-a79e8100-75b3-11ea-83b7-d742617a9751.png)

- function `_renderItemCategory` 

![image](https://user-images.githubusercontent.com/19247680/78333297-c43ab900-75b3-11ea-9e0f-34e7f70656c0.png)
