### ISSUE TITLE
Cant run flutter app - missing mock files

### ISSUE THREAD

**Issue by redamakarem** [inspireui/support#2539]
Hello InspireUI
When I try to run the app I get the following error message:
Target debug_android_application failed: FileSystemException: Cannot copy file to 'C:\Users\GeneralSenses\Downloads\codecanyon-ALePLZao-fluxstore-the-universal-woocommerce-magento-opencart-mobile-app-by-flutter-framework\FluxStore 1.6.5c\source\build\app\intermediates\flutter\debug\flutter_assets\lib\config\mocks\fetch_product_by_category.json', path = 'C:\Users\XXXXXX\Downloads\codecanyon-ALePLZao-fluxstore-the-universal-woocommerce-magento-opencart-mobile-app-by-flutter-framework\FluxStore 1.6.5c\source\lib\config\mocks\fetch_product_by_category.json' (OS Error: The system cannot find the path specified.

I tried finding the json file manually but it indeed did not exist
Please advise
Cant wait to start using your product
![Screenshot (6)](https://user-images.githubusercontent.com/9447486/78318749-3b4d5e80-756e-11ea-8d09-0f8ed6f6b5ec.png)

**Comment by minhcasi** [comment]
please update the latest 1.6.6 to fix build issue, we also note the detail on this changelog blog - https://medium.com/@inspireui/announcing-fluxstore-1-6-337efff1791f - thank you!

**Comment by redamakarem** [comment]
Hello again,
I did download the latest version and im now getting a few errors. Looking at the error logs, I can see that most of the errors are due to custom colors that the app flags as undefined. The image below is a snapshot of the error logs:
![image](https://user-images.githubusercontent.com/9447486/78367077-31594900-75ca-11ea-9e7d-f61a53893a8c.png)
Appreciate your support

**Comment by redamakarem** [comment]
Update:
I managed to fix the color related issues by adding the appropriate import statements
Now I am facing errors related to undefined attributes and methods:
![image](https://user-images.githubusercontent.com/9447486/78369839-8008e200-75ce-11ea-9881-5c3766f2cb28.png)
Thanks again

**Comment by minhcasi** [comment]
@redamakarem - please note that the latest version has updated the folder of config and constants - https://tppr.me/AcdT7 - please help to compare with the original download package if you have updated your config files - thanks

**Comment by redamakarem** [comment]
I have an extra route_constants.dart file. Removing it increases the number of errors xD
Please help me get the app running and ill be forever thankful

**Comment by redamakarem** [comment]
I have re-downloaded the package again and still getting errors. Just wanted to update you

**Comment by redamakarem** [comment]
I strongly suggest that you download the package so that you can get the same issues that I am facing
Thanks

**Comment by redamakarem** [comment]
I was able to fix all errors (by fixing import  @statements) except the one below:
The getter 'password' isn't defined for the class 'User'.
Try importing the library that defines 'password', correcting the name to the name of an existing getter, or defining a getter or field named 'password'. 
File: user_update.dart
Please help me address this issue
Thanks @minhcasi

**Comment by redamakarem** [comment]
please add me on Skype: makarem.reda@gmail.com
There are loads of issues in the app
I am starting to get frustrated

**Comment by minhcasi** [comment]
@minhtruong315 - please help to support this issue

**Comment by minhcasi** [comment]
I'm sorry for the build issue, please help to download the latest 1.6.6b, there is new cool One-Page-Checkout via Webview feature have been added.

Also, upload the detail file change from Gitlab, if you have not accessed to the repo, please submit this link https://docs.google.com/forms/d/e/1FAIpQLSeuBqUkScy42V7KKhfNPj0fl581anrB1mWkbMa3p2WQt7fhfw/viewform

**Comment by redamakarem** [comment]
I submitted the Google Form
Thanks

**Comment by redamakarem** [comment]
I downloaded the newest version of the app now. The size is around 5 times smaller than the previous version I had downloaded. The new version has no error when I open the project. However, when I run the project, I get the following error message:
Target debug_android_application failed: FileSystemException: Cannot copy file to 'C:\Users\XXXXX\Downloads\codecanyon-G14zldUe-fluxstore-the-universal-woocommerce-magento-opencart-mobile-app-by-flutter-framework\FluxStore 1.6.6b\source\build\app\intermediates\flutter\debug\flutter_assets\lib\config\mocks\fetch_product_by_category.json', path = 'C:\Users\XXXXX\Downloads\codecanyon-G14zldUe-fluxstore-the-universal-woocommerce-magento-opencart-mobile-app-by-flutter-framework\FluxStore 1.6.6b\source\lib\config\mocks\fetch_product_by_category.json' (OS Error: The system cannot find the path specified.
, errno = 3)
build failed.
Thanks

**Comment by redamakarem** [comment]
@minhcasi  please respond...I have been fixing errors for 3 days. As a customer, I am supposed to download the app, configure and run it smoothly. This is unacceptable

**Comment by minhcasi** [comment]
@redamakarem - it seems there is the path issue on your Android OS

we could help for remoting to help resolve this issue, are you available today 9:00am to 5:pm GMT+7 ?

**Comment by minhcasi** [comment]
@minhtruong315 - pls help for checking

**Comment by minhcasi** [comment]
[Archive.zip](https://github.com/inspireui/support/files/4435429/Archive.zip)

Also, try to override this common / config to your lib folder - thanks

**Comment by redamakarem** [comment]
I am available anytime. Add me on skype : makarem.reda@gmail.com
Thanks

**Comment by redamakarem** [comment]
I replaced the files in the project with the ones in the archive provided but im still getting the same error. Could you please elaborate about the Android path issue you mentioned? 
Thanks @minhcasi

**Comment by minhtruong315** [comment]
@redamakarem I added your skype. pls check

**Comment by redamakarem** [comment]
UPDATE: The path issue was solved by moving the project to another location so that the full path is shorter and has no spaces. Thanks a lot for the support

**Comment by redamakarem** [comment]
When I started using the mobile app, I noticed that the currency is still in USD although I changed it to KWD in my Magento store. Please fix this issue.
Thanks again for the good support

**Comment by minhtruong315** [comment]
@redamakarem You need to change in config as well https://tppr.me/FjRma

**Comment by redamakarem** [comment]
I just tried what you suggested and it works. Many thanks
Another question. How can I make the categories in the top of the homepage dynamic?. As of now, they are not showing the categories in my Magento store.
Thanks

**Comment by redamakarem** [comment]
Another question:
How can I assign an image to the categories in the category tab in the app? Right now it shows a placeholder image.
Thanks

**Comment by redamakarem** [comment]
the app now shows the products and all looks good. I can add items to cart successfully but when I try to checkout nothing happens. When I ran the app in debug mode and pressed checkout, I saw these messages in the console:
E/flutter (17051): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Scaffold.of() called with a context that does not contain a Scaffold.
E/flutter (17051): No Scaffold ancestor could be found starting from the context that was passed to Scaffold.of(). This usually happens when the context provided is from the same StatefulWidget as that whose build function actually creates the Scaffold widget being sought.
E/flutter (17051): There are several ways to avoid this problem. The simplest is to use a Builder to get a context that is "under" the Scaffold. For an example of this, please see the documentation for Scaffold.of():
E/flutter (17051):   https://api.flutter.dev/flutter/material/Scaffold/of.html
E/flutter (17051): A more efficient solution is to split your build function into several widgets. This introduces a new context from which you can obtain the Scaffold. In this solution, you would have an outer widget that creates the Scaffold populated by instances of your new inner widgets, and then in these inner widgets you would use Scaffold.of().
E/flutter (17051): A less elegant but more expedient solution is assign a GlobalKey to the Scaffold, then use the key.currentState property to obtain the ScaffoldState rather than using the Scaffold.of() function.
E/flutter (17051): The context used was:
E/flutter (17051):   MyCart
E/flutter (17051): #0      Scaffold.of 
package:flutter/…/material/scaffold.dart:1316
E/flutter (17051): #1      _MyCartState.doCheckout.<anonymous closure> 
package:fstore/…/cart/my_cart.dart:387
E/flutter (17051): #2      new Future.delayed.<anonymous closure>  (dart:async/future.dart:316:39)
E/flutter (17051): #3      _rootRun  (dart:async/zone.dart:1122:38)
E/flutter (17051): #4      _CustomZone.run  (dart:async/zone.dart:1023:19)
E/flutter (17051): #5      _CustomZone.runGuarded  (dart:async/zone.dart:925:7)
E/flutter (17051): #6      _CustomZone.bindCallbackGuarded.<anonymous closure>  (dart:async/zone.dart:965:23)
E/flutter (17051): #7      _rootRun  (dart:async/zone.dart:1126:13)
E/flutter (17051): #8      _CustomZone.run  (dart:async/zone.dart:1023:19)
E/flutter (17051): #9      _CustomZone.bindCallback.<anonymous closure>  (dart:async/zone.dart:949:23)
E/flutter (17051): #10     Timer._createTimer.<anonymous closure>  (dart:async-patch/timer_patch.dart:23:15)
E/flutter (17051): #11     _Timer._runTimers  (dart:isolate-patch/timer_impl.dart:384:19)
E/flutter (17051): #12     _Timer._handleMessage  (dart:isolate-patch/timer_impl.dart:418:5)
E/flutter (17051): #13     _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:174:12)

Note: I did not change anything in code
Thanks :)

**Comment by minhtruong315** [comment]
@redamakarem can u record screen?

**Comment by redamakarem** [comment]
Hello @minhtruong315 
There's nothing to record because nothing happens when I checkout, the button press does nothing
Thanks

**Comment by redamakarem** [comment]
@minhtruong315 I managed to resolve the context issue using the suggestion in the link below:
https://github.com/flutter/flutter/issues/17097#issuecomment-501762525
Thanks

**Comment by redamakarem** [comment]
Can you please let me know how to resolve the issue: https://github.com/inspireui/support/issues/2539#issuecomment-609925620
Thanks

**Comment by minhtruong315** [comment]
@redamakarem replace getCategories function in services/magento.dart like this
```
@override
  Future<List<Category>> getCategories({lang}) async {
    try {
      var response = await http.get(
          MagentoHelper.buildUrl(domain, "mstore/categories", lang),
          headers: {'Authorization': 'Bearer ' + accessToken});
      List<Category> list = [];
      if (response.statusCode == 200) {
        for (var item in convert.jsonDecode(response.body)["children_data"]) {
          var category = Category.fromMagentoJson(item);
          category.parent = 0;
          if (item["image"] != null) {
            category.image = item["image"].toString().contains("pub/media")
                ? "$domain/${item["image"]}"
                : "$domain/pub/media/catalog/category/${item["image"]}";
          }
          list.add(category);

          for (var item1 in item["children_data"]) {
            list.add(Category.fromMagentoJson(item1));

            for (var item2 in item1["children_data"]) {
              list.add(Category.fromMagentoJson(item2));
            }
          }
        }
      }
      return list;
    } catch (e) {
      rethrow;
    }
  }
```

**Comment by redamakarem** [comment]
@minhtruong315 Yes! Your suggestion works! Thanks :)

**Comment by redamakarem** [comment]
![processed1](https://user-images.githubusercontent.com/9447486/78736697-78db2e80-7956-11ea-8f0a-b3a20789e158.jpeg)
![processed](https://user-images.githubusercontent.com/9447486/78736699-7aa4f200-7956-11ea-9b39-8c3fcc505bf9.jpeg)

@minhtruong315 As you can see from the screenshots above, changing the sub category does not change the title.
Please advise
Thanks

**Comment by minhtruong315** [comment]
@redamakarem replace _renderItemCategory function in screens/products/products.dart
```
 Widget _renderItemCategory({int categoryId, String categoryName}) {
    return GestureDetector(
      child: AnimatedContainer(
        duration: Duration(milliseconds: 200),
        padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
        margin: EdgeInsets.symmetric(horizontal: 3),
        decoration: BoxDecoration(
          color:
              newCategoryId == categoryId ? Colors.white24 : Colors.transparent,
          borderRadius: BorderRadius.circular(30),
        ),
        child: Text(
          categoryName.toUpperCase(),
          style: TextStyle(
            fontSize: 12,
            letterSpacing: 0.5,
            fontWeight: FontWeight.w500,
            color: Colors.white,
          ),
        ),
      ),
      onTap: () {
        Provider.of<ProductModel>(context, listen: false)
            .fetchProductsByCategory(
                categoryId: categoryId, categoryName: categoryName);
        setState(() {
          _page = 1;
          newCategoryId = categoryId;
          onFilter(
              minPrice: minPrice,
              maxPrice: maxPrice,
              categoryId: newCategoryId);
        });
      },
    );
  }
```

**Comment by redamakarem** [comment]
@minhtruong315 I followed your instructions and got the following error:
Compiler message:
lib/screens/products/products.dart:274:11: Error: The setter '_page' isn't defined for the class 'ProductsPageState'.
 - 'ProductsPageState' is from 'package:fstore/screens/products/products.dart' ('lib/screens/products/products.dart').
Try correcting the name to the name of an existing setter, or defining a setter or field named '_page'.
          _page = 1;
          ^^^^^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

**Comment by minhtruong315** [comment]
> @minhtruong315 I followed your instructions and got the following error:
> Compiler message:
> lib/screens/products/products.dart:274:11: Error: The setter '_page' isn't defined for the class 'ProductsPageState'.
> 
> * 'ProductsPageState' is from 'package:fstore/screens/products/products.dart' ('lib/screens/products/products.dart').
>   Try correcting the name to the name of an existing setter, or defining a setter or field named '_page'.
>   _page = 1;
>   ^^^^^
>   Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
>   build failed.

Supported to fix this

**Comment by redamakarem** [comment]
![image](https://user-images.githubusercontent.com/9447486/78740543-c019ed00-795f-11ea-9629-e9de0da8cc56.png)
Very well deserved :)

**Comment by redamakarem** [comment]
Hello again,
When I am looking at a list of products and i scroll down, the products get duplicated. 
Thanks

**Comment by sodhanii** [comment]
This happens with me as well. When I refresh the page, products get duplicated.
