### ISSUE TITLE
[Mstore] - Checkout Fields customization

### ISSUE THREAD

**Issue by CloudExpressTeam** [inspireui/support#2540]
Hi, I need a way to make the checkout fields are the same as the WP WooCommerce Checkout fields

I need to use a city as dropdown like the one I created in the WP installation
also I created on WP additional fees based on city selected
so I need to completely display the checkout form of WP not Mstore's one
I use a premium plugin to create these fields

**Comment by minhcasi** [comment]
@CloudExpressTeam - please try to customize the app to meet your Wordpress Checkout fields 

We may not support for customization at this time due to the CoV-9 issues - very best!
