### ISSUE TITLE
[FluxStore-Pro]A couple of problems with the app itself.

### ISSUE THREAD

**Issue by Pascalnhuis** [inspireui/support#2541]
Hi,

I have some problems with the app.

The 3 problems are:
1. The quantity-setting doesn't work in the cart itself. When I want to change the quantity in the cart itself, the app will do nothing. In Android Studio it show a error nul-error or something.

2. Address:
When someone saved his address in our app, he can't select it again. The app shows his history app, but when he is pressing the button, the app will still do nothing. Do you know about that problem?

3. Shipping problems:
When people will place an order over €29,00 the product will be shipped for free. But the app shows  all shippings methodes. Even when someone is placing an order under €29,00 the app still shows the free shipping option. On the website itself I have a code to dissapear the free shipping until the client ordered over €29,00.

Please can you help me with this problems?

Pascal

**Comment by minhcasi** [comment]
Hi, thank you for the feedback. Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads it's used to verify your proof of purchase? 
Sorry for any inconvenience, we will reopen the ticket when it is verified, thank you!

**Comment by Pascalnhuis** [comment]
![Screenshot_20200403_141049_com google android apps docs](https://user-images.githubusercontent.com/62649032/78359376-45468000-75b5-11ea-803f-78caeff076ed.jpg)

**Comment by minhcasi** [comment]
Sorry for the late response as we could not get the notification from this ticket - could you mind to attach the common and config folder so that we could reproduce the above issues?

**Comment by Pascalnhuis** [comment]
Let me create an error file, whit al the problem I have. I will put them in a folder including the Common Folder and Config Folder. Give me a hour to do that. And I will let you know

**Comment by philipvu30** [comment]
Hi @Pascalnhuis ,

If I'm not wrong, all the issues above have already been fixed with the latest version 1.6.6. Please make sure you have downloaded our latest code. Thank you.

**Comment by Pascalnhuis** [comment]
Hi and thanks for your reply!

How can I update my app without losing my settings?

**Comment by philipvu30** [comment]
Hi,

You could try to create a git repository for your project, then every time you update your source code, the changed files will be highlighted. Or you can submit to this [form](https://docs.google.com/forms/d/e/1FAIpQLSeuBqUkScy42V7KKhfNPj0fl581anrB1mWkbMa3p2WQt7fhfw/viewform) to gain access to our GitLab repository.

**Comment by Pascalnhuis** [comment]
Hi and thanks for you reply!

I have already completed that form. But what you say is completly new for me. Do you have a tutorial or something?

**Comment by Pascalnhuis** [comment]
**You said:** _You could try to create a git repository for your project, then every time you update your source code, the changed files will be highlighted._

**Comment by philipvu30** [comment]
At the moment, we don't have any tutorial for this. You could try to search for a tutorial on Youtube.

**Comment by Pascalnhuis** [comment]
Hi, I have already find a option, but
please note that there’s an problem in the cart after the last update. 
**When does this problem starts?** 
_Put something in the cart, close de app and start it again. Now you will see the error in the cart._

See screenshot: This error shows also in your last demo please simulate it. 
![Screenshot_20200408_061054](https://user-images.githubusercontent.com/62649032/78743988-98775480-7960-11ea-8f9e-f2bfd16fba1a.jpg)

**Comment by philipvu30** [comment]
Hi,

We have already noticed this bug and currently on finding a solution.

**Comment by philipvu30** [comment]
Refer to [2615](https://github.com/inspireui/support/issues/2615)
