### ISSUE TITLE
[Fluxstore] - 

### ISSUE THREAD

**Issue by Saifahmad99** [inspireui/support#2543]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: How Can I add progress Bar in webview

2. Screenshots issues (required):

3. Proof of my purchased (required):
![Screenshot (80)](https://user-images.githubusercontent.com/59877416/78334663-ca2b9c80-75a9-11ea-978e-13bd5854035b.png)

3. Config files (required)

**Comment by minhcasi** [comment]
@Saifahmad99 - could you help to explain more about the idea, which screen would you like to add this feature?

We could help to upgrade feature for free as it seems a great idea

**Comment by Saifahmad99** [comment]
As we see there is an option to see webview in your codes but the problem is when webview loads the customer don't get any idea that its loading or not so they continuously click the link and it never open so there should be a progress bar for webview so that customer can understand that the page is loading.

**Comment by minhcasi** [comment]
@Saifahmad99 - thank you, we will investigate this UX

**Comment by trunghieuvn** [comment]
Hi @Saifahmad99 ,  Currently some places in the source code using webview have loading.
An example of this is the opening of the chat, the code that uses webview to open the chat page and attach loading.

![video_loadding](https://user-images.githubusercontent.com/19247680/78637391-76d08b80-78d4-11ea-92fd-2054bba43511.gif)

You can find the code in file `lib/screens/custom/smartchat.dart` , in  function `_openChat`.
![image](https://user-images.githubusercontent.com/19247680/78637511-b1d2bf00-78d4-11ea-9865-fc282f524195.png)

Is this what you need? Where do you want to try them? If this is not what you want to please describe more clearly about them, I will help you solve your problem. Thank you.
