### ISSUE TITLE
Fluxstore Pro android build failed

### ISSUE THREAD

**Issue by nobakhtvip** [inspireui/support#2544]
https://imgur.com/XovgfB9

output:
↳
03/04/2020
12:49 PM	Flutter packages get.
				The pubspec.yaml file has been modified since the last time 'flutter packages get' was run.
				Run 'flutter packages get'

12:49 PM	* daemon not running; starting now at tcp:5037

12:49 PM	* daemon started successfully

12:49 PM	Load Settings
				Cannot load settings from file 'C:\src\source\android\android.iml': File C:\src\source\android\android.iml does not exist
				Please correct the file content

12:49 PM	Load Settings
				Cannot load settings from file 'C:\src\source\android\app\app.iml': File C:\src\source\android\app\app.iml does not exist
				Please correct the file content

12:49 PM	Load Settings
				Cannot load settings from file 'C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\app_settings-3.0.1\android\app_settings.iml': File C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\app_settings-3.0.1\android\app_settings.iml does not exist
				Please correct the file content

12:49 PM	Load Settings
				Cannot load settings from file 'C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\apple_sign_in-0.1.0\android\apple_sign_in.iml': File C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\apple_sign_in-0.1.0\android\apple_sign_in.iml does not exist
				Please correct the file content

12:49 PM	Load Settings
				Cannot load settings from file 'C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\connectivity-0.4.8+1\android\connectivity.iml': File C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\connectivity-0.4.8+1\android\connectivity.iml does not exist
				Please correct the file content

12:49 PM	Load Settings
				Cannot load settings from file 'C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\connectivity_macos-0.1.0+2\android\connectivity_macos.iml': File C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\connectivity_macos-0.1.0+2\android\connectivity_macos.iml does not exist
				Please correct the file content

12:49 PM	Load Settings
				Cannot load settings from file 'C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\device_apps-1.0.9\android\device_apps.iml': File C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\device_apps-1.0.9\android\device_apps.iml does not exist
				Please correct the file content

12:49 PM	Load Settings
				Cannot load settings from file 'C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\facebook_audience_network-0.4.0\android\facebook_audience_network.iml': File C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\facebook_audience_network-0.4.0\android\facebook_audience_network.iml does not exist
				Please correct the file content

12:49 PM	Load Settings
				Cannot load settings from file 'C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\firebase_admob-0.9.2+1\android\firebase_admob.iml': File C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\firebase_admob-0.9.2+1\android\firebase_admob.iml does not exist
				Please correct the file content

12:49 PM	Load Settings
				Cannot load settings from file 'C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\firebase_analytics-5.0.11\android\firebase_analytics.iml': File C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\firebase_analytics-5.0.11\android\firebase_analytics.iml does not exist
				Please correct the file content

12:49 PM	Load Settings
				Cannot load settings from file 'C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.15.4\android\firebase_auth.iml': File C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.15.4\android\firebase_auth.iml does not exist
				Please correct the file content

12:49 PM	Load Settings
				Cannot load settings from file 'C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-0.1.2\android\firebase_auth_web.iml': File C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-0.1.2\android\firebase_auth_web.iml does not exist
				Please correct the file content

12:49 PM	Load Settings
				Cannot load settings from file 'C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.4.4\android\firebase_core.iml': File C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.4.4\android\firebase_core.iml does not exist
				Please correct the file content

12:49 PM	Load Settings
				Cannot load settings from file 'C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-0.1.1+2\android\firebase_core_web.iml': File C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-0.1.1+2\android\firebase_core_web.iml does not exist
				Please correct the file content

12:49 PM	Load Settings
				Cannot load settings from file 'C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\firebase_database-3.1.1\android\firebase_database.iml': File C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\firebase_database-3.1.1\android\firebase_database.iml does not exist
				Please correct the file content

12:49 PM	Load Settings
				Cannot load settings from file 'C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\firebase_messaging-6.0.9\android\firebase_messaging.iml': File C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\firebase_messaging-6.0.9\android\firebase_messaging.iml does not exist
				Please correct the file content

12:49 PM	Load Settings
				Cannot load settings from file 'C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\flutter_facebook_login-3.0.0\android\flutter_facebook_login.iml': File C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\flutter_facebook_login-3.0.0\android\flutter_facebook_login.iml does not exist
				Please correct the file content

12:49 PM	Load Settings
				Cannot load settings from file 'C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\flutter_keyboard_visibility-0.7.0\android\flutter_keyboard_visibility.iml': File C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\flutter_keyboard_visibility-0.7.0\android\flutter_keyboard_visibility.iml does not exist
				Please correct the file content

12:49 PM	Load Settings
				Cannot load settings from file 'C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.6\android\flutter_plugin_android_lifecycle.iml': File C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.6\android\flutter_plugin_android_lifecycle.iml does not exist
				Please correct the file content

12:49 PM	Load Settings
				Cannot load settings from file 'C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\flutter_statusbarcolor-0.2.3\android\flutter_statusbarcolor.iml': File C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\flutter_statusbarcolor-0.2.3\android\flutter_statusbarcolor.iml does not exist
				Please correct the file content

12:49 PM	Load Settings
				Cannot load settings from file 'C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\flutter_webview_plugin-0.3.10+1\android\flutter_webview_plugin.iml': File C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\flutter_webview_plugin-0.3.10+1\android\flutter_webview_plugin.iml does not exist
				Please correct the file content

12:49 PM	Load Settings
				Cannot load settings from file 'C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\fluttertoast-3.1.3\android\fluttertoast.iml': File C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\fluttertoast-3.1.3\android\fluttertoast.iml does not exist
				Please correct the file content

12:49 PM	Load Settings
				Cannot load settings from file 'C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\google_maps_flutter-0.5.24+1\android\google_maps_flutter.iml': File C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\google_maps_flutter-0.5.24+1\android\google_maps_flutter.iml does not exist
				Please correct the file content

12:49 PM	Load Settings
				Cannot load settings from file 'C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\google_sign_in-4.1.4\android\google_sign_in.iml': File C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\google_sign_in-4.1.4\android\google_sign_in.iml does not exist
				Please correct the file content

12:49 PM	Load Settings
				Cannot load settings from file 'C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\google_sign_in_web-0.8.3+2\android\google_sign_in_web.iml': File C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\google_sign_in_web-0.8.3+2\android\google_sign_in_web.iml does not exist
				Please correct the file content

12:49 PM	Load Settings
				Cannot load settings from file 'C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\image_picker-0.6.3+4\android\image_picker.iml': File C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\image_picker-0.6.3+4\android\image_picker.iml does not exist
				Please correct the file content

12:49 PM	Load Settings
				Cannot load settings from file 'C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\launch_review-2.0.0\android\launch_review.iml': File C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\launch_review-2.0.0\android\launch_review.iml does not exist
				Please correct the file content

12:49 PM	Load Settings
				Cannot load settings from file 'C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\libphonenumber-1.0.1\android\libphonenumber.iml': File C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\libphonenumber-1.0.1\android\libphonenumber.iml does not exist
				Please correct the file content

12:49 PM	Load Settings
				Cannot load settings from file 'C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\location-2.5.4\android\location.iml': File C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\location-2.5.4\android\location.iml does not exist
				Please correct the file content

12:49 PM	Load Settings
				Cannot load settings from file 'C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\notification_permissions-0.4.4\android\notification_permissions.iml': File C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\notification_permissions-0.4.4\android\notification_permissions.iml does not exist
				Please correct the file content

12:49 PM	Load Settings
				Cannot load settings from file 'C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\onesignal_flutter-2.3.3\android\onesignal_flutter.iml': File C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\onesignal_flutter-2.3.3\android\onesignal_flutter.iml does not exist
				Please correct the file content

12:49 PM	Load Settings
				Cannot load settings from file 'C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.5\android\path_provider.iml': File C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.5\android\path_provider.iml does not exist
				Please correct the file content

12:49 PM	Load Settings
				Cannot load settings from file 'C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4\android\path_provider_macos.iml': File C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4\android\path_provider_macos.iml does not exist
				Please correct the file content

12:49 PM	Load Settings
				Cannot load settings from file 'C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\rate_my_app-0.5.0+3\android\rate_my_app.iml': File C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\rate_my_app-0.5.0+3\android\rate_my_app.iml does not exist
				Please correct the file content

12:49 PM	Load Settings
				Cannot load settings from file 'C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\razorpay_flutter-1.1.2\android\razorpay_flutter.iml': File C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\razorpay_flutter-1.1.2\android\razorpay_flutter.iml does not exist
				Please correct the file content

12:49 PM	Load Settings
				Cannot load settings from file 'C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\share-0.6.3+6\android\share.iml': File C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\share-0.6.3+6\android\share.iml does not exist
				Please correct the file content

12:49 PM	Load Settings
				Cannot load settings from file 'C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.6+2\android\shared_preferences.iml': File C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.6+2\android\shared_preferences.iml does not exist
				Please correct the file content

12:49 PM	Load Settings
				Cannot load settings from file 'C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-0.0.1+6\android\shared_preferences_macos.iml': File C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-0.0.1+6\android\shared_preferences_macos.iml does not exist
				Please correct the file content

12:49 PM	Load Settings
				Cannot load settings from file 'C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-0.1.2+4\android\shared_preferences_web.iml': File C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-0.1.2+4\android\shared_preferences_web.iml does not exist
				Please correct the file content

12:49 PM	Load Settings
				Cannot load settings from file 'C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\sqflite-1.2.2+1\android\sqflite.iml': File C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\sqflite-1.2.2+1\android\sqflite.iml does not exist
				Please correct the file content

12:49 PM	Load Settings
				Cannot load settings from file 'C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\uni_links-0.2.0\android\uni_links.iml': File C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\uni_links-0.2.0\android\uni_links.iml does not exist
				Please correct the file content

12:49 PM	Load Settings
				Cannot load settings from file 'C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\url_launcher-5.4.2\android\url_launcher.iml': File C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\url_launcher-5.4.2\android\url_launcher.iml does not exist
				Please correct the file content

12:49 PM	Load Settings
				Cannot load settings from file 'C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-0.0.1+4\android\url_launcher_macos.iml': File C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-0.0.1+4\android\url_launcher_macos.iml does not exist
				Please correct the file content

12:49 PM	Load Settings
				Cannot load settings from file 'C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-0.1.1+1\android\url_launcher_web.iml': File C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-0.1.1+1\android\url_launcher_web.iml does not exist
				Please correct the file content

12:49 PM	Load Settings
				Cannot load settings from file 'C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\video_player-0.10.8+1\android\video_player.iml': File C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\video_player-0.10.8+1\android\video_player.iml does not exist
				Please correct the file content

12:49 PM	Load Settings
				Cannot load settings from file 'C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\video_player_web-0.1.2+1\android\video_player_web.iml': File C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\video_player_web-0.1.2+1\android\video_player_web.iml does not exist
				Please correct the file content

12:49 PM	Load Settings
				Cannot load settings from file 'C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\wakelock-0.1.3+4\android\wakelock.iml': content truncated
				File content will be recreated

12:49 PM	Load Settings
				Cannot load settings from file 'C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\webview_flutter-0.3.19+8\android\webview_flutter.iml': File C:\Users\HP\.pub-cache\hosted\pub.dartlang.org\webview_flutter-0.3.19+8\android\webview_flutter.iml does not exist
				Please correct the file content

**Comment by minhcasi** [comment]
Please update the latest 1.6.6 to fix build issue, we also note the detail on this changelog blog - https://medium.com/@inspireui/announcing-fluxstore-1-6-337efff1791f - thank you!

**Comment by minhcasi** [comment]
Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads it's used to verify your proof of purchase? 
Sorry for any inconvenience, we will reopen the ticket when it is verified, thank you!
