### ISSUE TITLE
[MStore] Firebase auth issue

### ISSUE THREAD

**Issue by undigitals** [inspireui/support#2545]
<img width="817" alt="Screen Shot 2020-04-03 at 12 07 05 AM" src="https://user-images.githubusercontent.com/22441312/78360324-95433800-75f1-11ea-9927-b010ec732134.png">

<img width="1151" alt="Screen Shot 2020-04-03 at 5 36 49 PM" src="https://user-images.githubusercontent.com/22441312/78342738-b2b5d900-75d4-11ea-9912-822b7e7677f5.png">

<img width="1280" alt="Screen Shot 2020-04-03 at 5 59 04 PM" src="https://user-images.githubusercontent.com/22441312/78342816-d711b580-75d4-11ea-9a89-9a733dabf4fc.png">

**Comment by minhcasi** [comment]
Hi, thank you for the feedback. Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads it's used to verify your proof of purchase? 
Sorry for any inconvenience, we will reopen the ticket when it is verified, thank you!

**Comment by undigitals** [comment]
can you check now?

**Comment by minhcasi** [comment]
@luyx2412 - please help to investigate the issues

**Comment by luyx2412** [comment]
Hi @undigitals Please follow the article to fix your issue.  https://github.com/invertase/react-native-firebase/issues/2149. 

Thanks
