### ISSUE TITLE
[my-product] - 

### ISSUE THREAD

**Issue by Elshaden** [inspireui/support#2547]
My Product is Fluxstore pro
---------

1. My issue:
After Update Flutter to new Version, I get this error, 
I am running on Windows OS, and only have Android Studio

2. Screenshots issues (required):
![image](https://user-images.githubusercontent.com/33955172/78360652-6c9e4c80-75b7-11ea-941d-4dbcedd893bc.png)

Compiler message:
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image-0.7.2/lib/src/gesture/extended_image_slide_page_route.dart:333:9: Error: No named parameter with the name 'animation'.
        animation: animation,
        ^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/cupertino/route.dart:435:3: Context: Found this candidate, but the arguments don't match.
  CupertinoFullscreenDialogTransition({
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

3. Proof of my purchased (required):
![image](https://user-images.githubusercontent.com/33955172/78360312-e550d900-75b6-11ea-9d5d-e59174a12dfa.png)

3. Config files (required)
I have not changed anything from downloaded files

**Comment by trunghieuvn** [comment]
please share me info version flutter 
```
 flutter --version
```
<img width="535" alt="Screen Shot 2020-04-04 at 12 47 00 AM" src="https://user-images.githubusercontent.com/19247680/78389909-cc274700-760d-11ea-8353-fef32ecf5d45.png">

**Comment by Elshaden** [comment]
```

Flutter 1.16.4-pre.69 • channel master • https://github.com/flutter/flutter.git
Framework • revision 19e7db585d (3 days ago) • 2020-04-01 11:16:01 -0700
Engine • revision c9506cb8e9
Tools • Dart 2.8.0 (build 2.8.0-dev.18.0 eea9717938)
```

**Comment by minhcasi** [comment]
@Elshaden - I'm sorry for the build issue, please help to download the latest 1.6.6b, there is new cool One-Page-Checkout via Webview feature have been added.

**Comment by minhcasi** [comment]
Let us know if you have any issue, feel free to reopen ticket - thank you!

**Comment by jeeali** [comment]
I have same issue. I have been searching for two days. Kindly, guide me properly, Thanks :)

<img width="1152" alt="Screenshot 2020-04-16 at 12 39 16 PM" src="https://user-images.githubusercontent.com/17235314/79428230-4c22b900-7fdf-11ea-817e-6fc44f742b5f.png">

**Comment by jeeali** [comment]
Here is the output of:
flutter --version

<img width="531" alt="Screenshot 2020-04-16 at 1 24 53 PM" src="https://user-images.githubusercontent.com/17235314/79432735-a9ba0400-7fe5-11ea-87fa-6c1590d31945.png">

**Comment by atishpaul** [comment]
Hello,
I'm also getting the same error on the latest version of your package.
kindly solve the issue.

**Comment by jeeali** [comment]
> Hello,
> I'm also getting the same error on the latest version of your package.
> kindly solve the issue.

`flutter channel stable`

Shift to stable channel. It'll work.

**Comment by jeeali** [comment]
@atishpaul 

https://github.com/inspireui/support/issues/2740#issuecomment-614582990

**Comment by atishpaul** [comment]
okay,i'll let you know if it works.
and thanks for helping!

**Comment by atishpaul** [comment]
Yes,it works! Thanks alot.

**Comment by jeeali** [comment]
@atishpaul your welcome man
