### ISSUE TITLE
[FluxStore 1.6.5 3] - notification 

### ISSUE THREAD

**Issue by abdullatif1989** [inspireui/support#2549]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: I have an issue with notification 

2. Screenshots issues (required):
<img width="1680" alt="Screen Shot 2020-04-03 at 6 02 27 PM" src="https://user-images.githubusercontent.com/63112219/78375363-6323dd00-75d5-11ea-844d-4d67192e6db9.png">

3. Proof of my purchased (required):
<img width="1680" alt="Screen Shot 2020-04-03 at 6 04 39 PM" src="https://user-images.githubusercontent.com/63112219/78375694-d88fad80-75d5-11ea-84f7-6b1fdbf02578.png">

3. Config files (required)
{
  "HorizonLayout": [
    {
      "image": "########/wp-content/uploads/2019/09/black-logo.png",
      "layout": "logo",
      "showMenu": false,
      "showSearch": false
    },
    {
      "autoPlay": false,
      "design": "default",
      "isSlider": false,
      "items": [
        {
          "image": "###############/uploads/2019/11/arabicweb-16-min.jpg",
          "padding": 0,
          "product": ""
        }
      ],
      "layout": "bannerImage"
    }
  ],
  "Setting": {
    "MainColor": "#000000",
    "ProductListLayout": "list"
  },
  "TabBar": [
    {
      "icon": "assets/icons/tabs/icon-home.png",
      "layout": "home",
      "pos": 100
    },
    {
      "icon": "assets/icons/tabs/icon-search.png",
      "layout": "search",
      "pos": 300
    },
    {
      "icon": "assets/icons/tabs/icon-heart.png",
      "layout": "wishlist",
      "pos": 390
    },
    {
      "icon": "assets/icons/tabs/icon-cart2.png",
      "layout": "cart",
      "pos": 400
    },
    {
      "icon": "assets/icons/tabs/icon-user.png",
      "layout": "profile",
      "pos": 500
    }
  ],
  "VerticalLayout": {
    "layout": "columns",
    "name": "منتجاتنا"
  }
}

In general I have an issue to implement firebase with the app. 

I need to know what is the function I should but it in index.js, and is there folder I should get it from you side could firebase? 

documentation not clear for me if you can help me with that.

https://docs.inspireui.com/fluxstore/firebase/

**Comment by minhcasi** [comment]
@abdullatif1989 - please help to download the latest 1.6.6b, there is a new cool One-Page-Checkout via Webview feature that has been added.

**Comment by gugan7** [comment]
Hi @trunghieuvn  and @minhcasi  ,

The documentation video on Push notification is not clear. https://docs.inspireui.com/fluxstore/firebase/#2-push-notifications-via-firebase

Between i'm do have valid proof of purchase in case #2494

The part where push notification function added is not clear. Once i install firebase cli , i tried firebase init functions , it then automatically authenticate to firebase and download dependency for it. The file .firebaserc was automatically generated with correct project-id. Then finally i did firebase deploy. Below is the output . I go back to Firebase console under Functions but couldn't find any functions there. Do we need to add something to index.js ? if yes , please let us know what is code to put there.

`MFBM-2W80WCHV2H:source guganesanselvaraj$ firebase deploy

=== Deploying to 'nextcommerce-367eb'...

i deploying functions
i functions: ensuring necessary APIs are enabled...
✔ functions: all necessary APIs are enabled
i functions: preparing functions directory for uploading...

✔ Deploy complete!

**Comment by trunghieuvn** [comment]
Hi @gugan7 , we will remake a video tutorial for Firebase push notification. We will send it to you soon when it is done. Please wait for us. Thank you.

**Comment by trunghieuvn** [comment]
@gugan7 please follow tutorial here: https://github.com/inspireui/support/wiki/%5BFeature%5D-Setup-firebase-cloud-messaging(FCM)-push-notification-in-IOS
i  will upload video and send for you later.

**Comment by minhcasi** [comment]
@abdullatif1989 - https://www.youtube.com/watch?v=rFCcWNRPrSk please help to check this detail video - thank you!
