### ISSUE TITLE
[ListApp] 29 EUR listing subtitile

### ISSUE THREAD

**Issue by bobozd** [inspireui/support#255]
Hi,

Under one of my listing there is a text - 29 EUR  and I'm pretty sure it's displayed by the ListApp and not my Wordpress backend. How can I remove it? I use my listing theme in WP.
![screen shot 2019-02-04 at 12 17 15](https://user-images.githubusercontent.com/28021993/52205284-d4072200-2876-11e9-99ca-570914f54441.png)

**Comment by bobozd** [comment]
still no any answer how to remove 29EUR text?

**Comment by minhcasi** [comment]
Hi, just update that we received your ticket and the team will back to check on Monday (after the Tet holiday), sorry for the delay - thank you!

**Comment by thangvo9x** [comment]
Hi. Thanks for your purchase. You can try by removing this block as attach.
<img width="580" alt="attach" src="https://user-images.githubusercontent.com/23457178/52544619-5d24d880-2de4-11e9-98ba-81217347c256.png">

**Comment by bobozd** [comment]
Hi, I found when I search for listings EUR 29 still exist there...please help me how to remove it from there. 
![screen shot 2019-02-14 at 09 48 52](https://user-images.githubusercontent.com/28021993/52774676-1500f280-303e-11e9-875d-e86c2f9efda9.png)
![screen shot 2019-02-14 at 09 49 09](https://user-images.githubusercontent.com/28021993/52774677-1500f280-303e-11e9-934f-6f7dba89fe0f.png)
