### ISSUE TITLE
[Fluxstore] - Cannot build mylisting demo

### ISSUE THREAD

**Issue by skong328** [inspireui/support#2550]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: Cannot build mylisting demo

2. Screenshots issues (required):

![12 48 30](https://user-images.githubusercontent.com/63035658/78385388-566fab00-760e-11ea-91b3-9c92e814679c.jpg)

3. Proof of my purchased (required):
![12 51 23](https://user-images.githubusercontent.com/63035658/78385467-78692d80-760e-11ea-9a56-39d4e3071137.jpg)

3. Config files (required)
mylisting demo file: example > mylisting > config.dart.txt

**Comment by minhcasi** [comment]
@skong328 - please help to change the import to 
```
import 'constants.dart';
```

**Comment by skong328** [comment]
Hi,

I want the search result page's listings can display the sale price, rent price, and other custom fields data. And also, the single listing page doesn't show the custom field data. Please help.

Thanks and Best regards.

**Comment by minhcasi** [comment]
It seems these features are not available, could you help to share the config files and screenshot to explain more about the idea so that can report to the technical team to see if they could upgrade the features - thank you!

**Comment by minhcasi** [comment]
moved to backlogs for investigating - https://trello.com/c/EIXyPp1f/27-search-result-pages-listings
