### ISSUE TITLE
[MStore] can't be changed splashScreen & App icon/name

### ISSUE THREAD

**Issue by undigitals** [inspireui/support#2551]
1.  purchase proof
<img width="817" alt="Screen Shot 2020-04-03 at 12 07 05 AM" src="https://user-images.githubusercontent.com/22441312/78389062-0b10c900-761d-11ea-8539-8ffa045c85cc.png">

2. I have changed `SplashScreen` `< Image source={Image.splash} />` 
![Screen Shot 2020-04-04 at 2 27 14 AM (2)](https://user-images.githubusercontent.com/22441312/78389864-773ffc80-761e-11ea-848a-6153a63b8b69.png)

![Screen Shot 2020-04-04 at 2 48 58 AM (2)](https://user-images.githubusercontent.com/22441312/78390106-f0d7ea80-761e-11ea-95bf-dd6d6b99d2aa.png)

3. and changed logo of the App
![Screen Shot 2020-04-04 at 2 27 55 AM (2)](https://user-images.githubusercontent.com/22441312/78389803-5d9eb500-761e-11ea-9ded-45669975d11d.png)

As you can see I have changed all but when app starts it still showing the demo splash am I missing?
inside `src/images` all the splash right? and inside root DIR `assets` there are app logo and app icon right?

**Comment by luyx2412** [comment]
Hi @undigitals Currently we did not use SplashScreen component and screen. So if you want to change the splash screen. You can use https://github.com/bamlab/react-native-make to change splash screen, the library will generate splash screen also app icon for react native app. This is the location about splash screen on iOS.
![image](https://user-images.githubusercontent.com/8909619/78420226-696a9580-7677-11ea-867b-d0b788dbd18f.png)

Thanks

**Comment by undigitals** [comment]
when I do confirm using `bacs` payment method it is redirecting to Mstore checkout 

![Screenshot_1586257405](https://user-images.githubusercontent.com/22441312/78668716-1a8e5b80-7916-11ea-8e10-be3ab7f489c5.png)


![Screenshot_1586257429](https://user-images.githubusercontent.com/22441312/78668821-47427300-7916-11ea-854f-62584ee772f0.png)

how can I redirect to this checkout 
![Screenshot_1586257444](https://user-images.githubusercontent.com/22441312/78669120-bae48000-7916-11ea-8c91-6db86466ada1.png)
