### ISSUE TITLE
[Fluxstore] - Product quantity in cart doesnt update when changing quantity

### ISSUE THREAD

**Issue by ykarapanca** [inspireui/support#2552]
---------

1. My issue: 
Product quantity in cart doesn't update when changing quantity and gives error.
2. Screenshots issues (required):
![image](https://user-images.githubusercontent.com/58140554/78394698-c3764700-75f4-11ea-857a-9f7ae2d43749.png)

3. Proof of my purchased (required):
![image](https://user-images.githubusercontent.com/58140554/78394909-29fb6500-75f5-11ea-8a8d-4dc1ea04e764.png)

3. Config files (required)
[config + common files.zip](https://github.com/inspireui/support/files/4429367/config.%2B.common.files.zip)

**Comment by ykarapanca** [comment]
![image](https://user-images.githubusercontent.com/58140554/78395362-fcfb8200-75f5-11ea-987d-72e7afd0c611.png)

**Comment by ykarapanca** [comment]
I also have another issue.
After clicking select address, address field fills in but name and email fields are not autofill at the same time. After i click to shipping from top progress bar and go back, it fills in but the user may not do this way. In my case after selecting address, they click continue shipping and warnings appear about unfilled required fields. 
![image](https://user-images.githubusercontent.com/58140554/78451393-09331e00-768e-11ea-898a-8c03458278e6.png)

**Comment by ykarapanca** [comment]
Could you please inform me when can you guys show me how to fix these 2 issues. Thank you

**Comment by ykarapanca** [comment]
Hi, 
1- The cart update issue have resolved after updating to 1.6.6
2- The auto fill issue have resloved after updating to 1.6.6 - (But still it doesnt fill the phone number.)

3- I have another issue. Some of the users has the same issue but i couldn't work it out. Issue is: On the main page the products in collection categories shows undiscounted price instead of showing with sale price and badge. But it's ok in the product page.

Problematic view:
![image](https://user-images.githubusercontent.com/58140554/78461174-7e731300-76cf-11ea-83c1-d272150458a8.png)
Product page:
![image](https://user-images.githubusercontent.com/58140554/78461186-99de1e00-76cf-11ea-9348-58eba3b28c76.png)


4- The other issue is: I have fixed the DefaultCountry to Turkey by inserting the code below
-----------
const List DefaultCountry = [
  { "name": "Türkçe","iosCode": "TR", "icon": "https://cdn.britannica.com/s:1500x700,q:85/82/4782-004-0AB0A759/Flag-Turkey.jpg"},
];
-----------

However, when checking out, the state province dropdown list shows another countries states. I want it to show Turkey's cities. In fact, if possible, i want to show a single city from Turkey. 

![image](https://user-images.githubusercontent.com/58140554/78461272-34d6f800-76d0-11ea-8874-d7ee7a25e170.png)
![image](https://user-images.githubusercontent.com/58140554/78461276-3c969c80-76d0-11ea-9849-7ff991cb7951.png)

5- Before update i wasn't facing this kind of issue but it's a new thing: I login once as a user account and place an order. But after second run, app requires another login. This is very important. please tell me how to fix this.

![image](https://user-images.githubusercontent.com/58140554/78461244-f3dee380-76cf-11ea-9426-ce1d92065703.png)

Here is my common folder.
[common.zip](https://github.com/inspireui/support/files/4432522/common.zip)

After all this, i will be ok for good. @minhcasi @trunghieuvn 

Thank you for your attention. Please let me know when can you assist me with these issues. Have a nice day.

**Comment by minhcasi** [comment]
please help to download the latest 1.6.6b, there is the build issues 1.6.6 that could break some function - thank you!

Also, upload the detail file change from Gitlab, if you have not accessed to the repo, please submit this link https://docs.google.com/forms/d/e/1FAIpQLSeuBqUkScy42V7KKhfNPj0fl581anrB1mWkbMa3p2WQt7fhfw/viewform

**Comment by ykarapanca** [comment]
Hi there, i ve just downloaded new version and let you know with the results. 
I have submitted to the link but it said:
"Submit to Access Gitlab
Thanks for submitting, please give us 2-4 days to handle for this request."

Also im not sure what you mean by detail file change. 
Thank you.

**Comment by ykarapanca** [comment]
Hi, i have upgradet to1.6.6b and i have the issues below:
1- In cart page, not always but sometimes it gives this error:
![image](https://user-images.githubusercontent.com/58140554/78504483-407cfa00-7776-11ea-8e07-761cdfc38ea4.png)

2- The collection page's product price still show undiscounted price without sale badge.
3- Country and city issue fixed.
4- Login issue fixed. 
5- Phone number field still returns empty. 

Please let me know when can you assist me with this so that i can organize my self. @minhcasi 
Thank you!

**Comment by minhcasi** [comment]
@trunghieuvn - pls investigate this issue - thanks

**Comment by trunghieuvn** [comment]
> Hi, i have upgradet to1.6.6b and i have the issues below:
> 1- In cart page, not always but sometimes it gives this error:
> ![image](https://user-images.githubusercontent.com/58140554/78504483-407cfa00-7776-11ea-8e07-761cdfc38ea4.png)

To fix this problem, please correct the code in the `addProductToCart` function at the file `lib/models/cart.dart`:

```
    if (message.isEmpty) {
      item[product.id] = product;
      if (isSaveLocal) {
        _productVariationInCart[key] = variation;
        _productSkuInCart[key] = product.sku;
        saveCartToLocal(
            product: product, quantity: quantity, variation: variation);
      }
    }
```

![image](https://user-images.githubusercontent.com/19247680/78521363-cc813700-77f3-11ea-8c33-e09795a46011.png)

The remaining issues I am checking. I will respond as soon as I finish solving them.
Please wait for me. Thanks.

**Comment by trunghieuvn** [comment]
> 5- Phone number field still returns empty.

The application will only display phone information in billing when an order has been placed.
In case no orders have arisen on the application, the application will retrieve user information when logging in to fill data (only including firstname, lastname and email).

If there was an invoice before that, the information will be saved locally. At this point, the application will take local data to fill in. But there is an error in the code, in order to run this feature correctly, please fix the code in file `lib/models/cart.dart` as follows:

```
 Future getAddress() async {
    if (address == null) {
      address = await getShippingAddress();
    }
    return address;
  }

```

![image](https://user-images.githubusercontent.com/19247680/78530752-71107280-780e-11ea-87ee-4205c22bdc65.png)

**Comment by trunghieuvn** [comment]
> 2- The collection page's product price still show undiscounted price without sale badge.

Sorry I still do not understand the problem, please provide images of this error for me. Thanks very much.

**Comment by ykarapanca** [comment]
Hi @trunghieuvn ,
Thanks for the corrections. All of them working great now.

The last issue is: 
At the main page the product shows regular price instead of discounted price.

Main page screenshot:
![image](https://user-images.githubusercontent.com/58140554/78541529-6f3eb300-77fe-11ea-9039-c0db422c2f82.png)

It needs to be shown as the product page. Which shows the real discounted price with a sale badge.

Product page screenshot:
![image](https://user-images.githubusercontent.com/58140554/78541676-add46d80-77fe-11ea-8622-036ce457ba33.png)

You can see the prices are different and there is no badge at the 1st screenshot.

Thank you!

**Comment by trunghieuvn** [comment]
You seem to have submitted a missing config folder. Please send me your config folder. 
Compress them and post here, I will help you solve this problem quickly. Thanks.

**Comment by ykarapanca** [comment]
Hi there, 
Here is my config folder. 
[config.zip](https://github.com/inspireui/support/files/4438534/config.zip)

Also i need a add to cart button at the corner of the products in the main page if possible. Can we do that?
Thank you!

**Comment by ykarapanca** [comment]
Hi @trunghieuvn i ve wanted to remind my self🖐

**Comment by trunghieuvn** [comment]
@ykarapanca , Sorry but I have not reproduce this error yet. You can add me to your gitlab or github source or send me the source code (compress them and send emails)  so I can reproduce the error faster. I will help you solve this problem quickly.

**Comment by ykarapanca** [comment]
@trunghieuvn I have sent an email with the source file. Thank you!

**Comment by trunghieuvn** [comment]
I have received. I will check and respond soon.

**Comment by trunghieuvn** [comment]
> Hi @trunghieuvn ,
> Thanks for the corrections. All of them working great now.
> 
> The last issue is:
> At the main page the product shows regular price instead of discounted price.
> 
> Main page screenshot:
> ![image](https://user-images.githubusercontent.com/58140554/78541529-6f3eb300-77fe-11ea-9039-c0db422c2f82.png)
> 
> It needs to be shown as the product page. Which shows the real discounted price with a sale badge.
> 
> Product page screenshot:
> ![image](https://user-images.githubusercontent.com/58140554/78541676-add46d80-77fe-11ea-8622-036ce457ba33.png)
> 
> You can see the prices are different and there is no badge at the 1st screenshot.
> 
> Thank you!

To fix this problem, you can use `ProductCard` instead of` ProductSelectCard` in file `lib/widgets/home/vertical/menu_layout.dart` and find by keyword `ProductSelectCard`. 

![image](https://user-images.githubusercontent.com/19247680/78668626-2faebe80-7905-11ea-807b-acfd9ca75f94.png)

> Also i need a add to cart button at the corner of the products in the main page if possible. Can we do that?
> Thank you!

Assigning `showCard` to `true` will solve this problem.

**Comment by ykarapanca** [comment]
Hi there @trunghieuvn 
Thanks for the fix. It's working great now.

One last issue is do i have to use macos in order to submit the app to apple store? Is tere a way around? 
Thank you

**Comment by minhcasi** [comment]
@ykarapanca - yes you need macOS to submit the ios to AppStore via XCode - it's the only way to release ios :)

Let us know if you have any questions, please also help us to give some good rating to http://codecayon.net/downloads - we are still continuing to upgrade the app more powerful feature - thank you!
