### ISSUE TITLE
Issues on Version 1.6.6

### ISSUE THREAD

**Issue by alexrali** [inspireui/support#2553]
Hi,
I already download, decompress and build the latest version (1.6.6), and whit  changing anything, 

- Category´s images does not show
- Language switch not working
- Dark theme switch not working

Please, i´ve missing anything...

Please,

**Comment by alicankarakus** [comment]
Yeah. the same problem for me. im checking this issue

**Comment by alexrali** [comment]
Proof of my purchased (required):

<img width="1080" alt="Captura de Pantalla 2020-04-03 a la(s) 15 02 59" src="https://user-images.githubusercontent.com/4369002/78404765-4cbd5780-75bc-11ea-8ec2-23e2d91ae010.png">

**Comment by minhcasi** [comment]
@alexrali - could you help to share the screenshot of the issues, it could be the development environment issues?

**Comment by vanlalruata** [comment]
Same for me. 

Also, the smart chat button are not working. The Rate App buttons are not working as well.

![image](https://user-images.githubusercontent.com/20646204/78424462-55309380-768b-11ea-8f56-b261709f705f.png)

![image](https://user-images.githubusercontent.com/20646204/78424482-8610c880-768b-11ea-8e80-7ff1b8925f34.png)

**Comment by farhaanabdulla** [comment]
Same issue am facing the new update has many issue, still waiting for support to reply

**Comment by alexrali** [comment]
Of course

> @alexrali - could you help to share the screenshot of the issues, it could be the development environment issues?

Im testing, but I don´t think so, 

flutter doctor

![Captura de Pantalla 2020-04-04 a la(s) 11 31 57](https://user-images.githubusercontent.com/4369002/78457764-da0ab580-7669-11ea-8a82-0cf9f51ce9e8.png)

Issue 1 - Category´s images does not show

![Captura de Pantalla 2020-04-04 a la(s) 11 36 56](https://user-images.githubusercontent.com/4369002/78457786-fb6ba180-7669-11ea-8279-e0d786a162c2.png)

Issue 2 -  Language switch not working

![Captura de Pantalla 2020-04-04 a la(s) 11 40 36](https://user-images.githubusercontent.com/4369002/78457807-248c3200-766a-11ea-9278-a232b4b458d7.png)
![Captura de Pantalla 2020-04-04 a la(s) 11 40 30](https://user-images.githubusercontent.com/4369002/78457808-2655f580-766a-11ea-9586-abd282d9123b.png)


Issue 3 - Dark theme & currency switch not working

![Captura de Pantalla 2020-04-04 a la(s) 11 40 14](https://user-images.githubusercontent.com/4369002/78457820-484f7800-766a-11ea-9a5a-ca3f806b6656.png)
![Captura de Pantalla 2020-04-04 a la(s) 11 39 47](https://user-images.githubusercontent.com/4369002/78457822-4b4a6880-766a-11ea-8547-29f97a29970a.png)

n the screenshot is the detail of some exceptions...

If i can do something else to help, please let me know
Greetings

**Comment by taryaalo** [comment]
same on me there is many issue and a lot of error in code
![Screen Shot 2020-04-05 at 10 42 15 AM](https://user-images.githubusercontent.com/26363734/78470476-303f2d80-772a-11ea-83f3-d858ccafd0f2.png)
and Magento not working at all 
![Screen Shot 2020-04-05 at 10 44 03 AM](https://user-images.githubusercontent.com/26363734/78470502-64b2e980-772a-11ea-8ec7-45b7cdab2f0d.png)

**Comment by farhaanabdulla** [comment]
Everyone is facing this same issue, yet no response from support.
I've even sent several email include all issues found and screen shot but no reply from them.

**Comment by wishie** [comment]
The issue seems to be with it trying to load plugins from plugins.flutter.io, which no longer exists.

**Comment by minhcasi** [comment]
#2548 - we double-check the package and will get back to you shortly - thank you!

**Comment by minhcasi** [comment]
#2570

**Comment by minhcasi** [comment]
@alexrali @wishie  @farhaanabdulla @taryaalo - I'm sorry for the build issue, please help to download the latest 1.6.6b, there is new cool One-Page-Checkout via Webview feature have been added.

Also, upload the detail file change from Gitlab, if you have not accessed to the repo, please submit this link https://docs.google.com/forms/d/e/1FAIpQLSeuBqUkScy42V7KKhfNPj0fl581anrB1mWkbMa3p2WQt7fhfw/viewform

**Comment by alexrali** [comment]
@minhcasi 

Sure, we will subscribe to the repo.

After test the currently update i found not error in the issues i described previously... by the moment, its working as expected. 

Thankful for your attention, i will let you know if it anything else going bad

**Comment by minhcasi** [comment]
@alexrali - thank you 😊

**Comment by vanlalruata** [comment]
I am upgrading the flutter to the latest version as of now that is 1.18.0

![image](https://user-images.githubusercontent.com/20646204/78633495-6c57c700-78bf-11ea-9e20-ca244f70f3b7.png)


But I am getting the following error I try to debug / run the app.

```
Compiler message:
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image-0.7.2/lib/src/gesture/extended_image_slide_page_route.dart:333:9: Error: No named parameter with the name 'animation'.
        animation: animation,
        ^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/cupertino/route.dart:435:3: Context: Found this candidate, but the arguments don't match.
  CupertinoFullscreenDialogTransition({
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Compiler message:
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image-0.7.2/lib/src/gesture/extended_image_slide_page_route.dart:333:9: Error: No named parameter with the name 'animation'.
        animation: animation,
        ^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/cupertino/route.dart:435:3: Context: Found this candidate, but the arguments don't match.
  CupertinoFullscreenDialogTransition({
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.
```
`* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

`

Rest of the things are perfect now. I downgrade the flutter to version 1.6.3 and It works like charm.

The developer team are great, support is more than great. You all rock, we are all happy too. Thanks and keep up the spirit.

**Comment by jeeali** [comment]
I have same issue, I don't want to downgrade my flutter version. I am working on other Projects also. Why should I have to downgrade to resolve the issue! I don't get it.

I bought the FluxStore. But, It hasn't run even once on my laptop. (I attached a screenshot)

Kindly, Suggest to me, What should I do. @minhcasi 

<img width="1216" alt="Screenshot 2020-04-16 at 1 38 02 PM" src="https://user-images.githubusercontent.com/17235314/79434237-81330980-7fe7-11ea-949c-e57f856bff8b.png">

**Comment by jeeali** [comment]
> I am upgrading the flutter to the latest version as of now that is 1.18.0
> 
> ![image](https://user-images.githubusercontent.com/20646204/78633495-6c57c700-78bf-11ea-9e20-ca244f70f3b7.png)
> 
> But I am getting the following error I try to debug / run the app.
> 
> ```
> Compiler message:
> /C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image-0.7.2/lib/src/gesture/extended_image_slide_page_route.dart:333:9: Error: No named parameter with the name 'animation'.
>         animation: animation,
>         ^^^^^^^^^
> /C:/src/flutter/packages/flutter/lib/src/cupertino/route.dart:435:3: Context: Found this candidate, but the arguments don't match.
>   CupertinoFullscreenDialogTransition({
>   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> Compiler message:
> /C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image-0.7.2/lib/src/gesture/extended_image_slide_page_route.dart:333:9: Error: No named parameter with the name 'animation'.
>         animation: animation,
>         ^^^^^^^^^
> /C:/src/flutter/packages/flutter/lib/src/cupertino/route.dart:435:3: Context: Found this candidate, but the arguments don't match.
>   CupertinoFullscreenDialogTransition({
>   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
> build failed.
> ```
> 
> `* What went wrong:
> Execution failed for task ':app:compileFlutterBuildDebug'.
> 
> > Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1
> 
> `
> 
> Rest of the things are perfect now. I downgrade the flutter to version 1.6.3 and It works like charm.
> 
> And another solution with my problem is, I change it back to Flutter Stable Channel, and upgrade it to latest, and now it works fine. Cheer!
> 
> The developer team are great, support is more than great. You all rock, we are all happy too. Thanks and keep up the spirit.

You downgraded the flutter to version 1.6.3 or downgrade the flutter to version 1.16.3 ???
