### ISSUE TITLE
[FluxStore Pro] - Phone/SMS Login & Push Notification

### ISSUE THREAD

**Issue by IbrahimHd** [inspireui/support#2555]
1. My issue:
   I'm using v1.6.5c
  A.  I'm able to login using "whitelisted phone numbers" supported by firebase but not "real numbers".
  B.  Push notification works on Emulator/Simulator but not on real device.

2. Screenshots issues (required):
   A. 
   I/BiChannelGoogleApi( 9378): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@a980567
  I/flutter ( 9378): **verified**
E/        ( 9378): [ZeroHung]zrhung_get_config: **Get config failed** for wp[0x0008]

   B. No error noticed.

3. Proof of my purchased (required):
   
![image](https://user-images.githubusercontent.com/16100897/78409005-473e2c80-7611-11ea-93fc-096b9f62d473.png)

3. Config files (required)
  -  android/app/**google-services.json** file has been updated as per the firebase project/app.
  -  android/app/**build.gradle**:  applicationId has been updated
  -  **package** property has been updated in all (3) AndroidManifest.xml

**Comment by IbrahimHd** [comment]
**Update**
Issue B:  SOLVED
     Push notification needs the app to be in the *background* (minimized) in order to work.

Issue: A
     Awaiting for your kind support.

**Comment by minhcasi** [comment]
@trunghieuvn - pls check this push notification issue

**Comment by gugan7** [comment]
Hi @trunghieuvn and @minhcasi ,

The documentation video on Push notification is not clear. https://docs.inspireui.com/fluxstore/firebase/#2-push-notifications-via-firebase

Between i'm do have valid proof of purchase in case https://github.com/inspireui/support/issues/2494

The part where push notification function added is not clear. Once i install firebase cli , i tried firebase init functions , it then automatically authenticate to firebase and download dependency for it.  The file .firebaserc was automatically generated with correct project-id. Then finally i did firebase deploy.  Below is the output . I go back to Firebase console under Functions but couldn't find any functions there. Do we need to add something to index.js ? if yes , please let us know what is code to put there.



`MFBM-2W80WCHV2H:source guganesanselvaraj$ firebase deploy

=== Deploying to 'nextcommerce-367eb'...

i  deploying functions
i  functions: ensuring necessary APIs are enabled...
✔  functions: all necessary APIs are enabled
i  functions: preparing functions directory for uploading...

✔  Deploy complete!

Project Console: https://console.firebase.google.com/project/nextcommerce-367eb/overview`

**Comment by trunghieuvn** [comment]
Hi @IbrahimHd , 
We will remake a video tutorial for Firebase push notifications and send it to you as soon as it is done. Please wait for us. Thank you.

**Comment by IbrahimHd** [comment]
Hi @trunghieuvn,
As I mentioned, it's fine with Push Notification.  I need your support for Phone/SMS login.

**Comment by trunghieuvn** [comment]
Oke, checking it

**Comment by minhcasi** [comment]
@IbrahimHd - pls help to check with the latest release 1.6.6b and let us know the remain issues from your website integration within this ticket - thank you!

We will update new video guide for the Firebase installing soon

**Comment by IbrahimHd** [comment]
Hi @minhcasi, 
I don't think the approach of "per-customer" issues helps you build a good "koweldege base" for other customers facing the same issue.
For example, this issue is talking about Phone Login & Pucsh Notification, is it a good practice to ask here for variation products, search, filter, carousel, product tags, ...?
I do recommend "Topic" based thread which is more useful.
Thanks

**Comment by advaitn** [comment]
> @IbrahimHd - pls help to check with the latest release 1.6.6b and let us know the remain issues from your website integration within this ticket - thank you!
> 
> We will update new video guide for the Firebase installing soon

I am also facing major issues with Firebase now, it was working fine earlier. Now it is really not doing anything, the active users throw 0. 

How long for the video to come up? Can you give a tentative date?

**Comment by trunghieuvn** [comment]
@advaitn about feature push notification use firebase. 
please follow tutorial here: https://github.com/inspireui/support/wiki/%5BFeature%5D-Setup-firebase-cloud-messaging(FCM)-push-notification-in-IOS
 i will update video and send for you later
thanks

**Comment by IbrahimHd** [comment]
Hi @trunghieuvn,
More than 2 weeks and still no progress on the issues I raised, unfortunately.
As requested by @minhcasi, I'm going to put all the cases here in this issue.
**A.**  Phone/SMS Login, same error with v1.6.6b:
I/flutter ( 9378): verified
E/ ( 9378): [ZeroHung]zrhung_get_config: Get config failed for wp[0x0008]
**B.** Search tool sends tag query like this: &tag=[tagName] but it has to be &tag=[tagId] instead.
**C.** In product "listing" screen, not single product page, variable product shows only the "lowest" price instead of "low-highest" price.

Thank you for your prompt response.
Ibrahim

**Comment by minhcasi** [comment]
@IbrahimHd - https://www.youtube.com/watch?v=rFCcWNRPrSk please help to check this detail video - thank you!

**Comment by IbrahimHd** [comment]
@minhcasi it seems that you did't read the issue I raised above, along with the other issues (A, B, C, D).
As I said, Push notification works well, I'm asking support on SMS Login.
Please refer to my most recent msg above.
I'm still waiting for more than TWO WEEKS!

**Comment by trunghieuvn** [comment]
Hi @IbrahimHd , 
Sorry to keep you waiting. 
Your problems are as follows:

With issue B, you can easily fix it by editing the following code in the abc.dart file.
File: lib/models/search.dart
Function: searchByFilter
Code edit: ` tag = value.isNotEmpty ? '${value.first.id}' : '';`

![image](https://user-images.githubusercontent.com/19247680/79567375-5081cb80-80de-11ea-8aea-354e91decf0e.png)

With problem C, I have checked in the api docs of woo. Woo support gets the default sorted product list by date, along with that, it supports sort by id, include, title and slug. (Default is date).
You can see this link: https://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-products

With issue D, this I will review and solve them, I will send you within the next few days.

If there are any problems, please comment here.
Very sorry for waiting for you so long. I will especially follow up with your ticket.

**Comment by IbrahimHd** [comment]
Dear @minhcasi, I appreciate your attention. 

**A.** SMS Login: I'm still encountering the same issue mentioned above.
(It's worth to mention that I'm able to login using "whitelisted phone numbers" supported by firebase but not "real numbers")
**B.** Solved. Thank you!
**C.** I don't mean "sorting" products. What I mean is the price of a variable product. As you know, in WordPress, price of variable products are displayed in a range, like this: $10-$20. However, FluxStore displays only the lowest price [$10] in product listing but it works well in single product screen. Shouldn't the price be displayed as a range [$10-$20] everywhere?
**D.** Locking the buttons until variations are loaded is really IMPORTANT. Thank you for following up on this.
**E** (new). In search tool, the request is sent with Null for [lang] parameter: **&lang=NULL**. Consequently, non-native lauguages don't work.
**F** (new). In search tool, translation of categories works well but not for "tags" and "attributes".
**G** (new). Product Variations: type and translations need to be defined (hard-coded) "manually" which means the app will no longer accept/understand any new product with new variations. In light of this, can't variations (type, names, & values) be captured automatically from the backend?

Hope I'm helping make FluxStore SHINES more & more!
Thank you in advance.

**Comment by trunghieuvn** [comment]
> C. I don't mean "sorting" products. What I mean is the price of a variable product. As you know, in WordPress, price of variable products are displayed in a range, like this: $10-$20. However, FluxStore displays only the lowest price [$10] in product listing but it works well in single product screen. Shouldn't the price be displayed as a range [$10-$20] everywhere?
> 

Would you please check if your api returns the highest or lowest price? I guess it may be returning the lowest price.

**Comment by trunghieuvn** [comment]
> (new). In search tool, the request is sent with Null for [lang] parameter: &lang=NULL. Consequently, non-native lauguages don't work.


To fix this problem, please add null and empty checks as follows:

File: `lib/services/woo_commerce.dart`
Function: `searchProducts`
Code:

```
String endPoint =
          "products?status=publish&search=$name&page=$page&per_page=$ApiPageSize";

      if (lang?.isNotEmpty ?? false) {
        endPoint += '&lang=$lang';
      }
```
![image](https://user-images.githubusercontent.com/19247680/79724721-303a5280-8312-11ea-9c92-82a0bae871d6.png)

**Comment by IbrahimHd** [comment]
Hi @trunghieuvn,
I really wonder why you gave answers to only 2 cases!  I hope you can be more responsive.
**A.** SMS Login: I used below command to get the SHA-1 key.
`keytool -list -v -keystore D:\dev\ Android\.android\debug.keystore -alias androiddebugkey -storepass android -keypass android `
Is this the right way?
**C.** As the price range works fine in the single product screen, it has to be in the product listing. Is it normal for FluxStore to display only the lowest price or it's configured to display a range [lowest-highest]?
**E.** The code you shared "checks" if "lang" has a value or not. However, the problem is why it's send NULL? It has to be fixed somewhere else where `searchProducts` is called and the parameter is filled. right?
**F.** Unfortunately, ignored by your side!
**G.** Unfortunately, ignored by your side!

Looking for your response.
Thanks

**Comment by trunghieuvn** [comment]
> **A.** SMS Login: I used below command to get the SHA-1 key.
> `keytool -list -v -keystore D:\dev\Android\.android\debug.keystore -alias androiddebugkey -storepass android -keypass android `
> Is this the right way?

You should use the command that [flutter docs](https://flutter.dev/docs/deployment/android) suggests.
 
```
keytool -genkey -v -keystore c:/Users/USER_NAME/key.jks -storetype JKS -keyalg RSA -keysize 2048 -validity 10000 -alias key

```
-------

> **C.** As the price range works fine in the single product screen, it has to be in the product listing. Is it normal for FluxStore to display only the lowest price or it's configured to display a range [lowest-highest]?

Almost all fluxstore display products are not arranged by price. They are usually sorted by another attribute.

-------

> **E.** The code you shared "checks" if "lang" has a value or not. However, the problem is why it's send NULL? It has to be fixed somewhere else where `searchProducts` is called and the parameter is filled. right?

Maybe someone else used it and forgot to add it to the language, or in some cases this language variable didn't load.

So we will have to do 2 steps:
   - First, check all places using this function and make sure they are all passed to the lang parameter
   - The second we check null and empty at the API call to ensure that even if we have missing checks in the previous step, the function will still be able to call.

Don't forget to check the `DefaultLanguage` variable to make sure it is never null.

-------

> **G** (new). Product Variations: type and translations need to be defined (hard-coded) "manually" which means the app will no longer accept/understand any new product with new variations. In light of this, can't variations (type, names, & values) be captured automatically from the backend?

It is true. If you want to do that, you have to revise the way they work.

-------

> **F** (new). In search tool, translation of categories works well but not for "tags" and "attributes".

In the old version of FluxStore, I had an error when searching and filtering with tags. But I have not seen it failed with attribute. You can update to the latest version of FluxStore and check them again. If there are still errors, please take a video to help me with the steps to create the error, I will handle them quickly. Thanks very much.

**Comment by IbrahimHd** [comment]
Hi @trunghieuvn 

A. For the reference to other people, this commad is to create a "key": 
`keytool -genkey -v -keystore c:/Users/USER_NAME/key.jks -storetype JKS -keyalg RSA -keysize 2048 -validity 10000 -alias key`  while you still need another commad to GET the SHA-1 fingerprint through this cmd:
`keytool -list -v -keystore D:\dev\Android\.android\debug.keystore -alias androiddebugkey -storepass myPass -keypass myPass`

C.  For 3 weeks, even in a different issue #, you still talking about Sorting!!, it's about how the price of a variable product is displayed, [one value] or [Range] price?, that's it!

E. The problem is that `Provider.of<AppModel>(context, listen: false).locale;` returns `NULL` which means ` Provider.of<AppModel>(context, listen: false)
                  .changeLanguage(languages[i]["code"], context);` does not set the language as expected.

F. Attributes are not translated neither in Search (filter) nor in products Filter.

I'm going to close this issue which is maily addressing "Phone/SMS Login & Push Notification" and trying to report other issues separetly because they becasme un-manageable and hard to keep track of.
