### ISSUE TITLE
[ListPro] WP REST API Controller  not Working Properly!!!

### ISSUE THREAD

**Issue by jaksatomovic** [inspireui/support#256]
**Required Info (please complete the following information):**
 - Product: [ListPro]
 - Your Purchased Code: [e52cfbdd-f79e-4946-ae15-0daadc94fdfa]
(we may not reply if you are not our customer)

**Describe the bug**
 After looking into REST API controller i double checked are all api endpoints enabled.
Dispate enabling api endpoint they are empty on request. For example gallery_show images, when clearly they exist cause they can be seen in list details on website...many more fields are not displayed correctly in app (phone, address etc..) cause api endpoints are empty on request 

**Screenshots**
x
**Additional context**
x

**Comment by minhcasi** [comment]
Hi, just update that we received your ticket and the team will back to check on Monday (after the Tet holiday), sorry for the delay - thank you!

**Comment by thangvo9x** [comment]
Hi. They're working fine. Please refer detail more here: 
https://inspireui.github.io/listpro/docs/quickstart
Thanks

**Comment by thangvo9x** [comment]
@jaksatomovic  How ? let me know
