### ISSUE TITLE
[my-product] - 

### ISSUE THREAD

**Issue by assaneeguitar** [inspireui/support#2562]
i  Config files      config.dart.    data not show in home sceen app 

help me?

**Comment by assaneeguitar** [comment]
![xx1](https://user-images.githubusercontent.com/16398614/78422347-cc185d00-7688-11ea-9d23-32923ad851e5.jpg)
![Screenshot_20200404-151631](https://user-images.githubusercontent.com/16398614/78422351-d33f6b00-7688-11ea-8ce8-1d57908d7ca6.jpg)

**Comment by minhcasi** [comment]
Hi, thank you for the feedback. Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads it's used to verify your proof of purchase? 
Sorry for any inconvenience, we will reopen the ticket when it is verified, thank you!

**Comment by assaneeguitar** [comment]
![1](https://user-images.githubusercontent.com/16398614/78535058-b6846e00-7815-11ea-8a3c-4bf9af1a5c1c.png)
![2](https://user-images.githubusercontent.com/16398614/78535070-bdab7c00-7815-11ea-915f-2f5e42d13fa2.png)
