### ISSUE TITLE
[fluxstore] - Webview payment page issue

### ISSUE THREAD

**Issue by khalidsharif** [inspireui/support#2563]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
I am not able to complete the web payment process please check the video below:

https://yadi.sk/i/Wf5i1ON565fi3w

I am using the latest release 1.6.6 fluxstore woocommerce

2. Screenshots issues (required):

<img width="486" alt="Screen Shot 2020-04-04 at 12 21 24 PM" src="https://user-images.githubusercontent.com/50369621/78423413-cf065400-766e-11ea-88a1-cfc64705c399.png">

3. Proof of my purchased (required):

https://user-images.githubusercontent.com/50369621/77859009-8fbfa980-720f-11ea-8361-1d13561501c6.png

3. Config files (required)

[common.zip](https://github.com/inspireui/support/files/4431083/common.zip)

**Comment by minhcasi** [comment]
@khalidsharif - we will update new patching for the Webview issue in 1-2 days - thanks

**Comment by minhcasi** [comment]
please help to download the latest 1.6.6b, there is a new cool One-Page-Checkout via Webview feature that has been added.

Also, upload the detail file change from Gitlab, if you have not accessed to the repo, please submit this link https://docs.google.com/forms/d/e/1FAIpQLSeuBqUkScy42V7KKhfNPj0fl581anrB1mWkbMa3p2WQt7fhfw/viewform

**Comment by khalidsharif** [comment]
The One-Page-Checkout ask me to login everytime I want to checkout right ? the normal way will not work ?
I think I have acces to your gitlab. Which detail file I have to upload ? 
Shall I open an issue topic there ?

**Comment by minhcasi** [comment]
@khalidsharif - the normal way still work, this is extra features - if you have logged in from the app, it will be synced automatically when checkout. The new version is also available to download from http://codecayon.net/downloads 

Our team will check and send invitation shortly - thank you!
