### ISSUE TITLE
[Fluxstore - Woo] - (Important) Filtering issue and more "1.6.5 1-2-3"

### ISSUE THREAD

**Issue by sketchuprzr** [inspireui/support#2564]
Hi @trunghieuvn @minhcasi 
### Problem 1 ; 🟥
filtering feature works for only 1 page. I have displayed 10 products on each page in the application. When you drag the page down, it loads the next page.

But the problem is this;
If the "on Sale" filter is enabled, it only validates this for page 1.
Filtering continues invalid when I drag the page down.
**However, there are "on sale" products on multiple pages (page = 1, page = 2, page = 3 ...) on my site, just like the video appears.**

📷 Video;
https://media.giphy.com/media/UTSt2CS89oMrenaLQN/source.gif

### Problem 2; 🟥
When I fixed the filtering, I realized that this only applies to the main categories. When I want to see the sub-categories, just as before, no products are displayed. Because when I enter the subcategory, "index" does not work.

🟢 Main category = products appear 
🟠 Subcategory = Products are not visible 
🟢 Sub / Subcategory = products are visible 

📷 Video;
https://media.giphy.com/media/l3rsc3cG8p6RVBkrGN/source.gif

### Problem 3; 🟧 
On my site, a standard visual definition for non-visual products. But this does not appear in the visual application and gives an error like this; "edited"

📷 Screen Shots;
![image](https://user-images.githubusercontent.com/60021696/78434929-dafa1200-767e-11ea-8c61-bc335abdac82.png)
![image](https://user-images.githubusercontent.com/60021696/78435007-e0eff300-767e-11ea-8012-ee4c93966265.png)

### Problem 4; 🟥 
Firebase Push notification does not work on the iOS platform. There is no problem on Android. Firebase Push Notification is working incorrectly on iOS too.
There is no notification when the application is in the background. But when the app is open, notification is coming.

### Problem 5 (Request); 🟪 
There are too many products on some shopping sites. Therefore, the screen loads very late when the application is opened. Meanwhile, he can play a flare animation on the screen. This may vary from store to store. It would be much better if it uses this lottie. Because there are thousands of images in lottie, and very nice visuals can be created using the after effect. Flare is a disgusting platform. Still, it's up to you to evaluate it. Below is the video showing that the app was installed late.

📷 Video;
![bekleme](https://user-images.githubusercontent.com/60021696/78444618-a6d42080-7681-11ea-9857-6015e1fcb070.gif)

📷 An example of a lottie I made;
https://lottiefiles.com/13983-page-loading-app-tr
https://lottiefiles.com/13814-shop-app-loading
https://lottiefiles.com/9796-shop-loading
https://lottiefiles.com/14221-page-loading-for-app-tr
... etc

### Problem 6 (Request); 🟪 
I want to add a button to the Navbar. And when I press this button, I want to open a page that I prepared. "example.dart".
Like this; 
`FlatButton(
onPressed: () {
Navigator.push( context, MaterialPageRoute(builder: (context) =>example()));
}`
or something like that.
Apart from that, can we add a button to the home page?

**Comment by trunghieuvn** [comment]
> Problem 1 ; 🟥
> filtering feature works for only 1 page. I have displayed 10 products on each page in the application. When you drag the page down, it loads the next page.
> 
> But the problem is this;
> If the "on Sale" filter is enabled, it only validates this for page 1.
> Filtering continues invalid when I drag the page down.
> However, there are "on sale" products on multiple pages (page = 1, page = 2, page = 3 ...) on my site, just like the video appears.
> 
> 📷 Video;
> https://media.giphy.com/media/UTSt2CS89oMrenaLQN/source.gif

Hi, on this issue please add feature and onSale parameters to the `onLoadMore` function on file `lib/screens/products/products.dart`


![image](https://user-images.githubusercontent.com/19247680/78517534-d7ce6580-77e7-11ea-9cb0-6d9c5b5cf8e5.png)

The remaining issues I am checking. I will respond as soon as I finish solving them. 
Please wait for me. Thanks.

**Comment by trunghieuvn** [comment]
Hi @sketchuprzr ,  I cannot see the gif links that you send because the resolution is too low. Please send me the videos, you can upload to dropbox, google drive and share the link for me.

![video](https://user-images.githubusercontent.com/19247680/78518093-9c349b00-77e9-11ea-9e6c-85c898482686.gif)

**Comment by sketchuprzr** [comment]
> Hi @sketchuprzr , I cannot see the gif links that you send because the resolution is too low. Please send me the videos, you can upload to dropbox, google drive and share the link for me.

Try This: 

![giphy](https://user-images.githubusercontent.com/60021696/78557542-a53d6080-7819-11ea-8e36-152384b8a7e8.gif)

**Comment by sketchuprzr** [comment]
Hi @trunghieuvn @minhcasi ,
 Still no improvement on these important issues?

Thanks..

**Comment by minhcasi** [comment]
@sketchuprzr - we are still working on the update, please bear with us for these improvements and update - thank you!

**Comment by sketchuprzr** [comment]
Hello @minhcasi @trunghieuvn ,
 it's been a long time. No improvement? Our application is in maintenance mode and we cannot use the system. We are still waiting for editing!
There is no edit yet.

**Comment by trunghieuvn** [comment]
Hi @sketchuprzr ,
Sorry to keep you waiting. I have tried but also cannot reproduce these errors to find out the cause. To solve this issue faster, please add my skype, I will support you to handle these issues.

My Skype: trunghieu-it@hotmail.com

**Comment by sketchuprzr** [comment]
Hi @trunghieuvn @minhcasi ,@everyone
 can't make sense of your work. It's been 15 days since I reported the error, and you return after 14 days. In the return you make; you state that you do not understand the problem.

Problems write very clearly!

Do I need to write again!
separate for ios
We tried separately for Android.
3 different software developers tried these problems and couldn't find a solution.

I don't find your skype solution right. Because one of you previously gave the skype address, when I talked it was unable to find a solution to the problem. So you can not provide solutions with skype. You say different things.

**I'll send you the source files if you want. But it is very sad to say that you cannot understand the problem in 14 days.**

**this is a big problem! You ask why?**
Listen:
**1)**
![image](https://user-images.githubusercontent.com/60021696/79690377-cb73ef00-8262-11ea-8ffa-e1fe5ee48a5f.png)
in the product sales description
Includes "onesignal". But you removed it. The person who bought the software from you gets it by thinking that this feature is available.

**2)**
![image](https://user-images.githubusercontent.com/60021696/79690433-09711300-8263-11ea-8741-4889833ea6a0.png)
It writes support via push notification with firebase.
But ios doesn't work this either!

Add firebase pn in pure form to your ios app. and try! it's that simple! This feature does not work in the background when the application is closed! it's that simple to understand!

**3)**

> Problem 1 ; 🟥
> filtering feature works for only 1 page. I have displayed 10 products on each page in the > > application. When you drag the page down, it loads the next page.

> But the problem is this;
> If the "on Sale" filter is enabled, it only validates this for page 1.
> Filtering continues invalid when I drag the page down.
> However, there are "on sale" products on multiple pages (page = 1, page = 2, page = 3 ...) on my > site, just like the video appears.

you have suggested a solution for this problem;
https://github.com/inspireui/support/issues/2564#issuecomment-609532926

I also mentioned that this solution does not work;
https://github.com/inspireui/support/issues/2564#issuecomment-609758363

but there was no turn on this matter.
I am sure that there is no one in this platform who makes a detailed explanation and content as much as I do!

a team member with whom I contacted skype before;
"you can return" if you want
He also!
This is not a solution! We have made so many arrangements and we need to return it because we couldn't solve an error! It has been 3 months since I received the application! We have been trying to use the application for so long. we have made hundreds of edits. Since I bought the application, due to my texts and explanations, dozens of errors have been corrected and dozens of edits have been made! If you are going to say "You can return the application" once again do not answer at all.

this topic has become really annoying.
I don't understand why you are so upset ..

however, I really liked your application. And in my country, "turkey" I want to spread this practice.
But hundreds of software developers around me ask me;
"Should I buy the application?"
I answer;
"there are still problems in practice"
why so?

**Comment by minhcasi** [comment]
@sketchuprzr 

1. As OneSignal is having the critical crashing issue that cause the build broken so that we just hold on support on this library, we will revest this feature when it is stable 

2. We could not reproduce this issue, it works fine with our testing. You can zip your current source code and send back us for checking - please note that on the iOS you need to have purchased Apple Developer Account to make it work, try to use this video guide on ios - https://www.youtube.com/watch?v=rFCcWNRPrSk&t=89s

3. Fix on latest build 1.6.7 - we will update new version on Gitlab today

Thank you very much for your suggestion so far, as you are also a good developer - if you could find out any issues and could fix the issues, we could offer to pay you the cost. Please help to provide more positive words instead of claiming the issues. 

As you know - this product is providing the full source code package with a very reasonable price, I believe you could not find the same quality on the market. Yes, there could have some issues that the team is working hard and willing to fix it, but at the critical time of the CoV time crisis, I'm sure you guys also have some impact on your work and the same with us - thank you!

**Comment by sketchuprzr** [comment]
@minhcasi 
First of all thank you for your return.

I downloaded version 1.6.7 for edits today. But the system has detected many problems.

I do not charge any fees for problem and feature fixes & suggestions.
Yes, your application is very nice and has a reasonable price, but it still has problems. I was not aware of these problems before I received the application. If I knew it would change my mind. But it's been 3 months, I don't think my mind can change after this time. Because we lost a lot of time!

We are all sorry for the Covid virus. Everyone should show understanding in this regard. I show understanding too. But not less than 14 days. We are really shocked when we get an answer saying "we didn't understand the problem" after 14 days!

I will try their suggestions for ios, but I am waiting for version 1.6.7 first.

Currently, bugs for version 1.6.7 are like this;

![image](https://user-images.githubusercontent.com/60021696/79914500-142bd380-842e-11ea-8d77-bc90dceefa8e.png)

[errors log.txt](https://github.com/inspireui/support/files/4512660/errors.log.txt)

I think there is a problem with the file paths.

thank you.

**Comment by minhcasi** [comment]
@sketchuprzr - thank you for quick feedback, please try to clean up the cache and rebuild the source again, it's ok with my checking - https://tppr.me/NZKAw

Make sure to use the fresh download from GitHub as we have updated and refactored the source more powerful, you could check the modes/user to see if like this screenshot - https://tppr.me/6Lb8p

**Comment by sketchuprzr** [comment]
Hi @minhcasi ,
As you said, I downloaded the final version of the project.
I cleared the cache.

But version 1.6.7 is not the same as the photo you sent. The files are in different folders.

for example, you can compare the folders in these two pictures.

![image](https://user-images.githubusercontent.com/60021696/79935275-2ec97100-845d-11ea-9ef1-cccdc2e84085.png)

https://tppr.me/6Lb8p

Currently I have cleared the cache and some errors still persist.

What I want from you is to download 1.6.7 version from gitlab and try again.

Logs:
![image](https://user-images.githubusercontent.com/60021696/79935341-5b7d8880-845d-11ea-9e99-23d3ee5f31ac.png)
[logs.txt](https://github.com/inspireui/support/files/4513550/logs.txt)

**Comment by minhcasi** [comment]
@sketchuprzr - I got you, I've updated the build, please try to pull it again - there is some redundancy file that not remove when I commit the source.

Do you have skype so that we could reach you quickly for urgent report - thanks

**Comment by sketchuprzr** [comment]
@minhcasi  - I applied the edit. Currently worked. Thank you. I will review the application in detail and return again.

You can give me your skype address.

We do not prefer skype in Europe.
In Western Europe, Discdord is generally used for such situations. I can recommend it to you.

I downloaded skype right now. I just had to use it for you.

**Comment by minhcasi** [comment]
@sketchuprzr - pls add my skype: minhcasi

If you are using Telegram, please add my id: inspireui

Thank you!

**Comment by minhcasi** [comment]
move the issue to notion note with a private VIP support ;)
