### ISSUE TITLE
Beonews - Analytic Tracking of Post Visits

### ISSUE THREAD

**Issue by kevlict** [inspireui/support#2565]
I would like to track the post that my visitors see in the app.

Can I track the post title or even the url and be seen in google analytics?

Thanks

**Comment by minhcasi** [comment]
@kevlict - pls move the conversation to your same ticket #2566 

Also, help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads

**Comment by kevlict** [comment]
[image: Screenshot 2020-04-05 at 12.10.35 PM.png]
