### ISSUE TITLE
CustomPage Shown in Android not shown in IOS

### ISSUE THREAD

**Issue by kevlict** [inspireui/support#2566]
I have purchased BeoNews and the purchase code has already been sent to you before.

I have a custompage but it cannot be shown in IOS as attached.

Please advise.

![78420174-55c32d00-767f-11ea-970d-b572939389c2](https://user-images.githubusercontent.com/54314498/78450094-a900a400-76ae-11ea-9035-85009d7b4021.jpg)

**Comment by minhcasi** [comment]
@kevlict - could you share your custom page URL here so that we could have a quick check? Thanks

**Comment by kevlict** [comment]
Yes sure.

URL: https://www.simplytastehk.com/contact-us

Kevin

**Comment by luyx2412** [comment]
Hi @kevlict Can you send me the Config.js and AppConfig.json? Because the contact is id, so i need the files to investigate.

Thanks
