### ISSUE TITLE
[Fluxstore Shopify] - Can't Load Products by Category

### ISSUE THREAD

**Issue by IAPCorporate** [inspireui/support#2567]
The apps seems to be connected with the store, I see all my categories in hamburger menu. But, when I try to link it with a category in the home page it doesn't load any content. It returns null. I did generate my category through GraphiQL.

Secondly, I don’t want Wordpress Blog. I want Shopify Blog and the posts to be loaded from Shopify.

**Comment by IAPCorporate** [comment]
Any update @minhcasi we are waiting to fix this and launch our app. Please!

**Comment by minhcasi** [comment]
Hi, thank you for the feedback. Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads it's used to verify your proof of purchase? 
Sorry for any inconvenience, we will reopen the ticket when it is verified, thank you!

**Comment by IAPCorporate** [comment]
Sure, here you go.
![Screen Shot 2020-04-05 at 08 25 00](https://user-images.githubusercontent.com/62869859/78466505-06304000-7717-11ea-9a73-dfa957cc4843.png)

**Comment by IAPCorporate** [comment]
hello????

**Comment by minhcasi** [comment]
@IAPCorporate - thank you, it's verified - could you help to share your common / config folder so that we could help for checking - very best!

**Comment by IAPCorporate** [comment]
My connection works fine with the website. My problem is that I can't generate "Collection" id from collections with spaces in between like "New Arrivals" with GraphiQL. Please help with that.

**Comment by luyx2412** [comment]
Hi @IAPCorporate 
- Can you do follow the guide to get right collection id? Can you send me the config_en.json? And this is the video guide https://www.youtube.com/watch?v=OIpnoThJ2Rs
- we will update next version replace wordpress blog.

Thanks

**Comment by IAPCorporate** [comment]
Thanks a lot @luyx2412 it worked. Just 2 more things, if you could respond now so that I can launch my app immediately after. Please see the screenshots attached. I want to remove;

1. Extra white space in the product page 
2. "Title" & "Default Title" to "Vendor and Vendor Name".
3. Remove the word "Title" from the order page. 

![Screen Shot 2020-04-07 at 19 51 33](https://user-images.githubusercontent.com/62869859/78687383-58d14e00-7909-11ea-9a8c-327fa8072ef9.png)

![Screen Shot 2020-04-07 at 19 51 28](https://user-images.githubusercontent.com/62869859/78687338-4d7e2280-7909-11ea-8acc-2efda4d0aa86.png)
