### ISSUE TITLE
Smartchat Whatsapp Fail to open

### ISSUE THREAD

**Issue by jmpena** [inspireui/support#2568]
having this in config.dart whatsapp://send?phone=8493610727 and smartchat enable it says:

"Cannot launch this app, makes sure your settings on config.dat is correct"

**Comment by jmpena** [comment]
![image](https://user-images.githubusercontent.com/8821920/78460048-8f019a00-768b-11ea-98d0-eac3787516bd.png)

**Comment by robaa1418** [comment]
I solved by in config.dart 
in smartchat 
in app 
change link to https://api.whatsapp.com/send?phone=your phone

**Comment by minhcasi** [comment]
- thank you for resolving it quickly, we will update the document for this suggestion - very best!
