### ISSUE TITLE
[MStore Pro] - Affiliate Links

### ISSUE THREAD

**Issue by san2pedro** [inspireui/support#2569]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. when i press buy now it take to my website not to affiliated link.
how i can change it then press buy now it will go to affiliated link not to my website.

![Screenshot_3](https://user-images.githubusercontent.com/13208693/78453492-bdd33c80-769a-11ea-9cb6-5ce2080a6812.png)

**Comment by minhcasi** [comment]
@san2pedro - could i check if you have updated the product as Affiliate from the Woocommerce side? https://tppr.me/gz436

**Comment by san2pedro** [comment]
yes add link but take to my website to product page 

![afflite](https://user-images.githubusercontent.com/13208693/78479646-fb44d200-774d-11ea-8e0c-f5d1ac0c1ffb.png)

**Comment by minhcasi** [comment]
@luyx2412 - please help to fix this issue, we only open the WebView if check the product is affiliated/extend_url

**Comment by san2pedro** [comment]
???

**Comment by luyx2412** [comment]
Hi @san2pedro Sorry about reply you late.
Can you send me the AppConfig.json and Config.js file? 

Thanks

**Comment by san2pedro** [comment]
upload zip dosnt give me upload json
[appconfig_config.zip](https://github.com/inspireui/support/files/4445522/appconfig_config.zip)

**Comment by san2pedro** [comment]
any news?

**Comment by luyx2412** [comment]
Hi @san2pedro i just tested your config and everything worked normal.
![image](https://user-images.githubusercontent.com/8909619/79036557-6a5d7300-7bf3-11ea-9342-78d986676930.png)
So can you describe your issue?

Thanks

**Comment by san2pedro** [comment]
Can do will take to website afflite example press buy now and will take to amazon product not to my website

**Comment by luyx2412** [comment]
Hi @san2pedro You can reaplace `product.permalink` with amazon product link to redirect it.

Thanks

**Comment by san2pedro** [comment]
Ty but send me code sorry for asking cause know just c#

**Comment by luyx2412** [comment]
Hi @san2pedro Can you send me the link, i will add the code and resend you again.

Thanks

**Comment by san2pedro** [comment]
The problems it's about 600 links so if have easy way to send each product
to their product on amazon or aliexpress  directly

ср, 15 апр. 2020 г., 06:28 luyx2412 <notifications@github.com>:

**Comment by minhcasi** [comment]
@san2pedro - could you try to quick fix by replace the code from above screenshot by  this code (it mean to remove the if condition)

```
this.props.onOpenWebsite(product.permalink)
```

![image](https://user-images.githubusercontent.com/1459805/79426189-f9e89480-7fec-11ea-8a2c-ec55f534da43.png)

**Comment by minhcasi** [comment]
Or check to see if there is any hidden link from product object or `meta_data` from wooCommerce that have not mapped to the product object
