### ISSUE TITLE
Buzzapp setup issue using CeBuilder with grpc

### ISSUE THREAD

**Issue by Rixsta** [inspireui/support#257]
Hi Just wondering if you guys can help me get this going I have this error

682 warn @babel/helper-create-class-features-plugin@7.3.0 requires a peer of @babel/core@^7.0.0 but none is installed. You must install peer dependencies yourself.
683 warn @babel/plugin-proposal-class-properties@7.3.0 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.
684 warn @babel/plugin-proposal-decorators@7.3.0 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.
685 warn @babel/plugin-proposal-export-default-from@7.2.0 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.
686 warn @babel/plugin-proposal-nullish-coalescing-operator@7.2.0 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.
687 warn @babel/plugin-proposal-object-rest-spread@7.3.1 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.
688 warn @babel/plugin-proposal-optional-catch-binding@7.2.0 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.
689 warn @babel/plugin-proposal-optional-chaining@7.2.0 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.
690 warn @babel/plugin-syntax-decorators@7.2.0 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.
691 warn @babel/plugin-syntax-dynamic-import@7.2.0 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.
692 warn @babel/plugin-syntax-export-default-from@7.2.0 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.
693 warn @babel/plugin-syntax-flow@7.2.0 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.
694 warn @babel/plugin-syntax-jsx@7.2.0 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.
695 warn @babel/plugin-syntax-nullish-coalescing-operator@7.2.0 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.
696 warn @babel/plugin-syntax-object-rest-spread@7.2.0 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.
697 warn @babel/plugin-syntax-optional-catch-binding@7.2.0 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.
698 warn @babel/plugin-syntax-optional-chaining@7.2.0 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.
699 warn @babel/plugin-syntax-typescript@7.2.0 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.
700 warn @babel/plugin-transform-arrow-functions@7.2.0 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.
701 warn @babel/plugin-transform-block-scoping@7.2.0 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.
702 warn @babel/plugin-transform-classes@7.2.2 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.
703 warn @babel/plugin-transform-computed-properties@7.2.0 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.
704 warn @babel/plugin-transform-destructuring@7.2.0 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.
705 warn @babel/plugin-transform-exponentiation-operator@7.2.0 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.
706 warn @babel/plugin-transform-flow-strip-types@7.2.3 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.
707 warn @babel/plugin-transform-for-of@7.2.0 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.
708 warn @babel/plugin-transform-function-name@7.2.0 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.
709 warn @babel/plugin-transform-literals@7.2.0 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.
710 warn @babel/plugin-transform-modules-commonjs@7.2.0 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.
711 warn @babel/plugin-transform-object-assign@7.2.0 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.
712 warn @babel/plugin-transform-parameters@7.2.0 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.
713 warn @babel/plugin-transform-react-display-name@7.2.0 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.
714 warn @babel/plugin-transform-react-jsx@7.3.0 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.
715 warn @babel/plugin-transform-react-jsx-source@7.2.0 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.
716 warn @babel/plugin-transform-regenerator@7.0.0 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.
717 warn @babel/plugin-transform-runtime@7.2.0 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.
718 warn @babel/plugin-transform-shorthand-properties@7.2.0 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.
719 warn @babel/plugin-transform-spread@7.2.2 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.
720 warn @babel/plugin-transform-sticky-regex@7.2.0 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.
721 warn @babel/plugin-transform-template-literals@7.2.0 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.
722 warn @babel/plugin-transform-typescript@7.2.0 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.
723 warn @babel/plugin-transform-unicode-regex@7.2.0 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.
724 warn create-react-context@0.2.2 requires a peer of prop-types@^15.0.0 but none is installed. You must install peer dependencies yourself.
725 warn @react-navigation/native@3.1.3 requires a peer of react-native@* but none is installed. You must install peer dependencies yourself.
726 warn react-native-gesture-handler@1.0.15 requires a peer of react-native@>= 0.50.0 but none is installed. You must install peer dependencies yourself.
727 warn react-native-screens@1.0.0-alpha.22 requires a peer of react-native@* but none is installed. You must install peer dependencies yourself.
728 warn create-react-context@0.2.3 requires a peer of prop-types@^15.0.0 but none is installed. You must install peer dependencies yourself.
729 warn eslint-plugin-react-native@3.6.0 requires a peer of eslint@^3.17.0 || ^4 || ^5 but none is installed. You must install peer dependencies yourself.
730 warn react-native-maps@0.22.1 requires a peer of react-native@>= 0.51 but none is installed. You must install peer dependencies yourself.
731 warn expo-react-native-adapter@1.2.0 requires a peer of react-native@^0.57.1 but none is installed. You must install peer dependencies yourself.
732 warn lottie-react-native@2.5.0 requires a peer of react-native@>=0.46 but none is installed. You must install peer dependencies yourself.
733 warn metro-react-native-babel-preset@0.49.2 requires a peer of @babel/core@* but none is installed. You must install peer dependencies yourself.
734 warn react-native-branch@2.2.5 requires a peer of react-native@>=0.40.0 but none is installed. You must install peer dependencies yourself.
735 warn react-native-clean-webview@1.0.1 requires a peer of react-native@^0.53.0 but none is installed. You must install peer dependencies yourself.
736 warn react-native-expo-image-cache@3.2.0 requires a peer of react-native@* but none is installed. You must install peer dependencies yourself.
737 warn react-native-flip-page@0.4.0 requires a peer of react-native@>= 0.56.x but none is installed. You must install peer dependencies yourself.
738 warn react-native-gesture-handler@1.0.9 requires a peer of react-native@>= 0.50.0 but none is installed. You must install peer dependencies yourself.
739 warn react-native-paper@2.9.1 requires a peer of react-native@* but none is installed. You must install peer dependencies yourself.
740 warn react-native-reanimated@1.0.0-alpha.10 requires a peer of react@16.0.0-alpha.6 but none is installed. You must install peer dependencies yourself.
741 warn react-native-reanimated@1.0.0-alpha.10 requires a peer of react-native@^0.44.1 but none is installed. You must install peer dependencies yourself.
742 warn react-native-render-html@3.10.0 requires a peer of prop-types@>=15.5.10 but none is installed. You must install peer dependencies yourself.
743 warn react-native-render-html@3.10.0 requires a peer of react-native@* but none is installed. You must install peer dependencies yourself.
744 warn react-native-safe-area-view@0.12.0 requires a peer of react-native@* but none is installed. You must install peer dependencies yourself.
745 warn react-native-safe-module@1.2.0 requires a peer of react-native@* but none is installed. You must install peer dependencies yourself.
746 warn react-native-screens@1.0.0-alpha.15 requires a peer of react-native@* but none is installed. You must install peer dependencies yourself.
747 warn react-native-scrollable-tab-view@0.10.0 requires a peer of react-native@>=0.20.0 but none is installed. You must install peer dependencies yourself.
748 warn react-native-snap-carousel@3.7.5 requires a peer of react-native@* but none is installed. You must install peer dependencies yourself.
749 warn react-native-svg@8.0.8 requires a peer of react-native@>=0.50.0 but none is installed. You must install peer dependencies yourself.
750 warn react-native-tab-view@1.3.2 requires a peer of react-native@* but none is installed. You must install peer dependencies yourself.
751 warn react-native-timeago@0.4.0 requires a peer of react-native@* but none is installed. You must install peer dependencies yourself.
752 warn react-native-view-shot@2.5.0 requires a peer of react-native@* but none is installed. You must install peer dependencies yourself.
753 warn react-navigation@3.1.2 requires a peer of react-native@* but none is installed. You must install peer dependencies yourself.
754 warn react-navigation-drawer@1.1.0 requires a peer of react-native@* but none is installed. You must install peer dependencies yourself.
755 warn react-navigation-drawer@1.1.0 requires a peer of react-native-gesture-handler@^1.0.12 but none is installed. You must install peer dependencies yourself.
756 warn react-navigation-material-bottom-tabs@0.4.0 requires a peer of react-native@* but none is installed. You must install peer dependencies yourself.
757 warn react-native-safe-area-view@0.7.0 requires a peer of react-native@* but none is installed. You must install peer dependencies yourself.
758 warn react-navigation-tabs@0.4.1 requires a peer of react-native@* but none is installed. You must install peer dependencies yourself.
759 warn react-navigation-tabs@0.4.1 requires a peer of react-navigation@^2.0.0 but none is installed. You must install peer dependencies yourself.
760 warn react-navigation-stack@1.0.6 requires a peer of react-native@* but none is installed. You must install peer dependencies yourself.
761 warn react-navigation-tabs@1.0.2 requires a peer of react-native@* but none is installed. You must install peer dependencies yourself.
762 warn reactotron-react-native@2.1.0 requires a peer of react-native@>=0.40.0 but none is installed. You must install peer dependencies yourself.
763 verbose stack Error: grpc@1.18.0 install: `node-pre-gyp install --fallback-to-build --library=static_library`
763 verbose stack Exit status 1
763 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
763 verbose stack     at EventEmitter.emit (events.js:197:13)
763 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
763 verbose stack     at ChildProcess.emit (events.js:197:13)
763 verbose stack     at maybeClose (internal/child_process.js:978:16)
763 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
764 verbose pkgid grpc@1.18.0
765 verbose cwd C:\Buzzapp.1.3.0\Source
766 verbose Windows_NT 10.0.17134
767 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "grpc"
768 verbose node v11.9.0
769 verbose npm  v6.5.0
770 error code ELIFECYCLE
771 error errno 1
772 error grpc@1.18.0 install: `node-pre-gyp install --fallback-to-build --library=static_library`
772 error Exit status 1
773 error Failed at the grpc@1.18.0 install script.
773 error This is probably not a problem with npm. There is likely additional logging output above.
774 verbose exit [ 1, true ]

**Comment by Rixsta** [comment]
Thats after trying to install grpc on its own

**Comment by Rixsta** [comment]
This is what happens in CeBuilder, it gets stuck at grpc
[https://www.rikibuckingham.com/wp-content/uploads/2019/02/www.rikibuckingham.com_CODE.jpg](url)

**Comment by minhtruong315** [comment]
Hi @Rixsta Can you add my skype? I will help you check it via teamview.
my skype: minhtruong315

**Comment by Rixsta** [comment]
Thanks I have added you, got to go out now but Im thinking of reinstalling my windows and then using CeBuilder on its own to set things up from scratch. As this setup had been done by me not using CeBuilder.
Do I need to install teamview ?
Thanks

**Comment by minhtruong315** [comment]
Hi @Rixsta Pls add my skype again. minhtruong315

**Comment by KIRANNAIR1** [comment]
My CeBuilder Not woking , ICon Keep Spinning. Is it Compulsory to install Chocolatey. 
I already have Yarn, Node.js & Expo installed
