### ISSUE TITLE
Cannot run FluxStore Pro v 1.6.6

### ISSUE THREAD

**Issue by kimsung2018gnu** [inspireui/support#2570]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
I've purchase FluxStore Pro a few days ago but I couldn't run this project. It shows many errors as you can see in this attached screenshot.

2. Screenshots issues (required):
![Screen Shot 2563-04-05 at 14 30 11](https://user-images.githubusercontent.com/63182499/78469347-68566880-774a-11ea-91b2-9e9c748b3aa6.png)

3. Proof of my purchased (required):
![Screen Shot 2563-04-05 at 14 30 05](https://user-images.githubusercontent.com/63182499/78469342-64c2e180-774a-11ea-8a63-825d16b36676.png)

3. Config files (required)

**Comment by minhcasi** [comment]
@kimsung2018gnu - could you try to clean up the Flutter cache on your PC - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

**Comment by kimsung2018gnu** [comment]
I have already tried with those solution but it still doesn't work. I got this error in FluxStore Pro v1.6.6. 
For previous version, it is okay.

**Comment by minhcasi** [comment]
I'm sorry for the build issue, please help to download the latest 1.6.6b to fix the build issue

**Comment by kimsung2018gnu** [comment]
thanks. I have submitted a request to access gitlab already. Please kindly accept me. Thanks for your prompt response. :)

**Comment by kimsung2018gnu** [comment]
Hello @minhcasi , do you have any update? I have already submit form to access gitlab link. Could you please kindly accept me please?

**Comment by minhcasi** [comment]
@kimsung2018gnu - we already sent the invitation - pls help to check the email
