### ISSUE TITLE
[fluxnews] - No RTL support

### ISSUE THREAD

**Issue by haidarsalim** [inspireui/support#2571]
I have a problem supporting the published Arabic language and the list despite choosing the default language
I need her ignorance from right to left
![333](https://user-images.githubusercontent.com/54249914/78471527-9f248280-773a-11ea-95a1-afbe6f4b0a0b.JPG)
![Screenshot_1586079041](https://user-images.githubusercontent.com/54249914/78471530-a6e42700-773a-11ea-8e09-8fb1eeb19810.png)
![45Y](https://user-images.githubusercontent.com/54249914/78491185-34cb0c80-7751-11ea-8f13-64ca9fb63631.JPG)
![Uploading 45Y.JPG…]()

**Comment by minhcasi** [comment]
Hi, thank you for the feedback. Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads it's used to verify your proof of purchase? 
Sorry for any inconvenience, we will reopen the ticket when it is verified, thank you!

**Comment by haidarsalim** [comment]
OK
