### ISSUE TITLE
Fluxstore 1.6.6 : Compilation issues corrected manually. After that Xcode build succeeds but unable to install to iPhone.

### ISSUE THREAD

**Issue by harrisbaitalrayan** [inspireui/support#2573]
1. My issue: The flux store version 1.6.6 giving compilation issues. However I fixed these manually. The build succeeds in Xcode, however can't install to iPhone with below error : Failure Reason: No code signature found.

2. Screenshots issues (required):
<img width="1007" alt="Screen Shot 2020-04-05 at 2 58 54 PM" src="https://user-images.githubusercontent.com/13076524/78473008-6393b380-774e-11ea-8b8f-95d18be27eac.png">

3. Proof of my purchased (required):

<img width="749" alt="Screen Shot 2020-04-05 at 3 02 34 PM" src="https://user-images.githubusercontent.com/13076524/78473028-8d4cda80-774e-11ea-8d8b-314a1b8bc548.png">

3. Config files (required)

Flutter version  : 1.12.13+hotfix.9 on channel stable. Fluxstore version : 1.6.6

**Comment by minhcasi** [comment]
@harrisbaitalrayan - could you try to clean the cache - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

**Comment by minhcasi** [comment]
@harrisbaitalrayan -  please help to download the latest 1.6.6b to fix some build issue on 1.6.6 - thank you!

**Comment by harrisbaitalrayan** [comment]
OK. will check and update you the status. Thank you for quick support.

**Comment by harrisbaitalrayan** [comment]
Thanks in 1.6.6b, there is no compilation error. However still Runner cannot install on iPhone with same error:

Full trace:
Details

Unable to install "Runner"
Domain: com.apple.dtdevicekit
Code: -402620388
--
App installation failed
Domain: com.apple.dtdevicekit
Code: -402620388
Failure Reason: No code signature found.
User Info: {
    DVTRadarComponentKey = 487927;
    "com.apple.dtdevicekit.stacktrace" = (
	0   DTDeviceKitBase                     0x00000001194536e7 DTDKCreateNSError + 109
	1   DTDeviceKitBase                     0x0000000119453de9 DTDK_AMDErrorToNSError + 792
	2   DTDeviceKitBase                     0x000000011949356a __90-[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:]_block_invoke + 164
	3   DVTFoundation                       0x000000010128ac12 DVTInvokeWithStrongOwnership + 73
	4   DTDeviceKitBase                     0x0000000119493301 -[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:] + 1589
	5   IDEiOSSupportCore                   0x000000011931ba25 __118-[DVTiOSDevice(DVTiPhoneApplicationInstallation) processAppInstallSet:appUninstallSet:installOptions:completionBlock:]_block_invoke.352 + 4523
	6   DVTFoundation                       0x00000001013bbe7a __DVT_CALLING_CLIENT_BLOCK__ + 7
	7   DVTFoundation                       0x00000001013bd552 __DVTDispatchAsync_block_invoke + 809
	8   libdispatch.dylib                   0x00007fff67aba6c4 _dispatch_call_block_and_release + 12
	9   libdispatch.dylib                   0x00007fff67abb658 _dispatch_client_callout + 8
	10  libdispatch.dylib                   0x00007fff67ac0c44 _dispatch_lane_serial_drain + 597
	11  libdispatch.dylib                   0x00007fff67ac15d6 _dispatch_lane_invoke + 363
	12  libdispatch.dylib                   0x00007fff67acac09 _dispatch_workloop_worker_thread + 596
	13  libsystem_pthread.dylib             0x00007fff67d15a3d _pthread_wqthread + 290
	14  libsystem_pthread.dylib             0x00007fff67d14b77 start_wqthread + 15
);
}
--

**Comment by minhcasi** [comment]
@harrisbaitalrayan - please help to clean cache issue - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

We will also share the latest video on this page in 1-2 days - http://youtube.com/inspireui

**Comment by harrisbaitalrayan** [comment]
Tried above solution. Clean all cache and even reinstalled Xcode. But still the same error on running the project from Xcode, but same error.

Tried running the same from Android Studio. Error below:

2020-04-08 00:45:29.015 ios-deploy[44154:247750] [ !! ] Error 0xe800801c: No code signature found. AMDeviceSecureInstallApplication(0, device, url, options, install_callback, 0)
Could not install build/ios/iphoneos/Runner.app on 00008020-00023C822E52002E.
Try launching Xcode and selecting "Product > Run" to fix the problem:
  open ios/Runner.xcworkspace

**Comment by harrisbaitalrayan** [comment]
This is the error from Xcode.

Details

Unable to install "Runner"
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402620388
--
No code signature found.
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402620388
User Info: {
    DVTRadarComponentKey = 261622;
    MobileDeviceErrorCode = "(0xE800801C)";
    "com.apple.dtdevicekit.stacktrace" = (
	0   DTDeviceKitBase                     0x0000000123e9281a DTDKCreateNSErrorFromAMDErrorCode + 233
	1   DTDeviceKitBase                     0x0000000123ed3f70 __90-[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:]_block_invoke + 155
	2   DVTFoundation                       0x000000010aa76385 DVTInvokeWithStrongOwnership + 73
	3   DTDeviceKitBase                     0x0000000123ed3ca8 -[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:] + 1654
	4   IDEiOSSupportCore                   0x0000000123d4ae91 __118-[DVTiOSDevice(DVTiPhoneApplicationInstallation) processAppInstallSet:appUninstallSet:installOptions:completionBlock:]_block_invoke.352 + 4165
	5   DVTFoundation                       0x000000010aba9a10 __DVT_CALLING_CLIENT_BLOCK__ + 7
	6   DVTFoundation                       0x000000010abab652 __DVTDispatchAsync_block_invoke + 1194
	7   libdispatch.dylib                   0x00007fff67bb76c4 _dispatch_call_block_and_release + 12
	8   libdispatch.dylib                   0x00007fff67bb8658 _dispatch_client_callout + 8
	9   libdispatch.dylib                   0x00007fff67bbdc44 _dispatch_lane_serial_drain + 597
	10  libdispatch.dylib                   0x00007fff67bbe5d6 _dispatch_lane_invoke + 363
	11  libdispatch.dylib                   0x00007fff67bc7c09 _dispatch_workloop_worker_thread + 596
	12  libsystem_pthread.dylib             0x00007fff67e12a3d _pthread_wqthread + 290
	13  libsystem_pthread.dylib             0x00007fff67e11b77 start_wqthread + 15
);
}
--


System Information

macOS Version 10.15.4 (Build 19E266)
Xcode 11.4 (16134)

**Comment by harrisbaitalrayan** [comment]
Please help.

**Comment by minhcasi** [comment]
@harrisbaitalrayan - pls try to edit the Xcode setting -> check this option and login your Apple account - https://tppr.me/vFsCa

**Comment by minhcasi** [comment]
@harrisbaitalrayan  - let us know if you could fix the problem, feel free to reopen the ticket if you have further issue - thank you!

**Comment by harrisbaitalrayan** [comment]
Hi Thanks, I fixed it by creating a new flutter project and then porting the files to it.
