### ISSUE TITLE
FluxNews - Ios login page problem!!!!!

### ISSUE THREAD

**Issue by zemeister2332** [inspireui/support#2574]
1. My issue:
IOS login page problem. HELP
2. Screenshots issues :
<img src="https://i.ibb.co/3NsswDB/Screen-Shot-2020-04-05-at-5-42-51-PM.png">
3. Proof of my purchased :
<img src="https://i.ibb.co/TY7N2FZ/Screen-Shot-2020-04-05-at-5-46-38-PM.png">

**Comment by minhcasi** [comment]
@zemeister2332 - could you help to share your common folder so that we could help for checking - thanks
