### ISSUE TITLE
[FluxStore-Multivendor] - 

### ISSUE THREAD

**Issue by qorane099** [inspireui/support#2576]
1. App is crashing every time, l try to click product, with error "connection lost":

2. I did set up, login with firebase but it throws an error:

3. smart chat error, l followed document steps but still whatsapp not working with an error of "please edit config.dart":
![IMG_20200402_185743](https://user-images.githubusercontent.com/39888242/78502199-75d91600-777d-11ea-9b7f-26eacf203193.jpg)
![Uploading IMG_20200322_005709.jpg…]()

**Comment by qorane099** [comment]
![IMG_20200402_201209](https://user-images.githubusercontent.com/39888242/78502233-b33da380-777d-11ea-8e16-ee9903f047f7.jpg)


this is proof of purchase

**Comment by minhcasi** [comment]
@qorane099 - could i know which the device that you are testing the app, please also share your common and config folder so that we could try to reproduce from our side - thanks

**Comment by qorane099** [comment]
hello brother.

i am using emulator with android 9, and 3 pixel.

please have config files.
[config.zip](https://github.com/inspireui/support/files/4435491/config.zip)
[common.zip](https://github.com/inspireui/support/files/4435498/common.zip)

**Comment by qorane099** [comment]
dear,

l am also getting this below error today after l did updated dependencies:

Launching lib/main.dart on AOSP on IA Emulator in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not find com.google.firebase:firebase-core:17.3.9.
     Required by:
         project :app

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4m 10s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by qorane099** [comment]
hello please reply

**Comment by minhcasi** [comment]
@qorane099 - please hep to download the latest version and check the clean cache solution on this link https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

Let us know your checking, thank you!

**Comment by minhcasi** [comment]
How is your checking :) ?

**Comment by qorane099** [comment]
The app is working fine now, although l started from the beginning again.

I have to reset up again.

9121948906
