### ISSUE TITLE
[Fluxstore] - error when i Build and release for iOS

### ISSUE THREAD

**Issue by limitlessfirm** [inspireui/support#2577]
1. My issue: when i Build and release for iOS i see error

2. Screenshots issues (required):
![ios-release-001-without copy](https://user-images.githubusercontent.com/59250639/78509367-cf494100-778d-11ea-8ad9-ba8237fe3d82.jpg)

3. Proof of my purchased (required):
![screenshot](https://user-images.githubusercontent.com/59250639/78509379-d96b3f80-778d-11ea-9ecc-79f14bfd82f7.JPG)

3. Config files (required)

**Comment by minhcasi** [comment]
@limitlessfirm - please try to download the latest 1.6.6b to fix the issue - thanks
