### ISSUE TITLE
[fluxnews] - No RTL support

### ISSUE THREAD

**Issue by haidarsalim** [inspireui/support#2578]
I have a problem supporting the published Arabic language and the list despite choosing the default language
I need her ignorance from right to left
![333](https://user-images.githubusercontent.com/54249914/78471527-9f248280-773a-11ea-95a1-afbe6f4b0a0b.JPG)
![Screenshot_1586079041](https://user-images.githubusercontent.com/54249914/78471530-a6e42700-773a-11ea-8e09-8fb1eeb19810.png)
![45Y](https://user-images.githubusercontent.com/54249914/78491185-34cb0c80-7751-11ea-8f13-64ca9fb63631.JPG)

**Comment by haidarsalim** [comment]
Two days without a response

**Comment by dttrung26** [comment]
Hi @haidarsalim , 
kindly download attached files and replace as following: 
- blog_card_view.dart in /lib/widgets/blog_news/
- wishlist.dart in /lib/screens/
- app.dart in /lib/models/ 
please confirm if it works. 
[ticket_support#2578.zip](https://github.com/inspireui/support/files/4442093/ticket_support.2578.zip)
Happy coding!

**Comment by haidarsalim** [comment]
Thanks the problem was solved
