### ISSUE TITLE
Flux Store Shopify Android App not compiling <onesignal_google_project_number> is provided.

### ISSUE THREAD

**Issue by bilalmunir1995** [inspireui/support#2579]
D:\Shopify App\fluxstore-shopify 1.6.5\source\android\app\src\debug\AndroidManifest.xml Error: Attribute meta-data#onesignal_app_id@value at AndroidManifest.xml requires a placeholder substitution but no value for <onesignal_app_id> is provided. D:\Shopify App\fluxstore-shopify 1.6.5\source\android\app\src\debug\AndroidManifest.xml Error: Attribute meta-data#onesignal_google_project_number@value at AndroidManifest.xml requires a placeholder substitution but no value for <onesignal_google_project_number> is provided.

Following error pops up when i compile my android application to run it in android studio 
Flutter and dart are functional as i tried running an example

**Comment by bilalmunir1995** [comment]
![image](https://user-images.githubusercontent.com/37571277/78511449-30850a80-77b6-11ea-83e7-9376aa633976.png)
purchase proof

**Comment by minhcasi** [comment]
@bilalmunir1995 - note with investigating - thank you!

**Comment by raatool** [comment]
Same Issue - please help us!

**Comment by amankwatra** [comment]
Same Issue here as well. Just purchased the app yesterday and have'nt been able to run it at all.
Please help.

**Comment by amankwatra** [comment]
![scr](https://user-images.githubusercontent.com/55830839/78548225-0f580480-781e-11ea-9015-b0aa9ce7f76f.png)


Proof of purchase.

**Comment by raatool** [comment]
![image](https://user-images.githubusercontent.com/46068313/78551237-0bbc8180-780e-11ea-9bd0-a3170d29bffe.png)

**Comment by amankwatra** [comment]
I got around the error. I searched online and found a thread in which people were facing the same problem. 

Others facing the same problem can try doing this as well:

You can add the code into your library build.gradle.

like this:

buildTypes {
        release {
            minifyEnabled false
            debuggable true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.awter
            manifestPlaceholders = [onesignal_app_id: "xxxxxxx",
                                    // Project number pulled from dashboard, local value is ignored.
                                    onesignal_google_project_number: "REMOTE"]
        }
        debug {
            manifestPlaceholders = [onesignal_app_id: "xxxxx",
                                    // Project number pulled from dashboard, local value is ignored.
                                    onesignal_google_project_number: "REMOTE"]
        }
    }



Hope this helps.

**Comment by minhcasi** [comment]
@bilalmunir1995 - appreciate for your sharing

**Comment by raatool** [comment]
Hi , thank you for sharing !
Did this method work on you?
I'd appreciate an official confirmation

**Comment by amankwatra** [comment]
> Hi , thank you for sharing !
> Did this method work on you?
> I'd appreciate an official confirmation

It worked for me. that's why i shared it.

**Comment by raatool** [comment]
Hi , thank you !
In my case i pasted this code in build.gradle from app folder between defaultConfig braces 

 // One Signal:
        manifestPlaceholders = [onesignal_app_id: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
                                onesignal_google_project_number: "REMOTE"]

**Comment by bilalmunir1995** [comment]
> Hi , thank you for sharing !
> Did this method work on you?
> I'd appreciate an official confirmation

Yes this worked had to comment out 
//signingConfig signingConfigs.awter
but it worked fine thanks mate :)
