### ISSUE TITLE
[Mstore-Pro] I can't build on Android Studio

### ISSUE THREAD

**Issue by Jegufull** [inspireui/support#258]
**Required Info (please complete the following information):**
 - Product: [e.g. MStore, ListApp]
 - Your Purchased Code: [get from https://codecanyon.net/downloads]
(we may not reply if you are not our customer)

**Describe the bug**

**Screenshots**

**Additional context**
Add any other detail logs about the problem here.
If possible please share your config.js that use for the app setting

**Comment by minhcasi** [comment]
Hi, just update that we received your ticket and the team will back to check on Monday (after the Tet holiday), sorry for the delay - thank you!

**Comment by luyx2412** [comment]
Hi @Jegufull Please read the article to fix your issue https://github.com/google/ExoPlayer/issues/3168.

Thanks

**Comment by minhcasi** [comment]
As there is no response, kindly reopen the ticket if you have the issue - thanks
