### ISSUE TITLE
[FluxStore-MV] - Categories not display

### ISSUE THREAD

**Issue by avvvar** [inspireui/support#2580]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: i went through your documentation , but now i can not see the categories and the store list in my first test 

2. Screenshots issues (required): 

3. Proof of my purchased (required):6102f2a5-b660-4164-8a21-d82383dd55a8

3. Config files (required)

**Comment by minhcasi** [comment]
@avvvar - could you help to share the common and config folder so that we could help for checking - thank you!

**Comment by avvvar** [comment]
Dear @minhcasi 

Please download it here 
https://we.tl/t-9kqUOLI2OJ

**Comment by minhcasi** [comment]
@philipvu30 - please help for investigating - thank you!

**Comment by philipvu30** [comment]
It said your consumer_key is invalid. 

![image](https://user-images.githubusercontent.com/54442328/78774720-46195080-79bf-11ea-965e-04069f581f85.png)

Please check or replace it if necessary. Thanks

**Comment by avvvar** [comment]
I reseted the consumer key again and it is still the same 

https://we.tl/t-q04OCsdxmI

Regards

**Comment by avvvar** [comment]
can you please help me @philipvu30

**Comment by philipvu30** [comment]
Hi,

I need to investigate more on this issue. If possible please send me a support account for your site to this email: toan@inspireui.com. 

Thanks

**Comment by avvvar** [comment]
Dear @philipvu30 

I sent you the account

**Comment by minhcasi** [comment]
@philipvu30 - please help to set priory support on this issue

**Comment by philipvu30** [comment]
@avvvar ,

Please remove this term
![image](https://user-images.githubusercontent.com/54442328/79440285-ff9ba580-7fff-11ea-8de7-368294c14bb9.png)

You can find it in the path: lib/services/woo_commerce.dart

**Comment by avvvar** [comment]
Dear @philipvu30 

thank you very much , now i have the categories listed 

however i am facing few other issue  such as 

the list of stores are not showing 
i can not register to 

there are couple more but i am still testing them and trying to fix

**Comment by philipvu30** [comment]
Hi,

Do you mean list of vendors? And what is your issue with registration? Please provide images. Thanks

**Comment by avvvar** [comment]
yes list of vendors 

and this is the error message 

![WhatsApp Image 2020-04-21 at 02 46 41](https://user-images.githubusercontent.com/39483126/79809919-6b706c00-837a-11ea-9c6c-3bc3777715e6.jpeg)

**Comment by philipvu30** [comment]
Please check if your MainActivity is like this

![image](https://user-images.githubusercontent.com/54442328/79858946-67842e80-83fa-11ea-83c1-823f3bafa980.png)

**Comment by avvvar** [comment]
hey 
now it can not be installed on the app 
it gives 

E/FlutterFcmService( 6996): Fatal: failed to find callback

there is toomuch bug and issues , can you send me a bugfree version? or set it up for me 

it has been 20 days since i purchased yet there is not chance to run it correctly

**Comment by philipvu30** [comment]
Hi,

Send me a account for your site to this email: toan@inspireui.com and I'll see what I can do. 
Thanks

**Comment by avvvar** [comment]
I have already sent you account info, 

i just replied the previous email

**Comment by philipvu30** [comment]
Hi,

Sent you the new lib folder and the pubspec.yaml via email. Please replace them then run these 2 commands:
- flutter clean
- flutter packages get

**Comment by avvvar** [comment]
thank you very much,
the registration is okey , i am trying to check the other things right now 

one more thing for now, you mentioned that i have to mark the vendor as featured so that they will be displayed in store list , can you explain how to do that cause i can not find it 
![WhatsApp Image 2020-04-28 at 20 56 54](https://user-images.githubusercontent.com/39483126/80521028-feb92b00-8992-11ea-968d-e4d4393fe1ea.jpeg)

**Comment by avvvar** [comment]
also the add to cart and buy now buttons are not working now

**Comment by philipvu30** [comment]
Hi,

I'm so sorry I was mistaken. I thought you were using dokan theme. 

Please change this term in your config.dart
"type": "dokan" to this   "type": "wcfm"

Also this one does not support featured vendors feature.

What exactly is the non-working product?

And Stores are also working now. Would you mind checking it again?

![image](https://user-images.githubusercontent.com/54442328/80561595-31086e00-8a0f-11ea-85de-e7018a5e88a7.png)

**Comment by avvvar** [comment]
Hello 

thank you , the store list is fine now 

but still i can not add products to the cart 

and there are alot of extra text in the description
![WhatsApp Image 2020-04-30 at 05 39 46](https://user-images.githubusercontent.com/39483126/80666529-2993a400-8aa5-11ea-92ec-2eb3be0af4c8.jpeg)

**Comment by kenneth1690** [comment]
> Hi,
> 
> Sent you the new lib folder and the pubspec.yaml via email. Please replace them then run these 2 commands:
> 
> * flutter clean
> * flutter packages get
> 
> ![image](https://user-images.githubusercontent.com/54442328/80350522-0c8b8500-889b-11ea-9efd-9b2ff29a5bf3.png)

how to enable vendors in home screen ?

**Comment by philipvu30** [comment]
Hi,

Please remove the feature vendors in your config_.json as it only applies to dokan theme.

**Comment by avvvar** [comment]
> Hello
> 
> thank you , the store list is fine now
> 
> but still i can not add products to the cart
> 
> and there are alot of extra text in the description
> ![WhatsApp Image 2020-04-30 at 05 39 46](https://user-images.githubusercontent.com/39483126/80666529-2993a400-8aa5-11ea-92ec-2eb3be0af4c8.jpeg)

Dear @philipvu30 

please check my issue

**Comment by philipvu30** [comment]
Hi,

Please add this line to this file: lib/models/product/product.dart

![image](https://user-images.githubusercontent.com/54442328/81030641-b5e20480-8eb3-11ea-9708-4e404f94dd7f.png)


description = description.replaceAll(RegExp(r'\[(.*?)\]'), '');

**Comment by avvvar** [comment]
Dear @philipvu30 

i still have both issues , i can not add products to the cart and i see the extra text
this installation took more than a month for me please give me a lib that works perfectly 

Regards

**Comment by philipvu30** [comment]
Hi,

Please send your new config files to my email toan@inspireui.com.
Thanks

**Comment by avvvar** [comment]
@philipvu30 
Hi

i have sent you

**Comment by philipvu30** [comment]
Hi,

I replied to your email with new lib. Please check.

**Comment by avvvar** [comment]
@philipvu30 

Thank you very much let me test it
