### ISSUE TITLE
[FluxNews 1.3] - RelatedBlogList showing "Getting Error" and Date Display Problem

### ISSUE THREAD

**Issue by bidfor** [inspireui/support#2581]
1st problem:
in the post, RelatedBlogList showing an error. 

![image](https://user-images.githubusercontent.com/2523772/78525437-b8483480-7809-11ea-9975-828b005b9eee.png)

2nd problem:
Problem with date showing "-28030 seconds ago"
![image](https://user-images.githubusercontent.com/2523772/78526026-60aac880-780b-11ea-95e9-14a528d04c74.png)

**Comment by bidfor** [comment]
Proof of purchase 
![image](https://user-images.githubusercontent.com/2523772/78526153-ba12f780-780b-11ea-8c24-aa72dc494c81.png)

**Comment by dttrung26** [comment]
Hi @bidfor , 
I've received your ticket support requirement, please leave me your /lib/common folder to check. 
Nice day!

**Comment by bidfor** [comment]
Here it is. 
[common.zip](https://github.com/inspireui/support/files/4436012/common.zip)

**Comment by dttrung26** [comment]
Hi @bidfor ,
please download attached files and replace as following: 
- replace related_blogs.dart in your /lib/widgets/blog/detailed_blog/
- replace wordpress.dart in your /lib/services/ 
kindly confirm if it works.
Happy coding!

**Comment by bidfor** [comment]
```
"HorizonLayout": [
    {
      "layout": "logo",
      "showMenu": true
    },
    {
      "name": "Breaking News",
      "layout" : "largeCardHorizontalListItems",
      "category": 73,
      "imageBorder": 20.0
    },
    {
      "name": "Latest News",
      "layout": "sliderList"
    }
  ],
```

1> My Latest News have no category value because I want to show all post. Is there anything wrong with that?

2> As for the date, it occurs in the homepage post widgets. Mainly on post that just published recently. I think it suppose to be "A moment ago" instead?
![image](https://user-images.githubusercontent.com/2523772/78747387-e198ca00-799b-11ea-94ff-64b057628a8a.png)

This is when I press "See all" 
![image](https://user-images.githubusercontent.com/2523772/78747439-fd03d500-799b-11ea-8521-31dc59f78f8c.png)

I ran a fresh copy downloaded by envato and change only the url value. This problem only appear in version 1.3.

**Comment by dttrung26** [comment]
1. Currently, FluxNews doesn't support layout containing all blogs. Please add a category value to make it works. 
2. Please replace below file into your /lib/common. I've updated "A moment ago" display for recently updated blogs. I also use l10n to generate language, please customize the "A moment ago" text to meet your need. 
[ticket_support#2581.zip](https://github.com/inspireui/support/files/4459717/ticket_support.2581.zip)

**Comment by bidfor** [comment]
1> But its already working though. I have no problem displaying the posts from all categories using the layout. Doesnt cause any error.

**Comment by dttrung26** [comment]
I close the ticket then, have a nice day!
