### ISSUE TITLE
ListPro - 

### ISSUE THREAD

**Issue by leonmktg** [inspireui/support#2583]
<img width="1680" alt="Screen Shot 2020-04-03 at 11 05 09 PM" src="https://user-images.githubusercontent.com/62923357/78534757-940c3980-77b0-11ea-980d-439524d626a4.png">

**warn Failed to chmod xsel: EPERM: operation not permitted, chmod '/Users/mannyleon/Documents/Marketing/Clients/Visita Teziutlán/App/source/node_modules/@react-native-community/cli/build/commands/server/external/xsel'**
ERROR
02:41
**warn Package react-native-onesignal has been ignored because it contains invalid configuration. Reason: Unknown option dependency.platforms.ios.sourceDir with value ""./ios"" was found. This is either a typing error or a user mistake. Fixing it will remove this message.**
INFO
02:41
Starting Metro Bundler on port 19001.
INFO
02:41
Tunnel ready.
INFO
02:41
Booting device in iOS simulator...
INFO
02:41
Opening exp://127.0.0.1:19000 in iOS simulator
ERROR
02:41
**Unable to resolve "EventEmitter" from "App/Services/AppEventEmitter.js"**
ERROR
02:41
**Building JavaScript bundle: error**

<img width="1678" alt="Screen Shot 2020-04-06 at 2 41 41 AM" src="https://user-images.githubusercontent.com/62923357/78534738-8a82d180-77b0-11ea-8e4d-21cec26662a3.png">

<img width="1680" alt="Screen Shot 2020-04-06 at 2 42 48 AM" src="https://user-images.githubusercontent.com/62923357/78534743-8e165880-77b0-11ea-87d5-a0b8b5dbdc78.png">

{
  "name": "VisitaTeziutlan",
  "version": "1.3.5",
  "description": "vtpro",
  "author": "InspireUI",
  "private": true,
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "setup": "./scripts/setup.sh",
    "detach": "./scripts/detach.sh",
    "start": "expo start -c",
    "postinstall": "patch-package"
  },
  "dependencies": {
    "@appandflow/masonry-list": "^0.4.0",
    "@babel/plugin-proposal-decorators": "^7.4.0",
    "api-ecommerce": "0.0.29",
    "axios": "^0.18.0",
    "base-64": "^0.1.0",
    "create-react-class": "^15.6.2",
    "crypto-js": "^3.1.9-1",
    "currency-formatter": "1.5.4",
    "emoji-utils": "^1.0.1",
    "expo": "^37.0.0",
    "expo-analytics": "1.0.8",
    "firebase": "7.9.0",
    "hoist-non-react-statics": "3.3.0",
    "html-entities": "^1.2.1",
    "lodash": "^4.17.11",
    "moment": "2.24.0",
    "oauth-1.0a": "1.0.1",
    "patch-package": "^6.1.2",
    "postinstall-postinstall": "^2.0.0",
    "prop-types": "15.7.2",
    "react": "16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz",
    "react-native-animatable": "1.3.2",
    "react-native-button": "2.4.0",
    "react-native-collapsible": "^1.3.0",
    "react-native-dates": "^2.0.4",
    "react-native-dropdownalert": "3.11.0",
    "react-native-gifted-chat": "0.8.2",
    "react-native-google-places-autocomplete": "^1.3.9",
    "react-native-invertible-scroll-view": "^1.1.0",
    "react-native-keyboard-aware-scroll-view": "0.8.0",
    "react-native-map-link": "2.4.0",
    "react-native-modal-datetime-picker": "7.4.2",
    "react-native-modalbox": "1.7.1",
    "react-native-onboarding-component": "0.0.5",
    "react-native-onesignal": "3.2.13",
    "react-native-parallax-swiper": "^1.1.7",
    "react-native-progress-bar-animated": "^1.0.6",
    "react-native-render-html": "4.1.2",
    "react-native-root-toast": "^3.0.2",
    "react-native-safe-area-view": "0.14.3",
    "react-native-scrollable-tab-view": "^0.10.0",
    "react-native-slider": "0.11.0",
    "react-native-snap-carousel": "3.7.5",
    "react-native-swipe-list-view": "1.5.3",
    "react-native-swiper": "^1.5.14",
    "react-native-tab-view": "2.3.0",
    "react-native-tag-select": "^2.0.0",
    "react-native-textinput-effects": "0.5.1",
    "react-native-timeago": "^0.4.0",
    "react-native-vector-icons": "6.4.2",
    "react-navigation": "^4.0.0",
    "react-redux": "5.1.1",
    "react-timer-mixin": "^0.13.3",
    "react-tween-state": "^0.1.5",
    "redux": "4.0.1",
    "redux-persist": "^5.6.5",
    "redux-thunk": "^2.2.0",
    "sanitize-html": "1.20.1",
    "schedule": "0.4.0",
    "sentry-expo": "1.13.0",
    "tcomb-form-native": "^0.6.20",
    "urijs": "^1.19.0",
    "url": "^0.11.0",
    "util": "0.12.0",
    "wpapi": "1.2.1",
    "xdate": "^0.8.2",
    "expo-ads-facebook": "8.1.0",
    "expo-facebook": "~8.1.0",
    "expo-localization": "~8.1.0"
  },
  "devDependencies": {
    "@babel/core": "7.4.4",
    "@babel/plugin-transform-runtime": "7.4.4",
    "@babel/preset-env": "7.4.4",
    "babel-jest": "24.8.0",
    "babel-plugin-module-resolver": "3.2.0",
    "babel-polyfill": "^6.26.0",
    "babel-preset-expo": "^8.1.0",
    "babel-preset-react-native": "4.0.1",
    "path": "^0.12.7",
    "reactotron-react-native": "3.5.2",
    "reactotron-redux": "3.1.0"
  }
}

**Comment by leonmktg** [comment]
These are the latest screenshots. I was able to get the javascript build to complete (Run on IOS simulator) but then i get this error:

warn Failed to chmod xsel: EPERM: operation not permitted, chmod '/Users/mannyleon/Documents/Marketing/Clients/Visita Teziutlán/App/source/node_modules/@react-native-community/cli/build/commands/server/external/xsel'
ERROR
04:09
warn Package react-native-onesignal has been ignored because it contains invalid configuration. Reason: Unknown option dependency.platforms.ios.sourceDir with value ""./ios"" was found. This is either a typing error or a user mistake. Fixing it will remove this message.
INFO
04:09
Starting Metro Bundler on port 19001.
INFO
04:10
Booting device in iOS simulator...
INFO
04:10
Opening exp://127.0.0.1:19000 in iOS simulator
INFO
04:10
Building JavaScript bundle: finished in 3874ms.

**Bundle finishes then i get errors:**

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-06 at 04 10 38](https://user-images.githubusercontent.com/62923357/78542467-d3408780-77bc-11ea-9859-6582bc5dea4e.png)

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-06 at 04 06 33](https://user-images.githubusercontent.com/62923357/78542128-54e3e580-77bc-11ea-8236-70dffc6e3e1c.png)

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-06 at 04 05 59](https://user-images.githubusercontent.com/62923357/78542137-59100300-77bc-11ea-8408-a90a737ffd63.png)

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-06 at 04 06 24](https://user-images.githubusercontent.com/62923357/78542151-5d3c2080-77bc-11ea-88ed-e66a2aff6baa.png)

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-06 at 03 59 36](https://user-images.githubusercontent.com/62923357/78542119-50b7c800-77bc-11ea-8138-a8267287e714.png)

**Comment by luyx2412** [comment]
Hi @leonmktg Currently the library `Eventemiter` did not available in React native. You can use this library to replace old library https://github.com/primus/eventemitter3. And we will update next version to fix the issues.

Thanks

**Comment by leonmktg** [comment]
When will the update be ready? I need to start this project as soon as possible. Thank you!

**Comment by luyx2412** [comment]
Hi @leonmktg We will upgrade new version in couple days.

Thanks

**Comment by leonmktg** [comment]
@luyx2412 
You said that 4 days ago. when will it actually be available?

**Comment by luyx2412** [comment]
Hi @leonmktg We just update new version with latest expo and fix some issues related your issue. We will mention you when upload to envanto.

Thanks

**Comment by leonmktg** [comment]
@luyx2412 
I downloaded the files and did a fresh install with CeBuilder and i still get an SDK version error.

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-15 at 01 44 35](https://user-images.githubusercontent.com/62923357/79306620-2a301600-7ebb-11ea-9eec-9912f7d32296.png)

**Comment by minhcasi** [comment]
@leonmktg - pls try to remove the Expo SDK on your simulator to fix the issue - thanks
