### ISSUE TITLE
Integration with payment gateway & delivery

### ISSUE THREAD

**Issue by mazrobby** [inspireui/support#2584]
Hi, 

I have MStore Multi Vendor - Complete React Native, and I want to integrate.
I use Expo & CEBuilder.
- Payment Gateway - https://wordpress.org/plugins/woo-xendit-virtual-accounts/
- Delivery - https://wordpress.org/plugins/epeken-all-kurir/
I can't find anything in your documentation regarding this.
Do you have any tutorial so I can integrate those?

my user on Envato : mazrobby

Thanks

**Comment by minhcasi** [comment]
@mazrobby - the payment gateway could be compatible with the Mstore MV via current multi-payment Webview features

But the Delivery plugins need to be customized to integrate via Rest API, we don't have the document for this customize so far :)
