### ISSUE TITLE
[FluxStore] - Bug: Search-Filter Product Tags

### ISSUE THREAD

**Issue by IbrahimHd** [inspireui/support#2585]
1. My issue:
    v1.6.5c
    As the displayed tags in the Search tool are for products, the end point is missing the "product-" prefix so it has to be "product-tag" instead of "tag", like this:
endPoint += '&product-tag=$tag';

By the way, how can I show list of products by "product-tag", just as the categories screen. I think Tags can be shown in a section below "Categories".
I appreciate your support on this.

2. Screenshots issues (required):
   woo_commerce.dart
3. Proof of my purchased (required):
![image](https://user-images.githubusercontent.com/16100897/78554743-5c36dd80-7814-11ea-8c3c-20e255e184e9.png)

3. Config files (required)
    (not relevant)

**Comment by trunghieuvn** [comment]
Hi @IbrahimHd , 
You mean the code is wrong right.
When a search has a tag parameter, it should be called `&product-tag=`  rather than `&tag=` ?

If that's the case, I check out the API of woo here: https://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-products. 
I could not find any parameter `product-tag`. Am I misunderstanding what you mean?

Sorry if I do not understand correctly, please describe and illustrate some illustrations. I will help you solve this problem.
Thanks very much.

**Comment by IbrahimHd** [comment]
Hi @trunghieuvn,
The search tool is not working when a "tag" is selected, so I monitored the requested url and I tried to fetch it directly through the browser, I got nothing [ ].  When I change parameter tag to product-tag, I got the products.  Then I figured out that product-tag parameter works just becuase it's "ignored" by wooCommerce!
Summing up, yes there is an issue in the api parameter, the parameter name (tag) is correct but the value is not. It has to be the **tag ID in stead of tag slug**.

Hope you can respond to my 2nd part:
By the way, how can I show list of products by Tag, just as the categories screen. I think Tags can be shown in a section below "Categories".
I appreciate your support on this.

**Comment by IbrahimHd** [comment]
Could you pls response to this issue?

**Comment by minhcasi** [comment]
@IbrahimHd - pls help to create one ticket for your all issues to help us focus better on the investigating issue - kindly move to this same ticket #2555

We are trying out best with the support but for some extra customization, we need to review if the feature is useful we will consider to add it to next release - thank you for your time so far.
