### ISSUE TITLE
Error in categories page

### ISSUE THREAD

**Issue by louissaad24** [inspireui/support#2586]
I have a problem in the categories page and i don't know what is causing it. please help me.
![Screenshot_1586177442](https://user-images.githubusercontent.com/55917976/78560222-678f0680-781e-11ea-9825-66d283fbe159.png)

**Comment by minhcasi** [comment]
Hi, thank you for the feedback. Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads it's used to verify your proof of purchase? 
Sorry for any inconvenience, we will reopen the ticket when it is verified, thank you!

**Comment by louissaadx** [comment]
![Screenshot_20200407-051802](https://user-images.githubusercontent.com/63242220/78622953-2f73dc00-788f-11ea-8d34-83d8b07a1253.jpg)
here is the photo to verify

**Comment by minhcasi** [comment]
@trunghieuvn - pls help for suggestion

**Comment by trunghieuvn** [comment]
Please share me folder config and common in source. I need reproduce issue.
Thanks

**Comment by louissaad24** [comment]
[Desktop.zip](https://github.com/inspireui/support/files/4442718/Desktop.zip)
Here they are

**Comment by louissaadx** [comment]
@trunghieuvn i have sent the folders you asked for, please help me :)

**Comment by trunghieuvn** [comment]
Hi @louissaad24 , @louissaadx 
There are two problems with this error.

The first problem is that the call to the API category fails, I check and see that the application calls the api category using the following link.
It is an error on your server.
- Remove `/` in file config 
![image](https://user-images.githubusercontent.com/19247680/78679013-e2861900-7913-11ea-8701-fbfdba21344c.png)
- Check the server:
    + URL API category:  http://buraimigrocery.com/index.php?route=extension/mstore/category&limit=100&lang=ar
    + image error: 
![image](https://user-images.githubusercontent.com/19247680/78679245-2e38c280-7914-11ea-8e48-6e1d13da3b6a.png)


The second problem is a null render error in the interface, you can fix it quickly by adding `Container` like the following code.
File: `lib/screens/categories/index.dart`
Function:  build 
![image](https://user-images.githubusercontent.com/19247680/78679610-a69f8380-7914-11ea-99e5-41a8e2d9174c.png)

**Comment by louissaadx** [comment]
@trunghieuvn thank you! but the screen is not showing any categories, it is not showing the error anymore but no category is displayed why?

**Comment by trunghieuvn** [comment]
It looks like the product catalog API has a problem, I mentioned above. Please check the server API again.
An example of this is when you call the product catalog API url you will see an error:

> Check the server:
> * URL API category:  http://buraimigrocery.com/index.php?route=extension/mstore/category&limit=100&lang=ar
> * image error:
>  ![image](https://user-images.githubusercontent.com/19247680/78679245-2e38c280-7914-11ea-8e48-6e1d13da3b6a.png)

**Comment by minhcasi** [comment]
@louissaad24 - could you help to update the mstore-api plugin to latest version, thanks

**Comment by minhcasi** [comment]
@louissaad24 - sorry, we just realize you are using opencart, please help to replace this open cart extension 

[mstore.ocmod.zip](https://github.com/inspireui/support/files/4459707/mstore.ocmod.zip)

**Comment by minhcasi** [comment]
@louissaad24 - just notice there is the "Null coalescing operator" from PHP that using from previous Open cart extension, just try to use my attachment to fix the issue - thank you!

**Comment by louissaadx** [comment]
@minhcasi thank you everything is working well.

**Comment by minhcasi** [comment]
Thank you! you are very welcome 😊
