### ISSUE TITLE
cannot run FluxStore Pro v1.6.6b on ios devices and simulator

### ISSUE THREAD

**Issue by kimsung2018gnu** [inspireui/support#2588]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: 
I have download FluxStore Pro 1.6.6b from Gitlab. I can run it successfully on Android but I cannot run it in ios device and simulator. I have already tried your solution by cleaning project but it seems does not work. Could you please help me?

2. Screenshots issues (required):

![image](https://user-images.githubusercontent.com/63182499/78587973-02600300-7868-11ea-9b5e-0b749bcc5b24.png)

![image](https://user-images.githubusercontent.com/63182499/78588712-4d2e4a80-7869-11ea-8ea6-715a15bbbeae.png)
3. Proof of my purchased (required):
![image](https://user-images.githubusercontent.com/63182499/78588084-320f0b00-7868-11ea-92ae-d604c7a92fcf.png)

3. Config files (required)

**Comment by minhcasi** [comment]
@kimsung2018gnu - it seems the Pods install issue - could you confirm to remove these folder

Remove following files and folders (see this screenshot - https://tppr.me/vwqX0 )
```
- Go to ios: remove Pods folder, Podfile and fodfile.lock, .symlink folder (this folder is hidden)
- remove build folder
```
Open XCode, File > Workspace Settings > Select 'New Build System' - https://tppr.me/CRHLC

Then restart the build from Android Studio again

**Comment by minhcasi** [comment]
@kimsung2018gnu - we already sent the invitation - pls help to check the email

**Comment by kimsung2018gnu** [comment]
I have already tried this solution but it seems not work. Could you please help me?

**Comment by minhcasi** [comment]
@kimsung2018gnu - could you try with the package from - http://codecayon.net/downloads

We will post the video regarding 1.6.6b - could be helpful - it will be ready today on http://youtube.com/inspireui

**Comment by minhcasi** [comment]
@kimsung2018gnu - please help to check this video guide - https://www.youtube.com/watch?v=ReAUZDIgh2I

**Comment by kimsung2018gnu** [comment]
I can run successfully on Simulator but I can't run on real device. 
![image](https://user-images.githubusercontent.com/63182499/78904686-21000d00-7aa7-11ea-843a-414a09b7f8ad.png)

**Comment by IAPCorporate** [comment]
This issue occurs for me when I change the splashscreen image.

**Comment by minhcasi** [comment]
@IAPCorporate - to run on the real device you need to update this code sign setting from XCode

<img width="1090" alt="Screen Shot 2020-04-10 at 9 17 52 AM" src="https://user-images.githubusercontent.com/1459805/78956391-5428b780-7b0c-11ea-8eb7-97b23aad41d9.png">

**Comment by IAPCorporate** [comment]
It doesn't even work on Simulator. It works fine but as soon as I change the splash screen, it breaks.

**Comment by minhcasi** [comment]
moved to #2638
