### ISSUE TITLE
[FluxStore-Pro] Issue trying to finish the purchase

### ISSUE THREAD

**Issue by nahuelbourdichon** [inspireui/support#2589]
Hello I using FluxStore Pro. 
I'm having an issue when trying to finish the purchase then  next error appear!! 
![image](https://user-images.githubusercontent.com/16769047/78609478-27894d00-7839-11ea-9c24-eab5c921956a.png)

"Errors log deleted due to exposing Consumer/Secret keys"

please can you help me with this error ?

Thanks!!!

**Comment by minhcasi** [comment]
@nahuelbourdichon - could you help to translate the error message? What does it mean 😅

**Comment by nahuelbourdichon** [comment]
yes sorry , I'm going to set it in English and I'll send it again..

**Comment by philipvu30** [comment]
Hi @nahuelbourdichon ,

It is not wise to expose your consumer_key and secret_key on Internet.

Please send your common folder to this email: toan@inspireui.com. I'll help you solve this issue.
