### ISSUE TITLE
Can not get Categories and Tags

### ISSUE THREAD

**Issue by Relimer-Technologies** [inspireui/support#259]
**Mandatory Info (please complete the following information):**
 - Product: [e.g. MStore, ListApp]
M Store Pro
Purchase Code: d98eb201-aba4-4c76-a0a1-cbd67415737d
 - Your Purchased Code: [get from https://codecanyon.net/downloads]
(we may not reply if you are not our customer)

**Describe the issues**
Hello,

Good Evening, I have purchased M Store Pro from Envato. I have done all the basic setup required... I have installed all the required tools... I have assigned the Consumer Key and ConsumerSecret Key in the CeBuilder as well as in the config.js file as shown in the documentation. I have added products to my website with categories and tags assigned to each of them. Even after doing all the setup I get this warning when I try to move in the customize tab of CeBuilder.Please help me to proceed further.

Thank You.

**Screenshots**
![screenshot_1](https://user-images.githubusercontent.com/47352123/52279434-90e4a600-297f-11e9-825f-9a5837e7d6b3.png)

**Comment by minhtruong315** [comment]
Hi @Relimer-Technologies Can you send me AppConfig.json file? I will help you check issue

**Comment by valeopay** [comment]
i have the same problem.

**Comment by Relimer-Technologies** [comment]
[AppConfig.txt](https://github.com/inspireui/support/files/2840258/AppConfig.txt)

**Comment by valeopay** [comment]
you find an solution?

**Comment by minhtruong315** [comment]
Hi @Relimer-Technologies I can not access this site: https://rasp.beginoninternet.com
is it working?

**Comment by Relimer-Technologies** [comment]
It was a subdomain I created for the testing purpose I am sending you the new AppConfig file... I have sent you a message in Skype with Relimer Technologies as a Username... If you can contact me in skype and TeamViewer the project it would be good... I am waiting for your reply... KIndly please provide me with the solution.
[AppConfig.txt](https://github.com/inspireui/support/files/2854382/AppConfig.txt)

**Comment by minhtruong315** [comment]
Remember to enable WooCommerce Api
https://docs.woocommerce.com/document/woocommerce-rest-api/
