### ISSUE TITLE
[EvaStore] - Adding Customized Attributes for a Customer

### ISSUE THREAD

**Issue by denny-dang** [inspireui/support#2590]
---------

1. My issue: 
Hi! Thank you so much for answering my previous question.
I want to add a new field during registration (e.g. birthday, university, etc.) Do you have any recommendations on how to proceed with this? 
In which files would you create and save these fields/attributes? 
How does storage of these attributes work? Would it link to the Shopify account?
Is it possible to make it show up within my Shopify account, under the “Customers” tab? How would admins access or modify these attributes?
If we were to implement a reward point system, which files should we look into and modify?

Perhaps there is a way to modify a user's info or implement it similar to the Wishlist?

2. Screenshots issues (required):
![image](https://user-images.githubusercontent.com/52182574/78610781-707dd900-781a-11ea-9091-b4bfc8b514f9.png)

3. Proof of my purchased (required):
![image](https://user-images.githubusercontent.com/52182574/78610794-7673ba00-781a-11ea-9a19-4f28938a2ea8.png)

3. Config files (required)
config home page show
horizontal with multi collection id or
vertical layout with latest product and first product is banner
*/
HomePage: {
Horizon: true,
PageSize: 12,
},
HorizonLayout: [
// {
// categoryId: "Z2lkOi8vc2hvcGlmeS9Db2xsZWN0aW9uLzQyMTg1ODM4MQ==",
// paging: true,
// layout: Constants.Layout.miniBanner,
// },
{
name: "Jitter-less Coffee",
categoryId: "Z2lkOi8vc2hvcGlmeS9Db2xsZWN0aW9uLzE1NDgyMTQ5Mjc4OQ==",
layout: Constants.Layout.card,
},
{
name: "Apparel & Accessories",
categoryId: "Z2lkOi8vc2hvcGlmeS9Db2xsZWN0aW9uLzE1NDgyMTM5NDQ4NQ==",
layout: Constants.Layout.twoColumn,
},
],

**Comment by minhcasi** [comment]
@luyx2412 - please help to suggest the solution

**Comment by luyx2412** [comment]
Hi @denny-dang Currently we did not support another field and the shopify also support another fields. Please see the screenshot. You can use the graphql and select the document to see another api support.
![image](https://user-images.githubusercontent.com/8909619/78679870-f67e4a80-7914-11ea-8691-7eddee9d70bb.png)
![image](https://user-images.githubusercontent.com/8909619/78679933-0f86fb80-7915-11ea-896d-d1c74a4c8249.png)

Thanks

**Comment by denny-dang** [comment]
I see, that makes sense. Thank you!
