### ISSUE TITLE
[BeoNews 3.0.6] - Can't compile after first bought

### ISSUE THREAD

**Issue by robertwt7** [inspireui/support#2592]
1. My issue:

After I type yarn inside the folder beonews-expo, I have a couple of error that can't compile this and that (I forgot to screenshot because after it goes to yarn start, it just clears the commandline). This happened when I'm using node v13 lts, so i figure that probably the dependencies of the app is node v12? After I changed it to Node v12 it works straightaway, I don't see any dependencies instructed anywhere.

After I changed my node version to version 12 LTS, then I can run yarn, but after I start the app with `yarn start` and see it in the web view i encountered another error:

```
 web  Failed to compile.
/Users/roberttirtasentana/Documents/OneDrive/Macbook/Documents/Dev/BeoNews.3.0.6/beonews-expo/node_modules/react-native/Libraries/Network/XMLHttpRequest.js
Module not found: Can't resolve './RCTNetworking' in '/Users/roberttirtasentana/Documents/OneDrive/Macbook/Documents/Dev/BeoNews.3.0.6/beonews-expo/node_modules/react-native/Libraries/Network'
```

2. Screenshots issues (required):

<img width="850" alt="Screen Shot 2020-04-07 at 1 24 19 pm" src="https://user-images.githubusercontent.com/15647967/78626976-a7fc8c00-78d3-11ea-98d2-a378e101fc6c.png">

3. Config files (required)

AppConfig is not edited yet, i haven't edit it

**Comment by robertwt7** [comment]
Possible issue with reacttotron-react-native?

https://forums.expo.io/t/failed-to-compile-cant-resolve-rctnetworking/26273/6

Did anyone has the same issue?

**Comment by robertwt7** [comment]
Now when I tried to open it in my expo app in my iPhone, I got another error

![IMG_614E8C8427EC-1](https://user-images.githubusercontent.com/15647967/78628368-4b9b6b80-78d7-11ea-8999-2273e24b54c3.jpeg)

Can you please help? I'm so confused with this. Should I start with the react-native cli instead? Is there any minimum or max version of node or npm that I shouldn't use?

**Comment by minhcasi** [comment]
Hi, thank you for the feedback. Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads it's used to verify your proof of purchase? 
Sorry for any inconvenience, we will reopen the ticket when it is verified, thank you!

**Comment by robertwt7** [comment]
<img width="1370" alt="Screen Shot 2020-04-07 at 2 12 28 pm" src="https://user-images.githubusercontent.com/15647967/78629265-d9785600-78d9-11ea-8728-c4ac0f6574fe.png">


There you go, I've downloaded the license so you can check. Just bought it today so should be last purchase

**Comment by robertwt7** [comment]
Hey there, I manage to compile my apps when i'm running it in iOS app instead of the webview. However when I try to use wordpress page, it gives me:

```
Warning: Failed prop type: Invalid props.style key `fontSize` supplied to `WebView`.
Bad object: {
  "height": 900,
  "fontSize": 30
}
Valid keys: [
  "display",
  "width",
  "height",
  "start",
```

What happened with this? Webview only returns blank page as well. I already put the correct ID in CustomPages in the Config.js for the contact page. Do i have to do something further?

**Comment by robertwt7** [comment]
<img width="500" alt="Screen Shot 2020-04-08 at 12 46 41 pm" src="https://user-images.githubusercontent.com/15647967/78739168-0b9bbd80-7997-11ea-8a02-7351e0ca0eef.png">

My webview is getting the correct page ID, test it with postman as well. But it does not render and it returns blank screen, any idea why?

**Comment by minhcasi** [comment]
@robertwt7 - it seems the latest WebView issue on iOS, we will do some investigating - thank you for the detail explaination

**Comment by luyx2412** [comment]
Hi @robertwt7 You can use the url instead of id with webview page. It will work normal with url.

Thanks

**Comment by robertwt7** [comment]
Yeah i manage to get it done, actually you guys, by only using `<WebView html={this.state.html} />` makes it work for me. not sure why do you need the other property on your template. I checked the documentation from Webview component that they have update their props options
