### ISSUE TITLE
[Fluxstore Pro - Flutter E-commerce Full App ] - Magento Checkout URL not found and In My Cart Page error for cart.

### ISSUE THREAD

**Issue by Pankaj-Sakariya** [inspireui/support#2594]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:   Magento 2 Checkout URL not found and In My Cart Page error for cart.

2. Screenshots issues (required): 
![1586237443503](https://user-images.githubusercontent.com/6638426/78647962-ea749780-78d8-11ea-9a24-20c8ff85b70a.JPEG)
![picturemessage_p4ujte2x l21](https://user-images.githubusercontent.com/6638426/78647968-ecd6f180-78d8-11ea-8967-b5da7d843006.png)

3. Proof of my purchased (required):

![image](https://user-images.githubusercontent.com/6638426/78647882-cd3fc900-78d8-11ea-8479-caf71ee1fedd.png)

3. Config files (required)

`const serverConfig = {
  "type": "magento",
  "url": "https://souq-e.com",
  "accessToken": "ib0uqa42kpjdm077luwzov752fu7hy1a",
  "forgetPassword": "https://souq-e.com/customer/account/forgotpassword/"
};`

**Comment by Pankaj-Sakariya** [comment]
@minhcasi  I hope you got both issues.

1. GetCheckoutURL is blank - there must be some code for magento checkout url.
2. MyCart is facing issue - when you put some product in cart and then close the application ane again come to that cart page - you will found this error. 

Let me know if you need any clarification.

**Comment by minhtruong315** [comment]
@Pankaj-Sakariya replace addProductToCart function in models/cart.dart to fix cart error
```
// Adds a product to the cart.
  String addProductToCart(
      {Product product,
      int quantity = 1,
      ProductVariation variation,
      isSaveLocal = true}) {
    String message = '';

    var key = "${product.id}";
    if (variation != null) {
      if (variation.id != null) {
        key += "-${variation.id}";
      }
      for (var attribute in variation.attributes) {
        if (attribute.id == null) {
          key += "-" + attribute.name + attribute.option;
        }
      }
    }

    //Check product's quantity before adding to cart
    int total = !_productsInCart.containsKey(key)
        ? quantity
        : _productsInCart[key] + quantity;
    int stockQuantity =
        variation == null ? product.stockQuantity : variation.stockQuantity;
    print('stock is here');
    print(product.manageStock);

    if (product.manageStock == null || !product.manageStock) {
      _productsInCart[key] = total;
    } else if (total <= stockQuantity) {
      if (product.minQuantity == null && product.maxQuantity == null) {
        _productsInCart[key] = total;
      } else if (product.minQuantity != null && product.maxQuantity == null) {
        total < product.minQuantity
            ? message = 'Minimum quantity is ${product.minQuantity}'
            : _productsInCart[key] = total;
      } else if (product.minQuantity == null && product.maxQuantity != null) {
        total > product.maxQuantity
            ? message =
                'You can only purchase ${product.maxQuantity} for this product'
            : _productsInCart[key] = total;
      } else if (product.minQuantity != null && product.maxQuantity != null) {
        if (total >= product.minQuantity && total <= product.maxQuantity) {
          _productsInCart[key] = total;
        } else {
          if (total < product.minQuantity) {
            message = 'Minimum quantity is ${product.minQuantity}';
          }
          if (total > product.maxQuantity) {
            message =
                'You can only purchase ${product.maxQuantity} for this product';
          }
        }
      }
    } else {
      message = 'Currently we only have $stockQuantity of this product';
    }

    if (message.isEmpty) {
      item[product.id] = product;
      if (isSaveLocal) {
        _productVariationInCart[key] = variation;
        _productSkuInCart[key] = product.sku;
        saveCartToLocal(
            product: product, quantity: quantity, variation: variation);
      }
    }

    notifyListeners();
    return message;
  }
```

**Comment by minhtruong315** [comment]
@Pankaj-Sakariya GetCheckoutURL only use for woo commerce, it doesn't support for magento and opencart. so you can't use one page checkout on magento

**Comment by Pankaj-Sakariya** [comment]
So in order to use webview - in Magento What should I do? Because website has lot of extension on checkout page, which are not supported by your default fluxstore code, so what is the way to open webview from mycart page to overcome this issue?

**Comment by minhtruong315** [comment]
@Pankaj-Sakariya Fluxstore doesn't support payment webview for magento now. so I dont have any solutions to help you make it. You can  research to add it. Thanks

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
