### ISSUE TITLE
Need urgent help on installation

### ISSUE THREAD

**Issue by assalatuzzaman** [inspireui/support#2595]
I have purchase Fluxstore Multi Vendor. I am very new. I need help for Installation. and do I need to have another theme for the website?

**Comment by minhcasi** [comment]
Hi, thank you for the feedback. Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads it's used to verify your proof of purchase? 
Sorry for any inconvenience, we will reopen the ticket when it is verified, thank you!
