### ISSUE TITLE
[my-product] - FluxStore FLUTTER

### ISSUE THREAD

**Issue by mpnihad** [inspireui/support#2596]
info@sciwiz.net

---------

1. My issue:
i have an error while check out cart in Fluxstore app Exception: you need to choose option for your option
2. Screenshots issues (required):
![Screenshot_1586252422](https://user-images.githubusercontent.com/59775230/78654525-4263cc00-78e2-11ea-8dd5-b799620fbcf6.png)
3. Proof of my purchased (required):

![image](https://user-images.githubusercontent.com/59775230/78654857-cfa72080-78e2-11ea-81ee-f22297659dc1.png)

3. Config files (required)

[config.txt](https://github.com/inspireui/support/files/4443327/config.txt)

**Comment by minhtruong315** [comment]
Hi @mpnihad check this solution to fix https://github.com/inspireui/support/issues/2594#issuecomment-610816934
