### ISSUE TITLE
[my-product] - Unhandled Exception: MissingPluginException

### ISSUE THREAD

**Issue by kumsalajans** [inspireui/support#2597]
1. My issue:

no library external is running on android

2. Screenshots issues (required):

[https://ibb.co/MhQWJ0W](https://ibb.co/MhQWJ0W)
[https://ibb.co/w4ZFdmS](https://ibb.co/w4ZFdmS)

3. Proof of my purchased (required):
[https://ibb.co/bKHZkff](https://ibb.co/bKHZkff)

**Comment by netfirms** [comment]
I also faced this issue.

**Comment by minhcasi** [comment]
@kumsalajans - please use the latest 1.6.6b to fix this issue or replace with new MainActiviry.kt file - https://tppr.me/vMzOc

**Comment by MiguelHAngelH** [comment]
Hello dear, the company has bought the template, I am the developer.

I have this error  executed the command -FLUTTER CLEAN -FLUTTER DOCTOR and I have not managed to solve the problem, the same thing always comes out. I need help.

![Screenshot_16](https://user-images.githubusercontent.com/3894371/78739984-7ad7ca00-7923-11ea-82e2-133e832e03a0.png)
![Screenshot_15](https://user-images.githubusercontent.com/3894371/78739989-80351480-7923-11ea-89ff-1505bcdccc5b.png)

**Comment by minhcasi** [comment]
@MiguelHAngelH - try to subscribe on this channel - http://youtube.com/inspireui - i will upload video installing guide from basic flutter to fluxstore installing today - thank you!

This is a good guide to clean up the cache - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

@kumsalajans - let us know if you could install the project so far - thank you!

**Comment by MiguelHAngelH** [comment]
> @MiguelHAngelH - intenta suscribirte en este canal - http://youtube.com/inspireui - subiré la guía de instalación de videos desde flutter básico hasta la instalación de fluxstore hoy - ¡gracias!
> 
> Esta es una buena guía para limpiar el caché: https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1
> 
> @kumsalajans - háganos saber si puede instalar el proyecto hasta ahora - ¡gracias!
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/f406561f2bbdfd164cbf7ac7ee7a95adc7e14990/68747470733a2f2f7974332e67677068742e636f6d2f612f41415458414a7830426352753550447657705a326d71624a477068796165466c6d6f436d4f32577634773d733930302d632d6b2d63307866666666666666662d6e6f2d726a2d6d6f"><img alt="" height="14" src="/yts/img/favicon_144-vfliLAfaB.png"> Youtube**[Inspirar interfaz de usuario](https://www.youtube.com/channel/UCQd30xCKstlM6PL6qtSOjFw)**
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/0aeb324a3445c618a67c0140da8216d28af304fa/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f696d616765732f6d6f64756c65732f67697374732f676973742d6f672d696d6167652e706e67"><img alt="" height="14" src="https://camo.githubusercontent.com/040b5519c6d1891329f5f6d3e511003657131cf2/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> Esencia**[Estos son problemas comunes en Flutter y soluciones para solucionar](https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1)**Estos son problemas comunes en Flutter y soluciones para solucionar - Flutter Clean.md

thank you very much i subscribe immediately.

**Comment by MiguelHAngelH** [comment]
> @MiguelHAngelH - try to subscribe on this channel - http://youtube.com/inspireui - i will upload video installing guide from basic flutter to fluxstore installing today - thank you!
> 
> This is a good guide to clean up the cache - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1
> 
> @kumsalajans - let us know if you could install the project so far - thank you!
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/f406561f2bbdfd164cbf7ac7ee7a95adc7e14990/68747470733a2f2f7974332e67677068742e636f6d2f612f41415458414a7830426352753550447657705a326d71624a477068796165466c6d6f436d4f32577634773d733930302d632d6b2d63307866666666666666662d6e6f2d726a2d6d6f"><img alt="" height="14" src="/yts/img/favicon_144-vfliLAfaB.png"> YouTube**[Inspire UI](https://www.youtube.com/channel/UCQd30xCKstlM6PL6qtSOjFw)**
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/0aeb324a3445c618a67c0140da8216d28af304fa/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f696d616765732f6d6f64756c65732f67697374732f676973742d6f672d696d6167652e706e67"><img alt="" height="14" src="https://camo.githubusercontent.com/040b5519c6d1891329f5f6d3e511003657131cf2/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> Gist**[These are common issues on Flutter and solutions to fix](https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1)**These are common issues on Flutter and solutions to fix - Flutter Clean.md

THANK YOU very much I just solved the problem with the cache issues .... SAVED ME THE DAY, GREETINGS.
