### ISSUE TITLE
[Fluxstore-Magento] - issue in app

### ISSUE THREAD

**Issue by taryaalo** [inspireui/support#2599]
1. My issue:
Hi i complete the app and i already upload to play sore and iOS as a beta to test it on several devices.
i want to thank you for this grate app.
i have some issue i think it related to magento .
all issue you can check it on beta version on this google play link just register as beta tester
https://play.google.com/store/apps/details?id=com.nmclibya.tedbesha 
issue 1.
product price is not boded for all product ,( simple product are ok, configurable product the price some time lode after you open the product and some time are not boded at all) even this issue in your default configuration.

issue 2.
category image tap the image not loaded  , even this issue in your default configuration.

issue3.
when i get into any category not all product are showing but is repeated the last 4 product

issue 4.
when i go to order history the same issue 3 happen

issue 5.
when i save the address i can't select it an other time and the address that are saved in magento not loaded..

2. Screenshots issues (required):
this is video show you the issue 
https://drive.google.com/file/d/1zA8fI6csE6MKBOXst_TUOisxQothTBxr/view?usp=sharing

![Screenshot_20200407-135800](https://user-images.githubusercontent.com/26363734/78668527-201a8000-78db-11ea-8df2-aa0cc0c840ce.jpg)

![Screenshot_20200407-135744](https://user-images.githubusercontent.com/26363734/78668541-24469d80-78db-11ea-9c98-b7c1808f6119.jpg)
![Screenshot_20200407-135730](https://user-images.githubusercontent.com/26363734/78668551-26106100-78db-11ea-9ce2-52290bebf479.jpg)
![Screenshot_20200407-135722](https://user-images.githubusercontent.com/26363734/78668553-27418e00-78db-11ea-9a58-45799be760b4.jpg)
![Screenshot_20200407-135713](https://user-images.githubusercontent.com/26363734/78668560-29a3e800-78db-11ea-9074-412ce5a45be3.jpg)

3. Proof of my purchased (required):
![Screen Shot 2020-03-27 at 3 00 43 PM](https://user-images.githubusercontent.com/26363734/78668746-7edff980-78db-11ea-9a6f-bdbcbadc9a7b.png)

3. Config files (required)

**Comment by minhcasi** [comment]
@taryaalo - congratulation success release on store 👍

We will help to check the issue and let you know - very best!

**Comment by minhtruong315** [comment]
@taryaalo 1. As this is limit from the Magento API that could not show the pricing from the configable product from the product list - it could only show when you go to the product detail

**Comment by minhtruong315** [comment]
2. check this solution https://github.com/inspireui/support/issues/2539#issuecomment-610702221

**Comment by minhtruong315** [comment]
4. check this solution https://github.com/inspireui/support/issues/2594#issuecomment-610816934

**Comment by minhtruong315** [comment]
3. Please help me record screen for this issue.

**Comment by minhtruong315** [comment]
5. Fluxstore only supports to save address on local, it doesn't save on the website.

**Comment by taryaalo** [comment]
Thanks for your quick responses. 
About issue 3.
When go to any category screen the product for this category just repeat it when I scroll down 
Check this video 
https://drive.google.com/file/d/1Em8Qk3WXIQxPjZZVatqQF800oQWetFeW/view?usp=drivesdk

**Comment by taryaalo** [comment]
and about issue 1 there is some product price not showing even when you go to the product detail 
![Screenshot_20200407-135722](https://user-images.githubusercontent.com/26363734/78771077-dd66af80-798f-11ea-9195-753bd5ee3227.jpg)

**Comment by taryaalo** [comment]
about issue 4 .
the issue is loop in orders (order history screen) when you pull down it showing the same orders again and agin .

**Comment by taryaalo** [comment]
issue 6.
quantity of product is incorrect , out of stock product are showing and product that have 1 item in stock can add any quantity in to cart when you try to checkout cannot process because of it and there is no massage that tell about product quantity .

**Comment by sodhanii** [comment]
One question, does Flux Store Pro download the address stored on Magento backend?

**Comment by minhtruong315** [comment]
> One question, does Flux Store Pro download the address stored on Magento backend?

No

**Comment by sodhanii** [comment]
It's an API thing. Will you be adding this in future releases?

**Comment by minhtruong315** [comment]
@taryaalo Can u give me your email, I will send you updates for your issues. thanks

**Comment by sodhanii** [comment]
Yes, adityasodhani92@gmail.com

**Comment by taryaalo** [comment]
@minhtruong315 m.alorofie@gmail.com

**Comment by minhtruong315** [comment]
@taryaalo sent

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
