### ISSUE TITLE
[Mstore] Installation & Build Issue on Mac [mstore pro version 3.6.3]

### ISSUE THREAD

**Issue by hammadhassan** [inspireui/support#26]
**Mandatory Info (please complete the following information):**
**Product: [MStore]
Purchase Code: f20afe4a-778e-4089-bcb2-7ec1bb4ed49b**

**Describe the issues**
**Unable to run app on MAC.**

**Additional context**
I did used the solution give in following link.
https://docs.mstore.io/faq-and-troubleshooting#fix-cfbundleidentifier-does-not-exist

mstore build is still failed but when is used 2nd solution `select React from drop down & build project. the build is successful`  but when is run `react-native run-ios` following error occurs.

`CFBundleIdentifier. Print: Entry, ":CFBundleIdentifier", Does Not Exist`

**Comment by luyx2412** [comment]
HI @hammadhassan Can you send me the screenshot about the issue. Because we tested and working normal. Thanks

**Comment by hammadhassan** [comment]
Here are the screen shots.

Build Error
![build 2](https://user-images.githubusercontent.com/5791268/48762775-952ceb80-eccd-11e8-9123-004c3a4036d4.jpg)

Terminal error
![error](https://user-images.githubusercontent.com/5791268/48762793-9f4eea00-eccd-11e8-9b95-fab826462c83.jpg)

**Comment by luyx2412** [comment]
HI @hammadhassan Please alway using XCode to build your app which help resolving the  issue `CFBundleIdentifier `. And i saw your XCode appear issue about Admob, Please check again make sure install and link the library. Thanks

**Comment by luyx2412** [comment]
Yes, please change scheme and build mstore.

**Comment by hammadhassan** [comment]
I have changes schema but still build is failed.

![image](https://user-images.githubusercontent.com/5791268/48776723-65440f00-ecf2-11e8-8ea8-29efa78d7d0b.png)

**Comment by hammadhassan** [comment]
Got following error again & again.

![image](https://user-images.githubusercontent.com/5791268/48777145-a12ba400-ecf3-11e8-89a3-bc086ecf1bb1.png)

**Comment by hammadhassan** [comment]
Got following error again & again.

![Uploading image.png…]()

**Comment by luyx2412** [comment]
Hi @hammadhassan Can you provide me your Config.js file and your package.json file. Thanks

**Comment by hammadhassan** [comment]
New version 3.6.4 is fixed the issue.

Thanks
