### ISSUE TITLE
[BeoNews] Can someone help me install BeoNews

### ISSUE THREAD

**Issue by trappat** [inspireui/support#260]
**Mandatory Info (please complete the following information):**
 - Product: BeoNews
 - Your Purchased Code: bb904f63-d575-4586-9afd-b7d283e357ff

**Describe the issues**
Trying to install this for my site Melaninterest.com doesnt work. Pics dont pop up. I need help.

**Comment by minhcasi** [comment]
Hi, just update that we received your ticket and the team will back to check on Monday (after the Tet holiday), sorry for the delay - thank you! 

Could you help to share your detail screenshot please

**Comment by trappat** [comment]
How much longer?

**Comment by minhcasi** [comment]
Hi, could you send detailed screenshot to explain what is the issues please, there is no clue to fix the issues

**Comment by trappat** [comment]
Photos of blog posts are not showing up. Can you do a skype/teamviewer? screenshare

**Comment by minhcasi** [comment]
Hi, please send your detail config to my email: minh@inspireui.com - we will help for checking and set up all ready for the teamviewer - thank you!

**Comment by trappat** [comment]
I just sent the email
