### ISSUE TITLE
[Fluxstore Pro] - Importing Issue

### ISSUE THREAD

**Issue by xLidoni** [inspireui/support#2601]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:

Hi, I followed the guide at the link https://www.youtube.com/watch?time_continue=454&v=abMi8JYurpM&feature=emb_logo,

but when I do all the steps Get dependencies does not appear!

![image](https://user-images.githubusercontent.com/11965301/78677235-c7051900-78e7-11ea-8ffd-203caacef882.png)

2. Screenshots issues (required):

![image](https://user-images.githubusercontent.com/11965301/78677781-70e4a580-78e8-11ea-8d6c-321bc221bd45.png)

3. Proof of my purchased (required):

![image](https://user-images.githubusercontent.com/11965301/78677141-a937b400-78e7-11ea-9cdf-984b03536a34.png)

3. Config files (required)

**Comment by minhcasi** [comment]
@xLidoni - please try to remove the hidden .idea folder https://tppr.me/hziYd and .git folder from the project will fix the issue - thank you!

**Comment by minhcasi** [comment]
Also, try to run 'flutter clean' by using this guide - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

**Comment by xLidoni** [comment]
Hello! I followed what you said, but to no avail.
I am desperate
![image](https://user-images.githubusercontent.com/11965301/78757242-7b507f00-797c-11ea-8f2b-2f216e02e827.png)



![image](https://user-images.githubusercontent.com/11965301/78757297-8f947c00-797c-11ea-8c51-e1714ba7ede5.png)


![image](https://user-images.githubusercontent.com/11965301/78757307-96bb8a00-797c-11ea-8073-f18f061aa8d5.png)

**Comment by xLidoni** [comment]
@minhcasi there is no .git folder in source.

**Comment by xLidoni** [comment]
![image](https://user-images.githubusercontent.com/11965301/78757606-0d588780-797d-11ea-85c8-d472ce97347c.png)

**Comment by minhcasi** [comment]
@xLidoni 

- From Android Studio please select the Flutter SDK from the setting - https://tppr.me/gmhf7
- Also, try to run "flutter doctor" to check if there is any issue
- From the script run: 
```
flutter clean
flutter pub get
```

I will share the installing basic for latest fluxstore on this link https://www.youtube.com/watch?v=ReAUZDIgh2I

the next video will be for window - thank you!

**Comment by xLidoni** [comment]
Same problem! 
![image](https://user-images.githubusercontent.com/11965301/78758705-d7b49e00-797e-11ea-9b71-b7d63c9950ac.png)

@minhcasi @kvt0012

**Comment by xLidoni** [comment]
Hello! Now work's! 

But i have a problem..

![image](https://user-images.githubusercontent.com/11965301/78767729-40a21300-798b-11ea-92d8-acfa6e8b85ac.png)


I temp deleted .ttf founts, because app won't start.


When i click app crash..
![image](https://user-images.githubusercontent.com/11965301/78767593-18b2af80-798b-11ea-9fb2-e22e09d2cdb2.png)




![image](https://user-images.githubusercontent.com/11965301/78767792-58799700-798b-11ea-950a-d891fa00d4a6.png)


@minhcasi @kvt0012

**Comment by xLidoni** [comment]
![image](https://user-images.githubusercontent.com/11965301/78775411-75679780-7996-11ea-9f19-96a6a27d12be.png)

**Comment by xLidoni** [comment]
![image](https://user-images.githubusercontent.com/11965301/78775449-86180d80-7996-11ea-9662-f28486af51b3.png)

**Comment by xLidoni** [comment]
![image](https://user-images.githubusercontent.com/11965301/78777804-7e5a6800-799a-11ea-81b6-7dc9b7230e22.png)

**Comment by xLidoni** [comment]
![image](https://user-images.githubusercontent.com/11965301/78780332-b5327d00-799e-11ea-93d3-7b5b32eaccbc.png)
.........

**Comment by xLidoni** [comment]
I apologize for the many screens, but unfortunately I can't get out of it, on Monday I bought the package, but I still can't use it ..

**Comment by xLidoni** [comment]
Please check my video :   https://www.youtube.com/watch?v=m9mVlR6AXOI&feature=youtu.be


I kindly ask you to help me.


I'm stuck I can't start the application, could you kindly help me? I am stopped and can not do anything else because of this problem.

Kindly..

Thanks.

**Comment by kvt0012** [comment]
Dear sir, this error is normal because the faild of Grandl, so the easiest way is you keep running it again and it will run normally for build failed, if it build failed, it will display the real error, thank you

**Comment by xLidoni** [comment]
How do I solve it?

I do not understand.
I have tried a thousand times. @kvt0012

**Comment by xLidoni** [comment]
I bought the package from codecanyon 3 days ago, but I still haven't succeeded !!

@kvt0012 

I followed all the guides.

**Comment by kvt0012** [comment]
Do you know how to use command line, sir ? 
Please run the command 
flutter clean 
And run it again, thank you

**Comment by xLidoni** [comment]
sir, I've already done all the steps.

Yes I can use the command line.

However I fixed it, I downloaded an older version of flutter and installed it. Then I upgraded from the command line.

Now everything seems to be working.

Also I totally reinstalled android studio.

Deleting all the folders.


Thanks for your help

**Comment by kvt0012** [comment]
Ok, sir, I'm very glad when I see it. 
Wish you have a nice health, sir.
