### ISSUE TITLE
Mstore-mv V1.3.3 grpc error

### ISSUE THREAD

**Issue by govindasingh95** [inspireui/support#2602]
Hi there, I'm having trouble setting up my app. 
When I run setup through CE builder I get the error shown below.

V1.3 1 worked before but now V1.3.3 is giving this error. 

I have noticed the error states node -v 12.2.0 
Maybe I need to update node.js? 
![Screenshot_20200407-104039_Chrome](https://user-images.githubusercontent.com/43021182/78684009-fdc63980-78bd-11ea-8c9b-bf6c28b5ae0c.jpg)
![20200407_105103](https://user-images.githubusercontent.com/43021182/78684044-074fa180-78be-11ea-984c-a3f712bd2222.jpg)

**Comment by minhcasi** [comment]
@govindasingh95 - pls use 10.x for more stable and compatible with the app - thank you!
