### ISSUE TITLE
fluxstore pro - 

### ISSUE THREAD

**Issue by peppyday** [inspireui/support#2603]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:

2. Screenshots issues (required):

3. Proof of my purchased (required):

3. Config files (required)

**Comment by peppyday** [comment]
Hi i am using opencart grocery website. There i have option in product page like in screen shot. When i load it in app the price shows 0 since i can't show the unit. please let me know how to solve this in our app. My website for ref . 
![screen2](https://user-images.githubusercontent.com/63037137/78685740-ce401d00-790f-11ea-8926-b967bb7e35ff.jpg)
![screen3](https://user-images.githubusercontent.com/63037137/78685799-e0ba5680-790f-11ea-8b21-a235b0841d0a.jpg)

**Comment by peppyday** [comment]
And need add to cart button on home page product listing

**Comment by minhcasi** [comment]
@peppyday - pls help to share your common / config file so that we could help for checking - thanks

**Comment by peppyday** [comment]
export 'config/advertise.dart';
export 'config/general.dart';
export 'config/onboarding.dart';
export 'config/payments.dart';
export 'config/products.dart';
export 'config/smartchat.dart';

/// Server config demo for opencart
const serverConfig = {
  "type": "opencart",
  "url": "http://biggshop.in",
  "blog": "",
  "forgetPassword":
  "http://biggshop.in/index.php?route=account/forgotten"
};

**Comment by minhtruong315** [comment]
@peppyday Fluxstore doesn't support options in product now. We're working on it.

**Comment by peppyday** [comment]
But these are the basic things in ecommerce right?

**Comment by peppyday** [comment]
Also there is no add to cart icon or button in product widget. At least is it possible by now

**Comment by minhcasi** [comment]
@peppyday - yes, you are right - please bear with us for new Opencart improvement as our team is working on these features, it will be include on 1.6.7

<img width="547" alt="Screen Shot 2020-04-10 at 18 47 53" src="https://user-images.githubusercontent.com/1459805/78988662-cb396c80-7b5b-11ea-90bf-19c08eb386ca.png">

**Comment by minhcasi** [comment]
@peppyday - please help to check this issue as well - https://tppr.me/aIXty

**Comment by peppyday** [comment]
1. Hi when i use search for a existing product with its name it shows nothing

2. Nothing shows in the category page when i click on home tab. Need clarification nothing in doc.

3. How to add addcart icon to home page product widgets.

4. Can the opencart website users login in to the app with the same credentials.

thanks

**Comment by minhtruong315** [comment]
@peppyday can u send me full your source code via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/2603

**Comment by peppyday** [comment]
sent you through wetransfer please check https://we.tl/t-5QWI9s3txZ

**Comment by minhtruong315** [comment]
Hi @peppyday can u send me admin account to login to your website? I wanna check your website, because it's not working with MStore extension now.

**Comment by peppyday** [comment]
Sent you  email: truong@inspireui.com

**Comment by minhtruong315** [comment]
1.2 fixed. please try again
3. https://tppr.me/5WF73 
4. Yes. can

**Comment by peppyday** [comment]
Where can i find the fixed code.

**Comment by minhtruong315** [comment]
1.2 I fixed on MStore extension, I help you update the latest MStore extension on your website. so it's working well.
3. Follow by above image

**Comment by peppyday** [comment]
I see the category page now. but i need to display only the top level category. Now its showing some random category

**Comment by minhtruong315** [comment]
you can change "categoryLayout": "card", in config json to show top categories

**Comment by peppyday** [comment]
Ok.
1.In category names i see &AMP; instead of & symbol. Any fix.
2. Also in homepage recent items shows duplicate products as in attachement
![1](https://user-images.githubusercontent.com/63037137/79111050-6b300980-7d99-11ea-94fc-115f7943697a.jpg)

**Comment by peppyday** [comment]
Now the category is working. Thanks

Is there any way i can change the box colour or use image bg. If so which file to edit it.

Thanks

![2](https://user-images.githubusercontent.com/63037137/79111771-c9a9b780-7d9a-11ea-887f-d6e745476b5d.jpg)

**Comment by peppyday** [comment]
> Now the category is working. Thanks
> 
> Is there any way i can change the box colour or use image bg. If so which file to edit it.
> 
> Thanks
> 
> ![2](https://user-images.githubusercontent.com/63037137/79111771-c9a9b780-7d9a-11ea-887f-d6e745476b5d.jpg)

Found the solution for this....Thx.

Is there any way i can edit onboard screen ui and login and register screen ui. Thanks

**Comment by peppyday** [comment]
![3](https://user-images.githubusercontent.com/63037137/79118422-860b7980-7dab-11ea-9a11-f7e78d3d8326.jpg)
Getting this error while checkout can't able to move to next screen.

**Comment by minhtruong315** [comment]
> Ok.
> 1.In category names i see & instead of & symbol. Any fix.
> 2. Also in homepage recent items shows duplicate products as in attachement
> ![1](https://user-images.githubusercontent.com/63037137/79111050-6b300980-7d99-11ea-94fc-115f7943697a.jpg)

https://tppr.me/mNVmF you can edit _loadProduct function  like this to fix  duplicate product
```
_loadProduct() async {
    if (!endPage) {
      var config = widget.config;
      _page = _page + 1;
      config['page'] = _page;
      config['limit'] = 10;
      var newProducts = await _service.fetchProductsLayout(
          config: config,
          lang: Provider.of<AppModel>(context, listen: false).locale);
      bool isExisted = newProducts.isNotEmpty &&
          _products.indexWhere((o) => o.id == newProducts[0].id) > -1;
      if (newProducts != null && !isExisted) {
        setState(() {
          _products = [..._products, ...newProducts];
        });
        if (newProducts.length < 10) {
          setState(() {
            endPage = true;
          });
        }
      }
    }
  }
```
about symbol issues, we will fix on next release.

**Comment by peppyday** [comment]
> ![3](https://user-images.githubusercontent.com/63037137/79118422-860b7980-7dab-11ea-9a11-f7e78d3d8326.jpg)
> Getting this error while checkout can't able to move to next screen.

Any clue on this issue...

**Comment by minhtruong315** [comment]
@peppyday can you add this config to show detail error. 
https://isenselabs.com/posts/500-internal-server-error-opencart
Let me know when you add these. I will check your website again. Thanks

**Comment by peppyday** [comment]
> @peppyday can you add this config to show detail error.
> https://isenselabs.com/posts/500-internal-server-error-opencart
> Let me know when you add these. I will check your website again. Thanks
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/f379e814e46499a6b5997b2a78006327874eacd4/687474703a2f2f6973656e73656c6162732e636f6d2f696d672f75706c6f6164732f6f70656e636172742d3530305f643436613566353364652e706e67"><img alt="" height="14" src="https://camo.githubusercontent.com/9b15b794dec4b699491da2cef043b7d3f67fc4d9/68747470733a2f2f64336568337376706c31627573712e636c6f756466726f6e742e6e65742f4e4a65496f436a475679764954576d706a44505862524b7663696c425a4249542f6173736574732f7374617469632f736f757263652f7265762d633837343665662f2f66617669636f6e2e69636f"> iSenseLabs**[500 Internal Server Error in OpenCart: How to Find The Cause - Blogs | iSenseLabs](https://isenselabs.com/posts/500-internal-server-error-opencart)**500 Internal Server Error is a general HTTP status code that signals a problem with your OpenCart server, but the server cannot report the exact error cause.

Done.

**Comment by peppyday** [comment]
![image](https://user-images.githubusercontent.com/63037137/79186558-979a6300-7e37-11ea-9cd5-d56904da363b.png)
getting this now

**Comment by minhtruong315** [comment]
@peppyday replace this function then try again https://tppr.me/rbS5N
```
Future<bool> addItemsToCart(CartModel cartModel, String token) async {
    try {
      if (cookie != null) {
        List items = [];
        cartModel.productsInCart.keys.forEach((productId) {
          items.add({
            "product_id": productId,
            "quantity": cartModel.productsInCart[productId]
          });
        });

        var res = await http.delete(
            "$domain/index.php?route=extension/mstore/cart/emptyCart",
            headers: {'cookie': cookie, "content-type": "application/json"});
        if (res.statusCode == 200) {
          final body = convert.jsonDecode(res.body);
          if (res.statusCode == 200 &&
              body["success"] == 1 &&
              body["data"]["total_product_count"] == 0) {
            var res = await http.post(
                "$domain/index.php?route=extension/mstore/cart/add",
                body: convert.jsonEncode(items),
                headers: {
                  'cookie': cookie,
                  "content-type": "application/json"
                });
            final body = convert.jsonDecode(res.body);
            if (res.statusCode == 200 &&
                body["success"] == 1 &&
                body["data"]["total_product_count"] > 0) {
              return true;
            } else {
              throw Exception("Can not add items to cart");
            }
          } else {
            throw Exception(body["error"][0]);
          }
        } else {
          throw Exception(res.reasonPhrase);
        }
      } else {
        throw Exception("You need to login to checkout");
      }
    } catch (err) {
      rethrow;
    }
  }
```

**Comment by peppyday** [comment]
Now i can add address. Thanks.  The next screen shipping method give an error
![image](https://user-images.githubusercontent.com/63037137/79188971-2a3e0080-7e3e-11ea-8a57-3970d0bb0afb.png)

**Comment by minhtruong315** [comment]
@peppyday please look the video. your website has problem when request api for checkout
https://www.dropbox.com/s/ndcbv3rdggtxjl8/request.mov?dl=0

**Comment by peppyday** [comment]
Now my website is working properly. How to remove your mod. Also send me the revised mod to install again.

**Comment by peppyday** [comment]
Is it real

> @peppyday please look the video. your website has problem when request api for checkout
> https://www.dropbox.com/s/ndcbv3rdggtxjl8/request.mov?dl=0
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/59fb3767bfb44ac19e88bdac50079da63f6f459e/68747470733a2f2f7777772e64726f70626f782e636f6d2f74656d705f7468756d625f66726f6d5f746f6b656e2f732f6e64636276337264676774786a6c383f70726573657276655f7472616e73706172656e63793d46616c73652673697a653d3132303078313230302673697a655f6d6f64653d34">Dropbox**[request.mov](https://www.dropbox.com/s/ndcbv3rdggtxjl8/request.mov?dl=0)**Shared with Dropbox

Is there any chance this error comes because of php version of website

**Comment by peppyday** [comment]
can you send me the new oc.mod file with all the above fix. Need it for new installation

**Comment by minhtruong315** [comment]
I sent you mstore.ocmod.zip via your email. pls check

**Comment by peppyday** [comment]
Hi i installed a new opencart site. Still i face the problem. with checkout. Please take a look.

**Comment by minhcasi** [comment]
@peppyday - thank you for your patience on this ticket, we are trying our best with the troubleshooting, if it does not work we could process the refund :)

**Comment by peppyday** [comment]
May i know the time frame so that i don't disturb you till then.

**Comment by minhtruong315** [comment]
@peppyday add my skype: minhtruong315
I'll help u check issue remotely

**Comment by peppyday** [comment]
Which time shall we meet

**Comment by minhtruong315** [comment]
you can ping me on the skype when you're ready for support

**Comment by peppyday** [comment]
i pinged you yesterday..

**Comment by minhcasi** [comment]
refunded

**Comment by peppyday** [comment]
Thanks
