### ISSUE TITLE
How can update to new fluxStore version without deleting everything 

### ISSUE THREAD

**Issue by saioufe** [inspireui/support#2605]
1. My issue:
i'm using FluxStore pro app and every time a new version come up **i have to redownload the new one and delete the old version files** from my flutter project and import all the new files and restart again from ZERO 

****So** , is there any way that i can import only the modification codes without the all files and keep my old settings**

 , THANKS 
 
3. Proof of my purchased (required):
![buy](https://user-images.githubusercontent.com/32012762/78692718-f2e1c800-7902-11ea-84a0-e9779cdd9483.png)
![buy2](https://user-images.githubusercontent.com/32012762/78692722-f4ab8b80-7902-11ea-88c2-6957facb0160.png)

**Comment by minhcasi** [comment]
@saioufe - thank you for your feedback, we will create the new video to share how to manage the git with new version upgrade, it will available on next couple days - please subscribe to http://youtube.com/inspireui

Let us know if you have any questions, keep safe out there...😊

**Comment by minhcasi** [comment]
@saioufe - please also submit to get access to the git repo here - https://docs.google.com/forms/d/e/1FAIpQLSeuBqUkScy42V7KKhfNPj0fl581anrB1mWkbMa3p2WQt7fhfw/viewform

**Comment by saioufe** [comment]
thanks you very much for your answer , but is the repo on gitlab or github ??

**Comment by harjono-flux** [comment]
> @saioufe - thank you for your feedback, we will create the new video to share how to manage the git with new version upgrade, it will available on next couple days - please subscribe to http://youtube.com/inspireui
> 
> Let us know if you have any questions, keep safe out there...😊
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/f406561f2bbdfd164cbf7ac7ee7a95adc7e14990/68747470733a2f2f7974332e67677068742e636f6d2f612f41415458414a7830426352753550447657705a326d71624a477068796165466c6d6f436d4f32577634773d733930302d632d6b2d63307866666666666666662d6e6f2d726a2d6d6f"><img alt="" height="14" src="/yts/img/favicon_144-vfliLAfaB.png"> YouTube**[Inspire UI](https://www.youtube.com/channel/UCQd30xCKstlM6PL6qtSOjFw)**

still waiting ur video....

**Comment by harjono-flux** [comment]
@saioufe do you already have the answer for ur issue No.1 ?
