### ISSUE TITLE
MStore Pro - Expo Android release on play store crash error

### ISSUE THREAD

**Issue by Jenarath** [inspireui/support#2606]
MStore Pro - Expo Android release on play store crash error

My screenshot log error on play store.
<img width="919" alt="Screen Shot 2563-04-07 at 23 11 25" src="https://user-images.githubusercontent.com/25680869/78693125-04d46280-7925-11ea-92c0-f567db021eed.png">

3. Proof of my purchased (required):
<img width="1219" alt="Screen Shot 2563-04-07 at 23 12 42" src="https://user-images.githubusercontent.com/25680869/78693254-33523d80-7925-11ea-826a-8b6b2bd5c477.png">

3. Config files (required)
package.json & app.json
[config.zip](https://github.com/inspireui/support/files/4445773/config.zip)

Please recommend and solve problem
Thank you so much.

**Comment by minhcasi** [comment]
@Jenarath - please make sure you have changed the bundle id correctly base on this guide - https://docs.inspireui.com/mstore/delivery/#change-android-package-name - also change the folder path to match with your bund id is important - thanks

**Comment by Jenarath** [comment]
Thank you.
I see your recommend. but My code structure doesn't have folder.
How to change a new android package name ?

<img width="287" alt="Screen Shot 2563-04-08 at 11 48 25" src="https://user-images.githubusercontent.com/25680869/78745915-bc05c380-798f-11ea-9556-14ad89e5d1b4.png">

**Comment by minhcasi** [comment]
@Jenarath - if you are using mstore-expo the config is located from app.json - pls check this guide https://docs.expo.io/versions/latest/workflow/configuration/
