### ISSUE TITLE
Fluxstore Multi Vendor 1.6.6 - Is it supposed to look like woomerce?

### ISSUE THREAD

**Issue by spetsglaz** [inspireui/support#2607]
<img width="1408" alt="Skärmavbild 2020-04-07 kl  20 02 55" src="https://user-images.githubusercontent.com/62562826/78704118-a8b11480-790b-11ea-92e7-f142f84d2b07.png">
Hello, i was trying out the example WCFM on my application and it looks just like woomerce single store, is this supposed to look like this? thanks

**Comment by minhcasi** [comment]
@spetsglaz - the homepage is flexible to upgrade same as Fluxstore Pro UI - pls check this guide https://docs.inspireui.com/mstore/home-theme/

You can also keep the default one and change the new category/tag id, or using fluxbuilder for the setting http://fluxbuilder.com/

Let us know if you have any questions - thank you!
