### ISSUE TITLE
[Mstore-pro] - after confirm order in the app, in modal still nothing in the cart 

### ISSUE THREAD

**Issue by undigitals** [inspireui/support#2608]
1.  purchase proof
<img width="817" alt="Screen Shot 2020-04-03 at 12 07 05 AM" src="https://user-images.githubusercontent.com/22441312/78389062-0b10c900-761d-11ea-8539-8ffa045c85cc.png">
---------

2. My issue:
after confirm order in the app, in modal still nothing in the cart when I use checkout page
<img width="534" alt="Screen Shot 2020-04-08 at 3 03 47 AM" src="https://user-images.githubusercontent.com/22441312/78703679-994ebd00-7945-11ea-9956-37514f9c0972.png">

<img width="317" alt="Screen Shot 2020-04-08 at 1 04 55 AM" src="https://user-images.githubusercontent.com/22441312/78703727-ac618d00-7945-11ea-84c7-68ed3a76f8f3.png">

When I use mstore-checkout there is nothing not even page
<img width="494" alt="Screen Shot 2020-04-08 at 3 06 42 AM" src="https://user-images.githubusercontent.com/22441312/78703953-14b06e80-7946-11ea-83c3-577001025375.png">
![Screenshot_1586257429](https://user-images.githubusercontent.com/22441312/78704066-4295b300-7946-11ea-9572-a875d49c40bf.png)

**Comment by minhtruong315** [comment]
@undigitals can u send me full source code via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/2608

**Comment by undigitals** [comment]
I did send. I sent also wordpress website login credentials. I am using bacs payment method. Thank you.

**Comment by minhtruong315** [comment]
Hi @undigitals I can't order  product on your website. can u record me screenshot for checkout on your website?

**Comment by undigitals** [comment]
I'm using Mstore website/storefront which is recommended by you.

**Comment by minhtruong315** [comment]
it seems we could not see the Add to cart on your website, please try to prefconfig site from us could be fixed the issue - https://github.com/inspireui/mstore

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
