### ISSUE TITLE
[FluxStore-Woocommerce] 1.6.5 - Still questions about editing

### ISSUE THREAD

**Issue by spetsglaz** [inspireui/support#2609]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: https://github.com/inspireui/support/issues/2501
Hello again i found the source in flutter inspector but i can't figure out how to add a pattern or a picture in the white background instead of just a color, i can't find the source of the images that i want to change, is it possible to change it with a png file?

2. Screenshots issues (required):
See the screenshots from the issue i linked.

3. Proof of my purchased (required):
verified ⭐️

Thank you.

**Comment by kvt0012** [comment]
Dear sir, with the image, you can access to assets/images and you will see it.
