### ISSUE TITLE
[cebuilder] on mac cannot run ios/android setup

### ISSUE THREAD

**Issue by yudhazp** [inspireui/support#261]
**Mandatory Info (please complete the following information):**
 - Product: [beonews pro]
 - Your Purchased Code: [6c987899-06d8-4020-af47-6987fe25a784]
(we may not reply if you are not our customer)

helo there..

i got this error when try to RUN IOS SETUP.. on cebuilder for mac

“cebuilder.sh” can’t be opened because Sandbox is not allowed to open documents in Terminal.

what should i do?

![screen shot 2019-02-06 at 9 53 44 am](https://user-images.githubusercontent.com/47374974/52318392-df815700-29f6-11e9-81bc-fab6167ae1be.png)

**Comment by minhtruong315** [comment]
Hi @yudhazp Can you add my skype? I will help you check it via teamview.
my skype is minhtruong315@gmail.com

**Comment by Riyashanke** [comment]
Am also facing the same issues for Mstore Pro. How to solve this kindly guide me
