### ISSUE TITLE
[FluxStore Pro] - So many issues with Opencart 3

### ISSUE THREAD

**Issue by harry503** [inspireui/support#2610]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issues:
There are many issues with opencart 3, please assign your team to make sure that every functionalities works. So many basic errors:
- SalePrice, OnSale fields not set correctly, mapped to the wrong field
- In Stock is incorrect.
The provided code cannot display red % discount + its discount price

- Save address missing so many fields in the opencart backend, fields are not being provided as required by opencart when saving the address as part of checkout
![Screen Shot 2020-04-08 at 00 28 25](https://user-images.githubusercontent.com/35995317/78704708-75d04600-7936-11ea-84cb-764048701410.jpg)

- Category Name, Product title and description not being encoded in the opencart api. therefore it displays html encoded tag.
<img width="421" alt="Screen Shot 2020-04-08 at 01 11 42" src="https://user-images.githubusercontent.com/35995317/78704348-ef1b6900-7935-11ea-82d7-a338b467a141.png">
The API code need to do html_entity_decode() inside the opencart API code.

<img width="410" alt="Screen Shot 2020-04-08 at 01 12 13" src="https://user-images.githubusercontent.com/35995317/78704407-00647580-7936-11ea-9523-f6db1b9850be.png">

Basically, I need you or your team to test all of the basic functionalities against OC 3 as specified and it has to work.

I believe the login functionalities is also not working. I notice that it tries to send PHP. When login with normal email and password, the code pass empty string on saveUser, and it causes the local storage to has token = "". and I don't think that this will work in the OC side. let;s say the next 2-3 hours after the session has been drop, how can the server knows which user is currently on without saving the token in the OC side?

I tried to use your demo, and there are many errors as well = not able to complete the transaction / checkout. Please again, fix all those errors above for Opencart and test all functionalities.

With this version, I don't believe that any of us can have a running app using this product and OC as the backend due to errors mentioned above. I feel like this is lack of testing with OC.

Thank you

2. Screenshots issues (required):
above

3. Proof of my purchased (required):
Item Purchase code: f2dca5d6-d4f8-446c-b5d9-75900edc613b

3. Config files (required)
default config as provided for OC.

**Comment by harry503** [comment]
Also:

in OC API file (catalog/extension/mstore/cart.php)
public function empty() {

empty is a reserved word in PHP, and has to be changed with someething else. I changed it to "clear"

public function clear() {

So, again that it seems it's almost there, can be used with OC, but it's not yet 100% and perhaps it's not yet tested throughly for Opencart.

It should be simple and just need testing.

**Comment by minhcasi** [comment]
@minhtruong315 - please help to investigate this issue as a high priority - thank you!

**Comment by harry503** [comment]
Moving on on the next step in Checkout, The shipping cost is not retrieved from API, but it's harcoded 0. Unlike magento that has been handled.

Again, lack of testing in OC
<img width="631" alt="Screen Shot 2020-04-09 at 00 22 07" src="https://user-images.githubusercontent.com/35995317/78814155-67e2f980-79f8-11ea-80f1-151d5ea7f1a0.png">

Even in magento, the currency is harcoded as $.

It should be 
cost = double.parse(item["cost"]);


Going back to the Address Step (previous step), few erros:
- country id is not passed as integer instead of code. OC works with country id as integer
- zone id is hardcoded as 1234, instead of passing the selected province / state from the dropdownlist

**Comment by harry503** [comment]
Select Address during checkout is also not handled for OC. Billing is not mapped nor retrieved from OC API. It should be part of the extention/mstore/account.php where it should return their addresses as well.


<img width="420" alt="Screen Shot 2020-04-09 at 00 41 21" src="https://user-images.githubusercontent.com/35995317/78815828-feb0b580-79fa-11ea-8bcb-93653b611438.png">

<img width="466" alt="Screen Shot 2020-04-09 at 00 40 22" src="https://user-images.githubusercontent.com/35995317/78815851-0708f080-79fb-11ea-8f78-e622e6180491.png">

the code seems to work only in WooCommerce.

**Comment by harry503** [comment]
"You Might Also Like" section of Product Page, is not using data of related product id from OC API. instead it's just using products from the same category.

Can you make it same like Mstore Pro where it displays related product ids from API?

**Comment by harry503** [comment]
"You Might Also Like" section of Product Page, is not using data of related product id from OC API. instead it's just using products from the same category.

Can you make it same like Mstore Pro where it displays related product ids from API?

**Comment by harry503** [comment]
Checkout -- Final Step: Order ID is hardcoded to 0 for OpenCart
---------------------

<img width="456" alt="Screen Shot 2020-04-10 at 08 38 20" src="https://user-images.githubusercontent.com/35995317/78954637-f0e85680-7b06-11ea-8aa5-372e3721148b.png">

<img width="493" alt="Screen Shot 2020-04-10 at 08 39 23" src="https://user-images.githubusercontent.com/35995317/78954643-f5ad0a80-7b06-11ea-88b2-77304cc94a05.png">


OC API: Payment Addres and Shipping Address
----------------------
PHP Code in the OC API keep creating a new address everytime. Need to be able to detect whether the selected is previously saved address by passing address id from the list of address from the APP to OC API

<img width="927" alt="Screen Shot 2020-04-10 at 10 12 25" src="https://user-images.githubusercontent.com/35995317/78959038-f26c4b80-7b13-11ea-9864-02d5be04f39d.png">

**Comment by midotaha** [comment]
**harry503**  spoke right , realy Opencart no tested at all, there is tones of issues , also there is many works to do it , i'd like to add another issue i spoke about it, and not got any support for this issue or solved it  :- 
**- products option like(colors - wights ............etc)**.
support team tell me in another previous closed ticket they will update this function on the next update , untile now there is 2 updates released , and i am not found this function 
**- also at the last update checkout on cart not working fine , after change server config type to "opencart"**.
**- application not got any address from my web store to customer profile on app, after sign in **.
i hope to fix this issues and test all stander function to opencart
Many thanks for you 
this proof 
![FluxStore](https://user-images.githubusercontent.com/19406537/79008684-9383f200-7b66-11ea-84db-0e08c6c7e711.png)

**Comment by minhtruong315** [comment]
SalePrice, OnSale fields, In Stock is incorrect. you can update fromOpencartJson function in models/product.product.dart to fix these issues
```
Product.fromOpencartJson(Map<String, dynamic> parsedJson) {
    id = parsedJson["product_id"] != null
        ? int.parse(parsedJson["product_id"])
        : 0;
    name = parsedJson["name"];
    description = parsedJson["description"];
    permalink = parsedJson["permalink"];
    regularPrice = parsedJson["price"];
    salePrice = parsedJson["special"];
    price = salePrice ?? regularPrice;
    onSale = salePrice != null;
    inStock = parsedJson["in_stock"] == "In Stock";
    averageRating = parsedJson["rating"] != null
        ? double.parse(parsedJson["rating"].toString())
        : 0.0;
    ratingCount = parsedJson["reviews"] != null
        ? int.parse(parsedJson["reviews"].toString())
        : 0.0;
    attributes = [];

    List<String> list = [];
    if (parsedJson["images"] != null && parsedJson["images"].length > 0) {
      for (var item in parsedJson["images"]) {
        list.add(item);
      }
    }
    if (list.isEmpty && parsedJson['image'] != null) {
      list.add('${serverConfig['url']}/image/${parsedJson['image']}');
    }
    images = list;
    imageFeature = images.isNotEmpty ? images[0] : "";
  }
```

**Comment by minhtruong315** [comment]
to fix html decode issue. you need to edit fromOpencartJson function in models/category/category.dart
```
Category.fromOpencartJson(Map<String, dynamic> parsedJson) {
    id = parsedJson["id"] != null ? int.parse(parsedJson["id"]) : 0;
    name = HtmlUnescape().convert(parsedJson["name"]);
    image = parsedJson["image"] != null ? parsedJson["image"] : kDefaultImage;
    totalProduct = parsedJson["count"] != null
        ? int.parse(parsedJson["count"].toString())
        : 0;
    parent = parsedJson["parent"] != null
        ? int.parse(parsedJson["parent"].toString())
        : 0;
  }
```
and replace models/product/product.dart
[product.dart.zip](https://github.com/inspireui/support/files/4463837/product.dart.zip)

**Comment by harry503** [comment]
@minhtruong315 Can you explain the fixes that you've done? is it part of the next release? when will it be release? have you tested every function of the fluxstore for the opencart to work the same as woocommerce?

I see the your fixes in category and products (above), but there are more that these 2 issues.

**Comment by harry503** [comment]
@minhcasi Can you share that @minhtruong315  has done? and when will be released? The ticket is just closed, yes he did provide with attached files. but there are more than these 2 files. When will it be published as a new release? Please also make sure that your team really test it out against Opencart as it's specified that your app is working with Opencart.

as mentioned earlier that many basic functionalities were missed - not working. It's not possible if they really test carefully.

Thank you

**Comment by atishpaul** [comment]
Hi,
I found a problem in stock status,every product is showing out of stock by default.
so to fix this,change 'in stock' to 'out of stock'. shown in image.


![image](https://user-images.githubusercontent.com/38566116/80722812-6b603100-8b1d-11ea-85f8-7f3dcdff61fa.png)
