### ISSUE TITLE
[FLUXNEWS] - Customise left menu side in tabbar.dart

### ISSUE THREAD

**Issue by ernandozatariano** [inspireui/support#2611]
Hi, i have two questions to finish my fluxnews app:

1) How i hide de login option in left menu side (tabbar.dart)?

2) In left menu side (tabbar.dart) i'd like to add a webview link, like i did in bottom menu. Something like that:

    {
      "layout": "page",
      "url": "https://eu.arq.br/app-feedlogin/",
      "icon": "assets/icons/tabs/icon-category.png"
    },

It's possible?

Tks again!!!

**Comment by minhcasi** [comment]
Hi, thank you for the feedback. Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads it's used to verify your proof of purchase? 
Sorry for any inconvenience, we will reopen the ticket when it is verified, thank you!

**Comment by ernandozatariano** [comment]
![Sem título](https://user-images.githubusercontent.com/63005352/78781265-4ccfa580-7976-11ea-9671-28fced19752d.jpg)

Hi, ok!

**Comment by dttrung26** [comment]
Hi @ernandozatariano ,
for issue number 1, comment out those line in logo.dart could hide your left side menu away.
` 
Positioned(
            top: 55,
            left: 10,
            child: IconButton(
              icon: Icon(
                Icons.blur_on,
                color: Theme.of(context).accentColor.withOpacity(0.6),
                size: 22,
              ),
              onPressed: () => Scaffold.of(context).openDrawer(),
            ),
          ), 
` 
for issue number 2, please add those lines and customize to meet your need.
`
import 'widgets/webview.dart';

ListTile(
                  leading: const Icon(
                    Icons.pageview,
                    size: 20,
                  ),
                  title: Text("Page view"),
                  onTap: () {
                    Navigator.push(
                        context,
                        MaterialPageRoute(
                            builder: (context) => WebView(
                                url: "https://inspireui.com/who-we-are",
                                title: "Page view")));
                  },
                ), 
`

**Comment by ernandozatariano** [comment]
Hi, tks again.

1. For issue number one, i dont like to hide my left side menu away. I just need to hide the login option inside my left menu. Look this screenshot:

![hide-logout](https://user-images.githubusercontent.com/63005352/79050178-b6fa7b80-7bfe-11ea-9fb3-22a573f90c40.jpg)

2. For issue number two, i add the code in my tabbar.dart, but its not working for me. 

![tabbar](https://user-images.githubusercontent.com/63005352/79050349-cded9d80-7bff-11ea-939b-0684f42f3ed8.jpg)

This is my compiler message:
----------------------------------------------------------------------------------------------------
Performing hot restart...
Syncing files to device Android SDK built for x86...

Compiler message:
lib/tabbar.dart:331:1: Error: Directives must appear before any declarations.
Try moving the directive before any declarations.
import 'widgets/webview.dart';
^^^^^^
lib/tabbar.dart:334:8: Error: Non-optional parameters can't have a default value.
Try removing the default value or making the parameter optional.
leading: const Icon(
       ^
lib/tabbar.dart:338:6: Error: Non-optional parameters can't have a default value.
Try removing the default value or making the parameter optional.
title: Text("Page view"),
     ^
lib/tabbar.dart:339:6: Error: Non-optional parameters can't have a default value.
Try removing the default value or making the parameter optional.
onTap: () {
     ^
lib/tabbar.dart:347:2: Error: Expected '{' before this.
),
 ^
lib/tabbar.dart:347:2: Error: Expected a declaration, but got ','.
),
 ^
lib/tabbar.dart:152:17: Error: Too few positional arguments: 3 required, 0 given.
        ListTile(
                ^
lib/tabbar.dart:333:1: Context: Found this candidate, but the arguments don't match.
ListTile(
^^^^^^^^
lib/tabbar.dart:170:17: Error: Too few positional arguments: 3 required, 0 given.
        ListTile(
                ^
lib/tabbar.dart:333:1: Context: Found this candidate, but the arguments don't match.
ListTile(
^^^^^^^^
lib/tabbar.dart:338:8: Error: Constant expression expected.
Try inserting 'const'.
title: Text("Page view"),
       ^^^^
lib/tabbar.dart:343:23: Error: Constant expression expected.
Try inserting 'const'.
builder: (context) => WebView(
                      ^^^^^^^
lib/tabbar.dart:343:23: Error: Cannot invoke a non-'const' constructor where a const expression is expected.
Try using a constructor or factory that is 'const'.
builder: (context) => WebView(
                      ^^^^^^^
lib/tabbar.dart:343:10: Error: Not a constant expression.
builder: (context) => WebView(
         ^^^^^^^^^
lib/tabbar.dart:342:1: Error: Constant expression expected.
Try inserting 'const'.
MaterialPageRoute(
^^^^^^^^^^^^^^^^^
lib/tabbar.dart:342:1: Error: Cannot invoke a non-'const' constructor where a const expression is expected.
Try using a constructor or factory that is 'const'.
MaterialPageRoute(
^^^^^^^^^^^^^^^^^
lib/tabbar.dart:341:1: Error: Getter not found: 'context'.
context,
^^^^^^^
lib/tabbar.dart:340:11: Error: Method invocation is not a constant expression.
Navigator.push(
          ^^^^
lib/tabbar.dart:339:8: Error: Not a constant expression.
onTap: () {
       ^^
Restarted application in 2.047ms.

----------------------------------------------------------------------------------------------------

**Comment by dttrung26** [comment]
Hi @ernandozatariano , please leave me your /lib/tabbar.dart and /lib/menu.dart, I'll finish the rest and send you back :D 
Nice day!

**Comment by ernandozatariano** [comment]
Hi, tks a lot! :D 

[tabbar.zip](https://github.com/inspireui/support/files/4469483/tabbar.zip)

best regards

**Comment by dttrung26** [comment]
Hi @ernandozatariano 
Replace below file into your /lib/ would fix that. Please bear in mind that those code needs to be customized to meet your need. 
```
  ListTile(
                  leading: const Icon(
                    Icons.pageview, // replace your icon here
                    size: 20,
                  ),
                  title: Text("About us"), //replace your title here
                  onTap: () {
                    Navigator.push(
                        context,
                        MaterialPageRoute(
                            builder: (context) => WebView(
                                url: "https://inspireui.com/about/", //replace your web link here
                                title: "About Us"))); // replace your title here
                  },
                ),
```
Let me know if you still have any question
[support_ticket#2611.zip](https://github.com/inspireui/support/files/4472799/support_ticket.2611.zip)

**Comment by dttrung26** [comment]
Close due to no response from customer!
