### ISSUE TITLE
ListApp issue

### ISSUE THREAD

**Issue by wannabe1st** [inspireui/support#2614]
I have the following error in ListApp when I hit run setup from CEbuilder.

C:\2\source\node_modules\api-ecommerce\node_modules\grpc>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build --library=static_library --module=C:\2\source\node_modules\api-ecommerce\node_modules\grpc\src\node\extension_binary\node-v79-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=C:\2\source\node_modules\api-ecommerce\node_modules\grpc\src\node\extension_binary\node-v79-win32-x64-unknown --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v79 )  else (node "" configure --fallback-to-build --library=static_library --module=C:\2\source\node_modules\api-ecommerce\node_modules\grpc\src\node\extension_binary\node-v79-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=C:\2\source\node_modules\api-ecommerce\node_modules\grpc\src\node\extension_binary\node-v79-win32-x64-unknown --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v79 )
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.7
gyp info using node@13.11.0 | win32 | x64
gyp ERR! find Python
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if "python" can be used
gyp ERR! find Python - "python" is not in PATH or produced an error
gyp ERR! find Python checking if "python2" can be used
gyp ERR! find Python - "python2" is not in PATH or produced an error
gyp ERR! find Python checking if "python3" can be used
gyp ERR! find Python - "python3" is not in PATH or produced an error
gyp ERR! find Python checking if the py launcher can be used to find Python 2
gyp ERR! find Python - "py.exe" is not in PATH or produced an error
gyp ERR! find Python checking if Python is C:\Python27\python.exe
gyp ERR! find Python - "C:\Python27\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Python37\python.exe
gyp ERR! find Python - "C:\Python37\python.exe" could not be run
gyp ERR! find Python
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python="C:\Path\To\python.exe"
gyp ERR! find Python   (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
gyp ERR! find Python   npm config set python "C:\Path\To\python.exe"
gyp ERR! find Python For more information consult the documentation at:
gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
gyp ERR! find Python **********************************************************
gyp ERR! find Python
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Python installation to use
gyp ERR! stack     at PythonFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:307:47)
gyp ERR! stack     at PythonFinder.runChecks (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:136:21)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:225:16)
gyp ERR! stack     at PythonFinder.execFileCallback (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:271:16)
gyp ERR! stack     at exithandler (child_process.js:310:5)
gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:322:5)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
gyp ERR! stack     at onErrorNT (internal/child_process.js:467:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:84:21)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--library=static_library" "--module=C:\\2\\source\\node_modules\\api-ecommerce\\node_modules\\grpc\\src\\node\\extension_binary\\node-v79-win32-x64-unknown\\grpc_node.node" "--module_name=grpc_node" "--module_path=C:\\2\\source\\node_modules\\api-ecommerce\\node_modules\\grpc\\src\\node\\extension_binary\\node-v79-win32-x64-unknown" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v79"
gyp ERR! cwd C:\2\source\node_modules\api-ecommerce\node_modules\grpc
gyp ERR! node -v v13.11.0
gyp ERR! node-gyp -v v5.0.7
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallback-to-build --library=static_library --module=C:\2\source\node_modules\api-ecommerce\node_modules\grpc\src\node\extension_binary\node-v79-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=C:\2\source\node_modules\api-ecommerce\node_modules\grpc\src\node\extension_binary\node-v79-win32-x64-unknown --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v79' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\2\source\node_modules\api-ecommerce\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1026:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Windows_NT 10.0.18363
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\2\\source\\node_modules\\api-ecommerce\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd C:\2\source\node_modules\api-ecommerce\node_modules\grpc
node-pre-gyp ERR! node -v v13.11.0
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd configure --fallback-to-build --library=static_library --module=C:\2\source\node_modu                                          

Proof
![proof](https://user-images.githubusercontent.com/50643754/78714908-4b29c180-7925-11ea-9bae-aba9daf11605.JPG)

**Comment by minhcasi** [comment]
@wannabe1st - could you help to take the whole screenshot that includes your username on Envato please, or you can also comment form the product

**Comment by wannabe1st** [comment]
![578DE4AE-3C24-4991-B469-D62E0CFC0382](https://user-images.githubusercontent.com/50643754/78743149-74b70d00-7966-11ea-984f-1cdf4f7c6a34.jpeg)

**Comment by wannabe1st** [comment]
> @wannabe1st - could you help to take the whole screenshot that includes your username on Envato please, or you can also comment form the product

**Comment by minhcasi** [comment]
@wannabe1st - pls try to install the nodejs 10.x from the link to fix the issue - https://nodejs.org/dist/latest-v10.x/

The react native may not work well on latest nodejs - thanks
