### ISSUE TITLE
[Fluxstore] - product color not appear in Arabic version

### ISSUE THREAD

**Issue by limitlessfirm** [inspireui/support#2616]
---------

1. My issue: product color appear in all language but not appear in Arabic version

2. Screenshots issues (required): 
![color-arabic](https://user-images.githubusercontent.com/59250639/78746394-01fa6180-7967-11ea-8ad8-6adb460aeb8e.JPG)

3. Proof of my purchased (required):
![screenshot](https://user-images.githubusercontent.com/59250639/78746435-1fc7c680-7967-11ea-842e-df1a33568b7d.JPG)

3. Config files (required)

**Comment by minhcasi** [comment]
@limitlessfirm - could you share the common and config folder so that we could help for checking - thanks

**Comment by limitlessfirm** [comment]
[common.zip](https://github.com/inspireui/support/files/4454098/common.zip)
[config.zip](https://github.com/inspireui/support/files/4454100/config.zip)

**Comment by philipvu30** [comment]
Hi @limitlessfirm ,

Please translate your colors into arabic in colors.dart
![image](https://user-images.githubusercontent.com/54442328/78879354-fbaad900-7a7d-11ea-9b0e-a8550aaa3a30.png)

![image](https://user-images.githubusercontent.com/54442328/78879327-f2ba0780-7a7d-11ea-8467-f5258ea2087e.png)
