### ISSUE TITLE
Flux News - Blog Detail Layout. I cant change style post

### ISSUE THREAD

**Issue by zemeister2332** [inspireui/support#2617]
NOTE: I ALREADY UPDATE NEW VERSION 1.3
1. My issue:
 I cant change style post. its only in quarterImage and not change
2. Screenshots issues:
<img src="https://i.ibb.co/xDRVrfN/Screen-Shot-2020-04-08-at-11-56-03-AM.png">
3. Proof of my purchased:
<img src="https://i.ibb.co/JvcdPBT/Screen-Shot-2020-04-08-at-11-59-57-AM.png">
4. Comments too not work. It say successfully write comment. But nothing.
<img src="https://i.ibb.co/Bg0WzpY/Screen-Shot-2020-04-08-at-1-37-14-PM.png">
<img src="https://i.ibb.co/qDn78d5/Screen-Shot-2020-04-08-at-2-03-03-PM.png">
5. Config files 
[common.zip](https://github.com/inspireui/support/files/4448753/common.zip)

**Comment by zemeister2332** [comment]
How can i change it. And Post Font Size ?

**Comment by dttrung26** [comment]
Hi @zemeister2332 ,
Noted checking sir. 
About number 4, please note that whether your comments need to be approved on wp admin site. 
In terms of post font size, we currently don't support that adjustment. This feature might be added in the near future. 
Nice day.

**Comment by zemeister2332** [comment]
yes it is

**Comment by zemeister2332** [comment]
> Hi @zemeister2332 ,
> Noted checking sir.
> About number 4, please note that whether or not your comments need to be approved on wp admin site.
> In terms of post font size, we currently don't support that adjustment. This feature might be added in the near future.
> Nice day.

do you have whatsapp or telegram

**Comment by zemeister2332** [comment]
how can i back my money

**Comment by minhcasi** [comment]
If you are not satisfied with the product so far, it's possible to refund on this link https://help.market.envato.com/hc/en-us/articles/202821460-Can-I-Get-A-Refund-
