### ISSUE TITLE
[FluxStore] Unable to build project at all

### ISSUE THREAD

**Issue by Artiiz-ZA** [inspireui/support#2618]
1. **My Issue:** I am unable to build the project even with a clean download. Below is what I run into when trying a flutter build:

```
Waiting for another flutter command to release the startup lock...
Launching lib\main.dart on Android SDK built for x86 in debug mode...

Compiler message:
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image-0.7.1/lib/src/gesture/extended_image_slide_page_route.dart:333:9: Error: No named parameter with the name 'animation'.
        animation: animation,
        ^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/cupertino/route.dart:435:3: Context: Found this candidate, but the arguments don't match.
  CupertinoFullscreenDialogTransition({
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.15.0/lib/src/picture_stream.dart:92:3: Error: The superclass, 'Diagnosticable', has no unnamed constructor that takes no arguments.
  PictureStream();
  ^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.15.0/lib/src/picture_stream.dart:192:16: Error: The superclass, 'Diagnosticable', has no unnamed constructor that takes no arguments.
abstract class PictureStreamCompleter extends Diagnosticable {
               ^
Exited (1)
```

2. **Screenshot of Issue:**
![image](https://user-images.githubusercontent.com/26002121/78764243-91633d00-7986-11ea-9a5a-7a4742b037f7.png)

3. **Proof of Purchase:**
![image](https://user-images.githubusercontent.com/26002121/78764327-acce4800-7986-11ea-8612-f8c3fe8f84ad.png)

Thanks

**Comment by minhcasi** [comment]
@Artiiz-ZA - could you try to update the channel to stable by using this script
```
flutter channel stable
flutter upgrade --force
```

The extended_image library will not work on master channel

**Comment by AteqEjaz** [comment]
SAME ISSUE with Beta channel as well :(

**Comment by kvt0012** [comment]
> SAME ISSUE with Beta channel as well :(

Please change to flutter channel stable and check it again, thank you

**Comment by harmispatel** [comment]
> > SAME ISSUE with Beta channel as well :(
> 
> Please change to flutter channel stable and check it again, thank you

It works Thanks a lot

**Comment by minhcasi** [comment]
Btw, you could use with the master channel if change the `extended_image: 0.7.3-dev`

@harmispatel - 
We're glad that it help, please give us some feedback/rating to this page https://codecanyon.net/downloads  if the product is helpful for your business, we are working hard to update more awesome and powerful features on next coming version release. Let us know if you have any feedback. Thank you very much 😊
