### ISSUE TITLE
Fluxstore Multi Vendor - Login Issue

### ISSUE THREAD

**Issue by raysernick** [inspireui/support#2619]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: Login  always loading and need to press back button to navigate home

2. Screenshots issues (required): 
![Screenshot_1586342307](https://user-images.githubusercontent.com/30488936/78775210-0868f780-79c0-11ea-86b3-c81e68d8b744.png)

3. Proof of my purchased (required):
![asdsad](https://user-images.githubusercontent.com/30488936/78775306-34847880-79c0-11ea-838f-f26ffaf656a3.png)

**Comment by raysernick** [comment]
solved!

**Comment by arafatkn** [comment]
> solved!

Can you please tell me how to solve this issue? I am facing same issue.
