### ISSUE TITLE
[my-product] - fluxnews.1.2.2

### ISSUE THREAD

**Issue by mbatm** [inspireui/support#2620]
My issue:
1- there is no side menu shown..
2- i cannot change fonts or adapting to turkish fonts.
3- my app dont show white background at news detail.
i want to translate all my app to turkish. so, i create a new strings_tr.arp document and translate all of it. but i dont know how can i set this.
4- at latest template update, mstore api give error from wp page and main page.

at last issue, Doan Tan Trung want my skype adres and close topic. pls solve or help abt. my problem 

![image](https://user-images.githubusercontent.com/62890007/78782330-87533580-79aa-11ea-8ab4-556fb9500b9b.png)

![image](https://user-images.githubusercontent.com/62890007/78782305-7e626400-79aa-11ea-8b83-148e2f0979de.png)
https://user-images.githubusercontent.com/62890007/77925678-d237c380-72ad-11ea-97f2-927caa51ee21.png

**Comment by dttrung26** [comment]
Hi @mbatm ,
I've reach you via skype. Please kindly response when you get it.

**Comment by dttrung26** [comment]
No response from customer. Please reopen the ticket instead of creating new one when you are available. 
Best
