### ISSUE TITLE
[FluxNews] - I have some questions here

### ISSUE THREAD

**Issue by haidarsalim** [inspireui/support#2622]
1- How do I remove these items with the chat tray
![222](https://user-images.githubusercontent.com/54249914/78808925-cf844f00-79ce-11ea-8617-49a97591aecc.JPG)
--------------------------------------
2- Is it possible to hide the registration through Facebook
![5675](https://user-images.githubusercontent.com/54249914/78809046-00648400-79cf-11ea-8af6-68172d502f46.JPG)
--------------------------------------
3- Where can I find and change these words?
![3243432](https://user-images.githubusercontent.com/54249914/78809443-99939a80-79cf-11ea-9d4d-e268b042811a.JPG)
--------------------------------------
4- A message appears below the images
BOTTOM OVERFLOWED BY 12 PIXELS
![BOTTOM OVERFLOWED BY 12 PIXELS](https://user-images.githubusercontent.com/54249914/78809576-d2cc0a80-79cf-11ea-816f-b34d0a495df8.JPG)
--------------------------------------
5- I would like to hide the categories and customize the Privacy-Policy links and more

![fff](https://user-images.githubusercontent.com/54249914/78809741-09098a00-79d0-11ea-91af-e45724e4e281.JPG)
Please include a screenshot of the modification method
--------------------------------------
6- Do I leave this part without modification
![2133214](https://user-images.githubusercontent.com/54249914/78810186-b11f5300-79d0-11ea-8f56-c1e634e305ae.JPG)
--------------------------------------
Thanks for your continued support
![222222](https://user-images.githubusercontent.com/54249914/78810135-9cdb5600-79d0-11ea-8ebc-0c5e722c52cd.JPG)

**Comment by minhcasi** [comment]
@haidarsalim - could you try to use the Inspector Tools - https://docs.inspireui.com/fluxstore/customization/#1-how-to-customize-any-ui-from-app - thanks

**Comment by haidarsalim** [comment]
I need a detailed answer for each unit separately

**Comment by minhcasi** [comment]
@haidarsalim - noted

@dttrung26 - please help to investigate and provide more detail

**Comment by dttrung26** [comment]
Hi @haidarsalim , please download attached files and replace as following: 
- horizontal_list_items.dart in /lib/widgets/blog/horizontal 
- login.dart in /lib/screens
- menu.dart in /lib/
- settings.dart in /lib/screens 

[ticket_support#2622.zip](https://github.com/inspireui/support/files/4461702/ticket_support.2622.zip)

Then follow those instructions to customize those codes: 
1/ I already comment out those layouts you don't need. However, I highly recommend you still keep chat button as floating button because it requires multiple choice to enter chat section which a simple `ListTile` couldn't handle. 
2/ Done in replaced file.
3/ In order to change those words, please find their place in souce code by using Inspector (https://docs.inspireui.com/fluxstore/customization/#1-how-to-customize-any-ui-from-app). After that, you can decide to hard code those text or use l10n to generate translate language. 
4/ Done in replaced file.
5/ Replaced file hides the unnecessary parts already, then customize those lines to display your desired link: 
```
  ListTile(
                  leading: const Icon(
                    Icons.pageview,
                    size: 20,
                  ),
                  title: Text("page view"),
                  onTap: () {
                    Navigator.push(
                        context,
                        MaterialPageRoute(
                            builder: (context) => WebView(
                                url: "https://inspireui.com/who-we-are",
                                title: "About Us")));
                  },
                ),
```
6/ I'm quite not sure what you meant. A little more explanation would be very appreciated sir. 
Happy coding!

**Comment by haidarsalim** [comment]
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...

Compiler message:
lib/screens/settings.dart:15:8: Error: Error when reading 'lib/screens/post_management/post_management.dart': The system cannot find the path specified.

import 'post_management/post_management.dart';
       ^
lib/screens/settings.dart:16:8: Error: Error when reading 'lib/screens/post_screen.dart': The system cannot find the file specified.

import 'post_screen.dart';
       ^
lib/menu.dart:3:8: Error: Error when reading 'lib/screens/post_screen.dart': The system cannot find the file specified.

import 'package:fstore/screens/post_screen.dart';
       ^
lib/screens/settings.dart:377:46: Error: The getter 'pageView' isn't defined for the class 'S'.
 - 'S' is from 'package:fstore/generated/l10n.dart' ('lib/generated/l10n.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'pageView'.
                            '${S.of(context).pageView.toString()}',
                                             ^^^^^^^^
lib/screens/settings.dart:390:55: Error: The method 'PostScreen' isn't defined for the class 'SettingScreenState'.
 - 'SettingScreenState' is from 'package:fstore/screens/settings.dart' ('lib/screens/settings.dart').
Try correcting the name to the name of an existing method, or defining a method named 'PostScreen'.
                                builder: (context) => PostScreen(
                                                      ^^^^^^^^^^
lib/screens/settings.dart:392:60: Error: The getter 'pageView' isn't defined for the class 'S'.
 - 'S' is from 'package:fstore/generated/l10n.dart' ('lib/generated/l10n.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'pageView'.
                                  pageTitle: S.of(context).pageView.toString(),
                                                           ^^^^^^^^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 780

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 58s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by haidarsalim** [comment]
This is what happened when I replaced the files

**Comment by haidarsalim** [comment]
![Capture](https://user-images.githubusercontent.com/54249914/79030418-81737500-7ba1-11ea-8d1a-f780a96ab33e.JPG)

**Comment by dttrung26** [comment]
Hi @haidarsalim , you can feel free to comment out those import lines. It's from the next released feature which has not ben completed yet.

**Comment by haidarsalim** [comment]
The application does not work when the error occurs

**Comment by haidarsalim** [comment]
[lib.zip](https://github.com/inspireui/support/files/4465105/lib.zip)

**Comment by dttrung26** [comment]
Replace following files as following: 
- menu.dart in /lib/
- settings.dart in /lib/screens
[ticket_support#2622.zip](https://github.com/inspireui/support/files/4468141/ticket_support.2622.zip)

Let me know it you still have any problem. 
Happy coding!

**Comment by haidarsalim** [comment]
![111111](https://user-images.githubusercontent.com/54249914/79160371-57f55c00-7de2-11ea-8896-c4de46f0fbaf.JPG)
It works fine but chatbox still exists
I want it removed to need it

**Comment by dttrung26** [comment]
Hi @haidarsalim , replacing this file into your lib/screens/ would fix that. 
[ticket_support#2622.zip](https://github.com/inspireui/support/files/4472775/ticket_support.2622.zip)
Best!

**Comment by haidarsalim** [comment]
There is an error in the file
![444](https://user-images.githubusercontent.com/54249914/79194030-7c7a2400-7e34-11ea-8799-361c41d1a6c7.JPG)

**Comment by haidarsalim** [comment]
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...

Compiler message:
lib/screens/settings.dart:15:8: Error: Error when reading 'lib/screens/post_management/post_management.dart': The system cannot find the path specified.

import 'post_management/post_management.dart';
       ^
lib/screens/settings.dart:16:8: Error: Error when reading 'lib/screens/post_screen.dart': The system cannot find the file specified.

import 'post_screen.dart';
       ^
lib/screens/settings.dart:186:55: Error: The method 'PostManagementScreen' isn't defined for the class 'SettingScreenState'.
 - 'SettingScreenState' is from 'package:fstore/screens/settings.dart' ('lib/screens/settings.dart').
Try correcting the name to the name of an existing method, or defining a method named 'PostManagementScreen'.
                                builder: (context) => PostManagementScreen(),
                                                      ^^^^^^^^^^^^^^^^^^^^
lib/screens/settings.dart:377:46: Error: The getter 'pageView' isn't defined for the class 'S'.
 - 'S' is from 'package:fstore/generated/l10n.dart' ('lib/generated/l10n.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'pageView'.
                            '${S.of(context).pageView.toString()}',
                                             ^^^^^^^^
lib/screens/settings.dart:390:55: Error: The method 'PostScreen' isn't defined for the class 'SettingScreenState'.
 - 'SettingScreenState' is from 'package:fstore/screens/settings.dart' ('lib/screens/settings.dart').
Try correcting the name to the name of an existing method, or defining a method named 'PostScreen'.
                                builder: (context) => PostScreen(
                                                      ^^^^^^^^^^
lib/screens/settings.dart:392:60: Error: The getter 'pageView' isn't defined for the class 'S'.
 - 'S' is from 'package:fstore/generated/l10n.dart' ('lib/generated/l10n.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'pageView'.
                                  pageTitle: S.of(context).pageView.toString(),
                                                           ^^^^^^^^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 780

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 9s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by dttrung26** [comment]
Hi @haidarsalim , 
I'm sorry I forgot to comment out unnecessary files, please download attached file and replace as above. Thanks.
[ticket_support#2622.zip](https://github.com/inspireui/support/files/4473618/ticket_support.2622.zip)

**Comment by haidarsalim** [comment]
> Replace following files as following:
> 
> * menu.dart in /lib/
> * settings.dart in /lib/screens
>   [ticket_support#2622.zip](https://github.com/inspireui/support/files/4468141/ticket_support.2622.zip)
> 
> Let me know it you still have any problem.
> Happy coding!

This file is working fine. I would like to remove the .box chat

**Comment by haidarsalim** [comment]
Items we have removed have returned

**Comment by haidarsalim** [comment]
![78808925-cf844f00-79ce-11ea-8617-49a97591aecc](https://user-images.githubusercontent.com/54249914/79195551-20fd6580-7e37-11ea-810c-94e8e1080158.jpg)

**Comment by haidarsalim** [comment]
![3333](https://user-images.githubusercontent.com/54249914/79197384-4dff4780-7e3a-11ea-9159-72e91fb81a18.JPG)
I learned how to fix this, thank you

**Comment by dttrung26** [comment]
Glad to hear that mate, keep going @haidarsalim  
Have a nice day :D
