### ISSUE TITLE
[Eva-Store] - Checkout Flow and Payment Issues

### ISSUE THREAD

**Issue by denny-dang** [inspireui/support#2624]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
There seems to be an issue with the checkout process. There are two flows that show up with checkout.

No shipping methods appear, and once we click the “Pay” button, the alert below pops up.

![image](https://user-images.githubusercontent.com/52182574/78843671-5679fd00-79b8-11ea-8176-30cc5e998a03.png)

Sometimes, the shipping methods do show up, and we’re not sure what triggers it and what doesn’t. In this case, the “Pay” button brings us to a blank screen that never finishes loading.

![image](https://user-images.githubusercontent.com/52182574/78843651-4530f080-79b8-11ea-9e09-2a81cd4119e5.png)

3. Proof of my purchased (required):
![image](https://user-images.githubusercontent.com/52182574/78843512-d489d400-79b7-11ea-94dc-7087d9b5c996.png)

3. Config files (required):
Config files (required):
/**

Step 3: Setting Home screen, category screen
Follow this article to use Graphql https://help.shopify.com/en/api/custom-storefronts/storefront-api/graphql
Video tutorial https://www.dropbox.com/s/m4kmp0quh8qplz3/Screen%20Recording%202018-11-05%20at%202.22.21%20PM.mov?dl=0
/
SpaceLayout: 15, // setting align right
/*
config home page show
horizontal with multi collection id or
vertical layout with latest product and first product is banner
*/
HomePage: {
Horizon: true,
PageSize: 12,
},
HorizonLayout: [
// {
// categoryId: "Z2lkOi8vc2hvcGlmeS9Db2xsZWN0aW9uLzQyMTg1ODM4MQ==",
// paging: true,
// layout: Constants.Layout.miniBanner,
// },
{
name: "Jitter-less Coffee",
categoryId: "Z2lkOi8vc2hvcGlmeS9Db2xsZWN0aW9uLzE1NDgyMTQ5Mjc4OQ==",
layout: Constants.Layout.card,
},
{
name: "Apparel & Accessories",
categoryId: "Z2lkOi8vc2hvcGlmeS9Db2xsZWN0aW9uLzE1NDgyMTM5NDQ4NQ==",
layout: Constants.Layout.twoColumn,
},
],

CategoryLayout: {
ListMode: "ListMode",
GridMode: "GridMode",
CardMode: "CardMode",
},

**Comment by minhcasi** [comment]
#2590

**Comment by denny-dang** [comment]
Where do you guys think I should start looking to fix this? Thanks!

**Comment by luyx2412** [comment]
Hi @denny-dang Can you share me AppConfig.json file? 
You can open Reactotron https://github.com/infinitered/reactotron tool to debug why the shipping method empty and webview checkout url loading forever.

Thanks

**Comment by denny-dang** [comment]
hello I emailed you the AppConfig.js file. Thanks!

**Comment by luyx2412** [comment]
Hi @denny-dang 
I just checked your AppConfig.json and everything worked normal. 
![image](https://user-images.githubusercontent.com/8909619/79062801-70248880-7cc7-11ea-94c5-66ca85db386b.png)
![image](https://user-images.githubusercontent.com/8909619/79062802-7155b580-7cc7-11ea-8269-ae04f3a2736f.png)

So can you recheck with your app?

Thanks

**Comment by denny-dang** [comment]
Hi, it's still not working on my end. I reverted back to the original evastore layout with no changes. Then, I changed the appconfig.json to what I emailed you and the config to show my products. However, the webview checkout url is still loading forever

**Comment by luyx2412** [comment]
Hi @denny-dang Can you send your project via luyxtran264@gmail.com. Let me investigate easier.

Thanks

**Comment by denny-dang** [comment]
hello I emailed you the project. Thanks!

**Comment by luyx2412** [comment]
Hi @denny-dang I just sent you the source code which fixed checkout issue.

Thanks
