### ISSUE TITLE
Search Page Shows all the products as out of stock

### ISSUE THREAD

**Issue by bilalmunir1995** [inspireui/support#2625]
![2](https://user-images.githubusercontent.com/37571277/78844137-4b59b800-7a1e-11ea-9935-825e99c0b0eb.PNG)
![3](https://user-images.githubusercontent.com/37571277/78844138-4d237b80-7a1e-11ea-9fd2-197156e77b3c.PNG)

**Comment by minhcasi** [comment]
Hi, thank you for the feedback. Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads it's used to verify your proof of purchase? 
Sorry for any inconvenience, we will reopen the ticket when it is verified, thank you!

**Comment by bilalmunir1995** [comment]
![Capture](https://user-images.githubusercontent.com/37571277/78847148-65e45f00-7a27-11ea-9b76-21efa05b12ed.PNG)

**Comment by minhcasi** [comment]
@bilalmunir1995 

The issues as clarifying from your bad rating could cause by the integration issues, we are willing to fix it for more stable, but could you help to update the rating as it will impact our business?

**Comment by bilalmunir1995** [comment]
> @bilalmunir1995
> 
> The issues as clarifying from your bad rating could cause by the integration issues, we are willing to fix it for more stable, but could you help to update the rating as it will impact our business?
> 
> It's possible to process the refund if you are not happy with the product, thank you for your understanding!

search is not working for your example at playstore i gave low rating because i believe the product is not ready to launch however i am changing it

**Comment by bilalmunir1995** [comment]
When can i expect a fix still waiting

**Comment by minhcasi** [comment]
@bilalmunir1995 - thank you for your help with the rating, please bear with us for the new version update, our team is working hard to release the new version on next couple of day - it could available on early next week, it will fix you all reporting issue - thank you!

**Comment by luyx2412** [comment]
Hi @bilalmunir1995 In `./lib/services/helper/shopify_query.dart` --> line 153 please insert `availableForSale` to fix your issues. We will update next version to fix it.

![image](https://user-images.githubusercontent.com/8909619/79465304-5c5d8700-8025-11ea-8fab-1d517c811cc1.png)

Thanks

**Comment by minhcasi** [comment]
@bilalmunir1995 - we will also upgrade new release on next 1-2 with more stable and new features upgrade - thank you!

**Comment by bilalmunir1995** [comment]
> Hi @bilalmunir1995 In `./lib/services/helper/shopify_query.dart` --> line 153 please insert `availableForSale` to fix your issues. We will update next version to fix it.
> 
> ![image](https://user-images.githubusercontent.com/8909619/79465304-5c5d8700-8025-11ea-8fab-1d517c811cc1.png)
> 
> Thanks
This solved it thanks i am having some issues other then this opening separate ticket
