### ISSUE TITLE
Evastore - Update Expo SDK 36

### ISSUE THREAD

**Issue by ramalheiro** [inspireui/support#2626]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:

Hi from April 2020, Apple Store will not allow to submit apps that use UIWebView API

"ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of new apps that use UIWebView APIs starting from April 2020"

Expo correct this issue in SDK 36.

Can we expect an update of the source code to SDK 36?

2. Screenshots issues (required):

![image](https://user-images.githubusercontent.com/15681299/78856587-8992af80-79fd-11ea-8eac-bf0b88691c79.png)

3. Proof of my purchased (required):
![image](https://user-images.githubusercontent.com/15681299/78856685-c3fc4c80-79fd-11ea-8096-6362d5e1689a.png)

3. Config files (required)

**Comment by minhcasi** [comment]
@ramalheiro - thank you for reporting, we will investigate and let you know 

@luyx2412

**Comment by luyx2412** [comment]
Hi @ramalheiro We will upgrade new version with expo 36 couple days to fix your issue.

Thanks

**Comment by ramalheiro** [comment]
Thank you. I will keep my project on hold until the next update.

**Comment by luyx2412** [comment]
We updated new version on Envato, please download latest version.

Thansk
