### ISSUE TITLE
[Fluxstore] - error when i Build and release for iOS 

### ISSUE THREAD

**Issue by limitlessfirm** [inspireui/support#2627]
1. My issue: when i Build and release for iOS i see error

2. Screenshots issues (required): 
![ios-release-002-without-001 copy](https://user-images.githubusercontent.com/59250639/78862514-d98e6800-7a37-11ea-8469-26878d346c67.jpg)

3. Proof of my purchased (required):
![screenshot](https://user-images.githubusercontent.com/59250639/78862537-e448fd00-7a37-11ea-90ff-9e0008e06f16.JPG)

3. Config files (required)

**Comment by minhcasi** [comment]
@limitlessfirm - pls double-check to run the project by following this video - https://www.youtube.com/watch?v=ReAUZDIgh2I

You can also try to clean up the cache- https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1
