### ISSUE TITLE
[my-product] - FluxStore Multivendor Splashcreen no Splashcreen no launch screen

### ISSUE THREAD

**Issue by aishema2000** [inspireui/support#2628]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:

My app is working well, I have correctly integrated my woocommerce website. But the splashscreen does not show up. It shows only white empty background before opening the app. I did research in all your documentation I don't see how to solve this. I am using a simple png image as splashsceen. Please help me. Thanks.

2. Screenshots issues (required):
Launch/splashcreen : 
![WhatsApp Image 2020-04-09 at 10 45 28](https://user-images.githubusercontent.com/15066381/78876511-bc659380-7a4f-11ea-81ed-c41c67d51d1f.jpeg)

App opens after empty / white background:
![WhatsApp Image 2020-04-09 at 10 44 49](https://user-images.githubusercontent.com/15066381/78876567-d010fa00-7a4f-11ea-878d-ef567529f5ae.jpeg)

3. Proof of my purchased (required):
![image](https://user-images.githubusercontent.com/15066381/78876659-f5056d00-7a4f-11ea-8d76-bf089a645bba.png)

3. Config files (required)
[config_FILES.zip](https://github.com/inspireui/support/files/4455238/config_FILES.zip)

**Comment by aishema2000** [comment]
Any assistance please?

**Comment by kvt0012** [comment]
Dear sir, do you do any set up on splash screen? Please tell me, thank you

**Comment by aishema2000** [comment]
Hello, I do not understand your question. What do you mean by "doing setup on splash screen" ??

What I did is to replace the original splash screen path with to my own PNG splash screen.. Please see screenshot above and the images.dart file that I sent you. Thanks

**Comment by kvt0012** [comment]
> Hello, I do not understand your question. What do you mean by "doing setup on splash screen" ??
> 
> What I did is to replace the original splash screen path with to my own PNG splash screen.. Please see screenshot above and the images.dart file that I sent you. Thanks

Sorry, sir 
I mean that do you edit any detail on splash screen code. 
I will check it if I can detect this is default error and config error, sir.  
Let's help me check your default is working or not, sir.

**Comment by kenngigz** [comment]
having same problem
