### ISSUE TITLE
[MStore MV] CAN NOT CREATE A NEW USER TO CHECK OUT

### ISSUE THREAD

**Issue by samber91** [inspireui/support#263]
purchase code ad1ac976-3e34-4e40-a473-0985df712891
![img_9325](https://user-images.githubusercontent.com/42559522/52353151-f6767800-29fb-11e9-905b-ee924128b6af.JPG)

Hi, please Look at the screenshot. when i try to sign on i get this error . how to solve it ? help thank you

**Comment by minhcasi** [comment]
Hi, just update that we received your ticket and the team will back to check on Monday (after the Tet holiday), sorry for the delay - thank you!

**Comment by thangvo9x** [comment]
Hi. Please install as guide https://inspireui.github.io/mstore-mv. And active them.
Thanks

**Comment by samber91** [comment]
I did everything said there. Nothing works!!

**Comment by thangvo9x** [comment]
Hi. Send me your admin for checking. AppConfig.json file.

**Comment by samber91** [comment]
*Get the config js on this link   :*
https://drive.google.com/open?id=1U7KmsUQChljG0PTX-R-6YtIPfEkv6Rjn

*Wordpress admin *
Direct URL: https://www.maplechap.com/wp-admin
Username: admin
Password: LWFaUypJIqAwb

**Comment by minhcasi** [comment]
@samber91  could you consider updating the rating? The is no reason for us to get your bad rating and continues to support, thanks

**Comment by samber91** [comment]
Lol. 😁. You will earn a good rating by providing a good service !  Okay ?
I don’t know why i should give you good rating if you keep ignoring your
customers

**Comment by samber91** [comment]
For the last days , you guys help me a little bit. So i will review my
rating . But , if you ignore my issues and don’t help me , i’m sorry, i
will give you bad rating again!! You are the business owner and i’m the
client . If i’m not happy with your service , i have the right to say my
opinion. Okay ?
Thanks

**Comment by samber91** [comment]
You can not force me to say i’m happy with your service when i’m not !! I’m
sorry . It does not work like that !!!!

**Comment by minhcasi** [comment]
Hey, remember that our team has been supported you during that time, it's just the willing both side, we will happy to refund to save your money & time! Thanks

**Comment by minhcasi** [comment]
Btw, we don't want a fight, as if you can see our previous support tickets - https://gyazo.com/d39c1e6845d10a1bd7e2916af940ec75 - it does not totally like your rating comment, and honestly, it is not fair 

How do you think if you update the rating again and we help to check your above issue form the maplechap website and resolves your current issues, we will priority resolve your issue on Monday?
