### ISSUE TITLE
Mstore _ Multi Vendors

### ISSUE THREAD

**Issue by T3kken** [inspireui/support#2630]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: Cebuilder and expo. The development environment is set correctly but the whole process keeps failing and it is very frustrating! I have been advised that Fluxstore Multi Vendor - Flutter E-commerce Full App is better and easy to build.

do you have a service where someone can do the whole app for me using my files and publish with my Apple dev account and android or can you offer me a reasonable price for Fluxstore Multi Vendor - Flutter E-commerce Full App instead as it is claimed to be easier.

2. Screenshots issues (required):

![SS_Cebuilder](https://user-images.githubusercontent.com/20121759/78907245-5e00db00-7a78-11ea-8e71-84433c670034.PNG)

3. Proof of my purchased (required):
![SS_Codecanyon](https://user-images.githubusercontent.com/20121759/78907622-da93b980-7a78-11ea-96bd-8b57d3b28424.PNG)

3. Config files (required)

[Config.zip](https://github.com/inspireui/support/files/4456808/Config.zip)

**Comment by minhcasi** [comment]
@T3kken - could you able to run the project from cebuilder so far?

It's also compatible with the Expo app - https://docs.inspireui.com/mstore-mv/quick-setup#manual-install-with-expo

**Comment by T3kken** [comment]
No I could not run the project from cebuilder? 

![expo](https://user-images.githubusercontent.com/20121759/78985722-6103d600-7b21-11ea-8efe-05180969dcc4.PNG)

Expo also now has this yet expo is installed.

![expo_2](https://user-images.githubusercontent.com/20121759/78985778-8690df80-7b21-11ea-9663-0e5b0955e202.PNG)

Thanks

**Comment by minhcasi** [comment]
@T3kken - there could be the permission issue that you could install expo, please try to install it manually by running 

```
npm install -g expo-cli
```

/Guide: https://docs.expo.io/versions/latest/get-started/installation/


Also, update the Cebuilder to the latest version - https://github.com/inspireui/cebuilder/releases - thank you!

**Comment by T3kken** [comment]
Hi I have done all this! 
Its just frustrating as you can see i bought this longtime ago but it keeps failing!!

**Comment by T3kken** [comment]
Hi 
just used another PC and set up the correct dev environment, Still am getting the same issue! having read comments and issues it seem Mstore MV has a number of issues, I would be happy to try Fluxstore Multi Vendor - Flutter E-commerce Full App so as to get this sorted. I don,t want for free but at least on a reasonable price! 

Can you also be a little considerate with the time it takes you to respond?

Thanks

**Comment by minhcasi** [comment]
@T3kken - we could discount 30% for your new purchase on Fluxstore MV, let us know when you start to buy so that we could update the pricing

Btw, the Mstore MV depends on Expo environment, please try your best to run the basic expo example first - http://docs.expo.io/ or https://reactnative.dev/docs/getting-started

**Comment by T3kken** [comment]
Hi I can buy now if you are ready. But no sure how you can do it. Do you want me to send you a PM?

**Comment by minhcasi** [comment]
move to email
