### ISSUE TITLE
[Fluxstore-Woo] - Issues with OnePageCheckout, CartPage, PointsAndRewards, ProductVariations

### ISSUE THREAD

**Issue by kobylogan** [inspireui/support#2631]
---------

1. My issue:

2. Screenshots issues (required):

3. Proof of my purchased (required):

3. Config files (required)

**My APP version. Fluxstore v1.6.6b. MstoreApi: v2.2.4**

**Issues**
**1A.  EnableOnePageCheckout Issue**. 
Whether I set EnableOnePageCheckout to ‘true’ or ‘false’, after clicking checkout button on cart page, the app opens my mobile website checkout page inside the in-app-browser. Is this normal behavior? Kindly advise on how to fix this.
![002](https://user-images.githubusercontent.com/43590567/78904978-da8dbc80-7a6c-11ea-9bf2-2fd648c1bbd5.jpg)

**1B Cart Page Crash Issue**. 
Part of the cart page seems to crash when you close and open app after adding a product to the cart. I get the error shown in the screenshot. The same thing happens with your app on playstore. 
To recreate error, open app, add product to cart, exit app, reopen app, go to cart page.
![001](https://user-images.githubusercontent.com/43590567/78905272-41ab7100-7a6d-11ea-97fa-15ea2f15e196.jpg)

**1C. Cannot Redeem User Points as Discount - PointsAndRewards**
Points and Rewards shows accrued user points on profile page but I have not found a way to redeem the points when placing order. i.e. use the user points to get a discount in the app. I think an option should be given on cart page to use your points for a discount. 
![003](https://user-images.githubusercontent.com/43590567/78905754-ff366400-7a6d-11ea-9c66-85e319d5b1dd.jpg)

**1D. Some Variation Options Do not appear in the app**
Take this example. Here is a cash register product on my website and how it is presented in the app. Kindly help to fix this so that variations appear. 
**WEB**
![004](https://user-images.githubusercontent.com/43590567/78907150-db741d80-7a6f-11ea-9cbe-a8bff83bdbf7.jpg)
**APP**
![005](https://user-images.githubusercontent.com/43590567/78907296-0cece900-7a70-11ea-94ec-d6238201db17.jpg)

**PROOF OF PURCHASE**
![006](https://user-images.githubusercontent.com/43590567/78908277-60ac0200-7a71-11ea-9841-e1e0c05e397e.JPG)

**Comment by minhcasi** [comment]
@kobylogan - thank you so much for detail feedback and screenshot

1A- this is normal behaviour from one-page checkout feature as it is using Webview.
1B- this bug is fixed on our latest code, it will be ready on next release
1C- @philipvu30 - please help to investigate this feature
1D- @philipvu30 - please check this issue

**Comment by philipvu30** [comment]
Hi @kobylogan ,

1C. Currently investigating.
1D. Please make sure to check these options 

![image](https://user-images.githubusercontent.com/54442328/78333379-ee8c7680-75b3-11ea-97e4-37b411a92f9d.png)

**Comment by philipvu30** [comment]
Hi,

We'll implement 1C in the future. Thanks
