### ISSUE TITLE
FluxNews

### ISSUE THREAD

**Issue by zemeister2332** [inspireui/support#2632]
why no one answered my questions.
comments are not work. 
issue: [http] #1 • POST http://redwolf.uz/wp-json/wp/v2/comments?post=576 • open
          [http] #1 • POST http://redwolf.uz/wp-json/wp/v2/comments?post=576 • request ready
          [http] #1 • POST http://redwolf.uz/wp-json/wp/v2/comments?post=576 • 401 Unauthorized
and not commented. in wordpress too not show anything
here is my old issue. if u dont help me. so say me how can i back my purchase
https://github.com/inspireui/support/issues/2617

**Comment by minhcasi** [comment]
@zemeister2332 - did you update the setting from document guide?

<img width="970" alt="Screen Shot 2020-04-10 at 09 09 08" src="https://user-images.githubusercontent.com/1459805/78955924-f21b8280-7b0a-11ea-8395-13ca755c7951.png">

**Comment by zemeister2332** [comment]
Yes here is:
<img src="https://i.ibb.co/fYBkfD3/Screen-Shot-2020-04-10-at-10-02-42-AM.png">
<img src="https://i.ibb.co/swrqV3F/Screen-Shot-2020-04-10-at-10-03-08-AM.png">
<img src="https://i.ibb.co/gWNpRmd/Screen-Shot-2020-04-10-at-10-03-37-AM.png">

**Comment by zemeister2332** [comment]
when i commented with app it say Unauthorized
<img src="https://i.ibb.co/X2JvjLG/Screen-Shot-2020-04-10-at-10-10-10-AM.png">

**Comment by zemeister2332** [comment]
I am sorry. Its finally work when i change my wordpress settings.
<img src="https://i.ibb.co/CmgXDyC/Screen-Shot-2020-04-10-at-10-19-50-AM.png">

and my finally question:
can i get my categories page like this one. i changed -> card, sideMenu, column, subCategories, animation, grid. this ones but only work card.
<img src"https://i.ibb.co/41GczLV/Screen-Shot-2020-04-10-at-10-22-54-AM.png">

**Comment by minhcasi** [comment]
@dttrung26 - pls help for checking the post comment issue, it seems working fine on Postman - https://tppr.me/tGkTp

Also, check if possible to show as other categories UI

**Comment by dttrung26** [comment]
Hi @zemeister2332 , currently Fluxnews only supports card layout for category screen. More layout might be updated in near future. 
Let me know if you still have any question.

**Comment by dttrung26** [comment]
Close due to no response from customer!
