### ISSUE TITLE
Fluxstore Multi-vendor Flutter app 

### ISSUE THREAD

**Issue by maximuskay2** [inspireui/support#2633]
Errors Generated 
1. When trying to signup from app
![Error from Registration](https://user-images.githubusercontent.com/4710692/78945481-6401b680-7a8e-11ea-8304-128d126b0221.png)

2. Error Generated when Signup with Google
![error from google signup](https://user-images.githubusercontent.com/4710692/78945505-767bf000-7a8e-11ea-9e89-2203a2044085.png)

3. Error Generated when trying to login with working user account in Wordpress
![Error from user ID login](https://user-images.githubusercontent.com/4710692/78945543-901d3780-7a8e-11ea-82b3-b5b0f9934926.png)

3. Proof of my purchased (required):

<img width="1437" alt="Screen Shot 2020-04-06 at 2 43 59 AM" src="https://user-images.githubusercontent.com/4710692/78945575-a925e880-7a8e-11ea-81e0-bd59fc881bb2.png">

**Comment by maximuskay2** [comment]
THE ISSUE HAS NOT BE SORTED OR ATTENDED TO.. CANT CREATE OR LOGIN FROM APP

**Comment by kvt0012** [comment]
Dear sir, please do step by step as our guide here 
https://docs.inspireui.com/fluxstore/woocommerce-setup/ 
https://docs.inspireui.com/fluxstore/sign-in/
and make sure that you setting our mstore api, this error raises because the app is lacking for plugin to run. 
Thank you

**Comment by maximuskay2** [comment]
I have followed all steps involved in mstore APi and woocommerce sign in
with firebase .. not error still persist

**Comment by minhcasi** [comment]
@maximuskay2 - thank you for your sharing - please help to move the conversation to this ticket #2645 - we will check and update ASAP

**Comment by walidcpu** [comment]
I have the same problem
