### ISSUE TITLE
[Fluxstore MV] - Does not go to the home page after login

### ISSUE THREAD

**Issue by aberatadiguzel** [inspireui/support#2634]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
Does not go to the home page after login. In Debug mode ** pictured, cannot exceed this area. Debug mod is disabled. There is the same problem at login with e-mail and SMS
2. Screenshots issues (required):
https://imgur.com/rfJy6j3
https://imgur.com/VPuOyMY ***

3. Proof of my purchased (required): https://imgur.com/HOxrZyA

3. Config files (required)
https://drive.google.com/open?id=1qkJUCXRJ_cRvFJD6k2pCdCWLduKDyeJ3

**Comment by kvt0012** [comment]
Dear sir, please try to press on back button to check whether your account login or not, thank you .

**Comment by aberatadiguzel** [comment]
yes, it logs in. but it remains on that page. but I realized that There is no problem with e-mail login. When activating login via SMS. both are broken

**Comment by aberatadiguzel** [comment]
In the models / user.dart file
the problem goes away when i disable the code below.

> Future saveUserToFirestore() async {
    try {
      final token = await _firebaseMessaging.getToken();
      print('token: $token');
      **await Firestore.instance
          .collection('users')
          .document(user.email)
          .setData({'deviceToken': token, "isOnline": true}, merge: true);**
      printLog("selam");
    } catch (e) {
      print(e);
    }
  }

But does this damage the structure?

**Comment by kvt0012** [comment]
I think that yes because of the await function.
