### ISSUE TITLE
Errors in fluxstore

### ISSUE THREAD

**Issue by fasttend** [inspireui/support#2636]
Please help!

1) Minimum order amount has been set in woocommerce admin but it’s not working in application.

2) Products variation not working properly. For example:

Product name "Mustard Oil" has 3 variants-
1 Litre - $100
2 Litre - $200
3 Litre - $300
If I place the order for 3 Litre, in order history its showing 3 Litre x 1 = $100

That means its showing the 1st price of the variation. Please guide me how to correct this.

3) In woocommerce I have set some zipcodes for delivery of the products. its working fine in my website. But in app it’s not working.

**Comment by minhcasi** [comment]
Hi, thank you for the feedback. Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads it's used to verify your proof of purchase? 
Sorry for any inconvenience, we will reopen the ticket when it is verified, thank you!

**Comment by fasttend** [comment]
[image: image.png]

**Comment by fasttend** [comment]
![image](https://user-images.githubusercontent.com/63434487/79039736-fc1fad00-7c00-11ea-9222-5af620be23fa.png)

**Comment by minhtruong315** [comment]
@fasttend can u send me config.dart file? I will help u check. Thanks

**Comment by fasttend** [comment]
Please find the attachment.

**Comment by minhtruong315** [comment]
I dont see config file
https://tppr.me/OkfJ2

**Comment by fasttend** [comment]
[config.dart.zip](https://github.com/inspireui/support/files/4474986/config.dart.zip)

**Comment by minhtruong315** [comment]
@fasttend I can't see the product name "Mustard Oil".

**Comment by fasttend** [comment]
please check a different product with this link
https://fasttend.com/product/tide-detergent-washing-powder/

**Comment by fasttend** [comment]
Are there any one to resolve the issue?

**Comment by fasttend** [comment]
Pathetic support

**Comment by minhtruong315** [comment]
it's working well. can u record scren?
[product.mov.zip](https://github.com/inspireui/support/files/4500938/product.mov.zip)

**Comment by fasttend** [comment]
[screen_record.zip](https://github.com/inspireui/support/files/4502064/screen_record.zip)

**Comment by fasttend** [comment]
Please also check the followings: 
1)Minimum order amount has been set in woocommerce admin but it’s not working in application.
2) In woocommerce I have set some limited zipcodes for delivery of the products. its working fine in my website. But in app it’s not working.

**Comment by swspro** [comment]
Hi @fasttend 

I am too facing the same problem 

>> Minimum order amount has been set in woocommerce admin but it’s not working in application.

>> In woocommerce I have set some limited zipcodes for delivery of the products. its working fine in my website. But in app it’s not working.

@minhcasi can you please look into it 

Sam

**Comment by minhtruong315** [comment]
@fasttend can u send me admin account via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/2636

**Comment by fasttend** [comment]
@minhtruong315 I have sent you the admin details on above email. Please check and do the needful.

**Comment by minhtruong315** [comment]
@fasttend Minimum order plugin doesn't support for Fluxstore. so it's not working

**Comment by minhtruong315** [comment]
@fasttend can u record this issue
2) In woocommerce I have set some limited zipcodes for delivery of the products. its working fine in my website. But in app it’s not working.

**Comment by fasttend** [comment]
> @fasttend Minimum order plugin doesn't support for Fluxstore. so it's not working

Then what is the solution for this?

**Comment by swspro** [comment]
@minhcasi which Plugin should we use then . Can you please recommend ?

**Comment by fasttend** [comment]
@minhtruong315 What about product variation problem which I shared in video format.

**Comment by fasttend** [comment]
@minhtruong315 Already 15 days gone. I was reported the issues 15 days before. Still I am not getting the solution.

**Comment by minhcasi** [comment]
@fasttend - could you help to update the latest code 1.6.7 on gitlab, we have fixed some issues related to the product variant

Also, the min/max product order is using for the demo https://wordpress.org/plugins/wc-min-max-quantities/ you can also use other plugins but require to change to new meta_data

**Comment by fasttend** [comment]
> @fasttend - could you help to update the latest code 1.6.7 on gitlab, we have fixed some issues related to the product variant
> 
> Also, the min/max product order is using for the demo https://wordpress.org/plugins/wc-min-max-quantities/ you can also use other plugins but require to change to new meta_data
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/72e9694271bb398c409d46af201d4b3b389219c2/68747470733a2f2f70732e772e6f72672f77632d6d696e2d6d61782d7175616e7469746965732f6173736574732f62616e6e65722d373732783235302e706e673f7265763d31393532373834">WordPress.org**[Min Max Quantities for WooCommerce](https://wordpress.org/plugins/wc-min-max-quantities/)**Description
> > Min Max Quantities for WooCommerce is the simplest WooCommerce extension to create special deals with product quantity and price.

@minhcasi Can you please help me? I have installed the plugin recommended by you. But I don't know how to add new meta data. So please help me on this.

**Comment by minhcasi** [comment]
@fasttend - could you help to share the admin login to support@inspireui.com - i will help to check the solution for this issue - thanks

**Comment by fasttend** [comment]
@minhcasi I have sent you the email. Please check and do the needful.

**Comment by minhcasi** [comment]
@fasttend - could you try the min/max quantity on this setting https://tppr.me/SsjQW - it is already integrated with the app (from 1.7.x) - thank you!

**Comment by fasttend** [comment]
@minhcasi - Please try to understand my concern. I don't want to set min/max quantity for products. I want to set minimum total cart value. I want to set minimum order total value of 500 rupees irrespective of item quantity or products.

**Comment by minhcasi** [comment]
I've got your idea - I will investigate this new feature and let you know!

**Comment by philipvu30** [comment]
Hi,

This feature will be included in the next update.
Thank you for using our product.

![Screenshot_1589277834](https://user-images.githubusercontent.com/54442328/81670951-95491a00-9472-11ea-834c-45a3f1f0fa32.png)

**Comment by fasttend** [comment]
@philipvu30 Thanks. I am waiting for the update.
