### ISSUE TITLE
FluxStore wooCommerce

### ISSUE THREAD

**Issue by KeaMengsrea** [inspireui/support#2637]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
   i can't build  for android platform. but ios working fine. *note my flutter configure is 
   correctly. 

2. Screenshots issues (required):  
![error fluxstore](https://user-images.githubusercontent.com/47241088/78954742-3ad13c80-7b07-11ea-8f1e-aa3c10ef8510.jpeg)

3. Proof of my purchased (required):
  Purchase code: verified ⭐️
![image](https://user-images.githubusercontent.com/47241088/78954913-c8149100-7b07-11ea-8eb0-ba3d138af5a8.png)

3. Config files (required)
i don't have change anything. i just download from my purchase then try to run on android 
[Archive.zip](https://github.com/inspireui/support/files/4459522/Archive.zip)

**Comment by minhcasi** [comment]
@KeaMengsrea - could you help to check this video guide on Android - https://codecanyon.net/item/fluxstore-multi-vendor-flutter-ecommerce-full-app/25013325

Also, try to clean cache could be fixed the issue - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

Let us know your checking :)

**Comment by KeaMengsrea** [comment]
Okay

**Comment by KeaMengsrea** [comment]
hello sir

**Comment by KeaMengsrea** [comment]
it's still not solve the problem.
check my flutter doctor

[image: image.png]

**Comment by minhcasi** [comment]
Sorry i paste the wrong link - https://www.youtube.com/watch?v=ReAUZDIgh2I

I will upload a new video for basic Window soon - could you able to run this example project so far - https://flutter.dev/docs/get-started/test-drive?tab=vscode ?

**Comment by KeaMengsrea** [comment]
yeah, i. can run an example of flutter project. and other project also.
except your project i can't run(android)

**Comment by KeaMengsrea** [comment]
do you have any solution. i stuck with this point. i can't move on.
deadline is coming soon :D

**Comment by minhcasi** [comment]
@KeaMengsrea - it's working fine with our testing, if you have tried to change the bundle ID, please make sure follow this guide https://docs.inspireui.com/fluxstore/delivery-android/

**Comment by KeaMengsrea** [comment]
okay, that is working now. thanks always support me

**Comment by minhcasi** [comment]
Dear @KeaMengsrea - we're glad that it help, please give us some feedback/rating to this page https://codecanyon.net/downloads if the product is helpful for your business

We are working hard to update more awesome and powerful features on the next coming version release. Let us know if you have any feedback.

Thank you very much! ❤️

**Comment by KeaMengsrea** [comment]
Hello Team

I have a problem with re-opening the app. The cart get error call salePrice
null

[image: image.png]
