### ISSUE TITLE
[Beonews Pro] - home screen not showing

### ISSUE THREAD

**Issue by HoWonJang** [inspireui/support#2639]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: I'm trying to set up a layout for my home screen, but only an empty screen appears.

2. Screenshots issues (required): https://ifh.cc/g/hHnjmo.jpg

3. Proof of my purchased (required): https://ifh.cc/g/snHoVY.png

3. Config files (required) https://drive.google.com/open?id=140Tj12dpAEqJA0zLLFBe4bEtLvOVdgA9

**Comment by luyx2412** [comment]
Hi @HoWonJang Can you share me your AppConfig.json file?

Thanks

**Comment by HoWonJang** [comment]
> Hi @HoWonJang Can you share me your AppConfig.json file?
> 
> Thanks

I've got the link above.

**Comment by HoWonJang** [comment]
I emailed it to you. Please reply after checking. Thank you.

**Comment by luyx2412** [comment]
Hi @HoWonJang I cannot see your AppConfig.json, can you share in this ticket or via luyxtran264@gmail.com?

Thanks

**Comment by HoWonJang** [comment]
This is the person who previously asked me that the home screen is not outputable. I am sending you a screenshot of the appconfig.js file. The category is 30, but why does it come out on an empty screen? Please reply. Thank you.

**Comment by HoWonJang** [comment]
> Hi @HoWonJang I cannot see your AppConfig.json, can you share in this ticket or via [luyxtran264@gmail.com](mailto:luyxtran264@gmail.com)?
> 
> Thanks
[send.zip](https://github.com/inspireui/support/files/4469956/send.zip)
![Capture](https://user-images.githubusercontent.com/49952957/79130093-5ecf9f00-7de1-11ea-8e1d-0ec70858b477.PNG)

please answer me.

1.Banner also does not output on screen even though category setting is set. What's the problem? I sent you an email and please reply as soon as possible. Thank you.

2. 

How do I get three columns instead of two columns in the posts when I enter the Categories tab?

**Comment by luyx2412** [comment]
Hi @HoWonJang I just test your AppConfig.json and the server response empty post. Can you check again your post.
![image](https://user-images.githubusercontent.com/8909619/79294109-946aaa00-7eff-11ea-8700-3806a4abb119.png)

 And You want to change in categories screen with three columns?
![image](https://user-images.githubusercontent.com/8909619/79294163-b82df000-7eff-11ea-88cc-4e4cd5f4c9f1.png)

Thanks

**Comment by HoWonJang** [comment]
이메일 을 다시 보냈습니다. 확인부탁드립니다.
[image.zip](https://github.com/inspireui/support/files/4479184/image.zip)

**Comment by HoWonJang** [comment]
Also, it does not come out when i set up the banner, such as the home screen. Please check the send.zip file and my website to solve the problem.(Please check your email.) Thank you.

**Comment by luyx2412** [comment]
https://github.com/inspireui/support/issues/2758
