### ISSUE TITLE
[Fluxstore] - 

### ISSUE THREAD

**Issue by qorane099** [inspireui/support#2640]
-1. after login email and password the app will not go to home page:

2. l did followed documentations and configured well, but sms, google login give me an error with a message "the app is not authorised to use firebase.....:

3. please note that l added google signin service file and SHA-1:
![IMG_20200402_201209](https://user-images.githubusercontent.com/39888242/78992011-f4f09480-7b57-11ea-8bb4-fca84507e560.jpg)

please l have this issue since last two weeks,

**Comment by minhtruong315** [comment]
@qorane099 can u send me full your source code via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/2640
and add this email to your firebase: minhtruong315@gmail.com

**Comment by qorane099** [comment]
Hello,

Did you receive that my above email?

I did send you the full source and also added your mail in my firebase.

Thank you, appreciated

9121948906

**Comment by minhtruong315** [comment]
@qorane099 did you add my email: minhtruong315@gmail.com to your firebase?

**Comment by qorane099** [comment]
Yes l added as editor.

9121948906

**Comment by qorane099** [comment]
Hello,

Please check if you can access the firebase and give me an update.

Appreciate your help

Thank you

9121948906

**Comment by minhtruong315** [comment]
@qorane099 change url to https to fix categories
"url": "https://zaamia.com",

**Comment by qorane099** [comment]
thank you very, l really appreciate your 5 star support, thank you again and again.

all my issue are fixed with help of explaining the root of the cause.
