### ISSUE TITLE
Fluxstore Multi-vendor 

### ISSUE THREAD

**Issue by yosefasad** [inspireui/support#2641]
Hello
How to generate Icon for favicon , Android icon ( mipmap-hdpi, drawable, ...) and IOS icon (Assets.xcassets) for Flutter

**Comment by minhcasi** [comment]
Hi, thank you for the feedback. Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads it's used to verify your proof of purchase? 
Sorry for any inconvenience, we will reopen the ticket when it is verified, thank you!

**Comment by yosefasad** [comment]
Sure sir;

<img width="1147" alt="Screen Shot 2020-04-11 at 1 59 17 PM" src="https://user-images.githubusercontent.com/23431061/79042008-c082e400-7bfc-11ea-8976-8f045766b7f9.png">

**Comment by minhcasi** [comment]
@yosefasad - pls try this script to generate the icon 
```
flutter pub run flutter_launcher_icons:main
```

We use this lib - https://pub.dev/packages/flutter_launcher_icons
