### ISSUE TITLE
rest api not working please help.

### ISSUE THREAD

**Issue by dasdev** [inspireui/support#2643]
rest api was working fine but now it's not working what is the problem am not understanding please help. 
this is my proof : 
![scrent prove](https://user-images.githubusercontent.com/34004057/79008792-c4baed00-7b7b-11ea-91a6-cc5853b9d641.png)
  please help me first as soon as possible.

**Comment by minhcasi** [comment]
@dasdev - could you attache the common and config folder here so that we could help for checking - thanks

You could also check with the Fluxbuilder http://fluxbuilder.com/

**Comment by dasdev** [comment]
i am getting this error while validation is clicked please check>

**Comment by dasdev** [comment]
i haven't updated the fluxstore multi vendor app yet. is the error
happening for that reason? but it was working fine before yesterday what
happened? suddenly kindly help me out please it's urgent.

**Comment by dasdev** [comment]
this is the folder you wanted to give:

**Comment by dasdev** [comment]
getting this error while checking rest api on fluxbuilder please help
![getting this error](https://user-images.githubusercontent.com/34004057/79035340-29f1fb00-7bdb-11ea-8dfd-2738b63629bb.jpg)

**Comment by dasdev** [comment]
https://shopzun.com/wp-json/wc/v3
rest api working fine in browser but not working in app please help.

**Comment by minhcasi** [comment]
@dasdev - try to double-check the Consume key and Secret from WooCommerce site, it may not set incorrectly!

**Comment by minhcasi** [comment]
Also, try to share your common and config here so that we could help for checking - thanks

**Comment by dasdev** [comment]
Yes I tried 100 times but didn't work I had to re make my site. I used qr
code scan but didn't work. Now I deleted my old site and now in new site
it's working fine.hope it will not have any problem again.

**Comment by minhcasi** [comment]
Let us know if you have any problem 👍

**Comment by dasdev** [comment]
Ya will but please reply me as soon as possible because little problem make
huge harm.

**Comment by minhcasi** [comment]
@dasdev - you can try to manage your local source by using Git and SourceTree - so that you could know which files have been changed - https://www.sourcetreeapp.com/ - thank you!

Also, try to download the latest 1.6.6b that release on today to fix some issue -

**Comment by dasdev** [comment]
same problem please help. rest api not working what's wrong? after reste everything it's working but after sometime getting same issue. please help me.

**Comment by dasdev** [comment]
![issuefluxbuilder](https://user-images.githubusercontent.com/34004057/80443420-cf6fd300-892c-11ea-88f9-817447ec09c1.jpg)
geting this problem what should i do? how to fix this?
