### ISSUE TITLE
BeoNews - Won't Run on iPhone 11 Plus or iPad Pro

### ISSUE THREAD

**Issue by shanenorman** [inspireui/support#2644]
![iPhone11 Pro Screenshot (Actual Device)](https://user-images.githubusercontent.com/11539085/79010833-9c99a280-7b17-11ea-9a59-2444aa9a3fae.PNG)
![iPhone11 Pro Screenshot (Actual Device) PNG](https://user-images.githubusercontent.com/11539085/79010844-a0c5c000-7b17-11ea-8263-ad6d26cb8926.png)

Please see previous open ticket for purchase substantiation. 

The JavaScript bundle for the app gets stuck at ~55% on newer devices (iPhone 11 Plus), but with the same OS (13.4) runs perfectly on iPhone 6s. The app also runs perfectly in the simulator, but get stuck on newer devices.

Attached you will find the following from the same build: 
iPhone11 Screenshot (Actual Device).PNG
iPhone11 Screenshot (Simulator).PNG

**Comment by minhcasi** [comment]
@shanenorman - please note that it could be the server issues from Expo that fetching the JS bundle, you could try to run the app on another time or build the app as Release mode

Kindly move the conversation to the same of your ticket on #2556
