### ISSUE TITLE
[fluxstore multi vendor] - register vendor

### ISSUE THREAD

**Issue by Emmarango** [inspireui/support#2645]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: 
I have missing pluging exception for Connectivity plugin on android 
2. Screenshots issues (required):
![Screenshot_20200410-050808_Fluxstore](https://user-images.githubusercontent.com/9246454/79014769-31f56080-7b31-11ea-9ece-6207671fbdf5.png)

3. Proof of my purchased (required):
![download_20200410_134211](https://user-images.githubusercontent.com/9246454/79014863-5b15f100-7b31-11ea-981e-993d7af34e22.jpg)

**Comment by maximuskay2** [comment]
This error has been generated with the following ticket ID but not resolved yet #2645 , #2667 , #2633 , .. Please  , @Emmarango @minhcasi  @philipvu30 .. look into it ... Please we are waiting

**Comment by minhcasi** [comment]
@maximuskay2 @Emmarango - thank you for your feedback - it seems the issue happy on recent update library from the window, we will check as high priority!

@philipvu30 @kvt0012

**Comment by minhcasi** [comment]
Moved from #2667 #2633 - same root cause

**Comment by philipvu30** [comment]
Hi,

I have tested our demo app and everything seems fine. My guess is you are missing some packages so please replace the file pubspec.yaml with this file.
[pubspec.zip](https://github.com/inspireui/support/files/4466070/pubspec.zip)

Thanks

**Comment by Emmarango** [comment]
I already edited the pubspec.yaml whit this, 
and run flutter clean, delete pub spec.lock, and run again

same error
![Captura de Pantalla 2020-04-12 a la(s) 3 01 11](https://user-images.githubusercontent.com/9246454/79066144-5a34aa80-7c6a-11ea-829f-245f370915eb.png)

**Comment by maximuskay2** [comment]
Same Error


 After replacing pubspec.yamlpubspec.yaml,
Flutter clean
flutter pub get
flutter run

**Comment by philipvu30** [comment]
Hi,

Please try to uninstall the app on your emulator then start again.

**Comment by MiguelHAngelH** [comment]
> Hola,
> 
> Intente desinstalar la aplicación en su emulador y luego comience nuevamente.

Good morning, I opened a ticket with the same problem but it was duplicated, I had not seen it, sorry. https://github.com/inspireui/support/issues/2667

But I want to comment that I have the same problem, followed this tutorial that was provided to me in the codecanyon comments and well nothing.
https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1
Hopefully they can solve it as soon as possible, regards.

**Comment by maximuskay2** [comment]
Hello , Thanks for your responses, I did a uninstall from emulator b4
testing but same error. Thanks

**Comment by Emmarango** [comment]
I did re-build and re-install app, same error

**Comment by minhcasi** [comment]
@maximuskay2 - @Emmarango - please help to download the latest source from Gitlab or the source 1.6.6b from the download page - thank you!

**Comment by MiguelHAngelH** [comment]
> @ maximuskay2 - @Emmarango - ayuda a descargar la última fuente de Gitlab o la fuente 1.6.6b de la página de descarga - ¡gracias!

thanks downloading the project.

**Comment by minhcasi** [comment]
I believe i could fix this issue on latest release - let us know if you have any issues, feel free to reopen the ticket :)

**Comment by maximuskay2** [comment]
@Emmarango please did the new update .. Downloaeded solve the whole issue of sign with sms and google .. I still encounter error .. pls respond

**Comment by walidcpu** [comment]
I download the latest version of the app 1-6-6b but it does not work at all 
https://imgur.com/mc1dlzb

> @Emmarango please did the new update .. Downloaeded solve the whole issue of sign with sms and google .. I still encounter error .. pls respond

**Comment by Emmarango** [comment]
all works fine for me thanks.

@maximuskay2  did you follow these steps?   https://docs.inspireui.com/fluxstore/sign-in/
android needs your sha1

**Comment by maximuskay2** [comment]
@Emmarango, I will really appreciate a little help..
I cant get this thing working.. With several tries

**Comment by walidcpu** [comment]
I download the latest version of the app 1-6-6b but it does not work at all
https://imgur.com/mc1dlzb

**Comment by walidcpu** [comment]
I download the latest version of the app 1-6-6b but it does not work at all program 
https://imgur.com/mc1dlzb
