### ISSUE TITLE
FluxListing - failed to connect full api data

### ISSUE THREAD

**Issue by eviano** [inspireui/support#2647]
1. My issue:
I am using different theme when trying to reconfigure my api, I get error connecting full api data such as categories, images, reviews/ratings, bookings, etc..
2. Screenshots issues (required):
https://prnt.sc/rx2fng
https://prnt.sc/rx2fzl
https://prnt.sc/rx2g4s
http://prnt.sc/rx2gch
http://prnt.sc/rx2ghv
3. Proof of my purchased (required):
http://prnt.sc/rx2grb
3. Config files (required)
rest api url: /rest/wp/v2/
- config.dart: https://pastebin.com/1SG7bHK5
- /models/listing.dart: https://pastebin.com/mnwXiS5R

**Comment by minhcasi** [comment]
@eviano - could i know which theme you are using for the app? So far, the app has tested with Listeo, Listingpro and MyListing 

Please note that some other theme will not work and need customize to map the correct field - we have noted the document on this guide https://docs.inspireui.com/fluxstore/listing-directory/#5-integrate-with-more-listing-themes-listable-listify-jobify

**Comment by eviano** [comment]
@minhcasi The theme I'm using is TownHub. I've tried to customize the map but I couldn't. 
Please Check my JSON: https://bit.ly/3caSA6G
and let me know what to do.

**Comment by minhcasi** [comment]
@eviano - try to update the mapping field from config.dart to match with your github - https://tppr.me/yniVG

**Comment by eviano** [comment]
Still not connecting! I followed the documents and it seems to be there is other configurations as booking or gallery!

**Comment by eviano** [comment]
Help, Anyone?!

**Comment by philipvu30** [comment]
Hi,

It seems you bought the wrong app for your site. FluxListing only supports My Listing/Listeo/ListingPro theme. Are you sure it is the correct theme?

**Comment by eviano** [comment]
Is there is any chance to configure the app to work with my theme?
