### ISSUE TITLE
Fluxstore Pro- duplicate same product in load product and load order list 

### ISSUE THREAD

**Issue by Ghadawi** [inspireui/support#2649]
i am using magento 2 i have the following issues:
1-  i have one product in the category if i load the product list page it duplicate same product also same problem when view order list if refresh it keep load and duplicate the order

2- problem 2 review product not display in magento 2

3- problem 3 checkout page not working in magento 2

4-  some filed are not required in address such as postcode

**Comment by Ghadawi** [comment]
I try to update setting using Android Studio  and remove app and build again but keep old setting how to solve this issue?

**Comment by minhcasi** [comment]
Hi, thank you for the feedback. Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads it's used to verify your proof of purchase? 
Sorry for any inconvenience, we will reopen the ticket when it is verified, thank you!

**Comment by Ghadawi** [comment]
https://drive.google.com/file/d/1xudQSO3aup8Gu4KPaz2RkYdgrVxyNFbS/view?usp=sharing

please find screenshot of the purchase product

**Comment by minhtruong315** [comment]
@Ghadawi can u record screen your issues and send me config.dart file? Thanks

**Comment by Ghadawi** [comment]
export 'config/advertise.dart';
export 'config/general.dart';
export 'config/onboarding.dart';
export 'config/payments.dart';
export 'config/products.dart';
export 'config/smartchat.dart';


/// Server config demo for WooCommerce

const serverConfig = {
  "type": "magento",
  "url": "https://magento-392124-1233941.cloudwaysapps.com",
  "accessToken": "j4faiasmq6dwcftzxf5q7el0xnvdnft7",
  "blog": "http://demo.mstore.io",
  "forgetPassword": "https://magento-392124-1233941.cloudwaysapps.com/customer/account/forgotpassword"
};

**Comment by Ghadawi** [comment]
https://drive.google.com/open?id=1kEur9KB1zGUFk0_iwPT6dDXGZFzpcx_t

find video record for product page and order the problem when reload the page it duplicate the order or product

**Comment by Ghadawi** [comment]
for  problem 3 checkout page not working in magento 2 it works after i run flutter run
zip code is not required and other filed in the address how can i change them?

**Comment by Ghadawi** [comment]
https://drive.google.com/file/d/1ooDDjq7pDOzV1q7PNbaiTBxvq3sOzLKd/view?usp=sharing
https://drive.google.com/file/d/1bRRrbtrLv4jgM3iX_-nUZpyY4Y3FcT-Q/view?usp=sharing

i have problem i try change slider in home page from local assets but doesn't change
and run this command flutter clean && flutter run --release 
the icon dodent display as attched link

please help to solve the icon problem and how can i change slides from assets?

**Comment by Ghadawi** [comment]
please find this problem in layout 
https://drive.google.com/file/d/1Zr3U2_ZJXPeo7ovXoU_sSPuDLkMeKCpv/view?usp=sharing

**Comment by taryaalo** [comment]
same on me in issue 1

**Comment by minhtruong315** [comment]
@Ghadawi can u send me models folder? I will help you fix issues

**Comment by Ghadawi** [comment]
@minhtruong315  please find models folder here:
https://drive.google.com/file/d/1LRaDhVxeR2b0VnEu_GMgic_RRGfJW_r5/view?usp=sharing

**Comment by minhtruong315** [comment]
@Ghadawi replace product and order model to fix duplicate issue
[Archive.zip](https://github.com/inspireui/support/files/4479018/Archive.zip)

**Comment by Ghadawi** [comment]
Thanks  @minhtruong315

how about other issues please help me to fix them such as :
1- view cart page if product name more than 3 lines display error "Bottom Overflowed by 19 Pixels"
https://drive.google.com/file/d/1Zr3U2_ZJXPeo7ovXoU_sSPuDLkMeKCpv/view

2- review product not display in product detail?

3- how to disable Zip code  from address not required?
4- how to display states in address from drop down i update state file but not display?

4- update home slide images from assets/images for home page slide error"error bad to load image"?

**Comment by minhtruong315** [comment]
@Ghadawi 
2. Review product doesn't support for magento. it only supports for woo commerce and opencart now.
4. You must edit code to support load assets for slider. Fluxstore only supports load url now.
<img width="1407" alt="Screen Shot 2020-04-16 at 7 16 44 AM" src="https://user-images.githubusercontent.com/10402500/79401190-a0637400-7fb2-11ea-9de2-aafdac9681e9.png">

**Comment by Ghadawi** [comment]
@minhtruong315  Ok noted 

please help to fix this issue as fast as possible:
1- add product to my cart and close the app and remove it from background, and open the app again but when you try to open my cart tab display this issue
https://drive.google.com/open?id=14iJ-QHEgm32VQQ2HHLLetoTs-YKeIoMo

**Comment by Ghadawi** [comment]
@minhtruong315  any update regarding my cart error?

**Comment by minhtruong315** [comment]
send me models/cart.dart file

**Comment by Ghadawi** [comment]
@minhtruong315  find cart.dart file
`import 'package:flutter/material.dart';
import 'package:localstorage/localstorage.dart';
import 'package:quiver/strings.dart';
import 'package:shared_preferences/shared_preferences.dart';

import '../common/config.dart';
import '../common/constants.dart';
import '../common/tools.dart';
import '../models/address.dart';
import '../models/coupon.dart';
import '../models/payment_method.dart';
import '../models/product.dart';
import '../models/shipping_method.dart';
import '../models/user.dart';
import '../services/index.dart';
import 'product.dart';

class CartModel with ChangeNotifier {
  CartModel() {
    initData();
  }

  Address address;
  ShippingMethod shippingMethod;
  PaymentMethod paymentMethod;
  Coupon couponObj;
  String notes;
  String currency;
  double discountAmount = 0.0; //for magento

  // The IDs and product Object currently in the cart.
  final Map<int, Product> item = {};

  // The IDs and quantities of products currently in the cart.
  final Map<String, int> _productsInCart = {};
  Map<String, int> get productsInCart => Map.from(_productsInCart);

  // The IDs and product variation of products currently in the cart.
  final Map<String, ProductVariation> _productVariationInCart = {};
  Map<String, ProductVariation> get productVariationInCart =>
      Map.from(_productVariationInCart);

  //This is used for magento
  //The IDs and product sku of products currently in the cart.
  final Map<String, String> _productSkuInCart = {};
  Map<String, String> get productSkuInCart => Map.from(_productSkuInCart);

  int get totalCartQuantity => _productsInCart.values.fold(0, (v, e) => v + e);

  double getSubTotal() {
    return _productsInCart.keys.fold(0.0, (sum, key) {
      if (_productVariationInCart[key] != null &&
          _productVariationInCart[key].price != null &&
          _productVariationInCart[key].price.isNotEmpty) {
        return sum +
            double.parse(_productVariationInCart[key].price) *
                _productsInCart[key];
      } else {
        var productId;
        if (key.contains("-")) {
          productId = int.parse(key.split("-")[0]);
        } else {
          productId = int.parse(key);
        }
        String price =
            Tools.getPriceProductValue(item[productId], currency, onSale: true);
        if (price.isNotEmpty) {
          return sum + double.parse(price) * _productsInCart[key];
        }
        return sum;
      }
    });
  }

  double getItemTotal({Product product, int quantity = 1}) {
    double subtotal = double.parse(product.price) * quantity;
    print('getItemTotal $subtotal');
    if (serverConfig['type'] == "magento" && discountAmount > 0) {
      return subtotal - discountAmount;
    } else {
      if (couponObj != null) {
        if (couponObj.discountType == "percent") {
          return subtotal - subtotal * couponObj.amount / 100;
        } else {
          return subtotal - (couponObj.amount * quantity);
        }
      } else {
        return subtotal;
      }
    }
  }

  String getCoupon() {
    if (serverConfig['type'] == "magento" && discountAmount > 0) {
      return "-" +
          Tools.getCurrecyFormatted(discountAmount, currency: currency);
    } else {
      if (couponObj != null) {
        if (couponObj.discountType == "percent") {
          return "-${couponObj.amount}%";
        } else {
          return "-" +
              Tools.getCurrecyFormatted(couponObj.amount * totalCartQuantity,
                  currency: currency);
        }
      } else {
        return "";
      }
    }
  }

  double getTotal() {
    double subtotal = getSubTotal();

    if (serverConfig['type'] == "magento" && discountAmount > 0) {
      subtotal -= discountAmount;
    } else {
      if (couponObj != null) {
        if (couponObj.discountType == "percent") {
          subtotal -= subtotal * couponObj.amount / 100;
        } else {
          subtotal -= (couponObj.amount * totalCartQuantity);
        }
      }
    }
    if (kPaymentConfig['EnableShipping']) {
      subtotal += getShippingCost();
    }
    return subtotal;
  }

  double getCouponCost() {
    if (serverConfig['type'] == "magento" && discountAmount > 0) {
      return discountAmount;
    } else {
      double subtotal = getSubTotal();
      if (couponObj != null) {
        if (couponObj.discountType == "percent") {
          return subtotal * couponObj.amount / 100;
        } else {
          return couponObj.amount * totalCartQuantity;
        }
      } else {
        return 0.0;
      }
    }
  }

  double getShippingCost() {
    if (shippingMethod != null && shippingMethod.cost > 0) {
      return shippingMethod.cost;
    }
    if (shippingMethod != null && isNotBlank(shippingMethod.classCost)) {
      List items = shippingMethod.classCost.split("*");
      String cost = items[0] != "[qty]" ? items[0] : items[1];
      double shippingCost =
          double.parse(cost) != null ? double.parse(cost) : 0.0;
      int count = 0;
      _productsInCart.keys.forEach((key) {
        count += _productsInCart[key];
      });
      return shippingCost * count;
    }
    return 0.0;
  }

  // Adds a product to the cart.
  String addProductToCart(
      {Product product,
      int quantity = 1,
      ProductVariation variation,
      isSaveLocal = true}) {
    String message = '';

    var key = "${product.id}";
    if (variation != null) {
      if (variation.id != null) {
        key += "-${variation.id}";
      }
      for (var attribute in variation.attributes) {
        if (attribute.id == null) {
          key += "-" + attribute.name + attribute.option;
        }
      }
    }

    //Check product's quantity before adding to cart
    int total = !_productsInCart.containsKey(key)
        ? quantity
        : _productsInCart[key] + quantity;
    int stockQuantity =
        variation == null ? product.stockQuantity : variation.stockQuantity;
    print('stock is here');
    print(product.manageStock);

    if (product.manageStock == null || !product.manageStock) {
      _productsInCart[key] = total;
    } else if (total <= stockQuantity) {
      if (product.minQuantity == null && product.maxQuantity == null) {
        _productsInCart[key] = total;
      } else if (product.minQuantity != null && product.maxQuantity == null) {
        total < product.minQuantity
            ? message = 'Minimum quantity is ${product.minQuantity}'
            : _productsInCart[key] = total;
      } else if (product.minQuantity == null && product.maxQuantity != null) {
        total > product.maxQuantity
            ? message =
                'You can only purchase ${product.maxQuantity} for this product'
            : _productsInCart[key] = total;
      } else if (product.minQuantity != null && product.maxQuantity != null) {
        if (total >= product.minQuantity && total <= product.maxQuantity) {
          _productsInCart[key] = total;
        } else {
          if (total < product.minQuantity) {
            message = 'Minimum quantity is ${product.minQuantity}';
          }
          if (total > product.maxQuantity) {
            message =
                'You can only purchase ${product.maxQuantity} for this product';
          }
        }
      }
    } else {
      message = 'Currently we only have $stockQuantity of this product';
    }

    if (isSaveLocal && message.isEmpty) {
      item[product.id] = product;
      _productVariationInCart[key] = variation;
      _productSkuInCart[key] = product.sku;
      saveCartToLocal(
          product: product, quantity: quantity, variation: variation);
    }

    notifyListeners();
    return message;
  }

  String updateQuantity(Product product, String key, int quantity) {
    String message = '';
    int total = quantity;
    ProductVariation variation;

    if (key.contains('-')) {
      variation = getProductVariationById(key);
    }
    int stockQuantity =
        variation == null ? product.stockQuantity : variation.stockQuantity;

    if (product.manageStock == null || !product.manageStock) {
      _productsInCart[key] = total;
    } else if (total <= stockQuantity) {
      if (product.minQuantity == null && product.maxQuantity == null) {
        _productsInCart[key] = total;
      } else if (product.minQuantity != null && product.maxQuantity == null) {
        total < product.minQuantity
            ? message = 'Minimum quantity is ${product.minQuantity}'
            : _productsInCart[key] = total;
      } else if (product.minQuantity == null && product.maxQuantity != null) {
        total > product.maxQuantity
            ? message =
                'You can only purchase ${product.maxQuantity} for this product'
            : _productsInCart[key] = total;
      } else if (product.minQuantity != null && product.maxQuantity != null) {
        if (total >= product.minQuantity && total <= product.maxQuantity) {
          _productsInCart[key] = total;
        } else {
          if (total < product.minQuantity) {
            message = 'Minimum quantity is ${product.minQuantity}';
          }
          if (total > product.maxQuantity) {
            message =
                'You can only purchase ${product.maxQuantity} for this product';
          }
        }
      }
    } else {
      message = 'Currently we only have $stockQuantity of this product';
    }
    if (message.isEmpty) {
      updateQuantityCartLocal(key: key, quantity: quantity);
      notifyListeners();
    }
    return message;
  }

  // Removes an item from the cart.
  void removeItemFromCart(String key) {
    if (_productsInCart.containsKey(key)) {
      _productsInCart.remove(key);
      _productVariationInCart.remove(key);
      _productSkuInCart.remove(key);
      removeProductLocal(key);
//      if (_productsInCart[key] == 1) {
//        _productsInCart.remove(key);
//        _productVariationInCart.remove(key);
//        _productSkuInCart.remove(key);
//      } else {
//        _productsInCart[key]--;
//      }
    }
    notifyListeners();
  }

  void setAddress(data) {
    address = data;
    saveShippingAddress(data);
  }

  Future getAddress() async {
    if (address == null) {
      await getShippingAddress();
    }
    return address;
  }

  void setShippingMethod(data) {
    shippingMethod = data;
  }

  void setPaymentMethod(data) {
    paymentMethod = data;
  }

  // Returns the Product instance matching the provided id.
  Product getProductById(int id) {
    return item[id];
  }

  // Returns the Product instance matching the provided id.
  ProductVariation getProductVariationById(String key) {
    return _productVariationInCart[key];
  }

  // Removes everything from the cart.
  void clearCart() {
    clearCartLocal();
    _productsInCart.clear();
    item.clear();
    _productVariationInCart.clear();
    _productSkuInCart.clear();
    shippingMethod = null;
    paymentMethod = null;
    couponObj = null;
    notes = null;
    discountAmount = 0.0;
    notifyListeners();
  }

  Future<void> initData() async {
    await getShippingAddress();
    await getCartInLocal();
    await getCurrency();
  }

  Future<void> saveShippingAddress(Address address) async {
    final LocalStorage storage = LocalStorage("fstore");
    try {
      final ready = await storage.ready;
      if (ready) {
        await storage.setItem(kLocalKey["shippingAddress"], address);
      }
    } catch (err) {
      print(err);
    }
  }

  Future getShippingAddress() async {
    final LocalStorage storage = LocalStorage("fstore");
    try {
      final ready = await storage.ready;
      if (ready) {
        final json = storage.getItem(kLocalKey["shippingAddress"]);
        if (json != null) {
          return Address.fromLocalJson(json);
        } else {
          final userJson = storage.getItem(kLocalKey["userInfo"]);
          if (userJson != null) {
            User user = await Services().getUserInfo(userJson["cookie"]);
            if (user != null) {
              user.isSocial = userJson["isSocial"] ?? false;
            } else {
              user = User.fromLocalJson(userJson);
            }
            return Address(
                firstName:
                    user.billing != null && user.billing.firstName.isNotEmpty
                        ? user.billing.firstName
                        : user.firstName,
                lastName:
                    user.billing != null && user.billing.lastName.isNotEmpty
                        ? user.billing.lastName
                        : user.lastName,
                email: user.billing != null && user.billing.email.isNotEmpty
                    ? user.billing.email
                    : user.email,
                street: user.billing != null && user.billing.address1.isNotEmpty
                    ? user.billing.address1
                    : "",
                country:
                    user.billing != null && isNotBlank(user.billing.country)
                        ? user.billing.country
                        : kPaymentConfig["DefaultCountryISOCode"],
                state: user.billing != null && user.billing.state.isNotEmpty
                    ? user.billing.state
                    : "",
                phoneNumber:
                    user.billing != null && user.billing.phone.isNotEmpty
                        ? user.billing.phone
                        : "",
                city: user.billing != null && user.billing.city.isNotEmpty
                    ? user.billing.city
                    : "",
                zipCode:
                    user.billing != null && user.billing.postCode.isNotEmpty
                        ? user.billing.postCode
                        : "");
          }
        }
      }
      return null;
    } catch (err) {
      print(err);
      return null;
    }
  }

  Future<void> saveCartToLocal({
    Product product,
    int quantity = 1,
    ProductVariation variation,
  }) async {
    final LocalStorage storage = LocalStorage("fstore");
    try {
      final ready = await storage.ready;
      if (ready) {
        List items = await storage.getItem(kLocalKey["cart"]);
        if (items != null && items.isNotEmpty) {
          items.add({
            "product": product.toJson(),
            "quantity": quantity,
            "variation": variation != null ? variation.toJson() : "null"
          });
        } else {
          items = [
            {
              "product": product.toJson(),
              "quantity": quantity,
              "variation": variation != null ? variation.toJson() : "null"
            }
          ];
        }
        await storage.setItem(kLocalKey["cart"], items);
      }
    } catch (err) {
      print(err);
    }
  }

  Future<void> updateQuantityCartLocal({String key, int quantity = 1}) async {
    final LocalStorage storage = LocalStorage("fstore");
    try {
      final ready = await storage.ready;
      if (ready) {
        List items = await storage.getItem(kLocalKey["cart"]);
        List results = [];
        if (items != null && items.isNotEmpty) {
          for (var item in items) {
            final product = Product.fromLocalJson(item["product"]);
            final ids = key.split("-");
            ProductVariation variant = item["variation"] != "null"
                ? ProductVariation.fromLocalJson(item["variation"])
                : null;
            if ((product.id == int.parse(ids[0]) && ids.length == 1) ||
                (variant != null &&
                    product.id == int.parse(ids[0]) &&
                    variant.id == int.parse(ids[1]))) {
              results.add(
                {
                  "product": product.toJson(),
                  "quantity": quantity,
                  "variation": variant
                },
              );
            } else {
              results.add(item);
            }
          }
        }
        await storage.setItem(kLocalKey["cart"], results);
      }
    } catch (err) {
      print(err);
    }
  }

  Future<void> getCartInLocal() async {
    final LocalStorage storage = LocalStorage("fstore");
    try {
      final ready = await storage.ready;
      if (ready) {
        List items = await storage.getItem(kLocalKey["cart"]);
        if (items != null && items.isNotEmpty) {
          items.forEach((item) {
            addProductToCart(
                product: Product.fromLocalJson(item["product"]),
                quantity: item["quantity"],
                variation: item["variation"] != "null"
                    ? ProductVariation.fromLocalJson(item["variation"])
                    : null,
                isSaveLocal: false);
          });
        }
      }
    } catch (err) {
      print(err);
    }
  }

  Future<void> clearCartLocal() async {
    final LocalStorage storage = LocalStorage("fstore");
    try {
      final ready = await storage.ready;
      if (ready) {
        await storage.deleteItem(kLocalKey["cart"]);
      }
    } catch (err) {
      print(err);
    }
  }

  Future<void> removeProductLocal(String key) async {
    final LocalStorage storage = LocalStorage("fstore");
    try {
      final ready = await storage.ready;
      if (ready) {
        List items = await storage.getItem(kLocalKey["cart"]);
        if (items != null && items.isNotEmpty) {
          final ids = key.split("-");
          var item = items.firstWhere(
              (item) =>
                  Product.fromLocalJson(item["product"]).id ==
                  int.parse(ids[0]),
              orElse: () => null);
          if (item != null) {
            items.remove(item);
//            if (item["quantity"] == 1) {
//              items.remove(item);
//            } else {
//              item["quantity"]--;
//            }
          }
          await storage.setItem(kLocalKey["cart"], items);
        }
      }
    } catch (err) {
      print(err);
    }
  }

  void setOrderNotes(String note) {
    notes = note;
    notifyListeners();
  }

  Future getCurrency() async {
    try {
      SharedPreferences prefs = await SharedPreferences.getInstance();
      currency = prefs.getString("currency") ??
          (kAdvanceConfig['DefaultCurrency'] as Map)['currency'];
    } catch (e) {
      currency = (kAdvanceConfig['DefaultCurrency'] as Map)['currency'];
    }
  }

  void changeCurrency(value) {
    currency = value;
  }
}
`

**Comment by Ghadawi** [comment]
@minhtruong315  find [cart.dart file](https://drive.google.com/file/d/1YYFkG1pP3uzCPB76bQB15TRvfzDfqm6a/view?usp=sharing)

**Comment by minhtruong315** [comment]
[cart.dart.zip](https://github.com/inspireui/support/files/4498735/cart.dart.zip)
try this file

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
