### ISSUE TITLE
[Cebuilder] Can not get categories and tags

### ISSUE THREAD

**Issue by valeopay** [inspireui/support#265]
**Mandatory Info (please complete the following information):**
 - Product: MStore Multi Vendor 
 - Your Purchased Code: c731404c-2710-472a-9f53-590e9399f964

**Describe the issues**
Installing all the wordpress plugins, and now i try to connect the setup and i have the problem "Can not get categories and tags"

**Screenshots**
https://abload.de/img/1a4jw9.jpg
https://abload.de/img/2coj3v.jpg
https://abload.de/img/3vqj6n.jpg

**Additional context**
AppConfig.json
{
  "WooCommerce": {
    "url": "https://linumbra.com",
    "consumerKey": "ck_b4eedc76dd236a78d15001321ec4c20e1e5a4196",
    "consumerSecret": "cs_39e123766f289c5508a007c8c55ffc9388766ea7"
  },
  "HorizonLayout": [
    {
      "tag": 62,
      "layout": 10
    },
    {
      "layout": 14,
      "tag": 32
    },
    {
      "name": "Feature Products",
      "featured": true,
      "image": "",
      "layout": 6
    },
    {
      "name": "On Sale Products",
      "onSale": true,
      "image": "",
      "layout": 2
    },
    {
      "name": "Electronics",
      "category": 35,
      "image": "",
      "layout": 8
    },
    {
      "name": "Digital",
      "category": 34,
      "image": "",
      "layout": 1
    }
  ],
  "MainColor": "#71BF44"
}

**Comment by minhcasi** [comment]
Hi, just update that we received your ticket and the team will back to check on Monday (after the Tet holiday), sorry for the delay - thank you!

**Comment by minhtruong315** [comment]
Hi @valeopay , I checked your config, Consumer Secret is invalid. pls check consumerKey and consumerSecret again

**Comment by valeopay** [comment]
@minhtruong315 where i can find the correct Secret code?

**Comment by minhtruong315** [comment]
Hi @valeopay, Pls enable WooCommerce Api and generate keys by this link
https://docs.woocommerce.com/document/woocommerce-rest-api/
