### ISSUE TITLE
[Fluxstore Pro] 

### ISSUE THREAD

**Issue by enamn** [inspireui/support#2651]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
I 've some issue in app , the app work fine in ios , But in android Image in categories tap not loaded , dark mode in android not working , and web view in about page not loaded . even all this issue work fine in ios , "I work with open cart back end "
2. Screenshots issues (required):

3. Proof of my purchased (required):
![WhatsApp Image 2020-04-09 at 10 46 33 PM](https://user-images.githubusercontent.com/27276716/79037962-3deb2c00-7bde-11ea-814e-65c2ef41097e.jpeg)

3. Config files (required)

**Comment by minhtruong315** [comment]
@enamn can u record screen and send me config.dart file? I will help u check. Thanks

**Comment by enamn** [comment]
This serren shot of android app . 
![Screenshot_1586662076](https://user-images.githubusercontent.com/27276716/79059796-dd63f980-7c86-11ea-8602-e6664aac4adf.png)
![Screenshot_1586662094](https://user-images.githubusercontent.com/27276716/79059800-dfc65380-7c86-11ea-84eb-3fb96e1e7e05.png)
![Screenshot_1586662085](https://user-images.githubusercontent.com/27276716/79059801-e05eea00-7c86-11ea-87db-2855210fa84a.png)
[config.dart.zip](https://github.com/inspireui/support/files/4465802/config.dart.zip)

**Comment by minhtruong315** [comment]
@enamn it's showing category image. https://tppr.me/t2l0i
can u send me full source code via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/2651

**Comment by enamn** [comment]
I told you than the problem in android only not in ios , I send you android  secreenshot , you try in ios ! 
That my peoplem. All issues above is in android only. Image , load webview , darkmode not working in android

**Comment by minhtruong315** [comment]
<img width="537" alt="Screen Shot 2020-04-15 at 10 26 58 AM" src="https://user-images.githubusercontent.com/10402500/79295738-a9493c80-7f03-11ea-997a-d188416133e4.png">

**Comment by minhtruong315** [comment]
<img width="535" alt="Screen Shot 2020-04-15 at 10 27 38 AM" src="https://user-images.githubusercontent.com/10402500/79295772-c0882a00-7f03-11ea-8465-47123374aad5.png">

**Comment by minhtruong315** [comment]
<img width="528" alt="Screen Shot 2020-04-15 at 10 28 09 AM" src="https://user-images.githubusercontent.com/10402500/79295803-d4cc2700-7f03-11ea-9fd7-92296aa3fa3f.png">

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
