### ISSUE TITLE
Firebase Auth Creating new user with phone number instead of fetching user from Wordpress database.

### ISSUE THREAD

**Issue by Varun24041993** [inspireui/support#2653]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
Hi I was able to setup login with SMS using firebase Auth configuration. Now when I try to login via SMS. I successfully receive the code (I already created a new user in Wordpress and given the mobile number as billing_phone in the database for authentication) and after verifying the firebase will create a new user with username as phone number from which I tried to login in. The process should be first app has to verify whether the phone number exist in the Wordpress database (billing_phone on the database) and if it exist then only I will get verification code and then the particular user from the database will be logged in. But now when I try to login via SMS it won't check if the user exist in the Wordpress database, I will always send verification code to every number I type in it and then it will automatically create a new user with the username as phone number. 

2. Screenshots issues (required):
![error_screenshot](https://user-images.githubusercontent.com/56767455/79040601-35f3b200-7c07-11ea-8720-a8ead3ff1523.png)

3. Proof of my purchased (required):
![codecanyon_purchase_proof](https://user-images.githubusercontent.com/56767455/79040607-3db35680-7c07-11ea-861e-d8530f0ec879.png)

3. Config files (required)

**Comment by minhcasi** [comment]
@Varun24041993 - the app is not smart enough to link the new SMS mobile login to existing billing_phone from other user - we will investigate the solution to show the message link to existing account 

- update ticket as 'Feature Request' thank you!

**Comment by minhcasi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Link SMS Login user to exist user who have same mobile_billing](https://trello.com/c/Tl75ylEs/28-link-sms-login-user-to-exist-user-who-have-same-mobilebilling)

**Comment by minhcasi** [comment]
moved to backlog
