### ISSUE TITLE
Products duplicate on refresh

### ISSUE THREAD

**Issue by redamakarem** [inspireui/support#2654]
When I am looking at a list of products and i scroll down, the products get duplicated.
Video recording of the issue: https://1drv.ms/v/s!AqEGAOzrhjidgc9R5q4hpAct2ijteg?e=hrNttB
Thanks
@trunghieuvn

**Comment by trunghieuvn** [comment]
Hi @redamakarem  , this problem may be due to something wrong in your source code, please add me to the gitlab / github repo or send your source code to me. So I can check and help you solve this problem as quickly as possible. Thanks.

My email / gitlab / github: hieu.trantrung1204@gmail.com

**Comment by redamakarem** [comment]
Hello, 
The source code has not been altered. Also, other users that bought the products are experiencing the same issue.
I have created a repo and added you as a collaborator
Thanks

**Comment by awwam** [comment]
> Hello,
> The source code has not been altered. Also, other users that bought the products are experiencing the same issue.
> I have created a repo and added you as a collaborator
> Thanks

Im also having the same issue. The products list is fetching again and again as i load more products. 
No code is changed on the category page.

**Comment by taryaalo** [comment]
i also have this issue on product and order history

**Comment by sodhanii** [comment]
Its a small hack.

Change getProductsList method of product model, and loadMore method of Order model.


[order.dart.txt](https://github.com/inspireui/support/files/4472449/order.dart.txt)
[product.dart.txt](https://github.com/inspireui/support/files/4472450/product.dart.txt)

**Comment by minhcasi** [comment]
@trunghieuvn - please help to review above sharing from Sodhanii and fix these issues if you could reproduce on latest source - thanks

**Comment by trunghieuvn** [comment]
hi @redamakarem 
Sorry, I could not reproduce this error. I have checked on the latest FluxStore source but still cannot reproduce the error. 
I did not find the source code the last time you emailed me, there must be an error. 
Please send me the source code here http://verify.inspireui.com/
