### ISSUE TITLE
[my-product] - FluxStore Listing

### ISSUE THREAD

**Issue by oliet333** [inspireui/support#2655]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: Hello

I am trying to setup the Listing app, i have an issue here

Step 3: Setup Listing website After configuring your website with the above plugins, it’s time to connect it to the Fluxstore Listing app. Open lib/common/config.dart and change the url, consumerKey and consumerSecret from serverConfig section to your own website which has the API set:
I dont have lib/common/config.dart file in Android Studio There is only main.dart file in the Lib folder

How can I fix it?

Thanks

2. Screenshots issues (required): 

3. Proof of my purchased (required):

3. Config files (required)

**Comment by oliet333** [comment]
![Снимок экрана 2020-04-11 в 14 57 13](https://user-images.githubusercontent.com/63500634/79042987-d09ec180-7c04-11ea-81a3-f57f22a6487c.png)

**Comment by oliet333** [comment]
![Снимок экрана 2020-04-11 в 14 58 39](https://user-images.githubusercontent.com/63500634/79043005-f5933480-7c04-11ea-902e-ca3fa783fd79.png)

**Comment by minhcasi** [comment]
@oliet333 - it seems there is some missing plugin on Android Studio - https://www.youtube.com/watch?v=ReAUZDIgh2I - please help for checking this video guide

**Comment by oliet333** [comment]
Hello, thanks for the answer

I downloaded Fluxstore Listing file from ThemeForest, there are fewer items in Source folder that in the "Flutter Basic Installation on Mac OS" video at 35 min
I dont have pubspec file 
I add my screenshot
Thanks
![Снимок экрана 2020-04-13 в 17 58 45](https://user-images.githubusercontent.com/63500634/79131639-958dc100-7db1-11ea-9308-bc1b8cfcf8fe.png)

**Comment by minhcasi** [comment]
Hi, pls check this file 

<img width="770" alt="Screen Shot 2020-04-14 at 9 01 08 AM" src="https://user-images.githubusercontent.com/1459805/79178186-bea06700-7e2e-11ea-9a7e-4e0f1d2bea1a.png">
