### ISSUE TITLE
Fluxstore WooCommerce

### ISSUE THREAD

**Issue by saber93** [inspireui/support#2656]
whenever I restart the project the products in cart widget not loaded because of fetching price response
![Screen Shot 2020-04-07 at 1 02 56 PM](https://user-images.githubusercontent.com/45682263/79043341-af8f9e00-7c0f-11ea-9b46-2eb76ca3e579.png)
![Screen Shot 2020-04-12 at 10 13 12 AM](https://user-images.githubusercontent.com/45682263/79061942-7a825a80-7ca6-11ea-90ee-939dd9085e38.png)

**Comment by minhcasi** [comment]
Hi, thank you for the feedback. Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads it's used to verify your proof of purchase? 
Sorry for any inconvenience, we will reopen the ticket when it is verified, thank you!

**Comment by saber93** [comment]
While I'm working on the project, added some products to the bag and every hot restart it gives me this error regarding to price, however this error don't happened before this code update, while I'm using the same website and the same plugins no changes

**Comment by minhcasi** [comment]
@saber93 - please fix by following this ticket https://github.com/inspireui/support/issues/2615 - there is the cart patching file could fix this issue

**Comment by minhcasi** [comment]
Also, download fluxstore MV 1.6.6b if you are using this product - thank you!
