### ISSUE TITLE
[FluxNews] - Can't run the project becouse of errors

### ISSUE THREAD

**Issue by jamesmendez** [inspireui/support#2657]
1. My issue:
Hi, this is my previous issue with the app https://github.com/inspireui/support/issues/2621. dttrung26 closed it but after i closed android studio and re-opened it after some hours i was not able to run the app anymore becouse of console errors.

2. Screenshots issues (required):
<img width="1428" alt="Screen Shot 2020-04-11 at 2 22 38 PM" src="https://user-images.githubusercontent.com/63358368/79043601-671cb400-7c00-11ea-9085-132d0062ebaf.png">
<img width="1425" alt="Screen Shot 2020-04-11 at 2 22 45 PM" src="https://user-images.githubusercontent.com/63358368/79043603-6ab03b00-7c00-11ea-8886-b3f03e139f75.png">
<img width="1432" alt="Screen Shot 2020-04-11 at 2 22 49 PM" src="https://user-images.githubusercontent.com/63358368/79043604-6be16800-7c00-11ea-9334-c6920a82c37e.png">

3. Proof of my purchased (required):
<img width="848" alt="purchase-confirm" src="https://user-images.githubusercontent.com/63358368/79043349-f5903600-7bfe-11ea-8069-cbbc73d01cb8.png">

3. Config files (required)
[common.zip](https://github.com/inspireui/support/files/4464577/common.zip)

**Comment by dttrung26** [comment]
Noted checking.

**Comment by dttrung26** [comment]
Support via skype!
