### ISSUE TITLE
[listapp] - Problems with expo. TypeError: undefined is not an object (evaluating category image)

### ISSUE THREAD

**Issue by dhruva7782** [inspireui/support#266]
**Required Info (please complete the following information):**
 - Product: [ListApp]
 - Your Purchased Code: [0a72ecc4-202a-4bfb-8528-ff0a87e54084]
(we may not reply if you are not our customer)

**Describe the bug**
Hello i am unable to get categories working in expo. All the options are working fine, but when clicked on categories in the bottom bar -  i get the error
![listapp error](https://user-images.githubusercontent.com/45306365/52408902-f5c40b80-2af9-11e9-9d93-98ae46391b66.png)
I have attached the screenshot and listify.js, Please help 

Thanks in advance

**Additional context**
Add any other detail logs about the problem here.

![listapp error](https://user-images.githubusercontent.com/45306365/52408987-2dcb4e80-2afa-11e9-9dde-cb508ad0ae4d.png)
[Listify.zip](https://github.com/inspireui/support/files/2840563/Listify.zip)

**Comment by minhcasi** [comment]
Hi, just update that we received your ticket and the team will back to check on Monday (after the Tet holiday), sorry for the delay - thank you!

**Comment by dhruva7782** [comment]
Hello,

Any update on the issue please?

Regards,
Dhruva

**Comment by thangvo9x** [comment]
Hi. Send me your AppConfig.json file to email thang@inspireui.com with a subject is #266. Thanks

**Comment by thangvo9x** [comment]
Hi. I noted your issue here. Please refer 
https://github.com/inspireui/support/issues/184#issuecomment-462589678
