### ISSUE TITLE
[Fluxstore-pro] - Cart and checkout issue  

### ISSUE THREAD

**Issue by MarioMSamy** [inspireui/support#2660]
1. My issue: 
Please note that there’s a problem in the cart after the last update. When does this problem start? Put something in the cart, close the app and start it again. nothing in cart now.

2. Proof of my purchased (required):
![Untitled](https://user-images.githubusercontent.com/16023864/79047422-b077fe00-7c16-11ea-88dc-b2b4129f467a.png)

**Comment by trunghieuvn** [comment]
Hi @MarioMSamy  , please provide me your config and common folder, I will help you solve this problem quickly. Thanks.
