### ISSUE TITLE
[FluxNews] - Invalid Argument in related_blogs.dart ("Things You Might Love") 

### ISSUE THREAD

**Issue by ernandozatariano** [inspireui/support#2662]
1. Hi, any solution for this error in my FluxNews app?

Invalid argument(s)
The relevant error-causing widget was: 
  BlogItem file:///C:/Dev/AndroidStudioProjects/euarquiteto2.1/source/lib/widgets/blog/detailed_blog/related_blogs.dart:126:40

2. Screenshot:

![error](https://user-images.githubusercontent.com/63005352/79050045-caf1ad80-7bfd-11ea-96b6-7cbe4cc63f5f.jpg)

3. Proof of my purchased:

![codecanyon](https://user-images.githubusercontent.com/63005352/79050078-faa0b580-7bfd-11ea-8022-9cae03db7b2a.jpg)

Tks again!

**Comment by dttrung26** [comment]
Hi @ernandozatariano , please leave me your /lib/common folder for checking. Nice day!

**Comment by ernandozatariano** [comment]
Hi! Tks again!!!

[common.zip](https://github.com/inspireui/support/files/4469493/common.zip)

**Comment by dttrung26** [comment]
Hi @ernandozatariano , could you point out exactly at which blog / category this related blogs layout error appear? Because so far so good, things still run fine on your site as I checked.

**Comment by ernandozatariano** [comment]
Hi, the error appear in all categories. I make a screencast from android studio to show you whats happen ;)

[screencast.zip](https://github.com/inspireui/support/files/4477020/screencast.zip)

**Comment by dttrung26** [comment]
Hi @ernandozatariano , please send me your /lib/widgets/blog/detailed_blog/related_blogs.dart and /lib/common/tools.dart?

**Comment by ernandozatariano** [comment]
Ok! Tks!
[related_blogs.zip](https://github.com/inspireui/support/files/4481057/related_blogs.zip)

**Comment by dttrung26** [comment]
Hi @ernandozatariano , could you leave me your skype or add me via skype: dttrung.ityu?

**Comment by ernandozatariano** [comment]
Tks for help. Maybe, for now, i just hide the related posts and the comments option.
how can i do?

![screen](https://user-images.githubusercontent.com/63005352/79506884-1eecff80-800d-11ea-87ab-200891576be2.jpg)

**Comment by dttrung26** [comment]
Hi @ernandozatariano ,
hope this helps. Let me know if you still have any question!
[ticket_support#2662.zip](https://github.com/inspireui/support/files/4490643/ticket_support.2662.zip)

**Comment by ernandozatariano** [comment]
tks so much, this worked for me! But now i have just one more problem: the post date appear on the title line. It should be below the title line, like in your demo app. Its possible?

![Sem título](https://user-images.githubusercontent.com/63005352/79572505-70d86880-8093-11ea-8c10-a5f2534f421d.jpg)

**Comment by minhcasi** [comment]
@ernandozatariano - you can try to add new Text widget with smaller font-size below the Title to fix the issue - thanks
