### ISSUE TITLE
Fluxstore Multi Vendor - Flutter E-commerce Full App 

### ISSUE THREAD

**Issue by abedfatafta** [inspireui/support#2663]
---------

1. My issue:
when we access the category sections  ,vendor stores show white screen under android , 
and undere  IOS we got the following error  and didn't show store images 
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: Exception: عذرًا، غير مسموح لك بفعل هذا.
#0      WCFMApi.getProductsByStore (package:fstore/services/wcfm.dart:113:9)
<asynchronous suspension>
#1      Services.getProductsByStore (package:fstore/services/index.dart:396:25)
<asynchronous suspension>
#2      _ProductListState.getProducts (package:fstore/vendor/store_detail/products.dart:43:12)
#3      _ProductListState.afterFirstLayout (package:fstore/vendor/store_detail/products.dart:33:5)
#4      AfterLayoutMixin.initState.<anonymous closure> (package:after_layout/after_layout.dart:10:38)
#5      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
#6      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1049:9)
#7      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:957:5)
#8      _rootRun (dart:async/zone.dart:1126:13)
#9      _CustomZone.run (dart:async/zone.dart:1023:19)
#10<…>

2. Screenshots issues (required):
![image](https://user-images.githubusercontent.com/16276919/79050424-95b38280-7c32-11ea-9536-e1cd48696551.png)

3. Proof of my purchased (required):
https://user-images.githubusercontent.com/16276919/77213700-71252880-6b14-11ea-8620-da09cf195cad.png
3. Config files (required)
const serverConfig = {
  "type": "wcfm",
  "url": "https://www.salla.ps",
  "consumerKey": "***",
  "consumerSecret": "***",
  "blog": "https://www.salla.ps",
  "forgetPassword":
  "https://www.salla.ps/my-account/lost-password/",
  "username": "admin",
  "password": "*******"
};

**Comment by abedfatafta** [comment]
another problem login not working , 
i already fixed jwt settings , and its login else where but 
response that we got 
/api/flutter_user/generate_auth_cookie
![image](https://user-images.githubusercontent.com/16276919/79053356-5e9a9c80-7c45-11ea-9b98-9d2d65968aa1.png)

**Comment by abedfatafta** [comment]
add product through exception on both IOS android 
![image](https://user-images.githubusercontent.com/16276919/79053799-a66ef300-7c48-11ea-8c39-b17154175a9f.png)

**Comment by minhcasi** [comment]
Hi, thank you for the feedback. Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads it's used to verify your proof of purchase? 
Sorry for any inconvenience, we will reopen the ticket when it is verified, thank you!

**Comment by minhcasi** [comment]
no worries - got the info from your previous ticket

@minhtruong315 - please help for checking

**Comment by minhtruong315** [comment]
@abedfatafta send me full source code via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/2663

**Comment by abedfatafta** [comment]
@minhtruong315 
thanks for your response its only the code i have downloaded , no customization yet ,
i just now sent you config file with realtime user and password  so just use them with the original source code.

**Comment by abedfatafta** [comment]
when run the app with debug in splash screen hang and the exception  raised ( MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)
i see this solution but i don't know how to implement hhhh 
https://stackoverflow.com/questions/44357053/flutter-test-missingpluginexception/44360235

**Comment by minhtruong315** [comment]
@abedfatafta I can get categories from your website https://tppr.me/yDN1N
rest api is not working on your website, I can't call any api. Please check

**Comment by abedfatafta** [comment]
Dear i stop the api . Because i re enabled the caching
The problem in stores listing
Even in your  config with last version


-- 
Regards


Abed Almonem Fatafta
Ttawor IT
Ramallah- Palestine
Skype: abed.fatafta
Tel-Fax:+970-2-2950842
Mobile: +970-59-9666221
http://www.ttawor.com

**Comment by abedfatafta** [comment]
> @abedfatafta I can get categories from your website https://tppr.me/yDN1N
> rest api is not working on your website, I can't call any api. Please check
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/6a932d99fb7860cd42bb88a60a745917daa5382a/68747470733a2f2f747070722e73332e616d617a6f6e6177732e636f6d2f75706c6f6164732f65356534643362616364656666363632353336623834396535313532643834392e706e67"><img alt="" height="14" src="/favicon-32x32.png"> tppr.me**[Public - Postman_2020-04-13 15-04-48](https://tppr.me/yDN1N)**

as i check the other tickets i found a solution , you have problem in new version in MainActivity.kt file 
I REPLACED it with 1.6.5 one and every thing till now fine 
i will update you for any problem

**Comment by minhtruong315** [comment]
ok. Thanks

**Comment by abedfatafta** [comment]
> ok. Thanks

you are welcome , but there is a nother bug 
not all store listed in stores screen ,its only load 10 , and nothing loaded after

**Comment by minhtruong315** [comment]
I sent you the latest updates on email. pls check

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!

**Comment by abedfatafta** [comment]
How can i read available countries , states , city from backend ?

our wordpress customized per vendor , so it return available shipping location per order based on customer from which vendors have bought

in addition i want to cancel some check out filds - like zip code

**Comment by abedfatafta** [comment]
and 
when i switched flutter to beta to include web
when run i got the following
.pub-cache/hosted/pub.dartlang.org/extended_image-0.7.2/lib/src/gesture/extended_image_slide_page_route.dart:333:9: Error: No named parameter with the name 'animation'.
animation: animation,
