### ISSUE TITLE
[Fluxstore] -Customize left menu side 

### ISSUE THREAD

**Issue by limitlessfirm** [inspireui/support#2666]
1. My issue: how i can add item in left menu side and when i press on it go to page in my website 

2. Screenshots issues (required): 
![top-menu-2](https://user-images.githubusercontent.com/59250639/79053555-93efbc00-7c3e-11ea-9991-f13ec1a9f6b6.JPG)

3. Proof of my purchased (required):
![screenshot](https://user-images.githubusercontent.com/59250639/79053566-a9fd7c80-7c3e-11ea-84f6-bef7d9f12db1.JPG)

3. Config files (required)

**Comment by minhcasi** [comment]
@dttrung26 - please suggest the solution and also update document for this new PostScreen feature - thank you!

**Comment by limitlessfirm** [comment]
![Capture](https://user-images.githubusercontent.com/59250639/79072841-90fad700-7ce3-11ea-955f-8bc96973a59e.JPG)

I want to add link in this menu  and when i press on it go to page in my website like (about us) link

**Comment by dttrung26** [comment]
Hi @limitlessfirm , 
please add those scripts just under column inside SingleChildScrollView and customize to meet your need in /lib/menu.dart. Permanent solution will be provided in the next patch including document. 

```
    ListTile(
                  leading: const Icon(
                    Icons.pageview,
                    size: 20,
                  ),
                  title: Text("page view"),
                  onTap: () {
                    Navigator.push(
                        context,
                        MaterialPageRoute(
                            builder: (context) => WebView(
                                url: "https://inspireui.com/who-we-are",
                                title: "About Us")));
                  },
                ),
```

Nice day!
