### ISSUE TITLE
[Fluxstore Pro] - Same Orders is loading again and again

### ISSUE THREAD

**Issue by Vetriselvan-NA** [inspireui/support#2668]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: I'm Using Opencart, In Orders screen I we scroll to bottom it is loading same orders again and again.

2. Screenshots issues (required):
![WhatsApp Image 2020-04-12 at 4 09 54 AM](https://user-images.githubusercontent.com/13717356/79056381-8d2f6c00-7c73-11ea-9a16-98b07a5296ad.jpeg)

3. Proof of my purchased (required):

3. Config files (required)
![image](https://user-images.githubusercontent.com/13717356/79056347-23af5d80-7c73-11ea-9534-dc89e0ba03ae.png)

**Comment by Vetriselvan-NA** [comment]
Product Options are not supported yet.. waiting for a very long time.

**Comment by Vetriselvan-NA** [comment]
Product Attributes is not Supported for Opencart

**Comment by Vetriselvan-NA** [comment]
When I place order it is showing Order id as 0

**Comment by minhcasi** [comment]
@Vetriselvan-NA - we are working hard to upgrade the opencart on next release version 

please move the conversation to the same ticket #2669
