### ISSUE TITLE
[Fluxstore Pro] - Opencart Major Performance issue When We open a single product

### ISSUE THREAD

**Issue by Vetriselvan-NA** [inspireui/support#2669]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:  Even If we open a single product, it is loading all products belongs to that category to 

2. Screenshots issues (required):
fetchProductsByCategory is there.. but Filter based on Product_id is not handled

3. Proof of my purchased (required):
![image](https://user-images.githubusercontent.com/13717356/79056803-aa663980-7c77-11ea-88ea-9830077f40bc.png)

3. Config files (required)

**Comment by minhtruong315** [comment]
@Vetriselvan-NA I dont understand your issue. can u record screen and send me config.dart file?

**Comment by Vetriselvan-NA** [comment]
I'm Using Opencart, In Orders screen I we scroll to bottom it is loading same orders again and again.
[2020_04_12_11_25_22.zip](https://github.com/inspireui/support/files/4465919/2020_04_12_11_25_22.zip)
![WhatsApp Image 2020-04-12 at 4 09 54 AM](https://user-images.githubusercontent.com/13717356/79061801-495b5780-7cb1-11ea-8ff0-096e43541c48.jpeg)

**Comment by Vetriselvan-NA** [comment]
For Performance issue: I can't screen shots.. Because this is a code Level issue.
When I debug I found, If we are taping a product you are calling below function
fetchProductsByCategory

When I check the API and debug. I found you are retrieving all products of its category from the server.

There is not filter based on product_id

**Comment by Vetriselvan-NA** [comment]
Fix for Orders loading again and again

  @override
  Future<List<Order>> getMyOrders({UserModel userModel, int page}) async {
    try {
      var response = await http.post(
          "$domain/index.php?route=extension/mstore/order/orders&page=$page&limit=10",
          headers: {"content-type": "application/json", "cookie": cookie});
      List<Order> list = [];
      if (response.statusCode == 200) {
        for (var item in convert.jsonDecode(response.body)["data"]) {
          list.add(Order.fromOpencartJson(item));
        }
      }
      return list;
    } catch (err) {
      rethrow;
    }
  }

**Comment by Vetriselvan-NA** [comment]
Add some products to cart. close the app and reopen the app. This is showing the following error
![image](https://user-images.githubusercontent.com/13717356/79076726-08e3f400-7d1a-11ea-9741-8705ea9a407b.png)

**Comment by minhtruong315** [comment]
@Vetriselvan-NA give me your email. I will send u updates. Thanks

**Comment by Vetriselvan-NA** [comment]
vetriselvan.na@gmail.com

**Comment by minhtruong315** [comment]
sent. please check your email

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
