### ISSUE TITLE
[ListApp] App immediately disconnects when run on browser

### ISSUE THREAD

**Issue by jane207593** [inspireui/support#267]
**Mandatory Info (please complete the following information):**
 - Product: [e.g. MStore, ListApp]
 - Your Purchased Code: [get from https://codecanyon.net/downloads]
(we may not reply if you are not our customer)

**Describe the issues**

**Screenshots**

**Additional context**
Add any other detail logs about the problem here.

**Comment by minhcasi** [comment]
Just update that we received your ticket and the team will back to check after the holiday on Monday - thank you! 

In the meantime, please share your detail screenshots

**Comment by thangvo9x** [comment]
Hi. Can you share screenshots, such as purchase code, AppConfig.js file? The team will check to help you.
Thanks

**Comment by jane207593** [comment]
[51067466-listapp-listing-directory-mobile-app-by-react-native-license.pdf](https://github.com/inspireui/support/files/2849922/51067466-listapp-listing-directory-mobile-app-by-react-native-license.pdf)

![screen shot 2019-02-11 at 10 30 44 am](https://user-images.githubusercontent.com/47419219/52547285-729c0180-2de8-11e9-8ec5-b1390915b8af.png)

**Comment by jane207593** [comment]
[cosumer key.pdf](https://github.com/inspireui/support/files/2849941/cosumer.key.pdf)
[51067466-listapp-listing-directory-mobile-app-by-react-native-license.pdf](https://github.com/inspireui/support/files/2849942/51067466-listapp-listing-directory-mobile-app-by-react-native-license.pdf)

**Comment by jane207593** [comment]
When will I get response?

**Comment by thangvo9x** [comment]
Hi. @@. You missed, you should send us your AppConfig.json with your domain to checking.
Thanks.
