### ISSUE TITLE
[Fluxstore - Woo] 1.6.6 - 1.6.6b - "Review - Cart Screen etc" Errors

### ISSUE THREAD

**Issue by sketchuprzr** [inspireui/support#2670]
I get some errors on these pages.

ScreenShots: 
![image](https://user-images.githubusercontent.com/60021696/79057226-a0d4d580-7c67-11ea-999d-6c086412ed0f.png)
![hata 1](https://user-images.githubusercontent.com/60021696/79057227-a3372f80-7c67-11ea-829a-f5f48d388d90.png)
![hata 2](https://user-images.githubusercontent.com/60021696/79057228-a4685c80-7c67-11ea-9a39-8aecbd71a1a1.png)
![image](https://user-images.githubusercontent.com/60021696/79057232-b21de200-7c67-11ea-9d3d-22511d67502b.png)

**Comment by minhcasi** [comment]
@philipvu30 - please update patching for this issue - thank you!

**Comment by Lokeswara-betha** [comment]
mi @minhcasi  , Please update your cart.dart in lib/models/cart.dart with below file.
[cart (1).zip](https://github.com/inspireui/support/files/4465880/cart.1.zip)

**Comment by sketchuprzr** [comment]
thank you for the solution. @Lokeswara-betha 

I solved all the other problems, I corrected some lines incorrectly while updating.
