### ISSUE TITLE
[MStoreAPI for Woocommerce] - After updating now i cannot use the API

### ISSUE THREAD

**Issue by lemarchexpress** [inspireui/support#2673]
---------

1. My issue:
Now i cannot login or call anything from/to the backend to the app. 

2. Screenshots issues (required):

![image](https://user-images.githubusercontent.com/63209110/79070294-29d62600-7cd5-11ea-9304-2dc683a89802.png)

3. Proof of my purchased (required):
![image](https://user-images.githubusercontent.com/63209110/79070311-496d4e80-7cd5-11ea-8b39-72894708d97c.png)

3. Config files (required)
does not apply

**Comment by lemarchexpress** [comment]
It has been solved after you have reset my purchase code in the backend.
Thanks!
![image](https://user-images.githubusercontent.com/63209110/79077239-49cf0f00-7d00-11ea-9549-5105e025684c.png)

**Comment by minhcasi** [comment]
move to #2672
