### ISSUE TITLE
i cannot run the demo woocommerce fluxstore.

### ISSUE THREAD

**Issue by andisalimudin** [inspireui/support#2674]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: i just download and extract and follow the tutorial but i still cannot run the demo apps. thanks in advance.

2. Screenshots issues (required): 
![Capture 2](https://user-images.githubusercontent.com/63330825/79071969-1648b080-7d11-11ea-8476-1c3a5ce74728.PNG)

3. Proof of my purchased (required):
![Capture](https://user-images.githubusercontent.com/63330825/79071972-1e085500-7d11-11ea-884e-2113c5f85b43.PNG)

3. Config files (required)

**Comment by minhcasi** [comment]
@andisalimudin - first you could run this script
```
flutter clean
flutter pub get
```
(this script also available from the menu of Android Studio)

Also try to use this video could be help - https://www.youtube.com/watch?v=ReAUZDIgh2I
