### ISSUE TITLE
[Flux-Pro] - How Can i change this orange photo in settings tab ?

### ISSUE THREAD

**Issue by iMezooo** [inspireui/support#2675]
i cannot found this picture asset in the project 
![settings](https://user-images.githubusercontent.com/38619185/79073635-f224a980-7ce7-11ea-9dd7-75d37879ebb1.png)

**Comment by minhcasi** [comment]
@iMezooo - pls try to use Inspector from Android studio - https://docs.inspireui.com/fluxstore/customization/#1-how-to-customize-any-ui-from-app
