### ISSUE TITLE
[Woocommerce Fluxstore] - Shipping Cost is not loading properly

### ISSUE THREAD

**Issue by lemarchexpress** [inspireui/support#2676]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:

Scenario....
I have 3 types of delivery:
1.- Always free (Pick-up at store) = 0.00€
2.- Always fixed price (Express delivery in 30 to 45min) = 3.95€
3.- Free shipping for orders over 30€
a) During morning (12:00h - 16:00h) =0.00€ if condition applies, otherwise it never appears.
b) During Afternoon (17:00h-21:00h) =0.00€ if condition applies, otherwise it never appears.

Issues found...
Case 1 has no problem it is always shown as 0.00€
Case 2 **HAS A PROBLEM** always is 0.00€ and it must be always as obtained from API (3.95€)
Case 3 i have solved in the app adjusting "Minfreeshippingcost" value. BUT I need to know if using this will afect also the case 2 which is fixed price always.

2. Screenshots issues (required):
![image](https://user-images.githubusercontent.com/63209110/79073612-da4d2580-7ce7-11ea-8641-7af7f3ffab0a.png)

![image](https://user-images.githubusercontent.com/63209110/79073760-97d81880-7ce8-11ea-860c-ade1223f7094.png)

![image](https://user-images.githubusercontent.com/63209110/79073754-8ee74700-7ce8-11ea-8a1b-50cffc43fbef.png)

3. Proof of my purchased (required):
![image](https://user-images.githubusercontent.com/63209110/79073520-6743af00-7ce7-11ea-97d8-a735b29a542b.png)

3. Config files (required)
[choose_address.zip](https://github.com/inspireui/support/files/4466648/choose_address.zip)

**Comment by minhcasi** [comment]
move to #2672
