### ISSUE TITLE
[Woocommerce Fluxstore] - Stripe does not work it showns a FATAL ERROR

### ISSUE THREAD

**Issue by lemarchexpress** [inspireui/support#2677]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
Stripe does not work it showns a FATAL ERROR
Also, paypal image is not shown and it is properly configured.

2. Screenshots issues (required):
![image](https://user-images.githubusercontent.com/63209110/79074150-0c13bb80-7ceb-11ea-99c5-82b80cc28b38.png)

3. Proof of my purchased (required):
![image](https://user-images.githubusercontent.com/63209110/79074154-146bf680-7ceb-11ea-85e5-dfdaafb70419.png)

3. Config files (required)
[stripe_fatalerror.zip](https://github.com/inspireui/support/files/4466660/stripe_fatalerror.zip)

**Comment by minhcasi** [comment]
move to #2672
