### ISSUE TITLE
RazorPay or GPay

### ISSUE THREAD

**Issue by vanlalruata** [inspireui/support#2678]
As we come across with the razorpay problem in the current version (1.6.6) is there any alternative way to implement native payment still? Say Google Pay (GPay) ?

**Comment by minhcasi** [comment]
Hi, the new version is supported via WebView combine with Native (https://razorpay.com/docs/payment-gateway/flutter-integration/), you can try to enable the Razopay and run via Webview

**Comment by vanlalruata** [comment]
RazorPay had already release stable version for RazorPay. Hopefully we could access the RazorPay Native Payment again
