### ISSUE TITLE
[Fluxstore - Woo] - Rate app - Language problem

### ISSUE THREAD

**Issue by sketchuprzr** [inspireui/support#2679]
I changed the text content in "settings.dart". But nothing has changed in practice.

![image](https://user-images.githubusercontent.com/60021696/79074584-ef30b580-7cf5-11ea-8253-dd9524ad51a6.png)

![image](https://user-images.githubusercontent.com/60021696/79074588-f5269680-7cf5-11ea-9674-4a14b50cbfce.png)

**Comment by sketchuprzr** [comment]
Another problem is the Upgrade feature.
I am having a problem when I do this as said. Also, "upgrader" package needs to be added to the application. But I'm still having problems.

![image](https://user-images.githubusercontent.com/60021696/79074689-83028180-7cf6-11ea-91f3-ec02ac7d40bd.png)

![image](https://user-images.githubusercontent.com/60021696/79074699-8e55ad00-7cf6-11ea-92b6-0509ec619b4e.png)

![image](https://user-images.githubusercontent.com/60021696/79074682-79791980-7cf6-11ea-95b8-65a2d99f8ae4.png)

![image](https://user-images.githubusercontent.com/60021696/79074680-74b46580-7cf6-11ea-98ea-e8da45480c7b.png)

**Comment by minhcasi** [comment]
1. you can try to copy the folder of rate my app to your own folder and translate directly inside the folder - https://github.com/Skyost/RateMyApp

2. not sure if you have included the upgrader from pubspec library - https://pub.dev/packages/upgrader - we may not support this lib as it is not stable, but you could try by search the comment code that integrates this lib - https://tppr.me/cr7Jq
