### ISSUE TITLE
[Woocommerce Fluxstore] -Logic for blocking Order button if Subtotal is lower than 10€

### ISSUE THREAD

**Issue by lemarchexpress** [inspireui/support#2680]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
My backend (woocommerce) has solved this with a plugin so on website we have no problems.

But we have not the same option in the APP as we have for a minimum free shipping order, where you can establish the amount required to establish an order on the site.
Would you mind to provide this solution?
It is really useful and important block the button on review screen during checkout process.
The message to customer is important to let them know why they cannot proceed to payment (the order does not accomplish the minimum amount criteria).

2. Screenshots issues (required):
![image](https://user-images.githubusercontent.com/63209110/79074601-a412a480-7ced-11ea-9182-f722005716a7.png)

3. Proof of my purchased (required):
![image](https://user-images.githubusercontent.com/63209110/79074587-92c99800-7ced-11ea-9cb9-a0cfb25b1bd1.png)

3. Config files (required)
no apply

**Comment by minhcasi** [comment]
move to #2672
