### ISSUE TITLE
[Woocommerce Fluxstore] - Paypal is not working

### ISSUE THREAD

**Issue by lemarchexpress** [inspireui/support#2681]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
Using a valid paypal account, it never login, so at this moment, either paypal or stripe as payment methods don't work. 
How can i fix this?
Is it possible to include an smart button from paypal so the payment can be done immediately?

2. Screenshots issues (required):
![image](https://user-images.githubusercontent.com/63209110/79075037-72e7a380-7cf0-11ea-8a2a-1d5bde559ffe.png)

3. Proof of my purchased (required):
![image](https://user-images.githubusercontent.com/63209110/79075074-bb06c600-7cf0-11ea-88f0-34194db16197.png)

4. Config files (required)
[paypal_notworking.zip](https://github.com/inspireui/support/files/4466711/paypal_notworking.zip)

**Comment by minhcasi** [comment]
move to #2672
