### ISSUE TITLE
[Woocommerce Fluxstore] - Customize left menu side (customer name)

### ISSUE THREAD

**Issue by lemarchexpress** [inspireui/support#2682]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
I would like to include the name of the customer in this menu down the logo.
If it is not loggedin, so it will not show it...

such as shown in the screenshot.
2. Screenshots issues (required):
![image](https://user-images.githubusercontent.com/63209110/79075211-babafa80-7cf1-11ea-9ae9-5dd12ad6320b.png)

3. Proof of my purchased (required):
![image](https://user-images.githubusercontent.com/63209110/79075247-efc74d00-7cf1-11ea-9116-a906bc58f311.png)

4. Config files (required)
[name in menu.zip](https://github.com/inspireui/support/files/4466728/name.in.menu.zip)

**Comment by minhcasi** [comment]
move to #2672
