### ISSUE TITLE
[my-product] - Fluxstore woocommerce 1.6.6b

### ISSUE THREAD

**Issue by chikip** [inspireui/support#2683]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: Unable to login via Email and password since the updation of MstoreApi plugin. 

2. Screenshots issues (required):
![emulator](https://user-images.githubusercontent.com/63201901/79075768-62482500-7d12-11ea-8d89-7b0cf00a0d4e.png)
![mstore api plugin](https://user-images.githubusercontent.com/63201901/79075769-62e0bb80-7d12-11ea-8cc3-af5eef425d95.jpg)

3. Proof of my purchased (required):
![codecanyon](https://user-images.githubusercontent.com/63201901/79075772-68d69c80-7d12-11ea-9419-28cf5226629b.jpg)

3. Config files (required)
[config.dart..txt](https://github.com/inspireui/support/files/4466760/config.dart.txt)

**Comment by minhtruong315** [comment]
@chikip I check your config on my source code. it's working well https://www.dropbox.com/s/8w47zk4lemh5mfd/login.mov?dl=0
can u give me your account? i will try to login

**Comment by chikip** [comment]
username: a@bb.com
pass: 123

I tried testing on a completely new source, still the same result


![emulator2](https://user-images.githubusercontent.com/63201901/79097418-63626c00-7d7d-11ea-8757-dd44bba6dc15.jpg)

**Comment by minhtruong315** [comment]
https://www.dropbox.com/s/8w47zk4lemh5mfd/login.mov?dl=0
it's working well on my source code. can u send me full source code via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/2683

**Comment by chikip** [comment]
Email sent, kindly check.

Thank you

**Comment by minhtruong315** [comment]
@chikip replace this function to fix 
<img width="1385" alt="Screen Shot 2020-04-15 at 9 55 07 AM" src="https://user-images.githubusercontent.com/10402500/79294017-4eade180-7eff-11ea-82db-0d76884d8683.png">

```
/// Auth
  @override
  Future<User> getUserInfo(cookie) async {
    try {
      final http.Response response = await http.get(
          "$url/wp-json/api/flutter_user/get_currentuserinfo?cookie=$cookie&$isSecure");
      final body = convert.jsonDecode(response.body);
      if (body["user"] != null) {
        var user = body['user'];
        return User.fromAuthUser(user, cookie);
      } else {
        throw Exception(body["message"]);
      }
    } catch (err) {
      //This error exception is about your Rest API is not config correctly so that not return the correct JSON format, please double check the document from this link https://docs.inspireui.com/fluxstore/woocommerce-setup/
      rethrow;
    }
  }
```

**Comment by chikip** [comment]
Did the above, still not able to login, getting this error

![emulator](https://user-images.githubusercontent.com/63201901/79301193-8ec49280-7f06-11ea-9c15-f9313ca8a3c4.jpg)

**Comment by minhtruong315** [comment]
@chikip you can try to  uninstall then reinstall the website. maybe you had some customize in your website. so it throw error.
