### ISSUE TITLE
[Woocommerce Fluxstore] - User profile is not updating the data

### ISSUE THREAD

**Issue by lemarchexpress** [inspireui/support#2684]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
After waiting more than 5minutes it does not do anything.
The button keep the loading signal and it had not changed the values in my backend.
The Phone Number is not kept in the profile so customer has to fulfill the data always.
Profile cannot be updated without including the actual password (should show a message)

2. Screenshots issues (required):

![image](https://user-images.githubusercontent.com/63209110/79077073-d37ddd00-7cfe-11ea-882f-f4b68467bd35.png)

3. Proof of my purchased (required):
![image](https://user-images.githubusercontent.com/63209110/79077162-99f9a180-7cff-11ea-81ec-aec159241498.png)

4. Config files (required)
[user profile.zip](https://github.com/inspireui/support/files/4466870/user.profile.zip)

**Comment by minhcasi** [comment]
move to #2672
