### ISSUE TITLE
[Woocommerce Fluxstore] - How to make the 3 titles (Category/Search/MyCart) look the same?

### ISSUE THREAD

**Issue by lemarchexpress** [inspireui/support#2686]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
I have tried to make them have:
Same font-type
Same font-size
Same padding and height level
Same weight (500)
Could you help me? I could not do it... sorry.

2. Screenshots issues (required):
![image](https://user-images.githubusercontent.com/63209110/79077324-1640b480-7d01-11ea-9339-92c4a645b431.png)

3. Proof of my purchased (required):
![image](https://user-images.githubusercontent.com/63209110/79077357-60299a80-7d01-11ea-8a3d-f87b7dbe0210.png)

4. Config files (required)
[screens.zip](https://github.com/inspireui/support/files/4466888/screens.zip)

**Comment by minhcasi** [comment]
move to #2672
