### ISSUE TITLE
[Woocommerce Fluxstore] - Tabbar indicator is not aligned 

### ISSUE THREAD

**Issue by lemarchexpress** [inspireui/support#2687]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
The bar in the selector of the tabbar is not aligned with icon and i am using standard configuration for this icon. what could be happening?

2. Screenshots issues (required):
![image](https://user-images.githubusercontent.com/63209110/79078923-f9f64500-7d0b-11ea-9227-2f41d67fe241.png)

3. Proof of my purchased (required):
![image](https://user-images.githubusercontent.com/63209110/79078949-227e3f00-7d0c-11ea-8bc2-9d936cc0ed41.png)
[screens.zip](https://github.com/inspireui/support/files/4467029/screens.zip)

3. Config files (required)

**Comment by minhcasi** [comment]
move to #2672
