### ISSUE TITLE
[Flutter MV] - Android Error after Update

### ISSUE THREAD

**Issue by aberatadiguzel** [inspireui/support#2688]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
I get the following error on Android after the 1.6.6 update. I couldn't find a solution. Many things don't work

> I/flutter (24146): MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)
E/flutter (24146): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)
E/flutter (24146): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method setCurrentScreen on channel plugins.flutter.io/firebase_analytics)
I/flutter (24146): [Fluxstore][tabbar] getCurrentUser error MissingPluginException(No implementation found for method currentUser on channel plugins.flutter.io/firebase_auth)
E/flutter (24146): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method setstatusbarwhiteforeground on channel plugins.fuyumi.com/statusbar)
E/flutter (24146): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method setstatusbarwhiteforeground on channel plugins.fuyumi.com/statusbar)
I/flutter (24146): ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
I/flutter (24146): The following MissingPluginException was thrown while activating platform stream on channel
I/flutter (24146): uni_links/events:
I/flutter (24146): MissingPluginException(No implementation found for method listen on channel uni_links/events)

bla bla bla

2. Screenshots issues (required):
https://imgur.com/3KRa2Lc
https://imgur.com/632YiSp

3. Proof of my purchased (required):
https://imgur.com/HOxrZyA

3. Config files (required)
https://drive.google.com/open?id=1qkJUCXRJ_cRvFJD6k2pCdCWLduKDyeJ3

**Comment by minhcasi** [comment]
@aberatadiguzel - thank you for the feedback,

Please help to pull from the Gitlab to fix these issue - https://tppr.me/MDiQB, or you can download this attache file (remove .txt)

[MainActivity.kt.txt](https://github.com/inspireui/support/files/4467679/MainActivity.kt.txt)

**Comment by aberatadiguzel** [comment]
there was another problem
https://imgur.com/1SXwkE9
https://imgur.com/HRHiNzt

**Comment by aberatadiguzel** [comment]
I replaced it with MainActivity in 1.6.5. problem solved!
