### ISSUE TITLE
[FluxStore Pro] - Language Issue

### ISSUE THREAD

**Issue by xLidoni** [inspireui/support#2689]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

My issue:

Hi recently, I'm trying to create a new language, I installed the  plugin , but when i try to create a new language they generate some errors.

Any solutions?
Thanks!

if I open a demo project it works.

Screenshots issues (required):

![image](https://user-images.githubusercontent.com/11965301/79084155-8c114400-7d32-11ea-90b6-b222d84db994.png)

Proof of my purchased (required):

![image](https://user-images.githubusercontent.com/11965301/79081275-2a45df80-7d1c-11ea-9f7d-b8b8043a36e6.png)

Config files (required)

**Comment by minhcasi** [comment]
Hi @xLidoni - these are just the warning from the plugin of Android studio - if the language is working fine then don't worry about it 

Would you mind to share this language file so that we will include it as officially from the app - thank you!

**Comment by xLidoni** [comment]
Certainly as soon as the translation is finished I will share it!

A question.


Not mine generated the files


config_it.json

states_it.json


and I added this string to the i10n.dart file.


  String get italian {
    return Intl.message (
      'Italian',
      name: 'italian',
      desc: '',
      args: [],
    );
  }


it's correct?

**Comment by minhcasi** [comment]
i10n.dart has been generated automatically by using this Android Studio plugin - https://plugins.jetbrains.com/plugin/13666-flutter-intl - so you don't need to edit it :)

The __.json file is load directly into the project :)

**Comment by xLidoni** [comment]
Not in my case.


config_it.json

states_it.json

were not generated, why?

**Comment by minhcasi** [comment]
@xLidoni - these json files should edit/update manually - it could not be generated

Please move your all conversation to the same #2722 - thank you!
