### ISSUE TITLE
i can t download the xde

### ISSUE THREAD

**Issue by yassineallami** [inspireui/support#269]
i can t download the xde
 - Product: Mstore Shopify - Complete React Native template for e-commerce
 - Your Purchased Code: a7f2fb94-25f6-4249-99c9-82a47b89d9f7

i can t download the xde

**Comment by minhcasi** [comment]
Hi, sorry for the confuse, please download the new expo tool (https://expo.io/tools) via terminal: npm install expo-cli --global

Then simply start the project by: yarn install && expo start 

Let us know if it does not work and reopen the issue

Thank you!
