### ISSUE TITLE
[FluxStore] - mstore-api 2.2.6 and 2.2.7 Updates Can't Sing in

### ISSUE THREAD

**Issue by Jegufull** [inspireui/support#2690]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:

When I update to woocomerce to mstore-api 2.2.6 and mstore api 2.2.7 my application doesn't want to login to my store, please fix that.

In the application supposedly the wrong password comes out,  I install an older version of the api, and if I can log in to the app.

2. Screenshots issues (required):

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-12 at 20 21 22](https://user-images.githubusercontent.com/47310507/79084778-34a3b180-7cfb-11ea-9566-68a147bd8965.png)

3. Proof of my purchased (required):
<img width="1516" alt="Captura de Pantalla 2020-04-12 a la(s) 8 19 58 p  m" src="https://user-images.githubusercontent.com/47310507/79084744-032ae600-7cfb-11ea-9b88-a87f36e2ff6e.png">

3. Config files (required)

**Comment by minhcasi** [comment]
#2683

**Comment by minhtruong315** [comment]
@Jegufull You need to verify purchase code to work with MStore Api
https://user-images.githubusercontent.com/63201901/79075769-62e0bb80-7d12-11ea-8cc3-af5eef425d95.jpg

**Comment by Jegufull** [comment]
I already updated to the latest version and added the purchase code and it worked 👍🏼, thanks

**Comment by Shiru-kun** [comment]
when im trying do signin i got a toaster msg saying wrong credentials , but its not true... i used to login in my website

**Comment by Shiru-kun** [comment]
i have the latest version of mstore api

**Comment by Jegufull** [comment]
@Shiru-kun  You need to verify purchase code to work with MStore Api  plugin. look at
next example
https://user-images.githubusercontent.com/63201901/79075769-62e0bb80-7d12-11ea-8cc3-af5eef425d95.jpg

**Comment by Shiru-kun** [comment]
I-  already verified the purchase but i still cant login.

**Comment by Shiru-kun** [comment]
![79193699-6f0c6c00-7e2b-11ea-99b8-add2cdadb85d](https://user-images.githubusercontent.com/54008441/79230774-69cc1300-7e65-11ea-91f3-054e000bc32a.png)
