### ISSUE TITLE
[Fluxstore - woo] - Getting an error when running the latest application version 

### ISSUE THREAD

**Issue by Justnopeople** [inspireui/support#2692]
I can't run my application while running it. I get an error response like the following.
![image](https://user-images.githubusercontent.com/49190031/79102280-9ebc6500-7d94-11ea-985e-9b0deec781f8.png)

Proof of my purchased
![image](https://user-images.githubusercontent.com/49190031/79102385-d9260200-7d94-11ea-8c50-1f53d64e3fae.png)

Please help me to solve this.

**Comment by minhcasi** [comment]
@Justnopeople - pls try to use the flutter stable channel 
```
flutter channel stable
flutter upgrade --force
```
Also, try to clean cache to fix the issue - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1 - thank you!
