### ISSUE TITLE
Fluxstore Pro - Flutter E-commerce Full App

### ISSUE THREAD

**Issue by elienaj** [inspireui/support#2693]
Hello Team.
1. My issue:

Trying to run the new update FluxStore 1.6.6b, I'm getting Registered as a Git root, but no Git repositories were found there
can you help?

2. Screenshots issues (required):

https://user-images.githubusercontent.com/61785293/79103413-2befc180-7d75-11ea-949b-644af23692d9.png

3. Proof of my purchased (required):

Item ID:
24020929

Item Purchase Code:
6ba98005-b5e2-49d5-b767-c97e3f35f38e

Purchase Date:
2020-02-26 08:30:22 UTC

3. Config files (required)

**Comment by minhcasi** [comment]
@elienaj - please try to clean cache to fix this issue - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1 - thank you!

**Comment by elienaj** [comment]
please check not solved.

"This package referenced a Flutter repository via the .packages file that
is no longer available."

**Comment by elienaj** [comment]
Solved below are the steps:

   1. Delete .packages file and
   2. Run following command flutter pub get

**Comment by minhcasi** [comment]
@elienaj - thank you for your sharing, I've also updated this solution to the gist - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

**Comment by elienaj** [comment]
Hello Team,
Please Check the attached image.

**Comment by minhcasi** [comment]
@elienaj - we could not see the screen, please share again

**Comment by elienaj** [comment]
hello,

https://drive.google.com/open?id=1eAGHYzypCHQw6lVRGgEMR5pc22O6UrVT

**Comment by elienaj** [comment]
Hello Team any news?

**Comment by minhcasi** [comment]
@elienaj - please help to check the solution on this ticket https://github.com/inspireui/support/issues/2615

We will update new released soon on this weekend

**Comment by minhcasi** [comment]
Please note that the new release 1.6.7 is available to download via Gitlab, it will be released on Codecayon in 1-2 days - thank you!
