### ISSUE TITLE
Fluxstore Shopify - No changes happening in the app 

### ISSUE THREAD

**Issue by amankwatra** [inspireui/support#2696]
Hi,

I have made many changes based on your tutorial on docs.inspireui.com/fluxstore and most of the changes are changing banner images, category images etc. etc. but none of these changes are happening in my emulator app. whenever i reload all the pictures that came originally only are visible and none of the replaced ones. 

What has happened? I cannot customize the app if I cant change the images? Please let me know how to go about it.

**Comment by Jegufull** [comment]
Go to Fluxstore project folder lib/common/config.dart, update "isCaching": false.

**Comment by amankwatra** [comment]
It is already false.

**Comment by amankwatra** [comment]
I still haven't been able to make any changes.... somebody help. this was supposed to be very easy.

**Comment by minhcasi** [comment]
@amankwatra - please share the common folder via this form - http://private.inspireui.com - we will help to investigate the issue - thank you!

**Comment by minhcasi** [comment]
@amankwatra - please share the config file so that we could help for checking
