### ISSUE TITLE
[Fluxstore-WooCommerce] - Bug in Cart Page

### ISSUE THREAD

**Issue by zahmed84** [inspireui/support#2697]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:

Hi, i have observed a bug in your App when changing the quantity on Cart Page. In fact when we change the quantity on cart page, then close the App. After reopening the App the Cart page shows the Error. Screenshot of Error msg. is attached herewith.

2. Screenshots issues (required):

![WhatsApp Image 2020-04-13 at 20 02 26](https://user-images.githubusercontent.com/58950301/79131652-5d42ae80-7dc2-11ea-9436-51caf1a9a735.jpeg)

3. Proof of my purchased (required):

![Proof of Purchase](https://user-images.githubusercontent.com/58950301/79131693-70557e80-7dc2-11ea-8b1c-ecf5aa9d25da.PNG)

3. Config files (required)

**Comment by twhittakerdev** [comment]
you're not the only one experiencing these issues. i find the app to be extremely buggy. question, have you been able to do a successful login and registration via the app

**Comment by minhcasi** [comment]
@zahmed84 - this bug is fixed on latest code - we will release it on this week

In the meantime please check solution on this ticket - https://github.com/inspireui/support/issues/2615
