### ISSUE TITLE
Fluxstore Pro Reqesting Fetures 

### ISSUE THREAD

**Issue by kurkuteabhi** [inspireui/support#2699]
Please add following features in Fluxstore Pro app

1) Add additional address line at as 
---- Address line 1
---- Address line 2
---- City
---- Postal Code
---- State
---- Country

2) conformation check box for T&C before making payment

3) place for privacy policy

Thanks in advance

![purches](https://user-images.githubusercontent.com/43174699/79148809-c555bc80-7de3-11ea-8fc8-0ffd00873521.jpg)

**Comment by minhcasi** [comment]
@kurkuteabhi - thank you for your suggestion, I've updated as a feature request and send to the team for checking

**Comment by kurkuteabhi** [comment]
Hi one more feature requested, which i forget to inform as below:

User can edit product variants at checkout or wishlist's page

**Comment by minhcasi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improve Shipping and Confirm Payment Screen](https://trello.com/c/WaMmUoX3/29-improve-shipping-and-confirm-payment-screen)

**Comment by minhcasi** [comment]
moved to our backlog for investigating - thanks
