### ISSUE TITLE
follow up how to the steps not clear

### ISSUE THREAD

**Issue by alaradi2006** [inspireui/support#27]
first expo init 
then project name 
then 
template blank

_Originally posted by @alaradi2006 in https://github.com/inspireui/support/issues/24#issuecomment-439731711_

**Comment by alaradi2006** [comment]
![1](https://user-images.githubusercontent.com/45144621/48802818-5a54a300-ed21-11e8-9380-dc703c85e307.jpg)

**Comment by minhcasi** [comment]
Hi, as the Expo new version suggest to use the Expo cli and not support for Expo XDE, please help to use following script:
npm install expo -g

From the source folder, run:
yarn install
expo start

Then it will open the simulator to run similar with the current Expo XDE, let us know your checking - thank you!

**Comment by alaradi2006** [comment]
can you send me video as how i will run the  script 
i will but the codes in cmd command for windows 10 
yarn install
expo start

**Comment by alaradi2006** [comment]
its installed in my pc

________________________________

**Comment by alaradi2006** [comment]
i have already both in my pc

**Comment by thangvo9x** [comment]
Hi, Send an email to thang@beostore.io for helping.

**Comment by alaradi2006** [comment]
ok
