### ISSUE TITLE
[MStore] problem in RTL and changing logo and splash screen

### ISSUE THREAD

**Issue by AbanoubReact** [inspireui/support#270]
**Mandatory Info (please complete the following information):**
 - Product: [ MStore]
 - Your Purchased Code: 8b86468a-13a0-49b3-afb2-68a30e59cb2f

**Describe the issues**
I have two problems:
firstly the RTL : 
I set default RTL and it firstly not work the app is ltr and I need to exit and open app again to make it RTL, 
my customer will not be happy with that I need the RTL is active when I open the APP first time 
,
Secondly I want to change APP name and logo and splash screen for mstore-pro 
I don't know how to change it in android folder and ios folder

**Comment by AbanoubReact** [comment]
Oh I forgot there are other issue 
I can't register any Account 
I am sure method of get nonce is works I tested it via Post man and get the nonce 
and test it on website from browser my link is derarstore.com and it works 
but the app didn't get the nonce before making registry request
![screenshot_1549625638](https://user-images.githubusercontent.com/47436634/52454047-ebf0d700-2afe-11e9-88e1-1369b01ee689.png)

**Comment by minhcasi** [comment]
Hi, just update that we received your ticket and the team will back to check on Monday, sorry for the delay - thank you!

**Comment by AbanoubReact** [comment]
There are another issue in countries in rtl version
There are no countries name just flags with no name

**Comment by AbanoubReact** [comment]
![screenshot_1549769453](https://user-images.githubusercontent.com/47436634/52529125-40cc5300-2ca1-11e9-9e62-2bd79f457d6e.png)

**Comment by AbanoubReact** [comment]
![screenshot_1549782764](https://user-images.githubusercontent.com/47436634/52530831-45ecca80-2cc0-11e9-8d7d-18bb59f42da6.png)

**Comment by luyx2412** [comment]
Hi @AbanoubReact i noted your issue and fix with next version.

Thanks

**Comment by luyx2412** [comment]
Hi @AbanoubReact Can you provide your AppConfig.json and Config.js file? i just tested your issues which worked normal.

Thanks
