### ISSUE TITLE
[Fluxstore-Listing] - Unable to archive the ios build 

### ISSUE THREAD

**Issue by khalidsharif** [inspireui/support#2700]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
I am using the latest fluxstore listing version 1.4.0 - I can build the ios app from android studio, its working fine with the simulator but the Archive from xcode always fails.
I want to deploy it to the apple store now but still no success. 

I tried removing and reinstalling pods. cleaning and rebuilding the app still no success.
I  always get this issue when I try to Archive:

<img width="1565" alt="Screen Shot 2020-04-13 at 9 33 57 PM" src="https://user-images.githubusercontent.com/50369621/79149161-64bc8480-7dcf-11ea-99b6-a1c96391667f.png">

2. Proof of my purchased (required):
<img width="326" alt="76076672-54cfaa80-5fb0-11ea-83b8-a85d702a599f" src="https://user-images.githubusercontent.com/50369621/79149195-72720a00-7dcf-11ea-9403-55a9b4880464.png">

**Comment by khalidsharif** [comment]
This is my flutter environment :

<img width="844" alt="Screen Shot 2020-04-13 at 11 58 34 PM" src="https://user-images.githubusercontent.com/50369621/79160612-c0443d80-7de2-11ea-8d98-243344e5cda1.png">

**Comment by minhcasi** [comment]
Hi, could I check if you try to run 'flutter release ios' from the terminal, also update the Signing as this screenshot

<img width="846" alt="Screen Shot 2020-04-14 at 8 55 26 AM" src="https://user-images.githubusercontent.com/1459805/79177879-f8bd3900-7e2d-11ea-85f7-809695ec1289.png">

**Comment by khalidsharif** [comment]
@minhcasi I think 'flutter release ios' is not a valid command. 
please check below, maybe you mean 'flutter build ios --release'?!

<img width="839" alt="Screen Shot 2020-04-14 at 11 47 37 AM" src="https://user-images.githubusercontent.com/50369621/79204998-0f6f8a00-7e46-11ea-98ea-63cc4e1168e5.png">


and here is my bundle id sigining page

<img width="999" alt="Screen Shot 2020-04-14 at 11 48 35 AM" src="https://user-images.githubusercontent.com/50369621/79205137-3928b100-7e46-11ea-86aa-495714ad0554.png">


'flutter build ios --release'? generate an Runner.app file ... 

 
<img width="929" alt="Screen Shot 2020-04-14 at 12 01 15 PM" src="https://user-images.githubusercontent.com/50369621/79206461-0aabd580-7e48-11ea-922e-32466037a564.png">

**Comment by khalidsharif** [comment]
@minhcasi  I think I found the root cause, I was opening the wrong xcode project file.

Runner.xcworkspace is the correct one while I was opening Runner.xcodeproj.

you can close the ticket and sorry for the inconvenience
