### ISSUE TITLE
[MStore Pro] - Recent Product Post

### ISSUE THREAD

**Issue by juniortimeline** [inspireui/support#2701]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: How can I add recent product post here

{
  "WooCommerce": {
    "url": "http://demo.mstore.io",
    "consumerKey": "ck_b7594bc4391db4b56c635fe6da1072a53ca4535a",
    "consumerSecret": "cs_980b9edb120e15bd2a8b668cacc734f7eca0ba40"
  },
  "HorizonLayout": [
    {
      "layout": "circleCategory"
    },
    {
      "layout": "bannerImage",
      "categoryOrTag": 23,
      "imageBanner": "https://user-images.githubusercontent.com/1459805/60091808-a19b8a00-976f-11e9-9cc7-576ca05c2442.png",
      "category": 23
    },
    {
      "name": "featureProducts",
      "image": "",
      "layout": "threeColumn",
      "categoryOrTag": 26,
      "category": 26
    },
    {
      "layout": "bannerSale",
      "categoryOrTag": 273,
      "tag": 273,
      "showDateTime": true,
      "countdown": true,
      "background": ["rgba(6, 188, 198, 1)", "rgba(244, 244, 246, 0.9)"]
    },
    {
      "name": "News",
      "layout": "Blog",
      "categoryOrTag": 21,
      "tag": 21
    },
  ],
  "MainColor": "#3FC1BE"
}

Thank You So Much

2. Screenshots issues (required):

3. Proof of my purchased (required): https://codecanyon.net/comments/24044744

3. Config files (required)

**Comment by minhcasi** [comment]
Hi, you can try this setting (to set empty category ID)

```
{
"name": "recentProduct",
"image": "",
"layout": "threeColumn",
},
```

**Comment by juniortimeline** [comment]
> Hi, you can try this setting (to set empty category ID)
> 
> ```
> {
> "name": "recentProduct",
> "image": "",
> "layout": "threeColumn",
> },
> ```

Its work thank you so much
