### ISSUE TITLE
[Fluxstore] - translate new item in menu

### ISSUE THREAD

**Issue by limitlessfirm** [inspireui/support#2702]
---------

1. My issue: Depend on to past issue number #2666. i added new item in menu but when change the language for app the new item in menu not translates so i want to know how the new item translate also

2. Screenshots issues (required): 
![Capture](https://user-images.githubusercontent.com/59250639/79154732-5f136e80-7dd0-11ea-8b5f-75c7693aadaf.JPG)

3. Proof of my purchased (required): 
![screenshot](https://user-images.githubusercontent.com/59250639/79154751-689cd680-7dd0-11ea-86cb-e9668b27a276.JPG)

3. Config files (required)

**Comment by dttrung26** [comment]
HI @limitlessfirm , 
if you are using my code in previous ticket, then please keep in mind that those Texts inside that widget is hard-coded. If you wish to use translate language feature, first you need to declare your language in l10n like this: 
`
Go to lib/l10n/ the folder and copy the existing files to make a new one (you may see there are 6 languages demo from the app). Let’s take adding the new French (fr) Language for example, the format should be intl_fr.arb. We suggest using the Android Studio with Flutter Intl when inputting new language to support auto-generating the WidgetsLocalizations file lib/generated/i10n.dart.
`
Second, inside /lib/menu.dart, import l10n by `import 'generated/l10n.dart';`

Then inside that ListTile, simple replace

`title: Text("About us"),` by `S.of(context).yourNewDeclaredLanguage`
and ` title: "About Us"` by `S.of(context).yourNewDeclaredLanguage`

Happy coding!

**Comment by limitlessfirm** [comment]
i made your steps and the translate for link  working now. But now the problem is that. all language for link go to the same URL 

i want each language for item in menu go to diffrent page 

i used the following code in menu.dart

                ListTile(
                  leading: const Icon(
                    Icons.search,
                    size: 20,
                  ),
                  title: Text(S.of(context).branches),
                  onTap: () {
                    Navigator.push(
                        context,
                        MaterialPageRoute(
                            builder: (context) => WebView(
                                url: "https://www.*******.net/branches",
                                title: "branches")));

                  },
                ),

**Comment by dttrung26** [comment]
Hi @limitlessfirm ,
 I'm quite not sure what you mean. Could you explain a little more detail?

**Comment by limitlessfirm** [comment]
I want the branches link in menu 
in English version go to this url : https://www.********.net/branches/
in Arabic version go to this url : https://www.********.net/ar/الفروع/

**Comment by dttrung26** [comment]
Hi @limitlessfirm , 
a short if-else checking could do the trick in your case. 
At the very first place in menu.dart, add following line:
` import 'models/app.dart'; ` 
Inside the build function, add following line: 
` String locale = Provider.of<AppModel>(context, listen: false).locale; `
Finally, edit your `ListTile` widget: 
```
     ListTile(
              leading: const Icon(
                Icons.search,
                size: 20,
              ),
              title: Text(S.of(context).branches),
              onTap: () {
                Navigator.push(
                    context,
                    MaterialPageRoute(
                        builder: (context) => WebView(
                         url: locale == 'en'
                              ? "https://your-web-link-in-en-language.com"
                              : "https://your-web-link-in-ar-language.com",
                            title: "branches")));

              },
            ),
```
Let me know if you still have any question.
Have a great day!

**Comment by limitlessfirm** [comment]
not working
retrieve the same page for all language

**Comment by dttrung26** [comment]
Replace this into your /lib/models/
[ticker_support#2702.zip](https://github.com/inspireui/support/files/4480182/ticker_support.2702.zip)
Hope this works.

**Comment by dttrung26** [comment]
Close due to no response from customer. Feel free to reopen ticket again if you still need help.

**Comment by limitlessfirm** [comment]
Please give me an example for if-else checking  in my case
