### ISSUE TITLE
[FluxStore PRO] - Opencart : Items in cart show error if app is reopened 

### ISSUE THREAD

**Issue by harrisbaitalrayan** [inspireui/support#2703]
Using OpenCart setup with latest version of OpenCart.

1. My issue: 

Add items to cart. Close app and reopen. Check Cart page. It shows error.
Also, with the latest OpenCart, offer price and products options are also not displaying. Its same in your demo app also connected to OpenCart. If there is a new version being released, can you please update the release date.

This is an urgent project for us. Your prompt help is appreciated.

2. Screenshots issues (required):

![WhatsApp Image 2020-04-14 at 1 54 56 AM](https://user-images.githubusercontent.com/13076524/79164866-01444e00-7df3-11ea-91e3-4a1cb93b97f8.jpeg)

3. Proof of my purchased (required):

<img width="902" alt="Fluxstore purchase" src="https://user-images.githubusercontent.com/13076524/79164887-0e613d00-7df3-11ea-93e9-28c39e45b0e4.png">

3. Config files (required)

**Comment by sodhanii** [comment]
This happens in magneto as well.

**Comment by minhcasi** [comment]
@sodhanii - @harrisbaitalrayan - confirm this issue is fixed on the latest code, we will release a new version on this week

In the meantime - please check the solution on this ticket https://github.com/inspireui/support/issues/2615

**Comment by harrisbaitalrayan** [comment]
Great. i'll wait for the release this week. The offer price display is very important, as all retailers are giving offers and discount sales.

Also can you explain how to show the sale tag on products. I want to show various tags like flash sales etc on products.
Example from your demo application downloaded from AppStore.

![WhatsApp Image 2020-04-14 at 3 03 49 PM](https://user-images.githubusercontent.com/13076524/79218491-8fefb400-7e61-11ea-9190-4c6fe3fe5b5d.jpeg)
![WhatsApp Image 2020-04-14 at 3 03 50 PM](https://user-images.githubusercontent.com/13076524/79218501-941bd180-7e61-11ea-97e6-8e217596b933.jpeg)

**Comment by minhcasi** [comment]
@harrisbaitalrayan - you can optimize the product cart view on this file - https://tppr.me/WVihL 

As the salePrice is fixed, allow us to close the ticket and update the fixing on next release.

If you have not accessed to the latest Gitlab repository source code, please help to submit it here - https://docs.google.com/forms/d/e/1FAIpQLSeuBqUkScy42V7KKhfNPj0fl581anrB1mWkbMa3p2WQt7fhfw/viewform

Thank you!

**Comment by harrisbaitalrayan** [comment]
I accessed your gitlab repository and took the code from there. But none of the issues are seen fixed:
1) Cart error when reopen the application
2) No options in product
3) Discount price is not shown

Is there something i am missing? Please advise.
