### ISSUE TITLE
[MStore Pro] - How to add dynamic config (HorizonLayouts) from cloud? 

### ISSUE THREAD

**Issue by harry503** [inspireui/support#2706]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
It would be good to be able to load config (HorizonLayouts) from the server just like Fluxstore Pro is currently doing.

Can you give a hint / solve a small code to make it happen?

I'm trying to do it in src/common/index.js
<img width="689" alt="Screen Shot 2020-04-14 at 12 00 06" src="https://user-images.githubusercontent.com/35995317/79187813-822d3500-7e47-11ea-86ce-205989f20c95.png">

But it's not working. Can you suggest a quick fix to the code above and perhaps it would be good to be part of next release.

2. Screenshots issues (required):

3. Proof of my purchased (required):
Purchase Code: 7c399f31-c465-4f76-ac62-7fa0f04fd615

3. Config files (required)

**Comment by minhcasi** [comment]
@luyx2412 - please suggest a solution to load json on cloud

**Comment by harry503** [comment]
@luyx2412 any update? Thank you

**Comment by luyx2412** [comment]
Hi @harry503 we are researching and reply you soon.

Thanks

**Comment by luyx2412** [comment]
Hi @harry503 
- the first in `src/Router.js` please load your json config in this file. After that, you need create a redux field to save it. You can see `updateConnectionStatus` function to follow it.

- When you had the config json in redux. Please remove everywhere used AppConfig and use it from redux where saved it.

Thanks

**Comment by harry503** [comment]
Thank you for your tips. it would be great for next release. For now i will close this one.
