### ISSUE TITLE
Mstore-MV

### ISSUE THREAD

**Issue by inimist** [inspireui/support#2707]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: its S10 Samsung the below menu is not showing. Apparently is covered by the system default banner. 

2. Screenshots issues (required):

![IMG-20200412-WA0002](https://user-images.githubusercontent.com/447618/79189858-78540380-7e40-11ea-81e4-7838026028e9.jpg)

3. Proof of my purchased (required):
![76964872-65d1d180-6949-11ea-9687-d2b778d05d0a](https://user-images.githubusercontent.com/447618/79189876-8013a800-7e40-11ea-8c7c-b772db8c8644.png)

3. Config files (required)
[common.zip](https://github.com/inspireui/support/files/4473357/common.zip)

**Comment by luyx2412** [comment]
Hi @inimist You meant the tabbar is not show?
![image](https://user-images.githubusercontent.com/8909619/79292865-66d03180-7efc-11ea-9227-c77ce0859a58.png)

Can you give me the specific version?

Thanks
