### ISSUE TITLE
FluxListing Error Message - Request For Help

### ISSUE THREAD

**Issue by swspro** [inspireui/support#2708]
Hi There,

This is Sam from INDIA and I am much excited about learning and using your Products

Recently I had got FluxListing and FluxNews from Themeforest 

I am using Wordpress as the Backend

Also I have installed flutter and other required applications  

But I am not able to run your run the App which I got in the source file

Getting error message

YOU CAN FIND THE SCREENSHOT IN THE ATTACHMENT.

Please suggest

Sam
![FluxListing Errors](https://user-images.githubusercontent.com/15525566/79194233-d6d1af80-7e49-11ea-839c-f6c46b1b9163.JPG)
![error1](https://user-images.githubusercontent.com/15525566/79194332-01bc0380-7e4a-11ea-9378-4663dc34412e.JPG)

**Comment by philipvu30** [comment]
Hi,

Please replace this line:

 _permission = await _locationService.requestPermission();
to this:
 _permission = (await _locationService.requestPermission()) as bool;

You can find it here: lib/widgets/home/banner/banner_map.dart

**Comment by swspro** [comment]
Thanks Philip for your quick response. It is highly appreciated.

Will update and test it again.

Sam

**Comment by minhcasi** [comment]
@swspro - Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads it's used to verify your proof of purchase? 
Sorry for any inconvenience, we will reopen the ticket when it is verified, thank you!

**Comment by swspro** [comment]
sure !
![Themeforest](https://user-images.githubusercontent.com/15525566/79212386-312c3980-7e65-11ea-9ab5-c67b0ea3862a.JPG)
