### ISSUE TITLE
CEStore 1.3.0 npm start error

### ISSUE THREAD

**Issue by salcad** [inspireui/support#271]
Hi,

I tried to run the CEStore 1.3.0 Web using the "npm start" command and I found the following error

C:\ReactjsLabs\CeStore-1.3.0\Source\web> npm start

> cezerin@0.33.0 start C:\ReactjsLabs\CeStore-1.3.0\Source\web
> concurrently npm:start-*

[start-store]
[start-store] > cezerin@0.33.0 start-store C:\ReactjsLabs\CeStore-1.3.0\Source\web
[start-store] > node -r esm dist/store/server/index.js
[start-store]
[start-api]
[start-api] > cezerin@0.33.0 start-api C:\ReactjsLabs\CeStore-1.3.0\Source\web
[start-api] > node -r esm src/api/server/index.js
[start-api]
[start-store] error: uncaughtException: Missing export name 'initOnServer' in ES module: file:///C:/ReactjsLabs/CeStore-1.3.0/Source/web/theme/dist/index.js
[start-store] file:///C:/ReactjsLabs/CeStore-1.3.0/Source/web/dist/store/server/pageRendering.js:1
[start-store] import winston from 'winston';
[start-store]
[start-store] SyntaxError: Missing export name 'initOnServer' in ES module: file:///C:/ReactjsLabs/CeStore-1.3.0/Source/web/theme/dist/index.js
[start-store]     at Object.<anonymous> (file:///C:/ReactjsLabs/CeStore-1.3.0/Source/web/dist/store/server/pageRendering.js:1)
[start-store]     at Generator.next (<anonymous>) {"error":{},"stack":"file:///C:/ReactjsLabs/CeStore-1.3.0/Source/web/dist/store/server/pageRendering.js:1\nimport winston from 'winston';\n\nSyntaxError: Missing export name 'initOnServer' in ES module: file:///C:/ReactjsLabs/CeStore-1.3.0/Source/web/theme/dist/index.js\n    at Object.<anonymous> (file:///C:/ReactjsLabs/CeStore-1.3.0/Source/web/dist/store/server/pageRendering.js:1)\n    at Generator.next (<anonymous>)","exception":true,"date":"Thu Feb 07 2019 15:03:00 GMT+0700 (Indochina Time)","process":{"pid":23832,"uid":null,"gid":null,"cwd":"C:\\ReactjsLabs\\CeStore-1.3.0\\Source\\web","execPath":"C:\\Program Files\\nodejs\\node.exe","version":"v10.10.0","argv":["C:\\Program Files\\nodejs\\node.exe","C:\\ReactjsLabs\\CeStore-1.3.0\\Source\\web\\dist\\store\\server\\index.js"],"memoryUsage":{"rss":115154944,"heapTotal":96780288,"heapUsed":70506272,"external":1004131}},"os":{"loadavg":[0,0,0],"uptime":509042},"trace":[{"column":null,"file":"file:///C:/ReactjsLabs/CeStore-1.3.0/Source/web/dist/store/server/pageRendering.js","function":null,"line":1,"method":null,"native":false},{"column":null,"file":null,"function":"Generator.next","line":null,"method":"next","native":false}]}
[start-store] npm ERR! code ELIFECYCLE
[start-store] npm ERR! errno 1
[start-store] npm ERR! cezerin@0.33.0 start-store: `node -r esm dist/store/server/index.js`
[start-store] npm ERR! Exit status 1
[start-store] npm ERR!
[start-store] npm ERR! Failed at the cezerin@0.33.0 start-store script.
[start-store] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[start-store]
[start-api] info: API running at http://localhost:3001
[start-store] npm ERR! A complete log of this run can be found in:
[start-store] npm ERR!     C:\Users\Dede\AppData\Roaming\npm-cache\_logs\2019-02-07T08_03_00_883Z-debug.log
[start-store] npm run start-store exited with code 1
[start-api] info: MongoDB connected successfully
Terminate batch job (Y/N)? [start-api] Terminate batch job (Y/N)? n

and the log file contains :

info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start-store' ]
2 info using npm@6.4.1
3 info using node@v10.10.0
4 verbose run-script [ 'prestart-store', 'start-store', 'poststart-store' ]
5 info lifecycle cezerin@0.33.0~prestart-store: cezerin@0.33.0
6 info lifecycle cezerin@0.33.0~start-store: cezerin@0.33.0
7 verbose lifecycle cezerin@0.33.0~start-store: unsafe-perm in lifecycle true
8 verbose lifecycle cezerin@0.33.0~start-store: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\ReactjsLabs\CeStore-1.3.0\Source\web\node_modules\.bin;C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\ReactjsLabs\CeStore-1.3.0\Source\web\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Python27\;C:\Python27\Scripts;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;c:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;c:\Program Files\Microsoft SQL Server\100\Tools\Binn\;c:\Program Files\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Git\cmd;c:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\VSShell\Common7\IDE\;c:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\;c:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio\;c:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\;c:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files\PuTTY\;C:\ProgramData\chocolatey\bin;C:\Program Files\nodejs\;C:\Program Files (x86)\Yarn\bin\;C:\Program Files\Microsoft VS Code\bin;C:\WINDOWS\System32\OpenSSH\;c:\Program Files\Microsoft SQL Server\110\DTS\Binn\;C:\PostgreSQL\pg10\bin;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Users\Dede\AppData\Local\GitHubDesktop\bin;C:\Users\Dede\AppData\Roaming\npm;C:\Users\Dede\AppData\Local\Yarn\bin;C:\Users\Dede\AppData\Local\Microsoft\WindowsApps;C:\Users\Dede\.dotnet\tools;C:\Users\Dede\AppData\Local\Markdown Monster;C:\Users\Dede\AppData\Local\Markdown Monster\Markdown Monster;C:\Users\Dede\AppData\Local\Microsoft\WindowsApps;;C:\Program Files\JetBrains\IntelliJ IDEA 2018.3.1\bin;
9 verbose lifecycle cezerin@0.33.0~start-store: CWD: C:\ReactjsLabs\CeStore-1.3.0\Source\web
10 silly lifecycle cezerin@0.33.0~start-store: Args: [ '/d /s /c', 'node -r esm dist/store/server/index.js' ]
11 silly lifecycle cezerin@0.33.0~start-store: Returned: code: 1  signal: null
12 info lifecycle cezerin@0.33.0~start-store: Failed to exec start-store script
13 verbose stack Error: cezerin@0.33.0 start-store: `node -r esm dist/store/server/index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid cezerin@0.33.0
15 verbose cwd C:\ReactjsLabs\CeStore-1.3.0\Source\web
16 verbose Windows_NT 10.0.17763
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start-store"
18 verbose node v10.10.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error cezerin@0.33.0 start-store: `node -r esm dist/store/server/index.js`
22 error Exit status 1
23 error Failed at the cezerin@0.33.0 start-store script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by minhcasi** [comment]
Hi, just update that we received your ticket and the team will back to check on Monday (after the Tet holiday), sorry for the delay - thank you!

**Comment by minhtruong315** [comment]
Hi @salcad Can you add my skype? I will help you check issues via teamview.
my skype: minhtruong315

**Comment by minhtruong315** [comment]
Pls check this video: https://www.youtube.com/watch?v=HF1aQzVHEPQ
