### ISSUE TITLE
[my-product] - Fluxstore WooCommerce - Flutter E-commerce Full App version 1.6.6b – 05 Apr 2020

### ISSUE THREAD

**Issue by vivekaris** [inspireui/support#2710]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: Wrong shipping method display in shipping Screen

2. Screenshots issues (required):
![WhatsApp Image 2020-04-14 at 2 01 17 AM](https://user-images.githubusercontent.com/3786005/79197971-53678c80-7e50-11ea-820b-1b01c4dd974a.jpeg)

3. Proof of my purchased (required): i am using gitlab same git userid my license last digit 
                                                               dad686e2 (bvm automation )

3. Config files (required) : json file output as per debug in console : 

![webservice-data](https://user-images.githubusercontent.com/3786005/79199377-89a60b80-7e52-11ea-86a0-f7ae00045669.png)

**Comment by minhcasi** [comment]
please help to move this conversation to the same ticket #2712
