### ISSUE TITLE
MstorePro coupon type always percent

### ISSUE THREAD

**Issue by binhetc** [inspireui/support#2711]
Hello,
I got an issue recently about coupon type, it always be percent in app only, my website works well.
Could you please help to check that.
I do not have any update on Apple Store.
Best regards,
Binh Dinh
![Ảnh chụp Màn hình 2020-04-14 lúc 15 02 49](https://user-images.githubusercontent.com/13253563/79200732-1952b680-7e61-11ea-947e-7e3b24c247ff.png)

**Comment by minhcasi** [comment]
@binhetc - could you help to share the screenshot issue pls and also attache the common folder so that we could reproduce the issue - thank you!
