### ISSUE TITLE
[FluxNews] - Guide to perform following changes

### ISSUE THREAD

**Issue by jamesmendez** [inspireui/support#2713]
1. My issue:
Hello,
Could you please guide me how do i perform the following changes : 
1. Disable Social Logins
2. Add all my wordpress categories of my website becouse i can't see all of them in the app
3. Rename Menu Items Names (Login and Home)
4. Exclude categories of my wordpress site on the app
5. Do not duplicate articles in homepage

2. Screenshots issues (required):

3. Proof of my purchased (required):
<img width="848" alt="79043349-f5903600-7bfe-11ea-8069-cbbc73d01cb8" src="https://user-images.githubusercontent.com/63358368/79206255-5c039700-7e3f-11ea-95a6-e7375099c209.png">

3. Config files (required)

**Comment by dttrung26** [comment]
Support via skype
