### ISSUE TITLE
Erro with mstore api plugin

### ISSUE THREAD

**Issue by n4solutions** [inspireui/support#2714]
Hi, i got this error:

![image](https://user-images.githubusercontent.com/63645600/79221317-f6f27600-7e2b-11ea-8c90-3b9dba9d429c.png)

Common folder
 [https://drive.google.com/file/d/1AtGE8DdFtzlQNIJyvJFDIV3A7LbuZz6L/view?usp=sharing](url)

**Comment by minhcasi** [comment]
@n4solutions - please update the latest mstore-api - we have hidden the verify purchase for a while due to the server problem issue - thank you!
