### ISSUE TITLE
[Fluxstore] - 

### ISSUE THREAD

**Issue by qorane099** [inspireui/support#2716]
the app is getting crashed with a of "connection lost"

please and please help me to fix this issue.

this is not first, l did configured the app a week ago and becouse of issue l did delete the whole and downloaded fresh source from envato.
 
the issue come again, please investigate this issue and try your best to help.

l did configured the whole app, everything is working fine. but only this issue.
![IMG_20200402_185743](https://user-images.githubusercontent.com/39888242/79228510-2da5ac00-7e7f-11ea-8dd0-373dea2cb861.jpg)
![IMG_20200402_201209](https://user-images.githubusercontent.com/39888242/79228522-30a09c80-7e7f-11ea-8d81-118eb49b020b.jpg)

**Comment by minhcasi** [comment]
@qorane099 - could you help to check if the MainActivity is the same as this screenshot - https://tppr.me/hQub4 

There is a known issue on the previous 1.6.6 and have also updated the patching on the latest 1.6.6b - than you!

**Comment by qorane099** [comment]
They are not same.

l checked the screen shot and they are not same

**Comment by minhtruong315** [comment]
@qorane099 I sent you the solution  on skype. please let me know the result. thanks

**Comment by minhcasi** [comment]
Please try to replace the latest MainActivity from 1.6.6b release, it could fix your issues, please help to give extra conversation to Truong via Skype - thank you so much for your time :)
