### ISSUE TITLE
[fluxstore] - 

### ISSUE THREAD

**Issue by mk4full** [inspireui/support#2718]
1. My issue:
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\src\FluxStore-woo 1.6.6b\source\android\app\build.gradle' line: 24

* What went wrong:
A problem occurred evaluating project ':app'.
> Failed to apply plugin [id 'com.android.internal.version-check']
   > Minimum supported Gradle version is 5.6.4. Current version is 5.4.1. If using the gradle wrapper, try editing the distributionUrl in C:\src\FluxStore-woo 1.6.6b\source\android\gradle\wrapper\gradle-wrapper.properties to gradle-5.6.4-all.zip

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
Finished with error: Gradle task assembleDebug failed with exit code 1

3. Proof of my purchased (required): [url=https://ibb.co/ZNqQ59N][img]https://i.ibb.co/kMNLjZM

**Comment by minhcasi** [comment]
@mk4full - this issue is caused by missing Flutter SDK config or not run the "flutter pub get" - please also check this guide to clean the cache - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

**Comment by mk4full** [comment]
thank you, I will check
