### ISSUE TITLE
[Mstore] - Product Quantity Issue

### ISSUE THREAD

**Issue by CloudExpressTeam** [inspireui/support#2719]
Hi, hope you all are in safe zone from COVID-19 and other diseases

Regarding to Mstore app, when we attempt to add product quantity it adds till 10 products regardless the number of apps in woocommerce stock!

It only display that product if it's expired from stock, but if there's 1 item ==> any number can be added to the cart!

So, Please make the api correctly achieve this

**Comment by CloudExpressTeam** [comment]
![Screenshot_2020-04-14-21-27-21-741_com cloudexpress zooy](https://user-images.githubusercontent.com/34522710/79266268-97ca4b00-7e97-11ea-8fe7-1d18c1908d63.jpg)

The first product only has 3 items in stock

The second product has 26 items in stock

I can only add 10 items regardless the stock quantity

Help please

**Comment by minhcasi** [comment]
Hi, thank you for the feedback. Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads it's used to verify your proof of purchase? 
Sorry for any inconvenience, we will reopen the ticket when it is verified, thank you!

**Comment by CloudExpressTeam** [comment]
Hi, Refer to this issue we have sent you the purchase code and you have confirmed the code!
https://github.com/inspireui/support/issues/2398

**Comment by CloudExpressTeam** [comment]
Hi, Any help please?

**Comment by CloudExpressTeam** [comment]
????

**Comment by minhcasi** [comment]
@CloudExpressTeam - sorry as i did not check on the ticket - confirm it is verified

I'm not sure to understand your point from the ticket, please help me to share the screenshot or video on this UX - thank you so much for your time

**Comment by CloudExpressTeam** [comment]
![Screenshot_2020-04-16-10-14-47-237_host exp exponent](https://user-images.githubusercontent.com/34522710/79431806-360afd80-7fcb-11ea-973a-c4c57e64a939.jpg)

In cart quantity I need to replace the LimitAddToCart as it's 10 to be product.stock_quantity

As some products have 3 items in stock
And others have 32 items
So I need to make it dynamic based on product stock_quantity  value

**Comment by CloudExpressTeam** [comment]
??

**Comment by minhcasi** [comment]
Try to customize this file - thanks

<img width="1050" alt="Screen Shot 2020-04-16 at 19 41 12" src="https://user-images.githubusercontent.com/1459805/79457327-3d0d2c80-801a-11ea-9b3a-9b8675323a58.png">

**Comment by CloudExpressTeam** [comment]
I've tried
But can't make the condition with product.stock_quantity

It gives error and crash

**Comment by CloudExpressTeam** [comment]
I need to replace this
< Constants.LimitAddToCart
To
< product.stock_quantity

**Comment by minhcasi** [comment]
i see - thank you!
