### ISSUE TITLE
[BeoNews] Android Studio open and get this error messages

### ISSUE THREAD

**Issue by pitter1104** [inspireui/support#272]
Hello, I have everything installed according to instructions (on the CeBuilder). Have the app with Androis Studio open and get these error messages:
![androis-studio-error](https://user-images.githubusercontent.com/39645285/52481729-9e807280-2baf-11e9-9cd1-62bc7d5d587f.jpg)
![androis-studio-error](https://user-images.githubusercontent.com/39645285/52481747-a9d39e00-2baf-11e9-8601-33c0dea276f4.jpg)
![androis-studio-error](https://user-images.githubusercontent.com/39645285/52481766-b3f59c80-2baf-11e9-8944-66c6ae411e25.jpg)

ERROR: The minSdk version should not be declared in the android manifest file. You can move the version from the manifest to the defaultConfig in the build.gradle file. Remove minSdkVersion and sync project Affected Modules: app

WARNING: The specified Android SDK Build Tools version (27.0.3) is ignored, as it is below the minimum supported version (28.0.3) for Android Gradle Plugin 3.3.1. Android SDK Build Tools 28.0.3 will be used. To suppress this warning, remove “buildToolsVersion ‘27.0.3’” from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools. Remove Build Tools version and sync project Affected Modules: app, lottie-react-native, react-native-admob, react-native-blur, react-native-fast-image, react-native-fbsdk, react-native-linear-gradient, react-native-onesignal, react-native-vector-icons, react-native-webview

WARNING: Configuration ‘compile’ is obsolete and has been replaced with ‘implementation’ and ‘api’. It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html Affected Modules: app, react-native-admob, react-native-blur, react-native-onesignal, react-native-vector-icons

WARNING: Configuration ‘testCompile’ is obsolete and has been replaced with ‘testImplementation’. It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html Affected Modules: react-native-onesignal

WARNING: API ‘variant.getMergeAssets()’ is obsolete and has been replaced with ‘variant.getMergeAssetsProvider()’. It will be removed at the end of 2019. For more information, see https://d.android.com/r/tools/task-configuration-avoidance. To determine what is calling variant.getMergeAssets(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace. Affected Modules: app

WARNING: The targetSdk version should not be declared in the android manifest file. You can move the version from the manifest to the defaultConfig in the build.gradle file. Remove targetSdkVersion and sync project Affected Modules: app

**Comment by minhcasi** [comment]
Hi, just update that we received your ticket and the team will back to check on Monday, sorry for the delay - thank you!

**Comment by luyx2412** [comment]
Hi @pitter1104 

- The first ERROR, you can read the article https://github.com/react-native-community/react-native-localize/issues/16 to fix the issue.
- And another WARNING, you do not care about it. It is just the warning.

Thanks

**Comment by pitter1104** [comment]
Now the next Error
![next error](https://user-images.githubusercontent.com/39645285/52568160-44311d00-2e0e-11e9-9fc4-49e90bdb310f.jpg)

**Comment by pitter1104** [comment]
can you help me?

**Comment by luyx2412** [comment]
HI @pitter1104 Please read the article to fix your issue https://medium.com/@adityasingh_32512/solved-unable-to-load-script-from-assets-index-android-bundle-bdc5e3a3d5ff

Thanks

**Comment by pitter1104** [comment]
Super thank you!
Now running on Android studio, but in emulator I see the website of Beonews and not my website.
I entered the following in config.js:
URL: {
root: 'https: // my-site'
},
Nevertheless, I only see those of Beonews
![beonews](https://user-images.githubusercontent.com/39645285/52647531-34d0d300-2ee5-11e9-8066-78a1a24515e7.jpg)

**Comment by luyx2412** [comment]
HI @pitter1104 Please uninstall the app and re-install again. Because we are using redux which cache store.

Thanks
