### ISSUE TITLE
[fluxstore pro] - Apple Sign in Not working Due to which app rejected

### ISSUE THREAD

**Issue by tjain90** [inspireui/support#2720]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: Apple sign in ask all the information then throws "Waiting error" once password is provided. Smilarly once facebook sign in done app crashes and closed.is there any way to fix else i am fine if we can remove these two signin from ios devices. Kindly Guide me to remove these sign in from IOS or fix this issue.

2. Screenshots issues (required):

3. Proof of my purchased (required): tjain90@gmail.com from themeforest

3. Config files (required)

**Comment by minhcasi** [comment]
Hi could you share the screenshot issue

The login form could be customized on this file - https://tppr.me/YOp0H

**Comment by tjain90** [comment]
![IMG-20200415-WA0009~2](https://user-images.githubusercontent.com/6376301/79335709-167ac300-7f40-11ea-9cc5-ab2325e6013b.jpg)
![IMG-20200415-WA0011](https://user-images.githubusercontent.com/6376301/79335713-17abf000-7f40-11ea-8484-8c6868cc078e.jpg)

here it is. 
On Apple sign in - Error and facebook sign in it crashed.

can you let me know the way to remove apple sign-in and facebook sign in from ios login page. Which variable i can use  so that it can check ios or android.

**Comment by minhcasi** [comment]
@tjain90 - you can remove it on this file https://tppr.me/gmdve - we have added the config option to allow hide these features on the next release - thank you!

**Comment by tjain90** [comment]
Thanks. On temporary basis i have commented facebook element and apple sign in element.

**Comment by tjain90** [comment]
Now when  i have removed apple login, it is rejected station below reason:
"We noticed that your app uses a third-party login service but does not offer Sign in with Apple."

**Comment by sodhanii** [comment]
Hi, my app got rejected for the same reason. I'd commented out Sign in with Apple. Its some Firebase database issue I think. Don't we have to enter database URL for firebase somewhere?

**Comment by tjain90** [comment]
@sodhanii I have commented all logins like sms, facebook , gmail and apple.and it got approved.You can do this if you want to launch it and in next version you can update this.

**Comment by minhcasi** [comment]
@tjain90 - thank you for your sharing

**Comment by sodhanii** [comment]
@minhcasi - how can you close the issue if you haven't provided with the updated code for Apple Login?

**Comment by minhcasi** [comment]
@sodhanii - there are no issues with the Apple login as you can see our demo app is online with Apple SignIn 

If your app already goes live, you could try to enable it again on next time, by order, the Apple Sign in on top of the list buttons to see if they can approve again. 

We will also update code on next release 1.6.7 - let us know if you have any question to same ticket #2760 - kindly just open 1-ticket to put your conversion there - thank you for your time

**Comment by sodhanii** [comment]
Apparently, your backend plugin for Magento doesn't really have any routes for Apple login as I've mentioned in my other ticket. #2749 

So please provide updated code.
