### ISSUE TITLE
[Flutter E-commerce Full App] - Sign in with social login dose not work

### ISSUE THREAD

**Issue by EhapAlazerk11** [inspireui/support#2721]
1. My issue:
hi i am follow docs website and videos to setup the app but  when setup sign in with gmail and sms phone and facebook option they are do not work i created firebase project with my bundle id and i get the SHA1 key but first
 when try to login by gmail :the issue print me 
"Warning there is an issue with app during request the 
data , please contact admin for fixing the issues PlatformException(sign_in_failed,com.google.android.gms.common.api.ApiEx caption:10 :,null)"

for sms excption:
Warning : This app is not authorized to use firebase Authentication .Please verify that the correct package name and SHA-1 key are configured in firebase console app vaildation error

for facebook i will add screen shot in screen shot section for all message error . 

2. Screenshots issues (required):
screen for gmail error:
https://ibb.co/t80rKLP
screen for sms error :
https://ibb.co/jLLKKrs
screen for facebook error:
https://ibb.co/DLL0MZt
3. Proof of my purchased (required):
screen shoot 👍 
https://ibb.co/CMfX3m4
purchase code : c898885e-3cd3-4dcb-8886-dabee2117fa6

3. Config files (required)
https://safenote.co/r/5e9622c7de1160@46437504
the file of firebase config : 
https://safenote.co/r/5e962415e531c1@33606888

**Comment by EhapAlazerk11** [comment]
Please reply me fast it very important to publish fast on play store

**Comment by trunghieuvn** [comment]
Please give me the config and common folder again, it looks like the link you sent has expired. 
Thanks.

**Comment by EhapAlazerk11** [comment]
hi trunghieuvn, i upload all you need in the link please pro replay fast it is critical time for me must be in play store in just one day left .
thanks,

**Comment by trunghieuvn** [comment]
Sorry but the information you sent me is not enough for me to check what the error is, please provide more information.
It would be nice if you send me the source you are using so I can check each of your configuration files.
Thanks.

(Send the file to this link: http://verify.inspireui.com/)

**Comment by EhapAlazerk11** [comment]
I solve the problem by add the realase key and the debug key to firebase
consle but the realase key i get by mstore. lockstore file in app path,
Is this key store file must change or what
Second i get error for cart shop page pressent error i attatch image for it
Third map auto fill option getting me this message i will attatch image for
the massage
Thanks please reply fast

**Comment by trunghieuvn** [comment]
Sorry to keep you waiting. I will check it quickly for you, please provide me more information about your source code here (http://verify.inspireui.com/). I will check and respond to you as soon as I finish solving them.

Best send me your source code or github / gitlab repo link, I will easily reproduce these errors and fix them quickly.
Thanks.
