### ISSUE TITLE
[FluxNews] - Default Language 

### ISSUE THREAD

**Issue by AhmedDarwish660** [inspireui/support#2723]
Hello 

My problem in changing the Default Language to arabic , i already change it in config.dart file but its not changing in the app

**Comment by AhmedDarwish660** [comment]
<img width="1199" alt="Screen Shot 2020-04-15 at 2 10 29 AM" src="https://user-images.githubusercontent.com/61433090/79282620-5731f800-7ebe-11ea-98c7-616a6777f4aa.png">

**Comment by dttrung26** [comment]
Hi @AhmedDarwish660 , please send me your /lib/models/app.dart for checking. Have a nice day!
