### ISSUE TITLE
MStore Multi Vendor - Complete React Native template for WooCommerce

### ISSUE THREAD

**Issue by anandkausha** [inspireui/support#2724]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: node_modules directory is missing. Please run `npm install` in your project directory.

Errors are as follows 
Publishing to channel 'default'...
Error: node_modules directory is missing. Please run `npm install` in your project directory.
Couldn't publish because errors were found. (See logs above.) Please fix the errors and try again.

D:\Dolphin Techno\Multi Vendor\APP Development\mstore-mv-expo>npm install
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated core-js@1.2.7: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\jest-haste-map\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/naver/hammer.js.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

2. Screenshots issues (required):!
![222](https://user-images.githubusercontent.com/63690210/79307405-7ce9ec00-7f14-11ea-8ccc-87a4c847eefc.png)

3. Proof of my purchased (required):
![purchase](https://user-images.githubusercontent.com/63690210/79292123-fc17f980-7eed-11ea-9513-6fcb4c69976d.png)

3. Config files (required)[Config.zip](https://github.com/inspireui/support/files/4478769/Config.zip)

**Comment by anandkausha** [comment]
Now, I am Facing another Error.  Please check updated error in above

**Comment by flapron** [comment]
Hi, I'm facing the same problem, what is the solution?

**Comment by luyx2412** [comment]
Hi @anandkausha Can you share me the `node` version? or you can use the yarn which same npm, but it support React native better https://yarnpkg.com/

Thanks
