### ISSUE TITLE
[Fluxstore - WooCommerce] - IOS 

### ISSUE THREAD

**Issue by Madraka** [inspireui/support#2725]
1. My issue:
Guideline 2.1 – Performance – App Completeness

We discovered one or more bugs in your app when reviewed on iPad running iOS 13.3 on Wi-Fi.

Specifically, we received a blank page on attempting to check out.

Next Steps

To resolve this issue, please run your app on a device to identify any issues, then revise and resubmit your app for review.

If we misunderstood the intended behavior of your app, please reply to this message in Resolution Center to provide information on how these features were intended to work.

For new apps, uninstall all previous versions of your app from a device, then install and follow the steps to reproduce the issue. For updates, install the new version as an update to the previous version, then follow the steps to reproduce the issue
---------

2. Screenshots issues (required):

https://ibb.co/287rrgf

3. Proof of my purchased (required):
https://ibb.co/qxfBP3L

3. IOS TestFlights (required)
https://ibb.co/k6fWBnj

**Comment by minhcasi** [comment]
@Madraka could you share the attache screenshot from Appstore on above issue?

**Comment by Madraka** [comment]
> @Madraka could you share the attache screenshot from Appstore on above issue?

https://ibb.co/JBTp0NX

**Comment by minhcasi** [comment]
@Madraka - could i confirm this issue has happened on the latest version 1.6.6b? Could you able to reproduce on iPad as well ? Thank you!

**Comment by Madraka** [comment]
> @Madraka - could i confirm this issue has happened on the latest version 1.6.6b? Could you able to reproduce on iPad as well ? Thank you!

Yes latest version 1.6.6B

**Comment by minhcasi** [comment]
@Madraka - could you mind to check the latest 1.6.7 - we have fixed some major bug of this version - thank you!

If you would like to keep to previous version, you could try to upgrade the flutter to latest stable version 
```
flutter channel stable
flutter upgrade --force
```
Or check the detail log from XCode when open ipad to see if there any crash issues 

Very best!
