### ISSUE TITLE
[FluxStore Pro] - Image Product Issue

### ISSUE THREAD

**Issue by xLidoni** [inspireui/support#2726]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:

Hello, present this problem with the product images, they practically cut themselves.

I followed the guide to generate thumbnails, they are generated correctly. But the problem persists.

Possible solutions?

Thanks!

2. Screenshots issues (required):

![image](https://user-images.githubusercontent.com/11965301/79322852-b2d7a200-7f0d-11ea-90c0-addcc1f57ee2.png)

3. Proof of my purchased (required):
![image](https://user-images.githubusercontent.com/11965301/79322896-c08d2780-7f0d-11ea-9943-5ae34f770812.png)

3. Config files (required)

**Comment by minhcasi** [comment]
@xLidoni - could you try to adjust the product image height from the config file https://tppr.me/hvYpO

**Comment by minhcasi** [comment]
Please move your all conversation to the same #2722 - thank you!
