### ISSUE TITLE
ListingPro fluxlisting[my-product] - 

### ISSUE THREAD

**Issue by egortretyakov** [inspireui/support#2727]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: Photo of category doesnt work, photo of product not show, category items r not showing

2. Screenshots issues (required): 
![Снимок экрана 2020-04-15 в 15 17 33](https://user-images.githubusercontent.com/62143162/79336440-6a7bac80-7f2c-11ea-8811-a90f4fa9a396.png)

3. Proof of my purchased (required):
![Снимок экрана 2020-04-15 в 15 19 26](https://user-images.githubusercontent.com/62143162/79336488-841cf400-7f2c-11ea-8737-851a2fa7a0af.png)

3. Config files (required)
{
  "HorizonLayout": [
    {
      "layout": "logo",
      "hideLogo": true
    },
    {
      "layout": "header_search",
      "radius": 6.0,
      "text": {
        "en": "Search for a product",
        "ar": "بلوق وظائف",
        "vi": "Tìm kiếm"
      }
    },

    {
      "layout": "header_text",
      "fontSize": 20.0,
      "padding": 20.0,
      "title": "What can we help you find?"
    },

    {
      "layout": "category",
      "type": "image",
      "size": 1.0,
      "radius": 50.0,
      "items": [
        {
          "category": 54,
          "showText": true,
          "name": "Bars&Pubs",
          "image": ""
        },
        {
          "category": 97,
          "showText": true,
          "name": "Beach",
          "image": "https://gettripon.com/wp-content/uploads/2020/01/98959-plyazh-london-nebo-poberezhe-karibskij_bassejn-1366x768-1.jpg"
        },
        {
          "category": 30,
          "showText": true,
          "name": "Beauty & Spa",
          "image": "https://gettripon.com/wp-content/uploads/2020/01/Aurora-Spa-Chiswick-Body-Treatments-1.jpg"
        },
        {
          "category": 119,
          "showText": true,
          "name": "Car/Bike rent",
          "image": "https://gettripon.com/wp-content/uploads/2020/01/Mercedes-Benz-SLK55-AMG-and-Ducati-Streetfighter-848-2011.jpg"
        },
        {
          "category": 96,
          "showText": true,
          "name": "Night life",
          "image": "https://gettripon.com/wp-content/uploads/2020/01/bg-nightlife.jpg"
        },
        {
          "category": 1215,
          "showText": true,
          "name": "Other",
          "image": "https://gettripon.com/wp-content/uploads/2020/01/1.jpg"
        }
      ]
    },
    {
      "name": "Coming Events",
      "layout": "twoColumn",
      "category": 34
    },
    {
      "layout": "bannerImage",
      "isSlider": true,
      "autoPlay": true,
      "showNumber": false,
      "design": "default",
      "showBackGround": true,
      "radius": 10.0,
      "height": 0.5,
      "items": [
        {
          "category": 29,
          "image": "https://trello-attachments.s3.amazonaws.com/5dd3a1ccf77d834e86dfd29a/1100x1292/7beb8a56f7db49bc0e147ec5040deb50/travel2.jpg",
          "padding": 20.0
        },
        {
          "category": 37,
          "image": "https://trello-attachments.s3.amazonaws.com/5dd3a1ccf77d834e86dfd29a/1100x1292/19369c86e6873fc2493da1e397fa6e27/travel3.jpg",
          "padding": 20.0
        },
        {
          "category": 34,
          "image": "https://trello-attachments.s3.amazonaws.com/5dd3a1ccf77d834e86dfd29a/1160x1362/4a1f8758322c3f5dc862c5bf7a9c5af3/travel5.jpg",
          "padding": 20.0
        }
      ]
    }
  ],
  "VerticalLayout": {
    "name": "Explore more",
    "layout" : "menu"
  },
  "Setting": {
    "MainColor": "#3FC1BE",
    "ProductListLayout": "list"
  },
  "TabBar": [
    {
      "layout": "home",
      "icon": "assets/icons/tabs/icon-home.png"
    },
    {
      "layout": "category",
      "categoryLayout": "card",
      "icon": "assets/icons/tabs/icon-category.png"
    },
    {
      "layout": "search",
      "icon": "assets/icons/tabs/icon-search.png"
    },
    {
      "layout": "profile",
      "icon": "assets/icons/tabs/icon-user.png"
    }
  ]
}

**Comment by egortretyakov** [comment]
any updates?

**Comment by philipvu30** [comment]
Hi,

Please send the common folder to this email: toan@inspireui.com.

Thanks

**Comment by egortretyakov** [comment]
hi,
done check plz mail box

**Comment by philipvu30** [comment]
Received

**Comment by egortretyakov** [comment]
Hello, 2 days past and no help

**Comment by philipvu30** [comment]
Hi,

Sorry for the late response. 
Please follow this topic [2522](https://github.com/inspireui/support/issues/2522). You can find solution for your issue and future bugs here. Thanks
