### ISSUE TITLE
[my-product] - flex store 1.6.6b error when i send order

### ISSUE THREAD

**Issue by ramyragab1** [inspireui/support#2728]
1. My issue:
error when i send order

2. Screenshots issues (required):
https://www.dropbox.com/s/64ng0c7fgi6o1xf/Screen%20Recording%202020-04-15%20at%207.57.10%20PM.mp4?dl=0

3. Proof of my purchased (required):
https://www.dropbox.com/s/hk4b3zm5sq7dhu0/Screen%20Shot%202020-01-11%20at%205.02.03%20PM.png?dl=0

**Comment by ramyragab1** [comment]
same error when i do register in app

**Comment by minhcasi** [comment]
@ramyragab1 - could you attache config file so that we could help for checking

**Comment by ramyragab1** [comment]
[https://www.dropbox.com/s/1rqlxti5v7awb5p/Archive%202.zip?dl=0](url)

**Comment by ramyragab1** [comment]
https://www.dropbox.com/s/1rqlxti5v7awb5p/Archive%202.zip?dl=0

**Comment by ramyragab1** [comment]
any update

**Comment by minhtruong315** [comment]
<img width="1058" alt="Screen Shot 2020-04-20 at 9 53 12 AM" src="https://user-images.githubusercontent.com/10402500/79709653-f7d44d80-82ec-11ea-8737-787242cacda7.png">
did you  allow write?
<img width="1248" alt="Screen Shot 2020-04-20 at 9 55 10 AM" src="https://user-images.githubusercontent.com/10402500/79709711-20f4de00-82ed-11ea-8013-8e79fe64250d.png">
 permission?

**Comment by ramyragab1** [comment]
<img width="767" alt="Screen Shot 2020-04-20 at 6 01 55 AM" src="https://user-images.githubusercontent.com/22369453/79712941-94d2be80-82cc-11ea-9a32-ab8dd7164a60.png">
yes its read and write

**Comment by minhtruong315** [comment]
@ramyragab1 can u send me admin account via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/2728

**Comment by ramyragab1** [comment]
> @ramyragab1 can u send me admin account via email: [truong@inspireui.com](mailto:truong@inspireui.com)
> with subject: #2728

sent

**Comment by minhtruong315** [comment]
@ramyragab1 can u change updateOrder function  in services/woo_commerce.dart
```
@override
  Future updateOrder(orderId, {status, token}) async {
    try {
      var response = await wcApi
          .postAsync("orders/$orderId", {"status": status}, version: 2);
      if (response["message"] != null) {
        throw Exception(response["message"]);
      } else {
        return Order.fromJson(response);
      }
    } catch (e) {
      //This error exception is about your Rest API is not config correctly so that not return the correct JSON format, please double check the document from this link https://docs.inspireui.com/fluxstore/woocommerce-setup/
      rethrow;
    }
  }
```

**Comment by ramyragab1** [comment]
thanks mate great work can you see my mail 
thanks

**Comment by minhtruong315** [comment]
it shows this error: You don't have permission to access /noor/wp-json/api/flutter_user/register/
on this server.

Can you try to set permission for folder website?

**Comment by ramyragab1** [comment]
i cant find this path /noor/wp-json/api/flutter_user/register/
i do set permission to all folder and file

**Comment by minhtruong315** [comment]
@ramyragab1 can u try to change to subdomain instead of sub folder
http://adsprou.com/noor to http://noor.adsprou.com

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!

**Comment by ramyragab1** [comment]
thanks mate problem fixed
