### ISSUE TITLE
[fluxnews] - Help with SHA-1

### ISSUE THREAD

**Issue by haidarsalim** [inspireui/support#2729]
Possible way to extract the project's SHA1
![11](https://user-images.githubusercontent.com/54249914/79383237-86ec0900-7f6d-11ea-8486-8e3e18811209.JPG)

Another question is how to open the project on xcode
Do I need to install flutter for Mac?

![22](https://user-images.githubusercontent.com/54249914/79383675-3fb24800-7f6e-11ea-9dc1-49759510d24a.JPG)

**Comment by minhcasi** [comment]
@haidarsalim - could you help to check the similar guide on this video regarding to SHA1- https://www.youtube.com/watch?v=C_9mk_MmvOQ&feature=emb_logo

(09:30) Update the SHA keys on Firebase to match with your app
