### ISSUE TITLE
[MStore MV] Product Variations not working

### ISSUE THREAD

**Issue by Foxxerman** [inspireui/support#273]
**Mandatory Info (please complete the following information):**
 - Product: [MStore Multi-vendor]
 - Your Purchased Code: [bfab9b07-5fe7-452b-9b5b-ff3a842c730a]
(we may not reply if you are not our customer)

**Describe the issues**
1) How can I set minimum purchase quantity for products?
2) Price doesn't change when selecting variations
3) The URL of your installation document is invalid

**Screenshots**

**Additional context**
Add any other detail logs about the problem here.

**Comment by minhcasi** [comment]
Hi, just update that we received your ticket and the team will back to check on Monday, sorry for the delay - thank you!

**Comment by Foxxerman** [comment]
Hi, any updates?
    Minh Pham (<notifications@github.com>) 在 2019年2月9日 星期六 上午11:15:37 [GMT+8] 寫道：  
 
 
Hi, just update that we received your ticket and the team will back to check on Monday, sorry for the delay - thank you!

**Comment by thangvo9x** [comment]
Hi. You can try to go to src/containers/Detail/index.js line 81 => uncomment it and restart the app.
Thanks

**Comment by thangvo9x** [comment]
Try here https://github.com/inspireui/support/issues/1#issuecomment-462592262

**Comment by Foxxerman** [comment]
Thanks, will try then
    thangvo9x (<notifications@github.com>) 在 2019年2月12日 星期二 上午10:46:23 [GMT+8] 寫道：  
 
 
Try here #1 (comment)

**Comment by Foxxerman** [comment]
Hi, may I know how to set the minimum quantity for purchasing?
    Fox Fox (<editorialfox@yahoo.com.hk>) 在 2019年2月12日 星期二 上午10:47:41 [GMT+8] 寫道：  
 
  Thanks, will try then
    thangvo9x (<notifications@github.com>) 在 2019年2月12日 星期二 上午10:46:23 [GMT+8] 寫道：  
 
 
Try here #1 (comment)

**Comment by thangvo9x** [comment]
Hi. You can enable manage stock quantity on your site.

**Comment by Foxxerman** [comment]
But it is not working, any ideas?
    thangvo9x (<notifications@github.com>) 在 2019年2月12日 星期二 下午5:44:43 [GMT+8] 寫道：  
 
 
Hi. You can enable manage stock quantity on your site.
