### ISSUE TITLE
[Woocommerce Fluxstore] - How do I integrate the Smartchat button on Categories & Search pages?

### ISSUE THREAD

**Issue by lemarchexpress** [inspireui/support#2730]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
Integration Guide of the Smartchat Element
I would like to included in the Static Page & 
Categories or Search Pages

2. Screenshots issues (required):
No Apply
3. Proof of my purchased (required):
![image](https://user-images.githubusercontent.com/63209110/79383654-d3cbe180-7f65-11ea-9c40-0a47d26a6460.png)

4. Config files (required)
No Apply

**Comment by dttrung26** [comment]
Hi @lemarchexpress , 
To add smartchat feature in your search screen, download and replace search.dart into your /lib/screens/search
To add smartchat feature in your static page, download and replace index.dart into your /lib/pages
Hope this helps.
[ticket_support#2730.zip](https://github.com/inspireui/support/files/4485751/ticket_support.2730.zip)

Happy coding!

**Comment by lemarchexpress** [comment]
Thanks! it works perfectly... :)
