### ISSUE TITLE
[fluxstore] - error sing in

### ISSUE THREAD

**Issue by mk4full** [inspireui/support#2731]
2. Screenshots issues (required): https://www.youtube.com/watch?v=IKD4zXYaKnc - error, first I try sing in via sms, next fb, and last I try google - I can not, occour error, can u tell what wrong I do?

3. Proof of my purchased (required): https://i.ibb.co/kMNLjZM

**Comment by minhcasi** [comment]
@mk4full - pls check the SHA1 issue on this link https://docs.inspireui.com/fluxstore/common-issues/#-login-with-sms-login-in-play-store

Or video https://www.youtube.com/watch?v=C_9mk_MmvOQ&t=621s (09:30) Update the SHA keys on Firebase to match with your app

**Comment by mk4full** [comment]
@minhcasi 

![formatexception](https://user-images.githubusercontent.com/55841331/79586573-97b58f80-80d1-11ea-9af0-d433494bfe3c.PNG)

I fixed SHA keys and changed facebook to live mode. I still get this error after logging in with facebook

**Comment by mk4full** [comment]
![google login](https://user-images.githubusercontent.com/55841331/79587554-00513c00-80d3-11ea-9068-b0594e0739e8.PNG)
And this error when I login with google

**Comment by danielito-1** [comment]
yo tengo el mismo problema 

lo soluciono ?
