### ISSUE TITLE
[my-product] - Cant connect wooocommerce api for Fluxstore Pro

### ISSUE THREAD

**Issue by Cheewingtan** [inspireui/support#2733]
**Step 1:** detail issues and screenshots

I follow the guild to create woocommerce API and change the code but it doesn't working and I check https://www.wingsshops.com/wp-json/wc/v3/ it doesn't show anything ,it is my SSL block the API ? I'm using lets encrypt SSL 
![Screenshot 2020-04-16 at 1 00 09 PM](https://user-images.githubusercontent.com/11556877/79416577-948fa600-7fe2-11ea-944c-c23db976900b.png)
![Screenshot 2020-04-16 at 1 00 28 PM](https://user-images.githubusercontent.com/11556877/79416587-98bbc380-7fe2-11ea-9c95-0655ec24af99.png)

**Step 2:** verify license and sharing config files via this google form - http://private.inspireui.com

*Note: please submit ticket support by following above 2 require steps, we may close the ticket without providing full information.*

**Comment by minhcasi** [comment]
@Cheewingtan - could you try to enable the debug mode from wp-config.php from wordpress site to see any warning the error log from PHP server?

**Comment by Cheewingtan** [comment]
> @Cheewingtan - could you try to enable the debug mode from wp-config.php from wordpress site to see any warning the error log from PHP server?

it display this on my screen
![Screenshot 2020-04-19 at 4 32 55 PM](https://user-images.githubusercontent.com/11556877/79683264-813b3f80-825b-11ea-873f-2ed2a593cb1a.png)
