### ISSUE TITLE
👉Important Notice - please read me 🌻

### ISSUE THREAD

**Issue by minhcasi** [inspireui/support#2734]
Dear customers,

After 16/04/2020, we would like to change the submit ticket process by update the 2 simple steps: 
- Step 1: require the detail issues and screenshots from the issues, please help to provide as detail as possible that will help us to find out the issue quickly.
- Step 2: Please verify license and sharing config files by submitting on this google form, http://private.inspireui.com, In this way your private config, license detail or any credential will be protected and kept private, then it will be removed up after we resolved the ticket.

We are working hard to support you better, please give us around 24 hours to investigate and respond to the ticket, also note that we may close the ticket without providing full information from the above steps, the closed ticket support could be deleted from our Github repo after 3 months.

Let us know if you have any feedback ❤️

**Comment by digirizon** [comment]
should I post  my issues here ?

**Comment by Roupasafricanas** [comment]
sim, pode sim

**Comment by saifmuhtar** [comment]
I'm very proud of you guys! Your support always impressed me :)

**Comment by Roupasafricanas** [comment]
Olá, é a primeira vez que eu uso o supporte de vocês e gostaria de saber como funciona. Eu tinha uma duvida e fui redirecionado para esse topio. Devo fazer de novo a pergunta ou só aguardar resposta aqui?  Desde já agradeco

**Comment by sketchuprzr** [comment]
Support issues are already being made late. With this system, it will be further delayed. I did not find the system well.

**Comment by anandkausha** [comment]
Support System is working late and not getting correct solution at that time , so here we face lots of problem to work on project .  Please make error free project

**Comment by sketchuprzr** [comment]
@inspireui
why are you deleting messages? Can people not freely express their thoughts about this system?

**Comment by minhcasi** [comment]
@sketchuprzr - kindly post positive words - thanks
