### ISSUE TITLE
Undefined symbols for architecture x86_64: "_OBJC_CLASS_$_OPPCheckoutProvider", referenced from

### ISSUE THREAD

**Issue by NALAWALAMURTUZA** [inspireui/support#2737]
`Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_OPPCheckoutProvider", referenced from:
      objc-class-ref in FlutterPeachpayPlugin.o
  "_OBJC_CLASS_$_OPPCheckoutSettings", referenced from:
      objc-class-ref in FlutterPeachpayPlugin.o
  "_OBJC_CLASS_$_OPPPaymentProvider", referenced from:
      objc-class-ref in FlutterPeachpayPlugin.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)` 

![Screenshot 2020-04-16 at 1 05 48 PM](https://user-images.githubusercontent.com/8521122/79428399-bc333e00-7fe3-11ea-8e43-be247154f4c9.png)

**Comment by minhcasi** [comment]
@NALAWALAMURTUZA - pls help to submit this https://docs.google.com/forms/d/e/1FAIpQLScWOjkAJIWJ9rgb9alopfOqLsJrGKbFM5cCYj1JBfLKLsBblQ/viewform
