### ISSUE TITLE
[fluxstore] Issue with Login

### ISSUE THREAD

**Issue by mk4full** [inspireui/support#2738]
SMS and Google sign-in is working in emulator but not on physical device, 
facebook login gives "FormatException: Unexpected end of input (at character 1" 

When I shift to physical device 
- Facbook login says "This App is not set up and is still in development mode".
- SMS login just keeps loading and I receive no OTP. (I tested this on emulator and It worked)
- Google sign in fails too ( it worked on emulator .) 

Proof of my purchased (required): https://i.ibb.co/kMNLjZM

**Comment by minhcasi** [comment]
@mk4full - please try to follow the previous conversation on this ticket - #2731

- Enable the Live mode on Facebook to fix the facebook login issue
- The google login could relate to this guide https://docs.inspireui.com/fluxstore/sign-in/#12-in-google-cloud-console-select-your-project-1-then-select-api-service-2-and-choose-oauth-consent-screen-3
