### ISSUE TITLE
[MSTORE-MV] Unable to Proceed with Payment

### ISSUE THREAD

**Issue by nghonyuen** [inspireui/support#274]
**Required Info (please complete the following information):**
 - Product: MStore MV
 - Your Purchased Code: 34a1d23d-c198-4cd8-beec-b4d0881c6437
(we may not reply if you are not our customer)

**Describe the bug**
When trying to complete a purchase it throws the attached error. We are currently using PayPal checkout

**Screenshots**
![img_1863](https://user-images.githubusercontent.com/47480781/52523347-5ce4ea00-2ccb-11e9-835f-d0e4d1701a07.jpg)
![img_1864](https://user-images.githubusercontent.com/47480781/52523348-5f474400-2ccb-11e9-8382-ab3be12d741f.jpg)

**Comment by thangvo9x** [comment]
Hi. Please check your connection and how the other payments?

**Comment by nghonyuen** [comment]
Hi 

Quite positive the connection is working fine. Cause this can be consistently reproduced (so far) and every time I need to reach this stage I believe the system have to retrieve the product list from the WC host. 

Updates: The above was tested on an iPhone, I try again today on an Android phone and it show a Page Not Found response from my WC sites. If you can guide me to how your front end construct the PayPal URL, I maybe able to investigate further. Cheers!

**Comment by thangvo9x** [comment]
Hi. You can try by create a page with Template Name is "Page Custom Template". Thanks

**Comment by nghonyuen** [comment]
Thanks, may I know if any shortcode/page id etc to be configured? Thanks
Did a quick try result as below:

**Comment by thangvo9x** [comment]
Hi. I can't view your image. You have only move to Pages menu create a page with Template Name is "Page Custom Template".

**Comment by thangvo9x** [comment]
Please refer https://github.com/inspireui/support/issues/1#issuecomment-462210490

**Comment by nghonyuen** [comment]
Hi, 

Tried to follow your recommendation. However, I notice the below:
1. If I create a new page with template name = Page Custom Template, it will says Update Failed
2. If I do a quick edit and modify it, while it doesn't throw and error, it actually does not save the template name changes
<img width="1440" alt="screenshot 2019-02-11 at 1 09 51 pm" src="https://user-images.githubusercontent.com/47480781/52546965-a3873100-2dfe-11e9-8d78-91727a82aa06.png">
Please help

**Comment by nghonyuen** [comment]
Updates, managed to fix by installing WP Classic Editor. With the classic version, can change the page attribute to Page Custom Template and it flows to the next screen.

2nd mistake I made is the name of the page seem plays a part. store-checkout is the right name according to https://docs.mstore.io

**Comment by thangvo9x** [comment]
Yes. url should be mstore-checkout. refer https://docs.mstore.io/faq-and-troubleshooting.

**Comment by nghonyuen** [comment]
Hi

I would like to re-open this issue. It turns out that while the issue is solved on Android. On iOS it still shows as NSURLErrorDomain -1005.

**Comment by nqtuyen92** [comment]
> Hi
> 
> I would like to re-open this issue. It turns out that while the issue is solved on Android. On iOS it still shows as NSURLErrorDomain -1005.

Same with me!
