### ISSUE TITLE
Can't Run on my MAC : Gradle task assembleRelease failed with exit code 1

### ISSUE THREAD

**Issue by jeeali** [inspireui/support#2740]
Step 1 (require): detail issues and screenshots
ISSUE: After downloading the FluxStore code. The app is not running. Not even once.
- I've downgraded my Flutter version also.
- I shifted from dev channel to master.
- I deleted old Flutter SDK and clone the new Flutter SDK (master)
Kindly, Resolve or let me know what can I do to resolve this issue.
I can't downgrade my Flutter Version so down. Because I'm working on other projects too.
Give me an authenticate solution. 
~ I've been trying to resolve this issue for two days.

Here is the error I'm getting:

<img width="1230" alt="Screenshot 2020-04-16 at 3 34 36 PM" src="https://user-images.githubusercontent.com/17235314/79446541-c9f2be80-7ff7-11ea-8833-e5664fdca931.png">

Here is the output of "flutter --version":

<img width="563" alt="Screenshot 2020-04-16 at 3 26 59 PM" src="https://user-images.githubusercontent.com/17235314/79445832-b98e1400-7ff6-11ea-9842-b8d680e8d52a.png">

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

<img width="680" alt="Screenshot 2020-04-16 at 3 32 07 PM" src="https://user-images.githubusercontent.com/17235314/79446297-708a8f80-7ff7-11ea-9c00-d037f9b496d1.png">

*Note: please submit ticket support by following above 2 require steps, we may close the ticket without providing full information.*

**Comment by minhcasi** [comment]
@jeeali - this is cause by latest flutter master channel, please try to use this script
```
flutter channel stable
flutter upgrade --force
```

If you would like to switch to multi version, this lib could be help - https://github.com/leoafarias/fvm

**Comment by jeeali** [comment]
> @jeeali - this is cause by latest flutter master channel, please try to use this script
> 
> ```
> flutter channel stable
> flutter upgrade --force
> ```
> 
> If you would like to switch to multi version, this lib could be help - https://github.com/leoafarias/fvm
> 
> > <img alt="" width="48" src="https://avatars3.githubusercontent.com/u/435833?s=400&amp;v=4"><img alt="" height="14" src="https://camo.githubusercontent.com/040b5519c6d1891329f5f6d3e511003657131cf2/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[leoafarias/fvm](https://github.com/leoafarias/fvm)**Flutter Version Management: A simple cli to manage Flutter SDK versions per project - leoafarias/fvm

Thanks for the quick response.
I'll try this one.

Stay Strong,
Sharjeel A.

**Comment by jeeali** [comment]
@minhcasi  This solved the issue.
Thanks

**Comment by jeeali** [comment]
I am working on several projects. Which are using the "FLUTTER WEB".
And Flutter Web is not available in the stable channel.
Kindly, Suggest something. Every project is important to me!!!
@minhcasi

**Comment by jeeali** [comment]
It is also not working on beta channel.

**Comment by jeeali** [comment]
I resolved it with FVM
