### ISSUE TITLE
Fluxstore MV issues from home screen

### ISSUE THREAD

**Issue by sadeq90** [inspireui/support#2743]
Hi,

1- Timer for bannerImage layout is changed to 10 seconds by adding "timer": 10 to the config file and by editing BannerSliderItems.
2- Featured Vendors display only 3 vendors, while in config file "columnCount": 4.
3- Latest Products shows empty but when access to any store I can find the products.

Config file:
`{
  "HorizonLayout": [
    {
      "layout": "bannerImage",
      "isSlider": true,
      "showBackground": true,
      "isBlur": true,
      "padding": 20.0,
      "radius": 20.0,
      "title": "Ramadan Kareem",
      "fontSize": 26.0,
      "isSafeArea": true,
      "showSearch": true,
      "design": "default",
      "autoPlay": true,
      "timer": "10",
      "items": [
        {
          "category": 25,
          "image": "https://user-images.githubusercontent.com/1459805/62834035-2899b880-bc71-11e9-9ed8-4ce1790e0460.jpg"
        },
        {
          "category": 23,
          "image": "https://user-images.githubusercontent.com/1459805/62834034-2899b880-bc71-11e9-956b-64e6d0c35d46.jpg"
        },
        {
          "category": 26,
          "image": "https://user-images.githubusercontent.com/1459805/62834036-29324f00-bc71-11e9-9262-af0b8ceeba87.jpg"
        }
      ]
    },
    {
      "layout": "category",
      "type": "icon",
      "wrap": true,
      "size": 1.2,
      "radius": 50.0,
      "noBackground": true,
      "columns": 4,
      "padding": 10.0,
      "items": [
        {
          "category": 491,
          "image": "assets/icons/categories/cate1.png",
          "colors": [
            "#3CC2BF",
            "#3CC2BF"
          ],
          "originalColor": true
        },
        {
          "category": 313,
          "image": "assets/icons/categories/cate2.png",
          "colors": [
            "#3E6AB5",
            "#3E6AB5"
          ],
          "originalColor": true
        },
        {
          "category": 500,
          "image": "assets/icons/categories/cate3.png",
          "colors": [
            "#53A2CC",
            "#53A2CC"
          ],
          "originalColor": true
        },
        {
          "category": 512,
          "image": "assets/icons/categories/cate4.png",
          "colors": [
            "#53688A",
            "#53688A"
          ],
          "originalColor": true
        }
      ]
    },
    {
      "name": "Featured Vendors",
      "layout": "featuredVendors",
      "columnCount": 4
    },
    {
      "name": "Recent View",
      "layout": "recentView"
    },
    {
      "name": "Latest Products",
      "image": "",
      "layout": "twoColumn",
      "isSnapping": true,
      "category": 276
    },
    {
      "name": "New Collections",
      "layout": "staggered",
      "limit": 20,
      "category": 473
    }
  ],
  "Setting": {
    "MainColor": "#c73e49",
    "ProductListLayout": "list"
  },
  "TabBar": [
    {
      "layout": "home",
      "icon": "assets/icons/tabs/icon-home.png"
    },
    {
      "layout": "category",
      "categoryLayout": "card",
      "icon": "assets/icons/tabs/icon-category.png"
    },
    {
      "layout": "search",
      "icon": "assets/icons/tabs/icon-search.png"
    },
    {
      "layout": "cart",
      "icon": "assets/icons/tabs/icon-cart2.png"
    },
    {
      "layout": "profile",
      "icon": "assets/icons/tabs/icon-user.png"
    }
  ],
  "searchSuggestion": [
    "man",
    "dress",
    "Stitch",
    "ma"
  ]
}`

Screenshots:
![1](https://user-images.githubusercontent.com/32711146/79459332-ceb97180-7ffb-11ea-8bfc-27fdc3caf0d9.png)

![2](https://user-images.githubusercontent.com/32711146/79459385-dd078d80-7ffb-11ea-8da5-fd9e86fa26db.png)

Proof:

![3](https://user-images.githubusercontent.com/32711146/79459727-661ec480-7ffc-11ea-9f3d-2a8713ed31d5.png)

**Comment by philipvu30** [comment]
Hi,

1. Please add this term in your config_**.json
![image](https://user-images.githubusercontent.com/54442328/79714716-e0e92780-82fb-11ea-8ff2-0e3ff6b2e117.png)
2. Currently it only supports max to 3 featured vendors at a time.
3. Please send your common folder to this email: toan@inspireui.com

**Comment by philipvu30** [comment]
Hi,

3. I don't see any category is created in the rest API. Please check your site again. Thanks

**Comment by sadeq90** [comment]
What about the timeframe for banner, because I sat it to 10 seconds and it keep showing for 3 seconds only.

Get BlueMail for Android<http://www.bluemail.me/r?b=15824>
On Apr 22, 2020, at 1:18 PM, philipvu30 <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi,

  1.  I don't see any category is created in the rest API. Please check your site again. Thanks

**Comment by philipvu30** [comment]
Hi,

Please replace this file in lib\widgets\home\banner and set the time like the image I provided. Thanks
[banner_slider_items.zip](https://github.com/inspireui/support/files/4517029/banner_slider_items.zip)
