### ISSUE TITLE
Web App Unable to start (Wordpress)

### ISSUE THREAD

**Issue by Kingdroid1** [inspireui/support#2744]
Step 1 (require): detail issues and screenshots
Although the Wordpress installation is complete but the home page cannot display fully. Find attached screenshot:

![image](https://user-images.githubusercontent.com/40317748/79467244-7c755200-7ff5-11ea-9db7-1818ed8ea17c.png)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

<img width="758" alt="license-purchase" src="https://user-images.githubusercontent.com/40317748/79467121-5780df00-7ff5-11ea-8335-f08f75646732.PNG">

*Note: please submit ticket support by following above 2 require steps, we may close the ticket without providing full information.*

**Comment by minhcasi** [comment]
@Kingdroid1 - please help to check this video guide https://www.youtube.com/watch?v=CEyfZmzBMTw&list=PLcF-HiQy-jOJAD8btGgr_CHcUmYyN8GgY

It seems you have missing config from the Wordpress, try to open database and change the hosting config to new one - please note that if you set as localhost, it may not reached from the simulator

**Comment by Kingdroid1** [comment]
Hello, please I have a new issue.
I particularly don't not like the default Storefront theme that came with the demo web app, so I decided to do a fresh installation of Wordpress and install a new theme of my choice.
Right now what I need help with is how I can integrate with the mobile app such that when I update products and other stuff, it can reflect on the mobile app.
Essentially what I am saying is that you show me how my WordPress app can sync with the mobile app. Thank you and I look forward to your assistance.

**Comment by minhcasi** [comment]
Hi, you can try to follow this guide to install extra plugins for the fresh app and connect with the fluxstore app - https://docs.inspireui.com/fluxstore/woocommerce-setup/#step-2-install-the-required-plugins

This is fresh installing demo via Ditialocean - https://www.youtube.com/watch?v=Q8Q3ywiiV9g&list=PLcF-HiQy-jOJAD8btGgr_CHcUmYyN8GgY&index=11&t=1429s
