### ISSUE TITLE
MStore Pro Installation Issues via CeBuilder (Windows/macOS)

### ISSUE THREAD

**Issue by sauron-tr** [inspireui/support#2746]
Hi,
I tried Windows and macOS.

**with macOS:**
I installed Homebrew, Node10 but you see i have cebuilder error icon:
Terminal ScreenShot: https://prnt.sc/s0oaby
CeBuilder ScreenShot: https://prnt.sc/s0oano

**with Windows:**
CeBuilder ScreenShot: https://prnt.sc/s0ofmy
Everything is OK in CeBuilder than i click to Start. But i am getting this error.

**Via Expo**
App Not working: https://prnt.sc/s0uqz2

**_Update:_**
I tried manual installation via Android Studio. Build worked but app is not working correctly.
Screenshot: https://prnt.sc/s0p9ag

How can i fix all ?

**Comment by minhcasi** [comment]
@sauron-tr - could you try this config guide to fix the image issues - https://docs.inspireui.com/mstore/woo-setting/#product-display-sizes

Please note that the app is quite stable at the current release

**Comment by sauron-tr** [comment]
I did what you said. Nothing has changed.

Please watch this screen record. I submitted to youtube for you.

https://youtu.be/KLqRhF1o8_8
