### ISSUE TITLE
[Fluxstore MV] - Multi Inquires and Issues (Dokan)

### ISSUE THREAD

**Issue by ody911** [inspireui/support#2748]
Step 1 (require): detail issues and screenshots

1- Signup 
- " using the sign up" to create new user for the first time,
after filling all required data, and press Create an account, the screen goes black.

- signup using profile, does not go back to profile page after successul singup i have to press back key?

![Screenshot_20200416-212521](https://user-images.githubusercontent.com/36228917/79497998-eb1fd300-8028-11ea-8b7b-f2095aa4fa5e.jpg)

black screen, i have to click back, application closed then reopen it again.

![Screenshot_20200329-110007_WhatsApp](https://user-images.githubusercontent.com/36228917/79496647-b90d7180-8026-11ea-9816-0e0036fed845.jpg)

2- availability : in stock 

how to show the actual available quantity for each variation instead of in stock and make the quantity added to cart equal to or less than the available quantity ?

![Screenshot_20200416-054341](https://user-images.githubusercontent.com/36228917/79497876-bb70cb00-8028-11ea-9799-0e18848e2bd9.jpg)

3- Create product " variable type" goes to loading for a long time. (without adding the item), 

![Screenshot_20200416-203418](https://user-images.githubusercontent.com/36228917/79496595-a3984780-8026-11ea-829b-662eb0a824f9.jpg)

4- shipping: i am using dokan shipping by vendor, which give the vendor the availablity to add their own shipping for each product based on the state " i have only configured two state shipping which are "cairo and giza", here i have chose cairo as a state in the address, but i see both states are there, and with value of zero ?

while on the site, the only appeared one is the selected state, and with actual vendor shipping price, divided by vendors in the order, so how can i accomplish the same.

![Screenshot_20200413-011211](https://user-images.githubusercontent.com/36228917/79496635-b27efa00-8026-11ea-8429-8e0d7aabb7ca.jpg)

appeared shipping

![Screenshot_20200416-035406](https://user-images.githubusercontent.com/36228917/79496622-adba4600-8026-11ea-935e-0411b85dd62a.jpg)

shipping on site

![site shipping](https://user-images.githubusercontent.com/36228917/79497624-4b624500-8028-11ea-9aed-ac6dd630c8cd.png)

thank you

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

done 

*Note: please submit ticket support by following above 2 require steps, we may close the ticket without providing full information.*

**Comment by ody911** [comment]
inquires,

- how to add order notification for the vendors ?

**Comment by ody911** [comment]
Hello, any update please

**Comment by philipvu30** [comment]
Hi,

We will let you know when they are fixed.

Thanks

**Comment by ody911** [comment]
Thank you for your response

**Comment by philipvu30** [comment]
1. 
 - Please replace Navigator.of(context).pop() to this Navigator.of(context).pushReplacementNamed('/home'). You can find it here: lib/screens/users/registration.dart
![image](https://user-images.githubusercontent.com/54442328/79737249-3ab21780-8325-11ea-953d-8a6dd0b87bf1.png)

 - No. It will automatically navigate you back to previous screen. Do you mean Social Login?
2. We have acknowleged about this issue and it is currently being fixed
3. Currently investigating
4. Currently we only support default shipping by Woocommerce. "Dokan shipping by vendor" will be updated in the future

**Comment by ody911** [comment]
hi back,

thanks for your reply, i have purchased this app due to your claiming of comparability with Dokan and to add items from it, either it is simple or variable, however, i can see there is no compatibility in the time been, either for adding items (simple or variable) , dokan shipping, or even using the current stock of variable item for ordering.

now i can't publish the app due to that, thank you to help overcome all these issues.

![comments](https://user-images.githubusercontent.com/36228917/79752183-2c0f3480-8314-11ea-941a-09682ef618d8.png)

**Comment by philipvu30** [comment]
Hi,

2. Fixed. It will be available in the next update.
3. I have no problem with creating product. May I ask what is your current version of plugin MStore API?
4. We will look further into this matter.

**Comment by ody911** [comment]
Hi Philipvu,

thanks for fixing point number 1 and 2,
for point no. 3 the issue is that when adding new product if it is simple it will be added as a draft, also there are missing options like shipping details, shipping class,
but for variable, it take time to be added and also the variation can not be added from the app, whoever it is posted as a draft with simple type? keep in mind that it also does not have options like simple one for the shipping classes .

for point no. 4 thank you to check it., as i can't operate the app without proper shipping and to show only available shipping for the selected state, shipping zone.

waiting for your feedback, as ship

**Comment by philipvu30** [comment]
Hi

3. Requested options noted. Also if we do not want users to mess up our layout for the demo app so we need to make it draft. You can add this term here to automatically publish the product.

![image](https://user-images.githubusercontent.com/54442328/80095380-068f5e80-8592-11ea-9933-d2f89e916bbc.png)

path: lib/models/product/product_model.dart

If you don't find it in this path, then maybe try to find that function name. Because we have changed the source code in the new upcoming release. Thanks

**Comment by philipvu30** [comment]
Hi,

Just checked with your config and it seems "create product function" is not working properly. May I ask what is your current version of MStore API?

**Comment by ody911** [comment]
> 
> 
> Hi,
> 
> Just checked with your config and it worked but slow. May I ask what is your current version of MStore API?

MStore version  2.3.5

**Comment by ody911** [comment]
> 
> 
> Hi
> 
>     1. Requested options noted. Also if we do not want users to mess up our layout for the demo app so we need to make it draft. You can add this term here to automatically publish the product.
> 
> 
> ![image](https://user-images.githubusercontent.com/54442328/80095380-068f5e80-8592-11ea-9933-d2f89e916bbc.png)
> 
> path: lib/models/product/product_model.dart
> 
> If you don't find it in this path, then maybe try to find that function name. Because we have changed the source code in the new upcoming release. Thanks

noted thank you, i will check it and update

**Comment by ody911** [comment]
the product published but with no category, and regarding the shipping, no shipping are calculated based on the flat rate and application show all available shipping with zero cost.

can you please tell me when the new version will be available ?

**Comment by philipvu30** [comment]
Hi @ody911 ,

Sorry for the late response. 
Would you mind sending me a support account for your site? Need to test it with the new code. 
You can send the account to this email: toan@inspireui.com.

Thanks.

**Comment by ody911** [comment]
Hi Philipvu30,

what kind of account would you like, ftp ? or http?
do you need normal customer / vendor or admin user for the http?

**Comment by philipvu30** [comment]
Hi,

I just need to see the plugins and the product/woo configuration. 
You can send me the admin account if you wish.

**Comment by ody911** [comment]
hi , Data sent to your email, user is support
please don't update me to disable the user when finished checking, also please if you need to change anything on configuration just update me before dont so.

Regards
ody911

**Comment by ody911** [comment]
Hi,

do you have any luck in 
- shipping by vendor method and separated per vendor as the dokan does ?
- shipping class to be calculated.
- shipping to be shown only for selected state ?
- variable product to limit the quantity to only available quantity and user can not order more that actual quantity ?

these are keeping late from my release date, please i argue to help me though all these things.

regards,
ody911

**Comment by philipvu30** [comment]
Hi,

Sorry for the delayed response. Currently, those features are not available yet.

As we cannot cover all the e-commerce businesses, and we have no plan on implementing them, I suggest that you should hire a freelancer to implement those specific features for your app. 

Regards,
Philip

**Comment by ody911** [comment]
hi Philip,

sorry but i did not understand what you are talking about,

first you said currently those features are not available yet, which mean that they will be available but not now, then you are telling me that you cannot cover all the e-commerce businesses ?, i did not ask you to cover it, i only ask you to check the issue on your release as you selling the app and telling everyone that you are compatable with Woocommerce and Dokan, and my request is on the default of Woocommerce and Dokan only i did not ask for any new feature.
then you suggest me to hire a freelanceer to implement the features, while these are not a feature i need to implement out of your scope, it is core woocommerce and dokan.
let me clarify it to you, as i may not be clear enough.
- Shipping by vendor is a tool in the Dokan plugin enable each vendor to add his own shipping flat rate and shipping classes.
- Separation of shipping per vendor is what we call multi-vendor plugins capabilities. (not a new feature, it is core of Dokan)
- Shipping classes is a core woocommerce shipping way, working with flat rate, but categorize the items based on predefined classes. (not a new feature, it is core woocommerce function).
- variable product can not be order more than the actual stock on hand, while you did not add this into consideration, while you did in Sample product ? ( not a feature, it is core woocommerce function)

so i can you please have another look over my request ?

Regards,
ody

**Comment by minhcasi** [comment]
@ody911 - there is the option EnableOnePageCheckout: true from the `common/config/payment.dart` that could help to resolve the shipping issue, it will enable the Webview solution at the first step. 

Regarding to the 'creating variant product,' it is not supported by the current release due to the complexity of this feature.

**Comment by ody911** [comment]
@minhcasi ,

hi,
I would like to thank you about your fast response, i will check and feedback,
hope you can help me to work without enabling the webview in your next release.

Regards,
ody

**Comment by minhcasi** [comment]
@ody911 - pls try your best to integrate with the extra shipping plugin if you using `NativeOnePageCheckout` - we could not support and make sure it works with all the plugins, that why we suggest using `EnableOnePageCheckout`, we believe it is not impacted too much to the UX - thank you!

**Comment by ody911** [comment]
Hi Minh,

I am not sure if I got you, do you need me to use a plugin called "extra
shipping " ?

And if I used it you will be able to show correct shipping cost?

Basically I am using woocommerce default flat rate with shipping classes to
manage different weighted product , which also supported by Dokan, and I
have checked yesterday release and it capture the shipping now but still
missing the shipping classes,  I really hope you can handle this as I
should be releasing my app for public by 15th of may .

Also I have seen that user still able to order quality more than the
available quantity for variable product,  I hope you can stop this as well.

Thank you for your understanding,  and keep your customers satisfied,
specially when they ask for something you said you are fully compatible
with.

Regards
Ody

**Comment by minhcasi** [comment]
@ody911 - we will investigate more and let you know 

@minhtruong315 - pls help to check the shipping class and mstore-api issue

**Comment by ody911** [comment]
@minhcasi ,

thank you.

**Comment by minhtruong315** [comment]
@ody911 if you're using customize plugin for shipping methods, You need to use EnableOnePageCheckout. if you're default shipping methods, you can use NativeOnePageCheckout

**Comment by ody911** [comment]
@minhcasi 
@minhtruong315 

i am not using customize plugin for shipping however, when i am using the check out way you implemented in the app the shipping classes are not calculated! and the shipping are showing all available shipping while i have chosen a specific state ?, also it is not shown shipping per vendor as doakn/woocommerce does ?, also there is something called vendor shipping in the dokan plugin where vendor can define his own shipping costs per shipping location and shipping classes, those are not available as well, 
before i purchase this app i was told that these are available options on the app not in the onepagecheckout as it is referring back to web-view which is not acceptable, as i have purchase this app due to not enabling web-view at any stage on the app.
hope you understand me and solve the current shipping class issue and vendor shipping issue, along with variable issue with enable user to chose quantity more that the available to purchase quantity.
i do have a very bad experience with you guys, and each time one of you reply my i have to mention all the issues again for beginning, this is not the way i was expecting!
case age is 26 days!
![image](https://user-images.githubusercontent.com/36228917/81733898-fe408a00-9492-11ea-9f03-876abc72db77.png)

![image](https://user-images.githubusercontent.com/36228917/81733944-0ef10000-9493-11ea-8734-d44a24b5503e.png)

thank you for your understanding and support!

**Comment by minhcasi** [comment]
@ody911 - sorry to hear that, the "vendor shipping" is the new features that we have not integrated with the Dokan on the current release, we have added this feature to our backlog for investigating.

We're trying our best with the support, but due to the limited features from the multi-vendor app, we are understand that it may not fit all requirement, If you are not satisfied with the product so far, we could also process refund to save your cost, thank you for your time.

**Comment by ody911** [comment]
@minhcasi 
really it is not about refund, i am really expecting match more from pig company like yours, 
i can see that you are working too hard to fulfill your customer and i see that you are working on the shipping classes ( it is already on the code) but not finished yet, and limit the shipping based on zip code as well but not state yet, i have no issue to wait until it finished, but i need to know when i expect it to be released.
also regarding limitation of variable products availability i can see you are working on it as well,
it is all about urgent matters to startup without match issues.
my urgent matters are :
- Limit the variable product quantity to the actual available quantity.
- shipping classes to calculate the different shipping classes.
- shipping for each vendor (shipping cost per vendor in the ordering), if there is two vendors in the order shipping should calculate each vendor shipping cost per products and shipping classes.

what is important but not urgent:
- vendor shipping facility which enable vendor to set there own shipping cost.
- create simple and variable product using shipping class and variable data

hope you can give me feedback over these. and lets move forward.

**Comment by minhcasi** [comment]
Thank you for your valuable feedback, let me discuss the team to investigate the most important issues first 👍

Btw, what do you mean "pig company" 🐷?

**Comment by ody911** [comment]
@minhcasi sorry i mean big  huge / respectable company💯 
and thank you for your always support :)
Regards,
ody

**Comment by abedfatafta** [comment]
Dear minhcasi , 
i am the same issue , 

1- native woocommerce shipping class not calculated , thats main woocommerce feature not add on , 
2- store shipping , wcfm and dokkan give each merchant store shipping different , your app read it as shipping method while its directive to tell you there is store shipping , 


the first one very important because its native woo-commerce feature , and again its not about refund we are at end of project customization  , and time is running
thanks

**Comment by ody911** [comment]
hi @minhcasi ,

any luck?
Regards,
Regards,
ody

**Comment by minhcasi** [comment]
@ody911 - our team is working on these upgrades for next coming release 👍  - thank you!

**Comment by ody911** [comment]
Thank you so much , really appreciated.

Regards
Ody

**Comment by stickypages** [comment]
When do you think 1.7.5 will be released?

**Comment by ody911** [comment]
@minhcasi 
When do you think 1.7.5 will be released?

**Comment by stickypages** [comment]
@ody911 would love to discuss with you more about the store stuff, if you find things out. Would you be open to help developing / solving these issues? Email or hangouts justin@stickypages.ca

**Comment by abedfatafta** [comment]
@ody911 @stickypages   @minhcasi @minhtruong315 

what do u think guys ? actually i am waiting the release , 

 @minhcasi @minhtruong315 
another thing is there is away to upgrade without losing customization ?

**Comment by stickypages** [comment]
Yeah I need these features asap. Trying to launch this week. And I need these basic things. Do I do it on my own or hire, just need some more communication.

**Comment by minhtruong315** [comment]
Hi @ody911 We just released version 1.7.4. You can try your issues on that version. Remember to update MStore Api plugin as well.
We're working on shipping for multi vendor. I hope it can be released on the next version.
Thanks

**Comment by ody911** [comment]
@minhtruong315 

thanks i will check and update you

Regards,

**Comment by minhtruong315** [comment]
Hi @ody911 I updated shipping method by vendor. it'll be available on next release.
https://github.com/inspireui/support/issues/3354#issuecomment-638904167

**Comment by ody911** [comment]
@minhtruong315 ,

thank you for update, can you please update me if the shipping class are calculated in version 1.7.4 or 1.7.5 ?, also i found that 1.7.5 is available on download page but when trying to download we got 1.7.4 ?

thanks on advance.

**Comment by minhtruong315** [comment]
Hi @ody911 We're researching to apply shipping classes to calculate.
I hope it'll be done and release on next version.
Thanks

**Comment by ody911** [comment]
@minhtruong315 , thank you for your kind feedback.

i am experiences something strange on version 1.7.5 and 1.7.4, the home screen (shop screen) i have added multiple sections to show specific category items, each time i scroll down or up the previous sections are reloaded again. ? 

here a screen record to check it.
[screen shot](https://we.tl/t-vhOparG4xr) 
with regards,
ody

**Comment by minhtruong315** [comment]
<img width="1109" alt="Screen Shot 2020-06-10 at 11 35 27 AM" src="https://user-images.githubusercontent.com/10402500/84227643-257c8c80-ab0f-11ea-813c-682a7d76f74d.png">
Hi @ody911 change cacheExtent to 10000 and try again

**Comment by ody911** [comment]
Hi @minhtruong315 ,

thank you, it works, one more thing if you can help, can i fix the height of each product on home screen, as some product images are big and others are normal, can i fix it to specific height ?

Regards,
ody

**Comment by minhtruong315** [comment]
Hi @ody911 try to change here
<img width="1172" alt="Screen Shot 2020-06-12 at 5 59 01 AM" src="https://user-images.githubusercontent.com/10402500/84447347-efa3e900-ac71-11ea-80e1-5cc965ea8f21.png">

**Comment by ody911** [comment]
> Hi @ody911 We're researching to apply shipping classes to calculate.
> I hope it'll be done and release on next version.
> Thanks

hi @minhtruong315 ,

i believe case not closed yet, also some features you have implemented in one page with bugs, live limit variable item to the current stock, it is not controlled on the cart page, and also user can choose item qty (as much as he can) without selecting variable  and place the order ?

Regards,
ody

**Comment by minhtruong315** [comment]
Hi @ody911 Can u list me your issues and explain clearly?
Can you fork from our git repo then invite me: minhtruong315@gmail.com? https://medium.com/@inspireui/how-to-upgrade-fluxstore-projects-by-using-git-cebde7489ea6 
I will help you check your issues 
Thanks

**Comment by ody911** [comment]
@minhtruong315 

i am not able to fork your git repo, can you please enable this to my email, "ody911@gmail.com",

regarding to explanation of the issues,
- if you have opened any variable product page, and tries to press on buy now/add to cart, it declare that item still loading, which is great, but if user go to quantity picker he still able to add whatever quantity ( can you disable this action until the product is fully loaded) as after loading, you by default chose one of the variables however this variable quantity might be lower that what user chose while variables being loaded. and the quantity is not updated in the quantity picker until the user chose another variable or confirm by clicking on the selected variable, however it is not reflected on the quantity user have chosen before., and user can process his quantity without any farther check.

- by going to my cart after choose wrong quantity, user still able process same wrong quantity to next level, then choose the shipping .
- in review page if user need to delete one or more items from the cart it is available however, it is not reflected on the shipping cost or vendors. ( and it show vendor shipping even user removed all items from this vendor) and not updating even the total of the order in review page or payment page.

- by processing the order to payment and done payment, the shipping is not in the placed order ?, either on the website or in the app. it is shown as zero.

- in the home page i have listed some categories items, the image height of the items are not equals, in website we have tool to crop images to be shown in the home page equally, you have done it on the item listing pages (products page), however in the products page the item missing name price  details as the section is holding item image only as it is a big image., i believe you need to fix item image location width and height and same for name and details.

- in the home page i have added lot of categories which take time to be loaded, if there any way we can add a loading indicator like the shipping loading indicator to tell the user that app still loading ? and to start loading the content of the home page during the splash screen time, as splash screen can be defined to stay on the screen for 3 sec, those can be used to minimize the loading of the home page.

- Using swap to refresh should refresh the page, and add or remove items as per the website , this is not happening you need to close the app and reopen it again!

- you still able to add to cart from my wish-list without chose the variable and you can chose any quantity.


- shipping classes, i believe you still working on it.
- variable product to be added by vendor with proper variation and shipping classes.
- simple product to be added by vendor with proper shipping classes.


regards,
Ody

**Comment by minhtruong315** [comment]
@ody911 I added you. please fork our git repo.
Thanks

**Comment by ody911** [comment]
@minhtruong315 ,

done and i have added you., i have change config.dart to march my site credential as well.

what is the next step?
regards,
ody

**Comment by minhtruong315** [comment]
You posted more issues. I need more time to check and update it. please wait

**Comment by ody911** [comment]
Thanks @minhtruong315  to update when you have finished any of listed issues accordingly

**Comment by ody911** [comment]
@minhtruong315 

any luck ?

Regards,
ody

**Comment by minhtruong315** [comment]
@ody911 I'm working hard to release the new version Fluxstore MV. Then you can check your issues on next release.

**Comment by minhtruong315** [comment]
@ody911 We released Fluxstore 1.7.7. it fixed some issues. please check your app in that version. remember to update MStore Api plugin as well

**Comment by ody911** [comment]
Thank you,  i will check it out
Regards
Ody

**Comment by minhcasi** [comment]
Let us know if you have any question - thank you!
