### ISSUE TITLE
Flux Store - Magento - mstore/appleLogin - route doesn't exists

### ISSUE THREAD

**Issue by sodhanii** [inspireui/support#2749]
Step 1 (require): detail issues and screenshots

Hi,

I checked your plugin for magento properly, and it doesn't have any implementation for the route mstore/appleLogin which is called from loginApple method in magento.dart. 

Please help fix this at the earliest. Apple wouldn't approve app without Sign in with Apple feature.

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

Done

*Note: please submit ticket support by following above 2 require steps, we may close the ticket without providing full information.*

**Comment by minhcasi** [comment]
@sodhanii - thank you for reporting - we will investigate and keep an update

**Comment by sodhanii** [comment]
Please do at the earliest.

I’ve also reported tax and coupon issues three days ago. No update on that
as well.

**Comment by minhtruong315** [comment]
@sodhanii give me your email, I will send u MStore extension

**Comment by sodhanii** [comment]
aditya.sodhani@sodhanii.com

**Comment by minhtruong315** [comment]
sent

**Comment by sodhanii** [comment]
Awesome! Got it.

Thank you so much!

Best regards,
Aditya
