### ISSUE TITLE
[MSTORE-MV] Undefined is not an Object (Vendor.Banner)

### ISSUE THREAD

**Issue by nghonyuen** [inspireui/support#275]
**Required Info (please complete the following information):**
* Product: MStore MV
* Your Purchased Code: 34a1d23d-c198-4cd8-beec-b4d0881c6437
  (we may not reply if you are not our customer)

**Describe the bug**
Our backend is WooCommerce & WooCommerce Marketplace (WCMP). When trying to connect to it, the product & categories listing is perfect. However, if I navigate to the Vendor Tab (under categories or under the individual products), it throws the below error. Please help

**Screenshots**
![img_1801](https://user-images.githubusercontent.com/47480781/52523388-c8c75280-2ccb-11e9-9546-56474efb4972.jpg)

**Additional context**
Add any other detail logs about the problem here.
If possible please share your config.js that use for the app setting

**Comment by nghonyuen** [comment]
Hi 

May I know if there's any update on this? 
Cheers. :)

**Comment by thangvo9x** [comment]
Hi. Try by update the info of vendor. If it is not working. please check your api. 
https://inspireui.github.io/mstore-mv/
Thanks

**Comment by nghonyuen** [comment]
Hi 

Are you referring to the below? I have ensure almost everything is filled up but error still happens. 

<img width="1440" alt="screenshot 2019-02-11 at 1 51 02 pm" src="https://user-images.githubusercontent.com/47480781/52547661-28287e00-2e04-11e9-8c76-ee004954c7b1.png">
<img width="1440" alt="screenshot 2019-02-11 at 1 50 59 pm" src="https://user-images.githubusercontent.com/47480781/52547662-28287e00-2e04-11e9-8fa0-567a60624c13.png">
<img width="1440" alt="screenshot 2019-02-11 at 1 50 56 pm" src="https://user-images.githubusercontent.com/47480781/52547664-28c11480-2e04-11e9-9d5f-6bd7385a854f.png">

**Comment by thangvo9x** [comment]
Hi. the follow above image. We can't support with the plugin WCMp. please check again here 
https://codecanyon.net/item/mstore-multi-vendor-complete-react-native-template-for-ecommerce/22278924
Support Dokan & https://wordpress.org/plugins/wc-vendors/
Thanks

**Comment by nghonyuen** [comment]
Tried using Dokan. Working fine. Except when goes to Category, Vendor, clicking on the individual vendors will throw below error
![img_1933](https://user-images.githubusercontent.com/47480781/52618194-1533ad80-2ed9-11e9-92d2-c573d99215bc.jpg)

**Comment by thangvo9x** [comment]
Hi. you can replace this file in src/Components/VendorInfo/index.js
Replace with this file.
p/s: rename .txt -> .js 
[index.txt](https://github.com/inspireui/support/files/2854590/index.txt)

**Comment by nghonyuen** [comment]
Perfect! Working fine.
