### ISSUE TITLE
Fluxstore Woocommerce [Payment Page]

### ISSUE THREAD

**Issue by amolsaini** [inspireui/support#2750]
Step 1 (require): detail issues and screenshots

When we go on payment page its showing website links in footer.

![picturemessage_xtv40thp 522](https://user-images.githubusercontent.com/61465898/79508047-706dac80-8056-11ea-8697-71b5a6bb791c.png)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

![Untitled](https://user-images.githubusercontent.com/61465898/79508142-93985c00-8056-11ea-8577-54fe948bf98e.jpg)

*Note: please submit ticket support by following above 2 require steps, we may close the ticket without providing full information.*

**Comment by minhcasi** [comment]
@amolsaini - please help to share the common / config file to http://private.inspireui.com or sharing public here so that we could suggest a solution on how to customize on that payment UI - thank you!

**Comment by minhcasi** [comment]
please help us to move all conversation to same ticket support #2751
