### ISSUE TITLE
Fluxstore Woocommerce Variations

### ISSUE THREAD

**Issue by amolsaini** [inspireui/support#2751]
Step 1 (require): detail issues and screenshots
 Buy now option in variation product is active without selection of variation. 

![new release](https://user-images.githubusercontent.com/61465898/79509169-9ac06980-8058-11ea-85af-f00dffd6e53f.jpg)

It was Perfect In earlier app release. 
![earlier](https://user-images.githubusercontent.com/61465898/79509017-5503a100-8058-11ea-9cf6-ab2689cea72d.jpg)
  

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

*Note: please submit ticket support by following above 2 require steps, we may close the ticket without providing full information.*

**Comment by amolsaini** [comment]
Hi I have already shared

**Comment by amolsaini** [comment]
![picturemessage_xtv40thp 522](https://user-images.githubusercontent.com/61465898/79568581-ba48a800-80d3-11ea-8145-252bd87de23a.png)

The payment page issue. Shows website links in footer

**Comment by amolsaini** [comment]
Hello any update on this ?

**Comment by amolsaini** [comment]
any update about the issue ??

**Comment by philipvu30** [comment]
Hi,

1. Fixed.
2. It is not possible to hide the website footer. Because the payment is the Webview that show the payment page on your site.

**Comment by amolsaini** [comment]
Hi i was able to fix the issue of payment but after payment success it redirect back to website home page..  
![Untitled](https://user-images.githubusercontent.com/61465898/80062199-cc519d00-8550-11ea-83fc-1da65ff01532.jpg)

**Comment by amolsaini** [comment]
is there is no fix for this also

**Comment by amolsaini** [comment]
Please let me know the fix of 1st problem also

**Comment by amolsaini** [comment]
![payment11](https://user-images.githubusercontent.com/61465898/80062803-33bc1c80-8552-11ea-91fe-fddd2a9d43c3.jpg)

well i fix the second problem on my own but after payment success i go back to website home page 
![Untitled](https://user-images.githubusercontent.com/61465898/80062894-5a7a5300-8552-11ea-808b-694ba4e2afc1.jpg)

Please don't tell me that there is no solution for that also
