### ISSUE TITLE
Cart error

### ISSUE THREAD

**Issue by Fovorno** [inspireui/support#2752]
Step 1 (require): detail issues and screenshots
Throws error in the cart. It reappears when I close the app with products in the cart. When start the app again and navigate to the cart, it throws the error on the screenshot.

![Capture](https://user-images.githubusercontent.com/27883324/79523993-6a170a80-802d-11ea-9ec5-8c67500276ae.JPG)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

*Note: please help to fill the required information from the above 2 steps, we may close the ticket which is not included the proof of purchase.*

**Comment by minhcasi** [comment]
@Fovorno - please help to check solution on this ticket https://github.com/inspireui/support/issues/2615 - we will update new version to fix this issue on 

Also - please move the conversation to the same ticket #2753
