### ISSUE TITLE
[FluxNews] How to increase font size of the post page 

### ISSUE THREAD

**Issue by bidfor** [inspireui/support#2754]
Step 1 (require): detail issues and screenshots
Font size too small for the post. How to Increase font size ?
![image](https://user-images.githubusercontent.com/2523772/79534807-2d3f2800-80ae-11ea-94bb-8ca027b81188.png)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

*Note: please help to fill the required information from the above 2 steps, we may close the ticket which is not included the proof of purchase.*

**Comment by minhcasi** [comment]
@bidfor - it's located on this file https://tppr.me/FYt1p 

we suggest to use Inspector to customize the UI from the app, please check similar guide https://docs.inspireui.com/fluxstore/customization/#1-how-to-customize-any-ui-from-app
