### ISSUE TITLE
Problema para pagamento e bug no sistema 

### ISSUE THREAD

**Issue by Roupasafricanas** [inspireui/support#2756]
Boa noite. Aparece uma mensagem de erro na hora de adicionar o carrinho e quando aperto para finalizar a compra, depois de uma longa demora me manda para uma página inválida 

https://vimeo.com/408758228

**Comment by minhcasi** [comment]
@Roupasafricanas - pls help to provide detailed info from http://private.inspireui.com  then reopen this ticket - thank you!
