### ISSUE TITLE
Mac os App

### ISSUE THREAD

**Issue by glpennino** [inspireui/support#2757]
good morning,
I can't log in.
I installed the latest version of the app from the App Store.

Thank you
<img width="1196" alt="Schermata 2020-04-17 alle 09 36 50" src="https://user-images.githubusercontent.com/44557088/79544235-fefe2000-808e-11ea-9407-e5c08eee01c8.png">

**Comment by minhcasi** [comment]
@glpennino - please try it again, we have just updated new migration server - thank you!

**Comment by glpennino** [comment]
Hello,
i tried again but can't login. I also restarted the mac but it doesn't work. I tried to install also on a windows pc and it gives me the same problem.
![Schermata 2020-04-17 alle 15 49 11](https://user-images.githubusercontent.com/44557088/79576071-017a6d00-80c3-11ea-9884-675204c9bb68.png)
