### ISSUE TITLE
Beonews pro  home screen not showing

### ISSUE THREAD

**Issue by HoWonJang** [inspireui/support#2758]
[Desktop.zip](https://github.com/inspireui/support/files/4491058/Desktop.zip)
1. I have a question again because the answer is too late.
I modified the appconfig.json file correctly, but I can't see the horizental
 home screen. Also, the sticky banner is not shown. I am attaching my code file and website admin ID and password to the attached file. Please check and let me know what the problem is. Please give me a quick answer. Thank you.

2.![height](https://user-images.githubusercontent.com/49952957/79561337-2af7c080-80e4-11ea-9bc2-82f2cfec742f.PNG)
![height2](https://user-images.githubusercontent.com/49952957/79561338-2c28ed80-80e4-11ea-9b19-1b69c0f2a8ea.PNG)

What code should be modified to modify the length of the height, height2?

3.
![column change](https://user-images.githubusercontent.com/49952957/79561436-52e72400-80e4-11ea-8ff4-8bc033a8efeb.PNG)

I would like to change the column of related post to 2 columns, which part of the code should I change?

4.
![title logo](https://user-images.githubusercontent.com/49952957/79561528-714d1f80-80e4-11ea-8e86-4425a47286df.PNG)

The title logo is cut out as you can see in the image The size of the logo is exactly the same as the size of the default logo. It's the same with physical devices. What's the problem?

Please give me a quick answer. Thank you.

**Comment by luyx2412** [comment]
Hi @HoWonJang 
1. In `App/Common/Constants.js` you can based on the layout type to show your items
![image](https://user-images.githubusercontent.com/8909619/79639529-9ca03f00-81b6-11ea-8e2e-723838249e84.png)

2. in `App/Components/PostLayout/index.js` Based on your layout type you can edit height. Currently i saw your config and you used `twoColumn`, please go to the `App/Components/PostLayout/Column/styles.js` line 14 this is a screenshot
![image](https://user-images.githubusercontent.com/8909619/79639882-90b57c80-81b8-11ea-8bfc-0ed408d45db3.png)
![image](https://user-images.githubusercontent.com/8909619/79639883-914e1300-81b8-11ea-9e14-f63158a9c8cf.png)

3. Please use layout type in Constants.js file to show two column. And the two column is `5`
![image](https://user-images.githubusercontent.com/8909619/79639899-ac208780-81b8-11ea-9f5a-9b83da8b2702.png)

4. In `App/Components/AnimatedHeader/styles.js` line 30. You can edit the style to suitable your app logo.
![image](https://user-images.githubusercontent.com/8909619/79639948-0a4d6a80-81b9-11ea-851b-c1f410a3a5a3.png)

Thanks
