### ISSUE TITLE
Listeo Integration - Search shops by Regions and filter by Categories

### ISSUE THREAD

**Issue by khaoss85** [inspireui/support#2759]
Hello,

I have bought Fluxstore listing yesterday and today I've completed to setup everything.
My website is running on Wordpress with Listeo theme at the following url: QuartiereMio.com
I'm not using wcommerce feature (but it's active), actually I'm using the only listing (listeo_core) plugin.

What I would like to create is a very simple app that let the user search shops by regions and filter by categories (I don't have events and rental features on).

Can you help me to add on the home:
- add the region listing in the home (instead of coming event for example)
- have cities instead of categories in the search section 
- search for product is ok, but should be nice a search by cities and categories 
- in the main nav change BY CATEGORY for BY CITIES

Thanks very much for support

**Comment by minhcasi** [comment]
@khaoss85 - thank you so much for your feedback, there are some new features we need to discuss with the team and keep upgrade - we will confirm when some new version is ready

**Comment by khaoss85** [comment]
Ok, thanks. 
In the meantime, can you tell me a trick to show region instead of categories? 
And Categories instead of Event?

**Comment by khaoss85** [comment]
Quick update.
I've changed in my wordpress site (REST API Controller Pugin) under the taxonomy tab,  "listing_category" in region and it's work now. 

Question: I don't use categories per post, so I can use categoriest tag for listing_categories. 
Does it make sense? Which module I can use too?

**Comment by khaoss85** [comment]
one more question, I have the following error when I open a detail item:

The relevant error-causing widget was:
  ProductMenu
file:///Users/danielepelleri/Sviluppo/quartieremio/lib/screens/detail/listing/themes/simpleType.dart:129:9
When the exception was thrown, this was the stack:
#2      new Text (package:flutter/src/widgets/text.dart:285:10)
#3      ProductMenu.build.<anonymous closure>.<anonymous closure>
(package:fstore/screens/detail/listing/product_menu.dart:54:44)
#4      new List.generate (dart:core/list.dart:165:28)
#5      ProductMenu.build.<anonymous closure>
(package:fstore/screens/detail/listing/product_menu.dart:42:36)
#6      new List.generate (dart:core/list.dart:165:28)
...

do you have any idea on how can I fix it?

Il giorno dom 19 apr 2020 alle ore 11:32 Minh Pham <notifications@github.com>
ha scritto:
