### ISSUE TITLE
[MSTORE-MV] Product Variations & Grouped Product not working

### ISSUE THREAD

**Issue by nghonyuen** [inspireui/support#276]
**Required Info (please complete the following information):**
 - Product: MSTORE-MV
 - Your Purchased Code: 34a1d23d-c198-4cd8-beec-b4d0881c6437
(we may not reply if you are not our customer)

**Describe the bug**
When vendor selling grouped product or product with variation, the additional options are not shown in the mobile page

**Screenshots**
Let me know what screenshots required. Thanks

**Additional context**
Add any other detail logs about the problem here.
If possible please share your config.js that use for the app setting

**Comment by thangvo9x** [comment]
Hi. Thanks for your purchase. Can you provide a screenshot, AppConfig.json file, plz?

**Comment by nghonyuen** [comment]
Please find the below
<img width="532" alt="screenshot 2019-02-10 at 6 35 00 pm" src="https://user-images.githubusercontent.com/47480781/52532604-f3b0b580-2d62-11e9-9de3-ab230710f559.png">

**Comment by thangvo9x** [comment]
hi, you can refer here https://github.com/inspireui/support/issues/1#issuecomment-462592262

**Comment by nghonyuen** [comment]
Thanks Product Variation works. But how about Grouped Product? Thanks

**Comment by thangvo9x** [comment]
Can u share screenshots, plz ?

**Comment by nghonyuen** [comment]
Please find below
[Web View] Can select individual quantity per product. Also variation
<img width="1119" alt="screenshot 2019-02-12 at 3 13 58 pm" src="https://user-images.githubusercontent.com/47480781/52618254-46ac7900-2ed9-11e9-8156-0dd527e90305.png">

[Mobile View] Nothing. In addition, the total amount is wrongly set.
![img_1934](https://user-images.githubusercontent.com/47480781/52618316-75c2ea80-2ed9-11e9-9902-68ca97fddad4.jpg)

**Comment by thangvo9x** [comment]
Hi. Please share your AppConfig.json to my email to checking. Thanks.

**Comment by thangvo9x** [comment]
Oh. We've checked with your Config. We've recorded and integrated with type is grouped product in the next version. First, you can use attributes instead of. Thanks

**Comment by nghonyuen** [comment]
Thanks, may I know the estimated release date? ThanksOn 12 Feb 2019 5:41 p.m., thangvo9x <notifications@github.com> wrote:Oh. We've checked with your Config. We've recorded and integrated with type is grouped product in the next version. First, you can use attributes instead of. Thanks

**Comment by thangvo9x** [comment]
We've planning && note it. We'll have a notice to everyone, ASAP @@ 
Thanks for your choice of our product.
