### ISSUE TITLE
[fluxstore pro] - Config_en is not updating homepage when uploaded on Mstore plugin

### ISSUE THREAD

**Issue by tjain90** [inspireui/support#2760]
Step 1 (require): detail issues and screenshots - my app is already published on app store and play store now i want to upload my app home page without uploading new version. So I have updated config_en file and uploaded over woocommerce mstore plugin. But unfortunately no update happens. is there any cache issue? or do i need to make some changes in code so that it will always pick confirm from mstore.?

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

*Note: please help to fill the required information from the above 2 steps, we may close the ticket which is not included the proof of purchase.*

**Comment by tjain90** [comment]
@minhcasi this issue is not at all related to apple sign in. This is for config file and I beleive plugin on woocomerce due to which unar to update home page after app publish. How can I update my homescreen without realeasing new version. I am using woocomerce.

**Comment by minhtruong315** [comment]
@tjain90 you can rename config_en.json to config.json then upload to mstore api plugin.
and you must to enable isCaching: true as well
<img width="1472" alt="Screen Shot 2020-04-19 at 8 36 07 AM" src="https://user-images.githubusercontent.com/10402500/79677212-f0437480-8218-11ea-8ee3-37a7f6b4e3a1.png">

**Comment by tjain90** [comment]
I have uploaded config.jason and checked at backend. Updated file is available. Also checked iscaching..it is also set to true. Unfortunately it is not showing updated home page on live apps.

**Comment by tjain90** [comment]
Hi Any Update on this.I need to launch few product and my app as wider level ?

**Comment by tjain90** [comment]
Hi team.You can close this Ticket. Some plugin was not working correctly on my website which was creating this issue. Deactivating mstore and activating again sorted out my issue.
