### ISSUE TITLE
Help Regarding adding Image banner To front Page

### ISSUE THREAD

**Issue by Varun24041993** [inspireui/support#2761]
Step 1 (require): detail issues and screenshots
Hi, I have added many banner to front page through Appconfig.json file.
At the last I have added a thank-you banner and I have not added any category id to it but still it always redirect me to some category of its own.

What I want is the if you click on the banner then nothing happens. It seems like straight forward but I am not able to do so. I am sending you a. screenshot below of how I have linked my thank-you image and have added no category id to it but still it will redirect me to some category.
  
![thank-you error](https://user-images.githubusercontent.com/56767455/79571530-f5010f00-80d8-11ea-9fd1-3c783367a360.png)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

*Note: please help to fill the required information from the above 2 steps, we may close the ticket which is not included the proof of purchase.*

**Comment by luyx2412** [comment]
Hi @Varun24041993 Please add layout type in this object to show your banner.

![image](https://user-images.githubusercontent.com/8909619/79639432-03712880-81b6-11ea-8fb4-64e2df1d4331.png)

Thanks

**Comment by Varun24041993** [comment]
hi @luyx2412 I have tried this but the image is still clickable and navigates to another page. I want this image to be a non-clickable image.

**Comment by Varun24041993** [comment]
Hi @luyx2412 I have changed the code in HorizontalLayout and changed the code to remove onPress in touchable opacity so its over but I haven't figured out how to hide the country list on payment page even when I changed hideCountryList: true in Config.js still on payment page I have to choose the country list, Please let me know how I can hide the list Because I just want the country to be default US and person don't have to choose it from a dropdown list.

**Comment by anandkausha** [comment]
I would like to know how to add this banner Images from website / admin side ?

**Comment by luyx2412** [comment]
Hi @Varun24041993 you can remove manual from `src/containers/Cart/Delivery/index.js`, find `hideCountryList ` and remove it. For exmaple: line `159`, i removed it. Please see the screenshot.
`...(Config.DefaultCountry.hideCountryList
        ? {}
        : { country: Tcomb.String })`

![image](https://user-images.githubusercontent.com/8909619/79863864-acac5e80-8402-11ea-810a-16cf085301c6.png)

Thanks
