### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by glpennino** [inspireui/support#2762]
Step 1 (require): detail issues and screenshots

Hello,
i tried again but can't login. I also restarted the mac but it doesn't work. I tried to install also on a windows pc and it gives me the same problem.
I also uninstalled the app, cleared the cache and reinstalled. Nothing, the login remains hanging.

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

*Note: please help to fill the required information from the above 2 steps, we may close the ticket which is not included the proof of purchase.*

**Comment by minhcasi** [comment]
@glpennino - pls help to move conversation to the same ticket on fluxbuilder https://github.com/inspireui/fluxbuilder/issues/29
