### ISSUE TITLE
Fluxbuilder - unable to put credentials of website

### ISSUE THREAD

**Issue by tjain90** [inspireui/support#2763]
Step 1 (require): detail issues and screenshots
I am unable to sign in in fluxbuilder ... It just get show processing and no signup and sign in done. Due to this I am unable to my woocomerce website link and tokens. What is the alternative of entering these details in fluxbuilder .

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

*Note: please help to fill the required information from the above 2 steps, we may close the ticket which is not included the proof of purchase.*

**Comment by minhcasi** [comment]
@tjain90 - pls help to move to https://github.com/inspireui/fluxbuilder/issues
