### ISSUE TITLE
Wrong number of units in the cart

### ISSUE THREAD

**Issue by Fovorno** [inspireui/support#2765]
Step 1 (require): detail issues and screenshots
After reloading app this products get multiplied by 2. For example it was one product after it becomes 2 products in the cart and keeps growing.
![Capture](https://user-images.githubusercontent.com/27883324/79619049-bf105a80-80d9-11ea-9dea-1319023ee30b.JPG)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

*Note: please help to fill the required information from the above 2 steps, we may close the ticket which is not included the proof of purchase.*

**Comment by minhtruong315** [comment]
@Fovorno can u help me record screen?

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
