### ISSUE TITLE
Changes on screen

### ISSUE THREAD

**Issue by Fovorno** [inspireui/support#2767]
Step 1 (require): detail issues and screenshots
1. How to change this wordpress icon besides the Blog link?
2. How to change the blue image on the login page?
![Capture](https://user-images.githubusercontent.com/27883324/79619643-82456300-80db-11ea-88bc-c3c44ae83b49.JPG)

![Capture](https://user-images.githubusercontent.com/27883324/79619684-9f7a3180-80db-11ea-8232-99fe45c82ab4.JPG)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

*Note: please help to fill the required information from the above 2 steps, we may close the ticket which is not included the proof of purchase.*

**Comment by minhcasi** [comment]
move to #2765

@Fovorno - kindly help us to create only 1 Ticket support include your all issues, that would help us focus better on the issues 👍
