### ISSUE TITLE
Android App Opens on Emulator But While Building Give an Exception FluxShopify

### ISSUE THREAD

**Issue by bilalmunir1995** [inspireui/support#2768]
Step 1 (require): detail issues and screenshots

Android App Opens on Emulator But While Building Give an Exception FluxShopify

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com
![error](https://user-images.githubusercontent.com/37571277/79622843-69b46780-8132-11ea-8411-97bd8fc93a0c.PNG)
![13](https://user-images.githubusercontent.com/37571277/79622876-9a949c80-8132-11ea-93e6-2d1fb88f1f25.PNG)

*Note: please help to fill the required information from the above 2 steps, we may close the ticket which is not included the proof of purchase.*

**Comment by minhcasi** [comment]
@bilalmunir1995 - this is caused by missing library install on Android 

- pls double check the flutter setting by using this guide https://www.youtube.com/watch?v=ReAUZDIgh2I
- or try to clean cache on android - https://www.youtube.com/watch?v=ReAUZDIgh2I

**Comment by bilalmunir1995** [comment]
Hey tried everything my flutter installation seem to work fine as i tried building the example app and the apk was built in no time also the app is running fine in the emulator this error comes when you try to build an apk file out of it

**Comment by bilalmunir1995** [comment]
I tried setting everything on a new mac and followed the video same issues

**Comment by bilalmunir1995** [comment]
This was fixed by reinstalling flutter and android studio dont know the exact reason but redoing everything fixed it
