### ISSUE TITLE
no products no categories 

### ISSUE THREAD

**Issue by waelkalesh** [inspireui/support#2769]
this URL 
https://khalasli.com/wp-json/wc/v2/flutter/category/cache?categoryIds=&consumer_key=ck_1a834404774ef2f9048f836bd299c6b38663084e&consumer_secret=cs_f7f983661dc423b7855c12af8669e9995ebc1822

and this response 
{"code":"rest_forbidden","message":"Sorry, you are not allowed to do that.","data":{"status":401}}

![Screenshot_1](https://user-images.githubusercontent.com/46270193/79623292-23f0a280-8124-11ea-8b60-9f03cb100043.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/46270193/79623297-281cc000-8124-11ea-9188-e919b00af17b.jpg)

**Comment by minhcasi** [comment]
@waelkalesh - thank you for the feedback, please help us to send the config file and purchase proof via http://private.inspireui.com - we would like to keep this info private and protect your purchase data and website secret. 

Allow us to edit your ticket to hide the website config data - thank you!

**Comment by waelkalesh** [comment]
I sent to you google form hope get response 
thanks

**Comment by waelkalesh** [comment]
https://khalasli.com/wp-json/wc/v2/flutter/category/cache?categoryIds=&consumer_key=ck_1a834404774ef2f9048f836bd299c6b38663084e&consumer_secret=cs_f7f983661dc423b7855c12af8669e9995ebc1822 

i noticed that no Outh generated from the app in console 

here your default URL from console android studio 
http://dokan.mstore.io/wp-json/wc/v2/products/categories?exclude=311&lang=ar&oauth_consumer_key=ck_5fd50d2948229e27b55f8a787b14ee5a4e01be8d&oauth_nonce=mdjuqhnedc&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1587211419&oauth_token=&oauth_version=1.0&page=1&per_page=100&oauth_signature=60YbhIdpCfQyqi5enCl%2BnsbkZ9Q%3D

but in my URL from android studio 

https://khalasli.com/wp-json/wc/v2/products/categories?exclude=311&per_page=100&page=1&lang=ar&consumer_key=ck_e7d3e6775543e2d85899df88d045aa04f1e0a511&consumer_secret=cs_5f3dfb3eff61fca07edee2a712bd75588c352bf3

there is no 
oauth_nonce=mdjuqhnedc&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1587211419&oauth_token=&oauth_version=1.0&page=1&per_page=100&oauth_signature=60YbhIdpCfQyqi5enCl%2BnsbkZ9Q%3D

**Comment by waelkalesh** [comment]
also i have update the config.dart  so where can I send you a new zip file

**Comment by waelkalesh** [comment]
update for this issue 
I reinstalled the wordpress and installed only woocommerce and JWT and create one product and every thing ok 
after i install and activate marketo theme the app no more showing the product and the url from run in android studio : 

https://khalasli.com/wp-json/wc/v2/products/categories?exclude=311&per_page=100&page=1&lang=ar&consumer_key=ck_2dd025a2276ab6ac12c3be0771ebda871344a46c&consumer_secret=cs_70394c4fab44741a2c726e4d3d81afb7aadbae2e

response with code : 401 
{"code":"woocommerce_rest_cannot_view","message":"Sorry, you cannot list resources.","data":{"status":401}}

please test with this consumer_key 
this is the new one 
and i hope to fast response

**Comment by waelkalesh** [comment]
why no answer ?

**Comment by minhcasi** [comment]
@waelkalesh - the Rest API is not worked - https://tppr.me/F61kA - you can use the fluxbuilder to check the connection http://fluxbuilder.com/

Please try this guide as well to set up the WoCommerce API - https://docs.woocommerce.com/document/woocommerce-rest-api/

**Comment by waelkalesh** [comment]
thanks for replay i fixed the problems two days ago 
and i need to know why firebase deploy --only functions 

from my CMD show me this response 
what should i do ?

Error: Missing permissions required for functions deploy. You must have permission iam.serviceAccounts.ActAs on service account fluxstore-inspireui@appspot.gserviceaccount.com.

**Comment by minhcasi** [comment]
Hi, please try to setting the permission  on your google account - https://cloud.google.com/iam/docs/granting-roles-to-service-accounts - the permission could related to this guide as well - It's possible to update your own Rest API but require some programming skill to change the API from the app.

**Comment by waelkalesh** [comment]
thanks i passed the step that up there but i have new  one problem
i activated the sms login and i got everything right 
but when i build apk and then try sms login i got 

this response 
This app is not authorized to use Firebase Authentication.Please verify that the correct package name and SHA-1 are configured in the Firebase Console
what should i do ?
thanks

**Comment by waelkalesh** [comment]
and how to generate sha1 and how to change package name .... in correct way ?

**Comment by waelkalesh** [comment]
![ice_screenshot_20200423-153305](https://user-images.githubusercontent.com/46270193/80099823-c3c08d00-8577-11ea-8dc3-be9687d87239.png)

i try to generate sha1 and i need password where should i get password ?

**Comment by waelkalesh** [comment]
Please can you support me via anydesk or teamviewer there is somethings i need to know.
My email:   nostalgiakalesh@gmail.com

**Comment by minhcasi** [comment]
Hi @waelkalesh you need to create new key.jks with your new password, and make sure to store this key after release to google play store - please help to double-check the guide https://flutter.dev/docs/deployment/android

**Comment by Zeehshan** [comment]
> thanks for replay i fixed the problems two days ago
> and i need to know why firebase deploy --only functions
> 
> from my CMD show me this response
> what should i do ?
> 
> Error: Missing permissions required for functions deploy. You must have permission iam.serviceAccounts.ActAs on service account [fluxstore-inspireui@appspot.gserviceaccount.com](mailto:fluxstore-inspireui@appspot.gserviceaccount.com).

http://portadiroma.ly/wp-json/wc/v2/products/categories?exclude=311&lang=en&oauth_consumer_key=ck_dbfa527419b8eddacf86ba0504558dbcbe7c6918&oauth_nonce=sxkoamzchj&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1589931196&oauth_token=&oauth_version=1.0&page=1&per_page=100&oauth_signature=y1LtasbZhnEf43G3o2V%2FN%2F1C8R0%3D



Hello sir i hope you will fine, i also got same error please let me know how can i solved
