### ISSUE TITLE
[MStore] Register User not working

### ISSUE THREAD

**Issue by milotsheholli** [inspireui/support#277]
**Mandatory Info (please complete the following information):**
 - Product: MStore
 - Your Purchased Code: 55d9da3e-c5ee-495c-a756-9bbe1c8159ca
(we may not reply if you are not our customer)

**Describe the issues**
I have connected my app with website (on website i have installed wordpress site you provided on github so it was already configured how you configured. Everything works good, product api works, and login also, but the only thing that is not working is registring new user, when trying to register user it shows this error included in screenshot. I have tried everything but i cant get it work. When i change from AppConfig and i use mstore consumer key and url, it works, just with my website new registration doesnt work. This are my website info
divaxo.shop
user: root
password: 12345678

Attached are my AppConfig.php and Config.php files

**Screenshots**
<img width="316" alt="screen shot 2019-02-09 at 18 32 47" src="https://user-images.githubusercontent.com/19651310/52524086-59386f80-2c99-11e9-94b2-69ad66849d35.png">

**Additional context**
[Archive.zip](https://github.com/inspireui/support/files/2848071/Archive.zip)

**Comment by luyx2412** [comment]
Hi @milotsheholli 
I tested your AppConfig.json and it worked sign up feature normal. So can you test again your app?

Thanks

**Comment by milotsheholli** [comment]
Hello,
I just tried again and same error i cant get rid of it i tried everything.
Here is video also, showing that login works only register doesnt work, if it works to you with my appconfig can you send me all code please. And with what user you tried to register i see test1@gmail.com on my wordpress is that you.
Here you can download my video (screen record):
https://we.tl/t-1n0a3ppEje

Thanks!

**Comment by milotsheholli** [comment]
Hello, i installed reactotron and from what i see i have an error with api, response status 409 
But when i try to execute the url it shows an array, but with api it returns null 
http://divaxo.shop/api/get_nonce/?controller=mstore_user&method=register
this url.

**Comment by luyx2412** [comment]
Hi @milotsheholli Please uninstall the app on your device or simulator and reinstall again. Because i checked again your config which worked normal.
https://www.screencast.com/t/mGZxuAcUd7sS

Thanks

**Comment by milotsheholli** [comment]
Hello,
Not that one, that api works good for me too, but the other one where it gets nounce, when you try to register it gets first nounce and that api returns status 409. i tried installing fresh new project many times, i did everything, now i formated my laptop also cuz i read somewhere they said maybe 409 error its because of malware but nothing works. 
Again same error, do you mind sending me the all files where you tried my config and worked, cuz maybe its because of my files (i have downloaded from codecanyon but maybe you have different files.
Thanks.

**Comment by milotsheholli** [comment]
Hello, im sorry, it was my hosting problem, my ip address is blacklisted from my host idk why, i tried to contact them. 
I tried to change host and it worked perfectly.
Thank you! you can close the thread

**Comment by minhcasi** [comment]
Thank you for your confirmed, let us know if you have any further issues.

Please help us to give good rating feedback to https://codecanyon.net/downloads if the product is useful for your business - very best!
