### ISSUE TITLE
FluxStore Listing not working CeBuilder

### ISSUE THREAD

**Issue by stad4real** [inspireui/support#2770]
Step 1 (require): detail issues and screenshots
I purchased FluxStore Listing but there is no package.json to load in CeBuilder.

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com
I haven't even gotten to config yet.

*Note: please help to fill the required information from the above 2 steps, we may close the ticket which is not included the proof of purchase.*

**Comment by minhcasi** [comment]
Hi @stad4real - fluxstore is not compatible with CeBuilder but it compatible with FluxBuilder - http://fluxbuilder.com/ - please check it out and let us know if you have any question - thanks

**Comment by stad4real** [comment]
Thank you. What is the difference between List App and FluxStore?
