### ISSUE TITLE
[Fluxstore Pro] Cannot proceed to payment when shipping limited areas

### ISSUE THREAD

**Issue by ridhuandaud** [inspireui/support#2771]
Step 1 (require): detail issues and screenshots

Hi.
We have problem when proceed to payment page if we put limited areas and postcodes in our woo commerce shipping

<img width="1105" alt="Screenshot 2020-04-18 at 08 58 45" src="https://user-images.githubusercontent.com/6647939/79624253-1acafa00-8153-11ea-8130-96b586bb0138.png">

The first shipping zone will be cause problem as screenshot below

<img width="294" alt="Screenshot 2020-04-18 at 08 48 11" src="https://user-images.githubusercontent.com/6647939/79624343-afcdf300-8153-11ea-85fb-fb7e1ee662d8.png">

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com
Done.
<img width="1279" alt="Screenshot 2020-04-18 at 09 05 38" src="https://user-images.githubusercontent.com/6647939/79624362-cecc8500-8153-11ea-909e-f10a6653ec41.png">

*Note: please help to fill the required information from the above 2 steps, we may close the ticket which is not included the proof of purchase.*

**Comment by minhtruong315** [comment]
@ridhuandaud we added NativeOnePageCheckout. it will help you resolve this issue. it'll be available in next release.

**Comment by minhtruong315** [comment]
@ridhuandaud pls update Fluxstore 1.6.7 to use NativeOnePageCheckout
