### ISSUE TITLE
error in cart page [fluxstore 1.6.6b]

### ISSUE THREAD

**Issue by immortal-kid** [inspireui/support#2772]
i add some products in cart, the it will be fine, then i will close the app and open again, i get this error. i never faced such issues in previous versions.

![image](https://user-images.githubusercontent.com/10250665/79630538-c6824300-816f-11ea-8a30-6f56a8733a8f.png)

![image](https://user-images.githubusercontent.com/10250665/79630515-87ec8880-816f-11ea-8cff-a5dc1dbab54f.png)

![image](https://user-images.githubusercontent.com/10250665/79630509-7acf9980-816f-11ea-9147-20575b977abc.png)

**Comment by minhcasi** [comment]
@immortal-kid - please help to check the solution on this ticket - https://github.com/inspireui/support/issues/2615 - we will update new version soon in 1-2 days - thank you!
