### ISSUE TITLE
Bugs, incomplete documentations. [fluxstore]

### ISSUE THREAD

**Issue by immortal-kid** [inspireui/support#2774]
![image](https://user-images.githubusercontent.com/10250665/79633278-1407ab80-8182-11ea-8730-c32b6de82707.png)

1. [bugs] as i said in #2385 ,I gave EnableReview to false, and also disabled review in woocommerce settings, but review is still showing.I removed review option manually in each page.

2.  [bugs] as i said in #2385 5th point, you have added list view in 1.6.6, where should i make changes to make it work? i tred in config json file but did not work.
![image](https://user-images.githubusercontent.com/10250665/79633340-6cd74400-8182-11ea-99f5-6bd47dc48252.png)
i

3. Honestly, i'm very disappointed with the documentation. You guys introduce lot of features in each update, but documentation remains incomplete. There are so many customization options in the code and there are not at all mentioned in documentation. We feel confused on what those option does.

**Comment by immortal-kid** [comment]
2. i made these changes in products.dart and still showing default layout.
![image](https://user-images.githubusercontent.com/10250665/79633913-1586a300-8185-11ea-8032-1c7ee41d588f.png)

**Comment by immortal-kid** [comment]
2. i made these changes in products.dart and still showing default layout.
![image](https://user-images.githubusercontent.com/10250665/79634007-95147200-8185-11ea-989a-8846d45bd66f.png)

**Comment by minhcasi** [comment]
1. You can try to disable the Review feature from the app as there is no option to get review option via Rest API

2. just change 
```
"layout": "listTile"
```
You can follow this blog to clarify the detail per new update - https://medium.com/@inspireui/announcing-fluxstore-1-6-337efff1791f

**Comment by immortal-kid** [comment]
1. yes, i disabled review by setting EnableReview to false, still it was showing. i manually removed in each page

2. i added that line u sent also, still default layout was showing. as u can see in that screenshot, i had commented that line, because it did not worked.

**Comment by trunghieuvn** [comment]
Hi @immortal-kid ,
 As for issue 1, I'm not sure which page you want to hide reviews from?

In this project, there are 2 flags to hide/show reviews and are 2 different types of reviews.

For the `EnableReview` flag in file `lib/common/config/payments.dart`, it is used to hide/show the reviews feature in the payment screen.
As shown below are 2 results of Toggle Review flag

- **EnableReview = false**
![image](https://user-images.githubusercontent.com/19247680/79714015-b7c79780-82f9-11ea-8ad1-3b74b598ec99.png)

- **EnableReview = true**
![image](https://user-images.githubusercontent.com/19247680/79714068-e34a8200-82f9-11ea-8475-b1c1c3f4b6b8.png)


For the `enableProductReview` flag in file `lib/widgets/frameworks/woocommerce.dart` (for Woo and similar with other frameworks), it is used to hide the review feature in details of a product.
As shown below is the result of turning off the review flag

- **enableProductReview = true**
![image](https://user-images.githubusercontent.com/19247680/79714140-1c82f200-82fa-11ea-9150-e9799f2ff456.png)

- **enableProductReview = false**
![disable-review-product](https://user-images.githubusercontent.com/19247680/79713823-27895280-82f9-11ea-89d4-7de0f163b4a2.jpg)

For these 2 flags, I check and they both work fine. Not sure where you want to hide reivew, please try again! Thanks!

**Comment by immortal-kid** [comment]
1. i wanted to hide product review option, that 5 star icons.  Its a grocery store and there are 1000's of products. review is not a good for grocery store. I'm hiding it manually now, in product detail page and product list page.

**Comment by immortal-kid** [comment]
2. Regrding product list view, i changed to listTile, still showing default layout only.

**Comment by trunghieuvn** [comment]
> 1. Regrding product list view, i changed to listTile, still showing default layout only.

This listTile currently only changes the layout of the product list in the home interface. You can add them in the config_en.json file like this

![image](https://user-images.githubusercontent.com/19247680/79719723-5c050a80-8309-11ea-8a20-84d65d9b2fc2.png)

![image](https://user-images.githubusercontent.com/19247680/79719828-9078c680-8309-11ea-98c0-bb9cc348df80.png)

**Comment by trunghieuvn** [comment]
> 1. i wanted to hide product review option, that 5 star icons.  Its a grocery store and there are 1000's of products. review is not a good for grocery store. I'm hiding it manually now, in product detail page and product list page.

I will review and guide the solution for you as soon as possible, please wait for me. 
Thanks

**Comment by trunghieuvn** [comment]
> > 1. i wanted to hide product review option, that 5 star icons.  Its a grocery store and there are 1000's of products. review is not a good for grocery store. I'm hiding it manually now, in product detail page and product list page.
> 
> I will review and guide the solution for you as soon as possible, please wait for me.
> Thanks

@immortal-kid , 
You can handle it this way, hide it if the rating is not there (because the minimum score is 1, so we check null or 0 for the case without a rating)

- In file `lib/common/config/general.dart`, add a new field is `hideEmptyProductListRating`
![image](https://user-images.githubusercontent.com/19247680/79721579-ca979780-830c-11ea-9280-4a94a620f307.png)

- in file : `lib/widgets/product/product_card_view.dart` and find the code with keyword: `SmoothStarRating`
![image](https://user-images.githubusercontent.com/19247680/79721553-bfdd0280-830c-11ea-9b6e-e0c90f270663.png)


```
 if (kAdvanceConfig['hideEmptyProductListRating'] == false || (item.ratingCount != null && item.ratingCount > 0))
 SmoothStarRating(
    allowHalfRating: true,
    starCount: 5,
    rating: item.averageRating ?? 0.0,
    size: starSize,
    color: theme.primaryColor,
    borderColor: theme.primaryColor,
    label: Text(
      item.ratingCount == 0 || item.ratingCount == null
          ? ''
          : '${item.ratingCount}',
      style: TextStyle(
        fontSize: ratingCountFontSize,
      ),
    ),
    spacing: 0.0),
```

If the hideEmptyProductListRating flag is false, the application will still show a review if the product has no reviews (like the old logic is there).
If the hideEmptyProductListRating flag is true, the application will hide that product if it has no reviews. (still showing reviews for rated products)

**Comment by immortal-kid** [comment]
I will do these changes.

When is the next update?

**Comment by immortal-kid** [comment]
2. as i said in #2385 see the screenshot there, product list screen is now in grid, i attached screenshot and asked list view also, but you are talking about front screen. product list screen is different from front screen

**Comment by immortal-kid** [comment]
@minhcasi @trunghieuvn

**Comment by trunghieuvn** [comment]
> 2\. [bugs] as i said in #2385 5th point, you have added list view in 1.6.6, where should i make changes to make it work? i tred in config json file but did not work.
>     ![image](https://user-images.githubusercontent.com/10250665/79633340-6cd74400-8182-11ea-99f5-6bd47dc48252.png)
>     i

**That's not a bug, it's a listTile feature at home. The feature you requested is not available. So when you change the ListTile layout, nothing happens.
As for the feature you suggested (in #2385  5th point) we will investigate this feature and review it to update it later, thank you for the suggestion.**

> 5. (View request) http://prntscr.com/rib5wh This screenshot is from some other app. Usually ecommerce stores doesn't have to be always grid view, you could add a list view like this http://prntscr.com/rib5wh . This is very useful view. (I know if we know flutter we can do it ourselves, but not everyone who bought the script is aware of flutter customization)

**Comment by minhcasi** [comment]
@immortal-kid - pls following out blog http://medium.com/@inspireui and video http://youtube.com/inspireui - we will put more document video guide there - thank you!
