### ISSUE TITLE
Flux News - Some Problem with login.

### ISSUE THREAD

**Issue by zemeister2332** [inspireui/support#2775]
I release my app and get some problem can u help me? I recorded my video. here is link
AND IF ITS POSSIBLE HOW CAN I DISABLE LOGIN FOR SHOW PROFILEM MENU DARK NIGHT MODE AND SMART CHAT MENUS.

https://vimeo.com/408607299

**Comment by dttrung26** [comment]
Hi @zemeister2332 , 
sorry I didn't pay attention to your last question. For customizing your request, please use inspector tool to identify all login elements in /lib/screens/login.dart and modify to meet your need. Thanks.
