### ISSUE TITLE
fluxnews question

### ISSUE THREAD

**Issue by mimasean** [inspireui/support#2776]
Step 1 (require): detail issues and screenshots
 what is the reason the application is creating this amount of pages? https://ctrlv.cz/1zWP  I have another problem: The application (flutter) is not capturing the delivery method. When accessing the website (outside the app) the capture normally occurs. https://ctrlv.cz/p0aM

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

*Note: please help to fill the required information from the above 2 steps, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhcasi** [comment]
@mimasean - the screenshot not working, please attach again. 

Kindly format the ticket on next time :)

<img width="921" alt="Screen Shot 2020-04-19 at 08 10 01" src="https://user-images.githubusercontent.com/1459805/79676912-2c74d600-8215-11ea-90f6-a1cbb827ed39.png">

**Comment by mimasean** [comment]
Problem one( fail in get shipping metod)
https://drive.google.com/open?id=1DmtMSEkdwL3C19uyQ9ASBC27jo9AutZP
Problem two( generate blank pages in checkout)
https://drive.google.com/open?id=1DQBijsoUVyowJJMcaoli4bwfpK-K-wNF

**Comment by mimasean** [comment]
The plugin has been updated to version 2.3.5 but the shipping problem has not been solved.

**Comment by minhtruong315** [comment]
@mimasean you can use EnableOnePageCheckout: true to fix these issues
<img width="1574" alt="Screen Shot 2020-04-27 at 5 31 13 AM" src="https://user-images.githubusercontent.com/10402500/80321582-6020b300-8848-11ea-86ba-318e956934ac.png">

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
