### ISSUE TITLE
 FluxNews - I have some problem here

### ISSUE THREAD

**Issue by haidarsalim** [inspireui/support#2777]
When writing a comment through the application, the comment does not appear
The comments shown in the image were written on the web
![444](https://user-images.githubusercontent.com/54249914/79639035-9ea3d700-8191-11ea-8232-760fb25b7bcb.JPG)
---

-----
I have some things that I hope to add in the next update
-----
Please add a feature when registering by phone number. You can enter a name. A lot of people prefer not to show a phone number in the comments
-----
Please add temporary memorization of articles as this increases the application speed
----
Please add an alert that the application needs internet to view articles
----
Add a feature. Change font size as per user choice
---
Enable comments without logging in as in WordPress
---
Add a button I liked
In the articles as an option to encourage the writer
---
night mode feature without logging in
---

**Comment by haidarsalim** [comment]
I need an answer to the first question

**Comment by dttrung26** [comment]
Hi @haidarsalim ,
first of all, sorry for the late response. 
Please send me admin access to your site via trung@inspireui.com to check for the comment issue. 
For the rest feature requests, we will consider implement them later on. 
Have a nice day!

**Comment by haidarsalim** [comment]
I have sent the information to the e-mail

**Comment by dttrung26** [comment]
Hi @haidarsalim , sorry for the late response. 
Your comment section on your site has been fixed. Please give it a try. 
nice day!
