### ISSUE TITLE
Some Errors while setting up app for our website

### ISSUE THREAD

**Issue by anandkausha** [inspireui/support#2778]
Step 1 (require): A) We are entering Purchase code which is we got from codecanyon.net in  Mstore API plugins, But it is showing "The purchase code is incorrect."

![Purchase Code is not taking](https://user-images.githubusercontent.com/63690210/79642985-36b7b580-81be-11ea-9538-e368edc29238.png)

B )  You have mention in Mstore API plugins "upload the config.json from the common folder"
  1) When We should add this file in this plugin while starting of project (Original file received from your source code after downloading from codecanyon.net  ) or after completing app editing part from our end ?

  2) You Have mentioned " config.json " file but in your project directory there is "AppConfig.json" file and "Config" file which is in JavaScript not a JSON file.  So Please confirm which file wee should upload.

![configu file](https://user-images.githubusercontent.com/63690210/79643208-85b21a80-81bf-11ea-97dc-def1743e340b.png)

C) Kindly add Product filter option at many places wherever required apart from search activity in app.

D)  Vendor List not coming and vendor information is not showing in product details section

![vendor 1 (1)](https://user-images.githubusercontent.com/63690210/79643431-8ac39980-81c0-11ea-84bf-88c6f365f363.jpeg)

![vendor 1 (2)](https://user-images.githubusercontent.com/63690210/79643432-8b5c3000-81c0-11ea-8fbf-e2ecd124cc83.jpeg)

E) Login Activity is not working for customer and also for vendor.
  its giving error " Sorry, you are not allowed to do that"  and same for Sign Up form

![Login](https://user-images.githubusercontent.com/63690210/79643543-0f161c80-81c1-11ea-90e6-73a7bd1ab58d.jpeg)

F) Bottom Navigation and header is not working correctly.
some time it is at correct place and sometime its goes down and will not visible in same mobile 

![bottom navigtion](https://user-images.githubusercontent.com/63690210/79643702-d6c30e00-81c1-11ea-8a7c-78872ed4ba6d.jpeg)

![bottom navigation 2](https://user-images.githubusercontent.com/63690210/79643705-d9bdfe80-81c1-11ea-8a57-255f27b94742.jpeg)

G) There is Variable base Pricing which is not working if we change option from variable section then price of product change depend on variable, which is not working in app.

![variable](https://user-images.githubusercontent.com/63690210/79643831-813b3100-81c2-11ea-9606-024d2c4a5f7b.jpeg)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

*Note: please help to fill the required information from the above 2 steps, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhcasi** [comment]
@anandkausha - please help to update mstore-api to latest version, we have disabled the verify feature for a while due to server issues - please note that you don't need to upload the config.json for the MStore Multi Vendor (as this product is not support caching from mstore-api)

We will check the product login issues and let you know

**Comment by minhcasi** [comment]
@luyx2412 - please help to investigate the above issues - thank you!

**Comment by luyx2412** [comment]
Hi @anandkausha Can you send me the AppConfig.json and Config.js file?

Thanks

**Comment by minhcasi** [comment]
@luyx2412 - pls download from the Google sheet

**Comment by luyx2412** [comment]
Hi @anandkausha 
- The website required AppConfig.json file, sorry about missing name.
- You need setup vendor in your dashboard wordpress page.
- In Sign in/Sign up, please use sign up and use this account to sign in. Or change role in your dashboard admin.
- Can you share me the full screenshot? about Bottom navigation? 
![image](https://user-images.githubusercontent.com/8909619/80909144-3daefe00-8d50-11ea-9429-0bf376f3ca16.png)

Thanks
