### ISSUE TITLE
Fluxstore Woocommerce - Issue with APP Name and Bundle ID Changing 

### ISSUE THREAD

**Issue by swspro** [inspireui/support#2779]
Step 1 (require): detail issues and screenshots

Hi,

I wanted to change the APP NAME ( FreshWay ) and the BUNDLE ID ie from com.inspireui.fluxstore to in.pocketapp.freshway

>> Followed the documentation under customization at https://docs.inspireui.com/fluxstore/delivery-android/ for ANDROID.

>> EVERYTHING seems fine until error which I am get at MainActivty.kt file ; which is suggesting to use '.' separator 

>> Please Refer to the Attachment 

>> I will share my license which I got from Envato in the link which you have shared.

>> YOUR QUICK RESPONSE WILL BE HIGHLY APPRECIATED!

Regards,
Samaresh B.

![1](https://user-images.githubusercontent.com/15525566/79645470-45599900-81cd-11ea-944d-3266ad6344b0.JPG)
![2](https://user-images.githubusercontent.com/15525566/79645473-47235c80-81cd-11ea-97ec-fac741cd5d22.JPG)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

*Note: please help to fill the required information from the above 2 steps, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhcasi** [comment]
@swspro - could you help to attach the android folder so that we could help with checking - thank you!

**Comment by swspro** [comment]
Hi Minhcasi,

Thanks for your quick response. 

Here in the attachment you will find the ANDROID FOLDER in ZIP FORMAT

Waiting for your reply !

Samaresh 
[android.zip](https://github.com/inspireui/support/files/4498355/android.zip)

**Comment by minhcasi** [comment]
@swspro - we have tried many times but could not download this file - https://tppr.me/Is39G - you can try to use this video guide to change the bundle id  - https://www.youtube.com/watch?v=3DYdBBtvAbg&t=363s

Also, try to customize your project first, the bundle id update is only required when you release to google play store.

I'm closing this ticket and move the same #2785
