### ISSUE TITLE
[MSTORE-MV] Customising the Link to the left hand menu

### ISSUE THREAD

**Issue by nghonyuen** [inspireui/support#278]
**Mandatory Info (please complete the following information):**
* Product: MSTORE-MV
* Your Purchased Code: 34a1d23d-c198-4cd8-beec-b4d0881c6437
  (we may not reply if you are not our customer)

**Describe the issues**
I don't think it is a bug but more to I am having trouble finding the right documentation to guide me.
May I know how to I, edit the link to the below?
![img_1897](https://user-images.githubusercontent.com/47480781/52532709-48086500-2d64-11e9-883f-cdd043eb638d.jpg)

I tried updating Config.js, while the title field takes effect, the id field does not seems to point to the page's tag id. 
<img width="426" alt="screenshot 2019-02-10 at 6 48 04 pm" src="https://user-images.githubusercontent.com/47480781/52532757-9584d200-2d64-11e9-818e-564748c79526.png">

I have similar question on other configuration such as Facebook login (e.g. normally needs both App ID + App Secret to construct the login url but here seems no need, and I cannot do the FB login successfully too :( )

If there's documentation that I may have missed out, please let me know. Thanks a bunch!

**Screenshots**
As attached.

**Additional context**
Add any other detail logs about the problem here.

**Comment by thangvo9x** [comment]
Hi. Please provide me your facebook App Id. such as AppConfig.json file , i'll be config it help you. Thanks

**Comment by nghonyuen** [comment]
Please ignore my request on the Shop, News, About Us & Contact Us. Strangely, after I rebuild, it takes effect. As for Facebook App ID,  I tried the below in Config.js:

appFacebookId: "2222222222222",
  CustomPages: {
    contact_id: 2,
    about_us: 2,
  },

I will send you the file & actual ID separately. Thanks

**Comment by nghonyuen** [comment]
FB App ID: 2499249650146109

**Comment by thangvo9x** [comment]
Ah. Because your app Facebook has been created && it wasn't login in anywhere. Please login another ways(docs on facebook dev) and re-try. The problem is coming from your facebook app.
