### ISSUE TITLE
[Fluxstore Pro]- Add space between products grid 

### ISSUE THREAD

**Issue by Alnaggar94** [inspireui/support#2780]
Step 1 (require): detail issues and screenshots
1*
Hello guys, Could you please help me add space between products grid see the screenshots:

I want to make space between girds similar to this just border or space to make it like this:
![i1](https://user-images.githubusercontent.com/49800146/79676519-bdd15180-81ef-11ea-8aa5-d392838cb534.JPG)

I have tried to change the background to #fafafa :

![i3](https://user-images.githubusercontent.com/49800146/79676545-f83aee80-81ef-11ea-8446-7e819480a4d1.JPG)

![i2](https://user-images.githubusercontent.com/49800146/79676550-ff61fc80-81ef-11ea-99a4-2b25627bd811.JPG)

----------------------------------------

2*
When I change the background color the product page get a problem part of it become black (I changed the backgrond color to ##fafafa)

![i5](https://user-images.githubusercontent.com/49800146/79676737-d6db0200-81f1-11ea-869b-cbc4e39ce7d2.JPG)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

I have submitted license code via private.inspireui.com

*Note: please help to fill the required information from the above 2 steps, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by kvt0012** [comment]
Ok, sir, which file do you use to config this, sir ? 
Please show me or send it to me,  I will check it, thank you

**Comment by Alnaggar94** [comment]
@kvt0012 
I'm using config_ar.json, config_en.json
[config.zip](https://github.com/inspireui/support/files/4501611/config.zip)

and this is the full lib folder :
[lib.zip](https://github.com/inspireui/support/files/4501615/lib.zip)

**Comment by Alnaggar94** [comment]
@minhcasi @kvt0012 - any updates?

**Comment by Alnaggar94** [comment]
@minhcasi @kvt0012 - It's been more than 5 days, Whenever I changed the background to any color the product screen gets a problem as shown above in the screenshots. Please, guys, this is a serious problem.

**Comment by Alnaggar94** [comment]
@minhcasi @kvt0012 - The problem #2 solved in v 1.7.0 , I just want to add space between the products grid please help with this

**Comment by minhcasi** [comment]
@Alnaggar94 - you could customize this file by increasing the padding https://tppr.me/iUITy or add new Margin to the product card
