### ISSUE TITLE
[Mstore] - Product Variation Stock Quantity Problem

### ISSUE THREAD

**Issue by CloudExpressTeam** [inspireui/support#2781]
Regarding our issue here https://github.com/inspireui/support/issues/2719
When a product has variation the quantity isn't get properly for each variation

How to solve it?

///////
Hi, Refer to this issue we have sent you the purchase code and you have confirmed the code!
#2398

**Comment by anandkausha** [comment]
We are also Facing Same Problem, In our Project we are having variation based pricing, but its not working

**Comment by CloudExpressTeam** [comment]
I don't know why support is too late

**Comment by luyx2412** [comment]
Hi @CloudExpressTeam Can you send me your AppConfig.json and Config.js file?

Thanks

**Comment by CloudExpressTeam** [comment]
@luyx2412 [https://drive.google.com/open?id=1dUUfZQJGd_DBx25d1WVuyv7IkwskhPDc](url)

**Comment by luyx2412** [comment]
HI @CloudExpressTeam can you give me the specific issues? I just tested your config and everything worked normal.

Thanks

**Comment by CloudExpressTeam** [comment]
When we have products with variations
for example
BMW Car ==> Black (3 items) - Red (0 items) - Blue (20 items)
when user select Red Car from variation dropdown then he can add up to 10 items while it should display a message "Out Of Stock!"
and if select Black Car should add up to 3 items only
and if Blue car should add up to 20 items not only 10!

**Comment by luyx2412** [comment]
Hi @CloudExpressTeam Let us investigate about it and reply you soon.

Thanks

**Comment by CloudExpressTeam** [comment]
ok we're waiting!

**Comment by luyx2412** [comment]
Hi @CloudExpressTeam We will update the variations issue in next version.

Thanks

**Comment by CloudExpressTeam** [comment]
Awsome!
Please make the add to cart button is disabled if the product variation quantity is 0
and enabled on change the selected variation to one with stock_quantity > 0

**Comment by CloudExpressTeam** [comment]
and please note that some products have multiple attributes with variations!

Color: red - black - green
Size: Medium - Large - xLarge

**Comment by luyx2412** [comment]
Hi @CloudExpressTeam Thanks for your request, i am working to improve this feature.

Thanks

**Comment by luyx2412** [comment]
Hi @CloudExpressTeam Thanks for your request, i am working to improve this feature.

Thanks

**Comment by minhcasi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Product Variant Upgrade](https://trello.com/c/aDreI9N8/41-product-variant-upgrade)

**Comment by minhcasi** [comment]
moved to backlogs for investigating

**Comment by CloudExpressTeam** [comment]
Seems to be interesting, will try it ASAP
