### ISSUE TITLE
missing dart classes in magento config.dart

### ISSUE THREAD

**Issue by ahmadhattab** [inspireui/support#2782]
I'm trying to connect a magento site to your mobile app, But when i followed the docs and start overriding the `lib/example/magento/config.dart.txt` I ended up with missing dart classes (it's not exists in the config folder):

- `config/advance.dart`
- `config/basic.dart`
- `config/languages.dart`

Kindly Advice.

**Comment by minhcasi** [comment]
@ahmadhattab - pls provide more info from http://private.inspireui.com/ - thank you!
