### ISSUE TITLE
[Fluxstore] - errors when  i write (pod install)

### ISSUE THREAD

**Issue by limitlessfirm** [inspireui/support#2783]
Step 1 (require): detail issues and screenshots

when i write (pod install) i show the following message

Analyzing dependencies
Downloading dependencies
Generating Pods project
Integrating client project
Pod installation complete! There are 0 dependencies from the Podfile and 0 total pods installed.

[!] The Podfile does not contain any dependencies.

[!] Automatically assigning platform iOS with version 10.3 on target Runner because no platform was specified. Please specify a platform for this target in your Podfile. See https://guides.cocoapods.org/syntax/podfile.html#platform.

[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target Runner to Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig or include the Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig in your build configuration (Flutter/Release.xcconfig).

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

![screenshot](https://user-images.githubusercontent.com/59250639/79679512-e87ad480-8206-11ea-8dd7-a290a670bfeb.JPG)

*Note: please help to fill the required information from the above 2 steps, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhcasi** [comment]
@limitlessfirm - pls follow this video guide https://www.youtube.com/watch?v=ReAUZDIgh2I 

Also try to clean cache to fix this issue https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

**Comment by limitlessfirm** [comment]
I did all of the steps in your links but the errors still appear

**Comment by minhcasi** [comment]
1. please send us your result `flutter doctor`

2. also try to run this script from ios folder
```
gem install cocoapods-deintegrate
pod deintegrate
pod install
```

**Comment by limitlessfirm** [comment]
1-Flutter doctor result
------------------
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15 19A602, locale
    en-EG)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.6)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
fewbig@192 ~ %
---------------------

2- when i write (gem install cocoapods-deintegrate)
i see this message
--------------------------------
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.6.0 directory.
--------------------------------

**Comment by minhcasi** [comment]
@limitlessfirm - sorry for replying late

 it seems there is some issue with the gem library or permission on your mac, please try the following script
```
brew install ruby
```
or 
```
sudo gem update --system
```


Also, try to make a quick test with the default Example from flutter to see if it could work smoothly - https://flutter.dev/docs/get-started/test-drive?tab=vscode

**Comment by limitlessfirm** [comment]
I made a  a quick test with the default Example from flutter as you mention and it is working fine

But when i build (FluxStore) project i see the following error

------------------------------------------------------------------------
Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
Running Xcode build...
Xcode build done.                                           29.6s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    /Users/fewbig/Desktop/ds-1.6.6.04/ios/Runner/AppDelegate.swift:3:8: error: no such module 'GoogleMaps'
    import GoogleMaps
           ^
    note: Using new build system
    note: Planning build
    note: Constructing build description

Could not build the application for the simulator.
Error launching application on iPhone 11 Pro Max.
------------------------------------------------------------------------

**Comment by gouvai** [comment]
I got the same problem for days now, if someone has the solution please let me know!
