### ISSUE TITLE
[FluxBuilder] API issues and Activations

### ISSUE THREAD

**Issue by steinheil** [inspireui/support#2788]
Step 1 (require): detail issues and screenshots

**API is Correct but is not working**
![2](https://user-images.githubusercontent.com/63489149/79680645-89d44b80-8244-11ea-9224-54fa1e253620.png)

**Activation is invalid**
![3](https://user-images.githubusercontent.com/63489149/79680649-8ccf3c00-8244-11ea-82bd-e794ac867a2d.png)

**Error of API Validation**
![1](https://user-images.githubusercontent.com/63489149/79680652-8f319600-8244-11ea-8e25-2a5b94c9aa6d.png)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

*Note: please help to fill the required information from the above 2 steps, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhcasi** [comment]
@steinheil - pls move this ticket to https://github.com/inspireui/fluxbuilder/issues - thank you!
