### ISSUE TITLE
Beostore Build error

### ISSUE THREAD

**Issue by bhashid** [inspireui/support#2789]
hello inspireui developers, I bought this source from codecanyon long back but i never used it..
i m trying this app for the first time.. tried to run the app with default settings , i mean just testing your source code with your predefined settings . Can you help me in fixing this error .
![Capture](https://user-images.githubusercontent.com/63911452/79680777-30aeec80-8231-11ea-87b8-4bf0c698c724.PNG)
![Screenshot_20200418-213501_BeoNews](https://user-images.githubusercontent.com/63911452/79680779-3278b000-8231-11ea-8133-993559fb158d.jpg)

or do you have latets version of this pack.. i m getting lot of warnings and build fails

**Comment by bhashid** [comment]
Hello developers 
I m waiting for you reply 

Can you provide we latest update of this package 
I m getting many errors with different versions of node
I tried using 10.x 12.x and even new versions..

Everytime I run react-native run-android I m getting different errors ..

**Comment by minhcasi** [comment]
@luyx2412 - pls help for suggestion - thank you!

**Comment by luyx2412** [comment]
Hi @bhashid Please open your Android Studio to sync with the config and run it again. Please make use you downloaded Beonews latest version.

Thanks

**Comment by bhashid** [comment]
Can explain in steps 
Do you mean 
I have to load the android project into android studio and same time install yarn?

**Comment by bhashid** [comment]
Same error 
Gradle build finished 
But 
react-native run-android  stuck at red screen

**Comment by bhashid** [comment]
problem mostly due to outdated packages . now i m having this error
![6251ed3d-3a78-4cff-ac7f-69c2802028c0](https://user-images.githubusercontent.com/63911452/79894513-2eac7f80-8423-11ea-8338-aff1c09deb6f.jpg)

**Comment by luyx2412** [comment]
Hi @bhashid can you send me your project via luyxtran264@gmail.com. Let me investigate about it.

Thanks

**Comment by bhashid** [comment]
Sir
I haven't changed any file 
Just try to compile your source code

**Comment by bhashid** [comment]
Problem is due to outdated dependencies in package.json


Pls provide me new update 

I m trying to reach you ppl past 6 days

**Comment by bhashid** [comment]
Trying to run
3.06 beonews from codecanyon 
No changes to files

**Comment by luyx2412** [comment]
Hi @bhashid Please send your project via inspireui.team@gmail.com. I need your project to investigate, because i tested the latest version which worked normal.

Thanks

**Comment by bhashid** [comment]
Fixed errors in mac ..now app complies 
But I m having few problems 
1  sign in sign up not working 
2 in sign up page letters not visible 
3 admob not working

**Comment by luyx2412** [comment]
Hi @bhashid 
- Please make sure you follow setup https://docs.inspireui.com/beonews/wordpress-setting/
- You meant you can not see characters in the sign up screen?
- Please make sure you config admob same document https://docs.inspireui.com/beonews/admob-setting/

Thanks

**Comment by bhashid** [comment]
All wordpress settings are correct 
Yes I can't see any characters in signup.
Admob config settings also correct ..but no ads

**Comment by bhashid** [comment]
Sir pls Check your demo in play store ver 3.0.2
Same errors in 3.0.6
Sign in Sign up not working
Sign up characters not shown
Share not working 
Ads not working 

Sir
Pls respond fast. 10 days gone still my problems not solved

**Comment by luyx2412** [comment]
Hi @bhashid sorry about reply you late. Can you send me the screenshot issue? I just tested beonews and everything worked normal.

Thanks

**Comment by bhashid** [comment]
Bro 
Pls check your app @ play store  and reply
Sign in and sign up not working 
Share not working
Many problems
I m also having same problems 

I can't keep posting here and there ..
I bought more than 15 source codes from codecanyon never faced issue like this.


https://codecanyon.net/item/beonews-react-native-mobile-app-for-wordpress/19186520/comments

I have to wait 3 days for this reply..
10 mins you solve my issue

**Comment by bhashid** [comment]
https://github.com/inspireui/support/issues/2878

https://github.com/inspireui/support/issues/2822

All related to login
Not solved but issues closed

**Comment by bhashid** [comment]
Sign in Sign Up Facebook sign in not working
https://youtu.be/ECnYtXX1KmM
Pls see this video

**Comment by bhashid** [comment]
Adding comment requires login but when logged in via fb it is again asking for login

Admob no being displayed  and I configured in this format 

deviceID: "pub-xxxxxxxxxxx",
 unitID: "ca-app-pub-xxxxxxxxxxx/xxxxxxxxxxx",
 unitInterstitial: "ca-app-pub-xxxxxxxxxxx/xxxxxxxxxxx" },

Pls check the video 
Admob banner not displayed 
And comment related issue 

Its signed apk


https://youtu.be/ANPRIzQY4bc

**Comment by luyx2412** [comment]
Hi @bhashid the beonews in play store did not latest version. And i just test the facebook login and admob on latest version and everything worked normal. So can you send again current project via inspireui.team@gmail.com?
https://www.dropbox.com/s/1m0biwsye56yf5l/Screen%20Recording%202020-05-03%20at%2014.47.38.mov?dl=0
![image](https://user-images.githubusercontent.com/8909619/80908818-4520d800-8d4d-11ea-9860-272b004dc0dd.png)

Thanks

**Comment by bhashid** [comment]
@luyx2412 
@minhcasi 

Sir mail sent..Pls check and reply as soon as possible.

**Comment by luyx2412** [comment]
Hi @bhashid I just saw your config, but it is default config of beonews. Can you send me your config?

Thanks

**Comment by bhashid** [comment]
Pls close this thread 

I m not interested with your app any more
Wasted 59$ for 

Thank you
