### ISSUE TITLE
how to send geolocation data to woocommerce via order?

### ISSUE THREAD

**Issue by hytcelebi100068** [inspireui/support#2791]
Step 1 (require): detail issues and screenshots

Hello, first of all thanks for the application. It works very well.

I just want to ask is there any way to send geo location to woocommerce backend? For now it just fills adress. I’m working with carriers and i want to make them job easier.

And about onboarding screen and banner slider photos. Is there no way to fix content show properly and complete? I tried all BoxFit options but none of them doesn’t meet my requests. I want to prepare templates for used in discount, product marketing etc. but it seems there is no standart for them.

And last about localization. I translated all strings placed on messages_en. But there is also strings placed on dart files to show exceptions, warnings, etc. I translated them too. It seems no error in my app but i’m afraid to this kind of tranlations going to cause an error. What should i do about this?

Thanks in advance.

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

**Comment by hytcelebi100068** [comment]
Hi, i sent support ticket.

1) I want to send location data over mail or woocommerce order entry, not to fill adress only (mentioned here: https://docs.inspireui.com/fluxstore/google-map/)

2) I'm trying to customize screens but they seems like this: [https://imgur.com/a/LtOb2cw](imgur)
Not fits the box. I tried all options in BoxFit widget under the file `/lib/screens/home/onboard_screen.dart`. When i took screenshots they are settled up fitWidth. Is there no way to fix image resolution to customization? Same problem in bannerImage layout childs in home screen.

3) I created another language <Turkish> to shown in app. But `lib/generated/intl/messages_tr.dart` file doesn't contain warnings, exceptions shown in app. They stay in English. I can translate all strings coded in files and i did. But isn't there a way to extract them to `messages_tr.dart` too?

**Comment by minhcasi** [comment]
1. this feature is not supported but you could try to add the google map URL via Order Notes (include long/lat), then the admin could see this order note link from the Wordpress site, we will consider the best way to implement this feature on next release as well 

2. you can customize the image on this file https://tppr.me/WQ7Cp

3. Try to add new language via .arb file - https://tppr.me/Qs15l - please check more detail from the document https://docs.inspireui.com/fluxstore/multi-language/

**Comment by IamJAX** [comment]
How do I add Google map url via order notes?

**Comment by hytcelebi100068** [comment]
> 
> 
>     1. this feature is not supported but you could try to add the google map URL via Order Notes (include long/lat), then the admin could see this order note link from the Wordpress site, we will consider the best way to implement this feature on next release as well
> 
>     2. you can customize the image on this file https://tppr.me/WQ7Cp
> 
>     3. Try to add new language via .arb file - https://tppr.me/Qs15l - please check more detail from the document https://docs.inspireui.com/fluxstore/multi-language/
> 
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/0e36d1a23c2e9da0aaf824b900ee387ca542f3d2/68747470733a2f2f747070722e73332e616d617a6f6e6177732e636f6d2f75706c6f6164732f39643537626363323830653238366132326566316131386265376663616264622e6a7067"><img alt="" height="14" src="/favicon-32x32.png"> tppr.me**[Public - Android Studio_2020-04-22 09-47-25](https://tppr.me/WQ7Cp)**
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/9b1dad0ee13a796df6287b6c9d1d215e128deff1/68747470733a2f2f747070722e73332e616d617a6f6e6177732e636f6d2f75706c6f6164732f39353666333663373631376631343363333133663037613737353065633538632e6a7067"><img alt="" height="14" src="/favicon-32x32.png"> tppr.me**[Public - Android Studio_2020-04-22 09-47-56](https://tppr.me/Qs15l)**
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/c1f5c35bdee2cf5a71b0e35ef38becdf8ec89d72/68747470733a2f2f646f63732e696e737069726575692e636f6d2f696d616765732f6d6574612f47686f73742d446f63732e6a7067">InspireUI Document**[FluxStore - Universal mobile commerce Flutter app for Magento, WooCommerce and Opencart](https://docs.inspireui.com/fluxstore/multi-language/)**Fluxstore is universal app that fully integration with the Woocommerce, Mangeto and Opencart

Thanks for the answers, i ll try to push location via url. Btw i was trying to tell you in question 3, there is coded strings in dart files and they're not referenced this .arb files (yea i created language file via arb. So if i change the language it's not changing strings completely. This strings stays in english, like exception warnings. Is there a way to get these errors strings to .arb files? At least these ones how can i translate them? (https://imgur.com/a/z06q6mZ)

**Comment by minhcasi** [comment]
@hytcelebi100068 - we will review some missing language warning and order status on later release - thank you!

**Comment by IamJAX** [comment]
How do I pass Google map url to order notes?

**Comment by minhcasi** [comment]
@IamJAX - we will upgrade this feature on next release, basically you will get the long/lat after user fill in the address and include this long/lat with google URL map with your own key - thank you!

**Comment by IamJAX** [comment]
@minhcasi Thank you for adding it to the next release. Is this available in the GitLab version?

I have added a plugin to select the delivery date/time while placing order. These details are saved as order Metadata. If I add 2 fields below order notes, can you guide me on how to pass these two as order meta data or as order notes? which file to modify for this change?

**Comment by minhcasi** [comment]
@IamJAX - it is available on GitLab - we will release a new version - thank you! 

You can update the meta_data via POST after create new Order ID - please check this guide - https://stackoverflow.com/questions/28952970/woocommerce-api-update-order-meta-fields

**Comment by minhcasi** [comment]
@hytcelebi100068 pls help to move your conversation to same one ticket #2845
