### ISSUE TITLE
MStore Pro - Complete React Native template for e-commerce

### ISSUE THREAD

**Issue by anandkausha** [inspireui/support#2792]
Step 1 (require):  1) In Our Last Ticket I asked for 7 Questions and you People only replied fro one Question.

Please also reply for remaining questions.  Please refer below ticket URL

https://github.com/inspireui/support/issues/2778

2) Login Activity is not working for customer and also for vendor.
its giving error " Sorry, you are not allowed to do that" and same for Sign Up form

This is important question for you, please provide solution for this.

3) In your Demo APP You have given some Banner advertisement section in homelayout , But How to change that advertisement from Website. You Should  Provide this feature in your Wordpress Plugin , from that feature we can change our Banner Advertisement which will display in Home 
layout.

![WhatsApp Image 2020-04-19 at 10 59 29 PM](https://user-images.githubusercontent.com/63690210/79694981-aea2e000-8291-11ea-810b-d5aa21b055b3.jpeg)
  
Some Other Developer are doing this activity as below

![Screenshot_2020-04-19 App Option ‹ Vignesh Herbal Products — WordPress](https://user-images.githubusercontent.com/63690210/79695043-08a3a580-8292-11ea-8227-da029e520f07.png)
 
 

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

*Note: please help to fill the required information from the above 2 steps, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhcasi** [comment]
1. pls continuous your feedback on ticket #2778
2. we will check this issue
3. sorry - we don't have good solution so far - will investigate
