### ISSUE TITLE
 shipping method

### ISSUE THREAD

**Issue by rodrigoalves1901** [inspireui/support#2793]
![image](https://user-images.githubusercontent.com/43248152/79696832-0bc87280-824d-11ea-987a-1ab0d5dfbd4f.png)

Good afternoon. After about 4 months without messing with the application because I had an error in the shipping method here in Brazil using the post office plugin. I wonder if it has already been fixed. Because I need to use the application. Recapitulating the problem in the shipping method, the freight calculation always comes as zero.

As you can see below on the website the calculation is done normal.

![image](https://user-images.githubusercontent.com/43248152/79696922-94471300-824d-11ea-972d-a64f5cff139b.png)

 And no app

![image](https://user-images.githubusercontent.com/43248152/79697183-46cba580-824f-11ea-9338-b11dafa411bb.png)

**Comment by minhcasi** [comment]
@rodrigoalves1901 - please try to enable the new `EnableOnePageCheckout` option to support dynamic Shipping option from the app - thanks

**Comment by rodrigoalves1901** [comment]
this way it worked he accesses the website to finish the process. very good. But do you have a project to be all finalized within the application with a third-party plugin?

**Comment by minhcasi** [comment]
Yes, it will handle the data to the website via Webview

Could you explain more about the third-party plugin? I'm not sure to understand your point 👍

**Comment by rodrigoalves1901** [comment]
Good Morning. What I wanted to say is if you have in your project to improve the shipping method without being Webview when using a plugin like the one in Brazil which is the post office. Or if you know any way to improve Webview because in the image below the customer may end up leaving the product purchase page and navigating the site.

In the image below I clicked on buy and already sent me to my website more opens so the check is below. Is there a way to open it right now when typing in the information

![image](https://user-images.githubusercontent.com/43248152/79977611-8cb18500-846c-11ea-8c39-5b34dadd4e70.png)

**Comment by minhcasi** [comment]
Hi, thank you for the screenshot - on the latest 1.6.7 you could use new option NativeOnePageCheckout to support display the native UI (shipping / address) combine with final Webview to support the payment - this could improve the payment process - thank you!

**Comment by rodrigoalves1901** [comment]
Perfect, does this version have a release day?

**Comment by minhcasi** [comment]
@rodrigoalves1901 - it is ready on Gitlab, please download there - or we will upload and notify to your email in 1-2 days - thank you!
