### ISSUE TITLE
working under flutter beta bug

### ISSUE THREAD

**Issue by abedfatafta** [inspireui/support#2794]
Step 1 (require): detail issues and screenshots

when i switched flutter to beta to include web  
when run i got the following 
.pub-cache/hosted/pub.dartlang.org/extended_image-0.7.2/lib/src/gesture/extended_image_slide_page_route.dart:333:9: Error: No named parameter with the name 'animation'.
        animation: animation,

Step 2 (require): verify license and sharing config files via this google form - you have it in previous 2 cased 

*Note: please help to fill the required information from the above 2 steps, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhcasi** [comment]
@abedfatafta - please provide more verify info from http://private.inspireui.com/ then reopen the ticket - thank you!
