### ISSUE TITLE
help with fluxlisting app

### ISSUE THREAD

**Issue by najeebalnasser** [inspireui/support#2795]
hello there,
hope you are doing well during these hard days.
I am facing a hard time with the local app developer working on my fluxlisting in the past months, he claims that there are many things wrong with the code, I believe the code is fine but he doesn't know how to deal with flutter code & I personally don't have any coding experience. before looking for an online freelancer to help me I want to ask you if you can help me for an extra charge, or suggest to me someone you know that he can do it for me.
- I need to configure the app & link it to my website ( I am using listingpro )
- I need to add languages ( translation will be for the main menu & the headlines. just a few words).
- ability to add listing from the app & make PayPal payments.
- show the user dashboard.
I will provide anything regarding images, graphics, designs or any other media.
thanks a lot

**Comment by minhcasi** [comment]
@najeebalnasser - please help to provide all detail info and send to our support email support@inspireui.com 

The team is also working hard on these crazy CoV days and keep upgrade new features on next release, they may available soon in 1-2 week and could help you with some customize and release - thank you for your time, keep safe out here
