### ISSUE TITLE
Mstore Pro not picture in apps

### ISSUE THREAD

**Issue by sanlalex** [inspireui/support#2796]
Hello i have a issue i can not get picture in apps

![mstore not pics](https://user-images.githubusercontent.com/33254426/79704000-ae5d1180-829e-11ea-9081-7c83874d41a0.jpg)
![Mstore proff](https://user-images.githubusercontent.com/33254426/79704001-b026d500-829e-11ea-8c32-9f66cd638d6a.jpg)

**Comment by minhcasi** [comment]
@sanlalex - pls check this solution - https://docs.inspireui.com/mstore/woo-setting/#product-display-sizes - thank you!

**Comment by sanlalex** [comment]
Ok thanks for support.
i tried this. But no working . Same problem.
I tried with expo version same problem

**Comment by minhcasi** [comment]
@luyx2412 - please help to suggest the solution

**Comment by luyx2412** [comment]
Hi @sanlalex Can you provide your AppConfig.json and Config.js file?

Thanks
