### ISSUE TITLE
[Fluxstore] 1.6.6b Opencart cannot checkout successfully

### ISSUE THREAD

**Issue by netdreamland** [inspireui/support#2798]
Step 1 (require): detail issues and screenshots
<img width="348" alt="image" src="https://user-images.githubusercontent.com/12180247/79708370-d1fd7780-82f1-11ea-8c02-d4adcb15224b.png">

When I add things to shopping cart until the checkout part, I could not make a successful order.

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

*Note: please help to fill the required information from the above 2 steps, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhtruong315** [comment]
@netdreamland can u send me admin account via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/2798

**Comment by johnsonyick** [comment]
Sorry that the website is under production, we could not share the admin right for this.
Would you have any script or files needed? I may grab it here!

**Comment by netdreamland** [comment]
we are capable of handling the checkout issue, there's another issue, the order no. returned from opencart is always #0

**Comment by netdreamland** [comment]
Meanwhile, I gonna test other functions, such as profile updating, there's error
<img width="348" alt="image" src="https://user-images.githubusercontent.com/12180247/79739095-46efa200-8330-11ea-9cf8-99b4ecafeb3b.png">

I wonder if there's any QA before release ?

**Comment by netdreamland** [comment]
Yet another bug has been shown while i double tapped the email for selection
<img width="348" alt="image" src="https://user-images.githubusercontent.com/12180247/79741058-2d038e80-8333-11ea-97f7-aa737b2eb8fb.png">
**Another exception was thrown: NoSuchMethodError: The getter 'cutButtonLabel' was called on null.**

**Comment by netdreamland** [comment]
> Yet another bug has been shown while i double tapped the email for selection
> <img alt="image" width="348" src="https://user-images.githubusercontent.com/12180247/79741058-2d038e80-8333-11ea-97f7-aa737b2eb8fb.png">
> **Another exception was thrown: NoSuchMethodError: The getter 'cutButtonLabel' was called on null.**

I found the solution to add below lines to app.dart, and it fixed
```
 GlobalCupertinoLocalizations.delegate,
  DefaultCupertinoLocalizations.delegate
```

**Comment by minhtruong315** [comment]
after order success, the api doesn't response order number. so it shows zero. we will update api to support that later.
I will help you check edit profile issue. then let you know

**Comment by harry503** [comment]
@minhcasi @minhtruong315  When will it be released? and make sure it's well tested especially for us using opencart

**Comment by netdreamland** [comment]
hi @minhtruong315 would it be any update from your side?

**Comment by minhtruong315** [comment]
@netdreamland pls update Fluxstore 1.6.7 to fix your issues

**Comment by netdreamland** [comment]
hi @minhtruong315 
i have updated 1.7.0 , however I still found the user update is not functioning.
