### ISSUE TITLE
Almost all flutter packages throws MissingPluginException

### ISSUE THREAD

**Issue by Sayandhkp** [inspireui/support#2799]
We have setup the shopify application successfully. We are using graph ql version and it is working fine. 
But almost all flutter packages added in pubspec.yaml throws MissingPluginException in android. **This causes application stuck in payment page. The payment uses web_view plugin which also throws this exception and application stuck on here.**

**Some Examples **

[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method launch on channel flutter_webview_plugin)

Unhandled Exception: MissingPluginException(No implementation found for method setstatusbarwhiteforeground on channel plugins.fuyumi.com/statusbar)

Please help to solve these issues

**Complete log of flutter_webview_plugin**

`[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method launch on channel flutter_webview_plugin)
E/flutter ( 5610): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
E/flutter ( 5610): <asynchronous suspension>
E/flutter ( 5610): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter ( 5610): #2      FlutterWebviewPlugin.launch (package:flutter_webview_plugin/src/base.dart:225:20)
E/flutter ( 5610): #3      _WebviewScaffoldState.build.<anonymous closure> (package:flutter_webview_plugin/src/webview_scaffold.dart:156:30)
E/flutter ( 5610): #4      _WebviewPlaceholderRender.notifyRect (package:flutter_webview_plugin/src/webview_scaffold.dart:246:7)
E/flutter ( 5610): #5      _WebviewPlaceholderRender.paint (package:flutter_webview_plugin/src/webview_scaffold.dart:256:7)
E/flutter ( 5610): #6      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2262:7)
E/flutter ( 5610): #7      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
E/flutter ( 5610): #8      RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2512:15)
E/flutter ( 5610): #9      RenderCustomMultiChildLayoutBox.paint (package:flutter/src/rendering/custom_layout.dart:396:5)
E/flutter ( 5610): #10     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2262:7)
E/flutter ( 5610): #11     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
E/flutter ( 5610): #12     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:128:15)
E/flutter ( 5610): #13     _RenderInkFeatures.paint (package:flutter/src/material/material.dart:531:11)
E/flutter ( 5610): #14     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2262:7)
E/flutter ( 5610): #15     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
E/flutter ( 5610): #16     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:128:15)
E/flutter ( 5610): #17     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:391:12)
E/flutter ( 5610): #18     RenderPhysicalModel.paint (package:flutter/src/rendering/proxy_box.dart:1792:15)
E/flutter ( 5610): #19     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2262:7)
E/flutter ( 5610): #20     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
E/flutter ( 5610): #21     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:128:15)
E/flutter ( 5610): #22     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2262:7)
E/flutter ( 5610): #23     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
E/flutter ( 5610): #24     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:128:15)
E/flutter ( 5610): #25     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2262:7)
E/flutter ( 5610): #26     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:135:11)
E/flutter ( 5610): #27     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:95:5)
E/flutter ( 5610): #28     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:201:7)
E/flutter ( 5610): #29     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:182:7)
E/flutter ( 5610): #30     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:128:15)
E/flutter ( 5610): #31     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2262:7)
E/flutter ( 5610): #32     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
E/flutter ( 5610): #33     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:128:15)
E/flutter ( 5610): #34     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:391:12)
E/flutter ( 5610): #35     PaintingContext.pushOpacity (package:flutter/src/rendering/object.dart:613:5)
E/flutter ( 5610): #36     RenderAnimatedOpacity.paint (package:flutter/src/rendering/proxy_box.dart:928:23)
E/flutter ( 5610): #37     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2262:7)
E/flutter ( 5610): #38     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
E/flutter ( 5610): #39     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:128:15)
E/flutter ( 5610): #40     RenderFractionalTranslation.paint (package:flutter/src/rendering/proxy_box.dart:2505:13)
E/flutter ( 5610): #41     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2262:7)
E/flutter ( 5610): #42     PaintingContext.paint
I/flutter ( 5610): _ProductTitleState enableStar false
I/flutter ( 5610): [Fluxstore][Tabbar] build
I/flutter ( 5610): [Fluxstore][Home] build`

**Comment by minhcasi** [comment]
@Sayandhkp - pls send more detail info to http://private.inspireui.com then reopen the ticket - thanks

**Comment by Sayandhkp** [comment]
I have updated the details via google forms , please check and reopen the issue and support us to resolve the issue asap

**Comment by minhcasi** [comment]
@Sayandhkp - sorry for the late response as we missed your message. 

Could you help to check the following solutions:
1. update flutter channel to stable
```
flutter channel stable
flutter update --force
```
2. Use this video for the installing https://www.youtube.com/watch?v=OIpnoThJ2Rs&feature=emb_logo

3. Try to clean cache - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

**Comment by Sayandhkp** [comment]
@minhcasi I have tried all above steps, still the same issues remains. 

We are not able to add any more packages also. Immediately we need to solve the web_view package issue mentioned above. It is not able to place the order.

**Comment by minhcasi** [comment]
@Sayandhkp - we are going to upload new version today and include this fix - thank you!

**Comment by Sayandhkp** [comment]
> @Sayandhkp - we are going to upload new version today and include this fix - thank you!

Okey @minhcasi , Please let me know when it finished.

**Comment by minhcasi** [comment]
@Sayandhkp - pls download the latest version 1.6.7 - thank you!

**Comment by Sayandhkp** [comment]
> @Sayandhkp - pls download the latest version 1.6.7 - thank you!

Thanks @minhcasi , I will check and update.

**Comment by Sayandhkp** [comment]
> @Sayandhkp - pls download the latest version 1.6.7 - thank you!

@minhcasi I have installed the updated version it seems the MissingPluginException issue is fixed. 
But I am not able to check the checkout flow and order completion process , Shipping method page gives error. 

**Please find the log below**

`I/flutter (23543): Product { id: Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ2MjA4NjIyNTkzMzU= name: Overprint T-Shirt in Navy }
I/flutter (23543): getShippingMethods with checkoutId 
I/flutter (23543): GraphQL Errors:
I/flutter (23543): Variable checkoutId of type ID! was provided invalid value: Undefined location`

**App Screenshot**

![Screenshot_2020-04-24-23-25-12-570_com inspireui fluxstore](https://user-images.githubusercontent.com/28803144/80242919-d0320c00-8683-11ea-8a01-7244d849dee9.jpg)

**Comment by minhcasi** [comment]
@Sayandhkp - try to enable the EnableOnePageCheckout: true to use the WebView payment, we will upgrade the app to support native payment on next release - thank you!

**Comment by Sayandhkp** [comment]
> @Sayandhkp - try to enable the EnableOnePageCheckout: true to use the WebView payment, we will upgrade the app to support native payment on next release - thank you!

@minhcasi This fixes the payment flow issue, but most of the times another issue/error is showing when click to **checkout** button from **Cart page**.

Can you please make sure that the basic functionalities works fine for the application. 

**Error Log**

`addItemsToCart null
I/flutter (16108): ::::addItemsToCart shopify error
I/flutter (16108): NoSuchMethodError: The getter 'id' was called on null.
I/flutter (16108): Receiver: null
I/flutter (16108): Tried calling: id`

**Screenshot**

![Screenshot_2020-04-27-10-24-51-213_com inspireui fluxstore](https://user-images.githubusercontent.com/28803144/80335297-7c851580-8871-11ea-993f-12f3ec4cd941.jpg)

**Comment by Sayandhkp** [comment]
> > @Sayandhkp - try to enable the EnableOnePageCheckout: true to use the WebView payment, we will upgrade the app to support native payment on next release - thank you!
> 
> @minhcasi This fixes the payment flow issue, but most of the times another issue/error is showing when click to **checkout** button from **Cart page**.
> 
> Can you please make sure that the basic functionalities works fine for the application.
> 
> **Error Log**
> 
> `addItemsToCart null I/flutter (16108): ::::addItemsToCart shopify error I/flutter (16108): NoSuchMethodError: The getter 'id' was called on null. I/flutter (16108): Receiver: null I/flutter (16108): Tried calling: id`
> 
> **Screenshot**
> 
> ![Screenshot_2020-04-27-10-24-51-213_com inspireui fluxstore](https://user-images.githubusercontent.com/28803144/80335297-7c851580-8871-11ea-993f-12f3ec4cd941.jpg)

@minhcasi I have tried to solve this issue and found that this happens when there is no variant for the selected product. If I add a variant for the product this issue fixes. 

Is that mandatory that every product should have minimum one variant added from back end admin ?   But in admin portal variant is not a mandatory field .

**Comment by Sophyra-Hou** [comment]
I have the same issue in Checkout page. I don't know where find and set the EnableOnePageCheckout: true to use the WebView payment. Would be appreciate if you could share.

**Comment by Sayandhkp** [comment]
> EnableOnePageCheckout

@Sophyra-Hou  You can find EnableOnePageCheckout in 

fluxstore-shopify 1.6.7\source\lib\common\config\payments.dart file

**Comment by Sophyra-Hou** [comment]
@Sayandhkp I found it. Thank you so much!

**Comment by Sayandhkp** [comment]
> > > @Sayandhkp - try to enable the EnableOnePageCheckout: true to use the WebView payment, we will upgrade the app to support native payment on next release - thank you!
> > 
> > 
> > @minhcasi This fixes the payment flow issue, but most of the times another issue/error is showing when click to **checkout** button from **Cart page**.
> > Can you please make sure that the basic functionalities works fine for the application.
> > **Error Log**
> > `addItemsToCart null I/flutter (16108): ::::addItemsToCart shopify error I/flutter (16108): NoSuchMethodError: The getter 'id' was called on null. I/flutter (16108): Receiver: null I/flutter (16108): Tried calling: id`
> > **Screenshot**
> > ![Screenshot_2020-04-27-10-24-51-213_com inspireui fluxstore](https://user-images.githubusercontent.com/28803144/80335297-7c851580-8871-11ea-993f-12f3ec4cd941.jpg)
> 
> @minhcasi I have tried to solve this issue and found that this happens when there is no variant for the selected product. If I add a variant for the product this issue fixes.
> 
> Is that mandatory that every product should have minimum one variant added from back end admin ? But in admin portal variant is not a mandatory field .

@minhcasi  This issue still persist, How can i solve this? We are only able to checkout products which have at-least one variant.  All other products shows this error.

**Comment by minhcasi** [comment]
@luyx2412 please help to check this issue

**Comment by luyx2412** [comment]
Hi @Sayandhkp Let we are investigating the issue.

Thanks

**Comment by Sayandhkp** [comment]
@luyx2412 @minhcasi Any updates on this issue?

**Comment by Sayandhkp** [comment]
@luyx2412  I have managed to solve above issue, now I am facing the following one. 

I am facing a GraphQl exception on the **Checkout page**-> **Shipping Method** Tab.  It shows that you don't have any items that require shipping. I am using Shopify version 1.6.7. This is a critical issue we are facing, please support us to solve this issue ASAP

**ERROR LOG**

`I/flutter (23692): GraphQL Errors:
[        ] I/flutter (23692): You don't have any items that require shipping: Undefined location
[   +1 ms] I/flutter (23692): ::::getShippingMethods shopify error
[        ] I/flutter (23692): Exception: GraphQL Errors:
[        ] I/flutter (23692): You don't have any items that require shipping: Undefined location
[+29727 ms] V/FA      (23692): Recording user engagement, ms: 78502
[        ] V/FA      (23692): Connecting to remote service`

**Screenshot**

![WhatsApp Image 2020-05-08 at 2 37 43 PM](https://user-images.githubusercontent.com/28803144/81390833-bb508080-9139-11ea-8cf7-c15dd0a0d588.jpeg)

**Comment by luyx2412** [comment]
Hi @Sayandhkp We uploaded new version to fix this issue. Please update latest version Fluxshopify.

Thanks

**Comment by Sayandhkp** [comment]
@luyx2412  May I know the version code.?

**Comment by Sayandhkp** [comment]
@luyx2412 I have tried the "EnableOnePageCheckout": true option already in v1.6.7. It redirects to the login web page. After login, it shows your shopping cart is empty. The item added to the cart using the mobile app is not getting synced on the web.

I haven't tried this method in the latest build. I will check the same and let you know.


**Screenshot**

![WhatsApp Image 2020-05-08 at 3 07 09 PM](https://user-images.githubusercontent.com/28803144/81393919-c35eef00-913e-11ea-8858-9aaef4003536.jpeg)

**Comment by Sayandhkp** [comment]
@luyx2412 "EnableOnePageCheckout": true now the flow is working fine. We can complete the order using webview.  But still, the user needs to log in two times. One from the app and one from webview. it is not a good UX. So is it possible to skip the login part from WebView?

**Comment by luyx2412** [comment]
Hi @Sayandhkp Thanks for your feedbacks, we are updating the payments to improve behavior and UX.

Thanks

**Comment by luyx2412** [comment]
Closed! Feel free to create new issue.
