### ISSUE TITLE
[ListApp] - Installation issue (2)

### ISSUE THREAD

**Issue by Pars1vaLl** [inspireui/support#28]
**Mandatory Info (please complete the following information):**
 - Product: ListApp
 - Your Purchased Code: 85059e37-2ddd-478d-899b-6db006280782

**Describe the issues**
https://github.com/inspireui/support/issues/9 - my first issue. Git reinstall and setting PATH environment didn`t help... Here is screens of what it says now.

**Screenshots**
[screenshot_2](https://user-images.githubusercontent.com/45024483/48919053-75a2e800-eeb2-11e8-9d1e-8388327caf3a.png)
[screenshot_3](https://user-images.githubusercontent.com/45024483/48919080-99fec480-eeb2-11e8-9fe2-d23d774048d2.png)

**Additional context**
Add any other detail logs about the problem here.

**Comment by minhcasi** [comment]
@thangvo9x could you zip the node_modules and share to see if it can help, looks like it is an issue with the git download - thanks

**Comment by thangvo9x** [comment]
@Pars1vaLl You can download node_modules folder here then put into your project.
https://we.tl/b-vd29aHzfHj
Thanks

**Comment by Pars1vaLl** [comment]
> @Pars1vaLl You can download node_modules folder here then put into your project.
> https://we.tl/b-vd29aHzfHj
> Thanks

Ok.I will try and respond soon.Thanks:)

**Comment by Pars1vaLl** [comment]
@minhcasi @thangvo9x  Hi guys.
I unziped Node_modules. Now npm error dissapeared,but I still can`t run Android simulator with Genymotion. I am attaching screenshots, so hope you will answer as soon as possible.

[android adb](https://user-images.githubusercontent.com/45024483/48959118-32fe1000-ef85-11e8-99b3-681e31058f9d.png)  - That how Expo Cli reacts to "Android Simulator Start"
[Cmd](https://user-images.githubusercontent.com/45024483/48959133-4b6e2a80-ef85-11e8-8bea-25a1bff929d5.png) Command Line respond.

Thanks:)

**Comment by minhcasi** [comment]
Hi, could you try to create the folder from document or temp (the folder where have full access right), and try to run the Example project to see if can run as normal:
https://docs.expo.io/versions/v31.0.0/introduction/installation

I suspect you have an issue with the Android simulator config

Thank you!

**Comment by Pars1vaLl** [comment]
Hi, downloaded ListApp last update, created new folder and start it with admin permissions - and it works now! Looks like everything is fine.
Thanks;)
