### ISSUE TITLE
Fluxstore WooCommerce issue in flutter_plugin_android_lifecycle

### ISSUE THREAD

**Issue by abd096** [inspireui/support#2800]
Hello,

Every time i try to build the app or run  "pub get" i am getting the following error: 

flutter_plugin_android_lifecycle-1.0.6\android\src\main\kotlin\io\flutter\plugins\flutter_plugin_android_lifecycle\FlutterAndroidLifecyclePlugin.kt' even though it exists. Please verify that this file has read permission and try again.

i am attaching the error screenshot.

https://drive.google.com/file/d/1Jpvn_SMmtOmi7hHeCC5tIUHEfKIuuY69/view?usp=sharing

Thanks

**Comment by minhcasi** [comment]
@abd096 - this is related to the issue of Flutter on your PC, pls try some solution on this ticket https://github.com/flutter/flutter/issues/47933

1. reinstall flutter 
2. remove the pubspec.lock and .dart_tool folder (hidden folder)
