### ISSUE TITLE
Can't run app with compile error. (Error: Invalid package URI 'package:/common/constants.dart':)

### ISSUE THREAD

**Issue by CreatorKim** [inspireui/support#2802]
Hi, I can't run app.

I have existing mylisting theme website (https://gunmastyle.com)
and I followed https://docs.inspireui.com/fluxstore/listing-directory/
But I can't run app.

<img width="1546" alt="스크린샷 2020-04-20 오후 5 45 59" src="https://user-images.githubusercontent.com/23479206/79732778-1c511980-832f-11ea-8a43-e41a134de0c9.png">
<img width="1565" alt="스크린샷 2020-04-20 오후 5 46 10" src="https://user-images.githubusercontent.com/23479206/79732787-207d3700-832f-11ea-8207-5166188c6e24.png">

**Comment by minhcasi** [comment]
@CreatorKim - pls fix by this screenshot https://tppr.me/enpIC

**Comment by CreatorKim** [comment]
Thanks a lot!
