### ISSUE TITLE
[FluxNews] How to run the project xcode

### ISSUE THREAD

**Issue by haidarsalim** [inspireui/support#2803]
I need a video on how to deal with the project, if any
Or the way to solve this error
![‏لقطة الشاشة ٢٠٢٠-٠٤-٢٠ في ٢ ٢١ ٣٢ ص](https://user-images.githubusercontent.com/54249914/79736994-56a4c180-8303-11ea-8870-33e4f71bbdce.png)
--
![33](https://user-images.githubusercontent.com/54249914/79737069-70de9f80-8303-11ea-8055-7d2e5cc19d2a.JPG)

**Comment by minhcasi** [comment]
1. try to run 'flutter clean' and reinstall via Android Studio

You can try to use some solution https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

2. We will check this issue on Fluxbuilder - please share to this repo - https://github.com/inspireui/fluxbuilder/issues

**Comment by haidarsalim** [comment]
I need an Xcode to create iPhone applications

**Comment by minhcasi** [comment]
Yes, @haidarsalim - you need XCode to release ios app - thank you!
