### ISSUE TITLE
[FluxListing]Listing detail is not same between app and web and other questions

### ISSUE THREAD

**Issue by CreatorKim** [inspireui/support#2805]
Hi, Listing detail is not same between app and web.
My theme is MyListing.
I have some questions.

-----------------------------------------<1>------------------------------------------
How can I add the field more in app?
In app, there is no location map field, WP editor contents field.

App
<img width="510" alt="스크린샷 2020-04-20 오후 9 27 59" src="https://user-images.githubusercontent.com/23479206/79751851-41a15000-834e-11ea-8e21-112835b9f1f3.png">

Web
<img width="1307" alt="스크린샷 2020-04-20 오후 9 29 46" src="https://user-images.githubusercontent.com/23479206/79751868-49f98b00-834e-11ea-8393-af3a18729efe.png">

The page is https://gunmastyle.com/listing/커피/

How can I make same?

-----------------------------------------<2>------------------------------------------
Can I use location-based search like MyListing theme in app?

<img width="266" alt="스크린샷 2020-04-20 오후 9 43 56" src="https://user-images.githubusercontent.com/23479206/79752951-10298400-8350-11ea-8e8c-2c70db97bc24.png">

Is it possible?

-----------------------------------------<3>------------------------------------------

<img width="458" alt="스크린샷 2020-04-20 오후 9 54 54" src="https://user-images.githubusercontent.com/23479206/79753881-9db9a380-8351-11ea-8a26-36c5375393d6.png">

There is no image in app listings unlike WP web.
Website : "gunmastyle.com"
How can I add image of each listings?

-----------------------------------------<4>------------------------------------------

<img width="511" alt="스크린샷 2020-04-20 오후 11 10 05" src="https://user-images.githubusercontent.com/23479206/79765632-d06b9800-8361-11ea-9f93-24d053bcc572.png">

I want to change other language the text "products".
But I can't find this.
Where can I find this text?

-----------------------------------------<5>------------------------------------------

<img width="526" alt="스크린샷 2020-04-20 오후 11 49 20" src="https://user-images.githubusercontent.com/23479206/79765654-d9f50000-8361-11ea-892f-9730af38fcbd.png">

<img width="538" alt="스크린샷 2020-04-20 오후 11 49 43" src="https://user-images.githubusercontent.com/23479206/79765680-e416fe80-8361-11ea-8338-d744eac76ca7.png">

I want to change other language the text "Search".
But I can't find this.
Where can I find this text?
-----------------------------------------<6>------------------------------------------
<img width="536" alt="스크린샷 2020-04-21 오전 12 14 38" src="https://user-images.githubusercontent.com/23479206/79768446-c481d500-8365-11ea-9b34-151c6f5165f9.png">

I want to change other language the text "$".
But I can't find this.
Where can I find this text?

-----------------------------------------<7>------------------------------------------
<img width="527" alt="스크린샷 2020-04-21 오전 12 20 01 1" src="https://user-images.githubusercontent.com/23479206/79769021-8e912080-8366-11ea-8305-af1eef42241a.png">
<img width="530" alt="스크린샷 2020-04-21 오전 12 22 06 1" src="https://user-images.githubusercontent.com/23479206/79769039-93ee6b00-8366-11ea-86e0-bb9159dc899b.png">

I want to change other language the text "Refreshing... / Refresh completed" when I click Blog.
But I can't find this.
Where can I find this text?

-----------------------------------------<8>------------------------------------------

<img width="534" alt="스크린샷 2020-04-21 오전 12 42 36" src="https://user-images.githubusercontent.com/23479206/79770938-06f8e100-8369-11ea-8b9c-3f0e6b78c1c1.png">

My listings has location in WP MyListing theme, but there is no marker in google-map in app.
How can I solve this problem?

-----------------------------------------<9>------------------------------------------

<img width="539" alt="스크린샷 2020-04-21 오전 9 10 37" src="https://user-images.githubusercontent.com/23479206/79811193-12bbc600-83b0-11ea-84da-ce61c0df8293.png">

How can I add this image?

----------------------------------------------------------------------------------------
Would you please help me?
Best regards!

**Comment by CreatorKim** [comment]
How can I added the field more in app?

Would you help me?

Best regards!

**Comment by philipvu30** [comment]
Hi,

Please install plugin Better Featured Image in order to show the listing images.
All the text change issues will be updated in the next release.
To show the map, in your config.dart please change this term: 
"lng": "listing_data.geolocation_lng" ->  "lng": "listing_data.geolocation_long"

Thanks

**Comment by CreatorKim** [comment]
Hi,

I've already installed plugin Better Featured Image.
But there is no image.

<img width="1591" alt="스크린샷 2020-04-21 오후 6 44 41" src="https://user-images.githubusercontent.com/23479206/79851488-563e2080-8400-11ea-965d-245e900979ef.png">


What's wrong with my app?

**Comment by philipvu30** [comment]
Hi,

Please create a support account for your site and send it to this email: toan@inspireui.com

I need to check what is wrong with your site because I don't see any image show up on the Rest API.

You can delete it later.

Thanks

**Comment by CreatorKim** [comment]
Thanks for help.

I sent you the mail about my site and admin ID/PW.

**Comment by philipvu30** [comment]
Hi,

You haven't set featured image for your listing.
![image](https://user-images.githubusercontent.com/54442328/79854702-0e190100-83f4-11ea-9a2f-a7d8a4781e76.png)

and your listing doesn't have image gallery. Please add image to this section also
![image](https://user-images.githubusercontent.com/54442328/79856491-a1ebcc80-83f6-11ea-8668-733d693dfa3f.png)

Thanks

**Comment by CreatorKim** [comment]
Thanks. The problem of loading image is solved. Thanks a lot!

I still have 2 Questions.

-----------------------------------------------------------------------------------------------
1.
Change Text.
Question 4~7 is about changing the text.
How can I do it?

-----------------------------------------------------------------------------------------------
2.
Map
After editing "lng": "listing_data.geolocation_lng" -> "lng": "listing_data.geolocation_long", the map appears in listing detail. Thanks a lot.
But the markers don't appear here.

-----------------------------------------------------------------------------------------------


Would you help me?
Best regards!

**Comment by philipvu30** [comment]
Hi,

All of your issues above will be fixed in the next update except the "nearby" function.
We have not supported this feature yet. But it will be implemented in the future due to receiving many requests about it.

**Comment by CreatorKim** [comment]
Thanks, Philip

Can I know when the date of update is?

**Comment by philipvu30** [comment]
Hi,

Currently we don't have a specific date for the official release. But you can submit to access the listing repository via this [form](http://private.inspireui.com/). 

You can get our latest version as we are planning on updating the app every 2-3 weeks.

Thanks.
