### ISSUE TITLE
Deep Link Not Working

### ISSUE THREAD

**Issue by emresutuna** [inspireui/support#2806]
Step 1 (require): detail issues and screenshots

I tried deeplink in my app but isn't working.

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

*Note: please help to fill the required information from the above 2 steps, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhcasi** [comment]
@emresutuna - pls double-check this detailed document config - https://pub.dev/packages/uni_links
