### ISSUE TITLE
FluxStore PRO - Opencart + multiple issues.

### ISSUE THREAD

**Issue by harrisbaitalrayan** [inspireui/support#2807]
Step 1 (require): detail issues and screenshots

Connecting to openCart.
Hi dear, These are the issues which is really causing troubles for me:

1) No product options appearing in product
2) Discount price is not shown
3) Cart error when reopen the application
4) Filter by price range not working
I understand a new release is coming, could you tell me the date it will be released.
I took the latest master branch from gitlab but still the above errors is not solved.

Please require your assistance .

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com
*Note: please help to fill the required information from the above 2 steps, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhtruong315** [comment]
@harrisbaitalrayan can u send me admin to login to your website via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/2807

**Comment by harrisbaitalrayan** [comment]
OK Thank you, I will send .

**Comment by minhtruong315** [comment]
I dont see your email

**Comment by harrisbaitalrayan** [comment]
Will send it tomorrow. Taking a backup of the site before sending you access.

**Comment by harrisbaitalrayan** [comment]
I have sent you the email.

**Comment by harrisbaitalrayan** [comment]
Hi dear, any updates ?

**Comment by harrisbaitalrayan** [comment]
@minhtruong315

**Comment by minhtruong315** [comment]
@harrisbaitalrayan we fixed 1,2,3 in version 1.6.7. it will release soon. I will check issue 4

**Comment by harrisbaitalrayan** [comment]
@minhtruong315 Thank you dear. Eagerly awaiting for the new release.

**Comment by minhtruong315** [comment]
@harrisbaitalrayan pls update Fluxstore 1.6.7 and test again
