### ISSUE TITLE
[CeBuilder] Can't see all Categories and Tags in Dropdown list

### ISSUE THREAD

**Issue by winechit1989** [inspireui/support#281]
**Required Info (please complete the following information):**
 - Product: [e.g. MStore, ListApp]
 - Your Purchased Code: [get from https://codecanyon.net/downloads]
(we may not reply if you are not our customer)

**Describe the bug**
Can't see all Categories and Tags in Dropdown list in CeBuilder

**Screenshots**
[
<img width="493" alt="screen shot 2019-02-11 at 12 56 37" src="https://user-images.githubusercontent.com/6885184/52548613-1e4f4c80-2dfd-11e9-9c82-e45f96a860f7.png">
](url)

**Additional context**
I can add my website and all required tools in cebuilder well.
But I didn't see all categories in dropdown box.

**Comment by minhcasi** [comment]
noted for checking the limit from the categories view.

@winechit1989 - could you let us know which the product that you are using?

**Comment by winechit1989** [comment]
BeoNews Pro - React Native mobile app for Wordpress

**Comment by minhtruong315** [comment]
I will fix this issue for next update CeBuilder.
Thanks

**Comment by winechit1989** [comment]
The another question is that how can i change App name from BeoFoods.

**Comment by winechit1989** [comment]
When will release the update? I am waiting for it.

**Comment by minhcasi** [comment]
Hi, we will fix this issue and rebuild the CeBuilder on Monday - in the meantime, you can edit the appConfg.json to change the category and pick up the ID manually from your wordpress side 

To change the app name you can follow this guide - https://beonews.inspireui.com/advance-customize/app-delivery
