### ISSUE TITLE
No named parameter with the name 'animation' with Beta channel

### ISSUE THREAD

**Issue by ykdeshmukh** [inspireui/support#2810]
I am unable make a build with fluxstore, this happens frequently, sometime it works and sometime it does not.. i am not technical person.. so can you please give me step by step procedure to resolve this issue.

C:\flutter\flutter\bin\flutter.bat --no-color build apk
Running "flutter pub get" in toynbook...                            2.8s
You are building a fat APK that includes binaries for android-arm, android-arm64, android-x64.
If you are deploying the app to the Play Store, it's recommended to use app bundles or split the APK to reduce the APK size.
    To generate an app bundle, run:
        flutter build appbundle --target-platform android-arm,android-arm64,android-x64
        Learn more on: https://developer.android.com/guide/app-bundle
    To split the APKs per ABI, run:
        flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
        Learn more on:  https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split
Running Gradle task 'assembleRelease'...                        

Compiler message:

/C:/Users/DELL/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/extended_image-0.7.2/lib/src/gesture/extended_image_slide_page_route.dart:333:9: Error: No named parameter with the name 'animation'.

        animation: animation,

        ^^^^^^^^^

../../../flutter/packages/flutter/lib/src/cupertino/route.dart:435:3: Context: Found this candidate, but the arguments don't match.

  CupertinoFullscreenDialogTransition({

  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Target kernel_snapshot failed: Exception: Errors during snapshot creation: null

build failed.

FAILURE: Build failed with an exception.

* Where:

Script 'C:\flutter\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 882

* What went wrong:

Execution failed for task ':app:compileFlutterBuildRelease'.

> Process 'command 'C:\flutter\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:

Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 59s
Running Gradle task 'assembleRelease'...                           61.1s
Gradle task assembleRelease failed with exit code 1
Process finished with exit code 1

**Comment by minhcasi** [comment]
@ykdeshmukh pls try to use the Flutter Stable Channel, instead of using master 

Try this script will fix the issue
```
flutter channel stable
flutter upgrade --force
```

**Comment by ykdeshmukh** [comment]
Done... But App is crashing... It installs and then nothing happened.

I already requested... Proper procedure
Where to run that script..   I ran it in terminal.

Check my config.zip.. Tell me where exactly the issue lies

**Comment by minhcasi** [comment]
@ykdeshmukh - thank you for the quick response - the root cause is  caused by incompatible of some library on latest flutter channel or the beta one - we suggest to use the stable channel to keep it work well

Please help to clean up the cache after update the flutter channel - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

We will upload new release Fluxstore Shopify today 

Very best!

**Comment by ykdeshmukh** [comment]
What do you mean?
Are you in support process.. Seriously.
See I don't want refund for this, I want resolution. I hope.. U
understood... Giving last chance to u... Explain urself

**Comment by minhcasi** [comment]
resolution from my previous comment: the issue is from flutter library - try to use flutter channel stable

I've run your common file and it working fine - https://tppr.me/AQCJK
(make sure to run the project from Android Studio to check if there is any Dart Analysis issues)

There could be a problem from your new file "Firebase Remote Config.dart"

**Comment by minhcasi** [comment]
@ykdeshmukh could i check if you could run the project so far?

**Comment by ykdeshmukh** [comment]
It's done...  Issues resolved... Thanks for the help.. I am new to
flutter..  So if needed will mail... The only thing I want to know is... If
I have purchased fluxstore for woo then can I use it for only web
integration for word press...  So I will get enough time to make the app
perfect..  And meanwhile I can go live with web integration...
Thanks in advance..!!

**Comment by ykdeshmukh** [comment]
Help me with splashscreen.flr, I want my logo there with that animation...
I don't wanna use png... So how to do that?

**Comment by Alababdiy** [comment]
@ykdeshmukh How did you find a solution?

**Comment by minhcasi** [comment]
@ykdeshmukh - yes you can use with the Web version by enabling Flutter channel beta

please check this guide to know your to custom the flare animate file - https://docs.inspireui.com/fluxstore/customization/#2-logo-splash-screen

**Comment by arjuntu1990** [comment]
@ykdeshmukh  i am also getting this error, could yoy pls help. How did you fix this issue?

**Comment by minhcasi** [comment]
@arjuntu1990 - you could download the latest version was fixed this issue, make sure to update to latest Flutter 1.17 - thank you!

**Comment by cdalsoniii** [comment]
What specific version of the beta channel do you support? These are what is available:

1.17.0-3.4.pre 1.17.0-3.3.pre 1.18.0-8.0.pre 1.18.0-7.0.pre 1.17.0-3.2.pre 1.18.0-6.0.pre 1.18.0-dev.5.0 1.18.0-dev.4.0 1.18.0-dev.3.0 1.17.0-dev.3.1 1.18.0-dev.2.0 1.18.0-dev.1.0 1.18.0-dev.0.0 1.17.0-dev.5.0 1.17.0-dev.4.0 1.17.0-dev.3.0 1.17.0-dev.2.0 1.17.0-dev.1.0 1.17.0-dev.0.0

**Comment by aravindmedamoni** [comment]
> @arjuntu1990 - you could download the latest version was fixed this issue, make sure to update to latest Flutter 1.17 - thank you!

i got this issue in new version only

**Comment by arjuntu1990** [comment]
the issue is not found in the version fluxstore 1.7.3
Thank you so much for the support
