### ISSUE TITLE
Error In NoSuchMethodError. The getter ‘salePrice’ was called on null

### ISSUE THREAD

**Issue by mastermined** [inspireui/support#2811]
Step 1 (require): detail issues and screenshots

Hello Team, I am getting (Error In NoSuchMethodError. The getter ‘salePrice’ was called on null) It only happen when there is any product in cart and app is closed and opened again then this error appear as long as app is running product in cart works fine.

I am using Fluxstore Pro version integrating with woocommerce, update MStoreAPI plugin already to latest version.

![2020-04-21 02 03 44](https://user-images.githubusercontent.com/36563476/79784261-9657c180-8374-11ea-8862-4fc6cb4fbb9e.jpg)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

*Note: please help to fill the required information from the above 2 steps, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhcasi** [comment]
@mastermined - please help to check the solution in https://github.com/inspireui/support/issues/2615 - we are going to update latest version in 1-2 days - thanks
