### ISSUE TITLE
Fluxstore Woocommerce - How To Set Minimum & Max Order Amount in the App ? 

### ISSUE THREAD

**Issue by swspro** [inspireui/support#2812]
Hi,

In the **Woocommerce WordPress** website we are using a **plugin** to set **minimum order amount** to place the order ; below which the order is not accepted and shows an **alert message** on the **checkout page.**

But in the **Fluxstore App** the order is placed **below** the **Minimum Amount** . Also it doesn't shows any alert message.

Can you please assist how to set the Minimum order amount ? 

Where to make the changes and what's the code .

All your help will be highly appreciated 🙏

Regards,
**Samaresh B.**

**Comment by minhcasi** [comment]
@swspro - please help to move this conversation to the same ticket #2785 - thank you!
