### ISSUE TITLE
purchase code 

### ISSUE THREAD

**Issue by robertoraposo** [inspireui/support#2813]
Hello my evanto user is: robertoraposo and my purchase code is: 8f9dda1c-62c2-4ca7-a510-6e0b586820db.

by mistake I activated my purchase code first in the MStore API in wordpress and now when I try to validate it in FluxBuilder it says that it is already in use on my website, I need a clearer guide of the steps to follow.

thanks

**Comment by minhcasi** [comment]
@robertoraposo - we have reset your license :)
