### ISSUE TITLE
Order Not Processing Keeps Loading

### ISSUE THREAD

**Issue by bilalmunir1995** [inspireui/support#2815]
Hi So in fluxstore shopify i completed the connection to my store and all the items and categories are showing but the order is not going through after everything it's. stuck on the loading screen
<img width="891" alt="Screenshot 2020-04-21 at 6 10 40 AM" src="https://user-images.githubusercontent.com/37571277/79814466-b8af0680-8397-11ea-971f-9feeef5193ba.png">

<img width="440" alt="Screenshot 2020-04-21 at 6 10 34 AM" src="https://user-images.githubusercontent.com/37571277/79814330-6a9a0300-8397-11ea-8dcb-8eaa72ed579c.png">
<img width="1127" alt="Screenshot 2020-04-21 at 6 16 14 AM" src="https://user-images.githubusercontent.com/37571277/79814430-a3d27300-8397-11ea-901f-c150d96979a4.png">

**Comment by minhcasi** [comment]
pls help to raise your all issues to one ticket #2817 - thank you!
