### ISSUE TITLE
[Fluxstore Shopify] When You are at the review screen and you change the quantity the price remains same

### ISSUE THREAD

**Issue by bilalmunir1995** [inspireui/support#2817]
In the order review page changing quantity does not change the total amount
<img width="1127" alt="Screenshot 2020-04-21 at 6 16 14 AM" src="https://user-images.githubusercontent.com/37571277/79814581-104d7200-8398-11ea-99f4-ca011bacbeb5.png">
<img width="454" alt="Screenshot 2020-04-21 at 6 18 45 AM" src="https://user-images.githubusercontent.com/37571277/79814587-14798f80-8398-11ea-8c3d-194640a9d933.png">
<img width="465" alt="Screenshot 2020-04-21 at 6 18 54 AM" src="https://user-images.githubusercontent.com/37571277/79814590-15aabc80-8398-11ea-84c7-1d4da0a22174.png">

**Comment by bilalmunir1995** [comment]
Still Waiting for your reply also darkmode is not working
When Order is finalised it is stuck at loading
<img width="440" alt="Screenshot 2020-04-21 at 6 10 34 AM" src="https://user-images.githubusercontent.com/37571277/80024866-2292f180-84f9-11ea-98b7-04df71e28bcc.png">
<img width="475" alt="Screenshot 2020-04-21 at 6 23 31 AM" src="https://user-images.githubusercontent.com/37571277/80024878-26267880-84f9-11ea-8ffa-2279a6f99196.png">
<img width="479" alt="Screenshot 2020-04-21 at 6 23 40 AM" src="https://user-images.githubusercontent.com/37571277/80024884-27f03c00-84f9-11ea-9271-20a3e8a8eb38.png">

**Comment by minhcasi** [comment]
confirm the dark mode is fixed on the latest code - we will upload a new build today - thank you!

**Comment by bilalmunir1995** [comment]
ok and the rest of the problems ?

**Comment by minhcasi** [comment]
@bilalmunir1995 - could you help to download the latest 1.6.7 stable version - thank you!
