### ISSUE TITLE
Dark Theme Button Does Nothing in fluxstore shopify 

### ISSUE THREAD

**Issue by bilalmunir1995** [inspireui/support#2818]
So the darktheme button is doing nothing and i have tried it on multiple devices. Also clicking dark theme button creates error.
<img width="1127" alt="Screenshot 2020-04-21 at 6 16 14 AM" src="https://user-images.githubusercontent.com/37571277/79814914-db8dea80-8398-11ea-9bf6-76938445a0a0.png">
![Uploading Screenshot 2020-04-21 at 6.23.31 AM.png…]()

**Comment by bilalmunir1995** [comment]
<img width="475" alt="Screenshot 2020-04-21 at 6 23 31 AM" src="https://user-images.githubusercontent.com/37571277/79814964-f3fe0500-8398-11ea-9fdb-a1dc25d3a0a1.png">
<img width="479" alt="Screenshot 2020-04-21 at 6 23 40 AM" src="https://user-images.githubusercontent.com/37571277/79814970-f8c2b900-8398-11ea-837b-d1bfc8b6bb13.png">
<img width="1228" alt="Screenshot 2020-04-21 at 6 24 40 AM" src="https://user-images.githubusercontent.com/37571277/79814971-f95b4f80-8398-11ea-8d88-aac44972a5bf.png">

**Comment by minhcasi** [comment]
pls help to raise your all issues to one ticket #2817 - thank you!
