### ISSUE TITLE
[FLUXSTORE MV] Google Sign In Error - Shader Compilation Error

### ISSUE THREAD

**Issue by antixirus** [inspireui/support#2819]
Step 1 (require): detail issues and screenshots
![gambar](https://user-images.githubusercontent.com/57300649/79850481-37369300-83ee-11ea-857b-b8feb488894d.png)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

*Note: please help to fill the required information from the above 2 steps, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by trunghieuvn** [comment]
hi @antixirus , 
You can try on many devices to check this. I have tried running your source code, but I have no errors like this. You can shoot me a video of the steps that make up this error so I can check it out.

**Comment by antixirus** [comment]
@trunghieuvn Do you have Skype sir? I will contact you from Skype sir...

**Comment by minhcasi** [comment]
@antixirus - pls help to double-check this guide as we could not reproduce this bug - https://docs.inspireui.com/fluxstore/sign-in/ - pls also try the latest version 1.6.7 - thank you!
