### ISSUE TITLE
Fluxstore Store page is showing blank

### ISSUE THREAD

**Issue by webofficial** [inspireui/support#2820]
Step 1 (require): detail issues and screenshots
As per the document instruction i have done all to connect the wordpress website to fluxstore app version 1.6.4

But store page showing blank also the about page showing the inspireui details.Here i am attaching the purchase proof as well the screenshot of store page.

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

*Note: please help to fill the required information from the above 2 steps, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhcasi** [comment]
@webofficial - please help to prove purchase code to http://private.inspireui.com/ - please don't share the public purchase code public here as another one could use it for activation - thank you!

**Comment by webofficial** [comment]
Hello Sir,

This is the first time i am raising one ticket so its happened i am sorry
for that.As you said i have given the proof yesterday itself on
http://private.inspireui.com/ this link.
Below find the attached screenshot of that.

Please do reply me if anything else is required from my side.

I hope soon i will get some solution for my issue.

Thanks and Regards
Subair ms

**Comment by minhcasi** [comment]
@webofficial - sorry we got your detail info already 👍

@minhtruong315 - pls help to investigate this issue

**Comment by minhtruong315** [comment]
@webofficial are you using Fluxstore version 1.6.4?

**Comment by webofficial** [comment]
Hello Sir,

Sorry for the late reply.Yes i am using fluxstore version 1.6.4.

Thanks & Regards
Subair Ms

**Comment by minhtruong315** [comment]
it's so old. please update Fluxstore 1.6.6 for now. We will release version 1.6.7 tomorrow.

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
