### ISSUE TITLE
FluxStore Full App :  Cart issues NoSuchMethodError

### ISSUE THREAD

**Issue by EhapAlazerk11** [inspireui/support#2821]
First : i get error NoSuchMethodError the getter salePrice was called on null error 
and the qaunatitey in cart is two item 
here the screen shot for error : https://ibb.co/Pw04ZL7

Step 2 (require): this is the screen shot 👍 https://ibb.co/fD9wQ6s

**Comment by minhcasi** [comment]
@EhapAlazerk11 please help us to provide more info to http://private.inspireui.com/

The latest source on github is fixed this issue - v1.6.7 (we will also release this version on this week), please process the request to access Gitlab on this link https://docs.google.com/forms/d/e/1FAIpQLSeuBqUkScy42V7KKhfNPj0fl581anrB1mWkbMa3p2WQt7fhfw/viewform
