### ISSUE TITLE
BeoNews - User Registration

### ISSUE THREAD

**Issue by shanenorman** [inspireui/support#2822]
Please see previous issue for purchase substantiation: 

User registration via Wordpress and Facebook does not work. In addition, logging into a page via web view (left menu) is disabled by window blocking:
![IMG_0388](https://user-images.githubusercontent.com/11539085/79858233-f1dd7b80-8383-11ea-9334-4a9e77fece20.PNG)
![IMG_0389](https://user-images.githubusercontent.com/11539085/79858238-f3a73f00-8383-11ea-894e-7cf73429e9a1.PNG)
![IMG_0390](https://user-images.githubusercontent.com/11539085/79858240-f43fd580-8383-11ea-8023-adbfb4abba1b.PNG)

**Comment by minhcasi** [comment]
@shanenorman - pls move this issue to the same of your ticket #2650 - thanks
