### ISSUE TITLE
webview checkout and missing config files

### ISSUE THREAD

**Issue by rfmer** [inspireui/support#2823]
Hello
on codecanyon i get told that i can set full webview checkout 
how to do that ?
i am using wcfm and when i copy the config there files missing 

`export 'config/advance.dart';
export 'config/advertise.dart';
export 'config/basic.dart';
export 'config/languages.dart';
export 'config/onboarding.dart';
export 'config/payments.dart';
export 'config/products.dart';
export 'config/smartchat.dart';
`

advance.dart
basic.dart
thanks

**Comment by minhcasi** [comment]
@rfmer - please help us to provide more info to this form http://private.inspireui.com/ and reopen the ticket - thanks

**Comment by rfmer** [comment]
the link is not working and i already provided proof that i bought the code
the issue is that i have been told that fluxstore multi vendor support webview checkout and it does not
EnableOnePageCheckout is not available on fluxstore multi vendor code 
please help

**Comment by rfmer** [comment]
@minhcasi done open please
