### ISSUE TITLE
Problem 

### ISSUE THREAD

**Issue by Roupasafricanas** [inspireui/support#2824]
Step 1 (require): detail issues and screenshots

Hello. This is my problem. It appears when I add to the card 
![Screenshot_2020-04-21-08-55-51-339_com inspireui fluxstore](https://user-images.githubusercontent.com/63840938/79863562-56adcb80-83ae-11ea-83e7-616dd2d3dd58.jpg)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

*Note: please help to fill the required information from the above 2 steps, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhcasi** [comment]
@Roupasafricanas - pls share the common and config folder so that we could help for checking

**Comment by minhcasi** [comment]
@Roupasafricanas - noted with checking, we got your detail info

**Comment by minhcasi** [comment]
@Roupasafricanas - could you help to check the latest build 1.6.7 on Gitlab? The team notice to fix this issue - thank you!

**Comment by Roupasafricanas** [comment]
For sure. But I don't know how to do it. What is the link that I should access please?

**Comment by Roupasafricanas** [comment]
Hi minhcasi. I tested the 1.6.7 and the same thing happened

**Comment by Roupasafricanas** [comment]
![Screenshot_2020-04-23-15-06-52-983_com inspireui fluxstore](https://user-images.githubusercontent.com/63840938/80134312-f6b55180-8574-11ea-8b6b-66716a9097f7.jpg)

**Comment by Roupasafricanas** [comment]
Just another feedback. This erro have been solved in 1.6.7
![problem-3](https://user-images.githubusercontent.com/63840938/80169060-d314fa00-85ba-11ea-83c4-a6deebee84c9.jpg)

But the first no

**Comment by minhcasi** [comment]
@Roupasafricanas - thank you for quick response 

@trunghieuvn - please help for investigating the first issue

**Comment by Roupasafricanas** [comment]
Hello, I am also encountering 3 problems that prevent me from finalizing the installation of my application
1- the blog does not appear despite the fact that I inserted the URL
![IMG_20200424_024143](https://user-images.githubusercontent.com/63840938/80182437-47f92b80-85dd-11ea-8e3c-4573b906bac4.jpg)

2- I installed aftership but it still shows 0 when calculating
![Screenshot_2020-04-24-02-43-37-613_com inspireui fluxstore](https://user-images.githubusercontent.com/63840938/80182516-77a83380-85dd-11ea-9bdf-74b2ab10995b.jpg)

3- At the time of the finisher, payment via the web is directed to an inexisting page. You can search for the top partition to see what's going on..
![Screenshot_2020-04-24-03-45-13-522_com inspireui fluxstore](https://user-images.githubusercontent.com/63840938/80182794-12087700-85de-11ea-9d99-4be32845c325.jpg)

**Comment by minhcasi** [comment]
@trunghieuvn

**Comment by minhcasi** [comment]
@Roupasafricanas - pls use the latest v1.7.0 - we have fix this issue - let us know your checking

**Comment by Roupasafricanas** [comment]
Hello. All problems have been solved except that of the blog. He's not showing up yet. The rest has already been fixed

**Comment by minhcasi** [comment]
@Roupasafricanas - pls try to install this plugin to see if you could fix the blog issue- https://wordpress.org/plugins/better-rest-api-featured-images/

Also, try to run the Regenerate image from the document, we also note some guide here - https://docs.inspireui.com/fluxstore/useful-tip/  thanks
