### ISSUE TITLE
Products categories etc are not showing 

### ISSUE THREAD

**Issue by UmaiZ** [inspireui/support#2825]
After replacing my URL and keys. Products are not showing in the app also categories etc are not showing in the console also. 
Already send config file etc in the google form.

**Comment by minhcasi** [comment]
@UmaiZ - sorry we could not get the detail via http://private.inspireui.com - please help us to submit again

Also share your common / config so that we could help for checking, you could use the fluxbuilder to support for this setting http://fluxbuilder.com/

**Comment by UmaiZ** [comment]
Fill and send the form again. Also, i share common folder please check. I have tested my keys and URL its fine because i have tested these keys on other theme and its working there. But dont know why its not working here.

**Comment by UmaiZ** [comment]
Can anyone please check issue ? waiting from 2 days please

**Comment by minhcasi** [comment]
@UmaiZ - thank you we got the form, it is sent via 2816 but we have verified by this ticket id 2825  👍

There is the issue with your consume keys that not correctly so that the app could not open the connection - https://tppr.me/6SiW9

You could also try to check the connection by using Fluxbuilder app - http://fluxbuilder.com/

**Comment by UmaiZ** [comment]
But keys are working perfectly in other mobile app. Or ill create new keys ?

**Comment by UmaiZ** [comment]
I have changed my keys but products are not showing. And dont no why these products are showing i change the URLs also 
![asda](https://user-images.githubusercontent.com/31176904/80165764-a16d5480-85f5-11ea-8ed4-27450f154047.png)

**Comment by UmaiZ** [comment]
Can you check in panel please ? Because i have try everything from docs and its not working and the keys are working but dont know in this app and fluxbuilder its saying not working ? any version issue or something ?

**Comment by minhcasi** [comment]
@UmaiZ - could you help to test the key via PostMan tool by using this guide - https://github.com/woocommerce/woocommerce/wiki/Getting-started-with-the-REST-API ?

**Comment by UmaiZ** [comment]
Try, showing same error as you show before  `"message": "Sorry, you cannot list resources.", `
Can you check my panel if ill send you credentials ? Its very strange because my keys are already working in one app dont know whats the problem here.

**Comment by UmaiZ** [comment]
Finally product showing issue resolved try with different store its working on that but now other issue login and register is not working. Already enable the tick register all users 

New config is this 
```
const serverConfig = {
  "type": "woo",
  "url": "https://manyshopbd.com/",
  "consumerKey": "ck_f2512104e131f91a23e8bd16128306bd2e2387ec",
  "consumerSecret": "cs_3e49cacacb720c5634ebe148440c2306476c1d1a",
  "forgetPassword": "http://demo.mstore.io/wp-login.php?action=lostpassword"
};

```

**Comment by UmaiZ** [comment]
Please tell how i can this logi/register with email issue

**Comment by minhcasi** [comment]
@UmaiZ - could I check if you have active the mstore-api as the document guide ?

**Comment by Zeehshan** [comment]
> store

http://portadiroma.ly/wp-json/wc/v2/products/categories?exclude=311&lang=en&oauth_consumer_key=ck_dbfa527419b8eddacf86ba0504558dbcbe7c6918&oauth_nonce=sxkoamzchj&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1589931196&oauth_token=&oauth_version=1.0&page=1&per_page=100&oauth_signature=y1LtasbZhnEf43G3o2V%2FN%2F1C8R0%3D
hello sir i hope you will find please let me know how you solved this issue becasue i am also facing same issue
