### ISSUE TITLE
App main page doesn't load before touching on screen

### ISSUE THREAD

**Issue by ykarapanca** [inspireui/support#2826]
Step 1 (require): detail issues and screenshots
App doesn't load before touching on screen or clicking another section and coming back to main page. After going to categories and product page, it loads there and when going back to main screen it's loaded. I need it to be loaded before touching anything or going another section. 

It stays forever like this if i dont't touch anything:
![Screenshot_20200421-155013](https://user-images.githubusercontent.com/58140554/79868331-6d711400-83e8-11ea-9998-c900f3b42833.jpg)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

I have uploaded files to the private.inspireui.com

**Comment by ykarapanca** [comment]
@minhcasi hi there. Please help me out with this one. It's really urgent. Thank you.

**Comment by minhcasi** [comment]
@ykarapanca - we could not reproduce this issue - could I know if there is a customize source that you have made that could cause the impact? Could you help to quick share the video screenshot please

**Comment by ykarapanca** [comment]
Hi @minhcasi % @trunghieuvn 
You can watch the screen recording under my drive folder in the link below:
https://drive.google.com/open?id=16akUct5MqZag3RzaeyGik6l-ohkgP3rk

As i mention at the video, i only put add to cart icon to the bottom right for the products as you have supported me. It was something like changing  ShowCardList and a value in it like "showcart: true,"

Also i have removed top slider from theme sample number 7 and configured it as my config_tr.json
However this problem were existing before these changes. 

I ve uploaded my config json file to my woocommerce site a couple times. I update plugins regularly. I have set iscaching to true. 

I was using a shared hosting, only for this problem, i have created a google intstance just to keep this wordpress site alone and keep it fast. 

You are the only hope now:) Please help me out with this. Thank you!

**Comment by ykarapanca** [comment]
If you like, i can provide all source code of mine. Thanks

**Comment by trunghieuvn** [comment]
Hi @ykarapanca 
Please send me all the files in the common folder (lib/common) and the config folder (lib / config). Currently you only send the config folder in common (lib/common/config), this makes it difficult for me to reproduce the error to find out the cause.

Compress all of them into zip files and send here: http://verify.inspireui.com/ for me. I will handle this issue quickly. Thanks.

**Comment by ykarapanca** [comment]
Hi @trunghieuvn 
I have submitted the folders you have requested. Waiting for feedback. 
Thank you.

**Comment by ykarapanca** [comment]
🖖🖖 @trunghieuvn

**Comment by ykarapanca** [comment]
Hi guys, @minhcasi @trunghieuvn ,
I don't want be seem antipathic by asking regularly but it's a bit urgent:) Could you manage to investigate my issue? It ll be great if you update me. Thank you!

**Comment by minhcasi** [comment]
@trunghieuvn - please help to prioritize the ticket - thanks

**Comment by ykarapanca** [comment]
Hi there @trunghieuvn , i see there is a new update. Should i update the app to solve the issue or wait for your answer?

**Comment by minhcasi** [comment]
@ykarapanca - we confirm to fix it on latest 1.7.0 - please help to download the latest version

**Comment by ykarapanca** [comment]
Hi @minhcasi , the loading issue is resolved by updating. 
However another problem came up, which is Buy Now and Add to Cart Buttons are not working.
You can see the screen recording video on via the link below. You have any idea about this?
Screen record video link:
https://drive.google.com/open?id=17b1FNKm-_CzUzCLA2cjq0NjQE850ldBm

Thank you.

**Comment by minhcasi** [comment]
@ykarapanca - i got the problem - could you try to replace widgets/frameworks/product_variant_mixin.dart to fix Buy button
[product_variant_mixin.dart.zip](https://github.com/inspireui/support/files/4549995/product_variant_mixin.dart.zip)

We will upload new patching soon - thanks

**Comment by ykarapanca** [comment]
Hi @minhcasi - it worked great! thank you for all support.
