### ISSUE TITLE
mstore-api issue

### ISSUE THREAD

**Issue by CodingFectum** [inspireui/support#2827]
Step 1 (require): detail issues and screenshots

Move from the title:
Unable activate plugin "Mstore API". I'm receiving this error Fatal error: Cannot declare class MstoreCheckOut, because the name is already in use in /home/mizakkac/public_html/wp-content/plugins/mstore-api/mstore-api.php on line 24

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

*Note: please help to fill the required information from the above 2 steps, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhcasi** [comment]
@CodingFectum - please help to provide more detail info to http://private.inspireui.com/ - thank you!
