### ISSUE TITLE
FluxStore Shopify installation issue

### ISSUE THREAD

**Issue by Sophyra-Hou** [inspireui/support#2828]
Step 1 (require): detail issues and screenshots

I have followed this link https://docs.inspireui.com/fluxstore/fluxstore-shopify/ to install fluxStore Shopify but get stuck coz no guideline to use my download package i just bought so no lib/common/config.dart
![Screenshot_3](https://user-images.githubusercontent.com/63991133/79877338-51846700-8416-11ea-93ee-62cda2a832b0.jpg)
![Screenshot_1](https://user-images.githubusercontent.com/63991133/79877462-74168000-8416-11ea-8f84-0df82b0af116.jpg)
Does anyone know to to install it correctly? coz the document is so messy and seems not completed for installation. i try many times even video from Fluxstore for woocommerce https://docs.inspireui.com/fluxstore/woocommerce-setup/ but it still not working. Maybe because the package i bought is out of date and not compatible with new component that always update in the documents?

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

*Note: please help to fill the required information from the above 2 steps, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhcasi** [comment]
@Sophyra-Hou - could i know if you have followed this video guide https://docs.inspireui.com/fluxstore/fluxstore-shopify/

The docs for fluxstore-shopify is located on this link - https://docs.inspireui.com/fluxstore/fluxstore-shopify/ - thank you!

**Comment by Sophyra-Hou** [comment]
I have followed that link and that videos but can get only demo but not working with example source and cannot link with my website. Do you know anyone can help me to set up? how much to pay? or could i exchange the package to use MStore shopify? I have no knowledge about web developing.
![Screenshot_5](https://user-images.githubusercontent.com/63991133/79940717-b2e71d00-848c-11ea-9420-81e079a0a7c4.jpg)

**Comment by minhcasi** [comment]
@Sophyra-Hou - did you follow this video guide https://www.youtube.com/watch?v=OIpnoThJ2Rs ?

**Comment by minhcasi** [comment]
please also check with the latest 1.6.7 stable version - thank you!

**Comment by Sophyra-Hou** [comment]
Thank you so much, I will try.
