### ISSUE TITLE
Won't run VC Root Mapping

### ISSUE THREAD

**Issue by MathewHogg** [inspireui/support#2829]
I have issue, I have followed guide for Android studio and have also done the pub get for the pubspec file however it still will not run. Screenshot below.

![image](https://user-images.githubusercontent.com/27287016/79893738-6227e380-83fc-11ea-8cf8-5492ba75ea6d.png)

**Comment by MathewHogg** [comment]
`Launching lib\main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Invalid depfile: I:\Downloads\lemonjayappbuild\lemonjay\source\.dart_tool\flutter_build\e9e3a46973e31fc5f21e6cf0d5501198\kernel_snapshot.d
Invalid depfile: I:\Downloads\lemonjayappbuild\lemonjay\source\.dart_tool\flutter_build\e9e3a46973e31fc5f21e6cf0d5501198\kernel_snapshot.d

Compiler message:
Error: Invalid package URI 'package:/common/constants.dart':
  Invalid argument (packageUri): Package URIs must not start with a '/': Instance of '_SimpleUri'.
lib/common/config.dart:2:8: Error: Not found: 'package:/common/constants.dart'
import '../../common/constants.dart';
       ^
lib/common/config.dart:84:25: Error: Getter not found: 'kBlogLayout'.
  "DetailedBlogLayout": kBlogLayout.halfSizeImageType,
                        ^^^^^^^^^^^
lib/common/config.dart:112:13: Error: Getter not found: 'kProductLayout'.
  "layout": kProductLayout.listingSimpleType
            ^^^^^^^^^^^^^^
Unhandled exception:
FileSystemException(uri=org-dartlang-untranslatable-uri:package%3A%2Fcommon%2Fconstants.dart; message=StandardFileSystem only supports file:* and
 data:* URIs
)
#0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:33:7)
#1      asFileUri (package:vm/kernel_front_end.dart:604:37)
<asynchronous suspension>
#2      writeDepfile (package:vm/k
ernel_front_end.dart:799:21)
<asynchronous suspension>
#3      Frontend
Compiler.compile (package:frontend_server/frontend_server.dart:472:15)
<as
ynchronous suspension>
#4      _FlutterFrontendCompiler.compile
 (package:flutter_frontend_server/server.dart:38:22)
#5  
    starter (package:flutter_frontend_server/server.dart:
149:27)
#6      main (file:///C:/b/s/w/ir/cache/builder/src/flutter/flutter_frontend_server/b
in/starter.dart:8:30)
#7      _startIsolate.<anonymous clos
ure> (dart:isolate-patch/isolate_patch.dart:305:32)
#8   
   _RawReceivePortImpl._handleMessage (dart:isolate-pat
ch/isolate_patch.dart:174:12)

Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 780

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\flutter\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s
Finished with error: Gradle task assembleDebug failed with exit code 1`

**Comment by MathewHogg** [comment]
Console output is above.

**Comment by minhcasi** [comment]
@MathewHogg - pls help to provide more info to http://private.inspireui.com/ as we could not verify your purchase - thank you!

**Comment by MathewHogg** [comment]
> @MathewHogg - pls help to provide more info to http://private.inspireui.com/ as we could not verify your purchase - thank you!
> 
> > **[Google Forms - create and analyze surveys, for free.](http://private.inspireui.com/)**Create a new survey on your own or with others at the same time. Choose from a variety of survey types and analyze results in Google Forms. Free from Google.

Provided.
