### ISSUE TITLE
FluxPro Woo - Apple sign in works only on simulator ! -*URGENT* PLZ

### ISSUE THREAD

**Issue by digirizon** [inspireui/support#2831]
![screenshot-codecanyon net-2020 04 (1)](https://user-images.githubusercontent.com/38114490/79903372-9fe83480-841b-11ea-892c-b37194c8c417.png)

I Managed to solve all my previous issues (that's why I closed the last ticket ) and stuck on this issue 

The apple sign-in works on simulator only and when try to sign in using the Real device, this is the output it gives 

```
credential =     {
        authorizationCode = "<FlutterStandardTypedData: 0x280d60a00>";
        authorizedScopes =         (
        );
        email = "<null>";
        fullName =         {
            familyName = "<null>";
            givenName = "<null>";
            middleName = "<null>";
            namePrefix = "<null>";
            nameSuffix = "<null>";
            nickname = "<null>";
        };
        identityToken = "<FlutterStandardTypedData: 0x280d609a0>";
        realUserStatus = 1;
        state = "<null>";
        user = "001150.cfac8f1d5fd04f55a80bebea7b46d82d.1647";
    };
    credentialType = ASAuthorizationAppleIDCredential;
    status = authorized;
}
```
No errors in xcode output 

**it seems that the sign-in is successful because even though it gives this error** 

![apple sign error](https://user-images.githubusercontent.com/38114490/79902480-3ae00f00-841a-11ea-9998-5fb61f74332f.jpeg)

### but it actually registers the user in WordPress users!

**I notice that it says** 

`status = authorized;`  

**but it didn't show the user info** 

```
        email = "<null>";
        fullName =         {
            familyName = "<null>";
            givenName = "<null>";
            middleName = "<null>";
            namePrefix = "<null>";
            nameSuffix = "<null>";
            nickname = "<null>";
```
tried on couple of real devices and uploaded it to Testflight but it still the same 
consulted some Flutter develpers and they says it's a permissions issue 

P.S. I've Uploaded my files to the google form

**Comment by iamar1k92** [comment]
In firebase > Realtime database > Rules > Do read & write to true. maybe this fix this issue.

**Comment by minhcasi** [comment]
@digirizon - also try to update the mstore-api plugin to the latest version - thank you!

**Comment by digirizon** [comment]
@iamar1k92 Real-time DB is already set to read write , and it works fine on simulator

@minhcasi did update to latest MStore plugin but still same error

**Comment by digirizon** [comment]
@minhcasi the issue seems to be occurred only on real devices ! , Please advise we have a deadline coming and afterwards we want to start working on multivendor

**Comment by Jegufull** [comment]
same problem

**Comment by minhcasi** [comment]
@trunghieuvn - please help for suggestion

**Comment by minhcasi** [comment]
@digirizon - sorry for reply late on the ticket as it take our time to find out the issue, please help to check this solution on your phone

Settings > Apple ID, iCloud, iTunes & Appstore > Password & Security > Apps Using Your Apple ID, on you the Fluxstore and Stop Using App ID > Then try to login again
