### ISSUE TITLE
[Cestore] Old SDK version

### ISSUE THREAD

**Issue by oussem** [inspireui/support#2832]
Hello,

I purchased your Cestore product today but the SDK version is too old (31).
If we change the version 34, some plugins  react-native-reanimated are not working. 
Do you have an newer version.

Thanks in advance

**Comment by minhcasi** [comment]
@luyx2412 - please help to update the cestore app to latest Expo version - thank you!

**Comment by hhouadria** [comment]
Hi there, me too I have the same issu : SDK version is too old (31).
Can you provide us with an updated version as soon as possible.
Thanks

**Comment by luyx2412** [comment]
Hi @oussem We are updating latest version and will send notification when have next version.

Thanks

**Comment by oussem** [comment]
Thanks.
But please how to access the cestore admin ?

We can't test the web app admin panel because it requires authorization
token with no possible login. You don't have documentation about this ?

Thank you very much.
