### ISSUE TITLE
[Fluxnews] Open Push Notifcation to the targeted articles  

### ISSUE THREAD

**Issue by bidfor** [inspireui/support#2833]
After I send a push notification with an article in it. Can the user click the push notification and then it will open the article in the app?

**Comment by minhcasi** [comment]
Yes, you can - it's one of the deep link feature support from the app - thanks

**Comment by bidfor** [comment]
How do you do that ? 

![image](https://user-images.githubusercontent.com/2523772/80058048-c1036f00-855a-11ea-9eb9-efab4bfcca81.png)

I tried placing my link on Message. It only open the app.
Then I tried placing on LaunchURL. All it does is open the app in webview.
