### ISSUE TITLE
Can not confirm order 

### ISSUE THREAD

**Issue by aphk2020** [inspireui/support#2834]
Hello, I am using the latest version. I found that the order could not be confirmed during the test. As long as you click to 「confirm order 」, an error will occur .Please check the screenshot :
https://drive.google.com/file/d/1Q-SKAGuY8l-jBjcC_f5-y5nAv1XFM1yH/view?usp=sharing https://drive.google.com/file/d/1jZfk3XDIgLdCzdwWRiCB_OxI26tR35ZK/view?usp=sharing

**Comment by minhcasi** [comment]
Hi @aphk2020 - please help to us to provide more info to http://private.inspireui.com/ - thank you!

**Comment by aphk2020** [comment]
I have sent the relevant information.
Hope you can help solve it as soon as possible.
