### ISSUE TITLE
Fluxstore WooCommerce app scroll gets slow

### ISSUE THREAD

**Issue by digant201** [inspireui/support#2835]
![Screenshot from 2020-04-22 12-38-07](https://user-images.githubusercontent.com/62238856/79952764-8933f300-8498-11ea-8c46-87e04d3e7afc.png)

When scroll top to bottom for reload/refresh scroller gets slow

Issue 1:

Here is console log when scroll works:

I/flutter (31195): Bad state: No element
I/flutter (31195): Bad state: No element
I/flutter (31195): Bad state: No element
I/flutter (31195): Bad state: No element
I/flutter (31195): Bad state: No element
I/flutter (31195): Bad state: No element
I/flutter (31195): Bad state: No element
I/flutter (31195): Bad state: No element
I/flutter (31195): Bad state: No element
I/flutter (31195): Bad state: No element
I/flutter (31195): Bad state: No element
I/flutter (31195): Bad state: No element
I/flutter (31195): Bad state: No element
I/flutter (31195): Bad state: No element
I/flutter (31195): Bad state: No element
I/flutter (31195): Bad state: No element
I/flutter (31195): Bad state: No element
I/flutter (31195): Bad state: No element
I/flutter (31195): Bad state: No element
I/flutter (31195): Bad state: No element
I/flutter (31195): Bad state: No element
I/flutter (31195): Bad state: No element
I/flutter (31195): Bad state: No element
I/flutter (31195): Bad state: No element

this issue comes when swipe top to bottom when top ends and again do bottom to top swipe. Please check this. 

Issue 2:

And also this when welcome screen comes firsttime font gets load and slider gets slow while fonts not loading but after error comes it swipe slider works fine
but not initially:

I/flutter (32611): error: google_fonts was unable to load font Raleway-Regular because the following exception occured
I/flutter (32611): Exception: Failed to load font with url: https://fonts.gstatic.com/s/a/1aec65f5e5dca3ec9f8719936af31f54336bb5d99f25bf343ff25e009d5e569d.ttf

**Comment by trunghieuvn** [comment]
> Issue 1:
> 
> Here is console log when scroll works:
> 
> I/flutter (31195): Bad state: No element
> I/flutter (31195): Bad state: No element
> I/flutter (31195): Bad state: No element
> I/flutter (31195): Bad state: No element
> I/flutter (31195): Bad state: No element
> I/flutter (31195): Bad state: No element
> I/flutter (31195): Bad state: No element
> I/flutter (31195): Bad state: No element
> I/flutter (31195): Bad state: No element
> I/flutter (31195): Bad state: No element
> I/flutter (31195): Bad state: No element
> I/flutter (31195): Bad state: No element
> I/flutter (31195): Bad state: No element
> I/flutter (31195): Bad state: No element
> I/flutter (31195): Bad state: No element
> I/flutter (31195): Bad state: No element
> I/flutter (31195): Bad state: No element
> I/flutter (31195): Bad state: No element
> I/flutter (31195): Bad state: No element
> I/flutter (31195): Bad state: No element
> I/flutter (31195): Bad state: No element
> I/flutter (31195): Bad state: No element
> I/flutter (31195): Bad state: No element
> I/flutter (31195): Bad state: No element
> 
> this issue comes when swipe top to bottom when top ends and again do bottom to top swipe. Please check this.

To fix this error, please check null and empty on the following code:

In file: `lib/common/tools.dart`
Function : `_getYoutubeLink` 
```
  static String _getYoutubeLink(String content) {
    final regExp = RegExp(
        "https://www.youtube.com/((v|embed))\/?[a-zA-Z0-9_-]+",
        multiLine: true,
        caseSensitive: false);

    String youtubeUrl;

    try {
      if (content?.isNotEmpty ?? false) {
        Iterable<RegExpMatch> matches = regExp.allMatches(content);
        if (matches?.isNotEmpty ?? false) { 
          youtubeUrl = matches?.first?.group(0) ?? '';
        }
      }
    } catch (error) {
//      printLog('[_getYoutubeLink] ${error.toString()}');
    }
    return youtubeUrl;
  }
```

Function `_getFacebookLink`
```
 static String _getFacebookLink(String content) {
    final regExp = RegExp(
        "https://www.facebook.com\/[a-zA-Z0-9\.]+\/videos\/(?:[a-zA-Z0-9\.]+\/)?([0-9]+)",
        multiLine: true,
        caseSensitive: false);

    String facebookVideoId;
    String facebookUrl;
    try {
      Iterable<RegExpMatch> matches = regExp.allMatches(content);
      if (matches?.isNotEmpty ?? false) {
        facebookVideoId = matches.first.group(1);
        if (facebookVideoId != null) {
          facebookUrl =
              'https://www.facebook.com/video/embed?video_id=$facebookVideoId';
        }
      }
    } catch (error) {
      print(error);
    }
    return facebookUrl;
  }
```

Function `_getVimeoLink`

```
static String _getVimeoLink(String content) {
    final regExp = RegExp("https://player.vimeo.com/((v|video))\/?[0-9]+",
        multiLine: true, caseSensitive: false);

    String vimeoUrl;

    try {
      Iterable<RegExpMatch> matches = regExp.allMatches(content);
      if (matches?.isNotEmpty ?? false) {
        vimeoUrl = matches.first.group(0);
      }
    } catch (error) {
      print(error);
    }
    return vimeoUrl;
  }
}
```


![image](https://user-images.githubusercontent.com/19247680/80087783-c88c3d80-8585-11ea-8d23-a90a1d7820b3.png)

**Comment by trunghieuvn** [comment]
> Issue 2:
> 
> And also this when welcome screen comes firsttime font gets load and slider gets slow while fonts not loading but after error comes it swipe slider works fine
> but not initially:
> 
> I/flutter (32611): error: google_fonts was unable to load font Raleway-Regular because the following exception occured
> I/flutter (32611): Exception: Failed to load font with url: https://fonts.gstatic.com/s/a/1aec65f5e5dca3ec9f8719936af31f54336bb5d99f25bf343ff25e009d5e569d.ttf

I checked that there was no error in the latest version of FluxStore. Please try to update to the latest version. If there are errors please record the video of the steps. I will handle them quickly. Thanks

**Comment by digant201** [comment]
> > Issue 2:
> > And also this when welcome screen comes firsttime font gets load and slider gets slow while fonts not loading but after error comes it swipe slider works fine
> > but not initially:
> > I/flutter (32611): error: google_fonts was unable to load font Raleway-Regular because the following exception occured
> > I/flutter (32611): Exception: Failed to load font with url: https://fonts.gstatic.com/s/a/1aec65f5e5dca3ec9f8719936af31f54336bb5d99f25bf343ff25e009d5e569d.ttf
> 
> I checked that there was no error in the latest version of FluxStore. Please try to update to the latest version. If there are errors please record the video of the steps. I will handle them quickly. Thanks


[VID-20200423-WA0009.zip](https://github.com/inspireui/support/files/4523520/VID-20200423-WA0009.zip)

here the video where font weight change and this error comes in console. Thanks :)

**Comment by digant201** [comment]
https://github.com/inspireui/support/issues/2862
(Cart items incrementing when i close and reopen app)

This issue also showing to me after implementing 
https://github.com/inspireui/support/issues/2615#issuecomment-610791140
so requested to Gitlab

**Comment by trunghieuvn** [comment]
> > > Issue 2:
> > > And also this when welcome screen comes firsttime font gets load and slider gets slow while fonts not loading but after error comes it swipe slider works fine
> > > but not initially:
> > > I/flutter (32611): error: google_fonts was unable to load font Raleway-Regular because the following exception occured
> > > I/flutter (32611): Exception: Failed to load font with url: https://fonts.gstatic.com/s/a/1aec65f5e5dca3ec9f8719936af31f54336bb5d99f25bf343ff25e009d5e569d.ttf
> > 
> > 
> > I checked that there was no error in the latest version of FluxStore. Please try to update to the latest version. If there are errors please record the video of the steps. I will handle them quickly. Thanks
> 
> [VID-20200423-WA0009.zip](https://github.com/inspireui/support/files/4523520/VID-20200423-WA0009.zip)
> 
> here the video where font weight change and this error comes in console. Thanks :)

Pls help to update the latest 1.7.0 and check again the problem. Thanks

**Comment by digant201** [comment]
Ok, thanks can you please send me the files changes log means changed file path so if i modified any old version files i can update those files that has changed or newly added in new version after compare with tool. Thank you for your help.

**Comment by minhcasi** [comment]
@digant201 - pls help to process this form to get the gitlab and files change - https://docs.google.com/forms/d/e/1FAIpQLSeuBqUkScy42V7KKhfNPj0fl581anrB1mWkbMa3p2WQt7fhfw/viewform - also download the latest release to fix the issue - thank you for your time 👍

**Comment by digant201** [comment]
Bellow error comes when i configured fluxstore 1.7 version, this comes when isCaching is enabled. Please check


I/flutter (30786): ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (30786): The following NoSuchMethodError was thrown during a scheduler callback:
I/flutter (30786): The getter 'length' was called on null.
I/flutter (30786): Receiver: null
I/flutter (30786): Tried calling: length
I/flutter (30786): 
I/flutter (30786): When the exception was thrown, this was the stack:
I/flutter (30786): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
I/flutter (30786): #1      MainTabsState.loadTabBar.<anonymous closure> (package:fstore/tabbar.dart:139:53)
I/flutter (30786): #2      State.setState (package:flutter/src/widgets/framework.dart:1148:30)
I/flutter (30786): #3      MainTabsState.loadTabBar (package:fstore/tabbar.dart:138:5)
I/flutter (30786): #4      MainTabsState.afterFirstLayout (package:fstore/tabbar.dart:79:5)
I/flutter (30786): #5      AfterLayoutMixin.initState.<anonymous closure> (package:after_layout/after_layout.dart:10:38)
I/flutter (30786): #6      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
I/flutter (30786): #7      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1049:9)
I/flutter (30786): #8      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:957:5)
I/flutter (30786): #12     _invoke (dart:ui/hooks.dart:259:10)
I/flutter (30786): #13     _drawFrame (dart:ui/hooks.dart:217:3)
I/flutter (30786): (elided 3 frames from package dart:async)
I/flutter (30786): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (30786): [Fluxstore][MyConnectivity] online
I/flutter (30786): [Fluxstore][App] internet issue change: {ConnectivityResult.mobile: true}
I/flutter (30786): Another exception was thrown: _AnimatedSplashState#9a9c3(ticker active) was disposed with an active Ticker.
I/flutter (30786): [Fluxstore][wocommerce_api][14:03:13.551788] getAsync END [endPoint:flutter/cache] url:flutter/cache
I/flutter (30786): [Debug] Finish Load AppConfig
I/flutter (30786): [Fluxstore][AppState] Init Data Finish
E/flutter (30786): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Looking up a deactivated widget's ancestor is unsafe.
E/flutter (30786): At this point the state of the widget's element tree is no longer stable.
E/flutter (30786): To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.
E/flutter (30786): #0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure> (package:flutter/src/widgets/framework.dart:3508:9)
E/flutter (30786): #1      Element._debugCheckStateIsActiveForAncestorLookup (package:flutter/src/widgets/framework.dart:3522:6)
E/flutter (30786): #2      Element.getElementForInheritedWidgetOfExactType (package:flutter/src/widgets/framework.dart:3588:12)
E/flutter (30786): #3      Provider.of (package:provider/src/provider.dart:221:34)
E/flutter (30786): #4      _AppInitState.loadInitData.<anonymous closure> (package:fstore/app_init.dart:75:18)
E/flutter (30786): #5      new Future.delayed.<anonymous closure> (dart:async/future.dart:316:39)
E/flutter (30786): #6      _rootRun (dart:async/zone.dart:1122:38)
E/flutter (30786): #7      _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter (30786): #8      _CustomZone.runGuarded (dart:async/zone.dart:925:7)
E/flutter (30786): #9      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
E/flutter (30786): #10     _rootRun (dart:async/zone.dart:1126:13)
E/flutter (30786): #11     _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter (30786): #12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
E/flutter (30786): #13     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
E/flutter (30786): #14     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
E/flutter (30786): #15     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
E/flutter (30786): #16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
E/flutter (30786): 
I/flutter (30786): [Fluxstore][AppState] build Theme
