### ISSUE TITLE
Install Error Flutter Shopify

### ISSUE THREAD

**Issue by kangsotheara** [inspireui/support#2836]
Step 1 (require): detail issues and screenshots

C:\Users\kangs\Dropbox\Android Project\Flutter Shopify\source\android\app\src\debug\AndroidManifest.xml Error:
	Attribute meta-data#onesignal_app_id@value at AndroidManifest.xml requires a placeholder substitution but no value for <onesignal_app_id> is provided.
C:\Users\kangs\Dropbox\Android Project\Flutter Shopify\source\android\app\src\debug\AndroidManifest.xml Error:
	Attribute meta-data#onesignal_google_project_number@value at AndroidManifest.xml requires a placeholder substitution but no value for <onesignal_google_project_number> is provided.

FAILURE: Build failed with an exception.

![Screenshot 2020-04-22 14 58 14](https://user-images.githubusercontent.com/2009861/79956102-e08e8f00-84a9-11ea-88eb-af8d1054bbac.png)

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by kangsotheara** [comment]
Hi sir,

What should I do to solve this problem?

**Comment by minhcasi** [comment]
@kangsotheara - this is caused by the onesignal setting - we will upload new build today to fix this issue - thank you!

**Comment by minhcasi** [comment]
@kangsotheara  - could you help to download the latest 1.6.7 stable version - thank you!
