### ISSUE TITLE
Fluxstore store page blank with type wcfm config

### ISSUE THREAD

**Issue by webofficial** [inspireui/support#2837]
Step 1 (require): detail issues and screenshots
I am using Fluxstore version 1.6.4 and config with type wcfm.After the config products with category id and also categories all are coming properly but the store showing blank.I don't know what i missed and where i am went wrong.

I hope i have properly followed the instruction of wordpress setting and config file as in the fluxstore document.

Here i am attaching the screen shot of store page.Kindly help me to resolve this issue.
![Screenshot_20200416-181501](https://user-images.githubusercontent.com/64073974/79960105-aa431680-848d-11ea-995b-6151fceec57f.png)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhcasi** [comment]
@webofficial - could you help to download latest 1.6.6b that fixed this problem - thank you!
