### ISSUE TITLE
fluxstore multi vendor - register vendor

### ISSUE THREAD

**Issue by walidcpu** [inspireui/support#2839]
https://ibb.co/mFg3cJF

https://ibb.co/DrLrwNr

This link for Ver: 1.6.6b. 
 https://imgur.com/mc1dlzb. Not work with any  program 

The new version 1.6.6b does not work on Android Studio or any other programs
The registration process in version 1.6.4 works well on facebook, gmail and sms.
but Register vendor not working and this problem is repeated with all PURCHASED. But you do not work to solve it

This link for same https://github.com/inspireui/support/issues/2645

**Comment by minhcasi** [comment]
@walidcpu - this is the error that you have not updated the library 

There are 2 solutions
1. open the pubspec.yaml and click 'Get Pub' from Android studio
2. Run this script `flutter pub get`

If you are not satisfied with the product, kindly process on this link - https://help.market.envato.com/hc/en-us/articles/202821460-Can-I-Get-A-Refund-
As you don't have experience with flutter, you need to spend some time to read the document http://flutter.dev, instead of claiming on the product :)

**Comment by walidcpu** [comment]
Thank you very much
but I still have the problem of( register vendor )that does not work.
https://ibb.co/wd3WN9D
 I hope for a solution and I followed all the instructions of this link  https://docs.inspireui.com/fluxstore/sign-in/

**Comment by minhcasi** [comment]
@walidcpu - this login issue could cause by your rest api not working fine, please help to check this similar URL: https://your-hosting/wp-json to see if it can return the data

example on our site: http://dokan.mstore.io/wp-json

**Comment by walidcpu** [comment]
this my site:    https://rehik.com/wp-json how to fix it

**Comment by walidcpu** [comment]
I have the same files on my website 
http://rehik.com/wp-json
and the example of your site http://dokan.mstore.io/wp-json 
dokan store not Multi-vendor 
Please give me a step-by-step solution to this problem register vendor  https://ibb.co/DrLrwNr

**Comment by walidcpu** [comment]
https://ibb.co/J7BSg2M
https://ibb.co/wd3WN9D
this my site:   https://rehik.com/wp-json how to fix it
I have the same files on my website 
Please give me a step-by-step solution to this problem register vendor

**Comment by minhcasi** [comment]
@walidcpu - could i know if you have active Dokan Pro plugins, it is used to support for the Rest API Vendor features ?

**Comment by walidcpu** [comment]
Required Plugins |
1. MStore API 
2.Regenerate Thumbnails   
3. JWT Authentication for WP Rest API
https://docs.inspireui.com/fluxstore/multi-vendor/
Give me this Dokan Pro plugin
And how to used it?

**Comment by walidcpu** [comment]
https://imguh.com/image/Od7vh
https://ibb.co/J7BSg2M
https://ibb.co/wd3WN9D
I have 3 plugins like this. https://docs.inspireui.com/fluxstore/multi-vendor/
How to fix please

**Comment by minhcasi** [comment]
refund

**Comment by hengsoheak** [comment]
This customer already refund?

**Comment by walidcpu** [comment]
I received a message on my email and did not read it
