### ISSUE TITLE
[ListApp] Unable to Customize home page banner

### ISSUE THREAD

**Issue by DNeelanshi** [inspireui/support#284]
**Required Info (please complete the following information):**
 - Listapp
 - Your Purchased Code: https://codecanyon.net/item/listapp-listing-directory-mobile-app-by-react-native/21456447?s_rank=3
[Config.zip](https://github.com/inspireui/support/files/2851418/Config.zip)

(we may not reply if you are not our customer)

**Describe the bug**
I have purchased code and want to Customize home page banner, infact remove it and place search bar instead but unable to do it. PLease help , why it is not happening while editing config/Listable.js.Also with Listable theme, MENU IS BLANK!!!!. I am sending you config file.

**Screenshots**

**Additional context**
Add any other detail logs about the problem here.
If possible please share your config.js that use for the app setting

**Comment by thangvo9x** [comment]
Hi. you can remove home page banner at config/Listable.js. Try to remove the expo app and re-install.
