### ISSUE TITLE
FluxstorePro Major Performance issue in Loading Opencart Product

### ISSUE THREAD

**Issue by Vetriselvan-NA** [inspireui/support#2840]
Step 1 (require): detail issues and screenshots
In the API file "resource\Opencart-extension\mstore.ocmod\upload\catalog\controller\extension\mstore\product.php"

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

In that API file we have only one api for loading a group of products. It doesn't have any filter based on product_id or Separate API for loading a sing product.

When I open a single product in APP, it is loading all the products of its category from server and displaying the selected product. it caused sever overhead. unnecessary processing time APP and API server.

Please optimize it  .

This issue is there in  update 1.6.7 also.

**Comment by minhtruong315** [comment]
@Vetriselvan-NA can u take me screenshot and explain clearly? sorry I don't understand your issues

**Comment by Vetriselvan-NA** [comment]
In the Mobile App, I Just selected and opened a product from home or any category page. 

I had a breakpoint on  Product.fromOpencartJson function. From That I could see you are calling **"/index.php?route=extension/mstore/product&limit=10&page=1&lang=en&category=null"**

That means you are loading all products from server, When I open a single product..

**Comment by minhtruong315** [comment]
@Vetriselvan-NA I checked Fluxstore 1.6.7 with our website. it's working well. do  you have any customize code on Fluxstore? and can u record screen?

**Comment by Vetriselvan-NA** [comment]
![image](https://user-images.githubusercontent.com/13717356/80416338-97976a00-88f1-11ea-8f1c-c5fb5afc23a4.png)

In Cart it is using Actual price instead of selling Price.

**Comment by Vetriselvan-NA** [comment]
![image](https://user-images.githubusercontent.com/13717356/80416476-d2010700-88f1-11ea-964a-89cc00c5a04b.png)

In case If we have different price based on options. it is not reflected in cart

**Comment by Vetriselvan-NA** [comment]
Stock status logic is wrong, May be it should be like this
  Product.fromOpencartJson(Map<String, dynamic> parsedJson) {
    try {
      id = parsedJson["product_id"] != null ? parsedJson["product_id"] : '0';
      name = HtmlUnescape().convert(parsedJson["name"]);
      description = parsedJson["description"];
      permalink = parsedJson["permalink"];
      regularPrice = parsedJson["price"];
      salePrice = parsedJson["special"];
      price = salePrice ?? regularPrice;
      onSale = salePrice != null;
      if (int.tryParse(parsedJson["quantity"]) <= 0) {
        inStock = false;
      } else {
        inStock = true;
     }

**Comment by minhtruong315** [comment]
<img width="1385" alt="Screen Shot 2020-04-28 at 6 59 37 AM" src="https://user-images.githubusercontent.com/10402500/80432269-e22edb80-891d-11ea-82c1-b9b904d86b3c.png">
Stock status is wrong on your website?

**Comment by Vetriselvan-NA** [comment]
> @Vetriselvan-NA I checked Fluxstore 1.6.7 with our website. it's working well. do you have any customize code on Fluxstore? and can u record screen?


[option_price_issue.zip](https://github.com/inspireui/support/files/4547369/option_price_issue.zip)
Please check the recorded video

**Comment by Vetriselvan-NA** [comment]
> <img alt="Screen Shot 2020-04-28 at 6 59 37 AM" width="1385" src="https://user-images.githubusercontent.com/10402500/80432269-e22edb80-891d-11ea-82c1-b9b904d86b3c.png">
> 
> Stock status is wrong on your website? take me screenshot on admin site for stock status?

This option is **not stock status.** This to option to display what we have to show the the product is out of stock. By default |2-3 days" for all default opencart products.

**Comment by Vetriselvan-NA** [comment]
> @Vetriselvan-NA I checked Fluxstore 1.6.7 with our website. it's working well. do you have any customize code on Fluxstore? and can u record screen?
This issue create impact issue if any one have more than 100 products.

[performanceissue.zip](https://github.com/inspireui/support/files/4547457/performanceissue.zip)

**Comment by minhtruong315** [comment]
@Vetriselvan-NA can u upload video to google drive and send me the link? I can't download your files
Thanks

**Comment by Vetriselvan-NA** [comment]
> @Vetriselvan-NA can u upload video to google drive and send me the link? I can't download your files
> Thanks

https://drive.google.com/drive/folders/109WvxCv9L1NgE3YPso5hpoMqZsqcvUx8?usp=sharing

**Comment by minhtruong315** [comment]
@Vetriselvan-NA can you give  me your email. I will send you updates for option price and out of stock.

**Comment by Vetriselvan-NA** [comment]
vetriselvan.na@gmail.com

I have access to you gitlab repo. It is fixed there?

**Comment by minhtruong315** [comment]
No. it haven't updated yet on gitlab. I sent you updates on the email. please check and let me know

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
