### ISSUE TITLE
Getting Error on Install Mstore APi plugins on Wordpress

### ISSUE THREAD

**Issue by husaingwl** [inspireui/support#2841]
Step 1 (require): detail issues and screenshots

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhcasi** [comment]
could you help to share the screenshot issue and complete this form please - http://private.inspireui.com - thank you!
