### ISSUE TITLE
Several questions and problems

### ISSUE THREAD

**Issue by juancamilocanal** [inspireui/support#2843]
Step 1 (require): detail issues and screenshots

1. When trying to archive for app publishing I get the following errors (And yes I have done flutter clean and flutter build ios:
![image](https://user-images.githubusercontent.com/818225/80003344-803a2600-8486-11ea-9736-f41d7e15a273.png)

2. When a user ads something to his cart, and then closes the app and then reopens later there is an error on cart. When will this be solved? I reported a while back:
Video: https://photos.app.goo.gl/pjTg73jvxK3jJehg9

3. Coupon codes are not working even though they do exist:

![image](https://user-images.githubusercontent.com/818225/80003611-e32bbd00-8486-11ea-8654-6a3079eea56f.png)

4. How should I structure a deeplink to go into a product? For example fluxstore://product/name-of-product? 

5. Will a universal link, if the domain is set up correctly, will also take you to a product? For example your source right now its configured with inspireui.com so will inspireui.com/product/name-of-product open a product directly in the app? 

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

Here is proof of purchase because your page private.inspireui.com does not load:
![image](https://user-images.githubusercontent.com/818225/80003854-3bfb5580-8487-11ea-89d5-74f81602c17f.png)

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by juancamilocanal** [comment]
6. I also have many issues with login even though I followed all the guides:
iOS: https://drive.google.com/open?id=1SI1EdaROwyZfBT6ukQCKcHg4nbc8bvKm 
No login works in iOS

Android: https://photos.app.goo.gl/fQnRGBEK8PJAzFg28
No login works in android

**Comment by minhcasi** [comment]
@juancamilocanal - could you try with the latest code 1.6.7 on Gitlab that fixed some issues above ?

**Comment by juancamilocanal** [comment]
Can you give me a link? Thanks

**Comment by minhcasi** [comment]
pls submit this link  https://docs.google.com/forms/d/e/1FAIpQLSeuBqUkScy42V7KKhfNPj0fl581anrB1mWkbMa3p2WQt7fhfw/viewform

**Comment by juancamilocanal** [comment]
Done

**Comment by minhcasi** [comment]
pls check your inbox and using the latest 1.6.7 - thank you!

**Comment by juancamilocanal** [comment]
Ok. I will try and let you know.

**Comment by juancamilocanal** [comment]
1.6.7 version doesn't even log in existing users with email and password. I
couldn't test anything.

**Comment by minhcasi** [comment]
@juancamilocanal - try to share your config via this link http://private.inspireui.com/ - we will help for checking - it could be caused by your rest api issue - thanks

**Comment by juancamilocanal** [comment]
Ok done. I also see there are many users complaining about the login issues. Any news on the fix? Also Ane news on all my questions on this ticket?

**Comment by juancamilocanal** [comment]
Mail and password login issue fixed by adding the purchase store to mstore api. Cart problem fixed with 1.6.7

Deeplink questions remain
Coupons still not working. Is it becaise this doesn't work with 1 page web checkout?

Thanks

**Comment by juancamilocanal** [comment]
Hi please I need an answer, I keep getting the xcode error And I cant archive to publish to appstore
@minhcasi 

![image](https://user-images.githubusercontent.com/818225/80436266-5f2d6700-88c4-11ea-91f2-a1b5d4f32ffe.png)

**Comment by juancamilocanal** [comment]
I managed to end up solving this on my own, the xcode problem. The deeplink questions and universal links questions still remain

**Comment by minhcasi** [comment]
@juancamilocanal - deep link feature is only supported for Blog at the current release, you could try to customize to support for the Product ID by updating this file - https://tppr.me/ZxJiW

**Comment by juancamilocanal** [comment]
Ok. I'll look at this and let you know. Thanks!

**Comment by minhcasi** [comment]
We've also noted this as a feature request and upgrade it on the next release - thank you!
