### ISSUE TITLE
Fluxstore WooCommerce - Flutter E-commerce Full App

### ISSUE THREAD

**Issue by halkawt-mahdi** [inspireui/support#2844]
Step 1 (require): detail issues and screenshots
I do not receive any notification from firebase. 
Looks like the configuration is ready, and I added the google-service.json to my project, but still, I do not get any notifications.

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com
the link didnt work.

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhcasi** [comment]
@halkawt-mahdi - pls try this link https://docs.google.com/forms/d/e/1FAIpQLScWOjkAJIWJ9rgb9alopfOqLsJrGKbFM5cCYj1JBfLKLsBblQ/viewform

**Comment by minhcasi** [comment]
@halkawt-mahdi also double this guide for push notification https://www.youtube.com/watch?v=rFCcWNRPrSk&t=96s

**Comment by halkawt-mahdi** [comment]
Hello dears, 
I have watched this video multiple times, but there are some things missing. for example, you need to have a function to deploy to google, and I cannot find it anywhere.
https://www.youtube.com/watch?v=rFCcWNRPrSk&t=96s
may you please update the video to this version?
