### ISSUE TITLE
Blog layout in homepage not shown properly

### ISSUE THREAD

**Issue by hytcelebi100068** [inspireui/support#2845]
In home screen, blog screen stays white even if fully loaded by app. But if i press show all button or go check on menu>blog, i can see blog entries well. Also i got this error repeatedly. Like trying something to do but can't succeed. I think "Wordpress Mstore API 2.3.x uptades" causes them. Because they were running and i doesnt get these kind of errors. Btw please write some changelog in plugin updates.

Here is an example white screen: https://imgur.com/a/OJjxxJg
And here is the error output: https://gist.github.com/hytcelebi100068/5cbdf6a4b046d0528a99c1639aeae9f7

p.s. submitted google form

**Comment by minhtruong315** [comment]
<img width="432" alt="Screen Shot 2020-04-23 at 5 27 08 PM" src="https://user-images.githubusercontent.com/10402500/80089132-adbac880-8587-11ea-969f-bbb25028449b.png">
I see it's working well
can u send me full source code via email: truong@inspireui.com
with subject:  https://github.com/inspireui/support/issues/2845

**Comment by hytcelebi100068** [comment]
I sent e-mail <kasimenes.29@gmail.com>

**Comment by minhtruong315** [comment]
<img width="394" alt="Screen Shot 2020-04-27 at 6 24 12 AM" src="https://user-images.githubusercontent.com/10402500/80322479-c3621380-884f-11ea-9f8c-20fc455da3d8.png">
I ran your source code. it's working well on blog layout. we're releasing version 1.6.7 soon, you can check your issue on that version

**Comment by minhtruong315** [comment]
@hytcelebi100068 pls update Fluxstore version 1.6.7 and check this issue again
