### ISSUE TITLE
Mstore Opencart

### ISSUE THREAD

**Issue by erknertn** [inspireui/support#2846]
Hi,
1- How do I make only the main categories appear in the categories?

2- Only 1 photo of the products is coming. How can I get all the photos to come?

**Comment by minhtruong315** [comment]
@erknertn can u send me  config.dart file and config_en.json

**Comment by erknertn** [comment]
> @erknertn can u send me config.dart file and config_en.json

Where exactly are the files you specified?

**Comment by minhtruong315** [comment]
send me config and common folder

**Comment by erknertn** [comment]
Hi,
Files attached.


________________________________
Gönderen: minhtruong315 <notifications@github.com>
Gönderildi: Friday, April 24, 2020 12:21:57 AM
Kime: inspireui/support <support@noreply.github.com>
Bilgi: erknertn <erkaner3@hotmail.com>; Mention <mention@noreply.github.com>
Konu: Re: [inspireui/support] Mstore Opencart (#2846)


send me config and common folder

**Comment by minhtruong315** [comment]
@erknertn I dont  see any attached files. pls send them via my email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/2846

**Comment by erknertn** [comment]
Hi,
I sent it with Wetransfer.

________________________________
Gönderen: minhtruong315 <notifications@github.com>
Gönderildi: Monday, April 27, 2020 1:42:49 AM
Kime: inspireui/support <support@noreply.github.com>
Bilgi: erknertn <erkaner3@hotmail.com>; Mention <mention@noreply.github.com>
Konu: Re: [inspireui/support] Mstore Opencart (#2846)


@erknertn<https://github.com/erknertn> I dont see any attached files. pls send them via my email: truong@inspireui.com<mailto:truong@inspireui.com>
with subject: #2846<https://github.com/inspireui/support/issues/2846>

**Comment by erknertn** [comment]
When do you plan to answer?

**Comment by minhtruong315** [comment]
@erknertn you can set ```CategoryListView: true``` in common/Config.js and replace this file: containers/Categories/index.js to fix category
[index.js.zip](https://github.com/inspireui/support/files/4542746/index.js.zip)
Can u send me admin account via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/2846
so that I can  check product images

**Comment by erknertn** [comment]
> @erknertn you can set `CategoryListView: true` in common/Config.js and replace this file: containers/Categories/index.js to fix category
> [index.js.zip](https://github.com/inspireui/support/files/4542746/index.js.zip)
> Can u send me admin account via email: [truong@inspireui.com](mailto:truong@inspireui.com)
> with subject: #2846
> so that I can check product images

I sent.

**Comment by erknertn** [comment]
When will you check?

**Comment by minhtruong315** [comment]
Hi @erknertn sorry for delay. I updated mstore extension for your website to support multi images, You need to change showThumbnailAtLeast: 2 in config to show multi images in app
<img width="1064" alt="Screen Shot 2020-05-02 at 3 48 33 PM" src="https://user-images.githubusercontent.com/10402500/80859640-961cc780-8c8c-11ea-9b26-1578a361f09e.png">

**Comment by erknertn** [comment]
Hi, 
Thanks. I asked a new question. I explained the details in the mail and I am waiting for your help.

**Comment by minhtruong315** [comment]
We dont support customize rest api. 
Thanks

**Comment by erknertn** [comment]
Hi,
index.php?route=extension/mstore/cart/empty

This function does not work. Please check.
[Image.jpeg]

________________________________
Gönderen: minhtruong315 <notifications@github.com>
Gönderildi: Tuesday, April 28, 2020 3:41:03 AM
Kime: inspireui/support <support@noreply.github.com>
Bilgi: erknertn <erkaner3@hotmail.com>; Mention <mention@noreply.github.com>
Konu: Re: [inspireui/support] Mstore Opencart (#2846)


@erknertn<https://github.com/erknertn> you can set CategoryListView: true in common/Config.js and replace this file: containers/Categories/index.js to fix category
index.js.zip<https://github.com/inspireui/support/files/4542746/index.js.zip>
Can u send me admin account via email: truong@inspireui.com<mailto:truong@inspireui.com>
with subject: #2846<https://github.com/inspireui/support/issues/2846>
so that I can check product images
