### ISSUE TITLE
[Fluxstore-Woo] - Issues with OnePageCheckout

### ISSUE THREAD

**Issue by lancerynearson** [inspireui/support#2847]
I'm having problems with One Page Checkout... I download a fresh copy from Code Canyon version is v1.6.6b. Then I got it working and only changed the
"EnableOnePageCheckout": true, and it works using your demo Wordpress site.

Then I switch to my site url and API keys then try One Page Checkout again and nothing happens on the App when the Checkout button is hit.

On Android Studio this comes up in Console:
flutter: getItemTotal 8.99
flutter: [Fluxstore][Cart] build
flutter: [Fluxstore][Cart] build
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: Scaffold.of() called with a context that does not contain a Scaffold.
No Scaffold ancestor could be found starting from the context that was passed to Scaffold.of(). This usually happens when the context provided is from the same StatefulWidget as that whose build function actually creates the Scaffold widget being sought.
There are several ways to avoid this problem. The simplest is to use a Builder to get a context that is "under" the Scaffold. For an example of this, please see the documentation for Scaffold.of():
  https://api.flutter.dev/flutter/material/Scaffold/of.html
A more efficient solution is to split your build function into several widgets. This introduces a new context from which you can obtain the Scaffold. In this solution, you would have an outer widget that creates the Scaffold populated by instances of your new inner widgets, and then in these inner widgets you would use Scaffold.of().
A less elegant but more expedient solutio<…>

![Screen Shot 2020-04-22 at 6 57 53 PM](https://user-images.githubusercontent.com/51379820/80041753-358ecd00-84cb-11ea-8c81-537928f4afa9.png)

**Comment by lancerynearson** [comment]
So I updated the MStore app and added my purchase code to it and now it load when I hit the checkout button but just comes up to this.
![Screen Shot 2020-04-22 at 7 08 12 PM](https://user-images.githubusercontent.com/51379820/80042644-93bcaf80-84cd-11ea-819f-9949077dc95a.png)

**Comment by minhtruong315** [comment]
@lancerynearson can u send me full source code and admin account via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/2847

**Comment by lancerynearson** [comment]
Email was sent a couple days ago, can you confirm email was received?

**Comment by minhtruong315** [comment]
<img width="258" alt="Screen Shot 2020-04-27 at 6 01 54 AM" src="https://user-images.githubusercontent.com/10402500/80322066-9fe99980-884c-11ea-8617-5fb059c71e78.png">
I dont see Plugin menu after login admin site.

**Comment by lancerynearson** [comment]
You will have it now. Thanks

**Comment by minhtruong315** [comment]
@lancerynearson I checked your website. You're using My Listing template for Fluxstore. We don't support this template for Fluxstore. it only supports this theme on Fluxlisting

**Comment by lancerynearson** [comment]
I have the same behavior with the default WordPress theme? I set it to the
default 2020 theme and turned off all plugins except the ones needed for
Fluxstore from your support documents and one page checkout just loads
empty cart page, same behavior.

I don’t need the listing to be in the app as I’m only using the app for
WooCommerce, I haven’t experienced any other issues with the site in
Fluxstore because it’s using My Listing with the exception of the one page
checkout problem witch is happening regardless of theme. Please advise.

Lance

**Comment by minhtruong315** [comment]
<img width="1214" alt="Screen Shot 2020-04-28 at 9 40 58 PM" src="https://user-images.githubusercontent.com/10402500/80500903-fa900c00-8998-11ea-86bd-d2281ea1a2fe.png">
you're still using listing theme

**Comment by lancerynearson** [comment]
Yes sir, I switch it to test to see if it made any difference and it
doesn’t. Im planning to use My Listing as it doesn’t cause any issues with
Fluxlisting. I have had this same site using MyListing thought countless
version of both MStore and FluxListing I have remade the same app in hopes
of having a publishable app over 8 times. No issues as a result of using My
Listing ever. I had hope to have an app in the stores 6 month ago. My
issues was always my weight based USPS shipping not being supported, One
Page Checkout will finally let me use the app after buying 2 different app
from you trying to ale this work. I just need to get One Page Checkout to
work. Feel free to briefly change the theme (as it will break the website
for my users) and you will see that the One Page Checkout problem is
unchanged. I do not believe that My Listing theme is a problem please
explain to me how as I’m extremely frustrated with restarting is project
over and over again, I have everything ready and working both with the site
using My Listing and WooCommerce now with the app, was hoping to lunch app
this week, just need this ONE ISSUES revolve with one checkout now your
telling me a have to start over with the website because of one issues that
is happing for me no mater what theme I use ??????????? I have bought 7
different app from you guy and if I can get this Flux Listing one page to
work I’ll be buying dozens more licenses for more projects. Please help!

Lance

**Comment by minhtruong315** [comment]
can u send me source code of the webiste and export database as well? I want to setup your website on my localhost to debug. I can't determine the problem if I can't debug.

**Comment by lancerynearson** [comment]
So I would just export the database and then download the site from ftp and
send it to you in a zip or ?

Or would it be easier if you to ftp it, or is source code something
different.

I did wonder if it has something to do with my WPEngine hosting, they have
there own cache and CDN but I had them exclude /checkout /cart
/mstore-checkout from the cache.

**Comment by lancerynearson** [comment]
What do I need to send you?

Thanks, Lance

**Comment by minhtruong315** [comment]
@lancerynearson you can zip source code on ftp and export database then send it via my email.
it take more time to download package on ftp, so I can't download. please help me to download

**Comment by lancerynearson** [comment]
Sent in private message.

**Comment by lancerynearson** [comment]
Why is this Closed, I spend a lot of time getting you files to run my site
local and have never heard back, been patently waiting for an update??!

**Comment by minhtruong315** [comment]
I sent you the email before close the ticket. pls check your email

**Comment by lancerynearson** [comment]
I haven’t gotten any emails

**Comment by minhtruong315** [comment]
I sent to this email lance@thedctree.com
