### ISSUE TITLE
Checkout Flow Issue

### ISSUE THREAD

**Issue by gupanant** [inspireui/support#2848]
I am logged in the app and trying to checkout :
1) It didn't copy my name and email on Address Page.
![image](https://user-images.githubusercontent.com/5823667/80055509-a8517580-84d6-11ea-9124-8072381e95f6.png)

2) I have to go back and re-visit shipping page so that is shows Free shipping method
![image](https://user-images.githubusercontent.com/5823667/80055551-c5864400-84d6-11ea-953f-7150ac58e515.png)

3) Payment screen doesn't show any payment methods though I have already enabled Paypal.
![image](https://user-images.githubusercontent.com/5823667/80055592-dfc02200-84d6-11ea-8f80-96142c1c889c.png)

4) For no reason, it takes user to Shopify checkout in webview. If order needs to be placed on shopify checkout page why do we need above three steps ? Also last point : 

5) User session is not transferred to shopify checkout page, so user needs to login again and type in email again ?
![image](https://user-images.githubusercontent.com/5823667/80055713-3594ca00-84d7-11ea-9ecb-1b918f7c8b1a.png)

**Comment by minhcasi** [comment]
@gupanant - could you help to download the latest 1.6.7 stable version, we have fixed these payment issues- thank you!
