### ISSUE TITLE
[MSTORE-MV] Firebase Chat Setup Instruction

### ISSUE THREAD

**Issue by nghonyuen** [inspireui/support#285]
**Mandatory Info (please complete the following information):**
* Product: MSTORE-MV
* Your Purchased Code: 34a1d23d-c198-4cd8-beec-b4d0881c6437
  (we may not reply if you are not our customer)

**Describe the issues**
Need guide to setup Firebase Chat

**Screenshots**
what we done so far is only to configure, but doesn't seems to work. Thanks

Firebase: {
    apiKey: "xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    authDomain: "farm2table-230914.firebaseapp.com",
    databaseURL: "https://farm2table-230914.firebaseio.com",
    storageBucket: "farm2table-230914.appspot.com",
    messagingSenderId: "995638442316",
    readlaterTable: "list_readlater",
  },

**Additional context**
Add any other detail logs about the problem here.

**Comment by nghonyuen** [comment]
Observation so far, using the default setting, which is mstore firebase database, Buyer can send chat to Seller in the Product Chat link, but not via the Profile's Chat List menu. 

On the Seller side, while can see the Buyer name popup in the Chat List, unable to zoom in to see the detail of the Chat.

In additional, there's no notification when a message is received. Please help

**Comment by nghonyuen** [comment]
Hi may I know if there's any update? Thanks

**Comment by thangvo9x** [comment]
Hi. We'll add a turtorial for setup firebase. Maybe in the next month. Thanks.
