### ISSUE TITLE
User can't sign in

### ISSUE THREAD

**Issue by aishema2000** [inspireui/support#2851]
Step 1 (require): detail issues and screenshots

When I launch my app on my device I can not sign in. The sign in with firebase seems to be successful but the login windows loads indefinitely without taking me back to the home screen or profile screen. Here is the output in the debug console when I sign in with email:

==================================
E/EGL-ERROR: _egl_platform_cancel_buffers:644: surface->num_buffers(4)
D/Surface (23198): Surface::disconnect(this=0x87e5e800,api=1)
D/GraphicBuffer(23198): unregister, handle(0x8abba6c0) (w:720 h:1344 s:720 f:0x1 u:f02)
D/View (23198): [Warning] assignParent to null: this = DecorView@b80c15a[SignInHubActivity]
D/WindowClient(23198): Remove from mViews: DecorView@b80c15a[SignInHubActivity], this = android.view.WindowManagerGlobal@fa9f256
I/flutter (23198): type 'String' is not a subtype of type 'int' of 'index'
I/flutter (23198): token: eTG1JsOlPsI:APA91bFt25dgB845YX277pu-NpnvzxMc1N4sCjndQr15S7m0R2jwvqKmdV9-IE0s3aqNECjqaljAg1hmYvm4WaFssHmWITJHdO0NoqGiPziyWeIJE7vgOFMWfGp8kO-uza36euR4ifU
W/DynamiteModule(23198): Local module descriptor class for providerinstaller not found.
I/DynamiteModule(23198): Considering local module providerinstaller:0 and remote module providerinstaller:0
W/ProviderInstaller(23198): Failed to load providerinstaller module: No acceptable module found. Local version is 0 and remote version is 0.
V/NativeCrypto(23198): Registering com/google/android/gms/org/conscrypt/NativeCrypto's 286 native methods...
I/ProviderInstaller(23198): Installed default security provider GmsCore_OpenSSL
I/System.out(23198): port:443

===============

When I connect using SMS, i get the code but after putting the code into the app, nothing happens, it continues loading, the debug console shows this:

![image](https://user-images.githubusercontent.com/15066381/80074982-492d4880-854a-11ea-9f74-e2a11d7a7d7a.png)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by aishema2000** [comment]
**UPDATE:** I have been able to login after I commented this line in the user.dart file like this:
![image](https://user-images.githubusercontent.com/15066381/80095490-4e998b80-8568-11ea-9263-77b54a3ccc7f.png)
I am able to login but if restart the app, I am no longer logged in. I have to log in again.

I also noticed this error in android studio:

![image](https://user-images.githubusercontent.com/15066381/80095558-68d36980-8568-11ea-97e2-cb02ef3ae1af.png)

I am totally new to flutter, I am struggling very hard to get this app working. **I HUMBLY AGAIN AND AGAIN ASK YOU FOR ASSISTANCE...**

**Comment by jeeali** [comment]
Same issue here.
I can't login/signup in FluxStore Pro if I make my Firebase Project.

**Comment by jeeali** [comment]
> **UPDATE:** I have been able to login after I commented this line # 167 in the lib/models/user.dart file like this:
> ![image](https://user-images.githubusercontent.com/15066381/80095490-4e998b80-8568-11ea-9263-77b54a3ccc7f.png)
> I am able to login but I am logged out if I restart the app . I have to log in again.
> 
> I also noticed this error in android studio:
> 
> ![image](https://user-images.githubusercontent.com/15066381/80095558-68d36980-8568-11ea-97e2-cb02ef3ae1af.png)
> 
> I am totally new to flutter, I am struggling very hard to get this app working. **I HUMBLY AGAIN AND AGAIN ASK YOU FOR ASSISTANCE...**

It should not be the problem.  
this line.

await saveUser(user);
is used to save the details of the user in Shared Preferences. So, When the user opens the app after closing it. The app should recognize the user.

**Comment by trunghieuvn** [comment]
> > **UPDATE:** I have been able to login after I commented this line # 167 in the lib/models/user.dart file like this:
> > ![image](https://user-images.githubusercontent.com/15066381/80095490-4e998b80-8568-11ea-9263-77b54a3ccc7f.png)
> > I am able to login but I am logged out if I restart the app . I have to log in again.
> > I also noticed this error in android studio:
> > ![image](https://user-images.githubusercontent.com/15066381/80095558-68d36980-8568-11ea-97e2-cb02ef3ae1af.png)
> > I am totally new to flutter, I am struggling very hard to get this app working. **I HUMBLY AGAIN AND AGAIN ASK YOU FOR ASSISTANCE...**
> 
> It should not be the problem.
> this line.
> 
> await saveUser(user);
> is used to save the details of the user in Shared Preferences. So, When the user opens the app after closing it. The app should recognize the user.

To fix this error, try changing this code:
File: lib/models/user/user.dart

```
 User.fromJsonSMS(Map<String, dynamic> json) {
    try {
      var user = json['user'];
      loggedIn = true;
      id = json['wp_user_id'].toString();
      name = json['user_login'];
      cookie = json['cookie'];
      username = "${user['id']}";  // <<< change this code
      firstName = json['user_login'];
      lastName = '';
      email = user['email'] ?? "${user['id']}";   // <<< change this code
      isSocial = true;
    } catch (e) {
      print(e.toString());
    }
  }
```

![image](https://user-images.githubusercontent.com/19247680/80446730-d5bc7a00-8941-11ea-8821-86d109e0c157.png)

**Comment by trunghieuvn** [comment]
> Same issue here.
> I can't login/signup in FluxStore Pro if I make my Firebase Project.

Please wait for me, I'm making videos and documentation step by step setup login Google, Facebook, Apple and SMS. I will send you as soon as done. 
Thanks

**Comment by jeeali** [comment]
> > Same issue here.
> > I can't login/signup in FluxStore Pro if I make my Firebase Project.
> 
> Please wait for me, I'm making videos and documentation step by step setup login. I will send you as soon as done. 
> Thanks

We are waiting.

**Comment by aishema2000** [comment]
I resolved this issue by creating databases rules in firebase. Now, I can sign in. Thanks

**Comment by minhcasi** [comment]
@aishema2000 - could you help to share your solution so that i could upgrade to the document?

**Comment by aishema2000** [comment]
This is the rule I applied in Firebase console under Database:

`rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {

    // This rule allows anyone on the internet to view, edit, and delete
    // all data in your Firestore database. It is useful for getting
    // started, but it is configured to expire after 30 days because it
    // leaves your app open to attackers. At that time, all client
    // requests to your Firestore database will be denied.
    //
    // Make sure to write security rules for your app before that time, or else
    // your app will lose access to your Firestore database
    match /{document=**} {
      allow read, write: if request.auth.uid != null;
    }
  }
}`

**Comment by Haniel5** [comment]
Videos step by step setup login via Google and Facebook account: https://youtu.be/14ALBSwvV4E
