### ISSUE TITLE
Country Selection on Delvery Page

### ISSUE THREAD

**Issue by anandkausha** [inspireui/support#2852]
Step 1 (require): Hello, we are not able to Select Country on Delivery Page So , It is not Moving on next Form
![WhatsApp Image 2020-04-23 at 1 57 53 PM](https://user-images.githubusercontent.com/63690210/80077066-9f11e880-856a-11ea-833b-6a9880037e37.jpeg)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by luyx2412** [comment]
Hi @anandkausha you meant you disabled `hideCountryList` in Config.js file the form still show?

Thanks
