### ISSUE TITLE
New Mstore Plugin  Version 2.3.5 Issue 

### ISSUE THREAD

**Issue by khalidsharif** [inspireui/support#2853]
Step 1 (require): detail issues and screenshots

<img width="1150" alt="Screen Shot 2020-04-23 at 1 17 44 PM" src="https://user-images.githubusercontent.com/50369621/80088434-2eb49880-8565-11ea-8f82-5130c44b1fd8.png">
The new Version 2.3.5 has an error and not able to activate.

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

<img width="326" alt="79149195-72720a00-7dcf-11ea-9403-55a9b4880464" src="https://user-images.githubusercontent.com/50369621/80088712-8e12a880-8565-11ea-93dc-411be60a5b87.png">

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by khalidsharif** [comment]
I googled the issue, after disabling the child theme ...this error is gone.

**Comment by minhcasi** [comment]
@khalidsharif - as explain from the document the Fluxstore Listing is not required mstore-api - please check of requiring plugins on this guide https://docs.inspireui.com/fluxstore/listing-directory/ - thanks
