### ISSUE TITLE
About detected errors - Fluxstore pro 1.6.6b - Woocommerce

### ISSUE THREAD

**Issue by kumsalajans** [inspireui/support#2855]
Envato User Name: uhceylan 

We have completed the required verification process at http://private.inspireui.com. We have a few problems, I would be glad if you could help.

I bought Fluxstore pro. I use it for Woocommerce.
version 1.6.6b – 05 Apr 2020

**General Information**

Could you please inform us about the files we need to fix regarding the following problems? If you send all project files to us, all the changes we make and additional bug fixes we make are lost.
All problems occur on both android and ios devices.

**Problem 1-)**

When we click on any input (Search, etc.) field twice in the mobile application, the following error appears.

Screenshot: https://i.ibb.co/JzpTb9X/problem-1.jpg

**Problem 2-)**

When the coupon code is entered, the basket amount suddenly turns into a negative number. You can find the example in the picture below.

Screenshot: https://i.ibb.co/SdBr1vW/problem-2.png

**Problem 3-)**

When we close the application completely and reopen it, the following error occurs. This is only valid if there is a product in the basket. Sample screenshot is provided below.

Screenshot: https://i.ibb.co/Cm2Sfxd/problem-3.jpg

**Comment by minhcasi** [comment]
@kumsalajans - please help to check the latest 1.6.7 on Gitlab that fixes most of these issues - thank you!

**Comment by kumsalajans** [comment]
Hello there,

@minhcasi minhcasi

Thank you for your answer.

We want all of these problems to be fixed. We spent a lot of time and we no longer have time. We need to deliver the work we do to our customers. Please can you give information about which problems are fixed in the new version, among our problems? I ask you to convey information about which problems are not fixed.

**Comment by kumsalajans** [comment]
@minhcasi 

I can't see any software updates on this topic. Version 1.6.6b (5 April) appears on Codecanyon.net.

**Comment by minhcasi** [comment]
@kumsalajans - please download the latest 1.7.0 from http://codecayon.net/downloads - confirm these issues as fixed, please help to have a check and let us know if you have any issues - thank you!
