### ISSUE TITLE
Fluxstore Woocommerce - Translation of some fields 

### ISSUE THREAD

**Issue by rodrigoalves1901** [inspireui/support#2856]
![image](https://user-images.githubusercontent.com/43248152/80121597-839ee180-855a-11ea-8380-dbdc6787d4aa.png)

Good afternoon how do I translate the fields below. Because it does not appear in the Spanish translator

Empty messages
![image](https://user-images.githubusercontent.com/43248152/80121726-ae893580-855a-11ea-81e5-b369e3747fac.png)

Date
Featured
On sale

![image](https://user-images.githubusercontent.com/43248152/80121870-ccef3100-855a-11ea-99f2-3a40b582618b.png)

Filters

![image](https://user-images.githubusercontent.com/43248152/80121931-dd071080-855a-11ea-9ffb-ad617be3e43c.png)

Cancel
refunds

![image](https://user-images.githubusercontent.com/43248152/80121996-f27c3a80-855a-11ea-9f67-452f1d8a6baa.png)

**Comment by minhcasi** [comment]
@rodrigoalves1901 - we will include these translated on the latest 1.6.7 - thank you!
