### ISSUE TITLE
Fluxstore Woocommerce: Number of issues found

### ISSUE THREAD

**Issue by basithzan** [inspireui/support#2857]
**1. Firebase push notification configured properly using the video guide and notification is receiving successfully on My account> Notify Messages But there is no push Notification is appearing on the notification bar**
``
![Screenshot 2020-04-23 at 6 57 17 PM](https://user-images.githubusercontent.com/12207952/80118768-7dceed80-85a6-11ea-89cd-2b755eabcfff.png)

**2. Facebook Login Issue**

![IMG_4988](https://user-images.githubusercontent.com/12207952/80118912-a6ef7e00-85a6-11ea-917d-2c8a01b3b708.PNG)

**3. Google login issue: ios App crash and exit when I click google login.**

**4. How to edit About us webview link?? I tried editing settings.dart , but it doesn't work** 

![IMG_063421840BD1-1](https://user-images.githubusercontent.com/12207952/80119353-3563ff80-85a7-11ea-882d-86be0c83a8c9.jpeg)

**5. Razorpay checkout redirecting me to Mstore checkout page (I already added my Razorpay secret key to the app)**

![Screenshot 2020-04-23 at 6 55 00 PM](https://user-images.githubusercontent.com/12207952/80119472-604e5380-85a7-11ea-9ff6-6b8908eb8acf.png)

**6. The signup option is not visible (it is out of the viewport of the screen). Also, can you move the option to above those two buttons?**

![IMG_4992](https://user-images.githubusercontent.com/12207952/80120707-06e72400-85a9-11ea-8fe3-941ef39ca2ee.jpg)

![IMG_4993](https://user-images.githubusercontent.com/12207952/80120727-0d759b80-85a9-11ea-8431-4f0ded91a068.jpg)

**7. I have edited the default country in lib/screens/loginsms/loginsms_constants.dart and lib/common/config/payments.dart , but the country still shows Vietnam**

![IMG_0D2EC8C850B1-1](https://user-images.githubusercontent.com/12207952/80122899-cdfc7e80-85ab-11ea-9608-870ddc1edefc.jpeg)

![IMG_4996](https://user-images.githubusercontent.com/12207952/80122912-d1900580-85ab-11ea-8e40-2f29cc59d1f1.jpg)

**Comment by basithzan** [comment]
Please respond.

**Comment by minhcasi** [comment]
@trunghieuvn - pls follow up the ticket

**Comment by trunghieuvn** [comment]
> **1. Firebase push notification configured properly using the video guide and notification is receiving successfully on My account> Notify Messages But there is no push Notification is appearing on the notification bar**
> ``
> ![Screenshot 2020-04-23 at 6 57 17 PM](https://user-images.githubusercontent.com/12207952/80118768-7dceed80-85a6-11ea-89cd-2b755eabcfff.png)

Push notification in the notification bar is only available on real devices, virtual machines currently do not support. Please try to help me on real device. Thanks

**Comment by trunghieuvn** [comment]
> **4. How to edit About us webview link?? I tried editing settings.dart , but it doesn't work**
> 
> ![IMG_063421840BD1-1](https://user-images.githubusercontent.com/12207952/80119353-3563ff80-85a7-11ea-882d-86be0c83a8c9.jpeg)
You can edit it in the file `lib/screens/settings/settings.dart`. Search keyword `About Us` and change your url.

![image](https://user-images.githubusercontent.com/19247680/80355704-9ab73980-88a2-11ea-8c14-9a68f447d6b9.png)

**Comment by trunghieuvn** [comment]
> 6. The signup option is not visible (it is out of the viewport of the screen). Also, can you move the option to above those two buttons?

You can move `Sign up` above the Sign in with email button or anywhere you like.

Scroll down to the end of the build function in file `lib/screens/users/login.dart`, move the Registration code and paste it above the `StaggerAnimation` Widget (you can search for keyword StaggerAnimation in file `lib/screens/users/login.dart`)

![image](https://user-images.githubusercontent.com/19247680/80356514-c25ad180-88a3-11ea-9f82-cd05619d5b11.png)


![image](https://user-images.githubusercontent.com/19247680/80356392-9dfef500-88a3-11ea-9851-05229ad80238.png)

As for the problem of not showing all the small screen size, you can reduce the size on the bottom of the Logo again. It will be quite helpful.

**Comment by trunghieuvn** [comment]
> 2. Facebook Login Issue
> 3. Google login issue: ios App crash and exit when I click google login.
> 5. Razorpay checkout redirecting me to Mstore checkout page (I already added my Razorpay secret key to the app)
> 7. I have edited the default country in lib/screens/loginsms/loginsms_constants.dart and lib/common/config/payments.dart , but the country still shows Vietnam


As for these issues I am checking and I will respond when I have a solution for you, please wait for me.

**Comment by basithzan** [comment]
Thanks for the response!!

I want to mention one more issue here, Sign in with apple is not working

![IMG_BE0E83BD8832-1](https://user-images.githubusercontent.com/12207952/80362108-afde9900-889f-11ea-9e88-d4de807ad8a4.jpeg)

**Comment by basithzan** [comment]
Any update pls??? Im not able to publish iOS app without fixing the sign in with apple option. Also, Payment gateway issue. Pls help.

**Comment by trunghieuvn** [comment]
Maybe you are missing some setup step. Please wait for me, I'm making videos and documentation step by step setup login Google, Facebook, Apple and SMS. I will send you as soon as done. Thanks

**Comment by basithzan** [comment]
Thanks! How about the Razorpay payment gateway???

**Comment by minhcasi** [comment]
@basithzan - we suggest not to start with Razorpay as the library is not stable that cause the crashing on your app - https://github.com/razorpay/razorpay-flutter/issues you could try to use Webview btw

@trunghieuvn will update the detailed video could help you resolve the issue - thank you!

**Comment by minhcasi** [comment]
@basithzan - pls help to check these video guides

Login with GG: https://drive.google.com/drive/folders/1-IWAUFkU34NFPQ5hDwY_VJCIvZ7lagv1?usp=sharing
Login with Facebook: https://drive.google.com/drive/folders/176_H6kpToYpmAsgt7ZeQgRvsmwPxhktG?usp=sharing

**Comment by basithzan** [comment]
How about the sign in with the apple issue???

**Comment by minhcasi** [comment]
@basithzan - could you explain more the apple issue, it's working fine with our testing 

the Razopay is still not stable so that we do not recommend to use, but if you would like to try, there are already function from the app you could un-comment to make it work (make sure to install it from pubspec)

**Comment by basithzan** [comment]
@minhcasi I have already shared a screenshot with the error code above.
![80362108-afde9900-889f-11ea-9e88-d4de807ad8a4](https://user-images.githubusercontent.com/12207952/81557161-2358ce00-93a9-11ea-9716-2361395952c7.jpeg)

Can you please explain how to enable it(Razorpay)??
