### ISSUE TITLE
Get vendor city location by api

### ISSUE THREAD

**Issue by hermesalvesbr** [inspireui/support#2858]
Is there an endpoint in the integration api that can return me to the vendor's city?

Maybe like this https://wclovers.github.io/wcfm-rest-api/#get-settings-by-email, but with filter by city.

I need to display on the first page of the application, only stores in the same city as the buyer.

**Comment by minhcasi** [comment]
@hermesalvesbr - unforgettable this Rest API is not available, if you find out any clue to implement this feature, please share with us  - thank you!
