### ISSUE TITLE
How to add custom fields to checkout page?

### ISSUE THREAD

**Issue by hytcelebi100068** [inspireui/support#2859]
I add some custom fields in woocommerce checkout page. I want to add it to app to. In `.../lib/screens/checkout/shipping_address.dart` i add required fields to shown in app. But i have a problem to parse in `.../lib/models/address.dart` file. Because the fields is not registering to the rest api endpoint so form field isnt working. Is the method i'm using true and if how to add them to rest api, could you please show?

i sent form

**Comment by minhcasi** [comment]
@hytcelebi100068 - you could try to add via Meta_data field, please check this solution - https://stackoverflow.com/questions/28952970/woocommerce-api-update-order-meta-fields

Could you share us your code and screenshot which field you would like to add, you could also try the onePageCheckout that support the webview sync all data as your website - thank you!

**Comment by hytcelebi100068** [comment]
Thank you for answer. I tried but i failed to do. I checked the link you post, i got the basics but its hard to implement on dart. Could you please help me? I sent the source code yesterday to <truong@inspireui.com> for another issue, do i need to send again? Here is the screenshot what i'm explaining. https://imgur.com/a/MJkjfSP

**Comment by minhcasi** [comment]
@hytcelebi100068 pls help to move your conversation to same one ticket #2845
