### ISSUE TITLE
(Flux Store) Hide price for unregistered users?

### ISSUE THREAD

**Issue by xLidoni** [inspireui/support#2861]
Step 1 (require): detail issues and screenshots

**How can I hide prices from unregistered users?**

I understood to use: Provider.of <UserModel> (context) .loggedIn

**Can I kindly know how to set it up?
Thank you.**

Step 2 (require): verify license and sharing config files via this google form - 

Already sent previously by e-mail.

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhcasi** [comment]
@xLidoni - you could customize this file product_cart_view -> https://tppr.me/qIvGG 

Please make sure the define 
```
bool isLogin = Provider.of (context) .loggedIn
```
