### ISSUE TITLE
[FluxStore-Woo} - PayPal Not working + Cart items incrementing when i close and reopen app.

### ISSUE THREAD

**Issue by Jazzykhan** [inspireui/support#2862]
Step 1 (require): detail issues and screenshots
Hi, i am trying to setup PayPal i did it working in version 1.5 i think but after few months now i want to update my app. The issue is quite simple when i use   "EnableOnePageCheckout": false, and my PayPal client id and secret is 100% correct. When i goto checkout page add my details to order and click paypal then i move to webview in paypal where i paid. now the problem is when ever i click on pay now it suddenly start the screen (sending you back etc) and then suddenly nothing happens no order comes to my website and it evens deduct money from my paypal but after that i have been trying with sandbox and old versions (old source 1.5.5 and old mstore wordpress plugin) it still doesnt work i will post my video and error from console below. 
The second issue is: When ever i put something in cart and close my app then reopen my app there is an error so i read somewhere to make something true and i did it now the problem is whenever i reopen my app it continuously increment the quantity in my cart i.e if i have 1 item it will 2 then 4 then 6. 
Also, i have applied for gitlab access please approve if you have solved these issues.
I am in emergency need of these bugs PayPal is very very critical.
Thanks
PayPal Error Details:
Error: https://pastebin.com/TudjJXDd

Cart Error Details:
Video: https://drive.google.com/open?id=1CLi5aKhW8DqTSaMF9HudulLyXpm6cAZn

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com
I did

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhcasi** [comment]
@Jazzykhan - this issue may fix on latest 1.6.7 on our Gitlab - it will be ready in 1-2 days, could you help to quick check on this version please. 

The default paypal is setup as native payment

**Comment by Jazzykhan** [comment]
Hi, i can help as soon i get access on gitlab. i have applied for it give me access.
Thanks

**Comment by minhtruong315** [comment]
@Jazzykhan you can update Fluxstore 1.6.7 to fix cart issue and enable NativeOnePageCheckout: true in common/config/payments.dart to fix paypal issue
