### ISSUE TITLE
[FluxStore] Build Issue - Codesign Error - When making any change to image , change app icon or logo .  & TAP Configuration

### ISSUE THREAD

**Issue by siyashamsudeen** [inspireui/support#2864]
Step 1 (require): detail issues and screenshots

Im getting Build Error - Codesign error when i make any change to image or add any image files to the assets folder such as changing app icon or changing logo or be anything . i did not have this issue with previous versions such as 1.6.3 and so . 

![image](https://user-images.githubusercontent.com/57159602/80172495-31af9780-85fe-11ea-8cd3-7a69e80ee948.png)

Please note : The code runs successfully if i build the downloaded code without making any changes on the code or files . If you run as it is downloaded then it works . but any change made on image files it will start giving codesign error . please help to fix this . i already tried all possible solutions mentioned on the documentation . 

I tried deleting the pod files and running
i tried flutter clean
i tried refreshing the provisioning profile and so 
i tried rebooting 
i tried deleting xcode derived files 
i tried upgrading flutter 
i installed latest version of xcode and mac . 
Still this issue is not resolved

2. Please give me instruction on how to configure TAP Payment gateway . Which key ( Test Key or Live API Key ) i should paste in the config file ? In woocommerce setting there are various fields such as merchant id, api key , username and password ? is it not required to give those values in the app code ? please clarify on this as i havent found any documentation for the same. 

Please Please Please help to resolve this issue . we are on a very bad crisis period . i request you to help to run this app so that we can atleast do some online sales of our products as the retail stores are closed due to lock down at the moment . please help . 

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhcasi** [comment]
sent email to verify license
