### ISSUE TITLE
"epayco" payment gateway issue

### ISSUE THREAD

**Issue by samik9** [inspireui/support#2865]
Hello guys i can not make this gateway to work, i got this error when i click on order: 

"Im sorry, you don't have permission to do that"
![Screenshot_20200424-003412](https://user-images.githubusercontent.com/50071744/80178339-94377200-85c3-11ea-86a3-9f24a4a2f258.jpg)

Config.dart file:
https://gzodigital.d.pr/36Btah

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by samik9** [comment]
I think this issue with this payment will be easily fix if you download and use the api sample data
epayco plugin:
https://wordpress.org/plugins/epayco-agregador-woocommerce/

sample data:

P_CUST_ID_CLIENTE:  41451

P_KEY: 51717ef0d494f1f2eb4ebafd10f98f8aed2aec2b

PUBLIC_KEY: b95340119e756e2dc49b3b6eccb53a38

Sitio en pruebas: YES

**Comment by minhcasi** [comment]
@samik9 - pls help to provide more info to http://private.inspireui.com and reopen the ticket - thanks

**Comment by samik9** [comment]
I did that 2 days ago!

**Comment by minhcasi** [comment]
@samik9 - sorry we missed your message - could you help to download the latest version 1.7.0 - there are a lot of improvements with the payment

Let us know your checking - thank you!

**Comment by samik9** [comment]
I downloaded latest version 1.7.0 and add to cart /  Buy now button are not working 
![screenshot-1588053379695](https://user-images.githubusercontent.com/50071744/80452178-4dab8580-88eb-11ea-9b67-d2f862150eff.jpg)

**Comment by samik9** [comment]
@minhcasi  ?

**Comment by minhtruong315** [comment]
@samik9 you need to verify purchase code to use MStore API plugin.
https://github.com/inspireui/support/issues/2884#issuecomment-619670407

**Comment by minhtruong315** [comment]
@samik9 you can replace widgets/frameworks/product_variant_mixin.dart to fix Buy button
[product_variant_mixin.dart.zip](https://github.com/inspireui/support/files/4546218/product_variant_mixin.dart.zip)

**Comment by samik9** [comment]
I replaced with the provided file and did not fix anything. By the way i am using the same api data from your site.

![screenshot-1588105274051_700x576](https://user-images.githubusercontent.com/50071744/80533971-1200d200-8964-11ea-9185-7c266a7883fc.jpg)

**Comment by samik9** [comment]
This happens also with fluxbuilder 1.0.4 , using your demo data
@minhcasi @minhtruong315 

![FluxBuilder of InspireUI 2020-04-28 22-22-02_1800x1179](https://user-images.githubusercontent.com/50071744/80558153-e64f0d80-899e-11ea-8ed0-5e594a4938be.jpg)

**Comment by minhtruong315** [comment]
@samik9 thanks for your report. we will update Fluxbuilder soon.

**Comment by samik9** [comment]
@minhtruong315 dont close the ticket, this started about the issue i got with payments gateways and they told me to update and a did. I found those bugs and now you closed the ticket.

**Comment by minhtruong315** [comment]
You only posted 2 issues. I gave you solutions. I dont see your post other issues. so I will close the ticket

**Comment by samik9** [comment]
@minhtruong315  payment gateway issue is not fixed

**Comment by minhtruong315** [comment]
Did you verify MStore Api plugin?

**Comment by samik9** [comment]
Plugin is fine, but as i said, it happens with your site woocommerce api too

<img width="856" alt="MStore Api - Bugambillia 2020-04-28 23-47-02" src="https://user-images.githubusercontent.com/50071744/80561582-92e2bc80-89aa-11ea-9860-bbefb4857008.png">

**Comment by ramyragab1** [comment]
> @samik9 you can replace widgets/frameworks/product_variant_mixin.dart to fix Buy button
> [product_variant_mixin.dart.zip](https://github.com/inspireui/support/files/4546218/product_variant_mixin.dart.zip)

i have same error and do this replace and error fixed

**Comment by samik9** [comment]
You guys made an excellent job fixing this payment gateway errors by allowing to use full WebView checkout: These options are very useful. Also, Buy button error was fixed on 1.7.1

EnableOnePageCheckout
 "NativeOnePageCheckout

You can close this ticket.

By the way i found a new bug, check ticket  #2991
