### ISSUE TITLE
errors FluxStore multivendor flutter

### ISSUE THREAD

**Issue by oexbril** [inspireui/support#2866]
Step 1 (require): detail issues and screenshots
Hello, good morning, from Android Studio they tell us that in the new version 1.6.6b there are many errors, and we cannot continue with the work.
The faults are presented in the following folders
![Captura de pantalla 2020-04-23 a las 19 05 22](https://user-images.githubusercontent.com/64252854/80196618-f1601180-861d-11ea-8611-b106bb64204f.png)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

[56406266-fluxstore-multi-vendor-flutter-ecommerce-full-app-license.pdf](https://github.com/inspireui/support/files/4527860/56406266-fluxstore-multi-vendor-flutter-ecommerce-full-app-license.pdf)

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by philipvu30** [comment]
Hi,

Please try to run flutter clean and flutter packages get. Then just run the app and ignore the errors.

Thanks.

**Comment by minhcasi** [comment]
@oexbril - pls try to double-check this video https://www.youtube.com/watch?v=ReAUZDIgh2I
