### ISSUE TITLE
[mstore pro] - apple signin does not work for 2nd time due to incomplete logic

### ISSUE THREAD

**Issue by harry503** [inspireui/support#2867]
Step 1 (require): detail issues and screenshots
1st attempt works, but once it's connected lets say thee user logout, and the user want to login again with apple connect, the app will say can't get email. Because for the 2nd time around, it's design to only return the user uid. not the email and name again.

See https://github.com/invertase/react-native-apple-authentication/issues/17

So, the api and code must be able to handle the 2nd apple login. otherwise it will not work.

either you persist in in redux or have the api to handle login with token that means the server side must save the user uid into the database to be used later / 2nd time.

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com
Done

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by harry503** [comment]
@minhcasi This exact problem is also happening in fluxstore. I also bought and faced the same issue.

**Comment by luyx2412** [comment]
Hi @harry503 currently the rule of apple sign in did not get email the second time. Let us investigate and fix in next version.

Thanks

**Comment by luyx2412** [comment]
Hi @harry503 You need integrate apple sign in with firebase, and it will save the user profile to firebase, and in next version you can get the email based on the firebase store. We am updating in next version which will fix the issue.

Thanks
