### ISSUE TITLE
I have changed icon, API URL and Splash screen but its not reflecting in side loading

### ISSUE THREAD

**Issue by iamrameshwar** [inspireui/support#2868]
Step 1 (require): detail issues and screenshots
https://monosnap.com/file/I0U6q3liaskJrCUpjRrzHgX9KZ2AcD
https://monosnap.com/file/kGv2ssrk4Ib6RwvXPgdwB5loaF0IgB

As you can see in above images I have changed, Logo, Splash screen and api url, but no change is reflecting in the app while side loading. Is there anything else needs to be done? I have followed your documentation to do the same.

**Comment by mansoor88** [comment]
Try to run flutter clean and than run apk or on emulator. I was facing issue of same kind in last i run flutter clean and it works.
