### ISSUE TITLE
Not Able to set Min Order Amount

### ISSUE THREAD

**Issue by chiragsolution** [inspireui/support#2869]
Need Below things into the app:

1. Need to hide add to cart button from Category page
2. Variations are not working properly. It is showing right variation in Cart and Payment page. But after order placement it is showing only the 1st and default option. Like if i have 500gm and 1kg option and when i have placing order for 1kg it shows correct till Payment page but after placing order it shows the amount for 500gm not of 1kg.  
3. Need to set Min Order amount: For example if we set min 500 then user will be not able to place order till he has 500 amount in their cart. 
4. Zipcode restriction is not working. I checked the zone setting. It working for Country and State but I set zipcode for a city location. Then it is only checking the City not the exact location for zipcode. because in a City there might be 8-10 zipcodes, but we want to delivery only 2-3 zipcodes.

**Comment by chiragsolution** [comment]
Our reg email id is: digitalweb@meecolondon.co.uk. You can check order history. 
--

**Comment by chiragsolution** [comment]
Hi, can I get the reply today.

**Comment by minhcasi** [comment]
Hi, thank you for the questions: 

1. Please try to use this tool  to find the related file- https://docs.inspireui.com/fluxstore/customization/#1-how-to-customize-any-ui-from-app
2. The Weight variant is not supported on the app
3. We use this plugin to manage max/min order - https://wordpress.org/plugins/wc-min-max-quantities/
4. Zipcode restriction is also not available

**Comment by chiragsolution** [comment]
Hi Minh,

Thanks for your reply. Please check my comment

1. I will try this.

2. Ok. 

3. For it I am asking to set Min Order Amount like 500 USD. So when user want to checkout we can tell them you can't checkout if you have less then 500USD amount in cart. 

4. How the Zone is working. I checked in Doc. Can we just sent a City or State.

**Comment by Jegufull** [comment]
@minhcasi 

2. The Weight variant is not supported on the app

I tried the variations of color, size and height, and it is not working correctly, when the order is made it takes the default product value, and not the one chosen in the app

Please help, 


I also tried it in version 1.7.0 and it didn't work

**Comment by minhcasi** [comment]
@chiragsolution 

3. The min order amount is not ready to support on the current release, feel free to customize this feature to meet your requirement
4. zone is picked up auto from the app when you set up the Shipping from the Wordpress site

@Jegufull - pls input the detail on your ticket #2893

**Comment by chiragsolution** [comment]
can you help us on which page we have to do customization for amount. Payment or Cart can you let us know the path and line no where the total amount calculation is going.

**Comment by minhcasi** [comment]
@chiragsolution - try to use this Inspector tool - https://docs.inspireui.com/fluxstore/customization/#1-how-to-customize-any-ui-from-app - to point to the UI screen, example the Product detail to get the File Path - then you could customize the file

Could i know which plugin you have been used to support for ' min order amount' - we could consider upgrading this feature

**Comment by chiragsolution** [comment]
https://wordpress.org/plugins/wc-min-max-quantities/  -- We have set the Min Cart Amount 200 but for App it is not working. 

![image](https://user-images.githubusercontent.com/64270731/80566936-b1c86980-8a11-11ea-94dc-ccaf6b47863f.png)

**Comment by minhcasi** [comment]
@chiragsolution - we have updated ticket as a feature request for next improvement - so far this feature is not available - thanks

**Comment by minhcasi** [comment]
moved to backlog for next improvement - https://trello.com/c/yW4Rw0i0/30-min-order-amount

**Comment by chiragsolution** [comment]
thanks but I am also getting the same issue as per here: https://github.com/inspireui/support/issues/2893. when this will be also fixed.
