### ISSUE TITLE
Fluxstore: Checkout page

### ISSUE THREAD

**Issue by qorane099** [inspireui/support#2870]
after l do finish address and shipping parts, the app will not go shipping to review tab, 

l cannot proceed to review and payment.
![IMG_20200402_201209](https://user-images.githubusercontent.com/39888242/80254775-658bcb00-8699-11ea-84c9-e9f7f08a454e.jpg)

**Comment by minhcasi** [comment]
@qorane099 - we could not reproduce this issue - could you try if the original download package have the same issues?

**Comment by qorane099** [comment]
hello, i am still facing the issue.

please note that also the original source has the same issue
