### ISSUE TITLE
[EvaStore] Problems with configurating the app-Help needed 

### ISSUE THREAD

**Issue by zaruman** [inspireui/support#2873]
The app is bringing Null response from the shopify page, the only changes to the code have been on the appconfig.json, I will post below the configuration and where I got each value from to see if everything is alright, also was wondering if the shop having the "Developmet" tag could be the reason why it's not bringing the products. 

Post request made to the server(the problem) return everything as null:
![Post](https://user-images.githubusercontent.com/23266484/80262960-1e7fe480-865d-11ea-98bd-9d2f1b2c821f.png)

APP:
![Genymotion](https://user-images.githubusercontent.com/23266484/80262835-b16c4f00-865c-11ea-9e37-616fe88a1208.png)
Configuration file:
![Config](https://user-images.githubusercontent.com/23266484/80262853-c1842e80-865c-11ea-822b-af9325128527.png)
`{
  "Shopify": {
    "url": "https://yolcan-test.myshopify.com",
    "graphqlUrl": "https://yolcan-test.myshopify.com/api/graphql",
    "storeAccessToken": "544780a48dcdcdd52eff4229cb387e9d",
    "shopId": "29033201712"
  }
}`
Aproved private app store front:
![Storefrontapppermision](https://user-images.githubusercontent.com/23266484/80262903-e1b3ed80-865c-11ea-98a6-f142156eebe5.png)

Store Front acces key:
![StoreFrontAccestoken](https://user-images.githubusercontent.com/23266484/80262906-e4164780-865c-11ea-9c74-6cc56ac626ff.png)

Store Id:
![ID](https://user-images.githubusercontent.com/23266484/80262934-fee8bc00-865c-11ea-817e-5db114037c74.png)

Products on the store:
![Products](https://user-images.githubusercontent.com/23266484/80263006-4707de80-865d-11ea-957a-ff746ba1a343.png)

Any help that you guys could bring would be appreciate it.

and the proof of purchase:
![proffofpurchase](https://user-images.githubusercontent.com/23266484/80263030-5850eb00-865d-11ea-817e-7cce3f3433d3.png)

**Comment by minhcasi** [comment]
@zaruman - please help to sen more detail verify to http://private.inspireui.com - thank you for your time

**Comment by zaruman** [comment]
> 
> 
> @zaruman - please help to sen more detail verify to http://private.inspireui.com - thank you for your time
> 
> > **[Google Forms - create and analyze surveys, for free.](http://private.inspireui.com/)**Create a new survey on your own or with others at the same time. Choose from a variety of survey types and analyze results in Google Forms. Free from Google.

Done

**Comment by zaruman** [comment]
Sorry for Posting too many times, But I need an answer soon.

**Comment by minhcasi** [comment]
@zaruman - sorry for the late response as we have some issue with CoV crisis 

@luyx2412 - pls help with suggestion - thank you!

**Comment by luyx2412** [comment]
Hi @zaruman Please follow the video guide to get right "collection id" https://www.youtube.com/watch?v=nE7a_yx5Q9w&t=66s I just tested your config and everything worked normal. 
![image](https://user-images.githubusercontent.com/8909619/80681132-3edef180-8aea-11ea-86e3-72d190f9f031.png)

Thanks
