### ISSUE TITLE
Product multiplies in the cart

### ISSUE THREAD

**Issue by Fovorno** [inspireui/support#2874]
Step 1 (require): detail issues and screenshots
1. Once product is added and then after the app restarted it multiplies amount of units in the cart, the same happens on actual live app on my mobile. Video included.
Video link: https://vimeo.com/411623514
Pass: 12345

2. On the onboarding, the third page of the onboarding where it has to display fogg-completed-1.png it doesn't show. I changed it with my own image but same name and it doesn't show up, the first two actually show up.

![Capture1](https://user-images.githubusercontent.com/27883324/80266548-6f4a0a00-866a-11ea-9e9b-2832a0672cbb.JPG)
![Capture2](https://user-images.githubusercontent.com/27883324/80266551-6f4a0a00-866a-11ea-92ff-417ef035b295.JPG)
![Capture3](https://user-images.githubusercontent.com/27883324/80266552-6fe2a080-866a-11ea-8e99-da0a9ba1b9d6.JPG)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhcasi** [comment]
1. please use the latest 1.6.7 to fix the issue - it's available on gitlab - we will upload on codecayon in 1-2 day

2. try to replace "assets/images/fogg-completed-1.png"

**Comment by Fovorno** [comment]
1. Is there guide how to update so I don't loose my own changes?

2. Tried before and now, same result.

![Capture4](https://user-images.githubusercontent.com/27883324/80268550-ff418100-8675-11ea-86eb-60881299bf54.JPG)

**Comment by Fovorno** [comment]
Fixed the image. So now only the update part.

**Comment by Fovorno** [comment]
Can you also tell me how to change this image? I just can't find which file. 

![Capture5](https://user-images.githubusercontent.com/27883324/80269015-197d5e00-867a-11ea-8bba-53b019f54a24.JPG)

**Comment by minhcasi** [comment]
@Fovorno - pls try this tool to customize the UI https://docs.inspireui.com/fluxstore/customization/#1-how-to-customize-any-ui-from-app
