### ISSUE TITLE
Change home screen.

### ISSUE THREAD

**Issue by lpzczar** [inspireui/support#2875]
Hello, I hope you are well. I recently bought the Fluxstore Multi Vendor app and I really liked it. But I would like to change home screen. I currently have it (fig. 1) and I want it (fig. 2). How do i do it?

![fig-1](https://user-images.githubusercontent.com/19940455/80270475-1be1b700-867e-11ea-8e8c-95bfbfd5971e.jpg)
![fig-2](https://user-images.githubusercontent.com/19940455/80270477-20a66b00-867e-11ea-80e9-784605a828a9.jpg)

**Comment by philipvu30** [comment]
Hi,

You can find plenty of themes in our example folder. Just copy one of them and replace the config_en, config_ar... with it.

![image](https://user-images.githubusercontent.com/54442328/80271363-be834f80-86e9-11ea-9956-209e82efd7b8.png)

**Comment by minhcasi** [comment]
@lpzczar - pls provide more verify info from http://private.inspireui.com then reopen the ticket - thanks

**Comment by lpzczar** [comment]
thanks!
