### ISSUE TITLE
Adding Advanced Custom Fields to Product Screen

### ISSUE THREAD

**Issue by sercada** [inspireui/support#2876]
Step 1 (require): detail issues and screenshots
I have created custom fields using the Advanced Custom Fields Plugin. I'd like to add this information to the product screen. Right after the availability. 

**Packing: (Custom Field String Here)** 

![Screen Shot 2020-04-25 at 12 24 31 AM](https://user-images.githubusercontent.com/24389792/80271967-26567d80-868b-11ea-84e0-51724db6ac0d.jpg)

I was able to do it in Wordpress by editing functions.php, but unfortunately I don't know how to call for this field on the app. 

This is the code I used to add the custom field on the product page in my site. 
![Screen Shot 2020-04-25 at 12 20 09 AM](https://user-images.githubusercontent.com/24389792/80271923-bea03280-868a-11ea-9d16-463b3f3f2e1c.jpg)

This is the location I'd like to add it:

![Screen Shot 2020-04-25 at 12 15 20 AM](https://user-images.githubusercontent.com/24389792/80271956-08891880-868b-11ea-9d2b-4bb69a8e541a.jpg)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhcasi** [comment]
@sercada - we will help for investigating and let you know - thank you!

**Comment by minhcasi** [comment]
we could not help for checking as the consume key is invalid

**Comment by sercada** [comment]
My apologies, I’m working on the app and create new keys recently. Should I send a new ticket with the new keys?
