### ISSUE TITLE
[beonews pro] Unable to login using email & no data is stored in firebase data base

### ISSUE THREAD

**Issue by hammadhassan** [inspireui/support#2878]
Beonews Pro.

Purchase code [b33d6761-b089-4dee-8f99-8d4859eaad59]

I did check every thing 3 to 4 times but no success on login using email & also no user & data is stored in firebase data base.

![image](https://user-images.githubusercontent.com/5791268/80274814-7f0f3000-86f6-11ea-95e9-142a9c388988.png)

Please check & solve ASAP.

**Comment by hammadhassan** [comment]
Can you please have a look into my issue & respond me back ASAP. I need to fix this soon.

**Comment by luyx2412** [comment]
Hi @hammadhassan In `App/Common/Constant.js` line 25, please enable this field to use firebase.
![image](https://user-images.githubusercontent.com/8909619/80499441-2f9b5f00-8997-11ea-8f23-429361783847.png)

Thanks

**Comment by hammadhassan** [comment]
Thanks for you response.
I will check & let you know.
What about the login issue i'm facing.
When login via email only blank screen appears with the loader?

**Comment by luyx2412** [comment]
HI @hammadhassan Can you share me your screenshot about this issue, i just tested the beonews and everything worked normal.

Thanks

**Comment by hammadhassan** [comment]
Okay. Please wait few hours.

**Comment by hammadhassan** [comment]
I have changed the setting as you said but unfortunately still no data I saved on fire base database & still I can't login using email just a blank screen appears with the loader ....
And it's beonews Pro.  I did checked each & every thing many times but still but able to solve this.

**Comment by hammadhassan** [comment]
@luyx2412 Please check the attached config file.

I used these setting but can't login using email & also no data is stored in Firebase Database. 

[Config.zip](https://github.com/inspireui/support/files/4567795/Config.zip)

Please test login with email & data to stored in Firebase data base.

**Comment by hammadhassan** [comment]
![image](https://user-images.githubusercontent.com/5791268/80875496-39dd9600-8cd4-11ea-9d59-41d9146ab71c.png)
@luyx2412 you never called **readlaterTable** to store user in firebase DB.

Can you please check this for me. Because i'm still not able to login using email & pass.

**Comment by luyx2412** [comment]
Hi @hammadhassan we did not need to call `readlaterTable`. Please read the document https://rnfirebase.io/reference/auth#createUserWithEmailAndPassword

Thanks

**Comment by hammadhassan** [comment]
> 
> 
> @luyx2412 Please check the attached config file.
> 
> I used these setting but can't login using email & also no data is stored in Firebase Database.
> 
> [Config.zip](https://github.com/inspireui/support/files/4567795/Config.zip)
> 
> Please test login with email & data to stored in Firebase data base.

Could you please check this & give me the solution as well.

**Comment by hammadhassan** [comment]
I'm still waiting for your response guys @luyx2412 @minhcasi @trunghieuvn @vumanhsn97 .
It's been 10 days since i open up this issue but not get enough support from you guys to fix this....

**Comment by luyx2412** [comment]
Hi @hammadhassan The first please not mention another guy in this topic. It was assigned to me
![image](https://user-images.githubusercontent.com/8909619/81188156-32253680-8fdf-11ea-8bdb-25af151ea740.png)

Thanks.

**Comment by luyx2412** [comment]
Hi @hammadhassan I have no idea about the issue. So can you send your project via inspireui.team@gmail.com and invite this email to your firebase.

Thanks

**Comment by hammadhassan** [comment]
Thanks for your response. I have sent you an Email.

Please check.

**Comment by luyx2412** [comment]
HI @hammadhassan I just downloaded your project, but it lack of your firebase config. So can you send me your project via inspireui.team@gmail.com again?

Thanks

**Comment by hammadhassan** [comment]
Yes!  I will send the project again & let you know. 
Thanks

**Comment by hammadhassan** [comment]
Project sent. Please check.

**Comment by luyx2412** [comment]
Hi @hammadhassan I am checking about this.

Thanks

**Comment by GHO5TMEDO** [comment]
Any news about the login issue??

**Comment by luyx2412** [comment]
HI @hammadhassan I just tested your project and the firebase login worked normal. Can you test it again?
![image](https://user-images.githubusercontent.com/8909619/82115617-16afed80-978e-11ea-8a5b-5b9cef038cdb.png)

Thanks

**Comment by hammadhassan** [comment]
You have checked with hard-coded email but when I test on iOS & Android I'm not able to log in & data is also not stored in firebase database!

**Comment by luyx2412** [comment]
Hi @hammadhassan Can you invite me to your firebase via inspireui.team@gmail.com. I will easy to investigate.

Thanks

**Comment by hammadhassan** [comment]
I will invite & let you know!

**Comment by luyx2412** [comment]
Closed!

P/S: Feel free to reopen the issue.
