### ISSUE TITLE
Fluxsotre WooCommerce Some bug in the app

### ISSUE THREAD

**Issue by Himnashu** [inspireui/support#2879]
Step 1 (require): detail issues and screenshots
1. When I add some items in the cart and after that close the app when I open I got this error in cart.
![WhatsApp Image 2020-04-21 at 11 47 42 AM](https://user-images.githubusercontent.com/53173981/80276600-7ffc8d80-8707-11ea-804c-127774df93f5.jpeg)

![WhatsApp Image 2020-04-19 at 6 53 31 AM](https://user-images.githubusercontent.com/53173981/80276391-1af46800-8706-11ea-973b-3e36d5f3938f.jpeg)

2. Thumbnails are not loading but the product image is coming. 
![WhatsApp Image 2020-04-19 at 6 59 32 AM](https://user-images.githubusercontent.com/53173981/80276405-45debc00-8706-11ea-8291-1b37e09cf266.jpeg)

3. Select Address is not updating all fields.
![WhatsApp Image 2020-04-19 at 10 15 50 AM](https://user-images.githubusercontent.com/53173981/80276427-69a20200-8706-11ea-8e2f-f0368332fc9f.jpeg)

4. 
**App rejected**
Your recent app submission is not compliant with the Device and Network Abuse policy. We don't allow apps that interfere with, disrupt, damage, or access in an unauthorized manner the user's device, other devices or computers, servers, networks, application programming interfaces (APIs), or services, including but not limited to other apps on the device, any Google service, or an authorized carrier's network. Please make appropriate changes to your app, then submit the updated app for another review. If you submitted an update, the previous version of your app is still available on Google Play.

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you [😊*]

my configuration:- 
The MStore API Plugin Version 2.1.7
Regenerate Thumbnails Version 3.1.3

**Comment by minhcasi** [comment]
@Himnashu - pls try the latest release 1.7.0 

Also, try to upgrade your site to https and keep the default AndroidManifest.xml, if you add some extra setting, it could be rejected from the google play store due to effect the policies

**Comment by Himnashu** [comment]
@minhcasi Thanks, Can you tell me how can I update. Do you have any npm package?

**Comment by Himnashu** [comment]
@minhcasi Select address is not working.

**Comment by minhcasi** [comment]
@Himnashu - pls download the latest version from http://codecayon.net/downloads or you could get it from the gitlab 

Please share the detailed screenshot if you have tested on latest version

**Comment by Himnashu** [comment]
The cart icon is not coming properly.
<img width="299" alt="Screenshot 2020-05-02 at 9 47 37 PM" src="https://user-images.githubusercontent.com/53173981/80869517-933aca80-8cbe-11ea-8db7-90646a86290b.png">

**Comment by Himnashu** [comment]
Hi, @minhcasi  I'm not able to load all products for any categories when users come from category Icon. It's only loading 10 products on load more it's calling API data is coming but not showing in the UI. I tried  by changing ApiPageSize but it's not working. 
Can you please tell me how can I use the same load more functionality when users come from categories icons.
