### ISSUE TITLE
how to update, facebook group invite, react native version of it?

### ISSUE THREAD

**Issue by michaelbrinkworth** [inspireui/support#2880]
https://github.com/inspireui/support/issues/2095 

I already have verified.

how to update it?

Is their a react native version?

where is facebook group invite?

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhcasi** [comment]
@michaelbrinkworth 

This is the facebook group - https://www.facebook.com/groups/1401824449973438/

We have released this react-native product version https://codecanyon.net/item/listapp-listing-directory-mobile-app-by-react-native/21456447 - pelase help to check it - thank you!

**Comment by michaelbrinkworth** [comment]
Does this work with listeo?
