### ISSUE TITLE
How dokan multivendor plugin login and register user in WP woocommerce.   

### ISSUE THREAD

**Issue by rjaimish09** [inspireui/support#2881]
When we have tried to register and login user in dokan but every time show this error.  
![Screen Shot 2020-04-25 at 5 52 35 PM](https://user-images.githubusercontent.com/62127843/80279849-a9281880-871d-11ea-87b4-19f36eb08809.png)

**Comment by minhcasi** [comment]
@rjaimish09 pls provide more verify detail info to http://private.inspireui.com then reopen the ticket support - thank you for your time
