### ISSUE TITLE
login/register issue

### ISSUE THREAD

**Issue by ahmedabdo1995** [inspireui/support#2882]
i got this error in login “no implementation found for method login on channel com.roughike/flutter_facebook_login” i got same for the 3 login methods

**Comment by minhcasi** [comment]
@ahmedabdo1995 - could you help to share this screenshot - also try to use the latest version could fix the issue - thank you!

**Comment by ahmedabdo1995** [comment]
latest version of what ?
the code ?
or what ?
iam using version 1.6.6
is version 1.6.6b solving this issue ?

**Comment by ahmedabdo1995** [comment]
![WhatsApp Image 2020-04-26 at 4 17 59 AM](https://user-images.githubusercontent.com/11061266/80295673-faafc200-8774-11ea-989b-c5a99f57f0c1.jpeg)

**Comment by kumsalajans** [comment]
The same problems are found in other login options. (Facebook & Google)

@minhcasi

**Comment by ahmedabdo1995** [comment]
@minhcasi any recommendation to solve this?

**Comment by mansoor88** [comment]
I am also unable to login with already build id's with my woocommerce store.

**Comment by minhcasi** [comment]
@ahmedabdo1995 @mansoor88 - could you help to update the latest 1.7.0. Also update the mstore-api Wordpress plugin and input the activation code to the mstore-api, then test the login feature again

**Comment by ahmedabdo1995** [comment]
@minhcasi iam using magento

**Comment by mansoor88** [comment]
> @ahmedabdo1995 @mansoor88 - could you help to update the latest 1.7.0. Also update the mstore-api Wordpress plugin and input the activation code to the mstore-api, then test the login feature again

Solved by adding activation key in mstore plugin in wordpress.

**Comment by mansoor88** [comment]
![image](https://user-images.githubusercontent.com/7188395/80589134-0fb97900-8a33-11ea-8886-6ac897fcc256.png)

I am facing this issue while login now. Before it was working fine and i could'nt find this error number.

**Comment by ahmedabdo1995** [comment]
@minhcasi iam still with magento 
so what to do now ?

**Comment by ahmedabdo1995** [comment]
@minhcasi helllo
iam stuck there
please help

**Comment by minhcasi** [comment]
@minhtruong315 - pls help for investigating - thank you!

**Comment by ahmedabdo1995** [comment]
@minhcasi @minhtruong315 
iam still waiting for help !!

**Comment by ahmedabdo1995** [comment]
@minhcasi @minhtruong315 is this so hard ?

**Comment by minhtruong315** [comment]
@ahmedabdo1995 I checked your website. maybe MStore extension is so old. can u give me your email. I will send me the latest MStore extension
Thanks

**Comment by ahmedabdo1995** [comment]
@minhtruong315 i used the one downloaded with the app

midomachakl9@gmail.com
send me the ext here
magento 2

**Comment by minhtruong315** [comment]
I sent it to your email. please check and try to install again. after copy MStore  to app/code folder you run these commands to  reinstall it
```
php bin/magento setup:upgrade
php bin/magento cache:flush
php bin/magento setup:di:compile
```
Let me know when you  done

**Comment by ahmedabdo1995** [comment]
@minhtruong315 is this require to insert api key into magento after that or not ?

**Comment by minhtruong315** [comment]
your mean is accessToken? you dont need to recreate accessToken. it only create the first time
