### ISSUE TITLE
flix news onesignal notefaction

### ISSUE THREAD

**Issue by abdoshy97** [inspireui/support#2883]
I have added that onesignal to the program code. I want the notification to open inside the program and display the news Because when I get a notification, it opens inside the site, not inside the application The code for One signal I added it manually because when I purchased the code it was not inside it even though you are in the explanation you said there is a code inside it

**Comment by minhcasi** [comment]
@abdoshy97 - please help to provide more info from the ticket - http://private.inspireui.com/
