### ISSUE TITLE
Can't login/signup in FluxStore Pro

### ISSUE THREAD

**Issue by jeeali** [inspireui/support#2884]
I've changed the Package Name and created a new project in Firebase and enabled the email, Google, Facebook login options. But not able to login/signup. Facing some weird issues.
a. When I signup. It adds the user to the Firebase Project in the Authentication Tab.

<img width="994" alt="Screenshot 2020-04-25 at 6 23 54 PM" src="https://user-images.githubusercontent.com/17235314/80282299-1cd02280-872a-11ea-9421-40139e9fcf25.png">

b. But shows a SnakBar "Exception: Sorry, you are not allowed to do that."

<img width="250" alt="Screenshot 2020-04-25 at 6 23 54 PM" src="https://user-images.githubusercontent.com/17235314/80282248-e09cc200-8729-11ea-9dd1-15fb1287884f.png">

*Even, I tried to signup with the FluxBuilder's Demo App with my Website and Consumer Keys.

<img width="1265" alt="Screenshot 2020-04-25 at 7 40 27 PM" src="https://user-images.githubusercontent.com/17235314/80282740-a08b0e80-872c-11ea-8e7e-5f7f7f11c0b7.png">

c. And when I try to login with the recently signed-up email. It says "username or password incorrect".

 <img width="250" alt="Screenshot 2020-04-25 at 6 23 54 PM" src="https://user-images.githubusercontent.com/17235314/80282276-032edb00-872a-11ea-9fd4-49c06eadad60.png">

What it is showing up on the Signup Tap.

<img width="1102" alt="Screenshot 2020-04-25 at 7 23 34 PM" src="https://user-images.githubusercontent.com/17235314/80282330-438e5900-872a-11ea-86b1-2aa5cd1b6a3f.png">

Please Help!

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

<img width="619" alt="Screenshot 2020-04-25 at 7 48 56 PM" src="https://user-images.githubusercontent.com/17235314/80282959-d250a500-872d-11ea-9d99-a812c74214f4.png">

I've filled the Google Form also.

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by kumsalajans** [comment]
@minhcasi 

I have the same problem.

The same problems are found in other login options. (Facebook & Google)

**Comment by jeeali** [comment]
@kumsalajans yes, same same.
I'm sure @minhcasi & @trunghieuvn have a solution for this.

Looking forward!

**Comment by bikostudio** [comment]
Same here too

**Comment by juancamilocanal** [comment]
Also having problems on all login options

**Comment by Jegufull** [comment]
You need to verify purchase code to work with MStore Api
https://user-images.githubusercontent.com/63201901/79075769-62e0bb80-7d12-11ea-8cc3-af5eef425d95.jpg

**Comment by jeeali** [comment]
> You need to verify purchase code to work with MStore Api
> https://user-images.githubusercontent.com/63201901/79075769-62e0bb80-7d12-11ea-8cc3-af5eef425d95.jpg
> 
> <blockquote></blockquote>

I've already did this.

**Comment by juancamilocanal** [comment]
Ok thanks. This is new and was not on documentation. I'll try this.

**Comment by jeeali** [comment]
> You need to verify purchase code to work with MStore Api
> https://user-images.githubusercontent.com/63201901/79075769-62e0bb80-7d12-11ea-8cc3-af5eef425d95.jpg
> 
> <blockquote></blockquote>

I did this. I verified the purchase code in WordPress MStore API. And issue is resolved.
Thanks!

**Comment by bikostudio** [comment]
> 
> 
> > You need to verify purchase code to work with MStore Api
> > https://user-images.githubusercontent.com/63201901/79075769-62e0bb80-7d12-11ea-8cc3-af5eef425d95.jpg
> 
> I did this. I verified the purchase code in WordPress MStore API. And issue is resolved.
> Thanks!

Creating account solved by  verifying the purchase code. But please refer to this in documentation Thank you

**Comment by stanleyreubens** [comment]
> I've changed the Package Name and created a new project in Firebase and enabled the email, Google, Facebook login options. But not able to login/signup. Facing some weird issues.
> a. When I signup. It adds the user to the Firebase Project in the Authentication Tab.
> 
> <img alt="Screenshot 2020-04-25 at 6 23 54 PM" width="994" src="https://user-images.githubusercontent.com/17235314/80282299-1cd02280-872a-11ea-9421-40139e9fcf25.png">
> 
> b. But shows a SnakBar "Exception: Sorry, you are not allowed to do that."
> 
> <img alt="Screenshot 2020-04-25 at 6 23 54 PM" width="250" src="https://user-images.githubusercontent.com/17235314/80282248-e09cc200-8729-11ea-9dd1-15fb1287884f.png">
> 
> *Even, I tried to signup with the FluxBuilder's Demo App with my Website and Consumer Keys.
> 
> <img alt="Screenshot 2020-04-25 at 7 40 27 PM" width="1265" src="https://user-images.githubusercontent.com/17235314/80282740-a08b0e80-872c-11ea-8e7e-5f7f7f11c0b7.png">
> 
> c. And when I try to login with the recently signed-up email. It says "username or password incorrect".
> 
> <img alt="Screenshot 2020-04-25 at 6 23 54 PM" width="250" src="https://user-images.githubusercontent.com/17235314/80282276-032edb00-872a-11ea-9fd4-49c06eadad60.png">
> 
> What it is showing up on the Signup Tap.
> 
> <img alt="Screenshot 2020-04-25 at 7 23 34 PM" width="1102" src="https://user-images.githubusercontent.com/17235314/80282330-438e5900-872a-11ea-86b1-2aa5cd1b6a3f.png">
> 
> Please Help!
> 
> Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com
> 
> <img alt="Screenshot 2020-04-25 at 7 48 56 PM" width="619" src="https://user-images.githubusercontent.com/17235314/80282959-d250a500-872d-11ea-9d99-a812c74214f4.png">
> 
> I've filled the Google Form also.
> 
> _Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊_

Hello bro pls I need your help to setup the login and also how I can change the package name on android studio.. I will be glad if you can respond as soon as you can.. thank you

**Comment by ghanchi2000** [comment]
same issue with 1.7.4
