### ISSUE TITLE
How to connect the app with the opencart

### ISSUE THREAD

**Issue by prosenjeet123** [inspireui/support#2885]
Step 1 (require): detail issues and screenshots
I have already gone though all the steps but i am stuck in client key at the json where should i suppose to find it? also i have installed mstore in the website please please tell me what should i do next to connect my app with the store.

I am using opencart Version 3.0.3.2

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by prosenjeet123** [comment]
I have already filled the google doc let me know what else do you need to provide support

**Comment by minhtruong315** [comment]
@prosenjeet123 you dont need consumerKey and consumerSecret for opencart. you can check opencart config file in example folder.
