### ISSUE TITLE
 Mstore Pro Expo payment problem #2659

### ISSUE THREAD

**Issue by sajidgangat** [inspireui/support#2886]
Ticket 2659 Still having an issue.

After I click on the buy now button I am getting this error.

![Screen Shot 2020-04-26 at 6 56 56 AM](https://user-images.githubusercontent.com/22694841/80305552-5edd8080-878b-11ea-9fd5-941e905e0bd5.png)

I have done as directed and getting this error.

**Comment by luyx2412** [comment]
Hi @sajidgangat Please move to the Mstore Pro which will fix the issue or in `src/common/Tools.js` please add 
` 
static getItemsToCheckout = (cartItems) => {
    const items = [];
    for (let i = 0; i < cartItems.length; i++) {
      const cartItem = cartItems[i];
      const item = {
        product_id: cartItem.product.id,
        quantity: cartItem.quantity,
      };
      if (cartItem.variation !== null) {
        item.variation_id = cartItem.variation.id;
      }
      items.push(item);
    }
    return items;
  };
`
 same the screenshot to fix your issue.

![image](https://user-images.githubusercontent.com/8909619/80499063-b26fea00-8996-11ea-8170-15547f96e761.png)

Thanks
