### ISSUE TITLE
[FluxStore Pro] - Some Problems

### ISSUE THREAD

**Issue by bikostudio** [inspireui/support#2888]
**Hi,**

**In this new ticket will concentrate on the most important issues I want to fix as I want to publish my Woocommerce App as soon as possible.**

FluxShope Pro **ver1.6.6b**

**Environment's details:**
----------------------
Windows 8.1
Android Studio Latest Version
Flutter Latest Version
All Flutter and Dart plugins were installed
MStore API Plugin installed
--------------------------------
**Flutter doctor :**

![79006535-ac39db00-7b59-11ea-82dd-fad6f6eccf71](https://user-images.githubusercontent.com/62074493/80308147-8ce3b480-87cd-11ea-972e-c8a88a4cca3d.jpg)

**Comment by bikostudio** [comment]
[ Problem 1 ]  Error When Creating New Account

When I try to create a new account, I got this message. 
![2020-04-26_145609](https://user-images.githubusercontent.com/62074493/80308244-198e7280-87ce-11ea-9fb4-4ff53e329213.jpg)
 
BUT, The account created at Firebase only and not at Woocommerce site.

**Comment by bikostudio** [comment]
**### [ Problem 2 ] Cloud messages from Firebase not stored in Notify Messages page in the App.**

![79007430-7269d400-7b5b-11ea-962e-4a7a14637e97](https://user-images.githubusercontent.com/62074493/80308335-bbae5a80-87ce-11ea-9826-8cf50d4fe367.jpg)

**Comment by bikostudio** [comment]
**### [ Problem 3 ] Can not update current user profile**

![2020-04-26_155032](https://user-images.githubusercontent.com/62074493/80309487-ab4dae00-87d5-11ea-84cf-e9f936f0e34b.jpg)

**Comment by Jegufull** [comment]
You need to verify purchase code to work with MStore Api
https://user-images.githubusercontent.com/63201901/79075769-62e0bb80-7d12-11ea-8cc3-af5eef425d95.jpg

**Comment by bikostudio** [comment]
> 
> 
> You need to verify purchase code to work with MStore Api
> https://user-images.githubusercontent.com/63201901/79075769-62e0bb80-7d12-11ea-8cc3-af5eef425d95.jpg

Creating account solved by  verifying the purchase code. But please refer to this in documentation Thank you

**Comment by minhcasi** [comment]
@Jegufull @bikostudio - thank you for updating, we will also clarify detail from the mstore-api plugin

**Comment by bikostudio** [comment]
I have a question why you close issues before solving all problems? I still having problem with the cloud notifications!! 

> 
> 
> **### [ Problem 2 ] Cloud messages from Firebase not stored in Notify Messages page in the App.**
> 
> ![79007430-7269d400-7b5b-11ea-962e-4a7a14637e97](https://user-images.githubusercontent.com/62074493/80308335-bbae5a80-87ce-11ea-9826-8cf50d4fe367.jpg)

**Comment by bikostudio** [comment]
### [ Problem 3 ] Cloud messages from Firebase not stored in Notify Messages page in the App.
After installing 1.7.0

![2020-04-28_135106](https://user-images.githubusercontent.com/62074493/80484176-91d46f80-8957-11ea-8311-5696ad78ea5e.jpg)
