### ISSUE TITLE
Order completion gives error

### ISSUE THREAD

**Issue by bilalmunir1995** [inspireui/support#2889]
<img width="387" alt="Screenshot 2020-04-26 at 7 08 38 PM" src="https://user-images.githubusercontent.com/37571277/80310060-2329d180-87f2-11ea-8cc5-ef321bf052e8.png">
<img width="1127" alt="Screenshot 2020-04-21 at 6 16 14 AM" src="https://user-images.githubusercontent.com/37571277/80310066-3177ed80-87f2-11ea-9e01-1a22e98fa322.png">

**Comment by luyx2412** [comment]
Hi @bilalmunir1995 Can you uninstall app and reinstall again which will fix your issue. We will update next version to fix the issue.

Thanks

**Comment by bilalmunir1995** [comment]
This does not fix the issue and this is the second build from your end and i haven't been able to launch my app please send me a quick fix

**Comment by luyx2412** [comment]
Hi @bilalmunir1995 Can you share your config via inspireui.team@gmail.com. Let me investigate about it.

Thanks

**Comment by bilalmunir1995** [comment]
email done please check my email address is mister.bilalmunir@gmail.com

**Comment by luyx2412** [comment]
Hi @bilalmunir1995 I saw your email. And i am updating to fix this issue in next version ASAP.

Thanks

**Comment by abhiuee** [comment]
I am also facing the same issue, Can you please email how to download the next version as I need to get the app working as soon as possible ? When is the next version available ?

**Comment by akshaykumar04** [comment]
Hy @luyx2412, I am also facing the same issue...
![image](https://user-images.githubusercontent.com/25170390/80928563-ff065b80-8dc2-11ea-8482-3e6b0648f594.png)

**Comment by luyx2412** [comment]
Hi @abhiuee i am updating to fix the issue. And will have next version soon.

Thanks

**Comment by luyx2412** [comment]
Hi @akshaykumar04 @abhiuee We fixed this issue in next version. Please download latest version.

Thanks

**Comment by akshaykumar04** [comment]
Thanks, its working fine now!🙂
