### ISSUE TITLE
[FluxStore-MV]Vendor list not working 

### ISSUE THREAD

**Issue by EffectiveOG** [inspireui/support#2891]
Step 1 (require): detail issues and screenshots

![IMAGE 2020-04-26 16:45:07](https://user-images.githubusercontent.com/33296809/80312482-4ac26f00-87dd-11ea-893f-c6bdc7626526.jpg)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

![Screen Shot 2020-04-26 at 4 45 48 PM](https://user-images.githubusercontent.com/33296809/80312515-6b8ac480-87dd-11ea-9f90-f6e09a5e9b73.png)

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by philipvu30** [comment]
Hi,

May I ask what theme are you using? It seems your Rest API is not fully configured. 
If possible, please send me a support account of your site to this email: toan@inspireui.com. 
I need to make sure your configuration is correct or not. Thanks

**Comment by EffectiveOG** [comment]
im using rehub 9.9.4 
site: uzuri.spcae
admin access provided with the given email

**Comment by philipvu30** [comment]
@EffectiveOG 

Hi,

Have you done our step 2: "verify license and sharing config files via this google form - http://private.inspireui.com"? 

Because I don't see your config folder in our form. Also you don't give me the access to the plugin, would you mind giving me an image of what plugins you are currently using?

Thanks
