### ISSUE TITLE
[FluxStore Pro]Error in order with variable product, Urgent

### ISSUE THREAD

**Issue by Jegufull** [inspireui/support#2893]
Step 1 (require): detail issues and screenshots

Hello,

I have my app published in the app store and play store.

in this update the variable product is not working for me,

When the product is selected, it is added to the cart correctly, but when the item is ordered, the selected item does not come out. if not the one that is predetermined for the item.

please help me urgently.

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-26 at 23 38 59](https://user-images.githubusercontent.com/47310507/80334992-934b4e00-8818-11ea-93db-a4b354d2a9dc.png)

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-26 at 23 39 22](https://user-images.githubusercontent.com/47310507/80334997-98100200-8818-11ea-856f-a42ed600e171.png)

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-26 at 23 41 46](https://user-images.githubusercontent.com/47310507/80334998-98a89880-8818-11ea-99c2-67512d921cf1.png)

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-26 at 23 41 54](https://user-images.githubusercontent.com/47310507/80335000-99412f00-8818-11ea-8b96-902a73f56cc7.png)

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-26 at 23 42 23](https://user-images.githubusercontent.com/47310507/80335001-99d9c580-8818-11ea-9a24-e96c395f9c9b.png)

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-26 at 23 42 44](https://user-images.githubusercontent.com/47310507/80335002-99d9c580-8818-11ea-8263-2d43ae5ba152.png)

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-26 at 23 45 06](https://user-images.githubusercontent.com/47310507/80335004-9a725c00-8818-11ea-95eb-164408332a9e.png)

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-26 at 23 45 14](https://user-images.githubusercontent.com/47310507/80335005-9a725c00-8818-11ea-9e48-639b131e84ff.png)

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-26 at 23 45 26](https://user-images.githubusercontent.com/47310507/80335007-9a725c00-8818-11ea-929a-5de96cab9470.png)

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-26 at 23 45 59](https://user-images.githubusercontent.com/47310507/80335008-9b0af280-8818-11ea-92db-8eb38458a247.png)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhcasi** [comment]
@Jegufull - Thank you for reporting the issue -  could i confirm if this issue happens on 1.7.0 or 1.6.x?

**Comment by Jegufull** [comment]
@minhcasi 

The issue appears in both versions 1.6.6b and 1.7.0,  I already tried it in both

**Comment by minhcasi** [comment]
@Jegufull - thank you for quick response 

@philipvu30 - pls help to investigate this issue

**Comment by Jegufull** [comment]
@minhcasi 

I tried the variations of color, size and height, and it is not working correctly, when the order is made it takes the default product value, and not the one chosen in the app

Please help,

I also tried it in version 1.7.0 and it didn't work

**Comment by philipvu30** [comment]
Hi,

Your issue is currently under investigation. I'll let you know when it is fixed.

Thanks.

**Comment by Jegufull** [comment]
Hello, any update?

**Comment by philipvu30** [comment]
Hi,

It has been fixed and will be updated in 1-2 days.
