### ISSUE TITLE
Web-view Not loading in FluxStore Listing

### ISSUE THREAD

**Issue by Martinaude** [inspireui/support#2896]
Hi there, 

So I've dowloaded the FluxStore Listing app, and loving the layout features of the app. 
Im unfortunately having an issue with getting any WebView Content to display within the app.

Using the Flux builder i create the JSON File, and when uploading it to the app, I run it. 

When trying to access the tab where the Web-view should be, it simply reloads the "home" tab, and no webview content is shown. 

<img width="1799" alt="Screenshot 2020-04-27 at 11 41 17" src="https://user-images.githubusercontent.com/11926272/80358002-105bdf00-887c-11ea-8f7c-27ce75797479.png">

There is also no option or instruction in the Flex Builder to add video based content to the app - which was described in the info when downloading the app.

**Comment by Martinaude** [comment]
sorry, and the CE Builder no longer works with this V1.4.0 version of the app. 
<img width="1027" alt="Screenshot 2020-04-27 at 11 49 58" src="https://user-images.githubusercontent.com/11926272/80358785-3c2b9480-887d-11ea-957c-99e028dff963.png">

**Comment by minhcasi** [comment]
@Martinaude thank you for the questions

- Please copy the output json and check the demo on the simulator if you are using Webview, there is an issue so preview the Webview could be shown on the Desktop OS, you could use the real device or on ipad to Preview to webview

- Cebuilder is only supported for react native project
