### ISSUE TITLE
Magento adding configurable product to cart gives an error

### ISSUE THREAD

**Issue by bdairy** [inspireui/support#2897]
Step 1 (require): detail issues and screenshots

when adding a  configurable product to the cart,, it gives me this message that product options are missing..  It treats are the products as simple products.. even though the product is displayed as a configurable product.
![image](https://user-images.githubusercontent.com/10797121/80362004-8ebf7d80-888a-11ea-9e30-a0cf884a09ec.png)
![image](https://user-images.githubusercontent.com/10797121/80362129-c2020c80-888a-11ea-8087-8a10022d05a0.png)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhcasi** [comment]
@bdairy - could i know if you are testing on latest 1.7.x - thank you!

**Comment by minhtruong315** [comment]
@bdairy send me common and config folder via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/2897
<img width="401" alt="Screen Shot 2020-04-30 at 2 51 14 PM" src="https://user-images.githubusercontent.com/10402500/80685931-1e1a9a00-8af2-11ea-9079-59cc85e643d4.png">

**Comment by bdairy** [comment]
@minhtruong315 email is sent.. thanks

**Comment by minhtruong315** [comment]
<img width="906" alt="Screen Shot 2020-05-02 at 6 43 53 PM" src="https://user-images.githubusercontent.com/10402500/80863223-fd467600-8ca4-11ea-9a51-200450493127.png">
I checked rest api on your website. some api don't work. 
You need to check rest api on your website
https://devdocs.magento.com/guides/v2.3/rest/tutorials/orders/order-create-quote.html

**Comment by bdairy** [comment]
@minhtruong315  thanks for the reply,, I'll check with the backend guy about the APIs,, as. I understand from you, MStore plugin tries to to access these APIs and Fails..
Ok I'll look into that,, But any Idea about the other issue,, that asset icons are not showing,, yet the icons exists and in the right path.

**Comment by minhtruong315** [comment]
@bdairy can u send  me full your source code via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/2897
so that I can check asset icons  issue.
Thanks

**Comment by bdairy** [comment]
@minhtruong315  thanks for the reply, email has been sent with library folder, source code is huge,,, if you wish I can add you to the get repo..

**Comment by minhtruong315** [comment]
@bdairy it's better if you add me to your repo. minhtruong315@gmail.com

**Comment by bdairy** [comment]
@minhtruong315  done

**Comment by minhtruong315** [comment]
@bdairy can you  explain your issues? I see it's showing static icons
<img width="392" alt="Screen Shot 2020-05-06 at 2 13 25 PM" src="https://user-images.githubusercontent.com/10402500/81147118-d4272d80-8fa3-11ea-8029-d0b83cc039c3.png">

**Comment by bdairy** [comment]
@minhtruong315 In my case it wont show initially,, Until I perform a plenty of hot reloads and some navigation,,,, in versions before 1.7 it is working fine,,, on the original Flex Store source code it works fine,, only on my code it won't show directly,, even on native devices.. Was that screen shot taken instantly when u run the app,, ?? again I appreciate your patience.

**Comment by minhtruong315** [comment]
@bdairy you can try to clear cache
https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

**Comment by bdairy** [comment]
@minhtruong315  unfortunately no luck... This is weird...  I cannot even find it online... 
![image](https://user-images.githubusercontent.com/10797121/81250748-640fba80-902a-11ea-9d0e-2ef9c5f72f77.png)

**Comment by minhtruong315** [comment]
Can you try to build release to test?

**Comment by bdairy** [comment]
On release and test it is working,, although the assets flashes on the first run on the devise...which is quite unusual...BUt again I appreciate your efforts @minhtruong315 ...

On the other hand back to the original issue,, I see you have now 2 versions updated, is any update related to the these issues?? 

Thanks a million for your quick response.

**Comment by minhtruong315** [comment]
@bdairy We release new version, it fixed some issues and upgrade Flutter 1.17. if you upgraded flutter 1.17. You need to update the latest version on codecanyon.
Thanks for your feedback. Please give us some feedback/rating to this page https://codecanyon.net/downloads if the product is helpful for your business, we are working hard to update more awesome and powerful features on next coming version release. Let us know if you have any feedback. Thank you very much!
