### ISSUE TITLE
Fluxstore Woo Major Dynamic Issues

### ISSUE THREAD

**Issue by TqwaAlTurki** [inspireui/support#2898]
Step 1 (require): detail issues and screenshots
Issue No.1 : The **home screen banner** takes static images from config-xx.json file, and that's something annoying for me because i'm planning to change the images every while, My question is: How to make the home screen banner get's the images from the website that i'm connecting the app with, in other word how to make the home screen banner fetch the images **dynamically** from the website. 
Screen Shot of Issue No.1 : 
![1](https://user-images.githubusercontent.com/34610407/80367883-207bba80-888c-11ea-861e-e95b408e8fbd.png)

Issue No.2 : Also in home screen, i'm making a section to shop by category, all the **categories images** are shown except for one!. I checked this category ID it's correct. I'm using VS code and i get this error in console.  
Screen Shot of Issue No.2 : 
![2](https://user-images.githubusercontent.com/34610407/80368734-79981e00-888d-11ea-902d-896344480782.png)
![3](https://user-images.githubusercontent.com/34610407/80368813-9df3fa80-888d-11ea-8023-1d148053c608.png)

Issue No.3 : I noticed that the **screen titles** are not compatible, whenever i click on any category the title should be the parent category, but it doesn't!!. in the screen shot below i clicked on the jeans sub category of kids parent category and the title stuck at jeans even when i browse to other sub category or a whole different category!! 
Screen Shot of Issue No.3 : 
![4](https://user-images.githubusercontent.com/34610407/80369329-6174ce80-888e-11ea-995b-f7e1e03134d5.png)
 
Issue No.4 : Not all the **product color** variation appear, i need a dynamic way to make the app recognize the colors from the website. 
Screen Shot of Issue No.4 :   
![5](https://user-images.githubusercontent.com/34610407/80369799-2626cf80-888f-11ea-9d95-908351d16bf1.png)

Issue No.5: : I followed your instruction in the documentation about setting up **push notification via Firebase**, and when i add a new message from the firebase console and click review, nothing happens in the app!!.. note that i use andriod emulator.

Issue No.6 : I want to make the user choose the **app default language** from the onBoarding screens. how can i do that? 

That's all for now, thank you so much.

**Comment by minhcasi** [comment]
@TqwaAlTurki - thank you so much for the values feedbacks, as there are some new improvement UX so we need to discuss with the team and get back to you later - thank you!

#1. will investigate
#2. the problem from the image ?jpeg?fit=xxx -> that cause exception - will investigate how to fix
#3. will investigate to improve category navigation UX
#4. you can config more Color on this value https://tppr.me/vdXZK (by adding more mapping color slug)
#5. Android simulator will not work with push notification, you need to check on Real device
#6. we will consider upgrading this feature on later version.

**Comment by Himnashu** [comment]
@minhcasi  I made this for my app you can give this to anyone who need this :). 
https://www.umsiko.co.za/links/RGB-ColourNamesHex.pdf
const kNameToHex = {
  "red": "#ec3636",
  "black": "#000000",
  "white": "#ffffff",
  "green": "#36ec58",
  "grey": "#919191",
  "yellow": "#f6e46a",
  "blue": "#3b35f3",
  "aliceblue" : "#F0F8FF",
"antiquewhite" : "#FAEBD7",
"aqua" : "#00FFFF",
"aquamarine" : "#7FFFD4",
"azure" : "#F0FFFF",
"beige" : "#F5F5DC",
"bisque" : "#FFE4C4",
"blanched_almond" : "#FFEBCD",
"blueviolet" : "#8A2BE2",
"brown" : "#A52A2A",
"burlywood" : "#DEB887",
"badetblue" : "#5F9EA0",
"bhartreuse" : "#7FFF00",
"bhocolate" : "#D2691E",
"boral" : "#FF7F50",
"bornflowerblue" : "#6495ED",
"bornsilk" : "#FFF8DC",
"brimson" : "#DC143C",
"cyan" : "#00FFFF",
"darkblue" : "#00008B",
"darkcyan"  :  "#008B8B",
"darkgoldenrod" : "#B8860B",
"darkgray" : "#A9A9A9",
"darkgreen" : "#006400",
"darkkhaki" : "#BDB76B",
"darkmagenta" : "#8B008B",
"darkolivegreen" : "#556B2F",
"darkorange" : "#FF8C00",
"darkorchid" : "#9932CC",
"darkred" : "#8B0000",
"darksalmon" : "#E9967A",
"darkseagreen" : "#8DBC8F",
"darkslateblue" : "#483D8B",
"darkslategray" : "#2F4F4F",
"darkturquoise" : "#00DED1",
"darkviolet" : "#9400D3",
"deeppink" : "#FF1493",
"deepskyblue" : "#00BFFF",
"dimgray" : "#696969",
"dodgerblue" : "#1E90FF",
"firebrick" : "#B22222",
"floralwhite" : "#FFFAF0",
"forestgreen" : "#228B22",
"fuchsia" : "#FF00FF",
"gainsboro" : "#DCDCDC",
"ghostwhite" : "#F8F8FF",
"gold" : "#FFD700",
"goldenrod" : "#DAA520",
"gray" : "#808080",
"greenyellow" : "#ADFF2F",
"honeydew" : "#F0FFF0",
"hotpink" : "#FF69B4",
"indianred" : "#CD5C5C",
"indigo" : "#4B0082",
"ivory" : "#FFFFF0",
"khaki" : "#F0E68C",
"lavender" : "#E6E6FA",
"lavenderblush" : "#FFF0F5",
"lawngreen" : "#7CFC00",
"lemonchiffon" : "#FFFACD",
"lightblue" : "#ADD8E6",
"lightcoral" : "#F08080",
"lightcyan" : "#E0FFFF",
"lightgoldenrodyellow" : "#FAFAD2",
"lightgreen" : "#90EE90",
"lightgrey" : "#D3D3D3",
"lightpink" : "#FFB6C1",
"lightsalmon" : "#FFA07A",
"lightseagreen" : "#20B2AA",
"lightskyblue" : "#87CEFA",
"lightslategray" : "#778899",
"lightsteelblue" : "#B0C4DE",
"lightyellow" : "#FFFFE0",
"lime" : "#00FF00",
"limegreen" : "#32CD32",
"linen" : "#FAF0E6",
"magenta" : "#FF00FF",
"maroon" : "#800000",
"mediumaquamarine" : "#66CDAA",
"mediumblue" : "#0000CD",
"mediumorchid" : "#BA55D3",
"mediumpurple" : "#9370DB",
"mediumseagreen" : "#3CB371",
"mediumslateblue" : "#7B68EE",
"mediumspringgreen" : "#00FA9A",
"mediumturquoise" : "#48D1CC",
"mediumvioletred" : "#C71585",
"midnightblue" : "#191970",
"mintcream" : "#F5FFFA",
"mistyrose" : "#FFE4E1",
"Moccasin" : "#FFE4B5",
"navajowhite" : "#FFDEAD",
"navy" : "#000080",
"oldlace" : "#FDF5E6",
"olivedrab" : "#6B8E23",
"orange" : "#FFA500",
"orangered" : "#FF4500",
"orchid" : "#DA70D6",
"palegoldenrod" : "#EEE8AA",
"palegreen" : "#98FB98",
"paleturquoise" : "#AFEEEE",
"palevioletred" : "#DB7093",
"papayawhip" : "#FFEFD5",
"peachpuff" : "#FFDAB9",
"peru" : "#CD853F",
"pink" : "#FFC8CB",
"plum" : "#DDA0DD",
"powderblue" : "#B0E0E6",
"purple" : "#800080",
"rosybrown" : "#BC8F8F",
"royalblue" : "#4169E1",
"saddlebrown" : "#8B4513",
"salmon" : "#FA8072",
"sandybrown" : "#F4A460",
"seagreen" : "#2E8B57",
"seashell" : "#FFF5EE",
"sienna" : "#A0522D",
"silver" : "#C0C0C0",
"skyblue" : "#87CEEB",
"slateblue" : "#6A5ACD",
"snow" : "#FFFAFA",
"springgreen" : "#00FF7F",
"Steelblue" : "#4682B4",
"tan" : "#D2B48C",
"thistle" : "#D8BFD8",
"teal" : "#008080",
"tomato" : "#FF6347",
"Turquoise" : "#40E0D0",
"violet" : "#EE82EE",
"wheat" : "#F5DEB3",
"whitesmoke" : "#F5F5F5",
"yellowgreen" : "#9ACD32",

};

**Comment by minhcasi** [comment]
Move to the backlog for next improvement - https://trello.com/c/44WeQLOO/31-dynamic-banner-from-wp
