### ISSUE TITLE
Error when choosing Pay.

### ISSUE THREAD

**Issue by omarsawalhah** [inspireui/support#2899]
Step 1 (require): detail issues and screenshots

I disabled Address, review and when try to make a payment I get an error
here is config.dart section 
"IsRequiredLogin": false,
  "GuestCheckout": false,
  "EnableShipping": false,
  "EnableAddress": false,
  "EnableReview": false,
  "GridCount": 3,

<img width="1288" alt="Screen Shot 2020-04-27 at 5 26 59 PM" src="https://user-images.githubusercontent.com/2116277/80383579-6ba5c580-88ac-11ea-9ef5-55258f908e82.png">

**Comment by minhcasi** [comment]
@omarsawalhah - pls help us to provide more verify purchase info to http://private.inspireui.com/ - thank you!
