### ISSUE TITLE
Set Up

### ISSUE THREAD

**Issue by agriffyn** [inspireui/support#29]
**Mandatory Info (please complete the following information):**
 - Product: [MStore Multi Vendor IOS]
 - Your Purchased Code: [446143c0-53ec-41bd-a1c9-29f30bcbe3fd]
(we may not reply if you are not our customer)

**Describe the issues**
I am having an issue setting up the app, I understand the wordpress etc but the first part about nodejs, yarn etc I do not understand. So I have xcode with its simulator, now I need to download an app called "NodeJS"? What do I do after that, do I need to run or install something called yarn? Then I need to download something called XDE? When will I need to use these and what do I need them for, can I just configure it all through wordpress? Sorry I am not experienced with these programs, thank you.

**Screenshots**

**Additional context**
Add any other detail logs about the problem here.

**Comment by thangvo9x** [comment]
Hi.  First, You must install nodejs, https://nodejs.org/en/
then install yarn (https://yarnpkg.com/en/docs/install#mac-stable) 
install expo-cli with run this cmd " yarn global add expo-cli"
open your project and run "yarn install"  then "expo start"

**Comment by minhcasi** [comment]
@agriffyn let us know if you still have the problem then reopen the ticket - thank you!
