### ISSUE TITLE
[CeBuilder] I am getting error while installing tools

### ISSUE THREAD

**Issue by akbarfu1234** [inspireui/support#290]
Hi i am getting this error, please check (https://ibb.co/F6hGkt6)

**Comment by luyx2412** [comment]
Hi @akbarfu1234 Please follow the template issue to reproduce issue easier.
https://github.com/inspireui/support/blob/master/.github/ISSUE_TEMPLATE/report-installing-issues.md

Thanks

**Comment by akbarfu1234** [comment]
This is my Purchase code: fd6e8992-ad20-495f-9b1a-fa60765b990a

Please see the link:  https://ibb.co/F6hGkt6

**Comment by akbarfu1234** [comment]
This is my Purchase code: fd6e8992-ad20-495f-9b1a-fa60765b990a

Please see the link: https://ibb.co/F6hGkt6

**Comment by minhcasi** [comment]
@akbarfu1234 - could i check if you are using the window 10? the ceBuilder on support on the window 10 version and above

You may run it manually by using the expo tool from the document guide

**Comment by akbarfu1234** [comment]
I am using windows 7

**Comment by akbarfu1234** [comment]
Can you give me link of expo

**Comment by minhcasi** [comment]
Please check this link - https://expo.io/tools

You can use this script for installing: npm install expo-cli -g
