### ISSUE TITLE
Fluxstore woocommerce - NativeOnePageCheckout

### ISSUE THREAD

**Issue by rodrigoalves1901** [inspireui/support#2900]
![image](https://user-images.githubusercontent.com/43248152/80385747-72b0e180-8874-11ea-990f-9ce4de668de6.png)

Good Morning. I tested the new functionality and it seems that for my store it doesn't work. I saw that in yours it worked. Do you have any other settings to do besides activating NativeOnePageCheckout?

![image](https://user-images.githubusercontent.com/43248152/80386293-316d0180-8875-11ea-9b67-6bfacae27f53.png)

**Comment by minhcasi** [comment]
@rodrigoalves1901 - could you help to test with the latest version, 1.7.0 - we have updated some payment issues on this release - thank you!

**Comment by rodrigoalves1901** [comment]
I am using version 1.7.0. Even NativeOnePageCheckout only appeared in version 1.7.0 correct?

**Comment by minhtruong315** [comment]
@rodrigoalves1901 can u send me common folder and admin account to login your website via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/2900
I will help you check this issue
Thanks

**Comment by rodrigoalves1901** [comment]
ok i already sent

**Comment by rodrigoalves1901** [comment]
Hello, I've solved my problem. Thank you
