### ISSUE TITLE
Blog don't appear 

### ISSUE THREAD

**Issue by Roupasafricanas** [inspireui/support#2901]
Step 1 (require): detail issues and screenshots
![80271891-337b6880-869b-11ea-9558-4f4e5ee0e237](https://user-images.githubusercontent.com/63840938/80401587-f679c680-8892-11ea-8d91-35c257374fa1.jpg)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

Ola. Eu já atualizei a nova versão mas os problemas continuam. 
1- O blog do meu site não aparece. Aparece na demo com a fluxstore, aparece no flux builder mas quando instalo no meu site, não aparece. Como posso solucionar isso pfv?
![IMG_20200427_143500](https://user-images.githubusercontent.com/63840938/80402499-5cb31900-8894-11ea-9878-b58435157a4f.jpg)
![IMG_20200427_143441](https://user-images.githubusercontent.com/63840938/80402502-5f157300-8894-11ea-9774-f27397c62b9f.jpg)
![IMG_20200427_143242](https://user-images.githubusercontent.com/63840938/80402504-5fae0980-8894-11ea-9434-270de8fa0a20.jpg)

2- Quando adiciono o cupom de desconto, aparece a seguinte mensagem 
![Screenshot_2020-04-27-03-20-17-667_com inspireui fluxstore](https://user-images.githubusercontent.com/63840938/80402595-7f453200-8894-11ea-882d-8bbf54ab5fc8.jpg)

**Comment by minhcasi** [comment]
@Roupasafricanas - could I check if you have update to the latest  Fluxstore 1.7.0 ? Thank you!

**Comment by Roupasafricanas** [comment]
Good night. It's still not showing up even though I've upgraded to version 1.7.0. I need to resolve this issue quickly before I can publish my app.
I saw a "Get_blog" folder and I don't know if something should be set up inside the folder. 
Please, don't forget me

**Comment by minhcasi** [comment]
@Roupasafricanas - could you try to install this plugin - https://wordpress.org/plugins/better-rest-api-featured-images/ - see if the blog is displayed

Also make sure you have run the Regenerate image as this guide https://docs.inspireui.com/fluxstore/woocommerce-setup/#step-2-install-the-required-plugins
