### ISSUE TITLE
Address in checkout

### ISSUE THREAD

**Issue by Shiru-kun** [inspireui/support#2902]
Step 1 (require): detail issues and screenshots
when an user writes his address and it doesnt match the exactly address from my website it fails.  and i cant place my order (im using the webview payment). 
can i have a dropdown for my provinces?

![WhatsApp Image 2020-04-27 at 20 53 57](https://user-images.githubusercontent.com/54008441/80409961-0660cd00-88ca-11ea-859b-8d682ce6c799.jpeg) 

![WhatsApp Image 2020-04-27 at 20 53 43](https://user-images.githubusercontent.com/54008441/80409957-04970980-88ca-11ea-9f29-bedde90b35fd.jpeg)

 

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhcasi** [comment]
@Shiru-kun - could you help to translate the red warning message? Please take the screenshot from the Shipping config so that we could check for investigating. 

Could you able to process successfully on the same Address on website?

**Comment by Shiru-kun** [comment]
Billing address is not valid, 
Please insert one as followed: Maputo , Cabo Delgado.... 


Space for screenshot


....



I can’t successfully process with the address on the website. 



Focas Kandulo 
+258 844218050

**Comment by minhcasi** [comment]
@Shiru-kun - as you could not process on Website, it mean there is an issue when you config the WooCommerce shipping - try to update the setting from Woo - ex: https://tppr.me/Ys4UA

**Comment by Shiru-kun** [comment]
I already have it working on the web version, using plugin WC City Select by 8manos. I would like to know if you could have a look to add it to the app because its a requirement on my website, where it will give an error if he does not type the correct address. and i already added a new state to lib/common/states how can i put this list of states to the widget and which widget??
there is a way i can add a dropdown with my own states??

**Comment by Shiru-kun** [comment]
never mind its working...
