### ISSUE TITLE
Can't push to github

### ISSUE THREAD

**Issue by michaelbrinkworth** [inspireui/support#2904]
FluxStore Errors installing #1981
 

I am trying to push local project to github to share with friend but somehow it keeps being pushed to yours even though I created a remote, local respiratory etc.

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhcasi** [comment]
@michaelbrinkworth - pls try your own private Github or Gitlab repo and don't share it as public 

Let us know if you have any further question - thank you! :)
