### ISSUE TITLE
mstore-api error

### ISSUE THREAD

**Issue by victormtz8** [inspireui/support#2905]
Step 1 (require): detail issues and screenshots

when i try to activaed mstore-api there's a error 

![Screen Shot 2020-04-27 at 7 22 58 PM](https://user-images.githubusercontent.com/10205285/80440071-cf37ef00-88bc-11ea-8e1e-72720e59e577.png)

FluxStore Listing - The Best Directory WooCommerce app by Flutter

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

i already did

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhcasi** [comment]
@victormtz8 - sorry for confusion, if you are using Fluxstore Listing then only update the Listapp Mobile Manger plugin - thank you!

**Comment by victormtz8** [comment]
Thanks
