### ISSUE TITLE
[Fluxstore MV] - Add text to the tab icons

### ISSUE THREAD

**Issue by ideas24** [inspireui/support#2906]
Step 1 (require): detail issues and screenshots
Please how do I add text to the Tab Icons to indicate 
Home
Categories 
Search etc.
Thanks 

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhcasi** [comment]
Hi, could you use this tabbar and add "label": "Home" ... to the config json to display the tab, we will also include this fix on next release - thank you!

[tabbar.dart.txt](https://github.com/inspireui/support/files/4569637/tabbar.dart.txt)

**Comment by minhcasi** [comment]
<img width="1096" alt="Screen Shot 2020-05-03 at 11 55 21" src="https://user-images.githubusercontent.com/1459805/80899019-f9facb00-8d34-11ea-9232-b0c875b3da8c.png">

**Comment by ideas24** [comment]
@minhcasi Thank You very much

**Comment by minhcasi** [comment]
we're glad that it help, please give us some feedback/rating to this page https://codecanyon.net/downloads  if the product is helpful for your business, we are working hard to update more awesome and powerful features on next coming version release. Let us know if you have any feedback. Thank you very much!

**Comment by ideas24** [comment]
@minhcasi DONE! Awesome product !
