### ISSUE TITLE
rest api not working and product images not working 

### ISSUE THREAD

**Issue by samz29** [inspireui/support#2907]
my application does not display products and images, in fluxbuilder rest api not working and product images not working
![photo_2020-04-28_10-29-06](https://user-images.githubusercontent.com/60650955/80444161-33999380-893b-11ea-85af-f351c63a61d6.jpg)
![photo_2020-04-28_10-29-03](https://user-images.githubusercontent.com/60650955/80444180-414f1900-893b-11ea-9ffb-29f179f0734b.jpg)

**Comment by minhcasi** [comment]
@samz29 - pls help to check if your Woocommerce REST API is working fine - https://docs.inspireui.com/fluxstore/woocommerce-setup/#step-1-setup-rest-api ? - thank you!

**Comment by samz29** [comment]
my api rest is work in woocommerce
![2020-04-28 20 02 32](https://user-images.githubusercontent.com/60650955/80490223-3e7c1480-898b-11ea-8cf4-912ec3c4228e.jpg)

**Comment by samz29** [comment]
This happens when the fluxstore updates the new mstore, my application yesterday functions and is just fine, and has been uploaded to the Play Store

**Comment by samz29** [comment]
![Screen Shot 2020-04-28 at 20 16 51](https://user-images.githubusercontent.com/60650955/80491667-3c1aba00-898d-11ea-87a5-e1ae2af2c121.png)
