### ISSUE TITLE
[Beonews 3.0.6] related categories does not reload everytime i open new post?

### ISSUE THREAD

**Issue by robertwt7** [inspireui/support#2908]
Step 1 (require): detail issues and screenshots

The categories <RelatedPost> component in beonews does not load the related posts?

```
		if (
			typeof this.props.related === "undefined" ||
			this.props.related.length === 0
		) {
			this.props.fetchPostsRelated(
				this.page,
				this.postCurrent.categories[0],
				this.postCurrent
			);
		}
```

I found that code at ComponentDidMount, already tried to put it outside the if to make sure it keep reloading everytime I open a post. But then its still stuck with the first related post of a post that I open. 

For instance, if i open a post related to Play categories at first time I opened the app. Then the related posts will always be Play categories related. It will never change during my session even if I open another post with other category

What should I do?

**Comment by luyx2412** [comment]
Hi @robertwt7 You can remove `if` same the screenshot and it will fix your issue.
![image](https://user-images.githubusercontent.com/8909619/80498486-fb736e80-8995-11ea-9adf-8cf29bfb7abe.png)

Thanks

**Comment by robertwt7** [comment]
It doesn't apparently because the componentDidMount was only called once. I managed to get it done with onDidFocus for react navigation because it runs everytime a component is navigated to
