### ISSUE TITLE
[Mstore Pro] Issue while checkout and payment gateway

### ISSUE THREAD

**Issue by rajbonsa** [inspireui/support#291]
- Product: [MStore Pro]
 - USer: rajbonsa
 
**Describe the bug**
There is a problem while pay with razorpay the page showing form filled with address details saying that (Unfortunately we do not deliver to "Country") i tried with all other countries but same issue occurred.

**Screenshots**
Screenshot attached for your reference.

![screenshot_20190211-163109](https://user-images.githubusercontent.com/47560631/52632481-b7f32880-2ee7-11e9-9ec3-4515dded2e77.png)

**Comment by rajbonsa** [comment]
In our MStore demo app also has a same issue while using razorpay

**Comment by luyx2412** [comment]
Hi @rajbonsa Can you provide your Mstore version?

Thanks

**Comment by rajbonsa** [comment]
V3.6.8

**Comment by rajbonsa** [comment]
Hi, u can check with MStore Pro demo app, there itself same error. "Unfortunately we do not ship to India" or any countries...

**Comment by luyx2412** [comment]
Hi @rajbonsa Can you provide AppConfig.json and Config.js file?

Thanks

**Comment by rajbonsa** [comment]
Hi, you can find the app credentials from my wordpress with below
credentials:

Wordpress link: https://amburoutlet.hyfetech.com/wp-login.php
username: admin
Password: 123456

**Comment by luyx2412** [comment]
Hi @rajbonsa I need the AppConfig.json and Config.js file in your folder MStore code without your wordpress admin.

Thanks

**Comment by rajbonsa** [comment]
Hi, you would have ask while i posted WordPress admin credentials , why you are taking so much time to reply.
I am sharing 2 files now (config and appconfig in zip format) Thanks

[config.zip](https://github.com/inspireui/support/files/2867688/config.zip)

**Comment by rajbonsa** [comment]
Hi luyx, when it will be done?

**Comment by rajbonsa** [comment]
Any update?!!

**Comment by luyx2412** [comment]
Hi @rajbonsa Sorry about reply late. We fixed and will update next version. 

Thanks
