### ISSUE TITLE
Mstore payment y refund

### ISSUE THREAD

**Issue by David9192** [inspireui/support#2910]
Step 1 (require): detail issues and screenshots

hello the problem is that I need to activate and put a function in the mstore application for the native payment of paypal and stripe since the system now with vkview does not work has many errors please I need to get the native payment to work.  Also please and I bought by mistake the flutter store pro as you see in the photo and I need a refund since I do not program and also do not need it I thought that it would fix my problems and it was worse please I already bought mstore and I do not need the other app flutter store  Pro. Thanks

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

Mi email cleaningdpro@gmail.com

![54E8481A-C590-4B6A-B0E3-51AC43152BE5](https://user-images.githubusercontent.com/39241693/80477852-a5adb080-891a-11ea-8b27-dd719c55b387.png)

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhcasi** [comment]
@David9192 - could you help to update the rating? Thanks

**Comment by David9192** [comment]
ok update already but i need support and refund

ok update already but i need support and refund
https://github.com/inspireui/support/issues/2910

**Comment by minhcasi** [comment]
@David9192 - pls submit on this link https://help.market.envato.com/hc/en-us/articles/202821460-Can-I-Get-A-Refund- - thanks

**Comment by David9192** [comment]
I already made the request again check it please thank you

**Comment by David9192** [comment]
I already filled out the refund application twice and you could see it.
Also please I need to know if someone is going to help me with the mstore
problem

https://github.com/inspireui/support/issues/2910

**Comment by David9192** [comment]
Hello, I am writing to you again and quite unhappy since a week ago I requested a solution for Mstore and nobody was able to listen to me.  I opened a refund on this platform twice and no one has cared even my refund case doesn't even appear and it is not the first time that this platform keeps my money.  I need an urgent refund since the mstore application does not work as described and has quite a few problems which nobody takes care of.  I ask for a little respect from this themeforest platform and from the developer.  Thank you

**Comment by David9192** [comment]
Hello, I am writing to you again and quite unhappy since a week ago I
requested a solution for Mstore and nobody was able to listen to me.  I
opened a refund on this platform twice and no one has cared even my refund
case doesn't even appear and it is not the first time that this platform
keeps my money.  I need an urgent refund since the mstore application does
not work as described and has quite a few problems which nobody takes care
of.  I ask for a little respect from this themeforest platform and from the
developer.  Thank you

**Comment by minhcasi** [comment]
refunded
