### ISSUE TITLE
New Language: German language added

### ISSUE THREAD

**Issue by kumsalajans** [inspireui/support#2911]
I think adding a new language would be great for the project

Please accept the merge request.

![image](https://user-images.githubusercontent.com/63232893/80487025-d1ee1f00-8964-11ea-9993-41888848c67a.png)

**Comment by minhcasi** [comment]
@kumsalajans - thank you so much for your help - we will upgrade it on the next release - very best!

**Comment by minhcasi** [comment]
updated to 1.7.1
