### ISSUE TITLE
View and language files were separated

### ISSUE THREAD

**Issue by kumsalajans** [inspireui/support#2912]
The view and language files were separated to fix language problems that occurred during the version update.

Please accept the merge request. Because we have to translate on multiple files with every update

![image](https://user-images.githubusercontent.com/63232893/80487197-18437e00-8965-11ea-8041-36adb3c8ec97.png)

**Comment by minhcasi** [comment]
@kumsalajans - we will review the MR and get back you later - thank you for your contribute

**Comment by minhcasi** [comment]
updated to 1.7.1
