### ISSUE TITLE
Fluxstore Woocommerce- MStore purchase code 

### ISSUE THREAD

**Issue by Tifahhh** [inspireui/support#2913]
Hi all,  im having an issue with the MStore plugin. 
When i read the guides, i saw most people have a section to paste their purchase code.

Im not seeing this, am i doing something wrong?

This is what im seeing
https://pasteboard.co/J5TXmpj.png

instead of
https://user-images.githubusercontent.com/63201901/79075769-62e0bb80-7d12-11ea-8cc3-af5eef425d95.jpg

Sorry im a bit new.

**Comment by minhcasi** [comment]
@Tifahhh - thank you for the question, it could be because you are an old version of mstore-api - please help to upgrade the latest one.

We will upgrade more feature on the mstore-api to support more features for this plugin.

Let us know if you have any questions, thank you!

**Comment by Tifahhh** [comment]
i upgraded to the latest version and its stil the same problem.
please help @minhcasi
