### ISSUE TITLE
string (57): “Invalid authentication cookie. Please try to login again.

### ISSUE THREAD

**Issue by magic-coding** [inspireui/support#2914]
**Step 1 (require):** detail issues and screenshots

on checkout at the last step I got this error: string (57): “Invalid authentication cookie. Please try to login again.

I try to log in several times but still, the same message appears.

We use the latest mStore plugin on WordPress.Also, we do fully customize to the app so we can’t download the new version because it’s difficult to overwrite our code again.

I see this error message on the console:
**No route was found matching the URL and request method.**

![IMG_9574](https://user-images.githubusercontent.com/15148391/80491401-b76f7200-8973-11ea-90e6-a8ff2cacbd46.PNG)

**Comment by minhcasi** [comment]
@minhtruong315 - pls help for suggestion - thank you!

**Comment by minhcasi** [comment]
@magic-coding - in the meantime could you try to check the latest source code if you have the same issue ? This could be about the login issue that not store user info

**Comment by osama-157** [comment]
@minhcasi am facing the same issue 
after digging around whenever i try to call user data and id it returns null .
even though the firebase authentication sends the otp and authenticates the user but when i print the user data its null always null

**Comment by minhcasi** [comment]
@magic-coding @osama-157 pls also try to update the mstore-api plugin to the latest version

**Comment by magic-coding** [comment]
@minhcasi We use the latest Version 2.3.9 .

**Comment by mastermined** [comment]
I am also getting same issue, it was working fine previously.

**Comment by mastermined** [comment]
I manage to go through, I re-installed app and user logged in already in app does not exist in my WP website. I simply logged out and logged in back issue resolved, that makes sense why it didnt find user

**Comment by minhcasi** [comment]
@magic-coding - sorry i mean the Fluxstore 1.7.x ? are you using this latest version?
