### ISSUE TITLE
[FluxListing] Whatsapp link can't click

### ISSUE THREAD

**Issue by gartional** [inspireui/support#2915]
![WechatIMG141](https://user-images.githubusercontent.com/41742783/80492565-dddddf00-896c-11ea-9e46-62fc685be896.jpeg)

**Comment by philipvu30** [comment]
Hi,

Please verify license and sharing config files by submitting on this google form, http://private.inspireui.com, In this way your private config, license detail or any credential will be protected and kept private, then it will be removed up after we resolved the ticket.

Thank you for using our product.

**Comment by philipvu30** [comment]
Hi,

Please install Whatsapp app. Otherwise, the link cannot be opened.

**Comment by gartional** [comment]
Installed and use it everyday

在 2020年5月4日星期一，philipvu30 <notifications@github.com> 写道：
