### ISSUE TITLE
[FluxStore Pro] Various Problems

### ISSUE THREAD

**Issue by kumsalajans** [inspireui/support#2916]
Firstly, i use the latest release shared gitlab ([link](https://gitlab.com/inspireui/fluxstore-pro/-/commit/1bdd1ff3b885b1dbc6a20fd8b495bf354442bf87))

### **1. Whatsapp Only iOS problem, working on Android**
![IMG_4228](https://user-images.githubusercontent.com/63232893/80489116-0adbc300-8968-11ea-8b6d-eeeafe3dd006.PNG)

### **2. Apple Sign In**
![IMG_4211](https://user-images.githubusercontent.com/63232893/80489175-1d55fc80-8968-11ea-9a00-dcc4c45e769b.PNG)

### **3. Coupon Code Problem (Woo Commerce) (Type: Fixed card discount)**

Fixed card discount is selected but it applies the same discount to every product, this is causing the problem.

![IMG_4230](https://user-images.githubusercontent.com/63232893/80489672-d9172c00-8968-11ea-9913-016adf762036.PNG)
![image](https://user-images.githubusercontent.com/63232893/80489904-33b08800-8969-11ea-907c-b1b1b0b1dff7.png)
![image](https://user-images.githubusercontent.com/63232893/80490087-825e2200-8969-11ea-9742-5e670a394bd5.png)

### **4. Adding to the basket problem for non-variant products **
(lib/widgets/frameworks/product_variant_mixin.dart)

The isUpdateVariationDone variable returns incorrectly on non-variant products

![Screenshot_20200428-160831](https://user-images.githubusercontent.com/63232893/80491093-ed5c2880-896a-11ea-84c8-846de628e134.jpg)

### **5. adding products to basket, without selecting a variant **

When you add the variant product to the basket from the list, the variant does not appear on the basket page. 

When added from the second picture below, the third picture does not show a variant. It should be detailed that it cannot be added without selecting a variant. The same problem can be added from the product detail without selecting the variant.

this is about the fourth problem

![IMG_4233](https://user-images.githubusercontent.com/63232893/80494657-94db5a00-896f-11ea-8c97-1f8c4e22faeb.png)
![IMG_4236](https://user-images.githubusercontent.com/63232893/80494686-9efd5880-896f-11ea-86aa-9272b8b8ceb5.png)
![IMG_4237](https://user-images.githubusercontent.com/63232893/80494698-a3c20c80-896f-11ea-9d21-ee3ccf531f2b.png)

It should be like this

![IMG_4234](https://user-images.githubusercontent.com/63232893/80495198-47abb800-8970-11ea-942a-3c339a55c6c8.png)

### **6. Input double tap problem Only iOS problem, working on Android**

![IMG_4239](https://user-images.githubusercontent.com/63232893/80499385-960f8580-8975-11ea-93bb-59f7427eac51.PNG)

**Comment by minhcasi** [comment]
@philipvu30 - pls help for investigating - thank you!

**Comment by philipvu30** [comment]
Hi,

Some of these issues are being investigated. I'll get back to you as soon as they're done. 

Thanks.

**Comment by kumsalajans** [comment]
Hi @minhcasi & @philipvu30 ,

When can you get back to us with these errors?

AppStore does not accept the latest version of your application. There is a job we need to deliver to our customer.

Thank you for your understanding and help.

**Comment by minhcasi** [comment]
Some below issues are fixed on 1.7.2
1. fixed
2. pls enable this setting on Firebase - https://tppr.me/JmDVO
3. will upgrade Discount feature
4. fixed
5. fixed - we will disable the adding "product variant" from product list to prevent this issues, only allow simple product could be add
6. can not reproduce on latest code

**Comment by minhcasi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improve Coupon Code](https://trello.com/c/JMGcLVhR/35-improve-coupon-code)

**Comment by minhcasi** [comment]
moved to backlog to upgrade the Coupon feature
