### ISSUE TITLE
Order notes no longer showing after update

### ISSUE THREAD

**Issue by drew1607** [inspireui/support#2917]
![Screen Shot 2020-04-28 at 17 17 51](https://user-images.githubusercontent.com/26347213/80505234-5ac08700-8974-11ea-9a2f-2a69909a91c2.png)

Hi, Please check this on your end ###Update – upgrade the Billing Address screen, also save long/lat to Order note (WooCommerce) ## Order notes are no longer showing on orders after the recent update and not sure how “also save long/lat to Order note” will be triggered …..my guess is the “search address”? Please help with a fix. Thanks

**Comment by minhtruong315** [comment]
@drew1607 I dont understand your issue. can u help me record screen?
Thanks

**Comment by drew1607** [comment]
The issue is when the orders are created on the backend , "order notes/customer notes are not showing
![customer-note-available-in-v 1 6 6b](https://user-images.githubusercontent.com/26347213/80707369-2242b980-8aea-11ea-81d3-a57364e48956.jpg)
![customer-note-missing](https://user-images.githubusercontent.com/26347213/80707375-25d64080-8aea-11ea-9e4c-01ceb0b59233.jpg)

" are no longer showing on the orders created on woocommerce, used to work just fine in v1.6.6b

**Comment by drew1607** [comment]
Infact the billing address is also empty just noticed yet it was filled in on the app

**Comment by drew1607** [comment]
Still no feedback? I updated to the latest version still no fix. Please help

**Comment by drew1607** [comment]
[common.zip](https://github.com/inspireui/support/files/4574209/common.zip)

**Comment by minhtruong315** [comment]
Hi @drew1607 you can try to edit toJson function in lib/models/order/order.dart like this
```
Map<String, dynamic> toJson(CartModel cartModel, userId, paid) {
    var lineItems = cartModel.productsInCart.keys.map((key) {
      String productId = Product.cleanProductID(key);

      Product product = cartModel.item[productId];

      var item = {
        "product_id": productId,
        "quantity": cartModel.productsInCart[key]
      };
      if (cartModel.productVariationInCart[key] != null) {
        item["variation_id"] = cartModel.productVariationInCart[key].id;
      }
      int quantity = cartModel.productsInCart[key];
      String total =
          (double.parse(isNotBlank(product.price) ? product.price : "0") *
                  quantity)
              .toString();
      String subtotal =
          (cartModel.getItemTotal(product: product, quantity: quantity))
              .toString();
      //before apply any coupons
      item['subtotal'] = total;
      //after apply any coupons
      item['total'] = subtotal;
      return item;
    }).toList();

    var params = {
      "set_paid": paid,
      "line_items": lineItems,
      "customer_id": userId,
    };
    try {
      if (cartModel.paymentMethod != null) {
        params["payment_method"] = cartModel.paymentMethod.id;
      }
      if (cartModel.paymentMethod != null) {
        params["payment_method_title"] = cartModel.paymentMethod.title;
      }
      if (paid) params["status"] = "completed";

      if (cartModel.address.mapUrl != null &&
          cartModel.address.mapUrl.isNotEmpty) {
        params["customer_note"] = "URL:" + cartModel.address.mapUrl;
      }
      if (kPaymentConfig['EnableReview'] &&
          cartModel.notes != null &&
          cartModel.notes.isNotEmpty) {
        if (params["customer_note"] != null) {
          params["customer_note"] += "\n" + cartModel.notes;
        } else {
          params["customer_note"] = cartModel.notes;
        }
      }

      if (kPaymentConfig['EnableAddress'] && cartModel.address != null) {
        params["billing"] = cartModel.address.toJson();
        params["shipping"] = cartModel.address.toJson();
      }

      if (kPaymentConfig['EnableShipping'] &&
          cartModel.shippingMethod != null) {
        params["shipping_lines"] = [
          {
            "method_id":
                "${cartModel.shippingMethod.methodId}:${cartModel.shippingMethod.id}",
            "method_title": cartModel.shippingMethod.title,
            "total": cartModel.getShippingCost().toString()
          }
        ];
      }

      if (cartModel.couponObj != null) {
        params["coupon_lines"] = [
          cartModel.couponObj.toJson(),
        ];
        params["subtotal"] = cartModel.getSubTotal();
        params["total"] = cartModel.getTotal();
      }
    } catch (e, trace) {
      print(e.toString());
      print(trace.toString());
    }
    return params;
  }
```
then try again

**Comment by drew1607** [comment]
thank you very much the order notes and info are now showing :)

**Comment by drew1607** [comment]
Sorry lastly point 8 to save long/lat to Order note (WooCommerce) as per 1.7.0 changelogs isnt working only getting the customer note even after setting the location on the address page(on checkout).

Reference - "Update - upgrade the Billing Address screen, also save long/lat to Order note (WooCommerce)"

**Comment by minhtruong315** [comment]
lat/long is saved on admin when you checkout on mobile app and use  search place function when input address

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
