### ISSUE TITLE
FluxStore Not Working - Build Error in iOS - PhaseScript Execution Failed

### ISSUE THREAD

**Issue by ffstore** [inspireui/support#2918]
Step 1 (require): detail issues and screenshots

The code is now working at all . i downloaded and tried to run the code but it is throwing phasescript execution failed error:

Command PhaseScriptExecution failed with a nonzero exit code

![image](https://user-images.githubusercontent.com/64485935/80510248-84d17380-898b-11ea-93b5-8f0e490d4d3c.png)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

![image](https://user-images.githubusercontent.com/64485935/80510417-bfd3a700-898b-11ea-92b7-48abb23dea32.png)

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhcasi** [comment]
@ffstore - pls help to provide more verify info to http://private.inspireui.com/ and reopen the ticket - thanks
