### ISSUE TITLE
[Flux Listing] Display bugs

### ISSUE THREAD

**Issue by gartional** [inspireui/support#2919]
![WechatIMG142](https://user-images.githubusercontent.com/41742783/80517675-193cd580-898e-11ea-95d4-6e6368c60a0e.jpeg)

![WechatIMG143](https://user-images.githubusercontent.com/41742783/80517663-1510b800-898e-11ea-8073-999263fa4e77.jpeg)
 
they are all from your ios app demo.

**Comment by philipvu30** [comment]
Hi,

May I ask did you use Flux Builder to build the app?

**Comment by gartional** [comment]
No
Android studio

philipvu30 <notifications@github.com>于2020年4月29日 周三11:04写道：

**Comment by gartional** [comment]
Actually, the screenshot is your app, official demo app in iOS store
Not build by me

philipvu30 <notifications@github.com>于2020年4月29日 周三11:04写道：

**Comment by philipvu30** [comment]
Hi,

Please use a smaller font and size for your phone. This app does not support scaling with the system font and size.
