### ISSUE TITLE
[CeBuilder]could not able to run the command in run setup after app config.. 

### ISSUE THREAD

**Issue by Pavithran10** [inspireui/support#292]
**Required Info (please complete the following information):**
 Product:[ListApp]
Version:1.6.1
Theme: MyListing

**Describe the bug**
In CeBuilder app development process can't able to run the command ''expo start" in run setup option while config app project folder. 

**Screenshots**
![expo error](https://user-images.githubusercontent.com/46148046/52636827-aadc3680-2ef3-11e9-9984-e5a62b8804e4.PNG)

**Comment by luyx2412** [comment]
Hi @Pavithran10 please provide your purchase code.

Thanks

**Comment by thangvo9x** [comment]
Hi. Please remove node_modules folder && run yarn again.

**Comment by Pavithran10** [comment]
thanks, I will try again

**Comment by Pavithran10** [comment]
Hi, Few days before I sended our site credentials for config purpose. you also fixed it and solved the problem. Regarding that comment I send you further reply for that comment in mail but still now I didn't get any reply from you for that mail. So, please check my comment and send a reply. thanks

**Comment by thangvo9x** [comment]
I replied to your email. I've only updated the plugin. Important, our problem was being fixed.

**Comment by Pavithran10** [comment]
hi, you replied in mail after fixed the issue. I also seen but I need a proper answer what plugin you are updated. why I am asking again we also tried a lot but we can't get any solution. so, for our request what changes you did in site you explained means it a helpful for our further needs. Thanks

**Comment by thangvo9x** [comment]
Hi. ListApp Mobile Manager plugin is erroring. I've fixed it. @Pavithran10

**Comment by Pavithran10** [comment]
thanks, for the reply
