### ISSUE TITLE
fluxstore-shopify not showing any payment options

### ISSUE THREAD

**Issue by amankwatra** [inspireui/support#2920]
I have almost completed by fluxstore shopify setup but am stuck at various points. 

1. When we are trying to place an order and reach the payment page, the Payment Methods tab is not activated, nothing happens when we click on it and when we press place order, the page gets stuck with the fluxstore timer icon. My website has Cash on Delivery and paypal enabled, but nothing is showing on the app. Screenshot included.
![Screenshot_1588094176](https://user-images.githubusercontent.com/55830839/80517250-675bd400-89a2-11ea-938b-3a9d254f1f87.png)

2. The Dark theme button is not working. When i downloaded your demo app it was working perfectly there but in the source code it is not working. Nothing happens when we click on it. Please let me know what to do to enable it.

3. The Calling/SMS/Whatsapp support tab is also not working. When we click on the tab the icons show but nothing happens when we click on those icons. 

4. The About Us page keeps loading and does not show. Please let me know what to do about all this. 

5. The google maps is not integrating(It is not the most urgent thing in the world).

6. The Shopify website has a column while placing orders for discount codes but the app does not have any. Is there any way that we can add the discount code line in the checkout page so that people have the same experience while shopping on the website or the app. 

Thanks

**Comment by minhcasi** [comment]
@amankwatra - thank you for the issues, we will double-check the issue and keep a new version update on next couple of day

**Comment by amankwatra** [comment]
Thanks, waiting for the same. Please see all the points I have made and try to solve as many as them.

**Comment by amankwatra** [comment]
Is there any update?

**Comment by luyx2412** [comment]
Hi @amankwatra We are checking and updating your issue in next version. 

Thanks for your request.

**Comment by amankwatra** [comment]
I can see that you have released a new version. Are the issues that I told you solved in that release or should I wait for another version after this one?

**Comment by amankwatra** [comment]
I've tried almost all the features requested and they are working, I could not check the payment page as it wanted me to  log on and for some reason that wasn't working.

I also want to know how to upgrade my code to this version? should i copy some files from the 1.6.5 project to this project? how does that work?

**Comment by Mikel-NC** [comment]
Same issues here

Please refund, fully bugged app

**Comment by amankwatra** [comment]
> Same issues here
> 
> Please refund, fully bugged app

Have you tried the new version? they have eliminated most of the problems that I had. a 3-4 day turnaround is impressive in my opinion. 

However, their reply would have been appreciated. there's no response which is frustrating.

**Comment by luyx2412** [comment]
Hi @amankwatra Sorry about reply you late. We are trying update new version to fix the issues.

Thanks

**Comment by amankwatra** [comment]
Hi,
It has been 18 days since i came to you with the issues, but I haven't received any update on the progress yet. Please let me know how long do I have to wait in order to get the update.

**Comment by luyx2412** [comment]
Hi @amankwatra Sorry about reply you late. Can you update latest version which fixed and improve some features. 

Thanks

**Comment by amankwatra** [comment]
Hi,

I have downloaded the latest version. How do I update my code in it? Do i manually enter all the website details again or can i import something? Please let me know.

**Comment by Mikel-NC** [comment]
Same question here

**Comment by luyx2412** [comment]
Hi @amankwatra Please add your old config.dart file or another file you changed and move to latest version.

Thanks

**Comment by minhcasi** [comment]
@amankwatra - please let us know if you have any questions, feel free to reopen the ticket - very best!
