### ISSUE TITLE
Fluxnews - Webview iOS 

### ISSUE THREAD

**Issue by ernandozatariano** [inspireui/support#2921]
Step 1 (require): detail issues and screenshots

Hi! My fluxnews app is done and working in Android. But i have a problem in iOS using webview.

I have a login page. After logging in (by the webview), I close the app and then reopen it. Upon re-opening, I am still logged in on Android, but on iOS I am shown the login page again. And this happens also when im go to another tab in ios app.

How can I preserve the webview session in ios?

Tks a lot!

Purchase screenshot:

![78781265-4ccfa580-7976-11ea-9671-28fced19752d](https://user-images.githubusercontent.com/63005352/80521955-365baf00-8962-11ea-9f72-7aa62c60a743.jpg)

**Comment by minhcasi** [comment]
@ernandozatariano - could share the screenshot or your app so that we could try this test case - thanks

**Comment by ernandozatariano** [comment]
Hi, i make a screen video to show my ios issue, using testflight and iphone 8. In webview page, when i  I close the app and then reopen, or simple change between the tabs, i need to make login again in my wordpress page. The same  not occurs in android version. Tks for help!

[VIDEO-2020-05-01-19-38-22.zip](https://github.com/inspireui/support/files/4566541/VIDEO-2020-05-01-19-38-22.zip)
