### ISSUE TITLE
[FluxStore] Translation of Attributes & Auto Fill for User Info in Checkout

### ISSUE THREAD

**Issue by IbrahimHd** [inspireui/support#2922]
Step 1 (require): detail issues and screenshots
#1. In search tool, the request is sent with Null value for [lang] parameter: `&lang=NULL`. Consequently, non-native lauguages don't work.
I think the problem is that `Provider.of<AppModel>(context, listen: false).locale;` returns `NULL` which means `Provider.of<AppModel>(context, listen: false) .changeLanguage(languages[i]["code"], context);` does not set/store the language as expected.

#2. In search tool (filter_search.dart) and product listing filter (backdrop_menu.dart), the translation of attributes doesn't work (but attribute terms works well).
As the attributes are already defined and translated in config, I used them by replacing:
`value.lstProductAttribute[index].name` with:
`(kProductVariantLanguage[lang] != null &&
                    kProductVariantLanguage[lang][value.lstProductAttribute[index].name.toLowerCase()] !=
                      null)
                      ? kProductVariantLanguage[lang][value.lstProductAttribute[index].name.toLowerCase()]
                      : value.lstProductAttribute[index].name`
Please consider this in the next update.

#3. Checkout: User info (name, email, phone) is not filled in automatically during checkout. (neither with email login nor Phone/SMS login)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com
![image](https://user-images.githubusercontent.com/16100897/80505441-01a92100-897d-11ea-9e9d-8288e653a335.png)

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhcasi** [comment]
@trunghieuvn - pls help to check this searching issue - thanks

**Comment by trunghieuvn** [comment]
> #1. In search tool, the request is sent with Null value for [lang] parameter: `&lang=NULL`. Consequently, non-native lauguages don't work.
> I think the problem is that `Provider.of<AppModel>(context, listen: false).locale;` returns `NULL` which means `Provider.of<AppModel>(context, listen: false) .changeLanguage(languages[i]["code"], context);` does not set/store the language as expected.

Please update to the latest version of FluxStore, we fix this problem by checking if the language is null. In case the language value is not obtained, we will not call the lang parameter to run the api (using the default language on the backend).

But if you want in that case, still call the default language of the app, you can add the following code to the `searchProducts` function in file `lib/services/woo_commerce.dart`.

![image](https://user-images.githubusercontent.com/19247680/81037988-c5bb1200-8ece-11ea-82f2-1638835c9c28.png)

**Comment by IbrahimHd** [comment]
Hi @trunghieuvn, 

#1.  Unfortunately this doesn't solve the problem.  I believe `lang` has not to be `NULL` in any case.  Please refer to my first message in the top.
#2. Is this helps?
#3. Waiting for your response.

Thanks

**Comment by trunghieuvn** [comment]
Please add me to git source or zip source send to mail: hieu.trantrung1204@gmail.com

**Comment by trunghieuvn** [comment]
> #3. Checkout: User info (name, email, phone) is not filled in automatically during checkout. (neither with email login nor Phone/SMS login)

At the Checkout screen, only fill info before you have created an order. The information to be filled in here is the customer's shipping information, which is not available. After the first time the customer orders successfully, the system will save and automatically fill in the next times. You can check this out.

**Comment by trunghieuvn** [comment]
> #2. In search tool (filter_search.dart) and product listing filter (backdrop_menu.dart), the translation of attributes doesn't work (but attribute terms works well).
> As the attributes are already defined and translated in config, I used them by replacing:
> `value.lstProductAttribute[index].name` with:
> `(kProductVariantLanguage[lang] != null && kProductVariantLanguage[lang][value.lstProductAttribute[index].name.toLowerCase()] != null) ? kProductVariantLanguage[lang][value.lstProductAttribute[index].name.toLowerCase()] : value.lstProductAttribute[index].name`
> Please consider this in the next update.



> #2. In search tool (filter_search.dart) and product listing filter (backdrop_menu.dart), the translation of attributes doesn't work (but attribute terms works well).
> As the attributes are already defined and translated in config, I used them by replacing:
> `value.lstProductAttribute[index].name` with:
> `(kProductVariantLanguage[lang] != null && kProductVariantLanguage[lang][value.lstProductAttribute[index].name.toLowerCase()] != null) ? kProductVariantLanguage[lang][value.lstProductAttribute[index].name.toLowerCase()] : value.lstProductAttribute[index].name`
> Please consider this in the next update.

Please send me the error video about this, I will check it more accurately. Thanks!

**Comment by trunghieuvn** [comment]
> #1. In search tool, the request is sent with Null value for [lang] parameter: `&lang=NULL`. Consequently, non-native lauguages don't work.
> I think the problem is that `Provider.of<AppModel>(context, listen: false).locale;` returns `NULL` which means `Provider.of<AppModel>(context, listen: false) .changeLanguage(languages[i]["code"], context);` does not set/store the language as expected.

I checked, it still works fine. Please try adding this code to the build function (in lib/screens/search/search.dart) and try again

```
lang: Provider.of<AppModel>(context, listen: false).locale,
```
![image](https://user-images.githubusercontent.com/19247680/81220274-4121de00-900b-11ea-92e6-cc2f09d3303c.png)

**Comment by IbrahimHd** [comment]
Hi @trunghieuvn 

#1. Great it works.  Now there is **no** need for the other code in `lib/services/woo_commerce.dart`:
 ```      
      if (lang?.isEmpty ?? false) {
        endPoint += '&lang=$lang';
      }else{
        endPoint += '&lang=${kAdvanceConfig['DefaultLanguage']}';
      }
```

#2.  Attributes traslation issue:
![image](https://user-images.githubusercontent.com/16100897/81484847-abc45b00-9251-11ea-8275-496d0d55ad11.png)

**The code I shared solves the problem**
Files: `lib/screens/search/widgets/filters/filter_search_attributes.dart` AND `backdrop_menu.dart`
**replace**
`value.lstProductAttribute[index].name`
with
```
(kProductVariantLanguage[lang] != null &&
kProductVariantLanguage[lang][value.lstProductAttribute[index].name.toLowerCase()] != null)
 ? kProductVariantLanguage[lang][value.lstProductAttribute[index].name.toLowerCase()]
 : value.lstProductAttribute[index].name,
```

#3.  At checkout, the email is autofilled but the name is NOT.

Thanks for your support.

**Comment by IbrahimHd** [comment]
@minhcasi @trunghieuvn 
It's really *weird* how you close issues before before they are COMPLETELY solved.
Same happend with other issues!!

**Comment by minhcasi** [comment]
@trunghieuvn - pls help to continuous checking

**Comment by trunghieuvn** [comment]
> #2. Attributes traslation issue:
> **The code I shared solves the problem**
> Files: `lib/screens/search/widgets/filters/filter_search_attributes.dart` AND `backdrop_menu.dart`
> **replace**
> `value.lstProductAttribute[index].name`
> with
> 
> ```
> (kProductVariantLanguage[lang] != null &&
> kProductVariantLanguage[lang][value.lstProductAttribute[index].name.toLowerCase()] != null)
>  ? kProductVariantLanguage[lang][value.lstProductAttribute[index].name.toLowerCase()]
>  : value.lstProductAttribute[index].name,
> ```

Thanks so much, that is a flaw. I will update in the next version.


> #3. At checkout, the email is autofilled but the name is NOT.




> > #3. Checkout: User info (name, email, phone) is not filled in automatically during checkout. (neither with email login nor Phone/SMS login)

I checked and found it still works. Please update to the latest version of FluxStore.
This is a video showing this feature is working well.

https://drive.google.com/file/d/1KAKiInxpZn4xRedQkAfXG5QAbH__ZMd_/view
> 
> At the Checkout screen, only fill info before you have created an order. The information to be filled in here is the customer's shipping information, which is not available. After the first time the customer orders successfully, the system will save and automatically fill in the next times. You can check this out.
