### ISSUE TITLE
[FluxStore MV] 3 important issues 

### ISSUE THREAD

**Issue by abedfatafta** [inspireui/support#2923]
Step 1 (require): detail issues and screenshots

1- the shipping method under wcfm show all  available methods even the disabled one 
2- hidden products displayed 
3- in wcfm store shipping have different shipping methods based on the store shipping for each shop . so each vendor have its own shipping method , and in checkout show up all the methods related to the selected products 

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by philipvu30** [comment]
Hi,

Your issues are being investigated. I will let you know when there is a result.

Thanks for using our product.

**Comment by philipvu30** [comment]
Hi, 

1. Fixed.
2. I have checked and the hidden products on our demo app are hidden. Can you provide more detail in image?
3. Currently, this feature is not available yet. Also we have no plan on implementing this. I suggest hiring a freelancer to do this for you.

**Comment by philipvu30** [comment]
Closed as no response. Feel free to re-open.
