### ISSUE TITLE
application  shows only 10 products in each list Category "Fluxstore woocommerce"

### ISSUE THREAD

**Issue by abqrinou** [inspireui/support#2924]
Step 1 (require): detail issues and screenshots
 The application  shows only 10 products in each list Category 
When i click on any category only 10 products are shown and when i click on see all it shows all product. 

[config.zip](https://github.com/inspireui/support/files/4549426/config.zip)

- screen video also from app demo data same issues
https://drive.google.com/file/d/1J6SlUxM5zR-bjy1e5jprJrRPKub4muWM/view

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhcasi** [comment]
@abqrinou - could i confirm if you are testing on the latest version 1.7.0 - thank you!

**Comment by abqrinou** [comment]
yes latest version 1.7.0

**Comment by minhcasi** [comment]
@trunghieuvn - pls investigating this issue - thank you!
