### ISSUE TITLE
CeBuilder mstore expo grpc error

### ISSUE THREAD

**Issue by mvargasp9** [inspireui/support#2925]
Hi i need help with this pls

warning " > reactotron-redux@3.1.1" has unmet peer dependency "reactotron-core-client@^2.5.0".
[4/4] Building fresh packages...
[-/5] ⠈ waiting...                                                                                                      [2/5] ⠈ grpc                                                                                                            [-/5] ⠈ waiting...                                                                                                      [-/5] ⠈ waiting...                                                                                                      error D:\Documents\Proyectos\Surtifarma\mstore-3.9.8\mstore-expo\node_modules\api-ecommerce\node_modules\grpc: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build --library=static_library
Arguments:
Directory: D:\Documents\Proyectos\Surtifarma\mstore-3.9.8\mstore-expo\node_modules\api-ecommerce\node_modules\grpc
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.12.0
node-pre-gyp info using node@12.16.3 | win32 | x64
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp info check checked for "D:\Documents\Proyectos\Surtifarma\mstore-3.9.8\mstore-expo\node_modules\api-ecommerce\node_modules\grpc\src\node\extension_binary\node-v72-win32-x64-unknown\grpc_node.node" (not found)
node-pre-gyp http GET https://node-precompiled-binaries.grpc.io/grpc/v1.20.0/node-v72-win32-x64-unknown.tar.gz
node-pre-gyp http 404 https://node-precompiled-binaries.grpc.io/grpc/v1.20.0/node-v72-win32-x64-unknown.tar.gz
node-pre-gyp WARN Tried to download(404): https://node-precompiled-binaries.grpc.io/grpc/v1.20.0/node-v72-win32-x64-unknown.tar.gz
node-pre-gyp WARN Pre-built binaries not found for grpc@1.20.0 and node@12.16.3 (node-v72 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://node-precompiled-binaries.grpc.io/grpc/v1.20.0/node-v72-win32-x64-unknown.tar.gz

D:\Documents\Proyectos\Surtifarma\mstore-3.9.8\mstore-expo\node_modules\api-ecommerce\node_modules\grpc>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node "" clean )
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@12.16.3 | win32 | x64
gyp info ok

D:\Documents\Proyectos\Surtifarma\mstore-3.9.8\mstore-expo\node_modules\api-ecommerce\node_modules\grpc>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build --library=static_library --module=D:\Documents\Proyectos\Surtifarma\mstore-3.9.8\mstore-expo\node_modules\api-ecommerce\node_modules\grpc\src\node\extension_binary\node-v72-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=D:\Documents\Proyectos\Surtifarma\mstore-3.9.8\mstore-expo\node_modules\api-ecommerce\node_modules\grpc\src\node\extension_binary\node-v72-win32-x64-unknown --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72 )  else (node "" configure --fallback-to-build --library=static_library --module=D:\Documents\Proyectos\Surtifarma\mstore-3.9.8\mstore-expo\node_modules\api-ecommerce\node_modules\grpc\src\node\extension_binary\node-v72-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=D:\Documents\Proyectos\Surtifarma\mstore-3.9.8\mstore-expo\node_modules\api-ecommerce\node_modules\grpc\src\node\extension_binary\node-v72-win32-x64-unknown --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72 )
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@12.16.3 | win32 | x64
gyp info find Python using Python version 3.8.2 found at "C:\Users\kurom\AppData\Local\Programs\Python\Python38-32\python.exe"
gyp ERR! find VS
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:310:5)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--library=static_library" "--module=D:\\Documents\\Proyectos\\Surtifarma\\mstore-3.9.8\\mstore-expo\\node_modules\\api-ecommerce\\node_modules\\grpc\\src\\node\\extension_binary\\node-v72-win32-x64-unknown\\grpc_node.node" "--module_name=grpc_node" "--module_path=D:\\Documents\\Proyectos\\Surtifarma\\mstore-3.9.8\\mstore-expo\\node_modules\\api-ecommerce\\node_modules\\grpc\\src\\node\\extension_binary\\node-v72-win32-x64-unknown" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd D:\Documents\Proyectos\Surtifarma\mstore-3.9.8\mstore-expo\node_modules\api-ecommerce\node_modules\grpc
gyp ERR! node -v v12.16.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallback-to-build --library=static_library --module=D:\Documents\Proyectos\Surtifarma\mstore-3.9.8\mstore-expo\node_modules\api-ecommerce\node_modules\grpc\src\node\extension_binary\node-v72-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=D:\Documents\Proyectos\Surtifarma\mstore-3.9.8\mstore-expo\node_modules\api-ecommerce\node_modules\grpc\src\node\extension_binary\node-v72-win32-x64-unknown --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\Documents\Proyectos\Surtifarma\mstore-3.9.8\mstore-expo\node_modules\api-ecommerce\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Windows_NT 10.0.18363
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\Documents\\Proyectos\\Surtifarma\\mstore-3.9.8\\mstore-expo\\node_modules\\api-ecommerce\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd D:\Documents\Proyectos\Surtifarma\mstore-3.9.8\mstore-expo\node_modules\api-ecommerce\node_modules\grpc
node-pre-gyp ERR! node -v v12.16.3
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd configure --fallback-to-build --library=static_library --module=D:\Documents\Proyectos\Surtifarma\mstore-3.9.8\mstore-expo\node_modules\api-ecommerce\node_modules\grpc\src\node\extension_binary\node-v72-win32

![Captura](https://user-images.githubusercontent.com/5010518/80570177-59b94500-89c8-11ea-892f-76c6463f72da.PNG)

![Captura2](https://user-images.githubusercontent.com/5010518/80570225-6dfd4200-89c8-11ea-9e5f-c724e66a982b.PNG)
Python38-32

**Comment by minhcasi** [comment]
@mvargasp9 - could you try to reinstall nodejs 10.x could fix this issue - https://nodejs.org/dist/latest-v10.x/ - thank you!

**Comment by mvargasp9** [comment]
Hi changed node, but this message appears

[4/4] Building fresh packages...
success Saved lockfile.
$ patch-package
patch-package 6.2.0
Applying patches...

**ERROR** Failed to apply patch for package metro at path

    node_modules/metro

  This error was caused because metro has changed since you
  made the patch file for it. This introduced conflicts with your patch,
  just like a merge conflict in Git when separate incompatible changes are
  made to the same piece of code.

  Maybe this means your patch file is no longer necessary, in which case
  hooray! Just delete it!

  Otherwise, you need to generate a new patch file.

  To generate a new one, just repeat the steps you made to generate the first
  one.

  i.e. manually make the appropriate file changes, then run

    patch-package metro

  Info:
    Patch file: patches/metro+0.51.1.patch
    Patch was made for version: 0.51.1
    Installed version: 0.56.4

Done in 3136.18s.

**Comment by mvargasp9** [comment]
Hi i solved that, but i have a problem, installed WPML and put the Spanish translation.. the products appear to me but the categories do not. What can be? Pls i need help urgent
![Captura1](https://user-images.githubusercontent.com/5010518/80690131-5f805a80-8a9c-11ea-95e1-bec0e98b3a4b.PNG)
![Captura2](https://user-images.githubusercontent.com/5010518/80690144-627b4b00-8a9c-11ea-9ec2-89ba885cb9e0.PNG)

**Comment by minhcasi** [comment]
we will have a check and let you know - thank you!

**Comment by minhcasi** [comment]
just read your message, you could refund on this link https://help.market.envato.com/hc/en-us/articles/202821460-Can-I-Get-A-Refund- thank you!
