### ISSUE TITLE
Can't get data from Server - Mstore Magento

### ISSUE THREAD

**Issue by RashVenkat6795** [inspireui/support#2926]
Step 1 (require): detail issues and screenshots
Configured url and accesstoken in AppConfig.json but still getting can't get data form server error. Please help me on how to customise the app

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com
uploaded in google form

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by RashVenkat6795** [comment]
@minhtruong315 please help me out on this

**Comment by minhcasi** [comment]
@RashVenkat6795 - could you send more detail purchase to http://private.inspireui.com/ then reopen the ticket - thanks

**Comment by RashVenkat6795** [comment]
@minhcasi i've already done it and i did already mention above also

**Comment by RashVenkat6795** [comment]
@minhcasi Please help me to resolve the error
