### ISSUE TITLE
Fluxstore Shopify : Product Details Formatting 

### ISSUE THREAD

**Issue by dsiewmy** [inspireui/support#2927]
Hi - i need help with two matters.

1) the product details formatting.
The app is currently synced to my shopify and getting correct information. But the text has no formatting.

In the app - no formatting 
<img width="460" alt="app" src="https://user-images.githubusercontent.com/63144745/80583251-90cc3c80-8a42-11ea-8ae0-9343b03048d5.png">

In web browser - with formatting
<img width="449" alt="browser" src="https://user-images.githubusercontent.com/63144745/80583288-99247780-8a42-11ea-945e-38df49391109.png">

2) What is the Title : Default Title tag ? Can I edit it to Brand names instead?
<img width="460" alt="app" src="https://user-images.githubusercontent.com/63144745/80583669-1bad3700-8a43-11ea-9066-d0bfc9fd6a30.png">

Thank you

**Comment by dsiewmy** [comment]
@luyx2412 @minhcasi  Waiting for an update on this issue. Thank you

Also, may i know if Blog function is available for Shopify? I'm not able to make it work, but i see the class being declared.

**Comment by luyx2412** [comment]
Hi @dsiewmy we are updating blog feature for shopify, and will release next version soon.

Thanks

**Comment by dsiewmy** [comment]
@luyx2412 thank you - but please help me on the above issue - about the formatting of text.

**Comment by luyx2412** [comment]
Hi @dsiewmy in `lib/screens/detail/product_description.dart` line 30. you can edit the html viewer plugin https://pub.dev/packages/flutter_widget_from_html to same your website.
![image](https://user-images.githubusercontent.com/8909619/80908586-389b8000-8d4b-11ea-8d7c-682f3772dacf.png)

Thanks

**Comment by dsiewmy** [comment]
<img width="806" alt="product_description" src="https://user-images.githubusercontent.com/63144745/80911799-3812e180-8d6b-11ea-8904-c362793ba079.png">

@luyx2412 Looking at the file, webView is already true. (I didn't change anything)
But it's not showing the html tags properly (as shown in my first post).

**Comment by dsiewmy** [comment]
@luyx2412 any updates ?
i see that there is another new version 1.7.2 but it probably doesn't help with my problem here.

**Comment by luyx2412** [comment]
Hi @dsiewmy Please add this function in your project `lib/screens/detail/product_description.dart`.

`normalizeHtml(String html) {
  return """
      <p style='font-size: 50px'>$html</p>
    """;
}`
And replace `product.description.replaceAll('src="//', 'src="https://')` with `normalizeHtml(product.description.replaceAll('src="//', 'src="https://')),` same the screenshot
![image](https://user-images.githubusercontent.com/8909619/81195606-46216600-8fe8-11ea-9108-7bb30d5fd8c2.png)

![image](https://user-images.githubusercontent.com/8909619/81195621-4a4d8380-8fe8-11ea-8386-a955537ecd60.png)

Thanks
