### ISSUE TITLE
opencart website collapse by adding opencart-extension 

### ISSUE THREAD

**Issue by adnan5588** [inspireui/support#2928]
Step 1 (require): detail issues and screenshots

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by adnan5588** [comment]
![Screenshot (16)](https://user-images.githubusercontent.com/21254658/80584118-489d2200-8a22-11ea-9128-28a1ea2ae45f.png)
![Screenshot (17)](https://user-images.githubusercontent.com/21254658/80584148-50f55d00-8a22-11ea-9299-67d62b103f11.png)

**Comment by adnan5588** [comment]
my opencart website is not behaving well after installing the opencart-extension included in the package. Kindly guide me about it.

**Comment by minhcasi** [comment]
@adnan5588 - pls add more verify purchase info to http://private.inspireui.com/ then reopen the ticket - thank you!
