### ISSUE TITLE
After change GoogleService-Info.plist, all login not return page settings

### ISSUE THREAD

**Issue by angelohu** [inspireui/support#2929]
FIREBASE, running the project is normal, until I switch to my account, change the file GoogleService-Info.plist, I can also log in normally, and will not automatically jump to the page afterwards

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all require info to continue with the support  - http://private.inspireui.com/ 

We're closing this ticket as is not provided enough detail, kindly reopen the ticket after you have done the form.

Very regards.

**Comment by angelohu** [comment]
website not work

 *my problem some*









Minh Pham <notifications@github.com>于2020年4月30日 周四02:55写道：
