### ISSUE TITLE
Trouble setting up Listapp for MyListing

### ISSUE THREAD

**Issue by hachikaru** [inspireui/support#293]
i opened an issue it has been closed ...please for some weeks now i havent setup the list app tried cebuilder getting errors like SET EXPO TRUE and it stops ...my skype name is live:4c6c034728a42823 please help me

**Comment by luyx2412** [comment]
Hi @hachikaru Please follow the template issue https://github.com/inspireui/support/blob/master/.github/ISSUE_TEMPLATE/report-installing-issues.md

Thanks

**Comment by minhcasi** [comment]
@hachikaru as we don't see your feedback on the ticket #202 so that it is closed, i've re-opened it & close this one - thanks
