### ISSUE TITLE
Fluxstore Pro - Woocommerce. Facebook & Google login issues

### ISSUE THREAD

**Issue by Tifahhh** [inspireui/support#2930]
As requested by support to open a ticket for this issue.

When you test the App on Android and try to login with Facebook or google. It comes back with an error. I found that if the device has the actual App of facebook or gmail installed it fails, but if they are not installed it prompts to open with the browser.

Here are some screenshots
Facebook error
https://pasteboard.co/J63iB0H.jpg

Google
https://pasteboard.co/J63jeqN.jpg

- Will upload the Config files with the support ticket thing.

Please help.

**Comment by Alnaggar94** [comment]
Same for me also I have reported in - 
 https://github.com/inspireui/support/issues/2895#issuecomment-621523766

**Comment by minhcasi** [comment]
@trunghieuvn - please help to check this login issue

**Comment by Tifahhh** [comment]
@trunghieuvn hope you can help thanks

**Comment by Alnaggar94** [comment]
@minhcasi - any update? many people having the same problem it's really annoying. Could you please give it more attention as this a real problem and  it was okay in the previous version .

**Comment by Alnaggar94** [comment]
@Tifahhh - I have found the solution check my comment  https://github.com/inspireui/support/issues/2895#issuecomment-622601633

**Comment by Tifahhh** [comment]
> @Tifahhh - I have found the solution check my comment [#2895 (comment)](https://github.com/inspireui/support/issues/2895#issuecomment-622601633)

ooh thanks! ill give it a shot. Thanks for sharing.

**Comment by minhcasi** [comment]
@Tifahhh - also try this guide https://paper.dropbox.com/doc/Fix-Login-GoogleSMS--AzJqodsGy2_ZYR4hluGH2UTLAg-jy7aa8GBDhBliErF345M3
