### ISSUE TITLE
[FluxStore] Product Variation Images

### ISSUE THREAD

**Issue by Mohamed20884** [inspireui/support#2931]
Hi 

I would like to ask what happened with this issue as it has been over 3 months since I open the last ticket https://github.com/inspireui/support/issues/1869

Thanks

**Comment by minhcasi** [comment]
@Mohamed20884 - sorry this Variant Image feature is not available, it is still on our backlog and waiting for the team to update after the crisis, please follow up our blog page to get the detail update for the next coming changelog - http://medium.com/@inspireui - thank you for your time.
