### ISSUE TITLE
Fluxstore Pro - Woocommerce. ADD

### ISSUE THREAD

**Issue by kzbar** [inspireui/support#2932]
in 1.7.0 store add to card and buy now button not work 
every thing is ok but buttons not work

**Comment by bikostudio** [comment]
same here not working too

**Comment by minhcasi** [comment]
@kzbar @bikostudio - pls help to update this patching on this ticket - https://github.com/inspireui/support/issues/2865#issuecomment-620630117 - we will update new hotfix in 1-2 days
