### ISSUE TITLE
 [FluxStore Pro] - Cloud messages from Firebase not stored in Notify Messages page in the App.

### ISSUE THREAD

**Issue by bikostudio** [inspireui/support#2933]
Cloud messages from Firebase not stored in Notify Messages page in the App.

![80308335-bbae5a80-87ce-11ea-9826-8cf50d4fe367](https://user-images.githubusercontent.com/62074493/80607820-3cbb5b00-8a36-11ea-9d34-73aac26f22d6.jpg)

**Comment by minhcasi** [comment]
@bikostudio - pls use this patching to fix the issue lib/model/notification.dart

[notification.dart.zip](https://github.com/inspireui/support/files/4555599/notification.dart.zip)

We also note the detailed video on https://www.youtube.com/watch?v=rFCcWNRPrSk - thank you!

**Comment by bikostudio** [comment]
> sue lib/model/notificati

@minhcasi - Hi, I did replaced the file you sent and it is the same code no changes. The Video you sent I already used it to setup the firebase. Please find solution for this problem. Thank you

**Comment by minhcasi** [comment]
@bikostudio - could you try with the latest version 1.7.1 - thanks

**Comment by bikostudio** [comment]
> 
> 
> @bikostudio - could you try with the latest version 1.7.1 - thanks

@minhcasi  I will try today and will update. thanks
