### ISSUE TITLE
[FluxStore Pro] - Add to cart and Buy now not working on v1.7.0

### ISSUE THREAD

**Issue by bikostudio** [inspireui/support#2934]
Add to cart and Buy now not working on v1.7.0
![2020-04-28_135106](https://user-images.githubusercontent.com/62074493/80608121-a176b580-8a36-11ea-85eb-95762960ac29.jpg)

**Comment by abdullatif1989** [comment]
I have same issue

**Comment by mohamedibrahim89** [comment]
same

**Comment by huseyincalli** [comment]
I have the same problem

**Comment by minhcasi** [comment]
@bikostudio @mohamedibrahim89 @huseyincalli  - pls help to update this patching on this ticket - #2865 (comment) - we will update new hotfix in 1-2 days
