### ISSUE TITLE
transfer the license to a new domain

### ISSUE THREAD

**Issue by sadeq90** [inspireui/support#2936]
Hi,

I want to transfer the license from http://sweetmamabh.com/ to dakakeenme.com because the previous domain was for testing only.

I couldn't find any option to disable or delete the license.

thank you,

**Comment by minhcasi** [comment]
could you try to download the latest Fluxbuilder, there is the Reset Purchase Code to help you transfer the license again - thank you!

**Comment by sadeq90** [comment]
how? I downloaded and installed it, I entered my website details and when typed my license it gives me the message it already used.
could you rest it from your side?

**Comment by sadeq90** [comment]
done, I had to remove www from URL.
