### ISSUE TITLE
image cache not enabled

### ISSUE THREAD

**Issue by mohamedibrahim89** [inspireui/support#2938]
hi this is the first time I pursache ur product I try to build my first app I have small problem
in flux builder image cache not enabled how can I solve this because image load so slow

<img width="1440" alt="Screen Shot 2020-04-29 at 8 50 32 PM" src="https://user-images.githubusercontent.com/35544603/80634652-12c85f80-8a5b-11ea-973f-61640345afc3.png">

second question

why I can't add to cart for product page and why I found buy now and add to cart button
but I can add to cart from category page why
<img width="1440" alt="Screen Shot 2020-04-29 at 10 24 54 PM" src="https://user-images.githubusercontent.com/35544603/80643466-6a20fc80-8a68-11ea-9dfe-8b2ea7b510eb.png">

**Comment by minhcasi** [comment]
@mohamedibrahim89 - pls check this Regerate solution to optimize the image - https://docs.inspireui.com/fluxstore/performance/

And use this patching for the Checkout button issue
https://github.com/inspireui/support/issues/2865#issuecomment-620630117

**Comment by minhcasi** [comment]
Pls download the latest one that fixes the #2 issue - thanks

**Comment by mohamedibrahim89** [comment]
try to change splash screen to my gif but not reflect in app and app make logo.png to splash screen I don't know why

<img width="1440" alt="80890804-042eb200-8cc0-11ea-8bee-8350da1a79f7" src="https://user-images.githubusercontent.com/35544603/80908858-b77cc280-8d23-11ea-8131-34baa638bd68.png">

**Comment by mohamedibrahim89** [comment]
?? I try this in last version 1.7.2 but not work also

**Comment by rabeehlive** [comment]
is there any solution for this issue, i can't change splash screen into gif, not reflecting in app
