### ISSUE TITLE
error while opening notification, shop and logout menu on side bar not working and layouts error

### ISSUE THREAD

**Issue by dasdev** [inspireui/support#2939]
getting lot of issue so i have fixed my self some i need urgent help plese. 

1)error after login:  getting error after login : error in multiple widgets used the same Globalkey. – i have changed the code form the ticket #2054 but not working. please help.
![Screenshot_2020-04-28-17-57-00-43_5322b48291e770e9bb1148f27d6b2d01 1](https://user-images.githubusercontent.com/34004057/80666626-6cac4200-8aba-11ea-869b-11885255ad0c.png)

2) error while opening onsignal notification : 
![Screenshot_2020-04-30-07-48-46-48_5322b48291e770e9bb1148f27d6b2d01 1](https://user-images.githubusercontent.com/34004057/80667093-cd884a00-8abb-11ea-8523-1abec9bee5f0.png)

3) shop and logout menu on side bar not working how to fix it?

4) Product layouts error while apply number 4 like this :
![Screenshot_2020-04-30-08-36-42-35_5322b48291e770e9bb1148f27d6b2d01 1](https://user-images.githubusercontent.com/34004057/80668085-89e30f80-8abe-11ea-8aff-bb9cf6e743e5.png)

5) my wishlist error 'OVERFLOWED BY' : 
![Screenshot_2020-04-30-08-39-07-26_5322b48291e770e9bb1148f27d6b2d01 1](https://user-images.githubusercontent.com/34004057/80669305-b0567a00-8ac1-11ea-8627-559374dd6791.png)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhcasi** [comment]
@dasdev could I confirm it has happened on the latest release?

**Comment by dasdev** [comment]
No it is old version

**Comment by minhcasi** [comment]
@dasdev - pls try with the latest version, we already fixed these issues

**Comment by dasdev** [comment]
how to upgrade to new version?

**Comment by minhcasi** [comment]
just use the package from http://codecayon.net/downloads and override your config folder, make sure to backup your existing code by using Git so that you could monitor your customize - thank you!

**Comment by dasdev** [comment]
bash tools/change-appbundle.sh this command not working in your new verison
