### ISSUE TITLE
[Mstore MV] Cant see Categories and Tags. 

### ISSUE THREAD

**Issue by valeopay** [inspireui/support#294]
**Mandatory Info (please complete the following information):**
* Product: MStore Multi Vendor
* Your Purchased Code: c731404c-2710-472a-9f53-590e9399f964

**Describe the issues**
i cant see any category or tag in the boxes. 2. how i can customize the category icons on the home screen? 

**Screenshots**
https://abload.de/img/capturevgk09.jpg

**Comment by thangvo9x** [comment]
Hi. Thanks for your purchase. Can you share screenshots more, plz? I can't see clearly.
you can edit category icons on AppConfig.json, here http://prntscr.com/mkcq1s
Thanks
