### ISSUE TITLE
[mstore-pro] expo - My Order total & Detail total different of shipping fees

### ISSUE THREAD

**Issue by oikim** [inspireui/support#2940]
Step 1 (require): detail issues and screenshots
As in first picture, the overview of #17396 shows total of RM31.68 (correct amount because already added RM5 of delivery fee), but once get into "Show details" - shows a total or RM36.68 - it got added again. This is confusing and request to fix this. 

![IMG_1895](https://user-images.githubusercontent.com/32124092/80674922-beb68d00-8ae5-11ea-9f8f-ca13f8e806f0.png)

![IMG_1896](https://user-images.githubusercontent.com/32124092/80674924-c0805080-8ae5-11ea-842b-c916ba563ca5.jpeg)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

created in above URL. 

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by luyx2412** [comment]
Hi @oikim Thanks for your request. We will fix and update in next version.

Thanks.

**Comment by oikim** [comment]
Hi good morning! I tried updated to version 2.4.4 on mstore API this morning and there's critical failure on the WooCommerce. Kindly resolve this. 

When seeking help with this issue, you may be asked for some of the following information:
WordPress version 5.4.1
Current theme: Food Market (version 1.0.9)
Current plugin: Mstore API (version 2.4.4)
PHP version 7.2.24-0ubuntu0.18.04.4


Error Details
=============
An error of type E_ERROR was caused in line 20 of the file /var/www/html/express/wp-content/plugins/mstore-api/functions/index.php. Error message: Cannot redeclare deleteDuplicateCheckoutPages() (previously declared in /var/www/html/express/wp-content/plugins/mstore-api/functions/index.php:20)

**Comment by luyx2412** [comment]
Hi @oikim Please update the latest mstore-api plugin.

Thanks

**Comment by oikim** [comment]
Thank you folks.

**Comment by minhcasi** [comment]
Dear @oikim - please help us to give the rating to http://codecanyon.net/downloads if the product is useful for your business, appreciated for your help :)
