### ISSUE TITLE
FLUXSTORE PRO IS NOT WORKING ! AGAIN!

### ISSUE THREAD

**Issue by alicankarakus** [inspireui/support#2941]
you told me to wait for the new update for opencart. However, there are errors in your new update.

the most important of these;
1- Option variations of the products do not work in the cart.
2- Membership entry is not made.

I have been waiting for your system to work stable for 1.5 months. 
I am not satisfied with your application and your product at all. It is enough.
![screen1](https://user-images.githubusercontent.com/6725793/80680753-06c6b700-8ac8-11ea-8939-4e3261c45335.JPG)
![screen2](https://user-images.githubusercontent.com/6725793/80680756-08907a80-8ac8-11ea-8d21-4e320348e67b.JPG)
![screen3](https://user-images.githubusercontent.com/6725793/80680758-08907a80-8ac8-11ea-98a7-d7f6d1a4015e.JPG)
![screen4](https://user-images.githubusercontent.com/6725793/80680761-09291100-8ac8-11ea-9a71-54bb7481761d.JPG)

**Comment by minhcasi** [comment]
@alicankarakus - it is ok to process refund if you are not satisfy with the product - https://help.market.envato.com/hc/en-us/articles/202821460-Can-I-Get-A-Refund- - thanks

**Comment by alicankarakus** [comment]
you have to solve the problem of mine and other users.
If you do not fully support opencart, you will not sell this product. 

At the moment, your system is not stable with opencart. you have to fix it as soon as possible.
and you cannot close this request until my problem is resolved.
