### ISSUE TITLE
[fluxstore] opencart variant

### ISSUE THREAD

**Issue by alicankarakus** [inspireui/support#2942]
you told me to wait for the new update for opencart. However, there are errors in your new update.

the most important of these;
1- Option variations of the products do not work in the cart.
2- Membership entry is not made.

I have been waiting for your system to work stable for 1.5 months.
I am not satisfied with your application and your product at all. It is enough.

you have to solve the problem of mine and other users.
If you do not fully support opencart, you will not sell this product.

At the moment, your system is not stable with opencart. you have to fix it as soon as possible.
and you cannot close this request until my problem is resolved.

![screen1](https://user-images.githubusercontent.com/6725793/80682721-b4879500-8acb-11ea-9e8e-ca7438cb0f18.JPG)
![screen2](https://user-images.githubusercontent.com/6725793/80682724-b5b8c200-8acb-11ea-96c6-751366e03c02.JPG)
![screen3](https://user-images.githubusercontent.com/6725793/80682726-b6515880-8acb-11ea-8564-94599129aec2.JPG)
![screen4](https://user-images.githubusercontent.com/6725793/80682727-b6e9ef00-8acb-11ea-8b6d-e3659213d091.JPG)

**Comment by minhcasi** [comment]
The weight variant and membership cart are not available on current release and we may not support these features. 

It supports only some product variants that we explain from  - https://medium.com/@inspireui/announcing-fluxstore-1-7-x-9a636c5468e8

**Comment by alicankarakus** [comment]
How? 
customer wanted to buy the product.
For example, he will buy a t-shirt and chose a small size for it.

product price: dropped from $ 15 to $ 10.
small price: $ 11
medium price: $ 12
large price: $ 13

When added to the cart, the customer sees the price of the product as $ 15. it does not see the price of the option it chooses.

**Comment by minhtruong315** [comment]
@alicankarakus you can try to choose options in product, then create the order. you  will see the options product in admin site.

**Comment by alicankarakus** [comment]
admin area is not important. the customer wants to be treated correctly in the basket.

**Comment by minhtruong315** [comment]
@alicankarakus can you give me your email. I will send u updates for option price issues

**Comment by alicankarakus** [comment]
alicankarakuss@gmail.com

**Comment by minhtruong315** [comment]
sent

**Comment by alicankarakus** [comment]
Hi..
I have a this error now. What is that?
![image](https://user-images.githubusercontent.com/6725793/81039647-4ddeee80-8eb2-11ea-893d-dc22180e4b98.png)

**Comment by minhtruong315** [comment]
@alicankarakus it's working on my website 
<img width="414" alt="Screen Shot 2020-05-06 at 2 36 25 PM" src="https://user-images.githubusercontent.com/10402500/81148744-05552d00-8fa7-11ea-97ea-95c2027724fa.png">
Can u upload your source code to git repo? Then add my email: minhtruong315@gmail.com
I will checkout your source code and check on it.
Thanks

**Comment by alicankarakus** [comment]
i didn't change anything. I just downloaded and i did "Run Application" ...

I downloaded latest FluxstorePro 1.7.2
and I downloaded latest android studio
and I'm using 1.12.13 flutter

The others full default. Anything not change

![image](https://user-images.githubusercontent.com/6725793/81149031-1477b300-8f86-11ea-8a67-6cc94e5ec512.png)

**Comment by minhtruong315** [comment]
@alicankarakus replace models/product/product.dart to fix
[product.dart.zip](https://github.com/inspireui/support/files/4590273/product.dart.zip)

**Comment by alicankarakus** [comment]
Okay... this error has been fixed. 

![image](https://user-images.githubusercontent.com/6725793/81288973-43695400-906e-11ea-8f17-747cbbedec65.png)

But now: product price is $ 14. The customer has to choose 3 Kilograms for the minimum order. 
As you can see, 14 * 3.25 = 45.5 dollars for 3 kilograms.
But it doesn't look that way.

![image](https://user-images.githubusercontent.com/6725793/81289025-5845e780-906e-11ea-9ac9-03632cd1ca12.png)

**Comment by minhtruong315** [comment]
@alicankarakus you can use Fluxstore version 1.7.3 on codecanyon then test again
