### ISSUE TITLE
Fluxstore 1.7 Checkout Paypal wrong currency

### ISSUE THREAD

**Issue by Lapic23** [inspireui/support#2943]
Step 1 (require): detail issues and screenshots

Currency in Paypal checkout is different with original currency
![Simulator Screen Shot - iPhone 11 Pro - 2020-04-30 at 12 20 45](https://user-images.githubusercontent.com/36863195/80700341-d5f17c80-8add-11ea-91f5-d62e2851b201.png)
![Simulator Screen Shot - iPhone 11 Pro - 2020-04-30 at 12 24 55](https://user-images.githubusercontent.com/36863195/80700352-d9850380-8add-11ea-8500-c2e42a569214.png)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhcasi** [comment]
It is the same Euro - you could change the symbol form the app on this setting https://tppr.me/5C1e1

**Comment by Lapic23** [comment]
Sorry, but It was not my issue,  when I checkout in Euros but in PayPal it's the same amount but in dollars.
