### ISSUE TITLE
No such module 'GoogleMaps'

### ISSUE THREAD

**Issue by TheEgyptianDevelopers** [inspireui/support#2944]
/Users/imac/*/fluxstore1.7.0/source/ios/Runner/AppDelegate.swift:3:8: No such module 'GoogleMaps'

**Comment by TheEgyptianDevelopers** [comment]
When I build & run on xcode, It say build failed and it give me this message

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all require info to continue with the support  - http://private.inspireui.com/ 

We're closing this ticket as is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!
