### ISSUE TITLE
Images won't load 

### ISSUE THREAD

**Issue by victormtz8** [inspireui/support#2945]
Step 1 (require): detail issues and screenshots

Images won't load pull from assets, images for categories i am referring  

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

already did
*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all require info to continue with the support  - http://private.inspireui.com/ 

We're closing this ticket as is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!
