### ISSUE TITLE
[fluxstore] Checkout issue!!

### ISSUE THREAD

**Issue by aishema2000** [inspireui/support#2947]
Step 1 (require): detail issues and screenshots

During Checkout when I place the order, the response takes extremely long time to show that order is successful. it takes about three minutes to see the successful message.

When I check in visual code console I see this:
![image](https://user-images.githubusercontent.com/15066381/80705512-da6e6300-8ae6-11ea-81a7-fb46e40ea8a0.png)

When I see in woocomerce, the order is placed within seconds.

After three minutes the order placed successfull page comes. This is what I see in debug console:
![image](https://user-images.githubusercontent.com/15066381/80705596-00940300-8ae7-11ea-89d9-deb6be4ae9f6.png)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by immortal-kid** [comment]
yes even i'm facing similar issue, checkout button is not working instantly, it is taking too much time to perform next action, meanwhile people will be keep pressing it, this will create lot of duplicate orders in COD

**Comment by aishema2000** [comment]
@minhtruong315 when can I expect your support sir? Please respond

**Comment by minhtruong315** [comment]
@aishema2000 we don't work on the weekend. but I will try to support you today. Thanks

**Comment by aishema2000** [comment]
@minhtruong315 I posted support request two days ago. I am really tired. Please I beg you help me today. Please

**Comment by minhtruong315** [comment]
[index.dart.zip](https://github.com/inspireui/support/files/4567294/index.dart.zip)
replace this file widgets/frameworks/woocommerce/index.dart then try again

**Comment by aishema2000** [comment]
Let me try fast fast, I come back shortly.

**Comment by aishema2000** [comment]
Very nice. It working perfectly. Thank you very much, now I can go on, publishing my APP. May God Bless you.
