### ISSUE TITLE
[Fluxstore Shopify] Build issues

### ISSUE THREAD

**Issue by ctactuk** [inspireui/support#2948]
![image](https://user-images.githubusercontent.com/4774542/80707979-e3484000-8ab8-11ea-9fcb-bf0fd3879851.png)

**Comment by minhcasi** [comment]
@ctactuk - try to use flutter stable
```
flutter channel stable
flutter upgrade --force
```
Thank you

**Comment by ctactuk** [comment]
Thanks, it works.!
