### ISSUE TITLE
Fluxstore Pro opencart issues | Opencart website is collapsing after installing extension

### ISSUE THREAD

**Issue by adnan5588** [inspireui/support#2949]
![Screenshot (18)](https://user-images.githubusercontent.com/21254658/80710758-56c17000-8b00-11ea-83c5-d9fb7fbad14e.png)
![Screenshot (19)](https://user-images.githubusercontent.com/21254658/80710765-588b3380-8b00-11ea-9562-43304707be78.png)
![Screenshot (20)](https://user-images.githubusercontent.com/21254658/80710767-588b3380-8b00-11ea-983e-b384b539e885.png)

Step 1 (require): detail issues and screenshots

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhtruong315** [comment]
Hi @adnan5588 it throw error on module extension, but you only use MStore extension. You can try to uninstall MStore extension, then try to use your website again.

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
