### ISSUE TITLE
[listpro] login and register 

### ISSUE THREAD

**Issue by chad-the-first** [inspireui/support#295]
**Mandatory Info (please complete the following information):**
 - Product: [ListApp]
 - Your Purchased Code: [65e47917-78fa-4b8e-97ec-80bf8345f72a]
(we may not reply if you are not our customer)

**Describe the issues**
what are the steps that i should make to enable the login, register and register with facebook, I've tried but i can't get it to work.

**Comment by thangvo9x** [comment]
Can you share screenshots, plz ?

**Comment by chad-the-first** [comment]
here's the api response 
![sketch](https://user-images.githubusercontent.com/17035853/52709799-6bb2f180-2f96-11e9-9ff7-14b7a1787d65.png)

**Comment by thangvo9x** [comment]
HI. What are your issues? Please screenshot on device

**Comment by chad-the-first** [comment]
It doesn't login 
![sketch1](https://user-images.githubusercontent.com/17035853/52710555-49ba6e80-2f98-11e9-92a4-66d4bec78d71.png)

**Comment by chad-the-first** [comment]
and this is what happens when i try to signup

the signup button keep rolling:
![sketch2](https://user-images.githubusercontent.com/17035853/52712714-1844a180-2f9e-11e9-8d70-be3e9a181087.png)

and here's the api response:
![sketch3](https://user-images.githubusercontent.com/17035853/52712751-33afac80-2f9e-11e9-9457-fdb9a4fa3981.png)

**Comment by thangvo9x** [comment]
Please remove expo app && remove yarn cache clean, such as check on your site.
I checked the link which works fine.
<img width="837" alt="fine" src="https://user-images.githubusercontent.com/23457178/52893319-a9e62600-31cd-11e9-95ef-b7ded868a73e.png">

**Comment by kragenv** [comment]
* Product: [ListApp] + MyListing Theme 2.0.10
* Your Purchased Code: [9cfbf8b5-1cbb-4ab1-a4ab-0b2741668b30]

Same issue. Cannot login and show the same message about "userinfo.user.id"
and also cannot display image in homepage while it can display image inside the listing items.

**Comment by chad-the-first** [comment]
@thangvo9x  I did clean yarn cache and delete expo and still the same problem.
i added you to the repo: https://github.com/chad-the-first/listpro

**Comment by thangvo9x** [comment]
Hi Please try again. I've checked with your repo on a real device.
refer here: https://we.tl/t-a4i1AUZve7
Thanks

**Comment by chad-the-first** [comment]
As I can see, when I register from the app, i can use this account to login on the app. But when I register on the website I can't use this account to login on the app. Any idea how I can fix that?

**Comment by thangvo9x** [comment]
Please provide me that account which is created on your website.

**Comment by chad-the-first** [comment]
Hi, website is: www.cataloglebnen.com
Username: thang
Email: worktannoury@gmail.com
Password: Help1234!@#$

**Comment by thangvo9x** [comment]
You must update the password before login on your app
1. Before . https://gyazo.com/a132f6b2decaa28d33ccb1838c92e6e5
2. after change.  https://gyazo.com/cfc6c5923a2c81dfc862d92a11f51f21
