### ISSUE TITLE
Exception: The initialValue provided is not a supported iso code

### ISSUE THREAD

**Issue by algheilani** [inspireui/support#2950]
Hi, I have this issue evreytime i try to make an order blue screen shows this error

I/flutter (14725): Exception: The initialValue provided is not a supported iso code!

I/flutter (14725): Fluxstore[15:19:01.211003] getAsync END [endPoint:shipping/zones] url:shipping/zones I/flutter (14725): Fluxstore[15:19:01.211279] getAsync START [endPoint:shipping/zones/0/methods] url:https://mysitecom/wp-json/wc/v2/shipping/zones/0/methods?consumer_key=ck_582e42c9axxxxx4e&consumer_secret=cs_59ce73c6a0xxxx I/flutter (14725): Fluxstore[15:19:02.747629] getAsync END [endPoint:shipping/zones/0/methods] url:shipping/zones/0/methods

also i noticed this issue

I/flutter (14725): The relevant error-causing widget was: I/flutter (14725): ShippingAddress I/flutter (14725): file:///C:/Users/Desktop/me/folder/FluxStore-woo%201.7.0/source/lib/screens/checkout/index.dart:351:16

i don’t think the link should be local but am not sure!

**Comment by minhcasi** [comment]
@algheilani could you share your `lib/common` folder

pls try to check my guide from the localhost setup - https://www.youtube.com/watch?v=CEyfZmzBMTw
