### ISSUE TITLE
Honest feedback 

### ISSUE THREAD

**Issue by immortal-kid** [inspireui/support#2952]
(revised from #2385 )
hello
i use your script for my grocery store. sounds strange but Yes, woocommerce for grocery store. Your fluxstore script is the only best source code i found in envato with too many customization and without much errors. Before i buy i saw reviews and your support, and after i purchased your people have been providing lightening support and honest service. Hats off to your hardwork. especially in this corona time, i must give you a huge round of applause. Bravo 👏👏👏.

1. From the day i purchased, i was waiting for one feature. You can see other grocery store apps on playstore, your script is not good enough for grocery store. I've been requesting this one feature from a very long time and i'm **very disappointed** in this. see this screenshot 
![Untitled-1](https://user-images.githubusercontent.com/10250665/80722648-3a7ffc00-8b1d-11ea-806e-3af35a9d9e34.png)

I know if we know flutter we can do it ourselves, but not everyone who bought the script is aware of flutter customization.  Every time when you push updates, i see changelogs and get dissapponted that list view in product list layout is not present. I get many phone calls from customer saying "other  grocery app is like that and why is your app is like this". I know your guys are working very hard to improve the script and i hope you would consider my feedback.

2. (Feature request) login with OTP is fine, but you could have added an otp screen after checkout and before placing order, this could stop lot of fake orders. Think about it once. Because lot of people use fake email id's to login and enter some random 10 digit number in address page and place order by selecting COD with fake information. If you add opt after checkout, these fraud activities can be easily. make use of services like twilio, msg91 or  somehow try with Firebase itself. If i remove other option in signup and enable only sms login, they cannot login from website. So separate OTP option in after shipping address in checkout would be very helpful.

Apart from these, this script is incredible and support is very best i had seen far.

**Comment by minhcasi** [comment]
@immortal-kid - thank you for your valuable feedback

#1 - there is already the List product view on the homepage, but it seems work perfect as your screenshot, we confirm to move this UI and upgrade as the same into the product list 👍

#2- we will investigate the OTP features 🤓

Please bear with us for these improvements. In the meantime, could you help to change the emotion ":(" from the title to another super active one 👍

**Comment by minhcasi** [comment]
This UI will be included on 1.7.2 - other OPT is complex and will be upgraded later - thanks

![Simulator Screen Shot - iPhone 11 Pro - 2020-05-03 at 09 54 53](https://user-images.githubusercontent.com/1459805/80897552-29550c00-8d24-11ea-8367-291bc5ab3764.png)

**Comment by minhcasi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [OPT login](https://trello.com/c/9JScybz3/15-opt-login)

**Comment by minhcasi** [comment]
Also, moved OPT to the backlog
