### ISSUE TITLE
WooCommerce Bookings with some minor errors

### ISSUE THREAD

**Issue by sercada** [inspireui/support#2953]
Step 1 (require): detail issues and screenshots
Hi, I noticed in the code that [Woocommerce Bookings](https://woocommerce.com/products/woocommerce-bookings/?utm_campaign=woocommerce%20bookings&utm_source=adwords&utm_medium=search&utm_term=woocommerce%20%2Bbookings&utm_content=99512254283&gclid=Cj0KCQjw7qn1BRDqARIsAKMbHDYKPcBRtJhQ56PsLX7f6tNZWZgRIJMRNgtrFp_JJzo7itCQVMZFnDMaAlBJEALw_wcB&gclsrc=aw.ds) is compatible with your app, which is great. I decided to implement it in my website to use it in the app ( I was using another not compatible plugin ). 

The information is being correctly pulled from my website but there are a few aesthetic details I'd like you to help me resolve: 

![Screen Shot 2020-04-30 at 9 39 24 AM](https://user-images.githubusercontent.com/24389792/80723626-7b98f180-8ac6-11ea-927a-18f6876cf135.jpg)

Please do your trials with the product Pampas Grass Greenery, that is the only one with the booking options set up. 

1. The Booking date includes hours, minutes, seconds and milliseconds. How can I leave just the date (without hour)?
2. My booking setup doesn't require duration to book the products. Just the date. How can I hide the duration field?
3. When a date is chosen, the final price doesn't show correctly, instead it shows an updated line of code below (with the price), but it looks bad, can it be shown above as the normal price?
4. The add to cart button doesn’t show.

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

It has been submitted.

**Comment by minhcasi** [comment]
@sercada - thank you for the detail, we will investigate this feature, could you also share us the admin website login so that we could check the plugin integration - pls send to support@inspireui.com

**Comment by sercada** [comment]
> @sercada - thank you for the detail, we will investigate this feature, could you also share us the admin website login so that we could check the plugin integration - pls send to [support@inspireui.com](mailto:support@inspireui.com)

Thanks for your prompt reply, I’ve send you the required details.

**Comment by sercada** [comment]
@minhcasi please lee me know if you need any other information to speed up a resolution for this.

**Comment by sercada** [comment]
I've decided not to use this plugin as it is impractical for my business operation. Thanks for your support.

**Comment by minhcasi** [comment]
@sercada - thank you for the confirm - let us know if you need any support from us
