### ISSUE TITLE
Error when running green button

### ISSUE THREAD

**Issue by trananhchien** [inspireui/support#2954]
Error when running green button - When changing components such as logo, splash, onboarding ...
Step 1 (require): detail issues and screenshots

Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
Running Xcode build...
Xcode build done.                                           37.6s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    In file included from /Users/trananhchien/flutter/.pub-cache/hosted/pub.dartlang.org/uni_links-0.2.0/ios/Classes/UniLinksPlugin.m:1:
    /Users/trananhchien/flutter/.pub-cache/hosted/pub.dartlang.org/uni_links-0.2.0/ios/Classes/UniLinksPlugin.h:4:4: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
    + (instancetype)sharedInstance;
       ^
    /Users/trananhchien/flutter/.pub-cache/hosted/pub.dartlang.org/uni_links-0.2.0/ios/Classes/UniLinksPlugin.h:4:4: note: insert '_Nullable' if the pointer may be null
    + (instancetype)sharedInstance;
       ^
                    _Nullable 
    /Users/trananhchien/flutter/.pub-cache/hosted/pub.dartlang.org/uni_links-0.2.0/ios/Classes/UniLinksPlugin.h:4:4: note: insert '_Nonnull' if the pointer should never be null
    + (instancetype)sharedInstance;
       ^
                    _Nonnull 
    /Users/trananhchien/flutter/.pub-cache/hosted/pub.dartlang.org/uni_links-0.2.0/ios/Classes/UniLinksPlugin.h:7:33: warning: block pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
          restorationHandler:(void (^)(NSArray *_Nullable))restorationHandler;
                                    ^
    /Users/trananhchien/flutter/.pub-cache/hosted/pub.dartlang.org/uni_links-0.2.0/ios/Classes/UniLinksPlugin.h:7:33: note: insert '_Nullable' if the block pointer may be null
          restorationHandler:(void (^)(NSArray *_Nullable))restorationHandler;
                                    ^
                                     _Nullable
    /Users/trananhchien/flutter/.pub-cache/hosted/pub.dartlang.org/uni_links-0.2.0/ios/Classes/UniLinksPlugin.h:7:33: note: insert '_Nonnull' if the block pointer should never be null
          restorationHandler:(void (^)(NSArray *_Nullable))restorationHandler;
                                    ^
                                     _Nonnull
    2 warnings generated.
    /Users/trananhchien/flutter/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0.6.0+2/ios/Classes/RateMyAppPlugin.m:15:30: warning: 'requestReview' is only available on iOS 10.3 or newer [-Wunguarded-availability]
        [SKStoreReviewController requestReview];
                                 ^~~~~~~~~~~~~~
    In module 'StoreKit' imported from /Users/trananhchien/flutter/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0.6.0+2/ios/Classes/RateMyAppPlugin.m:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.4.sdk/System/Library/Frameworks/StoreKit.framework/Headers/SKStoreReviewController.h:22:1: note: 'requestReview' has been marked as being introduced in iOS 10.3 here, but the deployment target is iOS 8.0.0
    + (void)requestReview API_AVAILABLE(ios(10.3), macos(10.14)) API_UNAVAILABLE(watchos) __TVOS_PROHIBITED;
    ^
    /Users/trananhchien/flutter/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0.6.0+2/ios/Classes/RateMyAppPlugin.m:15:30: note: enclose 'requestReview' in an @available check to silence this warning
        [SKStoreReviewController requestReview];
                                 ^~~~~~~~~~~~~~
    /Users/trananhchien/flutter/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0.6.0+2/ios/Classes/RateMyAppPlugin.m:15:6: warning: 'SKStoreReviewController' is only available on iOS 10.3 or newer [-Wunguarded-availability]
        [SKStoreReviewController requestReview];
         ^~~~~~~~~~~~~~~~~~~~~~~
    In module 'StoreKit' imported from /Users/trananhchien/flutter/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0.6.0+2/ios/Classes/RateMyAppPlugin.m:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.4.sdk/System/Library/Frameworks/StoreKit.framework/Headers/SKStoreReviewController.h:14:110: note: 'SKStoreReviewController' has been marked as being introduced in iOS 10.3 here, but the deployment target is iOS 8.0.0
    SK_EXTERN_CLASS API_AVAILABLE(ios(10.3), macos(10.14)) API_UNAVAILABLE(watchos) __TVOS_PROHIBITED @interface SKStoreReviewController : NSObject
                                                                                                                 ^
    /Users/trananhchien/flutter/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0.6.0+2/ios/Classes/RateMyAppPlugin.m:15:6: note: enclose 'SKStoreReviewController' in an @available check to silence this warning
        [SKStoreReviewController requestReview];
         ^~~~~~~~~~~~~~~~~~~~~~~
    2 warnings generated.
    /Users/trananhchien/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_admob-0.9.3+2/ios/Classes/FLTRewardedVideoAdWrapper.m:75:66: warning: implicit conversion loses integer precision: 'FLTRewardedVideoAdStatus' to 'int' [-Wshorten-64-to-32]
          (NSString *)rewardedStatusToString[[NSNumber numberWithInt:_rewardedStatus]];
                                             ~                       ^~~~~~~~~~~~~~~
    1 warning generated.
    /Users/trananhchien/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_admob-0.9.3+2/ios/Classes/FLTRequestFactory.m:71:13: warning: 'testDevices' is deprecated: Use GADMobileAds.sharedInstance.requestConfiguration.testDeviceIdentifiers. [-Wdeprecated-declarations]
        request.testDevices = testDevices;
                ^
    In module 'GoogleMobileAds' imported from /Users/trananhchien/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_admob-0.9.3+2/ios/Classes/FLTRequestFactory.h:5:
    /Users/trananhchien/RM/ios/Pods/Google-Mobile-Ads-SDK/Frameworks/GoogleMobileAdsFramework-Current/GoogleMobileAds.framework/Headers/GADRequest.h:88:71: note: 'testDevices' has been explicitly marked deprecated here
    @property(nonatomic, copy, nullable) NSArray<NSString *> *testDevices GAD_DEPRECATED_MSG_ATTRIBUTE(
                                                                          ^
    In module 'GoogleMobileAds' imported from /Users/trananhchien/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_admob-0.9.3+2/ios/Classes/FLTRequestFactory.h:5:
    /Users/trananhchien/RM/ios/Pods/Google-Mobile-Ads-SDK/Frameworks/GoogleMobileAdsFramework-Current/GoogleMobileAds.framework/Headers/GoogleMobileAdsDefines.h:25:56: note: expanded from macro 'GAD_DEPRECATED_MSG_ATTRIBUTE'
    #define GAD_DEPRECATED_MSG_ATTRIBUTE(s) __attribute__((deprecated(s)))
                                                           ^
    /Users/trananhchien/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_admob-0.9.3+2/ios/Classes/FLTRequestFactory.m:91:15: warning: 'birthday' is deprecated [-Wdeprecated-declarations]
          request.birthday =
                  ^
    In module 'GoogleMobileAds' imported from /Users/trananhchien/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_admob-0.9.3+2/ios/Classes/FLTRequestFactory.h:5:
    /Users/trananhchien/RM/ios/Pods/Google-Mobile-Ads-SDK/Frameworks/GoogleMobileAdsFramework-Current/GoogleMobileAds.framework/Headers/GADRequest.h:95:55: note: 'birthday' has been explicitly marked deprecated here
    @property(nonatomic, copy, nullable) NSDate *birthday GAD_DEPRECATED_ATTRIBUTE;
                                                          ^
    In module 'GoogleMobileAds' imported from /Users/trananhchien/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_admob-0.9.3+2/ios/Classes/FLTRequestFactory.h:5:
    /Users/trananhchien/RM/ios/Pods/Google-Mobile-Ads-SDK/Frameworks/GoogleMobileAdsFramework-Current/GoogleMobileAds.framework/Headers/GoogleMobileAdsDefines.h:33:49: note: expanded from macro 'GAD_DEPRECATED_ATTRIBUTE'
    #define GAD_DEPRECATED_ATTRIBUTE __attribute__((deprecated))
                                                    ^
    /Users/trananhchien/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_admob-0.9.3+2/ios/Classes/FLTRequestFactory.m:106:19: warning: 'gender' is deprecated [-Wdeprecated-declarations]
              request.gender = genderValue;
                      ^
    In module 'GoogleMobileAds' imported from /Users/trananhchien/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_admob-0.9.3+2/ios/Classes/FLTRequestFactory.h:5:
    /Users/trananhchien/RM/ios/Pods/Google-Mobile-Ads-SDK/Frameworks/GoogleMobileAdsFramework-Current/GoogleMobileAds.framework/Headers/GADRequest.h:92:47: note: 'gender' has been explicitly marked deprecated here
    @property(nonatomic, assign) GADGender gender GAD_DEPRECATED_ATTRIBUTE;
                                                  ^
    In module 'GoogleMobileAds' imported from /Users/trananhchien/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_admob-0.9.3+2/ios/Classes/FLTRequestFactory.h:5:
    /Users/trananhchien/RM/ios/Pods/Google-Mobile-Ads-SDK/Frameworks/GoogleMobileAdsFramework-Current/GoogleMobileAds.framework/Headers/GoogleMobileAdsDefines.h:33:49: note: expanded from macro 'GAD_DEPRECATED_ATTRIBUTE'
    #define GAD_DEPRECATED_ATTRIBUTE __attribute__((deprecated))
                                                    ^
    /Users/trananhchien/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_admob-0.9.3+2/ios/Classes/FLTRequestFactory.m:116:14: warning: 'tagForChildDirectedTreatment:' is deprecated:  use [GADMobileAds.sharedInstance.requestConfiguration tagForChildDirectedTreatment] [-Wdeprecated-declarations]
        [request tagForChildDirectedTreatment:childDirected.boolValue];
                 ^
    In module 'GoogleMobileAds' imported from /Users/trananhchien/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_admob-0.9.3+2/ios/Classes/FLTRequestFactory.h:5:
    /Users/trananhchien/RM/ios/Pods/Google-Mobile-Ads-SDK/Frameworks/GoogleMobileAdsFramework-Current/GoogleMobileAds.framework/Headers/GADRequest.h:126:5: note: 'tagForChildDirectedTreatment:' has been explicitly marked deprecated here
        GAD_DEPRECATED_MSG_ATTRIBUTE(
        ^
    In module 'GoogleMobileAds' imported from /Users/trananhchien/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_admob-0.9.3+2/ios/Classes/FLTRequestFactory.h:5:
    /Users/trananhchien/RM/ios/Pods/Google-Mobile-Ads-SDK/Frameworks/GoogleMobileAdsFramework-Current/GoogleMobileAds.framework/Headers/GoogleMobileAdsDefines.h:25:56: note: expanded from macro 'GAD_DEPRECATED_MSG_ATTRIBUTE'
    #define GAD_DEPRECATED_MSG_ATTRIBUTE(s) __attribute__((deprecated(s)))
                                                           ^
    4 warnings generated.
    2 warnings generated.
    While building module 'uni_links' imported from /Users/trananhchien/RM/ios/Runner/GeneratedPluginRegistrant.m:146:
    In file included from <module-includes>:1:
    In file included from /Users/trananhchien/RM/build/ios/Debug-iphonesimulator/uni_links/uni_links.framework/Headers/uni_links-umbrella.h:13:
    /Users/trananhchien/RM/build/ios/Debug-iphonesimulator/uni_links/uni_links.framework/Headers/UniLinksPlugin.h:4:4: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
    + (instancetype)sharedInstance;
       ^
    /Users/trananhchien/RM/build/ios/Debug-iphonesimulator/uni_links/uni_links.framework/Headers/UniLinksPlugin.h:4:4: note: insert '_Nullable' if the pointer may be null
    + (instancetype)sharedInstance;
       ^
                    _Nullable 
    /Users/trananhchien/RM/build/ios/Debug-iphonesimulator/uni_links/uni_links.framework/Headers/UniLinksPlugin.h:4:4: note: insert '_Nonnull' if the pointer should never be null
    + (instancetype)sharedInstance;
       ^
                    _Nonnull 
    /Users/trananhchien/RM/build/ios/Debug-iphonesimulator/uni_links/uni_links.framework/Headers/UniLinksPlugin.h:7:33: warning: block pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
          restorationHandler:(void (^)(NSArray *_Nullable))restorationHandler;
                                    ^
    /Users/trananhchien/RM/build/ios/Debug-iphonesimulator/uni_links/uni_links.framework/Headers/UniLinksPlugin.h:7:33: note: insert '_Nullable' if the block pointer may be null
          restorationHandler:(void (^)(NSArray *_Nullable))restorationHandler;
                                    ^
                                     _Nullable
    /Users/trananhchien/RM/build/ios/Debug-iphonesimulator/uni_links/uni_links.framework/Headers/UniLinksPlugin.h:7:33: note: insert '_Nonnull' if the block pointer should never be null
          restorationHandler:(void (^)(NSArray *_Nullable))restorationHandler;
                                    ^
                                     _Nonnull
    2 warnings generated.
    2 warnings generated.
    /Users/trananhchien/RM/build/ios/Debug-iphonesimulator/Runner.app: resource fork, Finder information, or similar detritus not allowed
    Command CodeSign failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

Could not build the application for the simulator.
Error launching application on iPhone 11 Pro Max.

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhcasi** [comment]
@trananhchien - pls try following solutions https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

**Comment by trananhchien** [comment]
Do following instruction. But still error. When change images, sentences and run green button. But when remove source and make new begining, it work.

Launching lib/main.dart on iPhone 11 Pro in debug mode...
Running pod install...
Running Xcode build...
Xcode build done.                                           14.8s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    error: unable to attach DB: error: accessing build database "/Users/trananhchien/Library/Developer/Xcode/DerivedData/Runner-ajufnnounqsrndailhuopacseayi/Build/Intermediates.noindex/XCBuildData/build.db": database is locked Possibly there are two concurrent builds running in the same filesystem location.
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

Could not build the application for the simulator.
Error launching application on iPhone 11 Pro.

**Comment by minhcasi** [comment]
@trananhchien - try to close the XCode - only open Android Studio or VS Code to run the project. 

We suggest spending more time to play around with setting up the Flutter framework - https://flutter.dev/docs/get-started/test-drive?tab=vscode
