### ISSUE TITLE
Problems 

### ISSUE THREAD

**Issue by Roupasafricanas** [inspireui/support#2957]
Step 1 (require): detail issues and screenshots

![80401587-f679c680-8892-11ea-8d91-35c257374fa1](https://user-images.githubusercontent.com/63840938/80747308-9d5f9c00-8af9-11ea-802b-a837f0f168f6.jpg)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

Hi. I have 2 problems

1) I set up the Onboarding but it doesn't appear when I run the app for the first time

2) I can't set up the Firebase Notification on Android. Messages don't come. The video on YouTube is for ios e non-Android. 

3) when I update the caching to true, the app screen turns black 
Can you help me?

**Comment by Roupasafricanas** [comment]
Update: The notification problem have been resolved with the new video posted on YouTube.
Thanks

**Comment by Alnaggar94** [comment]
@minhcasi - I have the same issue "I set up the Onboarding but it doesn't appear when I run the app for the first time"

**Comment by minhcasi** [comment]
fixed on latest build - we will also update Gitlab shortly - thank you for reporting

**Comment by abqrinou** [comment]
I have the same issue "1.7.1"
1-I set up the Onboarding but it doesn't appear when I run the app for the first time
2-when I update the caching to true, and change "splashscreen"the app screen turns black
Any solutions??

**Comment by Roupasafricanas** [comment]
> corrigé sur la dernière version - nous mettrons également à jour Gitlab sous peu - merci de nous avoir signalé
Very thanks. Can you tell me if the OneSignal still works?

**Comment by minhcasi** [comment]
@abqrinou - we have fixed on 1.7.2 - it will be updated soon - thank you!

**Comment by minhcasi** [comment]
we have fixed this bug on the latest 1.7.2 - pls help to download the package - thank you!
