### ISSUE TITLE
When i modify the file config_en.json it doesnt make any change in the UI of my app when testing

### ISSUE THREAD

**Issue by andrex16** [inspireui/support#2958]
Every time I make any change to the conig_en.json, do I have to modify something else so that I can have any chage made?

When i modify for example the home Screen whit FluxBuilder, I copy that file and pastase it, but also nothing happens.

Do I have to rebuid the proyect somehow or what else do I have to modify?

thanks

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all require info to continue with the support  - http://private.inspireui.com/ 

We're closing this ticket as is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!
