### ISSUE TITLE
[Beonews Pro] Facebook 

### ISSUE THREAD

**Issue by globe21** [inspireui/support#296]
**Mandatory Info (please complete the following information):**
 - Product: beonews-pro
 - Your Purchased Code: [2dbba340-dbfd-4d43-bbe3-dfcdb29e3458]
(we may not reply if you are not our customer)

**Describe the issues**
Facebook Sharekit.h file missing
<img width="830" alt="screen shot 2019-02-12 at 1 44 20 pm" src="https://user-images.githubusercontent.com/1266746/52670159-b9fbbe00-2ecc-11e9-9180-9c9d00b04436.png">

**Screenshots**

**Additional context**
The FBSDK is in my documents directory

**Comment by luyx2412** [comment]
HI @globe21 Please follow the comment to fix your issue https://github.com/facebook/react-native-fbsdk/issues/401#issuecomment-435312536
Thanks

**Comment by minhcasi** [comment]
@globe21 Could you try this solution:

Go to RCTFBSDK.xcodeproj then select build settings -> framework search paths
And change ~/Documents/FacebookSDK to $(HOME)/Documents/FacebookSDK

This bug happens on the XCode 10 - [facebook/react-native-fbsdk#401](https://github.com/facebook/react-native-fbsdk/issues/401)

Please reopen if it is not worked, thank you!
