### ISSUE TITLE
Cannot get data from REST API

### ISSUE THREAD

**Issue by miamir2000** [inspireui/support#2961]
Step 1 (require): detail issues and screenshots
- I've setup a woo-commerce(WCFM) multi vendor portal
- However, my mobile app can't get data from this REST API
- Please help..

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhcasi** [comment]
@miamir2000 - try to double-check your consume key as it is not working correctly - https://tppr.me/XGXeV

you could also use the fluxbuilder to test this feature http://fluxbuilder.com/
