### ISSUE TITLE
FluxNews Project update to version 1.4.0

### ISSUE THREAD

**Issue by haidarsalim** [inspireui/support#2962]
> I spent a lot of time editing the project
> You have modified rtl support files
> You have removed some menu items

I would like to know the necessary files to replace them
1.3.0 ➜ 1.4.0
Is it better for me to work on Project 1.4.0 ?

![33333](https://user-images.githubusercontent.com/54249914/80781297-81e8a580-8b7a-11ea-8f0d-b5a8adf463bf.JPG)

**Comment by minhcasi** [comment]
@haidarsalim - you could process on this Gitlab to get the detail file change on the app - https://docs.google.com/forms/d/e/1FAIpQLSeuBqUkScy42V7KKhfNPj0fl581anrB1mWkbMa3p2WQt7fhfw/viewform

RTL and menu is still there, you could customize via fluxbuilder as well http://fluxbuilder.com/ 

If you have heavy customize you could keep your version, as the latest 1.4.0 have added new post management and some improvements to compatible with fluxbuilder app
