### ISSUE TITLE
Cart total shows regular price total instead of sale price total

### ISSUE THREAD

**Issue by ykarapanca** [inspireui/support#2963]
Step 1 (require): detail issues and screenshots
Cart total shows regular price total instead of sale price total. Screenshot regular price is 20tl, sale price is 14tl. In cart, it shows 20TL in total.

![Screenshot_20200501-122830](https://user-images.githubusercontent.com/58140554/80797252-ff77da00-8ba9-11ea-80b0-5fd16f55b203.jpg)
![Screenshot_20200501-122838](https://user-images.githubusercontent.com/58140554/80797415-7319e700-8baa-11ea-8ffb-82bcc2d32779.jpg)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

**Comment by ykarapanca** [comment]
Hi @minhcasi - This is the only issue left of mine. I am using the latest release of update. Thank you

**Comment by iamar1k92** [comment]
Big issue this is.

**Comment by ykarapanca** [comment]
agreed @iamar1k92

**Comment by minhcasi** [comment]
@iamar1k92 @ykarapanca - thank you for reporting - we will double check as a high priority 👍

**Comment by mohamedibrahim89** [comment]
@minhcasi  no new this is the first version. I have and need to lunch app

**Comment by minhcasi** [comment]
Please update below file to fix this issue, we have included the patching for 1.7.2 - it will be ready soon - thank you!

<img width="1067" alt="Screen Shot 2020-05-03 at 09 49 58" src="https://user-images.githubusercontent.com/1459805/80897491-74baea80-8d23-11ea-8a08-0f34727f3da2.png">

**Comment by minhcasi** [comment]
we have fixed this bug on the latest 1.7.2 - pls help to download the package - thank you!

**Comment by ykarapanca** [comment]
It worked. Thanks @minhcasi
