### ISSUE TITLE
Fluxstore login issue 

### ISSUE THREAD

**Issue by netappzone** [inspireui/support#2964]
I have been unable to signin to my app for months now after updating the mstore api

![Screenshot_20200501_105101_com igreenmall](https://user-images.githubusercontent.com/33864849/80798231-d3edf300-8b9b-11ea-8faa-b2bb4d11f43f.jpg)

![Screenshot_20200501_110157](https://user-images.githubusercontent.com/33864849/80798224-ce90a880-8b9b-11ea-8a9f-fe79e8fe452e.jpg)

**Comment by Alnaggar94** [comment]
@minhcasi - The same problem many people have reported the same but not fixed until now

**Comment by Alnaggar94** [comment]
![80657544-8d5da300-8a8c-11ea-9774-f4262ac8495e](https://user-images.githubusercontent.com/49800146/80801348-bbd69d80-8bb4-11ea-9da2-f83af32d8d5b.jpg)

**Comment by Alnaggar94** [comment]
@netappzone - I have found the solution check my comment https://github.com/inspireui/support/issues/2895#issuecomment-622601633

**Comment by maynard88** [comment]
I am having the same issue. I installed it on my mobile phone and login keeps loading

**Comment by minhcasi** [comment]
@netappzone @netappzone @maynard88 - pls check the solution by update SHA1 on both Goolge Play and Firebase - it's explained on this link https://docs.inspireui.com/fluxstore/sign-in/#3-sms-sign-in
