### ISSUE TITLE
app customize

### ISSUE THREAD

**Issue by mohamedibrahim89** [inspireui/support#2965]
how can I change webview loading icon
<img width="1440" alt="Screen Shot 2020-05-01 at 12 31 18 PM" src="https://user-images.githubusercontent.com/35544603/80799634-ab6bf600-8ba7-11ea-92fc-085deea3e9c9.png">
second question how can I disable SMS Login from sign in?

**Comment by iamar1k92** [comment]
For changing webview loading icon: go to lib/common/constants/loading.dart
https://imgur.com/y8eeFSq.png & change SpinKitFadingCube to any of the predefined if you like : https://github.com/ybq/Android-SpinKit




To disable sms login : go to lib/common/config/general.dart & search const kLoginSetting and under that you will find  'showSMSLogin': true, just change the true to false. 
https://imgur.com/T12Kvia.png
