### ISSUE TITLE
Products not showing on the app, 

### ISSUE THREAD

**Issue by cayanjo** [inspireui/support#2966]
Hi,

I am facing an issue that once I connect the app to my woo commerce website, nothing showing (products and categories), but its showing from the demo website.
although I follow all the instructions for installation.

please help

**Comment by minhcasi** [comment]
@cayanjo 


Please help us to submit this form and fill all require info to continue with the support  - http://private.inspireui.com/ 

We're closing this ticket as is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!
