### ISSUE TITLE
[FluxStore Shopify] NoSuchMethodError

### ISSUE THREAD

**Issue by ctactuk** [inspireui/support#2967]
Error Ocurred when building the app

![image](https://user-images.githubusercontent.com/4774542/80812897-e4e83580-8b96-11ea-8ed2-68e44de34087.png)

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all require info to continue with the support  - http://private.inspireui.com/ 

We're closing this ticket as is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by ctactuk** [comment]
Form submitted
