### ISSUE TITLE
Fluxstore app - Problem with Shipping on checkout

### ISSUE THREAD

**Issue by PauloBrazilDHPP** [inspireui/support#2968]
Hi there

I have an issue with shipping on fluxstore app... the app cant get right values from shipping on my woocommerce site.
On my site i use a plugin called "Claudio Sanches - Correios for Woocommerce" to calculate shipping costs on Correios in Brazil...
The shipping options are listed on app screen but not the values... it comes with zero.

Here goes the output on console and screeshots

flutter: [Fluxstore][Cart] build
flutter: Product { id: 2739 name: Sapatinho para Bebê em Crochê }
flutter: Product { id: 2739 name: Sapatinho para Bebê em Crochê }
flutter: [Fluxstore][wocommerce_api][11:18:30.090081] getAsync START [endPoint:coupons] url:https://tricodavoxiloca.com.br//wp-json/wc/v2/coupons?consumer_key=ck_35383adf2739783b413f80ae92c83ff5452cf09f&consumer_secret=cs_709beb73059982bbf46555087a6f6e3cfd52d44c
flutter: [Fluxstore][wocommerce_api][11:18:34.383136] getAsync END [endPoint:coupons] url:coupons
flutter: [Fluxstore][App] internet issue change: {ConnectivityResult.none: false}
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The getter 'noInternetConnection' was called on null.
Receiver: null
Tried calling: noInternetConnection
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      showDialogNotInternet (package:fstore/widgets/common/dialogs.dart:17:34)
#2      AppState.initState.<anonymous closure>.<anonymous closure> (package:fstore/app.dart:87:17)
#3      _rootRunUnary (dart:async/zone.dart:1134:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#5      _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#7      _DelayedData.perform (dart:async/stream_impl.dart:593:14)
#8      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:709:11)
#9      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:669:7)
#10     _rootRun (dart:async/zone.dart:1122:38)
#11     _CustomZone.run (dart:async/zone.dart:102<…>
	[C6.1 C96E3584-25C2-4702-8CF8-9F646713E5AF 192.168.1.117:51026<->64.233.190.188:5228]
	Connected Path: unsatisfied (No network route)
	Duration: 8534.812s, DNS @0.000s took 0.011s, TCP @0.012s took 0.051s
	bytes in/out: 0/0, packets in/out: 0/0, rtt: 0.000s, retransmitted packets: 0, out-of-order packets: 0
flutter: [Fluxstore][Cart] build
flutter: Product { id: 2739 name: Sapatinho para Bebê em Crochê }
flutter: Product { id: 2739 name: Sapatinho para Bebê em Crochê }
flutter: [Fluxstore][wocommerce_api][12:46:42.423571] getAsync START [endPoint:shipping/zones] url:https://tricodavoxiloca.com.br//wp-json/wc/v2/shipping/zones?consumer_key=ck_35383adf2739783b413f80ae92c83ff5452cf09f&consumer_secret=cs_709beb73059982bbf46555087a6f6e3cfd52d44c
flutter: [Fluxstore][wocommerce_api][12:46:47.363035] getAsync END [endPoint:shipping/zones] url:shipping/zones
flutter: [Fluxstore][wocommerce_api][12:46:47.364423] getAsync START [endPoint:shipping/zones/0/methods] url:https://tricodavoxiloca.com.br//wp-json/wc/v2/shipping/zones/0/methods?consumer_key=ck_35383adf2739783b413f80ae92c83ff5452cf09f&consumer_secret=cs_709beb73059982bbf46555087a6f6e3cfd52d44c
flutter: [Fluxstore][wocommerce_api][12:46:49.617538] getAsync END [endPoint:shipping/zones/0/methods] url:shipping/zones/0/methods
flutter: [Fluxstore][wocommerce_api][12:46:49.621107] getAsync START [endPoint:shipping/zones/0/locations] url:https://tricodavoxiloca.com.br//wp-json/wc/v2/shipping/zones/0/locations?consumer_key=ck_35383adf2739783b413f80ae92c83ff5452cf09f&consumer_secret=cs_709beb73059982bbf46555087a6f6e3cfd52d44c
flutter: [Fluxstore][wocommerce_api][12:46:51.231821] getAsync END [endPoint:shipping/zones/0/locations] url:shipping/zones/0/locations
flutter: [Fluxstore][wocommerce_api][12:46:51.234181] getAsync START [endPoint:shipping/zones/4/methods] url:https://tricodavoxiloca.com.br//wp-json/wc/v2/shipping/zones/4/methods?consumer_key=ck_35383adf2739783b413f80ae92c83ff5452cf09f&consumer_secret=cs_709beb73059982bbf46555087a6f6e3cfd52d44c
flutter: [Fluxstore][wocommerce_api][12:46:53.345208] getAsync END [endPoint:shipping/zones/4/methods] url:shipping/zones/4/methods
flutter: [Fluxstore][wocommerce_api][12:46:53.347826] getAsync START [endPoint:shipping/zones/4/locations] url:https://tricodavoxiloca.com.br//wp-json/wc/v2/shipping/zones/4/locations?consumer_key=ck_35383adf2739783b413f80ae92c83ff5452cf09f&consumer_secret=cs_709beb73059982bbf46555087a6f6e3cfd52d44c
flutter: [Fluxstore][wocommerce_api][12:46:54.923853] getAsync END [endPoint:shipping/zones/4/locations] url:shipping/zones/4/locations
flutter: shippingMethods SEDEX 10 Pacote
flutter: shippingMethods PAC
flutter: shippingMethods SEDEX
![Captura de Tela 2020-05-01 às 12 50 42](https://user-images.githubusercontent.com/64207931/80818922-68f7e880-8baa-11ea-9fb7-ac48bc415bd0.png)
![Captura de Tela 2020-05-01 às 12 49 54](https://user-images.githubusercontent.com/64207931/80818926-6bf2d900-8baa-11ea-877f-cf8d0f842251.png)
![Captura de Tela 2020-05-01 às 12 47 07](https://user-images.githubusercontent.com/64207931/80818934-6dbc9c80-8baa-11ea-95cd-456ac534cdad.png)
![Captura de Tela 2020-05-01 às 12 46 50](https://user-images.githubusercontent.com/64207931/80818939-6eedc980-8baa-11ea-95a4-970347609871.png)

Someone have a solution for this issue?

**Comment by minhcasi** [comment]
@PauloBrazilDHPP - could i know if you are using any extra custom Shipping plugin?

**Comment by PauloBrazilDHPP** [comment]
Yes, i am using in WordPress the “Cláudio Sanches - correios for woocommerce” plugin

**Comment by PauloBrazilDHPP** [comment]
I need to use this plugin to calculate the shipping costs...

**Comment by rodrigoalves1901** [comment]
@PauloBrazilDHPP  o nosso plugin dos correios não funciona. vc tem que ativar a função.
Localizado em : common/config/payments.dart
"EnableOnePageCheckout": true,
 "NativeOnePageCheckout": true

**Comment by PauloBrazilDHPP** [comment]
> @PauloBrazilDHPP o nosso plugin dos correios não funciona. vc tem que ativar a função.
> Localizado em : common/config/payments.dart
> "EnableOnePageCheckout": true,
> "NativeOnePageCheckout": true

Mas neste caso o checkout fica na página do woocommerce certo? O usuário não aceita desta forma... teria que ser o checkout no app mesmo
Com checkout no app conhece alguma solução?

**Comment by minhcasi** [comment]
@PauloBrazilDHPP 

A página do processo de check-out ainda está no aplicativo, mas está incorporada à Webview do Woocommerce, por essa abordagem é flexível e você pode usar plug-ins extras para personalizar o pagamento, mas sem impacto no UX geral do pagamento, vamos tentar essas configurações e deixe-nos saber
