### ISSUE TITLE
Fluxstore Pro - Fetch more tabs & custom tabs from woocomerce product

### ISSUE THREAD

**Issue by tjain90** [inspireui/support#2969]
Step 1 (require): detail issues and screenshots
Is there any way to to Fetch more tabs like short discription or custom tabs from woocomerce ? 

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhcasi** [comment]
Sorry, i'm not sure on this question, i think you could customize the Rest API from WooCommerce - thank you!

**Comment by tjain90** [comment]
Right now we have discription and review from woocomerce . But let's say if we have more products tabs like short discription, size chart etc in our product at website then how we can show that to product page in fluxstore. 

Similarly how to pull global attributes of each products in product page in app.

**Comment by tjain90** [comment]
So request you to not to close this issue. I need resolution for same.
