### ISSUE TITLE
[ListApp] could able to remove account logo in fb..

### ISSUE THREAD

**Issue by Pavithran10** [inspireui/support#297]
**Mandatory Info (please complete the following information):**
Product:[ListApp]
Version:1.6.1
Theme: MyListing

**Describe the issues**
hi, I have doubt in your application that facebook login account page "beo foods" log is fixed. If it is able to change or remove from that place.

**Screenshots**
![account](https://user-images.githubusercontent.com/46148046/52702668-a28f0480-2fa2-11e9-9576-e594e68a5411.png)

**Comment by thangvo9x** [comment]
HI. Please refer 
https://github.com/inspireui/support/issues/184#issuecomment-463458243

**Comment by Pavithran10** [comment]
Thanks, fb logo and name as changed.

**Comment by thangvo9x** [comment]
The issue is coming from your Facebook app. please read documents facebook app as a guide.
