### ISSUE TITLE
Fluxstore pro woocomerce - Fetch html in product page

### ISSUE THREAD

**Issue by tjain90** [inspireui/support#2970]
Step 1 (require): detail issues and screenshots
Is there any way to Fetch html elements and data in product description. 
Any way to have short html form elements in product page ?

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhcasi** [comment]
@tjain90 you could try to render the shortcode inside the HTML from rest api - pls check this solution - https://wordpress.stackexchange.com/questions/50564/how-to-handle-shortcodes-when-using-the-json-api - thank you!
