### ISSUE TITLE
[Fluxstore pro- Woocomerce] : Firebase notification showing grey box & Inapp Messaging notworking

### ISSUE THREAD

**Issue by tjain90** [inspireui/support#2971]
Step 1 (require): 

1. Firebase notifications are showing dark grey box in place of app logo or icon
2. In app messaging not working on any device. is there any extra setting we need to do to enable In App Messaging campaigns.

 

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by Alnaggar94** [comment]
I  have the same issue #1 : 
![ffff](https://user-images.githubusercontent.com/49800146/80848592-69c96280-8c1c-11ea-8112-d60b60b47e6d.JPG)

@tjain90 - Just to help you out for your problem #2 you have to set up an account in "tawk.to" then replace your link in (lib\common\config\smartchat.dart):
![c5](https://user-images.githubusercontent.com/49800146/80848690-c0cf3780-8c1c-11ea-99ac-6f07f8b2f26a.JPG)

**Comment by tjain90** [comment]
@Alnaggar94 thanks for suggestion but tawk.to is an live chat white firebase in app messaging is a campaign that shows popup type of message when somebody open your app or based on other event.

**Comment by minhcasi** [comment]
@trunghieuvn - pls give suggestion of how to fix the grey avatar

**Comment by trunghieuvn** [comment]
@tjain90 
I've fixed it on my app by ensuring

<meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@mipmap/ic_notification" />

using the image name 'ic_notification.png'

and also ensuring your GCM data has this property:

icon: 'ic_notification'

**Comment by Alnaggar94** [comment]
@tjain90 @minhcasi - Could you please help how and where to put this code or the png icon in asset/images ??

**Comment by Alnaggar94** [comment]
@trunghieuvn - Could you please help explain it and where to put the code and which director do we put the icon, and what's the right size?

**Comment by tjain90** [comment]
Hi Team,

Kindly resolve this before closing. We are getting dark grey notification icon.

**Comment by tjain90** [comment]
@minhcasi Kindly help us on same.

**Comment by Haniel5** [comment]
@trunghieuvn

**Comment by trunghieuvn** [comment]
You can provide info version android from device test
