### ISSUE TITLE
shipping method error in 1.7.1v not complete to preview 

### ISSUE THREAD

**Issue by Ahmadkazbar** [inspireui/support#2972]
<img width="397" alt="Screen Shot 2020-05-02 at 01 14 43" src="https://user-images.githubusercontent.com/64666453/80845662-96787c80-8c12-11ea-8912-0fac8eb0c852.png">
<img width="394" alt="Screen Shot 2020-05-02 at 01 15 10" src="https://user-images.githubusercontent.com/64666453/80845666-9bd5c700-8c12-11ea-9db7-4eada02c5e03.png">

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all require info to continue with the support  - http://private.inspireui.com/ 

We're closing this ticket as is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!
