### ISSUE TITLE
Payment Methods Not working in Fluxstore Pro Magento Version v1.7.1

### ISSUE THREAD

**Issue by JohanSmith20** [inspireui/support#2975]
Step 1 (require): detail issues and screenshots: Now i configured the app v1.7.1 with my online store on Magento v2.3.4 and everything is working successfully until when i reach the Payment Methods it gives me an error saying: (**There is an issue with the app during request the data. please contact admin for fixing the issues Exception: Can not get payment methods**). [Screenshot attached].

*** I already sent to you through the private.inspireui.com everythin to help you to solve the problem including [**config.dart-config_en.json-payments.dart-Website Admin Login-Common Folder of my app-Proof of purchase**]

![ScreenShot Of the ISSUE](https://user-images.githubusercontent.com/64312037/80849584-105f3480-8c18-11ea-8c26-108cef3b1517.jpg)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com  : **DONE**

**Comment by JohanSmith20** [comment]
@minhcasi @trunghieuvn @vumanhsn97 @luyx2412 Please Solve this Issue!!

**Comment by minhcasi** [comment]
@JohanSmith20 - could i check if you have already config the payment from the Woocommerce setting? Which payment gateway you are using?

**Comment by JohanSmith20** [comment]
@minhcasi No i'm using Magento v2.3.4 not WooCommerce and i already sent to you a issue.zip which contain a text have the url of the admin website panel and the username and password of admin account. Also in this file you will find the config.dart and the common folder with all the files inside it and the config_en.json also.

*Note: Now i just configured Cash On Delivery Feature on Magento admin panel you can take a look on it.

**Comment by minhtruong315** [comment]
@JohanSmith20 I checked your website. I see it's not working. I can't find product to make place order.
https://www.dropbox.com/s/rj0m572hk3kg2wx/website.mov?dl=0

**Comment by JohanSmith20** [comment]
Ohh thats because i still didn't put the main categories on the home page but you can find the product at: https://krimzy.com/clothing

**Comment by JohanSmith20** [comment]
> @JohanSmith20 I checked your website. I see it's not working. I can't find product to make place order.
> https://www.dropbox.com/s/rj0m572hk3kg2wx/website.mov?dl=0
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/dbec08c2f0c321c36aab03391b1cd7f52fdfe8ef/68747470733a2f2f7777772e64726f70626f782e636f6d2f74656d705f7468756d625f66726f6d5f746f6b656e2f732f726a306d353732686b336b673277783f70726573657276655f7472616e73706172656e63793d46616c73652673697a653d3132303078313230302673697a655f6d6f64653d34">Dropbox**[website.mov](https://www.dropbox.com/s/rj0m572hk3kg2wx/website.mov?dl=0)**Shared with Dropbox

 Ohh thats because i still didn't put the main categories on the home page but you can find the product at: https://krimzy.com/clothing

**Comment by JohanSmith20** [comment]
I have discovered that the error was coming for the **include.path** and when i write the right path it worked successfully on the website and the app
I'm so sorry for making noise to you but you helped me to know the problem and its solution.
Thank you <3

**Comment by JohanSmith20** [comment]
Now there is a problem i have a product with price of: 482$ and after the sale, its price is: 361$ and when the product appears on the home page or inside any category it appears with the sale price but when i enter to buy it, it shows the original price and it make my buy it by the original price not the sale one. [See the Screenshots please]. @minhtruong315 

![Screenshot_2020-05-02-06-54-22](https://user-images.githubusercontent.com/64312037/80855573-89738180-8c42-11ea-97ce-2d742e6a0ffd.jpg)
![Screenshot_2020-05-02-06-59-14](https://user-images.githubusercontent.com/64312037/80855580-94c6ad00-8c42-11ea-8573-f1ede9d6b96d.jpg)
![Screenshot_2020-05-02-06-54-45](https://user-images.githubusercontent.com/64312037/80855582-95f7da00-8c42-11ea-965c-606799f3b718.jpg)
![Screenshot_2020-05-02-06-54-35](https://user-images.githubusercontent.com/64312037/80855583-96907080-8c42-11ea-8b51-87bd3c35c969.jpg)

**Comment by JohanSmith20** [comment]
@minhcasi @minhtruong315

**Comment by minhtruong315** [comment]
@JohanSmith20 I can't request api with this token
```
"url": "https://krimzy.com",
  "accessToken": "esmezoxbevhmrro7wml3joqx0a1g9y3k",
```

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
