### ISSUE TITLE
Showing store list based on radius

### ISSUE THREAD

**Issue by ganesha10** [inspireui/support#2976]
my website is https://www.wargakita.id and I would like to show radius filtered store list such as shown at the website for my apps. So when the user used the apps, the location will be acquired and only vendor within the radius will be shown. Is ti possible? Thank you.

**Comment by minhcasi** [comment]
Hi, could i know your site base on which dokan plugin? Did you store the vendor as long/lat from the admin side?

**Comment by ganesha10** [comment]
I am using WCFM, the store list is provided from WCFM such as described from [this documentation](https://docs.wclovers.com/store-list/).

**Comment by minhcasi** [comment]
@ganesha10 - thank you, we have updated as a feature request and will investigate - very best!

**Comment by minhcasi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [GeoLocation Vendor Search](https://trello.com/c/GlKgXx2p/32-geolocation-vendor-search)

**Comment by minhcasi** [comment]
moved to backlog for implementing

**Comment by enriqueleon80** [comment]
Howdy! 

Very excited to see this is under development, as I was going to code my own implementation.  Would it be possible to ask when this might get released?

**Comment by mumin-si** [comment]
I am also very excited to see how this will be implemented really a great feature

**Comment by mumin-si** [comment]
Any updates? Will plan for future based on response!
