### ISSUE TITLE
Problem when opening the application

### ISSUE THREAD

**Issue by eslamcasper** [inspireui/support#2977]
Step 1 (require): When opening the application this problem appears as in the screenshot

![GitHub Logo](https://e.top4top.io/p_1582l2x7t1.jpeg)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all require info to continue with the support  - http://private.inspireui.com/ 

We're closing this ticket as is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!
