### ISSUE TITLE
Fluxstore -  Translation and some errors

### ISSUE THREAD

**Issue by rodrigoalves1901** [inspireui/support#2978]
![image](https://user-images.githubusercontent.com/43248152/80852816-86a06e80-8bf9-11ea-845b-fd0ab995ccc0.png)

hello, I congratulate you for the application is getting very good.

I am using the latest version 1.7.1 and I still have some problems with the translation. Would you help me?

BY ATTRIBUTE
![image](https://user-images.githubusercontent.com/43248152/80852882-3e358080-8bfa-11ea-86a8-60192be88924.png)

CANCELL / REFUNDS
![image](https://user-images.githubusercontent.com/43248152/80852899-62915d00-8bfa-11ea-8e09-70e29b9a9730.png)

PROCESSING / CANCELLED / ON - HOLD
![image](https://user-images.githubusercontent.com/43248152/80852925-9d939080-8bfa-11ea-9252-8a77fbed61c4.png)

I would like to know if it is possible to add the Portuguese - Brazil language. I am making the file translated into Portuguese available.

[intl_es.zip](https://github.com/inspireui/support/files/4566947/intl_es.zip)

I also have other centralization errors
![image](https://user-images.githubusercontent.com/43248152/80852992-493ce080-8bfb-11ea-8228-e70585cfce20.png)

![image](https://user-images.githubusercontent.com/43248152/80853020-6e315380-8bfb-11ea-8607-97d814a7eb25.png)

**Comment by minhcasi** [comment]
@rodrigoalves1901 - thank you for sharing the translated file 

We will have a check the solution and let you know

**Comment by kvt0012** [comment]
We're working on it and will have update soon, thank you.
