### ISSUE TITLE
[FluxStore-MV] Stores list no show 

### ISSUE THREAD

**Issue by kenneth1690** [inspireui/support#2979]
No show store list, and is posible show store in home? 

i use WCFM

**Comment by minhcasi** [comment]
@kenneth1690 could you help to share the screenshot issue pls? could i confirm you have tested on latest version - thank you!

**Comment by kenneth1690** [comment]
![image](https://user-images.githubusercontent.com/1425445/80897536-e90b7480-8cb6-11ea-9700-f58a59b10b70.png)


is posible show store list in home screen? 

![image](https://user-images.githubusercontent.com/1425445/80897544-10fad800-8cb7-11ea-9dd9-baf372aee039.png)

**Comment by minhcasi** [comment]
@trunghieuvn - pls help to investigate

**Comment by kenneth1690** [comment]
new question,  i build de app in release, but open de app, only show splash screen

**Comment by minhcasi** [comment]
@kenneth1690 - pls try to double-check the bundle ID to see if you have changed it correctly?
please check more detail - https://docs.inspireui.com/fluxstore/delivery-android/

**Comment by Jazzykhan** [comment]
can we show stores screen on home? means all stores on home how to do that? is there any json that we can or code please share @minhcasi 
thanks
