### ISSUE TITLE
[ListApp] Need Help

### ISSUE THREAD

**Issue by bobozd** [inspireui/support#298]
![screen shot 2019-02-13 at 13 43 25](https://user-images.githubusercontent.com/28021993/52712870-31495480-2f96-11e9-93ab-9f7cbdc51bba.png)
Listapp Mylisting theme used.

1. When I click on Login Facebook account it asks me for BeoNews facebook page. How can I change iot to my facebook page?

2. When I click on specific listing there is BOOKING button in lower right corner. How can I change it to CONTACT ME button and start calling phone number added while filling listing form on backend?

3. How can I change BROWSE MORE PLACES text with something else on app homepage.

4. Login page / error message "JWT is not configured properly, please contact admin." when click on LOGIN button.

5. Where I can change TABLE section inside each listing. I would like it to configure differently then it is now. This is for apatments and my service is completely differetn.

Thanks.

**Comment by thangvo9x** [comment]
Hi. Please refer 
1. You can change it Config/YourTheme (myListing,...) with name Facebook (logInID)
2. Change it in Common/Languages.js. Calling phone will be auto start when run on real device .
3. such as Common/Languages.js
4. Please refer documents https://wordpress.org/plugins/jwt-authentication-for-wp-rest-api/
5. You can change it Config/YourTheme (myListing,...) with name ListingData for ordering/sort/remove.
Thanks

**Comment by bobozd** [comment]
Thanks for help.

6. Is it possible to change background color and text color only on this FIND ON MAP section and how?
![screen shot 2019-02-14 at 09 12 21](https://user-images.githubusercontent.com/28021993/52772479-d9175e80-3038-11e9-97e9-f7069b47a55c.png)

**Comment by bobozd** [comment]
Also, under Price Per Image section (originaly called Table)
how can I connect my keys (exterior,interior...) with one from the wordpress backend) so it loads correctly?

thanks.
![screen shot 2019-02-14 at 09 17 13](https://user-images.githubusercontent.com/28021993/52772726-85f1db80-3039-11e9-9e95-178d76f6ad39.png)

**Comment by bobozd** [comment]
I would like under listing thumbnail image to have this
LISTING NAME (like it is now with bolded font)
City, Country - in the same line / not listing description like it is now
how can do this. thanks so much.
![screen shot 2019-02-14 at 09 52 41](https://user-images.githubusercontent.com/28021993/52774822-75902f80-303e-11e9-9e64-f3da9f1c61bb.png)

**Comment by thangvo9x** [comment]
Hi. 
1.The keys are loaded from your backend.
2. change background -> Components/BrowseLocation/index.js to change it
3. To change it , you must have to go to Components/PostLayout/Column/index.js and change it. Thanks

**Comment by bobozd** [comment]
Images not loaded. Thumbnails and images regenerated with backend plugin.
![screenshot 2019-02-21 at 20 41 48](https://user-images.githubusercontent.com/28021993/53196818-356e1580-3619-11e9-993d-0f52349d97a6.png)
![screenshot 2019-02-21 at 20 41 58](https://user-images.githubusercontent.com/28021993/53196821-356e1580-3619-11e9-81a0-ca0cda0ad426.png)
