### ISSUE TITLE
Cannot login in fluxtore app. Showing code error.

### ISSUE THREAD

**Issue by maynard88** [inspireui/support#2980]
Step 1 (require): detail issues and screenshots

![image](https://user-images.githubusercontent.com/13436953/80857416-96b16000-8c84-11ea-86c6-107dff58039c.png)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by maynard88** [comment]
I have processed step two already.

**Comment by maynard88** [comment]
I trace the code. the root cause of the issue was the method - Future<Map<String, dynamic>> getCategoryCache on file woo_commerce.dart and throwing exception on line 966. The api rest url is throwing error.

**Comment by maynard88** [comment]
Further details of the error is on mstore wordpress plugin. The error dues to this one.

![image](https://user-images.githubusercontent.com/13436953/80858926-7a66f080-8c8f-11ea-8f41-75b6f8f86929.png)

**Comment by maynard88** [comment]
Hello I am able to login now but your wordpress plugin needs updating. I commented this to fluttersuser.php and mstore user.php. You need to check if user has avatar or not I believe.  

![image](https://user-images.githubusercontent.com/13436953/80859615-ded87e80-8c94-11ea-8ec3-4b11c3c3d652.png)

**Comment by minhcasi** [comment]
@maynard88 appreciated for your sharing - we will investigate and fix this issue

@minhtruong315 - pls help to have a check

**Comment by minhtruong315** [comment]
@maynard88 can u send me admin account to login to your website via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/2980

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
