### ISSUE TITLE
[MultiVendor] Categories are returning Empty List

### ISSUE THREAD

**Issue by jinuem** [inspireui/support#2981]
Step 1 (require): detail issues and screenshots

I am using Doken for my MultiVendor Store.
Configured the App and Tried to Open it. But categories are not coming. Its Empty list [ ]. 
But I have Categories in my Wocommerce.
<img width="1680" alt="Screenshot 2020-05-02 18 17 13" src="https://user-images.githubusercontent.com/3512723/80864586-514f5b80-8ca1-11ea-80cc-0d4eaa551889.png">

Also as per the documentation (https://docs.inspireui.com/fluxstore/multi-vendor/)
> 💡 Tip: to quickly show the category ID, go to lib/models/category.dart and print the returned categories object from the returned JSON.

There is no such file. But I can find lib/models/category/category_model.dart . Hope that's the right file. Printed the Category to find the IDs. but returns the empty list.
<img width="1032" alt="Screenshot 2020-05-02 at 6 25 00 PM" src="https://user-images.githubusercontent.com/3512723/80864756-41844700-8ca2-11ea-976e-c6f860ac53e3.png">

So I debugged more, I am getting a Signature error (woocommerce_rest_authentication_error) from WooCommerce.
<img width="768" alt="Screenshot 2020-05-02 18 59 45" src="https://user-images.githubusercontent.com/3512723/80865450-354eb880-8ca7-11ea-8067-ecb11f91c89a.png">
<img width="762" alt="Screenshot 2020-05-02 19 15 34" src="https://user-images.githubusercontent.com/3512723/80865820-57e1d100-8ca9-11ea-9e93-2130c74f85dc.png">

But I can see the list of vendors in the store screen. If the key is not valid. how this list is loaded?
<img width="874" alt="Screenshot 2020-05-02 at 7 02 52 PM" src="https://user-images.githubusercontent.com/3512723/80865502-89599d00-8ca7-11ea-92dd-896690675d26.png">

Steps already were taken:
- Recreated the WooCommerce Keys.
- Legacy APIs enabled.

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com
Submitted!

**Comment by maynard88** [comment]
Hello you need to put the secret key and consumer key on config.dart.  - https://docs.inspireui.com/fluxstore/woocommerce-setup/

**Comment by jinuem** [comment]
@maynard88 Yes, Already added the keys in config.dart file.

const serverConfig = {
  "type": "dokan",
  "url": "http://170.249.194.58/~democam/",

  /// document: https://docs.inspireui.com/fluxstore/woocommerce-setup/
  "consumerKey": "ck_XXXXXXXX60876f18fcd5b3e7a11f73dd31506e1d81",
  "consumerSecret": "cs_XXXXXX49a426a2a8689194c24867e6033d4889",

  /// Your website woocommerce. You can remove this line if it same url
  "blog": "http://170.249.194.58/~democam/",

  /// set blank to use as native screen
  "forgetPassword":
      "http://170.249.194.58/~democam/wp-login.php?action=lostpassword"
};


The same key I have used in Postman and it's working against "OAuth 1.0" Authorization.
<img width="1384" alt="Screenshot 2020-05-02 at 8 46 40 PM" src="https://user-images.githubusercontent.com/3512723/80868103-0ab82c00-8cb6-11ea-8d41-46240f628bc0.png">

**Comment by maynard88** [comment]
I believe this is the way the app gets categories. Run the url on your browser and replace values. This should load json data.

http://170.249.194.58/~democam/wp-json/wc/v2/flutter/category/cache?categoryIds=58,20,84,82,83,22,21&consumer_key=CSKEY&consumer_secret=CSECRET

58,20,84,82,83,22,21 --> replace with your categorids
CSECRET --> replace with your secret key
CSKEY --> replace with your consumer key



If you see errors, then something is wrong with the key or I my initial guest is that your url setup with ~ is not working properly.

**Comment by jinuem** [comment]
@maynard88 
This is the way App Gets the Categories: 
<img width="1375" alt="Screenshot 2020-05-02 21 54 16" src="https://user-images.githubusercontent.com/3512723/80869691-7f439880-8cbf-11ea-9696-aaaba4ea4c40.png">

URLREQUEST :
`http://170.249.194.58/~democam//wp-json/wc/v2/products/categories?exclude=311&lang=en&oauth_consumer_key=ck_XXXXXXXXXXXXXXXXXXXXXXXXXXX&oauth_nonce=wfzibqibha&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1588436614&oauth_token=&oauth_version=1.0&page=1&per_page=100&oauth_signature=XXXXXXXXXXXXXXXXXXXX`

May be Invalid Signature is generated in the code.
Thats why WooCommerce Returns this error 
`{"code":"woocommerce_rest_authentication_error","message":"Invalid signature - provided signature does not match.","data":{"status":401}}`

**Comment by maynard88** [comment]
Remove the photo your key is showing.

Try to deploy your app on a url like http://170.249.194.58/demo. Remove the ~ sign.

**Comment by jinuem** [comment]
@maynard88 that's not the issue. I checked. Still same error.

**Comment by minhcasi** [comment]
@jinuem - try to remove "/" from the end of URL, there is "//" that caused the issue

**Comment by jinuem** [comment]
@minhcasi wow thanks a lot. It got fixed. But I am getting an error in the Vendor Visit Store page.
Reproduce Steps- >
Go to Stores -> Visit Store- > ERROR
![Screenshot 2020-05-03 at 11 37 11 AM](https://user-images.githubusercontent.com/3512723/80907196-6f18d100-8d32-11ea-9f9e-caa78a0b83af.png)
 

Any idea why its coming?

**Comment by jeanelvis** [comment]
{"code":"rest_forbidden","message":"Sem permiss\u00e3o para fazer isso.","data":{"status":401}}

**Comment by minhcasi** [comment]
@trunghieuvn - pls help to investigate

**Comment by jinuem** [comment]
@minhcasi @trunghieuvn 
any Update?

**Comment by kenneth1690** [comment]
i have similar error

**Comment by minhtruong315** [comment]
@jinuem can you config domain for your website? rest api doesn't work in this url
```http://170.249.194.58/~democam/```

**Comment by jinuem** [comment]
@minhtruong315 changed to https://businessmela.com/
Still the same issue.

**Comment by kenneth1690** [comment]
> @minhcasi wow thanks a lot. It got fixed. But I am getting an error in the Vendor Visit Store page.
> Reproduce Steps- >
> Go to Stores -> Visit Store- > ERROR
> ![Screenshot 2020-05-03 at 11 37 11 AM](https://user-images.githubusercontent.com/3512723/80907196-6f18d100-8d32-11ea-9f9e-caa78a0b83af.png)
> 
> Debugged and Got this following UserModal.User and Vendor Email as Null.
> What supposed to come in User when visiting the Store?
> Vendor Email, I am having Vendor Email in the backend settings. Why it's empty here?
> 
> <img alt="Screenshot 2020-05-03 12 03 20" width="836" src="https://user-images.githubusercontent.com/3512723/80907746-2c0d2c80-8d37-11ea-900c-c5f06d19ff43.png">
> 
> Any idea why it's coming?

i fix, temporal 

![image](https://user-images.githubusercontent.com/1425445/81108489-05392c80-8ed6-11ea-81c0-7816b223f9aa.png)

**Comment by minhtruong315** [comment]
@jinuem it's working well. can u upload your source  code to git repo then add my email: minhtruong315@gmail.com. I will checkout your source code and check on  it
<img width="424" alt="Screen Shot 2020-05-06 at 6 33 54 AM" src="https://user-images.githubusercontent.com/10402500/81125862-b5a14200-8f63-11ea-8d95-11d0479733c5.png">

**Comment by jinuem** [comment]
@minhtruong315 Hi. the screenshot you sent is a Category page.

But The issue I am talking about is STORE DETAIL SCREEN.

Go to this page:
STORES-> LIST OF STORES ->VISIT STORE 
You definitely see the error.

![Screen Recording 2020-05-06 at 2 01 16 PM](https://user-images.githubusercontent.com/3512723/81155493-a2619700-8fa2-11ea-9eea-40faa172d716.gif)

Anyway, I have given access to my Repo. Plz look into it

**Comment by kenngigz** [comment]
I am having the same issue,
 
![Screenshot_2020-05-06-19-29-16](https://user-images.githubusercontent.com/57593885/81203172-4ca3e380-8fd0-11ea-8e02-8273e79694e7.png)

**Comment by minhtruong315** [comment]
@jinuem please pull source code and check again. I fixed it

**Comment by minhtruong315** [comment]
@kenneth1690 replace this file lib/vendor/store_detail/store_detail_screen.dart to fix that issue
[store_detail_screen.dart.zip](https://github.com/inspireui/support/files/4590814/store_detail_screen.dart.zip)
