### ISSUE TITLE
Item Showing Out of Stock on App but its instock

### ISSUE THREAD

**Issue by mahajansahab** [inspireui/support#2983]
http://167.71.234.47/index.php?route=product/product&path=59&product_id=50

This item is showing out of stock on app.

I am using FluxStore for Opencart

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all require info to continue with the support  - http://private.inspireui.com/ 

We're closing this ticket as is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by mahajansahab** [comment]
Hi I have created Ticket ID#3114 & 3115 again showing that I am unable to upload the pdf license file in your google docs form.
Please help me out on this asap.
