### ISSUE TITLE
 issue in the cart

### ISSUE THREAD

**Issue by yasernet1989** [inspireui/support#2984]
Step 1 (require): detail issues and screenshots
![5555](https://user-images.githubusercontent.com/64695299/80867149-3d086000-8c9b-11ea-82d4-2e8cd60ac989.png)

I'm facing this issue in the cart. i saw that its fixed in the newest version.
please specify which file should i update to fix this issue as i dont want to mess up my stable code

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com
![4444](https://user-images.githubusercontent.com/64695299/80866991-670d5280-8c9a-11ea-9d02-17c1cd6c8f66.png)

**Comment by minhcasi** [comment]
@yasernet1989 - pls use the latest 1.7.x to fix this issue - thank you!

**Comment by yasernet1989** [comment]
@minhcasi - can you please read me question once again?
i know its fixed in the 1.7 version. my question which file exactly should i replace to fix this issue?
