### ISSUE TITLE
Problem when opening the application

### ISSUE THREAD

**Issue by eslamcasper** [inspireui/support#2985]
Step 1 (require): When opening the application this problem appears as in the screenshot

![GitHub Logo](https://e.top4top.io/p_1582l2x7t1.jpeg)

Also, there is a problem in displaying product pictures, as all pictures do not appear, and there is a problem that occurs when you click on the vendor name in the vendor information tab

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by maynard88** [comment]
Hello did you some how created a break point and on debug mode?

Also make sure to delete the build folder and delete the installed apk. Let me know if it works.

**Comment by eslamcasper** [comment]
> Hello did you some how created a break point and on debug mode?
> 
> Also make sure to delete the build folder and delete the installed apk. Let me know if it works.

I didn't do that either, let me know where I'm deleting the build folder and the apk file because they're not in the project directory.
  I just modified the config.js file to set the Arabic language and the currency in the Arabic language

**Comment by maynard88** [comment]
Hello when you download the latest fluxstore, under source folder there should be a build folder. Delete that folder before running the app. Delete also the app installed on your mobile. ( in case you are connecting your phone) 

![image](https://user-images.githubusercontent.com/13436953/80869129-15cc8580-8cd1-11ea-8da9-0990ccd92479.png)

I have encountered this before and that did the trick.

**Comment by eslamcasper** [comment]
My project is mstore-mv-expo and not fluxstore

> Hello when you download the latest fluxstore, under source folder there should be a build folder. Delete that folder before running the app. Delete also the app installed on your mobile. ( in case you are connecting your phone)
> 
> ![image](https://user-images.githubusercontent.com/13436953/80869129-15cc8580-8cd1-11ea-8da9-0990ccd92479.png)
> 
> I have encountered this before and that did the trick.

**Comment by ameenbadri7** [comment]
just do on the terminal : flutter clean and run the build again.

**Comment by eslamcasper** [comment]
> just do on the terminal : flutter clean and run the build again.

My project is mstore-mv-expo and not fluxstore

**Comment by luyx2412** [comment]
Hi @maynard88 the issue related when can not get categories from wordpress site. Please make sure you config right way in your website. https://docs.inspireui.com/mstore-mv/getting-started/

Thanks

**Comment by eslamcasper** [comment]
The attached guide in the link has been verified in this response and I have implemented what is needed in it as it is but the problem still exists.
What is the solution ?

> Hi @maynard88 the issue related when can not get categories from wordpress site. Please make sure you config right way in your website. https://docs.inspireui.com/mstore-mv/getting-started/
> 
> Thanks
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/c1f5c35bdee2cf5a71b0e35ef38becdf8ec89d72/68747470733a2f2f646f63732e696e737069726575692e636f6d2f696d616765732f6d6574612f47686f73742d446f63732e6a7067">InspireUI Document**[MStore Multi Vendor - Complete React Native template for WooCommerce](https://docs.inspireui.com/mstore-mv/getting-started/)**You are shop-owners of physical stores with high-traffic consumers and think to go digital. Or you are online shop-owners with E-Commerce websites. Both of you want to maximize sale opportunities.  You are developers who are challenged to develop store mobile application in a shorter time.  You question how can MStore help. Here are your answers.

**Comment by eslamcasper** [comment]
The problem does not appear when I tried it in a simulator, I need to delete the cash expo in my phone.
But now there are problems that existed before, when I click on the favorite icon in the top menu when it is empty, this error appears:

![GitHub Logo](https://i.top4top.io/p_1584ilmfx1.gif)

**Comment by luyx2412** [comment]
Hi @maynard88 can you send your project via inspireui.team@gmail.com? Let me investigate about it.

Thanks

**Comment by eslamcasper** [comment]
> Hi @maynard88 can you send your project via [inspireui.team@gmail.com](mailto:inspireui.team@gmail.com)? Let me investigate about it.
> 
> Thanks

Sent, but unfortunately I haven't received a response yet

**Comment by eslamcasper** [comment]
Hello, I sent the project 5 days ago and no response was sent

‫في الاثنين، 4 مايو 2020 في 4:27 م تمت كتابة ما يلي بواسطة ‪luyx2412‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by minhcasi** [comment]
@eslamcasper - sorry related issues as our team is off a few days due to the CoV issues

@luyx2412 - pls help to check as a high priority - thank you!

**Comment by luyx2412** [comment]
Hi @eslamcasper Sorry about reply you late.
In `src/containers/WishList/index.js` replace this file with this attach to fix your issues.
[index.js.zip](https://github.com/inspireui/support/files/4602946/index.js.zip)

![image](https://user-images.githubusercontent.com/8909619/81467577-bfe16b80-9203-11ea-83a3-84f3eafdc986.png)

Thanks

**Comment by eslamcasper** [comment]
1- When clicking seller details on the product page, the error appears as in the screenshot:
![GitHub Logo](https://j.top4top.io/p_1591kigp11.png)


2- Also, there is another problem when I choose the country on the page to finish the request to not be chosen and this page cannot be passed without selecting the country taking into account that I have already chosen it:
![GitHub Logo](https://k.top4top.io/p_1591mncfn2.png)


3- How do I make the top bar in the application on the home page to be a specific color instead of being transparent? I mean the tape indicated in this screenshot:
![GitHub Logo](https://l.top4top.io/p_15911gysa3.png)


4- How to deactivate the conversations icon as in the screenshot:
![GitHub Logo](https://a.top4top.io/p_1591ch1p04.png)
Also, I cancel the chat list page in the side menu.



5- How to remove category icons in the main page of the application, as in this screenshot:
![GitHub Logo](https://b.top4top.io/p_1591j4nuc5.png)


6- How do I delete the date and the day found on the home page.


7- Finally, how do I make the default application language Arabic and deactivate any other language?

**Comment by eslamcasper** [comment]
Hello, I apologize for the inconvenience
But I am committed to an application delivery date. Please see the previous response and help me solve these problems.

**Comment by eslamcasper** [comment]
I am awaiting a response from you, please respond quickly

**Comment by luyx2412** [comment]
HI @maynard88 Sorry about reply you late. Can you send me your project via inspireui.team@gmail.com? Let me investigate easier.

Thanks

**Comment by eslamcasper** [comment]
Submitted, but please speed up the work and if you have any answer to the questions above, please answer me

**Comment by luyx2412** [comment]
Hi @eslamcasper Sorry about reply you late. I am investigating your project and will fix it.

Thanks

**Comment by luyx2412** [comment]
Hi @eslamcasper I just fix your project.
1. Fixed
2. Fixed
3. In each screen you can edit `headerStyle` to your style. This is a document about that. https://reactnavigation.org/docs/4.x/stack-navigator/#headerstyle
![image](https://user-images.githubusercontent.com/8909619/82352337-03b84a00-9a28-11ea-9a77-2664416b7dde.png)
4. I removed it, in `src/containers/Detail/index.js` line 524. you can edit the variable depend on you. I commented the code.
![image](https://user-images.githubusercontent.com/8909619/82352449-35311580-9a28-11ea-956e-c836fc34d56e.png)

5. I commented the code in `src/components/HorizonList/Hlist.js` line 175
![image](https://user-images.githubusercontent.com/8909619/82352537-572a9800-9a28-11ea-827c-2097eb4e0ef5.png)

6. I commented it. In `src/components/HorizonList/index.js` line 92
![image](https://user-images.githubusercontent.com/8909619/82352633-732e3980-9a28-11ea-8396-f0bceba363ee.png)
7. In `src/common/Constants.js` line 19. you can change language in there
![image](https://user-images.githubusercontent.com/8909619/82352708-8e00ae00-9a28-11ea-91c2-81b61b15009a.png)

P/S: i sent to your email.

Thanks

**Comment by eslamcasper** [comment]
How to translate this phrase as in the screenshot I searched for a lot and did not find it:

![GitHub Logo](https://k.top4top.io/p_1601l09dx1.png)

How to translate the word Vendor and also set its direction. The page appears blank as in the screenshot : 

![GitHub Logo](https://l.top4top.io/p_1601cv2652.png)

Translate the word products as shown in the screenshot:

![GitHub Logo](https://a.top4top.io/p_1601c2pd83.png)

How to translate the text in this screenshot: 

![GitHub Logo](https://b.top4top.io/p_16013rzuu4.png)

**Comment by luyx2412** [comment]
Hi @eslamcasper Please add the language in `src/common/Languages.js` same the screenshot
![image](https://user-images.githubusercontent.com/8909619/82721722-25e0ef00-9cea-11ea-9078-8e2a7f168b1b.png)

- With the categories screen, please change text in `src/containers/Categories/CategoriesTab.js` line 142
![image](https://user-images.githubusercontent.com/8909619/82721740-5759ba80-9cea-11ea-9060-0f69bd541c90.png)

Thanks

**Comment by eslamcasper** [comment]
>Thank you, but what about this
> How to translate the word Vendor and also set its direction. The page appears blank as in the screenshot :
> 
> ![GitHub Logo](https://camo.githubusercontent.com/77b164ffc3ea871083caa97ef67b571c60226b5f/68747470733a2f2f6c2e746f7034746f702e696f2f705f313630316376323635322e706e67)
>

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
