### ISSUE TITLE
ios build error and cebuilder not working on macos

### ISSUE THREAD

**Issue by Ibrahimmohammedevuti** [inspireui/support#2986]
Step 1 (require): detail issues and screenshots

<img width="1440" alt="Screen Shot 2020-05-02 at 5 08 08 PM" src="https://user-images.githubusercontent.com/38354564/80869419-34625a80-8c98-11ea-994e-c7ba16d2041c.png">
<img width="1440" alt="Screen Shot 2020-05-02 at 5 02 05 PM" src="https://user-images.githubusercontent.com/38354564/80869433-447a3a00-8c98-11ea-8e0f-ca8df8e995b7.png">

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

![mstore proof](https://user-images.githubusercontent.com/38354564/80869221-1f38fc00-8c97-11ea-98df-423c94395a83.jpg)

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by Ibrahimmohammedevuti** [comment]
<img width="1440" alt="Screen Shot 2020-05-02 at 5 08 01 PM" src="https://user-images.githubusercontent.com/38354564/80869456-5f4cae80-8c98-11ea-849d-a600800d278d.png">

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all require info to continue with the support  - http://private.inspireui.com/ 

We're closing this ticket as is not provided enough detail (as we could not verify from above screenshot), kindly reopen the ticket after you have done the form submission. Thank you for your time!
