### ISSUE TITLE
No Products Displaying [FluxStore MV]

### ISSUE THREAD

**Issue by josefmvs** [inspireui/support#2987]
I'm getting these errors on compile time.

1. getFilterTags: NoSuchMethodError: The method 'getFilterTags' was called on null.
2. getFilterAttributes: NoSuchMethodError: The method 'getFilterAttributes' was called on null.

When you click a product nothing is displayed on product screen
Sometimes on Home screen, I get a white screen.

Please see the files submitted via google docs here for screenshots
http://private.inspireui.com/

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by josefmvs** [comment]
![plugins 1](https://user-images.githubusercontent.com/12368884/80894538-4d0d5780-8d0e-11ea-8f9a-3acc21ec21ac.PNG)


![plugins 2](https://user-images.githubusercontent.com/12368884/80894544-572f5600-8d0e-11ea-9db5-c86e8dad4e48.PNG)

**Comment by josefmvs** [comment]
ERRORS;

1. getFilterTags: NoSuchMethodError: The method 'getFilterTags' was called on null.
2. getFilterAttributes: NoSuchMethodError: The method 'getFilterAttributes' was called on null.

SCREENSHOTS:

![error 1](https://user-images.githubusercontent.com/12368884/80894671-9dd18000-8d0f-11ea-88e6-c5fba9d46914.PNG)


![error 3](https://user-images.githubusercontent.com/12368884/80894673-a4f88e00-8d0f-11ea-8838-742ca00d380d.PNG)


![error 3](https://user-images.githubusercontent.com/12368884/80894678-b5106d80-8d0f-11ea-871a-75a1c4f9c611.PNG)


![error on compile](https://user-images.githubusercontent.com/12368884/80894681-bb9ee500-8d0f-11ea-9f31-231ef4f63dde.PNG)

**Comment by josefmvs** [comment]
![purchase](https://user-images.githubusercontent.com/12368884/80894720-16d0d780-8d10-11ea-87e9-7a3724ce1612.PNG)

**Comment by minhcasi** [comment]
@josefmvs could you try to test if your simulator could reach your local host URL? Please help to check this guide https://www.youtube.com/watch?v=CEyfZmzBMTw

**Comment by josefmvs** [comment]
Thank you for replying. I'll try.

**Comment by josefmvs** [comment]
I check the video and I see that I have already went through the video a few times. 

I see that it has different config.dart:

import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:fstore/common/constants.dart';

/// Server config
const serverConfig = {
  "type": "woo",
  "url": "http://mstore.local",
  "consumerKey": "ck_98f9ca71c82ec652ac27194eafef4a9cf2af300a",
  "consumerSecret": "cs_83d385c0711ace08304126f48618d7a9aa7ff663",
  "blog": "http://mstore.local",
  "forgetPassword": "http://mstore.local/wp-login.php?action=lostpassword"
};

const afterShip = {
  "api": "e2e9bae8-ee39-46a9-a084-781d0139274f",
  "tracking_url": "https://fluxstore.aftership.com"
};

const CategoriesListLayout = kCategoriesLayout.card;

const Payments = {
  "paypal": "assets/icons/payment/paypal.png",
  "stripe": "assets/icons/payment/stripe.png",
  "razorpay": "assets/icons/payment/razorpay.png",
};
etc...

But it's looking for the other packages like:

 export 'config/advertise.dart';
 export 'config/general.dart';
 export 'config/onboarding.dart';
 export 'config/payments.dart';
 export 'config/products.dart';
 export 'config/smartchat.dart';

**Comment by josefmvs** [comment]
Please tell what should I change? Or where to look specifically?

**Comment by minhcasi** [comment]
@josefmvs - on the latest version we have updated the config easily format - https://tppr.me/4vAKv

Please try to check the video and config your virtual host mstore.local - you could also change to another name, the important is it could be reached from your simulator

**Comment by josefmvs** [comment]
In my very first post I have done the steps required like uploading the screenshots to 
http://private.inspireui.com/ but I think you guys have not looked at it. What you are showing to me is already in my screenshots uploaded. Meaning, I have already done that. 

Please look the files uploaded first and see what I am missing. I am using the same format that's I was able to notice that in the video, config is different.

**Comment by HumerCode** [comment]
I have the same problem.

**Comment by minhcasi** [comment]
@trunghieuvn - pls investigate - thanks

**Comment by josefmvs** [comment]
I am able to browse through my woocommerce site throught the mobile browser without any issue. Thus that mean there's shouldn't be any issue w/ accessing the api from flutter app?

**Comment by josefmvs** [comment]
Please I need it resolved this week.

**Comment by HumerCode** [comment]
Surfing from FluxBuilder i can see categories, but when on emulator i cant see nothing also nothing on real device.
So what might be the problem in the app or in our config files??

**Comment by minhcasi** [comment]
@josefmvs 

1- could you share your whole screen issues when you run the app on the simulator
2. What is your local URL website? Does it is reachable from the simulator browser?

**Comment by josefmvs** [comment]
Yes, it ease reachable. I exposed it on the internet through ngrok and was able to access wordpress site through my mobile.

**Comment by minhcasi** [comment]
could you share your whole screen issues when you run the app on the simulator? We need more clue to investigating.

Could you able to load the homepage so far?

**Comment by HumerCode** [comment]
Hi, can you solve this or do i need to open duplicate ticket? seems that is the problem with woo, your dokan test site works.

**Comment by HumerCode** [comment]
UPDATE
When i switch my config file "type": "woo", to "type": "dokan", i can see categories but not home screen....

**Comment by minhcasi** [comment]
@HumerCode - the vendor product is only supported type dokan or wfcm - the setting woo will not working - thank you!

**Comment by josefmvs** [comment]
hi. I am just going to check again. Because after changing so many things that app does not open now. I'll retry the whole setup. thanks. I got busy w/ other things.

**Comment by TAMS2018** [comment]
Hello i had same issue, so many time been check and properly followed the  guidelines but still no work.

my main Issue: 
1. several products not displaying on app.
2. shipping rate that i configures on my woo-commerce  is not also appeared during check out.
3. several time i tried to upload the new products some error appeared like. "FormatException: unexpected Character (at Character 1)
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"
