### ISSUE TITLE
[Fluxstore-MV] Share button for blog pages and product 

### ISSUE THREAD

**Issue by ideas24** [inspireui/support#2988]
Step 1 (require): detail issues and screenshots
Please how can I enable native share for my blogs and single product page?
On my website and mobile, I'm able to share blogs to the various social media platforms. How can I achieve the same on the app, please?

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhcasi** [comment]
@ideas24 - the native sharing is already supported from Product, you could try this feature https://tppr.me/mtSuo

**Comment by ideas24** [comment]
@minhcasi oh thanks. What about the blogs sharing please ?

**Comment by kvt0012** [comment]
This feature is not available on out app now, we will develop it on the future, thanks for your recommendation.

**Comment by minhcasi** [comment]
@ideas24 - pls try to use
```
import 'package:share/share.dart';
....
Share.share(blog.url)
```

**Comment by ideas24** [comment]
@minhcasi on which page should I insert the code? Thanks
