### ISSUE TITLE
[Magento mstore] - Can't get data from server

### ISSUE THREAD

**Issue by RashVenkat6795** [inspireui/support#2989]
Step 1 (require): detail issues and screenshots
Installed cebuilder - gave the project folder path - web URL and also the accesstoken configured in magento admin panel - when I run the app through expo client - Getting can't get data from server toast. Not able to proceed further. Please guide me on this how to proceed?

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com
Please find the attachment
<img width="1031" alt="Screenshot 2020-05-02 at 11 22 12 PM" src="https://user-images.githubusercontent.com/26426904/80871917-452cc380-8ccc-11ea-8674-fc7701f7be74.png">

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhcasi** [comment]
@RashVenkat6795 - could you share your config file and the screenshot issues ?

**Comment by RashVenkat6795** [comment]
@minhcasi Yes sure here it is
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-05-03 at 11 17 16](https://user-images.githubusercontent.com/26426904/80902653-ca958f80-8d2f-11ea-9b46-2aabe0fd75fe.png)

[Config.js.zip](https://github.com/inspireui/support/files/4569688/Config.js.zip)

**Comment by minhtruong315** [comment]
@RashVenkat6795 send me AppConfig.js to check your website.
Thanks

**Comment by RashVenkat6795** [comment]
@minhtruong315 Please find the attachment
[AppConfig.json.zip](https://github.com/inspireui/support/files/4579676/AppConfig.json.zip)

**Comment by minhtruong315** [comment]
@RashVenkat6795 You haven't installed MStore extension on your website
<img width="898" alt="Screen Shot 2020-05-06 at 6 36 39 AM" src="https://user-images.githubusercontent.com/10402500/81125969-0a44bd00-8f64-11ea-817a-26162eda2edf.png">
Please check this guide to install MStore extension
https://docs.inspireui.com/fluxstore/magento-setup/
<img width="720" alt="Screen Shot 2020-05-06 at 6 38 55 AM" src="https://user-images.githubusercontent.com/10402500/81126047-47a94a80-8f64-11ea-8e8a-a634a6210b94.png">

**Comment by RashVenkat6795** [comment]
@minhtruong315  will do these steps, check and get back. Thanks!

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
