### ISSUE TITLE
[MSTORE-MV] Shipping Charges Error (Show Stopper)

### ISSUE THREAD

**Issue by nghonyuen** [inspireui/support#299]
**Required Info (please complete the following information):**
* Product: MSTORE-MV
* Your Purchased Code: 34a1d23d-c198-4cd8-beec-b4d0881c6437
(we may not reply if you are not our customer)

**Describe the bug**
The bug happens when buyer purchase goods from more than 1 seller. These 2 sellers located in different location, hence is charging different shipping rate even when delivering to the same destination. E.g. Seller A charges USD 1.00 shipping charges where as Seller B charges USD 2.00. The shipping screens doesn't show the correct charges and hence when proceed to payment (mstore-checout), it get rejected.

**Screenshots**
Sample screen shots from wordpress
![whatsapp image 2019-02-13 at 1 32 16 am](https://user-images.githubusercontent.com/47480781/52713478-61164d80-2fd2-11e9-8c18-aedf8ccf1d2d.jpeg)

**Additional context**
Add any other detail logs about the problem here.
If possible please share your config.js that use for the app setting

**Comment by nghonyuen** [comment]
Hi, may I know if there's any update? Tsk

**Comment by minhcasi** [comment]
Hi @nghonyuen  is it possible to share your config and the login account testing for the above screenshot? Thanks

**Comment by nghonyuen** [comment]
Certainly, may I know which email I should send to? Thanks

**Comment by nghonyuen** [comment]
Hi @minhcasi 

Of 2nd thought, no need to have login account, you can visit our development site https://farm2table-dev.tk/ and 'purchase' the goods according to the screen shot to reproduce the issue. 

Let me know how I can help to expedite. Thanks! :)

**Comment by thangvo9x** [comment]
Hi. This problem is your's website. but the team checked to help you. Some problems are coming from set calculate shipping.
