### ISSUE TITLE
Splashscreen version 1.7.0

### ISSUE THREAD

**Issue by mohamedibrahim89** [inspireui/support#2990]
try to change splash screen to my gif but not reflect in app and app make logo splash screen I don't know why
<img width="1440" alt="Screen Shot 2020-05-02 at 9 51 03 PM" src="https://user-images.githubusercontent.com/35544603/80890804-042eb200-8cc0-11ea-8bee-8350da1a79f7.png">

second can u tell me it u fix sale price in cart I need to lunch my app asap

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all require info to continue with the support  - http://private.inspireui.com/ 

We're closing this ticket as is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!
