### ISSUE TITLE
Fluxstore 1.7.1 ( Discounted products price error)

### ISSUE THREAD

**Issue by samik9** [inspireui/support#2991]
Hello, guys, i found an error that can confuse users, when a product have a discount and go to payment it shows the full price and not the discount, check this video.   https://gzodigital.d.pr/4KIWhB

![discount](https://user-images.githubusercontent.com/50071744/80892766-45a86880-8c92-11ea-9288-01c71929210f.jpg)

**Comment by minhcasi** [comment]
@samik9 - confirm this fix on the latest 1.7.2 - we will release this version shortly - thank you!

**Comment by minhcasi** [comment]
we have fixed this bug on the latest 1.7.2 - pls help to download the package - thank you!

**Comment by samik9** [comment]
Issue was fixed on 1.7.2 thanks!

I got another bug with fluxbuilder 
#3012
