### ISSUE TITLE
Opencart app: customer address is not retrieved and custom fields are not supported? 

### ISSUE THREAD

**Issue by touch2hussain** [inspireui/support#2992]
Hi,
I have purchased license yesterday and looking for integration with my existing opencart backend. I found that the app doesn't retrieve customers saved address. Also new address doesn't support custom fields which I have created in the backend. My whole delivery system works on this custom fields. And retrieving customers saved address is must feature I'm looking for.

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com - i will be sharing this.

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhcasi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Saving Address for Opencart](https://trello.com/c/gTJ84o26/33-saving-address-for-opencart)

**Comment by minhcasi** [comment]
moved to the backlog to investigate on later upgrading

**Comment by touch2hussain** [comment]
Hello, Please provide some information before closing the ticket. It will help us planning accordingly.  so is this feature not available? Customers Address is one Key functions should be working out of the box.

**Comment by touch2hussain** [comment]
And Now every time I place order 2 new address us being created in back-end :(, It doesn't use previously added address.  
<img width="619" alt="Screen Shot 2020-05-03 at 12 43 46 PM" src="https://user-images.githubusercontent.com/1061729/80909751-c7a09c00-8d3b-11ea-90d8-2ee46e94807e.png">

So the Overall issues
1. The app doesn't retrieve customers saved Address 
2. Instead, it creates new address every time for an order ( Actually it's adding 2 Address in backed - means if a customer makes 100 orders, there will be 200 Address saved in DB) 
3. Custom fields created in backend for Address have no value - SO its totally working out of sync with the backend 
4. Where to delete all the Countries from the address in APP? I don't require Country and State selector.
