### ISSUE TITLE
[Fluxstore pro - Woocomerce] - Unable to complete after at checkout page- Format Exception

### ISSUE THREAD

**Issue by tjain90** [inspireui/support#2993]
Step 1 (require): detail issues and screenshots
I am getting FormatException: Unexpected character(atcharacter1)<!-Doctype HTML PUBLIC "-//IEFTF//DTD HTML 2.0//EN">
![Screenshot_20200503-122621](https://user-images.githubusercontent.com/6376301/80908162-2c0f2b80-8d3b-11ea-9839-528d4de3a4bf.jpg)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhcasi** [comment]
@tjain90 - could you try to debug the return HTML from your service side when process the payment, it will be shown on Android Studio log

**Comment by tjain90** [comment]
I have updated my app to new version. Now order is getting placed at backend but on app screen it do not show any confirmation and throws below error ""FormatException: Unexpected character (at character1 <br/>"

Below is log:

I/flutter ( 5485): [2020-05-04 12:00:24.496820Z][Fluxstore][wocommerce_api][17:30:24.496736] getAsync END [endPoint:payment_gateways] url:payment_gateways
I/flutter ( 5485): getItemTotal 350.0
I/flutter ( 5485): [2020-05-04 12:00:34.241491Z][Fluxstore][wocommerce_api][17:30:34.241182] postAsync START [endPoint:orders] url:https://www.indidecor.com/wp-json/wc/v2/orders?consumer_key=XXXXXXa&consumer_secret=XXXXX
I/flutter ( 5485): [2020-05-04 12:00:38.023392Z][Fluxstore][wocommerce_api][17:30:38.023151] postAsync END [endPoint:orders]
I/flutter ( 5485): [2020-05-04 12:00:38.046421Z][Fluxstore][wocommerce_api][17:30:38.046170] postAsync START [endPoint:orders/7527] url:https://www.indidecor.com/wp-json/wc/v2/orders/7527?consumer_key=XXXXXX&consumer_secret=XXXXX
I/flutter ( 5485): #0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1394:5)
I/flutter ( 5485): #1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1261:9)
I/flutter ( 5485): #2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:926:22)
I/flutter ( 5485): #3      _parseJson (dart:convert-patch/convert_patch.dart:31:10)
I/flutter ( 5485): #4      JsonDecoder.convert (dart:convert/json.dart:495:36)
I/flutter ( 5485): #5      JsonCodec.decode (dart:convert/json.dart:153:41)
I/flutter ( 5485): #6      WooCommerceAPI.postAsync (package:fstore/services/helper/woocommerce_api.dart:191:35)
I/flutter ( 5485): <asynchronous suspension>
I/flutter ( 5485): #7      WooCommerce.updateOrder (package:fstore/services/woo_commerce.dart:618:12)
I/flutter ( 5485): #8      Services.updateOrder (package:fstore/services/index.dart:262:23)
I/flutter ( 5485): #9      WooWidget.createOrder (package:fstore/widgets/frameworks/woocommerce/index.dart:124:26)
I/flutter ( 5485): <asynchronous suspension>
I/flutter ( 5485): #10     WooWidget.placeOrder (package:fstore/widgets/frameworks/woocommerce/index.dart:151:7)
I/flutter ( 5485): #11     _PaymentMethodsState.placeOrder (package:fstore/screens/checkout/payment.dart:321:27)
I/flutter ( 5485): #12     _P

**Comment by minhcasi** [comment]
@minhtruong315 - pls help with checking, thank you!

**Comment by minhtruong315** [comment]
@tjain90 can u send me common folder via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/2993

**Comment by tjain90** [comment]
@minhtruong315 - Email sent. 
Really appreciate your quick help on same.

**Comment by minhtruong315** [comment]
@tjain90 check this solution https://github.com/inspireui/support/issues/2947#issuecomment-622820068

**Comment by tjain90** [comment]
Thanks @minhtruong315 . It solved my problem.

**Comment by tjain90** [comment]
Hi @minhtruong315 , @minhcasi  I am facing similar issue when trying to login via sms .

Below is the snapshot:

![Screenshot_20200507-081840](https://user-images.githubusercontent.com/6376301/81249266-db9a1580-903b-11ea-818d-3cfce5fdee28.jpg)
