### ISSUE TITLE
Product image not loading on homescreen and gmail login

### ISSUE THREAD

**Issue by mansoor88** [inspireui/support#2994]
Step 1 (require): detail issues and screenshots
I am facing the following issue in-app. My product images are not loading in home screen. They are showing in detail of product but not showing on the home screen. I need assistance in this matter.
![Screenshot_2020-05-02-22-16-49-492_com inspireui fluxstore](https://user-images.githubusercontent.com/7188395/80909053-81007100-8d3e-11ea-8b4a-d06499f12023.jpg)

I am unable to login with google from physical device. Meanwhile, it is working fine in the emulator.
![Screenshot_2020-05-02-22-17-18-748_com inspireui fluxstore](https://user-images.githubusercontent.com/7188395/80908925-5c57c980-8d3d-11ea-910e-8dfa6e644311.jpg)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhcasi** [comment]
@mansoor88 - could you help to check this guide - https://paper.dropbox.com/doc/Fix-Login-GoogleSMS--AzPzYneE9rU1jFeQiZUKCqCjAg-jy7aa8GBDhBliErF345M3

**Comment by mansoor88** [comment]
> @mansoor88 - could you help to check this guide - https://paper.dropbox.com/doc/Fix-Login-GoogleSMS--AzPzYneE9rU1jFeQiZUKCqCjAg-jy7aa8GBDhBliErF345M3
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/059c01fb07caa5a3e91bd76d0eef0524d82bffb1/68747470733a2f2f70617065722d6174746163686d656e74732e64726f70626f782e636f6d2f735f433839324139354636333541414335444539434333363235363143313143413633453044433237413539463346363530334139343045363545304232314432455f313538383431363034303632305f696d6167652e706e67"><img alt="" height="14" src="https://camo.githubusercontent.com/93a7cc8db3f275c35f0331e4b45850e7aab23eb2/68747470733a2f2f70617065722e64726f70626f787374617469632e636f6d2f7374617469632f696d672f66617669636f6e2f66617669636f6e2d31362e706e67"> Dropbox Paper**[Fix Login Google/SMS](https://paper.dropbox.com/doc/Fix-Login-GoogleSMS--AzPzYneE9rU1jFeQiZUKCqCjAg-jy7aa8GBDhBliErF345M3)**1. Missing config SHA certificate fingerprints   #Ticket https://github.com/[/issues/2895](https://github.com/inspireui/support/issues/2895) 1.

I go throught with mstore.keystore file command it is asking keystore password. Where to get that.

**Comment by tiagosoliver** [comment]
when I do this it generates the same SHA1 that you already use, a and firebase informs you that there is already a project with the same sha1.

**Comment by mansoor88** [comment]
Anyone here to help/support?

**Comment by mansoor88** [comment]
@trunghieuvn anyone?

**Comment by trunghieuvn** [comment]
> > @mansoor88 - could you help to check this guide - https://paper.dropbox.com/doc/Fix-Login-GoogleSMS--AzPzYneE9rU1jFeQiZUKCqCjAg-jy7aa8GBDhBliErF345M3
> > > <img alt="" width="48" src="https://camo.githubusercontent.com/059c01fb07caa5a3e91bd76d0eef0524d82bffb1/68747470733a2f2f70617065722d6174746163686d656e74732e64726f70626f782e636f6d2f735f433839324139354636333541414335444539434333363235363143313143413633453044433237413539463346363530334139343045363545304232314432455f313538383431363034303632305f696d6167652e706e67"><img alt="" height="14" src="https://camo.githubusercontent.com/93a7cc8db3f275c35f0331e4b45850e7aab23eb2/68747470733a2f2f70617065722e64726f70626f787374617469632e636f6d2f7374617469632f696d672f66617669636f6e2f66617669636f6e2d31362e706e67"> Dropbox Paper**[Fix Login Google/SMS](https://paper.dropbox.com/doc/Fix-Login-GoogleSMS--AzPzYneE9rU1jFeQiZUKCqCjAg-jy7aa8GBDhBliErF345M3)**1. Missing config SHA certificate fingerprints   #Ticket [https://github.com/[/issues/2895](https://github.com/inspireui/support/issues/2895)](https://github.com/%5B/issues/2895%5D(https://github.com/inspireui/support/issues/2895)) 1.
> 
> I go throught with mstore.keystore file command it is asking keystore password. Where to get that.
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/059c01fb07caa5a3e91bd76d0eef0524d82bffb1/68747470733a2f2f70617065722d6174746163686d656e74732e64726f70626f782e636f6d2f735f433839324139354636333541414335444539434333363235363143313143413633453044433237413539463346363530334139343045363545304232314432455f313538383431363034303632305f696d6167652e706e67"><img alt="" height="14" src="https://camo.githubusercontent.com/93a7cc8db3f275c35f0331e4b45850e7aab23eb2/68747470733a2f2f70617065722e64726f70626f787374617469632e636f6d2f7374617469632f696d672f66617669636f6e2f66617669636f6e2d31362e706e67"> Dropbox Paper**[Fix Login Google/SMS](https://paper.dropbox.com/doc/Fix-Login-GoogleSMS--AzPzYneE9rU1jFeQiZUKCqCjAg-jy7aa8GBDhBliErF345M3)**1. Missing config SHA certificate fingerprints   #Ticket https://github.com/[/issues/2895](https://github.com/inspireui/support/issues/2895) 1.

Hi @mansoor88 
Keystore info details are in this file "android / key-debug.properties"

**Comment by mansoor88** [comment]
I put the keystore password. But it said the password is tempered and it is not matching. The keystore file came with downloaded file. 

Also my products image load issue not supported.

**Comment by trunghieuvn** [comment]
> I put the keystore password. But it said the password is tempered and it is not matching. The keystore file came with downloaded file.
> 
> Also my products image load issue not supported.

hi @mansoor88 
You try to create a new key and test it.

Step 1: create the keystore according to the instructions here: https://flutter.dev/docs/deployment/android

Step 2: Enter the keystore file information into the xxx file

Step 3: Update SHA1 of your firebase android app

**Comment by mansoor88** [comment]
> > I put the keystore password. But it said the password is tempered and it is not matching. The keystore file came with downloaded file.
> > Also my products image load issue not supported.
> 
> hi @mansoor88
> You try to create a new key and test it.
> 
> Step 1: create the keystore according to the instructions here: https://flutter.dev/docs/deployment/android
> 
> Step 2: Enter the keystore file information into file `android/key-debug.properties`
> 
> Step 3: Update SHA1 of your firebase android app
> 
> _Note:_
> 
>     * The keystore file must be saved in the folder `android/app/`
> 
>     * The format of the `key-debug.properties` file will be:
> 
> 
> ```
> storePassword=<storePassword>
> keyPassword=<keyPassword>
> keyAlias=<keyAlias>
> storeFile=<storeFile>
> ```
> 
> If everything still does not work, please add me to your github / gitlab and firebase, I will find out the specific cause and guide you how to fix it.
> 
> Email/github/gitlab : [hieu.trantrung1204@gmail.com](mailto:hieu.trantrung1204@gmail.com)

I send invite to you of github. Please check. I create the file of keyNew.jks and it is created but further procedure is not going in.

**Comment by trunghieuvn** [comment]
> I send invite to you of github. Please check. I create the file of keyNew.jks and it is created but further procedure is not going in.

You accidentally deleted the setup key code for build debug mode, so logging doesn't work when you run the debug. Please correct the code as follows (in file `android/app/build.gradle`):

![image](https://user-images.githubusercontent.com/19247680/81216132-9d353400-9004-11ea-9632-5a2a01b7b67a.png)

**Comment by mansoor88** [comment]
I have developed and google login is working on the emulator. I copy the google-services.json file as well. Which i generete with my account. What next i need to do.

**Comment by mansoor88** [comment]
> > I send invite to you of github. Please check. I create the file of keyNew.jks and it is created but further procedure is not going in.
> 
> You accidentally deleted the setup key code for build debug mode, so logging doesn't work when you run the debug. Please correct the code as follows (in file `android/app/build.gradle`):
> 
> ![image](https://user-images.githubusercontent.com/19247680/81216132-9d353400-9004-11ea-9632-5a2a01b7b67a.png)

where to get that setup key code?
