### ISSUE TITLE
Product Filter Price Bar Issue 

### ISSUE THREAD

**Issue by chocotacos** [inspireui/support#2996]
Step 1 (require): detail issues and screenshots

![55](https://user-images.githubusercontent.com/55656013/80909516-a72a0f00-8d46-11ea-96c4-a82093bcaba1.PNG)

It start with ₹500 and goes maximum to ₹1000 i want it to go further as of my products maximum prices. My products prices are₹ 1500-₹2000+  and more but it goes till ₹1000 and it shows no products.

![56](https://user-images.githubusercontent.com/55656013/80909553-e0627f00-8d46-11ea-91f3-831623271930.PNG)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

I had already filed the google form.

![33](https://user-images.githubusercontent.com/55656013/80909603-20c1fd00-8d47-11ea-8402-7e5764f11fa2.PNG)

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by iamar1k92** [comment]
go to lib/commons/constants/slider.dart:
change const kMaxPriceFilter from ... to 2000 or any number which is amount to your highest price of the product. This will be the right extreme of filter.

**Comment by chocotacos** [comment]
Could you help me bro how to change the naviagation drawer icon and the layout of the drawer !

**Comment by iamar1k92** [comment]
When you click apply then it will show result.

**Comment by chocotacos** [comment]
They don't when i click on apply it shows no products.

**Comment by minhcasi** [comment]
@chocotacos 

Thank you for the feedback.

Please help us to submit this form and fill all require info to continue with the support  - http://private.inspireui.com/ 

We're closing this ticket as is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
@chocotacos - verify purchased 👍

We will check the issue and let you know - thanks

**Comment by chocotacos** [comment]
Ok so i have more issues as well can i post them here. Did you verified the purchase?

**Comment by minhcasi** [comment]
Yes - verified, please post it here :)

**Comment by chocotacos** [comment]
Ok so i am gonna wrap all my issues i am facing as i don't want to create lot's of tickets. cz i am having plenty of issues as well. 🤐 

Issue1- I want to change the change the navigation icon. and want to display cart icon at no-2
i am not able to understand the flutter inspector thing. Can i edit this with the code or something?

https://docs.inspireui.com/fluxstore/customization/#1-how-to-customize-any-ui-from-app

I have gone through this! but it shows the icon but how to change it still bounced off my head i am a budding developer and flutter is new for me like i am learning just for this app so please @minhcasi describe it bit briefly.😕

![11](https://user-images.githubusercontent.com/55656013/80961880-838bc500-8e29-11ea-8f55-3e6826a03fe6.PNG)

Issue2- Can i modify the setting area i want to add/remove few things from this layout.

![12](https://user-images.githubusercontent.com/55656013/80962163-22182600-8e2a-11ea-8f78-0dd62cb37812.PNG)

Issue3- https://github.com/inspireui/support/issues/3007#issue-611481196
 From that ticket it isn't resolved so i need help in that.

Issue4- FluxBuilder lacks with some feature i want to add in my app UI and have some bugs as well can i code and then change the layout. or any other way.
I have some design i want my design to look like but that functions aren't available at FluxBuilder.

That's all i need help with. Maybe more rightnow i am dealing with them only.🤐 & am sad of not getting ahead stuck at a place from 2 days.
SO help me sir @minhcasi.

**Comment by chocotacos** [comment]
@minhcasi no reply yet....!

**Comment by minhcasi** [comment]
@chocotacos 

1+2- pls try to see this video to now how to use Inspector Tool - just touch the button on Android Studio, and Tap the icon UI, it will jump to the source so that you could change it quickly - https://www.youtube.com/watch?v=X-JldsKdNKk&t=191s
I will update new video for some basic Technique as well - pls subscribe to http://youtube.com/inspireui

3. Try to edit this file - https://tppr.me/j5lcw 

4. The fluxbuilder could not meet your all requirement, you could use Android Studio to update as more advance customization, you have all the source code btw
