### ISSUE TITLE
Opencart App: Unable to run the web app in chrome - Failed to compile application.

### ISSUE THREAD

**Issue by touch2hussain** [inspireui/support#2997]
I want to run the app for web, I have switched to flutter beta

 flutter channel beta
 flutter upgrade
 flutter config --enable-web

then running the app. I got following error

<img width="1231" alt="Screen Shot 2020-05-03 at 1 13 03 PM" src="https://user-images.githubusercontent.com/1061729/80910374-15b79e80-8d40-11ea-9565-050c54dd31e0.png">

Step 2 (require):  Already verified with the previous ticket

http://private.inspireui.com

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all require info to continue with the support  - http://private.inspireui.com/ 

We're closing this ticket as is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!
