### ISSUE TITLE
App performance: Caching not working

### ISSUE THREAD

**Issue by aishema2000** [inspireui/support#2998]
Step 1 (require): detail issues and screenshots

My MStore API is update, I uploaded the config_en.json file, i cleared the cache, I enable caching to true in the general.dart file but when I launch my App it fails to build. Below is what i see in the debug console...
![image](https://user-images.githubusercontent.com/15066381/80910906-07af5100-8d33-11ea-95f5-be72956faf60.png)

What can I do?

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhcasi** [comment]
@aishema2000 - we have fixed this bug on latest 1.7.2 - pls help to download the package - thank you!

**Comment by aishema2000** [comment]
Dear support, you said this issue is resolved with version 1.7.2 but i tested with the codes downloaded from private gitlab, the issue is still there, the app does not work when caching is enabled, Please help me, I have been waiting for so long to publish my app.

**Comment by aishema2000** [comment]
Where do I download this 1.7.2 version?

**Comment by minhcasi** [comment]
please download it from http://codecayon.net/downloads or you could get it from the Gitlab - if you don't have an account, pls submit it here https://docs.google.com/forms/d/e/1FAIpQLSeuBqUkScy42V7KKhfNPj0fl581anrB1mWkbMa3p2WQt7fhfw/viewform - thank you!
