### ISSUE TITLE
FluxStore listing showing white sreen when testing on device

### ISSUE THREAD

**Issue by LiamBayford123** [inspireui/support#2999]
Hi, I'm new to this so apologies in advance. I'm trying to test my app on my iPhone and it only shows a white screen. I have no idea where to start to fix this. I need to submit to the app store asap so any help would be appreciated. Thanks!
![Image 03-05-2020 at 11 28](https://user-images.githubusercontent.com/64730410/80911915-4a702980-8d31-11ea-921f-cfaaac531142.jpg)

**Comment by iamar1k92** [comment]
do you have install cocoapods?

**Comment by iamar1k92** [comment]
run: flutter doctor command in the terminal and share the result.

**Comment by LiamBayford123** [comment]
> run: flutter doctor command in the terminal and share the result.

![Image 03-05-2020 at 12 40](https://user-images.githubusercontent.com/64730410/80913274-5f51ba80-8d3b-11ea-9331-0a7d320ba405.jpg)

**Comment by iamar1k92** [comment]
have you installed cocoapods before?

**Comment by LiamBayford123** [comment]
> have you installed cocoapods before?

Yes that's installed

**Comment by minhcasi** [comment]
@LiamBayford123 

Thank you for the feedback.

Please help us to submit this form and fill all require info to continue with the support  - http://private.inspireui.com/ 

We're closing this ticket as is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!
