### ISSUE TITLE
[MSTORE-MV] Shipping Address not Auto Populated from WP

### ISSUE THREAD

**Issue by nghonyuen** [inspireui/support#300]
**Required Info (please complete the following information):**
* Product: MSTORE-MV
* Your Purchased Code: 34a1d23d-c198-4cd8-beec-b4d0881c6437
  (we may not reply if you are not our customer)

**Describe the bug**
When checkout, the address was not auto populated from the user profile. 

**Screenshots**

**Additional context**
Add any other detail logs about the problem here.
If possible please share your config.js that use for the app setting

**Comment by thangvo9x** [comment]
Hi. Please update your address on your site. The app has only get data from your app.

**Comment by nghonyuen** [comment]
Noted. I tested, but it still doesn't pull from the WP. 
<img width="363" alt="screenshot 2019-02-18 at 12 41 11 pm" src="https://user-images.githubusercontent.com/47480781/52928439-9e842d80-337a-11e9-8d98-9e47b79ab88a.png">
<img width="654" alt="screenshot 2019-02-18 at 12 37 55 pm" src="https://user-images.githubusercontent.com/47480781/52928446-a6dc6880-337a-11e9-838b-d48d6df62d7f.png">

**Comment by thangvo9x** [comment]
Hi.  Try to update your billing address. and remove the expo app and re-install. Thanks

**Comment by nghonyuen** [comment]
HiDoes that means the sync only one time during initial install? ThanksOn Mon, 18 Feb 2019 at 2:22 PM, thangvo9x <notifications@github.com> wrote:Hi.  Try to update your billing address. and remove the expo app and re-install. Thanks

?You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by thangvo9x** [comment]
Yes. That's right

**Comment by nghonyuen** [comment]
Ok noted. It may makes sense to synchronise 2 ways & also more frequently because I may purchase good and send to different locations. In additional it also ease testing (can be quite frustrating to keep entering address since it never sync after installation). 

Hopefully this feature can be added to next release. You may close this issue. Thanks a bunch!
