### ISSUE TITLE
[MStore] Currency change not Working

### ISSUE THREAD

**Issue by yuwono2694** [inspireui/support#3000]
I already made changes in the src/common/config.js but nothing changed in the product list

please help

Screenshoot : 
![image](https://user-images.githubusercontent.com/12391894/80913442-d9e7fd80-8d6e-11ea-86bc-2d41b1ca11b4.png)

The source code of the library files : 
Expo : 
[common.zip](https://github.com/inspireui/support/files/4570205/common.zip)

Pro : 
[common.zip](https://github.com/inspireui/support/files/4570204/common.zip)

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all require info to continue with the support  - http://private.inspireui.com/ 

We're closing this ticket as is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by yuwono2694** [comment]
done submitted !! thanks @minhcasi

**Comment by minhcasi** [comment]
@yuwono2694 - the current switcher is not ready to support from MstorePro - we will check the solution to upgrade it soon -thank you!

**Comment by minhcasi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Currency Switcher](https://trello.com/c/t8bIqv9G/34-currency-switcher)

**Comment by minhcasi** [comment]
moved to the backlog for investigating
