### ISSUE TITLE
FluxStore listing showing white screen when testing on device

### ISSUE THREAD

**Issue by LiamBayford123** [inspireui/support#3001]
Hi, I'm new to this so apologies in advance. I'm trying to test my app on my iPhone and it only shows a white screen. I have no idea where to start to fix this. I need to submit to the app store asap so any help would be appreciated. Thanks!

![Image 03-05-2020 at 11 28](https://user-images.githubusercontent.com/64730410/80914060-113fb580-8d41-11ea-82cf-d62a20d2bb81.jpg)
![Image 03-05-2020 at 12 40](https://user-images.githubusercontent.com/64730410/80914061-1270e280-8d41-11ea-94a9-34cd0cc3f07e.jpg)

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all require info to continue with the support  - http://private.inspireui.com/ 

We're closing this ticket as is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by LiamBayford123** [comment]
> Thank you for the feedback.
> 
> Please help us to submit this form and fill all require info to continue with the support - [http://private.inspireui.com/ ](http://private.inspireui.com/%C2%A0)
> 
> We're closing this ticket as is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

I've submitted the form..

**Comment by minhcasi** [comment]
@LiamBayford123 - could I know if you could able to run the app on the simulator? 

Please help us to check this guide to see if you have any missing steps during the installing - https://www.youtube.com/watch?v=ReAUZDIgh2I

**Comment by philipvu30** [comment]
Closed as no response
