### ISSUE TITLE
Language & customization

### ISSUE THREAD

**Issue by mryous** [inspireui/support#3002]
Step 1 (require): detail issues and screenshots

![image](https://user-images.githubusercontent.com/28628432/80913824-24bb4280-8d7a-11ea-99b7-47f86f39b2ea.png)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

1. How to Properly change main Language, I want to switch to Indonesian, as well as the Currency n etc
2. How to change intro Screen with image
3. How to change circle category image
could you make the details step plz?

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all require info to continue with the support  - http://private.inspireui.com/ 

We're closing this ticket as is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by mryous** [comment]
done the step soe days a go, should I repeat it sir?

**Comment by mryous** [comment]
done sir

**Comment by mryous** [comment]
![image](https://user-images.githubusercontent.com/28628432/80914686-bc6f5f80-8d7f-11ea-8286-5b277cb33dd5.png)

I try it, got this and revert it back

**Comment by mryous** [comment]
or.. how can I reset All the settings?

**Comment by mryous** [comment]
plz sir @minhcasi 😔😔

**Comment by minhcasi** [comment]
@luyx2412 - pls help with the suggestion - thank you!

**Comment by luyx2412** [comment]
Hi @mryous Currently you should be add Indonesian language in `src/common/Languages.js` 
![image](https://user-images.githubusercontent.com/8909619/80975803-c4490580-8e4c-11ea-998d-87129a8d7f17.png)

After that in `src/common/Constants.js` line 19 please add your language in there.
![image](https://user-images.githubusercontent.com/8909619/80975850-d75bd580-8e4c-11ea-9ecf-7eb2d4130e01.png)

The issue related can not find the localization.

Thanks

**Comment by mryous** [comment]
Plz move here sir ... I hope this is the last question I have... pleasee
[https://github.com/inspireui/support/issues/3073](url)
