### ISSUE TITLE
Phone Number is not enough character

### ISSUE THREAD

**Issue by yuwono2694** [inspireui/support#3003]
![image](https://user-images.githubusercontent.com/12391894/80916780-1aeb0c80-8d85-11ea-9cdc-84c1d5eb86f5.png)
As you can see above is the delivery info detail, but the fact in Indonesia, our phone number is 13-14 digits, but your app only limited up to 11 digits

Is there anything you can do or I can do with the code?
Thanks in advance

**Comment by minhcasi** [comment]
@yuwono2694 

Thank you for the feedback.

Please help us to submit this form and fill all require info to continue with the support  - http://private.inspireui.com/ 

We will close this ticket as is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by yuwono2694** [comment]
done submitted @minhcasi

**Comment by luyx2412** [comment]
Hi @yuwono2694 In `src/common/Validator.js` line 33 you can change validate phone number in this line same the screenshot
![image](https://user-images.githubusercontent.com/8909619/80974767-5e0fb300-8e4b-11ea-976c-d97ff6c9e065.png)

Thanks

**Comment by yuwono2694** [comment]
hi @luyx2412 my app still cannot write the phone number even i changed the code. any other things i need to do? thanks..

**Comment by yuwono2694** [comment]
is there any update for this? 
Still cant write the phone number.. :( @luyx2412 @minhcasi

**Comment by luyx2412** [comment]
HI @yuwono2694 Sorry about reply you late. The issue related https://github.com/benhurott/react-native-masked-text#cel-phone . You can change `TextInputMask` with `TextInput ` default React native https://reactnative.dev/docs/textinput#__docusaurus or using another 
![image](https://user-images.githubusercontent.com/8909619/81187545-65b39100-8fde-11ea-9985-d0080d9a431b.png)
![image](https://user-images.githubusercontent.com/8909619/81187540-64826400-8fde-11ea-8dd2-600e1aae7657.png)

Thanks

**Comment by yuwono2694** [comment]
hi @luyx2412 thanks for your explanation but, i think you're missing to tell me where the code is located since you got a lott of js file inside this mstore pro and im not an engineer here. May you please help me like the first one?
Because i tried to search for the code piece that you gave from that screetshoot, but i just didnt found it.
so, maybe you can tell me which file is it, which line and what i need to write there?
Your help would be really appreciate.

**Comment by luyx2412** [comment]
Hi @yuwono2694 Sorry about my missing.
The code inside `src/containers/Cart/Delivery/index.js` line 305.

Thanks

**Comment by yuwono2694** [comment]
also change the line 9 become : 
import { TextInput } from "react-native";

Solved and case close

Thanks @luyx2412

**Comment by yuwono2694** [comment]
Closed
