### ISSUE TITLE
fluxstore woocommerce exited 1

### ISSUE THREAD

**Issue by Saneleros** [inspireui/support#3004]
Couldn't read file LocalFile: 'C:\Users\Book a book\Desktop\flutter_windows_v1.12.13+hotfix.9-stable\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.7\android\src\main\kotlin\io\flutter\plugins\flutter_plugin_android_lifecycle\FlutterAndroidLifecyclePlugin.kt' even though it exists. Please verify that this file has read permission and try again.
Exited (1)
![main dart](https://user-images.githubusercontent.com/21216812/80917537-e749bb80-8d5f-11ea-9a7d-8415268b32a5.PNG)

**Comment by minhcasi** [comment]
@Saneleros - this could cause by the permission issue on your Flutter pls try to run this script
```
flutter channel stable
flutter upgrade --force
flutter pub cache repair
cd <YOUR APP FOLDER>
flutter clean
```
