### ISSUE TITLE
Error Portuguese Brazil

### ISSUE THREAD

**Issue by tiagosoliver** [inspireui/support#3005]
Language brazil presents error

**Comment by tiagosoliver** [comment]
adjusted. It is necessary to change from 'br' to 'pt', and change in I110n.dart to
Locale.fromSubtags (languageCode: 'pt', countryCode: 'BR')

this is because br is not a language, the language is portuguese, which has Portugal (pt_pt) and Brazilian (pt_br)

**Comment by minhcasi** [comment]
@tiagosoliver - thank you so much for your solution - we have updated on latest code - very best!
