### ISSUE TITLE
Fluxstore Pro - 1.7.2 Variations issues

### ISSUE THREAD

**Issue by huntelar10** [inspireui/support#3006]
Step 1 (require): detail issues and screenshots
Hello Dear
version 1.5 was working ok since any new update was include this issues
if you can fix it will be good for us to update our app

https://drive.google.com/file/d/1fyH3A0_RTkOh8KIf5NDUACxAby6z9Jhe/view?usp=sharing
as you can see in cart all is fine price 

https://drive.google.com/file/d/1buXETIL4oLw15qLa1LRzbjg8N7zeuDEt/view?usp=sharing

when send to server will be all same price and will choose the lowest price.and this is cause issue with our customer cause that we back to version 1.5

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhtruong315** [comment]
@huntelar10 can u send me admin account via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/3006

**Comment by huntelar10** [comment]
i email you , you check please

**Comment by minhtruong315** [comment]
You dont answer the email. Please check. Thanks

**Comment by huntelar10** [comment]
Dear @minhtruong315 i send login info to your email
thank you

**Comment by minhtruong315** [comment]
<img width="1175" alt="Screen Shot 2020-05-11 at 9 40 38 AM" src="https://user-images.githubusercontent.com/10402500/81519449-80359380-936b-11ea-8c9c-a6b4b538b9e9.png">
I checked your website on the latest version Fluxstore. it's working well. what is your Fluxstore version?

**Comment by huntelar10** [comment]
Dear @minhtruong315 ,
i was use version 1.7.2 and i was still face same issues.
but version 1.7.3 i confirm no more this issues.

 good job guys

thank you @minhtruong315 @minhcasi for the support .
 wish all the best for you guys .
