### ISSUE TITLE
{FLUXSTORE}--The Product Filter Slide Bar & Taxes issues.

### ISSUE THREAD

**Issue by chocotacos** [inspireui/support#3007]
Issue-1 (require): detail issues and screenshots

When the slider is pulled any where from ₹500 right or left then pressing apply button it shows no products.

![55](https://user-images.githubusercontent.com/55656013/80922659-37df0a00-8d9c-11ea-9de6-2cf35c9ed406.PNG)

Issue 2- Could someone help me how to change the layout (home screen of the app with coding) which file to open. config_an.json,config_en.json and there are much more.

![76](https://user-images.githubusercontent.com/55656013/80923019-8a212a80-8d9e-11ea-956e-da865e0a15cf.PNG)

Issue-3 There is an Tax system in my website but it isn't displaying in the app during checkout but it is showing after the order is completed in order details section.

1- Not showing here !

![77](https://user-images.githubusercontent.com/55656013/80923027-960cec80-8d9e-11ea-9d34-f33c197ed8dd.PNG)

2- Not in Preview as well!

![78](https://user-images.githubusercontent.com/55656013/80923040-a4f39f00-8d9e-11ea-8266-7075ffa41bf5.PNG)

3- But showing over here! its annoying !

![79](https://user-images.githubusercontent.com/55656013/80923054-bb015f80-8d9e-11ea-9e06-0b893e26e8d8.PNG)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

Did already...!

**Comment by minhcasi** [comment]
@chocotacos - we could not verify your previous purchase email - eshindwivedi@gmail.com, please help submit again http://private.inspireui.com/ - thank you for your time

**Comment by minhcasi** [comment]
@chocotacos - pls help us to move your all issues to the same ticket - #3007 - thank you!
