### ISSUE TITLE
new update 1.7.2 some errors

### ISSUE THREAD

**Issue by mohamedibrahim89** [inspireui/support#3008]
first issue I upgrade splash screen to gif file as u told u support gif but not reflect in app and app show logo as a splash screen u told this fix in this update but nothing solve
<img width="1440" alt="Screen Shot 2020-05-03 at 9 04 10 PM" src="https://user-images.githubusercontent.com/35544603/80923098-a793cb80-8d81-11ea-8f12-950a1d30284d.png">
2) onboarding not start in app from where can I solve this issue 
3) until product load in shop page it show (no product ) before it load product I need to make this like as before
![WhatsApp Image 2020-05-03 at 9 01 36 PM](https://user-images.githubusercontent.com/35544603/80923125-d611a680-8d81-11ea-8c71-a1e7054c1d3b.jpeg)
![WhatsApp Image 2020-05-03 at 9 02 37 PM](https://user-images.githubusercontent.com/35544603/80923128-ddd14b00-8d81-11ea-9756-1e94a777b839.jpeg)

4) google login give me this error

![WhatsApp Image 2020-05-03 at 9 01 38 PM](https://user-images.githubusercontent.com/35544603/80923139-e9bd0d00-8d81-11ea-9230-e5ca1f9f0fb2.jpeg)

hello
this is the file 
[app_init.dart.zip](https://github.com/inspireui/support/files/4579594/app_init.dart.zip)

 I have also error when I add new order I found this error in app

![WhatsApp Image 2020-05-04 at 6 28 39 PM](https://user-images.githubusercontent.com/35544603/81046724-496a0400-8eb9-11ea-9dab-cfc753677d81.jpeg)
Thxxx for ur support

**Comment by trunghieuvn** [comment]
> 2) onboarding not start in app from where can I solve this issue

To fix this error, follow these steps:

**In file `lib/app_init.dart`**

- change function `checkFirstSeen`

```
Future checkFirstSeen() async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    bool _seen = prefs.getBool('seen') ?? false;
    return !_seen;
  }
```
- in function `loadInitData`, move code

```
isFirstSeen = await checkFirstSeen();
isLoggedIn = await checkLogin();
```
up on the following code

```
Services().setAppConfig(serverConfig);
      appConfig =
          await Provider.of<AppModel>(context, listen: false).loadAppConfig();

```

- Move the code in function `build` to function`onNextScreen`

![image](https://user-images.githubusercontent.com/19247680/80951072-54715580-8e21-11ea-9f5e-6ae65401cb57.png)


![image](https://user-images.githubusercontent.com/19247680/80950634-6e5e6880-8e20-11ea-9c08-1c21b783354b.png)

![image](https://user-images.githubusercontent.com/19247680/80950650-74544980-8e20-11ea-835b-85be2950ff18.png)

----

In file `lib/screens/home/onboard_screen.dart` add code :

![image](https://user-images.githubusercontent.com/19247680/80950670-7cac8480-8e20-11ea-8b48-bc3809201d7e.png)

**Comment by mohamedibrahim89** [comment]
I will check now about the other problem can u help me to finish them

**Comment by mohamedibrahim89** [comment]
I do everything still onboarding not show
and u don't tell me how to fix other issues

**Comment by angelohu** [comment]
@trunghieuvn @minhcasi  
for onboarding not show  i tried
![WeChatc62b0b36dc669fc16a4de725f9c58dc2](https://user-images.githubusercontent.com/64202693/81021510-9cb56580-8e6b-11ea-8a49-b51afc15e967.png)

**Comment by trunghieuvn** [comment]
Hi @mohamedibrahim89 @angelohu ,
Please send me your file `lib/app_init.dart`. 
Thanks

**Comment by angelohu** [comment]
Il giorno mar 5 mag 2020 alle ore 08:44 Hiếu <notifications@github.com> ha
scritto:

**Comment by mohamedibrahim89** [comment]
hello
this is the file 
[app_init.dart.zip](https://github.com/inspireui/support/files/4579594/app_init.dart.zip)

u don't answer the other questions
and I have also error when I add new order I found this error in app

![WhatsApp Image 2020-05-04 at 6 28 39 PM](https://user-images.githubusercontent.com/35544603/81046724-496a0400-8eb9-11ea-9dab-cfc753677d81.jpeg)

**Comment by mohamedibrahim89** [comment]
@minhcasi no answer

**Comment by minhcasi** [comment]
@mohamedibrahim89 - line_items empty was caused the issue, did you customize any UI from the Checkout that breaks the chain - pls try to double-check the original source

**Comment by mohamedibrahim89** [comment]
@minhcasi I dont change anything could u tell me which file to replace it with original again
and what about other issue .

**Comment by mohamedibrahim89** [comment]
I'm sure not change anything in ui in checkout and plz hep me also in other issues

**Comment by minhcasi** [comment]
@mohamedibrahim89 - you could send us the source to support@inspireui.com - we will help to check the issue - thank you!

**Comment by minhcasi** [comment]
Btw, we also update latest Fluxstore 1.7.3 to compatible with Flutter 1.17, please keep the update - thank you!
