### ISSUE TITLE
Change catagories id

### ISSUE THREAD

**Issue by ANaSHaker** [inspireui/support#3009]
In my code 
I follow the instruction and change the const server config 
But i don't know where i put my  id catagories
Which file should i put them in it

**Comment by ANaSHaker** [comment]
I hope any one can help me in it

**Comment by JohanSmith20** [comment]
config_en.json

**Comment by minhcasi** [comment]
@ANaSHaker 
Thank you for the feedback.

Please help us to submit this form and fill all require info to continue with the support  - http://private.inspireui.com/ 

We will close this ticket as is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!
