### ISSUE TITLE
[FluxStore Pro] The app worked well and now it doesn't show me any products.

### ISSUE THREAD

**Issue by Jegufull** [inspireui/support#3010]
Step 1 (require): detail issues and screenshots
Hello,

I need urgent help, I have my app published in the App Store and Play Store, it was working well, but as of today it does not show products or load the images from the home page. I have not made any update on the page, I reinstalled a backup from Friday that the app worked well, and it did not work.

I do not know why I did not upload products or images from my website.

Version 1.6.6b is the one that is published.

I tried with the new versions 1.7.0, 1.7.1 and 1.7.2, and it doesn't recognize the products either and it doesn't load the images either.

Could you help me with this?
My store is in Woocommerce

![IMG_9678](https://user-images.githubusercontent.com/47310507/80929542-6d6efd80-8d72-11ea-8503-bc839e7b1ac0.PNG)

![IMG_9679](https://user-images.githubusercontent.com/47310507/80929546-71028480-8d72-11ea-9eeb-4befda8d60c9.PNG)

![IMG_9680](https://user-images.githubusercontent.com/47310507/80929547-719b1b00-8d72-11ea-9fd7-cdd444c9632a.PNG)

https://apps.apple.com/co/app/wuauh/id1441668099

https://play.google.com/store/apps/details?id=com.wuauh.app

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhcasi** [comment]
@Jegufull - could you help to quick check the mstore-api and active the License from the plugin, it could be the reason

**Comment by Jegufull** [comment]
@minhcasi mstore-api is active 

<img width="1440" alt="Captura de Pantalla 2020-05-03 a la(s) 9 32 10 p  m" src="https://user-images.githubusercontent.com/47310507/80932570-ac5a7e80-8d85-11ea-9879-2f6629b6403b.png">

**Comment by kvt0012** [comment]
Dear sir, can you share me your config file, if you change too much please send your whole project to my email, I will help you investigate it, thank you

**Comment by Jegufull** [comment]
@kvt0012 pelea send my your email.

**Comment by kvt0012** [comment]
you can send to me throug vinhkhiemt135@gmail,com for priority 
or khiem@inspireui.com, after sending it to me, please comment your email here, I will checkj it, thank you

**Comment by Jegufull** [comment]
@kvt0012 

Hello, I already sent the files to your email from jegufull@hotmail.com

Any concerns remain pending

**Comment by kvt0012** [comment]
I'll check and problem on the api, please downgrade your mstrore api and check it again, thank you 
Or check again and make sure your api work well

**Comment by yasernet1989** [comment]
i have the same issue too. Im using latest version 1.7.2
please help

**Comment by kvt0012** [comment]
> i have the same issue too. Im using latest version 1.7.2
> please help

please check your rest api, sir

**Comment by kvt0012** [comment]
https://github.com/woocommerce/woocommerce/wiki/Getting-started-with-the-REST-API Follow the guide on this link, I think that will help you

**Comment by Jegufull** [comment]
@kvt0012 Hello,
I tried downgrading from the Mstore Api and it did not work, I created an administrator account on my site with your gmail, if you want to check how everything is on my site.
Any concerns remain pending.

Thank you

**Comment by kvt0012** [comment]
Dear sir, because supporting of api is out of our support scope. By the way, I will help you on my ability, thank you
