### ISSUE TITLE
ISSUE in FluxStore Pro Magento APP v1.7.2

### ISSUE THREAD

**Issue by JohanSmith20** [inspireui/support#3011]
Step 1 (require): detail issues and screenshots: Now the FluxStore Magento app v1.7.1 was running successfully but after i updated to the app v1.7.2 this issue appears when i enter to any product. Also i tried many times to start configuring the code as usual but still i end by the same issue everytime.
I sent to you through (**http://private.inspireui.com**) all the files you will need:
1- config.dart
2- config_es.json
3- common folder with all the files in it

![Error](https://user-images.githubusercontent.com/64312037/80932143-6d94ea80-8dbe-11ea-9008-c432edbf70df.jpg)

****Note: When i return to v1.7.1 with the same setting and configuration the app runs without any issue like this.**

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here): **DONE**

**Comment by JohanSmith20** [comment]
@minhcasi @trunghieuvn Help here please!!

**Comment by JohanSmith20** [comment]
2. **ANOTHER ISSUE** when i buy a product in my app and after the purchase is completed i cannot find my order in the order history , i always find it empty without any details about the order or any thing..

**Comment by JohanSmith20** [comment]
@minhtruong315

**Comment by JohanSmith20** [comment]
@minhcasi  @minhtruong315  Why no one is answering ?!!

**Comment by minhtruong315** [comment]
@JohanSmith20 can u upload your project to git repo then add my email: minhtruong315@gmail.com
I will pull your source code and check

**Comment by JohanSmith20** [comment]
@minhtruong315 Done i uploaded my project and i added you by invitation
Thank you.

**Comment by JohanSmith20** [comment]
@minhtruong315 @minhcasi Please give me a solution!!!

**Comment by mugua** [comment]
@JohanSmith20  I have the same issue with you, Could you add my Skype to talk ?
Skype: john.lou@msn.com
Thanks a lot.

**Comment by minhtruong315** [comment]
@JohanSmith20 I fixed on your source code. please check again
