### ISSUE TITLE
Category loader

### ISSUE THREAD

**Issue by samik9** [inspireui/support#3013]
**Issue 1**
Hello team, this is an really important improvement, when the category is loading it should show a loading animation, or a loader instead of show (no products)  Check this video https://gzodigital.d.pr/e3Czpm

**Comment by kvt0012** [comment]
Dear sir, 
Can you share me your config file and your api, I will help you investigate it, thank you

**Comment by mohamedibrahim89** [comment]
same issue

**Comment by minhcasi** [comment]
@samik9 

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ 

We will close this ticket as is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by samik9** [comment]
@minhcasi I already filled that form for a previous ticket, there is no point to fill that form every time that i find new bugs, by the way that link does not work http://private.inspireui.com/ .

**Issue 2:** #3055

**Spanish special characters**
my app is in Spanish I am using external .json config file, and I got this weird result.
![81234986-891b1380-8fbf-11ea-9e16-42ada381fbd1](https://user-images.githubusercontent.com/50071744/81326846-0a29e780-9060-11ea-8ae9-2c0a657a3688.png)

**Issue 3:** #3056

**Home banners does not show content** 

I noticed that home sliders doesn´t load any category , I verified that the category exist and have content.
Video: https://gzodigital.d.pr/qPMc6P



**Issue 3  #3058
ZIP CODE TO BE OPTIONAL (REQUEST)** 

![81238680-46116e00-8fc8-11ea-9e88-6c232c33ac6c](https://user-images.githubusercontent.com/50071744/81327104-655bda00-9060-11ea-8359-2387b6078697.png)

**Comment by kvt0012** [comment]
Dear sir, about issue 2, we use google translate to generate this file, so it will be weird sometimes.   
If you want to improve it, you can follow this guide : https://docs.inspireui.com/fluxstore/multi-language/   
Issue 3 we will help you after verified.

**Comment by samik9** [comment]
> @samik9
> 
> Please help us to submit this form and fill all required info to continue with the support - [http://private.inspireui.com/ ](http://private.inspireui.com/%C2%A0)
> 
> We will close this ticket as is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

I already sent the verification form

**Comment by samik9** [comment]
**About Issue 2:**

When I load the config.json file in Spanish in local, the special characters load very good, but when I put the same file on external location http://mysite.com/config.json  loads terrible. please note that only happens when I use external json

**Comment by kvt0012** [comment]
I'm sorry but you config wrong file, sir. config.json is the file is generated from itln10, And the main file of language is lib/l10n/

**Comment by kvt0012** [comment]
Verified.   
About issue 3, please check your video again because I can't see it.   
And make sure that your api is working well, thank you

**Comment by samik9** [comment]
**Issue 4** 
V. **1.7.3**

There is a bug when changing to any other language, i just downloaded the latest FluxStore , check this video https://gzodigital.d.pr/HK2HAI

**Comment by samik9** [comment]
**Issue 6 (LOGIN SCREEN)
1.7.3**

After adding a product to cart, the login screen keeps showing up when I successfully logged in. I am using the **default api credentials of your store**. Check this video

[https://gzodigital.d.pr/Wfcmng](url)

**Comment by danielito-1** [comment]
amigo, hablas español?

**Comment by samik9** [comment]
> amigo, hablas español?

Claro 😉

**Comment by kvt0012** [comment]
About login problem, we record and it will be uploaded soon, sir.   
About Changing Language, we can't detect this error now sir, I think it happens because of your configuration, thank you

**Comment by samik9** [comment]
Hello , i can not find the  upgrader version of app on 1.7.4 
<img width="859" alt="d8dde3a6ecec42aff3136af04b2b97b1" src="https://user-images.githubusercontent.com/50071744/82613896-1ea3cf00-9b8c-11ea-8338-fec6e0d13644.png">

@minhcasi @mohamedibrahim89 @kvt0012
