### ISSUE TITLE
search address on  google maps , Error

### ISSUE THREAD

**Issue by angelohu** [inspireui/support#3014]
WARNING: Unable to find and load 'GoogleMaps.bundle' for Google Maps SDK for iOS. This may be a sign that you've forgotten to include a resources bundle in your 'Copy Bundle Resources' build phase. As this bundle contains important resources, you may encounter missing images, translations and other incorrect behavior.
*** First throw call stack:
(
        0   CoreFoundation                      0x00007fff23e39f0e __exceptionPreprocess + 350
        1   libobjc.A.dylib                     0x00007fff50ad79b2 objc_exception_throw + 48
        2   CoreFoundation                      0x00007fff23e39d4c +[NSException raise:format:] + 188
        3   Runner                              0x00000001051b0a99 +[GMSMapsResources sharedResources] + 376
        4   Runner                              0x00000001051baa35 +[GMSServices mapsBundle] + 31
        5   Runner                              0x00000001051b771e -[GMSAsyncInitServices sharedInitWithSync:] + 103
        6   Runner                              0x00000001051b7642 -[GMSAsyncInitServices initSync] + 71
        7   Runner                              0x00000001051b8963 +[GMSServices sharedServicesSync] + 176
        8   Runner                 <…>

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all require info to continue with the support  - http://private.inspireui.com/ 

We will close this ticket as is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
#3014
