### ISSUE TITLE
Flux-MultiStore

### ISSUE THREAD

**Issue by jeanelvis** [inspireui/support#3015]
I have inspect the REST API for products endpoint it said ”rest_forbidden”, “Sorry, you are not allowed to do that.” 401. Can you help me fix this issues?

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all require info to continue with the support  - http://private.inspireui.com/ 

We will close this ticket as is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by jeanelvis** [comment]
[http://radiosantana.fm.br/img/001.JPG](url)
[http://radiosantana.fm.br/img/002.JPG](url)

I have already redone all the steps, but the products do not appear, only the shopkeepers appear, and the following error always returns:

[https://shoppingibiapaba.com.br/store/wp-json/wc/v2/products?lang=en&status=publish&category=473&per_page=20&consumer_key=ck_599a6710ac7c4c1606b9023d01f78fde9a2d10fc&consumer_secret=cs_4a7706afbaf84e73915f052da10153bcb9c3c3c3](url)

**Comment by minhcasi** [comment]
sorry, we should close the ticket as you could not provide the proof of purchase

**Comment by minhtruong315** [comment]
@jeanelvis You should change to use subdomain instead of folder
https://shoppingibiapaba.com.br/store
Rest  Api doesn't work well on folder.
Please update Fluxstore 1.7.3 on codecanyon.

**Comment by lpzczar** [comment]
> rest_forbidden”, “Sorry, you are not allowed to do that.” 401.

Please add the following code on your htaccess file.

RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule ^(.*) - [E=HTTP_AUTHORIZATION:%1]
