### ISSUE TITLE
The UI not updated after upload the config-xx.json

### ISSUE THREAD

**Issue by waelkalesh** [inspireui/support#3016]
Step 1 (require): detail issues and screenshots

1- I installed mstore-api plugin and change some of UI in application and changed "isCaching" to true
But no changing at all 
I checked the JSON information from this URL every thing right the JSON info updated 
but in the app nothing changed!!!!!
this URL : https://khalasli.com/wp-json/mstore/v1/cache 

2-Is there another plugin like WPML for currency swither.
3-I have white screen when open chat with vendor.

I shared with you config and common and the purchase code via google Form 

also one more thing how to print all coupons code to console

also when i build the project i have this problems in next photo 
![ice_screenshot_20200504-224235](https://user-images.githubusercontent.com/46270193/81006872-e6488500-8e58-11ea-8f98-82c4ae864198.png)

![ice_screenshot_20200504-224217](https://user-images.githubusercontent.com/46270193/81006909-efd1ed00-8e58-11ea-995a-e6b02206af32.png)

**Comment by jinuem** [comment]
Same Issue I am facing in my Multi-Vendor after enabling isCaching. 
App Goes Blank.(Black Screen)
"http://170.249.194.58/~democam/wp-json/mstore/v1/cache"

> Already posted my purchase proof in this ticket.
> [https://github.com/inspireui/support/issues/2981](url)

**Comment by minhcasi** [comment]
@waelkalesh 

Thank you for the feedback.

Please help us to submit this form and fill all require info to continue with the support  - http://private.inspireui.com/ 

We will close this ticket as is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!
----

@jinuem - the blank screen is fixed on latest version, we will update new version shortly - thank you!

**Comment by waelkalesh** [comment]
I already sent to you via google form all what you need

**Comment by waelkalesh** [comment]
> @waelkalesh 
> 
> Thank you for the feedback.
> 
> Please help us to submit this form and fill all require info to continue with the support  - http://private.inspireui.com/ 
> 
> We will close this ticket as is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!
> 
> @jinuem - the blank screen is fixed on latest version, we will update new version shortly - thank you!
> 

What info you need i sent to you purchase code

**Comment by minhcasi** [comment]
@waelkalesh sorry could i know your email as we could not get the form according to this ticket 3016 - thank you for your time

**Comment by waelkalesh** [comment]
nostalgiakalesh@gmail.com

**Comment by minhcasi** [comment]
verified - thank you!

**Comment by minhcasi** [comment]
1- fixed on latest version, we will update new version in 1-2 days

2- sorry we don't know other plugin, -> WPML is our suggestion 

also one more thing how to print all coupons code to console - you could set the break point to debug from coupon model, or you could use this API - https://woocommerce.github.io/woocommerce-rest-api-docs/#retrieve-a-coupon

also when i build the project i have this problems in next photo - try to clean cache https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

~~~~

3-I have white screen when open chat with vendor. - @kvt0012 - please help to check this issue

**Comment by waelkalesh** [comment]
I'm still waiting for new release of mstore api plugin.

**Comment by minhcasi** [comment]
@waelkalesh - please help to download latest 1.7.3 - it is compatible with Flutter 1.17 as well

Let us know your checking
