### ISSUE TITLE
Unoptimized APK

### ISSUE THREAD

**Issue by themanchev** [inspireui/support#3017]
Hi,

I am trying to publish the app for a closed test but the publish button is inactive and I get this error:

“Unoptimized APK

Warning:

This APK results in unused code and resources being sent to users. Your app could be smaller if you used the Android App Bundle. By not optimizing your app for device configurations, your app is larger to download and install on users’ devices than it needs to be. Larger apps see lower install success rates and take up storage on users’ devices.”

I have tried everything and cannot proceed. I have generated the apk the way youve stated at the documentation and and also by Build > Flutter > Build APP Bundle.

What should I do now?

<img width="810" alt="proof" src="https://user-images.githubusercontent.com/38177670/80972336-e70bf780-8e15-11ea-9b67-f656dbed0588.PNG">

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all require info to continue with the support  - http://private.inspireui.com/ 

We will close this ticket as is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
Hi @themanchev - could I know how total MB on your APK? Try to check if you have included some heavy assets files? Thank you!

**Comment by themanchev** [comment]
Its 36mb, no heavy asset files included

**Comment by minhcasi** [comment]
@themanchev 
That size is not too big.

Could you try to run `flutter build apk --split-per-abi`
You could check this guide could be helpful https://flutter.dev/docs/deployment/android

**Comment by themanchev** [comment]
Hey again,

I have tried everything, went from 0 again just now and only changed REST API, app name and keys, still same error from Google. Would it be possible to send my build and tell me what could be wrong, I am starting to lose my mind over this issue
