### ISSUE TITLE
Push notifications questions (Not an issue)

### ISSUE THREAD

**Issue by colourtest** [inspireui/support#3018]
Hi,

I'm new to the subject, so apologies for daft questions.
1. If push notifications can be controlled via firebase, why would I use onesignal?
2. Can I send a push notifications to certain users after 30 days from placing an order for example? If so, would I need onesignal premium plan?
3. Is onesignal multi-site?

Thank you!

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all require info to continue with the support  - http://private.inspireui.com/ 

We will close this ticket as is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!
