### ISSUE TITLE
[MultiVendor] Screen goes Black after updating isCaching to True

### ISSUE THREAD

**Issue by jinuem** [inspireui/support#3019]
Step 1 (require): detail issues and screenshots
The app was working perfectly.

I have Uploaded my `lib/config/config_en.json`
to my MStore API (activated by purchase code too)
I can see the JSON "http://170.249.194.58/~democam/wp-json/mstore/v1/cache".
Also Installed "WP_REST_CACHE_ plugin and Cleared.
And enabled isCaching = true in `lib/common/config/general.dart`.

Now App Goes black. And Widgets are not loaded.
<img width="1432" alt="Screenshot 2020-05-04 at 9 31 26 PM" src="https://user-images.githubusercontent.com/3512723/80986740-9ebcfb80-8e4e-11ea-9610-4932dbedd08f.png">

The app working perfectly if isCaching is false.
What issue is this? 

but Code assessing this URL.
`"http://170.249.194.58/~democam/wp-json/wc/v2/flutter/cache?oauth_consumer_key=XXXX&oauth_nonce=gqbizrsmat&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1588607198&oauth_token=&oauth_version=1.0&oauth_signature=p2%XXXX"
`
The response JSON File link attached:
[https://www.icloud.com/iclouddrive/0ALJywkAicLDdkyUoetrQG4Mw#cache](url)

and Debug Console SS:
<img width="686" alt="Screenshot 2020-05-04 at 9 47 56 PM" src="https://user-images.githubusercontent.com/3512723/80988293-ecd2fe80-8e50-11ea-8655-fcd6836b3556.png">

<img width="725" alt="Screenshot 2020-05-04 22 50 18" src="https://user-images.githubusercontent.com/3512723/80994060-c49bcd80-8e59-11ea-81b5-47a37f5cafcc.png">

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)
SUBMITTED
*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhcasi** [comment]
@jinuem - pls help to followup and raise this issue to the same ticket - thank you for your time - #2981
