### ISSUE TITLE
[MStore Pro] Banner Layout display only one word of the Product name

### ISSUE THREAD

**Issue by Relimer-Technologies** [inspireui/support#302]
**Mandatory Info (please complete the following information):**

* Product: [e.g. MStore, ListApp]
  M Store Pro
  Purchase Code: d98eb201-aba4-4c76-a0a1-cbd67415737d
* Your Purchased Code: [get from https://codecanyon.net/downloads]
  (we may not reply if you are not our customer)

**Describe the issues**
Hello,

Good Evening, I have purchased M Store Pro from Envato. I have done all the setup required... I have installed all of the required tools... When I assign a category to the banner section in the layout. The product names are displayed only one word... The second word of the product name is not displayed. I need a solution to this as soon as possible.

Thank You.

**Comment by Relimer-Technologies** [comment]
I am very disappointed with the rash behaviour of @minhtruong315 
I need some other executive to solve my problem.
Thank You

**Comment by luyx2412** [comment]
HI @Relimer-Technologies Sorry about that. Can you provide your AppConfig.json and Config.js file?

Thanks

**Comment by Relimer-Technologies** [comment]
Hi... @luyx2412  I am providing the AppConfig.json file and Config.js file.

[AppConfig.txt](https://github.com/inspireui/support/files/2864044/AppConfig.txt)

[Config.txt](https://github.com/inspireui/support/files/2864046/Config.txt)

**Comment by luyx2412** [comment]
HI @Relimer-Technologies What's the second word you want to show?

![image](https://user-images.githubusercontent.com/8909619/52831230-768c9400-3106-11e9-892f-5bf201258a9c.png)
![image](https://user-images.githubusercontent.com/8909619/52831437-38dc3b00-3107-11e9-9288-7acf95b3f3cd.png)


Thanks

**Comment by Relimer-Technologies** [comment]
It was not showing during the debugging to my android device... After deployment, it is working good... Is there any option for guest checkout...?

**Comment by Relimer-Technologies** [comment]
See the below image the product is Sonamasoori it is just showing Sonama-
![image](https://user-images.githubusercontent.com/47352123/52838850-08ea6300-311a-11e9-8f38-69e34913b6d7.jpeg)

**Comment by Relimer-Technologies** [comment]
The category icons below the banner layout don't show the respective title... 
I need two changes... The guest checkout is not available if a user wants to buy a product without logging in he/she is unable to do that... One more thing is the notification bar colour changes to grey which looks odd... You can see that in the image above... Send me the solution to this problem
![image](https://user-images.githubusercontent.com/47352123/52839229-53b8aa80-311b-11e9-92ef-3bbeb0544e55.jpeg)


See the above image Guest is displayed as Gues... Moreover, if a person orders anything his ordered is displayed default as completed both in Wordpress backend and the App... Please respond to my problem as early as possible... Thank You

**Comment by Relimer-Technologies** [comment]
See the below image on Login button the text is shown as LO- instead of Login... and even the last line in the page instead of Sign In it is displayed as Sign
![image](https://user-images.githubusercontent.com/47352123/52839733-1c4afd80-311d-11e9-94a9-c1f93f36a9cb.jpeg)


I have experimented the APK on various devices... First thing is that when we try to install the APK file on any device I get the warning message of Blocked by Play Protect... I use Install anyway option to install it and then the App is installed in few devices and few devices it doesn't get installed... Second thing is that the layout and all the bugs which I mentioned above is coming in the devices whose screen resolution is less than 19:9... I checked the layouts and other things which I face on my mobile which is 19.5: 9 screen ratio in the device of 16: 9 it is coming fine... Please help me with the problem as soon as possible.... Thank You

**Comment by luyx2412** [comment]
Hi @Relimer-Technologies Can you provide your current device which used the testing. 

Thanks

**Comment by Relimer-Technologies** [comment]
The Current device which I used for testing is Realme U1... The major thing I want help in is the Checkout page where I order anything the status in the Wordpress and the Application is shown as completed instead of showing In Process... I need this issue solved for first... Please help me with this first... Remaining other issues can be done later first help me out with the issue I mentioned above... Thank You

**Comment by Relimer-Technologies** [comment]
Hello, @luyx2412  I am waiting for your reply... Please provide me with a solution to my problem... Majorly, I need a solution in the checkout page where I order anything the status in the Wordpress and the Application is shown as completed instead of showing Processing... Please help me with this first... Please help me out with this issue... Thank You

**Comment by luyx2412** [comment]
HI @Relimer-Technologies We have two ways to resolve your issue. But i will provide the best way.
in `src/containers/Cart/Payment/index.js` --> line `88`. Please add the line `status: "completed"` look like the photo.
https://www.screencast.com/t/9JGZiPmCDVb

And please read the Woocommerce document to more understand http://woocommerce.github.io/woocommerce-rest-api-docs/#order-properties

Thanks
