### ISSUE TITLE
[Flux Listing]Start and HotReload error

### ISSUE THREAD

**Issue by adnanmur** [inspireui/support#3020]
Fluxstore Listing Flutter

Category.dart 31 Line

FlutterError (A CategoryModel was used after being disposed.
Once you have called dispose() on a CategoryModel, it can no longer be used.)

25113066 
2020-01-26 11:32:30 UTC

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all require info to continue with the support  - http://private.inspireui.com/ 

We will close this ticket as is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by adnanmur** [comment]
Dear sir,

I tried opening this provided website but its not working, err connection
refused, maybe firewalled or something.

**Comment by philipvu30** [comment]
Hi,

It seems you have not submitted the required information yet. Also please provide more error details in images. Thank you.

**Comment by adnanmur** [comment]
Dear Inspireui/Support,

Once again im repeating i cant OPEN the website provided
private.inspireui.com!

br


Adnan Muratovic

Account Director

Marketing | Konzept Digital & Social Media
+38761442685 | +38761442685
adnanmuratovic@gmail.com
konzept.ba
Terezije BB, Skenderija, Sarajevo
[image: facebook] <https://www.facebook.com/konzept.ba/>
[image: twitter] <https://twitter.com/konzept_social>
[image: linkedin] <https://www.linkedin.com/company/konzept-social-media/>
[image: instagram] <https://www.instagram.com/konzeptsocial/>

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
05/05/20,
12:59:24 PM

**Comment by adnanmur** [comment]
http://private.inspireui.com/ this link is not working

**Comment by adnanmur** [comment]
I have found your form from another link and its working now, i have sent all the required data.

**Comment by minhcasi** [comment]
@adnanmur - pls help to move your all conversation to the same ticket #3047 - thank you!
