### ISSUE TITLE
Checkout issue response takes extremely long time 

### ISSUE THREAD

**Issue by abqrinou** [inspireui/support#3021]
FluxStore 1.7.2
checkout button is not working instantly, it is taking too much time to perform next action, meanwhile people will be keep pressing it, this will create lot of duplicate orders in COD

- in version 1.6.6b .. It was "loading" onLoading Activated. It is not cannot be pressed again
What is the solution this issue? or how i can Activate "onLoading" in place order Until the application success page is loaded.

**Comment by yasernet1989** [comment]
i have same issue also. any more presses it will create multiple duplicate orders.
please help

**Comment by drew1607** [comment]
Same issue as well, I strongly feel its best you also put back the previous loading indicator to stop duplicate entries

**Comment by minhtruong315** [comment]
@abqrinou check this solution https://github.com/inspireui/support/issues/2947#issuecomment-622820068

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
