### ISSUE TITLE
Issue trying to create order ..

### ISSUE THREAD

**Issue by nahuelbourdichon** [inspireui/support#3022]
Hello I have the next issue  trying to create order .

I/flutter ( 7251): [2020-05-04 22:37:22.351564Z][Fluxstore][wocommerce_api][19:37:22.351492] postAsync START [endPoint:orders] url:https://maspuntos.com.ar/wp-json/wc/v2/orders?consumer_key=xxxxxxxxxxxxxxxxxxxxxxxxxxxx&consumer_secret=xxxxxxxxxxxxxxxxxx
I/flutter ( 7251): [2020-05-04 22:37:23.676112Z][Fluxstore][wocommerce_api][19:37:23.676039] postAsync END [endPoint:orders]
I/flutter ( 7251): #0      WooCommerce.createOrder (package:fstore/services/woo_commerce.dart:604:9)
I/flutter ( 7251): <asynchronous suspension>
I/flutter ( 7251): #1      Services.createOrder (package:fstore/services/index.dart:257:23)
I/flutter ( 7251): #2      WooWidget.createOrder (package:fstore/widgets/frameworks/woocommerce/index.dart:122:12)
I/flutter ( 7251): #3      WooWidget.placeOrder (package:fstore/widgets/frameworks/woocommerce/index.dart:151:7)
I/flutter ( 7251): #4      _PaymentMethodsState.placeOrder (package:fstore/screens/checkout/payment.dart:321:27)
I/flutter ( 7251): #5      _PaymentMethodsState.build.<anonymous closure> (package:fstore/screens/checkout/payment.dart:261:38)
I/flutter ( 7251): #6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706:14)
I/flutter ( 7251): #7      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:789:36)
I/flutter ( 7251): #8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
I/flutter ( 7251): #9      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
I/flutter ( 7251): #10     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/t

I tried to create order by postman software and get the same problem 

{
    "code": "rest_invalid_param",
    "message": "Invalid(s) Parámeter(s): status",
    "data": {
        "status": 400,
        "params": {
            "status": "status is not one of the following processing, completed, cancelled, refunded, listopararetirar."
        }
    }
}

I sent the code by https://docs.google.com/

my site https://www.maspuntos.com.ar/

Thanks 
Nahuel

**Comment by minhcasi** [comment]
Hi @nahuelbourdichon - it seems the issue from your Wordpress Rest API - pls check the format from https://woocommerce.github.io/woocommerce-rest-api-docs/#create-an-order 

Did you customize the app that causes the issue - thank you!

**Comment by nahuelbourdichon** [comment]
Hello Sorry what did you say  about next paragraph  
**Did you customize the app that causes the issue - thank you!**,
 because I didn't do any change in Fluxtore app . 
I sent this json by postman adding status processing and this work 

{
  "payment_method": "cod",
  "payment_method_title": "contra rembolso",
  "set_paid": true,
  "status": "processing",
  "billing": {
    "first_name": "John",
    "last_name": "Doe",
    "address_1": "969 Market",
    "address_2": "",
    "city": "San Francisco",
    "state": "CA",
    "postcode": "94103",
    "country": "US",
    "email": "john.doe@example.com",
    "phone": "(555) 555-5555"
  },
  "shipping": {
    "first_name": "",
    "last_name": "",
    "address_1": "",
    "address_2": "",
    "city": "",
    "state": "",
    "postcode": "",
    "country": ""
  },
  "line_items": [
    {
      "product_id": 188,
      "quantity": 2
    },
    {
      "product_id": 189,
      "quantity": 1
    }
  ]
  
}

so please can you check it  or tell me in which part of code fluxtore app make the json to send to wordpress  site !!. because I need analyze it ..

Thanks

**Comment by minhcasi** [comment]
Hi, you could debug from this file 

<img width="893" alt="Screen Shot 2020-05-06 at 08 26 04" src="https://user-images.githubusercontent.com/1459805/81130798-3ca9e680-8f73-11ea-9d91-1d313441e0ae.png">

**Comment by hengsoheak** [comment]
I got this error when process payment when I update all api plugin  
`Invalid parameter(s): billing, shipping`
