### ISSUE TITLE
How to configure MStore magento login and payment

### ISSUE THREAD

**Issue by 234146326** [inspireui/support#3024]
Step 1 (require): 

1. This doc link;
![image](https://user-images.githubusercontent.com/17285770/81046321-b649c200-8eea-11ea-82e6-1c44860d5041.png)
![image](https://user-images.githubusercontent.com/17285770/81046407-e7c28d80-8eea-11ea-9495-57480494968f.png)
2 I cannot access the document.
![image](https://user-images.githubusercontent.com/17285770/81046453-fc9f2100-8eea-11ea-9d83-323ea17cf19c.png)

Step 2 (require): 
My problem :

> 1. How to configure social login?.
> 2, and payment issues.
> 

I hope to get detailed documentation.Thank you.

**Comment by minhcasi** [comment]
@234146326 - sorry it is missing link - pls try this one https://docs.inspireui.com/mstore-magento/customization/ - the current website is the document :)
