### ISSUE TITLE
FluxStore - YouTube videos 

### ISSUE THREAD

**Issue by LiamBayford123** [inspireui/support#3025]
Is it possible to embed Youtube Videos to the app?

**Comment by philipvu30** [comment]
Hi,

It's possible but we do not provide customization services at the moment. You have to add it yourself or hire a freelancer to help you. Thank you

**Comment by minhcasi** [comment]
@LiamBayford123 - you could import as the embed iframe link - it will display on the app, example adding through the product description - we are using this library https://pub.dev/packages/flutter_widget_from_html - thank you!
