### ISSUE TITLE
[Fluxstore-MV] - Set default zip code and dropdown cities at checkout 

### ISSUE THREAD

**Issue by ideas24** [inspireui/support#3026]
Step 1 (require): detail issues and screenshots
1. I would like to set a default zip code since my country uses only one zip code. I don't want customers to be entering zip code at checkout. I want to set a difficult zip or better still hide it altogether.

2. I ship to specific cities in my country hence I would like to set these default cities in the app so the user will select their city at checkout. I already achieved this on the website.
If possible make the cities configurable at the config_en.json file. Thanks 

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by philipvu30** [comment]
Hi,

Thank you for using our product. 
We appreciate your suggestion. But we do not provide customization services at the moment.
I suggest hiring a freelancer to add those features if you cannot wait for the future update.

**Comment by minhcasi** [comment]
@ideas24 

1- you could try to add zip code as hard code - https://tppr.me/s1ROY 
2- The city could reuse from the State - config/states/state_xx.json - example you could rename the State to City 👍
