### ISSUE TITLE
Fluxnews authentication issue

### ISSUE THREAD

**Issue by rherreror** [inspireui/support#3027]
Hello,

Fluxnews
version: 1.4.0+3003

My configuration in common/config.dart (the other part is the same that i have downloaded)
/// Server config
const serverConfig = {
  "url": "http://ampamartamata.fundacioviladecans.net",
  "forgetPassword": "https://ampamartamata.fundacioviladecans.net/wp-login.php?action=lostpassword"
};

Im using mstore-api wordpress plugin (version 2.3.6) and i see in your documentation that:
= 2.0.0 =
  * Major update to remove the depend on JSON API plugins

I can see the following code in fluxnews to authenticate a user against wordpress. That code throws an exception because that endPoint doesnt exist in my wordpress installation. $url/wp-json/jwt-auth/v1/token?username=$username&password=$password -> this url doesnt come from mstore-api but wp-json.

that code is in wordpress.dart ->
 `  Future<String> getJwtAuth(String username, String password) async {
    try {
      var endPoint =
          "$url/wp-json/jwt-auth/v1/token?username=$username&password=$password";
      var response = await http.post(endPoint);
      var jsonDecode = convert.jsonDecode(response.body);
      if (jsonDecode['token'] == null) {
        throw Exception(jsonDecode['code']);
      }
      return jsonDecode['token'];
    } catch (e) {
      //This error exception is about your Rest API is not config correctly so that not return the correct JSON format, please double check the document or contact supporters/
      throw e;
    }
  }`

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all require info to continue with the support  - http://private.inspireui.com/ 

We will close this ticket as is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by rherreror** [comment]
I have already filled the form with more information (2 times)

**Comment by rherreror** [comment]
are you using this plugin from the wordpress side? i have not seen nothing about it in your documentation.

https://wordpress.org/plugins/jwt-authentication-for-wp-rest-api/

**Comment by minhcasi** [comment]
@rherreror - we have got your info - thank you for your time :)

Yes, the jwt plugin is required on the latest release of the Fluxnews to support the Author could able create a new Post from the app. Please also update the mstore-api to the latest one - thank you!

**Comment by rherreror** [comment]
Thank you, but it's really hard to be able to configure the app with an outdated documentation.

**Comment by minhcasi** [comment]
@rherreror - we will upgrade the document to compatible with latest Fluxnews - thank you for your suggestion
