### ISSUE TITLE
Building for the IOS CodeSign Fauile

### ISSUE THREAD

**Issue by iamglicious** [inspireui/support#3028]
While im building the IOS thru visualcode or xcode im getting an error with the codesign and for that it can't build the IOS version.

I have tried several things.
- Compiled a new version
- flutter update
- flutter beta
- removed all the keys 

Im working on Xcode 11 

https://www.dropbox.com/s/flbv9q2eht6td40/Screenshot%202020-05-05%2013.39.14.png?dl=0
https://www.dropbox.com/s/1oolkje6rm269wu/Screenshot%202020-05-05%2013.47.11.png?dl=0

**Comment by minhcasi** [comment]
Hi, pls try to open Xcode and config the Signing with your own Apple account 

<img width="792" alt="Screen Shot 2020-05-05 at 7 28 54 PM" src="https://user-images.githubusercontent.com/1459805/81066054-b8ba1500-8f06-11ea-95e7-cdf8c862cdb9.png">

**Comment by iamglicious** [comment]
I have done that but error keeps coming

https://www.dropbox.com/s/cu6a0wikkyjcwcz/Screenshot%202020-05-05%2014.36.58.png?dl=0

**Comment by minhcasi** [comment]
Hi, also try to use stable channel, instead of beta
```
flutter channel stable
flutter update --force
```

Make sure to run `flutter release ios` before open XCode to Archive the project

**Comment by iamglicious** [comment]
[LOGS.pdf](https://github.com/inspireui/support/files/4586586/LOGS.pdf)
Hi,

I have done that several times but have done everything again so you can see i can't even go to Xcode because its not building in visual code for the same reason

**Comment by minhcasi** [comment]
Hi, could i check if you have changed the Bundle ID? Please make sure to create a new one if you would like to release your app on Appstore - thank you!

**Comment by iamglicious** [comment]
Hi,

so yes I checked the bundle id. I have created a new one.
Also i download the latest version used the script and changed the bundle id.

But now I get a new error. I have used the stable flutter, double checked the signature but now. Im working on this for almost 2 weeks. Double checked everything.

So even if i started fresh still having issues. So please let me know what I can do.
Im willing to start over again. 

Compiler message:
    ../../gregoryvrede/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image-0.7.2/lib/src/gesture/extended_image_slide_page_route.dart:333:9: Error: No named parameter with the name
    'animation'.
            animation: animation,
            ^^^^^^^^^
    ../../gregoryvrede/flutter/packages/flutter/lib/src/cupertino/route.dart:435:3: Context: Found this candidate, but the arguments don't match.
      CupertinoFullscreenDialogTransition({
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
    build failed.
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

Encountered error while building for device.
gregoryvrede@MacBook-Pro-2 iamerch % 
[pdfr.pdf](https://github.com/inspireui/support/files/4600892/pdfr.pdf)

**Comment by iamglicious** [comment]
> Hi, could i check if you have changed the Bundle ID? Please make sure to create a new one if you would like to release your app on Appstore - thank you!

This issue is not resolved yet
