### ISSUE TITLE
Fluxnews Google Sign In

### ISSUE THREAD

**Issue by rherreror** [inspireui/support#3029]
Hi,

im in Fluxnews 1.4.0. and configured correctly Google Sign In (it works fine with no error). 

...but when  a user goes out from the app (and killed by android so)  when user comes back to the app he must log in again, I think internally he is logged, but the view doesnt reflects it. I dont mean user has clicked the log out button just that the app has gone to background.

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all require info to continue with the support  - http://private.inspireui.com/ 

We will close this ticket as is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by rherreror** [comment]
sended form with information

**Comment by minhcasi** [comment]
@dttrung26 - pls help with suggestion ;)

**Comment by dttrung26** [comment]
Hi @rherreror , so sorry for taking so long in replying your ticket. Due to large modification on source code, this issue will be fixed in the next patch. 
Thank you so much for reporting us and for your patience as well. 
Stay safe.
