### ISSUE TITLE
Installing Plugin

### ISSUE THREAD

**Issue by jane207593** [inspireui/support#303]
Hi!
I am facing issue while installing pluging always find that issue, not valid plugins found.
![image](https://user-images.githubusercontent.com/47419219/52775715-23610580-3062-11e9-9c33-72dd1dec363d.png)
please check it!
I am installing the plugins provided in that folder!

**Comment by minhcasi** [comment]
Hi, this is related to the Wordpress installing plugin, basic issue when installing the Wordpress  

try to copy the plugins file to the wp-content/plugins

Or update the wp-config.php and add this line: define('FS_METHOD', 'direct')

**Comment by jane207593** [comment]
we are facing issue with regenerating thumbnails on server we checked that there are missing some of auth files and there were missing some plugins please check the attached files i have uploaded and installed plugins but in the provided document there are more files please guide me about.

![image 1](https://user-images.githubusercontent.com/47419219/52959352-ccd42e00-33b7-11e9-9c9b-36c4493fff30.png)
![image 2](https://user-images.githubusercontent.com/47419219/52959353-ccd42e00-33b7-11e9-8409-fd92255fe046.png)
![image 3](https://user-images.githubusercontent.com/47419219/52959355-cd6cc480-33b7-11e9-86b3-b8599785e213.png)
