### ISSUE TITLE
[Fluxstore] flutter build issue

### ISSUE THREAD

**Issue by arjuntu1990** [inspireui/support#3030]
Hi Team,
I am getting the error pasted below when i try to run fluxstore flutter project in android studio. Then screenshot is also uploaded.

Executing tasks: [:app:assembleDebug] in project /home/AndroidStudioProjects/flutter/FluxStore 1.7.2/source/android

> Task :app:compileFlutterBuildDebug
Target kernel_snapshot failed: FileSystemException: Cannot open file, path = '/home//AndroidStudioProjects/flutter/FluxStore 1.7.2/source/.packages' (OS Error: No such file or directory, errno = 2)
build failed.

> Task :app:compileFlutterBuildDebug FAILED

FAILURE: Build failed with an exception.

* Where:
Script '/home//Android/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 780

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/home//Android/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s

whenrun with stack trace option i got te error below
Caused by: org.gradle.process.internal.ExecException: Process 'command '/home/arjuntu/Android/flutter/bin/flutter'' finished with non-zero exit value 1

![Screenshot from 2020-05-05 16-56-16](https://user-images.githubusercontent.com/49298215/81068366-de8eec00-8efd-11ea-89b8-42a754f4622a.png)
*

**Comment by minhcasi** [comment]
@arjuntu1990 - please try to clean cache to fix this issue - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1 - thank you!
