### ISSUE TITLE
CE builder is not working

### ISSUE THREAD

**Issue by postonoh** [inspireui/support#3032]
The CeBuilder is not working the tool link is not displaying on my mac.  BeoNewPro

**Comment by minhcasi** [comment]
@postonoh - could you help to attache the screenshot so that we could help for checking the issue? Thank you!

**Comment by postonoh** [comment]
Here is the link with errors

[https://drive.google.com/open?id=1OdW-UsVcKi5kH2GE8137uYKCgz-ZRNHr](url)

**Comment by luyx2412** [comment]
HI @postonoh I did not see your url, Can u send again?

Thanks

**Comment by postonoh** [comment]
https://drive.google.com/open?id=1OdW-UsVcKi5kH2GE8137uYKCgz-ZRNHr

**Comment by minhcasi** [comment]
@postonoh - it's seem there is any issue with the Cebuilder permission, could you help to try with the orginal method by running the script, pls help to check and install the library from react native homepage guide - https://reactnative.dev/docs/getting-started - thank you!

**Comment by postonoh** [comment]
I manually installed all of the plugin I can at least get the android to runs, the ios version does not work getting a lot of error messages 

https://drive.google.com/drive/folders/1OdW-UsVcKi5kH2GE8137uYKCgz-ZRNHr
Please give me quick response  its going 10 days.

**Comment by luyx2412** [comment]
Hi @postonoh You can read the document to install manual https://docs.inspireui.com/beonews/getting-started/

Thanks

**Comment by postonoh** [comment]
Why did close this the issues has not been resolved.
