### ISSUE TITLE
New account/Login issue

### ISSUE THREAD

**Issue by xsamir** [inspireui/support#3034]
Step 1 (require): detail issues and screenshots
Login usually shows "Warning: Exception: The username or password Is incorrect"
![image](https://user-images.githubusercontent.com/7432001/81125982-f2ad0a80-8f4a-11ea-9dac-0b7fca56d36d.png)

For Signup shows "Exception: Sorry, you are not allowed to do that."
![image](https://user-images.githubusercontent.com/7432001/81126077-43bcfe80-8f4b-11ea-9544-c74d2c4379a7.png)

* I do all steps in the tutorial (step by step) and review it multiple times.
** I'm using google cloud as a host, and all products and blog shows fine on the app without problems.

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhcasi** [comment]
@xsamir - could i check if you have activated the License from mstore-api plugin (Wordpress site)?

**Comment by xsamir** [comment]
Thank you for your support, it works after I verify the MStore API with the purchase code.

**Comment by minhcasi** [comment]
@xsamir - We're glad that it help, please give us some feedback/rating to this page https://codecanyon.net/downloads  if the product is helpful for your business, we are working hard to update more awesome and powerful features on next coming version release. Let us know if you have any feedback. Thank you very much 😊
