### ISSUE TITLE
Multi vendor app sign up page loading

### ISSUE THREAD

**Issue by basssel1993** [inspireui/support#3036]
Dear,
when i sign up it took unlimted time to load as per attachments. 
how can i solve it?
Note: while loading the signup user and pass registerd at firefase only in case gmail login and sign up with mail. 
but sms verified loading with out sign up
![Screenshot_20200506_044627_com basel sonikstore vendor](https://user-images.githubusercontent.com/52530818/81134700-d5ca0480-8f55-11ea-9f8e-bddfa4801587.jpg)
![Screenshot_20200506_044653_com basel sonikstore vendor](https://user-images.githubusercontent.com/52530818/81134702-d6fb3180-8f55-11ea-9d25-ffd622004f1f.jpg)
![Screenshot_20200506_044829_com basel sonikstore vendor](https://user-images.githubusercontent.com/52530818/81134703-d6fb3180-8f55-11ea-8959-18b1b176128a.jpg)

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all require info to continue with the support  - http://private.inspireui.com/ 

We will close this ticket as is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
Sorry, we should closed this ticket as it could not be verified, please create the new one when you got enough purchased info - thank you!
