### ISSUE TITLE
Update 1.7.2,  "Loading... " shows in all products.

### ISSUE THREAD

**Issue by sercada** [inspireui/support#3037]
Step 1 (require): detail issues and screenshots
Hi, I'm trying your updated version 1.7.2 but when I open all products a "Loading..." sign show on the image of the product. Everything loads but it remains there. I've tried disabling all plugins in my website just in case there's some issue with them and there's no change. 

![Screen Shot 2020-05-05 at 11 54 07 PM](https://user-images.githubusercontent.com/24389792/81139563-c930b680-8f2b-11ea-9579-44a69ba62196.jpg)

I'd appreciate your help with this issue, this was not happening with version 1.7.0.

**Comment by philipvu30** [comment]
Hi,

Please uncomment the below term. You can find it here lib/screens/detail/variant_image_feature.dart 

![image](https://user-images.githubusercontent.com/54442328/81167453-70126280-8fbf-11ea-956d-ae3d2f5e8956.png)

**Comment by sercada** [comment]
This has solved my issue. Thanks again for your great support.
