### ISSUE TITLE
BeoNews - App Rejected by Apple Store

### ISSUE THREAD

**Issue by kevlict** [inspireui/support#3038]
Dear sir/madam,

My purchase code is b33d6761-b089-4dee-8f99-8d4859eaad59

I have installed the BeoNews App and prepared to upload the App Store. However, it was rejected due to minimum functionality and provide me this reason:

=========================================
Guideline 4.2.2 - Design - Minimum Functionality

We noticed that your app only includes links, images, or content aggregated from the Internet with limited or no native iOS functionality. Although this content may be curated from the web specifically for your users, since it does not sufficiently differ from a mobile web browsing experience, it is not appropriate for the App Store.

Next Steps

We encourage you to review your app concept and work towards creating an app that offers customers an engaging and lasting experience that also meets the App Store’s high expectations for quality and functionality.

Apple Developer includes a variety of design and development resources. Download iOS templates from Apple UI Design Resources, learn more about crafting intuitive, well-designed apps with the Design Video collection, and review the iOS Human Interface Guidelines for best practices to follow when designing apps for the App Store.

===================================

I have disable the login function and video navigation menu only.

Since that's all functions that BeoNews can provide, I wish to have your opinion on that and how it can be fixed.

Thanks
Kevin

**Comment by minhcasi** [comment]
@kevlict - the Apple preview is quite a sensibility and strictly recently, please check following solution to pass these issues reviews:
- Review your all Image with high resolution on iphone
- Double-check the links or it should not contain the demo or lorem text
- Try to change the Category of the app items, some Category is strictly if you have not to match with their criteria, example 'Food delivery' should not put in 'Travel' 
- Double-check your all screenshot, it should use the iphone, not take from Android

Good luck!
