### ISSUE TITLE
[Fluxshopify] Payment settings

### ISSUE THREAD

**Issue by phcaraujo** [inspireui/support#3039]
I would like to know what forms of payment Fluxshopify accepts, the video does not show this.

I don't use PayPal, I use Mercado Pago (Brazil).

**Comment by minhcasi** [comment]
@phcaraujo - pls use the latest Fluxstore Shopify and include update config/payment.dart - EnableOnePageCheckout: true - then it will support all type of payment gateway from Shopify 👍

Let us know if you have any questions - thank you!
