### ISSUE TITLE
[MStore Pro] Payment not processing, Cannot detect order-received URL

### ISSUE THREAD

**Issue by juraganwp** [inspireui/support#304]
- Product: MStore Pro
 - Your Purchased Code: 17780922-7c4e-44ab-a1a8-1156a6b3b3f8

**Describe the bug**
First Bug :
On iOS theres some problem with the payment page, on emulator is fine but some devices when an order is place the browser just processing about 2 seconds and nothing happens. 

Tested on two iPhone X with latest update, one of the iPhone can process the payment page successfully the other is stuck. I'm using bacs payment in the test.

Second Bug :
And i think the woocommerce order-received URL is changed, so after the payment is successfull the modal is not closing. So we stuck in payment page until we click the close button.

**Screenshots**
[VID-20190213-WA0006.mp4.zip](https://github.com/inspireui/support/files/2865783/VID-20190213-WA0006.mp4.zip)

I have send emails but no one response @minhcasi @luyx2412 @minhtruong315 @thangvo9x

**Comment by samber91** [comment]
I'm having the same issues . payment problems.  Nobody can place orders. Simulator is fine . but on the device, NO ! Sometimes android won't work.!

**Comment by luyx2412** [comment]
Hi @juraganwp Let me check right now and update with next version.

Thanks for your feedbacks.

**Comment by luyx2412** [comment]
Checked!

**Comment by juraganwp** [comment]
> Checked!

Hi, do you have estimated time when this fixed is pushed to codecanyon ? or i can have the modified version first because it's crucial to my business.

Thanks for quick response
