### ISSUE TITLE
Auto translation & currency for products?

### ISSUE THREAD

**Issue by xsamir** [inspireui/support#3040]
I'm using Multi-Vendor app (WooCommerce-WP)

1- How can I make the product information (Subject - Description) translated automatically based on the app language which is chosen by the user?
for example, integrating Google translation

2- Also, the product price based on the currency must be changed, but the only thing changed is the currency symbol and the price keeps the same!

**Should I do something on my Wordpress to let that happen? or it's something must be done on the app part?**

Thanks & regards,

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ 

We will close this ticket as is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
@xsamir - pls help us to move your all conversation to the same ticket 😊 - pls use #3071

Thank you so much for your support on other comment tickets, we're appreciated that ❤️
