### ISSUE TITLE
Categories and product images are not showing

### ISSUE THREAD

**Issue by webofficial** [inspireui/support#3041]
As per the team suggestion i have downloaded the latest version 1.7.0 but now the issue that i am facing is the products and the categories are not showing but the store page showing perfect.

before i used version 1.6.4 on that version store page was not working but products and categories are working very fine.
![Screenshot_20200506-155310](https://user-images.githubusercontent.com/64073974/81180151-48b59880-8fb3-11ea-80d4-97bd0a79d12f.png)
![Screenshot_20200506-151457](https://user-images.githubusercontent.com/64073974/81180167-4d7a4c80-8fb3-11ea-86ca-78f3f055d66a.png)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhtruong315** [comment]
@webofficial can u send me admin  account to login to your website? via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/3041

**Comment by webofficial** [comment]
Hello Sir,

As you said here i am mentioning the credential of website admin for
further process.Hope it will help.

website :-   http://mercadodev.wpengine.com/
adminpanel :- https://mercadodev.wpengine.com/wp-admin/
admin credentials :-  User :- sbwebofficial92@gmail.com
                                 Password :- merkado@123#@!

Please inform me if anything else needed.

Thanks & Regards
Subair ms

**Comment by minhcasi** [comment]
@webofficial - we have upgraded to latest Flutter 1.17 on v.1.7.3 - pls help to update to fix this issue - thank you!

**Comment by webofficial** [comment]
Hello Sir,

Is there any other option without upgrade because for solving this issue
this is the third version that i am downloading.

Please do help with dev team. case no #3041
<https://github.com/inspireui/support/issues/3041>

Thanks & Regards
Subair ms

**Comment by minhtruong315** [comment]
Hi @webofficial what is the version you're using?

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!

**Comment by webofficial** [comment]
Hello Inspireui/Support,

I have given what ever you guys asked then what happened, actually i was
waiting for your kind reply.But now you guys closed the ticket.hmm.

Thank you.
@webimobi

**Comment by minhcasi** [comment]
@webofficial - pls try to update your comment - we have closed as there is no response from you - it's reopened - thank you!

**Comment by webofficial** [comment]
Hello Inspireui/Support,

I have given the reply but i think the notifications@github.com i had
missed.any way last i have got a mail from Minhtruong315 about asking app
version so i have replied but now once more with whole details i will
explain.

#3041 <https://github.com/inspireui/support/issues/3041>

I am using version 1.7.0. Before I used v 1.6.4 that time my issue was
store page and you said to upgrade the version to solve the issue so I
upgraded but now store page working fine but categories and other product
images are not coming.

any files or credentials you want please ask me i will give but please
guide me what wrong am i doing with this issue or what i need to do to
solve this issue.

Thank you
@webimobi

**Comment by minhtruong315** [comment]
Hi @webofficial please replymy message on skype.Thanks

**Comment by webofficial** [comment]
Hello sir,
Right now I don't have laptop. If you don't mind can we talk Sunday about
this issue.is that possible?.please.

Thank you
@webimobi

**Comment by kibbyboi** [comment]
Hello, I have the problem

**Comment by kibbyboi** [comment]
For me Products take too long to show on the app

**Comment by minhtruong315** [comment]
![Simulator Screen Shot - iPhone X - 2020-05-17 at 19 55 42](https://user-images.githubusercontent.com/10402500/82147236-94e8be80-9878-11ea-8aa1-bfe8fdd47c9f.png)
@webofficial you didn't change category id on config_en.json by your website. so it doesn't products

**Comment by webofficial** [comment]
Hello sir,

That is ok but what my issue is the categories.the category page near store
page which is automatically used to change once we connect the website with
the app on config file.i need both the categories also the store page
should come once we config with website.

I hope now I make clear about the issue I was facing.

And you are so kind and patient to do deal with it I am so thank you for
that.can you please check what actually I was facing. I have mentioned
above all clearly. Please do ask me anything else you want regarding this.

Hopefully
@webimobi

**Comment by minhtruong315** [comment]
<img width="412" alt="Screen Shot 2020-05-17 at 8 50 19 PM" src="https://user-images.githubusercontent.com/10402500/82149028-109a3980-9880-11ea-84b4-735bb117add7.png">
The categories is working well

**Comment by webofficial** [comment]
Ok let me try the code and i will let you know today.Thank you for the
whole patients and help.

Regards
Subair ms

**Comment by webofficial** [comment]
Hello Sir,

I have checked the categories and store.Thank you very much all working
very well.Here i am mention one more issue  i saw that while registering
one error is showing that "please agree with out terms".even after we agree
the terms and conditions.
Please do help me on that, for making that correct where i want to change
and what correction i have to do.

Screenshot below.

Thankfully
@webomobi
