### ISSUE TITLE
iOS issues

### ISSUE THREAD

**Issue by midhun1983** [inspireui/support#3042]
I am not able to proceed as I am facing difficulty to integrate the libraries with the fluxstore using cocoapods.  Error given below.

![image](https://user-images.githubusercontent.com/4860644/81181097-8fae8880-8fc9-11ea-91e4-d0e0287899ae.png)

**Comment by adnanmur** [comment]
I am curios as well is it possible to integrate a secondary payment processor event through webview

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ 

We will close this ticket as is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by adnanmur** [comment]
Dear friendly team,

I have already done that and i have access to the gitlab portion. So it
means i am verified right now.

**Comment by minhcasi** [comment]
@midhun1983 - could you share your email or envato username so that we could search on the inbox, so far we could not verify your github ID - thank you for your time

**Comment by minhcasi** [comment]
@midhun1983 - pls help to update and create new ticket and there is no response on this ticket, thank you for your time
