### ISSUE TITLE
Fluxnews - Webview iOS - My old ticket #2921 was closed!

### ISSUE THREAD

**Issue by ernandozatariano** [inspireui/support#3043]
I dont no why, but my old ticket was closed:

https://github.com/inspireui/support/issues/2921#event-3292558248

I commented 5 days ago:

"Hi, i make a screen video to show my ios issue, using testflight and iphone 8. In webview page, when i I close the app and then reopen, or simple change between the tabs, i need to make login again in my wordpress page. The same not occurs in android version. Tks for help!"

[VIDEO-2020-05-01-19-38-22 (1).zip](https://github.com/inspireui/support/files/4587233/VIDEO-2020-05-01-19-38-22.1.zip)

Tks again :)

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ 

We will close this ticket as is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
Sorry, we should closed this ticket as it could not be verified, please create the new one when you got enough purchased info - thank you!

**Comment by ernandozatariano** [comment]
Hi, I Submit the Private Files For Support Ticket, tks again!
