### ISSUE TITLE
Multi-vendor Login error + unlimited time login

### ISSUE THREAD

**Issue by engbasselayman** [inspireui/support#3044]
Step 1 (require): detail issues and screenshots
..........................................................
when i logged in with gmail accounts i got error (as per video)
when i logged in with sms verify it took unlimited time (as per video)
when i sign up it took unlimited time (as per video)

[20200506_155151.zip](https://github.com/inspireui/support/files/4587264/20200506_155151.zip)

and
this is my screen shoots of configuration
![android app in firebase](https://user-images.githubusercontent.com/64425666/81187531-79e29880-8fb4-11ea-842e-f13766afd2ff.PNG)
![Authorized domains](https://user-images.githubusercontent.com/64425666/81187536-7b13c580-8fb4-11ea-9f75-da956390aa88.PNG)
![credentials](https://user-images.githubusercontent.com/64425666/81187538-7b13c580-8fb4-11ea-8080-be8df0d69316.PNG)
![firebase sign -in auth](https://user-images.githubusercontent.com/64425666/81187541-7bac5c00-8fb4-11ea-806c-88d14eb63b23.PNG)
![oAuth cosent screen](https://user-images.githubusercontent.com/64425666/81187542-7c44f280-8fb4-11ea-966b-d9b78df3ee99.PNG)

**Comment by trunghieuvn** [comment]
![](https://user-images.githubusercontent.com/64425666/81187542-7c44f280-8fb4-11ea-966b-d9b78df3ee99.PNG)

Log in with google, you check me at this step, did you choose email support? This is necessary because if not set it will fail.

![image](https://user-images.githubusercontent.com/19247680/81358642-4cefcc00-9101-11ea-9896-c0977f559f3b.png)

If that still doesn't work, please add me to your github/gitlab project. I will solve this problem quickly.

My Github / Gitlab: hieu.trantrung1204@gmail.com

**Comment by engbasselayman** [comment]
But I haven't gitlab project.
Can you support me remotely 
i have the problem for along and i try and try and try with any progress
hieu.trantrung1204@gmail.com

**Comment by engbasselayman** [comment]
this is the last time
![Screenshot_20200509_044024_com inspireui fluxstore vendor](https://user-images.githubusercontent.com/64425666/81462441-d27f8480-91b2-11ea-8355-42f83dec3227.jpg)
![Screenshot_20200509_044014_com inspireui fluxstore vendor](https://user-images.githubusercontent.com/64425666/81462443-d3181b00-91b2-11ea-9acf-c0df2017c32e.jpg)
![Screenshot_20200509_043933_com inspireui fluxstore vendor](https://user-images.githubusercontent.com/64425666/81462444-d3b0b180-91b2-11ea-87d6-4202e68912e3.jpg)

**Comment by minhcasi** [comment]
@trunghieuvn - there could be missing validate the Condition Term from the code?

**Comment by kenngigz** [comment]
having the same problem

**Comment by minhcasi** [comment]
@kvt0012 - pls help to check the Term checking issue

**Comment by kvt0012** [comment]
We're fixed this and this will be updated on next release, thank you

**Comment by kenngigz** [comment]
When is the next release? We have not been using the app, we are waiting on this issue to be fixed
.
