### ISSUE TITLE
Error at FluxStore + Woocomerce

### ISSUE THREAD

**Issue by informaticajovani** [inspireui/support#3045]
I have downloaded and followed the steps for the installation and startup of fluxstore + woocomerce, but problems arise.

When installing woocomerce modules, 258 error lines are generated.
The json file that I must upload to the store does not exist, at least in the path
I change the configuration of the **config.dart** file, introducing the web on which the app will be based, and it does not load, instead, the Who we are, telephones and several other things, if the change is reflected.

Image deleted as exposing consumer key/secret

<img width="584" alt="blog1" src="https://user-images.githubusercontent.com/64914565/81197956-33e00180-8fc1-11ea-9f1e-3ced78010bed.png">
![wordpress](https://user-images.githubusercontent.com/64914565/81197959-34789800-8fc1-11ea-9ab2-baa05fb2dcf6.jpg)

Thanks

**Comment by philipvu30** [comment]
Hi,

Just ignore the errors if your app successfully run. Also please remove the blog link in config.dart for displaying the blogs.

For other issues, I'm sorry I quite don't get what you meant. Would you mind providing more details in images?

**Comment by informaticajovani** [comment]
I try to explain
I do all the settings, but I feel like steps are missing. In wordpress, the mstore module asks me for a json file that does not exist.
I put the url of my store, and it is not shown.
You see my store in the settings, but not when I deploy the app.
It is important for me to have the operational application as soon as possible.
Thank you
--
Informatica FerreteriaJovani.com jueves, 07 mayo 2020, 05:52a. m. +02:00 de philipvu30  notifications@github.com :

**Comment by philipvu30** [comment]
Hi,

It seems your consumer key and consumer secret are not correct. The app cannot load products without proper consumer key and secret key. Please refer to this [doc](https://docs.woocommerce.com/document/woocommerce-rest-api/) and replace them in config.dart file.

Thank you.

**Comment by informaticajovani** [comment]
hello, with yesterday's update it works.
The config.json is missing valid in wordpress
Also, I would like to filter the categories shown in the menus, is it documented?
Thank you
--
Informatica FerreteriaJovani.com viernes, 08 mayo 2020, 05:35a. m. +02:00 de philipvu30  notifications@github.com :

**Comment by philipvu30** [comment]
Hi,

What menus are you mentioning? Please include images with details. Thanks

**Comment by informaticajovani** [comment]
this menu. the side menu, and the menu of the home page located at the top, as well as its icons
Thanks
--
Informatica FerreteriaJovani.com viernes, 08 mayo 2020, 08:42a. m. +02:00 de philipvu30  notifications@github.com :

**Comment by informaticajovani** [comment]
This menu.
And when i change the default language to spanish, the home screen fail. Json is spected
Thanks 4 all
--
Informatica FerreteriaJovani.com viernes, 08 mayo 2020, 08:42a. m. +02:00 de philipvu30  notifications@github.com :

**Comment by informaticajovani** [comment]
Hi,
Some categories are duplicated in the side menu and in the second menu bar option.
The homepage are ok, the option_es.json are bad, replace by en, and now are ok
Thanks
--
Informatica FerreteriaJovani.com viernes, 08 mayo 2020, 08:42a. m. +02:00 de philipvu30  notifications@github.com :

**Comment by philipvu30** [comment]
Hi,

Sorry for the delayed response. Please check if the file's name is correct. It should be config_es.json and you need to copy the config_en.json to the config_es.json for it to work.

About the duplicated categories, it will be fixed in the next update. Thanks for using our product.

**Comment by informaticajovani** [comment]
Hello,
I solved the problem before your reply. From now on, I at least need to know what files are being changed.
regarding the json file, should any confirmation be shown in my woocomerce? I have carried out this action and did not see improvement.
on the other hand, when launching a webview, the menu and header of the store are displayed. to hide, is it better to control from flutter or wp?
I have to change the splash screen
Greetings
--
Informatica FerreteriaJovani.com lunes, 11 mayo 2020, 05:27a. m. +02:00 de philipvu30  notifications@github.com :

**Comment by philipvu30** [comment]
Hi,

1. Webview launch issue: Sorry. Currently, we don't have any solution for this situation.
2. Splash screen change: Please refer to this [doc](https://docs.rive.app/tutorials) and create your own custom flare with the .flr extension.
3. Sorry, I do not understand what you mean.

> regarding the json file, should any confirmation be shown in my woocomerce? I have carried out this action and did not see improvement.

**Comment by informaticajovani** [comment]
Hello,

In addition to the duplicates of the categories that I would like to 
resolve as soon as possible. I have this error when reading from the blog.

I would also like to remove the green color from the top of the app.

a greeting
