### ISSUE TITLE
[Fluxstore WooCommerce] Payment gateway

### ISSUE THREAD

**Issue by phcaraujo** [inspireui/support#3046]
You have several Brazilian customers, however, the vast majority do not use PayPal or Stripe.

The most used form of payment for online payments in Brazil is Mercado Pago.

Do you intend to integrate this payment gateway into the application?

**Comment by minhcasi** [comment]
@phcaraujo - the current WooCommerce is supported multi-payment gateway, it will work as the same on your website, please help to check the config `EnableOnePageCheckout` or `NativeOnePageCheckout` 

Let us know if you have any issues - thank you 👍

**Comment by danielito-1** [comment]
lo solucionaste?

**Comment by midasmkt** [comment]
Hola Danielito como estas? Pudiste resolver lo de mercado pago en la integración con la app?
