### ISSUE TITLE
Default category thumbnail

### ISSUE THREAD

**Issue by adnanmur** [inspireui/support#3047]
<img width="466" alt="Screenshot 2020-05-06 at 20 54 21" src="https://user-images.githubusercontent.com/55198169/81216788-c8eff400-8fdb-11ea-9360-d35d349419cc.png">

Can you please advise how to edit the default category thumbnails that appear here?

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ 

We will close this ticket as is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by adnanmur** [comment]
any feedback?

**Comment by philipvu30** [comment]
Hi,

Please modify them in config.dart

![image](https://user-images.githubusercontent.com/54442328/81378706-efc03e80-9131-11ea-9c58-900f41ab30d1.png)

**Comment by adnanmur** [comment]
That is not correct, the images that you are refering are travel images and i have them, what i am refering here are the thumbnails that default to category.

Thanks anyways.

**Comment by adnanmur** [comment]
any feedback here?

**Comment by minhcasi** [comment]
@adnanmur - it's the correct one - just try to map your ID to the kCategoryImages values, you could try to inspect by using Inspector Tools from Android Studio to navigate to the source code 😊

<img width="1447" alt="Screen Shot 2020-05-10 at 19 15 56" src="https://user-images.githubusercontent.com/1459805/81499036-aff48500-92f2-11ea-8884-4e7fda32d5a8.png">

**Comment by minhcasi** [comment]
Let us know if you have any question 😊
