### ISSUE TITLE
Issue Fluxstore when selecting language

### ISSUE THREAD

**Issue by PauloBrazilDHPP** [inspireui/support#3048]
Hi there

I am using 1.7.2 version of fluxstore and when i select BR language, the app crashes...

here is the screenshots and output from console

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
No MaterialLocalizations found.
The ancestors of this widget were: 
  : SliverAppBar
    dependencies: [TickerMode, MediaQuery]
    state: _SliverAppBarState#938d3
  : CustomScrollView
    scrollDirection: vertical
    primary: using primary controller
    AlwaysScrollableScrollPhysics
    dependencies: [PrimaryScrollController]
  : Scaffold
    dependencies: [MediaQuery, TickerMode, _InheritedTheme, _LocalizationsScope-[GlobalKey#3a29f], Directionality]
    state: ScaffoldState#b1699(tickers: tracking 2 tickers)
  : SettingScreen
    dependencies: [MediaQuery, TickerMode, _DefaultInheritedProviderScope<AppModel>, _InheritedTheme, _LocalizationsScope-[GlobalKey#3a29f], _DefaultInheritedProviderScope<UserModel>]
    state: SettingScreenState#b40de
  : Consumer<UserModel>
    dependencies: [_DefaultInheritedProviderScope<UserModel>]
  : ListenableProvider<UserModel>
    value: Instance of 'UserModel'
    listening to value
  : UserScreen
    dependencies: [_DefaultInheritedProviderScope<UserModel>]
    state: _UserScreenState#63d90
  : TabBarView
    state: _TabBarViewState#89bd8
  : WillPopScope
    dependencies: [_ModalScopeStatus]
    state: _WillPopScopeState#32501
  : Scaffold-[LabeledGlobalKey<ScaffoldState>#8697b]
    dependencies: [MediaQuery, TickerMode, _InheritedTheme, _LocalizationsScope-[GlobalKey#3a29f], Directionality]
    state: ScaffoldState#b0d22(tickers: tracking 2 tickers)
  : Container
    bg: BoxDecoration(color: Color(0xffffffff))
  : MainTabs
    dependencies: [_DefaultInheritedProviderScope<CartModel>, MediaQuery, TickerMode, _InheritedTheme, _LocalizationsScope-[GlobalKey#3a29f]]
    state: MainTabsState#fff4b(ticker inactive and muted)
  : MaterialApp
    state: _MaterialAppState#3192b
  : ChangeNotifierProvider<Ads>
    value: <not yet loaded>
  : ChangeNotifierProvider<BlogModel>
    value: Instance of 'BlogModel'
    listening to value
  : ChangeNotifierProvider<BlogModel>
    value: <not yet loaded>
  : ChangeNotifierProvider<CategoryModel>
    value: Instance of 'CategoryModel'
    listening to value
  : ChangeNotifierProvider<CartModel>
    value: Instance of 'CartModelWoo'
    listening to value
  : Provider<FilterTagModel>
    value: Instance of 'FilterTagModel'
  : Provider<FilterAttributeModel>
    value: Instance of 'FilterAttributeModel'
  : Provider<UserModel>
    value: Instance of 'UserModel'
  : Provider<RecentModel>
    value: Instance of 'RecentModel'
  : Provider<SearchModel>

![Captura de Tela 2020-05-06 às 16 29 49](https://user-images.githubusercontent.com/64207931/81219945-f1192c00-8fb6-11ea-9052-8a3d49f3a5ff.png)

![Captura de Tela 2020-05-06 às 16 29 37](https://user-images.githubusercontent.com/64207931/81219957-f4acb300-8fb6-11ea-87c5-1a4c13cd78d1.png)

i didnt made any changes on languages... can you help?

**Comment by minhcasi** [comment]
it's fix on latest source, please change the language file `br` to `pt` and from tools.dart https://tppr.me/BIGLc

We will update new release in 1-2 days, together with new Flutter 1.17 - thank you!
