### ISSUE TITLE
The Buy Now and Add to Cart buttons are disabled.

### ISSUE THREAD

**Issue by emmanueldamiancid** [inspireui/support#3049]
Step 1 (require): detail issues and screenshots

Good morning, I acquired the Fluxtore Pro application.
I am using it with Magento, but I have a problem when adding the product to the cart. The Buy Now and Add to Cart buttons are disabled.
The products have stock, are active and published but do not allow adding them.
However on the product list screen, I can add them to the cart from the cart button.

![ef89ca5d-c445-4f7b-b9c7-cfd747d89953](https://user-images.githubusercontent.com/38361142/81220203-8f50c600-8fa6-11ea-8db3-34bf16c576fd.jpg)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by sketchuprzr** [comment]
This issue has been resolved in versions 1.7.1 and 1.7.2. Please check for updates.

**Comment by emmanueldamiancid** [comment]
Hello, I already updated to the new version but now it sends me another error. Attached is the screenshot of the new error.
![scren](https://user-images.githubusercontent.com/38361142/81246796-1b321480-8fde-11ea-9e27-8335b489cd2d.png)

**Comment by minhcasi** [comment]
@emmanueldamiancid - we are going to release new 1.7.3 that compatible with the latest Flutter 1.17 - it will be ready in 1-2 days (also fix this issue) - thank you!

**Comment by emmanueldamiancid** [comment]
The update fixed the previous errors. Now I have another error when going to the shipping tab, it does not show me the shipping options and it does not allow me to continue to the review tab. I have the app configured with magneto.
![Screenshot_20200508_001122_com inspireui fluxstore](https://user-images.githubusercontent.com/38361142/81372720-abe12100-90c0-11ea-926b-6c180c4cb34a.jpg)
![Screenshot_20200508_001130_com inspireui fluxstore](https://user-images.githubusercontent.com/38361142/81372738-b56a8900-90c0-11ea-8f06-25c6c2eb6553.jpg)

**Comment by minhcasi** [comment]
@minhtruong315 - pls help to check this Magento issue - thank you!

**Comment by emmanueldamiancid** [comment]
Hello, I was able to solve the problem of shipping methods.
Now I have problems trying to finish the purchase.
When ordering, the screen keeps loading and the purchase does not finish.
![2f3f92d4-db42-49c0-b227-f6ff434e4dd5](https://user-images.githubusercontent.com/38361142/81476427-7f6bf880-91d7-11ea-9df0-9426243e400c.jpg)
![02f71149-18e7-4880-94e0-17122a05fa29](https://user-images.githubusercontent.com/38361142/81476430-8135bc00-91d7-11ea-9eba-bf11ed5fe220.jpg)

**Comment by minhcasi** [comment]
@emmanueldamiancid - could you help to trace the response from a server by using Android Studio to see if there is any detailed log?

**Comment by emmanueldamiancid** [comment]
E/SpannableStringBuilder( 5885): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
I/chatty  ( 5885): uid=10199(com.inspireui.fluxstore) identical 2 lines
E/SpannableStringBuilder( 5885): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
E/SpannableStringBuilder( 5885): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
E/SpannableStringBuilder( 5885): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
I/flutter ( 5885): [2020-05-10 04:05:53.812830Z][Fluxstore][tabbar] ============== tabbar.dart DASHBOARD ==============
I/flutter ( 5885): product.type simple
I/HwViewRootImpl( 5885): removeInvalidNode all the node in jank list is out of time
E/SpannableStringBuilder( 5885): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
E/SpannableStringBuilder( 5885): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
W/IInputConnectionWrapper( 5885): getExtractedText on inactive InputConnection
W/IInputConnectionWrapper( 5885): getTextBeforeCursor on inactive InputConnection
E/SpannableStringBuilder( 5885): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
I/chatty  ( 5885): uid=10199(com.inspireui.fluxstore) identical 2 lines
E/SpannableStringBuilder( 5885): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
E/SpannableStringBuilder( 5885): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
E/SpannableStringBuilder( 5885): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
W/IInputConnectionWrapper( 5885): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 5885): setComposingRegion on inactive InputConnection
W/IInputConnectionWrapper( 5885): endBatchEdit on inactive InputConnection
E/SpannableStringBuilder( 5885): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
I/chatty  ( 5885): uid=10199(com.inspireui.fluxstore) identical 2 lines
E/SpannableStringBuilder( 5885): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
E/SpannableStringBuilder( 5885): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
E/SpannableStringBuilder( 5885): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
E/SpannableStringBuilder( 5885): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
E/SpannableStringBuilder( 5885): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
E/SpannableStringBuilder( 5885): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
E/SpannableStringBuilder( 5885): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
W/IInputConnectionWrapper( 5885): getExtractedText on inactive InputConnection
W/IInputConnectionWrapper( 5885): getTextBeforeCursor on inactive InputConnection
I/flutter ( 5885): [2020-05-10 04:06:13.324481Z][Fluxstore][tabbar] ============== tabbar.dart DASHBOARD ==============
I/flutter ( 5885): product.type simple
V/AudioManager( 5885): querySoundEffectsEnabled...
I/flutter ( 5885): shippingMethods Free Shipping
I/flutter ( 5885): shippingMethods Envio Fijo
I/flutter ( 5885): [2020-05-10 04:06:16.650344Z][Fluxstore][tabbar] ============== tabbar.dart DASHBOARD ==============
I/flutter ( 5885): product.type simple
I/flutter ( 5885): shippingMethods Free Shipping
I/flutter ( 5885): shippingMethods Envio Fijo
V/AudioManager( 5885): querySoundEffectsEnabled...
I/flutter ( 5885): Product { id: 17 name: VIT.CHICLE CELOFAN4P SURT.6/300 }
I/flutter ( 5885): Product { id: 17 name: VIT.CHICLE CELOFAN4P SURT.6/300 }
V/AudioManager( 5885): querySoundEffectsEnabled...
V/AudioManager( 5885): querySoundEffectsEnabled...
I/flutter ( 5885): screenName null
I/flutter ( 5885): product.type simple

**Comment by minhtruong315** [comment]
@emmanueldamiancid what is the Fluxstore version you're using?

**Comment by emmanueldamiancid** [comment]
Hi, 1.7.3

**Comment by minhtruong315** [comment]
can u upload your source code to git repo then add my email: minhtruong315@gmail.com?
I'll help u check and fix on it
Thanks

**Comment by emmanueldamiancid** [comment]
Hello, I already added you to the repository. Thank you

**Comment by minhtruong315** [comment]
> Hello, I already updated to the new version but now it sends me another error. Attached is the screenshot of the new error.
> ![scren](https://user-images.githubusercontent.com/38361142/81246796-1b321480-8fde-11ea-9e27-8335b489cd2d.png)

<img width="413" alt="Screen Shot 2020-05-13 at 10 13 25 PM" src="https://user-images.githubusercontent.com/10402500/81830997-010caf00-9567-11ea-804b-6f9ed984aa79.png">
I checked your source code, it's working well

**Comment by emmanueldamiancid** [comment]
Hello, the problem is that it does not let you finish the purchase.
The screen freezes with the loading logo.
And the purchase does not finish

**Comment by minhtruong315** [comment]
> Hello, I was able to solve the problem of shipping methods.
> Now I have problems trying to finish the purchase.
> When ordering, the screen keeps loading and the purchase does not finish.
> ![2f3f92d4-db42-49c0-b227-f6ff434e4dd5](https://user-images.githubusercontent.com/38361142/81476427-7f6bf880-91d7-11ea-9df0-9426243e400c.jpg)
> ![02f71149-18e7-4880-94e0-17122a05fa29](https://user-images.githubusercontent.com/38361142/81476430-8135bc00-91d7-11ea-9eba-bf11ed5fe220.jpg)

fixed on your source code. pls pull updates.

**Comment by emmanueldamiancid** [comment]
Hello I have some details with the application.
1.- The "hideOutOfStock" variable is set to true. And even so, it shows the products that are out of stock.

2. When trying to make the payment with Paypal the message appears: Invalid argument (s). It is already configured in magento and in the app with the clientId and secret keys.
3.- There is an error when buying a product. If you do not finish the purchase and empty the cart, when you select the same product, although the cart appears with the quantity you are currently selecting, when generating the order, add the previous products.
Example: I select 3 products and I don't finish the purchase, I empty the cart.
I select 3 products again, I finish the purchase with the cart in 3. But at the time of reviewing the order, it generates it with 6 products, even though I only select 3.

I wait for your answer, since I already have to upload the application to the playstore to start using it.
I appreciate your help
