### ISSUE TITLE
Can not confirm order on real device

### ISSUE THREAD

**Issue by samber91** [inspireui/support#305]
purchase code ad1ac976-3e34-4e40-a473-0985df712891

Mstore is working on the simulator. but not on a real phone, it wont let you place your order. I need it fixed urgently please. 
Here are the files
![img_8964](https://user-images.githubusercontent.com/42559522/52837499-f68e0c00-30bc-11e9-8307-4cf900712533.JPG)
Config.js   ---------  https://drive.google.com/open?id=1U7KmsUQChljG0PTX-R-6YtIPfEkv6Rjn
thanks

**Comment by samber91** [comment]
TRY IT ON REAL DEVICES (ANDROID AND IPHONE) AND FIX THE ISSUE PLEASE. THANKS

**Comment by minhcasi** [comment]
@samber91  could you consider updating the rating? The is no reason for us to get your bad rating and continues to support, thanks
