### ISSUE TITLE
In Checkout,After Click " Place my Order"  Button ,not show loading any and very long  to checkout 

### ISSUE THREAD

**Issue by zawwinhtunn** [inspireui/support#3050]
hello please help  me.In checkout ,after click " place my order"  button, not show any loading and very long to checkout success.I sent screen video error and purchased screen shot . please check my issue and fix .thank you so much for your kindness.

This is my screen video error.
http://tobismart.ru/checkout-video-error/

This is my purchased screen shot 
https://github.com/zawwinhtunn/multiflutter/blob/master/purchase.PNG

**Comment by sketchuprzr** [comment]
What you mean is;

Do you want something like this?

![waiting2](https://user-images.githubusercontent.com/60021696/81242707-80096100-9016-11ea-9baa-217c2ed3f04f.gif)

**Comment by zawwinhtunn** [comment]
Yes sir. Like this but want  loading time not too slow

**Comment by sketchuprzr** [comment]
> Yes sir. Like this but want loading time not too slow

implementation is not slow in this regard. There are several reasons for this to be slow;
for example;

slow web hosting
slow system of your website
dozens of order requests at the same time
etc..

**Comment by sketchuprzr** [comment]
I reported the loading screen to fluxstore. I hope they implement a "loading" screen like I did recently or similar.

**Comment by zawwinhtunn** [comment]
Yes sir. So please fix with loading circle after click place order like this

**Comment by zawwinhtunn** [comment]
I brought  fluxstore with multivendor sir

**Comment by minhcasi** [comment]
@zawwinhtunn - Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ 

We will close this ticket as is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
@zawwinhtunn - the new release will be updated in 1-2 days with the latest Flutter 1.17 compatible - thank you!

**Comment by zawwinhtunn** [comment]
hello sir I have been sent private ticket.please check me.

**Comment by minhcasi** [comment]
@zawwinhtunn - we have fixed this issue on latest 1.7.3 - detail changelog https://medium.com/@inspireui/announcing-fluxstore-1-7-x-9a636c5468e8

Make sure you update to the latest Flutter 1.17 - thank you!
