### ISSUE TITLE
[FluxStore WooCommerce] Issue on FluxStore payment - wrong order status 

### ISSUE THREAD

**Issue by PauloBrazilDHPP** [inspireui/support#3051]
Hi there

On woocommerce, after a payment order is confirmed, the status is "Processing", but when an order is made by the app, on woocommerce it comes as "Completed".

Here is the screenshots

![Captura de Tela 2020-05-06 às 16 47 02](https://user-images.githubusercontent.com/64207931/81221471-435b4c80-8fb9-11ea-90d2-2d6175211dae.png)
![Captura de Tela 2020-05-06 às 16 45 52](https://user-images.githubusercontent.com/64207931/81221482-46563d00-8fb9-11ea-8e85-2a334ac3ac78.png)

Can you help with this issue?

**Comment by minhcasi** [comment]
@PauloBrazilDHPP - sorry please explain more as i see the status is shown correctly both mobile app and web, do you mean the order number 2870? Thank you!

**Comment by siyashamsudeen** [comment]
i have the same issue mentioned here - https://github.com/inspireui/support/issues/3063

It means when an order is placed from WooCommerce Website Directly , the order status changes to "Processing" . 

But when order is placed from the App then order status is getting changed to " Completed " . instead of " Processing " .

**Comment by PauloBrazilDHPP** [comment]
Sorry but I didn’t understood… I must buy an extended license?

I already bought the license and I am using in just one site… I didn’t understood the real problem

**Comment by minhcasi** [comment]
@PauloBrazilDHPP - you could share your admin account to support@inspireui.com - we will help to investigate this `status` issue, it could cause by your missing setting from the WooCommerce - thank you!

**Comment by PauloBrazilDHPP** [comment]
I sent admin account on email as requested... now waiting for a solution :)

**Comment by philipvu30** [comment]
Hi,

Please navigate to lib/models/order/order.dart and change this from completed to processing

![image](https://user-images.githubusercontent.com/54442328/81545958-dfaf9580-93a3-11ea-89df-707d931165e0.png)

**Comment by PauloBrazilDHPP** [comment]
I will test, and let you know if now is OK...
and about the shipping issue? Any solution?

**Comment by PauloBrazilDHPP** [comment]
I made the change as you told and we have another issue... when completing the order, i choose paypal as payment method... i logged with a sandbox account and it keeps asking me the adress... i update adress and it ask again... 
after some attempts, it come back to the screen ask to choose payment method.
![Captura de Tela 2020-05-11 às 08 52 43](https://user-images.githubusercontent.com/64207931/81558868-cf2bfa80-9364-11ea-8b93-f0667487c43d.png)
![Captura de Tela 2020-05-11 às 08 48 11](https://user-images.githubusercontent.com/64207931/81558878-d2bf8180-9364-11ea-872a-217ca92f87ee.png)

here is the output on console

flutter: [2020-05-11 11:49:52.651100Z][Fluxstore][tabbar] ============== tabbar.dart DASHBOARD ==============
flutter: product.type variable
flutter: Product { id: 2682 name: Pashmina }
flutter: Product { id: 2682 name: Pashmina }
flutter: product.type variable
flutter: fetchProductsByCategory: products?status=publish&lang=pt&per_page=20&page=1&category=85
flutter: url https://tricodavoxiloca.com.br//wp-json/wc/v2/products?status=publish&lang=pt&per_page=20&page=1&category=85
flutter: [2020-05-11 11:49:53.150469Z][Fluxstore][wocommerce_api][08:49:53.150328] getAsync START [endPoint:products?status=publish&lang=pt&per_page=20&page=1&category=85] url:https://tricodavoxiloca.com.br//wp-json/wc/v2/products?status=publish&lang=pt&per_page=20&page=1&category=85&consumer_key=ck_35383adf2739783b413f80ae92c83ff5452cf09f&consumer_secret=cs_709beb73059982bbf46555087a6f6e3cfd52d44c
flutter: [2020-05-11 11:49:55.576209Z][Fluxstore][wocommerce_api][08:49:55.575967] getAsync END [endPoint:products?status=publish&lang=pt&per_page=20&page=1&category=85] url:products?status=publish&lang=pt&per_page=20&page=1&category=85
flutter: [2020-05-11 11:50:00.790455Z][Fluxstore][tabbar] ============== tabbar.dart DASHBOARD ==============
flutter: product.type variable
flutter: Product { id: 2682 name: Pashmina }
flutter: Product { id: 2682 name: Pashmina }
flutter: product.type variable
flutter: fetchProductsByCategory: products?status=publish&lang=pt&per_page=20&page=1&category=85
flutter: url https://tricodavoxiloca.com.br//wp-json/wc/v2/products?status=publish&lang=pt&per_page=20&page=1&category=85
flutter: [2020-05-11 11:50:01.212328Z][Fluxstore][wocommerce_api][08:50:01.209948] getAsync START [endPoint:products?status=publish&lang=pt&per_page=20&page=1&category=85] url:https://tricodavoxiloca.com.br//wp-json/wc/v2/products?status=publish&lang=pt&per_page=20&page=1&category=85&consumer_key=ck_35383adf2739783b413f80ae92c83ff5452cf09f&consumer_secret=cs_709beb73059982bbf46555087a6f6e3cfd52d44c
flutter: [2020-05-11 11:50:01.409326Z][Fluxstore][tabbar] ============== tabbar.dart DASHBOARD ==============
flutter: product.type variable
flutter: Product { id: 2682 name: Pashmina }
flutter: Product { id: 2682 name: Pashmina }
flutter: product.type variable
flutter: fetchProductsByCategory: products?status=publish&lang=pt&per_page=20&page=1&category=85
flutter: url https://tricodavoxiloca.com.br//wp-json/wc/v2/products?status=publish&lang=pt&per_page=20&page=1&category=85
flutter: [2020-05-11 11:50:01.610496Z][Fluxstore][wocommerce_api][08:50:01.609277] getAsync START [endPoint:products?status=publish&lang=pt&per_page=20&page=1&category=85] url:https://tricodavoxiloca.com.br//wp-json/wc/v2/products?status=publish&lang=pt&per_page=20&page=1&category=85&consumer_key=ck_35383adf2739783b413f80ae92c83ff5452cf09f&consumer_secret=cs_709beb73059982bbf46555087a6f6e3cfd52d44c
flutter: [2020-05-11 11:50:02.072014Z][Fluxstore][tabbar] ============== tabbar.dart DASHBOARD ==============
flutter: product.type variable
flutter: Product { id: 2682 name: Pashmina }
flutter: Product { id: 2682 name: Pashmina }
flutter: product.type variable
flutter: fetchProductsByCategory: products?status=publish&lang=pt&per_page=20&page=1&category=85
flutter: url https://tricodavoxiloca.com.br//wp-json/wc/v2/products?status=publish&lang=pt&per_page=20&page=1&category=85
flutter: [2020-05-11 11:50:02.503223Z][Fluxstore][wocommerce_api][08:50:02.503154] getAsync START [endPoint:products?status=publish&lang=pt&per_page=20&page=1&category=85] url:https://tricodavoxiloca.com.br//wp-json/wc/v2/products?status=publish&lang=pt&per_page=20&page=1&category=85&consumer_key=ck_35383adf2739783b413f80ae92c83ff5452cf09f&consumer_secret=cs_709beb73059982bbf46555087a6f6e3cfd52d44c
flutter: [2020-05-11 11:50:04.532253Z][Fluxstore][wocommerce_api][08:50:04.532044] getAsync END [endPoint:products?status=publish&lang=pt&per_page=20&page=1&category=85] url:products?status=publish&lang=pt&per_page=20&page=1&category=85
flutter: [2020-05-11 11:50:05.250203Z][Fluxstore][wocommerce_api][08:50:05.250048] getAsync END [endPoint:products?status=publish&lang=pt&per_page=20&page=1&category=85] url:products?status=publish&lang=pt&per_page=20&page=1&category=85
flutter: [2020-05-11 11:50:05.345147Z][Fluxstore][wocommerce_api][08:50:05.345032] getAsync END [endPoint:products?status=publish&lang=pt&per_page=20&page=1&category=85] url:products?status=publish&lang=pt&per_page=20&page=1&category=85
flutter: [2020-05-11 11:50:22.582676Z][Fluxstore][tabbar] ============== tabbar.dart DASHBOARD ==============
flutter: product.type variable
flutter: Product { id: 2682 name: Pashmina }
flutter: Product { id: 2682 name: Pashmina }
flutter: product.type variable
flutter: fetchProductsByCategory: products?status=publish&lang=pt&per_page=20&page=1&category=85
flutter: url https://tricodavoxiloca.com.br//wp-json/wc/v2/products?status=publish&lang=pt&per_page=20&page=1&category=85
flutter: [2020-05-11 11:50:23.024532Z][Fluxstore][wocommerce_api][08:50:23.024449] getAsync START [endPoint:products?status=publish&lang=pt&per_page=20&page=1&category=85] url:https://tricodavoxiloca.com.br//wp-json/wc/v2/products?status=publish&lang=pt&per_page=20&page=1&category=85&consumer_key=ck_35383adf2739783b413f80ae92c83ff5452cf09f&consumer_secret=cs_709beb73059982bbf46555087a6f6e3cfd52d44c
flutter: [2020-05-11 11:50:25.014969Z][Fluxstore][wocommerce_api][08:50:25.014794] getAsync END [endPoint:products?status=publish&lang=pt&per_page=20&page=1&category=85] url:products?status=publish&lang=pt&per_page=20&page=1&category=85
flutter: screenName null

**Comment by siyashamsudeen** [comment]
i have the same same issue in the new version . 

After payment it comes back to the same checkout screen too choose the payment method . Even for successful payment this happens. 

Same error : Screen Null 
Comes

**Comment by philipvu30** [comment]
Hi all,

@PauloBrazilDHPP Please check your Paypal information if it is correct since I don't have any trouble ordering with Paypal.
@siyashamsudeen The checkout screen issue has been fixed and will be included in the next update.

**Comment by PauloBrazilDHPP** [comment]
i have the same issue @siyashamsudeen have... but i must relase app to production this week.
can you tell me the step by step to fix it?
And how about my issue on shipping?

**Comment by philipvu30** [comment]
Hi @PauloBrazilDHPP  @siyashamsudeen ,

Please replace this file in lib/screens/checkout/payment.dart

[payment.dart.zip](https://github.com/inspireui/support/files/4621729/payment.dart.zip)

**Comment by PauloBrazilDHPP** [comment]
Hi, i did that and it gives another error... here is the console

Compiler message:
lib/screens/checkout/payment.dart:344:7: Error: No named parameter with the name 'onLoading'.
      onLoading: widget.onLoading,
      ^^^^^^^^^

You added a parameter on a function but have more dependencies to update...
can you send me all files that is needed? And when the update will be released?

I am running out o f time... this friday is the release date for me...

**Comment by siyashamsudeen** [comment]
Im getting the same error after replacing the file. 

<img width="703" alt="Screen Shot 2020-05-14 at 12 32 40 AM" src="https://user-images.githubusercontent.com/57159602/81862259-7f268100-957a-11ea-8f39-8fea816768bb.png">


Also now in the 1.7.3 Version 

for Cash On Delivery Option : The Order status changes to Pending - but its suppose to be " Processing "

1.7.4 Pre Release - The Code has errors and if we comment it then it gives build error

<img width="1069" alt="Screen Shot 2020-05-13 at 10 40 34 PM" src="https://user-images.githubusercontent.com/57159602/81862499-de849100-957a-11ea-8fb1-1aeeedeec394.png">
<img width="1418" alt="Screen Shot 2020-05-13 at 10 50 56 PM" src="https://user-images.githubusercontent.com/57159602/81862508-e17f8180-957a-11ea-9ed7-13985bc25152.png">
<img width="848" alt="Screen Shot 2020-05-13 at 10 51 09 PM" src="https://user-images.githubusercontent.com/57159602/81862509-e2b0ae80-957a-11ea-8616-4dfe090eb7d0.png">

**Comment by philipvu30** [comment]
Hi,

Please pull our latest version on our GitLab repository then replace this file. 

I'm sorry for this inconvenience.

**Comment by siyashamsudeen** [comment]
Latest version is only having the above build error ? You mean the Pre Release 1.7.4 version right ?

**Comment by philipvu30** [comment]
Hi @siyashamsudeen 

Please delete that function. Or just delete that line of error. It has no impact on the main code.

**Comment by siyashamsudeen** [comment]
Yes i commented out that line after that i started getting the build error .

**Comment by philipvu30** [comment]
@siyashamsudeen 
Have you run pod repo update?

**Comment by siyashamsudeen** [comment]
Thanks I run and it helped to build the code . 

But there are more bugs on this version and old issue still persists :

**1. For Declined TAP Payments - Order gets created successfully ( Old Issue ).**
For eg if you give wrong card information also order will get created successfully . 

**2. For Cash On Delivery Payments – It creates order with Order Status : ” Pending ” it is suppose to be ” Processing “ ( Version 1.7.2 and previous version this works perfectly )**

**3. When we go to checkout screen it asks for Login and after logged in, when i click check out again login box appears .**
after we go to home and click cart and check out again then it works .

but directly after login it doesn't go to checkout or when we click checkout button it doesn't work .

Please find the screen video for the above to reproduce the error:

https://www.dropbox.com/s/awwsp0eb56vhp74/IMG_3108.MOV?dl=0

The below are the console log received:

flutter: screenName null
flutter: screenName null

════════ (13) Exception caught by gesture ══════════════════════════════════════════════════════════
ExpandingBottomSheet.of() called with a context that does not contain a ExpandingBottomSheet.
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by PauloBrazilDHPP** [comment]
Hi
I made all the changes and the issue is still there... the payment is made succesfully but the next screen didnt come... 

here goes the screenshot and console output

I really need a solution... this issue is open has too many days... when will you solve it?

![Captura de Tela 2020-05-14 às 17 28 23](https://user-images.githubusercontent.com/64207931/81982525-5947bd80-9608-11ea-9158-806ef901f346.png)


Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x600000ee0500 UIButtonLabel:0x7fac153a4d30'Done'.centerY == _UIModernBarButton:0x7fac1179ef70'Done'.centerY + 0.5   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
flutter: [2020-05-14 20:27:42.790791Z][Fluxstore][tabbar] ============== tabbar.dart DASHBOARD ==============
flutter: [2020-05-14 20:27:42.808276Z][Fluxstore][tabbar] ============== tabbar.dart DASHBOARD ==============
flutter: product.type variable
flutter: Product { id: 2739 name: Sapatinho para Bebê em Crochê }
flutter: Product { id: 2739 name: Sapatinho para Bebê em Crochê }
flutter: product.type variable
flutter: fetchProductsByCategory: products?status=publish&lang=pt&per_page=20&page=1&category=77
flutter: url https://tricodavoxiloca.com.br//wp-json/wc/v2/products?status=publish&lang=pt&per_page=20&page=1&category=77
flutter: [2020-05-14 20:27:43.751723Z][Fluxstore][wocommerce_api][17:27:43.750255] getAsync START [endPoint:products?status=publish&lang=pt&per_page=20&page=1&category=77] url:https://tricodavoxiloca.com.br//wp-json/wc/v2/products?status=publish&lang=pt&per_page=20&page=1&category=77&consumer_key=ck_35383adf2739783b413f80ae92c83ff5452cf09f&consumer_secret=cs_709beb73059982bbf46555087a6f6e3cfd52d44c
flutter: [2020-05-14 20:27:47.168336Z][Fluxstore][wocommerce_api][17:27:47.168107] getAsync END [endPoint:products?status=publish&lang=pt&per_page=20&page=1&category=77] url:products?status=publish&lang=pt&per_page=20&page=1&category=77
flutter: [2020-05-14 20:27:50.908334Z][Fluxstore][tabbar] ============== tabbar.dart DASHBOARD ==============
flutter: [2020-05-14 20:27:50.982887Z][Fluxstore][tabbar] ============== tabbar.dart DASHBOARD ==============
flutter: product.type variable
flutter: Product { id: 2739 name: Sapatinho para Bebê em Crochê }
flutter: Product { id: 2739 name: Sapatinho para Bebê em Crochê }
flutter: product.type variable
flutter: fetchProductsByCategory: products?status=publish&lang=pt&per_page=20&page=1&category=77
flutter: url https://tricodavoxiloca.com.br//wp-json/wc/v2/products?status=publish&lang=pt&per_page=20&page=1&category=77
flutter: [2020-05-14 20:27:51.652416Z][Fluxstore][wocommerce_api][17:27:51.647909] getAsync START [endPoint:products?status=publish&lang=pt&per_page=20&page=1&category=77] url:https://tricodavoxiloca.com.br//wp-json/wc/v2/products?status=publish&lang=pt&per_page=20&page=1&category=77&consumer_key=ck_35383adf2739783b413f80ae92c83ff5452cf09f&consumer_secret=cs_709beb73059982bbf46555087a6f6e3cfd52d44c
flutter: [2020-05-14 20:27:53.243110Z][Fluxstore][tabbar] ============== tabbar.dart DASHBOARD ==============
flutter: [2020-05-14 20:27:53.269386Z][Fluxstore][tabbar] ============== tabbar.dart DASHBOARD ==============
flutter: product.type variable
flutter: Product { id: 2739 name: Sapatinho para Bebê em Crochê }
flutter: Product { id: 2739 name: Sapatinho para Bebê em Crochê }
flutter: product.type variable
flutter: fetchProductsByCategory: products?status=publish&lang=pt&per_page=20&page=1&category=77
flutter: url https://tricodavoxiloca.com.br//wp-json/wc/v2/products?status=publish&lang=pt&per_page=20&page=1&category=77
flutter: [2020-05-14 20:27:53.812952Z][Fluxstore][wocommerce_api][17:27:53.812878] getAsync START [endPoint:products?status=publish&lang=pt&per_page=20&page=1&category=77] url:https://tricodavoxiloca.com.br//wp-json/wc/v2/products?status=publish&lang=pt&per_page=20&page=1&category=77&consumer_key=ck_35383adf2739783b413f80ae92c83ff5452cf09f&consumer_secret=cs_709beb73059982bbf46555087a6f6e3cfd52d44c
flutter: [2020-05-14 20:27:53.971455Z][Fluxstore][wocommerce_api][17:27:53.971309] getAsync END [endPoint:products?status=publish&lang=pt&per_page=20&page=1&category=77] url:products?status=publish&lang=pt&per_page=20&page=1&category=77
flutter: [2020-05-14 20:27:56.010615Z][Fluxstore][wocommerce_api][17:27:56.010388] getAsync END [endPoint:products?status=publish&lang=pt&per_page=20&page=1&category=77] url:products?status=publish&lang=pt&per_page=20&page=1&category=77
flutter: [2020-05-14 20:28:01.169730Z][Fluxstore][tabbar] ============== tabbar.dart DASHBOARD ==============
flutter: [2020-05-14 20:28:01.238459Z][Fluxstore][tabbar] ============== tabbar.dart DASHBOARD ==============
flutter: product.type variable
flutter: Product { id: 2739 name: Sapatinho para Bebê em Crochê }
flutter: Product { id: 2739 name: Sapatinho para Bebê em Crochê }
flutter: product.type variable
flutter: fetchProductsByCategory: products?status=publish&lang=pt&per_page=20&page=1&category=77
flutter: url https://tricodavoxiloca.com.br//wp-json/wc/v2/products?status=publish&lang=pt&per_page=20&page=1&category=77
flutter: [2020-05-14 20:28:01.894999Z][Fluxstore][wocommerce_api][17:28:01.894930] getAsync START [endPoint:products?status=publish&lang=pt&per_page=20&page=1&category=77] url:https://tricodavoxiloca.com.br//wp-json/wc/v2/products?status=publish&lang=pt&per_page=20&page=1&category=77&consumer_key=ck_35383adf2739783b413f80ae92c83ff5452cf09f&consumer_secret=cs_709beb73059982bbf46555087a6f6e3cfd52d44c
flutter: [2020-05-14 20:28:04.208483Z][Fluxstore][wocommerce_api][17:28:04.207854] getAsync END [endPoint:products?status=publish&lang=pt&per_page=20&page=1&category=77] url:products?status=publish&lang=pt&per_page=20&page=1&category=77
flutter: [2020-05-14 20:28:05.325320Z][Fluxstore][tabbar] ============== tabbar.dart DASHBOARD ==============
flutter: [2020-05-14 20:28:05.361820Z][Fluxstore][tabbar] ============== tabbar.dart DASHBOARD ==============
flutter: product.type variable
flutter: Product { id: 2739 name: Sapatinho para Bebê em Crochê }
flutter: Product { id: 2739 name: Sapatinho para Bebê em Crochê }
flutter: product.type variable
flutter: fetchProductsByCategory: products?status=publish&lang=pt&per_page=20&page=1&category=77
flutter: url https://tricodavoxiloca.com.br//wp-json/wc/v2/products?status=publish&lang=pt&per_page=20&page=1&category=77
flutter: [2020-05-14 20:28:06.058637Z][Fluxstore][wocommerce_api][17:28:06.058566] getAsync START [endPoint:products?status=publish&lang=pt&per_page=20&page=1&category=77] url:https://tricodavoxiloca.com.br//wp-json/wc/v2/products?status=publish&lang=pt&per_page=20&page=1&category=77&consumer_key=ck_35383adf2739783b413f80ae92c83ff5452cf09f&consumer_secret=cs_709beb73059982bbf46555087a6f6e3cfd52d44c
flutter: [2020-05-14 20:28:07.612158Z][Fluxstore][tabbar] ============== tabbar.dart DASHBOARD ==============
flutter: [2020-05-14 20:28:07.646174Z][Fluxstore][tabbar] ============== tabbar.dart DASHBOARD ==============
flutter: product.type variable
flutter: Product { id: 2739 name: Sapatinho para Bebê em Crochê }
flutter: Product { id: 2739 name: Sapatinho para Bebê em Crochê }
flutter: product.type variable
flutter: fetchProductsByCategory: products?status=publish&lang=pt&per_page=20&page=1&category=77
flutter: url https://tricodavoxiloca.com.br//wp-json/wc/v2/products?status=publish&lang=pt&per_page=20&page=1&category=77
flutter: [2020-05-14 20:28:08.496889Z][Fluxstore][wocommerce_api][17:28:08.496824] getAsync START [endPoint:products?status=publish&lang=pt&per_page=20&page=1&category=77] url:https://tricodavoxiloca.com.br//wp-json/wc/v2/products?status=publish&lang=pt&per_page=20&page=1&category=77&consumer_key=ck_35383adf2739783b413f80ae92c83ff5452cf09f&consumer_secret=cs_709beb73059982bbf46555087a6f6e3cfd52d44c
flutter: [2020-05-14 20:28:08.665376Z][Fluxstore][wocommerce_api][17:28:08.665211] getAsync END [endPoint:products?status=publish&lang=pt&per_page=20&page=1&category=77] url:products?status=publish&lang=pt&per_page=20&page=1&category=77
flutter: [2020-05-14 20:28:10.753102Z][Fluxstore][wocommerce_api][17:28:10.752901] getAsync END [endPoint:products?status=publish&lang=pt&per_page=20&page=1&category=77] url:products?status=publish&lang=pt&per_page=20&page=1&category=77
flutter: screenName null
flutter: #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      WooWidget.createOrder (package:fstore/widgets/frameworks/woocommerce/index.dart:127:16)
#2      _PaymentMethodsState.createOrder (package:fstore/screens/checkout/payment.dart:340:29)
#3      _PaymentMethodsState.placeOrder.<anonymous closure>.<anonymous closure> (package:fstore/screens/checkout/payment.dart:294:19)
#4      PaypalPaymentState.build.<anonymous closure>.<anonymous closure> (package:fstore/widgets/payment/paypal/index.dart:158:34)
#5      _rootRunUnary (dart:async/zone.dart:1192:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#9      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#10     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#11     _AsyncAwaitCompleter.complete (dart:async-p<…>
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: Looking up a deactivated widget's ancestor is unsafe.
At this point the state of the widget's element tree is no longer stable.
To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.
#0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure> (package:flutter/src/widgets/framework.dart:3781:9)
#1      Element._debugCheckStateIsActiveForAncestorLookup (package:flutter/src/widgets/framework.dart:3795:6)
#2      Element.findAncestorStateOfType (package:flutter/src/widgets/framework.dart:3914:12)
#3      Navigator.of (package:flutter/src/widgets/navigator.dart:2115:19)
#4      PaypalPaymentState.build.<anonymous closure>.<anonymous closure> (package:fstore/widgets/payment/paypal/index.dart:159:29)
#5      _rootRunUnary (dart:async/zone.dart:1192:38)
#6      _CustomZone.runUnary (dart:async/zone.da<…>

**Comment by philipvu30** [comment]
Hi,

Send your project with the title "#3051" to this email: toan@inspireui.com.
I'll help you check if there is anything wrong with it.

**Comment by siyashamsudeen** [comment]
Hi, 

Can you help to check the issues i have mentioned above ? 

1. For Declined TAP Payments - Order gets created successfully ( Old Issue ).
For eg if you give wrong card information also order will get created successfully .

2. For Cash On Delivery Payments – It creates order with Order Status : ” Pending ” it is suppose to be ” Processing “ ( Version 1.7.2 and previous version this works perfectly )

3. When we go to checkout screen it asks for Login and after logged in, when i click check out again login box appears .
after we go to home and click cart and check out again then it works .

but directly after login it doesn't go to checkout or when we click checkout button it doesn't work .

Please find the screen video for the above to reproduce the error:

https://www.dropbox.com/s/awwsp0eb56vhp74/IMG_3108.MOV?dl=0

The below are the console log received:

flutter: screenName null
flutter: screenName null

════════ (13) Exception caught by gesture ══════════════════════════════════════════════════════════
ExpandingBottomSheet.of() called with a context that does not contain a ExpandingBottomSheet.
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by philipvu30** [comment]
Hi @siyashamsudeen 

1. We are finding a solution. Please be patient.
2. There is an attribute in lib/common/config/payments.dart called UpdateOrderStatus. Please set it to true.
3. Already fixed. In lib/screens/cart/my_cart.dart add this line
![image](https://user-images.githubusercontent.com/54442328/82034343-43013680-96c8-11ea-86c6-354d76236391.png)

**Comment by PauloBrazilDHPP** [comment]
I sent by email as you asked... waiting for your answer

**Comment by siyashamsudeen** [comment]
Dear Philip, 
Thanks for your update . im still waiting if you found a solution to check the issue 1 . 
Please help to fix.

**Comment by philipvu30** [comment]
Hi @PauloBrazilDHPP ,

My apologies for the delayed response. Would you mind sending me your testing Paypal account?
I couldn't test your project with mine.

**Comment by siyashamsudeen** [comment]
Hi @philipvu30 can you please help with the solution for TAP Payment issue. :(

Im really stuck with this :(

**Comment by PauloBrazilDHPP** [comment]
> Hi @PauloBrazilDHPP ,
> 
> My apologies for the delayed response. Would you mind sending me your testing Paypal account?
> I couldn't test your project with mine.
> 
> Also please check the test mode option for Paypal on your site. Thanks

here goes... the website is in sandbox mode

First Name:
John
Last Name:
Doe
Email ID:
sb-oxm9q1354484@business.example.com
System Generated Password:
oNd@48<_

api credentials

Username:
sb-oxm9q1354484_api1.business.example.com
Password:
KXBN5CQ9XGLP7UEE
Signature:
A465l9-Rt6uXpUdtcL-jr9JFlY49AKoOH67azYJBzwdgz5gM1GcI465t

**Comment by philipvu30** [comment]
Hi

It seems your client id and secret for the Paypal test account are not correct. I keep getting this error.
{"error":"invalid_client","error_description":"Client Authentication failed"}

Please check and send them to this email: toan@inspireui.com. Thank you

**Comment by PauloBrazilDHPP** [comment]
> toan@inspireui.com

Sent by email

**Comment by philipvu30** [comment]
@PauloBrazilDHPP 
No I meant the clientid and secretid of PaypalConfig in payments.dart

![image](https://user-images.githubusercontent.com/54442328/82396963-83223980-9a79-11ea-8390-7b19ebfc4057.png)

**Comment by PauloBrazilDHPP** [comment]
Here goes

const PaypalConfig = {
  "clientId":
      "AdLOymg-nzzcK4oFJPsFHAPdFc8NdSAdV-aCi8oy1Ta3kXcg_kvf2e4NT5Cs0HOw5fIJLfHyufi2vLPJ",
  "secret":
      "EIt9hu9cvYkAy3iTFKr0o0GiulvNzhYxVmasmTfddNYFuIz2iTZisXZeg8o62PBvORxncorpfg3S6o2r",
  "production": false,
  "paymentMethodId": "paypal",
  "enabled": true,
  "returnUrl": "http://return.example.com",
  "cancelUrl": "http://cancel.example.com",
};


But to test in sandbox, you can use the previous information I has sent to you

First Name:
John
Last Name:
Doe
Email ID:
sb-apxbj1837990@personal.example.com
System Generated Password:
Ew#0+4DL

**Comment by philipvu30** [comment]
Hi,

Everything seems fine to me. Here is the [result](https://drive.google.com/open?id=1RCAQX-ttK4qfbWKjKSKMi_k3RjWFYlXL), please watch it and give me confirmation.
Thank you.

**Comment by PauloBrazilDHPP** [comment]
I downloaded the version 1.7.4 and now it works. Thanks
