### ISSUE TITLE
Issue on Fluxstore Shipping

### ISSUE THREAD

**Issue by PauloBrazilDHPP** [inspireui/support#3052]
Hi there

My woocommerce site is configured for shipping with only one option, fixed tax... that have one value in one state here in brazil e another for the other states.

The app get only one value... i use on the order on app the state "São Paulo" that has 25 as chipping costs... but it comes 35 that is the shipping costs on another region.

Here is the screenshots and console output

flutter: product.type variable
flutter: Product { id: 2722 name: Gola Mesclada }
flutter: Product { id: 2722 name: Gola Mesclada }
flutter: 10
flutter: [2020-05-06 19:53:29.208938Z][Fluxstore][Home] build
flutter: [2020-05-06 19:53:29.241215Z][Fluxstore][Home] build
flutter: product.type variable
flutter: Product { id: 2722 name: Gola Mesclada }
flutter: 10
flutter: product.type variable
flutter: fetchProductsByCategory: products?status=publish&lang=en&per_page=20&page=1&category=91
flutter: [2020-05-06 19:53:29.366151Z][Fluxstore][wocommerce_api][16:53:29.366021] getAsync START [endPoint:products?status=publish&lang=en&per_page=20&page=1&category=91] url:https://tricodavoxiloca.com.br//wp-json/wc/v2/products?status=publish&lang=en&per_page=20&page=1&category=91&consumer_key=ck_35383adf2739783b413f80ae92c83ff5452cf09f&consumer_secret=cs_709beb73059982bbf46555087a6f6e3cfd52d44c
flutter: [2020-05-06 19:53:30.862948Z][Fluxstore][Cart] build
flutter: Product { id: 2722 name: Gola Mesclada }
flutter: [2020-05-06 19:53:30.991973Z][Fluxstore][wocommerce_api][16:53:30.991845] getAsync END [endPoint:coupons] url:coupons
flutter: [2020-05-06 19:53:31.702519Z][Fluxstore][wocommerce_api][16:53:31.702364] getAsync END [endPoint:products?status=publish&lang=en&per_page=20&page=1&category=91] url:products?status=publish&lang=en&per_page=20&page=1&category=91
flutter: [2020-05-06 19:53:32.622321Z][Fluxstore][wocommerce_api][16:53:32.622186] getAsync START [endPoint:shipping/zones] url:https://tricodavoxiloca.com.br//wp-json/wc/v2/shipping/zones?consumer_key=ck_35383adf2739783b413f80ae92c83ff5452cf09f&consumer_secret=cs_709beb73059982bbf46555087a6f6e3cfd52d44c
flutter: [2020-05-06 19:53:34.808198Z][Fluxstore][wocommerce_api][16:53:34.807825] getAsync END [endPoint:shipping/zones] url:shipping/zones
flutter: [2020-05-06 19:53:34.810394Z][Fluxstore][wocommerce_api][16:53:34.809634] getAsync START [endPoint:shipping/zones/0/methods] url:https://tricodavoxiloca.com.br//wp-json/wc/v2/shipping/zones/0/methods?consumer_key=ck_35383adf2739783b413f80ae92c83ff5452cf09f&consumer_secret=cs_709beb73059982bbf46555087a6f6e3cfd52d44c
flutter: [2020-05-06 19:53:36.908477Z][Fluxstore][wocommerce_api][16:53:36.908352] getAsync END [endPoint:shipping/zones/0/methods] url:shipping/zones/0/methods
flutter: [2020-05-06 19:53:36.909019Z][Fluxstore][wocommerce_api][16:53:36.908896] getAsync START [endPoint:shipping/zones/4/methods] url:https://tricodavoxiloca.com.br//wp-json/wc/v2/shipping/zones/4/methods?consumer_key=ck_35383adf2739783b413f80ae92c83ff5452cf09f&consumer_secret=cs_709beb73059982bbf46555087a6f6e3cfd52d44c
flutter: [2020-05-06 19:53:38.759672Z][Fluxstore][wocommerce_api][16:53:38.759490] getAsync END [endPoint:shipping/zones/4/methods] url:shipping/zones/4/methods
flutter: [2020-05-06 19:53:38.760929Z][Fluxstore][wocommerce_api][16:53:38.760802] getAsync START [endPoint:shipping/zones/4/locations] url:https://tricodavoxiloca.com.br//wp-json/wc/v2/shipping/zones/4/locations?consumer_key=ck_35383adf2739783b413f80ae92c83ff5452cf09f&consumer_secret=cs_709beb73059982bbf46555087a6f6e3cfd52d44c
flutter: [2020-05-06 19:53:40.621047Z][Fluxstore][wocommerce_api][16:53:40.620851] getAsync END [endPoint:shipping/zones/4/locations] url:shipping/zones/4/locations
flutter: [2020-05-06 19:53:40.625679Z][Fluxstore][wocommerce_api][16:53:40.625513] getAsync START [endPoint:shipping/zones/6/methods] url:https://tricodavoxiloca.com.br//wp-json/wc/v2/shipping/zones/6/methods?consumer_key=ck_35383adf2739783b413f80ae92c83ff5452cf09f&consumer_secret=cs_709beb73059982bbf46555087a6f6e3cfd52d44c
flutter: [2020-05-06 19:53:42.669665Z][Fluxstore][wocommerce_api][16:53:42.669361] getAsync END [endPoint:shipping/zones/6/methods] url:shipping/zones/6/methods
flutter: [2020-05-06 19:53:42.672668Z][Fluxstore][wocommerce_api][16:53:42.672508] getAsync START [endPoint:shipping/zones/6/locations] url:https://tricodavoxiloca.com.br//wp-json/wc/v2/shipping/zones/6/locations?consumer_key=ck_35383adf2739783b413f80ae92c83ff5452cf09f&consumer_secret=cs_709beb73059982bbf46555087a6f6e3cfd52d44c
flutter: [2020-05-06 19:53:44.565393Z][Fluxstore][wocommerce_api][16:53:44.565164] getAsync END [endPoint:shipping/zones/6/locations] url:shipping/zones/6/locations
flutter: [2020-05-06 19:53:48.169355Z][Fluxstore][wocommerce_api][16:53:48.162363] getAsync START [endPoint:shipping/zones] url:https://tricodavoxiloca.com.br//wp-json/wc/v2/shipping/zones?consumer_key=ck_35383adf2739783b413f80ae92c83ff5452cf09f&consumer_secret=cs_709beb73059982bbf46555087a6f6e3cfd52d44c
flutter: [2020-05-06 19:53:49.853872Z][Fluxstore][wocommerce_api][16:53:49.853717] getAsync END [endPoint:shipping/zones] url:shipping/zones
flutter: [2020-05-06 19:53:49.854503Z][Fluxstore][wocommerce_api][16:53:49.854397] getAsync START [endPoint:shipping/zones/0/methods] url:https://tricodavoxiloca.com.br//wp-json/wc/v2/shipping/zones/0/methods?consumer_key=ck_35383adf2739783b413f80ae92c83ff5452cf09f&consumer_secret=cs_709beb73059982bbf46555087a6f6e3cfd52d44c
flutter: [2020-05-06 19:53:52.500424Z][Fluxstore][wocommerce_api][16:53:52.500245] getAsync END [endPoint:shipping/zones/0/methods] url:shipping/zones/0/methods
flutter: [2020-05-06 19:53:52.501103Z][Fluxstore][wocommerce_api][16:53:52.500961] getAsync START [endPoint:shipping/zones/4/methods] url:https://tricodavoxiloca.com.br//wp-json/wc/v2/shipping/zones/4/methods?consumer_key=ck_35383adf2739783b413f80ae92c83ff5452cf09f&consumer_secret=cs_709beb73059982bbf46555087a6f6e3cfd52d44c
flutter: [2020-05-06 19:53:54.114869Z][Fluxstore][wocommerce_api][16:53:54.114761] getAsync END [endPoint:shipping/zones/4/methods] url:shipping/zones/4/methods
flutter: [2020-05-06 19:53:54.115552Z][Fluxstore][wocommerce_api][16:53:54.115464] getAsync START [endPoint:shipping/zones/4/locations] url:https://tricodavoxiloca.com.br//wp-json/wc/v2/shipping/zones/4/locations?consumer_key=ck_35383adf2739783b413f80ae92c83ff5452cf09f&consumer_secret=cs_709beb73059982bbf46555087a6f6e3cfd52d44c
flutter: [2020-05-06 19:53:56.085433Z][Fluxstore][wocommerce_api][16:53:56.085242] getAsync END [endPoint:shipping/zones/4/locations] url:shipping/zones/4/locations
flutter: [2020-05-06 19:53:56.087165Z][Fluxstore][wocommerce_api][16:53:56.087001] getAsync START [endPoint:shipping/zones/6/methods] url:https://tricodavoxiloca.com.br//wp-json/wc/v2/shipping/zones/6/methods?consumer_key=ck_35383adf2739783b413f80ae92c83ff5452cf09f&consumer_secret=cs_709beb73059982bbf46555087a6f6e3cfd52d44c
flutter: [2020-05-06 19:53:58.003108Z][Fluxstore][wocommerce_api][16:53:58.002987] getAsync END [endPoint:shipping/zones/6/methods] url:shipping/zones/6/methods
flutter: [2020-05-06 19:53:58.003874Z][Fluxstore][wocommerce_api][16:53:58.003761] getAsync START [endPoint:shipping/zones/6/locations] url:https://tricodavoxiloca.com.br//wp-json/wc/v2/shipping/zones/6/locations?consumer_key=ck_35383adf2739783b413f80ae92c83ff5452cf09f&consumer_secret=cs_709beb73059982bbf46555087a6f6e3cfd52d44c
flutter: [2020-05-06 19:54:00.078804Z][Fluxstore][wocommerce_api][16:54:00.078616] getAsync END [endPoint:shipping/zones/6/locations] url:shipping/zones/6/locations
flutter: shippingMethods Taxa fixa
flutter: [2020-05-06 19:54:52.194672Z][Fluxstore][wocommerce_api][16:54:52.194405] getAsync START [endPoint:shipping/zones] url:https://tricodavoxiloca.com.br//wp-json/wc/v2/shipping/zones?consumer_key=ck_35383adf2739783b413f80ae92c83ff5452cf09f&consumer_secret=cs_709beb73059982bbf46555087a6f6e3cfd52d44c
flutter: [2020-05-06 19:54:54.657431Z][Fluxstore][wocommerce_api][16:54:54.657241] getAsync END [endPoint:shipping/zones] url:shipping/zones
flutter: [2020-05-06 19:54:54.658201Z][Fluxstore][wocommerce_api][16:54:54.658056] getAsync START [endPoint:shipping/zones/0/methods] url:https://tricodavoxiloca.com.br//wp-json/wc/v2/shipping/zones/0/methods?consumer_key=ck_35383adf2739783b413f80ae92c83ff5452cf09f&consumer_secret=cs_709beb73059982bbf46555087a6f6e3cfd52d44c
flutter: [2020-05-06 19:54:56.297225Z][Fluxstore][wocommerce_api][16:54:56.297034] getAsync END [endPoint:shipping/zones/0/methods] url:shipping/zones/0/methods
flutter: [2020-05-06 19:54:56.297904Z][Fluxstore][wocommerce_api][16:54:56.297750] getAsync START [endPoint:shipping/zones/4/methods] url:https://tricodavoxiloca.com.br//wp-json/wc/v2/shipping/zones/4/methods?consumer_key=ck_35383adf2739783b413f80ae92c83ff5452cf09f&consumer_secret=cs_709beb73059982bbf46555087a6f6e3cfd52d44c
flutter: [2020-05-06 19:54:58.054462Z][Fluxstore][wocommerce_api][16:54:58.054287] getAsync END [endPoint:shipping/zones/4/methods] url:shipping/zones/4/methods
flutter: [2020-05-06 19:54:58.055810Z][Fluxstore][wocommerce_api][16:54:58.055664] getAsync START [endPoint:shipping/zones/4/locations] url:https://tricodavoxiloca.com.br//wp-json/wc/v2/shipping/zones/4/locations?consumer_key=ck_35383adf2739783b413f80ae92c83ff5452cf09f&consumer_secret=cs_709beb73059982bbf46555087a6f6e3cfd52d44c
flutter: [2020-05-06 19:54:59.470047Z][Fluxstore][wocommerce_api][16:54:59.469814] getAsync END [endPoint:shipping/zones/4/locations] url:shipping/zones/4/locations
flutter: [2020-05-06 19:54:59.472221Z][Fluxstore][wocommerce_api][16:54:59.472002] getAsync START [endPoint:shipping/zones/6/methods] url:https://tricodavoxiloca.com.br//wp-json/wc/v2/shipping/zones/6/methods?consumer_key=ck_35383adf2739783b413f80ae92c83ff5452cf09f&consumer_secret=cs_709beb73059982bbf46555087a6f6e3cfd52d44c
flutter: [2020-05-06 19:55:01.009395Z][Fluxstore][wocommerce_api][16:55:01.009089] getAsync END [endPoint:shipping/zones/6/methods] url:shipping/zones/6/methods
flutter: [2020-05-06 19:55:01.012096Z][Fluxstore][wocommerce_api][16:55:01.011884] getAsync START [endPoint:shipping/zones/6/locations] url:https://tricodavoxiloca.com.br//wp-json/wc/v2/shipping/zones/6/locations?consumer_key=ck_35383adf2739783b413f80ae92c83ff5452cf09f&consumer_secret=cs_709beb73059982bbf46555087a6f6e3cfd52d44c
flutter: [2020-05-06 19:55:02.955679Z][Fluxstore][wocommerce_api][16:55:02.955544] getAsync END [endPoint:shipping/zones/6/locations] url:shipping/zones/6/locations
flutter: shippingMethods Taxa fixa

![Captura de Tela 2020-05-06 às 16 55 06](https://user-images.githubusercontent.com/64207931/81222376-9255b180-8fba-11ea-9f41-8aa415696b56.png)
![Captura de Tela 2020-05-06 às 16 54 58](https://user-images.githubusercontent.com/64207931/81222383-95e93880-8fba-11ea-8d9c-4dd7559de1d0.png)
![Captura de Tela 2020-05-06 às 16 51 51](https://user-images.githubusercontent.com/64207931/81222387-9681cf00-8fba-11ea-9b74-0675e257d3ff.png)

can you help on this issue?

**Comment by minhcasi** [comment]
@PauloBrazilDHPP - thank you for reporting, please help us to raise your all issue to one ticket that i could assign for one member to check the issue - pls help to move this issue to #3051

Could you help to share the account admin to support@inspireui.com - we need to check your shipping setting - thank you!

**Comment by PauloBrazilDHPP** [comment]
Hi

Here go the information

User: daniloguedes@dhppsolucoes.com <mailto:daniloguedes@dhppsolucoes.com>
Password: vaginashow#69
