### ISSUE TITLE
TypeError: categories.forEach is not a function.

### ISSUE THREAD

**Issue by spetsglaz** [inspireui/support#3054]
Step 1 (require): detail issues and screenshots

Hello! i’ve tried to open the project but when i do this shows up, 

![image](https://user-images.githubusercontent.com/62562826/81233647-5e4cb180-8ff7-11ea-8790-29ea7c58f67f.jpg)

what am i doing wrong? i’ve tried to replace the config file with the one provided in mstore-1.0.0/examples/mstore, also tried the one in mstore-master/examples/mstore

but this shows up

![image](https://user-images.githubusercontent.com/62562826/81233494-0ada6380-8ff7-11ea-9e26-0d7dec4ed0e9.jpg)

Thank you for your help :)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here) 
ec7f9b1c-0996-4c71-8a53-1bd4f2159511

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhcasi** [comment]
@spetsglaz - sorry the verify purchase is invalid

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ 

We will close this ticket as is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!
