### ISSUE TITLE
1.7-2 Spanish special characters

### ISSUE THREAD

**Issue by samik9** [inspireui/support#3055]
Hello guys, my app is in Spanish I am using external .json config file, and I got this weird result.

![config json 2020-05-06 17-28-56](https://user-images.githubusercontent.com/50071744/81234986-891b1380-8fbf-11ea-9e16-42ada381fbd1.png)

**Comment by minhcasi** [comment]
Thank you for the feedback - pls post your all issues & question to One ticket, also help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ - thank you for your time!

**Comment by minhcasi** [comment]
#3013
