### ISSUE TITLE
Home banners does not show content  1.7-2

### ISSUE THREAD

**Issue by samik9** [inspireui/support#3056]
Hello team, I noticed that home sliders doesn´t load any category , I verified that the category exist and have content. 

https://gzodigital.d.pr/qPMc6P

**Comment by minhcasi** [comment]
Thank you for the feedback - pls post your all issues & question to One ticket #3013, also help us to submit this form and fill all required info to continue with the support - http://private.inspireui.com/ - thank you for your time!
