### ISSUE TITLE
[FluxStore Woocommerce] Order Notes and Major problem with orders

### ISSUE THREAD

**Issue by abstractionltd** [inspireui/support#3057]
Step 1 (require): detail issues and screenshots
* I am having some trouble customizing the text in the app. I have changed the l10n.dart and intl_en.arb files but the text in the app remains the same.
* I would also like to make this field mandatory for checkout please

![](https://screenshot.click/k6fzt-4m7lg.png)

![](https://screenshot.click/alwz8-8b4ki.png)

![](https://screenshot.click/z2qo3-1jm4b.png)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)
DONE

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by abstractionltd** [comment]
Second **MAJOR** problem: Orders through app are not showing correct variant price

1. select variant on app:
![](https://screenshot.click/3ul7c-7tkat.png)

2. place order (price is totally wrong, based on base or lowest price)
![](https://screenshot.click/pv6t5-lwgsn.png)

3. web orders work 100%
![](https://screenshot.click/s4231-x5csv.png)

![](https://screenshot.click/g9vkk-r7ndm.png)

**Comment by philipvu30** [comment]
Hi,

1. Make sure you change the text in this file also lib/generated/intl/messages_en.dart.
2. Currently investigating.

**Comment by abstractionltd** [comment]
Yes, but when the order is placed it ignores the selected options and shows the base price, which is wrong.

Look at my screenshots again:
![](https://camo.githubusercontent.com/3dae84d66a4c26b342b11bdf6580d6e64cfed335/68747470733a2f2f73637265656e73686f742e636c69636b2f70763674352d6c7767736e2e706e67)
* this is from the order screen after the order was placed from the app. Note the options in the red box, and the price charged (4.50)

![](https://camo.githubusercontent.com/68a61e27dd011d4805d997e5f4221be6b4a7e129/68747470733a2f2f73637265656e73686f742e636c69636b2f73343233312d78356373762e706e67)
* this is from the storefront, with those same options selected. It should be charging $5.

![](https://camo.githubusercontent.com/59338b1b08ddd61d641a057382818cd8eb51961f/68747470733a2f2f73637265656e73686f742e636c69636b2f33756c37632d37746b61742e706e67)
* this is the options when selected on the app, it is also showing $5 but the order being put through to woocommerce is for 4.50, which is the base price without options.

Conclusion: the app is sending the wrong order information to woocommerce

**Comment by abstractionltd** [comment]
I have made a video showing the order steps in the app, confirming several times that the order is $5, and then showing the order in WooCommerce for $4.50. It is also adding TAX which is NOT supposed to happen since the prices all already include tax.

https://screenshot.click/nh0me-nk0uk.mp4

**Comment by abstractionltd** [comment]
I have also noticed that the the order notes are not showing on the actual order (you can see me typing an order note in the video. Screenshot below shows order without any order notes)

![](https://screenshot.click/72zmi-efwfu.png)

**Comment by abstractionltd** [comment]
![](https://screenshot.click/j07fw-rcerc.png)

The loading bar also never goes away. Running Mstore API 2.3.9

**Comment by philipvu30** [comment]
Hi,

I'm sorry I didn't understand your problem correctly. These issues have been fixed and they will be included in the next update.

**Comment by abstractionltd** [comment]
No problem 😃

 

Can you tell me when the next update will be available? Would love to get this app out asap.

 

Best,

Hugo

**Comment by abstractionltd** [comment]
![](https://camo.githubusercontent.com/b96c32fa42557dbedb5d91aeee531b4efbb4aacd/68747470733a2f2f73637265656e73686f742e636c69636b2f6c35796b622d72623037612e706e67)

The variant in woocommerce is set to NOT have default values selected. The app is ignoring this setting and selecting random options and then showing the incorrect price even based on the variant it selects.

In my screenshot it has selected Regular X Regular x Yes options which should have a cost of $5.5, not $6.0.

![](https://camo.githubusercontent.com/158d0ac989b1f2cc131a14485737f5f04d6f6418/68747470733a2f2f73637265656e73686f742e636c69636b2f71796a717a2d70763877382e706e67)

If you then add that random selection to the cart it is not even adding the same product as what has been selected.

**Comment by philipvu30** [comment]
Hi,

Sorry for the delayed response.
Please send your config.dart and config.json to this email: toan@inspireui.com.
Also don't delete your old consumer key and consumer secret until all your problems have been solved. 
Thanks

**Comment by philipvu30** [comment]
Hi,

Please change this term per_page=20 to per_page=100. Your issue should be fixed.

![image](https://user-images.githubusercontent.com/54442328/81925373-9d3bc200-960a-11ea-9df5-87bff9be7ac7.png)

You can find it here: lib/services/woo_commerce.dart
