### ISSUE TITLE
ZIP CODE TO BE OPTIONAL (REQUEST)

### ISSUE THREAD

**Issue by samik9** [inspireui/support#3058]
Hello, will be nice for next update that Zip code, or postal code could be set as true or false
![Android Emulator - Nexus_5_API_29:5554 2020-05-06 18-34-40](https://user-images.githubusercontent.com/50071744/81238680-46116e00-8fc8-11ea-9e88-6c232c33ac6c.png)

**Comment by minhcasi** [comment]
Thank you for the feedback - pls post your all issues & question to One ticket #3013, also help us to submit this form and fill all required info to continue with the support - http://private.inspireui.com/ - thank you for your time!
