### ISSUE TITLE
Stuck when change the config_en.json

### ISSUE THREAD

**Issue by harjono-flux** [inspireui/support#3060]
hello, can you help me, im newbie in programming, and i try to setting my own website.
I got problem when editing config_en.json from flexbuilder
when i paste the code to config_en.json and running the program, always stack in [Fluxstore][Tabbar] build

![Screen Shot 2020-05-07 at 09 42 50](https://user-images.githubusercontent.com/64935574/81245261-20777980-9047-11ea-95ba-891670d78c32.png)

**Comment by minhcasi** [comment]
@harjono-flux - thank you for the detail - we will investigate and update it on the next release - thank you!

**Comment by minhcasi** [comment]
@harjono-flux - pls help to try with latest Fluxstore 1.7.3 to fix this issue - thank you!

**Comment by harjono-flux** [comment]
Yeah, thx for fast respons.
Problem Solved
