### ISSUE TITLE
[FluxStore Shopify] NoSuchMethodError on cart page

### ISSUE THREAD

**Issue by Mikel-NC** [inspireui/support#3061]
Step 1 (require): detail issues and screenshots

![image](https://user-images.githubusercontent.com/64938924/81245477-c84d7100-9060-11ea-9433-8e02da87c6d3.png)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

Done

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by luyx2412** [comment]
Hi @Mikel-NC Can you give me the specific version? 

Thanks

**Comment by Mikel-NC** [comment]
fluxstore-shopify 1.6.7

**Comment by luyx2412** [comment]
Hi @Mikel-NC Please update latest version fluxshopify to fix the issues.

Thanks

**Comment by justinekatebe69** [comment]
Hey I’m experiencing this issue to. What’s a the fix for this. I’m on the update posted on June 11.

**Comment by justinekatebe69** [comment]
Even your current demo flux Shopify app is experiencing this issue.
