### ISSUE TITLE
[FluxStore Woocommerce] Facing many issues

### ISSUE THREAD

**Issue by fabfeminacan** [inspireui/support#3062]
Issues noted in image below:
![issues1](https://user-images.githubusercontent.com/64870491/81245808-fc368100-8fe3-11ea-86e1-9426e9327ce5.jpg)

Step 1 (require): detail issues and screenshots

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by philipvu30** [comment]
Hi,

1. Please check if you have updated the Mstore-API plugin and verify the purchase code with it.
2. Make sure you have checked these options for each product's setting.
![image](https://user-images.githubusercontent.com/54442328/81257552-bcac7b00-905d-11ea-8598-ada9b90f589f.png)
3. The rating that we get from your product it shows 0.0. We only support the default rating from woocommerce. If you are using any other rating plugin, then it won't show correctly. 
For the title issue, it will be solved in the next update. It happens because the variable products in step 2 are not fully loaded.

Ps: If you are doing Dropshipping, it will be a burden to do step 2. If you don't want to do it, you can remove this term in lib/models/product/product.dart
![image](https://user-images.githubusercontent.com/54442328/81258158-3f820580-905f-11ea-91c8-82f06b67606c.png)

**Comment by fabfeminacan** [comment]
Hi,

Please check if you have updated the Mstore-API plugin and verify the purchase code with it. 
- **YES BUT STILL UNABLE TO LOGIN**

The rating that we get from your product it shows 0.0. We only support the default rating from woocommerce. If you are using any other rating plugin, then it won't show correctly. 
- **I AM NOT USING ANY OTHER RATING PLUGIN**

For the price and sale issues, it will be solved in the next update. It happens because the variable products in step 2 are not fully loaded. 
- **HOW TO UPDATE WITHOUT AFFECTING CHANGES IN APP?** **I AM GETTING ERROR AFTER UPDATING TO 1.7.3 - ERROR IN FAILED ASSERTION: BOOLEAN EXPRESSION MUST NOT BE NULL **

Ps: If you are doing Dropshipping, it will be a burden to do step 2. If you don't want to do it, you can remove this term in lib/models/product/product.dart 
- **DONE. BUT MY PRODUCT VARIANTS ARE DISPLAYED IN IMAGE ON WEBSITE. HOW TO DISPLAY IMAGES FOR PRODUCT VARIANTS IN APP?**
image

**Comment by fabfeminacan** [comment]
Sorry for capital letters in my last comment. I forgot to clarify in above comment that I am not showing anger. Just wanted my answers to be differentiate from your suggestions. Waiting for your answers. Thank you. :)

**Comment by fabfeminacan** [comment]
Getting this error after updating to fluxstore 1.7.3

![96280968_572696936988500_3920603206152880128_n](https://user-images.githubusercontent.com/64870491/81358341-39fade80-90a4-11ea-9bfb-7352ad7fe035.png)

**Comment by philipvu30** [comment]
Hi,

In your config_en.json, please add "StickyHeader" : false to the Setting section. If you are using multiple languages, add that term to all of them.

![image](https://user-images.githubusercontent.com/54442328/81362992-5cc0dd80-910c-11ea-9d96-4b4554ad863a.png)

**Comment by magic-coding** [comment]
Also the product variations quantity not supported. I have a product with 2 variations, each variation has a different number of quantity the issue is the app allows the user to select from 1-100 quantity. For example one of the variations has 10 quantity and i add to cart 20 quantity and complete the order.

**Comment by kenngigz** [comment]
hi i am having the same problem. I upgraded to 1.7.3 and updated config_en_json with "StickyHeader" : false but still got the same issue.
![cop](https://user-images.githubusercontent.com/57593885/81408333-ba255080-9145-11ea-82bd-5e6d41942d17.png)

**Comment by philipvu30** [comment]
Hi all,

Sorry for the delayed response.
@magic-coding I'll check your issue. I remember this issue has already been fixed.
@kenngigz Please check if you added it in the correct section.

**Comment by magic-coding** [comment]
@philipvu30 I solve this by checking the product type on `ProductVariantMixin` then I pass the `productVariation.stockQuantity` and change the `limitSelectQuantity` to variation stock quantity.
Now the quantity selection got update when I click on any product attributes.


```
if(product.type == 'variable') {
  return QuantitySelection(
    stockQuantity: productVariation.stockQuantity,
    value: quantity,
    color: theme.accentColor,
    limitSelectQuantity: productVariation.stockQuantity,
    onChanged: onChangeQuantity,
  );
} else if(product.type == 'simple') {
  return QuantitySelection(
    value: quantity,
    color: theme.accentColor,
    limitSelectQuantity: product.stockQuantity,
    onChanged: onChangeQuantity,
  );
}   

```

**Comment by minhcasi** [comment]
@magic-coding - appreciate for your help with the magic code 👍

@philipvu30 - pls help to check and apply this fix

**Comment by philipvu30** [comment]
Updated. This fix will be available in the next update. 
Thanks for your help.

**Comment by magic-coding** [comment]
Hello,
Is the product variation max quantity selection fixed on the 1.7.5 version ? Before it’s show selection from 1-100 and the product quantity on the website only 5 .

**Comment by philipvu30** [comment]
Hi @magic-coding ,

Yes. Now it'll only show current available stock for a specific product/variable product (if manage stock is enabled).

**Comment by fabfeminacan** [comment]
Hi,

Please check if you have updated the Mstore-API plugin and verify the purchase code with it.

**YES BUT STILL UNABLE TO LOGIN**

The rating that we get from your product it shows 0.0. We only support the default rating from woocommerce. If you are using any other rating plugin, then it won't show correctly.

**I AM NOT USING ANY OTHER RATING PLUGIN**

For the price and sale issues, it will be solved in the next update. It happens because the variable products in step 2 are not fully loaded.

**HOW TO UPDATE WITHOUT AFFECTING CHANGES IN APP?** 

Ps: If you are doing Dropshipping, it will be a burden to do step 2. If you don't want to do it, you can remove this term in lib/models/product/product.dart

**DONE. BUT MY PRODUCT VARIANTS ARE DISPLAYED IN IMAGE ON WEBSITE. HOW TO DISPLAY IMAGES FOR PRODUCT VARIANTS IN APP?**
