### ISSUE TITLE
Issue running the MStore Pro - Complete React Native template

### ISSUE THREAD

**Issue by mesbahiayoub** [inspireui/support#3064]
Hello, 
I just purchased the MStore Pro React Native App, and i can't run it on  snack.expo.io tool,
I run into some issues, but i can't resolve this one : 

`Device: (857:881) Unable to resolve module 'module://react-native/Libraries/Network/XHRInterceptor.js'
  Evaluating module://react-native/Libraries/Network/XHRInterceptor.js
  Evaluating module://reactotron-react-native.js
  Evaluating module://src/store/configureStore.js.js
  Evaluating module://App.js.js
  Loading module://App.js`

**Comment by minhcasi** [comment]
@mesbahiayoub snack.expo will not work with Mstore Pro as we have used some native library that could only run on the local machine - thank you for your question
