### ISSUE TITLE
[FluxStore Pro] - Native Password reset showing blank screen

### ISSUE THREAD

**Issue by tjain90** [inspireui/support#3065]
Step 1 (require): detail issues and screenshots
Native password screen is showing blank white screen.  Attached snapshot for your refrence.
![Screenshot_20200507-091228](https://user-images.githubusercontent.com/6376301/81252323-4c90fb80-9043-11ea-8ad4-38ee14b62a4d.jpg)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by philipvu30** [comment]
Hi,

Have you submitted the common folder via our form? Because I don't see your ticket IDs along with the required folder.

**Comment by tjain90** [comment]
@philipvu30 Shared.  Please review now.

**Comment by philipvu30** [comment]
Hi,

Please put your forget password link to your config.dart

 "forgetPassword": "https://www.indidecor.com/wp-login.php?action=lostpassword"

And you don't need to submit the form every time you open a ticket in case you are missing required config files. Just write your previous ticket ID so we can check if you are our customer. Thanks

**Comment by tjain90** [comment]
It was left blank because it was mentioned to leave blank if we want to use native feature.
Adding forgot password link redirect using webview. Any way to use this feature as app feature via api or something?

**Comment by philipvu30** [comment]
Hi,

Sorry for the delayed response. Please replace this code:
**final String forgotPasswordUrl = Config().forgetPassword;**
to this code:
**final String forgotPasswordUrl = Config().forgetPassword ?? '${Config().url}/wp-login.php?action=lostpassword';**
You can find the code in lib/screens/users/forgot_password.dart

**Comment by tjain90** [comment]
Thanks it worked :)
