### ISSUE TITLE
Fluxnews I have some things that need to be customized

### ISSUE THREAD

**Issue by haidarsalim** [inspireui/support#3066]
I have some things that I hope you will answer

1 Can this part be hidden or converted into Arabic?
![Capture11](https://user-images.githubusercontent.com/54249914/81254723-98887400-9034-11ea-96f4-ca62dcf1dc0d.JPG)
---

2 Can you add infinite scrolling * View more
![Capture](https://user-images.githubusercontent.com/54249914/81254843-e604e100-9034-11ea-94e3-775e8f2232fc.JPG)
---

**3 In the iPhone version, why does the record button via Apple ID not work?**
![Capture](https://user-images.githubusercontent.com/54249914/81255189-b60a0d80-9035-11ea-89b7-729a899fbd38.JPG)

> Thanks again for your continued support

**Comment by minhcasi** [comment]
Thank you for reporting, we have updated as the feature request and send to the team for investigating - thank you!

**Comment by haidarsalim** [comment]
Was it added with version 1.4.1

**Comment by dttrung26** [comment]
Hi @haidarsalim , 
Please download and replace those files as following: 
- detailed_blog_quarter_image.dart into your /lib/widgets/blog/detailed_blog/ 
- vertical_layout.dart into your /lib/widgets/blog/vertical/
For the last issue, could you please leave me console error when clicking Appgle Signin button? Many thanks.
[support_ticket3066.zip](https://github.com/inspireui/support/files/4610723/support_ticket3066.zip)

**Comment by dttrung26** [comment]
Close due to unactivity from user. Feel free to reopen this ticket again if you are still facing this issue.
Nice day!

**Comment by haidarsalim** [comment]
I cannot experiment at the moment because of other problems that I have
Because of the new update and the old version is not working
https://github.com/inspireui/support/issues/3221
https://github.com/inspireui/support/issues/3132

**Comment by imbritto** [comment]
> Hi @haidarsalim ,
> Please download and replace those files as following:
> 
> * detailed_blog_quarter_image.dart into your /lib/widgets/blog/detailed_blog/
> * vertical_layout.dart into your /lib/widgets/blog/vertical/
>   For the last issue, could you please leave me console error when clicking Appgle Signin button? Many thanks.
>   [support_ticket3066.zip](https://github.com/inspireui/support/files/4610723/support_ticket3066.zip)

This fixes the loading issue but it keeps loading the same 10 posts again in a loop.
