### ISSUE TITLE
Fluxstore:

### ISSUE THREAD

**Issue by qorane099** [inspireui/support#3067]
I have several issue please help to solve/

1. the app is not running to ios device, i even run sudo gem install cocoapods.

please see link below for error message

https://anotepad.com/notes/6j83h9wc

2. there an issue in checkout page, review and payments tabs are not working, after l do finish address and shipping, nothing will happen. plz note that l checked original source and has the same issue.

3. set up basics of xcode, l got an issue of "Your development team, "Abdulkadir Qorane", does not support the Push Notifications and Associated Domains capabilities"

plz see screenshot below
<img width="1060" alt="Screenshot 2020-05-07 at 12 47 46 PM" src="https://user-images.githubusercontent.com/39888242/81265661-1c585580-9061-11ea-96d6-2fe67c1ab825.png">
![IMG_20200402_201209](https://user-images.githubusercontent.com/39888242/81265708-2c703500-9061-11ea-84ae-f6774dd4c728.jpg)

**Comment by minhcasi** [comment]
Hi @qorane099 - please thank you for the feedbacks
1. pls check this video guide- https://www.youtube.com/watch?v=ReAUZDIgh2I
2. please help to share the screenshot again as we could read it
3. pls check this video guide - https://www.youtube.com/watch?v=rFCcWNRPrSk&t=17s

**Comment by qorane099** [comment]
what about the issue of checkout page?

review and payments tabs are not working

**Comment by minhcasi** [comment]
@qorane099 - that's why we need your detailed screenshot so that we reproduce to fix the issue, pls help to share it - thank you!

**Comment by qorane099** [comment]
<img width="542" alt="Screenshot 2020-05-09 at 2 46 40 PM" src="https://user-images.githubusercontent.com/39888242/81469660-e99a9280-9203-11ea-854e-5fc4e8800f93.png">


THIS IS THE SCREENSHOT OF THE ISSUE.

please note the button "continues to review" is not working. the app will not open review and payments tabs

**Comment by qorane099** [comment]
also this issue is still exist even after l watch videos and followed docs.

https://anotepad.com/notes/6j83h9wc

**Comment by qorane099** [comment]
also l got this issue from checkout after l did change ISO code to Kenya

error in exception: the initial value provided is not supported in iso code


l see the your app is not supporting kenya ISO.

please when will you able to update this. this is very very important to me

**Comment by minhcasi** [comment]
@qorane099 - could you hep to rename this file to woo_commerce.dart (remove .txt) and override to the services folder to see if it can be fixed the issue

[woo_commerce.dart.txt](https://github.com/inspireui/support/files/4605071/woo_commerce.dart.txt)

**Comment by minhcasi** [comment]
@minhtruong315 - pls help to investigate

**Comment by qorane099** [comment]
the file was woo_commerce.dart and i changed to woo_commerce.dart.txt.


the issue is still there

**Comment by trunghieuvn** [comment]
Hello @qorane099   
about error in picture: https://user-images.githubusercontent.com/39888242/81265661-1c585580-9061-11ea-96d6-2fe67c1ab825.png  
Currently project have feature push notification in iOS platform.  
It's require use account apple develop  (99$ or 299$).   
if account apple develop does not exis, please run in emulator  
thanks

**Comment by hengsoheak** [comment]
account apple develop 99$ how about 299$? Please help explain.

**Comment by qorane099** [comment]
It's require use account apple develop  (99$ or 299$).
if account apple develop does not exis, please run in emulator


please let me know more details about two above points.


l dont have apple account, l am still to pay the apple developer account.
so does that mean, l cannot run the app without having apple
purchased account.


so this point "if account apple develop does not exis, please run in
emulator" l already run emulator and shows that error in the screen

**Comment by minhtruong315** [comment]
@qorane099 The original source code is working on checkout. Can you record screen?

**Comment by qorane099** [comment]
@minhtruong315 this is screen recording of checkout issue.

https://drive.google.com/open?id=1Q3TRiiOxh55L8EmWhPHFhR3KJX5LO7Vp

**Comment by minhtruong315** [comment]
@qorane099 can u upload your source code to  git repo then add my email: minhtruong315@gmail.com
I will help you fix this issue
Thanks

**Comment by qorane099** [comment]
@minhtruong315 let me send you through private mail. I will add google drive and share with you the link

**Comment by minhtruong315** [comment]
@qorane099 you can upload to github then invite me. it's easy to check and fix on your source code.  Thanks

**Comment by qorane099** [comment]
@minhtruong315  l dont have any experience from github and it will take time to learn more about github and how it works.  please allow me to send you the source to any otherway or you can get my laptop using teamviewer.

 due to your professionalism, it will not take more a few minutes to fix this error.

thank you

**Comment by minhtruong315** [comment]
@qorane099 add my skype: minhtruong315. i will help you  via teamviewer

**Comment by qorane099** [comment]
@minhtruong315  l said hi to you from skype today earlier.


this is my skype ID: qorane.002@gmail.com

**Comment by qorane099** [comment]
@minhtruong315 please get back to me,  today is friday and you will be off tomorrow and after tomorrow .


please try to contact before the end of the day

thank you

**Comment by minhtruong315** [comment]
Hi @qorane099 I ping you  on the skype. pls reply.
Thanks

**Comment by minhtruong315** [comment]
@qorane099 I checked your source code. it's old source code. please download the latest version 1.7.3 on codecanyon then check again

**Comment by qorane099** [comment]
l downloaded the source from codecanyon and after runned, l am getting this issue.

https://anotepad.com/notes/wrw4i66x

**Comment by minhtruong315** [comment]
You need to upgrade flutter 1.17

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!

**Comment by qorane099** [comment]
Dear @minhtruong315, the checkout issue is still there, the original source has no issue and its checkout is working fine but when l do connect to my dokan website, then the checkout is not working.

please note that the website has payment method like bank and cash on delivery.


also, l need to know, what are the best way to update the old source to new version 1.17 without writing and customersing the whole source.

my old source has everything, l did customersized and allowed social login, how can l update that old source.

or do l have to download the new source and customer and allow social login from the begining
