### ISSUE TITLE
FluxstoreMV Latest Products & New Collections not showing on main page

### ISSUE THREAD

**Issue by miamir2000** [inspireui/support#3068]
FluxstoreMV

Latest Products & New Collections not showing on main page. Other pages working fine.

**Comment by miamir2000** [comment]
<img width="951" alt="Screenshot 2020-05-07 at 3 46 34 PM" src="https://user-images.githubusercontent.com/9026297/81268381-744f8600-907a-11ea-89ef-b8717b5b8a0d.png">

<img width="951" alt="Screenshot 2020-05-07 at 3 46 49 PM" src="https://user-images.githubusercontent.com/9026297/81268421-7f0a1b00-907a-11ea-98bc-cc67cb03bf64.png">

**Comment by minhcasi** [comment]
@miamir2000 - Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ 

We will close this ticket as is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
verified - @minhtruong315 - pls help to investigate the issue - thanks

**Comment by kibbyboi** [comment]
Same issues here

**Comment by minhtruong315** [comment]
@miamir2000 add my skype: minhtruong315
I will help you check it.

**Comment by kibbyboi** [comment]
Noted I will do so

**Comment by minhtruong315** [comment]
@kibbyboi ping me when you're ready. Thanks
