### ISSUE TITLE
Fluxnews Build flutter error after upgrading to 1.17.0

### ISSUE THREAD

**Issue by rherreror** [inspireui/support#3069]
Hi,
i am at flutter stable channel, and it upgraded to 1.17.0, after that i can see the following errors:
note:
this error is the same at https://github.com/inspireui/support/issues/2547, but they were at master channel and solved changing to stable, now im in stable (and i supose changes in master have been commited to stable).

Launching lib\main.dart on Aquaris U2 in debug mode...

Compiler message:
/D:/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image-0.7.2/lib/src/gesture/extended_image_slide_page_route.dart:333:9: Error: No named parameter with the name 'animation'.
        animation: animation,
        ^^^^^^^^^
/D:/flutter/packages/flutter/lib/src/cupertino/route.dart:435:3: Context: Found this candidate, but the arguments don't match.
  CupertinoFullscreenDialogTransition({
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/D:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.15.0/lib/src/picture_stream.dart:92:3: Error: The superclass, 'Diagnosticable', has no unnamed constructor that takes no arguments.
  PictureStream();
  ^^^^^^^^^^^^^
/D:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.15.0/lib/src/picture_stream.dart:192:16: Error: The superclass, 'Diagnosticable', has no unnamed constructor that takes no arguments.
abstract class PictureStreamCompleter extends Diagnosticable {
               ^

**Comment by minhcasi** [comment]
@rherreror - we will update Fluxnews today to fix this issue and fully compatible with Flutter 1.17, in the meantime please try to update the pubspec.yaml  and upgrade the extended_image same as this version then run the `pub get` again to rebuild the project.

```
  extended_image: 0.7.3-dev
```

**Comment by minhcasi** [comment]
@rherreror - also try with latest 1.4.1 that released today - we have fixed this issue
