### ISSUE TITLE
Error when access to store

### ISSUE THREAD

**Issue by xsamir** [inspireui/support#3070]
Step 1 (require): detail issues and screenshots
When I try to open any shop on the store list, it gives me an error:  Error in Failed assertion: boolean expression must not null.
![image](https://user-images.githubusercontent.com/7432001/81279208-e23e8200-9067-11ea-9321-c14bd670a3cd.png)
![image](https://user-images.githubusercontent.com/7432001/81279220-e7033600-9067-11ea-858a-5972cb241591.png)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhcasi** [comment]
@xsamir - pls help us to raise your all issues to the same ticket #3071 - thank you!
