### ISSUE TITLE
Login issues

### ISSUE THREAD

**Issue by xsamir** [inspireui/support#3071]
Step 1 (require): detail issues and screenshots
this problem can be in two parts:
1- I already set on WordPress that the new user will be assigned as a vendor:
![image](https://user-images.githubusercontent.com/7432001/81279832-aeb02780-9068-11ea-9bc6-fb0733fe2503.png)
and when the user signup using social login (Facebook.Google), he shows on my dashboard a vendor
![image](https://user-images.githubusercontent.com/7432001/81279941-d69f8b00-9068-11ea-83ee-619ab1a10217.png)

But in the App, there are no My Product options
![image](https://user-images.githubusercontent.com/7432001/81280291-4dd51f00-9069-11ea-8085-062354ed6e53.png)

My Product options show only when the user sign up by email and password.
......................................

2- Second part of the problem, is that the user when he login even social login or by email & password, he use the App smoothly and fine but when he close the App and reopen it again it required to log in again (App sign him out when close the app).
Also when the user login, it's doesn't forward the user to the app screen, it keeps processing on the login page, unless if he clicks back.
![image](https://user-images.githubusercontent.com/7432001/81280729-f1beca80-9069-11ea-9b64-b74169364ed2.png)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhcasi** [comment]
@xsamir - could i confirm you are using the latest version? 

@minhtruong315 - pls help for checking

**Comment by xsamir** [comment]
No, I'm was using 1.7.0, now I try to move to the next version

**Comment by minhtruong315** [comment]
Hi @xsamir pls use the latest version on codecanyon and replace this file models/user/user.dart
[user.dart.zip](https://github.com/inspireui/support/files/4597461/user.dart.zip)

**Comment by xsamir** [comment]
I tried to upgrade to the newer version 1.7.3 and I'm using layout number 11
But it shows an error as shown on the main screen, but it's going fine with the original layout.

![image](https://user-images.githubusercontent.com/7432001/81481940-9bf24a00-9244-11ea-94ce-097b7681e063.png)
