### ISSUE TITLE
[Multi Vendor] Issues in Product Image, Checkout, and Build Failed in latest Flutter 1.17.0

### ISSUE THREAD

**Issue by jinuem** [inspireui/support#3072]
Step 1 (require): detail issues and screenshots
Hi,
Total 3 Issues.

1. Even Guest Checkout is false in the settings. Still, I can swipe left and go to checkout from the cart page. But the Checkout button takes to Login/Signup page. Swipe should be disabled.

![Screenshot 2020-05-07 17 03 33](https://user-images.githubusercontent.com/3512723/81289856-b087e400-9084-11ea-8048-112bae847b29.png)

2. Product Image is overlapping the status bar of the mobile also lots of spaces below the product image.
![5d301d68-29f1-4b44-b108-07e3f3551c0f-1](https://user-images.githubusercontent.com/3512723/81289897-c4334a80-9084-11ea-823f-b31891bcfaff.jpg)

3. Compile Error after updating Flutter Latest Stable (1.17.0)

![Screenshot 2020-05-07 17 07 17](https://user-images.githubusercontent.com/3512723/81290196-43c11980-9085-11ea-82d0-26360a1eb325.png)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)
SUBMITTED

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by kumsalajans** [comment]
3 compile error

https://gitlab.com/inspireui/fluxstore-pro/-/merge_requests/9/diffs?commit_id=12178ee6dba8ac73aeb6bb1314eb0b0b80f6bc6f

**Comment by minhcasi** [comment]
@jinuem 

1. we will check this UX issue - @minhtruong315 - pls help to check this issue
2. pls update this config - https://tppr.me/BITl9
3. update the latest 1.7.3 will fix this issue

**Comment by minhcasi** [comment]
solution for #1 - update this file https://tppr.me/gXYSd
```
 Widget renderCartPageView({context, isModal, isBuyNow, pageController}) {
    bool isEmptyCart =
        Provider.of<CartModel>(context, listen: false).totalCartQuantity == 0;
    bool loggedIn = Provider.of<UserModel>(context).loggedIn;

    bool enableSwipping =
        !kPaymentConfig["EnableOnePageCheckout"] && !isEmptyCart && loggedIn;
...
```

**Comment by jinuem** [comment]
Thank You!
