### ISSUE TITLE
Needs to be changed?

### ISSUE THREAD

**Issue by mryous** [inspireui/support#3073]
is that all these code should be changed?

Firebase
![image](https://user-images.githubusercontent.com/28628432/81291074-bdfc9880-909b-11ea-9742-43f7ff79d83f.png)

Analytic
![image](https://user-images.githubusercontent.com/28628432/81291240-ff8d4380-909b-11ea-9448-7fb0867dfb08.png)

Default Currency & OneSignal 
![image](https://user-images.githubusercontent.com/28628432/81291355-306d7880-909c-11ea-8c9c-3b5a997591f6.png)
( Indonesia Symbol is Rp)

please answer sir, and maybe some short documentation plz.
--

**And with all the limit I have, I want to start build a test app with CeBuilder Delivery menu**

`? Choose the build type you would like: apk
An Expo user account is required to proceed.
? How would you like to authenticate? Log in with an existing Expo account
? Username/Email Address: ****
? Password: [hidden]

Success. You are now logged in as ****.
Checking if there is a build in progress...

? Would you like to upload a keystore or have us generate one for you?
If you don't know what this means, let us handle it! :)
 false
Warning: Your project may contain unoptimized image assets. Smaller image sizes can improve app performance.
To compress the images in your project, abort publishing and run npx expo-optimize.
Unable to find an existing Expo CLI instance for this directory; starting a new one...
Starting Metro Bundler on port 19004.
Publishing to channel 'default'...
Building iOS bundle
Unable to resolve module `../../App` from `node_modules\expo\AppEntry.js`:

None of these files exist:
  * App(.native|.ios.expo.ts|.native.expo.ts|.expo.ts|.ios.expo.tsx|.native.expo.tsx|.expo.tsx|.ios.expo.js|.native.expo.js|.expo.js|.ios.expo.jsx|.native.expo.jsx|.expo.jsx|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.wasm|.native.wasm|.wasm)
  * App\index(.native|.ios.expo.ts|.native.expo.ts|.expo.ts|.ios.expo.tsx|.native.expo.tsx|.expo.tsx|.ios.expo.js|.native.expo.js|.expo.js|.ios.expo.jsx|.native.expo.jsx|.expo.jsx|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.wasm|.native.wasm|.wasm)
› Closing Expo server
Unable to resolve "../../App" from "node_modules\expo\AppEntry.js"
Failed building JavaScript bundle.
› Stopping Metro bundler
Packager URL http://127.0.0.1:19004/node_modules\expo\AppEntry.bundle?dev=false&minify=true&hot=false&platform=ios returned unexpected code 500. Please open your project in the Expo app and see if there are any errors. Also scroll up and make sure there were no errors or warnings when opening your project.`

what error I have now sir?

**Comment by mryous** [comment]
![image](https://user-images.githubusercontent.com/28628432/81298984-2782a400-90a8-11ea-955c-9c75a5c397c7.png)

@minhcasi @luyx2412

**Comment by mryous** [comment]
even tho i've done select the country, it still become not selected, the process cannot continue

![image](https://user-images.githubusercontent.com/28628432/81307652-7bdf5100-90b3-11ea-9d3a-8be0bb7a1384.png)

**Comment by mryous** [comment]
Hallo sir.. please help me 
![image](https://user-images.githubusercontent.com/28628432/81408589-1a30ec80-9170-11ea-9393-de38421a9d23.png)

**Comment by mryous** [comment]
cmon sir..., its been two days right now. :(

**Comment by minhcasi** [comment]
@luyx2412 - please help to investigate

**Comment by luyx2412** [comment]
Hi @mryous Thanks for your rating.

1. The expo project have two options to generate apk file. Please login your expo account and generate new keystore. Please read the document https://docs.expo.io/distribution/app-signing/#android
2. Do you want to remove select country in Delivery tab?

Thanks

**Comment by mryous** [comment]
1. Yes, I have logged in to my acc
As seen as the code above
`Success. You are now logged in as ****.
Checking if there is a build in progress...

? Would you like to upload a keystore or have us generate one for you?
If you don't know what this means, let us handle it! :)
false
Warning: Your project may contain unoptimized image assets. Smaller image sizes can improve app performance.`

2. Yess.. sir

**Comment by mryous** [comment]
and yess..... I should've to waiting some more time...
cmon sir... how long I have to wait??
plzz @minhcasi mention him..

**Comment by luyx2412** [comment]
Hi @mryous 
- The first please follow the document issue. You need optimize your assets 
![image](https://user-images.githubusercontent.com/8909619/81490447-a6482e80-92ac-11ea-80df-c055f3b330c8.png)
- In `src/common/Config.js` line 488 please change `hideCountryList` from false to true to hide select country.

Thanks

**Comment by mryous** [comment]
1. How to change the date to Indonesian
![image](https://user-images.githubusercontent.com/28628432/81561823-637a7980-93c6-11ea-9ca6-32952afb56da.png)

2. I Want to remove the circle Category icon
![image](https://user-images.githubusercontent.com/28628432/81561850-742aef80-93c6-11ea-809e-089ee6376a6c.png)

3. I Think this is should be not present too
![image](https://user-images.githubusercontent.com/28628432/81562488-85283080-93c7-11ea-89e1-b5a42f38ea12.png)

4. How to change this currency with the language too
![image](https://user-images.githubusercontent.com/28628432/81563297-a9384180-93c8-11ea-894c-5740d576f27d.png)

Thank you sir

**Comment by luyx2412** [comment]
Hi @mryous 
1. You can import moment locale in `src/components/HorizonList/index`, please read this comment to import locale https://github.com/moment/moment/issues/2517#issuecomment-335016136
2. Please remove this field in your AppConfig.json file 
![image](https://user-images.githubusercontent.com/8909619/81566143-a9ced900-93c4-11ea-8a9e-108cd7818da8.png)
3. You can remove this component in `src/components/ProductList/index.js` file
![image](https://user-images.githubusercontent.com/8909619/81566240-cff47900-93c4-11ea-967d-c100d366f1f3.png)
4. In `src/components/ShippingMethod/index.js` please change `$` to your currency 
![image](https://user-images.githubusercontent.com/8909619/81566323-eef30b00-93c4-11ea-8343-7cdbae33a4cb.png)

Thanks

**Comment by mryous** [comment]
heyy pls sir, dont close this..
1 I still cant find how to do this
2,3,4 done change that , but still exist.. how to properly do it?? plzz

**Comment by mryous** [comment]
and number 3, I want the ListAllScreen is remove, not the category name
