### ISSUE TITLE
language, constant, cutButtonLabel, flutter 1.7 ios build  fix

### ISSUE THREAD

**Issue by kumsalajans** [inspireui/support#3074]
The view and language files were separated to fix language problems that occurred during the version update.

Settings page appbar color use constant.

**cutButtonLabel problem ios 1.7.3**

![image](https://user-images.githubusercontent.com/63232893/81298068-ed4fdd00-907c-11ea-98fe-feebfe01633c.png)

[**This issue**](https://github.com/inspireui/support/issues/2916)
6. issue

The error continues when the main language is not English, example german language.

This issue fix: [link](https://gitlab.com/inspireui/fluxstore-pro/-/blob/951ff289703511f8df59f13496955da903b54011/lib/app.dart#L199)

[fix](https://github.com/flutter/flutter/issues/43050#issuecomment-555121801)

![image](https://user-images.githubusercontent.com/63232893/81297902-acf05f00-907c-11ea-8138-5e0e431d75b6.png)

flutter 1.7 ios build failed fix,

Please accept merge request,
Thank You

**Comment by minhcasi** [comment]
@kumsalajans - thank you for your contribute - we have updated it 👍
