### ISSUE TITLE
[FluxStore Pro] How to make the Dark theme is the default theme?

### ISSUE THREAD

**Issue by bikostudio** [inspireui/support#3075]
Hi, @minhcasi 

1. How to make the Dark theme is the default theme? And how to change it's black background to any other color?

2. How to change the Tabber background to be different form the other pages?

Thank you

**Comment by minhcasi** [comment]
@philipvu30 - pls help to update this question to the document under the Customize menu (with the code demo and screenshot output)

**Comment by philipvu30** [comment]
Hi,

Please change your files as the image below

![image](https://user-images.githubusercontent.com/54442328/81383594-724cfc00-913a-11ea-8083-8e5a0d5cf2e9.png)

**Comment by bikostudio** [comment]
> 
> 
> Hi,
> 
> Please change your files as the image below
> 
> ![image](https://user-images.githubusercontent.com/54442328/81383594-724cfc00-913a-11ea-8083-8e5a0d5cf2e9.png)
Hi @philipvu30 
It works. Thank you
