### ISSUE TITLE
[Fluxstore Pro] Wommerce Unable to login by SMS 

### ISSUE THREAD

**Issue by tjain90** [inspireui/support#3076]
Step 1 (require): detail issues and screenshots
Login By SMS throws below exception
"Format Exception: Unexpected character (at character 1)<br/>"
![Screenshot_20200507-081840](https://user-images.githubusercontent.com/6376301/81303578-812fa200-9099-11ea-9c50-ef6909f56169.jpg)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by xsamir** [comment]
Make sure that the plugin MStore API activated on your website with your license number.

**Comment by tjain90** [comment]
@xsamir it is already activated and rest things are working fine including placing order.

**Comment by minhcasi** [comment]
@tjain90 - could you try to debug to see if there is any return issue from Android Studio? https://tppr.me/mc5BQ

**Comment by minhcasi** [comment]
Also, help us to raise only one ticket for your question - pls move to #3065
