### ISSUE TITLE
[Fluxstore Pro] Create HTML Page and Use in Privacy policy and About Us

### ISSUE THREAD

**Issue by tjain90** [inspireui/support#3077]
Step 1 (require): detail issues and screenshots

How to create page that can be used as privacy policy and about us content. 
Right now we need to paste text in post_screen.dart. How to show any html page we have in assets/html/xyx.html ?

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhcasi** [comment]
@tjain90 - pls try to use FluxBuilder tools - http://fluxbuilder.com/ - we have add these feature so that you could config super easy 

Also, help us to raise only one ticket for your question - pls move to #3076
