### ISSUE TITLE
App Crashing

### ISSUE THREAD

**Issue by joprey2020** [inspireui/support#3078]
Step 1 (require): detail issues and screenshots

My app keeps crashing. I noticed that it only crashes when I connect it to my woocommerce website. I also noticed that it crashes on certain occasions, for example, when I add something to cart or click buy now. It crashed on the AVD in the Android studio and even after publishing and on real devices (both iOS and Android). It just says (the app crashed).

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

License 0c69cc17-d907-4f8e-ac9b-45b4b86abcde

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by aldinhozanovicDev** [comment]
@joprey2020 If I was you, I wouldn't post my license key right here. You should send them your license as proof via  http://private.inspireui.com

**Comment by xsamir** [comment]
For your security, remove the license key
Otherwise anyone can use it and stole your license for his website

**Comment by minhcasi** [comment]
@joprey2020 

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ 

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!
