### ISSUE TITLE
Logged In User is Not Working in FluxStore Shopify

### ISSUE THREAD

**Issue by bilalmunir1995** [inspireui/support#3080]
When a User is logged in through the app order is treated as guest.
 My Point is not working
Order History also are not functional
![96234959_2927475963988539_7680444691199819776_n](https://user-images.githubusercontent.com/37571277/81346577-f1f3b000-90d3-11ea-9d51-c77a188e334a.jpg)
![95330592_2588185698176245_813594748643180544_n](https://user-images.githubusercontent.com/37571277/81346579-f28c4680-90d3-11ea-83e1-1df8ef98d1ac.jpg)
![96162426_868012140378775_4785641531174289408_n](https://user-images.githubusercontent.com/37571277/81346582-f324dd00-90d3-11ea-8e8c-3d086b076cc5.jpg)
<img width="1127" alt="Screenshot 2020-04-21 at 6 16 14 AM" src="https://user-images.githubusercontent.com/37571277/81346662-1b144080-90d4-11ea-841c-9cb18ee845ea.png">

**Comment by minhcasi** [comment]
@bilalmunir1995 - 
When a User is logged in through the app order is treated as guest. -> will check
My Point is not working -> this feature is not available, we will hide this menu
Order History also are not functional -> will check

Could you consider to update the rating as it is impacted to our business - thank your for your feedback so far, we are working really hard to support you, but we need your willing to support us the same - thank you for your time

**Comment by bilalmunir1995** [comment]
@minhcasi  i would love to update the rating but it has been around a month since i bought the product and two updates later if one thing is fixed the other is broken

**Comment by minhcasi** [comment]
@bilalmunir1995 - we are working hard to resolve them all, once they are all good, please consider to update :)

**Comment by bilalmunir1995** [comment]
any update?

**Comment by luyx2412** [comment]
Hi @bilalmunir1995 Sorry about delay, we are updating new version which included fix the some issues and add new features.

Thanks

**Comment by minhcasi** [comment]
@bilalmunir1995 - could you help to check the latest version and let us know if you are happy with the update, please make sure to update the Flutter to latest version 1.17.x - thank you!

**Comment by bilalmunir1995** [comment]
version 1.7.2 – 05 May 2020
i tried this version

**Comment by luyx2412** [comment]
Hi @bilalmunir1995 
- The login checkout payment, we are update native credit checkout, but have some issues. We will try to update soon.
- the my point function do not support in shopify version.
- I updated order history in 1.7.4 version and will release in couple dates.

Thanks

**Comment by luyx2412** [comment]
Hi @bilalmunir1995 Can you give me your email, I will send you the latest project which improve and add some features.

Thanks

**Comment by kwsystems** [comment]
@bilalmunir1995 I got a question for you. How you were able to hide the blog? I set it to false but it is not working.

Thank you in advance.

**Comment by luyx2412** [comment]
HI @kwsystems i replied in your post.

Thanks

**Comment by bilalmunir1995** [comment]
@luyx2412  mister.bilalmunir@gmail.com is the email

**Comment by bilalmunir1995** [comment]
@luyx2412  waiting for the new version?

**Comment by minhcasi** [comment]
@bilalmunir1995 - would you mind to update our rating pls - https://codecanyon.net/ratings/3120397 

Honestly, your rating have huge impact on our business, as you can see our team have been working hard to support your all issue - thank you for your help!
