### ISSUE TITLE
Home problem and notification

### ISSUE THREAD

**Issue by Roupasafricanas** [inspireui/support#3083]
Step 1 (require): detail issues and screenshots

![80747308-9d5f9c00-8af9-11ea-802b-a837f0f168f6](https://user-images.githubusercontent.com/63840938/81374852-9840b500-90d6-11ea-9969-76c9b9cb999c.jpg)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

Good night. I have some doubts :

1) I installed version 1.7.3 and on the home page, the following message appears:
![Screenshot_2020-05-08-02-46-57-963_com inspireui fluxstore](https://user-images.githubusercontent.com/63840938/81375214-68de7800-90d7-11ea-9d66-37c71582ceb0.jpg)

2) I can no longer connect via Google, pops up the following message : 
![Screenshot_2020-05-08-02-51-33-074_com inspireui fluxstore](https://user-images.githubusercontent.com/63840938/81375260-8ad7fa80-90d7-11ea-887c-379881b81644.jpg)

3) Here comes a suggestion : could you leave a cache on the pages accessed also by the application?
I have a social network that I inserted as onglet of the site and every time the visitor comes and goes to do anything, he needs to log in again. 
![Screenshot_2020-05-08-02-54-12-482_com inspireui fluxstore](https://user-images.githubusercontent.com/63840938/81375428-df7b7580-90d7-11ea-9542-bac91d1065ef.jpg)

Thank

**Comment by aldinhozanovicDev** [comment]
I installed version 1.7.3 and got the same issue. Since installed 1.7.3, the Home Screen doesn't work. It only works for the english Language.

**Comment by minhcasi** [comment]
@aldinhozanovicDev - try to add this setting to fix the homepage issue https://tppr.me/QTojz

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ - please don't share the purchase code public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by Roupasafricanas** [comment]
@minhcasi -Homepage erro fixed with the StickyHeader, thanks
-Notification erro fixed with the last youtube video
-Can you add my sugestion (the number 3) to the sugestion list please



Now I have two doubts, how to change the about us inspired by mine and how to insert my privacy page

**Comment by minhcasi** [comment]
Sorry, we should close this ticket as it could not be verified, please create the new one when you got enough purchased info - thank you!
