### ISSUE TITLE
Product pictures are not showing in Product Detail Page

### ISSUE THREAD

**Issue by Riorich** [inspireui/support#3084]
Step 1 (require): detail issues and screenshots

![LatLatSatSat_Screenshot_2020 05 08_13 14 38](https://user-images.githubusercontent.com/39195214/81378802-f8167a80-912d-11ea-8112-b010f421f061.jpg)

Hello Dear,
Please help to resolve my issues.
It's working fine in Debug Mode. But after I delployed app to Play Store, the product pictures are not showing in Downloaded App as above.

Fluxstore 1.7.2

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhcasi** [comment]
@Riorich - could you try to remove the flash "/" on the website URL - https://tppr.me/B3rqq

**Comment by minhcasi** [comment]
it's working fine with our testing on Fluxbuilder - https://tppr.me/H5AbV

**Comment by Riorich** [comment]
Aldy done it sir. But It's the same. In test mode, everything is ok. But Deployed Apk  still got the same error. 

![2020-05-09 (2)](https://user-images.githubusercontent.com/39195214/81469783-fd96c200-920c-11ea-91db-6ce3169e55a7.png)

**Test Mode (Flutter run)**
![Screenshot_1589015979](https://user-images.githubusercontent.com/39195214/81469808-25862580-920d-11ea-9d70-e3d895451bac.png)

**Deployed Apk**
![2020-05-09 (3)](https://user-images.githubusercontent.com/39195214/81469837-464e7b00-920d-11ea-8816-bc879af1c378.png)

**Comment by Riorich** [comment]
Thanks you for your assistance. I got this error on Android Tablet. It's totally fine on Android Phone.
