### ISSUE TITLE
FluxStore Pro.  some issues

### ISSUE THREAD

**Issue by yosefasad** [inspireui/support#3085]
1.    how to change the blue pic ... as shown below
![1](https://user-images.githubusercontent.com/23431061/81390297-d9ab8180-9123-11ea-9216-f0ee5298432a.jpg)

2.   when press category button,     in Arabic.  All categories are shown,, in English. Not all categories are shown   ....    How to fix it  ? 

![2  Catgegories copy](https://user-images.githubusercontent.com/23431061/81390430-1d05f000-9124-11ea-9fe7-bc1a864f1013.jpg)

3.     How to place these icon in the middle.  as shown below

![3      Middle icon copy](https://user-images.githubusercontent.com/23431061/81390501-3b6beb80-9124-11ea-95fd-eadfc85d8139.jpg)

4.    Arabc Font is not installed correctly everywhere ..how to fix it 

![4  copy](https://user-images.githubusercontent.com/23431061/81390535-52124280-9124-11ea-84f1-7960f4cf768f.jpg)
![5  copy](https://user-images.githubusercontent.com/23431061/81390574-5fc7c800-9124-11ea-9efc-8864af071a0d.jpg)

![6](https://user-images.githubusercontent.com/23431061/81390591-65251280-9124-11ea-8ced-9978227ccd54.jpg)

Thank you for your cooperation

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/  - please don't share the purchase code as public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
Sorry, we should close this ticket as it could not be verified, please create the new one when you got enough purchased info - thank you!

**Comment by yosefasad** [comment]
I already opened another ticket 

Fluxstore 1.7.2 and 1.7.3 issues #3124

and Submit Private Files For Support Ticket.  through  http://private.inspireui.com/     .... 

I hope this is enough for activation for my support
