### ISSUE TITLE
Cart Stock Problem

### ISSUE THREAD

**Issue by erknertn** [inspireui/support#3086]
Hi,
Mstore Opencart.
No stock control in the basket. There is 1 product, but it can be added to more than one basket. It can be ordered out of stock. Each time you press the add to cart button on the product detail page, it increases the number without making stock control. I request you to fix this error.

**Comment by immortal-kid** [comment]
@minhcasi facing same issue in woocommerce version also

**Comment by minhcasi** [comment]
@erknertn 
We wanted to thank you for your patience during this busy time. We currently have reduced staff and a significantly higher volume of inquiries. We’re working as hard as we can to get to your request as soon as possible.

Could i know if you could able to run the project successful so far
