### ISSUE TITLE
Invalid Prices on Variation and Order Placement, Invalid Images of Products in cart

### ISSUE THREAD

**Issue by divyamsolanki9** [inspireui/support#3087]
![1](https://user-images.githubusercontent.com/45650554/81393645-58151d00-913e-11ea-8aff-719406321943.jpg)
![2](https://user-images.githubusercontent.com/45650554/81393713-724efb00-913e-11ea-8d27-b77598b34eea.jpg)

Image 1 & Image 2 both shows same price for different variation. PS: On Woocommerce prices are different

![3](https://user-images.githubusercontent.com/45650554/81393780-885cbb80-913e-11ea-99ab-ac663e889a3f.jpg)

Image 3 shows correct amount in cart but images are same for both product. PS: On wordpress image for both product are not same

![4](https://user-images.githubusercontent.com/45650554/81393855-a4605d00-913e-11ea-969c-6a0297cedae3.jpg)
![5](https://user-images.githubusercontent.com/45650554/81393863-a7f3e400-913e-11ea-994d-fbdbbb5b6c05.jpg)

Image 4 & 5 for verification on cart order and successful order placement

![6](https://user-images.githubusercontent.com/45650554/81393910-c063fe80-913e-11ea-9617-7df011fcb041.jpg)

Order price after order placement shows wrong amount

Another issue is on last step of order placement. After selecting Cash on Delivery, Next we click is Place order Button. Once clicked it stucks for a while, instead it should show some message or gif. Else user clicks on button multiple times. Which results in multiple order placement.

**Comment by minhcasi** [comment]
@divyamsolanki9 - could i know if you are testing on latest Flutter 1.7.3 - thank you!

**Comment by divyamsolanki9** [comment]
@minhcasi I just downloaded 1.7.3 and it's working on your default setup. I'll change basic configuration and re-compile. Will get back ASAP.

**Comment by divyamsolanki9** [comment]
@minhcasi Re-Config done. Upgrade done. 
Works Perfect. When can documentation be updated?
Looking for Loader Replacement.

**Comment by minhcasi** [comment]
@divyamsolanki9 - thank you for the confirmed 

We will upgrade the Loader Replacement on the next release - thank you!

**Comment by divyamsolanki9** [comment]
@minhcasi 
Flux Builder Works fine during designing. But after pasting code in config_en.json

It shows error.

Code ->
`{
  "HorizonLayout": [
    {
      "showMenu": true,
      "image": "https://i.imgur.com/A6GcShd.png",
      "showSearch": true,
      "layout": "logo",
      "showLogo": true
    },
    {
      "radius": 10,
      "items": [
        {
          "tag": -1,
          "padding": 15,
          "category": null,
          "image": "https://i.imgur.com/07GUL5W.png"
        }
      ],
      "layout": "bannerImage",
      "autoPlay": true,
      "isSlider": true,
      "design": "default"
    },
    {
      "height": 0.13,
      "isSafeArea": true,
      "padding": 20,
      "showSearch": false,
      "layout": "header_text",
      "fontSize": 20,
      "title": "Shop By Category"
    },
    {
      "items": [
        {
          "category": 39,
          "colors": [
            "#333333"
          ],
          "showText": false,
          "originalColor": true,
          "image": "https://i.imgur.com/7S3ynX9.jpg"
        },
        {
          "category": 37,
          "colors": [
            "#333333"
          ],
          "showText": false,
          "originalColor": true,
          "image": "https://i.imgur.com/E9sutnt.jpg"
        }
      ],
      "type": "image",
      "layout": "category",
      "size": 0.1,
      "wrap": false,
      "radius": 0
    }
  ],
  "Setting": {
    "MainColor": "#3FC1BE",
    "ProductListLayout": "list",
    "ProductDetail": "halfSizeImageType"
  },
  "TabBar": [
    {
      "icon": "assets/icons/tabs/icon-home.png",
      "layout": "home",
      "pos": 100
    },
    {
      "categoryLayout": "card",
      "layout": "category",
      "pos": 200,
      "icon": "assets/icons/tabs/icon-category.png"
    },
    {
      "layout": "search",
      "pos": 300,
      "icon": "assets/icons/tabs/icon-search.png"
    },
    {
      "icon": "assets/icons/tabs/icon-cart2.png",
      "layout": "cart",
      "pos": 400
    },
    {
      "layout": "profile",
      "pos": 500,
      "icon": "assets/icons/tabs/icon-user.png"
    }
  ],
  "Background": {
    "image": null,
    "height": 0.2,
    "color": "#E1F5FE",
    "type": null
  },
  "VerticalLayout": {
    "name": "Recent Collections",
    "layout": "pinterest",
    "image": ""
  }
}`


Output:
![Screenshot_1589105615](https://user-images.githubusercontent.com/45650554/81496408-27b3b700-92d5-11ea-9917-f30fe83e9510.png)

**Comment by minhcasi** [comment]
@divyamsolanki9 - it's fixed on latest Fluxbuilder 1.0.5, pls try to add this setting StickyHeader

<img width="816" alt="Screen Shot 2020-05-11 at 09 32 51" src="https://user-images.githubusercontent.com/1459805/81519139-63e52700-936a-11ea-9da9-694ab28d703f.png">

**Comment by divyamsolanki9** [comment]
@minhcasi Thank you. Will try that.
Just checked App Store. Still says Flux Builder version as 1.0.4
Any help regarding the update ?

**Comment by divyamsolanki9** [comment]
Also on homepage when we add category from fluxbuilder it asks for category code. Instead is it possible to pull all parent category from woocommerce

**Comment by minhcasi** [comment]
@divyamsolanki9 - new release 1.0.5 will be available on the end of this week, pls help us to fix it temporarily by the solution provide :)

**Comment by divyamsolanki9** [comment]
@minhcasi 
Sorry to bother. But is there any way to modify single product page. 
Keep the image fix, instead of getting it scrolled ?

**Comment by minhcasi** [comment]
@divyamsolanki9 - you could try to customize the file - thank you!

<img width="1241" alt="Screen Shot 2020-05-15 at 09 51 29" src="https://user-images.githubusercontent.com/1459805/82006285-a8860080-9691-11ea-9aef-09d5b5475d03.png">

**Comment by divyamsolanki9** [comment]
@minhcasi 
Sorry, but Rates issue in variation is still not solve. Rates are updating after clicking on add to cart though it should update if we click on variation item. As I couldn't upload screen recording here. So Uploading on GDrive and sharing link below->

https://drive.google.com/file/d/1OHtCGjVNg3pLoYtvl0LTrIRCwnVzOaP3/view?usp=sharing
Link is public.

Please check.

**Comment by minhcasi** [comment]
@divyamsolanki9 - it seems the source was customized, could you help to share the whole source code- we will investigate and let you know, please share via wetransfer.com  to our email support@inspireui.com

**Comment by minhcasi** [comment]
Or add my email to your private repository minhcasi@gmail.com - thank you!

**Comment by divyamsolanki9** [comment]
@minhcasi Shared via WeTransfer

**Comment by divyamsolanki9** [comment]
I re-downloaded from codecanyon. 

Now again it showing errors:
`Compiler message:

../../.pub-cache/hosted/pub.dartlang.org/rate_my_app-0.6.0+2/lib/src/dialogs.dart:272:17: Error: No named parameter with the name 'onRatingChanged'.

                onRatingChanged: (rating) {

                ^^^^^^^^^^^^^^^

../../.pub-cache/hosted/pub.dartlang.org/smooth_star_rating-1.1.0+1/lib/smooth_star_rating.dart:23:3: Context: Found this candidate, but the arguments don't match.

  SmoothStarRating({

  ^^^^^^^^^^^^^^^^

Target kernel_snapshot failed: Exception: Errors during snapshot creation: null

build failed.



FAILURE: Build failed with an exception.



* Where:

Script '/Users/divyam/Desktop/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 882



* What went wrong:

Execution failed for task ':app:compileFlutterBuildRelease'.

> Process 'command '/Users/divyam/Desktop/flutter/bin/flutter'' finished with non-zero exit value 1
`
