### ISSUE TITLE
fluxstore multi vendor android app _  Building apk release issues 

### ISSUE THREAD

**Issue by jonebiden** [inspireui/support#3088]
![ice_screenshot_20200508-151343](https://user-images.githubusercontent.com/65021423/81404725-d83b8280-913e-11ea-94ee-d0eb427f4c2a.png)

**build.gradle**

``def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

def keystorePropertiesRelease = new Properties()
def keystorePropertiesFileRelease = rootProject.file('key.properties')
if (keystorePropertiesFileRelease.exists()) {
    keystorePropertiesRelease.load(new FileInputStream(keystorePropertiesFileRelease))
}

def keystorePropertiesDebug = new Properties()
def keystorePropertiesFileDebug = rootProject.file('key-debug.properties')
if (keystorePropertiesFileDebug.exists()) {
    keystorePropertiesDebug.load(new FileInputStream(keystorePropertiesFileDebug))
}

android {
    compileSdkVersion 28

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        applicationId "com.inspireui.fluxstore.vendor"
        minSdkVersion 19
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
        resConfigs "en"
    }

    signingConfigs {
        release {
           
            if (System.getenv()["CI"]) { // CI=true is exported by Codemagic
                storeFile file(System.getenv()["FCI_BUILD_DIR"] + "/key.jks")
                storePassword System.getenv()["FCI_KEYSTORE_PASSWORD"]
                keyAlias System.getenv()["FCI_KEY_ALIAS"]
                keyPassword System.getenv()["FCI_KEY_PASSWORD"]
            } else {
                 keyAlias keystorePropertiesRelease['keyAlias']
                keyPassword keystorePropertiesRelease['keyPassword']
                storeFile file(keystorePropertiesRelease['storeFile'])
                storePassword keystorePropertiesRelease['storePassword']
            }
        }
        
        debug {
            keyAlias keystorePropertiesDebug['keyAlias']
            keyPassword keystorePropertiesDebug['keyPassword']
            storeFile file(keystorePropertiesDebug['storeFile'])
            storePassword keystorePropertiesDebug['storePassword']
        }
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.release
            //signingConfig signingConfigs.debug
        }

        debug {
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
    implementation 'com.google.firebase:firebase-core:16.0.9'
    implementation 'com.google.android.gms:play-services-auth:16.0.0'
    implementation 'com.google.firebase:firebase-auth:18.1.0'
    implementation 'com.android.support:multidex:1.0.3'
    implementation 'com.google.firebase:firebase-storage:18.1.0'
    implementation 'com.google.firebase:firebase-ads:17.2.0'
    implementation 'com.facebook.android:facebook-android-sdk:[5,6)'
}
apply plugin: 'com.google.gms.google-services'
googleServices { disableVersionCheck = true }
![ice_screenshot_20200508-151232](https://user-images.githubusercontent.com/65021423/81404708-cfe34780-913e-11ea-84a3-92a04e8eb266.png)

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ - please don't share the purchase code public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
Sorry, we should close this ticket as it could not be verified, please create the new one when you got enough purchased info - thank you!

**Comment by jonebiden** [comment]
Upload the Project Common Folder *
Only share the COMMON FOLDER as ZIP file from the project. These files will
help us reproduce the issue easier. Please do not share the whole source
code here. This folder will be saved privately and it will be removed after
we have solved your ticket.


Hi where can i find the    common folder    that you want  do you mean
create a zip whole source  file and than send as .  ???
