### ISSUE TITLE
No shipping methods shown at first attempt

### ISSUE THREAD

**Issue by yasernet1989** [inspireui/support#3089]
Step 1 (require): detail issues and screenshots
Hi,
After entering full address and click on (continue to shipping), no shipping methods will be shown.
But if i click (Back to address) then again (continue to shipping) it will be shown
can you help to solve that issue?

check this gif shot
![15889424732655592486173463197489](https://user-images.githubusercontent.com/64695299/81408119-5569f600-9145-11ea-8263-383809ad9bed.gif)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by lpzczar** [comment]
Me too

**Comment by minhcasi** [comment]
@yasernet1989 @lpzczar - our team is checking and will provide the solution shortly - thank you so much for reporting :)

**Comment by minhtruong315** [comment]
@yasernet1989 You can update loadShippingMethods function in widgets/frameworks/woocommerce/index.dart
```
void loadShippingMethods(context, Address address, bool beforehand) {
    final cartModel = Provider.of<CartModel>(context, listen: false);
    Future.delayed(Duration.zero, () {
      final token = Provider.of<UserModel>(context, listen: false).user != null
          ? Provider.of<UserModel>(context, listen: false).user.cookie
          : null;
      Provider.of<ShippingMethodModel>(context, listen: false)
          .getShippingMethods(
              address: address,
              token: token,
              checkoutId: cartModel.getCheckoutId());
    });
  }
```

**Comment by yasernet1989** [comment]
@minhtruong315 Solved. Thanks a lot dear.
