### ISSUE TITLE
Facing Home Screen Issue after Update to Release 1.7.3

### ISSUE THREAD

**Issue by kurkuteabhi** [inspireui/support#3090]
Home Screen is showing error as display in screen shot 
![Screenshot_20200508-183146](https://user-images.githubusercontent.com/43174699/81408641-38d8b880-915b-11ea-9747-573d09990b01.png)

**Comment by minhcasi** [comment]
Hi, please add this `"StickyHeader": false` to the config json to fix the issue - thank you!

<img width="717" alt="Screen Shot 2020-05-09 at 10 55 37" src="https://user-images.githubusercontent.com/1459805/81463405-9f091e00-91e3-11ea-8076-3019aff5bec6.png">

**Comment by kurkuteabhi** [comment]
Thanks..!

**Comment by minhcasi** [comment]
@kurkuteabhi - you could try to use the Inspector tool (https://docs.inspireui.com/fluxstore/customization/) to adjust the height of that widget + resize the font-style from image category list - thank you!

**Comment by harjono-flux** [comment]
> Hi, please add this `"StickyHeader": false` to the config json to fix the issue - thank you!

not works for me

**Comment by minhcasi** [comment]
@harjono-flux - could you try to use the default config_en json from download package, or send your config file here so that we could help to check - thank you!

**Comment by harjono-flux** [comment]
> @harjono-flux - could you try to use the default config_en json from download package, or send your config file here so that we could help to check - thank you!

before run, i already run flutter clean. same error

![Screen Shot 2020-05-11 at 19 12 15](https://user-images.githubusercontent.com/64935574/81556507-ff06ec80-93bc-11ea-8d83-4caac2eead6e.png)

**Comment by harjono-flux** [comment]
@minhcasi : how about this ? 

> > @harjono-flux - could you try to use the default config_en json from download package, or send your config file here so that we could help to check - thank you!
> 
> before run, i already run flutter clean. same error. my json config
> [myconfig_en.json.zip](https://github.com/inspireui/support/files/4609251/myconfig_en.json.zip)
> 
> ![Screen Shot 2020-05-11 at 19 12 15](https://user-images.githubusercontent.com/64935574/81556507-ff06ec80-93bc-11ea-8d83-4caac2eead6e.png)

**Comment by harjono-flux** [comment]
@kurkuteabhi 
try this

![Screen Shot 2020-05-16 at 08 05 01](https://user-images.githubusercontent.com/64935574/82105051-f3644e80-974b-11ea-92e2-df2b178ab03f.png)
