### ISSUE TITLE
Need Support to configure the app to Magento

### ISSUE THREAD

**Issue by coinbardevelop** [inspireui/support#3091]
Hello,
we purchased the app Fluxstore pro for wordpress, opencart and magento.
We installed the app in our develop enviroment, and could succesfully start it debug and production.
Then we installed on our magento2 platform the mstore plugin as described to the guide.
We tried to use CEBuilder too but it needs a react project meanwhile this is a flutter one and it has no package.json to link.
After this we modified the app files (config.dart and config_lang.json) to display the products from our store. Sadly when we call the products it returns always no elements.
If we call the magento2 native rest api we have the correct result instead.

What we missing to let it works with mstore?

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ - please don't share the purchase code public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
Sorry, we should close this ticket as it could not be verified, please create the new one when you got enough purchased info - thank you!
