### ISSUE TITLE
[Multi Vendor] Login not Redirecting to Checkout

### ISSUE THREAD

**Issue by jinuem** [inspireui/support#3092]
Step 1 (require): detail issues and screenshots
When User login from the cart for the checkout process. 
User getting the Authentication Token but it's not redirecting to Checkout.

<img width="725" alt="Screenshot 2020-05-08 19 24 35" src="https://user-images.githubusercontent.com/3512723/81412663-cf0fdd00-9161-11ea-92f1-64935bedbf8c.png">
TOKEN Printed in Debug Screen but not Redirecting to Checkout.
It's still loading. If I go back to the settings page, the user logged it. So Login works but redirection from cart to checkout is not working.
Version : 1.7.3

Reproduce Steps:

1. Use as Guest user
2. Add Products to Cart
3. Go to Cart and click Checkout (guest checkout is false)
4. Login Screen Apears -> Enter the Existing Login.
5. Token Received in the Debug Panel. but still loading and not redirecting.

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)
SUBMITTED

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by abqrinou** [comment]
i have same issues in Fluxstore WooCommerce ." login screen appears again even after the successful login"

**Comment by kenneth1690** [comment]
i have error

**Comment by jinuem** [comment]
@minhcasi any update?

**Comment by minhtruong315** [comment]
@jinuem can u upload your source code to git repo then add my email: minhtruong315@gmail.com?
I'll help u check and fix on it
Thanks

**Comment by jinuem** [comment]
@minhtruong315 
You already have access to my repo.
https://github.com/jinuem/CameronMarket/tree/1.7.3

Use Branch 1.7.3 which is the latest.

**Comment by minhtruong315** [comment]
@jinuem i checked your source code. it's not latest version. so it can't build on flutter 1.17

**Comment by jinuem** [comment]
@minhtruong315 I am using 1.7.3 and it can build on flutter 1.17.
Plz check the above comment, I told specifically to check the branch named "1.7.3" and also gave the link of the branch too. 

I can't move the code with defects to the master branch. So please check the 1.7.3 branch. its been 1 week this issue is not sorted out.

**Comment by minhtruong315** [comment]
@jinuem sorry I checked master.  let  me check again and let you know

**Comment by minhtruong315** [comment]
@jinuem I fixed your issue. please pull updates and check again. Then let me know the result.
Thanks

**Comment by jinuem** [comment]
@minhtruong315  thanks .
