### ISSUE TITLE
[FluxStore Pro] Some How To Questions 

### ISSUE THREAD

**Issue by bikostudio** [inspireui/support#3093]
**Hi @minhcasi 

Please I want to know how to:

1- add the add to cart icon and Wish list Heart icon to products at home?
2- How to add a border around the product in products list?

I want to be like this:

![www](https://user-images.githubusercontent.com/62074493/81414038-ab8b6900-9146-11ea-9d55-b0055868ce63.jpg)

3- Is it possible to replace the add to cart icon in product list view with word (add to cart) instead of Icon?

To be like this :

![ww](https://user-images.githubusercontent.com/62074493/81414208-e8576000-9146-11ea-8071-b63ea41f5b32.jpg)

4- Is it possible to Make the smart chat Icon to be always visible?

Thank you for your time**

**Comment by minhcasi** [comment]
@bikostudio - pls try your best to use the Inspector Tools to customize the UI - https://docs.inspireui.com/fluxstore/customization/#1-how-to-customize-any-ui-from-app

We could not support all of the "how-to" customizations at it is not included from our support scope - please try your best and let us know if you have any issues with the Inspector Tools

We could consider adding more layout to customize the product card view to Fluxbuilder as well

**Comment by minhcasi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update the Product Cart View](https://trello.com/c/1a07xUXr/36-update-the-product-cart-view)

**Comment by bikostudio** [comment]
Hi @minhcasi  Thank you for help. 
I still need to know can I add smart chat floating Icon to be visible in any page for example : static page, external link page ?

![2020-05-10_072658](https://user-images.githubusercontent.com/62074493/81491551-07153e00-9290-11ea-81da-cb72acb9f23e.jpg)

thank you

**Comment by bikostudio** [comment]
To show add to cart and wishlist icons in home products list : 

go to file : \lib\widgets\product\product_card_view.dart

and turn this.showHeart  and this.showCart  from false to true

![2020-05-10_171410](https://user-images.githubusercontent.com/62074493/81503053-da8a1200-92e1-11ea-80a0-9a8be3b75d32.jpg)
