### ISSUE TITLE
FluxStore Pro 1.7.3     blue screen after changing the language to arabic

### ISSUE THREAD

**Issue by yosefasad** [inspireui/support#3095]
on the default settings as downloaded from the Fluxstore 1.7.3 package 
when I change the language to arabic ..I face the blue screen below 

<img width="288" alt="Screen Shot 2020-05-08 at 10 00 28 PM" src="https://user-images.githubusercontent.com/23431061/81439869-c1fde880-9177-11ea-9789-a0c673518c4f.png">

How to solve this issue ? 
Thank you for your cooperation 

<img width="1147" alt="79042008-c082e400-7bfc-11ea-8976-8f045766b7f9" src="https://user-images.githubusercontent.com/23431061/81439909-d641e580-9177-11ea-9192-3f87464b7e22.png">

**Comment by minhcasi** [comment]
@yosefasad - pls move to the same ticket #3085
