### ISSUE TITLE
fluxstore Pro 1.7.2 series of questions for configuration

### ISSUE THREAD

**Issue by danielito-1** [inspireui/support#3096]
Hello,
greetings and thanks for the effort with the application I am very happy it is a good product.

I'm about to finish it but before I have a series of questions I hope you help me

Thank you again

-the purchase record is sent by private-

i start:

#1:  **where do i find this image to change it**

![imagen ajustes](https://user-images.githubusercontent.com/63943871/81441614-b1c61900-9137-11ea-991b-d896fdc0418b.jpg)

#2:  
**I am from Colombia and I want to sell exclusively in my country.
How can I change a single country for the sms login**

![sms login2](https://user-images.githubusercontent.com/63943871/81441742-e9cd5c00-9137-11ea-94f7-fd8ea3c8f6d5.jpg)

![sms login](https://user-images.githubusercontent.com/63943871/81441758-f18d0080-9137-11ea-990b-c2d588bbe1b2.jpg)

#3:  
**the order note is not received on woocomerce
What I can do**

![nota pedido](https://user-images.githubusercontent.com/63943871/81442006-652f0d80-9138-11ea-81f1-30935a5b65c7.jpg)

#4:  
**I just want to sell in my country
How to eliminate the others and by default choose Colombia?**

![pais y provincia](https://user-images.githubusercontent.com/63943871/81442138-ab846c80-9138-11ea-8439-bf02756a4611.jpg)

#5:
**I set the default local currency and language
but I don't want the user to see these options how to i can disable it**

![moneda idioma](https://user-images.githubusercontent.com/63943871/81442350-08802280-9139-11ea-8d74-f0bd4d07175e.jpg)

#6: 

**in recent view when i click
this problem occurs and cannot be added to the cart
What I can do?**

![vista reciente](https://user-images.githubusercontent.com/63943871/81442673-a7a51a00-9139-11ea-9d1b-cfdf6363fbc8.jpg)

![vista reciente2](https://user-images.githubusercontent.com/63943871/81442685-ae339180-9139-11ea-8def-3fb599cae3a1.jpg)

#7: 

**where can i change the general color**

![vista](https://user-images.githubusercontent.com/63943871/81442943-1da98100-913a-11ea-816e-15c203fd8ba6.jpg)

#8: 

**how to disable these designs**

![vista2](https://user-images.githubusercontent.com/63943871/81443086-56e1f100-913a-11ea-9ae3-85f268ae7e87.jpg)

**### Thank you,

I hope it can be useful to other colleagues.**

**Comment by kenneth1690** [comment]
Escribame por privado y le ayudo a configurar eso kennethhdc@gmail.com 

No es complicado

**Comment by danielito-1** [comment]
Hello🙋‍♂️

**Comment by kenneth1690** [comment]
Hello?, you want help?

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ 

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
Sorry, we should close this ticket as it could not be verified, please create the new one when you got enough purchased info - thank you!

**Comment by minhcasi** [comment]
verified!

**Comment by minhcasi** [comment]
@danielito-1 
Please try to use this Inspector Tools so that you could fully control to customize the UI - https://docs.inspireui.com/fluxstore/customization/ - it will resolve your question 

1. use Inspector Tools
2. you could customize this file https://tppr.me/tkcZC 
3. fixed on latest 1.7.3
4. ref: https://docs.inspireui.com/fluxstore/multi-language/#country-settings
5. refer: https://docs.inspireui.com/fluxstore/multi-language/#how-to-set-a-language-as-the-default-language
6. fixed 1.7.3
7. config_en.json file 
8. use Inspector Tools
