### ISSUE TITLE
Warning: FormatException: Unexpected character (at chaacter1)

### ISSUE THREAD

**Issue by opooletech** [inspireui/support#3097]
Step 1 (require): detail issues and screenshots
Warning: FormatException: Unexpected character (at chaacter1)
Dear sir having issue in signin signup please help to resolve the issue
even everything correct connect
Be sure you have pasted the SHA-1 key to your Firebase setting. Check more in https://docs.inspireui.com/fluxstore/common-issues/ - thank you
Everything done even purchase key enter also in mstore
but still having issue in signin or signup product show in app
![image](https://user-images.githubusercontent.com/8824264/81444724-0ea1ed80-9191-11ea-9f72-822f3474df97.png)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

Warning: FormatException: Unexpected character (at chaacter1)
Dear sir having issue in signin signup please help to resolve the issue
even everything correct connect
Be sure you have pasted the SHA-1 key to your Firebase setting. Check more in https://docs.inspireui.com/fluxstore/common-issues/ - thank you
Everything done even purchase key enter also in mstore
but still having issue in signin or signup product show in app
*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by opooletech** [comment]
Dear Sir please Give my Any Solution Still  waiting

**Comment by trunghieuvn** [comment]
you can follow document get SHA1 key setup for console firebase project in here: https://github.com/inspireui/support/wiki/Setup-login-with-Google#3-setup-for-android  
p/s: because sha1 key will link to 1 package name in project for you.

**Comment by opooletech** [comment]
Dear Sir not gmail or facebook login even not working simple login from website database even not signin or signup

**Comment by opooletech** [comment]
kasheesstore.com/wp-content/plugins/mstore-api/mstore-api.php
This error showing in website site

**Comment by opooletech** [comment]
please need solution i really upset please help

**Comment by minhcasi** [comment]
@opooletech - could you help to share the screenshot on this comment, it seems the issue from mstore-api - you could try to disable the debug mode from wp-config.php (Wordpress side)

<img width="928" alt="Screen Shot 2020-05-10 at 09 30 50" src="https://user-images.githubusercontent.com/1459805/81489555-f1f4db00-92a0-11ea-8f6d-f173862fc788.png">

**Comment by unaluslusoy** [comment]
@minhcasi  hi Warning: FormatException: Unexpected character (at chaacter1) 
The same problem is that I did not want to open a new support request.
![image](https://user-images.githubusercontent.com/31100257/81572859-6cf6e800-93ac-11ea-8998-9306abf65ae5.png)

**Comment by minhtruong315** [comment]
@opooletech can u upload your source code to github then invite me: minhtruong315@gmail.com
I will help u check and fix on it
Thanks

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
