### ISSUE TITLE
FluxStore - opencart - Product with options and filtering issues.

### ISSUE THREAD

**Issue by harrisbaitalrayan** [inspireui/support#3100]
Step 1 (require): detail issues and screenshots

1) Product with options :

The price of the product keeps on increasing if add to cart for a product with options. More we add the product to the cart, the more the price of the product keeps increasing.

<img width="294" alt="Screen Shot 2020-05-09 at 12 25 39 AM" src="https://user-images.githubusercontent.com/13076524/81452617-63953200-9198-11ea-8602-7b9a0ebca7b1.png">
<img width="294" alt="Screen Shot 2020-05-09 at 12 26 12 AM" src="https://user-images.githubusercontent.com/13076524/81452639-73147b00-9198-11ea-8bf0-1e7236b17300.png">
<img width="294" alt="Screen Shot 2020-05-09 at 12 27 06 AM" src="https://user-images.githubusercontent.com/13076524/81452656-7d367980-9198-11ea-8dc8-7015d8e8abc9.png">
<img width="294" alt="Screen Shot 2020-05-09 at 12 27 39 AM" src="https://user-images.githubusercontent.com/13076524/81452669-858eb480-9198-11ea-85db-19beb4312ca5.png">

2) Price Filter  :
Applying price filter no products returned. The initial category selection is lost with applying filter.
Price filter widget is difficult to select.
Better to have a simple filtering UI

<img width="294" alt="Screen Shot 2020-05-09 at 12 31 12 AM" src="https://user-images.githubusercontent.com/13076524/81452696-950dfd80-9198-11ea-9fee-5366cd3b9487.png">

<img width="294" alt="Screen Shot 2020-05-09 at 12 33 00 AM" src="https://user-images.githubusercontent.com/13076524/81452703-993a1b00-9198-11ea-9aea-eb349b2c4d2f.png">

<img width="294" alt="Screen Shot 2020-05-09 at 12 33 09 AM" src="https://user-images.githubusercontent.com/13076524/81452715-9dfecf00-9198-11ea-8f15-9b90a5679c16.png">

3) Payment option required :
Even if Cash on delivery is automatically selected, it still prompts for selecting payment option
![IMG_5163](https://user-images.githubusercontent.com/13076524/81452804-e8804b80-9198-11ea-9847-01340674a39d.PNG)

4) Customer notes:
Customer notes in the review screen is not updated in the Opencart admin when viewing the order.

![IMG_5164](https://user-images.githubusercontent.com/13076524/81452894-29786000-9199-11ea-9428-08f4c2c6f866.PNG)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhcasi** [comment]
@minhtruong315 - pls help to investigate the issue

**Comment by minhtruong315** [comment]
Hi @harrisbaitalrayan can u record screen for issue: 1,2
issue  3,4 are working well on my source code. what is Fluxstore version you're using?

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!

**Comment by karthick-thomsun** [comment]
I am having the exact issue. The price get added for each and every option. 

Unfortunately though fluxstore is well developed it has flaws. For example, there is no support for adding quantity for each options in fluxstore.

<img width="1296" alt="Screenshot 2020-08-18 at 4 11 09 PM" src="https://user-images.githubusercontent.com/69500356/90503670-7347ed80-e16d-11ea-8bc4-8b411319fde5.png">
