### ISSUE TITLE
Products on APP are not updated 

### ISSUE THREAD

**Issue by gostore-aicom** [inspireui/support#3101]
The APP is working as expected except for retrieving the products from Shopify. The products on the APP are not updated, as we add new products to Shopify, these don't appear on the APP.
Check the attached images, these show the difference in products on the APP vs Shopify.

![image](https://user-images.githubusercontent.com/37650345/81451410-1b244700-918d-11ea-89bb-aa36d8d6ffbf.png)
![image](https://user-images.githubusercontent.com/37650345/81451428-24adaf00-918d-11ea-840a-1582d00fd63f.png)

Thanks

**Comment by luyx2412** [comment]
Hi @gostore-aicom You can use pull to refresh to load latest products in your app.

![image](https://user-images.githubusercontent.com/8909619/81465848-5e1b0480-91f7-11ea-821d-e5e70f55d706.png)

Thanks

**Comment by gostore-aicom** [comment]
Hi ,

Yes I did that, that is trivial :)

However the products are not updated, as you see in the screenshot, in this specific collection, the APP shows two products, where on the Shopify there are 12 products.

Can you assist us with troubleshooting this?

**Comment by luyx2412** [comment]
Hi @gostore-aicom Can you send me the AppConfig.json and Config.js file?

Thanks

**Comment by gostore-aicom** [comment]
Hi All,

Here you go, the files are here:
https://drive.google.com/file/d/14U-n-X7hlZ9EFZRlWvYFQ5v8OwxUA73_/view?usp=sharing

Thanks
Ihab

**Comment by luyx2412** [comment]
Hi @gostore-aicom please send to inspireui.team@gmail.com. We need the private it.

Thanks

**Comment by gostore-aicom** [comment]
This is done, I've shared it with inspireui.team@gmail.com

Regards
Ihab

**Comment by luyx2412** [comment]
HI @gostore-aicom Can i know specific your collection id? Because your shop have many categories. 

Thanks

**Comment by gostore-aicom** [comment]
Hi Guys,

The issues happen on all categories, you can choose any of them. Take for
example this one: 14908828647488

Thanks
Ihab

**Comment by gostore-aicom** [comment]
Hi Guys,

Any update on this?

Thx
Ihab

**Comment by luyx2412** [comment]
Hi @gostore-aicom Sorry about reply you. Please send your website information via inspireui.team@gmail.com I need it for investigate.

Thanks

**Comment by gostore-aicom** [comment]
I just sent it

Regards
Ihab

**Comment by luyx2412** [comment]
HI @gostore-aicom I did not your email? Can you send again with subject 3101.

Thanks

**Comment by gostore-aicom** [comment]
Hi
I just did, let me know if you did not receive it.

Ihab

**Comment by gostore-aicom** [comment]
Did you have the chance to look at it?

**Comment by luyx2412** [comment]
Hi @gostore-aicom I saw your email but could not any information. Please invite inspireui.team@gmail.com to your shopify, i need investigate in admin dashboard. 

Thanks

**Comment by gostore-aicom** [comment]
Hi Inspireui/Support,

You requested the store URL and I provided that. Can you let me know what
is needed from the admin dashboard? I will provide it.
This is a live store for one of my customers and I cant provide you access.
However I can provide you with any information you need to fix this issue

Can you please expedite this? This is taking too much time before the
actual troubleshooting.

Ihab

**Comment by gostore-aicom** [comment]
Any updates?

**Comment by luyx2412** [comment]
Hi @gostore-aicom Please give the name category which is smallest items in your website. I will investigate about the issue. Because your website have many products, so i could not know any limit.

Thanks

**Comment by gostore-aicom** [comment]
Here is the collection path: /collections/headpieces-accessories-girls

**Comment by gostore-aicom** [comment]
Hi Support,

This case has been opened for 13 days. I am really disappointed by the quality of support you provide. It is fine that you take all the time you need to troubleshoot any issue, but so far the past 13 days were spent trying to explain to you a very simple issue and so far no progress has been made.

If you don't want to provide support, please let your customers know, and save our time.

Ihab

**Comment by luyx2412** [comment]
hi @gostore-aicom Sorry about reply you late. But i lack of the information to investigate. So can you give me the specific collection id which smallest items.

Thanks

**Comment by gostore-aicom** [comment]
Collection ID: 136961359936
URL:  {store_name}.myshopify.com/collections/hats-2

**Comment by gostore-aicom** [comment]
Any updates?

**Comment by luyx2412** [comment]
HI @gostore-aicom Please give me the collection id same the screenshot. I don't understand your language, so it is very difficult to investigate 
![image](https://user-images.githubusercontent.com/8909619/83022538-df76f180-a055-11ea-94aa-82bb3b54fbf6.png)

Thanks

**Comment by gostore-aicom** [comment]
Hi,

I used a similar query, and added "handle" to look for "hats-2", as I sent you before:
Collection ID: 136961359936
URL: {store_name}.myshopify.com/collections/hats-2

See my screen shot:
![Screen Shot 2020-05-27 at 5 28 33 PM](https://user-images.githubusercontent.com/37650345/83033325-a764b400-a03f-11ea-9732-156aab7431ee.jpg)

**Comment by luyx2412** [comment]
Hi @gostore-aicom I think you give me another website, so i could not see any products 
![image](https://user-images.githubusercontent.com/8909619/83034709-c0329100-a062-11ea-819d-04b8b5ae608b.png)
![image](https://user-images.githubusercontent.com/8909619/83034705-be68cd80-a062-11ea-85e2-5b07a9fbc6a4.png)

So please send me right your AppConfig.json via inspireui.team@gmail.com

Thanks

**Comment by gostore-aicom** [comment]
This is the correct hostname, can you send me the full API query I will test on my side

**Comment by luyx2412** [comment]
Hi @gostore-aicom This is query
`
{
  collections(first: 100, query: "hats") {
    edges {
      node {
        id
        handle
        products(first: 100) {
          edges {
            node {
              title
              id
            }
          }
        }
      }
    }
  }
}`

Thanks

**Comment by gostore-aicom** [comment]
It works fine:

[image: image.png]

Can we have a zoom call to discuss this? I think it will be faster. Can you?

Thanks

**Comment by luyx2412** [comment]
Hi @gostore-aicom Sorry we could not discuss via zoom or something like that, please share me your screenshot. Let me investigate about it.

Thanks

**Comment by gostore-aicom** [comment]
Ok, as you can see here in the screenshot this works fine:
[image: image.png]

**Comment by luyx2412** [comment]
HI @gostore-aicom Sorry i saw any screenshot, can you share me again.

Thanks

**Comment by luyx2412** [comment]
Closed!
P/S: Feel free to reopen the issue, or create new issue.
