### ISSUE TITLE
Error Releasing Latest version 1.7.3 on Appstore

### ISSUE THREAD

**Issue by sercada** [inspireui/support#3102]
Step 1 (require): detail issues and screenshots
Hi, after successfully doing the archive command on Xcode, I get the following error when I try to publish the app:

![Screen Shot 2020-05-08 at 6 01 58 PM](https://user-images.githubusercontent.com/24389792/81456001-8e5e9680-9156-11ea-8007-f3fdcecafb8c.jpg)

I have successfully published version 1.7.2 so I have tried several times with 1.7.3 without success. I don’t really know what to do, the info.plist is on the iOS folder. 

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhcasi** [comment]
@sercada - noted with investigating - thank you!

Did you store your previous info.plist on git to and compare the difference with the latest one?

**Comment by sercada** [comment]
@minhcasi Unfortunately I didn’t keep a copy.

**Comment by sercada** [comment]
@minhcasi  There was an error with the provisioning certificates and profile, it’s weird because it didn’t say so, it was referring to the Info.plist but after deleting all certificates and provisioning profiles I managed to successfully update the new version on the App Store. 

I’m closing this ticket as it’s been solved on my end. 

One more thing before we close it. I have requested access to the gitlab repository a couple of times but haven’t got access. Can you help?

**Comment by minhcasi** [comment]
@sercada - could you share your email and Envato username so that we could have a check the invitation - thank you!

**Comment by minhcasi** [comment]
sent invitation 🎉
