### ISSUE TITLE
Generating lots of errors when gradle build starts

### ISSUE THREAD

**Issue by shamseerazeez** [inspireui/support#3103]
Step 1 (require): detail issues and screenshots

Hello, I recently purchased FluxStore and installed all required plugins and editors and flutter doctor says no error found. Unfortunately when I run gradle task (to preview in simulator) I get a huge number of errors starts like below

-----------------------
Running Gradle task 'assembleDebug'...

Compiler message:
lib/screens/home/onboard_screen.dart:22:34: Error: Getter not found: 'kLoginSetting'.
  final isRequiredLogin = config.kLoginSetting['IsRequiredLogin'];
                                 ^^^^^^^^^^^^^
lib/app_init.dart:92:9: Error: The getter 'kLoginSetting' isn't defined for the class '_AppInitState'.
 - '_AppInitState' is from 'package:fstore/app_init.dart' ('lib/app_init.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'kLoginSetting'.
    if (kLoginSetting['IsRequiredLogin'] && !isLoggedIn) return LoginScreen();
        ^^^^^^^^^^^^^
lib/models/advertisement.dart:23:12: Error: Getter not found: 'kAdType'.
      case kAdType.googleBanner:
           ^^^^^^^

and somany errors are displayed. All are related to KLoginSetting
-----------------------
<img width="1280" alt="Screen Shot 2020-05-09 at 3 21 28 AM" src="https://user-images.githubusercontent.com/16466771/81456891-3307c500-91a5-11ea-9068-6d29f411a056.png">

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhcasi** [comment]
@shamseerazeez - pls help to use the default config from the download package and only change your `serverConfig`, or you could copy this code from the original one - https://tppr.me/j2qkF

**Comment by minhcasi** [comment]
@shamseerazeez - also try to clean the cache issue as well 👍 https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

**Comment by shamseerazeez** [comment]
Hi, thank you for the prompt response. I tried all the method that you
suggested above. Still getting the same error. Can I share my
teamweaver login with you. From my end all settings are correct. Please
find attached flutter doctor details. Thankyou


Thanks & Regards,

*Shamseer Azeez*

*This message may contain information that is privileged, confidential and
exempt from disclosure under applicable law. If you are not the intended
recipient (or authorized to act on behalf of the intended recipient) of
this message, you may not disclose, forward, distribute, copy, or use this
message or its contents. If you have received this communication in error,
please notify me immediately by return e-mail and delete the original
message from your e-mail system.*
