### ISSUE TITLE
1.7.3 > Woocommerce Variant Settings Ignored + Price Wrong

### ISSUE THREAD

**Issue by abstractionltd** [inspireui/support#3104]
![](https://screenshot.click/l5ykb-rb07a.png)

The variant in woocommerce is set to NOT have default values selected. The app is ignoring this setting and selecting random options and then showing the incorrect price even based on the variant it selects.

In my screenshot it has selected Regular X Regular x Yes options which should have a cost of $5.5, not $6.0. 

![](https://screenshot.click/qyjqz-pv8w8.png)

If you then add that random selection to the cart it is not even adding the same product as what has been selected.

**Comment by minhcasi** [comment]
@abstractionltd - pls help to raise this issue to your previous ticket conversation #3057 - thanks

**Comment by abstractionltd** [comment]
I have added this thread to that ticket but there has been no reply. I would appreciate it if someone could update me on how to fix this?
