### ISSUE TITLE
I need help with these problems

### ISSUE THREAD

**Issue by orez3** [inspireui/support#3105]
1.- 1.- when pasting the fluxbuilder code I always get this error
![error al pegar el diseño de fluxbilder](https://user-images.githubusercontent.com/32586190/81463413-148ed300-917f-11ea-8203-19a1de93db74.jpg)

2.- when I try to add a new product from the app it always stops and doesn't publish anything
![no caraga producto](https://user-images.githubusercontent.com/32586190/81463420-2bcdc080-917f-11ea-8896-de889e3b9faa.jpg)

3.- I can't get it to show me the products in fluxbuilder and when I switch to the app it doesn't show me anything either
![no carga productos fluxbulder](https://user-images.githubusercontent.com/32586190/81463434-3e47fa00-917f-11ea-910b-4813260932ef.jpg)

4.- the main screen doesn't work, it doesn't show information of the products and categories
![pantalla principal no carga nada](https://user-images.githubusercontent.com/32586190/81463440-46a03500-917f-11ea-8778-916781becd68.jpg)

I am using WCFM

**Comment by orez3** [comment]
I add the files from the common folder
[common.zip](https://github.com/inspireui/support/files/4602601/common.zip)

**Comment by minhcasi** [comment]
@orez3 - Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
@vumanhsn97 - please help to investigate 😊

**Comment by vumanhsn97** [comment]
1. Add StickyHeader: true/false in Settings https://tppr.me/WOvZ
2. post default using type: dokan
3 - 4: keys are not correctly. So I can't check it. Can you share it again?

**Comment by orez3** [comment]
now he doesn't show me the categories

**Comment by vumanhsn97** [comment]
@orez3 Can you share your config again? I can't check your website because consumerKey and consumerSecret are not correctly.

**Comment by orez3** [comment]
hello several of the previous errors I solved but new ones are coming out now
1.- When I try to register a user or a seller, I always get the legend Please agree with our terms

2. If I make a purchase, it does not reduce the quantity of the stock

3.- i can't add new products and it doesn't load the images

4 .- when making the purchase in the shipping method always comes to me that is free and does not respect the price established by the sellers

here i send you the correct configuration file
[common.zip](https://github.com/inspireui/support/files/4619019/common.zip)

**Comment by vumanhsn97** [comment]
@orez3 
1. Replace file in lib/screens/users/registration.dart to 
[registration.dart.zip](https://github.com/inspireui/support/files/4626987/registration.dart.zip)
2. Update in feature
3. Update this line in lib/services/woo_commerce.dart look like https://tppr.me/j12K3 (Solve categories not showing problem)
4. Shipping method can't edit by the sellers

**Comment by orez3** [comment]
Thank you, it all worked out perfectly for me.

only 2 suggestions for a future update with WCFM the seller can set his own costs for the shipments and choose which kind of shipping he wants to give either free of charge, shipping cost and pick up in the shop.

like in the registration when you register from your app this generates the default user and does not respect the type of membership you have in the shop like the type of roles you set up when you registered

all this can be done in the WCFM
