### ISSUE TITLE
Doesn't open the news

### ISSUE THREAD

**Issue by lpzczar** [inspireui/support#3106]
hi excellent day.  I have some bugs.

1)My news app doesn't open the news.  When I want to open a news, a black screen appears and throws the following error (image1) - “ There are multiple heroes that share the same tag within a subtree.”

 Everything works perfectly but the news does not open.  Even when I want to log in, I get a black screen.  how do I solve it?

2) Some news shows me an error and shows me a blue screen that says "Error in invalid argument (source)" - image2

Help me please!

![2A338B61-B3D4-418E-AB7B-E77D5FB14E66](https://user-images.githubusercontent.com/19940455/81465047-9df8d200-918c-11ea-91b2-6d175087f038.jpeg)
![7B6B6E5A-31BD-40DE-BC41-286DD4167DEE](https://user-images.githubusercontent.com/19940455/81465108-195a8380-918d-11ea-9beb-034aa0c4b6b4.jpeg)

**Comment by minhcasi** [comment]
@lpzczar 

Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
Sorry, we should close this ticket as it could not be verified, please create the new one when you got enough purchased info - thank you!
