### ISSUE TITLE
fluxstore 1.7.2 Why does this happen?

### ISSUE THREAD

**Issue by danielito-1** [inspireui/support#3107]
Why does this happen?

I make changes to config.dart or some other element

and it doesn't update when i open simulator or create apk

after a few hours it is already seen

**Comment by minhcasi** [comment]
@danielito-1 - it could be the cache issue on Flutter, pls try this script - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

Also, please help us to post your all comment to one ticket #3096
