### ISSUE TITLE
Request: Integration with 2Checkout

### ISSUE THREAD

**Issue by sercada** [inspireui/support#3108]
Hi Guys I love your app, it’s an amazing flexible project.

I’d like to know how to setup native payments with 2Checkout, can you add this feature on future releases ? 

https://knowledgecenter.2checkout.com/API-Integration/Start-using-the-2Checkout-API

**Comment by minhcasi** [comment]
@sercada - thank you so much for your suggestion - we will  investigate this new feature

**Comment by minhcasi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Integrate with 2Checkout](https://trello.com/c/EUe6UsHH/37-integrate-with-2checkout)

**Comment by minhcasi** [comment]
moved to the backlog for the team investigating
