### ISSUE TITLE
Problems building IOS Fluxstore

### ISSUE THREAD

**Issue by iamglicious** [inspireui/support#3109]
Hi,

so yes I checked the bundle id. I have created a new one.
Also i download the latest version used the script and changed the bundle id.

But now I get a new error. I have used the stable flutter, double checked the signature but now. Im working on this for almost 2 weeks. Double checked everything.

So even if i started fresh still having issues. So please let me know what I can do.
Im willing to start over again. 

Compiler message:
    ../../gregoryvrede/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image-0.7.2/lib/src/gesture/extended_image_slide_page_route.dart:333:9: Error: No named parameter with the name
    'animation'.
            animation: animation,
            ^^^^^^^^^
    ../../gregoryvrede/flutter/packages/flutter/lib/src/cupertino/route.dart:435:3: Context: Found this candidate, but the arguments don't match.
      CupertinoFullscreenDialogTransition({
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
    build failed.
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

Encountered error while building for device.
gregoryvrede@MacBook-Pro-2 iamerch % 
[pdfr.pdf](https://github.com/inspireui/support/files/4600892/pdfr.pdf)

**Comment by Oh8Digital** [comment]
did you manage to get it fixed? i have the same problem

**Comment by trunghieuvn** [comment]
![](https://user-images.githubusercontent.com/19247680/81473946-6a6d8480-922c-11ea-8d10-13bb3e0b08aa.png)

**Comment by trunghieuvn** [comment]
please share me version from you  
\`\`\`  
flutter --version  
\`\`\`

**Comment by iamglicious** [comment]
Flutter 1.17.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision e6b34c2b5c (7 days ago) • 2020-05-02 11:39:18 -0700
Engine • revision 540786dd51
Tools • Dart 2.8.1

**Comment by iamglicious** [comment]
> did you manage to get it fixed? i have the same problem

no still not

**Comment by minhcasi** [comment]
@iamglicious - Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by iamglicious** [comment]
> @iamglicious - Thank you for the feedback.
> 
> Please help us to submit this form and fill all required info to continue with the support - [http://private.inspireui.com/ -](http://private.inspireui.com/%C2%A0-) please don't share the purchase code or screenshot public here as another user will use it for activation.
> 
> We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

Hi,

I already had a case open were i filled in all information #3028
But it was closed with our an resolution so ypu want me to fill it in again ?

**Comment by iamglicious** [comment]
I filled it in again

**Comment by minhcasi** [comment]
@iamglicious - thank you for a response quickly 
Please help to try to clean up the cache https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1 and using the latest release from Fluxstore 1.7.3 to fix this issue (there is the extended_image issus on Flutter 1.17 that fixed on this release)

You may require to run `flutter upgrade --force` to update your local flutter sdk, it seems it is using from previous version

**Comment by iamglicious** [comment]
> @iamglicious - thank you for a response quickly
> Please help to try to clean up the cache https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1 and using the latest release from Fluxstore 1.7.3 to fix this issue (there is the extended_image issue on Flutter 1.17 that fixed on this release)
> 
> You may require to run `flutter upgrade --force` to update your local flutter sdk, it seems it is using from the previous version
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/0aeb324a3445c618a67c0140da8216d28af304fa/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f696d616765732f6d6f64756c65732f67697374732f676973742d6f672d696d6167652e706e67"><img alt="" height="14" src="https://camo.githubusercontent.com/040b5519c6d1891329f5f6d3e511003657131cf2/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> Gist**[These are common issues on Flutter and solutions to fix](https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1)**These are common issues on Flutter and solutions to fix - Flutter Clean.md

Thank you for the quick response. I just download again from codecanyon or are you going to give access to the git repo. Please let me know where to find the latest release and how I can make sure im on the latest version.

**Comment by iamglicious** [comment]
Still having issues let me know how i can check if im on the latest release.

**Comment by minhcasi** [comment]
@iamglicious - the release 1.7.3 is the latest version of Fluxstore

Regarding to Flutter, you could try to run "flutter doctor" - the latest version should be 1.17.x stable

**Comment by iamglicious** [comment]
Thank you but how can I collect the latest release because I still don't have access to the github account

**Comment by minhcasi** [comment]
@iamglicious - please help to submit this form https://docs.google.com/forms/d/e/1FAIpQLSeuBqUkScy42V7KKhfNPj0fl581anrB1mWkbMa3p2WQt7fhfw/viewform

You could also download the latest release on http://codecayon.net/downloads

**Comment by iamglicious** [comment]
The problem is solved to made some updates for the image and put it on 0.7.3. 
After that the problem was solved
