### ISSUE TITLE
[ListApp] listing a photo, not show and then clicking on any listing name give me error 

### ISSUE THREAD

**Issue by pramji** [inspireui/support#311]
**Required Info (please complete the following information):**
 - Product: ListApp
 - Your Purchased Code: e4a91710-0507-4072-9472-b507d45e1df2
(we may not reply if you are not our customer)

**Describe the bug**
hello listing a photo, not show and then clicking on any listing name give me error same in the picture link https://imgur.com/a/MHzbbPN

[con.zip](https://github.com/inspireui/support/files/2872657/con.zip)

**Comment by minhcasi** [comment]
Noted for checking - thank you!

**Comment by thangvo9x** [comment]
hi. First, Thanks for your purchase. Try check on your site at domain/wp-json/wp/v2/job_listing has listing_data fields. Try check plugin works.

**Comment by pramji** [comment]
hello 
not working 
http://www.interactive-guides.com/domain/wp-json/wp/v2/job_listing
give me email to send site cpanel to check if you can

**Comment by pramji** [comment]
https://www.interactive-guides.com/wp-json/wp/v2/job_listing
here working

**Comment by pramji** [comment]
@thangvo9x help please
