### ISSUE TITLE
Fluxstore Pro for Magento 2.3.4 problem

### ISSUE THREAD

**Issue by bundy29** [inspireui/support#3110]
Hi Support
I alreaday connnect to Magento 2.3.4 but found main feature error
 1) error add to cart and product attribute 
<img width="402" alt="error_add_cart_arrt" src="https://user-images.githubusercontent.com/16270929/81467979-9f66e080-9206-11ea-8ee2-0cad318f5d71.png">
2) product attribute filter not work
<img width="191" alt="error_arritube_filter" src="https://user-images.githubusercontent.com/16270929/81467986-ab52a280-9206-11ea-9526-602e3087b4c6.png">
3) order history error
<img width="193" alt="error_order_history_not_show" src="https://user-images.githubusercontent.com/16270929/81467991-af7ec000-9206-11ea-8542-b45e4962cb54.png">
Pls help to check and fix it?
Thank

**Comment by minhcasi** [comment]
@bundy29 - Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
verify 🎉

@trunghieuvn - pls help to investigate this issue

**Comment by minhtruong315** [comment]
@bundy29 what is the Fluxstore version  you're using?

**Comment by bundy29** [comment]
Hi support
Fluxstore Pro 1.7.3

**Comment by bundy29** [comment]
Hi support
Fluxstore Pro 1.7.3 and Magento 2.3.4 
Thank

**Comment by minhtruong315** [comment]
@bundy29 can u upload your source code to git repo then add my email: minhtruong315@gmail.com

**Comment by minhtruong315** [comment]
@bundy29 let me know when you invited
Thanks

**Comment by bundy29** [comment]
Hi minhtruong315
i create private https://github.com/bundy29/Magento2_Fluxrepo 
and invite you email but upload limited total file and size
i change only 1) Magento token key 2 ) Magento websit url
for another not change any source code
can you help to upload? or refer from my email send to you yesterday
Thank

**Comment by bundy29** [comment]
Hi Support
i  uploaded code to  https://github.com/bundy29/Magento234_Fluxstore
and invite minhtruong315@gmail.com
Pls refer my problem
1 ) error add to cart and product attribute  ==>fixed
2 ) product attribute filter not work ==> pending
3 ) order history error  ==>fixed
4 ) customer shipping address when check out ==> pending
<img width="387" alt="error_product_attribute_filter_not_show" src="https://user-images.githubusercontent.com/16270929/82026827-7db1a180-96bd-11ea-97d5-1facd30286e1.png">
<img width="756" alt="erro_customer_address_checkout" src="https://user-images.githubusercontent.com/16270929/82026840-81452880-96bd-11ea-83f4-63bf41e0926f.png">

**Comment by bundy29** [comment]
Hi Support
Seem this pending 2 issue will take long time Magento 2 not provide any Api for this
hope yours Magento 2 dev team can fix i will wait once new version available
Thank

**Comment by bundy29** [comment]
if no any update pls close this ticket

**Comment by minhtruong315** [comment]
@bundy29 product attribute doesn't support for Fluxstore magento, it only use for woo commerce.
customer shipping address only save on local. it doesn't pull from backend and doesn't save to backend.
