### ISSUE TITLE
StickyHome bar not show and only show white bar

### ISSUE THREAD

**Issue by zawwinhtunn** [inspireui/support#3111]
hello sir I have updated app version 1.7.3

In my app .StickyHome bar not show and only show white bar .I sent screen shot .please fix my issue.thank you so much.

https://github.com/zawwinhtunn/stickyhome/blob/master/1234.jpg

This is my purchased screen shot sir
https://github.com/zawwinhtunn/multiflutter/blob/master/purchase.PNG

**Comment by minhcasi** [comment]
@zawwinhtunn 
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by zawwinhtunn** [comment]
hello sir .I have sent to private links  form.please reply me.

**Comment by minhcasi** [comment]
@zawwinhtunn - thank you for quick response 🎉

@vumanhsn97 - pls help to check this issue on Fluxstore MV
We also need to improve to allow to change the background of Logo via Fluxbuilder

**Comment by vumanhsn97** [comment]
@zawwinhtunn 
- remove or change color in logo. #FFFFFF is white color: https://tppr.me/qOMor
- add line code into lib/main.dart https://tppr.me/kdepH
await SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.bottom]);

**Comment by zawwinhtunn** [comment]
Hello sir .I have added to home.dart and removed white color in config.json file.When I run show error sir.I sent error screen shot and other screen shot file .Please check my error and fix .Thank you so much for your kindly fast response.

This is error screen shot
https://github.com/zawwinhtunn/stickyhome/blob/master/error_after_change.jpg


This is home.dart screen shot after I added  
https://github.com/zawwinhtunn/stickyhome/blob/master/home.dart.PNG


This is main dart screen shot
https://github.com/zawwinhtunn/stickyhome/blob/master/main.dart.PNG

respectively

**Comment by vumanhsn97** [comment]
- replace file in lib/screen/home.dart to 
[home.dart.zip](https://github.com/inspireui/support/files/4613789/home.dart.zip)
- replace file in lib/widgets/home/index.dart to 
[index.dart.zip](https://github.com/inspireui/support/files/4613793/index.dart.zip)

**Comment by zawwinhtunn** [comment]
Thank you so much for your reply .I have placed and work fine.But I cannot find products in search button by using my native language.I filled products names ,description in wordpress  with my native language (Myanmar) .but I cannot search products by typing with Myanmar language.Please help me.

This screen shot is I searched with Myanmar Language.
https://github.com/zawwinhtunn/stickyhome/blob/master/search.jpg

This screen shot is  one product with Myanmar language.
https://github.com/zawwinhtunn/stickyhome/blob/master/language%20product.jpg


Thank you so much for your kindly help.
With Respectively

**Comment by minhcasi** [comment]
@trunghieuvn - pls help to check this search utf-8 issue - thank you!

**Comment by zawwinhtunn** [comment]
Hello please help me.

**Comment by zawwinhtunn** [comment]
Hello I have still error about utf8 . Please help me sir.

**Comment by trunghieuvn** [comment]
Hi @zawwinhtunn 
- To fix this error, please configure HTTPS for your api.
- Next edit the following code in the file `lib/services/helper/woocommerce_api.dart`:

```
class QueryString {
  static Map parse(String query) {
    var search = RegExp('([^&=]+)=?([^&]*)');
    var result = Map();

    // Get rid off the beginning ? in query strings.
    if (query.startsWith('?')) query = query.substring(1);
    // A custom decoder.
    decode(String s) => Uri.decodeComponent(s.replaceAll('+', ' '));
    // Go through all the matches and build the result map.
    for (Match match in search.allMatches(query)) {
      try {
        result[decode(match.group(1))] = decode(match.group(2));
      } catch (e) {
        result[match.group(1)] = match.group(2);
      }
    }

    return result;
  }
}
```

![image](https://user-images.githubusercontent.com/19247680/82209328-4e0dce00-9937-11ea-8d47-687d777969c8.png)
