### ISSUE TITLE
[FluxStore Woocommerce] Assertion boolean can’t be null

### ISSUE THREAD

**Issue by uade-pick-up** [inspireui/support#3112]
Hello:

I'm facing a problem only at home screen, it gives this error with my custom design or even any other pre-made template:

![DF1437D3-70B7-4A3C-A4BC-AD221516841D](https://user-images.githubusercontent.com/52259327/81474911-e214c280-91de-11ea-82a2-0ce8d117aad5.png)

I need a solution, will fill the form in few minutes.

Regards,
Pablo

**Comment by aldinhozanovicDev** [comment]
Take a look here:  #3090

**Comment by uade-pick-up** [comment]
Great, this worked perfectly!! Thank you very much @aldinhozanovicDev By the way do yo know how can I put a Header Logo to change image depending on mobile phone theme color? Light and Dark one?

Thank you,
Pablo

**Comment by minhcasi** [comment]
@uade-pick-up 
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
@uade-pick-up - we will upgrade the Logo Sticky setting/background with some enhancement via Fluxbuilder

In the meantime please add this line - https://tppr.me/uH95g

Let us know if you have any further question, just create a new ticket and link to this one without sending verify form again 😊
