### ISSUE TITLE
Unable to upload license key in private.inspireui.com

### ISSUE THREAD

**Issue by mahajansahab** [inspireui/support#3115]
Step 1 (require): detail issues and screenshots

My ticket id is 3114 but while uploading the license pdf or common zip folder its giving an error that server rejected upload.
You guys have made such a massive software but your support system is not upto the mark. Its too complex to ask for support.

![image](https://user-images.githubusercontent.com/2174778/81477086-609b4f80-9233-11ea-870a-e5de82942204.png)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhcasi** [comment]
@mahajansahab - pls help to try again

You could also try to give the comment on our product page http://codecayon.net/ - that is also other way to verify your purchase :)
