### ISSUE TITLE
Technical error in My Cart

### ISSUE THREAD

**Issue by myappcompany** [inspireui/support#3116]
Hi: 
When I add a product to the shopping cart (I don’t buy) and I exit the app and after a moment I enter again, I see the error in the following image
https://ibb.co/t3qgrJj

I am using the Fluxstore app from the Play Store. Could you please review it. 
Thanks a lot

**Comment by minhcasi** [comment]
@myappcompany 
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
Sorry, we should close this ticket as it could not be verified, please create the new one when you got enough purchased info - thank you!
