### ISSUE TITLE
Edit the products

### ISSUE THREAD

**Issue by Emmarango** [inspireui/support#3117]
Step 1 (require): detail issues and screenshots
How can I edit the products from the app?  
fluxstore multivendor with dokan

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhcasi** [comment]
@Emmarango - could you manage the product from the WooCommerce Admin or Vendor Dokan Dashboard

**Comment by Emmarango** [comment]
I manager from woocomerce admin,

**Comment by Emmarango** [comment]
But i need from the app, no put opción?

**Comment by minhcasi** [comment]
Hi, you could try to login as the Vendor account form the app, then you could post new product, and manage your previous product - the features could be lightweight but we will upgrade it more powerful later on - thank you!
