### ISSUE TITLE
TypeError: categorioes.forEach is not a function

### ISSUE THREAD

**Issue by spetsglaz** [inspireui/support#3118]
Step 1 (require): detail issues and screenshots
What am i doing wrong?

can't seem to start the project
<img width="1440" alt="Skärmavbild 2020-05-08 kl  17 35 49" src="https://user-images.githubusercontent.com/62562826/81421878-784ed700-9152-11ea-8bad-456bdd504ad5.png">

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by luyx2412** [comment]
Hi @spetsglaz This issue related with fetch categories. So can you give me the AppConfig.json and Config.js file? 

Thanks

**Comment by spetsglaz** [comment]
[configs.zip](https://github.com/inspireui/support/files/4605731/configs.zip)

**Comment by luyx2412** [comment]
Hi @spetsglaz This is default config of project. I need your config which appeared this issue.

Thanks

**Comment by spetsglaz** [comment]
[appconfigs.zip](https://github.com/inspireui/support/files/4609818/appconfigs.zip)

These are the files, i most likely haven't modified them as i have tried to start the app with a fresh copy. Many thanks :)

**Comment by luyx2412** [comment]
Hi @spetsglaz Can you send the project via inspireui.team@gmail.com? Because i just tested the default config with MstoreMV and everything worked normal.

Thanks

**Comment by spetsglaz** [comment]
It says the file is too large for email, how would you like me to send it to you? Through a link?

**Comment by luyx2412** [comment]
Hi @spetsglaz You can upload to the drive and send the link via inspireui.team@gmail.com.

Thanks

**Comment by minhcasi** [comment]
@spetsglaz - let us know if you have updated - thank you!

**Comment by spetsglaz** [comment]
I have ran in my terminal: yarn start, 

npm install -g expo-cli, 

and 

npm install -g npm

I am still experiencing the issue.

**Comment by luyx2412** [comment]
Hi @spetsglaz I still waiting your project upload to drive and send via inspireui.team@gmail.com.

Thanks

**Comment by spetsglaz** [comment]
<img width="424" alt="Skärmavbild 2020-05-23 kl  10 15 40" src="https://user-images.githubusercontent.com/62562826/82725636-8b2ee300-9cde-11ea-8f0b-2adb00141f87.png">

Hello @luyx2412 I have sent you the file a while ago, should i do it again?

**Comment by luyx2412** [comment]
HI @spetsglaz Sorry i did not see your email, please add your ticket id to the subject id `3118`. 

Thanks

**Comment by luyx2412** [comment]
HI @spetsglaz I saw your project, but this is default config. I need your website to investigate easier.

Thanks

**Comment by spetsglaz** [comment]
@luyx2412 I am using the default folder, i have no website connected and redid everything to be default, what website do you want? The one that starts after i write yarn start in the terminal? I am confused as to why it wont work even if i have your demo app website connected.

**Comment by luyx2412** [comment]
HI @spetsglaz The default config worked normal. So can you check again and give me the specific issues.

Thanks

**Comment by luyx2412** [comment]
Closed!
P/S: Feel free to reopen the issue.
