### ISSUE TITLE
[MSTORE-MV] Unable to Proceed with Payment (related to issue 274)

### ISSUE THREAD

**Issue by nghonyuen** [inspireui/support#312]
* Product: MSTORE-MV
* Your Purchased Code: 34a1d23d-c198-4cd8-beec-b4d0881c6437
  (we may not reply if you are not our customer)

Reopening issue as the same error still persists on iOS device. Android works perfectly fine. Thanks!

**Comment by nghonyuen** [comment]
Can I have some update please?

**Comment by nghonyuen** [comment]
some update on my side, I notice in my web server stderr log, below is recorded when I click on Confirm Order

warning: core file may not match specified executable file.
postdrop: warning: unable to look up public/pickup: No such file or directory


Shortly after the -1005 error will be displayed

**Comment by thangvo9x** [comment]
Which payment has occurred when you're checkout? If it still isn't working. you can send the AppConfig.json to email.

**Comment by nghonyuen** [comment]
We are using Paypal. Please find the below. Do note, it works on Android. Problem only happens in iOS. Thanks
[AppConfig.json.zip](https://github.com/inspireui/support/files/2884127/AppConfig.json.zip)

**Comment by thangvo9x** [comment]
Hi. Thanks for your file. Can you provide me your info website?

**Comment by nghonyuen** [comment]
Hi I have forwarded the login info to thang@inspireui.com. Tsk

**Comment by thangvo9x** [comment]
I can't login with that account.

**Comment by nghonyuen** [comment]
My apology, my colleague has changed the password. Please find the below:

URL: https://farm2table-dev <https://farm2table-dev/>.tk/wp-admin
Username: InspireUI
Password: farm2table

**Comment by thangvo9x** [comment]
I checked your source. The problem is coming from your shipping fee when you let it auto calculate.
It'll not work on the app. 
![Uploading Screen Shot 2019-02-27 at 10.09.48 AM.png…]()
