### ISSUE TITLE
 integrate new native payment ..

### ISSUE THREAD

**Issue by danielito-1** [inspireui/support#3121]
https://github.com/Gazer/px-flutter/

the application brings two native default payments,
but in my country they are not functional

these libraries are safe and add the native payment method I need

could you help me?

Thanks

**Comment by minhcasi** [comment]
@danielito-1 - sorry we could not help with the customization job, please try your best to investigate the source code by refer the previous Paypal native and apply for this payment gateway, or you could use the Webview solution to apply for this payment - https://docs.inspireui.com/fluxstore/multi-payment/
