### ISSUE TITLE
ListApp-MyListing(default): problems with "react-native-screen" from "node-modules" 

### ISSUE THREAD

**Issue by JonasB23** [inspireui/support#3123]
During the installation/connection with my site I was exposed to this error. Unfortunately I can't find out how to solve it.

<img width="376" alt="Schermata 2020-05-10 alle 00 13 47" src="https://user-images.githubusercontent.com/65094302/81486222-98b28a80-9253-11ea-9791-747de2eb63d3.png">

<img width="566" alt="Schermata 2020-05-10 alle 00 17 55" src="https://user-images.githubusercontent.com/65094302/81486247-b849b300-9253-11ea-92de-b68970d74916.png">

<img width="730" alt="Schermata 2020-05-10 alle 00 14 01" src="https://user-images.githubusercontent.com/65094302/81486232-a36d1f80-9253-11ea-9539-b1d4d70fb605.png">
I checked to see if everything was correct. I was confronted by these WARN
<img width="1188" alt="Schermata 2020-05-10 alle 00 25 11" src="https://user-images.githubusercontent.com/65094302/81486384-c1874f80-9254-11ea-8800-3d6611c202dd.png">

I don't understand if there is a relationship between the two problems. In any case, I would like to know if there is a solution. Thank you

**Comment by luyx2412** [comment]
Hi @JonasB23 Please follow the document to install `react-native-screens` https://docs.expo.io/versions/latest/sdk/screens/

Thanks

**Comment by JonasB23** [comment]
I followed the documentation to install react-native-screens. Unfortunately, he keeps giving me this mistake. 

<img width="384" alt="Schermata 2020-05-10 alle 21 39 29" src="https://user-images.githubusercontent.com/65094302/81508875-14b9da80-9307-11ea-87c7-1ae93d22b661.png">



Most likely I'm making a mistake, but I wouldn't know where...

**Comment by luyx2412** [comment]
Hi @JonasB23 Are use this script `expo install react-native-screens` to install this library? 

Thanks

**Comment by JonasB23** [comment]
yes

**Comment by luyx2412** [comment]
Hi @JonasB23 Can you send me the package.json file? Let me see the libraries installed.

Thanks

**Comment by JonasB23** [comment]
thanks for your help. I solved the problem.
