### ISSUE TITLE
Fluxstore 1.7.2 and 1.7.3 issues 

### ISSUE THREAD

**Issue by yosefasad** [inspireui/support#3124]
This is from   Fluxstore 1.7.2

1.    how to change the blue pic ... as shown below
![1](https://user-images.githubusercontent.com/23431061/81390297-d9ab8180-9123-11ea-9216-f0ee5298432a.jpg)

2.   when press category button,     in Arabic.  All categories are shown,, in English. Not all categories are shown   ....    How to fix it  ? 

![2  Catgegories copy](https://user-images.githubusercontent.com/23431061/81390430-1d05f000-9124-11ea-9fe7-bc1a864f1013.jpg)

3.     How to place these icon in the middle.  as shown below

![3      Middle icon copy](https://user-images.githubusercontent.com/23431061/81390501-3b6beb80-9124-11ea-95fd-eadfc85d8139.jpg)

4.    Arabc Font is not installed correctly everywhere ..how to fix it 

![4  copy](https://user-images.githubusercontent.com/23431061/81390535-52124280-9124-11ea-84f1-7960f4cf768f.jpg)
![5  copy](https://user-images.githubusercontent.com/23431061/81390574-5fc7c800-9124-11ea-9efc-8864af071a0d.jpg)

![6](https://user-images.githubusercontent.com/23431061/81390591-65251280-9124-11ea-8ced-9978227ccd54.jpg)

This is from   Fluxstore 1.7.3

on the default settings as downloaded from the Fluxstore 1.7.3 package 
when I change the language to arabic ..I face the blue screen below 

<img width="288" alt="Screen Shot 2020-05-08 at 10 00 28 PM" src="https://user-images.githubusercontent.com/23431061/81439869-c1fde880-9177-11ea-9789-a0c673518c4f.png">

How to solve this issue ? 

I already submit Submit Private Files For Support Ticket. 

<img width="720" alt="Screen Shot 2020-05-10 at 4 07 53 AM" src="https://user-images.githubusercontent.com/23431061/81488627-f525a200-9273-11ea-8bcd-391344c79325.png">

<img width="835" alt="Screen Shot 2020-05-10 at 4 20 28 AM" src="https://user-images.githubusercontent.com/23431061/81488755-b7297d80-9275-11ea-823c-2c6435320626.png">

Thank you for your cooperation

**Comment by kvt0012** [comment]
1.  What do you mean blue pic, sir ?
2.  Please check your api because it's not configured on app, it's fetched on api 
3.  You can add picture on this screen by coding. 
4.  We use google font, sir, you can check where you want to config and config it by inspecting sir.

**Comment by yosefasad** [comment]
1. 
![1](https://user-images.githubusercontent.com/23431061/81731263-5e392f80-9497-11ea-83fb-36bad91cc772.jpg)

2. it has been solved

3.  

![3](https://user-images.githubusercontent.com/23431061/81731376-7e68ee80-9497-11ea-953a-13ec33f25eeb.jpg)

>

**Comment by kvt0012** [comment]
1.  Please explain more about it, I will check it. Thank you

**Comment by yosefasad** [comment]
1. i want to replace the blue background with the blue orange with another picture with different background color  ...as shown in the previous comment

2. I have 3 icons only  and i want place them in the middle of the row .as shown in the comment.... 

I hope this is clear to you...

**Comment by kvt0012** [comment]
Please show on this format   
First problem   
+Picture to describe first problem   
Second problem  
+Picture to describe second problem    
...   
Because it's very hard to detect your picture because I don't know Abric, thank you

**Comment by kvt0012** [comment]
Ok I got your picture on my email, so I will check and show you a place, thank you

**Comment by kvt0012** [comment]
Q1.   
You can come to lib/common/constant.dart  and change this link to change your background, thank you 

![](https://user-images.githubusercontent.com/49152325/82026555-1693ed00-96bd-11ea-9dc1-0f4be08df6ba.png)

**Comment by yosefasad** [comment]
Thank you  for resolving question  Q1 

what about Q3 ...how can I resolve it ..?

**Comment by kvt0012** [comment]
If you use flutter inspector on the top left of android studio, you can check it, thank you   
 

![](https://user-images.githubusercontent.com/49152325/82035171-5d87df80-96c9-11ea-90c6-455affc4d1bc.png)
