### ISSUE TITLE
[FluxStore Pro] How to new tab page?

### ISSUE THREAD

**Issue by bikostudio** [inspireui/support#3125]
Hi @minhcasi 

I want to separate the items in settings tab to two tabs. I want it to be like this:

**one tab** : Login and profile settings + Whislist link + Get Notification switch + Notify Messages + Languages + Currencies + Dark theme switch.

**Tab two** : About us + Rate the app + Privacy + the Smart chat floated Icon.

is that possible ?

thank you

**Comment by minhcasi** [comment]
Yes, it's possible, it will require your little skills on Flutter - try to customize the tabbar.dart and clone the current Setting into 2 widgets, good luck 👍

**Comment by bikostudio** [comment]
>  tabbar.dart and clon

@minhcasi  I really don't know much about flutter, I'm using some tutorials to finish my app. Would you please send me tutorial to do so? 

also please see my last comment in my  issue:  [https://github.com/inspireui/support/issues/3093](url)


Thank you for your help
