### ISSUE TITLE
About us and privacity page

### ISSUE THREAD

**Issue by Roupasafricanas** [inspireui/support#3126]
Step 1 (require): detail issues and screenshots
![81374852-9840b500-90d6-11ea-9969-76c9b9cb999c](https://user-images.githubusercontent.com/63840938/81491036-7292e780-925f-11ea-82ac-f85f94d91f7c.jpg)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

Good night. I have two questions and a suggestion

1) how to switch the page "about-us" of inspireui for mine.
2) where to enter the privacy policy link

Tip: Can you leave a cache open for the pages visited in the app? One of my menu redirects to the social network of my store but every time the visitor leaves, needs to re-log again. Thank you

**Comment by Roupasafricanas** [comment]
Any answer please

**Comment by dttrung26** [comment]
Hi @Roupasafricanas , 
if you want to change the 'about-us' item on Settings Screen, first please use Flutter Inspector to identify its position, then whether you can use a Webview to display what you need
```
import '../../widgets/common/webview.dart';

WebView(
   url: "repleace-your-website.com",
   title: 'Your title webview),

```
or a postscreen 

```
import '../../screens/blogs/post_screen.dart';

PostScreen(
      pageId: 9937, //replace your page id here 
      pageTitle:    "Your page title here"),
```

The only difference between those two is that WebView displays your page via a browser, and PostScreen will convert your page content into Flutter widget. Please let me know if you still can't implement them. 
Nice day!

**Comment by Roupasafricanas** [comment]
Worked. Very thanks
