### ISSUE TITLE
How to remove currencies and language menu from profile page

### ISSUE THREAD

**Issue by NabiNeamati** [inspireui/support#3128]
Hi 
Hope be fine and doing well 
I have the fluxstore woocommerce.
I want to remove currencies and language menu from profile page also I want to remove the zip code from checkout page please help me.

Best regards

**Comment by iamar1k92** [comment]
Well, it's quite easier to that you have to navigate to: lib/screens/settings/settings.dart

1- Search and delete this block: 
  Divider(
                            color: Colors.black12,
                            height: 1.0,
                            indent: 75,
                            //endIndent: 20,
                          ),
                          Card(
                            margin: EdgeInsets.only(bottom: 2.0),
                            elevation: 0,
                            child: GestureDetector(
                              onTap: () {
                                Navigator.push(
                                  context,
                                  MaterialPageRoute(
                                      builder: (context) => Language()),
                                );
                              },
                              child: ListTile(
                                leading: Icon(
                                  Icons.language,
                                  color: Theme.of(context).accentColor,
                                  size: 24,
                                ),
                                title: Text(S.of(context).language),
                                trailing: Icon(
                                  Icons.arrow_forward_ios,
                                  size: 18,
                                  color: kGrey600,
                                ),
                              ),
                            ),
                          ),
                          Divider(
                            color: Colors.black12,
                            height: 1.0,
                            indent: 75,
                            //endIndent: 20,
                          ),
                          Card(
                            margin: EdgeInsets.only(bottom: 2.0),
                            elevation: 0,
                            child: ListTile(
                              onTap: () {
                                Navigator.push(
                                  context,
                                  MaterialPageRoute(
                                      builder: (context) => Currencies()),
                                );
                              },
                              leading: Icon(FontAwesomeIcons.dollarSign,
                                  size: 22,
                                  color: Theme.of(context).accentColor),
                              title: Text(S.of(context).currencies,
                                  style: TextStyle(fontSize: 16)),
                              trailing: Icon(Icons.arrow_forward_ios,
                                  size: 18, color: kGrey600),
                            ),
                          ),

**Comment by iamar1k92** [comment]
navigate to: lib/screens/checkout/shipping_address.dart

2- Search and delete this block:
Text(
                      S.of(context).zipCode,
                      style: TextStyle(
                          fontSize: 12,
                          fontWeight: FontWeight.w300,
                          color: Colors.grey),
                    ),
                    TextFormField(
                        controller: _zipController,
                        validator: (val) {
                          return val.isEmpty
                              ? S.of(context).zipCodeIsRequired
                              : null;
                        },
                        keyboardType: TextInputType.number,
                        decoration:
                            InputDecoration(labelText: S.of(context).zipCode),
                        onSaved: (String value) {
                          address.zipCode = value;
                        }),

**Comment by NabiNeamati** [comment]
Hi thanks for your quick response,

I have 3 more issue please help me on this also 
-1 After login to app using the login form (email and password ), app crashing and show this error 
please watch on the bellow video 
https://photos.app.goo.gl/VYyqQCdLRpzm1YcT8

-2 when i add products to cart and not show my payment method on payment Page, how can i solve this issue?
https://photos.app.goo.gl/1ARyQqLdZ25SxSTSA


-3 how i can change the height of Images on Onboard Screen? 

Best Regards

**Comment by NabiNeamati** [comment]
when i Try to place an order in App, after the Payment Method page redirect me to website order page and after a few second show the Payment Success message.
 how i can hide that page ?  https://photos.app.goo.gl/HCr9ugrNy8obnhmK8

**Comment by vumanhsn97** [comment]
@NabiNeamati 
Sorry for late response. I check all issue. Everything working well.
- Payment issue: https://tppr.me/DXr4Q. I order it and it always redirect to my order page: https://tppr.me/m9dYb
- To customize height image on Onboard Screen: Open file onboard_screen.dart in lib/screens/home folder. Change this code: https://tppr.me/7ZhU5 and resize height

**Comment by NabiNeamati** [comment]
Hi thanks for replay 
I mean when I submit an order it will redirect me for a few second in my website order page in a web view
I don't want to show the redirect page for few seconds 

please check this 

https://drive.google.com/file/u/2/d/1WS5mSTgGf33YRdZMLkpCACc_Q6GPJ139/view?usp=drivesdk

on the last page before Order Successfully message 

best Regrads
