### ISSUE TITLE
GraphQL Errors Shopify

### ISSUE THREAD

**Issue by kangsotheara** [inspireui/support#3129]
On Checkout page - Section SHIPPING

There is an issue with the app during request the data, place contact admin for fixing issues Exception: GraphQL Errors.
Variable checkoutid of type ID! was provided invalid value Undefined location.

![photo_2020-05-10_14-49-54](https://user-images.githubusercontent.com/2009861/81493841-17e4a480-92ce-11ea-966e-5be843210d83.jpg)

Step 1 (require): detail issues and screenshots

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@kangsotheara 
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
Sorry, we should close this ticket as it could not be verified, please create the new one when you got enough purchased info - thank you!
