### ISSUE TITLE
local ssl not working with fluxstore multi vendor.

### ISSUE THREAD

**Issue by spetsglaz** [inspireui/support#3131]
Step 1 (require): detail issues and screenshots
Hello, when i try to connect to my website with a localhost ssl certificate through mamp, it won't connect, is this supported or do i need to buy a ssl certificate? i have both tried to change the adress to https and http but it only works when i don't apply the localhost certificate. Thank you for the help :)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@spetsglaz - the ssl with not work on localhost 

Please check this video guide here to know how to setup as the virtual host on your local - https://www.youtube.com/watch?v=CEyfZmzBMTw&list=PLcF-HiQy-jOJAD8btGgr_CHcUmYyN8GgY&index=12
