### ISSUE TITLE
Problem in the new update fluxnew.1.4.1

### ISSUE THREAD

**Issue by haidarsalim** [inspireui/support#3132]
I am having trouble returning the welcome screen
https://vimeo.com/user115159967/review/416934845/122fb86472

**Comment by minhcasi** [comment]
@haidarsalim - the link is not working - pls share it again :)

<img width="1161" alt="Screen Shot 2020-05-11 at 08 51 07" src="https://user-images.githubusercontent.com/1459805/81517262-8f651300-9364-11ea-925a-7fecc09e9a18.png">

**Comment by haidarsalim** [comment]
https://vimeo.com/416934845

**Comment by dttrung26** [comment]
Hi @haidarsalim , due to there is a large modification for fixing this issue, we will update a fix in the next patch soon. 
Thank you for your patience.

**Comment by haidarsalim** [comment]
I can't work on the app. Is there a quick solution?
