### ISSUE TITLE
Error (Not matched) facebook login!

### ISSUE THREAD

**Issue by xsamir** [inspireui/support#3133]
Step 1 (require): detail issues and screenshots
On version 1.7.0 was working fine, but with the new version 1.7.3 of MultiVendor App it keeps shows this error.
![image](https://user-images.githubusercontent.com/7432001/81507319-a3c9f100-930d-11ea-8931-0d19697e0844.png)

What I tried:
Reconfirmed the Facebook code and hash code, secret key.
Reviewed the information on Firebase and Facebook developer page.

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by harjono-flux** [comment]
yes, i have same issue, when want to sign in with sms

![Screen Shot 2020-05-11 at 00 20 16](https://user-images.githubusercontent.com/64935574/81514929-3dbc8880-9364-11ea-9966-aeb1da298661.png)

**Comment by minhcasi** [comment]
@xsamir @harjono-flux - pls move conversion to this same issue - #3151 

It seems there is a new bug from Google Sign In + latest Flutter 1.17 - we are still investigating this issue - thank you!
