### ISSUE TITLE
Failed to load default media URL

### ISSUE THREAD

**Issue by agent3bood** [inspireui/support#3134]
Step 1 (require): detail issues and screenshots

The default product placeholder is not being fetched correctly.
I have setup media size as per this https://tppr.me/IbRvL 

Error screenshot
https://i.ibb.co/wp4dFBx/Screen-Shot-2020-05-11-at-00-49-48.png

WP setting page
https://i.ibb.co/2M8dGDP/Screen-Shot-2020-05-11-at-00-55-06.png

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

Done

NOTE: This issue is with the woocommerce placeholder image where a product does not has an image attached to it, other products with image are showing fine.

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by Amitjeypore** [comment]
Same issue here

**Comment by vumanhsn97** [comment]
- replace file in lib/common/tools.dart to 
[tools.dart.zip](https://github.com/inspireui/support/files/4614109/tools.dart.zip)

**Comment by agent3bood** [comment]
`import '../services/config.dart';` is missing from my code, I have 1.6.6

**Comment by vumanhsn97** [comment]
You can replace function image from line 82 to 182: https://tppr.me/NwgIl

**Comment by agent3bood** [comment]
Issue fixed with the provided code, thanks.

**Comment by agent3bood** [comment]
Can I get access to the gitlab repo? I have put my email in the google form.

Thanks

**Comment by agent3bood** [comment]
Can I get access to the gitlab repo? I have put my email in the google form.
Otherwise what is the way to apply new versions to my app?

Thanks
