### ISSUE TITLE
Integrate Klarna and swish to fluxstore multi vendor

### ISSUE THREAD

**Issue by spetsglaz** [inspireui/support#3135]
Step 1 (require): detail issues and screenshots
<img width="1440" alt="screen klarna" src="https://user-images.githubusercontent.com/62562826/81512021-a2a0c000-931d-11ea-923a-2aec9fe51c05.png">

I have the api key and also done everything that needs to be done to test the klarna service with the website, but when i try to test both the services on the app it looks like the picture. I have tried to replicate the paypal config for klarna what am i missing here? Many thanks :)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@spetsglaz - we are sorry that could not help to check on this issue as this is a new feature improvement to add your new Native Payment. 

Please try your best with the Debugger from Android Studio to find out the root cause issues
