### ISSUE TITLE
Shopify App showing flutter: Infinity or NaN toInt flutter issue

### ISSUE THREAD

**Issue by 8lbiasian** [inspireui/support#3136]
Step 1 (require): detail issues and screenshots

When I use the builder its show this msg and now also when I do with the simulator 

flutter: Another exception was thrown: Unsupported operation: Infinity or NaN toInt
flutter: Another exception was thrown: Unsupported operation: Infinity or NaN toInt

https://imgur.com/Dhblvut

https://imgur.com/auZedtQ

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by luyx2412** [comment]
HI @8lbiasian can you share me your config.dart file?

Thanks

**Comment by 8lbiasian** [comment]
> HI @8lbiasian can you share me your config.dart file?
> 
> Thanks

`export 'config/advertise.dart';
export 'config/general.dart';
export 'config/onboarding.dart';
export 'config/payments.dart';
export 'config/products.dart';
export 'config/smartchat.dart';

/// Server config demo for Shopify
/// Get more example for Opencart / Magento / Shopify from the example folder
const serverConfig = {
  "type": "shopify",
  "url": "https://xxxxxxx.myshopify.com",

  /// document: https://docs.inspireui.com/fluxstore/woocommerce-setup/
  "accessToken": "4ce4d2b95ba7f374c8d36xxxxxxxxxx",

  /// Your website woocommerce. You can remove this line if it same url
  "blog": "",

  /// set blank to use as native screen
  "forgetPassword": ""
};
`

**Comment by luyx2412** [comment]
Hi @8lbiasian Can you share me your specific config. Because i need your website information to investigate about it. You can share via inspireui.team@gmail.com to private.

Thanks

**Comment by 8lbiasian** [comment]
> Hi @8lbiasian Can you share me your specific config. Because i need your website information to investigate about it. You can share via [inspireui.team@gmail.com](mailto:inspireui.team@gmail.com) to private.
> 
> Thanks

ok please give me few mints.

**Comment by luyx2412** [comment]
Hi @8lbiasian Please replace this file in `lib/widget/product/product_card_view.dart`
[product_card_view.dart.zip](https://github.com/inspireui/support/files/4626585/product_card_view.dart.zip)

to fix the issues. We will fix it in next version.

Thanks

**Comment by 8lbiasian** [comment]
> Hi @8lbiasian Please replace this file in `lib/widget/product/product_card_view.dart`
> [product_card_view.dart.zip](https://github.com/inspireui/support/files/4626585/product_card_view.dart.zip)
> 
> to fix the issues. We will fix it in next version.
> 
> Thanks

when i try to run it i got this error 


`

Compiler message:
lib/widgets/product/product_card_view.dart:194:44: Error: The getter 'from' isn't defined for the class 'S'.
 - 'S' is from 'package:fstore/generated/l10n.dart' ('lib/generated/l10n.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'from'.
                        ? '${S.of(context).from} ${Tools.getPriceProduct(item, currency, onSale: true)}'
                                           ^^^^
lib/widgets/product/product_card_view.dart:196:56: Error: The getter 'headline6' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../../Documents/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline6'.
                    style: Theme.of(context).textTheme.headline6.copyWith(
                                                       ^^^^^^^^^
lib/widgets/product/product_card_view.dart:205:58: Error: The getter 'headline6' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../../Documents/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline6'.
                      style: Theme.of(context).textTheme.headline6.copyWith(
                                                         ^^^^^^^^^
        [C26.1 5F52FF7D-5187-4728-8BFE-0F8AE4A945A1 192.168.0.128:62942<->157.240.195.17:443]
        Connected Path: satisfied (Path is satisfied), interface: en0
        Duration: 0.389s, DNS @0.000s took 0.008s, TCP @0.010s took 0.105s, TLS took 0.125s
        bytes in/out: 4704/1360, packets in/out: 8/10, rtt: 0.098s, retransmitted packets: 0, out-of-order packets: 0
        [C25.1 90DD7AD1-1267-477F-BEF1-90E9CC516A98 192.168.0.128:62941<->157.240.195.17:443]
        Connected Path: satisfied (Path is satisfied), interface: en0
        Duration: 0.399s, DNS @0.000s took 0.009s, TCP @0.011s took 0.105s, TLS took 0.124s
        bytes in/out: 4417/1291, packets in/out: 8/9, rtt: 0.105s, retransmitted packets: 0, out-of-order packets: 0
flutter: [2020-05-14 12:24:55.484093Z][Fluxstore][MenuBar] build
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
Failed to build bundle.
Error launching application on iPhone 11 Pro.
`

**Comment by 8lbiasian** [comment]
ok i did the following change and its work

S.of(context).form 
to be 
S.of(context)

headline6 to be headline 



now the products view work fine, but the issue in the home 
check the following 

<img width="457" alt="Screen Shot 2020-05-14 at 4 32 20 PM" src="https://user-images.githubusercontent.com/2717113/81934891-c5bebe80-9600-11ea-85bc-e40b1eac6042.png">

what the the changes u made in the product view so i can implement the same on the home file

**Comment by luyx2412** [comment]
HI @8lbiasian Can you uninstall and reinstall app again.

Thanks

**Comment by 8lbiasian** [comment]
> HI @8lbiasian Can you uninstall and reinstall app again.
> 
> Thanks

didn't understand what u mean by that which app?

**Comment by luyx2412** [comment]
HI @8lbiasian Sorry about my comment, can you uninstall the app on simulator and build it again. The app need clear cache to run normal.

Thanks

**Comment by 8lbiasian** [comment]
same issue

**Comment by 8lbiasian** [comment]
please update me with a solution for this issue.

**Comment by luyx2412** [comment]
Hi @8lbiasian Can you send me your config json file? i saw your config.dart but missing config json file.
![image](https://user-images.githubusercontent.com/8909619/82119921-7a491380-97ac-11ea-9c08-160abbe6b33b.png)

Thanks

**Comment by 8lbiasian** [comment]
please check your email i already send it first time.

**Comment by 8lbiasian** [comment]
@luyx2412 Please any update?!

**Comment by luyx2412** [comment]
Hi @8lbiasian Can you send me again. i could not find it.

Thanks

**Comment by 8lbiasian** [comment]
@luyx2412 please check now

**Comment by jberman280** [comment]
No, the issue is the config. fluxbuilder gave you. 
There so many errors.

try to compare it with the original and edit it.

**Comment by 8lbiasian** [comment]
> No, the issue is the config. fluxbuilder gave you.
> There so many errors.
> 
> try to compare it with the original and edit it.

you mean the fluxbuilder have wrong config format and parameters ?!
this apply with other plugins for woocomerce etc??

**Comment by jberman280** [comment]
Yes, exactly.
beacuse if you try original config, the app will work just normal.
Try js beautifier. so you can modify your code. it'll be easy for you.
Delete the pub cache in Appdata and then
Flutter clean
and try flutter packages get.

**Comment by luyx2412** [comment]
Hi @jberman280 Thanks for your help. This is right way to fix the issues.

**Comment by 8lbiasian** [comment]
@jberman280 I try to find the difference but didn't know exactly what as I am changing the style through the builder, but when I put the default config its work 

@luyx2412 =_= and I wait more than a week just because you guys have bug in the builder, how I can fix this issue? as I don't know what parameters are not working from the builder ?!

**Comment by luyx2412** [comment]
Hi @8lbiasian Can you send me your project via inspireui.team@gmaill.com Sorry about reply late and support. We have some problems about Covid 19 issue.

Thanks

**Comment by minhcasi** [comment]
@8lbiasian - let us know if you have any update on this ticket - thank you!

**Comment by 8lbiasian** [comment]
> Hi @8lbiasian Can you send me your project via [inspireui.team@gmaill.com](mailto:inspireui.team@gmaill.com) Sorry about reply late and support. We have some problems about Covid 19 issue.
> 
> Thanks

i send already and wait for reply.

**Comment by luyx2412** [comment]
HI @8lbiasian I just tested your project, and everything worked normal. Maybe something was wrong. So please you this config to apply your project. 
[config_en.json.zip](https://github.com/inspireui/support/files/4689509/config_en.json.zip)
![Uploading image.png…]()

Thanks

**Comment by 8lbiasian** [comment]
check the attach 
its now showing like urs see the icons in nav having text.

[config_en.json.zip](https://github.com/inspireui/support/files/4693306/config_en.json.zip)

**Comment by luyx2412** [comment]
HI @8lbiasian Thanks for your sharing, Please change `StickyHeader: false` same the screenshot. It have some issues related to the stickyheader, we will improve and fix it in next version.
![image](https://user-images.githubusercontent.com/8909619/83166466-2be72d80-a139-11ea-826c-279fcf21c5f1.png)
![image](https://user-images.githubusercontent.com/8909619/83166515-3e616700-a139-11ea-9388-b07040a540b5.png)

Thanks

**Comment by luyx2412** [comment]
Feel free to re-open or create new issues.

Thanks
