### ISSUE TITLE
[FluxStore Pro] Side Menu Background Color & Smart Chat Icon

### ISSUE THREAD

**Issue by bikostudio** [inspireui/support#3137]
Hi @minhcasi  

### **1. How to change the background color of the Side Menu?**

![2020-05-11_052544](https://user-images.githubusercontent.com/62074493/81521833-ba416e00-9348-11ea-8985-02bb52061501.jpg)

### **2. Can I add smart chat floating Icon to be visible in any page for example : static page, external link page ?**

![2020-05-10_072658](https://user-images.githubusercontent.com/62074493/81491551-07153e00-9290-11ea-81da-cb72acb9f23e.jpg)

Thank you

**Comment by minhcasi** [comment]
- try to edit this file - https://tppr.me/e0hy0
- and this file for smartchat - https://tppr.me/fCXC8 (we have upgraded it on next release as well)

**Comment by bikostudio** [comment]
> 
> 
>     * try to edit this file - https://tppr.me/e0hy0
> 
>     * and this file for smartchat - https://tppr.me/fCXC8 (we have upgraded it on next release as well)
> 
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/e0ab8cd7cdf3c096df74a026ca5d2fb596ade251/68747470733a2f2f747070722e73332e616d617a6f6e6177732e636f6d2f75706c6f6164732f61633065623862643365333234633764393561346339363534383938323437622e6a7067"><img alt="" height="14" src="/favicon-32x32.png"> tppr.me**[Public - Android Studio_2020-05-11 14-13-28](https://tppr.me/e0hy0)**
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/0ee2cb12bc6de48a039e41dbbde115027b70927e/68747470733a2f2f747070722e73332e616d617a6f6e6177732e636f6d2f75706c6f6164732f64643838356139373564343563656134383736623162386561616137363963372e6a7067"><img alt="" height="14" src="/favicon-32x32.png"> tppr.me**[Public - Android Studio_2020-05-11 14-21-29](https://tppr.me/fCXC8)**

Thank you @minhcasi 
I will try and let you know
thank you for your time

**Comment by bikostudio** [comment]
The case is : 

- I have created a page via FulxBuilder 
![2020-05-11_153129](https://user-images.githubusercontent.com/62074493/81567480-a7588900-939c-11ea-8504-39ec4be7a1d5.jpg)

- this Page is linked to a contact us for URL at my WooCommerce site.

- I want to make the Smart Chat floating icon to be visible in this webview page in the app.

How to do this please?

Thank you
