### ISSUE TITLE
error in failed assertion: boolean expression must not be null

### ISSUE THREAD

**Issue by framepoint-id** [inspireui/support#3138]
Hi there,

I have purchased fluxstore for woocommerce. I am designing the layout and template from fluxbuilder and copying the code from publish section [http://prnt.sc/seh5il](url)
and paste to my android studio "config_en.json". however the simulator come up "error in failed assertion: boolean expression must not be null" [http://prnt.sc/seh61d](url)

any work around this?

**Comment by minhcasi** [comment]
@framepoint-id - there is the bug from Fluxbuilder - try to fix by adding new StickyHeader to the config json file 

https://github.com/inspireui/support/issues/3090#issuecomment-626100903

**Comment by framepoint-id** [comment]
Dear @minhcasi ,

I have added the sticky header false to the file. [http://prnt.sc/sejzo2](url)
This is the result [http://prnt.sc/sek08p](url)

The method '[]' was called on null.
Receiver: null
Tried calling: []("TabBar")


Can i attach my config_en.json file here? Your help will be much appreciated. Thank You.

**Comment by minhcasi** [comment]
Yes sure, pls share it here :)

**Comment by framepoint-id** [comment]
[config_en.json.zip](https://github.com/inspireui/support/files/4608725/config_en.json.zip)
Dear @minhcasi , Thank you so much. This is the config_en.json file. Please kindly advise. Thanks again! :)

**Comment by framepoint-id** [comment]
Waiting for your update @minhcasi Thank You :)

**Comment by framepoint-id** [comment]
Dear @minhcasi , sorry for disturbing. Any update yet? We plan to publish the app during this ramadan period, since we are based in Indonesia. Thanks in advance :)

**Comment by minhcasi** [comment]
@framepoint-id - pls try to use this setting - there is the wrong syntax issue on the json you have sent, if it is generated from the Fluxbuilder then it could be the bug from Builder app.

Also, try to use the latest code from Gitlab, we will release new 1.7.4 in 1-2 days - thank you!

[config_en.json.zip](https://github.com/inspireui/support/files/4620173/config_en.json.zip)

<img width="1392" alt="Screen Shot 2020-05-13 at 13 22 33" src="https://user-images.githubusercontent.com/1459805/81778319-d0a02300-951c-11ea-8a3b-4f37877281cc.png">

**Comment by minhcasi** [comment]
Let us know if you have any question - thank you!

**Comment by framepoint-id** [comment]
Dear @minhcasi , I have copied your config_en-json.zip into android studio. 

still have some error below, did i do anything wrong? or i should still wait for your newest release?

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building HomeLayout-[<'en'>](dirty, state: _HomeLayoutState#ea7d9):
Failed assertion: boolean expression must not be null

The relevant error-causing widget was: 
  HomeLayout-[<'en'>] file:///Users/stevieliawardi/Downloads/FluxStore-woo%201.7.3/source/lib/screens/home/home.dart:119:13
When the exception was thrown, this was the stack: 
#0      _HomeLayoutState.jsonWidget (package:fstore/widgets/home/index.dart:36:52)
#1      _HomeLayoutState.build (package:fstore/widgets/home/index.dart:149:11)
#2      StatefulElement.build (package:flutter/src/widgets/framework.dart:4619:28)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4502:15)
#4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
