### ISSUE TITLE
Lighter app

### ISSUE THREAD

**Issue by Roupasafricanas** [inspireui/support#3139]
Step 1 (require): detail issues and screenshots

![81491036-7292e780-925f-11ea-82ac-f85f94d91f7c](https://user-images.githubusercontent.com/63840938/81524189-9c631180-9326-11ea-9d74-ab42cf35a60d.jpg)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

Good night. I uploaded my app and gave 42MB. I wonder if there's any way to make him lighter. If so, what should I delete in the app. Thank you

**Comment by minhcasi** [comment]
@Roupasafricanas - you could try to remove some heavy library like Firebase, i've explained detail on this blog - https://medium.com/@inspireui/how-to-build-flutter-instant-app-with-fluxstore-7d14c4630ae6

Or you could follow this link https://flutter.dev/docs/deployment/android#build-an-app-bundle 

Our final app-only 17MB (the original package one that you have downloaded) - https://play.google.com/store/apps/details?id=com.inspireui.fluxstore&hl=en

Thank you!
