### ISSUE TITLE
[Fluxstore -MV] Social logins and SMS not working after update - 1.7.3

### ISSUE THREAD

**Issue by ideas24** [inspireui/support#3140]
Step 1 (require): detail issues and screenshots
I keep getting errors for the social login after update to 1.7.3. The SMS login also takes forever with no code received. Please fix asap. Video of error is attached as config file to the private form. Thanks 

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@ideas24 - we will update this issue on this ticket - #3151 - it seems there is a new issue with the Google Sign In in the update that we could figure out so far

**Comment by ideas24** [comment]
@minhcasi The Facebook login is also not working. Kindly fix all please
