### ISSUE TITLE
Not Showing Wholesale Info. On FluxStore MV app

### ISSUE THREAD

**Issue by sanpiseth** [inspireui/support#3141]
Step 1 (require): detail issues and screenshots
I have configure Dokan Wholesale on my website and It works normally.
However, in FluxStore MV the wholesale information is not shown.

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@sanpiseth - could you help to share the detailed screenshot  so that we could try to reproduce the issue :)

**Comment by sanpiseth** [comment]
Please kindly see the attached files of 
1/ Dokan Wholesale Setting
2/ My Website shows Wholesale price normally
3/ Fluxstore MV doesnot show wholesale price
![Fluxstore MV Not Show Wholesale Price](https://user-images.githubusercontent.com/52672170/81546390-f7c2ed00-9382-11ea-80c4-b52d5abd105e.jpg)
![website shows wholesale price](https://user-images.githubusercontent.com/52672170/81546399-fabddd80-9382-11ea-9d1f-e23a2b05691d.png)
![wholesale setting](https://user-images.githubusercontent.com/52672170/81546401-fbef0a80-9382-11ea-9878-823234c0c76e.png)

**Comment by minhcasi** [comment]
@sanpiseth - thank you for quick response, I've got your idea

The current Fluxstore MV product is not supported for Wholesale feature - we have marked as a feature request and upgrade it later - thank you!

**Comment by sanpiseth** [comment]
Please kindly check other features (of Dokan Pro) with the Fluxstore MV
also.

They might not working

Thanks

**Comment by sanpiseth** [comment]
Any update on this please?

**Comment by minhcasi** [comment]
hi, it's still on our queue - thank you!

**Comment by minhcasi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Wholesale Info. On FluxStore MV app](https://trello.com/c/SK19SrEy/44-wholesale-info-on-fluxstore-mv-app)

**Comment by minhcasi** [comment]
moved to backlogs for further investigating

**Comment by sanpiseth** [comment]
Hello,

Is this closed? How can I get the updated fluxstore MV ?

Thanks

**Comment by sanpiseth** [comment]
Hello

Any update on this please ?

**Comment by minhcasi** [comment]
Hi, we only move to the todo from our team for investigating, thank you!
