### ISSUE TITLE
Error launching application on iPhone 11 Pro Max. Shopify Version 

### ISSUE THREAD

**Issue by rabahaldoori** [inspireui/support#3142]
i already fellow the video you post it on you youtube still i can't make it build could you help me please 

thank you 

Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
Running Xcode build...

Compiler message:
../flutter/.pub-cache/hosted/pub.dartlang.org/extended_image-0.7.2/lib/src/gesture/extended_image_slide_page_route.dart:333:9: Error: No named parameter with the name 'animation'.
        animation: animation,
        ^^^^^^^^^
../flutter/packages/flutter/lib/src/cupertino/route.dart:435:3: Context: Found this candidate, but the arguments don't match.
  CupertinoFullscreenDialogTransition({
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Xcode build done.                                           31.0s
Failed to build iOS app
Error output from Xcode build:
↳
    2020-05-11 02:21:58.372 XCBBuildService[4850:40291] Failed to remove: /Users/aldoori/Library/Developer/Xcode/DerivedData/Runner-ffzztrdhionixdeljlmidiyigbbs/Build/Intermediates.noindex/XCBuildData/4c3355ac59200d09ec11ae9c1586feda-desc.xcbuild: unlink(/Users/aldoori/Library/Developer/Xcode/DerivedData/Runner-ffzztrdhionixdeljlmidiyigbbs/Build/Intermediates.noindex/XCBuildData/4c3355ac59200d09ec11ae9c1586feda-desc.xcbuild): No such file or directory (2)
    ** BUILD FAILED **

Xcode's output:
↳
    In file included from /Users/aldoori/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/uni_links-0.2.0/ios/Classes/UniLinksPlugin.m:1:
    /Users/aldoori/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/uni_links-0.2.0/ios/Classes/UniLinksPlugin.h:4:4: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
    + (instancetype)sharedInstance;
       ^
    /Users/aldoori/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/uni_links-0.2.0/ios/Classes/UniLinksPlugin.h:4:4: note: insert '_Nullable' if the pointer may be null
    + (instancetype)sharedInstance;
       ^
                    _Nullable 
    /Users/aldoori/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/uni_links-0.2.0/ios/Classes/UniLinksPlugin.h:4:4: note: insert '_Nonnull' if the pointer should never be null
    + (instancetype)sharedInstance;
       ^
                    _Nonnull 
    /Users/aldoori/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/uni_links-0.2.0/ios/Classes/UniLinksPlugin.h:7:33: warning: block pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
          restorationHandler:(void (^)(NSArray *_Nullable))restorationHandler;
                                    ^
    /Users/aldoori/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/uni_links-0.2.0/ios/Classes/UniLinksPlugin.h:7:33: note: insert '_Nullable' if the block pointer may be null
          restorationHandler:(void (^)(NSArray *_Nullable))restorationHandler;
                                    ^
                                     _Nullable
    /Users/aldoori/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/uni_links-0.2.0/ios/Classes/UniLinksPlugin.h:7:33: note: insert '_Nonnull' if the block pointer should never be null
          restorationHandler:(void (^)(NSArray *_Nullable))restorationHandler;
                                    ^
                                     _Nonnull
    2 warnings generated.
    /Users/aldoori/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0.6.0+2/ios/Classes/RateMyAppPlugin.m:15:30: warning: 'requestReview' is only available on iOS 10.3 or newer [-Wunguarded-availability]
        [SKStoreReviewController requestReview];
                                 ^~~~~~~~~~~~~~
    In module 'StoreKit' imported from /Users/aldoori/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0.6.0+2/ios/Classes/RateMyAppPlugin.m:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/StoreKit.framework/Headers/SKStoreReviewController.h:22:1: note: 'requestReview' has been marked as being introduced in iOS 10.3 here, but the deployment target is iOS 8.0.0
    + (void)requestReview API_AVAILABLE(ios(10.3), macos(10.14)) __TVOS_PROHIBITED;
    ^
    /Users/aldoori/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0.6.0+2/ios/Classes/RateMyAppPlugin.m:15:30: note: enclose 'requestReview' in an @available check to silence this warning
        [SKStoreReviewController requestReview];
                                 ^~~~~~~~~~~~~~
    /Users/aldoori/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0.6.0+2/ios/Classes/RateMyAppPlugin.m:15:6: warning: 'SKStoreReviewController' is only available on iOS 10.3 or newer [-Wunguarded-availability]
        [SKStoreReviewController requestReview];
         ^~~~~~~~~~~~~~~~~~~~~~~
    In module 'StoreKit' imported from /Users/aldoori/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0.6.0+2/ios/Classes/RateMyAppPlugin.m:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/StoreKit.framework/Headers/SKStoreReviewController.h:14:85: note: 'SKStoreReviewController' has been marked as being introduced in iOS 10.3 here, but the deployment target is iOS 8.0.0
    SK_EXTERN_CLASS API_AVAILABLE(ios(10.3), macos(10.14)) __TVOS_PROHIBITED @interface SKStoreReviewController : NSObject
                                                                                        ^
    /Users/aldoori/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0.6.0+2/ios/Classes/RateMyAppPlugin.m:15:6: note: enclose 'SKStoreReviewController' in an @available check to silence this warning
        [SKStoreReviewController requestReview];
         ^~~~~~~~~~~~~~~~~~~~~~~
    2 warnings generated.
    /Users/aldoori/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_admob-0.9.3+2/ios/Classes/FLTRewardedVideoAdWrapper.m:75:66: warning: implicit conversion loses integer precision: 'FLTRewardedVideoAdStatus' to 'int' [-Wshorten-64-to-32]
          (NSString *)rewardedStatusToString[[NSNumber numberWithInt:_rewardedStatus]];
                                             ~                       ^~~~~~~~~~~~~~~
    1 warning generated.
    /Users/aldoori/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_admob-0.9.3+2/ios/Classes/FLTRequestFactory.m:71:13: warning: 'testDevices' is deprecated: Use GADMobileAds.sharedInstance.requestConfiguration.testDeviceIdentifiers. [-Wdeprecated-declarations]
        request.testDevices = testDevices;
                ^
    In module 'GoogleMobileAds' imported from /Users/aldoori/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_admob-0.9.3+2/ios/Classes/FLTRequestFactory.h:5:
    /Users/aldoori/Desktop/source/ios/Pods/Google-Mobile-Ads-SDK/Frameworks/GoogleMobileAdsFramework-Current/GoogleMobileAds.framework/Headers/GADRequest.h:88:71: note: 'testDevices' has been explicitly marked deprecated here
    @property(nonatomic, copy, nullable) NSArray<NSString *> *testDevices GAD_DEPRECATED_MSG_ATTRIBUTE(
                                                                          ^
    In module 'GoogleMobileAds' imported from /Users/aldoori/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_admob-0.9.3+2/ios/Classes/FLTRequestFactory.h:5:
    /Users/aldoori/Desktop/source/ios/Pods/Google-Mobile-Ads-SDK/Frameworks/GoogleMobileAdsFramework-Current/GoogleMobileAds.framework/Headers/GoogleMobileAdsDefines.h:25:56: note: expanded from macro 'GAD_DEPRECATED_MSG_ATTRIBUTE'
    #define GAD_DEPRECATED_MSG_ATTRIBUTE(s) __attribute__((deprecated(s)))
                                                           ^
    /Users/aldoori/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_admob-0.9.3+2/ios/Classes/FLTRequestFactory.m:91:15: warning: 'birthday' is deprecated [-Wdeprecated-declarations]
          request.birthday =
                  ^
    In module 'GoogleMobileAds' imported from /Users/aldoori/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_admob-0.9.3+2/ios/Classes/FLTRequestFactory.h:5:
    /Users/aldoori/Desktop/source/ios/Pods/Google-Mobile-Ads-SDK/Frameworks/GoogleMobileAdsFramework-Current/GoogleMobileAds.framework/Headers/GADRequest.h:95:55: note: 'birthday' has been explicitly marked deprecated here
    @property(nonatomic, copy, nullable) NSDate *birthday GAD_DEPRECATED_ATTRIBUTE;
                                                          ^
    In module 'GoogleMobileAds' imported from /Users/aldoori/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_admob-0.9.3+2/ios/Classes/FLTRequestFactory.h:5:
    /Users/aldoori/Desktop/source/ios/Pods/Google-Mobile-Ads-SDK/Frameworks/GoogleMobileAdsFramework-Current/GoogleMobileAds.framework/Headers/GoogleMobileAdsDefines.h:33:49: note: expanded from macro 'GAD_DEPRECATED_ATTRIBUTE'
    #define GAD_DEPRECATED_ATTRIBUTE __attribute__((deprecated))
                                                    ^
    /Users/aldoori/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_admob-0.9.3+2/ios/Classes/FLTRequestFactory.m:106:19: warning: 'gender' is deprecated [-Wdeprecated-declarations]
              request.gender = genderValue;
                      ^
    In module 'GoogleMobileAds' imported from /Users/aldoori/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_admob-0.9.3+2/ios/Classes/FLTRequestFactory.h:5:
    /Users/aldoori/Desktop/source/ios/Pods/Google-Mobile-Ads-SDK/Frameworks/GoogleMobileAdsFramework-Current/GoogleMobileAds.framework/Headers/GADRequest.h:92:47: note: 'gender' has been explicitly marked deprecated here
    @property(nonatomic, assign) GADGender gender GAD_DEPRECATED_ATTRIBUTE;
                                                  ^
    In module 'GoogleMobileAds' imported from /Users/aldoori/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_admob-0.9.3+2/ios/Classes/FLTRequestFactory.h:5:
    /Users/aldoori/Desktop/source/ios/Pods/Google-Mobile-Ads-SDK/Frameworks/GoogleMobileAdsFramework-Current/GoogleMobileAds.framework/Headers/GoogleMobileAdsDefines.h:33:49: note: expanded from macro 'GAD_DEPRECATED_ATTRIBUTE'
    #define GAD_DEPRECATED_ATTRIBUTE __attribute__((deprecated))
                                                    ^
    /Users/aldoori/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_admob-0.9.3+2/ios/Classes/FLTRequestFactory.m:116:14: warning: 'tagForChildDirectedTreatment:' is deprecated:  use [GADMobileAds.sharedInstance.requestConfiguration tagForChildDirectedTreatment] [-Wdeprecated-declarations]
        [request tagForChildDirectedTreatment:childDirected.boolValue];
                 ^
    In module 'GoogleMobileAds' imported from /Users/aldoori/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_admob-0.9.3+2/ios/Classes/FLTRequestFactory.h:5:
    /Users/aldoori/Desktop/source/ios/Pods/Google-Mobile-Ads-SDK/Frameworks/GoogleMobileAdsFramework-Current/GoogleMobileAds.framework/Headers/GADRequest.h:126:5: note: 'tagForChildDirectedTreatment:' has been explicitly marked deprecated here
        GAD_DEPRECATED_MSG_ATTRIBUTE(
        ^
    In module 'GoogleMobileAds' imported from /Users/aldoori/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_admob-0.9.3+2/ios/Classes/FLTRequestFactory.h:5:
    /Users/aldoori/Desktop/source/ios/Pods/Google-Mobile-Ads-SDK/Frameworks/GoogleMobileAdsFramework-Current/GoogleMobileAds.framework/Headers/GoogleMobileAdsDefines.h:25:56: note: expanded from macro 'GAD_DEPRECATED_MSG_ATTRIBUTE'
    #define GAD_DEPRECATED_MSG_ATTRIBUTE(s) __attribute__((deprecated(s)))
                                                           ^
    4 warnings generated.
    2 warnings generated.

    Compiler message:
    ../flutter/.pub-cache/hosted/pub.dartlang.org/extended_image-0.7.2/lib/src/gesture/extended_image_slide_page_route.dart:333:9: Error: No named parameter with the name 'animation'.
            animation: animation,
            ^^^^^^^^^
    ../flutter/packages/flutter/lib/src/cupertino/route.dart:435:3: Context: Found this candidate, but the arguments don't match.
      CupertinoFullscreenDialogTransition({
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
    build failed.
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Planning build
    note: Constructing build description

Could not build the application for the simulator.
Error launching application on iPhone 11 Pro Max.

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
you could try to open the pubspec file and update below library and rebuild the project to fix the issue - thank you!

from
```
 extended_image: 0.7.2
```
to

```
extended_image: 0.7.3+1
```

**Comment by rabahaldoori** [comment]
i already submit the purchase code , how i can update the file to extended_image: 0.7.3+1  !! 


thank you
