### ISSUE TITLE
The method '[]' was called on null. Receiver: null Tried calling: []("TabBar")

### ISSUE THREAD

**Issue by framepoint-id** [inspireui/support#3144]
Dear @minhcasi ,
I have added the sticky header false to the file. http://prnt.sc/sejzo2
This is the result http://prnt.sc/sek08p
The method '[]' was called on null.
Receiver: null
Tried calling:
Can i attach my config_en.json file here? Your help will be much appreciated. Thank You.

**Comment by minhcasi** [comment]
Duplicate of #3138
