### ISSUE TITLE
Unable to Open Expo Folder via CeBuilder

### ISSUE THREAD

**Issue by BLBeniwal** [inspireui/support#3146]
Step 1 (require): detail issues and screenshots
i check on both Window 10 & window 8.1 but i'm getting same issue when itry to connect my EXPO folder

Win10 -  https://prnt.sc/sekvo3

Win8.1 -  https://prnt.sc/sekwdp

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

Yes sure I will do after create ticket from here.

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by BLBeniwal** [comment]
Hello Cebuilder Support?

Have you looked into my issue? can i know how to fix this?

Thanks

**Comment by minhcasi** [comment]
@BLBeniwal - sorry for late response - could you help to quick look to this video to see if you have open the right folder - https://www.youtube.com/watch?v=6-Eno3dtR4M&list=PLcF-HiQy-jOKVI23G0ppKoSaTA-gwCAew&index=3&t=0s

the folder should contain the package.json file 

also try to update to latest cebuilder - https://github.com/inspireui/cebuilder/releases

**Comment by BLBeniwal** [comment]
Hello @minhcasi ,
Thanks for your valuable response.

I used the latest version of cebuilder & I'm in the right folder. I'm trying to access this "beonews-expo". This folder has all files including package.json.

Apart from that if I try to access "beonews-pro" folder then YES I can access. 

I'm face issues only with EXPO.

Waiting for your valuable response.

Thanks

**Comment by minhcasi** [comment]
Hi sorry for the issues, it could be an issue with the recent release on nodejs - i've reported to the team. 

You could also try to run the project by running react-native-cli (more document guide https://reactnative.dev/docs/getting-started)?

It is possible to process the refund on this link if you could not use the product so far - https://help.market.envato.com/hc/en-us/articles/202821460-Can-I-Get-A-Refund- 

- very best
