### ISSUE TITLE
No route was found matching the URL and request method

### ISSUE THREAD

**Issue by magic-coding** [inspireui/support#3148]
I use a custom endpoint on my WordPress that uses `POST` method. The issue is when i try to login to the app it returns `Username or password is wrong`.
I take a look at logs and I see it returns ` No route was found matching the URL and request method` in every time I try to log in. 

So I remove the custom endpoint from `functions.php` and try again to log in and it works.
It looks when we add a custom endpoint to WordPress it cause conflict with your plugin.

Please how I can get this work? because we must use that custom endpoint.

Functions.php

```
POST request
add_action(
    'rest_api_init',
    function () {
        register_rest_route(
            'api',
            'viewOrder',
            array(
                'methods'  => 'POST',
                'callback' => 'viewOrder',
            )
        );
    }
);

function viewOrder( WP_REST_Request $request ) {
    $arr_request = json_decode( $request->get_body() );
    $order_id = $arr_request->order_id;
    $order = wc_get_order( $order_id );
	if($arr_request) {
			if ( $order ) {
                         ............

			}		
	} else {
		return null;
	}

}
```

**Comment by minhcasi** [comment]
@magic-coding - thank you for your feedback, we will investigate and let you know ⭐️

@minhtruong315 - pls help to check

**Comment by minhtruong315** [comment]
@magic-coding can u send me mstore api plugin after you added custom endpoint

**Comment by magic-coding** [comment]
I solve this issue by changing the `namespace` from **API** to another name. I think Mstore-API use API namespace for custom Wordpress endpoint and that maybe cause the conflict.

**Comment by imhafeez** [comment]
I am facing this issue. How to solve this. @magic-coding

**Comment by imhafeez** [comment]
@minhcasi

**Comment by brygom** [comment]
Please, how to solve this issue?

**Comment by imhafeez** [comment]
@brygom you need to activate your plugin via Mstore API tab on your Wordpress admin

**Comment by brygom** [comment]
Thank you @imhafeez, I trying this but i have conflict error:
```Fatal error: Cannot redeclare registerJsonApiController() (previously declared in /var/www/html/wp-content/plugins/listapp-mobile-manager/listapp-manager.php:223) in /var/www/html/wp-content/plugins/json-api/mstore-api.php on line 104```

**Comment by ameenbadri7** [comment]
Uninstall the plugin and download the latest version and then activate and try agian.
If that not working, I will let a higher developer to see your issue.
