### ISSUE TITLE
[MStore] workable links for  custom pages for Mstore

### ISSUE THREAD

**Issue by yosefasad** [inspireui/support#315]
I was expecting when i add a link in the config.js for the privacy and term and condition, about-us…the link should work.

<img width="789" alt="screen shot 2019-02-18 at 8 38 27 pm" src="https://user-images.githubusercontent.com/23431061/52968192-81bd1980-33bd-11e9-867c-24aa17557f73.png">

**Comment by minhcasi** [comment]
@luyx2412 - ref to this video - https://www.youtube.com/watch?v=OdNlWZCNJ_Y&feature=youtu.be shared by @yosefasad

**Comment by luyx2412** [comment]
Fixed in next version.

**Comment by yosefasad** [comment]
Thank you very much...

Waiting for the next release....
