### ISSUE TITLE
Feature Request: More robust store screens for Multi Vendor

### ISSUE THREAD

**Issue by enriqueleon80** [inspireui/support#3150]
Hello! Unbelievable template, I keep finding features as I dig in through this code.

I'm using the Multi Vendor app and can see that the single store app has a very tight integrated structure, while vendors received a sort of "plug-in" code base with it's own folder housing models, screens, etc.  It's good in that I can make modifications to your code base in a consolidated folder but at the same time it's clear that the existing logic didn't get extended.

1) A great example of this would be the search screen.  This screen is critically important, as I can filter, sort, by category, change layout, etc.  and (as I understand it) launch it from a configured home screen with pre defined settings.  Would be nice if we can add a store as filter criteria.

2) When I navigate to the vendor list it's just a big old list.  Stores should be filtered by category or area. NOTE: We are working on a work around/modificiation for our case.

3) When I open up the store detail screen the products are just listed.  Again, they need to be filterable, searchable, divided by category.

4) Ability to add home screen modules that show stores/vendors instead of products or product categories.

**Comment by minhcasi** [comment]
@enriqueleon80 - thank you so much for your suggestions - we will discuss with the technical team and keep an update 🎉

**Comment by minhcasi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Feature Request: More robust store screens for Multi Vendor](https://trello.com/c/iMGmpx8t/43-feature-request-more-robust-store-screens-for-multi-vendor)

**Comment by minhcasi** [comment]
moved to the backlog for further investigating and update

**Comment by mauriciozuniga** [comment]
Hi @enriqueleon80 How are you?  How did you manage to implement point 2? The category filter for stores? any suggestion on how can I implement it?

ThkS!

**Comment by enriqueleon80** [comment]
So the store model is quite simple, but it does include category ID.  So you have two options, you can select ALL stores ALL the time when you call the model GETSTORES method, and then just filter with a UI control.

Or, you would update the model to consume a category ID pre-selected on the UI and then filter.  

B/c I wanted to go with option #2, I shelved the enhancement for a subsequent release.  The first however is a simple option, and then implementing a category toolbar at the top or something.

Good luck!

**Comment by mauriciozuniga** [comment]
Thnks for the help Enrique! I will take a look at it

**Comment by Jazzykhan** [comment]
@enriqueleon80  did you manage to do all the changes i dont know luckily i need all the same features that you have given above. can you please share your lib folder or the code that does those changes i will be hugely thankful man...
thanks

**Comment by Jazzykhan** [comment]
GOD i need all those 4. Please help i am not a good developer.

**Comment by Jazzykhan** [comment]
hello @enriqueleon80 ???

**Comment by Jazzykhan** [comment]
hello @enriqueleon80 ?

**Comment by enriqueleon80** [comment]
Hi @Jazzykhan.  Wow man I'm so sorry to take so long to answer your repeated requests.  So just to make sure I understand before I send you the code.  You need me to send you all the code for my application that gives you vendor functionality features which the team is currently working on, which I've worked on for weeks.  Did I catch that right?

**Comment by Jazzykhan** [comment]
if you can that will help me a lot as i have also talked to the authors i can pay extra but they are not listening i can pay some amount to you Sir.
i will be very thankful.

**Comment by Jazzykhan** [comment]
I know it is a huge request but People are awesome i know that.

**Comment by enriqueleon80** [comment]
Got it, well... I haven't written this logic yet, but if I do before the boys deliver their own solution via feature request I'll let you know.

**Comment by Jazzykhan** [comment]
Which logic you have implemented right now? the dropdown or location thing?

**Comment by enriqueleon80** [comment]
It's all half way, nothing is finished.  Starting with: 

When I navigate to the vendor list it's just a big old list. Stores should be filtered by category or area. NOTE: We are working on a work around/modificiation for our case.

When I open up the store detail screen the products are just listed. Again, they need to be filterable, searchable, divided by category.

**Comment by Jazzykhan** [comment]
Can you tell me @enriqueleon80  did you manage to make the multi vendor chat working? i am not able to make it work can you guide for that?
thanks

**Comment by enriqueleon80** [comment]
> Can you tell me @enriqueleon80 did you manage to make the multi vendor chat working? i am not able to make it work can you guide for that?
> thanks

No I didn't use it, it just doesn't suit mee.  I ended up changing how the smart chat works and it opens up specific to a each business instead.  So the business can choose the type of communication they want through their own config on the backend.
