### ISSUE TITLE
Issue & solution to sign in (gmail or SMS) the Fluxstore v1.7.x

### ISSUE THREAD

**Issue by aishema2000** [inspireui/support#3151]
Step 1 (require): detail issues and screenshots
![image](https://user-images.githubusercontent.com/15066381/81570394-d53fcc80-93a0-11ea-999b-981e750346d8.png)

I don't need to send you my config files because this screenshots is the same using your own Demo config files. Demo app and my APP produce this same error.

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by iamar1k92** [comment]
you have not setup google OAuth consent screen on google developer console. 
https://docs.inspireui.com/fluxstore/sign-in/
refer to 1.2 in this link!

**Comment by aishema2000** [comment]
The google OAuth setup has been done sir. My setup has been working perfectly with old versions. See screenshot:
![image](https://user-images.githubusercontent.com/15066381/81573118-5d73a100-93a4-11ea-81fa-da989ac876b7.png)

ALSO NOTE YOUR DEMO APP IS HAVING SAME PROBLEM. The issue is with your app not firebase

**Comment by xsamir** [comment]
Everyone facing the same problem (Social login) with version 1.7.3
Most of the recent questions about this issue even me!

**Comment by iamar1k92** [comment]
please change the package name across the app, use that package name in the firebase and generate googleservices.json and place in into the project. Get the SHA1 keys and add them on firebase.

**Comment by xsamir** [comment]
Unfortunately, the problem not in the settings or integrating information
Everything was working fine on the previous versions of FluxApp, but on 1.7.3 it keep shows error!

**Comment by minhcasi** [comment]
@trunghieuvn - could you help to investigate this issue

**Comment by aishema2000** [comment]
All your suggested solutions here are not relevant, and can't solve the issue because it only happens with 1.7.3 version. You can also Try your own 1.7.3 demo app, it will never sign in.
My Google-service.json file is very very ok, because I can sign in with Fluxstore version 1.6.5, 1.6.6, 1.6.6b and 1.7.0 but IT BECOMES IMPOSSIBLE WITH 1.7.3 . Please investigate and provide a solution. Thanks.

**Comment by Amitjeypore** [comment]
Facing same problem

**Comment by xsamir** [comment]
Any solutions?
Because my project pending for three days without any new action for releasing because of that problem!

I already submitted a ticket without any response #3133

**Comment by engbasselayman** [comment]
I have the same problem, kindly is there any update ? ? ?

**Comment by minhcasi** [comment]
@aishema2000 @engbasselayman @xsamir @Amitjeypore @iamar1k92 

We have checked the previous version that happened on the same issues - it meant there was some polices change from Google authentication, could you try to double-check your setting from **OAuth consent screen** from your Google account? 

Related open ticket from Flutter: https://github.com/flutter/flutter/issues/33393

Example config from Fluxstore:
<img width="1124" alt="Screen Shot 2020-05-13 at 15 00 22" src="https://user-images.githubusercontent.com/1459805/81786917-7e65fe80-952a-11ea-9756-4c735e595f12.png">

**Comment by aishema2000** [comment]
1. Do you really see any difference between your OAuth consent screen and mine? 
![image](https://user-images.githubusercontent.com/15066381/81790154-47312680-9505-11ea-9345-618c94800d22.png)

2. If my configs have issues, then Why is your own demo APP is providing the same error. You can't sign in too.

3. Why are we able to sign in using Fluxstore Version 1.6.5, 1.6.6, 1.6.6b and 1.7.0 but only 1.7.3 fails?

I am still struggling to understand what's going on and searching everywhere for a solution, but please help us to crosscheck too because so long time without being able to launch our business.

**Comment by aishema2000** [comment]
1. Sir, Do you really see any difference between your OAuth consent screen and mine?
![console cloud google com_apis_credentials_consent_edit_project=iwacurwanda-2bcee duration=P1D(iPad Pro)](https://user-images.githubusercontent.com/15066381/81791006-73997280-9506-11ea-923a-3eea413f8854.png)


2. If my configs have issues, then Why is your own demo APP is providing the same error. You can't sign in too.

3. Why are we able to sign in using Fluxstore Version 1.6.5, 1.6.6, 1.6.6b and 1.7.0 but only 1.7.3 fails?

I am still struggling to understand what's going on and searching everywhere for a solution, but please help us to crosscheck too because so long time without being able to launch our business.

**Comment by minhcasi** [comment]
Yes, it works with our app demo before, but not sure it is not working now, the same with your situation, that's why you could see the ticket from Flutter 33393 still opening.

**Comment by aishema2000** [comment]
Okay. I understand. Let's fight together. If anyone finds a solution will share here. I am going to restart step by step will put my results here

**Comment by Amitjeypore** [comment]
Notjong is working,
My Fluxbuilder Rest API is not working too:
Mentioned my issues in datils here: https://github.com/inspireui/fluxbuilder/issues/77

![Capture_1](https://user-images.githubusercontent.com/65069372/81847198-e63f3800-9570-11ea-901f-36d170afd992.PNG)
![Screenshot_20200513-232215](https://user-images.githubusercontent.com/65069372/81847229-ef300980-9570-11ea-8ad5-40de8ba101f8.jpg)

**Comment by Amitjeypore** [comment]
Ok a development here, In my case oAuth was failing because of some ssl issue in my website. I updated my ssl and it started working fine.
SMS Login working
Google Login Working
Facebook Login Working

Rest API started working

Let me know if it works for you guys too.

PS why dont you guys add to your tutorial if SSL is mandatory for your site to get this login function to work.

**Comment by Amitjeypore** [comment]
Also there is a update to Mstore app to wordpress, anyone updated and see if it works.

**Comment by minhcasi** [comment]
@Amitjeypore - you could able to log in via Google SignIn as well? We are also using the https from our demo app but it is not worked for some reason.

**Comment by xsamir** [comment]
Enabled SSL, but still facing the same problem!

Can you please explain if you do any change on the app codes?

**Comment by xsamir** [comment]
FYI, I tried to go back to version 1.7.0, and it was working fine for all social logins!

I prefer if you can go back to the previous version and fix the bugs without touching the social logins codes.

**Comment by aishema2000** [comment]
You are right. Something is wrong with 1.7.3. I tried everything that I can imagine for the whole week now. I give up now. All other versions work fine but only 1.7.3 fails. I give up this version now, i go back to 1.7.0 until developers find a solution. Good luck.

**Comment by minhcasi** [comment]
Thank you for sharing - we will compare with 1.7.0 and update it shortly 

The demo on Google Play store works well as well - https://play.google.com/store/apps/details?id=com.inspireui.fluxstore&hl=en

**Comment by Aklilu-Alazar22** [comment]
Hi, any updates on the login issue

**Comment by mohamedibrahim89** [comment]
any updates to solve this issue

**Comment by minhcasi** [comment]
@mohamedibrahim89 @Aklilu-Alazar22 @aishema2000 - there is no luck with our checking so far, event switch to previous version 1.7.0 (which is worked well in the past), but it does not work now. 

Does anyone have experience with this issue?

**Comment by minhcasi** [comment]
@minhtruong315 @trunghieuvn - any help?

**Comment by minhcasi** [comment]
Some related bug from Google: https://github.com/flutter/flutter/labels/p%3A%20google_sign_in

Relate Open issues: https://github.com/flutter/flutter/issues/54255 https://github.com/flutter/flutter/issues/33393

**Comment by trunghieuvn** [comment]
![](https://camo.githubusercontent.com/8f47913622e766b5ce1b1b708b84d26e79e8b8cb/68747470733a2f2f70617065722d6174746163686d656e74732e64726f70626f782e636f6d2f735f374639353545393338374233334239383330333638413134353733413033303041383842383032443337343733413646393846413938423344464144334343445f313538383734353334363534335f696d6167652e706e67)

Please change bundle id (package name) and get SHA1 key add to console firebase  
https://github.com/inspireui/support/wiki/Setup-login-with-Google

**Comment by Amitjeypore** [comment]
Guys add both SHA1 and  SHA256 keys

**Comment by minhcasi** [comment]
@aishema2000 - please try to create a new key and update SHA1 to Firebase to fix this issue

![fix-login](https://user-images.githubusercontent.com/1459805/82194114-8229c480-9920-11ea-9398-ad95637aa71b.gif)

Follow this detailed guide from our Blog: https://medium.com/@inspireui/setup-google-login-for-flutter-apps-fedc58a490b8

**Comment by aishema2000** [comment]
@minhcasi Thanks. I am going to do this, and I will tell you the output. Please allow some few hours I will report here, the results.

**Comment by engbasselayman** [comment]
is there any news about the next version release

**Comment by aishema2000** [comment]
@minhcasi NO LUCK!

Things I did:
I followed step by step the above documentation on the medium blog. But no luck. I tried all solutions on different forums but there is no luck. 

AGAIN: Sir, I tried your own demo and it is still not working.

This SignIn issue is making me crazy. If anyone has a solution please share. The frustrating thing is that firebase error messages are not specific so We can't know exactly where to look for answers.

I will try again tomorrow to find solutions everywhere on the web, let's hope that one day there will be a solution

**Comment by trunghieuvn** [comment]
Hi @aishema2000 
Please add me to your gitub gitlab repo project and console firebase, I will check the problem and help you quickly handle it.

Email my github/gitlab/firebase: hieu.trantrung1204@gmail.com

**Comment by aishema2000** [comment]
Dear @trunghieuvn I have invited you to my firebase project as well as Github where I uploaded my app.. Waiting for your kind support. Thank you.

**Comment by mohamedibrahim89** [comment]
Finally
I use this command keytool -list -v -keystore /Users/mak/Desktop/trollak/android/app/key.jks -alias key
and add sha1 and sha256 in firebase google sign in work
u can try this

**Comment by Amitjeypore** [comment]
Same thing worked for me:

-Step 1 create a Keystore
-Step 2 Move it to the location
-Step 3 Create corresponding property file
-Step 4 enter the SHA1 & SHA256 Fingerprints in firebase
-Step 5 Regenerate the Google-Services.json
-Step 6 Move it to the location
-Step 7 Flutter Clean
-Step 8 Run your app and see

The tutorials provided is not for noobs like me, had to put hours and hours of research to find a solution.

**Comment by aishema2000** [comment]
> Same thing worked for me:
> 
> -Step 1 create a Keystore
> -Step 2 Move it to the location
> -Step 3 Create corresponding property file
> -Step 4 enter the SHA1 & SHA256 Fingerprints in firebase
> -Step 5 Regenerate the Google-Services.json
> -Step 6 Move it to the location
> -Step 7 Flutter Clean
> -Step 8 Run your app and see
> 
> The tutorials provided is not for noobs like me, had to put hours and hours of research to find a solution.
Dear @Amitjeypore 
1. Can you confirm you are using version 1.7.3 ??? Because even the fluxstore demo app signIn still not working.
2. Can you give more details of what you did on step 2 (which location are you talking about?) and step 3 (which corresponding property file?)

Thanks

**Comment by Aklilu-Alazar22** [comment]
@minhcasi @trunghieuvn can you give us a detailed explanation on what worked?.
thanks

**Comment by Amitjeypore** [comment]
Yes I am on 1.7.3

-Step 1 create a Keystore

In Powershell I used this command
keytool -genkey -v -keystore **c:/Users/Amit/key.jks** -storetype JKS -keyalg RSA -keysize 2048 -validity 10000 -alias **key**
Location where your keystore is going to be saved post this command processes: c:/Users/Amit/key.jks
Alias of your keystore: key

-Step 2 Move it to the Android location

Move the key.jks file to android/app/key.jks

-Step 3 Create a corresponding property file

Create a key.properties file with the following code:

storePassword=123456
keyPassword=123456
keyAlias=key
storeFile=key.jks

Move the key.properties to android/key.properties

-Step 4 enter the SHA1 & SHA256 Fingerprints in firebase

Open Powershell in Source/Android path and use this command

keytool -list -v   -alias **key** -keystore **app\key.jks**

The Key should be placed in the location above before using this command,
make sure the alias you provided is correct

If everything is right this command should show your SHA1 & SHA256 Fingerprints, copy-paste the same in your Firebase fingerprints

-Step 5 Regenerate the Google-Services.json after the Fingerprints are updated

-Step 6 Move it to the location

Replace the regenerated json file at android/app.google-services.json

-Step 7 Flutter Clean

Run the following command in your IDE terminal
Flutter Clean

-Step 8 Run your app and see

**Comment by aishema2000** [comment]
Thanks @Amitjeypore for your time, I think we are all closer to the solution, and this will help developers to write clean documentation for newbies😉.
LAST QUESTION
What are the procedures you took on the firebase side?

**Comment by engbasselayman** [comment]
I tested all the previous instructions and this is the output
https://mega.nz/file/MA8VkTjR#Nig_2P2Mq4pX2ARwh1XRg-A1gacKuqkJkFtzw_PpYf8
1- kindly is there any one can support me because my business is stopped.
2- is there any comming release soon which has no problem.
3- i applied a ticket to join you in gitlab and no one reply me.
kindly can you support me in fast

**Comment by Amitjeypore** [comment]
> Thanks @Amitjeypore for your time, I think we are all closer to the solution, and this will help developers to write clean documentation for newbies😉.
> LAST QUESTION
> What are the procedures you took on the firebase side?

I made sure my ecommerce domain was added to the firebase, thats all on the firebase side.

**Comment by aishema2000** [comment]
@Amitjeypore , Interesting, that means you do not use the default domain name in the OAuth consent screen? I will test all of this tomorrow. @trunghieuvn I sent you invitations you requested to help, any update? Dear @minhcasi what do you think about above updates, any discovery? I see the demo app still can not SignIn.

**Comment by engbasselayman** [comment]
> I tested all the previous instructions and this is the output
> https://mega.nz/file/MA8VkTjR#Nig_2P2Mq4pX2ARwh1XRg-A1gacKuqkJkFtzw_PpYf8
> 1- kindly is there any one can support me because my business is stopped.
> 2- is there any comming release soon which has no problem.
> 3- i applied a ticket to join you in gitlab and no one reply me.
> kindly can you support me in fast
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/fb61704d3d66ebf807dc8f6ae64551836d60a54a/68747470733a2f2f6d6567612e6e7a2f726963682d66696c652e706e67">**[File on MEGA](https://mega.nz/file/MA8VkTjR)**MEGA provides free cloud storage with convenient and powerful always-on privacy. Claim your free 50GB now

> I tested all the previous instructions and this is the output
> https://mega.nz/file/MA8VkTjR#Nig_2P2Mq4pX2ARwh1XRg-A1gacKuqkJkFtzw_PpYf8
> 1- kindly is there any one can support me because my business is stopped.
> 2- is there any comming release soon which has no problem.
> 3- i applied a ticket to join you in gitlab and no one reply me.
> kindly can you support me in fast
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/fb61704d3d66ebf807dc8f6ae64551836d60a54a/68747470733a2f2f6d6567612e6e7a2f726963682d66696c652e706e67">**[File on MEGA](https://mega.nz/file/MA8VkTjR)**MEGA provides free cloud storage with convenient and powerful always-on privacy. Claim your free 50GB now!

this is my email that i purchased with it and it is the same of gitlab
aymanbasel611@gmail.com

**Comment by Mcrahul555** [comment]
> 
> 
> Okay. I understand. Let's fight together. If anyone finds a solution will share here. I am going to restart step by step will put my results here

after adding sha 1 key its working fr me 

sms login

**Comment by minhcasi** [comment]
@aishema2000 - how is your checking?

**Comment by aishema2000** [comment]
@minhcasi I give you update tomorrow. Thanks

**Comment by xsamir** [comment]
Hello Everyone 😄 

**### I found the solution** 👍 
Please read carefully

In the beginning the main problem will face a lot of you is that you are getting the wrong SHA1 & SHA256 code! 
When you use this code for example: _keytool -list -v -keystore C:\Users\MG\Desktop\test.jks -alias test_
it will show the current code not the code which the app build with, so I recorded a video for the full solution to fix that and the common problem will be caused by Facebook as well!
**Here's the video with English subtitle**: https://www.youtube.com/watch?v=spC-CJzlno4 🎥 

**The second problem**, that Firebase doesn't support the old Google Play services on the phones, that means you need to update it by following these steps from your smartphone:
- Settings > Apps > Apps > Google Play services > App Details
then check for updates.
![image](https://user-images.githubusercontent.com/7432001/82726616-1c598600-9cee-11ea-87e3-3965d715e5e4.png)


For me I'm using Huawei mate 20 pro, the new update wasn't available, but it works for Samsung s20 and Oppo Reno 2... also not worked on the emulator of Android studio
For Huawei, **I solved the problem** by downloading the update manually from here: https://www.apkmirror.com/apk/google-inc/google-play-services/
I think the problem is the Google ban on Huawei phones

Everything should work fine now.

The last thing I want is to help me with another problem  :D here: https://github.com/inspireui/support/issues/3364

**Comment by Albertoswift** [comment]
Any solution for PlatformException(sign_in_required,com.google.android.gms.common.api.ApiException: 4: 4: , null)? I have been searching online for days to no avail

**Comment by xsamir** [comment]
> 
> 
> Any solution for PlatformException(sign_in_required,com.google.android.gms.common.api.ApiException: 4: 4: , null)? I have been searching online for days to no avail

Try to follow the Fluxstore documentation

**Comment by minhcasi** [comment]
@aishema2000 - thank you so much for your sharing with detail video 🥇

**Comment by minhcasi** [comment]
@aishema2000 - let us know if you could fix the issue - thank you!

**Comment by aishema2000** [comment]
@minhcasi Nonw I am going to apply @xsamir solution, and ill will come back here shortly...

**Comment by ajatsoft** [comment]
NOT working, firebase works well and register is added to users, but not register user to Wordpress. 

is posible to register directly to Wordpress?

**Comment by aishema2000** [comment]
😎❤️
Dear @xsamir thank you so much. I can confirm that your method works, there are important improvements. The Login with email works perfectly, but **SMS login after receiving the phone code, will take around 1 to 2 minutes to login**, dear @minhcasi please check that.

The documentation needs to focus on this part, generating SHA1 and SHA256 keys.

@Amitjeypore I din't have time to test your method, but if it deals with the way we generate the SHA1 and SHA256, then it should work too.

For those who are still facing the issue:

1. Follow strictly the official documentation ( https://medium.com/@inspireui/setup-google-login-for-flutter-apps-fedc58a490b8) 
2. If you fail, try @xsamir solution above about how to get a working SHA1 and SHA256 keys. or try @Amitjeypore 

**IMPORTANT RECOMMANDATION TO FLUXSTORE DEVELOPPERS TEAM.**

Please, make very very very clean documentation, this will avoid you to always have to troubleshoot very simple issues.

Thanks @xsamir @Amitjeypore and @minhcasi for your kind support!

**Comment by minhcasi** [comment]
@aishema2000 - congratulation and thank you very much for your feedback! Are you happy to close this ticket so far 🎉

**Comment by aishema2000** [comment]
Sure @minhcasi , let's close the ticket.

**Comment by Nic-Tai** [comment]
Hi dear admin. i have followed the step mentioned here, to add the sha1 and sha256 to firebase. and my google play services is already version 20.18.17, but when i try to register using email with my flutter app, it still gives error message of:
Exception: Unknown controller 'flutter_user'.

*im using the FluxStore-listing 1.4.1 not fluxstore v1.7.x.
