### ISSUE TITLE
Some input files use or override a deprecated API.

### ISSUE THREAD

**Issue by gelocaindoy** [inspireui/support#3152]
Step 1 (require): detail issues and screenshots

![image](https://user-images.githubusercontent.com/65111463/81581964-0987ad00-93e2-11ea-8c7d-2aab8910cc0c.png)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@gelocaindoy - thank you for your notice, don't worry about these warning messages as it will be fixed after the pubspec library upgrade on later release, most of the libraries from flutter are up-to-date 👍
