### ISSUE TITLE
[FluxStore WooCommerce] 1.7.3 is duplicating category names on side menu. +Other request

### ISSUE THREAD

**Issue by alexrali** [inspireui/support#3155]
Step 1 (require): detail issues and screenshots

after several test on development environment on 1.7.3 version, i found that there are category names repeating on the side menu.

Also i have a question, there is a place to configure straightforward a loading animation on select a category product listing?

thanks in advance

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by alexrali** [comment]
On the update 1.7.4, same issue 

![WhatsApp Image 2020-05-12 at 11 12 57 AM](https://user-images.githubusercontent.com/4369002/81718836-da088d00-9441-11ea-80bb-97840127d902.jpeg)

On the update 1.7.4, same issue
category names on side menu is repeating, and if the application are opened several times.

Currently in woocommerce site there are +180 categories, i have to say that this is working with no issues in 1.6.6 version, i mean, in that version there are no repeating categorys in side menu. 

I alredy sent the "common" folder for debug purposes. 

Grettings

**Comment by alexrali** [comment]
It seems to be related or a connectivity issue, due to if the app open on wifi, it repeat category names, and if it open by mobile data apparently it load with no duplicate items

**Comment by minhcasi** [comment]
@alexrali - pls help us to submit your verify purchase detail to http://private.inspireui.com/ - thank you for your time

**Comment by alexrali** [comment]
of course,
it is already done

**Comment by minhcasi** [comment]
@philipvu30 - pls help for checking - thank you!

**Comment by philipvu30** [comment]
Hi,

1. I have tested your config with poor connection condition and no problem was found.
2. 
- If you are mentioning the cube loading thing, you can modify it here lib/common/constants/loading.dart

- If you are mentioning the loading animation when products are being loaded, you can find it here lib/widgets/common/skeleton.dart

**Comment by alexrali** [comment]
hi, thanks for the reply, 

1. 
i have to say that the app is doing the same way. Now its repeating 3 times. 

![InkedWhatsApp Image 2020-05-14 at 9 17 03 AM_LI](https://user-images.githubusercontent.com/4369002/81946277-cafe1800-95c4-11ea-92b8-530b458be16f.jpg)

Maybe something in the load process after or between the splash screen and the home screen is doing the problem. Again, say that in version 1.6.6, this situation was not happening

2. Thank you, i will look in that files.

**Comment by philipvu30** [comment]
Hi,

For issue number 1, can you try to add this term to the file lib/menu.dart

![image](https://user-images.githubusercontent.com/54442328/82023860-1eea2900-96b9-11ea-822e-ba354658a33a.png)

As I have no problem when reproducing this issue, please pull our latest version from GitLab and see if the issue still persists.

**Comment by philipvu30** [comment]
Hello,

We usually close the ticket after 2 days of no response. Feel free to ask me to re-open your ticket if you encounter any problem. Thanks
