### ISSUE TITLE
Failed assertion: boolean expression must not be null exception

### ISSUE THREAD

**Issue by Cheewingtan** [inspireui/support#3156]
Step 1 (require): detail issues and screenshots
on version FluxStore-vendor-1.7.3 when I run flutter run it display this error on home page of the app other page is ok only home page display this error
<img width="367" alt="Screenshot 2020-05-12 at 11 37 24 AM" src="https://user-images.githubusercontent.com/11556877/81635908-070a6f00-9445-11ea-8e40-26b88f71bc08.png">

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by papaya1986** [comment]
yes these issue also here

**Comment by minhcasi** [comment]
@Cheewingtan @papaya1986 - we will update the Gitlab to fix this issue shortly - thank you!

**Comment by harjono-flux** [comment]
@Cheewingtan try this 
![Screen Shot 2020-05-16 at 08 03 23](https://user-images.githubusercontent.com/64935574/82105007-b8fab180-974b-11ea-9f9d-f4447f16dac4.png)

**Comment by Cheewingtan** [comment]
> @Cheewingtan try this
> ![Screen Shot 2020-05-16 at 08 03 23](https://user-images.githubusercontent.com/64935574/82105007-b8fab180-974b-11ea-9f9d-f4447f16dac4.png)

not work to me ,ios and android same error

**Comment by minhcasi** [comment]
@Cheewingtan - please help to move your conversation to the same ticket #3254 - thank you!
