### ISSUE TITLE
Drawer Layout (left menu side)

### ISSUE THREAD

**Issue by premod** [inspireui/support#3157]
**referencing from documentation, while doing drawer layout (left side menu), i am having some errors,
To add new menu item, go to lib/tabbar.dart**

drawer: Drawer(
    child: SingleChildScrollView(
        child: Column(
            children: <Widget>[
                DrawerHeader(
                    child: Row(
                        children: <Widget>[
                            Image.asset(kLogoImage, height: 38),
                        ],
                    ),
                    decoration: BoxDecoration(
                        color: Colors.white,
                    ),
                ),
                Padding(
                    padding: const EdgeInsets.only(left: 15.0),
                    child: Column(
                        children: <Widget>[
                            ListTile(
                                leading: Icon(
                                    Icons.shopping_basket,
                                    size: 20,
                                ),
                                title: Text(S.of(context).shop),
                                onTap: () {
                                    Navigator.pushReplacementNamed(context, "/home");
                                },
                            ),
                            ListTile(
                                leading: Icon(FontAwesomeIcons.wordpress, size: 20),
                                title: Text(S.of(context).blog),
                                onTap: () {
                                    Navigator.pushNamed(context, "/blogs");
                                },
                            ),
                            ListTile(
                                leading: Icon(FontAwesomeIcons.heart, size: 20),
                                title: Text(S.of(context).myWishList),
                                onTap: () {
                                    Navigator.pushNamed(context, "/wishlist");
                                },
                            ),
                            ListTile(
                                leading: Icon(Icons.exit_to_app, size: 20),
                                title: loggedIn
                                ? Text(S.of(context).logout)
                                : Text(S.of(context).login),
                                onTap: () {
                                    loggedIn
                                        ? Provider.of<UserModel>(context).logout()
                                        : Navigator.pushNamed(context, "/login");
                                },
                            ),
                            SizedBox(
                                height: 20,
                            ),
                            ExpansionTile(
                                initiallyExpanded: true,
                                title: Text(
                                    S.of(context).byCategory.toUpperCase(),
                                    style: TextStyle(
                                        fontSize: 14,
                                        fontWeight: FontWeight.w600,
                                        color: Theme.of(context)
                                        .accentColor
                                        .withOpacity(0.5),
                                    ),
                                ),
                                children: showCategories(),
                            ),
                        ],
                    ),
                )
            ],
        ),
    ),
),

**i just replaced this code on the lib/tabbar.dart, in drawer line**

Compiler message:
lib/tabbar.dart:347:47: Error: 'UserModel' isn't a type.
                                ? Provider.of<UserModel>(context).logout()
                                              ^^^^^^^^^
lib/tabbar.dart:327:41: Error: The getter 'FontAwesomeIcons' isn't defined for the class 'MainTabsState'.
 - 'MainTabsState' is from 'package:fstore/tabbar.dart' ('lib/tabbar.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'FontAwesomeIcons'.
                          leading: Icon(FontAwesomeIcons.wordpress, size: 20),
                                        ^^^^^^^^^^^^^^^^
lib/tabbar.dart:334:41: Error: The getter 'FontAwesomeIcons' isn't defined for the class 'MainTabsState'.
 - 'MainTabsState' is from 'package:fstore/tabbar.dart' ('lib/tabbar.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'FontAwesomeIcons'.
                          leading: Icon(FontAwesomeIcons.heart, size: 20),
                                        ^^^^^^^^^^^^^^^^
lib/tabbar.dart:342:34: Error: The getter 'loggedIn' isn't defined for the class 'MainTabsState'.
 - 'MainTabsState' is from 'package:fstore/tabbar.dart' ('lib/tabbar.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'loggedIn'.
                          title: loggedIn
                                 ^^^^^^^^
lib/tabbar.dart:346:29: Error: The getter 'loggedIn' isn't defined for the class 'MainTabsState'.
 - 'MainTabsState' is from 'package:fstore/tabbar.dart' ('lib/tabbar.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'loggedIn'.
                            loggedIn
                            ^^^^^^^^
lib/tabbar.dart:366:37: Error: The method 'showCategories' isn't defined for the class 'MainTabsState'.
 - 'MainTabsState' is from 'package:fstore/tabbar.dart' ('lib/tabbar.dart').
Try correcting the name to the name of an existing method, or defining a method named 'showCategories'.
                          children: showCategories(),
                                    ^^^^^^^^^^^^^^
Restarted application in 2,562ms.

**can u please solve my issue, my current drawer is the default one, i would like to change it.

**

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as it could not be verified, please create the new one when you got enough purchased info - thank you!
