### ISSUE TITLE
[FluxStore Woocommerce] 1.7.3 - For a simple product, attributes are not shown in App

### ISSUE THREAD

**Issue by chikip** [inspireui/support#3158]
Step 1 (require): detail issues and screenshots
1. Simple product type in Woocommerce has a few attributes they show up fine in the website but do not come up in the app

![Attributes](https://user-images.githubusercontent.com/63201901/81640584-86e00b80-943c-11ea-85d0-6e37e501edfc.jpg)

![Site att](https://user-images.githubusercontent.com/63201901/81640801-22717c00-943d-11ea-8a6f-b5cba9c56046.jpg)

![emulator](https://user-images.githubusercontent.com/63201901/81640885-551b7480-943d-11ea-841e-0c5a12b0aa50.jpg)

Kindly look into this issue, thank you

2. I had previously also raised this issue - A product category requires quantity in decimal form. For eg. 1.5 kg or 0.5 kg. This does not get reflected in the app.

It would be really nice if you can suggest me any solution/workaround for this.

![Rib Site](https://user-images.githubusercontent.com/63201901/81641497-c1e33e80-943e-11ea-88c3-b11de5bdcffd.jpg)

![Rib App](https://user-images.githubusercontent.com/63201901/81641628-1686b980-943f-11ea-8464-3b0db3a98b9a.jpg)

My app is almost ready, but for these two issues.

Thanks a lot for your tutorials and support, it has been a great experience 👍 

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

For customer verification you can check my previous ticket no. #2755 , thank you

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by philipvu30** [comment]
Hi,

1. Have you checked these options? 
![image](https://user-images.githubusercontent.com/7034048/78338453-80d45080-759b-11ea-87e0-be077e6936e2.png)

2. You can make that product variable with additional attributes like 0.5 kg or 1.5 kg

**Comment by chikip** [comment]
1. The product shown in the image is "Variable product" whereas my product is simple product. Is it possible to view product attributes in "additional information" as it shows in the website?

2. That would add a very high number of attributes, like 0.1, 0.2, 0.3.......10.1, 10.2......kgs for every product, also the stock management would be troublesome.
This does not seem feasible, any other convenient method/workaround available?

Thank you

**Comment by philipvu30** [comment]
Hi,

1. Currently, this feature has not been implemented yet. We'll try to update it in the next release.
2. Are you using an external plugin to make the stock quantity decimal? We'll look into this issue as there are some concerns about it.

**Comment by chikip** [comment]
1. Okay, till then I guess I'll write these attributes in Product Description Tab.

2. To make the stock quantity decimal I am currently using this plugin - https://wordpress.org/plugins/quantities-and-units-for-woocommerce/, there are other plugins also like this https://wordpress.org/plugins/product-quantity-for-woocommerce/.
I am awaiting your response in this particular issue to launch my app.

Thank you.

3. I also encountered another issue - while logging in through SMS via Firebase, OTP SMS is sent and received in the first try, but if I log out of the app and try to log in again the SMS is neither sent nor received in the device.
I have tried this in 3 different physical devices with the same result.
In another app built on flutter platform and using firebase SMS integration, I have noticed that after sending OTP one time, if I log out and log back in, the app automatically signs me in based on my previous login.
Kindly look into this issue.
Thank you

![SMS](https://user-images.githubusercontent.com/63201901/81900527-9ac17400-95da-11ea-86e8-1c4f1cb76582.jpg)

**Comment by philipvu30** [comment]
Hi,

About your issue number 3, may I ask are you using a release SHA 1 key or debug SHA 1 key? Also according to [Firebase doc](), this may be the problem you are facing.

> To prevent abuse, Firebase enforces a limit on the number of SMS messages that can be sent to a single phone number within a period of time. If you exceed this limit, phone number verification requests might be throttled. If you encounter this issue during development, use a different phone number for testing, or try the request again later.

**Comment by chikip** [comment]
Hello :)
I am using both the keys - SHA1 debug and release key. Google login is working perfectly fine.
I seriously doubt if just using Google's Firebase SMS feature for the second time or third time will amount to usage abuse.
I am attaching a video, in that video the app was used for the first time on that handset.
Kindly have a look.

https://drive.google.com/open?id=10IC6aeMbjwoZH0tYAxrNZ0ZTM4X9VJzC

Thank you

**Comment by philipvu30** [comment]
Hi,

I see what is the problem here. You cannot request 2 SMS verifications in a short period of time. 
I'll forward this issue to the technical team to find a solution. Thanks for pointing it out.

For further questions or issues, kindly post them here. Also, we usually close the ticket after 2 days of no response/issue. Feel free to ask us to re-open the ticket. Thank you.

**Comment by chikip** [comment]
If there is any update in these issues do let me know, in the meantime I am closing this ticket.

Thank you

**Comment by chikip** [comment]
1. In the latest 1.7.5 build, the name of category on home page gets cut

![Screenshot_20200608-151524~2](https://user-images.githubusercontent.com/63201901/84020584-abc69080-a9a0-11ea-9790-df4dcb11e16e.png)

it was not the case with 1.7.3

![Screenshot_20200608-151719~2](https://user-images.githubusercontent.com/63201901/84020639-c0a32400-a9a0-11ea-807c-c0847413c28a.png)

2. Also the smartchat button has disappeared from settings page in version 1.7.5

![Screenshot_20200608-155516](https://user-images.githubusercontent.com/63201901/84020768-fba55780-a9a0-11ea-8b3b-b5484558c748.png)

Kindly look into the issues, thank you

**Comment by philipvu30** [comment]
Hi,

We have been aware of these issues and they are currently under investigation.

**Comment by chikip** [comment]
Hi,
Should I keep this ticket open or close it.

**Comment by philipvu30** [comment]
Hi,

For issue number 1, open this file lib/widgets/home/category/category_icon_items.dart and replace these attributes to meet your need.

![image](https://user-images.githubusercontent.com/54442328/84373794-46280d80-ac07-11ea-88f5-c0d98d6e7943.png)

![image](https://user-images.githubusercontent.com/54442328/84373838-53dd9300-ac07-11ea-97b0-7bd12d575388.png)

Issue number 2 has not been fixed yet. I will update it later.

**Comment by chikip** [comment]
@philipvu30  Thanks a lot it's working perfectly fine now.

If there is any update regarding the decimal quantity issue do let me know, I am closing this issue as of now

Thank you

**Comment by chikip** [comment]
Hi @philipvu30 

When clicking on any category icon from the top of home page and then clicking on any sub-category only 20 products are shown.

This is the same for your app on Google Play Store. For your 'Jeans Man' category you have 24 products, but when you select any category icon on home page and try viewing it you will only see 20 products.
Kindly look into this issue.

Thank you

**Comment by philipvu30** [comment]
Hi,

For woocommerce version, please comment these lines and add this code in this file lib/models/product/product_model.dart

```
      if (page == 0 || page == 1) {
        productsList = products;
      } else {
        productsList = [...productsList, ...products];
      }
```

![image](https://user-images.githubusercontent.com/54442328/84730134-957f8c80-afbf-11ea-941f-4a4af6d13c36.png)

**Comment by chikip** [comment]
Hi @philipvu30 
Your modifications did not work in the beginning, I tried removing comment from these 3 lines

```
bool isExisted = productsList.indexWhere(
              (o) => products.isNotEmpty && o.id == products[0].id) >
          -1;
```
and it worked flawlessly.

Thanks for this code

Any update regarding the product decimal quantity?

Thank you

**Comment by philipvu30** [comment]
Hi,

>Your modifications did not work in the beginning, I tried removing comment from these 3 lines

It's strange because these lines of code do not make any difference. But I'm glad it helped.

>Any update regarding the product decimal quantity?

I just asked the one who is in charge of this project, I'm afraid I cannot help you on this one as we only support the default WooCommerce features.

My apologies for this inconvenience.

**Comment by chikip** [comment]
No issues, I'll keep checking your updates in case this new feature gets added.

Thanks anyways
