### ISSUE TITLE
[Beonews] Android FlatList + RTL + horizontal issue

### ISSUE THREAD

**Issue by hadi13** [inspireui/support#316]
**Mandatory Info (please complete the following information):**
In beonews, when I click on a post it shows another one
I have this issue on Android only using expo

Product: [Beonews]
Your Purchased Code: 2b7fa788-ea4d-4d1c-bb3a-4bf22a499783

**Describe the issues**
I have an issue since the first time, the comments are not delivered to the WP admin?
**Screenshots**

**Additional context**
I need to solve it ASAP

**Comment by minhcasi** [comment]
note for checking - could you able to share your testing admin login so that we could help for checking - thanks

relate #252

**Comment by hadi13** [comment]
I already share them with you 
You can use this
Admin panel http://hhz20.co/KHN/wp-login.php

Login
user
aTaue@pXtvMuGZ%D#dYZ*63D

Please this issue is killing me, it is the only one I am facing 

<blockquote><div><strong><a href="http://hhz20.co/KHN/wp-login.php">Log In ‹ تطبيق الخويلدية — WordPress</a></strong></div></blockquote>

**Comment by minhcasi** [comment]
Noted for investigating - thanks

**Comment by hadi13** [comment]
when should I expect you to solve this ?

**Comment by hadi13** [comment]
any update?!!!

**Comment by luyx2412** [comment]
Hi @hadi13 Can you provide your Config.js and AppConfig.json file? I just tested the comment on Android, everything worked normal.

Thanks

**Comment by hadi13** [comment]
config.js 
https://drive.google.com/file/d/1DqlWbLugauboaByQazY3Is-p-FU8n8c6/view?usp=sharing
appconfig.json
https://drive.google.com/file/d/1J5P5ft5bPSz2hd9_acLBjUJqHluBL0wL/view?usp=sharing

**Comment by hadi13** [comment]
to clarify I have two issues, the comments issue and the posts issue,

by the way I have the pro version, but how can I make it RTL?

**Comment by hadi13** [comment]
Still struggling with this issue since 8 days now without a solution from you guys, if you can not solve your programming issues, who will solve it for your customers??!!!

**Comment by luyx2412** [comment]
Hi @hadi13 Please update new version 3.7 which improved RTL. And please select User Profile in bottom tab, after that change Language to Arabic which will change RTL.

Thanks

**Comment by hadi13** [comment]
now I am having this issue in android and you are hiding !!
![image](https://user-images.githubusercontent.com/2642454/53474218-89e01d80-3a7d-11e9-947b-5a3b08057ce4.png)

**Comment by hadi13** [comment]
I need someone from the support team to connect with me on team viewer and fix android issue ASAP

**Comment by minhcasi** [comment]
@hadi13 please try following solution:
1 - use the fresh project without modify grade file on Android
2 - start the Android simulator first
3 -  run following script:
yarn start --reset-cache
react-native run-android

Let us know your checking then, and share the detail error screenshot, please still not success we will help for Teamviewer on tomorrow - thanks

**Comment by hadi13** [comment]
I am building the app successfully but I am facing this issue 


help to solve it please 
![screenshot_20190227-200048_](https://user-images.githubusercontent.com/2642454/53509024-00a40780-3acc-11e9-828f-009721c8fa6e.jpg)

**Comment by luyx2412** [comment]
Hi @hadi13 Please follow the article to fix the issue. https://medium.com/@adityasingh_32512/solved-unable-to-load-script-from-assets-index-android-bundle-bdc5e3a3d5ff

Thanks

**Comment by hadi13** [comment]
Ok, this is solved the issue, but another issue is there, in android if `i open one post it opens another one, it is not opening the post I click @luyx2412 @minhcasi @minhtruong315 @thangvo9x

**Comment by hadi13** [comment]
any advise?

**Comment by hadi13** [comment]
Come on guys!!!! 
Should I request you every time to solve those problems!!!

**Comment by minhcasi** [comment]
Hi @hadi13 - we could not replicated this issues "in android if `i open one post it opens another one" - can you provide the screenshot and show us which the post that you are testing on our app demo ?

**Comment by hadi13** [comment]
ok see this video and focus on the photos of the post since it is on deferent language 
check this video https://www.youtube.com/watch?v=OLi1sdXZJ94&feature=youtu.be

**Comment by minhcasi** [comment]
@hadi13 - could you confirm the download is from the fresh package without modifying any function/components (except the common config) ? 

As we could not reproduce this issues from the original app so that we thinks there is something wrong with your customization

Thanks

**Comment by hadi13** [comment]
yes, it is fresh download without any changes

**Comment by hadi13** [comment]
where are you friend ??????!!!1

**Comment by minhcasi** [comment]
Could you send your source to support@inspireui.com as this is public chat? Thanks

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hadi13** [comment]
> Could you send your source to [support@inspireui.com](mailto:support@inspireui.com) as this is public chat? Thanks
> 
> Sent with [GitHawk](http://githawk.com)

sent to you please try to solve today ASAP, 12 days to solve this is very long period @minhcasi

**Comment by minhcasi** [comment]
Hi man,  got your file and we are checking, thanks

**Comment by hadi13** [comment]
since 4 hours, just now ! Ok will see

**Comment by minhcasi** [comment]
Why all the data is gone on your website? 
<img width="459" alt="screen shot 2019-03-03 at 7 33 40 pm" src="https://user-images.githubusercontent.com/1459805/53695236-60abee00-3deb-11e9-96e8-b63de1eae234.png">

**Comment by hadi13** [comment]
I am cleaning the old posts, you can posts or I will add now

**Comment by hadi13** [comment]
I have added on more, you can test on those posts

**Comment by minhcasi** [comment]
@hadi13 - confirm this is the bug on the Android - Flatlist with RTL on horizontal (https://github.com/facebook/react-native/issues/19150), so we need to get the update from RN to fix this issue.

Our temporary solution only displays the single PostDetailView from the PostDetail/index.js  (line 86) if the Platform is on Android.

Thanks

**Comment by hadi13** [comment]
So, what is the solution now exactly, what code should I change? 
Give me exact edit or change please

**Comment by minhcasi** [comment]
File: App/Container/PostDetail/index.js - update the if condition as below (also make sure import the Platform at the top. 
```
renderContent = postList => {
    const { onViewPost, onBack, index, post } = this.props;
    const { pageIndex } = this.state;

    if (typeof index === "undefined" || postList.length === 0 || Platform.OS == 'android') {
      return (
        <PostDetailView
          post={post}
          onBack={onBack}
          onViewPost={onViewPost}
          onNext={() => {}}
          onPostComment={() => this.refs.input.show()}
        />
      );
    }
```

**Comment by hadi13** [comment]
how to rebuild the app after changing this code? I changed and rebuild the code with the same issue!
am I missing something?

**Comment by hadi13** [comment]
you have my source code, please fix the issue and send back to me, I tried your temporary solution with no luck

**Comment by hadi13** [comment]
still waiting for your reply

**Comment by minhcasi** [comment]
Just overwrite this file will fix the issues - https://www.dropbox.com/s/csdsrysay9ud26d/index.js?dl=0 

Path: App/Container/PostDetail/index.js

**Comment by hadi13** [comment]
Comments are not delivered to my admin wp panel!!!!

**Comment by hadi13** [comment]
your push notification is not for expo version?!! 
https://beonews.inspireui.com/advance-customize/push-notification
what about expo version??
  notification: {
    AppId: '4f52b601-6f4e-4785-8e19-73hshsb6dfa',
    NewAppId: '4f52b601-6f4e-4785-8e19-29sjswb6dfa',
  },

**what is the NewAppId???**

**Comment by mustafamsy** [comment]
بتتعب وياهم يا هادي 
الدعم حقهم مو لهناك
