### ISSUE TITLE
Please agree with our terms Error on sign up

### ISSUE THREAD

**Issue by kenngigz** [inspireui/support#3160]
Step 1 (require): detail issues and screenshots

![Screenshot_2020-05-12-10-09-43 1](https://user-images.githubusercontent.com/57593885/81650058-f7d1f400-9439-11ea-861c-1103891521e4.png)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@kenngigz - we will have a check and let you know, pls move the conversation to #3044
