### ISSUE TITLE
[Fluxstore Multivendor] No Such Method Error

### ISSUE THREAD

**Issue by gelocaindoy** [inspireui/support#3162]
Step 1 (require): detail issues and screenshots

![image](https://user-images.githubusercontent.com/65111463/81667905-7cdafe80-9476-11ea-9ac0-6d26e095e7c4.png)

Hi

How to solve this?

Thanks!
Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by gelocaindoy** [comment]
Additional image

![image](https://user-images.githubusercontent.com/65111463/81688373-1fea4300-948c-11ea-952f-b0dd869569c7.png)

**Comment by gelocaindoy** [comment]
up

**Comment by gelocaindoy** [comment]
@kvt0012 hi any help please

**Comment by gelocaindoy** [comment]
@minhcasi hi any help please

**Comment by minhcasi** [comment]
@gelocaindoy - as your are using the fluxstore MV so that the serverConfig for  `"type": "woo"` is invalid and will not work - could you try to change to `dokan` or `wcfm`

**Comment by minhcasi** [comment]
We will upload the latest release to gitlab today as well - please help to update the latest version - thank you!

**Comment by gelocaindoy** [comment]
@minhcasi noted on this, i will try and give an update

for the gitlab latest release is this the file https://github.com/inspireui/support and i will paste it to the folder of my source?

**Comment by minhcasi** [comment]
@gelocaindoy - you could submit the gitlab access on this link https://docs.google.com/forms/d/e/1FAIpQLSeuBqUkScy42V7KKhfNPj0fl581anrB1mWkbMa3p2WQt7fhfw/viewform

**Comment by gelocaindoy** [comment]
@minhcasi hi done for the submission.
thanks

**Comment by minhcasi** [comment]
@gelocaindoy - thank you, we got the info 👍

Please move the conversation to your same ticket #3240 - our team will keep update there
