### ISSUE TITLE
[FluxStore Pro][OpenCart] Exception: Forbidden Error on checkout

### ISSUE THREAD

**Issue by umarmeo** [inspireui/support#3163]
Step 1 (require): detail issues and screenshots
Hello,
I am getting Exception: Forbidden Error while clicking on checkout Button. Its not proceeding further. Please guide me how to resolve this.
Thanks

![image](https://user-images.githubusercontent.com/21283229/81677931-bc9be900-946a-11ea-9e80-6e5b64341fcd.png)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

**Comment by minhtruong315** [comment]
@umarmeo what is opencart version on your website?

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
