### ISSUE TITLE
Don't show image product in Fluxstore Listing app

### ISSUE THREAD

**Issue by ton2engin** [inspireui/support#3164]
Step 1 (require): detail issues and screenshots

Hello sir,

I have problem not show image product in front screen,product screen but text is show normal(red circle ) , if click product have image normal  .

<a href="https://www.img.in.th/image/UoqC7L"><img src="https://s3-ap-southeast-1.amazonaws.com/img-in-th/ac3987ad5fdb537d97fea59d39d27da9.md.png" alt="ac3987ad5fdb537d97fea59d39d27da9.png" border="0" /></a>

**I check serverConfig in config.dart is correct**

**Regenerate Thumbnails already** 

**In website have images normal**

please support this case.
Thank you.

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by philipvu30** [comment]
Hi,

Currently, there is an issue with images in Listeo theme. We are trying to find a solution.

I'll get back to you when it has been solved.

**Comment by philipvu30** [comment]
Hi,

Please refer to this [comment](https://github.com/inspireui/support/issues/2801#issuecomment-628467469) to solve this issue. Thanks

**Comment by ton2engin** [comment]
Dear Sir 

I try all but image product not show. 
1.) Update plugin = ListApp Mobile Manager
2.) Change file: lib/models/product.dart with change this term kDefaultImage to item.
3.) Remove lines of cod in : lib/services/listing.dart
4.) In rest API controller plugin and turn off enable all for listing.

Please check again. 
Thank you.

**Comment by ton2engin** [comment]
My logcat as below ...

flutter: image 313
flutter: image 314
flutter: image 315
flutter: image 316
flutter: image 317
flutter: image 319
flutter: image 318
flutter: image 320
flutter: image 321
flutter: image 322
flutter: fetchProductsLayout done
flutter: url 313
flutter: url 313
flutter: NoSuchMethodError: The getter 'statusCode' was called on null.
Receiver: null
Tried calling: statusCode
flutter: NoSuchMethodError: The getter 'statusCode' was called on null.
Receiver: null
Tried calling: statusCode
flutter: Bad state: Failed to load 313-medium.
flutter: Listing.fromJson: type 'String' is not a subtype of type 'Map<String, dynamic>'
flutter: url 313
flutter: NoSuchMethodError: The getter 'statusCode' was called on null.
Receiver: null
Tried calling: statusCode
flutter: NoSuchMethodError: The getter 'statusCode' was called on null.
Receiver: null
Tried calling: statusCode
flutter: Bad state: Failed to load 313-medium.
