### ISSUE TITLE
[Fluxstore MV] Vendors wont showing in store list.

### ISSUE THREAD

**Issue by iamar1k92** [inspireui/support#3165]
Step 1 (require): detail issues and screenshots

Vendors doesnt show up;
Please fix this issue.  
[video.zip](https://github.com/inspireui/support/files/4616662/video.zip)

**Comment by vumanhsn97** [comment]
@iamar1k92 
Please help us to submit this form and fill all required info to continue with the support - http://private.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by iamar1k92** [comment]
I have submitted already, please check!!

**Comment by vumanhsn97** [comment]
@iamar1k92 
Replact this line in lib/vendor/store/store_model.dart: image = parsedJson["gravatar"] is String ? parsedJson["gravatar"] : null;
https://tppr.me/kU3SQ
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-05-14 at 14 39 18](https://user-images.githubusercontent.com/39208623/81906738-e5e68180-95f0-11ea-8790-e415bce893d3.png)

**Comment by iamar1k92** [comment]
How to get phone number for particular store in cart? Please share...

**Comment by vumanhsn97** [comment]
@iamar1k92 Can't get phone number in cart. Just see information about store in contact https://tppr.me/L9QBd

**Comment by iamar1k92** [comment]
i have customized the code and added whatsapp order button instead of add to cart.
![32cf6292-20d3-4e18-bdb7-d35e0629c4dd](https://user-images.githubusercontent.com/58983166/81920054-12e76400-95f2-11ea-82e1-fa5a8452eccd.jpeg)


Button is working well but i want to send to whatsapp of the vendor.

![whatsappbutitp](https://user-images.githubusercontent.com/58983166/81920178-44f8c600-95f2-11ea-938d-6587260be912.png)


I cant figure out how can i get the vendor phone number in the cart.

**Comment by iamar1k92** [comment]
i just cannot fetch phone number of vendor, from store class. It always givens called on null.

**Comment by iamar1k92** [comment]
is it possible?

**Comment by vumanhsn97** [comment]
@iamar1k92 
It is not possible. Because rest api not have data

**Comment by iamar1k92** [comment]
Well, ok.. We have the solution of first problem so we can close this ticket.
