### ISSUE TITLE
Suggestion to make corrections on your online instruction

### ISSUE THREAD

**Issue by gotomoon** [inspireui/support#3166]
Please review and revise your instruction on https://docs.inspireui.com/fluxstore/getting-started/ as my suggestion below.  I had to waste several hours because this instruction made me skip a page.  I attached the screenshot with my comments below.

By the way, your overall video instructions are very thorough and much better than the tutorial in flutter.dev.  That should save beginners from frustration and wasted time.  I appreciate that.

Chris

![image](https://user-images.githubusercontent.com/653432/81719473-51bcd300-94a7-11ea-801e-5439604b3d5d.png)

**Comment by minhcasi** [comment]
@gotomoon - appreciated for your help to point out the problem, we will fix it immediately 👍

**Comment by minhcasi** [comment]
Hi Chris, could I know which product that you have purchased so that we could update this page more clearer?

**Comment by gotomoon** [comment]
Hi Minh,
I bought Fluxstore Multi Vendor.
