### ISSUE TITLE
Receiver: null

### ISSUE THREAD

**Issue by adnanmur** [inspireui/support#3169]
Receiver: null
Tried calling: @[]( " menu_title " )@ withoute @

Any thought why this error pops up non stop on debug console?

**Comment by minhcasi** [comment]
@adnanmur - pls share your screenshot issue so that we could help to checking

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
