### ISSUE TITLE
[ListPro] How to add and set a language as default pt-br?

### ISSUE THREAD

**Issue by eduardovaladares** [inspireui/support#317]
**Mandatory Info (please complete the following information):**
 - Product: ListPro - Listing Directory React Native template
 - Your Purchased Code: 7328927a-cb39-411b-ab07-0bad8c0aba44
(we may not reply if you are not our customer)

**Describe the issues**
How to add and set a language as default pt-br?

**Screenshots**

**Additional context**
Add any other detail logs about the problem here.

**Comment by minhcasi** [comment]
@thangvo9x - please make the video to guide for this feature - thanks

**Comment by thangvo9x** [comment]
Hi. Please refer to this video guide. Thanks 
https://github.com/inspireui/support/issues/184#issuecomment-465037534
