### ISSUE TITLE
Getting Cors error in Dokan Pro Plugin

### ISSUE THREAD

**Issue by inspireuis** [inspireui/support#3170]
I have purchased the inspireui multivendor product. I am trying to setup the site in the multi vendor flutter app. I am getting CORS error while trying to hit the site url.
I tried to fix Dokan plugin issue but no success. Then after your suggestion I tried installing ListMap Manager API but while activating plugin I am getting below error

Fatal error: Cannot redeclare mstore_users_routes() (previously declared in /home/jobyas82/public_html/gurutos.com/wp-content/plugins/mstore-api/mstore-api.php:145) in /home/jobyas82/public_html/gurutos.com/wp-content/plugins/listapp-mobile-manager/listapp-manager.php on line 236

**Comment by minhcasi** [comment]
@inspireuis - I'm sorry for my previous wrong suggestion - i though you have purchased the Fluxlisting app, please help to remove the Listapp Manager plugin and only install the mstore-api one, and follow this guide to setup the multi vendor app - https://docs.inspireui.com/fluxstore/multi-vendor/

**Comment by inspireuis** [comment]
Good day @minhcasi , we are 2 developers trying to install both of the themes, 

**Fluxstore multivendor and Fluxstore Listing.**

I will create a different ticket for Fluxstore Listing, as this will be a mess with the two of us here, for **Fluxstore Miltivendor** its pending the next: 

I have purchased the inspireui multivendor product. I am trying to setup the site in the multi vendor flutter app. I am getting CORS error while trying to hit the site url.
I tried to fix Dokan plugin issue but no success. Then after your suggestion I tried installing ListMap Manager API but while activating plugin I am getting below error

Fatal error: Cannot redeclare mstore_users_routes() (previously declared in /home/jobyas82/public_html/gurutos.com/wp-content/plugins/mstore-api/mstore-api.php:145) in /home/jobyas82/public_html/gurutos.com/wp-content/plugins/listapp-mobile-manager/listapp-manager.php on line 236

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as it could not be verified, please create the new one when you got enough purchased info - thank you!
