### ISSUE TITLE
Store page not showing all the products

### ISSUE THREAD

**Issue by mauriciozuniga** [inspireui/support#3172]
Step 1 (require): detail issues and screenshots
I purchased Fluxstore Multi-vendor for WooCommerce, and I am using Dokan in WC for multivendor functionality.
I have a store (vendors) with several products, but in the application, when I open the store profile (for example, from "Stores" tabs), in "products" tab, it only show me 10 products, it doesn't show me the rest or let me navigate to the other pages.

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

<img width="882" alt="Captura de Pantalla 2020-05-12 a la(s) 23 58 39" src="https://user-images.githubusercontent.com/8905579/81772961-dcec9780-94ac-11ea-9fce-92868bd64be5.png">

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by mauriciozuniga** [comment]
Hi guys, excuse me, do you have any news regarding this?

thanks!

**Comment by vumanhsn97** [comment]
@mauriciozuniga 
- Replace services and vendor folder in lib to 
[services.zip](https://github.com/inspireui/support/files/4626759/services.zip)
[vendor.zip](https://github.com/inspireui/support/files/4626760/vendor.zip)

**Comment by mauriciozuniga** [comment]
Hi,

Now it's sending me the following errors while compiling...

`
Compiler message:
lib/vendor/store/widgets/store_item.dart:111:30: Error: The getter 'subtitle1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'subtitle1'.
                            .subtitle1
                             ^^^^^^^^^
lib/vendor/store_detail/widgets/contact.dart:108:59: Error: The getter 'subtitle1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'subtitle1'.
                style: Theme.of(context).primaryTextTheme.subtitle1.copyWith(
                                                          ^^^^^^^^^
lib/vendor/chat/messages.dart:152:40: Error: The getter 'headline6' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline6'.
                style: theme.textTheme.headline6.copyWith(
                                       ^^^^^^^^^
lib/vendor/chat/messages.dart:235:42: Error: The getter 'headline6' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline6'.
                  style: theme.textTheme.headline6.copyWith(
                                         ^^^^^^^^^
lib/services/helper/flash_helper.dart:56:66: Error: The getter 'subtitle1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'subtitle1'.
    return (theme.dialogTheme?.titleTextStyle ?? theme.textTheme.subtitle1)
                                                                 ^^^^^^^^^
lib/services/helper/flash_helper.dart:62:68: Error: The getter 'bodyText1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'bodyText1'.
    return (theme.dialogTheme?.contentTextStyle ?? theme.textTheme.bodyText1)
                                                                   ^^^^^^^^^
`

**Comment by mauriciozuniga** [comment]
Hi guys, any news regarding this?
Thnks a lot!

**Comment by kibbyboi** [comment]
I have the same issue

**Comment by vumanhsn97** [comment]
Can you zip lib folder and share it?

**Comment by mauriciozuniga** [comment]
Sure, here you go
[lib.zip](https://github.com/inspireui/support/files/4645403/lib.zip)

**Comment by minhcasi** [comment]
Guys, please share the source private via email - thank you!

@mauriciozuniga - please help us to create one ticket for your issue - thank you!

**Comment by mauriciozuniga** [comment]
This is MY issue, I created it... what do you mean create one ticket for my issue? create another one? Also, I just sent you the lib folder to support email

Thanks

> Guys, please share the source private via email - thank you!
> 
> @mauriciozuniga - please help us to create one ticket for your issue - thank you!

**Comment by minhcasi** [comment]
Yes, please create your all comment to one ticket, we will keep one ticket open until it is resolved  

moved to #3285
