### ISSUE TITLE
Flusxtore Listing - Build Failed.

### ISSUE THREAD

**Issue by inspireuis** [inspireui/support#3173]
Step 1 (require): detail issues and screenshots

Hello @minhcasi ,
im getting the next error and dont let me run the app theme, 

D8: Type com.google.firebase.iid.zzbb is referenced as an interface from `com.google.firebase.messaging.zzf`

![image](https://user-images.githubusercontent.com/65219388/81773945-145c4380-94af-11ea-85ca-d7c8ba785c20.png)

![image](https://user-images.githubusercontent.com/65219388/81773955-1a522480-94af-11ea-8466-dc238bd49e8c.png)
![image](https://user-images.githubusercontent.com/65219388/81773961-1f16d880-94af-11ea-995f-ab100254a331.png)

Also have the red notes, can you please let me know how to solve the error and the red notes?

at this moment i configure the theme till the part to connect to website, server config.

Thanks and Regadrs,
InspireuiS.

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@inspireuis 
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by inspireuis** [comment]
good day minhcasi, 

what else do you need? more info related to?

Thanks and regards,
InspireuiS

**Comment by minhcasi** [comment]
@inspireuis - pls submit your verify purchase to http://private.inspireui.com - as we could not verify your proof of purchase so far - thank you for your time!

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as it could not be verified, please create the new one when you got enough purchased info - thank you!
