### ISSUE TITLE
error while creating new wp customer account :  exception no route was found matching the URL and request method.

### ISSUE THREAD

**Issue by mmasifashraf** [inspireui/support#3174]
![image](https://user-images.githubusercontent.com/44862509/81808778-e1ef2c80-9528-11ea-9852-6cdae388a46a.png)

**Comment by minhcasi** [comment]
@mmasifashraf 

Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as it could not be verified, please create the new one when you got enough purchased info - thank you!

**Comment by mmasifashraf** [comment]
what else you have needed. I downloaded it from my evanto itself

**Comment by minhcasi** [comment]
@kvt0012 - pls help for checking

**Comment by kvt0012** [comment]
Please send me your whole file via my email : khiem@inspireui.com and post your email here, I will check it, thank you

**Comment by mmasifashraf** [comment]
the issue has been resolved.

i think it happened because of the mstore  api plugin was deactivate.
