### ISSUE TITLE
[FluxStore] [Woocommerce] MercadoPago integration

### ISSUE THREAD

**Issue by uade-pick-up** [inspireui/support#3175]
Hello everyone!

I´ve found this Flutter SDK on Github for an already requested payment gateway. I´ve seen there are lot of users interested in this payment as native solution.

[Mercado Pago Payment Gateway](https://github.com/hostelix/mercadopago_sdk_dart)

I´ve talked with the Git owner and he confirmed is fully working, could you take a look and try adding it as native payment gateway?

Thanks!

**Comment by minhcasi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add new Native Payment: MercadoPago](https://trello.com/c/MbtYUnav/42-add-new-native-payment-mercadopago)

**Comment by minhcasi** [comment]
moved to the backlog for further investigating

**Comment by midasmkt** [comment]
Hello Minh. 
Is this ready? Is there any news?

**Comment by uade-pick-up** [comment]
I think @minhcasi just put it on backlog... no further updates about this since May 15 or so... Hope to have this feature as soon as posible.

**Comment by midasmkt** [comment]
because it doesn't take the native payment so you know something?

**Comment by minhcasi** [comment]
sorry we did not start on this feature yet, due to the limit team capacity so that we could handle all the request
