### ISSUE TITLE
onboarding error 

### ISSUE THREAD

**Issue by surajk1986** [inspireui/support#3177]
Step 1 (require): detail issues and screenshots
after run app in emulator shows error

https://drive.google.com/open?id=11Ow-dxivsGxaLS53fSRSIfbpMyEt2p13 screen shot
Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@surajk1986 - pls help to share the `lib/common` and `lib/config` folder so that we could help for checking, we could not help with the folder from your sharing https://tppr.me/qpdEt

**Comment by minhcasi** [comment]
@surajk1986 - pls confirm if you could run the project so far :)
