### ISSUE TITLE
Where can I find consumer key and consumer secret on ListingPro theme?

### ISSUE THREAD

**Issue by gotomoon** [inspireui/support#3178]
Step 1 (require): detail issues and screenshots
I bought FluxStore Listing.  I am using ListingPro theme and I can't locate consumer key and consumer secret.  It doesn't use Woocommerce.  Your instruction doesn't show where I can get those values: https://docs.inspireui.com/fluxstore/listing-directory/.

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@gotomoon - sorry for the confusion, you could set these values empty on ListingPro - https://tppr.me/Hs1Lb
