### ISSUE TITLE
[ListApp] Thumbnail regenerating issue- missing plugins

### ISSUE THREAD

**Issue by jane207593** [inspireui/support#318]
we are facing issue with regenerating thumbnails on server we checked that there are missing some of auth files and there were missing some plugins please check the attached files i have uploaded and installed plugins but in the provided document there are more files please guide me about.
![image 1](https://user-images.githubusercontent.com/47419219/53006150-7ff36480-3456-11e9-9990-ae327893db31.png)
![image 2](https://user-images.githubusercontent.com/47419219/53006152-7ff36480-3456-11e9-8279-a1497e2cd520.png)
![image 3](https://user-images.githubusercontent.com/47419219/53006156-808bfb00-3456-11e9-8c2e-467c881aebc5.png)

**Comment by minhcasi** [comment]
Hi, could you share your Wordpress testing login account so that we could help to check the issue, thanks

**Comment by thangvo9x** [comment]
Hi. You can me your info to thang@inspireui.com for checking. with subject id is 318. Thanks
