### ISSUE TITLE
Fluxstore 1.7.3 - Opencart - Mobile app showing prices without Tax

### ISSUE THREAD

**Issue by harrisbaitalrayan** [inspireui/support#3180]
Step 1 (require): detail issues and screenshots

I have set tax class in opencart. The price in the e-commerce website is shown with tax added. The mobile app doesn't show the price with tax. As per regulation in my region, all prices to be displayed with tax. Is there a configuration to display price with tax ?

Tax is 5%.

![IMG_777AE74A0668-1](https://user-images.githubusercontent.com/13076524/81840246-c18b9600-9559-11ea-845f-cb05b0f5cb30.jpeg)

In website, display price is inclusive of 5% tax.
<img width="1190" alt="Screen Shot 2020-05-13 at 8 38 03 PM" src="https://user-images.githubusercontent.com/13076524/81840280-cfd9b200-9559-11ea-9f56-5de54637838a.png">

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by minhtruong315** [comment]
Hi @harrisbaitalrayan Thanks for your report. Fluxstore doesn't  support tax price now. We will note it backlog and update it on next release.

**Comment by harrisbaitalrayan** [comment]
@minhtruong315 , Thanks for the response. Is there a quick fix available to include tax price ? Because website and mobile app showing different prices is a major problem for us to make the app live. It will also attract fine from the government in UAE.  If it will be only available in next release, when would that be ? Because i want to reschedule my app release according to that.

**Comment by minhtruong315** [comment]
No. we need more time to research tax price. so we will add it in the future.
Thanks

**Comment by harrisbaitalrayan** [comment]
ok. Thank you.

**Comment by karthick-thomsun** [comment]
Dear Support, 

Is this fixed? Are there any other workaround if not fixed already?

Thank you for your support.. It is critical for our app.

**Comment by karthick-thomsun** [comment]
> @minhtruong315 , Thanks for the response. Is there a quick fix available to include tax price ? Because website and mobile app showing different prices is a major problem for us to make the app live. It will also attract fine from the government in UAE. If it will be only available in next release, when would that be ? Because i want to reschedule my app release according to that.

@harrisbaitalrayan: You able to solve the problem?
