### ISSUE TITLE
iOS problem with pod framework

### ISSUE THREAD

**Issue by xsamir** [inspireui/support#3183]
Step 1 (require): detail issues and screenshots
I faced an error when I try to run the app on the simulator as below:

![image](https://user-images.githubusercontent.com/7432001/81852379-99a13000-9563-11ea-8a14-08d841059e9b.png)

![image](https://user-images.githubusercontent.com/7432001/81852686-1502e180-9564-11ea-9589-518c5a1cf016.png)

I tried to do (pod install)
Also (sudo gem install cocoapods)
But all not working
I think there's a missing library (pods_runner.framework)!
Can you provide the installing link or attach it here?

Or does this problem have a solution?

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by xsamir** [comment]
I removed the framework line from the pod file
I faced another problem:
![image](https://user-images.githubusercontent.com/7432001/81855819-85136680-9568-11ea-8856-8389e2de69c3.png)

**Comment by minhcasi** [comment]
@xsamir did you try to run `flutter clean`

You are using MacOS but your share why there is the `C:\SDK\flutter` config on Window? Try to search and remove that setting on your project

**Comment by xsamir** [comment]
I relinked the flutter, but still facing a problem as below:
![image](https://user-images.githubusercontent.com/7432001/81960358-8486d880-9619-11ea-9b3f-e2c88a86bb62.png)


And there's a missing framework, I couldn't find it:
![image](https://user-images.githubusercontent.com/7432001/81960561-cf085500-9619-11ea-8e1b-fe5002071ae8.png)


Please give me a solutions, the time is running

**Comment by minhcasi** [comment]
@xsamir - pls try some solution on this link https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

**Comment by xsamir** [comment]
I followed the steps, but I faced those errors:

Error with (pod install):
![image](https://user-images.githubusercontent.com/7432001/82072986-389f6680-96e1-11ea-86ed-f70d9f6e35d8.png)


Error when I launch the app:
![image](https://user-images.githubusercontent.com/7432001/82073055-566ccb80-96e1-11ea-92bd-d6973c7967bd.png)

**Comment by minhcasi** [comment]
@xsamir - pls try to update the pubspec.yaml and change the version code `rate_my_app` to fix the issue 

```
  rate_my_app: 0.6.1
```

Let us know your checking, thank you!

**Comment by xsamir** [comment]
The steps I do:
Changed the rate_my_app version in Pubspec.yaml and Pubspec.lock

Then delete those files:
podfile - podfile.lock - pods folder - build folder

Then run those command inside the project directory:
pod init
add this lines to podfile:
pod 'GoogleMaps'
pod 'Firebase'
pod 'FirebaseAuth'

add this line to AppDelegate.swift
import FirebaseAuth

add this line to lib/models/user/user_model.dart
import 'package:app_settings/app_settings.dart';

then run this command
pod install

Then from Xcode > Product > Clean build folder

The run the app

All errors gone, but there's a new error as below:

![image](https://user-images.githubusercontent.com/7432001/82120094-58d82f80-978c-11ea-8422-1db9a32da829.png)

**Comment by xsamir** [comment]
After multiple tries, this is the last error:

![image](https://user-images.githubusercontent.com/7432001/82129895-0ec46d80-97cf-11ea-8ebe-3ce061facbe1.png)

**Comment by minhcasi** [comment]
@xsamir could you try to update this code
```
Padding(
                padding:
                    const EdgeInsets.symmetric(vertical: 8.0, horizontal: 30),
                child: PinCodeTextField(
                  length: 6,
                  obsecureText: false,
                  autoFocus: true,
                  animationType: AnimationType.fade,
                  animationDuration: Duration(milliseconds: 300),
                  onChanged: (value) {
                    if (value != null && value.length == 6) {
                      _loginSMS(value, context);
                    }
                  },
                )),
```
File verify.dart - https://tppr.me/2Mfdl

**Comment by xsamir** [comment]
Still facing a problem!

![image](https://user-images.githubusercontent.com/7432001/82239800-0b052800-9942-11ea-9bc2-f79921834853.png)


![image](https://user-images.githubusercontent.com/7432001/82239739-f0cb4a00-9941-11ea-8ea8-1f0eda5fdd56.png)

**Comment by xsamir** [comment]
With Flutter run:

![image](https://user-images.githubusercontent.com/7432001/82263252-29cbe480-996b-11ea-9669-447ba2f5d9a2.png)

**Comment by xsamir** [comment]
**I found a solution.**

The problem was with ios/Flutter directory files, it was missing and some corrupted files.

What did I do is creating another Flutter project with same project and Bundl name, then I copied the Flutter folder from the new project to my current one.

That fixed everything for me.

**Comment by minhcasi** [comment]
@xsamir - appreciated for your sharing, i will update this to the common issue document

@Haniel5
