### ISSUE TITLE
[FluxStore Pro]How to change Side Menu Sub Categories Text Color

### ISSUE THREAD

**Issue by bikostudio** [inspireui/support#3184]
Hi @minhcasi 

I want to change the font color of the sub categories please.

![2020-05-11_150018](https://user-images.githubusercontent.com/62074493/81868319-6e720d00-9572-11ea-8628-e766df1935fb.jpg)

Thank you

**Comment by minhcasi** [comment]
@bikostudio - try this file

<img width="1047" alt="Screen Shot 2020-05-14 at 10 55 54" src="https://user-images.githubusercontent.com/1459805/81890989-7ca34600-95d1-11ea-83d0-35196c7c619b.png">

**Comment by bikostudio** [comment]
> 
> 
> @bikostudio - try this file
> 
> <img alt="Screen Shot 2020-05-14 at 10 55 54" width="1047" src="https://user-images.githubusercontent.com/1459805/81890989-7ca34600-95d1-11ea-83d0-35196c7c619b.png">

@minhcasi  I already did this, This only changes the Main Categories font color. I need to change the Sub categories font color.
