### ISSUE TITLE
How make animate SplashScreen 

### ISSUE THREAD

**Issue by harjono-flux** [inspireui/support#3185]
Dear Support,

My splash screen not animate, can you help me?

This is my screen record
https://drive.google.com/file/d/16k9avvwnH1MdvISZEekYM76K_Zb1muDN/view?usp=sharing

And my app.dart
[Archive.zip](https://github.com/inspireui/support/files/4625284/Archive.zip)

**Comment by minhcasi** [comment]
@harjono-flux - we could not access to your file sharing

Pls try to check if the startAnimaiton from the app is the same on your Flare Dashboard

<img width="919" alt="Screen Shot 2020-05-14 at 10 51 02" src="https://user-images.githubusercontent.com/1459805/81890705-cfc8c900-95d0-11ea-88a4-a390b6839949.png">

<img width="839" alt="Screen Shot 2020-05-14 at 10 53 02" src="https://user-images.githubusercontent.com/1459805/81890871-32ba6000-95d1-11ea-8e64-394f1dbbf5a0.png">

**Comment by rabahaldoori** [comment]
@minhcasi i have question when i use this design is slow 
<img width="368" alt="Screen Shot 2020-05-14 at 12 21 25 AM" src="https://user-images.githubusercontent.com/31085177/81895870-dd526480-9578-11ea-9cf5-fa0b9f3ccb3b.png">

when i used different one is more faster

**Comment by harjono-flux** [comment]
yeah... cool. its works. thx
