### ISSUE TITLE
bottom bar Shopify 

### ISSUE THREAD

**Issue by rabahaldoori** [inspireui/support#3186]
i already submit my Purchase Code , 

the bottom bar for the Menu Like to Home , Category when i do the Customize make it bigger and not organize i already attached  pictures so you can see.

thank you 

<img width="1276" alt="Screen Shot 2020-05-13 at 10 00 38 PM" src="https://user-images.githubusercontent.com/31085177/81887988-0289a780-9566-11ea-8c38-8d99d8251eb3.png">

![IMG_8047](https://user-images.githubusercontent.com/31085177/81887972-f7cf1280-9565-11ea-93cc-bb36acf05fd1.PNG)

**Comment by minhcasi** [comment]
@rabahaldoori - please try to open the config json and remove Label to fix the problem, it will look like this screenshot

<img width="1032" alt="Screen Shot 2020-05-14 at 10 58 28" src="https://user-images.githubusercontent.com/1459805/81891121-d9066580-95d1-11ea-939d-1697961018e2.png">

**Comment by rabahaldoori** [comment]
i don't have the "top bar" in config_en.json 
<img width="1170" alt="Screen Shot 2020-05-13 at 11 37 59 PM" src="https://user-images.githubusercontent.com/31085177/81893254-d9bbdf00-9572-11ea-8ab4-a3509bf1cbae.png">

thank you

**Comment by rabahaldoori** [comment]
its fix thank you @minhcasi

**Comment by minhcasi** [comment]
Great, thank you for quickly confirm 

Could you mind to help us give rating feedback to https://codecanyon.net/downloads - thank you so much for your help 👍

**Comment by rabahaldoori** [comment]
@minhcasi when  i use this design is slow and when i use other one is faster !! 
<img width="368" alt="Screen Shot 2020-05-14 at 12 21 25 AM" src="https://user-images.githubusercontent.com/31085177/81895968-1f7ba600-9579-11ea-9978-563d3984e48d.png">

**Comment by minhcasi** [comment]
@rabahaldoori - are you testing on the same demo app or connect to your own shopify site?
