### ISSUE TITLE
Shopify 

### ISSUE THREAD

**Issue by rabahaldoori** [inspireui/support#3187]
slow and after that crash 

<img width="818" alt="Screen Shot 2020-05-14 at 12 50 35 AM" src="https://user-images.githubusercontent.com/31085177/81897848-0e349880-957d-11ea-992f-8149f040537f.png">

and this video how is crash 

https://youtu.be/nB5FhdShnVc

* Second problems 

Notifications show inside the app but not showing when i'm out side the app but save in "notify massage 

<img width="1216" alt="Screen Shot 2020-05-14 at 11 41 41 PM" src="https://user-images.githubusercontent.com/31085177/82047398-5f758280-9678-11ea-8b3d-8fa2bd48957a.png">

** third problem

how i can change the Category image ? could you help me , and also
<img width="345" alt="Screen Shot 2020-05-14 at 10 23 56 PM" src="https://user-images.githubusercontent.com/31085177/82047476-816f0500-9678-11ea-9fbd-7dec0ff100ac.png">

thank you

**Comment by minhcasi** [comment]
related verified ticket #3142

**Comment by minhcasi** [comment]
@rabahaldoori - could you share your common & config folder so that we could help to check the issue on your site?

**Comment by rabahaldoori** [comment]
i uses my on Store and i already attached the common & config 
[Archive.zip](https://github.com/inspireui/support/files/4631426/Archive.zip)


thank you

**Comment by rabahaldoori** [comment]
@minhcasi any feedback ? 

thank you

**Comment by luyx2412** [comment]
Hi @rabahaldoori Sorry about reply you late. We are checking about the issue. Can you give me the specific version? Because i checked and everything worked normal.

Thanks

**Comment by rabahaldoori** [comment]
@luyx2412 fluxstore-shopify 1.7.2,  and is not crash on the simulator is crash when you upload in flight test or you use your phone
thank you

**Comment by rabahaldoori** [comment]
@luyx2412 if you need the link to the flight test i have public link if that help i will send to you

**Comment by rabahaldoori** [comment]
@luyx2412 @minhcasi any update?

**Comment by luyx2412** [comment]
Hi @rabahaldoori Sorry about reply you late. Can you invite me to your testflight via luyxtran264@gmail.com.

Thanks

**Comment by rabahaldoori** [comment]
@luyx2412 

https://testflight.apple.com/join/f0XmplM4

**Comment by rabahaldoori** [comment]
@minhcasi did you get it it’s public link 
Thank you

**Comment by luyx2412** [comment]
Hi @rabahaldoori Sorry about reply you late. Can you give me the specific screen? Because i tested your app. And everything worked normal.

Thanks

**Comment by rabahaldoori** [comment]
@minhcasi sir i gave everything sent you flight test and you can check its crash and i sent you the API and the link for my store ! And no response!!! You can see the video in the top !! I proved you everything and you said everything work !!

**Comment by rabahaldoori** [comment]
https://youtu.be/nB5FhdShnVc

@minhcasi you can check this one too again and see the flight test I don’t thing so you check it

**Comment by rabahaldoori** [comment]
@luyx2412 could you help and check

**Comment by luyx2412** [comment]
Hi @rabahaldoori Thanks for your video, i see the crash let me investigate it.

Thanks

**Comment by rabahaldoori** [comment]
@luyx2412 thank you please i you could and this is my test flight its public link you can check its crash too 

https://testflight.apple.com/join/f0XmplM4

**Comment by luyx2412** [comment]
Hi @rabahaldoori Yep i am testing your app via testflight. Let me investigate it and reply you soon. Thanks and sorry about late.

**Comment by rabahaldoori** [comment]
@luyx2412 hi , any result

**Comment by luyx2412** [comment]
Hi @rabahaldoori In `lib/screens/products/products.dart` please replace this file to fix the issue.
[products.dart.zip](https://github.com/inspireui/support/files/4662640/products.dart.zip)

P/S: we will update next version to fix the issues.

Thanks

**Comment by rabahaldoori** [comment]
@luyx2412 thank you i will try and gave you feed back

**Comment by rabahaldoori** [comment]
@luyx2412 how about the Notifications show inside the app but not showing when i'm out side the app but save in "notify massage
<img width="1216" alt="72D82730-62CE-470A-A2B5-31677D8ADE4A" src="https://user-images.githubusercontent.com/31085177/82574531-e630d080-9b4c-11ea-9c83-ddd28d47111d.png">


And how i can change the Category image ? could you help me , and also

<img width="345" alt="309C3A8F-5F62-4794-AE91-7A0738BBA234" src="https://user-images.githubusercontent.com/31085177/82574605-fa74cd80-9b4c-11ea-9426-2bfc4868f9c4.png">

Thank you

**Comment by rabahaldoori** [comment]
when i replace products.dart i got errors 

<img width="1399" alt="Screen Shot 2020-05-21 at 6 28 57 PM" src="https://user-images.githubusercontent.com/31085177/82615857-17cb8b00-9b91-11ea-90f4-fdb51e8d82b6.png">

**Comment by rabahaldoori** [comment]
@luyx2412 hi did you check this image i got this error after replace the file cannot build the app 
<img width="1399" alt="3BE47E17-9652-4720-BDC6-EE3606C9EF74" src="https://user-images.githubusercontent.com/31085177/82653408-c816af00-9be4-11ea-8af7-09369e78e37f.png">

**Comment by rabahaldoori** [comment]
@luyx2412 any update?

**Comment by luyx2412** [comment]
Hi @rabahaldoori Sorry about sent you next version file, this is right file. 
[products.dart.zip](https://github.com/inspireui/support/files/4671110/products.dart.zip)

Thanks

**Comment by rabahaldoori** [comment]
@luyx2412 same issue 
<img width="1241" alt="Screen Shot 2020-05-22 at 11 11 30 PM" src="https://user-images.githubusercontent.com/31085177/82721303-aa4b5780-9c81-11ea-87f4-f185a7f7f583.png">

**Comment by rabahaldoori** [comment]
@luyx2412 I thank you send same file again !! 

could you check because i mach it , its same file

**Comment by luyx2412** [comment]
Hi @rabahaldoori Sorry my mistake. This is right file :(
[products.dart.zip](https://github.com/inspireui/support/files/4671126/products.dart.zip)

Thanks

**Comment by rabahaldoori** [comment]
@luyx2412 i got different error right now "Could not build Objective-C module 'Firebase"
<img width="1213" alt="Screen Shot 2020-05-22 at 11 54 34 PM" src="https://user-images.githubusercontent.com/31085177/82721933-b0dccd80-9c87-11ea-9eb0-8580ce54d66a.png">

**Comment by luyx2412** [comment]
Hi @rabahaldoori Please send your project via inspireui.team@gmail. i can investigate about your issues easier.

Thanks

**Comment by rabahaldoori** [comment]
@luyx2412 you need all the project ?

**Comment by rabahaldoori** [comment]
@luyx2412 I already sent to you Thank you

**Comment by rabahaldoori** [comment]
@luyx2412 never maid i fixed it , i will keep you update about , and how i can remove  this bar 
<img width="320" alt="Screen Shot 2020-05-23 at 2 30 16 AM" src="https://user-images.githubusercontent.com/31085177/82724694-6f571d00-9c9d-11ea-92b8-801e725785a0.png">

**Comment by rabahaldoori** [comment]
@luyx2412 its same things crash and slow when use real phone or upload to TestFlight 
watch the Video 

https://www.youtube.com/watch?v=6OyuH0fITuU

and i already sent you invention for Flight Test to you Email 


Thank you

**Comment by rabahaldoori** [comment]
@luyx2412 any update ?

**Comment by luyx2412** [comment]
Hi @rabahaldoori Sorry about reply you late, i just come back my hometown. Can you send me your project via inspireui.team@gmail.com. I can investigate easier and give you the solution about that.

Thanks

**Comment by rabahaldoori** [comment]
hi @luyx2412 i already sent ti you could check it

thank you

**Comment by rabahaldoori** [comment]
@luyx2412 and did you see the memory is take around 19 GB to much that way crash i thank has one code load all that or some loop

**Comment by luyx2412** [comment]
Hi @rabahaldoori thanks for your effort, and i received your email. Let me investigate about it. 

Thanks

**Comment by rabahaldoori** [comment]
hi @luyx2412 any update ?

**Comment by luyx2412** [comment]
Hi @rabahaldoori Please replace this file with `lib/services/hepers/shopify_query.dart` 
[shopify_query.dart.zip](https://github.com/inspireui/support/files/4680083/shopify_query.dart.zip) to fix the issues. Because the app load original image size which will increase the memory. 

Thanks

**Comment by rabahaldoori** [comment]
hi @luyx2412 its letter bit better but still slow and crash 

https://www.youtube.com/watch?v=k8tJdwldagE

Thank you

**Comment by luyx2412** [comment]
Hi @rabahaldoori We are improving and investigating about this issue. Thanks for your information. 

Thanks

**Comment by luyx2412** [comment]
HI @rabahaldoori I just sent you the latest project which fix some related issues. Please check your email.

Thanks

**Comment by rabahaldoori** [comment]
Hi @luyx2412 ok  i will check and gave you feedback thank you

**Comment by rabahaldoori** [comment]
hi @luyx2412 not working building issue 
i upload for you the logs you can see

<img width="1151" alt="Screen Shot 2020-05-28 at 5 57 09 PM" src="https://user-images.githubusercontent.com/31085177/83202179-ab123c80-a10c-11ea-8f4c-20831b8307b2.png">





[Error logs.zip](https://github.com/inspireui/support/files/4698707/Error.logs.zip)

**Comment by rabahaldoori** [comment]
Hi @luyx2412 is not Crash but still slow 
<img width="1359" alt="Screen Shot 2020-05-28 at 7 24 35 PM" src="https://user-images.githubusercontent.com/31085177/83207548-13671b00-a119-11ea-9cd8-97f039342e33.png">

**Comment by luyx2412** [comment]
HI @rabahaldoori I saw your products load in home screen, please reduce the products which will impact performance or you can edit image size in `shopify_query.dart`. We are improving load image and release in next version.

Thanks

**Comment by rabahaldoori** [comment]
@luyx2412 yes when i reduce from the home screen its better but i when i edit change image size can't build and i notes when i go to the catagory not show all the products on the catagory ,

<img width="1143" alt="Screen Shot 2020-05-30 at 9 39 58 AM" src="https://user-images.githubusercontent.com/31085177/83331238-701e1f00-a25a-11ea-9c40-6f30423a142e.png">


Thank you

**Comment by rabahaldoori** [comment]
Hi @luyx2412 yes its better , i edit image size its better but i have issue category not showing all the image

**Comment by luyx2412** [comment]
Hi @rabahaldoori Sorry i don't understand what you meant.

**Comment by rabahaldoori** [comment]
hi @luyx2412 when i go to the products category its showing just 50 products i can't see more in that

**Comment by luyx2412** [comment]
HI @rabahaldoori So you meant the products category could not load more? i am investigating about this issues.

Thanks

**Comment by rabahaldoori** [comment]
Hi @luyx2412 yes its load just 50 products and stop

**Comment by rabahaldoori** [comment]
@luyx2412 any update

**Comment by luyx2412** [comment]
Hi @rabahaldoori Currently we added 50 products in `lib/services/shopify.dart` line 248. Please change the pageSize depend on you.

Thanks

**Comment by rabahaldoori** [comment]
@luyx2412 i can did more 180 if i put more in that will not show any products

**Comment by rabahaldoori** [comment]
@luyx2412 any update ?

**Comment by luyx2412** [comment]
Hi @rabahaldoori I just invited you to repo which fixed the issues. And improve some features.

Thanks for your times.

**Comment by rabahaldoori** [comment]
i can't see anything 

<img width="1058" alt="Screen Shot 2020-06-07 at 2 53 34 PM" src="https://user-images.githubusercontent.com/31085177/83978669-b284d300-a8ce-11ea-827f-cf648c946493.png">
<img width="1057" alt="Screen Shot 2020-06-07 at 2 53 26 PM" src="https://user-images.githubusercontent.com/31085177/83978672-b44e9680-a8ce-11ea-98f2-a12fa2057ac3.png">

**Comment by luyx2412** [comment]
Hi @rabahaldoori Sorry about it, i just change your role. Please check again.

**Comment by rabahaldoori** [comment]
hi @luyx2412 i did download it so far show all the category products . but images quality it's bad and i tried to change it from" shopify_query.dart" didn't work 

thank you

**Comment by rabahaldoori** [comment]
hi @luyx2412 any update?  the new version is not Compatible with " FluxBuilder " and products image still bad ! 

Thank you

**Comment by luyx2412** [comment]
Hi @rabahaldoori We are checking the issues, and will update soon. And the photo, can you give me the shopify_query.dart file? let me check about it.

Thanks

**Comment by rabahaldoori** [comment]
hi @luyx2412 this is 
[shopify_query.dart.zip](https://github.com/inspireui/support/files/4795599/shopify_query.dart.zip)

**Comment by luyx2412** [comment]
Hi @rabahaldoori please pull latest code in gitlab repo. https://github.com/inspireui/support/issues/3187#issuecomment-640681020 And please uninstall the app and reinstall again with your changed in photo size. 

Thanks

**Comment by rabahaldoori** [comment]
hi @luyx2412 i don't have any more access because you put the access for 4 dyes only .

**Comment by luyx2412** [comment]
HI @rabahaldoori I just invited you again. Thanks

**Comment by luyx2412** [comment]
Closed! Feel free to create new issue. Thanks
