### ISSUE TITLE
product list not showing

### ISSUE THREAD

**Issue by meeraforefront** [inspireui/support#3188]
I purchased Fluxstore Multi-vendor for WooCommerce, and I am using Dokan in WC for multivendor functionality.
but product list is not showing items

**Comment by minhcasi** [comment]
@meeraforefront 
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as it could not be verified, please create the new one when you got enough purchased info - thank you!
