### ISSUE TITLE
Default woocommerce payments methods  in a webview

### ISSUE THREAD

**Issue by Shiru-kun** [inspireui/support#3189]
Step 1 (require): detail issues and screenshots

Hello, all payments methods that i have in my website the app it redirects to a webview....

1. here i selected eg. bank transfer  then  place my order 
![index](https://user-images.githubusercontent.com/54008441/81911783-09e49b80-95ce-11ea-81dd-9d8720705d05.jpeg)

2. it goes to my website 
![index](https://user-images.githubusercontent.com/54008441/81912026-54661800-95ce-11ea-83e9-3dffbfa85450.jpeg)

2.1 It Confirms my order 
![index](https://user-images.githubusercontent.com/54008441/81912128-78c1f480-95ce-11ea-8440-28aacb7d1c10.jpeg)

3. at last show  this app confirm screen 
![index](https://user-images.githubusercontent.com/54008441/81912258-a0b15800-95ce-11ea-80dd-56cce5d5cd4c.jpeg)

i dont want it to go on a webview, there is a way i can avoid this? 
if its necessary to code, i will.  
I got a little basics of flutter i can go code..
 

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@Shiru-kun - you could refer to the payment via Paypal that support to process as native without processing to WooCommerce website - you could apply the similar method to your own payment gateway

**Comment by Shiru-kun** [comment]
How can i do that?

**Comment by Shiru-kun** [comment]
@minhcasi can u show me the steps for  thar?

**Comment by Shiru-kun** [comment]
@keizershaquil

**Comment by byroncanga** [comment]
I have the same problem, I don't know how to solve it

**Comment by minhcasi** [comment]
@Shiru-kun - i have also shared the same question on this ticket #3192

Some file and screenshot you could refer:
<img width="1083" alt="Screen Shot 2020-05-16 at 15 08 06" src="https://user-images.githubusercontent.com/1459805/82114451-0d6f5280-9787-11ea-9d02-9c9517dc9b75.png">

<img width="1099" alt="Screen Shot 2020-05-16 at 15 08 42" src="https://user-images.githubusercontent.com/1459805/82114479-22e47c80-9787-11ea-9ea3-8076f4b0677f.png">

**Comment by Shiru-kun** [comment]
@janiodrey

**Comment by minhcasi** [comment]
Let us know if you have any question, thanks

**Comment by Shiru-kun** [comment]
i created my own const , in lib/commom/config/payments with the name bankTransfer

**Comment by Shiru-kun** [comment]
i want the bank transfer method... but im kind lost how i can get this Id, the token and... 
im trying to follow the services.dart... 
![image](https://user-images.githubusercontent.com/54008441/82219731-f878f780-991d-11ea-999c-8364e3fb98d4.png)

**Comment by Shiru-kun** [comment]
![image](https://user-images.githubusercontent.com/54008441/82220056-70dfb880-991e-11ea-83f8-427236e370e4.png)

**Comment by Shiru-kun** [comment]
i ran  this on postman to find the ID of the method i want to make it native: and its ID is bacs an  woocommerce defaul payment method.... 

https://mywebsite.com//wp-json/wc/v2/payment_gateways?consumer_key=&consumer_secret=

**Comment by Shiru-kun** [comment]
i already create my payment method on widget/payment named bank_transfer,  and  added my payment method to payment.dart, but im still have doubts about the endpoints for the services... 

![image](https://user-images.githubusercontent.com/54008441/82237288-b0fe6580-9935-11ea-8e04-1737bb74cfc7.png)

**Comment by Shiru-kun** [comment]
@minhcasi some help? please

**Comment by Shiru-kun** [comment]
i did this first 


then 
![Uploading image.png…]()

**Comment by Shiru-kun** [comment]
i already added this files 
![image](https://user-images.githubusercontent.com/54008441/82240617-00936000-993b-11ea-816c-e2a916d39308.png)

**Comment by minhcasi** [comment]
Hi, could you able to run this payment success via Postman? Please also share your source to support@inspireui.com - we need time to investigate

Please note this checking is not in our support scope, we will try our best

**Comment by Shiru-kun** [comment]
Hi, could you able to run this payment success via Postman?
i didnt try... i'll send this now ....

**Comment by Shiru-kun** [comment]
already sent

**Comment by minhcasi** [comment]
"could you able to run this payment success via Postman?" - please try to test your payment first, to make it's working fine before integrating with the app as native feature - thank you!

**Comment by Shiru-kun** [comment]
@minhcasi  can u help me with the endpoints? 
used in services.dart for my payment, and the whole body of json used to place a order

**Comment by Shiru-kun** [comment]
i  couldnt  run this payment success via Postman cause im missing the endpoints to make the http requests...

**Comment by Shiru-kun** [comment]
@minhcasi there is i can just  hide the webview or change it with an animation? if possible how can i do that?

**Comment by minhcasi** [comment]
@Shiru-kun sorry, i'm still confused on your question? What do you mean hide the Webview or change animation?

**Comment by Shiru-kun** [comment]
i mean, i dont want to see that screen(the webview)

**Comment by Shiru-kun** [comment]
i dont want to see this.... 

https://user-images.githubusercontent.com/54008441/81912128-78c1f480-95ce-11ea-8440-28aacb7d1c10.jpeg

**Comment by minhcasi** [comment]
@Shiru-kun - i could not read the language from the screenshot. 

Could I know it is the screens after process purchased or before? As there is the code to post back the successful screen after purchase, it could be a bug on your integration - thank you!

**Comment by Shiru-kun** [comment]
when i click place order in the payment tab it shows this screens then  it returns to this page.... saying purchase complete. 
https://user-images.githubusercontent.com/54008441/81912258-a0b15800-95ce-11ea-80dd-56cce5d5cd4c.jpeg

**Comment by Shiru-kun** [comment]
@minhcasi  i think we are misunderstanding each other.. lets start it all... 
the main question here is that i see the  **webview when i place a order in any payment method**. that is the default from woocommerce like bank transfer.

**Comment by minhcasi** [comment]
@Shiru-kun - thank you, I've got your file, also forwarded to my team for checking and will get back to you soon - very best!

**Comment by Shiru-kun** [comment]
ok thanks

**Comment by Shiru-kun** [comment]
any new?

**Comment by minhcasi** [comment]
@Shiru-kun - your customize source code (`bank_transfer`) does not work well on this case, our team is checking and will keep update for this payment option - thanks

**Comment by minhtruong315** [comment]
Hi @Shiru-kun I replied you on the email. please check

**Comment by Shiru-kun** [comment]
@minhtruong315  hi, i checked my email thank you.

**Comment by Shiru-kun** [comment]
sorry but you can help me with  the "rest api document for my implementation of  "bank transfer"?

**Comment by Shiru-kun** [comment]
about this **checkoutUrl** i was thinking about using  the wordpress woocommerce endpoints... but i dont see  any to make payments.

**Comment by minhtruong315** [comment]
Hi @Shiru-kun for example, if you want to add paypal payment to flutter app. you need to follow their document to know how to call the api to make the payment.
https://developer.paypal.com/docs/integration/direct/payments/paypal-payments/#

**Comment by Shiru-kun** [comment]
ok, i got it. but im using a default woocommerce payment method

**Comment by Shiru-kun** [comment]
sadly i dont know the endpoint for it

**Comment by minhtruong315** [comment]
So you can try to use OnePageCheckout to support bank transfer payment

**Comment by minhcasi** [comment]
We wanted to thank you for your patience during this busy time. We currently have reduced staff and a significantly higher volume of inquiries. 

I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
