### ISSUE TITLE
Fluxstore shopify no homepage

### ISSUE THREAD

**Issue by jberman280** [inspireui/support#3190]
Here is my issues.
1st: homepage is not working only blue page with text: Unsupported operation: Infinity or NaN toInt.

2nd issue:
Compiler message:
../../flutter/flutter/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0.6.0+2/lib/src/dialogs.dart:272:17: Error: No named parameter with the name 'onRatingChanged'.
                onRatingChanged: (rating) {
                ^^^^^^^^^^^^^^^
../../flutter/flutter/.pub-cache/hosted/pub.dartlang.org/smooth_star_rating-1.1.0/lib/smooth_star_rating.dart:23:3: Context: Found this candidate, but the arguments don't match.
  SmoothStarRating({
  ^^^^^^^^^^^^^^^^

Compiler message:
../../flutter/flutter/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0.6.0+2/lib/src/dialogs.dart:272:17: Error: No named parameter with the name 'onRatingChanged'.
                onRatingChanged: (rating) {
                ^^^^^^^^^^^^^^^
../../flutter/flutter/.pub-cache/hosted/pub.dartlang.org/smooth_star_rating-1.1.0/lib/smooth_star_rating.dart:23:3: Context: Found this candidate, but the arguments don't match.
  SmoothStarRating({
  ^^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\user\Downloads\nyrod1\flutter\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 882

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\Users\user\Downloads\nyrod1\flutter\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 28s
Exception: Gradle task assembleDebug failed with exit code 1

Step 1 (require): detail issues and screenshots
I dont have one because i uninstalled the app/

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by jberman280** [comment]
I also forgot to add another issue: Failed assertion: boolean expression must not be null exception

**Comment by minhcasi** [comment]
@jberman280 - could you try to run `flutter doctor` and send us the result?

**Comment by jberman280** [comment]
it shows: No issues found.

**Comment by jberman280** [comment]
extended_image_slide_page_route.dart:333:9: Error: No named parameter with the name 'animation'.
        animation: animation,

**Comment by jberman280** [comment]
I fixed, image issue.
Homepage shows: Error in failed assertion: boolean expression must not be null

**Comment by jberman280** [comment]
════════ Exception caught by animation library ═════════════════════════════════════════════════════
'package:flutter/src/widgets/heroes.dart': Failed assertion: line 539 pos 14: 'overlayEntry != null': is not true.
════════════════════════════════════════════════════════════════════════════════════════════════════
I/Surface (29969): opservice is null false
I/flutter (29969): screenName null
I/flutter (29969): didPush detail
I/flutter (29969): product.type null
I/flutter (29969): ::::getProductVariations shopify product variants [Instance of 'ProductVariation', Instance of 'ProductVariation', Instance of 'ProductVariation', Instance of 'ProductVariation', Instance of 'ProductVariation', Instance of 'ProductVariation', Instance of 'ProductVariation', Instance of 'ProductVariation', Instance of 'ProductVariation', Instance of 'ProductVariation', Instance of 'ProductVariation', Instance of 'ProductVariation']
I/flutter (29969): ::::request fetchProductsByCategory Z2lkOi8vc2hvcGlmeS9Db2xsZWN0aW9uLzE2MTUwODIyOTE3NQ==

════════ Exception caught by scheduler library ═════════════════════════════════════════════════════
The following NoSuchMethodError was thrown during a scheduler callback:
The method '-' was called on null.
Receiver: null
Tried calling: -(454.7368421052632)

When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      RenderSliverMultiBoxAdaptor.childMainAxisPosition (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:573:37)
#2      RenderSliverHelpers.applyPaintTransformForBoxChild (package:flutter/src/rendering/sliver.dart:1695:20)
#3      RenderSliverMultiBoxAdaptor.applyPaintTransform (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:586:5)
#4      RenderObject.getTransformTo (package:flutter/src/rendering/object.dart:2345:24)
...

**Comment by jberman280** [comment]
Any Help?

**Comment by luyx2412** [comment]
Hi @jberman280 Sorry about reply you late. I just tested your config and everything worked normal. So can you clean `flutter clean` after that uninstall and reinstall app.

![Simulator Screen Shot - iPhone 11 - 2020-05-17 at 16 33 35](https://user-images.githubusercontent.com/8909619/82140883-40cfe100-985c-11ea-8058-b2e2a17995af.png)

P/S: Btw, your app is very beautiful :D 

Thanks

**Comment by jberman280** [comment]
its still showing me:
Compiler message:
../../flutter/flutter/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0.6.0+2/lib/src/dialogs.dart:272:17: Error: No named parameter with the name 'onRatingChanged'.
                onRatingChanged: (rating) {
                ^^^^^^^^^^^^^^^
../../flutter/flutter/.pub-cache/hosted/pub.dartlang.org/smooth_star_rating-1.1.0+1/lib/smooth_star_rating.dart:23:3: Context: Found this candidate, but the arguments don't match.
  SmoothStarRating({
  ^^^^^^^^^^^^^^^^

**Comment by jberman280** [comment]
The solutions was to change  rate_my_app: 0.6.0+2 to  rate_my_app: 0.6.0+3
But right now i still have the homepage issue, nothing seems to be working.

**Comment by luyx2412** [comment]
Hi @jberman280 Please remove pub-cache based on the comment https://github.com/flutter/flutter/issues/24733#issuecomment-441599240

Thanks

**Comment by jberman280** [comment]
Where can i find the file to edit sidebar menu. i want to remove blog>

**Comment by luyx2412** [comment]
Hi @jberman280 In `common/config/general.dart` line 93. Please change `show: false` or remove this field to hide the blog.

Thanks

**Comment by jberman280** [comment]
Thanks, and section to change htheme to dark. i want to remove it as well.

**Comment by jberman280** [comment]
Can i know where to edit privacy link?

**Comment by jberman280** [comment]
I tried all that you said, but still noy working.

**Comment by luyx2412** [comment]
Hi @jberman280 Can you give me the specific version. Because i loaded your config and everything worked great.

Thanks

**Comment by jberman280** [comment]
What version?

**Comment by jberman280** [comment]
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building HomeLayout-[<'en'>](dirty, state: _HomeLayoutState#4ae9e):
Failed assertion: boolean expression must not be null

The relevant error-causing widget was: 
  HomeLayout-[<'en'>] file:///C:/Users/user/Downloads/nyrod1/nyrod2/source/lib/screens/home/home.dart:119:13
When the exception was thrown, this was the stack: 
#0      _HomeLayoutState.jsonWidget (package:fstore/widgets/home/index.dart:36:52)
#1      _HomeLayoutState.build (package:fstore/widgets/home/index.dart:149:11)
#2      StatefulElement.build (package:flutter/src/widgets/framework.dart:4623:28)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4506:15)
#4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4679:11)
...

**Comment by jberman280** [comment]
The issue was fixed. i found the fluxbuilder gives wrong config script. so i just modified it and compare it to the original. and everything is working.

1 issue left is: 

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
colors list must have at least two colors
'package:flutter/src/painting/gradient.dart':
Failed assertion: line 187 pos 12: 'colors.length >= 2'
The relevant error-causing widget was: 
  Container file:///C:/Users/user/Downloads/nyrod1/nyrod2/source/lib/widgets/home/category/category_icon_items.dart:94:19
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by jberman280** [comment]
And does image resizing work for shopify?

**Comment by luyx2412** [comment]
Hi @jberman280 Thanks for your effort. Can you give me the specific image resizing?

Thanks

**Comment by jberman280** [comment]
1:1 for all images. i want them to look all the same

**Comment by jberman280** [comment]
Any news yet? and how can i change privacy policy in signup and in settings page

**Comment by jberman280** [comment]
When i change   "kIsResizeImage": false, to true, images wont load at all.

**Comment by minhcasi** [comment]
@jberman280 - note with investigating, the `kIsResizeImage` option is not ready supported on the current release, we will investigate and upgrade it later

@luyx2412 - pls help to have a quick look to see if we could optimize more on the Shopify product image, for example, medium/large/small size?

**Comment by luyx2412** [comment]
Hi @jberman280 Sorry about missing your issues. Currently the shopify is not resize medium/large/small size. The image will not load in the kIsResizeImage option. So please change `kIsResizeImage : false`.

You can changed the privacy term content in`generated/messages_en.dart` line 226. And this message will not effect hotreload, so please build app again.
![image](https://user-images.githubusercontent.com/8909619/82561589-d8f00200-9b9d-11ea-83c9-3014374d8ff3.png)

Thanks

**Comment by jberman280** [comment]
Hi,

I have a problem with new version. it does not show products in home page only banners.

and i also wanna know how to change error messages that being shown to users.

I/flutter (20890): screenName null
I/flutter (20890): [2020-06-19 14:58:00.652392Z][Fluxstore][tabbar] ============== tabbar.dart DASHBOARD ==============
I/flutter (20890): [2020-06-19 14:58:00.710196Z][Fluxstore][tabbar] ============== tabbar.dart DASHBOARD ==============
I/flutter (20890): [2020-06-19 14:58:00.942962Z][Fluxstore][Home] initState
I/flutter (20890): [2020-06-19 14:58:00.948534Z][Fluxstore][Home] build
I/flutter (20890): ::::request fetchProductsByCategory with category id Z2lkOi8vc2hvcGlmeS9Db2xsZWN0aW9uLzE2MTY3MDY2MDE1MQ==
I/flutter (20890): ::::fetchProductsByCategory shopify error
I/flutter (20890): NoSuchMethodError: The getter 'cursor' was called on null.
I/flutter (20890): Receiver: null
I/flutter (20890): Tried calling: cursor
I/flutter (20890): ::::request fetchProductsByCategory with category id Z2lkOi8vc2hvcGlmeS9Db2xsZWN0aW9uLzE2MTUwODI5NDcxMQ==
I/flutter (20890): ::::fetchProductsByCategory shopify error
I/flutter (20890): NoSuchMethodError: The getter 'cursor' was called on null.
I/flutter (20890): Receiver: null
I/flutter (20890): Tried calling: cursor
I/flutter (20890): ::::request fetchProductsByCategory with category id Z2lkOi8vc2hvcGlmeS9Db2xsZWN0aW9uLzE2MTY3MDU5NDYxNQ==
I/flutter (20890): ::::fetchProductsByCategory shopify error
I/flutter (20890): NoSuchMethodError: The getter 'cursor' was called on null.
I/flutter (20890): Receiver: null
I/flutter (20890): Tried calling: cursor
I/flutter (20890): ::::request fetchProductsByCategory with category id Z2lkOi8vc2hvcGlmeS9Db2xsZWN0aW9uLzE2MTUwODQyNTc4Mw==
I/flutter (20890): ::::fetchProductsByCategory shopify error
I/flutter (20890): NoSuchMethodError: The getter 'cursor' was called on null.
I/flutter (20890): Receiver: null
I/flutter (20890): Tried calling: cursor
I/flutter (20890): ::::request fetchProductsByCategory with category id Z2lkOi8vc2hvcGlmeS9Db2xsZWN0aW9uLzE2MTUwODQ1ODU1MQ==
I/flutter (20890): ::::fetchProductsByCategory shopify error
I/flutter (20890): NoSuchMethodError: The getter 'cursor' was called on null.
I/flutter (20890): Receiver: null
I/flutter (20890): Tried calling: cursor
I/flutter (20890): [2020-06-19 14:58:01.688652Z][Fluxstore][Category] getCategories
I/flutter (20890): ::::request category
I/flutter (20890): getFilterAttributes: UnimplementedError
I/flutter (20890): ::::fetchProductsLayout shopify error
I/flutter (20890): NoSuchMethodError: The getter 'cursor' was called on null.
I/flutter (20890): Receiver: null
I/flutter (20890): Tried calling: cursor
I/flutter (20890): ::::fetchProductsLayout shopify error
I/flutter (20890): NoSuchMethodError: The getter 'cursor' was called on null.
I/flutter (20890): Receiver: null
I/flutter (20890): Tried calling: cursor
I/flutter (20890): ::::fetchProductsLayout shopify error
I/flutter (20890): NoSuchMethodError: The getter 'cursor' was called on null.
I/flutter (20890): Receiver: null
I/flutter (20890): Tried calling: cursor
I/flutter (20890): ::::fetchProductsLayout shopify error
I/flutter (20890): NoSuchMethodError: The getter 'cursor' was called on null.
I/flutter (20890): Receiver: null
I/flutter (20890): Tried calling: cursor
I/flutter (20890): ::::fetchProductsLayout shopify error
I/flutter (20890): NoSuchMethodError: The getter 'cursor' was called on null.
I/flutter (20890): Receiver: null
I/flutter (20890): Tried calling: cursor

**Comment by jberman280** [comment]
Its home product layouts does appear at all only banner layouts.

**Comment by jberman280** [comment]
════════ Exception caught by foundation library ════════════════════════════════════════════════════
The following NoSuchMethodError was thrown while dispatching notifications for ValueNotifier<bool>:
The method '-' was called on null.
Receiver: null
Tried calling: -(0.7788819890273544)

When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      RenderSliverMultiBoxAdaptor.childMainAxisPosition (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:573:37)
#2      RenderSliverHelpers.applyPaintTransformForBoxChild (package:flutter/src/rendering/sliver.dart:1695:20)
#3      RenderSliverMultiBoxAdaptor.applyPaintTransform (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:586:5)
#4      RenderObject.getTransformTo (package:flutter/src/rendering/object.dart:2345:24)
...
The ValueNotifier<bool> sending notification was: ValueNotifier<bool>#5e320(false)
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by luyx2412** [comment]
Hi @jberman280 I just invited you to the gitlab repo which is latest version, please check it about the issue. We will upgrade to the evanto soon.

Thanks

**Comment by jberman280** [comment]
Okay, Thanks

How can i change about us page url?

**Comment by jberman280** [comment]
I/flutter (17845): setCurrentCursor with hasNextPage true
I/flutter (17845): setCurrentCursor with cursor eyJsYXN0X2lkIjo0NTE1NjA3ODM4Nzc1LCJsYXN0X3ZhbHVlIjoiMCJ9
I/flutter (17845): GraphQL Errors:
I/flutter (17845): Malformed cursor: Undefined location
I/flutter (17845): ::::fetchProductsByCategory shopify error
I/flutter (17845): NoSuchMethodError: The method '[]' was called on null.
I/flutter (17845): Receiver: null
I/flutter (17845): Tried calling: []("node")
I/flutter (17845): ::::fetchProductsLayout shopify error
I/flutter (17845): NoSuchMethodError: The method '[]' was called on null.
I/flutter (17845): Receiver: null
I/flutter (17845): Tried calling: []("node")
I/flutter (17845): GraphQL Errors:
I/flutter (17845): Malformed cursor: Undefined location
I/flutter (17845): ::::fetchProductsByCategory shopify error
I/flutter (17845): NoSuchMethodError: The method '[]' was called on null.
I/flutter (17845): Receiver: null
I/flutter (17845): Tried calling: []("node")
I/flutter (17845): ::::fetchProductsLayout shopify error
I/flutter (17845): NoSuchMethodError: The method '[]' was called on null.
I/flutter (17845): Receiver: null
I/flutter (17845): Tried calling: []("node")
I/flutter (17845): GraphQL Errors:
I/flutter (17845): Malformed cursor: Undefined location
I/flutter (17845): ::::fetchProductsByCategory shopify error
I/flutter (17845): NoSuchMethodError: The method '[]' was called on null.
I/flutter (17845): Receiver: null
I/flutter (17845): Tried calling: []("node")
I/flutter (17845): ::::fetchProductsLayout shopify error
I/flutter (17845): NoSuchMethodError: The method '[]' was called on null.
I/flutter (17845): Receiver: null
I/flutter (17845): Tried calling: []("node")
I/flutter (17845): GraphQL Errors:
I/flutter (17845): Malformed cursor: Undefined location
I/flutter (17845): ::::fetchProductsByCategory shopify error
I/flutter (17845): NoSuchMethodError: The method '[]' was called on null.
I/flutter (17845): Receiver: null
I/flutter (17845): Tried calling: []("node")
I/flutter (17845): ::::fetchProductsLayout shopify error
I/flutter (17845): NoSuchMethodError: The method '[]' was called on null.
I/flutter (17845): Receiver: null
I/flutter (17845): Tried calling: []("node")
I/flutter (17845): ::::request fetchProductsByCategory with category id Z2lkOi8vc2hvcGlmeS9Db2xsZWN0aW9uLzE2MTY3MDU5NDYxNQ==
I/flutter (17845): ::::request fetchProductsByCategory with cursor 
I/flutter (17845): ::::request fetchProductsByCategory with category id Z2lkOi8vc2hvcGlmeS9Db2xsZWN0aW9uLzE2MTUwODI5NDcxMQ==
I/flutter (17845): ::::request fetchProductsByCategory with cursor 
I/flutter (17845): ::::request fetchProductsByCategory with category id Z2lkOi8vc2hvcGlmeS9Db2xsZWN0aW9uLzE2MTY3MDY2MDE1MQ==
I/flutter (17845): ::::request fetchProductsByCategory with cursor 
I/flutter (17845): GraphQL Errors:
I/flutter (17845): Malformed cursor: Undefined location
I/flutter (17845): ::::fetchProductsByCategory shopify error
I/flutter (17845): NoSuchMethodError: The method '[]' was called on null.
I/flutter (17845): Receiver: null
I/flutter (17845): Tried calling: []("node")
I/flutter (17845): ::::fetchProductsLayout shopify error
I/flutter (17845): NoSuchMethodError: The method '[]' was called on null.
I/flutter (17845): Receiver: null
I/flutter (17845): Tried calling: []("node")
I/flutter (17845): GraphQL Errors:
I/flutter (17845): Malformed cursor: Undefined location
I/flutter (17845): ::::fetchProductsByCategory shopify error
I/flutter (17845): NoSuchMethodError: The method '[]' was called on null.
I/flutter (17845): Receiver: null
I/flutter (17845): Tried calling: []("node")
I/flutter (17845): ::::fetchProductsLayout shopify error
I/flutter (17845): NoSuchMethodError: The method '[]' was called on null.
I/flutter (17845): Receiver: null
I/flutter (17845): Tried calling: []("node")
I/flutter (17845): GraphQL Errors:
I/flutter (17845): Malformed cursor: Undefined location
I/flutter (17845): ::::fetchProductsByCategory shopify error
I/flutter (17845): NoSuchMethodError: The method '[]' was called on null.
I/flutter (17845): Receiver: null
I/flutter (17845): Tried calling: []("node")
I/flutter (17845): ::::fetchProductsLayout shopify error
I/flutter (17845): NoSuchMethodError: The method '[]' was called on null.
I/flutter (17845): Receiver: null
I/flutter (17845): Tried calling: []("node")

**Comment by jberman280** [comment]
> Hi @jberman280 Sorry about reply you late. I just tested your config and everything worked normal. So can you clean `flutter clean` after that uninstall and reinstall app.
> 
> ![Simulator Screen Shot - iPhone 11 - 2020-05-17 at 16 33 35](https://user-images.githubusercontent.com/8909619/82140883-40cfe100-985c-11ea-8058-b2e2a17995af.png)
> ![Simulator Screen Shot - iPhone 11 - 2020-05-17 at 16 35 18](https://user-images.githubusercontent.com/8909619/82140905-69f07180-985c-11ea-9b4a-983cc23626a1.png)
> 
> P/S: Btw, your app is very beautiful.
> 
> Thanks

Please remove this picture as well. 

Thank you

**Comment by luyx2412** [comment]
HI @jberman280 Removed.

**Comment by karmelcorn** [comment]
I am having the same issues with products not showing up. What's the solution to the problem?

**Comment by kazimVahobov** [comment]
> Hi,
> 
> I have a problem with new version. it does not show products in home page only banners.
> 
> and i also wanna know how to change error messages that being shown to users.
> 
> I/flutter (20890): screenName null
> I/flutter (20890): [2020-06-19 14:58:00.652392Z][Fluxstore][tabbar] ============== tabbar.dart DASHBOARD ==============
> I/flutter (20890): [2020-06-19 14:58:00.710196Z][Fluxstore][tabbar] ============== tabbar.dart DASHBOARD ==============
> I/flutter (20890): [2020-06-19 14:58:00.942962Z][Fluxstore][Home] initState
> I/flutter (20890): [2020-06-19 14:58:00.948534Z][Fluxstore][Home] build
> I/flutter (20890): ::::request fetchProductsByCategory with category id Z2lkOi8vc2hvcGlmeS9Db2xsZWN0aW9uLzE2MTY3MDY2MDE1MQ==
> I/flutter (20890): ::::fetchProductsByCategory shopify error
> I/flutter (20890): NoSuchMethodError: The getter 'cursor' was called on null.
> I/flutter (20890): Receiver: null
> I/flutter (20890): Tried calling: cursor
> I/flutter (20890): ::::request fetchProductsByCategory with category id Z2lkOi8vc2hvcGlmeS9Db2xsZWN0aW9uLzE2MTUwODI5NDcxMQ==
> I/flutter (20890): ::::fetchProductsByCategory shopify error
> I/flutter (20890): NoSuchMethodError: The getter 'cursor' was called on null.
> I/flutter (20890): Receiver: null

Hi @jberman280 were you able to solve this problem?

**Comment by kazimVahobov** [comment]
Hi @luyx2412 Can you help me to solve the same problem?
