### ISSUE TITLE
[FluxStore] LOGIN

### ISSUE THREAD

**Issue by Blunnyn** [inspireui/support#3191]
Hi, I have a problem.
If you are not connected to your account and you add a product to the cart and you give it a checkout, it opens the window to log in. Then redirect to the cart again and pressing checkout again will redirect you to the login window and not the checkout.

I hope it is understood since it is a bit complex and I am using google translate

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as it could not be verified, please create the new one when you got enough purchased info - thank you!
