### ISSUE TITLE
How to add native payment? Fluxstore multi vendor

### ISSUE THREAD

**Issue by spetsglaz** [inspireui/support#3192]
Step 1 (require): detail issues and screenshots
Hello! I understand the payments.dart and to create a const, but how would i add a brand new payment? Would this be in the widgets like the paypal folder? In my payment developer site they provide me with downloading an sdk folder and state i need to link the dependencies. How would i link the dependencies on Fluxstore multi vendor? 

Thank you for the help :)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@spetsglaz - could you try the following step

1. add the native payment into pubspec.yaml file.
2. follow the guide from native payment library to see how it work, the example you could check this lib https://pub.dev/packages/stripe_payment that use for Stripe payment
3. You could try to follow our example from Paypal to make a similar payment

Let us know if you have any questions, thank you!
