### ISSUE TITLE
Apple login not working

### ISSUE THREAD

**Issue by juancamilocanal** [inspireui/support#3193]
I can't get apple login working either on emulator o device I get the error on the image. Please provide better documentation on apple login and on how to solve this problem:
![image](https://user-images.githubusercontent.com/818225/81955631-f2a6ad80-95cf-11ea-9af6-f91b459f01b2.png)

Proof of purchase:
![image](https://user-images.githubusercontent.com/818225/81955681-06521400-95d0-11ea-92f0-4fce27047349.png)

**Comment by minhcasi** [comment]
@juancamilocanal - could i know if you have enabled this option from the Firebase - https://tppr.me/xexw3 ?

**Comment by juancamilocanal** [comment]
Yes, that option is enabled

**Comment by juancamilocanal** [comment]
Any news with this issue?

**Comment by minhcasi** [comment]
@juancamilocanal - please help to check following solutions

1. Update the google-service file download from your Firebase
2. Update the OAuth consent from your Google account - https://user-images.githubusercontent.com/1459805/81786917-7e65fe80-952a-11ea-9756-4c735e595f12.png
3. You need paid apple account - Sign in with Apple you need a paid membership to the Apple Developer Program - 
4. pls check the detail on this video guide https://www.youtube.com/watch?v=14ALBSwvV4E&feature=youtu.be and this library https://pub.dev/packages/sign_in_with_apple
