### ISSUE TITLE
[FluxStore Pro] Problem with updating app realese in Google Play

### ISSUE THREAD

**Issue by bikostudio** [inspireui/support#3194]
Hi @minhcasi @luyx2412 @trunghieuvn @vumanhsn97 

three weeks ago I uploaded the app with ver. 1.6.6b to google play and it is live now. 
But today I tried to update to 1.7.3 but I got this error from Google Play

![2020-05-14_175902](https://user-images.githubusercontent.com/62074493/81957944-8ea2da00-960d-11ea-8901-3f721456c82b.jpg)

How to fix this please?

Please make this High priority as I need to update the app today at Google Play.

Thank you

**Comment by trunghieuvn** [comment]
Hi @bikostudio   
  
you can bum version code in pub.yaml in root folder source code   
 

![](https://user-images.githubusercontent.com/19247680/81966592-ee1bdc80-9643-11ea-8937-ea0b51e7661c.png)

**Comment by bikostudio** [comment]
> 
> 
> Hi @bikostudio 
> 
> you can bum version code in pub.yaml in root folder source code 
>  
> 
> ![](https://user-images.githubusercontent.com/19247680/81966592-ee1bdc80-9643-11ea-8937-ea0b51e7661c.png)

Thank you @trunghieuvn for fast respond. I will try and till you the result. Please don't close the issue.

**Comment by minhcasi** [comment]
@bikostudio - every time you upgrade a new version on Google Play, the version code should be increased.

@Haniel5 - pls help to update document for this issue

**Comment by bikostudio** [comment]
Works for me now thank you
