### ISSUE TITLE
my app is super slow to load the content

### ISSUE THREAD

**Issue by yasernet1989** [inspireui/support#3195]
Step 1 (require): detail issues and screenshots

Hello, my app after being published in play store is super slow to load the content - it takes around 20 to 30 seconds - to load the content which is too much for a flutter app.

I have already added the code   "isCaching": true,
in lib/common/config/general.dart 
and uploaded config_en.json to admin 

but its slow. can you please check it. i will send app url in google form verification for you to check

thanks

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by yasernet1989** [comment]
I solved the issue. Thanks

**Comment by RomeoDar** [comment]
how did you solve this issue, i'm also facing similar problem
