### ISSUE TITLE
Authorize.net payment gateway image is not displaying on payment page in mstore pro for WooCommerce

### ISSUE THREAD

**Issue by Varun24041993** [inspireui/support#3196]
Step 1 (require): detail issues and screenshots
I have added Authorize.net payment gateway and it is working fine but the image is not displaying on payment page. I have also checked the problem on device also it is still the same. Screenshot of error is attached and also the screenshot for plugin that I am using is also attached. I have done all the configurations in all the files required even I have added in Languages.js, Image.js and config.js still the error remains the same.

Issue Screenshot of emulator:
![error_screenshot](https://user-images.githubusercontent.com/56767455/81959918-d0437d00-962d-11ea-8639-f3e8b3be56b1.png)

Plugin used in wordpress for payment gateway:
![authorize_payment_plugin](https://user-images.githubusercontent.com/56767455/81959989-e6e9d400-962d-11ea-93b3-0bc6a2200642.png)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by bhardwajdeepak** [comment]
Same issue is happening with me, I have done everything. but no result

**Comment by Varun24041993** [comment]
Hi @luyx2412  please help us with this.

**Comment by luyx2412** [comment]
Hi @bhardwajdeepak Sorry about reply you late. You can add image in Config.js file line 105
![image](https://user-images.githubusercontent.com/8909619/82074109-7497f300-9704-11ea-8e6a-fc7f83c478cc.png)

Thanks

**Comment by Varun24041993** [comment]
Hi @luyx2412 I have sent you the config folder there you can see I have already added the image for authorize but still I am getting blank image in the app like the screenshot I have sent to you.

**Comment by luyx2412** [comment]
Hi @Varun24041993 Can you send me your AppConfig.json again? I just checked your config and wrong `consumerKey` and `consumerSecret`.

Thanks

**Comment by Varun24041993** [comment]
Hi @luyx2412 I have deleted the consumer key and secret while sending file to you so can you please provide me your email I don't want to share it in open.

**Comment by bhardwajdeepak** [comment]
> Hi @bhardwajdeepak Sorry about reply you late. You can add image in Config.js file line 105
> ![image](https://user-images.githubusercontent.com/8909619/82074109-7497f300-9704-11ea-8e6a-fc7f83c478cc.png)
> 
> Thanks

Sorry but I is not working, showing empty image.

**Comment by luyx2412** [comment]
Hi @bhardwajdeepak Please make sure, you opened the payment same your config.
Hi @Varun24041993 Please send the information via inspireui.team@gmail.com

Thanks

**Comment by bhardwajdeepak** [comment]
> Hi @bhardwajdeepak Please make sure, you opened the payment same your config.
> Hi @Varun24041993 Please send the information via [inspireui.team@gmail.com](mailto:inspireui.team@gmail.com)
> 
> Thanks

Hi, I did not get you. Please explain what you want to say.

**Comment by luyx2412** [comment]
Hi @bhardwajdeepak Please send your project via inspireui.team@gmail.com. I will fix it and re-send your project.

Thanks

**Comment by bhardwajdeepak** [comment]
> Hi @bhardwajdeepak Please send your project via [inspireui.team@gmail.com](mailto:inspireui.team@gmail.com). I will fix it and re-send your project.
> 
> Thanks

Please give me answer here. I will make those changes. I am using Payuindia payment gateway.

**Comment by bhardwajdeepak** [comment]
> Step 1 (require): detail issues and screenshots
> I have added Authorize.net payment gateway and it is working fine but the image is not displaying on payment page. I have also checked the problem on device also it is still the same. Screenshot of error is attached and also the screenshot for plugin that I am using is also attached. I have done all the configurations in all the files required even I have added in Languages.js, Image.js and config.js still the error remains the same.
> 
> Issue Screenshot of emulator:
> ![error_screenshot](https://user-images.githubusercontent.com/56767455/81959918-d0437d00-962d-11ea-8639-f3e8b3be56b1.png)
> 
> Plugin used in wordpress for payment gateway:
> ![authorize_payment_plugin](https://user-images.githubusercontent.com/56767455/81959989-e6e9d400-962d-11ea-93b3-0bc6a2200642.png)
> 
> Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)
> 
> _Important Note:_
> 
> * Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better.
> * If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
>   Thank you so much for your time 😊

Have you got the solution?

**Comment by luyx2412** [comment]
Hi @bhardwajdeepak Are you send project via inspireui.team@gmail.com? i could not see any things. Please add "subject" with your ticket id `3196`.

Thanks

**Comment by minhcasi** [comment]
@Varun24041993 - let us know if you have any update on this ticket - thank you!

**Comment by Varun24041993** [comment]
Hi @minhcasi I have to change the payment gateway because no image was displaying for android even after doing all the changes also the default placeholder image for payment gateway in android is also not displaying I have made a video to demonstrate the error you can see that even the default image supposed to be shown is not displaying in android but when I minimise and maximise the app then the image appears for a second and then it disappear. For iOS also when I added image for authorize.net it won't show so for iOS when I changed the default placeholder image for payment then it started showing the image else no other payment gateway image is showing. I have also previous sent you the screenshot for the plugin I am using for authorize.net.

Here is the video of the error google drive link for your app:
https://drive.google.com/file/d/1FygpkMIFJ_-5FovukwPodBmgTvicWFro/view?usp=sharing

**Comment by luyx2412** [comment]
Hi @Varun24041993 I tested your config which was wrong id of payment, please make sure you added right id. How to get id, you can see the api response same the screenshot.
![image](https://user-images.githubusercontent.com/8909619/83033032-caec2680-a060-11ea-813b-08c3556514aa.png)
![image](https://user-images.githubusercontent.com/8909619/83033030-caec2680-a060-11ea-8c10-6c0984be5e09.png)
![image](https://user-images.githubusercontent.com/8909619/83033058-cfb0da80-a060-11ea-9b59-f569bee417ed.png)

Thanks

**Comment by Varun24041993** [comment]
Hi @luyx2412  thanks for the response sure I will try that, please let me know how have you post payment id request to get these parameters.

**Comment by luyx2412** [comment]
HI @Varun24041993 You can use Reactotron to debug about response api. https://docs.inspireui.com/mstore/project-structure/#debug-app-with-reacttotron

Thanks

**Comment by Varun24041993** [comment]
Hi @luyx2412 thanks for the response
