### ISSUE TITLE
[Fluxstore Pro - Woocommerce] - Mstore Plugin Not showing new jason

### ISSUE THREAD

**Issue by tjain90** [inspireui/support#3197]
Step 1 (require): detail issues and screenshots

New json is not getting updated in app while it is properly uploaded in mstore plugin.

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by minhtruong315** [comment]
@tjain90 I don't understand your issue. please record screen

**Comment by tjain90** [comment]
After Uploading new json file to my woocommerce website i could not see my new home page. It shows my previous home page in app.

**Comment by minhtruong315** [comment]
<img width="875" alt="Screen Shot 2020-05-17 at 6 35 52 AM" src="https://user-images.githubusercontent.com/10402500/82132321-b3af6c80-9808-11ea-9e4a-85519927f746.png">
Did you enable isCaching?

**Comment by tjain90** [comment]
Yes caching is true. 
Previously it was working fine. It stopped working whan I jave update app to 1.7.1 and updated plugin as well

**Comment by tjain90** [comment]
Below is my general config.
![Screenshot_20200517-091105](https://user-images.githubusercontent.com/6376301/82135291-9f766a00-981e-11ea-9a63-d8cda5978966.jpg)

**Comment by minhtruong315** [comment]
Hi @tjain90 can u upload your source code to github then invite me: minhtruong315@gmail.com
I will check and fix on your source code
Thanks

**Comment by tjain90** [comment]
Thanks I have invited you to my project. Updated Jason is already uploaded on mstore plugin. But app is showing current jason when it was compiled. 

It would be great if you can check sms login which ia also not working. #3046

**Comment by minhtruong315** [comment]
Hi @tjain90 I checked your source code. you're using the old version Fluxstore. You need to download version 1.7.3 on codecanyon and upgrade flutter to 1.17 then check again

**Comment by tjain90** [comment]
Hi @minhtruong315 i have update code and version but still updating new config don't update home screen

**Comment by tjain90** [comment]
Please reopen this ticket
