### ISSUE TITLE
Failed assertion: boolean expression must not be null

### ISSUE THREAD

**Issue by joaonathan** [inspireui/support#3198]
![Sem título](https://user-images.githubusercontent.com/9143192/81970256-96ef1b00-95f5-11ea-91b1-ac90ee362971.png)

Performing hot reload...
Syncing files to device Android SDK built for x86...
I/flutter ( 5073): [2020-05-14 18:02:59.920766Z][Fluxstore][AppState] build
I/flutter ( 5073): [2020-05-14 18:02:59.929262Z][Fluxstore][AppState] build Theme
I/flutter ( 5073): [2020-05-14 18:03:00.010184Z][Fluxstore][tabbar] ============== tabbar.dart DASHBOARD ==============
I/flutter ( 5073): [2020-05-14 18:03:00.053144Z][Fluxstore][Home] build

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building HomeLayout-[<'pt'>](dirty, state: _HomeLayoutState#4610d):
Failed assertion: boolean expression must not be null

The relevant error-causing widget was: 
  HomeLayout-[<'pt'>] file:///E:/FluxStore-woo%201.7.3/source/lib/screens/home/home.dart:119:13
When the exception was thrown, this was the stack: 
#0      _HomeLayoutState.build (package:fstore/widgets/home/index.dart:165:34)
#1      StatefulElement.build (package:flutter/src/widgets/framework.dart:4619:28)
#2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4502:15)
#3      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
#4      Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
...

how do i resolve this error?

**Comment by minhcasi** [comment]
Hi @joaonathan - thank you for your feedback, could you help to try to override this config_en.json - you could us this file and clone to other config json language, example config_es.json

[config_en.json.zip](https://github.com/inspireui/support/files/4631906/config_en.json.zip)

**Comment by joaonathan** [comment]
Thanks

**Comment by joaonathan** [comment]
the error reappeared
