### ISSUE TITLE
Unable to get selected country from Country dropdown when checkout

### ISSUE THREAD

**Issue by hamzahz** [inspireui/support#3199]
Facing issue of country not selected even when country was selected
 pakage_name : react-native-country-picker-modal
file_path:  mstore-multi-vendor-v1.3.3/mstore-mv-expo/src/containers/AddAddress/index.js

**Comment by luyx2412** [comment]
Hi @hamzahz Can you share me the screenshot? 

Thanks

**Comment by hamzahz** [comment]
https://www.dropbox.com/s/kb9t1tir2hw6jep/20200516144941.mp4?dl=0

Here is the video attached for reference

**Comment by luyx2412** [comment]
Hi @hamzahz Sorry about reply you late. Please update latest version to fix the issues.

Thanks
