### ISSUE TITLE
[Listapp] still now I didn't get any solution for heart icon button

### ISSUE THREAD

**Issue by Pavithran10** [inspireui/support#320]
**Required Info (please complete the following information):**
Product:[ListApp]
Version:1.6.1
Theme: MyListing

**Describe the bug**
you send this command few days before for heart icon button error
It'll fix the error "props.onPress is not a function" when clicking on heart button. but still now error not cleared. so, please give any other idea or suggestion about to clear this error. thanks

**Screenshots**
![list booking1](https://user-images.githubusercontent.com/46148046/53068721-74a84380-34ff-11e9-8589-7f3beeaa1582.jpg)
![favourites icon err](https://user-images.githubusercontent.com/46148046/53068734-7e31ab80-34ff-11e9-9d7f-4e8bde49930c.png)

**Comment by thangvo9x** [comment]
Hi. This is a bug && we'll release in the version. Thanks

**Comment by Pavithran10** [comment]
ok, thanks
