### ISSUE TITLE
[ Fluxstore Pro 1.7.4 ]- Error when running the app (smooth_star_rating)

### ISSUE THREAD

**Issue by Alnaggar94** [inspireui/support#3200]
- Hi, I just downloaded the v 1.7.4 from Gitlab and when I try to run the app it shows the following error I have tried all possible solutions (flutter clean, delete the pubspec.lock then run the command flutter pub get, delete the flutter cash, etc...) I think it has something to do with (smooth_star_rating):

![u1](https://user-images.githubusercontent.com/49800146/81990961-e579d500-9648-11ea-8376-7f5f77cf09fc.JPG)

![u2](https://user-images.githubusercontent.com/49800146/81990979-eb6fb600-9648-11ea-850b-69df39b30531.JPG)

- I verified my purchase code and upload the Config Files through - http://private.inspireui.com

**Comment by tiagosoliver** [comment]
change rate_my_app: 0.6.0+2 to rate_my_app: 0.6.0+3  / in pubspec.yaml

**Comment by sketchuprzr** [comment]
Version 1.7.4 has not been fully released. The version included in gitlab is pre-1.7.4 version. Contains errors. It would be more accurate to wait for the release of the official version 1.7.4.

**Comment by minhcasi** [comment]
@Alnaggar94 - we will have a check and let you know

**Comment by ameenbadri7** [comment]
yesterday i fix the error. 
you just have to add this to your Pubspec yaml file:
smooth_star_rating: ^1.1.0+1

what really happened is the flutter team had changed the international api 
onRatingChanged -> onRated

if you just replace on rating change with => onrated it will fix it . 

https://pub.dev/packages/smooth_star_rating#-changelog-tab-

i have made 1.7.4 working beautifully. 
i love fluxstore app very much.

**Comment by kvt0012** [comment]
You should come to pubspec.yaml and upgrade rate\_my\_app to 0.6.0+3, it will fix your issue, thank you

**Comment by Alnaggar94** [comment]
@tiagosoliver - Thank you so much it's working now.
