### ISSUE TITLE
[FluxStore Pro] Question About User Registration

### ISSUE THREAD

**Issue by bikostudio** [inspireui/support#3201]
Hi @trunghieuvn  @minhcasi 

I have a question, Is it possible to use WordPress registration page within the app instead of the normal app registration screen? 

I mean, When new user tap on Sign in it open the WordPress registration from from the site. 

Thank you

**Comment by minhcasi** [comment]
@bikostudio - I'm not sure if it is possible as you should sync the cookies from webview to app - you could investigate and share with us

**Comment by bikostudio** [comment]
> 
> 
> @bikostudio - I'm not sure if it is possible as you should sync the cookies from webview to app - you could investigate and share with us

Hi @minhcasi I really don't know how to do this to share it. That's why I'm asking you as a app developer. 

I Really want to make the WordPress registration form to be the default registration form on FluxStore App.

Any Ideas?

Thank you
