### ISSUE TITLE
Change image Category ! Shopify 

### ISSUE THREAD

**Issue by rabahaldoori** [inspireui/support#3204]
how i can change the Category image ? could you help me , and also 
<img width="345" alt="Screen Shot 2020-05-14 at 10 23 56 PM" src="https://user-images.githubusercontent.com/31085177/82008260-c754aa80-9631-11ea-8aa1-e698341b29b1.png">

thanks

**Comment by minhcasi** [comment]
please help us to move your all conversion to one ticket #3187 - our team will check all and get back you shortly - thank you!
