### ISSUE TITLE
Push Notifications /Shopify 

### ISSUE THREAD

**Issue by rabahaldoori** [inspireui/support#3205]
Notifications show inside the app but not showing when i'm out side the app but save in "notify massage " 
<img width="1216" alt="Screen Shot 2020-05-14 at 11 41 41 PM" src="https://user-images.githubusercontent.com/31085177/82012218-e73d9b80-963c-11ea-90f8-2bb5e5767538.png">

**Comment by minhcasi** [comment]
please help us to move your all conversion to one ticket #3187 - our team will check all and get back you shortly - thank you!
