### ISSUE TITLE
"flutter pub get" in source getting failed. du eto google_sign_in dependencies.

### ISSUE THREAD

**Issue by shah0203** [inspireui/support#3208]
Hi,

When i am running **"flutter pub get"** i am getting below error message. your prompt resolution will be highly appreciated. thanks!

**My current Version Details:**
------------------------------
$ flutter --version
Flutter 1.12.13 • channel stable • https://github.com/flutter/flutter.git
Framework • revision cf37c2cd07 (6 months ago) • 2019-11-25 12:04:30 -0800
Engine • revision b6b54fd606
Tools • Dart 2.7.2

------------------------------------------------------------
**Error Message:**
----------------
Running "flutter pub get" in source...                          
The current Flutter SDK version is 1.12.13.

Because fstore depends on google_sign_in >=4.1.0 which requires Flutter SDK version >=1.12.13+hotfix.4 <2.0.0, version solving failed.
pub get failed (1; Because fstore depends on google_sign_in >=4.1.0 which requires Flutter SDK version >=1.12.13+hotfix.4 <2.0.0, version solving failed.)
Process finished with exit code 1

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by shah0203** [comment]
Hi Minhcasi,

I have submitted the form as requested above.

**Comment by shah0203** [comment]
Kindly find below image which i missed to upload for the above request.

![image](https://user-images.githubusercontent.com/63024624/82050204-63c58e00-96c0-11ea-8a06-7688694dc6fd.png)

**Comment by shah0203** [comment]
hi,

I have submitted the form with all requested details. Kindly do let me know in case of anything required. thanks for your prompt response.

reagds,
shah
________________________________

**Comment by minhcasi** [comment]
@shah0203 - pls try this script to update to latest flutter version 
```
flutter channel stable
flutter upgrade --force
flutter pub get
```

**Comment by shah0203** [comment]
Hi minhcasi,
I executed the above steps but still the same issue. below is the output of the steps.

----------------------------------------------------------------------------------------------
**$ flutter channel stable**
Switching to flutter channel 'stable'...
git: From https://github.com/flutter/flutter
git:    800e95116..32547dcc7  master     -> origin/master
git: Your branch is behind 'origin/stable' by 1512 commits, and can be fast-forwarded.
git:   (use "git pull" to update your local branch)
git: Already on 'stable'

**$ flutter upgrade --force**
Upgrading Flutter from C:\src\flutter\flutter...
error: The following untracked working tree files would be overwritten by merge:
        packages/_flutter_web_build_script/README.md
        packages/_flutter_web_build_script/analysis_options.yaml
        packages/_flutter_web_build_script/lib/build_script.dart
        packages/_flutter_web_build_script/pubspec.yaml
        packages/flutter/lib/src/foundation/object.dart
        packages/flutter/lib/src/foundation/stack_frame.dart
        packages/flutter/lib/src/material/curves.dart
        packages/flutter/lib/src/material/navigation_rail.dart
        packages/flutter/lib/src/material/navigation_rail_theme.dart
        packages/flutter/lib/src/material/pickers/calendar_date_picker.dart
        packages/flutter/lib/src/material/pickers/date_picker_common.dart
        packages/flutter/lib/src/material/pickers/date_picker_deprecated.dart
        packages/flutter/lib/src/material/pickers/date_picker_dialog.dart
        packages/flutter/lib/src/material/pickers/date_picker_header.dart
        packages/flutter/lib/src/material/pickers/date_utils.dart
        packages/flutter/lib/src/material/pickers/input_date_picker.dart
        packages/flutter/lib/src/material/pickers/pickers.dart
        packages/flutter/lib/src/rendering/mouse_tracking.dart
        packages/flutter/lib/src/rendering/proxy_sliver.dart
        packages/flutter/lib/src/widgets/disposable_build_context.dart
        packages/flutter/lib/src/widgets/image_filter.dart
        packages/flutter/lib/src/widgets/scroll_aware_image_provider.dart
        packages/flutter/lib/src/widgets/sliver_fill.dart
        packages/flutter/test/foundation/defines_test.dart
        packages/flutter/test/foundation/stack_frame_test.dart
        packages/flutter/test/material/navigation_rail_test.dart
        packages/flutter/test/material/navigation_rail_theme_test.dart
        packages/flutter/test/material/text.dart
        packages/flutter/test/rendering/mouse_tracking_test.dart
        packages/flutter/test/rendering/proxy_sliver_test.dart
        packages/flutter/test/rendering/viewport_caching_test.dart
        packages/flutter/test/services/text_formatter_test.dart
        packages/flutter/test/widgets/binding_cannot_schedule_frame_test.dart
        packages/flutter/test/widgets/binding_deferred_first_frame_test.dart
        packages/flutter/test/widgets/disposable_build_context_test.dart
        packages/flutter/test/widgets/image_filter_test.dart
        packages/flutter/test/widgets/list_view_semantics_test.dart
        packages/flutter/test/widgets/localizations_test.dart
        packages/flutter/test/widgets/multichildobject_with_keys_test.dart
        packages/flutter/test/widgets/scroll_aware_image_provider_test.dart
        packages/flutter/test/widgets/sliver_visibility_test.dart
        packages/flutter/test/widgets/text_semantics_test.dart
        packages/flutter/test/widgets/ticker_mode_test.dart
        packages/flutter_driver/lib/src/common/layer_tree.dart
        packages/flutter_driver/lib/src/driver/vmservice_driver.dart
        packages/flutter_driver/lib/src/driver/web_driver.dart
        packages/flutter_driver/lib/src/extension/_extension_io.dart
        packages/flutter_driver/lib/src/extension/_extension_web.dart
        packages/flutter_driver/test/src/real_tests/extension_test.dart
        packages/flutter_driver/test/src/real_tests/find_test.dart
        packages/flutter_driver/test/src/real_tests/io_extension_test.dart
        packages/flutter_driver/test/src/real_tests/timeline_summary_test.dart
        packages/flutter_driver/test/src/real_tests/timeline_test.dart
        packages/flutter_driver/test/src/real_tests/wait_test.dart
        packages/flutter_driver/test/src/web_tests/web_extension_test.dart
        packages/flutter_test/lib/src/_matchers_io.dart
        packages/flutter_test/lib/src/_matchers_web.dart
        packages/flutter_test/lib/src/buffer_matcher.dart
        packages/flutter_test/test/bindings_test_failure.dart
        packages/flutter_tools/gradle/.dartignore
        packages/flutter_tools/lib/src/android/android_device_discovery.dart
        packages/flutter_tools/lib/src/base/bot_detector.dart
        packages/flutter_tools/lib/src/base/command_help.dart
        packages/flutter_tools/lib/src/base/error_handling_file_system.dart
        packages/flutter_tools/lib/src/base/template.dart
        packages/flutter_tools/lib/src/build_runner/devfs_web.dart
        packages/flutter_tools/lib/src/build_runner/mustache_template.dart
        packages/flutter_tools/lib/src/build_system/targets
Updating cf37c2cd0..f7a6a7906
Aborting

**$ flutter pub get**
Running "flutter pub get" in source...
The current Flutter SDK version is 1.12.13.

Because fstore depends on google_sign_in >=4.1.0 which requires Flutter SDK version >=1.12.13+hotfix.4 <2.0.0, version solving failed.
pub get failed (1; Because fstore depends on google_sign_in >=4.1.0 which requires Flutter SDK version >=1.12.13+hotfix.4 <2.0.0, version solving
failed.)

**Comment by minhcasi** [comment]
@shah0203 - try to update the pubspec `google_sign_in: 4.4.6` - you could also try to download the latest package 1.7.3 to fix the issue, there is new 1.7.4 will be released in next couple of day

**Comment by shah0203** [comment]
Hi,

Ok, i will try to update pubspec google_sign_in: 4.4.6. mean while it would be great help if you can send me the exact URL link to download the latest package 1.7.3 to fix the issue. Thanking you in advance and waiting for your response.

**Comment by shah0203** [comment]
@minhcasi - I downloaded 1.7.3 package but can you tell me how can i migrate all the changes which was done in my current version 1.6.5c to new version 1.7.3.

**Comment by minhcasi** [comment]
@shah0203 - could I check if you have managed your custom code by using git, we will upload a new video on next couple of day to share 'how to use git to manage the fluxstore version', please follow our update from - http://youtube.com/inspireui

There are a lot of changes between 2 versions if you are happy with your custom source on 1.6.5c then just keep that version.

**Comment by minhcasi** [comment]
@shah0203 - please help to use this guide to manage your project via Git

Video: https://drive.google.com/drive/folders/1kFLOwuzccrh2nxcVhn_m6OzOQrYfXoiX?usp=sharing
Docs: https://github.com/inspireui/support/wiki/Guide-to-using-git-to-work-repo-Fluxstore-pro

Content:
    FORK GIT FLUXSTORE 			:	 00:00 - 05:22
    INSTALL SOURCETREE			:	 05:23 - 08:27
    MERGE CODE - NO CONFLICT	: 	 08:28 - 10:56
    MERGE CODE - CONFLICT		:	 10:57  - 13:37

Let us know if you have any questions
