### ISSUE TITLE
[FluxStore Pro] Adding clickable Bunner with Image to Categories Screen

### ISSUE THREAD

**Issue by bikostudio** [inspireui/support#3209]
Hi @minhcasi @trunghieuvn 

**### Please, I want to add an banner image to be at the end of the Category screen. An I want it to be clickable with external link url . And I want the Image is a network image not asset image please**

### **Question: How to make external open on chrome instead of opening in the app built-in browser?**

![2020-05-15_140426](https://user-images.githubusercontent.com/62074493/82048613-43440680-96b5-11ea-86d8-d786791f11a7.jpg)

thank you for your time and help

**Comment by minhcasi** [comment]
@bikostudio - you could use this lib to open the banner image at the bottom of category page - https://pub.dev/packages/url_launcher

**Comment by bikostudio** [comment]
> 
> 
> @bikostudio - you could use this lib to open the banner image at the bottom of category page - https://pub.dev/packages/url_launcher
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/c8aac9817108b9bec9f8beaed2bd5bfab62f1899/68747470733a2f2f7075622e6465762f7374617469632f696d672f7075622d6465762d69636f6e2d636f7665722d696d6167652e706e673f686173683d76673836723272336d62733632686976346c646f703069666535756d32673567">Dart packages**[url_launcher | Flutter Package](https://pub.dev/packages/url_launcher)**Flutter plugin for launching a URL on Android and iOS. Supports web, phone, SMS, and email schemes.

Thank you @minhcasi  for the code. But which file in FluxStore app I have to use this lib? 
and how to add an image banner with it?

thank you for your time and help

**Comment by bikostudio** [comment]
I tried to add it in lib/categories/index.dart 
but nothing happened.

**Comment by bikostudio** [comment]
Hi @philipvu30
Would you please give me a ready code to paste it? and tell me where to paste it please? 
thank you

**Comment by bikostudio** [comment]
4th day now and no answer
