### ISSUE TITLE
Google Signin Not Working

### ISSUE THREAD

**Issue by inspireuis** [inspireui/support#3210]
I integrated the google signin. It is able to fetch the info but the app keeps loading the progress bar. When I click back button at the top left corner then it shows the option to logout. When I purchase the anything then in shipment details it shows me the email address I selected while doing google login.

The problem is it should automatically redirect to profile screen.

Getting token from google (checked in logs)
before that getting below error 
 type 'String' is not a subtype of type 'int' of 'index'

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as it could not be verified, please create the new one when you got enough purchased info - thank you!

**Comment by inspireuis** [comment]
Getting below error after saving user to firebase

W/DynamiteModule( 3969): Local module descriptor class for providerinstaller not found.
I/DynamiteModule( 3969): Considering local module providerinstaller:0 and remote module providerinstaller:0
W/ProviderInstaller( 3969): Failed to load providerinstaller module: No acceptable module found. Local version is 0 and remote version is 0.
V/NativeCrypto( 3969): Registering com/google/android/gms/org/conscrypt/NativeCrypto's 286 native methods...
I/ProviderInstaller( 3969): Installed default security provider GmsCore_OpenSSL

Please help
