### ISSUE TITLE
IOS App Build 

### ISSUE THREAD

**Issue by gmldigital2019** [inspireui/support#3213]
Good Day Please note this error is coming up every time we attempt an app build for IOS.  
![WhatsApp Image 2020-05-11 at 2 53 26 PM (1)](https://user-images.githubusercontent.com/60437057/82100721-71870d80-96d8-11ea-9ee5-a89597799f7f.jpeg)

**Comment by minhcasi** [comment]
@luyx2412 - pls help to suggest on this issue

**Comment by luyx2412** [comment]
Hi @gmldigital2019 Please remove height style in `Components/PostLayout/Card/index.js` file same the screenshot. The issue related height wrong format.
![image](https://user-images.githubusercontent.com/8909619/82114487-2bd54e00-9787-11ea-88bf-64feba61e499.png)

Thanks

**Comment by gmldigital2019** [comment]
Hi we got the error to work, however, we are getting this error when a story does not have a featured
![WhatsApp Image 2020-05-16 at 5 15 29 PM](https://user-images.githubusercontent.com/60437057/82225512-4e847580-98f3-11ea-9f47-7d719b037e21.jpeg)
 image.
