### ISSUE TITLE
Design - Custom search box "Feature Request"

### ISSUE THREAD

**Issue by sketchuprzr** [inspireui/support#3215]
You can use the special search box that I prepared using the application parts on your homepage.
Just edit your _"header_type.dart"_ file.
You can then place it in your "config.json" file as desired.

### Design;
![srch](https://user-images.githubusercontent.com/60021696/82108543-d02fa400-9737-11ea-9b05-cfdba7337c7c.gif)
-----
![image](https://user-images.githubusercontent.com/60021696/82108735-4b458a00-9739-11ea-8620-08bfe8949002.png)

### How?
**1- place this code on top of the "case:" static ":" code in the "header_type.dart" file. (line:93)**

`      case 'animatedSearch':
        return Container(
          height: 40.0,
          padding: const EdgeInsets.only(left: 15.0, right: 15.0),
          decoration: BoxDecoration(
            color: Theme.of(context).primaryColorLight,
            boxShadow: [
              BoxShadow(
                color: Colors.black12,
                blurRadius: Tools.formatDouble(config['shadow'] ?? 15.0),
                offset: Offset(0, Tools.formatDouble(config['shadow'] ?? 10.0)),
              ),
            ],
            borderRadius: BorderRadius.circular(
              Tools.formatDouble(config['radius'] ?? 30.0),
            ),
            border: Border.all(
              width: 1.0,
              color: Colors.black.withOpacity(0.05),
            ),
          ),
          child: Row(
           mainAxisAlignment: MainAxisAlignment.start,
           children: <Widget>[
            TypewriterAnimatedTextKit(
              isRepeatingAnimation: true,
              speed: Duration(milliseconds:  150),
              pause: Duration(milliseconds:  2000),
              totalRepeatCount: 50,
              text: _rotate,
              textAlign: TextAlign.center,
              textStyle: TextStyle(
                fontSize: _fontSize,
                fontWeight: FontWeight.w500,
              ),
            ),
           ],
          ),
        );
`
**Eg:**
![image](https://user-images.githubusercontent.com/60021696/82108700-fc97f000-9738-11ea-900f-682b40b5a3af.png)

**2- Place this part (code) in your "config.json" file as you wish;**
`
    {
      "layout": "header_text",
      "fontsize": 20.0,
      "padding": 40.0,
      "height": 0.17,
      "rotate": [
        "Your title 1",
        "Your title 2",
        "Your title 3"
      ],
      "type": "animatedSearch",
      "showSearch": true
    }
`
**Eg:**
![image](https://user-images.githubusercontent.com/60021696/82108712-11748380-9739-11ea-9eaf-10ffd471edb1.png)

thanks to the inspireui team  🤝

**Comment by minhcasi** [comment]
@sketchuprzr - thank you for the suggestion, it's a great idea

@vumanhsn97 - pls help to investigate and update into Fluxstore + Fluxbuilder

**Comment by vumanhsn97** [comment]
updated!!!
