### ISSUE TITLE
SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at 

### ISSUE THREAD

**Issue by surajk1986** [inspireui/support#3216]
Step 1 (require): https://drive.google.com/open?id=1UdaAJDbGfmO7An4Zd95UjU-ecjY1Oe8X

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@surajk1986 - please help to edit the local.properties file and change to your own Android SDK - also try to run `flutter doctor` to see if you have any issues need to be fixed

<img width="895" alt="Screen Shot 2020-05-16 at 14 04 36" src="https://user-images.githubusercontent.com/1459805/82113177-3212fc80-977e-11ea-8dce-fbf023317402.png">

Also pls help to move/update your conversation on this ticket #3177 and keep to raise only one ticket for your all issues

**Comment by minhcasi** [comment]
Also, read this document also could help - https://flutter.dev/docs/get-started/install/windows?gclid=Cj0KCQjwnv71BRCOARIsAIkxW9E2H991XhSfKAEIlrdAKtMdeTJT8iw_O25zrG6msI7FM8q5lnhLQA0aAqA1EALw_wcB&gclsrc=aw.ds
