### ISSUE TITLE
Cannot register and cannot access vendor dashboard 

### ISSUE THREAD

**Issue by olorunfemi007** [inspireui/support#3217]
Hello, Please I can’t seem to register using without google authentication or Facebook.
i get an “Exception” error as a snack bar. 
I’m also not able to access the vendor dashboard once I login to app as a vendor. 
I use Dokan as my multi vendor plugin.
Pls kindly help resolve this issue.

**Comment by minhcasi** [comment]
@olorunfemi007 
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by olorunfemi007** [comment]
I have sent my details to the above link. 
Thank you.

**Comment by olorunfemi007** [comment]
Hello, Pls kindly give me an update on my problem

**Comment by minhcasi** [comment]
@minhtruong315 - pls help to suggest on this issue - thank you!

**Comment by minhtruong315** [comment]
Hi @olorunfemi007 can u upload your source code to github then invite me: minhtruong315@gmail.com
I will help you check and fix on your source code.
Thanks

**Comment by olorunfemi007** [comment]
Thank you for your reply. I was able to get the create product page to show in settings. Discovered the “isVender” variable returns null. So the option doesn’t show. But meanwhile I’m not able to post product too. It keeps loading posting products and nothing happens.

**Comment by olorunfemi007** [comment]
I already invited you. Here is the invite: https://github.com/olorunfemi007/Store/invitations
I also want to say how amazing the product is. You’re doing a good work.

**Comment by minhtruong315** [comment]
Hi @olorunfemi007 Did you update MStore Api plugin to the latest version?

**Comment by olorunfemi007** [comment]
Yes I did. I also activated my license on MStore

**Comment by olorunfemi007** [comment]
> Thank you for your reply. I was able to get the create product page to show in settings. Discovered the “isVender” variable returns null. So the option doesn’t show. But meanwhile I’m not able to post product too. It keeps loading posting products and nothing happens.

Do you have any solution to this problem ?

**Comment by minhtruong315** [comment]
I fixed "isVender" on your source code. pls pull update.

**Comment by minhtruong315** [comment]
@olorunfemi007 can u send me admin  account via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/3217

**Comment by olorunfemi007** [comment]
I have sent my account details to the above email

**Comment by olorunfemi007** [comment]
> I fixed "isVender" on your source code. pls pull update.

I didn’t see any recent commit by you to the repository

**Comment by minhtruong315** [comment]
I just commit. pls check again. thanks

**Comment by minhtruong315** [comment]
Hi @olorunfemi007 please pull updates. I fixed register user.

**Comment by olorunfemi007** [comment]
Thank you for the work so far. The register now works. But the isVender variable still returns null. And post product doesn’t work still. 
Regards.

**Comment by olorunfemi007** [comment]
I have fixed product posting. There was an error with product price data type. But when I create a variable product I can’t see the option to add the variations. 
Is it also possible to delete products listed or change stock in inventory. Also can I get list of orders for a vendor. 
Regards.

**Comment by minhtruong315** [comment]
Hi @olorunfemi007 
- isVender variable is working well on your source code. I dont see it returns null.
- Fluxstore doesn't  support add the variantions while post product. You need to update variantions on admin panel.
- You only can create product, you can't  delete or change product in app.
- Fluxstore doesn't support get list of orders for vendor now.

**Comment by olorunfemi007** [comment]
![D381B4BD-D1D1-421C-A65D-FE021896F1DA](https://user-images.githubusercontent.com/22244303/82236715-6cba9780-992c-11ea-980f-a20681539afd.png)
Pls kindly look at the misleading add your company put up. It clearly states that product variant can be created. You guys even go as far to say we should upgrade to dokan pro to get the full features. 
Because without these features I can’t publish this app. 
Pls kindly test with a user that isn’t a vendor. You’ll see the product page in setting still showing . And a user can’t register unless the vendor checkbox is ticked. Pls kindly look into this.

**Comment by olorunfemi007** [comment]
Hello, pls kindly help fix the registration and isVender issue.

**Comment by minhtruong315** [comment]
@olorunfemi007 Product  variant is showing in detail page.

**Comment by minhtruong315** [comment]
Can u record screen for issue isVender? I checked your source code. it's working well
https://www.dropbox.com/s/fpmoq442lup2gws/register.mov?dl=0

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
