### ISSUE TITLE
UI Editing using Flutter Inspector Issue

### ISSUE THREAD

**Issue by masthan8** [inspireui/support#3218]
Hi there, 

I am trying to modify, actually change colors for some part of the application and as per your document I tried the flutter inspector but its not jumping to the source. For example, if I want to change the search icon in the homepage header, when I click that in the flutter inspector and try to jump to the source, nothing happens, tried in 2 different PCs, this is happening after the latest update and like before 2 months it was working fine 

Kindly let me know how to fix this and edit the UI. thanks 

I already have access to your GITLAB too, username is masthan_8

**Comment by minhcasi** [comment]
@masthan8 - you could try to update the Android Studio + Flutter plugin to the latest version.

And make sure you are using latest Flutter as well, try to run 
```
flutter channel stable
flutter upgrade --force
```

If it still not work, please try to use the web tool - https://flutter.dev/docs/development/tools/devtools/overview

Let us know with your checking 👍

**Comment by minhcasi** [comment]
Let us know if you have any question, feel free to reopen or create a new ticket - very best 😊
