### ISSUE TITLE
Exception: The plugin cloud_firestore could not be built due to the issue above.

### ISSUE THREAD

**Issue by JoDeveloper** [inspireui/support#3219]
```
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin app_settings...
✓ Built build/app/outputs/repo.
Building plugin apple_sign_in...
✓ Built build/app/outputs/repo.
Building plugin cloud_firestore...
Exception: The plugin cloud_firestore could not be built due to the issue above.
Exited (sigterm)
```

**Comment by minhcasi** [comment]
@JoDeveloper 

Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by JoDeveloper** [comment]
ok @minhcasi

**Comment by JoDeveloper** [comment]
done @minhcasi

**Comment by minhcasi** [comment]
@JoDeveloper - could you help to clarify about more on this issue, is this happen you build the apk? or run at the debug mode?

Please make to change your own bundle ID if you build the final apk app - https://docs.inspireui.com/fluxstore/delivery-android/

**Comment by JoDeveloper** [comment]
No I'm just trying to run the app?

**Comment by JoDeveloper** [comment]
@minhcasi  ???

**Comment by minhcasi** [comment]
@JoDeveloper - pls try following solution 
1. Send us your `flutter doctor` result 
2. Make sure you could run this Example from Flutter https://flutter.dev/docs/get-started/test-drive?tab=vscode
3. There could be the Flutter cache on your window, pls try to clean it up - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

**Comment by JoDeveloper** [comment]
```
flutter doctor                                                             
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.1, on Linux, locale en_US.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.45.1)
[✓] Connected device (1 available)

• No issues found!
```

the problem isn't in my flutter version it works very well !!

**Comment by kvt0012** [comment]
Please go to  Project folder > android > app > build.gradle, add the following Line in   
\<span class="pln" style="border:0px;box-sizing:inherit;color:var(--black-750);font-family:inherit;font-size:13px;font-stretch:inherit;font-style:inherit;font-variant:inherit;font-weight:inherit;line-height:inherit;margin:0px;padding:0px;vertical-align:baseline;">multiDexEnabled true\</span>

**Comment by kvt0012** [comment]
Please go to  Project folder > android > app > build.gradle, add the following Line in    
multiDexEnabled true

**Comment by kvt0012** [comment]
If it cannot solve, please follow this guide :   
https://medium.com/@carlosAmillan/fixing-androidx-error-in-flutter-f35e18d5925   
  
Thank you

**Comment by JoDeveloper** [comment]
@kvt0012  I've added ```multiDexEnabled true``` but still not working

Exception: The plugin cloud_firestore could not be built due to the issue above.
Exited (sigterm) 


and the link https://medium.com/@carlosAmillan/fixing-androidx-error-in-flutter-f35e18d5925  isn't working  :-(

**Comment by kvt0012** [comment]
Because as I see you have 2 errors here   
first is The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.   
Second is the exception: Exception: The plugin cloud\_firestore could not be built due to the issue above.  
Exited (sigterm)   
  
Check whether the first is solved, thank you

**Comment by JoDeveloper** [comment]
I've added  ``` multiDexEnabled true```  but still have the error 


```
import io.flutter.embedding.engine.plugins.lifecycle.FlutterLifecycleAdapter;
                                                    ^
  symbol:   class FlutterLifecycleAdapter
  location: package io.flutter.embedding.engine.plugins.lifecycle
/home/joe/flutter/.pub-cache/hosted/pub.dartlang.org/google_maps_flutter-0.5.26+4/android/src/main/java/io/flutter/plugins/googlemaps/GoogleMapsPlugin.java:78: error: cannot find symbol
    lifecycle = FlutterLifecycleAdapter.getActivityLifecycle(binding);
                ^
  symbol:   variable FlutterLifecycleAdapter
  location: class GoogleMapsPlugin
/home/joe/flutter/.pub-cache/hosted/pub.dartlang.org/google_maps_flutter-0.5.26+4/android/src/main/java/io/flutter/plugins/googlemaps/GoogleMapsPlugin.java:105: error: cannot find symbol
    lifecycle = FlutterLifecycleAdapter.getActivityLifecycle(binding);
                ^
  symbol:   variable FlutterLifecycleAdapter
  location: class GoogleMapsPlugin
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 errors
```

**Comment by kvt0012** [comment]
`Add this to pubspec.yaml :` **flutter\_plugin\_android\_lifecycle: ^1.0.7**   
**And run these command**   
`flutter channel stable`  
`flutter upgrade --force`  
`flutter pub cache repair`  
`flutter clean`   
  
Thank you

**Comment by JoDeveloper** [comment]
now it gives me this 
```

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'apple_sign_in'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Failed to ping owner of lock for artifact cache (/home/joe/.gradle/caches/modules-2) (lock id: -7741331821917979558, port: 40919)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

Exception: The plugin apple_sign_in could not be built due to the issue above.
```

**Comment by kvt0012** [comment]
https://docs.inspireui.com/fluxstore/sign-in/ 
The problem on apple sign in, please follow this guide, it will help you

**Comment by JoDeveloper** [comment]
## apple sign in problem solved but it gives me the first error again 
```
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin app_settings...
✓ Built build/app/outputs/repo.
Building plugin apple_sign_in...
✓ Built build/app/outputs/repo.
Building plugin cloud_firestore...
Exception: The plugin cloud_firestore could not be built due to the issue above.
Exited (sigterm)
```

**Comment by minhcasi** [comment]
@JoDeveloper - please help to try with the latest release `1.7.4` - thank you!
