### ISSUE TITLE
[MStore] Product Variation not working

### ISSUE THREAD

**Issue by GoGood1** [inspireui/support#322]
- Product: MStore
 - Your Purchased Code: d66a24b3-c52a-45e3-8ad2-9fd3e5580c13

**Describe the bug**
I have created variable products is WP and they show in the app, yet when a variation is selected, the price does not change. I have commeted out line 81 in src/containers/Detail/index.js and it has made no difference.

**Comment by luyx2412** [comment]
Hi @GoGood1 Can you provide your version Mstore?

Thanks

**Comment by GoGood1** [comment]
Hi - version 3.5.1 thanks

**Comment by GoGood1** [comment]
Hi, was asked to upload the config.js file - this is attached. Was also asked to upload the appconfig.json file but my version does not seem to have it. Thanks. 
[Config.txt](https://github.com/inspireui/support/files/2889857/Config.txt)

**Comment by luyx2412** [comment]
HI @GoGood1 Please update latest version MStore to fix your issue.

Thanks
