### ISSUE TITLE
Errror in failed assertion boolean expression must not null

### ISSUE THREAD

**Issue by sonubdu** [inspireui/support#3220]
after updating config file. run flutter command build successfully created and get the following error
Please check this issue and prode some solution.

![error](https://user-images.githubusercontent.com/4449291/82115065-42c47200-9780-11ea-9509-ca123ef853ae.png)

**Note:one more thing fluxbuilder pro also crash in my window system**

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building HomeLayout-[<'en'>](dirty, state: _HomeLayoutState#f9fd0):
Failed assertion: boolean expression must not be null

The relevant error-causing widget was: 
  HomeLayout-[<'en'>] file:///C:/roobau/lib/screens/home/home.dart:119:13
When the exception was thrown, this was the stack: 
#0      _HomeLayoutState.jsonWidget (package:fstore/widgets/home/index.dart:36:52)
#1      _HomeLayoutState.build (package:fstore/widgets/home/index.dart:149:11)
#2      StatefulElement.build (package:flutter/src/widgets/framework.dart:4619:28)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4502:15)
#4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
E/flutter ( 4050): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: FormatException: Unexpected character (at character 1)
E/flutter ( 4050): <!doctype html>
E/flutter ( 4050): ^
E/flutter ( 4050): 
E/flutter ( 4050): #0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1394:5)
E/flutter ( 4050): #1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1261:9)
E/flutter ( 4050): #2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:926:22)
E/flutter ( 4050): #3      _parseJson (dart:convert-patch/convert_patch.dart:31:10)
E/flutter ( 4050): #4      JsonDecoder.convert (dart:convert/json.dart:505:36)
E/flutter ( 4050): #5      JsonCodec.decode (dart:convert/json.dart:153:41)
E/flutter ( 4050): #6      jsonDecode (dart:convert/json.dart:96:10)
E/flutter ( 4050): #7      Blog.getBlogs (package:fstore/models/blogs/blog.dart:85:12)
E/flutter ( 4050): <asynchronous suspension>
E/flutter ( 4050): #8      BlogModel.getBlogs (package:fstore/models/blogs/blog.dart:20:29)
E/flutter ( 4050): #9      HomeScreenState.afterFirstLayout (package:fstore/screens/home/home.dart:97:52)
E/flutter ( 4050): #10     AfterLayoutMixin.initState.<anonymous closure> (package:after_layout/after_layout.dart:10:38)
E/flutter ( 4050): #11     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1113:15)
E/flutter ( 4050): #12     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1060:9)
E/flutter ( 4050): #13     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:968:5)
E/flutter ( 4050): #14     _rootRun (dart:async/zone.dart:1184:13)
E/flutter ( 4050): #15     _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter ( 4050): #16     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
E/flutter ( 4050): #17     _invoke (dart:ui/hooks.dart:261:10)
E/flutter ( 4050): #18     _drawFrame (dart:ui/hooks.dart:219:3)
E/flutter ( 4050):

**Comment by minhcasi** [comment]
@sonubdu 

Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by sonubdu** [comment]
detail shared.

**Comment by minhcasi** [comment]
@sonubdu - pls help to check the solution on this issue - https://github.com/inspireui/support/issues/3198 - thank you!
