### ISSUE TITLE
fluxnew.1.4.1 error in the config_ar.json file

### ISSUE THREAD

**Issue by haidarsalim** [inspireui/support#3221]
An error occurs when creating a new configuration file

![33](https://user-images.githubusercontent.com/54249914/82115329-d5f2ad00-976a-11ea-9233-146bacb93c45.PNG)
![222](https://user-images.githubusercontent.com/54249914/82115585-5c5bbe80-976c-11ea-818d-4941017de089.PNG)

------
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
√ Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...
I/OpenGLRenderer(16716): Davey! duration=725ms; Flags=1, IntendedVsync=28339936121603, Vsync=28339952788269, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=28339955795600, AnimationStart=28339955846600, PerformTraversalsStart=28339955891300, DrawStart=28340511174800, SyncQueued=28340522973700, SyncStart=28340527381500, IssueDrawCommandsStart=28340538736100, SwapBuffers=28340617452000, FrameCompleted=28340665828000, DequeueBufferDuration=19798000, QueueBufferDuration=904000, 
Debug service listening on ws://127.0.0.1:50369/osUPHTuQ8_0=/ws
Syncing files to device Android SDK built for x86...
I/Choreographer(16716): Skipped 44 frames!  The application may be doing too much work on its main thread.
I/cr_LibraryLoader(16716): Time to load native libraries: 129 ms (timestamps 675-804)
I/chromium(16716): [INFO:library_loader_hooks.cc(50)] Chromium logging enabled: level = 0, default verbosity = 0
I/cr_LibraryLoader(16716): Expected native library version number "74.0.3729.185", actual native library version number "74.0.3729.185"
W/cr_ChildProcLH(16716): Create a new ChildConnectionAllocator with package name = com.google.android.webview, sandboxed = true
W/inspireui.fnew(16716): Accessing hidden method Landroid/content/Context;->bindServiceAsUser(Landroid/content/Intent;Landroid/content/ServiceConnection;ILandroid/os/Handler;Landroid/os/UserHandle;)Z (greylist, reflection, allowed)
I/cr_BrowserStartup(16716): Initializing chromium process, singleProcess=false
I/inspireui.fnew(16716): Background young concurrent copying GC freed 32513(2339KB) AllocSpace objects, 14(568KB) LOS objects, 8% free, 6481KB/7122KB, paused 794us total 126.482ms
I/inspireui.fnew(16716): Background concurrent copying GC freed 31854(1687KB) AllocSpace objects, 5(260KB) LOS objects, 49% free, 5575KB/10MB, paused 1.057ms total 143.744ms
D/EGL_emulation(16716): eglMakeCurrent: 0xf287f460: ver 3 1 (tinfo 0xc7d798f0)
I/flutter (16716): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (16716): The following NoSuchMethodError was thrown building AppInit(dirty, state: _AppInitState#e87f5):
I/flutter (16716): The method '[]' was called on null.
I/flutter (16716): Receiver: null
I/flutter (16716): Tried calling: []("type")
I/flutter (16716): 
I/flutter (16716): The relevant error-causing widget was:
I/flutter (16716):   AppInit file:///C:/Users/haida/Desktop/source/lib/app.dart:105:23
I/flutter (16716): 
I/flutter (16716): When the exception was thrown, this was the stack:
I/flutter (16716): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
I/flutter (16716): #1      _AppInitState.build (package:fstore/app_init.dart:81:56)
I/flutter (16716): #2      StatefulElement.build (package:flutter/src/widgets/framework.dart:4619:28)
I/flutter (16716): #3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4502:15)
I/flutter (16716): #4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
I/flutter (16716): #5      Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
I/flutter (16716): #6      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4481:5)
I/flutter (16716): #7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4666:11)
I/flutter (16716): #8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
I/flutter (16716): ...     Normal element mounting (19 frames)
I/flutter (16716): #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
I/flutter (16716): #28     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5947:32)
I/flutter (16716): ...     Normal element mounting (185 frames)
I/flutter (16716): #213    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
I/flutter (16716): #214    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5947:32)
I/flutter (16716): ...     Normal element mounting (123 frames)
I/flutter (16716): #337    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
I/flutter (16716): #338    Element.updateChild (package:flutter/src/widgets/framework.dart:3211:20)
I/flutter (16716): #339    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
I/flutter (16716): #340    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
I/flutter (16716): #341    Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
I/flutter (16716): #342    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2627:33)
I/flutter (16716): #343    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:20)
I/flutter (16716): #344    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:284:5)
I/flutter (16716): #345    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1113:15)
I/flutter (16716): #346    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1052:9)
I/flutter (16716): #347    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:968:5)
I/flutter (16716): #351    _invoke (dart:ui/hooks.dart:261:10)
I/flutter (16716): #352    _drawFrame (dart:ui/hooks.dart:219:3)
I/flutter (16716): (elided 3 frames from dart:async)
I/flutter (16716): 
I/flutter (16716): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (16716): [AppState] Inital Data
I/flutter (16716): [AppState] Init Data Finish

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building AppInit(dirty, state: _AppInitState#e87f5):
The method '[]' was called on null.
Receiver: null
Tried calling: []("type")

The relevant error-causing widget was: 
  AppInit file:///C:/Users/haida/Desktop/source/lib/app.dart:105:23
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      _AppInitState.build (package:fstore/app_init.dart:81:56)
#2      StatefulElement.build (package:flutter/src/widgets/framework.dart:4619:28)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4502:15)
#4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
...

**Comment by minhcasi** [comment]
@haidarsalim - i'm sorry for replying late on this ticket.

As your purchase product is using Fluxnews, please try to use this option, instead of selecting the WooCommerce one (as the config will be a difference)

<img width="785" alt="Screen Shot 2020-05-23 at 14 25 28" src="https://user-images.githubusercontent.com/1459805/82724576-41a3bf80-9d01-11ea-8e61-cf4f66de21d8.png">

Also, help us to update the latest Fluxbuilder 1.0.5 as well 

Let us know your checking 😊

**Comment by haidarsalim** [comment]
I'm already using WordPress
I will try version 1.0.5 and tell you what happened

**Comment by haidarsalim** [comment]
The same error occurs even with the use of 1.0.5

![rrrr](https://user-images.githubusercontent.com/54249914/82727030-8b37de80-9cf0-11ea-8516-79f004b2bf87.PNG)

-----

Performing hot restart...
Syncing files to device Android SDK built for x86...
Restarted application in 2,860ms.
W/FA      (11693): setCurrentScreen cannot be called with the same class and name
I/flutter (11693): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (11693): The following NoSuchMethodError was thrown building AppInit(dirty, state: _AppInitState#cb8f0):
I/flutter (11693): The method '[]' was called on null.
I/flutter (11693): Receiver: null
I/flutter (11693): Tried calling: []("type")
I/flutter (11693): 
I/flutter (11693): The relevant error-causing widget was:
I/flutter (11693):   AppInit file:///C:/Users/haida/Desktop/fluxnew.1.4.1/source/lib/app.dart:105:23
I/flutter (11693): 
I/flutter (11693): When the exception was thrown, this was the stack:
I/flutter (11693): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
I/flutter (11693): #1      _AppInitState.build (package:fstore/app_init.dart:81:56)
I/flutter (11693): #2      StatefulElement.build (package:flutter/src/widgets/framework.dart:4619:28)
I/flutter (11693): #3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4502:15)
I/flutter (11693): #4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
I/flutter (11693): #5      Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
I/flutter (11693): #6      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4481:5)
I/flutter (11693): #7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4666:11)
I/flutter (11693): #8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
I/flutter (11693): ...     Normal element mounting (19 frames)
I/flutter (11693): #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
I/flutter (11693): #28     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5947:32)
I/flutter (11693): ...     Normal element mounting (185 frames)
I/flutter (11693): #213    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
I/flutter (11693): #214    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5947:32)
I/flutter (11693): ...     Normal element mounting (123 frames)
I/flutter (11693): #337    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
I/flutter (11693): #338    Element.updateChild (package:flutter/src/widgets/framework.dart:3211:20)
I/flutter (11693): #339    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
I/flutter (11693): #340    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
I/flutter (11693): #341    Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
I/flutter (11693): #342    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2627:33)
I/flutter (11693): #343    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:20)
I/flutter (11693): #344    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:284:5)
I/flutter (11693): #345    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1113:15)
I/flutter (11693): #346    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1052:9)
I/flutter (11693): #347    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:968:5)
I/flutter (11693): #351    _invoke (dart:ui/hooks.dart:261:10)
I/flutter (11693): #352    _drawFrame (dart:ui/hooks.dart:219:3)
I/flutter (11693): (elided 3 frames from dart:async)
I/flutter (11693): 
I/flutter (11693): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (11693): [AppState] Inital Data
I/flutter (11693): [AppState] Init Data Finish

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building AppInit(dirty, state: _AppInitState#cb8f0):
The method '[]' was called on null.
Receiver: null
Tried calling: []("type")

The relevant error-causing widget was: 
  AppInit file:///C:/Users/haida/Desktop/fluxnew.1.4.1/source/lib/app.dart:105:23
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      _AppInitState.build (package:fstore/app_init.dart:81:56)
#2      StatefulElement.build (package:flutter/src/widgets/framework.dart:4619:28)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4502:15)
#4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by minhcasi** [comment]
@haidarsalim - thank you for quick response -  could you share your website URL - we will for investigating, this could be the issue with the latest 1.4.1

**Comment by haidarsalim** [comment]
Actually I am using 1.4.1
https://baytaltatbiqat.com/

**Comment by minhcasi** [comment]
@haidarsalim - pls help to use the config file as an attachment, there is the issue with the Fluxbuilder that not up-to-date with the latest build, we will fix it shortly 

There is missing config from the config json
```
  "SplashScreen": {
    "type": "zoomIn",
    "data" : "assets/images/splashscreen.png"
  },
```

[config_en.json.txt](https://github.com/inspireui/support/files/4673411/config_en.json.txt)

**Comment by minhcasi** [comment]
Hi @haidarsalim - please keep update on this ticket :)

**Comment by haidarsalim** [comment]
The problem has been resolved

**Comment by haidarsalim** [comment]
How to disable a welcome message
![qqq](https://user-images.githubusercontent.com/54249914/82852101-96665680-9f0a-11ea-9ecd-8ec3695219a3.PNG)

**Comment by haidarsalim** [comment]
When using list configuration file it does not appear to me
![22](https://user-images.githubusercontent.com/54249914/82852158-c7df2200-9f0a-11ea-8ea4-e0ec786ba49b.PNG)

**Comment by minhcasi** [comment]
@dttrung26 - pls help to investigate this issue - thank you!

**Comment by dttrung26** [comment]
Hi @haidarsalim , 
There is a vertical layout FluxNews bug in FluxBuilder current version and it will be fixed in the next patch. In the meantime, FluxNews could still display vertical layout by itself fine. Please add these lines at the same level as "HorizonLayout", "Settings", "TabBar" in order to make it work: 
``` 
  "VerticalLayout":{
    "name":"Explore more",
    "layout":"list"
  },
``` 
Hope this helps!

**Comment by haidarsalim** [comment]
> Hi @haidarsalim ,
> There is a vertical layout FluxNews bug in FluxBuilder current version and it will be fixed in the next patch. In the meantime, FluxNews could still display vertical layout by itself fine. Please add these lines at the same level as "HorizonLayout", "Settings", "TabBar" in order to make it work:
> 
> ```
>   "VerticalLayout":{
>     "name":"Explore more",
>     "layout":"list"
>   },
> ```
> 
> Hope this helps!

**Can you add it to me, I can't**
[config_en.zip](https://github.com/inspireui/support/files/4707720/config_en.zip)

**Comment by dttrung26** [comment]
Hi @haidarsalim , 
please my file modified config to see if it works. Hope this helps!
[config_en.zip](https://github.com/inspireui/support/files/4722170/config_en.zip)

**Comment by haidarsalim** [comment]
> Hi @haidarsalim ,
> please my file modified config to see if it works. Hope this helps!
> [config_en.zip](https://github.com/inspireui/support/files/4722170/config_en.zip)
---

How do I choose a specific category to display category&tag_ID=43
---
**How to activate an infinite download**

![444](https://user-images.githubusercontent.com/54249914/83956050-52584780-a862-11ea-9510-cda41c40e9b8.PNG)
