### ISSUE TITLE
Fluxstore Paypal configuration 

### ISSUE THREAD

**Issue by Lucatezuma** [inspireui/support#3222]
Hi, Paypal configuration
What's the problem?

Attached screenshots and common zip file

Thanks

![Schermata 2020-05-12 alle 13 51 40](https://user-images.githubusercontent.com/47059435/82116148-ca51b700-9767-11ea-9ec6-0e7faa009006.png)

[common.zip](https://github.com/inspireui/support/files/4638120/common.zip)

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as it could not be verified, please create the new one when you got enough purchased info - thank you!
