### ISSUE TITLE
BUILD FAILED!

### ISSUE THREAD

**Issue by jajamoks** [inspireui/support#3225]
> Task :app:compileDebugJavaWithJavac FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.5/userguide/command_line_interface.html#sec:command_line_warnings
186 actionable tasks: 3 executed, 183 up-to-date
C:\Users\Jajamoks\Desktop\BACKUP\REACT NATIVE\mstore-3.9.8\mstore-pro\android\app\build\generated\rncli\src\main\java\com\facebook\react\PackageList.java:23: error: package io.invertase.firebase.auth does not exist
import io.invertase.firebase.auth.ReactNativeFirebaseAuthPackage;
                                 ^
C:\Users\Jajamoks\Desktop\BACKUP\REACT NATIVE\mstore-3.9.8\mstore-pro\android\app\build\generated\rncli\src\main\java\com\facebook\react\PackageList.java:99: error: cannot find symbol
      new ReactNativeFirebaseAuthPackage(),
          ^
  symbol:   class ReactNativeFirebaseAuthPackage
  location: class PackageList
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 24s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
C:\Users\Jajamoks\Desktop\BACKUP\REACT NATIVE\mstore-3.9.8\mstore-pro\android\app\build\generated\rncli\src\main\java\com\facebook\react\PackageList.java:23: error: package io.invertase.firebase.auth does not exist
import io.invertase.firebase.auth.ReactNativeFirebaseAuthPackage;
                                 ^
C:\Users\Jajamoks\Desktop\BACKUP\REACT NATIVE\mstore-3.9.8\mstore-pro\android\app\build\generated\rncli\src\main\java\com\facebook\react\PackageList.java:99: error: cannot find symbol
      new ReactNativeFirebaseAuthPackage(),
          ^
  symbol:   class ReactNativeFirebaseAuthPackage
  location: class PackageList
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 24s

    at makeError (C:\Users\Jajamoks\Desktop\BACKUP\REACT NATIVE\mstore-3.9.8\mstore-pro\node_modules\execa\index.js:174:9)
    at C:\Users\Jajamoks\Desktop\BACKUP\REACT NATIVE\mstore-3.9.8\mstore-pro\node_modules\execa\index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async runOnAllDevices (C:\Users\Jajamoks\Desktop\BACKUP\REACT NATIVE\mstore-3.9.8\mstore-pro\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:94:5)
    at async Command.handleAction (C:\Users\Jajamoks\Desktop\BACKUP\REACT NATIVE\mstore-3.9.8\mstore-pro\node_modules\react-native\node_modules\@react-native-community\cli\build\index.js:186:9)

![image](https://user-images.githubusercontent.com/24262635/82120602-30284980-973c-11ea-8882-62995abc4dfa.png)

**Comment by minhcasi** [comment]
@jajamoks 

Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as it could not be verified, please create the new one when you got enough purchased info - thank you!
