### ISSUE TITLE
[Fluxstore MV] Homepage not loading properly if IsRequiredLogin is set to True.

### ISSUE THREAD

**Issue by jinuem** [inspireui/support#3227]
Step 1 (require): detail issues and screenshots
VERSION: 1.7.3 / Flutter: 1.17
The app works fine if **IsRequiredLogini is false.**
Even I can able to log in while checkout and logout.

But when I turn **"IsRequiredLogin to true"**
I can see the login screen, once I log in. Home page not loading properly.

![Screenshot 2020-05-16 20 02 48](https://user-images.githubusercontent.com/3512723/82122318-8afb8880-97b0-11ea-849d-666edf24ca2b.png)

If you want to look into my code. I can give access to my repo.
https://github.com/jinuem/CameronMarket/tree/1.7.3 (1.7.3 branch)
Already @minhtruong315 have access to my repo.

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)
SUBMITTED

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by jinuem** [comment]
@minhcasi @minhtruong315  Any update?

**Comment by minhcasi** [comment]
@minhtruong315 - pls keep an update

**Comment by minhtruong315** [comment]
Hi @jinuem Can you try this solution
- replace file screens/users/login.dart
[login.dart.zip](https://github.com/inspireui/support/files/4654246/login.dart.zip)
- replace function onNextScreen in lib/app_init.dart like this
```
  Widget onNextScreen() {
    if (!isFirstSeen && !kIsWeb) {
      if (onBoardingData.isNotEmpty) return OnBoardScreen(appConfig);
    }

    if (kLoginSetting['IsRequiredLogin'] && !isLoggedIn) {
      return LoginScreen(
        onLoginSuccess: (context) async {
          await Navigator.pushNamed(context, RouteList.home);
        },
      );
    }
    return widget.onNext(appConfig);
  }
```

**Comment by jinuem** [comment]
I am moving the issue from ticket #3302 here to keep everything in one open ticket as per @minhcasi.

ISSUE 2:
Build Working fine on iOS. but its failing for Android.
Tried Cleaning the Flutter Clean also Gradlew clean. nothing works.

Version : 1.7.3
Flutter: 1.17.1 Latest
Dart 2.8.2

Error Log:

> 
> (base) vincent@Vincents-MacBook-Pro CameronMarket (quote) $ flutter run
> Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts,
> consider enabling software rendering with "--enable-software-rendering".
> Launching lib/main.dart on Android SDK built for x86 in debug mode...
> Note: Some input files use or override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: /Library/Flutter/.pub-cache/hosted/pub.dartlang.org/firebase_admob-0.9.3+2/android/src/main/java/io/flutter/plugins/firebaseadmob/AdRequestBuilderFactory.java uses or overrides a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: /Library/Flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.13.4/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java uses unchecked or unsafe operations.
> Note: Recompile with -Xlint:unchecked for details.
> Note: Some input files use or override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: Some input files use unchecked or unsafe operations.
> Note: Recompile with -Xlint:unchecked for details.
> Note: Some input files use unchecked or unsafe operations.
> Note: Recompile with -Xlint:unchecked for details.
> Note: /Library/Flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.5/android/src/main/java/io/flutter/plugins/pathprovider/PathProviderPlugin.java uses or overrides a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: /Library/Flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.4.5/android/src/main/java/io/flutter/plugins/urllauncher/WebViewActivity.java uses or overrides a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: Some input files use or override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: /Library/Flutter/.pub-cache/hosted/pub.dartlang.org/video_player-0.10.9+1/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayerPlugin.java uses or overrides a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> e: /Users/vincent/Workspace/HAIL/cameron-1.7.0/CameronMarket/android/app/src/main/kotlin/com/inspireui/fluxstore/MainActivity.kt: (8, 7): Redeclaration: MainActivity
> e: /Users/vincent/Workspace/HAIL/cameron-1.7.0/CameronMarket/android/app/src/main/kotlin/com/inspireui/fluxstore/vendor/MainActivity.kt: (7, 7): Redeclaration: MainActivity
> 
> FAILURE: Build failed with an exception.
> 
> What went wrong:
> Execution failed for task ':app:compileDebugKotlin'.
> Compilation error. See log for more details
> 
> Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> Get more help at https://help.gradle.org
> 
> BUILD FAILED in 53s
> Running Gradle task 'assembleDebug'...
> Running Gradle task 'assembleDebug'... Done 54.4s
> Exception: Gradle task assembleDebug failed with exit code 1

**Comment by jinuem** [comment]
PROBLEM 1 (Login- IsRequiredLogin) : 
@minhtruong315 Incorporated "**onNextScreen**" function and **Login.dart** file which you gave throwing following errors while building.

>  Launching lib/main.dart on iPhone SE (2nd generation) in debug mode...
> 
> Compiler message:
> lib/screens/users/login.dart:142:9: Error: No named parameter with the name 'context'.
>         context: context);
>         ^^^^^^^
> lib/screens/users/login.dart:156:9: Error: No named parameter with the name 'context'.
>         context: context);
>         ^^^^^^^
> lib/screens/users/login.dart:254:11: Error: No named parameter with the name 'context'.
>           context: context);
>           ^^^^^^^
> Xcode build done.                                           140.7s
> Failed to build iOS app
> Error output from Xcode build:
> ↳
>     ** BUILD FAILED **
> Xcode's output:

<img width="716" alt="Screenshot 2020-05-20 at 3 31 02 PM" src="https://user-images.githubusercontent.com/3512723/82433340-ec706f80-9aae-11ea-8778-5a1dcb36a12c.png">

**Comment by jinuem** [comment]
**ISSUE 3:**
Cart page Login Modal not working properly.
Steps:
1. Guest User adds the product to the cart.
2. Go to cart (not modal, use cart icon in the bottom)
3. Click checkout.
4. Login Form opens
5. Enter login details and get Login Success.
6. Click the checkout button again. it will open the login modal again.
If I go to settings and I can see logged in username details and coming back to the cart page. Now Checkout buttons work perfectly and redirecting to the checkout page.

Video: https://www.dropbox.com/t/MuGi3rxbyr4CqryI

**Comment by minhtruong315** [comment]
Hi @jinuem can u upload your source  code to github then invite me: minhtruong315@gmail.com
I will help you check and update on your source code.
Thanks

**Comment by jinuem** [comment]
> Hi @jinuem can u upload your source code to github then invite me: [minhtruong315@gmail.com](mailto:minhtruong315@gmail.com)
> I will help you check and update on your source code.
> Thanks

In the first comment itself, I told. You have permission to my repo. :( 
https://github.com/jinuem/CameronMarket/tree/1.7.3
**(BRANCH: 1.7.3)**

**Comment by minhtruong315** [comment]
Hi @jinuem I fixed your issues. pls pull updates and check again

**Comment by jinuem** [comment]
Thanks alot @minhtruong315 
All Three Issues Fixed.
