### ISSUE TITLE
#3181

### ISSUE THREAD

**Issue by amitw7786** [inspireui/support#3228]
**1)**	As you suggested for removing ”Order Cancel” Button, I did same thing for “Refund” Button but it is still appearing ..
I deleted code of Cancel Order as well as code of Refund too but it is not removed, How can I remove “Refund” Button also..
![removed refund](https://user-images.githubusercontent.com/64218485/82124854-7a064380-97bf-11ea-905a-6b32e9d46e6d.png)
![Refund still there](https://user-images.githubusercontent.com/64218485/82124862-84c0d880-97bf-11ea-8756-f95e8b71188c.jpg)

**2)**	My config_en.json contains
"VerticalLayout": {
 	"layout": "menu",
"name": "Shop by Categories"
},

It is now showing Add to Cart button but It is not showing All products of selected category, It is showing only 20 products when category contains 36 products.
![shows 20 products](https://user-images.githubusercontent.com/64218485/82124885-b46fe080-97bf-11ea-83ca-378e41edef1f.jpg)

**3)**	When I use filter, and select any category then after getting into that category , category name is not changing, it is showing previous category name.
![filter](https://user-images.githubusercontent.com/64218485/82124914-fdc03000-97bf-11ea-9fea-75af1cc3dbc7.jpeg)
![category name dosent change when we use filters ](https://user-images.githubusercontent.com/64218485/82124921-07e22e80-97c0-11ea-8ea3-4f23c8840ecf.jpeg)

**4)**       At the address page, I don’t need country and State, I want to rename country as flat No and make this editable (Now country can’t be edited) and want to rename state as “Community” and add some predefined name of area groups in its drop-down instead of states.. Please tell me how can I do this..
![change country and city](https://user-images.githubusercontent.com/64218485/82127402-dde53800-97d0-11ea-9a9c-6586925cc198.jpg)

**5)**       At the checkout page, Address searching button when I try to search address by entering in text field I get the following error
"You have exceeded your daily request quota for this API, If you did not set a custom daily request quota, verify your project has an active billing account :"
Please tell me how to force this location service to work for just Bangalore (Bangalore, Karnataka, India) city only and
tell me how can I disable this Search address button also ..
![api error](https://user-images.githubusercontent.com/64218485/82127253-b477dc80-97cf-11ea-9010-d1a4d639d9b8.jpg)

**6)**	If I use “See All” button and click on it, it displays a blank category named as “See All” , How to remove this “See All” category blank page
![see all](https://user-images.githubusercontent.com/64218485/82124965-5db6d680-97c0-11ea-8d53-4c83b673fdb5.jpg)
![See All No products](https://user-images.githubusercontent.com/64218485/82124970-6dceb600-97c0-11ea-95bd-bfe44e7268dc.jpeg)

**Comment by minhcasi** [comment]
@amitw7786 - pls continue your conversion on this ticket and move to #3181 - thank you!
