### ISSUE TITLE
Don't see push notification on IOS

### ISSUE THREAD

**Issue by iamglicious** [inspireui/support#3229]
When I sent a push notification to IOS I only see it in the store and not in the on the phone it self. 
I have checked all the settings and even on different phones.

Also at the zipcode its only possible to type in number but in the Netherlands we also have letters in our zipcode.  I filled in the form many times for other issues I openend. Hope somebody knows how to solve. And maybe its an idea to put it in wiii so we can see the different solutions for people with the same problem.

**Comment by minhcasi** [comment]
@iamglicious - please check this detailed guide https://medium.com/@inspireui/setup-firebase-cloud-messaging-fcm-push-notification-for-flutter-apps-8c767fe64e54

**Comment by iamglicious** [comment]
Thank you Im receiving the message on the iphone but only in the store.Im not receiving the messages in the overall IOS.
![Simulator Screen Shot - iPhone 11 Pro - 2020-05-17 at 11 44 58](https://user-images.githubusercontent.com/15807007/82141093-e28f0800-9833-11ea-8032-475721a80c07.png)

**Comment by minhcasi** [comment]
Did you subscribe to ios Developer Account? This feature only support when you paid their account - thank you!

**Comment by iamglicious** [comment]
Yes I have an developer account and also running in testflight. But same situation.

**Comment by iamglicious** [comment]
Also the zipcode problem is still active. I only can type in number instead of numbers and letters.

**Comment by minhcasi** [comment]
Pls make sure to test the push notify on ios via the real device as it will not work well on the simulator. Also, try double-check our medium blog for the set up.

We have noted the zip code issue and upgrade it latest - thank you!

**Comment by iamglicious** [comment]
Hi Minhcasi,

I have test it on a real device because im testing thru testflight and have double checked the medium blog setup

**Comment by minhcasi** [comment]
@trunghieuvn - do you have any recommendations on this issue?

**Comment by trunghieuvn** [comment]
@iamglicious  i have write tutorial step  by step: [https://medium.com/@inspireui/setup-firebase-cloud-messaging-fcm-push-notification-for-flutter-apps-8c767fe64e54](https://medium.com/@inspireui/setup-firebase-cloud-messaging-fcm-push-notification-for-flutter-apps-8c767fe64e54)  
and demo in video, please check in doc and view video.   
i think you have missing any step :D

**Comment by iamglicious** [comment]
Will check everything again today and will get back

**Comment by iamglicious** [comment]
Now the following I have done. I have created a new APN certificate and uploaded in Firebase. Im receiving the messages now in my home screen but missing in my app.

The only change I made is the key specific for Push Notifications and not for apple sign in.
I tested it on the original testflight. So no code changed only the certificate in my developer account.

**Comment by minhcasi** [comment]
@iamglicious - could you clarify more what you you mean "missing in my app" ? Does it not display on the Setting screen?

**Comment by minhcasi** [comment]
'm sorry to close this ticket as there is no response, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Comment by iamglicious** [comment]
I will check I was free yesterday. Will recheck everything and will open a new ticket @minhcasi
