### ISSUE TITLE
Fluxstore MultiVendor Google Signin Not working

### ISSUE THREAD

**Issue by inspireuis** [inspireui/support#3230]
Step 1 (require): detail issues and screenshots
I am trying to integrate social logins and normal email login. Have followed the documentation and the app is creating the account on firebase but the app gets stuck at the login screen as shown in the below screenshot. During the debuging of the code I found that 

await Firestore.instance
          .collection('users')
          .document(user.email)
          .setData({'deviceToken': token, "isOnline": true}, merge: true);

this line is not returning anything and code get's stuck here. Please help me resolve the issue to enable the login and signup.

![WhatsApp Image 2020-05-16 at 11 02 00 PM](https://user-images.githubusercontent.com/65219388/82126271-55af6480-97c9-11ea-95cb-549bf75dae67.jpeg)

/----------------------------------------------------------------------------------------/
Good day support team,

There are some pages that the app calls from the webview, like the next one:

At the payment gateway, it calls the checkout page, for us ( https://gurutos.com/checkout-2/ )

How its the best way to make the changes? from the app theme? from the webview? cloning the webview page?

The idea its that it looks the same all the app, as the webview dont have the same colors and buttons.

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@trunghieuvn - pls check this issue, thank you!

**Comment by trunghieuvn** [comment]
Hi @inspireuis  
Please add me to your gitub/gitlab repo project, I will check the problem and help you quickly handle it.

Email my github/gitlab: hieu.trantrung1204@gmail.com

**Comment by minhcasi** [comment]
@inspireuis - could you update on this ticket?

**Comment by engbasselayman** [comment]
@trunghieuvn 
Kindly i add you to my git lab project i have the same issue of loading without log or register.
this my user name on git lab (@engbasselayman ) the project name is sonik store

**Comment by inspireuis** [comment]
> hieu.trantrung1204@gmail.com

we have given you the permission of our github account so please check the issue.

**Comment by trunghieuvn** [comment]
I have tested your project, I don't see any login issues. I can log in normally. What is the device information you are checking?

I am checking on real device. Because login google can run on the virtual machine, but login with SMS, there is an error.


![video (1)](https://user-images.githubusercontent.com/19247680/82644344-5e75bf80-9c3b-11ea-806d-c8f203f12372.gif)

**Comment by inspireuis** [comment]
Good Day Inspireui, 

Thanks for your assistance in this case, Ticket solve.

Thanks and Regards,
