### ISSUE TITLE
Change Payment Gateways

### ISSUE THREAD

**Issue by hackzie** [inspireui/support#3231]
Is there any possible way to add paytm and PayU money payment gateways in flux store woocommerce app?

**Comment by minhcasi** [comment]
Hi, it's possible to support these payments, it will work as the same on your Website, for more information please check - https://docs.inspireui.com/fluxstore/multi-payment/

**Comment by hackzie** [comment]
Hi, I have purchased the fluxstore woocommerce app today. I have got a
license key. I have a simple question-

I want to test the app on a test website. So, i will use my license key
there only for few days. After that, I will remove the license key from the
test site. And then i will use it on live site. So, I can i do this? Or my
license key will be useless after using and removing it in one site.

I hope this wont go against your license policy.

Thank you
