### ISSUE TITLE
Home Screen Not Showing when Changing Language

### ISSUE THREAD

**Issue by ahmadali86** [inspireui/support#3232]
Step 1 (require): detail issues and screenshots
When I change the language of the app to arabic or any other language I receive the following errors:
`The following assertion was thrown building HomeLayout-[<'ar'>](dirty, state: _HomeLayoutState#fb005):
Failed assertion: boolean expression must not be null

The relevant error-causing widget was: 
  HomeLayout-[<'ar'>] file:///Users/ahmed/Downloads/untitled%20folder/source/lib/screens/home/home.dart:119:13
When the exception was thrown, this was the stack: 
#0      _HomeLayoutState.jsonWidget (package:fstore/widgets/home/index.dart:36:52)
#1      _HomeLayoutState.build (package:fstore/widgets/home/index.dart:149:11)
#2      StatefulElement.build (package:flutter/src/widgets/framework.dart:4623:28)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4506:15)
#4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4679:11)
...`

and the screen turns blue and show this message on Home screen:
Error Failed assertion: boolean expression must not be null

<img width="377" alt="Screen Shot 2020-05-16 at 9 50 58 PM" src="https://user-images.githubusercontent.com/60041105/82129149-fc433780-97c0-11ea-901c-311a9687986c.png">

**Comment by bigbossmaher** [comment]
same issue , even i tested on a fresh copy

**Comment by alvillegas** [comment]
The same happens to me when selecting the Spanish language "es", I wait for the solution

**Comment by minhcasi** [comment]
@ahmadali86 - this is fixed on the latest code - we will release new version 1.7.4 in 1-2 days - thank you!

In the meantime, you could use this config files 
[Archive.zip](https://github.com/inspireui/support/files/4639645/Archive.zip)

**Comment by ahmadali86** [comment]
Thank you it works now

**Comment by minhcasi** [comment]
We're glad that it help, please give us some feedback/rating to this page https://codecanyon.net/downloads  if the product is helpful for your business, we are working hard to update more awesome and powerful features on next coming version release. Let us know if you have any feedback. Thank you very much 😊
