### ISSUE TITLE
just 1 category show in page

### ISSUE THREAD

**Issue by badral3nzi** [inspireui/support#3233]
just 1 category show in page : “layout”: “category”, “categoryLayout”: “card”,

q1: how can i show all category . ( screenshot q3 and 2 )

q2 : how can customisations the category, like : font , color , size of image... etc . which file control this ? ( screenshot q3 and 2 )

q3 : the welcome screen , how can i change it .. which file control this ? ( screenshot q3 )

q4 : i config splash screen to : const kSplashScreen = "assets/images/splashscreen.png";  and showing white page when app run ?? ( screenshot q4 )

q5 : how can i put logo in header ? ( screenshot q5 )

note-1 : i have 2 category in website
note-2 : i have last version of : app and flutter .

![q1 and 2](https://user-images.githubusercontent.com/65447371/82130054-9ced2380-97d0-11ea-9590-f1ce9b01f36c.png)
![q4](https://user-images.githubusercontent.com/65447371/82130058-9f4f7d80-97d0-11ea-9811-cb8454ecd51a.png)
![q5](https://user-images.githubusercontent.com/65447371/82130060-a080aa80-97d0-11ea-95d8-87ee50309f21.png)
![q3](https://user-images.githubusercontent.com/65447371/82130062-a1194100-97d0-11ea-9f32-dbd354497c68.png)

**Comment by badral3nzi** [comment]
note : q4 splash screen is work now ... but how can i change background to another color .. not white ...?

**Comment by kvt0012** [comment]
I can't see your screenshot, please send to me again, thank you   
Q1,Q2 : Please config it on common folder, sir. About show more category, please go to file config.dart, about color,size, please go to style.dart   
All of it here.   
And other I will wait for your screenshot, thank you

**Comment by badral3nzi** [comment]
screenshot is here 
https://www.up-00.com/ysqzzmlko8eb
https://www.up-00.com/k264zy0by52j
https://www.up-00.com/dju2wgs8bjvk
https://www.up-00.com/7jevl7hpp0d2

**Comment by badral3nzi** [comment]
any update .?

**Comment by badral3nzi** [comment]
> sir. About show more category, please go to file config.dart,

can u show me what code can i change to show all category ? because i'm not see anything to control category in config.dart ...???

**Comment by badral3nzi** [comment]
my app is waiting ?? 2 day no update ??

**Comment by Haniel5** [comment]
Hi, to change the design of app, you can use FluxBuilder tool for free. Please refer this video to see how it works https://youtu.be/Dfv2eNFadQs
This is the guide: https://docs.inspireui.com/fluxbuilder/download-install/

Best regards

**Comment by badral3nzi** [comment]
my friend, this is not solution !!
PLZ give me 1 solution to fix ( show all category in app) just 1 solution ???/?????

i'm see all your ( website + youtube channel + Fluxbuilder pro ... etc )

**Comment by minhcasi** [comment]
@vumanhsn97 - pls help suggest on this issue - thank you!

**Comment by vumanhsn97** [comment]
**1-Category not show**: You can check in lib/services/woo_commerce.dart. In getCategoriesByPage function, update this code
![image](https://user-images.githubusercontent.com/39208623/82772889-c9f1a400-9e6a-11ea-8ae5-63531e6c8629.png)
If it is not working, please share your common.zip to vumanhsn97@gmail.com. Your common.zip in your form submit is mstore.io site. So I can't check
**2-Edit category**: You can edit in lib/screens/categories/card.dart. In CategoryCardItem class: 
![image](https://user-images.githubusercontent.com/39208623/82773289-db877b80-9e6b-11ea-92ba-090f84783c5d.png)
**3-Welcome screen**: You can edit in common/config/onboarding.dart: 
![image](https://user-images.githubusercontent.com/39208623/82773378-138ebe80-9e6c-11ea-8ae9-f10a7fdc56e1.png)
**4-Splashscreen**: Any update? I don't understand. If you use splashscreen with type image, it will load with image background
**5-Logo Header**: Update in your config.json file: 
![image](https://user-images.githubusercontent.com/39208623/82773805-29e94a00-9e6d-11ea-912f-364ffcaaa4df.png)

**Comment by badral3nzi** [comment]
BIG thanx to your professional replay .

but just a category not solved yet , i send u common.folder : vumanhsn97@gmail.com

**Comment by vumanhsn97** [comment]
@badral3nzi Some category have parent id = 15 but Category with id = 15 not exist 
![image](https://user-images.githubusercontent.com/39208623/82974545-6dc28780-a004-11ea-9f50-cfa5f66efb40.png)
. So 2 solutions:
1 - cheat in fluxstore app: in lib/models/category/category.dart, change this code 
![image](https://user-images.githubusercontent.com/39208623/82974639-a4989d80-a004-11ea-9d3e-049d5e119650.png). 
![image](https://user-images.githubusercontent.com/39208623/82974667-b37f5000-a004-11ea-8541-3b8df6ec5147.png)
2 - check in wordpress site and match correct parent category

**Comment by badral3nzi** [comment]
i want try this solution but i update Android studio and have error : 

Controller's length property (4) does not match the number of tabs (5) present in TabBar's tabs property.

??

**Comment by vumanhsn97** [comment]
Do you edit in lib/tabbar.dart file?

**Comment by badral3nzi** [comment]
I think I did not make any changes to the file tabbar.dart before !!
 
i Was deleted :
 

> "layout": "category",
>   "icon": "assets/icons/tabs/icon-category.png"
> from file config_ar.json : "TabBar": [ ]  ,

 before, When i put him back , the error hidden.
but the problem now : old config .json file return ??
in photo no.1 old config . json 
in photo no.2  u can see new error in tabbar.dart in red line ???

![no1](https://user-images.githubusercontent.com/65447371/83707240-38302680-a622-11ea-83b8-d9734620973d.png)

![no2](https://user-images.githubusercontent.com/65447371/83707253-3cf4da80-a622-11ea-9f63-6a32ca5e45f2.png)

**Comment by vumanhsn97** [comment]
Nope! This red line is not bug. This come from your computer. It will be disappear when you reopen
