### ISSUE TITLE
Urgent Question For Fluxstore Woocommerce App

### ISSUE THREAD

**Issue by hackzie** [inspireui/support#3234]
Hi, I have purchased the fluxstore woocommerce app today. I have got a license key. I have a simple question-

I want to test the app on a test website. So, i will use my license key there only for few days. After that, I will remove the license key from the test site. And then i will use it on live site. So, I can i do this? Or my license key will be useless after using and removing it in one site.

I hope this wont go against your license policy.

Thank you

**Comment by hackzie** [comment]
I just want to ask that, can we remove our license key from one site and reuse it to connect to other site?

**Comment by minhcasi** [comment]
@hackzie - Yes, you could Reset your license key to switch from Testing to Product website config, there is the Reset Purchase code feature when you install the Fluxbuilder app - http://fluxbuilder.com

**Comment by hackzie** [comment]
I need to purchase 5 more license keys, Is there any discount offer available sir?

**Comment by minhcasi** [comment]
@hackzie - if you could purchase a bunch 5 products in a day, we could discount 20% - as there is no discount feature from Envato, we will set it as Flash Sale in 1 day - thank you!

Let us know if you have any questions.

**Comment by minhcasi** [comment]
@hackzie - pls contact us via email to get next coming sale update - support@inspireui.com - thank you!
