### ISSUE TITLE
Can't login to Fluxstore Shopify

### ISSUE THREAD

**Issue by IAPCorporate** [inspireui/support#3235]
Step 1 (require): detail issues and screenshots
I can't login to my Shopify store. I can list all my products, collections, etc but when I try to login it gives the following error. 

flutter: ::::request login
flutter: ::::request createAccessToken
flutter: result {customerAccessTokenCreate: {userErrors: [{field: null, message: Unidentified customer}], customerAccessToken: null}}
flutter: ::::createAccessToken shopify error
flutter: NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: []("accessToken")
flutter: ::::login shopify error
flutter: NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: []("accessToken")

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)
Submitted.

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by jberman280** [comment]
I have the same issue as well. everything works well. but cannot change privacy policy and login not working

**Comment by luyx2412** [comment]
Hi @IAPCorporate Can you send me your config.dart file? Let me investigate about it.

Thanks

**Comment by IAPCorporate** [comment]
Never mind. I fixed it. It was a problem on the login screen with password validation. If someone puts a wrong password; they see that error. I changed it to a static message.

**Comment by luyx2412** [comment]
Hi @IAPCorporate Thanks for your effort. Closed this issue.

**Comment by kwsystems** [comment]
@jberman280 Quick question, how did you change your privacy policy?
