### ISSUE TITLE
Currency does not work very well !!

### ISSUE THREAD

**Issue by obaidh** [inspireui/support#3236]
fluxstore App

Step 1 (require): detail issues and screenshots
currency does not work very well you can check gif 

![step 01](https://user-images.githubusercontent.com/10709888/82139707-f9852880-983a-11ea-886f-98bbdce82ac2.jpg)

![step2](https://user-images.githubusercontent.com/10709888/82139718-06a21780-983b-11ea-9fe6-88e8f201f2fc.jpg)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)
done

**Comment by kvt0012** [comment]
Please give me more detail about your issue, sir. Thank you

**Comment by obaidh** [comment]
my backend its WordPress and I use WPML for the multi-language store I have 2 currency USD and AED, the issue is the APP show on Home Screen price symbol its AED but amount its USD.
on the category, list amounts its AED but when go details products get amount its USD but symbol its AED, summery the app confused with multi-currency some time give me the amount AED with correct symbol some time the amount USD with AED symbol.

check out some time USD some time AED with USD amount

**Comment by kvt0012** [comment]
Dear sir, we don't add the function to change the amount of currency because it changes daily, so if you want to change it, please make sure that your api support to this, thank you

**Comment by obaidh** [comment]
my friend my issue not about change the currency, 
I'm select AED to be default currency to my app, but the app shows me some time USD amount with AED symbol.
I mean 
the default symbol its AED but amount change between the screen between USD and AED with keeping it a symbol  AED.

if you see photo above on category screen the amount and symbol correct but single product screen the amount change to USD but keep it symbol AED without change

**Comment by kvt0012** [comment]
Dear sir, now we just support on default with 3 kinds of currencies.   
Please check it on file advance.dart on common/config folder. Thank you 

![](https://user-images.githubusercontent.com/49152325/82205247-7940ef00-9930-11ea-9def-010de9d4499e.png)

**Comment by obaidh** [comment]
any plan to support or help me to add  AED

**Comment by kvt0012** [comment]
You can follow this guide   
https://docs.inspireui.com/fluxstore/customization/#9-product-advance-options   
You can add by yourself, sir, go to common/config folder and add it.   
About plan to support AED currency we've still not yet on this time, sir. Sorry for this inconvenience.

**Comment by kvt0012** [comment]
You can follow this guide   
https://docs.inspireui.com/fluxstore/customization/#9-product-advance-options   
You can add by yourself, sir, go to common/config folder and add it.   
About plan to support AED currency we've still not yet on this time, sir. Sorry for this inconvenience.
