### ISSUE TITLE
No Shipping options are available

### ISSUE THREAD

**Issue by ahmadali86** [inspireui/support#3237]
When I finish the order and proceed to shipping details it gives me this error although I use the same details of shipping and Geo Zone in the website and it works , here is what I get:
Exception: No Shipping options are available

and here what is shown in debug window:

`════════ Exception caught by gesture ═══════════════════════════════════════════════════════════════
The following NoSuchMethodError was thrown while handling a gesture:
The getter 'isNotEmpty' was called on null.
Receiver: null
Tried calling: isNotEmpty

When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      _ShippingMethodsState.build.<anonymous closure> (package:fstore/screens/checkout/shipping_method.dart:155:61)
#2      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:918:19)
#3      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1004:38)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
...
Handler: "onTap"
Recognizer: TapGestureRecognizer#ddce5
  debugOwner: GestureDetector
  state: ready
  won arena
  finalPosition: Offset(269.7, 332.0)
  finalLocalPosition: Offset(254.7, 14.5)
  button: 1
  sent tap down
════════════════════════════════════════════════════════════════════════════════════════════════════`

#Ticket-ID: #3232

<img width="377" alt="Screen Shot 2020-05-17 at 11 15 28 AM" src="https://user-images.githubusercontent.com/60041105/82140704-fe44df00-9830-11ea-8a6c-6150d5fed9d5.png">

**Comment by minhtruong315** [comment]
@ahmadali86 can u send me admin account via email:  truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/3237
I'll help you check that issue.
thanks

**Comment by ahmadali86** [comment]
> @ahmadali86 can u send me admin account via email: [truong@inspireui.com](mailto:truong@inspireui.com)
> with subject: #3237
> I'll help you check that issue.
> thanks

I sent the details via email

**Comment by minhtruong315** [comment]
<img width="703" alt="Screen Shot 2020-05-18 at 4 27 59 PM" src="https://user-images.githubusercontent.com/10402500/82197011-a25b8280-9924-11ea-9612-ff2553845efd.png">
Hi @ahmadali86 Your website throws this issue. I think the website has issue with extensions. you can try to remove these extensions
<img width="1365" alt="Screen Shot 2020-05-18 at 4 31 47 PM" src="https://user-images.githubusercontent.com/10402500/82197357-1c8c0700-9925-11ea-8f13-c5fafe234a14.png">

**Comment by ahmadali86** [comment]
After I deleted the above-mentioned extensions now it does not even proceed to shipping method and locked into cart page:
<img width="380" alt="Screen Shot 2020-05-18 at 12 30 26 PM" src="https://user-images.githubusercontent.com/60041105/82203449-9e6b3880-9903-11ea-8a26-4430322cb625.png">
What shall I do now?

**Comment by minhtruong315** [comment]
[checkout.mov.zip](https://github.com/inspireui/support/files/4644802/checkout.mov.zip)
it's working on my source code

**Comment by ahmadali86** [comment]
I uninstalled the app from the phone and reinstall it again and it is back to the first problem that it is stopped with the following error: No Shipping options are available
[shipping .zip](https://github.com/inspireui/support/files/4645303/shipping.zip)

**Comment by minhtruong315** [comment]
Hi  @ahmadali86 can you try to replace getCheckoutId function on  models/cart/mixin/shopify_mixin.dart  like this
```
@override
  String getCheckoutId() {
    return checkout?.id;
  }
```
it's showing on my  end
![Simulator Screen Shot - iPhone X - 2020-05-20 at 14 12 19](https://user-images.githubusercontent.com/10402500/82416261-f04ac480-9aa3-11ea-8506-2abae2230816.png)

**Comment by ahmadali86** [comment]
It worked .. really I would not think the problem would be in this file. 
Thank you
