### ISSUE TITLE
login FluxStore

### ISSUE THREAD

**Issue by abd096** [inspireui/support#3239]
issue in login using emails and password registered in woocommerce.

After i created firebase config and put the google-services.json file then changed bundle id in those files:
build.grdle, AndroidManifest.xml, MainActivity.kt, 

then changed android/app/src/main/kotlin/com/inspireui/fluxstore name to my package name.

The app stop login and keep rounding on login page when i put customer email and password

**Comment by abd096** [comment]
it is for both both android and ios

**Comment by kvt0012** [comment]
https://medium.com/@inspireui   
Please follow these guides, I think it will help you solve your issue   
And watch more video, we also guide it there, thank you

**Comment by abd096** [comment]
Hello, yes i did exactly the same and push notifications worked. 

But after i did all steps the app stop login in for customers resisted in woocommerce, i mean the app working fine but when customer try to login, the app keeps rounding without login

**Comment by kvt0012** [comment]
You mean that after you login into the app when you checkout, it conitnue to force you login again ? Thank you

**Comment by abd096** [comment]
No, that happens on the login screen and before login. please watch this video 

https://jumpshare.com/v/5mmgadRycTZVnllxA8Yg

when i login using customer email and password, it keeps rounding without login in

**Comment by kvt0012** [comment]
This issue happens because of your api, please try to check and make sure that you do right as our document, thank you

**Comment by abd096** [comment]
bro, the api is correct. this issue came up when i added the Firebase settings, i have old version of app is live now and without firebase settings and it is working fine

**Comment by kvt0012** [comment]
Oh please send your whole project via my email : vinhkhiemt135@gmail.com   
I will check it for you, thank you

**Comment by abd096** [comment]
ok bro, i sent you the source code

**Comment by kvt0012** [comment]
which is your email, sir ? I will check it now, thank you

**Comment by abd096** [comment]
Hello, my email address is abd.turk.096@gmail.com

i put the subject as login FluxStore #3239

Thank you

**Comment by abd096** [comment]
hello @kvt0012 how are you ? 

did you have the chance to check my project ?

**Comment by abd096** [comment]
hello @kvt0012 how are you ?

did you have the chance to check my project ?

**Comment by minhcasi** [comment]
@kvt0012 - pls help to update

**Comment by minhcasi** [comment]
We wanted to thank you for your patience during this busy time. We currently have reduced staff and a significantly higher volume of inquiries. We’re working as hard as we can to get to your request as soon as possible.

We sincerely apologize for the delay and hope you’re staying safe.

**Comment by kvt0012** [comment]
> hello @kvt0012 how are you ?
> 
> did you have the chance to check my project ?

Sorry for late, sir. 
This ip updated and will be released on the next version. Thank you

**Comment by abd096** [comment]
Hello,

when will publish the new update?
