### ISSUE TITLE
[ListApp]while login into facebook account it's shows error message...

### ISSUE THREAD

**Issue by Pavithran10** [inspireui/support#324]
**Required Info (please complete the following information):**
Product:[ListApp]
Version:1.6.1
Theme: MyListing

**Describe the bug**
Hi, we create our own app id in facebook and we sync our app id into your coding. then while run the app we use to login into facebook it's logged into the test user account but it show error msg "unsuccessful debug_token response from facebook". The user fb account not able to sync in our application.

**Screenshots**
![fberror1](https://user-images.githubusercontent.com/46148046/53149000-60814680-35d2-11e9-80e0-e62217e553de.png)

**Additional context**
note: Our app id is sync only in facebook account login or we need to sync app id in firebase account too.

**Comment by thangvo9x** [comment]
Ah. This error is coming from your Facebook app such as config facebook app on your firebase app.
Please check guide of the facebook app. Thanks

**Comment by Pavithran10** [comment]
hi, I seen and then I've config appid into firebase account the "setup facebook config OAuth redirect URI" in facebook developer but I don't know to solve this error. so, please give any solution for this issue.  thanks
