### ISSUE TITLE
[Fluxstore Multivendor] Build appbundle issue

### ISSUE THREAD

**Issue by gelocaindoy** [inspireui/support#3240]
Step 1 (require): detail issues and screenshots

![image](https://user-images.githubusercontent.com/65111463/82146789-09266080-987f-11ea-8ba0-fe15afba0647.png)

help me for this error please.

Step 2 DONE (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by vumanhsn97** [comment]
@gelocaindoy This error appear because you edit file folder in android folder or you delete android folder and create a new one. Please download app again and just edit in lib folder

**Comment by gelocaindoy** [comment]
hi @vumanhsn97 

here is the error while editing in bundle id in tools

![image](https://user-images.githubusercontent.com/65111463/82273472-2ad33500-99b0-11ea-99db-6bbe57c88794.png)

**Comment by gelocaindoy** [comment]
@vumanhsn97 @minhcasi help me please. thanks!

**Comment by vumanhsn97** [comment]
@gelocaindoy 
This tools just support for MAC. It will support for windows in the future. Thanks!

**Comment by gelocaindoy** [comment]
Hi @vumanhsn97 yes i already installed ubuntu to my windows to create a bash command
is this not possible?

Thanks!

**Comment by vumanhsn97** [comment]
it just work in MAC. Waiting for 3-4 days to work in windows

**Comment by minhcasi** [comment]
@gelocaindoy - please help try this guide to change the bundle manually on window https://docs.inspireui.com/fluxstore/delivery-android/ - we will upgrade new script on later lease due to the complexity/permission script on Window that we need time to check it.

Let us know if you have any further issues, feel free to reopen the ticket - thank you!
