### ISSUE TITLE
Comments didnot work

### ISSUE THREAD

**Issue by ANaSHaker** [inspireui/support#3245]
I have a problem in my app with comments
When i try to add when it only show snackbar

**Comment by ANaSHaker** [comment]
؟؟

**Comment by minhcasi** [comment]
@ANaSHaker - Thank you for the feedback.

Please help us to submit this form and fill all require info to continue with the support - http://private.inspireui.com/ 

We will close this ticket as is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
pls help not to share the purchase code here as other users could use it for activation, thank you for your time

**Comment by minhcasi** [comment]
@ANaSHaker - pls help to update - thank you!
