### ISSUE TITLE
How to route to profile update screen after sms login

### ISSUE THREAD

**Issue by mmasifashraf** [inspireui/support#3249]
How to route to profile update screen after sms login is successful.

there i want to show the mobile number desperately from the display name. Please advice how to do this.

**Comment by minhcasi** [comment]
Hi, you could customize this function to route to the profile page

<img width="1072" alt="Screen Shot 2020-05-18 at 13 57 18" src="https://user-images.githubusercontent.com/1459805/82183063-7eda0d00-990f-11ea-8437-72fd5667398b.png">

pls move your all further conversation to the same ticket #3248
