### ISSUE TITLE
Mstore multi vendor

### ISSUE THREAD

**Issue by Bilal-Saidat** [inspireui/support#3250]
1- The Rest API is not working correctly !

2- and how to setup product categories 
its not clear 
should i add the same name - and hoe is the category number work -- should i add it on the woocommerce tag place ?????

**Comment by Bilal-Saidat** [comment]
i don't get any thing useful 
could you help 
how to write category in woo-commerce and app 
?????????
thank you in advance

**Comment by minhcasi** [comment]
@Bilal-Saidat - please check this guide to test the Rest API - https://github.com/woocommerce/woocommerce/wiki/Getting-started-with-the-REST-API

The category will be synced to the app on category screen. On the homescreen you could check this guide - https://docs.inspireui.com/mstore-mv/customization/#2-update-the-homepage-layout - thank you!

**Comment by Bilal-Saidat** [comment]
Dear MR Minh

thank you for the response
i still dont get what is (Open src/common/AppConfig.json and edit the
categoryId or TagId of your site)
how to do it with my site
thank you in advance
Regards
Bilal Saidat

**Comment by luyx2412** [comment]
Hi @Bilal-Saidat Please read the document and follow it to install your app. https://docs.inspireui.com/mstore-mv

Thanks

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
