### ISSUE TITLE
MultiVendor google sign in not work

### ISSUE THREAD

**Issue by Cheewingtan** [inspireui/support#3253]
Step 1 (require): detail issues and screenshots
https://docs.inspireui.com/fluxstore/sign-in/ I follow this guild to do the google social login but on this step, I found this guild is for fluxstore only, not for multivendor, cause on multivendor version I didn't found this .keystore file
<img width="1440" alt="Screenshot 2020-05-18 at 11 14 07 AM" src="https://user-images.githubusercontent.com/11556877/82171125-fbadbc80-98f8-11ea-99ef-a8ac7fb03003.png">
<img width="1440" alt="Screenshot 2020-05-18 at 11 14 52 AM" src="https://user-images.githubusercontent.com/11556877/82171128-fd778000-98f8-11ea-8524-e2ea89befcd5.png">
<img width="389" alt="Screenshot 2020-05-18 at 11 15 06 AM" src="https://user-images.githubusercontent.com/11556877/82171131-fea8ad00-98f8-11ea-804e-1fb5e8a9f209.png">

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@Cheewingtan - you could generate your own .keystore 

Please check this guide: 
- https://flutter.dev/docs/deployment/android#create-a-keystore
- https://stackoverflow.com/questions/39144629/how-to-add-sha-1-to-android-application

Please help to move your conversation to the same ticket #3156 - thank you!
