### ISSUE TITLE
MultiVendor Stores show nothing

### ISSUE THREAD

**Issue by Cheewingtan** [inspireui/support#3254]
Step 1 (require): detail issues and screenshots
the app get showing the category but on stores page is show nothing and my website haver around 1000k stores  
<img width="440" alt="Screenshot 2020-05-18 at 12 10 18 PM" src="https://user-images.githubusercontent.com/11556877/82173658-98278d00-9900-11ea-938a-fbb92e235e59.png">
<img width="363" alt="Screenshot 2020-05-18 at 12 08 30 PM" src="https://user-images.githubusercontent.com/11556877/82173660-9e1d6e00-9900-11ea-91f2-efcf8e25a1a3.png">

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by minhtruong315** [comment]
Hi @Cheewingtan Do you use dokan plugin on your website? Can u send me admin account to login to your website via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/3254

**Comment by Cheewingtan** [comment]
> Hi @Cheewingtan Do you use dokan plugin on your website? Can u send me admin account to login to your website via email: [truong@inspireui.com](mailto:truong@inspireui.com)
> with subject: #3254

HI I just send you admin account from tcheewing1@gmail.com please check your inbox

**Comment by Cheewingtan** [comment]
> Hi @Cheewingtan Do you use dokan plugin on your website? Can u send me admin account to login to your website via email: [truong@inspireui.com](mailto:truong@inspireui.com)
> with subject: #3254

how about the subject 3156? I still cant see my product on first screen

**Comment by minhtruong315** [comment]
Hi @Cheewingtan your website is using WCFM plugin by your config is doken
```
const serverConfig = {
  "type": "dokan",
  "url": "https://dev.lokein.com/",
```
You could refer example folder to update config.
You must verify MStore Api plugin to use our plugin. 
Thanks
<img width="1017" alt="Screen Shot 2020-05-21 at 6 05 02 AM" src="https://user-images.githubusercontent.com/10402500/82506242-79f0a580-9b29-11ea-8b43-e73fbad8aaf4.png">

**Comment by Cheewingtan** [comment]
> Hi @Cheewingtan your website is using WCFM plugin by your config is doken
> 
> ```
> const serverConfig = {
>   "type": "dokan",
>   "url": "https://dev.lokein.com/",
> ```
> 
> You could refer example folder to update config.
> You must verify MStore Api plugin to use our plugin.
> Thanks
> <img alt="Screen Shot 2020-05-21 at 6 05 02 AM" width="1017" src="https://user-images.githubusercontent.com/10402500/82506242-79f0a580-9b29-11ea-8b43-e73fbad8aaf4.png">



> Hi @Cheewingtan your website is using WCFM plugin by your config is doken
> 
> ```
> const serverConfig = {
>   "type": "dokan",
>   "url": "https://dev.lokein.com/",
> ```
> 
> You could refer example folder to update config.
> You must verify MStore Api plugin to use our plugin.
> Thanks
> <img alt="Screen Shot 2020-05-21 at 6 05 02 AM" width="1017" src="https://user-images.githubusercontent.com/10402500/82506242-79f0a580-9b29-11ea-8b43-e73fbad8aaf4.png">

yes , is work to me thanks , how about the subject 3156?

**Comment by Cheewingtan** [comment]
<img width="461" alt="Screenshot 2020-05-21 at 2 32 02 PM" src="https://user-images.githubusercontent.com/11556877/82530509-0de56000-9b70-11ea-82af-fceceba82eed.png">
I create the cert before and I type this command on terminal "keytool -list -v -keystore ~/key.jks -alias key"
it display the sha1 and sha256 I put on firebase and generate json file to replace my folder but it still not work I don't know why 
<img width="1440" alt="Screenshot 2020-05-21 at 2 36 02 PM" src="https://user-images.githubusercontent.com/11556877/82530770-a085ff00-9b70-11ea-9bda-5d379b2c10eb.png">
<img width="1440" alt="Screenshot 2020-05-21 at 2 35 39 PM" src="https://user-images.githubusercontent.com/11556877/82530777-a54ab300-9b70-11ea-9299-dbe71f18f4f9.png">

**Comment by minhtruong315** [comment]
@Cheewingtan you're using our package id. please change package id. You can refer this link to change package id
https://medium.com/@skyblazar.cc/how-to-change-the-package-name-of-your-flutter-app-4529e6e6e6fc

**Comment by Cheewingtan** [comment]
> @Cheewingtan you're using our package id. please change package id. You can refer this link to change package id
> https://medium.com/@skyblazar.cc/how-to-change-the-package-name-of-your-flutter-app-4529e6e6e6fc
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/546bb3ea61c144cabbdfc584035f101c839cb7f0/68747470733a2f2f6d69726f2e6d656469756d2e636f6d2f6d61782f3838392f312a64752d76354c545841783155452d386f4d365a4b4e672e706e67"><img alt="" height="14" src="https://camo.githubusercontent.com/a1c598ee8610a8cdb0e8bdbf112f3f1c77af25cb/68747470733a2f2f63646e2d7374617469632d312e6d656469756d2e636f6d2f5f2f66702f69636f6e732f66617669636f6e2d72656272616e642d6d656469756d2e33593678705a2d3046536457446e504d3368534249412e69636f"> Medium**[How to Change the Package Name of your Flutter app](https://medium.com/@skyblazar.cc/how-to-change-the-package-name-of-your-flutter-app-4529e6e6e6fc)**There are 6 main steps to take to successfully change the package name for your flutter app.

HI ,I follow these step to do but on step 1 I didn't found MainActivity.java file,but I found GeneratedPluginRegistrant.java and I continue follow all the step from the article ,and it get error "FAILURE: Build failed with an exception.  " 

<img width="1440" alt="Screenshot 2020-05-22 at 3 34 05 PM" src="https://user-images.githubusercontent.com/11556877/82643615-67b65a80-9c42-11ea-95f3-2f6d138e2728.png">

**Comment by minhtruong315** [comment]
@Cheewingtan check this https://www.youtube.com/watch?v=3DYdBBtvAbg

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!

**Comment by Cheewingtan** [comment]
> @Cheewingtan check this https://www.youtube.com/watch?v=3DYdBBtvAbg
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/d8925a291cddde9a34b12298ef0f4aae3ebe6805/68747470733a2f2f692e7974696d672e636f6d2f76692f33445964424274764162672f6d617872657364656661756c742e6a7067"><img alt="" height="14" src="/yts/img/favicon_144-vfliLAfaB.png"> YouTube**[Easily change bundle id through script on Mac (Flutter E-Commerce App In 10 Minutes)](https://www.youtube.com/watch?v=3DYdBBtvAbg)**Learn how to run the script to change bundle id, rename working folder, and change project name easily and quickly. This script mainly supports for Fluxstore...

I follow this step to do on my project is to get fail and I download new file and try this step ,it will occur same error with below image
<img width="351" alt="Screenshot 2020-05-27 at 1 11 07 PM" src="https://user-images.githubusercontent.com/11556877/82980534-45468780-a01c-11ea-8b38-d43842c07ecb.png">
<img width="1034" alt="Screenshot 2020-05-27 at 1 11 29 PM" src="https://user-images.githubusercontent.com/11556877/82980539-48417800-a01c-11ea-9b15-f4b567ddfc32.png">
<img width="1440" alt="Screenshot 2020-05-27 at 1 13 22 PM" src="https://user-images.githubusercontent.com/11556877/82980543-4aa3d200-a01c-11ea-830f-64b08173d8fd.png">
