### ISSUE TITLE
[FluxStore Pro] An example of what I'm talking about in issue #3247

### ISSUE THREAD

**Issue by bikostudio** [inspireui/support#3255]
[FluxStore Pro] An example of what I'm talking about in issue #3247 

This problem was not in 1.7.2  Now it is in 1.7.3

![2020-05-18_062516](https://user-images.githubusercontent.com/62074493/82174428-f9376c80-98d0-11ea-8255-708fd17d8b91.jpg)

![2020-05-18_062851](https://user-images.githubusercontent.com/62074493/82174443-05bbc500-98d1-11ea-8bfa-b55ee16aaa90.jpg)

**Comment by bikostudio** [comment]
Ok @minhcasi, what I understand now is I need to pay additional money for more support. No problem. I have two things need to add in the app. Can you do it for me with paid service?

1. I need to add some new custom fields in registration page and checkout page.
2. I need to add a clickable image banner in the categories screen.

How much this will cost me?

Thanks

**Comment by bikostudio** [comment]
I need to add some new custom fields in registration page and checkout page.
How much this will cost me?

Thanks

**Comment by bikostudio** [comment]
> 
> 
> [FluxStore Pro] An example of what I'm talking about in issue #3247
> 
> This problem was not in 1.7.2 Now it is in 1.7.3
> 
> ![2020-05-18_062516](https://user-images.githubusercontent.com/62074493/82174428-f9376c80-98d0-11ea-8255-708fd17d8b91.jpg)
> 
> ![2020-05-18_062851](https://user-images.githubusercontent.com/62074493/82174443-05bbc500-98d1-11ea-8bfa-b55ee16aaa90.jpg)

@minhcasi     Is there any hope to fix this?

**Comment by bikostudio** [comment]
Now it gives me this

![2020-05-18_201414](https://user-images.githubusercontent.com/62074493/82246077-57e9fe00-9944-11ea-9f47-1ba8d2a40895.jpg)

and creates the account at Firebase not woocommerce site. 

Any idea how to fix?
thank you

**Comment by minhtruong315** [comment]
@bikostudio can u send me common folder and admin account to login your website via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/3255

**Comment by bikostudio** [comment]
> 
> 
> @bikostudio can u send me common folder and admin account to login your website via email: [truong@inspireui.com](mailto:truong@inspireui.com)
> with subject: #3255
Thank you @minhtruong315  I just tried to recreate WooCommerce RESET API and use it and it works. But I thing the problem maybe with the Mstore api plugin stability. Because this issue happened before.

**Comment by minhtruong315** [comment]
Hi @bikostudio so are your issues resolved?

**Comment by bikostudio** [comment]
> 
> 
> Hi @bikostudio so do your issues resolved?

Yes @minhtruong315 it solved by recreate WooCommerce RESET. but Please check the stability of the Mstore aip plugin. maybe it make the error I don't know. but for now it works.
thank you for your time

**Comment by minhtruong315** [comment]
@bikostudio Thanks  for your report. I will check MStore Api plugin.
