### ISSUE TITLE
Fluxstore multi vendor - i'm not able to login or register

### ISSUE THREAD

**Issue by shubhamsurvase** [inspireui/support#3257]
1.I have username and password in database, i was try to login using this username and password but it shows me this error on mobile screen.
![Screenshot_2020-05-16-13-57-01-82](https://user-images.githubusercontent.com/65527267/82179228-7081f600-98fb-11ea-8b06-0a30c7ba2c2a.png)
2. i already checked checkbox, but still it  gives me this error.
![Screenshot_2020-05-16-13-33-21-60](https://user-images.githubusercontent.com/65527267/82179399-e0907c00-98fb-11ea-87ef-23d07ba00e1a.png)

**Comment by vumanhsn97** [comment]
1. Follow this toturial: https://docs.inspireui.com/fluxstore/sign-in/
2. Fixed in this issue: https://github.com/inspireui/support/issues/3105#issuecomment-628487671

**Comment by shubhamsurvase** [comment]
hi sir, still there is same problem.
![Screenshot_2020-05-19-15-21-26-68](https://user-images.githubusercontent.com/65527267/82313466-03975a80-99e6-11ea-98af-eaf6f39f218c.png)

**Comment by shubhamsurvase** [comment]
i followed all the instructions in document still error occurs
![Screenshot_2020-05-19-15-21-26-68](https://user-images.githubusercontent.com/65527267/82313793-7c96b200-99e6-11ea-8afd-c44164de6ff4.png)

**Comment by shubhamsurvase** [comment]
i followed all the instructions in document still error occurs
![Screenshot_2020-05-19-14-36-51-71](https://user-images.githubusercontent.com/65527267/82313892-9df79e00-99e6-11ea-9a87-7e7b783ebb92.png)

**Comment by vumanhsn97** [comment]
@shubhamsurvase rest_forbidden: https://tppr.me/tyfzc
Follow this issue: https://github.com/inspireui/support/issues/3015#issuecomment-626111390

**Comment by shubhamsurvase** [comment]
Thank you, i'll check it.

**Comment by shubhamsurvase** [comment]
sir still there is same problem.
in terminal,
I/BiChannelGoogleApi( 7076): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@1f7b2d54
W/DynamiteModule( 7076): Local module descriptor class for com.google.firebase.auth not found.
I/FirebaseAuth( 7076): [FirebaseAuth:] Preparing to create service connection to gms implementation
 whenever i'm tring to create account this error occurs and on mobile screen "you are not allow to do this" is appear

**Comment by shubhamsurvase** [comment]
Store List is getting NULL

**Comment by vumanhsn97** [comment]
Can you send your admin account to vumanhsn97@gmail.com?

**Comment by shubhamsurvase** [comment]
Username:- lajawab
Password:- admin?123

**Comment by vumanhsn97** [comment]
@shubhamsurvase 
Make sure you add 2 lines in htaccess file
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule ^(.*) - [E=HTTP_AUTHORIZATION:%1]

**Comment by shubhamsurvase** [comment]
[image: image.png]

**Comment by shubhamsurvase** [comment]
sir, still there is same error.

**Comment by minhcasi** [comment]
@shubhamsurvase - pls help to try the solution on this ticket https://github.com/inspireui/support/issues/3151#issuecomment-633011788 - thank you!

**Comment by shubhamsurvase** [comment]
W/ContextImpl(13925): forgetServiceDispatcher failed for:
W/ContextImpl(13925): java.lang.IllegalArgumentException: Service not
registered: com.google.android.gms.measurement.internal.zzin@25cb3151

sir, i added SHA key to firebase but still this error appear and same
problem is there

**Comment by minhcasi** [comment]
@shubhamsurvase - pls try it more careful to fix the login issue, all these steps will fix the problem - https://github.com/inspireui/support/issues/3151#issuecomment-633489369

**Comment by shubhamsurvase** [comment]
see i already done it.

**Comment by shubhamsurvase** [comment]
sir, from last week i stuck on the same problem, i already did what you say
but still it's not working. please give me a solution.

**Comment by shubhamsurvase** [comment]
I solved a login and register problem. thank you
