### ISSUE TITLE
FluxStore [Woocommerce]

### ISSUE THREAD

**Issue by zahmed84** [inspireui/support#3258]
I just want to show products with discount or on Sale at home page. Please let me know what to mention on config.json file so that the customer can view those products which i have put on discount.

Thanks

**Comment by minhcasi** [comment]
@zahmed84 

You could try to add the `onSale: true`

**Comment by zahmed84** [comment]
Its not working, Can you show me where to add this string "onSale: true" Your response in this regard will be highly appreciated thanks.

**Comment by ameenbadri7** [comment]
if you would like to show only the woocommerce Featured Products add this to your config.json files:

{
      "name": "Featured Products",
      "image": "assets/companyLogo/samsunglogo.png",
      "layout": "threeColumn",
      "category": 56,
      "isSnapping": true,
      "featured": true

    },

if you would like to show only the on sale products (the products with red discount badge) add this: 
    {
      "name": "Big Discounts",
      "image": "assets/companyLogo/applelogo.png",
      "layout": "threeColumn",
      "category": 58,
      "isSnapping": true,
      "onSale": true
    },

if you would like to show on sale products only end exclude the feathers from it: 
    {
      "name": "LG Phones",
      "image": "assets/companyLogo/lglogo.png",
      "layout": "threeColumn",
      "category": 59,
      "isSnapping": true,
      "featured": false,
      "onSale": true

    },


just play with the : 

      "featured": true
      "featured": false

or 
      "onSale": true
      "onSale": false 

or mix them all  ...
enjoy
