### ISSUE TITLE
How to integrate the stripe payment to FluxStore app?

### ISSUE THREAD

**Issue by liqiang1995** [inspireui/support#3259]
How are you?
I need to integrate the stripe payment to the Fluxstore app.
But I can not find the documentation for the stripe payment system.
I have done the stripe setting on my WordPress admin panel.
But I don't know How to setup the stripe payment for the FluxStore app.
Please help me.
Or give me a documentation link.
Thank You.
![image](https://user-images.githubusercontent.com/54995513/82185818-67ede780-991c-11ea-9dae-6cd94e9782b2.png)

**Comment by minhcasi** [comment]
@liqiang1995 - pls try this lib - https://pub.dev/packages/stripe_payment  

----

Next time: Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!
