### ISSUE TITLE
Fluxstore Pro - Order history not loading for Magento store.

### ISSUE THREAD

**Issue by subhquad** [inspireui/support#3260]
Step 1 (require): detail issues and screenshots

Order history page loading with error . Please check the attached screenshot.
<img width="348" alt="Screenshot 2020-05-17 at 21 59 23" src="https://user-images.githubusercontent.com/10830054/82186832-5a683b80-98e3-11ea-8245-9127f4201d90.png">

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by minhtruong315** [comment]
Hi @subhquad Can you try to edit fromMagentoJson function like this
```
Order.fromMagentoJson(Map<String, dynamic> parsedJson) {
    try {
      id = parsedJson["entity_id"].toString();
      number = "${parsedJson["entity_id"]}";
      status = parsedJson["status"];
      createdAt = parsedJson["created_at"] != null
          ? DateTime.parse(parsedJson["created_at"])
          : DateTime.now();
      total = parsedJson["base_grand_total"] != null
          ? double.parse("${parsedJson["base_grand_total"]}")
          : 0.0;
      paymentMethodTitle = parsedJson["payment"]["additional_information"][0];
      shippingMethodTitle = parsedJson["shipping_description"];
      parsedJson["items"].forEach((item) {
        lineItems.add(ProductItem.fromMagentoJson(item));
      });
      billing = Address.fromMagentoJson(parsedJson["billing_address"]);
    } catch (e, trace) {
      print(e.toString());
      print(trace.toString());
    }
  }
```

**Comment by subhquad** [comment]
Its working fine now.
