### ISSUE TITLE
Google SignIn is email is not storing in firebase

### ISSUE THREAD

**Issue by inspireuis** [inspireui/support#3266]
Step 1 (require): detail issues and screenshots
I have integrated facebook, google and sms login. All three are working but google ones are not storing in firebase. User is able to login in all three cases. Only the user is not get registered in firebase in case of google

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@inspireuis - pls move this conversation to the same of your ticket #3230
