### ISSUE TITLE
[FluxStore Pro WooCommerce] Insert Short Description in product page

### ISSUE THREAD

**Issue by felipelevangelista** [inspireui/support#3267]
Hi, how are you? First of all, thanks for this app, it's amazing!

I bought the app this weekend and since then I'm looking a way to insert the Short Description as a new tab in product page.

It is possible?

This is very important to me! My store in WooCommerce was configured with the all informations in Short Description and I have more than 1000 products active. I can't change the config of all this products.

I need to put this information:

[https://www.hoppi.com.br/wp-content/uploads/2020/05/Short-Description.jpg](https://www.hoppi.com.br/wp-content/uploads/2020/05/Short-Description.jpg)

Here:

[https://www.hoppi.com.br/wp-content/uploads/2020/05/Screenshot_20200518-103043.jpg](https://www.hoppi.com.br/wp-content/uploads/2020/05/Screenshot_20200518-103043.jpg)

Thanks for your help!

**Comment by felipelevangelista** [comment]
I forgot one thing, this is the proof that I buy the app:

[https://www.hoppi.com.br/wp-content/uploads/2020/05/Proof.jpg](https://www.hoppi.com.br/wp-content/uploads/2020/05/Proof.jpg)

**Comment by kvt0012** [comment]
Dear sir, on our app we had this feature here   
 

![](https://user-images.githubusercontent.com/49152325/82312217-f5027080-99f0-11ea-992f-d041d5344bda.png)

**Comment by kvt0012** [comment]
> ![](https://user-images.githubusercontent.com/49152325/82312266-03e92300-99f1-11ea-92c6-d3f4b3ee57ce.png)

**Comment by kvt0012** [comment]
![image](https://user-images.githubusercontent.com/49152325/82312475-4e6a9f80-99f1-11ea-80b8-db831b2ad111.png)
