### ISSUE TITLE
[Fluxstore] - errors when i make New Account and the shipping address or city not appear

### ISSUE THREAD

**Issue by limitlessfirm** [inspireui/support#3268]
Step 1 (require): detail issues and screenshots
![97043249_580921225861865_5771834698862952448_n](https://user-images.githubusercontent.com/59250639/82219047-0da15680-991d-11ea-8fce-9199442b5812.png)
![97892449_2665944343648279_5843270793953280000_n](https://user-images.githubusercontent.com/59250639/82219058-1134dd80-991d-11ea-8f5b-357dcbc50be3.png)

1- I show error when i make New Account the error attached

2- when i login with google login and make order there is no shipping address appear or required and zones and cites appear in egypt country 

3- no shipping cost appear 

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by limitlessfirm** [comment]
The problems:


1- I show error when i make New Account the error attached

2- when i login with google login and make order there is no shipping address appear or required and zones and cites appear in egypt country 


3- no shipping cost appear

**Comment by kvt0012** [comment]
Q1: Please attached your screenshot again because I can't see it, thank you   
Q2: But I think you should send me your whole project via khiem@inspireui.com, I will check it.   
Q3: About shipping cost, please check your api, you must make sure that your api is well for it, thank you

**Comment by limitlessfirm** [comment]
I sent the whole project to your email (khiem@inspireui.com)
