### ISSUE TITLE
product out of stock it is possible to buy on the wish list

### ISSUE THREAD

**Issue by joaonathan** [inspireui/support#3269]
when I take a product out of stock, it disappears from the application, but it is still possible to buy it through the wish list

![WhatsApp Image 2020-05-18 at 11 41 21](https://user-images.githubusercontent.com/9143192/82226393-d58a1b80-98fc-11ea-9f45-aeda8a1291eb.jpeg)

![WhatsApp Image 2020-05-18 at 11 41 21 (1)](https://user-images.githubusercontent.com/9143192/82226409-da4ecf80-98fc-11ea-9052-9eaac4b860a3.jpeg)

![WhatsApp Image 2020-05-18 at 11 41 21 (2)](https://user-images.githubusercontent.com/9143192/82226417-dc189300-98fc-11ea-8683-d61e10875567.jpeg)

**Comment by joaonathan** [comment]
if there is any product saved in the cart it is also possible to buy without stock

**Comment by minhcasi** [comment]
@joaonathan - thank you for your feedback, we will investigate and keep update on this enhancement

**Comment by minhcasi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improve: product out of stock it is possible to buy on the wish list](https://trello.com/c/xkvPf8QN/45-improve-product-out-of-stock-it-is-possible-to-buy-on-the-wish-list)

**Comment by minhcasi** [comment]
moved to team backlog for further investigating
