### ISSUE TITLE
App rate 

### ISSUE THREAD

**Issue by Roupasafricanas** [inspireui/support#3271]
Step 1 (require): detail issues and screenshots

![IMG_20200518_132615](https://user-images.githubusercontent.com/63840938/82237662-64526480-990c-11ea-89e3-637680a03313.jpg)

Good Morning. I would like to know where I insert my application data to be able to rate on playstore. When I choose to evaluate, the apk of fluxstore appears and not mine. show me the exact path please

![Screenshot_2020-05-18-13-31-56-004_com roupasafricanas app](https://user-images.githubusercontent.com/63840938/82237715-7b915200-990c-11ea-9861-6402e51c77dc.jpg)
![Screenshot_2020-05-18-13-32-11-365_com android vending](https://user-images.githubusercontent.com/63840938/82237723-80560600-990c-11ea-980f-b61a270322ff.jpg)

**Comment by minhcasi** [comment]
Hi, you could try to edit this config to fix this issue - thank you!


<img width="950" alt="Screen Shot 2020-05-19 at 10 59 58" src="https://user-images.githubusercontent.com/1459805/82283208-e2237800-99bf-11ea-97d4-36e4b65a6d1b.png">
