### ISSUE TITLE
MstoreCheckOut issue

### ISSUE THREAD

**Issue by 1hourlife** [inspireui/support#3273]
Step 1 (require): detail issues and screenshots
We are getting the following error when we try to activate MStore API.

Fatal error: Cannot declare class MstoreCheckOut, because the name is already in use in /var/www/wp-content/plugins/mstore-api/mstore-api.php on line 24

We are trying to create our app using, and we have been having a lot of issues to make this work. 

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@1hourlife - the fluxstore listing is not required to install the mstore-api plugin, please help to check the list plugin from this guide - https://docs.inspireui.com/fluxstore/listing-directory/ - thank you!

**Comment by minhcasi** [comment]
Hi @1hourlife - please help us only install these plugins https://docs.inspireui.com/fluxstore/listing-directory/#step-2-install-the-required-plugins - the mstore-api is not required for the FluxListing - very best!
