### ISSUE TITLE
Product variants show an error on product detail on FluxStore MultiVendor

### ISSUE THREAD

**Issue by mauriciozuniga** [inspireui/support#3274]
Step 1 (require): detail issues and screenshots
When I configure products variants on WooCommerce, it shows me an error on product detail of FluxStore Multivendor 1.7.0
I am attaching a screenshot of how it displays on web, and how it shows on application.
Also, I am attaching screenshot of product configuration on wp admin, and Exception thrown in Android studio
<img width="1329" alt="Captura de Pantalla 2020-05-18 a la(s) 14 16 42" src="https://user-images.githubusercontent.com/8905579/82251449-d62dac80-9912-11ea-95c6-9d1a46274a78.png">
<img width="1309" alt="Captura de Pantalla 2020-05-18 a la(s) 14 22 37" src="https://user-images.githubusercontent.com/8905579/82251652-345a8f80-9913-11ea-8663-5f9b31ddacd5.png">

Exception thrown
════════ Exception caught by widgets library ════════════════════════════
The following _TypeError was thrown building ProductVariant(dirty, dependencies: [_InheritedTheme, _LocalizationsScope-[GlobalKey#4b02c]], state: StateProductVariant#bfc14):
type 'String' is not a subtype of type 'int'

The relevant error-causing widget was: 
  ProductVariant file:///Users/maozuniga/Documents/Desarrollo/FluxStore-vendor-1.7.0/source/lib/screens/detail/themes/simple_type.dart:169:43
When the exception was thrown, this was the stack: 
#0      WooVariantMixin.getProductAttributeWidget (package:fstore/widgets/frameworks/woocommerce/woo_variant_mixin.dart:112:52)
#1      StateProductVariant.getProductAttributeWidget (package:fstore/screens/detail/product_variant.dart:139:28)
#2      StateProductVariant.build (package:fstore/screens/detail/product_variant.dart:164:12)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4334:27)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4223:15)
...

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by minhcasi** [comment]
Please move your conversation to -  #3274

**Comment by mauriciozuniga** [comment]
This is #3274 what do you mean move it ?

**Comment by mauriciozuniga** [comment]
Please re open this issue since I think you get confused and closed it
