### ISSUE TITLE
[FluxStore Listing] Build Failed.

### ISSUE THREAD

**Issue by inspireuis** [inspireui/support#3276]
Step 1 (require): detail issues and screenshots

Hello @minhcasi ,
im getting the next error and dont let me run the app theme,

D8: Type com.google.firebase.iid.zzbb is referenced as an interface from com.google.firebase.messaging.zzf

![image](https://user-images.githubusercontent.com/65219388/82261807-53fab380-9925-11ea-9ecd-4a85df4dede6.png)

![image](https://user-images.githubusercontent.com/65219388/82261840-62e16600-9925-11ea-8aa9-46e855e0a9de.png)

![image](https://user-images.githubusercontent.com/65219388/82261860-6f65be80-9925-11ea-8e3e-517c1138c552.png)

Also have the red notes, can you please let me know how to solve the error and the red notes?

at this moment i configure the theme till the part to connect to website, server config.

Thanks and Regadrs,
InspireuiS.

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)
Complete, please check the link with the information / i add both licenses fluxstoreMV and fluxstore Listing 

![image](https://user-images.githubusercontent.com/65219388/82262673-f5363980-9926-11ea-82d2-08183cf32965.png)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by philipvu30** [comment]
Hi,

Please run these commands in the terminal
1. flutter upgrade
2. flutter clean
3. flutter packages get

**Comment by inspireuis** [comment]
hello philipvu30,

make the 3 steps:

1.2.) flutter upgrade, flutter clean

![image](https://user-images.githubusercontent.com/65219388/82295755-d8752280-9975-11ea-9cac-4a8ef2ac0c05.png)

3) pub get at pbspec.yaml

![image](https://user-images.githubusercontent.com/65219388/82295842-f80c4b00-9975-11ea-8934-eb7f21521784.png)

errors: 
![image](https://user-images.githubusercontent.com/65219388/82298251-76b6b780-9979-11ea-9fb6-b51d63af3ad8.png)

![image](https://user-images.githubusercontent.com/65219388/82298143-4b33cd00-9979-11ea-87ec-c9a86b7c1a0e.png)

**Comment by philipvu30** [comment]
Change version of rating_my_app in pubspec.yaml
from 0.6.0+2 to 0.6.1+2 then use the pub get

**Comment by inspireuis** [comment]
Hello Philipvu30,

change from 
![image](https://user-images.githubusercontent.com/65219388/82310615-3b70b480-998a-11ea-9f9d-1df0c3ecaf68.png)
to 
![image](https://user-images.githubusercontent.com/65219388/82310646-462b4980-998a-11ea-96b4-42b42d39bf2b.png)

errors:
![image](https://user-images.githubusercontent.com/65219388/82310710-5d6a3700-998a-11ea-9ce3-b610e1e4a8b8.png)

![image](https://user-images.githubusercontent.com/65219388/82310783-6c50e980-998a-11ea-9035-6cddc1d2a265.png)

**Comment by philipvu30** [comment]
Hi,

Please run flutter doctor -v then send me the log. Thanks

**Comment by inspireuis** [comment]
Hello Philipvu30,

![image](https://user-images.githubusercontent.com/65219388/82391718-9dbbca80-9a07-11ea-887d-19717d675af8.png)

Thanks,

**Comment by philipvu30** [comment]
Hi,

Can I have a look at these files?
1. android/app/build.gradle
2. android/gradle/wrapper/gradle-wrapper.properties
3. android/build.gradle 

Thanks

**Comment by inspireuis** [comment]
Good Day Philipvu30,

share you the files,
[android.zip](https://github.com/inspireui/support/files/4655868/android.zip)

thanks

**Comment by inspireuis** [comment]
Good Day Philipvu30, for making this process faster i put my code at the next link: 

https://drive.google.com/open?id=137XHbcGk5kG_vUGfXPGaD0lzBcwrYEOM 

Now i cant see gradle folder for android app

![image](https://user-images.githubusercontent.com/65219388/82522039-dafa8800-9aed-11ea-935b-122f6a676c0e.png)

even if it could run, code it still getting bugs, 

![image](https://user-images.githubusercontent.com/65219388/82522063-e8b00d80-9aed-11ea-8c92-7b457bc78f88.png)

Thanks,

**Comment by minhcasi** [comment]
@inspireuis - remind, pls don't share your all source here - thx

**Comment by inspireuis** [comment]
@minhcasi @philipvu30 let me know how can i provide the code? this is a slow way to solve, and im in first step of configuration, can you provide me your email to share the link? or can we connnect by a meeting so you can see it? 

Thanks,

**Comment by philipvu30** [comment]
Hi,

1. Please go to android/build.gradle and replace these 2 lines like this
![image](https://user-images.githubusercontent.com/54442328/82531903-70d3f880-9b6a-11ea-8024-57cd3a22e2b3.png)
2. Navigate to android/gradle/wrapper/gradle-wrapper.properties and change distributionurl from 6.3 to 4.10.2 like this
![image](https://user-images.githubusercontent.com/54442328/82532042-b1337680-9b6a-11ea-8ac5-7192c6fc8ae0.png)

**Comment by inspireuis** [comment]
hi @philipvu30 ,

almost, it load but with errors,

![image](https://user-images.githubusercontent.com/65219388/82539624-591d5580-9b13-11ea-85be-78ace4eed2f9.png)

![image](https://user-images.githubusercontent.com/65219388/82539629-5c184600-9b13-11ea-93a4-4ce4cd036d09.png)

![image](https://user-images.githubusercontent.com/65219388/82539637-5fabcd00-9b13-11ea-9b95-c373d56bfad7.png)

![image](https://user-images.githubusercontent.com/65219388/82539651-663a4480-9b13-11ea-837a-810e040f1ac6.png)

![image](https://user-images.githubusercontent.com/65219388/82539681-72260680-9b13-11ea-8438-c97db27f9d44.png)

![image](https://user-images.githubusercontent.com/65219388/82539692-77835100-9b13-11ea-99e3-632e726e5183.png)

![image](https://user-images.githubusercontent.com/65219388/82539711-7e11c880-9b13-11ea-87bc-797b804f4072.png)

![image](https://user-images.githubusercontent.com/65219388/82539721-8538d680-9b13-11ea-9c0f-beb1abd87ea4.png)

![image](https://user-images.githubusercontent.com/65219388/82539737-8d911180-9b13-11ea-9624-e601cbc1dcb9.png)

![image](https://user-images.githubusercontent.com/65219388/82539748-9255c580-9b13-11ea-8618-61bfa4633c55.png)

![image](https://user-images.githubusercontent.com/65219388/82539766-9a156a00-9b13-11ea-9cf9-a29a84fcdc9d.png)

![image](https://user-images.githubusercontent.com/65219388/82539782-9e418780-9b13-11ea-9ed8-6e93a273a432.png)

![image](https://user-images.githubusercontent.com/65219388/82539792-a39ed200-9b13-11ea-9b64-77d45e91313c.png)

![image](https://user-images.githubusercontent.com/65219388/82539800-a8fc1c80-9b13-11ea-8280-1a5f338dca90.png)

**Comment by philipvu30** [comment]
Hi,

Have you modified the config.dart and config.json files?
Because I run it fine with the common folder you submitted via our form.

**Comment by inspireuis** [comment]
Hi, 

1. config.dart modify as guide to connect to website:
![image](https://user-images.githubusercontent.com/65219388/82554488-a6a5bc80-9b2b-11ea-888b-f942fe63968a.png)
any other change was made.

2. config.json : no change was made.

3. Next plugins where install :
![image](https://user-images.githubusercontent.com/65219388/82554607-e40a4a00-9b2b-11ea-9e94-5aadda68020e.png)
![image](https://user-images.githubusercontent.com/65219388/82554650-f71d1a00-9b2b-11ea-966d-806974cac1be.png)

4. change the woo_commerce.dart file with the new shared,

5. Run again the app, same issues,

Thanks,

**Comment by philipvu30** [comment]
Hi,

Please replace the lib folder and the pubspec.yaml that I sent to your email.
Remember to copy and paste these 2 files config.json and config.dart in the example folder, then modify them as you like.

Hopefully it will solve all your issues.

**Comment by philipvu30** [comment]
Closed as no response in 2 days. Feel free to ask us to re-open the ticket again. Thank you
