### ISSUE TITLE
blog

### ISSUE THREAD

**Issue by miskayapp** [inspireui/support#3277]
Step 1 (require): detail issues and screenshots

my WordPress blog is not coming up on the fluxstore, I have added the url and connected api, everything else works fine but the blog

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as it could not be verified, please create the new one when you got enough purchased info - thank you!

**Comment by miskayapp** [comment]
i tried openeing your link and it wasent taking me to where i put the
purchase code

**Comment by miskayapp** [comment]
i keep getting this error, while i try to upload the app, "This bundle is
invalid - The Info.plist file is missing or could not be parsed"

**Comment by miskayapp** [comment]
please help,  https://github.com/inspireui/fluxbuilder/issues/85

i need to upload this for a client in 2hrs

**Comment by miskayapp** [comment]
im tired, i client are on my neck, i dint this app has bugs at at every
turn, i have sent tickets at github an 1 reply is all i get with nothing
helping my issue
