### ISSUE TITLE
Fluxstore Multivendor - APP and Webview

### ISSUE THREAD

**Issue by inspireuis** [inspireui/support#3278]
Step 1 (require): detail issues and screenshots

Good day support team,

There are some pages that the app calls from the webview, like the next one:

At the payment gateway, it calls the checkout page, for us ( https://gurutos.com/checkout-2/ )

How its the best way to make the changes? from the app theme? from the webview? cloning the webview page?

The idea its that it looks the same all the app, as the webview dont have the same colors and buttons.

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

Complete the verify license have been send.

![image](https://user-images.githubusercontent.com/65219388/82265374-6f1cf180-992c-11ea-939d-9274e4e3c01f.png)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@inspireuis - pls move this conversation to the same of your ticket #3230
