### ISSUE TITLE
how to change the flexstore logo Loading indicator 

### ISSUE THREAD

**Issue by mmasifashraf** [inspireui/support#3279]
How to change the default flex-store logo using from Loading indicator gif?

**Comment by minhcasi** [comment]
You could update this file 

<img width="955" alt="Screen Shot 2020-05-19 at 11 28 27" src="https://user-images.githubusercontent.com/1459805/82284718-dd60c300-99c3-11ea-858e-2f49ea4b1483.png">

**Comment by minhcasi** [comment]
Duplicate of #3294
