### ISSUE TITLE
[ListApp]facebook login related error issue we can't able to access facebook....

### ISSUE THREAD

**Issue by Pavithran10** [inspireui/support#328]
**Required Info (please complete the following information):**
Product:[ListApp]
Version:1.6.1
Theme: MyListing

**Describe the bug**
hi, i have a doubt regarding facebook login. your facebook app id is working directly through facebook only. Otherwise app id working through firebase application process via facebook. because I've confusing between these two functionality in the coding and also I'm geting two different error while testing the user fb login. I've displayed both error in screenshot. So, please tell which is error i need to solve.

**Screenshots**
![fberror](https://user-images.githubusercontent.com/46148046/53282366-b2ee6e80-375c-11e9-89a5-d6f4c81b3994.png)
![screenshot_1550747482](https://user-images.githubusercontent.com/46148046/53282371-b97ce600-375c-11e9-9f0c-c40de430befb.png)

**Comment by thangvo9x** [comment]
Hi, Please check your documentation facebook app such as the above image. The issue is coming from your setting facebook app.
