### ISSUE TITLE
[FluxStore MV] Product & category, splashscreen is not showing

### ISSUE THREAD

**Issue by ekramul-1** [inspireui/support#3280]
1) Product & category, is not showing,
2) Splash Screen unable to change even though following all the given steps in multivender.
3) Unable to connect the FLUXBUILDER even though giving all the correct details s mention in docs,
4) MAP not working.

Please have a look into the google form as I uploaded the more in details.

Thank you so much for your time 😊

**Comment by ekramul-1** [comment]
Any update  vumanhsn97 ?

**Comment by vumanhsn97** [comment]
@ekramul-1 Username or password not correct. Please check

**Comment by ekramul-1** [comment]
> @ekramul-1 Username or password not correct. Please check
@vumanhsn97 
https://bbmall.in/wp-admin
User-bbadmin
password-Gohere40410

**Comment by ekramul-1** [comment]
Please update this one as I am waiting from long time @vumanhsn97  @minhcasi ?

**Comment by vumanhsn97** [comment]
I try to create a new key but it can not connect your website because woocommerce_rest_cannot_view. Follow this solution: https://wordpress.org/support/topic/woocommerce-rest-api-error-401/

**Comment by ekramul-1** [comment]
But few things are connecting like I can see the all vendor/store but unable to connect category & product

**Comment by ekramul-1** [comment]
check now

**Comment by ekramul-1** [comment]
Please update this as I am waiting from a long time.

**Comment by ekramul-1** [comment]
![image](https://user-images.githubusercontent.com/63785688/82398118-aba53600-9a6f-11ea-96a5-d29b277e6d6d.png)

**Comment by ekramul-1** [comment]
Api connected today in fluxbuilder

![image](https://user-images.githubusercontent.com/63785688/82398197-dc856b00-9a6f-11ea-91e0-b1ad2871329c.png)

**Comment by ekramul-1** [comment]
Please let me know the solution for this

![image](https://user-images.githubusercontent.com/63785688/82405198-bf0ccd00-9a80-11ea-91ab-d2afda5d6767.png)

**Comment by vumanhsn97** [comment]
@ekramul-1 
Add this line in your config https://tppr.me/HKHM7. It will be fix in next version

**Comment by ekramul-1** [comment]
**### COULD YOU PLEASE EXPLAIN THE DETAILS STEPS FOR UPDATING SERVER CONFIG** 

Open lib/common/config.dart and change the url from serverConfig section to your own website which has the API set:

LIKE -  "type": "dokan", but I purchased wcfm then shall I replace with WCFM 
  "url": "http://dokan.mstore.io", = http://wcfm.bbmall.in
"forgetPassword": "http://demo.mstore.io/wp-login.php?action=lostpassword" = "forgetPassword": "http://wcfm.bbmall.in/wp-login.php?action=lostpassword" ?

**Comment by vumanhsn97** [comment]
In app: you just change "type":"dokan" to "type":"wcfm"
In wordpress site: you need to install wcfm plugin. Domain is not important!!!

**Comment by ekramul-1** [comment]
What about rest of the issues solution ?

> @ekramul-1
> Add this line in your config https://tppr.me/HKHM7. It will be fix in next version
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/032fc4debc4e9e006371b37ea08168903ac31012/68747470733a2f2f747070722e73332e616d617a6f6e6177732e636f6d2f75706c6f6164732f63616263303832666364383331363361303161396434396637366138333630632e6a7067"><img alt="" height="14" src="/favicon-32x32.png"> tppr.me**[Public - Android Studio_2020-05-20 11-37-19](https://tppr.me/HKHM7)**

Still error is showing

**Comment by ekramul-1** [comment]
> What about rest of the issues solution ?
> 
> > @ekramul-1
> > Add this line in your config https://tppr.me/HKHM7. It will be fix in next version
> > > <img alt="" width="48" src="https://camo.githubusercontent.com/032fc4debc4e9e006371b37ea08168903ac31012/68747470733a2f2f747070722e73332e616d617a6f6e6177732e636f6d2f75706c6f6164732f63616263303832666364383331363361303161396434396637366138333630632e6a7067"><img alt="" height="14" src="/favicon-32x32.png"> tppr.me**[Public - Android Studio_2020-05-20 11-37-19](https://tppr.me/HKHM7)**
> 
> Still error is showing
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/032fc4debc4e9e006371b37ea08168903ac31012/68747470733a2f2f747070722e73332e616d617a6f6e6177732e636f6d2f75706c6f6164732f63616263303832666364383331363361303161396434396637366138333630632e6a7067"><img alt="" height="14" src="/favicon-32x32.png"> tppr.me**[Public - Android Studio_2020-05-20 11-37-19](https://tppr.me/HKHM7)**

![image](https://user-images.githubusercontent.com/63785688/82529949-c0f68f00-9b59-11ea-9d4b-783a75d2fa2f.png)

**Comment by vumanhsn97** [comment]
You lose , after "ProductListLayout": "list" https://tppr.me/oBOK9

**Comment by ekramul-1** [comment]
Not yet fixed the issue please have a look into the issues @minhcasi 

*Product & category, is not showing, but store is showing
*Splash Screen unable to change even though following all the given steps in multivender.
*Unable to connect the FLUXBUILDER even though giving all the correct details s mention in docs,
*MAP not working.
Please have a look into the google form as I uploaded the more in details.

**Comment by minhcasi** [comment]
could you help to share the screenshots issue pls?

**Comment by ekramul-1** [comment]
![image](https://user-images.githubusercontent.com/63785688/83000210-ae7fc800-a027-11ea-8240-5cd20c40a8af.png)

![image](https://user-images.githubusercontent.com/63785688/83000239-b6d80300-a027-11ea-9e41-7b07ac6315c7.png)

**Comment by ekramul-1** [comment]
![image](https://user-images.githubusercontent.com/63785688/83003744-5f886180-a02c-11ea-9732-8fb1305f81ec.png)

**Comment by vumanhsn97** [comment]
@ekramul-1 Add this lines in .htaccess
SetEnvIf Authorization .+ HTTP_AUTHORIZATION=$0
RewriteRule ^wp-json/.* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization},L]

**Comment by ekramul-1** [comment]
I have added this above line inside the wordpress domain .htaccess file but still having same issue.

**Comment by ekramul-1** [comment]
![image](https://user-images.githubusercontent.com/63785688/83025389-979f9c80-a04c-11ea-94fc-55f46d7634c8.png)

**Comment by ekramul-1** [comment]
How to add function.php code inside the child function, their is nothing child function

![image](https://user-images.githubusercontent.com/63785688/83033418-b4d86900-a054-11ea-833e-9bdecb31c30f.png)

**Comment by ekramul-1** [comment]
How I will add this
![image](https://user-images.githubusercontent.com/63785688/83096947-8befbc80-a0c4-11ea-9ea9-014e486b4e81.png)

<?php
/**
 * Astra functions and definitions
 *
 * @link https://developer.wordpress.org/themes/basics/theme-functions/
 *
 * @package Astra
 * @since 1.0.0
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly.
}

/**
 * Define Constants
 */
define( 'ASTRA_THEME_VERSION', '2.4.4' );
define( 'ASTRA_THEME_SETTINGS', 'astra-settings' );
define( 'ASTRA_THEME_DIR', trailingslashit( get_template_directory() ) );
define( 'ASTRA_THEME_URI', trailingslashit( esc_url( get_template_directory_uri() ) ) );


/**
 * Minimum Version requirement of the Astra Pro addon.
 * This constant will be used to display the notice asking user to update the Astra addon to latest version.
 */
define( 'ASTRA_EXT_MIN_VER', '2.5.0' );

/**
 * Setup helper functions of Astra.
 */
require_once ASTRA_THEME_DIR . 'inc/core/class-astra-theme-options.php';
require_once ASTRA_THEME_DIR . 'inc/core/class-theme-strings.php';
require_once ASTRA_THEME_DIR . 'inc/core/common-functions.php';

/**
 * Update theme
 */
require_once ASTRA_THEME_DIR . 'inc/theme-update/class-astra-theme-update.php';
require_once ASTRA_THEME_DIR . 'inc/theme-update/astra-update-functions.php';
require_once ASTRA_THEME_DIR . 'inc/theme-update/class-astra-theme-background-updater.php';
require_once ASTRA_THEME_DIR . 'inc/theme-update/class-astra-pb-compatibility.php';


/**
 * Fonts Files
 */
require_once ASTRA_THEME_DIR . 'inc/customizer/class-astra-font-families.php';
if ( is_admin() ) {
	require_once ASTRA_THEME_DIR . 'inc/customizer/class-astra-fonts-data.php';
}

require_once ASTRA_THEME_DIR . 'inc/customizer/class-astra-fonts.php';

require_once ASTRA_THEME_DIR . 'inc/core/class-astra-walker-page.php';
require_once ASTRA_THEME_DIR . 'inc/core/class-astra-enqueue-scripts.php';
require_once ASTRA_THEME_DIR . 'inc/core/class-gutenberg-editor-css.php';
require_once ASTRA_THEME_DIR . 'inc/class-astra-dynamic-css.php';

/**
 * Custom template tags for this theme.
 */
require_once ASTRA_THEME_DIR . 'inc/core/class-astra-attr.php';
require_once ASTRA_THEME_DIR . 'inc/template-tags.php';

require_once ASTRA_THEME_DIR . 'inc/widgets.php';
require_once ASTRA_THEME_DIR . 'inc/core/theme-hooks.php';
require_once ASTRA_THEME_DIR . 'inc/admin-functions.php';
require_once ASTRA_THEME_DIR . 'inc/core/sidebar-manager.php';

/**
 * Markup Functions
 */
require_once ASTRA_THEME_DIR . 'inc/extras.php';
require_once ASTRA_THEME_DIR . 'inc/blog/blog-config.php';
require_once ASTRA_THEME_DIR . 'inc/blog/blog.php';
require_once ASTRA_THEME_DIR . 'inc/blog/single-blog.php';
/**
 * Markup Files
 */
require_once ASTRA_THEME_DIR . 'inc/template-parts.php';
require_once ASTRA_THEME_DIR . 'inc/class-astra-loop.php';
require_once ASTRA_THEME_DIR . 'inc/class-astra-mobile-header.php';

/**
 * Functions and definitions.
 */
require_once ASTRA_THEME_DIR . 'inc/class-astra-after-setup-theme.php';

// Required files.
require_once ASTRA_THEME_DIR . 'inc/core/class-astra-admin-helper.php';

require_once ASTRA_THEME_DIR . 'inc/schema/class-astra-schema.php';

if ( is_admin() ) {

	/**
	 * Admin Menu Settings
	 */
	require_once ASTRA_THEME_DIR . 'inc/core/class-astra-admin-settings.php';
	require_once ASTRA_THEME_DIR . 'inc/lib/notices/class-astra-notices.php';

	/**
	 * Metabox additions.
	 */
	require_once ASTRA_THEME_DIR . 'inc/metabox/class-astra-meta-boxes.php';
}

// BSF Analytics library.
require_once ASTRA_THEME_DIR . 'admin/bsf-analytics/class-bsf-analytics.php';

require_once ASTRA_THEME_DIR . 'inc/metabox/class-astra-meta-box-operations.php';


/**
 * Customizer additions.
 */
require_once ASTRA_THEME_DIR . 'inc/customizer/class-astra-customizer.php';


/**
 * Compatibility
 */
require_once ASTRA_THEME_DIR . 'inc/compatibility/class-astra-jetpack.php';
require_once ASTRA_THEME_DIR . 'inc/compatibility/woocommerce/class-astra-woocommerce.php';
require_once ASTRA_THEME_DIR . 'inc/compatibility/edd/class-astra-edd.php';
require_once ASTRA_THEME_DIR . 'inc/compatibility/lifterlms/class-astra-lifterlms.php';
require_once ASTRA_THEME_DIR . 'inc/compatibility/learndash/class-astra-learndash.php';
require_once ASTRA_THEME_DIR . 'inc/compatibility/class-astra-beaver-builder.php';
require_once ASTRA_THEME_DIR . 'inc/compatibility/class-astra-bb-ultimate-addon.php';
require_once ASTRA_THEME_DIR . 'inc/compatibility/class-astra-contact-form-7.php';
require_once ASTRA_THEME_DIR . 'inc/compatibility/class-astra-visual-composer.php';
require_once ASTRA_THEME_DIR . 'inc/compatibility/class-astra-site-origin.php';
require_once ASTRA_THEME_DIR . 'inc/compatibility/class-astra-gravity-forms.php';
require_once ASTRA_THEME_DIR . 'inc/compatibility/class-astra-bne-flyout.php';
require_once ASTRA_THEME_DIR . 'inc/compatibility/class-astra-ubermeu.php';
require_once ASTRA_THEME_DIR . 'inc/compatibility/class-astra-divi-builder.php';
require_once ASTRA_THEME_DIR . 'inc/compatibility/class-astra-amp.php';
require_once ASTRA_THEME_DIR . 'inc/compatibility/class-astra-yoast-seo.php';
require_once ASTRA_THEME_DIR . 'inc/addons/transparent-header/class-astra-ext-transparent-header.php';
require_once ASTRA_THEME_DIR . 'inc/addons/breadcrumbs/class-astra-breadcrumbs.php';
require_once ASTRA_THEME_DIR . 'inc/addons/heading-colors/class-astra-heading-colors.php';
require_once ASTRA_THEME_DIR . 'inc/class-astra-filesystem.php';

// Elementor Compatibility requires PHP 5.4 for namespaces.
if ( version_compare( PHP_VERSION, '5.4', '>=' ) ) {
	require_once ASTRA_THEME_DIR . 'inc/compatibility/class-astra-elementor.php';
	require_once ASTRA_THEME_DIR . 'inc/compatibility/class-astra-elementor-pro.php';
}

// Beaver Themer compatibility requires PHP 5.3 for anonymus functions.
if ( version_compare( PHP_VERSION, '5.3', '>=' ) ) {
	require_once ASTRA_THEME_DIR . 'inc/compatibility/class-astra-beaver-themer.php';
}

/**
 * Load deprecated functions
 */
require_once ASTRA_THEME_DIR . 'inc/core/deprecated/deprecated-filters.php';
require_once ASTRA_THEME_DIR . 'inc/core/deprecated/deprecated-hooks.php';
require_once ASTRA_THEME_DIR . 'inc/core/deprecated/deprecated-functions.php';

**Comment by ekramul-1** [comment]
Please tell me solution for this issue

![image](https://user-images.githubusercontent.com/63785688/83103540-8601d780-a0d4-11ea-9f21-027b3db2136f.png)

**Comment by minhcasi** [comment]
@ekramul-1 - as you can see the team is very active to support you, there are some issues with your setting from the Wordpress site that cause the issue - could you able to share the admin login to hi@inspireui.com - our backend team will help for checking the issue.


Please also help to update our rating to continue getting support from us - thank you for your time 😅

**Comment by ekramul-1** [comment]
Thank you @minhcasi for you quick support, I am changing the rating. 
I have send the details in above mention email.

**Comment by minhcasi** [comment]
@ekramul-1 - thank you for quick response, please share your detail info via email

**Comment by ekramul-1** [comment]
I have mailed to this email - hi@inspireui.com

**Comment by philipvu30** [comment]
Hi,

Would you mind changing your .httpacess file refer to this [answer](https://github.com/WP-API/Basic-Auth/issues/35#issuecomment-431422771) and try again?

And this issue is caused by the JWT authentication plugin. I have it disabled and that error is no longer shows up.

**Comment by ekramul-1** [comment]
Nging I am not using, hope everything is done & now I will be able to customize.
Thank you so much for your time and support.

**Comment by philipvu30** [comment]
I'm sorry I was mistyped. It's supposed to be .htaccess file

Here is our demo wcfm website .htaccess. You can refer to it to fix this issue as this is related to the server-side.
[htaccess.zip](https://github.com/inspireui/support/files/4695067/htaccess.zip)

**Comment by ekramul-1** [comment]
Please don't mind, for you it's really easy but as I am non coder, quite hard & that is the reason I disturbing you.

Please have a look into this .htaccess file.

[htaccess (1).zip](https://github.com/inspireui/support/files/4695455/htaccess.1.zip)

**Comment by ekramul-1** [comment]
Now Fluxbuilder also not working, before it was connecting & showing all checked.

![image](https://user-images.githubusercontent.com/63785688/83141223-ef054180-a10c-11ea-98f7-1f363da9d9f2.png)

**Comment by ekramul-1** [comment]
But in fluxbuilder is not working
![image](https://user-images.githubusercontent.com/63785688/83153282-68586080-a11c-11ea-926e-b7b6aab290dd.png)

**Comment by ekramul-1** [comment]
Please have a look @minhcasi ### @philipvu30 into this as I am waiting everyday for your response.
Please try to understand as **priority !!! basis**

**Comment by philipvu30** [comment]
Hi,

I managed to determine what is your problem right now. Your website has an issue with SSL configuration. 
If you have enabled the SSL, then you don't need to use the oAuth1 method to get the data. But in your case, although you've already enabled it, I must use oAuth1 to get your data. You can see the image below.
![image](https://user-images.githubusercontent.com/54442328/83215300-d76f9c80-a190-11ea-84d7-7687a5e0aecc.png)

This issue is nothing related to our app, would you mind checking your website configuration again? It could be some of your plugins already modified the .htaccess. As you said you are an expert in WordPress, can you help us? Because we are not experienced much with it.

**Comment by ekramul-1** [comment]
### @philipvu30  Sir/madam, please fix this by your side I urge you as I am unable to recognize the issue & I am not the expert in wordpress configuration please fix this, I have SSL enabled & please tell me what are the plugin I need to uninstall, either please help me to fix or uninstall all the plugin by your side.

**Comment by ekramul-1** [comment]
@philipvu30  Sir/madam, please fix this by your side I urge you as I am unable to recognize the issue & I am not the expert in wordpress configuration please fix this, I have SSL enabled & please tell me what are the plugin I need to uninstall, either please help me to fix or uninstall all the plugin by your side.

**Comment by philipvu30** [comment]
Hi,

Please use these config.dart and config_en.json as references.

[config.dart](https://github.com/inspireui/support/files/4699664/config.dart.zip)
[config_en.json](https://github.com/inspireui/support/files/4699665/config_en.json.zip)

**Comment by ekramul-1** [comment]
> Hi,
> 
> Please use these config.dart and config_en.json as references.
> 
> [config.dart](https://github.com/inspireui/support/files/4699664/config.dart.zip)
> [config_en.json](https://github.com/inspireui/support/files/4699665/config_en.json.zip)

Thank you @philipvu30

**Comment by ekramul-1** [comment]
Dear @philipvu30 , I don't have words to appreciate you really, Thank you so much for your hard work, finally it's done I am extremely happy full to joy. Now I will be able to customize.
Big thanks once again.

**Comment by minhcasi** [comment]
you are welcome 🎉

**Comment by ekramul-1** [comment]
After customizing from fluxbuilder, I copied the scripts & updated in config_en.json file & not working while emulate,
Later I tried to in config.json file also & not working, I checked the https://docs.inspireui.com/fluxstore/multi-vendor/ & tried to follow but still not working.

Please tell me that I will able to customise & update.
Thank you
