### ISSUE TITLE
[fluxstore Pro Woocomerce] Redirect to home page after logout

### ISSUE THREAD

**Issue by tjain90** [inspireui/support#3282]
Step 1 (require): detail issues and screenshots
How to redirect customer to home page or give message that they have logged out successfully. Right now nothing happens and we don't even know if it is logged out post pressing logout button.

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@tjain90 - thank you for the great feedback, we will upgrade this UX on later upgrade

**Comment by minhcasi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Redirect to home page after logout](https://trello.com/c/obPelhoV/46-redirect-to-home-page-after-logout)

**Comment by minhcasi** [comment]
moved to team backlog for investigating & updating
