### ISSUE TITLE
[FluxstorePro Woocomerce] Use .webp images for all images 

### ISSUE THREAD

**Issue by tjain90** [inspireui/support#3283]
Step 1 (require): detail issues and screenshots
Right now webp images are used for banner which we provide manually on home config. Is there any way that we can use webp for all images of products to make app much faster and reliable. I am using webpexress plugin on my website. 

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@tjain90 - we also use the Webp for the demo app, there are no problems, it will be loaded automatically - thank you!

**Comment by tjain90** [comment]
Any way to check if app is loading webp images . Because it seems to be slow, i guess it is loading normal images.

**Comment by minhcasi** [comment]
@tjain90 - you could try to add `.webp` into the end of image URL if using the, the Flutter is also supported webp as well. 

Let us know your checking

**Comment by minhcasi** [comment]
Please help us to add your all comment to one ticket, our team will keep the update and get back you shortly, pls move to #3313 - thank you for your time
