### ISSUE TITLE
Error is shown in products with variants configured (FluxStore MV)

### ISSUE THREAD

**Issue by mauriciozuniga** [inspireui/support#3285]
When I have products configured with some variants on WooCommerce, the application does not load them and show me an error: **Error in type '_oneByteString' is not a subtype of type 'int'.**.
Even with a "simple" color variable, application does not show them.
I am attaching a screenshot of how it displays on web, and the ERROR that I see on application.

<img width="1329" alt="82251449-d62dac80-9912-11ea-95c6-9d1a46274a78" src="https://user-images.githubusercontent.com/8905579/82288241-a9f04b00-9967-11ea-9193-ff45c640f9e6.png">

Also, I'm pasting at the end o f this message the stack trace with the Exception thrown in Android studio.
Also, the screenshot of an example of product configuration on wp admin. 
<img width="1309" alt="82251652-345a8f80-9913-11ea-8663-5f9b31ddacd5" src="https://user-images.githubusercontent.com/8905579/82288255-b4124980-9967-11ea-9a29-a9a4a69d5f89.png">

Exception thrown
════════ Exception caught by widgets library ════════════════════════════
The following _TypeError was thrown building ProductVariant(dirty, dependencies: [_InheritedTheme, _LocalizationsScope-[GlobalKey#4b02c]], state: StateProductVariant#bfc14):
type 'String' is not a subtype of type 'int'

The relevant error-causing widget was:
ProductVariant file:///Users/maozuniga/Documents/Desarrollo/FluxStore-vendor-1.7.0/source/lib/screens/detail/themes/simple_type.dart:169:43
When the exception was thrown, this was the stack:
#0 WooVariantMixin.getProductAttributeWidget (package:fstore/widgets/frameworks/woocommerce/woo_variant_mixin.dart:112:52)
#1 StateProductVariant.getProductAttributeWidget (package:fstore/screens/detail/product_variant.dart:139:28)
#2 StateProductVariant.build (package:fstore/screens/detail/product_variant.dart:164:12)
#3 StatefulElement.build (package:flutter/src/widgets/framework.dart:4334:27)
#4 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4223:15)
...

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by vumanhsn97** [comment]
@mauriciozuniga You create this bug. In common/config/products.dart, you change ProductVariantLayout from Map to List ??? https://tppr.me/ngCpN. Please return to Map look like this https://tppr.me/CLktY
Error fixed. https://tppr.me/3hRED

**Comment by mauriciozuniga** [comment]
Please attach the image on how does it needs to look, the link you posted as the second image doesn´t show anything. (Map?) I didn´t change any code, but if I can change something to fix it according to your instructions, I will gladly do it.
Thnks
