### ISSUE TITLE
updates to flexstore

### ISSUE THREAD

**Issue by echostorm** [inspireui/support#3286]
I have been mostly working with this version of flexstore 1.6.6b and am mostly done with with my app however the latest version I downloaded today was flexstore 1.7.3 was wondering if there is any tutorial or any script to enable me to easily update to latest version of flextore code?

What options do I have to make sure I can update my project?

**Comment by minhcasi** [comment]
@echostorm - sorry we don't have the auto way for upgrading the version, we are adding a new video to guide you on how to manage the Gitlab effective to due with the new version update, please keep subscribe to http://youtube.com/inspireui - thank you!
