### ISSUE TITLE
[Fluxnews] Youtube Embed not showing correctly

### ISSUE THREAD

**Issue by bidfor** [inspireui/support#3287]
Step 1 (require): detail issues and screenshots

![image](https://user-images.githubusercontent.com/2523772/82292729-f9715e00-99dd-11ea-8908-02a4f4d58891.png)

**Comment by minhcasi** [comment]
@bidfor - could i check if you are using iframe or shortcode - the current release only support iframe youtube - thank you!

**Comment by bidfor** [comment]
I'm using iframe, the embed feature in the Wordpress. 

![image](https://user-images.githubusercontent.com/2523772/82398782-35f89480-9a86-11ea-962b-58090aab60c8.png)

**Comment by minhcasi** [comment]
Could you share the website URL here? Thanks

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
