### ISSUE TITLE
Show a notification unread messages.

### ISSUE THREAD

**Issue by mmasifashraf** [inspireui/support#3288]
Hi,
I would like to show a notification if there is any unread messages in the notification folder.
is it possible?

 
![notifcation](https://user-images.githubusercontent.com/44862509/82307495-18b1c080-99c9-11ea-84d4-5a69ed8bf75a.png)

**Comment by minhcasi** [comment]
it's possible by managing the Unread message, you could try with the implementing and share with us 👍

**Comment by minhcasi** [comment]
@mmasifashraf - we will keep in post open #3279 - pls post all questions there - thank you!
