### ISSUE TITLE
Fluxstore.

### ISSUE THREAD

**Issue by qorane099** [inspireui/support#3289]
Dear @minhtruong315, the checkout issue is still there, the original source has no issue and its checkout is working fine but when l do connect to my dokan website, then the checkout is not working.

please note that the website has payment method like bank and cash on delivery.

also, l need to know, what are the best way to update the old source to new version 1.17 without writing and customersing the whole source.

my old source has everything, l did customersized and allowed social login, how can l update that old source.

or do l have to download the new source and customer and allow social login from the begining

Ref: issue number #3067
![IMG_20200322_005709](https://user-images.githubusercontent.com/39888242/82310157-a7cad280-99e1-11ea-9c5f-cb44a56873f6.jpg)

**Comment by minhcasi** [comment]
@qorane099 - we are in middle to create a new video to clarify how to manage the git with a new version upgrade, most of the task is updated manually - we don't have the best way without using Git, please help to subscribe to http://youtube.com/inspireui

**Comment by minhcasi** [comment]
@qorane099  - please help to use this guide to manage your project via Git

Video: https://drive.google.com/drive/folders/1kFLOwuzccrh2nxcVhn_m6OzOQrYfXoiX?usp=sharing
Docs: https://github.com/inspireui/support/wiki/Guide-to-using-git-to-work-repo-Fluxstore-pro

Content:
    FORK GIT FLUXSTORE 			:	 00:00 - 05:22
    INSTALL SOURCETREE			:	 05:23 - 08:27
    MERGE CODE - NO CONFLICT	: 	 08:28 - 10:56
    MERGE CODE - CONFLICT		:	 10:57  - 13:37

Let us know if you have any questions

**Comment by qorane099** [comment]
can you please add me:

FluxStore-Pro repo to update from FluxStore-PRo website
