### ISSUE TITLE
[MStore] after updating config.js app still showing old data

### ISSUE THREAD

**Issue by Hamzanisar** [inspireui/support#329]
**Required Info (please complete the following information):**
 - Product: [MStore]
 - Your Purchased Code: [ff661203-9b77-4e4f-b8e8-d6ba3025b834]
(we may not reply if you are not our customer)

**Describe the bug**
as per provided instruction i have installed admin panel on live server then create api to connect app in cebuilder i update my api keys everything even update also config.js but when i compile application its shows old data demo data which provided from your site even i tested make order but nothing get in my admin panel app is getting data working with an demo api after updating config.js as well please tell me 

**Screenshots**

**Additional context**
Add any other detail logs about the problem here.
If possible please share your config.js that use for the app setting

**Comment by Hamzanisar** [comment]
config.js
https://jsfiddle.net/usywj02h/

AppConfig.js
https://jsfiddle.net/r9ojpfnk/

**Comment by luyx2412** [comment]
HI @Hamzanisar Please uninstall your app or expo, after that reinstall again. The data stored by redux.

Thanks

**Comment by Hamzanisar** [comment]
im using windows and what is redux

**Comment by Hamzanisar** [comment]
compiling application through cebuilder your provided software

**Comment by luyx2412** [comment]
Hi @Hamzanisar this is the tutorial redux https://redux.js.org/ and redux-persist https://github.com/rt2zz/redux-persist

Thanks

**Comment by Hamzanisar** [comment]
but actually i don't understand why are you recommend me this framework i purchased your app just for save my time for development but you are moving me to develop so this is ridiculous. Please provide me way to fix your app.

**Comment by Hamzanisar** [comment]
as you said i reinstall everything clear cache of emulator and update my wordpress woocommerce plugins but now image and data is not showing. I searched in old comments with other user where you mentioned about regenerate thumbnail i tried it already so i'm expecting better response now.

My Config.js
https://jsfiddle.net/4L2v3s0p/

AppConfig.js
https://jsfiddle.net/ktd2f8up/

Screenshot of app
https://imgur.com/V9Wfqxd

**Comment by Hamzanisar** [comment]
everything is working fine now no need of you

**Comment by luyx2412** [comment]
Closed!
