### ISSUE TITLE
Push notification is not working in version 1.7.3

### ISSUE THREAD

**Issue by TirthrajRao** [inspireui/support#3290]
Hello,

I am using fluxstore version 1.7.3.  
I have followed all the steps described in this video, [https://youtu.be/rFCcWNRPrSk](url).  But is is not working in IOS.

I am getting all messages in "Notify messages" tab but push notifications are not working.

Please check. I have updated all details in the form.

**Comment by minhcasi** [comment]
@TirthrajRao - pls also help to check the detail here https://medium.com/@inspireui/setup-firebase-cloud-messaging-fcm-push-notification-for-flutter-apps-8c767fe64e54 

You could only test on Real device + after purchasing the Apple Developer from apple

**Comment by TirthrajRao** [comment]
@minhcasi I have already followed this guide but still I am unable to receive push notifications.

I am testing on real device only. 

Please help

**Comment by minhcasi** [comment]
@TirthrajRao - are you using the Paid Apple Developer account(99$/year) from Apple? - thank you!

**Comment by TirthrajRao** [comment]
@minhcasi Yes, I have paid account in Apple Developer. 

Please resolve it as soon as possible.

**Comment by TirthrajRao** [comment]
Hello @minhcasi  any update ?

**Comment by minhcasi** [comment]
@TirthrajRao - please help to try to restart the integrate by following this video step by step to see if you have missed any important step? - https://www.youtube.com/watch?time_continue=19&v=rFCcWNRPrSk

**Comment by TirthrajRao** [comment]
Hello @minhcasi , Why are you sending me the same video every time ? I told you that I have followed every steps mentioned. I have already crossed my deadline and my client is waiting for more than 3 days. I need a concrete solution now. I also got an email from firebase about deprecation of API. I am attaching the screenshot here.

Please look into it and resolve the issue as soon as possible.

![oie_m3F61uI6CrAZ](https://user-images.githubusercontent.com/50260585/82661032-e44c3780-9c48-11ea-8e5a-e9890892765b.png)

**Comment by minhcasi** [comment]
+ There are important steps setup the APN - could you confirm it is done?
+ Make sure to test on Real iPhone as the simulator will not work
+ Try to add my email minhcasi@gmail.com to firebase for quick checking.

Related ticket #3229

**Comment by TirthrajRao** [comment]
@minhcasi I have changed my APN certificates for two times and I am testing on real iPhone only.

Also I have added you in the Firebase project. Please check.

**Comment by TirthrajRao** [comment]
Hello @minhcasi,
Have you checked the firebase project ? Is there any issue ? Please update me...

**Comment by minhcasi** [comment]
it looks oki with your Firebase setting, it could relate to the issue you have shared above. @trunghieuvn - do you have any suggestion on this issue?

There is also another approach by using OneSignal push notification that available on `1.7.4`, you could try this solution as well.

**Comment by TirthrajRao** [comment]
@minhcasi Are you sure 1.7.4 with one signal will fix the issue ?

**Comment by minhcasi** [comment]
Yes, please give a try

**Comment by minhcasi** [comment]
Confirmed, it is working perfectly - let us know if you have any further question :)
