### ISSUE TITLE
Product options not mandatory + price between brackets

### ISSUE THREAD

**Issue by midotaha** [inspireui/support#3292]
**Hi My Dear Sir/Mrs 
Greetings !! 
i have 3 small issues 
1- Product options not mandatory , i want to make it mandatory ,customer must be forced to select it, without skip it or add product to cart without specification . you can check next screenshot .**
![001](https://user-images.githubusercontent.com/19406537/82314381-67b02380-99d2-11ea-87d5-91c407abd1c8.png)

**2- price between brackets make customers Confused , i want to hide it (price between brackets) , i want to hide prices that contain  (+)&(-) or zero beside price you can check next 2 screenshots.**
![002](https://user-images.githubusercontent.com/19406537/82314406-71398b80-99d2-11ea-96e3-b74fa2c66d08.png)
![003](https://user-images.githubusercontent.com/19406537/82314411-73034f00-99d2-11ea-9266-a380d5e6d36e.png)

**3- when i change app to English interface , App still fetching Arabic words from website, this appears to me at product options clearly , also you can check the previous screenshots, You can notice that,,,
can you tell me what is file can i edit and what is  the right code should be put to fix this issues
Many thanks for you**

**Comment by minhcasi** [comment]
@midotaha - these features are required to customize, I've marked the ticket as Feature Request and sent to the team to investigate, thank you for your feedback!

**Comment by minhcasi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [UX: Product mandatory options](https://trello.com/c/qHKaZAX4/47-ux-product-mandatory-options)

**Comment by minhcasi** [comment]
moved to team backlog for further upgrade
