### ISSUE TITLE
[FluxStore MV] Sold by on product page not available with WCFM

### ISSUE THREAD

**Issue by djks74** [inspireui/support#3295]
Hi,
I dont see "sold by" on single product page,
based on WCFM, it showing vendor name and when click it goes to vendor page.

Plase add it. Thanks

**Comment by minhcasi** [comment]
@djks74 - thank you for your suggestion, we have noted and will keep this upgrade - thank you!

**Comment by djks74** [comment]
Thanks Minh,
Sorry, should I add new request for whatsapp / smashchat should adding per vendors phone number?
or here should fine to add this request together?

Also firebase chat on product page would be great! Thanks.

Sandi

**Comment by djks74** [comment]
While the ticket #3310 is closed (which should be different actually)
anyway,
I will add the different issue here then.
this one is shipping method :

I use woogosend shipping method, its showing but seems its not calculate and shipping fee is 0.
Im using webview checkout now, but hopefully it could be fixed on the next update.

I think because the address we input on address checkout is not filled to woocommerce address in API, so maybe thats why its not showing calculation.

here is the plugin :
https://wordpress.org/plugins/woogosend/

Meanshile, I bypass using enable onepage checkout to webview.

Hope the shipping method is addes for woogosend calculation on checkout.

but I prefer IsmpireUI adding the "Sold by" and smashchat link to vendors phone number first if possible. Thanks.

**Comment by philipvu30** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Integrate "Sold by" merchant](https://trello.com/c/XK1LYVOl/48-integrate-sold-by-merchant)

**Comment by philipvu30** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add individual SmartChat for each merchant](https://trello.com/c/3UZU0rQU/49-add-individual-smartchat-for-each-merchant)

**Comment by philipvu30** [comment]
Hi,

Your requests are moved to our backlogs. 

About the shipping method/plugin you are using, we are sorry to say this but we only support the default shipping method provided by WooCommerce. 
Because this is a global app, we cannot fulfill every single request from all users. You can seek for someone that is able to assist you in customizing the app to meet your need.

Thank you for using our product.

**Comment by djks74** [comment]
Hi,
sorry, it mean fixed or still developing for sold by and smartchat?

**Comment by philipvu30** [comment]
Hi,

It is under development.

**Comment by djks74** [comment]
Ok Philip thanks alot.
also just to remind that products not showing all in store/merchant stores. (only showing 10 products)
make sure it fixed. Thanks alot. :-)
