### ISSUE TITLE
FluxStore pro - 1.7.3 - home page load take 10 second.

### ISSUE THREAD

**Issue by huntelar10** [inspireui/support#3296]
Step 1 (require): detail issues and screenshots

comparing 1.7.3 version with one before , after add load animation , app loading
slow.
this what android studio give me 

[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: setState() called after dispose(): _PinterestLayoutState#924a1(lifecycle state: defunct, not mounted)
This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
#0      State.setState.<anonymous closure> (package:flutter/src/widgets/<…>
flutter: [2020-05-19 13:04:40.459930Z][Fluxstore][wocommerce_api][17:04:40.459754] getAsync END [endPoint:products?lang=ar&status=publish&category=772] url:products?lang=ar&status=publish&category=772
flutter: [2020-05-19 13:04:40.612931Z][Fluxstore][wocommerce_api][17:04:40.612805] getAsync END [endPoint:products/attributes] url:products/attributes

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

i was verify my license with issue number #3006 

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@huntelar10 - pls try to run the ReGenerate image by using this guide - https://docs.inspireui.com/fluxstore/performance/#2-image-optimization - and enable below option 

<img width="762" alt="Screen Shot 2020-05-20 at 15 42 16" src="https://user-images.githubusercontent.com/1459805/82425268-7c62e900-9ab0-11ea-8e96-ecf68242616c.png">

**Comment by huntelar10** [comment]
Dear @minhcasi i was do what you told me and i update all package in pubspec.yaml
and now app much better take 4-6 second to load product in home page
thank you

**Comment by minhcasi** [comment]
@huntelar10 - thank you for quick response, we are working hard to upgrade it faster on next release, let us know if you have any further issues.

You could also try to upload the config_en.json to your website, install the Rest API Cache, enable the `isCaching: true` - it will be load faster, 1-2s

Very best!

**Comment by harjono-flux** [comment]
> @huntelar10 - thank you for quick response, we are working hard to upgrade it faster on next release, let us know if you have any further issues.
> 
> You could also try to upload the config_en.json to your website, install the Rest API Cache, enable the `isCaching: true` - it will be load faster, 1-2s
> 
> Very best!

Sory, if i use lite speed cache, is the same?
