### ISSUE TITLE
A problem in the Arabic language

### ISSUE THREAD

**Issue by abbasfendi** [inspireui/support#3298]
Step 1 (require): detail issues and screenshots

![image](https://user-images.githubusercontent.com/48460530/82525118-52a1d480-9b39-11ea-9d09-a57641dbd0b8.png)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

hi
A problem in the Arabic language

How do I make the application completely Arabic

Consider the title does not appear in the Arabic language
*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by abbasfendi** [comment]
Hello
Is there a solution to the problem?

**Comment by luyx2412** [comment]
Hi @abbasfendi Can you give me the screenshot about Arabic language?

Thanks

**Comment by minhcasi** [comment]
@abbasfendi - could i confirm you are rating the ticket for which product? Mstore or Fluxstore?

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
