### ISSUE TITLE
[Fluxstorepro Woocomerce]- Native Razorpay not working

### ISSUE THREAD

**Issue by tjain90** [inspireui/support#3299]
Step 1 (require): detail issues and screenshots

I have updated my app to 1.7.4 and native Razorpay is not working. It is redirecting to webpage with one page checkout. I want to have native checkout.

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@tjain90 - we will review this library again and will confirm if it is ready for integration - thank you!

**Comment by tjain90** [comment]
Meanwhile can you let us know how to autofill address and name in webview. Because right now when customer has already filled there address they need to fill that again when they select razorpay?? Which is very much repitative task as per customer.

**Comment by minhcasi** [comment]
@tjain90 - we have some deep review and find out one issue on latest Razorpay lib - https://github.com/razorpay/razorpay-flutter/issues/74 - if could success install, you could use for your app, the code+features are still keeping as a comment code, try to un-comment and use it :)

I've reported the address issues to the team, there is a new release 1.7.4 will be ready shortly - thank you!

Please help us to add your all comment to one ticket, our team will keep the update and get back you shortly, pls move to #3313 - thank you for your time
