### ISSUE TITLE
[Mstore] Mstore home page blank

### ISSUE THREAD

**Issue by SalamMohammed** [inspireui/support#33]
Hello 
I installed Mstore pro using expo. everything works fine by following the instruction that you posted. but there is a problem in the home page for the of the app.
the picture does't show at all only in the home page. I made sure of the Better feature image installed. I update enable: false and then true but still the same.
it shows the category id is 21 or 18 so what is the connection between these numbers and my actual categories because mine are not 21. 
I tried to add tags 273 and 21 but they never showed. 
pleases will you help me 
because your explanation in the document are not so much clear 
best regards

**Comment by minhcasi** [comment]
Could you share your config.js file so that we could help for checking

**Comment by SalamMohammed** [comment]
Do you want me to send it here ?

**Comment by SalamMohammed** [comment]
/** @format */

import Images from "./Images";
import Constants from "./Constants";
import Icons from "./Icons";

export default {
  /**
     Step 1: change to your website URL and the wooCommerce API consumeKey
     */
  WooCommerce: {
    url: "http://first-lady.store",
    consumerKey: "ck_874001271a2ce6c1f00ddd0f3c830e7bf092638d",
    consumerSecret: "cs_b8a18dbdafe588c0860cb103ea070f840ab40c75",
  },

  /**
     Step 2: Setting Product Images
     - ProductSize: Explode the guide from: update the product display size: https://mstore.gitbooks.io/mstore-manual/content/chapter5.html
     The default config for ProductSize is disable due to some problem config for most of users.
     If you have success config it from the Wordpress site, please enable to speed up the app performance
     - HorizonLayout: Change the HomePage horizontal layout - https://mstore.gitbooks.io/mstore-manual/content/chapter6.html
       Update Oct 06 2018: add new type of categories
       NOTE: name is define value --> change field in Language.js
     */
  ProductSize: {
    enable: false,
    CatalogImages: { width: 300, height: 360 },
    SingleProductImage: { width: 600, height: 720 },
    ProductThumbnails: { width: 180, height: 216 },
  },

  HorizonLayout: [
    // Update 07 Oct 2018: support more Banner layout, HTML, category
    { tag: 273, layout: Constants.Layout.Banner },
    {
       layout: Constants.Layout.circle,
       items: [
         {category: 18, image : require("@images/categories_icon/ic_shorts.png"), colors: ["#4facfe", "#00f2fe"] },
         {category: 21, image : require("@images/categories_icon/ic_tshirt.png"), colors: ["#43e97b", "#38f9d7"] },
         {category: 208, image : require("@images/categories_icon/ic_panties.png"), colors: ["#fa709a", "#fee140"] },
         {category: 26, image : require("@images/categories_icon/ic_dress.png"), colors: ["#7F00FF", "#E100FF"] },
         {category: 24, image : require("@images/categories_icon/ic_glasses.png"), colors: ["#30cfd0", "#330867"] },
         {category: 212, image : require("@images/categories_icon/ic_shoes.png"), colors: ["#2af598", "#009efd"] },
         {category: 213, image : require("@images/categories_icon/ic_tie.png"), colors: ["#6a11cb", "#2575fc"] },
         {category: 211, image : require("@images/categories_icon/ic_socks.png"), colors: ["#c471f5", "#fa71cd"] },
         {category: 210, image : require("@images/categories_icon/ic_woman_shoes.png"), colors: ["#f43b47", "#453a94"] },
       ]
    },
    {
      name: "منتجات مختارة",
      category: 21,
      image: Images.Banner.Feature,
      layout: Constants.Layout.threeColumn,
    },
    {
      name: "bagsCollections",
      category: 23,
      image: Images.Banner.Bag,
      layout: Constants.Layout.twoColumn,
    },
    {
      name: "womanBestSeller",
      category: 22,
      image: Images.Banner.Woman,
      layout: Constants.Layout.twoColumnHigh,
    },
    {
      name: "manCollections",
      category: 18,
      image: Images.Banner.Man,
      layout: Constants.Layout.card,
    },
  ],

  /**
     step 3: Config image for the Payment Gateway
     Notes:
     - Only the image list here will be shown on the app but it should match with the key id from the WooCommerce Website config
     - It's flexible way to control list of your payment as well
     Ex. if you would like to show only cod then just put one cod image in the list
     * */
  Payments: {
    // bacs: require("@images/payment_logo/PayPal.png"),
    cod: require("@images/payment_logo/cash_on_delivery.png"),
    paypal: require("@images/payment_logo/PayPal.png"),
    stripe: require("@images/payment_logo/stripe.png"),
  },

  /**
     Step 4: Advance config:
     - showShipping: option to show the list of shipping method
     - showStatusBar: option to show the status bar, it always show iPhoneX
     - LogoImage: The header logo
     - LogoWithText: The Logo use for sign up form
     - LogoLoading: The loading icon logo
     - appFacebookId: The app facebook ID, use for Facebook login
     - CustomPages: Update the custom page which can be shown from the left side bar (Components/Drawer/index.js)
     - WebPages: This could be the id of your blog post or the full URL which point to any Webpage (responsive mobile is required on the web page)
     - CategoryListView: default layout for category (true/false)
     - intro: The on boarding intro slider for your app
     - menu: config for left menu side items (isMultiChild: This is new feature from 3.4.5 that show the sub products categories)
     * */
  shipping: {
    visible: true,
    time: {
      free_shipping: "4 - 7 Days",
      flat_rate: "1 - 4 Days",
      local_pickup: "1 - 4 Days",
    },
  },
  showStatusBar: true,
  LogoImage: require("@images/2.png"),
  LogoWithText: require("@images/2.png"),
  LogoLoading: require("@images/Icon.png"),

  showAdmobAds: false,
  AdMob: {
    deviceID: "pub-2101182411274198",
    unitID: "ca-app-pub-2101182411274198/4100506392",
    unitInterstitial: "ca-app-pub-2101182411274198/8930161243",
    isShowInterstital: true,
  },
  appFacebookId: "422035778152242",
  CustomPages: { contact_id: 10941 },
  WebPages: { marketing: "http://first-lady.store" },


  intro: [
    {
      key: "page1",
      title: "Lorem Ipsum Dolor Sit Ame",
      text:
        "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      icon: "ios-basket-outline",
      colors: ["#0FF0B3", "#036ED9"],
    },
    {
      key: "page2",
      title: "Consectetur Adipisicing Elit Sed Do Eiusmod",
      text:
        "Consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna",
      icon: "ios-card-outline",
      colors: ["#13f1fc", "#0470dc"],
    },
    {
      key: "page3",
      title: "Adipisicing Elit Sed Do",
      text: "Usage Consectetur adipisicing elit, sed do eiusmod",
      icon: "ios-finger-print-outline",
      colors: ["#b1ea4d", "#459522"],
    },
  ],

  /**
   * Config For Left Menu Side Drawer
   * @param goToScreen 3 Params (routeName, params, isReset = false)
   * BUG: Language can not change when set default value in Config.js ==> pass string to change Languages
   */
  menu: {
    // has child categories
    isMultiChild: true,
    // Unlogged
    listMenuUnlogged: [
      {
        text: "Login",
        routeName: "LoginScreen",
        params: {
          isLogout: false,
        },
        icon: Icons.MaterialCommunityIcons.SignIn,
      },
    ],
    // user logged in
    listMenuLogged: [
      {
        text: "Logout",
        routeName: "LoginScreen",
        params: {
          isLogout: true,
        },
        icon: Icons.MaterialCommunityIcons.SignOut,
      },
    ],
    // Default List
    listMenu: [
      {
        text: "Shop",
        routeName: "Default",
        icon: Icons.MaterialCommunityIcons.Home,
      },
      {
        text: "News",
        routeName: "NewsScreen",
        icon: Icons.MaterialCommunityIcons.News,
      },
      {
        text: "contactus",
        routeName: "CustomPage",
        params: {
          id: 10941,
          title: "contactus",
        },
        icon: Icons.MaterialCommunityIcons.Pin,
      },
      {
        text: "About",
        routeName: "CustomPage",
        params: {
          url: "http://inspireui.com",
        },
        icon: Icons.MaterialCommunityIcons.Email,
      },
      // {
      //   text: "Setting",
      //   routeName: "SettingScreen",
      //   icon: Icons.MaterialCommunityIcons.Setting,
      // },
    ],
  },

  //define menu for profile tab
  ProfileSettings: [
    {
      label: "WishList",
      routeName: "WishListScreen",
    },
    {
      label: "MyOrder",
      routeName: "MyOrders",
    },
    {
      label: "Address",
      routeName: "Address",
    },
    {
      label: "Currency",
      isActionSheet: true,
    },
    // only support mstore pro
    //   {
    //     label: Languages.Languages,
    //     routeName: 'SettingScreen',
    //     value: language.lang,
    //   },
    {
      label: "PushNotification",
    },
    {
      label: "contactus",
      routeName: "CustomPage",
      params: {
        id: 10941,
        title: "contactus",
      },
    },
    {
      label: "Privacy",
      routeName: "CustomPage",
      params: {
        url: "https://inspireui.com/privacy",
      },
    },
    {
      label: "termCondition",
      routeName: "CustomPage",
      params: {
        url: "https://inspireui.com/term-of-service",
      },
    },
    {
      label: "About",
      routeName: "CustomPage",
      params: {
        url: "http://inspireui.com",
      },
    },
  ],

  // Layout select
  layouts: [
    {
      layout: Constants.Layout.card,
      image: Images.icons.iconCard,
      text: "cardView",
    },
    {
      layout: Constants.Layout.simple,
      image: Images.icons.iconRight,
      text: "simpleView",
    },
    {
      layout: Constants.Layout.twoColumn,
      image: Images.icons.iconColumn,
      text: "twoColumnView",
    },
    {
      layout: Constants.Layout.threeColumn,
      image: Images.icons.iconThree,
      text: "threeColumnView",
    },
    {
      layout: Constants.Layout.horizon,
      image: Images.icons.iconHorizal,
      text: "horizontal",
    },
    {
      layout: Constants.Layout.advance,
      image: Images.icons.iconAdvance,
      text: "advanceView",
    },
  ],

  // Default theme loading, this could able to change from the user profile (reserve feature)
  Theme: {
    isDark: false
  },

  // new list category design
  CategoryListView: true,

  DefaultCurrency:{
    symbol: "$",
    name: "US Dollar",
    code: "USD",
    name_plural: "US dollars",
    decimal: ".",
    thousand: ",",
    precision: 2,
    format: "%s%v", // %s is the symbol and %v is the value
  },

  DefaultCountry: {
    code: 'Ar',
    RTL: false, // em move config tu ben Constanst qua day de user ho de su dung
    language: 'Arabic',
    countryCode: "Iraq",
    hideCountryList: false // when this option is try we will hide the country list from the checkout page, default select by the above 'countryCode'
  }
};

**Comment by minhcasi** [comment]
Hi, we are checking the issue and will get back soon - thank you

**Comment by luyx2412** [comment]
Hi @SalamMohammed Can you try clean your project https://gist.github.com/jarretmoses/c2e4786fd342b3444f3bc6beff32098d and uninstall your app on simulator. After that install again.
P/S: your issue is cache default config redux-persist.
Thanks

**Comment by SalamMohammed** [comment]
Sorry I didn't answer you because I was so busy.
so you mean I enter this code in the CMD?
plus I bought two other of your apps ( eva store and mstore for shopify)
The mstore for shopify shows me error when I checked there were no config
file at all in it directory I delete the folder and re-download it again
the same issue.
and the eva store I entered all the details for my website but when I open
the app first bottom bar is invisible it is there but it is white. and the
other thing is the same content of the demo app even after I entered the
API key and all information as if I never entered a thing in it.
Will you check it for me please
best regards

‫في السبت، 24 نوفمبر 2018 في 9:47 ص تمت كتابة ما يلي بواسطة ‪luyx2412‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by luyx2412** [comment]
Hi @SalamMohammed Let me check your Config.js file with Mstore. Can you provide me the Config.js file Evastore and should be create another issue. Thanks

**Comment by luyx2412** [comment]
Hi @SalamMohammed With Evastore https://github.com/inspireui/support/issues/45 this is some issues related. 
And i checked your config, something was wrong with your category id. So please read document and add your category to see the products https://docs.mstore.io/basic-app-setting.
This is your right category id
<img width="320" alt="screen shot 2018-11-29 at 4 44 20 pm" src="https://user-images.githubusercontent.com/8909619/49213083-0b300180-f3f6-11e8-945b-d181218d7e24.png">

Thanks

**Comment by SalamMohammed** [comment]
I am so sorry I didn’t respond because i am not at home. When I get home I
will check it
Many thanks
