### ISSUE TITLE
[BeoNews] Please help me install BeoNews

### ISSUE THREAD

**Issue by trappat** [inspireui/support#330]
**Mandatory Info (please complete the following information):**
 - Product: beonews pro
 - Your Purchased Code: bb904f63-d575-4586-9afd-b7d283e357ff
(we may not reply if you are not our customer)

**Describe the issues**
The script doesnt work with my site. I need someone to make it work with Melaninterest.com

Problems
1.I need defaulted to Masonry and thats it.
2. Related posts pictures arent popping up
3. Login/related isnt working
4. Descriptions are popping up as undefined
5. next doesnt work
6. Need to be able to click on pictures
7. Remove the photo/video tab since they dont work

**Screenshots**

**Additional context**
Add any other detail logs about the problem here.

**Comment by minhcasi** [comment]
Hi, this is kind of customize work that not include from our support scope, the team also go extra smile of help for fixing the Masonry on your pinClone template and you may need do some customize by yourself - thank you!
