### ISSUE TITLE
Installation error. 

### ISSUE THREAD

**Issue by waghankit** [inspireui/support#3300]
<img width="1280" alt="Screenshot 2020-05-19 at 7 29 21 PM" src="https://user-images.githubusercontent.com/47549138/82362719-64488680-9a2a-11ea-8207-7dce6fd08198.png">

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as it could not be verified, please create the new one when you got enough purchased info - thank you!

**Comment by waghankit** [comment]
Hi,

The link  you provided was not responding so i was not able to verify the
issue. So what should i do now? Issue the ticket again?

Regards,
