### ISSUE TITLE
How to set up my shopify to InspireUI?

### ISSUE THREAD

**Issue by YuntongLi6543** [inspireui/support#3301]
I changed storefront API and web url, but got message from SDK like this.
![图片](https://user-images.githubusercontent.com/46054396/82362984-32f49a00-99db-11ea-9757-a256fa0bb168.png)

Also, how can I have the category ID for my products?

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as it could not be verified, please create the new one when you got enough purchased info - thank you!
