### ISSUE TITLE
[Fluxstore MV] Android Build Failing : Execution failed for task ':app:compileDebugKotlin'

### ISSUE THREAD

**Issue by jinuem** [inspireui/support#3302]
Step 1 (require): detail issues and screenshots

Build Working fine on iOS. but its failing for Android.
Tried Cleaning the Flutter Clean also Gradlew clean.  nothing works.

**Version : 1.7.3
Flutter: 1.17.1 Latest
Dart 2.8.2**

Error Log:

> (base) vincent@Vincents-MacBook-Pro CameronMarket (quote) $ flutter run
Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts,
consider enabling software rendering with "--enable-software-rendering".
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Note: Some input files use or override a deprecated API.                
Note: Recompile with -Xlint:deprecation for details.                    
Note: /Library/Flutter/.pub-cache/hosted/pub.dartlang.org/firebase_admob-0.9.3+2/android/src/main/java/io/flutter/plugins/firebaseadmob/AdRequestBuilderFactory.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                    
Note: /Library/Flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.13.4/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.                      
Note: Some input files use or override a deprecated API.                
Note: Recompile with -Xlint:deprecation for details.                    
Note: Some input files use unchecked or unsafe operations.              
Note: Recompile with -Xlint:unchecked for details.                      
Note: Some input files use unchecked or unsafe operations.              
Note: Recompile with -Xlint:unchecked for details.                      
Note: /Library/Flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.5/android/src/main/java/io/flutter/plugins/pathprovider/PathProviderPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                    
Note: /Library/Flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.4.5/android/src/main/java/io/flutter/plugins/urllauncher/WebViewActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                    
Note: Some input files use or override a deprecated API.                
Note: Recompile with -Xlint:deprecation for details.                    
Note: /Library/Flutter/.pub-cache/hosted/pub.dartlang.org/video_player-0.10.9+1/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayerPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                    
e: /Users/vincent/Workspace/HAIL/cameron-1.7.0/CameronMarket/android/app/src/main/kotlin/com/inspireui/fluxstore/MainActivity.kt: (8, 7): Redeclaration: MainActivity
e: /Users/vincent/Workspace/HAIL/cameron-1.7.0/CameronMarket/android/app/src/main/kotlin/com/inspireui/fluxstore/vendor/MainActivity.kt: (7, 7): Redeclaration: MainActivity    
                                                            

> FAILURE: Build failed with an exception.                                
>                                                                         
> * What went wrong:                                                      
> Execution failed for task ':app:compileDebugKotlin'.                    
>  Compilation error. See log for more details                           
>                                                                         
> * Try:                                                                  
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
>                                                                         
> * Get more help at https://help.gradle.org                              
>                                                                         
> BUILD FAILED in 53s                                                     
> Running Gradle task 'assembleDebug'...                                  
> Running Gradle task 'assembleDebug'... Done                        54.4s
> Exception: Gradle task assembleDebug failed with exit code 1

Same issue in screenshot.
<img width="823" alt="Screenshot 2020-05-20 at 12 42 20 AM" src="https://user-images.githubusercontent.com/3512723/82368268-c5745800-9a32-11ea-9029-ac258d20a242.png">

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

SUBMITTED

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@jinuem - pls help to us continues with the conversation and add your new comment into this ticket #3227

**Comment by jinuem** [comment]
@minhcasi  you are not at all replying there for days. what else I can do.

**Comment by minhcasi** [comment]
hi, pls check there again, i could see an comment 4h ago?

**Comment by jinuem** [comment]
@minhcasi yes. I get it. But this ticket opened 11Hrs ago.
I thought you guys not replying there or it's abandoned.
