### ISSUE TITLE
Adding more menu items

### ISSUE THREAD

**Issue by pingudew** [inspireui/support#3304]
How can I add/edit/delete items on this part of the app?

![a1](https://user-images.githubusercontent.com/65609192/82369331-20985180-9a17-11ea-82e6-ddb0a7c2432a.png)

**Comment by pingudew** [comment]
ps, http://private.inspireui.com, is not opening

**Comment by minhcasi** [comment]
@pingudew - these menu items could be managed on next release of fluxbuilder 1.0.5

Pls help to submit this link https://docs.google.com/forms/d/e/1FAIpQLScWOjkAJIWJ9rgb9alopfOqLsJrGKbFM5cCYj1JBfLKLsBblQ/viewform 

Let us know if you have any questions :) - thank you

**Comment by pingudew** [comment]
I filled the form.

1. How can I edit this part of menu from Android Studio not from Fluxbuilder?
2. How can I link an image with a particular store? For example if I want to put an ad for a store on the homepage. Also how can I change the image/link without updating the app?
3. When registering, after filling the data and clicking Sign up, the button says **Waiting** and nothing happens BUT on the woocommerce site the user registers. The user registers on background but there is no page change to tell that the registration is successful.
4. Im having problems with the login. I get this message: **Exception: The username or password is incorrect.**
5. The Google login doesn't work even that I have configured the Firebase. The error says "**There is an issue with the app during request the data, please contact admin for fixing the issues. PlatformException(sing_in_failed, com.google.android.gms.common.api.ApiException: 10: , null)**"

**Comment by pingudew** [comment]
Can you please help? @minhcasi

**Comment by pingudew** [comment]
I need help on this! I have filled out the form but no answer!

**Comment by pingudew** [comment]
**Issue 1**
On Woocommerce and Dokan, I have configured that:
1. When a Vendor is from country A the shipping rate to country B and C will be 5$
2. When a Vendor is from country A the shipping rate to country A will be 2$
The shipping doesnt get calculated on the app like I have configured on web. How can I do this?

**Issue 2**
How can I allow shipping on particular countries? I don't want users to have the option to select different country but only 3 countries that I allow.

**Issue 3**
How can a simple user edit their account details?
How can a simple user request to make their account vendor?

**Issue 4**
I have set the default user role to Client on Wordpress but when the user registers they register as Subscriber.

**Issue 5**
When a vendor registers I don't receive an email that a vendor is registered as when I receive when they register via website. I don't get email when a product is uploaded too, I only get email when the products are uploaded from website.

Please help!

**Comment by minhcasi** [comment]
@pingudew - thank you for verify, I've forwarded to my team for checking and get back your shortly.

@vumanhsn97 - please help with suggestion

**Comment by vumanhsn97** [comment]
**Edit menu items**: 
 remove/change position/add: you need to edit kDefaultSettings in lib/common/config/general.dart
 edit code: You can edit code in lib/screens/settings/settings.dart file
**Link image to store**: improve in future request
**Register success auto navigate to settings screen**
**Username and password in correct**: Please check your plugins in your wordpress site. It cant login in https://vintgo.al/ but it login success in https://vintgo.al/wp-login.php
**Google login**: Please follow this tutorial: https://docs.inspireui.com/fluxstore/sign-in/. Test it in emulator and real devices
**Shipping method**: You need to use one page checkout in lib/common/config/payments.dart https://tppr.me/zdqEp
**Shipping countries**: Add list default countries in lib/common/config/payments.dart but it not support for webview in issue 1 https://tppr.me/vHDq0
**Edit user**: You can edit it in profile but can't edit type of user
**Register as Subscriber**: type of user register is subscriber. It have been fixed at lib/services/dokan.dart https://tppr.me/usM0. You can edit type of there
**Verify email**: Don't have verify email and email when updated product.It just have product author id

**Comment by pingudew** [comment]
**Edit menu items:** There is no line "kDefaultSettings" on lib/common/config/general.dart

**Username and password in correct:** I have checked. I had my Maintenance on but I turned it off but **I still cant login**. I can login from vintgo.al and from vintgo.al/. It seems that **reCaptcha** on web is blocking the login from the app but when I **turned off the reCaptcha plugin** now when I try to login there is **no message "Wrong username or password", now it only stays on loading.** On the terminal I can see that a token is being displayed but then nothing happens. I have to go back.

**Google login:** I have done exactly how the documentation says but I still can't login/sign up.

**Shipping method:** Now it opens the website. I don't want users to go on the website!! I want they to finish buying on app!

**Shipping countries:** Fixed.

**Edit user:** Its very bad that user cant request for a vendor account.

**Register as Subscriber:** I have put "client" but when registering I get this error "Role is invalid"

**Verify email:** When a user registers as vendor or upload a product, I as administrator receive an email for new registered vendor or new uploaded product so I can approve or not. When the user registers or uploads a product from app I dont receive the email!

**Comment by pingudew** [comment]
Also I need help with this:

On Woocommerce and Dokan, I have configured that:

When a Vendor is from country A the shipping rate to country B and C will be 5$
When a Vendor is from country A the shipping rate to country A will be 2$
The shipping doesnt get calculated on the app like I have configured on web. How can I do this?

**Comment by pingudew** [comment]
Since the lack of support from your side, I had to request refund for my purchase!

**Comment by minhcasi** [comment]
resolved
