### ISSUE TITLE
Have an issue trying to change layout !!!!

### ISSUE THREAD

**Issue by nahuelbourdichon** [inspireui/support#3305]
Step 1 (require): detail issues and screenshots
Hello I trying to change the layout theme in this case the example Number 7 (I got it from FluxStore 1.7.3\source\lib\example\woocommerce\config_theme7.json) but I have been having the next issue

 
![image](https://user-images.githubusercontent.com/16769047/82377591-44996a00-99fa-11ea-8751-dba45856f259.png)
and this is the script error 

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building HomeLayout-[<'es'>](dirty, state: _HomeLayoutState#d0dc7):
Failed assertion: boolean expression must not be null

The relevant error-causing widget was: 
  HomeLayout-[<'es'>] file:///C:/src/MasPuntos_v1.7.3/FluxStore%201.7.3/source/lib/screens/home/home.dart:119:13
When the exception was thrown, this was the stack: 
#0      _HomeLayoutState.jsonWidget (package:fstore/widgets/home/index.dart:36:52)
#1      _HomeLayoutState.build (package:fstore/widgets/home/index.dart:149:11)
#2      StatefulElement.build (package:flutter/src/widgets/framework.dart:4619:28)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4502:15)
#4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
E/flutter (11708): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Looking up a deactivated widget's ancestor is unsafe.
E/flutter (11708): At this point the state of the widget's element tree is no longer stable.
E/flutter (11708): To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.
E/flutter (11708): #0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure> (package:flutter/src/widgets/framework.dart:3781:9)
E/flutter (11708): #1      Element._debugCheckStateIsActiveForAncestorLookup (package:flutter/src/widgets/framework.dart:3795:6)
E/flutter (11708): #2      Element.findAncestorStateOfType (package:flutter/src/widgets/framework.dart:3914:12)
E/flutter (11708): #3      Navigator.of (package:flutter/src/widgets/navigator.dart:2115:19)
E/flutter (11708): #4      _AnimatedSplashState.build.<anonymous closure> (package:fstore/widgets/common/animated_splash.dart:75:23)
E/flutter (11708): #5      _rootRunUnary (dart:async/zone.dart:1192:38)
E/flutter (11708): #6      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter (11708): #7      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
E/flutter (11708): #8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
E/flutter (11708): #9      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
E/flutter (11708): #10     Future._complete (dart:async/future_impl.dart:516:7)
E/flutter (11708): #11     new Future.delayed.<anonymous closure> (dart:async/future.dart:315:16)
E/flutter (11708): #12     _rootRun (dart:async/zone.dart:1180:38)
E/flutter (11708): #13     _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter (11708): #14     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
E/flutter (11708): #15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
E/flutter (11708): #16     _rootRun (dart:async/zone.dart:1184:13)
E/flutter (11708): #17     _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter (11708): #18     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1003:23)
E/flutter (11708): #19     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
E/flutter (11708): #20     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
E/flutter (11708): #21     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
E/flutter (11708): #22     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

I trying solved it changed the idion and other thing but it not work.
if  I use the original layout .json it working ok 

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by pingudew** [comment]
Try adding "StickyHeader": false" under "Setting: {" on lib/config/config_en.json

**Comment by minhcasi** [comment]
You could also try to download the latest release 1.7.4 on Gitlab - thank you!

**Comment by nahuelbourdichon** [comment]
Please can you provide me the link
thanks

**Comment by minhcasi** [comment]
@nahuelbourdichon - pls help to submit here - https://docs.google.com/forms/d/e/1FAIpQLSeuBqUkScy42V7KKhfNPj0fl581anrB1mWkbMa3p2WQt7fhfw/viewform

We also upload a new package shortly on today, http://codecayon.net/downloads - let us know if you have any further issue - thank you!
