### ISSUE TITLE
Mstore Opencart (expo version)

### ISSUE THREAD

**Issue by MrSubhani** [inspireui/support#3307]
This issue must be resolved by doing npm Install or by deleting the node modules folder and then doing npm install, but tried it so many times but still not solved. Tried all the following steps as well but still getting the same issue. No help about it in the documentation or the internet. Plus not aware of this library much as well. Your help will be appreciated.
![WhatsApp Image 2020-05-20 at 2 24 48 AM](https://user-images.githubusercontent.com/50181126/82391947-f65c8900-9a42-11ea-8467-c2dff964b4d8.jpeg)

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by MrSubhani** [comment]
Well, this given form is not opening. if you want the proof of the purchase I can give you but I can't share the purchase code here. I am attaching the screenshots of the proof of purchase. I have also added the comment with the ticket number on codecanyon. Loged in there with the name johnsharry93.
thanks!
![Screenshot 2020-05-20 at 8 28 48 AM](https://user-images.githubusercontent.com/50181126/82412669-51f33a80-9a74-11ea-83fb-5bfce65dabf3.png)
![Screenshot 2020-05-20 at 8 29 24 AM](https://user-images.githubusercontent.com/50181126/82412671-53246780-9a74-11ea-91cf-657267c51305.png)

**Comment by MrSubhani** [comment]
Team I need help about the above-mentioned issue.

**Comment by minhtruong315** [comment]
Hi @MrSubhani I tried to run on my source code. it's working well. 
<img width="1338" alt="Screen Shot 2020-05-21 at 5 59 14 AM" src="https://user-images.githubusercontent.com/10402500/82505570-44978800-9b28-11ea-8056-61b410fa3b4e.png">
Can u upload your source code to github then invite me: minhtruong315@gmail.com
ping me when you invited.
Thanks.

**Comment by MrSubhani** [comment]
My mate has uploaded the source code in the repository from his account. It's public. He has sent you the invitation as well. 
I am sharing the link so that you may see and help us. 
when you see this we will make it private
https://github.com/basitarshadkhan/Mstore

Looking forward to your response and help.

**Comment by minhtruong315** [comment]
Hi @MrSubhani you shouldn't public repo. please make it private

**Comment by MrSubhani** [comment]
ok, I will ask my mate to make it private.

**Comment by MrSubhani** [comment]
Hi, @minhtruong315 have you seen that repo? which my friend has shared with you? The respected team we are facing the above-mentioned issue. Please have a look at his repo, and please try to solve our issue as soon as possible. 
thanking you in advance.

**Comment by MrSubhani** [comment]
Hello team, I am still waiting for the support from your side. Please help us. @minhtruong315 @minhcasi

**Comment by minhcasi** [comment]
@MrSubhani 

We wanted to thank you for your patience during this busy time. We currently have reduced staff and a significantly higher volume of inquiries. We’re working as hard as we can to get to your request as soon as possible.

We sincerely apologize for the delay and hope you’re staying safe.

**Comment by MrSubhani** [comment]
@minhcasi @minhtruong315 
Thank you so much for replying. I am waiting, but please it is requested to resolve my issue as soon as possible as it is really urgent. 
Thanking you in advance!

**Comment by minhtruong315** [comment]
Hi @MrSubhani I ran your source code. it's working well. don't show your error. You can remove node_modules folder, then run ```yarn install``` again. But your website doesn't work. so can't get data from your website to show in app. please check again
<img width="1536" alt="Screen Shot 2020-05-25 at 11 37 13 AM" src="https://user-images.githubusercontent.com/10402500/82778710-55276580-9e7c-11ea-9708-cf533a7bd2ad.png">

**Comment by MrSubhani** [comment]
Hi @minhtruong315, I think there might be some node versions compatibility issue, can you share your node and npm versions?

**Comment by minhtruong315** [comment]
<img width="501" alt="Screen Shot 2020-05-25 at 9 31 12 PM" src="https://user-images.githubusercontent.com/10402500/82822304-bf1d2a80-9ecf-11ea-9062-709b1e8ea98c.png">

**Comment by basitarshadkhan** [comment]
Hi @minhtruong315, I've tried removing node_modules and doing npm install multiples times. But I'm having the same issue. What I am thinking is that there must be issue of node version. I'm using 12.14.0 node version, and you are having an old one, v10.18.1. Is this possible that the libraries that you're using are uncompatible with latest verson. I'll be waiting for the response.Thanks!

**Comment by minhcasi** [comment]
@basitarshadkhan - pls try to downgrade to nodejs 10.x to fix this issue - https://nodejs.org/dist/latest-v10.x/
