### ISSUE TITLE
[Fluxstore Multi Vendor] - IOS Build Failed after updating to flutter 1.17.1 • channel stable

### ISSUE THREAD

**Issue by HassanChmsdn** [inspireui/support#3308]
Step 1 (require): detail issues and screenshots

I realized that there are multiple dependencies required to be upgraded after upgrading flutter to 1.17.1 stable, I fixed most of the errors I got, but only one was not possible because it's breaking the packages get due to **koukicons**.

This Error was shown probably due to flutter_svg package missing in the pubspec.yaml file
<img width="1206" alt="Screenshot 2020-05-20 at 04 53 51" src="https://user-images.githubusercontent.com/921709/82400116-d931b580-9a56-11ea-8020-2da052431cc7.png">

but after adding it with the last version:
<img width="1194" alt="Screenshot 2020-05-20 at 04 54 35" src="https://user-images.githubusercontent.com/921709/82400309-49403b80-9a57-11ea-8f90-03a48f578c49.png">

It seems that koukicons has failed since It requires a lower version of flutter_svg which leads again to the error above
<img width="1155" alt="Screenshot 2020-05-20 at 04 55 00" src="https://user-images.githubusercontent.com/921709/82400272-2f065d80-9a57-11ea-9778-ececa84ae616.png">

Could you @minhcasi  please help if I am missing something!

Many Thanks

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

Item purchased code: d1141eb5-edf3-4bcc-844b-112677d6f489
Date : 2019-11-21 21:15:50 UTC

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@HassanChmsdn  - could you help to check the latest version as we remember to remove this library to fix the latest Flutter 1.17 - thank you!

**Comment by HassanChmsdn** [comment]
Hey @minhcasi,

Well it might be the reason yes, but is it possible if you can point me to the change that fixed this plugin issue, since i really dont need the whole changes of 17.1.3

Many thanks,
Hassan

**Comment by minhcasi** [comment]
Hi, you could try to update this file `screens/categories/grid_category.dart` as an attachment then remove the `koukicons` and`flutter_svg` to fix the issues.

[grid_category.dart.txt](https://github.com/inspireui/support/files/4665938/grid_category.dart.txt)

**Comment by HassanChmsdn** [comment]
Thanks, yes I figured it too.. its working now!
