### ISSUE TITLE
issue with category.dart

### ISSUE THREAD

**Issue by dwk1978usa** [inspireui/support#3309]
![catergories_dart](https://user-images.githubusercontent.com/10337459/82399897-f6409700-9a0a-11ea-8819-68bd7bb49f80.png)

I have have an issue finding category.dart in the folder mentioned. You mentioned it was in lib\models\category.dart. I found it in lib\models\category\category.dart
![android_studio_category](https://user-images.githubusercontent.com/10337459/82400171-88489f80-9a0b-11ea-8bf1-06d123d99b15.png)

Also the code in the category.dart is very much different from the one mentioned in the tutorial. Where do I put print(categories); in the second screenshot shown.

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as it could not be verified, please create the new one when you got enough purchased info - thank you!
