### ISSUE TITLE
[Eva] Homepage Text edit doesn't seem to work & Product Variant button showing Default Title

### ISSUE THREAD

**Issue by ONIXTurtle** [inspireui/support#331]
**Mandatory Info (please complete the following information):**
 - Product: Eva Store
 - Your Purchased Code: 1d0ff74c-5ee3-4129-9ef0-200b2b020b16
(we may not reply if you are not our customer)

**Describe the issues**
Hey there, the text of the Homepage categories is not changing after editing the name in the config.js ... Is there maybe some sort of translation variable somewhere else? Also how can I change/remove the button on the product page, which normally says choose your size? It is showing on my screen "Default Title" which shouldn't be there, because i don't have any variables on that product.

**Screenshots**

**Additional context**
Add any other detail logs about the problem here.

**Comment by luyx2412** [comment]
Hi @ONIXTurtle 
- The first question, Please check `src/common/Languages.js` file.
- Can you provide your Config.js and AppConfig.json file in common folder.

Thanks

Thanks
