### ISSUE TITLE
Shipping method is 0 on woogosend plugin

### ISSUE THREAD

**Issue by djks74** [inspireui/support#3311]
Dear InspireUI,
I use woogosend shipping method, its showing but seems its not calculate and shipping fee is 0.
Im using webview checkout now, but hopefully it could be fixed on the next update. 

I think because the address we input on address checkout is not filled to woocommerce address in API, so maybe thats why its not showing calculation.

here is the plugin :
https://wordpress.org/plugins/woogosend/

Meanshile, I bypass using enable onepage checkout to webview.

Thanks,
Sandi

**Comment by minhcasi** [comment]
@djks74 - pls help us to note your all conversation/issues to same ticket #3295

**Comment by djks74** [comment]
This one is different mate, this one is shipping method not payment.

Thanks
