### ISSUE TITLE
product not showing

### ISSUE THREAD

**Issue by meeraforefront** [inspireui/support#3312]
Step 1 (require): detail issues and screenshots

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by sketchuprzr** [comment]
You should write a more detailed explanation, my friend. you can also add pictures and videos.
But in general, the reason for not showing the products, if you have applied all the settings correctly; 
The mother tongue you use in your website must match the mother tongue you specified in the application.

**Comment by minhcasi** [comment]
@meeraforefront - I'm sorry to close this ticket as it could not be verified, please create the new one when you got enough purchased info - thank you!

#3188
