### ISSUE TITLE
[fluxstorepro] - Woocoemrce Boarding screen everytime when when app is open

### ISSUE THREAD

**Issue by tjain90** [inspireui/support#3313]
Step 1 (require): detail issues and screenshots

This is regarding my previous ticket -  #3275 
This bug is still there in new version. Please provide fix on this asap. 

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by Roupasafricanas** [comment]
I am in the same situation. I have access to gitlab and the new version does not solve the situation. Please provide fix

**Comment by bikostudio** [comment]
same here in ver 1.7.3

**Comment by trunghieuvn** [comment]
I have checked your common folder. I see you are using Splashscreen as png. It looks like the delay time to wait for the config is not enough. So please increase splash screen time to 3 seconds so that the app can fully load the configuration before going to the next screen. If you check and 3 seconds is not enough, please increase gradually (each increase of 100 milliseconds).

![image](https://user-images.githubusercontent.com/19247680/82524197-8a6c4480-9b58-11ea-94ba-4d6d0246845d.png)

**Comment by Roupasafricanas** [comment]
> J'ai vérifié votre dossier commun. Je vois que vous utilisez Splashscreen en png. Il semble que le délai d'attente pour la configuration ne soit pas suffisant. Veuillez donc augmenter le temps d'écran de démarrage à 3 secondes afin que l'application puisse charger complètement la configuration avant de passer à l'écran suivant. Si vous cochez et que 3 secondes ne suffisent pas, veuillez augmenter progressivement (chaque augmentation de 100 millisecondes).
> 
> ![image](https://user-images.githubusercontent.com/19247680/82524197-8a6c4480-9b58-11ea-94ba-4d6d0246845d.png)

@trunghieuvn, I think the problem is not splashscreen. Onboarding images appear every time the app is opened. If you close and open, you have to slide again. Please, how to solve that?

**Comment by tjain90** [comment]
Tried changing this and it did not stopped opening my boarding screen everytime. I believe 

> **isFirstSeen = await checkFirstSeen();**

is not punched due to which screen shown everytime.

**Comment by tjain90** [comment]
This new version of 1.7.4 that launched yesterday is too much buggy. It made my app super slow.
previous versions were fast and good. Kindly look into this on priority. My Home page never took this much time to load but it started now taking huge time.

**Comment by tjain90** [comment]
@minhcasi Is there any way to update phone number using update profile section ?  I want to replace link with phone number attribute so that it can be updated .

**Comment by trunghieuvn** [comment]
> Tried changing this and it did not stopped opening my boarding screen everytime. I believe
> 
> > **isFirstSeen = await checkFirstSeen();**
> 
> is not punched due to which screen shown everytime.

I have checked and found that the error is due to insufficient time to load isFirstScreen from SharedPreferences. If you fix it the way I still can't, there's probably something wrong somewhere. Please add me to your gitub gitlab repo project and let me know the device configuration you are testing. I will check the problem and help you quickly handle it.

Email my github/gitlab: hieu.trantrung1204@gmail.com

**Comment by tjain90** [comment]
@trunghieuvn I have invited you to my live project in gitlab. 
Please note current version of 1.7.4 is crashing in IOS when address is about to be selected. 
Previous 1.6.6 was working fine.

**Comment by minhcasi** [comment]
We wanted to thank you for your patience during this busy time. We currently have reduced staff and a significantly higher volume of inquiries. We’re working as hard as we can to get to your request as soon as possible.

We sincerely apologize for the delay and hope you’re staying safe.

@trunghieuvn - pls help with checking

**Comment by trunghieuvn** [comment]
Hi @tjain90 ,
I have created a Merge Request on your gitlab repo to fix this issue. Please check it again for me.
https://gitlab.com/inspireui/fluxstore-pro/-/merge_requests/12

**Comment by trunghieuvn** [comment]
Hi @tjain90 ,
I have created a Merge Request on your gitlab repo to fix this issue. 
Please check it again for me.

https://gitlab.com/tjain90/fluxstore-pro/-/merge_requests/1

**Comment by tjain90** [comment]
Thanks I will check and let you know. Meanwhile can you check why on iOS razorpay is not working ? It is throwing some error and app crashes

**Comment by minhcasi** [comment]
@tjain90 - we do not suggest to use `razorpay` library at its library contains a lot of build issue - thank you!
