### ISSUE TITLE
Fluxstore limitSelectQuantity on checkout

### ISSUE THREAD

**Issue by agent3bood** [inspireui/support#3317]
Step 1 (require): detail issues and screenshots
In `lib/widgets/product/cart_item.dart`
The `QuantitySelection` widget should have `limitSelectQuantity` property.

I have version 1.7.3

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

https://github.com/inspireui/support/issues/3134

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by minhcasi** [comment]
pls help to move your all comments to one ticket - #3316
