### ISSUE TITLE
Microphone support?

### ISSUE THREAD

**Issue by enriqueleon80** [inspireui/support#3318]
Hello, as we work to release our app we've noticed that this app requires a number of features from the phones itself on both iOS and Android.  What we find strange is the need to ask for Microphone access.  The PLIST on IOS doesn't list a reason.  Could you please tell us what feature in this template needs this access? If not needed, we'd like to remove it. iOS example below from PLIST.

	<key>NSMicrophoneUsageDescription</key>
	<string>This app requires</string>

<key>NSCameraUsageDescription</key>
	<string>This app requires access to take the photo from camera</string>
	<key>NSLocationAlwaysUsageDescription</key>
	<string>Need current location access</string>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string>Get your current location for delivery</string>
	<key>NSMicrophoneUsageDescription</key>
	<string>This app requires</string>
	<key>NSPhotoLibraryUsageDescription</key>
	<string>This app requires access to the photo library to support Chat Features.</string>
	<key>UIBackgroundModes</key>
	<array>

**Comment by minhcasi** [comment]
- NSMicrophoneUsageDescription is not used, pls remove it 

- Other permissions are required: camera to pick up the photo and photo galleries when upload image when Vendor creat new product, location is required when using Map picker from Address

**Comment by minhcasi** [comment]
Let us know if you have any questions.

Please also share your final app on Appstore, good luck 👍
