### ISSUE TITLE
When we followed the config tutorial for fluxstore app using  opencart, in Step.2 (Test default demo website)

### ISSUE THREAD

**Issue by pustakmandi-developer** [inspireui/support#3319]
When we followed the tutorial for configuring our Fluxstore app using OpenCart setup, then in Step 2.(Test default demo website) we received an error on our Homescreen page

![Screenshot (37)](https://user-images.githubusercontent.com/56787208/82446308-0cf6f480-9ac4-11ea-9703-f9832c05b509.png)

**Comment by pustakmandi-developer** [comment]
Please reply asap.

**Comment by minhcasi** [comment]
@pustakmandi-developer - pls move your all conversation to same ticket #3320
