### ISSUE TITLE
LISTAPP Error

### ISSUE THREAD

**Issue by bobozd** [inspireui/support#332]
Hello, 

I try to install listapp and connect with my mylisting wordpress.
It loads only Blog section into my Listapp and there is no any listing loaded to the app.

Please help.

[Archive.zip](https://github.com/inspireui/support/files/2898052/Archive.zip)

**Comment by thangvo9x** [comment]
Hi. You must change category in your Config theme. It's mean, the file which is your theme. 
(mylisting, listapp, listify...)

**Comment by bobozd** [comment]
can you specify me which file and which code line.
I selected Mylisting as theme in rebuilder, so It needs to work by default ???

Thanks.

**Comment by thangvo9x** [comment]
The MyListing.js file in Config folder. with property is "horizontalLayout". change it & restart
let me know

**Comment by bobozd** [comment]
Hello,

here is my whole app folder.
please debug it and make it working.
Also please let me know what you change which file and line of code) so I
can know next time to do it alone

LINK:
https://drive.google.com/file/d/1-m8cuwcNNcoqYxEj_1wYEdjd9W6Tlv2U/view?usp=sharing


tnx.

**Comment by bobozd** [comment]
also, where I can change intro slider text (map support and 4-5 other
sliders) is it just images or need to chenge text in code) where is it
saved?

**Comment by minhcasi** [comment]
@bobozd - kindly send to private email or send to our Chat support from the https://inspireui.com - thank you!

I have delete the link and will send to the team for checking - thank you!

**Comment by thangvo9x** [comment]
Hi. You can change it App/Common/IntroData.js
Thanks

**Comment by bobozd** [comment]
thanks, but please answer me to the bost before this. I send complete app
folders for you to properly install.
