### ISSUE TITLE
Issue while setting up Fluxstore for Opencart Site: Step 3 of the Tutorial. 

### ISSUE THREAD

**Issue by pustakmandi-developer** [inspireui/support#3320]
Also when we followed Step. 3 for linking with API and in the url gave it for our own website then we faced the same issue on the Homescreen Page , also in the category section we received blank page, also in the blog section we received the same.

![Screenshot (39)](https://user-images.githubusercontent.com/56787208/82446739-d4a3e600-9ac4-11ea-8706-c858fdf017c4.png)
![Screenshot (35)](https://user-images.githubusercontent.com/56787208/82446806-f604d200-9ac4-11ea-92d4-97fc18943a6e.png)

**Comment by minhtruong315** [comment]
hi @pustakmandi-developer Fluxstore only supports blog on wordpress site now. so you're using opencart blog site, so it dont work.
For category issue, you can remove categories array in TabBar of config json

**Comment by pustakmandi-developer** [comment]
Hello Team,
There is some issue with the latest version of the code. I did not make any changes in the code except for opencart config file -> Site URL. Initially default site got run successfully but as soon as i updated the link, products and category are not getting displayed. Only home page is opening but its blank. 
Please guide. Its holding our work a lot by getting multiple errors. Request you to revert asap.

**Comment by minhtruong315** [comment]
@pustakmandi-developer can u upload your source code to github then invite me: minhtruong315@gmail.com
I'll help you check and update on it

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!

**Comment by KhanJahanzaib** [comment]
Hey sir, I have same issue

**Comment by ameenbadri7** [comment]
@KhanJahanzaib you can open a new support ticket and verify your self and we will fix Your problems .
Thank you for your time !

**Comment by KhanJahanzaib** [comment]
my client bought fluxstore pro .Here is website link
http://www.dikaken.com/shop/admin

‪On Mon, Jun 29, 2020 at 4:34 AM ‫amin badri أمين بدري‬‎ <
notifications@github.com> wrote:‬

**Comment by KhanJahanzaib** [comment]
my client bought fluxstore pro .Here is website link
http://www.dikaken.com/shop/admin
 user name :support
password : yousefccc
