### ISSUE TITLE
Fluxstore - Login & Payment  Checkout Issue

### ISSUE THREAD

**Issue by hirahsoft** [inspireui/support#3321]
Step 1 (require): detail issues and screenshots
1. Login Screen & SignUp shows this error  
Warning : FormatException , Unexpected Character (at character 1)
<html>
^
Screenshot Attached.
[https://ibb.co/4pZw3GW](url)

- Fixed Login but Signup Shows a different error.
  [https://ibb.co/pwt3vRm](url) 

2. Checkout also shows same error.    -*-  Fixed by changing the server url to https
    I would like to add cash on delivery and default magento payment settings to the mobile app.
    Please guide me how to add cash on Delivery as well.

**Comment by nathajjar** [comment]
Same problem of login with FLUXNEW
" login err FormatException: Unexpected end of input (at character 1)"
I have a issue with the auth_cookie
*domain/wp-json/api/flutter_user/generate_auth_cookie/?insecure=cool&&insecure=cool

**Comment by hirahsoft** [comment]
I fixed Checkout  issue with by changing url to HTTPS instead of HTTP.

**Comment by minhcasi** [comment]
@hirahsoft - thank you for resolving it quickly, could I know if this is your question "who to enable cash on Delivery on magento"?

**Comment by hirahsoft** [comment]
> @hirahsoft - thank you for resolving it quickly, could I know if this is your question "who to enable cash on Delivery on magento"?
I cannot find the option or Guide to add cash on delivery as its not showing in the payments page.

**Comment by nathajjar** [comment]
thanks for your reply

The solution for me HTTP --> HTTPS lol

many thanks !

**Comment by minhcasi** [comment]
Thank you for sharing, i will update document for this issue, let us know if you have any further issue

**Comment by hirahsoft** [comment]
Hi, 
I had to resolve the issue of COD myself too but, Now i am stuck with another issue
Shipping Error. Invalid value in Region ID field
 When you try to checkout in last step. From Magento The issue was fixed by returning a Null value but in the app where should i change this value of regionID?

**Comment by AmeerEbrahim** [comment]
Having the same error of FormatException: Unexpected end of input(at character 1) at Payment checkout and Login .
Can you please elaborate on how you solved this issue and let me know where did you manipulate this change of : 
"The solution for me HTTP --> HTTPS lol"

**Comment by nathajjar** [comment]
In the configuration file --> config.dart

You need to put the path of your website with the adresse "https://xxx..." and not "http://xxx."
