### ISSUE TITLE
REMOVE TABBAR LABEL

### ISSUE THREAD

**Issue by papaya1986** [inspireui/support#3322]
How to remove tabbar Label like home, search, category, etc .

Tried Bellow

1.i checked fluxstore builder there is no option.
2.removed label from config_en.json 

tried version 1.7.4 but it's still there....

**Comment by minhcasi** [comment]
@papaya1986 - could you share your config json file, it could hide the Label from the TabBar section by removing it. (if you have upload your config file to your website, make sure to reupload it)

<img width="1271" alt="Screen Shot 2020-05-21 at 08 09 18" src="https://user-images.githubusercontent.com/1459805/82512452-60a42500-9b3a-11ea-8b3b-7094add5ef2c.png">

**Comment by papaya1986** [comment]
yes it's working now ..server-side file replaced with new one ..
