### ISSUE TITLE
App crash after a minute

### ISSUE THREAD

**Issue by agent3bood** [inspireui/support#3324]
Step 1 (require): detail issues and screenshots
The app crash after a minute of usage, just clicking around in any random way.
I have downloaded 1.7.3 copied my config files (included) and the app is crashing also.
I have tried to catch logs from flutter & logcat but I did not find any pattern to the crash.
The issue is on both debug and release modes, Android 10 device (checked on 2 devices).

from logcat
`Process com.inspireui.fluxstore (pid 1635) has died: fore TOP`

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

DONE

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by minhcasi** [comment]
pls help to move your all comments to one ticket - #3316
