### ISSUE TITLE
Masonry Layout Crashing Build 

### ISSUE THREAD

**Issue by gmldigital2019** [inspireui/support#3326]
We are trying to change the masonry layout which keeps crashing. 
![WhatsApp Image 2020-05-16 at 5 15 29 PM](https://user-images.githubusercontent.com/60437057/82473482-a0fe9700-9a97-11ea-92c0-9f7b639904e9.jpeg)

**Comment by luyx2412** [comment]
Hi @gmldigital2019 in `App/Components/PostLayout/Card/index.js` replace to this file 
[index.js.zip](https://github.com/inspireui/support/files/4671122/index.js.zip) to fix the issue.

Thanks

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
