### ISSUE TITLE
Can't build 1.7.3

### ISSUE THREAD

**Issue by minaunghein** [inspireui/support#3327]
Step 1 (require): detail issues and screenshots
lib/common/styles.dart:52:9: Error: No named parameter with the name 'headline6'. and all issue are related to TextTheme

<img width="1243" alt="Screen Shot 2020-05-21 at 12 19 03 AM" src="https://user-images.githubusercontent.com/4039502/82479676-b35ced00-9af8-11ea-8d14-07d342245f29.png">

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by sketchuprzr** [comment]
Update your flutter and dart version

**Comment by ayyanitp** [comment]
I am facing the same issue. Can you please guide on how to fix it ?

**Comment by minhcasi** [comment]
@minaunghein - try to follow this guide https://medium.com/@inspireui/announcing-fluxstore-1-7-x-9a636c5468e8

You can use this script:
```
flutter channel stable
flutter upgrade --force
```

ref: https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

Let us know your checking

**Comment by ayyanitp** [comment]
I did those steps but still having the same errors

**Comment by minaunghein** [comment]
i just follow 

flutter channel stable
flutter upgrade --force
and it work !

<img width="1274" alt="Screen Shot 2020-05-21 at 11 05 21 AM" src="https://user-images.githubusercontent.com/4039502/82523727-0c596f00-9b53-11ea-83a8-a555e0592a5b.png">

**Comment by minaunghein** [comment]
thanks

**Comment by ayyanitp** [comment]
I did the same steps but same errors showing 😢
