### ISSUE TITLE
email and password registration function does not work

### ISSUE THREAD

**Issue by joaonathan** [inspireui/support#3328]
all login functions are working correctly, only the email and password registration function does not work.

![registro](https://user-images.githubusercontent.com/9143192/82495406-6dd0fd80-9ac1-11ea-9ee6-a3438e5a6fad.png)

**Comment by minhcasi** [comment]
@joaonathan - pls try to active the License from mstore-api to un-lock the verify purchase to fix this issue - thank you!

**Comment by joaonathan** [comment]
![image](https://user-images.githubusercontent.com/9143192/82594293-3c683880-9b7a-11ea-8a32-e4b4389b8bde.png)


already activated, everything works correctly, except the registration

**Comment by minhcasi** [comment]
@minhtruong315 - pls help to check the registration issue

**Comment by minhcasi** [comment]
We wanted to thank you for your patience during this busy time. We currently have reduced staff and a significantly higher volume of inquiries. We’re working as hard as we can to get to your request as soon as possible.

We sincerely apologize for the delay and hope you’re staying safe.

**Comment by minhtruong315** [comment]
Hi @joaonathan Please update Fluxstore version 1.7.4 and upgrade MStore Api plugin to the latest version then test again.
if your issue doesn't resolved. please upload your source code to github and invite me: minhtruong315@gmail.com
I'll help you check and fix on that.
Ping me when you invited me.
Thanks

**Comment by joaonathan** [comment]
I did all the updates, but it still doesn't work, I invited you to the source code.

**Comment by joaonathan** [comment]
> Oi @joaonathan Atualize a versão 1.7.4 do Fluxstore e atualize o plug-in MStore Api para a versão mais recente e teste novamente.
> se o seu problema não for resolvido. faça o upload do seu código-fonte para o github e me convide: [minhtruong315@gmail.com Ajudarei](mailto:minhtruong315@gmail.com)
> você a verificar e corrigir isso.
> Ping-me quando você me convidou.
> obrigado
Fiz todas as atualizações, mas ainda não funciona, convidei você para o código-fonte.

**Comment by joaonathan** [comment]
> Oi @joaonathan Atualize a versão 1.7.4 do Fluxstore e atualize o plug-in MStore Api para a versão mais recente e teste novamente.
> se o seu problema não for resolvido. faça o upload do seu código-fonte para o github e me convide: [minhtruong315@gmail.com Ajudarei](mailto:minhtruong315@gmail.com)
> você a verificar e corrigir isso.
> Ping-me quando você me convidou.
> obrigado


I did all the updates, but it still doesn't work, I invited you to the source code

**Comment by minhtruong315** [comment]
Hi @joaonathan I checked your config. it can't request api for sign up. Can you send me admin account to login to your website via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/3328
<img width="891" alt="Screen Shot 2020-05-25 at 9 28 13 PM" src="https://user-images.githubusercontent.com/10402500/82821710-c1cb5000-9ece-11ea-9431-92fa3837d536.png">

**Comment by joaonathan** [comment]
> Oi @joaonathan eu verifiquei sua configuração. ele não pode solicitar a API para se inscrever. Você pode me enviar uma conta de administrador para acessar o seu site via e-mail: [truong@inspireui.com](mailto:truong@inspireui.com)
> com o assunto: [# 3328](https://github.com/inspireui/support/issues/3328)
> <img alt="Captura de tela 2020-05-25 em 9 28 13 PM" width="891" src="https://user-images.githubusercontent.com/10402500/82821710-c1cb5000-9ece-11ea-9431-92fa3837d536.png">

ok

**Comment by joaonathan** [comment]
Any solution?

**Comment by minhcasi** [comment]
@minhtruong315 - pls follow up the ticket

**Comment by minhtruong315** [comment]
Hi @joaonathan please replace createUser function in services/woocommerce.dart like this
```
@override
  Future<User> createUser({firstName, lastName, username, password}) async {
    try {
      String niceName = firstName + " " + lastName;
      final http.Response response = await http.post(
          "$url/wp-json/api/flutter_user/sign_up/?insecure=cool&$isSecure",
          body: convert.jsonEncode({
            "user_email": username,
            "user_login": username,
            "username": username,
            "user_pass": password,
            "email": username,
            "user_nicename": niceName,
            "display_name": niceName,
          }));
      var body = convert.jsonDecode(response.body);
      if (response.statusCode == 200 && body["message"] == null) {
        var cookie = body['cookie'];
        return await getUserInfo(cookie);
      } else {
        var message = body["message"];
        throw Exception(message != null ? message : "Can not create the user.");
      }
    } catch (err) {
      //This error exception is about your Rest API is not config correctly so that not return the correct JSON format, please double check the document from this link https://docs.inspireui.com/fluxstore/woocommerce-setup/
      rethrow;
    }
  }
```
then try again and let me know the result

**Comment by joaonathan** [comment]
it worked now, thanks
