### ISSUE TITLE
[ListApp] categories featured image not visible in list column field

### ISSUE THREAD

**Issue by Pavithran10** [inspireui/support#333]
**Mandatory Info (please complete the following information):**
Product:[ListApp]
Version:1.6.1
Theme: MyListing

**Describe the issues**
hi, In listapp categories featured image is not visible in list field column. It is located in mapping tab icon inside the list categories column. thanks 

**Screenshots**
![categorylist](https://user-images.githubusercontent.com/46148046/53318621-ed3f4380-38f5-11e9-9cda-84f995db1abd.jpg)

**Comment by thangvo9x** [comment]
Hi. Try comment line 17 Containers/Search/HorizonItemSearch.js
let me know. Thanks

**Comment by Pavithran10** [comment]
thanks, I'll try and update

**Comment by Pavithran10** [comment]
hi, I tried your comment but it shows error after comment the line 17 
![catlisterror](https://user-images.githubusercontent.com/46148046/53321190-b2410e00-38fd-11e9-9d9f-27b790369150.png)

**Comment by thangvo9x** [comment]
Please take a screenshot your file

**Comment by Pavithran10** [comment]
hi, I've attached the files
[Search.zip](https://github.com/inspireui/support/files/2900668/Search.zip)

**Comment by thangvo9x** [comment]
Hi. Please comment this line & try again.
<img width="443" alt="screen shot 2019-02-26 at 9 14 59 am" src="https://user-images.githubusercontent.com/23457178/53382470-0d7b0b00-39a7-11e9-85a4-aec01006e189.png">

**Comment by Pavithran10** [comment]
ok, I'll check and update.
