### ISSUE TITLE
Mercado pago Nativo de la web

### ISSUE THREAD

**Issue by midasmkt** [inspireui/support#3330]
Hola Me ocurre lo mismo, no puedo hacer que me tome el pago por mercado pago. 
Se resolvió? 

Step 1 (require): detail issues and screenshots

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by midasmkt** [comment]
Hola Minh. Gracias por la preocupación e interés en solucionar mi caso. 
Pero no hay caso, no lo pude arreglar con actualización realizada en el día de hoy, ocurre lo mismo. 
Envió un vídeo de lo que ocurre. 
https://www.youtube.com/watch?v=VpzwgVt4P14

**Comment by minhcasi** [comment]
We wanted to thank you for your patience during this busy time. We currently have reduced staff and a significantly higher volume of inquiries. We’re working as hard as we can to get to your request as soon as possible.

We sincerely apologize for the delay and hope you’re staying safe.

@kvt0012 - pls help to investigate

**Comment by kvt0012** [comment]
Sorry guys, can you speak English ? Thank you

**Comment by kvt0012** [comment]
Hello sir, I use google translate and if something is not clear, please tell me 
you can follow this guide, it will help you set up.
https://docs.inspireui.com/fluxstore/multi-payment/ 

thank you

**Comment by midasmkt** [comment]
Hi minh, I already did that and I checked many times

**Comment by kvt0012** [comment]
Dear sir, can you decribe your problem in English, I will help you fix it, thank you

**Comment by midasmkt** [comment]
Hello good afternoon.
the problem is that the app does not recognize the web payment,
despite the fact that I did everything as the manual says.
I send a video so you can have a better detail of the problem.
Thank you.
I need this

urgently.https://youtu.be/VpzwgVt4P14

the payment method used on the web is paid market.www.animalworldveterinaria.com
