### ISSUE TITLE
InkResponse widgets require a Material widget ancestor.

### ISSUE THREAD

**Issue by christianmls** [inspireui/support#3332]
Step 1 (require): detail issues and screenshots

"IsRequiredLogin": true,
Default Language es

After entering, the home screen does not render

![image](https://user-images.githubusercontent.com/5238734/82509042-6b27d580-9acc-11ea-8ccf-ca33c2d7af26.png)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by christianmls** [comment]
I sent form

**Comment by christianmls** [comment]
I sent form

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

________________________________
De: Minh Pham <notifications@github.com>
Enviado: Wednesday, May 20, 2020 10:53:21 PM
Para: inspireui/support <support@noreply.github.com>
Cc: Christian <christianmls@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [inspireui/support] InkResponse widgets require a Material widget ancestor. (#3332)


Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://private.inspireui.com/ -<http://private.inspireui.com/%C2%A0-> please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by joaonathan** [comment]
I have the same problem #3346

**Comment by minhcasi** [comment]
@vumanhsn97 - please help to investigate the issue

**Comment by vumanhsn97** [comment]
Update kLayoutWeb = identical(0, 0.0); in lib/common/config/general.dart
![image](https://user-images.githubusercontent.com/39208623/82639194-7137c680-9c32-11ea-94a9-3444edac4940.png)

**Comment by christianmls** [comment]
Thanks, this change fixes the issue.

**Comment by joaonathan** [comment]
thanks
