### ISSUE TITLE
App Configuration issue

### ISSUE THREAD

**Issue by darsadask** [inspireui/support#3334]
Hi i just purchased 

My website is http://fresh2home.com.au/
I changed my app name using your videotutorial.  It works fine.
In your video (https://www.youtube.com/watch?v=Q8Q3ywiiV9g) in MainActivity.kt you suggested to change com.inspireui.fluxstore to com.myhost.mysite
So should I change this as au.com.fresh2home ?

In Your video in same  MainActivity.kt you are changing at line 52 but in my app it is not showing there and also the next step is renaming the folder but i didn't find any folder for renaming
![image](https://user-images.githubusercontent.com/5181183/82533049-2cdbf600-9b60-11ea-9e44-43076626f71d.png)

**Comment by iamar1k92** [comment]
go into kotlin bro instead of java.

and please use com.au.fresh2home

**Comment by minhcasi** [comment]
Please also help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
@darsadask - I'm sorry to close this ticket as it could not be verified, please create the new one when you got enough purchased info - thank you!
