### ISSUE TITLE
Push Notifications

### ISSUE THREAD

**Issue by RohithKilaparthi** [inspireui/support#3339]
Hi

I have a small question regarding push notifications. For sending a push notification, we need a token with which the device can be uniquely identified. Are we storing the token in the DB? If so, where in the code? Is it possible to automate the push notifications part?

**Comment by minhcasi** [comment]
Thank you for the question.

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
@RohithKilaparthi 
please try to check the solution from these guide
- https://documentation.onesignal.com/reference/create-notification
- https://firebase.google.com/docs/cloud-messaging

Thank you!

**Comment by RohithKilaparthi** [comment]
Just submitted a response in the link provided. I know how to send a push notification to a targeted user using FCM. But for doing to, we need to have the token(device identifier), I would want to understand where are we storing that token and how do we trigger the notification when order state changes
