### ISSUE TITLE
[MStore] Unable to change name field in AppConfig.json file

### ISSUE THREAD

**Issue by lyrathaprinces** [inspireui/support#334]
- Product: MstorePro
 - Your Purchased Code: e1c19d73-87c3-4bee-afb4-9451b95dbc45

Unable to change name field in AppConfig.json file,,,only default names are displaying,, if i edit nothing is displayed. Tried with CEBuilder as well This is my file: https://drive.google.com/open?id=1vx6hV0-8aQ6cNhzoGsHtyQkame7wYhj9

**Comment by minhcasi** [comment]
Hi, the name is the keys of the language that could be changed from the languages.js file - thanks

**Comment by lyrathaprinces** [comment]
Thanks you,, those who are still here check line 264 of languages.js

**Comment by minhcasi** [comment]
@lyrathaprinces - thank you so much for your sharing, please help us to give a rating if the product is useful for your business, appreciated for your help :)
