### ISSUE TITLE
Getting parameter errors in code

### ISSUE THREAD

**Issue by GNAG1993** [inspireui/support#3340]
this is the error i'm getting.

Launching lib\main.dart on Infinix X626B in debug mode...
Running Gradle task 'assembleDebug'...

Compiler message:
lib/common/styles.dart:52:9: Error: No named parameter with the name 'headline6'.
        headline6: TextStyle(
        ^^^^^^^^^
../flutter/packages/flutter/lib/src/material/text_theme.dart:109:9: Context: Found this candidate, but the arguments don't match.
  const TextTheme({
        ^^^^^^^^^
lib/common/styles.dart:68:25: Error: The getter 'headline5' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline5'.
        headline5: base.headline5
                        ^^^^^^^^^
lib/common/styles.dart:70:25: Error: The getter 'headline6' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline6'.
        headline6: base.headline6.copyWith(fontSize: 18.0),
                        ^^^^^^^^^
lib/common/styles.dart:75:25: Error: The getter 'subtitle1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'subtitle1'.
        subtitle1: base.subtitle1.copyWith(
                        ^^^^^^^^^
lib/common/styles.dart:68:9: Error: No named parameter with the name 'headline5'.
        headline5: base.headline5
        ^^^^^^^^^
lib/common/styles.dart:88:49: Error: The getter 'headline4' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline4'.
      .copyWith(headline4: kHeadlineTheme(base).headline4.copyWith());
                                                ^^^^^^^^^
lib/common/styles.dart:88:17: Error: No named parameter with the name 'headline4'.
      .copyWith(headline4: kHeadlineTheme(base).headline4.copyWith());
                ^^^^^^^^^
lib/common/styles.dart:133:9: Error: No named parameter with the name 'headline6'.
        headline6: TextStyle(
        ^^^^^^^^^
../flutter/packages/flutter/lib/src/material/text_theme.dart:109:9: Context: Found this candidate, but the arguments don't match.
  const TextTheme({
        ^^^^^^^^^
lib/screens/settings/wishlist.dart:232:44: Error: The getter 'subtitle1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'subtitle1'.
                                          .subtitle1
                                           ^^^^^^^^^
lib/screens/blogs/post_screen.dart:134:48: Error: The getter 'subtitle1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'subtitle1'.
        textStyle: Theme.of(context).textTheme.subtitle1.copyWith(
                                               ^^^^^^^^^
lib/widgets/blog/slider_list.dart:214:40: Error: The getter 'bodyText1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'bodyText1'.
                                      .bodyText1
                                       ^^^^^^^^^
lib/widgets/blog/slider_list.dart:227:40: Error: The getter 'bodyText1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'bodyText1'.
                                      .bodyText1
                                       ^^^^^^^^^
lib/widgets/blog/slider_list.dart:330:40: Error: The getter 'bodyText1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'bodyText1'.
                                      .bodyText1
                                       ^^^^^^^^^
../flutter/.pub-cache/hosted/pub.dartlang.org/extended_image-0.7.3-dev/lib/src/gesture/extended_image_slide_page_route.dart:335:9: Error: No named parameter with the name 'primaryRouteAnimation'.
        primaryRouteAnimation: animation,
        ^^^^^^^^^^^^^^^^^^^^^
../flutter/packages/flutter/lib/src/cupertino/route.dart:430:3: Context: Found this candidate, but the arguments don't match.
  CupertinoFullscreenDialogTransition({
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/screens/checkout/payment.dart:222:58: Error: The getter 'subtitle1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'subtitle1'.
                      style: Theme.of(context).textTheme.subtitle1.copyWith(
                                                         ^^^^^^^^^
lib/screens/checkout/review.dart:66:56: Error: The getter 'subtitle1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'subtitle1'.
                    style: Theme.of(context).textTheme.subtitle1.copyWith(
                                                       ^^^^^^^^^
lib/screens/checkout/review.dart:92:62: Error: The getter 'subtitle1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'subtitle1'.
                          style: Theme.of(context).textTheme.subtitle1.copyWith(
                                                             ^^^^^^^^^
lib/screens/checkout/review.dart:118:58: Error: The getter 'subtitle1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'subtitle1'.
                      style: Theme.of(context).textTheme.subtitle1.copyWith(
                                                         ^^^^^^^^^
lib/screens/checkout/review.dart:143:56: Error: The getter 'subtitle1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'subtitle1'.
                    style: Theme.of(context).textTheme.subtitle1.copyWith(
                                                       ^^^^^^^^^
lib/widgets/backdrop/backdrop.dart:95:39: Error: The getter 'headline6' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline6'.
          Theme.of(context).textTheme.headline6.copyWith(color: Colors.white),
                                      ^^^^^^^^^
lib/screens/users/user_point.dart:69:60: Error: The getter 'subtitle1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'subtitle1'.
                        style: Theme.of(context).textTheme.subtitle1.copyWith(
                                                           ^^^^^^^^^
lib/screens/users/user_point.dart:102:38: Error: The getter 'subtitle1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'subtitle1'.
                                    .subtitle1
                                     ^^^^^^^^^
lib/vendor/store_detail/store_detail_screen.dart:96:30: Error: The getter 'headline6' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline6'.
                            .headline6
                             ^^^^^^^^^
lib/vendor/store/widgets/store_item.dart:111:30: Error: The getter 'subtitle1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'subtitle1'.
                            .subtitle1
                             ^^^^^^^^^
lib/widgets/product/product_card_view.dart:179:56: Error: The getter 'headline6' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline6'.
                    style: Theme.of(context).textTheme.headline6.copyWith(
                                                       ^^^^^^^^^
lib/widgets/product/product_card_view.dart:191:58: Error: The getter 'headline6' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline6'.
                      style: Theme.of(context).textTheme.headline6.copyWith(
                                                         ^^^^^^^^^
lib/widgets/product/product_list_tile.dart:150:54: Error: The getter 'headline6' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline6'.
                  style: Theme.of(context).textTheme.headline6.copyWith(
                                                     ^^^^^^^^^
lib/widgets/product/product_list_tile.dart:159:56: Error: The getter 'headline6' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline6'.
                    style: Theme.of(context).textTheme.headline6.copyWith(
                                                       ^^^^^^^^^
lib/vendor/store_detail/widgets/contact.dart:108:59: Error: The getter 'subtitle1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'subtitle1'.
                style: Theme.of(context).primaryTextTheme.subtitle1.copyWith(
                                                          ^^^^^^^^^
lib/widgets/blog/detailed_blog/detailed_blog_fullsize_image.dart:146:59: Error: The getter 'bodyText1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'bodyText1'.
                              Theme.of(context).textTheme.bodyText1.copyWith(
                                                          ^^^^^^^^^
lib/widgets/blog/detailed_blog/detailed_blog_quarter_image.dart:153:59: Error: The getter 'bodyText1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'bodyText1'.
                              Theme.of(context).textTheme.bodyText1.copyWith(
                                                          ^^^^^^^^^
lib/screens/cart/my_cart.dart:152:65: Error: The getter 'subtitle1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'subtitle1'.
                                    style: localTheme.textTheme.subtitle1
                                                                ^^^^^^^^^
lib/widgets/blog/detailed_blog_fullsize_image.dart:214:59: Error: The getter 'bodyText1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'bodyText1'.
                              Theme.of(context).textTheme.bodyText1.copyWith(
                                                          ^^^^^^^^^
lib/widgets/blog/detailed_blog_half_image.dart:211:38: Error: The getter 'bodyText1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'bodyText1'.
                                    .bodyText1
                                     ^^^^^^^^^
lib/widgets/blog/detailed_blog_quarter_image.dart:206:32: Error: The getter 'bodyText1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'bodyText1'.
                              .bodyText1
                               ^^^^^^^^^
lib/widgets/blog/detailed_blog_view.dart:114:57: Error: The getter 'bodyText1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'bodyText1'.
                            Theme.of(context).textTheme.bodyText1.copyWith(
                                                        ^^^^^^^^^
lib/widgets/home/search/custom_search_page.dart:456:38: Error: The getter 'subtitle1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'subtitle1'.
              style: theme.textTheme.subtitle1,
                                     ^^^^^^^^^
lib/screens/detail/product_title.dart:66:50: Error: The getter 'subtitle1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'subtitle1'.
              style: Theme.of(context).textTheme.subtitle1.copyWith(
                                                 ^^^^^^^^^
lib/screens/detail/product_title.dart:80:58: Error: The getter 'subtitle1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'subtitle1'.
                      style: Theme.of(context).textTheme.subtitle1.copyWith(
                                                         ^^^^^^^^^
lib/screens/detail/product_title.dart:117:52: Error: The getter 'subtitle1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'subtitle1'.
                style: Theme.of(context).textTheme.subtitle1.copyWith(
                                                   ^^^^^^^^^
lib/vendor/chat/messages.dart:152:40: Error: The getter 'headline6' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline6'.
                style: theme.textTheme.headline6.copyWith(
                                       ^^^^^^^^^
lib/vendor/chat/messages.dart:235:42: Error: The getter 'headline6' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline6'.
                  style: theme.textTheme.headline6.copyWith(
                                         ^^^^^^^^^
lib/services/helper/flash_helper.dart:56:66: Error: The getter 'subtitle1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'subtitle1'.
    return (theme.dialogTheme?.titleTextStyle ?? theme.textTheme.subtitle1)
                                                                 ^^^^^^^^^
lib/services/helper/flash_helper.dart:62:68: Error: The getter 'bodyText1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'bodyText1'.
    return (theme.dialogTheme?.contentTextStyle ?? theme.textTheme.bodyText1)
                                                                   ^^^^^^^^^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 780

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8m 0s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by minhcasi** [comment]
@GNAG1993 - please try to update your Flutter to the latest version by using this script
```
flutter channel stable
flutter upgrade --force
```

**Comment by GNAG1993** [comment]
Thanx, looks like issue resolved. Now I'm getting another issue like I'm using Cashfree as my payment gateway and app doesn't have native support for it. Is there any way to get native support for that?

**Comment by minhcasi** [comment]
@GNAG1993 - we can not see the Cashfree is supported native with Flutter framework, you could only use if by the Webview solution from the app - thank you!

**Comment by GNAG1993** [comment]
i got that and i am ok with that, but after finishing all stages of check out in app, like billing address, shipping address and payment gateway selection to cashfree, it opens check out page in webview again asking for address and other details. That's the error i'm getting.

**Comment by GNAG1993** [comment]
hello, i'm trying to get sha-1 key from script, how do I do that? I'm trying to edit buid.gradle to get signing reports but i'm unable to do that.

**Comment by minhcasi** [comment]
@GNAG1993 - you can create your own key that use for your app - pls check this guide https://flutter.dev/docs/deployment/android#signing-the-app

**Comment by minhcasi** [comment]
@GNAG1993 - let us know your checking

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
