### ISSUE TITLE
[FLUXSTORE 1.7.4] - Bad state failed to load [Image URL]

### ISSUE THREAD

**Issue by iamar1k92** [inspireui/support#3341]
App doesn't fetch images on latest version. It shows the following error while fetching the image. Every thing is setup correctly.
![error](https://user-images.githubusercontent.com/58983166/82564086-9c1e0e00-9b91-11ea-9a80-be1d9c864561.png)

**Comment by minhcasi** [comment]
@iamar1k92 - could you try to update this lib `extended_image 0.8.0`

Also, check your server setting if you have apply some caching? There are some new library upgrade from latest 1.7.4 that could cause the issue

**Comment by iamar1k92** [comment]
Still not fixed.

**Comment by minhcasi** [comment]
@iamar1k92 - could you help to check the Tools.dart to and return the FadeInImage instead if using ExtendedImage.network to see if it can fix your issue? Also help to debug to see which the related screen is using those images?

<img width="1028" alt="Screen Shot 2020-05-23 at 14 28 07" src="https://user-images.githubusercontent.com/1459805/82724634-a2cb9300-9d01-11ea-9658-fc68200a416c.png">

**Comment by iamar1k92** [comment]
do you have solution if the image url giving error on website. 

Access to image url denied
You don't have authorization to view this page.

HTTP ERROR 403

**Comment by minhcasi** [comment]
@iamar1k92 - there is the `LoadState.failed` function from the https://pub.dev/packages/extended_image library that could cover this case, you could try to add your own fail place holder to handle this kind of error

**Comment by minhcasi** [comment]
@iamar1k92 - hi man, pls share your checking 💯

**Comment by iamar1k92** [comment]
well, as per my research. There is no issue with the app..There is issue with the site...

**Comment by iamar1k92** [comment]
https://store77.in/wp-content/uploads/2020/03/rsz_hand-concept.png

can you access this image url?

**Comment by minhcasi** [comment]
No man

<img width="1053" alt="Screen Shot 2020-05-27 at 09 20 48" src="https://user-images.githubusercontent.com/1459805/82970797-5cc14880-9ffb-11ea-9760-f81c463d93d8.png">

**Comment by iamar1k92** [comment]
yes, that why can you help there is something to which is created by wp-rocket..

**Comment by minhcasi** [comment]
@iamar1k92 - we will help to investigate this caching mater issue from wp-rocket - thank you!

**Comment by minhcasi** [comment]
@iamar1k92 - could you share your solution?
