### ISSUE TITLE
App Build request

### ISSUE THREAD

**Issue by T3kken** [inspireui/support#3342]
I have  proposal for you because my Macbook  pro is blue screened! also I found it difficult to work with Firebase  yet I want this feature on the  apps.

Would you be able to build the apps for me? I would  give you access to my Firebase console, and all info from my woo-commerce site. all information you want.
The fee can be reasonable please. Let me know as soon as possible please.

Thanks

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@T3kken - please help to send the request to our email support@inspireui.com 

we may not available for the customization or installing the job at this time, due to my capacity team is limited under the CoV time. But the team will verify and confirm if they are available.
