### ISSUE TITLE
Open cart | When user registre a new account on app the information be empty on his account

### ISSUE THREAD

**Issue by aladmiral2** [inspireui/support#3343]
hi, 

(Proof of purchase https://live.staticflickr.com/65535/49919351733_8fcc2a1642_o.jpg ) 

I use Fluxstore Pro with OpenCart, and i have 2 problems: 

1- When the user register a new account using the app, address information be lost in his account after finishig regestring the account. 

https://live.staticflickr.com/65535/49919390583_96cfc5cf34_o.jpg

It also make a lot of address entry

2- when user wright a not with his order, it deosn't appear on his order. 

Best Regards

**Comment by premod** [comment]
same problem with me, also. my problems,
1. customer's phonenumber, country and state not enter into the backend,
2. shipping options always showing zero (may be due to point 1)

**Comment by aladmiral2** [comment]
is there anyone can help with this problem?!

**Comment by minhcasi** [comment]
We wanted to thank you for your patience during this busy time. We currently have reduced staff and a significantly higher volume of inquiries. We’re working as hard as we can to get to your request as soon as possible.

We sincerely apologize for the delay and hope you’re staying safe.

@minhtruong315

**Comment by minhtruong315** [comment]
Hi @aladmiral2 when you register new account. there are no fields for country and state. so you can't save country and state on backend.
Can u explain issue 2

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
