### ISSUE TITLE
[FluxStore Pro] Question about Related Products and Product Reviews

### ISSUE THREAD

**Issue by bikostudio** [inspireui/support#3344]
Hi @minhcasi 

How to :

1- Make the related products to be in two column not three.
2- How to disable product review.

Thank you

**Comment by minhcasi** [comment]
1. try to change 0.35 to 0.5
<img width="985" alt="Screen Shot 2020-05-22 at 08 35 45" src="https://user-images.githubusercontent.com/1459805/82622140-3cfae080-9c07-11ea-98f8-1f97342544a2.png">

2. enable this option to `true`
<img width="785" alt="Screen Shot 2020-05-22 at 08 30 50" src="https://user-images.githubusercontent.com/1459805/82621898-8c8cdc80-9c06-11ea-90da-db553f0bfe80.png">
