### ISSUE TITLE
Fluxstore Multivendor - Onboarding Screen

### ISSUE THREAD

**Issue by marknestor261** [inspireui/support#3345]
Step 1 (require): N/A
                        My onboarding screen does not work, even after setting it to true. After the splash screen, the app just starts.

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by marknestor261** [comment]
Hello, also when I select cash on delivery, the place my order button does not proceed, instead I get an error. I have attached a screenshot of the error.
Other payment methods work, they proceed, but cash on delivery doesn't.
![Screenshot_20200521-210820](https://user-images.githubusercontent.com/46901102/82591786-8a943080-9ba8-11ea-9b41-15b7dfc5baa0.png)

**Comment by minhcasi** [comment]
We wanted to thank you for your patience during this busy time. We currently have reduced staff and a significantly higher volume of inquiries. We’re working as hard as we can to get to your request as soon as possible.

We sincerely apologize for the delay and hope you’re staying safe.

@minhtruong315 - please help to investigate this issue

**Comment by minhtruong315** [comment]
Hi @marknestor261 can u upload your source code to github and invite me: minhtruong315@gmail.com
I'll check and fix on your source code.
Thanks

**Comment by marknestor261** [comment]
Hi, @minhtruong315 i have sent the source to your email (minhtruong315@gmail.com) from my email (marknestor261@gmail.com), through google drive. The file is gulastore-source.

**Comment by minhtruong315** [comment]
Hi @marknestor261 you're using old source code. please update the latest version and upgrade flutter 1.17

**Comment by marknestor261** [comment]
But the source code am using is the latest i downloaded from codecanyon.

**Comment by marknestor261** [comment]
Hi @minhtruong315 , i have tested again and the checkout button for cash on delivery takes long to respond, but eventually does. If someone tapped the checkout button many times due to the lack of response, it would order the number of times he/she has tapped checkout.

**Comment by minhcasi** [comment]
@marknestor261 - try to use the `pubspec.yaml` form the latest version.

You could also fix by upgrading `extended_image: 0.8.0`

**Comment by minhcasi** [comment]
Please also try to use the latest `1.7.4` - thank you!
