### ISSUE TITLE
when logging in onboardingscreen the home screen does not render correctly

### ISSUE THREAD

**Issue by joaonathan** [inspireui/support#3346]
when logging in onboardingscreen the home screen does not render correctly

![image](https://user-images.githubusercontent.com/9143192/82594868-1ee79e80-9b7b-11ea-8d5b-321a1fe901d1.png)

![image](https://user-images.githubusercontent.com/9143192/82594891-260eac80-9b7b-11ea-8f99-6712ca7eb8c8.png)

InkResponse widgets require a Material widget ancestor

**Comment by minhcasi** [comment]
@joaonathan - pls help us to rate this issue to the same of your ticket #3328
