### ISSUE TITLE
IOS BITCODE ISSUE VERSION 1.7.4

### ISSUE THREAD

**Issue by papaya1986** [inspireui/support#3347]
I can run app in the device but try to archive its showing 

"Bitcode bundle could not be generated because '/Users/sam/Documents/CHARISMATIX-1.7.4/ios/Flutter/Flutter.framework/Flutter' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file '/Users/sam/Documents/CHARISMATIX-1.7.4/ios/Flutter/Flutter.framework/Flutter' for architecture armv7"

Build settings bitcode "no" default ...

**Comment by minhcasi** [comment]
Hi, pls try to check if you Podfile is the same as this screenshot:

<img width="908" alt="Screen Shot 2020-05-22 at 09 05 38" src="https://user-images.githubusercontent.com/1459805/82623848-69186080-9c0b-11ea-9bb4-83bec2217137.png">

Try this script before Archive the app `flutter build ios`

**Comment by papaya1986** [comment]
issue is solved 
changed bit code Yes to No
and run flutter build ios

**Comment by papaya1986** [comment]
thank you
