### ISSUE TITLE
[ Fluxstore Pro 1.7.4 ]- Sort categories in the side menu doesn't work

### ISSUE THREAD

**Issue by Alnaggar94** [inspireui/support#3348]
- Hello, I noticed that you added sorting category by category id number in the config_xx.json in the pre-releases 1.7.4 it works in the categories screen but not effecting the side menu categories still sort randomly, The second problem in the category screen it sorts it correctly but when you click in the category it doesn't open the subcategory like before it opens the category directly.

screenshots : 
![b44](https://user-images.githubusercontent.com/49800146/82608294-0e5b1680-9bc3-11ea-8aac-0fd6b8320ae2.jpg)

the old category submenu is gone! it opens directly : 

![Screenshot_2020-05-22-00-23-47-920_com vaanz makhzony](https://user-images.githubusercontent.com/49800146/82608365-30549900-9bc3-11ea-88d4-fcb214edfeaa.jpg)

- I verified my purchase code and upload the Config Files through - http://private.inspireui.com

**Comment by minhcasi** [comment]
@Alnaggar94 - this is missing feature, we will upgrade it on the next release - thank you!

**Comment by vumanhsn97** [comment]
@Alnaggar94 
Fixed in next version. You can update by replace list file in this zip file to your app folder. 
[archive.zip](https://github.com/inspireui/support/files/4666850/archive.zip)

**Comment by Alnaggar94** [comment]
@vumanhsn97 - Thank you so much, I really appreciate your help It works fine now.
