### ISSUE TITLE
Arabic language problem in addition how to remove other languages plus additional questions and other issues

### ISSUE THREAD

**Issue by abedfatafta** [inspireui/support#3349]
Step 1 (require): detail issues and screenshots

![image](https://user-images.githubusercontent.com/16276919/82610144-88d96580-9bc6-11ea-804a-d61055957a95.png)
for all languages other than english .
in addition , i just want to have 2 languages, arabic , english and remove other languages .
1-remove all other countries other than one because its local app. 
2-is there is away to remove some menu items unusable ?
3- is there is a way to display site page inside the app ?
4- there is GUI Bug 
![image](https://user-images.githubusercontent.com/16276919/82610869-e1f5c900-9bc7-11ea-80c8-914722c62fa0.png)
5- 
![image](https://user-images.githubusercontent.com/16276919/82622988-cdc1c400-9be7-11ea-974d-b515358d1ac1.png) images for products not symatric not fixed hight and width .

6- product with visibility (hidden ) show up in the app , how i can control this also products hidden from search attributes show up in the app search 
all of the following products are hidden , but showing in search 
![image](https://user-images.githubusercontent.com/16276919/82623408-c9e27180-9be8-11ea-809b-93ebcce22230.png)

7- default woocommerce shipping classes calculation not work in the app, it just show basic shipping not support main woocommerce  shipping classes https://docs.woocommerce.com/document/product-shipping-classes/
8- shipping zone by state show all states options. not only selected state , this is woocommerce core feature not implemented 
https://docs.woocommerce.com/document/setting-up-shipping-zones/
9- store shipping is main feature in wcfm , the app read woocommerce option as store shipping with 0 cost while it must extract that store shipping options which is (same as woocommerce ) 

10 - vendor orders listing how vendor can see the orders - with notifications ( it can be embeded from web at this stage from wcfm then add it ) 

11- when click on category in home page   show all  tab showing nothing 
![image](https://user-images.githubusercontent.com/16276919/82624323-e97a9980-9bea-11ea-9e7e-20592e2f90dd.png)

and when you click sub category it show 
![image](https://user-images.githubusercontent.com/16276919/82624345-f6978880-9bea-11ea-9583-5c588d40ca9e.png)

when u click back it must back to  first screen with subcategories . but its take you to home screen 
![image](https://user-images.githubusercontent.com/16276919/82624375-09aa5880-9beb-11ea-8ba4-00d5b9a1954b.png)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)
#3176
#3306
#2663
#2923
#2872
#2406

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by minhtruong315** [comment]
Hi @abedfatafta can u upload your source code to github then invite me: minhtruong315@gmail.com
I will you check and fix on it

**Comment by abedfatafta** [comment]
> u check and fix on it

its original source code downloaded , i thought its from customization but i tested it with fresh version the same issues there , check with wcfm

**Comment by minhtruong315** [comment]
Dont you change anything config?

**Comment by abedfatafta** [comment]
> Dont you change anything config?

on my code changed , in fresh one no change , but now i have uploaded my customized one ( i have fixed by replacing config_ar content  added you to thre repo

**Comment by abedfatafta** [comment]
> Dont you change anything config?

very important also how to fix the image sizes for products in categories and main page its varies not fixed now look at screenshots

**Comment by minhtruong315** [comment]
hi @abedfatafta pls pull source code to fix issue on home screen and language screen

**Comment by Alnaggar94** [comment]
> 6- product with visibility (hidden ) show up in the app , how i can control this also products hidden from search attributes show up in the app search.

Same here, please suggest us a solution.

**Comment by abedfatafta** [comment]
> hi @abedfatafta pls pull source code to fix issue on home screen and language screen

alright i will do  , what about image size  fixing ? and other bugs ? and missing features and suggestions ?

**Comment by emadpost2016** [comment]
same erro here are you find solution when change to arbic

**Comment by minhcasi** [comment]
@abedfatafta - other missing features are checking in our queue, we will upgrade it on next release `1.7.5` - thank you!

**Comment by abedfatafta** [comment]
@minhcasi @minhtruong315  still waiting , when its expected to get the new release ? can I get Access to  development git?

**Comment by minhtruong315** [comment]
Hi @abedfatafta We just released version 1.7.4. it fixed almost issues and add more features. Please try your issues on that version and update MStore Api plugin as well. 
We're working hard to update Fluxstore MV as well.
Thanks.

**Comment by minhtruong315** [comment]
Hi @abedfatafta please download version 1.7.5 and check again.
Thanks

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
