### ISSUE TITLE
[MStore] Picture Product not show

### ISSUE THREAD

**Issue by badaiardiat** [inspireui/support#335]
**Mandatory Info (please complete the following information):**
 - Product: mstore-expo
 - Your Purchased Code: e22dd2dc-9b33-4936-89e5-eac089b698ac

**Describe the issues**
Hallo dude, help me image product still not show 
iam aready following step by step our document but still error

**Screenshots**
https://imgur.com/a/3FJNvRi

helpp me plis

**Comment by badaiardiat** [comment]
help plis

**Comment by minhcasi** [comment]
Hi, could you check the product display size setting - https://docs.mstore.io/advance-customize-app/woocommerce-setting 

Thank you!
