### ISSUE TITLE
Error in Failed Assertion

### ISSUE THREAD

**Issue by harjono-flux** [inspireui/support#3350]
Appear this error when first launch apps. Already flutter clean and invalidate cache/restart before run the app
![Screen Shot 2020-05-11 at 10 01 40](https://user-images.githubusercontent.com/64935574/82619632-0aea7e00-9c09-11ea-949c-b35ee3ab8edf.png)

I already sent you my whole program
![Screen Shot 2020-05-22 at 08 51 53](https://user-images.githubusercontent.com/64935574/82619903-bf849f80-9c09-11ea-8518-91e08e085de3.png)

Plis help, im stuck in this almost 1 week

**Comment by minhcasi** [comment]
@harjono-flux - the latest release 1.7.4 already fixed this issue, please help to download 👍  - thank you!

**Comment by harjono-flux** [comment]
how to update, without lost anysetting we have done?

**Comment by minhcasi** [comment]
@harjono-flux - you could try to override some config json file from the latest release to see if if can fix this issue?

If it does not work, try to backup your customization via Git repository and manually copy your config files to the latest download package `1.7.4`

**Comment by harjono-flux** [comment]
hmmm... i hope you make tools to update automatically. Because, 1 by 1 page we must try to setting manually everytime you launch the update. But thanks to support team for the hard work
