### ISSUE TITLE
Fluxstore MV 1.7.3 - Woocommerce + WCFM Issues

### ISSUE THREAD

**Issue by mixkey23** [inspireui/support#3351]
Step 1 (require): detail issues and screenshots
1- App's stores list isnt loading vendor's header image or gravatar configured on their wcfm profile. There is no rating showed too Its normal?
![store_sin_banner](https://user-images.githubusercontent.com/62155503/82394693-520d1f00-9a0f-11ea-8fdd-bdfdc1257de3.jpeg)

2- Can we have a switch in config.json, to only show stores that meet the condition: 
store statu is active and product published qty its at least 1 ?

![inactive_or_empty_stores](https://user-images.githubusercontent.com/62155503/82567508-14a9ae00-9b43-11ea-926a-b5da41847d72.jpeg)
In App's screenshot above:

**Store that shouldn't be shown:** 
Nicashamacas - Reason: Do not have at least one published product in their catalog
Home And Swag - Same reason that Nicashamacas store
BFF SHOPPING MIX - Reason: This store is marked as inactive on WCFM
BARA STORE PTY - Same reason that BFF SHOPPING MIX store

**Store that are shown and should be:**
Jelani Suplidora Medica - Reason: Have one or more published products and its state is ACTIVE on WCFM

3- Question: Are there a way to edit products or its not supported yet ?

4- The App are unable to register new user or vendor, its showing the following message "Please agree with out terms" even with all fields filled and agreement checked.
![new_user](https://user-images.githubusercontent.com/62155503/82567860-98639a80-9b43-11ea-8157-57dc6a5dc68b.jpeg)

5- I cant setup Google Sign In:
In your video/guide to [Setup Google Login and Facebook Login (Flutter E-Commerce App In 10 Minutes)](https://www.youtube.com/watch?v=14ALBSwvV4E) you say that there is a file `key-debug.properties` for SHA1 and SHA256 key's generation, I cannot see this file on the source downloaded FluxStore Multivendor 1.7.3, there is only a file `key.properties` i follow the [google/guide](https://developers.google.com/android/guides/client-auth) you mention too, without success. When i try to login i get fluxstore Oauth instead mine.

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by minhtruong315** [comment]
Hi @mixkey23 can u try to replace file screens/users/registration.dart to fix register new user
[registration.dart.zip](https://github.com/inspireui/support/files/4665721/registration.dart.zip)

**Comment by mixkey23** [comment]
@minhtruong315 i have tried, and the message its not shown, but the button stay on "Loading..."

**Comment by minhtruong315** [comment]
@mixkey23 can u upload your source code to github then invite me: minhtruong315@gmail.com
I'll check and fix on your source code. 
Thanks

**Comment by mixkey23** [comment]
> 
> 
> @mixkey23 can u upload your source code to github then invite me: [minhtruong315@gmail.com](mailto:minhtruong315@gmail.com)
> I'll check and fix on your source code.
> Thanks

Do you mean, upload the source folder Fluxstore > source ?

**Comment by minhtruong315** [comment]
yes. please upload your source code to git repo.

**Comment by mixkey23** [comment]
> 
> 
> yes. please upload your source code to git repo.

Ok, i will upload asap

**Comment by mixkey23** [comment]
> 
> 
> > yes. please upload your source code to git repo.
> 
> Ok, i will upload asap

Github its extremely slow, can i upload it to drive or similar ?

**Comment by minhtruong315** [comment]
you can upload to gitlab or bitbucket.

**Comment by mixkey23** [comment]
> you can upload to gitlab or bitbucket.

Pushing to github...  once it  finish, I will notify

Thanks

**Comment by mixkey23** [comment]
@minhtruong315 i have sent the invitaton

**Comment by minhtruong315** [comment]
Hi @mixkey23 please update MStore Api plugin and change some functions to fix store issues
- Replace services/wcfm.dart file
[wcfm.dart.zip](https://github.com/inspireui/support/files/4667018/wcfm.dart.zip)
- Replace fromWCFMJson function on lib/vendor/store/store_model.dart like this
``` 
Store.fromWCFMJson(Map<String, dynamic> parsedJson) {
    id = parsedJson["vendor_id"];
    name = parsedJson["vendor_shop_name"];
    email = parsedJson["vendor_email"];
    rating = 0.0;
    image = parsedJson["settings"] != null &&
            parsedJson["settings"]["gravatar"].toString().isNotEmpty
        ? parsedJson["settings"]["gravatar"]
        : null;
    address = parsedJson["vendor_address"];
    if (parsedJson["settings"] != null) {
      banner = parsedJson["settings"]["mobile_banner"].toString().isNotEmpty
          ? parsedJson["settings"]["mobile_banner"]
          : (parsedJson["settings"]["banner"].toString().isNotEmpty
              ? parsedJson["settings"]["banner"]
              : image);
    }
    phone =
        parsedJson["settings"] != null ? parsedJson["settings"]["phone"] : null;
  }
```

**Comment by mixkey23** [comment]
@minhtruong315 Many thanks for that fast support, i am amazed!

**For issue 1:**
I have made the changes and now the stores show their banner and address correctly

What about store rating, can calculate it based on vendor reviews?

In WCFM Rest api there are endpoint to get that info:
**https://domain.com/wp-json/wcfmmp/v1/reviews**

This show all reviews for stores like this:

    {
        "ID": "1",
        "vendor_id": "18", <--------- Whe have the vendor_id
        "author_id": "0",
        "author_name": "Customer Name",
        "author_email": "client@mail.com",
        "review_title": "",
        "review_description": "Like the color!",
        "review_rating": "5", <--------  Rating obtained
        "approved": "1",
        "created": "2020-05-12 06:38:01",
        "author_image": "https://domain.com/wp-content/plugins/wc-frontend-manager/assets/images/avatar.png"
    }

So i think adding all the reviews for particular vendor, we can get an average rating ?

**Regarding issue 2: Show or not a vendor in the list:**

I was seeing the wcfm json response, and i think that:

For a disabled vendor the field **disable_vendor** = "1" otherwise **disable_vendor** = ""
For a offline vendor to public the field **is_store_offline** = "yes" otherwise **is_store_offline** = ""

Example: 
{
        "vendor_id": 5,
        "vendor_display_name": "Vendor display Name",
        "vendor_shop_name": "STORE NAME",
        "vendor_email": "mail@gmail.com",
        "vendor_address": "Addres",
        "vendor_phone": "Phone",
        "disable_vendor": "1", <--- This vendor is marked as disabled in WCFM
        "is_store_offline": "yes", <--- This vendor is marked as offline in WCFM
        "email_verified": "1",
         ...............
}

So i think the condition for show an store in list should be:

if disable_vendor != "1" AND is_store_offline != "yes"  otherwise not show it

**Comment by mixkey23** [comment]
> 
> 
> Hi @mixkey23 please update MStore Api plugin and change some functions to fix store issues
> 
>     * Replace services/wcfm.dart file
>       [wcfm.dart.zip](https://github.com/inspireui/support/files/4667018/wcfm.dart.zip)
> 
>     * Replace fromWCFMJson function on lib/vendor/store/store_model.dart like this
> 
> 
> ```
> Store.fromWCFMJson(Map<String, dynamic> parsedJson) {
>     id = parsedJson["vendor_id"];
>     name = parsedJson["vendor_shop_name"];
>     email = parsedJson["vendor_email"];
>     rating = 0.0;
>     image = parsedJson["settings"] != null &&
>             parsedJson["settings"]["gravatar"].toString().isNotEmpty
>         ? parsedJson["settings"]["gravatar"]
>         : null;
>     address = parsedJson["vendor_address"];
>     if (parsedJson["settings"] != null) {
>       banner = parsedJson["settings"]["mobile_banner"].toString().isNotEmpty
>           ? parsedJson["settings"]["mobile_banner"]
>           : (parsedJson["settings"]["banner"].toString().isNotEmpty
>               ? parsedJson["settings"]["banner"]
>               : image);
>     }
>     phone =
>         parsedJson["settings"] != null ? parsedJson["settings"]["phone"] : null;
>   }
> ```

Hi, @minhtruong315 the banners and info of the stores get loaded but now i cant paginate
When i try to swipe up the app does not load more items

**Comment by mixkey23** [comment]
> Hi @mixkey23 please update MStore Api plugin and change some functions to fix store issues
> 
> * Replace services/wcfm.dart file
>   [wcfm.dart.zip](https://github.com/inspireui/support/files/4667018/wcfm.dart.zip)
> * Replace fromWCFMJson function on lib/vendor/store/store_model.dart like this
> 
> ```
> Store.fromWCFMJson(Map<String, dynamic> parsedJson) {
>     id = parsedJson["vendor_id"];
>     name = parsedJson["vendor_shop_name"];
>     email = parsedJson["vendor_email"];
>     rating = 0.0;
>     image = parsedJson["settings"] != null &&
>             parsedJson["settings"]["gravatar"].toString().isNotEmpty
>         ? parsedJson["settings"]["gravatar"]
>         : null;
>     address = parsedJson["vendor_address"];
>     if (parsedJson["settings"] != null) {
>       banner = parsedJson["settings"]["mobile_banner"].toString().isNotEmpty
>           ? parsedJson["settings"]["mobile_banner"]
>           : (parsedJson["settings"]["banner"].toString().isNotEmpty
>               ? parsedJson["settings"]["banner"]
>               : image);
>     }
>     phone =
>         parsedJson["settings"] != null ? parsedJson["settings"]["phone"] : null;
>   }
> ```

Hi @minhtruong315 the wcfm.dart file load store's banner ok, but only 1st page get loaded, when you swipe Up, it does not load next page

**Comment by minhtruong315** [comment]
let me check. thanks

**Comment by minhtruong315** [comment]
Hi @mixkey23 you can replace getStores function in vendor/store/store_model.dart like this to fix load more stores
```
void getStores({lang, page, callback}) async {
    try {
      isLoading = true;
      List<Store> list = await _service.getStores(lang: lang, page: page);
      if (page > 1) {
        stores = [...stores, ...list];
      } else {
        stores = list;
      }
      isLoading = false;
      message = null;
      callback(list.isEmpty);
      notifyListeners();
    } catch (err) {
      callback(true);
      isLoading = false;
      message =
          "There is an issue with the app during request the data, please contact admin for fixing the issues " +
              err.toString();
      notifyListeners();
    }
  }
```

**Comment by mixkey23** [comment]
> Hi @mixkey23 you can replace getStores function in vendor/store/store_model.dart like this to fix load more stores
> 
> ```
> void getStores({lang, page, callback}) async {
>     try {
>       isLoading = true;
>       List<Store> list = await _service.getStores(lang: lang, page: page);
>       if (page > 1) {
>         stores = [...stores, ...list];
>       } else {
>         stores = list;
>       }
>       isLoading = false;
>       message = null;
>       callback(list.isEmpty);
>       notifyListeners();
>     } catch (err) {
>       callback(true);
>       isLoading = false;
>       message =
>           "There is an issue with the app during request the data, please contact admin for fixing the issues " +
>               err.toString();
>       notifyListeners();
>     }
>   }
> ```

Hi, im gonna try

Thanks

**Comment by mixkey23** [comment]
Yup, that fix the issue with stores list pagination

Thanks

**Comment by minhtruong315** [comment]
are your issues resolved?

**Comment by mixkey23** [comment]
> 
> 
> are your issues resolved?

Hi @minhtruong315 issues 1, 2 and 3 are resolved Thanks for that

Number 4 is more like a question, i cant see how a vendor can edit a product through app s that posible right now?

Im still having problems to signup using google registration
5- I cant setup Google Sign In:
In your video/guide to Setup Google Login and Facebook Login (Flutter E-Commerce App In 10 Minutes) you say that there is a file key-debug.properties for SHA1 and SHA256 key's generation, I cannot see this file on the source downloaded FluxStore Multivendor 1.7.3, there is only a file key.properties i follow the google/guide you mention too, without success can you help me with that?

Why the file mentioned in the video is not in the source code i downloaded (1.7.3) how can i generate the correct keys to put in firebase and google's project

**Comment by minhtruong315** [comment]
Hi @mixkey23 can u upload your source code to github and invite me: minhtruong315@gmail.com
I'll check google sign in on your source code

**Comment by mixkey23** [comment]
> 
> 
> Hi @mixkey23 can u upload your source code to github and invite me: [minhtruong315@gmail.com](mailto:minhtruong315@gmail.com)
> I'll check google sign in on your source code

Sure, i already upload it to github and sent you the invitation as collaborator

**Comment by minhtruong315** [comment]
<img width="944" alt="Screen Shot 2020-05-27 at 3 24 08 PM" src="https://user-images.githubusercontent.com/10402500/82995757-34067680-a02e-11ea-9c85-66246f759539.png">
Hi @mixkey23 I see you have 2 key files. which did you create?

**Comment by mixkey23** [comment]
Hi @minhtruong315 no i did not created them

They comes in the zip source code downloaded from envato:

https://codecanyon.net/item/fluxstore-multi-vendor-flutter-ecommerce-full-app/25013325

Here are the screen from zip file:

![Annotation 2020-05-27 121240](https://user-images.githubusercontent.com/62155503/83051777-13c9be00-a014-11ea-847d-db39fa5a010b.png)

![Annotation 2020-05-27 121402](https://user-images.githubusercontent.com/62155503/83051817-1cba8f80-a014-11ea-91c6-d4c6b96b714f.png)

**Comment by minhcasi** [comment]
@mixkey23 - try to create your own `jks` key - https://flutter.dev/docs/deployment/android#create-a-keystore

**Comment by mixkey23** [comment]
> 
> 
> @mixkey23 - try to create your own `jks` key - https://flutter.dev/docs/deployment/android#create-a-keystore
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/b79d5f795eac013611f2dac92850a689fc9d3d46/68747470733a2f2f666c75747465722e6465762f696d616765732f666c75747465722d6c6f676f2d73686172696e672e706e67">**[Build and release an Android app](https://flutter.dev/docs/deployment/android)**How to prepare for and release an Android app to the Play store.

Ok let me try

**Comment by mixkey23** [comment]
> 
> 
> @mixkey23 - try to create your own `jks` key - https://flutter.dev/docs/deployment/android#create-a-keystore
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/b79d5f795eac013611f2dac92850a689fc9d3d46/68747470733a2f2f666c75747465722e6465762f696d616765732f666c75747465722d6c6f676f2d73686172696e672e706e67">**[Build and release an Android app](https://flutter.dev/docs/deployment/android)**How to prepare for and release an Android app to the Play store.

Hi @minhtruong315 i follow the guide you provide me, and i was able to signup via email and google Oauth, i can see the user's email in firebase and my site, however despite creating the user in both ways, the application keeps in SignUp screen with button text Loading ...

![after_press_signup](https://user-images.githubusercontent.com/62155503/83187210-6b8b2680-a0f3-11ea-9c7d-cd9134fed582.jpeg)

**User is created in Firebase**
![firebase-USERS](https://user-images.githubusercontent.com/62155503/83187513-e3595100-a0f3-11ea-9776-876bee03724e.png)

**Comment by minhtruong315** [comment]
Hi @mixkey23 did you create firebase like this guide:  https://www.youtube.com/watch?v=C_9mk_MmvOQ
You need to  enable Cloud Firestore, Realtime database, Storage...
Please check again and let me know.
Thanks

**Comment by mixkey23** [comment]
> 
> 
> Hi @mixkey23 did you create firebase like this guide: https://www.youtube.com/watch?v=C_9mk_MmvOQ
> You need to enable Cloud Firestore, Realtime database, Storage...
> Please check again and let me know.
> Thanks

Hi @minhtruong315 i will try, but now im getting this error regarding  onboarding screen

i tried with flutter clean without success

![oboard_screen](https://user-images.githubusercontent.com/62155503/83209155-3bf11400-a11d-11ea-834c-564604471ae6.jpeg)

**Comment by mixkey23** [comment]
> 
> 
> > Hi @mixkey23 did you create firebase like this guide: https://www.youtube.com/watch?v=C_9mk_MmvOQ
> > You need to enable Cloud Firestore, Realtime database, Storage...
> > Please check again and let me know.
> > Thanks
> 
> Hi @minhtruong315 i will try, but now im getting this error regarding onboarding screen
> 
> i tried with flutter clean without success
> 
> ![oboard_screen](https://user-images.githubusercontent.com/62155503/83209155-3bf11400-a11d-11ea-834c-564604471ae6.jpeg)
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/66fd6d54022c9b08125eea22471a43052b667c2c/68747470733a2f2f732e7974696d672e636f6d2f7974732f696d672f66617669636f6e2d76666c3871535632462e69636f">**[YouTube](https://www.youtube.com/watch?v=C_9mk_MmvOQ)**Enjoy the videos and music you love, upload original content, and share it all with friends, family, and the world on YouTube.

Hi @minhtruong315 i think i found the cause of the error above:

I want to make spanish as a main or default language on the app so i changed:

in common/config/general.dart

   const kAppConfig = 'lib/config/**config_es.json**';

const kAdvanceConfig = {
  "DefaultLanguage": "**es**", <--- This was causing the error above so switch to en again 
  "DetailedBlogLayout": kBlogLayout.halfSizeImageType,
  "EnablePointReward": true,
   .....
}

**Comment by mixkey23** [comment]
Where i can set the default app language?

**Comment by stickypages** [comment]
@mixkey23 I found that doing a print() on the response from signing up, it could be an issue with the users password. I put in an extra if statement on 
registration.dart (line 206) 

Maybe this will help.
```
onPressed: () async {
                            try {
                              await _auth.createUserWithEmailAndPassword(
                                  email: username, password: password);
                            } catch (e) {
                              if(password.length < 6) {
                                _snackBar('Password should be at least 6 characters long');
                              }
                            }
                            _submitRegister(
                                firstName, lastName, username, password);
                          },
```

**Comment by mixkey23** [comment]
> 
> 
> Where i can set the default app language?



> prin

@minhtruong315 i made the changes and it works, im able to signup through facebook and google

**Comment by mixkey23** [comment]
@minhtruong315 can we ask 

> 
> 
> > Where i can set the default app language?
> 
> > prin
> 
> @minhtruong315 i made the changes and it works, im able to signup through facebook and google
I have other issue now:

Due to payment gateways installed on my site i cant use native payment on app.

So im using OnepagePayment, to use webview redirect to my site, but i have a problem.

Woocommerce shows cities, based on state selected, this is not working on the app, but browsers working fine, it seems to me something related to javascript or jquery

I want to know, if the App's webview integrates javascript or jquery.

Or if we can call it from webview or something to make that function work correctly?

**Comment by minhtruong315** [comment]
Hi @mixkey23 please download the latest version on codecanyon and check your issues. We just released it. Please update MStore Api plugin as well

**Comment by mixkey23** [comment]
Hi @minhtruong315 I will upgrade and test. 
I want to know if this upgrade have the option to see vendor's client orders and if the vendor can update or edit existent products.

**Comment by minhtruong315** [comment]
The latest version is fixed some issues in prev version. and you can see vendor name in cart.

**Comment by mixkey23** [comment]
> 
> 
> The latest version is fixed some issues in prev version. and you can see vendor name in cart.

Hi @minhtruong315 im testing it right now with all features i had on 1.7.3

**Comment by mixkey23** [comment]
> 
> 
> > The latest version is fixed some issues in prev version. and you can see vendor name in cart.
> 
> Hi @minhtruong315 im testing it right now with all features i had on 1.7.3

Do you have included in this releasee a screen for edit/update products?

**Comment by mixkey23** [comment]
@minhtruong315 I have tested 1.7.4 and until now i only have one issue
Do i have to open a new issue or its not needed.

When app start by first time the last onboarding screen that show button register or login are in blank. however ifi i do clic on them the action is executed without problems
im using spanish language as default an isCached its activated
![WhatsApp Image 2020-06-02 at 5 10 05 PM](https://user-images.githubusercontent.com/62155503/83578350-281e2700-a4fc-11ea-84d8-e07678f3098c.jpeg)

**Comment by minhtruong315** [comment]
Hi @mixkey23 Please commit the new source code to repo. I will pull your source code and check on it.
Thanks

**Comment by mixkey23** [comment]
> 
> 
> Hi @mixkey23 Please commit the new source code to repo. I will pull your source code and check on it.
> Thanks

Ok i will commit the new version

**Comment by mixkey23** [comment]
> 
> 
> Hi @mixkey23 Please commit the new source code to repo. I will pull your source code and check on it.
> Thanks

@minhtruong315 Ready i have commited the new version to my repo

**Comment by minhtruong315** [comment]
Hi @mixkey23 i checked your source code. it's working well
<img width="525" alt="Screen Shot 2020-06-05 at 9 46 36 AM" src="https://user-images.githubusercontent.com/10402500/83831399-82440580-a711-11ea-8a9a-afbbd00af90d.png">

**Comment by mixkey23** [comment]
> 
> 
> Hi @mixkey23 i checked your source code. it's working well
> <img alt="Screen Shot 2020-06-05 at 9 46 36 AM" width="525" src="https://user-images.githubusercontent.com/10402500/83831399-82440580-a711-11ea-8a9a-afbbd00af90d.png">

That's weird

**Comment by mixkey23** [comment]
> 
> 
> > Hi @mixkey23 i checked your source code. it's working well
> > <img alt="Screen Shot 2020-06-05 at 9 46 36 AM" width="525" src="https://user-images.githubusercontent.com/10402500/83831399-82440580-a711-11ea-8a9a-afbbd00af90d.png">
> 
> That's weird

Also, can you test, create a product as vendor ?

**Comment by mixkey23** [comment]
> 
> 
> > Hi @mixkey23 i checked your source code. it's working well
> > <img alt="Screen Shot 2020-06-05 at 9 46 36 AM" width="525" src="https://user-images.githubusercontent.com/10402500/83831399-82440580-a711-11ea-8a9a-afbbd00af90d.png">
> 
> That's weird

@minhtruong315 ok for some reason i did a flutter clean and its show the buttons fine

However im facing a few issues:

1- Some product's categories in Home screen are blank (**In Fluxbuilder they just are shown fine**) 
on previous version (1.7.3) this was working fine.

![some_categories_no_products](https://user-images.githubusercontent.com/62155503/83921938-111e4580-a745-11ea-8891-6bec42d389fb.jpeg)


The console log is showing this error:

```

getAsync END [endPoint:products?lang=es&status=publish&category=543] url:products?lang=es&status=publish&category=543
I/flutter ( 9797): #0      int._throwFormatException (dart:core-patch/integers_patch.dart:133:5)
I/flutter ( 9797): #1      int._parseRadix (dart:core-patch/integers_patch.dart:144:16)
I/flutter ( 9797): #2      int._parse (dart:core-patch/integers_patch.dart:102:12)
I/flutter ( 9797): #3      int.parse (dart:core-patch/integers_patch.dart:65:12)
I/flutter ( 9797): #4      new Store.fromWCFMJson (package:fstore/vendor/store/store_model.dart:94:14)
I/flutter ( 9797): #5      WCFMWidget.updateProductObject (package:fstore/widgets/frameworks/wcfm/index.dart:12:27)
I/flutter ( 9797): #6      WooCommerce.fetchProductsLayout (package:fstore/services/woo_commerce.dart:225:41)
I/flutter ( 9797): <asynchronous suspension>
I/flutter ( 9797): #7      Services.fetchProductsLayout (package:fstore/services/index.dart:207:23)
I/flutter ( 9797): #8      ProductListLayout.build.getProductLayout.<anonymous closure> (package:fstore/widgets/home/product_list_layout.dart:158:27)
I/flutter ( 9797): #9      new Future.sync (dart:async/future.dart:224:31)
I/flutter ( 9797): #10     AsyncMemoizer.runOnce (package:async/src/async_memoizer.dart:43:45)
I/flutter ( 9797): #11     ProductListLayout.build.getProductLayout (package:fstore/widgets/home/product_list_layout.dart:152:5
I/flutter ( 9797): FormatException: Invalid radix-10 number (at character 1)
I/flutter ( 9797): null
I/flutter ( 9797): ^
```

2- On categories screen, when click on some of subcategories, even if they have items on it, the screen show  no product is found. **(I test "hideOutOfStock": false, and that didnt works.)**

Selected category:
![hombre_items](https://user-images.githubusercontent.com/62155503/83924665-c30c4080-a74a-11ea-8411-a3cd6c9ad6d3.jpeg)


Screen shown:
![hombre_empty](https://user-images.githubusercontent.com/62155503/83924252-cbb04700-a749-11ea-9841-ade56c8e6586.jpeg)

Error show in console:

```
I/flutter (18382): [2020-06-05 21:34:52.491101Z][Merkalat][wocommerce_api][16:34:52.490643] getAsync END [endPoint:products?status=publish&lang=es&per_page=20&page=1&category=544] url:products?status=publish&lang=es&per_page=20&page=1&category=544
I/flutter (18382): #0      int._throwFormatException (dart:core-patch/integers_patch.dart:133:5)
I/flutter (18382): #1      int._parseRadix (dart:core-patch/integers_patch.dart:144:16)
I/flutter (18382): #2      int._parse (dart:core-patch/integers_patch.dart:102:12)
I/flutter (18382): #3      int.parse (dart:core-patch/integers_patch.dart:65:12)
I/flutter (18382): #4      new Store.fromWCFMJson (package:fstore/vendor/store/store_model.dart:94:14)
I/flutter (18382): #5      WCFMWidget.updateProductObject (package:fstore/widgets/frameworks/wcfm/index.dart:12:27)
I/flutter (18382): #6      WooCommerce.fetchProductsByCategory (package:fstore/services/woo_commerce.dart:344:41)
I/flutter (18382): <asynchronous suspension>
I/flutter (18382): #7      Services.fetchProductsByCategory (package:fstore/services/index.dart:190:23)
I/flutter (18382): #8      ProductModel.getProductsList (package:fstore/models/product/product_model.dart:116:39)
I/flutter (18382): #9      Product.showList (package:fstore/models/product/product.dart:205:15)
I/flutter (18382): #10     SubItem.build.<anonymous closure> (package:fstore/screens/categories/card.dart:227:27)
I/flutter (18382): #11     _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:779:19)
```

3- How can i set a fixed height for product images, so no overflow message its not show in app and no transparent background?
![product_card_height_transparent](https://user-images.githubusercontent.com/62155503/83924274-db2f9000-a749-11ea-8b9d-ed987c152e0c.jpeg)


4- Can i disable the "overflow" message?
![overflow_message](https://user-images.githubusercontent.com/62155503/83924593-9a844680-a74a-11ea-8195-8a43d3435429.jpeg)

**Comment by mixkey23** [comment]
@minhtruong315  im wating this so i can finally publish my client's app

**Comment by mixkey23** [comment]
@minhcasi  can my gitlab user @mixkey23  be added to your gitlab repo, so can test pre-releases ?

**Comment by minhtruong315** [comment]
Hi @mixkey23 please pull the source code. I fixed showing products on home

**Comment by minhtruong315** [comment]
@mixkey23 for products in category, it's showing well
<img width="428" alt="Screen Shot 2020-06-08 at 4 22 55 PM" src="https://user-images.githubusercontent.com/10402500/84014380-673cf400-a9a4-11ea-9cc9-aee3c047e22a.png">

**Comment by minhtruong315** [comment]
@mixkey23 I fixed height for product's images. pls check again and let me know.
Thanks

**Comment by mixkey23** [comment]
> @mixkey23 I fixed height for product's images. pls check again and let me know.
> Thanks

@minhtruong315 Hi, you fixed it in version 1.7.4 or 1.7.5
I mean, with this I don't have to upgrade to 1.7.5?

**Comment by minhtruong315** [comment]
I fixed on your repo.

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!

**Comment by mixkey23** [comment]
Hi @minhtruong315 there are few issues yet on the app
i was having problems with my internet provider, so i couldnt check you answer

When im on store products, the list get loop, so is like infinite and never finish
