### ISSUE TITLE
Magento - Order By onSale and Featured does nothing.

### ISSUE THREAD

**Issue by bdairy** [inspireui/support#3352]
Step 1 (require): detail issues and screenshots

Magento - Order By onSale and Featured does nothing.

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)
Already verified many time

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@bdairy - thank you for your suggestion - this feature is not available for Magento - we will investigate and will make the decision to see if could hide or upgrade the API to support it

**Comment by bdairy** [comment]
@minhcasi thanks for the response,, I suggest that this sort by should be configurable.. my client want to sort by Price,, or date,, so we could specify in config what to show and what to hide as  a sort by element..
I need to do it now from my side,, I hope you guys got it solved soon.

Thanks

**Comment by minhcasi** [comment]
@bdairy - could you try to research if there is extra param from Magento to support for those features?

<img width="1312" alt="Screen Shot 2020-05-23 at 14 02 47" src="https://user-images.githubusercontent.com/1459805/82724132-17043780-9cfe-11ea-8780-ab85e1b36fb0.png">

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
