### ISSUE TITLE
[Fluxnews] Youtube Embed not showing correctly

### ISSUE THREAD

**Issue by bidfor** [inspireui/support#3353]
https://github.com/inspireui/support/issues/3287
Ticket closed. Problem not solved.

**Comment by minhcasi** [comment]
<img width="948" alt="Screen Shot 2020-05-22 at 11 29 46" src="https://user-images.githubusercontent.com/1459805/82631408-8c4d0b00-9c1f-11ea-86ce-d8b4574e7a0c.png">

it's closed as we don't see your reply?

**Comment by minhcasi** [comment]
can you able to share the website that includes that Youtube URL? Thanks

**Comment by bidfor** [comment]
https://www.dimsumdaily.hk/parody-video-by-corridor-digital-shows-how-a-bosstown-dynamics-robot-retaliates-after-being-attacked/

**Comment by minhcasi** [comment]
Thank you for a quick reply, I've sent to the team for checking and will keep update on this ticket - thanks

**Comment by minhcasi** [comment]
It's working with my testing on the latest release `1.4.1` - you could check the source file to see if there is `webView: true` from the detail screen

<img width="1431" alt="Screen Shot 2020-05-24 at 19 09 52" src="https://user-images.githubusercontent.com/1459805/82753733-26fd4380-9df2-11ea-9324-9633f463c662.png">

**Comment by bidfor** [comment]
Thanks, it works now. I'm using quarter_image and the webView is not there. You might want to fix it in the next update.
