### ISSUE TITLE
Unoptimised APK

### ISSUE THREAD

**Issue by hengsoheak** [inspireui/support#3355]
Step 1 (require): detail issues and screenshots

Unoptimised APK
Warning:

This APK results in unused code and resources being sent to users. Your app could be smaller if you used the Android App Bundle. By not optimising your app for device configurations, your app is larger to download and install on users' devices than it needs to be. Larger apps see lower installation success rates and take up storage on users' devices.

Resolution:

Use the Android App Bundle to automatically optimise for device configurations, or manage it yourself with multiple APKs.

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as it could not be verified, please create the new one when you got enough purchased info - thank you!

**Comment by hengsoheak** [comment]
Sorry friends mostly I try myself again and again more than 10 time if still can not I will ask here.
and now the app is working well but I can not optimize it.

![errrror](https://user-images.githubusercontent.com/812528/83100218-8486de00-a0d9-11ea-835b-9ee1da30246d.PNG)

![as](https://user-images.githubusercontent.com/812528/83100286-c0ba3e80-a0d9-11ea-9ecd-4c71eda696b3.PNG)
