### ISSUE TITLE
get Shipping Methods api taking to much time 

### ISSUE THREAD

**Issue by CodeIncognite** [inspireui/support#3356]
Step 1 (require): when i call shipping method api it will take about 30 sec to retrieve the response or result

 try {
      List<ShippingMethod> list = [];
      var response = await wcApi.getAsync("shipping/zones");
      var reversedList = new List.from(response.reversed);
      if (response is Map && isNotBlank(response["message"])) {
        throw Exception(response["message"]);
      } else {
        for (var zone in reversedList) {
          final id = zone["id"];
          var response = await wcApi.getAsync("shipping/zones/$id/methods");
          printLog("SHIPPING METHOD ${response.toString()}");
          if (response is Map && isNotBlank(response["message"])) {
            throw Exception(response["message"]);
          } else {
            var res = await wcApi.getAsync("shipping/zones/$id/locations");
            if (res is Map && isNotBlank(res["message"])) {
              throw Exception(res["message"]);
            } else {
              List locations = res;
              bool isValid = false;
              bool checkedPostcode = false;
              locations.forEach((o) {
                if (o["code"].toString().toLowerCase().trim() == '${address.country + ':' + address.city}'.toLowerCase().trim()) {
                  isValid = true;
                }
                if (o["type"] == "country" && isValid) {
                  isValid =
                      address.country == o["code"] && address.city == o["city"];
                }
                if (o["type"] == "postcode" &&
                    ((!checkedPostcode && isValid) ||
                        (checkedPostcode && !isValid))) {
//                  isValid = address.zipCode == o["code"];
                  isValid = true;
                  checkedPostcode = true;
                }
              });

              if (isValid) {
                for (var item in response) {
                  list.add(ShippingMethod.fromJson(item));
                }
              }
/*
* if no shipping method for selected region 
* */
              if (locations.length == 0 && list.length == 0) {
                for (var item in response) {
                  list.add(ShippingMethod.fromJson(item));
                }
              }
            }
          }
        }
      }
      return list;
    } catch (e) {
      //This error exception is about your Rest API is not config correctly so that not return the correct JSON format, please double check the document from this link https://docs.inspireui.com/fluxstore/woocommerce-setup/
      throw e;
    }

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as it could not be verified, please create the new one when you got enough purchased info - thank you!
