### ISSUE TITLE
[ListApp] Documentation for ListApp 1.6 to configure it with MyListing

### ISSUE THREAD

**Issue by damianlluch** [inspireui/support#336]
**Mandatory Info (please complete the following information):**
 - Product: [ListApp]
 - Your Purchased Code: [get from https://codecanyon.net/downloads]
b21e47a3-42d6-406d-9064-87a4ba0805f3
(we may not reply if you are not our customer)

**Describe the issues**
hello, a client has bought ListApp 1.6 to use it in the MyListing theme and I can not find the updated documentation to generate the application correctly. Please, I need support. Thank you!

**Screenshots**

I have installed and configured the add-ons and permissions in wordpress.
Then I installed CeBuilder and with Apikeys I created the application, but both the current documentation and the videos have different versions and file structure. I need a tutorial and updated documentation.

**Additional context**
Add any other detail logs about the problem here.

**Comment by thangvo9x** [comment]
hi. you can  refer here https://inspireui.github.io/listapp/docs/quickstart

**Comment by damianlluch** [comment]
hi, this documentation does not correspond to version 1.6. I have already reviewed it, precisely, the file structure of this documentation is not in version 1.6.

**Comment by thangvo9x** [comment]
Hi. Can you tell me what your issue

**Comment by damianlluch** [comment]
What files should I edit to configure the application with the MyListing theme?

**Comment by damianlluch** [comment]
I have edited only the file, AppConfig.json with the WooCommerce data, and when I run the application I have this error:

Require cycle: App/Components/index.js -> App/Components/Detail/ListingData/index.js -> App/Components/index.js


Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
- node_modules/expo/build/environment/logging.js:25:23 in warn
- node_modules/metro/src/lib/polyfills/require.js:109:19 in metroRequire
* App/Components/Detail/ListingData/index.js:6:0 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:292:12 in loadModuleImplementation
* App/Components/index.js:241:0 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:292:12 in loadModuleImplementation
* App/RootRouter.js:5:0 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:292:12 in loadModuleImplementation
* App.js:27:0 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:292:12 in loadModuleImplementation
- node_modules/expo/AppEntry.js:2:0 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:292:12 in loadModuleImplementation
- node_modules/metro/src/lib/polyfills/require.js:179:45 in guardedLoadModule
* null:null in global code

**Comment by thangvo9x** [comment]
Require cycles. This is a warning from the expo lib. not important. you can refer
update latest Expo 31 which could cause VERY SLOW at development mode (as you will get the "require cycle: " warning, please remove the IF block from node_modules/metro/src/lib/polyfills/require.js (https://gyazo.com/df9e8c80e88d51fed30807b0a369e7e1) - Or, select the build with PRODUCTION 

1. You must change your domain in AppConfig.json
2. Change to categoryId on your site. in MyListing.js in Config folder. property name is "horizontalLayout"

**Comment by damianlluch** [comment]
How do I change the category in MyListing.js?
an example please

**Comment by thangvo9x** [comment]
Hi. You can refer here https://inspireui.github.io/listapp/docs/quickstart
Or you can use CeBuilder to config them.
Thanks

**Comment by damianlluch** [comment]
I already told you that the structure of the directories and files used in the documentation and the videos does not match the source code.
I have already done the steps with CeBuilder. When talking about editing the theme, do you mean the "Support Template" selection Menu?. There are 2 options: MyListing (default) and MyListing (MyHome), which ones should be chosen?
I have tried both options. It keeps showing me the example application.

My website is: www.famitip.com

![screenshot 2019-03-01 at 10 27 30](https://user-images.githubusercontent.com/1463804/53629663-64cee480-3c0e-11e9-87d5-d265942bf0dc.png)

**Comment by damianlluch** [comment]
MyApp.json

[Uploading AppConfig.json.zip…]()

**Comment by damianlluch** [comment]
My AppConfig.json

[AppConfig.json.zip](https://github.com/inspireui/support/files/2918865/AppConfig.json.zip)

**Comment by thangvo9x** [comment]
Hi. Your template is running on your website. MyListing if your them is mylisting and myHome if your them is myHome.
Thanks
