### ISSUE TITLE
Website linking issue with App

### ISSUE THREAD

**Issue by vkasks** [inspireui/support#3360]
Step 1 (require): detail issues and screenshots
Hi Team, I am unable to Login/Register from app from, also images are also not being fetched by app.
![Screenshot_2020-05-22-11-57-37-446_com greeno greensynglobal](https://user-images.githubusercontent.com/28772045/82668868-fc778300-9c57-11ea-8d76-0e31bc48aeb1.jpg)
![Screenshot_2020-05-22-11-58-14-263_com greeno greensynglobal](https://user-images.githubusercontent.com/28772045/82668876-fda8b000-9c57-11ea-84bf-7027750f6888.jpg)
![Screenshot_2020-05-22-12-15-28-405_com greeno greensynglobal](https://user-images.githubusercontent.com/28772045/82668878-fe414680-9c57-11ea-8560-8a8c104ed4ac.jpg)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@vkasks - please help to double-check your website is not working "greensynglobal" - thank you!

**Comment by kvt0012** [comment]
Please check your api and m-store api, I think problem is on api, thank you

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Comment by vkasks** [comment]
Issue is resolved thank, I uploaded config file in mStore API. and it
working great.

Thanks.
:-)

One more query I want to use this source code, for my another client, do
you have any plan /package for multiple use?

Please let me know the best possible & cost effective way.

regards

Vikas Sharma
