### ISSUE TITLE
fluxstore in woocomerce : error in Failed assertion boolean expression must not null

### ISSUE THREAD

**Issue by hssinaman** [inspireui/support#3361]
Step 1 (require): detail issues and screenshots

![WhatsApp Image 2020-05-22 at 2 17 22 AM](https://user-images.githubusercontent.com/61097607/82670493-c53fac80-9c2c-11ea-88b5-356fbd762279.jpeg)

**Comment by hssinaman** [comment]
can you help please ?

**Comment by harjono-flux** [comment]
plis check this
https://github.com/inspireui/support/issues/3350

**Comment by minhcasi** [comment]
@hssinaman - pls try with the latest release `1.7.4` to fix this issue - thank you!

**Comment by minhcasi** [comment]
@hssinaman - pls move the conversation to the same ticket #3350
