### ISSUE TITLE
Fluxstore Multivendor build failed

### ISSUE THREAD

**Issue by gelocaindoy** [inspireui/support#3362]
Step 1 (require): detail issues and screenshots

![image](https://user-images.githubusercontent.com/65111463/82676217-96e7be80-9c78-11ea-88fd-80df060ea2aa.png)

> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:processDebugGoogleServices'.
> > No matching client found for package name 'com.kaysuki.android.vendor'
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 3m 56s

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by gelocaindoy** [comment]
this is for https://github.com/inspireui/support/issues/3240

**Comment by gelocaindoy** [comment]
@minhcasi @vumanhsn97

**Comment by minhcasi** [comment]
@gelocaindoy - could you try to zip the android folder and share here, we will help to fix your config - thanks

**Comment by gelocaindoy** [comment]
> @gelocaindoy - could you try to zip the android folder and share here, we will help to fix your config - thanks

Hi. @minhcasi 

Please see below link

https://1drv.ms/u/s!AgXNyS9ufRT2gfd1pEs8kwh0lxVxrg?e=qB6tcd

Thanks!

**Comment by gelocaindoy** [comment]
hi @minhcasi 

any update please.

Thanks!

**Comment by vumanhsn97** [comment]
@gelocaindoy 
You need to match applicationId in your android folder and bundle id in your firebase. In your firebase, your bundle is com.kaysuki.android. In your android folder, your bundle is com.kaysuki.android.vendor. I match its with same bundle: com.kaysuki.android(firebase) and it working well.
[android.zip](https://github.com/inspireui/support/files/4675062/android.zip)

**Comment by gelocaindoy** [comment]
Hi @vumanhsn97 

Thanks build success but i have an error in homepage.
![image](https://user-images.githubusercontent.com/65111463/82792479-10162a00-9ea2-11ea-91d5-e802f55e8dbf.png)

and i can't view the vendors.
![image](https://user-images.githubusercontent.com/65111463/82792558-291edb00-9ea2-11ea-9227-5cc39ecf239f.png)

and upon checking in language i have an error this one.
![image](https://user-images.githubusercontent.com/65111463/82792906-aa766d80-9ea2-11ea-8fdc-6aed6d5a9277.png)

**Comment by vumanhsn97** [comment]
Stores: follow this: https://github.com/inspireui/support/issues/3385#issuecomment-633390469
Home page: In your config.json add this line: 
![image](https://user-images.githubusercontent.com/39208623/82802669-76527b00-9ea9-11ea-91b5-bed43ad79d5f.png)

**Comment by gelocaindoy** [comment]
@vumanhsn97 thanks!

how about the language?

**Comment by gelocaindoy** [comment]
Hi @vumanhsn97 

not yet solve for stores
here is my config 

![image](https://user-images.githubusercontent.com/65111463/82852589-ec042880-9f35-11ea-8b31-9dbf0551e286.png)

my mstore api were updated
![image](https://user-images.githubusercontent.com/65111463/82853011-07236800-9f37-11ea-92ff-264a332cf1a7.png)

**Comment by vumanhsn97** [comment]
@gelocaindoy 
update code in lib/vendor/store/store_model.dart
banner = parsedJson["settings"]["banner"].toString().isNotEmpty
              ? parsedJson["settings"]["banner"]
              : image;
![image](https://user-images.githubusercontent.com/39208623/82856419-1c4cc680-9f38-11ea-9091-8da9d90d10c2.png)

**Comment by gelocaindoy** [comment]
hi @vumanhsn97 

done paste
![image](https://user-images.githubusercontent.com/65111463/82859821-5b841300-9f4a-11ea-9dbc-28534bd74a7b.png)

Please see below error upon build

`Exception: Gradle task assembleDebug failed with exit code 1

C:\src\source>flutter run
Launching lib\main.dart on SM G965F in debug mode...

Compiler message:
Running Gradle task 'assembleDebug'...
lib/vendor/store/store_model.dart:100:33: Error: Expected an identifier, but got '!='.
Running Gradle task 'assembleDebug'...
    if (parsedJson["settings"]) != null ) {
Running Gradle task 'assembleDebug'...
                                ^^
Running Gradle task 'assembleDebug'...
lib/vendor/store/store_model.dart:100:36: Error: Expected ';' after this.
Running Gradle task 'assembleDebug'...
    if (parsedJson["settings"]) != null ) {
Running Gradle task 'assembleDebug'...
                                   ^^^^
Running Gradle task 'assembleDebug'...
lib/vendor/store/store_model.dart:100:41: Error: Expected an identifier, but got ')'.
Running Gradle task 'assembleDebug'...
    if (parsedJson["settings"]) != null ) {
Running Gradle task 'assembleDebug'...
                                        ^
Running Gradle task 'assembleDebug'...
lib/vendor/store/store_model.dart:100:41: Error: Expected ';' after this.
Running Gradle task 'assembleDebug'...
    if (parsedJson["settings"]) != null ) {
Running Gradle task 'assembleDebug'...
                                        ^
Running Gradle task 'assembleDebug'...
lib/vendor/store/store_model.dart:100:41: Error: Unexpected token ';'.
Running Gradle task 'assembleDebug'...
    if (parsedJson["settings"]) != null ) {
Running Gradle task 'assembleDebug'...
                                        ^
Running Gradle task 'assembleDebug'...

Running Gradle task 'assembleDebug'...
Compiler message:
Running Gradle task 'assembleDebug'...
lib/vendor/store/store_model.dart:100:33: Error: Expected an identifier, but got '!='.
Running Gradle task 'assembleDebug'...
    if (parsedJson["settings"]) != null ) {
Running Gradle task 'assembleDebug'...
                                ^^
Running Gradle task 'assembleDebug'...
lib/vendor/store/store_model.dart:100:36: Error: Expected ';' after this.
Running Gradle task 'assembleDebug'...
    if (parsedJson["settings"]) != null ) {
Running Gradle task 'assembleDebug'...
                                   ^^^^
Running Gradle task 'assembleDebug'...
lib/vendor/store/store_model.dart:100:41: Error: Expected an identifier, but got ')'.
Running Gradle task 'assembleDebug'...
    if (parsedJson["settings"]) != null ) {
Running Gradle task 'assembleDebug'...
                                        ^
Running Gradle task 'assembleDebug'...
lib/vendor/store/store_model.dart:100:41: Error: Expected ';' after this.
Running Gradle task 'assembleDebug'...
    if (parsedJson["settings"]) != null ) {
Running Gradle task 'assembleDebug'...
                                        ^
Running Gradle task 'assembleDebug'...
lib/vendor/store/store_model.dart:100:41: Error: Unexpected token ';'.
Running Gradle task 'assembleDebug'...
    if (parsedJson["settings"]) != null ) {
Running Gradle task 'assembleDebug'...
                                        ^
Running Gradle task 'assembleDebug'...
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
Running Gradle task 'assembleDebug'...
build failed.
Running Gradle task 'assembleDebug'...

Running Gradle task 'assembleDebug'...
FAILURE: Build failed with an exception.
Running Gradle task 'assembleDebug'...

Running Gradle task 'assembleDebug'...
* Where:
Running Gradle task 'assem* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 29s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                       223.5s (!)
Exception: Gradle task assembleDebug failed with exit code 1
`

**Comment by vumanhsn97** [comment]
Please compare code 
![image](https://user-images.githubusercontent.com/39208623/82981462-52f90e80-a016-11ea-8673-9d3d47a1aae0.png)

**Comment by gelocaindoy** [comment]
hi @vumanhsn97 

done. thanks but
upon rebuild it's not showing.
![image](https://user-images.githubusercontent.com/65111463/83086856-74afcf80-a0c2-11ea-96cd-9f38a2eac9fa.png)

**Comment by vumanhsn97** [comment]
@gelocaindoy 
Can you zip lib folder and send to vumanhsn97@gmail.com?

**Comment by gelocaindoy** [comment]
@vumanhsn97 

already sent subject [inspireui/support] Fluxstore Multivendor build failed (#3362)

**Comment by minhcasi** [comment]
@gelocaindoy - please help to try to update latest `1.7.4` and the mstore-api WP plugin

**Comment by gelocaindoy** [comment]
@minhcasi how to update into latest 1.7.4 sir ?

**Comment by minhcasi** [comment]
@gelocaindoy - pls use this video guide - https://www.youtube.com/watch?v=SWLHKx-xzn0

Make sure both fluxstore `1.7.4` and mstore-api is up-to-date, let us know if you have any further question :)
