### ISSUE TITLE
Fluxstore Multivendor facebook login

### ISSUE THREAD

**Issue by romaque** [inspireui/support#3363]
Hi,
Accounts created on facebook using the cell phone number without email cannot log into the app.

error message:
Your 'access_token' did not return the user's email. Without 'email', the user cannot be logged in or registered. Get extended user email permission when joining the Facebook app.

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as it could not be verified, please create the new one when you got enough purchased info - thank you!

**Comment by romaque** [comment]
I sent the form

**Comment by minhcasi** [comment]
@

**Comment by minhcasi** [comment]
@romaque - we got your verify ticket - pls have a look to this detail to config for your Facebook login - https://medium.com/@inspireui/setup-facebook-login-for-flutter-apps-4e7bd031479d 

Let us know your checking
