### ISSUE TITLE
Social login works, but not by a correct way for 1.7.3!

### ISSUE THREAD

**Issue by xsamir** [inspireui/support#3364]
Step 1 (require): detail issues and screenshots
I'm using 1.7.3 version of Multiple vendor app, I enabled the social login
But I'm facing a problem on Android version as below:

- When the user login using Facebook or Google, it will process everything fine but it **keeps running without stop** as shown in this video with Facebook login: https://drive.google.com/file/d/1rKDbc55OHVLoS0WhM0PCOWhW4IoFR8_w/view?usp=sharing

And the user information will be shown on Firebase as well:
![image](https://user-images.githubusercontent.com/7432001/82702782-bcc69080-9c83-11ea-943d-178a6f4727c6.png)

- The second problem, when **I click back, it will show only logout button** on the user area Also there's no product add option, but on Wordpress dashboard, it shows that the user is a vendor :
![image](https://user-images.githubusercontent.com/7432001/82702929-fc8d7800-9c83-11ea-9080-ba5c18d46ab5.png)

![image](https://user-images.githubusercontent.com/7432001/82702980-1a5add00-9c84-11ea-9de2-ebf1733074fe.png)

- Third issue:
The app doesn't **keep me log in**, I need to login every time I use the app. 

_Please assist urgently because my app already released on Play & Apple stores._

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)
Done

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by trunghieuvn** [comment]
I cannot access your link drive, please grant me permission to check it out.

![image](https://user-images.githubusercontent.com/19247680/82773815-31105800-9e6d-11ea-8db5-f8cade1d94d1.png)

For login related issues, please add me to your github / gitlab and firebase console repo so that I can check it out as quickly as possible. Thanks very much.

My email/github/gitlab/firebase account is: ` hieu.trantrung1204@gmail.com`

**Comment by xsamir** [comment]
Hi,

You have now an access to my Firebase project & Gitlab.

Regards.

**Comment by trunghieuvn** [comment]
i receive console firebase, but not have see gitlab.

please add my skype: trunghieu-it@hotmail.com

thanks

**Comment by xsamir** [comment]
Thank you @trunghieuvn for your fast response.
I text you before a while through Skype

**Comment by xsamir** [comment]
FYI, the app already live on Apple & Play stores.

**Comment by xsamir** [comment]
Any UPDATE! please

**Comment by minhcasi** [comment]
@trunghieuvn

**Comment by xsamir** [comment]
I'm sure that the problem started shows up when I moved from Bluehost to Google cloud WP.

Do you have certain settings for google cloud? or should I return back to Bluehost?

**Comment by trunghieuvn** [comment]
Hi @xsamir ,
I have checked your code. You have added the cloud_firestore library and used it in login.
I found that the `saveUserToFirestore` function in` lib/models/user/user_model.dart` has called

```
Firestore.instance
           .collection ('users')
           .document (user.email)
           .setData ({'deviceToken': token, "isOnline": true}, merge: true);
```

![image](https://user-images.githubusercontent.com/19247680/83226683-ba48c700-a1ac-11ea-88a0-aea9f22c218b.png)

and it failed.

I tried deleting your code and the result was a successful login.
Please check the configuration steps of the cloud_firestore library.
We do not currently support this library.

Note: if you want feature put data users after login success to firebase database please create new ticket suggestion feature

**Comment by xsamir** [comment]
Thank you a lot for your assistance, that works to pass the login process

But there's another problem, it's that the user after getting login, he cannot add products! (MyProducts option not shows).

While he is a vendor user as it shows on Wordpress dashboard?

But if the user signup using an email, everything shows fine.

Regards,

**Comment by minhcasi** [comment]
@xsamir - would you mind to check the latest `1.7.4` - thank you!

**Comment by xsamir** [comment]
> 
> 
> @xsamir - would you mind to check the latest `1.7.4` - thank you!

Thanks, I will work on the new version today.

**Comment by trunghieuvn** [comment]
Nice to help you \<3 . Please help me close the ticket and if you feel satisfied please give me 5 stars [https://codecanyon.net/downloads](https://codecanyon.net/downloads) .

Thank you very much.
