### ISSUE TITLE
MSTORE PRO CUSTOMIZATION

### ISSUE THREAD

**Issue by malibate** [inspireui/support#3365]
Step 1 (require): detail issues and screenshots
1. I want to include and use my local currency (Tanzanian Shillings) in the app or how the app can sync currencies from the website?
2. How to change links for Privacy policies and Terms & condtions as well as to include contact us details?
3. On the login how to remove the SMS login? is there a possibility to include google login?
4. Where do I change the welcoming three pages? The welcome, Secure payment and High Perfomance?
5. There is a problem with Price value and discounted price value, the cancelled value comes the same as the actual value
![Screenshot_20200522-225652](https://user-images.githubusercontent.com/45195047/82711159-3b73fb80-9c8d-11ea-8fcc-16d635d5aa8f.jpg)
![InkedScreenshot_20200523-002947_LI](https://user-images.githubusercontent.com/45195047/82711164-3dd65580-9c8d-11ea-825f-09b78b47e282.jpg)
![Screenshot_20200522-225626](https://user-images.githubusercontent.com/45195047/82711167-3fa01900-9c8d-11ea-9cfb-7ec1f46339e9.jpg)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

DONE!

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by minhcasi** [comment]
We wanted to thank you for your patience during this busy time. We currently have reduced staff and a significantly higher volume of inquiries. We’re working as hard as we can to get to your request as soon as possible.

We sincerely apologize for the delay and hope you’re staying safe.

**Comment by malibate** [comment]
![Screenshot_20200525-232246_LI](https://user-images.githubusercontent.com/45195047/82842080-fd6f1580-9ee0-11ea-8dd6-efcd29ac58a9.jpg)

1. There is another challenge for prices to Overlap as seen above, can the design change for the discounted price to be below the actual price
2. Note the pricing seem to be well on that list as seen on the screenshot above, but once you open the product, the price becomes the same as the discounted price; see attachment below


![Screenshot_20200525-232300_LI](https://user-images.githubusercontent.com/45195047/82842203-52129080-9ee1-11ea-89c0-8b997b5dc6af.jpg)

**Comment by luyx2412** [comment]
Hi @malibate 
1. In `src/containers/Category/styles.js` line 59, You can comment same the screenshot to fix the overlap price
2. Please change your sale price in your wordpress dashboard.

Thanks

**Comment by malibate** [comment]
2. The prices are different, to assure you that, you cannot add same price in Sale and normal price, it is restricted.

**Comment by luyx2412** [comment]
HI @malibate You can compare sale and regular price. If 2 prices is equal, you can hide it.

Thanks
