### ISSUE TITLE
fluxstore

### ISSUE THREAD

**Issue by Himnashu** [inspireui/support#3366]
Hi, @minhcasi  I'm not able to load all products for any categories when users come from category Icon. It's only loading 10 products on load more it's calling API data is coming but not showing in the UI. I tried  by changing ApiPageSize but it's not working. 
Can you please tell me how can I use the same load more functionality when users come from categories icons.

_Originally posted by @Himnashu in https://github.com/inspireui/support/issues/2879#issuecomment-632917517_

**Comment by minhcasi** [comment]
We wanted to thank you for your patience during this busy time. We currently have reduced staff and a significantly higher volume of inquiries. We’re working as hard as we can to get to your request as soon as possible.

We sincerely apologize for the delay and hope you’re staying safe.

@kvt0012 - pls keep the update

**Comment by kvt0012** [comment]
You can check on lib/services/ woocomerce_api. We've already set limitation on thi file, thank you

**Comment by kvt0012** [comment]
I close this because it's been a long time no response. Thank you
