### ISSUE TITLE
(Magento 2.3; FluxStore Pro) Configurable Product Not Working

### ISSUE THREAD

**Issue by saudadev** [inspireui/support#3369]
# ACTIVE ISSUES

***

**ISSUE 14 : Not Fixed 👎**

**Summary : In Product Search and Category View How to Sort Products By Price (High/Low) By Review**

**IMAGES**

![searchproductsort](https://user-images.githubusercontent.com/63896811/86997736-6af2af00-c1cc-11ea-975c-0e7e5bdcaee0.JPG)

![categorysort](https://user-images.githubusercontent.com/63896811/86997757-7645da80-c1cc-11ea-919f-c431f34cec99.JPG)

**ISSUE 15 : Not Fixed 👎**

**SUMMARY : Product Display in Category Page Doesn't Lazy Load, Customers will loose interest on seeing Inactive Screen. Video been Shared with @minhcasi **

**ISSUE 16 : Not Fixed 👎**

**SUMMARY : Recent View Items Shows Same Product Multiple Times**

![repeated_recentview](https://user-images.githubusercontent.com/63896811/86999813-333a3600-c1d1-11ea-8377-f91610046e30.JPG)

***
# COMPLETED ISSUES

***

***

**ISSUE : 5 (FIVE) : Temp Fixed 👍👎**

**ISSUE 5 - A:**

Fix: Added the Product to Route Category Also.

Summary : In any Category if you go to See All, it doesnt display any products.

![app-see-all](https://user-images.githubusercontent.com/63896811/82875553-292be300-9f55-11ea-8fc4-ed48fe3dfd2e.png)

***
**ISSUE : 6 (SIX) : Fixed 👍**

**ISSUE 6 - A:**
Fix: Fixed in new Release
**Temp Resolution : The App Should be getting the Region ID as per the address from Magento, for now I have hard coded the my region ID as a work around**

Summary: During If I select any product and Checkout I get Region ID 43 Invalid Error

![app-checkout-regionid43](https://user-images.githubusercontent.com/63896811/82876196-09e18580-9f56-11ea-8458-75762ce833f7.png)

In the Code It throws error in magento.dart

![code-error-region-id](https://user-images.githubusercontent.com/63896811/82877551-f7684b80-9f57-11ea-88d6-f6a5e1ee3667.PNG)

I see in the address.dart you have hard coded the Value of 43

![code-address-dart-hardcoded-region-id](https://user-images.githubusercontent.com/63896811/82877461-d69ff600-9f57-11ea-8bd9-e0f6412f61e2.PNG)

***
**ISSUE : 7 (SEVEN) :  Fixed 👍**

**ISSUE 7 - A:**

**Summary:** After sometime of Inactivity the App's Token gets expired and it doesn't allow you to check out and for a brief time it shows you the Exception Message  and goes away, its confusing for customers it should redirect you to login screen.

![app-login-pop-up](https://user-images.githubusercontent.com/63896811/82930512-235cee80-9fa3-11ea-962e-d46aa6faf407.png)

**ISSUE 2 - A: 👍 Fixed **
**ISSUE 2-A: I am trying to search the keyword “rice” in Search Tab.

**More Observations: The Search should only get the Product Names and suggest you on Auto Complete, but here the Search start fetching all product details which make is resource Heavy**

The Product is a Configurable Product and the Configured Products are Marked not to be displayed Individually.

Backend of Magento Product**

![Search-Magento-BackEnd](https://user-images.githubusercontent.com/63896811/82725114-65163c80-9cf8-11ea-9391-7c939ac1a115.png)

As you can see, these products are marked not to be searched Individually.

**IN APP : As you can see, it display all the products and Displays the Primary Configurable Product Value to ZERO.**

![Seacrh-App-Showing-4-Products](https://user-images.githubusercontent.com/63896811/82725120-72332b80-9cf8-11ea-9c70-79abfb80ca61.png)

***

**ISSUE : 1 (ONE -- Fixed) 👍 **
Step 1 (require): detail issues and screenshots

I have a configurable Product Called as RICE which has an Attribute of “WeightKG” and values are 1KG, 5KG and 10 KG. These are Text Swatch.

I have added the Attribute to general.dart

/// Below config is used for Magento store
  "DefaultStoreViewCode": "",
  "EnableAttributesConfigurableProduct": ["color", "size","WeightKG"],
  "EnableAttributesLabelConfigurableProduct": ["color", "size","WeightKG"]

Made below changes to Products.dart

const ProductVariantLayout = {
  "color": "color",
  "size": "box", 
  "WeightKG" : "box", 
  "height": "option",
};

**Above Issue is Fixed**
------------------------------------------------------------------------------------------------------------------------------
**ISSUE 1 - A:--Fixed 👍 **
**Resolution : For Configurable Products I have fetched all Variant Prices and assigned  Minimum Price from All Variant to the Primary Product. So in the Product Display List it shows the Lowest Price** 

Issue 1-A : In App when we go to Categories the Product Default Value Comes as 0, which should be the Lowest Price of a Configurable Product.

![Category-ConfigurableProduct-Zeron-Value](https://user-images.githubusercontent.com/63896811/82721571-db587600-9cdb-11ea-8fdd-e44ffacecb68.png)

**ISSUE 1 - B: Fixed -- 👍 **

**Resolution : For Configurable Products I Modified the Add to Cart Button to take it to Product Detail Page and from there we select the Variant and we add to the Cart. But for Simple Product Add to Cart Icon will add to Cart.** 

**More Details: I have added a Product for Attribute Color and for that Product I my Pictures Changes as Per Variant but for my Custom Attribute "weightkg" the Price changes but not the images. **

**Image is also getting changed**

ISSUE 1 - B: Price and Images Doesn’t Change as I change the text Swatch.

BEFORE
![Category-ConfigurableProduct-Text-Swatch-Before](https://user-images.githubusercontent.com/63896811/82721574-e9a69200-9cdb-11ea-9cb7-1f157d05b845.png)

AFTER : - I CLICKED THE TEXT SWATCH 5 KG

![Category-ConfigurableProduct-Text-Swatch-After](https://user-images.githubusercontent.com/63896811/82721579-f5925400-9cdb-11ea-8b4c-d8d0d75b7b1b.png)

ADDITIONAL ISSUES :

**ISSUE : 2 (TWO) : Fixed 👍**
Adding the Product to Cart of Other Swatches ( like 5 KG and 10 KG) makes SKU value “NULL”.

**ADDING MORE ISSUES IN A SINGLE TICKET AS PER THE ADMIN**
**#########################################################################**
Step 1 (require): detail issues and screenshots

**ISSUE 2 - B: Fixed 👍 **

ISSUE 2-B: If you Scroll Down it keep on adding 4 more Same Products and wont Stop adding as you scroll down.

![Seacrh-App-Showing-8-Products](https://user-images.githubusercontent.com/63896811/82722268-b5829f80-9ce2-11ea-92bc-97c925d10b01.png)

WORKING MAGENTO FRONT-END

![Search-Magento-frontend](https://user-images.githubusercontent.com/63896811/82722272-bd424400-9ce2-11ea-8c1a-4e3c5bf0b7da.png)

**#########################################################################**
**ISSUE : 3 (THREE) - Fixed 👍**

**Resolution: Pulled both Regular Price and Discounted Price from Attribute and shows the Discounts in Product Listing and also Product Details Page for both Configurable and Simple Product **
**ISSUE 3 - A:**
ISSUE 3-A : - In APP Product Discounts are Not Shown (Magento Special Price are Not Shown)

Please find the below ScreenShot

![Discount-App-Not-Shown](https://user-images.githubusercontent.com/63896811/82722492-e82d9780-9ce4-11ea-96d8-e6228478c5c0.png)

WORKING MAGENTO FRONTEND

![Discount-Web-Working](https://user-images.githubusercontent.com/63896811/82722497-ec59b500-9ce4-11ea-8cea-b31791e94076.png)

HOW TO QUESTION (NOT AN ISSUE)

If I have an attribute as BRAND, How I can display that in the APP?

**#########################################################################**
**ISSUE : 4 (FOUR) **

**ISSUE 4 - A: : Fixed (Temporary Work Around) 👍👎**

**Resolution (Temp Fix): I pulled Categories Under More and added to Primary List so it shows me all the Categories and its Sub Categories but doesn't display More. In there Code Base they Pull only two level down** 

Summary:  I have Sub Categories Like This under "More" >> "Other Categories" >> "Sub Other Categories"

![mobile-categorylisting](https://user-images.githubusercontent.com/63896811/82874623-d7cf2400-9f53-11ea-902d-a9cf66c53e65.PNG)

In App I cant see these sub Categories

![mobile-categorylisting-app](https://user-images.githubusercontent.com/63896811/82875100-9428ea00-9f54-11ea-93f7-e580ecaa2596.PNG)

Please advise.

**#########################################################################**

 
**#########################################################################**

**ISSUE : 8 (EIGHT) : Fixed 👍**

**ISSUE 8 - A:**

**Summary :**  Cannot See Order History.

![app-order-history](https://user-images.githubusercontent.com/63896811/82930624-4f786f80-9fa3-11ea-8a40-b62779f31a31.PNG)

**#########################################################################**

**ISSUE : 9 (NINE) : Fixed 👍**

**ISSUE 9 - A:**

**Summary :**  Cannot Reset Password, Throws Exception. You have hard coded Word Press Rest Link but our Setup is Magento.

Below is the App Error

![app-issue-password-rest](https://user-images.githubusercontent.com/63896811/83286297-48e53480-a1fd-11ea-8e54-1405c0f93d8c.png)

Code Behind Exception 

![code-password-rest-exception](https://user-images.githubusercontent.com/63896811/83286345-5dc1c800-a1fd-11ea-9b6a-26e6257549ec.PNG)

**#########################################################################**

**ISSUE : 10 (TEN) :Fixed 👍 **

**Summary : For Our App its a Mandatory Feature that the items Quantity a customer can Order should be limited and the data should be dynamic from Magento **

In the App Its been Hard Coded to 100 and Product or ProductVariation Stock Quantity is not populated. 

![app-max-quantity](https://user-images.githubusercontent.com/63896811/83731765-aef01280-a668-11ea-89fd-c7d3ad5e0fe6.PNG)

 **#########################################################################**

**ISSUE : 11  : Fixed 👍**

**Summary : In the App in any product Customer can add Max 6 Items, can you please change the cart Quantity to (+) or ( -) icons   **

![app-max-item-toadd](https://user-images.githubusercontent.com/63896811/83734509-ba453d00-a66c-11ea-8bce-83200107490a.PNG)

**#########################################################################**

**ISSUE : 12  : Fixed 👍**
**Summary : In the Cart Summary you can change the stock to any quantity you want if you have limit of 10 you can still order 100  **

** Fixed and committed**

**#########################################################################**

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

ADDED

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by saudadev** [comment]
> Thank you for the feedback.
> 
> Please help us to submit this form and fill all required info to continue with the support - [http://private.inspireui.com/ -](http://private.inspireui.com/%C2%A0-) please don't share the purchase code or screenshot public here as another user will use it for activation.
> 
> We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

I have Already added the Private Files.

**Comment by minhcasi** [comment]
@saudadev - thank you for replying quickly, please help to list your all question just one ticket - i have assigned to the technical team for investigating and get back you on Monday (after back to work) - thank you for your time

**Comment by minhtruong315** [comment]
Hi @saudadev 
You can replace fromMagentoJson function on models/product/product_variantion.dart like this to fix ISSUE 2
```
ProductVariation.fromMagentoJson(Map<String, dynamic> parsedJson) {
    id = parsedJson["id"].toString();
    sku = parsedJson["sku"];
    price = parsedJson["price"].toString();
    regularPrice = parsedJson["price"].toString();
    salePrice = parsedJson["price"].toString();
    onSale = false;
    inStock = parsedJson["status"] == 1;

    final imageUrl = MagentoHelper.getCustomAttribute(
        parsedJson["custom_attributes"], "image");
    imageFeature =
        MagentoHelper.getProductImageUrlByName(Config().url, imageUrl);

    List<Attribute> attributeList = [];
    List attributesConfig =
        kAdvanceConfig["EnableAttributesConfigurableProduct"];
    attributesConfig.forEach((element) {
      final item = MagentoHelper.getCustomAttribute(
          parsedJson["custom_attributes"], element);
      if (item != null) {
        attributeList.add(Attribute.fromMagentoJson(
            {"value": item, "attribute_code": element}));
      }
    });
    attributes = attributeList;
  }
```

**Comment by saudadev** [comment]
> Hi @saudadev
> You can replace fromMagentoJson function on models/product/product_variantion.dart like this to fix ISSUE 2
> 
> ```
> ProductVariation.fromMagentoJson(Map<String, dynamic> parsedJson) {
>     id = parsedJson["id"].toString();
>     sku = parsedJson["sku"];
>     price = parsedJson["price"].toString();
>     regularPrice = parsedJson["price"].toString();
>     salePrice = parsedJson["price"].toString();
>     onSale = false;
>     inStock = parsedJson["status"] == 1;
> 
>     final imageUrl = MagentoHelper.getCustomAttribute(
>         parsedJson["custom_attributes"], "image");
>     imageFeature =
>         MagentoHelper.getProductImageUrlByName(Config().url, imageUrl);
> 
>     List<Attribute> attributeList = [];
>     List attributesConfig =
>         kAdvanceConfig["EnableAttributesConfigurableProduct"];
>     attributesConfig.forEach((element) {
>       final item = MagentoHelper.getCustomAttribute(
>           parsedJson["custom_attributes"], element);
>       if (item != null) {
>         attributeList.add(Attribute.fromMagentoJson(
>             {"value": item, "attribute_code": element}));
>       }
>     });
>     attributes = attributeList;
>   }
> ```

Hello ,

I imported below in 
import '../../common/config/general.dart';

And Made the changes as you said, but nothing changed .. same Issues as before

![product-search-report](https://user-images.githubusercontent.com/63896811/82874140-24662f80-9f53-11ea-83b2-bf8e7c2af234.PNG)

**Comment by saudadev** [comment]
Hi @minhtruong315 @minhcasi ,

I have added few more issues, Is this Product works for Magento?

**Comment by saudadev** [comment]
Added two more issue, total Open 8

**Comment by minhtruong315** [comment]
what is Fluxstore version you're using?

**Comment by saudadev** [comment]
@minhcasi @minhtruong315 
Flux Store 1.7.3 

![version](https://user-images.githubusercontent.com/63896811/82976907-fee23000-9ffd-11ea-9d1b-60f22ecf256f.PNG)

**Comment by saudadev** [comment]
Hi @minhcasi @minhtruong315 ,

Is there any ETA for resolution for these issues?

**Comment by minhtruong315** [comment]
Hi @saudadev can u update Fluxstore 1.7.4? it's released.

**Comment by saudadev** [comment]
> Hi @saudadev can u update Fluxstore 1.7.4? it's released.

Hi @minhcasi @minhtruong315 I will try out on 1.7.4 but is my issues addressed on 1.7.4 version?

**Comment by saudadev** [comment]
> > Hi @saudadev can u update Fluxstore 1.7.4? it's released.
> 
> Hi @minhcasi @minhtruong315 I will try out on 1.7.4 but is my issues addressed on 1.7.4 version?

Hey @minhcasi @minhcasi , 

I updated the Version Still the same issues. 

You just put a message change version and **didn't replied on when I specifically asked you if any my issues are addressed.** 

**Today I added one more Issue when you try to reset Password from App you get exceptions because you have hard coded WordPress password reset Link, it doesnt check if the Backend is Magento or not.**

Please note I have spent hours in testing and reporting these issues to you and these issues are with basic Magento Setup with Zero Modification to your code base. This is my strongest believe now you haven't done proper testing for Magento before releasing your product. 

Will appreciate if you seriously look into my issues and post resolutions.

**Comment by minhcasi** [comment]
@minhtruong315 - pls help to investigate these issues on Magento - thank you!

**Comment by minhtruong315** [comment]
Hi @saudadev Thanks for your reports. Are your issues Reset Password link? Can you list me your issues? We will investigate and update them on next version.

**Comment by saudadev** [comment]
> Hi @saudadev Thanks for your reports. Are your issues Reset Password link? Can you list me your issues? We will investigate and update them on next version.

Hi @minhtruong315 ,

**All of my issues are listed in First Post, please scroll up.**

I was creating separate post for each issue but @minhcasi advised me to update all my issues in one post. He also closed all other issues.

You advertise this product saying its support Magento as back-end, but if you look into my issues these are very basic issues so your code base is not fully operational for Magento. 

Fixing it in your next version will delay our product release, please start fixing and providing resolution now and combine these fixes to your next release.

I will thoroughly test your product as you fix issues one by one.  

I have also started going through your code to see if I can be of any help to fix these issues.

One request, please start posting resolutions. Your once in a day reply make no sense of your support model. Today is Day 9, not single issue been fixed by you.

**Comment by minhcasi** [comment]
@saudadev 
We wanted to thank you for your patience during this busy time. We currently have reduced staff and a significantly higher volume of inquiries. We’re working as hard as we can to get to your request as soon as possible.

We sincerely apologize for the delay and hope you’re staying safe.

@minhtruong315 - pls help to investigate these issues carefully!

**Comment by minhtruong315** [comment]
Hi @saudadev can u upload your source code to github then invite me: minhtruong315@gmail.com.
I'll check and fix on your source code.
Thanks

**Comment by saudadev** [comment]
> Hi @saudadev can u upload your source code to github then invite me: [minhtruong315@gmail.com](mailto:minhtruong315@gmail.com).
> I'll check and fix on your source code.
> Thanks

Hi @minhcasi @minhtruong315 ,
I have started fixing couple of Issue and also fixed some of them , you can see more details at First Post.

I have active repository in GitLab, Please share me your Gitlab ID, you can also see my fixes and improve the changes if required. 

If you can share your Source Code Documentation, it will be easier for me to work on your code.

Regards,

**Comment by saudadev** [comment]
hi @minhcasi @minhtruong315 ,

Added one More Issue of MaxCart Quantity, needs to be Dynamic not a fixed value of 100.

**Comment by minhtruong315** [comment]
Hi @saudadev can u invite me to your gitlab project with email: minhtruong315@gmail.com?
Thanks

**Comment by saudadev** [comment]
> Hi @saudadev can u invite me to your gitlab project with email: [minhtruong315@gmail.com](mailto:minhtruong315@gmail.com)?
> Thanks

Hi @minhcasi @minhtruong315 ,

I have sent you the invite. Please check.

**Comment by saudadev** [comment]
Hi @minhcasi , @minhtruong315 ,

I am trying to fix below issue of 
*******************************************************************************************************
ISSUE : 10 (TEN) : Not Fixed 👎

**Summary : For Our App its a Mandatory Feature that the items Quantity a customer can Order should be limited and the data should be dynamic from Magento **

*******************************************************************************************************

I have checked in a commit yesterday on Gitlab, I have created a function in magento.dart to get the "max_sale_qty" from /V1/stockItems/sku in both Product and Product Variant.

As the Product Variant get initialized when we click for Product Details, the Future Async function to get Max_sale_qty get called at that time. 

Now I am able to get max quantity for both Product and Product Variant but for Product Variant the first screen gets the default 100 limit and when i select any variant then the real stockquantity get reflected.

Please check my code.

**Comment by minhtruong315** [comment]
Hi @saudadev Please pull source code. I fixed ISSUE 2
for ISSUE : 5. We will research to update API to get all. It can't get all products on child category for now.
for ISSUE : 6. I updated this on our source code. it will be available on next release.
ISSUE : 8 it's working well now.
![Simulator Screen Shot - iPhone X - 2020-06-05 at 18 49 22](https://user-images.githubusercontent.com/10402500/83873064-4a62af80-a75d-11ea-8f9e-9720cab438fc.png)
ISSUE : 11 you can scroll to see more number

**Comment by minhtruong315** [comment]
Hi @saudadev I can't commit code
<img width="699" alt="Screen Shot 2020-06-05 at 6 54 42 PM" src="https://user-images.githubusercontent.com/10402500/83873475-13d96480-a75e-11ea-9d0d-8cdc6853e5d4.png">

**Comment by saudadev** [comment]
> Hi @saudadev I can't commit code
> <img alt="Screen Shot 2020-06-05 at 6 54 42 PM" width="699" src="https://user-images.githubusercontent.com/10402500/83873475-13d96480-a75e-11ea-9d0d-8cdc6853e5d4.png">

Please try now

**Comment by saudadev** [comment]
> Hi @minhcasi , @minhtruong315 ,
> 
> I am trying to fix below issue of
> 
> ISSUE : 10 (TEN) : Not Fixed 👎
> 
> **Summary : For Our App its a Mandatory Feature that the items Quantity a customer can Order should be limited and the data should be dynamic from Magento **
> 
> I have checked in a commit yesterday on Gitlab, I have created a function in magento.dart to get the "max_sale_qty" from /V1/stockItems/sku in both Product and Product Variant.
> 
> As the Product Variant get initialized when we click for Product Details, the Future Async function to get Max_sale_qty get called at that time.
> 
> Now I am able to get max quantity for both Product and Product Variant but for Product Variant the first screen gets the default 100 limit and when i select any variant then the real stockquantity get reflected.
> 
> Please check my code.

Can you please check this commit, one thing due is to delay render or put some logic where Variant will come with proper stock quantity?

**Comment by saudadev** [comment]
> Hi @saudadev Please pull source code. I fixed ISSUE 2
> for ISSUE : 5. We will research to update API to get all. It can't get all products on child category for now.
> for ISSUE : 6. I updated this on our source code. it will be available on next release.
> ISSUE : 8 it's working well now.
> ![Simulator Screen Shot - iPhone X - 2020-06-05 at 18 49 22](https://user-images.githubusercontent.com/10402500/83873064-4a62af80-a75d-11ea-8f9e-9720cab438fc.png)
> ISSUE : 11 you can scroll to see more number

Hi @minhtruong315 ,

Thanks a lot for Fixing Search Showing All Variant of Primary Product, but now its showing all the products for the search of "rice"

Can you please check the code?

![Seacrh-App-Showing-All-Products-PostFix](https://user-images.githubusercontent.com/63896811/83918347-2c657100-a796-11ea-9671-9e8055e04f63.png)

**Comment by saudadev** [comment]
Hi @minhcasi @minhtruong315 ,

One more thing I have noticed At Start the App get stuck in Exception 

Below is the Exception Details

```

#0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure> (package:flutter/src/widgets/framework.dart:3785:9)
#1      Element._debugCheckStateIsActiveForAncestorLookup (package:flutter/src/widgets/framework.dart:3799:6)
#2      Element.findAncestorStateOfType (package:flutter/src/widgets/framework.dart:3918:12)
#3      Navigator.of (package:flutter/src/widgets/navigator.dart:2135:19)
#4      _AnimatedSplashState.build.<anonymous closure> (package:fstore/widgets/common/animated_splash.dart:75:23)
#5      _RootZone.runUnary (dart:async/zone.dart:1450:54)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#9      Future._complete (dart:async/future_impl.dart:519:7)
#10     new Future.delayed.<anonymous closure> (dart:async/future.dart:321:16)
#11     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#12     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)
#13     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

Debug Log

`E/flutter (16985): #13     _CustomZone.run  (dart:async/zone.dart:1093:19)
E/flutter (16985): #14     _CustomZone.runGuarded  (dart:async/zone.dart:997:7)
E/flutter (16985): #15     _CustomZone.bindCallbackGuarded.<anonymous closure>  (dart:async/zone.dart:1037:23)
E/flutter (16985): #16     _rootRun  (dart:async/zone.dart:1190:13)
E/flutter (16985): #17     _CustomZone.run  (dart:async/zone.dart:1093:19)
E/flutter (16985): #18     _CustomZone.bindCallback.<anonymous closure>  (dart:async/zone.dart:1021:23)
E/flutter (16985): #19     Timer._createTimer.<anonymous closure>  (dart:async-patch/timer_patch.dart:18:15)
E/flutter (16985): #20     _Timer._runTimers  (dart:isolate-patch/timer_impl.dart:397:19)
E/flutter (16985): #21     _Timer._handleMessage  (dart:isolate-patch/timer_impl.dart:428:5)
E/flutter (16985): #22     _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:168:12)`

Image of Exception

![Exception-At-Start](https://user-images.githubusercontent.com/63896811/83918951-54a19f80-a797-11ea-86e9-dc4a9c6e2796.PNG)

**Comment by saudadev** [comment]
Hi @minhcasi @minhtruong315 ,

For the Issue 9-A I have written API call function to send email to reset password.

I Pushed a commit, only issue is after the API Call Success its going back to Login Screen without showing a Message That Email Sent Successfully can you please check.

**Comment by minhtruong315** [comment]
Hi @saudadev I checked your source code. it only shows one product
<img width="421" alt="Screen Shot 2020-06-08 at 2 12 55 PM" src="https://user-images.githubusercontent.com/10402500/84002189-3a7fe100-a992-11ea-8c85-01bf0a33b103.png">

**Comment by minhtruong315** [comment]
> Hi @minhcasi @minhtruong315 ,
> 
> For the Issue 9-A I have written API call function to send email to reset password.
> 
> I Pushed a commit, only issue is after the API Call Success its going back to Login Screen without showing a Message That Email Sent Successfully can you please check.

I helped you fix reset password. please pull the source code and check again
Thanks

**Comment by saudadev** [comment]
> Hi @saudadev I checked your source code. it only shows one product
> <img alt="Screen Shot 2020-06-08 at 2 12 55 PM" width="421" src="https://user-images.githubusercontent.com/10402500/84002189-3a7fe100-a992-11ea-8c85-01bf0a33b103.png">

Hi @minhcasi @minhtruong315 ,

I have attached a video below please check.

The issue as per my understanding is the Search box start searching as we put the cursor on the Search, it takes blank as Wildcard %% 

![ezgif-6-6d8af4d0392c (1)](https://user-images.githubusercontent.com/63896811/84054426-01b32c80-a9d1-11ea-9613-5ac108751eaf.gif)

**Comment by minhtruong315** [comment]
Hi @saudadev pls accept the permission to see the video.
Thanks

**Comment by saudadev** [comment]
> Hi @saudadev pls accept the permission to see the video.
> Thanks

Its been Shared with you.

**Comment by saudadev** [comment]
Hi @minhcasi  @minhtruong315 ,

On ISSUE 13, can you please share me Front End code that you have published in App Store.

On ISSUE 7, can you please take care of Coupon Expired for both Check out and Apply Coupon Button.
Apply Coupon on Expired Token throws big UGLY Exception.

**Comment by saudadev** [comment]
> > Hi @saudadev pls accept the permission to see the video.
> > Thanks
> 
> Its been Shared with you.

Hello @minhcasi @minhtruong315 ,

On the Search Issue my 2 cents will be

1. Disable Auto Search as you type, Search only when click Search Button on Key Pad

```
TextField(
  textInputAction: TextInputAction.search,
  onSubmitted: (value) {
    print("search");
  },
  decoration: InputDecoration(
    border: InputBorder.none,
    prefixIcon: Icon(Icons.search),
    hintText: 'Search ',
    contentPadding: EdgeInsets.fromLTRB(20.0, 15.0, 20.0, 15.0),
  ),
);. 
```
https://api.flutter.dev/flutter/services/TextInputAction-class.html#constants

2. You have hard coded the Name Suggestion  Like below
```
"searchSuggestion": [
    "man",
    "dress",
    "Stitch",
    "ma"
  ],
```

In this case we can just add a Search Query from Magento API with below endpoint, it will fetch only names, sku and status and suggest as you type.

`V1/mstore/products?searchCriteria[filter_groups][0][filters][0][field]=name&searchCriteria[filter_groups][0][filters][0][value]=%%&searchCriteria[filter_groups][0][filters][0][condition_type]=like&searchCriteria[currentPage]=1&searchCriteria[pageSize]=20&searchCriteria[filter_groups][1][filters][0][field]=visibility&searchCriteria[filter_groups][1][filters][0][value]=4&fields=items[sku,name,status]`

3. On Click of Search it will Search as per your existing code.

It will make the app Lighter in operations.

**Comment by minhtruong315** [comment]
Hi  @saudadev add my skype: minhtruong315
I will help you check via teamviewer
Thanks

**Comment by saudadev** [comment]
Hi @minhtruong315 ,

Added you.

**Comment by minhtruong315** [comment]
Hi @saudadev ping me on the skype. Thanks

**Comment by minhtruong315** [comment]
Hi @saudadev I commented your issues on the skype. please check. Thanks

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!

**Comment by saudadev** [comment]
I am working on it. Please dont close it.

**Comment by minhcasi** [comment]
@saudadev - try to comment on your status on this ticket - thank you!

**Comment by saudadev** [comment]
Thanks .. will update you once I made all the changes.

**Comment by saudadev** [comment]
Hi @minhcasi @minhtruong315 ,

When you upgrade your Core Version its is very difficult for me to see whats changed.
Is there any Change Log or can I only get Magneto Related Upgrade.
All other Code Base like Open Cart Woo Commerce Sopify and now prestashop increases our release code base. Which are not needed at all for magento.

Any Solutions?

**Comment by minhtruong315** [comment]
Hi @saudadev somewhere I can find and remove other services. You should search all source code to remove other services as well
<img width="676" alt="Screen Shot 2020-06-24 at 6 25 29 AM" src="https://user-images.githubusercontent.com/10402500/85477099-d68d2780-b5e3-11ea-854f-1f700802624e.png">

<img width="438" alt="Screen Shot 2020-06-24 at 6 27 08 AM" src="https://user-images.githubusercontent.com/10402500/85477091-d2f9a080-b5e3-11ea-8782-a138d2622f16.png">

**Comment by saudadev** [comment]
Hi @minhtruong315 ,

Do you have any sh script which will do that for me?

**Comment by minhtruong315** [comment]
@saudadev No. I dont have. I do it manually

**Comment by saudadev** [comment]
Hi @minhtruong315 ,

My Country has made Mandatory to show Country of Origin in Product Listing, Magneto has the Data, how to show it in App.

**Comment by minhtruong315** [comment]
Hi @saudadev I only support issues for integrating with your website. I dont support customize code. You can research and implement that.
Thanks

**Comment by amjadalfawal** [comment]
@saudadev check i shared some fixing about magento in this issue please check 
https://github.com/inspireui/support/issues/3705

**Comment by minhtruong315** [comment]
@amjadalfawal Thanks for your support.

**Comment by saudadev** [comment]
> @saudadev check i shared some fixing about magento in this issue please check
> #3705

Thanks @amjadalfawal .. Will check that.

**Comment by saudadev** [comment]
Hi @minhcasi @minhtruong315,

How to enable lazy loading of items, in product listing?

**Comment by saudadev** [comment]
I have shared a video with you on Sykpe, Hi @minhcasi  Please provide access to user also reopen tickets.

**Comment by saudadev** [comment]
Hi @minhcasi , @minhtruong315 ,

I have added Issue Number 15, 16 & 17. 16 was reported over email with video. We are end of our development, please help to close these ASAP.

**Comment by saudadev** [comment]
Will create a new Ticket
