### ISSUE TITLE
Does your Fluxstore Multi Vendor - Flutter E-commerce Full App support multi-sites?

### ISSUE THREAD

**Issue by peaceedotcom** [inspireui/support#3372]
Step 1 (require): detail issues and screenshots
Does your Fluxstore Multi-Vendor - Flutter E-commerce Full App support multi-sites? I have just installed Dokan on my multisite, and it's not letting me log in to my admin of one of the multisite. SO does your product support multisite, if yes, which multivendor plugin is compatible.

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by minhcasi** [comment]
Hi, sorry this product does not support the multi-site :)
