### ISSUE TITLE
Login And sign up isse

### ISSUE THREAD

**Issue by lucsonpay** [inspireui/support#3373]
Step 1 (require): detail issues and screenshots

Hi, i did all the things mentioned in the document, but after updating to latest version of Fluxstore, the issue with woocommerce login it is not working and giving the error on sign in as well as sign up. Please find attached screen shot 

Signup screen shot for sms login

https://lucsone.com/demoWeb/wordpress/wp-content/uploads/2020/05/Screenshot-2020-05-23-at-1.28.34-PM.png

Login Screen shot

https://lucsone.com/demoWeb/wordpress/wp-content/uploads/2020/05/Screenshot-2020-05-23-at-1.16.38-PM.png

for login the user name and password is the root user name and password for my wordpress web.

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@lucsonpay - pls try to update your website URL as the subdomain, as the API will not work well on subfolder that will cause the issue

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
