### ISSUE TITLE
Installation error.

### ISSUE THREAD

**Issue by waghankit** [inspireui/support#3375]
<img width="1280" alt="Screenshot 2020-05-19 at 7 29 21 PM" src="https://user-images.githubusercontent.com/47549138/82728231-c47e4780-9d0c-11ea-8986-c0590f1a9db6.png">

**Comment by minhcasi** [comment]
@waghankit - pls help us to submit your verified purchase to this link - https://docs.google.com/forms/d/e/1FAIpQLScWOjkAJIWJ9rgb9alopfOqLsJrGKbFM5cCYj1JBfLKLsBblQ/viewform

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as it could not be verified, please create the new one when you got enough purchased info - thank you!

**Comment by minhcasi** [comment]
@waghankit - we got your verify purchased and assigned to the team for investigating - thank you!

**Comment by minhcasi** [comment]
@waghankit - pls try to downgrade your nodejs to 10.x (the current is 13.x on your PC that will cause the issue) - this is the library - https://nodejs.org/dist/latest-v10.x/

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Comment by waghankit** [comment]
Solved . Thank you
