### ISSUE TITLE
Fluxstore iOS App Rejected on Appstore - Guideline 3.1.1 - Business - Payments - In-App Purchase

### ISSUE THREAD

**Issue by jeeali** [inspireui/support#3376]
Step 1 (require): detail issues and screenshots

--------------

Here is the detail from Appstore:
Guideline 3.1.1 - Business - Payments - In-App Purchase

We noticed that your app or its metadata provides access to external mechanisms for purchases or subscriptions to be used in the app, which does not comply with the App Store Review Guidelines.

Next Steps

To resolve this issue, please remove the account registration links and any other fully qualified links to your site that could indirectly provide access to these mechanisms, such as links to web pages for support, FAQs, product or program details, etc.

In-App Purchase

It may be appropriate to revise your app to use the in-app purchase API to provide content purchasing functionality.

In-app purchase provides several benefits, including:

- The flexibility to support a variety of business models.
- Impacting your app ranking by consolidating your sales to one app rather than distributing them across multiple apps.
- An effective marketing vehicle to drive additional sales of new content.

For information on in-app purchase, please refer to the following documentation:

In-App Purchase for Developers

In-App Purchase Programming Guide

For step-by-step instructions on in-app purchase creation within App Store Connect, refer to App Store Connect Help.

----------
Can you please tell me what should I change during submission!

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

I filled the form

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@jeeali - the fluxstore product did not provide In-App Purchase, did you add this feature?

**Comment by jeeali** [comment]
> @jeeali - the fluxstore product did not provide In-App Purchase, did you add this feature?

No Brother. I haven't added anything.
I just changed some colors and config_en.json and edit config files. I sent you guys the common folder as a zip in google form as well.

**Comment by jeeali** [comment]
In the issue they sent. It is clear that I haven't added In-App Purchase. They are asking me to add In-App Purchase in a case to make this App live on Appstore.

They wrote the NEXT STEPS.
But, I don't get it fully. Did you guys face any issue during the AppStore Deployment. If Yes, How can we resolve this!

**Comment by jeeali** [comment]
Can you suggest me anything?

**Comment by minhcasi** [comment]
"your app or its metadata provides access to external mechanisms for purchases" -> this could be 2 reasons.

- Your app description or banner intro is not described correctly about your app (relate to meta_data)
- What the current payment system you are using so far?
- Please also note the category that you assign your app, are per our experience, each category will be applied difference preview policies, please check Apple docs and apply correct category setting.
- Also, share your app TestFlight to my email minhcasi@gmail.com - i could give some feedbacks

**Comment by jeeali** [comment]
1. Below are the Appstore Description, Banner Intro. Please check.

**Promotional Text:** Need your fashion fix on the move? Shop using the Ciera Couture app

**Description:** Ciera Couture is an affordable online shopping platform with a distinct tone focusing on women's fashion. No matter what the current fashion trend is, CieraCouture.com is sure to follow it or even lead it. With all the categories like women's clothing, shoes and accessories. Ciera Couture is a one-stop destination for fashionistas. Shopping becomes even more enjoyable with the new Ciera Couture mobile app. 

• Buy straight from our app to get essential new season women's clothing delivered straight to your door.
• Don't have time right now? No worries, add your favorite outfit to your cart, add to your wishlist to add to bag later.
• While you're on your phone - join our squad and share your selfie with the hashtag #3174 

**Keywords:** ciera couture, fashion, women, online shopping

2. Current Payment is Paypal only.

3. Main Category-> Shopping
    Sub Category -> Lifestyle

4. I added you as a Tester in TestFlight
