### ISSUE TITLE
not display items in 'SEE ALL' main category.

### ISSUE THREAD

**Issue by ravindam** [inspireui/support#3377]
not display items in 'SEE ALL' main category.
i want to display subcategories item in select main category

![Screenshot_2020-05-23-10-06-25-076_com inspireui fluxstore](https://user-images.githubusercontent.com/63419889/82731619-e3d59e80-9d25-11ea-8e04-32d1759d4d7d.jpg)

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as it could not be verified, please create the new one when you got enough purchased info - thank you!
