### ISSUE TITLE
how to place admob on different screen of Aap?

### ISSUE THREAD

**Issue by surajk1986** [inspireui/support#3379]
I HAVE purchased the App ......how to send purchase proof 

Step 1 (require): at present admob present active on  on product description section .

i want to enable all 3 ads banner ,Interstitial,and reward add in different section of App(home screen-interstitial ad , product layout -banner ad, product description -interstitial ad)

PLEASE HELP 
![GOOGLE AD](https://user-images.githubusercontent.com/65123761/82734529-6acd4b80-9d13-11ea-8bf0-d81592fb819f.jpg)

**Comment by minhcasi** [comment]
@dttrung26 - pls suggest on this ticket

**Comment by minhcasi** [comment]
@dttrung26 - we could upgrade the app to allow config via Fluxbuilder as well

**Comment by surajk1986** [comment]
how ....to apply changes ...due you have any solution

**Comment by minhcasi** [comment]
@surajk1986 - we are working on this upgrade and will release it on the next version - thank you!

**Comment by surajk1986** [comment]
when will be next update ?

**Comment by dttrung26** [comment]
Hi @surajk1986 , we can't tell you for sure, but at most next patch of FluxBuilder will be released next month. Please keep yourself up-to-date with our update. Thanks for your patience. 
Have a nice day!

**Comment by surajk1986** [comment]
![Screenshot_1590564496](https://user-images.githubusercontent.com/65123761/82990467-27fdc300-9ff4-11ea-8ab8-f3c4771ed232.png)
GETTING LOGIN ERROR
