### ISSUE TITLE
[ListApp]while clicking the booking button it's show error message

### ISSUE THREAD

**Issue by Pavithran10** [inspireui/support#338]
**Required Info (please complete the following information):**
Product:[ListApp]
Version:1.6.1
Theme: MyListing

**Describe the bug**
hi, In listapp product booking page while clicking booking button without any login its will redirect to login page. otherwise any user account  login already in the app after while clicking the booking button it's show error message please check the error ASAP. thanks

**Screenshots**
![booking](https://user-images.githubusercontent.com/46148046/53466808-7337c780-3a79-11e9-839f-784a4a2d02e4.jpg)
![bookingerr](https://user-images.githubusercontent.com/46148046/53466815-7a5ed580-3a79-11e9-977f-7a67faf03ae9.png)

**Comment by thangvo9x** [comment]
Hi. Thanks for your valuable feedback. We noted & fix it in the next update

**Comment by Pavithran10** [comment]
thanks for your reply
