### ISSUE TITLE
Edit Some Menu

### ISSUE THREAD

**Issue by harjono-flux** [inspireui/support#3380]
Hello, plis help

1. How edit this field? i want add phone number, and remove nicename and url
Setting - Update Profile
![WhatsApp Image 2020-05-24 at 00 43 25](https://user-images.githubusercontent.com/64935574/82735888-c4576980-9d57-11ea-8ab1-6a5c04c80f9c.jpeg)

2. How to change the setting background image? If using the original path, its oke (orange fruit with blue background). If i change to local path, its not appear the image i want
![Screen Shot 2020-05-24 at 00 54 26](https://user-images.githubusercontent.com/64935574/82736034-206ebd80-9d59-11ea-817a-c2399484b050.png)

3. How to add/remove some menu at setting page?
4. How to config the order at category layout? In default, i see, sort by name. I want change, sort by ID

Thx b4

**Comment by minhcasi** [comment]
@harjono-flux - could you have a look to the Fluxbuilder tool - http://fluxbuilder.com/ - it will help you config the question 2-3-4

The registration could be customize on this file
<img width="1280" alt="Screen Shot 2020-05-24 at 14 01 14" src="https://user-images.githubusercontent.com/1459805/82747803-08ce1e00-9dc7-11ea-8ab7-f9222d05cb2f.png">

**Comment by harjono-flux** [comment]
Thx for ur reply.
Q1 and 2 is solved.

Q3, how about if i wanna add menu;
name : whatsapp
when someone click, its a url to https://api.whatsapp.com/send?phone=0816255779
Q4, flexbuilder cannot sort in Drawer

![WhatsApp Image 2020-05-25 at 11 56 37](https://user-images.githubusercontent.com/64935574/82777122-c9afd380-9e7f-11ea-9a3a-0179e328afb2.png)

**Comment by minhcasi** [comment]
@harjono-flux - the sorting on the category from the Drawer will fix on next release of Fluxbuilder

You could try to add the ChatMe function as this feature is not ready to support from the app 🥇

**Comment by harjono-flux** [comment]
Yeah, because i try to use whatsapp url to my banner, and the result this is (this pict i get from google, because im not on my phone when i send this message).
Any solution?

![xTaht](https://user-images.githubusercontent.com/64935574/82846671-9cfdc980-9f1c-11ea-9aab-2759ed4909b7.png)

**Comment by minhcasi** [comment]
@harjono-flux - pls try this schema instead `https://wa.me/+91886xxxx`

**Comment by harjono-flux** [comment]
same error. When i use 081, this error appear
![WhatsApp Image 2020-05-26 at 20 27 19](https://user-images.githubusercontent.com/64935574/82900884-c277eb00-9f8f-11ea-80a5-426a99abdd79.jpeg)


when use +6281 (+62 is my country code), this window appear

![WhatsApp Image 2020-05-26 at 20 28 24](https://user-images.githubusercontent.com/64935574/82900862-b9871980-9f8f-11ea-9fe0-4647dce114da.jpeg)

**Comment by minhcasi** [comment]
@harjono-flux - you could try some example on this link https://faq.whatsapp.com/en/iphone/23559013 - thank you!

**Comment by harjono-flux** [comment]
> @harjono-flux - you could try some example on this link https://faq.whatsapp.com/en/iphone/23559013 - thank you!
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/99298c91e1615acf87ce60a04a30c324466edc3b/68747470733a2f2f7374617469632e77686174736170702e6e65742f727372632e7068702f76332f794f2f722f4673575571526f4f7350752e706e67">WhatsApp.com**[WhatsApp FAQ - How to link to WhatsApp from a different app](https://faq.whatsapp.com/en/iphone/23559013)**How to link to WhatsApp from a different app - There are several ways to have your iPhone application interact with WhatsApp: universal links, custom URL schemes, share extension, and the Document Interaction API.
> > Universal links
> > Universal links are the preferred method of linking to a WhatsApp account.
> > Use https://wa.me/<number> where the <number> is a full phone number in international format.

Already trying, but same result. This the error when i press the banner that link to whatsapp
![Screen Shot 2020-05-27 at 19 29 04](https://user-images.githubusercontent.com/64935574/83013897-5610f080-a050-11ea-9854-9b4cd21b54d0.png)

**Comment by harjono-flux** [comment]
> @harjono-flux - you could try some example on this link https://faq.whatsapp.com/en/iphone/23559013 - thank you!
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/99298c91e1615acf87ce60a04a30c324466edc3b/68747470733a2f2f7374617469632e77686174736170702e6e65742f727372632e7068702f76332f794f2f722f4673575571526f4f7350752e706e67">WhatsApp.com**[WhatsApp FAQ - How to link to WhatsApp from a different app](https://faq.whatsapp.com/en/iphone/23559013)**How to link to WhatsApp from a different app - There are several ways to have your iPhone application interact with WhatsApp: universal links, custom URL schemes, share extension, and the Document Interaction API.
> > Universal links
> > Universal links are the preferred method of linking to a WhatsApp account.
> > Use https://wa.me/<number> where the <number> is a full phone number in international format.

Already trying, but same result. This the error when i press the banner that link to whatsapp
![Screen Shot 2020-05-27 at 19 29 04](https://user-images.githubusercontent.com/64935574/83013897-5610f080-a050-11ea-9854-9b4cd21b54d0.png)

**Comment by minhcasi** [comment]
@harjono-flux - could you share the screenshot issue of which code that you put this config? The banner url may not support as it is using Webview inside the app - try to use `url_launcher` function  - https://pub.dev/packages/url_launcher

**Comment by harjono-flux** [comment]
this banner

![Screen Shot 2020-05-29 at 00 37 50](https://user-images.githubusercontent.com/64935574/83168809-a36e8a00-a144-11ea-8f6d-f99c63cc8b51.png)

**Comment by minhcasi** [comment]
1. try to edit the json to `"url_launch": "https://wa.me/84988808854"`

2. Update the banner item as below code+screenshot:

```
    import 'package:url_launcher/url_launcher.dart';
    ....

    if (widget.config['url_launch'] != null) {
      launch(widget.config["url_launch"]);
    }
```

<img width="1441" alt="Screen Shot 2020-05-29 at 09 36 51" src="https://user-images.githubusercontent.com/1459805/83214911-f02b8280-a18f-11ea-8924-41bba65babfc.png">

**Comment by harjono-flux** [comment]
Yesss... thx, its works. 

I continue with my question,
1. how to make cash on delivery payment method as native payment? Because if take from woo, is loading 1-2 second
2. how to add loading animation, when someone click the banner, and the url web is loading?
3. how to make smartchat appear at the homescreen?
4. in blog, it is true, this page cannot support html format? because in web the table is looking good, but at app blog, the table to be text code
5. Is it true, to make our instagram apprear, i put this query at config_xx.json?
{
"name": "Follow Us",
"layout": "instagram",
"tag": "hpkita.co.id"
}
*hpkita.co.id is my instagram name

**Comment by minhcasi** [comment]
@harjono-flux - We wanted to thank you for your patience during this busy time. We currently have reduced staff and a significantly higher volume of inquiries

For some questions like "How to customize.." app, please forgive us as we could not answer, due to the limit of the scope support - hope you could understand and try to discover more about the app.

**Comment by harjono-flux** [comment]
hmmm... oke i understand.
but, plis answer this case https://github.com/inspireui/support/issues/3439
thx

**Comment by minhcasi** [comment]
Thank you for your understanding, we are appreciated that. 

I'm closing this ticket and reopen the 3439 issue to support you on the login issue 😊
