### ISSUE TITLE
Issue with autofill if logged in by sms

### ISSUE THREAD

**Issue by yasernet1989** [inspireui/support#3381]
Step 1 (require): detail issues and screenshots
Hi,
Once i logged in with SMS, 1. the name is auto filled with my number. 2. the email field is auto filled with my number@mydomain.com !!!. 3. the number field is blank while it should be filled with my number.

Check this shot
![Screenshot_20200524-022814](https://user-images.githubusercontent.com/64695299/82742584-dee60e80-9d68-11ea-96d1-b4e53fb4b287.png)

Please help to fix that. Im using 1.7.2
Thanks

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by minhcasi** [comment]
As when login via SMS the app could not get your username, that why it will pick up the phone number as the default username.

It is possible to change the profile via the Setting page. Thank you!

**Comment by yasernet1989** [comment]
No relation between the (First Name) and the phone number! 
How come the first name in the bill is a phone number?! 
and the email is the number @ my domain!!!
Your solution that each user has to edit manually and move the number from (First name Field) to (Phone Number field) in setting page is unrealistic. Sorry to say that.

The good solution is the phone number field to be filled with the phone number which used to sign in. Other fields to be blank and to be filled by the customer.

**Comment by minhcasi** [comment]
@yasernet1989 - do you think to route to the Edit profile after user Login by SMS is a good solution? From then we could ask them to update the profile

**Comment by yasernet1989** [comment]
No need to route anything. No need to ask user to update anything.
Just after login by sms the address screen to be like this: Instead of the screenshot above

![Screenshot_20200524-0228222](https://user-images.githubusercontent.com/64695299/82805305-77c17a80-9e8c-11ea-8a2a-b31b22cdbca5.png)

**Comment by minhcasi** [comment]
@yasernet1989 - thank you for the suggestion - we will investigate and upgrade this feature

**Comment by minhcasi** [comment]
@minhtruong315 - pls upgrade the mstore-api plugin to upgrade the UX for mobile SMS registration

**Comment by minhcasi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [UX: update Mobile phone when login as SMS](https://trello.com/c/q8FPO8bB/59-ux-update-mobile-phone-when-login-as-sms)

**Comment by minhcasi** [comment]
Added to backlog for next improvement
