### ISSUE TITLE
Tip : cache in the App 

### ISSUE THREAD

**Issue by Roupasafricanas** [inspireui/support#3382]
Step 1 (require): detail issues and screenshots

![81374852-9840b500-90d6-11ea-9969-76c9b9cb999c](https://user-images.githubusercontent.com/63840938/82743048-e17e3f00-9d3b-11ea-8550-3288321100f9.jpg)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

I would like to make a suggestion: I added the community page of my store in the menu and to enter needs registration. Every time the costumer quit the tab reserved to the community, it needs to digit the login again. Could you include a native cache to save logins other than WooCommerce, or does this function already exist?

**Comment by minhcasi** [comment]
@Roupasafricanas - could you help to share your app so that we could investigate this feature? Did you release the app successfully on stores

**Comment by Roupasafricanas** [comment]
Thanks for the quick response. My app is being approved on Google console. Do you have an email? I can share it by drive in the meantime. This update would be very important. I'll show you prints to explain better.
1) I inserted the community page into the tab so below and it requires to log in
![IMG_20200524_061015](https://user-images.githubusercontent.com/63840938/82750349-f4b5fc80-9d85-11ea-95b0-241f0791c5ab.jpg)
2) customers who have access to the community login by inserting their data and gain access
![IMG_20200524_061116](https://user-images.githubusercontent.com/63840938/82750377-26c75e80-9d86-11ea-8f9e-48b98cb1fe4d.jpg)
![IMG_20200524_061142](https://user-images.githubusercontent.com/63840938/82750392-39419800-9d86-11ea-9323-7e5756581c74.jpg)
3) If by mistake the user logout and goes into a tab of the shop, when he returns he must again log in 
![IMG_20200524_061234](https://user-images.githubusercontent.com/63840938/82750432-73129e80-9d86-11ea-8692-dec40949af1f.jpg)
. 
So I'd like to know if it's possible to put a Login cache so that he doesn't always have to insert his data. 
For example, like Facebook, where data is usually pre-loaded
![IMG_20200524_061259](https://user-images.githubusercontent.com/63840938/82750456-b4a34980-9d86-11ea-900f-fee27b6152a2.jpg).

**Comment by minhcasi** [comment]
@Roupasafricanas - pls help to share your source to support@inspireui.com - this feature need to be investigated to find new solution to fix it - thank you!
