### ISSUE TITLE
I cannot change english language to other languages.

### ISSUE THREAD

**Issue by zawwinhtunn** [inspireui/support#3383]
Please help me sir.I have one issue that I cannot change language in my app. When I change english to other language show this error.i installed latest version .please fix my issue .

error screen shot is 
https://github.com/zawwinhtunn/multiflutter/blob/master/language%20error.jpg

this is my ss of purchased .
https://github.com/zawwinhtunn/multiflutter/blob/master/purchase.PNG

this is my downloaded version .https://github.com/zawwinhtunn/multiflutter/blob/master/latest%20version%201.7.3.PNG

**Comment by minhcasi** [comment]
@zawwinhtunn - please help to add this value to your all `config_xx.json` file
```
 "Setting": {
    ...
    "StickyHeader": false
  },
```

screenshot : https://tppr.me/YSaTO

**Comment by minhcasi** [comment]
Let us know if you have any question, feel free to reopen the ticket 👍
