### ISSUE TITLE
shipping class not working in the app.

### ISSUE THREAD

**Issue by zawwinhtunn** [inspireui/support#3384]
Step 1 (require): detail issues and screenshots

woocommerce shipping classes calculation not work in the app, it just show basic shipping not support main woocommerce shipping classes.please help me.

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@zawwinhtunn - the shipping class is known issue on the current release of fluxstore mv - we are working on the new release and fix this issue on next version 

Please help us to move your all conversation to the same ticket #3383 - thank you
