### ISSUE TITLE
in store section of App… no vendor store show why ?

### ISSUE THREAD

**Issue by surajk1986** [inspireui/support#3385]
in store section of App… no vendor store show why ?

![store](https://user-images.githubusercontent.com/65123761/82748354-08b72980-9d99-11ea-8fa4-6ea977d856a0.jpg)

**Comment by vumanhsn97** [comment]
@surajk1986 
Please update mstore plugin in your wordpress site and update type wcfm in your config.dart
![image](https://user-images.githubusercontent.com/39208623/82782533-bfdd9e80-9e86-11ea-9b66-f05847f8c198.png)

**Comment by surajk1986** [comment]
Done its working...THANKS
