### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by michaelbrinkworth** [inspireui/support#3387]
Step 1 (require): detail issues and screenshots

Unable to resolve "react-native-screens" from "node_modules/react-navigation-tabs/lib/module/navigators/createBottomTabNavigator.js"

this is literally on the yarn start and expo step.... literally only just purchased and running into issue https://docs.inspireui.com/listapp/quick-setup/

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by michaelbrinkworth** [comment]
dw i fixed it

**Comment by michaelbrinkworth** [comment]
you had to install react-native-screen

**Comment by minhcasi** [comment]
Thank you for quick resolving the issue
