### ISSUE TITLE
FluxStore MultiVendor Login issue with Email ID or User Name

### ISSUE THREAD

**Issue by HarrySmith01** [inspireui/support#3388]
Step 1 (require): detail issues and screenshots

Hello,

I am trying to login a test account with user name or email but I am getting below error:

 "The username or password is incorrect"

However, I have entered the correct password.

![WhatsApp Image 2020-05-24 at 5 22 29 PM](https://user-images.githubusercontent.com/58846483/82753501-be0ecf00-9de3-11ea-8e65-d80c33f42ffb.jpeg)
![WhatsApp Image 2020-05-24 at 5 22 28 PM](https://user-images.githubusercontent.com/58846483/82753502-bf3ffc00-9de3-11ea-8bff-c71603d622ec.jpeg)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by retinq** [comment]
Same issue here

**Comment by HarrySmith01** [comment]
I hope someone is looking into ticket id: 3394 too.

**Comment by HarrySmith01** [comment]
Hey Login issue is now solved.

I was facing the issue because JWT Plugin has some issue so I just reinstalled it and everything worked fine.

However, Please fix Ticket: 3394

**Comment by minhcasi** [comment]
@HarrySmith01 - thank you for the confirm - let us know if you have any further questions 👍
