### ISSUE TITLE
[ListApp]In Booking page chatwithus text button inner functionality is not working

### ISSUE THREAD

**Issue by Pavithran10** [inspireui/support#339]
**Required Info (please complete the following information):**
 Product:[ListApp]
Version:1.6.1
Theme: MyListing

**Describe the bug**
hi, In the booking page below the footer tab "chatwithus"  text button option is there while clicking it's redirect to chat page. After inner functionality are all not working.
1.While entering the message after click send. our message is not displaying in chat page
2.Phone and video chat option icon not working
3.Back arrow icon also not working

**Screenshots**
![chat](https://user-images.githubusercontent.com/46148046/53468014-85683480-3a7e-11e9-8d1e-192161403320.jpg)
![chaterr](https://user-images.githubusercontent.com/46148046/53468030-8f8a3300-3a7e-11e9-945f-df3962cef7f6.png)

**Comment by thangvo9x** [comment]
Hi. The message is not displayed. the problem has been only from config our firebase app.  Please check again. Video Call is a function which is being updated, We'll think about it.

**Comment by Pavithran10** [comment]
thanks, I'll check and update

**Comment by Pavithran10** [comment]
hi, I've a doubt how to remove the chatwithus text button in the booking page. We use that in  future updates so, please give the comment for that for removing purpose

**Comment by thangvo9x** [comment]
You can go to Components/Detail/Footer.js 
find this block and remove it.
<img width="329" alt="block" src="https://user-images.githubusercontent.com/23457178/53548512-35fc3400-3b64-11e9-8fc2-563a2c21ad2a.png">
Thanks
