### ISSUE TITLE
flutter SDK issue

### ISSUE THREAD

**Issue by cdbinfotech** [inspireui/support#3390]
"message": "'body1' is deprecated and shouldn't be used. This is the term used in the 2014 version of material design. The modern term is bodyText2. This feature was deprecated after v1.13.8..\nTry replacing the use of the deprecated member with the replacement.",

**Comment by cdbinfotech** [comment]
total 41 issue and saying same errors

**Comment by minhcasi** [comment]
@cdbinfotech - pls try this script to upgrade your Fluter SDK to fix the issue
```
flutter channel stable
flutter upgrade --force
```

**Comment by minhcasi** [comment]
Please also help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
@cdbinfotech - pls try with the above solution to upgrade the Flutter version - thank you!

**Comment by cdbinfotech** [comment]
hi I have try above solution but same error .. so downloaded again all files from purchase account and done all steps again which is suggested in document also which suggested by you 

below is message 
flutter upgrade --force
Switching to flutter channel 'stable'...
git: Already on 'stable'
git: Your branch is up to date with 'origin/stable'.
Successfully switched to flutter channel 'stable'.
To ensure that you're on the latest build from this channel, run 'flutter upgrade'
Flutter is already up to date on channel stable
Flutter 1.17.1 • channel stable • https://github.com/flutter/flutter.git
Tools • Dart 2.8.2

after this I have run flutter upgrade

Flutter is already up to date on channel stable
Flutter 1.17.1 • channel stable • https://github.com/flutter/flutter.git

then I run flutter doctor to check is there is any issue below is result 

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X __________, locale en-IN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.45.1)
[✓] Connected device (1 available)

• No issues found!

****after all this same 2 error is there below is error**** 

flutter/.pub-cache/hosted/pub.dartlang.org/extended_image-0.7.2/lib/src/gesture/extended_image_slide_page_route.dart:333:9: Error: No named parameter with the name 'animation'.
        animation: animation,

./../flutter/packages/flutter/lib/src/cupertino/route.dart:435:3: Context: Found this candidate, but the arguments don't match.
  CupertinoFullscreenDialogTransition({
  ^^^^^^^^^^^^^^^^^


**also below 41 issues found** 

This was the name used in the material design 2014 specification. The new specification calls this.............

**Comment by minhcasi** [comment]
@cdbinfotech - could you confirm the download Fluxstore Shopify is the latest one? pls download it from http://codecayon.net/downloads - thanks

**Comment by cdbinfotech** [comment]
yes I am confirm that it is latest version cause yesterday I downloaded again from http://codecayon.net/downloads also I have down loaded now but after that again same error please guid

**Comment by minhcasi** [comment]
@cdbinfotech - sorry we got your issue, please help to change the pubspec.yaml file 
from
```
extended_image: 0.7.2
```
to 

```
extended_image: 0.8.0
```

We will update new version in 1-2 days, we sincerely apologize for the delay and hope you’re staying safe.

**Comment by cdbinfotech** [comment]
hi this work thank for your prompt and great support

**Comment by minhcasi** [comment]
We're glad that it help, please give us some feedback/rating to this page https://codecanyon.net/downloads  if the product is helpful for your business, we are working hard to update more awesome and powerful features on next coming version release. Let us know if you have any feedback. Thank you very much 😊
