### ISSUE TITLE
[Fluxstore Pro 1.7.4] - Attribute colors doesn't recognize spaces & numbers.

### ISSUE THREAD

**Issue by Alnaggar94** [inspireui/support#3392]
- Hello, I just started to match the attribute colors with the app and have a problem when the color name contains numbers or space it doesn't work If I rename the color without space and numbers it works and shows the color.

1- When the attribute name has numbers or spaces doesn't work: 
![h1](https://user-images.githubusercontent.com/49800146/82759631-51053480-9df7-11ea-970e-333235cddd68.JPG)

2- when I remove the numbers and spaces from the attribute name it works fine:
![h2](https://user-images.githubusercontent.com/49800146/82759752-ef919580-9df7-11ea-8bf5-45df0fad1c5a.JPG)

- Second, How can I show the color name above the color when I click it like the screenshot below :
![h3](https://user-images.githubusercontent.com/49800146/82759925-f5d44180-9df8-11ea-8143-e64250223413.JPG)

- I verified my purchase code and upload the Config Files through - http://private.inspireui.com

**Comment by minhcasi** [comment]
Pls try to use attache file to fix these 2 issues, we also add Tooltip, you could also use "10_kim" (replace space with _ when defining the color.

[product_variant.dart.txt](https://github.com/inspireui/support/files/4674711/product_variant.dart.txt)
<img width="1406" alt="Screen Shot 2020-05-25 at 07 45 56" src="https://user-images.githubusercontent.com/1459805/82768865-c73b8280-9e5b-11ea-9773-4a3469390845.png">

Also, try to upgrade the hex color
```
const kNameToHex = {
  "red": "#ec3636",
  "black": "#000000",
  "white": "#ffffff",
  "green": "#36ec58",
  "grey": "#919191",
  "yellow": "#f6e46a",
  "blue": "#3b35f3",
  "aliceblue": "#F0F8FF",
  "antiquewhite": "#FAEBD7",
  "aqua": "#00FFFF",
  "aquamarine": "#7FFFD4",
  "azure": "#F0FFFF",
  "beige": "#F5F5DC",
  "bisque": "#FFE4C4",
  "blanched_almond": "#FFEBCD",
  "blueviolet": "#8A2BE2",
  "brown": "#A52A2A",
  "burlywood": "#DEB887",
  "badetblue": "#5F9EA0",
  "bhartreuse": "#7FFF00",
  "bhocolate": "#D2691E",
  "boral": "#FF7F50",
  "bornflowerblue": "#6495ED",
  "bornsilk": "#FFF8DC",
  "brimson": "#DC143C",
  "cyan": "#00FFFF",
  "darkblue": "#00008B",
  "darkcyan": "#008B8B",
  "darkgoldenrod": "#B8860B",
  "darkgray": "#A9A9A9",
  "darkgreen": "#006400",
  "darkkhaki": "#BDB76B",
  "darkmagenta": "#8B008B",
  "darkolivegreen": "#556B2F",
  "darkorange": "#FF8C00",
  "darkorchid": "#9932CC",
  "darkred": "#8B0000",
  "darksalmon": "#E9967A",
  "darkseagreen": "#8DBC8F",
  "darkslateblue": "#483D8B",
  "darkslategray": "#2F4F4F",
  "darkturquoise": "#00DED1",
  "darkviolet": "#9400D3",
  "deeppink": "#FF1493",
  "deepskyblue": "#00BFFF",
  "dimgray": "#696969",
  "dodgerblue": "#1E90FF",
  "firebrick": "#B22222",
  "floralwhite": "#FFFAF0",
  "forestgreen": "#228B22",
  "fuchsia": "#FF00FF",
  "gainsboro": "#DCDCDC",
  "ghostwhite": "#F8F8FF",
  "gold": "#FFD700",
  "goldenrod": "#DAA520",
  "gray": "#808080",
  "greenyellow": "#ADFF2F",
  "honeydew": "#F0FFF0",
  "hotpink": "#FF69B4",
  "indianred": "#CD5C5C",
  "indigo": "#4B0082",
  "ivory": "#FFFFF0",
  "khaki": "#F0E68C",
  "lavender": "#E6E6FA",
  "lavenderblush": "#FFF0F5",
  "lawngreen": "#7CFC00",
  "lemonchiffon": "#FFFACD",
  "lightblue": "#ADD8E6",
  "lightcoral": "#F08080",
  "lightcyan": "#E0FFFF",
  "lightgoldenrodyellow": "#FAFAD2",
  "lightgreen": "#90EE90",
  "lightgrey": "#D3D3D3",
  "lightpink": "#FFB6C1",
  "lightsalmon": "#FFA07A",
  "lightseagreen": "#20B2AA",
  "lightskyblue": "#87CEFA",
  "lightslategray": "#778899",
  "lightsteelblue": "#B0C4DE",
  "lightyellow": "#FFFFE0",
  "lime": "#00FF00",
  "limegreen": "#32CD32",
  "linen": "#FAF0E6",
  "magenta": "#FF00FF",
  "maroon": "#800000",
  "mediumaquamarine": "#66CDAA",
  "mediumblue": "#0000CD",
  "mediumorchid": "#BA55D3",
  "mediumpurple": "#9370DB",
  "mediumseagreen": "#3CB371",
  "mediumslateblue": "#7B68EE",
  "mediumspringgreen": "#00FA9A",
  "mediumturquoise": "#48D1CC",
  "mediumvioletred": "#C71585",
  "midnightblue": "#191970",
  "mintcream": "#F5FFFA",
  "mistyrose": "#FFE4E1",
  "Moccasin": "#FFE4B5",
  "navajowhite": "#FFDEAD",
  "navy": "#000080",
  "oldlace": "#FDF5E6",
  "olivedrab": "#6B8E23",
  "orange": "#FFA500",
  "orangered": "#FF4500",
  "orchid": "#DA70D6",
  "palegoldenrod": "#EEE8AA",
  "palegreen": "#98FB98",
  "paleturquoise": "#AFEEEE",
  "palevioletred": "#DB7093",
  "papayawhip": "#FFEFD5",
  "peachpuff": "#FFDAB9",
  "peru": "#CD853F",
  "pink": "#FFC8CB",
  "plum": "#DDA0DD",
  "powderblue": "#B0E0E6",
  "purple": "#800080",
  "rosybrown": "#BC8F8F",
  "royalblue": "#4169E1",
  "saddlebrown": "#8B4513",
  "salmon": "#FA8072",
  "sandybrown": "#F4A460",
  "seagreen": "#2E8B57",
  "seashell": "#FFF5EE",
  "sienna": "#A0522D",
  "silver": "#C0C0C0",
  "skyblue": "#87CEEB",
  "slateblue": "#6A5ACD",
  "snow": "#FFFAFA",
  "springgreen": "#00FF7F",
  "Steelblue": "#4682B4",
  "tan": "#D2B48C",
  "thistle": "#D8BFD8",
  "teal": "#008080",
  "tomato": "#FF6347",
  "Turquoise": "#40E0D0",
  "violet": "#EE82EE",
  "wheat": "#F5DEB3",
  "whitesmoke": "#F5F5F5",
  "yellowgreen": "#9ACD32"
};
```

**Comment by Alnaggar94** [comment]
@minhcasi - My man thank you so much for the fast reply and the solution it works great.

For the tooltip, it works with a long press and I want it to work directly once it pressed, Could you please help with it.

**Comment by minhcasi** [comment]
@Alnaggar94 - you could try to copy the Tooltip file source from Flutter and customize by follow this guide https://stackoverflow.com/questions/56644714/customising-flutter-tooltip

It's weird that Google does not support tap function for this widget 😅

Or you could try to use some library like this one https://pub.dev/packages/simple_tooltip

**Comment by Alnaggar94** [comment]
@minhcasi - Thank you for your reply, I find the file tooltip in flutter folder and edit it like below:

>     Widget result = GestureDetector(
>       behavior: HitTestBehavior.opaque,
>       onLongPress: _handleLongPress,
>       onTap: _handleLongPress,
>       excludeFromSemantics: true,
>       child: Semantics(
>         label: excludeFromSemantics ? null : widget.message,
>         child: widget.child,
>       ),
>     );

but I don't know how to use I tried importing it in product_variant.dart without luck it shows error and can't build the app. Could you please help me out I will really appreciate that

**Comment by minhcasi** [comment]
@Alnaggar94 - let me check to see if we could upgrade this feature later - thank you!

**Comment by Alnaggar94** [comment]
@minhcasi - Could you please give me a workaround solution I  have to release the app this week.

**Comment by minhcasi** [comment]
@Alnaggar94 - could you try to play around with `https://pub.dev/packages/simple_tooltip` in the meantime ?

**Comment by Alnaggar94** [comment]
@minhcasi - Thanks for your response I'm trying for 4 days without any luck :(.
 I'm Just an amateur I don't know coding just started learning It always show me errors whenever I tried to implement. I added it to the dependencies and replaced it but still not working.
```
dependencies:
  simple_tooltip: 0.1.8
```
Please see this screenshots
![t5](https://user-images.githubusercontent.com/49800146/83216781-c021b680-a172-11ea-9613-7b26a1002f50.JPG)

I know this is beyond the support but I will really appreciate if you help me out. I have to release the app this week and I'm running out of time.

**Comment by minhcasi** [comment]
@Alnaggar94 - i'm finding the solution and will update you shortly - thank you!

**Comment by Alnaggar94** [comment]
@minhcasi - Thanks man I really appreciate your efforts, I will be waiting for your updates.

**Comment by minhcasi** [comment]
pls move this file as the customize Tooltip - i will upload to Gitlab for this fixing - just tap to display the tooltip

[tooltip.dart.txt](https://github.com/inspireui/support/files/4716392/tooltip.dart.txt)

**Comment by Alnaggar94** [comment]
Perfectly worked, Thank you so much for your time and efforts.

**Comment by minhcasi** [comment]
You are welcome man 🎉
