### ISSUE TITLE
FluxStore MultiVendor Login Issue with Mobile Number & Google Account

### ISSUE THREAD

**Issue by HarrySmith01** [inspireui/support#3393]
Step 1 (require): detail issues and screenshots

I am unable to login through **Mobile Number And Google Account**.

Getting below error.

I am getting same Below Error for Google Account Signin too.

![WhatsApp Image 2020-05-24 at 10 54 23 PM](https://user-images.githubusercontent.com/58846483/82760576-f0372580-9e11-11ea-82ec-6dc126c7cfa0.jpeg)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

**Required Information already shared with Ticket ID: 3388**

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@HarrySmith01 - please try to activate the License from mstore-api (Wordpress side to fix this issue which is caused by the lock Rest API)

Please also help us to raise your all feedbacks to the same ticket #3388 - that help the technical support focus to resolve it better 😊

**Comment by HarrySmith01** [comment]
Hey, It worked.

I was not aware that I need to activate license from woocommerce backend.
