### ISSUE TITLE
FluxStore MultiVendor Signup Issue

### ISSUE THREAD

**Issue by HarrySmith01** [inspireui/support#3394]
Step 1 (require): detail issues and screenshots

I am trying to signup in app and I have already accepted the privacy and policy but still I get error "Please Agree our Terms" When I clicking on Create An Account.

![WhatsApp Image 2020-05-24 at 11 04 38 PM](https://user-images.githubusercontent.com/58846483/82760710-127d7300-9e13-11ea-977a-3c99f6ef9a60.jpeg)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

**Required Information already shared with Ticket ID: 3388**

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by minhcasi** [comment]
Please also help us to raise your all feedbacks to the same ticket #3388 - that help the technical support focus to resolve it better 😊

**Comment by HarrySmith01** [comment]
Hey, It worked.

I was not aware that I need to activate license from woocommerce backend.
