### ISSUE TITLE
Getting Shipping Method Issue

### ISSUE THREAD

**Issue by umargigani** [inspireui/support#3396]
Everything is Working Fine Just Getting Shipping Issue 
And i really loved the UI and Docs provided 
Thank you
I am Using opencart 3 
![24F04AC9-EC0D-4C45-9183-BC356EC5B083](https://user-images.githubusercontent.com/22342007/82773342-6746db00-9e5f-11ea-9ce3-bf9312e23f24.jpeg)

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by umargigani** [comment]
done
if its possible to make checkout fully webview
eg customer can login
add products to cart
and then review products and proceed to checkout
where a webview opens and our opencart method happnes and after confirm order it will be closed and app shows order placed
if this can be implemented for opencart only then this will be very easy fix
as mostly opencart users like us have tons of plugins and 99% of them uses custom theme
we have more then 55 plugins and custom theme ive tested the app 85% works with my store 
just check out page i a big headache 

if this can be possible in future update i am ready to wait for it i dont want refund i want to use this app i really loved the ui 

so hope you can help

**Comment by minhcasi** [comment]
@umargigani - could you try to enable this option to enable the full Webview for checkout screen - thank you!

<img width="880" alt="Screen Shot 2020-05-26 at 09 16 45" src="https://user-images.githubusercontent.com/1459805/82854099-a0e81680-9f31-11ea-9840-ae8149732f08.png">

**Comment by umargigani** [comment]
ive done it still same issue no shipping method
after disable address, shipping
and keeping only review there are no payment methods fetched 

![bug-1](https://user-images.githubusercontent.com/22342007/82855206-47c7b500-9f28-11ea-95e1-fe558b42d552.png)
![bug-2](https://user-images.githubusercontent.com/22342007/82855211-4bf3d280-9f28-11ea-84ca-943d50c542aa.png)

**Comment by umargigani** [comment]
so what i am asking 
after add to cart customer review the product and
after hitting continue to payment webview should load and this page should load
https://ezpzsolutions.in/index.php?route=checkout/checkout

so there is some address issue also so i don't have to mange that if address is not available customer can enter address in webview only

![checkout1](https://user-images.githubusercontent.com/22342007/82855780-ddb00f80-9f29-11ea-8ec2-82818a49e476.png)

**Comment by minhcasi** [comment]
@minhtruong315 - please help to investigate this issue as it should open the Webview as the first stage when we enable the OnePageCheckout ?

**Comment by umargigani** [comment]
yes after review is done customer hit continue to payment and webview should load

**Comment by Vetriselvan-NA** [comment]
OnePageCheckout is not working for me too..

**Comment by minhtruong315** [comment]
Hi @umargigani what is the Fluxstore you're using?

**Comment by minhtruong315** [comment]
Hi @umargigani please try this solution
- replace fromOpencartJson function in models/shipping_method.dart
```
ShippingMethod.fromOpencartJson(Map<String, dynamic> parsedJson) {
    Map<String, dynamic> quote = parsedJson["quote"];
    if (quote["code"] == null &&
        quote.values.isNotEmpty &&
        quote.values.toList()[0] is Map) {
      quote = quote.values.toList()[0];
    }
    String title =
        quote["title"] != null ? quote["title"] : parsedJson["title"];
    id = quote["code"];
    this.title = title ?? id;
    description = title ?? "";
    cost = quote["cost"] != null ? double.parse("${quote["cost"]}") : 0.0;
  }
```
- replace getShippingMethods function in services/opencart.dart
```
@override
  Future<List<ShippingMethod>> getShippingMethods(
      {Address address, String token, String checkoutId}) async {
    try {
      List<ShippingMethod> list = [];
      var response = await http.post(
          "$domain/index.php?route=extension/mstore/shipping_address/save",
          body: convert.jsonEncode(address.toOpencartJson()),
          headers: {"content-type": "application/json", "cookie": cookie});
      final body = convert.jsonDecode(response.body);
      if (response.statusCode == 200 && body["success"] == 1) {
        var res = await http.get(
            "$domain/index.php?route=extension/mstore/shipping_method",
            headers: {"cookie": cookie});
        final body = convert.jsonDecode(res.body);
        if (res.statusCode == 200 && body["data"]["error_warning"] == "") {
          Map<String, dynamic> data = body["data"]["shipping_methods"];
          for (var item in data.values.toList()) {
            if (item["quote"] is Map) {
              list.add(ShippingMethod.fromOpencartJson(item));
            } else if (item["quote"] is List) {
              for (var quote in item["quote"]) {
                item["quote"] = quote;
                list.add(ShippingMethod.fromOpencartJson(item));
              }
            }
          }
          return list;
        } else {
          throw Exception(body["data"]["error_warning"]);
        }
      } else {
        throw Exception(body["error"][0]);
      }
    } catch (e) {
      rethrow;
    }
  }
```

**Comment by umargigani** [comment]
> Hi @umargigani what is the Fluxstore you're using?

the latest one with opencart

**Comment by premod** [comment]
i have tried this, shipping method solved, but after that going to payment, i have selected the payumoney (which is my payment gateway), its going to mobile view of the app's website

**Comment by premod** [comment]
@umargigani, do u have the tax calculation?. in my case tax is not showing. what should i do for that?

**Comment by umargigani** [comment]
> @umargigani, do u have the tax calculation?. in my case tax is not showing. what should i do for that?

no we are not using tax on product we make invoice

**Comment by umargigani** [comment]
@minhtruong315 perfect this solved the issue
i have one question we use images in payment method
![11111111111111](https://user-images.githubusercontent.com/22342007/82972484-c852e800-9ff2-11ea-920f-02ace0a043f3.png)

![22222222222](https://user-images.githubusercontent.com/22342007/82972600-1536be80-9ff3-11ea-80b2-ea0ef9cd0b7b.png)


so is it possibe to fetch the images?

**Comment by premod** [comment]
@umargigani is it going to the payment gateway after place order?

**Comment by umargigani** [comment]
yes payment methods are fetching now and after placing order it goes to my website web-view checkout but it wont select shipping any payment user to to select it again and place order

**Comment by umargigani** [comment]
> @minhtruong315 perfect this solved the issue
> i have one question we use images in payment method
> ![11111111111111](https://user-images.githubusercontent.com/22342007/82972484-c852e800-9ff2-11ea-920f-02ace0a043f3.png)
> 
> ![22222222222](https://user-images.githubusercontent.com/22342007/82972600-1536be80-9ff3-11ea-80b2-ea0ef9cd0b7b.png)
> 
> so is it possibe to fetch the images?

lib fixed it in thank you

**Comment by umargigani** [comment]
and one more question 
![33333333333333](https://user-images.githubusercontent.com/22342007/82974504-c7708500-9ff7-11ea-9472-dba154278277.png)

banner images are there so for changing it i always have to edit source code?
after publishing to play store we weekly update the banners 
so i have this query
thank you

**Comment by premod** [comment]
@umargigani mine is going to shoppingcart page, with 404 error. any idea to solve this

**Comment by umargigani** [comment]
![contry-issue](https://user-images.githubusercontent.com/22342007/83141098-bc5b4900-a10c-11ea-8664-6fbd6e5c07e3.png)
Why it is not saving county and state when adding address from checkout

and it is not fetching already saved address
why so?

**Comment by minhtruong315** [comment]
> and one more question
> ![33333333333333](https://user-images.githubusercontent.com/22342007/82974504-c7708500-9ff7-11ea-9472-dba154278277.png)
> 
> banner images are there so for changing it i always have to edit source code?
> after publishing to play store we weekly update the banners
> so i have this query
> thank you

Hi @umargigani you can save the config_en.json  file in server and update kAppConfig constants. it will load your config remotely. so you can change config without rebuild the app on store.
<img width="1253" alt="Screen Shot 2020-05-29 at 6 55 39 AM" src="https://user-images.githubusercontent.com/10402500/83205814-c2d3da00-a179-11ea-8af6-ad658bb2a90c.png">

**Comment by minhtruong315** [comment]
> ![contry-issue](https://user-images.githubusercontent.com/22342007/83141098-bc5b4900-a10c-11ea-8664-6fbd6e5c07e3.png)
> Why it is not saving county and state when adding address from checkout
> 
> and it is not fetching already saved address
> why so?
> 
> ![stateeee](https://user-images.githubusercontent.com/22342007/83161496-23392c00-a126-11ea-8305-15b61e239f14.png)
> 
> any why it is saving
> and state as Kerewan???????
> 
> and shows order id 0 when order is placed

hi @umargigani for address, Fluxstore doesn't support to save or fetch address from server now. We will research and add the feature on next release.
for zero order, I think you're using old MStore extension. can u give me your email? I'll send the latest MStore extension.
Thanks

**Comment by umargigani** [comment]
umargigani@gmail.com

> > ![contry-issue](https://user-images.githubusercontent.com/22342007/83141098-bc5b4900-a10c-11ea-8664-6fbd6e5c07e3.png)
> > Why it is not saving county and state when adding address from checkout
> > and it is not fetching already saved address
> > why so?
> > ![stateeee](https://user-images.githubusercontent.com/22342007/83161496-23392c00-a126-11ea-8305-15b61e239f14.png)
> > any why it is saving
> > and state as Kerewan???????
> > and shows order id 0 when order is placed
> 
> hi @umargigani for address, Fluxstore doesn't support to save or fetch address from server now. We will research and add the feature on next release.
> for zero order, I think you're using old MStore extension. can u give me your email? I'll send the latest MStore extension.
> Thanks

**Comment by umargigani** [comment]
> i have tried this, shipping method solved, but after that going to payment, i have selected the payumoney (which is my payment gateway), its going to mobile view of the app's website

yes the app is not purly native its kind of hybrid for payment and i personally prefer that as i have some fees liked with gateway and stuff and app doesn't fetch that, buts that's totally fine for me  its working better then other developer apps i tried and UI is also good so really loving this app

**Comment by umargigani** [comment]
![sign up](https://user-images.githubusercontent.com/22342007/83332127-02541080-a2b7-11ea-910f-24d4e74634a6.png)
is it possible to change sign up for in app to webview??

i have email and phone verification setup so i prefer customer sign up directly on website using webview

thank you

**Comment by minhtruong315** [comment]
Hi @umargigani I sent you mstore extension via email. Please install it on your website to fix zero order number.
 Fluxstore doesn't support webview for Sign Up screen. You can try to customize it.
Thanks

**Comment by umargigani** [comment]
https://drive.google.com/open?id=1vchC-nvHBx4LFIvcokZ7PuWDJ98upAEt

i am facing search issue 
when search shows in list the keyboard hides automatically

but when search shows in grid view it acts normal 
so i want it to show in grid view above link have both videos

**Comment by minhtruong315** [comment]
let me check this issue @umargigani

**Comment by umargigani** [comment]
> let me check this issue @umargigani

Okie waiting for your reply

**Comment by minhtruong315** [comment]
Hi @umargigani remove ```FocusScope.of(mainContext)..unfocus();``` to fix this issue.
<img width="1096" alt="Screen Shot 2020-06-05 at 10 41 07 AM" src="https://user-images.githubusercontent.com/10402500/83834717-34330000-a719-11ea-9f1c-5f5cc455b043.png">

**Comment by umargigani** [comment]
> > ![contry-issue](https://user-images.githubusercontent.com/22342007/83141098-bc5b4900-a10c-11ea-8664-6fbd6e5c07e3.png)
> > Why it is not saving county and state when adding address from checkout
> > and it is not fetching already saved address
> > why so?
> > ![stateeee](https://user-images.githubusercontent.com/22342007/83161496-23392c00-a126-11ea-8305-15b61e239f14.png)
> > any why it is saving
> > and state as Kerewan???????
> > and shows order id 0 when order is placed
> 
> hi @umargigani for address, Fluxstore doesn't support to save or fetch address from server now. We will research and add the feature on next release.
> for zero order, I think you're using old MStore extension. can u give me your email? I'll send the latest MStore extension.
> Thanks

after installing new extension the order still shows 0
