### ISSUE TITLE
FLUXNEWS - Design Header

### ISSUE THREAD

**Issue by nathajjar** [inspireui/support#3398]
Hi,

I've a stupid question...but i can't align center the Title in the home screen

Where should I go to change this information ?

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

Solution: pls try to wrap with the `Center(child: xxx)` widget

**Comment by nathajjar** [comment]
i've just sent the informations

I'm sorry but i don't see where i've put the wrap-widget....

**Comment by minhcasi** [comment]
@nathajjar - could you help to share which title the screen you need to align the UI? Please as the specific screenshot  - thank you!

**Comment by nathajjar** [comment]
OK....here (homepage after the splashscreen and sliders)

Cordialement

Hajjar Nathanaël
Gérant
NHSolutions
m:	+32497071290
w:	nhsolutions.be  e: admin@nhsolutions.be

Information confidentielle : Le présent message, ainsi que tout fichier qui y est joint, est envoyé à l'intention exclusive de son ou de ses destinataires ; il est de nature confidentielle et peut constituer une information privilégiée. Nous avertissons toute personne autre que le destinataire prévu que tout examen, réacheminement, impression, copie, distribution ou toute autre utilisation de ce message et tout document joint est strictement interdit. Si vous n'êtes pas le destinataire prévu, veuillez en aviser immédiatement l'expéditeur par retour de courriel et supprimer ce message et tout document joint de votre système. Merci!

**Comment by dttrung26** [comment]
Hi @nathajjar , 
please replace my attached file into your /lib/widgets/blog/header. Hope this helps.

[support_ticket#3398.zip](https://github.com/inspireui/support/files/4686376/support_ticket.3398.zip)

Have a nice day!
