### ISSUE TITLE
Filtering with Arabic attribute not working

### ISSUE THREAD

**Issue by ilyesrd** [inspireui/support#3399]
I updated the project to the latest version as well as Flutter ... but the problem still there! ... I noticed that when I try to filter with an English attribute, it works well, but when I use the Arabic attribute, it doesn't work ... my application will use Arabic every where, I don't need english and i'll not use it... so that's why i did not install multilanguage plugin.. is it required to fix the problem?
<img width="512" alt="Capture d’écran 2020-05-23 à 11 55 23 AM" src="https://user-images.githubusercontent.com/25514080/82804085-8a7e8400-9e79-11ea-81ab-8d79d07306c4.png">

**Comment by ilyesrd** [comment]
@minhcasi @trunghieuvn 
Hello! ... Can anyone reply? please?

**Comment by minhcasi** [comment]
We wanted to thank you for your patience during this busy time. We currently have reduced staff and a significantly higher volume of inquiries. We’re working as hard as we can to get to your request as soon as possible.

We sincerely apologize for the delay and hope you’re staying safe.

@trunghieuvn

**Comment by trunghieuvn** [comment]
> I updated the project to the latest version as well as Flutter ... but the problem still there! ... I noticed that when I try to filter with an English attribute, it works well, but when I use the Arabic attribute, it doesn't work ... my application will use Arabic every where, I don't need english and i'll not use it... so that's why i did not install multilanguage plugin.. is it required to fix the problem?
> <img alt="Capture d’écran 2020-05-23 à 11 55 23 AM" width="512" src="https://user-images.githubusercontent.com/25514080/82804085-8a7e8400-9e79-11ea-81ab-8d79d07306c4.png">

Hi @ilyesrd 
I check your api get Attribute. The results returned are "Color" and "المقاس". "المقاس" doesn't exist in "kProductVariantLanguage" so it displays the name. Please check your API again.

![image](https://user-images.githubusercontent.com/19247680/83220768-1a843c80-a19e-11ea-9656-cd45ce03b18b.png)

**Comment by ilyesrd** [comment]
@trunghieuvn 
<img width="709" alt="Capture d’écran 2020-05-29 à 8 24 42 PM" src="https://user-images.githubusercontent.com/25514080/83304312-8befd980-a1f6-11ea-83cc-419b0d35eb5a.png">

I did what you suggest but it doesn't work! ... I also found that the attribute in the product screen did not work. please check the attachement. 
https://drive.google.com/file/d/1WdxXuS9AsN9MQBXbC41lvDsmYGvmg01I/view?usp=sharing

**Comment by trunghieuvn** [comment]
> @trunghieuvn
> <img alt="Capture d’écran 2020-05-29 à 8 24 42 PM" width="709" src="https://user-images.githubusercontent.com/25514080/83304312-8befd980-a1f6-11ea-83cc-419b0d35eb5a.png">
> 
> I did what you suggest but it doesn't work! ... I also found that the attribute in the product screen did not work. please check the attachement.
> https://drive.google.com/file/d/1WdxXuS9AsN9MQBXbC41lvDsmYGvmg01I/view?usp=sharing
> 
> > **[Meet Google Drive – One place for all your files](https://drive.google.com/file/d/1WdxXuS9AsN9MQBXbC41lvDsmYGvmg01I/view?usp=sharing)**Google Drive is a free way to keep your files backed up and easy to reach from any phone, tablet, or computer. Start with 15GB of Google storage – free.

Please check your API and make sure the return value exists in the file `lib/common/config/products.dart`

![image](https://user-images.githubusercontent.com/19247680/83318799-5b458980-a262-11ea-84a0-9d39d56e3858.png)

![image](https://user-images.githubusercontent.com/19247680/83318794-49fc7d00-a262-11ea-8a14-37f9bfb630a8.png)
