### ISSUE TITLE
For archive,  error: bitcode bundle could not be generated

### ISSUE THREAD

**Issue by angelohu** [inspireui/support#3400]
ld: bitcode bundle could not be generated because '/Users/userxxxx/Desktop/FluxStore 1.7.4/source/ios/Flutter/Flutter.framework/Flutter' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file '/Users/wenlonghu/Desktop/FluxStore 1.7.4/source/ios/Flutter/Flutter.framework/Flutter' for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as it could not be verified, please create the new one when you got enough purchased info - thank you!

**Comment by minhcasi** [comment]
#3014
