### ISSUE TITLE
Unable to register new users - Mstore Pro 

### ISSUE THREAD

**Issue by shikhardb** [inspireui/support#3401]
#### Step 1 (require): detail issues and screenshots

I have 2 issues while registering a new user.

1. While creating a new user, it says _"Sorry you are not allowed to do that"_

![image](https://user-images.githubusercontent.com/4832195/82823672-a0199b00-9ec5-11ea-8520-4680d1691d35.png)

2. Also, the same thing is happening with Facebook sign up/login. It returns to the login page after trying to sign in with Facebook.

#### Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)
_Done_

**Comment by minhcasi** [comment]
@shikhardb - pls try to go to mstore-api plugin and verify purchase code to unlock the app features - thank you!

<img width="1117" alt="Screen Shot 2020-05-26 at 08 35 00" src="https://user-images.githubusercontent.com/1459805/82852037-dd187880-9f2b-11ea-9498-8c2c5b79d10f.png">
