### ISSUE TITLE
[FluxStore WooCommerce] REST API - Not Working 

### ISSUE THREAD

**Issue by swspro** [inspireui/support#3402]
Step 1 (require): detail issues and screenshots

Hi ,

I have downloaded the Latest Version of the **FluxStore Woocommerce App** from my Envato Account, and have made the setup for the Fluxstore on the domain www.fbfashions.co

Activated the REST API and Installed the M-Store Api and other two plugins 

You can even Test the API at http://www.fbfashions.co/wp-json/wc/v3

But the Api is not fetching the data from the site..

You can refer the screenshot of the Config File and FB Fashion App

Even the Categories ID's are well listed but still not showing 

Sam

![categories ids](https://user-images.githubusercontent.com/15525566/82824440-f509e100-9ec6-11ea-9e1c-388eae72787b.PNG)

![API Configuration](https://user-images.githubusercontent.com/15525566/82823180-bbd07180-9ec4-11ea-88c6-c3216b86ad7c.PNG)
![WhatsApp Image 2020-05-25 at 20 08 18](https://user-images.githubusercontent.com/15525566/82823186-be32cb80-9ec4-11ea-8daf-35c012cea514.jpeg)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@swspro - could you try to remove the '/" at the end of the `url` setting from the config.dart file to see if can be fixed - thank you!

**Comment by swspro** [comment]
Sure .. doing it right now

**Comment by swspro** [comment]
@minhcasi thanks for the quick response. I tried but it work ..

Please suggest

**Comment by philipvu30** [comment]
Hi,

It seems your consumer key and consumer secret are incorrect. Please replace them with the new ones. Thanks.

**Comment by swspro** [comment]
Hi @philipvu30 

Hope you are doing well.

As per your suggestion I have created a NEW API and have updated in the Config File but still Data is not Fetched

I think there is an issue with New Updated Version 

Sending you the API Screen Info and Config File Screenshot 

![Fb Fashion Api](https://user-images.githubusercontent.com/15525566/82861492-764e8b80-9f3a-11ea-8b8b-97d5100f122d.PNG)
![Updated Api](https://user-images.githubusercontent.com/15525566/82861497-78184f00-9f3a-11ea-9837-3714a0138a0b.PNG)

**Comment by philipvu30** [comment]
Hi,

Please send them directly to my email: toan@inspireui.com.

Thank you.

**Comment by swspro** [comment]
Sending you the website login and common & Config folder

**Comment by swspro** [comment]
Just sent to your email ID from samareshbisoi@gmail.com with Subject Line : "Fluxstore REST API - Not Working #3402"

Sam

**Comment by philipvu30** [comment]
Hi,

I have tried many solutions but none of them worked. 
So my only suggestion right now is to enable SSL on your site.

**Comment by swspro** [comment]
Ok. But just wondering when I give the default API key which comes with the download  and the URL your domain which is http it retrieve the data from your site 

Sam

**Comment by philipvu30** [comment]
Hi,

I think you must be mistaking our demo URL with something else. Our demo URL for FluxStore always is https://mstore.io/

**Comment by swspro** [comment]
Please refer to this
![inspireui](https://user-images.githubusercontent.com/15525566/82884597-8cbc0d80-9f61-11ea-9298-c07683c533dc.PNG)

![WhatsApp Image 2020-05-26 at 14 56 11](https://user-images.githubusercontent.com/15525566/82884569-8594ff80-9f61-11ea-9fa4-814ab5e9ab46.jpeg)
![WhatsApp Image 2020-05-26 at 14 56 12](https://user-images.githubusercontent.com/15525566/82884575-875ec300-9f61-11ea-9185-2a3d4d66dadf.jpeg)

**Comment by swspro** [comment]
OK. Lets me then try with the HTTPS w

**Comment by hssinaman** [comment]
Hi, 
we have the same issue can you help please ?

**Comment by philipvu30** [comment]
Hi @hssinaman 
Have you enabled ssl on your site?

**Comment by hssinaman** [comment]
Yes we enabled the SSL and we did also all instructions that you have provided above but the problem no't resolved..
awaiting for your quick help asap please ..

**Comment by hssinaman** [comment]
Can you help please ?

**Comment by swspro** [comment]
Hi @philipvu30 

Good morning

We have installed the SSL certificate on the domain www.fbfashion.co

Can you please check from your side as I have shared the login details of the site to you ?

You have the COMMON & the CONFIG folders which I had shared with you.

Sam

**Comment by philipvu30** [comment]
Hi,

I see it is working now. So what is your problem?

![image](https://user-images.githubusercontent.com/54442328/83229152-ab184800-a1b1-11ea-9221-e3d7eb3d1804.png)

![image](https://user-images.githubusercontent.com/54442328/83229208-be2b1800-a1b1-11ea-984c-93e186ff532a.png)

Have you changed your URL in config.dart to https? Also, remember to remove "/feed" for the blog URL so the app can get the blog data.

**Comment by hssinaman** [comment]
we are still waiting for your help.. 
the app is stopped why this issue is taken much time and we can't find any solution to move ahead !!!

**Comment by philipvu30** [comment]
Hi @hssinaman,

Are you and swspro the same person?

**Comment by swspro** [comment]
Hi @philipvu30 

I will check and message you.

@hssinaman  is not from our Team

Sam

**Comment by hssinaman** [comment]
Hi @philipvu30 
No sir, im getting the same issue and i can't get any reply till now

**Comment by philipvu30** [comment]
Hi @hssinaman ,

It seems fine to me. So what exactly is your problem you are facing?

![image](https://user-images.githubusercontent.com/54442328/83250972-158db000-a1d3-11ea-8691-c102c46f8bd9.png)

![image](https://user-images.githubusercontent.com/54442328/83251746-47534680-a1d4-11ea-95a2-1ee68e336f52.png)

In this file lib/common/config/general.dart, there is an attribute called "hideOutOfStock", please set it to false.

**Comment by swspro** [comment]
Thanks @philipvu30 ! It worked when I created the NEW API .

Can you please Assist how to Add Color and Size Option in the ITEMS ? 

Please refer to the Screenshot of an Demo ITEM where the COLOR and SIZE option is AVAILABLE . 

![WhatsApp Image 2020-05-28 at 22 28 16](https://user-images.githubusercontent.com/15525566/83254094-cc862d80-a1cb-11ea-8740-db3619a711a7.jpeg)

**Comment by hssinaman** [comment]
Thank you @philipvu30   its working now by setting up attribute called "hideOutOfStock" to false

**Comment by swspro** [comment]
Good Morning @philipvu30 

Product variant issue is also fixed.

So I am closing this ticket.

Thanks again for Very Fast Support . Just Love it :)
