### ISSUE TITLE
Duplicated Categories + Error Blog not load

### ISSUE THREAD

**Issue by informaticajovani** [inspireui/support#3403]
As you can see in the screenshots, I have the following problems:

- Error when capturing the news of the blog, an exception occurs in the information processing.

- Error listing categories. IF the user exits the application and re-enters, the list is duplicated. IF it does a third time, triples. Surely it is a state problem, but I can't find it.

![thumbnail](https://user-images.githubusercontent.com/64914565/82825725-04c7fc00-9eac-11ea-8dfb-c941cbd874d2.png)

![thumbnail (1)](https://user-images.githubusercontent.com/64914565/82825736-085b8300-9eac-11ea-853b-40a0a4192aba.png)

thanks for your help.

**Comment by dttrung26** [comment]
Hi @informaticajovani , 
please attach your common folder here because you left an empty one in our Google Docs Form. 
Thanks for your cooperation.

**Comment by informaticajovani** [comment]
Good afternoon. I just sent them the files they told me. The incidence of the blog is already solved, I had misspelled the url to the blog.

It only remains to fix the duplicate categories

Thanks and good work to date

**Comment by dttrung26** [comment]
Hi @informaticajovani , could you please send me your whole files via trung@inspireui.com including record video steps to encounter this issue? So far so good, I don't see any error on your config folder.

**Comment by informaticajovani** [comment]
Have you recibed my mail?
--
Informatica FerreteriaJovani.com miércoles, 27 mayo 2020, 08:41a. m. +02:00 de Doan Tan Trung  notifications@github.com :

**Comment by informaticajovani** [comment]
the failure just by changing the config so that it points to my site, but ok, I send you the complete source
thank
--
Informatica FerreteriaJovani.com martes, 02 junio 2020, 04:33a. m. +02:00 de Doan Tan Trung  notifications@github.com :

**Comment by dttrung26** [comment]
Hi @informaticajovani , 
First of all, so sorry for the late response. 
I know it's weird and annoying, but could you double-check category settings on your site (including duplicate categories or any external plugins that you installed accidentally) because according to our demo and customers' site tests, everything still runs smoothly. 
Let me know your situation then,
very best!

**Comment by dttrung26** [comment]
Close due to no response from customer. Feel free to re-open this ticket if you're still facing this issue. 
Best!
