### ISSUE TITLE
products image not showing all the images show only one Multi Vendor WooCommerce

### ISSUE THREAD

**Issue by rabahaldoori** [inspireui/support#3404]
products image not showing all the images show only one Multi Vendor WooCommerce
if i add products manual its will show , when its URL Images  its show only one Image for Each products 

<img width="1267" alt="Screen Shot 2020-05-25 at 2 46 03 AM" src="https://user-images.githubusercontent.com/31085177/82838798-eacdef80-9e92-11ea-985b-0b762b7230a6.png">

<img width="1381" alt="Screen Shot 2020-05-25 at 2 18 55 PM" src="https://user-images.githubusercontent.com/31085177/82838809-f5888480-9e92-11ea-99d8-f2d2a55b8a78.png">

Thank you

**Comment by kvt0012** [comment]
Dear sir, can you take a picture to describe more about your idea? Thank you

**Comment by rabahaldoori** [comment]
hi @kvt0012 i explain it on the image 
thank you 

<img width="1381" alt="Screen Shot 2020-05-25 at 2 18 55 PM" src="https://user-images.githubusercontent.com/31085177/82859514-918aae00-9edc-11ea-9c05-c828b9c24b53.png">

<img width="441" alt="Screen Shot 2020-05-25 at 2 25 56 PM" src="https://user-images.githubusercontent.com/31085177/82859520-95b6cb80-9edc-11ea-8451-4094bdd10c54.png">

**Comment by kvt0012** [comment]
Do you use any other extension for this feature ? Thank you

**Comment by rabahaldoori** [comment]
@kvt0012 i have my suppler and got the image from the API all URL

**Comment by rabahaldoori** [comment]
@kvt0012 This is the future my supplier use 

https://wordpress.org/plugins/featured-image-by-url/

**Comment by kvt0012** [comment]
Sorry sir, it is out of our support scope. If you use the feature is default on your api as woocomerce api, we can support it, but if you use other plugin, it is out of our support scope, thank you.

**Comment by rabahaldoori** [comment]
@kvt0012 Sir i don't think so o have that issue i make a video you can see what i mean , when i put URL Image app cannot detected the image


https://www.youtube.com/watch?v=Lq-VbE3jZZQ&feature=youtu.be



Thank you

**Comment by rabahaldoori** [comment]
@kvt0012 any update?

**Comment by kvt0012** [comment]
https://docs.inspireui.com/ 
We have a docs here, you can follow it to check whether your plugin is supported or not. Btw, I will ask about your case and give you response, thank you

**Comment by rabahaldoori** [comment]
@kvt0012 did you check the video is not about the plugin ! Its any Url image its not showing!!! You can trying to put any product with and image url you will see it and I already followed instructions

**Comment by kvt0012** [comment]
Ok sir, I asked my boss and thanks for your suggestion, we will integrate it to our app soon, thank you.

**Comment by rabahaldoori** [comment]
@kvt0012 ok thank you if you cloud let me know soon release

**Comment by rabahaldoori** [comment]
@kvt0012 

First issue payment when i click on the Review not going through .

<img width="985" alt="Screen Shot 2020-05-30 at 12 03 12 AM" src="https://user-images.githubusercontent.com/31085177/83320109-dcbcfd80-a209-11ea-977b-b93474356f74.png">




and send issue i trying to change the image catagory  i change the Url and The ID still didn't take it 

<img width="1324" alt="Screen Shot 2020-05-29 at 6 39 39 PM" src="https://user-images.githubusercontent.com/31085177/83320111-dfb7ee00-a209-11ea-839c-3fd82a4ee29d.png">






thank you

**Comment by minhcasi** [comment]
@rabahaldoori - please help to try to update latest `1.7.4` and the mstore-api WP plugin

**Comment by rabahaldoori** [comment]
@minhcasi ok will gave you feedback i but i have another ticket about the home screen still didn't fix it

**Comment by minhcasi** [comment]
@rabahaldoori - pls move your all conversation to the same to ticket to prevent double investigating on your site - thank you for your time

**Comment by rabahaldoori** [comment]
@minhcasi the new update not showing the product at all

**Comment by rabahaldoori** [comment]
@kvt0012 how i make the App Sticky Home not moving when i scroll down, link the picture i don't need it to go above the background image 



<img width="367" alt="Screen Shot 2020-05-28 at 8 15 18 PM" src="https://user-images.githubusercontent.com/31085177/83210326-2cbf9580-a120-11ea-8add-cfdc204a18b6.png">

<img width="365" alt="Screen Shot 2020-05-28 at 8 15 11 PM" src="https://user-images.githubusercontent.com/31085177/83210321-2a5d3b80-a120-11ea-9658-ccafebeb90fc.png">



Thank you

**Comment by rabahaldoori** [comment]
@minhcasi any update?

**Comment by Cheewingtan** [comment]
> @rabahaldoori - pls move your all conversation to the same to ticket to prevent double investigating on your site - thank you for your time

Get the same problem here , I use latest Fluxbuilder to generate the code ,and everything on Fluxbuilder screen is ok but when I paste the code and generate to stimulator it almost blank just few categories got display
<img width="398" alt="Screenshot 2020-06-03 at 4 20 00 PM" src="https://user-images.githubusercontent.com/11556877/83613572-8c9dbc80-a5b6-11ea-8352-d6774a093353.png">

**Comment by rabahaldoori** [comment]
@Cheewingtan make sure you put your API in said the config and when you use the Fluxbuilder make sure you use your API and Chosen your category .

**Comment by minhcasi** [comment]
@rabahaldoori - could you send me your latest config json file ?

**Comment by rabahaldoori** [comment]
@minhcasi i already changed the them i have problems with vendor podcasts its showing same products over and over when i scroll down . I’m waiting for the new update

**Comment by Cheewingtan** [comment]
> @Cheewingtan make sure you put your API in said the config and when you use the Fluxbuilder make sure you use your API and Chosen your category .

yes ,I'm sure the API on config file is same to fluxbuilder API , when I flutter run to emulator is display all blank , and I use wcfm plugin is that not support ?

**Comment by Cheewingtan** [comment]
> @rabahaldoori - could you send me your latest config json file ?

I put the code to 1.7.3 and is all work to me now..... 1.7.4 is not stable to me ....

**Comment by rabahaldoori** [comment]
@Cheewingtan yes  1.4.7 in not stable with me too I’m waiting for the update

**Comment by minhcasi** [comment]
@rabahaldoori - pls update the `1.7.4` together with the latest mstore-api to fix the store list issue - thanks

**Comment by rabahaldoori** [comment]
@minhcasi I already did i have several problems as i said , vendor podcasts its showing same Products over and over when i scroll down and and the header not Sticky 
<img width="355" alt="Screen Shot 2020-06-03 at 10 45 45 PM" src="https://user-images.githubusercontent.com/31085177/83712822-3ba8bb00-a5ec-11ea-81a6-f9c558687a8a.png">


and see the products coming same for example if i have store have 50 products will show just 10 products over and over i already test it they previous  version was faster too 


<img width="377" alt="Screen Shot 2020-06-03 at 10 47 04 PM" src="https://user-images.githubusercontent.com/31085177/83712846-49f6d700-a5ec-11ea-9f08-df327d8b9975.png">


<img width="409" alt="Screen Shot 2020-06-03 at 10 47 10 PM" src="https://user-images.githubusercontent.com/31085177/83712839-46fbe680-a5ec-11ea-83e2-22f7a518842f.png">

**Comment by rabahaldoori** [comment]
@minhcasi i make video so you can see more clear 

https://www.youtube.com/watch?v=F9Op3gezUIw


Thank you

**Comment by rabahaldoori** [comment]
@minhcasi any update? and i didn't got the new release version 1.7.5 , when i download its showing" FluxStore-vendor-1.7-3.4 " and could check this video 

https://www.youtube.com/watch?v=F9Op3gezUIw

thank you

**Comment by minhcasi** [comment]
@rabahaldoori - I'm sorry for the confusion, the latest `1.7.5` is still on the sharing private Gitlab, please download from there if you have access to that repo.

We will release a new version on Envato on this week - thank you!

**Comment by rabahaldoori** [comment]
@minhcasi I don’t have an access. Did you check the video how i can fix this issue for vendors product?

**Comment by minhcasi** [comment]
@rabahaldoori - we are going to release the latest version `1.7.5` to fix this issue on today - thank you for your time

**Comment by rabahaldoori** [comment]
@minhcasi sir i update to 1.7.5 ,didn't fix anythings still same thing

**Comment by rabahaldoori** [comment]
@minhcasi i found out when i use "wcfm " its has this issue if i use "dokan " its find and normal !! could you help to found out why and fix this issue because my store with "wcfm"
Thank you

**Comment by minhcasi** [comment]
@minhtruong315 - pls help to check the image issue as described on this video https://www.youtube.com/watch?v=UPcvBjCa-9A

**Comment by rabahaldoori** [comment]
@minhcasi any update ?

**Comment by rabahaldoori** [comment]
hi @philipvu30 

Thank you 

[Archive.zip](https://github.com/inspireui/support/files/4750000/Archive.zip)

**Comment by minhtruong315** [comment]
> @minhtruong315 - pls help to check the image issue as described on this video https://www.youtube.com/watch?v=UPcvBjCa-9A
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/9c87a5623e733b005ebbccbe7266f94b3f2866b3/68747470733a2f2f692e7974696d672e636f6d2f76692f55506376426a43612d39412f687164656661756c742e6a7067"><img alt="" height="14" src="/yts/img/favicon_144-vfliLAfaB.png"> YouTube**[1 7 5](https://www.youtube.com/watch?v=UPcvBjCa-9A)**

hi @rabahaldoori 
please replace getProductsByStore function in services/wfcm.dart to fix this issue
```
@override
  Future<List<Product>> getProductsByStore({storeId, page}) async {
    try {
      if (page != 1) return [];
      final response =
          await wcApi.postAsync('flutter/products/owner', {"id": storeId});
      if (response is Map && isNotBlank(response["message"])) {
        throw Exception(response["message"]);
      } else {
        List<Product> list = [];
        for (var item in response) {
          if (item["status"] == "published" || item["status"] == "publish") {
            final product = Product.fromJson(item);
            if (item['store'] != null) {
              product.store = Store.fromWCFMJson(item["store"]);
            }
            list.add(product);
          }
        }
        return list;
      }
    } catch (e) {
      rethrow;
    }
  }
```

**Comment by rabahaldoori** [comment]
@minhtruong315 When i replace the "getProductsByStore "  products can't load on the page for check the video and i have issue with the URL Faill  when i used the old version 1.7.3+35 i don't get any fail and all the image work fine when i used the new version 1.7.5 i got this error 



https://www.youtube.com/watch?v=3IQeksQrJuQ


thank you

**Comment by minhtruong315** [comment]
How many products do you have on that vendor?

**Comment by rabahaldoori** [comment]
@minhtruong315 around 250 products

**Comment by minhtruong315** [comment]
@rabahaldoori can u send me admin account via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/3404

**Comment by rabahaldoori** [comment]
@minhtruong315 i already sent

**Comment by rabahaldoori** [comment]
@minhtruong315 i have second problem" vertical layout" not working when make the "isCaching : True " and App crash in real phone 


and i have last update for "MStore API" and 1.7.5 i make a video you can chick 


https://www.youtube.com/watch?v=zSbZXTBCp-w&feature=youtu.be


Thank you

**Comment by minhtruong315** [comment]
Hi @rabahaldoori please replace getProductsByStore function in services/wcfm.dart like this
```
@override
  Future<List<Product>> getProductsByStore({storeId, page}) async {
    try {
      final response = await wcApi
          .postAsync('flutter/products/owner', {"id": storeId, "page": page});
      if (response is Map && isNotBlank(response["message"])) {
        throw Exception(response["message"]);
      } else {
        List<Product> list = [];
        for (var item in response) {
          if (item["status"] == "published" || item["status"] == "publish") {
            final product = Product.fromJson(item);
            if (item['store'] != null) {
              product.store = Store.fromWCFMJson(item["store"]);
            }
            list.add(product);
          }
        }
        return list;
      }
    } catch (e) {
      rethrow;
    }
  }
```
replace build function in vendor/store_detail/products.dart like this
```
@override
  Widget build(BuildContext context) {
    final productsList = (products == null || products.isEmpty) && isFetching
        ? emptyList
        : products;

    if (productsList == null || productsList.isEmpty) {
      return Center(
          child: Text("No Product", style: TextStyle(color: Colors.black)));
    }

    return LayoutBuilder(
      builder: (context, contraints) {
        return Container(
          decoration: BoxDecoration(color: Theme.of(context).backgroundColor),
          child: SmartRefresher(
            enablePullDown: true,
            enablePullUp: !isEnd,
            controller: _refreshController,
            onRefresh: getProducts,
            onLoading: loadMore,
            child: productsList.isNotEmpty
                ? GridView.builder(
                    gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
                      crossAxisCount: 2,
                      childAspectRatio: 0.5,
                    ),
                    cacheExtent: 10000.0,
                    itemCount: productsList.length,
                    itemBuilder: (context, i) {
                      return Container(
                        width: 100,
                        child: ProductCard(
                          item: productsList[i],
                          showCart: false,
                          showHeart: true,
                          width: contraints.maxWidth / 2,
                          marginRight: 0.0,
                          // tablet: widget.width / screenSize.height > 1.2,
                        ),
                      );
                    },
                  )
                : Center(
                    child: Text(S.of(context).myProductsEmpty),
                  ),
          ),
        );
      },
    );
  }
```

**Comment by rabahaldoori** [comment]
@minhtruong315 its work Thank you , i need more thing if you could i need "vertical layout " keep loading in the home page ! its not load all the products 

Thank lot

**Comment by minhtruong315** [comment]
@rabahaldoori for vertical layout. if you don't config "limit" property it will load 20 products.
it can't load all products

**Comment by rabahaldoori** [comment]
@minhtruong315 how i can set the limits? I didn’t found it . And how about if I use the isCaching: true will not show the category on the vertical layout ?

**Comment by rabahaldoori** [comment]
@minhtruong315 its stop working again "wcfm " i don't know why !!!

**Comment by rabahaldoori** [comment]
@minhtruong315 any update?

**Comment by minhtruong315** [comment]
Hi @rabahaldoori you can edit VerticalLayout like this
```
"VerticalLayout": {
    "layout": "list",
    "name": "Recent Collections",
    "limit": 10,
    "category": 10
  }
```

**Comment by rabahaldoori** [comment]
hi @minhtruong315 this not just the problem first "wcfm" come back not working after update .and when isCaching : true " not got any products and if i keep it without isCaching the app crash .

**Comment by minhtruong315** [comment]
can u upload your source code to github and invite me: minhtruong315@gmail.com
I will help you check and fix on it
Thanks

**Comment by rabahaldoori** [comment]
@minhtruong315 ok and see this video too 

https://www.youtube.com/watch?v=O5RKwruo-zU

thank you

**Comment by rabahaldoori** [comment]
@minhtruong315 i sent to by email my project and the login to website 

Thank you

**Comment by minhtruong315** [comment]
Hi @rabahaldoori I dont see any email. please resend again. Thanks

**Comment by rabahaldoori** [comment]
@minhtruong315 i sent it again . Thanks

**Comment by minhtruong315** [comment]
Hi @rabahaldoori please update like this to fix your issue
<img width="1282" alt="Screen Shot 2020-06-16 at 1 44 22 PM" src="https://user-images.githubusercontent.com/10402500/84740438-94f2f000-afd7-11ea-8846-8140c8023b2e.png">

**Comment by minhtruong315** [comment]
Hi @rabahaldoori I enabled isCaching. it's working well.
![Simulator Screen Shot - iPhone X - 2020-06-16 at 13 50 43](https://user-images.githubusercontent.com/10402500/84745966-84df0e80-afdf-11ea-947d-ed76abf43779.png)

**Comment by rabahaldoori** [comment]
@minhtruong315 not working because I already uploaded different json them to my sore Api . if you turn off you will see

**Comment by minhtruong315** [comment]
Hi @rabahaldoori I tried to enable and disable isCaching, it's working well
https://www.dropbox.com/s/446owqgddexai5r/home.mov?dl=0

**Comment by rabahaldoori** [comment]
Hi @minhtruong315 i saw your video just the vertical layout is not working with isCaching not showing products . i update to new version it’s better but same issue the vertical layout isCaching . 

Thank you

**Comment by rabahaldoori** [comment]
@minhtruong315 i have same issue with this ticket 3779

**Comment by minhtruong315** [comment]
@rabahaldoori replace these functions in services/woocommerce.dart
```
@override
  Future<List<Product>> fetchProductsLayout({config, lang}) async {
    try {
      List<Product> list = [];

      if (kAdvanceConfig['isCaching'] && configCache != null) {
        var obj;
        final horizontalLayout = configCache["HorizonLayout"] as List;
        if (horizontalLayout != null) {
          obj = horizontalLayout.firstWhere(
              (o) =>
                  o["layout"] == config["layout"] &&
                  ((o["category"] != null &&
                          o["category"] == config["category"]) ||
                      (o["tag"] != null && o["tag"] == config["tag"])),
              orElse: () => null);
          if (obj != null && obj["data"].length > 0) return obj["data"];
        }

        final verticalLayout = configCache["VerticalLayout"];
        if (verticalLayout != null &&
            verticalLayout["layout"] == config["layout"] &&
            ((verticalLayout["category"] != null &&
                    verticalLayout["category"] == config["category"]) ||
                (verticalLayout["tag"] != null &&
                    verticalLayout["tag"] == config["tag"]))) {
          return verticalLayout["data"];
        }
      }

      var endPoint = "products?lang=$lang&status=publish";
      if (config.containsKey("category") && config["category"] != null) {
        endPoint += "&category=${config["category"]}";
      }
      if (config.containsKey("tag") && config["tag"] != null) {
        endPoint += "&tag=${config["tag"]}";
      }

      /// Add featured filter
      if (config.containsKey("featured") && config["featured"] != null) {
        endPoint += "&featured=${config["featured"]}";
      }

      /// Add onSale filter
      if (config.containsKey("onSale") && config["onSale"] != null) {
        endPoint += "&on_sale=${config["onSale"]}";
      }

      if (config.containsKey("page")) {
        endPoint += "&page=${config["page"]}";
      }
      if (config.containsKey("limit")) {
        endPoint += "&per_page=${config["limit"] ?? ApiPageSize}";
      }

      var response = await wcApi.getAsync(endPoint);

      if (response is Map && isNotBlank(response["message"])) {
        print('WooCommerce Error: ' + response["message"]);
      } else {
        for (var item in response) {
          if (!kAdvanceConfig['hideOutOfStock'] || item["in_stock"]) {
            Product product = Product.fromJson(item);
            product.categoryId = config["category"].toString();
            if (item['store'] != null) {
              product = Services().widget.updateProductObject(product, item);
            }
            list.add(product);
          }
        }
      }
      return list;
    } catch (e, trace) {
      print(trace.toString());
      print(e.toString());
      //This error exception is about your Rest API is not config correctly so that not return the correct JSON format, please double check the document from this link https://docs.inspireui.com/fluxstore/woocommerce-setup/
      return [];
    }
  }
```
```
Future<Map<String, dynamic>> getHomeCache() async {
    try {
      final data = await wcApi.getAsync('flutter/cache');
      if (data['message'] != null) {
        throw Exception(data['message']);
      }
      var config = data;
      if (config['HorizonLayout'] != null) {
        var horizontalLayout = config['HorizonLayout'] as List;
        var items = [];
        var products = [];
        List<Product> list;
        for (var i = 0; i < horizontalLayout.length; i++) {
          if (horizontalLayout[i]["radius"] != null) {
            horizontalLayout[i]["radius"] =
                double.parse("${horizontalLayout[i]["radius"]}");
          }
          if (horizontalLayout[i]["size"] != null) {
            horizontalLayout[i]["size"] =
                double.parse("${horizontalLayout[i]["size"]}");
          }
          if (horizontalLayout[i]["padding"] != null) {
            horizontalLayout[i]["padding"] =
                double.parse("${horizontalLayout[i]["padding"]}");
          }

          products = horizontalLayout[i]["data"] as List;
          list = [];
          if (products != null && products.isNotEmpty) {
            for (var item in products) {
              Product product = Product.fromJson(item);
              product.categoryId = horizontalLayout[i]["category"].toString();
              product = Services().widget.updateProductObject(product, item);
              list.add(product);
            }
          }
          horizontalLayout[i]["data"] = list;

          items = horizontalLayout[i]["items"] as List;
          if (items != null && items.isNotEmpty) {
            for (var j = 0; j < items.length; j++) {
              if (items[j]["padding"] != null) {
                items[j]["padding"] = double.parse("${items[j]["padding"]}");
              }

              List<Product> listProduct = [];
              var prods = items[j]["data"] as List;
              if (prods != null && prods.isNotEmpty) {
                for (var item in prods) {
                  Product product = Product.fromJson(item);
                  product =
                      Services().widget.updateProductObject(product, item);
                  listProduct.add(product);
                }
              }
              items[j]["data"] = listProduct;
            }
          }
        }

        if (config['VerticalLayout'] != null) {
          var products = config['VerticalLayout']["data"] as List;
          List<Product> list = [];
          if (products != null && products.isNotEmpty) {
            for (var item in products) {
              Product product = Product.fromJson(item);
              product = Services().widget.updateProductObject(product, item);
              list.add(product);
            }
          }
          config['VerticalLayout']["data"] = list;
        }

        configCache = config;
        return config;
      }
      return null;
    } catch (e, trace) {
      print(trace);
      print(e);
      //This error exception is about your Rest API is not config correctly so that not return the correct JSON format, please double check the document from this link https://docs.inspireui.com/fluxstore/woocommerce-setup/
      return null;
    }
  }
```

**Comment by rabahaldoori** [comment]
@minhtruong315 its work but show error and i put in my limit 30 products its showing only 10 

<img width="1411" alt="Screen Shot 2020-06-17 at 11 32 14 PM" src="https://user-images.githubusercontent.com/31085177/84978616-0378a080-b0f3-11ea-8f2b-dac6cc657caf.png">

**Comment by minhtruong315** [comment]
@rabahaldoori fixed. please check  again

**Comment by rabahaldoori** [comment]
@minhtruong315 yes its fix good thank you 

i have some problem 

1- the products in showing the background behind the products i tried to put the 

"Container(decoration: BoxDecoration(color: Theme.of(context).backgroundColor)," 

its work with some and some not 

<img width="392" alt="Screen Shot 2020-06-19 at 5 11 54 AM" src="https://user-images.githubusercontent.com/31085177/85122135-b1677600-b1eb-11ea-9a19-ba5213024369.png">


2- the when i try to post new products from vendor when i chose the category its didn't post inside the category its post only in vendor store 

<img width="391" alt="Screen Shot 2020-06-19 at 5 12 57 AM" src="https://user-images.githubusercontent.com/31085177/85122387-13c07680-b1ec-11ea-8a69-751a57cbe584.png">





3- question there is a way i can put the vendor stores in home screen ? 


<img width="374" alt="Screen Shot 2020-06-19 at 5 18 10 AM" src="https://user-images.githubusercontent.com/31085177/85122528-508c6d80-b1ec-11ea-9e9e-b9240bd48ac8.png">



Thank you lot for your help .

**Comment by Carlosdmendoza** [comment]
I am having the same problem at you at the backgorund image if you get a response in how to remove the image in the back and how to put vendors in home page let me know please.

**Comment by minhtruong315** [comment]
@rabahaldoori 1- the products in showing the background behind the products i tried to put the
You can change like this
<img width="1261" alt="Screen Shot 2020-06-24 at 9 49 02 AM" src="https://user-images.githubusercontent.com/10402500/85492826-021e0b00-b600-11ea-9750-080c149dba95.png">

**Comment by minhtruong315** [comment]
@rabahaldoori I didn't  install MStore Api  plugin on your website. so I can't check create product issue.

**Comment by rabahaldoori** [comment]
@minhtruong315   the background its working thank you @Carlosdmendoza check this one its work with me

**Comment by minhtruong315** [comment]
> @rabahaldoori I didn't install MStore Api plugin on your website. so I can't check create product issue.

@rabahaldoori how about this?

**Comment by Carlosdmendoza** [comment]
@rabahaldoori  @minhtruong315  Let me tell you that the code above partially worked for me it fixed the problem with the background for the  ProductListLayout which is great but the background is still showing in the vertical LAyout with the Menu Widget I have at the bottom see attached screenshots. Any idea on how to fix it?
![WhatsApp Image 2020-06-24 at 12 52 34 PM (3)](https://user-images.githubusercontent.com/46724211/85615983-51713500-b61a-11ea-8252-83da365cc0c9.jpeg)
![WhatsApp Image 2020-06-24 at 12 52 34 PM (2)](https://user-images.githubusercontent.com/46724211/85615994-56ce7f80-b61a-11ea-8671-a16e8b0b396f.jpeg)

**Comment by Carlosdmendoza** [comment]
"VerticalLayout":{
    "key":"0f9o23ca7e",
    "layout":"menu",
    "name":"Mas productos",
    "category":"91",
    "background": "FFFFFF"
  } In my Config.json file this is the one that is still not displaying properly yet if you have any suggestions that would be great!

**Comment by rabahaldoori** [comment]
@Carlosdmendoza i will send you my file i already fix all of them for Widget so you can just replace it   Gave around 3 hours

**Comment by minhtruong315** [comment]
@rabahaldoori how about issue for create product?

**Comment by rabahaldoori** [comment]
hi @minhtruong315 same thing when i create product didn't go to category and didn't show just on my products

**Comment by rabahaldoori** [comment]
@Carlosdmendoza 
[widgets.zip](https://github.com/inspireui/support/files/4828797/widgets.zip)

**Comment by minhtruong315** [comment]
Hi @rabahaldoori 
You're config your app is wcfm
```
 "type": "wcfm", // type: dokan or wcfm
  "url": "https://www.alnehrstreet.com",
```
But you dont install any wcfm plugin on your website

**Comment by rabahaldoori** [comment]
@minhtruong315 yes i remove your app because lot of bugs until fix everything i'm doing local test right now and i will install it on different domain  "alnehrstreet.org " i will send you the information about it by email 

Thank you

**Comment by Carlosdmendoza** [comment]
Man, It finally worked Thank you I appreciate it, you have been great! I
don't want to be bothering you with every small issue I might have in the
future would you mind telling me what was the problem? Or how did you fix
it I have spoken with three different people and you are the only one that
has been able to fix it so thank you!

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by minhtruong315** [comment]
> @minhtruong315 yes i remove your app because lot of bugs until fix everything i'm doing local test right now and i will install it on different domain "alnehrstreet.org " i will send you the information about it by email
> 
> Thank you

How?
