### ISSUE TITLE
[FluxStore WooCommerce] Problems with product variations for complex variable products

### ISSUE THREAD

**Issue by and-eee** [inspireui/support#3406]
Hello support team,

In my project I am dealing with a number of products with many attributes and therefore a large number of variatons (200+ each) which affect the price, and while it is working fine on the site it is not working correctly on the app. 

Sample product on site: https://app.whitehenry.com.au/product/cappuccino/

Site (**correct** price):
![image](https://user-images.githubusercontent.com/63891246/82855441-adc73300-9f4e-11ea-8e6d-3f14e2061141.png)

App: (**incorrect** price):
![image](https://user-images.githubusercontent.com/63891246/82855644-31811f80-9f4f-11ea-95cb-ce6551ca38f8.png)

I have attached the **common/config** directory for your reference as requested.
[config.zip](https://github.com/inspireui/support/files/4679676/config.zip)

Secondarily, when these products are being purchased, the checkout page truncates the list of variations as seen in this screenshot:
![image](https://user-images.githubusercontent.com/63891246/82856559-9dfd1e00-9f51-11ea-9de4-27f09ad9fe4f.png)

It would be ideal to extend the cart field to include all variations (ideally in a smaller font with reduced line spacing). Keep in mind however that not all products will have such a long list of variations.

As a side-note, can I suggest that you begin to look into supporting any one of the many **product add-on plugins** for woocommerce which are so widely used by users like me for complex products that don't require individual SKUs. 

Please let me know if you require more information. 

Thank you for your prompt attention.

**Comment by kvt0012** [comment]
Dear sir, the first issue is because this price is fetched on your api, so please check it. 
Second problem, please send me your screenshow again, I can't see it. 
About this feature, on this time we don't have plan to support enternal plugin because it's too much. Btw if you suggest us for detail and we will survey our customer to check whether it's neccessary or not. If it's neccessary, we will put it on suggest feature. Thank you

**Comment by and-eee** [comment]
Hi, you can see the screen captures here:  https://github.com/inspireui/support/issues/3406

In regards to the api issue, can you please explain what you mean. "Check it" doesnt help me at all. It is working fine on the website.

**Comment by kvt0012** [comment]
Dear sir, I mean that on second problem, you said that
"Secondarily, when these products are being purchased, the checkout page truncates the list of variations as seen in this screenshot:" 
I can't see this screenshot here, can you send me again. 
About api, can you take a pic on your website with same probduct, I will check it, thank you

**Comment by and-eee** [comment]
My first 2 screenshots are a comparison of the same product, one on the site, the other on the app. the 3rd screen capture in my original post is the app truncating the list of variations in the cart. SO there should be 3 screen captures in the original post. Can you see the 3 screen captures in https://github.com/inspireui/support/issues/3406 or is there something wrong with the entry? 

I am adding here for your reference the result of an API call to one of the many variation combinations that don't work on the app but is clearly being served by the API:

![image](https://user-images.githubusercontent.com/63891246/82896380-379bee00-9f99-11ea-8d94-62f96d0dd05b.png)

Text Results

**`GET https://app.whitehenry.com.au/wp-json/wc/v3/products/13950/variations?page=14`**

```
{
    "id": 21639,
    "date_created": "2020-05-26T21:06:36",
    "date_created_gmt": "2020-05-26T11:06:36",
    "date_modified": "2020-05-26T21:08:50",
    "date_modified_gmt": "2020-05-26T11:08:50",
    "description": "<p><span id=\"mbainfo\">Product price $3.70<br \/>\nAdd $0.50 for SOY<br \/>\nAdd $0.50 for SINGLE ORIGIN<br \/>\n<\/span><\/p>\n",
    "permalink": "https:\/\/app.whitehenry.com.au\/product\/latte\/?attribute_pa_size=small&attribute_pa_milk=soy&attribute_pa_blend=single-origin&attribute_pa_strength=regular",
    "sku": "",
    "price": "4.7",
    "regular_price": "4.7",
    "sale_price": "",
    "date_on_sale_from": null,
    "date_on_sale_from_gmt": null,
    "date_on_sale_to": null,
    "date_on_sale_to_gmt": null,
    "on_sale": false,
    "status": "publish",
    "purchasable": true,
    "virtual": false,
    "downloadable": false,
    "downloads": [],
    "download_limit": -1,
    "download_expiry": -1,
    "tax_status": "taxable",
    "tax_class": "",
    "manage_stock": false,
    "stock_quantity": null,
    "stock_status": "instock",
    "backorders": "no",
    "backorders_allowed": false,
    "backordered": false,
    "weight": "",
    "dimensions": {
      "length": "",
      "width": "",
      "height": ""
    },
    "shipping_class": "",
    "shipping_class_id": 0,
    "image": {
      "id": 20851,
      "date_created": "2020-05-20T03:53:28",
      "date_created_gmt": "2020-05-19T07:53:28",
      "date_modified": "2020-05-20T03:53:28",
      "date_modified_gmt": "2020-05-19T07:53:28",
      "src": "https:\/\/i0.wp.com\/app.whitehenry.com.au\/wp-content\/uploads\/2020\/04\/latte.jpg?fit=800%2C400&ssl=1",
      "name": "latte",
      "alt": ""
    },
    "attributes": [
      {
        "id": 23,
        "name": "Size",
        "option": "SMALL"
      },
      {
        "id": 24,
        "name": "Milk",
        "option": "SOY"
      },
      {
        "id": 28,
        "name": "Blend",
        "option": "SINGLE ORIGIN"
      },
      {
        "id": 27,
        "name": "Strength",
        "option": "REGULAR"
      }
    ],
    "menu_order": 147,
    "meta_data": [],
    "_links": {
      "self": [
        {
          "href": "https:\/\/app.whitehenry.com.au\/wp-json\/wc\/v3\/products\/13950\/variations\/21639"
        }
      ],
      "collection": [
        {
          "href": "https:\/\/app.whitehenry.com.au\/wp-json\/wc\/v3\/products\/13950\/variations"
        }
      ],
      "up": [
        {
          "href": "https:\/\/app.whitehenry.com.au\/wp-json\/wc\/v3\/products\/13950"
        }
```
The 3 screen captures in the original post again:

**Website** product - working correctly (`https://user-images.githubusercontent.com/63891246/82855441-adc73300-9f4e-11ea-8e6d-3f14e2061141.png`):
https://user-images.githubusercontent.com/63891246/82855441-adc73300-9f4e-11ea-8e6d-3f14e2061141.png

**App** screen for the same product, note **price is wrong** (`https://user-images.githubusercontent.com/63891246/82855644-31811f80-9f4f-11ea-95cb-ce6551ca38f8.png`):
https://user-images.githubusercontent.com/63891246/82855644-31811f80-9f4f-11ea-95cb-ce6551ca38f8.png

Cart screen in App, note the truncated variations list: (`https://user-images.githubusercontent.com/63891246/82856559-9dfd1e00-9f51-11ea-9de4-27f09ad9fe4f.png`):
https://user-images.githubusercontent.com/63891246/82856559-9dfd1e00-9f51-11ea-9de4-27f09ad9fe4f.png 

I hope this helps to clarify the issue. Please let me know.

**Comment by minhcasi** [comment]
@philipvu30 - pls help with investigating

**Comment by philipvu30** [comment]
Hi,

1. Please replace this [woo_commerce.dart](https://github.com/inspireui/support/files/4693085/woo_commerce.dart.zip) in the path lib/services/woo_commerce.dart

2. Remove this line in lib/widgets/product/cart_item.dart

![image](https://user-images.githubusercontent.com/54442328/83096276-7b910f00-a0cf-11ea-959b-b9a7cc8e0ac2.png)

**Comment by and-eee** [comment]
Brilliant, that's solved it, thanks very much guys!

**Comment by ameenbadri7** [comment]
@minhcasi  this fix is Brilliant inded.
