### ISSUE TITLE
How to Center Category Icon widget

### ISSUE THREAD

**Issue by aliehanani** [inspireui/support#3407]
Step 1 (require): detail issues and screenshots
Hi , please advise on centering the category icon widget? 

Also, for some reason the largeCardHorizontalListItems is no longer loading products with version 1.7.3; I had flush the cache on the site and it works fine in version 1.6.6.

![image](https://user-images.githubusercontent.com/12172666/82865227-3e245a00-9ef4-11ea-9e6d-930e07218bbc.png)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by kvt0012** [comment]
Please try to use our fuxbuilder to config it, thank you

**Comment by aliehanani** [comment]
When "wrap":true is set, not all the text of the category title shows. I tried changing the font size (fontSize: kLayoutWeb ? 18 : 10,) in lib/widgets/home/category/category_icon_items.dart, but reducing the size makes the text/title look too small. I did some research on making the words fit but no clear direction found so far. Please help on making the category title text fit?

<img width="1709" alt="Screen Shot 2020-05-26 at 4 07 31 PM" src="https://user-images.githubusercontent.com/12172666/82945528-17edd100-9f6b-11ea-849f-2f34c33f132c.png">

**Comment by kvt0012** [comment]
You can check it on woo_comerce.dart, we set limit is 10, if you want more, please change it, thank you

**Comment by aliehanani** [comment]
Please read my previous comment carefully. The option is not in lib/services/__mocks__/woo_commerce.dart, it in category_icon_items.dart. I want to know how to configure the text to fit within the the container?

**Comment by kvt0012** [comment]
Ok sir, I'm sorry for not reading your issue carefully. 
You can try to edit textAlign: TextAlign.center to textAlign: TextAlign.left. 
Or you add margin: const EdgeInsets.all(10.0), it will help you add margin to the text. And you can edit width and height of container to increase the space of text, thank you
