### ISSUE TITLE
New release of flux store multi vendor

### ISSUE THREAD

**Issue by engbasselayman** [inspireui/support#3408]
can I know when will you upload the new release because i have the same errors of 
1- continuous loading after login via gmail and sms .
2- registration error (please agree with our terms ) .

**Comment by minhcasi** [comment]
@engbasselayman - we will upload the latest `1.7.4` in 1-2 days - thank you!

**Comment by engbasselayman** [comment]
@minhcasi 
it is 4 days until now any news ?

**Comment by Zeehshan** [comment]
same here i am facing this issue in version 1.7.3, kindly let us know when you will resolve this issues ?

**Comment by minhcasi** [comment]
@engbasselayman @Zeehshan - sorry for the delay - we will update the new release today (due to some final testing issue) - thank you for your patience

**Comment by minhcasi** [comment]
Please help to try to update latest `1.7.4` and the mstore-api WP plugin.
