### ISSUE TITLE
FLUXSTORE MV - CAN'T REGIST NEW CUSTOMER

### ISSUE THREAD

**Issue by antixirus** [inspireui/support#3409]
Step 1 (require): detail issues and screenshots
![gambar](https://user-images.githubusercontent.com/57300649/82871633-17017300-9f5c-11ea-9466-479011bacf5c.png)

Iam delete code for create Vendor account, because i'll make it manual, but after iam delete code vendor, iam can't regist new customer. "Please agree with Privacy and Police" Even though I agreed.
Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by antixirus** [comment]
@minhcasi @vumanhsn97 @trunghieuvn

**Comment by minhcasi** [comment]
@antixirus  - We wanted to thank you for your patience during this busy time. We currently have reduced staff and a significantly higher volume of inquiries. We’re working as hard as we can to get to your request as soon as possible.

We will release new version `1.7.4` to fix this issue in 1-2 days

**Comment by emadpost2016** [comment]
are you release new version 1.7.4 to fix this issue

**Comment by antixirus** [comment]
@emadpost2016 v1.7.4 maybe as soon as possible sir

**Comment by minhcasi** [comment]
sorry for the delay - we will update the new release today (due to some final testing issue) - thank you for your patience

**Comment by minhcasi** [comment]
@antixirus - please update the latest `1.7.4` to fix this issue - thank you!
