### ISSUE TITLE
[ListApp]While sending the comment is not working properly..

### ISSUE THREAD

**Issue by Pavithran10** [inspireui/support#341]
**Required Info (please complete the following information):**
 Product:[ListApp]
Version:1.6.1
Theme: MyListing

**Describe the bug**
hi, In booking page message icon is there while clicking that icon it's redirect to review page in that we enter the comment in the text box after clicking send button the comment not sending. thanks

**Screenshots**
![msgicon](https://user-images.githubusercontent.com/46148046/53493911-8b800480-3ac2-11e9-86f5-e9816db0ddcc.jpg)
![msgbutton](https://user-images.githubusercontent.com/46148046/53493919-9044b880-3ac2-11e9-9251-711fad333323.jpg)

**Comment by thangvo9x** [comment]
HI. Can you send me your AppConfig file for checking ? These problem is coming from your site.

**Comment by Pavithran10** [comment]
hi, I've attached both files appconfig.json and mylisting.js 

[main.zip](https://github.com/inspireui/support/files/2913419/main.zip)

**Comment by thangvo9x** [comment]
Please refer document guide here 
https://inspireui.github.io/listapp/docs/quickstart
JWT plugin is not configurated clearly.
![not clear](https://user-images.githubusercontent.com/23457178/53548048-26302000-3b63-11e9-87ca-a597504769e4.png)

**Comment by Pavithran10** [comment]
ok, now we want to update JWT plugin

**Comment by thangvo9x** [comment]
Hi. Login is not working. I can't test it.
JWT is not configurated invalid.
<img width="645" alt="issue" src="https://user-images.githubusercontent.com/23457178/53613115-a019e500-3c07-11e9-8429-0521fa47df8e.png">

**Comment by Pavithran10** [comment]
hi, then how to solve this issue...

**Comment by thangvo9x** [comment]
Please refer here 
https://wordpress.org/plugins/jwt-authentication-for-wp-rest-api/
or https://inspireui.github.io/listapp/docs/quickstart

**Comment by Pavithran10** [comment]
hi, I'll try and update. thanks

**Comment by thangvo9x** [comment]
Hi. I can't test review function because JWT plugin isnt config correctly. Please check help me.
<img width="684" alt="issue" src="https://user-images.githubusercontent.com/23457178/53715342-14f95300-3e84-11e9-9d1f-371315e38278.png">

**Comment by Pavithran10** [comment]
hi, I've config last update of JWT authentication of rest-api plugin as you sended in that link . So, please check it.

**Comment by thangvo9x** [comment]
Hi. I checked your JWT. you isn't config correctly. refer here 
https://wordpress.org/plugins/jwt-authentication-for-wp-rest-api/

1. add to .htaccess
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule ^(.*) - [E=HTTP_AUTHORIZATION:%1]
2. add to .htaccess (out of </IfModule> )
SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1
3. define a key in wp-config.php 
define('JWT_AUTH_SECRET_KEY', 'your-top-secret-key');
4. or set define('JWT_AUTH_CORS_ENABLE', true) in wp-config.php if your server is running nginx.
Thanks

**Comment by Pavithran10** [comment]
thanks, i'll check and update

**Comment by Pavithran10** [comment]
hi, We updated 'htaccess' things in the site server. then also than review "send" button doesn't working still now. 
Note: The Rest API is able to fetch data from the above json url
https://housora.com/wp-json/wp/v2/job_listing?_embed=true&page=1&per_page=10&status=publish

thanks.

**Comment by thangvo9x** [comment]
Because the JWT is not config correctly. you must log in to test review "send". I checked again. but still not working. show .htaccess file here to view it.

**Comment by Pavithran10** [comment]
hi, this is the public forum so, that I've atttached the htaccess file text format to your mail. please check it. thanks

**Comment by thangvo9x** [comment]
Hi. i viewed your htaccess file, but i still can't login because JWT is not config correctly.

**Comment by Pavithran10** [comment]
hi, our side we solve that htaccess config and plugins installation are done properly. **JWT is not config correctly** but you told this the problem to clear we don't know how to clear this error. otherwise please give correct solution make to solve this issue. thanks

**Comment by thangvo9x** [comment]
Then the issue has only from your server. which server are you using?
