### ISSUE TITLE
Change the content of screen that comes after splash screen

### ISSUE THREAD

**Issue by hackzie** [inspireui/support#3410]
Hi , I want to change the content of the screen that comes after splash screen. I think how to change it is not mentioned in documentation. Please tell me how to do that.
![Inkede5083358-96f8-468e-a052-2fb4d9cf6bfe_LI](https://user-images.githubusercontent.com/35571313/82872613-e962fc80-9f50-11ea-8058-75bac3714a26.jpg)

**Comment by atijke** [comment]
Check this one https://docs.inspireui.com/fluxstore/customization/

7. Onboarding and Login mode

**Comment by hackzie** [comment]
Hii thanks a lot. I got that. I have one more error. Please resolve it
![ice_screenshot_20200526-131038](https://user-images.githubusercontent.com/35571313/82873625-69d62d00-9f52-11ea-875b-3927ca3aacdb.png)

I dont know why is this error coming. I uploaded the same config in website and pased on config_en.json file of source code.

**Comment by minhcasi** [comment]
@hackzie - you could try to use the latest 1.7.4 to fix this issue
