### ISSUE TITLE
Country selection from pop up does not work...

### ISSUE THREAD

**Issue by niravmithani** [inspireui/support#3412]
![image](https://user-images.githubusercontent.com/65595605/82877608-01e11000-9f6d-11ea-8c6d-15c2e0f2f06c.png)

I had selected country from pop up but its not coming to parent window.

_Originally posted by @niravmithani in https://github.com/inspireui/support/issues/3291#issuecomment-633882110_

**Comment by luyx2412** [comment]
HI @niravmithani the issue related https://github.com/inspireui/support/issues/2190#issuecomment-593433656

Thanks
