### ISSUE TITLE
Error in Compilation since Package Name Changed

### ISSUE THREAD

**Issue by GNAG1993** [inspireui/support#3413]
**This is the issue I'm getting when I play app in debug mode after changing package name:**

Launching lib\main.dart on Infinix X626B in debug mode...
Running Gradle task 'assembleDebug'...
e: C:\src\source\android\app\src\main\kotlin\com\violetkart\mlv\MainActivity.kt: (8, 7): Redeclaration: MainActivity
e: C:\src\source\android\app\src\main\kotlin\com\violetkart\mlv\vlk\MainActivity.kt: (7, 7): Redeclaration: MainActivity

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9m 16s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by minhcasi** [comment]
@GNAG1993 - what is your package name? is it `com.violetkart.mlv` ?

**Comment by GNAG1993** [comment]
its com.violetkart.mlv.vlk

**Comment by GNAG1993** [comment]
Hello..You there?

**Comment by GNAG1993** [comment]
Hello?? @minhcasi

**Comment by minhcasi** [comment]
@GNAG1993 - try to remove this file from your project `C:\src\source\android\app\src\main\kotlin\com\violetkart\mlv\MainActivity.kt` it seem you have 2 MainActivity.kt file

**Comment by minhcasi** [comment]
let us know your checking, thanks

**Comment by GNAG1993** [comment]
Hy, I checked and it worked. Thanx
