### ISSUE TITLE
[FluxStore Pro] Problem with Fluxstore Pro and WooCommerce v1.7.4

### ISSUE THREAD

**Issue by JohanSmith20** [inspireui/support#3414]
Step 1 (require): detail issues and screenshots
Hello I have a problem with fluxstore and woocommerce, first i'm using a plugin for variation image swatch so i can put on the website the swatches as an image not a color or a text and everything is working good but now when i enter my app everything working correctly except when i start to choose a color for the product i want to buy, it gives me an error as you see in the screenshot... I sent to you through (**http://private.inspireui.com**) All the files you need: lib>common (folder) with all the files inside it - config.dart - config_en.json - Website Admin Panel Username and Password as a text

Thank you.

![98119357_1299243996931941_6365606196593819648_n](https://user-images.githubusercontent.com/64312037/82884818-908d6700-9f44-11ea-85c1-631f17ca6bd6.jpg)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)
**DONE**

**Comment by philipvu30** [comment]
Hi,

Please replace this [file](https://github.com/inspireui/support/files/4681311/product_variant.dart.zip) in lib/screens/detail/product_variant.dart

Kindly close this ticket if it solves your issue. Thank you.

For further questions/issues, feel free to ask us to re-open this ticket

**Comment by Jegufull** [comment]
ok
