### ISSUE TITLE
how to add admob on home screen Interstitial ?

### ISSUE THREAD

**Issue by surajk1986** [inspireui/support#3415]
how to add admob on home screen Interstitial ?

at present  admob shown in product detail section only

![admo](https://user-images.githubusercontent.com/65123761/82892343-380b9900-9f47-11ea-8660-b10d6ffa233b.jpg)

**Comment by minhcasi** [comment]
@surajk1986 - pls help us to move your all conversation to the same ticket #3379 - our team will help for checking and easier to update
