### ISSUE TITLE
Unable to create Facebook Hash Key

### ISSUE THREAD

**Issue by HarrySmith01** [inspireui/support#3417]
Step 1 (require): detail issues and screenshots

I am trying to create facebook hash key but it is not working.

I have tried below commands but nothing worked.

```
Microsoft Windows [Version 10.0.18363.836]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\PUBG\Desktop\FluxStore>keytool -exportcert -alias key -keystore C:\Users\PUBG\Desktop\FluxStore\certs\key.jks | openssl
sha1 -binary | openssl base64
'openssl' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\PUBG\Desktop\FluxStore>keytool -exportcert -alias key -keystore C:\Users\PUBG\Desktop\FluxStore\android\key.properties |
 openssl sha1 -binary | openssl base64
'openssl' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\PUBG\Desktop\FluxStore>keytool -exportcert -alias key -keystore certs/key.jks| openssl sha1 -binary | openssl base64
'openssl' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\PUBG\Desktop\FluxStore>
```

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

Required information submitted through google form

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@HarrySmith01 - pls check this guide https://medium.com/@inspireui/setup-facebook-login-for-flutter-apps-4e7bd031479d

**Comment by HarrySmith01** [comment]
I have already followed that guide but code mentioned in the guide is not working.

If you want then I can share the team viewer.

**Comment by minhcasi** [comment]
On window please try this script

```
keytool -genkey -v -keystore c:\Users\USER_NAME\key.jks -storetype JKS -keyalg RSA -keysize 2048 -validity 10000 -alias key
```

ref: https://flutter.dev/docs/deployment/android

**Comment by minhcasi** [comment]
@HarrySmith01 

17

pleases try to install `openssl` for windows from the following link.

https://code.google.com/p/openssl-for-windows/downloads/detail?name=openssl-0.9.8k_WIN32.zip

**Comment by HarrySmith01** [comment]
I have downloaded it but it does not have any installation file.

how to install it or where should i place the downloaded file?

**Comment by minhcasi** [comment]
@HarrySmith01  - that is the installing file - pls check this conversation https://stackoverflow.com/questions/4388992/key-hash-for-android-facebook-app 

_Download openssl from Google code (If you have a 64 bit machine you must download openssl-0.9.8e X64 not the latest version)_

**Comment by HarrySmith01** [comment]
This one worked and I was able to get hash key.
