### ISSUE TITLE
how to change vendor section  display image in …..

### ISSUE THREAD

**Issue by surajk1986** [inspireui/support#3418]
how to change vendor display image 
in …..my app blank images shown in vendor section

![Screenshot_1590491265](https://user-images.githubusercontent.com/65123761/82894104-f29c9b00-9f49-11ea-8e2c-3d91a102318b.png)

**Comment by minhcasi** [comment]
@surajk1986 - pls help us to move your all conversation to the same ticket #3379 - our team will help for checking and easier to update
