### ISSUE TITLE
Adding New Language Problem

### ISSUE THREAD

**Issue by smark98** [inspireui/support#3419]
![Képernyőfotó 2020-05-26 - 14 59 26](https://user-images.githubusercontent.com/37720115/82903644-87f75980-9f61-11ea-9738-6914ec01fa03.png)
Hi,

For me the new languages not working. The automatically generation not work. And when I added by hand and copied and translated all files it is get error to the file not found but I have the file.

What can I do?

![Képernyőfotó 2020-05-26 - 14 50 44](https://user-images.githubusercontent.com/37720115/82903018-9e50e580-9f60-11ea-9672-01d05910ca0a.png)
![Képernyőfotó 2020-05-26 - 14 51 50](https://user-images.githubusercontent.com/37720115/82903021-9f821280-9f60-11ea-9b49-da59121012f3.png)

**Comment by minhcasi** [comment]
@smark98 - could you try this guide https://docs.inspireui.com/fluxstore/multi-language/

**Comment by smark98** [comment]
> @smark98 - could you try this guide https://docs.inspireui.com/fluxstore/multi-language/
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/c1f5c35bdee2cf5a71b0e35ef38becdf8ec89d72/68747470733a2f2f646f63732e696e737069726575692e636f6d2f696d616765732f6d6574612f47686f73742d446f63732e6a7067">InspireUI Document**[FluxStore - Universal mobile commerce Flutter app for Magento, WooCommerce and Opencart](https://docs.inspireui.com/fluxstore/multi-language/)**Fluxstore is universal app that fully integration with the Woocommerce, Mangeto and Opencart

Hi, yes I tried but as I said I get error when try to generate the langua
![Képernyőfotó 2020-05-26 - 15 05 04](https://user-images.githubusercontent.com/37720115/82904214-6f3b7380-9f62-11ea-8358-0ba355b9c8b3.png)
ge.

**Comment by minhcasi** [comment]
@smark98 - you could try to re-install flutter

Also, try to check via `flutter doctor` - it seems issue caused from your Flutter SDK

**Comment by smark98** [comment]
It is not work. Same issue.

![Képernyőfotó 2020-05-28 - 17 14 03](https://user-images.githubusercontent.com/37720115/83159916-d5f99200-a106-11ea-95fb-e4f2363e31a0.png)

**Comment by minhcasi** [comment]
@smark98 - there may be syntax issue with your _hu language, could you attache the `intl_hu.arb` here - thank

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
