### ISSUE TITLE
[ListApp] App not displaying the listing only post

### ISSUE THREAD

**Issue by jafxdesign** [inspireui/support#342]
**Mandatory Info (please complete the following information):**
 - Product: [ListApp]
-  Purchased Code: 8215e657-117a-4eae-a1dd-37dc6fb735bb

**Describe the issues**
The app is not loading the listings just the post alone check the screenshots
![empty-content](https://user-images.githubusercontent.com/12873759/53503908-499a9280-3ab1-11e9-8bf4-2d1fa08948a9.jpeg)
![blog-content](https://user-images.githubusercontent.com/12873759/53503930-515a3700-3ab1-11e9-82a7-5aa309beaa8b.jpeg)

**Comment by thangvo9x** [comment]
Hi. Thanks for your purchase. Can you send me your AppConfig file, plz ? 
for checking . Thanks

**Comment by jafxdesign** [comment]
[AppConfig.json.zip](https://github.com/inspireui/support/files/2913800/AppConfig.json.zip)

**Comment by thangvo9x** [comment]
I can't see any listing from your site here
https:/yourdomain/wp-json/wp/v2/job_listing
Please check Document Guide or you can use Cebuilder to config it correctly.
https://inspireui.github.io/listapp/docs/quickstart
