### ISSUE TITLE
[FluxStore MV] Checkout returns Login screen

### ISSUE THREAD

**Issue by aishema2000** [inspireui/support#3420]
Dear support, I tell you this with all my respect, but This is the second month since I bought Fluxstore multivendor

**1.** I am using  fluxstore mutli vendor 1.7.3. But there is a problem, 

Users browse for products and add them to cart =>They  Click on Checkout button ==> They go to Login screen ==> After login successfully they are taken back to the cart. ==> When they click on checkout button the apps takes them again to Login screen, again and again.

**THe debug console shows this:** SAYING "SCREENNAME NULL"

![image](https://user-images.githubusercontent.com/15066381/82911655-76677f00-9f6c-11ea-8bf4-8c43fbd85d9a.png)

**2.** Your Demo app (1.7.3) available on CodeCanyon does not work, it gives several exceptions errors, so we don't have any reference in case something goes wrong.

**3.** SMS LOGIN takes very longtime (about 1 to 2 minutes) after putting phone code.

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by aishema2000** [comment]
I saw somewhere you were working on 1.7.4 version, maybe it will solve many of our issues. When can we expect it? Thx

**Comment by philipvu30** [comment]
Hi,

1. Add this line in the file lib/screens/cart/my_cart.dart:  
![image](https://user-images.githubusercontent.com/54442328/83109974-873efe80-a0ec-11ea-8de1-f649025891bc.png)
2. You can submit to our form [here](http://verify.inspireui.com/) to gain access to our latest version.
3. Are you testing it on real phone number or a testable fictional number?

**Comment by aishema2000** [comment]
Dear @philipvu30 thank you for your help. 
1. It works now.
2. I have access to Gitlab already. Waiting for the 1.7.4 version
3. I am testing on real phone

**4. NEW ISSUE: User can not SIGN UP. App says "Please agree with terms" even if "I agree with privacy policy" is checked. WHAT'S THE SOLUTION?**

**Comment by aishema2000** [comment]
Issue N 4 is also solved. I got solution from here: #3351

**Comment by philipvu30** [comment]
Hi,

- Issue number 2: What are exactly the errors?
- Issue number 3: According to this [document](https://firebase.google.com/docs/auth/android/phone-auth#create-a-phoneauthcredential-object), you cannot request an OTP on a phone number for a short period of time after successfully logged in.

>To prevent abuse, Firebase enforces a limit on the number of SMS messages that can be sent to a single phone number within a period of time. If you exceed this limit, phone number verification requests might be throttled. If you encounter this issue during development, use a different phone number for testing, or try the request again later.

**Comment by minhcasi** [comment]
'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
