### ISSUE TITLE
FluxStore Change the color in the Setting area

### ISSUE THREAD

**Issue by yosefasad** [inspireui/support#3421]
The main color is changed to red in config.json

When I scroll down , The green color is shown up ... 
How can I change the green color to red or blue ?

![11](https://user-images.githubusercontent.com/23431061/82906271-a7947f00-9f6d-11ea-8a68-3bdc3f20db4f.jpg)

<img width="787" alt="Screen Shot 1441-10-03 at 4 27 30 PM" src="https://user-images.githubusercontent.com/23431061/82906388-d6aaf080-9f6d-11ea-824e-69dcdd815ddd.png">

**Comment by minhcasi** [comment]
@yosefasad - pls help to fix by edit this file 
```
SliverAppBar(
            backgroundColor: kBackgroundAppBar ?? Theme.of(context).primaryColor,
```

<img width="1026" alt="Screen Shot 2020-05-27 at 08 11 38" src="https://user-images.githubusercontent.com/1459805/82965219-b290f300-9ff1-11ea-99f4-1d2675b9702d.png">

**Comment by yosefasad** [comment]
I tried the this solution ...it did not work .... 

I made  clean flutter ... wipe data of the emulator .... 
then flutter run ....still it is not working 

<img width="970" alt="Screen Shot 1441-10-04 at 4 35 43 AM" src="https://user-images.githubusercontent.com/23431061/82966460-8ebeb480-9fd3-11ea-9e31-2ed08bb46f3c.png">
