### ISSUE TITLE
FluxBuilder purchase code issue

### ISSUE THREAD

**Issue by anurag-cser** [inspireui/support#3422]
I registered my purchase code with the fluxbuilder for the website https://tiagabasket.com.
However, my client decided to change the domain to https://tiagago.com.  Now the URL https://tiagabasket.com is the parked domain.

Now I am not able to access the fluxbuilder as it says that my purchase code is associated with https://tiagabasket.com

What should I do? @minhcasi

**Comment by minhcasi** [comment]
@anurag-cser - there is the Reset Verify from the Build menu from the Fluxbuilder, you could try to reset one-time to switch new website, or you could send us your purchase code license to reset - pls send to support@inspireui.com - thank you!
