### ISSUE TITLE
 Fluxstore Caching is not working

### ISSUE THREAD

**Issue by annaraiders** [inspireui/support#3423]
Step 1 (require): detail issues and screenshots
I have uploaded the config_en.json file to mstore api which is different from local config file.
The UI doesn't change as made in the new config_en.json file in the wp admin when loading the app.
WP Rest cache is active, mstore api installed

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

**Comment by minhcasi** [comment]
@annaraiders - could i know if you have enabled the `isCaching` from the config file - https://docs.inspireui.com/fluxstore/performance/

**Comment by annaraiders** [comment]
@minhcasi - I have set "isCaching": true, in general.dart . I have installed the app in different devices still ui doesn't change as uploaded in config_en.json file in website

**Comment by minhcasi** [comment]
@annaraiders - would you mind to share your admin login to support@inspireui.com - we will help for investigating - thanks

**Comment by aishema2000** [comment]
Please share the solution here, I have similar issue too, I am interested to see the fix.

**Comment by minhcasi** [comment]
@annaraiders - i can see your caching is working fine - https://www.mobileraja.in/wp-json/wc/v2/flutter/cache?consumer_key=ck_6d1d6d07a119f40d913c99076e5c3017a6b5b7ec&consumer_secret=cs_62a91db6cec3bcf47d726270f4f343befa8c08f7 

You could try to go to this link for checking https://www.mobileraja.in/wp-admin/options-general.php?page=wp-rest-cache&sub=endpoint-api

Make sure to clean up the REST API cache every time you upload a new config file.

<img width="1110" alt="Screen Shot 2020-05-29 at 13 59 03" src="https://user-images.githubusercontent.com/1459805/83230770-90939e00-a1b4-11ea-9498-d7e2be1158cf.png">

**Comment by annaraiders** [comment]
@minhcasi The cache is working but the new issue is adding category list .
For eg : adding below code doesn't work
{
      "name": "Headphone",
      "layout": "threeColumn",
      "category": 53
}

**Comment by minhcasi** [comment]
@minhtruong315 - pls help to check this caching issue

**Comment by minhcasi** [comment]
@annaraiders - it's working fine with our checking, could you try to clean up the Rest API cache every time you update the config json file - thank you!

**Comment by minhcasi** [comment]
@annaraiders - we confirmed to fix this issue on latest `1.7.5` - please help to keep update this version today - thank you!

**Comment by aishema2000** [comment]
When and where is 1.7.5 being available for download?
