### ISSUE TITLE
Products > SEE ALL, Display "No Product"

### ISSUE THREAD

**Issue by ravindam** [inspireui/support#3424]
i'm using fluxstore pro with opencart.
 Products > SEE ALL, Display "No Product"
Filter > 'BY PRICE' 0.00 - 500.00 Change to 0.00-0.00 and SEE ALL Items are display how to fix this ?
how to remove filter

**Comment by minhcasi** [comment]
@ravindam - could I know which the version you are using for test, could you share the screenshot issue, please? Thank you!

**Comment by ravindam** [comment]
version - 
FluxStore Pro 1.7.3 

![Screenshot_2020-05-27-10-01-19-127_com inspireui fluxstore](https://user-images.githubusercontent.com/63419889/82979223-2805bf00-a004-11ea-8953-6ea9f6d62dcd.jpg)

![Screenshot_2020-05-27-10-01-43-702_com inspireui fluxstore](https://user-images.githubusercontent.com/63419889/82979239-305dfa00-a004-11ea-8565-4348619d590f.jpg)

***************************************************
How to Change Price and Item Descriptions font and font size

![Screenshot_2020-05-27-10-02-58-921_com inspireui fluxstore](https://user-images.githubusercontent.com/63419889/82979246-348a1780-a004-11ea-9ceb-b50aa2e4dc74.jpg)

**Comment by minhcasi** [comment]
@ravindam - try to use latest `1.7.4` to fix this issue - thank you!

**Comment by ravindam** [comment]
sum code a edit in my old version 1.7.3 how can i update it 1.7.4

**Comment by ravindam** [comment]
we update 1.7.3 to 1.7.4 but same result  
how to fix this problem

**Comment by minhcasi** [comment]
@trunghieuvn - pls help to check this filter issue - thanks

**Comment by ravindam** [comment]
Pls Help i well send the video in issue
open  Products and click SEE ALL on category list display as No Product . 
but i select category (ex. Bed, Bicycle, ...) display all product in correctly.
i want to display all sub category under SEE ALL.
we using OpenCart Version 3.0.3.2

https://envl.app/ravindam/bqikU8!Lt8jxtadfrRcLHj8

**Comment by trunghieuvn** [comment]
> Pls Help i well send the video in issue
> open Products and click SEE ALL on category list display as No Product .
> but i select category (ex. Bed, Bicycle, ...) display all product in correctly.
> i want to display all sub category under SEE ALL.
> we using OpenCart Version 3.0.3.2
> 
> https://envl.app/ravindam/bqikU8!Lt8jxtadfrRcLHj8
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/9691d4241d64fd0823fc5a04e374442722048950/687474703a2f2f656e76656c6f702e6170702f696d616765732f6f672d696d6167652d646f776e6c6f61642e706e67">**[Download file - Envelop](https://envl.app/ravindam/bqikU8!Lt8jxtadfrRcLHj8)**Download this file shared with Envelop

Hi @ravindam 
I have tested your API, something is not right on your server. Please check again. This is the api that is called when selecting "SEE ALL" that I check.

```
http://lakmuthu.dyndns.org/opencart//index.php?route=extension/mstore/product&limit=20&page=1&lang=en&category=62
```

![image](https://user-images.githubusercontent.com/19247680/83218872-1d306300-a199-11ea-8611-1fcf40c04add.png)

**Comment by ravindam** [comment]
Thanks for helping.
your information is very helpful for fixing this error.
it is a opencart extension error i well fix it.
thanks for great response.

**Comment by minhcasi** [comment]
@ravindam - We're glad that it help, please give us some feedback/rating to this page https://codecanyon.net/downloads  if the product is helpful for your business, we are working hard to update more awesome and powerful features on next coming version release. Let us know if you have any feedback. Thank you very much 😊

**Comment by codex-pro** [comment]
@ravindam  how did you fixed the error i m getting bug
