### ISSUE TITLE
bitcode

### ISSUE THREAD

**Issue by miskayapp** [inspireui/support#3426]
Step 1 (require): detail issues and screenshots

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.
![Screen Shot 2020-05-26 at 11 47 56 PM](https://user-images.githubusercontent.com/64660378/82961377-1812be80-9fb5-11ea-94cd-62a3623d85b8.png)
com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@miskayapp - we have replied on your ticket https://github.com/inspireui/fluxbuilder/issues/92

Please also try to contact us by one ticket/email, instead of sending a bunch of spam email https://tppr.me/5wf1g
