### ISSUE TITLE
Ref to :   FluxStore Change the color in the Setting area - #3421

### ISSUE THREAD

**Issue by yosefasad** [inspireui/support#3429]
@minhcasi minhcasi
I tried the your solution  ...it did not work .... 

I made  clean flutter ... wipe data of the emulator .... 
then flutter run ....still it is not working 

<img width="970" alt="Screen Shot 1441-10-04 at 4 35 43 AM" src="https://user-images.githubusercontent.com/23431061/82966460-8ebeb480-9fd3-11ea-9e31-2ed08bb46f3c.png">

**Comment by minhcasi** [comment]
ah sorry, try this one
```
backgroundColor: Theme.of(context).primaryColor,
```

**Comment by yosefasad** [comment]
it works perfectly

Thank you very much for your support
