### ISSUE TITLE
[MStore] issue with Custom Arabic font

### ISSUE THREAD

**Issue by yosefasad** [inspireui/support#343]
1.  When I install custom arabic font, which include arabic numbers and make it default, the arabic number is shown in some location(as Homepage) as english number and other location (Product pages is shown in arabic. How to solve this issue?

2. . When I transfer back from Arabic Language to english language from the menu, the arabic numbers still shown in product page , How to solve this issue?

3. The arabic font itself is not installed correctly everywhere, which is the most important :) 

The Arabic font type used is      GEDinarOne-Medium.ttf

Please check the link below which show where the issues are.
https://imgur.com/a/jBjwW8p

I hope I made it clear as possible

**Comment by yosefasad** [comment]
More places where Arabic font is not installed . 
https://imgur.com/a/SDkJsBT

Best Regards

**Comment by luyx2412** [comment]
Hi @yosefasad You should be looking for the Text which used default font or another font, and change it. Currently we did not support change font one time.

Thanks

**Comment by yosefasad** [comment]
thank you , and best regards
