### ISSUE TITLE
the same issue of #3402

### ISSUE THREAD

**Issue by hssinaman** [inspireui/support#3430]
Step 1 (require): let us know your detail issues & screenshots, what is the product name and version?

Hi, we have the same issue of this 
https://github.com/inspireui/support/issues/3402

we have tried all replies but still not working .. can you help please 

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by hssinaman** [comment]
can you help please ?

**Comment by hssinaman** [comment]
we enabled the SSL and we did also all instructions that you have provided on 
https://github.com/inspireui/support/issues/3402
 but the problem no't resolved..

awaiting for your quick help please 

thanks

**Comment by hssinaman** [comment]
can you help please ??

**Comment by kvt0012** [comment]
Dear sir, I see that you have the same issue with #3402, please follow this ticket and my brother will help you fix it. Thank you

**Comment by kvt0012** [comment]
@philipvu30  This user has same issue with #3402, please help him, thank you :D

**Comment by philipvu30** [comment]
Solved.
