### ISSUE TITLE
<Multivendor> Get suck at change package name

### ISSUE THREAD

**Issue by Cheewingtan** [inspireui/support#3431]
Step 1 (require): let us know your detail issues & screenshots, what is the product name and version?
HI on this issue https://github.com/inspireui/support/issues/3156 
the article that you send to me
https://medium.com/@skyblazar.cc/how-to-change-the-package-name-of-your-flutter-app-4529e6e6e6fc
I follow this article step but confuse on step 2
<img width="1440" alt="Screenshot 2020-05-27 at 4 28 09 PM" src="https://user-images.githubusercontent.com/11556877/82996719-fb6b9a80-a037-11ea-9624-65e5e80b4549.png">
because when I change the directory structure from it doesn't work for me it will auto create another io/flutter/plugin folder and will occur this error
<img width="1440" alt="Screenshot 2020-05-27 at 4 29 38 PM" src="https://user-images.githubusercontent.com/11556877/82997169-9d8b8280-a038-11ea-8d44-39fd554ef0e3.png">

<img width="1440" alt="Screenshot 2020-05-27 at 4 30 52 PM" src="https://user-images.githubusercontent.com/11556877/82996884-38379180-a038-11ea-86c0-5bcefb5c6ab7.png">

by the way the video you send to me 
https://www.youtube.com/watch?v=3DYdBBtvAbg
is not work to me also 
can you help me with this ? thanks 

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by Cheewingtan** [comment]
btw and how about this issue? https://github.com/inspireui/support/issues/3156
?

**Comment by minhcasi** [comment]
Try to rename this folder instead - we already explain through the documents - https://docs.inspireui.com/fluxstore/delivery-android/#12-change-the-app-bundle-id-package-name

<img width="955" alt="Screen Shot 2020-05-28 at 07 47 42" src="https://user-images.githubusercontent.com/1459805/83085925-85a71380-a0b7-11ea-92cf-1a06944fd1d8.png">

Pls note the android project is base on `Kolint` on the latest release

**Comment by Cheewingtan** [comment]
> Try to rename this folder instead - we already explain through the documents - https://docs.inspireui.com/fluxstore/delivery-android/#12-change-the-app-bundle-id-package-name
> 
> <img alt="Screen Shot 2020-05-28 at 07 47 42" width="955" src="https://user-images.githubusercontent.com/1459805/83085925-85a71380-a0b7-11ea-92cf-1a06944fd1d8.png">
> 
> Pls note the android project is base on `Kolint` on the latest release
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/c1f5c35bdee2cf5a71b0e35ef38becdf8ec89d72/68747470733a2f2f646f63732e696e737069726575692e636f6d2f696d616765732f6d6574612f47686f73742d446f63732e6a7067">InspireUI Document**[FluxStore - Universal mobile commerce Flutter app for Magento, WooCommerce and Opencart](https://docs.inspireui.com/fluxstore/delivery-android/)**Fluxstore is universal app that fully integration with the Woocommerce, Mangeto and Opencart

thanks it work to me and I follow this https://github.com/inspireui/support/issues/3151
I successfully get the SHA-1 and SHA-256 key and connecting the app ,but it take me a lot of time to logging in see the pic
<img width="401" alt="Screenshot 2020-05-28 at 11 47 01 AM" src="https://user-images.githubusercontent.com/11556877/83097272-46d68500-a0da-11ea-9293-1f7106ff3e4a.png">
loading this part already 30mins but still loading , SMS sign in also ,after typing the verify code it keep loading as well

**Comment by Cheewingtan** [comment]
> Try to rename this folder instead - we already explain through the documents - https://docs.inspireui.com/fluxstore/delivery-android/#12-change-the-app-bundle-id-package-name
> 
> <img alt="Screen Shot 2020-05-28 at 07 47 42" width="955" src="https://user-images.githubusercontent.com/1459805/83085925-85a71380-a0b7-11ea-92cf-1a06944fd1d8.png">
> 
> Pls note the android project is base on `Kolint` on the latest release
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/c1f5c35bdee2cf5a71b0e35ef38becdf8ec89d72/68747470733a2f2f646f63732e696e737069726575692e636f6d2f696d616765732f6d6574612f47686f73742d446f63732e6a7067">InspireUI Document**[FluxStore - Universal mobile commerce Flutter app for Magento, WooCommerce and Opencart](https://docs.inspireui.com/fluxstore/delivery-android/)**Fluxstore is universal app that fully integration with the Woocommerce, Mangeto and Opencart

I saw your package name sometime is com.inspireui.fluxstore ans sometime is com.inspireui.fluxstore.vendor ,but all I change to my package name com.lokein.store only not included .vendor is that the problem cause this ?

**Comment by minhcasi** [comment]
That could be the problem, you should rename the folder as well `com/lokein/store/MainActivity.kt` - otherwise, it will be crash

**Comment by Cheewingtan** [comment]
> That could be the problem, you should rename the folder as well `com/lokein/store/MainActivity.kt` - otherwise, it will be crash

how about the issue #3156 ?I still can't fix this

**Comment by minhcasi** [comment]
the issue from ticket 3156 is caused by missing config from the json file, please try to add

```
  "Setting": {
    ...
    "StickyHeader": true
```

We will update new release version shortly on today

**Comment by minhcasi** [comment]
Please try with latest `1.7.4` to fix this issue - thank you!

**Comment by Cheewingtan** [comment]
> Please try with latest `1.7.4` to fix this issue - thank you!

yes, it solves me this , but get another issue that the app didn't show all my product , it seem like API connect problem , that 1.7.3 version didn't have 
<img width="367" alt="Screenshot 2020-06-01 at 10 58 35 AM" src="https://user-images.githubusercontent.com/11556877/83372178-2cace780-a3f7-11ea-9feb-8833ff656d1b.png">
and my API key sure is work on 1.7.3 version
