### ISSUE TITLE
eroor

### ISSUE THREAD

**Issue by meeraforefront** [inspireui/support#3432]
Step 1 (require): let us know your detail issues & screenshots, what is the product name and version?
i purchased Fluxstore Multi Vendor WooCommerce project from evento, now the issue is products list not showing in product page,but its running. yesterday suddenly i got a new issue too.
"""Compiler message:
/C:/Users/hbsgl/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/extended_image-0.7.1/lib/src/gesture/extended_image_slide_page_route.dart:333:9: Error: No named parameter with the name 'animation'.
        animation: animation,
        ^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/cupertino/route.dart:435:3: Context: Found this candidate, but the arguments don't match.
  CupertinoFullscreenDialogTransition({
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/Users/hbsgl/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/rate_my_app-0.5.0+3/lib/src/dialogs.dart:245:17: Error: No named parameter with the name 'onRatingChanged'.
                onRatingChanged: (rating) {
                ^^^^^^^^^^^^^^^
/C:/Users/hbsgl/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/smooth_star_rating-1.1.1/lib/smooth_star_rating.dart:24:3: Context: Found this candidate, but the arguments don't match.
  SmoothStarRating({
  ^^^^^^^^^^^^^^^^
/C:/Users/hbsgl/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_svg-0.15.0/lib/src/picture_stream.dart:92:3: Error: The superclass, 'Diagnosticable', has no unnamed constructor that takes no arguments.
  PictureStream();
  ^^^^^^^^^^^^^
/C:/Users/hbsgl/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_svg-0.15.0/lib/src/picture_stream.dart:192:16: Error: The superclass, 'Diagnosticable', has no unnamed constructor that takes no arguments.
abstract class PictureStreamCompleter extends Diagnosticable {
               ^

Compiler message:
/C:/Users/hbsgl/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/extended_image-0.7.1/lib/src/gesture/extended_image_slide_page_route.dart:333:9: Error: No named parameter with the name 'animation'.
        animation: animation,
        ^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/cupertino/route.dart:435:3: Context: Found this candidate, but the arguments don't match.
  CupertinoFullscreenDialogTransition({
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/Users/hbsgl/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/rate_my_app-0.5.0+3/lib/src/dialogs.dart:245:17: Error: No named parameter with the name 'onRatingChanged'.
                onRatingChanged: (rating) {
                ^^^^^^^^^^^^^^^
/C:/Users/hbsgl/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/smooth_star_rating-1.1.1/lib/smooth_star_rating.dart:24:3: Context: Found this candidate, but the arguments don't match.
  SmoothStarRating({
  ^^^^^^^^^^^^^^^^
/C:/Users/hbsgl/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_svg-0.15.0/lib/src/picture_stream.dart:92:3: Error: The superclass, 'Diagnosticable', has no unnamed constructor that takes no arguments.
  PictureStream();
  ^^^^^^^^^^^^^
c:\b\s\w\ir\cache\builder\src\third_party\dart\runtime\vm\thread_pool.cc: 341: error: Could not start worker thread: result = 22.
version=2.8.2 (stable) (Mon May 11 15:06:42 2020 +0200) on "windows_x64"
pid=10260, thread=13708, isolate=(null)(0000000000000000)
isolate_instructions=0, vm_instructions=7ff70e781010
  pc 0x00007ff70e90e17b fp 0x000000c2e77ff260 Unknown symbol
  pc 0x0000024dc2842e60 fp 0x000000c2e77ff550 Unknown symbol
-- End of DumpStackTrace""" 
 this is the error showing in my project. but my project location is  D:\Fluxstore\Autowelkin\resource.........
kindly please give a solution.

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@meeraforefront - pls try to verify your purchase before posting new ticket - thanks
