### ISSUE TITLE
Fluxstore Pro - Opencart Options

### ISSUE THREAD

**Issue by alicankarakus** [inspireui/support#3433]
Hi again.. 

i have a two problems.
Firstly : the picture is not fully visible.

![image](https://user-images.githubusercontent.com/6725793/83003853-90aa6700-a017-11ea-818b-2b02ea868ff3.png)

And then:  I don't want to show option prices in parentheses.

![image](https://user-images.githubusercontent.com/6725793/83004037-ce0ef480-a017-11ea-80ab-df3667f6e90c.png)

and finally : I want to make it mandatory. Do not buy without choosing an option.

![image](https://user-images.githubusercontent.com/6725793/83004388-47a6e280-a018-11ea-8868-6a37be1311c6.png) 
![image](https://user-images.githubusercontent.com/6725793/83004434-58efef00-a018-11ea-9c5c-6dfb1838242f.png)

**Comment by minhcasi** [comment]
1. pls try to adjust this setting to update the image on product detail to fit with your image - https://tppr.me/H8AWC - you could also try to change the `fit` property https://tppr.me/vlxv7

2. try to edit this text - https://tppr.me/Qlw6n 

Let us know your checking

**Comment by alicankarakus** [comment]
I changed but nothing has changed.

![image](https://user-images.githubusercontent.com/6725793/83113994-07576b00-a0d1-11ea-8510-3f70506ab576.png)
![image](https://user-images.githubusercontent.com/6725793/83114019-13dbc380-a0d1-11ea-88c1-658294e0c9ed.png)

**Comment by minhcasi** [comment]
Sorry, try to edit on the same file, under InputRadio widget - thanks

<img width="1057" alt="Screen Shot 2020-05-29 at 09 11 46" src="https://user-images.githubusercontent.com/1459805/83213486-6cbc6200-a18c-11ea-8fa2-0512c6718436.png">

**Comment by alicankarakus** [comment]
It fixed. Thanks..

How can I make the option selection mandatory? Do not add to the basket without choosing an option.

**Comment by alicankarakus** [comment]
How can i add background color? 
![image](https://user-images.githubusercontent.com/6725793/83230655-d0e22480-a192-11ea-9041-88063141fdf5.png)

**Comment by alicankarakus** [comment]
How can I add app title? 
to the right of the icon?

![image](https://user-images.githubusercontent.com/6725793/83246402-bd42b800-a1aa-11ea-80de-1cec5f2d6e9c.png)

**Comment by minhcasi** [comment]
@alicankarakus - the background issue on the sticky option will be fixed on next release.

We are not sure about the app title on the second screenshot, it seems to depend on your Android OS

**Comment by alicankarakus** [comment]
can you test this apk for app title?

https://gofile.io/d/3wol4z

**Comment by minhcasi** [comment]
We wanted to thank you for your patience during this busy time. We currently have reduced staff and a significantly higher volume of inquiries. We’re working as hard as we can to get to your request as soon as possible.

We sincerely apologize for the delay and hope you’re staying safe.

Could you help to share the source to support@inspireui.com so that i can check this Title issue - thanks
