### ISSUE TITLE
 issue of #3268 not solved until now

### ISSUE THREAD

**Issue by limitlessfirm** [inspireui/support#3436]
[Fluxstore] - errors when i make New Account  #3268
and i sent the whole project to your email (khiem@inspireui.com) as you mention
I did not receive and feedback from you until now

**Comment by minhcasi** [comment]
@limitlessfirm 
We wanted to thank you for your patience during this busy time. We currently have reduced staff and a significantly higher volume of inquiries. We’re working as hard as we can to get to your request as soon as possible.
We sincerely apologize for the delay and hope you’re staying safe.

@kvt0012 - pls help to check this ticket

**Comment by kvt0012** [comment]
Sorry sir because I can't see your response after a while, so I close this ticket. 
Please keep it update, thank you 
Can you comment your email here ? Thank you

**Comment by limitlessfirm** [comment]
The Email : mb@limitlessfirm.com

**Comment by kvt0012** [comment]
Ok sir, I will check tomorrow.  Thank you

**Comment by kvt0012** [comment]
I'm sorry, sir, I have not received any email from mb@limitlessfirm.com 
Please send me again, thank you

**Comment by limitlessfirm** [comment]
I sent the whole project to this email (khiem@inspireui.com) again

**Comment by kvt0012** [comment]
It will be released on next version, thank you
