### ISSUE TITLE
First time login & InStock count  Errors

### ISSUE THREAD

**Issue by hinai** [inspireui/support#3437]
Step 1 (require): let us know your detail issues & screenshots, what is the product name and version?

1)My app require login ( IsRequiredLogin =true) but when I install the app first time and logged in the error appear as shown, but when I close the app and reopen it again the error gone.How to fix the problem for the first login ??

![img1](https://user-images.githubusercontent.com/4161259/83012460-7dee5d00-a02c-11ea-8b7c-411aa2eb0556.jpeg)

2) when I purchase Item the (Instock) number doesn't update . It show decrease 
![img2](https://user-images.githubusercontent.com/4161259/83012816-fead5900-a02c-11ea-80c3-e493d02646be.jpeg)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

A)Done

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@hinai - confirm this is a bug - we have fixed it on latest `1.7.5` - it will be ready in 1-2 days

We sincerely apologize for the delay and hope you’re staying safe.

**Comment by hinai** [comment]
thanks @minhcasi  waiting for your  updates.
hope you'r staying safe also .wish you all the best

**Comment by minhcasi** [comment]
@hinai - the latest version is ready to download on our Gitlab - we will add new package release on Envato soon, hope you are staying safe as well 😊

Let us know once your app goes live, please also help us to give some feedback rating to http://codecayon.net/downloads - appreciated for your help !

**Comment by hinai** [comment]
Thanks @minhcasi  , but could you show me how to get the code in gitlab . Couldn't find it. 

Thanks

**Comment by minhcasi** [comment]
@hinai - pls send your submission to http://gitlab.inspireui.com - thanks

**Comment by minhcasi** [comment]
Please let us know if you have any further issue, feel free to reopen the ticket - thank you!

**Comment by hinai** [comment]
sure, Thanks A lot
