### ISSUE TITLE
[FluxStore Pro] Some Problems

### ISSUE THREAD

**Issue by kumsalajans** [inspireui/support#3438]
### ** 1) White color on white background

Same problem exists other pages 

Problem iOs, Android

background of the clock is white, it is recording background red

Video 

[RPReplay_Final1590577859.zip](https://github.com/inspireui/support/files/4688351/RPReplay_Final1590577859.zip)

### 2) **Multi variant is fixed, but one variant same problem**

Fourth Issue 

https://github.com/inspireui/support/issues/3167

### 3) button is not working when kCartDetail["minAllowTotalCartValue"] is determined but slider is working 

I can slide past the basket

While this is being corrected, it needs to be checked again when the quantity is changed or when the product is deleted.

### 4) on the review tab of the basket when I complete the minimum amount, This action needs to be checked again when I change the number of products or delete products.  
Making changes here is actually a problem in terms of options such as free shipping.

**Comment by philipvu30** [comment]
Hi,

Thanks for listing down all the bugs. They are fixed and will be included in the next update except issue number 2 since I'm not sure it is fixed or not.

**Comment by EmreCaliskan1** [comment]
issue number 2, fixed ?

**Comment by kumsalajans** [comment]
issue number 2, fixed ?

**Comment by kumsalajans** [comment]
please do not close the problem without fully resolving
