### ISSUE TITLE
Cannot Login Gmail

### ISSUE THREAD

**Issue by harjono-flux** [inspireui/support#3439]
Before i change the app bundle id, everything is OK. After i change the bundle ID, i cannot Login with Gmail. Im trying my best, to follow the tutorial, but still cant be login. Plis help, where im missing. Already do this

![WhatsApp Image 2020-05-27 at 08 05 34 (1)](https://user-images.githubusercontent.com/64935574/83029634-739c8500-a065-11ea-86f5-464355e2531f.jpeg)
![Screen Shot 2020-05-27 at 21 50 43](https://user-images.githubusercontent.com/64935574/83029268-14d70b80-a065-11ea-8612-6a79751c2fd4.png)
![Screen Shot 2020-05-27 at 21 51 12](https://user-images.githubusercontent.com/64935574/83029283-1accec80-a065-11ea-812e-bfa80c238d97.png)
![Screen Shot 2020-05-27 at 21 48 32](https://user-images.githubusercontent.com/64935574/83029311-24eeeb00-a065-11ea-9e2d-8803e6218be8.png)
![Screen Shot 2020-05-27 at 21 46 38](https://user-images.githubusercontent.com/64935574/83029335-2a4c3580-a065-11ea-9c72-60de878a7b23.png)

**Comment by minhcasi** [comment]
@harjono-flux - try to follow the solution on this ticket #3151

**Comment by harjono-flux** [comment]
Sory, this is first time i want register the app in play store. And let me make make it sequential

Im following tutorial by you https://medium.com/@inspireui/setup-google-login-for-flutter-apps-fedc58a490b8

and i succes to connect firebase with my app. this is the screen shoot. Success sent the cloud messaging, but still cant login by gmail.
https://user-images.githubusercontent.com/64935574/83029283-1accec80-a065-11ea-812e-bfa80c238d97.png
![WhatsApp Image 2020-05-29 at 08 22 12](https://user-images.githubusercontent.com/64935574/83207522-fae11a00-a185-11ea-9bd9-ba3094dbceca.jpeg)

After that, i trying tutorial by Xsamsir Youtube
1. to get SHA, i not use command keytool, because error in me, so i use SHASUM command, and its works too get SHA1 and SHA256. Put it in firebase. Test the connection, it succes sent cloud message
![Screen Shot 2020-05-29 at 08 49 02](https://user-images.githubusercontent.com/64935574/83208913-87410c00-a189-11ea-8e1f-3f75d9c850fe.png)

2. next, register in facebook developer, but im waiting in this section. It is true, for pass this, we must posting our apps in google play store first? 
![Screen Shot 2020-05-29 at 08 05 31](https://user-images.githubusercontent.com/64935574/83206308-2d3d4800-a183-11ea-97ac-8997dcae7720.png)

**Comment by minhcasi** [comment]
@harjono-flux - yes, you need to post your app on Google play store to activate the Live mode on Facebook, otherwise use the Development option - thank you!
