### ISSUE TITLE
Opencart Admin Not Change Language After Module Installation

### ISSUE THREAD

**Issue by ahmadali86** [inspireui/support#3440]
After installing Opencart module for FluxPro , the default language of the admin panel turned to english only and it does not change to any other language even I choose it from Settings as Admin Control Panel Default Language.

#3237

**Comment by minhtruong315** [comment]
Hi @ahmadali86 can u explain your issue clearly?

**Comment by ahmadali86** [comment]
After installing the Opencart module for FluxPro,  the Admin control panel of Opencart changed to English instead of Arabic and when I try to change it back to Arabic again,  it stuck on English and cannot be changed to arabic

**Comment by minhtruong315** [comment]
Hi @ahmadali86 I remove mstore extension on your website. but it's same issue. I think the cause is your website. can u check it?

**Comment by ahmadali86** [comment]
After removing the mstore extension everything in website goes wrong, I can not edit products or categories and it shows things like that (text_home) next to everything in website.
<img width="826" alt="Screen Shot 2020-06-01 at 9 10 44 PM" src="https://user-images.githubusercontent.com/60041105/83445064-9a373300-a44c-11ea-990e-74d401e3775c.png">

I have another test website and tried it and the same problem happens with the extension,
What shall I do now?

**Comment by minhtruong315** [comment]
it's weird. it's working well on our website. Can u help me install other website without the mstore extension? I will help u install the mstore extension.
Thanks

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
