### ISSUE TITLE
Fluxtore

### ISSUE THREAD

**Issue by qorane099** [inspireui/support#3441]
I was following your video of managing the source using gitlab and sourcetree.

I did forked and installed sourcetree well but after l reach to emerge the your source to my source.

the sourcetree is not opening terminal to paste: https://gitlab.com/inspireui/fluxstore-multi-vendor.git

 so that l can get the lattest update of fluxstore.

i searched the issue and discover that google and develoers sites but got no answers.

please, help on this. why the sourcetree is not opening the terminal or if there another option l can continue emerging the source without using terminal if it doesnt work
<img width="1170" alt="Screenshot 2020-05-27 at 8 30 49 PM" src="https://user-images.githubusercontent.com/39888242/83037754-cc662080-a059-11ea-857b-febc3f8ecae2.png">
![IMG_20200402_201209](https://user-images.githubusercontent.com/39888242/83037793-d9830f80-a059-11ea-8f8f-0f653ca0095b.jpg)

**Comment by minhcasi** [comment]
the link https://gitlab.com/inspireui/fluxstore-multi-vendor.git our repository, your fork link will be https://gitlab.com/zammia/fluxstore-multi-vendor.git  - then you could manage your own source on that link.

**Comment by qorane099** [comment]
the terminal inside sourcetree is not working for me: 

to paste 

git remote add upstream https://gitlab.com/inspireui/fluxstore-pro
