### ISSUE TITLE
userPackagerOpts.sourceExts is not iterable

### ISSUE THREAD

**Issue by hteiktinoo** [inspireui/support#3442]
I downloaded MStore Multi Vendor.
cd mstore-mv-expo
yarn install
yarn start

then I get this error

```
yarn run v1.13.0
$ expo start
Starting project at ~/mstore-multi-vendor/mstore-mv-expo
Expo DevTools is running at http://localhost:19002
Opening DevTools in the browser... (press shift-d to disable)
userPackagerOpts.sourceExts is not iterable
TypeError: userPackagerOpts.sourceExts is not iterable
    at startReactNativeServerAsync (/@expo/xdl@57.9.12/src/Project.ts:1788:80)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I've expo installed. I can do expo init and run an empty project without this issue.

**Comment by hteiktinoo** [comment]
I tried with yarn version 1.22.4 and still get the same error

**Comment by hteiktinoo** [comment]
Any update on this?

**Comment by christky99** [comment]
same problem.... help please

**Comment by luyx2412** [comment]
HI @hteiktinoo Can you give me the node version? Please move to node 10 version which will work great.

Thanks

**Comment by hteiktinoo** [comment]
Hi My current node version is 10.13.0

**Comment by luyx2412** [comment]
HI @hteiktinoo Please read the article https://forums.expo.io/t/userpackageropts-sourceexts-is-not-iterable/35271. Maybe your expo version was old.

Thanks

**Comment by hteiktinoo** [comment]
Hi, I just installed expo cli for this project 3 days ago so it should be the latest version. it's 3.21.3 in my machine

**Comment by luyx2412** [comment]
Hi @hteiktinoo https://github.com/expo/expo-cli/issues/1019 Please try fix the issues based on the article or downgrade expo version https://forums.expo.io/t/userpackageropts-sourceexts-is-not-iterable-expo-cli-3-21-3/38287/5 

Thanks

**Comment by hteiktinoo** [comment]
Hi @luyx2412 thanks. Downgrading to 3.21.1 solve this issue.
