### ISSUE TITLE
Android Login Issue - key-debug.properties missing

### ISSUE THREAD

**Issue by yullux** [inspireui/support#3443]
Missing key-debug.properties file on my installation which means I can't follow this step:
https://youtu.be/14ALBSwvV4E?t=172

I can't get Debug signing certificate SHA-1 which is required for Android login.
<img width="1325" alt="Screenshot 2020-05-27 at 11 47 32 PM" src="https://user-images.githubusercontent.com/65419353/83079775-794d9700-a074-11ea-93fa-fd2f469bcade.png">

**Comment by minhcasi** [comment]
@yullux - pls try to check the SHA-1 login issue on this ticket #3151

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
