### ISSUE TITLE
Edit Menu - 2

### ISSUE THREAD

**Issue by harjono-flux** [inspireui/support#3444]
Hello, sory if i make much question, maybe u can add some my question in docs.customization for future customer :)

1. How to make cash on delivery payment method as native payment? Because if take from woo, is loading 1-2 second
2. How to add loading animation, when someone click the banner, and the url web is loading?
3. How to make smartchat appear at the homescreen?
4. In blog, it is true, this page cannot support html format? because in web the table is looking good, but at app blog, the table to be text code
5. Is it true, to make our instagram apprear, i put this query at config_xx.json?
 {
      "name": "Follow Us",
      "layout": "instagram",
      "tag": "hpkita.co.id"
    }
*hpkita.co.id is my instagram name

**Comment by minhcasi** [comment]
Please help to move your all questions to #3380 and also comment your all conversation to the same ticket - thank you for your time

We will upgrade the document with your suggestion ❤️
