### ISSUE TITLE
[FluxStore] Mutliple problems

### ISSUE THREAD

**Issue by kwsystems** [inspireui/support#3449]
Hi
1)	1 image: I’m trying to get rid of the blog. I want to hide.  On my config _en.json is set to false but it is still there.
2)	2 image: I have modified the settings on the FluxBuilder, on my config_en everything is fine (see image 4, it should look like that) but it is not working. It keeps showing the the same image with the lemons and some items are not hiding. I put the json on fluxbuilder and it worked but when I add it to the project it doesn’t work. I delete the page create the same one but it does not change.
3)	3 image: The share doesn’t work. How can I fix this?
4)	5 image: What it is title and default title? I think this is not for shopify. How can I get ride off.

I'm attaching my config_en

![1](https://user-images.githubusercontent.com/49769009/83106067-d0aa3200-a089-11ea-98a6-5aff518cadf7.jpg)
![2](https://user-images.githubusercontent.com/49769009/83106070-d0aa3200-a089-11ea-9f91-24b0aac4857c.jpg)
![3](https://user-images.githubusercontent.com/49769009/83106072-d0aa3200-a089-11ea-8eda-e5ab61fa53dd.jpg)
![4](https://user-images.githubusercontent.com/49769009/83106073-d142c880-a089-11ea-9dde-aaf84544ecb1.PNG)
![5](https://user-images.githubusercontent.com/49769009/83106066-d0119b80-a089-11ea-8af5-e8f289a7599c.jpg)
[config_en.txt](https://github.com/inspireui/support/files/4693622/config_en.txt)

Thanks

**Comment by kwsystems** [comment]
5. The privacy policy doesnt open profile
![Screenshot_20200528-022640 1](https://user-images.githubusercontent.com/49769009/83106629-cc324900-a08a-11ea-80fb-e34ce0928758.jpg)

6. Languages give you an error at the botton
![Screenshot_20200528-022755 1](https://user-images.githubusercontent.com/49769009/83106700-e9ffae00-a08a-11ea-991c-85812661557b.jpg)

**Comment by kwsystems** [comment]
Can someone help me please?

**Comment by luyx2412** [comment]
HI @kwsystems Sorry about reply you late.
1. In `src/common/config/general.dart` please remove this field to hide the blog
![image](https://user-images.githubusercontent.com/8909619/83324886-54366f80-a292-11ea-8de0-660cc0f44cd7.png)
2. In `src/common/constants/images.dart` line 18, please change your image in there.
![image](https://user-images.githubusercontent.com/8909619/83324968-e0489700-a292-11ea-96bf-29b77ab67cc8.png)
3. We will fix the issues in next version 1.7.5.
4. This is from shopify title, so can you check again your products.
5. Currently the privacy link to wordpress website, so you can change in `src/lib/screens/settings/settings.dart` same the screenshot
![image](https://user-images.githubusercontent.com/8909619/83325276-4fbf8600-a295-11ea-9927-f27b0f683254.png)

Thanks

**Comment by Mcrahul555** [comment]
hi am also facing the same problem with privacy policy 
the script u mentioned is not visible in the settings section
ver 1.7.4
kindly help
![privacy policy](https://user-images.githubusercontent.com/65422936/83353611-c7101b00-a364-11ea-91c4-c9598ac53e8a.jpg)

**Comment by luyx2412** [comment]
Hi @Mcrahul555 This is use for website url, so please change the code same the screenshot https://user-images.githubusercontent.com/8909619/83325276-4fbf8600-a295-11ea-9927-f27b0f683254.png . Because i saw your code not same the screenshot.

Thanks

**Comment by luyx2412** [comment]
Closed!
P/S: Feel free to reopen the issue.
