### ISSUE TITLE
[MStore Pro] Logo location and category banner

### ISSUE THREAD

**Issue by yosefasad** [inspireui/support#345]
Hello,

1. How can I move the logo in homepage to be in the middle of the header as shown in the link below
https://imgur.com/a/QSrDtZF 

2.  in MStore 3.7, when I click in the image (MEN) , the clickable image take me to the category page, But it I don't find the category banner in the upper of the page as shown in the link below
https://imgur.com/a/qRMlWCl .   How to add banner here? 

Thank you for your support

**Comment by luyx2412** [comment]
Hi @yosefasad 
- You can check in HomeScreen with `navigationOptions` which is config header.
- In `src/navigation/ListAllScreen.js` file from line `47`, please add code banner image to this file.

Thanks

**Comment by yosefasad** [comment]
** .    In src/navigation/ListAllScreen.js file from line 47, please add code banner image to this file.

return (
      <ProductList
        headerImage={
         params.config.image && params.config.image.length > 0
         ? { uri: params.config.image }
         : null
        }
        config={params.config}
        page={1}
        navigation={this.props.navigation}
        index={params.index}
        onViewProductScreen={item => navigate("DetailScreen", item)}
      />
    );

I did not know how to get the image to Header of category page, 

Need your help

**Comment by luyx2412** [comment]
Hi @yosefasad Please read the document to add the banner image to this code. https://facebook.github.io/react-native/docs/image

Thanks

**Comment by yosefasad** [comment]
Best Regards....
