### ISSUE TITLE
How to get apk for demo

### ISSUE THREAD

**Issue by macahamed** [inspireui/support#3451]
https://github.com/inspireui/support/issues/3143 my previous ticket closed
i want to test my app in my phone, you have any video please share video your document is not good for me, your video is very good please share, and how to change contact details

**Comment by minhcasi** [comment]
@macahamed - just plug your mobile device to your laptop and open the Android Studio to run it.

Could i know which screen you need to update/customize, we will add more guide to this link https://docs.inspireui.com/fluxstore/customization/ - thanks

**Comment by macahamed** [comment]
I know how to run in android app, ios only not running. ios is very important. if i buy only i can get apk

**Comment by macahamed** [comment]
i want to run ios app in my phone please help for that no need android?

**Comment by minhcasi** [comment]
@macahamed - sorry generate the final app ipa/apk is not included from our support scope. Please help to find some developer that could generate your final ios build

There is also some service like https://codemagic.io/start/ to support you build the app without having the MacOS

**Comment by macahamed** [comment]
![Screen Shot 2020-05-30 at 5 58 42 PM](https://user-images.githubusercontent.com/62641104/83345183-4aa81880-a321-11ea-8fb9-c35833d91919.png)
if i run this app it showing connect to apple id? you have any video?

**Comment by minhcasi** [comment]
@macahamed - please help to check this similar guide on Apple sign in 
`Search Results
Featured snippet from the web
Enable Sign-in with Apple capability in Xcode
Next, open up your Xcode project, select your project in the left side bar, then in the "Signing & Capabilities" tab, click "+" and select "Sign in with Apple". This capability would allow your app to use the "Sign-in with Apple" feature.
`

https://codewithandrea.com/videos/2020-01-20-apple-sign-in-flutter-firebase/

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
