### ISSUE TITLE
Changing Item Purchase Code

### ISSUE THREAD

**Issue by dextersiah** [inspireui/support#3452]
Hi, I was wondering is it possible to change my item purchase code? I tried deleting the plugin from wordpress and reinstalling but it still recognizes the previous purchase code. 

![cache](https://user-images.githubusercontent.com/46256927/83118848-7cdb2f80-a101-11ea-8087-a7319dcdf712.PNG)

**Comment by minhcasi** [comment]
@dextersiah - you could try reset it from the Fluxbuilder tools - http://fluxbuilder.com/ - select the Build menu - thank you!

**Comment by dextersiah** [comment]
@minhcasi What build menu? I only see data, design and publish.
