### ISSUE TITLE
Issue with the login 

### ISSUE THREAD

**Issue by dinkuraja** [inspireui/support#3453]
Step 1 (require): detail issues and screenshots

Hi, i did all the things mentioned in the document, but after updating to latest version of Fluxstore, the issue with woocommerce login it is not working and giving the error on sign in as well as sign up. Please find attached screen shot

Signup screen shot for sms login

https://lucsone.com/demoWeb/wordpress/wp-content/uploads/2020/05/Screenshot-2020-05-23-at-1.28.34-PM.png

Login Screen shot

https://lucsone.com/demoWeb/wordpress/wp-content/uploads/2020/05/Screenshot-2020-05-23-at-1.16.38-PM.png

for login the user name and password is the root user name and password for my wordpress web.

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

Important Note:

Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better.
If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

I have asked same question from different user name sorry there is some issue with my login to that id. I was told there that the issue is for folder structure but i just want to make clear that in previous version of the flux store it was working. Please let me know.

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as it could not be verified, please create the new one when you got enough purchased info - thank you!
