### ISSUE TITLE
[FluxStore Pro] New Google Play Requirements

### ISSUE THREAD

**Issue by bikostudio** [inspireui/support#3454]
Hi @minhcasi 

Few days ago I got an email from google console says that Google Play will apply new policies and App Requirements for both new and exciting apps. I'm sure that you got the same email too.

I just want to know is the current version of FluxStore Pro meets this new requirements? Or you will handle this in upcoming release? 

Thank you

**Comment by minhcasi** [comment]
@bikostudio - there is no problem with fluxstore app, but you need to make sure to update the Google Play service to prevent some login issue like this ticket #3151 - thank you!
