### ISSUE TITLE
OnBoarding screen keeps coming back! Fluxstore 1.7.3

### ISSUE THREAD

**Issue by aishema2000** [inspireui/support#3455]
The Onboarding screen keeps showing everytime I open the App. 

Am I wrong if i think that the onBoarding screen is supposed to come only at first App install??

How do I set it up to show only at first Install?

Step 1 (require): let us know your detail issues & screenshots, what is the product name and version?

Step 2 (require): verify license and sharing config files via this google form - http://verify.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@aishema2000 - this issue is fixed on latest code, please help to raise your all comment inside on ticket - #3420
