### ISSUE TITLE
Online linked json files language. Text of heading not loading properly

### ISSUE THREAD

**Issue by mansoor88** [inspireui/support#3456]
I linked my language-based files with online link. The following is a screenshot and content is loading from the internet. The English version is working fine. But when I switch to the Arabic version it doesn't load the Arabic heading text. Like category names I mentioned. You can see the difference in the below images.
![Screenshot_2020-05-28-10-27-20-230_com inspireui fluxstore](https://user-images.githubusercontent.com/7188395/83150203-71453400-a114-11ea-8714-fe144b1f4a05.jpg)

![Screenshot_2020-05-28-10-27-41-061_com inspireui fluxstore](https://user-images.githubusercontent.com/7188395/83150237-786c4200-a114-11ea-8db1-4334bafb8269.jpg)

my previous ticket id is
https://github.com/inspireui/support/issues/2994

**Comment by mansoor88** [comment]
This is my Arabic JSON file.

`{
  "HorizonLayout": [
    {
      "layout": "logo",
      "showMenu": true,
      "showSearch": true
    },
    {
      "layout": "category",
      "type": "icon",
      "wrap": false,
      "size": 1.0,
      "radius": 50.0,
      "items": [
        {

          "category": 50,
          "image": "https://user-images.githubusercontent.com/1459805/62820029-2e679f00-bb88-11e9-80de-fdf115cfd942.png",
          "colors": [
            "#3CC2BF",
            "#3CC2BF"
          ],
          "originalColor": false
        },
        {

          "category": 41,
          "image": "assets/icons/categories/ic_dress.png",
          "colors": [
            "#3E6AB5",
            "#3E6AB5"
          ]
        },
        {

          "category": 49,
          "image": "assets/icons/categories/ic_shorts.png",
          "colors": [
            "#53A2CC",
            "#53A2CC"
          ]
        },
        {

          "category": 51,
          "image": "assets/icons/categories/ic_glasses.png",
          "colors": [
            "#53688A",
            "#53688A"
          ]
        }
      ]
    },
    {
      "name": "عرض الأخيرة",
      "layout": "recentView"
    },
    {
      "name": "مجموعات البنات",
      "image": "",
      "layout": "twoColumn",
      "category": 49,
      "isSnapping": true
    },
    {
      "name": "مجموعات الأولاد",
      "image": "",
      "layout": "twoColumn",
      "category": 41,
      "isSnapping": true
    },
    {
      "name": "مجموعات الآباء",
      "layout": "listTile",
      "category": 51
    },
    {
      "name": "مجموعات جديدة",
      "layout": "staggered",
      "limit": 20,
      "category": 50
    }
  ],
  "Setting": {
    "MainColor": "#3FC1BE",
    "ProductListLayout": "list"
  },
  "TabBar": [
    {
      "layout": "home",
      "icon": "assets/icons/tabs/icon-home.png"
    },
    {
      "layout": "category",
      "categoryLayout": "card",
      "icon": "assets/icons/tabs/icon-category.png"
    },
    {
      "layout": "search",
      "icon": "assets/icons/tabs/icon-search.png"
    },
    {
      "layout": "cart",
      "icon": "assets/icons/tabs/icon-cart2.png"
    },
    {
      "layout": "profile",
      "icon": "assets/icons/tabs/icon-user.png"
    }
  ]
}`

**Comment by minhcasi** [comment]
@vumanhsn97 - pls help with investigating

**Comment by mansoor88** [comment]
Any comments on it?

**Comment by vumanhsn97** [comment]
@mansoor88 
Can you zip list config.json file?

**Comment by mansoor88** [comment]
> @mansoor88
> Can you zip the list config.json file?

My files are available online
http://try.talsm.com/flutter_app/config_ar.json
http://try.talsm.com/flutter_app/config_en.json

i provide direct link in path.

**Comment by vumanhsn97** [comment]
@mansoor88 
Change file in lib/models/app.dart to 
[app.dart.zip](https://github.com/inspireui/support/files/4709617/app.dart.zip)

**Comment by mansoor88** [comment]
[app.dart.zip](https://github.com/inspireui/support/files/4709647/app.dart.zip)


> @mansoor88
> Change file in lib/models/app.dart to
> [app.dart.zip](https://github.com/inspireui/support/files/4709617/app.dart.zip)

**Comment by minhcasi** [comment]
@mansoor88 - could you explain what is your remaining issue? Thanks

**Comment by mansoor88** [comment]
My files for homepage design are located on the internet. I keep them there so I can change the design without notifying the user. Everything works fine but the heading shows in Arabic is not showing in application when the language is changed. If i put the files locally like without directing to domain name. Than the text show properlly.

> @mansoor88 - could you explain what is your remaining issue? Thanks

**Comment by vumanhsn97** [comment]
Try to replace this file in lib/models/app.dart or follow this code: https://tppr.me/f05aK
[app.dart.zip](https://github.com/inspireui/support/files/4722738/app.dart.zip)

**Comment by mansoor88** [comment]
> Try to replace this file in lib/models/app.dart or follow this code: https://tppr.me/f05aK
> [app.dart.zip](https://github.com/inspireui/support/files/4722738/app.dart.zip)
> 
> > <img alt="" height="14" src="/favicon-32x32.png"> tppr.me**[Public](https://tppr.me/f05aK)**

I changed your suggested code. But it is still showing the same.


![image](https://user-images.githubusercontent.com/7188395/83655359-c501c280-a5d7-11ea-9951-8ebdec43f0da.png)


This is how my code looks like now.

if (kAppConfig.indexOf('http') != -1) {

String path = kAppConfig;
if(path.contains('.json')){
  path = path.substring(0, path.lastIndexOf('/'));
  print(path);
  path += '/config_$locale.json';
}
          // load on cloud config and update on air
          final appJson = await http.get(Uri.encodeFull(kAppConfig),
              headers: {"Accept": "application/json"});
          appConfig = convert.jsonDecode(appJson.body);
        }

**Comment by vumanhsn97** [comment]
@mansoor88 
Please check carefully. It is working well. You can see in this video: https://drive.google.com/file/d/1uoq4hfbJScwGlyHSW1hu4A7WH_NsExrr/view?usp=sharing

**Comment by vumanhsn97** [comment]
Make sure your link in general config look like this : https://tppr.me/5SaE0

**Comment by mansoor88** [comment]
> Make sure your link in general config look like this : https://tppr.me/5SaE0
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/251957eb5affaec3d57a5021b63b8d4590e71b0c/68747470733a2f2f747070722e73332e616d617a6f6e6177732e636f6d2f75706c6f6164732f35346236393862623264323539333530316630343263376232656530383038652e706e67"><img alt="" height="14" src="/favicon-32x32.png"> tppr.me**[Public - Code_2020-06-04 17-36-54](https://tppr.me/5SaE0)**

Yes it is like this and English version works perfectly as it should work. Why isn't not loading  my arabic json file?

**Comment by vumanhsn97** [comment]
Because it load from same url: http://try.talsm.com/flutter_app/config_en.json in kAppConfig. Not change to http://try.talsm.com/flutter_app/config_ar.json. You can see it in this line: https://tppr.me/XrzHd. So, You need to change config_en.json to config_ar.json by this code: https://tppr.me/Rx4TK

**Comment by mansoor88** [comment]
![Screenshot_1591357362](https://user-images.githubusercontent.com/7188395/83872576-afada500-a74b-11ea-952f-269bf46ccb5e.png)

Successfully showing arabic json file. But text showing in special characters. Can you help me in this?

**Comment by vumanhsn97** [comment]
@mansoor88 
Please check this line : https://tppr.me/TFCxy

**Comment by mansoor88** [comment]
> @mansoor88
> Please check this line : https://tppr.me/TFCxy
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/8e6af4b09486cd0d9ce3b09e62fc1fe3f9a26579/68747470733a2f2f747070722e73332e616d617a6f6e6177732e636f6d2f75706c6f6164732f34623138623634346338656161366664303136346664343535656530616161392e706e67"><img alt="" height="14" src="/favicon-32x32.png"> tppr.me**[Public - Google Chrome_2020-06-08 09-16-58](https://tppr.me/TFCxy)**

It's working fine only when I press flutter clean and run the application. When i come again it stars giving me in encrypted text.

**Comment by vumanhsn97** [comment]
@mansoor88 
Please delete your app in your devices and run again

**Comment by mansoor88** [comment]
Worked perfectly. Thanks

> @mansoor88
> Please delete your app in your devices and run again
