### ISSUE TITLE
UNABLE TO UPDATE PUB GET

### ISSUE THREAD

**Issue by Shadowji** [inspireui/support#3457]
Hi i am trying to test the demo app but unable to click on get dependencies it is simply not working 
![get dependencies error](https://user-images.githubusercontent.com/65677660/83155675-18c76400-a11f-11ea-9b05-2d0e68154bdf.jpg)

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as it could not be verified, please create the new one when you got enough purchased info - thank you!
