### ISSUE TITLE
login with facebook issue

### ISSUE THREAD

**Issue by perkamto** [inspireui/support#3458]
Step 1 (require): let us know your detail issues & screenshots, what is the product name and version?
![WhatsApp Image 2020-05-28 at 7 20 05 PM](https://user-images.githubusercontent.com/66078926/83162583-fd5a5a00-a11a-11ea-945b-88f4fe440306.jpeg)
![WhatsApp Image 2020-05-28 at 7 20 33 PM](https://user-images.githubusercontent.com/66078926/83162589-fe8b8700-a11a-11ea-8e57-0375e1b2a4dc.jpeg)
![WhatsApp Image 2020-05-28 at 7 22 28 PM](https://user-images.githubusercontent.com/66078926/83162595-fe8b8700-a11a-11ea-949b-ef48a415c2da.jpeg)
![WhatsApp Image 2020-05-28 at 7 22 44 PM](https://user-images.githubusercontent.com/66078926/83162596-ff241d80-a11a-11ea-9ae0-345a78f80f99.jpeg)
![WhatsApp Image 2020-05-28 at 7 20 05 PM](https://user-images.githubusercontent.com/66078926/83162664-12cf8400-a11b-11ea-815c-dfaad28baa2c.jpeg)
![WhatsApp Image 2020-05-28 at 7 20 33 PM](https://user-images.githubusercontent.com/66078926/83162666-1400b100-a11b-11ea-8eb4-c192862f6c05.jpeg)
![WhatsApp Image 2020-05-28 at 7 22 28 PM](https://user-images.githubusercontent.com/66078926/83162667-14994780-a11b-11ea-8dd4-3c8f9042d476.jpeg)
![WhatsApp Image 2020-05-28 at 7 22 44 PM](https://user-images.githubusercontent.com/66078926/83162671-1531de00-a11b-11ea-993f-2b84b8b54161.jpeg)

after login with facebook user creating on firebase and also on wordpress through mstore api butt still loading indicator, same google, same login, same login with phone number

Step 2 (require): verify license and sharing config files via this google form - http://verify.inspireui.com 
![WhatsApp Image 2020-05-28 at 7 17 30 PM](https://user-images.githubusercontent.com/66078926/83163583-42cb5700-a11c-11ea-8757-f9a8c2420025.jpeg)
![WhatsApp Image 2020-05-28 at 7 18 10 PM](https://user-images.githubusercontent.com/66078926/83163586-43fc8400-a11c-11ea-8066-57bd086ef0ed.jpeg)
![WhatsApp Image 2020-05-28 at 7 18 32 PM](https://user-images.githubusercontent.com/66078926/83163591-44951a80-a11c-11ea-9636-8fe4dcdc8af4.jpeg)
[58933775-fluxstore-multi-vendor-flutter-ecommerce-full-app-license.pdf](https://github.com/inspireui/support/files/4696743/58933775-fluxstore-multi-vendor-flutter-ecommerce-full-app-license.pdf)
![WhatsApp Image 2020-05-28 at 7 20 05 PM](https://user-images.githubusercontent.com/66078926/83163600-465ede00-a11c-11ea-9675-98c9c2c45f74.jpeg)
![WhatsApp Image 2020-05-28 at 7 20 33 PM](https://user-images.githubusercontent.com/66078926/83163602-465ede00-a11c-11ea-94c0-2b95b3475726.jpeg)
![WhatsApp Image 2020-05-28 at 7 22 28 PM](https://user-images.githubusercontent.com/66078926/83163603-46f77480-a11c-11ea-9178-7af2d9a7ac0d.jpeg)
![WhatsApp Image 2020-05-28 at 7 22 44 PM](https://user-images.githubusercontent.com/66078926/83163606-47900b00-a11c-11ea-8601-a263542595f4.jpeg)

(please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@perkamto - would you mind to check the latest release `1.7.4` to fix the login issue?

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
