### ISSUE TITLE
[MStore Pro] issue with "5-Banner Slider Image and Vertical Card"

### ISSUE THREAD

**Issue by yosefasad** [inspireui/support#346]
Hello 

I think I did the right configuration for changing the layout file, there is an issue with slider  and card layouts.  Please see the video below. 

https://youtu.be/WfMFMzcNFtI

How to solve this issue?

**Comment by minhcasi** [comment]
Noted for fixing on next release - thank you!

**Comment by minhcasi** [comment]
Fixed 3.7.1
