### ISSUE TITLE
Errors while installing Yarn 

### ISSUE THREAD

**Issue by kunalkhandol** [inspireui/support#3462]
Hello

I am facing errors while installing yarn. Please check this and help me to solve it.

here is the log:

gyp ERR! build error
gyp ERR! stack Error: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe failed with exit code: 1
gyp ERR! stack at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack at ChildProcess.emit (events.js:210:5)
gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=E:\xampp\htdocs\ri\jeenam\jeenam-store-app\node_modules\api-ecommerce\node_modules\grpc\src\node\extension_binary\node-v72-win32-x64-unknown\grpc_node.node" "--module_name=grpc_node" "--module_path=E:\xampp\htdocs\ri\jeenam\jeenam-store-app\node_modules\api-ecommerce\node_modules\grpc\src\node\extension_binary\node-v72-win32-x64-unknown" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd E:\xampp\htdocs\ri\jeenam\jeenam-store-app\node_modules\api-ecommerce\node_modules\grpc
gyp ERR! node -v v12.13.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd build --fallback-to-build --library=static_library --module=E:\xampp\htdocs\ri\jeenam\jeenam-store-app\node_modules\api-ecommerce\node_modules\grpc\src\node\extension_binary\node-v72-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=E:\xampp\htdocs\ri\jeenam\jeenam-store-app\node_modules\api-ecommerce\node_modules\grpc\src\node\extension_binary\node-v72-win32-x64-unknown --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
node-pre-gyp ERR! stack at ChildProcess. (E:\xampp\htdocs\ri\jeenam\jeenam-store-app\node_modules\api-ecommerce\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack at ChildProcess.emit (events.js:210:5)
node-pre-gyp ERR! stack at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
node-pre-gyp ERR! System Windows_NT 10.0.18362
node-pre-gyp ERR! command "C:\Program Files\nodejs\node.exe" "E:\xampp\htdocs\ri\jeenam\jeenam-store-app\node_modules\api-ecommerce\node_modules\node-pre-gyp\bin\node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd E:\xampp\htdocs\ri\jeenam\jeenam-store-app\node_modules\api-ecommerce\node_modules\grpc
node-pre-gyp ERR! node -v v12.13.0
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd build --fallback-to-build --library=static_library --module=E:\xampp\htdocs\ri\jeenam\jeenam-store-app\node_modules\api-ecommerce\node_modules\grpc\src\node\extension_binary\node-v72-win32-x64-unknown\grpc_no

Please help to solve it.

Thanks in Advance

**Comment by minhcasi** [comment]
@kunalkhandol - please help to re-download the nodejs to fix the issue - https://nodejs.org/dist/latest-v10.x/

**Comment by kunalkhandol** [comment]
Hello
Thanks for the reply 

I already using the latest version of node and npm i.e. 
C:>node --version
v12.13.0
C:>npm --version
6.12.0
but as per your suggestion, I downgrade it to 10.x.

but while I run **expo start** command it sends me another error:

SyntaxError: e:\xampp\htdocs\ri\jeenam\jeenam-store-app\src\components\PostList\index.js: Support for the experimental syntax 'decorators-legacy' isn't currently enabled (14:1):

  12 |   Constants.Window.headerHeight - HEADER_MIN_HEIGHT;
  13 | 
>14 | @withTheme
        | ^
  15 | class PostList extends PureComponent {
  16 |   state = { scrollY: new Animated.Value(0) };
  17 | 
Error
09:54
Building JavaScript bundle: error


Regards
Kunal

**Comment by luyx2412** [comment]
HI @kunalkhandol Please switch to node 10 version. You current node is 12 which is not work with project now.

Thanks

**Comment by kunalkhandol** [comment]
Hii @luyx2412 I changed it already but after that, I got this error


SyntaxError: e:\xampp\htdocs\ri\jeenam\jeenam-store-app\src\components\PostList\index.js: Support for the experimental syntax 'decorators-legacy' isn't currently enabled (14:1):

12 | Constants.Window.headerHeight - HEADER_MIN_HEIGHT;
13 |

14 | @withTheme
| ^
15 | class PostList extends PureComponent {
16 | state = { scrollY: new Animated.Value(0) };
17 |
Error
09:54
Building JavaScript bundle: error

When I run **EXPO START**

I hope you understand my point.

Thanks

**Comment by luyx2412** [comment]
Hi @kunalkhandol Are use Mstore expo version?

Thanks

**Comment by kunalkhandol** [comment]
Hi
Yes, I am using Mstore Expo Version.

**Comment by luyx2412** [comment]
Hi @kunalkhandol Please follow the comment to fix your issue https://github.com/ds300/react-native-typescript-transformer/issues/81#issuecomment-431217587

Thanks

**Comment by kunalkhandol** [comment]
Hii
okay, thanks for your support.

Regards
Kunal
