### ISSUE TITLE
I need assistance to install my purchase

### ISSUE THREAD

**Issue by aceventure99** [inspireui/support#3464]
> Step 1 (require): let us know your detail issues & screenshots, what is the product name and version?
I purchase Fluxstore Woocommerce and
Fluxture Multi Vendor
Need help to install and start using it. I have limited knowldedge and it will take a time for me to study it.  Thank you

Step 2 (require): verify license and sharing config files via this google form - http://verify.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by minhcasi** [comment]
Sorry installing support is not included from our support scope - please help to use our document guide http://docs.inspireui.com/fluxstore and video http://youtube.com/inspireui - let us know if you have any question.

Also, Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

**Comment by minhcasi** [comment]
@aceventure99 - I'm sorry to close this ticket as it could not be verified, please create the new one when you got enough purchased info - thank you!
