### ISSUE TITLE
Cannot display any images

### ISSUE THREAD

**Issue by JaserJsk** [inspireui/support#3465]
**Using Version 1.7.3**

**I can display the Categories but I cannot display any images even though I did everything in the docs**

**You can see a screenshot of the issue here -** https://ibb.co/Fz9pzY0

**Comment by minhcasi** [comment]
@JaserJsk - the team confirm it is fixed on latest release, we will update new version in 1-2 days - thank you!

**Comment by JaserJsk** [comment]
So are you saying that the issue is not relasted to my my server ???

**Comment by minhcasi** [comment]
Yes, it could relate to the mstore-api plugin (happen on WCFM plugin), let try with the latest `1.7.4` release and mstore-api - thanks

**Comment by JaserJsk** [comment]
Will it work properly if I donnload **Version 1.7.3** ???

**Comment by JaserJsk** [comment]
I'm trying to download - **Version 1.7.4**

But only **Version 1.7.3** is available

WHere do I find **Version 1.7.4**

**Comment by minhcasi** [comment]
It's available now - please help to download and let us know - thank you!

**Comment by Cheewingtan** [comment]
> I'm trying to download - **Version 1.7.4**
> 
> But only **Version 1.7.3** is available
> 
> Where do I find **Version 1.7.4**

I get the same issue here , solved already, just update your mstoreapi plugin on your website

**Comment by Cheewingtan** [comment]
> It's available now - please help to download and let us know - thank you!

I get this issue too , I update store API plugin on my website but it only show certain product on my app most other product still display blank ,and stores didn't show anything .

<img width="389" alt="Screenshot 2020-06-01 at 11 19 06 AM" src="https://user-images.githubusercontent.com/11556877/83373175-063c7b80-a3fa-11ea-901e-40fc6e5291fe.png">
<img width="414" alt="Screenshot 2020-06-01 at 11 19 33 AM" src="https://user-images.githubusercontent.com/11556877/83373182-0a689900-a3fa-11ea-962a-c29e6ae9f53f.png">
I think you better check again the mstoreapi plugin

**Comment by minhcasi** [comment]
@Cheewingtan - pls also try with the Fluxbuilder tool - http://fluxbuilder.com - thank you!

**Comment by minhcasi** [comment]
@JaserJsk - could you able to create Oneticket for your all comments/ issues?

#3515
