### ISSUE TITLE
Fluxstore Shipping Error

### ISSUE THREAD

**Issue by fasttend** [inspireui/support#3466]
Hi,
I have set limited zip codes for delivery of products. It working fine on my website. but it's not working in App. Please find the attached sreenshoot and dio the needful.

![Untitled](https://user-images.githubusercontent.com/63434487/83248001-06eacd00-a1c2-11ea-9f0f-bfb545a9473f.png)

**Comment by kvt0012** [comment]
Dear sir, you mean that you set shipping zone by zip code on worpdress and it works well on your website but in app it doesn't work ? Can you take me your screenshot, thank you

**Comment by fasttend** [comment]
Hi,
Thank you for understanding my concern. Please find the attached screenshot.

**Comment by kvt0012** [comment]
![image](https://user-images.githubusercontent.com/49152325/83322519-95268800-a282-11ea-82a2-c0b941d40a88.png)

On woocomerce, please go to setting -->Shipping and set up your zip code and price you want, thank you

**Comment by fasttend** [comment]
Hi,
I have already did this and also shared the screenshot with you in previous
reply. Thing is that this is not working in app. The problem is any one can
place their order even they put the zip code is not specified by me. Please
look at this problem.

Is it possible to set City and Zip codes in drop down list like country and
State.

**Comment by kvt0012** [comment]
![image](https://user-images.githubusercontent.com/49152325/83513106-72eb6f00-a4fb-11ea-9a31-7179796bab9e.png)
 
Here sir, please edit it.

**Comment by KhanJahanzaib** [comment]
yes its possible to add State in app
![Screenshot (119)](https://user-images.githubusercontent.com/19766983/83537495-0b8aea80-a50e-11ea-8dbf-f953a4060ccf.png)
`

**Comment by minhcasi** [comment]
@fasttend - let us know if you have any further issue - thanks
