### ISSUE TITLE
apple sign in not working

### ISSUE THREAD

**Issue by mfouadegy** [inspireui/support#3467]
Step 1 (require): let us know your detail issues & screenshots, what is the product name and version?

when i log in with apple i get this error
flutter: There is an issue with the app during request the data, please contact admin for fixing the issues: FormatException: Unexpected character (at character 1)
<br />
[https://imgur.com/6QBeI8g](url)

i enabled apple in my firebase project
[https://imgur.com/jq0yL8S](url)

Step 2 (require): verify license and sharing config files via this google form - http://verify.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@mfouadegy - could i confirm if you have activated the License from the mstore-api plugin - it is required to unlock some API from the app

**Comment by thrmda** [comment]
yes I did activated it

**Comment by thrmda** [comment]
Sorry but I work on the same project with @mfouadegy

**Comment by mfouadegy** [comment]
any updates ?

**Comment by minhtruong315** [comment]
Hi @mfouadegy I can't see the image link. So I dont understand your issue. Please send me screenshot for issues.
Thanks

**Comment by mfouadegy** [comment]
@minhtruong315  i uploaded again please check any of this urls
[https://pasteboard.co/Jb2WeNB.jpg](url)
[https://www.imageupload.net/image/Y8LVz](url)
[https://we.tl/t-VPlOFBzbGY](url)

**Comment by thrmda** [comment]
Any progress or updates?

**Comment by minhtruong315** [comment]
Hi @mfouadegy I still can't see image link. can u attach image files in the comment?

**Comment by thrmda** [comment]
all links are working please copy any of them and past it in your browser.

Please be more responsive to the issue. it's not right to wait 3 Days to say links are not working while they are!

**Comment by thrmda** [comment]
![78592E93-0EB8-43E1-8362-66E084B7FF06](https://user-images.githubusercontent.com/33094923/83751396-73a51200-a66f-11ea-96c1-309ded57e847.jpeg)

**Comment by minhtruong315** [comment]
hi @mfouadegy can u upload your source code to github and invite me: minhtruong315@gmail.com
I'll help you check and fix on your source code.
Thanks

**Comment by mfouadegy** [comment]
@minhtruong315 Done Sent to you invitation

**Comment by minhtruong315** [comment]
Hi @mfouadegy please download Fluxstore version 1.7.5 and upgrade Flutter to the latest version. 
I can't build your source code now. 
<img width="1395" alt="Screen Shot 2020-06-08 at 6 35 46 AM" src="https://user-images.githubusercontent.com/10402500/83982628-5cf20a00-a952-11ea-8ec1-322151460fcc.png">
Can u add my skype: minhtruong315
I'll help you check it quickly.
Thanks

**Comment by mfouadegy** [comment]
@minhtruong315  OK will upgrade to Flux store version 1.7.5 and check if issues solved in this version or not
i already worked in latest Flutter SDK version
Thanks

**Comment by minhtruong315** [comment]
Please let me know when you checked the latest version.
Thanks @mfouadegy

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
