### ISSUE TITLE
Fluxstore error in payment with paypal.

### ISSUE THREAD

**Issue by emmanueldamiancid** [inspireui/support#3469]
Step 1 (require): let us know your detail issues & screenshots, what is the product name and version?

Good morning, I bought the app and started to configure it with Magento, but it has many errors and I decided to install and configure it with WooCommerce.
But still, there are still mistakes.
The one that urges me to correct is the payment gateway with paypal.
When "NativeOnePageCheckout": true, when you select paypal as the payment method, it only remains loading. And it sends the following error:
Exception: invalid request.
I need to correct this error to upload the app to the Playstore.
Other errors can wait for an update.

![eab22929-9d2a-445e-a2ad-7e570364a847](https://user-images.githubusercontent.com/38361142/83277710-0dfce580-a198-11ea-86e1-ac81c39e613e.jpg)
![72cb8e26-64ed-40a8-9c82-befc73a48f08](https://user-images.githubusercontent.com/38361142/83277716-11906c80-a198-11ea-93d4-496a3a2bb753.jpg)

Step 2 (require): verify license and sharing config files via this google form - http://verify.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by minhtruong315** [comment]
Hi @emmanueldamiancid you need to disable paypal native to use NativeOnePageCheckout for paypal
<img width="1142" alt="Screen Shot 2020-06-01 at 10 45 45 AM" src="https://user-images.githubusercontent.com/10402500/83374239-37ff1380-a3f5-11ea-85f0-5145ec484ebc.png">
I try to check NativeOnePageCheckout on your website. it's not working. 
You can try to open this url: 
```https://alpuratehuacan.com/checkout/?code=ee6e78303f87370643a9c2f7dd52015f&mobile=true```
it's showing this
<img width="616" alt="Screen Shot 2020-06-01 at 10 47 58 AM" src="https://user-images.githubusercontent.com/10402500/83374291-641a9480-a3f5-11ea-8584-e480d765c9c2.png">

**Comment by emmanueldamiancid** [comment]
With that option if it works. but it shows a webview of the page with the Paypal payment. Does the app not support native payment without occupying the webview?
![Screenshot_20200531_225301_com android chrome](https://user-images.githubusercontent.com/38361142/83374615-c641ae00-a391-11ea-9bd9-2f9df1d6de21.jpg)

**Comment by minhtruong315** [comment]
Hi @emmanueldamiancid If you set ```enable:true``` you will use native payment for paypal. Did you check this video to config paypal?
https://www.youtube.com/watch?v=MrDq3CqRphY

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
