### ISSUE TITLE
[ListApp]In Booking page chatwithus text button error code

### ISSUE THREAD

**Issue by Pavithran10** [inspireui/support#347]
**Required Info (please complete the following information):**
Product:[ListApp]
Version:1.6.1
Theme: MyListing

**Describe the bug**
hi, I've tried your comment what you send in below folder .
You can go to Components/Detail/Footer.js
find this block and remove it.
after I've commented the code it show the error now while, clicking item list it's not redirect to booking page it display the error.

**Screenshots**
<img width="329" alt="errcode" src="https://user-images.githubusercontent.com/46148046/53550961-08ac8780-3b5e-11e9-9639-04c8a9147f99.png">
![chaterror](https://user-images.githubusercontent.com/46148046/53550977-1235ef80-3b5e-11e9-9616-7834492795be.png)

**Comment by thangvo9x** [comment]
Hi. You must remove whole that block. from "{" to "}"

**Comment by Pavithran10** [comment]
ya,now it's working
