### ISSUE TITLE
Unable to build APK

### ISSUE THREAD

**Issue by pirrot** [inspireui/support#3470]
Hey guys I have an issue while building the apk

`Launching lib\main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...

Compiler message:
lib/widgets/home/banner/banner_map.dart:44:23: Error: A value of type 'PermissionStatus' can't be assigned to a variable of type 'bool'.
 - 'PermissionStatus' is from 'package:location/location.dart' ('../../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/location-2.5.4/lib/location.dart').
        _permission = await _locationService.requestPermission();
                      ^
../../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0.6.0+2/lib/src/dialogs.dart:272:17: Error: No named parameter with the name 'onRatingChanged'.
                onRatingChanged: (rating) {
                ^^^^^^^^^^^^^^^
../../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/smooth_star_rating-1.1.1/lib/smooth_star_rating.dart:24:3: Context: Found this candidate, but the arguments don't match.
  SmoothStarRating({
  ^^^^^^^^^^^^^^^^
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

Compiler message:
lib/widgets/home/banner/banner_map.dart:44:23: Error: A value of type 'PermissionStatus' can't be assigned to a variable of type 'bool'.
 - 'PermissionStatus' is from 'package:location/location.dart' ('../../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/location-2.5.4/lib/location.dart').
        _permission = await _locationService.requestPermission();
                      ^
../../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0.6.0+2/lib/src/dialogs.dart:272:17: Error: No named parameter with the name 'onRatingChanged'.
                onRatingChanged: (rating) {
                ^^^^^^^^^^^^^^^
../../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/smooth_star_rating-1.1.1/lib/smooth_star_rating.dart:24:3: Context: Found this candidate, but the arguments don't match.
  SmoothStarRating({
  ^^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\HugoPC\Documents\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 882

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\Users\HugoPC\Documents\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 57s
Exception: Gradle task assembleDebug failed with exit code 1
`

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!
