### ISSUE TITLE
Lots Of issues , not fully functional app for magento 2  

### ISSUE THREAD

**Issue by sonubdu** [inspireui/support#3471]
issue number 1: the configurable product does not display properly.  product variant missing on the product detail page.
2. on search page configurable product display along with child products.
3. unable to checkout because its show expires token issue.  (user profile clearly show i am logged in)
4. product detail page show error 
5. configurable product added to cart without selecting the variant.
![without](https://user-images.githubusercontent.com/4449291/83297232-ec404480-a211-11ea-9495-5a3af0e5dff6.jpeg)
![error](https://user-images.githubusercontent.com/4449291/83297253-f5311600-a211-11ea-885a-611c8e92bfa8.jpeg)
![cherror](https://user-images.githubusercontent.com/4449291/83297276-037f3200-a212-11ea-97ac-ba4d1a1e7cfe.jpeg)

**Comment by sonubdu** [comment]
project detail
fluxstore version 1.7.4
magento 2.3.2
======================general.dart==========
/// Below config is used for Magento store
  "DefaultStoreViewCode": "",
  "EnableAttributesConfigurableProduct": ["color", "size", "chidyaa_size"],
  "EnableAttributesLabelConfigurableProduct": ["color", "size", "chidyaa_size"]

=======================products.dart=================
const ProductVariantLayout = {
 "color": "color",
  "size": "box",
  "height": "option",
  "chidiya_size": "box"
};

**Comment by minhtruong315** [comment]
Hi @sonubdu can u send me config files via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/3471
I'll help u check your issues
Thanks

**Comment by minhtruong315** [comment]
Hi @sonubdu I saw your config. I will check and let you know soon.
Thanks

**Comment by minhtruong315** [comment]
Hi @sonubdu I can't find the product "Blue Cotton Shirt Dress...." on your website. so I dont know which attributes it's showing. Can u help me check?
<img width="1576" alt="Screen Shot 2020-06-05 at 10 57 19 AM" src="https://user-images.githubusercontent.com/10402500/83835647-85dc8a00-a71b-11ea-902e-c80f828bf6e3.png">

**Comment by sonubdu** [comment]
link of config product  url:
http://www.roobaruu.com/blue-flyon-cotton-shirt.html
http://www.roobaruu.com/catalog/product/view/id/4454/s/blue-blockprinted-cotton-dress/

http://www.roobaruu.com/blue-handprinted-dress-with-gota-details.html

**Comment by sonubdu** [comment]
you guys are too slow , you spend almost 4 days with no progress.
are you really think this will work for all us.

**Comment by minhcasi** [comment]
We wanted to thank you for your patience during this busy time. We currently have reduced staff and a significantly higher volume of inquiries. We’re working as hard as we can to get to your request as soon as possible.

We sincerely apologize for the delay and hope you’re staying safe.

**Comment by minhtruong315** [comment]
Hi @sonubdu You made wrong config for configurable product in magento. You can try to this config
```
"EnableAttributesConfigurableProduct": ["chidiya_color", "chidiya_size"],
  "EnableAttributesLabelConfigurableProduct": ["Color", "Size"]
```
<img width="1611" alt="Screen Shot 2020-06-08 at 11 30 20 AM" src="https://user-images.githubusercontent.com/10402500/83992786-a6a31a80-a97b-11ea-889c-d3f7052b2205.png">

**Comment by minhtruong315** [comment]
This is all attributes on your website
```
[ 'name',
  'description',
  'short_description',
  'sku',
  'price',
  'special_price',
  'special_from_date',
  'special_to_date',
  'cost',
  'weight',
  'name',
  'description',
  'short_description',
  'sku',
  'price',
  'special_price',
  'special_from_date',
  'special_to_date',
  'cost',
  'weight',
  'manufacturer',
  'meta_title',
  'meta_keyword',
  'meta_description',
  'image',
  'small_image',
  'thumbnail',
  'media_gallery',
  'old_id',
  'tier_price',
  'color',
  'news_from_date',
  'news_to_date',
  'gallery',
  'status',
  'tax_class_id',
  'url_key',
  'url_path',
  'minimal_price',
  'visibility',
  'custom_design',
  'custom_design_from',
  'custom_design_to',
  'custom_layout_update',
  'options_container',
  'required_options',
  'has_options',
  'gift_message_available',
  'price_type',
  'sku_type',
  'weight_type',
  'price_view',
  'shipment_type',
  'lorem_ipsum',
  'image_label',
  'small_image_label',
  'thumbnail_label',
  'links_purchased_separately',
  'samples_title',
  'links_title',
  'page_layout',
  'created_at',
  'updated_at',
  'links_exist',
  'is_recurring',
  'recurring_profile',
  'is_imported',
  'country_of_manufacture',
  'msrp_display_actual_price_type',
  'msrp',
  'videoid',
  'new',
  'sale',
  'eh_schedule_start_date',
  'eh_schedule_end_date',
  'eh_schedule_status',
  'chidiya_color',
  'chidiya_size',
  'ssize',
  'shape',
  'ship',
  'measurement',
  'care',
  'reward_points',
  'material1',
  'fixed_tax',
  'hsn',
  'category_ids',
  'quantity_and_stock_status',
  'custom_layout',
  'swatch_image',
  'mgs_brand',
  'extragallery_glr_type',
  'mgs_lookbook',
  'mgs_template',
  'mgs_image_dimention',
  'mgs_image_dimention_more_view',
  'mgs_j360',
  'ts_dimensions_length',
  'ts_dimensions_width' ]
```
You can check the magento 2 rest api document to get more attribute info 
https://devdocs.magento.com/guides/v2.4/rest/list.html
<img width="1012" alt="Screen Shot 2020-06-08 at 11 36 35 AM" src="https://user-images.githubusercontent.com/10402500/83993055-7f991880-a97c-11ea-90ce-fc6fe35a4917.png">

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
