### ISSUE TITLE
how to show "brand" in product page 

### ISSUE THREAD

**Issue by mattia9055** [inspireui/support#3472]
Step 1 (require): let us know your detail issues & screenshots, what is the product name and version?
fluxstore pro   v 1.6.3, product page 

Step 2 (require): verify license and sharing config files via this google form - http://verify.inspireui.com (please don't share the screenshot purchase here)

done 

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

how to show brand in product page 
i was fill goole form under name attia9055

**Comment by minhcasi** [comment]
@mattia9055 - could i know which brand plugin you are using?

**Comment by mattia9055** [comment]
using Attribute

‫في السبت، 30 مايو 2020 في 6:26 ص تمت كتابة ما يلي بواسطة ‪Minh Pham‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by minhcasi** [comment]
@mattia9055 - please help to move this conversation to this ticket 'feature request' #3504 - we will update when it is available - thank you!
