### ISSUE TITLE
Fluxstore single vendor 1.7.3 app issue during isCaching to true

### ISSUE THREAD

**Issue by Zeehshan** [inspireui/support#3476]
Hi, i want to fast performance of the app and i follow instruction in documentation butt at last when i set in general.dart in kAdvanceConfig of "isCaching": true, app performance little bit fast butt my app showing welcome screens again and again and when i back to false then welcome screen not shows up

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as it could not be verified proof of purchase on step 2, please create the new ticket when you got enough purchased info - thank you for your time!
