### ISSUE TITLE
"Sorry, you cannot list resources." 401 error

### ISSUE THREAD

**Issue by amahlathini** [inspireui/support#3477]
Product Name: Fluxstore Multi Vendor - Flutter E-commerce Full App
Version: 1.7.3
I recently bought Fluxstore Multi Vendor and started working on it for about 2 days now. I tried using fluxbuilder, I keep getting this error:

{"code":"woocommerce_rest_cannot_view","message":"Sorry, you cannot list resources.","data":{"status":401}}

![image](https://user-images.githubusercontent.com/51906122/83315656-c7ec6400-a221-11ea-87bd-f2aca60ea40a.png)

When I manually do the setup, following the documentation, it still won't work, no categories and no products displayed on the app.

![image](https://user-images.githubusercontent.com/51906122/83315643-b60ac100-a221-11ea-8d67-7ab80f9c3b1c.png)

- I have followed the fluxstore documentation properly

- I have followed the woocommerce rest api documentation properly, the api keys are corrects.

- I have tried editing the .htaccess file by adding RewriteCond %{HTTP:Authorization} ^(.*) 
RewriteRule ^(.*) - [E=HTTP_AUTHORIZATION:%1]

- I have tried deactivating all plugins

Nothing seems to be working

Please help me. Thank you in advance.

**Comment by minhcasi** [comment]
@philipvu30 - pls help to investigate this issue

**Comment by Rzone7** [comment]
Same issues with me

**Comment by mpsb** [comment]
Experiencing same issues. Any ideas on how to solve please?

**Comment by daffa485** [comment]
Where can i find .htaccess file?
