### ISSUE TITLE
Store Details To Include "Description/Biography"

### ISSUE THREAD

**Issue by stickypages** [inspireui/support#3479]
_*Step 1* (require): let us know your detail issues & screenshots, what is the product name and version?_
**I would like to receive ALL the store information. The API doesn't include the biography, are we able to include the bio, in a new tab, or in the 'contact' section as well?**

_*Step 2* (require): verify license and sharing config files via this google form - http://verify.inspireui.com (please don't share the screenshot purchase)_
**I just verified from my previous ticket, 3478**

**Comment by minhcasi** [comment]
There could be a missing mapping field for the Vendor info, you could try to add more field under the contact section

Please help to post your all comment to one ticket as well #3478 - thank you!
