### ISSUE TITLE
M Store Checkout plugin doesn't allow to upload images in Wordpress throwing HTTP 500 Error

### ISSUE THREAD

**Issue by Relimer-Technologies** [inspireui/support#348]
**Mandatory Info (please complete the following information):**
 - Product: [e.g. MStore, ListApp]
 - Your Purchased Code: [get from https://codecanyon.net/downloads]
(we may not reply if you are not our customer)

**Describe the issues**

**Screenshots**

**Additional context**
Add any other detail logs about the problem here.
**Mandatory Info (please complete the following information):**

* Product: [e.g. MStore, ListApp]
  M Store Pro
  Purchase Code: d98eb201-aba4-4c76-a0a1-cbd67415737d
* Your Purchased Code: [get from https://codecanyon.net/downloads]
  (we may not reply if you are not our customer)

**Describe the issues**
Hello,

Good Evening, I have purchased M Store Pro from Envato. I have done all the setup required... I have installed all of the required tools... M Store Checkout Plugin in Wordpress doesn't allow me to add images in the website... It shows HTTP 500 error... When I deactivate the plugin and try to upload the images, the images are uploaded perfectly fine... Please find the solution to my problem.

Thank You.

**Comment by minhcasi** [comment]
Hi, could you try with this latest mstore-checkout - https://github.com/inspireui/mstore/blob/master/plugins/mstore-checkout.zip - thanks

**Comment by Relimer-Technologies** [comment]
Thanks... It worked for me... Please resolve another issue which I registered 

https://github.com/inspireui/support/issues/350#issue-415610305

Thank You.
