### ISSUE TITLE
payment issue and image catagory

### ISSUE THREAD

**Issue by rabahaldoori** [inspireui/support#3480]
First issue payment when i click on the Review not going through .

<img width="985" alt="Screen Shot 2020-05-30 at 12 03 12 AM" src="https://user-images.githubusercontent.com/31085177/83320109-dcbcfd80-a209-11ea-977b-b93474356f74.png">

and send issue i trying to change the image catagory  i change the Url and The ID still didn't take it 

<img width="1324" alt="Screen Shot 2020-05-29 at 6 39 39 PM" src="https://user-images.githubusercontent.com/31085177/83320111-dfb7ee00-a209-11ea-839c-3fd82a4ee29d.png">

thank you

**Comment by minhcasi** [comment]
@rabahaldoori - pls post the comment on your previous comment ticket #3404 - thanks
