### ISSUE TITLE
Fluxbuilder & config json issue

### ISSUE THREAD

**Issue by ekramul-1** [inspireui/support#3481]
@minhcasi  Please arrange @philipvu30

After customizing from fluxbuilder, I copied the scripts & updated in config_en.json file & not working while emulate,
Later I tried to in config.json file also & not working, I checked the https://docs.inspireui.com/fluxstore/multi-vendor/ & tried to follow but still not working.

Please tell me that how I will able to customise & update.
Thank you

<blockquote><img src="https://docs.inspireui.com/images/meta/Ghost-Docs.jpg" width="48" align="right"><div>InspireUI Document</div><div><strong><a href="https://docs.inspireui.com/fluxstore/multi-vendor/">FluxStore - Universal mobile commerce Flutter app for Magento, WooCommerce and Opencart</a></strong></div><div>Fluxstore is universal app that fully integration with the Woocommerce, Mangeto and Opencart</div></blockquote>

_Originally posted by @ekramul-1 in https://github.com/inspireui/support/issues/3280#issuecomment-636110184_

**Comment by minhcasi** [comment]
@ekramul-1 - some new features from Fluxbuider is not reflecting on the latest Fluxstore MV, we will release new Fluxstore MV `1.7.5` version soon to compatible with the latest Fluxbuilder 1.7.5 - thank you!

**Comment by ekramul-1** [comment]
Basically I'm using WCFM, Hope this release will come fast.

For this how much time required @minhcasi ?
Shall I able to customize or not ?

**Comment by ekramul-1** [comment]
Received update :)
Let's see

**Comment by minhcasi** [comment]
Let us know your checking man 😊

**Comment by ekramul-1** [comment]
Not yet finished, I will let you know @minhcasi

**Comment by ekramul-1** [comment]
> Let us know your checking man 😊

It's Working fine and really happy to see this.

**Comment by minhcasi** [comment]
Thank you for confirmation, let us know if you have any further questions. 

The team will very much appreciate your help to support us with the rating to http://codecayon.net/downloads - thank you!

**Comment by ekramul-1** [comment]
Hello @minhcasi 
could you please confirm from that can I change my packages name from package="com.inspireui.fluxstore.vendor">to package="bbmall.in"> as the last time I was published my app in ionic project & package is "bbmall.in"
Shall I upgrade to the futter app with different package ?
Please reply ASAP, I know that you always active :)

**Comment by ekramul-1** [comment]
Please have a look into this issue & please let me know the solution please
![image](https://user-images.githubusercontent.com/63785688/83427923-2185a600-a44f-11ea-8188-a22ceb7fe70c.png)

**Comment by ekramul-1** [comment]
> Thank you for confirmation, let us know if you have any further questions.
> 
> The team will very much appreciate your help to support us with the rating to http://codecayon.net/downloads - thank you!
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/c5a18223816825ebf6c0fec648742882ecbb6a7b/68747470733a2f2f6173736574732e73686f7066726f6e742e656e7661746f2d7374617469632e636f6d2f696d616765732f6d6574612f6c6f676f732f636f646563616e796f6e2e706e67"><img alt="" height="14" src="https://camo.githubusercontent.com/c75d968dba11187d74e09644791494a4418ce2d8/68747470733a2f2f6173736574732e73686f7066726f6e742e656e7661746f2d7374617469632e636f6d2f69636f6e732f636f646563616e796f6e2e6e65742f66617669636f6e2e69636f"> CodeCanyon**[Buy Plugins & Code from CodeCanyon](https://codecanyon.net/)**Discover 33,265 Plugins, Code and Script for Bootstrap, Javascript, PHP, Wordpress, HTML5 and more. Save time, buy Code on CodeCanyon!

5 star rating already given & well as comment.
