### ISSUE TITLE
How to find WooCommerce API Consume Key

### ISSUE THREAD

**Issue by prsar** [inspireui/support#3483]
Could not find this key in Woocommerce/Wordpress. App is not showing our Woocommerce content. App is also showing an error 

"Missing Oauth parameters Oauth_consumer_Key, oauth_timestamp, oauth_nonce, oauth_signature_method

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as it could not be verified proof of purchase on step 2, please create the new ticket when you got enough purchased info - thank you for your time!
