### ISSUE TITLE
When bulding apk its got error

### ISSUE THREAD

**Issue by amankhan7** [inspireui/support#3484]
![IMG_20200530_133438](https://user-images.githubusercontent.com/66056095/83325919-b6d93c80-a28d-11ea-9c5f-246a6967f4a5.jpg)

Please help me in my pc any emulator is not working so want to build apk for testing the app

![Screenshot_20200529_212253](https://user-images.githubusercontent.com/66056095/83325944-f6078d80-a28d-11ea-9462-9aa7f3f54a13.jpg)

  And when build apk from android studio and apk its got error.    

When i click  in relod  then this is display

![Screenshot_20200530_160042](https://user-images.githubusercontent.com/66056095/83326115-efc5e100-a28e-11ea-9792-ef751edb71ed.jpg)

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as it could not be verified, please create the new one when you got enough purchased info - thank you!
