### ISSUE TITLE
Coupon code issue .excluded product or catogories 

### ISSUE THREAD

**Issue by papaya1986** [inspireui/support#3487]
The coupon code deduction same for all ..
If a coupon code exclude a catogory Or a product ,the app cant understand the restrictions it’s deducting .please fix the issue the coupon code should have restrictions.

**Comment by minhcasi** [comment]
@papaya1986 - we will upgrade `coupon` issue on next `1.7.6` - thank you!

**Comment by minhcasi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add product Brand](https://trello.com/c/LCzLNKvh/50-add-product-brand)

**Comment by minhcasi** [comment]
moved to backlog for implementing
