### ISSUE TITLE
unable to resolve react -native-screens (android application)

### ISSUE THREAD

**Issue by dhruva7782** [inspireui/support#3488]
hello i'm new here for react native i'm faceing some issues after launch expo starting app 'Unable to resolve "react-native-screens" from "node_modules\react-navigation-tabs\lib\module\navigators\createBottomTabNavigator.js"

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!
