### ISSUE TITLE
[ListApp] Again some features images and map functions are not working in our application after config

### ISSUE THREAD

**Issue by Pavithran10** [inspireui/support#349]
**Mandatory Info (please complete the following information):**
Product:[ListApp]
Version:1.6.1
Theme: MyListing

**Describe the issues**
hi, I need a help in listapp application before some problem we faced that home screen featured images,map and categories list inner features are all not working fine after that you only configure our site creditional and fixed the issues. Now the same problem occurs suddenly today while running our application after config our site completely. so, kindly please check and fix our site creditional. 

[note:] I've attached our site creditional details via mail. please check it ASAP. and then I've attached that our application error video below please watch that too.

**Screenshots**
[Uploading errorapp.zip…]()

**Comment by thangvo9x** [comment]
HI. Can you provide us the screenshots, plz?

**Comment by thangvo9x** [comment]
https://github.com/inspireui/support/issues/341
