### ISSUE TITLE
Fluxlisting: ListPro 1.4.1 - Notifications are NULL

### ISSUE THREAD

**Issue by iamar1k92** [inspireui/support#3490]
![714a5019-2a23-4ddf-9991-c0faa40a61dc](https://user-images.githubusercontent.com/58983166/83339283-a8b70a80-a2e5-11ea-88a0-8bfa439e9e40.jpeg)

Notifications are setup correctly, i can received the notification on the notification bar, but show null on notify message screens

**Comment by minhcasi** [comment]
@iamar1k92 - could i know you are using Firebase for push notification - thank you!

**Comment by iamar1k92** [comment]
yes i do

**Comment by philipvu30** [comment]
Hi,

In the file lib/models/notification.dart, please remove this term: json['data'] ?? for every function. 

Thank you

**Comment by iamar1k92** [comment]
Thanks, it was fixed. Is it setup for image notification with firebase blaze? Or need to set it up?

**Comment by philipvu30** [comment]
Hi,

I'm sorry. Image notification is not implemented.

**Comment by iamar1k92** [comment]
can you help me with that?

**Comment by philipvu30** [comment]
Hi,

Sorry, we do not provide customization service. You can ask someone who is able to help you as I think this is an easy implementation. 

- First, you need to print out the JSON response from the FireBase in this function in the file lib/models/notification.dart like this
![image](https://user-images.githubusercontent.com/54442328/83609608-b819aa80-a5a8-11ea-8439-4282d9a38b09.png)

- Second, add an additional attribute and look for an image attribute in the JSON response and assign URL to the created attribute(For example imageURL). The response somehow will be like this:
{notification: {title: Test, body: Test}, data: {}}

Example:
![image](https://user-images.githubusercontent.com/54442328/83610182-4c840d00-a5a9-11ea-9a77-e23525699f5a.png)

Then you can use it as normal. I hope this solution works for you.

**Comment by iamar1k92** [comment]
ok thank you!!
