### ISSUE TITLE
Native Payment in Fluxstore - Shopify not working 

### ISSUE THREAD

**Issue by MHashim2020** [inspireui/support#3491]
Hi I've issue with setup tap payment gateway in fluxstore - shopify can you please help 
aslo i've other issue when use is logged in checkout is not working am getting this message 
Exception : graphQL Errors : checkout is already completed . undefined location.

Please help thanks

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as it could not be verified proof of purchase on step 2, please create the new ticket when you got enough purchased info - thank you for your time!
