### ISSUE TITLE
Fluxstore Listing app version 1.4.1, Images do  not show

### ISSUE THREAD

**Issue by youngtet** [inspireui/support#3492]
Images from site do not show in app, but when a listing is clicked the images display

![room](https://user-images.githubusercontent.com/60430933/83339618-b70c1480-a25a-11ea-8c29-598ba3e77c9e.jpg)

I am using a Listeo Theme

Proof of payment
![Van](https://user-images.githubusercontent.com/60430933/83339641-e7ec4980-a25a-11ea-8e30-95c3eb7f43dd.jpg)

**Comment by youngtet** [comment]
??

**Comment by philipvu30** [comment]
Hi,

Currently, the app is compatible with these versions:

ListingPro
- Theme version 2.5.1
- ListingPro Plugin version 2.5.1
- ListingPro Review 1.2
My Listing
- Theme version 2.2.2
Listeo
- Theme version 1.3.1

And remember to change your gallery in config.dart to "gallery" : "gallery_images".
Thank you.

**Comment by youngtet** [comment]
okay but i saw you fix this issue for someone in the comments

**Comment by philipvu30** [comment]
Hi,

May I ask what is your email?

**Comment by youngtet** [comment]
youngtet@gmail.com

**Comment by philipvu30** [comment]
Hi,

Fixed solution is sent to your mailbox. If it works, kindly close this ticket. Otherwise, we will close it after 2 days of no response. Thank you

**Comment by youngtet** [comment]
It hasn't worked still wont show

**Comment by youngtet** [comment]
this is my listeo site roomz.sydstanzania.org can u try it on your side

**Comment by philipvu30** [comment]
Hi,

Please replace these files in the common folder.
[3492.zip](https://github.com/inspireui/support/files/4714610/3492.zip)

![image](https://user-images.githubusercontent.com/54442328/83477580-c939bd00-a4bd-11ea-8ede-7c8f8c53dd9e.png)

**Comment by philipvu30** [comment]
Hi,

It was a mistake that we uploaded the wrong version of ListApp Mobile Manager plugin.
Please manually delete the plugin on your website and upload this [plugin](https://github.com/inspireui/support/files/4722691/listapp-mobile-manager.zip) instead. 

Thank you for your patience.

**Comment by michaelbrinkworth** [comment]
join :) https://www.facebook.com/groups/289288585778355/
