### ISSUE TITLE
Total order's value must be at least $100,00

### ISSUE THREAD

**Issue by joaonathan** [inspireui/support#3493]
![WhatsApp Image 2020-05-30 at 18 49 34](https://user-images.githubusercontent.com/9143192/83339662-910c6180-a2a6-11ea-8958-9d9331995fdf.jpeg)

after upgrading to 1.7.4, the message "Total order's value must be at least $ 100.00" appears every time I try to make a purchase below $ 100, how do I change this minimum purchase amount?

**Comment by minhcasi** [comment]
@joaonathan - please update this file - we will note to the document

<img width="624" alt="Screen Shot 2020-05-31 at 09 23 08" src="https://user-images.githubusercontent.com/1459805/83343080-5b0bc380-a320-11ea-89a7-8a7043970551.png">
