### ISSUE TITLE
APP NOT INSTALLED

### ISSUE THREAD

**Issue by MorisTech** [inspireui/support#3494]
Hello,
After building the app in android studio, I run it in the emulator but it's slow

So I try to install it on my android phone and it doesn't work, it says "App not installed"

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by MorisTech** [comment]
I've submitted the form and I need your response ASAP

**Comment by minhcasi** [comment]
@MorisTech - could you help to try with the latest `1.7.4` to fix the performance issue.

There is an important step to optimize the app performance on this guide https://docs.inspireui.com/fluxstore/performance/#2-image-optimization

Once you install on your device, could i check if you have plug the device into PC and run with Android Studio? If you build as final apk, make sure to follow this guide https://docs.inspireui.com/fluxstore/delivery-android/

**Comment by MorisTech** [comment]
So I have to plug in my android phone then build the app?
I don't understand, what latest 1.7.4, please explain explicitly 

Also, what i meant above is, I want to try the app on my android phone, you mean I have to change the app bundle or what?

**Comment by MorisTech** [comment]
Also, this code doesn't work on windows

keytool -genkey -v -keystore c:/Users/USER_NAME/key.jks -storetype JKS -keyalg RSA -keysize 2048 -validity 10000 -alias key

**Comment by minhcasi** [comment]
Pls check this note - https://flutter.dev/docs/deployment/android

<img width="1035" alt="Screen Shot 2020-06-02 at 11 04 08" src="https://user-images.githubusercontent.com/1459805/83478739-cbe9e180-a4c0-11ea-8ce4-6f67a384c0bf.png">

**Comment by MorisTech** [comment]
Okay thanks

I run this code and this is what I'm getting


> Running pub upgrade...
> Got socket error trying to find package shelf_packages_handler at https://pub.dartlang.org.
> Error (69): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)
> 
> Waiting for 0 seconds, press CTRL+C to quit ...
> Running pub upgrade...

**Comment by minhcasi** [comment]
Please check if you setting the same with the default one ? 

<img width="891" alt="Screen Shot 2020-06-04 at 10 41 49" src="https://user-images.githubusercontent.com/1459805/83712440-01710500-a650-11ea-9486-078d0454caa5.png">

**Comment by MorisTech** [comment]
i changed the settings to default settings.gradle 

This is the error now


Running Gradle task 'assembleRelease'...


FAILURE: Build failed with an exception.



* What went wrong:

Execution failed for task ':app:validateSigningRelease'.

> Keystore file 'C:\Users\Adesoji\Downloads\Compressed\codecanyon-Mmm0XdFL-fluxstore-multi-vendor-flutter-ecommerce-full-app\FluxStore-vendor-1.7.3\source\android\app\Users\Adesoji\key.jks' not found for signing config
'release'.



* Try:

Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.



* Get more help at https://help.gradle.org



BUILD FAILED in 21s
Running Gradle task 'assembleRelease'...                           22.0s
Gradle task assembleRelease failed with exit code 1

**Comment by minhcasi** [comment]
@MorisTech -

there is missing storekey config from - app\Users\Adesoji\key.jks - try to double-check this guide pls  https://flutter.dev/docs/deployment/android#create-a-keystore

**Comment by MorisTech** [comment]
Thank you
it works

Now How do I edit the IOS template
I'm done with the Android

**Comment by minhcasi** [comment]
iOS is easy by only change the info.plist - pls check https://docs.inspireui.com/fluxstore/delivery/

Let us know if you have any further issue - thank you!

**Comment by MorisTech** [comment]
Does that mean what i'm editing in Android Studio also works for IOS?
If so, how do i test the ios

**Comment by MorisTech** [comment]
hello???
