### ISSUE TITLE
New Installation Error Mstore Expo (Windows)

### ISSUE THREAD

**Issue by onlineosman** [inspireui/support#3495]
Hi, after updating to new version got into error, i removed every thing from PC and started fresh installation still cannot resolve it.  Followed all the guidelines of docs still unable to solve.

![image](https://user-images.githubusercontent.com/34172061/83342614-7cf64d80-a302-11ea-9e7e-e20220a2a243.png)
 
Thanks

**Comment by luyx2412** [comment]
Hi @onlineosman Please change the bundle id in app.json https://docs.expo.io/workflow/configuration/#ios and start again.

Thanks

**Comment by onlineosman** [comment]
![Second issue](https://user-images.githubusercontent.com/34172061/83351399-8c05eb80-a354-11ea-9fdf-a8b827272bbb.png)

Thanks but stuck here!

**Comment by onlineosman** [comment]
Secondly what if i wan't to upgrade this license for flutter, because it seems flutter is more easy and better then mstore pro, can i get replacement of license for flutter ?

**Comment by luyx2412** [comment]
Hi @onlineosman Please contact with @minhcasi to resolve this issue. Thanks

**Comment by onlineosman** [comment]
How can I cantact @minhcasi  ?

**Comment by minhcasi** [comment]
@onlineosman - sorry replace new License is not support on our support scope at this time :)

**Comment by onlineosman** [comment]
No problem, but could you fix the error as I have to finalize the project this week

**Comment by onlineosman** [comment]
Secondly where shell I send Teamviewer Link ?

**Comment by onlineosman** [comment]
Could you manage to solve the issue today ?

**Comment by luyx2412** [comment]
Hi @onlineosman Please install react-native first https://reactnative.dev/docs/environment-setup, after that follow the document to install the project https://docs.inspireui.com/mstore/getting-started/

![](https://user-images.githubusercontent.com/8909619/83768519-162db700-a6a9-11ea-8bff-06d96e52f123.png)

Thanks

**Comment by onlineosman** [comment]
Hi, Thanks a lot it worked but getting this error.


![React-native](https://user-images.githubusercontent.com/34172061/83908803-c0c0db00-a778-11ea-95ae-a88ae21f573e.png)
![third issue](https://user-images.githubusercontent.com/34172061/83908804-c28a9e80-a778-11ea-85ab-effcf1cf54be.png)

**Comment by luyx2412** [comment]
Hi @onlineosman It is the warning, so can you run your app?

Thanks
