### ISSUE TITLE
How to set returnUrl and cancel Url in Paypal config?

### ISSUE THREAD

**Issue by liqiang1995** [inspireui/support#3496]
How are you?
I have the PayPal payment method for this app.
but I don't know how set it.
Would you please help me?
thank you.
![image](https://user-images.githubusercontent.com/54995513/83342998-d3c24e00-a327-11ea-83a4-101ebc8682d6.png)

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as it could not be verified, please create the new one when you got enough purchased info - thank you!

---

Please submit the proof of purchase from http://verify.inspireui.com/ and create new ticket - thanks
