### ISSUE TITLE
home screen shows like this

### ISSUE THREAD

**Issue by goelrajiv75** [inspireui/support#3497]
![assertion](https://user-images.githubusercontent.com/65877361/83343987-eedc9000-a31e-11ea-82de-da1c232895cf.jpg)
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by goelrajiv75** [comment]
Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building HomeLayout-[<'en'>](dirty, state: _HomeLayoutState#091ec):
Failed assertion: boolean expression must not be null

The relevant error-causing widget was: 
  HomeLayout-[<'en'>] file:///C:/flux/Flutter/fluxstore/FluxStore-vendor-1.7.3/source/lib/screens/home/home.dart:120:22
When the exception was thrown, this was the stack: 
#0      _HomeLayoutState.jsonWidget (package:fstore/widgets/home/index.dart:37:52)
#1      _HomeLayoutState.build (package:fstore/widgets/home/index.dart:155:11)
#2      StatefulElement.build (package:flutter/src/widgets/framework.dart:4619:28)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4502:15)
#4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)


return Stack(
          children: <Widget>[
            if (value.appConfig['Background'] != null)
              HomeBackground(config: value.appConfig['Background']),
            SafeArea(
              child: HomeLayout(
                configs: value.appConfig,
                key: Key(value.locale),
              ),
            ),
          ],
        );
      },
...

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as it could not be verified proof of purchase on step 2, please create the new ticket when you got enough purchased info - thank you for your time!
