### ISSUE TITLE
[MStore] - issue one exporting andorid 

### ISSUE THREAD

**Issue by kiamoz** [inspireui/support#35]
MStroe 3.4 last ver
![screen shot 2018-11-23 at 11 50 07 am](https://user-images.githubusercontent.com/10494372/48933666-66ee1c80-ef16-11e8-996d-95b9682291ff.png)

**Comment by minhcasi** [comment]
Could you try to use this build.grade - https://www.dropbox.com/s/v3d3xzjoemybc2i/build.gradle?dl=0

File: android/build.gradle
