### ISSUE TITLE
[MStore] Razorpay Integration fail 404 Error Page

### ISSUE THREAD

**Issue by Relimer-Technologies** [inspireui/support#350]
**Mandatory Info (please complete the following information):**
 - Product: [e.g. MStore, ListApp]
 - Your Purchased Code: [get from https://codecanyon.net/downloads]
(we may not reply if you are not our customer)

**Describe the issues**

**Screenshots**

**Additional context**
Add any other detail logs about the problem here.
**Mandatory Info (please complete the following information):**

* Product: [e.g. MStore, ListApp]
* Your Purchased Code: [get from https://codecanyon.net/downloads]
  (we may not reply if you are not our customer)

**Describe the issues**

**Screenshots**

**Additional context**
Add any other detail logs about the problem here.
**Mandatory Info (please complete the following information):**

* Product: [e.g. MStore, ListApp]
  M Store Pro
  Purchase Code: d98eb201-aba4-4c76-a0a1-cbd67415737d
* Your Purchased Code: [get from https://codecanyon.net/downloads]
  (we may not reply if you are not our customer)

**Describe the issues**
Hello,

Good Evening, I have purchased M Store Pro from Envato. I have done all the setup required... I have installed all of the required tools... I have tried to integrate Razorpay into the website and I even followed the tutorial video... First, when I have done the setup I get the 404-page error after the checkout... Then I have tried to find the solution in the FAQ and I got this link...

https://github.com/inspireui/support/issues/38#issuecomment-441363940

I have tried to create the page with page attribute as Page Custom Template... But the page is not getting published... Please find the solution to my problem.

Thank You.

**Comment by Relimer-Technologies** [comment]
Hello... Please provide me with a solution as soon as possible.
Thank You

**Comment by minhcasi** [comment]
@Relimer-Technologies please try with the second solution as on above link, sometime the first setting does not work so you need to copy its manually:

Copy the file "plugins/mstore-checkout/templates/mstore-checkout-template.php" to your current Wordpress template folder.
The same step-2 from the first solution above but select the "MStore Checkout" instead of "Page custom template" from the dropdown list, this naming could be changed from mstore-checkout-template.php file


This is the video guide for Razopay: https://www.youtube.com/watch?v=uTxvwgG9M3s&index=3&t=0s&list=PLcF-HiQy-jOJJwVfQ7VDrM3xWgxd0Jte9

**Comment by Relimer-Technologies** [comment]
Hello... I have edited the mstore-checkout-template.php file and copied it to the current Wordpress template folder as you said to "plugins/mstore-checkout/templates/mstore-checkout-template.php"... But in the dropdown list, I don't find any name as "Mstore Checkout"... Rather I find Page custom template option as usual... Please help me with this problem as soon as possible... Thank You

**Comment by Relimer-Technologies** [comment]
Hello... Please provide me with a solution as soon as possible.
Thank You

**Comment by minhcasi** [comment]
Hi, please try to rename the template name "MStore Checkout" to another name and look up its name from the dropdown list

- you can see this name on header of the file - https://github.com/inspireui/mstore/blob/master/plugins/mstore-checkout/templates/mstore-checkout-template.php

**Comment by Relimer-Technologies** [comment]
Hello... @minhcasi  I have tried this method also... I have edited the "Mstore Checkout" to another name and checked in the dropdown list... But it still shows the Page Custome Template... I have edited the name in the header of the file as shown below

![screenshot_2](https://user-images.githubusercontent.com/47352123/53785216-c27c6d00-3f3d-11e9-805f-214bfc9de104.png)
![screenshot_3](https://user-images.githubusercontent.com/47352123/53785217-c27c6d00-3f3d-11e9-89d9-bd121caf1252.png)

Please provide me with the solution to this problem as soon as possible

Thank You

**Comment by thangvo9x** [comment]
Can you give me your info hosting to checking?

**Comment by Relimer-Technologies** [comment]
I will give you soon... Just doing some work on it... Thank You

**Comment by Relimer-Technologies** [comment]
Hello @thangvo9x ... The following below are the hosting info

206.189.133.102

mstouser
MST=B678!

home/mbhagwanlal.com/public_html

Please provide me with a solution as soon as possible... Thank You

**Comment by thangvo9x** [comment]
Can not log in with that account.

**Comment by Relimer-Technologies** [comment]
I will provide you with updated hosting info soon... Thank You

**Comment by thangvo9x** [comment]
please give me your info to your admin dashboard.

**Comment by Relimer-Technologies** [comment]
Hello @thangvo9x ...
Site:- https://mbhagwanlal.com/wp-admin
Username:- mbhagwanlal
Password:- Bhagwan=Lal345!

**Comment by thangvo9x** [comment]
Hi.  I published again your link to check out on your site.
https://mbhagwanlal.com/mstore-checkout/
Thanks

**Comment by Relimer-Technologies** [comment]
It is Published as Default Template... I have mentioned above that all the other templates it is able to publish except the Page Custom Template... In the solution provided by @minhcasi ... It is clearly said to publish the page in Page Custom Template... The Screenshot is also available... Check the below link

https://github.com/inspireui/support/issues/38#issuecomment-441363940

When it is published as Page Custom Template... Then I will be able to get the solution for 404 Page Error... Look into the problem again and please help me out soon.

Thank You

**Comment by thangvo9x** [comment]
That solution is the best way for this issue.

**Comment by Relimer-Technologies** [comment]
@thangvo9x  That is not the solution for the comment show by @minhcasi  in 

https://github.com/inspireui/support/issues/38#issuecomment-441363940

I need a proper solution to my problem...
