### ISSUE TITLE
smartchat crashes after returning from settings

### ISSUE THREAD

**Issue by basith9381** [inspireui/support#3500]
+ Detail Issues: 
smartchat (floatingActionButton) crashes when I go to single product page after returning from settings.
to reproduce the issue, after launching the app please go to settings,  back to home screen and go to single product page.  It doesn't happen in this sequence (single product page - home - settings)

+ Product & version:
FluxStore-woo 1.7.3
  
+ Flutter (or React Native) version: 
Flutter 1.17.1

+ Testing Device/Simulator: 
Samsung galaxy S9+

+ Screenshot issues : 
with smartchat 

![Screenshot1](https://user-images.githubusercontent.com/21219304/83346499-89969800-a33a-11ea-8792-070be7b85528.jpg)

after crash
![Screenshot_20200531-122447](https://user-images.githubusercontent.com/21219304/83346503-961af080-a33a-11ea-9567-4aa39f2627e4.jpg)

+ Thrown exception on Android studio :

════════ Exception caught by scheduler library ═════════════════════════════════════════════════════
The following NoSuchMethodError was thrown during a scheduler callback:
The method '-' was called on null.
Receiver: null
Tried calling: -(0.0)

When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      RenderSliverMultiBoxAdaptor.childMainAxisPosition (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:573:37)
#2      RenderSliverHelpers.applyPaintTransformForBoxChild (package:flutter/src/rendering/sliver.dart:1695:20)
#3      RenderSliverMultiBoxAdaptor.applyPaintTransform (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:586:5)
#4      RenderObject.getTransformTo (package:flutter/src/rendering/object.dart:2345:24)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
D/ViewRootImpl@a3c5221[MainActivity]( 8612): Relayout returned: old=(0,0,1080,2220) new=(0,0,1080,2220) req=(1080,2220)0 dur=17 res=0x1 s={true 514056790016} ch=false

════════ Exception caught by animation library ═════════════════════════════════════════════════════
The following assertion was thrown while notifying status listeners for ProxyAnimation:
'package:flutter/src/widgets/heroes.dart': Failed assertion: line 539 pos 14: 'overlayEntry != null': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack: 
#2      _HeroFlight._handleAnimationUpdate (package:flutter/src/widgets/heroes.dart:539:14)
#3      AnimationLocalStatusListenersMixin.notifyStatusListeners (package:flutter/src/animation/listener_helpers.dart:198:19)
#4      AnimationLocalStatusListenersMixin.notifyStatusListeners (package:flutter/src/animation/listener_helpers.dart:198:19)
#5      AnimationLocalStatusListenersMixin.notifyStatusListeners (package:flutter/src/animation/listener_helpers.dart:198:19)
#6      AnimationController._checkStatusChanged (package:flutter/src/animation/animation_controller.dart:777:7)
...
The ProxyAnimation notifying status listeners was: ProxyAnimation(null; ⏭ 1.000)
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by minhcasi** [comment]
@basith9381 - we will investigate your issue and will get back soon - thank you!

**Comment by Alnaggar94** [comment]
Same issue in v1.7.5

**Comment by minhcasi** [comment]
fixed on the latest `1.7.5` - it will be ready to download today - thank you!

**Comment by minhcasi** [comment]
let us know if you have any further questions - thank you!

**Comment by basith9381** [comment]
tried  1.7.5. Still the problem is not resolved.

**Comment by minhcasi** [comment]
could you help to share the video of the issue pls ?

**Comment by basith9381** [comment]
Sure, Please check the gif. from home screen navigating to settings. At that time there is smartchat, after that coming back to home screen and going to product page. At that time the smartchat crashes. Again coming back to home screen and going to settings. smartchat  crashes again 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/21219304/83850643-d8737180-a72e-11ea-8585-338aa3db181a.gif)

**Comment by minhcasi** [comment]
@vumanhsn97 - pls help with investigating

**Comment by basith9381** [comment]
The problem has resolved. It was related to the FabCircularMenu library. Imported the latest package and changed the  FabCircularMenu parameters inside the smartchat.dart. 

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/21219304/84011413-b3cc0380-a993-11ea-85af-697c2000b686.gif)
