### ISSUE TITLE
After updated latest version 1.7.4.In my app dont show any products

### ISSUE THREAD

**Issue by zawwinhtunn** [inspireui/support#3501]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

hello please help me. After updated latest version 1.7.4.In my app dont show any products.only show categories and nothing products show .please help me .my website is https://sunthitshop.com
This is my screen shot error https://github.com/zawwinhtunn/multiflutter/blob/master/products%20error.jpg

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by philipvu30** [comment]
Hi,

It seems fine to me. Please check if you have configured the config_xx.json files.
Thank you.

![image](https://user-images.githubusercontent.com/54442328/83395858-35b4ad80-a425-11ea-90f8-79b8fb7496b6.png)

**Comment by philipvu30** [comment]
Closed as no response.
