### ISSUE TITLE
[Fluxstore Pro Woocomerce] - Cannot update homepage via Mstore Plugin

### ISSUE THREAD

**Issue by tjain90** [inspireui/support#3502]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 
Hi team, I have raised this issue several times but no resolution. App is not picking new config.json that is uploaded via Mstore. Kindly help on this i have raised this concern several times.

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@tjain90 - could you share your login access to your site to support@inspireui.com - we will help for checking - thank you!

**Comment by tjain90** [comment]
Sent Credentials over email.

**Comment by tjain90** [comment]
App was working fine suddenly it stopped picking any data ?

**Comment by tjain90** [comment]
@minhcasi can you please check and update ?

**Comment by minhcasi** [comment]
Good news, we have fixed it - pls add toString as the screenshot - we will upload new release `1.7.5` today - thank you!

<img width="1462" alt="Screen Shot 2020-06-03 at 14 39 29" src="https://user-images.githubusercontent.com/1459805/83609146-09756a00-a5a8-11ea-9545-1052df1f966d.png">
