### ISSUE TITLE
Adding new language problem

### ISSUE THREAD

**Issue by smark98** [inspireui/support#3503]
Hi,

My last ticked closed. ( 3419 ) 

Now I attached the requested language .arb file.
[intl_hu.arb.zip](https://github.com/inspireui/support/files/4707515/intl_hu.arb.zip)

**Comment by minhcasi** [comment]
@smark98 - we will have a check on this file and let you know, thank you!

**Comment by minhcasi** [comment]
@smark98 - we have added this language on latest release `1.7.5`

**Comment by smark98** [comment]
Thank you. But the github link still restricted from so I cant available to upgrade my project.

**Comment by minhcasi** [comment]
@smark98 - pls submit access to http://gitlab.inspireui.com  - thank you!

**Comment by smark98** [comment]
Once i submitted but nothing happened. :(

**Comment by minhcasi** [comment]
it's sent to your email - pls double check :)

**Comment by smark98** [comment]
Yes, now it is works. Thank you.

**Comment by minhcasi** [comment]
let us know if you have any issues - thank you!
