### ISSUE TITLE
[Fluxstore Pro] - Brand feature request

### ISSUE THREAD

**Issue by Alnaggar94** [inspireui/support#3504]
- Hi, First of all, I would like to thank the great team behind Fluxstore. It's the best e-commerce app in the market and will be much powerful if you add the brand feature As you know the brand of a product is an important element that the customers would like to know in the product page details, It will be awesome to see such an important feature added to Fluxstore.

I use Woodmart theme and they implement it within there theme futures through Attributes, please see the screenshots below for the best practice for it:

Example of the best way to add it(Show it above the product name):
![y1](https://user-images.githubusercontent.com/49800146/83348817-91553d00-a338-11ea-90c9-f3d381dc9a24.JPG)

reference example - https://woodmart.xtemos.com/shop/furniture/panton-%d0%beunior-chair/

and when you click on the brand logo above the name it shows products filtered by brand. see this short video for example - https://streamable.com/1rcbgu

I'm not a programmer I just started learning, I think it doesn't need plugins as you can pull the data from attribute as Woodmart theme does it. see these screenshots from my dashboard on how I add brand with the logo of it :

![y2](https://user-images.githubusercontent.com/49800146/83349581-9b7a3a00-a33e-11ea-9e30-ee37e11ead9c.JPG)
![y6](https://user-images.githubusercontent.com/49800146/83349841-6e2e8b80-a340-11ea-8032-682c3a00edcf.JPG)
![y1](https://user-images.githubusercontent.com/49800146/83348817-91553d00-a338-11ea-90c9-f3d381dc9a24.JPG)
 
It already shows in fluxstore in the additional information tab in product screen:

![gt](https://user-images.githubusercontent.com/49800146/83350019-b4381f00-a341-11ea-9872-78bdf59711fa.JPG)
--------------------------------------------------------------

- That's all for the product screen and I suggest also adding brand screen containing brands as of most e-commerce apps have that feature too and when the user click the brand it open products filtered by that brand see this short video explaining  - https://streamable.com/2s9wm0

- I verified my purchase code and upload the Config Files through - http://verify.inspireui.com

**Comment by minhcasi** [comment]
@Alnaggar94 - thank you so much for your great feedback, we confirm to add this feature into the backlog and will keep new upgrade 🎉

**Comment by Alnaggar94** [comment]
Thanks for your response, We hope to see it soon in Fluxstore and again I would like thank you and your great team for your efforts, wish you all the success.

**Comment by minhcasi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Product Brand](https://trello.com/c/TUG4JB8U/51-product-brand)

**Comment by minhcasi** [comment]
moved to the backlog for implementing

**Comment by Alnaggar94** [comment]
@minhcasi - Any updates on this feature? Will it be available soon?
