### ISSUE TITLE
Problem with Status Bar - Ticket #3465

### ISSUE THREAD

**Issue by JaserJsk** [inspireui/support#3505]
+ Fluxstore Multi Vendor - Version 1.7.4
+ Flutter E-commerce Full App
+ Device : Samsung S8
+ Screenshot issue : https://ibb.co/6Y4fMYQ

+ I have downloaded the latest version and there is an issue with (**Status Bar**) and (**Appbar Icons**) on the front page.

**Comment by minhcasi** [comment]
@JaserJsk - note with investigating - thank you!

**Comment by minhcasi** [comment]
@JaserJsk - pls help us raise this comment to the same previous ticket - #3465 - thank you!
