### ISSUE TITLE
[Mstore PRO] cannot find symbol

### ISSUE THREAD

**Issue by ferizaenal** [inspireui/support#3506]
+ Detail Issues: BUILD FAILED in 26s
+ Product & version: Mstore Pro 3.9.8
+ Flutter (or React Native) version: React Native
+ Testing Device/Simulator: Lenovo k4 note
+ Screenshot issues (drag the file to attach here): 

im new in react, try to run but got stuck in this error.

[error_install.log](https://github.com/inspireui/support/files/4707581/error_install.log)

thanks

**Comment by luyx2412** [comment]
Hi @ferizaenal 
- The first please use `yarn install` to install the libraries
- After that use `yarn android` to build the app
- If appear some issues, please open android studio which will help import some libraries. After that use `yarn android` to install app on emulator.

Thanks

**Comment by ferizaenal** [comment]
> Hi @ferizaenal
> 
> * The first please use `yarn install` to install the libraries
> * After that use `yarn android` to build the app
> * If appear some issues, please open android studio which will help import some libraries. After that use `yarn android` to install app on emulator.
> 
> Thanks

dear @luyx2412 
use yarn install and then yarn android still cannot resolved the "cannot find symbol" error
is there any sollution?


 yarn android
yarn run v1.22.4
$ cd android/ && ./gradlew clean && cd ../ && react-native run-android

> Configure project :app
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCol
> Configure project :react-native-firebase_app
:react-native-firebase_app:firebase.bom using default value: 24.1.0
:react-native-firebase_app package.json found at C:\feri\ecommerce\codecanyon-DYhGKLSy-beostore-complete-react-native-template-for-ecommerce\mstore-3.9.8\mstore-pro\node_modules\@react-native-firebase\app\package.json
:react-native-firebase_app:version set from package.json: 6.7.1 (6,7,1 - 6007001)
:react-native-firebase_app:android.compileSdk using custom value: 28
:react-native-firebase_app:android.targetSdk using custom value: 28
:react-native-firebase_app:android.minSdk using custom value: 16
:react-native-firebase_app:reactNativeAndroidDir C:\feri\ecommerce\codecanyon-DYhGKLSy-beostore-complete-react-native-template-for-ecommerce\mstore-3.9.8\mstore-pro\node_modules\react-native\android

> Configure project :react-native-apple-authentication
WARNING: API 'variant.getJavaCompile()' is obsolete and has been replaced with 'variant.getJavaCompileProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getJavaCompile(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.

> Configure project :app
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 41s
19 actionable tasks: 19 up-to-date
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 1113 file(s) to forward-jetify. Using 4 workers...
info Starting JS server...
info Installing the app...

> Configure project :app
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCol
> Configure project :react-native-firebase_app
:react-native-firebase_app:firebase.bom using default value: 24.1.0
:react-native-firebase_app package.json found at C:\feri\ecommerce\codecanyon-DYhGKLSy-beostore-complete-react-native-template-for-ecommerce\mstore-3.9.8\mstore-pro\node_modules\@react-native-firebase\app\package.json
:react-native-firebase_app:version set from package.json: 6.7.1 (6,7,1 - 6007001)
:react-native-firebase_app:android.compileSdk using custom value: 28
:react-native-firebase_app:android.targetSdk using custom value: 28
:react-native-firebase_app:android.minSdk using custom value: 16
:react-native-firebase_app:reactNativeAndroidDir C:\feri\ecommerce\codecanyon-DYhGKLSy-beostore-complete-react-native-template-for-ecommerce\mstore-3.9.8\mstore-pro\node_modules\react-native\android

> Configure project :react-native-apple-authentication
WARNING: API 'variant.getJavaCompile()' is obsolete and has been replaced with 'variant.getJavaCompileProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getJavaCompile(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.

> Configure project :app
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

> Task :app:processDebugGoogleServices
Parsing json file: C:\feri\ecommerce\codecanyon-DYhGKLSy-beostore-complete-react
> Task :react-native-admob:compileDebugJavaWithJavac

> Task :react-native-apple-authentication:compileDebugJavaWithJavac

> Task :react-native-community_async-storage:compileDebugJavaWithJavac

> Task :react-native-community_netinfo:compileDebugJavaWithJavac

> Task :react-native-community_viewpager:compileDebugJavaWithJavac

> Task :react-native-facebook-account-kit:compileDebugJavaWithJavac

> Task :react-native-fbsdk:compileDebugJavaWithJavac

> Task :react-native-gesture-handler:compileDebugJavaWithJavac

> Task :react-native-linear-gradient:compileDebugJavaWithJavac

> Task :react-native-localization:compileDebugJavaWithJavac

> Task :react-native-onesignal:compileDebugJavaWithJavac

> Task :react-native-reanimated:compileDebugJavaWithJavac

> Task :react-native-restart:compileDebugJavaWithJavac

> Task :react-native-screens:compileDebugJavaWithJavac

> Task :react-native-vector-icons:compileDebugJavaWithJavac

> Task :react-native-webview:compileDebugJavaWithJavac

> Task :app:processDebugManifest
C:\feri\ecommerce\codecanyon-DYhGKLSy-beostore-complete-react-native-template-for-ecommerce\mstore-3.9.8\mstore-pro\android\app\src\debug\AndroidManifest.xml:24:9-31:50 Warning:
        activity#com.google.firebase.auth.internal.FederatedSignInActivity@android:launchMode was tagged at AndroidManifest.xml:24 to replace other declarations
> Task :app:compileDebugJavaWithJavac

> Task :app:compileDebugJavaWithJavac FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.3/userguide/command_line_interface.html#sec:command_line_warnings
186 actionable tasks: 168 executed, 18 up-to-date
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
3 warnings
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
3 warnings
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
Note: C:\feri\ecommerce\codecanyon-DYhGKLSy-beostore-complete-react-native-template-for-ecommerce\mstore-3.9.8\mstore-pro\node_modules\@react-native-community\async-storage\android\src\main\java\com\reactnativecommunity\asyncstorage\AsyncStorageModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
3 warnings
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
3 warnings
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\feri\ecommerce\codecanyon-DYhGKLSy-beostore-complete-react-native-template-for-ecommerce\mstore-3.9.8\mstore-pro\node_modules\@react-native-community\viewpager\android\src\main\java\com\reactnativecommunity\viewpager\ReactViewPagerManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 warnings
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
Note: C:\feri\ecommerce\codecanyon-DYhGKLSy-beostore-complete-react-native-template-for-ecommerce\mstore-3.9.8\mstore-pro\node_modules\react-native-facebook-account-kit\android\src\main\java\io\underscope\react\fbak\RNAccountKitModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
3 warnings
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\feri\ecommerce\codecanyon-DYhGKLSy-beostore-complete-react-native-template-for-ecommerce\mstore-3.9.8\mstore-pro\node_modules\react-native-fbsdk\android\src\main\java\com\facebook\reactnative\androidsdk\Utility.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 warnings
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
Note: C:\feri\ecommerce\codecanyon-DYhGKLSy-beostore-complete-react-native-template-for-ecommerce\mstore-3.9.8\mstore-pro\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerButtonViewManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 warnings
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
3 warnings
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
Note: C:\feri\ecommerce\codecanyon-DYhGKLSy-beostore-complete-react-native-template-for-ecommerce\mstore-3.9.8\mstore-pro\node_modules\react-native-localization\android\src\main\java\com\babisoft\ReactNativeLocalization\ReactNativeLocalization.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
3 warnings
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
Note: C:\feri\ecommerce\codecanyon-DYhGKLSy-beostore-complete-react-native-template-for-ecommerce\mstore-3.9.8\mstore-pro\node_modules\react-native-onesignal\android\src\main\java\com\geektime\rnonesignalandroid\RNOneSignal.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
3 warnings
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
Note: C:\feri\ecommerce\codecanyon-DYhGKLSy-beostore-complete-react-native-template-for-ecommerce\mstore-3.9.8\mstore-pro\node_modules\react-native-reanimated\android\src\main\java\com\swmansion\reanimated\NodesManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\feri\ecommerce\codecanyon-DYhGKLSy-beostore-complete-react-native-template-for-ecommerce\mstore-3.9.8\mstore-pro\node_modules\react-native-reanimated\android\src\main\java\com\swmansion\reanimated\NodesManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 warnings
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
3 warnings
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 warnings
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
3 warnings
Note: C:\feri\ecommerce\codecanyon-DYhGKLSy-beostore-complete-react-native-template-for-ecommerce\mstore-3.9.8\mstore-pro\node_modules\react-native-webview\android\src\main\java\com\reactnativecommunity\webview\RNCWebViewManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\feri\ecommerce\codecanyon-DYhGKLSy-beostore-complete-react-native-template-for-ecommerce\mstore-3.9.8\mstore-pro\node_modules\react-native-webview\android\src\main\java\com\reactnativecommunity\webview\RNCWebViewManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
C:\feri\ecommerce\codecanyon-DYhGKLSy-beostore-complete-react-native-template-for-ecommerce\mstore-3.9.8\mstore-pro\android\app\build\generated\rncli\src\main\java\com\facebook\react\PackageList.java:26: error: package io.invertase.firebase.auth does not exist
import io.invertase.firebase.auth.ReactNativeFirebaseAuthPackage;
                                 ^
C:\feri\ecommerce\codecanyon-DYhGKLSy-beostore-complete-react-native-template-for-ecommerce\mstore-3.9.8\mstore-pro\android\app\build\generated\rncli\src\main\java\com\facebook\react\PackageList.java:102: error: cannot find symbol
      new ReactNativeFirebaseAuthPackage(),
          ^
  symbol:   class ReactNativeFirebaseAuthPackage
  location: class PackageList
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 13s

error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
3 warnings
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
3 warnings
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
Note: C:\feri\ecommerce\codecanyon-DYhGKLSy-beostore-complete-react-native-template-for-ecommerce\mstore-3.9.8\mstore-pro\node_modules\@react-native-community\async-storage\android\src\main\java\com\reactnativecommunity\asyncstorage\AsyncStorageModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
3 warnings
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
3 warnings
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\feri\ecommerce\codecanyon-DYhGKLSy-beostore-complete-react-native-template-for-ecommerce\mstore-3.9.8\mstore-pro\node_modules\@react-native-community\viewpager\android\src\main\java\com\reactnativecommunity\viewpager\ReactViewPagerManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 warnings
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
Note: C:\feri\ecommerce\codecanyon-DYhGKLSy-beostore-complete-react-native-template-for-ecommerce\mstore-3.9.8\mstore-pro\node_modules\react-native-facebook-account-kit\android\src\main\java\io\underscope\react\fbak\RNAccountKitModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
3 warnings
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\feri\ecommerce\codecanyon-DYhGKLSy-beostore-complete-react-native-template-for-ecommerce\mstore-3.9.8\mstore-pro\node_modules\react-native-fbsdk\android\src\main\java\com\facebook\reactnative\androidsdk\Utility.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 warnings
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
Note: C:\feri\ecommerce\codecanyon-DYhGKLSy-beostore-complete-react-native-template-for-ecommerce\mstore-3.9.8\mstore-pro\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerButtonViewManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 warnings
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
3 warnings
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
Note: C:\feri\ecommerce\codecanyon-DYhGKLSy-beostore-complete-react-native-template-for-ecommerce\mstore-3.9.8\mstore-pro\node_modules\react-native-localization\android\src\main\java\com\babisoft\ReactNativeLocalization\ReactNativeLocalization.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
3 warnings
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
Note: C:\feri\ecommerce\codecanyon-DYhGKLSy-beostore-complete-react-native-template-for-ecommerce\mstore-3.9.8\mstore-pro\node_modules\react-native-onesignal\android\src\main\java\com\geektime\rnonesignalandroid\RNOneSignal.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
3 warnings
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
Note: C:\feri\ecommerce\codecanyon-DYhGKLSy-beostore-complete-react-native-template-for-ecommerce\mstore-3.9.8\mstore-pro\node_modules\react-native-reanimated\android\src\main\java\com\swmansion\reanimated\NodesManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\feri\ecommerce\codecanyon-DYhGKLSy-beostore-complete-react-native-template-for-ecommerce\mstore-3.9.8\mstore-pro\node_modules\react-native-reanimated\android\src\main\java\com\swmansion\reanimated\NodesManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 warnings
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
3 warnings
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 warnings
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
3 warnings
Note: C:\feri\ecommerce\codecanyon-DYhGKLSy-beostore-complete-react-native-template-for-ecommerce\mstore-3.9.8\mstore-pro\node_modules\react-native-webview\android\src\main\java\com\reactnativecommunity\webview\RNCWebViewManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\feri\ecommerce\codecanyon-DYhGKLSy-beostore-complete-react-native-template-for-ecommerce\mstore-3.9.8\mstore-pro\node_modules\react-native-webview\android\src\main\java\com\reactnativecommunity\webview\RNCWebViewManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
C:\feri\ecommerce\codecanyon-DYhGKLSy-beostore-complete-react-native-template-for-ecommerce\mstore-3.9.8\mstore-pro\android\app\build\generated\rncli\src\main\java\com\facebook\react\PackageList.java:26: error: package io.invertase.firebase.auth does not exist
import io.invertase.firebase.auth.ReactNativeFirebaseAuthPackage;
                                 ^
C:\feri\ecommerce\codecanyon-DYhGKLSy-beostore-complete-react-native-template-for-ecommerce\mstore-3.9.8\mstore-pro\android\app\build\generated\rncli\src\main\java\com\facebook\react\PackageList.java:102: error: cannot find symbol
      new ReactNativeFirebaseAuthPackage(),
          ^
  symbol:   class ReactNativeFirebaseAuthPackage
  location: class PackageList
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 13s

    at checkExecSyncError (child_process.js:616:11)
    at execFileSync (child_process.js:634:13)
    at runOnAllDevices (C:\feri\ecommerce\codecanyon-DYhGKLSy-beostore-complete-react-native-template-for-ecommerce\mstore-3.9.8\mstore-pro\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:94:39)
    at buildAndRun (C:\feri\ecommerce\codecanyon-DYhGKLSy-beostore-complete-react-native-template-for-ecommerce\mstore-3.9.8\mstore-pro\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:179:41)
    at then.result (C:\feri\ecommerce\codecanyon-DYhGKLSy-beostore-complete-react-native-template-for-ecommerce\mstore-3.9.8\mstore-pro\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:133:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by luyx2412** [comment]
HI @ferizaenal Follow the issues something was wrong with install environment, so please follow the document to install your environment https://reactnative.dev/docs/environment-setup

Thanks

**Comment by luyx2412** [comment]
Closed!
P/S: Feel free to reopen the issue.
