### ISSUE TITLE
MStore Pro Expo - products are loaded without the images 

### ISSUE THREAD

**Issue by GuyAvraham** [inspireui/support#3509]
MStore Pro Expo - products are loaded without the images 
+ Testing Device/Simulator: 
No product images on real devices and on simulator.

+ Screenshot issues (drag the file to attach here): 
![image](https://user-images.githubusercontent.com/4614438/83358507-b5d30880-a37c-11ea-9c13-dc4d1309a137.png)

**Comment by minhcasi** [comment]
@GuyAvraham - could you help to check the product display image issue/solution on this link https://docs.inspireui.com/mstore/woo-setting/#product-display-sizes

**Comment by GuyAvraham** [comment]
@minhcasi Thanks. 
1. The reason I missed it - The page before said that the thumbnail addon is optional.
2. What is the meaning of the productSize definition? where is the appConfig json file should it be?

**Comment by minhcasi** [comment]
@GuyAvraham - thank you for the quick response

The `ProductSize` is used to optimize image loading on Mstore product while combine with the Regenerate Image, if it is turn off the product image will load as full size that causes performance loading from app issues.

"It turned all my product images with from having transparent background to have black one." - i'm not sure on this question, if you are using the plugin, the image will be generate more smaller size, not impact to your existing files.

**Comment by GuyAvraham** [comment]
@minhcasi thanks!
Where should the ProductSize be on the appConfig.json? 
Should it be on the root?
![image](https://user-images.githubusercontent.com/4614438/83622464-adefb000-a598-11ea-8ca1-bb023f030441.png)
