### ISSUE TITLE
[MStore Pro] reviews

### ISSUE THREAD

**Issue by eduardo9104** [inspireui/support#351]
**Required Info (please complete the following information):**
 - Product: [MStore]
 - Your Purchased Code: eba4998b-49c3-4eb0-b750-0c77d53df1ae

**Describe the bug**
the comments on the product are not saved in wordpress.

**Screenshots**

**Additional context**
let requestUrl = `${this.url}/api/mstore_user/post_comment/?insecure=cool`;
where is de url in wordpress?, I do not find.

**Comment by luyx2412** [comment]
HI @eduardo9104 

The url is this function, you can see the photo. https://www.screencast.com/t/hj3HfaaPY

Thanks

**Comment by eduardo9104** [comment]
Hi, the problem is that the post_comment function I can not find in wordpress module.

**Comment by minhcasi** [comment]
Hi, could you follow this guide for active the mstore_checkout https://docs.mstore.io/basic-app-setting - this plugin will content the post_comment - thank you!
