### ISSUE TITLE
Problem with Xcode 

### ISSUE THREAD

**Issue by Khaled1979** [inspireui/support#3510]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
+ Product & version:
3.9.8
+ Flutter (or React Native) version:
react-native@0.62.2 
+ Testing Device/Simulator:
Xcode Iphone XR 
+ Screenshot issues (drag the file to attach here): 

[https://ibb.co/7JfGMqQ](url)
[https://ibb.co/cbLrZc6](url)

**Comment by Khaled1979** [comment]
Step 1 (require): describe detail issues & screenshots

Detail Issues:
Product & version:
3.9.8
Flutter (or React Native) version:
react-native@0.62.2
Testing Device/Simulator:
Xcode Iphone XR
Screenshot issues (drag the file to attach here):
[https://ibb.co/7JfGMqQ]
[https://ibb.co/cbLrZc6]

Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com

Purchase code: 0946e7c6-3d0a-4398-a04a-a75dfb456e63

Important Note:

We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
Kindly create only One Ticket & includes all the issues, that would help us focus to resolve it better.
If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID
Thank you so much for your time 😊

**Comment by luyx2412** [comment]
HI @Khaled1979 Please send me the screenshot issue. It will investigate easier.

Thanks

**Comment by Khaled1979** [comment]
Please check the first comment I added two links:
https://ibb.co/7JfGMqQ
https://ibb.co/cbLrZc6
 which contains the screen shots and the  ticket also

**Comment by luyx2412** [comment]
Hi @Khaled1979 Please go to the ios folder and using `pod install` . After that build app again.

Thanks

**Comment by Khaled1979** [comment]
Same Problem :(

**Comment by luyx2412** [comment]
Hi @Khaled1979 Please make sure you followed the document to install the app. https://docs.inspireui.com/mstore/getting-started/ the message issue related missing install libraries.

Thanks

**Comment by luyx2412** [comment]
Closed!
P/S: Feel free to reopen the issue.
