### ISSUE TITLE
search field does not accept accents

### ISSUE THREAD

**Issue by joaonathan** [inspireui/support#3511]
Product & version: Fluxstore 1.7.4
Flutter (or React Native) version:  Flutter
Testing Device/Simulator: Xiaomi mi a2

my language is brazilian portuguese, some words have accents (~, ^, ´, `) like for example (feijão, macarrão, óleo), when i type words without accent the search is done correctly, but when i type accent the product is not found.

how could i solve this problem?
![WhatsApp Image 2020-05-31 at 20 56 00 (1)](https://user-images.githubusercontent.com/9143192/83365957-7efff100-a382-11ea-80cf-7104df68eabc.jpeg)

![WhatsApp Image 2020-05-31 at 20 56 00](https://user-images.githubusercontent.com/9143192/83365960-81fae180-a382-11ea-9e7c-7abae503756e.jpeg)

**Comment by minhcasi** [comment]
@joaonathan - could I know if your website has enabled the `https`? The search could have a problem on `http` website

**Comment by philipvu30** [comment]
Hi,

Currently, there is an issue with the search on the Home Page. You can consider changing to use the search option on the Tab Bar by adding this JSON in your config_xx.json files.

![image](https://user-images.githubusercontent.com/54442328/83506383-50ecef00-a4f1-11ea-8b5b-24494830b927.png)

Thank you.

**Comment by joaonathan** [comment]
Ok, thanks.
