### ISSUE TITLE
Firebase Cloud Messaging in FOREGROUND Issue

### ISSUE THREAD

**Issue by enriqueleon80** [inspireui/support#3512]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
There is a known issue with how FLUTTER manages firebase messages in the foreground.  This is tracked in a number of online threads, one for example is here:https://stackoverflow.com/questions/54643294/flutter-foreground-notification-is-not-working-in-firebase-messaging.

To summarize, when a PUSH notification from firebase is sent in foreground, the user gets no indication he received a message without going to the NOTIFICATIONS section.  Could the application raise the message in the SNACKBAR or in some other way?  We plan to rely very heavily on CLOUD messaging and not having this feature will be a very big problem for us.

This issue only affects IOS as far we can tell.

PS: We see some code in the APPDELEGATE which seems like you tried to address this? But it might not be working?

I've looked into this issue myself 
+ Product & version: MultiStore 1.7.3

+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@enriqueleon80 - thank you for your sharing, we will investigate this issue and keep an update - very best!

**Comment by minhcasi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Firebare Push notification - foreground fixing](https://trello.com/c/jp3R5Fgg/52-firebare-push-notification-foreground-fixing)

**Comment by minhcasi** [comment]
moved to backlogs for further implementing - thank you!

**Comment by enriqueleon80** [comment]
Epic. Thank you keep up the great work and support


Enrique Leon
M 404.226.9904
