### ISSUE TITLE
(WCFM) New product create with photo not working 

### ISSUE THREAD

**Issue by mamunag8** [inspireui/support#3513]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
WCFM New product with photo not working. Without photo no problem. Photo not uploading to server or creating product. Please solve it.

screenshot : https://paste.pics/96EB5

+ Product & version:
+ Flutter version: 
+ Testing Device/Simulator: AS
+ Screenshot issues (drag the file to attach here): 
screenshot : https://paste.pics/96EB5
![96EB5](https://user-images.githubusercontent.com/33388253/83375261-1d766b80-a3f0-11ea-9121-0dd1430ebd11.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

![1](https://user-images.githubusercontent.com/33388253/83375159-c40e3c80-a3ef-11ea-9007-d64621dd9217.JPG)

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by philipvu30** [comment]
Hi,

Please verify your information via this [form](http://verify.inspireui.com/) for further assistance.
As I cannot find your config files in the form above, I cannot replicate your issue. Sorry.

**Comment by philipvu30** [comment]
Closed as no response.
