### ISSUE TITLE
Product not showing on home page (layout fourColumn) FLUXSTORE MV

### ISSUE THREAD

**Issue by yassiney120** [inspireui/support#3514]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 1 categorie is not showing on the app but on fluxbuilder & old version it's working
+ Product & version: fluxstore MV V : 1.7.4
+ Flutter (or React Native) version: 1.17.2
+ Testing Device/Simulator: iphone se 2 (SIMULATOR )& iphone 11 pro max (real device)

skype : mohdar@fleure.ma
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com
<img width="1316" alt="Screen Shot 2020-06-01 at 9 11 28 AM" src="https://user-images.githubusercontent.com/8164673/83378282-552de500-a3e9-11ea-8894-8426ea84249f.png">
<img width="1792" alt="Screen Shot 2020-06-01 at 9 14 13 AM" src="https://user-images.githubusercontent.com/8164673/83378306-6545c480-a3e9-11ea-8535-1be24b98bc07.png">

_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by xsamir** [comment]
It's a common problem, and to fix it just simply go to your **WordPress** dashboard as Admin
then go to **Tool > Regenerate Thumbnails**
Then Regenerate Thumbnails All your attachments

**Comment by yassiney120** [comment]
Already done but it's only in 1 categories all others  working fine

**Comment by yassiney120** [comment]
![1653DB61-CF6B-4D5B-8506-9C289E02762C](https://user-images.githubusercontent.com/8164673/83395534-86b7a800-a40b-11ea-959c-3ac1493dc5c6.png)

**Comment by xsamir** [comment]
I'm sure it's something on the WP dashboard.
Can you go please to your WordPress then **edit the category** , and make sure that the **Display option is Default**

**Comment by xsamir** [comment]
Oh, it's with the new arrival section
That problem I already pass it by changing the layout, because there's some layout on the app doesn't show the new arrivals (الله يعينك)

**Comment by yassiney120** [comment]
I try to change layout also but no chance شكرا  لمساعدتك

**Comment by yassiney120** [comment]
problem solved ( I'm adding Automatique product so there is no vendor name for that it's not showing )
thank you
