### ISSUE TITLE
Display header image behind Status Bar

### ISSUE THREAD

**Issue by JaserJsk** [inspireui/support#3515]
Product & version :: **1.7.4**
Flutter (or React Native) version :: **Flutter**
Testing Device/Simulator :: **Samsung S8**
Screenshot :: **https://ibb.co/6Y4fMYQ**

**This is the second time I'm creating this issue.
I hope that you will not delete it for no reason like last time**

**The issue is that there is a problem with the - (Status Bar) and (Action Buttons) on Android when running the app the first time. This a new issue in 1.7.4**

**On the (Action Buttons) I need to know how to change the colors of the Icons.**

**The earlier version did not have this issue**

**Look at the screenshot and please tell me how to fix this.**

**Comment by minhcasi** [comment]
@JaserJsk - could you able to create One ticket for your all comments/ issues? As you have created multiple tickets we will close and group to one ticket.

**Comment by philipvu30** [comment]
Hi @JaserJsk,

My apologies for any convenience that we may have caused. But we recommend users to post all of the issues in one ticket. You can see that at the very first line when submitting our verification form.

Here are the fixed solutions:
1. Status bar: add this code "Utils.setStatusBarWhiteForeground(false);" in lib/screens/settings/settings.dart under build function like this.
![image](https://user-images.githubusercontent.com/54442328/83392464-5843c800-a41f-11ea-9f4e-8da0fac377f0.png)

2. In your config_xx.json, add this term 
![image](https://user-images.githubusercontent.com/54442328/83392620-99d47300-a41f-11ea-85c0-b475fc960dd2.png)

I hope these solutions are able to solve your trouble.

**Comment by JaserJsk** [comment]
**If I'am supposed to keep all my issues in same ticket - then am I supposed to update the Title everytime I repport a new issue or just keep the original ???**

**Comment by philipvu30** [comment]
Hi,

Just keep it original. Thank you.

**Comment by JaserJsk** [comment]
How can I make it so that the header image is displayed behind the Status Bar

I don't want just a white background for the Status Bar

**Comment by philipvu30** [comment]
Hi,

Navigate to this file lib/screens/home/home.dart and remove the SafeArea widget that wraps this Consumer widget.

![image](https://user-images.githubusercontent.com/54442328/83479673-7cf17b80-a4c3-11ea-8beb-2328d2179513.png)

Or just simply replace this file [home.dart.zip](https://github.com/inspireui/support/files/4714743/home.dart.zip)

**Comment by JaserJsk** [comment]
**I replaced the - home.dart file but still it did not fix the issue**

**Take a look at the screenshot :** https://ibb.co/B4ywCRF

**Comment by philipvu30** [comment]
Hi,

Sorry I did not give you enough information. Here are the next steps you have to do after replace the home.dart
- In main.dart, change the code to the highlighted term
![image](https://user-images.githubusercontent.com/54442328/83490595-7fab9b00-a4da-11ea-8c10-94dfe5d2befd.png)

- In the config_xx.json, set StickyHeader to false.

That's all you have to do. :)

**Comment by JaserJsk** [comment]
**Thank you for helping me fix the above issue.**

**I have another issue that I want to fix.**
**I will post here instead of creating a new ticket and see how that works.**

**Please tahe alook at the screenshot :** https://ibb.co/bNGgJyt

In the attached image, there are 3 issues that I want to fix

**Comment by philipvu30** [comment]
Hi,

In the lib/widgets/home/header/header_search.dart, add this line

![image](https://user-images.githubusercontent.com/54442328/83508110-ab874a80-a4f3-11ea-95f9-e9216a995dea.png)

**Comment by JaserJsk** [comment]
**Thank you for the fix ?**

**I have another issue That I need help with.**

**Do I post it here or create a new ticket ?**

**Comment by philipvu30** [comment]
Hi,

We recommend users to post all of their issues in 1 ticket only. It would be great if you do so.
Also, if you are happy with our service/support, please consider rating us on your [download page](https://codecanyon.net/downloads)

Thank you.

**Comment by JaserJsk** [comment]
**This is my other issue that I need help with**
**I will post here instead of creating a new ticket and see how that works.**

**Please take alook at the screenshot :** https://ibb.co/bNGgJyt

**In the attached image, there are 3 issues that I need to fix**

<blockquote><img src="https://i.ibb.co/DwjDp6d/categoriy-issues.jpg" width="48" align="right"><div><img src="//simgbb.com/images/favicon.png" height="14"> ImgBB</div><div><strong><a href="https://ibb.co/bNGgJyt">categoriy-issues</a></strong></div><div>Image categoriy-issues hosted in ImgBB</div></blockquote>

**Comment by philipvu30** [comment]
Hi,

Well, would you mind giving a more detailed explanation regarding to your issue? It would be great if you can include images.

Thank you.

**Comment by JaserJsk** [comment]
**After adding like you said -** margin: const EdgeInsets.only(bottom: 10.0),

**I got this result -** https://ibb.co/k43Fjct

**Comment by philipvu30** [comment]
Hi,

To remind you, all of your requests above are not related to bugs/issues/features, they are called "customization requests". And usually, we do not support this kind of request. 

If that did not work, try to set this height from 0.3 to 0.4 in your config_xx.json

![image](https://user-images.githubusercontent.com/54442328/83513775-97941680-a4fc-11ea-917a-16dbd3e6c523.png)

**Comment by JaserJsk** [comment]
**I understand that this is not bugs, but the reason I meantion this here in a ticket is becouse I did not have this issue in Version 1.7.3**

**Comment by JaserJsk** [comment]
**So it is finally working properly now and thank you the help.**

**There is one more thing I would kindly request your help with.**
**I will post here instead of creating a new ticket and see how that works.**

**Please take alook at the screenshot :** https://ibb.co/bNGgJyt

**In the attached image, there are 3 issues that I need to fix if possible**

**Comment by philipvu30** [comment]
Hi,

1. It seems you fixed it yourself?
2. Currently, it only supports up to the second category level.
3. It happens because the data on your website is incorrect. It shows 0 in the returned JSON
![image](https://user-images.githubusercontent.com/54442328/83618832-37ad7680-a5b5-11ea-88d6-0d0a734b03cf.png)

**Comment by JaserJsk** [comment]
How do I correct the **DATA** count on my website.

Can you please help me with this.

**Comment by philipvu30** [comment]
Hi,

You could try to press the Update button for that category (Kids). This trick worked before. Now, I don't know. 

![image](https://user-images.githubusercontent.com/54442328/83623531-a55ca100-a5bb-11ea-9484-06fd06cd9620.png)

**Comment by JaserJsk** [comment]
I tried that but did not work

Is there no other solution ?

**Comment by philipvu30** [comment]
Hi,

This issue is related to your website data. Please stop making it like it is a bug from our app.

If you want to remove or change anything, please use Inspector Tool in Android Studio. You can find the tutorial [here](https://youtu.be/Rx8HhadjKcw?t=337) and refer to this official [doc](https://flutter.dev/docs/development/tools/devtools/inspector).

Thank you.

**Comment by JaserJsk** [comment]
**I did not know about the inspector tool.**

**The only reason I made a ticket with this issues is becouse I did not have these issues in 
Version 1.7.3**

**I don't know what happend in in Version 1.7.4 to make all of this issues appear.**

**Comment by JaserJsk** [comment]
**Also when I bought this Item - I could only test the Demo app**

**SO therefore please do not get upset if I point out that your Application does not work like the Demo Advertised**

**Comment by philipvu30** [comment]
Hi,

Firstly, please stop using bold and UPPERCASE words. It makes our conversation not comfortable.

Secondly, we do not get upset when customers pointed out the bugs. Instead, we are happy if users help us improve the app by doing that. But for most of your questions, they are related to "customization" requests that we are not required to answer.

Thirdly, here is your fixed solution. Replace this file in lib/screens/categories/card.dart
[card.dart.zip](https://github.com/inspireui/support/files/4727356/card.dart.zip)

Thank you and have a good day.
