### ISSUE TITLE
showing the loading screen while re-installation and not showing the on boarding for some devices

### ISSUE THREAD

**Issue by mmasifashraf** [inspireui/support#3516]
showing the progress  loading screen while re installation and showing the on boarding for some devices. But App will open after re open the session.

![sasasa](https://user-images.githubusercontent.com/44862509/83384373-cec8d180-a3ef-11ea-9415-b845aa876ca1.PNG)

**Comment by minhcasi** [comment]
Sorry i'm not sure to understand your point, what is your detail test case?

**Comment by mmasifashraf** [comment]
on-boarding is not working 👯

**Comment by bananeasamoah** [comment]
I think it's your animation file, check it out. I was having the same issues too.

**Comment by mmasifashraf** [comment]
Im using the jpg image for flash screen. Issue with the on boarding screen. Is it also a n animation?

**Comment by minhcasi** [comment]
@mmasifashraf - it seems they team have fixed this issue on latest `1.7.5` - we will release it today
