### ISSUE TITLE
Variable Product Short Description Not Showing...

### ISSUE THREAD

**Issue by omman** [inspireui/support#3518]
Hi, I am using Variable Product and My Variable Product is Different from Each Product So We write Short Description on Each Product so that when variable Product Change the Variation also it will show the short description. Please Help me to fix this.

Thanks and Best Regards

**Comment by minhcasi** [comment]
@omman - could you share your Rest API result and point us which field you need to show on app? Thanks

**Comment by omman** [comment]
Hi,
Web Link: https://www.qutoof.qa/product/tomato-cherry/
https://www.qutoof.qa/wp-json/wc/v3/products/4655/variations

There is 3 Variation Short Description 
1)  "description": "<p>1 Packet<\/p>\n",
2) "description": "<p>4 Packet<\/p>\n",
3) "description": "<p>2 Packet<\/p>\n",



`[
  {
    "id": 9284,
    "date_created": "2020-05-21T10:35:22",
    "date_created_gmt": "2020-05-21T07:35:22",
    "date_modified": "2020-05-21T10:37:48",
    "date_modified_gmt": "2020-05-21T07:37:48",
    "description": "<p>1 Packet<\/p>\n",
    "permalink": "https:\/\/www.qutoof.qa\/product\/tomato-cherry\/?attribute_pa_weight=250gm",
    "sku": "qtf-tomato-cherry-095-03",
    "price": "8.50",
    "regular_price": "8.50",
    "sale_price": "",
    "date_on_sale_from": null,
    "date_on_sale_from_gmt": null,
    "date_on_sale_to": null,
    "date_on_sale_to_gmt": null,
    "on_sale": false,
    "status": "publish",
    "purchasable": true,
    "virtual": false,
    "downloadable": false,
    "downloads": [],
    "download_limit": -1,
    "download_expiry": -1,
    "tax_status": "taxable",
    "tax_class": "",
    "manage_stock": false,
    "stock_quantity": null,
    "stock_status": "instock",
    "backorders": "no",
    "backorders_allowed": false,
    "backordered": false,
    "weight": "",
    "dimensions": {
      "length": "",
      "width": "",
      "height": ""
    },
    "shipping_class": "",
    "shipping_class_id": 0,
    "image": {
      "id": 9282,
      "date_created": "2020-05-21T13:32:05",
      "date_created_gmt": "2020-05-21T07:32:05",
      "date_modified": "2020-05-21T13:32:05",
      "date_modified_gmt": "2020-05-21T07:32:05",
      "src": "https:\/\/www.qutoof.qa\/wp-content\/uploads\/2020\/04\/qtf_Tomato_Cherry_image_3.jpg",
      "name": "qtf_Tomato_Cherry_image_3",
      "alt": ""
    },
    "attributes": [
      {
        "id": 3,
        "name": "Weight",
        "option": "250 gm"
      }
    ],
    "menu_order": 1,
    "meta_data": [
      {
        "id": 56027,
        "key": "_wpml_word_count",
        "value": "{\"total\":0,\"to_translate\":{\"ar\":6,\"en\":6}}"
      },
      {
        "id": 56028,
        "key": "_wpml_media_featured",
        "value": "1"
      },
      {
        "id": 56029,
        "key": "_wpml_media_duplicate",
        "value": "1"
      }
    ],
    "_links": {
      "self": [
        {
          "href": "https:\/\/www.qutoof.qa\/wp-json\/wc\/v3\/products\/4655\/variations\/9284"
        }
      ],
      "collection": [
        {
          "href": "https:\/\/www.qutoof.qa\/wp-json\/wc\/v3\/products\/4655\/variations"
        }
      ],
      "up": [
        {
          "href": "https:\/\/www.qutoof.qa\/wp-json\/wc\/v3\/products\/4655"
        }
      ]
    }
  },
  {
    "id": 8898,
    "date_created": "2020-05-16T00:20:46",
    "date_created_gmt": "2020-05-15T21:20:46",
    "date_modified": "2020-05-21T10:37:30",
    "date_modified_gmt": "2020-05-21T07:37:30",
    "description": "<p>4 Packet<\/p>\n",
    "permalink": "https:\/\/www.qutoof.qa\/product\/tomato-cherry\/?attribute_pa_weight=per-kg",
    "sku": "qtf-tomato-cherry-095-02",
    "price": "34",
    "regular_price": "34",
    "sale_price": "",
    "date_on_sale_from": null,
    "date_on_sale_from_gmt": null,
    "date_on_sale_to": null,
    "date_on_sale_to_gmt": null,
    "on_sale": false,
    "status": "publish",
    "purchasable": true,
    "virtual": false,
    "downloadable": false,
    "downloads": [],
    "download_limit": -1,
    "download_expiry": -1,
    "tax_status": "taxable",
    "tax_class": "",
    "manage_stock": false,
    "stock_quantity": null,
    "stock_status": "instock",
    "backorders": "no",
    "backorders_allowed": false,
    "backordered": false,
    "weight": "",
    "dimensions": {
      "length": "",
      "width": "",
      "height": ""
    },
    "shipping_class": "",
    "shipping_class_id": 0,
    "image": {
      "id": 9282,
      "date_created": "2020-05-21T13:32:05",
      "date_created_gmt": "2020-05-21T07:32:05",
      "date_modified": "2020-05-21T13:32:05",
      "date_modified_gmt": "2020-05-21T07:32:05",
      "src": "https:\/\/www.qutoof.qa\/wp-content\/uploads\/2020\/04\/qtf_Tomato_Cherry_image_3.jpg",
      "name": "qtf_Tomato_Cherry_image_3",
      "alt": ""
    },
    "attributes": [
      {
        "id": 3,
        "name": "Weight",
        "option": "Per kg"
      }
    ],
    "menu_order": 3,
    "meta_data": [
      {
        "id": 44490,
        "key": "_wpml_word_count",
        "value": "{\"total\":0,\"to_translate\":{\"ar\":6,\"en\":6}}"
      },
      {
        "id": 44491,
        "key": "_wpml_media_featured",
        "value": "1"
      },
      {
        "id": 44492,
        "key": "_wpml_media_duplicate",
        "value": "1"
      },
      {
        "id": 55729,
        "key": "_yith_wfbt_data",
        "value": {
          "products": "",
          "default_variation": "",
          "num_visible": ""
        }
      }
    ],
    "_links": {
      "self": [
        {
          "href": "https:\/\/www.qutoof.qa\/wp-json\/wc\/v3\/products\/4655\/variations\/8898"
        }
      ],
      "collection": [
        {
          "href": "https:\/\/www.qutoof.qa\/wp-json\/wc\/v3\/products\/4655\/variations"
        }
      ],
      "up": [
        {
          "href": "https:\/\/www.qutoof.qa\/wp-json\/wc\/v3\/products\/4655"
        }
      ]
    }
  },
  {
    "id": 8897,
    "date_created": "2020-05-16T00:20:46",
    "date_created_gmt": "2020-05-15T21:20:46",
    "date_modified": "2020-05-21T10:37:30",
    "date_modified_gmt": "2020-05-21T07:37:30",
    "description": "<p>2 Packet<\/p>\n",
    "permalink": "https:\/\/www.qutoof.qa\/product\/tomato-cherry\/?attribute_pa_weight=500gm",
    "sku": "qtf-tomato-cherry-095-01",
    "price": "17",
    "regular_price": "17",
    "sale_price": "",
    "date_on_sale_from": null,
    "date_on_sale_from_gmt": null,
    "date_on_sale_to": null,
    "date_on_sale_to_gmt": null,
    "on_sale": false,
    "status": "publish",
    "purchasable": true,
    "virtual": false,
    "downloadable": false,
    "downloads": [],
    "download_limit": -1,
    "download_expiry": -1,
    "tax_status": "taxable",
    "tax_class": "",
    "manage_stock": false,
    "stock_quantity": null,
    "stock_status": "instock",
    "backorders": "no",
    "backorders_allowed": false,
    "backordered": false,
    "weight": "",
    "dimensions": {
      "length": "",
      "width": "",
      "height": ""
    },
    "shipping_class": "",
    "shipping_class_id": 0,
    "image": {
      "id": 9282,
      "date_created": "2020-05-21T13:32:05",
      "date_created_gmt": "2020-05-21T07:32:05",
      "date_modified": "2020-05-21T13:32:05",
      "date_modified_gmt": "2020-05-21T07:32:05",
      "src": "https:\/\/www.qutoof.qa\/wp-content\/uploads\/2020\/04\/qtf_Tomato_Cherry_image_3.jpg",
      "name": "qtf_Tomato_Cherry_image_3",
      "alt": ""
    },
    "attributes": [
      {
        "id": 3,
        "name": "Weight",
        "option": "500 gm"
      }
    ],
    "menu_order": 2,
    "meta_data": [
      {
        "id": 44470,
        "key": "_wpml_word_count",
        "value": "{\"total\":0,\"to_translate\":{\"ar\":6,\"en\":6}}"
      },
      {
        "id": 44471,
        "key": "_wpml_media_featured",
        "value": "1"
      },
      {
        "id": 44472,
        "key": "_wpml_media_duplicate",
        "value": "1"
      },
      {
        "id": 55728,
        "key": "_yith_wfbt_data",
        "value": {
          "products": "",
          "default_variation": "",
          "num_visible": ""
        }
      }
    ],
    "_links": {
      "self": [
        {
          "href": "https:\/\/www.qutoof.qa\/wp-json\/wc\/v3\/products\/4655\/variations\/8897"
        }
      ],
      "collection": [
        {
          "href": "https:\/\/www.qutoof.qa\/wp-json\/wc\/v3\/products\/4655\/variations"
        }
      ],
      "up": [
        {
          "href": "https:\/\/www.qutoof.qa\/wp-json\/wc\/v3\/products\/4655"
        }
      ]
    }
  }
]`

**Comment by minhcasi** [comment]
Hi, this feature is not available, you could try to add new mapping for the description, then show it when the product variant selection is change (refer to the product variant from image)

<img width="1052" alt="Screen Shot 2020-06-01 at 20 00 53" src="https://user-images.githubusercontent.com/1459805/83411520-9c948f80-a442-11ea-856b-4e93263927bf.png">

**Comment by minhcasi** [comment]
As this is new customization request that not include from our support, please try your best with the custom work - thank you for your time!
