### ISSUE TITLE
[ Fluxstore Woocommerce ] - Screen Layout Minor Changes

### ISSUE THREAD

**Issue by swspro** [inspireui/support#3519]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 

Hi @minhcasi ,

I need your help on making minor changes to the Screen design

### 1 ) Toggle Menu - Want to Replace with another images [ Refer to the Screenshot ] . Tried Flutter Inspector but could not find the Menu Icon to replace . Please suggest how to do it.
![Screen Shot 2020-06-01 at 4 28 49 PM](https://user-images.githubusercontent.com/15525566/83403468-6517ea00-a426-11ea-9656-c2b47376d3e6.png)

### 2 ) Sidebar Menu - Want to Remove the BLANK SPACE above the Logo of the Sidebar menu Option . Please refer to the Screenshot

![Screen Shot 2020-06-01 at 4 29 26 PM](https://user-images.githubusercontent.com/15525566/83403632-b32ced80-a426-11ea-943b-0ec187af872b.png)

### 3 ) Category Page - Want to make the CATEGORIES HEADING Font Size Smaller . But not able to locate the file . Please refer to the Screenshot

![WhatsApp Image 2020-06-01 at 16 26 49](https://user-images.githubusercontent.com/15525566/83403905-364e4380-a427-11ea-9abc-e16f3325689f.jpeg)

+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
1. you can change from the `widgets/home/logo.dart` search `Icons.blur_on`
2. update `menu.dart`, the `DrawerHeader` widget
3. edit this file https://tppr.me/YA4XM

Please note that we may not answer these 'how to' customize questions in the future due to the scope of our support. Please try your best with the inspector tool https://www.youtube.com/results?search_query=inspector+flutter
