### ISSUE TITLE
[ListApp] Install Issue

### ISSUE THREAD

**Issue by bobozd** [inspireui/support#352]
here is my files. It can't load listings from my site. Only blog posts loaded.
need help asap.

Listings from backend is ID51,50 that I need...

[Archive.zip](https://github.com/inspireui/support/files/2916353/Archive.zip)
![screen shot 2019-02-28 at 19 23 14](https://user-images.githubusercontent.com/28021993/53588973-77a1d480-3b8e-11e9-93b9-a1bcfcbb009f.png)
![screen shot 2019-02-28 at 19 23 21](https://user-images.githubusercontent.com/28021993/53588980-7c668880-3b8e-11e9-9285-193ae86ca59b.png)
![screen shot 2019-02-28 at 19 27 34](https://user-images.githubusercontent.com/28021993/53589202-14fd0880-3b8f-11e9-876b-91df87d344dc.png)
![screen shot 2019-02-28 at 19 28 08](https://user-images.githubusercontent.com/28021993/53589208-175f6280-3b8f-11e9-9c47-e34159a6c72f.png)

**Comment by thangvo9x** [comment]
Hi, I can't access to your site. Please check on your server.
https://gyazo.com/c2e4cb7d551d6ad786c6b4d4d052ce2f
Thanks

**Comment by bobozd** [comment]
Where i need to ad this, or send me your email so i can send you my web
access data

pet, 1. ožu 2019. 04:10 thangvo9x <notifications@github.com> je napisao:

**Comment by thangvo9x** [comment]
Hi. Our Product has only support ListApp, Listify, MyListing templates . Only these templates.
Please check again. Thanks

**Comment by bobozd** [comment]
I use Listapp with Mylisting theme which I mention few times.
I'm pretty unsatisfied with your support.
I just want my app to work like in demo and connect to my site.
I loose few months with you on this one. Just to make it working, nothing
else !!!
Please solve this issue and make my app working ASAP or I will ask for
refund.
This is very unprofessional. For any info about my site or app data contact
me on email bobo.bozic and I will send you everything you need.
Do I need to said that I send it few times already?

Guys, please fix this immediately.

**Comment by minhcasi** [comment]
Hi @bobozd - sorry for the issues, if you are satisfied with the product, it is possible to request a refund from this link - https://help.market.envato.com/hc/en-us/articles/202821460-Can-I-Get-A-Refund- 

Thanks!

<blockquote><img src="https://theme.zdassets.com/theme_assets/470490/0faca3b00d960ae77bd29445688a0a43e14751d7.svg" width="48" align="right"><div>Envato Market Help Center</div><div><strong><a href="https://help.market.envato.com">Envato Market Help Center</a></strong></div><div>Envato Market is a collection of themed marketplaces, where creatives sell digital assets to help bring your ideas to life. Visit our dedicated Help Center for Envato Market.</div></blockquote>

**Comment by bobozd** [comment]
I know i can ask for refund of course and unfortunately I will if you dont
solve my problem in a next few days. I am talking about basic instalation
and connection to my site just like in demo. Am I asking too much. I am
waiting few months for this. Do you think this is professional? Can you at
least explain to where the problem is?

sri, 6. ožu 2019. 03:37 Minh Pham <notifications@github.com> je napisao:
