### ISSUE TITLE
[ Fluxstore MV 1.7.4 ] - Crashing within 20 second of loading the config

### ISSUE THREAD

**Issue by iamar1k92** [inspireui/support#3523]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: App crash on home page after fetching the config.
+ Product & version: Fluxstore MV 1.7.4
+ Flutter (or React Native) version: Flutter 1.17.2 + Dart 2.8.3
+ Testing Device/Simulator: Samsung Grand Prime
+ Screenshot issues (drag the file to attach here): 

You can test the config file generated by fluxbuilder crashing the app all time.

Please let me know with the solution...

**Comment by minhcasi** [comment]
@iamar1k92 - could you share the your test case config + config file so that we could investigate the issue - thanks

**Comment by iamar1k92** [comment]
[config_es.json.zip](https://github.com/inspireui/support/files/4715562/config_es.json.zip)
Generated from Fluxbuiler

**Comment by iamar1k92** [comment]
It was might be issue with my flutter sdk or the testing device. Test the code on android R emulator and it worked without crashing....
