### ISSUE TITLE
How to change font from asset/fonts for Language

### ISSUE THREAD

**Issue by omman** [inspireui/support#3524]
Hi, I add this to pubspec.yaml
- family: GESSTwoLight
      fonts:
        - asset: assets/fonts/GESSTwoLight.ttf

So How to add this lib/common/config/fonts.dart
`import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

/// Google fonts constant setting: https://fonts.google.com/
TextTheme kTextTheme(theme, String language) {
  switch (language) {
//    case 'vi':
//      return GoogleFonts.montserratTextTheme(theme);
    case 'ar':
      **return GoogleFonts.robotoTextTheme(theme);**
    default:
      return GoogleFonts.robotoTextTheme(theme);
  }
}

TextTheme kHeadlineTheme(theme, [language = 'en']) {
  switch (language) {
//    case 'vi':
//      return GoogleFonts.montserratTextTheme(theme);
    case 'ar':
      **return GoogleFonts.robotoTextTheme(theme);**
    default:
      return GoogleFonts.robotoTextTheme(theme);
  }
}`

**Comment by minhcasi** [comment]
@omman - try this guide https://flutter.dev/docs/cookbook/design/fonts

pls help to open only one ticket for your all issue on next time, this issue will be marked duplicate with #3536
