### ISSUE TITLE
Image size

### ISSUE THREAD

**Issue by emadpost2016** [inspireui/support#3525]
When adding product images from my website, the image is incorrect in size and gives a problem with me. I added a program to adjust the image size from WordPress.but donot fix it

**Comment by emadpost2016** [comment]
![Screenshot_20200601-062829](https://user-images.githubusercontent.com/58606378/83430505-140ff200-a436-11ea-8f08-7dc3568a5795.jpg)
![Screenshot_20200601-182647](https://user-images.githubusercontent.com/58606378/83430513-17a37900-a436-11ea-8cd2-005febd70f77.jpg)
![Screenshot_20200601-182709](https://user-images.githubusercontent.com/58606378/83430521-1a05d300-a436-11ea-907b-3d39d366188b.jpg)
![Screenshot_20200601-182725](https://user-images.githubusercontent.com/58606378/83430526-1c682d00-a436-11ea-8ec5-ca149a2920b3.jpg)

**Comment by emadpost2016** [comment]
this is after update 1.7.4 and also in 1.7.3  in the flux MV

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as it could not be verified proof of purchase on step 2, please create the new ticket by including the the purchased License info - thank you for your time.
