### ISSUE TITLE
My every time i run i get build failed - app:compileDebugJavaWithJavac

### ISSUE THREAD

**Issue by stagedoor16** [inspireui/support#3526]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: Failed build - app:compileDebugJavaWithJavac FAILED
+ Product & version: MStore pro 3.9.8
+ Flutter (or React Native) version:  React-native 2.0.1
+ Testing Device/Simulator: Android studio - avd - android 6.00
Name: myavd

CPU/ABI: Google APIs Intel Atom (x86)

Path: C:\Users\jpwal\.android\avd\myavd.avd

Target: google_apis [Google APIs] (API level 23)

Skin: pixel_2

SD Card: 512M

fastboot.chosenSnapshotFile: 

runtime.network.speed: full

hw.accelerometer: yes

hw.device.name: pixel_2

hw.lcd.width: 1080

hw.initialOrientation: Portrait

image.androidVersion.api: 23

tag.id: google_apis

hw.mainKeys: no

hw.camera.front: emulated

avd.ini.displayname: myavd

hw.gpu.mode: auto

hw.ramSize: 1536

PlayStore.enabled: false

fastboot.forceColdBoot: no

hw.cpu.ncore: 4

hw.keyboard: yes

hw.sensors.proximity: yes

hw.dPad: no

hw.lcd.height: 1920

vm.heapSize: 256

skin.dynamic: yes

hw.device.manufacturer: Google

hw.gps: yes

hw.audioInput: yes

image.sysdir.1: system-images\android-23\google_apis\x86\

showDeviceFrame: yes

hw.camera.back: virtualscene

AvdId: myavd

hw.lcd.density: 420

hw.arc: false

hw.device.hash2: MD5:55acbc835978f326788ed66a5cd4c9a7

fastboot.forceChosenSnapshotBoot: no

fastboot.forceFastBoot: yes

hw.trackBall: no

hw.battery: yes

hw.sdCard: yes

tag.display: Google APIs

runtime.network.latency: none

disk.dataPartition.size: 800M

hw.sensors.orientation: yes

avd.ini.encoding: UTF-8

hw.gpu.enabled: yes

+ Screenshot issues (drag the file to attach here): 

> Task :app:compileDebugJavaWithJavac FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.5/userguide/command_line_interface.html#sec:command_line_warnings
186 actionable tasks: 157 executed, 29 up-to-date
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\jpwal\Downloads\mstore-3.9.8\mstore-pro\node_modules\@react-native-community\async-storage\android\src\main\java\com\reactnativecommunity\asyncstorage\AsyncStorageModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\jpwal\Downloads\mstore-3.9.8\mstore-pro\node_modules\@react-native-community\viewpager\android\src\main\java\com\reactnativecommunity\viewpager\ReactViewPagerManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: C:\Users\jpwal\Downloads\mstore-3.9.8\mstore-pro\node_modules\react-native-facebook-account-kit\android\src\main\java\io\underscope\react\fbak\RNAccountKitModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\jpwal\Downloads\mstore-3.9.8\mstore-pro\node_modules\react-native-fbsdk\android\src\main\java\com\facebook\reactnative\androidsdk\Utility.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: C:\Users\jpwal\Downloads\mstore-3.9.8\mstore-pro\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerButtonViewManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: C:\Users\jpwal\Downloads\mstore-3.9.8\mstore-pro\node_modules\react-native-localization\android\src\main\java\com\babisoft\ReactNativeLocalization\ReactNativeLocalization.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\jpwal\Downloads\mstore-3.9.8\mstore-pro\node_modules\react-native-onesignal\android\src\main\java\com\geektime\rnonesignalandroid\RNOneSignal.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\jpwal\Downloads\mstore-3.9.8\mstore-pro\node_modules\react-native-reanimated\android\src\main\java\com\swmansion\reanimated\NodesManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\jpwal\Downloads\mstore-3.9.8\mstore-pro\node_modules\react-native-reanimated\android\src\main\java\com\swmansion\reanimated\NodesManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: C:\Users\jpwal\Downloads\mstore-3.9.8\mstore-pro\node_modules\react-native-webview\android\src\main\java\com\reactnativecommunity\webview\RNCWebViewManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\jpwal\Downloads\mstore-3.9.8\mstore-pro\node_modules\react-native-webview\android\src\main\java\com\reactnativecommunity\webview\RNCWebViewManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
C:\Users\jpwal\Downloads\mstore-3.9.8\mstore-pro\android\app\build\generated\rncli\src\main\java\com\facebook\react\PackageList.java:23: error: package io.invertase.firebase.auth does not exist
import io.invertase.firebase.auth.ReactNativeFirebaseAuthPackage;
                                 ^
C:\Users\jpwal\Downloads\mstore-3.9.8\mstore-pro\android\app\build\generated\rncli\src\main\java\com\facebook\react\PackageList.java:99: error: cannot find symbol
      new ReactNativeFirebaseAuthPackage(),
          ^
  symbol:   class ReactNativeFirebaseAuthPackage
  location: class PackageList
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 26s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\jpwal\Downloads\mstore-3.9.8\mstore-pro\node_modules\@react-native-community\async-storage\android\src\main\java\com\reactnativecommunity\asyncstorage\AsyncStorageModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\jpwal\Downloads\mstore-3.9.8\mstore-pro\node_modules\@react-native-community\viewpager\android\src\main\java\com\reactnativecommunity\viewpager\ReactViewPagerManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: C:\Users\jpwal\Downloads\mstore-3.9.8\mstore-pro\node_modules\react-native-facebook-account-kit\android\src\main\java\io\underscope\react\fbak\RNAccountKitModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\jpwal\Downloads\mstore-3.9.8\mstore-pro\node_modules\react-native-fbsdk\android\src\main\java\com\facebook\reactnative\androidsdk\Utility.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: C:\Users\jpwal\Downloads\mstore-3.9.8\mstore-pro\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerButtonViewManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: C:\Users\jpwal\Downloads\mstore-3.9.8\mstore-pro\node_modules\react-native-localization\android\src\main\java\com\babisoft\ReactNativeLocalization\ReactNativeLocalization.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\jpwal\Downloads\mstore-3.9.8\mstore-pro\node_modules\react-native-onesignal\android\src\main\java\com\geektime\rnonesignalandroid\RNOneSignal.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\jpwal\Downloads\mstore-3.9.8\mstore-pro\node_modules\react-native-reanimated\android\src\main\java\com\swmansion\reanimated\NodesManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\jpwal\Downloads\mstore-3.9.8\mstore-pro\node_modules\react-native-reanimated\android\src\main\java\com\swmansion\reanimated\NodesManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: C:\Users\jpwal\Downloads\mstore-3.9.8\mstore-pro\node_modules\react-native-webview\android\src\main\java\com\reactnativecommunity\webview\RNCWebViewManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\jpwal\Downloads\mstore-3.9.8\mstore-pro\node_modules\react-native-webview\android\src\main\java\com\reactnativecommunity\webview\RNCWebViewManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
C:\Users\jpwal\Downloads\mstore-3.9.8\mstore-pro\android\app\build\generated\rncli\src\main\java\com\facebook\react\PackageList.java:23: error: package io.invertase.firebase.auth does not exist
import io.invertase.firebase.auth.ReactNativeFirebaseAuthPackage;
                                 ^
C:\Users\jpwal\Downloads\mstore-3.9.8\mstore-pro\android\app\build\generated\rncli\src\main\java\com\facebook\react\PackageList.java:99: error: cannot find symbol
      new ReactNativeFirebaseAuthPackage(),
          ^
  symbol:   class ReactNativeFirebaseAuthPackage
  location: class PackageList
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 26s

    at makeError (C:\Users\jpwal\Downloads\mstore-3.9.8\mstore-pro\node_modules\execa\index.js:174:9)
    at C:\Users\jpwal\Downloads\mstore-3.9.8\mstore-pro\node_modules\execa\index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:85:5)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

![image](https://user-images.githubusercontent.com/66263784/83422414-6bf02e00-a421-11ea-9103-cb9645a79364.png)

After looking on here i tried deleting the nod_modules then rerunning yarn install and clean gradle which didnt work.

Thank you so much for your time 😊

**Comment by stagedoor16** [comment]
Forgot to add i am doing this on windows 10

**Comment by minhcasi** [comment]
@luyx2412 - please help to suggest the solution

**Comment by luyx2412** [comment]
HI @stagedoor16 

You can try 2 comments to fix your issues https://github.com/facebook/react-native/issues/27374#issuecomment-577022702 and https://stackoverflow.com/a/57018475/6622971

Thanks

**Comment by stagedoor16** [comment]
I uninstalled everything and reinstalled then ran gradleclean and it seemed to work thank you for your suggestions

**Comment by luyx2412** [comment]
Closed!
