### ISSUE TITLE
Not being redirected to PayFast payment gateway 

### ISSUE THREAD

**Issue by dcb-online** [inspireui/support#3527]
Good day,

I have been experiencing this issue on the emulator for Android Studio as well as when testing my app on multiple android devices.

As soon as I hit "Place my order" (screenshot_1.jpg) on the app it should redirect me directly to the PayFast payment gateway, however when I select "Place my order" it directs me to the checkout screen of the website within the app (screenshot_2.jpg) and not all the fields are entered as well.

![screenshot_1](https://user-images.githubusercontent.com/66263315/83424152-52a0af00-a42c-11ea-8f8c-26d9a87aab09.jpg)

![screenshot_2](https://user-images.githubusercontent.com/66263315/83424212-64825200-a42c-11ea-90e2-e83281394d60.jpg)

I then have to click on "Place Order" again (screenshot_3.jpg) at the bottom of the page and then only it directs to the PayFast payment gateway.

![screenshot_3](https://user-images.githubusercontent.com/66263315/83424248-73690480-a42c-11ea-92a0-a37b6cc0a657.jpg)

How do I resolve this issue so that when a user selects "Place my order" it automatically redirects to the payment gateway (sreenshot_4.jpg)?

![sreenshot_4](https://user-images.githubusercontent.com/66263315/83424291-824fb700-a42c-11ea-8c72-0520804dccbd.jpg)

+ Product & version: 
WP REST API version: 2020.1.1
WooCommerce PayFast Gateway Version: 1.4.15
WooCommerce version: 4.1.1
Mstore API version: 2.5.0 
WordPress Version: 5.4.1

+ Flutter (or React Native) version: 
FluxStore-woo Version: 1.7.4
FluxBuilder.1.0
flutter_windows_1.17.1-stable

+ Testing Device/Simulator:
Android Studio latest version and on every anrdoid device (Samsung Galaxy s10, Samsung Galaxy S8, Samsung A70, Samsung A20

I did submit a proof of purchase using http://verify.inspireui.com

Just a friendly note that I would like to get the above working as PayFast is one of the most used payment gateways in South Africa and this will attract a lot of new clients if this works.

Many thanks Team!

**Comment by minhcasi** [comment]
@dcb-online - we suspect this could be a bug as it is designed to go directly to the payment.

@minhtruong315 - pls help for checking - thanks

**Comment by minhtruong315** [comment]
Hi @dcb-online Did you try to set ```NativeOnePageCheckout:false``` in common/config/payments.dart and try again

**Comment by fab17an** [comment]
Good, I have a similar problem as that of the colleague, but to me, if he directs me to the payment gateway, once he makes the payment, he does not generate the code, he stays on the payment screen, successful payment appears and there it is, does not return to the completed purchase window

**Comment by minhtruong315** [comment]
Hi @fab17an can u debug to log URLs? You can try to edit the code to fix the issue there.
<img width="1154" alt="Screen Shot 2020-06-07 at 11 05 41 PM" src="https://user-images.githubusercontent.com/10402500/83973873-7c1d7700-a913-11ea-9c4a-7c1f8b59c10a.png">

**Comment by fab17an** [comment]
> Hi @fab17an can u debug to log URLs? You can try to edit the code to fix the issue there.
> <img alt="Screen Shot 2020-06-07 at 11 05 41 PM" width="1154" src="https://user-images.githubusercontent.com/10402500/83973873-7c1d7700-a913-11ea-9c4a-7c1f8b59c10a.png">

good, I already modified but I see that once the process ends, success comes out to me, it comes out differently, I leave capture

![image](https://user-images.githubusercontent.com/41801914/83976578-659a0000-a8c0-11ea-9a36-e7e14ebc3a30.png)

**Comment by papaya1986** [comment]
go to checkout page mstore-checkout and change template mstore api ..then try

**Comment by fab17an** [comment]
> vaya a la página de pago mstore-checkout y cambie la plantilla mstore api .. luego intente

as well? could you explain to me please with an image, i am using on my page

**Comment by minhtruong315** [comment]
Hi @fab17an I see in the url "proceso-de-compra" but you're putting "predido-recibido"
pls update and try again

**Comment by minhtruong315** [comment]
Hi @fab17an how? please let me know the result.
Thanks

**Comment by fab17an** [comment]
Good, I made the change as he told me and now he no longer directs me to the payment method, but I receive the order received from the front, also what I see is that the payment method does not come out, but instead he launches me into the payment method Web

![image](https://user-images.githubusercontent.com/41801914/84027605-db4fab80-a954-11ea-8fb5-f6974361f322.png)

![image](https://user-images.githubusercontent.com/41801914/84027644-eacef480-a954-11ea-8e94-0f4174293e54.png)

**Comment by fab17an** [comment]
the payment process from the web is like this

![image](https://user-images.githubusercontent.com/41801914/84027782-29fd4580-a955-11ea-9338-801c9439dfd9.png)

![image](https://user-images.githubusercontent.com/41801914/84027838-413c3300-a955-11ea-958c-582dddc7e885.png)

![image](https://user-images.githubusercontent.com/41801914/84027888-55803000-a955-11ea-8001-f52ee58630cf.png)

![image](https://user-images.githubusercontent.com/41801914/84027946-6fba0e00-a955-11ea-87e0-cc81c1bf8167.png)

![image](https://user-images.githubusercontent.com/41801914/84027970-7d6f9380-a955-11ea-952a-89021316b736.png)

**Comment by fab17an** [comment]
my settings in the woocomerce

![image](https://user-images.githubusercontent.com/41801914/84028093-be67a800-a955-11ea-8839-d3184b1307a4.png)

![image](https://user-images.githubusercontent.com/41801914/84028121-ca536a00-a955-11ea-8feb-1ab484a2c40e.png)

![image](https://user-images.githubusercontent.com/41801914/84028141-d2aba500-a955-11ea-840c-72eb64113a91.png)

**Comment by fab17an** [comment]
my payment settings

![image](https://user-images.githubusercontent.com/41801914/84028420-4c439300-a956-11ea-984b-f7010e75acd4.png)

**Comment by dcb-online** [comment]
> Hi @dcb-online Did you try to set `NativeOnePageCheckout:false` in common/config/payments.dart and try again

Hi @minhtruong315 hope you are well.

I did try and set "NativeOnePageCheckout:false" in common/config/payments.dart and tried again, however I was unsuccessful. I have attached a screenshot below of the outcome when selecting "Place My Order".

![Screenshot_1](https://user-images.githubusercontent.com/66263315/84117118-4f5f8180-aa31-11ea-86f1-8fe104c21087.png)

![Screenshot_2](https://user-images.githubusercontent.com/66263315/84117183-643c1500-aa31-11ea-95c2-a93d0d958b95.png)

I have not touched any other code in the app.

Looking forward to your response!

**Comment by minhtruong315** [comment]
hi @dcb-online can u upload your source code to github and invite me: minhtruong315@gmail.com
I will help u check and fix on your source code.
Thanks

**Comment by fab17an** [comment]
> hola @ dcb-online ¿ puedes subir tu código fuente a github e invitarme? [minhtruong315@gmail.com](mailto:minhtruong315@gmail.com)
> Te ayudaré a verificar y corregir tu código fuente.
> Gracias

hi, please your support

**Comment by dcb-online** [comment]
Hi @minhtruong315 Thank you very much! How do I upload my source code to github? I did share it when I created the thread.

**Comment by dcb-online** [comment]
Hi @minhtruong315 
I have shared my source code to you via Google Drive
https://drive.google.com/drive/folders/1IplH5eY9xxwRI26DW_q0QZO5l_qAOo8B?usp=sharing

Only you would be able to access it.

If I set NativeOnePageCheckout to true then I get at least to the checkout page as you will see in my first few screenshots, however, if I set NativeOnePageCheckout to false it gives me an error 404 the page can not be found.

**Comment by minhtruong315** [comment]
Hi @dcb-online pls add my skype: minhtruong315
I will help you check via teamviewer.
Thanks

**Comment by dcb-online** [comment]
Hi @minhtruong315,

Thank you, I have added you to skype if it is the correct one :)

**Comment by minhtruong315** [comment]
Hi @dcb-online thanks for your rating. if you have any issues. pls ping me.
![picturemessage_s2ionmr4 a0h](https://user-images.githubusercontent.com/10402500/84371980-aa959d80-ac04-11ea-9294-f36daadfd253.png)

**Comment by fab17an** [comment]
> Hi @dcb-online thanks for your rating. if you have any issues. pls ping me.
> ![picturemessage_s2ionmr4 a0h](https://user-images.githubusercontent.com/10402500/84371980-aa959d80-ac04-11ea-9294-f36daadfd253.png)

good, even I still have the same problem as in the captures I left, how can I do? Or do I have to open my own ticket to be attended?

**Comment by minhtruong315** [comment]
Hi @fab17an please create new the ticket. it's easy to follow up.
Thanks
