### ISSUE TITLE
[ListApp]Home screen and some functionality not working in our application..

### ISSUE THREAD

**Issue by Pavithran10** [inspireui/support#353]
**Mandatory Info (please complete the following information):**
Product:[ListApp]
Version:1.6.1
Theme: MyListing

**Describe the issues**
hi, you asked to send screenshot I've attached below zip files and I've send error video too please check and then i need a help i think this problem occur from our admin we faced this problem before also you only solved it. so, please config our site creditional once.

[note:] Already I've attached our site creditional details to your mail private. please check and fix it

**Screenshots**
[errortabs.zip](https://github.com/inspireui/support/files/2917857/errortabs.zip)
[errorapp.zip](https://github.com/inspireui/support/files/2917859/errorapp.zip)

**Comment by Pavithran10** [comment]
hi, did u seen the problem how to solve this issue.

**Comment by Pavithran10** [comment]
hi, anybody is there. I've sent the comment two days before but still now i didn't get any solution.

**Comment by thangvo9x** [comment]
Hi. We checked your problem. Home is not displayed this problem is coming from your change category Listing Id. You can change it by manual (Common/Config/MyListing.js - property is horizontalLayout) or using CeBuilder at 
https://inspireui.com/

**Comment by Pavithran10** [comment]
hi, we checked already that things are all we config correctly. but our problem is app listing theme some feature images ,map location, and listing item in category functionlaity is not working. please check the error video. thanks
[errorapp.zip](https://github.com/inspireui/support/files/2925028/errorapp.zip)

**Comment by thangvo9x** [comment]
Hi . I checked your site . The problem is coming from your server. 
yourdomain/wp-json/wp/v2/job_listing?_embed=true&page=1&per_page=10&status=publish
try a solution such as disable debug on server...

**Comment by Pavithran10** [comment]
thanks, I'll check and update

**Comment by thangvo9x** [comment]
Hi. Follow me, this error is be related to plugins for reviews on your website. Try check disable some plugins. or research from GG. @@

**Comment by Pavithran10** [comment]
thanks, I will try and update then I've a doubt what is mean by   **research from GG. @@**

**Comment by thangvo9x** [comment]
Your mean? Url is facing to the error. 
<img width="1435" alt="error" src="https://user-images.githubusercontent.com/23457178/53852410-8bb55e00-3ff4-11e9-8b64-b8bf746bf921.png">

**Comment by Pavithran10** [comment]
How we can resolve this? The app build throowing error after error. When one resolved the other starts. We are thinking to drop the project build via ListApp as your codebase is not upto the mark and it is just a boilerplate we need to work around it to get it functional. 

Tell us whether you can help us or not to decide.

**Comment by thangvo9x** [comment]
Hi. Such as my comment before. Recommend to you, try to disable some plugins from reviews.

**Comment by Pavithran10** [comment]
kk, we will try and update
