### ISSUE TITLE
Fluxstore android tools 

### ISSUE THREAD

**Issue by mercadocerouno** [inspireui/support#3530]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: Problem with fluxstore
+ Product & version: Fluxstore Multi Vendor - Flutter E-commerce Full App
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: Android studio
+ Screenshot issues (drag the file to attach here): 

Could not find com.android.tools:r8:1.5.25.
Searched in the following locations:
  - https://dl.google.com/dl/android/maven2/com/android/tools/r8/1.5.25/r8-1.5.25.pom
  - https://jcenter.bintray.com/com/android/tools/r8/1.5.25/r8-1.5.25.pom
  - http://storage.googleapis.com/r8-releases/raw/com/android/tools/r8/1.5.25/r8-1.5.25.pom
Required by:
    project :

**Comment by minhcasi** [comment]
@mercadocerouno - could you help to run `flutter doctor` to see if there is an issue on your PC.

Please help to check this detailed video https://www.youtube.com/playlist?list=PLcF-HiQy-jOLumZ3Pedj_MNLZfwI4yLQy

Thank you!

**Comment by mercadocerouno** [comment]
This is that appear after running flutter doctor

![result](https://user-images.githubusercontent.com/66270970/83536742-7bff2080-a4a8-11ea-82e6-6bd39cefba33.jpg)

**Comment by minhcasi** [comment]
@mercadocerouno 

The flutter sdk on your PC is ok.

Could you help to check the installed on your PC by following this guide https://www.youtube.com/watch?v=3dv_8UerNpQ

Also check to clean up the flutter cache - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
