### ISSUE TITLE
Error inNoSuchMethodError: 

### ISSUE THREAD

**Issue by basithzan** [inspireui/support#3531]
I'm getting this error while selecting variations.

![IMG_5468](https://user-images.githubusercontent.com/12207952/83444452-0b84df00-a469-11ea-8074-244649926695.jpg)

Pls help 

@minhcasi

**Comment by minhcasi** [comment]
@basithzan - this bug is fixed on latest build `1.7.5` we will release it today - thank you!

**Comment by minhcasi** [comment]
Let us know if you have any further question - thank you!
