### ISSUE TITLE
The product page shows 'Default Title' for unknown reason.

### ISSUE THREAD

**Issue by ediruzza** [inspireui/support#3532]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
"Default TItle" shows on product page for unknown reason.  Page on website is without this.
https://dechoesresale.com/collections/vintage/products/vintage-as-is-natural-embroidered-bermuda-shoulder-bag

+ Product & version:
Evastore Shopify
+ Flutter (or React Native) version: 
1.2.0
+ Testing Device/Simulator: 
Samsung S10+
+ Screenshot issues (drag the file to attach here): 
![Screenshot_20200601-155711_Dechoes](https://user-images.githubusercontent.com/66277001/83450195-d6559e00-a422-11ea-8432-004e7fa174ed.jpg)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by luyx2412** [comment]
Hi @ediruzza Please change your variant default in admin page same the screenshot 

![](https://user-images.githubusercontent.com/8909619/83474919-65ac9100-a4b7-11ea-8cbe-4deff3efbe60.png)

Thanks

**Comment by ediruzza** [comment]
This product does not have any variants...so why do I have to put this in the Admin section?

**Comment by luyx2412** [comment]
Hi @ediruzza Please it is the default, so you want to hide the variant, in `src/containers/ProductDetailContainer/index.js` line 253. Please comment this code to hide the variant section.

Thanks

**Comment by ediruzza** [comment]
What will happen if SOME of the products have a variant and others DON'T?

**Comment by ediruzza** [comment]
You deleted my issue for the HTML description....what is the answer?  The HTML is NOT formatted correctly in the app, however, it is formatted correctly on the website and mobile phone browser.

**Comment by luyx2412** [comment]
Hi @ediruzza Sorry about closed your issues, because this issues is not follow the template. You can create new one or add the issues in this articles. 

And please send me your AppConfig.json and Config.js file. Let me filter the default title and send you code again.

Thanks

**Comment by ediruzza** [comment]
[files.zip](https://github.com/inspireui/support/files/4731074/files.zip)

**Comment by luyx2412** [comment]
HI @ediruzza Please replace this file in  [AnotherAttributes.js.zip](https://github.com/inspireui/support/files/4741492/AnotherAttributes.js.zip) src/containers/ProductDetailContainer/AnotherAttributes.js

Thanks

**Comment by ediruzza** [comment]
is this a fix for the HTML or a fix for the Variant information?

**Comment by luyx2412** [comment]
HI @ediruzza This is fix for variant, please check it.

Thanks

**Comment by luyx2412** [comment]
Closed!
P/S: Feel free to reopen or create new issue.
