### ISSUE TITLE
Cannot post new product to store as a vendor.

### ISSUE THREAD

**Issue by Rakiborv** [inspireui/support#3533]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

Hi,
For some reason I am unable to post new product in my store as a vendor. After filling all the fields and adding an image from gallery or by taking one via the camera, when I click post product button it shows the "Waiting for post product" screen and keeps loading forever.

I am currently using 1.6.6b release. I am testing on my real phone as well. 
![Screenshot_2020-06-02-02-04-23-884_com paikaribazaar store](https://user-images.githubusercontent.com/22408797/83449891-2c9ffc80-a476-11ea-8108-a7846584b071.jpg)

 Everything else is working fine on my app and it is launched in play store. 

My flutter version is the latest 1.17 and dart 2..8.3
I have also updated the rate_my_app version to 0.6.0+3 and shared_preferences to 0.5.7 and was able to successfully build app bundle and launch in play store.

Here is the link to the screen video : I believe this is enough for you to see what I am facing.

https://drive.google.com/file/d/1bwRksLExh2WrQpQKkbImIBBm29JWJbO2/view?usp=sharing

I have submitted the purchase proof as well. Please help me solve this issue asap. By the way I am able to post product via the demo app.

Note : Id like the solution / fix for 1.6.6b and cannot risk using the source code of 1.7.4 at the moment as I have made lots of changes in this source code and added custom tutorial pages for customers with the options in the side menu . Also added around 15 different layout columns for homepage customization and config_en.json which are working perfectly as intended. I do not remember all the dart files and locations where I made the changes so redoing all of this again in the new source code release is going to be very hard and time consuming for me.

Thank you for the awesome support you are providing to everyone. Looking forward to your reply.

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by philipvu30** [comment]
Hi,

Did you update the MStore API plugin or any WCFM plugins recently?

**Comment by Rakiborv** [comment]
Hi @philipvu30 ,

Mstore Api  - Version 2.5.0 ( was happening on previous as well so I updated to see if it resolves the issue )

Here are the current plugin versions below. But I doubt this is because of the plugin. I found out that I could not upload and facing this issue from my device and 4 other devices, from mobile network and wifi both. I have also tried uploading from my sisters network when I visited her house in another area but failed. But my another partner is able to upload product from his phone. Another customer tried from another city and I say products in his store. But there is no way I can upload from any of my device at home. Please help me indentify the cause.

WCFM - WooCommerce Frontend Manager - Version 6.5.0
WCFM - WooCommerce Multivendor Marketplace - Version 3.4.0 
WCFM - WooCommerce Multivendor Marketplace  REST API - Version 1.2.10
WCFM - WooCommerce Multivendor Membership - Version 2.9.0
WooCommerce - Version 4.1.1

**Comment by Rakiborv** [comment]
Issue number 2  : 
I have gone a head executed the solution for this issue #3351 as I had similar concerns regarding my store visibility as well and the banner part worked perfectly, but I cannot see any product in a store even though the product is published for that store and visible in the website and app but not in the store of a customer. That was yesterday but today I cannot see any stores, Im guessing since none of the stores has any product thats why I cannot see them, but I should be able to see the customer's one containing 2 products which I cannot either.

**Comment by philipvu30** [comment]
Hi,

I saw your comment in our verification form. We really appreciate your kind words.
Usually, we do not support the older versions. But you can send your project to my email: toan@inspireui.com, I'll help you check what's wrong with the app. 

Thank you.

**Comment by mixkey23** [comment]
> 
> 
> Issue number 2 :
> I have gone a head executed the solution for this issue #3351 as I had similar concerns regarding my store visibility as well and the banner part worked perfectly, but I cannot see any product in a store even though the product is published for that store and visible in the website and app but not in the store of a customer. That was yesterday but today I cannot see any stores, Im guessing since none of the stores has any product thats why I cannot see them, but I should be able to see the customer's one containing 2 products which I cannot either.
> 
> Note : I have changed these codes yesterday night after I posted the first issue so the config and common zip I added here does not contain these changes. Let me know if you want the new zip when you are looking into this issue.
> 
> Thank you.

Hi @Rakiborv, in the previous build (1.7.3) there is a bad status name in condition to show products 

In /lib/services/wcfm.dart, look for this part:

          if (item["status"] == "published") {
            final product = Product.fromJson(item);
            product.store = Store.fromWCFMJson(item["store"]);
            list.add(product);
          }

If you look in the code, the condition for status to show a product is published but in woocommerce's api, says status **publish** not **published**, so i change published by publish and thats show my products.





Change

**Comment by Rakiborv** [comment]
Hi @philipvu30 ,
I have sent an email to your email address provided above. It contains the source zip and the support account credentials. Thanks a lot again for all your help and support.

**Comment by Rakiborv** [comment]
Hi @mixkey23 

Thank you so much for pointing that out, I couldn't have figured it out myself. But I think it is not matching with my version of code.
your code has --> product.store = Store.fromWCFMJson(item["store"]);
but since I am using 1.6.6b by code has --> product.storeId = "$storeId";
If I paste your code's line it gives error. :(

**Comment by philipvu30** [comment]
Hi,

It seems everything is fine for me. I'm able to create a simple product including an image taken from my phone's camera.
I tested on the Samsung Galaxy S9+ device. The video you included is damaged and I couldn't see it so I reproduced the problem myself.
Here are the proofs:

![image](https://user-images.githubusercontent.com/54442328/83606782-58210500-a5a4-11ea-8755-bcbcb8e9e292.png)
![101692136_3157695237629559_6830849320523137024_n](https://user-images.githubusercontent.com/54442328/83606804-5e16e600-a5a4-11ea-9d1e-682346a519a9.jpg)

**Comment by Rakiborv** [comment]
Hi Philip,

Thank you so much for testing the code out confirming that you could upload simple products with a S9 device. But I don't get it why I am unable to add new products from my device. It just keeps loading forever, I shared the same apk via drive to my friend and even he was able to add product. But I have tried from my device and another device and getting same result. This is really taking my sleep away. My device is Redmi Note 8 pro, and another one is Xiomi 4x. I will email you a screen record for the product upload in your email so that you can see what is happening in my device.

I also wanted to confirm one more thing, in the below code is the line "await wcApi.getAsync("flutter/wcfm-stores?per_page=10&page=$page");" correct or should it be
"wcfmApi.getAsync(........); ?

@override
  Future<List<Store>> getStores({lang, page}) async {
    try {
      List<Store> list = [];
      var response =
      await wcApi.getAsync("flutter/wcfm-stores?per_page=10&page=$page");

      if (response is Map && isNotBlank(response["message"])) {
        throw Exception(response["message"]);
      } else {
        for (var item in response) {
          if (!item["disable_vendor"]) list.add(Store.fromWCFMJson(item));
        }
        return list;
      }
    } catch (e) {
      rethrow;

**Comment by philipvu30** [comment]
Hi,

I can confirm this is correct.

> @override
> Future<List> getStores({lang, page}) async {
> try {
> List list = [];
> var response =
> await wcApi.getAsync("flutter/wcfm-stores?per_page=10&page=$page");

I assume you are stuck at this line?
> await wcApi.getAsync("flutter/wcfm-stores?per_page=10&page=$page");

If that is the case, it means there is a connection issue with your device. Please check the link below if it takes much time to load the data or not.

>https://paikaribazaar.com/wp-json/wc/v2/flutter/wcfm-stores?per_page=10&page=1&consumer_key=YOUR_CONSUMER_KEY&consumer_secret=YOUR_CONSUMER_SECRET

**Comment by Rakiborv** [comment]
Hi Philip,
I have found the issue and now I can upload products, it was not uploading because I was keeping the sale field blank thinking that since I did not have a sale on the product I needed to keep that field blank that is why the product was not uploading. But keeping the regular and sale value the same does the work.

But there are two issues that I came across.

1. After logging in to my vendor profile I can see the message button at the lower right corner. But as soon as I go to stores and click on a store to go inside the button disappears. Now if I go to profile page again I cannot see the button.
2. To exit the app if I click on back button it generates the pop up for confirming Yes and No, clicking yes takes me back to homepage and doing the same thing again takes me to tutorial page. Clicking this yes button should force the app to close instantly.

Can you suggest me the code to fix these? Thank you

**Comment by Rakiborv** [comment]
Hi Philip,

I hope you are doing well. I had a request, can you discuss with your team and may be add Bengali language in the next release as well. I can see that you have added Hungary in the latest release. If you can add Bengali language I am willing to jump upgrade from 1.6.6b to 1.7.X as the bengali language will complete my app's requirement for my market.

Also its okay if you are unable to provide solution due to my backdated version usage, I completely understand. Its not a launch blocker bug so I will be fine until I update. You can close the issue. When you close the issue after that I will erase the support admin from my site admin panel. 

Thanks alot bro. Waiting for your confirmation.

**Comment by philipvu30** [comment]
Hi Rakiborv,

Sorry for the delayed response as we rarely work on Weekends. You can add the language to your current project yourself with the help of Android Studio and this [Flutter intl plugin](https://plugins.jetbrains.com/plugin/13666-flutter-intl).
Or if you want to use the latest version with the Bengali language but don't have time for it, simply translate the intl_en.arb to intl_bn.arb and send us that file. We will include it in the next release.

About your earlier issues, I'll check them if they occur in the current version.

Thank you for your concern.

**Comment by philipvu30** [comment]
Hi,

> After logging in to my vendor profile I can see the message button at the lower right corner. But as soon as I go to stores and click on a store to go inside the button disappears. Now if I go to profile page again I cannot see the button.

This issue is happening on new version also. We have been aware of it and it may be included in the next release.
>To exit the app if I click on back button it generates the pop up for confirming Yes and No, clicking yes takes me back to homepage and doing the same thing again takes me to tutorial page. Clicking this yes button should force the app to close instantly.

This issue does not happen in the latest version. 

You may now delete the support account on your site. 
Thank you for your interest.

**Comment by Rakiborv** [comment]
Thank you so much! 😃 I will send you the bn file and once you include it in the release I will upgrade my source as there  are many other fixes as well. So since I have to go for the upgrade, its better that I go for it once all these are done and tested by your awesome team.

**Comment by devienguilde** [comment]
how do i upload product from gallery?, i try press from gallery but only show camera
