### ISSUE TITLE
10 Categories showing but I have 13 Categories...

### ISSUE THREAD

**Issue by omman** [inspireui/support#3536]
Hi, In My App
Problem# 1: Categories Tab I see only 10 Categories, 
Problem# 2: In My Banners I linked 3 Categories Which is Not Showing in Categories Tab also Not Showing.
Problem# 3: Left Drawer also Showing 10 Categories,
Problem# 4: Product Filter also Showing 10 Categories,

Please Fix This Issues All Place Showing 10 Categories. But I have 13 Categories...

**Comment by omman** [comment]
Hi, please also tell how to use custom fonts because my English font is google Roboto then Arabic font is custom font so please tell me how to do that. I already add the font in yaml file..

**Comment by kvt0012** [comment]
About Font, please come to sttyle.dart, yyou can config it there, thank you

**Comment by omman** [comment]
Hi @kvt0012 , 

TextTheme kTextTheme(theme, String language) {
  switch (language) {

    case 'ar':
      return GoogleFonts.robotoTextTheme(theme); <-- This Font I want to change for Custom Font.
    default:
      return GoogleFonts.robotoTextTheme(theme);
  }
}

**Comment by kvt0012** [comment]
You can follow this plugin, we use it to load font from Google.  https://pub.dev/packages/google_fonts

**Comment by kvt0012** [comment]
About category, you can config the amount  of category on Category folder, because we set the limitation is 10 categories, thank you

**Comment by omman** [comment]
hi @kvt0012 , 
- family: GE SS Two Light
      fonts:
        - asset: assets/google_fonts/GE-SS-Two-Light.ttf
And This Error

TextTheme kTextTheme(theme, String language) {
  switch (language) {
    case 'ar':
      return GoogleFonts.gesstwolightTextTheme(theme);
    default:
      return GoogleFonts.robotoTextTheme(theme);
  }
}

About Categories Can you Explain Because I don't know which folder in categories i will configure it.

**Comment by omman** [comment]
hi @kvt0012 , Please check this https://i.imgur.com/5htGWoT.jpg

**Comment by kvt0012** [comment]
You can come to config folder and find file config_en.json, and add more categories here, sir.

**Comment by omman** [comment]
hi, @kvt0012 Where i can ad this can you check this link https://drive.google.com/file/d/1L4zv4h_c0hsDK938XsNU76OytfORGnIf/view?usp=sharing 
I already in in slider benner but 3 categories number not showing in banner also side drawer, also categories tab ALSO categories filter all place 10 categories coming.

**Comment by omman** [comment]
hi @kvt0012 kind please check my github with this source https://github.com/OPTEACH/FluxStore-woo-1.7.4/tree/master/source

**Comment by omman** [comment]
Hi @kvt0012 , I still configure the font for arabic and categories limit..Please reply

**Comment by omman** [comment]
Hi, @kvt0012 Please tell me how to do this Font and Categories.. I am Still can't Configure this Issues.

**Comment by alexrali** [comment]
i've been testing 1.7.5 version since its published, and i dont know if this issue is related to that product listing that after load the first time, is not loading more items.  

I mean, the loading on the bottom is not working for me.

**Comment by minhcasi** [comment]
@omman - the categories issues is fixed on latest 1.7.5 - https://tppr.me/icvua

- try to custom font assess by this file https://tppr.me/HHd4R - check the guide https://flutter.dev/docs/cookbook/design/themes

**Comment by omman** [comment]
Hi @minhcasi , After adding to cart then loading the webview payment method in second language not working always view as 1st language. Problem because Arabic people's not understand English plz fix also this, so that 2nd language to redirect to second language page.

**Comment by minhcasi** [comment]
@omman - it is possible if we add the param `?lang=en` or `?lang=ar` to switch the language inside the Webview on your site?

Are you using WPML or Polylang?

**Comment by omman** [comment]
Wpml

**Comment by omman** [comment]
Hi My Language is Mydomain/en or ar

**Comment by minhcasi** [comment]
@omman - i'm not sure if it can be fixed on your site, pls try to customize this file - https://tppr.me/KRJhA

**Comment by omman** [comment]
hi, @minhcasi I update the 1.7.5 version then
Problem is:
1) Still not showing all the categories
2) still not redirecting the translation web view always showing english cart.
3) home page `  "Setting":{
    "MainColor":"#FB8C00",
    "ProductListLayout":"list",
    "StickyHeader":true
  },`
in the config Not Showing Loading when i scroll down but 1.7.4 it was showing also see all product not showing all product..

**Comment by omman** [comment]
hi @minhcasi , 

**- Problem No (1): Categories Limit 10**
---------------------------------------
1. Site Categories List: https://i.imgur.com/O6rwwVu.jpg 
2. Site Drawer showing only 10: https://i.imgur.com/KvYzquV.jpg
3. Categories tab only showing 10: https://i.imgur.com/1E6nbDo.jpg
4. Filter Menu only showing 10: https://i.imgur.com/AnQXhRX.jpg

**- Problem No (2): "See All" and "Load More" For Scroll Down Not Working:**
---------------------------------------
1. "See All" and "Load More" : https://i.imgur.com/MBfiXfN.jpg
2. After Click "See All" No Product Shown: https://i.imgur.com/QkRVe1X.jpg

**- Problem No (3): Show Only 10 Product in Home Page:**
---------------------------------------
1. Showing 10 Products only : https://i.imgur.com/frv1n3z.jpg

**- Problem No (4): Categories Language Not Change:**
---------------------------------------
1. Categories Language Not Change : https://i.imgur.com/hfjCl40.jpg

**- Problem No (5): New Variation Language Not Change:**
---------------------------------------
1. New Variation Language Not Change: : https://i.imgur.com/6BNgcq5.jpg
2. New Variation Language Not Change: : https://i.imgur.com/DKhRIaG.jpg

**- Problem No (6): Web view Cart Not redirecting to current Language mode:**
---------------------------------------
1. Not Redirecting the current language web view page: : https://i.imgur.com/1AGkXqf.jpg

**Comment by minhcasi** [comment]
@omman - could you zip the whole source and send to support@inspireui.com - we will help to check the issue - thank you!

**Comment by omman** [comment]
hi @minhcasi , i already send email also i send invite to "minhcasi" for my GitHub source, Kindly please check email.

**Comment by omman** [comment]
hi @minhcasi There is another isuue when the otp user signup with number then number is not coming in billing phone Please fix also this...

**Comment by minhcasi** [comment]
@omman - noted with checking - thank you!

**Comment by omman** [comment]
Hi, @vumanhsn97 @minhcasi please tell me when i will received this solution?

**Comment by vumanhsn97** [comment]
@omman 
I checked it and fixed your issues. Can you send  me your email address to share this resource?

**Comment by omman** [comment]
devomman@gmail.com

**Comment by omman** [comment]
hi @vumanhsn97 , This issues still not fixed Please check:

**- Problem No (1): Free shipping only for valid Free Shipping Coupon:**
---------------------------------------
1. When I enable Free Shipping with valid Coupon not working : https://i.imgur.com/ihRX8Ko.jpg


**- Problem No (2): Load More & See All Showing 2 Times:**
---------------------------------------
1. Two (2) Times showing Load More and See All Option in Home Tab https://i.imgur.com/YYKj1Tb.png


**- Problem No (3): Data not send when user signup with number & Card Payment Webview Mode:**
---------------------------------------
1. When the otp user signup with number then number is not coming in billing phone.
2. When We fill-up  billing details with native payment method then Billing Details data not send for "Card Payment" options for web view.


**- Problem No (4): New Variation Language Not Change:**
---------------------------------------
1. New Variation Language Not Change: : https://i.imgur.com/6BNgcq5.jpg
2. New Variation Language Not Change: : https://i.imgur.com/DKhRIaG.jpg


**- Problem No (5): Web view Cart Not redirecting to second Language mode ARABIC:**
---------------------------------------
1. Not Redirecting the current language web view page: : https://i.imgur.com/1AGkXqf.jpg

**Comment by vumanhsn97** [comment]
@omman 
1. Coupon code not support for valid Free shipping
2. Please check clean and rebuild your project
3. Working well. Can you share video record?
4. Keep it in this version. We will update in next version
5. Please change language to Arabic before you checkout: https://tppr.me/gDwGw

**Comment by omman** [comment]
Hi, Please check i already explain with this video link 
https://drive.google.com/file/d/1qVLEyvVG9Z6Uv10mJcC9fI4kx-tnXw7m/view?usp=sharing

Problem No: (1)
1. If i select Free Delivery if use coupon then it will show but in the app always appear.

Problem No: (2)
1. if i click slider or banner image for categories not go the categories screen I give the correct categories id but version 1.7.4 it was working only some categories not working which is not coming, but now all not working.

Problem No: (3)
1. Data not send when user signup with number & 
2. Also not send data (Map, Phone, Street, City) Card Payment Web view Mode

Problem No: (4)
 1. Web view Cart Not redirecting to second Language mode ARABIC.

**Comment by vumanhsn97** [comment]
1. In app, Coupon code just support for discount product price
2. In lib/models/product/product.dart check this line: https://tppr.me/IY7F8 and product_model.dart check this code: https://tppr.me/OIknj
3. Address auto field with billing address (setup in user profile in wordpress site).
4. Language mode: update this file in lib/widgets/frameworks/woocommerce/index.dart 
[index.dart.zip](https://github.com/inspireui/support/files/4798186/index.dart.zip)

**Comment by omman** [comment]
@kvt0012 How i get the map if using payment method? Because payment method not coming the map please suggest me any plugins for same as map using the app.
About Coupon how we can give user free delivery if they apply coupon? it will fix with new version in future updates?

**Comment by omman** [comment]
hi @kvt0012 , Please check this Video Still Having Problem with "see more"
**Problem 1:** Two (2) Times showing Load More and See All Option in Home Tab When i logged in with user pass then it will show 2 times. If not logged in not showing 2 times. https://drive.google.com/file/d/1rgZABKt9TQ12-G9PkEo6z-se7BcKhV5u/view?usp=sharing

**Problem 2:** About Coupon how we can give user free delivery if they apply coupon? it will fix with new version in future updates?

**Need Suggestion:** How i get the map if using payment method? Because payment method not coming the map please suggest me any plugins for same as map using the app.

**Comment by vumanhsn97** [comment]
@omman 
Problem 1: edit file in lib/widgets/home/index.dart to 
[index.dart.zip](https://github.com/inspireui/support/files/4804032/index.dart.zip)

Problem 2: Try to customize it. We will not update in the future

Suggestion: You can use this plugin in your wordpress site: https://codecanyon.net/item/woocommerce-checkout-location-picker/6811588

**Comment by omman** [comment]
Hi, @vumanhsn97 It's Fixed, Thank You! Hope You add Free Delivery option if coupon apply..

**Comment by omman** [comment]
Hi @vumanhsn97 it has sam issues today i update and check it has same issues.https://drive.google.com/file/d/1rgZABKt9TQ12-G9PkEo6z-se7BcKhV5u/view?usp=sharing

**Comment by ameenbadri7** [comment]
if you want a local font just add `  fontFamily: 'AlJazeera'`
to every `TextStyle()` inside ` lib/common/style.dart`
remaber 
do like this `'AlJazeera' `not `"AlJazeera"`


this is my full code : 

`import 'package:flutter/material.dart';

import 'config/fonts.dart';
import 'constants/colors.dart';

const kProductTitleStyleLarge = TextStyle(
  fontSize: 18,
  fontWeight: FontWeight.bold,
  fontFamily: 'AlJazeera',
);

const kTextField = InputDecoration(
  hintText: 'Enter your value',
  contentPadding: EdgeInsets.symmetric(
    vertical: 10.0,
    horizontal: 20.0,
  ),
  border: OutlineInputBorder(
    borderRadius: BorderRadius.all(Radius.circular(3.0)),
  ),
  enabledBorder: OutlineInputBorder(
    borderSide: BorderSide(color: Colors.blueGrey, width: 1.0),
    borderRadius: BorderRadius.all(Radius.circular(3.0)),
  ),
);

IconThemeData _customIconTheme(IconThemeData original) {
  return original.copyWith(color: kGrey900);
}

ThemeData buildLightTheme(String language) {
  final ThemeData base = ThemeData.light();
  return base.copyWith(
    colorScheme: kColorScheme,
    buttonColor: kTeal400,
    cardColor: Colors.white,
    textSelectionColor: kTeal100,
    errorColor: kErrorRed,
    buttonTheme: const ButtonThemeData(
      colorScheme: kColorScheme,
      textTheme: ButtonTextTheme.normal,
      buttonColor: kDarkBG,
    ),
    primaryColorLight: kLightBG,
    primaryIconTheme: _customIconTheme(base.iconTheme),
    textTheme: _buildTextTheme(base.textTheme, language),
    primaryTextTheme: _buildTextTheme(
      base.primaryTextTheme,
      language,
    ),
    accentTextTheme: _buildTextTheme(base.accentTextTheme, language),
    iconTheme: _customIconTheme(base.iconTheme),
    hintColor: Colors.black26,
    backgroundColor: Colors.white,
    primaryColor: kLightPrimary,
    accentColor: kLightAccent,
    cursorColor: kLightAccent,
    scaffoldBackgroundColor: kLightBG,
    appBarTheme: AppBarTheme(
      elevation: 0,
      textTheme: TextTheme(
        headline6: TextStyle(
          color: kDarkBG,
          fontSize: 18.0,
          fontWeight: FontWeight.w800,
          fontFamily: 'AlJazeera',
        ),
      ),
      iconTheme: IconThemeData(
        color: kLightAccent,
      ),
    ),
    pageTransitionsTheme: PageTransitionsTheme(builders: {
      TargetPlatform.iOS: FadeUpwardsPageTransitionsBuilder(),
      TargetPlatform.android: FadeUpwardsPageTransitionsBuilder(),
    }),
    tabBarTheme: TabBarTheme(
      labelColor: Colors.black,
      unselectedLabelColor: Colors.black,
      labelPadding: EdgeInsets.zero,
      labelStyle: TextStyle(
        fontSize: 13,
        fontFamily: 'AlJazeera',
      ),
      unselectedLabelStyle: TextStyle(
        fontSize: 13,
        fontFamily: 'AlJazeera',
      ),
    ),
  );
}

TextTheme _buildTextTheme(TextTheme base, String language) {
  return kTextTheme(base, language)
      .copyWith(
        headline5: base.headline5
            .copyWith(fontWeight: FontWeight.w500, color: Colors.red),
        headline6: base.headline6.copyWith(fontSize: 18.0),
        caption: base.caption.copyWith(
          fontWeight: FontWeight.w400,
          fontSize: 14.0,
          fontFamily: 'AlJazeera',
        ),
        subtitle1: base.subtitle1.copyWith(
          fontWeight: FontWeight.w400,
          fontSize: 16.0,
          fontFamily: 'AlJazeera',
        ),
        button: base.button.copyWith(
          fontWeight: FontWeight.w400,
          fontSize: 14.0,
          fontFamily: 'AlJazeera',
        ),
      )
      .apply(
        displayColor: kGrey900,
        bodyColor: kGrey900,
        fontFamily: 'AlJazeera',
      )
      .copyWith(
        headline4: kHeadlineTheme(base).headline4.copyWith(
              fontFamily: 'AlJazeera',
            ),
      );
}

const ColorScheme kColorScheme = ColorScheme(
  primary: kTeal100,
  primaryVariant: kGrey900,
  secondary: kTeal50,
  secondaryVariant: kGrey900,
  surface: kSurfaceWhite,
  background: kBackgroundWhite,
  error: kErrorRed,
  onPrimary: kDarkBG,
  onSecondary: kGrey900,
  onSurface: kGrey900,
  onBackground: kGrey900,
  onError: kSurfaceWhite,
  brightness: Brightness.light,
);

ThemeData buildDarkTheme(String language) {
  final ThemeData base = ThemeData.dark();
  return base.copyWith(
    textTheme: _buildTextTheme(base.textTheme, language).apply(
      displayColor: kLightBG,
      bodyColor: kLightBG,
    ),
    primaryTextTheme: _buildTextTheme(base.primaryTextTheme, language).apply(
      displayColor: kLightBG,
      bodyColor: kLightBG,
      fontFamily: 'AlJazeera',
    ),
    accentTextTheme: _buildTextTheme(base.accentTextTheme, language).apply(
      displayColor: kLightBG,
      bodyColor: kLightBG,
      fontFamily: 'AlJazeera',
    ),
    cardColor: kDarkBgLight,
    brightness: Brightness.dark,
    backgroundColor: kDarkBG,
    primaryColor: kDarkBG,
    primaryColorLight: kDarkBgLight,
    accentColor: kDarkAccent,
    scaffoldBackgroundColor: kDarkBG,
    cursorColor: kDarkAccent,
    appBarTheme: AppBarTheme(
      elevation: 0,
      textTheme: TextTheme(
        headline6: TextStyle(
          color: kDarkBG,
          fontSize: 18.0,
          fontWeight: FontWeight.w800,
          fontFamily: 'AlJazeera',
        ),
      ),
      iconTheme: IconThemeData(
        color: kDarkAccent,
      ),
    ),
    buttonTheme: ButtonThemeData(
        colorScheme: kColorScheme.copyWith(onPrimary: kLightBG)),
    pageTransitionsTheme: PageTransitionsTheme(builders: {
      TargetPlatform.iOS: FadeUpwardsPageTransitionsBuilder(),
      TargetPlatform.android: FadeUpwardsPageTransitionsBuilder(),
    }),
    tabBarTheme: TabBarTheme(
      labelColor: Colors.white,
      unselectedLabelColor: Colors.white,
      labelPadding: EdgeInsets.zero,
      labelStyle: TextStyle(
        fontSize: 13,
        fontFamily: 'AlJazeera',
      ),
      unselectedLabelStyle: TextStyle(
        fontSize: 13,
        fontFamily: 'AlJazeera',
      ),
    ),
  );
}

const kMessageContainerDecoration = BoxDecoration(
  border: Border(
    top: BorderSide(color: kTeal400, width: 2.0),
  ),
);

const kSendButtonTextStyle = TextStyle(
  color: kTeal400,
  fontWeight: FontWeight.bold,
  fontSize: 18.0,
  fontFamily: 'AlJazeera',
);

const kMessageTextFieldDecoration = InputDecoration(
  contentPadding: EdgeInsets.symmetric(vertical: 10.0, horizontal: 20.0),
  hintText: 'Type your message here...',
  border: InputBorder.none,
);
`
