### ISSUE TITLE
Product variation error 1.7.2

### ISSUE THREAD

**Issue by samik9** [inspireui/support#3537]
I made a video when trying to choose any option it displays an error 
video:
https://gzodigital.d.pr/TXU9eg

Also, when i open the product page, the featured image change for another one from other product.

![Screenshot_1591056980_700x601](https://user-images.githubusercontent.com/50071744/83466375-8b488480-a43c-11ea-9f5d-8a057c71a3e1.jpg)

I already sent the verification form

**Comment by minhcasi** [comment]
@samik9 - please help to use the latest `1.7.4` or `1.7.5` to fix this issue, we will also release new `1.7.5` today - thank you!

**Comment by minhcasi** [comment]
pls help to update the app and let us know if you have any question - thank you!
