### ISSUE TITLE
[ListApp] Not installing on ios simulator.

### ISSUE THREAD

**Issue by DNeelanshi** [inspireui/support#354]
**Mandatory Info (please complete the following information):**
 - Product:  ListApp
 - Your Purchased Code:

**Describe the issues**
I am trying to run this project on Ios simulator but nothing is happening on simulator.Expo is successfully  downloaded on simulator but nothing happens further.Its been more than 30 mins.and network connection is consistent.

**Screen shot
![screen shot 2019-03-01 at 6 45 37 pm](https://user-images.githubusercontent.com/32795046/53640464-4559ab00-3c52-11e9-8abb-c08338619c43.png)
enshots**

**Additional context**
please help. we have purchased code and want to customize for Ios

**Comment by thangvo9x** [comment]
Hi. Please try click expo app on your simulator.
