### ISSUE TITLE
Version 1.7.4 stickey header

### ISSUE THREAD

**Issue by rushank** [inspireui/support#3540]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues:  Yesterday i have downloaded latest code from codecanyon and run that project there is already defined stcikey header true but it is not working as expected. I have checked your app on play store and it works perfect with stickey header. 
+ Product & version:  Fluxstore Multi Vendor - Flutter E-commerce Full App  1.7.4
+ Flutter (or React Native) version:  Flutter
+ Testing Device/Simulator:  Real android phones
+ Screenshot issues (drag the file to attach here):

**Comment by minhcasi** [comment]
@rushank - could you share the screenshot of the issue - thank you!

**Comment by rushank** [comment]
![Screenshot_20200602-221536](https://user-images.githubusercontent.com/8816814/83547072-4e08f300-a51f-11ea-8611-95ef05ee28d2.png)

I have again downloaded latest source code now and run app again. But still it is not fixed the header. !

**Comment by rushank** [comment]
[fstore.zip](https://github.com/inspireui/support/files/4718578/fstore.zip)

Uploaded common and config folder from latest source code

**Comment by minhcasi** [comment]
@rushank 

We wanted to thank you for your patience during this busy time. We currently have reduced staff and a significantly higher volume of inquiries. We’re working as hard as we can to get to your request as soon as possible.

We sincerely apologize for the delay and hope you’re staying safe.

**Comment by vumanhsn97** [comment]
@rushank 
In lib/widgets/home/index.dart add this line https://tppr.me/xwTK8

**Comment by rushank** [comment]
ok. Thanks
