### ISSUE TITLE
[FluxStore w/ woocommerce] Changes to category page

### ISSUE THREAD

**Issue by and-eee** [inspireui/support#3541]
Hi guys, this is just a question.Ccould you please guide me to where I need to look to change a couple of aspects of the category page? Specifically:

1. Remove "see all" line so products can only been seen through their subcategory (this is a standard option in Woocommerce but it's not replicated in the app).
2. Change height/dimensions of the cards (looking to make them less tall).
3. Remove the product count.
3. Change the font sizes.

Thank you as always for your time.

**Comment by minhcasi** [comment]
@and-eee - pls help to try to use the Inspector Tools so that you could customize this UI very easy 👍
