### ISSUE TITLE
Image size

### ISSUE THREAD

**Issue by emadpost2016** [inspireui/support#3542]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
When adding product images from my website, the image is incorrect in size and gives a problem with me. I added a program to adjust the image size from WordPress.but donot fix it after I update 1.7.4 and the same in 1.7.3 please help me 

+ Product & version:1.7.4 and 1.7.3
+ Flutter (or React Native) version: last version 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 
![Screenshot_20200601-182725](https://user-images.githubusercontent.com/58606378/83487884-2dec1c00-a4ac-11ea-8439-296d297627d0.jpg)
![Screenshot_20200601-182709](https://user-images.githubusercontent.com/58606378/83487895-30e70c80-a4ac-11ea-9c8f-8d7f8761d8a0.jpg)
![Screenshot_20200601-182647](https://user-images.githubusercontent.com/58606378/83487909-35132a00-a4ac-11ea-94ed-597f633fac86.jpg)
![Screenshot_20200601-062829](https://user-images.githubusercontent.com/58606378/83487914-37758400-a4ac-11ea-8dbe-5f2ca1766d36.jpg)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@emadpost2016 - pls update this value to 0.45 - thank you!

<img width="825" alt="Screen Shot 2020-06-02 at 17 17 36" src="https://user-images.githubusercontent.com/1459805/83509016-f786bf00-a4f4-11ea-812a-a5c9ec06b2f1.png">

**Comment by emadpost2016** [comment]
i update that to 0.45 and donot fix it

‫في الثلاثاء، 2 يونيو 2020 في 12:18 م تمت كتابة ما يلي بواسطة ‪Minh Pham‬‏
<‪notifications@github.com‬‏>:‬

**Comment by emadpost2016** [comment]
any update

**Comment by minhcasi** [comment]
@emadpost2016 - it is fixed well, could i know what is your device OS version used to test so that we could reproduce the issue?

**Comment by emadpost2016** [comment]
Samsung a30 my device

**Comment by emadpost2016** [comment]
bottom in my cart the same issue and when i change value to 30  that
solve issue in my list productlistdart but another places give me same
issue in my card product bottem  in the ( you can like also ) bottem the
product details  and bottem my cart


‫في الخميس، 4 يونيو 2020 في 6:37 ص تمت كتابة ما يلي بواسطة اونا الصغنونة <‪
emad.post2016@gmail.com‬‏>:‬

> Samsung a30 my device
>

**Comment by emadpost2016** [comment]
‫في الخميس، 4 يونيو 2020 في 10:20 ص تمت كتابة ما يلي بواسطة اونا الصغنونة <‪
emad.post2016@gmail.com‬‏>:‬

> bottom in my cart the same issue and when i change value to 30  that
> solve issue in my list productlistdart but another places give me same
> issue in my card product bottem  in the ( you can like also ) bottem the
> product details  and bottem my cart
>
>
> ‫في الخميس، 4 يونيو 2020 في 6:37 ص تمت كتابة ما يلي بواسطة اونا الصغنونة <‪
> emad.post2016@gmail.com‬‏>:‬
>
>> Samsung a30 my device
>>

**Comment by minhcasi** [comment]
@emadpost2016 - pls help to try with latest `1.7.5` that release on today - thank you!

**Comment by emadpost2016** [comment]
Any update on this?
Are you uploaded 1.7.5

**Comment by minhcasi** [comment]
Yes, it is updated - please help to download and let us know if you have any issues - thank you!

**Comment by emadpost2016** [comment]
Iam update to 1.7.5 but the image doesn't show in some places like this

**Comment by Alnaggar94** [comment]
@minhcasi same with me some images doesn't show !! It's the latest 1.7.5

**Comment by emadpost2016** [comment]
Pls solve this problem

**Comment by minhcasi** [comment]
@emadpost2016 - we are not quite sure about this issue, could you try to check if there is any plugin from the WooCommerce site that cause the issues, example some image cache or security plugin will prevent access from the app (although it could be reached from the browser)?

**Comment by emadpost2016** [comment]
I want send to you my word press admin username and password  and pls help
me and integrate with this app and send me source code

**Comment by emadpost2016** [comment]
Any update on this?
And any help in this problem in build app

**Comment by emadpost2016** [comment]
![20200611_201012](https://user-images.githubusercontent.com/58606378/84600697-8a234880-ae7b-11ea-9423-df167c44216b.jpg)
Any help in this problem

**Comment by minhcasi** [comment]
@emadpost2016 - could i check if you have upgrade any build grade form android studio? Please make sure to use the default build grade form the download package - thank you!

**Comment by emadpost2016** [comment]
[image: image.png]

‫في الاثنين، 15 يونيو 2020 في 5:54 م تمت كتابة ما يلي بواسطة ‪Emad Fouad‬‏
<‪emad.post2016@gmail.com‬‏>:‬

> i donot update any thing from source code and give me the same problem and
> i changed android studio and install another one same version and give same
> problem
> [image: image.png]
>
> On Sat, Jun 13, 2020, 9:44 PM Mail Delivery Subsystem <

**Comment by emadpost2016** [comment]
---------- Forwarded message ---------
من: Emad Fouad <emad.post2016@gmail.com>
‪Date: الاثنين، 15 يونيو 2020 في 5:54 م‬
Subject: Re: Delivery Status Notification (Failure)
To: Mail Delivery Subsystem <mailer-daemon@googlemail.com>


i donot update any thing from source code and give me the same problem and
i changed android studio and install another one same version and give same
problem
[image: image.png]

**Comment by kvt0012** [comment]
You can resize your image with size not over place, thank you

**Comment by minhcasi** [comment]
@emadpost2016 - Could you check this solution as well https://github.com/flutter/flutter/issues/59355#issuecomment-643482076

**Comment by minhcasi** [comment]
pls move all conversation relate to android-r to this ticket #3708
