### ISSUE TITLE
Fluxbuilder issue

### ISSUE THREAD

**Issue by ekramul-1** [inspireui/support#3543]
Please have a look into this issue & please let me know the solution please
![image](https://user-images.githubusercontent.com/63785688/83427923-2185a600-a44f-11ea-8188-a22ceb7fe70c.png)

_Originally posted by @ekramul-1 in https://github.com/inspireui/support/issues/3481#issuecomment-636943170_

**Comment by ekramul-1** [comment]
**Dear support team & @vumanhsn97,**

First of all thank you for making this fantastic app. I need your support that the below mention issues :-

I published one app in google play & that one developted under ionic/cordova.
My bundle is mentioned bbmall.in in config.xml & now the issue is coming

that am I able to change  the bundle id from "com.inspireui.fluxstore.vendor" to "bbmall.in" ?
do I need to change any other things as well ?
Please, I urge you to assist me here either I will lost many positives review.

I have the apk sign details that the last time I was published.

**Comment by ekramul-1** [comment]
Please have a look into this matter @minhcasi

**Comment by ekramul-1** [comment]
Try to understand that if our issues is not that urgent then we will try by our self @minhcasi 
Two days going on

**Comment by minhcasi** [comment]
@ekramul-1 - sorry i lost your reply message. 

Please help to check this guide to replace your own bundle id - https://docs.inspireui.com/fluxstore/delivery-android/ 

One it is changed to your own previous id `bbmall.in` you could override and upload to existing app. Make sure to use the same previous store key as well

**Comment by ekramul-1** [comment]
App is taking too much time to load the data, any solution

**Comment by ekramul-1** [comment]
> @ekramul-1 - sorry i lost your reply message. 
> 
> Please help to check this guide to replace your own bundle id - https://docs.inspireui.com/fluxstore/delivery-android/ 
> 
> One it is changed to your own previous id `bbmall.in` you could override and upload to existing app. Make sure to use the same previous store key as well
> 
> <blockquote><img src="https://docs.inspireui.com/images/meta/Ghost-Docs.jpg" width="48" align="right"><div>InspireUI Document</div><div><strong><a href="https://docs.inspireui.com/fluxstore/delivery-android/">FluxStore - Universal mobile commerce Flutter app for Magento, WooCommerce and Opencart</a></strong></div><div>Fluxstore is universal app that fully integration with the Woocommerce, Mangeto and Opencart</div></blockquote>

*Another confusion*
Do I also need to change the folder name i.e:- com Folder to in
inspire Folder to bbmall
.com.vendor....

**Comment by minhcasi** [comment]
@ekramul-1 - pls help to check this image solution to optimize your app - https://docs.inspireui.com/fluxstore/performance/#2-image-optimization

Also, please try to use the latest version.

Yes, please try to update the folder name as well - detail guide: https://docs.inspireui.com/fluxstore/delivery-android/#12-change-the-app-bundle-id-package-name

**Comment by ekramul-1** [comment]
Please note that the file *android/app/google-services.json* should be *download again* from Firebase to match your new bundle id. Otherwise the app will crash.

*could you please tell me that how I will download again*

**Comment by minhcasi** [comment]
@ekramul-1 - pls go the Firebase > Project Settings

<img width="1370" alt="Screen Shot 2020-06-08 at 15 38 32" src="https://user-images.githubusercontent.com/1459805/84009894-1de9a600-a99e-11ea-9652-8dc2cfacc63b.png">

**Comment by ekramul-1** [comment]
Websites became too slow, I hope that is the reason of application taking too long time.

As I seen that from your side already provided one demo website, so can I set that, if yes then could you please help me with the process

**Comment by ekramul-1** [comment]
> Websites became too slow, I hope that is the reason of application taking too long time.
> 
> As I seen that from your side already provided one demo website, so can I set that, if yes then could you please help me with the process

@minhcasi

**Comment by ekramul-1** [comment]
> @ekramul-1 - could you confirm if already apply this Caching solution as my previous comment - https://docs.inspireui.com/fluxstore/performance/#2-image-optimization?
> 
> <blockquote><img src="https://docs.inspireui.com/images/meta/Ghost-Docs.jpg" width="48" align="right"><div>InspireUI Document</div><div><strong><a href="https://docs.inspireui.com/fluxstore/performance/">FluxStore - Universal mobile commerce Flutter app for Magento, WooCommerce and Opencart</a></strong></div><div>Fluxstore is universal app that fully integration with the Woocommerce, Mangeto and Opencart</div></blockquote>

Yes it did this but showing optimisation is done & running in background

**Comment by minhcasi** [comment]
@ekramul-1 - could you try with latet fluxbuilder `1.0.5` and fluxstore `1.7.5` - there are some improvement on these release  - thank you!

**Comment by ekramul-1** [comment]
![image](https://user-images.githubusercontent.com/63785688/85911920-223f0b80-b846-11ea-9088-de4f8f530a2f.png)
@minhcasi Could you please check this error in new update.

**Comment by ekramul-1** [comment]
![image](https://user-images.githubusercontent.com/63785688/85928872-0a12cf00-b8ce-11ea-9ade-9ebed754e285.png)
