### ISSUE TITLE
login FluxStore

### ISSUE THREAD

**Issue by abd096** [inspireui/support#3544]
Hello

i updated the app for the latest version you have published two days ago, but my previews issues still the same.

This is the previews issues link:

https://github.com/inspireui/support/issues/3239

Please urgent support

**Comment by minhcasi** [comment]
@kvt0012 - pls help with checking - thank you!

**Comment by kvt0012** [comment]
Can you take me screenshot, thank you

**Comment by abd096** [comment]
here you go a video of the issue,

same for android and ios 

https://jumpshare.com/v/5mmgadRycTZVnllxA8Yg

**Comment by Cheewingtan** [comment]
> here you go a video of the issue,
> 
> same for android and ios
> 
> https://jumpshare.com/v/5mmgadRycTZVnllxA8Yg
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/8e8a9cba8820471156c759665db949d93b5bd56a/68747470733a2f2f64336c6c68396d376e7068706c662e636c6f756466726f6e742e6e65742f445a4668745a7842462d5f794150705151477945327a633265553334565349544f613059653735587175616f55796a33734556474c354e6a5878444e4d7057325a6e62555a666d656259696172304154465a58463567">Jumpshare**[RPReplay_Final1589735494.mp4](https://jumpshare.com/v/5mmgadRycTZVnllxA8Yg)**Shared with Jumpshare

I get the same issue too always keep loading and loading

**Comment by abd096** [comment]
@kvt0012 @minhcasi any update please ?

**Comment by stickypages** [comment]
I would assume this is a setup issue with Firebase. I debugged this, ensure your password is at least 6 characters long. 

On my test, it was an issue with "/lib/screens/users/registration.dart" around Line 206. This was my code

```
onPressed: () async {
                            var success = false;
                            try {
                              if(password.length < 6) {
                                _snackBar('Password should be at least 6 characters long');
                              } else {
                                await _auth.createUserWithEmailAndPassword(
                                    email: username, password: password);
                                success = true;
                              }
                            } catch (e) {
                              success = false;
                              print(e);
                            }
                            if(true == success) {
                              _submitRegister(
                                  firstName, lastName, username, password);
                            }
                          },
```

**Comment by abd096** [comment]
@stickypages I tried your fix, it didnt work for me. @kvt0012 please advice

**Comment by stickypages** [comment]
Get it to print an error using print () and see what it says.

**Comment by abd096** [comment]
I am getting this from the console:


> I/flutter (13205): token: dpbwNmmGHt0:APA91bFlmBDLZ1vZvKAPb5nWadKDOQ4VRaGO15sAqAZrv7twdZ8aCii7qW9SL61GL3Gq9sbMQ5G-y_bxM-Dim59RdizKjaG4-slBhO2mSoBNj3Hz48fPeFK-BxpskcfrunNW-9hhb6z0
> W/DynamiteModule(13205): Local module descriptor class for providerinstaller not found.
> I/DynamiteModule(13205): Considering local module providerinstaller:0 and remote module providerinstaller:0
> W/ProviderInstaller(13205): Failed to load providerinstaller module: No acceptable module found. Local version is 0 and remote version is 0.
> W/minaldar.marke(13205): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, linking, allowed)
> W/minaldar.marke(13205): Accessing hidden method Lsun/misc/Unsafe;->copyMemory(JJJ)V (greylist,core-platform-api, linking, allowed)
> W/minaldar.marke(13205): Accessing hidden method Lsun/misc/Unsafe;->getByte(J)B (greylist,core-platform-api, linking, allowed)
> W/minaldar.marke(13205): Accessing hidden method Lsun/misc/Unsafe;->getByte(Ljava/lang/Object;J)B (greylist,core-platform-api, linking, allowed)
> W/minaldar.marke(13205): Accessing hidden method Lsun/misc/Unsafe;->getLong(J)J (greylist,core-platform-api, linking, allowed)
> W/minaldar.marke(13205): Accessing hidden method Lsun/misc/Unsafe;->putByte(JB)V (greylist,core-platform-api, linking, allowed)
> W/minaldar.marke(13205): Accessing hidden method Lsun/misc/Unsafe;->putByte(Ljava/lang/Object;JB)V (greylist,core-platform-api, linking, allowed)
> W/minaldar.marke(13205): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, reflection, allowed)
> W/minaldar.marke(13205): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, reflection, allowed)
> V/NativeCrypto(13205): Registering com/google/android/gms/org/conscrypt/NativeCrypto's 286 native methods...
> W/minaldar.marke(13205): Accessing hidden method Ljava/security/spec/ECParameterSpec;->getCurveName()Ljava/lang/String; (greylist, reflection, allowed)
> I/ProviderInstaller(13205): Installed default security provider GmsCore_OpenSSL
> W/minaldar.marke(13205): Accessing hidden field Ljava/net/Socket;->impl:Ljava/net/SocketImpl; (greylist, reflection, allowed)
> W/minaldar.marke(13205): Accessing hidden method Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard; (greylist,core-platform-api, linking, allowed)
> W/minaldar.marke(13205): Accessing hidden method Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V (greylist,core-platform-api, linking, allowed)
> W/minaldar.marke(13205): Accessing hidden field Ljava/io/FileDescriptor;->descriptor:I (greylist, JNI, allowed)
> W/minaldar.marke(13205): Accessing hidden method Ljava/security/spec/ECParameterSpec;->setCurveName(Ljava/lang/String;)V (greylist, reflection, allowed)
> W/System  (13205): A resource failed to call release. 
> I/chatty  (13205): uid=10152(com.minaldar.market) FinalizerDaemon identical 1 line
> W/System  (13205): A resource failed to call release. 
> W/minaldar.marke(13205): Accessing hidden method Ldalvik/system/BlockGuard;->getThreadPolicy()Ldalvik/system/BlockGuard$Policy; (greylist,core-platform-api, linking, allowed)
> W/minaldar.marke(13205): Accessing hidden method Ldalvik/system/BlockGuard$Policy;->onNetwork()V (greylist, linking, allowed)
> D/EGL_emulation(13205): eglMakeCurrent: 0xecf22130: ver 3 0 (tinfo 0xae6b92f0)

**Comment by stickypages** [comment]
Well it's good that you got a token back from Firebase, so that means your on the right step. But something locally is off. Perhaps trying renaming your 'build' folder, and letting it do a full re-build. And see if it clears anything out.

**Comment by abd096** [comment]
@minhcasi @kvt0012  i just tested that latest version you published today, the issue is not fixed yet. still as same as before

**Comment by investisocial** [comment]
Hi, i've the same problem! When i insert username and password redirect doesn't regularly work and waiting for an action! Is there a solution please?
Regards
Carlo

**Comment by investisocial** [comment]
I've solved this issue with regenerating config_it.json file by fluxbuilder and overwriting it. Now I regularly login and logout.

**Comment by abd096** [comment]
@kvt0012 @minhcasi why no one is helping ?

**Comment by minhcasi** [comment]
@abd096 - sorry for late response on this ticket - We wanted to thank you for your patience during this busy time. We currently have reduced staff and a significantly higher volume of inquiries.

Would you mind to share your current project to support@inspireui.com - we will help for quick checking your current issue. If you have screenshot issue pls also include - thank you for your time

**Comment by minhcasi** [comment]
Let us know if you have any feedback
