### ISSUE TITLE
Hi, There is the still a small issue

### ISSUE THREAD

**Issue by JaserJsk** [inspireui/support#3545]
Hi,

Sorry I did not give you enough information. Here are the next steps you have to do after replace the home.dart
- In main.dart, change the code to the highlighted term
![image](https://user-images.githubusercontent.com/54442328/83490595-7fab9b00-a4da-11ea-8c10-94dfe5d2befd.png)

- In the config_xx.json, set StickyHeader to false.

That's all you have to do. :)

There is the still a small issue

After doing all the changes that you mentioned above
There is still the issue with the Search Bar

Can you tell me how to add a small space bellow the Search Bar ?
Screenshot : https://ibb.co/wCCZ6wr

**Comment by philipvu30** [comment]
Closed as a duplicated topic.
