### ISSUE TITLE
[FluxStore w/ Woocommerce] Out of stock variable product error when selecting variable

### ISSUE THREAD

**Issue by and-eee** [inspireui/support#3546]
Running FluxStore on Woocommerce, for variable products which are out of stock, when any variable is selected this error is thrown: 

**Error in NoSuchMethodError: The method '_greaterThanFromInteger' was called or null.**
**Receiver: null**
**Tried calling: _greaterThanFromInteger(0)**

Screen on product load (before selecting variation):

![image](https://user-images.githubusercontent.com/63891246/83514310-c3bc9100-a516-11ea-9f62-8b2edbaac6b8.png)

Screen after selecting any variation:

![image](https://user-images.githubusercontent.com/63891246/83514359-da62e800-a516-11ea-855b-e64717614977.png)

I will load Common and Config folders for your reference.

Cheers.

**Comment by minhcasi** [comment]
@and-eee - thank you for reporting, we could not reproduce this issue on latest code, could i know what is the version you are using for testing?

**Comment by and-eee** [comment]
@minhcasi I'm on 1.7.4

**Comment by minhcasi** [comment]
@and-eee - we confirm to fix it on latest `1.7.5` - it will be ready soon - thank you!

**Comment by and-eee** [comment]
Thank you @minhcasi, will continue development on other aspects in the meantime. I haven't seen a document on how upgrades work, can you let me know what needs to be done when a new release is out?

**Comment by minhcasi** [comment]
@and-eee - please help to check this video guide https://www.youtube.com/watch?v=SWLHKx-xzn0

guide: https://github.com/inspireui/support/wiki/Guide-to-using-git-to-work-repo-Fluxstore-pro

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
