### ISSUE TITLE
[ListApp] Building app

### ISSUE THREAD

**Issue by Squaggs** [inspireui/support#355]
**Mandatory Info (please complete the following information):**
 - Product: [ListApp]
 - Your Purchased Code: {email me to confirm please this is public. User name: Squaggs]

**Describe the issues**

I have having a problem with the app setup.

The 'run set' seems to work fine and complete until I need to 'build android' and then I get the problems in screen shot.

Another issue is I have expo and scoop correctly installed on my system but building tool does not seem to agree

**Screenshots**

https://ibb.co/r4ZRWZQ

https://ibb.co/ySzTJB9

**Additional context**

**Comment by thangvo9x** [comment]
Hi. Do you try to install or update the expo-cli to the lastest ? some solutions such as : 
check latest yarn lib, update expo-cli, config Variable Environment. Thanks
