### ISSUE TITLE
Keypad closes automatically while typing in search.

### ISSUE THREAD

**Issue by deep12650** [inspireui/support#3551]
Go to the search start typing, once result start displaying keypad closes automatically, even you can't type full word.

+ Product & version: Fluxstore Pro 1.7.4
+ Flutter (or React Native) version: Flutter
+ Testing Device/Simulator: IOS

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as it could not be verified proof of purchase on step 2, please create the new ticket by including the purchased License info - thank you for your time.
