### ISSUE TITLE
The descrption is not property HTML formatted. 

### ISSUE THREAD

**Issue by ediruzza** [inspireui/support#3554]
The app displays the description all together rather than formatting it.

Compare to descriprition on browser version in Chrome. 
![Screenshot_20200602-150043_Chrome](https://user-images.githubusercontent.com/66277001/83559107-01eb8d80-a4e2-11ea-952d-098165c36fa6.jpg)
![Screenshot_20200602-145748_Dechoes](https://user-images.githubusercontent.com/66277001/83559108-02842400-a4e2-11ea-9db8-f49edf263ac9.jpg)

**Comment by minhcasi** [comment]
@ediruzza - pls help to move your all conversation to the same ticket #3532 - our support team will help for focus on your issue, thank you for your time!
