### ISSUE TITLE
node_modules file is not exist in project which i have downloaded

### ISSUE THREAD

**Issue by jitu94517** [inspireui/support#3557]
When I was creating apk this error was shown
A problem occurred evaluating setting ‘mstore’ Could not read script ’ C:\users\desktop\mstore-pro\node_modules\@react-native-community\cli-platform-android\native_modules.gradle’ as it does not exist.

![Screenshot (106)](https://user-images.githubusercontent.com/66323700/83583567-4dde1700-a562-11ea-8b87-588814e1916b.png)

**Comment by jitu94517** [comment]
how to merging a pull request ?

**Comment by luyx2412** [comment]
Hi @jitu94517 Please use `yarn install` to install your node\_modules. Please read the document how to install and start the app. https://docs.inspireui.com/mstore/getting-started/

Thanks

**Comment by luyx2412** [comment]
Hi @jitu94517 Please use `yarn install` to install your node\_modules. Please read the document how to install and start the app. https://docs.inspireui.com/mstore/getting-started/

Thanks

**Comment by jitu94517** [comment]
Did but again get same problem...

**Comment by luyx2412** [comment]
Hi @jitu94517 Please follow the comment to fix your issues react-native-community/cli#591

Thanks

**Comment by jitu94517** [comment]
i have tried every things which you have suggested me but still facing the same problem...
can you do this for me through "AnyDesk". ?

**Comment by jitu94517** [comment]
when i am installing yarn this error show me "error Couldn't find the binary git"

**Comment by minhcasi** [comment]
@jitu94517 - pls try to install this lib to fix the git issue - https://git-scm.com/download/win

**Comment by jitu94517** [comment]
When trying to generate apk, got this error.
![error_gen_apk](https://user-images.githubusercontent.com/66323700/83939444-be06ca00-a7fa-11ea-96dc-436f72b2cdf9.png)

**Comment by jitu94517** [comment]
@luyx2412 sir please give me proper solution for this

**Comment by luyx2412** [comment]
Hi @jitu94517 Please send me the log file or specific screenshot about the issues which investigate easier.

Thanks

**Comment by jitu94517** [comment]
@luyx2412 
![error_gen_apk](https://user-images.githubusercontent.com/66323700/83962474-5f555500-a8bb-11ea-826a-80c7c0023335.png)

**Comment by jitu94517** [comment]
import io.invertase.gradle.common.PackageJson

buildscript {
  // The Android Gradle plugin is only required when opening the android folder stand-alone.
  // This avoids unnecessary downloads and potential conflicts when the library is included as a
  // module dependency in an application project.
  if (project == rootProject) {
    repositories {
      google()
      jcenter()
    }

    dependencies {
      classpath("com.android.tools.build:gradle:3.5.2")
    }
  }
}

plugins {
  id "io.invertase.gradle.build" version "1.4"
}

def packageJson = PackageJson.getForProject(project)
def firebaseBomVersion = packageJson['sdkVersions']['android']['firebase']

project.ext {
  set('react-native', [
    versions: [
      android : [
        minSdk    : 16,
        targetSdk : 28,
        compileSdk: 28,
        // optional as gradle.buildTools comes with one by default
        // overriding here though to match the version RN uses
        buildTools: "28.0.3"
      ],

      firebase: [
        bom: firebaseBomVersion,
      ],
    ],
  ])
}

android {
  defaultConfig {
    multiDexEnabled true
  }
  lintOptions {
    disable 'GradleCompatible'
    abortOnError false
  }
  compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
  }

  sourceSets {
    main {
      java.srcDirs = ['src/main/java', 'src/reactnative/java']
    }
  }
}

repositories {
  google()
  jcenter()
}

dependencies {
  implementation platform("com.google.firebase:firebase-bom:${ReactNative.ext.getVersion("firebase", "bom")}")
  implementation "com.google.firebase:firebase-core"
  implementation "com.google.firebase:firebase-common"
}

apply from: file("./firebase-json.gradle")

ReactNative.shared.applyPackageVersion()
ReactNative.shared.applyDefaultExcludes()
ReactNative.module.applyAndroidVersions()
ReactNative.module.applyReactNativeDependency("api")

**Comment by jitu94517** [comment]
@luyx2412  I have started this project again from scratch, but again getting the same error when generating release apk
**### Error is** 
> Task :app:bundleReleaseJsAndAssets FAILED

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\Acer\Desktop\mstore-pro\node_modules\react-native\react.gradle' line: 151

* What went wrong:
Execution failed for task ':app:bundleReleaseJsAndAssets'.
> Process 'command 'cmd'' finished with non-zero exit value -1073741515

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9m 6s
1 actionable task: 1 executed

![error](https://user-images.githubusercontent.com/66323700/83984457-f02b3f80-a952-11ea-8e73-c1a62942dc01.png)

**Comment by luyx2412** [comment]
Hi @jitu94517 Please send me the log file which will easier to investigate.

Thanks

**Comment by jitu94517** [comment]
@luyx2412 
[react.zip](https://github.com/inspireui/support/files/4750387/react.zip)

**Comment by jitu94517** [comment]
> Hi @jitu94517 Please send me the log file which will easier to investigate.
> 
> Thanks

[react.zip](https://github.com/inspireui/support/files/4750397/react.zip)

**Comment by jitu94517** [comment]
@luyx2412 
This error shown me 
> Task :app:bundleReleaseJsAndAssets FAILED

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\Acer\Desktop\mstore-pro\node_modules\react-native\react.gradle' line: 151

* What went wrong:
Execution failed for task ':app:bundleReleaseJsAndAssets'.
> Process 'command 'cmd'' finished with non-zero exit value -1073741515

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9m 20s
1 actionable task: 1 executed
[react.zip](https://github.com/inspireui/support/files/4750495/react.zip)

**Comment by jitu94517** [comment]
@luyx2412 
**### This error shown me, file is attached at bottom....**

Task :app:bundleReleaseJsAndAssets FAILED

FAILURE: Build failed with an exception.

Where:
Script 'C:\Users\Acer\Desktop\mstore-pro\node_modules\react-native\react.gradle' line: 151

What went wrong:
Execution failed for task ':app:bundleReleaseJsAndAssets'.

Process 'command 'cmd'' finished with non-zero exit value -1073741515

Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

Get more help at https://help.gradle.org

BUILD FAILED in 9m 20s
1 actionable task: 1 executed

[react.zip](https://github.com/inspireui/support/files/4750501/react.zip)

**Comment by luyx2412** [comment]
HI @jitu94517 Can you send me your node version?

Thanks

**Comment by jitu94517** [comment]
@luyx2412 
My node version is v14.4.0

**Comment by luyx2412** [comment]
HI @jitu94517 Please downgrade your node version to 10 or use nvm https://github.com/nvm-sh/nvm to switch to node 10. Please it have some issues related to another node, specially the newest node version.

Thanks

**Comment by jitu94517** [comment]
@luyx2412 still getting the same error

**Comment by jitu94517** [comment]
@luyx2412 ### **Facing this error**

C:\Users\Jitu\Desktop\mstore-pro\android>gradlew bundleRelease
Starting a Gradle Daemon, 1 stopped Daemon could not be reused, use --status for details

> Configure project :@react-native-firebase_app
:@react-native-firebase_app:firebase.bom using default value: 24.1.0
:@react-native-firebase_app package.json found at C:\Users\Jitu\Desktop\mstore-pro\node_modules\@react-native-firebase\app\package.json
:@react-native-firebase_app:version set from package.json: 6.2.0 (6,2,0 - 6002000)
:@react-native-firebase_app:android.compileSdk using custom value: 28
:@react-native-firebase_app:android.targetSdk using custom value: 28
:@react-native-firebase_app:android.minSdk using custom value: 16
:@react-native-firebase_app:reactNativeAndroidDir C:\Users\Jitu\Desktop\mstore-pro\node_modules\react-native\android

> Configure project :@react-native-firebase_auth
:@react-native-firebase_auth:firebase.bom using default value: 21.1.0
:@react-native-firebase_auth package.json found at C:\Users\Jitu\Desktop\mstore-pro\node_modules\@react-native-firebase\auth\package.json
:@react-native-firebase_auth:version set from package.json: 6.2.0 (6,2,0 - 6002000)
:@react-native-firebase_auth:android.compileSdk using custom value: 28
:@react-native-firebase_auth:android.targetSdk using custom value: 28
:@react-native-firebase_auth:android.minSdk using custom value: 16
:@react-native-firebase_auth:reactNativeAndroidDir C:\Users\Jitu\Desktop\mstore-pro\node_modules\react-native\android

> Configure project :app
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

> Configure project :react-native-apple-authentication
WARNING: API 'variant.getJavaCompile()' is obsolete and has been replaced with 'variant.getJavaCompileProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getJavaCompile(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.

> Configure project :app
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

> Task :app:bundleReleaseJsAndAssets
warning: the transform cache was reset.
Loading dependency graph, done.
info Writing bundle output to:, C:\Users\Jitu\Desktop\mstore-pro\android\app\build\generated\assets\react\release\index.android.bundle
info Writing sourcemap output to:, C:\Users\Jitu\Desktop\mstore-pro\android\app\build\intermediates\sourcemaps\react\release\index.android.bundle.packager.map
info Done writing bundle output
info Done writing sourcemap output
info Copying 110 asset files
info Done copying assets

> Task :app:bundleReleaseJsAndAssets FAILED

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\Jitu\Desktop\mstore-pro\node_modules\react-native\react.gradle' line: 151

* What went wrong:
Execution failed for task ':app:bundleReleaseJsAndAssets'.
> Process 'command 'cmd'' finished with non-zero exit value -1073741515

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7m 7s
10 actionable tasks: 1 executed, 9 up-to-date

**Comment by luyx2412** [comment]
Hi @jitu94517 Please follow this comment to fix your issue https://github.com/facebook/react-native/issues/23516#issuecomment-466032988.

Thanks

**Comment by jitu94517** [comment]
**### Hello @luyx2412 Now I getting new error**
Log
> Configure project :@react-native-firebase_app
:@react-native-firebase_app:firebase.bom using default value: 24.1.0
Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\Jitu\Desktop\mstore-pro\node_modules\@react-native-firebase\app\android\build.gradle' line: 66

* What went wrong:
A problem occurred evaluating project ':@react-native-firebase_app'.
> Could not find method platform() for arguments [com.google.firebase:firebase-bom:24.1.0] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by luyx2412** [comment]
Hi @jitu94517 Please follow this issue to fix your issue https://github.com/invertase/react-native-firebase/issues/2794. The issue related install gradle.

Thanks
