### ISSUE TITLE
Firebase Authentication.

### ISSUE THREAD

**Issue by boqaqa** [inspireui/support#3558]
Hello and thank your for this beautiful app I have 3 issues:

1. I cannot get the SHA1 certificate for my application I have created key.jks in android/app, and key.preperties in the android folder. but I am unable to get the certificates.

2. I wanted to remove cancel order/ and refund order buttons, I saw a same issue on github and did the same but I still have the refund button there.

3.Can I block some accounts on my app or ban them because they don't want to buy things and wasting my time.

best regards.

**Comment by minhcasi** [comment]
1. please check the SHA1 guide on this link https://medium.com/@inspireui/setup-google-login-for-flutter-apps-fedc58a490b8 or https://flutter.dev/docs/deployment/android#create-a-keystore

2. pls add this code https://tppr.me/2SzT6

3. i'm not sure about this feature, i think you could try to add the Wordpress plugin to block the user login from your system and disable there account to prevent login from the app.

**Comment by boqaqa** [comment]
![firebase key](https://user-images.githubusercontent.com/65863900/83642772-ece12e00-a5b7-11ea-9cd2-7534f705e877.png)
![key pass](https://user-images.githubusercontent.com/65863900/83642775-eeaaf180-a5b7-11ea-867c-b4c909a4be6b.png)
![Screenshot_20200603-161612](https://user-images.githubusercontent.com/65863900/83643162-5e20e100-a5b8-11ea-8763-2bffd8c7bf6f.jpg)

I am doing everything right and sms verification is not working please help.

I have created a keystore and genrated the SH1 certificates then copied them to firebase but still it's not working can you please do it for me via teamviewer!

**Comment by boqaqa** [comment]
After trying many times to solve my issues I got this new one,

FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:validateSigningRelease'.
> Keystore file 'C:\src\flutter\Online\FluxStore\source\android\app\key.jks>' not found for signing config 'release'.

This means I cannot try anymore because I can't build an apk to test if the problem is gone so please help,


* Try:

Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by stickypages** [comment]
Your screenshot doesn't look like you put the info in the right spot. This is the gradle file, look in the config for that.
![83642775-eeaaf180-a5b7-11ea-867c-b4c909a4be6b](https://user-images.githubusercontent.com/658488/83696920-83125580-a5b2-11ea-81ed-b56d8d0c2472.png)

Is your key place in the right spots of the app?
I'm going off of memory, but there is a 'certs' fold as well as /android/key.jks

Just my thoughts

**Comment by boqaqa** [comment]
![Untitled](https://user-images.githubusercontent.com/65863900/83697283-4290f700-a607-11ea-9039-a4356d645be2.jpg)

Should I right something in this two places.

I am in trouble, please tell me where is the right place.

My key is in /android/app

and they key.properties in the android folder

**Comment by stickypages** [comment]
I wouldn't touch that in there, I never did and mine is building.

try flutter doctor
in key.properties, it is referenced in your #2 circle... keyAlias IS
key.properties (keyAlias).... don't change anything in that file for now.


All the best,


*Justin Giesbrecht* | justin@stickypages.ca
250-869-5952 | www.stickypages.ca

**Comment by boqaqa** [comment]
I cant believe it! Everything worked fine I just added under debug: signingconfig signingcofig.release and and replaced key.jks in certs folder with key.jks in /android/app. Thank you @stickypages and @minhcasi for helping.

![Untitled](https://user-images.githubusercontent.com/65863900/83700541-c6e77800-a60f-11ea-82bd-47e7248b9088.jpg)

**Comment by minhcasi** [comment]
related #3151

**Comment by minhcasi** [comment]
@boqaqa - there is no problem, by that config, your app will using the key as release mode for authentication. 

Let us know if you have any question

**Comment by boqaqa** [comment]
Thank you very much.
