### ISSUE TITLE
Login with An API for JSON API Auth Word Press plugin

### ISSUE THREAD

**Issue by minhtet-BeeComTech** [inspireui/support#3559]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: I have an issue that is not logged in
![Screen Shot 2020-06-03 at 08 42 11](https://user-images.githubusercontent.com/60533218/83587909-2abd6280-a576-11ea-95ac-dbf758fa2af8.png)

+ Product & version: MStore Multi Vendor app & version - 1.3.3
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: Simulator
+ Screenshot issues (drag the file to attach here): 
![Screen Shot 2020-06-02 at 10 24 14](https://user-images.githubusercontent.com/60533218/83587392-fd23e980-a574-11ea-818b-dd5f2fc1c622.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhtet-BeeComTech** [comment]
Please, can you solved? Why this problem?

**Comment by luyx2412** [comment]
Hi @minhtet-BeeComTech Please update latest mstore-api version which will fix your issues.

Thanks

**Comment by minhtet-BeeComTech** [comment]
@luyx2412 I has been updated it, but I still have an error
![Screen Shot 2020-06-03 at 08 41 03](https://user-images.githubusercontent.com/60533218/83713861-45173f00-a64f-11ea-9f27-c584e4faf0a4.png)

**Comment by minhtet-BeeComTech** [comment]
@luyx2412 Please take a look at the issue above

**Comment by luyx2412** [comment]
Hi @minhtet-BeeComTech In wordpress dashboard please add your license key to use the plugin. All features will unlock.

![](https://user-images.githubusercontent.com/8909619/83766703-eed5ea80-a6a6-11ea-9ae4-0f517edf6744.png)

Thanks

**Comment by luyx2412** [comment]
Closed!

P/S: Feel free to reopen the issue.
