### ISSUE TITLE
[MStore] proper variant are not showing and on shake no menu option open

### ISSUE THREAD

**Issue by webliskatech** [inspireui/support#356]
All attribute are showing on screen.
let say i have 10 attribute out of which i only use 2 attribute for variation.
only that 2 attribute should be show on screen instead on all.
in my website it showing only 2 attribute but in app it showing all
please help me
and also when i run it though expo in android emulator and when i shake ,it does not show option of menu.
i want to live reload and debug things
but shaking does not do anything
in my other projects shaking is working but not working on mStore

**Comment by luyx2412** [comment]
Hi @webliskatech What's the device name? Maybe you did not open debug mode.

Thanks
