### ISSUE TITLE
I got error while compile an app 

### ISSUE THREAD

**Issue by gengefasta** [inspireui/support#3560]
I got this error while compile with android simulator, im using intelJ

Launching lib\main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve com.google.android.gms:play-services-ads-identifier:[15.0.0, 16.0.99].
     Required by:
         project :app > com.onesignal:OneSignal:3.13.2
      > Failed to list versions for com.google.android.gms:play-services-ads-identifier.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/google/android/gms/play-services-ads-identifier/maven-metadata.xml.
            > Could not get resource 'https://jcenter.bintray.com/com/google/android/gms/play-services-ads-identifier/maven-metadata.xml'.
               > Could not GET 'https://jcenter.bintray.com/com/google/android/gms/play-services-ads-identifier/maven-metadata.xml'.
                  > jcenter.bintray.com
      > Failed to list versions for com.google.android.gms:play-services-ads-identifier.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/google/android/gms/play-services-ads-identifier/maven-metadata.xml.
            > Could not get resource 'https://jcenter.bintray.com/com/google/android/gms/play-services-ads-identifier/maven-metadata.xml'.
               > Could not GET 'https://jcenter.bintray.com/com/google/android/gms/play-services-ads-identifier/maven-metadata.xml'.
                  > jcenter.bintray.com
      > Failed to list versions for com.google.android.gms:play-services-ads-identifier.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/google/android/gms/play-services-ads-identifier/maven-metadata.xml.
            > Could not get resource 'https://jcenter.bintray.com/com/google/android/gms/play-services-ads-identifier/maven-metadata.xml'.
               > Could not GET 'https://jcenter.bintray.com/com/google/android/gms/play-services-ads-identifier/maven-metadata.xml'.
                  > jcenter.bintray.com
      > Failed to list versions for com.google.android.gms:play-services-ads-identifier.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/google/android/gms/play-services-ads-identifier/maven-metadata.xml.
            > Could not get resource 'https://jcenter.bintray.com/com/google/android/gms/play-services-ads-identifier/maven-metadata.xml'.
               > Could not GET 'https://jcenter.bintray.com/com/google/android/gms/play-services-ads-identifier/maven-metadata.xml'.
                  > jcenter.bintray.com

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13m 9s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by sarbaz989** [comment]
same with me
