### ISSUE TITLE
i don't get email notifications when an order is submited.. can you help me please

### ISSUE THREAD

**Issue by Badreddinee** [inspireui/support#3561]

**Comment by Badreddinee** [comment]
> We would appreciate it if you could provide us with more info (purchased code, detail screenshot) about this issue, thank you!!

i don't receive notification emails when customers submit their orders, and i need help with this

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as it could not be verified proof of purchase on step 2, please create the new ticket by including the purchased License info - thank you for your time.
