### ISSUE TITLE
Products are not shown in several categories Opencart, v.1.7.4

### ISSUE THREAD

**Issue by OlegMillennium** [inspireui/support#3562]
When I open see all of any Category it shows 0 products. But several categories show products. Why products are not shown for some categories and subcategories? See screenshots.

<img width="378" alt="Снимок экрана 2020-05-20 в 23 24 25" src="https://user-images.githubusercontent.com/26544829/83597460-0b233b80-a570-11ea-9373-942be65a2aa9.png">
<img width="385" alt="Снимок экрана 2020-05-20 в 23 24 11" src="https://user-images.githubusercontent.com/26544829/83597467-10808600-a570-11ea-80c8-caf743b09f88.png">

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as it could not be verified proof of purchase on step 2, please create the new ticket by including the purchased License info - thank you for your time.
