### ISSUE TITLE
Can I Add options in Product_List_View?

### ISSUE THREAD

**Issue by govindh163** [inspireui/support#3563]
Product details:FluxStore Pro 1.7.3(I am using OpenCart)

I had added the Option dropdrown in  Product listview(Layout)?

But it is not updating the selected value in cart/admin website!!

This is the code I added in product_list_tile.dart
---https://gist.github.com/govindh163/92e8faa64d8851cb1fc08eb0bcc701f1

The Screenshot:
---https://tppr.me/9O7CO

Is there is any way to solve this? 
@minhcasi

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as it could not be verified proof of purchase on step 2, please create the new ticket by including the purchased License info - thank you for your time.
