### ISSUE TITLE
Internal server error + No Categories synchronization 

### ISSUE THREAD

**Issue by atlasdzedgo** [inspireui/support#3564]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 1-Once Mstore plugin activated we get an internal server error please check the attached google drive video for more info.
2- response from the API for category list still gives the same response before (we need category Id to get a list of products based on category)

+ Product & version: 
Fluxstore Multi Vendor - Flutter E-commerce Full App
Version: 1.7.4
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 
https://drive.google.com/file/d/1ZI9QldGvJIicTjKeT76UfxpYPwLhwoYU/view?usp=drivesdk

![Screenshot from 2020-06-03 12-20-04](https://user-images.githubusercontent.com/66356874/83613043-d0dc8d00-a5b5-11ea-8041-0b0aa35407b0.png)
![Screenshot from 2020-06-03 12-19-44](https://user-images.githubusercontent.com/66356874/83613058-d4701400-a5b5-11ea-908c-6a29ccbb685c.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as it could not be verified proof of purchase on step 2, please create the new ticket by including the purchased License info - thank you for your time.
