### ISSUE TITLE
Fluxstore Multivendor Technical Inquiries

### ISSUE THREAD

**Issue by AlandaKong** [inspireui/support#3565]
Detail Issues: 
1. When I login different account, the items in the cart and wishlist will always be there. The items in the cart and wishlist are not followed by the users? 
![Screenshot_1591154034](https://user-images.githubusercontent.com/61262872/83591848-8219fd80-a58b-11ea-8e44-b075f8790a16.png)
![Screenshot_1591154042](https://user-images.githubusercontent.com/61262872/83591852-834b2a80-a58b-11ea-8dc6-a1cc22fc920c.png)
![Screenshot_1591154083](https://user-images.githubusercontent.com/61262872/83591853-83e3c100-a58b-11ea-8441-58d2134278ea.png)

2. Is the checkout page able to be configured based on item type for native view? For example, I will have virtual and actual products in my store but virtual products should not have shipping options during checkout while physical product should. 
(In this screenshot I have configured to disable billing address and shipping manually)
![Screenshot_1591155133](https://user-images.githubusercontent.com/61262872/83592854-e1790d00-a58d-11ea-85cb-d793b0efd6d8.png)

3. The Drawer (Left menu bar) has an option to logout but after logout, the text will still remained “Logout” instead of “Login” even though user has actually logout.
![Screenshot_1591154533](https://user-images.githubusercontent.com/61262872/83592242-7c70e780-a58c-11ea-8214-3610cbfa24c6.png)

4. Whenever launch the app, the onboarding screen will be shown even if the user is login. 
![Screenshot_1591155030](https://user-images.githubusercontent.com/61262872/83592836-d3c38780-a58d-11ea-891f-91650368cbf7.png)
![Screenshot_1591155106](https://user-images.githubusercontent.com/61262872/83592839-d4f4b480-a58d-11ea-8e29-54e9de50751b.png)

5. I have configured the IsRequiredLogin to be true however at the sign up page i press back button on left top it will redirect to the home tab.
![Screenshot_1591154962](https://user-images.githubusercontent.com/61262872/83592704-80e9d000-a58d-11ea-8875-07edb64d7349.png)
![Screenshot_1591154969](https://user-images.githubusercontent.com/61262872/83592708-821afd00-a58d-11ea-91c6-226e686ddc33.png)

6. Vendor profile page, the vendor-customer chat module does not appear 
![Screenshot_1591155592](https://user-images.githubusercontent.com/61262872/83602376-09279f80-a5a5-11ea-9461-358acc533118.png)

7. When add a new product, the adding screen is loading forever. However in the debug message I receive "FormatException: Invalid double". Even I enter the product price with decimal point, it still hits the same error and loading forever.
![Screenshot_1591173801](https://user-images.githubusercontent.com/61262872/83615608-5e6dac00-a5b9-11ea-825c-2d038dbb93f3.png)
![Screenshot_1591173842](https://user-images.githubusercontent.com/61262872/83615670-72b1a900-a5b9-11ea-899b-72082d42d4c3.png)
![Screenshot_1591173921](https://user-images.githubusercontent.com/61262872/83615901-bb696200-a5b9-11ea-8c69-ace17d17f6a6.png)

8. As in WCFM I have configured the product to be approved before published. Hence, once vendor adds a new product the product is in draft. However, I am able to see the product in vendor profile's products tab but not in products page filtered by the category.
![image](https://user-images.githubusercontent.com/61262872/83616122-071c0b80-a5ba-11ea-883c-84819afe125f.png)
![Screenshot_1591174112](https://user-images.githubusercontent.com/61262872/83616210-22871680-a5ba-11ea-8c5b-701d0b32268c.png)
![Screenshot_1591174136](https://user-images.githubusercontent.com/61262872/83616221-24e97080-a5ba-11ea-8a74-29f0a9d02db1.png)

9. The vendor's profile banner is not reflected?
![image](https://user-images.githubusercontent.com/61262872/83616641-ab9e4d80-a5ba-11ea-902a-686d4e44f225.png)
![Screenshot_1591174112](https://user-images.githubusercontent.com/61262872/83616656-b0fb9800-a5ba-11ea-8524-76ec653f8a69.png)
![Screenshot_1591174392](https://user-images.githubusercontent.com/61262872/83616696-b9ec6980-a5ba-11ea-95d6-8d23f80e3288.png)

10. I have configure on firebase and able to trigger notification from firebase Cloud Messaging. However when receive a new conversation/message, I don't receive any notification. 
![Screenshot_1591174499](https://user-images.githubusercontent.com/61262872/83616937-fddf6e80-a5ba-11ea-9b7d-7f73beaacae8.png)

11. When logout and I clicked on the reset password before login, it brings me to the my account page of my website?
![Screenshot_1591174864](https://user-images.githubusercontent.com/61262872/83617615-e94fa600-a5bb-11ea-88c0-92062ab24142.png)

12. Everytime login will hit this exception 
![image](https://user-images.githubusercontent.com/61262872/83617686-04221a80-a5bc-11ea-9eb1-a738fc3911af.png)

13. The Vendor-Customer chatting function is not synchronised with the WCFM chat module? For example, customer initialises chat from website and vendor can reply through the app.
![image](https://user-images.githubusercontent.com/61262872/83618214-b823a580-a5bc-11ea-9876-8af6165fafe7.png)
![Screenshot_1591175260](https://user-images.githubusercontent.com/61262872/83618228-be198680-a5bc-11ea-8a45-07533a5d81c3.png)

14. How can vendor manage all the orders placed by customers?

- Product & version: Fluxstore Multivendor version 1.7.3
- Flutter version: 1.18.0
- Testing Device/Simulator: Huawei Nova 2i (actual device), Pixel 3a XL (emulator)

**Comment by stickypages** [comment]
Not the developer, but what I have noticed going through some of the items. 
1, the chat module. They use different technology, hence why they are not the same as on the website. One feature is paid, firebase is included

2, When creating products, there is a 'patch' for that online in this forum, it has to do with the 'sale price' not being entered

3, Forgot password, that is in the code, it's meant to do that, as it uses the websites ability to send emails to your customer and resetting it properly through WordPress's config.

4, when you launch the app, are you launching it on your phone, or in the debug through android studio? sometime the studio doesn't keep track of the platform state. It doesn't do that on an actual build.

hope that helps clarify a few things.

**Comment by vumanhsn97** [comment]
@AlandaKong 
1, The items in cart and wishlist save in localstorage. Progress is the user can add wishlist and cart item without login so logout will not clear it
2, You can add this function in lib/screens/checkout/index.dart https://tppr.me/IXKia and replace all check enable shipping or shipping address by call this function: https://tppr.me/dqaY0
3, Checked it! But it always working well. Can you share your video record?
4,  It will not appear in release mode
5, Checked it! But it always redirect to login page. Can you share your video record?
6, Make sure you enable smartchat in lib/common/confing/smartchat.dart https://tppr.me/8G46r
7, update this line in lib/vendor/products/create_product_screen.dart: https://tppr.me/so0W0
8, Product daft will not show. You need to publish it
9, Not receive your submit form. So I can't connect to your site. You can check by your self with call link api in postman http://yoursite/flutter/wcfm-stores?per_page=10 with OAuth 1.0. And check parsed json in lib/vendor/store/store_model.dart https://tppr.me/JKsGR
10, 13, Can you share more detail?
11, Make sure you set correct link in config.dart https://tppr.me/ofDwn
12, Don't worry!!!
14, Future request!!

**Comment by AlandaKong** [comment]
1. Then the cart is not sync across website and app? From user perspective, it is kind of a bad experience? E.g. I added product A to my cart through web and when I open app to make payment I have to search and add the products again. 

2. I have setup according to your screenshots. However, when checking out virtual products, it shows as the image belows. I did replace the kPaymentConfig["EnableShipping"] and kPaymentConfig["EnableAddress"] to the new function. 
![image](https://user-images.githubusercontent.com/61262872/83738141-7ceda900-a686-11ea-85f0-dc6a6060a307.png)
![image](https://user-images.githubusercontent.com/61262872/83738174-8840d480-a686-11ea-978b-99ebeb77f398.png)

3. Here is the screen recording.
![sidebar](https://user-images.githubusercontent.com/61262872/83727561-da2e2e00-a677-11ea-9dfd-13634df3eb60.gif)

5. After onboarding screen, I chose to sign up.
![signup](https://user-images.githubusercontent.com/61262872/83727628-f5993900-a677-11ea-8331-f7313e0eebe1.gif)

6. Yes, smart chat is enabled. The issue is sometime when I navigate to the vendor profile screen it did show but sometime it didn't. 
![image](https://user-images.githubusercontent.com/61262872/83738467-ee2d5c00-a686-11ea-84c5-1ecbdf629547.png)

7. With adding the line of code https://tppr.me/so0W0, my product price will become 0.0? as i don't have sale price for this product. A product is not compulsory to have a sale price. 
![Screenshot_1591258191](https://user-images.githubusercontent.com/61262872/83731973-f339dd80-a67d-11ea-9d67-7554dbd6aaee.png)

8. Then by right the draft product should not show in the vendor's profile page? But it did. Please refer my screenshot again.

9. In the parsedJson do not consist of banner or image data?
![image](https://user-images.githubusercontent.com/61262872/83730026-14e59580-a67b-11ea-9b1f-1f1ed5f78502.png)

10. When message received, I do not receive any notification till I check my conversation only realise there is new incoming message. However, I tested using Firebase cloud messaging, my phone did receive notification but in the tab "Notify Messages" is empty. 
![Screenshot_1591257216](https://user-images.githubusercontent.com/61262872/83730424-a228ea00-a67b-11ea-9875-9ce8d1589c6f.png)
![Screenshot_20200604-155252](https://user-images.githubusercontent.com/61262872/83730862-41e67800-a67c-11ea-9085-f9c97b3a655a.jpg)
![Screenshot_1591257497](https://user-images.githubusercontent.com/61262872/83730875-4579ff00-a67c-11ea-992d-512ae5ce53d9.png)

11. I have pointed to the correct link. However, at that point of time actually I am logged out why when I click reset password it brings to my account? 

13. WCFM has a vendor-customer chat module but the chat module in Fluxstore seems not using the same database as WCFM vendor-customer chat module? Hence, the chat also doesn't sync across web and apps.
![image](https://user-images.githubusercontent.com/61262872/83731095-83772300-a67c-11ea-9479-dfe12062e748.png)
![Screenshot_1591257216](https://user-images.githubusercontent.com/61262872/83731116-88d46d80-a67c-11ea-90aa-a771f2208f4d.png)

14. Any target date to have this feature? Need to have this feature ASAP.

**Comment by vumanhsn97** [comment]
1, The cart not async between app and website
2, compare your code with list file(using git): 
[archive.zip](https://github.com/inspireui/support/files/4733878/archive.zip)
3, 4, 5: please update new version(fluxstore vendor)
6, 8 compare this code: 
[vendor.zip](https://github.com/inspireui/support/files/4734410/vendor.zip)
7, update in new version: check this code in lib/services/wcfm.dart https://tppr.me/9DwMa
9, Can't check
10, Try to test in other devices
11, Chat list screen using firebase. It is not connect to database in WCFM

**Comment by AlandaKong** [comment]
After updated to the Fluxstore Vendor version 1.7.5, several issues still remained. 
2. I have setup according to the code that you given. However, when I paid for a non-virtual product, it will skip the address and shipping tab. I tried put a print item type but it returns null. 
![image](https://user-images.githubusercontent.com/61262872/84125909-ce73aa80-aa6f-11ea-8db9-fe4f1260c0df.png)
![Screenshot_1591691978](https://user-images.githubusercontent.com/61262872/84126016-f105c380-aa6f-11ea-9d03-a66ff4c3ac19.png)

3. Still same issue, after click logout on the sidebar the text still remained.
![sidebar](https://user-images.githubusercontent.com/61262872/84122543-2bb92d00-aa6b-11ea-9957-a8abf6bad5bf.gif)

7. When add product still hit loading forever...Unhandled Exception: FormatException: Invalid double
![addproduct](https://user-images.githubusercontent.com/61262872/84126251-3fb35d80-aa70-11ea-8d3d-7dd7b126d3d9.gif)

10. I am able to view my Notify Message. However, when new message coming, I still don't get any notification. (Devices: Huawei Nova 2i, Emulator: Pixel 3XL, Pixel 3a)
![image](https://user-images.githubusercontent.com/61262872/84140517-56fc4600-aa84-11ea-830f-996af5ef82d3.png)

11. I first login and logout to the app. After that, I tried to reset password, but it redirects me to my account page of my website without logout?
![Screenshot_1591687867](https://user-images.githubusercontent.com/61262872/84122532-26f47900-aa6b-11ea-8388-40054e45648f.png)

**Comment by vumanhsn97** [comment]
@AlandaKong 
Can you send your source code with your edit to vumanhsn97@gmail.com?
