### ISSUE TITLE
Internal server error + No Categories synchronization

### ISSUE THREAD

**Issue by atlasdzedgo** [inspireui/support#3566]
Step 1 (require): describe detail issues & screenshots

Detail Issues: 1-Once Mstore plugin activated we get an internal server error please check the attached google drive video for more info.
2- response from the API for category list still gives the same response before (we need category Id to get a list of products based on category)

Product & version:
Fluxstore Multi Vendor - Flutter E-commerce Full App
Version: 1.7.4

Flutter (or React Native) version:

Testing Device/Simulator:

Screenshot issues (drag the file to attach here):
https://drive.google.com/file/d/1ZI9QldGvJIicTjKeT76UfxpYPwLhwoYU/view?usp=drivesdk
![Screenshot from 2020-06-03 12-20-04](https://user-images.githubusercontent.com/66356874/83616127-084d3880-a5ba-11ea-9ccc-8e635ef33c67.png)
![Screenshot from 2020-06-03 12-19-44](https://user-images.githubusercontent.com/66356874/83616135-0be0bf80-a5ba-11ea-90fa-d27be968fbe4.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhtruong315** [comment]
Hi @atlasdzedgo Your website is not working. Please check
<img width="1636" alt="Screen Shot 2020-06-05 at 4 42 17 PM" src="https://user-images.githubusercontent.com/10402500/83862033-99074e00-a74b-11ea-98af-e90abc17a11c.png">

**Comment by atlasdzedgo** [comment]
> Hi @atlasdzedgo Your website is not working. Please check
> 
> <img width="1636" alt="Screen Shot 2020-06-05 at 4 42 17 PM" src="https://user-images.githubusercontent.com/10402500/83862033-99074e00-a74b-11ea-98af-e90abc17a11c.png">
> 
> 

Hello! 

We just started doing some marketing in social media before the launch that's why we put a landing page! 
I need to give you access to WP admin. Please let me know where I can send it 

Regards

**Comment by minhtruong315** [comment]
send me via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/3566
Thanks

**Comment by minhtruong315** [comment]
Hi @atlasdzedgo I checked your config. it's working well with our api in MStore Api plugin. but woo commerce api doesn't work. Do you have any config or plugin for blocking woo commerce api?

**Comment by minhtruong315** [comment]
<img width="862" alt="Screen Shot 2020-06-08 at 10 01 49 AM" src="https://user-images.githubusercontent.com/10402500/83988983-21b20400-a96f-11ea-9340-f9956f96142a.png">

**Comment by atlasdzedgo** [comment]
My developers checking! I will update you soon

**Comment by atlasdzedgo** [comment]
> Hi @atlasdzedgo I checked your config. it's working well with our api in MStore Api plugin. but woo commerce api doesn't work. Do you have any config or plugin for blocking woo commerce api?
> 
> 

My developer is checking! I will update you as soon as possible

**Comment by minhtruong315** [comment]
Thank you @atlasdzedgo , let me know when it is resolved

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
