### ISSUE TITLE
FluxStore version 1.4.1: Not able to create reviews

### ISSUE THREAD

**Issue by paulagarciab** [inspireui/support#3567]
Fluxstore Listing APP version 1.4.1

**First Issue: User is not able to create reviews**

If you go to the file  /screens/detail/listing/review.dart

The line number 95 you will see that the code for send Review is commented, If I take the comments out, It is not working. 

Then this is causing that users are not able to create reviews on the latest version. 

*Second Issue: Login was not working.*
After trying to login through the app I was getting the error flutter_user controller doesnt exists. 
I check why the login was not working and if you check the file services/woo_commerce.dart
on the line 514, 
final http.Response response = await http.get(
          "$url/api/flutter_user/get_currentuserinfo/?cookie=$cookie&$isSecure");

It should be 

final http.Response response = await http.get(
          "$url/api/mstore_user/get_currentuserinfo/?cookie=$cookie&$isSecure");

after In change this now login is working, but obviously your other users are impacted.

**Comment by philipvu30** [comment]
Hi,

Have you updated the ListApp Mobile Manager to the latest version?

**Comment by paulagarciab** [comment]
Yes I have updated, the issue is not the website, I am pointing the code and the code for writing reviews is commented, check the line that I told you and you will see that is commented if I take // the comments out then is not working. Can you please check the line of code that I am posting on my comment. Thanks.

Sent from my iPhone

On 3 Jun 2020, at 7:32 pm, philipvu30 <notifications@github.com> wrote:

﻿

Hi,

Have you updated the ListApp Mobile Manager to the latest version?

**Comment by paulagarciab** [comment]
Please find attached the screenshot of the review.dart file. I have for list app manager version 1.6.3

[cid:CB6AA0B5-7DDD-4907-B935-D9FFA43DC071-L0-001]
Sent from my iPhone

On 3 Jun 2020, at 7:39 pm, Paula Andrea Bejarano Garcia <it.paula@hotmail.com> wrote:

﻿ Yes I have updated, the issue is not the website, I am pointing the code and the code for writing reviews is commented, check the line that I told you and you will see that is commented if I take // the comments out then is not working. Can you please check the line of code that I am posting on my comment. Thanks.

Sent from my iPhone

On 3 Jun 2020, at 7:32 pm, philipvu30 <notifications@github.com> wrote:

﻿

Hi,

Have you updated the ListApp Mobile Manager to the latest version?

**Comment by philipvu30** [comment]
Hi,

I would like to give you my apologies. It was a mistake that we uploaded the wrong version of ListApp Mobile Manager plugin.
Please manually delete the plugin on your website and upload this [plugin](https://github.com/inspireui/support/files/4722691/listapp-mobile-manager.zip) instead. 

Thank you for your patience.

**Comment by paulagarciab** [comment]
Hi there,

I upload the ListApp Mobile manager that you provide, but please read the following because I am talking about another thing:

The issue is on the following https://codecanyon.net/item/fluxstore-listing-directory-woocommerce-app-by-flutter/25113066

Version 1.4.1 which is the latest version

File: Screens/detail/listing/review.dart

I am not talking about the list app mobile manager.

I attached the screenshot.

Thanks,

________________________________

**Comment by philipvu30** [comment]
Hi,

Please replace these files in lib/services. Thank you
[SERVICES.zip](https://github.com/inspireui/support/files/4727259/SERVICES.zip)

**Comment by paulagarciab** [comment]
Thanks now is looking better, but the file is not compiling as the models/review.dart doesnt have the variable status,

Can you send me a copy of the latest files for the entire project?

Thanks,

________________________________

**Comment by philipvu30** [comment]
Hi,

They are sent to your email.

**Comment by michaelbrinkworth** [comment]
https://www.facebook.com/groups/289288585778355/

**Comment by philipvu30** [comment]
Closed as no response in 2 days. 

If you are happy with our services/support, would you mind rating us on your [download page](https://codecanyon.net/downloads)?
We truly appreciate your help.

**Comment by paulagarciab** [comment]
Sorry it was a public holiday yesterday, I just checked my messages and the reviews are working now. Thank you so much for your support.

________________________________
