### ISSUE TITLE
Fluxlisting - questions

### ISSUE THREAD

**Issue by bobozd** [inspireui/support#3570]
1. how can I decrease empty space between two blocks causd by CARD LAYOUT
![Screenshot_20200603_130708](https://user-images.githubusercontent.com/28021993/83637230-8a803180-a5a7-11ea-9629-faf52f55b43d.jpg)

2. please give me code snippet for config.json to import blog section from my mylisting website

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by philipvu30** [comment]
Hi,

Please refer to this [comment](https://github.com/inspireui/support/issues/2004#issuecomment-585057625). You asked this question before.

**Comment by bobozd** [comment]
thanks.
3. how can I hide price tag from listings while it's being loaded to the app. Once it's loaded it disapear but while it loads there is a price tag  and my app do not need any costs.
![Screenshot_20200604_085216](https://user-images.githubusercontent.com/28021993/83724688-febae380-a640-11ea-9a84-76fd67f6e7c5.jpg)

**Comment by bobozd** [comment]
7. when I remove LOGO and SEARCH HEADER layouts from app homepage here is an issue with overlaping with BANNERIMAGE layout with mobile top bar. 
How can I add top padding betwwen top bar and pulze (bannerimage) item block ?
![Screenshot_20200604_095456_com inspireui fluxlisting](https://user-images.githubusercontent.com/28021993/83730802-e3a0a180-a649-11ea-85a0-25d1894bba40.jpg)

**Comment by bobozd** [comment]
8. how is possible with "layout": "bannerImage", to point not on category from backend website but to point to specific URL address? please explain how to modify this section of code:
       {
          "category": 18,
          "image": "https://scontent.fzag4-1.fna.fbcdn.net/v/t1.0-9/72483866_1000137320329472_6167717837583417344_o.jpg?_nc_cat=109&_nc_sid=dd9801&_nc_ohc=Rt846ZikCEkAX-Fo64W&_nc_ht=scontent.fzag4-1.fna&oh=33d9203f4530b6d67db57a25c4b29e34&oe=5EFD2B66",
          "padding": 20.0
        },

**Comment by philipvu30** [comment]
Hi,

As we are in a busy time, we will no longer support customization requests/questions. Please open the ticket only when a bug/error occurs.

We really appreciate it if you could do that.

**Comment by bobozd** [comment]
what a support !!!  I'll probably request refund. Please answer on number 7. at least as this is a bug.

**Comment by philipvu30** [comment]
Hi,

Our apologies that the support service did not meet your expectation. But please understand that all of us are going through a hard time. 
For these small things like widget customization, please use Inspector tool to determine and modify it.
Again, we are sorry for not having enough time to support you as we did before. If our app does not meet your expectation or you feel us unreasonable/unhelpful, we are happy to refund you.

Thank you for your understanding.

PS: To answer your question 7. Please head to lib/screens/home.dart and wrap this Widget in SafeArea.

![image](https://user-images.githubusercontent.com/54442328/84147476-aa23c800-aa87-11ea-8104-ad835520d496.png)

**Comment by bobozd** [comment]
same top padding problem with BLOG TITLE on blog section. It overlays with top bar.
![Screenshot_20200609_192923_com inspireui fluxlisting](https://user-images.githubusercontent.com/28021993/84197297-faa81f00-aaa1-11ea-9b6f-5644f72ed477.jpg)

**Comment by bobozd** [comment]
BUG
spinning cricle while taping on locaion icon for loading map
video: https://drive.google.com/file/d/15VZSkBVeJ8xexan8YC7at2S2lFIeQgbU/view?usp=sharing

also,
previous question is not answered yet !

**Comment by bobozd** [comment]
U would like to get support. Please answer !!!
