### ISSUE TITLE
How to add subdivision on address (in state_xx.jason )

### ISSUE THREAD

**Issue by ravindam** [inspireui/support#3571]
Hi
i have two questions
FluxStore-1.7.4
Flutter 
Testing Device - Mi Redmi 8

(01) How to add subdivision on address (in state_xx.jason )
i want select Country and State , City

![Untitled](https://user-images.githubusercontent.com/63419889/83629815-65e08580-a5b8-11ea-8ef9-3fff39db5b47.jpg)
![Screenshot_2020-06-03-16-34-37-877_com inspireui fluxstore](https://user-images.githubusercontent.com/63419889/83629834-6c6efd00-a5b8-11ea-8eed-9859e41afa18.jpg)

(02) Home screen category ("layout": "category") 
want to show custom name in icon 
and url doesn't work (click the  icon and navigate to producket) I wont to loge .html page 

![Screenshot_2020-06-03-17-02-05-709_com inspireui fluxstore](https://user-images.githubusercontent.com/63419889/83632114-4f3c2d80-a5bc-11ea-9bc1-d290bdb2163f.jpg)
![Untitled2](https://user-images.githubusercontent.com/63419889/83632121-5400e180-a5bc-11ea-8a3a-610ecca5bfcb.jpg)

**Comment by minhtruong315** [comment]
Hi @ravindam Fluxstore only supports to choose country and state for now. So in state_xx.json only has code and name, doesn't have subdivision.

**Comment by minhtruong315** [comment]
You can't add url on config like this
```
 {
          "name": "Recent Collections",
          "url": "http://lakmuthu.dyndns.org/image/service.html",
          "image": "assets/icons/categories/sc_100.png",
          "colors": [
            "#53A2CC"
          ],
          "originalColor": true
        }
```
category layout only shows icon from asset or url. when click the category, it shows product page by category. You can't add url to show a website.
