### ISSUE TITLE
Logging issues

### ISSUE THREAD

**Issue by goelrajiv75** [inspireui/support#3572]
when trying to login through google or facebook it throws exeptions
When Logging through google this happens

![1](https://user-images.githubusercontent.com/65877361/83643013-2c664500-a5cd-11ea-9788-b954adf4f293.png)

When From Facebook Screen Shows This

![facebook](https://user-images.githubusercontent.com/65877361/83643057-39833400-a5cd-11ea-9811-cffd51166e26.png)

When signup through email on signup it keeps loading.......i have press back button
When login through mail it keeps loading...... this is screenshot

![Login](https://user-images.githubusercontent.com/65877361/83643283-7818ee80-a5cd-11ea-9592-a898f568a044.png)

After Adding product to cart and press checkout button This screen comes
![checkout](https://user-images.githubusercontent.com/65877361/83643356-8c5ceb80-a5cd-11ea-9fe2-4de7495b9bf8.png)

Fluxstore Multivendor 1.7.4
Flutter Version 1.17.2
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

this is my purchase proof
[58966544-fluxstore-multi-vendor-flutter-ecommerce-full-app-license.pdf](https://github.com/inspireui/support/files/4723668/58966544-fluxstore-multi-vendor-flutter-ecommerce-full-app-license.pdf)

here is my lib/common/config folder
[config.zip](https://github.com/inspireui/support/files/4723674/config.zip)

Sometimes Home screen shows products and sometime it doesnt

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as it could not be verified proof of purchase on step 2, please create the new ticket by including the purchased License info - thank you for your time.

**Comment by goelrajiv75** [comment]
I dont know about this ticket system.i am a lay man with little bit
knowledge. I am having few issues as follows
1. When logging in, it stucks and keep loading, i have to press back and
its logged in. But customwrs will not understand it.
2. I sign us as vender. On first login i am having all options of vendor,
but when i logout and login again, vendor options gone.
3. Everytime i open the app i have to login, it doesnt remember my
credentials so customwr dont have to login again and again.
Thanks and regards

**Comment by minhcasi** [comment]
@goelrajiv75 - i've got your License to verify via email and reopen the ticket. 

Our team will back on Monday and assist with the checking - thank you for time :)

**Comment by philipvu30** [comment]
Hi,

Sorry for the delayed response as we rarely work on the weekends. 
1. Google login: this error is related to FireBase is not correctly/fully configured. Please refer to this [doc](https://docs.inspireui.com/fluxstore/sign-in/#1-google-sign-in) to set it up.
2. Facebook login: same as the reason above. Please refer to this [doc](https://docs.inspireui.com/fluxstore/sign-in/#4-facebook-sign-in) to set it up.

For other issues, we'll need more time to check. 
Thank you for your understanding.

**Comment by philipvu30** [comment]
Hi,

I have tested all of the issues you mentioned on our latest FluxStore MV and MStoreAPI plugin version but none of them occurred on our Demo app. Would you mind updating your app to the latest?

Thank you.

**Comment by goelrajiv75** [comment]
Hello, 
My fluxstore multivendor is working fine now. Only 2 issues
1. In create product while adding image when i click on gallery it opens camera.
2. When i click on post product it keeps on loading.

**Comment by goelrajiv75** [comment]
![postproduct](https://user-images.githubusercontent.com/65877361/84504021-df732480-acd8-11ea-9d58-7eaf24cb7312.jpg)

**Comment by philipvu30** [comment]
Hi,

Sorry for the delayed response.
1. Change this camera to gallery. You can find it here lib/vendor/products/widgets/select_image.dart
![image](https://user-images.githubusercontent.com/54442328/84642249-636e1c00-af26-11ea-81fc-2b4ed38598ee.png)

2. Don't leave the sale price empty. Set it to 0 if you don't have sale price.

**Comment by goelrajiv75** [comment]
Thanks foor support. Everything working fine now.

**Comment by minhcasi** [comment]
@goelrajiv75 - thank you for the quick response - we hope you have enjoyed the product so far. Let us know if you have any further questions.

If you are happy with our services/support, would you mind rating us on your download page? We truly appreciate your help.
