### ISSUE TITLE
Unable to login using Mail, Google, Facebook, SMS (FluxStore WooCommerce)

### ISSUE THREAD

**Issue by netuseruk** [inspireui/support#3575]
Unable to login using Mail, Google, Facebook, SMS Its giving following error

For signup using mail id & password
![sign up](https://user-images.githubusercontent.com/66378474/83662996-e49fe780-a5e5-11ea-9f36-e7e98f7bc0a8.PNG)

For login using Google account
![Google](https://user-images.githubusercontent.com/66378474/83663094-026d4c80-a5e6-11ea-8d8e-0ff3b5c812ae.PNG)

For login using Facebook
![facebook](https://user-images.githubusercontent.com/66378474/83663176-20d34800-a5e6-11ea-82d8-4aba698c97fa.PNG)

For login using SMS
![sms](https://user-images.githubusercontent.com/66378474/83663219-30eb2780-a5e6-11ea-84ac-df2c0f643cba.PNG)

I purchased yesterday . 
I am using windows system & currently looking for android app.

Please help me .

**Comment by stickypages** [comment]
You didn't setup your REST API properly for one. And as your errors state, Firebase isn't authorized with your app. Re authorize, download the files, do a 'flutter clean', and start over going through the setup tutorials.

**Comment by minhcasi** [comment]
@netuseruk - please try to active the mstore-api from the Wordpress side as well 

@stickypages - thank you for the comment 🎖

**Comment by netuseruk** [comment]
@stickypages I did tried but getting same issue .

@minhcasi I purchased FluxStore 2nd June , when I tried to activate MStore API it was throwing bellow error . 
![API Error](https://user-images.githubusercontent.com/66378474/83712270-fbc0f280-a642-11ea-87c0-321207dfc012.PNG)
 So I contacted you guys via mail , and next day again I tried and this time code accepted .
![API Working](https://user-images.githubusercontent.com/66378474/83712389-4c385000-a643-11ea-8bc9-65dcca4bd702.PNG)


Note : MStore API wordpress plugin which I received from package that was asking me to Update So I did updated . 
Current Version : 2.5.0

Waiting for your valuable solution

**Comment by netuseruk** [comment]
@minhcasi I checked using guest checkout , and it is working . 
except registration & login , most of the features working smoothly . 
Also fluxbuilder working ..
I shared common+config folder in google form . 

From first day of purchase I am facing issues , very upset now. 
Please help me ASAP.

**Comment by minhcasi** [comment]
@minhtruong315 - pls check the validate code issue on mstore-api - thank you!

**Comment by minhcasi** [comment]
@netuseruk - try to follow up this guide carefully to resolve the SHA1 issue and Google login - https://medium.com/@inspireui/setup-google-login-for-flutter-apps-fedc58a490b8

Also, refer to this solution https://github.com/inspireui/support/issues/3151

**Comment by netuseruk** [comment]
@minhcasi Ok I can re configuring again . I will let you know .

**Comment by netuseruk** [comment]
@minhcasi I have successfully reconfigured Firebase , now Google , Mail , Facebook login working fine but only SMS not working . see below screenshot 
![smsm](https://user-images.githubusercontent.com/66378474/83745745-a3f2ad80-a67b-11ea-849d-64582708bb0e.PNG)

Steps Followed :
1.Firebase Enabled Authentication
![image](https://user-images.githubusercontent.com/66378474/83745879-ddc3b400-a67b-11ea-987e-cab51b77153a.png)

2. Added android app to firebase & Pasted google-services.json to android --> app

![image](https://user-images.githubusercontent.com/66378474/83746246-722e1680-a67c-11ea-8536-4678d0ff8378.png)

3. From terminal 
flutter clean
flutter run

Mail, FB, Google all working but sms no luck .

followed this link 
https://docs.inspireui.com/fluxstore/sign-in/#3-sms-sign-in


Please guide me . Urgent .

**Comment by stickypages** [comment]
To be honest, I wouldn't even use SMS login. It's nice, but the real benefit is getting there email address. Even though that's not a FIX, it's a solution, and in my opinion, better.

**Comment by minhcasi** [comment]
@netuseruk - could i check if you have config the "OAuth consent screen" same as the guide?

**Comment by netuseruk** [comment]
@minhcasi thanks for your support , Issue has been resolved . 

You can close the Ticket .

**Comment by minhcasi** [comment]
We're glad that it help, please give us some feedback/rating to this page https://codecanyon.net/downloads  if the product is helpful for your business, we are working hard to update more awesome and powerful features on next coming version release. Let us know if you have any feedback. Thank you very much 😊
