### ISSUE TITLE
I have Many problems (Urgent)

### ISSUE THREAD

**Issue by careerun** [inspireui/support#3576]
Dear Team

I have many problems such

**First the app dose not build (img 1)**
https://careerun.com/wp-content/uploads/2020/06/android-studio.png

**Second fluxbuilder has many problem (img 2)**
https://careerun.com/wp-content/uploads/2020/06/fluxbuilder.png

**third how to make the app RTL Style (img 3)**
https://careerun.com/wp-content/uploads/2020/06/third-img.png

best regards

**Comment by stickypages** [comment]
I'm not the developer, but it looks like you haven't set it up properly. Spend some more time setting up your data. And going through the setup tutorials.

**Comment by minhcasi** [comment]
@dttrung26 - please help to investigate

**Comment by dttrung26** [comment]
Hi @careerun ,

there are still some warnings on your Dart analysis, please try to fix them. If you're not sure how to do it, please begin the installation again from scratch by following our tutorial video guides: [Flutter Basic Installation](https://www.youtube.com/watch?v=3dv_8UerNpQ), [FluxNews Installation](https://www.youtube.com/watch?v=xX4c5MfzH9o)

Let me know if you still have any questions.

**Comment by careerun** [comment]
Hi @dttrung26  give me this error


Compiler message:
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0.6.0+2/lib/src/dialogs.dart:272:17: Error: No named parameter with the name 'onRatingChanged'.





                onRatingChanged: (rating) {
                ^^^^^^^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/smooth_star_rating-1.1.1/lib/smooth_star_rating.dart:24:3: Context: Found this candidate, but the arguments don't match.
  SmoothStarRating({
  ^^^^^^^^^^^^^^^^

Target kernel_snapshot failed: Exception: Errors during snapshot creation: null

build failed.












FAILURE: Build failed with an exception.

* Where:
Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 882

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command 'C:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 10s





Running Gradle task 'assembleRelease'...                          192.0s (!)
Gradle task assembleRelease failed with exit code 1
Process finished with exit code 1

**Comment by careerun** [comment]
give me this error

![sdfgdfgdg](https://user-images.githubusercontent.com/66385783/84196518-9e90cb00-aaa0-11ea-83fb-0dfc664ee88d.png)

**Comment by dttrung26** [comment]
Hi @careerun, 
kindly contact me via skype: dttrung.ityu. I'll support you via teamviewer. 
Best!

**Comment by stickypages** [comment]
We should open up a slack channel for support. Feel like that could be
useful.


All the best,


*Justin Giesbrecht* | justin@stickypages.ca
250-869-5952 | www.stickypages.ca

**Comment by careerun** [comment]
> Hi @careerun,
> kindly contact me via skype: dttrung.ityu. I'll support you via teamviewer.
> Best!

I can't find you please give me the email

**Comment by minhcasi** [comment]
We wanted to thank you for your patience during this busy time. We currently have reduced staff and a significantly higher volume of inquiries. We’re working as hard as we can to get to your request as soon as possible.

We sincerely apologize for the delay and hope you’re staying safe.

**Comment by careerun** [comment]
nothing happen please we want to refund our money other wise we will contact https://codecanyon.net/ and rate the app with one star and give negative feedback

**Comment by dttrung26** [comment]
Hi @careerun ,
could you kindly check skype please? I've been contacting you in the last 2 days.
Nice day!

**Comment by minhcasi** [comment]
Hi @careerun, 

Please go to source/android/gradle/wrapper/ folder, open gradle-wrapper.properties file and change distributionUrl as below:
distributionUrl=https://services.gradle.org/distributions/gradle-5.6.2-all.zip

then run again (you can turn of the Android Studio, reopen it and run again)

Thank you

**Comment by dttrung26** [comment]
Supported via Skype!
