### ISSUE TITLE
fluxnews error

### ISSUE THREAD

**Issue by bangbiggy** [inspireui/support#3578]
Hello, am facing some errors when i try to run Flux News app. please help.
![Fluxnews error](https://user-images.githubusercontent.com/60167322/83692030-e2488800-a5fb-11ea-9883-ad6d0b7670f5.png)

**PROOF OF PURCHASE**
![purchase proof 1](https://user-images.githubusercontent.com/60167322/83692496-cee9ec80-a5fc-11ea-8a94-fba684a29647.png)
![purchase proof 2](https://user-images.githubusercontent.com/60167322/83692516-d5786400-a5fc-11ea-8e9f-3407e1910e53.png)
I have hide part of the Purchase code because i thing is should be a secret. If Needed let me know so i cans send it too.
I need this help as soon as you can help me.
Thanks.

**Comment by minhcasi** [comment]
@bangbiggy - please try to open the `pubspec.yaml` file and update the value ` rate_my_app: 0.6.1+3`

**Comment by bangbiggy** [comment]
Thanks it works just fine now.
