### ISSUE TITLE
[ListPro] Reviews not working

### ISSUE THREAD

**Issue by jaksatomovic** [inspireui/support#358]
Required Info (please complete the following information):

Product: [ListPro]
Your Purchased Code: [e52cfbdd-f79e-4946-ae15-0daadc94fdfa]
(we may not reply if you are not our customer)

**Describe the bug**
Reviews not working...unable to commit and send review of listing from mobile app.

**Comment by thangvo9x** [comment]
Hi. can you send me your AppConfig for checking, plz?

**Comment by jaksatomovic** [comment]
{
  "Website": {
    "url": "http://ekorcula.eu",
    "consumerKey": "ck_23d3372ffecbe925f07872c5261ddd78d1ea00d3",
    "consumerSecret": "cs_0b0ff89a8f8a231fe7351c1926fb8051095abf14"
  },
  "Theme": "restaurant",
  "MainColor": {
    "tabbarTint": "rgb(27, 229, 141)",
    "tabbarColor": "#D5D8DE",
    "mainColorTheme": "rgb(27, 229, 141)",
    "tabbar": "#FFF"
  }
}

**Comment by thangvo9x** [comment]
Hi. CAn you send me your admin info, plz ? thang@inspireui.com with subject id is 358. Thanks ASAP

**Comment by thangvo9x** [comment]
Your review is working fine again. 
<img width="1245" alt="review" src="https://user-images.githubusercontent.com/23457178/53720926-7c1f0380-3e94-11e9-9ab5-424700a92c8d.png">

**Comment by jaksatomovic** [comment]
Hi thx again...but one quick question for the end....after you submit review it is saved as comment but not review so it is not visible on the website under reviews

**Comment by thangvo9x** [comment]
Hi. you must approve it to display => Avoid spam.

**Comment by jaksatomovic** [comment]
yes i have approved it and it is still not visible as review..... you have separate category called Reviews for listing reviews ( i can see it on my website admin panel) this is just comment on post which is not visible

**Comment by jaksatomovic** [comment]
also why cant i see any icons in ios simulator?
