### ISSUE TITLE
Store Section No Showing

### ISSUE THREAD

**Issue by aldosoraluz** [inspireui/support#3580]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

hi
I use the WCFM plugin and the stores does not show in the app .
any souloution please ?

![77297218-30f5af80-6ca6-11ea-8b07-064c31694b5b](https://user-images.githubusercontent.com/3812304/83701564-05614080-a5d8-11ea-97cc-a795e7aec3bd.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as it could not be verified proof of purchase on step 2, please create the new ticket by including the purchased License info 

Please note - we have removed the screenshot proof purchase to protect your private data.

Thank you for your time.

**Comment by JoshuaObateru** [comment]
my issue was just closed before I could finish uploading my proof of purchase to the http://verify.inspireui.com link

**Comment by JoshuaObateru** [comment]
issue 3590

**Comment by JoshuaObateru** [comment]
Issue [3590](https://github.com/inspireui/support/issues/3590)

**Comment by minhcasi** [comment]
@minhtruong315 - pls help to check this issue

**Comment by minhtruong315** [comment]
Hi @aldosoraluz I checked your config. it's working well
<img width="444" alt="Screen Shot 2020-06-10 at 10 50 48 AM" src="https://user-images.githubusercontent.com/10402500/84225039-586f5200-ab08-11ea-87c1-1bf765fdfae4.png">
what is Fluxstore version you're using?

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
