### ISSUE TITLE
Identifying User with their Roles

### ISSUE THREAD

**Issue by znchung** [inspireui/support#3581]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: I want to show a different experience based on the logged in user's role, how can I get the 'role' data? As far as I know, it is not returned as part of the endpoint.
+ Product & version: FluxStore Pro
+ Flutter (or React Native) version:  Flutter 1.17.1
+ Testing Device/Simulator: Simulator
+ Screenshot issues (drag the file to attach here): 
<img width="1317" alt="Screen Shot 2020-06-04 at 9 47 24 AM" src="https://user-images.githubusercontent.com/25826971/83705984-ee0e6b80-a648-11ea-9ade-1f73bd0e859c.png">

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as it could not be verified proof of purchase on step 2, please create the new ticket by including the purchased License info - thank you for your time.

**Comment by 1hourlife** [comment]
Hi this ticket is linked to https://github.com/inspireui/support/issues/3273. Can you reopen this ticket and help answer please.

**Comment by 1hourlife** [comment]
@minhcasi I meant reopen this ticket 3581. Not the 3273 (that was answered). We need answers for 3581!

**Comment by philipvu30** [comment]
Hi @1hourlife ,

May I ask what is your current version of Mstore Api plugin? Because I can see the response for that endpoint returns "role" attribute in our latest version.

**Comment by 1hourlife** [comment]
These are the plugins we have installed.  We dont have MStore Api plugin

Better REST API Featured Images v1.2.1
JSON API	v 2.0.0
ListApp Mobile Manager	v1.6.3
WP REST API - Pure Taxonomies v 1.0
WP REST API Controller v 2.0.3

**Comment by philipvu30** [comment]
Hi @1hourlife,

Are you using FluxStore Pro or FluxListing? I am confused because the author-znchung said he used FluxStore Pro and you are using ListApp Mobile Manager, which is for FluxListing only.

Are you and znchung coming from the same place or the same person?

**Comment by znchung** [comment]
@philipvu30  I am one of the developers for @1hourlife. 

Sorry that was my fault! It is FluxListing. I got confused myself.

**Comment by philipvu30** [comment]
Hi @znchung 

If you use FluxListing, the rest API should be wp-json/api/flutter_user/get_currentuserinfo. It should return the role as the response shows in the image below.

![image](https://user-images.githubusercontent.com/54442328/84462627-bc755000-ac99-11ea-8b1a-6fffe2212202.png)

**Comment by znchung** [comment]
@philipvu30 Got it! Thank you! :)

**Comment by philipvu30** [comment]
Closed as no response in 2 days. 

If you are happy with our services/support, would you mind rating us on your [download page](https://codecanyon.net/downloads)?
We truly appreciate your help.
