### ISSUE TITLE
Update Profile not working

### ISSUE THREAD

**Issue by mpnihad** [inspireui/support#3582]
HI,
I am having trouble with this Api
http://purpleland.hostwiz.in/index.php/rest/V1/mstore/customers/me/changeEmail
Paremetes:
 {user_id: 15, display_name: nihad mp, user_email: mpnihad.sciwiz@gmail.com, user_nicename: , user_url: }

token: 7a8wc5xf9mr23q1aeeurmjd1v51gb95n
The response I get is
 {
    "message": "Request does not match any route.",
    "trace": null
}
Can you please help me out 
proof of purchase
![Screenshot (21)](https://user-images.githubusercontent.com/59775230/83716249-f668a580-a64c-11ea-895e-a83f39f162b8.png)

the  Purchase code is : edfd7037-d6b9-4f95-8879-0d8ecffbe3fe
[config.zip](https://github.com/inspireui/support/files/4727568/config.zip)
![Screenshot_20200604-100549](https://user-images.githubusercontent.com/59775230/83715808-e4d2ce00-a64b-11ea-9103-3700c2566658.jpg)

**Comment by minhcasi** [comment]
@mpnihad - could i know if you have active the mstore-api from the wordpress side - thank you!

**Comment by mpnihad** [comment]
We are working on Magento.Not on WordPress. Already activated the mstore
module.

**Comment by minhcasi** [comment]
@minhtruong315 - pls help to check this feature issue on Magento - thank you!

**Comment by minhtruong315** [comment]
Hi @mpnihad give me your email. I will  send me the latest MStore extension.
Thanks

**Comment by mpnihad** [comment]
Email is mpnihad.sciwiz@gmail.com

**Comment by minhtruong315** [comment]
Hi @mpnihad I sent you the latest MStore extension, please reinstall it on your website and try again.
Thanks

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!

**Comment by amjadalfawal** [comment]
i have the same issue what is the solve ?
