### ISSUE TITLE
Need Support for Price Update in product listtile Layout!

### ISSUE THREAD

**Issue by govindh163** [inspireui/support#3583]
Product Details :  Fluxstore Pro 1.7.3 (OpenCart Framework)

Step 1: I have added the Price Updation Feature in Product description Screen,(i.e) When User changes the Option in dropdown the price gets updated!
              It is working fine in Product description screen.
If  you replace this three files with your respective file in lib folder
[updateprice.zip](https://github.com/inspireui/support/files/4727837/updateprice.zip)
         
 Then I add this feature to Product Listtile layout page,When I select the option from dropdown 
  the price is being changed for all other products in listlile layout. 
https://gist.github.com/govindh163/92e8faa64d8851cb1fc08eb0bcc701f1
This is my product_list_tile.dart file
 I Just need to fix it as it must change price for selected product
@minhcasi 

  Step 2 (require): submitted proof of purchasing the license on http://verify.inspireui.com

**Comment by govindh163** [comment]
> Product Details : Fluxstore Pro 1.7.3 (OpenCart Framework)
> 
> Step 1: I have added the Price Updation Feature in Product description Screen,(i.e) When User changes the Option in dropdown the price gets updated!
> It is working fine in Product description screen.
> [updateprice.zip](https://github.com/inspireui/support/files/4727837/updateprice.zip)
> 
> If you replace this three files with your respective file in lib folder
> 
> Then I add this feature to Product Listtile layout page,When I select the option from dropdown
> the price is being changed for all other products in listlile layout.
> https://gist.github.com/govindh163/92e8faa64d8851cb1fc08eb0bcc701f1
> This is my product_list_tile.dart file
> I Just need to fix it as it must change price for selected product
> @minhcasi

**Comment by minhcasi** [comment]
@govindh163 - thank you for your feedback, sorry we could not help with this customization due to limitations of the support scope (we could only support for the issues existing from the app, any customization code will not be supported) - please try your best to customize the app 😊
