### ISSUE TITLE
Language Support

### ISSUE THREAD

**Issue by mpnihad** [inspireui/support#3584]
#3582 previous ticket

currently, there are only 6 language 
needed  5 more language Philippines, Hindi, Indonesia, Malay, Thai
proof of purchase
![Screenshot (21)](https://user-images.githubusercontent.com/59775230/83724986-cd511080-a65e-11ea-8f5d-3d593cf0a2f9.png)

**Comment by philipvu30** [comment]
Hi,

Would you mind translating all of the terms in lib/l10n/intl_en.arb to your preferred languages? 
After that, please send them to our email: support@inspireui.com or my email: toan@inspireui.com. We will add them in the next release.

Thanks

**Comment by minhcasi** [comment]
Duplicate of #3582
