### ISSUE TITLE
How to make upgrade from a version to another 

### ISSUE THREAD

**Issue by avvvar** [inspireui/support#3585]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 
Hello , could you provide a documentation of how to upgrade the app from a release to another 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@avvvar - pls help to check this guide
https://github.com/inspireui/support/wiki/Guide-to-using-git-to-work-repo-Fluxstore-pro
https://www.youtube.com/watch?v=SWLHKx-xzn0

**Comment by minhcasi** [comment]
Let us know if you have any further questions, thank you!
