### ISSUE TITLE
error archiving

### ISSUE THREAD

**Issue by miskayapp** [inspireui/support#3587]
version 1.7.5

error code 

Standalone embedder initialization failed: Error determining current directory: Operation not permitted

Command PhaseScriptExecution failed with a nonzero exit code
![Screen Shot 2020-06-04 at 9 35 18 AM](https://user-images.githubusercontent.com/64660378/83734368-cb7b5300-a646-11ea-95de-c54bb487e2ff.png)

**Comment by minhcasi** [comment]
@miskayapp - before running build on XCode did you run this script `flutter build ios` 

Ref: https://flutter.dev/docs/deployment/ios

**Comment by miskayapp** [comment]
Yes, and it was successful on the terminal

**Comment by minhcasi** [comment]
@miskayapp - please help to check if this setting is updated as 'new build system'

<img width="676" alt="Screen Shot 2020-06-05 at 14 04 23" src="https://user-images.githubusercontent.com/1459805/83846867-79652b00-a735-11ea-8ac7-673869fbee32.png">

And make sure to use the lastest XCode to compatible with Fluter 1.17

**Comment by miskayapp** [comment]
yes, and the error im getting "

Standalone embedder initialization failed: Error determining current
directory: Operation not permitted


Command PhaseScriptExecution failed with a nonzero exit code




*Showing All Errors Only*

Standalone embedder initialization failed: Error determining current
directory: Operation not permitted


"

**Comment by miskayapp** [comment]
is this the cause?

**Comment by minhcasi** [comment]
@miskayapp - pls try to add my account to your TestFlight minhcasi@gmail.com - and send your latest source again, we will give a try to upload to your TestFlight -thanks

**Comment by miskayapp** [comment]
I don’t understand this, you can only add testers to TestFlight, is that
what you mean?

**Comment by miskayapp** [comment]
Ok, i just added you, you should get an invite.

**Comment by miskayapp** [comment]
I have added you and shared the source via google drive to your mail address

**Comment by miskayapp** [comment]
hello, any update

**Comment by minhcasi** [comment]
@miskayapp - we will have a check and let you know today - thanks

**Comment by miskayapp** [comment]
Good evening, still no update.

**Comment by minhcasi** [comment]
We will help to check and let you know today - thanks

**Comment by miskayapp** [comment]
Its been a week now since, you asked for details. Please try to understand
that people are pressuring me for this. Please just help me out and upload
to the test flight.

**Comment by miskayapp** [comment]
Hello, please its very urgent.

**Comment by minhcasi** [comment]
@miskayapp - we're checking and get back you soon - thank you!

**Comment by minhcasi** [comment]
@miskayapp - you could try to override this file https://drive.google.com/file/d/1VlYAGUY89buU6h2v9cphuOlIdldxcTNf/view?usp=sharing

Also, make sure 2 settings:
+ the workspace setting should be new build system: https://tppr.me/j6Pq8
+ XCode version should be 11.5

**Comment by miskayapp** [comment]
can  you just help me send to testflight, i have tried all these, same
error, please.

**Comment by minhcasi** [comment]
@miskayapp - pls try to add my account to your App Delivery Manager so that I could upload on your behalf - my MacBook is having an issue today and I'm preparing - I could only help to check on Monday - thank you

**Comment by miskayapp** [comment]
I added you as admin before, i have deleted that and send an invite as app
manager. You said you will help upload last week Friday and this is 1 week
after, sigh. Please please, if you could help befoee Monday

**Comment by miskayapp** [comment]
good morning, just a reminder about helping upload the app, please, i have
sent an invite.

**Comment by miskayapp** [comment]
Whats the update, its been two weeks. And we have been trying to upload a
single app for a month now, this is not fair.

**Comment by miskayapp** [comment]
whats the update, you still havent accepted my invite, its been twow weeks
and have shared and sent invitem, no follow up or words from you.

**Comment by minhcasi** [comment]
@minhcasi - i've still had an issue with the signing on your app - https://tppr.me/OmRjx - we would help with the team viewer on your PC on tomorrow - let us know when you are available (pls send the request to email support@inspireui.com) - thank you!

**Comment by miskayapp** [comment]
I have given you access to the app manager, or do you need admin level? I
dont have a mac with me anymore.

**Comment by miskayapp** [comment]
the team, select the account i added or can send my apple developer login
in private anywhere. can we chat on WhatsApp, please i don't want this to
drag to next week, youre 7hours ahead of me and its hard to keep track, we
cant move forward communicating just once a day. i know youre busy but this
is a month and 2 weeks now trying to upload an app, i have lost my MacBook
in the process. i will send my login details to   support@inspireui.com ,
only problem is the otp.

**Comment by minhcasi** [comment]
@miskayapp - i got your account, let move this conversation to the email loop - thanks

**Comment by miskayapp** [comment]
Email loop??
