### ISSUE TITLE
wcfm store list not showing

### ISSUE THREAD

**Issue by investisocial** [inspireui/support#3588]
Hello,
i've bought your app and i'm trying to configure it. I'm working with android studio and when i go into the categories and i click on store i cannot see store list. I don't understand where is the issue.
If i check this link, i can look that API correctly works:
https://www.spesaservita.it/wp-json/wc/v2/flutter/wcfm-stores?per_page=10&page=1&consumer_key=ck_ff843d02cc361a72f795da34b2a1948e0d062594&consumer_secret=cs_2d7193537c8db0812247ff1952baa3306bc5c656
Can you help me please?
Thank you.
Regards
Carlo
![Store_Issue](https://user-images.githubusercontent.com/57216890/83749201-9fba9600-a663-11ea-93cb-6de89515a0fe.jpg)

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as it could not be verified proof of purchase on step 2, please create the new ticket by including the purchased License info - thank you for your time.

**Comment by investisocial** [comment]
Hi, please see the attached file, it's my license.
Waiting for support, thank you.
Regards
Carlo
[59095596-fluxstore-multi-vendor-flutter-ecommerce-full-app-license.pdf](https://github.com/inspireui/support/files/4730208/59095596-fluxstore-multi-vendor-flutter-ecommerce-full-app-license.pdf)
