### ISSUE TITLE
[ListPro] Login not working properly

### ISSUE THREAD

**Issue by jaksatomovic** [inspireui/support#359]
Required Info (please complete the following information):

Product: [ListPro]
Your Purchased Code: [e52cfbdd-f79e-4946-ae15-0daadc94fdfa]
(we may not reply if you are not our customer)

**Describe the bug**
So after I logout with random user and login again with another account all info about previous account remains, also sometimes i need to login twice and also i dont have avatar picture it is empty

**Comment by thangvo9x** [comment]
Hi. We've checked it. This is a bug from our app. We're fixing and release to fix this issue. THANKS

**Comment by jaksatomovic** [comment]
Ok When can i expect to be fixed and released?
