### ISSUE TITLE
products and categories not showing on built fluxstore woocommerce apk 

### ISSUE THREAD

**Issue by JoshuaObateru** [inspireui/support#3590]
+ Detail Issues: During development, when testing the app with flutter run, sometimes some products show on the homepage and sometimes they don't and I put the appropriate categories and the appropriate details as stated in the documentation. Now that I have built the apk for testing, after a fresh install if I close and open the app again, the categories and producs stop showing completely

+ Product & version: Fluxstore version 1.7.4 using it with a wordpress site that has woocommerce installed

+ Flutter version: Flutter version 1.17.2 stable channel, dart 2.8.3

+ Testing Device/Simulator: Infinix HOT 6x with android version 8.1.0

+ Screenshots attached below

![Screenshot_20200604-133446](https://user-images.githubusercontent.com/44484002/83759552-9fbe9400-a66b-11ea-85c1-c2b960151195.png)
![Screenshot_20200604-133514](https://user-images.githubusercontent.com/44484002/83759561-a220ee00-a66b-11ea-89c0-aa2ac04db3bb.png)
![Screenshot_20200604-133525](https://user-images.githubusercontent.com/44484002/83759563-a2b98480-a66b-11ea-9488-1f0259eef1bd.png)

I also get this logs on the terminal some are okay but some point out issues

![Screenshot (31)](https://user-images.githubusercontent.com/44484002/83759799-03e15800-a66c-11ea-8adf-c60e95daa7d6.png)

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as it could not be verified proof of purchase on step 2, please create the new ticket by including the purchased License info - thank you for your time.
