### ISSUE TITLE
Cannot register as a customer only a vendor

### ISSUE THREAD

**Issue by olorunfemi007** [inspireui/support#3591]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
Hello,
1. I can't register as a customer only as a vendor.
2. isVender variable in the settings page doesn't work so add product page is hidden.
I have a screen recording demonstrating  these issues. Below are the links for the issues respectively.
https://www.dropbox.com/s/2184jnuvdzkkfyc/store_rec1.mov?dl=0
https://www.dropbox.com/s/vvvc1n65tc5adim/store_rec2.mov?dl=0

Thank you for your speedy resolution.

**Comment by philipvu30** [comment]
Hi,

Please submit your information via our verification [form](http://verify.inspireui.com/) for further assistance. After I received your information, I'll help to solve your issues. Thank you.

**Comment by olorunfemi007** [comment]
Hello i already filled the form and await your response. 
Regards.

**Comment by olorunfemi007** [comment]
Hello, Pls this request is still pending, Kindly help resolve.

**Comment by philipvu30** [comment]
Hi @olorunfemi007 ,

May I know what is your current FluxStore MV version and Mstore API version? Because the error I got is different than the one in your videos.

**Comment by olorunfemi007** [comment]
Mstore Api version is Version 2.4.6 
I don't know how to get fluxstore mv version

**Comment by philipvu30** [comment]
Hi,

Our MStore API is already at version 2.5.4. Please update it and see if your issue is solved.

Thank you.

**Comment by olorunfemi007** [comment]
I already updated my MStore API version but problem persist.
Thanks.

**Comment by philipvu30** [comment]
Hi,

I tested your config with our latest version. It seems everything is fine. 
Our latest version is 1.7.5, it's better to pull the latest one via GitLab if you have access to our Repository.

**Comment by philipvu30** [comment]
Closed as no response in 2 days.

**Comment by philipvu30** [comment]
@olorunfemi007 

An invitation email will be sent to your email soon.

**Comment by minhcasi** [comment]
sent

**Comment by olorunfemi007** [comment]
I just created a new gitlab account with @olorunfemi007 Kindly send the invitation again as I didn’t see it. Thanks

**Comment by olorunfemi007** [comment]
Thank you. I’m able to access it. Appreciate your help
