### ISSUE TITLE
don not  show any products  fluxstore 1.7.4 woocommerce

### ISSUE THREAD

**Issue by almaredt** [inspireui/support#3592]
Hello
products not showing in categories , when I add new product then app show new product but old ones not showing. 

Fluxstore 1.7.4 woocommerce

![Screenshot_20200604_171419_com inspireui fluxstore](https://user-images.githubusercontent.com/66424717/83764333-de177b80-a68a-11ea-904f-5f1a3d6e1aa0.jpg)

**Comment by Anoirwork** [comment]
I got the same problem please can you help me ? How can i update the app from 1.7.4 to 1.7.5 please thanks for your reply

**Comment by almaredt** [comment]
hi

I did not update , I just did a fresh install of 1.7.5 , but still for some
of my category's items dose not showing.

Best regards
Ahmad Samadi

Almared Trading
P.O.BOX 15043 Dubai
almaredt@gmail.com
Tel: 00971 4 33 11 940
Mobile: 00971 50 11 66 110

**Comment by Anoirwork** [comment]
I really made everything you might think of even i cloned the wordpress site they got on thier github repo idid everything you might think of but no product show when i change the config.dart to the woo commence website of mine for the default config it works like charm but with my config Nothing would show blogs are there categories with sub categories and item  count for example Men Category got subcategory shores item (16)

**Comment by vumanhsn97** [comment]
@Anoirwork 
You need to set parent category in category setting https://tppr.me/bRQE0. All your categories with parent id = 0 so your categories will not subcategory item
Product is empty because list products return into out of stock so you need to set "hideOutOfStock": false

**Comment by TAMS2018** [comment]
hi,

i have same issue, several products not displaying and even to sell all options.

**Comment by Anoirwork** [comment]
I have solved the issue when i installed dokan plugin which they didn't mention it in their documentation

**Comment by TAMS2018** [comment]
Thank you for supporting me, sir, I will try this recommendation. godbless.

regard.
Wilson

**Comment by TAMS2018** [comment]
Anyway sir, i have wcfm installed on my site, do i can still use this even
the dokan install too?

**Comment by Anoirwork** [comment]
If you are using wcfm then in config.dart put wcfm if dokan (which i use personal) then put dokan but you shouldn’t use both i may help if needed I’m not support stuff by the way !

**Comment by TAMS2018** [comment]
i highly appreciate your support sir, now i have used dokan and it seems
good but unfortunately i also had paid purchased licensed on wcfm.

**Comment by vumanhsn97** [comment]
@TAMS2018 
It will working well. But we just support for one site and one product
Thanks!

**Comment by minhcasi** [comment]
@almaredt - let us know if you have any further issue, feel free to reopen the ticket.

@TAMS2018 @Anoirwork - if you have issues with the Vendor version, pls open new ticket for the Fluxstore VN - this ticket is related to the Fluxstore pro product - thank you for your time
