### ISSUE TITLE
Product not showing FluxStore app

### ISSUE THREAD

**Issue by Anoirwork** [inspireui/support#3593]
So the issue that the products won't show else the categories do show and show that they contains xx items in it but as the screenshots provided also the api of the WooCommerce do show the products like you may go in this url [apiCallProducts](https://market.picslyapp.fun/wp-json/wc/v3/products?status=publish&lang=en&per_page=20&page=1&min_price=0&max_price=500&consumer_key=ck_4fb9dbe96f7e91fa80a2a5fbbb3f17184705ec6c&consumer_secret=cs_44fd9121dbdeda93902a9493b61b828889a67d7a) 
and here's a screenshot of the config and the api call for all products as you may find in the url
//this is pc screen with terminal debug for the app ,config.dart and api call for all products 
https://ibb.co/fxn8J6K
//App screenshots
https://ibb.co/yBDdP25
https://ibb.co/SQFtvVk
https://ibb.co/0njLLhS
Please note i've even clone the wordpress provided in as a preconfig wordpress site as you mentioned in your documentation on the server so i got it preConfigured and i didn't work :x waiting for your reply thanks for your support

**Comment by Anoirwork** [comment]
Hi there if you got the same issue just set up dokan plugin in wordpress that’s it for the support please try to add the plugin to your documentation as there’s nothing that refers to it by any chance i was tired and my client needs the app asap i just came across this name and it works good luck

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as it could not be verified proof of purchase on step 2, please create the new ticket by including the purchased License info - thank you for your time.
