### ISSUE TITLE
wcfm store list not showing

### ISSUE THREAD

**Issue by investisocial** [inspireui/support#3595]
Hello,
i've bought your app and i'm trying to configure it. I'm working with android studio and when i go into the categories and i click on store i cannot see store list. I don't understand where is the issue.

Can you help me please?
Thank you.
Regards
Carlo

Attached files: Issue and license
![envato_panel](https://user-images.githubusercontent.com/57216890/83772033-39457000-a683-11ea-9dd1-776fc6193d1a.jpg)
![Store_Issue](https://user-images.githubusercontent.com/57216890/83772035-3a769d00-a683-11ea-8345-35e7c7226519.jpg)

**Comment by philipvu30** [comment]
Hi,

Please submit your information via our verification [form](http://verify.inspireui.com/). Then I'll send you the solution. Thank you

![image](https://user-images.githubusercontent.com/54442328/83833933-4e6bde80-a717-11ea-99ea-68a301979e35.png)

**Comment by investisocial** [comment]
woooow.. what a beautiful stores! :)
I've sent you the information, thank you.
Regards
Carlo

**Comment by investisocial** [comment]
Hi, i have the same problem with the products, can you help me for it too please? Sorry if I write it in the same form. Please see the attached file.
Thank you.
Regards
Carlo
![products-issue_1](https://user-images.githubusercontent.com/57216890/83865804-0c4a9900-a727-11ea-89f3-1c2101a386d2.jpg)
![products-issue_2](https://user-images.githubusercontent.com/57216890/83865807-0d7bc600-a727-11ea-80f5-e58f2035832a.jpg)

**Comment by philipvu30** [comment]
Hi,

A new lib folder has been sent to your mailbox. Please check.

**Comment by investisocial** [comment]
Hi, thank you i've got it. Have i copy and overwrite all the folders and files?

**Comment by atilaX** [comment]
I have the same problem. Can you send me the library and instructions???

**Comment by investisocial** [comment]
> Ciao,
> 
> Una nuova cartella lib è stata inviata alla tua casella di posta. Si prega di controllare.

I've reinstalled the app, and products and stores regularly works, thanks.
I still have the same problem with the blog. I don't see it. I refresh the page but articles are not showed. Can you help me please?
Thanks
Carlo

**Comment by investisocial** [comment]
Hi, can i hide the category menu in category tab and only show the stores?
Thanks
Regards
Carlo
![Category_Hiding](https://user-images.githubusercontent.com/57216890/83921677-27e18e00-a77f-11ea-8200-ddefa1d5c44d.jpg)

**Comment by investisocial** [comment]
Hi,
i cannot complete an order because there is an error with the shipping method.
I have wcfm shipping method by distance plugin, how can correctly set it?
You can see the error into the attached file.
Can you help me please?
Thank you
Carlo
![Shipping_error](https://user-images.githubusercontent.com/57216890/83940520-0adfa600-a7e5-11ea-9084-ba73a684a028.jpg)

**Comment by philipvu30** [comment]
Hi,

Sorry for the delayed response as we rarely work on weekends.
>I still have the same problem with the blog. I don't see it. I refresh the page but articles are not showed.

Did you manage to solve this?
>Hi, can i hide the category menu in category tab and only show the stores?

Currently, you cannot do that.
>I have wcfm shipping method by distance plugin, how can correctly set it?

Please set OnePageCheckOut to true in lib/common/config/payments.dart
![image](https://user-images.githubusercontent.com/54442328/84006006-3bb40c80-a998-11ea-8d1d-869ba49a8054.png)

**Comment by investisocial** [comment]
Hi,
thank you for reply. 
Blog: it still not works!
Categories: Can I select which categories to show?
Shipping method: it correctly works, great!

I have another question:
I see a minimum order of 100€, where can I change it?

Thank you.
Regards
Carlo

**Comment by philipvu30** [comment]
Hi,
>Blog: it still not works!

Set your settings in config.dart like this "blog": "https://www.spesaservita.it"
>Categories: Can I select which categories to show?

Currently, this feature is temporarily disabled due to an error with subcategories. When it is stable, we will enable it in future releases. 

My apologies for this inconvenience.

**Comment by investisocial** [comment]
Ok thank you, about minimum order, where can i set it?

**Comment by philipvu30** [comment]
Hi,

In lib/common/config/products.dart, there is an attribute kCartDetail. Please set it there.

Thank you.

**Comment by investisocial** [comment]
Thank you. Another question please:
My website is a wcfm multivendor platform where enduser has to do every order for each vendor. They cannot order many products by different vendors. How can I do it into the app?
If i'm doing an order from store "X" and I add to cart a product from store "Y" app must block me and show me a red notice with which it invite me to complete orders for each store.
On my website I just do it.
Thank you.
Regards
Carlo

**Comment by atilaX** [comment]
I need the same feature. Single mode vendor in the app.

I have similar errors of you investisocial. I send you a message by instagram and mail. If you can contact me answer please ;)

**Comment by philipvu30** [comment]
> Thank you. Another question please:
> My website is a wcfm multivendor platform where enduser has to do every order for each vendor. They cannot order many products by different vendors. How can I do it into the app?
> If i'm doing an order from store "X" and I add to cart a product from store "Y" app must block me and show me a red notice with which it invite me to complete orders for each store.
> On my website I just do it.
> Thank you.
> Regards
> Carlo

Hi,

Currently, this feature is not available. We'll consider adding it in later releases.

Thank you for your concern.

**Comment by investisocial** [comment]
Hi, excuse me for the pushing, but this feature is very important for my customer. I just apply this feature on the website. Can I use it into the app?
Thank you.
Regards
Carlo

**Comment by investisocial** [comment]
Hi, any news? Order for each vendor is the main feature of wcfm plugin. I have split stripe pay plugin and I cannot mix the order because I cannot mix the payment. I've asked for it before buying your solution. It's very important to me. Please help me. I only need it and I have completed my project.
Thank you
Regards
Carlo

**Comment by philipvu30** [comment]
Hi,

Sorry for the delayed response. May I ask the OnePageCheckOut function did not help?

**Comment by investisocial** [comment]
Hi, no. I have enabled OnePageCheckout but enduser can buy the products by different vendors. It's a big problem for me because I have split pay stripe payment enabled and I I need one order for each store.  On my website this feature regularly works. Please help me.
Thank you
Regards
Carlo

**Comment by investisocial** [comment]
hi any news? Help me please!

**Comment by philipvu30** [comment]
Hi,

I'm sorry to say this but FluxStore MV does not support this feature. You may need to customize it yourself as this feature requires a lot of work and it is not in our development plan.

**Comment by investisocial** [comment]
Excuse me friend but it's not correct. I'm still waiting for many days and I didn't expect this reply! I need your help it's very important. I asked for this important feature before buying the app! Can we find a solution together? I see that Onepagecheckout feature takes the website checkout page. If I insert this block into Wordpress checkout page, will I find it into the app checkout too?

**Comment by minhcasi** [comment]
@investisocial - feel free to customize the payment process to meet your website requirement.

Please help us to comment your all feedback to one ticket support issue #3730

Thank you for your time!

**Comment by tenkovroman** [comment]
> Hello,
> i've bought your app and i'm trying to configure it. I'm working with android studio and when i go into the categories and i click on store i cannot see store list. I don't understand where is the issue.
> 
> Can you help me please?
> Thank you.
> Regards
> Carlo
> 
> Attached files: Issue and license
> ![envato_panel](https://user-images.githubusercontent.com/57216890/83772033-39457000-a683-11ea-9dd1-776fc6193d1a.jpg)
> ![Store_Issue](https://user-images.githubusercontent.com/57216890/83772035-3a769d00-a683-11ea-8345-35e7c7226519.jpg)

I have the same problem. Please tell me how to fix it.

**Comment by bogatoons** [comment]
i have the same problem in MStore mv. how do i solve this?

**Comment by kenngigz** [comment]
I have the same problem. Please tell me how to fix it.
