### ISSUE TITLE
Chat is not working, Shipping from vendors does not show while checkout.

### ISSUE THREAD

**Issue by Jazzykhan** [inspireui/support#3599]
**_Step 1 (require): describe detail issues & screenshots_**
1: Hi, i have added (i am a vendor) multiple shipping methods via Dokan shipping on my vendor dashboard. see screenshot below:
<img width="934" alt="vendor website dashboard" src="https://user-images.githubusercontent.com/31903098/83795184-84c64100-a6b8-11ea-8028-b93fab8f36a1.png">

Now the issue is this shipping method doesnt show in the app while in the checkout. 
See below screenshot it only says vendor shipping doest show all shipping method that vendor has.
<img width="300" alt="mobile vendor shipping" src="https://user-images.githubusercontent.com/31903098/83795240-9b6c9800-a6b8-11ea-9639-1973fb365db1.png">

2: The issue is How the Live chat with vendor will work i am logged in and firebase datase is connected still the chat doesnt work.

+ Product & version:
FluxStore Multi Vendor.
+ Flutter (or React Native) version: 
Flutter
+ Testing Device/Simulator: 
Emulator.
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

I already sent it. Ticket #3569

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhtruong315** [comment]
Hi @Jazzykhan We updated vendor shipping. it'll be available in next release.
https://github.com/inspireui/support/issues/3354#issuecomment-638904167
For Chat, did you follow this video?
https://www.youtube.com/watch?v=C_9mk_MmvOQ

**Comment by Jazzykhan** [comment]
When the next vendor shipping version is coming? i also ask for access on gitlab but didnt approved yet? can you share code for just shipping? i need that urgent.
Thanks

**Comment by Jazzykhan** [comment]
please approve jzkhankakar@gmail.com on gitlab.
thanks

**Comment by minhtruong315** [comment]
Hi @Jazzykhan I sent you an invitation to the gitlab. please check and let me know the result
