### ISSUE TITLE
[BeoNews] Can not install app into device

### ISSUE THREAD

**Issue by thunderclap1030** [inspireui/support#36]
**Mandatory Info**
 - Product: beonews
 - My Purchased Code: 0c1af8d4-fed0-4095-89b1-f257ad0e1edd

**Describe the issues**

Can not install app into android device. When i type bellow command in root folder beonews-pro

> react-native run-android 

It will show error : 

> Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:

 I use gennymotion simulator and when I have checked adb devices and list devices also. 

> 192.168.56.101:5555  device

**Additional information about environment** : 
react-native-cli: 2.0.1
react-native: 0.57.0
yarn: 1.12.3
Simulator : Samsung Galaxy S7 - 8.0 - API 26

**Comment by thunderclap1030** [comment]
I provide some further proof of this error via bellow image attach : 

<img width="1223" alt="screen shot 2018-11-24 at 6 16 40 pm" src="https://user-images.githubusercontent.com/11660702/48967573-39d46380-f015-11e8-98de-406af8319a1b.png">

**Comment by minhcasi** [comment]
Hi, could you help to check this build.grade to see if can fix the issue - https://gist.github.com/minhcasi/755ae197e7068be289f5e8ea58e910b3

Thank you!

**Comment by alexisttt** [comment]
Hello.
I have the same problem. I did try to install program in two different program and i got error. I did updated android/build.grade but i still have the same issue. In one computer i have a virual device from android studio. On the other an android device is connected. Waiting your help thanks

**Comment by thunderclap1030** [comment]
@minhcasi I have fixed by move jcenter() located in end block.

> allprojects {
....
jcenter() <---
}
and

> buildscript {
...
repositories {
...
jcenter() <---
}
}

What's wrong ?

**Comment by minhcasi** [comment]
Great, thank you for sharing, as i know from the issue - the root cause it download the package from the build server, the google should be at the bottom

**Comment by luyx2412** [comment]
HI @thunderclap1030 Please follow the image add `google()` to fix the issue.
<img width="1197" alt="screen shot 2018-11-29 at 5 27 30 pm" src="https://user-images.githubusercontent.com/8909619/49215960-898fa200-f3fc-11e8-9420-886ed9e260aa.png">

Thanks
