### ISSUE TITLE
[Mstore pro] when launch error

### ISSUE THREAD

**Issue by hakihosting** [inspireui/support#360]
Hello when i clik on the run ios 

i have this error 
:Impossible d’ouvrir « cebuilder.sh » car Sandbox n’est pas autorisé à ouvrir des documents dans Terminal

**Comment by hakihosting** [comment]
what can i do

**Comment by luyx2412** [comment]
HI @hakihosting the Mstore pro can not use `expo cli` to run, please move to Expo version.

Thanks

**Comment by hakihosting** [comment]
I need the pro version for 
Multilanguage

**Comment by hakihosting** [comment]
how can i test the version pro ?

**Comment by luyx2412** [comment]
HI @hakihosting If you are using MStore pro, please do not use `expo cli` to test. This is the document https://docs.mstore.io/get-started#quick-install-pro-version. And please guide Pro version only.

Thanks
