### ISSUE TITLE
Fluxnews: OneSignal Embedded app issue

### ISSUE THREAD

**Issue by aldoyh** [inspireui/support#3600]
Hello,

Proof of purchase attached.

<img width="1033" alt="Screenshot 2020-06-04 20 50 36" src="https://user-images.githubusercontent.com/5215449/83793378-204db680-a6a5-11ea-922a-e680054333b0.png">

With the new update and upon compiling I get this error:

  ```
 error: Embedded binary's bundle identifier is not prefixed with the parent app's bundle identifier.

                Embedded Binary Bundle Identifier:      com.inspireui.fluxnews.OneSignalNotificationServiceExtension
                Parent App Bundle Identifier:           com.wehorseracing.app

```
even when I renamed it, it shows that AppID is not registered, so I need to register my own AppID for that addon app?

this is flutter doctor:
```

[✓] Flutter (Channel stable, v1.17.2, on Mac OS X 10.15.5 19F101, locale en-US)
    • Flutter version 1.17.2 at /Users/aldoyh/development/flutter
    • Framework revision 5f21edf8b6 (7 days ago), 2020-05-28 12:44:12 -0700
    • Engine revision b851c71829
    • Dart version 2.8.3

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/aldoyh/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.44.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1
```

Error screenshot:

<img width="1090" alt="Screenshot 2020-06-05 00 05 23" src="https://user-images.githubusercontent.com/5215449/83810176-5f3d3580-a6c0-11ea-8b43-79c41a19054d.png">

**Comment by minhcasi** [comment]
@aldoyh - please try to open the XCode and change the bundle ID to your own one, under the onesignal target 

<img width="1031" alt="Screen Shot 2020-06-05 at 11 30 10" src="https://user-images.githubusercontent.com/1459805/83837194-f9809600-a71f-11ea-8868-074397db752c.png">

pls check this guide for more detail  https://documentation.onesignal.com/docs/flutter-sdk-setup

**Comment by aldoyh** [comment]
It's resolved! Thank you.

Now, whenever I try to "Inspect target" from Flutter Inspector I get this error: 

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-06-05 at 09 57 34](https://user-images.githubusercontent.com/5215449/83849662-6d1ea500-a718-11ea-85aa-20f3083aaa9d.png)

**Comment by aldoyh** [comment]
Regardless that, and now this when Archive the app for AppStore:
`
bitcode bundle could not be generated because '/Users/.../ios/Flutter/Flutter.framework/Flutter' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file '/Users/.../ios/Flutter/Flutter.framework/Flutter' for architecture armv7`

**Comment by minhcasi** [comment]
@trunghieuvn - pls suggest the solution on this issue - thank you!

**Comment by trunghieuvn** [comment]
@aldoyh hi, you can add skype me, i will teamview fix issue for you  
skype: trunghieu-it@hotmail.com

**Comment by aldoyh** [comment]
I've sent the Teamviewer info on Skype and waiting for you.

**Comment by minhcasi** [comment]
@aldoyh - sorry for late response, please help to update this setting from the xcode to fix the issue (the bundle version from onesignal should be the same with the main app)

<img width="767" alt="Screen Shot 2020-06-16 at 15 36 29" src="https://user-images.githubusercontent.com/1459805/84751782-27e75680-afe7-11ea-9d37-56890862e04f.png">

**Comment by minhcasi** [comment]
@aldoyh let us know your checking :)

**Comment by aldoyh** [comment]
Yes it worked perfectly!

And accepted 😍😍

https://apps.apple.com/us/app/we-horse-racing/id1409165867
