### ISSUE TITLE
ios crash happening while trying to do sms validation

### ISSUE THREAD

**Issue by mmasifashraf** [inspireui/support#3601]
any idea about it??

(
	0   CoreFoundation                      0x00007fff23e3cf0e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff50ba89b2 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23e3cd4c +[NSException raise:format:] + 188
	3   Runner                              0x000000010c944401 -[FIRPhoneAuthProvider verifyPhoneNumber:UIDelegate:completion:] + 193
	4   Runner                              0x000000010d12ae10 -[FLTFirebaseAuthPlugin handleMethodCall:result:] + 17488
	5   Flutter                             0x000000010e7639df __45-[FlutterMethodChannel setMethodCallHandler:]_block_invoke + 104
	6   Flutter                             0x000000010e6f2622 _ZNK7flutter21PlatformMessageRouter21HandlePlat<…>
Lost connection to device.

**Comment by minhcasi** [comment]
is it happen on Android simulator? Thanks

**Comment by mmasifashraf** [comment]
I/flutter (14882): Error: 'package:flutter/src/widgets/localizations.dart': Failed assertion: line 447 pos 12: 'context != null': is not true.

**Comment by minhcasi** [comment]
@mmasifashraf - we have tested the latest release `1.7.5` and it is working fine on both ios and android - could you give a try and double-check the fresh download again?

**Comment by mmasifashraf** [comment]
@minhcasi I’m also working with your  latest updates. Which downloaded yesterday.

**Comment by mmasifashraf** [comment]
@minhcasi  I did following steps to get it resolved. But no luck. 

installed new flutter environment 
installed new flex-store 
created new Firebase settings

**Comment by mmasifashraf** [comment]
Solved.

Issue with MStore API since I forgot to activate after update .

**Comment by skalumek** [comment]
Am getting similar error on Android
Error: 'package:flutter/src/widgets/localizations.dart': Failed assertion: line 453 pos 12: 'context != null': is not true.
