### ISSUE TITLE
Need some app modifications.

### ISSUE THREAD

**Issue by boqaqa** [inspireui/support#3603]
Hello, I want 6 modifications on my app and 1 issue to solve please:

1. Issue is when I go to "Oder History" and tap on order it shows green screen?
![Order history](https://user-images.githubusercontent.com/65863900/83837316-c24dbd00-a6fe-11ea-8e5e-f44092ae81a5.jpg)

2. Remove sign up button, because it accepts fake Email sign up like: sadfdsfadsfasfas@fadasdfafdsfas.com
![remove all this](https://user-images.githubusercontent.com/65863900/83837380-ead5b700-a6fe-11ea-932f-5f67706b99e7.jpg)

3. Want to increase "sign up with sms" button size, it looks small.
![increase sms button size](https://user-images.githubusercontent.com/65863900/83837429-0e006680-a6ff-11ea-84a2-c6f1609eae06.jpg)

4. Replace rotating chat button with only Tawk.to icon, I mean remove, whatsapp,call and sms and the rotation.
![Replace only tawk button](https://user-images.githubusercontent.com/65863900/83837492-3daf6e80-a6ff-11ea-9f38-dd923959d894.jpg)

5. Insert Tawk.to  chat button to home screen.
![Home chat button](https://user-images.githubusercontent.com/65863900/83837545-5fa8f100-a6ff-11ea-9e71-821f086ac9c1.jpg)

6. Remove second line on this tab.
![remove second line](https://user-images.githubusercontent.com/65863900/83839831-bd403c00-a705-11ea-813b-5ea4b9d5bd0b.jpg)

7. Last but not the least, Can I hide one category from category list because It's shown on home screen and I don't want it to be in the category list.
![your choice](https://user-images.githubusercontent.com/65863900/83841544-ba474a80-a709-11ea-9836-43980ca72fb8.jpg)

and thanks.

**Comment by minhcasi** [comment]
@boqaqa - we are sorry that support for these customizations will not include from our support scope, please help to try the Inspector Tools - https://docs.inspireui.com/fluxstore/customization/#1-how-to-customize-any-ui-from-app
