### ISSUE TITLE
[ Fluxstore - Woocommerce ] - Color & Size Attribute Not Showing In Filter Section

### ISSUE THREAD

**Issue by swspro** [inspireui/support#3604]
Hi @minhcasi 

Sam here Hope you are doing well.

We have added the ATTRIBUTES in our PRODUCTS like COLOR & SIZE 

But when we open in the FILTER SECTION of the APP there is no such COLOR and SIZE filter showing under the ATTRIBUTE Section . Please refer to the SCREENSHOT
![WhatsApp Image 2020-06-05 at 11 58 32](https://user-images.githubusercontent.com/15525566/83844598-ecb27100-a724-11ea-978d-f02131db984f.jpeg)

![WhatsApp Image 2020-06-05 at 11 57 57](https://user-images.githubusercontent.com/15525566/83844614-f3d97f00-a724-11ea-9b90-856b12a5772d.jpeg)

Please suggest how we can show those two attributes

Sam

**Comment by minhcasi** [comment]
@trunghieuvn - pls help with suggestion

**Comment by trunghieuvn** [comment]
hi @swspro  i use config you submit, but i can't run app.   
please help me dupble check consumer key. and re-submit. 

thanks

![](https://user-images.githubusercontent.com/19247680/83990990-9a1bc380-a975-11ea-86f5-a5bbda66cddb.png)

**Comment by swspro** [comment]
Hi @trunghieuvn 

Provide me your Email ID i will share with you the website login details 

Also will attach the  common and Lib folder

Sam

**Comment by trunghieuvn** [comment]
i think you should use 'FORK' git and add me to folder source code   
https://www.youtube.com/watch?v=SWLHKx-xzn0  
please provide me access to source code: hieu.trantrung1204@gmail.com

**Comment by swspro** [comment]
Hi @trunghieuvn 

Thanks for your quick response.

Sending you an email and sharing folders

Sam

**Comment by swspro** [comment]
Hi @trunghieuvn 

Just sent you an email from samareshbisoi@gmail.com with Subject line : " Color & Size Attribute Not Showing In Filter Section #3604 "

All your help will be highly appreciated

Regards,
Sam

**Comment by trunghieuvn** [comment]
i receive email, i investigating and i will relay soon.

**Comment by swspro** [comment]
Hi @trunghieuvn 

Thanks for your quick response.


Sam

**Comment by trunghieuvn** [comment]
I have checked your project. It works fine. To show the attribute you need to click the Size or Color button. 

![](https://user-images.githubusercontent.com/19247680/84590085-c5af1a00-ae5d-11ea-8c1d-d1a75ae43622.png)

![](https://user-images.githubusercontent.com/19247680/84590093-d2337280-ae5d-11ea-98a2-c1783a7ad786.png)

It currently does not have any default attributes enabled. To activate the default attribute first, please follow the steps below:

In file `lib/widgets/backdrop/backdrop_menu.dart` , edit the following code:

*    Change `currentSelectedAttr` from -1 to 0 

![](https://user-images.githubusercontent.com/19247680/84590144-2f2f2880-ae5e-11ea-93b2-61ec69adaa23.png)

*   change code create button attribute, search for keyword `Consumer<FilterAttributeModel>`  and edit code: 

```
onTap: () {
  if (!value.isLoading) {
    currentSelectedAttr = index;
    currentSlug =
        value.lstProductAttribute[currentSelectedAttr].slug;
    value.getAttr(
        id: value.lstProductAttribute[currentSelectedAttr].id);
  }
},
```

![](https://user-images.githubusercontent.com/19247680/84590182-833a0d00-ae5e-11ea-9939-18d40eececdf.png)

**Comment by swspro** [comment]
Hi @trunghieuvn 

Thanks will try and revert you back..

Have some other queries..

Will msg you tomorrow 

Sam
