### ISSUE TITLE
[FluxStore WooCommerce 1.7.5] Saved Addresses Add additional fields to checkout.

### ISSUE THREAD

**Issue by IamJAX** [inspireui/support#3605]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 

**1. The app does not load user's address saved in the profile on the woocommerce site.
Are the address on the app stored locally? Can it update address on the site and retrieve it?**

**2. I want to add some additional fields to the checkout form on the app. The data is to be saved to custom fields for the order as 'billing_a'. Can you please help me out with which file to change and a sample code to add a single field?**

**3.  Address is not getting add when I select it from Google map.**

+ Product & version: **FluxStore WooCommerce** 
+ Flutter (or React Native) version: **1.7.5**
+ Testing Device/Simulator: **Android**

Thank you so much for your time 😊

**Comment by IamJAX** [comment]
Submitted purchase proof.

**Comment by IamJAX** [comment]
I have seen Ticket #2859

I have been able to add field. But was not able to figure out how to save the values as custom fields of the order. Can you please help me out with which file to edit and a sample code?

**Comment by minhcasi** [comment]
We wanted to thank you for your patience during this busy time. We currently have reduced staff and a significantly higher volume of inquiries. We’re working as hard as we can to get to your request as soon as possible.

We sincerely apologize for the delay and hope you’re staying safe.

**Comment by IamJAX** [comment]
Can you please help me out with #2 first so that I can learn more on customising this?

**Comment by minhtruong315** [comment]
Hi @IamJAX can u upload your source code to github and invite me: minhtruong315@gmail.com
I will help you check issue #1 and #3.
for #2, you can add additional fields on meta_data field https://woocommerce.github.io/woocommerce-rest-api-docs/#order-properties

**Comment by IamJAX** [comment]
Let me upload to GitHub.

**Comment by minhtruong315** [comment]
Hi @IamJAX can u record  screen?

**Comment by IamJAX** [comment]
Yes. I can record screen. Please let me know what you want recorded.

**Comment by minhtruong315** [comment]
Can you record screen your issues?
Thanks

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!

**Comment by IamJAX** [comment]
**2. I want to add some additional fields to the checkout form on the app. The data is to be saved to custom fields for the order as 'billing_a'. Can you please help me out with which file to change and a sample code to add a single field?**

Can you please help me out which files should I edit to add additional meta_data fields?
