### ISSUE TITLE
Category Card view dont show category image 

### ISSUE THREAD

**Issue by ahmadmadieh** [inspireui/support#3606]
**_Step 1 (require): describe detail issues & screenshots_**
I use woocommerce fluxstore app ,, when i use a card view for my categories the category image didnt shown ?
can you help me of that please

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by ahmadmadieh** [comment]
Issue #2 :
suddenly my app back to the default demo, the code show something but when i run it shows something else !!!

whats the problem here ?
please replay as soon as possible this is an urgent case !

**Comment by ahmadmadieh** [comment]
Issue #3 
the language of the bottom tab dont change when i switch to another language ?

**Comment by minhcasi** [comment]
We wanted to thank you for your patience during this busy time. We currently have reduced staff and a significantly higher volume of inquiries. We’re working as hard as we can to get to your request as soon as possible.

We sincerely apologize for the delay and hope you’re staying safe.

**Comment by ahmadmadieh** [comment]
Thank you and can you try to slove my issues as soon as possible .. 
this issues in shown suddenly and everytime i change the code nothing reflect on the app !

**Comment by minhtruong315** [comment]
Hi @ahmadmadieh can u upload your source code to github and invite me: minhtruong315@gmail.com
I will help you check and fix on your source code.
Thanks

**Comment by ahmadmadieh** [comment]
Done , please help me as soon as possible

**Comment by minhtruong315** [comment]
Hi @ahmadmadieh you're configuring ```"isCaching": true``` so the app only load config_xx.json from your website. doesn't load from config folder. so you can't use multi language if you enable isCaching. 
Can try to disable isCaching and try again.
For category issue, I see it's showing.
![Simulator Screen Shot - iPhone X - 2020-06-08 at 07 17 11](https://user-images.githubusercontent.com/10402500/83983390-23240200-a958-11ea-8a5f-66b0c306cc30.png)

**Comment by minhtruong315** [comment]
hi @ahmadmadieh how? let me know the result.
Thanks

**Comment by ahmadmadieh** [comment]
Thank you, it works now ...
another help please , i want to click anywhere on the category to show their product now i must click on arrow to show the products 

please find the attach for more clarify
![Capture](https://user-images.githubusercontent.com/25867226/84074678-96bb2300-a9db-11ea-86af-9caf567697cf.PNG)

**Comment by minhtruong315** [comment]
Hi @ahmadmadieh if you have children category, you can click on the row to show children category and click the number to show products. if you want to click the row to show products, you can update the source code. 
Thanks
