### ISSUE TITLE
xcode error failed to remove xcbuild

### ISSUE THREAD

**Issue by harrysol** [inspireui/support#3607]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues:     2020-06-05 13:43:37.188 XCBBuildService[19971:4046507] Failed to remove: /Users/harrysitbon/Library/Developer/Xcode/DerivedData/Runner-eharrogemdbmbvhhqzhnxmyrgdsu/Build/Intermediates.noindex/XCBuildData/55056ccc17bd9cf31e1b7f802c63aaf3-manifest.xcbuild: unlink(/Users/harrysitbon/Library/Developer/Xcode/DerivedData/Runner-eharrogemdbmbvhhqzhnxmyrgdsu/Build/Intermediates.noindex/XCBuildData/55056ccc17bd9cf31e1b7f802c63aaf3-manifest.xcbuild): No such file or directory (2)

+ Product & version: 1,7,5
+ Flutter (or React Native) version:  flutter
+ Testing Device/Simulator:  iphone 11
+ Screenshot issues (drag the file to attach here): 

![12](https://user-images.githubusercontent.com/37178477/83872792-f80c9900-a732-11ea-8512-9b2430d7c01e.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@harrysol - could you give a try with some solution on this link https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

some important points:
+ run `flutter clean` to clean up your previous settings.
+ update your pod to the latest by using `pod repo upgrade`
+ change the workspace the 'new build system`
+ update to latest XCode, some previous version could not work well on Flutter 1.17

**Comment by harrysol** [comment]
[image: image.png]

**Comment by minhtruong315** [comment]
Hi @harrysol can u add my skype: minhtruong315
I will help you check via teamviewer
Thanks

**Comment by minhtruong315** [comment]
Hi @harrysol what is the Flutter version you're using?

**Comment by minhtruong315** [comment]
supported via teamviewer
