### ISSUE TITLE
bitcode bundle

### ISSUE THREAD

**Issue by tintunnaing** [inspireui/support#3608]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: “bitcode bundle could not be generated because ’/Users/....” ERROR while run Xcode archive. Also , Yes bitcode on build setting, cannot.
+ Product & version: Woocommerce Flutter
+ Flutter (or React Native) version: 1.7.4
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

<img width="1010" alt="Screen Shot 2020-06-05 at 18 40 54" src="https://user-images.githubusercontent.com/1088761/83874951-47b38a80-a75c-11ea-8ec9-7e65692a5143.png">
<img width="746" alt="Screen Shot 2020-06-05 at 18 41 50" src="https://user-images.githubusercontent.com/1088761/83875240-c1e40f00-a75c-11ea-84cb-90b50eb3626f.png">

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@tintunnaing - could you give a try with some solution on this link https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

some 2 important points:
+ update your pod to the latest by using `pod repo upgrade`
+ change the workspace the 'new build system`

**Comment by tintunnaing** [comment]
I did this steps, stay appear error & cannot Archive.

**Comment by minhtruong315** [comment]
Hi @tintunnaing can u add my skype: minhtruong315
I will help you check via teamviewer
Thanks

**Comment by papaya1986** [comment]
i faced same issue,, need to change bitcode no from pod file , and run build ios

**Comment by minhtruong315** [comment]
Hi @tintunnaing I downloaded the Fluxstore version 1.7.5 on codecanyon. it's archiving well. 
Can you try to download the latest version and try again?
Thanks

**Comment by minhtruong315** [comment]
supported via teamviewer
