### ISSUE TITLE
application crashed when open it.

### ISSUE THREAD

**Issue by jitu94517** [inspireui/support#3609]
+ Detail Issues: **Application crashed after open it.** 
+ Product & version: **Mstore Pro**
+ Flutter (or React Native) version: **Latest** 
+ Testing Device/Simulator: **Real Device (Redmi Note 7s, Redmi 3s, Realme XT)**
+ Screenshot issues (drag the file to attach here): 
![Screenshot_2020-06-05-18-28-26-139_com miui home](https://user-images.githubusercontent.com/66323700/83890576-8f8cde80-a769-11ea-8c87-e07c23813f7f.jpg)

![Screenshot_2020-06-05-22-25-38-167_com miui bugreport](https://user-images.githubusercontent.com/66323700/83903939-a557cf00-a77c-11ea-8e3d-f5bed014324d.jpg)

**Comment by minhcasi** [comment]
@jitu94517 - pls help to move the conversattion to #3557
