### ISSUE TITLE
[Mstore] Category Page Error | JSON value '0' of type NSNumber cannot be converted to NSString

### ISSUE THREAD

**Issue by fthkrtl** [inspireui/support#361]
**Required Info (please complete the following information):**
 - Product: MStore
 - Your Purchased Code: 8e06cc57-6afe-441f-9acb-a8adb1a77f3c

**Describe the bug**
Can not open category tab

**Screenshots**

<img width="1112" alt="1" src="https://user-images.githubusercontent.com/32594264/53692825-7bf50a00-3da7-11e9-8671-4576392aabae.png">

**Comment by luyx2412** [comment]
Hi @fthkrtl You can debug in `src/containers/Categories/index.js` file. Maybe the name or another option is not string type.

Thanks
