### ISSUE TITLE
Unable to bluid the APK

### ISSUE THREAD

**Issue by pirrot** [inspireui/support#3610]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: Launching lib\main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...

Compiler message:
lib/widgets/home/banner/banner_map.dart:44:23: Error: A value of type 'PermissionStatus' can't be assigned to a variable of type 'bool'.
 - 'PermissionStatus' is from 'package:location/location.dart' ('../../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/location-2.5.4/lib/location.dart').
        _permission = await _locationService.requestPermission();
                      ^
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

Compiler message:
lib/widgets/home/banner/banner_map.dart:44:23: Error: A value of type 'PermissionStatus' can't be assigned to a variable of type 'bool'.
 - 'PermissionStatus' is from 'package:location/location.dart' ('../../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/location-2.5.4/lib/location.dart').
        _permission = await _locationService.requestPermission();
                      ^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\HugoPC\Documents\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 882

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\Users\HugoPC\Documents\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 33s
+ Product & version: Fluxstore-Listing 1.4.1
+ Flutter (or React Native) version: Flutter 1.17.2
+ Testing Device/Simulator: Pixel 3a XL API 29 - Android 10.0 x86
+ Screenshot issues (drag the file to attach here): 
![capture](https://user-images.githubusercontent.com/8491575/83892263-039c9780-a714-11ea-9956-ebdd9335669f.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

![validate support](https://user-images.githubusercontent.com/8491575/83893674-dcdf6080-a715-11ea-960e-ef3bcce623ed.png)

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by michaelbrinkworth** [comment]
https://www.facebook.com/groups/289288585778355/edit/

**Comment by michaelbrinkworth** [comment]
https://www.facebook.com/groups/289288585778355/

**Comment by philipvu30** [comment]
Hi,

Sorry for the delayed response as we rarely work on the weekends. May I have a look at this file android/gradle/wrapper/gradle-wrapper.properties? 

Thank you.

**Comment by pirrot** [comment]
Of course I'll attach that file
[wrapper.zip](https://github.com/inspireui/support/files/4746472/wrapper.zip)

**Comment by philipvu30** [comment]
Hi,

Have you tried to run pub get in pubspec.yaml file or run the command flutter packages get yet?

**Comment by pirrot** [comment]
Already done that, and keeps showing the same errors

**Comment by philipvu30** [comment]
Hi,

Sorry for the delayed response as we are kind of busy lately.

In lib/widgets/home/banner/banner_map.dart, replace this line with this code _permission = (await _locationService.requestPermission()) as bool;

![image](https://user-images.githubusercontent.com/54442328/84463202-3528dc00-ac9b-11ea-8dd3-e532b682dcd1.png)

I don't know why this happens if you are using the latest version. I hope this will solve your issue.
Thank you for your patience.

**Comment by pirrot** [comment]
Hi guys I was able to build the APK in another PC, thanks for the support

**Comment by minhcasi** [comment]
@pirrot - We're glad that it help, please give us some feedback/rating to this page https://codecanyon.net/downloads  if the product is helpful for your business, we are working hard to update more awesome and powerful features on next coming version release. Let us know if you have any feedback. Thank you very much 😊
