### ISSUE TITLE
i can't change my licence code 

### ISSUE THREAD

**Issue by mohamadrw** [inspireui/support#3611]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: I canceled  Regular License and bought  Extended License so my old License  stopped and my app is have problem i can not have all information like Categories 
i can't change old License  from wordpress please please help me because this app is available now 
+ Product & version: Fluxstore WooCommerce 1.7.5
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

![image](https://user-images.githubusercontent.com/53875618/83910059-94a25b80-a772-11ea-9803-f8868a0a91f2.png)
![image](https://user-images.githubusercontent.com/53875618/83910157-b996ce80-a772-11ea-89c6-da9c42a754c7.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhtruong315** [comment]
Hi @mohamadrw can u send me admin account to login to your website via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/3611

**Comment by minhtruong315** [comment]
Hi @mohamadrw The category name doesn't show because those categories dont have products.
You need to add products to categories which you config on category layout in config_xx.json

**Comment by mohamadrw** [comment]
there is products in it 

you can look at arabic vision 
i changed your admin panel to English 
and please help me to change licence code

**Comment by minhtruong315** [comment]
Hi @mohamadrw please replace getCategoriesByPage function on services/woocommerce.dart like this and try again
```
Future<List<Category>> getCategoriesByPage({lang, page}) async {
    try {
      List<Category> categories = [];
      String url =
          "products/categories?exclude=$kExcludedCategory&per_page=100&page=$page&hide_empty=true";
      if (lang != null) {
        url += "&lang=$lang";
      }
      var response = await wcApi.getAsync(url);

      if (response is Map && isNotBlank(response["message"])) {
        throw Exception(response["message"]);
      } else {
        for (var item in response) {
          if (item['slug'] != "uncategorized") {
            categories.add(Category.fromJson(item));
          }
        }
        return categories;
      }
    } catch (e) {
      //This error exception is about your Rest API is not config correctly so that not return the correct JSON format, please double check the document from this link https://docs.inspireui.com/fluxstore/woocommerce-setup/
      rethrow;
    }
  }
```
in common/config/general.dart you should config app config like this to load config_ar.json file
```
/// Default app config, it's possible to set as URL
const kAppConfig = 'lib/config/config_ar.json';
```
![Simulator Screen Shot - iPhone X - 2020-06-09 at 08 35 18](https://user-images.githubusercontent.com/10402500/84096456-2983ae00-aa2c-11ea-97e2-71aa6e89925c.png)

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
