### ISSUE TITLE
Code Changes dont reflect on the app, and everything reset to the default demo !

### ISSUE THREAD

**Issue by ahmadmadieh** [inspireui/support#3614]
Hello ,
suddenly my app back to the default demo, the code show something but when i run it shows something else !!!

whats the problem here ?
please replay as soon as possible this is an urgent case !

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by ahmadmadieh** [comment]
its just happen when i insert my Rest API ,when i remove them everything works correctly !
for more details look at the attached images :
1) the code for below tab
2) what is shown when i run it 
![Code](https://user-images.githubusercontent.com/25867226/83930073-7fdbbd00-a79e-11ea-8a5d-29b267398272.PNG)

![output](https://user-images.githubusercontent.com/25867226/83930074-81a58080-a79e-11ea-8593-adfe66767f21.PNG)

**Comment by minhcasi** [comment]
@ahmadmadieh - pls help to post your all issue to the same ticket #3606
