### ISSUE TITLE
Fluxstore App - Wcfm Shipping issues

### ISSUE THREAD

**Issue by investisocial** [inspireui/support#3615]
Hi,
i cannot complete an order because there is an error with the shipping method.
I have wcfm shipping method by distance plugin, how can correctly set it?
You can see the error into the attached file.

App: Fluxstore
Android Studio 1.8.0_242
![Shipping_error](https://user-images.githubusercontent.com/57216890/83922554-cb7f6e00-a780-11ea-913c-e086e5503050.jpg)

[√] Flutter (Channel stable, v1.17.3, on Microsoft Windows [Versione 10.0.18363.836], locale it-IT)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 4.0)
[√] VS Code (version 1.45.1)
[√] Connected device (1 available)

• No issues found!

Thank you.
Regards
Carlo

![envato_panel](https://user-images.githubusercontent.com/57216890/83922591-ddf9a780-a780-11ea-85a4-1a163e4bb99d.jpg)

**Comment by minhcasi** [comment]
@investisocial - pls help to move the conversation to the same of your ticket #3595
