### ISSUE TITLE
Multi language support for products!

### ISSUE THREAD

**Issue by xsamir** [inspireui/support#3616]
Thanks to the support team for their continued support for their clients.

I have a general question for the MultiVendor app.
Does the app support multi-language for categories names?

If not, Does the app will be ok with translating plugins like WPML?

Regards,

**Comment by minhcasi** [comment]
Yes, it supports multi-language for categories name, that why you could see multi config_xx file that uses for the language config

The WPML is required to support for multi-language

Let us know if you have any further questions - thank you!
