### ISSUE TITLE
How To Change Menu Drawer Icon To Hamburger ?

### ISSUE THREAD

**Issue by bakpaorabbit** [inspireui/support#3618]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: Edit Menu Drawer Icon
+ Product & version: Fluxstore Woocommerce
+ Flutter (or React Native) version: Latest
+ Testing Device/Simulator: Redmi Note 8 Pro Real Device
+ Screenshot issues (drag the file to attach here): 

Hi, a simple question, i cannot find how to change menu drawer icon?
Thank you so much.

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as it could not be verified proof of purchase on step 2, please create the new ticket by including the purchased License info - thank you for your time.
