### ISSUE TITLE
[listPro] Firebase Error

### ISSUE THREAD

**Issue by chad-the-first** [inspireui/support#362]
- Product: [ListPro]
 - Your Purchased Code: 65e47917-78fa-4b8e-97ec-80bf8345f72a
(we may not reply if you are not our customer)

**Describe the bug**
when i try to send a notification through firebase i get this error in the console as you can see in the screenshot.
this is the index.js:

const functions = require('firebase-functions');
// Import and initialize the Firebase Admin SDK
const admin = require("firebase-admin");
const Expo = require("expo-server-sdk");
admin.initializeApp(functions.config().firebase);

// // Create and Deploy Your First Cloud Functions
// // https://firebase.google.com/docs/functions/write-firebase-functions

exports.saveTokens = functions.https.onRequest((request, response) => {
	let ok = true;
	let error = null;
	let token = request.body.token;
	if(token == "" || typeof token == "undefined") {
		ok = false;
		error = "Token is required";
	} else {
		let db = admin.database();
		let ref = db.ref().child("fcm_tokens");
		ref.set({ token });
	}
	response.send({
		ok,
		error
	});
});

exports.sendPushNotification = functions.https.onRequest(
	(request, response) => {
		let ok = true;
		let error = null;
		// send Notification
		let title = request.body.title;
		let body = request.body.body;

		admin.database()
			.ref("fcm_tokens/")
			.on("value", function(snapshot) {
				// Creat a new Expo SDK client
				let expo = new Expo();

				// Create the messages that you want to send to clients
				let messages = [];
				snapshot.forEach(function(data) {
					let pushToken = data.val();
					// Each push token looks like ExponentPushToken [xxxxxxxxxxxxxxxxxxxxxxxxxx]
					// console.log(pushToken)
					// Check that all your push tokens appear to be valid Expo push tokens
					if (!Epo.isExpoPushToken(pushToken)) {
						console.error(
							`Push token ${pushToken} is not a valid Expo push token`
							);
						// continue;
					}

					// Construct a message (see https://docs.expo.io/versions/latesst/guides/push-notifications.html)
					messages.push({
						to: pushToken,
						sound: "default",
						body,
						data: { withSome: "data" }
					});

					let chunks = expo.chunkPushNotifications(messages);

					// Send the chunks to the Expo push notification service. There are
					// different strategies you could use. A simple one is to send one chunk at a
					// time, which nicely spreads the load out over time:
					for (let chunk of chunks) {
						try {
							let receipts = expo.sendPushNotificationsAsync(chunk)
							console.log(receipts);
						} catch (error) {
							console.error(error);
						}
					}

				}); // end snapshot

			}); // end for process

			// Return
			response.send({
				ok: ok,
				error: error
			});
		}
	);

**Screenshots**
![sketch](https://user-images.githubusercontent.com/17035853/53698721-47a23d80-3de9-11e9-9b4d-fd409bf460ff.png)

**Comment by thangvo9x** [comment]
Hi. Do you have test it on real device ? They has only worked on the real device. or you can detach it to native version.

**Comment by chad-the-first** [comment]
I'm getting this error from firebase console not from the app.

![sketch](https://user-images.githubusercontent.com/17035853/53744303-68c86400-3ea5-11e9-8549-4553d516f586.png)

**Comment by chad-the-first** [comment]
why closing the ticket without solving the issue?!!

**Comment by chad-the-first** [comment]
When will a detailed instruction about setting up Firebase will be released?
