### ISSUE TITLE
After adding my language and making it as deafult im getting MaterialLocalizations problem

### ISSUE THREAD

**Issue by eraldix** [inspireui/support#3623]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: This is the issue after i made my own translation
Warning: This application's locale, al, is not supported by all of its
flutter: localization delegates.
flutter: > A MaterialLocalizations delegate that supports the al locale was not found.
flutter: See https://flutter.dev/tutorials/internationalization/ for more
flutter: information about configuring an app's locale, supportedLocales,
flutter: and localizationsDelegates parameters.
+ Product & version:  Fluxstore Multiversion 1.7.4
+ Flutter (or React Native) version: latest
+ Testing Device/Simulator: iOS Android
+ Screenshot issues (drag the file to attach here): 
<img width="1680" alt="Screenshot 2020-06-06 at 2 25 15 PM" src="https://user-images.githubusercontent.com/44481659/83944422-ada71d00-a803-11ea-99c4-584d75ae2bce.png">

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@eraldix - please help to double-check this guide https://docs.inspireui.com/fluxstore/multi-language/ to setup the plugin on your Android Studio

**Comment by eraldix** [comment]
I checked everything and again this is what i get

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building TabBar(dirty, dependencies: [_InheritedTheme, _LocalizationsScope-[GlobalKey#fc2e4]], state: _TabBarState#a1a49):
No MaterialLocalizations found.

TabBar widgets require MaterialLocalizations to be provided by a Localizations widget ancestor.
Localizations are used to generate many different messages, labels, and abbreviations which are used by the material library.

To introduce a MaterialLocalizations, either use a MaterialApp at the root of your application to include them automatically, or add a Localization widget with a MaterialLocalizations delegate.

The specific widget that could not find a MaterialLocalizations ancestor was: TabBar
  dirty
  dependencies: [_InheritedTheme, _LocalizationsScope-[GlobalKey#fc2e4]]
  state: _TabBarState#a1a49
The ancestors of this widget were: 
  : Container
    constraints: BoxConstraints(w=333.5, 0.0<=h<=Infinity)
  : FittedBox
    fit: contain
    alignment: center
    dependencies: [Directionality]
    renderObject: RenderFittedBox#cc826 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
  : Container
    constraints: BoxConstraints(w=375.0, 0.0<=h<=Infinity)
  : SafeArea
    avoid left padding
    avoid top padding
    avoid right padding
    avoid bottom padding
    dependencies: [MediaQuery]
  : Scaffold-[LabeledGlobalKey<ScaffoldState>#65614]
    dependencies: [_InheritedTheme, _LocalizationsScope-[GlobalKey#fc2e4], _EffectiveTickerMode, Directionality, MediaQuery]
    state: ScaffoldState#fc4a1(tickers: tracking 2 tickers)
  : Container
    bg: Color(0xffffffff)
  : MainTabs
    dependencies: [_InheritedProviderScope<CartModel>, _InheritedTheme, _LocalizationsScope-[GlobalKey#fc2e4], MediaQuery]
    state: MainTabsState#d319b(ticker inactive)
  : MaterialApp
    state: _MaterialAppState#b5649
  : _InheritedProviderScope<Ads>
    value: <not yet loaded>
  : ChangeNotifierProvider<Ads>
    value: <not yet loaded>
  : _NestedHook
  : _InheritedProviderScope<BlogModel>
    value: Instance of 'BlogModel'
    listening to value
  : ChangeNotifierProvider<BlogModel>
    value: Instance of 'BlogModel'
    listening to value
  : _NestedHook
  : _InheritedProviderScope<BlogModel>
    value: <not yet loaded>
  : ChangeNotifierProvider<BlogModel>
    value: <not yet loaded>
  : _NestedHook
  : _InheritedProviderScope<CategoryModel>
    value: Instance of 'CategoryModel'
    listening to value
  : ChangeNotifierProvider<CategoryModel>
    value: Instance of 'CategoryModel'
    listening to value
  : _NestedHook
  : _InheritedProviderScope<CartModel>
    value: Instance of 'CartModelWoo'
    listening to value
  : ChangeNotifierProvider<CartModel>
    value: Instance of 'CartModelWoo'
    listening to value
  : _NestedHook
  : _InheritedProviderScope<FilterTagModel>
  : Provider<FilterTagModel>
    value: Instance of 'FilterTagModel'
  : _NestedHook
  : _InheritedProviderScope<FilterAttributeModel>
  : Provider<FilterAttributeModel>
    value: Instance of 'FilterAttributeModel'
  : _NestedHook
  : _InheritedProviderScope<UserModel>
  : Provider<UserModel>
    value: Instance of 'UserModel'
  : _NestedHook
  : _InheritedProviderScope<StoreModel>
  : Provider<StoreModel>
    value: Instance of 'StoreModel'
  : _NestedHook
  : _InheritedProviderScope<RecentModel>
  : Provider<RecentModel>
    value: Instance of 'RecentModel'
  : _NestedHook
  : _InheritedProviderScope<SearchModel>
  : Provider<SearchModel>
    value: Instance of 'SearchModel'
  : _NestedHook
  : _InheritedProviderScope<OrderModel>
  : Provider<OrderModel>
    value: Instance of 'OrderModel'
  : _NestedHook
  : _InheritedProviderScope<PaymentMethodModel>
  : Provider<PaymentMethodModel>
    value: Instance of 'PaymentMethodModel'
  : _NestedHook
  : _InheritedProviderScope<ShippingMethodModel>
  : Provider<ShippingMethodModel>
    value: Instance of 'ShippingMethodModel'
  : _NestedHook
  : _InheritedProviderScope<WishListModel>
  : Provider<WishListModel>
    value: Instance of 'WishListModel'
  : _NestedHook
  : _InheritedProviderScope<ProductModel>
  : Provider<ProductModel>
    value: Instance of 'ProductModel'
  : _NestedHook
  : MultiProvider
  : Consumer<AppModel>
    dependencies: [_InheritedProviderScope<AppModel>]
  : _InheritedProviderScope<AppModel>
    listening to value
  : ChangeNotifierProvider<AppModel>
    value: Instance of 'AppModel'
    listening to value
  : App
    state: AppState#a732f
  ...
The relevant error-causing widget was: 
  TabBar file:///Users/pentazon/Downloads/FluxStore-vendor-1.7.4/source/lib/tabbar.dart:319:26
When the exception was thrown, this was the stack: 
#0      debugCheckHasMaterialLocalizations.<anonymous closure> (package:flutter/src/material/debug.dart:72:7)
#1      debugCheckHasMaterialLocalizations (package:flutter/src/material/debug.dart:92:4)
#2      _TabBarState.build (package:flutter/src/material/tabs.dart:1000:12)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4619:28)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4502:15)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
No MaterialLocalizations found.
The ancestors of this widget were: 
  : Scaffold-[LabeledGlobalKey<ScaffoldState>#65614]
    dependencies: [_InheritedTheme, _LocalizationsScope-[GlobalKey#fc2e4], _EffectiveTickerMode, Directionality, MediaQuery]
    state: ScaffoldState#fc4a1(tickers: tracking 2 tickers)
  : Container
    bg: Color(0xffffffff)
  : MainTabs
    dependencies: [_InheritedProviderScope<CartModel>, _InheritedTheme, _LocalizationsScope-[GlobalKey#fc2e4], MediaQuery]
    state: MainTabsState#d319b(ticker inactive)
  : MaterialApp
    state: _MaterialAppState#b5649
  : _InheritedProviderScope<Ads>
    value: <not yet loaded>
  : ChangeNotifierProvider<Ads>
    value: <not yet loaded>
  : _NestedHook
  : _InheritedProviderScope<BlogModel>
    value: Instance of 'BlogModel'
    listening to value
  : ChangeNotifierProvider<BlogModel>
    value: Instance of 'BlogModel'
    listening to value
  : _NestedHook
  : _InheritedProviderScope<BlogModel>
    value: <not yet loaded>
  : ChangeNotifierProvider<BlogModel>
    value: <not yet loaded>
  : _NestedHook
  : _InheritedProviderScope<CategoryModel>
    value: Instance of 'CategoryModel'
    listening to value
  : ChangeNotifierProvider<CategoryModel>
    value: Instance of 'CategoryModel'
    listening to value
  : _NestedHook
  : _InheritedProviderScope<CartModel>
    value: Instance of 'CartModelWoo'
    listening to value
  : ChangeNotifierProvider<CartModel>
    value: Instance of 'CartModelWoo'
    listening to value
  : _NestedHook
  : _InheritedProviderScope<FilterTagModel>
  : Provider<FilterTagModel>
    value: Instance of 'FilterTagModel'
  : _NestedHook
  : _InheritedProviderScope<FilterAttributeModel>
  : Provider<FilterAttributeModel>
    value: Instance of 'FilterAttributeModel'
  : _NestedHook
  : _InheritedProviderScope<UserModel>
  : Provider<UserModel>
    value: Instance of 'UserModel'
  : _NestedHook
  : _InheritedProviderScope<StoreModel>
  : Provider<StoreModel>
    value: Instance of 'StoreModel'
  : _NestedHook
  : _InheritedProviderScope<RecentModel>
  : Provider<RecentModel>
    value: Instance of 'RecentModel'
  : _NestedHook
  : _InheritedProviderScope<SearchModel>
  : Provider<SearchModel>
    value: Instance of 'SearchModel'
  : _NestedHook
  : _InheritedProviderScope<OrderModel>
  : Provider<OrderModel>
    value: Instance of 'OrderModel'
  : _NestedHook
  : _InheritedProviderScope<PaymentMethodModel>
  : Provider<PaymentMethodModel>
    value: Instance of 'PaymentMethodModel'
  : _NestedHook
  : _InheritedProviderScope<ShippingMethodModel>
  : Provider<ShippingMethodModel>
    value: Instance of 'ShippingMethodModel'
  : _NestedHook
  : _InheritedProviderScope<WishListModel>
  : Provider<WishListModel>
    value: Instance of 'WishListModel'
  : _NestedHook
  : _InheritedProviderScope<ProductModel>
  : Provider<ProductModel>
    value: Instance of 'ProductModel'
  : _NestedHook
  : MultiProvider
  : Consumer<AppModel>
    dependencies: [_InheritedProviderScope<AppModel>]
  : _InheritedProviderScope<AppModel>
    listening to value
  : ChangeNotifierProvider<AppModel>
    value: Instance of 'AppModel'
    listening to value
  : App
    state: AppState#a732f
  ...
The relevant error-causing widget was: 
  Scaffold-[LabeledGlobalKey<ScaffoldState>#65614] file:///Users/pentazon/Downloads/FluxStore-vendor-1.7.4/source/lib/tabbar.dart:274:16
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
No MaterialLocalizations found.
The ancestors of this widget were: 
  : HomeLayout-[<'al'>]
    dependencies: [MediaQuery]
    state: _HomeLayoutState#21b9f
  : Stack
    alignment: AlignmentDirectional.topStart
    fit: loose
    overflow: clip
    dependencies: [Directionality]
    renderObject: RenderStack#1f347 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
  : Consumer<AppModel>
    dependencies: [_InheritedProviderScope<AppModel>]
  : SafeArea
    avoid left padding
    avoid top padding
    avoid right padding
    avoid bottom padding
    dependencies: [MediaQuery]
  : HomeScreen
    state: HomeScreenState#8a899
  : TabBarView
    state: _TabBarViewState#9553e
  : WillPopScope
    dependencies: [_ModalScopeStatus]
    state: _WillPopScopeState#f46d9
  : Scaffold-[LabeledGlobalKey<ScaffoldState>#65614]
    dependencies: [_InheritedTheme, _LocalizationsScope-[GlobalKey#fc2e4], _EffectiveTickerMode, Directionality, MediaQuery]
    state: ScaffoldState#fc4a1(tickers: tracking 2 tickers)
  : Container
    bg: Color(0xffffffff)
  : MainTabs
    dependencies: [_InheritedProviderScope<CartModel>, _InheritedTheme, _LocalizationsScope-[GlobalKey#fc2e4], MediaQuery]
    state: MainTabsState#d319b(ticker inactive)
  : MaterialApp
    state: _MaterialAppState#b5649
  : _InheritedProviderScope<Ads>
    value: <not yet loaded>
  : ChangeNotifierProvider<Ads>
    value: <not yet loaded>
  : _NestedHook
  : _InheritedProviderScope<BlogModel>
    value: Instance of 'BlogModel'
    listening to value
  : ChangeNotifierProvider<BlogModel>
    value: Instance of 'BlogModel'
    listening to value
  : _NestedHook
  : _InheritedProviderScope<BlogModel>
    value: <not yet loaded>
  : ChangeNotifierProvider<BlogModel>
    value: <not yet loaded>
  : _NestedHook
  : _InheritedProviderScope<CategoryModel>
    value: Instance of 'CategoryModel'
    listening to value
  : ChangeNotifierProvider<CategoryModel>
    value: Instance of 'CategoryModel'
    listening to value
  : _NestedHook
  : _InheritedProviderScope<CartModel>
    value: Instance of 'CartModelWoo'
    listening to value
  : ChangeNotifierProvider<CartModel>
    value: Instance of 'CartModelWoo'
    listening to value
  : _NestedHook
  : _InheritedProviderScope<FilterTagModel>
  : Provider<FilterTagModel>
    value: Instance of 'FilterTagModel'
  : _NestedHook
  : _InheritedProviderScope<FilterAttributeModel>
  : Provider<FilterAttributeModel>
    value: Instance of 'FilterAttributeModel'
  : _NestedHook
  : _InheritedProviderScope<UserModel>
  : Provider<UserModel>
    value: Instance of 'UserModel'
  : _NestedHook
  : _InheritedProviderScope<StoreModel>
  : Provider<StoreModel>
    value: Instance of 'StoreModel'
  : _NestedHook
  : _InheritedProviderScope<RecentModel>
  : Provider<RecentModel>
    value: Instance of 'RecentModel'
  : _NestedHook
  : _InheritedProviderScope<SearchModel>
  : Provider<SearchModel>
    value: Instance of 'SearchModel'
  : _NestedHook
  : _InheritedProviderScope<OrderModel>
  : Provider<OrderModel>
    value: Instance of 'OrderModel'
  : _NestedHook
  : _InheritedProviderScope<PaymentMethodModel>
  : Provider<PaymentMethodModel>
    value: Instance of 'PaymentMethodModel'
  : _NestedHook
  : _InheritedProviderScope<ShippingMethodModel>
  : Provider<ShippingMethodModel>
    value: Instance of 'ShippingMethodModel'
  : _NestedHook
  : _InheritedProviderScope<WishListModel>
  : Provider<WishListModel>
    value: Instance of 'WishListModel'
  : _NestedHook
  : _InheritedProviderScope<ProductModel>
  : Provider<ProductModel>
    value: Instance of 'ProductModel'
  : _NestedHook
  : MultiProvider
  : Consumer<AppModel>
    dependencies: [_InheritedProviderScope<AppModel>]
  : _InheritedProviderScope<AppModel>
    listening to value
  : ChangeNotifierProvider<AppModel>
    value: Instance of 'AppModel'
    listening to value
  : App
    state: AppState#a732f
  ...
The relevant error-causing widget was: 
  RefreshIndicator file:///Users/pentazon/Downloads/FluxStore-vendor-1.7.4/source/lib/widgets/home/index.dart:100:12

**Comment by eraldix** [comment]
This is on debug dart
// Copyright 2014 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';

import 'material.dart';
import 'material_localizations.dart';
import 'scaffold.dart' show Scaffold;

/// Asserts that the given context has a [Material] ancestor.
///
/// Used by many material design widgets to make sure that they are
/// only used in contexts where they can print ink onto some material.
///
/// To call this function, use the following pattern, typically in the
/// relevant Widget's build method:
///
/// ```dart
/// assert(debugCheckHasMaterial(context));
/// ```
///
/// Does nothing if asserts are disabled. Always returns true.
bool debugCheckHasMaterial(BuildContext context) {
  assert(() {
    if (context.widget is! Material && context.findAncestorWidgetOfExactType<Material>() == null) {
      throw FlutterError.fromParts(<DiagnosticsNode>[
        ErrorSummary('No Material widget found.'),
        ErrorDescription(
          '${context.widget.runtimeType} widgets require a Material '
          'widget ancestor.\n'
          'In material design, most widgets are conceptually "printed" on '
          "a sheet of material. In Flutter's material library, that "
          'material is represented by the Material widget. It is the '
          'Material widget that renders ink splashes, for instance. '
          'Because of this, many material library widgets require that '
          'there be a Material widget in the tree above them.'
        ),
        ErrorHint(
          'To introduce a Material widget, you can either directly '
          'include one, or use a widget that contains Material itself, '
          'such as a Card, Dialog, Drawer, or Scaffold.',
        ),
        ...context.describeMissingAncestor(expectedAncestorType: Material)
      ]
      );
    }
    return true;
  }());
  return true;
}


/// Asserts that the given context has a [Localizations] ancestor that contains
/// a [MaterialLocalizations] delegate.
///
/// Used by many material design widgets to make sure that they are
/// only used in contexts where they have access to localizations.
///
/// To call this function, use the following pattern, typically in the
/// relevant Widget's build method:
///
/// ```dart
/// assert(debugCheckHasMaterialLocalizations(context));
/// ```
///
/// Does nothing if asserts are disabled. Always returns true.
bool debugCheckHasMaterialLocalizations(BuildContext context) {
  assert(() {
    if (Localizations.of<MaterialLocalizations>(context, MaterialLocalizations) == null) {
      throw FlutterError.fromParts(<DiagnosticsNode>[
        ErrorSummary('No MaterialLocalizations found.'),
        ErrorDescription(
          '${context.widget.runtimeType} widgets require MaterialLocalizations '
          'to be provided by a Localizations widget ancestor.'
        ),
        ErrorDescription(
          'Localizations are used to generate many different messages, labels, '
          'and abbreviations which are used by the material library.'
        ),
        ErrorHint(
          'To introduce a MaterialLocalizations, either use a '
          'MaterialApp at the root of your application to include them '
          'automatically, or add a Localization widget with a '
          'MaterialLocalizations delegate.'
        ),
        ...context.describeMissingAncestor(expectedAncestorType: MaterialLocalizations)
      ]);
    }
    return true;
  }());
  return true;
}

/// Asserts that the given context has a [Scaffold] ancestor.
///
/// Used by various widgets to make sure that they are only used in an
/// appropriate context.
///
/// To invoke this function, use the following pattern, typically in the
/// relevant Widget's build method:
///
/// ```dart
/// assert(debugCheckHasScaffold(context));
/// ```
///
/// Does nothing if asserts are disabled. Always returns true.
bool debugCheckHasScaffold(BuildContext context) {
  assert(() {
    if (context.widget is! Scaffold && context.findAncestorWidgetOfExactType<Scaffold>() == null) {
      throw FlutterError.fromParts(<DiagnosticsNode>[
        ErrorSummary('No Scaffold widget found.'),
        ErrorDescription('${context.widget.runtimeType} widgets require a Scaffold widget ancestor.'),
        ...context.describeMissingAncestor(expectedAncestorType: Scaffold),
        ErrorHint(
          'Typically, the Scaffold widget is introduced by the MaterialApp or '
          'WidgetsApp widget at the top of your application widget tree.'
        )
      ]);
    }
    return true;
  }());
  return true;
}

**Comment by minhcasi** [comment]
@eraldix - it seems the issue cause by caching issue, please check this solution- https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

Please note that we also add the Hungary language on the latest `1.7.5` - could i know which language you are adding? please share the .arb file, we will help to add it as default support - thank you!

**Comment by eraldix** [comment]
I was trying to add Albanian language, but i fix it by tranlating another language that was there. Hope this will not be a problem.

**Comment by eraldix** [comment]
Now im not getting the product showing on the app, i can see the vendors but no product show. Also no categories show. I followed the video tutorial ive done everything like in the video,I dont know what Im doing wrong

**Comment by minhcasi** [comment]
@eraldix - could you help to attach the screenshot and latest config file - we will help for checking - thank you!

**Comment by minhcasi** [comment]
@eraldix - it's better to send us your all source to support@inspireui.com - thank you!

**Comment by minhcasi** [comment]
moved to private email conversation - thank you!

**Comment by Savphai** [comment]
I have the same problem, Could you send me the solution?

**Comment by eraldix** [comment]
> I have the same problem, Could you send me the solution?

Did you have the problem when adding new language?

**Comment by Savphai** [comment]
yes
i try to add khmer language

**Comment by Savphai** [comment]
it seems like when i clicked on new language that i added ,it seems like no config_xx.json file but i already have that file which named config_kh.json and i dont know does it automatically or manually detach to config_kh.json that i created manually.

**Comment by eraldix** [comment]
The best way is to translate a language within there, and you will not have this problem ,it's not perfect but it works

**Comment by Savphai** [comment]
![1](https://user-images.githubusercontent.com/61221970/86881746-307c0a00-c119-11ea-984a-52a6cbf25226.PNG)
![Uploading 2.PNG…]()

**Comment by Savphai** [comment]
i got this problem sir
can you send me the solutions

**Comment by eraldix** [comment]
I fixed mine by translation the japanese into my language

**Comment by Savphai** [comment]
after i clicked to a new language that i added it show this error "No MaterialLocalizations found"

**Comment by Savphai** [comment]
Could send guide me or send me a solution that you did?

**Comment by eraldix** [comment]
- lib/common/tools.dart -> getLanguagesList
- lib/common/constants/images.dart: set a new language flag image
- lib/l10n
- lib/config/config_xx.json (with `xx` is language)
- lib/config/states: state, city, or province of the country.

Check all of these

**Comment by Savphai** [comment]
for this one : lib/common/tools.dart -> getLanguagesList i have add:
      {
        "name": context != null ? S.of(context).cambodia: "Cambodia",
        "icon": ImageCountry.KH,
        "code": "kh",
        "text": "Cambodia",
        "storeViewCode": ""
      },
inside getLanguagelist

**Comment by Savphai** [comment]
for this one : lib/common/constants/images.dart: set a new language flag image i have added

static const String KH = 'assets/images/country/kh.png';

**Comment by Savphai** [comment]
for this one: lib/l10n

i have add : 

/// `Cambodia`
  String get cambodia {
    return Intl.message(
      'Cambodia',
      name: 'cambodia',
      desc: '',
      args: [],
    );
  }

**Comment by Savphai** [comment]
for this one : ib/config/config_xx.json (with xx is language):
i have copy an existing one (config_en.json) and change to config_kh.json

**Comment by Savphai** [comment]
Is that all i have did is correct or not?

**Comment by eraldix** [comment]
Try adding language with localization you have it at tools or something like that

**Comment by Savphai** [comment]
How to do that?

**Comment by Savphai** [comment]
I didn't see it on tools

**Comment by Savphai** [comment]
could you tell me ,what have you done with this issue?
