### ISSUE TITLE
Finally got it to work but super slow loads.

### ISSUE THREAD

**Issue by dragooninasia** [inspireui/support#3624]
So i go it running on my iOS phone, and i plan to start working on the little things, but I noticed its extremely slow.  Even with the json upload on the mstore its extremely slow.  Any thoughts on making it load fasteR?

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as it could not be verified proof of purchase on step 2, please create the new ticket by including the purchased License info - thank you for your time.
