### ISSUE TITLE
Fluxstore Multi vendor app email id and password is incorrect

### ISSUE THREAD

**Issue by avinashverma21** [inspireui/support#3625]
The app was working fine before but from some days it says email id and password is incorrect, what is the issue please help me.
![error](https://user-images.githubusercontent.com/63055526/83948535-8b30f600-a83b-11ea-96dc-ca1b5e646a20.jpg)

**Comment by minhcasi** [comment]
@avinashverma21 - could you try the email to see if it is working 

Also, make sure all the config is done by using this guide - https://docs.inspireui.com/fluxstore/woocommerce-setup/#step-1-setup-rest-api 

Thank you!

**Comment by avinashverma21** [comment]
Not working also when sign up it says you are not allowed, tell me the solution

**Comment by minhcasi** [comment]
@avinashverma21 - could i check if you have active the license from mstore-api plugin - thank you!

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
