### ISSUE TITLE
Error fluxstore list app

### ISSUE THREAD

**Issue by michaelbrinkworth** [inspireui/support#3627]
<img width="320" alt="Screen Shot 2020-06-06 at 7 35 20 am" src="https://user-images.githubusercontent.com/55236695/83953927-f86a7880-a887-11ea-9ca9-d44f7957686b.png">

**Comment by michaelbrinkworth** [comment]
I have probably over 1,000 bugs. Are you guys sure this is running properly lol.

**Comment by philipvu30** [comment]
Hi,

May I ask what version of FluxListing, Listeo, and ListApp Mobile Manager plugin you are using?

**Comment by michaelbrinkworth** [comment]
this was on fluxbuilder

listeo and the latest on all of them?

**Comment by philipvu30** [comment]
Hi,

Currently, the FluxListing on Flux Builder is an old version and it may not fully support the latest Listeo theme. I suggest you should download the source code and configure it manually.

My apologies for this inconvenience.

**Comment by michaelbrinkworth** [comment]
![Screen Shot 2020-06-08 at 8 44 32 pm](https://user-images.githubusercontent.com/55236695/84022221-3f13bc00-a9c9-11ea-96e4-b1a66dcdb7ad.png)
okay well running it locally ive sat here for 10 minutes and no search options show up

**Comment by philipvu30** [comment]
Hi,

I need to know what version of these items FluxListing, Listeo, and ListApp Mobile Manager plugin you are using so I can guess what is the cause. Because the errors you showed belong to old versions. 

Thank you.

**Comment by michaelbrinkworth** [comment]
21 November 19 - flux listing

listeo- latest one
listapp -latest one
--

**Comment by michaelbrinkworth** [comment]
everything is brand new

**Comment by michaelbrinkworth** [comment]
![Screen Shot 2020-06-08 at 9 08 18 pm](https://user-images.githubusercontent.com/55236695/84023855-3375c480-a9cc-11ea-9c71-2ab5324b4c67.png)

**Comment by philipvu30** [comment]
Hi,

Latest Flux Listing version with your config sent to your email. Also, please manually delete the plugin on your site and replace it with this [one](https://github.com/inspireui/support/files/4722691/listapp-mobile-manager.zip).

And please check if your site is correctly configured. Here is what I get when I try to access your site.
[3627.mov.zip](https://github.com/inspireui/support/files/4749873/3627.mov.zip)

Thank you.

**Comment by philipvu30** [comment]
Closed as no response in 2 days. 

If you are happy with our services/support, would you mind rating us on your [download page](https://codecanyon.net/downloads)?
We truly appreciate your help.

**Comment by michaelbrinkworth** [comment]
I want to connect my hypley.com listeo site to fluxstore chat.

So when a user sends messages on hypley.com . IT also shows up inapp.

How do i do this?

also if a person has an account on hypley.com does that mean they have an account on the hypley fluxstore app?I DONT WANT WHATSAPP OR the other dumb stuff. I want users to be able to chat IN APP

**Comment by michaelbrinkworth** [comment]
also your solution didnt work

**Comment by philipvu30** [comment]
Hi,

>I want to connect my hypley.com listeo site to fluxstore chat.
>So when a user sends messages on hypley.com . IT also shows up inapp.

Currently, the FluxStore Listing does not support Listeo Chat feature and it's also not in our development plan.

>also if a person has an account on hypley.com does that mean they have an account on the hypley fluxstore app?

Yes.

>I DONT WANT WHATSAPP OR the other dumb stuff. I want users to be able to chat IN APP

Please find someone who is experienced in Flutter development and implement this feature for you.

Thank you.

**Comment by michaelbrinkworth** [comment]
hi , this source code isnt working....... I redownloaded from theme forest and its not working at all :l

**Comment by philipvu30** [comment]
Hi,

We'll update a new version in couple of hours. Please be patient. Thank you

**Comment by michaelbrinkworth** [comment]
Is it done?

**Comment by philipvu30** [comment]
Hi,

Sorry for the delayed update. 
I sent a new version via your email. Please have a check.
Remember to update your ListApp Mobile Manager to version 1.6.4.

Thank you.

**Comment by michaelbrinkworth** [comment]
![Screen Shot 2020-06-18 at 5 19 49 pm](https://user-images.githubusercontent.com/55236695/84990072-f48ffd80-b187-11ea-9dcb-1baf910340c1.png)
okay but i keep getting build errors before launching

**Comment by philipvu30** [comment]
In pubspec.lock, find this and replace 2.3.5 -> 2.5.4. Then select pub get in the pubspec.yaml file

![image](https://user-images.githubusercontent.com/54442328/84990360-36607a00-b16f-11ea-93db-b56ce7a230a7.png)

**Comment by michaelbrinkworth** [comment]
![Screen Shot 2020-06-19 at 12 45 07 pm](https://user-images.githubusercontent.com/55236695/85091452-c44d6b00-b22a-11ea-9aa3-b67499b171c8.png)


![Screen Shot 2020-06-19 at 12 44 13 pm](https://user-images.githubusercontent.com/55236695/85091457-c7e0f200-b22a-11ea-8ffe-31f9f88ffa6b.png)cant 
![Uploading Screen Shot 2020-06-19 at 12.44.07 pm.png…]()

Cant book, 
cant log out. 
cant login normally,, had to use facebook. 


  @override
  Future logout() {
    // TODO: implement logout
    return null;
  }

  @override
  Future<User> loginGoogle({String token}) {
    // TODO: implement loginGoogle
    return null;
  }

  @override
  Future<String> submitForgotPassword(
      {String forgotPwLink, Map<String, dynamic> data}) {
    // TODO: implement submitForgotPassword
    return null;
  }
}


For some reason there are alot of to dos :l

**Comment by philipvu30** [comment]
Hi,

If you don't mind, please send a support account that is able to see and modify your settings on your website directly to my email: toan@inspireui.com or support@inspireui.com.

I'll help you with checking the issue.
Thanks.

**Comment by michaelbrinkworth** [comment]
done boss, you want github repo access or ?

**Comment by philipvu30** [comment]
No.

Please send me a Wordpress account.

Thank you.

**Comment by michaelbrinkworth** [comment]
hypley.com/wp-admin just reset password

**Comment by philipvu30** [comment]
Hi,

Did you send me the account? I have not received any email from you until now.

**Comment by michaelbrinkworth** [comment]
toan@inspireui.com
--


 hypley.com/wp-admin do password reset

**Comment by michaelbrinkworth** [comment]
howd it go? did you get in?

**Comment by michaelbrinkworth** [comment]
?

**Comment by michaelbrinkworth** [comment]
hopefully we can get this resolved today, let me know if i need to do anything on my side

**Comment by philipvu30** [comment]
Hi,

It seems our booking methods are outdated compared to the latest Listeo version. We'll need more time to develop a new approach to the booking function.

Thank you.

**Comment by michaelbrinkworth** [comment]
oh okay... we are currently working on integrating listeo chat with app. Let us know if we can do anything on our side

**Comment by michaelbrinkworth** [comment]
can you refund me please.

**Comment by philipvu30** [comment]
Sure.

Please submit via this [link](https://help.market.envato.com/hc/en-us/articles/202821460-Can-I-Get-A-Refund-)

**Comment by minhcasi** [comment]
@michaelbrinkworth - you could request this link https://help.market.envato.com/hc/en-us/articles/202821460-Can-I-Get-A-Refund- - thank you!
