### ISSUE TITLE
Fluxstore Listing booking and listing issues

### ISSUE THREAD

**Issue by brianosi** [inspireui/support#3628]
1. I use the latest version of the app and have bought Listeo theme, have created users and added listings, with time slots for testing, I have synced it with the app, however when I make booking, the app doesn't check and use available time slots when I book, the app books any random time at all and the theme accepts it, how can I fix it?

2. The listing from my website list in the order of the latest listing I added instead of listing nearest to user location(  in this case, me).

3.I have been struggling to put the user name on the home screen and other sections of the app like it appears on the profile screen when a user is logged in, how can I do this?

**Comment by michaelbrinkworth** [comment]
hi brianosi, unrelated but im doing a listing app to with same doc. it'd be good to chat, michael@hypley.com

**Comment by michaelbrinkworth** [comment]
https://www.facebook.com/groups/289288585778355/edit/

**Comment by michaelbrinkworth** [comment]
https://www.facebook.com/groups/289288585778355/

**Comment by philipvu30** [comment]
Hi,

Thank you for contacting us. Would you mind giving a more detailed explanation according to your issues with images? As I'm not quite sure I understand what you are trying to express correctly.

My apologies for this inconvenience.

**Comment by philipvu30** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update booking function](https://trello.com/c/SYGLdt0y/54-update-booking-function)

**Comment by brianosi** [comment]
Issue 2. 

The listings are ordered in recently added, instead of order by listings closest to the device, which is a big problem, can I get assistance with this?

**Comment by philipvu30** [comment]
Hi,

>The listings are ordered in recently added, instead of order by listings closest to the device, which is a big problem, can I get assistance with this?

Currently, the app has not supported this feature yet. We soon will implement it but not right now. 

For the booking feature, if you don't mind, please send a support account of your website to my email: toan@inspireui.com. I need to test it before releasing new version.

Thank you.

**Comment by philipvu30** [comment]
Closed as no response in 2 days.

**Comment by jinaldo** [comment]
@brianosi  Hello, Hope you are doing well.
I have same issues like yours.  I have purchased the latest version app and theme.
Is the booking working correctly during the open and close time?
Thanks.

**Comment by jinaldo** [comment]
@philipvu30  Hi, sir. I have purchased the latest flux listing project.
 But I have same issues like brianosi. The users can book anytime. Please help.
