### ISSUE TITLE
[MStore Pro] Confirm Order button is not working real device. Only 15 categories is display on Category tab.

### ISSUE THREAD

**Issue by mkashifrazzaq11** [inspireui/support#363]
**Required Info (please complete the following information):**
 - Product: [e.g. MStore, ListApp]
MStore
 - Your Purchased Code: [get from https://codecanyon.net/downloads]
f8d919b7-3308-4d8c-a454-6b2685fbae9c
(we may not reply if you are not our customer)

**Describe the bug**
I have two issues.
1 - confirm order button is not working on android and iOS device. when I press the confirm order button the text appear on the button is changed to loading but again confirm order appear and order does not place.
2 - We have 20 categories on my website but my app is showing only 15 categories. Please solve this.

**Screenshots**
![20190304_080728000_ios 1](https://user-images.githubusercontent.com/5534583/53700548-733b1d00-3e15-11e9-8091-3b11fde32360.png)

**Additional context**
Add any other detail logs about the problem here.
If possible please share your config.js that use for the app setting

**Comment by luyx2412** [comment]
HI @mkashifrazzaq11 Can you provide your AppConfig.json and Config.js file.

Thanks

**Comment by mkashifrazzaq11** [comment]
here it is.
thanks
[common.zip](https://github.com/inspireui/support/files/2924253/common.zip)

**Comment by luyx2412** [comment]
Hi @mkashifrazzaq11 

Can you provide the MStore version?

Thanks

**Comment by mkashifrazzaq11** [comment]
version is 3.6.7. but I've checked on 3.6.8 and 3.7.0 but same result.

**Comment by luyx2412** [comment]
HI @mkashifrazzaq11 I just checked your config, i saw the error related currency. Please make sure right currency code.
https://www.screencast.com/t/p2VVIzizs27l

Thanks

**Comment by mkashifrazzaq11** [comment]
I changed the currency code PK to PKR, it is working fine on emulator, but on the real devices (android and iOS) the confirm order button is not working.

**Comment by luyx2412** [comment]
Hi @mkashifrazzaq11 Please make sure uninstall app and reinstall again on your real device. Or you can debug with `Reactotron` or `react-native-debugger` to check the issue easier, this is the document https://docs.mstore.io/api-and-project-structure#debug-app-with-reacttotron

Thanks

**Comment by mkashifrazzaq11** [comment]
How can I debug my app with reactotron or react-native-debugger. Please share the links or any good website.

**Comment by luyx2412** [comment]
HI @mkashifrazzaq11 This is the document about debug https://docs.mstore.io/api-and-project-structure#debug-app-with-reacttotron. Please install and in Constant.js file, you can switch 2 debug tools.

Thanks

**Comment by mkashifrazzaq11** [comment]
One problem is Solved.

**Comment by luyx2412** [comment]
Great! :D
