### ISSUE TITLE
Many issues with publish product

### ISSUE THREAD

**Issue by dragooninasia** [inspireui/support#3630]
So I played with the app for the past 3 hours straight.  The app is buggy.  When pulling down the home screen to refresh it would just go down.  I mean it would gitter but not snap back up.   Other issues is load time of content even with config.json on website.  Honestly i am not loving the layout and functions.  I wanted to know what inspireu has in regards to future function and options timeline posted somewhere.

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as it could not be verified proof of purchase on step 2, please create the new ticket by including the purchased License info - thank you for your time.
