### ISSUE TITLE
FLUXSTOR MV Adding phone number to billing adress

### ISSUE THREAD

**Issue by yassiney120** [inspireui/support#3631]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

#3514 

Hello i need small change for exemple
User login from the app using sms ( firebase) 
The number normaly it's saved on username 
I need to save it on billing and shipping number because im using digits plugin for my website so the can synchronize the phone numbre

Thank you
Note: i submit the verification my user name on themeforest yassiney12

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
Thank you for your suggestion, we will add this feature to our backlog for next improvement - very best!

**Comment by yassiney120** [comment]
THANK YOU

**Comment by minhcasi** [comment]
we've moved this request to the same ticket request #3381

it will be updated in `1.7.6` - thank you!
