### ISSUE TITLE
How can add an alert about free delivery eligibility at the checkout time ?

### ISSUE THREAD

**Issue by mmasifashraf** [inspireui/support#3632]
How can add an alert about free delivery eligibility at the checkout time ?
![image](https://user-images.githubusercontent.com/44862509/83964430-cff97300-a8b5-11ea-8dd3-66b77e8dd36e.png)

**Comment by minhcasi** [comment]
Hi, we suggest using the Inspector Tool to customize any UI from your app

![Android Studio_2020-06-08 08-56-16@2x](https://user-images.githubusercontent.com/1459805/83986141-f2e36000-a965-11ea-8bbf-cb0018d1a941.png)
