### ISSUE TITLE
Mstore Pro Expo - debugging issue

### ISSUE THREAD

**Issue by GuyAvraham** [inspireui/support#3635]
Expo Mstore Pro - I am adding console.logs but they are not shown.
Same with debugging network activity.
https://www.loom.com/share/86b44d3cb52c425580e55b3a4b9913e5

With RN apps I am used to debugging this way.
Feels like a cilli question, but how do I watch my logs? Is there a configuration that hide it?

**Comment by luyx2412** [comment]
HI @GuyAvraham In `src/common/Constant.js` line 13. Please change `useReactotron: false` which will disable Reactotron tool and enable default config.
![image](https://user-images.githubusercontent.com/8909619/84041832-805a9a80-a9ce-11ea-927c-79f10b17fd7f.png)

Thanks

**Comment by GuyAvraham** [comment]
Thank you!
