### ISSUE TITLE
How to Edit SMS Login

### ISSUE THREAD

**Issue by harjono-flux** [inspireui/support#3636]
How i can edit the sms notification? I want change "FluxStore" to my store name

![File 08-06-20 09 25 53](https://user-images.githubusercontent.com/64935574/83985031-3dff7200-a96a-11ea-9a6b-6ae0e7102b36.jpeg)

**Comment by minhcasi** [comment]
@harjono-flux - could I check if you have changed your own Firebase and google service file with new name?

**Comment by harjono-flux** [comment]
Oh, can you show me where i must change?
NB: My apps not yet approve by google since 10 days ago

![Screen Shot 2020-06-09 at 21 23 00](https://user-images.githubusercontent.com/64935574/84152543-6769ec00-aa97-11ea-8840-9b1f968145fe.png)

**Comment by minhcasi** [comment]
the status is still Draft, you should Roll Out it to Production

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
