### ISSUE TITLE
problema de pago fluxstore 

### ISSUE THREAD

**Issue by henry2327** [inspireui/support#3637]
![Screenshot_20200607-212333](https://user-images.githubusercontent.com/36794944/83986866-3f9a4d00-a90c-11ea-9143-1ad7d4d1863f.jpg)

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as it could not be verified proof of purchase on step 2, please create the new ticket by including the purchased License info - thank you for your time.

**Comment by henry2327** [comment]
Mercadopago no me funciona para mi país estado unido

**Comment by henry2327** [comment]
[58788457-fluxstore-the-universal-woocommerce-magento-opencart-mobile-app-by-flutter-framework-license.pdf](https://github.com/inspireui/support/files/4743896/58788457-fluxstore-the-universal-woocommerce-magento-opencart-mobile-app-by-flutter-framework-license.pdf)

**Comment by henry2327** [comment]
> Lamento cerrar este boleto ya que no se pudo verificar el comprobante de compra en el paso 2, cree el nuevo boleto incluyendo la información de licencia comprada. Gracias por su tiempo.

Hay esta el pdf

**Comment by henry2327** [comment]
> Lamento cerrar este boleto ya que no se pudo verificar el comprobante de compra en el paso 2, cree el nuevo boleto incluyendo la información de licencia comprada. Gracias por su tiempo.

Hay esta el bolante de compra 
[58788457-fluxstore-the-universal-woocommerce-magento-opencart-mobile-app-by-flutter-framework-license.pdf](https://github.com/inspireui/support/files/4743908/58788457-fluxstore-the-universal-woocommerce-magento-opencart-mobile-app-by-flutter-framework-license.pdf)

**Comment by minhcasi** [comment]
we got your verify file, could you share your `lib/common` and `lib/config` folder so that we could help for checking the issue on your site - thanks

**Comment by henry2327** [comment]
El problema es cuando pongo el api de razorpay y PayPal meda ese problema y veo que razorpay no funciona para estado unido solo stripe

**Comment by henry2327** [comment]
La app dice que tiene stripe pero no lo veo donde esta

**Comment by henry2327** [comment]
![Screenshot_20200608-200034](https://user-images.githubusercontent.com/36794944/84091799-88f9a380-a9c3-11ea-8e79-575f2a2515d5.jpg)
Hey acaso de resolver el problema de pago pero sigue saliendo de la app cuando vas apaga el cliente y no quiero eso

**Comment by philipvu30** [comment]
Hi,

>sigue saliendo de la app cuando vas apaga el cliente y no quiero eso

I quite don't get what you mean. Would you please give a more detailed explanation?

Thank you.

**Comment by henry2327** [comment]
Si claro.. mira te explico cuando entra por la aplicación a comprar un
articulo cuando vas a pagar por la aplicación se sale de la aplicación y
vas a la pagina web mía terminar el pago.. entonces no quiere que salga de
la aplicación  cuando valla apagar

**Comment by philipvu30** [comment]
Hi,

Have you tried to use OnePageCheckOut? In lib/common/config/payments.dart, set this option to true. 

![image](https://user-images.githubusercontent.com/54442328/84118891-ce6aaf00-aa5d-11ea-92b6-aaa8dc3357f2.png)

**Comment by henry2327** [comment]
No echo eso voy a intentar pero no me sale de la aplicación cuando vallan
hacer el pago

**Comment by philipvu30** [comment]
Hi,

Please submit your purchase information via our [Form](http://verify.inspireui.com/) including common and config folders. It will help us assist you better in the future.
Or you could share those folders here (not recommended).

**Comment by henry2327** [comment]
Si me van ayudar a implementar el pago de square .?

**Comment by philipvu30** [comment]
Hi @henry2327 ,

Please use English as Google Translate doesn't quite translate your idea clearly. 
Thank you

**Comment by philipvu30** [comment]
Closed as no response in 2 days. 

If you are happy with our services/support, would you mind rating us on your [download page](https://codecanyon.net/downloads)?
We truly appreciate your help.

**Comment by henry2327** [comment]
Hola.. como puedo desactiva la pasarela de pago que entre por flutter no por la web.?
