### ISSUE TITLE
I Can´t run the app on android studio

### ISSUE THREAD

**Issue by michmj** [inspireui/support#3638]
I have the following message when I am trying to run the app on adroid studio:

Launching lib\main.dart on sdk gphone x86 in debug mode...
Running Gradle task 'assembleDebug'...

Compiler message:
../../../../flutter/.pub-cache/hosted/pub.dartlang.org/provider-4.1.0/lib/src/inherited_provider.dart:136:4: Error: Operator declarations must be preceded by the keyword 'operator'.
Try adding the keyword 'operator'.
  }+
   ^
../../../../flutter/.pub-cache/hosted/pub.dartlang.org/provider-4.1.0/lib/src/inherited_provider.dart:136:4: Error: A method declaration needs an explicit list of parameters.
Try adding a parameter list to the method declaration.
  }+
   ^
../../../../flutter/.pub-cache/hosted/pub.dartlang.org/provider-4.1.0/lib/src/inherited_provider.dart:137:1: Error: Expected '{' before this.
}
^
../../../../flutter/.pub-cache/hosted/pub.dartlang.org/provider-4.1.0/lib/src/inherited_provider.dart:136:4: Error: Operator '+' should have exactly one parameter.
  }+
   ^
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

Compiler message:
../../../../flutter/.pub-cache/hosted/pub.dartlang.org/provider-4.1.0/lib/src/inherited_provider.dart:136:4: Error: Operator declarations must be preceded by the keyword 'operator'.
Try adding the keyword 'operator'.
  }+
   ^
../../../../flutter/.pub-cache/hosted/pub.dartlang.org/provider-4.1.0/lib/src/inherited_provider.dart:136:4: Error: A method declaration needs an explicit list of parameters.
Try adding a parameter list to the method declaration.
  }+
   ^
../../../../flutter/.pub-cache/hosted/pub.dartlang.org/provider-4.1.0/lib/src/inherited_provider.dart:137:1: Error: Expected '{' before this.
}
^
../../../../flutter/.pub-cache/hosted/pub.dartlang.org/provider-4.1.0/lib/src/inherited_provider.dart:136:4: Error: Operator '+' should have exactly one parameter.
  }+
   ^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\Michael\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 882

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\Users\Michael\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 33s
Exception: Gradle task assembleDebug failed with exit code 1

I have the latest version of flutter, android studio and fluxerstore listing. I boughhtit 1 week ago and doesn't work.

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as it could not be verified proof of purchase on step 2, please create the new ticket by including the purchased License info - thank you for your time.

**Comment by minhcasi** [comment]
@michmj - we got your verify purchased - sorry we have closed your previous ticket as you could not provide the verify on step 2 - would you mind to update our rating?

Also, send us your result by running the script `flutter doctor` it seems there is an issue with your Flutter environment

Thank you!

**Comment by minhcasi** [comment]
@michmj - got your reply from another ticket, please help us to raise your all comments just within 1 ticket.

Could I know if you have followed this guide to set up your window - https://www.youtube.com/watch?v=3dv_8UerNpQ ?

Also, make sure to run the `flutter pub get` from the project to run the project. 

Could i know your are running it on Android Studio? Please share the screenshot issue?

Could you consider to update the rating as it is impacting to our business? Thanks for your time

**Comment by minhcasi** [comment]
@michmj - do you any feedback?
