### ISSUE TITLE
[MStore Pro) Confirm Order is not working 

### ISSUE THREAD

**Issue by yosefasad** [inspireui/support#364]
Hello

1.  in version 3.7,    the latest version, When I click on "confirm order" button, the button text appear to be " loading " then the button changed back to "confirm order" appear and order will not be placed.
please see the video .         https://youtu.be/0hxDb_bOjRI

2.   I want to show only COD (Cash on Delivery) option only, How to do this ?  
      I removed the options of Paypal and srtrip from Config.js and still show the options of  paypal
please see the image     https://imgur.com/a/c7KMbkE

3.   in the Delivery options, I want to show only 4 countries in the list to be chosen from 

How to do this ? 
please see the image        https://imgur.com/a/uDOVzMs

**Comment by luyx2412** [comment]
HI @yosefasad 

1. Can you provide your AppConfig.json and Config.js file?

2. You need setup in your website to disable another options, or in `src/containers/Cart/Payment.js` line `303` https://www.screencast.com/t/1bNuqg3viPD

3. In `src/redux/CountryRedux.js` file, you can filter in `fetchAllCountries` function.

Thanks

**Comment by yosefasad** [comment]
1.    Can you provide your AppConfig.json and Config.js file?
>>>>  I have a fresh installation from MStore 3.7 and have the same issue. 
            Please see the video .    https://youtu.be/oQh7sTpBirg

2.  You need setup in your website to disable another options, or in src/containers/Cart/Payment.js line 303 https://www.screencast.com/t/1bNuqg3viPD

>>>>>>> .   it is working now . Thank you .

3.  In src/redux/CountryRedux.js file, you can filter in fetchAllCountries function
>>>>>>> I tried to filter it , I could not make it, can you give me an example on how to filter the countries 


<blockquote><img src="https://i.ytimg.com/vi/oQh7sTpBirg/maxresdefault.jpg" width="48" align="right"><div><img src="/yts/img/favicon_144-vfliLAfaB.png" height="14"> YouTube</div><div><strong><a href="https://www.youtube.com/watch?v=oQh7sTpBirg">MStore-3.7</a></strong></div><div> </div></blockquote>
<blockquote><img src="https://content.screencast.com/users/DangTran4180/folders/Snagit/media/6d70b400-0066-489d-93de-84a066d9ba97/2019-03-04_09-22-00.png" width="48" align="right"><div><img src="/favicon.ico" height="14"> Screencast.com</div><div><strong><a href="https://www.screencast.com/t/1bNuqg3viPD">2019-03-04_09-22-00.png</a></strong></div><div>Shared from Screencast.com</div></blockquote>

**Comment by luyx2412** [comment]
HI @yosefasad 
- Please read the document https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter how to filter. 
- I just checked again the app, but everything worked great. Are you modified the code?

Thanks
