### ISSUE TITLE
Fluxstore: type 'int' is not a subtype of type 'double'

### ISSUE THREAD

**Issue by CodeIncognite** [inspireui/support#3641]
-- Detail Issues: it gives error when Config.json get using server url.
-- Flutter (or React Native) version: Flutter

![73665133-e772e600-46a0-11ea-835e-55b8aeeb0b06](https://user-images.githubusercontent.com/64594025/84006729-d9094380-a98c-11ea-9c3a-55a1e06d0485.png)

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building MainTabs-[LabeledGlobalKey<MainTabsState>#8531e homePageKey](dirty, dependencies: [_DefaultInheritedProviderScope<AppModel>, _InheritedTheme, _DefaultInheritedProviderScope<CartModel>, _LocalizationsScope-[GlobalKey#a79ad], _FocusMarker, MediaQuery], state: MainTabsState#a4e05(ticker inactive)):
type 'int' is not a subtype of type 'double'

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  MainTabs-[LabeledGlobalKey<MainTabsState>#8531e homePageKey] file:///E:/Elsner%20Projects/galleriastreet/lib/app.dart:225:12
When the exception was thrown, this was the stack: 
#0      MainTabsState.renderTabbar.<anonymous closure> (package:fstore/tabbar.dart:311:39)
#1      List.forEach (dart:core-patch/growable_array.dart:285:8)
#2      MainTabsState.renderTabbar (package:fstore/tabbar.dart:295:13)
#3      MainTabsState.renderBody (package:fstore/tabbar.dart:273:27)
#4      MainTabsState.build (package:fstore/tabbar.dart:177:16)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 7082): [galleriast][wocommerce_api][12:47:25.292769] getAsync START [endPoint:customers/317] url:https://galleriast.com/wp-json/wc/v3/customers/317?consumer_key=ck_6b2d6bee1aeb0e25b59f89e4416bfe4f6405eee4&consumer_secret=cs_5df2a8e0bcb688dbd61c7aa34072326bad258deb
D/libc-netbsd( 7082): getaddrinfo: galleriast.com get result from proxy gai_error = 0
D/WindowClient( 7082): Add to mViews: android.widget.FrameLayout{ee0ad7b V.E...... ......I. 0,0-0,0}, this = android.view.WindowManagerGlobal@bcd4474
D/OpenGLRenderer( 7082): CanvasContext() 0x7c13d7b000
D/ViewRootImpl[Toast]( 7082): hardware acceleration is enabled, this = ViewRoot{2a78798 Toast,ident = 1}
I/flutter ( 7082): [galleriast][Tabbar] build
D/OpenGLRenderer( 7082): CanvasContext() 0x7c13d7b000 initialize window=0x7c099f9e00, title=Toast
D/Surface ( 7082): Surface::connect(this=0x7c099f9e00,api=1)
W/libEGL  ( 7082): [ANDROID_RECORDABLE] format: 1
D/mali_winsys( 7082): EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000
D/OpenGLRenderer( 7082): CacheTexture 4 upload: x, y, width height = 0, 0, 73, 67
D/GraphicBuffer( 7082): register, handle(0x7c0ccea200) (w:260 h:83 s:272 f:0x1 u:0x000b00)
D/OpenGLRenderer( 7082): ProgramCache.generateProgram: 68719476736
D/OpenGLRenderer( 7082): ProgramCache.generateProgram: 34359738371
D/GraphicBuffer( 7082): register, handle(0x7c13c80e40) (w:260 h:83 s:272 f:0x1 u:0x000b00)

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building MainTabs-[LabeledGlobalKey<MainTabsState>#8531e homePageKey](dirty, dependencies: [_DefaultInheritedProviderScope<AppModel>, _InheritedTheme, _DefaultInheritedProviderScope<CartModel>, _LocalizationsScope-[GlobalKey#a79ad], _FocusMarker, MediaQuery], state: MainTabsState#a4e05(ticker inactive)):
type 'int' is not a subtype of type 'double'

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  MainTabs-[LabeledGlobalKey<MainTabsState>#8531e homePageKey] file:///E:/Elsner%20Projects/galleriastreet/lib/app.dart:225:12
When the exception was thrown, this was the stack: 
#0      MainTabsState.renderTabbar.<anonymous closure> (package:fstore/tabbar.dart:311:39)
#1      List.forEach (dart:core-patch/growable_array.dart:285:8)
#2      MainTabsState.renderTabbar (package:fstore/tabbar.dart:295:13)
#3      MainTabsState.renderBody (package:fstore/tabbar.dart:273:27)
#4      MainTabsState.build (package:fstore/tabbar.dart:177:16)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
I/System.out( 7082): Check isMmsSendPdu
I/System.out( 7082): PDU read len:49
I/System.out( 7082): MMS PDU Type:123:34
I/System.out( 7082): [OkHttp] sendRequest<<
I/System.out( 7082): Wrong owner. Perhaps a late disconnect
D/Surface ( 7082): Surface::disconnect(this=0x7c099f9e00,api=1)
D/GraphicBuffer( 7082): unregister, handle(0x7c0ccea200) (w:260 h:83 s:272 f:0x1 u:0x000b00)
D/GraphicBuffer( 7082): unregister, handle(0x7c13c80e40) (w:260 h:83 s:272 f:0x1 u:0x000b00)
D/Surface ( 7082): Surface::disconnect(this=0x7c099f9e00,api=1)
D/WindowClient( 7082): Add to mViews: android.widget.FrameLayout{4353bf1 V.E...... ......I. 0,0-0,0}, this = android.view.WindowManagerGlobal@bcd4474
D/OpenGLRenderer( 7082): CanvasContext() 0x7c13d7e800
D/ViewRootImpl[Toast]( 7082): hardware acceleration is enabled, this = ViewRoot{5423d6 Toast,ident = 2}
D/WindowClient( 7082): Remove from mViews: android.widget.FrameLayout{ee0ad7b V.E...... ........ 0,0-260,83}, this = android.view.WindowManagerGlobal@bcd4474
D/OpenGLRenderer( 7082): CanvasContext() 0x7c13d7e800 initialize window=0x7c099f9e00, title=Toast
D/Surface ( 7082): Surface::connect(this=0x7c099f9e00,api=1)
W/libEGL  ( 7082): [ANDROID_RECORDABLE] format: 1
D/mali_winsys( 7082): EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000
D/GraphicBuffer( 7082): register, handle(0x7c13c80e40) (w:260 h:83 s:272 f:0x1 u:0x000b00)
D/GraphicBuffer( 7082): register, handle(0x7c325f0e00) (w:260 h:83 s:272 f:0x1 u:0x000b00)
I/art     ( 7082): Enter while loop.
D/OpenGLRenderer( 7082): ~CanvasContext() 0x7c13d7b000
V/InputMethodManager( 7082): onWindowFocus: io.flutter.view.FlutterView{5f146cc VFE...... .F...... 0,0-720,1280} softInputMode=16 first=false flags=#81810100
D/Surface ( 7082): Surface::disconnect(this=0x7c099f9e00,api=1)
D/GraphicBuffer( 7082): unregister, handle(0x7c13c80e40) (w:260 h:83 s:272 f:0x1 u:0x000b00)
D/GraphicBuffer( 7082): unregister, handle(0x7c325f0e00) (w:260 h:83 s:272 f:0x1 u:0x000b00)
D/Surface ( 7082): Surface::disconnect(this=0x7c099f9e00,api=1)
D/WindowClient( 7082): Remove from mViews: android.widget.FrameLayout{4353bf1 V.E...... ........ 0,0-260,83}, this = android.view.WindowManagerGlobal@bcd4474
I/flutter ( 7082): {id: 317, date_created: 2020-02-25T10:39:17, date_created_gmt: 2020-02-25T08:39:17, date_modified: 2020-03-18T08:27:53, date_modified_gmt: 2020-03-18T06:27:53, email: vikas@elsner.com.au, first_name: Vikas, last_name: Yadav, role: customer, username: vikas@elsner.com.au, billing: {first_name: , last_name: , company: , address_1: , address_2: , city: , postcode: , country: , state: , email: , phone: }, shipping: {first_name: , last_name: , company: , address_1: , address_2: , city: , postcode: , country: , state: }, is_paying_customer: false, avatar_url: https://galleriast.com/wp-content/uploads/2020/03/image_picker_4E2C25A7-6C83-4815-9D30-71CBC8DE5205-575-000000C2AAF9D370.jpg, meta_data: [{id: 12678, key: _yoast_wpseo_profile_updated, value: 1582619957}, {id: 12680, key: wc_last_active, value: 1590796800}, {id: 12763, key: last_login_time, value: 2020-05-20 14:38:13}, {id: 12825, key: icl_admin_language_migrated_to_wp47, value: 1}, {id: 13967, key: icl_admin_language, value: en}, {id: 13969, key: default_pas
D/TelephonyManager( 7082): TelephonyManager:getNetworkOperator.
D/libc-netbsd( 7082): getaddrinfo: google.com get result from proxy gai_error = 0
I/flutter ( 7082): [galleriast][MyConnectivity] online
I/flutter ( 7082): [galleriast][App] internet issue change: {ConnectivityResult.mobile: true}
D/SQLiteConnectionPool( 7082): really get connection
D/SQLiteConnectionPool( 7082): really get connection
D/SQLiteConnectionPool( 7082): really get connection
D/SQLiteConnectionPool( 7082): really get connection
D/SQLiteConnectionPool( 7082): really get connection
D/SQLiteDatabase( 7082): beginTransaction()
D/SQLiteConnectionPool( 7082): really get connection
D/SQLiteDatabase( 7082): endTransaction()
D/SQLiteConnectionPool( 7082): really get connection
D/SQLiteConnectionPool( 7082): really get connection
D/SQLiteConnectionPool( 7082): really get connection
D/SQLiteConnectionPool( 7082): really get connection
D/SQLiteConnectionPool( 7082): really get connection
D/SQLiteDatabase( 7082): beginTransaction()
D/SQLiteConnectionPool( 7082): really get connection
D/SQLiteDatabase( 7082): endTransaction()
D/ActivityThread( 7082): BDC-Calling finishReceiver: IIntentReceiver=2ebad12
D/ActivityThread( 7082): BDC-Calling finishReceiver: IIntentReceiver=54c0beb
I/System.out( 7082): Check isMmsSendPdu
I/System.out( 7082): PDU read len:119
I/System.out( 7082): MMS PDU Type:123:34
I/System.out( 7082): [OkHttp] sendRequest<<
D/TelephonyManager( 7082): TelephonyManager:getNetworkOperator.
D/libc-netbsd( 7082): getaddrinfo: google.com get result from proxy gai_error = 0
I/flutter ( 7082): [galleriast][MyConnectivity] online
I/flutter ( 7082): [galleriast][App] internet issue change: {ConnectivityResult.mobile: true}
I/System.out( 7082): Wrong owner. Perhaps a late disconnect
V/ActivityThread( 7082): SVC-Creating service CreateServiceData{token=android.os.BinderProxy@b005ce3 className=com.onesignal.SyncJobService packageName=com.galleriast intent=null}
E/OneSignal( 7082): Error updating the user record because of the null user id
V/ActivityThread( 7082): SVC-Destroying service com.onesignal.SyncJobService@c88bd99

**Comment by minhcasi** [comment]
@CodeIncognite - could you make sure this is testing on latest Fluxstore `1.7.5` and mstore-api?

**Comment by CodeIncognite** [comment]
we cant upgrade because we have customized it so can you please help on our version..

**Comment by minhcasi** [comment]
@CodeIncognite - try to use Git to merge the latest update  - https://www.youtube.com/watch?v=SWLHKx-xzn0

**Comment by CodeIncognite** [comment]
thank for your support , but i resolved it by my self.
