### ISSUE TITLE
Unable to do login in mstore-pro app

### ISSUE THREAD

**Issue by smdanishali89** [inspireui/support#3644]
Setup woo commerce site and configured the app as well. upon signup, the app is creating users in woo commerce but not signing it in the app, not from the login screen.
When I press the login button it goes on loading and loading without any error.

<img width="407" alt="Screenshot 2020-06-08 at 6 47 46 PM" src="https://user-images.githubusercontent.com/7643171/84037828-8e9dbc00-a9b8-11ea-9851-47f9f5ee9fb1.png">

 Product & version: mstore-pro-3.9.8
 React Native version: react native 0.61.5 
 Testing Simulator: iphone11(13.5)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**
proof of purchasing the license is attached.

**Comment by minhcasi** [comment]
@smdanishali89 - could you share the private common config file via http://verify.inspireui.com - we will help to investigate the issue - thanks

**Comment by smdanishali89** [comment]
shared

**Comment by minhcasi** [comment]
@smdanishali89 - we did not get your sharing - pls resend

**Comment by smdanishali89** [comment]
I shared it again and also sent it on 
support@inspireui.com

**Comment by minhcasi** [comment]
got your verified, could you try to update the latest mstore-api - we will also update the latest release mstore 4.0 soon

**Comment by smdanishali89** [comment]
Sure, will let you know after that soon

**Comment by smdanishali89** [comment]
I update the mstore-api folder and now products are not reflecting in the app anymore

**Comment by minhcasi** [comment]
@smdanishali89 - got your issues, it could be the issue with `3.9.8` - we are going to update new release `4.0.0` today 

We sincerely apologize for the delay and hope you’re staying safe.

**Comment by smdanishali89** [comment]
Hi @minhcasi 
Did you guys update the 4.0 release, as for me I am unable to see 4.0 update in the store.

**Comment by minhcasi** [comment]
sorry, we are working hard to release it on this week, there are some new issues that pending our delivery plan - thank you!

**Comment by minhcasi** [comment]
@smdanishali89 - please help to update the latest release `4.0` to fix the issue 

Let us know if the issue still happens - thank you!
