### ISSUE TITLE
Mstore pro app reduce apk file size 

### ISSUE THREAD

**Issue by ahmedemad2345** [inspireui/support#3645]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

hello I installed the app and its working but there are some problems 1. the app size after extract the apk file using expo is over 50 MB how can I reduce this size 
2. the app takes a long time to open in some devices still on the white screen if there is any method to solve this problem or add preloader screen animation 
3. in some devices when I make order the app reload and can’t make orders from these devices
 4. I have multi-language in my store each language installed in a subdomain with different products and the main language in the main domain so I want to change the API when I changed the language in the app to request data from other API if this thing available in react native please send a docs and I will try to make this myself

Version 3.9.8 (12/02/2020):
Mstore pro react native app

testing on multi-devices

**Comment by stickypages** [comment]
Are you using a debug apk file? Or a production file? 
Debug files are known for slower performance.

**Comment by ahmedemad2345** [comment]
hello thank you 
I'm using expo to build the apk file by running the following command 
expo build:android
so how to export the release file

**Comment by ahmedemad2345** [comment]
ok thank you what about this feature 
4. I have multi-language in my store each language installed in a subdomain with different products and the main language in the main domain so I want to change the API when I changed the language in the app to request data from other API if this thing available in react native please send a docs and I will try to make this myself

**Comment by luyx2412** [comment]
HI @ahmedemad2345 We will release new vesion Mstore 4.0 which will use same your way.

Thanks

**Comment by ahmedemad2345** [comment]
thank you I will be wit for this

**Comment by luyx2412** [comment]
Closed!
P/S: Feel free to reopen or create new issue.

**Comment by ahmedemad2345** [comment]
hello, can you send a docs link for the last update because I can't use the dynamic config to change products in the app when I change the language?
I have the main domain with some products and also subdomain has different products  so I want to make the app change the API when I change the language to display the products based on the selected language
