### ISSUE TITLE
Urgent Help Needed! - Error code 1000 - Apple Sign in - Apple Rejected App

### ISSUE THREAD

**Issue by deep12650** [inspireui/support#3648]
**_Step 1 (require): describe detail issues & screenshots_**
- Sign out apple id from device
- Now try to login with apple id
- cancel the setting pop-up
you will get the error following error:
"Warning: Error: The operation couldn’t  be completed" 

=================================
Other Changes
- WooCommerce Brand Integration in Menu & Tabbar
- While Search keyboard got automatically close, once result fetched. It's very hard to type full words.

===========================
+ Product & version: Fluxstore Pro 1.7.4
+ Flutter (or React Native) version: Flutter
+ Testing Device/Simulator: Any IOS, Specially iPad Pro
+ Screenshot issues (drag the file to attach here): 
![attachment-2200041149396572901Screenshot-0607-065301](https://user-images.githubusercontent.com/12050549/84093963-bdb33c80-aa4f-11ea-9ec8-20700c628c55.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com
<img width="1159" alt="Screen Shot 2020-06-09 at 12 53 42 PM" src="https://user-images.githubusercontent.com/12050549/84094220-66fa3280-aa50-11ea-8a0d-570ecaf07429.png">
_**

**Comment by minhcasi** [comment]
@deep12650 - could you share the detail Apple review log - also help to check our latest release `1.7.5` that also fix the login and performance issues - thank you!

**Comment by deep12650** [comment]
@minhcasi Sure, please find the details below:

From Apple
2. 1 Performance: App Completeness
Guideline 2.1 - Performance - App Completeness


We discovered one or more bugs in your app when reviewed on iPad running iOS 13.5 on Wi-Fi.

- app display an error when we sign in with apple

Next Steps

To resolve this issue, please run your app on a device to identify any issues, then revise and resubmit your app for review.

If we misunderstood the intended behavior of your app, please reply to this message in Resolution Center to provide information on how these features were intended to work.

For new apps, uninstall all previous versions of your app from a device, then install and follow the steps to reproduce the issue. For updates, install the new version as an update to the previous version, then follow the steps to reproduce the issue.

Resources

For information about testing your app and preparing it for review, please see Technical Note TN2431: App Testing Guide.

For a networking overview, please review About Networking.

**Comment by deep12650** [comment]
Please help me close login issue asap, I have to push changes to app store this week.

**Comment by minhcasi** [comment]
@deep12650 
We wanted to thank you for your patience during this busy time. We currently have reduced staff and a significantly higher volume of inquiries. 

Please help to send the project to support@inspireui.com - we will help to investigate the root cause

**Comment by minhcasi** [comment]
Pls keep update on this ticket - thank you!

**Comment by deep12650** [comment]
@minhcasi I just dropped you an email and shared the source code.

**Comment by minhcasi** [comment]
noted with checking, thank you!

**Comment by deep12650** [comment]
Hi @minhcasi 

Could you please update me on this. 

Thanks,
Deep

**Comment by stickypages** [comment]
@minhcasi I too am receiving the response from Apple, **Performance: App Completeness**
I am unsure on how to deal with this. Any suggestions?

**Comment by minhcasi** [comment]
@deep12650 @stickypages - pls help to use the latest release `1.7.6` to fix the issue, there is also an improvement to align the Login form to center to resolve the apple review issue - let us know your checking
