### ISSUE TITLE
[FluxStore WooCommerce] Inventry stock status naming

### ISSUE THREAD

**Issue by and-eee** [inspireui/support#3649]
Hello, could you please let me know how to rename the stock status name, eg change "In Stock" to "Available". Thank you.

**Comment by minhcasi** [comment]
Please change In Stock on 2 files

`lib/model/product`
`lib/intl_en.arb` and related `.arb` file, make sure to install the intl plugin from android studio to generate the language file again 

<img width="1181" alt="Screen Shot 2020-06-10 at 08 46 15" src="https://user-images.githubusercontent.com/1459805/84217633-d9bde900-aaf6-11ea-91c6-c50bf0e97e2f.png">

**Comment by and-eee** [comment]
Perfect, thank you.
