### ISSUE TITLE
Facing issue in Social Login in Multivendor App

### ISSUE THREAD

**Issue by premware-services** [inspireui/support#3651]
Hello,

I downloaded your code and change it's package name first. After that I changed Firebase Credentials, Facebook & Google credentials. And guess what Login fails. Only loading came all the time. Please help me out. I have attached some screenshot with this.
[Issues.zip](https://github.com/inspireui/support/files/4750909/Issues.zip)

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
@premware-services - there is new policy form Google that impact to the login, pls follow the solution on this link https://github.com/inspireui/support/issues/3151

**Comment by premware-services** [comment]
Not Working..

**Comment by premware-services** [comment]
I sended to you attachment..

1=When I am Trying as a normal login but process not go forward.

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/62458442/84366971-36053380-abf1-11ea-9493-1b45bd675cbc.png)

2= When I am trying as a google login Please see attachment.

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/62458442/84367027-49180380-abf1-11ea-9bb7-c7632f03421d.png)

3= When i am trying as a sms Login but process not go forward.

4= When i am trying as a facebook login Please see attachment.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/62458442/84367312-af9d2180-abf1-11ea-98ce-8d60bc6d0780.png)

Please help me out. I have attached some screenshot with this.

**Comment by minhcasi** [comment]
@premware-services - pls follow the guide on this ticket to fix this login issue #3151
