### ISSUE TITLE
[FluxStore WooCommerce] hide 'all items' in Categories page

### ISSUE THREAD

**Issue by and-eee** [inspireui/support#3652]
Hi guys, I've spent quite some time in Flutter Inspector trying to work out how to remove the 'See All' line from the subcategory section of the category page but I haven't managed to work it out. Could you please show me what code needs to be changed to remove it?

[image](https://user-images.githubusercontent.com/63891246/84127451-a2155980-aa82-11ea-8ff2-38b1dfadb769.png)

FYI Flutter Inspector is a feature I'm sure many of us would love to learn to use better but there isn't a lot of information out about it, so more instructional videos or explanations (especially ones including examples) would be most welcome.

Thanks very much for your time.

**Comment by minhcasi** [comment]
@and-eee - please help to check this video https://youtu.be/yGMt3Y20Zmg

I've made the example to guide how to remove the `see all` and using Inspector Tool 🎉

**Comment by and-eee** [comment]
AWESOME! Thanks for the prompt response Minh.
