### ISSUE TITLE
[Fluxstore Pro woocomerce ] Remove extra space on product page

### ISSUE THREAD

**Issue by tjain90** [inspireui/support#3653]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

How to remove extra space on product category page. It seems so much wiered.

![Screenshot_20200609-180103~2](https://user-images.githubusercontent.com/6376301/84148231-4e077680-aa7c-11ea-900b-071dd75f4849.jpg)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by tjain90** [comment]
@minhcasi @trunghieuvn can you please provide an update over this as well. I need to update my app and I cannot launch due to space issue

**Comment by Alnaggar94** [comment]
@minhcasi @trunghieuvn - I have the same problem.

**Comment by tjain90** [comment]
Hi team 
Any update on this ? Its on priority

**Comment by trunghieuvn** [comment]
heelo @tjain90 , @Alnaggar94 i fixed issue  
please add line calculator ratio for gridview item   
\`\`\`  
childAspectRatio = widthContent / (widthContent \* 1.2 + 115);  
\`\`\`  
  
please open file: \`lib/widgets/product/product\_list.dart\`

![](https://user-images.githubusercontent.com/19247680/84533586-a0fa5b80-ad12-11ea-9550-05730fa7303f.png)

**Comment by tjain90** [comment]
It is solved but there is new issue. I cannot use paypal account with new version.
It says invalid credentials. 

![Screenshot_20200615-191638](https://user-images.githubusercontent.com/6376301/84665250-409b3200-af3d-11ea-89a3-7cb254541b23.jpg)

**Comment by tjain90** [comment]
I am using sanbox credentials and leaving return and cancel url as provided in dummy app.

**Comment by minhtruong315** [comment]
Hi @tjain90 can u send me common folder?

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
