### ISSUE TITLE
Fluxstore multivendor, page 404 

### ISSUE THREAD

**Issue by Shiru-kun** [inspireui/support#3656]
**_Step 1 (require): describe detail issues & screenshots_**
When I click  buy in the cart screen it redirects to a webview and show page 404. even with mstore updated and mstore page  installed  
+ Detail Issues: 
+ Product & version:
Multivendor 12-05-2020
+ Flutter (or React Native) version: 
v1.17.3 stable
+ Testing Device/Simulator: 
Samsung a01 OS 10
+ Screenshot issues (drag the file to attach here): 
![Screenshot_20200609-180202](https://user-images.githubusercontent.com/54008441/84172963-e7cf2380-aa7c-11ea-8d89-23c081904ea9.jpg)

![Screenshot_20200609-180156](https://user-images.githubusercontent.com/54008441/84172970-eaca1400-aa7c-11ea-8003-a5cbff912e96.jpg)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhtruong315** [comment]
Hi @Shiru-kun can u upload your source code to github and invite me minhtruong315@gmail.com
I will  help u  check and fix it.
Thanks

**Comment by Shiru-kun** [comment]
sorry im late, check your mail, already invited you

**Comment by minhtruong315** [comment]
Hi @Shiru-kun please change this config like this and try again
<img width="1322" alt="Screen Shot 2020-06-12 at 2 18 34 PM" src="https://user-images.githubusercontent.com/10402500/84476008-b726fe00-acb7-11ea-9226-c68d85e8c795.png">
![Simulator Screen Shot - iPhone 11 - 2020-06-12 at 14 20 00](https://user-images.githubusercontent.com/10402500/84476088-d9b91700-acb7-11ea-9674-6aba5552bbbb.png)

**Comment by Shiru-kun** [comment]
it works just like you showed in the screen, but im still dissatisfied with the fact my client go to the webview to complete their order.

**Comment by minhcasi** [comment]
@Shiru-kun - you could try to customize the app to meet your Client expectation by upgrade to native payment UX (instead of using payment website to support generic multi-payment type)

**Comment by Shiru-kun** [comment]
sorry , i didnt understand, can u show me how can i do that?

**Comment by minhtruong315** [comment]
We only supports payment via webview. it can work on all payment gateway. if you want to use Native Payment, you have to update code. We can't support that. Thanks
