### ISSUE TITLE
Dokan pro features not work on the App

### ISSUE THREAD

**Issue by xsamir** [inspireui/support#3657]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
I bought Dokan pro to solve those two problems, but as the Dokan support team that the problem on my App not on their pro plugin (They are right because the problems solved on the web version).

**1st problem**: That the vender can't publish a product directly, it's kept (pending review), so I need to review the product before it published directly, but with the Dokan pro web version it published directly!

**2nd Problem**: That the order with COD payment methods shows (Pending payment), but I already solve that problem on the web version by editing the payment method code to:
`$order->update_status( 'Processing');`
But that solution won't work on the orders made though the App.

+ Product & version:
MultiVendor 1.7.3

+ Flutter (or React Native) version: 
+ Testing Device/Simulator: On the live version
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**
Done

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhtruong315** [comment]
Hi @xsamir 
- Can you try to add status field on the params to publish the product directly
<img width="892" alt="Screen Shot 2020-06-10 at 11 00 40 AM" src="https://user-images.githubusercontent.com/10402500/84225680-03344000-ab0a-11ea-8455-d5e50b5ab044.png">
- You can change status here
<img width="1179" alt="Screen Shot 2020-06-10 at 11 02 03 AM" src="https://user-images.githubusercontent.com/10402500/84225720-16471000-ab0a-11ea-9c5a-c7c66af1cf3f.png">
Let me know the result when you tried. 
Thanks

**Comment by minhtruong315** [comment]
I dont understand 1st question. 
Social login is user account, it's not  vendor account, so you can't see My Products option

**Comment by xsamir** [comment]
The 1st question is about the product post form when the vendor tries to post a product with leaving the column (Sale Price) empty, it keeps running for endless time.
So the Vendor must put a sale price.

For the second question, I already solved the problem by removing the code line related to (IsVendor).

**Comment by minhcasi** [comment]
@xsamir - pls help to move the latest question to your new ticket  support #3768 - also help us to keep one open ticket instead open multi one - thank you for your time

@minhtruong315 - pls help investigating
