### ISSUE TITLE
Error on yarn install

### ISSUE THREAD

**Issue by SEMION0708** [inspireui/support#3659]
I have some errors when i try to execute yarn install on EXPO.
I tried node js 10 and nodejs 12 but the execution of yarb isntall is not successful as you can see from the attached logs.
[log using nodejs12.txt](https://github.com/inspireui/support/files/4754695/log.using.nodejs12.txt)
[log using nodejs 10.txt](https://github.com/inspireui/support/files/4754696/log.using.nodejs.10.txt)

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
we got your verify, the team will investigate and let you know

**Comment by minhcasi** [comment]
@SEMION0708 - please help to update the latest release `4.0` to fix the issue 

Let us know if the issue still happens - thank you!

**Comment by SEMION0708** [comment]
Kind staff,
thanks the problem has been solved with the new version.

I had tested the plugin with my test site staging.georgettepol.com and now I would like to use the site www.georgettepol.com

Can you change the registration of the plugin because I can't install it?

Thanks so much.
