### ISSUE TITLE
[MStore] (0,warn) is not a function

### ISSUE THREAD

**Issue by kamyp** [inspireui/support#366]
When we see your MStore Pro app on our iPhone, the application works but we have this red error " (0,warn) is not a function .." on every product load.

**Comment by minhcasi** [comment]
Hi, could you let us know:
1. your purchased code
2. screenshot of the issues
3. version of Mstore that you are using

Thank you!

**Comment by kamyp** [comment]
Item Purchase Code:
7e4bc9eb-4a97-458a-ae6f-dd93c0a22054

Last Version: MStore 3.7.0.2
We use your Cebuilder

![screenshot-error](https://user-images.githubusercontent.com/45363608/53789622-28102f80-3f25-11e9-8ecf-e3e238891aba.jpg)


> Thank you!

**Comment by kamyp** [comment]
We have add our purschased code, screenshot and version.
https://github.com/inspireui/support/issues/366 <https://github.com/inspireui/support/issues/366>

Meilleures Salutations - Kind Regards - Mit freundlichen Grüssen - Atento Saludo

CAMILLE-F. 
PASCHE 
Project Manager



Route d'Yverdon 15, 1040 Echallens, Suisse
021 881 22 28 | 078 344 62 62
www.bvisible.ch <https://www.bvisible.ch/> | camille@bvisible.ch <mailto:camille@bvisible.ch> | info@bvisible.ch <mailto:info@bvisible.ch>
Confidentiality Note: This message and any attachments are confidential and intended for the named addressee(s) only. If you have received this message in error, please notify immediately the sender, then delete the message. Any unauthorized modification, edition, use or dissemination is prohibited. The sender shall not be liable for this message if it has been modified, altered, falsified, infected by a virus or even edited or disseminated without authorization.

**Comment by minhcasi** [comment]
https://app.intercom.io/a/apps/xro9xnfd/inbox/inbox/2664005/conversations/21000516870

**Comment by minhcasi** [comment]
https://app.intercom.io/a/apps/xro9xnfd/inbox/inbox/2664005/conversations/21000516870

**Comment by minhcasi** [comment]
Hi, please override this src/common/Tools.js file will be fixed the issues - https://www.dropbox.com/s/l5vav9l0t9l98s3/Tools.js?dl=0
