### ISSUE TITLE
FluxStore - how to change point with discount in cart ?

### ISSUE THREAD

**Issue by huntelar10** [inspireui/support#3661]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

WooCommerce Points and Rewards working ok , but after customer get the point , how he can use it as discount in cart ?

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

the proof in #3006 

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [FluxStore - how to change point with discount in cart ?](https://trello.com/c/uu3MWI6d/58-fluxstore-how-to-change-point-with-discount-in-cart)

**Comment by minhcasi** [comment]
moved to our backlog for next release 1.6.7
