### ISSUE TITLE
Loading problem

### ISSUE THREAD

**Issue by Roupasafricanas** [inspireui/support#3663]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
+ Product & version: 
Fluxstore WooCommerce - Flutter E-commerce Full App - 1.7.5
+ Flutter (or React Native) version: Flutter
+ Testing Device/Simulator: Android Studio
+ Screenshot issues (drag the file to attach here): 

![image](https://user-images.githubusercontent.com/63840938/84232425-a2374880-aac6-11ea-8dec-49de1482ceca.png)
![image](https://user-images.githubusercontent.com/63840938/84232426-a2374880-aac6-11ea-9f97-732410ed09e8.png)

Boa noite 
1)Eu configurei meu aplicativo mas quando aperto em adicionar ao carrinho ou comprar, aparece a mensagem: carregando em vermelho

**Comment by Roupasafricanas** [comment]
![IMG_20200610_032100](https://user-images.githubusercontent.com/63840938/84234012-d4967500-aac9-11ea-945f-19df63ee5091.jpg)

**Comment by Roupasafricanas** [comment]
![Screenshot_2020-06-10-03-45-47-374_com roupasafricanas apps](https://user-images.githubusercontent.com/63840938/84235944-2db3d800-aacd-11ea-8a90-8852392220a4.jpg)

**Comment by Roupasafricanas** [comment]
Any answer please?

**Comment by minhcasi** [comment]
We sincerely apologize for the delay and hope you’re staying safe.

Could you try to edit this value setting from the config file, it could the issue as the app is using total min/max allow amount restriction.

<img width="812" alt="Screen Shot 2020-06-12 at 12 42 40" src="https://user-images.githubusercontent.com/1459805/84468981-36153a00-acaa-11ea-9aa4-73faa1813161.png">

**Comment by Roupasafricanas** [comment]
Don't work. Always Showing "loading*

**Comment by minhcasi** [comment]
@Roupasafricanas - could you try to zip the source and send back ur for checking support@inspireui.com - thank you!

**Comment by Roupasafricanas** [comment]
yes, I'm going to send it in the early evening because I am not with my computer now. Do not close the support please

**Comment by minhcasi** [comment]
confirm

**Comment by Roupasafricanas** [comment]
My computer's in trouble. As soon as i figure it out, I'm going to send it directly to the e-mail. Thank you very much
