### ISSUE TITLE
Fluxstore Woocommerce Product titles

### ISSUE THREAD

**Issue by tozgan** [inspireui/support#3667]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

Hi
1.Product titles should be in line
2.There is a lot of space
https://ibb.co/m4xvRHJ
+ Product & version: 1.7.5+3001
+ Flutter (or React Native) version: Flutter 1.17.1 • channel stable

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by and-eee** [comment]
Having the same issue on 1.7.5

**Comment by trunghieuvn** [comment]
Hi @tozgan ,

1.  To put the titles on the same line, please upload the image of the product into the same size.
2.  please add line calculator ratio for gridview item

```
childAspectRatio = widthContent / (widthContent * 1.2 + 115);
```

please open file: \`lib/widgets/product/product\_list.dart\`

![](https://user-images.githubusercontent.com/19247680/84533586-a0fa5b80-ad12-11ea-9550-05730fa7303f.png)

**Comment by tozgan** [comment]
To put the titles on the same line, please upload the image of the product into the same size.
I can't do this.
Vendor loads products and adds pictures.
We can solve this on the website.
There must be a way here

**Comment by minhcasi** [comment]
@tozgan - we have fixed this issue and upload it into gitlab - than you!

**Comment by tozgan** [comment]
Hi
There is an Image loading error in variation products.

**Comment by minhcasi** [comment]
Sorry I can still see the image on your screenshot?

**Comment by Alnaggar94** [comment]
> Hi
> There is an Image loading error in variation products.
> https://ibb.co/WFz7c9z

@minhcasi - I have the same in some variation products not all products, the image opening fine just the loading bar doesn't disappear after the image load.

**Comment by tozgan** [comment]
Please would you watch this video?

[Android Emulator - Nexus_6_API_26_5554 26.06.2020 12_26_34.zip](https://github.com/inspireui/support/files/4836140/Android.Emulator.-.Nexus_6_API_26_5554.26.06.2020.12_26_34.zip)

**Comment by minhcasi** [comment]
@philipvu30 please help to investigate

**Comment by philipvu30** [comment]
Hi,

My apologies for the delayed response. 
Please replace this file [product_variation.dart.zip](https://github.com/inspireui/support/files/4843687/product_variation.dart.zip) in lib/models/product/product_variation.dart

Thank you.

**Comment by tozgan** [comment]
Hi
@philipvu30  the code worked but gave the error in the picture.
https://ibb.co/dMDX4fr

**Comment by philipvu30** [comment]
Hi,

May I ask what version are you using?

**Comment by tozgan** [comment]
Fluxstore WooCommerce - Flutter E-commerce Full App
woocommerce
Version: 1.7.5

**Comment by philipvu30** [comment]
Hi,

What was the product that you tested? On my device, it's fine.

![image](https://user-images.githubusercontent.com/54442328/85987683-2884e180-ba18-11ea-91e3-c28d41bc24b0.png)

**Comment by tozgan** [comment]
@philipvu30
Hi
The file you sent me is looking for magento.
I removed it
The system is working.
But the error continues in the basket.
Currency is only Turkish lira
https://ibb.co/hfbH9T8

**Comment by philipvu30** [comment]
Remove and add it again. Don't keep the item after changing the code.

**Comment by tozgan** [comment]
@philipvu30 
sorry.
I did not understand

**Comment by philipvu30** [comment]
I meant to remove the item from the cart after you changed the code. Then try to add it again to see if the error still occurs.

**Comment by tozgan** [comment]
@philipvu30
top product variation
the bottom product is simple
https://ibb.co/jg7fv9S

**Comment by philipvu30** [comment]
Hi,

It's hard to guess what your error is without the log. If possible, please send your whole project after running flutter clean via this email: toan@inspireui.com. I'll help you check this issue.

Thank you.

**Comment by tozgan** [comment]
I sent with wetransfer

**Comment by philipvu30** [comment]
Hi,

Replace this file [tools.dart.zip](https://github.com/inspireui/support/files/4850772/tools.dart.zip) in lib/common/tools.dart

**Comment by philipvu30** [comment]
Are you sure you using the latest 1.7.5? As the code is quite different from us.

**Comment by tozgan** [comment]
wonderful
It was dissolved
thank you
