### ISSUE TITLE
(ASK) : Change Menu Drawer Icon

### ISSUE THREAD

**Issue by bakpaorabbit** [inspireui/support#3668]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: How to change menu drawer to hamburger icon in android studio ?
+ Product & version: Fluxstore WooCommerce
+ Flutter (or React Native) version: Latest Flutter 1.17.3-Stable
+ Testing Device/Simulator: Real Device - Xiaomi Redmi Note 8 Pro
+ Screenshot issues (drag the file to attach here): 
![Fluxstore](https://user-images.githubusercontent.com/56450705/84260200-d4d35680-ab43-11ea-88d5-f1392f6fd272.jpeg)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
it's `lib/widgets/home/logo.dart`
