### ISSUE TITLE
Checkout Issue "URGENT"

### ISSUE THREAD

**Issue by DevelopmentHere1** [inspireui/support#3669]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: I can not proceed to payment and keep getting this issue -> https://prnt.sc/sx6cfd
+ Product & version: Latest version from codecanyon market
+ Flutter (or React Native) version: Flutter
+ Testing Device/Simulator: iPhone 11 
+ Screenshot issues (drag the file to attach here): https://prnt.sc/sx6cfd

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhtruong315** [comment]
Hi @DevelopmentHere1 I dont see any products on your website. Please check again
Thanks

**Comment by DevelopmentHere1** [comment]
my site has lots of products https://prnt.sc/sy7v40
But I have not added anything on the main home page on the site 

and my issues are related to checkout not products

**Comment by minhtruong315** [comment]
Hi @DevelopmentHere1 can u send me admin account via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/3669

**Comment by DevelopmentHere1** [comment]
any updates ?

**Comment by minhcasi** [comment]
@DevelopmentHere1 - could you help to check with the hosting provider or double-check if you have enable any security that prevents the POST type data from the plugin? We have debugged and it could not pass this code (due to the POST params is always blank on your site)

<img width="884" alt="Screen Shot 2020-06-16 at 5 21 44 PM" src="https://user-images.githubusercontent.com/1459805/84764109-684ed080-aff7-11ea-80c9-8db8ac423cf9.png">

**Comment by DevelopmentHere1** [comment]
Please check my hosting provider reply 
https://prnt.sc/t11tyx

keep in mind that I have disabled ModSecurity

**Comment by minhtruong315** [comment]
Hi @DevelopmentHere1 it's same. I can't request api from your website. Can you create new website to test?

**Comment by DevelopmentHere1** [comment]
I did, the current own is just installed today

**Comment by minhtruong315** [comment]
Hi @DevelopmentHere1 can u install default opencart website? Dont install any theme or extensions, then install MStore  extension and test again.
Thanks

**Comment by DevelopmentHere1** [comment]
No I didn't install anything with it expect the api

**Comment by DevelopmentHere1** [comment]
so how can we solve the issue :(

**Comment by DevelopmentHere1** [comment]
what is this great support ?

**Comment by minhcasi** [comment]
We wanted to thank you for your patience during this busy time. We currently have reduced staff and a significantly higher volume of inquiries. We’re working as hard as we can to get to your request as soon as possible.

**Comment by minhtruong315** [comment]
Hi @DevelopmentHere1 Your website is not original. it installed other theme
https://icover-sa.com/

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
