### ISSUE TITLE
Disable/hide curency, language, and dark theme - Woo FLutter

### ISSUE THREAD

**Issue by mvin10** [inspireui/support#3670]
Flutter woocommerce APP 

Hello, can you share, how to edit "setting page"
I want to disable/hide curency, language, and dark theme.

<img width="305" alt="Captura de Pantalla 2020-06-10 a la(s) 08 52 07" src="https://user-images.githubusercontent.com/8391284/84283004-b5164100-aaf7-11ea-8343-cd598fec5bb8.png">

Thank you!

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by mvin10** [comment]
Done, i wait for your answer please.
NOTE: I USE **SPANISH** LANGUAGE, THANK YOU

**Comment by mvin10** [comment]
<img width="397" alt="custom icons" src="https://user-images.githubusercontent.com/8391284/84338020-3c939c80-ab58-11ea-958d-17e757008b1b.png">

2. Hi, i need help with this : 1. how do i hide some categories in category grid with icons, i need to hide somes and use custom icons , i tried with builder but code not works, thank you

**Comment by minhcasi** [comment]
@mvin10 - could you try to use the Inspector Tools - https://www.youtube.com/watch?v=yGMt3Y20Zmg - it will help to navigate to the source file then you could customize the UI

You could try to customize this function to show/hide the category ID that youd don't want to show
<img width="1071" alt="Screen Shot 2020-06-12 at 12 46 48" src="https://user-images.githubusercontent.com/1459805/84469238-c94e6f80-acaa-11ea-8d36-c219691dc37c.png">
