### ISSUE TITLE
Sidebar Menu/Drawer Background Color + Category Problem

### ISSUE THREAD

**Issue by gunero** [inspireui/support#3671]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: I have two problems; I can't find any option to change the background color of the sidebar menu/drawer. The second problem is the categories within the drawer (see on the screenshot). 
+ Product & version: FluxNews - Latest version
+ Flutter (or React Native) version: Latest version
+ Testing Device/Simulator: iPhone 11 / Android Studio
+ Screenshot issues (drag the file to attach here): 

I am using FluxNews.

1) I would like to change the background color of the sidebar menu/drawer. Could you tell me exactly what code I have to change for editing the color? 

2) It shows the category name and when I press on it, it expands and the same name appears again, which will then bring me to the category content. How can I make it that it doesn't expand, but directly go to the category content? Because otherwise, it shows the title of the category twice.

![Bildschirmfoto 2020-06-11 um 00 38 07](https://user-images.githubusercontent.com/66735847/84288259-e8021880-ab7b-11ea-861d-e08a5bf800ee.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by gunero** [comment]
I tried to use the Inspector already. I was also reading the other issues here on Github. Unfortunately, the code different from FluxStore and so on.

It would be really helpful if someone could show me exactly where I have to change/insert the specific code to change the background color of the sidebar.

Also about the categories. People need to press on the category name, to expand the category and see the same category name again (see on the screenshot). How can I change this?

**Comment by gunero** [comment]
I could figure out to change the background color.

Now about the problem with the categories? can anyone reply please?

**Comment by vumanhsn97** [comment]
@gunero 
In lib/menu.dart: check in showCategories and getChildren function in this file: 
[menu.dart.zip](https://github.com/inspireui/support/files/4768578/menu.dart.zip)

**Comment by gunero** [comment]
Awesome, worked!
