### ISSUE TITLE
Images not showing Fluxstore woocommerce

### ISSUE THREAD

**Issue by kweyamba** [inspireui/support#3673]
Product images are not showing in the app.
+ Did basic troubleshooting but images dont appear on the app
![image](https://user-images.githubusercontent.com/66207250/84299747-d4f34680-ab83-11ea-9852-24d793b1ff03.png)

**_Step 2 (require):

**Comment by minhcasi** [comment]
@kweyamba - pls help us to submit the verify purchase via http://verify.inspireui.com/ - pls don't share the purchase screenshot here - thank you for your time!

**Comment by kweyamba** [comment]
@minhcasi i sent the submission. Thanks

**Comment by kweyamba** [comment]
@minhcasi : I sent the form yesterday. Do Yu have any update on this issue.

**Comment by minhcasi** [comment]
@kweyamba - pls help to check this guide to optimize the image  - https://docs.inspireui.com/fluxstore/performance/#2-image-optimization
