### ISSUE TITLE
How to set Default Country ? FluxStore WooCommerce

### ISSUE THREAD

**Issue by netuseruk** [inspireui/support#3674]
Hello Author, 
I have two issues , please guide me .

1. How to set default country as India only . No need any drop down selection .
![image](https://user-images.githubusercontent.com/66378474/84311398-de2ee400-ab80-11ea-9865-07745ec7b8e4.png)

2. How to update app to latest version ?

**Comment by minhcasi** [comment]
Thank you for your feedback 

1. To limit the country list from the Delivery screen, open `lib/common/config/payments.dart` and update the `DefaultCountryISOCode`.
<img width="1428" alt="default-shipping" src="https://user-images.githubusercontent.com/1459805/84340119-232b3880-abca-11ea-81d6-02666d164738.png">


2. pls help to check this blog https://medium.com/@inspireui/how-to-upgrade-fluxstore-projects-by-using-git-cebde7489ea6

**Comment by netuseruk** [comment]
Thanks for your valuable solution .
Default country issue resolved. 

I am login in Gitlab but there is nothing .
Should I need to send purchase code to access that page ?

**Comment by sketchuprzr** [comment]
@netuseruk 

![image](https://user-images.githubusercontent.com/60021696/84433911-bcdcff00-ac37-11ea-94ad-81682ae88f57.png)

https://docs.google.com/forms/d/e/1FAIpQLSeuBqUkScy42V7KKhfNPj0fl581anrB1mWkbMa3p2WQt7fhfw/viewform

**Comment by netuseruk** [comment]
Issue resolved .
