### ISSUE TITLE
FluxPro Magento images  Bad state: Failed to load

### ISSUE THREAD

**Issue by amjadalfawal** [inspireui/support#3676]
![image](https://user-images.githubusercontent.com/37481122/84317632-c7cf5b00-ab75-11ea-94e7-09ff496620c8.png)
images and price not showing from outside but they are showing in the product details

![image](https://user-images.githubusercontent.com/37481122/84317846-24cb1100-ab76-11ea-821f-b5c2635f8430.png)

error
![image](https://user-images.githubusercontent.com/37481122/84317899-3ca29500-ab76-11ea-8403-98a26c3ada31.png)

the image URLs working on browser

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by amjadalfawal** [comment]
I found out there is a problem with the URL of the images I fixed it by adding this towline 
![image](https://user-images.githubusercontent.com/37481122/84442302-07fe0e80-ac46-11ea-8233-8e30ccc7a8e8.png)
