### ISSUE TITLE
[ Fluxlisting ] - Apple login ERROR

### ISSUE THREAD

**Issue by iamar1k92** [inspireui/support#3677]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: Apple login is not working on fluxlisting app.
Firebase apple login is enabled
realtime database is read and write =true;
tried to delete access of the app from setting

+ Product & version: fluxlisting 1.4.1
+ Flutter (or React Native) version: Flutter v1.17.2 & dart 2.8.3
+ Testing Device/Simulator: IPhone 11 Pro Max
+ Screenshot issues (drag the file to attach here): 

![bcf47817-f994-428b-a845-1865200f1e09](https://user-images.githubusercontent.com/58983166/84320780-a4afa600-ab8b-11ea-992c-82e094cce138.jpeg)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@iamar1k92 - could i check if you have active the mstore-api plugin License?

**Comment by minhcasi** [comment]
@iamar1k92 - could you try to test on real device and make sure your Apple account is Paid Developer 99usd/y to active this feature from Apple

**Comment by iamar1k92** [comment]
Yes apple id is paid and i also tried to test on real device, still fails...

**Comment by philipvu30** [comment]
Hi,

Please refer to this [issue](https://github.com/inspireui/support/issues/3474#issuecomment-641688081).

**Comment by iamar1k92** [comment]
not worked!

**Comment by iamar1k92** [comment]
![image](https://user-images.githubusercontent.com/58983166/84484550-5944e700-acb4-11ea-9b9f-bb4b4658fe11.png)
  
![image](https://user-images.githubusercontent.com/58983166/84484589-6530a900-acb4-11ea-9b80-2e1cfbf225b7.png)

![image](https://user-images.githubusercontent.com/58983166/84484683-842f3b00-acb4-11ea-836f-284e7130b5eb.png)

**Comment by iamar1k92** [comment]
![image](https://user-images.githubusercontent.com/58983166/84484747-9ad59200-acb4-11ea-9d9e-8c19290055be.png)

**Comment by philipvu30** [comment]
Hi,

Run flutter clean and send your project to toan@inspireui.com. I'll help you check the issue.

**Comment by iamar1k92** [comment]
okay

**Comment by philipvu30** [comment]
Hi,

Please replace these 2 files
- lib/models/user.dart [user.dart.zip](https://github.com/inspireui/support/files/4777851/user.dart.zip)
- lib/services/woo_commerce.dart [woo_commerce.dart.zip](https://github.com/inspireui/support/files/4777853/woo_commerce.dart.zip)

**Comment by iamar1k92** [comment]
Thank you so much @philipvu30, you are the man <3. Perfectly working

**Comment by philipvu30** [comment]
I'm glad I was able to help.

If you are happy with our services/support, would you mind rating us on your [download page](https://codecanyon.net/downloads)?
We truly appreciate your help.

**Comment by iamar1k92** [comment]
well after doing that, it fixed my apple login but. I think i have lost my email login.

having Error: getNonce on login, and different error on registration

before email logins were working

**Comment by philipvu30** [comment]
Hi,

If you don't mind, please provide a support account + your project after running the command flutter clean to my email: toan@inspireui.com. I'll help you check the problem.

**Comment by philipvu30** [comment]
Hi,

Please replace this [file](https://github.com/inspireui/support/files/4790374/woo_commerce.dart.zip) in lib/services/woo_commerce.dart

**Comment by iamar1k92** [comment]
All is well, on android, the notifications are working fine i can see them on notification screen in debug mode but when i export the release it also works on emulator, but on real device on release mode, they dont show in notification bar

**Comment by philipvu30** [comment]
Hi,

>but on real device on release mode

Do you mean your app already published to the playstore?

**Comment by iamar1k92** [comment]
No i am talking about the simple release mode by flutter.

i have added the sha1 & sha256 keys on playstore. I can login as well no issues at all.

I have tested the notifications on release mode on emulator it works perfectly, but the same release version is tested on physical device, notifications are received on notification panel, but dont show in app notification page.

**Comment by philipvu30** [comment]
Hi,

It's fine for me on the Samsung S9+ device on release mode.
But just to make sure. Please follow these steps
1. Replace this [notification.dart.zip](https://github.com/inspireui/support/files/4802299/notification.dart.zip) in lib/models/notification.dart
2. Follow this [official document](https://flutter.dev/docs/deployment/android#configure-signing-in-gradle).

**Comment by minhcasi** [comment]
@iamar1k92 - we notice that you are distributing our product on Fiverr as illegal - we will stop support for any further ticket
