### ISSUE TITLE
[Fluxstore Pro 1.7.5] - "Cart" Label of Bottom Navigation Bar not on the same line

### ISSUE THREAD

**Issue by Alnaggar94** [inspireui/support#3678]
- Hi, When I add a label to the Bottom Navigation Bar the "Cart" label not in the same line the text a little bit down more than the others(See the screenshots), I tried to change the height and padding in Tabbar.dart but without luck.

![ssss](https://user-images.githubusercontent.com/49800146/84321297-92c60700-ab7b-11ea-86ad-ff127da5ae67.JPG)

- I verified my purchase code through - http://private.inspireui.com

**Comment by minhcasi** [comment]
@Alnaggar94 - we will help to check and let you know :)

**Comment by minhcasi** [comment]
@Alnaggar94 - please fix this file

<img width="615" alt="Screen Shot 2020-06-12 at 14 11 49" src="https://user-images.githubusercontent.com/1459805/84475398-b04bbb80-acb6-11ea-9df3-3306b024bc2d.png">

**Comment by Alnaggar94** [comment]
@minhcasi - Thanks man, It's working perfectly now. And I have a few questions because it becomes so long after adding the text label: 

-  How can I change the height between the text and the icon?

- How can I change the height for the overall Bottom Navigation Bar?

- 
![c4](https://user-images.githubusercontent.com/49800146/84582435-84365480-adf4-11ea-9570-5ec81ff8ac65.JPG)

**Comment by minhcasi** [comment]
@Alnaggar94 - I'm not sure if you could customize this setting:

<img width="918" alt="Screen Shot 2020-06-16 at 17 54 46" src="https://user-images.githubusercontent.com/1459805/84766114-794d1100-affa-11ea-9e2a-286aa5a6a996.png">

**Comment by Alnaggar94** [comment]
@minhcasi - I tried but without luck, I just wanna decrease the height between the text and the icon, I will appreciate your help 👍
