### ISSUE TITLE
Showing state instead of City

### ISSUE THREAD

**Issue by mmasifashraf** [inspireui/support#3679]
Showing state instead of City in the address screen from google map. 

And state is not filling up. 

How to resolve? ![image](https://user-images.githubusercontent.com/44862509/84328617-205d2300-ab8b-11ea-967f-903f37fd6583.jpeg)

**Comment by minhcasi** [comment]
@mmasifashraf - you could try to edit this file to add more state in India

<img width="797" alt="Screen Shot 2020-06-11 at 11 24 09" src="https://user-images.githubusercontent.com/1459805/84344880-17457380-abd6-11ea-9fe0-31bc8c83937f.png">

Could i ask if you have the translation .ard Hindi for India language?

**Comment by mmasifashraf** [comment]
@minhcasi  which json file I have to use for Indian States? it is state_in right? or I have to change it to the same structure  of Vietnam ?

I can give you the Hindi Language file.

**Comment by minhcasi** [comment]
yes add the new file `state_in.json` - please also help to share this file and the .arb file after you finish the editing, we will add it as official support - thank you!

**Comment by mmasifashraf** [comment]
Its resolved by correcting the result parameters as 
admin_area_level_1  for state 
And 
Locality for city on place_picker.dart
