### ISSUE TITLE
error on cebuilder

### ISSUE THREAD

**Issue by osamasparky** [inspireui/support#368]
**Mandatory Info (please complete the following information):**
 - Product: [e.g. MStore, ListApp]  
 MStore
 - Your Purchased Code: [get from https://codecanyon.net/downloads] 
         Purchase code: da4e5510-501d-456f-9d1d-fbbcdd24f102 
(we may not reply if you are not our customer)

**Describe the issues**
When i click on customization i got error on cebuilder 
**Screenshots**
![image](https://user-images.githubusercontent.com/36470035/53803426-c1efd080-3f55-11e9-9c49-f4d92a8d6d5d.png)

**Additional context**
Add any other detail logs about the problem here.

**Comment by minhtruong315** [comment]
Hi @osamasparky I am updating CeBuilder for this issue

**Comment by osamasparky** [comment]
when you think you will finish that

**Comment by osamasparky** [comment]
Dear All this counted from my support period - when you will finish that

**Comment by osamasparky** [comment]
hello

**Comment by minhtruong315** [comment]
I am updating to fix this issue. thanks for waiting

**Comment by minhtruong315** [comment]
Pls update newest cebuilder to fix this issue. thanks

**Comment by osamasparky** [comment]
I did and got another error 
https://github.com/inspireui/support/issues/395
