### ISSUE TITLE
Checkbox in product page 

### ISSUE THREAD

**Issue by mercadocerouno** [inspireui/support#3680]
How can i add a checkbox in the product page?

![checkpoint](https://user-images.githubusercontent.com/66270970/84331169-5fb15280-ab3e-11ea-8e02-4645a34a34b0.png)

**Comment by minhcasi** [comment]
@mercadocerouno could i know which type of checkout you would like to add?

You could try to use the Inspector Tool to customize any UI from app - https://www.youtube.com/watch?v=yGMt3Y20Zmg
