### ISSUE TITLE
fluxstore MV shipping method not showing

### ISSUE THREAD

**Issue by TAMS2018** [inspireui/support#3681]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues:  fluxstore MV shipping method not showing
+ Product & version: 1.7.5
+ Flutter (or React Native) version:  
+ Testing Device/Simulator: emulator
+ Screenshot issues (drag the file to attach here): 

![image](https://user-images.githubusercontent.com/66580664/84342246-ae5efb00-abd7-11ea-9e90-3f4c51cc51cd.png)

![image](https://user-images.githubusercontent.com/66580664/84342527-5aa0e180-abd8-11ea-81fc-f0696d0fc8ec.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**
![image](https://user-images.githubusercontent.com/66580664/84342572-773d1980-abd8-11ea-85d5-cc4b7abeae20.png)

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@TAMS2018 - pls help to share the config folder via http://verify.inspireui.com/ so that we could reproduce the issue on your site 

or you could share it here if don't mind.

**Comment by minhcasi** [comment]
moved to email support
