### ISSUE TITLE
No Products Displaying FluxStore MV with wcfm 

### ISSUE THREAD

**Issue by TAMS2018** [inspireui/support#3682]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues:  product not displaying with wcfm market place but when i activate the dokan platform the issue got resolved. all plugins required are installed properly.

+ Product & version: 1.7.5
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: emulator & actual device
+ Screenshot issues (drag the file to attach here): 

![image](https://user-images.githubusercontent.com/66580664/84342926-60e38d80-abd9-11ea-8093-f237723043b0.png)
![image](https://user-images.githubusercontent.com/66580664/84343300-55dd2d00-abda-11ea-8520-418766bae516.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

![image](https://user-images.githubusercontent.com/66580664/84342988-8ff9ff00-abd9-11ea-9264-175fd898c5c9.png)

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@TAMS2018 - pls help us to move your all conversation in same ticket #3681
