### ISSUE TITLE
Fluxstore MV 1.7.5 + WCFM issues

### ISSUE THREAD

**Issue by mixkey23** [inspireui/support#3683]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
Please refer to my initial issue number #3351 for licence code. 

My first issue was closed, due to inativity, I just had problems with my Internet provider so could not read the last mesages and then was closed. 

So im opening this new issue, because I still having problems despite I have upgraded to 1.7.4

If you think guys, that its better to fix this issues on 1.7.5, let me know and i wiil commit to my repo

Issues:

* On home screen, some product list by categories are showing blank. 
![83921938-111e4580-a745-11ea-8891-6bec42d389fb](https://user-images.githubusercontent.com/62155503/84352457-fbfd4880-ab82-11ea-8bf4-50a1724bdcd0.jpeg)

In console is showing an error

* I have setup a couple of banners on home and set a category link on some of them when I clic, it shows "No products" where actually they have products. 
![Screenshot_20200611_013124_com merkalat io](https://user-images.githubusercontent.com/62155503/84352710-74640980-ab83-11ea-960f-1f5f0d0c1054.jpg)
![Screenshot_20200611_013142_com merkalat io](https://user-images.githubusercontent.com/62155503/84352725-79c15400-ab83-11ea-9389-e7635fb672ac.jpg)

* On categories tab, some of them shows "No products" despite have items on it

![83924665-c30c4080-a74a-11ea-8411-a3cd6c9ad6d3](https://user-images.githubusercontent.com/62155503/84352957-dde41800-ab83-11ea-9750-4f87d43e5a7e.jpeg)
![83924252-cbb04700-a749-11ea-9841-ade56c8e6586](https://user-images.githubusercontent.com/62155503/84352987-ea687080-ab83-11ea-9543-2e7c768f66cf.jpeg)

* On stores product's tab, the list is loaded but the refreshner is working wrong way because it keep loading in a loop and never reach end. If have 10 products they are loaded over and over when swipe Up. 
![Screenshot_20200611_014018_com merkalat io](https://user-images.githubusercontent.com/62155503/84353579-0f111800-ab85-11ea-9be2-d6a6b238d1b3.jpg)
![Screenshot_20200611_014139_com merkalat io](https://user-images.githubusercontent.com/62155503/84353597-159f8f80-ab85-11ea-85ca-f8c844078c9d.jpg)

* Product's card images height, are no fixed so overflow occurs random on any view/screen with product card. Need to set a fixed height 1:1 if possible so we can get a clean layout
![83924274-db2f9000-a749-11ea-8b9d-ed987c152e0c](https://user-images.githubusercontent.com/62155503/84353829-74650900-ab85-11ea-8569-ab950ed627dd.jpeg)

* Sidebar menú Store button do nothing

* isCaching ist not working, what i have to modify like in 1.7.5 to make it work?

+ Product & version:
Fluxstore MV 1.7.4
+ Flutter (or React Native) version: 
Flutter 1.17.13
+ Testing Device/Simulator: 
Real: Huawei Mate 20 pro
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhtruong315** [comment]
Hi @mixkey23 can u check your issues on version 1.7.5? if you have any issues. please add me to your  repo: minhtruong315@gmail.com

**Comment by mixkey23** [comment]
> Hi @mixkey23 can u check your issues on version 1.7.5? if you have any issues. please add me to your repo: [minhtruong315@gmail.com](mailto:minhtruong315@gmail.com)
> I will help u fix on new version. The old version is not stable
> Thanks

Ok I will test my config on 1.7.5 and commit the changes to my repo

**Comment by mixkey23** [comment]
> 
> 
> Hi @mixkey23 can u check your issues on version 1.7.5? if you have any issues. please add me to your repo: [minhtruong315@gmail.com](mailto:minhtruong315@gmail.com)
> I will help u fix on new version. The old version is not stable
> Thanks

Ok i made the test on 1.7.5, and the issues are the same i have mention above in 1.7.4 so actually  its seem to me that you have not fixed yet on 1.7.5

* Other issue is on store chat message push notification, if we look on profile's messages menu its there but no push notification.

Please fix it asap, cause i need to release my client's app

I made commit to my repo with my config on v1.7.5, you already are on my repo as collaborator

**Comment by minhtruong315** [comment]
@mixkey23 I'm ready to support you now. Did you invite me to your repo?

**Comment by mixkey23** [comment]
> @mixkey23 I'm ready to support you now. Did you invite me to your repo?

Yeah I already invite you

**Comment by minhtruong315** [comment]
@mixkey23 can u send me the url, I dont see  any invitation
Thanks

**Comment by mixkey23** [comment]
> @mixkey23 can u send me the url, I dont see any invitation
> Thanks

Ok I have sent a new invitation to you as collaborator

**Comment by mixkey23** [comment]
> @mixkey23 I'm ready to support you now. Did you invite me to your repo?

I haven't heard from you in a few days, it's been almost a month since I posted my first issue and I haven't been able to launch my client's app due to the issues found in the app. 

I recommend to fix everything in one version and when you are sure that everything works then release the next version, since you are practically forcing us developers to update every time from version to version to solve issues but there are still other issues.

I have requested access to the github repository to test new versions myself and have received no response to that. 

Please fix the app issues, I am using version 1.7.5 and I need to fix the issues mentioned in this report. 

My client needs the app and I'm already at the deadline.  If my customer cancels my services, I will have to request a refund of my purchase.

**Comment by minhtruong315** [comment]
@mixkey23 can u send me the link? I dont remember which repo that you added me.
Thanks

**Comment by mixkey23** [comment]
> 
> 
> @mixkey23 can u send me the url, I dont see any invitation
> Thanks

ok, this is the link: 
https://github.com/mixkey23/fluxstore-mv

**Comment by minhtruong315** [comment]
@mixkey23 pls pull the source code. I fixed products in home screen
![Simulator Screen Shot - iPhone 11 - 2020-06-22 at 11 38 44](https://user-images.githubusercontent.com/10402500/85249126-1b4a7e80-b47d-11ea-8a04-ff273af5d57b.png)

**Comment by mixkey23** [comment]
Ok I will pull the code, did you fix the products image height?

**Comment by minhtruong315** [comment]
Product image height is fixed on our source code. you can check it on next release

**Comment by mixkey23** [comment]
> 
> 
> > @mixkey23 can u send me the url, I dont see any invitation
> > Thanks
> 
> ok, this is the link:
> https://github.com/mixkey23/fluxstore-mv



> 
> 
> Product image height is fixed on our source code. you can check it on next release

I understand, so all the above issues i have are fixed on next release ?

i can upgrade and all these are fixed, thats what you mean

**Comment by minhtruong315** [comment]
Yes. You can  pull  the source code to check issue 1,2,3,4 now. other issues will be available on next release.

**Comment by mixkey23** [comment]
Ok what do you recommends, stay on 1.7.5 or upgrade to next

**Comment by minhtruong315** [comment]
We're working hard on Fluxstore MV to fix issues and update more features. We will release it soon. You can check your issues again when you release the new version.
Currently you only can check issue 1,2,3,4 on your source code.

**Comment by aishema2000** [comment]
Dear @minhtruong315 can you please share what you did to fix the issue especially issue Number 1???? I also have a blank home screen, I am using wcfm.

**Comment by minhtruong315** [comment]
I fixed this function in lib/widgets/frameworks/wcfm/index.dart
```
@override
  Product updateProductObject(Product product, Map json) {
    if (json["store"] != null && json["store"]["vendor_id"] != null) {
      product.store = Store.fromWCFMJson(json["store"]);
    }
    return product;
  }
```

**Comment by aishema2000** [comment]
> I fixed this function in lib/widgets/frameworks/wcfm/index.dart
> 
> ```
> @override
>   Product updateProductObject(Product product, Map json) {
>     if (json["store"] != null && json["store"]["vendor_id"] != null) {
>       product.store = Store.fromWCFMJson(json["store"]);
>     }
>     return product;
>   }
> ```

Perfect!!! It works like a charm.

**Comment by mixkey23** [comment]
> 
> 
> We're working hard on Fluxstore MV to fix issues and update more features. We will release it soon. You can check your issues again when you release the new version.
> Currently you only can check issue 1,2,3,4 on your source code.

Hi @minhtruong315 i tested and it works

> 
> 
> We're working hard on Fluxstore MV to fix issues and update more features. We will release it soon. You can check your issues again when you release the new version.
> Currently you only can check issue 1,2,3,4 on your source code.

@minhtruong315  I understand, i tested the source code and its working well.

Question: How i can change the tabbar items ?

I have tried with fluxbuilder and copy the config.json to my project but it keep loading the default layout.

**Comment by minhtruong315** [comment]
@mixkey23 You can check if you are enable or disable isCaching.
<img width="926" alt="Screen Shot 2020-06-24 at 2 17 26 PM" src="https://user-images.githubusercontent.com/10402500/85513693-77500700-b625-11ea-8b5a-787a0ad407f0.png">

**Comment by mixkey23** [comment]
> @mixkey23 You can check if you are enable or disable isCaching.
> <img alt="Screen Shot 2020-06-24 at 2 17 26 PM" width="926" src="https://user-images.githubusercontent.com/10402500/85513693-77500700-b625-11ea-8b5a-787a0ad407f0.png">

@minhtruong315 yeah, I set it true and upload the file to mstore plugin

**Comment by minhtruong315** [comment]
Hi @mixkey23 I only support you issues for integrating with your website. I dont support for customize code.
Thanks

**Comment by mixkey23** [comment]
> Hi @mixkey23 I only support you issues for integrating with your website. I dont support for customize code.
> Thanks

I just wanted to know how I could access the store phone.  But thanks for the support
