### ISSUE TITLE
Fluxstore "aramex" shipping method showing zero value but in wocommerce website its getting the right value  

### ISSUE THREAD

**Issue by andyodoo** [inspireui/support#3684]
**_Step 1 (require): describe detail issues & screenshots_**
we configured fluxstore to work with our  wordpress wocommerce website 
and we notice the following issue 

that our "aramex" shipping method cost is not the same as our website 
in the mobile app its always display zero value 
but the same address when entered in our website its giving 24 SAR 
see images attached for both mobile shipping and website  

+ Detail Issues: 

+ Product & version:
 FluxStore WooCommerce 
+ Flutter (or React Native) version: 
Flutter 
+ Testing Device/Simulator: 
iOS / android 
+ Screenshot issues (drag the file to attach here): 
<img width="471" alt="Screen Shot 2020-06-11 at 9 31 48 AM" src="https://user-images.githubusercontent.com/50452375/84352641-61265d80-abc6-11ea-9a3b-813424fb45c0.png">
<img width="471" alt="Screen Shot 2020-06-11 at 9 24 40 AM" src="https://user-images.githubusercontent.com/50452375/84352670-6d121f80-abc6-11ea-827e-086aa6370d23.png">
<img width="1326" alt="Screen Shot 2020-06-11 at 9 34 13 AM" src="https://user-images.githubusercontent.com/50452375/84352838-ba8e8c80-abc6-11ea-9468-b4b34f9c89c8.png">

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

<img width="1326" alt="Screen Shot 2020-06-11 at 9 37 08 AM" src="https://user-images.githubusercontent.com/50452375/84353089-2a047c00-abc7-11ea-9f0e-987eb8f1c724.png">

**Comment by minhcasi** [comment]
@andyodoo - could i check if the `aramex` config as default plugin form woocommerce or you should install new shipping plugin?

**Comment by andyodoo** [comment]
yes sure its the default plugin here is a link for it 
https://wordpress.org/plugins/aramex-shipping-woocommerce/

here is also common folder 
[common.zip](https://github.com/inspireui/support/files/4765485/common.zip)

**Comment by andyodoo** [comment]
please forget the link i sent for aramex shipping because 
we are using this one https://woocommerce.com/products/woocommerce-shipping-aramex/?aff=13200
and I  did email you the login details for our website to your email :minhcasi@gmail.com

**Comment by andyodoo** [comment]
update please

**Comment by andyodoo** [comment]
Dear @minhcasi,
update please

**Comment by minhcasi** [comment]
@andyodoo - i've checked with the team and they report the `aramex shipping` will not compatible with the app as it work separate with the default Rest API from Woocommerce, hence you need to add customization to make it work - thank you!

**Comment by andyodoo** [comment]
Hello 
How much $ and How long its will take you to fix the above aramex shipping issue ?

**Comment by minhcasi** [comment]
We wanted to thank you for your patience during this busy time. We currently have reduced staff and a significantly higher volume of inquiries. We’re working as hard as we can, but could not support more customization or installing the job at the moment.

Thank you so much for your interest in our services.

**Comment by andyodoo** [comment]
Thank you 
but having app that doesn't support shipping method makes the app worthless for us 
please either help use fix it and we will pay for customization or provide us with a recommended company to hire them 
I spent so much in last few days hiring 5 developers all failed with the task 
if you cant help us i would like a refund plz

**Comment by minhcasi** [comment]
@andyodoo - try to use this option config to enable the OnePage payment that supports for an extra plugin config like aramex

<img width="840" alt="Screen Shot 2020-06-17 at 10 19 40" src="https://user-images.githubusercontent.com/1459805/84851278-0f794980-b084-11ea-99b2-378c939ba0dd.png">

**Comment by minhcasi** [comment]
let us know if this solution is worked with your requirement?

**Comment by andyodoo** [comment]
No the solution you offered is using webview 
which is very bad and not reliable 
plz we want to hire developer to fix our problem

**Comment by minhcasi** [comment]
Sorry, we are not available for customization at this time, please help to find some developer on Upwork :)

**Comment by andyodoo** [comment]
we noticed there is not shipping method is getting the correct rate 
they all display zero value even flat rate 
![Screenshot_1593491859](https://user-images.githubusercontent.com/50452375/86084094-a68eca00-baa4-11ea-95b1-4a05e44d0804.png)
I attached the common folder 
[common.zip](https://github.com/inspireui/support/files/4849469/common.zip)
plz help us fix it asap

**Comment by andyodoo** [comment]
@minhcasi plz reopen it
