### ISSUE TITLE
Tons of warnings on my Expo app

### ISSUE THREAD

**Issue by GuyAvraham** [inspireui/support#3685]
Hi guys,
I am running the mstore expo app.
It works, but the log is full of warnings.
first on the npm install, it works only with node 10, and installing the patch fails
I wonder - this suppose to be a tight quality code. Maybe I am missing an update?
On yarn start I see the following warnings on most of the components:

![image](https://user-images.githubusercontent.com/4614438/84361538-7b673800-abd4-11ea-8202-8a34f6e65343.png)

And in addition there are the deprecation warnings:

![image](https://user-images.githubusercontent.com/4614438/84361575-8c17ae00-abd4-11ea-9d67-b1c3074bf12c.png)

Would love to get more info on how to progress.
Thanks in advance

**Comment by luyx2412** [comment]
HI @GuyAvraham This is a warning in new version. You can remove this warning, please follow the article https://stackoverflow.com/questions/55664673/require-cycles-are-allowed-but-can-result-in-uninitialized-values-consider-ref

Thanks

**Comment by luyx2412** [comment]
Closed!
P/S: Feel free to reopen or create new issue.

**Comment by GuyAvraham** [comment]
Thanks!
