### ISSUE TITLE
Issue during Online Transaction

### ISSUE THREAD

**Issue by chocotacos** [inspireui/support#3686]
Previous Verified Ticket id #2996 is now closed so creating new one.

1- Having this issue while having online Transaction

![Capture2](https://user-images.githubusercontent.com/55656013/84360525-d9514b00-abe7-11ea-80b1-47458b0e9b81.PNG)

2-App Fails to load data of the home page nor in the Test Device Nor in the Real Device

Real Device Photos Uploaded Below Home Page isn't loading data and even the category page takes a lot of time to load.

![WhatsApp Image 2020-06-11 at 13 37 05 (2)](https://user-images.githubusercontent.com/55656013/84361089-c55a1900-abe8-11ea-975b-e14cba086a87.jpeg)

![WhatsApp Image 2020-06-11 at 13 37 05 (1)](https://user-images.githubusercontent.com/55656013/84361103-c7bc7300-abe8-11ea-8c4e-718438070852.jpeg)

![WhatsApp Image 2020-06-11 at 13 37 05](https://user-images.githubusercontent.com/55656013/84361109-ca1ecd00-abe8-11ea-94e3-c2c9bd3b8d84.jpeg)

3- Can change this section?

![InkedWhatsApp Image 2020-06-11 at 13 37 05_LI](https://user-images.githubusercontent.com/55656013/84361671-a0b27100-abe9-11ea-869c-7144125ad621.jpg)

From the upper one to this the one below?

![WhatsApp Image 2020-06-11 at 13 43 18](https://user-images.githubusercontent.com/55656013/84361863-f0913800-abe9-11ea-8a35-06ab09423e5a.jpeg)

**Comment by chocotacos** [comment]
@minhcasi & @minhtruong315  Anyone gonna help me out in this ?? i am stuck data loads fine in the fluxbuilder but fails to load in the app help me please & that text "order above 999" can i change it ??

**Comment by minhtruong315** [comment]
Hi @chocotacos please upload your source code to github and invite me: minhtruong315@gmail.com
Thanks

**Comment by chocotacos** [comment]
@minhtruong315 i had send you the request and help me out with it please.

**Comment by chocotacos** [comment]
@minhtruong315 Are you there its been 3 days ???? I really need help!!!!

**Comment by minhtruong315** [comment]
Hi @chocotacos I dont see any your source code. https://github.com/chocotacos/Flux-v1.7.4
Please upload it. You need to use the latest version Fluxstore 1.7.5
Let me know when you upload
Thanks

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
