### ISSUE TITLE
[FluxStore] Home banner link to blog entry

### ISSUE THREAD

**Issue by and-eee** [inspireui/support#3687]
Hi guys, 

1. Is it possible to link a Banner Image on the Home Screen to a Blog Post, or to a local (native) HTML page? 

2. I'm struggling to work out what "Screen" and "Tab" Banner Image types do. Are there instructions somewhere?

Thanks in advance.

**Comment by minhcasi** [comment]
@and-eee - you could customize this file 

<img width="1005" alt="Screen Shot 2020-06-11 at 20 14 32" src="https://user-images.githubusercontent.com/1459805/84389396-2b15c780-ac20-11ea-8d3b-a70ebd1638f2.png">

**Comment by minhcasi** [comment]
@and-eee - pls try to keep you open with one ticket and include all comments there - #3662 - thank you!

**Comment by and-eee** [comment]
Hi Minh, I was keeping these two issues separate because they're completely separate issues and figured that users who are looking for solutions in this git will more easily find answers to their issues if they're kept separate.

Could I have an answer for point 2 please?
