### ISSUE TITLE
I didn't find any stripe payment configuration and implementation . please provide stripe configuration and coding .

### ISSUE THREAD

**Issue by CodeIncognite** [inspireui/support#3688]
if (paymentMethodModel.paymentMethods.isNotEmpty) {
                        final paymentMethod = paymentMethodModel.paymentMethods
                            .firstWhere((item) => item.id == selectedId);
                        Provider.of<CartModel>(context, listen: false)
                            .setPaymentMethod(paymentMethod);
                        print(paymentMethod.id);
                        if (paymentMethod.id
                                .contains(PaypalConfig["paymentMethodId"]) &&
                            PaypalConfig["enabled"] == true) {
                          Navigator.push(
                            context,
                            MaterialPageRoute(
                              builder: (context) => PaypalPayment(
                                onFinish: (number) {
                                  createOrder(paid: true);
                                },
                              ),
                            ),
                          );
                        } else if (paymentMethod.id
                                .contains(TapConfig["paymentMethodId"]) &&
                            TapConfig["enabled"] == true) {
                          Navigator.push(
                            context,
                            MaterialPageRoute(
                                builder: (context) =>
                                    TapPayment(onFinish: (number) {
                                      createOrder(paid: true);
                                    })),
                          );
                        } else {
                          if (paymentMethod.id == "cod" ||
                              serverConfig["type"] == "magento") {
                            createOrder(cod: true);
                          } else if (serverConfig["type"] == "woo") {
                            final user =
                                Provider.of<UserModel>(context, listen: false)
                                    .user;
                            var params = Order().toJson(
                                cartModel, user != null ? user.id : null, true);
                            params["token"] = user != null ? user.cookie : null;
                            makePaymentWebview(params);
                          } else if (serverConfig["type"] == "opencart") {
                            Navigator.push(
                              context,
                              MaterialPageRoute(
                                  builder: (context) =>
                                      PaymentWebview(onFinish: (number) {
                                        widget.onFinish(Order(number: number));
                                      })),
                            );
                          }
                        }
                      }

i want to add stripe payment in this script that i have.

**Comment by CodeIncognite** [comment]
This is not issue but as you provide script you mention stripe payment configured in script..but i didn't find any stripe configuration in script.  Please provide stripe configuration for our script.

**Comment by minhcasi** [comment]
@CodeIncognite - stripe payment is not yet supported as the native payment, it could only run via Webview, you could try to integrate with this lib - https://pub.dev/packages/stripe_payment
