### ISSUE TITLE
Translating to Brazilian portuguese - problem

### ISSUE THREAD

**Issue by lfabiotargino** [inspireui/support#3689]
Hello, i tryed to use the Flutter i18 plugin for Android Studio, but it was deprecated. I tryed with Flutter Intl plugin. So i created a file on i10n folder with all json content variables like english version, after that, i changed some variables for make a test. So the plugin generated the file on generated folder, but the i18n.dart file did not create the record variables for my new language pt_BR. I tryed follow the steps on website, but the information was deprecated too.

I am trying to translate to Brazilian Portuguese.

Only the main title on main screen was translated because i did directly on english file.
https://drive.google.com/file/d/1eL7tcKAO_RISCIK0lg1l3Z-qqgm5dCIg/view?usp=sharing, https://drive.google.com/file/d/1isxXUbFOGIuz6B24OGGKvW6sF-BjuHXd/view?usp=sharing

+ Product & version: fluxnews 1.4.1
+ Flutter (or React Native) version:  Flutter (Channel beta, v1.17.0, on Mac OS X 10.14.6 18G4032, locale pt-BR)
+ Testing Device/Simulator: Asus mobile phone device
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**
I sent

**Comment by minhcasi** [comment]
@dttrung26 - pls help with checking

**Comment by dttrung26** [comment]
Hi @lfabiotargino , 
as I tested so far, l10n plugin is still working fine. Do pay attention to i18n, it won't affect your translation feature. The only issue in your app is that you haven't set up your own new country flag to switch to your language. Please follow this [docs](https://docs.inspireui.com/fluxstore/multi-language/). 
Best!
