### ISSUE TITLE
Listpro App

### ISSUE THREAD

**Issue by ebusinessfiji** [inspireui/support#369]
**Mandatory Info (please complete the following information):**
 - Product: Listpro 
 - Your Purchased Code: 1ebe7a3b-5825-4a7a-862b-9a3100f39b66
(we may not reply if you are not our customer)

**Describe the issues**
-Initial startup of the app takes time, communicating with my server and displaying the listings in the app takes long time.
-the menu is not showing, the left hand menu and also the menu icon is white, want to change to some other color

**Comment by thangvo9x** [comment]
Hi. You can use CeBuilder to config it.
download here https://inspireui.com/ 
Thanks

**Comment by ebusinessfiji** [comment]
hi,
i believe you didn't understand the issue properly, i've already tried using the builder, it doesn't change the menu icons color, and the menu doesn't show in the drawer either , i'm talking about the menu that has "explore"and "settings" and other options in it.
also the initial startup of the app ... very slow in retrieving listings from the server ... can you adress this issues asap please.

**Comment by thangvo9x** [comment]
Hi. Can you screenshot that menu help me, plz?

**Comment by ebusinessfiji** [comment]
![53352604_228688651304854_7599914312097857536_n](https://user-images.githubusercontent.com/48225520/53930660-a1a74980-40ee-11e9-8ba1-04601adaeed3.jpg)
![53270721_2331459423799810_4923695858970525696_n](https://user-images.githubusercontent.com/48225520/53930668-a835c100-40ee-11e9-8273-bebece2fcc4f.jpg)

**Comment by ebusinessfiji** [comment]
thats the menu i'm talking about .... nothing shows in it and i wanna change the color for the icon for it since its white and easily blends with the background

**Comment by thangvo9x** [comment]
Hi. You can edit code. You can change it Components/Toolbar/index.js 
Thanks

**Comment by ebusinessfiji** [comment]
Hi, i'm going to neeed you to be a little bit more specific in regards to what exactly should i edit in the code , as i've tried doing it and still the menu doesn't show..

**Comment by thangvo9x** [comment]
You must go to Toolbar/index.js find this block
and change tintColor: "your color"
Save and restart.
Thanks
<img width="455" alt="block" src="https://user-images.githubusercontent.com/23457178/54249745-f5dd7e00-4573-11e9-8f3b-d63dca974399.png">
