### ISSUE TITLE
Message Screen does not show notifications

### ISSUE THREAD

**Issue by Zubi1001** [inspireui/support#3690]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: I set up push notifications with fcm and it works, the notifications appear in the notification tray but when I open fluxstore > settings > Messages
I don't see any messages
but at the same time the "No messsage" prompt has also disappeared.
I tried to debug and print out the notifications to console and found out that it is getting the notifications. but the notification data is empty

`screenName null
I/flutter (27012): [{"body":null,"title":null,"seen":null,"date":null}]
I/flutter (27012): Invalid argument(s) (input): Must not be null` 

this is the console print when I open the notification tab 

+ Product & version: FluxStore shopify 1.7.2
+ Flutter (or React Native) version: 1.17.3
+ Testing Device/Simulator: Android Emulator x86 PIXEL 2
+ Screenshot issues (drag the file to attach here): 
![Screenshot_1591886163](https://user-images.githubusercontent.com/43316919/84399947-dde32700-ac1a-11ea-96ab-9a500af9ddf8.png)
Working push notiifications

![Screenshot_1591886173](https://user-images.githubusercontent.com/43316919/84399990-eb98ac80-ac1a-11ea-81e7-3e68a7b74dea.png)
Not working message tab^

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**
FluxStore Shopify - The Best Flutter E-commerce app
Regular License

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by stickypages** [comment]
Side note, remove your purchase code, please. Someone can steal it.

**Comment by minhcasi** [comment]
@Zubi1001 
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
@Zubi1001 - note with investigating - thank you!

**Comment by minhcasi** [comment]
We have fixed this bug on latest release 1.7.7 - please help to update and let us know if you have any issues, thank you!

**Comment by minhcasi** [comment]
Hi Sir, Let us know if you have any questions - thank you!
