### ISSUE TITLE
Checkout process Payment Gateway redirects to webview checkout

### ISSUE THREAD

**Issue by iaksit** [inspireui/support#3691]
First of all, I cannot save preview customer note to the database I was not able to find where it sends the data to the database. I have just attached a screenshot from working app for customer note to be added (preview_customer_note_screen.png).

The other problem is that I am clicking on the continue payment button to choose payment methods screen (place_order_payment_screen.png). I choose the custom payment gateway which is working well on the opencart website. After then I go through that screen by clicking on Place Order button (screen_after_click_place_order.png). Even I have those settings in lib/common/config/payments.dart file /// Enable Payment option

"EnableOnePageCheckout": false,
"NativeOnePageCheckout": true,

---
paymensts.dart content
/**
 * Everything Config about the Payment
 */

/// config for payment features
const kPaymentConfig = {
  "DefaultCountryISOCode": "AR",

  /// Enable the Shipping option from Checkout, support for the Digital Download
  "EnableShipping": true,

  /// Enable the Google Map picker
  "EnableAddress": true,

  /// Enable the product review option
  "EnableReview": true,

  /// enable the google map picker from Billing Address
  'allowSearchingAddress': true,
  "GuestCheckout": false,

  /// Enable Payment option
  "EnableOnePageCheckout": true,
  "NativeOnePageCheckout": false,

  /// Enable Credit card payment
  "EnableCreditCard": false,

  /// Enable update order status to processing after checkout by COD on woo commerce
  "UpdateOrderStatus": false,

  /// Show Refund and Order button on Order Detail
  "EnableRefundCancel": false
};

const Payments = {
  "paypal": "assets/icons/payment/paypal.png",
  "stripe": "assets/icons/payment/stripe.png",
  "razorpay": "assets/icons/payment/razorpay.png",
};

![click_back_button_while_on_webview_checkout](https://user-images.githubusercontent.com/1135478/84404982-306b1600-ac10-11ea-9409-da20e2df23df.png)
![place_order_payment_screen](https://user-images.githubusercontent.com/1135478/84404987-3234d980-ac10-11ea-903f-5b243947e813.png)
![preview_customer_note_screen](https://user-images.githubusercontent.com/1135478/84404991-32cd7000-ac10-11ea-9dc7-94281fefce1c.png)

it directs me to the webview payment checkout screen (screen_after_click_place_order.png). Here I would like to open a popup for payment gateway company like Razor, PayPal etc. OR open directly Payment Gateway checkout webview.

The last issue I would like to share is that if we want to go back to previous screen (click_back_button_while_on_webview_checkout.png)  all screens freezes. We cannot click anywhere.

Please we need those fixes or solutions as soon as possible.

**Comment by minhcasi** [comment]
@iaksit - could you compare with the latest release `1.7.5` - we already fixed this issue - thank you!

**Comment by iaksit** [comment]
@minhcasi I have compared with the latest release 1.7.5 file by file especially lib/ folder contents, there are only my custom design changes. No more. Could you please point it out the lines or source DART files to work on? I would like to make sure it is what I expected.

Thanks in advance

**Comment by iaksit** [comment]
@minhcasi there is no solution so far. What can we do? I am still waiting for urgent reply to make app online.
Please it is really urgent for me. I would like to know how popup a payment gateway like PayPal or redirect to directly bank 3d payment system.
Thanks in advance

**Comment by minhcasi** [comment]
@iaksit - sorry for late response as we have some holiday off

Please check `EnableOnePageCheckout: true` from the config/payment.dart to enable the onepage checkout feature, or you could set
`  
"EnableOnePageCheckout": false,
 "NativeOnePageCheckout": true,
`

The display order note could cause by this issue from the woocommerce service file `item.type == 'any'`, please help to compare with the latest code on our Gitlab repository as well
<img width="914" alt="Screen Shot 2020-06-15 at 11 23 28" src="https://user-images.githubusercontent.com/1459805/84617897-a4503b80-aefa-11ea-8a87-cfe711654ec6.png">

**Comment by iaksit** [comment]
@minhcasi it does not work unfortunately. I have followed what you have said. Please I do not use woo commerce. I am using OpenCart. 
I need urgent reply to overcome the problem. 
I think you did not understand what problems I faced with.

**Comment by minhcasi** [comment]
@iaksit - sorry for misunderstanding your comment - the Order Note is not supported on Opencart, as explain from our product description

https://camo.envatousercontent.com/ada677e221e4434f1720a4d598c3a11888ab1eca/68747470733a2f2f7472656c6c6f2d6174746163686d656e74732e73332e616d617a6f6e6177732e636f6d2f3564323933323564323030306566326661643336333435662f3565633635393166613864653565323565356331643930652f39613035373736396139346636616235626365323336356433323762373266612f666561747572652e706e67

I've reported to the team for investigating and keep new upgrade

**Comment by minhcasi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Feature: Opencart Order Note](https://trello.com/c/twzIGzBF/60-feature-opencart-order-note)

**Comment by minhcasi** [comment]
Moved to the backlog for further upgrade. Please let us know if you have any questions by creating a new ticket - thank you!

**Comment by iaksit** [comment]
@minhcasi I have at least there question in the ticket. 
"The other problem is that I am clicking on the continue payment button to choose payment methods screen (place_order_payment_screen.png). I choose the custom payment gateway which is working well on the opencart website. After then I go through that screen by clicking on Place Order button (screen_after_click_place_order.png). Even I have those settings in lib/common/config/payments.dart file /// Enable Payment option"

When I click go back button or link on the payment gateway it freezes the whole screen and cannot click anything.
