### ISSUE TITLE
Could not determine the dependencies of task ':app_settings:compileDebugAidl'.

### ISSUE THREAD

**Issue by LTAshley** [inspireui/support#3692]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: I am trying to run the app in Android Studio & Visual Studio Code but always face this issue: 
* What went wrong:
Could not determine the dependencies of task ':app_settings:compileDebugAidl'.
> Failed to find Platform SDK with path: platforms;android-R 
+ Product & version: FluxStore Pro - Flutter E-Commerce app 
+ Flutter (or React Native) version: Flutter 1.17.3 
+ Testing Device/Simulator: Redmi 6 pro running Android Pie
+ Android Studio: 4.0 Latest stable release
Issue faced:
![Screenshot_1](https://user-images.githubusercontent.com/57007946/84417315-0c6cfc00-ac33-11ea-9697-d5fc4577e28b.png)
![Screenshot_2](https://user-images.githubusercontent.com/57007946/84417320-0ecf5600-ac33-11ea-8271-b7d738d1bea4.png)

+ Screenshot issues (drag the file to attach here): 
![Screenshot_3](https://user-images.githubusercontent.com/57007946/84416750-3f62c000-ac32-11ea-884e-d055badffe95.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

Purchased via CodeCanyon 
![Screenshot_3](https://user-images.githubusercontent.com/57007946/84417361-21e22600-ac33-11ea-98fd-9feac9618d08.png)

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by Jazzykhan** [comment]
same here how you solved it?
