### ISSUE TITLE
Flutter build problem

### ISSUE THREAD

**Issue by atakancelik** [inspireui/support#3695]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 

I am getting this error which I shared you.( Build failed with an exception)Flutter doctor does not give any error. When I create a new flutter project the new project is working fine but I cant build fluxstore. 
 
+ Product & version: fstore 1.7.5+3001
+ Flutter (or React Native) version: v1.17.3
+ Testing Device/Simulator: Pixel 3a XL  API 29
+ Screenshot issues (drag the file to attach here): ![testflux](https://user-images.githubusercontent.com/37778749/84458397-96d25180-ac6d-11ea-9cf0-fa2ff8aee274.PNG)
![flutterdoctor](https://user-images.githubusercontent.com/37778749/84458529-de58dd80-ac6d-11ea-8855-6d6c62ab2d8c.PNG)

**Comment by minhcasi** [comment]
@atakancelik - it seems there is missing Android SDK on your PC, please help to check this solution https://stackoverflow.com/questions/51183581/failed-to-find-platform-sdk-with-path-platformsandroid-p/51187271

**Comment by atakancelik** [comment]
![sdk](https://user-images.githubusercontent.com/37778749/84524922-6c22e000-ace3-11ea-8c05-66b26ded3428.PNG)
I have already installed SDK

**Comment by atakancelik** [comment]
@minhcasi so it is not working

**Comment by minhcasi** [comment]
@atakancelik - could you run this example default from Flutter? https://flutter.dev/docs/get-started/test-drive?tab=vscode

Please don't try to upgrade any build grade from Android Studio that will break the build from Flutter

**Comment by genjitsuCode** [comment]
I created it successfully. New flutter project working properly, with no error.

**Comment by genjitsuCode** [comment]
How can I resolve it?

**Comment by atakancelik** [comment]
I created it successfully. New flutter project working properly, with no error. How can I resolve it?

**Comment by kvt0012** [comment]
https://www.youtube.com/watch?v=3dv_8UerNpQ&t=1478s 

Dear sir, please follow this guide, thank you

**Comment by atakancelik** [comment]
I have already watched this video. I followed it step by step 2 times.

**Comment by minhcasi** [comment]
Could you check this solution as well https://github.com/flutter/flutter/issues/59355#issuecomment-643482076

**Comment by minhcasi** [comment]
pls move all conversation relate to android-r to this ticket #3708
