### ISSUE TITLE
URL/Website not opening from Homescreen/JSON file

### ISSUE THREAD

**Issue by gunero** [inspireui/support#3696]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: I used the Fluxbuilder to build my home screen. I used some banner images, which will then open an URL, but somehow instead of opening the URL it opens the blog category.
+ Product & version: Latest
+ Flutter (or React Native) version: Latest
+ Testing Device/Simulator: Android Studio iOS Simulator
+ Screenshot issues (drag the file to attach here): 

**_I am using Fluxnews._**

This is how my code in the config_en.json looks like
![issue](https://user-images.githubusercontent.com/66735847/84463672-6ca08400-acad-11ea-900c-60e490e57d18.jpg)

The banner image is showing correctly in the simulator, but once I clicked on it, it redirects me to a blog category instead of opening the URL.

Also, will this URL open as webview, or will it open in the browser? I would like to show it as a webview. 

Thanks for your help and hopefully hear from you soon.

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by gunero** [comment]
Is it possible the "WebViewScreen" is missing in the index.dart? I have no coding knowledge, its just my guess. I tried to fix for the last few hours without any results.

Btw. I used the FluxBuilder to build the app.

**Comment by gunero** [comment]
Hello, could someone please reply?

**Comment by gunero** [comment]
Hello?

**Comment by minhcasi** [comment]
@gunero 

We wanted to thank you for your patience during this busy time. We currently have reduced staff and a significantly higher volume of inquiries. We’re working as hard as we can to get to your request as soon as possible.

We sincerely apologize for the delay and hope you’re staying safe.

**Comment by gunero** [comment]
> @gunero
> 
> We wanted to thank you for your patience during this busy time. We currently have reduced staff and a significantly higher volume of inquiries. We’re working as hard as we can to get to your request as soon as possible.
> 
> We sincerely apologize for the delay and hope you’re staying safe.

Yes, I understand, but its quite frustrating for me, since I almost finished the app and only need this fixed.

As I said: Problem is it is not opening the Url/Webview, but the category page. I hope to hear from you soon.

**Comment by dttrung26** [comment]
Hi @gunero , 
please bear in mind that `BannerImage` widget does not support for launching an URL. If you are looking for this feature, please take a look at our docs: https://docs.inspireui.com/fluxnews/customization/#8-page-view (session 8 for native widget display, session 9 for launch a webview for URL) 
Best!

**Comment by gunero** [comment]
What? I built the app with the FluxBuilder. There is the option to launch an URL from the BannerImage.

Please fix your app or fix the FluxBuilder.

Now I have to change the whole design of my app. 

And seriously, it took 4 days to get this reply?

**Comment by dttrung26** [comment]
Hi @gunero , 
First of all, I'm really sorry for taking so long in replying your ticket. There is a significant number of request supports right now and we are working very hard in solving every single one of them. 
Besides, could you please give me screenshot of URL launching option in FluxBuilder from BannerImage so that I could fix it in FluxBuilder. 
Many thanks!

**Comment by minhcasi** [comment]
@gunero - we could upgrade this the banner issue on next release - do you mind updating the rating as it will impact our business?

It is possible to process a refund if you are not happy with our product - thank you for your time!
