### ISSUE TITLE
error in runung fluxstor on android studio

### ISSUE THREAD

**Issue by yaserarafat2020** [inspireui/support#3697]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: error in runung fluxstor on android studio
+ Product & version:android studio 4
+ Flutter (or React Native) version: 1.17.3
+ Testing Device/Simulator: pixel 3a xl
+ Screenshot issues (drag the file to attach here): 

![Untitled](https://user-images.githubusercontent.com/66765065/84472099-584d8e80-ac8f-11ea-8122-367bbb65f273.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by yaserarafat2020** [comment]
i have windows 10 system

**Comment by minhcasi** [comment]
@yaserarafat2020 - pls help to double-check if you have installed the Android SDK correctly: 
https://flutter.dev/docs/get-started/install/windows

Also help to check if you could run the Test Drive (basic example from flutter) - https://flutter.dev/docs/get-started/test-drive?tab=vscode - thank you!
