### ISSUE TITLE
Group by x is not working in App

### ISSUE THREAD

**Issue by hinai** [inspireui/support#3698]
#3437   

1) The group by feature is not working , for example if I make group of 10 ( the selection quantity should be 10,20,30,40), I'm using Fluxstore woocommerce 1.7.5

![Screen Shot 2020-06-12 at 10 59 26 AM](https://user-images.githubusercontent.com/4161259/84474990-d82e2580-ac9c-11ea-9608-998d0f54f4ca.png)

in the phone looks like this 

![Screenshot_2020-06-12-10-58-41-68](https://user-images.githubusercontent.com/4161259/84475130-0e6ba500-ac9d-11ea-8d5e-5ad71795918c.png)

the quantity should be 10,20,30  like that 

Thanks

**Comment by minhcasi** [comment]
Hi, this Group feature is not available, we will investigate and keep new upgrade - thank you!

**Comment by hinai** [comment]
Ok , thanks.
Is there any work around way? 
I did some modifications on my code but got some problems in other functions. 

Any way thanks

**Comment by minhcasi** [comment]
@hinai - i think we should customize the Rest API as well, we will investigate and keep an update - thank you!

**Comment by hinai** [comment]
Ok , thanks :)

**Comment by minhcasi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [UX: Group by x is product](https://trello.com/c/GQ2kPtdj/57-ux-group-by-x-is-product)

**Comment by minhcasi** [comment]
moved to backlog for next improvement
