### ISSUE TITLE
COD order goes to Pending for payment by default

### ISSUE THREAD

**Issue by Amitjeypore** [inspireui/support#3699]
Whwneven someone orders in App via COD the order status goes to pending for payment by default, which is why I dont get any notifications about the order. Once I change the order status to processing I start getting notifications.
This doesn't happen when someone orders in website, COD orders go to Prodessing by default.

Please let me know how to fix it, I am missing a lot of orders.

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

Already submitted 

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@Amitjeypore - could you try to check if you are using the latest `1.7.5` and if it is possible try to debug as this line to see if could update the order status on your site?

<img width="1151" alt="Screen Shot 2020-06-12 at 20 29 41" src="https://user-images.githubusercontent.com/1459805/84507707-734dec00-aceb-11ea-9ec9-c95e82379445.png">

**Comment by Amitjeypore** [comment]
Hi, yes I just checked the line, and its the same. But the order status goes to Payment pending only.

**Comment by magic-coding** [comment]
Go to `/FluxStore-woo 1.7.5/source/lib/common/config/payments.dart` and make sure to set `UpdateOrderStatus` to `true` .

<img width="775" alt="Screen Shot 2020-06-15 at 10 04 17 AM" src="https://user-images.githubusercontent.com/15148391/84623083-95b05700-aeef-11ea-86c3-33ebdd5cf312.png">

**Comment by Amitjeypore** [comment]
Thank you very much it helped!

**Comment by Amitjeypore** [comment]
Also I wanted to know that can we send firebase notifications to users on the order status when we update the order status in the backend, like processing, shipped, complete etc.

**Comment by xsamir** [comment]
> 
> 
> Also I wanted to know that can we send firebase notifications to users on the order status when we update the order status in the backend, like processing, shipped, complete etc.

**That a very important point**
To make a notification for both Vendors & Customers about the order status.
Especially some vendors don't check their emails all the day to get attentions on their orders

**Comment by minhcasi** [comment]
@Amitjeypore @xsamir - the firebase notifications when update Order will be upgraded later, it's already in our backlogs -  as this feature is quite complex that take our time for investigating.

Let us know if you have any questions - thank you!

**Comment by minhcasi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Notify when updating Order](https://trello.com/c/kp4rqktm/11-notify-when-updating-order)

**Comment by minhcasi** [comment]
moved the request notify via Firebase into Trello backlog
