### ISSUE TITLE
[EvaStore] - Error on Load shipping

### ISSUE THREAD

**Issue by leotseng159** [inspireui/support#37]
EvaStore - Shopify mobile store by React Native and GraphQL
 - 5b34e5b9-c0cf-4d52-9fae-1ff1168746f2

**Describe the bug**
When i trying to checkout the order its get error. TypeError: undefined is not an object (evaluating ‘shippingRates[0]’)

**Screenshots**
https://www.dropbox.com/s/9bky3wrx14rt7a2/IMG_2573.PNG?dl=0

Thank you!

**Comment by luyx2412** [comment]
Hi @leotseng159 Can you provide the Config.js file?
Thanks

**Comment by leotseng159** [comment]
Hello @luyx2412 ! 

Sure. Here is.
https://www.dropbox.com/s/vzu2bjrxmew3h4t/Config.js?dl=0

Thanks

**Comment by luyx2412** [comment]
Fixed with next version. Closed

**Comment by leotseng159** [comment]
Hello @luyx2412 ! 

Im getting another error.. 
I cant't choose the shipping method in the checkout page, he always assign the low's price shipping. When a select one more expensive he's back to the cheap automatic.

<img width="332" alt="captura de tela 2018-11-28 as 15 34 49" src="https://user-images.githubusercontent.com/23278604/49170834-26cad780-f324-11e8-92c2-c36b463e3c8a.png">

The 0 cost shipping method is local pickup (retirada na loja).


Thanks!

**Comment by luyx2412** [comment]
Hi @leotseng159 Can u share me the account app to check with your account. Thanks

**Comment by leotseng159** [comment]
Hi @luyx2412  

Sorry, what would it be the account app?
Its the shopify login?

Thanks

**Comment by luyx2412** [comment]
Yep @leotseng159 I need your shopify account when you logged in your app.
THanks

**Comment by leotseng159** [comment]
@luyx2412  App shopify account
Login. ttandtng@gmail.com
Password. tt123456

I sent to your email the shopify login.

Thanks

**Comment by leotseng159** [comment]
Hello,

I'm sending the shopify account for if you need.
https://pt.shopify.com/login

aq-shopping.myshopify.com
ti.aqshopping@gmail.com
aq2@18

thanks

Em sex, 30 de nov de 2018 às 00:42, luyx2412 <notifications@github.com>
escreveu:

**Comment by luyx2412** [comment]
Hi @leotseng159 I could not login with your account. Can you provide me your account again?
<img width="388" alt="screen shot 2018-12-01 at 5 38 49 pm" src="https://user-images.githubusercontent.com/8909619/49327155-0e5ef500-f590-11e8-8143-f05bb2f2c67b.png">
Thanks

**Comment by leotseng159** [comment]
Hi @luyx2412 

Login. ttandtng@gmail.com
Password. 123456

Thanks
