### ISSUE TITLE
Mstore pro Build failed

### ISSUE THREAD

**Issue by hakihosting** [inspireui/support#370]
Hello i have this error 
/Users/heyckelneji/Downloads/mstore-3.7.0/mstore-pro/ios/mstore/AppDelegate.m:12:9: 'FBSDKCoreKit/FBSDKCoreKit.h' file not found

**Comment by hakihosting** [comment]
I solved the problem FBSDK 
Now i have this two error : 
ld: framework not found GoogleMobileAds
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Argument list too long: recursive header expansion failed at /Users/heyckelneji/Downloads/mstore-3.7.0/mstore-pro/node_modules/react-native-admob/ios/../../../ios/DerivedData/mstore/Index/DataStore/v5/records/R8.

**Comment by luyx2412** [comment]
Hi @hakihosting Please clean your project and rebuild again. Or install again library.

Thanks

**Comment by hakihosting** [comment]
i have all done   clean your project and rebuild again  
How can i install again library ?

**Comment by luyx2412** [comment]
HI @hakihosting Please read the document to install library, and also understand about the project.
https://docs.mstore.io/get-started#quick-install-pro-version

Thanks

**Comment by Jegufull** [comment]
Hello, I have the same error.

clang: error: no such file or directory: '/Users/jeimergutierrez/Library/Developer/Xcode/DerivedData/mstore-cbxzvecnrrutzsbaulrxchzjfqma/Build/Products/Debug-appletvsimulator/libBVLinearGradient.a'

I reinstalled the libraries, cleaned the project and continued the same error.

**Comment by hakihosting** [comment]
hello is not worked , it's possible to do , a skype session please i am blocked still 2 weeks

**Comment by hakihosting** [comment]
![image](https://user-images.githubusercontent.com/47614045/54239955-fc8cd680-451c-11e9-9a59-8a2797d3eb0e.png)

Ok i have found how to work but when i launch i have this error

**Comment by Jegufull** [comment]
Hello, what did you do to make it work for you?

**Comment by hakihosting** [comment]
upgrade react native

**Comment by Jegufull** [comment]
Have you already tried it if it works with version 3.7.1?

**Comment by Jegufull** [comment]
Hello, Hello, did it work for you?
