### ISSUE TITLE
IOS edit

### ISSUE THREAD

**Issue by MorisTech** [inspireui/support#3701]
Hello, I had my issue on:

https://github.com/inspireui/support/issues/3494

It was closed without answering the question,

Please how do I edit the IOS version

**Comment by minhcasi** [comment]
@MorisTech - sorry for the issue, pls check this detail guide https://docs.inspireui.com/fluxstore/delivery/

Please note you will need the MacOS to release ios to appstore

**Comment by MorisTech** [comment]
Okay, I read that, but I still don't understand 

I made changes with Android Studio, does that mean it affects the design of IOS too?

**Comment by MorisTech** [comment]
Also, I'm Using WCFM and it has this feature to use location to display the store closer to you, how can i do that on the Fluxstore MV app, cos it doesn't make sense for a user to just scroll all the stores at once

**Comment by minhcasi** [comment]
the nearest stores feature is not ready on current release - we will investigate and upgrade this feature later.

**Comment by minhcasi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [GeoLocation Vendor Search](https://trello.com/c/GlKgXx2p/32-geolocation-vendor-search)

**Comment by minhcasi** [comment]
moved to backlog for next upgrade

**Comment by mumin-si** [comment]
Any updates on geo location filter in the app? and please capture the geolocation in the checkout page also so that our delivery boy when we assign him order can easily deliver the products
