### ISSUE TITLE
I have sign in and signup problem

### ISSUE THREAD

**Issue by elziny** [inspireui/support#3703]
**_Step 1 (require): describe detail issues & screenshots_**
+ Product & version: 1.7.5
+ Flutter (or React Native) version:  1.7.1

I use the app with woocommerce, every thing work fine
but signup and sign in show errors on device
signin :
"Exception: username or password is incorrect"
signup :
"Exception: sorry, you are not allowed to do that"

Thank you so much 😊

**Comment by aliciadc** [comment]
I have the same problem.
"Exception: username or password is incorrect"

{
    "code": "rest_not_logged_in",
    "message": "Actualmente no estás conectado.",
    "data": {
        "status": 401
    }
}

**Comment by elziny** [comment]
is there any support ?

**Comment by imhafeez** [comment]
I have the same problem. 
@minhcasi @trunghieuvn 

<img width="914" alt="Screenshot 2020-06-14 at 9 56 41 PM" src="https://user-images.githubusercontent.com/21155655/84599232-f73dda80-ae89-11ea-8daf-7fbba6ac1ca2.png">

**Comment by minhcasi** [comment]
@elziny @imhafeez - pls try to active the License from mstore-api plugin to fix this issue - thank you!

**Comment by minhcasi** [comment]
Let us know if you have any further issue, feel free to reopen the ticket - thank you!
