### ISSUE TITLE
Shopify Flux Store App Shipping & Native Payment Page Error

### ISSUE THREAD

**Issue by swiftindi** [inspireui/support#3709]
Dear Team I’m facing issues with fetching Shipping rates and also connecting with payment gateway for my Shopify store can anyone please help attaching screenshot of the error 
![A57493B6-0F2D-411A-B8B6-1371235ED302](https://user-images.githubusercontent.com/66407765/84539828-cd61a800-ad11-11ea-98d4-d14b03e4050e.jpeg)

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
@luyx2412 - pls help with the suggestion

**Comment by luyx2412** [comment]
Hi @swiftindi Can you give me the specific version? Let me investigate easier.

Thanks

**Comment by swiftindi** [comment]
Hi @luyx2412 could you please tell me which version am I supposed to share / whose version ?!

**Comment by swiftindi** [comment]
@luyx2412 waiting for your assistance I have also sent my config.dart file to you please help asap

**Comment by swiftindi** [comment]
@kunalone please check

**Comment by swiftindi** [comment]
Hi ,
I am still waiting for your reply ,
Please get back asap.

Which version do u need ??

**Comment by luyx2412** [comment]
Hi @swiftindi Sorry about reply you late. Can you give me the specific FluxShopify version? Let me investigate easier.
And please set `EnableOnePageCheckout: true` and `NativeOnePageCheckout: false` in your payment.dart follow the screenshot.
![image](https://user-images.githubusercontent.com/8909619/85033070-b6580580-b1aa-11ea-8d25-fab2b1d1530a.png)

Thanks

**Comment by swiftindi** [comment]
I am using Fluxstore-shopify 1.7.2 
When I activate EnableOnePage Checkout it is going to web view of shopify checkout , I do not want that , further if I click on the site logo when it is in web view it takes me to the store website and its totally not what I want , I want native payment within the app , the app is not supporting login , when I login inside the app , the web view payment page again asks for login , so I want native payment within the app only please help on this

**Comment by swiftindi** [comment]
It is also giving an error as checkoutid is null @kunalone can you please elaborate the error which we are facing here , thanks

**Comment by luyx2412** [comment]
Hi @swiftindi Please send your project to inspireui.team@gmaill.com, let me investigate about it.

Thanks

**Comment by swiftindi** [comment]
Dear Team
Please find attached file ,
Please help me with native payment for my Shopify store . Please treat this on priority as we have deadlines to release the app.
Thanks


https://drive.google.com/file/d/1VwKctA3WvjbWpnk_h3RRS6c9MpO6kaGt/view?usp=drive_web

Warm Regards,

Mihir Bam.
CEO , Swiftindi.com
+91-7507417417

**Comment by swiftindi** [comment]
Warm Regards,

Mihir Bam.
CEO , Swiftindi.com
+91-7507417417

**Comment by luyx2412** [comment]
Hi @swiftindi Please do not send your project in there, because it is public. I will send you the latest project which added checkout with credit card.

Thanks

**Comment by luyx2412** [comment]
Hi @swiftindi I just invite to the repo which latest version via info@swiftindi.com email. Please access to the repo and upgrade your source code latest. And specially, you can `EnableCreditCard: true` in payments.dart to enable checkout via credit card.

Thanks

**Comment by swiftindi** [comment]
Hey Luxy ,
Thanks a lot I will check this out and get back to you .
Appreciate it 

Warm Regards,

Mihir Bam.
CEO , Swiftindi.com
+91-7507417417

**Comment by swiftindi** [comment]
Hi ,
I cannot find EnableCreditCard in the payments.dart
Please help

**Comment by rth89** [comment]
Hello I have that same problem above with the Variable $checkoutId of type ID! was provided  invalid value: Undefined location

**Comment by luyx2412** [comment]
Hi @swiftindi Please pull latest code which will have `EnableCreditCard`. 
And @rth89 Can you give a new issue and give me the specific issue? or give me the email, i will invite you to the latest version, we will upgrade to the evanto soonj.

Thanks

**Comment by swiftindi** [comment]
Hey @luyx2412 thanks for the update I pulled the new code and found the enable credit card option but it is not going ahead and payment page is not opening currently I am using razor pay please tell me how to fix it . If you do not support razor pay please share list of payment gateway you support for Shopify in India.
Waiting for your reply thanks !!

**Comment by rth89** [comment]
@luyx2412  Hello. my email is rhetta.hovdal@gmail.com, we purchased the Fluxstore Shopify from envato for House of Posh Miami company.

**Comment by luyx2412** [comment]
Hi @swiftindi Currently we did not use razor pay, so please use webview to payment. Please change the payment.dart same the screenshot.
![image](https://user-images.githubusercontent.com/8909619/85918969-8cc96900-b891-11ea-87a1-09e46be059d9.png)

Hi @rth89 Please create your issue ticket, i will support you in your ticket.

Thanks

**Comment by swiftindi** [comment]
Hey @luyx2412 thank you for your help but can you please tell me which payment gateway are you supporting for native payments and Share a guide to integrate the same .

**Comment by luyx2412** [comment]
Hi @swiftindi Currently we support 2 gateways.
- Payment via webview (Recommended)
- Payment credit card. This solution need enable the Sale channel and config to pass shopify rule. https://community.shopify.com/c/Shopify-APIs-SDKs/CheckoutCompleteWithCreditCardV2-access-denied/m-p/567430/highlight/true#M37756 . You can enable it with `EnableCreditCard`.

Thanks

**Comment by luyx2412** [comment]
Closed! Feel free to create new issue. Thanks
