### ISSUE TITLE
ListPro setup issue & Wordpress unavailable auth under JSON API settings 

### ISSUE THREAD

**Issue by emothek** [inspireui/support#371]
**Mandatory Info (please complete the following information):**
 - Product: ListPro
 - Your Purchased Code: 9c42d95f-9483-4594-854f-9a76f94e6d7f
(we may not reply if you are not our customer)

**Describe the issues**
On windows 7 , I setup everything as mentionned I have following issues : (please note your ListPro doc is bit outdated) 
- JSON API Setting on my Wordpress installation after installing and activating all plugins your ship does not show : auth (authentication add-on controller for the Wordpress JSON api plugin)
- The app runs on expo (after yarn start) right after ListPro splash screen it remains white nothing is shown   
- is ConsumerKey and ConsumerSecret necessary to make it work ?
- I tried Reactotron & React-native debugger but you don't precise on your doc on how to debug the app

**Comment by JTaad** [comment]
Same problem here, but I respected the doc.
I also tested by creating an API with WooCommerce to enter ConsumerKey and ConsumerSecret but no change ...

Purchase code : d4c4ff44-9258-4212-8a63-ec3b36893b55

**Comment by thangvo9x** [comment]
Hi. Can you tell your issue more detail, plz ? 
You try to install ceBuilder at http://inspireui.com
Do you have to try this plugin? (such as JSON API )
https://github.com/inspireui/mstore/tree/master/plugins
Thanks

**Comment by ebusinessfiji** [comment]
Same issue as the above 2, the authentication controller for the JSON api doesn't show as the screenshot in the documentations states it should be activated, how can we ensure its activated when it doesn't show

Purchased Code: 1ebe7a3b-5825-4a7a-862b-9a3100f39b66

**Comment by JTaad** [comment]
It was missing the Auth part in the JSON API plugin, but once added and activated, still the same problem for me.

{
    "data": {
        "code": "rest_cannot_access",
        "message": "Only authenticated users can access the REST API.",
        "data": {
            "status": 401
        }
    },
    "headers": [],
    "status": 401
}

**Comment by JTaad** [comment]
A solution has been found?

**Comment by minhcasi** [comment]
@JTaad it could be caused by your .htaccess, please check following guide

https://stackoverflow.com/questions/50413414/wp-rest-api-and-only-authenticated-users-can-access-the-rest-api

and make sure you config the JWT correctly - https://wordpress.org/plugins/jwt-authentication-for-wp-rest-api/ 

Let us know your checking, thanks!

**Comment by egebese** [comment]
My purchase code: f62282cf-fe1f-447d-9c9d-1df9eeae993c

I have this problem, i followed all the steps on doc. 

I can see my listings on app but I can't see listing images when i'm not logged in,
My htaccess is right, i did all JWT settings correct, i followed their and your documantation.
Plugin settings done by looking at documantation so there is no wrong setting.
I resized and regenerated all the images. 
I can't see even the icons on nav bar or profile or menu. I can't see nothing!


And this is the red error screen shows up when i click on any listing.
`TypeError: undefined is not an object (evaluating 'postList.filter')

This error is located at:
in Index (created by Connect(Index))
in Connect(Index) (at PostDetailScreen.js:40)
in PostDetailScreen (at react-native-safe-area-view/index.js:365)
in RCTView (at View.js:44)
in AnimatedComponent (at react-native-safe-area-view/index.js:153)
in SafeView (at withOrientation.js:54)
in withOrientation (at react-native-safe-area-view/index.js:364)
in withSafeArea (created by Connect(withSafeArea))
in Connect(withSafeArea) (created by SceneView)
in SceneView (at createTabNavigator.js:39)
in RCTView (at View.js:44)
in RCTView (at View.js:44)
in ResourceSavingScene (at createBottomTabNavigator.js:113)
in RCTView (at View.js:44)
in ScreenContainer (at createBottomTabNavigator.js:103)
in RCTView (at View.js:44)
in TabNavigationView (at createTabNavigator.js:197)
in NavigationView (created by Navigator)
in Navigator (at createAppContainer.js:388)
in NavigationContainer (at RootRouter.js:70)
in RCTView (at View.js:44)
in AnimatedComponent (at react-native-drawer/index.js:632)
in RCTView (at View.js:44)
in Drawer (at MenuOverlay.js:39)
in MenuOverlay (created by Connect(MenuOverlay))
in Connect(MenuOverlay) (at RootRouter.js:83)
in RCTView (at View.js:44)
in RootRouter (created by Connect(RootRouter))
in Connect(RootRouter) (at App.js:217)
in Provider (at App.js:216)
in App (at react-native-safe-area-view/index.js:365)
in RCTView (at View.js:44)
in AnimatedComponent (at react-native-safe-area-view/index.js:153)
in SafeView (at withOrientation.js:54)
in withOrientation (at react-native-safe-area-view/index.js:364)
in withSafeArea (at withExpoRoot.js:22)
in RootErrorBoundary (at withExpoRoot.js:21)
in ExpoRootComponent (at renderApplication.js:34)
in RCTView (at View.js:44)
in RCTView (at View.js:44)
in RootSiblingsWrapper (at AppContainer.js:112)
in RCTView (at View.js:44)
in AppContainer (at renderApplication.js:33)

renderContent
AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fegebese%2FSource%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:258070:35
render
AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fegebese%2FSource%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:258149:30
finishClassComponent
AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fegebese%2FSource%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:17185:43
performUnitOfWork
AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fegebese%2FSource%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:19853:27
workLoop
AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fegebese%2FSource%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:19885:47
renderRoot
AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fegebese%2FSource%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:19948:21
performWorkOnRoot
AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fegebese%2FSource%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:20639:23
performWork
AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fegebese%2FSource%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:20563:30
performSyncWork
AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fegebese%2FSource%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:20538:20
batchedUpdates$1
AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fegebese%2FSource%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:20739:28
batchedUpdates
AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fegebese%2FSource%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:11813:37
_receiveRootNodeIDEvent
AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fegebese%2FSource%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:11870:23
receiveTouches
AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fegebese%2FSource%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:11900:34
__callFunction
AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fegebese%2FSource%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:3654:49
<unknown>
AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fegebese%2FSource%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:3427:31
__guard
AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fegebese%2FSource%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:3608:15
callFunctionReturnFlushedQueue
AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fegebese%2FSource%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:3426:21`

**Comment by qasmaoui** [comment]
im having the same error as egebese

> TypeError: TypeError: undefined is not an object (evaluating 'postList.filter')

This error is located at:
    in Index (created by Connect(Index))
    in Connect(Index) (at PostDetailScreen.js:38)
    in PostDetailScreen (created by Connect(PostDetailScreen))
    in Connect(PostDetailScreen) (created by SceneView)
    in SceneView (at createTabNavigator.js:39)
    in RCTView (at View.js:44)
    in RCTView (at View.js:44)
    in ResourceSavingScene (at createBottomTabNavigator.js:113)
    in RCTView (at View.js:44)
    in ScreenContainer (at createBottomTabNavigator.js:103)
    in RCTView (at View.js:44)
    in TabNavigationView (at createTabNavigator.js:197)
    in NavigationView (created by Navigator)
    in Navigator (at createAppContainer.js:388)
    in NavigationContainer (at RootRouter.js:82)
    in RCTView (at View.js:44)
    in AndroidDrawerLayout (at DrawerLayoutAndroid.android.js:205)
    in DrawerLayoutAndroid (at MenuAndroid.js:35)
    in MenuAndroid (created by Connect(MenuAndroid))
    in Connect(MenuAndroid) (at RootRouter.js:86)
    in RCTView (at View.js:44)
    in RootRouter (created by Connect(RootRouter))
    in Connect(RootRouter) (at App.js:221)
    in Provider (at App.js:220)
    in App (at withExpoRoot.js:22)
    in RootErrorBoundary (at withExpoRoot.js:21)
    in ExpoRootComponent (at renderApplication.js:34)
    in RCTView (at View.js:44)
    in RCTView (at View.js:44)
    in RootSiblingsWrapper (at AppContainer.js:112)
    in RCTView (at View.js:44)
    in AppContainer (at renderApplication.js:33)

This error is located at:
    in NavigationContainer (at RootRouter.js:82)
    in RCTView (at View.js:44)
    in AndroidDrawerLayout (at DrawerLayoutAndroid.android.js:205)
    in DrawerLayoutAndroid (at MenuAndroid.js:35)
    in MenuAndroid (created by Connect(MenuAndroid))
    in Connect(MenuAndroid) (at RootRouter.js:86)
    in RCTView (at View.js:44)
    in RootRouter (created by Connect(RootRouter))
    in Connect(RootRouter) (at App.js:221)
    in Provider (at App.js:220)
    in App (at withExpoRoot.js:22)
    in RootErrorBoundary (at withExpoRoot.js:21)
    in ExpoRootComponent (at renderApplication.js:34)
    in RCTView (at View.js:44)
    in RCTView (at View.js:44)
    in RootSiblingsWrapper (at AppContainer.js:112)
    in RCTView (at View.js:44)
    in AppContainer (at renderApplication.js:33)
renderContent
    index.js:70:33
render
    index.js:108:9
finishClassComponent
    ReactNativeRenderer-dev.js:10563:21
performUnitOfWork
    ReactNativeRenderer-dev.js:14091:21
workLoop
    ReactNativeRenderer-dev.js:14129:41
renderRoot
    ReactNativeRenderer-dev.js:14226:15
performWorkOnRoot
    ReactNativeRenderer-dev.js:15193:17
performWork
    ReactNativeRenderer-dev.js:15090:24
performSyncWork
    ReactNativeRenderer-dev.js:15047:14
batchedUpdates$1
    ReactNativeRenderer-dev.js:15315:21
batchedUpdates
    ReactNativeRenderer-dev.js:2616:31
_receiveRootNodeIDEvent
    ReactNativeRenderer-dev.js:2711:17
receiveTouches
    ReactNativeRenderer-dev.js:2787:28
__callFunction
    MessageQueue.js:349:47
<unknown>
    MessageQueue.js:106:26
__guard
    MessageQueue.js:297:10
callFunctionReturnFlushedQueue
    MessageQueue.js:105:17
