### ISSUE TITLE
I can't display any image from Listeo, product content  either

### ISSUE THREAD

**Issue by brygom** [inspireui/support#3710]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
I followed the instructions and solutions I found on Github, without finding a solution.
The images on my Listeo site are not displayed in the application, nor is any product content shown.
+ Product & version: FluxStore-listing 1.4.1

+ Flutter (or React Native) version: Flutter 1.17.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b041144f83 (8 days ago) • 2020-06-04 09:26:11 -0700
Engine • revision ee76268252
Tools • Dart 2.8.4

+ Testing Device/Simulator: iPhone 11(13.5) simulator
+ Screenshot issues (drag the file to attach here): 
![image](https://user-images.githubusercontent.com/313953/84543344-71b70080-acb8-11ea-8914-917dd63784b6.png)

![image](https://user-images.githubusercontent.com/313953/84543383-80051c80-acb8-11ea-995f-9ddd7bd09109.png)

![image](https://user-images.githubusercontent.com/313953/84544656-f014a200-acba-11ea-9ee9-97283f0ae328.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by brygom** [comment]
In the debug console, the app tries to load a "photo2-medium-medium.png.", this image doesn't exist, only exist "photo2-medium.png", how can fix it?

**Comment by minhcasi** [comment]
@brygom - pls try to check this solution https://docs.inspireui.com/fluxstore/performance/#2-image-optimization - thank you!

**Comment by brygom** [comment]
@minhcasi Thank you for your answer, but this solution does not apply for me, I've already tried without success.
What else can I try?

**Comment by minhcasi** [comment]
could you share the `lib/common` and `lib/config` folder - we will help for checking the issue - thank you!

**Comment by brygom** [comment]
Thank you @minhcasi I managed to fix this problem using the solutions of the following cases:
Now my problem is different, so I'll open another ticket.

https://github.com/inspireui/support/issues/3492
https://github.com/inspireui/support/issues/3434

**Comment by minhcasi** [comment]
Thank you for your sharing, let move to #3766
