### ISSUE TITLE
bitcode bundle could not be generated

### ISSUE THREAD

**Issue by TheEgyptianDevelopers** [inspireui/support#3711]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

bitcode bundle could not be generated because '/users/imac/source/ios/flutter/flutter.framework/flutter' was built without full bitcode. all frameworks and dylibs ford bitcode must be generated from xcode archive or install build file '/users/imac/source/ios/flutter/flutter.framework/flutter' for architecture armv7

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

![image](https://user-images.githubusercontent.com/6382309/84547102-18c08a00-ad03-11ea-87a4-442d9d69ed8d.png)

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by TheEgyptianDevelopers** [comment]
Detail Issues: bitcode bundle could not be generated because '/users/imac/source/ios/flutter/flutter.framework/flutter' was built without full bitcode. all frameworks and dylibs ford bitcode must be generated from xcode archive or install build file '/users/imac/source/ios/flutter/flutter.framework/flutter' for architecture armv7

    Product & version: Fluxstore 1.7.5

    Flutter (or React Native) version: flutter 1.17.3

    Testing Device/Simulator: mac/iPhone 11 max

    Screenshot issues (drag the file to attach here): up

**Comment by TheEgyptianDevelopers** [comment]
any updates?

**Comment by TheEgyptianDevelopers** [comment]
@minhcasi @trunghieuvn Can u help please I publish the android version on play store and it is live there, but the ios version not yet because I have always this problem from version fluxstore 1.7.4 and even on 1.7.5

**Comment by minhcasi** [comment]
@TheEgyptianDevelopers - pls check the following solutions:

1. make sure the ENABLE_BITCODE is Yes from the `ios/Podfile`
<img width="1164" alt="Screen Shot 2020-06-15 at 09 20 53" src="https://user-images.githubusercontent.com/1459805/84612005-84644c00-aee9-11ea-9322-c8643e4c5d60.png">

2. Make sure to run `flutter build ios` before opening the XCode for generate Archive file. pls double check https://docs.inspireui.com/fluxstore/delivery/

3. Try to clean up flutter cache on your mac os - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

**Comment by minhcasi** [comment]
Let us know if you have any further issue, feel free to open the ticket - thank you!
