### ISSUE TITLE
Issue with MStore Pro

### ISSUE THREAD

**Issue by Cloudcitycolombia** [inspireui/support#3712]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues:
I am working with the Pro version of Mstore,
I install in the npm project and run "npm start".
Then I go to Android Studio and open the project, start the application in the emulator and it works perfectly, but when I go to generate a signed apk release an error appears.

Can you help me please? Also, I don't quite understand how to add push notifications, I went to the app / build.gradle file but in the code I can't find where to add the OneSignal ID, should I add one more code?
Thanks for your support. 
+ Product & version:
Lastest version MStore Pro
+ Flutter (or React Native) version: 
"_from": "react-native@0.61.5",
+ Testing Device/Simulator: 
Pixel 2 API R
+ Screenshot issues (drag the file to attach here): 
When run the app on emulator:
![Captura de Pantalla 2020-06-12 a la(s) 4 36 06 p  m](https://user-images.githubusercontent.com/61888988/84548739-ffe8b200-accb-11ea-8875-f4240a7b4850.png)

When Build Signed APK Release:

![Captura de Pantalla 2020-06-12 a la(s) 4 00 37 p  m](https://user-images.githubusercontent.com/61888988/84548820-2c043300-accc-11ea-9922-147b52d6e766.png)
![Captura de Pantalla 2020-06-12 a la(s) 4 00 41 p  m](https://user-images.githubusercontent.com/61888988/84548824-2f97ba00-accc-11ea-8842-e87c1e54b74d.png)
![Captura de Pantalla 2020-06-12 a la(s) 4 00 45 p  m](https://user-images.githubusercontent.com/61888988/84548827-31fa1400-accc-11ea-9036-54884c157783.png)
![Captura de Pantalla 2020-06-12 a la(s) 4 00 52 p  m](https://user-images.githubusercontent.com/61888988/84548832-345c6e00-accc-11ea-8649-15958168a69c.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by luyx2412** [comment]
Hi @Cloudcitycolombia You can read the document to use Onesignal https://docs.inspireui.com/mstore/push-notification/ And the notification did not work on emulator or simulator, so if you want to test it, please use real device.

Thanks

**Comment by Cloudcitycolombia** [comment]
Thanks, but the problem is I can't generate Signed APK release.. when I try to generate the APK, appear this Errors I submitted with screenshots ☝🏽... what I can do?

**Comment by luyx2412** [comment]
Hi @Cloudcitycolombia The first please clean your project follow the screenshot, after that use build with android studio.
![image](https://user-images.githubusercontent.com/8909619/84783556-9cd08580-b013-11ea-819d-91874b71cf75.png)
![image](https://user-images.githubusercontent.com/8909619/84783588-a4902a00-b013-11ea-8d15-85f12c08cab2.png)

Thanks

**Comment by luyx2412** [comment]
HI @Cloudcitycolombia Can you upload your project to drive and invite inspireui.team@gmail to your folder or send via this email. I will fix and resend to you.

Thanks

**Comment by Cloudcitycolombia** [comment]
Hi @luyx2412, I will share my project .. Thanks for your support

**Comment by luyx2412** [comment]
Hi @Cloudcitycolombia the first please generate your keystore https://coderwall.com/p/r09hoq/android-generate-release-debug-keystores and make sure you add right location 
![image](https://user-images.githubusercontent.com/8909619/85417563-f4359f00-b599-11ea-9e63-e16c2b33ff9b.png)
![image](https://user-images.githubusercontent.com/8909619/85417568-f566cc00-b599-11ea-8f94-d46a6f6d7b05.png)

And i just tested and generate apk file from your project, everything worked normal
![image](https://user-images.githubusercontent.com/8909619/85417781-352db380-b59a-11ea-8299-e93ff98c40a1.png)

Thanks
