### ISSUE TITLE
How to remove the email sign up

### ISSUE THREAD

**Issue by mmasifashraf** [inspireui/support#3714]
Whats the best way to remove the email sign up and keep the sms sign up only? ![image](https://user-images.githubusercontent.com/44862509/84556984-c6499280-ad2f-11ea-95f9-c0410aca3844.jpeg)

**Comment by minhcasi** [comment]
@mmasifashraf - we suggest using Inspector Tool for further related question "How To Customer UI xx". Please refer to https://www.youtube.com/watch?v=yGMt3Y20Zmg
