### ISSUE TITLE
Add onsale product carsoul in home

### ISSUE THREAD

**Issue by mohamedibrahim89** [inspireui/support#3717]
Hii

Need to ask question can i add carosul in home app page for (onsale product , new product , featured product plz)
I add my pursache code alot of time before

**Comment by minhcasi** [comment]
@mohamedibrahim89 - please try to add following option to the config json
1. `featured: true` load the feature product
2. `onSale: true` load the onsale product

**Comment by mohamedibrahim89** [comment]
I try but no product show sorry I need to add three  product layout
for new product, featured product , onsale can u send me how can I add this in app home page
@minhcasi thxxx

**Comment by minhcasi** [comment]
@mohamedibrahim89 - did you try to add fully data that have feature product, onsale on your website, please share your config so that we could help for checking - thank you!
