### ISSUE TITLE
Flux store v 1.7.5 

### ISSUE THREAD

**Issue by mohmmadmoatz** [inspireui/support#3719]
fluxstore woocommerce  . when i search by arabic characters 
illegal percent encoding

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one with full information - thank you for your time!
