### ISSUE TITLE
[MStore Pro] Cannot process payment (bacs payment)

### ISSUE THREAD

**Issue by juraganwp** [inspireui/support#372]
Product: MStore Pro
Your Purchased Code: 17780922-7c4e-44ab-a1a8-1156a6b3b3f8

Hi, my last closed issues number 304 is still persistent in latest mstore version.
The order detail webview is not closed upon successfully transaction. I think this is urgent as i cant process any payment with bacs (bank transfer).

This is happening both on ios and android

Any help ? In video attached when using cod (cash on delielvery) is success.
@luyx2412 @minhtruong315 

Link to video : https://drive.google.com/a/juraganwp.com/file/d/1t4EgIBWl8ZPvarwktA8zfcHqINK3wgdk/view?usp=drivesdk

Best regards

**Comment by luyx2412** [comment]
HI @juraganwp Please access the video, let me see in your case.

Thanks

**Comment by luyx2412** [comment]
Hi @juraganwp I just checked the latest version Mstore, and everything worked normal with BACS. Can you debug to check the issue. https://docs.mstore.io/api-and-project-structure#debug-app-with-reacttotron

Thanks

**Comment by juraganwp** [comment]
hi @luyx2412 , when i click buy now i've got warning on reactotron
![confirm-order-click](https://user-images.githubusercontent.com/47637961/53929554-a8b76300-40c0-11e9-8a0e-70755616d178.png)

and this warning comes up when i click confirm order
`[
  "fd",
  "http://dream2.juraganwp.com/mstore-checkout/?order=JTdCJTIydG9rZW4lMjIlM0ElMjJnaWxrdW4lN0MxNTUzMDkwMTg4JTdDUHRwRUxwNVRPMlQ4akNHcXp4Unhscmd3ZEF0dEMzNzBCVmZMeEtZQzhFTCU3Q2ExZDI2NDcyNmEwMTVkMWZlMGYwZGExYTI0YWU2NmNiYjkwYWNkMjliNmIxNzQwMTVkMjhhMzAzOGVhMDBiNDglMjIlMkMlMjJjdXN0b21lcl9pZCUyMiUzQTElMkMlMjJzZXRfcGFpZCUyMiUzQWZhbHNlJTJDJTIycGF5bWVudF9tZXRob2QlMjIlM0ElMjJiYWNzJTIyJTJDJTIycGF5bWVudF9tZXRob2RfdGl0bGUlMjIlM0ElMjJEaXJlY3QlMjBiYW5rJTIwdHJhbnNmZXIlMjIlMkMlMjJiaWxsaW5nJTIyJTNBJTdCJTIyZmlyc3RfbmFtZSUyMiUzQSUyMnRlc3QlMjIlMkMlMjJsYXN0X25hbWUlMjIlM0ElMjJ1c2VyJTIyJTJDJTIyY29tcGFueSUyMiUzQSUyMiUyMiUyQyUyMmFkZHJlc3NfMSUyMiUzQSUyMmpha2FydGElMjIlMkMlMjJhZGRyZXNzXzIlMjIlM0ElMjIlMjIlMkMlMjJjaXR5JTIyJTNBJTIyamFrYXJ0YSUyMiUyQyUyMnN0YXRlJTIyJTNBJTIySkslMjIlMkMlMjJwb3N0Y29kZSUyMiUzQSUyMkpBS0FSVEElMjIlMkMlMjJjb3VudHJ5JTIyJTNBJTIySUQlMjIlMkMlMjJlbWFpbCUyMiUzQSUyMmlyd2FuMjM0NSU0MGdtYWlsLmNvbSUyMiUyQyUyMnBob25lJTIyJTNBJTIyKDEyMyklMjA0NTYtNzg5LTAlMjIlN0QlMkMlMjJzaGlwcGluZyUyMiUzQSU3QiUyMmZpcnN0X25hbWUlMjIlM0ElMjJ0ZXN0JTIyJTJDJTIybGFzdF9uYW1lJTIyJTNBJTIydXNlciUyMiUyQyUyMmFkZHJlc3NfMSUyMiUzQSUyMmpha2FydGElMjIlMkMlMjJjaXR5JTIyJTNBJTIyamFrYXJ0YSUyMiUyQyUyMnN0YXRlJTIyJTNBJTIySkslMjIlMkMlMjJjb3VudHJ5JTIyJTNBJTIySUQlMjIlMkMlMjJwb3N0Y29kZSUyMiUzQSUyMkpBS0FSVEElMjIlN0QlMkMlMjJsaW5lX2l0ZW1zJTIyJTNBJTVCJTdCJTIycHJvZHVjdF9pZCUyMiUzQTY4OCUyQyUyMnF1YW50aXR5JTIyJTNBMSU3RCU1RCUyQyUyMmN1c3RvbWVyX25vdGUlMjIlM0ElMjIlMjIlMkMlMjJjdXJyZW5jeSUyMiUzQSUyMklEUiUyMiUyQyUyMnNoaXBwaW5nX2xpbmVzJTIyJTNBJTVCJTdCJTIybWV0aG9kX2lkJTIyJTNBJTIyZnJlZV9zaGlwcGluZyUyMiUyQyUyMnRvdGFsJTIyJTNBJTIyMCUyMiU3RCU1RCUyQyUyMmNvdXBvbl9saW5lcyUyMiUzQSU3QiU3RCU3RA==",
  {
    "token": "gilkun|1553090188|PtpELp5TO2T8jCGqzxRxlrgwdAttC370BVfLxKYC8EL|a1d264726a015d1fe0f0da1a24ae66cbb90acd29b6b174015d28a3038ea00b48",
    "customer_id": 1,
    "set_paid": false,
    "payment_method": "bacs",
    "payment_method_title": "Direct bank transfer",
    "billing": {
      "first_name": "test",
      "last_name": "user",
      "company": "",
      "address_1": "jakarta",
      "address_2": "",
      "city": "jakarta",
      "state": "JK",
      "postcode": "JAKARTA",
      "country": "ID",
      "email": "irwan2345@gmail.com",
      "phone": "(123) 456-789-0"
    },
    "shipping": {
      "first_name": "test",
      "last_name": "user",
      "address_1": "jakarta",
      "city": "jakarta",
      "state": "JK",
      "country": "ID",
      "postcode": "JAKARTA"
    },
    "line_items": [
      {
        "product_id": 688,
        "quantity": 1
      }
    ],
    "customer_note": "",
    "currency": "IDR",
    "shipping_lines": [
      {
        "method_id": "free_shipping",
        "total": "0"
      }
    ],
    "coupon_lines": {}
  }
]`

then the order is successfully accept by woocommerce

**Comment by luyx2412** [comment]
Hi @juraganwp this is just console.warning to debug, don't worry about that. You need check the response return api.

Thanks

**Comment by juraganwp** [comment]
Hi @luyx2412 , the issues now resolved. For any of customers having this issues, this is how i fixed it.

Change the theme !

Looks like the webview doesnt load my theme files correctly, thats why some devices cant process the bacs payment and not detect the order-received page.

Hopefully in the future theres update to address bacs payment like cod payment, so it doesnt need to open webview and process the transaction on the background.
