### ISSUE TITLE
FluxNews How to change the words not included in the language file

### ISSUE THREAD

**Issue by haidarsalim** [inspireui/support#3720]
How do you change these words

FluxNews Version: 1.4.1
Flutter : v1.17.3
Testing Device/Simulator

![111](https://user-images.githubusercontent.com/54249914/84570510-adc09300-ad96-11ea-8dd3-6b9c6c2ee5ee.PNG)
![222](https://user-images.githubusercontent.com/54249914/84570512-aef1c000-ad96-11ea-817a-bb0d1850e140.PNG)

**Comment by minhcasi** [comment]
Sorry these text are not included from the translation, please change form these file
<img width="825" alt="Screen Shot 2020-06-15 at 10 29 25" src="https://user-images.githubusercontent.com/1459805/84615399-17ee4a80-aef3-11ea-9241-5acc90ab9e34.png">

<img width="852" alt="Screen Shot 2020-06-15 at 10 28 43" src="https://user-images.githubusercontent.com/1459805/84615342-fe4d0300-aef2-11ea-8afb-3ecaf1b3d587.png">


<img width="841" alt="Screen Shot 2020-06-15 at 10 29 50" src="https://user-images.githubusercontent.com/1459805/84615416-25a3d000-aef3-11ea-9e40-b6167dfe33ae.png">
