### ISSUE TITLE
payment and shipping methods issue

### ISSUE THREAD

**Issue by fahadmm98** [inspireui/support#3721]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: i tried to configure payment .dart but still payment methods dosnt show it just bring payment method from my site after  i choose one of them its direct it me to mu site as webview .

another issue is shiipping methods its gives zero cost for both two method (opencart)

+ Product & version: fluxStore 1.7.4 
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

![Screenshot_1591981465](https://user-images.githubusercontent.com/66878026/84572526-3a714e00-ada3-11ea-876a-1d0703b4749c.png)
![Screenshot_1591981450](https://user-images.githubusercontent.com/66878026/84572527-3ba27b00-ada3-11ea-9441-81306f2f2dae.png)
![Screenshot_1591981459](https://user-images.githubusercontent.com/66878026/84572528-3c3b1180-ada3-11ea-82cb-e97a27d52981.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@fahadmm98 - could i confirm these issues happened on Opencart ?

Could you try to test on the latest release `1.7.5` ?

**Comment by fahadmm98** [comment]
i test on new release 1.7.5 same issue and unfortunately  getting worst , shipping metho dosnt show pic same issue like payment

**Comment by minhcasi** [comment]
@minhtruong315 - pls help with investigating

**Comment by minhtruong315** [comment]
Hi @fahadmm98 can u send me common folder to check your issues?
Thanks

**Comment by fahadmm98** [comment]
[common.zip](https://github.com/inspireui/support/files/4788317/common.zip)

**Comment by fahadmm98** [comment]
why its redirected me to webview in payment  checkout it should be native

**Comment by minhtruong315** [comment]
Hi @fahadmm98 replace these files in screens/checkout folder
[Archive.zip](https://github.com/inspireui/support/files/4791626/Archive.zip)
install this lib
https://pub.dev/packages/flutter_html#-installing-tab-
to fix showing payment method image

I also checked your website, shipping methods are showing cost as well
![Simulator Screen Shot - iPhone X - 2020-06-17 at 16 34 03](https://user-images.githubusercontent.com/10402500/84882512-8f6dd680-b0b9-11ea-8910-d7fa58161af3.png)

Fluxstore opencart doesn't support native payment gateway

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
