### ISSUE TITLE
Category Screen Issue & Bundle id change issues

### ISSUE THREAD

**Issue by chocotacos** [inspireui/support#3723]
Previous Ticket #2996 

I have an issue with the category layout i have main category then sub category then sub sub categories
Accessories > Men Accessories > Wallets, Hats & all 

So i want to show layout like that mentioned above how to do that?

So how to show that in 1.7.0 they were showing sub categories atleast now they don't even

![Capture221](https://user-images.githubusercontent.com/55656013/84576822-1e86a000-add5-11ea-8264-d44713846ebf.PNG)

But in 1.7.4 there is just main category 
![Capture222](https://user-images.githubusercontent.com/55656013/84576824-234b5400-add5-11ea-8bcf-4df6fcb070e9.PNG)

2- I am using windows 10 want to change the source code of the project installed ubuntu in it but still having this error

![Capture141](https://user-images.githubusercontent.com/55656013/84577002-6954e780-add6-11ea-9cb1-4c5760db4968.PNG)

**Comment by minhcasi** [comment]
1. from the config config json pls update - ` "categoryLayout": "card"`
<img width="1092" alt="Screen Shot 2020-06-15 at 10 35 32" src="https://user-images.githubusercontent.com/1459805/84615719-f346a280-aef3-11ea-87e1-cc9582f01712.png">

2. We have not tested on Ubuntu, pls try to check this guide from Flutter document https://flutter.dev/docs/get-started/install/linux

**Comment by chocotacos** [comment]
@minhcasi please re open it its already selected card. & i have issue in changing package name in android studio & in visual studio in windows please help!!!!!!!!!!

**Comment by minhcasi** [comment]
@chocotacos - our team will help to check and follow up on this ticket #3686 - thank you!
