### ISSUE TITLE
Payment Getway Not working paypal Fluxstore MV

### ISSUE THREAD

**Issue by mdyunus24bd** [inspireui/support#3724]
My PayPal Express Checkout plugin payment gateway not working on your Fluxstore MV 1.7.5 version. see my website Checkout page not loading getaway page.
I see some problems on your 1.6.6b version but this time help to   @philipvu30  on skype. he asks Paypal enabled to give a **false** and I try it this time is working fine. but now this option I give a **false** on your 1.7.5 version is not working. please help us...
![Annotation 2020-06-13 231104](https://user-images.githubusercontent.com/56026816/84577538-2e4eb600-adce-11ea-8546-8d78ce65c3e7.jpg)
![Annotation 2020-06-13 231152](https://user-images.githubusercontent.com/56026816/84577540-33136a00-adce-11ea-967e-fbae9f70f5b4.jpg)

2nd problems I give a **is caching-true** see this problem
![Annotation 2020-06-07 232425](https://user-images.githubusercontent.com/56026816/84577567-78379c00-adce-11ea-9047-e271db95877c.jpg)
this option I give **is caching-false** its working fine

this is my project file link
https://drive.google.com/file/d/19sMXKMXX5rAmI97uc7ltrZXohFIf0hx1/view?usp=sharing

verify buying 

https://user-images.githubusercontent.com/56026816/77499667-2a189980-6e6c-11ea-985c-eacb506e8615.png

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one with full information - thank you for your time!
