### ISSUE TITLE
Payment Getway Not working paypal and currency not changing Fluxstore MV

### ISSUE THREAD

**Issue by yassiney120** [inspireui/support#3725]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
PAYMENT GATEWAY PAYPAL NOT WORKING AND PAYPAL CHECKOUT I TRY BOTH OF THEM
currency is not changing in product, cart, and checkout
in shipping method, it shows inexistent method
@minhcasi 
thank you
+ Product & version: 1.7.5
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: REAL DEVICE IPHONE 11 PRO MAX
+ Screenshot issues (drag the file to attach here): 
![IMG_5444](https://user-images.githubusercontent.com/8164673/84578302-16c6fb80-add5-11ea-9b02-e857f434661f.PNG)
![IMG_5441](https://user-images.githubusercontent.com/8164673/84578309-26dedb00-add5-11ea-863f-d42124703c93.PNG)
![IMG_5445](https://user-images.githubusercontent.com/8164673/84578312-2f371600-add5-11ea-9981-4fe6e9d37f8d.PNG)
![IMG_5446](https://user-images.githubusercontent.com/8164673/84578319-38c07e00-add5-11ea-81e7-32051c7c73f9.PNG)
<img width="1792" alt="Screen Shot 2020-06-14 at 3 50 09 AM" src="https://user-images.githubusercontent.com/8164673/84581485-8b5c6300-adf2-11ea-9176-b7afb723b6da.png">
![Uploading Screen Shot 2020-06-14 at 3.49.59 AM.png…]()
<img width="1792" alt="Screen Shot 2020-06-14 at 3 49 43 AM" src="https://user-images.githubusercontent.com/8164673/84581491-98795200-adf2-11ea-8063-3182175c60d1.png">

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**
MY SKYPE mohdar@fleure.ma
user yassiney12

#3514 

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by yassiney120** [comment]
Hello
Mr @minhtruong315  any news

**Comment by minhtruong315** [comment]
Hi @yassiney120 I messaged you on the skype. please check. Thanks

**Comment by yassiney120** [comment]
Hi , thank you mr @minhtruong315  so the payment method will work only with webiew 
Sill only 1 issues about currency

Thank you for your time

**Comment by minhtruong315** [comment]
Hi @yassiney120 I fixed currency issues in our source code. it has more changes. so you can check it on next release.
Thanks
