### ISSUE TITLE
Give me help. When I click the category in Apliaksi. Direct Apliaction Forclose

### ISSUE THREAD

**Issue by teampotlot** [inspireui/support#3726]
![image](https://user-images.githubusercontent.com/66760408/84578687-23117f80-adfa-11ea-9760-d6a580f9dd4e.png)

When I started the design using a bulder flux. and install it in cooding en. json. After opening categorory application Forclose

**Comment by teampotlot** [comment]
help me

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one with full information - thank you for your time!
