### ISSUE TITLE
Build APK Issue

### ISSUE THREAD

**Issue by Carlosdmendoza** [inspireui/support#3727]
Hi when I am trying to build the APK for the multi vendor app  using Android Studio I am having the following error: 
Error:Module 'source' production: java.lang.NoClassDefFoundError: com/android/resources/ResourceFolderType

Do you have any idea on what can I do?

**Comment by Carlosdmendoza** [comment]
I have submitted the form already, I hope you can respond soon I am not very happy with the purchase so far, and it's been hard there is no tutorials on how to build the multi vendor app after purchasing the product. I have the website already at https://emprendedorhn.com I have created the version 0.1 of my app just to see how would it look like on a phone but it's been 2 days now trying to figure this out on my own I would really appreciate your support in this matter.

**Comment by Carlosdmendoza** [comment]
![Flutter](https://user-images.githubusercontent.com/46724211/84590632-82b95c00-adf5-11ea-8f3f-961e342174d3.PNG)

![Error3](https://user-images.githubusercontent.com/46724211/84590633-8351f280-adf5-11ea-8427-5d061770d9a7.PNG)

It is worth saying that if I change the Java compiler To JAvaC I get that error. I have tried to run the Flutter Doctor command and it goes fine I also did a Flutter Update, then a flutter clean it worked but when I run a "flutter packages get " I got the error descripted in the screen shot I really needed a more convenient way to resolve this issues.

**Comment by minhcasi** [comment]
@Carlosdmendoza - just note that this is the basic issue from flutter environment. 

Could you confirm if you could run this example project from Flutter - https://flutter.dev/docs/get-started/test-drive?tab=vscode ?

We have the basic install guide from these links:
https://www.youtube.com/watch?v=3dv_8UerNpQ
https://www.youtube.com/watch?v=ReAUZDIgh2I

You could also run this script to check your flutter issue `flutter doctor`

**Comment by Carlosdmendoza** [comment]
I've done that already and it's showing the same flutter doctor is not showing any errors other than no Device connected.

**Comment by Carlosdmendoza** [comment]
I have also followed the tutorial you are saying step by step and same issue remains, It's worth saying that I was not able to make the pub get command because of the error I described on the screenshot.

**Comment by Carlosdmendoza** [comment]
Could you confirm if you could run this example project from Flutter - https://flutter.dev/docs/get-started/test-drive?tab=vscode ? 
I just did that and it worked no errors, there must be something with the app sourcecode itself I have installed everything that is required following steps on the video. It's urgent for me to fix that please help me I have a timefram I have to cover and I've been stuck on that for 3 days now. I will aprpreciate your help in this matter.

**Comment by minhcasi** [comment]
@Carlosdmendoza - pls help to check this script
```
flutter channel stable
flutter upgrade --force
flutter clean
flutter pub get
```

**Comment by minhcasi** [comment]
Also check this solution to clean up the cache - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

**Comment by Carlosdmendoza** [comment]
I tried all that but still no results I am getting the following error when running the first four commands 
![Captura1](https://user-images.githubusercontent.com/46724211/84824691-96bfb200-afdd-11ea-9d36-7dd7776330e3.PNG)

I tried all of the steps also as you adviced to clean up the cache and still not working this is not as easy s you advertise if you cannot provide me with a solution today I will need a refund please.

**Comment by minhcasi** [comment]
Hi, you could try to remove and reinstall the flutter to see if it work fine.

Sorry as this is kind of basic Flutter install that is not included from our support scope, please try your best - if you could not cover and run the app, you could process refund on this link https://help.market.envato.com/hc/en-us/articles/202821460-Can-I-Get-A-Refund- - thanks
