### ISSUE TITLE
Getting Started issues

### ISSUE THREAD

**Issue by kermalk** [inspireui/support#3728]
Hi,
I just purchased the fluxstore Pro and i have couple of questions

1- The drag and drop to re-arrange the category arrangement isn't working in any part of the mac version, for the categories drag&drop for example or for the menu icons
2- The products are not showing properly in the live preview in the builder, i can't see the variations of each product or when i write in the search bar i get no result. Also the currency showing $ while we use SAR
3- i want to disable the reviews, how to do that
4- i want to update the logo in the login page as it's not updated like in the app home
5- how to activate the social media login from the builder ?
6- how to add the contact details like what's app and phone
7- I can't update the About us section in the profile page, its not clickable
8- How to add instagram account layout in the home page
9- How to add products On Sale in the home

Thanks in advance for your support.

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one with full information - thank you for your time!
