### ISSUE TITLE
@michmj - do you any feedback?

### ISSUE THREAD

**Issue by michmj** [inspireui/support#3729]
@michmj - do you any feedback?

Yes nothing works I am really tired to try everything and nothing works I am not a developer and I can see many others have the same problem. I just want a refund unless you help me to build the app for me
_Originally posted by @minhcasi in https://github.com/inspireui/support/issues/3638#issuecomment-643075177_

**Comment by minhcasi** [comment]
Hi, you could refund on this link - https://help.market.envato.com/hc/en-us/articles/202821460-Can-I-Get-A-Refund- - thanks for your time
