### ISSUE TITLE
[Beonews] Comments + push notificatios

### ISSUE THREAD

**Issue by hadi13** [inspireui/support#373]
Mandatory Info (please complete the following information):

**

1. Comments are not delivered to my admin wp panel!!!!

**
2.
your push notification is not for expo version?!!
https://beonews.inspireui.com/advance-customize/push-notification
what about expo version??
notification: {
AppId: '4f52b601-6f4e-4785-8e19-73hshsb6dfa',
NewAppId: '4f52b601-6f4e-4785-8e19-29sjswb6dfa',
},

what is the NewAppId???

Product: [Beonews]
Your Purchased Code: 2b7fa788-ea4d-4d1c-bb3a-4bf22a499783

Describe the issues
I have an issue since the first time, the comments are not delivered to the WP admin?
your push notification in the documentation is not for expo version?!!

Additional context
I need to solve it ASAP

**Comment by minhcasi** [comment]
https://app.intercom.io/a/apps/xro9xnfd/inbox/inbox/2664005/conversations/21101461872

**Comment by hadi13** [comment]
What is that?

**Comment by luyx2412** [comment]
HI @hadi13 Currently the expo version did not support push notification, please move to Beonews pro version.

Thanks

**Comment by levi-beers** [comment]
I can confirm comments are not being sent to admin panel using latest Beonews Pro

**Comment by hadi13** [comment]
> HI @hadi13 Currently the expo version did not support push notification, please move to Beonews pro version.
> 
> Thanks

WHAT!!!
they said it supports it !!

**Comment by minhcasi** [comment]
@hadi13, use the folder beonew-pro for support the onesignal, instead of the beonew-expo, the Expo library is not still support for Expo - thanks

**Comment by hadi13** [comment]
really I have no comments!! 
so what is this issue!!
<img width="1320" alt="screen shot 2019-03-08 at 11 45 05 am" src="https://user-images.githubusercontent.com/2642454/54018117-e8ea1480-4198-11e9-8a2d-575efcfd25cf.png">

**Comment by hadi13** [comment]
ok, solved 
why the app is not running on IOS without Metro Bundler on port 8081.                                         │

**Comment by luyx2412** [comment]
Hi @hadi13 The port 8081 is default original react native. You can read the document to know about it https://facebook.github.io/react-native/docs/troubleshooting#terminating-a-process-on-port-8081.

Thanks

**Comment by hadi13** [comment]
I am having buil issue on Android 
cause error 2 no such file or directory

**Comment by luyx2412** [comment]
Hi @hadi13 Can you provide the screenshot? You can use `react-native link` to link library to project.

Thanks

**Comment by luyx2412** [comment]
Hi @hadi13 Please follow the article to see specific error, and take the screenshot.
https://stackoverflow.com/questions/16633956/android-studio-where-is-the-compiler-error-output-window

Thanks

**Comment by hadi13** [comment]
error still there !!

**Comment by luyx2412** [comment]
Hi @hadi13 i sent you to debug why appear this error, please follow the article and take me the screenshot.

Thanks
