### ISSUE TITLE
Store issue in product page

### ISSUE THREAD

**Issue by investisocial** [inspireui/support#3730]
Hi,
I've a problem with store information on the product page.
If you check the attached screenshot, you can see an issue with vendor information. There isn't a logo store and then if you click on the vendor profile, you will get a different vendor page where the header is not correct. It only seems an image error, because products and vendor information are correctly shown. If I go into the stores tab I correctly see vendor's profiles. This issue occurred only in product page. Can you help me, please?

FluxStore-vendor-1.7.4

Flutter 1.17.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b041144f83 (10 days ago) • 2020-06-04 09:26:11 -0700
Engine • revision ee76268252
Tools • Dart 2.8.4

![Store_Issue](https://user-images.githubusercontent.com/57216890/84592324-19f9d000-ae45-11ea-85d3-9564796db1cf.jpg)
![Store_Issue_2](https://user-images.githubusercontent.com/57216890/84592325-1b2afd00-ae45-11ea-8593-a014c1965cc0.jpg)
![Store_Tab_OK_1](https://user-images.githubusercontent.com/57216890/84592326-1ebe8400-ae45-11ea-8b8f-51ff7040b984.jpg)
![Store_Tab_OK_2](https://user-images.githubusercontent.com/57216890/84592327-1fefb100-ae45-11ea-8964-e546a4c765bc.jpg)
![envato_panel](https://user-images.githubusercontent.com/57216890/84592330-23833800-ae45-11ea-92d3-04632b07c8f7.jpg)

Thank you so much for your time 😊
Regards
Carlo

**Comment by minhcasi** [comment]
@investisocial - noted with investigating and improve on this issue - thank you!

**Comment by investisocial** [comment]
Hi,
i've ordered as your instruction, but now i see categories under the stores :(
Can you help me, please..
![Store_Screen_Issue](https://user-images.githubusercontent.com/57216890/84641148-f1341200-aefa-11ea-84bd-21793c55fb8d.jpg)

**Comment by minhcasi** [comment]
You could try to use this file - thank you! 
[index.dart.txt](https://github.com/inspireui/support/files/4783998/index.dart.txt)

**Comment by investisocial** [comment]
You are number one! Thank you..
I'm going now to try app releasing..
Regards
Carlo

**Comment by minhcasi** [comment]
Hi Carlo, we're glad that it help, please give us some feedback/rating to this page https://codecanyon.net/downloads  if the product is helpful for your business, we are working hard to update more awesome and powerful features on next coming version release. Let us know if you have any feedback. Thank you very much 😊

**Comment by investisocial** [comment]
Great! I successfully built my app! I've given you a five stars feedback :)
If you can, I only still have a store issue on the product page.
Can you help me with it?
Thank you.
Regards
Carlo

**Comment by minhcasi** [comment]
Yes sure Carlo, please help to the screenshot of the issue - you could create a new ticket (without sending verify code) or reopen this one.

Thank you so much for the rating!
