### ISSUE TITLE
Booking issues

### ISSUE THREAD

**Issue by APPLIWEBSOLUTIONS** [inspireui/support#3731]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by APPLIWEBSOLUTIONS** [comment]
Hi !

The App is buetifull (thanks your help, last time).

Now I have BIG BIG issue regarding the app and the website (on Listeo).

Booking didn't work (I receive email confirmation) and nothing on customer dashboard.

Rating listing didn't work as well.

And other point ? When I create an account from the app, am I a guest or an owner ? When I check on wordpress, Im a subscriber....

**Comment by APPLIWEBSOLUTIONS** [comment]
https://bnbtunisie.com/wp-content/uploads/2020/06/Screenshot_20200614-122056.jpg

**Comment by philipvu30** [comment]
Hi,

Please send a support account, config.dart/config.json files, and your project after running command flutter clean to my email toan@inspireui.com. I'll help you check the issue.

Thank you.

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
