### ISSUE TITLE
Category Tab firstly show store's tab

### ISSUE THREAD

**Issue by investisocial** [inspireui/support#3732]
Hi,
when i go in category page, i would want to automatically show firstly the store's tab.
How can do it?
Now it firstly shows all categories, can I change it?
Thank you.
![Category_Tab_Store_Showing](https://user-images.githubusercontent.com/57216890/84593486-c8edda00-ae4c-11ea-9e68-138a20f7c436.jpg)

FluxStore-vendor-1.7.4

Flutter 1.17.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b041144f83 (10 days ago) • 2020-06-04 09:26:11 -0700
Engine • revision ee76268252
Tools • Dart 2.8.4

Thank you so much for your time 😊
Regards
Carlo
![envato_panel](https://user-images.githubusercontent.com/57216890/84593492-cf7c5180-ae4c-11ea-812e-1563ff1a8dee.jpg)

**Comment by minhcasi** [comment]
You could order this Widget on top of the array list
<img width="1223" alt="Screen Shot 2020-06-15 at 10 54 23" src="https://user-images.githubusercontent.com/1459805/84616563-94365d00-aef6-11ea-961f-e9d9adaaec95.png">


ex
```
children: <Widget>[
                    Padding(
                      padding: EdgeInsets.symmetric(horizontal: 20),
                      child: Text(
                        S.of(context).stores,
                        style: TextStyle(fontWeight: FontWeight.w600),
                      ),
                    ),
                    Padding(
                      padding: EdgeInsets.symmetric(horizontal: 20),
                      child: Text(
                        S.of(context).categories,
                        style: TextStyle(fontWeight: FontWeight.w600),
                      ),
                    ),
                    
                  ],
```

**Comment by minhcasi** [comment]
kindly move to your all comments to one ticket support #3730

**Comment by investisocial** [comment]
Hi, 
i've ordered as your instruction, but now i see categories under the stores :(
Can you help me, please..
![Store_Screen_Issue](https://user-images.githubusercontent.com/57216890/84639971-60106b80-aef9-11ea-96c8-15e5ddaa7c70.jpg)
