### ISSUE TITLE
Change SMS default country

### ISSUE THREAD

**Issue by haidarsalim** [inspireui/support#3733]
I cannot find the file to change the login country
FluxNews Version: 1.4.1
Flutter : v1.17.1
![333](https://user-images.githubusercontent.com/54249914/84594800-52a5a380-ae5d-11ea-9bb9-abc3fea12595.PNG)

_I have previously checked into this ticket
https://github.com/inspireui/support/issues/3629_

**Comment by TheEgyptianDevelopers** [comment]
u will find it on the new location :/source/lib/common/constants/general.dart
or 
right-click in the project and press find in Path and search for (class LoginSMSConstants)
![Screen Shot 2020-06-14 at 4 53 11 PM](https://user-images.githubusercontent.com/6382309/84596785-027c1080-ae60-11ea-8be0-2819f0116505.png)

**Comment by minhcasi** [comment]
@haidarsalim - pls use solution from @TheEgyptianDevelopers

**Comment by haidarsalim** [comment]
My project does not contain a constants file
![3333](https://user-images.githubusercontent.com/54249914/84763498-f796bc80-afd4-11ea-868c-3cbf6bd66e21.PNG)

**Comment by TheEgyptianDevelopers** [comment]
1-right-click in the project ( the source folder) not into ( lib ) folder only
2- press find in Path and search for (class LoginSMSConstants)

**Comment by haidarsalim** [comment]
> 1-right-click in the project ( the source folder) not into ( lib ) folder only
> 2- press find in Path and search for (class LoginSMSConstants)

The same problem

**Comment by TheEgyptianDevelopers** [comment]
please re-download the file again from ThemeForest and try search again, and give us feedback, so we can help

**Comment by haidarsalim** [comment]
I only need to locate the file FluxNews Version: 1.4.1
