### ISSUE TITLE
Duplicate products when scrolling down for more loading

### ISSUE THREAD

**Issue by dragooninasia** [inspireui/support#3734]
Thanks Fixed

**Comment by dragooninasia** [comment]
Also there is a major issue in regards to the plugin for the Mstore.  People singing up using the mobile app to become a seller is automatic even thought they were not approved.

**Comment by dragooninasia** [comment]
There is another issue which i just discovered.  When trying to load more items, the rest of the items don't show from that store.  It keeps repeating the 10 items over and over again.

**Comment by minhtruong315** [comment]
Hi @dragooninasia can u send me common folder via email: truong@inspireui.com
I will help you check these issues
Thanks

**Comment by dragooninasia** [comment]
Here is the common file.

**Comment by dragooninasia** [comment]
It doesn’t do it anymore, but now the products on the vendor stores don’t show up on their store in the category section.

**Comment by minhtruong315** [comment]
Hi @dragooninasia please send common folder via my email. thanks

**Comment by dragooninasia** [comment]
I already did.

**Comment by minhtruong315** [comment]
Hi @dragooninasia I dont see any email.

**Comment by dragooninasia** [comment]
I put the files up on the posting instructions also that you had when making the post.  And I sent it to this email address.

**Comment by minhtruong315** [comment]
Hi @dragooninasia I dont see any email. Can u upload it to github?
Thanks

**Comment by dragooninasia** [comment]
I don’t understand why each time we build out to sim or on mobile phone, it sometimes works and sometimes doesn’t.  Do you guys have the app going through to your system that affects this?  The Duplicate products don’t happen anymore.  But I would like to know if inspire has all or some access to the app coding or functions after publish?  

It’s just odd that functions work some times and don’t the next minute with no changes to the source code on our end.

**Comment by minhtruong315** [comment]
Hi @dragooninasia I dont understand what are your issues now?
Can u explain your issues and send me common folder to my email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/3734
Thanks

**Comment by minhtruong315** [comment]
supported via email.
