### ISSUE TITLE
Authentication Issue

### ISSUE THREAD

**Issue by gupanant** [inspireui/support#3736]
Can't really figure out the authentication issue on our site. Tried installing the Basic-Auth plugin, changed htaccess, restarted apache. But nothing seems to work. 

Here is the screenshot 
<img width="868" alt="Screen Shot 2020-06-14 at 11 05 42 AM" src="https://user-images.githubusercontent.com/5823667/84600574-16f3e500-ae2f-11ea-994d-401c20c0f63a.png">

Here is my [phpinfo](https://bit.ly/3flOE4u) file. I have also dumped the headers at the bottom.

**Comment by minhcasi** [comment]
@gupanant Please add the following code on your .htaccess file.

RewriteCond %{HTTP:Authorization} ^(.)
RewriteRule ^(.) - [E=HTTP_AUTHORIZATION:%1]

**Comment by gupanant** [comment]
Added still same issue. Doesn't work. Here is how my .htaccess file looks like : 
`<IfModule mod_rewrite.c>
RewriteEngine On
RewriteCond %{HTTP:Authorization} ^(.)
RewriteRule ^(.) - [E=HTTP_AUTHORIZATION:%1]
RewriteBase /
RewriteRule ^index\.php$ - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization},L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>

# php -- BEGIN cPanel-generated handler, do not edit
# Set the “ea-php74” package as the default “PHP” programming language.
<IfModule mime_module>
  AddHandler application/x-httpd-ea-php74 .php .php7 .phtml
</IfModule>
# php -- END cPanel-generated handler, do not edit
`

**Comment by gupanant** [comment]
Any updates on this ?

**Comment by vumanhsn97** [comment]
@gupanant 
Try with this solution: https://github.com/woocommerce/woocommerce/issues/19649#issuecomment-538004143

**Comment by gupanant** [comment]
Already tried that, doesn't work. I changed to Litespeed server from fast-cgi but same issue. Can someone check on remote ?

I tried with both of these htaccess

```
#BEGIN WordPress
 <IfModule mod_rewrite.c>
 #METALOCATOR: This line added to allow basic authentication under FastCGI
 SetEnvIf Authorization .+ HTTP_AUTHORIZATION=$0
 RewriteEngine On
 RewriteCond %{HTTP:Authorization} ^(.)
 RewriteRule ^(.) - [E=HTTP_AUTHORIZATION:%1]
 RewriteBase /
 RewriteRule ^index\.php$ - [L]
 RewriteCond %{REQUEST_FILENAME} !-f
 RewriteCond %{REQUEST_FILENAME} !-d
 RewriteRule . /index.php [L]
 RewriteRule ^wp-json/.* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization},L]
 </IfModule>
 #END WordPress
```

And

```
#BEGIN WordPress
 <IfModule mod_rewrite.c>
 #METALOCATOR: This line added to allow basic authentication under FastCGI
 SetEnvIf Authorization .+ HTTP_AUTHORIZATION=$0
 RewriteEngine On
 RewriteBase /
 RewriteRule ^index\.php$ - [L]
 RewriteCond %{REQUEST_FILENAME} !-f
 RewriteCond %{REQUEST_FILENAME} !-d
 RewriteRule . /index.php [L]
 RewriteRule ^wp-json/.* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization},L]
 </IfModule>
 #END WordPress
```

**Comment by vumanhsn97** [comment]
@gupanant 
Can you send me your account login and wordpress site to vumanhsn97@gmail.com?

**Comment by gupanant** [comment]
Sent you an email. Thanks

**Comment by minhcasi** [comment]
@gupanant - we have detected that the `mod_rewrite` have not enabled from your website, please help to contact the Hosting provider to enable this option ?

**Comment by gupanant** [comment]
I know for the fact that it is enabled because I tried redirect in htaccess and it worked. We are using Litespeed server on this.

**Comment by minhcasi** [comment]
@gupanant - pls try your best to enable the Rest API by using this guide
https://github.com/woocommerce/woocommerce/wiki/Getting-started-with-the-REST-API

You could also enable the https to see if it works

**Comment by minhcasi** [comment]
Let us know your checking, thank you!

**Comment by gupanant** [comment]
It was something else. I installed your demo store on dev and saw that you were using a plugin for images webp express and one more. When I installed your second plugin and copied the web-express .htaccess rules it started working.
