### ISSUE TITLE
notification for ios 

### ISSUE THREAD

**Issue by abdulmoueidzanati** [inspireui/support#3737]
firebase pushnotification not working, i did all which they describe in documentation for getting ios notification, i also uploaded authkey fron apple developer acount i also removed code code from app swift class
and also i enable background fetch

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**
LICENSE CERTIFICATE : Envato Market Item
==============================================

This document certifies the purchase of:
ONE REGULAR LICENSE
as defined in the standard terms and conditions on Envato Market.

Licensor's Author Username:
InspireUI

Licensee:
DIGITAL FLOW

Item Title:
Fluxstore Pro - Flutter E-commerce Full App for Magento, Opencart, and Woocommerce

Item URL:
https://codecanyon.net/item/fluxstore-the-universal-woocommerce-magento-opencart-mobile-app-by-flutter-framework/24020929

Item ID:
24020929

Purchase Date:
2020-01-08 09:34:01 UTC

For any queries related to this document or license please contact Help Team via https://help.author.envato.com

Envato Pty. Ltd. (ABN 11 119 159 741)
PO Box 16122, Collins Street West, VIC 8007, Australia

==== THIS IS NOT A TAX RECEIPT OR INVOICE ====

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one with full information - thank you for your time!
