### ISSUE TITLE
Product not show

### ISSUE THREAD

**Issue by nassir1991** [inspireui/support#3738]
Hi, i have problem when change category id the FMV app not show any products. I already follow the common issue but no solution. Please help. Please give more detail documentation on this issue.

**Comment by minhcasi** [comment]
@nassir1991 - Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by nassir1991** [comment]
> @nassir1991 - Thank you for the feedback.
> 
> Please help us to submit this form and fill all required info to continue with the support - [http://verify.inspireui.com/ -](http://verify.inspireui.com/%C2%A0-) please don't share the purchase code or screenshot public here as another user will use it for activation.
> 
> We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

i already submit the form. PLS Check

**Comment by iamar1k92** [comment]
following this issue..

**Comment by IAPCorporate** [comment]
I have the same issue with 1.7.5 Fluxtore Shopify... every time there is an update; I say oh they would finally have fixed all these bugs but then it comes with a ton of new bugs.

**Comment by iamar1k92** [comment]
Please check and provide fix asap.

**Comment by minhcasi** [comment]
@nassir1991 - could you help to share the image screenshot of the issues? Do you mean the issue on the category page? Which Dokan or WCFM you are using?

**Comment by nassir1991** [comment]
> @nassir1991 - could you help to share the image screenshot of the issues? Do you mean the issue on the category page? Which Dokan or WCFM you are using?

Wcfm. The product not show on app after i change category id. Tried follow the common issue but still same. Let me know if u need my wordpress admin details

**Comment by nassir1991** [comment]
@minhcasi Wcfm. The product not show on app after i change category id. Tried follow the common issue but still same. Let me know if u need my wordpress admin details

**Comment by iamar1k92** [comment]
Wcfm

**Comment by philipvu30** [comment]
Hi,

In lib/common/config/general.dart , please set isCaching to false

![image](https://user-images.githubusercontent.com/54442328/84886383-8df2dd00-b0be-11ea-8e76-5d703577d71b.png)

![image](https://user-images.githubusercontent.com/54442328/84886498-b5e24080-b0be-11ea-9684-16c6f72947c7.png)

**Comment by IAPCorporate** [comment]
It's set to false. I download the project and run it without any changes. I don't even see their products. The problem only exists in home page. If I go to a category then I see everything.

**Comment by iamar1k92** [comment]
I/flutter ( 5019): [2020-06-17 21:03:08.553173Z][Tklakish][wocommerce_api][04:03:08.553098] getAsync END [endPoint:products?status=publish&lang=ar&per_page=20&page=1&category=520] url:products?status=publish&lang=ar&per_page=20&page=1&category=520
I/flutter ( 5019): #0      int._throwFormatException (dart:core-patch/integers_patch.dart:133:5)
I/flutter ( 5019): #1      int._parseRadix (dart:core-patch/integers_patch.dart:144:16)
I/flutter ( 5019): #2      int._parse (dart:core-patch/integers_patch.dart:102:12)
I/flutter ( 5019): #3      int.parse (dart:core-patch/integers_patch.dart:65:12)
I/flutter ( 5019): #4      new Store.fromWCFMJson (package:fstore/vendor/store/store_model.dart:123:14)
I/flutter ( 5019): #5      WCFMWidget.updateProductObject (package:fstore/widgets/frameworks/wcfm/index.dart:16:27)
I/flutter ( 5019): #6      WooCommerce.fetchProductsByCategory (package:fstore/services/woo_commerce.dart:382:43)
I/flutter ( 5019): <asynchronous suspension>
I/flutter ( 5019): #7      Services.fetchProductsByCategory (package:fstore/services/index.dart:193:23)
I/flutter ( 5019): #8      ProductModel.getProductsList (package:fstore/models/product/product_model.dart:116:39)
I/flutter ( 5019): #9      ProductsPageState._renderItemCategory.<anonymous closure> (package:fstore/screens/products/products.dart:274:59)
I/flutter ( 5019): #10     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
I/flutter ( 5019): #11     TapGestureRecognizer.handleTapUp (package:f
I/flutter ( 5019): 41
I/flutter ( 5019): 41

**Comment by philipvu30** [comment]
Hi,

Please just set the isCaching to false and replace the categories' id in your config_xx.json to match the categories' id on your website.

![image](https://user-images.githubusercontent.com/54442328/84974037-ac9fb500-b14c-11ea-8cda-0602570bdaf7.png)

**Comment by IAPCorporate** [comment]
I did not change anything, downloaded the script, and ran it... it doesn't show their products... i then changed with fluxbuilder and it doesn't work... it works fine on fluxbuillder

**Comment by philipvu30** [comment]
@IAPCorporate  Well, please head to lib/common/config/general.dart and set isCache to false.
Thanks.

**Comment by philipvu30** [comment]
Closed as no response in 2 days. 

If you are happy with our services/support, would you mind rating us on your [download page](https://codecanyon.net/downloads)?
We truly appreciate your help.
