### ISSUE TITLE
Product doesn't fetch in app (Fluxstore Listing App)

### ISSUE THREAD

**Issue by FaizalAndro** [inspireui/support#3743]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: Products doesn't fetching through my Wordpress website into app. I m using Listeo Theme and Flux store listing app. I uploaded all the plugins and generated woocommerce rest API as well. Setting up category but still issue persist. Please help if possible join me in teamviewer. For any license regarding matter let me know, I will send you my license file to you.

+ Product & version:FluxStore Lisiting 1.4.1
+ Flutter (or React Native) version: Flutter
+ Testing Device/Simulator: Physical Device Android(Realme 2 Pro)
+ Screenshot issues (drag the file to attach here): ![Screenshot 2020-06-15 at 2 03 11 PM](https://user-images.githubusercontent.com/37078576/84635684-2a777c80-af11-11ea-8e65-fe5af08599ca.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by FaizalAndro** [comment]
Hi, when I get reply

**Comment by philipvu30** [comment]
Hi,

Please send a support account, config.dart/config.json files, and your project after running command flutter clean to my email toan@inspireui.com. I'll help you check the issue.

Thank you.

**Comment by FaizalAndro** [comment]
Hi, I send the mail hope get a reply soon

**Comment by philipvu30** [comment]
Hi,

Send you the fixed project. Please check.

**Comment by FaizalAndro** [comment]
Hi, Give me google drive access to download

**Comment by philipvu30** [comment]
Hi @FaizalAndro,

Did it solve your issue?

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Comment by FaizalAndro** [comment]
Hi, There are many bugs in-app. I m listed all please have a look at it. 

1. APP BOOKED ITEMS   NOT SHOWING IN "MY ORDER HISTORY"
2. SLOT WISE NOT ABLE   TO BOOK, DOUBLE BOOKING HAPPENING WITH SAME TIME
3. MULTIPLE EXTRA SERVICE NOT ABLE TO SELECT
4. SHIPPING ADDRESS NOT THERE WHILE BOOKING
5. COMPLETED LISTING   ALSO USER ABLE TO CANCEL
6. ORDER PRICE TAX NOT SHOWING IN ORDER HISTORY
--

Please Have a look and resolve it

**Comment by minhcasi** [comment]
Hi, thank you for your feedback, as the ticket did not reopen so that they have not aware of the comment. 

Please note that your latest feedbacks is not about the issues because these features are not available from the current app.

Let us know if you have any further question - thank you!

**Comment by FaizalAndro** [comment]
APP BOOKED ITEMS NOT SHOWING IN "MY ORDER HISTORY"

**Comment by FaizalAndro** [comment]
When will you reply me?

**Comment by minhcasi** [comment]
@FaizalAndro - We sincerely apologize for the delay, could you clarify detail screenshot of the booking feature? 

Could I check if you are using the Listeo template? and also active the booking on the wordpress side? Thank you for your time

**Comment by FaizalAndro** [comment]
![Screenshot_2020-07-06-17-32-26-57_4e946608ab7baa8aab8918d5058c4fac](https://user-images.githubusercontent.com/37078576/86591241-ce9f9100-bfae-11ea-8b35-77a9f2b50589.png)


Mail me privately on this email address, I will share you wordpress site login.

**Comment by minhcasi** [comment]
hi, pls send to inspireui.team@gmail.com - thank you!

**Comment by FaizalAndro** [comment]
Already sent but didn't get any response yet

**Comment by minhcasi** [comment]
@FaizalAndro - sorry could i know your email to check from the team inbox, please share your email address here, thank you for your patience

**Comment by FaizalAndro** [comment]
faizalkhan8130@gmail.com

**Comment by FaizalAndro** [comment]
Sent email and password of my website, for last 5-6 days but don't know when will you reply back

**Comment by minhcasi** [comment]
@philipvu30 - pls help to check the My Order issue - if could note to the backlogs if this feature is not ready - thank you!

**Comment by FaizalAndro** [comment]
How much time assigned developer to solve my priority based inquiry?

**Comment by philipvu30** [comment]
Hi,

The booking feature has been fixed. Please refer to this [answer](https://github.com/inspireui/support/issues/4087#issuecomment-658688685) to update your app.

Thank you.

**Comment by FaizalAndro** [comment]
![Capture3](https://user-images.githubusercontent.com/37078576/87551282-c42b7880-c6cd-11ea-9dcb-2c251b7e0ab5.PNG)
BookStatus Error Everywhere

**Comment by FaizalAndro** [comment]
Also, I set   "IsRequiredLogin": true,
But it doesn't work

**Comment by philipvu30** [comment]
> Also, I set "IsRequiredLogin": true,
> But it doesn't work

This option only hides the Done button on OnBoardingScreen. I don't know if this is a suitable behavior or not.
If you have any suggestions, kindly post it here and we'll consider adding it.

Thank you.

**Comment by FaizalAndro** [comment]
![Capture3](https://user-images.githubusercontent.com/37078576/87551282-c42b7880-c6cd-11ea-9dcb-2c251b7e0ab5.PNG)
BookStatus Error Everywhere

**Comment by philipvu30** [comment]
In lib/common/constants.dart -> add this line enum BookStatus { booked, unavailable, waiting, confirmed, cancelled, error }

**Comment by FaizalAndro** [comment]
Problem still exist, Now in order history it just loading nothing happened. Also one more issue I m facing on booking screen.
![WhatsApp Image 2020-07-16 at 12 29 54 PM (1)](https://user-images.githubusercontent.com/37078576/87637763-5a0fe380-c760-11ea-996b-753b67d0b5c1.jpeg)
![WhatsApp Image 2020-07-16 at 12 29 54 PM](https://user-images.githubusercontent.com/37078576/87637766-5aa87a00-c760-11ea-8ab8-a402e3de7173.jpeg)

**Comment by philipvu30** [comment]
Hi,

Image 1: I've already tested several times on our demo apps and it's still fine. Also, the booking that sends to the system is in "waiting for confirmation" status, which means it won't show up in the WooCommerce orders until the owner accepts it.

Image 2: These non-null String errors usually occur because of lacking information on that item. I guess your listing is missing a name or a tagline.

**Comment by FaizalAndro** [comment]
1. I tried so many times, but it just shows loading icon. Also I checked it after accepting booking service through my website.

2. This non-null appeared when I add your booking and service code, before that it was not appear.

I can share my source code and website logins please have a look

**Comment by philipvu30** [comment]
Hi,

Please send them to my email: toan@inspireui.com

**Comment by philipvu30** [comment]
Hi,

1. I don't encounter this problem with your config files.
2. In lib/screens/detail/booking/thumbnail.dart add `?? ''` to this line
![image](https://user-images.githubusercontent.com/54442328/87659658-19c45b80-c788-11ea-9001-44aff274f61e.png)

**Comment by FaizalAndro** [comment]
> Hi,
> 
> Please send them to my email: [toan@inspireui.com](mailto:toan@inspireui.com)

Sent an email with code and website detail, please check.... Only order page issue @philipvu30

**Comment by philipvu30** [comment]
Hi,

Please replace this file in lib/screens/orders.dart
[orders.dart.zip](https://github.com/inspireui/support/files/4935581/orders.dart.zip)

**Comment by FaizalAndro** [comment]
@philipvu30 Thanks for your great effort but there is many problems still
1. Total Prices shows always zero
2. Once booking approved my listeo theme vendor, status of order still shows pending
3. Most important, it does not show more than 2 orders in  order history

![Screenshot_1594960451](https://user-images.githubusercontent.com/37078576/87749119-6609ad00-c815-11ea-81d8-00dfc9fdcd98.png)

**Comment by khalidsharif** [comment]
@FaizalAndro  did solve the order history issue ? I am facingg the same thing now.

**Comment by FaizalAndro** [comment]
Not yet, Order visible but only not more than 2 orders visible in order page. One more issue is after accepting, it's still showing pending in order page. Price also displayed zero. Please help @philipvu30

**Comment by FaizalAndro** [comment]
Hi @philipvu30 Please help in order page issue

**Comment by philipvu30** [comment]
Hi,

My apologies for the delayed response as we do not work on weekends.
I'm checking this issue. Please be patient.

Thank you.

**Comment by philipvu30** [comment]
Hi,

In lib/common/tools.dart, add .toString() to the price term
![image](https://user-images.githubusercontent.com/54442328/88025572-ac854180-cb5e-11ea-9045-e46be263498c.png)

>Order visible but only not more than 2 orders visible in order page

It's not happening to me.
![image](https://user-images.githubusercontent.com/54442328/88025502-8f507300-cb5e-11ea-943a-a7b8a7029ad2.png)

**Comment by philipvu30** [comment]
>One more issue is after accepting, it's still showing pending in order page

Pending here is for payment status, not booking status.

**Comment by FaizalAndro** [comment]
Hi @philipvu30 , Please check the video https://drive.google.com/file/d/1PVUK04dfofK5NuTK8b7TdP1n3e6Oot9X/view?usp=sharing

**Comment by philipvu30** [comment]
Hi,

I see what you meant. Replace this file [order.dart.zip](https://github.com/inspireui/support/files/4957661/order.dart.zip) in lib/models/order.dart

**Comment by FaizalAndro** [comment]
> Hi,
> 
> I see what you meant. Replace this file [order.dart.zip](https://github.com/inspireui/support/files/4957661/order.dart.zip) in lib/models/order.dart

I checked this, Order Waiting for approval doesn't showing in order history. Even after approve through backend.

One more thing, reset screen shows blank
![Screenshot_1595413974](https://user-images.githubusercontent.com/37078576/88166580-196b0b00-cc35-11ea-9d1e-0318caad048e.png)

**Comment by philipvu30** [comment]
Hi,
>Order Waiting for approval doesn't showing in order history. Even after approve through backend.

This order screen is for showing the orders in WooCommerce Orders only. It's not for showing Bookings from Listeo theme. Even if you change the status in Bookings section, it won't show because that is not a correct process. The booking has to be approved via Owner Dashboard.

![image](https://user-images.githubusercontent.com/54442328/88251432-01e35f00-ccd5-11ea-8d99-7f451a641bfa.png)

>One more thing, reset screen shows blank

Please check that if you have inserted the forgot password link in config.dart.

**Comment by FaizalAndro** [comment]
Otp screen shows some error. Please check
![IMG-20200724-WA0002](https://user-images.githubusercontent.com/37078576/88329225-3ee83980-cd47-11ea-96e7-f9911a5c5106.jpg)

**Comment by philipvu30** [comment]
Hi,

Replace this file in lib/screens/login_sms/verify.dart.
[verify.dart.zip](https://github.com/inspireui/support/files/4969989/verify.dart.zip)

**Comment by philipvu30** [comment]
Closed as no response in 2 days.
