### ISSUE TITLE
Cannot complete the checkout process

### ISSUE THREAD

**Issue by gitstc** [inspireui/support#3745]
+ Detail Issues: During checkout, I filled my address info and clicked the "Save Address" button at the bottom and got a confirmation that my address was saved. Then I selected my address from the "Select Address" button and clicked on "Continue to shipping". I got an error "type 'String' is not a subtype of type 'int' of 'index'" and I could not proceed with the checkout process. I am currently using the default store "https://mstore.io" and I created an account from the app.
+ Product & version: FluxStore v1.7
+ Flutter (or React Native) version: Flutter 1.17.3 • channel stable
+ Testing Device/Simulator: Pixel 2 API 28
+ Screenshot issues (drag the file to attach here): 

![Checkout-SaveAddress](https://user-images.githubusercontent.com/7489909/84638049-28a4bd80-aeff-11ea-9991-4d4c11efd405.PNG)
![Checkout-SelectAddress](https://user-images.githubusercontent.com/7489909/84638052-2a6e8100-aeff-11ea-9aa2-5a0333d349d0.PNG)
![Checkout-ShippingAddress](https://user-images.githubusercontent.com/7489909/84638055-2b071780-aeff-11ea-80d2-f952204f8f0c.PNG)

**Comment by minhcasi** [comment]
@gitstc - could you confirm this issue happened on latest release `1.7.5` - thank you!

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
