### ISSUE TITLE
Payment  integration options in Magento . 

### ISSUE THREAD

**Issue by subhquad** [inspireui/support#3746]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: what are payment options in Magento . As the  webview  is not supported for Magento  . What are payment integration options . Will it work with stripe ? 
+ Product & version: Fluxstore Pro 1.7.5
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: iPhone 11
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

80f2ca3f-3e8f-43cd-97ba-9dd311d5fb75

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@subhquad - current is it supports Paypal / Tap payment - thank you!

**Comment by subhquad** [comment]
How to integrate stripe ?
