### ISSUE TITLE
incompatibility of the script with the PHP 7.3 

### ISSUE THREAD

**Issue by mohamadrw** [inspireui/support#3749]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: i had fatal error when i try to reach to this payment page 
https://osfood.nl/mstore-checkout/
Fatal error: Uncaught Error: Cannot use object of type stdClass as array in /var/www/wptbox/wp-content/themes/RoidNet/templates/mstore-api-template.php:30 Stack trace: #0 /var/www/wptbox/wp-includes/template-loader.php(106): include() #1 /var/www/wptbox/wp-blog-header.php(19): require_once('/var/www/wptbox...') #2 /var/www/wptbox/index.php(17): require('/var/www/wptbox...') #3 {main} thrown in /var/www/wptbox/wp-content/themes/RoidNet/templates/mstore-api-template.php on line 30

i talked to my hosting provider they said "
I have just received an update from my colleagues that the error message relates to possible incompatibility of the script with the PHP 7.3 : https://stackoverflow.com/questions/931407/what-is-stdclass-in-php

Unfortunately, it will not be possible to change the PHP version within the Managed WordPress server environment.
"

+ Product & version: 1.7.4
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhtruong315** [comment]
Hi @mohamadrw I can't reproduce your issue on our site. Can u send me admin account to login to your website via email: truong@inspireui.com
with sibject: https://github.com/inspireui/support/issues/3749
Thanks

**Comment by mohamadrw** [comment]
i send to you

**Comment by mohamadrw** [comment]
i'm also changed my hosting for this issue

**Comment by minhtruong315** [comment]
@mohamadrw I fixed this issue on MStore Api plugin. You can check again and let me know the result.
Thanks

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
