### ISSUE TITLE
[BuzzApp] Change Category display style.

### ISSUE THREAD

**Issue by Ibra-ak95** [inspireui/support#375]
- Product: BuzzApp - Viral Magazine WordPress app by React Native (CeNews) 
 - Your Purchased Code: [17382b74-a752-4029-bc36-ebc5bdebac3c]

**Describe the bug**
I need some help In changing the category display from(image+text) to coloured labels only, to be specific I am using the buzzy theme but I want the category display of the cenews theme, when I switched to ceNews theme the categories are not displayed in home page.

**Screenshots**
My app is showing this:
![1](https://user-images.githubusercontent.com/46293510/53945517-74e13b00-40ca-11e9-8c12-a4ee7b32f53e.png)

but I need this:
![2](https://user-images.githubusercontent.com/46293510/53945519-76126800-40ca-11e9-9d59-eb26a9ad3fc6.png)

**Comment by minhtruong315** [comment]
Hi @Ibra-ak95 You can copy Categories in buzzy to cenews. Open file App/Theme/buzzy/Home/index.js. Then copy 
```
if (config.layout == Constants.Layout.horizontal) {
      return <Categories categories={categories} style={styles.categories} onPressItem={this.onPressCategory} numRows={2} contentWidth={Constants.Window.width}/>
    }
``` and replace it in App/Theme/cenews/Home/index.js

**Comment by Ibra-ak95** [comment]
Ok, I tried this but it is not showing any category now. Categories in Cenews is always not displayed.

**Comment by minhcasi** [comment]
@Ibra-ak95 - please try your best, as this could something wrong with your custom.

pls also note that this is customize coding stuff that is not from our support scope - thank you!

**Comment by Ibra-ak95** [comment]
Ok thanks, I changed that by code overwrite, I implemented my own.
