### ISSUE TITLE
magento2 issues

### ISSUE THREAD

**Issue by amjadalfawal** [inspireui/support#3750]
**issue 1:**
![2020-06-15_17h28_11](https://user-images.githubusercontent.com/37481122/84669589-ae3f6200-af2d-11ea-9639-5fa2e1ff1c1f.png)
![image](https://user-images.githubusercontent.com/37481122/84703225-93d2ac00-af60-11ea-8f44-46e41bdc5a9f.png)

**issue 3 :** 
![image](https://user-images.githubusercontent.com/37481122/84669786-f2326700-af2d-11ea-9896-853f0643f6a5.png)
**issue 4:**
![102587223_1625743737599649_1690108943079793939_n](https://user-images.githubusercontent.com/37481122/84670617-05920200-af2f-11ea-9c77-a0090db64199.png)
![104433802_1177370859272898_6525068156658358004_n (1)](https://user-images.githubusercontent.com/37481122/84670631-0aef4c80-af2f-11ea-8926-ce7f974e1f2c.png)
![103180001_705168200046514_1579871171368801818_n](https://user-images.githubusercontent.com/37481122/84670652-0fb40080-af2f-11ea-9716-ca9d5afc8fba.png)
![102340275_701673890621465_6963665674347746163_n](https://user-images.githubusercontent.com/37481122/84670663-12aef100-af2f-11ea-87e5-9b5492cb662a.png)

**issue 5:** 
![image](https://user-images.githubusercontent.com/37481122/84689227-54e52c00-af49-11ea-8ea3-0c1d7f39acbf.png)

**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
issue1: price not showing from outside
issue2: the item takes more than 5 seconds to load  
issue3: color not showing always 
issue4: when login or signup from the splash screen the whole app go wrong 
issue5: disable shipment give this error 
ps: I want to remove the shipping and address I tried to make them virtual products not work ethier

+ Product & version:
 1.7.5
+ Flutter (or React Native) version: 
flutter
+ Testing Device/Simulator: 
device

**Comment by minhcasi** [comment]
@amjadalfawal - please help to move your all conversation into one ticket support #3705 - thank you!
