### ISSUE TITLE
[Fluxstore Multi Vendor] - Requesting search Store by location feature

### ISSUE THREAD

**Issue by raziq10000** [inspireui/support#3751]
My app supports multi vendors with the help of WCFM.
Currently, all Stores are getting listed inside the categories tab with pagination. But my requirement is to have a section where the user can search for a store with the following fields.
- Store name
- Store location (Country & State)
- Category

It would be great if you guys can list the APIs you are going to use to implement the above feature here so that I can give it a try.

I searched for the API at https://wordpress.org/plugins/wcfm-marketplace-rest-api but no luck.

Currently, the app is using https://www.mywebsite.com/wp-json/wc/v2/flutter/wcfm-stores?per_page=10&page=1 which does not support any params for search.

**Product & Version: Fluxstore Multi-Vendor -** Flutter E-commerce Full App v1.7.5

**Comment by Amitjeypore** [comment]
Yes please add this feature called location, where sellers or products available in that location will be shown in the homepage. That would be awesome.

**Comment by minhcasi** [comment]
@raziq10000 @Amitjeypore - we are working on this improvement and will keep an update - very best!

**Comment by Amitjeypore** [comment]
Thank you :-)

**Comment by raziq10000** [comment]
@minhcasi  could you please let us know the tentative timeline?

**Comment by samer-ibrahim** [comment]
> @minhcasi could you please let us know the tentative timeline?

I am not get you, could you explain please ?

**Comment by minhcasi** [comment]
@raziq10000 - we are trying our best to delivery it as soon as we can, could be around on this month - thank you!

**Comment by kvt0012** [comment]
Dear sir, about category, I think it's quite hard because some store has many categories, so it is complicated to detect and not useful. 
About store name and store location, we will install it and display on the map, is it your idea ? Or you want to when you search it, it will be displayed on card form, sir ? Thank you

**Comment by Amitjeypore** [comment]
![Screenshot_20200630-090828](https://user-images.githubusercontent.com/65069372/86080822-66821400-bab1-11ea-99f1-5bebcc67a489.jpg)

Something like on the top, where if you select the location the products available on that location shall show.

**Comment by kvt0012** [comment]
> ![Screenshot_20200630-090828](https://user-images.githubusercontent.com/65069372/86080822-66821400-bab1-11ea-99f1-5bebcc67a489.jpg)
> 
> Something like on the top, where if you select the location the products available on that location shall show.

Amazon is large system and they use the recommendation system based on Machine Learning/AI algorithm, it is quite complicated with small app like FluxStore, sir.

**Comment by kvt0012** [comment]
But we will try this with other solution, accuracy is not good as Amazon but it adapts some basic requirements.

**Comment by Amitjeypore** [comment]
Ok sir thank you :-)

**Comment by minhcasi** [comment]
Pls, help to use the latest release that also supports the Map View and Vendor search :)
