### ISSUE TITLE
admob banner and intertitial do not work

### ISSUE THREAD

**Issue by 3Alouch1** [inspireui/support#3752]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: admob banner and intertiatial do not work
+ Product & version: fluxnews last version in codecanyon
+ Flutter (or React Native) version: last version in codecanyon
+ Testing Device/Simulator: Hwawei p30, Hwawei p320, Iphone11 pro, iphone 11 pro max, infinix s2, samsung galaxy s9, samsung galaxy s10
+ Screenshot issues (drag the file to attach here): 
https://mega.nz/file/bSoXwaKY#ENBL0bMRf6-PVqbQQScqBDInXcDtmHpyg6gL1eYjWYw

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by 3Alouch1** [comment]
as you can see it showing only reward video, no intertiatial and banner ads also the reward video must showing every 1 click not two or 4 or 6 ???

**Comment by gunero** [comment]
I also use FluxNews and the banner at the bottom is not showing.

**Comment by dttrung26** [comment]
Hi @3Alouch1  and @gunero , 
- As I just checked, FluxNews still supports fine with Advertisement with Banner, Interstitial and Reward type. Please double check your integration with Google Admob to make sure that everything is correctly done. 
![image](https://user-images.githubusercontent.com/32586676/84729331-a16a4f00-afbd-11ea-8af2-5d16b3811ff0.png)
![image](https://user-images.githubusercontent.com/32586676/84729364-b7780f80-afbd-11ea-9e21-6d06a174ae1c.png)
- When it comes to clicks required to display advertisement, it still appears fine within 1 click as I checked. Please be patient to wait a bit. You simply can't just click everything in a blink of an eye and switch to another widget and expect advertisement display within that insane short time.
Best!

**Comment by gunero** [comment]
Why you close this issue? Because it works for you? 

No banner appears for me. Only the interstitial opens after a few seconds. I checked it many times and implemented the banner ad ID correctly, no banner.

**Comment by dttrung26** [comment]
Hi @gunero , 
First of all, I need you to be calm. Then, please leave me the console log of your issue when banner image does not display after being clicked on. We can help you through it, but you need to co-operate instead of being angry. 
If you do not know how to find the console log, please contact me via skype: dttrung.ityu. We could do a teamviewer after that.
Have a nice day, again!
