### ISSUE TITLE
Fluxstore woo

### ISSUE THREAD

**Issue by samer-ibrahim** [inspireui/support#3753]
Dears InspireUI Team,

Thank you for this greate app,

(Fluxstore woocommerce) Flutter version 1.7.5
(Testing device : Andriod emulator pixel 3a XL API 29)

I have some issues need your support please :

1- Shipping charge not claculated when I add product to cart , I am not using any shipping plugin, I have one zone only, Shipping class setting enabled on backend : 
" you will notes that I assigned one zipcode only to this zone, as we sell to one zone with fixed shipping charge Can I make this default zipcode in my app? so when customer open checkout page it shows country and zipcode written by default?

![1](https://user-images.githubusercontent.com/66953736/84689735-11d78880-af4a-11ea-8320-efd6fbc5f7e4.jpg)

![4](https://user-images.githubusercontent.com/66953736/84692373-6c72e380-af4e-11ea-9235-8bf5d9efeb04.jpg)
![5](https://user-images.githubusercontent.com/66953736/84692427-83b1d100-af4e-11ea-863c-1c7510e62948.jpg)

![6](https://user-images.githubusercontent.com/66953736/84692801-18b4ca00-af4f-11ea-9d73-a4931ce001b4.jpg)

2-I enabled "onepagecheckout" webview but when I click checkout button it comes wiht this error message "your cart is currenly empty".

![2](https://user-images.githubusercontent.com/66953736/84689844-3d5a7300-af4a-11ea-9ef4-2b5cd9c028e4.jpg)

3- I just need to know how can I remove the discount percentage from product page as shown below, I am using the main theme of fluxstore I want to make it (Sale) Instead of (sale 33%) 
I tried to use inspector tools but I couldn't find the code.

![3](https://user-images.githubusercontent.com/66953736/84689860-46e3db00-af4a-11ea-8c47-c8ce7be1ca0f.jpg)

4- Coupon code is working well but I noted that is ignore the restrictions setting like execlude some category or sales item, min amount restrictions also not active.

I appreciate your work & Support

Kinds regards,

Samer

**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhtruong315** [comment]
Hi @samer-ibrahim can u upload your source code to github and invite me: minhtruong315@gmail.com
I will help you check and fix on it
Thanks

**Comment by samer-ibrahim** [comment]
> Hi @samer-ibrahim can u upload your source code to github and invite me: [minhtruong315@gmail.com](mailto:minhtruong315@gmail.com)
> I will help you check and fix on it
> Thanks

Hi, I just invited you.
Thank you !

**Comment by minhtruong315** [comment]
Hi @samer-ibrahim I dont see the source code on your repo
https://github.com/samer-ibrahim/My-App

**Comment by samer-ibrahim** [comment]
> Hi @samer-ibrahim I dont see the source code on your repo
> https://github.com/samer-ibrahim/My-App
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/cbfbdece72100f46536fc8c567f4fbdeb80df1c7/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f696d616765732f6d6f64756c65732f6f70656e5f67726170682f6769746875622d6c6f676f2e706e67"><img alt="" height="14" src="https://camo.githubusercontent.com/040b5519c6d1891329f5f6d3e511003657131cf2/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[Build software better, together](https://github.com)**GitHub is where people build software. More than 50 million people use GitHub to discover, fork, and contribute to over 100 million projects.

I uploaded common and config files, could you please check again.

**Comment by minhtruong315** [comment]
@samer-ibrahim 
1. Shipping cost only calculate when you choose shipping method. if you want to test this, you need to disable OnePageCheckout
2. can u upload all your source code to the repo so that I can help you to fix OnePageCheckout.
3. You can update code here
<img width="1373" alt="Screen Shot 2020-06-17 at 5 07 38 PM" src="https://user-images.githubusercontent.com/10402500/84885370-25efc700-b0bd-11ea-9347-8d7d8a980f81.png">
4. The restrictions setting for coupon doesn't work now. We will research and upgrade it in the future.
Thanks for your report.

**Comment by samer-ibrahim** [comment]
@minhtruong315 
Would you mind access to my project by teamviewer ? as i couldn't upload full source due to high size. if yes please let me know how can I give you teamviewer id & password.
Thank you !

**Comment by minhtruong315** [comment]
share me teamviewer

**Comment by samer-ibrahim** [comment]
> share me teamviewer

Send your email please

**Comment by minhtruong315** [comment]
truong@inspireui.com

**Comment by samer-ibrahim** [comment]
thanks for your support !
