### ISSUE TITLE
Woocommerse Subcategory is not showing up

### ISSUE THREAD

**Issue by mmasifashraf** [inspireui/support#3755]
Woocommerse Subcategory is not showing .
is there any settings to enable it?

**Comment by minhcasi** [comment]
Could you take the screenshot from your Woocommerce setting? Make sure the category is having child product items + and the category with parent/child multi-level. 

Also from the config JSON file, update the `TabBar` section menu: 
```
"layout":"category",
      "categoryLayout":"card",
```

**Comment by mmasifashraf** [comment]
I cant see the section which i marked in the screen shot in my layout. 

![image](https://user-images.githubusercontent.com/44862509/84760294-7b9a7580-afd0-11ea-8184-5664e557545f.jpeg)

**Comment by minhcasi** [comment]
@mmasifashraf - it will display when you click to the Parent categories, for the category don't have child, it will not display - thanks

**Comment by mmasifashraf** [comment]
@minhcasi My Category has a child and it contains item as well. But still not showing the child.
