### ISSUE TITLE
PushNotifcation when application is closed

### ISSUE THREAD

**Issue by stickypages** [inspireui/support#3756]
**_Step 1 (require): describe detail issues & screenshots_**
**PushNotification** when the application is closed.
**_Example:_** Vendor receives a notification of a chat from a customer. They should receive a notification pop-up, You have a new message from "XYZ Customer". They click on the notification and it takes them to the chat screen.

I do see that steps have been created to start this process, I assume with lib/services/woo_commerce.dart (1088). 

How do we enable the communication notification between a customer and a vendor, so they don't miss any messages?

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**
I have previously submitted proof of purchase.

**Comment by minhcasi** [comment]
@minhtruong315 - pls investigate this feature - thank you!

**Comment by stickypages** [comment]
@minhcasi @minhtruong315 Just a couple things to note from my diggings.

lib/app.dart (~133)
onLaunch() onMessage() onResume()

They need to have a couple of actions. 
```
onMessage() {
   /// Needs to show an alert, or some kind of message
}
onLaunch() / onResume() {
   /// On opening the app it needs to go to '/list-chats'
}
```

For some reason, my limited knowledge of Flutter, whatever code I implement it doesn't want to show a dialog or navigation... IE
```
Navigator.push(context,
        MaterialPageRoute(builder: (context) => NotificationScreen()));
```
OR
`Navigator.of(context).pushNamed('/list-chat');
`

It seems to be simple for the most part, but I cannot get these functions to react to anything I place in them other than, print(), which shows all the notification data just fine. Any help is appreciated here.

**Comment by stickypages** [comment]
@minhtruong315 If you get a minute to direct me on this, that would be amazing. I have spent my entire day looking at options and trying to force it to open a view/screen/dialog box, and I've had no success. Thank you!

**Comment by minhcasi** [comment]
@trunghieuvn - pls help to suggest this issue - thank you!

**Comment by stickypages** [comment]
Thank you @minhcasi hope to hear soon.

**Comment by stickypages** [comment]
I've been trying things like this but doesn't work apparently. 

```
@override
  onLaunch(Map<String, dynamic> message) {
    _saveMessage(message);
    print("onLaunch2: $message");
    Navigator.pushNamed(context, RouteList.listChat);
  }

  @override
  onMessage(Map<String, dynamic> message) {
    _saveMessage(message);
    print("onMessage2: $message");
    /// SHOW DIALOG OR ALERT
  }

  @override
  onResume(Map<String, dynamic> message) {
    _saveMessage(message);
    print("onResume2: $message");
    Navigator.pushNamed(context, RouteList.listChat);
  }
```

**Comment by trunghieuvn** [comment]
Hi @stickypages  for case when closed app. currently feature push notification don't receive.
i research and implement it.

**Comment by stickypages** [comment]
@trunghieuvn I am receiving notifications right now ... It's working with the vendor chat. 

In the app.dart it even has the func for onResume.... Etc... Are you able to help me with that still please. It is a vital feature for a customer or a vendor to know when they receive a message.

**Comment by stickypages** [comment]
If that doesn't work for you are you able to show me at least how to get a dialog, or route to the chat list on app load?

**Comment by stickypages** [comment]
I can screenshare if you like

**Comment by trunghieuvn** [comment]
please share me screen record demo issue, i will easier to understand, and will help solution to you

**Comment by stickypages** [comment]
@minhtruong315 Ok I can do first thing in the morning. PST time. 

In short. App.dart has a method called, onResume or onLaunch. When you receive a notification, and you click on the notification it needs to take you too the screen /list-chat

Same goes for onMessage, that it shows a notification // or an alert dialog and when you click on it, it goes to the chat. 

As you can see in my previous code, I tried putting a navigation, but it doesn't go there. I'm guess it has to do with the loading cycle of the app and the routing.

**Comment by stickypages** [comment]
@trunghieuvn sorry I tagged wrong person in previous message

**Comment by stickypages** [comment]
@trunghieuvn @minhcasi  Hey, here is a video overviewing my situation, please let me know asap! 

https://www.youtube.com/watch?v=f4qF9-nmVeA

**Comment by stickypages** [comment]
@trunghieuvn @minhcasi Anyone have any ideas?

**Comment by minhcasi** [comment]
@trunghieuvn - pls help to check the issue

**Comment by trunghieuvn** [comment]
@stickypages  sr for delay,  i development feature when user click to notification application will route to screen.

**Comment by stickypages** [comment]
@trunghieuvn Thanks for getting back to me. Post it to GitLab, and let me know so I can take a peek at what your cookin' 👯

**Comment by trunghieuvn** [comment]
hi @stickypages i develop done feature routing for when user click to notification. (i say feature name -> deeplink)
1. First,  you add variable Map save data for deeplinnk
<img width="484" alt="Screen Shot 2020-06-24 at 11 58 38 AM" src="https://user-images.githubusercontent.com/19247680/85502684-0bb06e80-b612-11ea-8bc3-9ac8aaa6d70b.png">

2. Continue need add data for AppModel in file app.dart i function `void _saveMessage(Map<String, dynamic> message) {` 

<img width="730" alt="Screen Shot 2020-06-24 at 12 00 08 PM" src="https://user-images.githubusercontent.com/19247680/85502780-41555780-b612-11ea-9a2f-1731b7dc7f66.png">

3. Continue handle life circle for tabbar.dart (https://medium.com/flutter-community/flutter-lifecycle-for-android-and-ios-developers-8f532307e0c7)
- with WidgetsBindingObserver
- initState: WidgetsBinding.instance.addObserver(this);
- dispose: WidgetsBinding.instance.removeObserver(this);
we will have functionn callback when user interup app (change  Background  and Foreground). Handle open redirect screen in this file.

```
  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if (state == AppLifecycleState.paused) {
      // went to Background
    }
    if (state == AppLifecycleState.resumed) {
      // came back to Foreground
      final appModel = Provider.of<AppModel>(context, listen: false);
      if (appModel.deeplink?.isNotEmpty ?? false) {
        if (appModel.deeplink['screen'] == 'NotificationScreen') {
          Navigator.push(
            context,
            MaterialPageRoute(builder: (context) => NotificationScreen()),
          );
        }
      }
    }

    super.didChangeAppLifecycleState(state);
  }
```

![demo-deeplinnk](https://user-images.githubusercontent.com/19247680/85503275-744c1b00-b613-11ea-9c6e-d1e3df311da4.gif)


[MStore_FCM(Server Key + token device).postman_collection.json.zip](https://github.com/inspireui/support/files/4823310/MStore_FCM.Server.Key.%2B.token.device.postman_collection.json.zip)

**Comment by stickypages** [comment]
Hey Thanks for all that! I am still trying to get a 'snackbar' to show when a new message is received if (foreground). And then click on it to go to the list-chat.... Is this possible, @trunghieuvn ?

**Comment by stickypages** [comment]
Actually, think I have a solution. I will post with my suggested changes to this process shortly.

**Comment by trunghieuvn** [comment]
Hi @stickypages  you can use implement with https://github.com/inspireui/support/issues/3756#issuecomment-648589511  
we can handle any case.

**Comment by stickypages** [comment]
@trunghieuvn @minhcasi 

This seems to have solved the difficulty with the 'notifications'. That being said I had to make a number of adjustments to other things to help assist with this all. You might want to include in the GitLab!

First I had to adjust the Firebase Functions
Here is the updated code for my function.
```
const functions = require('firebase-functions');

//The Firebase Admin SDK to access the Firebase Realtime Database.
const admin = require('firebase-admin');
admin.initializeApp();

// // Create and Deploy Your First Cloud Functions
// // https://firebase.google.com/docs/functions/write-firebase-functions
exports.pushNotification = functions.https.onCall((data, context) => {
    const code     = 'ok'
    let msg        = ''
    const details  = ''
    const receiver = data.receiverEmail
    const sender   = data.senderName
    const message  = data.message

    if(receiver) {
        admin
            .firestore()
            .collection('users')
            .doc(receiver)
            .get()
            .then( snapshot => {
                const user = snapshot.data()
                console.log('USER', user)

                /// Create payload to send to 'receiver'
                const payload = {
                    notification: {
                        tag: 'chat',
                        channel: 'chat',
                        label: 'chat',
                        title: `Message from "${sender}"`,
                        body: message,
                        badge: '1',
                        sound: 'default',
                        click_action: 'FLUTTER_NOTIFICATION_CLICK',
                        screen: 'NotificationScreen'
                    },
                    data: {
                        screen: '/list-chat',
                        title: `Message from "${sender}"`, /// This can be removed
                        body: message, /// This can be removed
                    }
                }

                /// Send to device
                admin
                    .messaging()
                    .sendToDevice(user.deviceToken, payload)
                    .then(response => {
                        //console.log('Successfully sent message:', response)
                        msg = 'Successfully sent message'
                    })
                    .catch(error => {
                        throw new functions.https.HttpsError(
                            'aborted',
                            error);
                    })

            }).catch( err => {
                throw new functions.https.HttpsError(
                    'not-found',
                    'Collection Not found');
            })

    } else {
        throw new functions.https.HttpsError(
            'invalid-argument',
            'No receiver idtentified');
    }

    return {
        code: code,
        message: msg,
        details: details
    }
});
```

**For the "onMessage()". for FCM, this is what I did.**
I used the OverlaySupport that you already have included in the application, 
**MAIN.DART**
```
///runApp(App());
  runApp(
        OverlaySupport(
            child: App()
        )
  );
```

**APP.DART**
```
@override
  void onMessage(Map<String, dynamic> message) {
    _saveMessage(message);
    printLog('[app.dart] onMessage PushNotification: $message');
    _fcm.showDialog(context, message);
  }
```

**FIREBASE_CLOUD_MESSAGING_WAPPER.DART**
```
import 'package:overlay_support/overlay_support.dart';


  void showDialog(BuildContext context, messageJson) {
    print('showDialog');

    try {
      final data = messageJson['data'];
      final notification =
      data != null && data.keys.isNotEmpty ? data : messageJson['notification'];
      var body = notification['body'];
      var title = notification['title'];

      showOverlayNotification((context) {
        return MessageNotification(
          title:title,
          message:body,
          onReplay: () {
            Navigator.of(context).pushNamed('/list-chat');
          },
        );
      }, duration: Duration(milliseconds: 4000));

    } catch (e) {
      print(e.toString());
    }
  }


class MessageNotification extends StatelessWidget {
  final VoidCallback onReplay;
  final String title;
  final String message;

  const MessageNotification({
    Key key,
    this.onReplay,
    @required this.title,
    @required this.message,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Card(
      margin: const EdgeInsets.symmetric(horizontal: 4),
      child: SafeArea(
        child: ListTile(
          leading: SizedBox.fromSize(
              child: Icon(Icons.chat_bubble, size: 20)),
          title: Text(title),
          subtitle: Text(message),
          trailing: IconButton(
              icon: Icon(Icons.reply),
              onPressed: () {
                if (onReplay != null) onReplay();
              }),
        ),
      ),
    );
  }
}
```

**TABBAR.DART**
```
@override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    printLog(state);

    final appModel = Provider.of<AppModel>(context, listen: false);

    if (state == AppLifecycleState.paused) {
      // went to Background
    }
    if (state == AppLifecycleState.resumed) {
      // came back to Foreground
      if (appModel.deeplink?.isNotEmpty ?? false) {
        if (appModel.deeplink['screen'] == 'NotificationScreen') {
          Navigator.of(context).pushNamed('/list-chat');
        } else {
          // Enables you to have dynamic push locations if need be
          Navigator.of(context).pushNamed(appModel.deeplink['screen']);
        }
      }
    }

    super.didChangeAppLifecycleState(state);
  }
```

I believe that was the majority of the adjustments. I would recommend adding these features to the core. As they are quite vital to the communication between Vendor/Customer.
+ We should look into enabling 'images' in the chat for customer support.
+ I have made tweaks in the GitLab for other items, not sure if that helps or not for you.

Thanks for helping out with this situation. Doing my best to gain more knowledge with Flutter/Dart.

**Comment by trunghieuvn** [comment]
Hi @stickypages we have 1 issue for reset variable deeplink. please update   
\`\`\`  
 if (appModel.deeplink?.isNotEmpty ?? false) {  
        if (appModel.deeplink\['screen'\] == 'NotificationScreen') {  
          Navigator.of(context).pushNamed('/list-chat');  
        } else {  
          // Enables you to have dynamic push locations if need be  
          Navigator.of(context).pushNamed(appModel.deeplink\['screen'\]);  
        }

appModel.deeplink = null;  
      }  
\`\`\`

**Comment by stickypages** [comment]
Good catch, so the app doesn't always load the chat screen on load.

Thanks!

**Comment by trunghieuvn** [comment]
Hi @stickypages the problem has been solved :D   
any issue you can open new ticket, i will help me solve 

Nice to help you \<3 . Please help me close the ticket and if you feel satisfied please give me 5 stars [https://codecanyon.net/downloads](https://codecanyon.net/downloads) 

Thank you very much.
