### ISSUE TITLE
starting fluxnews with ar RTL as default language

### ISSUE THREAD

**Issue by jodi3mad** [inspireui/support#3757]
hello and many greetings for all,
im facing a problem when staring fluxnews app with ar RTL as a default language by setting :
const kAdvanceConfig = {
"DefaultLanguage": "ar",

return withRED SCREEN:
NoSuchMethodError: the method '[]' was called on null

all i need to start fluuxnews with arabic RTL language by default.
please i need your help.

thanks in advance.

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by careerun** [comment]
can you help run my app ?

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one with full information - thank you for your time!
