### ISSUE TITLE
AppGuideline 4.0 - Design 

### ISSUE THREAD

**Issue by trananhchien** [inspireui/support#3758]
We noticed that several screens of your app were crowded or laid out in a way that made it difficult to use your app.

Next Steps
To resolve this issue, please revise your app to ensure that the content and controls on the screen are easy to read and interact with.

Resources
For more information, please review the following resources on the iOS Developer Center page:
- UI Do's and Don'ts
- iOS Human Interface Guidelines
- UIKit

Please see attached screenshot for details.
![attachment-9678432196905851637Screenshot-0615-093906](https://user-images.githubusercontent.com/64599942/84728626-ce1d6700-afbb-11ea-9e05-bcd211eb35c3.png)

In my thinking, they want to design the UI as your screen shot like below. Can you support to make this UI for me?

![864240a30f81f2dfab90](https://user-images.githubusercontent.com/64599942/84728687-fe650580-afbb-11ea-9f2e-f87dc9722604.jpg).

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
@trananhchien it seems they have test on iPad device and find out the mismatch design concept on iPad. The issue could be Alignment is not centralized. 

Are you able to customize this design on iPad? 

Please note that the preview from Apple by a human, sometimes it is quire strictly and not easy to pass.

**Comment by trananhchien** [comment]
Hi Minh,

Im not specialists of design and code. Can you support me to make UI like this photo.
![864240a30f81f2dfab90](https://user-images.githubusercontent.com/64599942/84855645-c7135900-b08e-11ea-9b30-09c46034b0bd.jpg)

Priority login with apple will be better

**Comment by minhcasi** [comment]
@trananhchien - you could check our previous version on Gitlab and apply that UI to your source - thank you!

If you have not had the access - pls submit to http://gitlab.inspireui.com - thanks

**Comment by trananhchien** [comment]
I am not a code expert. So can your team help with the adjustment of this issue for me?
Or this is a common problem for everyone if apple checks and detects the login screen on ipad is not center. Therefore an update is required for everyone

**Comment by minhcasi** [comment]
Hi, pls try to override `lib\screens\users\login.dart` by this file to fix the issue
[login.dart.txt](https://github.com/inspireui/support/files/4807628/login.dart.txt)

It will be similar to this screenshot - 
<img width="538" alt="Screen Shot 2020-06-20 at 16 13 16" src="https://user-images.githubusercontent.com/1459805/85198205-f46f3980-b310-11ea-86fa-2ccb724e486e.png">
