### ISSUE TITLE
Error run fluxstore app android studio

### ISSUE THREAD

**Issue by Impexi** [inspireui/support#3759]
When i run fluxstore app on android studio i get this message>>

 FAILURE: Build failed with an exception.

* What went wrong:

Could not determine the dependencies of task ':app_settings:compileDebugAidl'.

Failed to find Platform SDK with path: platforms;android-R

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by Impexi** [comment]
Ok I submitted form now

**Comment by minhcasi** [comment]
@Impexi - could you try this solution https://github.com/flutter/flutter/issues/59355#issuecomment-643482076

**Comment by minhcasi** [comment]
pls move all conversation relate to android-r to this ticket #3708

**Comment by Impexi** [comment]
I used this code but the problem is still!!
this is screen of it
![Github1](https://user-images.githubusercontent.com/66989859/84892666-452b2c00-b09e-11ea-8cb0-217197713c29.jpg)

**Comment by Impexi** [comment]
The issue error was changed with this

**Comment by Impexi** [comment]
![Error-9](https://user-images.githubusercontent.com/66989859/85957635-40645300-b98f-11ea-83ea-821ab7a1baa6.jpg)

**Comment by Impexi** [comment]
Please i want solve the problem its very urgent... the time to reply is too much

**Comment by Impexi** [comment]
![Error-12](https://user-images.githubusercontent.com/66989859/86193672-da252f00-bb4c-11ea-99f4-d01aee8c645b.jpg)

**Comment by Impexi** [comment]
This is last update of problem
