### ISSUE TITLE
[Listpro] Share problem 

### ISSUE THREAD

**Issue by chad-the-first** [inspireui/support#376]
- Product: [Listpro]
 - Your Purchased Code: 65e47917-78fa-4b8e-97ec-80bf8345f72a

**Describe the bug**
When I share a listing it just copy the text content of the listing and not share the link to the actual listing. How I can configure this feature right?

**Comment by thangvo9x** [comment]
Hi. We have a plan for in the next update. First, you can fix it by replace this file 
Components/Detail/Footer/index.js
Thanks 
p/s: remember rename .txt -> *.js 
[index.txt](https://github.com/inspireui/support/files/2944108/index.txt)

**Comment by chad-the-first** [comment]
please reopen the ticket because it didn't work, I tried and it gives me this error:
![Sketch6](https://user-images.githubusercontent.com/17035853/54645079-a501e400-4aa3-11e9-8647-7e5f12fe566f.png)

**Comment by thangvo9x** [comment]
Try with this file.
[index.txt](https://github.com/inspireui/support/files/2995961/index.txt)

**Comment by chad-the-first** [comment]
didn't work, here's what happens: 
![Sketch1](https://user-images.githubusercontent.com/17035853/54864810-f12f7b80-4d64-11e9-8d8f-6923f256b1bb.png)

and that's how the footer looks:
![Sketch](https://user-images.githubusercontent.com/17035853/54864813-fb517a00-4d64-11e9-9cda-b3384095df04.png)
