### ISSUE TITLE
magento support

### ISSUE THREAD

**Issue by christky99** [inspireui/support#3760]
I bought 2 of your products and until now none of them can run normally.
the current application that I am trying to use is Fluxstore Pro for Magento.

1. how to connect blog for magento
2. how to use PostScreen for magento

Please help...

**Comment by minhcasi** [comment]
@christky99 - could you help to share the screenshot issue - thank you!

**Comment by christky99** [comment]
Blog issue
![Screen Shot 2020-06-16 at 17 42 27](https://user-images.githubusercontent.com/62212126/84759342-2f176000-aff9-11ea-9161-79b61c8ce17f.png)
![Screen Shot 2020-06-16 at 17 44 01](https://user-images.githubusercontent.com/62212126/84759425-48201100-aff9-11ea-8b99-810632629312.png)
![Screen Shot 2020-06-16 at 17 14 01](https://user-images.githubusercontent.com/62212126/84759459-55d59680-aff9-11ea-9b9d-119a30d145fd.png)

**Comment by christky99** [comment]
PostScreen issue
![Screen Shot 2020-06-16 at 17 28 27](https://user-images.githubusercontent.com/62212126/84759575-7c93cd00-aff9-11ea-8808-9798d17c09a7.png)
![Screen Shot 2020-06-16 at 17 16 35](https://user-images.githubusercontent.com/62212126/84759616-8cabac80-aff9-11ea-8867-174d3263de71.png)

**Comment by minhcasi** [comment]
@christky99 - the Blog from Magento should be linked to the Wordpress blog as it does not support for the Magento Blog type at current release - let us know your checking - thank you!

**Comment by christky99** [comment]
PostScreen issue?

**Comment by minhcasi** [comment]
I'm mean the PostScreen is only compatible once you config the `blog` point to Wordpress site, if it is config to Magento site, it will not work - thank you!
