### ISSUE TITLE
 can't make a fluxstore keystore

### ISSUE THREAD

**Issue by teampotlot** [inspireui/support#3761]
![image](https://user-images.githubusercontent.com/66760408/84754258-b3b2b000-aff2-11ea-858a-7ee0c4bd4b31.png)

can i ask for help, how do i make a keystore in windows. I always fail to make it

- verified

**Comment by minhcasi** [comment]
there is the path missing on your android sdk that could not get the keytool - pls check some solution on https://stackoverflow.com/questions/6211919/errorkeytool-is-not-recognized-as-an-internal-or-external-command-operable-p

**Comment by teampotlot** [comment]
I have done the steps correctly. but this is happening. can I help me?

https://docs.inspireui.com/fluxstore/delivery-android/

![image](https://user-images.githubusercontent.com/66760408/84801366-a832a980-b031-11ea-959e-881ef385e31d.png)

**Comment by teampotlot** [comment]
D:\pootlotcrator\license\FluxStore-woo 1.7.5\source>flutter build apk --split-per-abi
Running Gradle task 'assembleRelease'...
Parameter format not correct -
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\connectivity-0.4.8+6\android\src\main\java\io\flutter\plugins\connectivity\ConnectivityBroadcastReceiver.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_admob-0.9.3+2\android\src\main\java\io\flutter\plugins\firebaseadmob\AdRequestBuilderFactory.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\uni_links-0.4.0\android\src\main\java\name\avioli\unilinks\UniLinksPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-5.4.10\android\src\main\java\io\flutter\plugins\urllauncher\WebViewActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\webview_flutter-0.3.22+1\android\src\main\java\io\flutter\plugins\webviewflutter\FlutterWebView.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\video_player-0.10.11+1\android\src\main\java\io\flutter\plugins\videoplayer\VideoPlayerPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Removed unused resources: Binary resource data reduced from 584KB to 574KB: Removed 1%
Removed unused resources: Binary resource data reduced from 584KB to 574KB: Removed 1%
Removed unused resources: Binary resource data reduced from 584KB to 574KB: Removed 1%

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:packageRelease'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > com.android.ide.common.signing.KeytoolException: Failed to read key mstore_key from store "C:\key\pasarsayur.jks": No key with alias 'mstore_key' found in keystore C:\key\pasarsayur.jks

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5m 12s
Running Gradle task 'assembleRelease'...
Running Gradle task 'assembleRelease'... Done                     313.2s (!)
Gradle task assembleRelease failed with exit code 1

D:\pootlotcrator\license\FluxStore-woo 1.7.5\source>

**Comment by teampotlot** [comment]
I have successfully made a keystore. and place the file in the C: \ key \ key.jks data
. but it's still an error 

![image](https://user-images.githubusercontent.com/66760408/84835029-40965180-b065-11ea-925a-7110d0326574.png)

**Comment by teampotlot** [comment]
help me please

**Comment by teampotlot** [comment]
help me please

**Comment by teampotlot** [comment]
help me please

**Comment by teampotlot** [comment]
help me please

**Comment by minhcasi** [comment]
@teampotlot - please remove `>` from the `storeFile` path - it seems you have paste the redundance character

**Comment by teampotlot** [comment]
> @teampotlot - please remove `>` from the `storeFile` path - it seems you have paste the redundance character

I have copied the key shop that I made (see picture), but the results remain the same. can you give more explanation. so that I can follow the tutorial you gave

![image](https://user-images.githubusercontent.com/66760408/84892077-87b92c80-b0cf-11ea-9368-b7c3a424a016.png)

**Comment by teampotlot** [comment]
![image](https://user-images.githubusercontent.com/66760408/84897976-15e5e080-b0d9-11ea-9bbe-c5a42a12d5c4.png)

**Comment by teampotlot** [comment]
help me please

**Comment by teampotlot** [comment]
help me please

**Comment by minhcasi** [comment]
@teampotlot - pls try to change this file 

<img width="737" alt="Screen Shot 2020-06-18 at 09 58 21" src="https://user-images.githubusercontent.com/1459805/84973012-40bc4d00-b14a-11ea-966e-45eb27473bdd.png">

to `storeFile=C:/key/key.jsk`

**Comment by teampotlot** [comment]
still error sir

**Comment by minhcasi** [comment]
@teampotlot - could you share the latest detail error? is it the same error log? Thank you!

**Comment by minhcasi** [comment]
Pls also check this guide could be helpful  https://flutter.dev/docs/deployment/android
