### ISSUE TITLE
 api-ecommerce issue in MStore Multi Vendor React native app

### ISSUE THREAD

**Issue by alhasson** [inspireui/support#3762]
i went through all the documentation process when i run the app it shows:
warn Package api-ecommerce has been ignored because it contains invalid configuration. Reason: Cannot find module 'api-ecommerce/package.json'
and on the app it shows:
unable to resolve module 'api-ecommerce' from 'app.js' api-ecommerce could not be found within the project.

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by alhasson** [comment]
@minhcasi couldnt upload the project files it exceed the size limit on your website. 
Please note this is testing so i didnt make any customization change only follow the instructions on you documentation, 
if you need to verify my purchase please send me a form with details only, without uploading files.
Also as i saw here, i think this problem is common and happen with others.  
thanks.

**Comment by minhcasi** [comment]
@alhasson - please help to verify the license via this link https://docs.google.com/forms/d/e/1FAIpQLScWOjkAJIWJ9rgb9alopfOqLsJrGKbFM5cCYj1JBfLKLsBblQ/viewform

**Comment by minhcasi** [comment]
it's verified through the comment.

@luyx2412 - pls help to suggest the issue

**Comment by alhasson** [comment]
@luyx2412 @minhcasi  im still waiting!

**Comment by luyx2412** [comment]
HI @alhasson Please send your project via inspireui.team@gmail.com. Let me investigate and reply you soon.

Thanks

**Comment by alhasson** [comment]
@luyx2412 
error!
mx.google.com rejected your message to the following email addresses:

inspireui.team@gmail.com (inspireui.team@gmail.com)
Your message wasn't delivered because the recipient's email provider rejected it.


this was my message:
hello regarding to this issue,
https://github.com/inspireui/support/issues/3762
couldnt upload whole the project because of the size.
But i didnt add any code only i add the api for woocommerce. 
i think there is a problem with installing the api-ecommerce module, if you can send me a copy from it with package.json so i can add it manually. 

thanks.

**Comment by luyx2412** [comment]
HI @alhasson Please upload your project to drive google, after that share the link via email inspireui.team@gmail.com and add the title with `3762` which will easier to find.

Thanks

**Comment by alhasson** [comment]
@luyx2412 sent. wish this issue be solved asap :)

**Comment by luyx2412** [comment]
Hi @alhasson Can you send me the specific screenshot issue? I just tested your project and everything worked normal. And please make sure you install `yarn install` before run the project.
![image](https://user-images.githubusercontent.com/8909619/85220669-a709cf80-b3d7-11ea-9590-9c8d3c0b2754.png)

Thanks

**Comment by alhasson** [comment]
@luyx2412 i use npm, 
i run npm install then npm start!! should i use yarn instead of npm?

**Comment by alhasson** [comment]
![Screenshot_1592744033](https://user-images.githubusercontent.com/18103270/85225103-732eaa00-b3d7-11ea-931e-4b5fccf4e92c.png)
@luyx2412 here is a screenshot

**Comment by alhasson** [comment]
this issue solved once i use yarn to install the packages. thanks.
