### ISSUE TITLE
Multi-Vendor Shipping Cost Issue

### ISSUE THREAD

**Issue by grnas00** [inspireui/support#3764]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues:  I face an problem in shipping page the cost of shipping method  for store retrieve with cost Zero
+ Product & version:  Fluxstore 1.7.5
+ Flutter (or React Native) version: Flutter (Channel stable, v1.17.3, on Microsoft Windows [Version 10.0.18363.900])
+ Testing Device/Simulator:  Simulator Android SDK 29.0.0
+ Screenshot issues (drag the file to attach here): 
![Screenshot_1592308762](https://user-images.githubusercontent.com/24503019/84772471-a6da9000-afe3-11ea-9fa9-0bbe16719ceb.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhtruong315** [comment]
Hi @grnas00 can u send me admin account? I see it's showing shipping cost
![Simulator Screen Shot - iPhone X - 2020-06-17 at 22 35 57](https://user-images.githubusercontent.com/10402500/84918597-01aadf00-b0eb-11ea-97e5-9e5fda6a2660.png)

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
