### ISSUE TITLE
Error when I try to run FluxStore Woocommerce on Android Studio

### ISSUE THREAD

**Issue by raedinkhaled** [inspireui/support#3765]
Hello,

I just downloaded the FluxStore Woocommerce version and when I try to run I get this Error Message:

`FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app_settings:compileDebugAidl'.
> Failed to find Platform SDK with path: platforms;android-R
`

I tried to use this command : **flutter run -v**
and the output was :

`[  +55 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +236 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +4 ms] e6b34c2b5c96bb95325269a29a84e83ed8909b5f
[   +1 ms] executing: [C:\flutter/] git tag --contains HEAD
[ +761 ms] Exit code 0 from: git tag --contains HEAD
[   +1 ms] 1.17.0
           1.17.0-3.4.pre
[  +15 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +379 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/stable
[        ] executing: [C:\flutter/] git ls-remote --get-url origin
[ +344 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +372 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[ +438 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[ +190 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +8 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +51 ms] executing: C:\Users\ASUS\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[ +314 ms] List of devices attached
                    emulator-5554          device product:sdk_gphone_x86 model:Android_SDK_built_for_x86 device:generic_x86 transport_id:4
[  +13 ms] C:\Users\ASUS\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell getprop
[ +266 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[  +17 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +267 ms] Found plugin app_settings at C:\flutter\.pub-cache\hosted\pub.dartlang.org\app_settings-4.0.0\
[  +11 ms] Found plugin apple_sign_in at C:\flutter\.pub-cache\hosted\pub.dartlang.org\apple_sign_in-0.1.0\
[  +60 ms] Found plugin connectivity at C:\flutter\.pub-cache\hosted\pub.dartlang.org\connectivity-0.4.8+6\
[   +8 ms] Found plugin connectivity_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\connectivity_macos-0.1.0+2\
[  +50 ms] Found plugin facebook_audience_network at C:\flutter\.pub-cache\hosted\pub.dartlang.org\facebook_audience_network-0.6.1\
[  +15 ms] Found plugin firebase_admob at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_admob-0.9.3+2\
[   +6 ms] Found plugin firebase_analytics at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_analytics-5.0.14\
[   +5 ms] Found plugin firebase_auth at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.15.3\
[  +10 ms] Found plugin firebase_auth_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-0.1.2\
[   +7 ms] Found plugin firebase_core at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.4.4\
[   +8 ms] Found plugin firebase_core_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-0.1.1+2\
[   +6 ms] Found plugin firebase_database at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_database-3.1.6\
[   +7 ms] Found plugin firebase_messaging at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_messaging-6.0.16\
[  +46 ms] Found plugin flutter_facebook_login at C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_facebook_login-3.0.0\
[   +4 ms] Found plugin flutter_keyboard_visibility at C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_keyboard_visibility-0.7.0\
[  +17 ms] Found plugin flutter_plugin_android_lifecycle at C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.7\
[  +26 ms] Found plugin flutter_statusbarcolor at C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_statusbarcolor-0.2.3\
[  +33 ms] Found plugin flutter_webview_plugin at C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_webview_plugin-0.3.11\
[  +32 ms] Found plugin google_maps_flutter at C:\flutter\.pub-cache\hosted\pub.dartlang.org\google_maps_flutter-0.5.28+1\
[  +12 ms] Found plugin google_sign_in at C:\flutter\.pub-cache\hosted\pub.dartlang.org\google_sign_in-4.5.1\
[  +15 ms] Found plugin google_sign_in_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\google_sign_in_web-0.9.1\
[  +68 ms] Found plugin location at C:\flutter\.pub-cache\hosted\pub.dartlang.org\location-3.0.2\
[  +12 ms] Found plugin location_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\location_web-1.0.0\
[  +15 ms] Found plugin notification_permissions at C:\flutter\.pub-cache\hosted\pub.dartlang.org\notification_permissions-0.4.4\
[   +5 ms] Found plugin onesignal_flutter at C:\flutter\.pub-cache\hosted\pub.dartlang.org\onesignal_flutter-2.4.1\
[  +12 ms] Found plugin path_provider at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.7\
[  +16 ms] Found plugin path_provider_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+1\
[  +37 ms] Found plugin rate_my_app at C:\flutter\.pub-cache\hosted\pub.dartlang.org\rate_my_app-0.6.1+3\
[  +11 ms] Found plugin share at C:\flutter\.pub-cache\hosted\pub.dartlang.org\share-0.6.4+3\
[   +5 ms] Found plugin shared_preferences at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.7+3\
[   +4 ms] Found plugin shared_preferences_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-0.0.1+7\
[   +7 ms] Found plugin shared_preferences_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-0.1.2+4\
[  +13 ms] Found plugin sqflite at C:\flutter\.pub-cache\hosted\pub.dartlang.org\sqflite-1.3.0\
[  +44 ms] Found plugin uni_links at C:\flutter\.pub-cache\hosted\pub.dartlang.org\uni_links-0.4.0\
[   +6 ms] Found plugin url_launcher at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-5.4.10\
[   +4 ms] Found plugin url_launcher_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-0.0.1+5\
[   +8 ms] Found plugin url_launcher_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-0.1.1+1\
[  +13 ms] Found plugin video_player at C:\flutter\.pub-cache\hosted\pub.dartlang.org\video_player-0.10.11+1\
[   +7 ms] Found plugin video_player_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\video_player_web-0.1.3\
[   +4 ms] Found plugin wakelock at C:\flutter\.pub-cache\hosted\pub.dartlang.org\wakelock-0.1.4+1\
[   +7 ms] Found plugin webview_flutter at C:\flutter\.pub-cache\hosted\pub.dartlang.org\webview_flutter-0.3.22+1\
[ +107 ms] Found plugin app_settings at C:\flutter\.pub-cache\hosted\pub.dartlang.org\app_settings-4.0.0\
[   +3 ms] Found plugin apple_sign_in at C:\flutter\.pub-cache\hosted\pub.dartlang.org\apple_sign_in-0.1.0\
[  +37 ms] Found plugin connectivity at C:\flutter\.pub-cache\hosted\pub.dartlang.org\connectivity-0.4.8+6\
[  +10 ms] Found plugin connectivity_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\connectivity_macos-0.1.0+2\
[  +19 ms] Found plugin facebook_audience_network at C:\flutter\.pub-cache\hosted\pub.dartlang.org\facebook_audience_network-0.6.1\
[  +12 ms] Found plugin firebase_admob at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_admob-0.9.3+2\
[  +30 ms] Found plugin firebase_analytics at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_analytics-5.0.14\
[   +3 ms] Found plugin firebase_auth at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.15.3\
[   +3 ms] Found plugin firebase_auth_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-0.1.2\
[   +2 ms] Found plugin firebase_core at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.4.4\
[   +3 ms] Found plugin firebase_core_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-0.1.1+2\
[   +2 ms] Found plugin firebase_database at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_database-3.1.6\
[   +2 ms] Found plugin firebase_messaging at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_messaging-6.0.16\
[  +19 ms] Found plugin flutter_facebook_login at C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_facebook_login-3.0.0\
[   +2 ms] Found plugin flutter_keyboard_visibility at C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_keyboard_visibility-0.7.0\
[   +5 ms] Found plugin flutter_plugin_android_lifecycle at C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.7\
[   +6 ms] Found plugin flutter_statusbarcolor at C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_statusbarcolor-0.2.3\
[   +8 ms] Found plugin flutter_webview_plugin at C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_webview_plugin-0.3.11\
[   +8 ms] Found plugin google_maps_flutter at C:\flutter\.pub-cache\hosted\pub.dartlang.org\google_maps_flutter-0.5.28+1\
[   +6 ms] Found plugin google_sign_in at C:\flutter\.pub-cache\hosted\pub.dartlang.org\google_sign_in-4.5.1\
[   +3 ms] Found plugin google_sign_in_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\google_sign_in_web-0.9.1\
[  +15 ms] Found plugin location at C:\flutter\.pub-cache\hosted\pub.dartlang.org\location-3.0.2\
[   +9 ms] Found plugin location_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\location_web-1.0.0\
[   +6 ms] Found plugin notification_permissions at C:\flutter\.pub-cache\hosted\pub.dartlang.org\notification_permissions-0.4.4\
[   +2 ms] Found plugin onesignal_flutter at C:\flutter\.pub-cache\hosted\pub.dartlang.org\onesignal_flutter-2.4.1\
[  +15 ms] Found plugin path_provider at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.7\
[   +2 ms] Found plugin path_provider_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+1\
[  +13 ms] Found plugin rate_my_app at C:\flutter\.pub-cache\hosted\pub.dartlang.org\rate_my_app-0.6.1+3\
[   +5 ms] Found plugin share at C:\flutter\.pub-cache\hosted\pub.dartlang.org\share-0.6.4+3\
[   +2 ms] Found plugin shared_preferences at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.7+3\
[   +2 ms] Found plugin shared_preferences_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-0.0.1+7\
[   +4 ms] Found plugin shared_preferences_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-0.1.2+4\
[   +9 ms] Found plugin sqflite at C:\flutter\.pub-cache\hosted\pub.dartlang.org\sqflite-1.3.0\
[  +15 ms] Found plugin uni_links at C:\flutter\.pub-cache\hosted\pub.dartlang.org\uni_links-0.4.0\
[   +3 ms] Found plugin url_launcher at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-5.4.10\
[   +2 ms] Found plugin url_launcher_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-0.0.1+5\
[   +3 ms] Found plugin url_launcher_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-0.1.1+1\
[   +6 ms] Found plugin video_player at C:\flutter\.pub-cache\hosted\pub.dartlang.org\video_player-0.10.11+1\
[   +6 ms] Found plugin video_player_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\video_player_web-0.1.3\
[   +4 ms] Found plugin wakelock at C:\flutter\.pub-cache\hosted\pub.dartlang.org\wakelock-0.1.4+1\
[  +10 ms] Found plugin webview_flutter at C:\flutter\.pub-cache\hosted\pub.dartlang.org\webview_flutter-0.3.22+1\
[ +177 ms] Generating C:\Users\ASUS\Desktop\Amina\codecanyon-y1R8M09o-fluxstore-woocommerce-flutter-ecommerce-full-app\FluxStore-woo
1.7.5\source\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +51 ms] ro.hardware = ranchu
[  +41 ms] Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
[  +39 ms] Launching lib\main.dart on Android SDK built for x86 in debug mode...
[  +23 ms] C:\flutter\bin\cache\dart-sdk\bin\dart.exe C:\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names -Ddart.developer.causal_async_stacks=true --output-dill
C:\Users\ASUS\AppData\Local\Temp\flutter_tool.2b383df2-afd9-11ea-9645-704d7b4a6c8b\app.dill --packages
C:\Users\ASUS\Desktop\Amina\codecanyon-y1R8M09o-fluxstore-woocommerce-flutter-ecommerce-full-app\FluxStore-woo 1.7.5\source\.packages -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation
--filesystem-scheme org-dartlang-root --initialize-from-dill build\cache.dill
[  +39 ms] executing: C:\Users\ASUS\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell -x logcat -v time -t 1
[  +96 ms] Exit code 0 from: C:\Users\ASUS\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell -x logcat -v time -t 1
[        ] --------- beginning of main
           06-16 14:56:30.711 E/GnssHAL_GnssInterface( 1749): gnssSvStatusCb: b: input svInfo.flags is 8
[  +40 ms] <- compile package:fstore/main.dart
[  +42 ms] executing: C:\Users\ASUS\AppData\Local\Android\sdk\platform-tools\adb.exe version
[ +281 ms] Android Debug Bridge version 1.0.41
                    Version 29.0.5-5949299
                    Installed as C:\Users\ASUS\AppData\Local\Android\sdk\platform-tools\adb.exe
[   +7 ms] executing: C:\Users\ASUS\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[ +151 ms] Building APK
[  +32 ms] Running Gradle task 'assembleDebug'...
[  +18 ms] gradle.properties already sets `android.enableR8`
[  +30 ms] Using gradle from C:\Users\ASUS\Desktop\Amina\codecanyon-y1R8M09o-fluxstore-woocommerce-flutter-ecommerce-full-app\FluxStore-woo 1.7.5\source\android\gradlew.bat.
[   +4 ms] C:\Users\ASUS\Desktop\Amina\codecanyon-y1R8M09o-fluxstore-woocommerce-flutter-ecommerce-full-app\FluxStore-woo 1.7.5\source\android\gradlew.bat mode: 33279 rwxrwxrwx.
[  +23 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +266 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[   +2 ms] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
           OpenJDK 64-Bit Server VM (build 25.242-b01, mixed mode)
[   +4 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +267 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[   +1 ms] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
           OpenJDK 64-Bit Server VM (build 25.242-b01, mixed mode)
[   +5 ms] executing: [C:\Users\ASUS\Desktop\Amina\codecanyon-y1R8M09o-fluxstore-woocommerce-flutter-ecommerce-full-app\FluxStore-woo 1.7.5\source\android/]
C:\Users\ASUS\Desktop\Amina\codecanyon-y1R8M09o-fluxstore-woocommerce-flutter-ecommerce-full-app\FluxStore-woo 1.7.5\source\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-x86
-Ptarget=C:\Users\ASUS\Desktop\Amina\codecanyon-y1R8M09o-fluxstore-woocommerce-flutter-ecommerce-full-app\FluxStore-woo 1.7.5\source\lib\main.dart -Ptrack-widget-creation=true
-Pfilesystem-scheme=org-dartlang-root assembleDebug
[+120365 ms] FAILURE: Build failed with an exception.
[  +13 ms] * What went wrong:
[   +1 ms] Could not determine the dependencies of task ':app_settings:compileDebugAidl'.
[   +1 ms] > Failed to find Platform SDK with path: platforms;android-R
[   +9 ms] * Try:
[   +1 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[   +1 ms] * Get more help at https://help.gradle.org
[   +2 ms] BUILD FAILED in 1m 59s
[ +591 ms] Running Gradle task 'assembleDebug'... (completed in 121.6s, longer than expected)
[   +7 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +2 ms] "flutter run" took 125,394ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:569:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:722:18)
#3      _rootRunUnary (dart:async/zone.dart:1192:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#12     _rootRunUnary (dart:async/zone.dart:1192:38)
#13     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#14     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#16     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#17     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#20     AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
#21     _rootRunUnary (dart:async/zone.dart:1192:38)
#22     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#23     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#25     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#26     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#27     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#28     _rootRun (dart:async/zone.dart:1184:13)
#29     _CustomZone.run (dart:async/zone.dart:1077:19)
#30     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#32     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
`

**Comment by hossein-khanmirzaei** [comment]
Same Issue!
Any Answer?!

**Comment by muhalab2010** [comment]
same issue

**Comment by minhcasi** [comment]
@raedinkhaled 
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
pls move all conversation relate to `android-r` to this ticket #3708
