### ISSUE TITLE
I can't do any searches

### ISSUE THREAD

**Issue by brygom** [inspireui/support#3766]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
when i try to do a search in the application, i get an error that i add screenshot I also get an error in the debug console.
+ Product & version:
FluxStore-listing 1.4.1
+ Flutter (or React Native) version: Flutter 1.17.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b041144f83 (8 days ago) • 2020-06-04 09:26:11 -0700
Engine • revision ee76268252
Tools • Dart 2.8.4
+ Testing Device/Simulator: iPhone 11(13.5) simulator
+ Screenshot issues (drag the file to attach here): 
<img width="431" alt="image" src="https://user-images.githubusercontent.com/313953/84816783-9e795980-afd1-11ea-95ea-e6d7f1dcd96c.png">

<img width="1124" alt="image" src="https://user-images.githubusercontent.com/313953/84817011-b3ee8380-afd1-11ea-8e3b-6ad95e520508.png">

<img width="1500" alt="image" src="https://user-images.githubusercontent.com/313953/84817198-c668bd00-afd1-11ea-9927-5643d35cdad1.png">

```flutter: getProductNearest
flutter: https://mysite/wp-json/search/v1/listing?_embed=true&search=c&page=1&per_page=50&_embed=true
flutter: https://mysite/wp-json/search/v1/listing?_embed=true&search=ca&page=1&per_page=50&_embed=true
flutter: https://mysite/wp-json/search/v1/listing?_embed=true&search=car&page=1&per_page=50&_embed=true
```
<img width="737" alt="image" src="https://user-images.githubusercontent.com/313953/84817477-4131d800-afd2-11ea-95b0-6530d110fb65.png">

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by philipvu30** [comment]
Hi,

A fixed source code has been sent to your email. Please check.

![image](https://user-images.githubusercontent.com/54442328/84850234-6c273500-b081-11ea-8330-edc752a06478.png)

**Comment by brygom** [comment]
Thank you @philipvu30

**Comment by philipvu30** [comment]
Hi,

Please do the following steps to solve all common issues that happen lately.

1. Update ListApp Mobile Manager to 1.6.4 version
2. Delete these files
![image](https://user-images.githubusercontent.com/54442328/84852217-78fa5780-b086-11ea-8e59-e416616fb883.png)
3. Run flutter clean
4. Run flutter pub get

I hope this solution will solve your issue.

Thank you.

**Comment by brygom** [comment]
@philipvu30 thank you.
I have performed the steps you describe without success.
I have this issues now:
```
Compiler message:
lib/widgets/home/banner/banner_map.dart:46:52: Error: Getter not found: 'DENIED'.
        if (_permissionGranted == PermissionStatus.DENIED) {
                                                   ^^^^^^
lib/widgets/home/banner/banner_map.dart:48:54: Error: Getter not found: 'GRANTED'.
          if (_permissionGranted != PermissionStatus.GRANTED) {
                                                     ^^^^^^^
lib/widgets/home/banner/banner_map.dart:45:30: Error: A value of type 'bool' can't be assigned to a variable of type 'PermissionStatus'.
 - 'PermissionStatus' is from 'package:notification_permissions/notification_permissions.dart' ('../../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/notification_permissions-0.4.4/lib/notification_permissions.dart').
        _permissionGranted = await _locationService.hasPermission();
                             ^
lib/widgets/home/banner/banner_map.dart:47:32: Error: A value of type 'bool' can't be assigned to a variable of type 'PermissionStatus'.
 - 'PermissionStatus' is from 'package:notification_permissions/notification_permissions.dart' ('../../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/notification_permissions-0.4.4/lib/notification_permissions.dart').
          _permissionGranted = await _locationService.requestPermission();
                               ^
Xcode build done.                                           41.0s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **```

**Comment by philipvu30** [comment]
Hi,

Did you delete the pubspec.lock also?

**Comment by brygom** [comment]
@philipvu30  Yes, I follow every step included delete pubspec.lock also.

**Comment by philipvu30** [comment]
Please note that after you delete those files, they won't be deleted right away. 
There will be a notification in the console window like this.
![image](https://user-images.githubusercontent.com/54442328/84862697-d352e280-b09d-11ea-9e36-d2c0a10d7353.png)

You have to select the Do refactor, then they will be deleted. Then press the **Pub get** button in pubspec.yaml file.

**Comment by brygom** [comment]
@philipvu30  thank you! now works well!

**Comment by philipvu30** [comment]
I'm glad I was able to help

If you are happy with our services/support, would you mind rating us on your [download page](https://codecanyon.net/downloads)?
We truly appreciate your help.

**Comment by philipvu30** [comment]
Closed as no more activity.
