### ISSUE TITLE
SDK Platform error

### ISSUE THREAD

**Issue by mercadocerouno** [inspireui/support#3767]
When i try to run the project this error appear 

<img width="1440" alt="Screen Shot 2020-06-16 at 1 03 42 PM" src="https://user-images.githubusercontent.com/66270970/84823254-e8167400-afd2-11ea-9c27-fd9184cf9215.png">

**Comment by muhalab2010** [comment]
same problem

**Comment by Moh-Zag** [comment]
the same issue 
![Screenshot_1](https://user-images.githubusercontent.com/50769781/84845187-4df31200-b04c-11ea-9f51-03bea04cae06.jpg)

**Comment by minhcasi** [comment]
@mercadocerouno 
Please try to update `android/build.gradle` and add the following code at bottom of the file 

```
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(':app')
    afterEvaluate {project ->
        if (project.hasProperty("android") && project.property("android").compileSdkVersion.equals("android-R")) {
            android {
                compileSdkVersion 30
            }
        }
    }
}
```

**Comment by minhcasi** [comment]
pls move all conversation relate to `android-r` to this ticket #3708
