### ISSUE TITLE
"See All" page empty with No Product

### ISSUE THREAD

**Issue by xsamir** [inspireui/support#3768]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
The products show fine in front screen & category pages, but it's **empty on See All page** .
But when I clicked on the filter and choose a category, it shows fine!!

I faced the same problem with 1.7.2 and 1.7.3!

I tried to make some modification on woocommerce_api file, but it's same
Also, I reviewed everything on the tutorial, but nothing wrong with my steps

+ Product & version: 1.7.5

+ Flutter (or React Native) version: 
+ Testing Device/Simulator: Nexus 6 API 28 x86 Android 9.0 & live version on the store for ios & android
+ Screenshot issues (drag the file to attach here): 
![image](https://user-images.githubusercontent.com/7432001/84826513-1aa48900-b034-11ea-9f06-1644a3d36814.png)
![image](https://user-images.githubusercontent.com/7432001/84826528-2001d380-b034-11ea-8d51-25f876fe5361.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**
Done

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhtruong315** [comment]
Hi @xsamir replace fetchProductsByCategory function in services/woocommerce.dart like this and try again
```
@override
  Future<List<Product>> fetchProductsByCategory(
      {categoryId,
      tagId,
      page,
      minPrice,
      maxPrice,
      orderBy,
      lang,
      order,
      attribute,
      attributeTerm,
      featured,
      onSale}) async {
    try {
      List<Product> list = [];

      /// this cause a bug on Profile List
      /// we just allow cache if the totalItem = perPageItem otherwise, should reload
      if ((page == 0 || page == 1) &&
          categoryCache["$categoryId"] != null &&
          categoryCache["$categoryId"].isNotEmpty &&
          featured == null &&
          onSale == null &&
          attributeTerm == null) {
        if (categoryCache["$categoryId"].length == ApiPageSize) {
          return categoryCache["$categoryId"];
        }
      }

      var endPoint =
          "products?status=publish&lang=$lang&per_page=$ApiPageSize&page=$page";
      if (categoryId != null && categoryId != "0") {
        endPoint += "&category=$categoryId";
      }
      if (tagId != null) {
        endPoint += "&tag=$tagId";
      }
      if (minPrice != null) {
        endPoint += "&min_price=${(minPrice as double).toInt().toString()}";
      }
      if (maxPrice != null && maxPrice > 0) {
        endPoint += "&max_price=${(maxPrice as double).toInt().toString()}";
      }
      if (orderBy != null) {
        endPoint += "&orderby=$orderBy";
      }
      if (order != null) {
        endPoint += "&order=$order";
      }
      if (featured != null) {
        endPoint += "&featured=$featured";
      }
      if (onSale != null) {
        endPoint += "&on_sale=$onSale";
      }
      if (attribute != null && attributeTerm != null) {
        endPoint += "&attribute=$attribute&attribute_term=$attributeTerm";
      }

      print('fetchProductsByCategory: ' + endPoint);
      var response = await wcApi.getAsync(endPoint);

      if (response is Map && isNotBlank(response["message"])) {
        throw Exception(response["message"]);
      } else {
        for (var item in response) {
          if (!kAdvanceConfig['hideOutOfStock'] || item["in_stock"]) {
            Product product = Product.fromJson(item);
            if (item['store'] != null) {
              product = Services().widget.updateProductObject(product, item);
            }
            list.add(product);
          }
        }
        return list;
      }
    } catch (e) {
      //This error exception is about your Rest API is not config correctly so that not return the correct JSON format, please double check the document from this link https://docs.inspireui.com/fluxstore/woocommerce-setup/
      rethrow;
    }
  }
```

**Comment by xsamir** [comment]
Thank you for your response, but the same (No Products) with these records:

```
I/flutter (26171): 14
I/flutter (26171): [2020-06-17 17:16:10.626320Z][myappname][wocommerce_api][20:16:10.626107] getAsync END [endPoint:products?status=publish&lang=en&per_page=20&page=1&category=null] url:products?status=publish&lang=en&per_page=20&page=1&category=null
I/flutter (26171): 14
I/flutter (26171): 14
```

**Comment by xsamir** [comment]
Also, there's another problem
On version 1.7.3 on theme no. 11, I can scroll down to load more products
But on 1.7.5 When I scroll down, it doesn't load any products, just a static number of products!

**Comment by alexrali** [comment]
> Also, there's another problem
> On version 1.7.3 on theme no. 11, I can scroll down to load more products
> But on 1.7.5 When I scroll down, it doesn't load any products, just a static number of products!

Yeah, same problem here

**Comment by minhtruong315** [comment]
> Thank you for your response, but the same (No Products) with these records:
> 
> ```
> I/flutter (26171): 14
> I/flutter (26171): [2020-06-17 17:16:10.626320Z][myappname][wocommerce_api][20:16:10.626107] getAsync END [endPoint:products?status=publish&lang=en&per_page=20&page=1&category=null] url:products?status=publish&lang=en&per_page=20&page=1&category=null
> I/flutter (26171): 14
> I/flutter (26171): 14
> ```

did you clicked See All but dont have products?
<img width="633" alt="Screen Shot 2020-06-18 at 9 03 09 AM" src="https://user-images.githubusercontent.com/10402500/84969298-942a9d00-b142-11ea-9139-7c4619102176.png">

**Comment by xsamir** [comment]
Yes, I tried, and also No products, here's a video:
https://drive.google.com/file/d/1xYW9GCsf97oXk8KHjB_3Hk2MU5eWSHS2/view?usp=sharing

**Comment by minhtruong315** [comment]
@xsamir can u send me full source code via email: minhtruong315@gmail.com

**Comment by xsamir** [comment]
Ok, I will do it today night, because it's in another computer not near from me now

**Comment by xsamir** [comment]
> minhtruong315@gmail.com

Sent, email subject (xsamir from github)

regards,

**Comment by minhtruong315** [comment]
Hi @xsamir can u zip your source code? I can't unrar.
Thanks

**Comment by xsamir** [comment]
Ok I will

**Comment by xsamir** [comment]
Sent to your email

**Comment by xsamir** [comment]
@minhcasi u closed a ticket about my Magento project and include it a MultiVendor project
Both of them diffrint product and diffrent projects!

**Comment by minhcasi** [comment]
Oh sorry, i though it is same product 😅

**Comment by xsamir** [comment]
Kindly reminder

**Comment by minhcasi** [comment]
@minhtruong315

**Comment by minhtruong315** [comment]
Hi @xsamir I ran your source code. but Home screen is not same with your video
<img width="1078" alt="Screen Shot 2020-06-23 at 3 54 22 PM" src="https://user-images.githubusercontent.com/10402500/85383198-e6682580-b569-11ea-8f19-2b2e61998ab5.png">

**Comment by xsamir** [comment]
Yes, I tried to move to another layout , but still the same problem
So I sent the latest codes I have.

**Comment by minhtruong315** [comment]
Hi @xsamir I'm running this source
<img width="1680" alt="Screen Shot 2020-06-24 at 10 12 12 AM" src="https://user-images.githubusercontent.com/10402500/85494653-4959cb00-b603-11ea-817a-209e49d45f50.png">
is it latest?

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
