### ISSUE TITLE
FireBase

### ISSUE THREAD

**Issue by MorisTech** [inspireui/support#3769]
Here was my issue which was closed 
https://github.com/inspireui/support/issues/3701

I'm getting an error while trying to sign in with Firebase

so i connected the app with firebase, downloaded the new google.json file

but i Still get the error

**Comment by minhcasi** [comment]
@MorisTech - could you help to share the screenshot login error?

Please also help to check this solution config from google auth consent - https://github.com/inspireui/support/issues/3151

**Comment by MorisTech** [comment]
I've Connected the Firebase, Google Sign in and Number Sign in works..

But there's a problem

It doesn't take show a successful message that I'm logged in

I used Google to sign in, it didn't show successful 

I receive message on my phone, but it doens't sign in

**Comment by minhcasi** [comment]
@MorisTech would you mind sharing the video screenshot of this issue as we could not reproduce the issue from our testing - thank you for your time!

**Comment by MorisTech** [comment]
Okay will share shortly
Also, I don't have a Mac, how do I edit Mac version and Test it

**Comment by minhcasi** [comment]
Hi, there is no solution to build ios without mac os
