### ISSUE TITLE
Pesonalisation( new payment gateway)

### ISSUE THREAD

**Issue by yassiney120** [inspireui/support#3770]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

hello,
please can you send me your email or contact me on mohdar@fleure.ma for personalization
I want to add new payment gateway (tap.company )
Product Fluxstore mv

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

#3725 

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@yassiney120 - pls move your conversation to the same open ticket #3725
