### ISSUE TITLE
Woocommerce Checkout Page Problem

### ISSUE THREAD

**Issue by atakancelik** [inspireui/support#3771]
Detail Issues: After entering my address information, it throws it from the basket page to the next page in the webview section opened by the payment screen and requests my address information.
It should be: "https://example.com/checkout/order-pay/4834/?key=wc_order_d0LlDQM7tTyrm
The app directs: "https://example.com/checkout/order-pay/?code=ab577c43ff6e1a1a98ddb78d61f6dd05&mobile=true"
+ Product & version: fstore 1.7.5+3001
+ Flutter (or React Native) version: v1.17.3
+ Testing Device/Simulator: Pixel 3a XL API 29

**Comment by Diaa-Boraq** [comment]
I have same issue

**Comment by minhtruong315** [comment]
Hi @atakancelik can  you explain the issue  clearly? can you record screen? 
Thanks

**Comment by atakancelik** [comment]
https://1drv.ms/v/s!ArjzGQLFC4M1g5FIeEfHfD9RGFyzGg?e=GuqLeg

problem: wrong payment link

**Comment by minhtruong315** [comment]
Can you fork from our git repo then invite me: minhtruong315@gmail.com? https://medium.com/@inspireui/how-to-upgrade-fluxstore-projects-by-using-git-cebde7489ea6 I will help you check your issues
 Thanks

**Comment by atakancelik** [comment]
i have added you to my repo. https://github.com/atakancelik/flux

**Comment by atakancelik** [comment]
Is there any improvement? Did you look? I am waiting you

**Comment by minhtruong315** [comment]
Hi @atakancelik I checked the video. it's showing checkout page on your website, you need to do checkout on  that site. 
For your link, it created an order and put to that link. But in our app, it show checkout info in the webview so that you checkout on the webview. Dont checkout in app

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
