### ISSUE TITLE
Need Flutter app for our woocommerce website

### ISSUE THREAD

**Issue by rozariogem3s** [inspireui/support#3772]
This is rozario from gem3s technologies pvt ltd. We have an eCommerce solution called "kadalunavu". Kadalunavu is a woocommerce website to sell seafoods, chicken, meats, etc. We have checked your flutter app in codecanyon - https://codecanyon.net/item/fluxstore-woocommerce-flutter-ecommerce-full-app/24050041

We need to purchase your app. But we have some additional requirements needed to integrate in your flutter app.

I have sent email to your support mail. Kindly check and revert back asap

**Comment by minhcasi** [comment]
@rozariogem3s - thank you for your time - let me have a check via email :)
