### ISSUE TITLE
Custom Payment gateway integration

### ISSUE THREAD

**Issue by Diaa-Boraq** [inspireui/support#3775]
-  Flutter (Channel stable, v1.17.3
- Products: FluxStore Flutter V1.7.4+3001
the  ticket was verified on http://verify.inspireui.com/
------------------------
I've linked the **FluxStore**  **Flutter** app with my **WooComerce** store and  it is 100% ok

Issue (1)
when selecting variantes I get this error
Error in NoSuchMethodError the method '_greaterThanFromInteger' was called on null
![image](https://user-images.githubusercontent.com/50443911/85012664-0794d480-b16c-11ea-96cd-3a3bedfaf4e1.png)

![image](https://user-images.githubusercontent.com/50443911/85013321-0912cc80-b16d-11ea-8fb5-33f60b2b2ec8.png)

issue(2)
I have one problem I could not find a doc about how to integrate with my custom Payment Gateway 
- at least opening the payment page in web-view.
can you  guide me please how& where to start ?

After adding shipping info and selecting CreditCad payment (my custom  payment)
the app open a webview with this URL
https://mystore.com/mstore-checkout?code=ff5b6303bb8254433946b45828e29a33&mobile=true
and shows **404** **error** page
Note:
MStore APi plugin is active and configured
![image](https://user-images.githubusercontent.com/50443911/84997488-55531200-b157-11ea-9db8-2b9d023b6abb.png)
please help! :(

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by Diaa-Boraq** [comment]
@minhcasi  I added more information and verified the ticket
I just need a doc or an example for payment integration( credit card from 3dParty provider

**Comment by minhcasi** [comment]
@Diaa-Boraq - we don't have the document for 3dParty payment integration, please help check from the source code.

Example, this is the code to integrate with Tap payment

<img width="1286" alt="Screen Shot 2020-06-20 at 11 36 56" src="https://user-images.githubusercontent.com/1459805/85191795-59fbff80-b2ea-11ea-8be3-19ba4be99fa5.png">

<img width="1315" alt="Screen Shot 2020-06-20 at 11 37 45" src="https://user-images.githubusercontent.com/1459805/85191824-7861fb00-b2ea-11ea-91c1-0a3805edb012.png">
