### ISSUE TITLE
Signup and Login are not working

### ISSUE THREAD

**Issue by JaserJsk** [inspireui/support#3776]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: **I have followed the tutorial in the Docs but I still cannot signup or register new account from the Flutter application.**
+ Product & version: **1.7.5**
+ Flutter (or React Native) version: **Flutter UI**
+ Testing Device/Simulator: **Real Device - Samsung S8**
+ Screenshot issues: 

![Screenshot_20200617-173156](https://user-images.githubusercontent.com/25635376/84919222-f0011180-b0c1-11ea-92b5-5bc12f6a31c4.jpg)

![Screenshot_20200617-173036](https://user-images.githubusercontent.com/25635376/84919237-f7281f80-b0c1-11ea-883b-fd9173f5d623.jpg)

**Comment by minhcasi** [comment]
@JaserJsk - pls check the solution on this ticket #3151#issuecomment-633489369 - thank you
