### ISSUE TITLE
about package name for firebase 

### ISSUE THREAD

**Issue by muhalab2010** [inspireui/support#3778]
hey
we face problem when change the name of the app
we see the video on youtube for install notification on android
but when we change the package name on the file AndroidManifest.xm to package name 
and upload the google service file 

we get this error

C:\src\best\android\app\src\debug\AndroidManifest.xml Error:
	Overlay manifest:package attribute declared at AndroidManifest.xml:2:5-38 value=(com.inspireui.fluxstore)
	has a different value=(com.effectline.bestylish) declared in main manifest at AndroidManifest.xml:2:5-39
	Suggestion: remove the overlay declaration at AndroidManifest.xml 	and place it in the build.gradle:
		flavorName {
			applicationId = "com.inspireui.fluxstore"
		}

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Overlay manifest:package attribute declared at AndroidManifest.xml:2:5-38 value=(com.inspireui.fluxstore)
  	has a different value=(com.effectline.bestylish) declared in main manifest at AndroidManifest.xml:2:5-39
  	Suggestion: remove the overlay declaration at AndroidManifest.xml 	and place it in the build.gradle:
  		flavorName {
  			applicationId = "com.inspireui.fluxstore"
  		}

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 22s
Exception: Gradle task assembleDebug failed with exit code 1

where also we change full package name on al app

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!
