### ISSUE TITLE
175 fresh copy issue with basic verticalayout

### ISSUE THREAD

**Issue by bigbossmaher** [inspireui/support#3779]
hello , 
i started from a frech copy of Fluxstore woocommerce 
1/ i added this line in config_en.json
  "VerticalLayout":{"key":"xkmve70sbk","layout":"columns","name":"New1 Collection"},
2 / uploaded the config_en.json to mstore api and emptying the cache 
3 / modifying config.dart to connect to my website
4 / enabling isCaching and 

=> when i run i get this error 
1/ the products are not shown in this widget ( vertical layout )
![image](https://user-images.githubusercontent.com/15154710/84929190-65bbac00-b0c7-11ea-87af-f20fdb5a8dd8.png)

2 / the issue is hapen only with Iscahing True
3 / this is the error log
`════════ Exception caught by scheduler library ═════════════════════════════════════════════════════
type 'List<dynamic>' is not a subtype of type 'List<Product>'
════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 9241): #0      WooCommerce.fetchProductsLayout (package:fstore/services/woo_commerce.dart:178:62)
I/flutter ( 9241): #1      Services.fetchProductsLayout (package:fstore/services/index.dart:189:23)
I/flutter ( 9241): #2      _PinterestLayoutState._loadProduct (package:fstore/widgets/home/vertical/vertical_layout.dart:31:38)
I/flutter ( 9241): #3      _PinterestLayoutState.initState (package:fstore/widgets/home/vertical/vertical_layout.dart:47:5)
I/flutter ( 9241): #4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4640:58)
I/flutter ( 9241): #5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
I/flutter ( 9241): #6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
I/flutter ( 9241): #7      MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5947:32)
I/flutter ( 9241): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
I/flutter ( 9241): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
I/flutter ( 9241): #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
I/flutter ( 9241): #11     Element.rebuild (pac`

**Comment by rabahaldoori** [comment]
@minhtruong315 i have same issue

**Comment by minhcasi** [comment]
@minhtruong315 - pls investigating - thank you!

**Comment by bigbossmaher** [comment]
same issue here 
https://github.com/inspireui/support/issues/3672

**Comment by vumanhsn97** [comment]
@bigbossmaher 
VerticalLayout is a Map(not List) https://tppr.me/pMftL. Can you update your config.json again with this setting "VerticalLayout":{"key":"xkmve70sbk","layout":"columns","name":"New1 Collection"}.  When you customize in issue #3672, Cache will not support this
Thanks!

**Comment by bigbossmaher** [comment]
> @bigbossmaher
> VerticalLayout is a Map(not List) https://tppr.me/pMftL. Can you update your config.json again with this setting "VerticalLayout":{"key":"xkmve70sbk","layout":"columns","name":"New1 Collection"}. When you customize in issue #3672, Cache will not support this
> Thanks!
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/8d6e85771493ad553ff6ee14ea2f7033c74a4be0/68747470733a2f2f747070722e73332e616d617a6f6e6177732e636f6d2f75706c6f6164732f30633462613937343661383065333634313036616566393131386432356666322e706e67"><img alt="" height="14" src="/favicon-32x32.png"> tppr.me**[Public - Google Chrome_2020-06-18 17-38-15](https://tppr.me/pMftL)**

i could not understand your answer

**Comment by vumanhsn97** [comment]
VerticalLayout in your cache is https://tppr.me/aLp3B. Not same step above. Please try this step again that I can check this issue.
1/ i added this line in config_en.json
"VerticalLayout":{"key":"xkmve70sbk","layout":"columns","name":"New1 Collection"},
2 / uploaded the config_en.json to mstore api and emptying the cache

In issue #3672, Mstore API will not support for VerticalLayout type List. So cache will not working with VerticalLayout data response. {} is a Map and [] is a List

**Comment by bigbossmaher** [comment]
@vumanhsn97 
1/check now , this is the config that is uploaded to Mstore API
`{
  "HorizonLayout": [{
      "layout": "logo",
      "showMenu": true,
      "showSearch": true,
      "showLogo": true,
      "background": "#FFFFFF"
    },
    {
      "layout": "category",
      "type": "icon",
      "wrap": false,
      "size": 1.0,
      "radius": 50.0,
      "items": [{
          "category": 18,
          "image": "https://user-images.githubusercontent.com/1459805/62820029-2e679f00-bb88-11e9-80de-fdf115cfd942.png",
          "colors": [
            "#3CC2BF",
            "#3CC2BF"
          ],
          "originalColor": false
        },
        {
          "category": 24,
          "image": "assets/icons/categories/ic_dress.png",
          "colors": [
            "#3E6AB5",
            "#3E6AB5"
          ]
        },
        {
          "category": 25,
          "image": "assets/icons/categories/ic_shorts.png",
          "colors": [
            "#53A2CC",
            "#53A2CC"
          ]
        },
        {
          "category": 28,
          "image": "assets/icons/categories/ic_glasses.png",
          "colors": [
            "#53688A",
            "#53688A"
          ]
        },
        {
          "category": 29,
          "image": "assets/icons/categories/ic_tie.png",
          "colors": [
            "#43506A",
            "#43506A"
          ]
        },
        {
          "category": 30,
          "image": "assets/icons/categories/ic_panties.png",
          "colors": [
            "#12B58C",
            "#12B58C"
          ]
        }
      ]
    },
    {
      "layout": "bannerImage",
      "isSlider": true,
      "autoPlay": false,
      "showNumber": false,
      "design": "default",
      "showBackGround": true,
      "radius": 2.0,
      "items": [{
          "category": 28,
          "image": "https://user-images.githubusercontent.com/1459805/59846818-12672e80-938b-11e9-8184-5f7bfe66f1a2.png",
          "padding": 15.0
        },
        {
          "category": 29,
          "image": "https://user-images.githubusercontent.com/1459805/60091575-1f12ca80-976f-11e9-962c-bdccff60d143.png",
          "padding": 15.0
        },
        {
          "product": 30,
          "image": "https://user-images.githubusercontent.com/1459805/60091808-a19b8a00-976f-11e9-9cc7-576ca05c2442.png",
          "padding": 15.0
        }
      ]
    },
    {
      "layout": "bannerImage",
      "items": [{
        "url": "https://inspireui.com",
        "image": "https://user-images.githubusercontent.com/1459805/59846820-12672e80-938b-11e9-8fa6-b331b7db331d.png",
        "padding": 5.0
      }]
    },
    {
      "layout": "bannerImage",
      "items": [{
          "category": 18,
          "image": "https://user-images.githubusercontent.com/1459805/59846823-12ffc500-938b-11e9-8d93-65ead3d6b1dd.png",
          "padding": 5.0
        },
        {
          "category": 23,
          "image": "https://user-images.githubusercontent.com/1459805/59846824-12ffc500-938b-11e9-8d5a-fc42cb1b7658.png",
          "padding": 5.0,
          "featured": true
        }
      ]
    },
    {
      "name": "Recent View",
      "layout": "recentView"
    },
    {
      "name": "Woman Collections",
      "image": "",
      "layout": "threeColumn",
      "category": 22,
      "isSnapping": true
    },
    {
      "name": "Man Collections",
      "image": "",
      "layout": "twoColumn",
      "category": 21,
      "isSnapping": true
    },

    {
      "name": "Our Blog Posts",
      "layout": "blog"
    },
    {
      "name": "New Collections",
      "layout": "staggered",
      "limit": 20,
      "category": 29
    }
  ],
  "VerticalLayout":{"key":"xkmve70sbk","layout":"columns","name":"New1 Collection"},
  "Setting": {
    "MainColor": "#3FC1BE",
    "ProductListLayout": "list",
    "StickyHeader": true
  },
  "TabBar": [{
      "layout": "home",
      "icon": "assets/icons/tabs/icon-home.png"
    },
    {
      "layout": "category",
      "categoryLayout": "card",
      "icon": "assets/icons/tabs/icon-category.png"
    },
    {
      "layout": "search",
      "icon": "assets/icons/tabs/icon-search.png"
    },
    {
      "layout": "cart",
      "icon": "assets/icons/tabs/icon-cart2.png"
    },
    {
      "layout": "profile",
      "icon": "assets/icons/tabs/icon-user.png",
      "showChat": true
    }
  ],
  "searchSuggestion": [
    "man",
    "dress",
    "Stitch",
    "ma"
  ],
  "OnBoarding": {
    "data": [
      {
        "title": "Welcome to FluxStore",
        "image": "assets/images/fogg-delivery-1.png",
        "desc": "Fluxstore is on the way to serve you. ",
        "background": "#FFF3F2"
      },
      {
        "title": "Connect Surrounding World",
        "image": "assets/images/fogg-uploading-1.png",
        "desc": "See all things happening around you just by a click in your phone. Fast, convenient and clean.",
        "background": "#F2FFFC"
      },
      {
        "title": "Let's Get Started",
        "image": "fogg-order-completed.png",
        "desc": "Waiting no more, let's see what we get!",
        "background": "#F9F2FF"
      }
    ]
  }
}`

for the #3672 issue , do you have any solution ?, 
thank you

**Comment by vumanhsn97** [comment]
@bigbossmaher 
Need to category id to get list product data. Edit your VerticalLayout to 
"VerticalLayout":{"key":"xkmve70sbk","layout":"columns","name":"New1 Collection", "category": 128}

For issue #3672, You need to edit Mstore API. Edit in controllers/MStoreHome.php: 
![image](https://user-images.githubusercontent.com/39208623/85121138-76e2f500-b24e-11ea-82f4-7fde13230b34.png)

**Comment by bigbossmaher** [comment]
it is updated try now 
2/ for issue 3672 , i will tell you after 2 hours if it works or not , thanks

**Comment by vumanhsn97** [comment]
@bigbossmaher 
It is working well. 
![image](https://user-images.githubusercontent.com/39208623/85124506-35eddf00-b254-11ea-9c87-68294ee13d1d.png)

**Comment by bigbossmaher** [comment]
thanks and what i should type in category to show the products from all categories 
"category": 128

**Comment by bigbossmaher** [comment]
hello @vumanhsn97  , are you there ?

**Comment by vumanhsn97** [comment]
@bigbossmaher 
Remove category param in VerticalLayout. In Mstore API, remove this line: 
![image](https://user-images.githubusercontent.com/39208623/85242864-64dd9e00-b46a-11ea-9f35-b2ce81670b07.png)

in issue #3672 , you need to use loop to get data from list item

**Comment by bigbossmaher** [comment]
Thanks , can you give me an example of this loop and where i put code ?

**Comment by vumanhsn97** [comment]
Look like this: https://tppr.me/1wlKZ

**Comment by bigbossmaher** [comment]
@vumanhsn97 
thanks for your replay , but i'm currently having other issues and they are debugging i cant' keep trying modifying to code until i get the result 

can you give me directly the code to put ?

pleasse :)

and this is my config
  "VerticalLayouts":
  [
    {
      "limit": 6,
      "category": 117,
      "name": "Kitchen Collections"
    },
    {
      "limit": 6,
      "category": 125,
      "name": "Toys Collections"
    },
    {
      "limit": 100,
      "name": "New Collections",

    }
  ],

**Comment by bigbossmaher** [comment]
i tried this but same error
`public function get_home_data()
    {
        $api = new WC_REST_Products_Controller();
        $request = new WP_REST_Request('GET');
        $path = str_replace('plugins/mstore-api/controllers','uploads',dirname( __FILE__ ))."/2000/01/config.json";
        
        if (file_exists($path)) {
            $fileContent = file_get_contents($path);
            $array = json_decode($fileContent, true);

            //get products for horizontal layout
            $results = [];
            $horizontalLayout = $array["HorizonLayout"];
            foreach ($horizontalLayout as $layout) {
                if (isset($layout['category']) || isset($layout['tag'])) {
                    $layout["data"] = $this->getProductsByLayout($layout, $api, $request);
                    $results[] = $layout;
                }else{
                    if(isset($layout["items"]) && count($layout["items"]) > 0){
                        $items = [];
                        foreach ($layout["items"] as $item) {
                            $item["data"] = $this->getProductsByLayout($item, $api, $request);
                            $items[] = $item;
                        }
                        $layout["items"] = $items;
                    }
                    $results[] = $layout;
                }
            }
            $array['HorizonLayout'] = $results;
            
            
                        //get products for vertical layout
            $results = [];
            $VerticalLayouts = $array["VerticalLayouts"];
            foreach ($VerticalLayouts as $layout) {
                if (isset($layout['category']) || isset($layout['tag'])) {
                    $layout["data"] = $this->getProductsByLayout($layout, $api, $request);
                    $results[] = $layout;
                }else{
                    if(isset($layout["items"]) && count($layout["items"]) > 0){
                        $items = [];
                        foreach ($layout["items"] as $item) {
                            $item["data"] = $this->getProductsByLayout($item, $api, $request);
                            $items[] = $item;
                        }
                        $layout["items"] = $items;
                    }
                    $results[] = $layout;
                }
            }
            $array['VerticalLayouts'] = $results;


/*
            //get products for vertical layout
            $layout = $array["VerticalLayouts"];
            //if (isset($layout['category'])) {
                $layout["data"] = $this->getProductsByLayout($layout, $api, $request);
                $array['VerticalLayouts'] = $layout;
            //}
           */
            return $array;
        }else{
            return new WP_Error( "existed_config", "Config file hasn't been uploaded yet.", array( 'status' => 400 ) );
        }
    }`

**Comment by bigbossmaher** [comment]
posted again here
https://github.com/inspireui/support/issues/3857
