### ISSUE TITLE
Mstore multivendor f

### ISSUE THREAD

**Issue by AbdullahNabta** [inspireui/support#378]
**Required Info (please complete the following information):**
 - Product: MStore Multi Vendor
 - Your Purchased Code: 81097dcc-f5c1-435c-bca6-e8e388bb725a

**Describe the bug**
How do I remove the the facebook login and the library. I just want login and registering from the wordpress which is already there. Also How can I change the checkout fields. such as the zip code and other? I have a plugin on my website called checkout feild editor which let me remove the zip code option. So How can i Remove it.
**Screenshots**

**Additional context**
Add any other detail logs about the problem here.
@minhcasi @luyx2412

**Comment by thangvo9x** [comment]
Hi. Thanks for your purchase. You can remove it by go to src/containers/Login/index.js
and remove this block 
<img width="353" alt="block" src="https://user-images.githubusercontent.com/23457178/54002620-d9ab9c80-4181-11e9-8979-15ada4b1d480.png">
Thanks

**Comment by AbdullahNabta** [comment]
Thank you. What about my second question?
" Also How can I change the checkout fields. such as the zip code and other? I have a plugin on my website called checkout feild editor which let me remove the zip code option. So How can i Remove it."

**Comment by thangvo9x** [comment]
You can edit it in Container/Cart/Delivery/index.js 
Thanks
