### ISSUE TITLE
remove privace and tream login and fluxstore woo

### ISSUE THREAD

**Issue by teampotlot** [inspireui/support#3781]
how to delete (privace and tream
![Untitled-1](https://user-images.githubusercontent.com/66760408/84945053-56654e80-b119-11ea-81ca-790c4cf80dc4.png)

how to delete (privace and tream) in the login menu

and set my drawing space in the category

**Comment by minhcasi** [comment]
@teampotlot - pls try to use the Inspector tool to remove/customize any UI from the app
ref: video: https://www.youtube.com/watch?v=yGMt3Y20Zmg
documents: https://docs.inspireui.com/fluxstore/customization/#1-how-to-customize-any-ui-from-app

The spacing on product list will be fixed on next release - or you could download the latest fix on Gitlab

Please help to move your all conversation to the same ticket support #3761
