### ISSUE TITLE
Home screen not updated after change in config_en.json

### ISSUE THREAD

**Issue by kuldeepkhobrekar** [inspireui/support#3782]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: after update config_en.json file home screen does't show changes on android
+ Product & version: Fluxstore Multivendor - Dokan
+ Flutter (or React Native) version:  Flutter
+ Testing Device/Simulator:  Android simulator
+ Screenshot issues (drag the file to attach here):attached 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊
![image](https://user-images.githubusercontent.com/49717293/85000814-8be95680-b170-11ea-8f76-38d520d072b6.png)

**Comment by philipvu30** [comment]
Hi,

Please check if you have set the isCaching in lib/common/config/general.dart to false.

Thank you.

**Comment by philipvu30** [comment]
Closed as no response in 2 days. 

If you are happy with our services/support, would you mind rating us on your [download page](https://codecanyon.net/downloads)?
We truly appreciate your help.

**Comment by nomicool** [comment]
i am also facing the same issue many days ticket open I'm not near to solution

**Comment by kuldeepklk** [comment]
Try to clean flutter and build again.

**Comment by nomicool** [comment]
> Try to clean flutter and build again.

ok let me try
