### ISSUE TITLE
Login or Sign up not working on app

### ISSUE THREAD

**Issue by dragooninasia** [inspireui/support#3783]
When trying to login or signing up a new account it just shows loading and nothing happens for over and hour now.
Using the latest SDKs
both sim and apple and android phone

Already submitted license on the url provided before.  Do we have to keep doing this every time?

**Comment by minhcasi** [comment]
It could be your website reject the connection, could i know if you could see any error log from the console log from Android Studio?

**Comment by dragooninasia** [comment]
Token and no errors

**Comment by dragooninasia** [comment]
another issue is, when registering using the app for new users, it categories them as a subscriber and not a customer even though settings on site is default to customer.

**Comment by dragooninasia** [comment]
Issue with removing onesing for push.  Firebase setup already but in xcode still shows onesig in configuration

**Comment by minhcasi** [comment]
Hi, you could remove the onesignal from pubspec.yalm and comment other related file to fix the onesignal 

<img width="779" alt="Screen Shot 2020-06-19 at 07 38 11" src="https://user-images.githubusercontent.com/1459805/85084715-d5cd4d80-b1ff-11ea-97eb-4b32b9502d16.png">
<img width="910" alt="Screen Shot 2020-06-19 at 07 38 32" src="https://user-images.githubusercontent.com/1459805/85084739-e1b90f80-b1ff-11ea-9db9-c336af183dcb.png">
<img width="859" alt="Screen Shot 2020-06-19 at 07 38 57" src="https://user-images.githubusercontent.com/1459805/85084760-f09fc200-b1ff-11ea-8fe1-01a30d6f3f2a.png">

**Comment by dragooninasia** [comment]
WHat about Firebase implementation after?

**Comment by dragooninasia** [comment]
Still the issue with the login and sign up.  No solution there still for my original issue.

**Comment by dragooninasia** [comment]
Can you provide solution for Login and Sign up stall?

**Comment by dragooninasia** [comment]
1.  Need solution for Login and Sign up Stalling.
     Issue also includes if new users sign up, their designation should be 
     'Customer'.  This is what is set at default, but they show up as 'Subscriber'.
     Login and Sign up works, but it just stalls on the login or sign up page 
     'loading'.  I have to exit back to the previous page to continue.  It doesn't 
     automatically go back after successfully logging in or sing-up.

2.  Push Notification doesn't work at all. Changed the code to comments in all locations listed above and still nothing.  Checked the firebase, xcode identifier, etc..  Still no movement on this. Need a solution other then using OneSignal.  I don't want to use OneSignal as I am already invested in to firebase.

**Comment by dragooninasia** [comment]
Don't you have other developers to help you Minh deal with all these issues on Github?

**Comment by dragooninasia** [comment]
Come on guys, give solutions. I've been emailing you about this with no response.

**Comment by minhcasi** [comment]
We wanted to thank you for your patience during this busy time. We currently have reduced staff and a significantly higher volume of inquiries. We’re working as hard as we can to get to your request as soon as possible, pls help to check our support policies on[ this page](https://codecanyon.net/item/fluxstore-multi-vendor-flutter-ecommerce-full-app/25013325/support)

1. The Registration is set as default `Subscriber` by woocommerce Rest API, you could try to customize this feature from the Rest API side.

2. The push notification is working with our testing, please help to double-check the detailed guide 
- https://docs.inspireui.com/fluxstore/firebase/
- https://medium.com/@inspireui/setup-firebase-cloud-messaging-fcm-push-notification-for-flutter-apps-8c767fe64e54
