### ISSUE TITLE
FluxStore version 1.4.1: Reviews not added on WP side

### ISSUE THREAD

**Issue by kalakgl** [inspireui/support#3784]
I just realized the reviews added in the app, are not added on the wordpress part.
![IMG_1755](https://user-images.githubusercontent.com/12363496/85007981-0bf4c980-b13b-11ea-804f-82d530a499fa.PNG)

**Comment by minhcasi** [comment]
@kalakgl - pls help to download the latest `1.4.2` to fix this issue - thank you!

**Comment by kalakgl** [comment]
@minhcasi Thanks, is it possible to know which files have been changed? I really don't want to start over with my localizations and "commented out" some of the features.

**Comment by minhcasi** [comment]
@kalakgl - please help to check the detail file change via Gitlab (pls submit here if you have don't have account http://gitlab.inspireui.com)
<img width="1254" alt="Screen Shot 2020-06-20 at 11 39 28" src="https://user-images.githubusercontent.com/1459805/85191883-b4955b80-b2ea-11ea-8766-123a05498b49.png">

**Comment by thawhakyi** [comment]
hello @minhcasi 
I am using mylisting theme and facing problems with API configuration about ( featured, verified and can't add comments and reviews from app side. I wanna know fluxlisting supports that features for mylisting theme? Thank You.

**Comment by kalakgl** [comment]
@minhcasi Thanks, I just requested access. But is it only the review.dart file that have changed ?

**Comment by minhcasi** [comment]
it's sent 

Please also check the guide how to manage git on this link https://medium.com/@inspireui/how-to-upgrade-fluxstore-projects-by-using-git-cebde7489ea6

**Comment by minhcasi** [comment]
Let us know your checking - thank you!

**Comment by kalakgl** [comment]
I just connect, and made a "clone" :-) Are looking into this fresh updated package, and make my needed adjustments.

**Comment by kalakgl** [comment]
I have added the gitlab, and connected to your project etc.
Downloaded the files to my Mac etc.
Run the android sim with no changes, running OK.
Then I start to make changes to config.dart and config.json - then it all won't run. I have now downloaded a "clean" package from gitlab 3 times, and every time it get errors as soon as I make changes to config.dart and config.json.
I know this is a great application to use for someone like you. But for me, it is a nightmare.
All I want is to have these reviews corrected. Everything else was running just fines.

**Comment by kalakgl** [comment]
I have iOS build ready, with minimal changes. But still no reviews are added to the wordpress backend.

**Comment by kalakgl** [comment]
Solved. I made changes to the WP backend.

**Comment by dalia-jasulaitiene** [comment]
Hello, kalakgl, which changes did you do in the WP backend?
I have the same issue with a newest version, I guess its also need to be done in WP backend.
Thank you in advance!

**Comment by kalakgl** [comment]
@dalia-jasulaitiene I just change my comment settings so they don't need to have username and email.

**Comment by dalia-jasulaitiene** [comment]
Thanks! Taking tick out of "Users must be registered and logged in to comment" helped me too.
