### ISSUE TITLE
Fluxstore multivendor, page 404 #3656,  Error when running app

### ISSUE THREAD

**Issue by Shiru-kun** [inspireui/support#3786]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
when i run in debug mode  i get a red screen  with yellow text
+ Product & version:
Fluxstore Multvendor 1.7.X
+ Flutter (or React Native) version:
flutter 1.17.3 
+ Testing Device/Simulator: 
Samsung A01 
+ Screenshot issues (drag the file to attach here): 
![Screenshot_20200618-125818](https://user-images.githubusercontent.com/54008441/85013587-20e65280-b165-11ea-8c96-a10462652d56.jpg)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhtruong315** [comment]
Hi @Shiru-kun can u fork from our git repo then invite me: minhtruong315@gmail.com? 
https://medium.com/@inspireui/how-to-upgrade-fluxstore-projects-by-using-git-cebde7489ea6
Thanks

**Comment by Shiru-kun** [comment]
> 

Already added u to my repo. 
GitHub.com/Shiru-kun/krolycnew


But I already fixed it by creating a new config json file. 

But with the config_en.json. 
I’m getting that error. 

Could u see what’s happening to the registration page in the app. 
I’m getting a yellow/black thing.

**Comment by Shiru-kun** [comment]
i got another question.  i tried to publish my app. 
i created the key.jks. and build the app for release. but when i installed that version in my phone i couldnt signin. the i tried to run i debug mode and encounter an error: 
BlockPolicyGuard i will screenshot it...

**Comment by Shiru-kun** [comment]
hi no response?

**Comment by minhtruong315** [comment]
![Simulator Screen Shot - iPhone 11 - 2020-06-23 at 14 46 43](https://user-images.githubusercontent.com/10402500/85375352-5ec9e900-b560-11ea-8cd8-250ccd265f16.png)
HI @Shiru-kun I ran your source code.  it's working well

**Comment by minhcasi** [comment]
@minhtruong315 - pls help with checking

**Comment by Shiru-kun** [comment]
i cant login

**Comment by Shiru-kun** [comment]
![Screenshot from 2020-06-23 11-10-55](https://user-images.githubusercontent.com/54008441/85387165-c83bfe80-b544-11ea-9588-02c4337f8972.png)
![Gsvd](https://user-images.githubusercontent.com/54008441/85387184-ce31df80-b544-11ea-9088-bebceaa1f796.jpg)

**Comment by minhtruong315** [comment]
@Shiru-kun I checked your source code. it's working well
https://www.dropbox.com/s/swws14axujgibyf/login.mov?dl=0

**Comment by Shiru-kun** [comment]
thats weird... i wll check again.

**Comment by Shiru-kun** [comment]
i truly cant login,  yesterday i pushed something to my repo check it please

**Comment by Shiru-kun** [comment]
from console i get this :
![image](https://user-images.githubusercontent.com/54008441/85549920-bdef3280-b620-11ea-956b-247dea19b93d.png)

**Comment by minhtruong315** [comment]
@Shiru-kun You can try to use my account to login: a34@gmail.com/123
What is your account that you can't login?

**Comment by Shiru-kun** [comment]
Its my admin account from my website.
I tried with your account and its says wrong password.

**Comment by minhtruong315** [comment]
@Shiru-kun add my skype: minhtruong315
I will help you check via teamviewer

**Comment by Shiru-kun** [comment]
check your skype

**Comment by Shiru-kun** [comment]
thanks it was solved...
