### ISSUE TITLE
Debug Error

### ISSUE THREAD

**Issue by gengefasta** [inspireui/support#3789]
I have done with verification, codecanyoon username is Medytz. Please support on this issue

BUILD FAILED in 5m 4s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
✏️ Creating android\settings_aar.gradle...
[!] Flutter tried to create the file android\settings_aar.gradle, but failed.
To manually update settings.gradle, follow these steps:

1. Copy `settings.gradle` as `settings_aar.gradle`
2. Remove the following code from `settings_aar.gradle`:

        def flutterProjectRoot = rootProject.projectDir.parentFile.toPath()

        def plugins = new Properties()
        def pluginsFile = new File(flutterProjectRoot.toFile(), '.flutter-plugins')
        if (pluginsFile.exists()) {
            pluginsFile.withReader('UTF-8') { reader -> plugins.load(reader) }
        }

        plugins.each { name, path ->
            def pluginDirectory = flutterProjectRoot.resolve(path).resolve('android').toFile()
            include ":$name"
            project(":$name").projectDir = pluginDirectory
        }
Exception: Please create the file and run this command again.

**Comment by minhcasi** [comment]
@gengefasta - there is some important guide to run the Flutter on this link https://flutter.dev/docs/get-started/install - please help to make sure you could run the `Test Drive` example to verify if all the Android SDK is installed correctly - thank you!

**Comment by gengefasta** [comment]
@minhcasi I have done all procedure for installation, my app is on playstore now. i updates some plugins with android studio then a problem start. Any idea to check plugin compatibility?

**Comment by minhcasi** [comment]
@gengefasta - you could try to clean flutter cache could fix the issue - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

**Comment by gengefasta** [comment]
@minhcasi I have done those too  but still when i run app i got same problem, please refer the image below

![image](https://user-images.githubusercontent.com/66345726/85104087-91967900-b210-11ea-94ae-e54543c2bd59.png)

**Comment by minhcasi** [comment]
@gengefasta - could you help to double-check this video https://www.youtube.com/watch?v=3dv_8UerNpQ

Please help to send us your result `flutter doctor`

**Comment by gengefasta** [comment]
@minhcasi i have done all but i get same error.

this is my flutter doctor result

![image](https://user-images.githubusercontent.com/66345726/85197941-28d0fe80-b2ed-11ea-80c7-6a6d2c3ebc89.png)

**Comment by minhcasi** [comment]
@gengefasta - you config flutter look ok, could I check if you have changed any build grade or android setting? 

Please help to check the default download package so see if you have the same issue

**Comment by guzmanahmed** [comment]
Can you advise me what is the build gradle version required?

**Comment by minhcasi** [comment]
use the default version from download package and don't upgrade by a suggestion from android studio

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
