### ISSUE TITLE
A problem occurred configuring project ':app'

### ISSUE THREAD

**Issue by 04Ank** [inspireui/support#379]
**Mandatory Info (please complete the following information):**
 - Product: [e.g. MStore Pro]
 - Your Purchased Code: [
a356d2b4-3c3b-4fa3-89cd-e710b8d96e64]
(we may not reply if you are not our customer)

**Describe the issues**
Unable to run the project please help. 

already tried to run sample project and its run fine in my windows. 
**Screenshots**

![error](https://user-images.githubusercontent.com/48328340/54010277-25674180-4194-11e9-9865-c6814fdb0663.png)

**Comment by 04Ank** [comment]
Now getting these errors 
![error2](https://user-images.githubusercontent.com/48328340/54050479-4e73ea80-4205-11e9-9a93-3044f720c1f2.png)

**Comment by minhcasi** [comment]
Hi @04Ank - could you try to remove the local.properties from the android folder to see if it can be fixed?

Also, try to run the Example project from this guide - https://facebook.github.io/react-native/docs/getting-started.html - and check to see if you have ready setup all the library correctly 

Thank you!
