### ISSUE TITLE
Language and currency

### ISSUE THREAD

**Issue by Marcleiton** [inspireui/support#3790]
Hello,

I tried all the ways and I can't change the default currency and language of the fluxstore in woocommerce.

I use the language of Brazil Portuguese and the default currency would be BRL, with a symbol in R $, could you help me do that?

**Comment by minhcasi** [comment]
@Marcleiton - could I check if you have changed update config:

<img width="965" alt="Screen Shot 2020-06-19 at 07 28 01" src="https://user-images.githubusercontent.com/1459805/85084224-699e1a00-b1fe-11ea-89e2-c9f7238496c3.png">

**Comment by Marcleiton** [comment]
> @Marcleiton - posso verificar se você mudou a configuração da atualização:
> 
> <img alt="Captura de tela 2020-06-19 em 07 28 01" width="965" src="https://user-images.githubusercontent.com/1459805/85084224-699e1a00-b1fe-11ea-89e2-c9f7238496c3.png">

Hi, I switched but it doesn't work for a Brazilian BRL currency, I don't know if I'm putting the wrong symbol and everything.

https://imgur.com/a/5dyZ7YZ

**Comment by kibbyboi** [comment]
I have a kind of similar issue, on mine when you switch currency it does switch with current exchange rate but same amount

**Comment by minhcasi** [comment]
@Marcleiton - try to resend your latest `lib\common` and `lib\config` folder - we will help for checking - thank you!

**Comment by Marcleiton** [comment]
> @Marcleiton - try to resend your latest `lib\common` and `lib\config` folder - we will help for checking - thank you!

follow the file on the drive: https://drive.google.com/file/d/1-O0fip6DMotaaBbm94siOsawbEU-ocOv/view?usp=sharing

**Comment by philipvu30** [comment]
Hi @Marcleiton ,

Sorry for the delayed response.
You should modify the code like this
  ```
  "symbol": "R\$",
    "decimalDigits": 0,
    "symbolBeforeTheNumber": true,
    "currency": "BRL"
```

**Comment by philipvu30** [comment]
Hi @kibbyboi,

The app does not support convert currency.

**Comment by Marcleiton** [comment]
> Hi @Marcleiton ,
> 
> Sorry for the delayed response.
> You should modify the code like this
> 
> ```
> "symbol": "R\$",
>   "decimalDigits": 0,
>   "symbolBeforeTheNumber": true,
>   "currency": "BRL"
> ```

Hi, thanks, could you help me with this problem? at all times the app closes, aiming that I also tested it on the emulator and haven't done tests in other places https://drive.google.com/file/d/1BVHWP1iW6gqCkcUOZRDCuLS7gtrN95Uw/view?usp=sharing

**Comment by philipvu30** [comment]
Hi,

I assume you have changed the Android bundle ID because this error is related to this kind of behavior.
If that is the case, you should: 
- Follow this [document](https://docs.inspireui.com/fluxstore/delivery-android/).
- On Windows, use Ctrl + Shift + F and find all terms that match **com.inspireui.fluxstore** and replace them with your package name.

Thank you.

**Comment by philipvu30** [comment]
Closed as no response in 2 days. 

If you are happy with our services/support, would you mind rating us on your [download page](https://codecanyon.net/downloads)?
We truly appreciate your help.
