### ISSUE TITLE
How to Add Date & Time Picker Field at checkout page in Fluxstore Woocomrerce

### ISSUE THREAD

**Issue by shah0203** [inspireui/support#3791]
Hi,

I want to add "Date & Time" field at checkout page so that my customers can select the date & time for their service booked. I am attaching the screenshot with highlighting the place where i expect the Date & Time field to be.

Please help me with steps or any documents, as i have already published my APP on google play and need to fix this as soon as possible. your prompt action will be highly appriciated.

![image](https://user-images.githubusercontent.com/63024624/85054815-4e52f080-b1a5-11ea-9fb2-97ef43c3eaa1.png)

**Comment by minhcasi** [comment]
Hi @shah0203 - you could customize the file 

<img width="1145" alt="Screen Shot 2020-06-19 at 07 47 13" src="https://user-images.githubusercontent.com/1459805/85085138-17aac380-b201-11ea-996d-9dda566ddf36.png">

**Comment by shah0203** [comment]
Hi,

As per your advise i have added the below code in the "cart_summary.dart" file for date picker option. but i am getting an error as attached is the screenshot of that error for your review & action.

kindly advise as my application is already published and customers are complaining due to delivery date option is not available in the Cart page. I hope you understand.

-----------------------------------------------------------------------------------
This is the code i have added:
![image](https://user-images.githubusercontent.com/63024624/85185597-46767780-b29d-11ea-93f6-fba035464205.png)


This is the error i am getting:
![image](https://user-images.githubusercontent.com/63024624/85185566-18913300-b29d-11ea-8093-69d8f8dfaadf.png)

**Comment by shah0203** [comment]
@minhcasi ..Please help me to fix the above issue. your prompt response will be highly appreciated.
