### ISSUE TITLE
all products image not showing

### ISSUE THREAD

**Issue by miskayapp** [inspireui/support#3792]
![WhatsApp Image 2020-06-18 at 20 09 40 (1)](https://user-images.githubusercontent.com/64660378/85062386-4e042680-b1a0-11ea-9f86-2573354ebc6d.jpeg)
![WhatsApp Image 2020-06-18 at 20 09 40](https://user-images.githubusercontent.com/64660378/85062388-4f355380-b1a0-11ea-93e9-6992abaf7334.jpeg)

some images are not showing, but when i click on it, it comes up.

yes caching is set to true and regenerate plugin, i have done it many times.

**Comment by minhcasi** [comment]
Hi, pls try to check the Log console from android studio to see if it display any error, also try to update `tool.sdart` to return FadeInImage

<img width="949" alt="Screen Shot 2020-06-19 at 07 42 10" src="https://user-images.githubusercontent.com/1459805/85084926-6441cf00-b200-11ea-943a-d094b792f276.png">

**Comment by miskayapp** [comment]
i have the same code ??
![minh](https://user-images.githubusercontent.com/64660378/85105784-f6e36d80-b202-11ea-9303-29d5e95bf889.PNG)

**Comment by minhcasi** [comment]
@miskayapp - try to comment the if condition as my screenshot

**Comment by minhcasi** [comment]
Let us know your checking - thanks

**Comment by miskayapp** [comment]
same thing, some pictures are not showing,

error seen

 Exception caught by image resource service ════════════════════════════════════════════════
HTTP request failed, statusCode: 400, https://i2.wp.com/www.miskayboutique.com/wp-content/uploads/2020/05/1d-e1592504543703-medium.jpeg?fit=720%2C912&ssl=1
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by miskayapp** [comment]
ok i have seeb the error, only jpg files are showing not jpeg, is there any way i can add jpeg to the files accpeteed?

**Comment by minhcasi** [comment]
@miskayapp 

- Try to remove this condition to skep `jpeg` from `lib\common\tools.dar`
<img width="853" alt="Screen Shot 2020-06-21 at 12 47 06" src="https://user-images.githubusercontent.com/1459805/85217648-51c0c480-b3bd-11ea-97e6-2544b7933883.png">

- Also, pls help us to keep one ticket support open and comment your all issue to one #3829

**Comment by miskayapp** [comment]
ok. i removed the code below and the images started showing, i hope its not gonna affect the app.

      if (ext == ".jpeg") {
        imageURL = url;
      } else {
        switch (size) {
          case kSize.large:
            imageURL = '$pathWithoutExt-large$ext';
            break;
          case kSize.small:
            imageURL = '$pathWithoutExt-small$ext';
            break;
          default: // kSize.medium:e
            imageURL = '$pathWithoutExt-medium$ext';
            break;
        }
      }
