### ISSUE TITLE
OneSignal to Firebase issue for Push

### ISSUE THREAD

**Issue by dragooninasia** [inspireui/support#3793]
Default is set to OneSignal but don't want to use it.  Setup Firebase for push notification but doesn't work because OneSignal is still on as default from the source original.
No Docs on changing this at all other than to setup Firebase.
Did everything in the Firebase Push setup, no errors, but no notification.

Lastest SDKs
Both iOS and Android

Already submitted several times http://verify.inspireui.com_**

**Comment by minhcasi** [comment]
@dragooninasia - pls help to add your all comment to one ticket #3783
