### ISSUE TITLE
[Fluxstore Pro Woocomerce] - customer order status not working

### ISSUE THREAD

**Issue by tjain90** [inspireui/support#3795]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 
How to add custom order status like dispatched in app. In website it is working perfectly file. I am using custom order plugin for this but for all custom order status they are marked as pending payment in app. For example in below screenshot when custom order status was dispatched in web it shows pending payment in app. 
![IMG-20200619-WA0001](https://user-images.githubusercontent.com/6376301/85079565-c096f580-b1e4-11ea-904d-228781c601c2.jpg)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@tjain90 - pls continuous the comment on #3653
