### ISSUE TITLE
Create Listing Endpoint

### ISSUE THREAD

**Issue by znchung** [inspireui/support#3798]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
Trying to create a page that allows only authenticated users with specific roles to create listings. What is the REST API endpoint and its required field(s) aside from the ones that are set in Wordpress? I have tried the endpoint (as per screenshot), and as you can see it says that "not allowed to create as this user". What else should I include as part of the request?
+ Product & version: FluxListing, Listeo
+ Flutter (or React Native) version:  Flutter 1.17.1
+ Testing Device/Simulator: N/A
+ Screenshot issues (drag the file to attach here): 
<img width="646" alt="Screen Shot 2020-06-19 at 2 42 40 PM" src="https://user-images.githubusercontent.com/25826971/85104629-7bea7900-b23b-11ea-94a2-cd7c983a5276.png">

**_Step 2 (require): I have submitted an issue before. Unfortunately, I do not have a ticket ID, but here's the reference to an issue I've submitted before. https://github.com/inspireui/support/issues/3581

**Comment by philipvu30** [comment]
Hi,

This is related to Listeo theme issue as we didn't create that endpoint. Please ask them for assistance.

Thank you.

P/s: You can check their Listeo-core plugin, maybe you'll find a clue in the file class-listeo-core-submit.php

**Comment by znchung** [comment]
@philipvu30 is it currently supported in the mobile app for creating a new listing/product?
