### ISSUE TITLE
apple sign in error

### ISSUE THREAD

**Issue by miskayapp** [inspireui/support#3799]
I can't sign in with apple
![WhatsApp Image 2020-06-19 at 07 41 54](https://user-images.githubusercontent.com/64660378/85105240-0a420900-b202-11ea-99e9-8e40d235b6c3.jpeg)

**Comment by minhcasi** [comment]
@miskayapp - did you enable the Apple Login from Firebase?

**Comment by minhcasi** [comment]
pls move you all comment to #3792

**Comment by miskayapp** [comment]
YES, ANY ADDITIONAL SETTINGS?
