### ISSUE TITLE
[MStore Pro] FAQ - Common Issue with Solution

### ISSUE THREAD

**Issue by minhcasi** [inspireui/support#38]
...android/app/src/main/java/com/inspireui/mstore/MainApplication.java:55: error: constructor FBSDKPackage in class FBSDKPackage cannot be applied to given types;
            new FBSDKPackage(),
            ^
  required: CallbackManager
  found: no arguments
----------------------------

Root cause: When you run react-native link many time it could add more the Facebook config to the MainApplication that cause this duplicate config
<img width="1149" alt="screen shot 2018-11-24 at 7 04 17 pm" src="https://user-images.githubusercontent.com/1459805/48968025-db5eb380-f01b-11e8-8d2f-d96bad0eeacd.png">

Solution: remove the config "new FBSDKPackage()" and from the import library will be fix the issue. And also remove some similar duplicate, example: RNFetchBlobPackage

The correct one will look like this - https://gist.github.com/minhcasi/d5b34bc7765d61f38072a1ff867d42ad

**Comment by minhcasi** [comment]
Fix "CFBundleIdentifier", Does Not Exist" ?
Root cause: missing React library or facebookSDK

Step 1: run: yarn setup (only for Mac OS, on window you should run yarn install)

Step 2: Open beostore.xcworkspace select Product/Schema/Edit Schema, then click + button to find React and add it to top of the list, make sure the Parallelize Build is uncheck and the React should be on top
<img width="802" alt="assets 2f-lh63eujg5iaezihcz4d 2f-lh7kqxrhldihigqy0nw 2f-lh7l-tiemttkhtki8kz 2fscreen shot 2018-07-11 at 4 54 55 pm" src="https://user-images.githubusercontent.com/1459805/48968149-67250f80-f01d-11e8-85e5-968128504e3b.png">


(Other solution is select the React from the list and click build again)
<img width="831" alt="assets 2f-lh63eujg5iaezihcz4d 2f-lh7kqxrhldihigqy0nw 2f-lh7l9uurbbya6qh5azr 2fscreen shot 2018-07-11 at 4 55 41 pm" src="https://user-images.githubusercontent.com/1459805/48968150-6ab89680-f01d-11e8-881f-8dcb939a9eb3.png">

**Comment by minhcasi** [comment]
node_modules/react-native/React/../third-party/glog-0.3.4/src/base/mutex.h:105:10: fatal error: 'config.h' file not found ?
Root cause: incomparable XCode 9.3 and latest React Native framework +0.45

Solution:

Go to Project > node_modules > react_native 

Remove third-party folder 

Add which is given in below link: https://github.com/inspireui/third-party​

Reference: https://github.com/facebook/react-native/issues/14382​

**Comment by minhcasi** [comment]
404 error page when processing the payment?
First solution: 

First, we need to create a page and name it "mstore-checkout" and remember don't set any parent page for it, then set page template to"page custom template 

You need to install the mstore-checkout plugin in the first place.

Below is the screenshot for how to set:
<img width="853" alt="assets 2f-lh63eujg5iaezihcz4d 2f-lh7kqxrhldihigqy0nw 2f-lh7ltu197vseptksjwh 2fscreen shot 2018-07-11 at 4 57 01 pm" src="https://user-images.githubusercontent.com/1459805/48968161-950a5400-f01d-11e8-8a01-221059cee16d.png">


2. Second solution is copy the mstore-checkout.php to your wordpress template folder.

**Comment by minhcasi** [comment]
FBSDKCoreKit/FBSDKCoreKit.h' file not found 

Go to RCTFBSDK.xcodeproj then select build settings -> framework search paths
And change ~/Documents/FacebookSDK to $(HOME)/Documents/FacebookSDK

This bug happens on the XCode 10 - facebook/react-native-fbsdk#401

**Comment by thangvo9x** [comment]
Fix Unable to Proceed with Payment or 404 Not Found when Checkout
Go to admin page -> Pages menu item -> create a page with Template Name is "Page Custom Template".

**Comment by minhcasi** [comment]
update latest Expo version could cause VERY SLOW at development mode (as you will get the "require cycle: " warning), and the icons/images load quite slow.


Solution: remove the IF block from node_modules/metro/src/lib/polyfills/require.js (https://gyazo.com/df9e8c80e88d51fed30807b0a369e7e1) - Or, select the build with PRODUCTION MODE to resolve the issues)

**Comment by minhcasi** [comment]
Argument list too long: recursive header expansion failed at /Users/minhpham/Data/Projects/mstore-pro/mstore-expo/node_modules/react-native-admob/ios/../../../ios/Pods/React/node_modules/connect/lib/middleware/session.

-> Fix by edit the RNAdmobManager and change the framework search path to Pods/Google-Mobile-Ads-SDK
<img width="1291" alt="Screen Shot 2019-05-12 at 2 53 10 PM" src="https://user-images.githubusercontent.com/1459805/57579441-fa67d980-74c5-11e9-809e-72e783bff37f.png">

**Comment by minhcasi** [comment]
'AccountKit/AccountKit.h' file not found

https://github.com/inspireui/support/issues/800

**Comment by minhcasi** [comment]
NodeJS issue 
https://github.com/inspireui/support/issues/830
