### ISSUE TITLE
[BeoNews Pro] Article count off by 1 on HomeScreen, 2 & 3 column horizontal scrolling

### ISSUE THREAD

**Issue by levi-beers** [inspireui/support#380]
Anytime I configure BeoNews and use any of the horizontal scrolling components (card, 2 column, 3 column), the post count is off by 1. For example, if I have 10 posts only 9 will show for that category on HomeScreen. Likewise, if I have 5 posts only 4 will show. 
Also, for list component on HomeScreen, let's say I have 8 posts and I want to display 3 rows with paging. While there should be 3 pages, only 2 pages will be swipable, it never shows the 3rd page. It only shows the 3rd page if the post count is equally divisible by the row setting.

**Comment by levi-beers** [comment]
In Components/HorizonList/Index.js on line 100
`if (typeof list === 'undefined' || newIndex + numOfLine >= list.length)`
The = causes the final post of each category to not be displayed. Removing the = is the solution. Line 100 should be
`if (typeof list === 'undefined' || newIndex + numOfLine > list.length)`

**Comment by levi-beers** [comment]
@minhcasi I resolved this issue but you'll need to include this modification in the next release if you also find it solves the problem I've mentioned.

**Comment by minhcasi** [comment]
@levi-beers - thank you so much for your suggestion, we will update this fix and do some testing on next version - very best!

**Comment by minhcasi** [comment]
fixed on beonews 3.0
