### ISSUE TITLE
[FluxStore WooCommerce 1.7.5] Saved Addresses Add additional fields to checkout. #3605

### ISSUE THREAD

**Issue by IamJAX** [inspireui/support#3800]
Step 1 (require): describe detail issues & screenshots

Detail Issues:
**1. The app does not load user's address saved in the profile on the woocommerce site. Only locally stored address are available in app. Can it update address on the site and retrieve it?**

2. I want to add some additional fields to the checkout form on the app. The data is to be saved to custom fields for the order as 'billing_a'. **Can you please help me out with which file to change** and a sample code to add a single field?

**3. Address is not getting add when I select it from Google map.**

**4. Products are not loading in Home screen carousel until category page is opened. This issue is not there on version 1.7.4. But in 1.7.4 the variable products are not working.**

Product & version: FluxStore WooCommerce
Flutter (or React Native) version: 1.7.5
Testing Device/Simulator: Android

**Comment by IamJAX** [comment]
The screen recording of the loading issue on 1.7.5 is at
https://imgur.com/a/NMz8YNO

**Comment by minhtruong315** [comment]
@IamJAX 
Can you fork from our git repo then invite me: minhtruong315@gmail.com? https://medium.com/@inspireui/how-to-upgrade-fluxstore-projects-by-using-git-cebde7489ea6 I will help you check your issues Thanks

**Comment by IamJAX** [comment]
I have invited you

**Comment by minhtruong315** [comment]
Hi @IamJAX 
I see your app config is incorrect
```
const kAppConfig = 'https://demo.tony.ws/app/config_en.json';
```
The url is not found. Can u check again?
Thanks

**Comment by IamJAX** [comment]
Updated. Please check now.

**Comment by minhtruong315** [comment]
Hi @IamJAX add my skype: I will help you check via remotely. I dont know why I can't run your source code in my mac

**Comment by IamJAX** [comment]
May I have your skype ID please?

**Comment by minhtruong315** [comment]
minhtruong315

**Comment by minhtruong315** [comment]
Hi @IamJAX I ping you on the skype. But I haven't received your response. please check the skype.
Thanks

**Comment by minhtruong315** [comment]
Hi @IamJAX Thanks for your report
<img width="653" alt="Screen Shot 2020-06-27 at 1 33 24 PM" src="https://user-images.githubusercontent.com/10402500/85916433-e6726900-b87a-11ea-96f2-f5bb9a205992.png">
