### ISSUE TITLE
urgent no one helps opencart api problem

### ISSUE THREAD

**Issue by roseyazilim** [inspireui/support#3801]
**_Step 1 (require): describe detail issues & screenshots_**
I install for opencart, but the products on the site are not visible

config.dart = https://prnt.sc/t2kuld

I run the application in this way and the products are not visible

Do I need to do anything else after installing the opencart mstore plugin?

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

I filled the forum and sent it

**my edits**

**Comment by roseyazilim** [comment]
Products don't come when I run on Android ios and android

i'm trying with fluxbuilder it gives api error

https://prnt.sc/t2ptcr

https://prnt.sc/t2pu7s

**Comment by roseyazilim** [comment]
will you help?

does not pull data from the site

**Comment by roseyazilim** [comment]
will you help?

**Comment by minhtruong315** [comment]
@roseyazilim your website doesn't working on rest api
<img width="881" alt="Screen Shot 2020-06-22 at 8 34 02 AM" src="https://user-images.githubusercontent.com/10402500/85240679-2db7be80-b463-11ea-9930-10d51d8d665d.png">
Can u send me admin account via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/3801
I will help you  check the website

**Comment by roseyazilim** [comment]
I sent mail, thanks

**Comment by roseyazilim** [comment]
did you solve the problem? I sent mail

**Comment by minhtruong315** [comment]
You sent me admin account but I can't login. please check again,
Thanks

**Comment by roseyazilim** [comment]
hello,

istedigimburada.com/admin
admin
yasin2351@


23 Haz 2020 Sal 12:05 tarihinde minhtruong315 <notifications@github.com>
şunu yazdı:

**Comment by roseyazilim** [comment]
Hello 
I sent mail again
thanks

**Comment by minhtruong315** [comment]
@roseyazilim can u help me change English language for the admin?
Thanks

**Comment by roseyazilim** [comment]
okey i did english

**Comment by minhtruong315** [comment]
@roseyazilim can I delete these  extensions? maybe it is cause to throw error for api
<img width="1625" alt="Screen Shot 2020-06-23 at 4 20 20 PM" src="https://user-images.githubusercontent.com/10402500/85386173-7491db00-b56d-11ea-95ee-d93ac1c49367.png">

**Comment by roseyazilim** [comment]
I use those extensions for seo and for currency update. you can delete to test

**Comment by minhtruong315** [comment]
Hi @roseyazilim This api doesn't response data json
```https://istedigimburada.com/index.php?route=extension/mstore/category```
<img width="1429" alt="Screen Shot 2020-06-23 at 17 04 10" src="https://user-images.githubusercontent.com/10402500/85393411-271a6b80-b577-11ea-843d-7d5df2782aea.png">

This issue is due to the server setting that we could not find out the root cause so far, please help to contact your hosting provider or the admin website to check to see if it is caused by the caching.

**Comment by roseyazilim** [comment]
![image](https://user-images.githubusercontent.com/53063121/85393895-6ab0ad80-b556-11ea-8c3a-4b7b5bab58bc.png)

what could be the reason some chronic problem occurred

**Comment by minhtruong315** [comment]
I dont know. can you try to install a website from original source code of opencart. and only install mstore extension then try again this link
https://istedigimburada.com/index.php?route=extension/mstore/category
Our mstore extension is working well on original source code opencart.

**Comment by roseyazilim** [comment]
![image](https://user-images.githubusercontent.com/53063121/85394185-db57ca00-b556-11ea-94a1-a042fdd70a8a.png)
it is working now

@minhtruong315

**Comment by roseyazilim** [comment]
![image](https://user-images.githubusercontent.com/53063121/85394245-f9252f00-b556-11ea-8981-3830da00d398.png)
Thank you man 

my problem is solved

**Comment by minhtruong315** [comment]
great. How do you fix that?

**Comment by roseyazilim** [comment]
maintenance mode remained on, it kept receiving data when it turned off

**Comment by minhtruong315** [comment]
ok. if you have any issues. please create other ticket.

**Comment by roseyazilim** [comment]
Hello,
I cannot register in the application, it gives an error. can you help me?

SectorN Tech <notifications@github.com>, 25 Haz 2020 Per, 10:06 tarihinde
şunu yazdı:

**Comment by KhanJahanzaib** [comment]
Yes
