### ISSUE TITLE
Hi,

### ISSUE THREAD

**Issue by investisocial** [inspireui/support#3803]
From 3730

Hi,
I've got a problem with store information on the product page.
If you check the attached screenshot, you can see an issue with vendor information. There isn't a logo store and then if you click on the vendor profile, you will get a different vendor page where the header is not correct. It only seems an image error, because products and vendor information are correctly shown. If I go into the store's tab I correctly see vendor's profiles. This issue occurred only on the product page. Can you help me, please?

Thank you so much for your time 😊
Regards
Carlo

**Comment by minhcasi** [comment]
@investisocial - try to update to latest release `1.7.5` to fix these issue - thank you!

**Comment by investisocial** [comment]
yes, I have checked the new release and there is the same issue.
How can i solve it? Help me, please.
Regards.
Carlo

**Comment by minhcasi** [comment]
@philipvu30 - pls help with investigating

**Comment by investisocial** [comment]
I think that one of the problems is in the store_detail_screen.dart file.
For the store banner there is a bad link to an incorrect image:

Widget build(BuildContext context) {
    final bannerUrl = widget.store.banner != null
        ? widget.store.banner
        : "https://media.istockphoto.com/photos/vintage-retro-grungy-background-design-and-pattern-texture-picture-id656453072?k=6&m=656453072&s=612x612&w=0&h=4TW6UwMWJrHwF4SiNBwCZfZNJ1jVvkwgz3agbGBihyE=";

Can you check it, please?

**Comment by investisocial** [comment]
Can I use the search field only to search the store's name?

**Comment by investisocial** [comment]
I have another issue always with store's page:
I have a store with only 6 products but if I visit it, the page is endless and it recharges the same products with an infinite scrolling. Can you help me, please?
Thank you.

**Comment by Carlosdmendoza** [comment]
Same problems here let me know if you got any update on that please

**Comment by philipvu30** [comment]
Hi @investisocial @Carlosdmendoza ,

The endless scrolling does not happen on the latest version **release pre-1.7.6**. Please consider updating your app via our GitLab repository.
Banner/Logo issue -> Please replace this [vendor folder](https://github.com/inspireui/support/files/4824522/vendor.zip) in lib/vendor

Thank you.

**Comment by philipvu30** [comment]
> Can I use the search field only to search the store's name?

Sorry, you can't.

**Comment by investisocial** [comment]
@philipvu30 Thank you, banner/logo problem is solved!
Where can I get the last 1.7.6 version to fix endless scrolling?
Regards

**Comment by investisocial** [comment]
I hope you can help me please please..
I've found in /lib/screens/cart/my_cart.dart file a rule that checks the total cart amount and blocks the order if it is different by a minimum value. It shows a red alert message too. 
Great!
Help me..
How can I do the same thing but for the vendor's ID?
I need the same rule but it must check the Vendor's ID. I have to change 'minAllowTotalCartValue' with 'IDvendor'.
If just only one Vendor's ID is different it must block the order showing a red alert message like "You cannot order products from different stores".
Can you help me? Please..
![Cart_Vendor_Block](https://user-images.githubusercontent.com/57216890/85615334-5e167d00-b65c-11ea-8750-b818732a8596.jpg)

Thank you for your attention.
Regards
Carlo

**Comment by investisocial** [comment]
Hi,
Apple doesn't approve my app release because of an error when I click on a store.
In fact, if I click on a store to see its products, it doesn't work and newly redirects me to the home screen.
Can you help me, please?
The testing device is an iPad pro-12.9-inch 4th generation.
It's very important.
Thank you.
Regards
<img width="1680" alt="IpadPro_Stores_Issue" src="https://user-images.githubusercontent.com/57216890/85713736-f6a70e80-b6e9-11ea-923a-af319559847a.png">

**Comment by philipvu30** [comment]
Hi,

Follow these steps:
1. In lib/models/cart/cart_model_woo.dart add this line
![image](https://user-images.githubusercontent.com/54442328/85838236-78b73600-b7c3-11ea-987e-ac5e602ff1af.png)

2. Add this code under **if(isLoading) return;**

```
    bool isMatch = true;
    var fistStoreName = '';
    var checkStoreName = '';
    model.item.forEach((key, value) {
      checkStoreName = value.store.name;
      if (fistStoreName.isNotEmpty && isMatch) {
        if (fistStoreName != checkStoreName) {
          isMatch = false;
        }
      }
      print('$fistStoreName  --  $checkStoreName');
      fistStoreName = checkStoreName;
    });

    if (!isMatch) {
      showFlash(
        context: context,
        duration: Duration(seconds: 3),
        builder: (context, controller) {
          return SafeArea(
            child: Flash(
              borderRadius: BorderRadius.circular(3.0),
              backgroundColor: Theme.of(context).errorColor,
              controller: controller,
              style: FlashStyle.grounded,
              position: FlashPosition.top,
              horizontalDismissDirection: HorizontalDismissDirection.horizontal,
              child: FlashBar(
                icon: Icon(
                  Icons.check,
                  color: Colors.white,
                ),
                message: Text(
                  'Different store id',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 18.0,
                    fontWeight: FontWeight.w700,
                  ),
                ),
              ),
            ),
          );
        },
      );
      return;
    }

```

**Comment by investisocial** [comment]
Hi,
thank you for your reply.
I've tried it but it doesn't work.
I don't find "if(isLoading) return" value into my file.
I've attached it. Please, can you directly modify it?
You are an Hero! 
Thank you thank you..
Regards
Carlo
[cart_model_woo.zip](https://github.com/inspireui/support/files/4836320/cart_model_woo.zip)

**Comment by philipvu30** [comment]
https://github.com/inspireui/support/issues/3803#issuecomment-649002407

It's in this image you sent me.

**Comment by investisocial** [comment]
Ok but that is another file. You told me to put this code into the "cart_model_woo.dart" file.
In my photo, there is "my_cart.dart" file, available to this path: /lib/screens/cart/my_cart.dart.
So have I to put your code into my_cart.dart file?
Thanks

**Comment by philipvu30** [comment]
Hi,

There are 2 files you need to put code in.
1. Is the file I mentioned.
2. Is the file in the image you sent me.

**Comment by investisocial** [comment]
It perfectly works!!
You are number one friend :)
I only need to solve the endless product page too.
Thank you

**Comment by philipvu30** [comment]
Hi,

I don't know which file should I send you as I'm not the one who fixed it. Maybe this [folder](https://github.com/inspireui/support/files/4843499/vendor.zip) will help.

**Comment by investisocial** [comment]
> I have another issue always with store's page:
> I have a store with only 6 products but if I visit it, the page is endless and it recharges the same products with an infinite scrolling. Can you help me, please?
> Thank you.

I still have the same problem, how can I fix it please?

**Comment by investisocial** [comment]
Can you help me with this please?
![Request_29 06](https://user-images.githubusercontent.com/57216890/86004162-28ceae00-ba13-11ea-8279-bc5f5c25d7b2.jpg)

**Comment by investisocial** [comment]
is there anyone?

**Comment by minhcasi** [comment]
@investisocial - pls download the latest code from gitlab to fix the white space issue - thanks

**Comment by investisocial** [comment]
> @investisocial - per favore scarica l'ultimo codice da gitlab per risolvere il problema degli spazi bianchi - grazie

Ok thanks, and what about endless scrolling into the vendor's shop page?

**Comment by investisocial** [comment]
> @investisocial - per favore scarica l'ultimo codice da gitlab per risolvere il problema degli spazi bianchi - grazie

where can i download it?

**Comment by Carlosdmendoza** [comment]
I need acces to the latest version as well where may I update it? Do you
have a link or something for it?

**Comment by philipvu30** [comment]
Hi @investisocial @Carlosdmendoza ,

Please send me an email with the title: [Access Request] - **The name of the product you purchased** to this email: toan@inspireui.com.
I'll send a request to the sender's email.

Thank you.

**Comment by philipvu30** [comment]
> > @investisocial - per favore scarica l'ultimo codice da gitlab per risolvere il problema degli spazi bianchi - grazie
> 
> Ok thanks, and what about endless scrolling into the vendor's shop page?

It has already been fixed in the latest version.

**Comment by Carlosdmendoza** [comment]
Hi I have sent the request already do you have any manual on how to update
it?

**Comment by philipvu30** [comment]
Hi @Carlosdmendoza ,

We've already sent you the access link via your email. Please have a check.
For updating the app, please have a look at this article [https://medium.com/@inspireui/how-to-upgrade-fluxstore-projects-by-using-git-cebde7489ea6](https://medium.com/@inspireui/how-to-upgrade-fluxstore-projects-by-using-git-cebde7489ea6)

**Comment by investisocial** [comment]
@philipvu30 I don't have the access to gitlab. Can you give me it, please? Thank you..

**Comment by Carlosdmendoza** [comment]
Great thank you!
