### ISSUE TITLE
Struggling to edit the drawer section

### ISSUE THREAD

**Issue by dcb-online** [inspireui/support#3804]
Good day @minhtruong315 

I am finding it very difficult to edit the drawer section. Can you perhaps assist me on adding a Title to the drawer section as well as move the login/logout list item to the bottom?

![Screenshot_1](https://user-images.githubusercontent.com/66263315/85130771-d8e33080-b235-11ea-8948-dfe9d34c2e4b.png)

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@dcb-online - you could try to move it by using Fluxbuilder app - http://fluxbuilder.com/

or customize `lib/menu.dart`

**Comment by dcb-online** [comment]
Hi @minhcasi 
Thank you for the response.
I am aware that you can enable or disable the login, blog, and shop wording.

However, I would like to move the entire section to below Category. I have attached my menu.dat file coding if you can perhaps point me to where I should edit if possible?

[menu.dat.txt](https://github.com/inspireui/support/files/4804615/menu.dat.txt)

**Comment by minhcasi** [comment]
@dcb-online - would you mind to custom this setting via Fluxbuilder tool - http://fluxbuilder.com/ - it's allowed to config the menu position by drag and drop on fluxbuilder on latest release - then you only need to copy and update the config_en json

**Comment by minhcasi** [comment]
Let us know if you have any question - thank you!

**Comment by dcb-online** [comment]
Hi @minhcasi thank you for the response. I have tried however still unsuccessful. What I would like to achieve is moving the login tab to below "By Categories". I have tried doing this in the code but I was unsuccesfull and on the Fluxbuilder it does not allow me to change the location of this menu. Only the option to enable and disable the "Blog" "Login" tabs.
