### ISSUE TITLE
Internal error 500

### ISSUE THREAD

**Issue by atlasdzedgo** [inspireui/support#3805]
#3566 
site getting error when plugin  Mstore API + JWT Authentication for WP-API  Activate.

our site have WPML + WCFM

We already talk to them. They said their configuration all good.
can you please check the site ?

**Comment by minhcasi** [comment]
@atlasdzedgo - could you share the screenshot of the issue - thank you!

**Comment by atlasdzedgo** [comment]
Check this please
https://pasteboard.co/JdU6oXD.png

**Comment by atlasdzedgo** [comment]
Please check this.. I hope for this we get internal error
https://pasteboard.co/Je0G6i1.png

Please tell me how can i solve it ?

**Comment by minhcasi** [comment]
@minhtruong315 - pls help to investigate this issue

**Comment by atlasdzedgo** [comment]
I hope this will help you..Check this attached
https://pasteboard.co/Je5ELYi.png

**Comment by minhcasi** [comment]
@minhtruong315

**Comment by minhtruong315** [comment]
@atlasdzedgo can u send me admin info account via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/3805
Thanks

**Comment by atlasdzedgo** [comment]
Sent...Check please mail

**Comment by minhtruong315** [comment]
Hi @atlasdzedgo what do you need me to support now? I see your website is working well.
https://testatlas.dzedgo.com/ar/

**Comment by atlasdzedgo** [comment]
Hey this is the test site.. here is uploaded our site old back up before installing their APi plugins when there was no internal error
https://testatlas.dzedgo.com/

So our test site, you will not find any internal error.

I already mentioned in the mail about our main site https://atlas.dzedgo.com
When It seems that as soon as Mstore API is installed that is when the error returns. So It's may be plugin api issue

so please check this site https://atlas.dzedgo.com

**Comment by atlasdzedgo** [comment]
Hey this is the test site.. here is uploaded our site old back up before installing their APi plugins when there was no internal error
https://testatlas.dzedgo.com/

So our test site, you will not find any internal error.

I already mentioned in the mail about our main site https://atlas.dzedgo.com Please check all version like https://atlas.dzedgo.com/fr/ https://atlas.dzedgo.com/ar/  and check random pages
 As I already sent you wp-admin.. So please check it from wp-admin
When It seems that as soon as Mstore API is installed that is when the error returns. So It's may be plugin api issue

so please check this site https://atlas.dzedgo.com

**Comment by minhtruong315** [comment]
Hi @atlasdzedgo I see this website is working well
https://atlas.dzedgo.com
what is wrong?

**Comment by atlasdzedgo** [comment]
Check this 
https://drive.google.com/file/d/1Bxgee4iKR48zDDRw1gAvd0CbfbkcF2xK/view?usp=sharing

**Comment by minhtruong315** [comment]
@atlasdzedgo pls accept the permission. thanks

**Comment by atlasdzedgo** [comment]
ok

**Comment by minhtruong315** [comment]
Hi @atlasdzedgo I fixed MStore Api plugin, it doesn't error database. But  Internal Server Error still shows although I deleted MStore Api plugin

**Comment by atlasdzedgo** [comment]
please reinstall it..

**Comment by minhtruong315** [comment]
installed

**Comment by atlasdzedgo** [comment]
I want to delete again let's see.

can you please tell if i see database error then how can i fix it ?

**Comment by atlasdzedgo** [comment]
Hello..

Please Check this site . I told you about the test site
https://testatlas.dzedgo.com/

I just install mstore api plugin and site shows Internal error . even after deleting the plugin it shows internal error

So I am going to import fresh back up again. because this back up has never been installed store plugin
so please 5 minutes later Please check the https://testatlas.dzedgo.com/wp-admin and install mstore plugin

**Comment by minhtruong315** [comment]
Hi @atlasdzedgo if you dont install mstore api plugin, your website is working well. right?

**Comment by atlasdzedgo** [comment]
Yes! But once we install it and even we delete it the error still occur

**Comment by minhtruong315** [comment]
Hi @atlasdzedgo I installed MStore Api plugin on your test site. it's working well. So I think that the cause is not MStore Api plugin on your production site.

**Comment by atlasdzedgo** [comment]
how could you say that ?
https://testatlas.dzedgo.com/ar/

https://testatlas.dzedgo.com

I still get error...Please check it..

**Comment by atlasdzedgo** [comment]
how could you say that ?
https://testatlas.dzedgo.com/ar/

https://testatlas.dzedgo.com

I still get error...Please check it....

I think you only click it for once..

Please check it in random pages.. like https://testatlas.dzedgo.com/ then https://testatlas.dzedgo.com/fr/ then https://testatlas.dzedgo.com/ar/

**Comment by atlasdzedgo** [comment]
# Firstly Please Check this video

https://drive.google.com/file/d/1IZ2TelnueUBDJupVpXLhov1_-SfwrB7e/view?usp=sharing

As I reinstalled it for making video and again I deactivate it but error are still exists even after deleting it , That's why I again Uploaded fresh back up. so please follow my video. And please check the front-end first then upload mstore api  then check random pages.

Now fresh site uploaded. so there is no error. So please check video first and then installed



# now upload the plugin
# then perform action

Please check it in random pages.. like https://testatlas.dzedgo.com/ then https://testatlas.dzedgo.com/fr/ then https://testatlas.dzedgo.com/ar/

 still get error...Please check it for random pages with Language switching

**Comment by minhtruong315** [comment]
@atlasdzedgo pls accept the permission so that I can see the video

**Comment by atlasdzedgo** [comment]
ok

**Comment by minhtruong315** [comment]
@atlasdzedgo Do you see any error logs on your hosting?

**Comment by atlasdzedgo** [comment]
No sir..no error log there.

I already talk to them 5 times for checking error log...But they said no error log.

Also I have checked in my file manager error log with debugging, but there is no error

may be can you please take the back up site and try to check it your own server. ,may be you find error log.
I can send you All in one wp migration back up file

**Comment by minhtruong315** [comment]
Hi @atlasdzedgo please check this video.
https://www.dropbox.com/s/sveauvx1ktlk9zc/error.mov?dl=0
MStore Api plugin doesn't install on your website, but it still throws error

**Comment by atlasdzedgo** [comment]
If you have just installed it and than deleted it the error with remain! But I will let my colleague upload a fresh backup without Mstore API installed ever and you will see that there is no error

**Comment by minhtruong315** [comment]
ok. let me know when you uploaded
Thanks

**Comment by atlasdzedgo** [comment]
Sure will do

**Comment by atlasdzedgo** [comment]
Fresh back up uploaded>> https://testatlas.dzedgo.com/   There is no error Now

And Also There is a fresh back up Uploaded. ALL in one wp Migration > backups > download it ( check the screenshot )
https://pasteboard.co/JeFLgh2.png

So you can download it and test it to your server. Please Download it & Import it Test it to your server.
if you need ALL In one premium extension plugin..let me Know

**Comment by atlasdzedgo** [comment]
@minhtruong315 hello guy, I hope you had a great weekend! 
Any updates on the issue please.
Thank you

**Comment by minhtruong315** [comment]
Hi @atlasdzedgo I downloaded the backup on your website and import in my website in localhost, but it doesn't work.

**Comment by atlasdzedgo** [comment]
can you please send me screenshot ?
I think you should upload it live server..

Or may be I can give you FTP server access. so you can download it ?

**Comment by minhtruong315** [comment]
<img width="1644" alt="Screen Shot 2020-06-30 at 9 14 30 AM" src="https://user-images.githubusercontent.com/10402500/86075410-21121680-bab2-11ea-94a2-c0330fb8682c.png">
it shows this error when disable coming soon

**Comment by atlasdzedgo** [comment]
Hi, Thanks

Please use live server. Send me admin access I will upload back up if you want

I hope in Live server, there will be no error. Because We already tested it

**Comment by atlasdzedgo** [comment]
@minhtruong315 @minhcasi hello guy! 
We hope you are doing well? 
The issue is caused by Mstore API.
We have lost time and money as well because we switched from dokan to WCFM because we though that’s dokan problem, but now it’s very clear that your plugin cause the error, as you have seen in the video we sent you! 
We already wasted lot of time switching multi vendors solution, investigating the issue and we are behind deadlines to launch our solution.
Looking forward to your reply
Thank you

**Comment by minhtruong315** [comment]
Hi @atlasdzedgo if I use live server. I can't debug to find the issue. I will try to install in localhost again,

**Comment by atlasdzedgo** [comment]
hi, I am really not aware why localhost showing error ? May be you can replace WordPress core files manually before Disable Maintenance mode. may be it can solve the issue.

And I create new export file. This is new generate now. Can you please try to download and import this file ?  Check the screenshot.. https://pasteboard.co/JfBF6aV.png

And Also I have uploaded backUp to another server, I see there is some error logs when site showing internal error. Could you please check the screenshot ? https://pasteboard.co/JfBFgVc.png

**Comment by minhtruong315** [comment]
let me download and install new backup.

**Comment by atlasdzedgo** [comment]
@minhtruong315 good morning! 
Any updates please? 
Thank you

**Comment by atlasdzedgo** [comment]
Hello @minhtruong315
any updates ?

**Comment by minhtruong315** [comment]
Hi @atlasdzedgo I haven't found the cause for breaking the database yet. maybe it's conflict with any plugins.

**Comment by atlasdzedgo** [comment]
We have a fix but it's really not what we wanted, but we can live with it for now! Thank you for your support really appreciate it 🙌
