### ISSUE TITLE
Login& create error 

### ISSUE THREAD

**Issue by unaluslusoy** [inspireui/support#3806]
The e-commerce application I use is opencart.
The user gives the error that appears on the screen on the login screen and registration screen.
+ Detail Issues: 
+ Product & version: Fluxstore Pro 1.7.5
+ Flutter (or React Native) version: 1.4.17
+ Testing Device/Simulator: Android 10+
+ Screenshot issues (drag the file to attach here): 
https://prnt.sc/t2qrnz
#Ticket-ID #2506

**Comment by minhcasi** [comment]
@unaluslusoy - could you try to debug the Android Studio to see if there is a detailed error from the server-side after finish the sign-in? - thank you!

**Comment by unaluslusoy** [comment]
@minhcasi - I solved the user login problem. It had to be the same language code used in Opencart. When user logs in, I get debug error on the screen. Please inform me.

https://prnt.sc/t3xmew

**Comment by minhcasi** [comment]
@unaluslusoy - could you check if the login password or the email login is correct?

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
