### ISSUE TITLE
adding payments methods

### ISSUE THREAD

**Issue by miskayapp** [inspireui/support#3809]
![pay1](https://user-images.githubusercontent.com/64660378/85153191-cbd23b80-b24d-11ea-9a8e-0745cb9f33f4.PNG)
![pay2](https://user-images.githubusercontent.com/64660378/85153195-cd9bff00-b24d-11ea-8ec9-a89228efe853.PNG)

your tutorial video shows only PayPal and razor, but we don't use those two in my country, i try editing the payment.dart and adding the secret  key but the "paypalconfig" looks connected some other file.

**Comment by miskayapp** [comment]
i need to add those two payment gateway

**Comment by minhcasi** [comment]
Try to enable one of these options to support multi-payment gateway via Webview.

<img width="685" alt="Screen Shot 2020-06-20 at 10 43 45" src="https://user-images.githubusercontent.com/1459805/85190463-eb677380-b2e2-11ea-8d3d-3287b407ca2f.png">

Or you could customize your own native payment gateway - thanks

**Comment by miskayapp** [comment]
the "enableonepagecheckout" when i add a coupoun, it dosent work when the woocomerce checkout page comes up thats why i want to use the natice.

**Comment by miskayapp** [comment]
i enabled nativeone but paypal dont work in my country just paystack and flutterwave, thats why i'm asking if i can integrate like you did paypal
