### ISSUE TITLE
Magento 2, Payment, Shipmint & Language problems

### ISSUE THREAD

**Issue by xsamir** [inspireui/support#3810]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
1- The **shipping fees** is (0) and didn't get the actual price of shipping!
     I'm using (Marketplace table rate shipping by Webkul)

2- Doesn't show the **payment methods** , which usually using WebView.

3- The English version working fine, but the Arabic version **doesn't show anything** (no data at all)

+ Product & version: FluxStore Pro (Magento 2.3.2)
+ Flutter (or React Native) version: 1.17.3 
+ Testing Device/Simulator: Nexus Android 9.0
+ Screenshot issues (drag the file to attach here): 
![image](https://user-images.githubusercontent.com/7432001/85163353-c25bca00-b273-11ea-98cb-d524744e64cb.png)

![image](https://user-images.githubusercontent.com/7432001/85163256-a0624780-b273-11ea-97f4-e1af08a0e0d1.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@xsamir - pls give your new comment to #3768

**Comment by xsamir** [comment]
Kindly reminder

**Comment by minhcasi** [comment]
@xsamir - as per our checking, the table rate from Webkul is not compatible with the current Fluxstore, could you able to customize this feature by your own?

**Comment by xsamir** [comment]
Ok, I will start digging for the solution.

But what about the second and third problems which there's no relation with Webkul plugin.

Regards,

**Comment by minhtruong315** [comment]
Can you fork from our git repo then invite me: minhtruong315@gmail.com? https://medium.com/@inspireui/how-to-upgrade-fluxstore-projects-by-using-git-cebde7489ea6 
I will help you check your issues 
Thanks

**Comment by minhtruong315** [comment]
Hi @xsamir how?

**Comment by xsamir** [comment]
Hi, I will upload the project to Gitlab within today.
Sorry for delay, it was our weekend.

**Comment by minhtruong315** [comment]
Hi @xsamir ping me when you uploaded.
Thanks

**Comment by xsamir** [comment]
Thank you,
I think it's better to close the ticket because I'm working now on a new Magento website without Webkul which will take up to a week.

Regards.
