### ISSUE TITLE
Wordpress Multisite Ecommerce

### ISSUE THREAD

**Issue by AddyaTechnologies** [inspireui/support#3811]
Hello
I have 2 offline store, i am making a website to list all products and sell online
Those 2 store will full fil order from their respective geography only and not to PAN India
So to handle this, once a user comes to my site i ask them Do you live in Area 1 or Area 2
Based on their selection i take them to that site ( Multisite option in wordpress )
So url is
sitename.com ( User lands )
sitename.com/Area1 is for Area 1
sitename.com/Area2 for Area 2
Product database is same, just the Inventory count varies in These 2 stores
How can i handle this with MStore ?
I have already purchased this, so kindly let me know how to make this work

+ Product & version: Mstore App
+ Flutter (or React Native) version: Latest Download
+ Testing Device/Simulator:  NA
+ Screenshot issues (drag the file to attach here):  NA

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
@AddyaTechnologies - could i check if you have interated with the Mstore mobile app already, basically if you are using the same core WooCommerce for sitename.com which id loaded form the same database, the Rest API will be the same and you could use to load multi areas 

We have not tested on this integration but it could work fine.
