### ISSUE TITLE
App rejected from PlayStore

### ISSUE THREAD

**Issue by netuseruk** [inspireui/support#3812]
Hello Author,
My app rejected from PlayStore , they mailed us as followed 
![image](https://user-images.githubusercontent.com/66378474/85175198-943ab200-b294-11ea-8907-77dbc65014e8.png)

Also attached one screenshot as followed 

![image](https://user-images.githubusercontent.com/66378474/85175332-d06e1280-b294-11ea-924a-34941ef2bc64.png)

Please help me on that .

**Comment by netuseruk** [comment]
Note : I build this app using FluxBuilder and disabled Language, Currencies, Dark Theme but here in screenshot all the option visible .

**Comment by minhcasi** [comment]
@netuseruk - could you share the screenshot report from Google?

<img width="668" alt="Screen Shot 2020-06-20 at 10 47 47" src="https://user-images.githubusercontent.com/1459805/85190537-7c3e4f00-b2e3-11ea-94c9-743fba4e47fa.png">

**Comment by netuseruk** [comment]
@minhcasi I already shared , again sharing 
![image](https://user-images.githubusercontent.com/66378474/85193574-89f5d380-b2e7-11ea-9e6e-ac75c9971569.png)
 They attached upper screenshot .

**Comment by amjadalfawal** [comment]
I think they trying to say that your rate app button linked with another app they consider this issue as hidden ad you just have to change the link or remove the button

**Comment by minhcasi** [comment]
@netuseruk - try to change your own bundle ID to point the rating to your own link

<img width="793" alt="Screen Shot 2020-06-20 at 13 48 37" src="https://user-images.githubusercontent.com/1459805/85195440-c1bb4600-b2fc-11ea-996a-07f4b23b8919.png">

**Comment by netuseruk** [comment]
@amjadalfawal thanks for your comment , 
before submitting to Play Console I disabled " Language" , "Currencies" ," Dark Theme" & "Rate the App" from FluxBuilder . 

@minhcasi I have checked and below is the screen shoot , 
 
![image](https://user-images.githubusercontent.com/66378474/85197196-06df7800-b2fd-11ea-867d-aa8dfe31d22a.png)

**Comment by netuseruk** [comment]
@minhcasi I followed every steps from Doc , except I did not create separate key.jks file , I was using default key.jks file . 

Is there any connection for key.jks file ? Is google fetching using SHA key ?

**Comment by netuseruk** [comment]
@minhcasi waiting for your valuable comment !

**Comment by minhcasi** [comment]
@netuseruk - please create your new `key.jks` that match with your bundle id - make sure to store this key for the next version uploading. 

Or you could try to hide the Rating feature at the meantime to pass the reporting error from google

**Comment by netuseruk** [comment]
@minhcasi ok , I am doing these and again submitting to PlayStore . 
I will update you soon .

**Comment by netuseruk** [comment]
@minhcasi Now app successfully published in Play Store . Thanks for your support .

I am facing issue related to Shipping method .

I created 2 type of shipping method 
1. Flat Rate 
2. Free Shipping ( for order value more that 499)

Problem : User can bypass Flat Rate shipping value. Because that option not selected by default .

![image](https://user-images.githubusercontent.com/66378474/85365073-359a6000-b542-11ea-88b2-19b95547a96a.png)

![image](https://user-images.githubusercontent.com/66378474/85365150-5d89c380-b542-11ea-97c0-b1b5301d3a8a.png)

For more than 499 here in displaying two option Flat Rate and Free Shipping but by default it selected free shipping . 

![image](https://user-images.githubusercontent.com/66378474/85365496-1cde7a00-b543-11ea-954d-b76db4f6564e.png)


How can I set default Flat Rate Shipping for all order value <499 .

**Comment by minhcasi** [comment]
Let us know when it goes live - thank you!

**Comment by netuseruk** [comment]
Our app was live from Yesterday night 11:40PM IST
https://play.google.com/store/apps/details?id=com.jogars.ecommerce

Please help me on shipping related issue.

**Comment by minhcasi** [comment]
Hi, congratulation 🎉

You could customize the shipping method minimum amount or customize the code on this file 

<img width="1221" alt="Screen Shot 2020-06-24 at 10 43 00" src="https://user-images.githubusercontent.com/1459805/85497007-7b6d2c00-b607-11ea-9b7d-d21848adeeb8.png">

**Comment by netuseruk** [comment]
Hello @minhcasi , 
I am scaring to customize code , can you please help me to customize code . 

I am using 2 shipping method.

1. Flat rate 
2. Free shipping 

When order value less then or equal 499 , then by default shipping method should be selected as Flat rate 
![image](https://user-images.githubusercontent.com/66378474/85523120-30addd00-b624-11ea-89d4-434f003c2412.png)



For more than 499 there will be only free shipping option , I dont want to show flat rate .

![image](https://user-images.githubusercontent.com/66378474/85523421-9601ce00-b624-11ea-8280-a8192b888c97.png)




2nd Issue 
Unable to login using FB , its giving below error 
![image](https://user-images.githubusercontent.com/66378474/85524017-55568480-b625-11ea-9a77-46e51a66c74f.png)

But from Emulator I can login using FB without any error.

Every time I am getting valuable support from your end  , hoping this time will get too .

**Comment by netuseruk** [comment]
@minhcasi 
Update : I resolved Flat rate related issue & FB login issue

Pending issue : I want to hide Flat rate shipping option when Free Shipping applicable. 
I am trying but unable to do that .

Can you please help me on that . 
Waiting for your valuable solution.

**Comment by minhcasi** [comment]
@netuseruk - pls try your best by adding this logic to the file that I have provided above - thank you!

**Comment by netuseruk** [comment]
@minhcasi I am trying but not able to do it , as you can see I am trying to fix problems by myself some problems able to fix , but this time I am unable to do that. 
I tried to change code in shipping_method.dart file but app crashed so I am scaring to do without your guidance.

I want to hide Flat Rate shipping method when Free Shipping applicable.
Please help me . I would be grateful to you.

**Comment by minhcasi** [comment]
<img width="1389" alt="Screen Shot 2020-06-26 at 16 36 51" src="https://user-images.githubusercontent.com/1459805/85843350-3eea2d80-b7cb-11ea-989d-58816405f4b9.png">

Pls try to override to resolve this feature
[shipping_method.dart.txt](https://github.com/inspireui/support/files/4836163/shipping_method.dart.txt)

**Comment by netuseruk** [comment]
Hello @minhcasi thank you for your quick response . 
Using your mentioned file able to hide flat rate option but unfortunately facing two new issues :

Issue 1

User can bypass shipping method because radio button not selected and by default Flat rate price adding with order , Please see the screenshot.

![image](https://user-images.githubusercontent.com/66378474/85859168-701e2a00-b7da-11ea-90b7-e084384d0a76.png)

Issue 2

If the cart value less then free shipping value , now there is no flat rate option in Shipping method , Please see the screenshot

![image](https://user-images.githubusercontent.com/66378474/85859652-2255f180-b7db-11ea-8eec-0c08ba43f89e.png)

 
Please help me . I would be grateful to you.

**Comment by amjadalfawal** [comment]
![Screenshot_1593179855](https://user-images.githubusercontent.com/37481122/85865295-5a0a6c80-b7ce-11ea-8dc7-b72124fc5373.png)
![Screenshot_1593179861](https://user-images.githubusercontent.com/37481122/85865313-5e368a00-b7ce-11ea-9b05-7b263681ac08.png)

disable shipping from the config  and then make you logic you can get the price of your order from the cartModel
in lib/screens/checkout/payment.dart 

in the initState  you can create an object of your default shipping option so that you can 
in my case i have only free shipping 
![image](https://user-images.githubusercontent.com/37481122/85866104-9094b700-b7cf-11ea-84fe-499f652d9a69.png)
![image](https://user-images.githubusercontent.com/37481122/85866182-b02bdf80-b7cf-11ea-9bee-5d203767ee89.png)



retrieve the payment 
``` ```

**Comment by minhcasi** [comment]
@netuseruk - please try your best with the customization as you got the idea from my example code how to customize that file - thank you!

**Comment by netuseruk** [comment]
@minhcasi thanks for your comment . Ok I am trying to customization.
