### ISSUE TITLE
Recommended image dimension size for Fluxstore WooCommerce

### ISSUE THREAD

**Issue by Iraqimobile** [inspireui/support#3813]
I can't open the provided picture :/ in the guide 
"Setup the Regenerate Image plugin
First, go to Setting/ Media Settings, and setup the image dimension size for the Product Image, this is our recommence setting - https://tppr.me/IbRvL"
Source: https://docs.inspireui.com/fluxstore/woocommerce-setup/

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by Iraqimobile** [comment]
done I uploaded the required files

**Comment by minhcasi** [comment]
Could you help to check the link https://docs.inspireui.com/fluxstore/woocommerce-setup/ and let us know which the section that missing "provided picture "?

**Comment by Shopyloot** [comment]
https://docs.inspireui.com/fluxstore/woocommerce-setup/#setup-the-regenerate-image-plugin

This where the above said file missing. want to know the recommended product image sizes. please check the url you mentioned there which is not working https://tppr.me/IbRvL

thank you
