### ISSUE TITLE
Products don't show on shop page but show on vendor page.

### ISSUE THREAD

**Issue by Benhur3000** [inspireui/support#3815]
- Detail Issues: Hi I'm having a weird issue with the fluxstore mv where the products do not show for the categories product page however they do show up in the vendor store page and in the wishlist if I add. 

- Product & version: 1.7.5

- Flutter (or React Native) version: 1.17.4- stable

- Testing Device/Simulator: emulator 

- Screenshot issues:
![App Categories](https://user-images.githubusercontent.com/67126788/85179832-22844900-b23f-11ea-9829-9931431182dc.PNG)
![App Products loaded](https://user-images.githubusercontent.com/67126788/85179835-231cdf80-b23f-11ea-9ddb-08af021fa036.PNG)
![App Products loading](https://user-images.githubusercontent.com/67126788/85179839-23b57600-b23f-11ea-8c4d-50c2bcd83674.PNG)
![Vendor Page](https://user-images.githubusercontent.com/67126788/85179840-23b57600-b23f-11ea-996d-67c2d50b5764.PNG)

**Comment by minhcasi** [comment]
@philipvu30 - please help with investigating - thank you!

**Comment by philipvu30** [comment]
Hi,

Your issue is already fixed in the release pre-1.7.6. If you have access to our GitLab, please update it.

Thank you.

![image](https://user-images.githubusercontent.com/54442328/85251191-df1a1c80-b482-11ea-99a5-aefda8e4f364.png)

**Comment by Benhur3000** [comment]
Hi is there documentation for updating this through gitlab

**Comment by philipvu30** [comment]
Hi,

Please refer to this [article](https://medium.com/@inspireui/how-to-upgrade-fluxstore-projects-by-using-git-cebde7489ea6).

**Comment by Benhur3000** [comment]
Thank you. Do I have to wait for my request to be accepted before I can
update?

**Comment by Benhur3000** [comment]
Sent request for gitlab but nothing yet.

**Comment by philipvu30** [comment]
Approved.
