### ISSUE TITLE
problem on product variant

### ISSUE THREAD

**Issue by muhalab2010** [inspireui/support#3817]
we have issue on the product variant like this 2 screenshot

we have product dresses and have options size and color for it
this screenshot example for  product we have 1 pcs from this model on our stock with meduim size
on website ok and appear just meduim option for it but on the app appear 2 options medium and large

and large for it finished from store and on the app still customer can order it but we not have

![1](https://user-images.githubusercontent.com/65735249/85187956-e6370400-b2a3-11ea-8138-b2596962186f.png)
![2](https://user-images.githubusercontent.com/65735249/85187957-e7683100-b2a3-11ea-8a9f-e8a87dd29003.png)

how we can resolve it

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one with full information - thank you for your time!
