### ISSUE TITLE
New payment gateway (FLUXSTORE MV)

### ISSUE THREAD

**Issue by yassiney120** [inspireui/support#3818]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
Hello , it's possible to integrate new payment gateway  
Tap.company

https://pub.dev/packages/go_sell_sdk_flutter

+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

#3725

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@yassiney120 - I'm not sure on `go_sell_sdk_flutter` library, this is kind of out of our understand and support scope - feel free to customize this library base on your business 👍

**Comment by yassiney120** [comment]
Hello thank you for your answer please do you have any extras service for customization
