### ISSUE TITLE
[MStore Pro] Contact US ID 

### ISSUE THREAD

**Issue by yosefasad** [inspireui/support#382]
1.   How to get the contact_us ID in the config.js ?   CustomPages: { contact_id: 10941 },?

2.  What is the difference Between "contact us" and other pages such About and Privacy? 

3.   in the left Menu, when I click on "Contact Us" , then click on "About", 
the "About" page is not shown up , 
Please see the video https://youtu.be/z-MW2ywz3DU
How to solve thi? 
Regards

**Comment by luyx2412** [comment]
Hi @yosefasad Can you give me your version MStore Pro?

Thanks

**Comment by yosefasad** [comment]
it is the latest version,    3.7.0 

Thanks
