### ISSUE TITLE
Android studio not rendering Fluxstore MV 1.7.5

### ISSUE THREAD

**Issue by goelrajiv75** [inspireui/support#3820]
Could not determine the dependencies of task ':app_settings:compileDebugAidl'
+ Detail Issues: 
* What went wrong:
Could not determine the dependencies of task ':app_settings:compileDebugAidl'.
> Failed to find Platform SDK with path: platforms;android-R

C:\src\FluxStore-vendor-1.7.5\source>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.4, on Microsoft Windows [Version 10.0.18362.836], locale en-IN)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[√] Android Studio (version 4.0)
[√] VS Code (version 1.46.1)
[√] Connected device (1 available)

• No issues found!

+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@goelrajiv75 - pls try to clean cache to fix the issue - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

**Comment by goelrajiv75** [comment]
I have done everything, even clean installation step by step as your video, but problem remains same.

**Comment by minhcasi** [comment]
@goelrajiv75 - could i check if you could run this example - https://flutter.dev/docs/get-started/test-drive?tab=vscode ?

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Comment by goelrajiv75** [comment]
Thanks actually everytging is working now.
