### ISSUE TITLE
product variant issue

### ISSUE THREAD

**Issue by muhalab2010** [inspireui/support#3822]
hey

we have store for  clothes so we use vaiable like size and color
we have issue on the app like this product :

we have from this product just 1 pcs on the store with meduim size 
on website working ok
on the app appear meduim size and large size ( this size out of stock)
and also customer can order the large size and we already this size out of stock

how we can resolve this problem
 
![1](https://user-images.githubusercontent.com/65735249/85199797-8ddb2300-b2f2-11ea-9bf7-8ce2d1529aa6.png)
![2](https://user-images.githubusercontent.com/65735249/85199798-8e73b980-b2f2-11ea-91cd-04d74cbd980f.png)

we use woocomerse and fluxstore pro last version

**Comment by ameenbadri7** [comment]
you have to config the fluxstore as the following:
go to `lib\common\config\products.dart` and then config your attributes copy them from your woocommerce attributes `wp-admin/edit.php?post_type=product&page=product_attributes`
as the following: 

```
const ProductVariantLayout = {
  "color": "color",
  "size": "option",
};
```
and also 

```
const kProductVariantLanguage = {
  "en": {
    "color": "Color",
    "size": "Size",
   },
  "ar": {
    "color": "لون",
    "size": "بحجم",
  },
};

```
and make sure you have a product with those attributes and also your woocommerce Terms are well configured.


[follow this to guide you ](https://docs.inspireui.com/fluxstore/customization/#6-dynamic-product-variant 
)

**Comment by muhalab2010** [comment]
yes we do this and same problem  on all items have variables
show all vriables and also when any variable its out of stock still working on app and customer can order it

![3](https://user-images.githubusercontent.com/65735249/85213721-5efc9580-b362-11ea-81cd-caaa7c5e8475.png)

this from website

and this products.dart
/**
 * Everything Config about the Product Setting
 */

/// The product variant config
const ProductVariantLayout = {
  "color": "color",
  "size": "box",
  "model": "option",
};

/// use to config the product image height for the product detail
/// height=(percent * width-screen)
/// isHero: support hero animate
const kProductDetail = {
  "height": 0.5,
  "marginTop": 0,
  "isHero": false,
  "safeArea": false,
  "showVideo": true,
  "showThumbnailAtLeast": 3,
  "layout": "simpleType",
  "enableReview": true,
};

const kCartDetail = {
  "minAllowTotalCartValue": 1,
  "maxAllowQuantity": 1000,
};

const kProductVariantLanguage = {
  "en": {
    "color": "Color",
    "size": "Size",
    "model": "model",
  },
  "ar": {"color": "اللون", "size": "المقاس", "model": "الموديل"},
  "vi": {
    "color": "Màu",
    "size": "Kích thước",
    "model": "Chiều Cao",
  },
};

/// Exclude this categories from the list
const kExcludedCategory = 311;

**Comment by ameenbadri7** [comment]
If you have more than english language you should try to use wmpl 

https://docs.inspireui.com/fluxstore/multi-language/

**Comment by muhalab2010** [comment]
i use on website and on app just arabic language and the problem on stock and variable not updated just copy the attribute and stock number working on all attrubiete and not reconized it you understand me

**Comment by minhcasi** [comment]
@muhalab2010 - I'm sorry to close this ticket as you could not send the proof of purchase code - thank for you time
