### ISSUE TITLE
i have issue with mollie and ideal payment gateway

### ISSUE THREAD

**Issue by mohamadrw** [inspireui/support#3823]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: i used this plugin 
https://ar.wordpress.org/plugins/mollie-payments-for-woocommerce/

and i had error when i tried to make payment
as this video 

I know that you support electronic payment as webview
But as you can see in the video, it cannot
the app doesn't allow another intent to be open

+ Product & version:
+ Flutter (or React Native) version:  1.7.5
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 
![image](https://user-images.githubusercontent.com/53875618/85199935-0beff780-b2fc-11ea-90a8-ff7210cfd719.png)

https://www.youtube.com/watch?v=Sk0Oq8JToNA

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by philipvu30** [comment]
Hi,

I watched your video but its title is Paypal and Mollie but you choose Ideal instead. But here the issue's title is Mollie and Ideal so I don't know what is your actual problems here.

1. Paypal issue: 
- Make sure the Paypal Payment setting is the same as the configuration in the app (lib/common/config/payments.dart). If it is set as live, in the payments.dart file you have to change the production for PaypalConfig from false to true and vice-versa for SandBox.
2. Mollie issue:
- Tested and no issue was found.
3. Ideal issue:
- Currently, the FluxStore does not support payment method that requires opening another app.

**Comment by philipvu30** [comment]
Closed as no response in 2 days. 

If you are happy with our services/support, would you mind rating us on your [download page](https://codecanyon.net/downloads)?
We truly appreciate your help.
