### ISSUE TITLE
Issue with the Categorie Cover Pictures

### ISSUE THREAD

**Issue by heftipascal1** [inspireui/support#3824]
Hi, i have follow problem. The Picture of the categorie cover is not showing on the page, but in the backend there is it visible? Show how in the Screenshot

![kategorieen](https://user-images.githubusercontent.com/67189625/85200075-aea47800-b2f4-11ea-98da-c6a2cf957241.JPG)
![detail](https://user-images.githubusercontent.com/67189625/85200076-af3d0e80-b2f4-11ea-91e7-49edc9735145.JPG)

Listeo V1.3.3
You can see it on https://web.oe-gourmet.at

**Comment by ameenbadri7** [comment]
you are using a `wpml plugin` to translate your shop or just the `config.json` file?

**Comment by Carlosdmendoza** [comment]
I have the same problem, but I am using loco translate to translate some of the plugins of my shop.

**Comment by minhcasi** [comment]
@heftipascal1 - pls contact Listeo author to resolve the ticket
