### ISSUE TITLE
Facebook Login

### ISSUE THREAD

**Issue by haidarsalim** [inspireui/support#3826]
FluxNews Version: 1.4.1
Flutter : v1.17.3
Testing Device/Simulator

Having trouble applying YouTube steps to create login with Facebook

      
keytool -exportcert -alias YOUR_RELEASE_KEY_ALIAS -keystore YOUR_RELEASE_KEY_PATH | openssl sha1 -binary | openssl base64

keytool -exportcert -alias key -keystore android\app\certs\key.jks | openssl sha1 -binary | openssl base64

![33333](https://user-images.githubusercontent.com/54249914/85202467-4f079600-b30f-11ea-8754-d427049c22dc.PNG)

**Comment by ameenbadri7** [comment]
the fast way to fix this if you already have key.jks 
download https://keystore-explorer.org/downloads.html and open the key with this software and then it will give you your key hashes everything you need 
sh1 or sha-256 or other stuff.

or you can use the old way 
[this guide ](https://gist.github.com/henriquemenezes/70feb8fff20a19a65346e48786bedb8f
)

**Comment by haidarsalim** [comment]
Having trouble dealing with this I do not have enough experience to know what to do

**Comment by minhcasi** [comment]
@haidarsalim - there is missing PATH link to keytool on your window- pls follow the solution on this link https://stackoverflow.com/questions/6211919/errorkeytool-is-not-recognized-as-an-internal-or-external-command-operable-p

**Comment by haidarsalim** [comment]
I am still facing the same problem

![4444](https://user-images.githubusercontent.com/54249914/85258923-e7695c00-b470-11ea-9e9e-783fdf5c181b.PNG)
![11](https://user-images.githubusercontent.com/54249914/85260716-cb1aee80-b473-11ea-8a1d-bf4f8ff5d163.PNG)

**Comment by haidarsalim** [comment]
Thank you
