### ISSUE TITLE
Issue with isCaching and google Sign in

### ISSUE THREAD

**Issue by chocotacos** [inspireui/support#3827]
Previous Verified Ticket #2996 

1- When i enable is caching to true my recent view, sticky scrolling stops working

When caching is false

![false](https://user-images.githubusercontent.com/55656013/85206255-7d509a00-b33e-11ea-9233-29e4810ab2f5.gif)

When caching is true

![true](https://user-images.githubusercontent.com/55656013/85206275-948f8780-b33e-11ea-9e26-1ed8dd3986bf.gif)

Recently viewed also lost after turning on caching

2- Google signup shows an error

![Screenshot_1592668608](https://user-images.githubusercontent.com/55656013/85206298-b721a080-b33e-11ea-90a6-72f662366c2e.png)

3- How to find SHAI in Android Studio ??????

**Comment by ameenbadri7** [comment]
I just tried now to work with `iscache:true `and everything is fine even the google signup and sign in 
you can use the https://docs.inspireui.com/fluxstore/performance/ to set up app cache 

I am using the lastest fluxstore update and also activating my cache plugin inside the Wordpress plugin and also used the Regenerate Thumbnails and everything is good ...

you can try to this:
clean the old project
update the latest fluxstore activation the plugins and mstore activation also.
and then go to[]( https://www.youtube.com/watch?v=zHtco9_Aw7I) to get your SH-1 and also 
SHA-256. and then try again to use the `iscache:true ` 
it will work.

**Comment by chocotacos** [comment]
@ameenbadri7 i am using 1.7.5 as well i have followed the steps mentioned in the guide everything is running fine as well having the caching speed as well but the product slider isn't working as i have mentioned above it getting stuck as i use "isCaching= true" that's the problem and i am still having it. Help me with this...

**Comment by JaserJsk** [comment]
> I just tried now to work with `iscache:true `and everything is fine even the google signup and sign in
> you can use the https://docs.inspireui.com/fluxstore/performance/ to set up app cache
> 
> I am using the lastest fluxstore update and also activating my cache plugin inside the Wordpress plugin and also used the Regenerate Thumbnails and everything is good ...
> 
> you can try to this:
> clean the old project
> update the latest fluxstore activation the plugins and mstore activation also.
> and then go to https://www.youtube.com/watch?v=zHtco9_Aw7I to get your SH-1 and also
> SHA-256. and then try again to use the `iscache:true `
> it will work.
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/c1f5c35bdee2cf5a71b0e35ef38becdf8ec89d72/68747470733a2f2f646f63732e696e737069726575692e636f6d2f696d616765732f6d6574612f47686f73742d446f63732e6a7067">InspireUI Document**[FluxStore - Universal mobile commerce Flutter app for Magento, WooCommerce and Opencart](https://docs.inspireui.com/fluxstore/performance/)**Fluxstore is universal app that fully integration with the Woocommerce, Mangeto and Opencart


I'm also having this issue - I have followed the steps above but **Google Signin** is showing error when **iscache:true**

In firebase I have set both SH-1 and SHA-256

**Comment by minhcasi** [comment]
@chocotacos - could you check the google login on this link https://github.com/inspireui/support/issues/3151
