### ISSUE TITLE
push notifications

### ISSUE THREAD

**Issue by miskayapp** [inspireui/support#3829]
its not working, on the app its receiving messages in the profile bar, "notify messages" but no badges or push notifications, whats this onesignal, do i need to set anything up agai

**Comment by ameenbadri7** [comment]
setup the `firebase` version it will work 100% I guess they have stopped `onsignal ` because of the API crashes and other stuff.

[use this to guide you](https://docs.inspireui.com/fluxstore/firebase/).

**Comment by miskayapp** [comment]
i did with firebase, i can see the notifications in the app "notify messages" but its not coming as push notifications badges and all

**Comment by ameenbadri7** [comment]
Cloud you please see this video. 

https://m.youtube.com/watch?v=rcJEB-tcLNU

Its working 100%.
Just turn the app off and the badge will show. It will not show if you are inside the app.  
Tell me if its not working please.

**Comment by miskayapp** [comment]
thaank you very much but the onesignal worked for me

**Comment by miskayapp** [comment]
![WhatsApp Image 2020-06-19 at 07 41 54](https://user-images.githubusercontent.com/64660378/85225476-8dfa2200-b3c9-11ea-8218-5c60ed1e76fe.jpeg)
i am still getting this error with apple login

**Comment by trananhchien** [comment]
I also meet this issue. Receiving messages in "notify messages". But dont show badges or push notifications on screen (Android work, but iOS dont work even I quit app)

**Comment by miskayapp** [comment]
Same with me, i just used onesignal, it worked perfect for me.

**Comment by minhcasi** [comment]
@trananhchien @miskayapp - pls help to double-check the guide from https://medium.com/@inspireui/setup-firebase-cloud-messaging-fcm-push-notification-for-flutter-apps-8c767fe64e54 - it is working fine
