### ISSUE TITLE
[BeoNews Pro] ios-heart-empty in CommentIcons not showing correctly on initial unclicked state.

### ISSUE THREAD

**Issue by levi-beers** [inspireui/support#383]
The heart outline isn't showing (on both iOS & Android) on HomeScreen & others. Instead, it shows a placeholder image as shown. I can't seem to figure this one out. 

Initial state
<img width="184" alt="screen shot 2019-03-08 at 1 33 10 pm" src="https://user-images.githubusercontent.com/16378407/54048728-9dd7fd80-41a8-11e9-913e-64bd3270b323.png">

Clicked state
<img width="185" alt="screen shot 2019-03-08 at 1 33 15 pm" src="https://user-images.githubusercontent.com/16378407/54048763-aa5c5600-41a8-11e9-80ce-335067b32586.png">

**Comment by minhcasi** [comment]
It's could be some recent update from the react-native-vector icon as they changed the icon name, noted for checking...
