### ISSUE TITLE
Exception: Gradle task assembleDebug failed with exit code 1

### ISSUE THREAD

**Issue by Arnaldo4ever** [inspireui/support#3830]
Hi, trying to build shopify shop using the flutter run command throws me this error, any solution? 

![terminal](https://user-images.githubusercontent.com/34065498/85213860-a155b080-b329-11ea-87f8-f492e3d739cf.png)

 and this is my common/config
export 'config/advertise.dart';
export 'config/general.dart';
export 'config/onboarding.dart';
export 'config/payments.dart';
export 'config/products.dart';
export 'config/smartchat.dart';

/// Server config demo for Shopify
/// Get more example for Opencart / Magento / Shopify from the example folder
const serverConfig = {
  "type": "shopify",
  "url": "https://el-colmadito-criollo.myshopify.com",

  /// document: https://docs.inspireui.com/fluxstore/woocommerce-setup/
  "accessToken": "95614d60dc46e446968f39d27e0a4a91",

  /// Your website woocommerce. You can remove this line if it same url
  "blog": "",

  /// set blank to use as native screen
  "forgetPassword": ""
};

**Comment by luyx2412** [comment]
Hi @Arnaldo4ever Please follow the document to install the app https://docs.inspireui.com/fluxstore/fluxstore-shopify/

Thanks

**Comment by Arnaldo4ever** [comment]
With app totaly crean i did get same error, i did make this with guide, do u have any update?

**Comment by minhcasi** [comment]
Hi, please go to source/android/gradle/wrapper/ folder, open gradle-wrapper.properties file and change distributionUrl as below:
distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.2-all.zip

Thank you

**Comment by Arnaldo4ever** [comment]
![New Project (6)](https://user-images.githubusercontent.com/34065498/85321489-57d0a700-b48a-11ea-98b0-67ce957d1db4.png)
do u have any version that work for u? can u zip it and send me? because idk why happen this :S i did try in linux and windows with source clean and same error

**Comment by luyx2412** [comment]
Hi @Arnaldo4ever You follow the comment https://github.com/inspireui/support/issues/3830#issuecomment-647355807 and still appear the issues?

Thanks

**Comment by Arnaldo4ever** [comment]
> Hi @Arnaldo4ever You follow the comment [#3830 (comment)](https://github.com/inspireui/support/issues/3830#issuecomment-647355807) and still appear the issues?
> 
> Thanks

yes

**Comment by solarwebbrasil** [comment]
I have the same problem, even with clean code does not work.
My ticket support ID
https://github.com/inspireui/support/issues/3861

**Comment by Arnaldo4ever** [comment]
any last or prev version? or any guide for can fix it? :S

**Comment by luyx2412** [comment]
Hi @Arnaldo4ever Please follow this article to resolve your issue https://github.com/inspireui/support/issues/3708.

Hi @solarwebbrasil Are you try with this article https://github.com/inspireui/support/issues/3708?

Thanks

**Comment by solarwebbrasil** [comment]
> Hi @Arnaldo4ever Please follow this article to resolve your issue #3708.
> 
> Hi @solarwebbrasil Are you try with this article #3708?
> 
> Thanks

Hi @luyx2412 
the change was made and the problem was solved.
Thank you very much.

**Comment by luyx2412** [comment]
You are welcome. 
Closed!
