### ISSUE TITLE
IMAGES NOT DISPLAYING [URGENT SUPPORT]

### ISSUE THREAD

**Issue by Carlosdmendoza** [inspireui/support#3831]
**_Step 1 (require): describe detail issues & screenshots_**
Hi, I have opened three tiickets already for different situations none of them has been resolved by you guys. You take almost 3 days to respond and when you do the only thing you do it's provide  a generalized answer but never a solution. I would reeally need someone who can really help me with this if you can help me through skype so I can make some other inquiries in a most efficient way I would deeply appreciate it. MY issue is the following:
+ Detail Issues: 

I am using FluxStore Vendor 1.7.5 for multivendor stores I have updated all the plugins, isntalled flutter, Get all of the dependencies. Activaed the required plugins on my wordpress site however When I am building my app using the fluxbuilder this is the way how it is supposed to be shown:
![image](https://user-images.githubusercontent.com/46724211/85213817-bf6ae300-b320-11ea-82d5-db0a07a908b9.png)

I have updated the dluxbuilder files in the config_en.json and replaced them to what I had there 
however for some reason when I manage to build the apk which is another problem I had you never helped me to resolve I have tried to install it in 3 different devices and in none of them the app is displaying like that. Se attached pictures please.

Device 1: Samsung SM-J260M
Android Version 8.1.0
It is howing like this 
![WhatsApp Image 2020-06-20 at 5 40 40 PM](https://user-images.githubusercontent.com/46724211/85213870-618acb00-b321-11ea-8ac5-93906b54b0e8.jpeg)

Device 2: Huawuei Y9 2019
Model: JKM-LX3
Andorid Version: 9
Compilation: 9.1.0.282
It is showing thtis way: 
![WhatsApp Image 2020-06-20 at 6 13 06 PM](https://user-images.githubusercontent.com/46724211/85213916-be868100-b321-11ea-9053-6793f82eac51.jpeg)

Device 3: Huawuei P20 Lite 2019
ModelL ANE-LX3
Android version 9
COMPILATION VERSION: 9.1.0.332
is showing this way:
![WhatsApp Image 2020-06-20 at 6 15 57 PM](https://user-images.githubusercontent.com/46724211/85213944-38b70580-b322-11ea-969f-b4acc1b44cc5.jpeg)

Ignore the "play Icon" in the third device.
As you can see in all of them there's issues with the LOGO and in the right side at the bottom it is supposed to be showing the wishlist Icon with a  Heart in it but is not displaying either. It is worth saying that I have noticed that in the first 2 devices the images that are not displaying properly for some reason  are the ones I uploaded manually to the FluxBuilder app because when I am trying to upload them through the website this is happening: 
![image](https://user-images.githubusercontent.com/46724211/85214011-2ab5b480-b323-11ea-9fd2-4cbafb4d3d49.png)

Issue:3 as you can see in the screenshot product images are not displaying pro
I am trying to doccument this as better as  In order to get assistance I have lost more than a week trying to build this app that wasn't cheap tho and didn't expect to have so many problems the only thing I am asking is for better customer service I need you to please give priority to this situation. 
![image](https://user-images.githubusercontent.com/46724211/85214075-c34c3480-b323-11ea-80b7-bc1a791f1041.png)
As you can see all images are displaying from a different size how can I make them to show as them to be the same size in a 1:1 square?

Issue 4: Cattergories images are not displaying over the images I haven't been able to fisc this t all can you help me with that also? 
![image](https://user-images.githubusercontent.com/46724211/85214064-a7489300-b323-11ea-92c6-5b89eb972961.png)

+ Product & version: V1.75 (Latest)
+ Flutter (or React Native) version: v1.17.4
+ Testing Device/Simulator: ?Android Studio V4.0  
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**
The prof of the form that I purchase the product can be found in this other ticket:
#https://github.com/inspireui/support/issues/3727#https://github.com/inspireui/support/issues/3727#issue-638231267

Other ticket created for similar issues #https://github.com/inspireui/support/issues/3727#https://github.com/inspireui/support/issues/3727#issue-638231267

Please Help me with this I have a deadline that I have to cover.

**Comment by minhcasi** [comment]
@vumanhsn97 - please help with investigating - thank you!

**Comment by Carlosdmendoza** [comment]
Please let me know

**Comment by Carlosdmendoza** [comment]
Hi, I am still waiting for someone to help me here.. I would like to add a new request I was able to temporarily fix some of the errors descripted above by uploading the images directly to the website and then refferencing that image in the config.json file.

Question 1: I have a new problem I hope you can help me for some reason the header background image is displaying in the back of some of my products and I don't want that to happen is there any way to keep the header image at the top of the page?  But I still need the with bar with logo menu and search to be sticky any suggestions?

![image](https://user-images.githubusercontent.com/46724211/85243567-6d4cbf00-b3ff-11ea-9e44-ea265d55ed4f.png)

Question 2: Is there any way in which I can show from the home page something like "featured stores" with a direct link to the store I am refferencing

Question 3: Is there any way I can add a filter by cattegory option on the vendors store page? That just shows the cattegories of their stores?

Question 4: Do you have a tutorial or documentation on how to integrate in store payments? At the moment when I am trying to checkout a product it takes me into my website and does not transfers over the cart info to the browser I would like to make the whole process throught the app using native payments please.

Addition I have fixed completely one of the problems I descripted above about the cattegories not showing. But for some reason o the FluxBuilder is still not showing me a preview of the images of my site to choose from for customization and still if I uplioad images from my computer files for some reason they still don't show in some devices as I stated on the previous ticket. I would really appreciate if you can give priority to this situation .

**Comment by Carlosdmendoza** [comment]
Question 5: I don't want to open another ticket just for this how can I make the images to display all of them the same size? I haven't find the way of doing that yet.

**Comment by vumanhsn97** [comment]
@Carlosdmendoza 
Can you send me you config.json(generated from fluxbuilder) and your serverConfig to vumanhsn97@gmail.com?

**Comment by Carlosdmendoza** [comment]
Of course I will do so right now, what woudl the server Config would be?

**Comment by vumanhsn97** [comment]
Look like this https://tppr.me/xQtqW

**Comment by Carlosdmendoza** [comment]
Alrirght  just a moment please I am getting thet right now.

**Comment by Carlosdmendoza** [comment]
I already send it at you to the email provided please let me know if you receive it.

**Comment by vumanhsn97** [comment]
@Carlosdmendoza 
Issue 1: Please run flutter clean before you run your app. If it is not working, Try with load image from assets.
Issue 3: In lib/widgets/product/product_card_view.dart add this line: https://tppr.me/Qkebg
Issue 4: In wordpress site, Open Product > Categories update your category image
Q 1: Update this code: 
[archive.zip](https://github.com/inspireui/support/files/4811326/archive.zip)
Q 2: You need to customize widget
Q 3: You need to customize widget and mstore API
Q 4: Native payment: follow this: https://docs.inspireui.com/fluxstore/multi-payment/
Q 5: Image same size: solve in issue 3

**Comment by miskayapp** [comment]
check  #3792 for fix

**Comment by Carlosdmendoza** [comment]
Thank you for all your support I will try all that and let you know how that goes. Regarding questions number 2 and 3 I understand that this might not be your job to fix because that is something extra that I am requesting. Regarding the widget customization and the Mstore api needed changes is there any way you can provide me with an idea on where to start customizing?
Or on how to do it? I would really appreciate if you do.

**Comment by Carlosdmendoza** [comment]
I haven't tried the payments yet but the documentation should help me with that. On my country none of those payments methods are accepted the only one is paypal but let me ask you am I going to be able to use another payment methods different than  Payment Paypal, Razopay and Tap as long as the payment gateway it's supported by WooCommerce? I just want to make sure about it.

**Comment by miskayapp** [comment]
Yes you can use another payment gateway, just go to payments.dart and set
“enableonepagecheckout” : true

And the “nativeonepagecheckout”:true,

**Comment by miskayapp** [comment]
Regarding 2 & 3 you can change category image from woocomerce, got to
categories and set an image on the category also make use of the
fluxbuilder.

**Comment by Carlosdmendoza** [comment]
Great I appreciate your help almost all of my problems were fixed thanks to your assistance but still I just have two problems still showing up  
![WhatsApp Image 2020-06-22 at 3 41 04 PM](https://user-images.githubusercontent.com/46724211/85338343-55c51300-b49f-11ea-97a7-d8233c3e3612.jpeg)

![WhatsApp Image 2020-06-22 at 3 41 59 PM](https://user-images.githubusercontent.com/46724211/85338363-607fa800-b49f-11ea-9c34-37db88a4e2ae.jpeg)

As you can see the banner image is still displaying in the back of my products 
and doesn;t look right I ahve tried already the solution provided and replaced the files to the ones you provide me on the archives.zip yet the issue remains. 

And about the fluxbuilder I am still having this issue when trying to attachimages from my website,
![image](https://user-images.githubusercontent.com/46724211/85338856-501bfd00-b4a0-11ea-834b-a199c09e8170.png)

Other than that I have no problems if you can help me with that that would be great!

**Comment by vumanhsn97** [comment]
@Carlosdmendoza 
It is working well in FluxBuilder. Can you show me your progress to get this error(video record)? https://tppr.me/civLo
In mobile background, Try with attach code above: https://tppr.me/r7K0v.

**Comment by Carlosdmendoza** [comment]
About the background I replaced the code already at least I think I did would you mind telling me what is the route directory where I am supposed to replace it? I just want to make sure that I did it right and sure I can record a video but there is not so much to record  I just open the program and when I go to attach any image that message is showing up would you reccomend anything to fix the app?

**Comment by Carlosdmendoza** [comment]
Hi, I am still waiting for you response on this matter I have tried with the files you provide me to fix the background error I replaced the files still the same error remains would you please mind be more specific when saying to update the files? I downloaded the ones you provide me on the archive.zip and I updated them were I tought they should be updated can you please tell me the exact directory where I should place them? I might be doing something wrong. Also about the fluxbuilder the issue remains whenever I try to upload an image from my website and if I do it from a file  in my pc it simply does not updates itself I have to manually type in the image URL for it to work. I have notice that you are using MAC OS for the screenshots you provide me I am using windows is there any type of bug or incompatiblity with current version that might be causing the problem with Flux Builder?

**Comment by vumanhsn97** [comment]
@Carlosdmendoza 
Can you send me your latest project folder to vumanhsn97@gmail.com? I will check background error in this.
In FluBuilder, We will release next version (1.0.6). If it keep saving your problem, you can send a feedback again
Thanks!

**Comment by Carlosdmendoza** [comment]
Sure the whole source folder or just the pubsex.yaml?

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
