### ISSUE TITLE
UIWebView rejected on AppStore

### ISSUE THREAD

**Issue by undigitals** [inspireui/support#3832]
**_Step 1 (require): describe detail issues & screenshots_**
![Screen Shot 2020-06-21 at 11 01 59 AM](https://user-images.githubusercontent.com/22441312/85215101-af99e000-b3ae-11ea-8d71-c9eb5d3d1e06.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

[57800852-beostore-complete-react-native-template-for-ecommerce-license.pdf](https://github.com/inspireui/support/files/4808825/57800852-beostore-complete-react-native-template-for-ecommerce-license.pdf)

**Comment by luyx2412** [comment]
Hi @undigitals We already upgrade new version MStore 4.0 which fix this issues and improve many things. So please download latest version when you got notification.

Thanks

**Comment by undigitals** [comment]
Hi @luyx2412 when you think I will get the notification? is that gonna happen like this week or something?

**Comment by undigitals** [comment]
That's it I got the email. But one can't you tell me what lib to change or anything like to fix this UIWebview issue, so that I don't have to do it all over again? if possible. Thanks.

**Comment by luyx2412** [comment]
Hi @undigitals You meant your app approved by apple? Because we used many libraries, so we did not know specific library, but i think upgrade react-native-firebase which will fix the issue.

Thanks

**Comment by undigitals** [comment]
Hello @luyx2412 should I update the pods or just npm package of react-native-firebase ?

**Comment by undigitals** [comment]
Hello @luyx2412 with new version 4.0.0 I deployed. Again this message. Please help me out.

![Screen Shot 2020-06-25 at 9 14 24 PM](https://user-images.githubusercontent.com/22441312/85718759-c54e3300-b729-11ea-887f-4d01ef6cd706.png)

**Comment by luyx2412** [comment]
HI @undigitals Please follow the comment to fix the issues, https://github.com/software-mansion/react-native-gesture-handler/issues/1008#issuecomment-634916717 or https://github.com/invertase/react-native-firebase/issues/3018#issuecomment-566829775. If everything did not work, please send your project via inspireui.team@gmail.com

Thanks

**Comment by undigitals** [comment]
@luyx2412 Hi I have sent you the file. I have tried all but still getting the same message please help me out. 

Thanks.

**Comment by undigitals** [comment]
HI @luyx2412 is there any news ? I have update almost 10 builds. I have tried updating gesture-handler, firebase, updated some of the pods. But still rejection.

**Comment by luyx2412** [comment]
Hi @undigitals The issue related react-native-admob, so if you did not use this library. Please remove it in your package.

Thanks

**Comment by undigitals** [comment]
Hi @luyx2412 I deleted the react-native-admob but still, I have that issue. Please look it up the file I have sent you over.
![Screen Shot 2020-06-28 at 1 27 18 PM](https://user-images.githubusercontent.com/22441312/85937935-5ea46180-b943-11ea-8217-35c697e0aeba.png)

**Comment by undigitals** [comment]
@luyx2412 it's been 4 months I have been doing this, `review` did not work, I waited. You updated and I had to do it all over again now this, rejected I had to do all over again. And you sending these links which I have already found on google. I have done all. But still, you sending these links and one message in 2 days.

**Comment by undigitals** [comment]
@luyx2412 Please help me out, it's taking me all day long. If I knew how to change those binary files I would have bought this template.
<img width="1029" alt="Screen Shot 2020-06-28 at 1 46 55 PM" src="https://user-images.githubusercontent.com/22441312/85938263-a4aef480-b946-11ea-9865-cb113e7812af.png">

**Comment by undigitals** [comment]
@luyx2412  https://groups.google.com/forum/#!category-topic/google-admob-ads-sdk/QuZMbjIyxn8%5B101-125%5D

**Comment by undigitals** [comment]
@luyx2412 I used `"react-native-admob": "^2.0.0-beta.6",` admob in another project and it's working. I mean apple accepted it. And there is `Google-Mobile-Ads-SDK` , `pod` as well. So that means `Account Kit` might be the issue?

**Comment by luyx2412** [comment]
Hi @undigitals I don't make sure about it, i try update all latest version when the apple approve it. But when i remove `react-native-admob` or upgrade `Google-Mobile-Ads-SDK` which worked normal.  And you meant `Account Kit` is login sms facebook?

Thanks

**Comment by undigitals** [comment]
@luyx2412 did you check my files? if that worked for you, can you fix my files too? and yeah I guess so `login sms`

**Comment by luyx2412** [comment]
Hi @undigitals I can upgrade your file, but i could not upload to check about it. So please try in your side.

Thanks

**Comment by undigitals** [comment]
@luyx2412 Yes I will check it.

**Comment by undigitals** [comment]
@luyx2412 lastly I figured out. It was with `AccountKit` as I have assumed. 
![Screen Shot 2020-06-28 at 10 01 38 PM](https://user-images.githubusercontent.com/22441312/85948364-71428900-b98b-11ea-94c8-e339c87c0b15.png)
