### ISSUE TITLE
Update Banner without Change the Code

### ISSUE THREAD

**Issue by harjono-flux** [inspireui/support#3833]
Hello... Sorry if my ask is very basic. How to change the banner image and URL (action when end user click the banner) without change the code/ update the program?

Thx

**Comment by ameenbadri7** [comment]
simply go to your `config_en.json` file and copy and paste this and add it:

```
{
      "layout": "bannerImage",
      "isSlider": true,
      "autoPlay": true,
      "showNumber": false,
      "design": "default",
      "showBackGround": true,
      "radius": 2.0,
      "items": [
        {
          "category": 55,
          "image": "http://aminshop.local/wp-content/uploads/banner/banner3-1.webp",
          "padding": 15.0
        },
        {
          "category": 52,
          "image": "http://aminshop.local/wp-content/uploads/banner/banner3-3.jpg",
          "padding": 15.0
        },
        {
          "category": 53,
          "image": "http://aminshop.local/wp-content/uploads/banner/banner3-2.webp",
          "padding": 15.0
        }
      ]
    },
```
`category ` is the  category id from woocommerce that you want to go after clicking on the picture 
`image` is the picture URL 
`isSlider` to make it the stable banner as a slider move by click
`autoPlay` to make the banner with more than two pictures move without clicking.

you can go to 20 themes inside your fluxstore app source files expect inside 
`lib\example\woocommerce
`
see this video you will be amazed [wow](https://www.youtube.com/watch?v=5AzAIU7Dddk)
also, you can learn more from this link 
[home-layout customization ](https://docs.inspireui.com/fluxstore/home-layout/). 

please read all the [documentation](https://docs.inspireui.com/fluxstore) you will be very impressed with this app. 
enjoy

**Comment by harjono-flux** [comment]
Sory, i mean, when the apps is already publish
