### ISSUE TITLE
FluxBuilder for Extended License user

### ISSUE THREAD

**Issue by imhafeez** [inspireui/support#3837]
I am using fluxBuilder for multiple clients as I purchased Flux-Pro Flutter e-commerce app with Extended license.
As I added another client it says the code has been used. Should it be to add multiple clients for the extended license buyer?

<img width="416" alt="Screenshot 2020-06-06 at 11 09 06 PM copy" src="https://user-images.githubusercontent.com/21155655/85221576-22668380-b3ce-11ea-9e1d-1203972362ac.png">

**Comment by ameenbadri7** [comment]
yes sir. your license only for one website and one flutter project. 
I am not from the fluxstore team 
but from my experience, there are two options to buy fluxstore 
`Regular` and `Extended` 
if you buy `Regular`  you will get only one product for one client. 
if you buy `Extended`  you will get also only one product for one client but with special development tips and customization. 

for further information go to this link 
[codecanyon license ](https://codecanyon.net/licenses/standard?license=regular)

**Comment by imhafeez** [comment]
@ameenbadri7 No before buying I confirmed that from Fluxstore team. You can distribute to as many client as you want.

**Comment by minhcasi** [comment]
@imhafeez - sorry the validate for extend license feature is not available from the fluxbuidler app, you could only build it as manually :)
