### ISSUE TITLE
Header Logo section is transparent 

### ISSUE THREAD

**Issue by Shopyloot** [inspireui/support#3838]
In Flux builder i have enable Logo header properties as sticky, show menu, and logo and search it looks good in the flux builder but in the real or emulator after placing the config file generated in the fluxbuilder the logo header here in the device is transparent which look weird 

In the emulator 
https://prnt.sc/t3pnri

In the fluxbuildrr
https://prnt.sc/t3ppe3

I have copied the entire config file to the config_en.json file and uploaded the same to the Mstore API in the wordpress.

Please help also in the fluxbuilder i have no option as apply website data in General settings

**Comment by ameenbadri7** [comment]
if you spent more time understanding the config file from this link [config setting of fluxstore](https://docs.inspireui.com/fluxstore/config/)  you will be amazed by what `fluxstore `is really about. 
you can do everything you like more than `20 themes` by only customizing the `config.json ` file.

ok to add a background to your header config as following: 
in this one 

```
 "HorizonLayout": [
    {
      "layout": "logo",
      "showMenu": true,
      "showSearch": false,
      "showLogo": true,
      "background": "#FFFFFF"
    },
```

the `background `to select a background color.
` #FFFFFF` is white you can but whatever color you want by using these colors hex codes.
for more colors hex go to `lib\common\constants\colors.dart ` .

you can also see the color from the code file directly without building each time by this VScode extension `Color Highlight`.

please tell me if you want any help. 
enjoy

**Comment by minhcasi** [comment]
@Shopyloot 
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one with full information - thank you for your time!
