### ISSUE TITLE
Anu new update on the cebuilder Issue

### ISSUE THREAD

**Issue by osamasparky** [inspireui/support#384]
Mandatory Info (please complete the following information):
 Please why you stop replaying on that 
    
    MVStore
    Purchase code: da4e5510-501d-456f-9d1d-fbbcdd24f102
    (we may not reply if you are not our customer)
   When i click on customization i got error on cebuilder
Screenshots
![53803426-c1efd080-3f55-11e9-9c49-f4d92a8d6d5d](https://user-images.githubusercontent.com/36470035/54082450-0c42ca00-4327-11e9-8df9-fb07883999dd.png)

Add any other detail logs about the problem here.

**Comment by minhtruong315** [comment]
I am updating to fix this issue. thanks

**Comment by minhtruong315** [comment]
Pls update newest cebuilder to fix this issue. thanks
