### ISSUE TITLE
Too much loading time 

### ISSUE THREAD

**Issue by kevinsh25** [inspireui/support#3840]
I am using Fluxtore Pro with Magento 2.3
I have too much loading issues. The time taken is 30-40 seconds to load. Have followed optimization link too

**Comment by amjadalfawal** [comment]
@kevinsh25 what is optimization link too

**Comment by minhcasi** [comment]
@kevinsh25 

Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one with full information - thank you for your time!

**Comment by kevinsh25** [comment]
This is happening to everyone. Tickets closed and too many error
