### ISSUE TITLE
mobile number login

### ISSUE THREAD

**Issue by meeraforefront** [inspireui/support#3841]
**_Step 1 (require): describe detail issues & screenshots_**
I would like to indicate mobile number login facility in my project. So what would i wants to do?
Is digits is supporting in it? 
i am using Fluxstore multi vendor 1.6.7.

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@meeraforefront - do you mean the SMS Login feature from the app?

**Comment by meeraforefront** [comment]
@minhcasi  i need an extra filed to add Phone number in my Registration form(vendor registration), and OTP verification.

**Comment by minhcasi** [comment]
@meeraforefront - please help us to make the customization by your own requirements to support these features - thank you!

**Comment by meeraforefront** [comment]
Hi minhcasi how can i help you to customize this requirement.

**Comment by minhcasi** [comment]
We're sorry that could not help for this customization at this time
