### ISSUE TITLE
collection ID format is different !!

### ISSUE THREAD

**Issue by egyping** [inspireui/support#3843]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
the original purchased template has the collection "category" in the layout.js has this format sample 
"Z2lkOi8vc2hvcGlmeS9Db2xsZWN0aW9uLzE2Mzg3MjQ3MzE2NQ=="
but in my store when i browse the graphql am getting the collection IDs as follow 
"gid://shopify/Collection/162337648205"

when i use the second its not working and am not able to get the first format actually 
any help here 

+ Product & version:MSTOR shopify react natve ecommerce
+ Flutter (or React Native) version: React native
+ Testing Device/Simulator: ios and android
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by egyping** [comment]
Done i have submit the form 

i will explain the issue once more

as per the conf document i have to change the category ID to the desired category ID from my store 
the category ID in the shopify admin panel i got it from the URL 
i psate it and refresh the emulator it doesnt pull any image or data however i put the correct apikey and even i tried token key both are not working 

i want the template to integrate and work with my store

**Comment by egyping** [comment]
I think this template may be little old may be the card not updated as per shopify new structure 

anyway i need urgently someone to help me getting this template work

**Comment by luyx2412** [comment]
HI @egyping Please follow the video to get right collection id https://www.youtube.com/watch?v=nE7a_yx5Q9w&t=66s and this is the document Evastore https://docs.inspireui.com/evastore/quick-setup/

Thanks

**Comment by egyping** [comment]
ok please allow me some time don't close the ticket

**Comment by luyx2412** [comment]
Hi @egyping Ok, please mention me when you need the support.

Thanks
