### ISSUE TITLE
Issue & Solution: Failed to find Platform SDK with path: platforms;android-R #3708 - Unsolved

### ISSUE THREAD

**Issue by honexmedina** [inspireui/support#3845]
Hello, I have the same issue. Previously i added SDK v30, and code:

subprojects {
project.buildDir = "${rootProject.buildDir}/${project.name}"
project.evaluationDependsOn(':app')
afterEvaluate {project ->
if (project.hasProperty("android") && project.property("android").compileSdkVersion.equals("android-R")) {
android {
compileSdkVersion 30
}
}
}
![85200147-368a8200-b2f5-11ea-9904-1136e0e06ef6](https://user-images.githubusercontent.com/67252681/85247549-1acdcb80-b41c-11ea-9b2a-0550e2fa8bbb.png)
After, I cleaned my cache, following the steps:
Open android studio Tools->Flutter->Clean
Go to File -> Invalidate Caches / Restart
Or open terminal run "flutter clean"
Remove pubspec.lock

But I can't do this steo: Double check the Flutter SDK Path config correctly, because the image https://tppr.me/qn6dP is broken.

Also I updated Flutter to Channel Stable and upgraded. After, I moved and updated flutter to master branch, following recommended solutions on this ticket.

After, I ran gradlew.bat clean command and deleted .grade folder.

But my problem not solved yet. Can you make a video explanation about how to fix this issue? I bought this product yesterday and I don´t want to lose my money. Pls, can you help me?

I have flutter Intl plugin install
![85200645-866b4800-b2f9-11ea-88b5-8bcfebdf05a6](https://user-images.githubusercontent.com/67252681/85247575-38029a00-b41c-11ea-919d-374ec41d74cf.png)
![image](https://user-images.githubusercontent.com/67252681/85247579-3afd8a80-b41c-11ea-9f2f-e5761c449dc3.png)
![image](https://user-images.githubusercontent.com/67252681/85247578-3933c700-b41c-11ea-8db3-64d33be42853.png)

I have flutter skd path correctly
![85200705-0396bd00-b2fa-11ea-9c47-64a28d5086b2](https://user-images.githubusercontent.com/67252681/85247603-510b4b00-b41c-11ea-81cf-82babc91c38e.png)

My Android SDK is API 30
![85200728-393ba600-b2fa-11ea-9f7c-e5c470958af2](https://user-images.githubusercontent.com/67252681/85247640-6bddbf80-b41c-11ea-84e5-63b80c75f5b6.png)
![85200785-79028d80-b2fa-11ea-896f-bdccfdc8cf3b](https://user-images.githubusercontent.com/67252681/85247648-726c3700-b41c-11ea-81a8-e2c635561371.png)

I made all solutions about this issue but I have the same error...

500
404

Video
https://www.loom.com/share/91eca750e5ee4d8fb68f6237d0de43b4

Loom
Issue & Solution: Failed to find Platform SDK with path: platforms;android-R · Issue #3708 · inspireui/support
Check out a video I made via Loom

**Comment by minhcasi** [comment]
@honexmedina - could you try to switch the flutter master to see if there is any luck
```
flutter channel master
flutter upgrade --force
flutter clean
```

Try a play with on this channel, then switch back the `stable channel` (some users have the same issue but they can run)

Also, have a try to run the example from Flutter - https://flutter.dev/docs/get-started/test-drive?tab=vscode

**Comment by minhcasi** [comment]
related #3708

@honexmedina - have a try on below solution, we will help to follow your update until it is fixed 😊

**Comment by multcriacoes** [comment]
> related #3708
> 
> @honexmedina - have a try on below solution, we will help to follow your update until it is fixed 😊

Hello minhcasi,

Even if I do all the indications, I still have the same problem.

With other projects, I have no problem.

**Comment by minhcasi** [comment]
please also have a check on latest comment - flutter/flutter#59355

or override this pubspec if using the Flutter pro
pubspec.yaml.txt

And make to run gradlew clean by following https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

**Comment by ertugazi91** [comment]
**_android/build.gradle_** You will go into it and delete the subprojects functions and replace them. 

subprojects {
project.buildDir = "${rootProject.buildDir}/${project.name}"
project.evaluationDependsOn(':app')
afterEvaluate {project ->
if (project.hasProperty("android") && project.property("android").compileSdkVersion.equals("android-R")) {
android {
compileSdkVersion 30
}
}
}
