### ISSUE TITLE
App restarts while trying to buy

### ISSUE THREAD

**Issue by akhilandraj** [inspireui/support#3846]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues:  I am getting the following error seen in the screenshot while trying to run the application from the cart, filter, buy now pages. I published the apk and its restartting on the pages.
+ Product & version: Mstore mgento app
+ Flutter (or React Native) version: React Native
+ Testing Device/Simulator: Nokia 7.1
+ Screenshot issues (drag the file to attach here): 
![Screen Shot 2020-06-22 at 10 04 34 AM](https://user-images.githubusercontent.com/41319834/85249339-1a135480-b471-11ea-9e27-8fab9fcabeb6.png)

![Screenshot_20200622-100758](https://user-images.githubusercontent.com/41319834/85249403-4a5af300-b471-11ea-913c-6029b27cfd85.png)

**Comment by minhtruong315** [comment]
Hi @akhilandraj can u upload your source code to github and invite me: minhtruong315@gmail.com"
I will help you check and fix on your source code.
Thanks

**Comment by akhilandraj** [comment]
Hi,

I have invited you to the repository, I am facing an issue from step one.
from installing the npm packages to installing teh Mstore extension in the
magento sites.

Please let me know if you need access to the magento site. Thank you.

Regards,
Akhil Raj

**Comment by minhtruong315** [comment]
Hi @akhilandraj Didn't you install Mstore extension on your website?
<img width="874" alt="Screen Shot 2020-06-25 at 10 05 15 AM" src="https://user-images.githubusercontent.com/10402500/85648664-740f5680-b6cb-11ea-8919-ff6ee477f24d.png">
Please follow this guide to install MStore extension
https://docs.inspireui.com/mstore-magento/customization/

**Comment by akhilandraj** [comment]
HI,

I tried this few times but the process is crashing my magento install and
then even the website won't work. I do not even find any supporting
document for the same.

I tried it again. and please check the site now.

This could be a minor issue, if we can connect through skype or slack on a
realtime support, this can be fixed in notime. Please let me know


Thank You
Akhil Raj

**Comment by minhtruong315** [comment]
Hi @akhilandraj The rest api is working well. please check app again

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!

**Comment by akhilandraj** [comment]
HI, Please check the app from the playstore

https://play.google.com/store/apps/details?id=com.bompixmori.wareroot

I am not able to do buy-now. Could you please help. This is just the same code, no customization has made.
