### ISSUE TITLE
Product offer price issue

### ISSUE THREAD

**Issue by basithzan** [inspireui/support#3848]
Same problem with v1.7.5

https://github.com/inspireui/support/issues/3693#event-3442553712

![Screenshot 2020-06-22 at 1 07 54 PM](https://user-images.githubusercontent.com/12207952/85261411-bea19080-b489-11ea-88bb-9fef3f124bcb.png)

@minhcasi

**Comment by minhcasi** [comment]
@basithzan - pls continuous this comment into one ticket #3849
