### ISSUE TITLE
Only 20 products are show in category page

### ISSUE THREAD

**Issue by basithzan** [inspireui/support#3849]
i have 98 products under top category, but only 20 products are loading when I select "Tops" category from top scrolling category bar. (But all 98 products are loading when I access "tops" category from Bottom category tab from homescreen.

![Screenshot 2020-06-22 at 1 14 18 PM](https://user-images.githubusercontent.com/12207952/85262408-59e73580-b48b-11ea-81f3-52e589534219.png)
![Screenshot 2020-06-22 at 1 16 22 PM](https://user-images.githubusercontent.com/12207952/85262437-64a1ca80-b48b-11ea-9b30-9ba6b4572301.png)
![Screenshot 2020-06-22 at 1 16 45 PM](https://user-images.githubusercontent.com/12207952/85262450-6c616f00-b48b-11ea-8b19-4ed107dc2042.png)

**Comment by philipvu30** [comment]
Hi,

In lib/models/product/product_model.dart, rewrite the code to be like this

![image](https://user-images.githubusercontent.com/54442328/85277642-e99ddb80-b4ad-11ea-8fb9-cc1376da7933.png)

**Comment by philipvu30** [comment]
Closed as no response in 2 days. 

If you are happy with our services/support, would you mind rating us on your [download page](https://codecanyon.net/downloads)?
We truly appreciate your help.

**Comment by basithzan** [comment]
Same problem with v1.7.5

https://github.com/inspireui/support/issues/3693#event-3442553712

![Screenshot 2020-06-22 at 1 07 54 PM](https://user-images.githubusercontent.com/12207952/85261411-bea19080-b489-11ea-88bb-9fef3f124bcb.png)

@minhcasi @philipvu30

**Comment by philipvu30** [comment]
Hi,

Please re-submit your common and config folders via our [form](https://docs.google.com/forms/d/e/1FAIpQLScWOjkAJIWJ9rgb9alopfOqLsJrGKbFM5cCYj1JBfLKLsBblQ/viewform), or send them to my email: toan@inspireui.com.

Thanks.

**Comment by basithzan** [comment]
> Hi,
> 
> Please re-submit your common and config folders via our [form](https://docs.google.com/forms/d/e/1FAIpQLScWOjkAJIWJ9rgb9alopfOqLsJrGKbFM5cCYj1JBfLKLsBblQ/viewform), or send them to my email: [toan@inspireui.com](mailto:toan@inspireui.com).
> 
> Thanks.

Done. Pls check.

**Comment by philipvu30** [comment]
Hi,

I've already shown you 2 [solutions](https://github.com/inspireui/support/issues/3849#issuecomment-647430981) but you followed only one. Next time, please try it before asking for assistance since we are really busy.

Thank you.

P/s: Replace this [file](https://github.com/inspireui/support/files/4830554/product_model.dart.zip) in lib/models/product/product_model.dart. Version tested: FluxStore Woocommerce v1.7.5

**Comment by basithzan** [comment]
> Hi,
> 
> I've already shown you 2 [solutions](https://github.com/inspireui/support/issues/3849#issuecomment-647430981) but you followed only one. Next time, please try it before asking for assistance since we are really busy.
> 
> Thank you.
> 
> P/s: Replace this [file](https://github.com/inspireui/support/files/4830554/product_model.dart.zip) in lib/models/product/product_model.dart. Version tested: FluxStore Woocommerce v1.7.5

I asked assistance for this issue https://github.com/inspireui/support/issues/3693#event-3442553712 (I opened a new ticket, but the admin asked me to send issue in one single ticket here.) 

**This issue is related to the Product offer price.** 


![84426046-32e56400-ac40-11ea-9f7d-6709a4591443](https://user-images.githubusercontent.com/12207952/85702645-3d9dff80-b6fc-11ea-87e9-f8bd520c68d5.jpg)

**Comment by philipvu30** [comment]
Hi,

Sorry, I thought you asked the previous question. Please have a check on your product, because it is titled as on_sale but no sale price was given.

![image](https://user-images.githubusercontent.com/54442328/85704162-3f6ebf80-b70a-11ea-9eb5-29bac8d49257.png)

**Comment by basithzan** [comment]
Can you please check these screenshots?? i can see sale price is added.

![Screenshot 2020-06-25 at 4 13 11 PM](https://user-images.githubusercontent.com/12207952/85705425-d2096180-b6fe-11ea-8f69-7e35d2e675d6.png)
![Screenshot 2020-06-25 at 4 10 43 PM](https://user-images.githubusercontent.com/12207952/85705176-9d95a580-b6fe-11ea-8dd1-981659f79b77.png)
![Screenshot 2020-06-25 at 4 13 01 PM](https://user-images.githubusercontent.com/12207952/85705407-cd44ad80-b6fe-11ea-9081-f8f6cad99ae7.png)

**Comment by philipvu30** [comment]
Hi,

I see what is the problem here. Because your product is variable, and the prices on the variable product are usually not consistent, so it needs to be removed and should leave only the On Sale tag. 
We forgot to remove that part. Would you mind adding this code to this line in lib/widgets/product/product_card_view.dart?

![image](https://user-images.githubusercontent.com/54442328/85707756-af327980-b70d-11ea-80ef-98358baca03b.png)

**Comment by basithzan** [comment]
Now only the sale price is showing!!

![Screenshot 2020-06-25 at 4 47 49 PM](https://user-images.githubusercontent.com/12207952/85710220-aa68c800-b703-11ea-83cc-d9d4316d2dab.png)

**Comment by philipvu30** [comment]
Hi,

It's supposed to be like that due to the prices are varied in variable products. The sale price is only showing when the product is simple.

**Comment by basithzan** [comment]
if we set a default product variation that should be shown right?? because the price will be constant in that case

**Comment by philipvu30** [comment]
Hi,

If you have only 1 variation for a product, then simply set it to a "simple" type will fix it.

> if we set a default product variation that should be shown right?? because the price will be constant in that case

Sorry, it doesn't work like that.

**Comment by philipvu30** [comment]
Closed as no response in 2 days. 

If you are happy with our services/support, would you mind rating us on your [download page](https://codecanyon.net/downloads)?
We truly appreciate your help.
