### ISSUE TITLE
[ListPro] installation guide

### ISSUE THREAD

**Issue by MuksMakkar** [inspireui/support#385]
- Product: [listpro]
 - Your Purchased Code: [email: m@omtechies.com]
 issue:
need step by step guide for buid and installation through cebuider

**Comment by MuksMakkar** [comment]
No i have installed and setup cebuilder by watching your youtube video. Android emulator also working through expo. But i see no listing at all. how can i customize it, see my listings, buid it and publish it?
your customer service response is very slow. Please improve it.
[WhatsApp Video 2019-03-11 at 7.20.33 PM.zip](https://github.com/inspireui/support/files/2952467/WhatsApp.Video.2019-03-11.at.7.20.33.PM.zip)

**Comment by thangvo9x** [comment]
Hi. Can u give me your AppConfig.json, info admin, plz? I'll config it helps you by manually.

**Comment by MuksMakkar** [comment]
I can't share my admin info here in public comments. I am going to email on Minh@inspireui.intercom-mail.com

**Comment by minhcasi** [comment]
https://app.intercom.io/a/apps/xro9xnfd/inbox/conversation/21167129306

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by thangvo9x** [comment]
Hi. You forgot to enable Rest API Controller from Tools menu in your admin. I activated it.

**Comment by MuksMakkar** [comment]
Now it will work? What about appconfig.json file? Will it remain same?

**Comment by thangvo9x** [comment]
Yes. I checked. You must have put full URL in AppConfig.json

**Comment by MuksMakkar** [comment]
Ok

**Comment by minhcasi** [comment]
refunded
