### ISSUE TITLE
Need support to integrate Stripe in Magento2 

### ISSUE THREAD

**Issue by subhquad** [inspireui/support#3850]
**_Step 1 (require): describe detail issues & screenshots_** 
+ Detail Issues: Need support to integrate Stripe in Magento2 . 
+ Product & version: Fluxstore Pro 1.7.5
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: iPhone 11
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

80f2ca3f-3e8f-43cd-97ba-9dd311d5fb75

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by SharafMHD** [comment]
Following

**Comment by minhcasi** [comment]
@subhquad - I'm sorry that we could not support for this integration, please help to reference to existing native Paypal payment, or reference to this library https://pub.dev/packages/stripe_payment
