### ISSUE TITLE
Long loading time fluxstore-multi-vendor-flutter

### ISSUE THREAD

**Issue by titicelv** [inspireui/support#3851]
**_Step 1 (require): describe detail issues & screenshots_**
I was running app 1.7.3 version. It was slow loading. Than i decided to move on 1.7.5 due i do not understood how to update versions i just created app from sratch. I have followed optimization doc. My loading time after splash screen disapers - 1 minute 44 sec. You can check video [here](https://www.youtube.com/watch?v=KjyaGgl4fA4&feature=youtu.be)
I am running dokan.

+ Detail Issues: 
+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by titicelv** [comment]
Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com
done

**Comment by minhcasi** [comment]
@titicelv - could you help to zip your source and share to support@inspireui.com for further investigating - thank you!

**Comment by titicelv** [comment]
I have created source zip and You can download it [www.titice.lv/source.zip](www.titice.lv/source.zip)

**Comment by minhcasi** [comment]
@titicelv - pls share private to email support@inspireui.com also comment the ticket ID - thank you!

**Comment by titicelv** [comment]
I am not able. Via Email Due zipped source file is 500+MB largeOr should I just zip part of source? Sent from my Huawei tablet-------- Original Message --------Subject: Re: [inspireui/support] Long loading time fluxstore-multi-vendor-flutter (#3851)From: Minh Pham To: inspireui/support CC: titicelv ,Mention 
@titicelv - pls share private to email support@inspireui.com also comment the ticket ID - thank you!

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/inspireui/support/issues/3851#issuecomment-648565043",
"url": "https://github.com/inspireui/support/issues/3851#issuecomment-648565043",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by minhcasi** [comment]
Hi, pls share via https://wetransfer.com and share as private to our support email - inspireui.team@gmail.com - thank you!

**Comment by titicelv** [comment]
File have been Sent.

**Comment by minhcasi** [comment]
noted with checking - thank you!

**Comment by titicelv** [comment]
Is there any update?

**Comment by kvt0012** [comment]
Can you send me your whole project via khiem@inspireui.com, I will check it for you, thank you

**Comment by titicelv** [comment]
I have already sent it via WeTransfer. It was whole project.

**Comment by titicelv** [comment]
Firstly i uploaded it to my webserver and provided link to it. I was told to use WeTransfer. So i did it. I am not able to attach it to email due it is too large file. 
Can You just download it from my webserver or should i use WeTransfer again? Or how could i must send it?

**Comment by kvt0012** [comment]
Ok, sir, because I'm new one so I don't receive your whole project. But now the previous person forward it for me, I will check is ASAP

**Comment by titicelv** [comment]
Thanks

**Comment by kvt0012** [comment]
You can come to app_init.dart and edit the time of the app. 
And you can come to config_en.json and change your image that you want. 
You don't need to config too much, it's better to follow our format. Thank you

**Comment by kvt0012** [comment]
![image](https://user-images.githubusercontent.com/49152325/86119093-0fedf780-bafc-11ea-9793-b14c97634ad4.png)
 
![image](https://user-images.githubusercontent.com/49152325/86119138-21370400-bafc-11ea-89a1-f55de9cd99a9.png)

**Comment by titicelv** [comment]
I have played with settings and yes You are right - if i use flr splash screen first data in app will be loaded in 20 sec, which is ok. Anyway all data is loaded in 1 minute. Your app is much more faster.
Is it possible to switch off splash screen and onboarding message at all?
If yes - how i can turn it off?

**Comment by kvt0012** [comment]
yes sir, you can off splash screen by config on file app_init, make a comment which part related to splash screen.

**Comment by titicelv** [comment]
I have played a lot. Even switched of splash screen. First item from dokan loads in 1 minute and 5 seconds. 
The interesting thing is - data from blog and banners are loaded instantly.
Also, if category is clicked first data will load in 10 - 15 sec.
How and what to improve?

**Comment by kvt0012** [comment]
Can you send me your source code, I'll check it, thank you

**Comment by titicelv** [comment]
You already have it:
kvt0012 commented 7 days ago
Ok, sir, because I'm new one so I don't receive your whole project. But now the previous person forward it for me, I will check is ASAP

Are You paying attention to whole conversation? What i must to send You if You have a whole project?????

**Comment by minhcasi** [comment]
@titicelv - i'm sorry to late response on this ticket - we have fixed this issue on latest released `1.7.6` - let us know if you have any further issue - thank you!
