### ISSUE TITLE
Error causing app to crash 

### ISSUE THREAD

**Issue by ddanas** [inspireui/support#3853]
After exporting config file, I ran the app on emulator and this is the error I got 

https://bit.ly/2Ym6U88

The following is the output in console. 

Launching lib\main.dart on sdk gphone x86 arm in debug mode...
Running Gradle task 'assembleDebug'...
Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\connectivity-0.4.8+5\android\src\main\java\io\flutter\plugins\connectivity\ConnectivityBroadcastReceiver.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_admob-0.9.3+2\android\src\main\java\io\flutter\plugins\firebaseadmob\AdRequestBuilderFactory.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.13.4\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
√ Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...
Flutter is taking longer than expected to report its views. Still trying...
Debug service listening on ws://127.0.0.1:58162/lDPqtMXhWnA=/ws
Syncing files to device sdk gphone x86 arm...
I/inspireui.fnew(12121): The ClassLoaderContext is a special shared library.
I/chatty  (12121): uid=10151(com.inspireui.fnews) identical 1 line
I/inspireui.fnew(12121): The ClassLoaderContext is a special shared library.
I/DynamiteModule(12121): Considering local module com.google.android.gms.ads.dynamite:0 and remote module com.google.android.gms.ads.dynamite:21400
I/DynamiteModule(12121): Selected remote version of com.google.android.gms.ads.dynamite, version >= 21400
D/DynamitePackage(12121): Instantiated singleton DynamitePackage.
D/DynamitePackage(12121): Instantiating com.google.android.gms.ads.reward.ChimeraRewardedVideoAdCreatorImpl
W/ContextImpl(12121): Failed to ensure /storage/140C-3D0B/Android/data/com.inspireui.fnews/files/Pictures: android.os.ServiceSpecificException:  (code -22)
I/WebViewFactory(12121): Loading com.google.android.webview version 83.0.4103.44 (code 410404481)
W/inspireui.fnew(12121): Accessing hidden method Landroid/view/accessibility/AccessibilityNodeInfo;->getSourceNodeId()J (greylist,test-api, reflection, allowed)
W/inspireui.fnew(12121): Accessing hidden method Landroid/view/accessibility/AccessibilityRecord;->getSourceNodeId()J (greylist, reflection, allowed)
W/inspireui.fnew(12121): Accessing hidden field Landroid/view/accessibility/AccessibilityNodeInfo;->mChildNodeIds:Landroid/util/LongArray; (greylist, reflection, allowed)
W/inspireui.fnew(12121): Accessing hidden method Landroid/util/LongArray;->get(I)J (greylist, reflection, allowed)
D/HostConnection(12121): HostConnection::get() New Host Connection established 0xf44596f0, tid 12231
D/HostConnection(12121): HostConnection::get() New Host Connection established 0xf4459450, tid 12257
D/HostConnection(12121): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_3_0
D/EGL_emulation(12121): eglCreateContext: 0xf4283f10: maj 3 min 0 rcv 3
D/HostConnection(12121): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_3_0
I/inspireui.fnew(12121): The ClassLoaderContext is a special shared library.
W/inspireui.fnew(12121): Verification of int com.google.firebase.auth.api.internal.zzek.zzd(java.lang.String) took 1.144s (85.66 bytecodes/s) (1904B approximate peak alloc)
I/FA      (12121): Tag Manager is not found and thus will not be used
I/Gralloc4(12121): mapper 4.x is not supported
D/HostConnection(12121): createUnique: call
D/EGL_emulation(12121): eglCreateContext: 0xf428ee10: maj 3 min 0 rcv 3
I/inspireui.fnew(12121): The ClassLoaderContext is a special shared library.
D/HostConnection(12121): HostConnection::get() New Host Connection established 0xf445b730, tid 12257
D/eglCodecCommon(12121): allocate: Ask for block of size 0x100
D/eglCodecCommon(12121): allocate: ioctl allocate returned offset 0x3faa3c000 size 0x2000
D/HostConnection(12121): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_3_0
I/cr_VariationsUtils(12121): Requesting new seed from IVariationsSeedServer
D/EGL_emulation(12121): eglMakeCurrent: 0xf428ee10: ver 3 0 (tinfo 0xf45bfe50) (first time)
D/EGL_emulation(12121): eglMakeCurrent: 0xf4283f10: ver 3 0 (tinfo 0xf45bfc90) (first time)
I/inspireui.fnew(12121): Background concurrent copying GC freed 30234(2659KB) AllocSpace objects, 23(6924KB) LOS objects, 49% free, 4374KB/8749KB, paused 16.014ms total 732.801ms
I/Choreographer(12121): Skipped 823 frames!  The application may be doing too much work on its main thread.
I/cr_LibraryLoader(12121): Loaded native library version number "83.0.4103.44"
I/cr_CachingUmaRecorder(12121): Flushed 3 samples from 3 histograms.
W/inspireui.fnew(12121): Verification of void org.chromium.net.AndroidNetworkLibrary.addTestRootCertificate(byte[]) took 100.895ms (545.12 bytecodes/s) (1616B approximate peak alloc)
I/inspireui.fnew(12121): Background young concurrent copying GC freed 30512(2323KB) AllocSpace objects, 11(600KB) LOS objects, 11% free, 7764KB/8749KB, paused 428us total 451.971ms
I/inspireui.fnew(12121): Background concurrent copying GC freed 36916(1693KB) AllocSpace objects, 17(1700KB) LOS objects, 49% free, 5386KB/10MB, paused 17.195ms total 684.943ms
W/inspireui.fnew(12121): Verification of void com.google.firebase.auth.api.internal.zzef.zza(com.google.android.gms.internal.firebase_auth.zzdp, com.google.firebase.auth.api.internal.zzec) took 136.930ms (116.85 bytecodes/s) (1048B approximate peak alloc)
W/SQLiteLog(12121): (28) double-quoted string literal: "notification"
I/Choreographer(12121): Skipped 165 frames!  The application may be doing too much work on its main thread.
I/Choreographer(12121): Skipped 73 frames!  The application may be doing too much work on its main thread.
W/inspireui.fnew(12121): Long monitor contention with owner Measurement Worker (12177) at boolean android.os.MessageQueue.enqueueMessage(android.os.Message, long)(MessageQueue.java:599) waiters=0 in android.os.Message android.os.MessageQueue.next() for 1.354s
I/flutter (12121): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (12121): The following NoSuchMethodError was thrown building AppInit(dirty, state: _AppInitState#f0557):
I/flutter (12121): The method '[]' was called on null.
I/flutter (12121): Receiver: null
I/flutter (12121): Tried calling: []("type")
I/flutter (12121):
I/flutter (12121): The relevant error-causing widget was:
I/flutter (12121):   AppInit
I/flutter (12121):   file:///C:/Users/Daniel/Desktop/codecanyon-QJCDPLVQ-fluxnews-fluxnews-flutter-mobile-app-for-wordpress/fluxnew.1.4.1/source/lib/app.dart:105:23
I/flutter (12121):
I/flutter (12121): When the exception was thrown, this was the stack:
I/flutter (12121): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
I/flutter (12121): #1      _AppInitState.build (package:fstore/app_init.dart:81:56)
I/flutter (12121): #2      StatefulElement.build (package:flutter/src/widgets/framework.dart:4619:28)
I/flutter (12121): #3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4502:15)
I/flutter (12121): #4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
I/flutter (12121): #5      Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
I/flutter (12121): #6      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4481:5)
I/flutter (12121): #7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4666:11)
I/flutter (12121): #8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
I/flutter (12121): ...     Normal element mounting (19 frames)
I/flutter (12121): #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
I/flutter (12121): #28     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5947:32)
I/flutter (12121): ...     Normal element mounting (185 frames)
I/flutter (12121): #213    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
I/flutter (12121): #214    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5947:32)
I/flutter (12121): ...     Normal element mounting (123 frames)
I/flutter (12121): #337    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
I/flutter (12121): #338    Element.updateChild (package:flutter/src/widgets/framework.dart:3211:20)
I/flutter (12121): #339    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
I/flutter (12121): #340    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
I/flutter (12121): #341    Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
I/flutter (12121): #342    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2627:33)
I/flutter (12121): #343    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:20)
I/flutter (12121): #344    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:284:5)
I/flutter (12121): #345    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1113:15)
I/flutter (12121): #346    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1052:9)
I/flutter (12121): #347    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:968:5)
I/flutter (12121): #351    _invoke (dart:ui/hooks.dart:261:10)
I/flutter (12121): #352    _drawFrame (dart:ui/hooks.dart:219:3)
I/flutter (12121): (elided 3 frames from dart:async)
I/flutter (12121):
I/flutter (12121): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (12121): [AppState] Inital Data
I/flutter (12121): [AppState] Init Data Finish

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by dttrung26** [comment]
Hi @ddanas , 
could you please leave your skype here or contact me directly via skype: dttrung.ityu@gmail.com? I would like to run tests on your IDE via teamviewer. 
So sorry for the late response. 
Best!

**Comment by ddanas** [comment]
Hi Minh,

Sorry for the delay.

I had to get a new pc and started all over again. Is it possible to test my
system as I'm getting the following errors in console when trying to run
fluxnews on emulator.

console.txt
<https://mail.google.com/mail/u/0?ui=2&ik=0303a1c7a2&attid=0.1&permmsgid=msg-a:r7300428558830094831&view=att&disp=safe&realattid=f_kcc8f8kr0>
(24K)
<https://mail.google.com/mail/u/0?ui=2&ik=0303a1c7a2&attid=0.1&permmsgid=msg-a:r7300428558830094831&view=att&disp=safe&realattid=f_kcc8f8kr0>


Thanks in advance,

Daniel.
