### ISSUE TITLE
Shipping methods not loading

### ISSUE THREAD

**Issue by SharafMHD** [inspireui/support#3855]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: I'm receiving  an error while loading shipping method  due to i have some custom filed in my website 
+ Product & version: Fuxstore pro with opencart
+ Flutter (or React Native) version: Flutter
+ Testing Device/Simulator: android pixel
+ Screenshot issues (drag the file to attach here): 
![Screenshot_1592845427](https://user-images.githubusercontent.com/34410524/85315750-af900200-b4cc-11ea-8cca-d035a83afbd3.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by ameenbadri7** [comment]
if you are using the Arabic language version you should use woocommerce wpml plugins.
see this guide ,[please ](https://docs.inspireui.com/fluxstore/multi-language/#how-to-adddeleteedit-language)

**Comment by SharafMHD** [comment]
I'm using opencart as backend

**Comment by minhcasi** [comment]
@SharafMHD 

Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by SharafMHD** [comment]
@minhcasi
Thank you for responding, I submitted this  form. Please check and let me know.

**Comment by SharafMHD** [comment]
@minhcasi  I managed to fix this issue  .

but i have another tow issues 

1- in checkout the load only one shipping option meanwhile i have 3 options it my website
2-  where i can find the stripe payment config its not mentioned in payment.dart 

looking forward to hear from you  .

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as it could not be verified the purchase, please help to create a new one with full information - thank you for your time!
