### ISSUE TITLE
Hide Coupon Button and url in manifest file

### ISSUE THREAD

**Issue by samer-ibrahim** [inspireui/support#3856]
Dears InspireUI Team,

Fluxstore woocommerce version 1.7.5
(Proof of purchased sent in last ticket ##3753 )

1-As you know that coupon functions not cover some restrictions in the app compared by woocommerce, I am using the webview and the customer can apply the coupon from checkout page.

So I would like to hide the row of apply coupon from the app in my cart page as shown in the picture below, I tried to use the inspector but I am not sure what exactly the right action.

![1](https://user-images.githubusercontent.com/66953736/85316903-35f51580-b4c6-11ea-9c55-2c8fe3eb7e16.jpg)

2- I have changed the bundle ID successfuly but please confirm should I change the url in the andriod manifest.xml file (metadata) ? generally should I change any url to my domian ?

![2](https://user-images.githubusercontent.com/66953736/85317510-27f3c480-b4c7-11ea-9580-677ce56b3b72.jpg)
 
Kinds Regards,

Samer

**Comment by philipvu30** [comment]
Hi,

1. In lib/screens/cart/cart_sumary.dart, comment line 109-162
2. No need to change.

**Comment by samer-ibrahim** [comment]
Thank you very much.
