### ISSUE TITLE
critical bug in product page and cart 

### ISSUE THREAD

**Issue by abedfatafta** [inspireui/support#3858]
**_Step 1 (require): describe detail issues & screenshots_**
 in product page when you want to select how many item want its hang the app and it take so long to  load.

in  cart its hang and you can't click on the number to change 

you can test it live on teh app we release 
https://play.google.com/store/apps/details?id=ps.salla.store&hl=en&gl=US

+ Detail Issues: 
+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

3844

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@abedfatafta - pls help to give this comment to #3844 - my team will help to investigate

Also, try to add him into your git repo
