### ISSUE TITLE
Payment

### ISSUE THREAD

**Issue by nseven7** [inspireui/support#3859]
Hello, my problem is that when I make a purchase of a product, it throws me to the site where my data is entered (in the 24 second video). I want to immediately transfer payment to the site.
The video itself: https://youtu.be/3KdBvEl2v2g

Version: 1.7.5

**Comment by minhcasi** [comment]
@minhtruong315 - pls help with investigating

**Comment by minhtruong315** [comment]
Hi @nseven7 
You can try to disable NativeOnePageCheckout in common/config/payments.dart
```
/// Enable Payment option
  "EnableOnePageCheckout": false,
  "NativeOnePageCheckout": false,
```

**Comment by nseven7** [comment]
Hi @minhtruong315 
![43](https://user-images.githubusercontent.com/57550221/85554504-8cde2480-b657-11ea-83e3-3bc4926e14e0.PNG)
"Oh, page not found."

**Comment by minhtruong315** [comment]
@nseven7 You need to create a page with slug: mstore-checkout and load the template Mstore Api then try again
<img width="1643" alt="Screen Shot 2020-06-25 at 9 04 29 AM" src="https://user-images.githubusercontent.com/10402500/85645151-1414b200-b6c3-11ea-8128-3bd94af6d645.png">

**Comment by nseven7** [comment]
@minhtruong315 
![23422234](https://user-images.githubusercontent.com/57550221/85659428-1e48a780-b6e7-11ea-8ede-f74b4490adf5.PNG)

**Comment by minhtruong315** [comment]
Hi @nseven7 can u explain me? I dont understand your language.
Thanks

**Comment by nseven7** [comment]
@minhtruong315 The problem is that it doesn’t transfer me to the site with payment, but throws it on my site to confirm payment

**Comment by nseven7** [comment]
@minhtruong315 Why do you reply by day? It is very uncomfortable. Of course, I understand that you are helping others, but I will answer you right away

**Comment by minhtruong315** [comment]
Can u share me your source code via email: minhtruong315@gmail.com? I will check on my end first.

**Comment by nseven7** [comment]
@minhtruong315  im wait second day

**Comment by minhtruong315** [comment]
Hi @nseven7 can u give me your skype. i will contact u. I dont see any email.
Thanks

**Comment by nseven7** [comment]
@minhtruong315 trafafafafafa@gmail.com

**Comment by minhtruong315** [comment]
@nseven7 I ping you on the skype. pls check
Thanks

**Comment by minhtruong315** [comment]
Hi @nseven7 Fluxstore supports some native payment methods such as: paypal, razorpay, tap. For other payment methods, you can use EnableOnePageCheckout or NativeOnePageCheckout.
Thanks
