### ISSUE TITLE
Can i use Polylang for translation or any free translator 

### ISSUE THREAD

**Issue by osamasparky** [inspireui/support#386]
MStore Multi Vendor 
Purchase code: da4e5510-501d-456f-9d1d-fbbcdd24f102

**Describe the issues**
First : please need to start building my app and you delay for answering . and fixing cebuilder .
second :  wpml in not free plugin for translation - can i use Polylang  or what else you recommend

**Comment by minhcasi** [comment]
Hi @osamasparky, the Polylang is not supporting on current version, thank you!

Our team is checking and Cebuilder issues and will get back you shortly
