### ISSUE TITLE
Running Gradle task 'assembleDebug'... 

### ISSUE THREAD

**Issue by solarwebbrasil** [inspireui/support#3861]
Currently has 
Debian Operating System 10.4
openjdk-11-jdk
Android-studio 4.0
Flutter 1.17.4
Dart VM version: 2.8.4 (stable)
FluxStore-woo 1.7.5

I need help to run my FluxStore Woocommerce app, I couldn't get it to work at any time, I tested it with enough versions of android-studio, Flutter, Dart, Openjdk, in none of the options I was successful, I found several tutorials on the internet reporting the same problem , unfortunately they had no effect.

My problem is

Launching lib/main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app_settings:compileDebugAidl'.
> Failed to find Platform SDK with path: platforms;android-R

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 43s
Exception: Gradle task assembleDebug failed with exit code 1
![Captura de tela de 2020-06-23 02-18-24](https://user-images.githubusercontent.com/67305684/85363906-65247a80-b4f8-11ea-8f80-5fa51877a71a.png)

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by solarwebbrasil** [comment]
For new apps flutter is running !
![Captura de tela de 2020-06-23 15-41-34](https://user-images.githubusercontent.com/67305684/85448297-ee759480-b56c-11ea-8e83-609d3faa3ba7.png)

**Comment by solarwebbrasil** [comment]
I try to run the app without any changes, just download the code and open a new project, the error persists.

Best regards

**Comment by minhcasi** [comment]
@solarwebbrasil - could you help to check the solution on this ticket #3708 ?

**Comment by solarwebbrasil** [comment]
The change was made and the problem was solved.
Thank you very much.
