### ISSUE TITLE
Mstore Pro 4.0 build failed error

### ISSUE THREAD

**Issue by ArifAnwar07** [inspireui/support#3862]
@minhcasi  i have error in mstore pro 4.0 when i builed i got error 
this is screen shot
![IMG_20200623_105000](https://user-images.githubusercontent.com/67143715/85364098-097ddf80-b540-11ea-8c31-a6a0e8abc448.jpg)

i have already verify my purchse proof.

**Comment by minhcasi** [comment]
@luyx2412 - pls help with investigating 

verify from previous ticket #3802

**Comment by luyx2412** [comment]
Hi @ArifAnwar07 The first please follow the document and setup empty project React native https://reactnative.dev/docs/environment-setup after that come back the Mstore project and run again.

Thanks

**Comment by ArifAnwar07** [comment]
Hello sir @luyx2412  have solved my previous  issue??

**Comment by ArifAnwar07** [comment]
hii @luyx2412  sir  i have follow react native setup then run Mstore pro project i got thi error  * What went wrong:
Execution failed for task ':app:bundleReleaseJsAndAssets'.
> Process 'command 'npx.cmd'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights. Because of jsconfig.json error please help me to solve this problem

![eror  jpg](https://user-images.githubusercontent.com/67143715/85504909-a907a480-b60a-11ea-9675-50b1b1ae2a08.jpg)

**Comment by luyx2412** [comment]
Hi @ArifAnwar07 Please send me your Config file again, and mention your issue id is `3862`. I could not login with old username and password to create new consumer key which need to test.

Thanks

**Comment by ArifAnwar07** [comment]
my msstore 3.9.8 config file 
[appconfig.zip](https://github.com/inspireui/support/files/4826217/appconfig.zip)
and my issue id is #3802   and my username = is fastykart@gmail.com
pass= khanahil499 i hope issue will be fix...
thank you in advance.

**Comment by luyx2412** [comment]
Hi @ArifAnwar07 Sorry about delete your comment, please do not share your information in there. So please send email via inspireui.team@gmail.com

Thanks

**Comment by ArifAnwar07** [comment]
@luyx2412  i have mailed you all things that you  have asked please check  and fix the issue 
Thank you.

**Comment by ArifAnwar07** [comment]
@luyx2412  hello sir, 
Hiw many days you take to solve the issue please tell me i m very depressed.

**Comment by ArifAnwar07** [comment]
Sir i have a new issue @luyx2412  In my country phone no start +91 9876543210 and i want this app only for india not for all country so please help me to custmize it... Thi is screenshot 
![IMG_20200627_081248](https://user-images.githubusercontent.com/67143715/85912994-85cd3700-b84e-11ea-92de-ccd1c057ff12.JPG)

**Comment by luyx2412** [comment]
Hi @ArifAnwar07 In Config.js file line 355. Please change your `countryCode: [YOUR_COUNTRY]`, and change`hideCountryList: true` to hide the country list. 
We are using the phone number based on this library https://github.com/benhurott/react-native-masked-text. So please read the document to change your option.

Thanks

**Comment by ArifAnwar07** [comment]
@luyx2412  sir have you solved my previous issue??????????

**Comment by luyx2412** [comment]
HI @ArifAnwar07 Can you send me AppConfig.json and Config.js file again with the title 3862. I used old config and it not work. And sorry about inconvenience.

Thanks

**Comment by ArifAnwar07** [comment]
hi @luyx2412  sir i have mailed you my config.json file please check it i have also attach  my config file here 
[appconfig.zip](https://github.com/inspireui/support/files/4842392/appconfig.zip)

**Comment by ArifAnwar07** [comment]
hi @luyx2412 sir i want Home cattegory layout like this 
![Screenshot_20200630_124251](https://user-images.githubusercontent.com/67143715/86095623-d56e6580-bacf-11ea-874a-2d17fe65f287.jpg)
not circle cattegory.
please help  me how to custmize home cattegory layout

**Comment by luyx2412** [comment]
Hi @ArifAnwar07 Currently we did not support about it. You can edit the circle in `components/HorizonList/Categories/index.js`.

Thanks

**Comment by ArifAnwar07** [comment]
@luyx2412  ok sir but have you solved my previous  issue please tell me

**Comment by ArifAnwar07** [comment]
hi @luyx2412  Sir,
Is it possible in side menu cattegory show with icon  
![Screenshot_20200702_135933](https://user-images.githubusercontent.com/67143715/86336205-2bc4db00-bc6d-11ea-92ee-f0ee2bf94bd8.jpg) please tell me.

**Comment by luyx2412** [comment]
Hi @ArifAnwar07 In `Config.js` file line `178` please change `isMultiChild: false` same the screenshot. The sidemenu will have the icon, after that based on the source code in `src/components/Drawer/DrawerDefault/index.js` to make icon.
![image](https://user-images.githubusercontent.com/8909619/86373749-f096cc00-bcad-11ea-8ea0-ec7654f308c2.png)

Thanks
