### ISSUE TITLE
NoSuchMethod Error Payment Method opencart, address filler

### ISSUE THREAD

**Issue by shamar112** [inspireui/support#3863]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: When reaching to payment after adding a product, getting NoSuchMethod the getter id was called on nulled. I have setup Paypal as on the youtube tutorial and manual, was working the first time but now gives the error. Tried clearing build n starting from scratch using fluxstore builder for drag n drop, disabled all payment methods, but still won't work. 

Also getting no shipping options so I disable shipping.

For google address filler it keeps saying "named location, tap to select this location" but when taped the address is not auto filled.

+ Product & version: Fluxstore Pro, v1.7.5
+ Flutter (or React Native) version: Flutter
+ Testing Device/Simulator: Samsung galaxy device and android emulator
+ Screenshot issues (drag the file to attach here): 
![Screenshot_1592895163](https://user-images.githubusercontent.com/44536258/85371537-fe9e5d00-b4f5-11ea-83d9-43028d6d7293.png)

![Screenshot_1592896657](https://user-images.githubusercontent.com/44536258/85372926-27275680-b4f8-11ea-96fb-b50573ad063b.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by shamar112** [comment]
I have free shipping set up for one specific country when I select the country in the app free shipping is not shown. When I set free shipping in opencart to all zones, it shows it the app. But I only want it for 1 zone which includes my country

**Comment by minhtruong315** [comment]
Hi @shamar112 
Can you fork from our git repo then invite me: minhtruong315@gmail.com? https://medium.com/@inspireui/how-to-upgrade-fluxstore-projects-by-using-git-cebde7489ea6
 I will help you check your issues 
Thanks

**Comment by shamar112** [comment]
@minhtruong315 I signed up for the gitlab but getting 404 error when I click the repo link, how do I request to access the Gitlab. user is shamar112

**Comment by minhtruong315** [comment]
@shamar112 invited. please check

**Comment by shamar112** [comment]
thanks, I got it, I also invited you to the forked project

**Comment by minhtruong315** [comment]
Hi @shamar112 I ran your source code. it's showing payment methods
![Simulator Screen Shot - iPhone X - 2020-06-25 at 09 40 53](https://user-images.githubusercontent.com/10402500/85647167-0f9ec800-b6c8-11ea-805d-4be9c6ff1c3d.png)

**Comment by minhtruong315** [comment]
@shamar112 please update google api key to use search address
<img width="1441" alt="Screen Shot 2020-06-25 at 9 43 29 AM" src="https://user-images.githubusercontent.com/10402500/85647327-6b695100-b6c8-11ea-803b-9429b9d08f2a.png">
<img width="1277" alt="Screen Shot 2020-06-25 at 9 42 56 AM" src="https://user-images.githubusercontent.com/10402500/85647339-758b4f80-b6c8-11ea-8d0d-6383efa55fcf.png">

**Comment by shamar112** [comment]
I see that but when I set enableshipping and enableaddress to false then the error shows.
My greater problem is it only shows flat rate shipping when flat rate shipping is set to all zones in opencart same for free shipping which I don't want because I use country zones. Imagine shipping your product to Germany for the same flat rate you use for your own country you will be losing because it's a high cost to ship to those countries the same with free shipping, that's why we use countries/zones.

The second issue I am having is address, if I place an order and look back in opencart the country and state fields are all blank so I won't know who bought the product and where they are located because only the street address is collected.

And this is why I disabled shipping and address in the app, so it shows that error. I also tried enableonepagecheckout but still no workaround. Please I really want this to work.

**Comment by minhtruong315** [comment]
Hi @shamar112 You can't not disable shipping, address when checkout in opencart.
Disable shipping, address only work for woo commerce.

**Comment by shamar112** [comment]
Aright, so how will I know my customer's country and state when they place an order? because only the street address and city is brought back to opencart backend. They are blank or it shows "Kerewan" I don't even know if that's a country because the default was Vietnam when the order was placed

**Comment by minhtruong315** [comment]
@shamar112 can u send me admin account via email: truong@inspireui.com
I will try to place the order and check admin site
Thanks

**Comment by shamar112** [comment]
sent with subject Ticket #3863 Admin account for opencart

**Comment by minhtruong315** [comment]
Hi @shamar112 add my skype: minhtruong315
I will help you check teamviewer
Thanks

**Comment by shamar112** [comment]
ok I have added you, do you have a time zone difference am Eastern -5

**Comment by SharafMHD** [comment]
Dear @shamar112 I have the same issue

**Comment by minhtruong315** [comment]
Hi @shamar112 what is your skype?

**Comment by shamar112** [comment]
its live:graysindustriesuno

**Comment by minhtruong315** [comment]
@shamar112 I added your skype. pls accept.
Thanks

**Comment by shamar112** [comment]
Yes i accepted

**Comment by minhtruong315** [comment]
supported via skype
