### ISSUE TITLE
[FluxStore Listing] Appbar in Categories does not changed

### ISSUE THREAD

**Issue by gokhand** [inspireui/support#3864]
Hi,

In the app, you can also check your own test Fluxstore listing app, when you got to the category and change the category top app bar section, the app bar hasn't been refreshed. The appbar name still the same, it should change when you change it over.

[http://dc-grup.com/test/category_issue.mp4](url)

You can find the video file you can see even we changed the category, contents in the page have been changed but not the appbar. It is misleading the user.

Is there any solution you can provide for this?

Thanks

**Comment by philipvu30** [comment]
Hi,

Please re-send the video as I cannot download it. 

Thank you.

**Comment by gokhand** [comment]
Have you copy-paste the URL itself http://dc-grup.com/test/category_issue.mp4

**Comment by philipvu30** [comment]
Hi,

Please replace these files:
- lib/widgets/[backdrop_menu.dart](https://github.com/inspireui/support/files/4823214/backdrop_menu.dart.zip)
- lib/screens/[products.dart](https://github.com/inspireui/support/files/4823211/products.dart.zip)

**Comment by gokhand** [comment]
Thanks it worked like a charm, one related issue though.
On the homepage events or some other category has "See All" button, when you go first in categories and the last one keeps, when you go to the homepage and click the category see all it shows in the header again the old state.

http://dc-grup.com/test/category_issue_2.mp4

Can you also have a look at that please?

Thanks

**Comment by philipvu30** [comment]
Hi,

Please replace these files.
- lib/models/product.dart [product.dart.zip](https://github.com/inspireui/support/files/4830345/product.dart.zip)
- lib/screens/products.dart [products.dart.zip](https://github.com/inspireui/support/files/4830350/products.dart.zip)
- lib/widgets/backdrop.dart [backdrop.dart.zip](https://github.com/inspireui/support/files/4830356/backdrop.dart.zip)
- lib/widgets/backdrop_menu.dart [backdrop_menu.dart.zip](https://github.com/inspireui/support/files/4830354/backdrop_menu.dart.zip)

**Comment by gokhand** [comment]
Thanks, it is working awesome now.

**Comment by sarankumar02** [comment]
hey guys.. I am new to flutter.. In the FluxStore app how do i change the appBar and splashscreen name.. it is really tough to go through the whole code yet i cant find a way how to change it. please help me
