### ISSUE TITLE
How to fix Social Login in iphone

### ISSUE THREAD

**Issue by mansoor88** [inspireui/support#3866]
Detail Issues: 

![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-06-23 at 16 43 35](https://user-images.githubusercontent.com/7188395/85399924-06e7ae00-b571-11ea-9474-7ca7388fde50.png)

I am facing issue of connecting social login in my ios version of app. The earlier issue in android is fixed in android it is working fine but in IOS i am facing this issue. I download the file GoogleService-Info.plist which is generated. But it still shows fstore.

https://github.com/inspireui/support/issues/2994

**Comment by minhcasi** [comment]
@mansoor88 - would you mind to check if you have follow this guide - https://medium.com/@inspireui/setup-facebook-login-for-flutter-apps-4e7bd031479d - thank you!

**Comment by mansoor88** [comment]
> @mansoor88 - would you mind to check if you have follow this guide - https://medium.com/@inspireui/setup-facebook-login-for-flutter-apps-4e7bd031479d - thank you!
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/ff5bd872091510a526f061b5700ea23c6c1cb107/68747470733a2f2f6d69726f2e6d656469756d2e636f6d2f6d61782f313230302f302a4171663976585335367a413033547378"><img alt="" height="14" src="https://camo.githubusercontent.com/a1c598ee8610a8cdb0e8bdbf112f3f1c77af25cb/68747470733a2f2f63646e2d7374617469632d312e6d656469756d2e636f6d2f5f2f66702f69636f6e732f66617669636f6e2d72656272616e642d6d656469756d2e33593678705a2d3046536457446e504d3368534249412e69636f"> Medium**[Setup Facebook Login for Flutter apps](https://medium.com/@inspireui/setup-facebook-login-for-flutter-apps-4e7bd031479d)**Greeting from InspireUI, this is the detail guide to clarify detail guidline to setup the Facebook login for the Fluxstore Projects, you…

Thanks for quick response. My facebook login solved. Kindly help me in the google login as well. The android is working fine on my end. Need to fix in ios.

**Comment by ameenbadri7** [comment]
use this guide to show you  google sign-in in IOS
https://medium.com/@inspireui/setup-google-login-for-flutter-apps-fedc58a490b8
and this video
https://www.youtube.com/watch?v=14ALBSwvV4E

if not working please give us a detailed issue.

**Comment by mansoor88** [comment]
> use this guide to show you google sign-in in IOS
> https://medium.com/@inspireui/setup-google-login-for-flutter-apps-fedc58a490b8
> and this video
> https://www.youtube.com/watch?v=14ALBSwvV4E
> 
> if not working please give us a detailed issue.
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/0e474c77cb831d4591d0e9ab279f145a94d71aa2/68747470733a2f2f6d69726f2e6d656469756d2e636f6d2f6d61782f3630312f302a6d4e51616b47434f4131505f48315a36"><img alt="" height="14" src="https://camo.githubusercontent.com/a1c598ee8610a8cdb0e8bdbf112f3f1c77af25cb/68747470733a2f2f63646e2d7374617469632d312e6d656469756d2e636f6d2f5f2f66702f69636f6e732f66617669636f6e2d72656272616e642d6d656469756d2e33593678705a2d3046536457446e504d3368534249412e69636f"> Medium**[Setup Google Login for Flutter apps](https://medium.com/@inspireui/setup-google-login-for-flutter-apps-fedc58a490b8)**Greeting from InspireUI, this is the detailed guide to clarify detail guidelines to set up the Google login for the Fluxstore Projects, you…
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/02fe572648463dc3fff7c8789e02d3f4c69bce62/68747470733a2f2f692e7974696d672e636f6d2f76692f3134414c425377765634452f6d617872657364656661756c742e6a7067"><img alt="" height="14" src="/yts/img/favicon_144-vfliLAfaB.png"> YouTube**[Setup Google Login and Facebook Login (Flutter E-Commerce App In 10 Minutes)](https://www.youtube.com/watch?v=14ALBSwvV4E)**Learn how to integrate Google Login and Facebook Login into your App on both Android and iOS. These are great features that supports users to sign in with a ...

This is done now. Would you please help me by refering article for apple login as well.

**Comment by mansoor88** [comment]
Also, I felt the config file showing the home screen is different than I provided in android device. Can anyone guide for its path if inside ios folder?

**Comment by minhcasi** [comment]
@mansoor88 - could I know what is your issues so far? Please also help to check this guide as well https://pub.dev/packages/flutter_facebook_login

**Comment by mansoor88** [comment]
Hi, Thanks for respond. My facebook and google login is done. Now i am looking for apple login which is available in app. I need to configure that.

> @mansoor88 - could I know what is your issues so far? Please also help to check this guide as well https://pub.dev/packages/flutter_facebook_login
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/c8aac9817108b9bec9f8beaed2bd5bfab62f1899/68747470733a2f2f7075622e6465762f7374617469632f696d672f7075622d6465762d69636f6e2d636f7665722d696d6167652e706e673f686173683d76673836723272336d62733632686976346c646f703069666535756d32673567">Dart packages**[flutter_facebook_login | Flutter Package](https://pub.dev/packages/flutter_facebook_login)**A Flutter plugin for allowing users to authenticate with native Android & iOS Facebook login SDKs.

**Comment by minhcasi** [comment]
@mansoor88  - pls try to check the step2 config on this link https://medium.com/smartters-studio/flutter-login-with-apple-3a98582f53a1 - also make sure to enable the Apple login from Firebase

We will update this missing guide on our document - thank you!

**Comment by mansoor88** [comment]
Ok i will update if face any issue. Let me read and check this.
> @mansoor88 - pls try to check the step2 config on this link https://medium.com/smartters-studio/flutter-login-with-apple-3a98582f53a1 - also make sure to enable the Apple login from Firebase
> 
> We will update this missing guide on our document - thank you!
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/693a577338b0286aaba15f192735e3b39343b9f3/68747470733a2f2f6d69726f2e6d656469756d2e636f6d2f6d61782f313032342f312a7a594c7951654d5442504c33374d4e32416c6f6f48772e6a706567"><img alt="" height="14" src="https://camo.githubusercontent.com/a1c598ee8610a8cdb0e8bdbf112f3f1c77af25cb/68747470733a2f2f63646e2d7374617469632d312e6d656469756d2e636f6d2f5f2f66702f69636f6e732f66617669636f6e2d72656272616e642d6d656469756d2e33593678705a2d3046536457446e504d3368534249412e69636f"> Medium**[Flutter : Login With Apple](https://medium.com/smartters-studio/flutter-login-with-apple-3a98582f53a1)**A simple integration of signIn with apple in flutter apps
