### ISSUE TITLE
Get category picture not just Name

### ISSUE THREAD

**Issue by sarbaz989** [inspireui/support#3867]
[+](https://prnt.sc/t4y1o2) Detail Issues:  I want show category picture and name from my woocommerce app its just get a name not category picture
+ Product & version: woocommerce flux store 
+ Flutter (or React Native) version:  flutter 1.17.2
+ Testing Device/Simulator:  real  phone 
+ Screenshot issues (drag the file to attach here): 
![Screenshot_8](https://user-images.githubusercontent.com/64475259/85400515-1673f080-b58b-11ea-984a-d4a8f92991d1.jpg)

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by sarbaz989** [comment]
submitted form

**Comment by ameenbadri7** [comment]
inside your 
`lib\config\config_ar.json`
you can see the 
```
{
      "layout": "category",
      "type": "icon",
```

you will have to put the new icons inside your assets folder or inside your Wordpress host and copy the ` icon image link`
and add it to your `config_ar.json` as following:
inside 
` "items": [
`
```
you will add icons from your host it will be like this:

```
{
        "category": 18,
        "image": "https://user-images.githubusercontent.com/1459805/62820029-2e679f00-bb88-11e9-80de-fdf115cfd942.png",
        "colors": [
          "#3CC2BF",
          "#3CC2BF"
        ],
        "originalColor": false
      },
```
you if you add icons from your assets folder it will be like this:
```

{
          "category": 59,
          "image": "assets/icons/categories/ic_tie.png",
          "colors": [
            "#3E6AB5",
            "#3E6AB5"
          ]
        },
```
if you open any config files you will find those. and please read the [documentation ](https://docs.inspireui.com/fluxstore/config/)for more info about anything inside the fluxstore.

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one with full information - thank you for your time!
