### ISSUE TITLE
Woocommerce Product variants (size) are missing 

### ISSUE THREAD

**Issue by suri1980** [inspireui/support#3869]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 

I've successfully configured and customized for my store. But the only problem is that the product variants are not coming as expected. Not sure what i'm missing here. Please find the screens below 

+ Product & version:

Fluxstore WooCommerce - Flutter E-commerce Full App
Version: 1.7.5

+ Flutter (or React Native) version: 

Flutter 1.17.4 •
Tools • Dart 2.8.4

+ Testing Device/Simulator: 

Google Pixel3 (simulator)
Nexus 7 (android)

+ Screenshot issues (drag the file to attach here): 

**App Screens**

![Screenshot_1592915327](https://user-images.githubusercontent.com/1085817/85405025-64d8bd80-b592-11ea-9534-e556ebdca6e9.png)
![Screenshot_1592916098](https://user-images.githubusercontent.com/1085817/85405031-673b1780-b592-11ea-964c-8619ecf492c2.png)

**Code** 
![productsvariants](https://user-images.githubusercontent.com/1085817/85405320-d1ec5300-b592-11ea-8428-9656cf570ca4.png)

**Wordpress**

![productvariants2](https://user-images.githubusercontent.com/1085817/85406133-eed55600-b593-11ea-9f88-60450c211294.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by ameenbadri7** [comment]
could you please use this guide to set up the fluxstore woocommerce variants products and also the attributes.
[link](https://docs.inspireui.com/fluxstore/config/#4-const-productvariantlayout
)
that main idea is to setup:
1- change you product to Product Variant and add attributes to it and also price and quantity for every product Variant.
2- add your attributes  `lib\common\config\products.dart` 
in these fields: 
`const ProductVariantLayout `
`const kProductVariantLanguage
`
if you have multiples languages please download WPML plugins as in this link
[link](https://docs.inspireui.com/fluxstore/config/#6-const-kadvanceconfig
)

and please read the documentation for more info about any thing.

**Comment by minhcasi** [comment]
@suri1980 - try to check the setting from inventory as well - https://tppr.me/k0znA

**Comment by suri1980** [comment]
@ameenbadri7 @minhcasi , thanks for your replies and suggestions, I able to find the root cause and did few code changes to get the attributes to display in the product screen.

1. The problem is with my woocommerce product attributions, **Visible on the product page** was not been checked for all of my store products
![fluxstore-fix1](https://user-images.githubusercontent.com/1085817/85773839-d6f70100-b750-11ea-864d-66a60254818a.png)

then i've tried fix (auto enable always) this in woocommerce side but unable do that, then i tried to fix (customize) this in flux store code just to meet my requirement.

![image](https://user-images.githubusercontent.com/1085817/85776873-b11f2b80-b753-11ea-8bb0-2e1b9ecb251a.png)

And now i'm seeing the attributes.

![Screenshot_15931103471](https://user-images.githubusercontent.com/1085817/85779815-9306fa80-b756-11ea-8bad-f0fb5aa262e9.png)

-Thank you.
