### ISSUE TITLE
CeBuilder Blank Screen

### ISSUE THREAD

**Issue by hixoldev** [inspireui/support#387]
**Mandatory Info (please complete the following information):**
 - Product: [e.g. BeoNews]
![cebuilder](https://user-images.githubusercontent.com/47609348/54125687-7cd11000-4427-11e9-8d51-0631567e7e9e.PNG)

**Describe the issues**
After Installing Cebuilder, it open up with a blank screen.

**Screenshots**

**Comment by minhtruong315** [comment]
Can you add my skype: minhtruong315. I will help you check it via teamviewer

**Comment by hixoldev** [comment]
Hi,

Thank you for your response, i have sent you skype request from
imtiazahmad07.

**Comment by minhcasi** [comment]
@hixoldev - please try with latest cebuilder 0.27 - thanks
