### ISSUE TITLE
Login Screen

### ISSUE THREAD

**Issue by boqaqa** [inspireui/support#3871]
Hi I would like to replace the Main Login screen with SMS Signup screen only like shown in the picture? I mean that I want every time a user wants to Sign in he must verify his number, Without putting his Username or Password and thanks.

![purchase pic](https://user-images.githubusercontent.com/65863900/85425929-7dd97280-b582-11ea-8288-4a0ad9cb1a6c.jpg)
Remove this Page.
![login](https://user-images.githubusercontent.com/65863900/85425933-7e720900-b582-11ea-8bb0-91db0a6b0cb2.jpg)
Replace with this Page.
![sms](https://user-images.githubusercontent.com/65863900/85425930-7dd97280-b582-11ea-94be-9eebb17716e1.jpg)

**Comment by ameenbadri7** [comment]
please go to` lib\common\config\general.dart` file and type `True `for show or `false `for not show.

const kLoginSetting = {
  "IsRequiredLogin": false,
  'showAppleLogin': false,
  'showFacebook': false,
  'showSMSLogin': true,
  'showGoogleLogin': false,
};

thank you

**Comment by minhcasi** [comment]
@boqaqa - try to return the LoginSMS as default - thank you!

<img width="954" alt="Screen Shot 2020-06-24 at 09 40 13" src="https://user-images.githubusercontent.com/1459805/85492024-b61e9680-b5fe-11ea-84e5-3fa62660e96f.png">

**Comment by boqaqa** [comment]
Thank you very much @minhcasi . You are really genius , I Like you :1st_place_medal: 
I also appreciate to @ameenbadri7 for trying, but that is not what I wanted.

**Comment by minhcasi** [comment]
@boqaqa - We're glad that it help, please give us some feedback/rating to this page https://codecanyon.net/downloads  if the product is helpful for your business, we are working hard to update more awesome and powerful features on next coming version release. Let us know if you have any feedback. Thank you very much 😊
