### ISSUE TITLE
Error uploading app

### ISSUE THREAD

**Issue by miskayapp** [inspireui/support#3872]
I get this error while trying to archive on xcode

Standalone embedder initialization failed: Error determining current directory: Operation not permitted

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
@miskayapp - as discussed there is no issue with your app build script - pls make sure to try this step

```
flutter clean
flutter pub get
flutter build ios
// open xcode and run archive
```

Thanks

**Comment by miskayapp** [comment]
but why am i getting this errors? i have run 
" flutter clean
flutter pub get
flutter build ios"
a millioin times, same error
