### ISSUE TITLE
Fluxstore 1.7.5 Icon's text / title is not showing properly

### ISSUE THREAD

**Issue by aishema2000** [inspireui/support#3873]
Dear Support,

I have a problem with the icon's text that doesn't show in full. Please see attached screenshot:
![WhatsApp Image 2020-06-23 at 18 01 11](https://user-images.githubusercontent.com/15066381/85428255-30a6d200-b57d-11ea-9d2c-1023db758949.jpeg)
As you can see the last icon on the first row should be "Made in Rwanda" but it only display "Made", the first icon on the second row should be "Health & Beauty" but it only shows "Health".

i attach here my config_en.json file
[json_en.txt](https://github.com/inspireui/support/files/4820610/json_en.txt)

How do I correct this?

NB: if you need to verify my purchase code, please refer to my first issue please see my first issue here: https://github.com/inspireui/support/issues/2458

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by aishema2000** [comment]
It is done boss....., the form has been submitted. Please note it is very frustrating to have to go through this process everytime we need support. Please help me to solve my issuem thanks

**Comment by ameenbadri7** [comment]
sorry to hear that. 
this will not happen in the future sorry it's my mistake. 

about the issue :

you can try to edit the file `lib\widgets\home\category\category_icon_items.dart`

inside ` line 124`
you can edit the text 
`   child: Text(
                        name,
                        style: TextStyle(
                          fontSize: kLayoutWeb ? 18 : 10.6,
                          fontWeight: FontWeight.w600,
                          color: Theme.of(context).accentColor,
                        ),
                        maxLines: 1,
                        textAlign: TextAlign.center,
                      ),`

and change the max lines: to 2 lines instead of 1.
and you can also change  ` textAlign`: from the center to
`TextAlign.left,`

please let me know if you have other problems I will help.

**Comment by minhcasi** [comment]
@aishema2000 - pls help us to move your all conversation to the same open ticket #3888
