### ISSUE TITLE
add-ons in flutter proyect

### ISSUE THREAD

**Issue by mercadocerouno** [inspireui/support#3874]
I want to know if in flutter project can add (add-ons  for woocommerce)
https://berrysalads.com/producto/small-2/

<img width="1440" alt="Screen Shot 2020-06-23 at 9 55 01 AM" src="https://user-images.githubusercontent.com/66270970/85432449-d9324300-b537-11ea-9ef4-c5e235b9737b.png">

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
@mercadocerouno - sorry the current release is not supported for Product Add-on - this feature is still on our backlog and will be investigated and update later - thank you for your question :)

**Comment by mercadocerouno** [comment]
ok, and dont have an estimated when that feature its gonna be released
