### ISSUE TITLE
Change button colors

### ISSUE THREAD

**Issue by mercadocerouno** [inspireui/support#3875]
How can i change the button colors

<img width="331" alt="Screen Shot 2020-06-23 at 11 45 07 AM" src="https://user-images.githubusercontent.com/66270970/85444764-8791b480-b547-11ea-94b9-22ccf0326911.png">

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
@mercadocerouno - pls check this guide https://docs.inspireui.com/fluxstore/customization/#5-app-main-color
