### ISSUE TITLE
Flutter Upgrade Problem

### ISSUE THREAD

**Issue by MorisTech** [inspireui/support#3876]
My issue is here

https://github.com/inspireui/support/issues/3854

No response

This is my error when I run flutter run

Running Gradle task 'assembleDebug'...

Compiler message:

lib/widgets/firebase/one_signal_wapper.dart:10:9: Error: The getter 'kOneSignalKey' isn't defined for
the class 'OneSignalWapper'.

 - 'OneSignalWapper' is from 'package:fstore/widgets/firebase/one_signal_wapper.dart'
 ('lib/widgets/firebase/one_signal_wapper.dart').

Try correcting the name to the name of an existing getter, or defining a getter or field named
'kOneSignalKey'.

    if (kOneSignalKey['appID'] != '') {

        ^^^^^^^^^^^^^

lib/widgets/firebase/one_signal_wapper.dart:22:13: Error: The getter 'kOneSignalKey' isn't defined for
the class 'OneSignalWapper'.

 - 'OneSignalWapper' is from 'package:fstore/widgets/firebase/one_signal_wapper.dart'
 ('lib/widgets/firebase/one_signal_wapper.dart').

Try correcting the name to the name of an existing getter, or defining a getter or field named
'kOneSignalKey'.

            kOneSignalKey['appID'],

            ^^^^^^^^^^^^^

lib/screens/settings/settings.dart:472:49: Error: The getter 'kDefaultSettings' isn't defined for the
class 'SettingScreenState'.

 - 'SettingScreenState' is from 'package:fstore/screens/settings/settings.dart'
 ('lib/screens/settings/settings.dart').

Try correcting the name to the name of an existing getter, or defining a getter or field named
'kDefaultSettings'.

**Comment by ameenbadri7** [comment]
did you add your OneSignalKey in `const kOneSignalKey`?
did you see the documentation in this [link ](https://docs.inspireui.com/fluxstore/firebase/#2-push-notifications-via-onesignal) ? 
please give us your feedback so we can help.

**Comment by MorisTech** [comment]
![error](https://user-images.githubusercontent.com/31305956/85453883-3eb41d00-b594-11ea-9390-a74840d83b42.PNG)

Here is my error

**Comment by MorisTech** [comment]
Do I need Onesignal?

**Comment by ameenbadri7** [comment]
if you don't one signal at all. and you are using firebase to provide notifications to your users its a good choice.

please remove those: 
inside 
`lib\app.dart
`
remove :
` OneSignalWapper()..init();
`
inside 
`lib\widgets\firebase\one_signal_wapper.dart
`
remove :
` // import 'dart:io' show Platform;

// import 'package:onesignal_flutter/onesignal_flutter.dart';

// import '../../common/config.dart';
// import '../../models/notification.dart';

// class OneSignalWapper {
//   init() {
//     if (kOneSignalKey['appID'] != '') {
//       Future.delayed(Duration.zero, () async {
//         bool allowed =
//             await OneSignal.shared.promptUserForPushNotificationPermission();
//         if (Platform.isIOS && allowed != null || !Platform.isIOS) {
//           OneSignal.shared.setNotificationOpenedHandler(
//               (OSNotificationOpenedResult result) {
//             print(result.notification
//                 .jsonRepresentation()
//                 .replaceAll("\\n", "\n"));
//           });
//           await OneSignal.shared.init(
//             kOneSignalKey['appID'],
//             iOSSettings: {
//               OSiOSSettings.autoPrompt: false,
//               OSiOSSettings.inAppLaunchUrl: true
//             },
//           );
//           await OneSignal.shared
//               .setInFocusDisplayType(OSNotificationDisplayType.notification);

//           OneSignal.shared
//               .setNotificationReceivedHandler((OSNotification osNotification) {
//             // print(osNotification.payload.body.toString());
//             // print(osNotification.payload.notificationId);
//             FStoreNotification a =
//                 FStoreNotification.fromOneSignal(osNotification);
//             a.saveToLocal(
//               osNotification.payload.notificationId != null
//                   ? osNotification.payload.notificationId
//                   : DateTime.now().toString(),
//             );
//           });
//         }
//       });
//     }
//   }
// }

`
inside `android\app\build.gradle` 

remove  
        // OneSignal-Gradle-Plugin
        // classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.12.6, 0.99.99]'

and also remove 
// apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'

if you don't want to remove please add `// `before the lines you want to `deactivate`.

please let me know if everything went fine.

**Comment by MorisTech** [comment]
Thanks man
Will try it now

**Comment by MorisTech** [comment]
![error](https://user-images.githubusercontent.com/31305956/85457544-13333180-b598-11ea-9bd5-1cb7583dd062.PNG)

I've done that, no more errors

Now I'm getting this

**Comment by ameenbadri7** [comment]
could you compare my file `lib\common\config\general.dart`
with your file.

[general.txt](https://github.com/inspireui/support/files/4821804/general.txt)

please don't send your `general.dart `file here because it contains secret things.

**Comment by MorisTech** [comment]
Okay I will

**Comment by MorisTech** [comment]
It's different, can I use your own file?
I'll rename it to .dart

**Comment by ameenbadri7** [comment]
Use it but change the values like the api secret keys. Please refer to this [link](https://docs.inspireui.com/fluxstore/config/)

**Comment by MorisTech** [comment]
I changed it, now i'm getting over 247 errors lol

**Comment by MorisTech** [comment]
![image](https://user-images.githubusercontent.com/31305956/85469933-3a90fb00-b5a6-11ea-9896-898d38602468.png)
here is another error again

**Comment by ameenbadri7** [comment]
If you are not using  fluxstore you can try to copy the same file from your original source code update ..
It will fix your problem.

**Comment by MorisTech** [comment]
what file am I copying?
I had 1.7.3 before

I had no problem but the Login system doesn't work
The Sign in doesn't work
I try to sign in as a vendor on the app, it just keeps rolling and all

I think I'll just go back to 1.7.3

**Comment by ameenbadri7** [comment]
Ok

**Comment by MorisTech** [comment]
So you can you kindly help me work on the 1.7.3

I'm trying to run it on my phone now to see if it works

**Comment by MorisTech** [comment]
![image](https://user-images.githubusercontent.com/31305956/85473147-b9883280-b5aa-11ea-9bcc-2815b8e7db5d.png)


The app installs successfully, but I have a problem with the sign in page

**Comment by MorisTech** [comment]
![image](https://user-images.githubusercontent.com/31305956/85474295-5c8d7c00-b5ac-11ea-9b79-4689fc294112.png)

This is what happens when I try to sign in with Google

**Comment by MorisTech** [comment]
Please help

All the changes I made in FLuxbuilder doesn't work too

**Comment by MorisTech** [comment]
Or can you just give me your source code and change the API keys, consumer keys and google-json file 
I've been battling this for a month now..

**Comment by MorisTech** [comment]
Who's going to help me on this project?
This thing isn't working

**Comment by MorisTech** [comment]
?????

**Comment by MorisTech** [comment]
> ![image](https://user-images.githubusercontent.com/31305956/85469933-3a90fb00-b5a6-11ea-9896-898d38602468.png)
> here is another error again

I'm still getting this error on version 1.7.5
What next?

**Comment by minhcasi** [comment]
@MorisTech - try to run `flutter clean`

The error is shown from the build folder, try to remove that folder and run `pub get`

Please compare with the default download package to see if you have change any config setting? Try to resend your latest config folder here so that we could help for checking

**Comment by MorisTech** [comment]
![Capture](https://user-images.githubusercontent.com/31305956/86957011-fa0eb100-c151-11ea-8f7c-cb8d564850fb.PNG)
I'm getting this error when I try uploading to google play

And also a language error

How do I fix it
