### ISSUE TITLE
Change intro screen and language

### ISSUE THREAD

**Issue by Khaled1979** [inspireui/support#3878]
how I can change intro screen and  add button to select the language when start the app before intro screen in mstore pro ?

**Comment by ameenbadri7** [comment]
مرحباً خالد. 

Hello khaled 
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
verified ticket - #3510

**Comment by luyx2412** [comment]
Hi @Khaled1979 In Config.js file line 149, you can change the content Intro screen
![image](https://user-images.githubusercontent.com/8909619/85569183-869e7700-b65c-11ea-81a7-c2cc7b3d616c.png)

Or edit in `src/components/AppIntro/index.js` file, and you can add Select language in this screen.

Thanks

**Comment by Khaled1979** [comment]
It is just change the colors i need to add photo

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by luyx2412** [comment]
HI @Khaled1979 Please read the document react native https://reactnative.dev/docs/getting-started, and understand it.
Because you want to edit which is not support this feature.

Thanks
