### ISSUE TITLE
Prestashop app is not functioning

### ISSUE THREAD

**Issue by avvvar** [inspireui/support#3879]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: hello , i have purchased the prestashop flutter app and configured it based on your instructions , but nothing is working except the app is unpinning empty 
+ Product & version: FluxStore prestashop
+ Flutter (or React Native) version: latest
+ Testing Device/Simulator: huawei p20 pro
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@vumanhsn97 - pls help with investigating - thank you!

**Comment by minhcasi** [comment]
@avvvar - would you mind to share the screenshot of the issues - thank you!

**Comment by avvvar** [comment]
here are
![WhatsApp Image 2020-06-24 at 15 33 51](https://user-images.githubusercontent.com/39483126/85557199-3c070580-b630-11ea-8da2-d7f534be9105.jpeg)
![WhatsApp Image 2020-06-24 at 15 33 52 (1)](https://user-images.githubusercontent.com/39483126/85557205-3d383280-b630-11ea-849f-298ff8e5d14d.jpeg)
![WhatsApp Image 2020-06-24 at 15 33 52](https://user-images.githubusercontent.com/39483126/85557208-3d383280-b630-11ea-8783-54949f305b50.jpeg)


 the screenshots

**Comment by vumanhsn97** [comment]
@avvvar 
Make sure you enable webservice api and check list permissions https://tppr.me/BNFx5

**Comment by avvvar** [comment]
@vumanhsn97 

i have enabled webservice api , and i am not sure what you mean by list permissions.
but i tried it even with my test server, it is the same.

**Comment by avvvar** [comment]
@vumanhsn97 

The reset API authorization issue is resolved, however it is the same i dont get anything but an error  see the screenshot
![aaa](https://user-images.githubusercontent.com/39483126/85677575-555f8e80-b6d0-11ea-9a15-da52adcf107a.jpeg)

**Comment by vumanhsn97** [comment]
@avvvar 
Can you send your website and webservice key to vumanhsn97@gmail.com?

**Comment by avvvar** [comment]
@vumanhsn97 

Sent

**Comment by vumanhsn97** [comment]
@gentianziu03 
Please reinstall this module: 
[customapi.zip](https://github.com/inspireui/support/files/4830510/customapi.zip)

**Comment by gentianziu03** [comment]
> @gentianziu03
> Please reinstall this module:
> [customapi.zip](https://github.com/inspireui/support/files/4830510/customapi.zip)

Same problem

**Comment by avvvar** [comment]
@gentianziu03 
 by adding the following to the .htaccess

`<IfModule mod_rewrite.c>
RewriteEngine on
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
</IfModule>
`

**Comment by vumanhsn97** [comment]
@gentianziu03 
Please check your email: https://tppr.me/mfVas
Thanks!

**Comment by avvvar** [comment]
Hi 
you sent me the the Lib from woo app , is that correct ?

**Comment by gentianziu03** [comment]
> Hi
> you sent me the the Lib from woo app , is that correct ?

no, i have send the lib from prestashop app

**Comment by avvvar** [comment]
The config file looks like this , why ?
<img width="583" alt="Screen Shot 2020-06-25 at 1 46 09 PM" src="https://user-images.githubusercontent.com/39483126/85707067-81d4d400-b6eb-11ea-91b6-33c8898b446a.png">

**Comment by gentianziu03** [comment]
> The config file looks like this , why ?
> <img alt="Screen Shot 2020-06-25 at 1 46 09 PM" width="583" src="https://user-images.githubusercontent.com/39483126/85707067-81d4d400-b6eb-11ea-91b6-33c8898b446a.png">
you misunderstood me, i have ticked #3898

and here are my config
![github](https://user-images.githubusercontent.com/46620232/85707565-9a40f080-b6e3-11ea-828f-1fa1b938a33c.JPG)

**Comment by avvvar** [comment]
@gentianziu03 
man this is my support ticked, i have issues same as you in prestashop app, please let us not make confusions and open a ticket for yourself or just follow here

**Comment by gentianziu03** [comment]
sorry, the .htaccess didn't work any another idea?

**Comment by avvvar** [comment]
@vumanhsn97 
thank you very much, now i have connection , but there are other issues, i will try to solve them 

otherwise i will get back to you here

**Comment by avvvar** [comment]
@vumanhsn97 
one more issue ,
when i add address and place the order, it will show below address in my backend and order not the entered one , also the order status is not shown in the app

John DOE
My Company
16, Main street
2nd floor
75002 Paris
France
0102030405

**Comment by avvvar** [comment]
@vumanhsn97 
Hi, there are many other issues in the app, shall i mention them all at once or one by one ?

**Comment by vumanhsn97** [comment]
@avvvar 
You can add it in this issue

**Comment by avvvar** [comment]
@vumanhsn97 
First issue 
-----------
one more issue ,
when i add address and place the order, it will show below address in my backend and order not the entered one , also the order status is not shown in the app

John DOE
My Company
16, Main street
2nd floor
75002 Paris
France
0102030405

<img width="430" alt="Screen Shot 2020-06-29 at 2 52 06 PM" src="https://user-images.githubusercontent.com/39483126/86001858-30448600-ba18-11ea-86c3-c070bbf4c1b3.png">



Second issue 
-----------------
let us say i have categories as following 

Men>top>shirts

the app does not show the products inside category Men or to  it only shows the end of category tree in this case shirts

you can try to display category number 3 in my store

![WhatsApp Image 2020-06-29 at 14 48 08](https://user-images.githubusercontent.com/39483126/86001504-a399c800-ba17-11ea-9675-307731a0d411.jpeg)


Third issue 
----------------
in category page it only shows the root category with banner the rest of categories are in text only 

![WhatsApp Image 2020-06-29 at 14 48 07 (1)](https://user-images.githubusercontent.com/39483126/86001497-a09ed780-ba17-11ea-8686-637b8c8de2f0.jpeg)


fourth issue 
-----------
in prestashop you can define a spesific shipping method to a specific product, but here it shows all the available shipping methods and it give 0 (free) to the disabled once 

![WhatsApp Image 2020-06-29 at 14 48 07](https://user-images.githubusercontent.com/39483126/86001502-a2689b00-ba17-11ea-8121-5604fa04a65e.jpeg)


fifth 
--------
there are some overflowed issue in the layout of products 
![WhatsApp Image 2020-06-29 at 14 49 44](https://user-images.githubusercontent.com/39483126/86001609-ccba5880-ba17-11ea-8301-93eb9849fedd.jpeg)


there are still more but let us fix these once first

**Comment by avvvar** [comment]
@vumanhsn97  i am still waiting

**Comment by vumanhsn97** [comment]
@avvvar 
It is working in progress. I fixed issues: 1, 2, 3. In issue 5, I can't get your list product because your webservices key in submit form is disable. Can you send your key to vumanhsn97@gmail.com?
Thanks!

**Comment by avvvar** [comment]
dear @vumanhsn97 

thank you very much for your support 

 there is good progress but still, there are some issues.

in the categories 
- the category banner or image is not displayed- the subcategories, for example, women-> clothes-> t-shirt is not displayed anywhere 
- in some categories, not all of the products are displayed for example category 12


in shipping methods 

two of my methods are always 0$ cost 



in products, I have this issue in most of the pages 
![WhatsApp Image 2020-07-04 at 05 08 17](https://user-images.githubusercontent.com/39483126/86503281-62a60880-bdb5-11ea-8be8-b06d00aaa313.jpeg)



I would like to go step by stem otherwise there are still other issues  such as non of the filtering is working

**Comment by avvvar** [comment]
@vumanhsn97 

thank you very much for your support 

I have replied to you in the email

**Comment by avvvar** [comment]
Dear @vumanhsn97 

I am still waiting for a reply to my latest email 

regards

**Comment by emanuelecolella** [comment]
With prestashop there are many issue

**Comment by avvvar** [comment]
Dear @vumanhsn97 

I was supposed to receive correction for my issues by this week, I haven't received it yet.

23 days ago I opened this ticket and still not solved

**Comment by vumanhsn97** [comment]
@avvvar 
Please download lastest version and update this permission in Webservices https://tppr.me/fGCgb
Thanks!

**Comment by avvvar** [comment]
Dear @vumanhsn97 

last time I received a version that contained stories, in your current update this feature is not included. 

in addition, I have requested the following fixes but it is still the same.

- sorting and filtering are not working.
- the order status is showing empty.

**Comment by vumanhsn97** [comment]
@avvvar 
Make sure your prestashop custom api version is 1.0.1 https://tppr.me/KiLui

**Comment by vumanhsn97** [comment]
@avvvar 
Can you share your admin account and backoffice to vumanhsn97@gmail.com?
It is working well in demo site.
Thanks!

**Comment by avvvar** [comment]
Dear @vumanhsn97 

Sent

**Comment by avvvar** [comment]
Hi @vumanhsn97 

I am still waiting for an update regarding the filtering issue

**Comment by vumanhsn97** [comment]
@avvvar 
Please follow this issue: https://github.com/inspireui/support/issues/4473#issuecomment-671759430
Thanks!

**Comment by avvvar** [comment]
I don't know why you closed the ticket, the issue is not solved yet, 

I followed the instruction in the mentioned ticket but now I get errors and the app won't even start 

Compiler message:
lib/services/prestashop.dart:477:32: Error: The method 'Prestashop.getShippingMethods' doesn't have the named parameter 'address' of overridden method 'BaseServices.getShippingMethods'.
  Future<List<ShippingMethod>> getShippingMethods(
                               ^
lib/services/index.dart:61:32: Context: This is the overridden method ('getShippingMethods').
  Future<List<ShippingMethod>> getShippingMethods(
                               ^
