### ISSUE TITLE
cannot change from CeBuilder

### ISSUE THREAD

**Issue by almleky** [inspireui/support#388]
**Mandatory Info (please complete the following information):**
 - Product: [e.g. MStore, ListApp]
 - Your Purchased Code: [get from https://codecanyon.net/downloads]
(we may not reply if you are not our customer)
Mstore Multi Vendors
**Describe the issues**
cannot change main color or not open customization page for Cebuilder 
also cannot add new payment gate way i have local API for web working now i already added but need for apps
**Screenshots**
attached 
![Screen Shot 2019-03-11 at 3 36 22 AM](https://user-images.githubusercontent.com/8718664/54126829-818ec780-4419-11e9-9541-478f478ec101.png)

**Additional context**
Add any other detail logs about the problem here.

**Comment by minhtruong315** [comment]
I am updating cebuilder to fix this issue

**Comment by almleky** [comment]
I need log in TeamViewer plz urgent to setup my apps thanks Skype almleky

**Comment by minhtruong315** [comment]
Pls update newest cebuilder to fix this issue. thanks

**Comment by almleky** [comment]
Now working but you can see the apps not working good see this link picture
not see also all functionality not working
https://expo.io/@almleky/alshadady-estore

**Comment by minhcasi** [comment]
@almleky - could you share the account login above expo link (as we are using ios), or take the screenshot of the issues here - sorry for late response as we missed this ticket

**Comment by lotfinoluffy** [comment]
same issue here

**Comment by minhcasi** [comment]
Hi @lotfinoluffy - please try to update the latest version to fix this issue - thank you!

**Comment by lotfinoluffy** [comment]
I did, have the CeBuilder-0.32 
and nothing
