### ISSUE TITLE
Update Banner without Change the Code

### ISSUE THREAD

**Issue by harjono-flux** [inspireui/support#3880]
Hello... Sorry if my ask is very basic. How to change the banner image and URL (action when end user click the banner) without change the code/ update/ reupload the program when the application already online in play store?

And how to reopen case when you closed? sometimes i got full activity, so 2-3 days later i reopen your reply 
Thx

#3833

**Comment by ameenbadri7** [comment]
Welcome harjono-flux. 
Sure you can do that by a simple move:  

You can set a fixed name for your images and then upload them to a specific folder called banner. 
Like : www.aminshop/wp-upload/banner/banner1.jpg

And then before you submit and build your app you change the banner to that link. 

And then you build the app and publishing to ios or google store. 

And then when you want to replace the images you should only go to your hosting website and then just replace the jpg image with other images with the same name. 

I do it like that sir. 
Thank you

**Comment by harjono-flux** [comment]
hooo ya i see, thx for ur quick respon.
how about the link? Example,  i use the banner for show the stuff in category 32, then i want update the banner to show stuff in category 33

**Comment by ameenbadri7** [comment]
Yes sure you can do that, you would have to change the categories ids for all products manually for all the shop 

`wp_terms
wp_term_relationships
wp_term_taxonomy`

And other stuff. 

So be prepare for a world of pain.

The best way if you like the fast way you have to will prepared your products categories from the beginning. 

nothing is impossible for the beautiful fluxstore team. 
Maybe one day you will publish your app updates without any rebuild with the fluxstore builder...

Have a good day.

**Comment by harjono-flux** [comment]
Hmmm... once more.
how about, change the url of product, like
first, banner A with url to show iphone X, then i want to update with banner B to show iphone 11.

**Comment by ameenbadri7** [comment]
Changing categories ids or urls need to manually editing the config files and rebuilding the app. 
But the images you can replace their names.  
If you have a new way please share it with me.

**Comment by harjono-flux** [comment]
hmmm... i understand. No, i have no ide, im not programer :) but the logic a little bit i can understand.
So, i think the top banner, for now, not suitable to display fast information that can be change 3-5 days, cause imposible make end user update their apps every 3-5 days

I dont know how hard it is, but i think this is the general/common feaure for apps.

**Comment by harjono-flux** [comment]
Hoo... i see... thx for the good information, unfortunately im not on my time to see the coding. Maybe 4-5 days later. You can closed the case if you want or you can wait me :)
Many thanks for ur fast response n way out for our problem

**Comment by ameenbadri7** [comment]
thank you @harjono-flux for your patients.
we will close this issue now and you can open a new issue any time.
