### ISSUE TITLE
Exception: Gradle task assembleDebug failed with exit code 1

### ISSUE THREAD

**Issue by macololiv** [inspireui/support#3881]
hello i finish to install the android studio and flutter doctor shows that everything is ok but when i run the test  app i got this message 

Launching lib\main.dart on sdk gphone x86 arm in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app_settings:compileDebugAidl'.
> Failed to find Platform SDK with path: platforms;android-R

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 2s
Exception: Gradle task assembleDebug failed with exit code 1

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@macololiv - could you check the solution on this similar issue #3708

**Comment by macololiv** [comment]
thank you solved
