### ISSUE TITLE
FluxStore MultiVendor : filter and sorting not working, after place order navigate to intro slider and more 

### ISSUE THREAD

**Issue by shubhamsurvase** [inspireui/support#3882]
**_Step 1 (require): describe detail issues & screenshots_**

1. sorting by Date, featured and on sale gives same list of products
 
![Screenshot_2020-06-24-11-40-49-79](https://user-images.githubusercontent.com/65527267/85507258-bd01d500-b60f-11ea-95bf-af4156095de5.png)

![Screenshot_2020-06-24-11-40-41-41](https://user-images.githubusercontent.com/65527267/85507459-05b98e00-b610-11ea-834e-edaecadd58db.png)
![Uploading Screenshot_2020-06-24-11-39-52-72.png…]()

2. i set default country as India but state are of different country
![Screenshot_2020-06-24-10-47-45-27](https://user-images.githubusercontent.com/65527267/85507532-24b82000-b610-11ea-8a1f-ac2b4bf88083.png)

3.After payment/cod of order ,go to home shows intro slides of app

+ Product & version: fluxstore multivendor version:1.7.3

+ Testing Device/Simulator:  API version 21

**Comment by minhcasi** [comment]
@shubhamsurvase - could you try to use the latest version `1.7.5` to fix these issue - thank you!

**Comment by shubhamsurvase** [comment]
i'm doing lots of changes in code so i can't update. i change lots of
screens UI

**Comment by shubhamsurvase** [comment]
When I'm trying to add a new product , it will give me "You must be a
seller to add a product

So what i do
.

**Comment by minhcasi** [comment]
@shubhamsurvase - pls check to see if you have login as Vendor account?

**Comment by shubhamsurvase** [comment]
yes , i login as Vendor that's why i'm able to see and add new products in
the app.

**Comment by minhcasi** [comment]
@shubhamsurvase - we have double-check the latest code and it is working fine on this feature, would you mind to share the video issue from your issue? Thank you!

**Comment by shubhamsurvase** [comment]
20200630_112221.mp4
<https://drive.google.com/file/d/13pG_wLYH04cKQxGdWomHdkME7u89MFnl/view?usp=drive_web>

**Comment by minhcasi** [comment]
i could not see the file - thanks

**Comment by shubhamsurvase** [comment]
Will you please check once again?

**Comment by shubhamsurvase** [comment]
in Categories, last category repeated some time.

**Comment by minhcasi** [comment]
@shubhamsurvase - pls try to compare the category model and service from the latest 1.7.5 and copy it manually to your project, it is already fix the duplicate issue on category - thank  you!
