### ISSUE TITLE
Add Local Area Code

### ISSUE THREAD

**Issue by boqaqa** [inspireui/support#3884]
Hello can I please add (Local Area code) before the Phone Number text Field Automatically like the Country code, Because some users don’t add their Local Area Code and they can’t receive SMS verification. 

252 is our Country Code
90 is our Local Area Code
And then User’s Number.

![purchase pic](https://user-images.githubusercontent.com/65863900/85512466-9ab58a80-b602-11ea-97e8-87e82a96a526.jpg)

![code](https://user-images.githubusercontent.com/65863900/85510920-b61f9600-b600-11ea-8938-c24125790140.jpg)

**Comment by minhcasi** [comment]
@boqaqa - we are using this library https://pub.dev/packages/country_code_picker it seems it does not support Area Code yet.

Please help post request feature to https://github.com/imtoori/CountryCodePicker/issues

**Comment by boqaqa** [comment]
Thank you @minhcasi I think I just found what I was looking for, I Edit the country code in flutter\.pub-cache\hosted\pub.dartlang.org\country_code_picker-1.3.14\lib\country_code.dart and added the Local Area Code.

List<Map<String, String>> codes = [
  {
    "name": "Soomaaliya (Golis)",
    "code": "SO",
    "dial_code": "+25290",
  },
];

![local area](https://user-images.githubusercontent.com/65863900/85592037-7aabb880-b64e-11ea-86bb-38bdf8cc9ab1.jpg)

Thanks once again for taking your precious time to help.

**Comment by boqaqa** [comment]
One more question please, Can you hide this window after tapping the country code because I have only one country in the list?
![local area](https://user-images.githubusercontent.com/65863900/85593136-6fa55800-b64f-11ea-8481-c8f05ff04558.jpg)

**Comment by minhcasi** [comment]
@boqaqa - you could try to customize the `country_code_picker` library by copy the source to flux store product - thank you!

**Comment by boqaqa** [comment]
Sorry I did not understand which file should I copy and where do I have to put it please? Should I copy the "country_code.dart" and where do I put it in flux store?

**Comment by minhcasi** [comment]
Hi, i think you need to copy the folder folder and move it into the internal widget to do the customization - thank you

<img width="609" alt="Screen Shot 2020-06-26 at 15 43 48" src="https://user-images.githubusercontent.com/1459805/85838477-d5b2ec00-b7c3-11ea-951b-8a171f7fe93d.png">
