### ISSUE TITLE
Couple of Questions

### ISSUE THREAD

**Issue by gupanant** [inspireui/support#3885]
Hi,
I have few questions regarding the plugin. This time I am using woocommerce plugin.

1. We have woocommerce subscription enabled on some products, how can we add this functionality in the app ? Also how can users manage their subscriptions within the app ?
2. For reviews we are using stamped.io, how can we implement that in the app?
3. Generally our product landing pages is custom design, is there any way to add condition for the custom landing page in the app and also store this configuration online so that it fetches the latest landing page from the website ?
4. Is there any way to setup abandoned push notification flow ?
5. We are using woofunnels as our checkout with post purchase upsells and orderbump. Can we include that in the app ?
6. Do you guys have a paid consulting service for all the above points?

Thanks

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by gupanant** [comment]
Done, verified.

**Comment by gupanant** [comment]
Any updates on this ?

**Comment by minhcasi** [comment]
@gupanant - sorry for the late response, we got your verified 

1. The subscription is not compatible with the Fluxstore app, but I think it is possible to customize the app to add more 
2. it may not compatible with the stamped.io, you may investigate show to connect with stamped platform API.
3. you could try to use the Fluxbuilder tool http://fluxbuilder.com/
4. It may available from the backend of Firebase or Onesignal to control the push notification features.
5. I'm not sure on this feature, you could try to enable this feature to `true` to test the payment via Webview https://tppr.me/CPozJ

Sorry, we are not supporting for customization at this time :)

**Comment by gupanant** [comment]
1. Any plans of adding subscription within the app ? 
2. I looked into flux builder but i was talking more about creating different landers for different products.
3. Do you have a guide for onesignal push notifications on how to integrate it. Can't really find it.
4. Webview for checkout worked great.

**Comment by minhcasi** [comment]
1. sorry we don't have exactly plan for this feature
2. thank you, do you mean the landing screen that allow to change the text/font/color... ?
3. pls check this guide https://documentation.onesignal.com/docs/flutter-sdk-setup
