### ISSUE TITLE
How Deactivate purchase code on mstoreapi plugin ?

### ISSUE THREAD

**Issue by Cheewingtan** [inspireui/support#3886]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: I use my purchase code activate on the staging server for testing ,now I want change it back to original server how I deactivate the code ?
+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@Cheewingtan - you could install the fluxbuilder tool http://fluxbuilder.com/ - there is the reset feature from build menu, or you could send a request to the email support@inspireui.com - thank you!
