### ISSUE TITLE
 Fluxstore MV 1.7.5 shows No product in categories

### ISSUE THREAD

**Issue by DanialRana** [inspireui/support#3887]
+ Detail Issues:  I was using FluxStore MV 1.7.3 it was working fine but categories loading was very slow , when i updated to v 1.7.5 its load time is good but now categories show up quickly but in categories says No product 
show up but its working fine in previous version , help me out i have tried all the things in documentation.
+ Product & version: Fluxstore MV 1.7.5
+ Flutter version: v1.17.4
+ Testing Device/Simulator: IOS 13.5 simulator iPhone 11 pro max
+ Screenshot issues (drag the file to attach here): 
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-06-24 at 17 04 14](https://user-images.githubusercontent.com/14982843/85526701-cce3de00-b63c-11ea-9c57-81b1bcc72e5b.png)
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-06-24 at 17 04 01](https://user-images.githubusercontent.com/14982843/85526740-d5d4af80-b63c-11ea-9fae-a50e61a016b1.png)

And should i submit your ticket here  as. proof of purchase ?

**Comment by minhcasi** [comment]
Yes, please send via this form http://verify.inspireui.com

**Comment by DanialRana** [comment]
i have verified it , now can you help me out. i have been stuck in this issue

**Comment by minhcasi** [comment]
@philipvu30 - please help to investigate the issue - thank you!

**Comment by philipvu30** [comment]
Hi,

You didn't say how you got that bug. I tested your config files and all is fine except the banners.
You assigned the banners as category 313, 537, and 538 but your website doesn't have those category's ids.

Please have a check and modify them to your preferred category's ids. 
Thank you.

**Comment by philipvu30** [comment]
Closed as no response in 2 days. 

If you are happy with our services/support, would you mind rating us on your [download page](https://codecanyon.net/downloads)?
We truly appreciate your help.
