### ISSUE TITLE
App Build provides a lot of errors 

### ISSUE THREAD

**Issue by aishema2000** [inspireui/support#3888]
The Build using VS code gives hundreds of errors that look like this 
![image](https://user-images.githubusercontent.com/15066381/85527962-a8bbd900-b60b-11ea-9e17-3f6126ebba65.png)

I did Flutter packages get, packages upgrades, pub get, clean, doctor, etc... but no solution

When the app is open and i try to click on a product nothing is opened and console gives this screen:
![image](https://user-images.githubusercontent.com/15066381/85531631-3b11ac00-b60f-11ea-804f-588e1e68a754.png)

Nothing can't be done. Please note this is happening with your own demo. And I am using latest Flutter SDK i also tried to downgrade flutter but errors are still there.

What can I do to solve this issue?

Thanks.

Proof of purchase? See Ticket #3151

**Comment by ameenbadri7** [comment]
please try to use a fresh latest fluxstore source code.
then use this [gits](https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1). it's about the common issues on Flutter and solutions to fix. 
that will fix your all files errors.

from the screenshot, I can see that the problems are from the build folder.
to remove it do from your terminal: flutter clean.

```
C:\SRC\fluxstore1.7.5>flutter clean
Deleting build...                                               15,852ms (!)      
Deleting .dart_tool...                                               8ms
Deleting Generated.xcconfig...                                       2ms
Deleting flutter_export_environment.sh...                            1ms
```

if the build folder not removes try to remove it manually by deleting the build folder.

tell us if you still have this problem or write a comment if you solved this issue to close it.

**Comment by aishema2000** [comment]
Dear @minhcasi please dont close ticket because issue has not been answered.

Dear @ameenbadri7 please take time to read full message before answering:
1. The flutter commands you are giving me i said very well in my message above that i run them before posting support request. 

**UPDATE: When i open in android studio i don't see build error.

2. You did not answer my second issue which is very URGENT. Again see the second screenshot. This happens when i open category list and click on any product:
![85531631-3b11ac00-b60f-11ea-804f-588e1e68a754](https://user-images.githubusercontent.com/15066381/85733405-7342e880-b6fc-11ea-89b9-29a4c9613f92.png)

Please help me to solve and dont close before we get a solution. Thank you.

**Comment by ameenbadri7** [comment]
Could you help to share your lib/common and lib/config folder to our privet link  http://verify.inspireui.com
so that we could help with investigating.
- thank you!

**Comment by aishema2000** [comment]
Dear @ameenbadri7 I have submitted common and config folder. 

**IMPORTANT NOTE:** Please, remember that you instructed me to modify lib/widgets/frameworks/wcfm/index.dart like this, i don't know if they are related:

`@override
  Product updateProductObject(Product product, Map json) {
    if (json["store"] != null && json["store"]["vendor_id"] != null) {
      product.store = Store.fromWCFMJson(json["store"]);
    }
    return product;
  }`

See ticket #3683

Waiting for your answer. Thanks

**Comment by minhcasi** [comment]
assign back to @minhtruong315 to check more on the impact - thank you!

**Comment by aishema2000** [comment]
Thank you @minhcasi but please act fast, three months now without being able to publish my app. It is heartbreaking.

**Comment by minhtruong315** [comment]
@aishema2000 add my skype: minhtruong315
I will help u check via teamviewer

**Comment by aishema2000** [comment]
Hello I have added you on skype, my ID is: aishema  and I am waiting for you reply. I will stay online until you connect. Thank you

**Comment by aishema2000** [comment]
Hey @minhtruong315 any progress so far? Any good news? :)

**Comment by minhtruong315** [comment]
Hi @aishema2000 I'm working on fixing shipping methods on Fluxstore vendor. I will send you updates when it finish
Thanks

**Comment by aishema2000** [comment]
Please @minhtruong315 do not close this issue because the shipping methods still can not be shown. I am really really very frustrated. **This is the 3rd month** trying to launch my app in vain. See below screenshot (error produced with your own code, without me changing anything).
![image](https://user-images.githubusercontent.com/15066381/86510639-c8b08100-bdf1-11ea-9b65-8cf5825c916f.png)
![image](https://user-images.githubusercontent.com/15066381/86510645-dd8d1480-bdf1-11ea-899e-afd52f0aa56f.png)

@minhcasi 

PLEASE PLEASE HELP ME TO LUNCH MY APP.

**Comment by aishema2000** [comment]
Any good news? I am stuck on this issue. Can't select shipping method

**Comment by minhtruong315** [comment]
@aishema2000 I'm checking

**Comment by minhtruong315** [comment]
Hi @aishema2000 I send you updates via your skype. please check and let me know
Thanks

**Comment by aishema2000** [comment]
Thank you so much @minhtruong315 . Now I can checkout, choose shipping method and order is well received in backend. Again, thank you for your kind, professional and dedicated support. God Bless!!
