### ISSUE TITLE
Caching categories 

### ISSUE THREAD

**Issue by bigbossmaher** [inspireui/support#3889]
hello 
I noticed that even the isCashing is enabled , the categories name took very long time to be loaded 
Is there any trick to cache them or to set their  names under the icons manually by config_en.json 

I will accept any solution 
![SmartSelect_20200624-102818](https://user-images.githubusercontent.com/15154710/85529997-7effb380-b605-11ea-9ff1-9d5c1865da01.jpg)

 
![Screenshot_20200624-102924](https://user-images.githubusercontent.com/15154710/85530158-a0609f80-b605-11ea-9dc9-c7ddfaf97645.jpg)

**Comment by minhcasi** [comment]
@bigbossmaher - please move your conversation to #3857
