### ISSUE TITLE
How to show order total on success.dart

### ISSUE THREAD

**Issue by macquack** [inspireui/support#3890]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
I use OnePageCheckout then redirect to success.dart everything work fine but i want to show Total on this page below order number. i already add 
`Tools.getCurrecyFormatted(order.total),`
but doesn't work it show 0$
+ Product & version: Fluxstore 1.7.4
+ Flutter (or React Native) version:  1.7.1
+ Testing Device/Simulator: Nexus 2
+ Screenshot issues (drag the file to attach here): 
![image](https://user-images.githubusercontent.com/30103694/85541112-e9cee000-b641-11ea-85f7-72e6c045d006.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**
already submit

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by macquack** [comment]
also try this but it show #null
`"#${order.total}",`

**Comment by minhcasi** [comment]
@macquack - you could get the Total Cart from previous screen

**Comment by macquack** [comment]
yeah previous screen show everything but it possible to show the total or other information on this. 
because my site use direct bank transfer. then when landing success.dart it should show order total 
(i already add button to link my bank transfer confirm page)

**Comment by minhcasi** [comment]
you could add this param to OrderedSuccess and display the total string on the success order screen

<img width="1178" alt="Screen Shot 2020-06-27 at 18 10 21" src="https://user-images.githubusercontent.com/1459805/85920846-788d6800-b8a1-11ea-9cd2-81207e6632d0.png">

**Comment by minhcasi** [comment]
Please note that this customize is not include from our support scope, but pls try above solution 👍

**Comment by macquack** [comment]
appreciate for your kindness so I already add 
`totalOrder: cartModel.getTotal(),` on index.dart

then add
`
Line :18 final double totalOrder;
Line :56 OrderedSuccess({this.order, this.isModal, this.controller, this.totalOrder,});
`

it's doesn't work still show 0 usd
