### ISSUE TITLE
Categories are not being added to the app from woo commerce - MstorePRO

### ISSUE THREAD

**Issue by stagedoor16** [inspireui/support#3892]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: I only have 2 product categories on the category screen. From Woocommerce
+ Product & version: MstorePro - "3.9.8"
+ Flutter (or React Native) 
version: react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
+ Testing Device/Simulator: Android studio - AVD
+ Screenshot issues (drag the file to attach here): 
![image](https://user-images.githubusercontent.com/66263784/85573056-73c07e00-b62d-11ea-9e5a-00bcf38f7d5d.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by stagedoor16** [comment]
So when i change the category layout it displays all of my categories
![image](https://user-images.githubusercontent.com/66263784/85586185-9b691380-b638-11ea-910c-8bc0f21a1320.png)

Although it does not show ampersands would it be better to just use the word "and"]


Also is it possible to pick and choose which categories are shown eg only high level categories

**Comment by stagedoor16** [comment]
although it seems the categories only display when it is as text and not an image

**Comment by stagedoor16** [comment]
![image](https://user-images.githubusercontent.com/66263784/85588540-ae7ce300-b63a-11ea-8b2b-3d4a0518ad36.png)

the side bar categories

the side menu categories on category page

![image](https://user-images.githubusercontent.com/66263784/85588671-ce140b80-b63a-11ea-9f90-3580eb5a54bb.png)

**Comment by stagedoor16** [comment]
I would also like to add my product brands and tags is this possible

**Comment by ameenbadri7** [comment]
you can config your woocommerce categories to be without a parent.

<img width="960" alt="category parent" src="https://user-images.githubusercontent.com/37524186/85624319-65488580-b672-11ea-9023-41c3266c9629.png">

the black circle is the parent and the red circle is the children. 
because fluxstore only supports one parent to be showing inside the app.

in then you can go to your config_xx.json file inside `lib\config\config_ar.json`

and then you can config your banner and products list as following: 

 {
      "name": "Woman Collections",
      "image": "",
      "layout": "threeColumn",
      "category": you_category_id, 
"tag": you_tag_id, show product with this tag from the category id you choose.
 "featured": true, // or false to show only featured product for the category id you choose.
 "onSale": true, // or false to show only onSale product for the category id you choose.
      "isSnapping": true
    },

to be like this

 example:
    {
      "name": "Man Collections",
      "image": "",
      "layout": "twoColumn",
      "category": 21,
      "isSnapping": true
      "onSale": true, 
     "featured": true,
     "tag": 12
    },

please try to read our fluxstore [documentation ](https://docs.inspireui.com/fluxstore/customization/). thank you

**Comment by stagedoor16** [comment]
I am using MStore Pro does the same principal apply, also i am using parent categories although the app is only showing one parent category when i have more top level parent categories

**Comment by minhcasi** [comment]
@stagedoor16 - pls help to download the latest `Mstore Pro 4.0` to fix the build issue

@luyx2412 - pls help to follow up this issue 

Thank you!

**Comment by stagedoor16** [comment]
HI, how do i update the source code without losing my changes

**Comment by luyx2412** [comment]
Hi @stagedoor16 You can use the git to compare new version with old version and merge it.

Thanks

**Comment by stagedoor16** [comment]
I have now updated although i am getting an error when running "npm install"

gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:203:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=C:\\Users\\jpwal\\OneDrive\\Documents\\Documents\\app\
\mstore4.0.0\\mstore-pro\\node_modules\\grpc\\src\\node\\extension_binary\\node-v72-win32-x64-unknown\\grpc_node.node" "--module_name=grpc_node" "--module_path=C:\\Users\\jpwal\\OneDrive\\Documents\\Documents\\app\\mstore4.0.0\\mstore-pro\\node_modules\\grpc\\src\\
node\\extension_binary\\node-v72-win32-x64-unknown" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd C:\Users\jpwal\OneDrive\Documents\Documents\app\mstore4.0.0\mstore-pro\node_modules\grpc
gyp ERR! node -v v12.8.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --library=static_library --module=C:\Users\jpwal\OneDrive\Documents\Documents
\app\mstore4.0.0\mstore-pro\node_modules\grpc\src\node\extension_binary\node-v72-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=C:\Users\jpwal\OneDrive\Documents\Documents\app\mstore4.0.0\mstore-pro\node_modules\grpc\src\node\extension_binar
y\node-v72-win32-x64-unknown --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\jpwal\OneDrive\Documents\Documents\app\mstore4.0.0\mstore-pro\node_modules\grpc\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:203:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
node-pre-gyp ERR! System Windows_NT 10.0.18362
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\jpwal\\OneDrive\\Documents\\Documents\\app\\mstore4.0.0\\mstore-pro\\node_modules\\grpc\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build" "--library=static_lib
rary"
node-pre-gyp ERR! cwd C:\Users\jpwal\OneDrive\Documents\Documents\app\mstore4.0.0\mstore-pro\node_modules\grpc
node-pre-gyp ERR! node -v v12.8.0
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --library=static_library --module=C:\Users\jpwal\OneDrive\Documents\Documents\app\mstore4.0.0\mstore-pro\nod
e_modules\grpc\src\node\extension_binary\node-v72-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=C:\Users\jpwal\OneDrive\Documents\Documents\app\mstore4.0.0\mstore-pro\node_modules\grpc\src\node\extension_binary\node-v72-win32-x64-unknown --
napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\jest-haste-map\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^2.1.2 (node_modules\@jest\transform\node_modules\jest-haste-map\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^2.1.2 (node_modules\@jest\reporters\node_modules\jest-haste-map\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^2.1.2 (node_modules\@jest\test-sequencer\node_modules\jest-haste-map\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^2.1.2 (node_modules\jest-runner\node_modules\jest-haste-map\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^2.1.2 (node_modules\jest-runtime\node_modules\jest-haste-map\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^2.1.2 (node_modules\jest-snapshot\node_modules\jest-haste-map\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^2.1.2 (node_modules\@jest\core\node_modules\jest-haste-map\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN react-native@0.62.2 requires a peer of react@16.11.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-country-picker-modal@1.11.0 requires a peer of react-dom@* but none is installed. You must install peer dependencies yourself.
npm WARN react-native-country-picker-modal@1.11.0 requires a peer of react-native-web@* but none is installed. You must install peer dependencies yourself.
npm WARN react-native-localization@2.1.6 requires a peer of react-native@^0.41.2 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-localization@2.1.6 requires a peer of react-native-windows@0.41.0-rc.1 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-webview@10.3.1 requires a peer of react@16.11.0 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.3.0 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.3.0 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN styled-components@5.1.1 requires a peer of react-dom@>= 16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN modal-react-native-web@0.2.0 requires a peer of react-art@16.x.x but none is installed. You must install peer dependencies yourself.
npm WARN modal-react-native-web@0.2.0 requires a peer of react-dom@16.x.x but none is installed. You must install peer dependencies yourself.
npm WARN modal-react-native-web@0.2.0 requires a peer of react-native-web@0.9.x but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-react-hooks@3.0.0 requires a peer of eslint@^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb@18.2.0 requires a peer of eslint-plugin-react@^7.20.0 but none is installed. You must install peer dependencies yourself.
npm WARN @typescript-eslint/eslint-plugin@2.34.0 requires a peer of eslint@^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @typescript-eslint/parser@2.34.0 requires a peer of eslint@^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-react@7.19.0 requires a peer of eslint@^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-react-native@3.8.1 requires a peer of eslint@^3.17.0 || ^4 || ^5 || ^6 but none is installed. You must install peer dependencies yourself.
npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
npm WARN jsdom@16.2.2 requires a peer of canvas@^2.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.3.0 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.3.0 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.20.0 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@1.20.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jpwal\AppData\Roaming\npm-cache\_logs\2020-06-30T15_42_15_580Z-de


I have tried clearing the cache and deleting node modules although nothing seems to work

**Comment by stagedoor16** [comment]
I have now updated with no issues and we are still getting the same issue

**Comment by luyx2412** [comment]
Hi @stagedoor16 Please clean your project with `flutter clean`, after that uninstall your app and reinstall again. Please check and give me the news.

Thanks

**Comment by luyx2412** [comment]
Hi @stagedoor16 Please use `yarn` https://yarnpkg.com/ to install the package instance of `npm`. Because npm will appear some unexpected issues.

Thanks
