### ISSUE TITLE
Fluxstore pro 1.7.5 not showing any products but showing single blog post from my live woocommerce site

### ISSUE THREAD

**Issue by nithinkumarsn** [inspireui/support#3893]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: images are not rendering in app from woocommerce live site 
+ Product & version:fluxstorepro 1.7.5
+ Flutter (or React Native) version: flutter 1.17.4 and dart 2.8.4
+ Testing Device/Simulator: redmi mi note 8
+ Screenshot issues (drag the file to attach here): 

![Screenshot_2020-06-24-22-58-38-946_com inspireui fluxstore](https://user-images.githubusercontent.com/40752313/85604378-df770b00-b66e-11ea-8286-da47e53ae26b.jpg)
![Screenshot_2020-06-24-22-58-46-444_com inspireui fluxstore](https://user-images.githubusercontent.com/40752313/85604409-e736af80-b66e-11ea-9e24-2de975a65f1d.jpg)
![Screenshot_2020-06-24-22-58-54-922_com inspireui fluxstore](https://user-images.githubusercontent.com/40752313/85604441-ed2c9080-b66e-11ea-8ae7-794f775926aa.jpg)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by ameenbadri7** [comment]
please try to double-check this [tutorial ](https://docs.inspireui.com/fluxstore/woocommerce-setup/). 
if you are connected to your store 
please also check your config_xx.json file `lib\config\config_en.json `

```
{
      "name": "Woman Collections",
      "image": "",
      "layout": "threeColumn",
      "category": 22,
      "isSnapping": true
    },
    {
      "name": "Man Collections",
      "image": "",
      "layout": "twoColumn",
      "category": 21,
      "isSnapping": true
    },
```

the `category`: id is the category id from your woocommerce from this link `your_shop_url/wp-admin/edit-tags.php?taxonomy=product_cat&post_type=product`


<img width="960" alt="categry id" src="https://user-images.githubusercontent.com/37524186/85622168-1e0cc580-b66f-11ea-8c7b-ded655866502.png">

**Comment by nithinkumarsn** [comment]
> please try to double-check this [tutorial ](https://docs.inspireui.com/fluxstore/woocommerce-setup/).
> if you are connected to your store
> please also check your config_xx.json file `lib\config\config_en.json `
> 
> ```
> {
>       "name": "Woman Collections",
>       "image": "",
>       "layout": "threeColumn",
>       "category": 22,
>       "isSnapping": true
>     },
>     {
>       "name": "Man Collections",
>       "image": "",
>       "layout": "twoColumn",
>       "category": 21,
>       "isSnapping": true
>     },
> ```
> 
> the `category`: id is the category id from your woocommerce from this link `your_shop_url/wp-admin/edit-tags.php?taxonomy=product_cat&post_type=product`
> 
> <img alt="categry id" width="960" src="https://user-images.githubusercontent.com/37524186/85622168-1e0cc580-b66f-11ea-8c7b-ded655866502.png">

yes i followed tutorial and did the same ...category id is replaced with mine site in config_en.json

**Comment by ameenbadri7** [comment]
thank you for your patience @nithinkumarsn.

Could you help to share your lib/common and lib/config folder to our privet [link  ](http://verify.inspireui.com)so that we could help with investigating 
- thank you!

**Comment by nithinkumarsn** [comment]
> thank you for your patience @nithinkumarsn.
> 
> Could you help to share your lib/common and lib/config folder to our privet [link ](http://verify.inspireui.com)so that we could help with investigating
> 
> * thank you!

shared everything you mentioned ...please help me soon.

**Comment by henry2327** [comment]
![20200626_135810](https://user-images.githubusercontent.com/36794944/85887077-1fe0a100-b7b5-11ea-83ea-821195530bbe.jpg)
Hola tiene que poner tu dominio propio hay donde te envie la foto para que se muestren los productos nada tiene puesto las claves de las apis

**Comment by ameenbadri7** [comment]
thank you @henry2327 

please @nithinkumarsn  consider rechecking your config file with the secrets keys from `lib\common\config.dart`

let us know if you still have a problem.

**Comment by nithinkumarsn** [comment]
> thank you @henry2327
> 
> please @nithinkumarsn consider rechecking your config file with the secrets keys from `lib\common\config.dart`
> 
> let us know if you still have a problem.

yes,checked i tried with same ck and cs with fluxbuilder it is working ..but in code not getting any products except blog ..

**Comment by nithinkumarsn** [comment]
in home page men collections ,woman collections and new collections shows nothing but if click see all then i can see.. see all and other categories ..only when i click on particular categories its shows products but see all is not showing anything...

**Comment by henry2327** [comment]
Si quiere ver todo de una ves tiene que ir a la pagina web de   WordPress limpia el cache de API

**Comment by ameenbadri7** [comment]
could you share with us your website link so we can see your API output?

try with @henry2327 he said that delete your cache API from the plugin `WP REST Cache`.

please try to correctly get your `category id` to double-check it, sir.

**Comment by nithinkumarsn** [comment]
> could you share with us your website link so we can see your API output?
> 
> try with @henry2327 he said that delete your cache API from the plugin `WP REST Cache`.
> 
> please try to correctly get your `category id` to double-check it, sir.

take my website ;https://marketn.in/          login user admin and pass is 1to 8 ..... please help me anybody ..still i am not getting clear ..

**Comment by xFryx** [comment]
I have the same problem, could you tell us how to solve it? Thanks ...

**Comment by ameenbadri7** [comment]
@nithinkumarsn, please send us your website link so we can see your API output to this emails only
minhcasi@gmail.com and inspireui-team@inspireui.com

you can find in the [documentation ](https://docs.inspireui.com/fluxstore/common-issues/)

Issue: My images do not show up on the app.

Solution: Refer to this [guide ](https://docs.inspireui.com/fluxstore/performance/#2-image-optimization)to display the images.

You also can re-upload the image, after I installed the[ Image PlugIn](https://wordpress.org/plugins/regenerate-thumbnails/)

And kindly checking if you are using an old version of config_en.json file. Please replace the latest one and let's see if it helps. Also fill in your consumerKey and consumerSecret in your config.dart file. You can refer to this doc get [Consumer Key](https://docs.woocommerce.com/document/woocommerce-rest-api/) to get those.

**Comment by ameenbadri7** [comment]
@xFryx you could use these tips and also refer to this our [documentation ](https://docs.inspireui.com/fluxstore/)for more info or you could open a new ticket so we can give you direct support. 
thank you.

**Comment by ameenbadri7** [comment]
I'm sorry to close this ticket as there is no response or active conversation, 
please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
