### ISSUE TITLE
Login crash on ios

### ISSUE THREAD

**Issue by Cheewingtan** [inspireui/support#3895]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: Facebook Google SMS perfectly work on android but not ios ,on ios when I click the facebook and google login it will force end the app on simulator,I sure I follow the step from here https://docs.inspireui.com/fluxstore/sign-in/
+ Product & version: 1.7.3
+ Flutter (or React Native) version: Flutter 1.17.4
+ Testing Device/Simulator: Iphone SE
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by ameenbadri7** [comment]
Please could you send screenshots About this problem.  
Also could you please check 
[This](https://github.com/inspireui/support/issues/3151) 

And also double checking 
The tutorial at fluxstore [documentation](https://docs.inspireui.com/fluxstore/sign-in/) 

Thank you for your patience.

**Comment by minhcasi** [comment]
@Cheewingtan - pls try to update to latest release `17.5` - thanks

**Comment by Cheewingtan** [comment]
OK I try on 1.7.5 first
by the way I using multi vendor,not fluxstore
> @Cheewingtan - pls try to update to latest release `17.5` - thanks

**Comment by Cheewingtan** [comment]
> Please could you send screenshots About this problem.
> Also could you please check
> [This](https://github.com/inspireui/support/issues/3151)
> 
> And also double checking
> The tutorial at fluxstore [documentation](https://docs.inspireui.com/fluxstore/sign-in/)
> 
> Thank you for your patience.

ok is work to me thanks
