### ISSUE TITLE
MStore Failed to compile

### ISSUE THREAD

**Issue by kersianuy** [inspireui/support#3896]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
Im trying to follow the tutorials of EXPO but now EXPO XDE dont work anymore, so I installed yarn install in the folder, then expo start and this happens, didnt touch a single file yet.
+ Product & version: MStore PRO
+ Flutter (or React Native) version:  React Native
+ Testing Device/Simulator: EXPO 
+ Screenshot issues (drag the file to attach here): 
![mstore](https://user-images.githubusercontent.com/49377087/85652032-00942780-b680-11ea-9673-4663dbc3bd33.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

![proof](https://user-images.githubusercontent.com/49377087/85652604-967c8200-b681-11ea-9b3b-5da6658f3a88.jpg)

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@kersianuy - please help to support verify purchase via this form http://verify.inspireui.com - thank you!

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
