### ISSUE TITLE
There are some files that could not be found

### ISSUE THREAD

**Issue by haidarsalim** [inspireui/support#3899]
I can't find missing files to change country and some settings
Just tell me where to find it

FluxNews Version: 1.4.1
Flutter : v1.17.1
Testing Device/Simulator

Missing files
1- lib/screens/login_sms/login_sms_constants.dart
2- lib/common/constants/general.dart

I told you this and here before without solving the problem
https://github.com/inspireui/support/issues/3733
---
![444](https://user-images.githubusercontent.com/54249914/85688533-8218a380-b6da-11ea-9cc0-44e6478b4065.PNG)
![84594800-52a5a380-ae5d-11ea-9bb9-abc3fea12595](https://user-images.githubusercontent.com/54249914/85688619-92c91980-b6da-11ea-901f-c6471ec7ba2e.png)

**Comment by ameenbadri7** [comment]
I saw your last [issue ](https://github.com/inspireui/support/issues/3733
)before 10 days.

I think you have deleted the config folder so please consider downloading your project again from the same source you download before.

you can learn more by using this [tutorial ](https://medium.com/@inspireui/how-to-upgrade-fluxstore-projects-by-using-git-cebde7489ea6).

thank you for your patience and please tell us if your problem fixed so we can close this issue, or to give you more help.

**Comment by haidarsalim** [comment]
do you speak Arabic ?
راح اجرب احمل المشروع من جديد بس ما اعتقد اني حاذف المفات لان عندي المشروع الاصلي  هاي الملفات ما موجودة بي 

مافهمت شنو استفاد من هذا المقال 
https://medium.com/@inspireui/how-to-upgrade-fluxstore-projects-by-using-git-cebde7489ea6

**Comment by ameenbadri7** [comment]
حياك الله استاذ حيدر 
انا حاليا متخصص بتطبيق fluxstore pro 
ولكن راح اخلي الشباب يشوفوا مشكلتك بإذن الله راح تنحل في أقرب وقت 


Hello, Mr. Haider, I am currently specialized in the Fluxstore Pro application, but I will let our team check you up to see your problem, it will be solved as soon as possible.

**Comment by haidarsalim** [comment]
> حياك الله استاذ حيدر
> انا حاليا متخصص بتطبيق fluxstore pro
> ولكن راح اخلي الشباب يشوفوا مشكلتك بإذن الله راح تنحل في أقرب وقت
> 
> Hello, Mr. Haider, I am currently specialized in the Fluxstore Pro application, but I will let our team check you up to see your problem, it will be solved as soon as possible.

**شكرا لك اخي العزيز انا بانتظار ذلك**
