### ISSUE TITLE
[MStore MV] - I need installation Support

### ISSUE THREAD

**Issue by imdeepakkashyap** [inspireui/support#39]
Hello Guys i have purchased your application and as requested and agreed i need your assistance in setting up my project , i m someone with no exploser to react native as pre sale i have asked and you guys agreed to help me setting up react native and help me do the setup i m asking it frm you..

https://codecanyon.net/item/mstore-multi-vendor-complete-react-native-template-for-ecommerce/22278924

I bought this project of yours Sharing details below

 Licensor's Author Username: InspireUI
Licensee: Ayan Malik
Item Title: MStore Multi Vendor - Complete React Native template for WooCommerce
Item URL: https://codecanyon.net/item/mstore-multi-vendor-complete-react-native-template-forecommerce/22278924
Item ID: 22278924
Item Purchase Code: 207f9295-96af-483f-98fb-9beb794bafc9

Help me out please .. for email or any support mail me @ deepak2ualways@gmail.com

**Comment by minhcasi** [comment]
Hi, first - could you help to install your environment for the app, please make sure you can run the Example simulator base on this guide - https://docs.expo.io/versions/v31.0.0/introduction/installation - thank you!
