### ISSUE TITLE
[MStore Multi Vendor] Category Image

### ISSUE THREAD

**Issue by AbdullahNabta** [inspireui/support#390]
**Required Info (please complete the following information):**
 - Product: mstore mutli vendor
 - Your Purchased Code: 81097dcc-f5c1-435c-bca6-e8e388bb725a
(we may not reply if you are not our customer)

**Describe the bug**
the page where there is the category tab and the vendor tab. The vendor tabs shows the images. but for the category tab there is no images at all. not even using the placeholder that you have provided. I am not sure what is going on i attached two diffrent screenshots in one link so pelase scroll down and see it. thanks Link : https://imgur.com/a/hGkDw31
**Screenshots**
https://imgur.com/a/hGkDw31
**Additional context**
Add any other detail logs about the problem here.
If possible please share your config.js that use for the app setting

**Comment by thangvo9x** [comment]
Hi. Can you give me your info admin, plz?

**Comment by AbdullahNabta** [comment]
I have sent it to you via email hi@inspireui.com

**Comment by thangvo9x** [comment]
How are u ?

**Comment by MrFaisal100** [comment]
Hi,
I have the same issue 
I would appreciate if you tell how to solve it
