### ISSUE TITLE
can not build the app

### ISSUE THREAD

**Issue by goelrajiv75** [inspireui/support#3900]
WHEN I SAY FLUTTER RUN
Note: C:\source\flutter\.pub-cache\hosted\pub.dartlang.org\connectivity-0.4.8+6\andr
oid\src\main\java\io\flutter\plugins\connectivity\ConnectivityBroadcastReceiver.java
 uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\source\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.13.4\an
droid\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.
java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: C:\source\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_admob-0.9.3+2\an
droid\src\main\java\io\flutter\plugins\firebaseadmob\AdRequestBuilderFactory.java us
es or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: C:\source\flutter\.pub-cache\hosted\pub.dartlang.org\uni_links-0.4.0\android\s
rc\main\java\name\avioli\unilinks\UniLinksPlugin.java uses or overrides a deprecated
 API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\source\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-5.4.10\andro
id\src\main\java\io\flutter\plugins\urllauncher\WebViewActivity.java uses or overrid
es a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\source\flutter\.pub-cache\hosted\pub.dartlang.org\video_player-0.10.11+1\an
droid\src\main\java\io\flutter\plugins\videoplayer\VideoPlayerPlugin.java uses or ov
errides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\source\flutter\.pub-cache\hosted\pub.dartlang.org\webview_flutter-0.3.22+1\
android\src\main\java\io\flutter\plugins\webviewflutter\FlutterWebView.java uses unc
hecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                        66.7s
Exception: Gradle task assembleDebug failed with exit code -1

+ Detail Issues: 
+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

pls help

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support
 - http://verify.inspireui.com/
 - please don't share the purchase code or screenshot public here as another user will use it for activation.
We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by ameenbadri7** [comment]
hello @goelrajiv75  

anything with `Note: Recompile with -Xlint:deprecation for details.` don't care about it ok.

but try to use the tips inside this page: 

https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

and please tell us if your problem fixed so we can close this ticket issue or let us help you more.
thank you

**Comment by goelrajiv75** [comment]
https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1
I have attempt these steps plenty of times. but problem still remains

**Comment by minhcasi** [comment]
@goelrajiv75 

1. pls have a check to see if could run this example https://flutter.dev/docs/get-started/test-drive?tab=vscode

2. send us your result by running this script `flutter doctor`
