### ISSUE TITLE
Fluxstore apk build issue - previous ticket "build appbundle issue #3794"

### ISSUE THREAD

**Issue by Moh-Zag** [inspireui/support#3901]
Hi, 
I still have the same issue "I got an error when I try to create an apk or appbundle of my project",
Although I run the project successfully on the emulator.
previous ticket [https://github.com/inspireui/support/issues/3794]

here is a screen shot of the error screen

![Screenshot_4](https://user-images.githubusercontent.com/50769781/85718987-53f18e80-b6ef-11ea-958c-dc9fba8b4852.jpg)

and this is a screen shot of the project running on the emulator

![Screenshot_3](https://user-images.githubusercontent.com/50769781/85719146-708dc680-b6ef-11ea-9a4d-74b614b910de.jpg)

I hope that you will be more patient and help me resolve this issue.

Thanks 

Best Regards

**Comment by ameenbadri7** [comment]
please consider using this [gits](https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1) to fix any building problems.
and if its not fixed try to change your fonts to the default fonts. 
and tell us if you problem fixed or not.

thank you for your patient.

**Comment by Moh-Zag** [comment]
Hi, the issue is resolved by replacing the installed fontawesome.ttf with a another file "downloaded from GitHub".
Thanks for your advice.
