### ISSUE TITLE
Products appearing and disappearing

### ISSUE THREAD

**Issue by justinekatebe69** [inspireui/support#3903]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: I’ve also noticed one thing about the app. If I go to a collection and go to the home page, and decide to go back to the collection I’m literally from, sometimes it says “no products” for a collection that had products just a few minutes ago WHAT IF THE FIX FOR THIS??
+ Product & version:1.7.5
+ Flutter (or React Native) version: 1.7.5
+ Testing Device/Simulator: device
+ Screenshot issues (drag the file to attach here): 
![Screenshot_20200625-142523](https://user-images.githubusercontent.com/67024464/85722379-8650bb00-b6f2-11ea-87d4-e64f57ee0f7d.jpg)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by ameenbadri7** [comment]
**** I deleted your license that you write here, please try to use the privet link in future issues requests. ** 

about your problem: 

consider using those tips to fix this problem:
- try to disable caching inside `lib\common\constants\general.dart`   "isCaching": false,`
- update mstore plugin in your WordPress project and also.

if your problem not fixed tell us with a comment so I can pass this issue to a higher developer. 

thank you

**Comment by justinekatebe69** [comment]
Hey this fix doesn’t solve the problem. It’s still present.

**Comment by justinekatebe69** [comment]
The funny thing about the problem is that, if I click on a collection from
the menu, it says “no products”, but if I click on the see all button of
that exact same collection from the home page below the recently viewed, it
loads the products.

**Comment by minhcasi** [comment]
@justinekatebe69 - pls help us to raise one ticket for your all issue to #3828 

We will help to check this product loading issue - thanks

**Comment by justinekatebe69** [comment]
I have already raised an issue, and it was closed without the issue being
fixed.  https://github.com/inspireui/support/issues/3903

**Comment by justinekatebe69** [comment]
Hey my issue is still present.
When I click on the icons, categories and menu collections, my products
aren't loading! But if I add a featured collection on the home page of the
app and click the "see all" button, it's loading products.
