### ISSUE TITLE
Push notifications icon is missing and how to link different pages ?

### ISSUE THREAD

**Issue by rihtak2020** [inspireui/support#3905]
**_Step 1 (require): describe detail issues & screenshots_**
In the push notification generated by google firebase, the icon missing and its not displayed in the notify messages present in app settings .
and can we link a particular product or category in push notifications ? right now its opening just the homepage of the app

+ Product & version: 1.7.5
+ Flutter (or React Native) version: Flutter 
+ Testing Device/Simulator:  android redmi note 5 pro
+ Screenshot issues (drag the file to attach here): 
![WhatsApp Image 2020-06-25 at 8 08 54 PM](https://user-images.githubusercontent.com/65780159/85741912-72bc4900-b720-11ea-8603-d0e5de23cc12.jpeg)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support 
- http://verify.inspireui.com/ 
- please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
@rihtak2020 - pls help to add you all comment into ONE ticket - #3907
