### ISSUE TITLE
Fluxstore Multi Vendor - Flutter E-commerce Full App -- login not working please help

### ISSUE THREAD

**Issue by dasdev** [inspireui/support#3906]
after i change the package id unable to login. can’t sing up too. what happening is when login the button running round infinity. after press back it’s showing logout option but no profile or update option there. please help it’s urgent i need to deliver the app today.

https://drive.google.com/file/d/1TEQpiqYS2_VhOL0ujQeKB69q5SEK76aA/view?usp=sharing
previous version of latest version of flutter.
latest product version recently downloaded for codecanyon
mobile phone android 9

![Screenshot_2020-06-25-20-06-37-62_5322b48291e770e9bb1148f27d6b2d01 1](https://user-images.githubusercontent.com/34004057/85742522-ef4f2780-b720-11ea-921e-b340fdfe2b4c.png)

![Screenshot_2020-06-25-20-07-12-13_5322b48291e770e9bb1148f27d6b2d01 1](https://user-images.githubusercontent.com/34004057/85742126-9e3f3380-b720-11ea-9c4b-6ed12cdafdba.png)

![Screenshot_2020-06-25-20-07-24-98_5322b48291e770e9bb1148f27d6b2d01 1](https://user-images.githubusercontent.com/34004057/85742270-b9aa3e80-b720-11ea-8def-062012e08647.png)
when clicking logout in sidemenu it's not login out.

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support 

- http://verify.inspireui.com/
- please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by dasdev** [comment]
I have already submitted

**Comment by dasdev** [comment]
[Gmail - Submit Private Files For Support Ticket.pdf](https://github.com/inspireui/support/files/4834106/Gmail.-.Submit.Private.Files.For.Support.Ticket.pdf)

**Comment by dasdev** [comment]
> [Gmail - Submit Private Files For Support Ticket.pdf](https://github.com/inspireui/support/files/4834106/Gmail.-.Submit.Private.Files.For.Support.Ticket.pdf)

i didnt wanted to share this but you guys take too much time to solve any problem so that to make it fast i had to share this which i already submitted but your asking to do that again. if can't help say i will return money to my customer.

**Comment by minhcasi** [comment]
@dasdev - pls try to refer to this similar issue #3151  - thank you!

**Comment by dasdev** [comment]
i am not having login problem with gmail or sms. i have problem with email logoin. kindly install the app and check what what's the problme

**Comment by dasdev** [comment]
> i am not having login problem with gmail or sms. i have problem with email logoin. kindly install the app and check what what's the problme

should i clean the invaileded cache than run the app?

**Comment by dasdev** [comment]
i am just unable to login there is no error massage showing when i am trying to login the circle button just running when pressing back button showing just logout menu there is no other may that should show after successfully login. it's a small issue which i have than i can releases the app on play store. please sir kindly save me. its already 5 6 month i have bought this app but couldn't complete for always some problem.

**Comment by dasdev** [comment]
i am waiting for the solution when will you help me to solve this problem?

**Comment by dasdev** [comment]
W/zun.ecom.vendo( 4086): Accessing hidden method Landroid/media/AudioManager;->getOutputLatency(I)I (light greylist, reflection)
W/cr_media( 4086): Requires BLUETOOTH permission
D/libEGL  ( 4086): [oppo_test] for feedback 1785468: dpy=1
D/WindowManager( 4086): Add to mViews: DecorView@6b8dc72[MainActivity], this = android.view.WindowManagerGlobal@ab87653,pkg=com.shopzun.ecom.vendor
D/Intent  ( 4086): disableDeathOnFileUriExposure com.android.chrome
W/AudioCapabilities( 4086): Unsupported mime audio/ffmpeg
W/VideoCapabilities( 4086): Unsupported mime image/vnd.android.heic
W/VideoCapabilities( 4086): Unsupported mime video/ffmpeg
W/VideoCapabilities( 4086): Unrecognized profile 8192 for video/hevc
W/VideoCapabilities( 4086): Unrecognized profile 8192 for video/hevc
I/Choreographer( 4086): Skipped 9 frames!  The application may be doing too much work on its main thread.
W/VideoCapabilities( 4086): Unrecognized profile 4 for video/hevc
W/VideoCapabilities( 4086): Unrecognized profile/level 0/3 for video/mpeg2
W/VideoCapabilities( 4086): Unrecognized profile/level 0/3 for video/mpeg2
I/VideoCapabilities( 4086): Unsupported profile 4 for video/mp4v-es
D/libEGL  ( 4086): [oppo_test] for feedback 1785468: dpy=1
D/libEGL  ( 4086): [oppo_test] for feedback 1785468: dpy=1
D/libEGL  ( 4086): [oppo_test] for feedback 1785468: dpy=1
D/libEGL  ( 4086): [oppo_test] for feedback 1785468: dpy=1
E/Parcel  ( 4086): Reading a NULL string not supported here.
I/chromium( 4086): [INFO:CONSOLE(2)] "JQMIGRATE: Migrate is installed, version 1.4.1", source: https://www.shopzun.com/wp-includes/js/jquery/jquery-migrate.min.js?ver=1.4.1 (2)
D/ViewRootImpl( 4086): Swipe From Side Rotation 0 mIgnoring true downX 669 downY 611 mScreenHeight 1600 mScreenWidth 720 mStatusBarHeight 54 globalScale 1.125
D/ViewRootImpl( 4086): Swipe From Side Rotation 0 mIgnoring true downX 669 downY 611 mScreenHeight 1600 mScreenWidth 720 mStatusBarHeight 54 globalScale 1.125
D/ViewRootImpl( 4086): swipeFromBottom mIgnoring === false downY 611 mStatusBarHeight 54
I/flutter ( 4086): screenName /login
W/FA      ( 4086): setCurrentScreen cannot be called with the same class and name
I/Choreographer( 4086): Skipped 4 frames!  The application may be doing too much work on its main thread.
W/IInputConnectionWrapper( 4086): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 4086): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper( 4086): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper( 4086): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 4086): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 4086): endBatchEdit on inactive InputConnection
I/flutter ( 4086): token: cWlg64dJUAY:APA91bGRWzcaBR8w2tWbgBxkUwYZU9-w4376wmWSs1bb6JPGQtQJSj0_oHvMLwZj78lQDFzDESpQ1zW3XNzAM0Pu79-T4LB5CoKJVaRKaRccAYGoEgWbtyHu-H88A4oDMLg6Tn7WjDvS
W/System  ( 4086): A resource failed to call release. 
I/Choreographer( 4086): Skipped 4 frames!  The application may be doing too much work on its main thread.
E/Parcel  ( 4086): Reading a NULL string not supported here.
I/RM_POWER_NET( 4086): com.shopzun.ecom.vendor(4086) Sucess to connect  to api.onesignal.com/2606:4700::6812:e234 (port 443) from /2401:4900:1040:c149:5845:88d6:eea6:a60d (port 48824)
E/OneSignal( 4086): Error updating the user record because of th enull user id
I/Choreographer( 4086): Skipped 7 frames!  The application may be doing too much work on its main thread.
I/Choreographer( 4086): Skipped 8 frames!  The application may be doing too much work on its main thread.
E/Parcel  ( 4086): Reading a NULL string not supported here.
I/Choreographer( 4086): Skipped 1 frames!  The application may be doing too much work on its main thread.
I/Choreographer( 4086): Skipped 2 frames!  The application may be doing too much work on its main thread.
I/Choreographer( 4086): Skipped 5 frames!  The application may be doing too much work on its main thread.
E/Parcel  ( 4086): Reading a NULL string not supported here.
I/Choreographer( 4086): Skipped 5 frames!  The application may be doing too much work on its main thread.
I/Choreographer( 4086): Skipped 8 frames!  The application may be doing too much work on its main thread.
I/zun.ecom.vendo( 4086): Background concurrent copying GC freed 112340(4MB) AllocSpace objects, 20(1040KB) LOS objects, 49% free, 5MB/11MB, paused 182us total 135.516ms
I/Choreographer( 4086): Skipped 1 frames!  The application may be doing too much work on its main thread.

**Comment by dasdev** [comment]
i have found the problem that after changing bundle id i am unable to login using email id. please now fix this issue.

**Comment by dasdev** [comment]
can you please fix my problem i need to fix my login issue. i got that
after changing bundle id email login not working. i don't need facebook sms
or google login right now.just fix my email loging i gave you my debug apk
please see please.

**Comment by dasdev** [comment]
how long i need to wait sir please look after me.

**Comment by ameenbadri7** [comment]
@dasdev 
We wanted to thank you for your patience during this busy time. We currently have reduced staff and a significantly higher volume of inquiries. We’re working as hard as we can to get to your request as soon as possible.
I let our team work on your issue as soon as possible.

**Comment by dasdev** [comment]
sir please fix my login issue i don't need anytingg at this time kindly help

**Comment by dasdev** [comment]
what happening is that when i am trying to sing up or login it's working but not leaving that screen. like when i am login it's staying in login page not successfully coming to profile page. and also just showing log out option. after i click on about page or reset page than option coming which after login should come please solve it as soon as possible. it's long time passed i am doing this now need to finish this work. please. or make login menu directly go to main site login it's working fine there.

**Comment by dasdev** [comment]
suddenly i am getting error on rest api. no product showing getting this error please check 
![amfun](https://user-images.githubusercontent.com/34004057/85918335-8d590400-b87f-11ea-869d-12e30c0d1f90.jpg)

**Comment by minhcasi** [comment]
@dasdev - could you try to update the 1.0.6 to check this issue on the fluxbuilder - https://github.com/inspireui/fluxbuilder/releases/edit/v1.0.6-beta- thank you!

**Comment by dasdev** [comment]
have you checked my login issue?

**Comment by dasdev** [comment]
kindly today fix my login issue. i am waiting for log month.

**Comment by dasdev** [comment]
> @dasdev - could you try to update the 1.0.6 to check this issue on the fluxbuilder - https://github.com/inspireui/fluxbuilder/releases/edit/v1.0.6-beta- thank you!
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/cbfbdece72100f46536fc8c567f4fbdeb80df1c7/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f696d616765732f6d6f64756c65732f6f70656e5f67726170682f6769746875622d6c6f676f2e706e67"><img alt="" height="14" src="https://camo.githubusercontent.com/040b5519c6d1891329f5f6d3e511003657131cf2/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[Build software better, together](https://github.com)**GitHub is where people build software. More than 50 million people use GitHub to discover, fork, and contribute to over 100 million projects.

this issue has been fixed. but login issue not please help and also having problem with app release will inform about it after login issue get fixed please.

**Comment by minhcasi** [comment]
@dasdev - pls try your best to check the solution on this issue #3151 - there is new policies form the google that require to update the OAuth consent

**Comment by eraldix** [comment]
same issue did you fix

**Comment by minhcasi** [comment]
@eraldix - pls double-check solution #3151

**Comment by dasdev** [comment]
No I I was asking for normal email login solution he gave me social login
and sms solution which I don't need.

**Comment by minhcasi** [comment]
pls try this solution to fix the login issue, this is a common problem when your Rest API not working

https://github.com/WordPress/application-passwords/wiki/Basic-Authorization-Header----Missing

**Comment by dasdev** [comment]
you guys provides which i already solved. what i couldn't solve you not
providing that. email login issue. not gmail or sms login.

**Comment by minhcasi** [comment]
@dasdev - would you mind to share the private admin login access to inspireui.team@gmail.com - we will help to check the issue - thank you!

**Comment by minhcasi** [comment]
This is something related to the website config settings, please double-check the consumse keys and .htacess as well

<img width="1409" alt="Screen Shot 2020-07-07 at 11 39 35" src="https://user-images.githubusercontent.com/1459805/86711811-8f248380-c046-11ea-98ab-c572308814be.png">

**Comment by vumanhsn97** [comment]
@dasdev 
Make sure your bundle id in your app look like bundle id in your database. And check in this issue: https://github.com/inspireui/support/issues/3978#issuecomment-653991244
