### ISSUE TITLE
how to filter and show products on sale ?

### ISSUE THREAD

**Issue by rihtak2020** [inspireui/support#3907]
**_Step 1 (require): describe detail issues & screenshots_**
Hi, i want to know is it possible to display products on sales ? on my website i use https://shanus.in/shop/?swoof=1&onsales=salesonly link to display all products on sale but how to do the same in app ? I am planning to have a sale banner and display on products on sale automatically.

+ Product & version: 1.7.5
+ Flutter (or React Native) version:  flutter

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by ameenbadri7** [comment]
hello @rihtak2020  
yes, it's possible ;

if you want to create a list of products or banners to show on sale products or feathers products by modifying your `config_xx.json` file like this :

```
{
      "name": "Big Discounts",
      "image": "assets/companyLogo/applelogo.png",
      "layout": "threeColumn",
      "isSnapping": true,
      "onSale": true,
      "limit": 20
    },
```

featured: true load the featured product.
onSale: true load the onSale product.
limit: to limit the list for 20 products.
...... 
.....

please consider viewing the fluxstore [documentation ](https://docs.inspireui.com/fluxstore) to get to know about all the other options you can do with fluxstore.
also,  you can download the [Fluxbuilder](https://fluxbuilder.com/) our powerful tool to create a full app without any coding skills.

**Comment by rihtak2020** [comment]
@ameenbadri7 thanks for the reply, and what about say products below 1000 rs or certain value?
Can we filter and show them in a banner ?
