### ISSUE TITLE
undefined is not an object (evaluating '_services.GraphqlAPI.getProductsByCollection({category_id: category_id}).then')

### ISSUE THREAD

**Issue by sebaitu11** [inspireui/support#3908]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: undefined is not an object (evaluating '_services.GraphqlAPI.getProductsByCollection({category_id: category_id}).then') i got this error and it is stuck there, I been not able to open the app once.
+ Product & version: 1.2.0
+ Flutter (or React Native) version: sdk-36.0.0
+ Testing Device/Simulator: Iphone SE 2
+ Screenshot issues (drag the file to attach here):
![WhatsApp Image 2020-06-25 at 11 48 00](https://user-images.githubusercontent.com/4778923/85754520-1daa1400-b6db-11ea-81d2-fa20edde501b.jpeg)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support

- http://verify.inspireui.com/
- please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support

- http://verify.inspireui.com/
- please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by sebaitu11** [comment]
I already did it when I open this ticket, I did it again now as you require

thanks

**Comment by luyx2412** [comment]
Hi @sebaitu11 Please reload app again, and please check your collection id. I just checked your config and it is wrong.
![image](https://user-images.githubusercontent.com/8909619/85918880-c6e63b00-b890-11ea-83e9-da4ebe36079f.png)
![image](https://user-images.githubusercontent.com/8909619/85918879-c5b50e00-b890-11ea-99cb-610bf7e7039b.png)

Thanks

**Comment by sebaitu11** [comment]
but where I am wrong?

**Comment by luyx2412** [comment]
Hi @sebaitu11 Please see the video guide to get the collection id https://www.youtube.com/watch?v=nE7a_yx5Q9w&t=105s

Thanks

**Comment by sebaitu11** [comment]
Already did it, got the same error

**Comment by luyx2412** [comment]
Hi @sebaitu11 Can you share me the Config.js file?

Thanks

**Comment by sebaitu11** [comment]
/** @format */

import Constants from "./Constants";
import Icons from "./Icons";

export default {
  /**
   * Step 1: change to your website shopify graphqlUrl, and storeAccessToken
   * https://help.shopify.com/en/api/custom-storefronts/storefront-api/getting-started
   * Moved AppConfig.json
   */

  // to config custompage
  Wordpress: {
    url: "http://mstore.io",
  },

  /**
     Step 2: Setting Product Images
     - ProductSize: Explode the guide from: update the product display size: https://mstore.gitbooks.io/mstore-manual/content/chapter5.html
     The default config for ProductSize is disable due to some problem config for most of users.
     If you have success config it from the Wordpress site, please enable to speed up the app performance
     - HorizonLayout: Change the HomePage horizontal layout - https://mstore.gitbooks.io/mstore-manual/content/chapter6.html
     */
  ProductSize: {
    enable: false,
    CatalogImages: { width: 300, height: 360 },
    SingleProductImage: { width: 600, height: 720 },
    ProductThumbnails: { width: 180, height: 216 },
  },

  /**
   * Step 3: Setting Home screen, category screen
   * Follow this article to use Graphql https://help.shopify.com/en/api/custom-storefronts/storefront-api/graphql
   * Video tutorial https://www.dropbox.com/s/m4kmp0quh8qplz3/Screen%20Recording%202018-11-05%20at%202.22.21%20PM.mov?dl=0
   */
  SpaceLayout: 15, // setting align right
  /**
   * config home page show
   * - horizontal with multi collection id or
   * - vertical layout with latest product and first product is banner
   */
  HomePage: {
    Horizon: true,
    PageSize: 12,
  },
  
  HorizonLayout: [
    {
      categoryId: "Z2lkOi8vc2hvcGlmeS9Db2xsZWN0aW9uLzg1NTU4OTE5MjMy",
      paging: true,
      layout: Constants.Layout.miniBanner,
    },
    {
      name: "Nuevos",
      categoryId: "Z2lkOi8vc2hvcGlmeS9Db2xsZWN0aW9uLzg5NjYyNjg1MjQ4",
      layout: Constants.Layout.twoColumn,
    },
    {
      name: "Destacados",
      categoryId: "Z2lkOi8vc2hvcGlmeS9Db2xsZWN0aW9uLzkzMjQ3MzA3ODQw",
      layout: Constants.Layout.card,
    }
  ],

  CategoryLayout: {
    ListMode: "ListMode",
    GridMode: "GridMode",
    CardMode: "CardMode",
  },

  /**
   * Now we only support Webview payment, so disable this feature
   * In the furture we will try support this feature
   */
  Payments: [
    // {
    //   name: "Cash on Delivery",
    //   imageUrl: require("@images/payment_logo/cash_on_delivery.png"),
    //   enabled: true,
    // },
    // {
    //   type: "card",
    //   name: "Credit Card",
    //   imageUrl: require("@images/payment_logo/credit_card.png"),
    //   enabled: true,
    // },
  ],

  /**
     Step 4: Advance config:
     - showShipping: option to show the list of shipping method
     - showStatusBar: option to show the status bar, it always show iPhoneX
     - LogoImage: The header logo
     - CustomPages: Update the custom page which can be shown from the left side bar (Components/Drawer/index.js)
     - intro: The on boarding intro slider for your app
     - menu: config for left menu side items (isMultiChild: This is new feature from 3.4.5 that show the sub products categories)
     * */
  shipping: {
    visible: true,
    time: {
      free_shipping: "4 - 7 Days",
      flat_rate: "1 - 4 Days",
      local_pickup: "1 - 4 Days",
    },
  },
  showStatusBar: true,
  LogoImage: require("@images/logo.png"),
  CustomPages: { contact_id: 10941 },

  /**
   * Config Menu Side Drawer
   * @param goToScreen 3 Params (routeName, params, isReset = false)
   * BUG: Language can not change when set default value in Config.js ==> pass string to change Languages
   */
  menu: {
    // has child categories
    isMultiChild: true,
    // Unlogged
    listMenuUnlogged: [
      {
        text: "Login",
        routeName: "Login",
        params: {
          isLogout: false,
        },
        icon: Icons.MaterialCommunityIcons.SignIn,
      },
    ],
    // user logged in
    listMenuLogged: [
      {
        text: "Logout",
        routeName: "Login",
        params: {
          isLogout: true,
        },
        icon: Icons.MaterialCommunityIcons.SignOut,
      },
    ],
    // Default List
    listMenu: [
      {
        text: "Shop",
        routeName: "Default",
        icon: Icons.MaterialCommunityIcons.Home,
      },
      {
        text: "About",
        routeName: "CustomPage",
        params: {
          url: "http://inspireui.com",
        },
        icon: Icons.MaterialCommunityIcons.Email,
      },
    ],
  },
};

**Comment by luyx2412** [comment]
HI @sebaitu11 Sorry about delete your comment, please do not share your config in there to avoid the leak your information. And i got your config.

Thanks

**Comment by luyx2412** [comment]
Hi @sebaitu11 Please send your project via inspireui.team@gmail.com. Let me investigate and resend you soon.

Thanks

**Comment by sebaitu11** [comment]
i sent the email, thanks

**Comment by luyx2412** [comment]
Hi @sebaitu11 Please access my permission to your project.

Thanks

**Comment by sebaitu11** [comment]
Hi @luyx2412  already did it yesterday, can you access my project?

**Comment by luyx2412** [comment]
Hi @sebaitu11 I just sent you the project which fixed the issues.

Thanks

**Comment by sebaitu11** [comment]
Hi @luyx2412  I didn't work , got the same error.

**Comment by luyx2412** [comment]
Hi @sebaitu11 Can you reload app again, i tested the source code and everything worked normal.

Thanks

**Comment by sebaitu11** [comment]
Hi @luyx2412  what do you mean with reload app and clean project, I decompress the folder and install dependencies, it was a clean setup

**Comment by sebaitu11** [comment]
Hi @luyx2412 pls refund my money as Im not able to run the app and its been 12 days, I cant keep waiting for a fix
thanks for your help

**Comment by minhcasi** [comment]
@sebaitu11 - you could refund on this link https://help.market.envato.com/hc/en-us/articles/202821460-Can-I-Get-A-Refund-

**Comment by sebaitu11** [comment]
Hi @minhcasi refund is always time demanding and I need a solution quick as possible, you can provide me with another solution to shopify app, because if you refund the money I will buy another solution from you like flutter shopify or the other one you have.
Thanks

**Comment by sebaitu11** [comment]
@luyx2412 I tried to install in another computer with windows and got the same error
![WhatsApp Image 2020-07-09 at 13 24 30](https://user-images.githubusercontent.com/4778923/87071003-9afb7b80-c1e7-11ea-812e-fd3fa147353c.jpeg)

**Comment by minhcasi** [comment]
@sebaitu11 - please try with the `flutter shopify` as the graphql library could be newest one - we suspect there is the issue with core graphql library from react native. We have our best to check your issue, but this problem does not happen from our side

**Comment by sebaitu11** [comment]
Hi @minhcasi where can I get the flutter shopify, Im not gonna buy another one if the purchase made not work

**Comment by sebaitu11** [comment]
HI @minhcasi I sent a refund ticket got not answer yet, I really need a solution pls

**Comment by sebaitu11** [comment]
HI @minhcasi @luyx2412 so no help whatsover over 11 days??

**Comment by luyx2412** [comment]
Hi @sebaitu11 Sorry we missed your ticket, so can you sent me your source code again. I will try fix it, because the issue did not appear on my side. 

Thanks

**Comment by luyx2412** [comment]
Hi @sebaitu11 I just shared you the source code which fixed the issue. Please check it.

Thanks

**Comment by sebaitu11** [comment]
Hi @luyx2412 I got the following error
![Screen Shot 2020-07-21 at 09 38 45](https://user-images.githubusercontent.com/4778923/88062108-61efcf00-cb36-11ea-9710-6eb776f80db2.png)

**Comment by luyx2412** [comment]
Hi @sebaitu11 Please remove node_modules and use `yarn install` before run app.

Thanks

**Comment by sebaitu11** [comment]
hi @luyx2412 already did that, same error

**Comment by luyx2412** [comment]
Hi @sebaitu11 Please follow the comment to fix your issue https://github.com/infinitered/ignite-bowser/issues/145#issuecomment-457728868

Thanks

**Comment by sebaitu11** [comment]
Hi @luyx2412, I created a .babelrc file and copy the code, now I got this error
![Screen Shot 2020-07-26 at 12 17 21](https://user-images.githubusercontent.com/4778923/88484073-0a889f00-cf3a-11ea-9721-a300362ab6a6.png)

Thanks

**Comment by luyx2412** [comment]
Hi @sebaitu11 Please follow the document to fix your issue. https://github.com/Shopify/babel-plugin-graphql-js-client-transform#in-your-babelrc. The 
Please install with `yarn add babel-plugin-graphql-js-client-transform` and add it to your .babelrc file
![image](https://user-images.githubusercontent.com/8909619/88675907-a589a080-d115-11ea-9eb8-8ff675388491.png)

Thanks

**Comment by sebaitu11** [comment]
It didn't work, same error, found this https://github.com/Shopify/babel-plugin-graphql-js-client-transform/issues/18, but I dont find the file where they add 'graphql-js-client-transform'

Thanks

**Comment by luyx2412** [comment]
Hi @sebaitu11 Please read the document, you should be add `graphql-js-client-transform` to .babelrc file.
![image](https://user-images.githubusercontent.com/8909619/88806390-8acd2f80-d1da-11ea-84af-841ae70efcfe.png)

Thanks

**Comment by sebaitu11** [comment]
Yes already did that, this is my .babelrc

{
  "plugins": [
    [
      "@babel/plugin-proposal-decorators",
      {
        "legacy": true
      }
    ],
    [
      "graphql-js-client-transform"
    ]
  ]
}

**Comment by luyx2412** [comment]
Hi @sebaitu11 Please replace your .babelrc with 
```
{
  "presets": ["babel-preset-expo"],
  "plugins": [ "graphql-js-client-transform"],
  "env": {
    "production": {
      "plugins": [
          "transform-remove-console"
      ]
    }
  }
}
```

Thanks

**Comment by sebaitu11** [comment]
hi @luyx2412 finally work it!!! thanks for your help, really appreciate it

**Comment by luyx2412** [comment]
Hi @sebaitu11 Great! Can you send me your RegisterContainer.js file? Because the `register` function added in this
![image](https://user-images.githubusercontent.com/8909619/89312118-121a1780-d6a1-11ea-8c70-785a06bf5f76.png)

Thanks

**Comment by sebaitu11** [comment]
/**
 * Created by InspireUI on 01/03/2017.
 *
 * @format
 */

import React, { PureComponent } from "react";
import {
  View,
  Text,
  ScrollView,
  TextInput,
  Switch,
  Image,
  I18nManager,
  KeyboardAvoidingView,
} from "react-native";
import { withTheme } from "@callstack/react-theme-provider";
import { register } from "@redux/operations";
import { Languages, Color, Config, Styles } from "@common";
import { toast, error, Validate } from "@app/Omni";
import { ButtonIndex } from "@components";
import { connect } from "react-redux";

const mapStateToProps = (state) => {
  return {
    netInfoConnected: state.app.netInfoConnected,
    isFetching: state.user.isFetching,
  };
};

@withTheme
@connect(
  mapStateToProps,
  { register }
)
export default class RegisterContainer extends PureComponent {
  constructor(props) {
    super(props);

    let state = {
      username: "",
      email: "",
      password: "",
      firstName: "",
      lastName: "",
      useGeneratePass: false,
    };

    const params = props.params;
    if (params && params.user) {
      state = { ...state, ...params.user, useGeneratePass: true };
    }

    this.state = state;

    this.onFirstNameEditHandle = (firstName) => this.setState({ firstName });
    this.onLastNameEditHandle = (lastName) => this.setState({ lastName });
    this.onUsernameEditHandle = (username) => this.setState({ username });
    this.onEmailEditHandle = (email) => this.setState({ email });
    this.onPasswordEditHandle = (password) => this.setState({ password });

    this.onPasswordSwitchHandle = () =>
      this.setState({ useGeneratePass: !this.state.useGeneratePass });

    this.focusLastName = () => this.lastName && this.lastName.focus();
    this.focusUsername = () => this.username && this.username.focus();
    this.focusEmail = () => this.email && this.email.focus();
    this.focusPassword = () =>
      !this.state.useGeneratePass && this.password && this.password.focus();
  }

  _onSignUpHandle = () => {
    const { netInfoConnected } = this.props;
    if (!netInfoConnected) return toast(Languages.noConnection);

    const {
      username,
      email,
      firstName,
      lastName,
      password,
      useGeneratePass,
    } = this.state;

    const _error = this.validateForm();
    if (_error) return this.stopAndToast(_error);

    const user = {
      username,
      email,
      firstName,
      lastName,
      password: useGeneratePass ? undefined : password,
    };
    this.props.register(user).then((data) => {
      if (data) {
        toast(Languages.SignUpSuccess);
        this.props.navigation.goBack(null);
      }
    });
  };

  validateForm = () => {
    const {
      email,
      password,
      firstName,
      lastName,
      useGeneratePass,
    } = this.state;
    if (
      Validate.isEmpty(
        email,
        firstName,
        lastName,
        useGeneratePass ? "1" : password
      )
    ) {
      // check empty
      return "Please complete the form";
    } else if (!Validate.isEmail(email)) {
      return "Email is not correct";
    }
    return undefined;
  };

  stopAndToast = (msg) => {
    toast(msg);
    error(msg);
  };

  render() {
    const {
      email,
      password,
      firstName,
      lastName,
      useGeneratePass,
    } = this.state;
    const { isFetching, theme } = this.props;
    const params = this.props.params;

    return (
      <KeyboardAvoidingView style={styles.container} behavior="padding" enabled>
        <ScrollView contentContainerStyle={styles.container}>
          <View style={styles.logoWrap}>
            <Image
              source={Config.LogoImage}
              style={styles.logo}
              resizeMode="contain"
            />
          </View>
          <View style={styles.formContainer}>
            <View style={styles.inputWrap}>
              <TextInput
                {...commonInputProps}
                ref={(comp) => (this.firstName = comp)}
                placeholder={Languages.firstName}
                onChangeText={this.onFirstNameEditHandle}
                onSubmitEditing={this.focusLastName}
                autoCapitalize="words"
                returnKeyType="next"
                value={firstName}
              />
            </View>
            <View style={styles.inputWrap}>
              <TextInput
                {...commonInputProps}
                ref={(comp) => (this.lastName = comp)}
                placeholder={Languages.lastName}
                onChangeText={this.onLastNameEditHandle}
                onSubmitEditing={this.focusUsername}
                autoCapitalize="words"
                returnKeyType="next"
                value={lastName}
              />
            </View>
            {/* <View style={styles.inputWrap}>
            <TextInput
              {...commonInputProps}
              ref={(comp) => (this.username = comp)}
              placeholder={Languages.username}
              onChangeText={this.onUsernameEditHandle}
              onSubmitEditing={this.focusEmail}
              autoCapitalize="none"
              returnKeyType="next"
              value={username}
            />
          </View> */}
            <View style={styles.inputWrap}>
              <TextInput
                {...commonInputProps}
                ref={(comp) => (this.email = comp)}
                placeholder={Languages.email}
                onChangeText={this.onEmailEditHandle}
                onSubmitEditing={this.focusPassword}
                keyboardType="email-address"
                returnKeyType={useGeneratePass ? "done" : "next"}
                value={email}
              />
            </View>
            {params && params.user ? (
              <View style={styles.switchWrap}>
                <Switch
                  value={useGeneratePass}
                  onValueChange={this.onPasswordSwitchHandle}
                  thumbTintColor={Color.accent}
                  onTintColor={Color.accentLight}
                />
                <Text
                  style={[
                    styles.text,
                    {
                      color: useGeneratePass
                        ? Color.accent
                        : Color.blackTextSecondary,
                    },
                  ]}>
                  {Languages.generatePass}
                </Text>
              </View>
            ) : null}
            {useGeneratePass ? (
              <View />
            ) : (
              <View style={styles.inputWrap}>
                <TextInput
                  {...commonInputProps}
                  ref={(comp) => (this.password = comp)}
                  placeholder={Languages.password}
                  onChangeText={this.onPasswordEditHandle}
                  secureTextEntry
                  returnKeyType="done"
                  value={password}
                />
              </View>
            )}
            <ButtonIndex
              containerStyle={styles.signUpButton(theme)}
              text={Languages.signup.toUpperCase()}
              onPress={this._onSignUpHandle}
              isLoading={isFetching}
            />
          </View>
        </ScrollView>
      </KeyboardAvoidingView>
    );
  }
}

const styles = {
  container: {
    flexGrow: 1,
    backgroundColor: Color.background,
  },
  formContainer: {
    paddingHorizontal: Styles.width * 0.1,
  },
  logoWrap: {
    ...Styles.Common.ColumnCenter,
    flexGrow: 0.55,
  },
  logo: {
    width: 200,
    height: (Styles.width * 0.8) / 2,
  },
  label: {
    fontWeight: "bold",
    fontSize: Styles.FontSize.medium,
    color: Color.blackTextPrimary,
    marginTop: 20,
  },
  inputWrap: {
    flexDirection: "row",
    alignItems: "center",
    borderColor: Color.blackTextDisable,
    borderWidth: 1,
    marginBottom: 10,
    borderRadius: 10,
  },
  input: {
    color: Color.blackTextPrimary,
    borderColor: "#9B9B9B",
    height: 44,
    padding: 10,
    flex: 1,
    textAlign: I18nManager.isRTL ? "right" : "left",
    letterSpacing: 1,
    fontSize: 15,
  },
  signUpButton: (theme) => ({
    marginTop: 20,
    backgroundColor: theme.primaryColor,
    elevation: 1,
  }),
  switchWrap: {
    ...Styles.Common.RowCenterLeft,
    marginTop: 10,
  },
  text: {
    marginLeft: 10,
    color: Color.blackTextSecondary,
  },
};

const commonInputProps = {
  style: styles.input,
  underlineColorAndroid: "transparent",
  placeholderTextColor: Color.blackTextSecondary,
};

**Comment by luyx2412** [comment]
Hi @sebaitu11 Please open the debug and log `this.props` and check about the register function. I saw your file included the `register` function.

Thanks

**Comment by sebaitu11** [comment]
Hi @luyx2412 , I did that and this.props.register is a function, I put a debugger and 
this.props.register(user).then((data) => {
      if (data) {
        toast(Languages.SignUpSuccess);
        this.props.navigation.goBack(null);
      }
    });

Cannot read property 'then' of undefined but this.props.register it is a function, the user object is also ok

**Comment by luyx2412** [comment]
Hi @sebaitu11 Maybe something was wrong in function return, so can you debug in `src/redux/user/operations.js` line 42 and log catch about the error?
![image](https://user-images.githubusercontent.com/8909619/89705639-315ac280-d989-11ea-84f1-4eae6c20b004.png)

Thanks

**Comment by sebaitu11** [comment]
Hi @luyx2412  so It was because in the GraphqlApi.createCustomer, mine code said AdminApi.createCustomer, so i copy your code and it works fine, but when I register susccesfully it doesn't auto login it says register ok but I have to login with my credentials, also Im having problems with the keyboard when I type text It shows a blank space between the keyboard and the input 

![Captura de pantalla de 2020-08-08 09-09-53](https://user-images.githubusercontent.com/4778923/89711244-fe97d680-d956-11ea-9ab5-520c13ba5d8b.png)

Thanks for all

**Comment by luyx2412** [comment]
Hi @sebaitu11 Please debug when register success, the flow should be dispatch to `registerSuccess` same the screenshot.
![image](https://user-images.githubusercontent.com/8909619/89906305-6aa76280-dc15-11ea-89c0-3cc4eaf27ef1.png)

- About the keyboard, you can change the props to suitable for your app. This is the document about it https://reactnative.dev/docs/keyboardavoidingview
![image](https://user-images.githubusercontent.com/8909619/89906412-8f033f00-dc15-11ea-8e4b-2677608e49d3.png)

Thanks
