### ISSUE TITLE
Error in product fluxstore 1.7.5

### ISSUE THREAD

**Issue by mercadocerouno** [inspireui/support#3909]
Recently update to the fluxstore 1.7.5 the project its running but when running and select a product this error appear, only change the api and the url in config.dart

<img width="1408" alt="Screen Shot 2020-06-25 at 9 26 42 AM" src="https://user-images.githubusercontent.com/66270970/85760611-ddd93180-b6c6-11ea-8ada-480f31e9fa03.png">

══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
The following NoSuchMethodError was thrown while handling a gesture:
The method 'toJson' was called on null.
Receiver: null
Tried calling: toJson()

When the exception was thrown, this was the stack:
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      Product.toJson (package:fstore/models/product/product.dart:377:22)
#2      RecentModel.addRecentProduct (package:fstore/models/recent_product.dart:16:21)
#3      ProductCard.onTapProduct (package:fstore/widgets/product/product_card_view.dart:68:54)
#4      ProductCard.build.<anonymous closure> (package:fstore/widgets/product/product_card_view.dart:142:31)
#5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:184:24)
#6      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:524:11)
#7      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:284:5)
#8      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:256:7)
#9      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:158:27)
#10     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:224:20)
#11     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:200:22)
#12     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:158:7)
#13     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:104:7)
#14     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:88:7)
#18     _invoke1 (dart:ui/hooks.dart:267:10)
#19     _dispatchPointerDataPacket (dart:ui/hooks.dart:176:5)
(elided 3 frames from dart:async)

Handler: "onTap"
Recognizer:
  TapGestureRecognizer#796b5
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by gesture ═══════════════════════════════════════════════════════════════
The following NoSuchMethodError was thrown while handling a gesture:
The method 'toJson' was called on null.
Receiver: null
Tried calling: toJson()

When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      Product.toJson (package:fstore/models/product/product.dart:377:22)
#2      RecentModel.addRecentProduct (package:fstore/models/recent_product.dart:16:21)
#3      ProductCard.onTapProduct (package:fstore/widgets/product/product_card_view.dart:68:54)
#4      ProductCard.build.<anonymous closure> (package:fstore/widgets/product/product_card_view.dart:142:31)
...
Handler: "onTap"
Recognizer: TapGestureRecognizer#796b5
  debugOwner: GestureDetector
  state: ready
  won arena
  finalPosition: Offset(57.9, 253.7)
  finalLocalPosition: Offset(51.9, 157.7)
  button: 1
  sent tap down
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by ameenbadri7** [comment]
again @mercadocerouno 

Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
@mercadocerouno - try to remove the existing app on simulator and test again

**Comment by mercadocerouno** [comment]
I tried what you mention and also try wiping the data of the simulator and occur the same error

**Comment by minhcasi** [comment]
Thank you for a quick response - we will have a check on your config and let you know

**Comment by philipvu30** [comment]
Hi,

I was unable to test due to incorrect consumer_key and consumer_secret with the files you provided.

**Comment by mixkey23** [comment]
Same bug Here. I think it comes from your mstore api plugin recent update

The error is on ontap method for product cards, 
"List<Dynamic> is not a su type of List<Product>

All was working fine to me too on 1.7.5 and by the grace of god I have not yet published the app

**Comment by mercadocerouno** [comment]
> Hi,
> 
> I was unable to test due to incorrect consumer_key and consumer_secret with the files you provided.

ok, and where i can send you again the archives?

**Comment by philipvu30** [comment]
Hi @mercadocerouno @mixkey23 ,

Please send the common and config folders to my email: toan@inspireui.com. I'll help you to check the issues.

Thank you.

**Comment by mercadocerouno** [comment]
> Hi @mercadocerouno @mixkey23 ,
> 
> Please send the common and config folders to my email: [toan@inspireui.com](mailto:toan@inspireui.com). I'll help you to check the issues.
> 
> Thank you.

Ok, already send you an email with that achives

**Comment by philipvu30** [comment]
Hi,

In lib/models/product/product.dart add "?" after the "store"
![image](https://user-images.githubusercontent.com/54442328/86454892-1a9dcc00-bd4a-11ea-9d90-ca6d8b5c98a6.png)

**Comment by mixkey23** [comment]
> Hi,
> 
> In lib/models/product/product.dart add "?" after the "store"
> ![image](https://user-images.githubusercontent.com/54442328/86454892-1a9dcc00-bd4a-11ea-9d90-ca6d8b5c98a6.png)

I tested, and it worked, now products open but same error `list<Dynamic> not subtype of list<Product>`  keep showing on console this is normal?

**Comment by mercadocerouno** [comment]
Any news about this error?

**Comment by mixkey23** [comment]
> Any news about this error?

I join the same question

**Comment by philipvu30** [comment]
Hi,

This error occurs because that item does not belong to any store. Please add this code `?? '' `after store.name in file lib/widgets/product/cart_item.dart to ignore this error or you could assign that item to a store.

Thank you.

![image](https://user-images.githubusercontent.com/54442328/87112096-30a11480-c295-11ea-9be2-4adee52bf07f.png)

**Comment by devienguilde** [comment]
Follow this
