### ISSUE TITLE
[MStore] Razorpay Integration fail 404 error page

### ISSUE THREAD

**Issue by Relimer-Technologies** [inspireui/support#391]
Mandatory Info (please complete the following information):

Product: [e.g. MStore, ListApp]
M Store Pro
Purchase Code: d98eb201-aba4-4c76-a0a1-cbd67415737d
Your Purchased Code: [get from https://codecanyon.net/downloads]
(we may not reply if you are not our customer)
Describe the issues
Hello,

Good Morning, I have purchased M Store Pro from Envato. I have done all the setup required... I have installed all of the required tools... I have tried to integrate Razorpay into the website and I even followed the tutorial video... First, when I have done the setup I get the 404-page error after the checkout... Then I have tried to find the solution in the FAQ and I got this link...

#38 (comment)

I want to reopen the issue which is closed without providing the proper solution to my problem... The issue is as follows:

https://github.com/inspireui/support/issues/350

I have tried to create the page with page attribute as Page Custom Template... But the page is not getting published... Please find the solution to my problem.

Thank You.

**Comment by luyx2412** [comment]
Hi @Relimer-Technologies Please using the second solution https://docs.mstore.io/faq-and-troubleshooting#404-error-page-when-process-the-payment to fix the issue.
![image](https://user-images.githubusercontent.com/8909619/54249987-a8addc00-4574-11e9-8502-bb4e538da7a4.png)

Thnks

**Comment by minhcasi** [comment]
@Relimer-Technologies could you resend your admin login to our private chat box - http://inspireui.com - and copy the link here, we will help to check it again the solution - thanks

**Comment by Relimer-Technologies** [comment]
Hello, @minhcasi  I have sent the login details and even attached this issue link in the conversation... I hope I will get a solution to this problem soon... Thank You

**Comment by Relimer-Technologies** [comment]
Hello, @luyx2412  I have tried both the solution and even discussed it with @minhcasi in my previous registered issue, but I was unable to get the solution for it... You can see our conversation in the previous issue which link is given below... Thank You.

https://github.com/inspireui/support/issues/350

**Comment by minhcasi** [comment]
Detail login: https://app.intercom.io/a/apps/xro9xnfd/inbox/inbox/2664005/conversations/21180935007

**Comment by Relimer-Technologies** [comment]
I don't have an Intercom Account I can Skype you the Hosting details... I have your id in the Skype... You want me to send my admin login details over there...?

**Comment by Relimer-Technologies** [comment]
@minhcasi  Please reply soon... Thank You

**Comment by Relimer-Technologies** [comment]
Hello, @minhcasi ... I have tried integrating PayUmoney and Paypal for the App... But none of it was successful... Kindly provide me with the best solution possible... Thank You

**Comment by Relimer-Technologies** [comment]
Hello, @minhcasi ... I have tried the Second solution again and now I am able to publish the page using page custom template from the drop down... But the issue is not resolved yet... When I click on razorpay in the checkout page... Now I don't get 404 Error... Now I get a blank page which redirects to nowhere... Kindly help me out with this problem... I am waiting for your reply... Thank You

**Comment by minhcasi** [comment]
Hi @Relimer-Technologies  the login provide for checking on admin does not work, could you help to reset it again, we will help to check you backend side, also attach your config file here so that we could investigate and debug - thanks

**Comment by Relimer-Technologies** [comment]
Hi, @minhcasi  I have found that the mstore-checkout-template.php filename is taken as the string for the templates... When I changed the name of the file as well as the code in it... It worked for me... and now I am able to get the checkout page... Thank You
