### ISSUE TITLE
FluxStore Problems

### ISSUE THREAD

**Issue by phcaraujo** [inspireui/support#3910]
1. Whenever I open the app it’s going to the home page (like i'm opening it for the first time)
Image - http://prnt.sc/t6f1vy

2. Whenever I open the app he is asking to log in again (even though I did it in the previous access) and the login is giving error. I can enter normally, however, this error always happens
Image https://prnt.sc/t6f2pd

3. My registration screen has an error
http://prnt.sc/t6f28j

4. Google login is not working
Image mobile: http://prnt.sc/t6f2ev
Image flutter: http://prnt.sc/t6f2oh

FluxStore version: latest

**Comment by ameenbadri7** [comment]
hello, @phcaraujo welcome back.

1-  on `lib\common\config\onboarding.dart` file you can remove it at all by the` list onBoardingData ` like this 
```
List onBoardingData = [
  // {
  //   "title": "مرحباً بك في بصمة فون",
  //   "image": "assets/images/fogg-delivery-1.png",
  //   "desc": "Fluxstore is on the way to serve you. "
  // },
  // {
  //   "title": "منتجات عصرية فخمة مناسبة للجميع",
  //   "image": "assets/images/fogg-uploading-1.png",
  //   "desc":
  //       "See all things happening around you just by a click on your phone. "
  //           "Fast, convenient and clean."
  // },
  // {
  //   "title": "لنبدأ مسيرة التسوق",
  //   "image": "fogg-order-completed.png",
  //   "desc": "Waiting no more, let's see what we get!"
  // },
];
```
or just : 
```
List onBoardingData = [];
```
also, check this [guide ](https://docs.inspireui.com/fluxstore/customization/#7-onboarding-and-login-mode)for more info.

2-  please double-check this guide to fix any signup error
[1](https://docs.inspireui.com/fluxstore/sign-in/) 
[2](https://github.com/inspireui/support/issues/3151)
and if it's returning anything please reset your woo-commerce secret keys by using this [guides ](https://docs.inspireui.com/fluxstore/woocommerce-setup/).

2 and 3 - it's all connected in one problem firebase sign-in. 

try those and let us know if you still have problems. 

thank you

**Comment by ameenbadri7** [comment]
I'm sorry to close this ticket as there is no response or active conversation, 
please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
