### ISSUE TITLE
how can i add AdMob on my app flux MV and ads in my app on store google play

### ISSUE THREAD

**Issue by emadpost2016** [inspireui/support#3911]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

How can I run ads on my app after uploading to Google Play

1.7.5 version
1.17.4 flutter version

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support 
- http://verify.inspireui.com/
- please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
verified 

@emadpost2016 - could you help to check this guide - https://docs.inspireui.com/fluxstore/Admod-FacebookAd/

**Comment by emadpost2016** [comment]
how i can change  rate my app from flux app to my app

Because when I want to rate my application on Google Play, I will be
transferred to flux app

‫في الجمعة، 26 يونيو 2020 في 4:20 ص تمت كتابة ما يلي بواسطة ‪Minh Pham‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by ameenbadri7** [comment]
go to your fluxstore lib folder `lib\common\config\general.dart`

you would see this 

const kStoreIdentifier = {
  "android": "write your own app name here like com.amin.aminbadri",
  "ios": "and here your ios Identifier"
};

thank you

**Comment by emadpost2016** [comment]
شكرا لك ولكن هل يمكن أن تشرح لى خطوة كيفية إضافة اعلانات جوجل وفيس بوك على
تطبيقى مع العلم انا عملت حساب على admob  ووضعت ip التطبيق والإعلانات فى
مكانها ووضعت اى بى التطبيق فى string ولكن الإعلانات لا تظهر أيضا ارجو شرح
توضيحية خطوة خطوة

**Comment by emadpost2016** [comment]
Hi how i can translate register page vendor to arabic
and how i can add in my app ads from admob

‫في الجمعة، 26 يونيو 2020 في 11:25 م تمت كتابة ما يلي بواسطة ‪Emad Fouad‬‏
<‪emad.post2016@gmail.com‬‏>:‬

> شكرا لك ولكن هل يمكن أن تشرح لى خطوة كيفية إضافة اعلانات جوجل وفيس بوك على
> تطبيقى مع العلم انا عملت حساب على admob  ووضعت ip التطبيق والإعلانات فى
> مكانها ووضعت اى بى التطبيق فى string ولكن الإعلانات لا تظهر أيضا ارجو شرح
> توضيحية خطوة خطوة
>
> On Fri, Jun 26, 2020, 11:00 PM amin badri أمين بدري <
