### ISSUE TITLE
Categories and posts are synced but products from woocommerce are not showing in app

### ISSUE THREAD

**Issue by 69megalodon96** [inspireui/support#3912]
+ Detail Issues: Products are not showing in app on emulator (android studio). Tried on fluxstore builder and showing. 
+ Product & version: Fluxstore vendor app latest version
+ Flutter version: Flutter 1.17.4
+ Testing Device/Simulator: Pixel 3a XL emulator
+ Screenshot issues (drag the file to attach here): 

<img width="1440" alt="Screenshot 2020-06-25 at 20 46 11" src="https://user-images.githubusercontent.com/67436742/85780443-eb250900-b724-11ea-9462-c0eda59d4e79.png">

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support

- http://verify.inspireui.com/
- please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
@69megalodon96 - could you try to use the latest fluxstore mv `1.7.5`?

**Comment by 69megalodon96** [comment]
How can i update without loosing data ?



Poslano iz pametnega telefona Samsung Galaxy.



-------- Izvirno sporočilo --------
Od: Minh Pham <notifications@github.com>
Datum: 26. 6. 20 04:26 (GMT+01:00)
Za: inspireui/support <support@noreply.github.com>
Kp: 69megalodon96 <martin.krc96@hotmail.com>, Mention <mention@noreply.github.com>
Zadeva: Re: [inspireui/support] Categories and posts are synced but products from woocommerce are not showing in app (#3912)


@69megalodon96<https://github.com/69megalodon96> - could you try to use the latest fluxstore mv 1.7.5?

**Comment by AbimaelASilva** [comment]
Good night. I have the same problem, woocommerce products are not displayed in the application.

You suggested using the mv 1.7.5 fluxstore.

Can you please leave the link for this version here?

**Comment by minhcasi** [comment]
@69megalodon96 - could you try this link https://medium.com/@inspireui/how-to-upgrade-fluxstore-projects-by-using-git-cebde7489ea6

**Comment by HouseDevStores** [comment]
Good afternoon.

I tried to start the tutorial you suggested:

https://medium.com/@inspireui/how-to-upgrade-fluxstore-projects-by-using-git-cebde7489ea6

But I came across the 404 error, the page doesn't exist or I don't have permission, even logged into my GitLab account, I encounter this error.

![erroFlux](https://user-images.githubusercontent.com/67519511/85930974-20aa2d80-b8b0-11ea-8b07-a577b4bb145d.png)

**Comment by HouseDevStores** [comment]
How to send a request to access Gitlab after purchasing the font?

**Comment by 69megalodon96** [comment]
i already have latest version 1.7.5 and there is still issue. Please provide solution asap because something like product not showing mean big issue.

**Comment by philipvu30** [comment]
Hi,

Please replace this file [woo_commerce.dart.zip](https://github.com/inspireui/support/files/4855579/woo_commerce.dart.zip) in lib/services/woo_commerce.dart  

This happens because there is something wrong with your rest API. The response of the store returns errors.
![image](https://user-images.githubusercontent.com/54442328/86201721-7b7ea600-bb8a-11ea-8e98-15a60c74b2e9.png)

**Comment by philipvu30** [comment]
Closed as no response in 2 days. 

If you are happy with our services/support, would you mind rating us on your [download page](https://codecanyon.net/downloads)?
We truly appreciate your help.
