### ISSUE TITLE
Images not displaying in app

### ISSUE THREAD

**Issue by nikitaaror** [inspireui/support#3913]
The flutter app doesn't display images. It displays the following error-
FormatException: Scheme not starting with alphabetic character (at character 1)
I/flutter (22437):  http://demo2.signitydemo.in/marketplace/wp-content/uploads/2020/06/PURI-D-...
I/flutter (22437): ^
I/flutter (22437): Bad state: Failed to load  http://demo2.signitydemo.in/marketplace/wp-content/uploads/2020/06/PURI-D-350-WH-03-medium.jpg.

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support 
- http://verify.inspireui.com/ 
- please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
verify ✅

**Comment by minhcasi** [comment]
Could you try to override the content from `lib/common/tools.dart` to see if it could fix the issue - thanks

[tools.dart.txt](https://github.com/inspireui/support/files/4844322/tools.dart.txt)

**Comment by nikitaaror** [comment]
Hi,
I am facing another issue on login & register. I am getting this error - 
{"code":"rest_forbidden","message":"Sorry, you are not allowed to do that.","data":{"status":401}}

**Comment by minhcasi** [comment]
@nikitaaror - pls try this solution to fix the 401 issues, this is a common problem when your Rest API not working 

https://github.com/WordPress/application-passwords/wiki/Basic-Authorization-Header----Missing
