### ISSUE TITLE
Make fluxbuilder design look like demo for Multi Vendor

### ISSUE THREAD

**Issue by Benhur3000** [inspireui/support#3914]
Detail Issues: 

1) My home page is missing images or the images look messed up when I upload my json file to fluxbuilder. 

2) The category page on fluxbuilder is missing the tabs for "category" and " stores" it only shows stores. I don't see a widget to achieve this look in fluxbuilder. 

3) Empty Categories are not showing in the category page.

Product & version: 1.7.5 (or pre-1.7.6)

Flutter (or React Native) version: 1.17.4- stable

Testing Device/Simulator: emulator and fluxbuilder

Screenshot issues:
![AndoidEmulator Home](https://user-images.githubusercontent.com/67126788/85802870-139c0b80-b703-11ea-8231-5bccec7ddf07.PNG)
![Category Shop Page](https://user-images.githubusercontent.com/67126788/85802877-1696fc00-b703-11ea-90f9-2275b3a52939.PNG)
![Fluxbuilder Home](https://user-images.githubusercontent.com/67126788/85802880-1860bf80-b703-11ea-8a4d-55dc1a086c9f.PNG)

**Comment by vumanhsn97** [comment]
@Benhur3000 
Please download latest version in https://github.com/inspireui/fluxbuilder/releases: https://tppr.me/2Uw5C
Make sure you choose correct app: https://tppr.me/jMrGJ

**Comment by Benhur3000** [comment]
Hi I'm using a WordPress website though. I'm suppose to choose woocommerce
multi instead?

**Comment by vumanhsn97** [comment]
WordPress is Fluxnew App. Follow this: https://tppr.me/jMrGJ and https://fluxbuilder.com/
