### ISSUE TITLE
i got error when copy style from builder

### ISSUE THREAD

**Issue by reanyouda** [inspireui/support#3917]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
![image](https://user-images.githubusercontent.com/58130055/85824407-f0786700-b7a9-11ea-9d0a-61bb1b928d81.png)

+ Product & version: 1.4.1
+ Flutter (or React Native) version:  1.20.0
+ Testing Device/Simulator: IOS
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by vumanhsn97** [comment]
@reanyouda 
Can you publish your config.json file?

**Comment by reanyouda** [comment]
How ?

**Comment by reanyouda** [comment]
Yeah but after copy and paste it error

**Comment by vumanhsn97** [comment]
@reanyouda 
Past this data to config.json file and drag this file in this issue

**Comment by reanyouda** [comment]
here

**Comment by vumanhsn97** [comment]
@reanyouda 
Add this code in bottom of your config file: 
"SplashScreen": {
    "type": "flare",
    "data" : "assets/images/splashscreen.flr"
  }
https://tppr.me/9BPuO

Like this attach
[config_en.json.zip](https://github.com/inspireui/support/files/4836016/config_en.json.zip)

**Comment by reanyouda** [comment]
[image: Screen Shot 2020-06-27 at 1.16.49 PM.png]
in builder is ok but in emulator is error
 -  how can i disable ads ?
- how can i adjust font size in page details ?

**Comment by reanyouda** [comment]
tap : profile is show different from my source code ?
in builder so setting page ? and in emulator show login page ?

**Comment by vumanhsn97** [comment]
@reanyouda 
Disable ads: Change file in this attach 
[disable_ads.zip](https://github.com/inspireui/support/files/4843662/disable_ads.zip)

Font size: In lib/widget/blog/detailed_blog_half_image.dart change code look like this: https://tppr.me/1jXfU

Settings and Profile page: Make sure you update latest Fluxnews version

**Comment by reanyouda** [comment]
Yes I download latest version of fluxnews from store

**Comment by vumanhsn97** [comment]
@reanyouda 
Can you share your config.json file and your website url?

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
