### ISSUE TITLE
Checkout Process opening webview with lost session

### ISSUE THREAD

**Issue by raidarmax** [inspireui/support#3918]
Hi

I am running the app (still in development) and everything works fine except for the checkout process. When I get to checkout, (After inputting the delivery address and all other required info) it opens a webview of the site without an active session or any data put in. The site loaded into the app also looks quite terrible. How can I get payments to load within the app and complete the process without having to leave the app? My site is [PartyHub ](https://partyhub.co.ke)

![Screenshot_20200626-100655](https://user-images.githubusercontent.com/67455609/85832580-09c4e780-b799-11ea-9f2b-f00d8b7f7037.png)
![Screenshot_20200626-100716](https://user-images.githubusercontent.com/67455609/85832586-0b8eab00-b799-11ea-8f8f-efe3f93aa737.png)
![Screenshot_20200626-100752](https://user-images.githubusercontent.com/67455609/85832589-0cbfd800-b799-11ea-9bdd-656b956372ed.png)
![Screenshot_20200626-101751](https://user-images.githubusercontent.com/67455609/85832595-0df10500-b799-11ea-8669-2bd9b73f040f.png)
![Screenshot_20200626-100628](https://user-images.githubusercontent.com/67455609/85832597-0e899b80-b799-11ea-9cd1-fc4b3765e59e.png)

Kindly assist.

**Comment by henry2327** [comment]
Hola tenia ese mismo problema tuve que implementar Stripe, Nativo en la aplicacion para solucionarlo fluxstore pro

**Comment by minhtruong315** [comment]
Hi @raidarmax can u send me admin info via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/3918

**Comment by minhtruong315** [comment]
Supported via the skype
