### ISSUE TITLE
verify Mstore API plugins. 

### ISSUE THREAD

**Issue by alolahussein** [inspireui/support#3919]
hello when I verify mstore API plugin and add purchase code show this error 

![screencapture-reemstore-net-wp-admin-admin-php-2020-06-26-11_11_12](https://user-images.githubusercontent.com/59389912/85835769-4810d580-b79e-11ea-8043-c27870d37fbb.png)

**Comment by alolahussein** [comment]
and when update plugin to 2.6.4v 
need email which, email I must enter 
and when I add purchase code and email nothing show or change

**Comment by minhcasi** [comment]
@minhtruong315 - pls help to fix this issue as a high priority - thank you!

**Comment by minhtruong315** [comment]
@alolahussein please update the latest version mstore api plugin to fix this issue. Let me know the result
Thanks

**Comment by alolahussein** [comment]
Hello @minhcasi it's verified thanks
