### ISSUE TITLE
MStore Pro Build Failed on Xcode

### ISSUE THREAD

**Issue by Jegufull** [inspireui/support#392]
**Required Info (please complete the following information):**
 - Product: [e.g. MStore, ListApp]
 - Your Purchased Code: [get from https://codecanyon.net/downloads]
(we may not reply if you are not our customer)

**Describe the bug**

**Screenshots**

**Additional context**
Add any other detail logs about the problem here.
If possible please share your config.js that use for the app setting

**Comment by Jegufull** [comment]
Product: [MStore-Pro V3.7.0]
Purchased Code: [36e9cfd7-96da-413e-b43f-83ef03bed15b]

Hello, I get the following error. I reinstalled the libraries, cleaned the project and continued the same error, what could I do?

clang: error: no such file or directory: '/Users/jeimergutierrez/Library/Developer/Xcode/DerivedData/mstore-cbxzvecnrrutzsbaulrxchzjfqma/Build/Products/Debug-appletvsimulator/libBVLinearGradient.a'
![Captura de pantalla 2019-03-12 a la(s) 7 49 14 a  m](https://user-images.githubusercontent.com/47310507/54213886-2e695300-44b3-11e9-9fdb-f575c490fba9.png)

**Comment by luyx2412** [comment]
Hi @Jegufull Make sure you linked library to project with `react-native link`. This is a document about link libraries https://facebook.github.io/react-native/docs/linking-libraries-ios

Thanks

**Comment by Jegufull** [comment]
Hi, The library is linked.

![Captura de pantalla 2019-03-12 a la(s) 10 00 56 p  m](https://user-images.githubusercontent.com/47310507/54250575-694ea380-4512-11e9-95ec-a4f200849d4e.png)

**Comment by Jegufull** [comment]
hi, I installed the new version and now I have this error. What could I do?

ld: warning: directory not found for option '-F/Users/jeimergutierrez/Library/Developer/Xcode/DerivedData/mstore-elojsfhkxxbufbdyvcecguupjxwp/Build/Products/Debug-iphonesimulator/Bolts'
ld: warning: directory not found for option '-F/Users/jeimergutierrez/Library/Developer/Xcode/DerivedData/mstore-elojsfhkxxbufbdyvcecguupjxwp/Build/Products/Debug-iphonesimulator/FBSDKCoreKit'
ld: warning: directory not found for option '-F/Users/jeimergutierrez/Library/Developer/Xcode/DerivedData/mstore-elojsfhkxxbufbdyvcecguupjxwp/Build/Products/Debug-iphonesimulator/FBSDKLoginKit'
ld: warning: directory not found for option '-F/Users/jeimergutierrez/Library/Developer/Xcode/DerivedData/mstore-elojsfhkxxbufbdyvcecguupjxwp/Build/Products/Debug-iphonesimulator/FBSDKShareKit'
ld: framework not found Pods_mstore
clang: error: linker command failed with exit code 1 (use -v to see invocation)

![Captura de pantalla 2019-03-13 a la(s) 8 16 20 p  m](https://user-images.githubusercontent.com/47310507/54324962-ed199600-45cd-11e9-87bb-e0c6fa28161c.png)

**Comment by luyx2412** [comment]
Hi @Jegufull Please go to ios folder and run `pod install`, clean project and rerun again. Your project did not install pod.

Thanks

**Comment by Jegufull** [comment]
Hi, I did it and the error continues

**Comment by luyx2412** [comment]
Hi @Jegufull Can you take the screenshot to specific error.

Thanks
