### ISSUE TITLE
mstore-api issue after installation 

### ISSUE THREAD

**Issue by smdanishali89** [inspireui/support#3920]
after installing mstore-api I am getting following errors
Notice: register_rest_route was called incorrectly. Namespace must not start or end with a slash. Please see Debugging in WordPress for more information. (This message was added in version 5.4.2.) in /var/www/wordpress/wp-includes/functions.php on line 5167

<img width="1279" alt="Screenshot 2020-06-26 at 3 47 35 PM" src="https://user-images.githubusercontent.com/7643171/85849428-5e318c80-b7c4-11ea-820b-f179c67b2f2e.png">

mstore pro is also not working due to this issue.

mstore-api version 2.6.4
mstore pro version 4.0

**Comment by minhtruong315** [comment]
Hi @smdanishali89 can u send me admin info via email: truong@inspireui.com
with subject:  https://github.com/inspireui/support/issues/3920

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
