### ISSUE TITLE
Cannot generate apk - flutter dokan app

### ISSUE THREAD

**Issue by Rosvaldas** [inspireui/support#3921]
Flutter dokan app.
I cannot generate the apk - it brings this error:

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app_settings:compileReleaseAidl'.
> Failed to find Platform SDK with path: platforms;android-R

I think this is related to some android sdk versions not working properly. Because if I put the below code at the end of build.gradle file in android folder, it works, but still doesnt generate the apk:
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"

    project.evaluationDependsOn(':app')

    afterEvaluate {project ->
        if (project.hasProperty("android") && project.property("android").compileSdkVersion.equals("android-R")) {
            android {
                compileSdkVersion 30
            }
        }
    }
}

So please take care of this issue. All your users have the same problem, because of this new android sdk.
Very looking forward to your reply and thank you.

**Comment by Rosvaldas** [comment]
Additional info:
if I put the mentioned code at the end of build.gradle file in android folder, it gives me this error:

Codepoint 58848 not found in font, aborting.

Target aot_android_asset_bundle failed: FontSubset error: Font subsetting failed with exit code -1.
build failed.


Please help. :(

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by Rosvaldas** [comment]
> Thank you for the feedback.
> 
> Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.
> 
> We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!
> 
> > **[Google Forms - create and analyze surveys, for free.](http://verify.inspireui.com/)**Create a new survey on your own or with others at the same time. Choose from a variety of survey types and analyze results in Google Forms. Free from Google.

Just sent it. Thank you!

**Comment by ameenbadri7** [comment]
could you look for this [issue ](https://github.com/inspireui/support/issues/3708)
if it's not working please let up know so we can give you more help on this issue.
thank you for your patience.

**Comment by Rosvaldas** [comment]
Excuse me ? There is no explanation at all what to do. Please update your
software and adapt it to new android sdk.

‪On Fri, Jun 26, 2020 at 8:51 PM ‫amin badri أمين بدري‬‎ <
notifications@github.com> wrote:‬

**Comment by ameenbadri7** [comment]
thank you for your patience with us due to this hard times, we are having a shortage in staff. 
I will deliver your issue to a higher developer to fix this issue.
for now, it's working with old SDKs like 28-29 and our team try his best 
thank you.

**Comment by minhcasi** [comment]
Pls try the solution in the meantime - https://github.com/flutter/flutter/issues/59355#issuecomment-643482076 - we will release the patching for this config. 

Also make sure to update your Android Studio same as below config

<img width="1002" alt="Screen Shot 2020-06-27 at 08 13 12" src="https://user-images.githubusercontent.com/1459805/85911236-38e96080-b84e-11ea-9aa7-83e170878735.png">
<img width="992" alt="Screen Shot 2020-06-27 at 08 13 18" src="https://user-images.githubusercontent.com/1459805/85911240-3ab32400-b84e-11ea-90be-4039d75a0d5c.png">

**Comment by Rosvaldas** [comment]
Hi,

thank you for your reply.

I am getting a lot of other errors, I have simply followed the
documentations. Is it possible at all to build both apps on windows? There
is nothing explained about xcode, not even mentioned. You just do it in the
video ant that's it. I am on windows and now I am getting these errors:

Compiler message:
Error: Could not resolve the package 'cloud_firestore' in
'package:cloud_firestore/cloud_firestore.dart'.
lib/models/user/user_model.dart:2:8: Error: Not found:
'package:cloud_firestore/cloud_firestore.dart'
import 'package:cloud_firestore/cloud_firestore.dart';
       ^
lib/vendor/chat/conversations.dart:2:8: Error: Not found:
'package:cloud_firestore/cloud_firestore.dart'
import 'package:cloud_firestore/cloud_firestore.dart';
       ^
lib/vendor/chat/chat_screen.dart:4:8: Error: Not found:
'package:cloud_firestore/cloud_firestore.dart'
import 'package:cloud_firestore/cloud_firestore.dart';
       ^
Error: Could not resolve the package 'image_picker' in
'package:image_picker/image_picker.dart'.
lib/vendor/chat/chat_typing.dart:1:8: Error: Not found:
'package:cloud_firestore/cloud_firestore.dart'
import 'package:cloud_firestore/cloud_firestore.dart';
       ^
lib/vendor/chat/messages.dart:1:8: Error: Not found:
'package:cloud_firestore/cloud_firestore.dart'
import 'package:cloud_firestore/cloud_firestore.dart';
       ^
Error: Could not resolve the package 'firestore_ui' in
'package:firestore_ui/firestore_ui.dart'.
lib/vendor/products/widgets/select_image.dart:5:8: Error: Not found:
'package:image_picker/image_picker.dart'
import 'package:image_picker/image_picker.dart';
       ^
lib/vendor/chat/messages.dart:2:8: Error: Not found:
'package:firestore_ui/firestore_ui.dart'
import 'package:firestore_ui/firestore_ui.dart';
       ^
lib/vendor/chat/messages.dart:81:9: Error: Type 'DocumentSnapshot' not
found.
  final DocumentSnapshot document;
        ^^^^^^^^^^^^^^^^
lib/vendor/chat/messages.dart:112:9: Error: Type 'DocumentSnapshot' not
found.
  final DocumentSnapshot document;
        ^^^^^^^^^^^^^^^^
lib/vendor/chat/conversations.dart:13:20: Error: Getter not found:
'Firestore'.
final _fireStore = Firestore.instance;
                   ^^^^^^^^^
lib/vendor/chat/chat_screen.dart:15:20: Error: Getter not found:
'Firestore'.
final _fireStore = Firestore.instance;
                   ^^^^^^^^^
lib/vendor/chat/chat_typing.dart:6:20: Error: Getter not found: 'Firestore'.
final _fireStore = Firestore.instance;
                   ^^^^^^^^^
lib/vendor/chat/messages.dart:8:20: Error: Getter not found: 'Firestore'.
final _fireStore = Firestore.instance;
                   ^^^^^^^^^
lib/models/user/user_model.dart:161:13: Error: The getter 'Firestore' isn't
defined for the class 'UserModel'.
 - 'UserModel' is from 'package:fstore/models/user/user_model.dart'
('lib/models/user/user_model.dart').
Try correcting the name to the name of an existing getter, or defining a
getter or field named 'Firestore'.
      await Firestore.instance
            ^^^^^^^^^
Running Gradle task 'assembleRelease'...
lib/vendor/chat/conversations.dart:97:26: Error: 'DocumentSnapshot' isn't a
type.
    return FutureBuilder<DocumentSnapshot>(
                         ^^^^^^^^^^^^^^^^
lib/vendor/chat/conversations.dart:100:48: Error: 'DocumentSnapshot' isn't
a type.
          (BuildContext context, AsyncSnapshot<DocumentSnapshot> snapshot) {
                                               ^^^^^^^^^^^^^^^^
lib/vendor/products/widgets/select_image.dart:26:28: Error: The method
'ImagePicker' isn't defined for the class 'SelectImage'.
 - 'SelectImage' is from
'package:fstore/vendor/products/widgets/select_image.dart'
('lib/vendor/products/widgets/select_image.dart').
Try correcting the name to the name of an existing method, or defining a
method named 'ImagePicker'.
    var pickedFile = await ImagePicker().getImage(source:
ImageSource.camera);
                           ^^^^^^^^^^^
lib/vendor/products/widgets/select_image.dart:26:59: Error: The getter
'ImageSource' isn't defined for the class 'SelectImage'.
 - 'SelectImage' is from
'package:fstore/vendor/products/widgets/select_image.dart'
('lib/vendor/products/widgets/select_image.dart').
Try correcting the name to the name of an existing getter, or defining a
getter or field named 'ImageSource'.
    var pickedFile = await ImagePicker().getImage(source:
ImageSource.camera);
                                                          ^^^^^^^^^^^
lib/vendor/products/widgets/select_image.dart:47:28: Error: The method
'ImagePicker' isn't defined for the class 'SelectImage'.
 - 'SelectImage' is from
'package:fstore/vendor/products/widgets/select_image.dart'
('lib/vendor/products/widgets/select_image.dart').
Try correcting the name to the name of an existing method, or defining a
method named 'ImagePicker'.
    var pickedFile = await ImagePicker().getImage(source:
ImageSource.camera);
                           ^^^^^^^^^^^
lib/vendor/products/widgets/select_image.dart:47:59: Error: The getter
'ImageSource' isn't defined for the class 'SelectImage'.
 - 'SelectImage' is from
'package:fstore/vendor/products/widgets/select_image.dart'
('lib/vendor/products/widgets/select_image.dart').
Try correcting the name to the name of an existing getter, or defining a
getter or field named 'ImageSource'.
    var pickedFile = await ImagePicker().getImage(source:
ImageSource.camera);
                                                          ^^^^^^^^^^^
lib/vendor/chat/messages.dart:59:20: Error: The method
'FirestoreAnimatedList' isn't defined for the class '_MessagesStreamState'.
 - '_MessagesStreamState' is from
'package:fstore/vendor/chat/messages.dart'
('lib/vendor/chat/messages.dart').
Try correcting the name to the name of an existing method, or defining a
method named 'FirestoreAnimatedList'.
            child: FirestoreAnimatedList(
                   ^^^^^^^^^^^^^^^^^^^^^
lib/vendor/chat/messages.dart:81:9: Error: 'DocumentSnapshot' isn't a type.
  final DocumentSnapshot document;
        ^^^^^^^^^^^^^^^^
lib/vendor/chat/messages.dart:112:9: Error: 'DocumentSnapshot' isn't a type.
  final DocumentSnapshot document;
        ^^^^^^^^^^^^^^^^



I don't know what else to say.


Thank you,
Rosvaldas

**Comment by Rosvaldas** [comment]
Can you please tell me how can I get this step done on windows? It's
explained on this page:
https://docs.inspireui.com/fluxstore/firebase/#1-push-notifications-via-firebase


[image: xcode.png]

Please tell me.


Very looking forward to your reply and thank you,
Rosvaldas

**Comment by minhcasi** [comment]
@Rosvaldas - could I know if you could build the app on the simulator so far?

The setting on Android will be the same, most of the job will be on your Firebase side, pls try to check the similar guide on https://pub.dev/packages/firebase_messaging

**Comment by Rosvaldas** [comment]
Hi,

I dont know how can we work with this. You cant even understand my
questions, or what? I am not asking how to do it for Android app!! I am
asking how to build the ios app in a Windows machine!!!!



2020 m. birž. 29 d., pr 10:16, Minh Pham <notifications@github.com> rašė:

**Comment by Rosvaldas** [comment]
And I wrote the exact point that is not explained how to do it on a Windows
PC, sir!

2020 m. birž. 29 d., pr 10:21, Rosvaldas Nudas <rosvaldas.nudas@gmail.com>
rašė:

**Comment by Rosvaldas** [comment]
Do you offer a complete set up for some kind of fee?

2020 m. birž. 29 d., pr 10:21, Rosvaldas Nudas <rosvaldas.nudas@gmail.com>
rašė:

**Comment by minhcasi** [comment]
@Rosvaldas - there is no solution to build ios app on window OS, we need to have a Mac OS - thank you!

**Comment by Rosvaldas** [comment]
Oh, ok...

2020 m. birž. 29 d., pr 11:05, Minh Pham <notifications@github.com> rašė:

**Comment by minhcasi** [comment]
Let us know if you have any further question, thank you!

**Comment by rinku1902** [comment]
Getting same issue :
E:\Android\fluxstore-multivendor>flutter build appbundle --target-platform android-arm,android-arm64,android-x64
Codepoint 58848 not found in font, aborting.

http://prntscr.com/u1ghxp

Please Help!

**Comment by IbrahimHd** [comment]
Any help with the above issue please?

**Comment by swappin** [comment]
Same issue here. 

> Getting same issue :
> E:\Android\fluxstore-multivendor>flutter build appbundle --target-platform android-arm,android-arm64,android-x64
> Codepoint 58848 not found in font, aborting.
> 
> http://prntscr.com/u1ghxp
> 
> Please Help!
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/92e5159487cf2851b37ca5c59c5483ce13012b9e/68747470733a2f2f696d6167652e70726e747363722e636f6d2f696d6167652f4f69502d4f5f71795468714144644b327631667734412e706e67">Lightshot**[Screenshot](https://prnt.sc/u1ghxp)**Captured with Lightshot

Same here... Works fine on Emulator but when I try to build APK, I get this. Can somebody help?

**Comment by IbrahimHd** [comment]
Refer to this #4819
