### ISSUE TITLE
error in build gradle file , and can't generate SHA key for firebase - Fluxstore MV

### ISSUE THREAD

**Issue by sadeq90** [inspireui/support#3922]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
**1-In android studio it shows me an error with build.gradle file**
below is the code
`
buildscript {
    repositories {
        // ...
        maven { url 'https://plugins.gradle.org/m2/' } // Gradle Plugin Portal
    }
    dependencies {
        // ...
        // OneSignal-Gradle-Plugin
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.12.6, 0.99.99]'
    }
}

apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    compileSdkVersion 28

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        applicationId "com.smartcodebh.shopn.vendor"
        minSdkVersion 19
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
        resConfigs "en"
    }

    signingConfigs {
        release {
           
            if (System.getenv()["CI"]) { // CI=true is exported by Codemagic
                storeFile file(System.getenv()["FCI_BUILD_DIR"] + "/key.jks")
                storePassword System.getenv()["FCI_KEYSTORE_PASSWORD"]
                keyAlias System.getenv()["FCI_KEY_ALIAS"]
                keyPassword System.getenv()["FCI_KEY_PASSWORD"]
            } else {
                keyAlias keystoreProperties['keyAlias']
                keyPassword keystoreProperties['keyPassword']
                storeFile file(keystoreProperties['storeFile'])
                storePassword keystoreProperties['storePassword']
            }
        }
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.release

            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }

        debug {
            signingConfig signingConfigs.release
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
    implementation 'com.android.support:multidex:1.0.3'
    implementation 'com.google.firebase:firebase-analytics:17.2.2'
}
apply plugin: 'com.google.gms.google-services'
googleServices { disableVersionCheck = true }
`

**2- I connected my app to firebase for SMS login, when I test it I get this error.**
![aa](https://user-images.githubusercontent.com/32711146/85861468-0fd2bc80-b7c9-11ea-8ada-97f504ca5b6f.jpeg)
**I followed the steps here https://developers.google.com/android/guides/client-auth
to generate SHA key, but I dont have .keystore file in my project.**

+ Product & version:
**Fluxstore MV - 1.7.5**
+ Flutter (or React Native) version: 
**Flutter**
+ Testing Device/Simulator: 
**Both**
+ Screenshot issues (drag the file to attach here): 
1- 
![image](https://user-images.githubusercontent.com/32711146/85861064-6a1f4d80-b7c8-11ea-81c4-ff7e3a211646.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by ameenbadri7** [comment]
@sadeq90  welcome back.

 could you use [this ](https://medium.com/@inspireui/setup-google-login-for-flutter-apps-fedc58a490b8) and [this ](https://github.com/inspireui/support/issues/3151)

and please let us know if you still having problems with setuping the login with your app.

**Comment by sadeq90** [comment]
@ameenbadri7 Thank you,

for the first issue, solved by updating to throw new FileNotFoundException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")

for firebase, I followed the structures and I updated I generate Keystore file and added  SHA key to firebase console, still, I get an error.
for me too in the previous versions of fluxstore it was working smoothly, but now I don't know what is the problem.

This is the error
**I/BiChannelGoogleApi( 5788): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@b0ae89d**

**Comment by ameenbadri7** [comment]
@minhcasi please help us here thank you.

**Comment by minhcasi** [comment]
@sadeq90 - try your best to check the solution on this ticket #3151

**Comment by minhcasi** [comment]
@sadeq90 - let us know your checking, thank you!

**Comment by sadeq90** [comment]
Hi, I tried to follow this video and run the command on this page
https://medium.com/@inspireui/setup-google-login-for-flutter-apps-fedc58a490b8

I got an error that .keystore not found and the video may be outdated.

and I don't have any file with extension .keystore, I have .jks

I ran **keytool -exportcert -list -v -alias key -keystore app/key.jks**
and I got the SHA1 key and I use it in firebase.
Now it works, I receive verification code when I enter the mobile number, but when I enter the verification code it keeps loading for more than 5 minutes without any output.

1- So what should I do in this case? @minhcasi 

2- for key file, is it safe to have with password 123456, and I have two keys, one in android/app folder (key.jks) and the other in certs folder

please take a look in the screenshot @minhcasi 

![Annotation 2020-07-02 175347](https://user-images.githubusercontent.com/32711146/86374242-05af3300-bc8d-11ea-9dca-94ee8184ca78.png)
