### ISSUE TITLE
ISSUES WITH FluxStore Listing

### ISSUE THREAD

**Issue by macbethm** [inspireui/support#3923]
Hi 

I have bellow issues

1. Search function does not work
2. Featured icon Does appear for paid listing
3. claimed/verified badge does not appear for claimed/verified listings
4. How to show all Events because only individual event has ID, not like categories.

![download page](https://user-images.githubusercontent.com/53470387/85857628-e4e56a00-b7c2-11ea-962f-3bd3b3c8e54c.PNG)

**Comment by macbethm** [comment]
Please find attached Config Files


[Config.zip](https://github.com/inspireui/support/files/4837002/Config.zip)

**Comment by ameenbadri7** [comment]
hello, @macbethm welcome back.

I will let the support teamwork see your problem right now. don't worry

**Comment by macbethm** [comment]
Hello

Any feedback ?

Br
Mac

**Comment by philipvu30** [comment]
Hi,

1. In this file lib/services/index.dart, replace this line with this code: 
 `     ListingApi().searchSearch = 'search/v1/$kProductPath';`
![image](https://user-images.githubusercontent.com/54442328/85984995-38022b80-ba14-11ea-880d-f8aec1b16ed6.png)

2. Not support on Listing Pro theme. You need to modify the config.dart and lib/entities/product.dart files to suit your requirement.
3. Same as above
4. Why not add all of them into a category? Currently, I can't think of a way to implement it though.

**Comment by macbethm** [comment]
Hi Philip

Thanks for the reply, but i think you have a lot to do with this app, its
missing a lot of features for listingpro. Even simple features like these
guys you can't implement. This shows you are not serious with this project.
You even did not know if the search function does work for listingpro.
Please remove listingpro as one the compatible theme and leave only listeo,
because it seems is the one that you care about. I bought this app because
you said its compatible with listingpro but now many features are missing,
even very important ones.

**Comment by philipvu30** [comment]
Hi,

My apologies for any inconvenience we may have caused. 
- For a product like FluxListing, it's hard to manage every single detail for each theme with every update. 
- About your issue 2 and 3, if you are a developer, just simply look into your Rest API response and modify the file I mentioned. It's easy. If not, you can ask for assistance from someone else who is able to help you as we are here only to answer and give instructions. 
- If you feel the product does not meet your needs or expectation, feel free to ask for a refund via this [link](https://help.market.envato.com/hc/en-us/articles/202821460-Can-I-Get-A-Refund-)

Thank you.

**Comment by macbethm** [comment]
Hi Inspireui/Support

I get this error
