### ISSUE TITLE
Bottom overflowed 

### ISSUE THREAD

**Issue by samer-ibrahim** [inspireui/support#3924]
Dear InspireUI Team,

Fluxstore woocommerce 1.7.5 Andriod
Previous tickets (3753,3856)

I have an error in  product view "bottom overflowed by xx pixle", this error appear in many products,
some suggestions to add Scaffold(
 resizeToAvoidBottomPadding: false
and SingleChildScrollView(....

please let me know if this is correct and how can I fixed ?

![1](https://user-images.githubusercontent.com/66953736/85857214-1b6eb500-b7c2-11ea-9f9d-7f2acbbbd1df.jpg)

Thank you

**Comment by ameenbadri7** [comment]
@samer-ibrahim welcome back

thank you for your feedback.

did you follow [image optimization](https://docs.inspireui.com/fluxstore/performance/#2-image-optimization) guiad ?

**Comment by samer-ibrahim** [comment]
> @samer-ibrahim welcome back
> 
> thank you for your feedback.
> 
> did you follow [image optimization](https://docs.inspireui.com/fluxstore/performance/#2-image-optimization) guiad ?

Hi Ameen, Yes I did.  I use Regenerate Thumbnails plugin.

**Comment by ameenbadri7** [comment]
please go to your `lib\common\config\general.dart`
and see  ` "kIsResizeImage": true,` can you conform that its true not false ?
that const will make the images in 3 sizes to fix any overflow issue.

hope this help sir?

**Comment by minhcasi** [comment]
@samer-ibrahim - also try with the latest code on Gitlab - thank you!

**Comment by samer-ibrahim** [comment]
> please go to your `lib\common\config\general.dart`
> and see ` "kIsResizeImage": true,` can you conform that its true not false ?
> that const will make the images in 3 sizes to fix any overflow issue.
> 
> hope this help sir?

yes, it is  "kIsResizeImage": true
The bottom overflowed is common problem can happen regardless of image size,  I think it's due to container size, check this short video
 https://www.youtube.com/watch?v=2E9iZgg5TOY

**Comment by abedfatafta** [comment]
@minhcasi 

same is here , 
some are small some are overflow

**Comment by ameenbadri7** [comment]
@abedfatafta  @samer-ibrahim could you try the new fluxstore builder with the new config_xx.json files
I don't have this issue in the new update with the right configs.

this is my config for both Arabic and English.
[config.zip](https://github.com/inspireui/support/files/4842746/config.zip)

**Comment by abedfatafta** [comment]
> @abedfatafta @samer-ibrahim could you try the new [fluxstore builder](https://github.com/inspireui/fluxbuilder/releases) with the new config_xx.json files
> I don't have this issue in the new update with the right configs.
> 
> this is my config for both Arabic and English.
> [config.zip](https://github.com/inspireui/support/files/4842746/config.zip)
@ameenbadri7  @samer-ibrahim 
actually i fix it with a ddifferent way , 
i went to tools.dart and changed from small to 300x300 in naming 
            imageURL = '$pathWithoutExt-300x300$ext';

every thing went fine

**Comment by samer-ibrahim** [comment]
I will try to change some products picture manually ,then I will test again & give you a feedback.

**Comment by ameenbadri7** [comment]
On our demo we use a one size pictures so its perfectly working. 
Yes if you do that you can fix the issue.

If you problem finish please share your experience with us and also close this ticket. 

Thank you @samer-ibrahim for your time.

**Comment by samer-ibrahim** [comment]
I adjusted the pictures manually and no errors in my app.
Thanks for everyone.
