### ISSUE TITLE
FluxNews Remove the registration using the phone number

### ISSUE THREAD

**Issue by haidarsalim** [inspireui/support#3928]
FluxNews Version: 1.4.1
Flutter : v1.17.1
Testing Device/Simulator

I had a problem changing the country here
https://github.com/inspireui/support/issues/3899
After thinking, I decided to remove the registration step by phone number
Please send me a modified file by removing the login by phone number
login.dart
On iPhone and Android
![3123214](https://user-images.githubusercontent.com/54249914/85866162-a86c3b00-b7cf-11ea-8b82-6544f11137e2.PNG)

**Comment by dttrung26** [comment]
Hi @haidarsalim ,
if you haven't modified your login.dart before, replacing the attached login.dart file into your /lib/screens/ would adapt your customization. 
[issue#3928.zip](https://github.com/inspireui/support/files/4837457/issue.3928.zip)
Best!

**Comment by haidarsalim** [comment]
Thanks for the quick reply
