### ISSUE TITLE
hello, can you send a docs link for the last update because I can't use the dynamic config to change products in the app when I change the language?

### ISSUE THREAD

**Issue by ahmedemad2345** [inspireui/support#3929]
hello, can you send a docs link for the last update because I can't use the dynamic config to change products in the app when I change the language?
I have the main domain with some products and also subdomain has different products  so I want to make the app change the API when I change the language to display the products based on the selected language

_Originally posted by @ahmedemad2345 in https://github.com/inspireui/support/issues/3645#issuecomment-648227641_

**Comment by ameenbadri7** [comment]
@ahmedemad2345 Welcome back.

you can use the [documentation ](https://docs.inspireui.com/fluxstore/config/) for knowing about the config files.

but if you want to show Arabic and English language and it should switch between both of them your 
you could use this [guide ](https://docs.inspireui.com/fluxstore/multi-language/)
you should use WPML to create two separate categories for the same products and also translate your products with all the attributes and other stuff.

those are my website Arabic and English config.json you could use to know more about it.

[config.zip](https://github.com/inspireui/support/files/4838538/config.zip)

if you want anything please tell us, Ahmed.
thank you for your patients.

**Comment by ahmedemad2345** [comment]
hello Ameen thank you so much but this for flux store and I'm working with store pro  react-native not flutter 
for the wpml i don't prefer to work with it because it causes bad performance so I am using two subdomains one for English and the other for Arabic each subdomain has different products than other

**Comment by ameenbadri7** [comment]
Sorry @ahmedemad2345  for misunderstanding, you did not use our issue template.

This issue will be transferred to a higher developer until your problem is resolved soon.

**Comment by luyx2412** [comment]
Hi @ameenbadri7 Please describe your issue clearly or specific screenshot.

Thanks

**Comment by ahmedemad2345** [comment]
Hello I'm sorry for issue template 
1. I want a docs to work with dynamic config in mstore pro 
2. If it possible please help me with any documentation for this , i have 2 sites with wp multi site the first site in the main domain like maindomain.com and the second site in subdomain like sub.maindomain.com and each site has a different products and language the first site is English and the second site is Arabic so i want to make one app by mstore pro but with new feature 
When the user change language in the app all the products change based on the selected language if English get English products from the main domain also if the selected language is Arabic in the app all the product changes to English products from the second site in subdomain 

I think the app will have two different api in the config file

**Comment by luyx2412** [comment]
Hi @ahmedemad2345 We are updating the document, you can upload AppConfig.json to your server and replace it in Config.js file follow the screenshot.
![image](https://user-images.githubusercontent.com/8909619/85944072-74735000-b95e-11ea-92d4-cb078cb119cd.png)
![image](https://user-images.githubusercontent.com/8909619/85944060-4c83ec80-b95e-11ea-907e-359e98fce76e.png)
And make sure `enable: true`.

- Current we did not support this features, you can do it yourself. Move all config to the redux, and add event when change language to load another website link again.

Thanks

**Comment by ahmedemad2345** [comment]
hello, can you explain more about this "Current we did not support this features, you can do it yourself. Move all config to the redux, and add event when change language to load another website link again." or any docs to make it or make it for me with extra fees

**Comment by luyx2412** [comment]
Hi @ahmedemad2345  You can contact with @minhcasi about it.

Thanks

**Comment by ahmedemad2345** [comment]
I'm witing

**Comment by minhcasi** [comment]
@ahmedemad2345 - We sincerely apologize for the delay on this ticket.

We currently have reduced staff and a significantly higher volume of inquiries. We’re working as hard as we can, but could not support more customization or installing the job at the moment. Please help us to find another team to support this custom job - thank you!
