### ISSUE TITLE
[MStore] Only 15 categories is display on Category tab.

### ISSUE THREAD

**Issue by mkashifrazzaq11** [inspireui/support#393]
**Required Info (please complete the following information):**
 - Product: [e.g. MStore, ListApp] MStore
 - Your Purchased Code: [get from https://codecanyon.net/downloads]
f8d919b7-3308-4d8c-a454-6b2685fbae9c
(we may not reply if you are not our customer)

**Describe the bug**
We have 20+ categories on my website but my app is showing only 9 categories. I have changed PagingLimit in common/Constants.js but nothing happened. Please solve this.

**Screenshots**

**Additional context**
Add any other detail logs about the problem here.
If possible please share your config.js that use for the app setting

**Comment by luyx2412** [comment]
HI @mkashifrazzaq11 Can you provide your AppConfig.json?

Thanks

**Comment by mkashifrazzaq11** [comment]
Okay.  Sure
[AppConfig.zip](https://github.com/inspireui/support/files/2959546/AppConfig.zip)

**Comment by luyx2412** [comment]
HI @mkashifrazzaq11 I just checked your config file which worked normal. Because Categories screen only show main category, you can see sub category in left menu and expand parent category. 
![image](https://user-images.githubusercontent.com/8909619/54327919-8aacae00-463e-11e9-8742-e38a477785cb.png)

Thanks

**Comment by mkashifrazzaq11** [comment]
Sorry, it's not working normal. I have 20+ main categories on my site. but app shows only 9 main categories. If you check woocommerce api from site, you will get 20+ main categories from it.

**Comment by luyx2412** [comment]
Hi @mkashifrazzaq11 Can you send me the example main category which did not show in the app?

Thanks

**Comment by mkashifrazzaq11** [comment]
These are categories that are not showing in the app...

Spices / Dry Fruits
Instant Foods
Soaps / Gel
Dental Care
Hair Care
Banaspati / Oil
Pulses / Rice / Flour
Bakery / Dairy
Drinks / Snacks
Ketchup / Sauce / Pickle
Tea / Coffee
Insect Killer / Air Fresheners
Electronics

**Comment by luyx2412** [comment]
Hi @mkashifrazzaq11 
- I just checked again your config, and i just see 4 main categories. Please make sure your config right.
- You can use the debug tools to check your api https://docs.mstore.io/api-and-project-structure#debug-app-with-reacttotron.

https://www.screencast.com/t/cWiiwgaH

Thanks
