### ISSUE TITLE
how to only show parent category in category page in column layout

### ISSUE THREAD

**Issue by rihtak2020** [inspireui/support#3930]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 

how to only show parent category in category page in column layout.

currently it show parent and child categories

+ Product & version:1.7.5
+ Flutter (or React Native) version:  flutter
+ Testing Device/Simulator: android
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

Have submitted proof 

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by ameenbadri7** [comment]
Thank you for the feedback.
you have three issues with us on the InspireUi support but you haven't confirmed that you buy the app from us.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
Verified ✅

**Comment by rihtak2020** [comment]
That's strange, for all the 3 issues I have filled the Google form to verify.

**Comment by ameenbadri7** [comment]
@minhcasi  could you help us here. thank you

**Comment by ameenbadri7** [comment]
from my experience, you can modify the category page from config_xx.json file to show four themes 

`(card, sideMenu, column, subCategories, animation, grid)
`
this [link ](https://docs.inspireui.com/fluxstore/home-layout/#4-category-layout)will guid you to customize it.

![1_qdqoFNrCQmDFfKsZr1IWRg](https://user-images.githubusercontent.com/37524186/85923511-31e54100-b894-11ea-80a4-e4136c3740ce.png)

in the six themes, you would show the full category you have. 

you can also try to customize it manually by editing with the inspector.
