### ISSUE TITLE
Some issues in MStore React Native Version

### ISSUE THREAD

**Issue by alhasson** [inspireui/support#3934]
Hello,
As i verified the purchase in this issue: 
https://github.com/inspireui/support/issues/3762
Also a copy sent to your email: inspireui.teaxxx

I have some issues: 
1. on the iphone shows an error once the splash screen done:
![iphone](https://user-images.githubusercontent.com/18103270/85891425-bafa6a80-b7f7-11ea-880f-871b28f570d6.jpg)

on Android emulator
2. When change language to Arabic it the categories, products and all other things don't show the translate  : 
![Screenshot_1593193061](https://user-images.githubusercontent.com/18103270/85891456-cc437700-b7f7-11ea-8067-430d53cfa812.png)
 
3. When checking out it shows an error that must select a country although i selected it: 
![Screenshot_1593197443](https://user-images.githubusercontent.com/18103270/85891623-19bfe400-b7f8-11ea-957f-4afd55b627f2.png)

4. Wishlist shows an error:
![Screenshot_1593198140](https://user-images.githubusercontent.com/18103270/85891990-ce5a0580-b7f8-11ea-82db-25f1d6a0a2df.png)

General inquiries: 
1. Is the currency switcher available? and how can i config it? 
2. How can i select a specific countries that shown in the checkout fields? 
3. Can i use custom fields in checkout screen? 
4. Is the vendor page shows the products that available on this vendor store or it shows only general information? 
![Screenshot_1593198358](https://user-images.githubusercontent.com/18103270/85892237-39a3d780-b7f9-11ea-9fe4-b8f9f6682aca.png)

thanks.

**Comment by luyx2412** [comment]
HI @alhasson Please send the project via inspireui.team@gmail.com. Let me investigate and re-send you soon.

Thans

**Comment by alhasson** [comment]
@luyx2412 project already sent to your email with the subject of "Some issues in MStore React Native Version #3934
"

**Comment by alhasson** [comment]
@luyx2412 this issue is still open!! any update?

**Comment by luyx2412** [comment]
Hi @alhasson Please access my request. 

Thanks

**Comment by alhasson** [comment]
@luyx2412 i did please try now.

**Comment by alhasson** [comment]
@luyx2412 i still waiting for you!

**Comment by luyx2412** [comment]
Hi @alhasson Sorry about reply you late. I just sent your project via your email.

Thanks
