### ISSUE TITLE
Deep Link to Vendor Profile

### ISSUE THREAD

**Issue by gonzalovvt** [inspireui/support#3935]
Hi, 

Ok right now for me it's like impossible to know how can i make a deep link for a Vendor Profile in the app, i was looking to do a Web Page externally and accesing it from the WebView in the app, and when they touch one botton in that page open the profile in the flutter app... 

Please help!!

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by gonzalovvt** [comment]
> Thank you for the feedback.
> 
> Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.
> 
> We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!
> 
> > **[Google Forms - create and analyze surveys, for free.](http://verify.inspireui.com/)**Create a new survey on your own or with others at the same time. Choose from a variety of survey types and analyze results in Google Forms. Free from Google.

I already send the verify form!

**Comment by ameenbadri7** [comment]
About Us

Open lib/screens/settings.dart file to change the About Us url. (or `lib/screens/settings/settings.dart` for apps from version 1.6.5 onwards).

MaterialPageRoute( builder: (context) => WebView( url: "https://inspireui.com/about", title: "About Us"))


Just write your wordpress about page here. 


You Could use This [guide](https://docs.inspireui.com/fluxstore/customization/). 

Please @gonzalovvt if your issue solved let us know with a comment. 

Thank you for your patients.

**Comment by gonzalovvt** [comment]
Thanks for the reply!!, but actually what I need is a DeepLink or any other way to communicate with the app internally, to open in the same app one vendor profile. I'm using this package ( https://pub.dev/packages/flutter_unity_widget )  and there is an example that is just sending a message from Unity to Flutter to do like a toast... here I want to open in the flutter app the vendor profile like a native way like you opend on the store list.

The other plan is make that the web view that comes with the app reads a javascript and from that open one deep link.

 I have seen that store_screen.dart have functions to display "x" store from the store list, but I dont know where to go from there

**Comment by ameenbadri7** [comment]
The feature you've just requested sounds great, I have to say that.
However, this belongs to the customization service. If you really in need of that feature, please contact our tech lead via minh@inspireui.com and declare your request.

**Comment by gonzalovvt** [comment]
Hi, I'm reopening the ticket cause I found the way to link this, but I need a little guide about how to make a search of a specific vendor?..

Like to display a vendor when you put just the name, thanks.
