### ISSUE TITLE
cashing file in mstore api plugin

### ISSUE THREAD

**Issue by alolahussein** [inspireui/support#3937]
when I update mstore API plugin to version 2.6.5
when uploading config-ar.json cant change in-app and show old folder and when disabling Iscashing in config.dart change show in-app (fluxstore )

**Comment by ameenbadri7** [comment]
hello @alolahussein welcome back 

please, sir, could you clean the cache of your wp-cache plugin 
you can read about it in [here](https://docs.inspireui.com/fluxstore/performance/).

please let us know if you fix this issue so we can close it or if it's not fixed we will find other solutions.

**Comment by alolahussein** [comment]
hi @ameenbadri7 
it's working thanks

**Comment by ameenbadri7** [comment]
If you love one of our apps or you are satisfied with our support. 
You can surprise us by leaving a 5-star rating on CodeCanyon.
Here’s how you do it:

Log in to your Envato account at codecanyon.net

Go to your downloads page at: codecanyon.net/downloads

Click on “Rate this item”:

Follow the popup, you can give a comment if you wish.

You’re done, thank you so much!

From InspireUiTeam with ♥
