### ISSUE TITLE
Inserting App Keys in Build

### ISSUE THREAD

**Issue by gmldigital2019** [inspireui/support#3938]
We are having some issues swapping our apps keys in the new application for publication, we had an old app we are trying to replace with this new build.

**Comment by ameenbadri7** [comment]
Hello, @gmldigital2019 Welcome back. 

You could use this [guide](https://docs.inspireui.com/beonews/delivery/) 

If your issues not solved please let us know with a comment, if you still having problems dont worry  we will help until your problems solved. 

Thank you.

**Comment by luyx2412** [comment]
Closed, because no longer response. Please feel free create new issue.

Thanks
