### ISSUE TITLE
Fluxstore Pro Woocommerce, duplicate Vertical layout problem

### ISSUE THREAD

**Issue by AliRaadAlsaedi** [inspireui/support#3939]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: I have a problem in the home page I have add vertical layout to show the product but when the user open the app for the fist time it’s okay but when he close the app and reopen it the vertical layout duplicate automatically can you please show me where is the problem
+ Product & version:Fluxstore Pro Woocommerce 
+ Flutter (or React Native) version: Flutter
+ Testing Device/Simulator: All Devices same for Simulator
+ Screenshot issues (drag the file to attach here): 
![Screenshot_20200627-020517](https://user-images.githubusercontent.com/67406451/85907973-ff97fd00-b81b-11ea-9a07-f2db25bc3576.jpg)
![Screenshot_20200627-020523](https://user-images.githubusercontent.com/67406451/85907976-032b8400-b81c-11ea-869e-a718eda46547.jpg)

config code
{
  "HorizonLayout":[
    {
      "layout":"logo",
      "showMenu":true,
      "showSearch":false,
      "showLogo":true,
      "background": "#ffffff",
      "image":"http://souqaliraq.com/wp-content/uploads/2020/06/souqlogo-medium.jpg"
    },
    {
      "isSafeArea":true,
      "showSearch":true,
      "rotate":["Women Clothes",
        "Men Clothes",
        "Bags",
        "Foods"],
      "type":"typewriter",
      "height":0.09,
      "padding":19.0,
      "fontSize":15.0,
      "layout":"header_text"
    },
    {
      "layout":"bannerImage",
      "isSlider":true,
      "autoPlay":true,
      "padding":0.0,
      "design":"default",
      "items":[
        {
          "image":"https://i.imgur.com/at5mXzX.jpg",
          "padding":15.0,
          "category":null
        },
        {
          "image":"",
          "padding":15.0,
          "category":null
        },
        {
          "image":"https://i.imgur.com/2qD2RiB.jpg",
          "padding":15.0,
          "category":null
        }
      ],
      "radius":0.0
    }
  ],
  "Setting":{
    "MainColor":"#3FC1BE",
    "ProductListLayout":"list",
    "StickyHeader":true
  },
  "TabBar":[
    {
      "layout":"home",
      "icon":"assets/icons/tabs/icon-home.png",
      "pos":100
    },
    {
      "layout":"category",
      "categoryLayout":"animation",
      "icon":"assets/icons/tabs/icon-category.png",
      "pos":300,
      "images":["briefcase",
        "chrome",
        "download",
        "compass"],
      "categories":["16",
        "17",
        "19",
        "18"],
      "showChat":false
    },
    {
      "layout":"cart",
      "icon":"shopping_bag",
      "data":{
        "id":1,
        "container":{
          "height":0.5,
          "image":{
            "height":0.5,
            "width":1.0,
            "url":"https://images.unsplash.com/photo-1584352587534-5763683125b5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2700&q=80",
            "align":{
              "x":1.0,
              "y":1.0}
          },
          "header":{
            "align":{
              "x":-1.0,
              "y":0.8
            },
            "padding":{
              "horizontal":20.0,
              "vertical":10.0
            },
            "color":"#FFFFFF",
            "background":"#000000",
            "text":"About US"}
        },
        "subHeader":"This is sub heading",
        "description":"This is description"
      },
      "pos":621,
      "showChat":false
    },
    {
      "layout":"page",
      "icon":"phone_call",
      "data":"",
      "pos":705,
      "showChat":false,
      "url":"https://inspireui.com",
      "title":""
    },
    {
      "layout":"profile",
      "icon":"users",
      "data":{
        "id":1,
        "container":{
          "height":0.5,
          "image":{
            "height":0.5,
            "width":1.0,
            "url":"https://images.unsplash.com/photo-1584352587534-5763683125b5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2700&q=80",
            "align":{
              "x":1.0,
              "y":1.0}
          },
          "header":{
            "align":{
              "x":-1.0,
              "y":0.8
            },
            "padding":{
              "horizontal":20.0,
              "vertical":10.0
            },
            "color":"#FFFFFF",
            "background":"#000000",
            "text":"About US"}
        },
        "subHeader":"This is sub heading",
        "description":"This is description"
      },
      "pos":775,
      "showChat":false
    }
  ],
  "Drawer":{
    "logo":"http://souqaliraq.com/wp-content/uploads/2020/06/souqlogo-medium.jpg",
    "items":[
      {
        "type":"home",
        "show":true
      },
      {
        "type":"blog",
        "show":false
      },
      {
        "type":"login",
        "show":true
      },
      {
        "type":"category",
        "show":true
      }
    ]
  },
  "VerticalLayout":{
    "key":"m6iwjpx405",
    "layout":"menu",
    "name":"New Items",
    "category":17}}

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by AliRaadAlsaedi** [comment]
I have make the verify step please check it

**Comment by ameenbadri7** [comment]
we are trying our best to solve this issue 
I will not close this ticket until we solve this issue.
for now, you can use another layout to show recent like 

```
 {
      "name": "New Collcation",
      "layout": "staggered"
    }
```

to get recent products until we get the solution for this issue.

thank you for your patients.

**Comment by ameenbadri7** [comment]
![Screenshot_20200630-024838_Skype_1](https://user-images.githubusercontent.com/37524186/86067018-6fa4be00-ba7c-11ea-9066-f5cd2b32ead6.jpg)

so you try our team temporary fix for the vertical double problem by changings you code as this picture. 

It will work with `vertical layouts` `Pinterest` option only  
Its not working with the other menu, default, etc.. 

![Screenshot_20200630-024808_Skype_1](https://user-images.githubusercontent.com/37524186/86067030-79c6bc80-ba7c-11ea-91c6-61b286c22f39.jpg)

**Comment by AliRaadAlsaedi** [comment]
it's not working for me plus see the below image of the console and the app is keeping repeat the request I don't know way and it's keep duplicate 
![error](https://user-images.githubusercontent.com/67406451/86118219-13bc5280-bad9-11ea-805a-80b57411ec8c.png)
![concel error](https://user-images.githubusercontent.com/67406451/86118225-17e87000-bad9-11ea-9daa-00492aabd2ae.png)

**Comment by ameenbadri7** [comment]
could you send your config_en.json file to here so I can see it?

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one with full information - thank you for your time!
