### ISSUE TITLE
[MStore] Font Load problem fontFamily Baloo

### ISSUE THREAD

**Issue by binaryversion** [inspireui/support#394]
- Product: MStore
 - Your Purchased Code: e6234342-5c83-4f91-9c1c-07c8585ad97a

**Describe the bug**
When APP starts I get console.error: fontFamily Baloo.

This only  @happens in version 3.7.0

**Comment by luyx2412** [comment]
Hi @binaryversion Can you send the screenshot to understand easier?

Thanks

**Comment by binaryversion** [comment]
In attachment you have the screenshots. I just downloaded the version 3.7.0 and run everything accordingly to your installation manual.
![WhatsApp Image 2019-03-13 at 11 24 31](https://user-images.githubusercontent.com/18722452/54275609-faf5f980-4582-11e9-8e96-dd0ccaaf6243.jpeg)
![WhatsApp Image 2019-03-13 at 11 24 31(1)](https://user-images.githubusercontent.com/18722452/54275610-faf5f980-4582-11e9-898e-07079c6fd24f.jpeg)
![WhatsApp Image 2019-03-13 at 11 24 47](https://user-images.githubusercontent.com/18722452/54275611-faf5f980-4582-11e9-8259-3456bf9a5c73.jpeg)

**Comment by luyx2412** [comment]
Hi @binaryversion You need load font before use it. Please read the document to add font https://docs.expo.io/versions/latest/sdk/font/#__next. The function to load font in `App.js` file, and make sure you have font in assets folder.

![image](https://user-images.githubusercontent.com/8909619/54327305-36a0ca00-463c-11e9-9683-b83ab45e799e.png)

Thanks

**Comment by ShrawanBK** [comment]
The font is not loading. I tried loading other font as well, the loadState gets true , but the fontFamily is not changing !!!
Are you sure you tested this with different fonts ??

**Comment by binaryversion** [comment]
Hi, the problem was really wired... I download again all the code and started all over and now it's working perfectly. thanks.
