### ISSUE TITLE
items count and pictures size problems

### ISSUE THREAD

**Issue by effec-tline** [inspireui/support#3940]
-i see problem now if we have item have just 1 pcs from it if i add it to cart and close item page and return on it again can add another 1 pcs from same item so cart will be 2 pcs and etc can add any number from this model on my cart we can fix it?

-and have another issue some pic appear big than another ( we use regenerate thumblnials ) and run it and also pics not same size

Product & version: FluxStore 1.7.5
Flutter (or React Native) version: Flutter 1.17.3-stable
Testing Device/Simulator: android studio last version / simulator nexus 6

Step 2: Please verify license and sharing config files by submitting on this google form, http://verify.inspireui.com, (done )

**Comment by ameenbadri7** [comment]
hello @effec-tline 
please try to attach some screenshots for your issue and give us more details

thank you

**Comment by effec-tline** [comment]
ok  about first problem here

![1](https://user-images.githubusercontent.com/67228253/85914248-f585f680-b83b-11ea-9fe7-9cfd2b3b6609.png)
![2](https://user-images.githubusercontent.com/67228253/85914251-fdde3180-b83b-11ea-8145-e8a9e8048a94.png)


this item have just 1 pcs on store and customer can add unlimited number from this item on his cart and complete the order also without any error 


and about the another problem some pic not same size

![3](https://user-images.githubusercontent.com/67228253/85914292-7644f280-b83c-11ea-957f-f9135cd6809e.png)

**Comment by ameenbadri7** [comment]
1- if you want to make the customer buy your products without the 100 products limit 
you can edit `lib\common\config\products.dart` to increase maxAllowQuantity to 10000 if you like .
 
```
const kCartDetail = {
  "minAllowTotalCartValue": 0,
  "maxAllowQuantity": 100000,
};
```


2- you should correct the size of the pictures before you upload them.
and after that make sure to [Image Optimization ](https://docs.inspireui.com/fluxstore/performance/#2-image-optimization)  by using the Regenerate Thumbnails. 

don't set up your cache now until you fix every problem. 

thank you for your patients.

**Comment by effec-tline** [comment]
thanks first problem fixed

i need to ask where we can change this category pic because i cant ound it on the docs

where we can change pic and how we sort it?
![1](https://user-images.githubusercontent.com/67228253/85951116-6115b400-b961-11ea-8f75-2fc1837d7d1f.png)

**Comment by ameenbadri7** [comment]
it's very easy to change the category picture but from woocommerce 

Do you go to woocommerce > products > categories

https://your_site/wp-admin/edit-tags.php?taxonomy=product_cat&post_type=product

and then you can edit every  `category ` and from inside you will find `Thumbnail`  and you upload you.

thank you for reading [our documentation](https://docs.inspireui.com/fluxstore) and I encourage you to see the [woocommerce documentation](https://docs.woocommerce.com/documentation/plugins/woocommerce/) 

I will close this ticket and you can open a new one if you still have problems
thank you for your time sir

**Comment by effec-tline** [comment]
> 
> 
> 1- if you want to make the customer buy your products without the 100 products limit
> you can edit `lib\common\config\products.dart` to increase maxAllowQuantity to 10000 if you like .
> 
> ```
> const kCartDetail = {
>   "minAllowTotalCartValue": 0,
>   "maxAllowQuantity": 100000,
> };
> ```
>

hey this works good with items not have variables    but with any items have variable like size or color customer can add unlimited number from 1 item

**Comment by effec-tline** [comment]
any reply please?
