### ISSUE TITLE
Undefined class 'PermissionStatus'. Try changing the name to the name of an existing class, or creating a class with the name 'PermissionStatus'.

### ISSUE THREAD

**Issue by adnanmur** [inspireui/support#3948]
Undefined class 'PermissionStatus'.
Try changing the name to the name of an existing class, or creating a class with the name 'PermissionStatus'.

I am getting this error after update and i cant start debugging because of it all. The app is fluxstore listing. latest update. Before the update i had no errors.

**Comment by ameenbadri7** [comment]
hello, @adnanmur  Wellcome back. 
we will look for this issue as soon as possible. 

thank you.

**Comment by philipvu30** [comment]
Hi,

Please navigate to pubspec.lock and find "location". Then change it from 2.3.5 -> 2.5.4 and run the pub get in pubspec.yaml file

Thank you.
![image](https://user-images.githubusercontent.com/54442328/85985938-a693b900-ba15-11ea-8d2e-48651830b240.png)

**Comment by philipvu30** [comment]
Closed as no response in 2 days. 

If you are happy with our services/support, would you mind rating us on your [download page](https://codecanyon.net/downloads)?
We truly appreciate your help.
