### ISSUE TITLE
Products not showing, for home page icons, menu collections & categories.

### ISSUE THREAD

**Issue by justinekatebe69** [inspireui/support#3949]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues:  When I click on the icons, categories and menu collections, my products aren't loading! But if I add a featured collection on the home page of the app and click the "see all" button, it's loading products.
+ Product & version: 1.7.5
+ Flutter (or React Native) version: 1.7.5
+ Testing Device/Simulator: Both
+ Screenshot issues (drag the file to attach here): 

![85722379-8650bb00-b6f2-11ea-87d4-e64f57ee0f7d](https://user-images.githubusercontent.com/67024464/85926282-b9d04880-b89e-11ea-9633-fff715464b02.jpg)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

please try to config your config_en.json files to point toward the categories ids from your woocommerce website.

you could try [this ](https://docs.inspireui.com/fluxstore/woocommerce-setup/#step-3-setup-fluxstore)

and also this is my config_en.json files you could use them as a guide.

[config.zip](https://github.com/inspireui/support/files/4840993/config.zip)
.
I deleted your license number from your ticket please don't upload any sensitive Infos like the woo commerce keys or your license keys. 
and remember to give us a line to our email minhcasi@gmail.com and inspireui-team@inspireui.com for any verification in the future.

**Comment by justinekatebe69** [comment]
The source code I have is for Shopify, not woocommerce. Will this fix still
work???

**Comment by justinekatebe69** [comment]
Hey the fix I was given still hasn't fixed the problem. Products are still disappearing.

**Comment by justinekatebe69** [comment]
They appear once and when I try to open the collection a second time, they are not appearing.
But one thing that's not making sense is that, when I click the "see all" button on the home page of featured collections, the products are loading.

**Comment by justinekatebe69** [comment]
And just a piece of advice, instead of giving US suggestions on how WE the customers can fix the problems were facing, how about you first try out the suggestions youre giving out to see for yourself if the suggestions youre giving will fix the issue, so that WE the customers wont have keep coming back here to give you updates on whether the issue has been fixed or not by the suggestions youve given. This will save both of us time because. Just food for thought...

**Comment by minhcasi** [comment]
@justinekatebe69 - sorry for the confusion, we will investigate the integration on your site and will give some update - thank you for your time

**Comment by luyx2412** [comment]
HI @justinekatebe69 Can you share me your config file same the screenshot via inspireui.team@gmail.com.
![image](https://user-images.githubusercontent.com/8909619/86135478-10df5300-bb15-11ea-81bd-a63acdd61a48.png)

Thanks

**Comment by justinekatebe69** [comment]
The source code is on my github

Config file link https://github.com/Zeehshan/makumbi/blob/master/lib/common/config.dart

config_en file link: https://github.com/Zeehshan/makumbi/blob/master/lib/config/config_en.json

**Comment by justinekatebe69** [comment]
The source code is on my github

Config file link
https://github.com/Zeehshan/makumbi/blob/master/lib/common/config.dart

config_en file link:
https://github.com/Zeehshan/makumbi/blob/master/lib/config/config_en.json

**Comment by luyx2412** [comment]
HI @justinekatebe69 Please do not share your project public which will effect the license. 

Thanks

**Comment by justinekatebe69** [comment]
I understand. I'm deleting the links now, I hope you've managed to access the config files though.

**Comment by justinekatebe69** [comment]
Oh alright, you've already deleted the comments. Have you managed to access the files or do you still need me to send them to you?

**Comment by luyx2412** [comment]
HI @justinekatebe69 Please remove it and send your file via inspireui.team@gmail.com. 

Thanks

**Comment by justinekatebe69** [comment]
I have sent the config files to inspireui.team@gmail.com. I'm also removing the code as we speak, my wifi is kinda slow here.

**Comment by luyx2412** [comment]
Hi @justinekatebe69 Sorry but i still see your repo, so please make it private. Thanks

**Comment by justinekatebe69** [comment]
I’ve made it private.
Any luck with the “no products” issue?

**Comment by luyx2412** [comment]
Hi @justinekatebe69 Please clean your project and uninstall the app, after that reinstall again. I just checked your config and everything worked great. 
![image](https://user-images.githubusercontent.com/8909619/86371982-cb08c300-bcab-11ea-9ce8-c5447484fe18.png)

Thanks

**Comment by justinekatebe69** [comment]
It’s still doing the same thing.

Do this, click on the alcohol icon on the home page, then go back to the home page and click on the icon again. You will notice that it will now say “no products”.

**Comment by justinekatebe69** [comment]
It’s doing the same thing not only with the icons, but with the menu collections as well. If you click on the same collection link 2 times in as roll, the second time it’ll say “no products”.

**Comment by luyx2412** [comment]
Hi @justinekatebe69 In `lib/models/product/product_model.dart` line 124. Please add this code before this line to fix the issue.
```
      // reset cursor and hasNextPage when same category
      if (this.categoryId == categoryId) {
        cursor = "";
        hasNextPage = false;
      }
```
![image](https://user-images.githubusercontent.com/8909619/86384421-e5956900-bcb8-11ea-9cd7-defd8ae50c53.png)

Thanks

**Comment by lucianacouto** [comment]
> Hi @justinekatebe69 In `lib/models/product/product_model.dart` line 124. Please add this code before this line to fix the issue.
> 
> ```
>       // reset cursor and hasNextPage when same category
>       if (this.categoryId == categoryId) {
>         cursor = "";
>         hasNextPage = false;
>       }
> ```
> 
> ![image](https://user-images.githubusercontent.com/8909619/86384421-e5956900-bcb8-11ea-9cd7-defd8ae50c53.png)
> 
> Thanks

Hi, I'm also trying to resolve the same issue (I was ignored on the issue #3927, BTW), but after adding this code, it is still broken. I'm using the fluxstore-shopify 1.7.5.

The issue is that `productModel` is `null` inside `fetchProductsByCategory` on `shoppify.dart`.

**Comment by luyx2412** [comment]
HI @lucianacouto Please create new your issue, will track and support you to fix the issue.

Thanks

**Comment by lucianacouto** [comment]
The issue is here #3927. You just have to reopen it.

**Comment by justinekatebe69** [comment]
Hey @luyx2412 the problem still isnt fixed. Can you just send me a copy of your code that doesnt have this problem?

**Comment by luyx2412** [comment]
Hi @justinekatebe69 Please send me your code via inspireui.team@gmail.com. Let me investigate and re-send you soon.
Hi @lucianacouto I just reopen your issue. 

Thanks

**Comment by justinekatebe69** [comment]
I have sent inspireui.team@gmail.com a collaboration invitation. Please accept it so that you can view all my code.

**Comment by justinekatebe69** [comment]
@luyx2412 My email address is justinkaunda@gmail.com

**Comment by luyx2412** [comment]
Hi @justinekatebe69 I just sent you the video via gmail. So please see it, i worked great with your config. So can you clean project and reinstall app again.

Thanks

**Comment by justinekatebe69** [comment]
hey @luyx2412 ive cleaned the project and reinstalled the app.

just send me a copy of your code that work.

**Comment by luyx2412** [comment]
Hi @justinekatebe69 I invited you to the gitlab repo which is latest. We did not you github to contain the source code. Are you pull latest code from gitlab and merge your current source code?

Thanks

**Comment by justinekatebe69** [comment]
I dont have access to it. Please share it again to justinkaunda@gmail.com

**Comment by justinekatebe69** [comment]
thanks let me try the code on gitlab

**Comment by minhcasi** [comment]
Let us know if you have any issue - thank you!
