### ISSUE TITLE
[MStore] Mstore Cebuilder Rest Api 

### ISSUE THREAD

**Issue by osamasparky** [inspireui/support#395]
MVStore
Purchase code: da4e5510-501d-456f-9d1d-fbbcdd24f102
(we may not reply if you are not our customer)

I got error on cebuilder 
![resit Api error](https://user-images.githubusercontent.com/36470035/54261363-a6e81680-457c-11e9-877b-3bb6f36537fc.jpg)

**Comment by minhcasi** [comment]
@osamasparky - could you add http into the Website at Setup screen, looks like it is missing - thanks

**Comment by osamasparky** [comment]
![resit api](https://user-images.githubusercontent.com/36470035/54334148-1c63ed80-4636-11e9-846e-974229496e9a.jpg)
I do that sir but the same problem - if you need to accsess my site please till me a way to send you the data

**Comment by osamasparky** [comment]
just need to ask - consumer key and consumer secret - do i need them any where on my website .

**Comment by hakihosting** [comment]
i have the same problem

**Comment by osamasparky** [comment]
Dear sir 
I purchased this app one month now i can’t even start it . From the problem the softwate have please need to start my setup my business

**Comment by minhcasi** [comment]
Hi, could you share your consumer key here, if it's possible please share the testing admin login to our email for further checking: support@inspireui.com - thank you!

**Comment by osamasparky** [comment]
Done i send you an email with all data

**Comment by hakihosting** [comment]
some news ?

**Comment by minhcasi** [comment]
@osamasparky sent you email update

The reason is your missing consumse key - https://gyazo.com/84fae759e652c582e8acca722381c94d

We have created a new one and also add the video guide, all working find now - pls use the key that we share from the email 

Thanks

**Comment by osamasparky** [comment]
Thanks a lot for your help - working now

**Comment by hakihosting** [comment]
i have the same problem but my api is done

**Comment by minhcasi** [comment]
@osamasparky - you are welcome

@hakihosting - please share the testing login or your consume keys so that we could have a check

**Comment by hakihosting** [comment]
i send you email
