### ISSUE TITLE
Error with the app bundle release

### ISSUE THREAD

**Issue by chocotacos** [inspireui/support#3950]
Previous Verified Ticket #2996 

When i use the default key app bundle builds successful but after building new key it shows error

Followed this doc https://docs.inspireui.com/fluxstore/delivery-android/ to build but it shows this error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:packageRelease'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > com.android.ide.common.signing.KeytoolException: Failed to read key key from store "c:\Users\myusername\key.jks": Keystore was tampered with, or password was incorrect

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6m 26s
Running Gradle task 'assembleRelease'...
Running Gradle task 'assembleRelease'... Done                     387.4s (!)
Gradle task assembleRelease failed with exit code 1

**Comment by ameenbadri7** [comment]
[could you check](https://github.com/inspireui/support/issues/3761) if you have the same problem?
try to use the solutions inside this [](https://github.com/inspireui/support/issues/3151).
 and you could use [this ](https://medium.com/@inspireui/setup-google-login-for-flutter-apps-fedc58a490b8) 
also 
right-click on `android `folder inside your project and from the `terminal `you could write: `gradle signingReport`
please consider using [this ](https://gist.github.com/henriquemenezes/70feb8fff20a19a65346e48786bedb8f).
and please let us know if you still having problems with setuping the login with your app.

**Comment by ameenbadri7** [comment]
I'm sorry to close this ticket as there is no response or active conversation, 
please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
