### ISSUE TITLE
Vertical Layout Again

### ISSUE THREAD

**Issue by bigbossmaher** [inspireui/support#3954]
hello , 
i'm using a single Verticale Layout in my app 1.7.5
`  "VerticalLayout":{
    "key":"84vy1djzd0",
    "category" : 215,
    "layout":"column",
    "name":"New Collection"},`
it is loading only with Iscaching False , when it is true , only the Heading is showed 

also is there any fast solution to make it cached , because the verticalLayout make the app loading too slow and buggy

**Comment by minhcasi** [comment]
@bigbossmaher - pls raise this issue to your previous open ticket #3936 - thanks
