### ISSUE TITLE
the order of the application I get 2 orders having several in WordPress

### ISSUE THREAD

**Issue by henry2327** [inspireui/support#3955]
![Screenshot_20200627-204224](https://user-images.githubusercontent.com/36794944/85934883-76360880-b8b7-11ea-96ac-97cef43609d1.png)
![Uploading 20200627_204307.jpg…]()

**Comment by henry2327** [comment]
![20200627_204307](https://user-images.githubusercontent.com/36794944/85934955-68cd4e00-b8b8-11ea-8880-b7f53582dedd.jpg)

**Comment by minhtruong315** [comment]
Hi @henry2327 This error always happen when you place an order?
Can u send me admin info and common folder via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/3955
