### ISSUE TITLE
![image](https://user-images.githubusercontent.com/63785688/85911920-223f0b80-b846-11ea-9088-de4f8f530a2f.png)

### ISSUE THREAD

**Issue by ekramul-1** [inspireui/support#3956]
![image](https://user-images.githubusercontent.com/63785688/85911920-223f0b80-b846-11ea-9088-de4f8f530a2f.png)
@minhcasi Could you please check this error in new update.

_Originally posted by @ekramul-1 in https://github.com/inspireui/support/issues/3543#issuecomment-650471709_

**Comment by minhcasi** [comment]
Please help to check the config file if you have missed this constaint

<img width="959" alt="Screen Shot 2020-06-28 at 10 01 15" src="https://user-images.githubusercontent.com/1459805/85936567-4eca5480-b926-11ea-86f6-2d268b2ae873.png">

**Comment by ekramul-1** [comment]
have a look into the error @minhcasi 

![image](https://user-images.githubusercontent.com/63785688/85938573-1f1e4b00-b92c-11ea-8e42-4f76c1fbaa58.png)

**Comment by ekramul-1** [comment]
> have a look into the error @minhcasi
> 
> ![image](https://user-images.githubusercontent.com/63785688/85938573-1f1e4b00-b92c-11ea-8e42-4f76c1fbaa58.png)

total 280 problem showing in new update

**Comment by ekramul-1** [comment]
export 'config/advertise.dart';
export 'config/general.dart';
export 'config/onboarding.dart';
export 'config/payments.dart';
export 'config/products.dart';
export 'config/smartchat.dart';

/// Server config demo for WooCommerce
const serverConfig = {
  "type": "wcfm", // type: dokan or wcfm
  "url": "http://bbmall.in",

  /// document: https://docs.inspireui.com/fluxstore/woocommerce-setup/
  "consumerKey": "ck_a4f757640bc517742e2139efe66fdc8336bde609",
  "consumerSecret": "cs_3f9f435aa23ca9dfbabdbfafdfde8b895b50503f",

  /// Your website woocommerce. You can remove this line if it same url
  "blog": "http://bbmall.in/blog",

  /// set blank to use as native screen
  "forgetPassword": "http://bbmall.in/wp-login.php?action=lostpassword"
};

**Comment by ekramul-1** [comment]
@minhcasi 
Please have a look into this as this really urgent, & I didn't take any backup & started updated.

**Comment by minhcasi** [comment]
pls try to add my email address to your gitlab repo minhcasi@gmail.com

**Comment by ekramul-1** [comment]
Please check, getting lots of issues in latest updates.
@minhcasi 
minhcasi@gmail.com

**Comment by ekramul-1** [comment]
![image](https://user-images.githubusercontent.com/63785688/85970180-3ff7a680-b9e7-11ea-91fc-4ebce7978cbe.png)
As you can see total 280 issues showing & why you are giving updates with out testing,last 20 days I customised my app & then suddenly came update, I lost everything. By my mistake, i didn't take any backup.

### **please send me the newer verson as I saw some of other issues & that's confirmed that will send. Please fix & it's all the issues in export moudle.**

My Email :- 
ekramul.2@gmail.com


Please help me as my app is down & unable to do any single thing, please give this as pirority @minhcasi .
Without doubt support is reduclass & unexpected.
I am thing to purchase another news app but after receving this types of support I am thing not suggest or purchase. Please don't brake our trust. Our expection is really high. I don't want any refund, just need little bit of your help & quick response. Please try to understand @minhcasi

**Comment by ekramul-1** [comment]
> pls try to add my email address to your gitlab repo [minhcasi@gmail.com](mailto:minhcasi@gmail.com)

How I can add ?

**Comment by minhcasi** [comment]
@ekramul-1 - did you try to clean CACHE? - pls follow https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

We always test the build before release new version, you could also try the gitlab repo - thanks

**Comment by ekramul-1** [comment]
Yes sir @minhcasi

**Comment by minhcasi** [comment]
try to test the fresh download and compare if you have updated any missing config. 

there is this blog that you may miss to read - https://medium.com/@inspireui/how-to-upgrade-fluxstore-projects-by-using-git-cebde7489ea6

**Comment by ekramul-1** [comment]
Okay sir @minhcasi

**Comment by ekramul-1** [comment]
![image](https://user-images.githubusercontent.com/63785688/85971568-18a2d880-b9eb-11ea-85e2-c85bb37c7853.png)

### 
@minhcasi could you please let me know that the actual reason of this error. app emulating but problem is showing

**Comment by ekramul-1** [comment]
> try to test the fresh download and compare if you have updated any missing config.
> 
> there is this blog that you may miss to read - https://medium.com/@inspireui/how-to-upgrade-fluxstore-projects-by-using-git-cebde7489ea6
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/569b2ff5ba844ccda67aa6609230e26bbd204f20/68747470733a2f2f6d69726f2e6d656469756d2e636f6d2f6d61782f313230302f302a5a6c56687841494b536a4f547250774a"><img alt="" height="14" src="https://camo.githubusercontent.com/a1c598ee8610a8cdb0e8bdbf112f3f1c77af25cb/68747470733a2f2f63646e2d7374617469632d312e6d656469756d2e636f6d2f5f2f66702f69636f6e732f66617669636f6e2d72656272616e642d6d656469756d2e33593678705a2d3046536457446e504d3368534249412e69636f"> Medium**[How to upgrade Fluxstore projects by using Git](https://medium.com/@inspireui/how-to-upgrade-fluxstore-projects-by-using-git-cebde7489ea6)**In this guide, we will clarify how to use the Git repo to manage your own source code and easily update the source when there is a new…

**Comment by ekramul-1** [comment]
![image](https://user-images.githubusercontent.com/63785688/85975029-a0d9ab80-b9f4-11ea-9362-dd1a5bbff819.png)

**### Please help me to fix the reason of app not installing after packages from "com.inspireui.fluxstore.vendor" to "in.bbmall" changed**

**Comment by ekramul-1** [comment]
> ![image](https://user-images.githubusercontent.com/63785688/85975029-a0d9ab80-b9f4-11ea-9362-dd1a5bbff819.png)
> 
> **### Please help me to fix the reason of app not installing after packages from "com.inspireui.fluxstore.vendor" to "in.bbmall" changed**

Followed the actual process as mentioned in https://docs.inspireui.com/fluxstore/multi-vendor/

**Comment by ekramul-1** [comment]
> ![image](https://user-images.githubusercontent.com/63785688/85975029-a0d9ab80-b9f4-11ea-9362-dd1a5bbff819.png)
> 
> **### Please help me to fix the reason of app not installing after packages from "com.inspireui.fluxstore.vendor" to "in.bbmall" changed**

@minhcasi 
### Please have a look

**Comment by minhcasi** [comment]
@ekramul-1 - it's working fine with our testing, please try to remove the previous app on simulator and try to install again. 

Sometimes you need to run `flutter clean` to clean up the caching - thank you!

**Comment by ekramul-1** [comment]
> @ekramul-1 - it's working fine with our testing, please try to remove the previous app on simulator and try to install again.
> 
> Sometimes you need to run `flutter clean` to clean up the caching - thank you!

All I tried but unable to found any solution, could you please send me the next version.
