### ISSUE TITLE
[CeNews] React Native drive app installs using Facebook ads

### ISSUE THREAD

**Issue by Ibra-ak95** [inspireui/support#396]
**Required Info (please complete the following information):**
 - Product: [CeNews]
 - Your Purchased Code: [17382b74-a752-4029-bc36-ebc5bdebac3c]
(we may not reply if you are not our customer)

**Describe the bug**
We'd like to drive app installs using Facebook ads. Is there any valid documentation. I checked many tutorials all IOS and Android No react Native. All they add is an event {publishInstallAsync(fbAppId)} and rest is in FB DEV dashboard. I'm working on a react native source code. Appreciate the help in advance.

**Comment by minhcasi** [comment]
Hi, it's kind of advance feature, please check following documents:
https://github.com/Suraj-Tiwari/react-native-ads-facebook

 https://docs.expo.io/versions/latest/sdk/facebook-ads/

Thanks
