### ISSUE TITLE
FluxNews A problem running the project on Xcode

### ISSUE THREAD

**Issue by haidarsalim** [inspireui/support#3961]
I mentioned my problem here
https://github.com/inspireui/support/issues/3959 @ameenbadri7 
With file replacement, I am still facing another problem
![‏لقطة الشاشة ٢٠٢٠-٠٦-٢٨ في ١٢ ٢١ ٣١ م](https://user-images.githubusercontent.com/54249914/85956575-52de8c80-b98f-11ea-93f7-d1298346c4d2.png)
![66](https://user-images.githubusercontent.com/54249914/85956586-70135b00-b98f-11ea-8f7f-fcbf53e8278e.PNG)

**Comment by ameenbadri7** [comment]
امسح هذه الملفات 
- من ملف ios : 
Pods folder, Podfile and fodfile.lock, .symlink folder
- وكمان ملف build folder
مثل هذه الصورة
https://tppr.me/vwqX0

**Comment by haidarsalim** [comment]
@ameenbadri7 
لقد قمت باتباع الخطوات ظهر خطا جديد
![666](https://user-images.githubusercontent.com/54249914/85968254-3e20e980-b9cd-11ea-875a-97c304cf6bcf.png)

**Comment by ameenbadri7** [comment]
ممكن تدخل ملف 
pubspec.yaml
وتعدل السطر اللي فيه 
rate_my_app: 0.6.0+2
إلى 
rate_my_app: 0.6.0+3

**Comment by haidarsalim** [comment]
غيرت الرقم من 
rate_my_app: 0.6.0+3
الى
ate_my_app: ^0.6.1+6
![Screen Shot 2020-06-28 at 11 11 00 PM](https://user-images.githubusercontent.com/54249914/85980481-57a73e80-b997-11ea-8513-a78b05bfc3a5.png)

لان يعمل بشكل صحيح شكرا لك اخ امين

**Comment by ameenbadri7** [comment]
انا في خدمتك اي وقت خذ السكايب تبعي وراسلني برد عليك ان شاء الله على قدر ماقدر 
9867598668da2ddc
او بالايميل تبعي
ameenbadri7@gmail.com

نشوفك بالخير
