### ISSUE TITLE
Help Starting Up

### ISSUE THREAD

**Issue by kyughost** [inspireui/support#3962]
Hello, your documentation is very limited and lacking. I watched the Youtube tutorial and I can't reproduce the same results. After adding the folder source to Android Studio and adding the Flutter and Dart, `Pub get` is not working but I do get this: ```
Running "flutter pub get" in source...                              1.1s
Process finished with exit code 0
```
I decided to run main.dart anyway and I get this:
```
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app_settings:compileDebugAidl'.
> Failed to find Platform SDK with path: platforms;android-R

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 56s
Exception: Gradle task assembleDebug failed with exit code 1
```
+ Product & version: 1.7.5
+ Flutter (or React Native) version: flutter_macos_1.17.3-stable
+ Testing Device/Simulator: Pixel 3a XL API 27
+ Screenshot issues (drag the file to attach here): 
<img width="1680" alt="Screen Shot 2020-06-29 at 00 18 25" src="https://user-images.githubusercontent.com/30949306/85959699-2c741d80-b99e-11ea-9c45-006ccbb48c1d.png">

**Comment by ameenbadri7** [comment]
Hello  @kyughost 
Thank you for the feedback.
 Readings our app documentation is a smart move to learn more about it. 
In our app we assume when you buy our app that you have the very basics of flutter development skills. 

But to worry we will help you out to fix all your problems. 

from the terminal write this: 
`Flutter clean `
`flutter pub get`

You can use this link as a https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

You should read more in the basics flutter development skills.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

Thank you for your time!

**Comment by kyughost** [comment]
Thank you for your reply. I have fix all the issues but the solution you suggested didn't work. Thanks again
