### ISSUE TITLE
Order History slow update?

### ISSUE THREAD

**Issue by macquack** [inspireui/support#3963]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
Order History page was slow update (status,order note) even slide down to refresh or reopen app it still not update. finally i try to re build apk but not work.

i know it's may be because the coding by using json. all i want it just make the pull to refresh get get update ASAP very 

+ Product & version: 1.7.4
Flutter (or React Native) version: 1.7.1
Testing Device/Simulator: Nexus 2
Screenshot issues (drag the file to attach here):
![image](https://user-images.githubusercontent.com/30103694/85971608-d5029b80-b9f7-11ea-9f9e-b1bc29a28d33.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**
submitted

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by macquack** [comment]
it will update when i leave it for a while it's normal?

**Comment by minhcasi** [comment]
@macquack - it could cause by your server-side network or caching from the app, pls try to have a test again if there is any issue - thank you!

**Comment by macquack** [comment]
i think it's to slow it about 20min so it normal that I pulled to refresh but still not update
