### ISSUE TITLE
FluxStore-Pro - opencart - Product with options and filtering-

### ISSUE THREAD

**Issue by midotaha** [inspireui/support#3966]
Hi Dear Sir 
Greetings!! 
i have disaster case , all products i have it with product option had the same problem 

**Step 1**
1- when i customer add first weight it will added correctly ,,,, after that if he remember and go back to the sam product, that is the disaster .... this problem i can't explain it as screenshot , you should see it as [video](https://youtu.be/XSzTvYDFrXI) 
search with Arabic language not working.
3-when i active Credit card method , cash on delivery turned to Credit card method too , the next screenshot from Cash on delivery 

![Screenshot_1593413240](https://user-images.githubusercontent.com/19406537/85981928-a8498680-b9ed-11ea-9a14-ba216f2b8900.png)

4-My Product is :- Fluxstore Pro 1.7.5 my platform Opencart
+Simulator:- Nexus 6 API 30 ----Testing Device many physical devices like:- huawei - samsung
please you can watch the video from here i uploaded it at youtube 
https://youtu.be/XSzTvYDFrXI
second video  https://youtu.be/oXLU0yxCgkE
there is tones of big issues at this source on opencart 
i need very fast solution please to stope the app untile the next update 

**Step 2**
i sent all required at the [verify link ](https://docs.google.com/forms/d/e/1FAIpQLScWOjkAJIWJ9rgb9alopfOqLsJrGKbFM5cCYj1JBfLKLsBblQ/viewform)
Many thanks for you

**Comment by ameenbadri7** [comment]
thank you for your feedback.
don't worry my friend @midotaha our support team will try to fix your problem as soon as possible.
for now, you can try to read our [documentation ](https://docs.inspireui.com/fluxstore/opencart-setup/) maybe you forgot to set up a setting.

**Comment by govindh163** [comment]
I am also having the same problem as the video describes in this issue

**Comment by minhtruong315** [comment]
Hi @midotaha This config only supports for shopify. I doesn't support for opencart. Please disable it.
```
/// Enable Credit card payment
  "EnableCreditCard": false,
```

**Comment by midotaha** [comment]
> Hi @midotaha This config only supports for shopify. I doesn't support for opencart. Please disable it.
> 
> ```
> /// Enable Credit card payment
>   "EnableCreditCard": false,
> ```


**-I know this solution Dear , but i want to enable both of them Credit Card payment and Cash on delivery , if you notice in my both 2 video the payment method turned  into Credit Card method** 
-also add to cart button it Calculates with wrong way when chose any Property for product option , if you checked my video you will get my point 
there is some customers not choosing 'Quantity' and press "add to cart" button , them clicking Twice or three times on "add to cart" .....if he go to check 'Quantity'  on the cart , then close cart he will back to the sam product , if he change his opinion to add more 'Quantity'  or to choose small 'Quantity'  from product option The problem will appear , 
what is the problem , These are the possibilities
         a)The unwanted price will double
         b)The price will turn negative if he choose some of small product option 
         c)The last price and the last weight are always saved in the application memory, to clear it must to close app , Clients cannot agree this very hard, also make me with a problem with customer and loses many of them.
**i already unpublished my app for this reason** 
I want to remind you  i open another ticket this **https://github.com/inspireui/support/issues/3292** ,i asked you to make product option mandatory it will help the customers not skipping any thing , It will reduce customer errors in selection , It was not finished for about two months 
I appreciate your work ٫ And the huge amount of tickets are opened , and you must solved it , but this problems i failed to solved it this problems not in your Documentation , I know it's related with Dart language , but I want a temporary alternative solution
-final search with Arabic words in app not working , i get zero result of searching .
Many thanks for you

**Comment by anwar288** [comment]
Hello
I want to buy this product but these problems are important to me
Because my platform
OpenCart 3.x
I use product options a lot and I want them mandatory

**Comment by midotaha** [comment]
Hi is there any news ?!! my store was disabled for these all this problems ..... i need fast support to fix this issues

**Comment by minhtruong315** [comment]
@midotaha I will check and let you know.
Thanks

**Comment by midotaha** [comment]
HI Dear still waiting the solutions, any updates coming soon for all issues I mentioned it ??!

**Comment by minhtruong315** [comment]
Hi @midotaha Can you give me your skype? I will help you check via remotely.
Thanks

**Comment by midotaha** [comment]
Hi Dear @minhtruong315 My Skype t_b_horse_o_desert

**Comment by minhtruong315** [comment]
Hi @midotaha I messaged you on  the skype. pls check

**Comment by rt-thomas** [comment]
Hi is ter any solution to the issue ?, i too have the same problems

**Comment by midotaha** [comment]
I'm still waiting another update from team to solved this problems and more of it !!!

**Comment by minhcasi** [comment]
@midotaha - please help to comment the remain issues on this ticket #4595 - we have upgraded it as high priority support ticket - thank you for your time!
