### ISSUE TITLE
Problem release app bundle

### ISSUE THREAD

**Issue by emadpost2016** [inspireui/support#3967]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

version 1.7.5 MV
flutter 1.17.3
When I do construction work app build release app bundle
and i uploaded on google play 
The application is logged in to one of the users
Note that I do not want that, but with many attempts to raise the same application gives the same result
This is the link of the application on Google Play to confirm the problem
https://play.google.com/store/apps/details?id=com.mymall.mall

![image](https://user-images.githubusercontent.com/58606378/85985562-2fe1c600-b9eb-11ea-9697-f304741234e0.png)
[https://play.google.com/store/apps/details?id=com.mymall.mall](url)
![Screenshot_20200629-092530](https://user-images.githubusercontent.com/58606378/85985855-a1217900-b9eb-11ea-8f24-4949fc99ad33.jpg)
![Screenshot_20200629-092523](https://user-images.githubusercontent.com/58606378/85985861-a252a600-b9eb-11ea-9d89-f3feb755432d.jpg)
![Screenshot_20200629-092523](https://user-images.githubusercontent.com/58606378/85985880-a979b400-b9eb-11ea-8b4e-4f5860a9f3de.jpg)
![Screenshot_20200629-092530](https://user-images.githubusercontent.com/58606378/85985885-ab437780-b9eb-11ea-80cf-ae8de48562b5.jpg)

![image](https://user-images.githubusercontent.com/58606378/85986056-eba2f580-b9eb-11ea-9e0d-75c6381aab8b.png)

**Comment by minhcasi** [comment]
@emadpost2016 - we could not reproduce this issue on our side from your app stores, could you try to remove the app testing and try to test on the fresh device?

There is some cache feature from the app that allows to store previous user login/setting from the Fluxstore app that may not the issues - thank you!
