### ISSUE TITLE
API does not load data on phone after updating the Mstore-API plugin

### ISSUE THREAD

**Issue by shikhardb** [inspireui/support#3968]
**_Step 1_**

+ Detail Issues: 

When I start the app, it only shows the loading sign, and does not load any data. The web works fine, but mobile doesn't work. It started happening when I updated the Mstore-API plugin. But I again downgraded to the old plugin, but it doesn't work still.

Also, on the settings page of WooCommerce plugin, I see an error saying:

`Notice: register_rest_route was called incorrectly. Namespace must not start or end with a slash. Please see Debugging in WordPress for more information. (This message was added in version 5.4.2.) in /opt/bitnami/apps/wordpress/htdocs/wp-includes/functions.php on line 5167`

+ Product & version: MSTORE Pro - 3.9.8
+ Flutter (or React Native) version: React Native 0.61.5
+ Testing Device/Simulator: OnePlus 5T
+ Screenshot issues (drag the file to attach here): 

![image](https://user-images.githubusercontent.com/4832195/85989888-cffd1680-ba0e-11ea-911c-4ee96ac51146.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

Proof submitted.

**Comment by minhcasi** [comment]
@minhtruong315 - pls check the mstore-api plugin issue - thank you!

**Comment by minhtruong315** [comment]
Hi @shikhardb can u send me admin info via email:  truong@inspireui.com with subject: https://github.com/inspireui/support/issues/3968
I will help you  check
Thanks

**Comment by minhtruong315** [comment]
Hi @shikhardb please check app again. I fixed MStore api plugin.
