### ISSUE TITLE
Categories are not being added to the app from woo commerce - MstorePRO please see #3892

### ISSUE THREAD

**Issue by stagedoor16** [inspireui/support#3969]
Step 1 (require): describe detail issues & screenshots

Detail Issues: I only have 2 product categories on the category screen. From Woocommerce
Product & version: MstorePro - "3.9.8"
Flutter (or React Native)
version: react: 16.9.0 => 16.9.0
react-native: 0.61.5 => 0.61.5
Testing Device/Simulator: Android studio - AVD
Screenshot issues (drag the file to attach here):
image
Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com

Important Note:

We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
Kindly create only One Ticket & includes all the issues, that would help us focus to resolve it better.
If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID
Thank you so much for your time 😊

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

This is the 2nd time i have now raised this issue after being advised how to resolve the fluxstore issue and not the mstorePRO

**Comment by minhcasi** [comment]
pls move to #3892
