### ISSUE TITLE
What is difference between regular and extended licence 

### ISSUE THREAD

**Issue by rajendar123** [inspireui/support#397]
I would like to buy the app from https://codecanyon.net/item/mstore-expo-complete-react-native-template-for-ecommerce/20244164?s_rank=4
link but there two licenses. What is exactly the difference ?

**Comment by Cheewingtan** [comment]
I think the regular license is can be let you modify the code and upload your product on the app and finally you publish to the app store, and the whole process is legal for regular license,  but if you sell the whole source code to other people then you must buy extended license

**Comment by minhcasi** [comment]
@rajendar123 @Cheewingtan  the Extended license can be used to delivery multi end-mobile product to the Appstore, but it is not allowed to re-sale or distribute the source code to other people.

Please help to check the detail from here - https://codecanyon.net/licenses/standard?license=regular 

Thank you!
