### ISSUE TITLE
Products and vendors are not showing in MstoreMV

### ISSUE THREAD

**Issue by amirkhld** [inspireui/support#3971]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: I am setting up my app, followed the instructions, however, it gets the gategories and the number of products but not the products themselves and the vendors.
please note two things : 
I have bought Fluxtore MV before buying Mstore MV thus I have used the liscence key of Fluxstore in the Mstore plugin ( is that a problem? I couldn't change the liscence number).
For WC vendors pro, I don't have a liscence key (is that the reason I'm no getting the products? )
+ Product & version: MStore Multi Vendor 1.3.3
+ Flutter (or React Native) version:  React
+ Testing Device/Simulator: Pixel 3 Api 28 and oneplus 5T
+ Screenshot issues (drag the file to attach here): 
![2020-06-29_13-32-02](https://user-images.githubusercontent.com/5295784/86000137-68929700-ba0d-11ea-9a5c-d91cb2b37aa3.png)
![2020-06-29_13-32-26](https://user-images.githubusercontent.com/5295784/86000139-692b2d80-ba0d-11ea-9e98-d573cadb53b3.png)
![2020-06-29_13-33-06](https://user-images.githubusercontent.com/5295784/86000142-69c3c400-ba0d-11ea-962f-8827ef596dcc.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**
done

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by amirkhld** [comment]
> Thank you for the feedback.
> 
> Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.
> 
> We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!
> 
> > **[Google Forms - create and analyze surveys, for free.](http://verify.inspireui.com/)**Create a new survey on your own or with others at the same time. Choose from a variety of survey types and analyze results in Google Forms. Free from Google.

I did when I send the issue, plz check

**Comment by minhcasi** [comment]
verified ✅

@luyx2412 - pls help with checking

**Comment by luyx2412** [comment]
Hi @amirkhld I just checked your config file and your wordpress lack of config multi vendor. Please see the screenshot and read the document to setup your website. https://docs.inspireui.com/mstore-mv
![image](https://user-images.githubusercontent.com/8909619/86134484-e2ad4380-bb13-11ea-9431-dc0f73d9a517.png)

Thanks

**Comment by amirkhld** [comment]
Dear @luyx2412 I didn't understand what do you mean by "your wordpress lack of config multi vendor", I did everything as mensioned in the docs but nothing. FYI, in the WCV plugin I changed "stores" by "Boutiques" if this changes anything. for this api, it works fine I guess : https://happyprix.com/wp-json/wc/v3 
Best regards, Amir

**Comment by amirkhld** [comment]
![newerror](https://user-images.githubusercontent.com/5295784/86154761-cf927780-bb03-11ea-9be9-8b1d6d30046f.png)
I get this error now

**Comment by amirkhld** [comment]
kind remider plz

**Comment by luyx2412** [comment]
HI @amirkhld Please replace this file to `src/components/HorizonList/Categories/index.js` to fix the issue.
[index.js.zip](https://github.com/inspireui/support/files/4864900/index.js.zip)

Thanks
