### ISSUE TITLE
Spaces in product list layout

### ISSUE THREAD

**Issue by hinai** [inspireui/support#3972]
Hi , I'm using fluxstore 1.7.5 and I have an issue  of spaces in product list ,please find attached  below :

![20200629_171750](https://user-images.githubusercontent.com/4161259/86010482-891e1980-ba2c-11ea-84b0-175b7f222be8.jpg)

- I tried to modify product_list.dart file in childAspectRatio but gives me ratio error.
- I regenerate  thumbnails but still same problem. 

Thanks 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

#3437

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by ameenbadri7** [comment]
hello, @hinai Wellcome back

if you want to remove the spaces you would replace the `lib\widgets\product\product_card_view.dart` with this file: 
[product_card_view.zip](https://github.com/inspireui/support/files/4847341/product_card_view.zip)

it will replace  the old: 
```
 return GestureDetector(
      onTap: onTapProduct,
      child: Tools.image(
        url: item.imageFeature,
        width: width,
        size: kSize.medium,
        isResize: true,
        // height: _height,
        fit: BoxFit.cover,
        offset: offset ?? 0.0,
      ),
    );
  }
```

with the new :
```
return GestureDetector(
      onTap: onTapProduct,
      child: Tools.image(
        url: item.imageFeature,
        width: width,
        height: width * 1.2,
        size: kSize.medium,
        isResize: true,
        // height: _height,
        fit: BoxFit.cover,
        offset: offset ?? 0.0,
      ),
    );
  }
```

and also you could learn more by going to this [link ](https://github.com/inspireui/support/issues/3662).
and also try to use the [inspector ](https://www.youtube.com/watch?v=yGMt3Y20Zmg) to fix any UI issues you have or try to customize your app the way you want.

thank you for your time sir.

**Comment by hinai** [comment]
thanks
