### ISSUE TITLE
Is it possible to get to Settings page without login? FluxNews 1.4.1

### ISSUE THREAD

**Issue by admincode1** [inspireui/support#3973]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
Is it possible to get to Settings page without login, if so, what do I need to edit?

+ Product & version:
FluxNews 1.4.1

+ Flutter (or React Native) version: 
N/A

+ Testing Device/Simulator:
 Android phone

+ Screenshot issues (drag the file to attach here): 
N/A

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by ameenbadri7** [comment]
try to work around with `lib\common\config\general.dart`
const kLoginSetting
and also 
kDefaultDrawer

please submit and we will finish this support.

**Comment by minhcasi** [comment]
verified ✅

**Comment by admincode1** [comment]
Hello Amin,

Thanks for your response.

I dont have lib\common\config\general.dart in this application.

I found the kDefaultDrawer on config.dart but editing it only make changes
on the side menu.

Searching in folder "lib", kLoginSetting is not found.

**Comment by ameenbadri7** [comment]
are you using [Fluxnews 1.4.1](https://docs.inspireui.com/fluxnews/changelogs/)? or old versions.

please update to the latest.

**Comment by admincode1** [comment]
I'm using Fluxnews 1.4,1 the latest version.

**Comment by ameenbadri7** [comment]
I am sorry I send you the fluxstore setting ..

please use this : 

the fluxnews on  `lib/common/config.dart`
const kDefaultDrawer = {
  "logo": "assets/images/logo.png",
  "background": null,
  "items": [
    {"type": "home", "show": true},
    {"type": "web", "show": true},
    {"type": "about", "show": true},
    {"type": "login", "show": true},
    {"type": "category", "show": true}
  ]
};

put false to hide anything like the login 
    {"type": "login", "show": true},
to 
    {"type": "login", "show": false},

also inside the same file make sure its false : 

```
const kAdvanceConfig = {
.....  
  "IsRequiredLogin": false,
.....  
};
```
also, remove this from the tap bar option : 

```
 {
      "layout": "profile",
      "icon": "assets/icons/tabs/icon-user.png"
    }
```
from all your config_xx.json like :
 
`lib\common\config_ar.json`
`lib\common\config_en.json
``lib\common\config_vn.json
`
hope those help?

**Comment by admincode1** [comment]
I changed:
{"type": "login", "show": false},
&
const kAdvanceConfig = {
.....  
  "IsRequiredLogin": false,
.....  
};

but still get to sign in page when I click on profile in TabBar.

If I remove:

 {
      "layout": "profile",
      "icon": "assets/icons/tabs/icon-user.png"
    }
from config_xx.json, the profile icon will be removed from TabBar & there is no way to get to settings page.

I still need the profile but just to go to setting page not the login page.

Thanks

**Comment by ameenbadri7** [comment]
ok. our higher developer @dttrung26  we help you from here.

thank you for your patience @admincode1

**Comment by dttrung26** [comment]
Hi @admincode1 ,
copying and replacing attached files in your /lib/screens would adapt your customization. Let me know if it helped!
Thanks for your help, btw @ameenbadri7. I really appreciate it :D 
Have a nice day!

**Comment by admincode1** [comment]
Hello dttrung26,
It worked very well, thanks for your support 👍
