### ISSUE TITLE
Paid updating service

### ISSUE THREAD

**Issue by rihtak2020** [inspireui/support#3974]
Hey i bought your flutter woocommerce code, when you release a new version can you provide a paid updating service ?

**Comment by ameenbadri7** [comment]
hello @rihtak2020, welcome back

yes, sure we do have a GitLab privet repo it has our code updated regularly you can use our update for life.

can you submit 

please send us your GitLab account to our email minhcasi@gmail.com and inspireui-team@inspireui.com. we will add you as soon as possible.
