### ISSUE TITLE
Multi Store magento set up 

### ISSUE THREAD

**Issue by subhakanta** [inspireui/support#3975]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 

1. I have one website with 2 stores . I need user to select store and enter the app . How can i configure mulitistore magento website.

2. payment method error . Please check attached screenshot

Product & version: Fluxstore Pro 1.7.5
Flutter (or React Native) version:
Testing Device/Simulator: iPhone 11

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

Important Note:

![WhatsApp Image 2020-06-29 at 10 28 06 PM](https://user-images.githubusercontent.com/7837160/86040792-8cb99c80-ba3c-11ea-87c0-3778e1d839b6.jpg)

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by ameenbadri7** [comment]
hello, @subhakanta
thank you for your feedback but please don't share your purchasing licensing number here you should always use http://verify.inspireui.com to submit privet keys.

for now, there is a significant number of request supports right now and we are working very hard in solving every single one of them.
we could not take customization requests you can use our [guide  ](https://docs.inspireui.com/fluxstore/magento-setup/) to learn more. 

thank you we have to close this ticket.
