### ISSUE TITLE
(URGENT) Multivendor Shipping Methode

### ISSUE THREAD

**Issue by grnas00** [inspireui/support#3976]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues:  I have an error when retrieve the Multi vendor shipping methods shipping method retrieve with zero cost 
+ Product & version: Fluxstore 1.7.5
+ Flutter (or React Native) version: Flutter (Channel stable, v1.17.3, on Microsoft Windows [Version 10.0.18363.900])
+ Testing Device/Simulator: Simulator Android SDK 29.0.0
+ Screenshot issues (drag the file to attach here): 

![Screenshot_1593449804](https://user-images.githubusercontent.com/24503019/86034134-b37ad180-ba42-11ea-93b4-74d6cd47f739.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by ameenbadri7** [comment]
hello @grnas00 Wellcome back 
if you are using woocommerce as a backend for your app 
please consider using this woocommerce [guide](https://docs.woocommerce.com/document/flat-rate-shipping/)
and also our [guide](https://docs.inspireui.com/fluxstore/multi-payment/#2-payment-options)
to setup the shipping on your app.
please let us know if you still have problems.

**Comment by grnas00** [comment]
Dear Amin, I saw and tested this guide two weeks ago, but I need all shipping methods for each vendor ,, please, I need my help to solve this problem as soon as possible. Thank you

**Comment by Shopyloot** [comment]
Yes, in wcfm each vendor have their own shipping method

**Comment by ameenbadri7** [comment]
Our team will investigate about this issue ASAP.  
Thank you for your patients.

**Comment by minhcasi** [comment]
@minhtruong315 - pls help with checking

**Comment by grnas00** [comment]
hello
Any Update

**Comment by minhtruong315** [comment]
@grnas00 send me common folder via email: truong@inspireui.com
with subject:https://github.com/inspireui/support/issues/3976

**Comment by grnas00** [comment]
> 
> 
> @grnas00 send me common folder via email: [truong@inspireui.com](mailto:truong@inspireui.com)
> with subject:#3976
check your inbox
Thx & BR

**Comment by grnas00** [comment]
any update

**Comment by minhtruong315** [comment]
@grnas00 I'm checking.I will send you updates today

**Comment by grnas00** [comment]
Thanks for support I'm waiting update 
thanks a lot

**Comment by minhtruong315** [comment]
Hi @grnas00 your config is dokan type
```
"type": "dokan",
  "url": "https://www.dokanline.com",
```
But I checked your admin, you dont install dokan, you're using wcfm

**Comment by grnas00** [comment]
Sorry in last day im change dokan to wcfm

**Comment by grnas00** [comment]
If you need to return to dokan i can do that for you

**Comment by minhtruong315** [comment]
yes. pls return dokan

**Comment by grnas00** [comment]
Ok get me 10 minutes

**Comment by grnas00** [comment]
sorry for late Dokan Plugin Now is install you can try now

**Comment by grnas00** [comment]
i'm waiting your response if it's ok

**Comment by minhtruong315** [comment]
I checked your website. it's working well. I will send u the latest source code. then you can check again
![Simulator Screen Shot - iPhone 11 - 2020-07-06 at 16 32 29](https://user-images.githubusercontent.com/10402500/86578813-985e1380-bfa6-11ea-95ce-7f1d79601082.png)

**Comment by grnas00** [comment]
Sorry but this method in woocommerce not in vendor
do you like to add vendor shipping to show error??

**Comment by minhtruong315** [comment]
can u take me screenshot for address? because shipping methods are showing based on the address.

**Comment by grnas00** [comment]
Dear Inspireui/Support
the same error when retrieve the vendor shipping method
please check screenshot
[image: image.png]

**Comment by grnas00** [comment]
and this image for cost to product shipping by vendor shipping method

[image: image.png]

**Comment by minhtruong315** [comment]
@grnas00 I dont see the image. pls send it via my email. thanks

**Comment by grnas00** [comment]
Please send your email

**Comment by minhtruong315** [comment]
Hi @grnas00 Did you install plugin to support Zaid Shipping?

**Comment by grnas00** [comment]
> 
> 
> Hi @grnas00 Did you install plugin to support Zaid Shipping?
Hi @minhtruong315 Zaid Shipping is vendor shipping method not need to plugin it's same as flat rate in woo commerce but this method can set  from vendor control for each vendor

**Comment by minhtruong315** [comment]
@grnas00 change this function in models/shipping_method.dart like this
```
ShippingMethod.fromJson(Map<String, dynamic> parsedJson) {
    try {
      id = "${parsedJson["id"]}";
      title = isNotBlank(parsedJson["title"])
          ? parsedJson["title"]
          : parsedJson["method_title"];
      description = parsedJson["method_description"];
      methodId = parsedJson["method_id"];
      methodTitle = parsedJson["method_title"];
      cost = 0.0;
      if (parsedJson["settings"]["cost"] != null) {
        if (parsedJson["settings"]["cost"] is Map) {
          cost = double.parse(parsedJson["settings"]["cost"]["value"]);
        } else {
          cost = double.parse(parsedJson["settings"]["cost"]);
        }
      }
      parsedJson["settings"]["min_amount"] != null
          ? min_amount =
              double.parse(parsedJson["settings"]["min_amount"]["value"])
          : min_amount = null;
      Map settings = parsedJson["settings"];
      settings.keys.forEach((key) {
        if (key is String && key.contains("class_cost_")) {
          classCost = parsedJson["settings"][key]["value"];
        }
      });
    } catch (e) {
      printLog('error parsing Shipping method');
    }
  }
```

**Comment by grnas00** [comment]
OK , I will try it  and i send feedback to you

**Comment by grnas00** [comment]
the same error vendor shipping cost retrieve its zero 
Please inform me when find the solution for this error for this time i run my application without vendor shipping method but with woo-commerce shipping method its not bad but i think this feature he most be needed in future

**Comment by minhtruong315** [comment]
Can u record me screen? I dont know how to show that shipping

**Comment by grnas00** [comment]
https://drive.google.com/file/d/1jFqR6UmbE0rxaegIWiqlenU1od0sWuXu/view?usp=sharing

**Comment by Carlosdmendoza** [comment]
I have exactly the same issue the shipping methods on woocommerce side for my vendors are set to shipping by store depeniding on the vendor I am also using WCFM but when I go to the shipping methods type for some reason is showing in 0 is not showing the methods predefined in my website.

**Comment by grnas00** [comment]
any update

**Comment by mo-elkholy** [comment]
Hi, I have a similar problem, MV on woocommere , during checkout no vendor shipping method is showing.
How can we solve this issue?

**Comment by Carlosdmendoza** [comment]
I think the three of us are waiting for the same problem to be resolved

**Comment by mo-elkholy** [comment]
> I think the three of us are waiting for the same problem to be resolved

I spend 1 week running in circles, trying to debug, and the last thing I found is that the getVendorShippingMethods is returning null, and I don't know why.

The MStore Plugin in Wordpress is updated to lates version and activated with the purchase code.

Both Shipping and Payment gateway integration is a nasty problem to handle. But without it running properly all the effort building, styling and configuring the app is rendered useless.

I hope this is sorted soon Carlos. :)

**Comment by minhcasi** [comment]
@minhtruong315 - pls try to check the `getVendorShippingMethods` issue

**Comment by minhcasi** [comment]
@minhtruong315

**Comment by minhtruong315** [comment]
Hi @grnas00 can u give me your skype? I will help you check via teamviewer.
Thanks

**Comment by grnas00** [comment]
> 
> 
> Hi @grnas00 can u give me your skype? I will help you check via teamviewer.
> Thanks

Hi @minhtruong315  sure this is my email in skype zaid.k.mgarab@hotmail.com

**Comment by praveenasok** [comment]
I am also facing the same issue of Shipping Method showing 0 (zero) instead of looking up the amount from the Woocommerce backend. The shipping method works perfectly on Webview and the desktop website. Kindly help.

**Comment by minhtruong315** [comment]
@grnas00 You changed shipping address. so I can't help you fix shipping method issue after customize.
<img width="1248" alt="Screen Shot 2020-07-27 at 7 49 11 AM" src="https://user-images.githubusercontent.com/10402500/88493906-c5b64400-cfdd-11ea-8c50-31438c897258.png">

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
