### ISSUE TITLE
Fluxbuilder

### ISSUE THREAD

**Issue by mistergig** [inspireui/support#3977]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
I have installed the Fluxbuilder on my windows10 pc.
I have successfully connected my Fluxstore app in the builder.
But after i made some changes to the design , It seems not possible to save my project. 
When I do save than a message warning appears at the bottom of the screen : "Please active your purchase code before" .

But where exactly do I insert the purchase code?

+ Product & version:
Fluxbuilder v1.0.6
Fluxstore version 1.7.5

+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
Windows 10 pc
+ Screenshot issues (drag the file to attach here): 

https://prnt.sc/t8mdg9

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**
https://docs.google.com/forms/d/e/1FAIpQLScWOjkAJIWJ9rgb9alopfOqLsJrGKbFM5cCYj1JBfLKLsBblQ/viewform
on this page you say to first create a ticket on github.
but on Github you say to sumbit proof on that other page...
I think you can understand that your instructions are very confusing. I hope you realize this yourself

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by ameenbadri7** [comment]
hello, @mistergig thank you for using our products.
you can use this guide 
https://medium.com/@inspireui/fluxbuilder-an-ultimate-approach-for-flutter-mobile-apps-bccf42a7676b
and this 
[video ](https://www.youtube.com/watch?v=m-8oO-YVpOg) 

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by mistergig** [comment]
Hi,

Please can you answer my question. Where can i insert the purchase code ?
https://prnt.sc/t8qyzh

when i try to save the my project than this prompt message appears. "Please
active your purchase code before ".

Where exactly do i need to insert the purchase code?

Thanks,

Best Regards,
Rene ormskerk

‪Op ma 29 jun. 2020 om 21:33 schreef ‫amin badri أمين بدري‬‎ <
notifications@github.com>:‬

**Comment by ameenbadri7** [comment]
![79686623-16c9d580-8242-11ea-9abe-1482e94f6aae](https://user-images.githubusercontent.com/37524186/86065739-11c2a700-ba79-11ea-834b-b3a765acee2f.png)

From the last page after you finish the design on publish page.

**Comment by mistergig** [comment]
Hi,
Thanks for reply.
Yes, i have found it.
But now the system refuses to accept my purchase code https://prnt.sc/t8yt1s
I used this purchase code for 1 site only https://toy-tastic.nl/
So why is this code not correct?

Best regards,



‪Op di 30 jun. 2020 om 01:27 schreef ‫amin badri أمين بدري‬‎ <
notifications@github.com>:‬

**Comment by ameenbadri7** [comment]
@mistergig thank you for your feedback 
don't worry about this problem 
Our team will investigate this issue and it will be solved as soon as possible.

happy coding!

**Comment by minhcasi** [comment]
@vumanhsn97 - pls help to check the verify code issue

**Comment by minhcasi** [comment]
sent via email

**Comment by mistergig** [comment]
Hello,

According to your associate on Skype this purchase code is not valid.
I demand a clear explanation why this purchase code is not correct anymore?
This code was working fine before. We already have worked on the app and
its live in Play store and App store.

https://apps.apple.com/us/app/toytastic/id1518559452

https://play.google.com/store/apps/details?id=com.toytastic.store
So if you dont want to resolve this issue , than I think you should at
least explain clearly why this code is not valid anymore.

Or if you want we can submit this issue with Envato and let them
intermediate.

Best regards,

Op di 7 jul. 2020 om 09:38 schreef Minh Pham <notifications@github.com>:
