### ISSUE TITLE
Infinity load time when I try to sign in on sign up

### ISSUE THREAD

**Issue by eraldix** [inspireui/support#3978]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: I have done every step as in documents, but I get infinity load time. I can assure that there is not a problem with connection with my account because if I sign up i can see the account created on users on my dashboard and if I stop the loading screen it shows my account when i sign up, when i sign in doesn't show nothing.
+ Product & version: Latest
+ Flutter (or React Native) version: flutter
+ Testing Device/Simulator: android, ios seems to work
+ Screenshot issues (drag the file to attach here): 
![Screenshot_1593462820](https://user-images.githubusercontent.com/44481659/86055209-b930e100-ba5b-11ea-8b1b-163a1b6fabfa.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by ameenbadri7** [comment]
Hello, @earldom welcome back

some times the hosting server also effect the app performance. 
 And also your internet connection. 

 From your terminal :
 Flutter clean 

 Then build your app on release

 Use this to [guide you ](https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1).

 Delete you app from the emulator or device.
Downlad the latest fluxstore. 

I hope those can help you.  

Please let us know if you still having trouble.

**Comment by eraldix** [comment]
No luck, this is the latest code I'm getting:

W/al.pentazon(15571): Accessing hidden field Ljava/net/Socket;->impl:Ljava/net/SocketImpl; (greylist, reflection, allowed)
W/al.pentazon(15571): Accessing hidden method Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard; (greylist,core-platform-api, linking, allowed)
W/al.pentazon(15571): Accessing hidden method Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V (greylist,core-platform-api, linking, allowed)
W/al.pentazon(15571): Accessing hidden field Ljava/io/FileDescriptor;->descriptor:I (greylist, JNI, allowed)
W/al.pentazon(15571): Accessing hidden method Ljava/security/spec/ECParameterSpec;->setCurveName(Ljava/lang/String;)V (greylist, reflection, allowed)
W/al.pentazon(15571): Accessing hidden method Ldalvik/system/BlockGuard;->getThreadPolicy()Ldalvik/system/BlockGuard$Policy; (greylist,core-platform-api, linking, allowed)
W/al.pentazon(15571): Accessing hidden method Ldalvik/system/BlockGuard$Policy;->onNetwork()V (greylist, linking, allowed)

**Comment by ameenbadri7** [comment]
Could you check your Firebase project 
Maybe you have Reached the daily 50k free writes of firebase spark plan?

**Comment by eraldix** [comment]
> Could you check your Firebase project
> Maybe you have Reached the daily 50k free writes of firebase spark plan?

I have just created the firebase project, also i don't think it has to do with that also , because It doesn't log in directly also. One other thing to mention, if I sign up and I stop the infinity load it shows my account correctly.

**Comment by ameenbadri7** [comment]
Thank you @eraldix for your feedback about your project issue. 

Dont worry
I will assign more advance developers from our team to see your ticket.

Thank you for your patience.

**Comment by minhcasi** [comment]
@vumanhsn97 - please help to investigate this issue

**Comment by vumanhsn97** [comment]
@eraldix 
Can you send your latest code to vumanhsn97@gmail.com?

**Comment by vumanhsn97** [comment]
@eraldix 
Please check your firebase. You need to allow read and write in firebase database
https://tppr.me/yej29

**Comment by eraldix** [comment]
Yes that was it, thank you

**Comment by eraldix** [comment]
Also how can I make checkout from inside the app, I'm redirected to my
website

**Comment by vumanhsn97** [comment]
@eraldix 
In lib/common/config/payments.dart set onepagecheckout = false https://tppr.me/kRG5r
