### ISSUE TITLE
Banners images not showing

### ISSUE THREAD

**Issue by nomicool** [inspireui/support#3979]
Changing WEB URL API keys banners are not showing and some of products images not showing I have also generated the thumbnails

**Comment by ameenbadri7** [comment]
Those tips can help to improve your app: 

Disable you `isCache: false`
Also update your wordpress plugins `mstore`  and `regenerate thumbnails `
And disable the `wp cache` plugin. 

Also if you have multiple languages in your site update the wpml products text and other strings. 

Clean your flutter project : `flutter clean` 
Also build for release. 

I guess it will work perfectly. 

Let us know if you still having issues in your app. 

Use our documentations to find out more tips 
docs.inspireui.com/fluxstore

Thank you for your time!

**Comment by nomicool** [comment]
its not fluxxstore its react native yarn mstore mv expo

**Comment by minhcasi** [comment]
@nomicool - could you submit the license for mstore mv to this ticket  http://verify.inspireui.com/

Your ticket does not enough info so that we think the question related to your previous ticket. Try to explain more detail as soon as possible - thanks

**Comment by nomicool** [comment]
i have subitted icense and its MStore Multi Vendor - Complete React Native template for WooCommerce, App I have changed API key on home page single category and image showing other does not empty and banners also not shwing

**Comment by luyx2412** [comment]
Hi @nomicool Can you share me your screenshot? I will investigate easier, and reply you soon.

Thanks

**Comment by nomicool** [comment]
here are the all empty banners one category showing image other is not. https://ibb.co/Bc3g71b
https://ibb.co/2WZ0G9q
https://ibb.co/0B6WGJ3 all shots on these links please reply quick

**Comment by luyx2412** [comment]
Hi @nomicool Please make sure you add right category id in AppConfig.json. This is the document MStore MV https://docs.inspireui.com/mstore-mv/quick-setup.

Thanks

**Comment by nomicool** [comment]
i understand to add category id i will add them i simply needs to know why banners are not appearing over there

**Comment by nomicool** [comment]
You can close your ticket I have fixed the issue my self I traced it well thanks for the help . it would be great if you can help me with another app issue is occurring ticket id is 4032

**Comment by bogatoons** [comment]
@nomicool how did you solve the banners issue? i have same problem.
