### ISSUE TITLE
How can i improve the App performance. I followed the steps of FluxStore but its not working.Please help me asap

### ISSUE THREAD

**Issue by phenomenal25** [inspireui/support#3981]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by phenomenal25** [comment]
[57848916-fluxstore-the-universal-woocommerce-magento-opencart-mobile-app-by-flutter-framework-license.pdf](https://github.com/inspireui/support/files/4849484/57848916-fluxstore-the-universal-woocommerce-magento-opencart-mobile-app-by-flutter-framework-license.pdf)

**Comment by minhcasi** [comment]
@phenomenal25 - as you can see you have closed the ticket so that the team could not get notified, please help to share the detailed config via step 2 so that we could help to investigate the issue - thank you!
