### ISSUE TITLE
Error loading products information in magento and need support for multi store

### ISSUE THREAD

**Issue by subhquad** [inspireui/support#3982]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
1. Getting error when loading products data . 
2 Does fluxstore multi store website ? We have multistore magento set up.
+ Product & version:  Fluxstore Pro 1.7.5
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: iphone 11 
+ Screenshot issues (drag the file to attach here): 

<img width="368" alt="Screenshot 2020-06-30 at 07 50 53" src="https://user-images.githubusercontent.com/10830054/86093381-c45d2e80-baa6-11ea-98bc-02e366bc2c96.png">

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@subhquad - the current release of Fluxstore will not support multi-store products on Magento site - thank you!

**Comment by subhquad** [comment]
<img width="362" alt="Screenshot 2020-06-30 at 21 26 22" src="https://user-images.githubusercontent.com/10830054/86177064-e47c0480-bb1d-11ea-8d7b-64e2b4f851b8.png">
Cant proceed with payment.

**Comment by minhtruong315** [comment]
Hi @subhquad 
Can you fork from our git repo then invite me: minhtruong315@gmail.com?
 https://medium.com/@inspireui/how-to-upgrade-fluxstore-projects-by-using-git-cebde7489ea6
 I will help you check your issues 
Thanks

**Comment by subhquad** [comment]
I will fork and add you

**Comment by subhquad** [comment]
https://gitlab.com/inspireui/fluxstore-pro getting 404 error

**Comment by minhtruong315** [comment]
Hi @subhquad  can u give me your email? I will add to our repo

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
