### ISSUE TITLE
Fluxnews welcome screen shows every run

### ISSUE THREAD

**Issue by jodi3mad** [inspireui/support#3983]
+ Detail Issues: 
welcome screen shows every run
+ Product & version:
Fluxnews 1.4.1
how to solve that , with every run in debug or release mode shows welcome screen, also after signing in keeps welcome scerrn shows up.

**Comment by minhcasi** [comment]
Duplicate of #3757

I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
