### ISSUE TITLE
Add Username Box in LoginSMS

### ISSUE THREAD

**Issue by boqaqa** [inspireui/support#3984]
Hello, 2 issue please.

1. Can I add a "username box" in the SMS sign up page, so that when a new user creates account he puts his username and number. like shown in the picture below.

2. "Rate this App" Translation is not changing, I have added three languages and translated everything in Lib/110n but translation did not change. 

![purchase pic](https://user-images.githubusercontent.com/65863900/86105175-afdd5e00-bac7-11ea-9bec-59aca92299a2.jpg)

![sms](https://user-images.githubusercontent.com/65863900/86105204-b79d0280-bac7-11ea-8237-01470ff53e2b.jpg)

![Screenshot_20200630-115245](https://user-images.githubusercontent.com/65863900/86112561-cd62f580-bad0-11ea-84ba-989b2b640b37.jpg)

**Comment by minhcasi** [comment]
@boqaqa 
1. yes - you can customize the form base on your requirement, also try to update the app code to submit the username into `mstore-api` plugin as well

2. The translate from rate my app is not available from the app, but you could see on this document to add new translate - https://pub.dev/packages/rate_my_app 

<img width="974" alt="Screen Shot 2020-06-30 at 17 24 10" src="https://user-images.githubusercontent.com/1459805/86115715-84be3300-baf6-11ea-99ec-eab89aa4492c.png">

**Comment by boqaqa** [comment]
Thanks no.2 is solved but no.1 is hard to do it.

Can you please add it in the next update or send me customized files with username.

**Comment by boqaqa** [comment]
Please @minhcasi it is urgent because my app provides only SMS Login and I have removed Update Profile Feature from the App, The User is unable to Comment on products because he does not have a Display Name Please try to send me customized files with username featuse on LoginSMS page and thanks.

**Comment by boqaqa** [comment]
Thanks @minhcasi I have came out with a temporary solution, It's not urgent anymore I can wait for an update with this feature.

**Comment by and-eee** [comment]
@boqaqa would you mind sharing your temporary solution? I need to do the same thing. Thanks.

**Comment by boqaqa** [comment]
@and-eee It's an honor if I could help, But the reason why I was looking for the Username was to hide the "User's Number in the Comment Section" Because when a user Sings up with SMS, The Displayed name will be his phone number.

If that is what you are looking for here is what I did:

I have used Flutter Inspector in Android Studio and changed The "User Name Container in the comment Section" and changed it to a text "Customer" That I have already added in 110n.dart

**Comment by boqaqa** [comment]
Other problem was when a user creates an account with SMS, He cannot comment on products until he updates his profile, here is what I did I have edited some lines in C:\src\flutter\77\17\source\lib\models\user\user.dart

import 'user_address.dart';

class User {
  String id;
  bool loggedIn;
  String name;
  String firstName;
  String displayName;
  String lastName;
  String username;
  String email;
  String nicename;
  String userUrl;
  String picture;
  String cookie;
  Shipping shipping;
  Billing billing;
  bool isSocial = false;

  User.fromWoJson(Map<String, dynamic> json) {
    try {
      id = json['id'];
      username = json['username'];
      firstName = json['wp_user_firstName'];
      lastName = json['wp_user_lastName'];
      displayName = json['wp_user_displayName'];
      nicename = json['wp_user_nickName'];
      shipping = Shipping.fromJson(json['shipping']);
      billing = Billing.fromJson(json['billing']);
    } catch (e) {
      print(e.toString());
    }
  }

  // from WooCommerce Json
  User.fromJsonFB(Map<String, dynamic> json) {
    try {
      isSocial = true;
      var user = json['user'];
      loggedIn = true;
      id = json['wp_user_id'].toString();
      name = user['name'];
      username = user['user_login'];
      cookie = json['cookie'];
      firstName = user["first_name"];
      lastName = user["last_name"];
      firstName = user['display_name'];
      email = user["email"];
      picture = user["picture"] != null &&
              user["picture"]["data"] != null &&
              user["picture"]['data']['url'] != null
          ? user["picture"]['data']['url']
          : '';
    } catch (e) {
      print(e.toString());
    }
  }

  // from WooCommerce Json
  User.fromJsonSMS(Map<String, dynamic> json) {
    try {
      var user = json['user'];
      loggedIn = true;
      id = json['wp_user_id'].toString();
      name = json['user_login'];
      cookie = json['cookie'];
      username = json['id'];
      firstName = json['wp_user_firstName'];
      lastName = json['wp_user_lastName'];
      nicename = json['wp_user_nickName'];
      displayName = json['wp_user_displayName'];
      email = user['email'] ?? user['id'];
      isSocial = true;
    } catch (e) {
      print(e.toString());
    }
  }


  Map<String, dynamic> toJson() {
    return {
      "id": id,
      "loggedIn": loggedIn,
      "name": name,
      "firstName": firstName,
      "lastName": lastName,
      "username": username,
      "displayname": displayName,
      "email": email,
      "picture": picture,
      "cookie": cookie,
      "nicename": nicename,
      "url": userUrl,
      "isSocial": isSocial
    };
  }

  User.fromLocalJson(Map<String, dynamic> json) {
    try {
      loggedIn = json['loggedIn'];
      id = json['id'].toString();
      name = json['name'];
      cookie = json['cookie'];
      username = json['username'];
      firstName = json['firstName'];
      lastName = json['lastName'];
      email = json['email'];
      picture = json['picture'];
      nicename = json['nicename'];
      userUrl = json['url'];
      isSocial = json['isSocial'];
    } catch (e) {
      print(e.toString());
    }
  }

  // from Create User
  User.fromAuthUser(Map<String, dynamic> json, String _cookie) {
    try {
      cookie = _cookie;
      id = json['id'].toString();
      name = json['displayname'];
      username = json['username'];
      firstName = json['firstname'];
      lastName = json['lastname'];
      email = json['email'];
      picture = json['avatar'];
      nicename = json['nicename'];
      userUrl = json['url'];
      loggedIn = true;
    } catch (e) {
      print(e.toString());
    }
  }

  @override
  String toString() => 'User { username: $id $name $email}';
}

class UserPoints {
  int points;
  List<UserEvent> events = [];

  UserPoints.fromJson(Map<String, dynamic> json) {
    points = json['points_balance'];

    if (json['events'] != null) {
      for (var event in json['events']) {
        events.add(UserEvent.fromJson(event));
      }
    }
  }
}

class UserEvent {
  String id;
  String userId;
  String orderId;
  String date;
  String description;
  String points;

  UserEvent.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    userId = json['user_id'];
    orderId = json['order_id'];
    date = json['date_display_human'];
    description = json['description'];
    points = json['points'];
  }
}

After doing this, User's phone number will displayed in the "comment section" , Next I have used Flutter Inspector to edit the phone number Box in the comment section and put "customer" instead of number.

Sorry If that not helped.

**Comment by and-eee** [comment]
@boqaqa thank you for taking the time to go through that, I am not going to be using reviews on my site but I have quite a few aspects of the Woocommerce back-end that require the user's actual name. I will go through the code you very kindly sent and see if I can adapt it. Good luck with your project :)

**Comment by boqaqa** [comment]
You welcome @and-eee  and good luck to you too.
