### ISSUE TITLE
I dont want to 3 intro screen

### ISSUE THREAD

**Issue by wolverineee92** [inspireui/support#3987]
**_Step 1 (require): describe detail issues & screenshots_**

+ Detail Issues: 

i dont want 3 intro screen...open the app then splash screen

+ Product & version:

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ 
- please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by wolverineee92** [comment]
hello

**Comment by wolverineee92** [comment]
![proof](https://user-images.githubusercontent.com/67648501/86156717-04aec200-bb24-11ea-8464-0f7694bf6ee1.png)
![Uploading proof.png…]()

**Comment by wolverineee92** [comment]
I want to use short description in my app.....i dont want use main description..

**Comment by minhcasi** [comment]
@wolverineee92 

Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by wolverineee92** [comment]
I am waiting for your response

**Comment by minhcasi** [comment]
@wolverineee92 - pls send your License PDF to http://verify.inspireui.com as the screenshot will not valid - one you have submitted the form, please reopen this ticket - thank you for your time
