### ISSUE TITLE
I want to use short description in my app

### ISSUE THREAD

**Issue by wolverineee92** [inspireui/support#3988]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 

I want to use short description in my app

+ Product & version:

Mstore expo 

+ Flutter (or React Native) version: 

latest version

+ Testing Device/Simulator: 
simulator 

+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**Comment by ameenbadri7** [comment]
Please add this ticket with your other ticket and confirm you purchase with the link 

 http://verify.inspireui.com/ 

Please sir don't do multiple issues and covert them to one issue .
