### ISSUE TITLE
Hii Please reopen My ticket I have some issues with our fluxstore app

### ISSUE THREAD

**Issue by amitw7786** [inspireui/support#3989]
Hii Please reopen My ticket I have some issues with our fluxstore app

_Originally posted by @amitw7786 in https://github.com/inspireui/support/issues/3181#issuecomment-651827259_

**Comment by ameenbadri7** [comment]
hello, @amitw7786 Welcome back
I have now reopening your ticket, we can continue the support there.
I will close this. 
thank you
