### ISSUE TITLE
[MStore Multi vendor]Login/Registration Bug

### ISSUE THREAD

**Issue by WOEXX** [inspireui/support#399]
Here is the details
- MStore Multi Vendor - Complete React Native template for WooCommerce
- Item Purchase Code: a4b5bb4d-13c3-481a-985b-6b403580a121
- Item URL: https://codecanyon.net/item/mstore-multi-vendor-complete-react-native-template-for-ecommerce/22278924

**Describe the bug**
Login and registration not working, Below you will find wordpress credentials and expo details
https://vnzy.com/admin
U: admin
P: demo

https://expo.io/@woexx/vnzy
U: WOEXX
P: 330000

I've installed all the wordpress plugin and followed up your guide, everything seems fine but users cannot login, register and checkout using app. 

Looking forward to hear you soon

**Comment by luyx2412** [comment]
HI @WOEXX can you send the AppConfig.json and Config.js file?

Thanks

**Comment by WOEXX** [comment]
Here you go

[vnzy-config.zip](https://github.com/inspireui/support/files/2969404/vnzy-config.zip)

**Comment by thangvo9x** [comment]
The error is coming from here 
https://vnzy.com/api/mstore_user/generate_auth_cookie/?second=120&username=&password=
Please fix it. or try disable_debug on your website.
More, you should change Firebase info in Config.js file

**Comment by WOEXX** [comment]
Okay, thank you. Its working

Can we make the app homepage layout, exactly like app store demo application. Featured product and 3 columns with lazy loading.

And how do i place user icon to bottom navigation. See attached 

![WhatsApp Image 2019-03-15 at 2 59 19 PM](https://user-images.githubusercontent.com/10099915/54421687-f8d29d00-4732-11e9-9c12-61097e432e67.jpeg)

**Comment by thangvo9x** [comment]
Your mean changes bottom icon? You can go to navigatioin/index.js 
change in tabBarIcon property

**Comment by WOEXX** [comment]
It's there, but it shows different icon. Is there anyway to get same copy as your app store demo?

**Comment by thangvo9x** [comment]
Hi. This problem is out of our support. Thanks

**Comment by ZamanGoraya** [comment]
i have a problem in mstore ... when user do login in my app  loged him as a vender... how can i solve the problem..?

**Comment by ZamanGoraya** [comment]
[mstore multi vender]i have problem in login ... the app is login me only as wonder... even i try with user i'd...

**Comment by ZamanGoraya** [comment]
[mstore multi vendor]i have problem in login ... the app is login me only as wonder... even i try with user i'd...
