### ISSUE TITLE
FluxNews Setup Google Login IOS 

### ISSUE THREAD

**Issue by haidarsalim** [inspireui/support#3992]
FluxNews Version: 1.4.1
Flutter : v1.17.3
xcode mac

Having trouble logging in with Google and Apple id, a sudden exit to the application occurs
I can't find a place to add REVERSED_CLIENT_ID
[Info.plist.zip](https://github.com/inspireui/support/files/4854687/Info.plist.zip)

![444](https://user-images.githubusercontent.com/54249914/86183573-ff10a680-bb3a-11ea-9a07-1ff1357a732d.PNG)
There is no place to add this code found in YouTube
![555](https://user-images.githubusercontent.com/54249914/86183580-02a42d80-bb3b-11ea-89b2-3496dd4d72aa.PNG)

**Comment by dttrung26** [comment]
Hi  @haidarsalim ,
According to the step in tutorial video, just right below the tag `<key>CFBundleURLSchemes</key>` and inside the next `<array> ... </array>` tag, you can add another `<string> [YOUR_RESERVED_CLIENT_ID_CODE] </string> ` here. Please bear in mind that it has to be in the same level as other `string` tab if existed. 
Hope this helped.

**Comment by haidarsalim** [comment]
> Hi @haidarsalim ,
> According to the step in tutorial video, just right below the tag `<key>CFBundleURLSchemes</key>` and inside the next `<array> ... </array>` tag, you can add another `<string> [YOUR_RESERVED_CLIENT_ID_CODE] </string> ` here. Please bear in mind that it has to be in the same level as other `string` tab if existed.
> Hope this helped.

**Can you include this in the attached file Info.plist  To avoid errors**

**Comment by dttrung26** [comment]
Hi @haidarsalim , 
As every single system generates different Info.plist file for accessing stored configuration data, my file definitely is different than yours and may not work in your case. 
Best!

**Comment by haidarsalim** [comment]
@dttrung26   My file is attached
[Info.plist.zip](https://github.com/inspireui/support/files/4854687/Info.plist.zip)
Can this be done?

**Comment by dttrung26** [comment]
Hi @haidarsalim , 
the file format is right, but the reserved client id code from google services file seems wrong. Every client code should start with `com.googleusercontent...`. Please double-check previous step in tutorial video. 
Best!

**Comment by haidarsalim** [comment]
You have added this way
Now works well
![555](https://user-images.githubusercontent.com/54249914/86353371-cfaf8600-bc6f-11ea-9397-2379583ea3d4.PNG)

**Comment by haidarsalim** [comment]
I only have one problem in login button with apple id

```
 التطبيقات[11160:1033390] [core] Authorization failed: Error Domain=AKAuthenticationError Code=-7026 "(null)" UserInfo={AKClientBundleID=com.baytaltatbiqat.app}
2020-07-02 14:17:47.620265+0300 بيت التطبيقات[11160:1032873] flutter: Sign in failed: The operation couldn’t be completed. (com.apple.AuthenticationServices.AuthorizationError error 1000.)
```
![Capture](https://user-images.githubusercontent.com/54249914/86353696-56646300-bc70-11ea-9d00-38ddb51f95e1.PNG)

**Comment by dttrung26** [comment]
Hi @haidarsalim , 
Since AuthorizationError error code 1000 is UNKNOWN error, I can't tell exact way to work around that. However, you could try following steps: 
- Try to execute Apple Signin in physical devices. Some experience this error in emulators only. 
- Make sure your config in apple + firebase developer console are perfectly done. 
- Edit configuration in xcode: `TARGETS>Signing & Capabilities>+Capability` then search `sign in` then add it.
- Add `Sign In Capability` in both development and release version. 
Hope this helps!

**Comment by haidarsalim** [comment]
The button now works, but when you log out, you cannot go back and log in
https://vimeo.com/435159052

**Comment by dttrung26** [comment]
Hi @haidarsalim , 
Does your above video illustrate a second attempt login after you've already logged in and logged out?

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one with full information - thank you for your time!
