### ISSUE TITLE
Welcome screen/setting page FluxNews  1.4.1

### ISSUE THREAD

**Issue by jodi3mad** [inspireui/support#3996]
**_Step 1 (require): describe detail issues & screenshots_**

+ Detail Issues: 
hi, could you please help me to fix these problems :

1-welcome screen keeps showing up every run in debug/release.
2-i want using settings page without login.
3-DefaultPhoneISOCode  - login with sms default country ant be changed to another.

thanks in advance.

+ Product & version:
 FluxNews 1.4.1

+ Flutter (or React Native) version: 

+ Testing Device/Simulator: 
Android phone

+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by jodi3mad** [comment]
Hi  dttrung26 
I'm waiting for ur advices

**Comment by dttrung26** [comment]
Hi @jodi3mad , 
- For #2 customization, you can prefer to this [ticket](https://github.com/inspireui/support/issues/3973) where I've already posted a solution. 
- For #3 customization, I've also gave a solution for this customization which you can take a look at this [ticket](https://github.com/inspireui/support/issues/3796)
- For #1 bug, I will take a look and get you back in a few hours. 
Have a nice day!

**Comment by jodi3mad** [comment]
Hi @dttrung26 
thanks for ur response.
**#3** solved 👍 .
**#2** solved. setting page without login ok but showing Logout without signing in.---screenshot
![Screenshot_1593617305](https://user-images.githubusercontent.com/33659977/86263043-f19dff80-bbc0-11ea-9c2d-d27979d32c7c.png)

**#1** still waiting for ur solution.

**Comment by jodi3mad** [comment]
Hi @dttrung26 
any update !

**Comment by dttrung26** [comment]
Hi @jodi3mad , 
please download and replace the following file:
- app_init.dart in /lib/
- constants.dart in /lib/common/
- onboard_screen.dart at /lib/screens/home
- settings.dart at /lib/screens/ 
[ticket#3996.zip](https://github.com/inspireui/support/files/4863567/ticket.3996.zip)

Those files will temporarily fix on-boarding screen issues as well as adapt your customization at setting pages.
Let me know if it works.
Best!

**Comment by jodi3mad** [comment]
hello  @dttrung26 
thanks for ur professional supports. 
ur temporarily solution works well 👍 , thanks 4 ur efforts. 👍 
and will waiting 4 next patch.
good luck and B safe.
Best !

**Comment by jodi3mad** [comment]
hello @dttrung26
thanks for ur professional supports.
ur temporarily solution works well 👍 , thanks 4 ur efforts. 👍
and will wait 4 next patch.
good luck and B safe.
Best !

**Comment by jodi3mad** [comment]
Now every thing is ok 👌, **lastly** the app won't save the last Sisson.
i mean when closing app,  opening again all running well but not saving my dark mode and my login info.
and i must to login again.
Have a great day .
Best,

**Comment by dttrung26** [comment]
Hi @jodi3mad , 
- As I checked login part, I can ensure your FluxNews could store user's last login session. 
- Currently, FluxNews does not support store DarkTheme in local storage. We'll consider adding this feature in few next patches. However, if you are really in need of this feature, you can investigate and implement it yourself by playing around with this package: https://pub.dev/packages/localstorage. 

If you are satisfied with our customer support, a rating for us on: https://codecanyon.net/item/fluxnews-fluxnews-flutter-mobile-app-for-wordpress/24569377 would be a great motivation for us to continue bringing you an amazing support serice. 

Happy coding mate!
