### ISSUE TITLE
How to change Variation Design in M-Store Pro

### ISSUE THREAD

**Issue by kunalkhandol** [inspireui/support#3997]
I have a few queries:
1) How to change the layout/design of product variation fro dropdown to swatches.
2) How do I upgrade MStore to 4.0? I am already using old version. Shall I replace the whole folder or what? did you maintain GIT so I can see which files are modified.

Thanks in Advance
Kunal

**Comment by luyx2412** [comment]
HI @kunalkhandol 
- In `src/containers/Detail/index.js` line 659 follow the screenshot, you can edit the component in there
![image](https://user-images.githubusercontent.com/8909619/86369241-597b4580-bca8-11ea-8001-4478e0e4bf6c.png)
- You can use gitlab and push your project to the repo. After that, copy latest version to old version and merge it.

Thanks
