### ISSUE TITLE
[ Fluxstore MV 1.7.5 ] - Categories & Store Page is empty

### ISSUE THREAD

**Issue by zubaerabdullah** [inspireui/support#3998]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
+ Product & version: Fluxstore MV 1.7.5
+ Flutter (or React Native) version:  1.1.4
+ Testing Device/Simulator:  IPhone 11 Pro Max
+ Screenshot issues (drag the file to attach here): 

https://drive.google.com/file/d/1Ga0FYFNwuEy3n0BXbGnv4XqA-PWEzmzZ/view?usp=sharing

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by zubaerabdullah** [comment]
i am using WCFM and please fix this issue quickly.

**Comment by minhtruong315** [comment]
Can you fork from our git repo then invite me: minhtruong315@gmail.com?
 https://medium.com/@inspireui/how-to-upgrade-fluxstore-projects-by-using-git-cebde7489ea6 
I will help you check your issues. Ping me when you shared.
 Thanks

**Comment by zubaerabdullah** [comment]
i have latest version 1.7.5, Please provide a solution for this

**Comment by zubaerabdullah** [comment]
i need serious help i am stuck in the middle and i have very limited time to upload it to stores.

**Comment by minhtruong315** [comment]
@zubaerabdullah pls send me common folder.

**Comment by zubaerabdullah** [comment]
i have already attached with the support verification

**Comment by minhtruong315** [comment]
Hi @zubaerabdullah try to replace fromWCFMJson function in lib/vendor/store/store_model.dart like this
```
Store.fromWCFMJson(Map<String, dynamic> parsedJson) {
    id = int.parse("${parsedJson["vendor_id"]}");
    name = parsedJson["vendor_shop_name"];
    email = parsedJson["vendor_email"];
    rating = 0.0;
    if(parsedJson["settings"] != null && parsedJson["settings"] is Map){
      image = parsedJson["settings"]["gravatar"].toString().isNotEmpty
        ? parsedJson["settings"]["gravatar"]
        : null;
        banner = parsedJson["settings"]["mobile_banner"] != null
          ? ((parsedJson["settings"]["mobile_banner"] is String)
              ? parsedJson["settings"]["mobile_banner"]
              : image)
          : (parsedJson["settings"]["banner"] != null
              ? (parsedJson["settings"]["banner"] is String
                  ? parsedJson["settings"]["banner"]
                  : image)
              : image);
        phone = parsedJson["settings"]["phone"];
    }
    address = parsedJson["vendor_address"];
  }
```

**Comment by minhtruong315** [comment]
Hi @zubaerabdullah how?

**Comment by zubaerabdullah** [comment]
haven't test this fix yet.

**Comment by minhtruong315** [comment]
pls test and let me know. thanks

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
