### ISSUE TITLE
app data loading 

### ISSUE THREAD

**Issue by Alqumairi** [inspireui/support#3999]
the app is not loading the data from my site 

1- After i installed the app, it was not loading from inspire site i though maybe i need to link to my site. but its still not working. 
please do help
2- Fluxstore version 1.7.5
3- Flutter version 1.17.4
4- Testing Device simulator Pixel XL API 29
![app](https://user-images.githubusercontent.com/37410069/86211450-0373a880-bba9-11ea-95b4-cd3427365882.png)

**Comment by Alqumairi** [comment]
Hello

**Comment by minhcasi** [comment]
@Alqumairi - would you mind to follow this guide to setup some require plugin and API to connect with your site - https://docs.inspireui.com/fluxstore/woocommerce-setup/ -

you could also use the Fluxbuilder to support for customization and validate the setting - http://fluxbuilder.com/

**Comment by Alqumairi** [comment]
Yes i did follow those instructions. im not new to the inspireui products. After i followed all the instructions , the app still not loading. even when i link it to your site

**Comment by minhcasi** [comment]
@Alqumairi - first pls make sure your Rest API is working fine by following the document guide or using Fluxbuilder to check it - otherwise, the app could not load the product - thank you!
