### ISSUE TITLE
[MStore Pro] User information not pre-populating when signing in for 1st time. [Fix Included]

### ISSUE THREAD

**Issue by levi-beers** [inspireui/support#400]
If you have a WooCommerce account with name, address, phone, etc and sign into the app, the Cart -> Delivery form is blank. While MStore successfully gets the address information from the WooAPI, the "@containers/Cart/Delivery" has rendered with "null" for all state data. 

To resolve, you can change componentWillReceiveProps in containers/Cart/Delivery/index.js as follows

`  componentWillReceiveProps(nextProps) {
    if (nextProps.user != this.props.user) {
      this.fetchCustomer(nextProps);
      const customerAccess = nextProps.user.user;
      this.state = {
        value: {
          first_name: customerAccess.first_name,
          last_name: customerAccess.last_name,
          address_1: customerAccess.billing.address_1,
          state: customerAccess.billing.state,
          postcode: customerAccess.billing.postcode,
          country: customerAccess.billing.country,
          email: customerAccess.email,
          city: customerAccess.billing.city,
          phone: customerAccess.billing.phone,
          note: "",
        },
        cca2: "EN",
      };
      this.initFormValues();
    }
  }`

This way, when the user logs in and the props to the Cart/Delivery container are changed, the state values will be updated to include the users information. 

<img width="994" alt="Screen Shot 2019-03-14 at 11 21 21 AM" src="https://user-images.githubusercontent.com/16378407/54370416-f5b1b100-464d-11e9-9b4d-b7d4b7b532ab.png">

**Comment by luyx2412** [comment]
HI @levi-beers Thanks for your sharing. I noted improving the issue in next version.

**Comment by luyx2412** [comment]
Noted for next version!
