### ISSUE TITLE
Fluxstore Pro - integrate with Magento 2 , SMS Login issues

### ISSUE THREAD

**Issue by alan9501** [inspireui/support#4002]
+ Detail Issues: 
I just download the fluxstore pro, firebase is point to default fluxstore project, only changes i made is magento config.

Issues:
1. After login with sms, it auto assign an email for user, I believe it created a fake email account for user to login into Magento, is it a best way to do? and some more I never get the password, how do i login to same account in web?

2. Every time i reload the APP, i have to relogin (currently only test on simulator)

3. After i login with sms, my order history always empty, no matter how many order i made, but the order is visible in admin portal.

4. Update profile doesn't work, get error "Exception: Request does not match any route"

5. May i know the actual logic on SMS authentication? 

+ Product & version:
Fluxstore Pro
Magento 2.3.5

+ Flutter (or React Native) version: 
Flutter 1.17.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 1ad9baa8b9 (2 weeks ago) • 2020-06-17 14:41:16 -0700
Engine • revision ee76268252
Tools • Dart 2.8.4

+ Testing Device/Simulator: 
Simulator
+ Screenshot issues (drag the file to attach here): 
**_Step 1 (require): describe detail issues & screenshots_**
<img src="https://user-images.githubusercontent.com/58323345/86223527-3a9e8580-bbba-11ea-9f72-3b4cdecb1037.png" width="250">
<img src="https://user-images.githubusercontent.com/58323345/86226266-fdd48d80-bbbd-11ea-812f-66aab75d2637.png" width="250">
<img src="https://user-images.githubusercontent.com/58323345/86224036-eb0c8980-bbba-11ea-99ab-0defc0c29fbd.png" width="250">
<img src="https://user-images.githubusercontent.com/58323345/86224041-ecd64d00-bbba-11ea-9bd6-0abc82eb8db2.png" width="250">

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by ameenbadri7** [comment]
@alan9501 
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by alan9501** [comment]
> http://verify.inspireui.com/



> @alan9501
> Thank you for the feedback.
> 
> Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.
> 
> We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!
> 
> > **[Google Forms - create and analyze surveys, for free.](http://verify.inspireui.com/)**Create a new survey on your own or with others at the same time. Choose from a variety of survey types and analyze results in Google Forms. Free from Google.

Hi 
I had submit the google form. please do help me

thanks

**Comment by minhtruong315** [comment]
Hi @alan9501 for sms login, it auto creates a fake account with random password. it's better to implement sms login in app without change database structure. I don't know the password for sms login to login in web.

**Comment by minhtruong315** [comment]
2. Every time i reload the APP, i have to relogin
What login type you're using? email vs password, facebook, sms or google?

**Comment by minhtruong315** [comment]
3. After i login with sms, my order history always empty, no matter how many order i made, but the order is visible in admin portal.
Did you place an order after login sms in app?

**Comment by alan9501** [comment]
> 1. After i login with sms, my order history always empty, no matter how many order i made, but the order is visible in admin portal.
>    Did you place an order after login sms in app?
Yes, I am

> 1. Every time i reload the APP, i have to relogin
>    What login type you're using? email vs password, facebook, sms or google?
SMS

**Comment by minhtruong315** [comment]
4. I sent you the latest MStore extension via your email. please check

**Comment by alan9501** [comment]
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-07-02 at 11 59 14](https://user-images.githubusercontent.com/58323345/86314932-7dfd0080-bc5b-11ea-8886-a9e36a33664c.png)

I had tried the latest Mstore, i get another error

**Comment by minhtruong315** [comment]
@alan9501 can u try to input current password when update email.
Note: Fluxstore only supports to update email and change password now. it doesn't support to change others: name, username, url...

**Comment by alan9501** [comment]
> @alan9501 can u try to input current password when update email.
> Note: Fluxstore only supports to update email and change password now. it doesn't support to change others: name, username, url...

Hi,
the email field is not editable, 
again i never know my password, and you also mention, it was a random password, how i suppose to know

**Comment by minhtruong315** [comment]
Hi @alan9501 you're updating for social login. social login can't update anything now. I will update our source code. it will not show update profile for social login

**Comment by alan9501** [comment]
> Hi @alan9501 you're updating for social login. social login can't update anything now. I will update our source code. it will not show update profile for social login

How about the order history empty issues

**Comment by minhtruong315** [comment]
@alan9501 I'm checking and let you know today.
Thanks

**Comment by alan9501** [comment]
Another issue:
The delivery rate calculated based on accumulated number of items but now actual current item in cart.

As we can see there are 9 items in the cart.

<img width="350" alt="Screenshot 2020-07-07 at 4 40 07 PM" src="https://user-images.githubusercontent.com/58323345/86751457-40d8aa00-c071-11ea-9ad8-809b9cc93d6a.png">

Delivery rates was 4 dollar per item

<img width="702" alt="Screenshot 2020-07-07 at 4 40 07 PM" src="https://user-images.githubusercontent.com/58323345/86751436-3cac8c80-c071-11ea-82c1-7f3f8dac35ef.png">

The changes suppose to be 36 dollar, but what we get 224 dollar

<img width="350" alt="Screenshot 2020-07-07 at 4 40 07 PM" src="https://user-images.githubusercontent.com/58323345/86751453-3fa77d00-c071-11ea-828e-b5321330d3fa.png">

After i found from console, It show the quantity are 56, but it suppose to be 9.

<img width="702" alt="Screenshot 2020-07-07 at 4 40 07 PM" src="https://user-images.githubusercontent.com/58323345/86751449-3f0ee680-c071-11ea-944a-d9e4f0face6b.png">

What should i do to make it correct?

**Comment by minhtruong315** [comment]
I will check it. thanks

**Comment by minhtruong315** [comment]
```
"type": "magento",
  "url": "http://192.168.64.6/htdocsbak",
```
please upload your website to host and send me the config

**Comment by alan9501** [comment]
I tried to host my magento,
I realise another bug from Mstore extension, when i run command bin/magento-cli setup:di:compile , 
i get error Class Hyperpay\Extension\Model\Adapter does not exist , 
Class Mstore\PaymentResolver\Controller\Resolver\Hyperpay\Status\Interceptor gene  
  ration error: The requested class did not generate properly, because the 'generat  
  ed' directory permission is read-only. If --- after running the 'bin/magento setu  
  p:di:compile' CLI command when the 'generated' directory permission is set to wri  
  te --- the requested class did not generate properly, then you must add the gener  
  ated class object to the signature of the related construct method, only.


In the Mstore extension, requires Hyperpay extension which I don't have..

**Comment by minhtruong315** [comment]
I removed PaymentResolver and resend you MStore extension. pls reinstall again
