### ISSUE TITLE
fluxnews home layout (column, vertical) max item just show 10

### ISSUE THREAD

**Issue by HoWonJang** [inspireui/support#4006]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊
![pic1](https://user-images.githubusercontent.com/49952957/86247700-d09cd500-bbe7-11ea-91e6-593756b1244b.PNG)

[config.zip](https://github.com/inspireui/support/files/4858058/config.zip)

![12](https://user-images.githubusercontent.com/49952957/86247587-a3e8bd80-bbe7-11ea-9c86-f52dd9c88dcc.PNG)
![434](https://user-images.githubusercontent.com/49952957/86247591-a5b28100-bbe7-11ea-84e3-6142c2ad9dc0.PNG)

Only up to 10 items appear on the horizontal layout home screen. and vertical layout
I want to show all the items in the horizontal layout.
Which part of the file should I modify? Please let me know in detail.
thank you

**Comment by HoWonJang** [comment]
Also, when i click the 'See All' button on the home screen, only 10 items appear.

I want to solve the problem as soon as possible. Please let me know where to add or modify some code.

'Please wait for the next update.' I don't want to hear comments like .

thank you

**Comment by vumanhsn97** [comment]
@HoWonJang 
Update files
In lib/common/constants.dart: 
[constants.dart.zip](https://github.com/inspireui/support/files/4861948/constants.dart.zip)
In lib/services/wordpress.dart: 
[wordpress.dart.zip](https://github.com/inspireui/support/files/4861950/wordpress.dart.zip)

To update size list product on the horizontal. You can set ApiSizePage in constants.dart https://tppr.me/Yz9o4

**Comment by HoWonJang** [comment]
Thank you for your reply. but I want to show about 500 items on the home screen later. So I set apisize to 500, but I can't see all the items as shown in the picture.
![KakaoTalk_Photo_20200702_1347_07909](https://user-images.githubusercontent.com/49952957/86317542-9c1e2d00-bc6a-11ea-95fe-ee2539a57b71.jpg)

When setting the api size to 30, all outputs well. What is the maximum size? How can I bring about 500 sizes?

And is there a reason for limiting the number to 10? There's no problem with the speed when you bring in a lot of sizes, right?

thank you

**Comment by HoWonJang** [comment]
And as you can see in the video, the demo version app is loaded when scrolling, so why is it done without scrolling and loading in my app? How can I solve it? When I scroll, I want to bring items by loading them.
[KakaoTalk_Video_20200702_1357_02786.zip](https://github.com/inspireui/support/files/4862049/KakaoTalk_Video_20200702_1357_02786.zip)

**Comment by vumanhsn97** [comment]
maximun size is 100. Please don't set limit of page size number greater than 20 item. Because it will be affect to performance. May be your app will crash
In vertical loading: Make sure you download latest code. You can see in this video. 
[Screen Recording 2020-07-02 at 12.35.52.mov.zip](https://github.com/inspireui/support/files/4862188/Screen.Recording.2020-07-02.at.12.35.52.mov.zip)

**Comment by HoWonJang** [comment]
Thank you for your answer. Lastly, autoplay of banner image does not work. I would appreciate it if you could tell me which code I should insert.

**Comment by vumanhsn97** [comment]
@HoWonJang 
Change code in lib/widgets/blog/banner/banner_slider_items.dart to 
[banner_slider_items.dart.zip](https://github.com/inspireui/support/files/4863045/banner_slider_items.dart.zip)
And add this line in your config.json: https://tppr.me/QKTGl

**Comment by HoWonJang** [comment]
Thank you for your answer. It's been resolved.
Can I apply for verticallayouts instead of verticallayout?
Can i print out each category on the screen like HorizonLayout? Can I print out the 'seeall' button as well?

**Comment by vumanhsn97** [comment]
Yeah! But VerticalLayout item need to fixed length(10-20 item). It can't load more and you need to customize it. We don't support it.
Thanks!

**Comment by HoWonJang** [comment]
Thank you for your reply. It worked out well thanks to you.
