### ISSUE TITLE
FluxStore-listing 1.4.2 .bugs

### ISSUE THREAD

**Issue by tariq-alskran** [inspireui/support#4008]
![Capture](https://user-images.githubusercontent.com/45825752/86253616-72f39300-bbbd-11ea-95db-4ee85b3cd55b.PNG)

FluxStore-listing 1.4.2 .bugs
There are some problems that occurred when moving 
from  demo Url :  http://listeo.inspireui.comto  our live Url  :  https://tooredoo.net

 1_ Some of the steps we've taken
We have taken the step mentioned in "FluxStore-listing" documentation to  change demo url to live url in "config" File         
 
We have changed endpoint  like "listing" to  "job_listing" to get our listings  
2_ The problems appeared
     error in parse json object         
_ error from android studio in parse category json object

**Comment by ameenbadri7** [comment]
@tariq-alskran 
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 
Thank you for your time!

**Comment by tariq-alskran** [comment]
@ameenbadri7 
I filled out the form and sent you a config file and some notes about problem .
Await your reply !

**Comment by philipvu30** [comment]
Hi,

In your config.dart file, please replace:

```
const kProductPath = 'listing'; 
to
const kProductPath = 'job_listing';

const kTaxonomies = {
  'category': 'listing_category',
  'region': 'region',
  'features': 'listing_feature'
};
to
const kTaxonomies = {
  'category': 'job_listing_category',
  'region': 'region',
  'features': 'listing_feature'
};
```

**Comment by tariq-alskran** [comment]
@philipvu30 
We have made these changes but the error still exists?
![86253616-72f39300-bbbd-11ea-95db-4ee85b3cd55b](https://user-images.githubusercontent.com/45825752/86467131-83cb1280-bd3d-11ea-8ce0-3b0205b106aa.png)

**Comment by tariq-alskran** [comment]
@ameenbadri7 
My friend.
 Please respond to my problem,
 I keep my promises with clients, and this wasted time delays work on 
 projects,
 This is not a professional way of working by your team.
Please respond as quickly

**Comment by minhcasi** [comment]
@vumanhsn97 - pls help to investigate the above issue

**Comment by vumanhsn97** [comment]
@tariq-alskran 
Replace file:
- lib/common/config.dart to 
[config.dart.zip](https://github.com/inspireui/support/files/4882199/config.dart.zip)
- lib/models/blog.dart to 
[blog.dart.zip](https://github.com/inspireui/support/files/4882200/blog.dart.zip)

**Comment by tariq-alskran** [comment]
In Tools - Rest Api Controller - Job Listing Category

When i enable all job listing category and click save it doesn't save and it displays ERROR 500 - INTERNAL SERVER ERROR.

![internelservererror](https://user-images.githubusercontent.com/45825752/86825157-b7889e00-c097-11ea-9d82-9b724e156134.PNG)
![job listing](https://user-images.githubusercontent.com/45825752/86825175-bbb4bb80-c097-11ea-96fc-736b6b038068.PNG)

**Comment by vumanhsn97** [comment]
@tariq-alskran 
Try with this solution: https://www.elegantthemes.com/blog/tips-tricks/how-to-fix-the-500-internal-server-error-on-your-wordpress-website#:~:text=The%20two%20most%20common%20causes,change%20to%20your%20WordPress%20site.
