### ISSUE TITLE
How to set Home Screen Categories icon dynamic form OpenCart "FluxStore Pro"

### ISSUE THREAD

**Issue by Hadramy116** [inspireui/support#4009]
I want the icons and categories on the main screen to be editable at any time after the app publication on stores. 
if there is an option to do that directly form OpenCart.

![1CatIcon](https://user-images.githubusercontent.com/24548708/86257739-7d0b9680-bba9-11ea-8a9a-0c6dddb5817b.PNG)

![2catHom](https://user-images.githubusercontent.com/24548708/86257784-8bf24900-bba9-11ea-8a4c-58f925b2916b.PNG)

Product & version: FluxStore 1.7.5
Flutter version : 
Flutter 1.17.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 1ad9baa8b9 (2 weeks ago) • 2020-06-17 14:41:16 -0700
Engine • revision ee76268252
Tools • Dart 2.8.4

**Comment by ameenbadri7** [comment]
@Hadramy116 


Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ 
- please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 
Thank you for your time!

**Comment by minhcasi** [comment]
@Hadramy116 - this feature is available from the Fluxbuilder app - pls give a try to install the builder, the current release of fluxbuilder allow your export the json config then you could use this config to upload via mstore-api to enable the cache, and not required to re-build the app.

We are also working on new version to upload the config just one-click on the next release - thank you!

**Comment by minhcasi** [comment]
<img width="946" alt="Screen Shot 2020-07-02 at 09 09 11" src="https://user-images.githubusercontent.com/1459805/86308526-b395ef80-bc43-11ea-93f5-e3f9b6734a3f.png">

In the meantime, you could try to change this config and upload to your own Cloud (instead of using local asset file from the app)

**Comment by Hadramy116** [comment]
Can i upload config via mstore-api in OpenCart?

**Comment by Hadramy116** [comment]
`In the meantime, you could try to change this config and upload to your own Cloud (instead of using local asset file from the app)`

thank you for this solution very helpful but can I do that for other files like config_fr.json, config_ar.json

**Comment by minhcasi** [comment]
other file does not support, It could only use for the default one. I will think about new solution

**Comment by minhcasi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Feature: support multi language config](https://trello.com/c/eLJQaYFl/61-feature-support-multi-language-config)

**Comment by minhcasi** [comment]
moved to backlog for further improvement
