### ISSUE TITLE
[BeoNews Pro] Categories Ajax loader bug

### ISSUE THREAD

**Issue by aleksandar-radivojevic** [inspireui/support#401]
**Required Info (please complete the following information):**
 - Product: [BeoNews Pro]

**Describe the bug**
Look at video, really strange behavior. I'm using Huawei Y6, Android 8.0.0

**Video evidence**

https://drive.google.com/file/d/13X1BsrBi7JE4mB20fY4ikIDVRZ_3amBY/view?usp=sharing

**Comment by minhcasi** [comment]
hi, do you mean the Post list is not updated when select category?

**Comment by aleksandar-radivojevic** [comment]
Well I believe that it is updating post but the process is just painful and slow.

Sent from Mail for Windows 10

**Comment by minhcasi** [comment]
Dear @aleksandar-radivojevic please help try on iOS or other Android device with latest BeoNews version, the performance is working fine with our testing, thank you!
