### ISSUE TITLE
How to add custom font in mstore-4.0.0 pro?

### ISSUE THREAD

**Issue by enoncie** [inspireui/support#4011]
I want to use my own font. Pls advise.

**Comment by ameenbadri7** [comment]
@enoncie 

Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by enoncie** [comment]
I did. But I can't find the config folder. My package is MStore React Native for Woocommerce. Where is it located?

**Comment by luyx2412** [comment]
Hi @enoncie Please read the article to add custom font in your project https://medium.com/better-programming/using-custom-fonts-in-react-native-2019-289099609837

Thanks

**Comment by enoncie** [comment]
Thanks. I will check it out today. :-)
