### ISSUE TITLE
last products doesn't show in app

### ISSUE THREAD

**Issue by alolahussein** [inspireui/support#4012]
hello, when I add new products it's doesn't show in-app and then refresh the page doesn't show anything,
in logs screen when running app I put the link in postman and get last products but in-app nothing to show

**Comment by ameenbadri7** [comment]
hello, @alolahussein Wellcome back.

could you specify what is your product and the version?
and what is the backend of your app (Woocommerce - Opencart .... )

**Comment by alolahussein** [comment]
fluxstore v 1.6.5c woocommerce

**Comment by alolahussein** [comment]
and how can update my own code to the last version of fluxstore

**Comment by alolahussein** [comment]
these issues show after update mstore API plugin before that app works fine

**Comment by minhtruong315** [comment]
Hi @alolahussein The latest version is 1.7.5. You're using old version. please update the latest version and check again.
https://codecanyon.net/item/fluxstore-woocommerce-flutter-ecommerce-full-app/24050041
Thanks
