### ISSUE TITLE
welcome screen & splashscreen

### ISSUE THREAD

**Issue by miskayapp** [inspireui/support#4013]
1. my splash screen takes close to 30aecs to boot when the app is closed and reopened
2. I don't want to use images on my welcomes screens and i don't like the white spaces in between, how do i close that.
![WhatsApp Image 2020-07-01 at 21 17 56 (1)](https://user-images.githubusercontent.com/64660378/86287783-bd3a3b80-bbe0-11ea-9ca8-ea961fc96c4c.jpeg)
![WhatsApp Image 2020-07-01 at 21 17 56](https://user-images.githubusercontent.com/64660378/86287786-bdd2d200-bbe0-11ea-9de9-5cb5f164b7c6.jpeg)
![WhatsApp Image 2020-07-01 at 21 17 57](https://user-images.githubusercontent.com/64660378/86287787-be6b6880-bbe0-11ea-9b3b-8890ff5e2390.jpeg)

**Comment by ameenbadri7** [comment]
hello, @miskayapp Wellcome back.
welcomes screens and splash screen are the easiest to config in fluxstore
you can just see our [documentation ](https://docs.inspireui.com/fluxstore/customization)to fix your issue.

[splash screen](https://docs.inspireui.com/fluxstore/customization/#2-logo-splash-screen)
[Onboarding](https://docs.inspireui.com/fluxstore/customization/#7-onboarding-and-login-mode)
please use those as a guide for you to customize fluxstore the way you want.
let us know if you still have any problems. 
thank you for your time.

**Comment by miskayapp** [comment]
it says nothing about removing the picture or sizing that space. please direct or show me how to close that white space, its urgent please.

**Comment by miskayapp** [comment]
You didnt reply why the slash screen taking almost 30seconds on start up

**Comment by miskayapp** [comment]
How do i use deeplink, idk, i use one signal notification how do i direct customers to a certain part pf the app

**Comment by miskayapp** [comment]
I set isheroAnimate:true does that affect the welcome screen or app speed?

**Comment by miskayapp** [comment]
?????

**Comment by miskayapp** [comment]
"OnBoarding": {
    "data": [
      {
        "title": "Welcome to FluxStore",
        "image": "assets/images/fogg-delivery-1.png",
        "desc": "Fluxstore is on the way to serve you. ",
        "background": "#FFF3F2"
      },
      {
        "title": "Connect Surrounding World",
        "image": "assets/images/fogg-uploading-1.png",
        "desc": "See all things happening around you just by a click in your phone. Fast, convenient and clean.",
        "background": "#F2FFFC"
      },
      {
        "title": "Let's Get Started",
        "image": "fogg-order-completed.png",
        "desc": "Waiting no more, let's see what we get!",
        "background": "#F9F2FF"
      }
    ]
  

this doesn't say anything about removing the white space

**Comment by ameenbadri7** [comment]
we don't take customization requests for the regular license but you can buy the Extended License or Support Pack and email us with your request via our email minhcasi@gmail.com and inspireui-team@inspireui.com.

**Comment by miskayapp** [comment]
SO HOW DO I GET SUPPORT PACK?

**Comment by miskayapp** [comment]
Unavailable sizes are showing up and when the user clicks add to cart, it automatically changes to the available ones in their cart.
![CDD14D2E-276D-457F-BF48-8E924B12D31C](https://user-images.githubusercontent.com/64660378/86522726-3e503780-be5a-11ea-9b35-5f076b93feca.jpeg)

**Comment by miskayapp** [comment]
Hello ooo, can you please replyyy

**Comment by minhcasi** [comment]
@miskayapp - the question is not quite clear to that we could answer your question, could you help to provide the quick video screenshot ?

We have tested the variant again it is working fine

**Comment by miskayapp** [comment]
The product is showing sizes that are soldout, but when the use click add to cart it automatically switch to the only available size, the picture above only size 10 is available but other sizes are selectable

**Comment by miskayapp** [comment]
![17B9CFBB-C212-411C-BDC1-C896750733F7](https://user-images.githubusercontent.com/64660378/86730993-fd594e00-c026-11ea-90ee-930cfde735a6.jpeg)

How can i add a webview page to that hamburger menu or switch the blog to open a different url

**Comment by ameenbadri7** [comment]
pls help to check our [support policies ](https://inspireui.com/support-policies)
we don't take customization requests for the regular license but you can buy the [Extended License](https://inspireui.com/support-policies) or Support Pack and email us with your request via our email minhcasi@gmail.com and inspireui-team@inspireui.com.

thank you.

**Comment by miskayapp** [comment]
![C886C4B5-1EC4-4844-AA19-FF285982A609](https://user-images.githubusercontent.com/64660378/87182858-e0e63b80-c2dc-11ea-8758-9f56329c85b1.png)
![396E6E12-FEA1-48BF-A132-228B7B53815D](https://user-images.githubusercontent.com/64660378/87182870-e5aaef80-c2dc-11ea-846d-e245741b74fd.png)
I picked size 10 but it switched to size 6 in cart, thats becaue size 10 is no longer available, but why is it still showing?

@minhcasi @ameenbadri7
