### ISSUE TITLE
[Fluxstore 1.7.5] Need Help with Product Card and List Layout

### ISSUE THREAD

**Issue by kobylogan** [inspireui/support#4014]
I had an issue in which product images were not displaying in app. I found out that the app was trying to download files with name format, '$pathWithoutExt-medium$ext'; which were not present in my media folder because for some reason, after regeneration, they were not generated. I therefore changed statement in tools.dart to '$pathWithoutExt-300x300$ext';. This is allowed 300 x 300 images in my media folder to display in app. This has left a big gap (white space) between product card view and tile view. (see screenshots). I have not been able to figure out how to remove them. Kindly help me with that. 
![1](https://user-images.githubusercontent.com/43590567/86304126-70b12900-bbfd-11ea-9746-1c354ad6f06e.JPG)
![2](https://user-images.githubusercontent.com/43590567/86304133-760e7380-bbfd-11ea-9b46-a409de907936.JPG)

**Testing Device** : Emulator - Genymotion

**Other Questions**
1. Which part of the app(on which device size) uses the '**$pathWithoutExt-small$ext'** and **'$pathWithoutExt-large$ext'** images.

![image](https://user-images.githubusercontent.com/43590567/86304785-73ad1900-bbff-11ea-81d5-c22b37dcd5ed.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by kobylogan** [comment]
Hello, No response yet?

**Comment by minhcasi** [comment]
@kobylogan - we have fixed this minor UI issue and will update in 1-2 days - thank you for reporting

**Comment by minhcasi** [comment]
Fixed on the latest `1.7.6`, let us know if you have any issues - thank you!
