### ISSUE TITLE
product image not aligned 

### ISSUE THREAD

**Issue by rihtak2020** [inspireui/support#4016]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 

my product images are not aligned. can you please check and help me out ? i have already regenerated my images 

+ Product & version: 1.7.5
+ Flutter (or React Native) version: flutter
![WhatsApp Image 2020-07-02 at 10 07 17 AM](https://user-images.githubusercontent.com/65780159/86316994-ea700380-bc4b-11ea-9fb6-5f64b774d715.jpeg)

+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

already verified 

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
Hi, you could try to fix the product image height by using this code 

<img width="974" alt="Screen Shot 2020-07-02 at 17 29 15" src="https://user-images.githubusercontent.com/1459805/86348220-8f5d0180-bc89-11ea-8f35-55a96f062365.png">


```
Widget getImageFeature
(onTapProduct) {
    double _maxWidth = maxWidth ?? width;
    double _height = math.min(_maxWidth * 1.2, height ?? width * 1.2);

    return GestureDetector(
      onTap: onTapProduct,
      child: Tools.image(
        url: item.imageFeature,
        width: width,
        size: kSize.medium,
        isResize: true,
        height: _height,
        fit: BoxFit.cover,
        offset: offset ?? 0.0,
      ),
    );
  }
```
