### ISSUE TITLE
sorry you cannot list resources

### ISSUE THREAD

**Issue by wolverineee92** [inspireui/support#4018]
**_Step 1 (require): describe detail issues & screenshots_**

sorry you cannot list resources in this error coming on my app.

Mstore pro latest version 

React native latest version

Simulator

![01](https://user-images.githubusercontent.com/67648501/86317175-69fdd280-bc4c-11ea-9386-dacd1412c1e7.png)

**Comment by wolverineee92** [comment]
Need urgently...i was submitted the form already

**Comment by minhcasi** [comment]
@wolverineee92 - could you confirm if you have enabled the Rest API successful - https://docs.woocommerce.com/document/woocommerce-rest-api/ - thank you!

**Comment by wolverineee92** [comment]
Yes,  I am already installed

**Comment by luyx2412** [comment]
Hi @wolverineee92 Please follow the document to install the plugin and app https://docs.inspireui.com/mstore/getting-started/

Thanks

**Comment by wolverineee92** [comment]
Hello..i was all setup is perfectly integrare the app...

**Comment by wolverineee92** [comment]
I building the lot of app from mstore...but I have error on this website only...please tell me proper solution

**Comment by luyx2412** [comment]
Hi @wolverineee92 Please invite me to the wordpress website inspireui.team@gmail.com to investigate easier.

Thanks

**Comment by wolverineee92** [comment]
Okay wait...I will send you

**Comment by wolverineee92** [comment]
please check your inbox...i sending the invitation

**Comment by wolverineee92** [comment]
You got it the access?

**Comment by wolverineee92** [comment]
please response...if you no means i will create another one.

**Comment by luyx2412** [comment]
Hi @wolverineee92 Can i edit your plugin or test your website?

Thanks

**Comment by wolverineee92** [comment]
yes, please resolved my API issue..i need urgently now

**Comment by wolverineee92** [comment]
Any Update?

**Comment by wolverineee92** [comment]
hide 'out of stock' in site but showing the app #4027

**Comment by luyx2412** [comment]
Hi @wolverineee92 Please hide this option in your code without setup on the website. You can edit it in `src/containers/Detail/index.js` line 595 
![image](https://user-images.githubusercontent.com/8909619/86475428-d96be300-bd6e-11ea-8422-8d96bdd89299.png)

Thanks

**Comment by wolverineee92** [comment]
Okay....what about the this issue

sorry you cannot list resources #4018

**Comment by wolverineee92** [comment]
I am already invite the your mail on my website...it's very important....please resolved

**Comment by luyx2412** [comment]
Hi @wolverineee92 I saw your product in the screenshot, so you setup another websites?

Thanks

**Comment by wolverineee92** [comment]
> Hi @wolverineee92 Please hide this option in your code without setup on the website. You can edit it in `src/containers/Detail/index.js` line 595
> ![image](https://user-images.githubusercontent.com/8909619/86475428-d96be300-bd6e-11ea-8422-8d96bdd89299.png)
> 
> Thanks

this is hide the all button text...its not solution...i want to not display in out of stock product item in my app..

**Comment by wolverineee92** [comment]
> Hi @wolverineee92 I saw your product in the screenshot, so you setup another websites?
> 
> Thanks

Yes...i will invite the https://www.kf94central.com/....this website is problem ( 
sorry you cannot list resources
#4018 )

**Comment by wolverineee92** [comment]
If you want site credential? i will send it?

**Comment by wolverineee92** [comment]
I want to remove the date from home page...please help

**Comment by wolverineee92** [comment]
Yes...i will invite the https://www.kf94central.com this website is problem (
sorry you cannot list resources
#4018 )

please very urgently

**Comment by wolverineee92** [comment]
![upload](https://user-images.githubusercontent.com/67648501/86486093-0a9ce100-bd78-11ea-8f00-e95830f97390.png)

I need any solution

**Comment by wolverineee92** [comment]
> Yes...i will invite the https://www.kf94central.com this website is problem (
> sorry you cannot list resources
> #4018 )
> 
> please very urgently
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/2d4e0733d6136ef20e0c66d730837f6f89715398/68747470733a2f2f7777772e6b66393463656e7472616c2e636f6d2f77702d636f6e74656e742f75706c6f6164732f323032302f30352f4131636c65616e636172652e6a7067"><img alt="" height="14" src="https://camo.githubusercontent.com/55fa5f38c20f5ede509f4880af68d903fe8c838d/68747470733a2f2f7777772e6b66393463656e7472616c2e636f6d2f77702d636f6e74656e742f75706c6f6164732f323032302f30352f63726f707065642d66617669636f6e322d313932783139322e706e67"> KF94 Central**[Home | KF94 Central](https://www.kf94central.com/)**Add to cart Air Queen 10 Pieces KF94 Face Mask help to Guard against harmful virus and bacteria influenza Made in Korea $42.00$46.00 Air Queen 10 Pieces KF94 Face Mask help to Guard against harmful virus and bacteria influenza Made in Korea $42.00$46.00 Add to cart DR Puri 20 Pieces KF94 Face Mask Guard against…

Any update?

**Comment by luyx2412** [comment]
Hi @wolverineee92 Sorry i researched about it, and your issue related the config ssl. Currently it always redirect from http to https. Please read the article about it https://wordpress.stackexchange.com/questions/334967/error-message-sorry-you-cannot-list-resources-using-woocommerce-api
- You can edit it in `src/containers/Cart/index.js` line 159
![image](https://user-images.githubusercontent.com/8909619/86514415-2ec1f600-be3c-11ea-812c-0a2f21dcb3cd.png)

Thanks

**Comment by wolverineee92** [comment]
> this is hide the all button text...its not solution...i want to not display in out of stock product item in my app..

hello any update?

**Comment by luyx2412** [comment]
Hi @wolverineee92 Please upgrade api-ecommerce to latest version 0.36.0. And in `src/redux/LayoutRedux.js` line 101. Please add `stock_status : "instock"` same the screenshot. 
![image](https://user-images.githubusercontent.com/8909619/86515392-c3c7ed80-be42-11ea-837d-0e7cf6a069b2.png)
![image](https://user-images.githubusercontent.com/8909619/86515394-c4f91a80-be42-11ea-8ce2-d6ca308cd4b5.png)
https://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-products 

Thanks

**Comment by wolverineee92** [comment]
> Hi @wolverineee92 Sorry i researched about it, and your issue related the config ssl. Currently it always redirect from http to https. Please read the article about it https://wordpress.stackexchange.com/questions/334967/error-message-sorry-you-cannot-list-resources-using-woocommerce-api
> 
> * You can edit it in `src/containers/Cart/index.js` line 159
>   ![image](https://user-images.githubusercontent.com/8909619/86514415-2ec1f600-be3c-11ea-812c-0a2f21dcb3cd.png)
> 
> Thanks
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/5004d2933a5c91eaf25d622e0138da2781d5f09b/68747470733a2f2f63646e2e737374617469632e6e65742f53697465732f776f726470726573732f496d672f6170706c652d746f7563682d69636f6e40322e706e673f763d383564376632323432343430">WordPress Development Stack Exchange**["error_message": "Sorry, you cannot list resources." using WooCommerce API](https://wordpress.stackexchange.com/questions/334967/error-message-sorry-you-cannot-list-resources-using-woocommerce-api)**When requesting the test API, getting the following response:
> > {
> > "errors": [
> > {
> > "error_code": "",
> > "error_message": "Sorry, you cannot list resources."
> > }
> > ...

i am already try this all...still have a issue...please help

**Comment by wolverineee92** [comment]
> Hi @wolverineee92 Please upgrade api-ecommerce to latest version 0.36.0. And in `src/redux/LayoutRedux.js` line 101. Please add `stock_status : "instock"` same the screenshot.
> ![image](https://user-images.githubusercontent.com/8909619/86515392-c3c7ed80-be42-11ea-837d-0e7cf6a069b2.png)
> ![image](https://user-images.githubusercontent.com/8909619/86515394-c4f91a80-be42-11ea-8ce2-d6ca308cd4b5.png)
> https://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-products
> 
> Thanks
> 
> > **[WooCommerce REST API Documentation - WP REST API v3](https://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-products)**

![error](https://user-images.githubusercontent.com/67648501/86516926-6af85500-be42-11ea-8a5c-c264194f996c.png)

i have error on this code...

**Comment by luyx2412** [comment]
Hi @wolverineee92 Sorry my mistake, please follow the screenshot.
![image](https://user-images.githubusercontent.com/8909619/86525330-096ecf80-beb0-11ea-94da-5cb7e4f24bba.png)

Thanks

**Comment by wolverineee92** [comment]
> Hi @wolverineee92 Sorry my mistake, please follow the screenshot.
> ![image](https://user-images.githubusercontent.com/8909619/86525330-096ecf80-beb0-11ea-94da-5cb7e4f24bba.png)
> 
> Thanks

![Screenshot at Jul 05 11-22-04](https://user-images.githubusercontent.com/67648501/86526321-48048a00-beb0-11ea-8f5d-38dae6c82009.png)

But still out of stock product showing

**Comment by wolverineee92** [comment]
how to reuse the purchase code in another site?

**Comment by wolverineee92** [comment]
{"code":"woocommerce_rest_cannot_view","message":"Sorry, you cannot list resources.","data":{"status":401}}

please resolve this problem

**Comment by luyx2412** [comment]
Hi @wolverineee92 
- The first you only use one purchase code with one website if regular license.
- The issue related your config with woocommerce and wordpress, we did not handle it. So please use another hosting or reinstall website again.

Thanks

**Comment by wolverineee92** [comment]
> > Hi @wolverineee92 Sorry my mistake, please follow the screenshot.
> > ![image](https://user-images.githubusercontent.com/8909619/86525330-096ecf80-beb0-11ea-94da-5cb7e4f24bba.png)
> > Thanks
> 
> ![Screenshot at Jul 05 11-22-04](https://user-images.githubusercontent.com/67648501/86526321-48048a00-beb0-11ea-8f5d-38dae6c82009.png)
> 
> But still out of stock product showing

please response

**Comment by luyx2412** [comment]
Please upgrade api-ecommerce to latest version 0.0.36 https://www.npmjs.com/package/api-ecommerce/v/0.0.36 which will show right data.

Thanks

**Comment by wolverineee92** [comment]
> Please upgrade api-ecommerce to latest version 0.0.36 https://www.npmjs.com/package/api-ecommerce/v/0.0.36 which will show right data.
> 
> Thanks
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/c2b95098a1c75357906fc6e8647c87345dde79fd/68747470733a2f2f7374617469632e6e706d6a732e636f6d2f33333865343930356132363834636139366530386337373830666336383431322e706e67"><img alt="" height="14" src="https://camo.githubusercontent.com/dbe46d42a523ce8a202f6cee2a130787bdd6cdde/68747470733a2f2f7374617469632e6e706d6a732e636f6d2f64613361623430666230383631643135633833383534633239663566323936322e706e67"> npm**[api-ecommerce](https://www.npmjs.com/package/api-ecommerce)**api for ecommerce

How to upgrade? will change the any code?

**Comment by wolverineee92** [comment]
I dont want to 3 intro screen..i need the splash screen when i open the app..

**Comment by wolverineee92** [comment]
> > > Hi @wolverineee92 Sorry my mistake, please follow the screenshot.
> > > ![image](https://user-images.githubusercontent.com/8909619/86525330-096ecf80-beb0-11ea-94da-5cb7e4f24bba.png)
> > > Thanks
> > 
> > 
> > ![Screenshot at Jul 05 11-22-04](https://user-images.githubusercontent.com/67648501/86526321-48048a00-beb0-11ea-8f5d-38dae6c82009.png)
> > But still out of stock product showing
> 
> please response

Its only hide from homepage...but i want to dont visible in out of stock on full app...

**Comment by wolverineee92** [comment]
> {"code":"woocommerce_rest_cannot_view","message":"Sorry, you cannot list resources.","data":{"status":401}}
> 
> please resolve this problem



require "woocommerce_api"

woocommerce = WooCommerce::API.new(
  "https://example.com",
  "consumer_key",
  "consumer_secret",
  {
    wp_json: true,
    version: "wc/v1",
    query_string_auth: true
  }
)

how to add this line from code? ->  query_string_auth: true )

**Comment by wolverineee92** [comment]
> > > > Hi @wolverineee92 Sorry my mistake, please follow the screenshot.
> > > > ![image](https://user-images.githubusercontent.com/8909619/86525330-096ecf80-beb0-11ea-94da-5cb7e4f24bba.png)
> > > > Thanks
> > > 
> > > 
> > > ![Screenshot at Jul 05 11-22-04](https://user-images.githubusercontent.com/67648501/86526321-48048a00-beb0-11ea-8f5d-38dae6c82009.png)
> > > But still out of stock product showing
> > 
> > 
> > please response
> 
> Its only hide from homepage...but i want to dont visible in out of stock on full app...

Quick response please...its very urgent

**Comment by wolverineee92** [comment]
Not able to login...Only loading
screenshot -> https://prnt.sc/te26vv

**Comment by luyx2412** [comment]
Hi @wolverineee92 Please clear your issue, i dont know what website or config. And please just use one source code for one website.

Thanks

**Comment by wolverineee92** [comment]
> Hi @wolverineee92 Please clear your issue, i dont know what website or config. And please just use one source code for one website.
> 
> Thanks

Sorry, I will developed lot of app in different purchase code...not a same

**Comment by wolverineee92** [comment]
Now all app are same login issue...please help
I am using the mstore expo..
[common.zip](https://github.com/inspireui/support/files/4891434/common.zip)

**Comment by wolverineee92** [comment]
Problem was updated mstore expo....i will try to old source code..its working fine...so please resolve the new source code...

**Comment by wolverineee92** [comment]
Waiting for your response...very urgently

**Comment by wolverineee92** [comment]
> > > > Hi @wolverineee92 Sorry my mistake, please follow the screenshot.
> > > > ![image](https://user-images.githubusercontent.com/8909619/86525330-096ecf80-beb0-11ea-94da-5cb7e4f24bba.png)
> > > > Thanks
> > > 
> > > 
> > > ![Screenshot at Jul 05 11-22-04](https://user-images.githubusercontent.com/67648501/86526321-48048a00-beb0-11ea-8f5d-38dae6c82009.png)
> > > But still out of stock product showing
> > 
> > 
> > please response
> 
> Its only hide from homepage...but i want to dont visible in out of stock on full app...

I am waiting for you response..

**Comment by wolverineee92** [comment]
> Now all app are same login issue...please help
> I am using the mstore expo..
> [common.zip](https://github.com/inspireui/support/files/4891434/common.zip)

I am waiting for you response..

**Comment by wolverineee92** [comment]
> Problem was updated mstore expo....i will try to old source code..its working fine...so please resolve the new source code...

see this message

**Comment by wolverineee92** [comment]
if you not reply...i will create the new ticket

**Comment by minhcasi** [comment]
As you have built a lot of app from Mstore, could you check these apps are used with multi licenses purchase code?
<img width="982" alt="Screen Shot 2020-07-10 at 17 08 07" src="https://user-images.githubusercontent.com/1459805/87143233-f1dc8000-c2cf-11ea-8958-a4b4b40d804a.png">

Please make sure to activate the License for each website, otherwise, the API will not work

**Comment by wolverineee92** [comment]
> As you have built a lot of app from Mstore, could you check these apps are used with multi licenses purchase code?
> <img alt="Screen Shot 2020-07-10 at 17 08 07" width="982" src="https://user-images.githubusercontent.com/1459805/87143233-f1dc8000-c2cf-11ea-8958-a4b4b40d804a.png">
> 
> Please make sure to activate the License for each website, otherwise, the API will not work

hello...i know about the license...

**Comment by wolverineee92** [comment]
Problem was updated mstore expo4.0.0....i will try to old source code 3.9..its working fine...so please resolve the new source code...
all app are sign up working...problem is login function

**Comment by wolverineee92** [comment]
1) I want to not showing in out of stock on full app...
2) i need to disable apple and fb login...

please help

**Comment by minhcasi** [comment]
@wolverineee92 - pls note that you are using 1 license for multiple sites that is not meet with the Envato policies.
