### ISSUE TITLE
Few  Orders are not being captured on Woocommerce

### ISSUE THREAD

**Issue by amitiitd999** [inspireui/support#4019]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues:  Some orders which have been paid by the customers had not been captured on woocommerce.
+ Product & version: Fluxstore Pro 1.7.3
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): There is nothing to attache because order is not captured

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by amitiitd999** [comment]
I have submitted the proof of purchase through your website

**Comment by minhcasi** [comment]
@amitiitd999 - could you help to share the detail screenshot and test case on your site so that we could help for checking the issue - thank you!

**Comment by amitiitd999** [comment]
Unfortunately, i don't have any test case or screenshot because these orders are not captured at all. We can just see payment done by customer and their complaining email/phones. This issue is happeing with few orders only.

**Comment by minhcasi** [comment]
@amitiitd999 - is it possible to share the login admin so that we could check this special case ? - thank you!

**Comment by amitiitd999** [comment]
Which login admin do you need? Woocommerce?
Please do provide me an email ID on which I can share admin details.

**Comment by ameenbadri7** [comment]
thank you for your feedback.

our email minhcasi@gmail.com and inspireui-team@inspireui.com. 
you can make sure it's ours by looking to the main support [template ](https://github.com/inspireui/support).

thank you

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Comment by amitiitd999** [comment]
I have already sent admin details on your mail. Did not hear back from you guys from last few days.

**Comment by macquack** [comment]
i'm facing this problem too
