### ISSUE TITLE
MStore_user

### ISSUE THREAD

**Issue by rajendar123** [inspireui/support#402]
- Product: MStore

We have purchased MStore code from codecanyon. While trying to integrate our website with woocommerce plugin to the code, we are not able to sign in to the app. While trying to understand the code, we saw the endpoint to login as '{url}/api/mstore_user/generate_auth_cookie/?second=${cookieLifeTime}&username=${username}&password=${password}${secure}'.
We are not sure which plugin we have to install for this to work. Any suggestions please?

**Comment by levi-beers** [comment]
@rajendar123 You need to install the mstore-checkout plugin which you can find [here on Github](https://github.com/inspireui/mstore). Also, make sure to look over the [online documentation](https://docs.mstore.io/) for Mstore, it's very helpful. I'm not a developer on the project, but I've been working with InspireUI's products for some time, if I can be of any help I'd be more than willing.

**Comment by minhcasi** [comment]
@rajendar123 pleas double check the document guide from https://docs.mstore.io/basic-app-setting - thank you!
