### ISSUE TITLE
Home page pull to refresh doesn't work [Fluxnews]

### ISSUE THREAD

**Issue by manjok** [inspireui/support#4020]
![image](https://user-images.githubusercontent.com/2523772/86319903-21541280-bc68-11ea-919b-2fde3315baa9.png) Home page pull to refresh doesn't do anything. You can clearly see it at the code level too.

**Comment by minhcasi** [comment]
@manjok - kindly update our rating to continue getting support from us, if you look back the previous ticket we are willing to support your all tickets and also refund one case
