### ISSUE TITLE
Dropdown list for City Selection is not working 

### ISSUE THREAD

**Issue by andyodoo** [inspireui/support#4021]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
I would like to include a Dropdownlist for City selection & ZipCode Selection in the Checkout form (Introducing the shipping Address).

Regarding State Province you have included this solution so I have just copy and adapt the script.
However is not working, Could you tell me what is missing? This are the actions I have done for the city case:

I have created /cities/city_es.json file to call and list the Cities inside by country
Here you can find attached my city_es.json, tools.dart and shipping_address.dart files...
<img width="1400" alt="Screen Shot 2020-07-02 at 7 50 45 AM" src="https://user-images.githubusercontent.com/50452375/86317699-c22ad980-bc38-11ea-8299-5be321046bb2.png">
here the files that we edited to add the dropdown city 
[files edited.zip](https://github.com/inspireui/support/files/4862029/files.edited.zip)
also we added the city directory in pubspec.yaml
<img width="610" alt="Screen Shot 2020-07-02 at 7 54 32 AM" src="https://user-images.githubusercontent.com/50452375/86317916-48472000-bc39-11ea-8b43-625335d8e4f9.png">

but still the city dropdown is not showing 
<img width="415" alt="Screen Shot 2020-07-02 at 7 56 39 AM" src="https://user-images.githubusercontent.com/50452375/86318031-92c89c80-bc39-11ea-864a-5d8c20bdeec9.png">

we did the following :
Include the declaration of the new variable in lib/screens/checkout/shipping_address.dart: (line 43)
List cities = [];

Include this widget in lib/screens/checkout/shipping_address.dart: (Line: 574)
Widget renderCityInput() {
if (cities.isNotEmpty) {
List items = [];
cities.forEach((item) {
items.add(
DropdownMenuItem(
child: Text(item is Map ? item["name"] : item),
value: item is Map ? item["code"] : item,
),
);
});
String value;
if (cities[0] is Map) {
if (cities.firstWhere((o) => o["code"] == address.city,
orElse: () => null) !=
null) {
value = address.city;
}
} else {
value = cities.contains(address.city) ? address.city : null;
}
return DropdownButton(
items: items,
value: value,
onChanged: (val) {
setState(() {
address.city = val;
});
},
isExpanded: true,
itemHeight: 70,
hint: Text("Ciudad"),
);
} else {
return TextFormField(
controller: _cityController,
validator: (val) {
return val.isEmpty ? S.of(context).cityIsRequired: null;
},
decoration: InputDecoration(labelText: S.of(context).city),
onSaved: (String value) {
address.city = value;
},
);
}
}

Include the modification of the widget (form) in lib/screens/checkout/shipping_address.dart: (line 574)

          renderCityInput(),

                //TextFormField(
                  //controller: _cityController,
                  //validator: (val) {
                    //return val.isEmpty
                      //  ? S.of(context).cityIsRequired
                        //: null;
                  //},
                  //decoration:
                    //  InputDecoration(labelText: S.of(context).city),
                  //onSaved: (String value) {
                    //address.city = value;
                  //},
                //),
Include the modification of initstate in lib/screens/checkout/shipping_address.dart: (line 84)
cities = await Tools.loadCitiesByCountry(address.country);
setState(() {});

Include the modification of the form in lib/screens/checkout/shipping_address.dart: (line 297)
cities = await Tools.loadCitiesByCountry(address.country);
setState(() {});

Include the modification in lib/common/tools.dart: (line 288)

static Future<List> loadCitiesByCountry(String country) async {
try {
// load local config
String path = "lib/config/cities/city_${country.toLowerCase()}.json";
final appJson = await rootBundle.loadString(path);
return List.from(convert.jsonDecode(appJson));
} catch (e) {
return [];
}
}
}

+ Product & version:
fluxstore woocommerce version 1.7.5
+ Flutter (or React Native) version: 
Flutter
+ Testing Device/Simulator: 
iOS / Android

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**
<img width="1280" alt="Screen Shot 2020-07-02 at 8 39 53 AM" src="https://user-images.githubusercontent.com/50452375/86320481-a5de6b00-bc3f-11ea-9782-4882738743c4.png">

https://docs.google.com/forms/u/1/d/e/1FAIpQLScWOjkAJIWJ9rgb9alopfOqLsJrGKbFM5cCYj1JBfLKLsBblQ

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@andyodoo - please help to try your best with this customization, we suggest to use the Debugger form Android Studio to find out the root cause

**Comment by andyodoo** [comment]
thank you for your respond 
we managed to configure  the states and its working 
and we added the cities base on this issue #2672 https://github.com/inspireui/support/issues/2672 
which is seem to be fixed 
but when implement the solution we cant see the city drop down list 
we need your help , can you check it plz

**Comment by minhcasi** [comment]
@andyodoo - could you zip the source and send us for quick checking support@inspireui.com - thank you!

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one with full information - thank you for your time!
