### ISSUE TITLE
add "node_modules" issue occured

### ISSUE THREAD

**Issue by kevadiya** [inspireui/support#4024]
hello team,

I have purchase this code and Username: mindsys

I raise ticket for not generated node_modules dependencies.
I have use command "yarn install" 

but after some process it goes to fail

i am use 
node V 12.18.2
npm V 6.14.5
expo V 3.21.13
yarn 1.22.4

![e03bce82-33cb-4b57-bba0-42dd084e5c73](https://user-images.githubusercontent.com/4812340/86364407-c3d6ba80-bc95-11ea-8d93-5d2beab0128e.jpg)

when i run yarn install command it show error like above image

but when i create new project that run very well in expo. while your code give me error in creating node_modules

please Help me to solve out this

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 
Thank you for your time!
