### ISSUE TITLE
[Fluxstore Woocommerce ] - Problem in Sending PUSH NOTIFICATION | Where to Find FCM Registration Token ?

### ISSUE THREAD

**Issue by swspro** [inspireui/support#4025]
Hi @minhcasi 

Hope you are doing well.

Want your assistance in two simple things

- In the Address Section we want to  **RENAME the Field**  Label **Street Name** to **Area Name** 

-  And Want to **Add another Text Field** Below **Street Name** Field as **LANDMARK** 

Can you please assist where to make that changes in which file and in which section.

I am sending you the SCREEN SHOT of the ADDRESS section of the APP

Your quick response will be highly appreciated.

Regards,
Sam

![address](https://user-images.githubusercontent.com/15525566/86366581-95a6aa00-bc98-11ea-802d-c76368e8a6fb.jpeg)

**Comment by ameenbadri7** [comment]
hello, @swspro Wellcome back.

as you may know, in our [license police](https://inspireui.com/support-policies) we declare that we don't take customization requests for the regular license but you can buy the Extended License or  Support Pack and email us with your request via our email minhcasi@gmail.com and inspireui-team@inspireui.com.

I can give you a little hint!
you can search for the string `'Street Name'` and 'streetName' in your project and try till you finish. 

thank you.

**Comment by swspro** [comment]
Hi @ameenbadri7 

Thanks for that information. Will check with your Extended license plan.

I am facing Issue is sending **PUSH NOTIFICATION using FIREBASE**

Please have a look into the SCREENSHOT in the ATTACHMENT

Its asking for to **ADD an FCM Registration Token**. [ Whene can I find that token ? ]

Sam




![1](https://user-images.githubusercontent.com/15525566/86406709-3e70fb80-bcd1-11ea-9da6-47bac4cb9f34.PNG)
![2](https://user-images.githubusercontent.com/15525566/86406711-403abf00-bcd1-11ea-9948-57bb5d534ad0.PNG)

**Comment by ameenbadri7** [comment]
Dont worry about this message it will be deleted after you successfully installed the firebase notification on your app. 

Please you have to double check your app settings as on this link
https://docs.inspireui.com/fluxstore/firebase/

And also be sure to clean the old build files by backing to your project, and run flutter clean and build agian with the new googleservices.Json file and the other stuff  mention in the tutorial.  
Thank you

**Comment by swspro** [comment]
Hi @ameenbadri7 

Thanks for your quick response.

As we have already enabled the Gmail Login and SMS login in the App, so replacing the new GoogleService . Json file is already done.

And the App is now available on the PlaySore 

So if I delete the existing googleservice .json file and create a new Android Googleservice .json then the login will not work unless and until I upload the new version of the App.

Please suggest..

Hope you understand what I am trying to say.

Sam

**Comment by ameenbadri7** [comment]
I would have to pass this ticket to higher developer in our team. 

@minhcasi

**Comment by swspro** [comment]
Thanks for replying so quick @ameenbadri7 . Highly appreciated!

Want to hear from @trunghieuvn or @minhcasi if you can escalate to any one of them

Thanks
Sam

**Comment by minhcasi** [comment]
@swspro - you could try to use the Inspector Tools to support for customization the Address UI screen - https://www.youtube.com/watch?v=yGMt3Y20Zmg

**Comment by swspro** [comment]
Hi @minhcasi 

Great to hear from you.

Thanks for your suggestions on Address Lable remaining .

1 ) Just wondering if we can add one more text field of Landmark in Address.

 As in real time people are not mentioning proper address, so asking for landmark will be helpful.

2 ) Please give a solution for Push Notifications issue which I have mentioned in the above posts

3 ) Do you provide multiple site License of your products ?

Sam

**Comment by swspro** [comment]
Hi @minhcasi 

Waiting for your assistance

Sam

**Comment by minhcasi** [comment]
@swspro - i will discuss with the team and get back you on these request - thank you!

**Comment by swspro** [comment]
@minhcasi its been login time I am not getting any response.

Can you please assist on the PUSH NOTIFICATION what to do ?

Sam

**Comment by minhcasi** [comment]
@swspro - pls use the latest release `1.7.6` - we have just updated the app more stable and also fix the push notification issue - thank you!

**Comment by swspro** [comment]
Hi @minhcasi 

We want to PURCHASE licence for multiple sites 

Do you provide multiple site license package?

Sam
