### ISSUE TITLE
Keep loading after enter the verification code - Fluxstore MV

### ISSUE THREAD

**Issue by sadeq90** [inspireui/support#4026]
My previous Ticket id: 3922
https://github.com/inspireui/support/issues/3922

Hi, I tried to follow this video and run the command on this page
https://medium.com/@inspireui/setup-google-login-for-flutter-apps-fedc58a490b8

I got an error that .keystore not found and the video may be outdated.

and I don't have any file with extension .keystore, I have .jks

I ran keytool -exportcert -list -v -alias key -keystore app/key.jks
and I got the SHA1 key and I use it in firebase.
Now it works, I receive verification code when I enter the mobile number, but when I enter the verification code it keeps loading for more than 5 minutes without any output.

**1- So what should I do in this case?** @minhcasi

**2- for key file, is it safe to have with password 123456, and I have two keys, one in android/app folder (key.jks) and the other in certs folder**

please take a look in the screenshot @minhcasi

![Annotation 2020-07-02 175347](https://user-images.githubusercontent.com/32711146/86375532-80c51900-bc8e-11ea-942e-e3ceafc305d0.png)

**Comment by ameenbadri7** [comment]
hello, Mr @sadeq90 Wellcome back.

its not outdated but its need some development skills to successfully do it.

please consider using the android studio documentation so you will have these skills in an easy way.

https://developer.android.com/studio/publish/app-signing
after you finish knowing about the sign-in your app you should go back to our 
tutorial https://medium.com/@inspireui/setup-google-login-for-flutter-apps-fedc58a490b8
I guess you will be ok.
if you still have problems you can use our Github it has more than 2300 closed tickets you can get benefit from it.

also, you can use this ticket as it focuses on key signing 
https://github.com/inspireui/support/issues/3151

thank you for your time!

**Comment by ameenbadri7** [comment]
I'm sorry to close this ticket as there is no response or active conversation, 
please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Comment by devienguilde** [comment]
How do u solved it sir i follow that thread too
