### ISSUE TITLE
Getting fluxstore notification in my app 

### ISSUE THREAD

**Issue by tjain90** [inspireui/support#4028]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: I am getting fluxstore sale notification in my app. I have placed my firebase then why so ? Kindly consider this on priority
+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 
![Screenshot_20200702-224609](https://user-images.githubusercontent.com/6376301/86390642-0dcf9880-bcb6-11ea-8ebd-520af50b4e23.jpg)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@tjain90 - pls help to remove this onesignal to fix the issue
```
const kOneSignalKey = {'appID': ''};
```

<img width="1011" alt="Screen Shot 2020-07-03 at 11 45 00" src="https://user-images.githubusercontent.com/1459805/86432636-a1d74980-bd22-11ea-88d4-f4a003ec4e01.png">

**Comment by minhcasi** [comment]
We will also remove this setting on the next release - thank you!
