### ISSUE TITLE
How to update ListApp

### ISSUE THREAD

**Issue by Pars1vaLl** [inspireui/support#403]
- Product: ListApp
 - Your Purchased Code: 85059e37-2ddd-478d-899b....

I  set up ListApp a few month before using 1.4 version. I did it in localhost, so now I am going to deliver it to stores. But I would like to update it  to 1.6 first. I didn`t find any tutorials for this. How can I update ListApp to 1.6 without losing my configurations?

Thanks)

**Comment by minhcasi** [comment]
Hi, the only good way is to override your existing customization to the latest version and compare to check your modify code

As the product is delivered as the full source code so that we don't have a better solution so far, if you have any good solution please suggest us.
