### ISSUE TITLE
Vendor Search

### ISSUE THREAD

**Issue by gonzalovvt** [inspireui/support#4030]
I was trying to perform a vendor search from a string value, this is cause I need to display a specific vendor profile.

I need just to put the name of a vendor and then display that "card" of only that store, as you see in the section of "Stores" in the Category tab.

I was looking in the code and there is a screen called "map" and it doesn't work as I need, later i was trying to code and i didn't get any result

How i can perform a search?

+ Fluxstore Multi Vendor (Latest Version)
+ Flutter version 
+ Android

**Comment by minhcasi** [comment]
@gonzalovvt - the vendor search is not available form current app release, we will upgrade it later - thank you!

**Comment by gonzalovvt** [comment]
Oh okay, this could be a nice feature. But "map" screen is there, isn't?

**Comment by minhcasi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add Vendor Search](https://trello.com/c/m2AoZmLy/64-add-vendor-search)

**Comment by minhcasi** [comment]
Yes, the map will be ready in `1.6.7` - the vendor search is noted in our backlog for further investigating - thank you!
