### ISSUE TITLE
Few issue for multivendor app 

### ISSUE THREAD

**Issue by Cheewingtan** [inspireui/support#4031]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
1. I have auction product on my website,Im using "Ultimate WooCommerce Auction PRO" plugin,but the app isn't support for this plugin, and all auction product display on the app and the price will be 0 and customer can add to cart to process to buy too ,is that possible to hide all auction product on the app?
2. Reward point not working on the mobile app,I use "SUMO Reward Points" plugin, is there any solution for this ?
3. Review function error, customer can leave a review whatever the customer buy or not buy before the product , any method that can let customer only can give a review when the purchased the product?

+ Product & version: 1.7.3
+ Flutter (or React Native) version: Flutter 
+ Testing Device/Simulator: ios
+ Screenshot issues (drag the file to attach here): 
<img width="1440" alt="Screenshot 2020-07-03 at 10 37 36 AM" src="https://user-images.githubusercontent.com/11556877/86427392-a993ef80-bd1c-11ea-933c-d4e5bed91878.png">
<img width="413" alt="Screenshot 2020-07-03 at 10 47 05 AM" src="https://user-images.githubusercontent.com/11556877/86427422-bdd7ec80-bd1c-11ea-9bb8-af4926a44843.png">
<img width="403" alt="Screenshot 2020-07-03 at 10 47 28 AM" src="https://user-images.githubusercontent.com/11556877/86427435-c3353700-bd1c-11ea-8e78-be6a70a5e7c6.png">

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
Sorry for the late response, I remember to answer on the ticket but not sure it is missing

1. It is possible to check if the audit product to hide the price and disable the add-to-cart for this type of product, please try your best with this customization
2. Sorry, we don't have a solution so far, but you could try to refer to existing WooCommerce Point and Reward feature
3. We will upgrade this feature

**Comment by Cheewingtan** [comment]
> Sorry for the late response, I remember to answer on the ticket but not sure it is missing
> 
> 1. It is possible to check if the audit product to hide the price and disable the add-to-cart for this type of product, please try your best with this customization
> 2. Sorry, we don't have a solution so far, but you could try to refer to existing WooCommerce Point and Reward feature
> 3. We will upgrade this feature

New question: 
1. is that any feature or configuration that can let the buyer direct contact the seller by the app message? 
2.It can display the store name on every product page?
3.

**Comment by minhcasi** [comment]
1. it supports via the Smartchat feature
2. yes, pls make sure to use that latest release 1.7.5 

Thank you!

**Comment by minhcasi** [comment]
Let us know if you have any question - thank you!
