### ISSUE TITLE
Product not showing  up when you access them the second time

### ISSUE THREAD

**Issue by medsaadit** [inspireui/support#4033]
Hi,
I am using FluxStore for Shopify
When I click on a category I get product list the first time when I refresh or click on it again on the same category nothing displays, and the same for any other category but only once as well.

the only modification I did is the website domain and the access key and I am accessing my website category from the right bar.
I tied to switch between the Webhook API versions (I am using 2020-07) but still getting the same issue.
Am I missing something?

The second problem is some errors under the product description (Check attachment) !

Is Shopify blog supported ({Domain}/blog/news) ?

Thanks in advance

![Screenshot_20200703-010405](https://user-images.githubusercontent.com/67774655/86539793-688f0d00-becd-11ea-8c64-5c454d8b19f9.jpg)

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by medsaadit** [comment]
Hey ! I got no feed back yet on the issue ?
I already sent license info

**Comment by minhcasi** [comment]
sorry for the issue, we have not got your response from the ticket so that the team has closed it (as missing the verify purchased), but we could verify it now via your comment and re-assign to the technical team for checking - thank you!

@luyx2412 - please help with suggestion

**Comment by luyx2412** [comment]
Hi @medsaadit I just invited you to the Fluxshopify repo, please pull latest code which fixed your issue.

Thanks

**Comment by medsaadit** [comment]
Hi,
When I open the repo folder and run flutter I get the following error :

`fluxstore-shopify-master$ bash tools/build-appbundle.sh
[!] Your app is using an unsupported Gradle project. To fix this problem, create a new project by running `flutter create -t app <app-directory>`
and then move the dart code, assets and pubspec.yaml to the new project.`

**Comment by medsaadit** [comment]
Hi @luyx2412 luyx2412
Can you look at the import issue? is there any upgrade/import documentation for the new code? the old code opened and executed smoothly, not sure what I am doing wrong

**Comment by medsaadit** [comment]
@luyx2412 All works now.
Except for one thing. The error under the "review" section in the product interface (See screenshot). do you have any idea what's going on there?

Thanks in advance.

**Comment by luyx2412** [comment]
Hi @medsaadit Can you share your screenshot again? I could not see anything.

Thanks

**Comment by medsaadit** [comment]
This one :

**Comment by medsaadit** [comment]
https://user-images.githubusercontent.com/67774655/86539793-688f0d00-becd-11ea-8c64-5c454d8b19f9.jpg

**Comment by medsaadit** [comment]
Also, if you notice in the screenshot, the reviews are not showing up not
sure if it's by design or just me.

**Comment by medsaadit** [comment]
@luyx2412 I just need confirmation :
1- is that a bug (instead of related products I get that error)?
![86539793-688f0d00-becd-11ea-8c64-5c454d8b19f9](https://user-images.githubusercontent.com/67774655/86969374-af823a00-c13b-11ea-919f-d6db07848b0d.jpg)

2- do you support reviews display?

Please confirm! thanks

**Comment by luyx2412** [comment]
Hi @medsaadit 
- Let me investigate with your config. And reply you soon.
- Currently we did not support reviews feature.

Thanks

**Comment by medsaadit** [comment]
Okay, please let me know as soon as possible
Thanks

**Comment by medsaadit** [comment]
And for the reviews if it's not supported it should be hidden instead of
empty block and 0 stars !
Can you please provide me an update just for the files that should be
edited. And also a fix for the "related products" bug I have.

Thanks

**Comment by luyx2412** [comment]
Hi @medsaadit We are updating new version and resolve the issue, and notify you soon.

Thanks

**Comment by medsaadit** [comment]
Thanks ! I can't wait to get the update. Hopefully for both, to support the
reviews and fix the "related products" issue.
And the project would be complete.

**Comment by Muad96** [comment]
Regarding the 1st issue of the category, I'm facing the same issue with **v1.7.5**.
I've notice that send time that "**fetchProductsByCategory with cursor**" is getting value and then this error will occur.
I'm not sure however what that value is or from where it's been fetched.

![image](https://user-images.githubusercontent.com/38084566/87491106-e7afde00-c64f-11ea-8a30-b4a144591d0e.png)

**Comment by Muad96** [comment]
> Regarding the 1st issue of the category, I'm facing the same issue with **v1.7.5**.
> I've notice that send time that "**fetchProductsByCategory with cursor**" is getting value and then this error will occur.
> I'm not sure however what that value is or from where it's been fetched.
> 
> ![image](https://user-images.githubusercontent.com/38084566/87491160-129a3200-c650-11ea-960b-9fe690a762a7.png)

I've removed 
`'cursor': productModel.cursor // for next page`
from **Shopify.dart** and now things working. I'd like to know if this will cause any issue. @luyx2412

**Comment by luyx2412** [comment]
Hi @Muad96 I just invited you to the fluxshopify repo which fixed the issue.

Thanks

**Comment by Muad96** [comment]
@luyx2412 Yes, this was fixed I have opened my ticket #4205 with other issues. Thanks

**Comment by GoyalSidhant** [comment]
> Hi @Muad96 I just invited you to the fluxshopify repo which fixed the issue.
> 
> Thanks

I am facing the issue in version 1.7.5+3001

**Comment by medsaadit** [comment]
Guys please create separate tickets !
@luyx2412  Did the issues resolved (reviews and related products error) ?
Thanks

**Comment by luyx2412** [comment]
Hi @medsaadit Yep it was resolved the related and review section in Product detail screen with latest code.

Thanks

**Comment by medsaadit** [comment]
Thanks. indeed I was able to see related products.
the only problem is the reviews I don't think they are working. Even with
the native Shopify reviews app.
how I can make the reviews work?

**Comment by luyx2412** [comment]
HI @medsaadit Currently the review section will not work, so we hided it. And we are updating and researching another api similar reviews.

Thanks
