### ISSUE TITLE
Problem in installation

### ISSUE THREAD

**Issue by Mahir-cloud** [inspireui/support#4036]
Your expo version is not updated
Check this link : https://expo.io/@minhcasi/mstore

So decide installation with react native cli
But it also not updated and gives errors 

Check this https://prnt.sc/tax8x2

I run it with Windows cmd then with visual Studio command line but nothing work plz help me to install as soon as possible. I am very upset with this product please help! 

Product : mstore pro version 4.0

**Comment by Mahir-cloud** [comment]
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

E:\mstore-pro> npm install
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.

> grpc@1.20.0 install E:\mstore-pro\node_modules\grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://node-precompiled-binaries.grpc.io/grpc/v1.20.0/node-v72-win32-x64-unknown.tar.gz
node-pre-gyp WARN Pre-built binaries not found for grpc@1.20.0 and node@12.18.0 (node-v72 ABI, unknown) (falling back to source compile with node-gyp)
gyp ERR! find VS
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:310:5)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--library=static_library" "--module=E:\\mstore-pro\\node_modules\\grpc\\src\\node\\extension_binary\\node-v72-win32-x64-unknown\\grpc_node.node" "--module_name=grpc_node" "--module_path=E:\\mstore-pro\\node_modules\\grpc\\src\\node\\extension_binary\\node-v72-win32-x64-unknown" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd E:\mstore-pro\node_modules\grpc
gyp ERR! node -v v12.18.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --library=static_library --module=E:\mstore-pro\node_modules\grpc\src\node\extension_binary\node-v72-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=E:\mstore-pro\node_modules\grpc\src\node\extension_binary\node-v72-win32-x64-unknown --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (E:\mstore-pro\node_modules\grpc\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Windows_NT 6.3.9600
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\mstore-pro\\node_modules\\grpc\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd E:\mstore-pro\node_modules\grpc
node-pre-gyp ERR! node -v v12.18.0
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --library=static_library --module=E:\mstore-pro\node_modules\grpc\src\node\extension_binary\node-v72-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=E:\mstore-pro\node_modules\grpc\src\node\extension_binary\node-v72-win32-x64-unknown --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\jest-haste-map\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^2.1.2 (node_modules\@jest\transform\node_modules\jest-haste-map\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^2.1.2 (node_modules\@jest\reporters\node_modules\jest-haste-map\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^2.1.2 (node_modules\@jest\test-sequencer\node_modules\jest-haste-map\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^2.1.2 (node_modules\jest-runner\node_modules\jest-haste-map\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^2.1.2 (node_modules\jest-runtime\node_modules\jest-haste-map\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^2.1.2 (node_modules\jest-snapshot\node_modules\jest-haste-map\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^2.1.2 (node_modules\@jest\core\node_modules\jest-haste-map\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN eslint-plugin-react-hooks@3.0.0 requires a peer of eslint@^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @typescript-eslint/eslint-plugin@2.34.0 requires a peer of eslint@^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @typescript-eslint/parser@2.34.0 requires a peer of eslint@^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb@18.2.0 requires a peer of eslint-plugin-react@^7.20.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-react@7.19.0 requires a peer of eslint@^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-react-native@3.8.1 requires a peer of eslint@^3.17.0 || ^4 || ^5 || ^6 but none is installed. You must install peer dependencies yourself.
npm WARN modal-react-native-web@0.2.0 requires a peer of react-art@16.x.x but none is installed. You must install peer dependencies yourself.
npm WARN modal-react-native-web@0.2.0 requires a peer of react-dom@16.x.x but none is installed. You must install peer dependencies yourself.
npm WARN modal-react-native-web@0.2.0 requires a peer of react-native-web@0.9.x but none is installed. You must install peer dependencies yourself.
npm WARN react-native@0.62.2 requires a peer of react@16.11.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-country-picker-modal@1.11.0 requires a peer of react-dom@* but none is installed. You must install peer dependencies yourself.
npm WARN react-native-country-picker-modal@1.11.0 requires a peer of react-native-web@* but none is installed. You must install peer dependencies yourself.
npm WARN react-native-localization@2.1.6 requires a peer of react-native@^0.41.2 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-localization@2.1.6 requires a peer of react-native-windows@0.41.0-rc.1 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-vector-icons@6.7.0 requires a peer of @react-native-community/toolbar-android@^0.1.0-rc.1 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-webview@10.3.1 requires a peer of react@16.11.0 but none is installed. You must install peer dependencies yourself.
npm WARN styled-components@5.1.1 requires a peer of react-dom@>= 16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.20.0 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@1.20.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2020-07-03T07_51_33_126Z-debug.log

E:\mstore-pro>

**Comment by luyx2412** [comment]
HI @Mahir-cloud Please downgrade your node version to 10.x.x, and use yarn https://yarnpkg.com/ to install the package which will fix your issue.

Thanks

**Comment by Mahir-cloud** [comment]
still having issue:

using node 10.20.0

PS E:\> cd mstore-pro
PS E:\mstore-pro> npm install
npm WARN deprecated deep-assign@3.0.0: Check out `lodash.merge` or `merge-options` instead.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number o
f issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to
 fsevents 2.
npm WARN deprecated core-js@1.2.7: core-js@<3 is no longer maintained and not recommended for usage due to the number of
 issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN rm not removing E:\mstore-pro\node_modules\.bin\rimraf.cmd as it wasn't installed by E:\mstore-pro\node_modules
\rimraf
npm WARN rm not removing E:\mstore-pro\node_modules\.bin\rimraf as it wasn't installed by E:\mstore-pro\node_modules\rim
raf
npm WARN rm not removing E:\mstore-pro\node_modules\.bin\semver.cmd as it wasn't installed by E:\mstore-pro\node_modules
\semver
npm WARN rm not removing E:\mstore-pro\node_modules\.bin\semver as it wasn't installed by E:\mstore-pro\node_modules\sem
ver

> grpc@1.20.0 install E:\mstore-pro\node_modules\grpc
> node-pre-gyp install --fallback-to-build --library=static_library

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'E:\mstore-pro\node_modules\node-pre-gyp\bin\node-pre-gyp'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\metro\node_modules\jest-haste-map\node_mod
ules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"an
y"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^2.1.2 (node_modules\jest-haste-map\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any
"} (current: {"os":"win32","arch":"x64"})
npm WARN react-native-country-picker-modal@1.11.0 requires a peer of react-dom@* but none is installed. You must install
 peer dependencies yourself.
npm WARN react-native-country-picker-modal@1.11.0 requires a peer of react-native-web@* but none is installed. You must
install peer dependencies yourself.
npm WARN react-native@0.62.2 requires a peer of react@16.11.0 but none is installed. You must install peer dependencies
yourself.
npm WARN react-native-localization@2.1.6 requires a peer of react-native@^0.41.2 but none is installed. You must install
 peer dependencies yourself.
npm WARN react-native-localization@2.1.6 requires a peer of react-native-windows@0.41.0-rc.1 but none is installed. You
must install peer dependencies yourself.
npm WARN react-native-webview@10.3.1 requires a peer of react@16.11.0 but none is installed. You must install peer depen
dencies yourself.
npm WARN styled-components@5.1.1 requires a peer of react-dom@>= 16.8.0 but none is installed. You must install peer dep
endencies yourself.
npm WARN modal-react-native-web@0.2.0 requires a peer of react-art@16.x.x but none is installed. You must install peer d
ependencies yourself.
npm WARN modal-react-native-web@0.2.0 requires a peer of react-dom@16.x.x but none is installed. You must install peer d
ependencies yourself.
npm WARN modal-react-native-web@0.2.0 requires a peer of react-native-web@0.9.x but none is installed. You must install
peer dependencies yourself.
npm WARN eslint-plugin-react-hooks@3.0.0 requires a peer of eslint@^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0 but none is inst
alled. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb@18.2.0 requires a peer of eslint-plugin-react@^7.20.0 but none is installed. You must inst
all peer dependencies yourself.
npm WARN eslint-plugin-react@7.19.0 requires a peer of eslint@^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0 but none is installed
. You must install peer dependencies yourself.
npm WARN eslint-plugin-react-native@3.8.1 requires a peer of eslint@^3.17.0 || ^4 || ^5 || ^6 but none is installed. You
 must install peer dependencies yourself.
npm WARN @typescript-eslint/parser@2.34.0 requires a peer of eslint@^5.0.0 || ^6.0.0 but none is installed. You must ins
tall peer dependencies yourself.
npm WARN @typescript-eslint/eslint-plugin@2.34.0 requires a peer of eslint@^5.0.0 || ^6.0.0 but none is installed. You m
ust install peer dependencies yourself.
npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.
0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dep
endencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.20.0 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@1.20.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2020-07-03T17_57_44_463Z-debug.log
PS E:\mstore-pro>

**Comment by Mahir-cloud** [comment]
Please instruct me to install mstore via expo

**Comment by Mahir-cloud** [comment]
Or please provide me cebuilder i am newbie to app development i bought mstore for cebuilder but now I am stuck. 

Can you please refund my money or just migrate me mstore to fluxstore or provide cebuilder becoz after 3 days it still give errors while installing

**Comment by Mahir-cloud** [comment]
Is there any live chat support I am totally exhausted plz plzz help

**Comment by minhcasi** [comment]
First pls try to install yarn - https://yarnpkg.com/

And go to the project to run `yarn install` instead of using npm install

**Comment by Mahir-cloud** [comment]
```
Having same issue now I am decided it to install with expo cli but it give following error tooo
```
PS E:\neww\mstore-expo> yarn install
yarn install v1.22.4
info No lockfile found.
[1/4] Resolving packages...
warning babel-preset-env > babel-plugin-check-es2015-constants > babel-runtime > core-js@2.6.11: core-js@<3 is no longer
 maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual v
ersion of core-js@3.
warning expo > babel-preset-expo@8.1.1: 8.1.1 mistakenly contains the contents of 8.2.1; use that version instead
warning expo > expo-font > fbjs > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due t
o the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning expo > fbemitter > fbjs > core-js@1.2.7: core-js@<3 is no longer maintained and not recommended for usage due to
 the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning react-native > fbjs-scripts > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage d
ue to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning react-native > metro-babel-register > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for
 usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning react-native > @react-native-community/cli > @hapi/joi@15.1.1: This version has been deprecated and is no longer
 supported or maintained
warning react-native > @react-native-community/cli > @hapi/joi > @hapi/topo@3.1.6: This version has been deprecated and
is no longer supported or maintained
warning react-native > @react-native-community/cli > @hapi/joi > @hapi/hoek@8.5.1: This version has been deprecated and
is no longer supported or maintained
warning react-native > @react-native-community/cli > @hapi/joi > @hapi/topo > @hapi/hoek@8.5.1: This version has been de
precated and is no longer supported or maintained
warning react-native > @react-native-community/cli > @hapi/joi > @hapi/address@2.1.4: This version has been deprecated a
nd is no longer supported or maintained
warning react-native > @react-native-community/cli > @hapi/joi > @hapi/bourne@1.3.2: This version has been deprecated an
d is no longer supported or maintained
warning react-native > @react-native-community/cli > metro-core > jest-haste-map > fsevents@1.2.13: fsevents 1 will brea
k on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
warning react-native > @react-native-community/cli > metro-core > jest-haste-map > micromatch > snapdragon > source-map-
resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning react-native > @react-native-community/cli > metro-core > jest-haste-map > micromatch > snapdragon > source-map-
resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
error Couldn't find the binary git
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
PS E:\neww\mstore-expo> yarn start
yarn run v1.22.4
$ expo start
Starting project at E:\neww\mstore-expo
Expo DevTools is running at http://localhost:19002
Opening DevTools in the browser... (press shift-d to disable)
Your project is in SDK version >= 33.0.0, but the expo package version seems to be older.
Error: node_modules directory is missing. Please run `npm install` in your project directory.
Couldn't start project. Please fix the errors and restart the project.
Error: Couldn't start project. Please fix the errors and restart the project.
    at startExpoServerAsync (C:\@expo\xdl@57.9.20\src\Project.ts:2070:11)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS E:\neww\mstore-expo>

**Comment by Mahir-cloud** [comment]
Please instruct me to install it with expo or provide me cebuilder

**Comment by minhcasi** [comment]
@Mahir-cloud - you could download the cebuilder on this link https://github.com/inspireui/cebuilder/releases/tag/0.40.1 and give a try with the installing

**Comment by Mahir-cloud** [comment]
Giving an error while setup project

https://prnt.sc/tci0ke

**Comment by Mahir-cloud** [comment]
Please Reply ASAP

**Comment by Mahir-cloud** [comment]
I think you making me fool 

File name showing beostore when downloaded 

Your cebuilder giving an error 

Expo not working 

React native cli didn't working 

I think you just want money 🤑

**Comment by Mahir-cloud** [comment]
And what type of support it is. You didn't solve my problem in 5 days 

I raise a ticket on envato for refund 

I need my money back you have nothing to offer you are making people fools that's it

**Comment by minhcasi** [comment]
if you could not use the product, it is possible to process refund on this link https://help.market.envato.com/hc/en-us/articles/202821460-Can-I-Get-A-Refund-

**Comment by Mahir-cloud** [comment]
I already request a refund on envato 3 Days back please response
