### ISSUE TITLE
Default products list  in one column with title on the left

### ISSUE THREAD

**Issue by daboujey** [inspireui/support#4037]
Detail Issues: Page productos display list as default view, without having to select list on the filter page
Product & version: Version: 1.7.5
Flutter (or React Native) version: 1.17.4
Testing Device/Simulator: Nexus 6 API 26
Screenshot issues (drag the file to attach here):

My app list 2 column with default view
e I nedd list 1 column

THIS IS THE LIST
![TELA-APP3](https://user-images.githubusercontent.com/64880213/86461051-cbcb4480-bcff-11ea-9b59-3ac41d14d094.jpeg)

BUT I NEED THE LIST SO
![TELA-APP2](https://user-images.githubusercontent.com/64880213/86461108-dd145100-bcff-11ea-8bd5-66adcacedfb2.jpeg)

 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by ameenbadri7** [comment]
I couldn't understand your request could you specify it with detailed screenshots.
or you can record a video so I can understand.
thank you for your patience.

**Comment by daboujey** [comment]
HOW DO I LEAVE THIS LIST AS DEFAULT ???
![TELA-APP2](https://user-images.githubusercontent.com/64880213/86509995-89b70700-bdc2-11ea-8357-30ecd8022e11.jpeg)

**Comment by daboujey** [comment]
I don't want it like that

https://www.youtube.com/watch?v=Jv2XCZZGTdI

**Comment by daboujey** [comment]
I want:
![TELA-APP2](https://user-images.githubusercontent.com/64880213/86510266-9f2d3080-bdc4-11ea-8ff4-a13f5f54c304.jpeg)

**Comment by daboujey** [comment]
![TELA-APP4](https://user-images.githubusercontent.com/64880213/86510448-039cbf80-bdc6-11ea-944f-f3c86fca9fa5.jpeg)

**Comment by ameenbadri7** [comment]
change your `config ` file inside `lib\config\config_ar.json`  you will find inside it:  `setting `> `ProductListLayout `> change it from `list `to `ProductListLayout`
```
 "Setting": {
......
    "ProductListLayout": "listTile",
  },
```
that will change the default to ProductListLayout that you want.

if you want to change to even change the order of that icon to the first instead of the fifth 
change `kProductListLayout`

const kProductListLayout = [
  {"layout": "list", "image": "assets/icons/tabs/icon-list.png"},
  {"layout": "columns", "image": "assets/icons/tabs/icon-columns.png"},
  {"layout": "card", "image": "assets/icons/tabs/icon-card.png"},
  {"layout": "horizontal", "image": "assets/icons/tabs/icon-horizon.png"},
  {"layout": "listTile", "image": "assets/icons/tabs/icon-lists.png"},
];

to be : 

```
const kProductListLayout = [
  {"layout": "listTile", "image": "assets/icons/tabs/icon-lists.png"},
  {"layout": "list", "image": "assets/icons/tabs/icon-list.png"},
  {"layout": "columns", "image": "assets/icons/tabs/icon-columns.png"},
  {"layout": "card", "image": "assets/icons/tabs/icon-card.png"},
  {"layout": "horizontal", "image": "assets/icons/tabs/icon-horizon.png"},
];
```

**Comment by daboujey** [comment]
I made the change but it doesn't work
https://www.youtube.com/watch?v=lRkF_hLlYxI

changed the position of the icon but it was not listTile default 

![TELA-APP5](https://user-images.githubusercontent.com/64880213/86530831-8be89680-be92-11ea-98aa-de730c2a0f50.jpg)

( comand flutter clean used )

**Comment by ameenbadri7** [comment]
I try it my self yesterday to check.  Its working!  
Could clear the build cache. 
From the terminal : flutter clean and then build for release. 
Please tell us if you still have problems

**Comment by ameenbadri7** [comment]
I'm sorry to close this ticket as there is no response or active conversation, 
please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
