### ISSUE TITLE
A problem when adding a product

### ISSUE THREAD

**Issue by emadpost2016** [inspireui/support#4039]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

When adding a product and when clicking on add a picture from the gallery
It opens the camera directly
I can not add product pictures, please quick help
flux MV 1.7.5
flutter 1.17.3
my samsung A30
![1](https://user-images.githubusercontent.com/58606378/86463941-c6392300-bd2e-11ea-99ab-930726437b56.jpg)
![2](https://user-images.githubusercontent.com/58606378/86463943-c6d1b980-bd2e-11ea-9955-fd91f23b03b2.png)
![7a49907b-cebe-4abd-8399-e98902860fc2](https://user-images.githubusercontent.com/58606378/86463950-c9ccaa00-bd2e-11ea-96a4-ce9ded0eb121.jpg)
![kk](https://user-images.githubusercontent.com/58606378/86463952-c9ccaa00-bd2e-11ea-9685-7a6d2160d633.png)

**Comment by jinuem** [comment]
Same issue I'm facing in 1.7.3 Version. Let me know the Solution as well. :)

**Comment by emadpost2016** [comment]
Any updates

**Comment by jinuem** [comment]
I debugged and found this ..  It might help the developer.

This is validation Error. SALE PRICE should be filled. No Error message thrown if not filled. But inside the code, Its expecting Double value. Thats where the Code Breaks and stops in Loading Screen.

<img width="704" alt="Screenshot 2020-07-05 at 2 36 19 PM" src="https://user-images.githubusercontent.com/3512723/86529255-e6064d80-becc-11ea-985c-1a11ad33cef5.png">

**Comment by jinuem** [comment]
@emadpost2016 I have added Few validations in the File according to my needs.

Use it and customise it as per your needs.

File:
lib/vendor/products/create_product_screen.dart
[create_product_screen.dart.zip](https://github.com/inspireui/support/files/4875208/create_product_screen.dart.zip)

**Comment by emadpost2016** [comment]
The problem when clicking on the product image from the gallery is entered
into the camera only

[image: image.png]


‫في الأحد، 5 يوليو 2020 في 6:11 م تمت كتابة ما يلي بواسطة ‪Vincent George‬‏
<‪notifications@github.com‬‏>:‬

**Comment by emadpost2016** [comment]
When I want to add a product and write all the required data, the
problem appears when adding a product image

[image: image.png]


‫في الأحد، 5 يوليو 2020 في 8:24 م تمت كتابة ما يلي بواسطة ‪Emad Fouad‬‏ <‪
emad.post2016@gmail.com‬‏>:‬

**Comment by minhtruong315** [comment]
@emadpost2016 can u send me common folder?
Thanks

**Comment by emadpost2016** [comment]
yes this is common folder

‫في الاثنين، 6 يوليو 2020 في 6:10 ص تمت كتابة ما يلي بواسطة
‪minhtruong315‬‏ <‪notifications@github.com‬‏>:‬

**Comment by minhtruong315** [comment]
@emadpost2016 I dont see. pls send via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/4039
<img width="1040" alt="Screen Shot 2020-07-06 at 11 27 57 AM" src="https://user-images.githubusercontent.com/10402500/86555857-d560e080-bf7b-11ea-8808-9257b429fa52.png">

**Comment by minhtruong315** [comment]
Hi @emadpost2016 I tried to update a product, it's working well
![Simulator Screen Shot - iPhone 11 - 2020-07-06 at 15 27 00](https://user-images.githubusercontent.com/10402500/86572510-3fd64880-bf9d-11ea-889d-4403ab4ae5f1.png)
Can u give me your skype? I will help u check the issue via teamviewer
Thanks

**Comment by emadpost2016** [comment]
my skype     emad.post2016@gmail.com

**Comment by emadpost2016** [comment]
+20    01221930409

‫في الاثنين، 6 يوليو 2020 في 1:16 م تمت كتابة ما يلي بواسطة ‪Emad Fouad‬‏ <‪
emad.post2016@gmail.com‬‏>:‬

**Comment by minhtruong315** [comment]
Hi @emadpost2016 I messaged you on the skype. pls check. thanks

**Comment by minhtruong315** [comment]
I sent you the latest source code for Fluxstore MV, it resolved issue for creating product.

**Comment by devienguilde** [comment]
how do solved it?
