### ISSUE TITLE
Deactivate Purchase Code from localhost

### ISSUE THREAD

**Issue by jeffrysaputra97** [inspireui/support#4040]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: I'm trying to move from my localhost to production environment. I'm already using my purchase code for the MStore API plugin in my localhost environment, is there any way I could deactivate and use the purchase code again? I already saw someone with similar issues here: https://github.com/inspireui/support/issues/3886, and try using the fluxbuilder but still getting confused. Any help will be appreciated
 
+ Product & version: Fluxstore WooCommerce - Flutter E-commerce Full App v 1.7.5
+ Flutter (or React Native) version: Flutter
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 
![image](https://user-images.githubusercontent.com/29313386/86471544-c1449580-bd67-11ea-99b5-88a49aea0b6d.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by jeffrysaputra97** [comment]
> Thank you for the feedback.
> 
> Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.
> 
> We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!
> 
> > **[Google Forms - create and analyze surveys, for free.](http://verify.inspireui.com/)**Create a new survey on your own or with others at the same time. Choose from a variety of survey types and analyze results in Google Forms. Free from Google.

Hello, ok noted. Already submit a form. Please check, thank you for your time

**Comment by minhcasi** [comment]
@jeffrysaputra97 - we have reset the code, could you help to check it again - thank you!

**Comment by jeffrysaputra97** [comment]
Ok, will check, thank you for the assistance
