### ISSUE TITLE
#3656. Fluxstore app,  permissions to make api requests

### ISSUE THREAD

**Issue by Shiru-kun** [inspireui/support#4042]
**_Step 1 (require): describe detail issues & screenshots_**
![Screenshot_20200703-174119](https://user-images.githubusercontent.com/54008441/86483954-702ba600-bd55-11ea-88a7-be1ea9bd886d.jpg)
when i try to login or signup it says "sorry dont have permissions to make api requests"
+ Detail Issues: 
when i try to login or signup it says "sorry dont have permissions to make api requests"

+ Product & version:
1.7.4
+ Flutter (or React Native) version: 
1.17.
+ Testing Device/Simulator: 
andorid device samsung A01, and simulator iphone SE
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by Shiru-kun** [comment]
I already created the htaccess file in root of my website and added these lines: 
![image](https://user-images.githubusercontent.com/54008441/86484255-1a0b3280-bd56-11ea-8525-780599d506c7.png)

**Comment by ameenbadri7** [comment]
its worked with you or you still have problems sir ?

**Comment by Shiru-kun** [comment]
Didnt work.

**Comment by minhcasi** [comment]
@Shiru-kun - please try to check from the mstore-api if you have activated the license - thank you!

**Comment by Shiru-kun** [comment]
already did 
![image](https://user-images.githubusercontent.com/54008441/86511265-a02b8580-bdf7-11ea-940d-4a4a8ed97e06.png)

but still got the issue.

**Comment by ameenbadri7** [comment]
if this  `https://garahesale.com/` is not your website or it has a misspelling please edit your config files to the new website.
because your site` https://garahesale.com/` is down.
could you please fix this issue with your host provider first so we can continue the investigation about your issue.

**Comment by ameenbadri7** [comment]
could you give us more detail about your problem with screenshots or a simple video you can upload to youtube? 

thank you for your patience.

**Comment by Shiru-kun** [comment]
@ameenbadri7  my problem is:  when i try to register or login i got this exception

![image](https://user-images.githubusercontent.com/54008441/86544509-bd5f7180-bf27-11ea-8da9-3ef7438b28c4.png)

i already installed the mstore plugin and activated the license, i also added few lines in htaccess as show in the screenshot in comments...

**Comment by ameenbadri7** [comment]
I will send a ticket to our staff email and they will answer it as soon as possible. 

Thank you for your patience agian.

**Comment by Shiru-kun** [comment]
@ameenbadri7 u  can also check in the source code or in my website.

**Comment by Shiru-kun** [comment]
> I will send a ticket to our staff email and they will answer it as soon as possible.
> 
> Thank you for your patience agian.

ok.  i appreciate

**Comment by minhcasi** [comment]
@minhtruong315 - pls help with checking

**Comment by minhtruong315** [comment]
@Shiru-kun Can u send me admin info via email: truong@inspireui.com?
with subject: https://github.com/inspireui/support/issues/4042
Thanks

**Comment by Shiru-kun** [comment]
Check your inbox
@minhtruong315

**Comment by minhtruong315** [comment]
Hi @Shiru-kun I disabled this plugin, so it's working well now. Please check again
<img width="1125" alt="Screen Shot 2020-07-06 at 4 25 25 PM" src="https://user-images.githubusercontent.com/10402500/86578040-6304f600-bfa5-11ea-9d33-e4e4977472ea.png">

**Comment by Shiru-kun** [comment]
ok let me try

**Comment by Shiru-kun** [comment]
its working...

**Comment by Shiru-kun** [comment]
why i got this conflict with this plugin ?

**Comment by minhtruong315** [comment]
I dont know. I think that plugin disabled POST data to backend, so it doesn't allow to use rest api.

**Comment by Shiru-kun** [comment]
might be that.. thank for the help...
