### ISSUE TITLE
Source code not transferring/ Settings (cog) icon does nothing

### ISSUE THREAD

**Issue by Benhur3000** [inspireui/support#4043]
Step 1 (require): describe detail issues & screenshots

Detail Issues: 1) When I publish in fluxbuilder and copy the config.json code and paste into the config.json file in android studio it is not showing any changes.

2) The icon that looks like a cog in fluxbuilder does not seem to do anything when I click on it.

Product & version: FLuxstore MV 1.7.6
Flutter (or React Native) version: Flutter 1.17.5
Testing Device/Simulator: Fluxbuilder and Emulator
Screenshot issues (drag the file to attach here):
![Cog icon does nothing](https://user-images.githubusercontent.com/67126788/86487386-258d3800-bd1b-11ea-9d23-8f8b56b8a392.png)
![Source Code not working in android studio](https://user-images.githubusercontent.com/67126788/86487389-26be6500-bd1b-11ea-82bb-17e9bd217060.PNG)

**Comment by Benhur3000** [comment]
3) Also all categories are not showing up in the categories page and when I go to add a new product I'm not given the full list of categories.

**Comment by Benhur3000** [comment]
4) How do I link the store page banner from my website to the store page banner on the app instead of showing the logo twice?

**Comment by ameenbadri7** [comment]
hello, @be please consider using our fluxstore configuration tutorials in our documentation https://docs.inspireui.com/fluxstore/multi-vendor/

please put the right category id for your app to work.

can you try with our demo first ?

**Comment by minhcasi** [comment]
@vumanhsn97 - please help to investigate the Fluxbuilder issue on this ticket - thank you!

**Comment by vumanhsn97** [comment]
Issue 1: Past your config to correct config_language. Default language is en: https://tppr.me/5TDvu
Issue 2: This icon is dark mode button. It is working well. Can you check it again? https://tppr.me/V5aGR
Issue 3: Your category with empty product will be hide
Issue 4: Feature request!

**Comment by Benhur3000** [comment]
Hi sorry for the delay did not have a chance to investigate. So I'll note the following

1) I already have the correct config language (config_en.json)
2) This icon doesn't seem to work for me but the dark feature is not needed anyhow
3) I would like to display empty categories as it for some reason when I add a product through the app I'm not given all the category options to select. I have used the correct category ID however do I need to fill in the rest of the category ID's? Please see attached images as I only changed the first category ID as instructed by you guide.
![CAtegory 1d](https://user-images.githubusercontent.com/67126788/87334447-e2da1580-c4fb-11ea-9e1a-984107899aea.png)
![Category number](https://user-images.githubusercontent.com/67126788/87334451-e40b4280-c4fb-11ea-9b0c-9909876ca899.png)


4) Yes this would be a great feature...less work!

**Comment by vumanhsn97** [comment]
@Benhur3000 
in lib/common/config/config.dart set isCaching = fasle https://tppr.me/ph7eM
Run this cmd:
flutter clean
flutter run

**Comment by Benhur3000** [comment]
@vumanhsn97 Thank you the isCaching method worked. However I still have the issue of categories not being full displayed...
1) Empty Categories are hidden...I would like them not to be hidden
2) When I add a product I don't get the full list of categories from my site...See images
![All categories](https://user-images.githubusercontent.com/67126788/87586094-40599800-c69d-11ea-8f70-c20cb5048943.png)
![App Categories](https://user-images.githubusercontent.com/67126788/87586096-418ac500-c69d-11ea-9900-0e833e6791e1.png)

**Comment by vumanhsn97** [comment]
@Benhur3000 
In lib/services/woo_commerce.dart remove &hide_empty=true in this line https://tppr.me/sQiPb

**Comment by Benhur3000** [comment]
This worked perfect. Thank you! I do have a pending issue that I sent through email and still waiting on a reply from you for. Please look for a email with subject: Add to cart function...
Thank you

**Comment by vumanhsn97** [comment]
@Benhur3000 
I didn't receive your email. Please show this issue at here
Thanks!

**Comment by Benhur3000** [comment]
Hi I've created a new support ticket and address it in #4232 Thank you
