### ISSUE TITLE
Mstore Api not working

### ISSUE THREAD

**Issue by Benhur3000** [inspireui/support#4044]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: When I try to add the config.json file to the mstore api plugin in wordpress it just disappears...I followed your guide steps to resolve but nothing.
+ Product & version: Fluxstore MV 1.7.6
+ Flutter (or React Native) version: 1.17.5
+ Testing Device/Simulator: N/A
+ Screenshot issues (drag the file to attach here): 
![Mstore api ](https://user-images.githubusercontent.com/67126788/86488304-cd0b6a00-bd1d-11ea-85b3-493c5afc9db9.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@Benhur3000 - it is showne the cached is actived, that mean you have uploaded successful, the next step to update the `isCaching:true` from the config to enable the caching

Please help to move your further comment into one Open ticket #4043 - thank you for your time
