### ISSUE TITLE
Show only specific blog pages

### ISSUE THREAD

**Issue by heftipascal1** [inspireui/support#4045]
Hi, is it possible to show only specific Blog Pages?
We have 3 Categorys on the Blog "Featured, News, Vouchers" is it possible to display in the app only Featured? and not the whole blog?

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**
https://github.com/inspireui/fluxbuilder/issues/129

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
@heftipascal1 - could you help to clarify more about the request, do you mean to show the Blog content on the Home screen, instead of the Listing content?

**Comment by heftipascal1** [comment]
Hi, on the Home Screen it´s possible to show the blog yes. 
But is it also possible to show only some blogpost with specific blog categorie on the HomeScreen, so we can filter some blogposts?

**Comment by minhcasi** [comment]
@heftipascal1 - sorry - the current design only supports one Blogpost on the homescreen, we will check solution to upgrade it later - thank you!

**Comment by minhcasi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add more config Blog support](https://trello.com/c/80Cx9X2r/63-add-more-config-blog-support)

**Comment by minhcasi** [comment]
move to the backlog for further investigating
