### ISSUE TITLE
Language and app error stopped working

### ISSUE THREAD

**Issue by Marcleiton** [inspireui/support#4046]
Hello, this is my third topic here about language bugs, and follow again.

1 ° The language does not change to the pt-br language, which in the app is BR, always remains in English as the main one.
Follow the print that shows that the change was made: https://i.imgur.com/3SP3rD3.png

I would like it to become the standard br, because it is interesting for me and I would only release that language.

2 ° The App after generating the apk, tested it always give the APP STOP WORKING, this in tests and with the app already working.
*tested on some devices and stop working, Android and everything ok

Every informed tutorial was followed and I still have the same errors.
I have already sent the files to you several times.

I appreciate if you can help me

**Comment by minhtruong315** [comment]
@Marcleiton can u send me full your source code via email: minhtruong315@gmail.com?
I'll help you check.
Ping me when you sent.
Thanks

**Comment by Marcleiton** [comment]
hello sent

**Comment by Marcleiton** [comment]
Hello friend, were you able to take a look at the files I sent?

**Comment by minhtruong315** [comment]
Hi @Marcleiton sorry for delay. I'm ready for supporting. I dont see any the email. can u resend me?
Thanks

**Comment by Marcleiton** [comment]
> Hi @Marcleiton sorry for delay. I'm ready for supporting. I dont see any the email. can u resend me?
> Thanks

hello sent

**Comment by Marcleiton** [comment]
> Hi @Marcleiton sorry for delay. I'm ready for supporting. I dont see any the email. can u resend me?
> Thanks

Hello friend, did you check something?

**Comment by minhtruong315** [comment]
Hi @Marcleiton Can u give me your skype? I will help you check via teamviewer.
Thanks

**Comment by Marcleiton** [comment]
Skype marcleiton.aj

**Comment by minhtruong315** [comment]
Hi @Marcleiton I messaged you on the skype. pls check
Thanks
