### ISSUE TITLE
Problema de visualización de productos en la categoría me sale que tengo 29 producto pero en la listado de visualización nada tengo 20 para mostrar 

### ISSUE THREAD

**Issue by henry2327** [inspireui/support#4047]
![20200703_143456](https://user-images.githubusercontent.com/36794944/86492055-c808e380-bd3a-11ea-98ca-3b254061e9f6.png)
![Screenshot_20200703-143417](https://user-images.githubusercontent.com/36794944/86492057-c8a17a00-bd3a-11ea-8782-4813e5aad22f.png)
![Screenshot_20200703-143426](https://user-images.githubusercontent.com/36794944/86492061-cd662e00-bd3a-11ea-887f-e050ef1b386d.png)
![Screenshot_20200703-143434](https://user-images.githubusercontent.com/36794944/86492065-d2c37880-bd3a-11ea-84c3-6cfb30939c53.png)

**Comment by minhcasi** [comment]
could you help to comment on the same open ticket #3955 ? Thanks
