### ISSUE TITLE
[Fluxstore 1.7.5 Woo]  progress indicator 

### ISSUE THREAD

**Issue by altimimika** [inspireui/support#4049]
Dear InspireUI Team,
Fluxstore woocommerce 1.7.5 Android
in my country the internet very bad my store some times be slowly.. So I need to add progress indicator in my product list like this in my screenshot thank you very much
![my pro](https://user-images.githubusercontent.com/49140931/86499089-db936900-bd91-11ea-81b7-4dcca2579ac4.jpg)

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by altimimika** [comment]
I have submited this form and fill all required info

**Comment by altimimika** [comment]
1-My issue:
in my country the internet very bad my store some times be slowly.. So I need to add progress indicator in my product list like this in my screenshot thank you very much

Screenshots issues (required):
![my pro](https://user-images.githubusercontent.com/49140931/86520698-f9270800-be4f-11ea-8f3f-422e94477848.jpg)

**Comment by minhcasi** [comment]
@altimimika - are you sure to improve this UX as we don't think it is better experience, the current product list is showing empty state product that is better than only show locking Loading icon

Do you think showing `loading...` from the product title is better?

**Comment by altimimika** [comment]
Yes it is better and  important thing . The costumer need to see someting move to know we have thing will appear .The empty state product Does not contain any movement just Static image ... thank you

**Comment by minhcasi** [comment]
noted, we will fix it on 1.6.7 and release in 1-2 days - thank you!

**Comment by minhcasi** [comment]
Fixed on the latest `1.7.6`, let us know if you have any issues - thank you!

**Comment by altimimika** [comment]
Thank you very very much..
Can you add flash sales on app .. please looks on this app there are my
nice special  things ..this is the link of app its also for woocommerce..
thank you

https://play.google.com/store/apps/details?id=woocommerce.onliner.ir

في الاثنين، ١٣ يوليو ٢٠٢٠ ٢:٥٣ م Minh Pham <notifications@github.com> كتب:
