### ISSUE TITLE
[Mstore Pro] 3.7.1 Android Facebook Login Not Working

### ISSUE THREAD

**Issue by levi-beers** [inspireui/support#405]
I recorded some real-time video of an actual device using the feature. When you try to login with FB it doesn't advance to next screen. I haven't debugged the issue yet but will report if I'm able to resolve. 

[https://youtu.be/XDjCsOrrFwo](https://youtu.be/XDjCsOrrFwo)

**Comment by minhcasi** [comment]
Thank you @levi-beers - we will have a check

Your custom homepage looks awesome, what is the branding plugins & API that you are using?

**Comment by luyx2412** [comment]
HI @levi-beers I just checked and everything worked normal, so can you debug to check this issue?

Thanks
