### ISSUE TITLE
FluxNews - in app comments are not working

### ISSUE THREAD

**Issue by joseph-ga** [inspireui/support#4050]
Comments on the app are not working,if i add comment it shows the following message on screenshot but comments don`t show up on the app or on the admin side.
App name: fluxnews
Version:1.4.1

I have attached my proof of purchase to the ur gitlab page.(envato username:galeboe)

![Screenshot_1593722839](https://user-images.githubusercontent.com/67762287/86502957-44d2a680-bda9-11ea-835a-1919d0f5244b.png)

**Comment by joseph-ga** [comment]
i am using android emulator

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by joseph-ga** [comment]
i have submitted the required info.

**Comment by minhcasi** [comment]
@joseph-ga - could you help to check this config - https://docs.inspireui.com/fluxnews/getting-started/#enable-post-a-comment - thank you!

**Comment by joseph-ga** [comment]
i did all that.

![pic1](https://user-images.githubusercontent.com/67762287/86543662-05c76100-bf21-11ea-8858-8a51c2ec7406.png)
![pic2](https://user-images.githubusercontent.com/67762287/86543669-0eb83280-bf21-11ea-9cf6-c744c16f4b22.png)
![pic4](https://user-images.githubusercontent.com/67762287/86543672-14157d00-bf21-11ea-8809-42a2281489b9.png)


i don`t know if the problem is mstoreApi config because this version has the following files in common folder:between config.dart and config_en.json,which file should i apload to the mstoreApi?.

I just uploaded config_en.json and still  its not working.

**Comment by joseph-ga** [comment]
![pic3](https://user-images.githubusercontent.com/67762287/86543686-38715980-bf21-11ea-9f52-f446095a3a41.png)

functions.php

**Comment by minhcasi** [comment]
Thank you for the detail, I've forward to my team for further investigating - thank you!

@dttrung26 - pls help to investigate

**Comment by dttrung26** [comment]
Hi @joseph-ga ,
could you send me admin access to your site via trung@inspireui.com? I've checked our demo site, it turned out things still work fine. Therefore, the problem might come from your site settings. 
Best!

**Comment by dttrung26** [comment]
In temrs of DarkTheme feature: Currently, FluxNews does not support store DarkTheme in local storage. We'll consider adding this feature in few next patches. However, if you are really in need of this feature, you can investigate and implement it yourself by playing around with this package: https://pub.dev/packages/localstorage.

**Comment by dttrung26** [comment]
Hi @joseph-ga , 
I've received your admin acess and working on your issue. I'll get you back soon.
Best!

**Comment by dttrung26** [comment]
Hi @joseph-ga ,
replacing below file into your /lib/widgets/blogs/comment would do the tricks. 
Kindly confirm if it works.
Best!
[issue#4050.zip](https://github.com/inspireui/support/files/4882407/issue.4050.zip)

**Comment by joseph946** [comment]
its working sir,Thank you

one more question sir, how do I set up YouTube videos/Facebook?

2.how to change drawer icon size and position?

3.how to change appbar background colour and drawer?


Thank you

**Comment by joseph946** [comment]
Sir I have a problem again with configuring about us screen, privacy policy and contact.please help

**Comment by dttrung26** [comment]
Hi @joseph946 , 
1. In order to add Facebook/Youtube video, all you have to do are pasting a youtube/facebook URL into Wordpress post, and change  `"DetailedBlogLayout": "oneQuarterImageType` which located at /lib/common/config.dart, `kAdvanceConfig` variable. 
2. In order to customize drawer icon position, you could replace item's order inside `items` array.
```
///this variable located at /lib/common/config.dart
const kDefaultDrawer = {
  "logo": "assets/images/logo.png",
  "background": null,
  "items": [
    {"type": "home", "show": true},
    {"type": "web", "show": true},
    {"type": "about", "show": true},
    {"type": "login", "show": true},
    {"type": "category", "show": true}
  ]
};
```
3. Currently, FluxNews does not support for customizing Tabbar and Drawer color. However, if you are in need of customization support, you can take a look at [InspireUI Support Policy](https://inspireui.com/support-policies/) for further information

Have a nice day!

**Comment by joseph946** [comment]
Sir thank you very much...everything is good except that

1. now I can't disable ads?

2.changing statusbar colour?

3.where to add no internet connection screen plus reload button?

4.any tutorial /guide to configure apple sign in Xcode?

**Comment by joseph946** [comment]
"oneQuarterImageType" causes this error on screenshot

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-07-13 at 02 20 54](https://user-images.githubusercontent.com/57080707/87260090-fcee0680-c4af-11ea-82be-09d13b2c360c.png)

**Comment by dttrung26** [comment]
Hi @joseph946 , 
1. to disable advertisements, you could go to `kAdConfig` at `/lib/common/config.dart` then set `"type":  ""`
2 + 3: those features are not available at FluxNews this version. You can send a request for them by dropping an email at support@inspireui.com. If there are a certain number of users wish to have the same, we will upgrade in the next update. 
4. In the meantime, we have yet released Tutorial video for Apple Signin. However, there are several online guides that can help you through: [Apple Developer Guide](https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_rest_api/authenticating_users_with_sign_in_with_apple)  or [Apple Authentication Package ](https://pub.dev/packages/apple_sign_in#-readme-tab-)
5. Currently, OneQuarterImageType could support display 1 video per page only. Hope you could find another way to work around your requirements. 

Let me know if you still have any questions.
Happy coding!

**Comment by dttrung26** [comment]
Close due to no response from customer.
