### ISSUE TITLE
App restarting while trying  buy-now

### ISSUE THREAD

**Issue by akhilandraj** [inspireui/support#4051]
Please refer the ticket #3846  for the details

HI, Please check the app from the playstore

https://play.google.com/store/apps/details?id=com.bompixmori.wareroot

I am not able to do buy-now. Could you please help. This is just the same code, no customization has made.😊

**Comment by minhtruong315** [comment]
@akhilandraj can u send me full your source code via email: minhtruong315@gmail.com
Ping me when you sent.
Thanks

**Comment by akhilandraj** [comment]
Hi,

Please find the source code attached. Please let me know for any questions,

Thank You
Regards,
Akhil
 Source.zip
<https://drive.google.com/file/d/1uqCnpqBDPCTKXgKAhEcMVx3Yunezw2FS/view?usp=drive_web>

**Comment by minhtruong315** [comment]
@akhilandraj pls accept the permission

**Comment by akhilandraj** [comment]
Its done, Thank You

**Comment by minhtruong315** [comment]
Hi @akhilandraj i checked your source code. it doesn't crash when click Buy Now
[magento.mov.zip](https://github.com/inspireui/support/files/4878199/magento.mov.zip)

**Comment by akhilandraj** [comment]
could you please create an signup and try to make a purchase of any
product, till now I am not able to make any as buy-now do not work. Are you
using the magento install mentioned in the code? I am actually stuck with
this from a long time. never faced such issue with ready to use application
before.

Regards,
Akhil Raj

**Comment by akhilandraj** [comment]
Hi,

Did you get a chance to check the app? Please let me know. Thank You

Regards,
Akhil Raj

**Comment by minhtruong315** [comment]
can u send me teamviewer? I help you check.

**Comment by akhilandraj** [comment]
Hi, I will only be available after 3 hours? Please let me know  a good time
to connect after that, I can be available by then. Thank you

Regards,
Akhil Raj

**Comment by minhtruong315** [comment]
Can u give me your skype? I will ping you after 3 hours

**Comment by akhilandraj** [comment]
HI,

Sorry for the late reply. Please find my skype ID below,

support@wpprob.com

Regards,
Akhil Raj

**Comment by akhilandraj** [comment]
HI,

Good Morning!

Please could help me to sort this out, I am stuck nowhere !!!

Regards,
Akhil Raj

**Comment by minhtruong315** [comment]
Hi @akhilandraj I messaged you on the skype, pls check
Thanks

**Comment by minhtruong315** [comment]
There is limitation from current mstore app that does not restrict the country/state which is required to complete the checkout process, if you select the wrong state/country the checkout will be fail - we have noted as feature upgrade and report to the team to fix it later - thank you!
