### ISSUE TITLE
Image not show  but it will show when check out    Fluxstore multi vendor

### ISSUE THREAD

**Issue by teeramail** [inspireui/support#4052]
Image not show  but it will show when check out
![107179519_203098520995157_1203866799388399649_n](https://user-images.githubusercontent.com/44755428/86505264-92243780-bdec-11ea-8c05-697f4411369f.png)
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
![107196760_584559078919542_1424956387488712104_n](https://user-images.githubusercontent.com/44755428/86505266-93556480-bdec-11ea-85af-b6f390c51afe.png)
![106298993_630859111117990_412314890531691954_n](https://user-images.githubusercontent.com/44755428/86505267-94869180-bdec-11ea-80c0-a7d8a97f29b5.png)

+ Product & version:
+ Flutter  version:  1.17.4
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by teeramail** [comment]
and can not login as vendor name

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
verified

**Comment by ameenbadri7** [comment]
please send us your `lib\common` and `lib\config ` to our privet email: `minhcasi@gmail.com` 
`inspireui-team@inspireui.com`.
so we can investigate about your problem.

**Comment by ameenbadri7** [comment]
please send us your `lib\common` and `lib\config ` to our privet email: `minhcasi@gmail.com` 
`inspireui-team@inspireui.com`.
so we can investigate your problem.
<img width="960" alt="Untitled" src="https://user-images.githubusercontent.com/37524186/86513491-5d77a680-be13-11ea-94f9-f3953a3ec912.png">

**Comment by teeramail** [comment]
sent   Thank you

**Comment by ameenbadri7** [comment]
sir, @ you, have sent us the default file could you add your website inside 
`lib\common\config.dart` also config your website and then try again. or send us 
`lib\common` and `lib\config`

thank you for your patience.

**Comment by teeramail** [comment]
sorry I send the wrong one this is the one that i run code Thank you

‪On Mon, Jul 6, 2020 at 1:43 AM ‫amin badri أمين بدري‬‎ <
notifications@github.com> wrote:‬

**Comment by teeramail** [comment]
[image: image.png]


My regenerate thumbnail not generate xxx - medium.jpg how can i fix

**Comment by teeramail** [comment]
this is my update one cancel the previous one thank you

**Comment by teeramail** [comment]
look like it work now

**Comment by teeramail** [comment]
thank you
