### ISSUE TITLE
[FluxStore WooCommerce 1.7.5] All products not shown, Deeplink

### ISSUE THREAD

**Issue by IamJAX** [inspireui/support#4053]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 

1. The see all link in product carousel on home screen doesn't show all products. I can see all products on category page.
2. How do I setup deeplink? I have changed the android:host. What other changes should I make?

+ Product & version: FluxStore Woocommerce 1.7.5

+ Flutter (or React Native) version: Flutter 1.17.5

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**
Submitted with Ticket #3605

Thank you so much for your time 😊

**Comment by ameenbadri7** [comment]
hello, @IamJAX Welcome back.

could you give us detail screenshots about your issue?

**Comment by IamJAX** [comment]
![image](https://user-images.githubusercontent.com/66655/86507269-948a8f80-bdf4-11ea-99da-70c244a601e1.png)
Suppose the fish category have 25 products. If you click see all button, it just shows 8 products shown in carousel and not all the products in the category.

**Comment by ameenbadri7** [comment]
please give make sure your from your categories inside the woocommerce website
<img width="960" alt="2" src="https://user-images.githubusercontent.com/37524186/86513600-2c4ba600-be14-11ea-981d-451a9ba985b3.png">

maybe your products are separated in different categories because I haven't seen this problem before.

**Comment by ameenbadri7** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Comment by ameenbadri7** [comment]
Could you help to share your lib/common and lib/config folder to our privet link  http://verify.inspireui.com 
also your website URL 
so that we could help with investigating - thank you!

**Comment by minhtruong315** [comment]
Hi @IamJAX Do you have my skype? pls ping me on the skype

**Comment by IamJAX** [comment]
OK. will ping on skype. Want to know how deep link works.

**Comment by minhtruong315** [comment]
@IamJAX how about deep link? I dont see any response on the skype.
