### ISSUE TITLE
Unavailable sizes still showing up

### ISSUE THREAD

**Issue by miskayapp** [inspireui/support#4055]
Unavailable sizes are showing up and when the user clicks add to cart, it automatically changes to the available ones in their cart. 
![07BFD514-364D-4838-8BA3-CDA0165449B1](https://user-images.githubusercontent.com/64660378/86507544-e7eae680-bdd0-11ea-96b1-d9af4664b8a0.jpeg)

**Comment by minhcasi** [comment]
Duplicate of #4013

**Comment by minhcasi** [comment]
pls move your all converstation to the same open ticket support

**Comment by miskayapp** [comment]
Reply me in the old ticket then
