### ISSUE TITLE
App Store keeps rejecting Application: Guideline 4.2.2 - Design - Minimum Functionality

### ISSUE THREAD

**Issue by gunero** [inspireui/support#4056]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: My application keeps getting rejected from the App Store. Even tho everything is high quality and unique. 

"Guideline 4.2.2 - Design - Minimum Functionality

We noticed that your app only includes links, images, or content aggregated from the Internet with limited or no native iOS functionality. Although this content may be curated from the web specifically for your users, since it does not sufficiently differ from a mobile web browsing experience, it is not appropriate for the App Store."

There are only three webview items in the application and the app has more than 70 other screens (posts and pages). 

What can I add or do to make the app getting approved?

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
coudl you share the detail screenshot so that we could give some feedback - it could cause by your simple UI that you have put to the ios app - thank you!

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one with full information - thank you for your time!

**Comment by gunero** [comment]
Hi, sorry I was waiting for the replying of Apple. I was doing an appeal to get more information on why they rejected the application.

Here is what they answered:
"Thank you for your response. We appreciate your feedback, however, your app is not in compliance with the App Store Review Guidelines. To clarify, we found that your app does not include enough interactive functionality to be appropriate for the App Store. To resolve this issue, you may revise your app to include additional features that take advantage of the iOS platform and enhance the user experience."

Here is a video of the app:
[https://youtu.be/EkVMUHHwuP0](url)

Which "interactive functionality" (as described in their answer above) could I implement to get the app approved?

By the way, the app was successfully published on the Google Play Store.
