### ISSUE TITLE
Issue with products featured images

### ISSUE THREAD

**Issue by d7o-ae** [inspireui/support#4057]
Hello, this is the first issue I faced with FluxStore , 
**The Problem is** when the app loads on the screen, the products images are show with different inconsistent sizes, and some products cards show that ugly yellow error (BOTTOM OVERFLOWED BY xx PIXELS) 
![image](https://user-images.githubusercontent.com/46653709/86511015-d53ad680-bdfd-11ea-8653-3ad191668677.png) 
This problem appear in Products layout, "You might also like" products layout, and homepage layout.

** BTW, I installed the Regenerate plugin and regenerated all the thumbnails correctly and configured the recommended settings for media in Wordpress side.
![image](https://user-images.githubusercontent.com/46653709/86511088-5befb380-bdfe-11ea-9100-fffd7ed7e883.png)

Please, how can I fix this?
version: FluxStore-woo 1.7.5
simulator: Nexus 5X (Emulator) - Galaxy Note 10 (Real Device)

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
@tgloc96 - pls help to investigate the issue

**Comment by ameenbadri7** [comment]
could you look to this [ticket ](https://github.com/inspireui/support/issues/3924) as it the same as your issue?
thank you for your patience.

**Comment by tgloc96** [comment]
Hi @d7o-ae 

To fix this, do the following:
- Open lib/config/config_en.json file in the project.
- Change the config type of list from "list" to "pinterest" at field "ProductListLayout"

Example:
"Setting": {
    ...
    "ProductListLayout": "pinterest"
    ...
  }

And we improved the listed product at the next version release `1.7.6` allow add configure for ratio image and information of the product. That means you still can use the property "list" for field "ProductListLayout"  but don't get this error.

Thank you for choosing our product ^^.

**Comment by d7o-ae** [comment]
Hi @tgloc96  .
Thanks for your feedback. I tried the solution u suggested. Actually, the error is gone but the inconsistent sizes issue are still exist.
The solution you suggested made the layout like a masonry layout, not a grid. But, in fact I want the layout as a grid.

so, you mean in the current version I can't use the grid layout (list) and I have to wait the next version that solved this problem, right?

**Comment by tgloc96** [comment]
> Hi @tgloc96 .
> Thanks for your feedback. I tried the solution u suggested. Actually, the error is gone but the inconsistent sizes issue are still exist.
> The solution you suggested made the layout like a masonry layout, not a grid. But, in fact I want the layout as a grid.
> 
> so, you mean in the current version I can't use the grid layout (list) and I have to wait the next version that solved this problem, right?

Yes, we will try to release the next version as soon as possible.

**Comment by minhcasi** [comment]
Fixed on the latest `1.7.6` - thank you!
