### ISSUE TITLE
localization.language null is not an object

### ISSUE THREAD

**Issue by EgyDeveloper** [inspireui/support#4058]
+ Detail Issues: localization.language null is not an object
+ Product & version: MStore (pro folder) 3.9.8
+ Flutter (or React Native) version:  react-native-cli: 2.0.1, react-native: 0.61.5
+ Testing Device/Simulator: Android physical device
+ Screenshot issues 
![Screenshot_20200704-135412 (1)](https://user-images.githubusercontent.com/8605848/86512043-bb4dc380-bdfe-11ea-9bbe-b6e2cc623009.png)

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by EgyDeveloper** [comment]
![Screenshot_30](https://user-images.githubusercontent.com/8605848/86514321-f6a5bd80-be11-11ea-85cb-9867df4affb9.png)

done

**Comment by EgyDeveloper** [comment]
any updates ! still can't run the app because of this error ..

**Comment by luyx2412** [comment]
Hi @EgyDeveloper Please upgrade latest version Mstore 4.0 and please try install again with `yarn` https://yarnpkg.com/ and node version 10.x.x.

Thanks

**Comment by EgyDeveloper** [comment]
all works fine now @luyx2412 
Mstore :  v4.0
node : v 10.20.1

Thanks

**Comment by luyx2412** [comment]
Great!
