### ISSUE TITLE
[MStore Pro] Products Page scroll 

### ISSUE THREAD

**Issue by mkashifrazzaq11** [inspireui/support#406]
**Required Info (please complete the following information):**
 [MStore]
 f8d919b7-3308-4d8c-a454-6b2685fbae9c
(we may not reply if you are not our customer)

**Describe the bug**
i am using mstore 3.7.0 version. my website have 20+ categories. when I open any category which have more then 100+ products if I scroll down to the last products or an certain limit and scroll goes to up. you can watch the problem in this link  https://www.youtube.com/watch?v=mNmPpPyY4a8

**Screenshots**
https://www.youtube.com/watch?v=mNmPpPyY4a8

**Additional context**

[common.zip](https://github.com/inspireui/support/files/2974417/common.zip)

Add any other detail logs about the problem here.
If possible please share your config.js that use for the app setting

**Comment by luyx2412** [comment]
Hi @mkashifrazzaq11 You can read the document and use `getItemLayout` to fix the issue. https://facebook.github.io/react-native/docs/flatlist#getitemlayout

Thanks
