### ISSUE TITLE
Blank screen in the application when putting the URL of my site

### ISSUE THREAD

**Issue by miguelitolaparra** [inspireui/support#4061]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: Blank screen in the application when putting the URL of my site
 BeoNews Pro - React Native mobile app for Wordpress
+ Flutter (or React Native) version: 

react-native-cli: 2.0.1
react-native: 0.60.4

+ Testing Device/Simulator: iPhone X
+ Screenshot issues (drag the file to attach here): 

Hello, I have followed the steps of the documentation and when I change the URL of the App / Common / AppConfig.json file when I refresh the application is left blank.

If I test the application without modifying the URL, it works perfectly in the iOS simulator.

  Another problem is that I can't find a tutorial to learn how to create a Firebase account that is correct for this application.

  Can you help me?

  I have reviewed the documentation several times, I have reviewed the Frequently Asked Questions, but I cannot find a solution to my problem.

  Should I install WooCommerce for the BeoNeows app?
Thank you

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

<img width="458" alt="Captura de pantalla 2020-07-04 a las 20 09 10" src="https://user-images.githubusercontent.com/28591454/86518426-54e29880-be32-11ea-8ec3-ac325c554e3f.png">

Thank you so much for your time 😊

**Comment by luyx2412** [comment]
Hi @miguelitolaparra I saw your config and the field `categories` is String type without Array. So please make it same the default config.
![image](https://user-images.githubusercontent.com/8909619/86602421-cf472000-bfcc-11ea-927d-da02739c6525.png)
![image](https://user-images.githubusercontent.com/8909619/86602407-cce4c600-bfcc-11ea-91e2-98e57971d8b6.png)

Thanks

**Comment by miguelitolaparra** [comment]
Thank you very much, the problem was solved.
 I have reviewed the instructions several times, but not doing the
translations correctly causes me problems.
I'm working with a test WP theme, I want to find a suitable WordPress theme
to create a good Kitchen Recipes app, but I don't know which one to choose.

You already have experience with other clients and maybe you can tell me
about something
Should I open a new question for this, or can't you help me?

Thank you

**Comment by luyx2412** [comment]
Hi @miguelitolaparra Sorry i dont have many experiences about the theme wordpress. You can search on the themeforest about it.

- Can you describe the translation issue?

**Comment by miguelitolaparra** [comment]
> * ¿Puedes describir el problema de traducción?
Hi.

I'm just looking for a Cooking Recipes WordPress theme that's suitable for this app.

Don't worry, I'll search the Envato market.
My problem is that I don't know how to create a project in Firebase for this application, as described in this section:
https://docs.inspireui.com/beonews/firebase-setting/

Can you tell me the steps to follow to create a Firebase project?
Can you show me a site where I can learn how to create a Firebase project for this application?
Thank you por su apoyo @luyx2412

**Comment by luyx2412** [comment]
Hi @miguelitolaparra This is the guide to create firebase project http://mariechatfield.com/tutorials/firebase/step1.html. Please read and follow the article.

Thanks
