### ISSUE TITLE
Mstore Pro : Error in wordpress Admin after installing Mstore API WP plugin

### ISSUE THREAD

**Issue by mesbahiayoub** [inspireui/support#4062]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues:  I run the app on IOS simulator and its working fine, but when changed the config.js file the images didn't appear and couldn't login into the app , so i tried installing the  Mstore API WP plugin like it says on the documentation : https://docs.inspireui.com/mstore/wordpress-setting/
When i tried entring the purchase code on the plugin page to activate it, i kept getting this error : 
`Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'duplicator_global_scripts' not found or invalid function name in /var/www/webroot/ROOT/wp-includes/class-wp-hook.php on line 287

Fatal error: Uncaught Error: Call to undefined function wc_get_notices() in /var/www/webroot/ROOT/wp-content/plugins/minmax-quantity-for-woocommerce/main.php:710 Stack trace: #0 /var/www/webroot/ROOT/wp-content/plugins/minmax-quantity-for-woocommerce/main.php(624): BeRocket_MM_Quantity->new_calculate_total(NULL) #1 /var/www/webroot/ROOT/wp-includes/class-wp-hook.php(287): BeRocket_MM_Quantity->fix_error_duplicate('') #2 /var/www/webroot/ROOT/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array) #3 /var/www/webroot/ROOT/wp-includes/plugin.php(478): WP_Hook->do_action(Array) #4 /var/www/webroot/ROOT/wp-includes/general-template.php(2884): do_action('wp_head') #5 /var/www/webroot/ROOT/wp-content/plugins/mstore-api/templates/mstore-api-admin-page.php(9): wp_head() #6 /var/www/webroot/ROOT/wp-includes/template.php(723): require_once('/var/www/webroo...') #7 /var/www/webroot/ROOT/wp-content/plugins/mstore-api/mstore-api.php(171): load_template('/var/www/webroo...') #8 /var/www/webroot/ROOT/wp-includes/class-wp in /var/www/webroot/ROOT/wp-content/plugins/minmax-quantity-for-woocommerce/main.php on line 710
There has been a critical error on your website. Please check your site admin email inbox for instructions.`

+ Product & version: MStore Pro - Complete React Native template for e-commerce 4.0.0 

+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by mesbahiayoub** [comment]
Hello,

I was able to activate the plugin by uninstalling another plugin, but the problem persists, images do not appear.

**Comment by minhcasi** [comment]
@mesbahiayoub - please help to check if you have updated the mstore-api to latest release - thank you!

**Comment by minhtruong315** [comment]
@mesbahiayoub can u send me admin info via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/4062
Thanks

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
