### ISSUE TITLE
Login, vendor product page, thumbnails - Issues. price filter, hide attribute, sort by price - Feauters | Fluxstore Multivendor

### ISSUE THREAD

**Issue by omarijbara** [inspireui/support#4065]
Issues:
1) Login, sign up and settings issue: keep loading! After changing the Package name and putting google-services.json from firebase.
Login and sign up are showing just loading no result, and after go back to setting menu it just shows logout there is no change personal info or post a new product for vendors.
https://prnt.sc/tc0msk
https://prnt.sc/tc0mtr
2) Vendor product page is showing the same products repeatedly https://prnt.sc/tc0bo6
3) some product Images are bigger than the another also after using regenerate thumbnails plugin.

Features:
1) Turning the price filter in category Filter from swipe line to from and to input box (https://prnt.sc/tbzku9)
2) Adding sort by Price (low to high - high to low) (https://prnt.sc/tc0qne)
3) remove Attributes from Search Filter and Category Filter ( https://prnt.sc/tbzidb https://prnt.sc/tbzihc )

**Comment by minhtruong315** [comment]
@omarijbara send me full your source code via email: minhtruong315@gmail.com
ping me when you sent.
Thanks

**Comment by omarijbara** [comment]
Done! @minhtruong315

**Comment by minhtruong315** [comment]
Hi @omarijbara can u help me zip source code? I can't unrar.
Thanks

**Comment by omarijbara** [comment]
Done! @minhtruong315

**Comment by Shopyloot** [comment]
### **Even i am having same problem** 

1.Vendor product page is showing the same products repeatedly >> Check My Screen Shot >>>>> https://prnt.sc/td0fzt

### **Features:**
**Need as it is** 
Turning the price filter in category Filter from swipe line to from and to input box (https://prnt.sc/tbzku9)
Adding sort by Price (low to high - high to low) (https://prnt.sc/tc0qne)
remove Attributes from Search Filter and Category Filter ( https://prnt.sc/tbzidb https://prnt.sc/tbzihc )

**Comment by minhtruong315** [comment]
Hi @omarijbara give me your skype. I will contact and support you via skype.
Thanks

**Comment by omarijbara** [comment]
> Hi @omarijbara give me your skype. I will contact and support you via skype.
> Thanks

 #Alright , live:omarijbara

**Comment by minhtruong315** [comment]
Hi @omarijbara I messaged you on the skype. pls check
Thanks

**Comment by minhtruong315** [comment]
Please follow this video to recreate firebase project and check your issues again. 
https://www.youtube.com/watch?v=C_9mk_MmvOQ&t=605s
Let me know if you have any issues
