### ISSUE TITLE
order number wont show after order is placed openacart rest api

### ISSUE THREAD

**Issue by umargigani** [inspireui/support#4066]
Ive already Raised This ticket #3396 
but after your suggested fix it wont work it still says order id is 0
attaching new screenshot 
FluxStore Pro version 1.7.5 – 05 Jun 2020

![order-id-issue](https://user-images.githubusercontent.com/22342007/86526001-f4903d00-beab-11ea-91d9-5c9dee44311d.png)

---------------------------------------------------------------------------------------------------------------------

And 2nd issues is when i try to update anything from app settings it throw this error

![update-order](https://user-images.githubusercontent.com/22342007/86526010-0b369400-beac-11ea-90b2-bce8e2c13d71.png)

**Comment by minhtruong315** [comment]
@umargigani can u give me your email? I will send you the latest MStore extension
Thanks

**Comment by umargigani** [comment]
umargigani@gmail.com

i already tried that stilll not working

**Comment by minhtruong315** [comment]
Hi @umargigani I sent you the latest mstore extension. pls reinstall. and check zero order id
sorry the current edit profile is not support for opencart, we have noted as feature request and upgrade it later
