### ISSUE TITLE
> @ekramul-1 - it's working fine with our testing, please try to remove the previous app on simulator and try to install again.

### ISSUE THREAD

**Issue by ekramul-1** [inspireui/support#4067]
> @ekramul-1 - it's working fine with our testing, please try to remove the previous app on simulator and try to install again.
> 
> Sometimes you need to run `flutter clean` to clean up the caching - thank you!

All I tried but unable to found any solution, could you please send me the next version.

_Originally posted by @ekramul-1 in https://github.com/inspireui/support/issues/3956#issuecomment-653359917_

**Comment by ekramul-1** [comment]
> > @ekramul-1 - it's working fine with our testing, please try to remove the previous app on simulator and try to install again.
> > Sometimes you need to run `flutter clean` to clean up the caching - thank you!
> 
> All I tried but unable to found any solution, could you please send me the next version.
> 
> _Originally posted by @ekramul-1 in [#3956 (comment)](https://github.com/inspireui/support/issues/3956#issuecomment-653359917)_

@minhcasi **### Please have a look into this issues.**
### When next version will be release.

**Comment by ekramul-1** [comment]
# Any updates****

**Comment by minhcasi** [comment]
@ekramul-1 - we will upload latest build on gitlab today - thank you!

**Comment by ekramul-1** [comment]
# ****Okay sir, may I get in registered email or if you could let me the process of getting from GitHub.****@minhcasi

**Comment by minhcasi** [comment]
@ekramul-1 - pls share your gitlab email here or you could request to http://gitlab.inspireui.com - thank you!

**Comment by ekramul-1** [comment]
![image](https://user-images.githubusercontent.com/63785688/86714654-081edd80-c03d-11ea-911c-abf79461a6f2.png)
### Envato user is - ekramul_official
Gitlab email - ekramul.2@gmail.com

**Comment by ekramul-1** [comment]
> ![image](https://user-images.githubusercontent.com/63785688/86714654-081edd80-c03d-11ea-911c-abf79461a6f2.png)
> 
> ### Envato user is - ekramul_official
> Gitlab email - [ekramul.2@gmail.com](mailto:ekramul.2@gmail.com)

@minhcasi

**Comment by ekramul-1** [comment]
@minhcasi 
Could you please send me in my email either please upload.

**Comment by ekramul-1** [comment]
@minhcasi @vumanhsn97 
Please have a look into the issue

**Comment by minhcasi** [comment]
it's updated requet

**Comment by ekramul-1** [comment]
**Full update not yet delivered in gitlab.com**

**Comment by ekramul-1** [comment]
### Still the issue is showing same ?
@minhcasi Now feel very much frustrated as I am requesting from long time to solve this issue but no response from you & your team. Tell me what I need to do ?

All the export is showing error, app is working but issue is highlighting. It's a long time issue but unable to rectify from long time again again.

Please try to solve this problem as posted above pics or if the export is not an issue then let me know as well.
@minhcasi 
![image](https://user-images.githubusercontent.com/63785688/87223308-5879a080-c399-11ea-9157-73218d73c60e.png)

**Comment by ekramul-1** [comment]
> ### Still the issue is showing same ?
> @minhcasi Now feel very much frustrated as I am requesting from long time to solve this issue but no response from you & your team. Tell me what I need to do ?
> 
> All the export is showing error, app is working but issue is highlighting. It's a long time issue but unable to rectify from long time again again.
> 
> Please try to solve this problem as posted above pics or if the export is not an issue then let me know as well.
> @minhcasi
> ![image](https://user-images.githubusercontent.com/63785688/87223308-5879a080-c399-11ea-9157-73218d73c60e.png)

I used flutter clean & then I tried so many times.

**Comment by minhcasi** [comment]
@ekramul-1 - i'm sure there is missing on your config.

Please help to note that, support for this checking is not included from our support scope - https://inspireui.com/support-policies/ - but we will try our best to help with this installing issue.

@minhtruong315 - pls help to remote to resolve this issue - thank you!

**Comment by ekramul-1** [comment]
### Thank you sir @minhcasi  Appreciated for your support & time.

**Comment by minhtruong315** [comment]
Hi @ekramul-1 give me your skype? I will help you check the issue via teamviewer.
Thanks

**Comment by minhcasi** [comment]
@ekramul-1 - we have just found the root cause, pls try to remove `lib/common` from the `pubspect.yml` to fix the build issue - you could run the `flutter clean`  first

**Comment by ekramul-1** [comment]
> Hi @ekramul-1 give me your skype? I will help you check the issue via teamviewer.
> Thanks

Okay Sir, As per the minhcasi, let me try to remove the above mention process & then I will let you know.

**Comment by ekramul-1** [comment]
Thank you so much, finally it's done.
