### ISSUE TITLE
[MStore Pro] portrait to landscape and vice-versa going to splash screen and starting again 

### ISSUE THREAD

**Issue by lyrathaprinces** [inspireui/support#407]
Product: MstorePro
Your Purchased Code: e1c19d73-87c3-4bee-afb4-9451b95dbc45

hi, app from playstore is going to splash screen and starting again if phone is going to landscape,, same thing if it is turned to portrait from landscape mode,,, tested with 3.7.0 and 3.7.1,,, Question is, is it the actual design or a problem? Please look into it.

**Comment by luyx2412** [comment]
Hi @lyrathaprinces It is not a problem. Because currently we did not support landscape mode. You can disable landscape mode, we will try improve this feature in the future. 

Thanks

**Comment by lyrathaprinces** [comment]
Ok,, why i have asked is,, there are splash screen folders in res ,,, 
Could you plz guide me to disable landscape mode

**Comment by sashaba** [comment]
Hi @lyrathaprinces for android and react native you can disable landscape  registering a lifecycle to force portrait at each activity of your app. place code inside onCreate block.

android/app/main/java/mainApplication
   ```
 registerActivityLifecycleCallbacks(new ActivityLifecycleCallbacks() {
      @Override
      public void onActivityCreated(Activity activity, Bundle bundle) {
        // Here we specify to force portrait at each start of any Activity
        activity.setRequestedOrientation(
                ActivityInfo.SCREEN_ORIENTATION_PORTRAIT);

      }

      @Override
      public void onActivityStarted(Activity activity) {

      }

      @Override
      public void onActivityResumed(Activity activity) {

      }

      @Override
      public void onActivityPaused(Activity activity) {

      }

      @Override
      public void onActivityStopped(Activity activity) {

      }

      @Override
      public void onActivitySaveInstanceState(Activity activity, Bundle bundle) {

      }

      @Override
      public void onActivityDestroyed(Activity activity) {

      }
    });
```
Hope this help.
