### ISSUE TITLE
[FluxStore WooCommerce 1.7.5] All products not shown, Deeplink

### ISSUE THREAD

**Issue by IamJAX** [inspireui/support#4070]
** REOPENED #4053 as there was no response **

**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 

1. The see all link in product carousel on home screen doesn't show all products. I can see all products on category page.
2. How do I setup deeplink? I have changed the android:host. What other changes should I make?

+ Product & version: FluxStore Woocommerce 1.7.5
+ Flutter (or React Native) version: Flutter 1.17.5

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**
Submitted with Ticket #3605

Thank you so much for your time 😊

**Comment by ameenbadri7** [comment]
hello @IamJAX  ,
Could you help to share your lib/common and lib/config folder to our privet link  http://verify.inspireui.com 
also your website URL 
so that we could help with investigating - thank you!

**Comment by IamJAX** [comment]
I will post it in a few hours.

**Comment by IamJAX** [comment]
If I pull to refresh on top of the page, it loads all. But by default It is not loading all products even when u scroll down. Any idea why?

**Comment by IamJAX** [comment]
Also, can you please help me out with second issue?

How do I setup deeplink? I have changed the android:host. What other changes should I make?

**Comment by ameenbadri7** [comment]
please consider deleting your comments and make them inside one comment so we can help.
[our free services are limit as you know](https://inspireui.com/support-policies).  so if you have customization on you app you can use the awesome `Support Pack`. 
please let us know if you still having problems with your demo app. so we can help.
thank you.

**Comment by IamJAX** [comment]
I have updated the comments


Can you explain how the deeplink works in demo app?

**Comment by ameenbadri7** [comment]
Start to read the documentations 
https://docs.inspireui.com/fluxstore/customization/

You will find allot of information about the fluxstore, and all you three questions answer's.

**Comment by IamJAX** [comment]
I have already gone through the documentation. Only mention of deep link in it is just a command on how to test it .

**Comment by ameenbadri7** [comment]
We wanted to thank you for your patience during this busy time.

pls help to check our [support policies ](https://inspireui.com/support-policies)
we don't take customization requests for the regular license but you can buy the [Extended License](https://inspireui.com/support-policies) or Support Pack and email us with your request via our email minhcasi@gmail.com and inspireui-team@inspireui.com.
