### ISSUE TITLE
FluxNews build failed iOS

### ISSUE THREAD

**Issue by admincode1** [inspireui/support#4071]
Hi,

I received a bitcode error while building/archiving my app in xcode. Please see screenshots:

![image](https://user-images.githubusercontent.com/67590385/86541944-ef69d700-bf19-11ea-83a4-295d04db89b8.png)

![image](https://user-images.githubusercontent.com/67590385/86541950-f690e500-bf19-11ea-8e26-00087261ca92.png)

* FluxNews 1.4.1.

* Flutter 1.17.4
   Dart 2.8.4

* Testing Device/Simulator: iPhone 11 / Generic iOS device.

**Comment by minhcasi** [comment]
@admincode1 - pls help us to raise the comment to the same open-ticket #4063
