### ISSUE TITLE
More fields from woocommerce extentions in the checkout part

### ISSUE THREAD

**Issue by easieber** [inspireui/support#4072]
Currently, we use an extension from woocommerce so the people can select date and times for their delivery and this is really important for us. (https://woocommerce.com/products/woocommerce-order-delivery/), therefore I would like to know how can I add these fields to be visible in the app too.

you can check that in our store we have this delivery field: https://tropimarkt.com/kasse/

<img width="1454" alt="Screenshot 2020-07-06 at 00 35 49" src="https://user-images.githubusercontent.com/35961470/86543639-baad4e00-bf20-11ea-9cf0-b05f994d59ab.png">

How can we add them to be fetched automatically from the website?

**Comment by ameenbadri7** [comment]
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/
 - please don't share the purchase code or screenshot public here as another user will use it for activation.
We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

The feature you've just requested sounds great, I have to say that. However, this belongs to the customization service. If you really in need of that feature, please contact our tech lead via minh@inspireui.com and declare your request. If our team are available, we could discuss this feature deeper later on

**Comment by easieber** [comment]
Good day, Thank you for the quick answer!.

I already fill and send your form. The folders that you requested, I sent them as original because I didn't start to work with the app yet. I just read your documentation and noticed that there is nothing related to these fields yet, and trying the Fluxbuilder I could see that I don't get these fields in the checkout part, but the rest yes.

Thank you for your help!

**Comment by minhcasi** [comment]
@easieber  - could you try to use this option EnableOnePageCheckout: true to enable one page checkout that could load the delivery option from the checkout screen

**Comment by easieber** [comment]
@minhcasi Where should I set that?

**Comment by minhcasi** [comment]
it's from the config folder - thanks

<img width="924" alt="Screen Shot 2020-07-08 at 09 54 53" src="https://user-images.githubusercontent.com/1459805/86869614-13d3d800-c101-11ea-89f6-8dfe9f0bb54b.png">
