### ISSUE TITLE
change order status when complete the order

### ISSUE THREAD

**Issue by effec-tline** [inspireui/support#4073]
when order completed on the app   it be on woocomerce panel status (on hold)

we need when customer complete the order be on status ( processing) automaticaly

how we do it?

roduct & version: FluxStore 1.7.5
Flutter (or React Native) version: Flutter 1.17.3-stable
Testing Device/Simulator: android studio last version / simulator nexus 6

Step 2: Please verify license and sharing config files by submitting on this google form, http://verify.inspireui.com, (done )

**Comment by minhcasi** [comment]
@effec-tline - you could try to enable this option to `true`

<img width="824" alt="Screen Shot 2020-07-06 at 09 12 52" src="https://user-images.githubusercontent.com/1459805/86549109-e05e4580-bf68-11ea-8340-a0ca839be73f.png">

**Comment by effec-tline** [comment]
ok thanks solved

**Comment by ameenbadri7** [comment]
@effec-tline 
**We're glad that it helps,** 😊
please give us some feedback/rating to [this page](https://codecanyon.net/downloads), 
we are working hard to update more awesome and powerful features on the next coming version release. 
Let us know if you have any feedback. 
Thank you very much ❤️
