### ISSUE TITLE
Dynamic Pirce based on role 

### ISSUE THREAD

**Issue by macquack** [inspireui/support#4075]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
I wondering the app can be show price based on user role login?. on my website have 5 role.It's work fine on my website and checkout webview on app. it's possible to show price based on user role on product page or summary page.
+ Product & version:1.7.4
+ Flutter (or React Native) version: 1.7.1
+ Testing Device/Simulator: Nexus 2
+ Screenshot issues (drag the file to attach here): 
![image](https://user-images.githubusercontent.com/30103694/86554317-7731fe80-bf77-11ea-97a4-f387a0552164.png)
![image](https://user-images.githubusercontent.com/30103694/86554331-83b65700-bf77-11ea-8912-6f95e0577f69.png)
![image](https://user-images.githubusercontent.com/30103694/86554348-8f098280-bf77-11ea-84e5-f5aa4b9203f1.png)
![image](https://user-images.githubusercontent.com/30103694/86554632-63d36300-bf78-11ea-9786-1390518af739.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**
Done

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@macquack - sorry this feature is not available form the app. 

Our suggestion solution: you could check the return API from the product to apply a new price for reach Role.
