### ISSUE TITLE
fluxnews google login, sms login error

### ISSUE THREAD

**Issue by HoWonJang** [inspireui/support#4077]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 
![인증](https://user-images.githubusercontent.com/49952957/86563096-bcb5f200-bf9e-11ea-84af-5a6fe4f850b7.PNG)

![error login](https://user-images.githubusercontent.com/49952957/86562264-61373480-bf9d-11ea-830e-5b544a047d6a.jpg)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

When testing the app (real device), Google Login and SMS Login work well.
But when I try to login after I actually launch the app, there's an error like a screenshot.
[settting screen shot.zip](https://github.com/inspireui/support/files/4877135/settting.screen.shot.zip)
I followed docs exactly well.
What should I do?
thank you :)

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@HoWonJang - pls help to check this solution #3151
