### ISSUE TITLE
How fluxstore "my point" working with magento point?

### ISSUE THREAD

**Issue by alan9501** [inspireui/support#4078]
Detail Issues: 
I like to know How fluxstore "my point" working with magento point?

Product & version:
Fluxstore Pro
Magento 2.3.5

Flutter (or React Native) version:
Flutter 1.17.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 1ad9baa8b9 (2 weeks ago) • 2020-06-17 14:41:16 -0700
Engine • revision ee76268252
Tools • Dart 2.8.4

Testing Device/Simulator:
Simulator

**Comment by minhcasi** [comment]
sorry the point is only compatible on Woocommerce, it will not work on Magento 

Pls also move your all further comment to this open ticket #4002 - thank you!
