### ISSUE TITLE
Customize card product

### ISSUE THREAD

**Issue by bananweb** [inspireui/support#4079]
hi, i need to customize card product by adding counter to card so that users can control products quantity without open product page like this

![image](https://user-images.githubusercontent.com/48653804/86564124-f4547800-bf65-11ea-8975-ca6c07a228da.png)

addition button is working well, but remove method doesn't work 
And I can't reach to its function details to know where is the problem

this is the code we wrote in product_card_view.dart

![image](https://user-images.githubusercontent.com/48653804/86565800-d0466600-bf68-11ea-93e9-2429d3e5d762.png)
![82d4079f-97cb-46f0-9007-4baa295b0f40](https://user-images.githubusercontent.com/48653804/86566662-4e573c80-bf6a-11ea-9f54-b036ee50dd4a.jpg)

**Comment by minhcasi** [comment]
We sincerely apologize for the issue as it is related to the customization that will not include from our support scope. 

But let me note this request as new Feature and assign to the team for further investigating 👍

**Comment by minhcasi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [UI: add + and - Icon button](https://trello.com/c/YjKoFfnZ/62-ui-add-and-icon-button)
