### ISSUE TITLE
Payumoney image missing in select payment method

### ISSUE THREAD

**Issue by lyrathaprinces** [inspireui/support#408]
Product: MstorePro
Your Purchased Code: e1c19d73-87c3-4bee-afb4-9451b95dbc45

PayUmoney image is missing inspite of providing image in Config.js, only box appearing.
Plese see this: https://drive.google.com/open?id=1omrQSSlxx_7IcJyIWzUFRDMGn2F7QzhU

Other methods are working fine,,,i tried with razorpay/ paypal images,,, no luck
Am i missing anything?

**Comment by luyx2412** [comment]
Hi @lyrathaprinces You can add image in Config.js file look like the image. Please add Payumoney or other payment in there. Make sure your image name right follow on your website.
![image](https://user-images.githubusercontent.com/8909619/54575825-3fbcdd00-4a28-11e9-9033-5c3cff01e010.png)

Thanks

**Comment by lyrathaprinces** [comment]
Dont understand, plz see the images,,, razorpay is fine,, problem with payumoney,, only box is showing ,, no image,,,
Assume that i had no image, PayUMoney.png,,, even i tried with working razorpay.png also,,
Any idea?

![Config](https://user-images.githubusercontent.com/48007083/54607092-8257d700-4a73-11e9-9171-7601f4134f79.PNG)
![payu_Woo](https://user-images.githubusercontent.com/48007083/54607093-82f06d80-4a73-11e9-887e-0479cbe0d913.PNG)

**Comment by luyx2412** [comment]
HI @lyrathaprinces you can use the debug tools to see your payment api which help you set the name image right. https://docs.mstore.io/api-and-project-structure#debug-app-with-reacttotron

Thanks

**Comment by lyrathaprinces** [comment]
Thanks, let me try that

**Comment by lyrathaprinces** [comment]
So,, here is the thing,,, you can close the issue....
First thing, I have struggledto debug with Reactrotron on a physical device because for some reason i couldn't use Emulator.
I tried trial and error with payumoney keyword,, finally it worked with "payu",,,

But before closing could you please guide me to debug on physical device instead of emulator,, Thanks

**Comment by luyx2412** [comment]
Hi @lyrathaprinces You can use Reactotron on physical device, you can read the article to know https://github.com/infinitered/reactotron/issues/216#issuecomment-254779275. Or using react-native-debugger https://github.com/jhen0409/react-native-debugger/blob/master/docs/debugger-integration.md#ios-only-force-your-app-on-debug-mode

Thanks
