### ISSUE TITLE
The purchase code is incorrect string(94) "{"error":"Please fill the Email and App Name, also update to the latest Fluxbuilder release!"}"

### ISSUE THREAD

**Issue by Abdullajaafar** [inspireui/support#4080]
I have once a problem in WordPress plugin mstore API  and I'm  already activation code on flux builder its work,  please give me the solution for that rest my code or anything for activation

The purchase code is incorrect string(94) "{"error":"Please fill the Email and App Name, also update to the latest Fluxbuilder release!"}"

**Comment by minhcasi** [comment]
@minhtruong315 - pls help to check this verify code issue on mstore-api

**Comment by minhtruong315** [comment]
Hi @Abdullajaafar can u send me admin info via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/4080
Thanks

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
