### ISSUE TITLE
Fluxstore upgrading by Gitlab

### ISSUE THREAD

**Issue by investisocial** [inspireui/support#4082]
Hi,
about the endless scrolling issue, you told me that I have to upgrade the fluxstore project to the last version by git.
I need the access authorization to gitlab.
How can I get it?
Can you help me, please?
I need to upgrade fluxstore to solve last issues.
Thank you.
Regards
Carlo

![envato_panel](https://user-images.githubusercontent.com/57216890/86583167-1dcfcc80-bf83-11ea-8c0e-89e6d64a4c16.jpg)

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@inspireui/team - pls help to submit on this form - http://gitlab.inspireui.com with your gitlab email - thank you!

**Comment by investisocial** [comment]
Done, thank you.

**Comment by investisocial** [comment]
What have I now to do?

**Comment by investisocial** [comment]
Hi, can I get access to gitlab? I still don't have it. I regularly sent the subscription.

**Comment by investisocial** [comment]
Hi,
how can I translate the order status in Italian, please?

![order_status_Translating](https://user-images.githubusercontent.com/57216890/86957271-c6845480-c15a-11ea-9832-aa1e2df060de.jpg)

Thank you for your time.

**Comment by minhcasi** [comment]
@investisocial - it will take some time to update all GitLab request, you will get email notify soon.

you could hard-code the Label from Order screen as this text could not translate from woocommerce side

**Comment by investisocial** [comment]
> @investisocial - it will take some time to update all GitLab request, you will get email notify soon.
Ok, thank you 


> you could hard-code the Label from Order screen as this text could not translate from woocommerce side
How can I do it, please?

**Comment by minhcasi** [comment]
@investisocial - did you get the invite gitlab? Thank  you!

**Comment by investisocial** [comment]
> @investisocial - hai ricevuto l'invito gitlab? Grazie!

Yes, thank you. I've downloaded the latest version. I've fixed the endless page product issue. Thank you.
Can you tell me, please, how can I translate the "processing" voice into the order status?
Thank you.
Regards
Carlo

**Comment by investisocial** [comment]
@minhcasi I've to build an app for a restaurant/pub, with menu, booking and food delivery. Can you help me to find a solution please? Can I use fluxstore pro? I don't need a listing app, it's only one restaurant.
Thank you for your time.
Regards
Carlo

**Comment by minhcasi** [comment]
@investisocial - thank you so much for your quick response 

1. You could try to hard code to check the `processing` status - example check the label and convert to your own language - https://tppr.me/b5nLh

2. We are in the middle to develop the module to integrate with this booking - https://bookingwp.com/plugins/woocommerce-appointments/ if you are interested, please email us to get the favorite price.

Please note that we may not support answering some technical questions for the regular license as per support policies - https://inspireui.com/support-policies/ - but we are trying to best to give extra miles with the supporting. 
Allow us to close the conversation on this ticket, let us know if you need any questions. Hope you enjoy the product and stay safe 😊

**Comment by investisocial** [comment]
Hi,
Thank you for your reply.
I’m interested to the new booking integration.
How can i have it?
Regards

Carlo


Digital Media Agency
www.investisocial.it
___________________________

-----------------------------------------------------
Questa email è stata inviata dal sito InvestiSocial.it (https://www.investisocial.it)
Non stampare questa e-mail.

Questo documento è formato esclusivamente per il destinatario. Tutte le informazioni ivi contenute, compresi eventuali allegati, sono da ritenere esclusivamente confidenziali e riservate secondo i termini del vigente D.Lgs. 196/2003 in materia di privacy e del Regolamento europeo 679/2016 – GDPR-  e quindi ne è proibita l’utilizzazione ulteriore non autorizzata. Se avete ricevuto per errore questo messaggio, Vi preghiamo cortesemente di contattare immediatamente il mittente e cancellare la e-mail. Grazie.
Please don’t print this e-mail.
Confidentiality Notice – This e-mail message including any attachments is for the sole use of the intended recipient and may contain confidential and privileged information pursuant to Legislative Decree 196/2003 and the European General Data Protection Regulation 679/2016 – GDPR-. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail and destroy all copies of the original message.

**Comment by minhcasi** [comment]
this is a new module that we will sell as an extra component - we will notify when it is ready in the next 1-2 week - thank you!

**Comment by investisocial** [comment]
Ok thank you. Write me when it will be ready.
Regards
Carlo


Digital Media Agency
www.investisocial.it
___________________________

-----------------------------------------------------
Questa email è stata inviata dal sito InvestiSocial.it (https://www.investisocial.it)
Non stampare questa e-mail.

Questo documento è formato esclusivamente per il destinatario. Tutte le informazioni ivi contenute, compresi eventuali allegati, sono da ritenere esclusivamente confidenziali e riservate secondo i termini del vigente D.Lgs. 196/2003 in materia di privacy e del Regolamento europeo 679/2016 – GDPR-  e quindi ne è proibita l’utilizzazione ulteriore non autorizzata. Se avete ricevuto per errore questo messaggio, Vi preghiamo cortesemente di contattare immediatamente il mittente e cancellare la e-mail. Grazie.
Please don’t print this e-mail.
Confidentiality Notice – This e-mail message including any attachments is for the sole use of the intended recipient and may contain confidential and privileged information pursuant to Legislative Decree 196/2003 and the European General Data Protection Regulation 679/2016 – GDPR-. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail and destroy all copies of the original message.

**Comment by investisocial** [comment]
Hi,
Any news about booking implementation?
Thank you.
Regards
Carlo


Digital Media Agency
www.investisocial.it
___________________________

-----------------------------------------------------
Questa email è stata inviata dal sito InvestiSocial.it (https://www.investisocial.it)
Non stampare questa e-mail.

Questo documento è formato esclusivamente per il destinatario. Tutte le informazioni ivi contenute, compresi eventuali allegati, sono da ritenere esclusivamente confidenziali e riservate secondo i termini del vigente D.Lgs. 196/2003 in materia di privacy e del Regolamento europeo 679/2016 – GDPR-  e quindi ne è proibita l’utilizzazione ulteriore non autorizzata. Se avete ricevuto per errore questo messaggio, Vi preghiamo cortesemente di contattare immediatamente il mittente e cancellare la e-mail. Grazie.
Please don’t print this e-mail.
Confidentiality Notice – This e-mail message including any attachments is for the sole use of the intended recipient and may contain confidential and privileged information pursuant to Legislative Decree 196/2003 and the European General Data Protection Regulation 679/2016 – GDPR-. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail and destroy all copies of the original message.

**Comment by investisocial** [comment]
Hi,
any news about booking implementation?
Thank you..
Regards
Carlo


Digital Media Agency
www.investisocial.it
___________________________

-----------------------------------------------------
Questa email è stata inviata dal sito InvestiSocial.it (https://www.investisocial.it)
Non stampare questa e-mail.

Questo documento è formato esclusivamente per il destinatario. Tutte le informazioni ivi contenute, compresi eventuali allegati, sono da ritenere esclusivamente confidenziali e riservate secondo i termini del vigente D.Lgs. 196/2003 in materia di privacy e del Regolamento europeo 679/2016 – GDPR-  e quindi ne è proibita l’utilizzazione ulteriore non autorizzata. Se avete ricevuto per errore questo messaggio, Vi preghiamo cortesemente di contattare immediatamente il mittente e cancellare la e-mail. Grazie.
Please don’t print this e-mail.
Confidentiality Notice – This e-mail message including any attachments is for the sole use of the intended recipient and may contain confidential and privileged information pursuant to Legislative Decree 196/2003 and the European General Data Protection Regulation 679/2016 – GDPR-. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail and destroy all copies of the original message.
