### ISSUE TITLE
Reset Purchase Code from blocked domain

### ISSUE THREAD

**Issue by vverbovenko91** [inspireui/support#4085]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
Good day. I need Reset purchase key from blocked domain. Please help.

+ Product & version: Fluxstore WooCommerce - Flutter E-commerce Full App v 1.7.5

+ Flutter (or React Native) version: FLUTTER

+ Testing Device/Simulator: 

+ Screenshot issues (drag the file to attach here): 
![screenshot_06 07 20](https://user-images.githubusercontent.com/6977576/86594980-6e5e1e80-bfb1-11ea-9cdf-ae6d613a578c.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**Comment by minhcasi** [comment]
@vverbovenko91 - it is resetted - pls try again and let us know your checking

**Comment by vverbovenko91** [comment]
Thanks, all done

**Comment by ameenbadri7** [comment]
@vverbovenko91 
We're glad that it helps, 😊
please give us some feedback/rating to [this page](https://codecanyon.net/downloads), 
we are working hard to update more awesome and powerful features on the next coming version release. 
Let us know if you have any feedback. 
Thank you very much ❤️
