### ISSUE TITLE
Inspire ui is running a scam

### ISSUE THREAD

**Issue by Mahir-cloud** [inspireui/support#4086]
I think you making me fool 

I bought mstore pro but File name showing beostore when downloaded from envato

Your cebuilder giving an error 

Expo not working 

React native cli didn't working 

I think you just want money 🤑

What I do with your files when I am struggling to install it from 5 days and the support team is very slow they reply your msg and disappear you have to whait for 24hr 

I request for refund on envato i need mu money back

@minhcasi 

I need money back you make me fool and waste my time and money

For verification if I  am real buyer see my pervious issue id #4036

**Comment by minhcasi** [comment]
@Mahir-cloud - you could refund on this link - https://help.market.envato.com/hc/en-us/articles/202821460-Can-I-Get-A-Refund- - thanks

**Comment by Mahir-cloud** [comment]
I have already requested for refund 3 days back please response.
