### ISSUE TITLE
Facebook login Error

### ISSUE THREAD

**Issue by attare026** [inspireui/support#4088]
Warning: There is an issue with the app during request the data, please contact admin for fixing the issues PlatformException(ERROR_OPERATIO N_NOT_ALLOWED, The given sign-in provider is disabled for this Firebase project. Enable it in the Firebase console, under the sign-in method tab of the Auth section. [ The identity provider configuration is disabled. ], null)

**Comment by ameenbadri7** [comment]
hello, @attare026 Wellcome back.

could you check our video guides on this [link](https://docs.inspireui.com/fluxstore/firebase/). 
I guess your problem is enabling the sign-in methods from firebase [console ](https://console.firebase.google.com/)website. 

![firebase-google-signin-5577-01](https://user-images.githubusercontent.com/37524186/86677505-55328d80-c004-11ea-83d6-288102cacc80.png)
Go to Authentication in the Authentication tab click on Sign-in method tab. 
Then click on Google option and enable the sign-in provider and enter your project support email id.

**Comment by attare026** [comment]
Please check titels of this issue

**Comment by attare026** [comment]
> hello, @attare026 Wellcome back.
> 
> could you check our video guides on this [link](https://docs.inspireui.com/fluxstore/firebase/).
> I guess your problem is enabling the sign-in methods from firebase [console ](https://console.firebase.google.com/)website.
> 
> ![firebase-google-signin-5577-01](https://user-images.githubusercontent.com/37524186/86677505-55328d80-c004-11ea-83d6-288102cacc80.png)
> Go to Authentication in the Authentication tab click on Sign-in method tab.
> Then click on Google option and enable the sign-in provider and enter your project support email id.

hello!!!!

**Comment by ameenbadri7** [comment]
you will find facebook under google !!

**Comment by attare026** [comment]
> you will find facebook under google !!

still face the same problem!

**Comment by minhcasi** [comment]
@attare026 - pls try to check this solution #3151

**Comment by attare026** [comment]
![image](https://user-images.githubusercontent.com/34741721/87043774-69020d80-c217-11ea-97fa-274cdd09f5ca.png)

I think here is my problem!

**Comment by minhcasi** [comment]
@attare026 - could you double-check this guide https://medium.com/@inspireui/setup-facebook-login-for-flutter-apps-4e7bd031479d - thanks

**Comment by attare026** [comment]
I will do perfectly follow this instructions! now  After press Facebook, Google, sms and email login its freez on login screen not going setting page! After waiting not going setting page then i will do manually press back then show only logout! Not user name or anything! 
- @minhcasi

**Comment by minhcasi** [comment]
@attare026 - try to double your setting from Facebook Developer app dashboard. 

Or try to fresh login example from this guide https://pub.dev/packages/flutter_facebook_login

**Comment by attare026** [comment]
okay, I will check!

**Comment by minhcasi** [comment]
Please try to double-check and let us know if you have any further issues. 

Please help note that we may not support answering some technical questions for the regular license as per support policies - https://inspireui.com/support-policies/ - but we are trying to best to give extra miles with the supporting. 

Hope you enjoy the product 😊
