### ISSUE TITLE
[MStore] Unable install apk file which generated from expo project

### ISSUE THREAD

**Issue by rajendar123** [inspireui/support#409]
Product: MStore
We have purchased MStore code from codecanyon. We have generated apk file with the expo project. But when trying to install it. It is not installing. How to generate proper apk file from expo project which can be installed in a mobile phone?
It will be more useful if I can convert into the react-native project.

**Comment by luyx2412** [comment]
Hi @rajendar123 You can follow the document to generate apk file https://docs.expo.io/versions/latest/distribution/building-standalone-apps/#4-wait-for-it-to-finish-building

Thanks

**Comment by rajendar123** [comment]
Hi @luyx2412,
I have tried that but no luck. Here I want to convert it into react-native app.
I have tried all the suggestions available on google. 
Please please help me to resolve it. 
If possible please share android folder after conversion.

**Comment by luyx2412** [comment]
Hi @rajendar123 You can use the original react native version with name Mstore Pro to export apk easier. 
And please provide your purchase code.

Thanks

**Comment by rajendar123** [comment]
That is great. Please help
purse code is : c01d05d8-013a-41e7-acd3-79a6847fdc13

**Comment by rajendar123** [comment]
Is it possible to convert mstore expo project to react native vesrion ?

**Comment by luyx2412** [comment]
Hi @rajendar123 We have Original react native version with name MStore Pro, you can switch to this version or using Expo kit https://docs.expo.io/versions/latest/expokit/eject/

Thanks

**Comment by rajendar123** [comment]
Is there any option to upgrade from expo to react-native

**Comment by luyx2412** [comment]
Hi @rajendar123 You can use the expokit to upgrade to Original version react native. It is the easiest way to move Original version.

Thanks

**Comment by rajendar123** [comment]
Hi @luyx2412  We have followed expo kit. Every looking fine. Even I opened android folder in the android studio. But when I run react-native run-android. I am seeing below error. Android emulator is configured and running as per the document. I am giving package.json file.
Could you please help me? If I miss anything here.
 `{
  "name": "mstore",
  "description": "MStore Pro - Complete React Native template for e-commerce",
  "author": "InpireUI",
  "version": "3.6.0",
  "private": true,
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "setup": "./scripts/setup.sh",
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "eject": "expo eject"
  },
  "dependencies": {
    "api-ecommerce": "0.0.22",
    "babel-plugin-transform-decorators-legacy": "^1.3.5",
    "babel-preset-env": "^1.7.0",
    "base-64": "^0.1.0",
    "create-react-context": "^0.2.3",
    "currency-formatter": "^1.4.2",
    "expo": "32.0.6",
    "expokit": "^32.0.7",
    "firebase": "5.8.3",
    "html-entities": "^1.2.1",
    "lodash": "4.17.11",
    "moment": "2.24.0",
    "monet": "0.9.0",
    "oauth-1.0a": "1.0.1",
    "path": "^0.12.7",
    "react": "16.5.0",
    "react-instantsearch": "^5.1.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
    "react-native-animatable": "^1.3.0",
    "react-native-app-intro-slider": "1.0.1",
    "react-native-clean-form": "^0.5.0",
    "react-native-collapsible": "1.4.0",
    "react-native-country-picker-modal": "^0.7.1",
    "react-native-drawer": "https://github.com/luyx2412/react-native-drawer.git",
    "react-native-fluid-slider": "^1.0.2",
    "react-native-keyboard-aware-scroll-view": "^0.8.0",
    "react-native-masked-text": "^1.10.1",
    "react-native-modalbox": "1.7.1",
    "react-native-paper": "^2.11.1",
    "react-native-parallax": "^0.3.0",
    "react-native-radio-buttons": "^1.0.0",
    "react-native-render-html": "4.1.1",
    "react-native-scrollable-tab-view": "0.10.0",
    "react-native-side-menu": "^1.1.3",
    "react-native-snap-carousel": "^3.6.0",
    "react-native-star-rating": "^1.0.9",
    "react-native-swipe-list-view": "1.5.2",
    "react-native-swiper": "^1.5.13",
    "react-navigation": "3.0.9",
    "react-navigation-header-buttons": "^2.1.0",
    "react-navigation-props-mapper": "^0.4.0",
    "react-redux": "6.0.1",
    "redux": "^4.0.0",
    "redux-actions": "^2.6.4",
    "redux-persist": "^5.9.1",
    "redux-thunk": "^2.3.0",
    "reselect": "4.0.0",
    "tcomb-form-native": "^0.6.13",
    "urijs": "1.19.1",
    "url": "^0.11.0",
    "url-parse": "1.4.4",
    "util": "0.11.1",
    "uuid": "3.3.2",
    "validate.js": "^0.12.0",
    "wpapi": "^1.2.1"
  },
  "devDependencies": {
    "babel-jest": "^24.1.0",
    "babel-plugin-transform-remove-console": "^6.9.4",
    "babel-preset-expo": "^5.0.0",
    "babel-preset-react-native": "4.0.1",
    "jest": "^24.1.0",
    "reactotron-react-native": "2.1.7",
    "reactotron-redux": "2.1.3"
  }
}
`

**Comment by rajendar123** [comment]
Hi @luyx2412 I have followed steps mentioned in expo kit document. Everything looking fine. Even I have opened app android folder in the android studio. I haven't seen any issue. But when I run 'react-native run-android' command. I am seeing below error. 
---- Error message ----
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html
------------------------
Android emulator is configured and running as per the document. 
I think something wrong in package.json file. 
My package.json file content is below.
Could you please help me? If I miss anything here.
'{
  "name": "mstore",
  "description": "MStore Pro - Complete React Native template for e-commerce",
  "author": "InpireUI",
  "version": "3.6.0",
  "private": true,
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "setup": "./scripts/setup.sh",
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "eject": "expo eject"
  },
  "dependencies": {
    "api-ecommerce": "0.0.22",
    "babel-plugin-transform-decorators-legacy": "^1.3.5",
    "babel-preset-env": "^1.7.0",
    "base-64": "^0.1.0",
    "create-react-context": "^0.2.3",
    "currency-formatter": "^1.4.2",
    "expo": "32.0.6",
    "expokit": "^32.0.7",
    "firebase": "5.8.3",
    "html-entities": "^1.2.1",
    "lodash": "4.17.11",
    "moment": "2.24.0",
    "monet": "0.9.0",
    "oauth-1.0a": "1.0.1",
    "path": "^0.12.7",
    "react": "16.5.0",
    "react-instantsearch": "^5.1.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
    "react-native-animatable": "^1.3.0",
    "react-native-app-intro-slider": "1.0.1",
    "react-native-clean-form": "^0.5.0",
    "react-native-collapsible": "1.4.0",
    "react-native-country-picker-modal": "^0.7.1",
    "react-native-drawer": "https://github.com/luyx2412/react-native-drawer.git",
    "react-native-fluid-slider": "^1.0.2",
    "react-native-keyboard-aware-scroll-view": "^0.8.0",
    "react-native-masked-text": "^1.10.1",
    "react-native-modalbox": "1.7.1",
    "react-native-paper": "^2.11.1",
    "react-native-parallax": "^0.3.0",
    "react-native-radio-buttons": "^1.0.0",
    "react-native-render-html": "4.1.1",
    "react-native-scrollable-tab-view": "0.10.0",
    "react-native-side-menu": "^1.1.3",
    "react-native-snap-carousel": "^3.6.0",
    "react-native-star-rating": "^1.0.9",
    "react-native-swipe-list-view": "1.5.2",
    "react-native-swiper": "^1.5.13",
    "react-navigation": "3.0.9",
    "react-navigation-header-buttons": "^2.1.0",
    "react-navigation-props-mapper": "^0.4.0",
    "react-redux": "6.0.1",
    "redux": "^4.0.0",
    "redux-actions": "^2.6.4",
    "redux-persist": "^5.9.1",
    "redux-thunk": "^2.3.0",
    "reselect": "4.0.0",
    "tcomb-form-native": "^0.6.13",
    "urijs": "1.19.1",
    "url": "^0.11.0",
    "url-parse": "1.4.4",
    "util": "0.11.1",
    "uuid": "3.3.2",
    "validate.js": "^0.12.0",
    "wpapi": "^1.2.1"
  },
  "devDependencies": {
    "babel-jest": "^24.1.0",
    "babel-plugin-transform-remove-console": "^6.9.4",
    "babel-preset-expo": "^5.0.0",
    "babel-preset-react-native": "4.0.1",
    "jest": "^24.1.0",
    "reactotron-react-native": "2.1.7",
    "reactotron-redux": "2.1.3"
  }
}'

**Comment by luyx2412** [comment]
Hi @rajendar123 If you open android studio and everything worked normal. Please use android studio build your app, you don't need using `react-native run-android`. And your issue related emulator, please make sure the emulator opened or real device connected.

https://docs.expo.io/versions/latest/expokit/expokit/#4-android-build-and-run

Thanks

**Comment by rajendar123** [comment]
Hi @luyx2412  Android studio generated apk. If I installed on mobile it is not opening.
Can you please review once package.json file once?

**Comment by rajendar123** [comment]
Hi @luyx2412 After too many tries. We are seeing the issue while loading google-services.json file.
`{
  "project_info": {
    "project_id": "exponent-5dd6d",
    "project_number": "367315174693",
    "name": "Exponent Play Services"
  },
  "client": [
    {
      "client_info": {
        "mobilesdk_app_id": "1:367315174693:android:f968efbb41d1fa7a",
        "client_id": "android:host.exp.exponent",
        "client_type": 1,
        "android_client_info": {
          "package_name": "com.inspireui.mstore",
          "certificate_hash": ""
        }
      },
      "oauth_client": [],
      "api_key": [
        {
          "current_key": ""
        }
      ],
      "services": {
        "analytics_service": {
          "status": 2,
          "analytics_property": {
            "tracking_id": "UA-76673608-1"
          }
        },
        "cloud_messaging_service": {
          "status": 2,
          "apns_config": []
        },
        "appinvite_service": {
          "status": 1,
          "other_platform_oauth_client": []
        },
        "google_signin_service": {
          "status": 1
        },
        "ads_service": {
          "status": 1
        }
      }
    }
  ],
  "client_info": [],
  "ARTIFACT_VERSION": "1"
}

Any suggestions ?`

**Comment by rajendar123** [comment]
Hi @luyx2412 After too many tries. We are seeing the issue while loading google-services.json file.
`{
"project_info": {
"project_id": "exponent-5dd6d",
"project_number": "367315174693",
"name": "Exponent Play Services"
},
"client": [
{
"client_info": {
"mobilesdk_app_id": "1:367315174693:android:f968efbb41d1fa7a",
"client_id": "android:host.exp.exponent",
"client_type": 1,
"android_client_info": {
"package_name": "com.inspireui.mstore",
"certificate_hash": ""
}
},
"oauth_client": [],
"api_key": [
{
"current_key": ""
}
],
"services": {
"analytics_service": {
"status": 2,
"analytics_property": {
"tracking_id": "UA-76673608-1"
}
},
"cloud_messaging_service": {
"status": 2,
"apns_config": []
},
"appinvite_service": {
"status": 1,
"other_platform_oauth_client": []
},
"google_signin_service": {
"status": 1
},
"ads_service": {
"status": 1
}
}
}
],
"client_info": [],
"ARTIFACT_VERSION": "1"
}
error message is 

* What went wrong:
Execution failed for task ':app:bundleProdKernelDebugExpoAssets'.

Any suggestions ?`

**Comment by luyx2412** [comment]
Hi @rajendar123 Can you take take the screenshot to understand easier?

Thanks

**Comment by rajendar123** [comment]
error image
![image](https://user-images.githubusercontent.com/42565521/55074202-acce1380-50b5-11e9-898b-32770ce826f9.png)

**Comment by luyx2412** [comment]
Hi @rajendar123 I saw the issue related release key, can you check the comment to fix the issue. https://docs.expo.io/versions/v32.0.0/distribution/app-signing/#1-using-app-signing-by-google-play https://forums.expo.io/t/release-channels-on-detached-expokit-app/4902/9

Thanks
