### ISSUE TITLE
Hamburger menu

### ISSUE THREAD

**Issue by miskayapp** [inspireui/support#4090]
How do i call a webpage on the hamburger menu

**Comment by miskayapp** [comment]
![1EF8F37D-EB58-4523-B954-D5B37AF9394C](https://user-images.githubusercontent.com/64660378/86639860-8c3b7b80-bfd1-11ea-80cd-d7d5d3294fee.jpeg)
How can i add a webview page to that hamburger menu or switch the blog to open a different url

**Comment by minhcasi** [comment]
@miskayapp - pls move your all comment to the same open ticket support #4013

**Comment by miskayapp** [comment]
You move all your comments but you dont reply them when i do.
