### ISSUE TITLE
Realtime Chat Firebase For Fluxstore MV Not workinh

### ISSUE THREAD

**Issue by Shopyloot** [inspireui/support#4091]
**Vendor Not Getting the messages instead of it here it was having an error in the my conversations of vendors. Followed each and every step as per in the guideline video https://www.youtube.com/watch?v=C_9mk_MmvOQ  **

Please go through the error screenshot 

<a href="https://ibb.co/6ZWLZxx"><img src="https://i.ibb.co/6ZWLZxx/Simulator-Screen-Shot-i-Phone-SE-2nd-generation-2020-07-07-at-02-51-37.png" alt="Simulator-Screen-Shot-i-Phone-SE-2nd-generation-2020-07-07-at-02-51-37" border="0"></a>

I am able to go to stores and click on chat icon to text the particular vendor, only issue with it is vendor not receiving the messages.

Please help me with this.

**Comment by minhtruong315** [comment]
@Shopyloot can u send me full your source code via email: minhtruong315@gmail.com
Ping me when you sent
Thanks

**Comment by Shopyloot** [comment]
@minhtruong315 Hi i have sent you my complete project file via the mail shopyloot@gmail.com please check

**Comment by minhtruong315** [comment]
Hi @Shopyloot give me your skype? I want to contact you via skype to check your firebase.
Thanks

**Comment by Shopyloot** [comment]
Hello @minhtruong315  this is my skype live:cid.ab26f3f3733eb5be and Email for skype:  rjcreations2016@gmail.com

**Comment by minhtruong315** [comment]
I ping you on the skype. pls check. thanks

**Comment by Shopyloot** [comment]
Thanks issue solved @minhtruong315 Great support as always

**Comment by ssathamenterprises** [comment]
hi what they done , i have same issue friend , vendor not receive the message
