### ISSUE TITLE
Product not showing up when you access them the second time

### ISSUE THREAD

**Issue by patelvinay** [inspireui/support#4093]
+ Product & version: I am using FluxStore for Shopify
+ Detail Issues: When I click on a category I get product list the first time when I refresh or click on it again on the same category nothing displays, and the same for any other category but only once as well.

the only modification I did is the website domain and the access key and I am accessing my website category from the right bar.
I tied to switch between the Webhook API versions (I am using 2020-07) but still getting the same issue.
Am I missing something?

The second problem is some errors under the product description (Check attachment) !

Is Shopify blog supported ({Domain}/blog/news) ?

+ Flutter (or React Native) version: Flutter version 1.17.4
+ Testing Device/Simulator: Pixel 2
+ Screenshot issues (drag the file to attach here): 
![86539793-688f0d00-becd-11ea-8c64-5c454d8b19f9](https://user-images.githubusercontent.com/46544799/86687971-aece9400-bfd3-11ea-93e7-30db75a7b477.jpg)

**Comment by luyx2412** [comment]
Hi @patelvinay I just invited to the fluxshopify repo, please pull latest version and try again which fix the issue.

Thanks

**Comment by patelvinay** [comment]
@luyx2412  thanks for the update, so far working pretty good. thank you so much.
