### ISSUE TITLE
Replacing splashscreen.flr

### ISSUE THREAD

**Issue by medsaadit** [inspireui/support#4094]
Hi,
I created another splashscreen.flr with the same dimensions, I replaced it but the app freezes whenever I start it. The flr I have exported is a json file that contains image binary (for assets) that looks like that : 
![Screenshot from 2020-07-06 22-07-55](https://user-images.githubusercontent.com/67774655/86690478-f524f280-bfd5-11ea-9c8f-842cec0b0411.png)

What would be wrong with my splashscreen ?

Thanks,

**Comment by minhcasi** [comment]
could you have a quick check to see if the startAnimation is the same with the Flare config? This is mention on this document https://docs.inspireui.com/fluxstore/customization/#2-logo-splash-screen 

Please help to move your all comment into one ticket support ticket #4033 - thank you!
