### ISSUE TITLE
Loading indicator is showing forever on fluxstore for woocommerce app.

### ISSUE THREAD

**Issue by aak830117** [inspireui/support#4096]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: In fluxstore for woocommerce app, loading indicator is showing forever when launch the app.
+ Product & version: fluxstore for woocommerce, 1.7.5
+ Flutter (or React Native) version: flutter 1.17.3
+ Testing Device/Simulator: ios simulator, iphone X, samsung galaxy note 10
+ Screenshot issues (drag the file to attach here): 
<img width="405" alt="Screen Shot 2020-07-07 at 10 48 53 AM" src="https://user-images.githubusercontent.com/67259982/86705508-263a0d00-c040-11ea-8c2d-df4b0eb4c323.png">

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@vumanhsn97 - pls help to check the rest api on the new fluxbuilder if it is related to 401 issue

**Comment by aak830117** [comment]
They're not 401 error. Api connection is success but it didn't disappear.

**Comment by vumanhsn97** [comment]
@aak830117 
Please submit a form to https://docs.google.com/forms/d/e/1FAIpQLScWOjkAJIWJ9rgb9alopfOqLsJrGKbFM5cCYj1JBfLKLsBblQ/viewform

**Comment by aak830117** [comment]
@vumanhsn97 I did it already. Do you need it again?

**Comment by vumanhsn97** [comment]
@aak830117 
It is working well with your config. https://tppr.me/n4SXA
Try with this cmd:
flutter clean
cd ios
pod deintegrate
rm -rf Podfile.lock
pod install
cd ..
flutter run

**Comment by aak830117** [comment]
@vumanhsn97 It appears not only on ios, also on android.
Do you working well when you run every time?
I have this issue over 80% when I run the app.

**Comment by vumanhsn97** [comment]
@aak830117 
Replace this file in lib/widgets/home/vertical/menu_layout.dart to 
[menu_layout.dart.zip](https://github.com/inspireui/support/files/4911006/menu_layout.dart.zip)

**Comment by minhcasi** [comment]
Also, try to use the latest release `1.7.6` let us know if you have any issue - thank you!
