### ISSUE TITLE
PRODUCTS NOT LOADING IN THE APP, LOADS IN FLUX BUILDER

### ISSUE THREAD

**Issue by nucl123** [inspireui/support#4099]
Hi,
The app is not loading any products or data, it works well in flux builder, but not in the simulator.
done, all setup steps as mentioned in the documentation.

![image](https://user-images.githubusercontent.com/51371138/86781409-85127d00-c066-11ea-8e91-489beb24d3a7.png)

![image](https://user-images.githubusercontent.com/51371138/86781467-98bde380-c066-11ea-8a99-f119af6ae36c.png)
![image](https://user-images.githubusercontent.com/51371138/86781528-b3905800-c066-11ea-86d2-5facf5898e17.png)

**Comment by nucl123** [comment]
Hello
Waiting for a fix.

**Comment by minhcasi** [comment]
@nucl123 - this could cause by version mismatch from fluxbuilder and fluxstore - we will update the latest fluxstore 1.6.7 asap - thank you!

**Comment by nucl123** [comment]
Can you send a link to download the matching fluxbuilder for the fluxstore?
I am just using the latest downloaded zip , and the flux builder as linked in your listing in codecanyon product listing description page.
If these versions are not matching, then send us the link to matching versions.
we are in project deadline and need to finish it asap.
waiting for your earliest feedback.

**Comment by nucl123** [comment]
the version is 1.7.5 . which 1.6.7 version are you talking about?
![image](https://user-images.githubusercontent.com/51371138/86914471-18ac8200-c129-11ea-8cc3-604f23847f7a.png)

**Comment by minhcasi** [comment]
`1.7.6` is the new release, we will update in 1-2 days - thank you!

**Comment by minhcasi** [comment]
it's available on our GitLab (you could request here if not get the access http://gitlab.inspireui.com/), new package release will update on early next week - thank you!

**Comment by nucl123** [comment]
already submitted the form https://prnt.sc/tg3t6l
how to access it?
It is too much delayed.
not even able to run the app, once after purchase !!!!
waiting for an immediate solution.

**Comment by minhcasi** [comment]
Fixed on the latest `1.7.6`, let us know if you have any issues - thank you!
