### ISSUE TITLE
[MStore] linking backend not working

### ISSUE THREAD

**Issue by nkuranhy3** [inspireui/support#410]
**Required Info (please complete the following information):**
 - Product: Mstore Expo 

 - Your Purchased Code:  41a15692-aacc-457e-a826-e13987ff0a86
(we may not reply if you are not our customer)

**Describe the bug**
Am still having issues with connecting the backend.

The website we want connect is http://www.hypacart.com/ We have installed all the dependencies and modules as described in the articles but the view is not looking good. 
The data from http://www.hypacart.com/ is not showing up in the mobile application.
The Categories are not showing up.

Again there are some products on the page that are not from our backend.
[appHypacart.zip](https://github.com/inspireui/support/files/2981712/appHypacart.zip)

Please can you help us with that in person? Can we schedule a call so that you help us resolve this as soon as possible?

**Screenshots**

**Additional context**
Add any other detail logs about the problem here.
If possible please share your config.js that use for the app setting

**Comment by luyx2412** [comment]
Hi @nkuranhy3 Sorry we can not a call to fix the issue, please follow the document install the website. https://docs.mstore.io/basic-app-setting. And if you have any issue, feel free create new issue on the github.

Thanks

**Comment by nkuranhy3** [comment]
Hi,
The basic setup is not working here.
I have installed all the plugins on http://hypacart.com backend.

When i change the customisations for ceBuilder it dont work.

Look at these screenshots.

[image: Screen Shot 2019-03-22 at 9.45.48 AM.png]

I am changed the app name to hypacart
and the website to http://hypacart.com

But the customisation dont work. it says cannot get categories and tags

[image: Screen Shot 2019-03-22 at 9.46.06 AM.png]

And it runs forever after clicking ok

[image: Screen Shot 2019-03-22 at 9.58.54 AM.png]

It has been running for hours.


Please can you help us in this?

Hear from you soon.

**Comment by luyx2412** [comment]
Hi @nkuranhy3 Can you send again the screenshot, and please use debug tools to check the issue https://docs.mstore.io/api-and-project-structure#debug-app-with-reacttotron

Thanks

**Comment by nkuranhy3** [comment]
Hi,
Am getting disappointed.
It is not working

The products api is showing up

[image: Screen Shot 2019-03-26 at 1.44.17 PM.png]
But the api to get the categories is not working

https://www.hypacart.com/wp-json/wc/v2/categories

[image: Screen Shot 2019-03-26 at 1.45.09 PM.png]
And the Payment gateways too is not working

[image: Screen Shot 2019-03-26 at 1.46.06 PM.png]

Starting the app is still not working after i change the website from
mstore.io to hypacart.com
[image: Screen Shot 2019-03-22 at 9.45.48 AM.png]
[image: Screen Shot 2019-03-22 at 9.46.06 AM.png]
[image: Screen Shot 2019-03-22 at 9.58.54 AM.png]

I updated CeBuilder but the problem is still persisting


I need much help please!!!
We need to publish this app by this weekend for an upcoming event. So
please do me a favour and help me connect hypacart.com to the app.

Even if i have to send you the credentials for hypacart.com and you can fix
it i will do so.

Hear from you soon!!

**Comment by luyx2412** [comment]
HI @nkuranhy3 Can you provide your AppConfig.json and config.js file?

Thanks

**Comment by nkuranhy3** [comment]
Hi,
These are the files on google drive

https://drive.google.com/file/d/1MmEqzZgyTAViSPfy2fe_3cv4dZ0linws/view?usp=sharing
https://drive.google.com/file/d/1ndD9z_wurigxeoNb-j7G8t4T_r0LEfSx/view?usp=sharing

The complete file is also here

https://drive.google.com/file/d/1gZO0F4qCUotDCxcZZgnHshGGuO2jMDXj/view?usp=sharing

Please help me out

Thank you.

**Comment by luyx2412** [comment]
Hi @nkuranhy3 Please do not share source code app in anything. And let me check your config.

Thanks

**Comment by luyx2412** [comment]
Hi @nkuranhy3 I just checked your config. The issue related consumer key. Please make sure you config right way follow the document.
And please update latest version Mstore, your version is old. Specially, please do not share your source code to anything.

![image](https://user-images.githubusercontent.com/8909619/55125800-61f7de80-513d-11e9-9bbc-29b40a423adf.png)

Thanks
