### ISSUE TITLE
Strange SMS Login "Error in NoSUchMethodError" The getter 'fieldHeight' was called on null.

### ISSUE THREAD

**Issue by aishema2000** [inspireui/support#4100]
I need URGENT support. I have a strange error when trying to login with SMS. Everything works well, Email login is perfect, but when I login with the phone number, I get the verification code well, but the app is stuck on this screen:
![EEEE](https://user-images.githubusercontent.com/15066381/86799269-0faca980-c072-11ea-934d-55d243c53e33.jpeg)

Below is the debug console when this errors happens:
![image](https://user-images.githubusercontent.com/15066381/86789536-b5a6e680-c067-11ea-9c51-5c859439c5bb.png)

What can i do?

**TO VERIFY MY PURCHASE PLEASE SEE THIS TICKET #3151**

**Comment by minhcasi** [comment]
@aishema2000 - did you double-check the guide to see if there is any missing config? https://docs.inspireui.com/fluxstore/sign-in/ ?

I'm not sure if this but related to this lib https://pub.dev/packages/pin_code_fields - you could try to add the pinTheme  so see if it can be fixed - https://tppr.me/doYSe

**Comment by aishema2000** [comment]
Dear @minhcasi you are a SUPER HERO, you are a genius. That was the exact problem. **BUT another very serious issue arises: **
After inputting the verification code, the Apps takes a very very very long time to load!!!! It takes about one minute and 20 seconds. Users can not wait, and I may end up loosing customers. Please see the attached video
![WhatsApp](https://user-images.githubusercontent.com/15066381/86889289-cef97280-c0fb-11ea-83af-be6aea2f35ef.gif)

When this happens this is what I see in the debug console:
![image](https://user-images.githubusercontent.com/15066381/86889616-534bf580-c0fc-11ea-9a18-3a354ab8cf1b.png)

**Comment by aishema2000** [comment]
Hello @minhcasi . I am about to launch my App please help me with the issues above. Thanks

**Comment by minhcasi** [comment]
@aishema2000 

1. the slow issue could because by your Firebase or hosting server, not from the app source code - try to check on product app to see if it is better?

2. we don't have good solution so far

3. this is limit of current SMS login, do you have suggestion on this feature? as the woocommerce require username after process SMS login

4. it's working fine with our testing number, not sure if it causes by the Firebase SMS login issue?

**Comment by aishema2000** [comment]
Dear @minhcasi thanks for your reply. Issues 2, 3, 4 are not big, we can ignore.

But the slowness issue is very serious. I have just tested with your demo app, and it takes around 7 seconds to login with sms, but on my end it is 1 minute and 20 second. I don't think it is the server issue because all other things are super fast. Maybe my firebase project?? I am going to delete it  and create a fresh new firebase project and will let you know. In the meantime if you have any other idea, please share. Thanks.

**Comment by aishema2000** [comment]
Dear @minhcasi i tried everything i can but the login process after code verification is too slow. I am 500% sure that if you have a close look at it, you can solve it and save me in less than 5 minutes. I have been here for so long, and this is the only issue i have before launch my app. I am not a developper, please accept to connect and see yourself, and let my dream become true. Thanks in advance.

**Comment by aishema2000** [comment]
@minhcasi  On this ticket #4139 one kind person advises me to create a new Database within firebase. (Not new firebase project) i am going to try and let you know.

**Comment by minhcasi** [comment]
Let us know your checking - thank you!

**Comment by aishema2000** [comment]
Dear @minhcasi, after investigation i found that the issue of sms login taking too long happens when a user already exists in wordpress. New users can sign in with sms very fast, but if a user logs out and try to login again it will take very long time to re-log in. This concerns SMS login only! Users who change phone, or who buy new phone will suffer whe trying to login again to their account... Best Regards,
Shema
