### ISSUE TITLE
Registration, order and categories

### ISSUE THREAD

**Issue by AntonRatushev** [inspireui/support#4101]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
**Registration:**
1. in registration process when we send request to server we've got error (in file): lib\services\woo_commerce.dart createUser()
2. after registration, WP gives us cookie key (f.e. test11411@test.ru%7C1593531203%7CbgFIClyaJUnUoLZQEIPnW9zKOHyNIGSWgKbCIRcOfJ4%7C4bb320011ff8c1d7aa08d542914e61f2797841df8d93f5d15b44a3614bfa885a&)
And when application sending this cookie to server to get user info we've got error with wrong cookie: lib\services\woo_commerce.dart getUserInfo()

**Order**
When we try to make an order we get error https://prnt.sc/tdg6gc (Api key doesn't have rights to write)

**Categories**
In categories, we've got all cats with doubles https://prnt.sc/tdg8ww https://prnt.sc/tdg97z

+ Product & version:
fstore 1.7.3+3001
+ Flutter (or React Native) version: 
Flutter
+ Testing Device/Simulator: 
Android studio

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
@ameenbadri7 - it's verified

**Comment by ameenbadri7** [comment]
you are using old fluxstore `1.7.3+3001` please use the latest one from our private repo inside Gitlab.com 
please if you are not their tell us so we can add you by email to it.

thank you

**Comment by AntonRatushev** [comment]
We are going to develop applications for our customers based on your ready-made solution.

We need everything to work correctly with the previous versions as well (our version was purchased a month ago).

 

Otherwise, after developing 50 applications, they will stop working because a new version has been released. In this case we will have to spend time and money on updates. At that each application will contain improvements that may be erased during updating.

 

Is it possible to use your application for our purposes, or will it always get crashed due to the release of a new version?

**Comment by minhcasi** [comment]
@AntonRatushev - we suggest to follow this guide to update the product by merging the new upgrade via gitlab - https://medium.com/@inspireui/how-to-upgrade-fluxstore-projects-by-using-git-cebde7489ea6

Please make sure you will purchase more 50 License if you would like to delivery 50 app 😅

**Comment by minhcasi** [comment]
Let me know if you have any question - thank you!
