### ISSUE TITLE
Not show discounted price and 'Share' not work

### ISSUE THREAD

**Issue by BreX900** [inspireui/support#4102]
+ Product & version: Fluxstore - WooCommerce 1.7.5
+ Flutter version: 1.17.5
+ Testing Device/Simulator: Physical devices
+ Screenshot issues (drag the file to attach here): 

-------
It does not show the discounted price on the home page
config.json
```json
{
  "HorizonLayout": [
    {
      "layout": "logo",
      "showMenu": true,
      "showLogo": true,
      "showSearch": true,
      "image": "assets/images/logo.png"
    }
  ],
  "VerticalLayout": {
    "layout": "menu"
  },
  "Setting": {
    "MainColor": "#3FC1BE",
    "ProductListLayout": "list",
    "StickyHeader": false
  },
  "TabBar": [{
    "layout": "home",
    "icon": "assets/icons/tabs/icon-home.png"
  },
    {
      "layout": "home",
      "icon": "assets/icons/tabs/icon-home.png"
    },
    {
      "layout": "category",
      "categoryLayout": "card",
      "icon": "assets/icons/tabs/icon-category.png"
    },
    {
      "layout": "search",
      "icon": "assets/icons/tabs/icon-search.png"
    },
    {
      "layout": "cart",
      "icon": "assets/icons/tabs/icon-cart2.png"
    },
    {
      "layout": "profile",
      "icon": "assets/icons/tabs/icon-user.png"
    }
  ],
  "searchSuggestion": [
    "man",
    "dress",
    "Stitch",
    "ma"
  ]
}
```
![Screenshot_20200707-164948](https://user-images.githubusercontent.com/44398785/86799332-1f2bf280-c072-11ea-9c90-a0b68e8cb50b.png)
-----
For the correct functioning of the 'Share' package in the Ipad it is required to use the 'sharePositionOrigin' parameter
Example: https://github.com/flutter/plugins/blob/master/packages/share/example/lib/main.dart
```dart
final RenderBox box = context.findRenderObject();
await Share.share(
  product.files[0], 
  sharePositionOrigin: box.localToGlobal(Offset.zero) & box.size,
);
```
![Screenshot_20200707-165018](https://user-images.githubusercontent.com/44398785/86799322-1cc99880-c072-11ea-8241-5f2e9d20e59a.png)

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by BreX900** [comment]
I have already completed the form at the link http://verify.inspireui.com/. As soon as I created the issues

**Comment by minhcasi** [comment]
@BreX900 - We wanted to thank you for your patience during this busy time. We currently have reduced staff and a significantly higher volume of inquiries. We’re working as hard as we can to get to your request as soon as possible.

We sincerely apologize for the delay and hope you’re staying safe.

**Comment by minhcasi** [comment]
@ameenbadri7 - pls help to check on this issue - thank you!

**Comment by ameenbadri7** [comment]
you can add banners and product blocks inside your app from the config file.
you can use this [tutorial ](https://docs.inspireui.com/fluxstore/home-layout/)
like if you add this to your config file its will show you a block of product that is :
```
  {
      "name": "Our best discounts",
      "image": "",
      "layout": "twoColumn",
      "isSnapping": true,
      "onsale": true,
     "featured": false,
    },
```
its will show discount product  `"onsale": true,` but will hide featured products `"featured": false,`.

you can see my config_en.json file 

[config_en.zip](https://github.com/inspireui/support/files/4900235/config_en.zip)

and use end modifies it to meet your customizations. just double check our [documentation](https://docs.inspireui.com/fluxstore). 

happy coding !!

**Comment by BreX900** [comment]
It did not answer my problem and I still consider it open as regards the "VerticalLayout" since it is not possible to view the discounted price except if you do not use "pinterest" or "menu".
For this reason I went to:
```json
"VerticalLayout": {
    "layout": "default"
  },
```
------------------------
In addition, the problem of the "Share" package that does not work on Ipad prevents me from updating the application as it is rejected by Apple!
For this reason, I ask you to correct it as soon as possible
From what I know it is enough to do as follows
```dart
final RenderBox box = context.findRenderObject();
await Share.share(
  <text>, 
  sharePositionOrigin: box.localToGlobal(Offset.zero) & box.size,
);
```

**Comment by ameenbadri7** [comment]
@minhcasi could you help here ?

**Comment by minhtruong315** [comment]
Hi @BreX900 Can u send me common folder via email: truong@inspireui.com
with subject:  https://github.com/inspireui/support/issues/4102
Thanks

**Comment by BreX900** [comment]
Hi @minhtruong315, I sent her the email with the folder
The real problem is the calls made with `Share.share ()`, they don't work on ipad if you don't pass the `Rect sharePositionOrigin` parameter

**Comment by minhtruong315** [comment]
Hi @BreX900 so is your issue resolved?

**Comment by BreX900** [comment]
@minhtruong315 The problem is still present regarding the 'Share' package as described in the previous comment

**Comment by minhtruong315** [comment]
Hi  @BreX900 I see the 'Share' is working on iPad.
 https://github.com/inspireui/support/issues/3966

**Comment by minhtruong315** [comment]
Hi @BreX900 can u record screen. it's working well
https://www.dropbox.com/s/hg72a6s9yiirulu/share.mov?dl=0

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
