### ISSUE TITLE
Don't show stores

### ISSUE THREAD

**Issue by tenkovroman** [inspireui/support#4103]
Hello,
i've bought your app and i'm trying to configure it. I'm working with android studio and when i go into the categories and i click on store i cannot see store list. I don't understand where is the issue.

Can you help me please?
Thank you.
Regards
Carlo

Attached files: Issue and license
envato_panel
Store_Issue

![83772035-3a769d00-a683-11ea-8345-35e7c7226519](https://user-images.githubusercontent.com/38020206/86807376-3f1fde00-c093-11ea-9698-162adbfe49f5.jpg)

I have the same problem. Please tell me how to fix it.

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by tenkovroman** [comment]
I sent it, please check it

**Comment by tenkovroman** [comment]
> Thank you for the feedback.
> 
> Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.
> 
> We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!
> 
> > **[Google Forms - create and analyze surveys, for free.](http://verify.inspireui.com/)**Create a new survey on your own or with others at the same time. Choose from a variety of survey types and analyze results in Google Forms. Free from Google.

???????

**Comment by minhcasi** [comment]
@tenkovroman - sorry we got your detail 

@minhtruong315 - please help to investigate this issue

**Comment by minhtruong315** [comment]
Hi @tenkovroman send me common folder and admin account via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/4103

**Comment by tenkovroman** [comment]
> Hi @tenkovroman send me common folder and admin account via email: [truong@inspireui.com](mailto:truong@inspireui.com)
> with subject: #4103

Sent

**Comment by minhtruong315** [comment]
Hi @tenkovroman You haven't installed dokan plugin on your website yet. So you can't use dokan type to config. please install Dokan Pro plugin and check again
```
"type": "dokan",
  "url": "https://intop.uz",
```

**Comment by tenkovroman** [comment]
> Hi @tenkovroman You haven't installed dokan plugin on your website yet. So you can't use dokan type to config. please install Dokan Pro plugin and check again
> 
> ```
> "type": "dokan",
>   "url": "https://intop.uz",
> ```

We have WCFM

**Comment by tenkovroman** [comment]
> Hi @tenkovroman You haven't installed dokan plugin on your website yet. So you can't use dokan type to config. please install Dokan Pro plugin and check again
> 
> ```
> "type": "dokan",
>   "url": "https://intop.uz",
> ```

Our config file
"type": "wcfm",
  "url": "https://intop.uz",

**Comment by minhtruong315** [comment]
Hi @tenkovroman replace this function in vendor/store/store_model.dart
```
Store.fromWCFMJson(Map<String, dynamic> parsedJson) {
    id = int.parse("${parsedJson["vendor_id"]}");
    name = parsedJson["vendor_shop_name"];
    email = parsedJson["vendor_email"];
    rating = 0.0;
    address = parsedJson["vendor_address"];
    if (parsedJson["settings"] != null && parsedJson["settings"] is Map) {
      image = parsedJson["settings"]["gravatar"].toString().isNotEmpty &&
              parsedJson["settings"]["gravatar"].toString().contains("http")
          ? parsedJson["settings"]["gravatar"]
          : null;
      banner = parsedJson["settings"]["mobile_banner"] != null
          ? ((parsedJson["settings"]["mobile_banner"] is String)
              ? parsedJson["settings"]["mobile_banner"]
              : image)
          : (parsedJson["settings"]["banner"] != null
              ? (parsedJson["settings"]["banner"] is String
                  ? parsedJson["settings"]["banner"]
                  : image)
              : image);
      try {
        lat = double.parse(parsedJson["settings"]['store_lat']);
        long = double.parse(parsedJson["settings"]['store_lng']);
      } catch (e) {
        lat = null;
        long = null;
      }
      phone = parsedJson["settings"]["phone"];
    } else {
      banner = parsedJson['mobile_banner'] ??
          parsedJson['vendor_shop_logo'] ??
          parsedJson['vendor_banner'] ??
          parsedJson['vendor_list_banner'];
    }
  }
```

**Comment by devienguilde** [comment]
> Hi @tenkovroman replace this function in vendor/store/store_model.dart
> 
> ```
> Store.fromWCFMJson(Map<String, dynamic> parsedJson) {
>     id = int.parse("${parsedJson["vendor_id"]}");
>     name = parsedJson["vendor_shop_name"];
>     email = parsedJson["vendor_email"];
>     rating = 0.0;
>     address = parsedJson["vendor_address"];
>     if (parsedJson["settings"] != null && parsedJson["settings"] is Map) {
>       image = parsedJson["settings"]["gravatar"].toString().isNotEmpty &&
>               parsedJson["settings"]["gravatar"].toString().contains("http")
>           ? parsedJson["settings"]["gravatar"]
>           : null;
>       banner = parsedJson["settings"]["mobile_banner"] != null
>           ? ((parsedJson["settings"]["mobile_banner"] is String)
>               ? parsedJson["settings"]["mobile_banner"]
>               : image)
>           : (parsedJson["settings"]["banner"] != null
>               ? (parsedJson["settings"]["banner"] is String
>                   ? parsedJson["settings"]["banner"]
>                   : image)
>               : image);
>       try {
>         lat = double.parse(parsedJson["settings"]['store_lat']);
>         long = double.parse(parsedJson["settings"]['store_lng']);
>       } catch (e) {
>         lat = null;
>         long = null;
>       }
>       phone = parsedJson["settings"]["phone"];
>     } else {
>       banner = parsedJson['mobile_banner'] ??
>           parsedJson['vendor_shop_logo'] ??
>           parsedJson['vendor_banner'] ??
>           parsedJson['vendor_list_banner'];
>     }
>   }
> ```

i try this one too, I'm using WCFM but no product show but when i change type to dokan it's come out, i try this code is no change too

**Comment by minhtruong315** [comment]
<img width="1121" alt="Screen Shot 2020-07-11 at 11 16 23 AM" src="https://user-images.githubusercontent.com/10402500/87216234-f9e7fe80-c367-11ea-83ed-714704aa6c09.png">
I see it's showing stores on my source code.

**Comment by tenkovroman** [comment]
> > Hi @tenkovroman replace this function in vendor/store/store_model.dart
> > ```
> > Store.fromWCFMJson(Map<String, dynamic> parsedJson) {
> >     id = int.parse("${parsedJson["vendor_id"]}");
> >     name = parsedJson["vendor_shop_name"];
> >     email = parsedJson["vendor_email"];
> >     rating = 0.0;
> >     address = parsedJson["vendor_address"];
> >     if (parsedJson["settings"] != null && parsedJson["settings"] is Map) {
> >       image = parsedJson["settings"]["gravatar"].toString().isNotEmpty &&
> >               parsedJson["settings"]["gravatar"].toString().contains("http")
> >           ? parsedJson["settings"]["gravatar"]
> >           : null;
> >       banner = parsedJson["settings"]["mobile_banner"] != null
> >           ? ((parsedJson["settings"]["mobile_banner"] is String)
> >               ? parsedJson["settings"]["mobile_banner"]
> >               : image)
> >           : (parsedJson["settings"]["banner"] != null
> >               ? (parsedJson["settings"]["banner"] is String
> >                   ? parsedJson["settings"]["banner"]
> >                   : image)
> >               : image);
> >       try {
> >         lat = double.parse(parsedJson["settings"]['store_lat']);
> >         long = double.parse(parsedJson["settings"]['store_lng']);
> >       } catch (e) {
> >         lat = null;
> >         long = null;
> >       }
> >       phone = parsedJson["settings"]["phone"];
> >     } else {
> >       banner = parsedJson['mobile_banner'] ??
> >           parsedJson['vendor_shop_logo'] ??
> >           parsedJson['vendor_banner'] ??
> >           parsedJson['vendor_list_banner'];
> >     }
> >   }
> > ```
> 
> i try this one too, I'm using WCFM but no product show but when i change type to dokan it's come out, i try this code is no change too

The same thing happens for me, now I'll try to change the code

**Comment by tenkovroman** [comment]
<img width="411" alt="Screen Shot 2020-07-11 at 12 12 06" src="https://user-images.githubusercontent.com/38020206/87218825-bdb89c00-c36f-11ea-88e3-98115ca893f1.png">

No host specified in URI file:///

**Comment by tenkovroman** [comment]
> <img alt="Screen Shot 2020-07-11 at 11 16 23 AM" width="1121" src="https://user-images.githubusercontent.com/10402500/87216234-f9e7fe80-c367-11ea-83ed-714704aa6c09.png">
> 
> I see it's showing stores on my source code.

Please delete this screenshot
