### ISSUE TITLE
https://github.com/inspireui/support/issues/3927

### ISSUE THREAD

**Issue by michaelbrinkworth** [inspireui/support#4105]
https://github.com/inspireui/support/issues/3927 I face same issue. products not being fetched in ios simulator but is working ifne in fluxbuilder. I have sent invite to my repo with all the required files in there for proof!

**Comment by minhcasi** [comment]
could you share the screenshot issues?

**Comment by michaelbrinkworth** [comment]
<img width="1353" alt="Screen Shot 2020-07-09 at 5 48 41 am" src="https://user-images.githubusercontent.com/55236695/86963427-dd04cd00-c1a7-11ea-980b-67125da6889a.png">

**Comment by michaelbrinkworth** [comment]
<img width="879" alt="Screen Shot 2020-07-09 at 5 59 19 am" src="https://user-images.githubusercontent.com/55236695/86964408-5b15a380-c1a9-11ea-8a40-03f81eed9fda.png">

**Comment by minhcasi** [comment]
@michaelbrinkworth - pls note that screenshots from Fluxbuilder is based on the fluxstore app (woocommerce) - as i can see your purchase is used Fluxlisting app that may not compatible

**Comment by michaelbrinkworth** [comment]
It says shopify bruh, because its shopify listing. https://codecanyon.net/item/fluxstore-shopify-the-best-flutter-ecommerce-app/25877299

**Comment by michaelbrinkworth** [comment]
i sent github invite  https://github.com/michaelbrinkworth/mjshoppng

**Comment by minhcasi** [comment]
Please help us to submit this form and fill all required Shopify License to continue with the support  - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

**Comment by michaelbrinkworth** [comment]
done. i invited your github for source code.

**Comment by michaelbrinkworth** [comment]
?

**Comment by minhcasi** [comment]
@luyx2412 - pls helpt o investigate this issue

**Comment by michaelbrinkworth** [comment]
yeh..... I invited email to github repo

**Comment by michaelbrinkworth** [comment]
hello

**Comment by michaelbrinkworth** [comment]
2 dyas now..

**Comment by michaelbrinkworth** [comment]
3 days now

**Comment by luyx2412** [comment]
Hi @michaelbrinkworth Sorry for reply you late. I enter your repo but it show 404
![image](https://user-images.githubusercontent.com/8909619/87295352-3dd93000-c52f-11ea-960e-bc40f0141405.png)

Thanks

**Comment by michaelbrinkworth** [comment]
I sent an. invite to inspireui as instructed.

**Comment by michaelbrinkworth** [comment]
i cant have it on public as you guys get angry. let me know what you need me to do

**Comment by michaelbrinkworth** [comment]
I feel like everyone else is getting help but me

**Comment by michaelbrinkworth** [comment]
@minhcasi

**Comment by michaelbrinkworth** [comment]
any progress?

**Comment by luyx2412** [comment]
hi @michaelbrinkworth Sorry i still did not see your repo on github, so can you send me again?

Thanks

**Comment by michaelbrinkworth** [comment]
Like I said. I sent an email.... are you asking for another email? 

inspireui.team@gmail.com  .. https://github.com/michaelbrinkworth/mjshoppng i put it on public since ya keep getting 404

**Comment by luyx2412** [comment]
Hi @michaelbrinkworth Please do not pubic your project which will effect license. So please change to private your project and upload the project in google drive and send via inspireui.team@gmail.com

Thanks

**Comment by michaelbrinkworth** [comment]
than why keep saying you cant access it...

**Comment by michaelbrinkworth** [comment]
nah just accept my invite. i dont have google drive.

**Comment by michaelbrinkworth** [comment]
![Screen Shot 2020-07-18 at 5 55 44 pm](https://user-images.githubusercontent.com/55236695/87848047-eddbde00-c91f-11ea-8002-85e07a3128ab.png)

**Comment by michaelbrinkworth** [comment]
???

**Comment by luyx2412** [comment]
Hi @michaelbrinkworth I accepted the invitation, let me investigate and reply you soon.

Thanks

**Comment by minhcasi** [comment]
@michaelbrinkworth  - could you give an update - thank you!

**Comment by michaelbrinkworth** [comment]
What do you mean.... YOU GIVE ME UPDATE lol

**Comment by michaelbrinkworth** [comment]
18 days this ticket has been open for now.

**Comment by luyx2412** [comment]
hi @michaelbrinkworth Sorry about for delay.  Please pull latest code in fluxshopify repo. We just fixed some issues related this issue.

Thanks

**Comment by minhcasi** [comment]
Let us know if you have any extra questions - thank you!
