### ISSUE TITLE
One problem in the night mode and another problem

### ISSUE THREAD

**Issue by haidarsalim** [inspireui/support#4106]
FluxNews Version: 1.4.1
Flutter : v1.17.3

The problem is explained in the next video
https://vimeo.com/436229643

1- Keeping the settings to stay at night mode when activated
2- signed in. There is a delay in the automatic login process

**Comment by dttrung26** [comment]
Hi @haidarsalim , 
1. As I explained in previous tickets related to `DarkTheme`, FluxNews currently supports for storing `DarkTheme` at user session only. We will add a feature for storing `DarkTheme` at local devices in next patch. You can either wait for the next release, which may come in next month, or you can investigate by playing around with this packagehttps://pub.dev/packages/localstorage if you are really in need of this feature.
2. Could you provide us a video for this issue? So far login feature still works fine in FluxNews demo. Please bear in mind that emulator device's performances could be negatively affected by your PC/ laptop resources (lack of RAM, low-quality graphic card, ...)

**Comment by haidarsalim** [comment]
I am using an iPhone 
Upon entering directly into the application, you cannot write a comment. You can comment only when the page is changed

I would like to keep gadgets when changing theme  Would you please explain to me how I can fix it

**Comment by haidarsalim** [comment]
Another video explains the login process
https://vimeo.com/436983683
I made a comparison on my iPhone with the demo app the same problem on the android versions

application does not retain the login data, there is a clear delay in the login process. The page must be changed, and the login will be recorded

**Comment by haidarsalim** [comment]
**Do these errors affect?**
```
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\connectivity-0.4.8+5\android\src\main\java\io\flutter\plugins\connectivity\ConnectivityBroadcastReceiver.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_admob-0.9.3+2\android\src\main\java\io\flutter\plugins\firebaseadmob\AdRequestBuilderFactory.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.13.4\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-5.4.5\android\src\main\java\io\flutter\plugins\urllauncher\WebViewActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\video_player-0.10.11+2\android\src\main\java\io\flutter\plugins\videoplayer\VideoPlayerPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\webview_flutter-0.3.22+1\android\src\main\java\io\flutter\plugins\webviewflutter\FlutterWebView.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
```
![56567](https://user-images.githubusercontent.com/54249914/87110051-cbd2c380-c26e-11ea-84b7-b20d4c550824.PNG)

**Comment by minhcasi** [comment]
@haidarsalim - this is cache issue on your simulator - pls try to run `flutter clean` - ref: https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

Make sure to remove the existing fluxnew app on your simulator - thank you!

**Comment by haidarsalim** [comment]
@minhcasi  Hope you answer the main topic

**Comment by dttrung26** [comment]
Hi @haidarsalim , 

sorry for the late response, 
Due to the inconsistency in your term definition,  could you please declare what is "gadgets"? And could you provide us a video explaining the process to encounter the comment error because so far so good, FluxNews comment still works fine? 
For the user saving session in the setting page, currently, FluxNews uses local storage to store user data into local devices. However, the FluxFood app, which you downloaded from App Store, and the app you are customizing, are using the same LocalStorage identifier and same kLocalKey as well. This might lead to the problem. 
As Mr.Minh has explained above, please try the FluxFood, clean the cache, and run your app again. 

Once again, so sorry for such a late reply.
Happy coding.

**Comment by haidarsalim** [comment]
Can I send the project to you?

**Comment by dttrung26** [comment]
Hi @haidarsalim , 
due to [InspireUI support policy](https://inspireui.com/support-policies/), we do not provide customizing support (remaining gadgets on theme changing request) on standard support licenses. If you wish to have your app customized, please take a look at extended licenses. 
Let me know if you still have any question, 
Nice day!

**Comment by dttrung26** [comment]
`application does not retain the login data, there is a clear delay in the login process. The page must be changed, and the login will be recorded` - fixed in next patch.
