### ISSUE TITLE
ITMS-90809: Deprecated API Usage – New apps that use UIWebView are no longer accepted

### ISSUE THREAD

**Issue by josephpnc** [inspireui/support#4108]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 

I submitted the app to App Store for TestFlight testing. And this is the info sent back by Apple:

ITMS-90809: Deprecated API Usage – New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more.

+ Product & version: mstore-pro 3.9.8
+ Flutter (or React Native) version: React Native
+ Testing Device/Simulator: App Store
+ Screenshot issues (drag the file to attach here): 

![image](https://user-images.githubusercontent.com/12858588/86869109-2ac5fa80-c100-11ea-9232-d4597a3202e2.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by josephpnc** [comment]
purchase verification just submitted. I can't find config folder, just common folder.

![image](https://user-images.githubusercontent.com/12858588/86869763-5695b000-c101-11ea-85f7-2efad3427be5.png)

**Comment by luyx2412** [comment]
Hi @josephpnc please follow this article to fix the issue https://github.com/inspireui/support/issues/3832

Thanks

**Comment by luyx2412** [comment]
Closed! Feel free to create new issue. Tks
