### ISSUE TITLE
Checkout Redirects to Webview

### ISSUE THREAD

**Issue by topmosth** [inspireui/support#4109]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
Checkout page redirects in Webview when I'm trying to checkout
+ Product & version: Fluxstore Multi Vendor - Flutter E-commerce Full App
+ Flutter (or React Native) version: Flutter
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 
![image](https://user-images.githubusercontent.com/57655242/86872119-31f40500-c10e-11ea-92e2-20f19d959b65.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhtruong315** [comment]
Hi @topmosth can u show me your config? What do you config for checkout:  OnePageCheckOut, NativeOnePageCheckout, native payment gateway or webview checkout?
<img width="1063" alt="Screen Shot 2020-07-10 at 8 09 00 AM" src="https://user-images.githubusercontent.com/10402500/87105360-ec0d7d00-c284-11ea-8b3e-5a3551f6be1e.png">

**Comment by minhtruong315** [comment]
Hi @topmosth how?

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
