### ISSUE TITLE
[MStore] null is not an object(evaluation 'blob.data')

### ISSUE THREAD

**Issue by 04Ank** [inspireui/support#411]
- Product: [Mstore Pro]
 - Your Purchased Code: 
a356d2b4-3c3b-4fa3-89cd-e710b8d96e64

**Describe the issues**
I have downloaded your new release and When trying to rub your new release in my windows 10 X64  without modifying any content its generating an error" null is not an object (evaluating 'blob.data')" in android aap, screen short attached . 
**Screenshots**
![WhatsApp Image 2019-03-19 at 16 44 08](https://user-images.githubusercontent.com/48328340/54602332-6b12ec80-4a67-11e9-87c9-09af9ee6a68f.jpeg)

**Comment by luyx2412** [comment]
Related https://github.com/inspireui/support/issues/398

**Comment by sashaba** [comment]
why is this post closed. I have this issue and I haven’t been able to find a solution. #398 doesn’t provide a solution.

**Comment by binaryversion** [comment]
Hi 04Ank, did you manage to solve the issue? I'm having this problem just with Android, on IOs works perfectly.

**Comment by 04Ank** [comment]
Still have the same issue with android
