### ISSUE TITLE
Problem in emulator android studio 

### ISSUE THREAD

**Issue by queenarwa** [inspireui/support#4110]
Launching lib\main.dart on Android SDK built for x86 in debug mode… Running Gradle task ‘assembleDebug’...

FAILURE: Build failed with an exception.

What went wrong: A problem occurred configuring root project ‘android’. > Could not resolve all artifacts for configuration ’:classpath’. > Could not resolve com.android.tools:r8:1.5.25. Required by: project : > Could not resolve com.android.tools:r8:1.5.25. > Could not get resource ‘http://storage.googleapis.com/r8-releases/raw/com/android/tools/r8/1.5.25/r8-1.5.25.pom'. > Could not GET ‘http://storage.googleapis.com/r8-releases/raw/com/android/tools/r8/1.5.25/r8-1.5.25.pom'. > Connect to localhost:80 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect
Try: Run with—stacktrace option to get the stack trace. Run with—info or—debug option to get more log output. Run with—scan to get full insights.
Get more help at https://help.gradle.org
BUILD FAILED in 3m 39s Exception: Gradle task assembleDebug failed with exit code 1

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by queenarwa** [comment]
Mr. Minhcasi
The verification request was filled out a few days ago and was not answered
The verification request will now be filled out again

**Comment by minhcasi** [comment]
@queenarwa - thank you for the quick response

Would you mind to check this solution to correct your Flutter environment - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1
