### ISSUE TITLE
Create Listing From App

### ISSUE THREAD

**Issue by znchung** [inspireui/support#4111]
Detail Issues:

Is there a way to submit/create a new listing from the app? Is that something that is currently supported? 

Thanks!

Product & version: FluxListing, Listeo
Flutter (or React Native) version: Flutter 1.17.1
Testing Device/Simulator: N/A

PS:  I have submitted an issue before. Unfortunately, I do not have a ticket ID, but here's the reference to an issue I've submitted before. #[3581](https://github.com/inspireui/support/issues/3581)

**Comment by philipvu30** [comment]
Hi,

I'm sorry but this feature has not been implemented yet.

**Comment by znchung** [comment]
Ahhh cool! Thanks ! :) @philipvu30
