### ISSUE TITLE
[Req Urgent Support] Unable to render app output

### ISSUE THREAD

**Issue by touchmarkdescience** [inspireui/support#4112]
Getting the exact issue as in the ticket - Error run fluxstore app android studio [#3759](https://github.com/inspireui/support/issues/3759)

Unable to build app.

ERROR LOG:
```
Error occurs while we run the command flutter build apk --split-per-abi

Error: FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app_settings:compileReleaseAidl'.
> Failed to find Platform SDK with path: platforms;android-R

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get
 full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16s
Running Gradle task 'assembleRelease'...
Running Gradle task 'assembleRelease'... Done                      17.1s
Gradle task assembleRelease failed with exit code 1
```

Product:  Fluxstore WooCommerce
Version: 1.7.5
Flutter Version: 1.17.5

Screenshot:
[errorFlux](https://user-images.githubusercontent.com/58761094/86886329-5c48c100-c114-11ea-9d96-60aaaa6f2041.png)

**Comment by touchmarkdescience** [comment]
submitted your verify form with purchase code.  Need to deploy to playstore today.

Do the needful, thanks in advance.

**Comment by minhcasi** [comment]
@touchmarkdescience - could you help to check solution on this ticket #3708

**Comment by touchmarkdescience** [comment]
@minhcasi  sure, will do it.   My development team complains that there is not complete documentation on building app or hosting on Apple / Google marketplace.

Could you point us out if you have...!!

**Comment by minhcasi** [comment]
@touchmarkdescience - please help to check this document guide https://docs.inspireui.com/fluxstore/delivery/ - there is the video as well - https://docs.inspireui.com/fluxstore/delivery/

That guide could use along with the guide from google team - https://flutter.dev/docs/deployment/android

Let us know if you have any question

**Comment by touchmarkdescience** [comment]
> 
> 
> @touchmarkdescience - could you help to check solution on this ticket #3708

the ticket you shared is not helpful.  still facing same issue.

unable to build gradle.....   is their any other mode of support available...???

waiting for 11 hours for a reply is killing us.

**Comment by minhcasi** [comment]
@touchmarkdescience - could i know if you are using MacOS or Window ? - please help to try this solution as well - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

**Comment by touchmarkdescience** [comment]
@minhcasi  I AM USING WINDOWS (OS - 10)

WILL CHECK THE SOLUTION.

**Comment by minhcasi** [comment]
Let us know your checking - thanks

We will update new latest release to gitlab, please submit here if you don't have an account yet - http://gitlab.inspireui.com/

**Comment by touchmarkdescience** [comment]
@minhcasi  No help from the links you shared.  Could you help us out in any other means.  

Because we are losing time and trust of the customer.

**Comment by touchmarkdescience** [comment]
@minhcasi  waiting for your help.   Can you share any previous version, which was successfully build and used.

**Comment by minhcasi** [comment]
@touchmarkdescience - sorry that we could not help to troubleshooting the installing issues that case many reasons, we also clarify from our support scope - https://inspireui.com/support-policies/

Please try your best with the following solutions:
- Re-install the Flutter could help https://flutter.dev/docs/get-started/test-drive?tab=vscode
- Re-install the Android Studio SDK
- Clean up the Cache on Flutter https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

If you could not use the product far or not satisfy with the product, we could help with the refund submit as well, thank you for your time!
