### ISSUE TITLE
Issues With New version Fluxstore 1.7

### ISSUE THREAD

**Issue by darsadask** [inspireui/support#4113]
1) Shop Button on the Menu is not working. 
	https://github.com/inspireui/support/issues/1862
Couldn’t find solutions online, mentioned supported via Skype in the above link. Kindly help us in fixing the same.

2) Cart Text baseline is unaligned in the Tab-bars. Please find the attached screenshot.

3) One page native checkout is not working even after enabling it in payment settings, still taking us to web view.

unable to access http://verify.inspireui.com/ for uploading product purchase code

![WhatsApp Image 2020-07-02 at 12 20 43 PM](https://user-images.githubusercontent.com/5181183/86895853-b2bcfc00-c122-11ea-9531-8443d1547e4c.jpeg)

**Comment by minhcasi** [comment]
pls help to try this link https://docs.google.com/forms/d/e/1FAIpQLScWOjkAJIWJ9rgb9alopfOqLsJrGKbFM5cCYj1JBfLKLsBblQ/viewform

**Comment by minhcasi** [comment]
@darsadask - thank you for the detail

1-2. These features will be fixed on latest release `1.7.6`

3. The one-page checkout will be work via Webview to support with extra plugins from woocommerce
