### ISSUE TITLE
No Such Method Error

### ISSUE THREAD

**Issue by topmosth** [inspireui/support#4114]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
Products are unclickable, I'm also getting The method 'toJson' was called on null. Receiver: null Tried calling: toJson() and The getter 'name' was called on null. Receiver: null Tried calling: name when i'm trying to checkout. 
+ Product & version: Fluxstore Multi Vendor - Flutter E-commerce Full App
+ Flutter (or React Native) version: Flutter
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 
![image](https://user-images.githubusercontent.com/57655242/86899514-b2c9f580-c13c-11ea-84ce-594451b4359e.png)
![image](https://user-images.githubusercontent.com/57655242/86899597-ce350080-c13c-11ea-826a-cb25310d18eb.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@topmosth - pls help to comment this ticket into #4109 - my team will help to check them all - thank you!
