### ISSUE TITLE
problem in switching currencies 

### ISSUE THREAD

**Issue by andyodoo** [inspireui/support#4115]
**_Step 1 (require): describe detail issues & screenshots_**
+ Product & version:
fluxstore woocommerce 1.7.5
+ Flutter (or React Native) version: 
flutter
+ Testing Device/Simulator: 
android
@minhcasi I'm having  problem in switching currencies 
I'm able to switch currencies and see the correct rate in  all products (shop)page  
but we i entered the product page its shows only base currency 

the products page
<img width="537" alt="Screen Shot 2020-07-08 at 12 22 52 PM" src="https://user-images.githubusercontent.com/50452375/86901782-c0b85000-c115-11ea-96e8-c9ec8e7cd10f.png">

the product page 
<img width="537" alt="Screen Shot 2020-07-08 at 12 23 05 PM" src="https://user-images.githubusercontent.com/50452375/86901812-c7df5e00-c115-11ea-8ae9-532835f148d4.png">

I'm using WPML multi currency  in woocommerce 
and I did follow 
please help us fix it 
 
[common.zip](https://github.com/inspireui/support/files/4889988/common.zip)

**Comment by ameenbadri7** [comment]
We wanted to thank you for your patience during this busy time.
We currently have reduced staff and a significantly higher volume of inquiries. We’re working as hard as we can to get to your request as soon as possible, pls help to check our old wpml related tickets on this link https://github.com/inspireui/support/issues?q=wpml
thank you



https://github.com/inspireui/support/issues?q=wpml

**Comment by andyodoo** [comment]
Dear  @ameenbadri7  
We did buy your app long time ago , and we are not receiving the proper support on time 
its not our issue that you are so busy in the last 2 months 
we need you to solve the bellow bug asap :


the bug is the currency exchange rate works everywhere else , but dose not work with the product page price .
please send us the solution asap as we are so late for going live because the above bug and  we are losing so much money of being late ..



<img width="434" alt="Screen Shot 2020-07-08 at 1 20 13 PM" src="https://user-images.githubusercontent.com/50452375/87040672-bb343600-c1f9-11ea-8c45-5571377ab861.png">
<img width="434" alt="Screen Shot 2020-07-08 at 1 18 40 PM" src="https://user-images.githubusercontent.com/50452375/87040682-bff8ea00-c1f9-11ea-9362-38cb03082e6d.png">

**Comment by enriqueleon80** [comment]
If this is the only bug holding you back. why not just try Fiverr.com and have someone look at that code and issue a 2 line fix? 

I am not being sarcastic, this is a real suggestion.  This team is no doubt very busy with dozens of requests, giving you an quick solve.

**Comment by andyodoo** [comment]
@enriqueleon80 
we did try to fix using so many different developers but not all of them know your code 
also this bug is not only in our side its an bug in all your demos 
mobile apps ( ios , android ) ,  and fluxbuilder  and our purchased app and I'm sure an issue such currency exchange rate is major issues and you have a fix for it 
its been a a month since the last update if you are working in fixing your app bugs you would notice it 
but instead  you keep asking you customers to share your own code with 5$ developers which is very bad for your "business"

**Comment by enriqueleon80** [comment]
@andyodoo 

I should have noted, I am a customer just like you.  I am in no way related to INSPIREUI, I just bough their app.  Just to be clear.

I've found my own bugs as well, which I have fixed.  Others I live with until they get addressed.  It's the price you pay when you sign up for a template solution.  Perfection (although this app comes close) can only be had with a fully custom/dev built app.

Good luck.

**Comment by andyodoo** [comment]
@enriqueleon80 Sorry i thought you are one of them 
God help you and help us 

dear @ameenbadri7  @minhcasi 
we really need you to fix the bug asap 


best regards 
Andy

**Comment by minhcasi** [comment]
@andyodoo - this bug will be fixed on next `1.7.6` that will be ready in next couple of day - thank you

**Comment by andyodoo** [comment]
Dear @minhcasi, thank you and waiting your update as soon as you relese1.7.6.

Best Regards
Andy

**Comment by minhcasi** [comment]
It's available on our Gitalb, it will be ready with the download package on Monday - thank you!

**Comment by minhcasi** [comment]
Fixed on the latest `1.7.6`, let us know if you have any issues - thank you!
