### ISSUE TITLE
Hide Booking Button in the App, when there is no booking avaibel

### ISSUE THREAD

**Issue by heftipascal1** [inspireui/support#4117]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: In the App, there is the Booking Button visible, but there is no option to book something, how we can disable this button?

![booknow](https://user-images.githubusercontent.com/67189625/86916532-067c1500-c124-11ea-90ae-97b715c8bfa1.JPG)

+ Screenshot issues (drag the file to attach here):

**Comment by philipvu30** [comment]
Hi,

In lib/screens/detail/listing/product_title.dart, comment these lines
![image](https://user-images.githubusercontent.com/54442328/87147982-c493d000-c2d7-11ea-8c8c-359f4be21f04.png)

**Comment by heftipascal1** [comment]
Thanks for the help!

**Comment by heftipascal1** [comment]
Hi, i need some help to hide something in the App:

1. Hide the Author from the Blog, how we can do it?
![Screenshot_1594496600](https://user-images.githubusercontent.com/67189625/87232461-8b368f80-c3bf-11ea-9037-fe654fee9141.png)

2. The Default Language is not working. 
![Screenshot_1594496740](https://user-images.githubusercontent.com/67189625/87232505-e8324580-c3bf-11ea-90b2-724afc72a696.png)
When we click on German, then the translation is working. But when the App starts, then the language is per default english... We have put in config.dart also " "DefaultCountryISOCode": "de","  How we can fix that?

3. The Login is required, "IsRequiredLogin": true,  but when we start the App, then click on Register or Login (Screenshot in German) then it switch directly to the App, without registration or login? How we can fix that?
![Screenshot_1594496871](https://user-images.githubusercontent.com/67189625/87232578-2def0e00-c3c0-11ea-8cfd-370b71ac1c84.png)


- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by heftipascal1** [comment]
Hi, is there any update to my comments?

**Comment by philipvu30** [comment]
Hi,

1. In lib/widgets/blog/detailed_blog/detailed_blog_view.dart, remove lines 95 -> 108. Or you could do this: on Windows use ctrl + shift + F - on Mac user cmd + shift + F to find "**by ${widget.item.author**" and remove the widget that covers this term. For example: https://tppr.me/v1jtf

2. Replace this file [app.dart.zip](https://github.com/inspireui/support/files/4922652/app.dart.zip) in lib/models/app.dart.
Add this line   `"DefaultLanguage": "en"` to kAdvanceConfig in lib/common/config.dart

3. Currently fixing.

**Comment by heftipascal1** [comment]
Thanks, i have found all the things. How long will the fix taken for the Login? Or can we deaktivated it for the meantime?

**Comment by philipvu30** [comment]
Hi,

As I checked the code, it turned out this option only hides the Done button on OnBoardingScreen. I don't know if this is good practice or not. 
If you have any suggestions for this feature, kindly post it here and we'll consider adding it.

Thank you.

**Comment by heftipascal1** [comment]
Ok, no ... but i thing it would be for the meantime a good solution to hide the Login / Register Text. So that the User are not irritated

**Comment by philipvu30** [comment]
> Ok, no ... but i thing it would be for the meantime a good solution to hide the Login / Register Text. So that the User are not irritated

You can hide the onboarding screen in lib/common/config.dart by removing the content inside this variable

![image](https://user-images.githubusercontent.com/54442328/87759532-aa5a7480-c838-11ea-91bc-838d1ee0b13b.png)

**Comment by philipvu30** [comment]
Closed as no response in more than 2 days.
