### ISSUE TITLE
unlink my license 

### ISSUE THREAD

**Issue by Modch** [inspireui/support#4118]
i linked my license to a domain i was just testing and now when am trying to link it to my main domain its telling me its already linked to a domain so please is it possible to unlink my license. i mean Mstore API plugin

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
Yes, it is possible -  you could use the fluxbuilder to reset the code one time - http://fluxbuilder.com/

**Comment by Modch** [comment]
it didnt work or you didnt get my question am talking about the plugin Mstore APi when i wanna connect my main domain its showing that license is already linked to my other domain, the bulider didnt fix it.

**Comment by minhcasi** [comment]
@Modch - please send your license to support@inspireui.com - we will help to reset it - thank you!

**Comment by Modch** [comment]
I did already i send private ticket to support. 

But till now nothing

**Comment by minhcasi** [comment]
@Modch - it is reset - pls try again - thanks

**Comment by Modch** [comment]
Yea thanks alot

**Comment by minhcasi** [comment]
@Modch - We're glad that it help, please give us some feedback/rating to this page https://codecanyon.net/downloads  if the product is helpful for your business, we are working hard to update more awesome and powerful features on next coming version release. Let us know if you have any feedback. Thank you very much 😊
