### ISSUE TITLE
Language Defualt not working

### ISSUE THREAD

**Issue by heftipascal1** [inspireui/support#4119]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: We have add the Language German, but we cannot use it as default by programm starts.. We must always switch in the language settings
![Screenshot_1594211828](https://user-images.githubusercontent.com/67189625/86919476-958b2c00-c128-11ea-8b51-613273e4e7a2.png)
![Screenshot_1594211822](https://user-images.githubusercontent.com/67189625/86919477-9623c280-c128-11ea-80f9-277bf546064f.png)
![Screenshot_1594211826](https://user-images.githubusercontent.com/67189625/86919478-96bc5900-c128-11ea-9305-8e287662beda.png)

**Comment by minhcasi** [comment]
@heftipascal1 - pls help to give your all comment to one open ticket #4115 4117
