### ISSUE TITLE
[ListApp] List App problem with CeBuilder

### ISSUE THREAD

**Issue by thespottedrabit** [inspireui/support#412]
**Mandatory Info (please complete the following information):**
 - Product: [e.g. MStore, ListApp] 
 - Your Purchased Code: [get from https://codecanyon.net/downloads]
(we may not reply if you are not our customer)

LISTAPP - MYLISTING
d8e3e06f-3447-4914-82e7-e55ac10bb234

**Describe the issues**

Hello, Ce Builder says it doesn't support the project when I try to upload the files in the "Setup" section. I really don't want to pay $400 to have you install it on the app stores but I am lost on what to do.

**Screenshots**

![image](https://user-images.githubusercontent.com/13178140/54653401-2fd0e780-4a80-11e9-8017-0d3301ad79ff.png)

**Additional context**
Add any other detail logs about the problem here.

**Comment by minhcasi** [comment]
Hi, pls try to upgrade the inspireui to latest one 0.27 - http://inspireui.com - thanks
