### ISSUE TITLE
Editing some fields on form and UI

### ISSUE THREAD

**Issue by basithzan** [inspireui/support#4120]
Hi

Can you please help me with these?

1. How can I enable the swipe feature here?
![IMG_5703](https://user-images.githubusercontent.com/12207952/86926268-7bb10f80-c14f-11ea-931d-6879df78021f.jpg)

2. How can i increase the product image size here? In default bottom portion of the image is cropped.
![IMG_5704](https://user-images.githubusercontent.com/12207952/86926367-971c1a80-c14f-11ea-9220-16593456ec55.jpg)

3. How can i edit these texts?
![IMG_5705](https://user-images.githubusercontent.com/12207952/86926709-05f97380-c150-11ea-9254-1dd80e402942.jpg)

4. Login with apple shows this error.
![IMG_5706](https://user-images.githubusercontent.com/12207952/86926777-190c4380-c150-11ea-962f-ff772de98a87.PNG)
@minhcasi @

**Comment by ameenbadri7** [comment]
**for issue 1-** 
you can go to `lib\common\config\products.dart` and change the `"layout": "simpleType",` to "layout": "fullSizeImageType",

and then see the new change. btw you have 3 themes to select from 
```
( simpleType,
  fullSizeImageType,
  halfSizeImageType,
  oneQuarterImageType)
```
use our [documentions](https://docs.inspireui.com/fluxstore/home-layout/) to find other good hints for customizing your app as you like.
 
**for issue 2:** 
you could try to use the [Inspector Tools ](https://www.youtube.com/watch?v=yGMt3Y20Zmg
) to support the customization of the fluxstore app.

**for issue 3:** 

we don't take customization requests for the regular license but you can buy the Extended License or Support Pack pls help to check our [support policies ](https://inspireui.com/support-policies) and email us with your request via our email minhcasi@gmail.com and inspireui-team@inspireui.com.

**for issue 4:** 
you could try to do [ this tutorial ](https://docs.inspireui.com/fluxstore/sign-in/
)again until you made it. it's working 

- thank you.

**Comment by basithzan** [comment]
1. the remaining layout doesn't have a zoom feature. ( I just want to enable swipe feature on this simple layout)
2. Flutter inspector tool does not show the exact file path 
https://drive.google.com/file/d/1IjzYoPOj63SERBIlu8jJ_7Rr31toBaOp/view?usp=sharing
3. Can you please tell me the file path to edit/translate checkout field texts?
5. I'm getting following response while login through SMS
![Screenshot 2020-07-09 at 2 00 14 PM](https://user-images.githubusercontent.com/12207952/87017149-3e9b5a80-c1ed-11ea-8d20-80c48fbf335f.png)

**Comment by ameenbadri7** [comment]
you should try with the customization fix because your issue is related to customization

and you should notice our [support policies](https://inspireui.com/support-policies/).
thank you

**Comment by basithzan** [comment]
3. in india Zip-code is not used, it called PIN code or postal code, so there should be an option to edit the text.
4. This one is pure technical issue.

Pls consider.
