### ISSUE TITLE
Problem with payment refs in Cart index js

### ISSUE THREAD

**Issue by Myced** [inspireui/support#4123]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: I bough MStore for Magento and started customizing it... The checkout process was working very fine.. Until late, I am now getting this error.. **TypeError: undefined is not an object (evaluating '_this.refs.payment.getPayments')** 
This is triggered by the line 230 or so.. in the file **Project/src/containers/Cart/index.js**
When I do a log of this.refs it get an empty object... instead of an object the contains a ref to payment
I have been trying to fix it for about 4 days now with not success. So I decided to contact you.

+ Product & version: MStore Magento - the complete react native app for Magento 2 
+ Flutter (or React Native) version: React Native sdk  35
+ Testing Device/Simulator: Testing Device
+ Screenshot issues (drag the file to attach here): 

![WhatsApp Image 2020-07-08 at 3 36 36 PM](https://user-images.githubusercontent.com/22053178/86934189-50b8c280-c133-11ea-87ba-35df62c49845.jpeg)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by Myced** [comment]
I had submitted earlier.. 

Just submitted again.

**Comment by minhcasi** [comment]
@minhtruong315 - pls suggest on this issue

**Comment by minhtruong315** [comment]
Hi @Myced give me your skype? I will contact you via skype and help you check via teamviewer.
Thanks

**Comment by Myced** [comment]
Great. 
Here is my skype id **tncedric**

**Comment by minhtruong315** [comment]
Hi @Myced I messaged you on the skype. pls check
Thanks

**Comment by minhtruong315** [comment]
There is limitation from current mstore app that does not restrict the country/state which is required to complete the checkout process, if you select the wrong state/country the checkout will be fail - we have noted as feature upgrade and report to the team to fix it later - thank you!
