### ISSUE TITLE
Mstore expo - Failed to login or sign up

### ISSUE THREAD

**Issue by marknestor261** [inspireui/support#4125]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 1. I am failing to login or sign up in app. It just keeps loading forever, until i close the app.
                         2. Product color variations do not show colors assigned in admin, it shows black color all over and a few other 
                             colors but not the correct colors.
+ Product & version: 3.9.7
+ Flutter (or React Native) version: 3.11.5
+ Testing Device/Simulator: Tecno Camon 12 Air
+ Screenshot issues (drag the file to attach here): 
![Screenshot_20200708-202143](https://user-images.githubusercontent.com/46901102/86951068-b324b980-c159-11ea-9d03-e2606d567f0c.png)
![Screenshot_20200708-204636](https://user-images.githubusercontent.com/46901102/86954217-43fd9400-c15e-11ea-963e-19d3989af663.png)
![Screenshot_20200708-204711](https://user-images.githubusercontent.com/46901102/86954256-52e44680-c15e-11ea-99ae-faeb2540270c.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by wolverineee92** [comment]
Same problem on my app also....please help

**Comment by minhcasi** [comment]
@wolverineee92 @marknestor261 - please try to update to latest Mstore 4.0 and mstore-api plugin to fix this issue.

Make sure to activate the License from the Mstore API plugin (WordPress side)

Thank you!

**Comment by wolverineee92** [comment]
I am using the latest mstore 4.0 and mstore-api with activate license....still login error...only loading....signup is working fine...

**Comment by marknestor261** [comment]
> @wolverineee92 @marknestor261 - please try to update to latest Mstore 4.0 and mstore-api plugin to fix this issue.
> 
> Make sure to activate the License from the Mstore API plugin (WordPress side)
> 
> Thank you!

@minhcasi I will do that. And what about the color variation issue, will that fix it too?

**Comment by wolverineee92** [comment]
> > @wolverineee92 @marknestor261 - please try to update to latest Mstore 4.0 and mstore-api plugin to fix this issue.
> > Make sure to activate the License from the Mstore API plugin (WordPress side)
> > Thank you!
> 
> @minhcasi I will do that. And what about the color variation issue, will that fix it too?

This issue coming from latest version mstore4.0.0....working fine in mstore 3.9

**Comment by minhcasi** [comment]
@luyx2412 - pls try to have a look on this issue - thank you!

**Comment by marknestor261** [comment]
Hello, now am failing to do yarn install, keeps giving me an error.
![vscode-react-error](https://user-images.githubusercontent.com/46901102/87113477-ffb1e700-c276-11ea-816c-21365c88bbff.PNG)

**Comment by luyx2412** [comment]
Hi @marknestor261 i saw your log error is using node v8. So please move to node v10 which will fix your issue.
![image](https://user-images.githubusercontent.com/8909619/87162271-e4cf8900-c2ef-11ea-87fb-a6dfbd7dde56.png)

Thanks

**Comment by marknestor261** [comment]
But my node version is 12.14.0
![node-version](https://user-images.githubusercontent.com/46901102/87173333-4129ad00-c2de-11ea-8994-603c266e0b50.PNG)

**Comment by marknestor261** [comment]
@luyx2412 i have managed to run and set up the new version, but still cannot login and variation issue is still there.

**Comment by marknestor261** [comment]
@luyx2412 i have verified license of plugin and i can login now, but variations are still messed up. It still shows different colors, mostly black.
