### ISSUE TITLE
Multiple issues with ordering

### ISSUE THREAD

**Issue by sabieworld** [inspireui/support#4126]
+ Detail Issues: 
1. Saved addresses from website are not listed at app side
2. Orders made via app are not showing at orders section in backoffice
3. No confirmation emails getting for orders made via app
4. Orders made from apps can be seen from dashboard recent orders widget at backoffice. There order status is blank.
5. when we open such orders from there, it has no invoice address or delivery address
6. no invoices has been generated for such orders

+ Product & version:
Fluxstore Prestashop - Flutter E-commerce Full App 1.1

+ Flutter (or React Native) version:
flutter 1.17.5

+ Testing Device/Simulator: 
Nexus 6

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by sabieworld** [comment]
@ameenbadri7 already filled and submitted the form at http://verify.inspireui.com

**Comment by vumanhsn97** [comment]
@sabieworld 
Try with this module: 
[customapi.zip](https://github.com/inspireui/support/files/4895803/customapi.zip)

**Comment by sabieworld** [comment]
unable to install this module. it shows error code 500
![Screenshot_2020-07-11_15-20-10](https://user-images.githubusercontent.com/32928969/87224002-29a7fe00-c38a-11ea-84ef-8831537a6ec2.png)

**Comment by sabieworld** [comment]
@vumanhsn97 Still same issue. no changes in any of the reported issues.

**Comment by sabieworld** [comment]
@vumanhsn97 why no responses for a week..?

**Comment by vumanhsn97** [comment]
@sabieworld 
Please download lastest version and update this permission in Webservices https://tppr.me/fGCgb
Thanks!

**Comment by sabieworld** [comment]
Attributes are not showing in filter menu (category page). when i check getFilterAttributes function in services/prestashop.dart, it is not done (just returns null).

**Comment by sabieworld** [comment]
@vumanhsn97 do i need to open a separate ticket for the above mentioned issue..?
