### ISSUE TITLE
Extra fees not showing on checkout.

### ISSUE THREAD

**Issue by Saneleros** [inspireui/support#4127]
+We have extra fees on the woocommerce store, we charge customers the price plus an extra fee. For extra fee we use the plugin: WooCommerce Product Fees.

+ Product & version: woocommerce fluxstore

+ Testing Device/Simulator: Nokia One

![Screenshot 2020-07-08 at 20 42 10](https://user-images.githubusercontent.com/21216812/86958786-fa607980-c15c-11ea-92cf-050ea656e38e.png)
![Screenshot 2020-07-08 at 20 43 34](https://user-images.githubusercontent.com/21216812/86958794-fe8c9700-c15c-11ea-88df-313cc413f7dd.png)
![Screenshot 2020-07-08 at 20 43 58](https://user-images.githubusercontent.com/21216812/86958801-00565a80-c15d-11ea-8c77-a8fb07c1987c.png)
![Screenshot 2020-07-08 at 20 44 16](https://user-images.githubusercontent.com/21216812/86958802-02201e00-c15d-11ea-816b-8afbbc0abddd.png)
![Screenshot 2020-07-08 at 20 44 33](https://user-images.githubusercontent.com/21216812/86958805-03e9e180-c15d-11ea-89c6-f878a4119d8f.png)

Thank you so much for your time 😊

**Comment by ameenbadri7** [comment]
we don't take customization requests for the regular license but you can buy the Extended License or Support Pack and email us with your request via our email minhcasi@gmail.com and inspireui-team@inspireui.com.

you could try to use the [Inspector ](https://www.youtube.com/watch?v=yGMt3Y20Zmg)Tools to support for customization your app.

- thank you.

**Comment by minhcasi** [comment]
@Saneleros - sorry that the Fluxstore is not compatible with extra plugin installing and you will need to add some customization, please try your best

Let us know if you have any questions
