### ISSUE TITLE
[ListApp] how to remove the review icon from the apps.

### ISSUE THREAD

**Issue by Pavithran10** [inspireui/support#413]
**Required Info (please complete the following information):**
Product:[ListApp]
Version:1.6.1
Theme: MyListingr)

**Describe the bug**
hi, In listapp application after login the user account into the app. In the booking page message icon is avaiable in that icon inside review option send button not working. So, that any solution is there to clear the issue. otherwise, we plan to update it for later purpose. 

 **how to remove that message icon from that page or how to solve review send button** 

**Screenshots**
![msgicon](https://user-images.githubusercontent.com/46148046/54678920-200edd00-4b2c-11e9-9d65-8c9527144ab8.jpg)
![msgbutton](https://user-images.githubusercontent.com/46148046/54678927-27ce8180-4b2c-11e9-9f88-f14532a013ed.jpg)

**Comment by thangvo9x** [comment]
Hi.
1. Remove this block in Components/Detail/Footer/index.js 
<img width="260" alt="block" src="https://user-images.githubusercontent.com/23457178/54731329-4aaa7580-4bc0-11e9-83df-fca76cc678d8.png">
2. This is a error UI. We'll update it in the next version. You can edit it Components/Comment/styles.js
with style is css.sendView
Thanks

**Comment by Pavithran10** [comment]
thanks. i'll try and update
