### ISSUE TITLE
native payment -in app payment for for opencart framework

### ISSUE THREAD

**Issue by fahadmm98** [inspireui/support#4130]
hi ,
i would like to guide or give me a hint to modify my fluxstore  to accept payment in app not directed me checkout in my website (opencart platform) 
to be more reasonable for users to use app 
if users could not pay through the app  why i should make app

note: i already have sdk for payment provider company 

i highly appreciate your support . thanks

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**
proof TKT #3721

**Comment by minhcasi** [comment]
@fahadmm98 - you could search the PayPal method that is used to integrate as a native payment

<img width="1268" alt="Screen Shot 2020-07-09 at 09 40 56" src="https://user-images.githubusercontent.com/1459805/86991038-4bf21e00-c1c8-11ea-8094-ba4b118eb7a0.png">

<img width="1230" alt="Screen Shot 2020-07-09 at 09 41 46" src="https://user-images.githubusercontent.com/1459805/86991100-688e5600-c1c8-11ea-92ad-6b7768f79c83.png">

As this request is not included from our support scope, allow it to close the ticket - thank you for your time :)
