### ISSUE TITLE
Product Image doesn't work, 'Booking Now' button error

### ISSUE THREAD

**Issue by dibbo-ru** [inspireui/support#4132]
**_Step 1 (require): describe detail issues & screenshots_**
Detail Issues: 1. Product Images can't show
2. 'Booking Now'' Doesn't work 
3. Want to hide "Guest' option during Booking but can't
Product & Version: Flux Listing app for Listeo Website, V:1.4.2
Flutter (or React Native) version: Latest
Testing Device/Simulator: Android Studio
Screenshot issues (drag the file to attach here):

![111](https://user-images.githubusercontent.com/19253603/86969726-103b6200-c190-11ea-8763-fb542b30ff1e.png)
![333](https://user-images.githubusercontent.com/19253603/86969753-16314300-c190-11ea-83e6-a0537e534959.png)
![444](https://user-images.githubusercontent.com/19253603/86969757-17627000-c190-11ea-97d5-acf626daa045.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**
I HAVE SUBMITTED ALREADY

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@dibbo-ru - pls help us to move your all comments into same ticket support #4087 - thank you!
