### ISSUE TITLE
Getting Error on Add to Cart and not able to login

### ISSUE THREAD

**Issue by sachinsuper18** [inspireui/support#4133]
We are getting this error.

![WhatsApp Image 2020-07-09 at 10 43 40 AM](https://user-images.githubusercontent.com/67690113/87000561-038c2d80-c1d3-11ea-9633-e55126ea7941.jpeg)

Also when we are trying to login the application, we are unable to. We have created a new user which is showing in WP  but by using same ID, it doesnt move ahead. SS attached

![WhatsApp Image 2020-07-09 at 10 59 52 AM](https://user-images.githubusercontent.com/67690113/87000731-5e258980-c1d3-11ea-952d-034aff99f1ac.jpeg)

How do we use register by Google and FB? is there a possiblity of showing store as per your address for booking order?

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by sachinsuper18** [comment]
I have not received any from in this email.

**Comment by minhcasi** [comment]
You could pick the license from https://codecanyon.net/downloads 

and submit to http://verify.inspireui.com

**Comment by minhcasi** [comment]
@minhtruong315 - pls help with investigating - thank you!

**Comment by minhtruong315** [comment]
Hi @sachinsuper18 can u send me common folder via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/4133
Thanks

**Comment by minhtruong315** [comment]
Hi @sachinsuper18 Check this video to create firebase project to fix login issue
https://www.youtube.com/watch?v=C_9mk_MmvOQ&t=612s
