### ISSUE TITLE
FLUXNEWS need help with there 2 Issues

### ISSUE THREAD

**Issue by msesetz** [inspireui/support#4134]
I get to issues a follow 
1. Loading Posts finite 

When I open my app doesn't load post infinite 

See video Here 

![GIF-200709_091051](https://user-images.githubusercontent.com/51053867/87003396-367af500-c1c4-11ea-8ca2-38d11369962a.gif)

2 . Error in format exception| Invalid date format when Open my app 

See screenshot here 

![Screenshot_20200709-085029](https://user-images.githubusercontent.com/51053867/87002313-fd418580-c1c1-11ea-9ea9-4fab115a587d.jpg)

**Comment by minhcasi** [comment]
#4116

**Comment by msesetz** [comment]
What a solution please

**Comment by dttrung26** [comment]
Hi @msesetz , 
for issue #1, FluxNews currently having a bug on the vertical layout. A permanent fix will come up in new patch, which would be in next month. 
for issue #2, could you try to wait for the app finishing its loading session, then perform any actions. Let me know the result,
Best!

**Comment by msesetz** [comment]
How to fix this issue of Splashscreen when I open my App come white, Blue,
black then white without showing logo

>

**Comment by dttrung26** [comment]
Hi @msesetz , 
there were some reports from customers who experienced your problem, which says that AM uses armeabi-v7a (32-bit) while emulator phone uses arm64-v8a (64-bit). Therefore, creating APK arm-64 will solve the problem. 
Let me know if you still have any questions.
Best!

**Comment by msesetz** [comment]
Ok another issues to fix are:-

1. Comment Button not working

3. Can I remove Splashscreen to remain with logo only

2. I created APK with 64 MB can I reduce it up to below 10 MB

**Comment by minhcasi** [comment]
refund given
