### ISSUE TITLE
changing package name

### ISSUE THREAD

**Issue by nomicool** [inspireui/support#4137]
after changing package name faces oveerlay declaration by following you guide I change manifest build.grade and path put google json under android>app faces this issue screen shot attached
![Screenshot (130)](https://user-images.githubusercontent.com/25566185/87013334-e90e8000-c1e3-11ea-8cc0-a3873ba09504.png)

**Comment by minhcasi** [comment]
@nomicool - try to double-check the guide https://docs.inspireui.com/fluxstore/delivery-android/#11-change-the-app-name - there is missing on your update - thanks

**Comment by nomicool** [comment]
By following what i did ..
1 manifest package change 
2 app name change
3 google JSON put to android>app>google-json
4 change in build.gradle
5 Edit whole path android/app/src/main/kotlin/com/inspireui/fluxstore as described to my package name rename it.
6 run following command for icon flutter pub run flutter_launcher_icons:main. 
Did I miss anything I have double heck the guide tried twice let me know If I miss something

**Comment by minhcasi** [comment]
@nomicool - we have checked you are using 2 difference Envato account - pls help to give us the comment on this link https://codecanyon.net/item/fluxstore-multi-vendor-flutter-ecommerce-full-app/25013325

**Comment by nomicool** [comment]
done commented

**Comment by minhcasi** [comment]
pls share your whole android folder here - or send to support@inspireui.com - we will help with checking - thanks

**Comment by nomicool** [comment]
[android.zip](https://github.com/inspireui/support/files/4906751/android.zip)
here is the folder complete

**Comment by nomicool** [comment]
I am expecting a reply please

**Comment by minhcasi** [comment]
You did not change the import package from `MainActivity.kt`
There are 3 files need to be updated as the screenshot
<img width="948" alt="Screen Shot 2020-07-12 at 18 57 39" src="https://user-images.githubusercontent.com/1459805/87245688-90ecad80-c471-11ea-917e-d15ace94c488.png">

<img width="971" alt="Screen Shot 2020-07-12 at 18 58 01" src="https://user-images.githubusercontent.com/1459805/87245697-9d710600-c471-11ea-87c2-2295be49f7d0.png">

**Comment by nomicool** [comment]
you have mentioned manifest and java which one is 3rd?

**Comment by minhcasi** [comment]
@nomicool - there is 2 file manifest from my screenshot + mainactivity.kt file = 3 👍
