### ISSUE TITLE
Logo didn't show 

### ISSUE THREAD

**Issue by devienguilde** [inspireui/support#4139]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: Logo didn't show, Wcfm product didn't show, but when i try put dokan on code it's showing
+ Product & version: 1.7.5
+ Flutter (or React Native) version: Lastest 
+ Testing Device/Simulator: SDK 29
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@vumanhsn97 - please investigate this feature (we could improve the Fluxbuilder feature to support checking for this basic integration)

**Comment by vumanhsn97** [comment]
@devienguilde 
In your config_xx.json, make sure you set showLogo = true. https://tppr.me/841CF
Run this cmd before you run your app:
flutter clean

**Comment by devienguilde** [comment]
Hello there, it's work thanks
but i got problem with :
1. Register as Vendor (WCFM) loading forever
2. login loading forever by email
3. login for normal user by email loading forever

how do i share my login

**Comment by devienguilde** [comment]
New update
=================
Succesfully register by SMS and Gmail, but when login it;s loading forever, i see the data goes to database in firebase and my user site

**Comment by aishema2000** [comment]
Hello @devienguilde I also have this serious issue of Successful SMS verification buy login is loading for almost 2 minutes. Did you find a solution??? Please share here. Thanking you in advance

**Comment by devienguilde** [comment]
> Hello @devienguilde I also have this serious issue . The SMS verification is Successful but login is loading for almost 2 minutes. Did you find a solution??? Please share here. Thanking you in advance

Yes the solution actually simple, create new database on Firebase, and be sure SHA-1,SHA-256 is correct

**Comment by devienguilde** [comment]
i got a new problem here, i try login and register as vendor, but can't see add product or vendor dashboard on account at all how do i solved it?

**Comment by devienguilde** [comment]
New update
=========================
if i register with email normally i can see my products page, but when try post product it's loading forever

**Comment by aishema2000** [comment]
> > Hello @devienguilde I also have this serious issue . The SMS verification is Successful but login is loading for almost 2 minutes. Did you find a solution??? Please share here. Thanking you in advance
> 
> Yes the solution actually simple, create new database on Firebase, and be sure SHA-1,SHA-256 is correct

Dear @devienguilde should i create a database??? No where in documentation they say we shoud create a firebase database. Do you mean a new databse or a new FIREBASE PROJECT?

**Comment by devienguilde** [comment]
> > > Hello @devienguilde I also have this serious issue . The SMS verification is Successful but login is loading for almost 2 minutes. Did you find a solution??? Please share here. Thanking you in advance
> > 
> > 
> > Yes the solution actually simple, create new database on Firebase, and be sure SHA-1,SHA-256 is correct
> 
> Dear @devienguilde should i create a database??? No where in documentation they say we shoud create a firebase database. Do you mean a new databse or a new FIREBASE PROJECT?

Yes no where in documentation, CREATE NEW DATABASE not FIREBASE PROJECT, and create default

**Comment by aishema2000** [comment]
Thanks @devienguilde, it is sad that they don't tell us to create database in documentation. i am going to try that NOW!

**Comment by devienguilde** [comment]
NEW UPDATE
=====================================
Can't publish new product solved by this solution : https://github.com/inspireui/support/issues/4039#issuecomment-653907159

**Comment by devienguilde** [comment]
Is there a way to change image directly on apps?

**Comment by devienguilde** [comment]
How to compress picture size when upload products?

**Comment by devienguilde** [comment]
New bug :
This bug come out after i change all products position to 3 column, i can't click details product anymore
=======================
The following NoSuchMethodError was thrown while handling a gesture:
The method 'toJson' was called on null.
Receiver: null
Tried calling: toJson()

When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      Product.toJson (package:fstore/models/product/product.dart:377:22)
#2      RecentModel.addRecentProduct (package:fstore/models/recent_product.dart:16:21)
#3      ProductCard.onTapProduct (package:fstore/widgets/product/product_card_view.dart:68:54)
#4      ProductCard.build.<anonymous closure> (package:fstore/widgets/product/product_card_view.dart:142:31)
...
Handler: "onTap"
Recognizer: TapGestureRecognizer#9e849
  debugOwner: GestureDetector
  state: ready
  won arena
  finalPosition: Offset(82.4, 573.6)
  finalLocalPosition: Offset(76.4, 84.8)
  button: 1
  sent tap down

**Comment by devienguilde** [comment]
> toJson

Solved by this : https://github.com/inspireui/support/issues/3909#issuecomment-656455766

**Comment by devienguilde** [comment]
ASK
===================
How do i change default all product to 3 column, and change filter price according to all category pricing?

**Comment by vumanhsn97** [comment]
@devienguilde 
In your config_xx.json change productlistlayout to columns: https://tppr.me/kntjD

**Comment by devienguilde** [comment]
Hey don't close it answer my question please :
1. i got a problem with my user can't upload picture from apps, how do i solved it?
2. How do i change color styles on settings, and on text only

Please answer sir
