### ISSUE TITLE
[MStore] Cebuilder not loading

### ISSUE THREAD

**Issue by asalah0707** [inspireui/support#414]
**Mandatory Info (please complete the following information):**
 - Product: [MStore,]
 - Your Purchased Code: [45a99e5d-00ca-40d1-******************]
(we may not reply if you are not our customer)

**Describe the issues**
Cebuilder not loading
**Screenshots**
![image](https://user-images.githubusercontent.com/18238235/54682672-9dcceb80-4b20-11e9-9c3e-e19c669c75d0.png)

**Additional context**
Add any other detail logs about the problem here.

**Comment by minhcasi** [comment]
Hi @asalah0707 - could i check if it is the latest CeBuilder 0.27 ? Thanks

**Comment by asalah0707** [comment]
Yes It's 
I tried it a few weeks ago with an old windows installation and it was loading at least like the images, now it's only blank with 0.27 and even older.

**Comment by wcreativo** [comment]
Run with Administrator privileges

**Comment by DaviDawn** [comment]
Hello, I have the same problem as him but using the version 0.30.0, I've install everything that MStore needs from CeBuilder, I mean, I pressed on the button install and then the powershell and the cmd.exe start install programs, then the CeBuilder goes in blank. I've tried to run it as Administrator but anything has change. Any solution?

**Comment by minhtruong315** [comment]
Hi @DaviDawn Can you share me teamviewer? i will help you check it

**Comment by DaviDawn** [comment]
@minhtruong315 
ID: 1 237 343 243
PW: f433za

**Comment by DaviDawn** [comment]
@minhtruong315
New password -> ktx249

**Comment by minhtruong315** [comment]
Done

**Comment by smoea** [comment]
Hi. I have the same problem: https://prnt.sc/n7h5qb
just loading for hours when setup with cebuider
