### ISSUE TITLE
Custom app category name in app home  

### ISSUE THREAD

**Issue by rasel6999** [inspireui/support#4140]
#4069

Hi bro, is possible tp set Custom group name in horizonLayout category?? I wanna put custom name in. Json file
![Screenshot_20200709-092049](https://user-images.githubusercontent.com/17203863/87072595-1f242200-c22d-11ea-84cc-570d8bc65a79.jpg)

**Comment by ameenbadri7** [comment]
you cannot add a title to the category from JSON files. 

I think that you want this feature because if you have a long title its will be cut not show up on the home page?

you can make the one line title two by modifying the code inside `lib\widgets\home\category\category_icon_items.dart` in line 130
from :

```                    child: Container(
                      child: Text(
                        name,
                        style: TextStyle(
                          fontSize: kLayoutWeb ? 18 : 12,
                          fontWeight: FontWeight.w600,
                          color: Theme.of(context).accentColor,
                        ),
                        maxLines: 1,
                        textAlign: TextAlign.center,
                      ),
                    ),
                  
```

to be like this : 

 ```
child: Text(
                      name,
                      style: TextStyle(
                        fontSize: kLayoutWeb ? 18 : 14,
                        fontWeight: FontWeight.w600,
                        color: Theme.of(context).accentColor,
                      ),
                      maxLines: 2,
                      textAlign: TextAlign.center,
                    ),
```
you can have `maxLines` as you want or even change the font size from here`kLayoutWeb ? 18 : 12,`

let us know if this not fix your problem?

**Comment by rasel6999** [comment]
No bro. I want change category name with english and arabic

**Comment by ameenbadri7** [comment]
I have Arabic and English website for my client 
you can use the wpml plugins to duplicate your content from English to be Arabic 
https://docs.inspireui.com/fluxstore/multi-language/
it's easy to configuration. 
it's beautiful when its dynamic changes when you change the woocommerce directly without rebuilding your app again and again.

**Comment by rasel6999** [comment]
okey i chakeout  and update you. please wait

**Comment by ameenbadri7** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
