### ISSUE TITLE
Payment is deducting from Paypal but Order is not showing in WooCommerce

### ISSUE THREAD

**Issue by jeeali** [inspireui/support#4142]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
Payment is deducting from Paypal but Order is not showing in WooCommerce
And I don't have an idea about return URL and cancel URL. Can you please help me!

+ Product & version:
Fluxstore WooCommerce - Flutter E-commerce Full App

+ Flutter (or React Native) version: 
Flutter latest Stable version
+ Testing Device/Simulator: 
Samsung S6 and many more
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**
OK, Done

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@jeeali - could you try to pull to refresh the list? Does the order appear on woocommerce side?

**Comment by jeeali** [comment]
No, The Order is not appearing in WordPress/WooComemrce.
Remember: I have not set return, cancel URLs in config.dart for paypal

**Comment by minhcasi** [comment]
@jeeali - note with investigating

**Comment by philipvu30** [comment]
Hi,

After completing payment with paypal, there is a loading screen which is for creating order. If you somehow go back or close the app, the order won't create.
We will implement a notification or a way to prevent user from going back at this step in the future releases.

Thank you
