### ISSUE TITLE
Fluxstore Woocommerce Issues

### ISSUE THREAD

**Issue by FaizalAndro** [inspireui/support#4143]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
1. Native Forgot Screen just show blank
![Capture](https://user-images.githubusercontent.com/37078576/87120592-6bf41100-c29e-11ea-9438-2928953076c9.PNG)
![WhatsApp Image 2020-07-10 at 11 14 45 AM](https://user-images.githubusercontent.com/37078576/87120653-9776fb80-c29e-11ea-8f23-79f15543bae7.jpeg)

2. How to add specific product i Banner click through fluxbuilder
![issue 3](https://user-images.githubusercontent.com/37078576/87120689-afe71600-c29e-11ea-83ae-8a2bfe24a337.PNG)

3. How to change privacy and policy terms
![WhatsApp Image 2020-07-10 at 11 14 45 AM (1)](https://user-images.githubusercontent.com/37078576/87120723-c55c4000-c29e-11ea-955e-65951dcf9827.jpeg)

4. In categories sub categories, it only display 20 products, it is a serious issue please tell why it happened if you want source code or website login msz me privately at faizalkhan8130@gmail.com

5. After dark theme text color problem
![WhatsApp Image 2020-07-10 at 11 14 45 AM (2)](https://user-images.githubusercontent.com/37078576/87120849-153b0700-c29f-11ea-9592-4ec93a7d3ff0.jpeg)

6. App seems like slow when I run in my device. It doesn't give a feel like native app.
+ Product & version: 1.7.5
+ Flutter (or React Native) version: Flutter
+ Testing Device/Simulator: Both
+ Screenshot issues (drag the file to attach here): Attached accordingly

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

Done

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by ameenbadri7** [comment]
1- fill it as this : 

```
 "blog": "https://demo.fluxstore.net/",
  "forgetPassword":
      "https://demo.fluxstore.net/wp-login.php?action=lostpassword"
```
2- you can config your config_en.json files to be like this one  : 

change the category id to be as your woocommerce category
[config_en.zip](https://github.com/inspireui/support/files/4903416/config_en.zip)
 ids.

3- you can get your privacy page from WordPress and then changing the default id:

inside `lib\screens\settings\settings.dart ` 

```
 MaterialPageRoute(
                  builder: (context) => PostScreen(
                      //enter your pageId here
                      pageId: 9937,
                      pageTitle: "${S.of(context).agreeWithPrivacy}"),
                ),
```

4- you can add `"limit": 30` to your product banner in `lib\config\config_en.json`

 ```
{
      "name": "Shrimp Collections",
      "image": "",
      "layout": "twoColumn",
      "category": 16,
      "isSnapping": true,
      "limit": 20
    },
```

5- you could try to use the [Inspector ](https://www.youtube.com/watch?v=yGMt3Y20Zmg)Tools to support the customization of your app.

please read all fluxstore [documentation ](https://docs.inspireui.com/fluxstore)so you can fix any problems you have >>>>

**Comment by FaizalAndro** [comment]
I don't know why you didn't reply what I'm asking for. Are you really sure, did you read question before reply..
1. I asked for native screen forgot password. In doc, it says blank it and I did the same but it shows blank screen. For screenshot refer above image. 

2. I asked for How can I add product link in banner through fluxbuilder, In fluxbuilder there is a option of product I didn't know what to put their. For more I tried to add product id and sku but both didn't work (I am not asking for category only product)

4. In category, I noticed it doesn't fetch all the products , most probably I noticed it fetched only 20 products. I don't know what you written in solution. In regards that I didn't find any code for that.

Humble request please read question first then reply don't be hurry.

**Comment by minhcasi** [comment]
@ameenbadri7 - please help to investigate 

@FaizalAndro - could you able to access to our latest source on GitLab - there is a new upgrade as well

**Comment by FaizalAndro** [comment]
I applied for that plz add me on gitlab and solve my query asap also

**Comment by minhcasi** [comment]
@FaizalAndro - could i know your gmail that request on gitab - there is the latest release 1.7.6 on GitLab, we will update new package and notify via email - thank you!

**Comment by FaizalAndro** [comment]
faizalkhan8130@gmail.com

**Comment by minhcasi** [comment]
@FaizalAndro - we have updated your request, the License you have purchased is based on Fluxstore Listing, not the Woocommerce one, could you help to resend the PDF License for Fluxstore Woo - thank you!

**Comment by FaizalAndro** [comment]
I purchase both fluxlisting and fluxstore woocomerce

**Comment by FaizalAndro** [comment]
Please don't merge both things

**Comment by minhcasi** [comment]
no worries got your comment - https://codecanyon.net/item/fluxstore-woocommerce-flutter-ecommerce-full-app/24050041/comments?page=55&filter=all#comment_24736127

**Comment by FaizalAndro** [comment]
I raised a support ticket for fluxlisting separate, please solve here my fluxstore woo queries

**Comment by minhcasi** [comment]
pls help to download latest `1.7.6`

**Comment by FaizalAndro** [comment]
ok, but if you just solve my above query that will be much better for me. I already reskin and build apk

**Comment by FaizalAndro** [comment]
Already mentioned all my issues very clearly with screenshots

**Comment by FaizalAndro** [comment]
1. Banner Image too much fading
![WhatsApp Image 2020-07-14 at 12 50 47 AM (1)](https://user-images.githubusercontent.com/37078576/87344768-9f6bbf80-c56c-11ea-892d-7acdb7cf754e.jpeg)
2. Search not working(Also it just displayed loading icon)
![WhatsApp Image 2020-07-14 at 12 50 47 AM](https://user-images.githubusercontent.com/37078576/87344783-a4307380-c56c-11ea-8bb5-96d0a337a00a.jpeg)
3. Banner Product link not working(I added product id in fluxbuilder but didn't work)
![issue 3](https://user-images.githubusercontent.com/37078576/87344809-ae527200-c56c-11ea-9bb8-87e739b6f4a7.PNG)
4. How can I put banner with no link up of any product and category

Plz try to reply asap, I'm using latest 1.7.6 version

**Comment by minhcasi** [comment]
@FaizalAndro - we have tried our best to make the Fluxbuilder to fit all customize requirement but sometimes it could support for all advance customize and you should to adjust the value after export as final JSON

1. Please update the json to fix the spacing

2. We have fixed the search issue from the latest `1.7.6` please let us know if it is working.

3-4. we have noted to check on the links issue

**Comment by FaizalAndro** [comment]
I don't have spacing issue and not ask for that sir,
1. Banner image too much fade
2. No, search bar just shows loading ...it's not working please help
3. Banner with product link not work
4. How can I put banner with no linkup

Thank you... Please resolve my query asap. I purchased your two source codes Fluxlisting and Fluxwoocommerce invested a lot but didn't get proper support. Not either fluxlisting raised ticket(3743) and not woocommerce. If you need anything... want my source code, website login please let me know but give me a solution.

I will rate your both product 5 star

**Comment by minhcasi** [comment]
@vumanhsn97 - pls suggest the detailed config for the above setting - thank you!

**Comment by FaizalAndro** [comment]
@vumanhsn97 Can you plz reply little quick, @minhcasi plz tell him to respond on it sir.

**Comment by vumanhsn97** [comment]
@FaizalAndro 
1. Change with other image. This problem come from your image
2. In lib/models/filer_attribute.dart change this code: https://tppr.me/h3VbK
3, 4. Follow this image: https://tppr.me/3mqAM

**Comment by FaizalAndro** [comment]
Banner with Product link opened after many clicks not in single click, why it happened like that

**Comment by vumanhsn97** [comment]
@FaizalAndro 
Because delay response from your site. This widget will be dispose. You can set autoPlay = false

**Comment by FaizalAndro** [comment]
I set autoplay false, but still it delayed only in product banner, I face one more issue. I enabled cache and pu config_en.json file to m-store plugin but I noticed my 3rd banner that is default(with no click) is when I click it shows new arrival products.

{
      "layout":"bannerImage",
      "isSlider":true,
      "autoPlay":false,
      "design":"default",
      "items":[ 
        {
          "image":"https://sagarshopping.com/wp-content/uploads/2019/11/aaa-300x125.jpg",
          "padding":15.0,
          "category":4775
        },
        {
          "image":"https://sagarshopping.com/wp-content/uploads/2019/11/ft10-300x124.jpg",
          "padding":15.0,
          "product":5394
        },
        {
          "image":"https://sagarshopping.com/wp-content/uploads/2019/11/yakult-300x123.jpg",
          "padding":15.0
        }
      ],
      "radius":6.0
    },


Another issue, When I rate product nothing happened

**Comment by vumanhsn97** [comment]
@FaizalAndro 
Mstore Api not support for banner without link
Product rating is working: https://tppr.me/b60Tc

**Comment by FaizalAndro** [comment]
"Mstore Api not support for banner without link" any solution for that
"Product rating is working: https://tppr.me/b60Tc" but in product rating shows zero, maybe it's not count

**Comment by FaizalAndro** [comment]
@vumanhsn97 plz solve this, I need to publish app tomorrow on playstore. Shipping method not visible, in older version it's working fine but in newer 1.7.6 it create issues. Another thing after review and rate any item... rating shows zero

**Comment by minhcasi** [comment]
@FaizalAndro - Please note that we may not support answering or support technical issues for the regular license as per support policies - https://inspireui.com/support-policies/ - but we are trying to best to give extra miles with the supporting. 

If you are using the app for commercial project pls upgrade it to Extended License as well.

Thank you for your time

**Comment by FaizalAndro** [comment]
Im not using it for commercial, i just frustrated with all the bugs that is in the app. Already facing bugs with many days, and what do you thing about it Shipping isn't work in your new update so what's the goal of this app to purchase.

**Comment by minhcasi** [comment]
@minhtruong315 - pls help to check the `blank shipping` issue - thank you!

**Comment by minhcasi** [comment]
@minhtruong315 - pls help to check the `blank shipping` issue - thank you!

**Comment by FaizalAndro** [comment]
@minhtruong315 Plz answer it, already it is due for two days. Please help @minhcasi in this issue.

**Comment by alexrali** [comment]
> I'm not using it for commercial sir, I just frustrated with all the bugs that are in the app. Already facing bugs with many days, and hope you also can understand that if shipping method will not work then it doesn't make any sense.
> 
> Please tell me the solution for this shipping sir, It's working in your previous version but not in this 1.7.6. It just shows blank. It's a serious issue. I'm also appreciate you and your effort that you're doing, but as a buyer if I face something odd then I have to describe to you only.
> 
> ![ezgif com-video-to-gif](https://user-images.githubusercontent.com/37078576/87578785-8bea6100-c6f2-11ea-9559-38a599779960.gif)

Same problem here, please help ASAP

**Comment by minhtruong315** [comment]
Hi @FaizalAndro can u give me your skype? I will contact you.
Thanks

**Comment by FaizalAndro** [comment]
@minhtruong315 yes skype username: creativetechapps

**Comment by minhtruong315** [comment]
I messaged you on the skype. pls check.
Thanks

**Comment by FaizalAndro** [comment]
@minhtruong315 mail sent, plz check

**Comment by minhtruong315** [comment]
@FaizalAndro I checked your website. it's not working well for checkout.
<img width="1291" alt="Screen Shot 2020-07-23 at 6 56 02 AM" src="https://user-images.githubusercontent.com/10402500/88240551-a05dc900-ccb1-11ea-8522-76c8b87b3dce.png">

**Comment by minhtruong315** [comment]
Hi @FaizalAndro 
- Change DefaultCountryISOCode in common/config/payments.dart like this
```"DefaultCountryISOCode": "IN",```
- Change config/states/state_in.json like this
```[
  {
    "code": "MP",
    "name": "Madhya Pradesh"
  }
]
```
it needs "code" in your website to checkout

**Comment by FaizalAndro** [comment]
@minhtruong315 Thanks a lot brother for your great support
