### ISSUE TITLE
Getting Dependencies to start the app with Android Situdio

### ISSUE THREAD

**Issue by easieber** [inspireui/support#4144]
after following your tutorial and start the demo flutter app successfully I am having problems starting your app with AndroidStudio.. it requests to get the dependencies, but when I try to click on her dependencies or upgrade dependencies nothing happen and is not possible to start the app and start working with it.

Do you have some suggestions please :D

![Screenshot 2020-07-10 at 08 49 26](https://user-images.githubusercontent.com/35961470/87125335-a18eff00-c28a-11ea-9402-192d57333943.png)

**Comment by minhcasi** [comment]
@easieber - pls try this method to clean up the cache could be fixed your issue - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

**Comment by easieber** [comment]
@minhcasi so far I accomplished to start the app in the ios simulator.

Kind of work the `flutter clean` and Invalidate Caches / Restart

but so far I need to do everything via the terminal in android studio, I need to `flutter build ios` as someone commented in your link and then I needed to run `flutter run` so the app start... but in the android simulator there is no success I am getting

``` FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Could not determine the dependencies of task ':app_settings:compileReleaseAidl'.
> Failed to find Platform SDK with path: platforms;android-R    ```

And I android studio is not available the run button, I could online make it run via terminal, some ideas?

![Screenshot 2020-07-10 at 10 38 48](https://user-images.githubusercontent.com/35961470/87134886-92fc1400-c299-11ea-89f2-37d0ba313630.png)

**Comment by ameenbadri7** [comment]
https://github.com/inspireui/support/issues/3708

try this

**Comment by easieber** [comment]
@ameenbadri7 it worked thanks!!

**Comment by ameenbadri7** [comment]
@easieber 
We're glad that it helps, 😊
please give us some feedback/rating to [this page](https://codecanyon.net/downloads), 
we are working hard to update more awesome and powerful features on the next coming version release. 
Let us know if you have any feedback. 
Thank you very much ❤️
