### ISSUE TITLE
Problem with Order [MStore Pro]

### ISSUE THREAD

**Issue by enoncie** [inspireui/support#4145]
I have 2 problems. 

1) Payment problem shows nothing in the cart after opening webview.

The products have been added to cart properly. Then I choose the payment method. It opens the link to my woocommerce website, I guess. But it has nothing in the cart.

Does it have anything to do with my setup for payment? on the app or on woocommerce?

Everything else, works just fine. Register, retrieving products, coupon and etc.

2) I have freeshipping but with condition 'With' coupon. I don't want it to show if there is no 'free shipping coupon' applied to the cart first.

Pls advise.

**Comment by luyx2412** [comment]
Hi @enoncie 
- Can you send you website information or create new user with inspireui.team@gmail. Let me check your website config.
- You can set normal default without free shipping, and when user apply coupon which discount 100% shipping fee. You can setup in your wordpress dashboard.

Thanks

**Comment by enoncie** [comment]
Thanks for your comment. I already add you to our development environment.

**Comment by enoncie** [comment]
Did you get on to our dev env?

**Comment by luyx2412** [comment]
Hi @enoncie Sorry i dont see your email, can you send again with title `4145`. I can filter easier, and reply you soon.

Thanks

**Comment by enoncie** [comment]
Sent

**Comment by luyx2412** [comment]
Hi @enoncie Are you config your payment in Config.js file? which must same your config in wordpress dashboard.
![image](https://user-images.githubusercontent.com/8909619/87847826-24f0c600-c905-11ea-9c93-02c907c03428.png)

Thanks

**Comment by enoncie** [comment]
Hi. 

Can you pls guide me a bit? I was checking out from the doc link "https://docs.inspireui.com/mstore/multi-payments/“

It is the old version. I’m using 4.0.0. So it’s a bit different.

As you see. I have 2c2p, credit card, and BACS on my Wordpress.

How should I setup the app to have these two payment types?

Appreciate your support. :-) 

Cam on em.

**Comment by luyx2412** [comment]
Hi @enoncie Please make sure your config on wordpress website same in your app. You can get payment method api to check https://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-payment-gateways

Thanks

**Comment by minhcasi** [comment]
@enoncie - let us know if you have any extra question :) 

#4145
