### ISSUE TITLE
Fluxstore Multi Vendor -Gradle issue 

### ISSUE THREAD

**Issue by marios858** [inspireui/support#4146]
i am having this issue when trying to run the project:

Could not find com.android.tools:r8:1.5.25.
Searched in the following locations:
  - https://dl.google.com/dl/android/maven2/com/android/tools/r8/1.5.25/r8-1.5.25.pom
  - https://jcenter.bintray.com/com/android/tools/r8/1.5.25/r8-1.5.25.pom
  - http://storage.googleapis.com/r8-releases/raw/com/android/tools/r8/1.5.25/r8-1.5.25.pom
Required by:
    project :

**Comment by minhcasi** [comment]
@marios858 - pls check the solution on this ticket #3708

**Comment by marios858** [comment]
Hi @minhcasi am very sorry i tried everything , i even try a new machine with new windows , android , flutter , dart , everything fresh , still i got errors , and especially the same : 

ould not resolve all artifacts for configuration ':classpath'.
   > Could not find com.android.tools:r8:1.5.25.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/android/tools/r8/1.5.25/r8-1.5.25.pom
       - https://jcenter.bintray.com/com/android/tools/r8/1.5.25/r8-1.5.25.pom
       - http://storage.googleapis.com/r8-releases/raw/com/android/tools/r8/1.5.25/r8-1.5.25.pom
     Required by:
         project :

**Comment by minhcasi** [comment]
@marios858 - i will update new release to Gitlab so that you could have a try on the latest version 

Please submit to http://gitlab.inspireui.com/ if you have not accessed to the private repository - thank you!
