### ISSUE TITLE
Error on building MStore Pro on Xcode

### ISSUE THREAD

**Issue by sreelash** [inspireui/support#4147]
**_Step 1 (require): describe detail issues & screenshots_**

+ **Detailed Issue:**

I am working on the MStore template downloaded from the InspireUI. The web team was dealing with the template and they have done with all the required updations. They were testing the application using Expo. Now we want to submit the application to Apple & Google store, but when I build the application with Xcode it throws a number of errors and we couldn't resolve it. The issue related to push notifications and certificates resolved from my side and even after that some more issues are throwing from the react side. Looking forward for the support asap.

+ **Product & version**: MStore Pro & 3.9.5

+ **Flutter (or React Native) version**: React Native
 
+ **Testing Device/Simulator**: Tried on both simulator and device, the same error throws.

+ **Screenshot issues (drag the file to attach here)**: 
![Screenshot 2020-07-06 at 4 05 44 PM](https://user-images.githubusercontent.com/1913797/87133123-7faa7200-c2b4-11ea-9f89-53ff42f19a33.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
@sreelash - could you try with the latest release `Mstore 4.0`? 

Please note that as we may not support for regular license regarding the release or technical question - https://inspireui.com/support-policies/ - but we will try our best to give some suggestions to help you fix your issue.

**Comment by sreelash** [comment]
Hi Minh,

Thanks for your email. However, we need support to launch the application
to appstores. Could you please let me know what shall we do next to get
technical support?

We have already made updates on the MStore version that we have, so how can
we move that to the latest version of MStore 4.0? Looking forward to
hearing from you.

Thanks,
Sreelash

**Comment by minhcasi** [comment]
@sreelash - pls try your best with the guide from the document, upload to AppStore is not take so much your time, some patience will be required if you get rejected from Apple review.

**Comment by sreelash** [comment]
Hello Minh,

We have purchased the app from InspireUI for the easiness to publish the
app to store. I am not asking you to give support to upload to AppStore.
The basic code building of the app is not working.

My query is not resolved yet and you easily made it as closed. Please let
me know the procedure to get extended support.

Sreelash.

**Comment by sreelash** [comment]
Hello Minh,

Sir, We have purchased the app from InspireUI for the easiness to publish the app to store. I am not asking you to give support to upload to AppStore. The basic code building of the app is not working. My query has not resolved yet and you easily kept it as closed. Please let me know the procedure to get extended support.

We are not able to go for launch the product due to the build errors and it's been a while that I keep on requesting to provide support. 

Let me explain what happened as of now. Since the purchase of this product, the web development team was working on the MStore Pro and they haven't tested the application on any mobile devices yet. They were using Expo for testing and now they want to take an IPA and APK to test it on respective platforms.

So, I just did the normal steps to take the react native build such as 
- npm install
- pod install [on iOS folder]
- npm start
- Build from the Xcode
- Throws the error mentioned in this post

What shall we do now?

Thanks

**Comment by minhcasi** [comment]
@sreelash - sorry we have missed your comment 

Please note that you could use the `mstore-expo` to test with the Expo app, the `mstore-pro` could be used with XCode and run with react-native.

Please help to have a look this guide - https://docs.inspireui.com/mstore/getting-started/#quick-install-pro-version. 

There is the option to select the extended license from the product page - https://tppr.me/JKK7P

**Comment by minhcasi** [comment]
Let us know if you have any question - thank you!

**Comment by sreelash** [comment]
Hi Minh,

I have mentioned the issue that I faced on the github issue #4147.

Do I need to create another ticket?

Thanks,
Sreelash
