### ISSUE TITLE
FluxStore MV: Tap Payment order status + Native option

### ISSUE THREAD

**Issue by mo-elkholy** [inspireui/support#4148]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: When I attempt to place the order then in the Tap Payment hosted page I cancel the transaction without entering the credit card details or by entering wrong credit card or by tapping the bak button, an order is created in WooCommerce and marked as paid although it should not be marked as paid.
+ Product & version: 1.7.4 MultiVendor Dokan
+ Flutter (or React Native) version:  Flutter (Channel master, 1.20.0-8.0.pre.1, on Mac OS X 10.15.5)
+ Testing Device/Simulator: iOS 11 Mobile
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

Done

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by mo-elkholy** [comment]
Also, no transactions are being created in Tap dashboard for the test transactions for which I used the Test cards provided by Tap Payments.

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by mo-elkholy** [comment]
Ia already did the form submission

**Comment by minhcasi** [comment]
@mo-elkholy - I'm sorry that the integrated support for payment will not include from our Regular Support, please consider using the Extended License, for more detail info please help to check this link - https://inspireui.com/support-policies/

Thank you so much for your time!

**Comment by mo-elkholy** [comment]
Hi minhcasi, according to InspireU Tap.payment is supported out of the box. But apparently your documentation and the responses. on code canyon questions are not accurate.

How much is the extended license and how fast can you sort Tap payments?

Thank you

**Comment by mo-elkholy** [comment]
https://codecanyon.net/item/fluxstore-multi-vendor-flutter-ecommerce-full-app/25013325/comments?utf8=✓&term=tap+payment&from_buyers_and_authors_only=0

You say it is NATIVE.
