### ISSUE TITLE
[ListApp] I can't connect mylisting theme to the listapp

### ISSUE THREAD

**Issue by myworldonline** [inspireui/support#415]
**Required Info (please complete the following information):**
 - Product: [ListApp]
 - Your Purchased Code: 18034861-7ede-4570-bbcb-2dbe*******

**Describe the bug**
I can't connect mylisting theme to the listapp

**Screenshots**

**Additional context**
After I installed the app and simulate it on my mobile phone via EXPO I made several customizations such as changing the colors of the menus and some labels but I can't make a connection with mylisting theme, any help, please.  

[MyListing.zip](https://github.com/inspireui/support/files/2989523/MyListing.zip)

**Comment by thangvo9x** [comment]
Hi. Please give me your domain to integrate to the app

**Comment by myworldonline** [comment]
Hello, Thanks for your reply.
my domain is https://listuz.com
Thanks a lot.

**Comment by thangvo9x** [comment]
I checked your site. Please change CategoryListingId in MyListing.js & active url for get categories at (Tools -> Rest API Controller)
Thanks

**Comment by myworldonline** [comment]
Hi,
do you mean by active URL from  (Tools -> Rest API Controller) is to enable job_listing?

**Comment by thangvo9x** [comment]
Active job_listing & job_listing_category And you MUST HAVE change categoryListingID with your domain.

**Comment by myworldonline** [comment]
when I click at job_listing_category URL (https://listuz.com/wp-json/wp/v2/job_listing_category) I got this in a pop-up page "{"code":"rest_no_route","message":"No route was found matching the URL and request method","data":{"status":404}}"
and from where I have to change categoryListingID with my domain.
and thank you very much :)

**Comment by myworldonline** [comment]
Sorry for that I think the URL  (https://listuz.com/wp-json/wp/v2/job_listing_category) works fine now, I just need to know from where to change categoryListingID with my domain.

**Comment by myworldonline** [comment]
any feedback, please. It's urgent.

**Comment by thangvo9x** [comment]
> I checked your site. Please change CategoryListingId in MyListing.js & active url for get categories at (Tools -> Rest API Controller)
> Thanks

here

**Comment by myworldonline** [comment]
I'm really sorry about that, but I can't find this option "active URL for get categories" in (Tools -> Rest API Controller).

**Comment by myworldonline** [comment]
guys!

**Comment by thangvo9x** [comment]
It's here. "Please change CategoryListingId in MyListing.js" @@ where is changed.

**Comment by myworldonline** [comment]
I did that but nothing changed I don't know what to do...

**Comment by myworldonline** [comment]
And when I set "Local: enable: false" I got this error message

![6d04df2f-9a15-4d86-ad2b-9d25515d5b9c](https://user-images.githubusercontent.com/48768897/54811708-55393d80-4c9a-11e9-9568-b4f00a974c7a.jpg)

**Comment by thangvo9x** [comment]
Huh? Do you have change categoryListingId in MyListing.js file, plz ? You must change it with your category Id on your site. It'll get data from your website.
Thanks
