### ISSUE TITLE
My order is not loading in my Wp DB and when i try to pay Fluxstore redirect to Webview

### ISSUE THREAD

**Issue by jvsamoa** [inspireui/support#4150]
Hello everyone

I'm trying to finalize my order but Fluxstore automatically redirect to my website (inside of Fluxstore app), and my order is not saved correctly in my Wordpress Database.

Only when I finalized the purchase at webview, my purchase is saved correctly in woocomerce table.

My question is the following: can I skip the payment process from fluxstore "native" screens and go to the webview checkout?
When I'll press "end purchase" button it redirect to my webview checkout page?

![image](https://user-images.githubusercontent.com/25646978/87163229-4fb89a00-c2c7-11ea-8499-ef68539113bd.png)

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
@jvsamoa - you could enable `EnableOnePageCheckout: true` from this file to enable the checkout webview

<img width="846" alt="Screen Shot 2020-07-11 at 13 22 27" src="https://user-images.githubusercontent.com/1459805/87218055-923aaf00-c379-11ea-967c-245acf87f4cb.png">
