### ISSUE TITLE
Enable Old Razorpay Native Checkout.

### ISSUE THREAD

**Issue by spss20** [inspireui/support#4152]
1. Sir, As you said there is build issue in for ios. I am targeting android audience. I want to enable native checkout of razorpay as in old versions before 1.6.6 . 

2. I want to add one more item in bottom navigation and want to load webview in it. How can i achieve it in code.

3. I want give my company social profile links such as Instagram, Twitter, etc. I dont want to give webview. I want to add it into profile items. I want the app to open (if app is installled) otherwise it should redirect to chrome.

4. I also want to give my store location and does't want webview but an intent to google maps.

*Thanks in advance. Keep up the good work. You guys are really doing great*

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**
![Screenshot (105)](https://user-images.githubusercontent.com/29224720/87199850-f6795680-c318-11ea-8f44-92f7abfbce60.png)

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by ameenbadri7** [comment]
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.
We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by spss20** [comment]
I have submitted form. Please Check

**Comment by spss20** [comment]
minhcasi, Thanku sir for giving your precious time and for the support. Take care of yourself in this pandemic. Hope you are doing well. You guys are doing really great.

**Comment by minhcasi** [comment]
Thank you @spss20 - hope you are staying safe 😊
