### ISSUE TITLE
WCFM marketplace vendors doesnt work .

### ISSUE THREAD

**Issue by bogatoons** [inspireui/support#4154]
i tried to use wcfm market place in mstore multi vendor. but the vendors doesnt show up. i have installed the needed rest Api and wcfm plugins but its still not showing up. Need your help its urgent please

**Comment by bogatoons** [comment]
![Screenshot_1594440499](https://user-images.githubusercontent.com/67900863/87216172-8d034300-c32c-11ea-8c85-0d53c3786489.png)

i managed to make some changes in the CustomAPI.js and now the vendors are showing but no information and products of vendors are showing. Anybody here to help fix this? its urgent!!!

**Comment by bogatoons** [comment]
![Screenshot_1594440815](https://user-images.githubusercontent.com/67900863/87216205-eec3ad00-c32c-11ea-97f8-885c7431f432.png)
![Screenshot_1594440803](https://user-images.githubusercontent.com/67900863/87216206-f08d7080-c32c-11ea-820d-e5b338df69b8.png)
![Screenshot_1594440797](https://user-images.githubusercontent.com/67900863/87216207-f1260700-c32c-11ea-860f-9c7038555813.png)

**Comment by minhcasi** [comment]
@bogatoons - pls help to comment on the same open ticket #4081 - thank you so much for your time
