### ISSUE TITLE
items count on add variable product to cart

### ISSUE THREAD

**Issue by effec-tline** [inspireui/support#4155]
hey
we have the problem  any items have variable like size or color customer can add unlimited number from 1 item  on the cart and complete the order 

we need it sync with the stock count if have 1 pcs customer can add just 1 pcs from this model on the cart

setting on  lib\common\config\products.dart

const kCartDetail = {
  "minAllowTotalCartValue": 0,
  "maxAllowQuantity": 100000,
};

![2](https://user-images.githubusercontent.com/67228253/87213159-3e9d7680-c323-11ea-81d1-f516f0c334c6.png)
![1](https://user-images.githubusercontent.com/67228253/87213160-40ffd080-c323-11ea-875a-5216c026a6b1.png)

Product & version: FluxStore 1.7.5
Flutter (or React Native) version: Flutter 1.17.3-stable
Testing Device/Simulator: android studio last version / simulator nexus 6

Step 2: Please verify license and sharing config files by submitting on this google form, http://verify.inspireui.com, (done )

**Comment by ameenbadri7** [comment]
The feature you've just requested sounds great, I have to say that. However, this belongs to the customization service. If you really in need of that feature, please contact our tech lead via minh@inspireui.com and declare your request. If our team are available, we could discuss this feature deeper later on.

**Comment by effec-tline** [comment]
you know what mean? this the basic things must repaired i not need to add customization this error from application not syn the stock with cart

**Comment by minhcasi** [comment]
@effec-tline - sorry - we did not get your point, does it relate to your previous #3839?

Please help to use latest `1.7.6` (available from GitLab) to see if it can be fixed? Could you take the screenshot of your setting from the Wordpess admin so that we could help with checking? If it possible please share the login admin to inspireui.team@gmail.com - thank you!

**Comment by effec-tline** [comment]
hey 

first this how i can download the last version  1.7.6 from GitLab ???

2 - sorry - we did not get your point, does it relate to your previous #3839?     about this the variable out of stock its not allowed to add to cart so its solved>>

but now we have another problem  1 - if items havevariables like size and color   the customer can add unlimited number from this items like screen i share on the screenshot the items have just 1 pcs on the stock but customer can add 11 pcs from it to his cart and complete the order

![87213159-3e9d7680-c323-11ea-81d1-f516f0c334c6](https://user-images.githubusercontent.com/67228253/87237893-f43bf880-c3fb-11ea-8c6b-1a07cc7593b5.png)
![87213160-40ffd080-c323-11ea-875a-5216c026a6b1](https://user-images.githubusercontent.com/67228253/87237894-f4d48f00-c3fb-11ea-80e4-d1908d6219cf.png)


-----------------------------------------------

problem number 2 - if item have 2 variables available  like (size and color)  when customer shoose 1 variable the items added to cart with the first varialble like this item we choose  yellow color and meduim size   the items add to cart yellow and large

![1](https://user-images.githubusercontent.com/67228253/87238146-3155ba00-c3ff-11ea-8bdc-1ef5535d98b1.png)
![2](https://user-images.githubusercontent.com/67228253/87238150-361a6e00-c3ff-11ea-961b-01504801eaaf.png)


i send the admin to inspireui.team@gmail.com

**Comment by effec-tline** [comment]
hey why no reply here or on the email?

**Comment by philipvu30** [comment]
Hi,

Sorry for the delayed response as we do not work on the weekend.
On your variable product, turn the Manage stock on. This should fix your issue.

https://tppr.me/RAcKD

**Comment by effec-tline** [comment]
very thanks probem solved
