### ISSUE TITLE
Facebook and email registration creating users at Firebase but Flux News App is not logging in. Its throwing errors on login screen

### ISSUE THREAD

**Issue by drakata** [inspireui/support#4156]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 

When I log in using Facebook or registering using email, Firebase creates the users perfectly, but on the app, it gives me an exception. I'm not able to move from the login screen to my home area. This happens for both Facebook login and email registration.

I cannot create a user at all with Google

+ Product & version:
Flux news 1.4.1

+ Flutter (or React Native) version: 
Flutter  v1.17.5 

+ Testing Device/Simulator: 
Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

+ Screenshot issues (drag the file to attach here): 

Email Registration Error
![email-exception](https://user-images.githubusercontent.com/9298144/87215031-3c8ae600-c32a-11ea-8b41-650dd28aff28.PNG)

Facebook Login Error
![facebook exeption](https://user-images.githubusercontent.com/9298144/87215034-3eed4000-c32a-11ea-8a37-27e2d8518a93.PNG)

Google Login Error
![google-exception](https://user-images.githubusercontent.com/9298144/87215035-3f85d680-c32a-11ea-8a47-5b86d6d7bdbc.PNG)

Terminal
![terminal-2](https://user-images.githubusercontent.com/9298144/87234465-136d6280-c3c9-11ea-9adc-d5ec51af7cc3.PNG)

Firebase Created users through Facebook and Email
![firebase created user](https://user-images.githubusercontent.com/9298144/87215076-d5216600-c32a-11ea-8eb7-59be7ae41e39.PNG)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by ameenbadri7** [comment]
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.
We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by drakata** [comment]
I've done so.

Thank you

**Comment by drakata** [comment]
Hi. Just wondering if there has been any information on this error? @dttrung26 

Thanks again

**Comment by dttrung26** [comment]
Hi @drakata , 
sorry for such a late response. 
Just a few questions before solving your problem.
1. Could you double-check your Firebase integration is correctly done? 
2. Did you modify any authentication-related part on both WordPress admin dashboard and source code? If it is, please send me your whole source code. Otherwise, just send me your WordPress admin access via trung@inspireui.com as well as Firebase access via dttrung.ityu@gmail.com. 
Once again, 
so sorry for the late reply. 
Have a nice day!

**Comment by drakata** [comment]
> Hi @drakata ,
> sorry for such a late response.
> Just a few questions before solving your problem.
> 
> 1. Could you double-check your Firebase integration is correctly done?
> 2. Did you modify any authentication-related part on both WordPress admin dashboard and source code? If it is, please send me your whole source code. Otherwise, just send me your WordPress admin access via [trung@inspireui.com](mailto:trung@inspireui.com) as well as Firebase access via [dttrung.ityu@gmail.com](mailto:dttrung.ityu@gmail.com).
>    Once again,
>    so sorry for the late reply.
>    Have a nice day!

Hi @dttrung26 

Thanks for getting back to me. I have checked the firebase integration, went through the steps in the documentation a number of times. If I have misconfigured, its something I cannot see. 

I have not modified the original authentication code. I have sent you all the admin access. 

Thank you.

**Comment by dttrung26** [comment]
Hi @drakata , 
I've received your sharing access and I'm working on that. I'll get you back when solution is found. 
Happy coding!

**Comment by dttrung26** [comment]
Given information from customer is not enough. Please re-open the ticket when you fulfill the needed information via trung@inspireui.com.
