### ISSUE TITLE
Fluxtore signup causing undefined index

### ISSUE THREAD

**Issue by maynard88** [inspireui/support#4158]
Hello when you signup on fluxtore pro you get undefined index error for "seconds" and "role"

Root cause of issue: Your woo_commerce.dart body param has no role and seconds being posted to your msto plugin 

final http.Response response = await http.post("$url/wp-json/api/flutter_user/register/?insecure=cool&$isSecure",
          body: convert.jsonEncode({
            "user_email": username,
            "user_login": username,
            "username": username,
            "user_pass": password,
            "email": username,
            "user_nicename": niceName,
            "display_name": niceName,
          }));

In your flutteruser.php line 158 to 159 the code is expecting seconds param and role paral. 

  public function register()
    {
        $json = file_get_contents('php://input');
        $params = json_decode($json, TRUE);
        $usernameReq = $params["username"];
        $emailReq = $params["email"];
        $secondsReq = $params["seconds"];
        $roleReq = $params["role"];

**Comment by maynard88** [comment]
I already updated my code to fix this but pls make sure you do integration testing when updating codes.  I'm starting to doubt your development team and starting to doubt if I should update my code as I get a lot of error after update.

**Comment by maynard88** [comment]
I added these because your mstore api wordpress plugin is expecting these params

![image](https://user-images.githubusercontent.com/13436953/87217236-98309000-c379-11ea-90a0-92d0495d5ed8.png)

**Comment by maynard88** [comment]
This is the original error message

<br /> <b>Notice</b>: Undefined index: seconds in <b>/home/ikumpra/public_html/wp-content/plugins/mstore-api/controllers/FlutterUser.php</b> on line <b>158</b><br /> <br /> 
<b>Notice</b>: Undefined index: role in <b>/home/..../public_html/wp-content/plugins/mstore-api/controllers/FlutterUser.php</b> on line <b>159</b><br /> <br /> <b>Notice</b>: Undefined index: notify in <b>/home/.../public_html/wp-content/plugins/mstore-api/controllers/FlutterUser.php</b> on line <b>166</b><br /> {"code":"existed_username","message":"Username already exists.","data":{"status":400}}

**Comment by minhcasi** [comment]
@minhtruong315 - pls double-check this issue

**Comment by minhtruong315** [comment]
Hi @maynard88 pls update MStore Api plugin and check again. let me know the result.
Thanks
