### ISSUE TITLE
Mstore mv change categories

### ISSUE THREAD

**Issue by nomicool** [inspireui/support#4159]
I am attaching screenshot where to edit hte above categories and icons . kindly check the highlighted areas in screenshots
![Screenshot_20200706-103434](https://user-images.githubusercontent.com/25566185/87217504-4b41bf00-c363-11ea-8aa8-1d88bb4bae7e.jpg)

**Comment by minhcasi** [comment]
@nomicool - we have checked you are using username on Envato, would you mind to give the comment on this link to verify your purchase again - https://codecanyon.net/item/mstore-multi-vendor-complete-react-native-template-for-ecommerce/22278924 - thank you for your time!

**Comment by nomicool** [comment]
Done commented there

**Comment by nomicool** [comment]
also let  me know how can i change color for button bar I tried to change color but it changes the cotton on below how can I change color please reply for both categories in screenshot
![Screenshot_1594470374](https://user-images.githubusercontent.com/25566185/87224067-a42d4980-c39b-11ea-9f59-3932ac627601.png) and when I click on wishlist I face following screenshot error in debug but in apk release app closes and starts again there 3 issues I shared lease let me know
 and color here

**Comment by nomicool** [comment]
please reply

**Comment by nomicool** [comment]
4th issue app is not getting logged in products shown when tried to login show invalid mail or password I reset password used username nothing works

**Comment by nomicool** [comment]
regarding 4th issue is when i tried to register my self it worked fine after registration its login automatically itself but I logout and login again shows error password or mail incorrect

**Comment by minhcasi** [comment]
@luyx2412 - pls help to suggest on this issue - thank you!

**Comment by nomicool** [comment]
5th issue found when selecting the country it disappears

 the field the country does not select 
I am attaching video you can find out the issue
here is the link to video please have a look ::: https://we.tl/t-NAofRmxj9M

**Comment by luyx2412** [comment]
Hi @nomicool Can you share me your project via inspireui.team@gmail.com. I will fix the issues and resend you soon.

Thanks

**Comment by nomicool** [comment]
@luyx2412 Hey i have sent source code check mail

**Comment by luyx2412** [comment]
Hi @nomicool I just reply your email, please check it.

Thanks

**Comment by nomicool** [comment]
Updating plugin login issue is still same there

**Comment by luyx2412** [comment]
Hi @nomicool Can you invite inspireui.team@gmail.com to your wordpress website. Let me investigate about it.

Thanks

**Comment by nomicool** [comment]
I have added you as editor in WordPress forgot password and check it let me know today please quickly

**Comment by luyx2412** [comment]
Hi @nomicool Please follow this comment to fix your issue https://github.com/Tmeister/wp-api-jwt-auth/issues/59
I saw your api response 
![image](https://user-images.githubusercontent.com/8909619/88472514-e9c24880-cf3d-11ea-86de-ffd3f4198c69.png)

Thanks

**Comment by nomicool** [comment]
Hey Following the document still facing issue with logging the app screenshot attached
![Screenshot_1596108260](https://user-images.githubusercontent.com/25566185/88918473-ec48d900-d282-11ea-930c-96ef9d4526f5.png)

**Comment by nomicool** [comment]
Hello login issue is still not solved with documentation

**Comment by nomicool** [comment]
Hello Please author try to respond me I am stuck on login issue
