### ISSUE TITLE
[Listpro] label under icon

### ISSUE THREAD

**Issue by chad-the-first** [inspireui/support#416]
**We are looking for any contribution to improve the product features and quality, please let us know.**
How to add a label under the icons in the bottom navigation
![Sketch7](https://user-images.githubusercontent.com/17035853/54759152-2ff2f380-4bf6-11e9-8dd2-1a2f3b4856fb.png)
 

**Mandatory Info (please complete the following information):**
 - Product: [Listpro]

**Comment by thangvo9x** [comment]
You can reference. https://reactnavigation.org/docs/en/bottom-tab-navigator.html
by adding tabLabel / title to Stacknavigator.

**Comment by chad-the-first** [comment]
I tried to add (tabBarLabel) as it shows in the documentation but it didn't show, and i have 'showlabel' as true. Any help on how to do it? 
![Sketch6](https://user-images.githubusercontent.com/17035853/54865400-df060b00-4d6d-11e9-86a9-0a9bba2b7a8c.png)

**Comment by thangvo9x** [comment]
Or you can fix it Components/TabBar/index.js
