### ISSUE TITLE
Unlink my License for Mstore API to add to my main domain - i purchased Fluxstore Multivendor

### ISSUE THREAD

**Issue by gsjaikrishnan** [inspireui/support#4160]
i linked my license to a domain https://vendor.cashhack.in which i was just testing and now when am trying to link it to my main domain https://ajtrendz.com its telling me its already linked to https://vendor.cashhack.in so please is it possible to unlink my license. i mean Mstore API plugin

**Comment by minhcasi** [comment]
@gsjaikrishnan - pls send your purchase code request to reset to support@inspireui.com - thank you!
