### ISSUE TITLE
Fluxstore mv dokan apk not working

### ISSUE THREAD

**Issue by nomicool** [inspireui/support#4161]
After having all configuration flux store mv works fine on emulator debug but releasing apk does not works shows error app not open and also I have tried flutter build apk and flutter build apk --split-per-abi
 command not apk works on physical device app crashes not an open issue.

**Comment by minhcasi** [comment]
Duplicate of #4137

**Comment by nomicool** [comment]
its not the duplicate could you please double check its about fluxstore and other was by store react native
