### ISSUE TITLE
[Fluxnews] How to bring back the login tab?

### ISSUE THREAD

**Issue by aldoyh** [inspireui/support#4162]
Hello,

I love the new release, but I would like to have the login screen back to the TabBar, how can I do that?

And what if I need to load Custom Post Type? What do I need to do?

**Comment by minhcasi** [comment]
@aldoyh - could you explain more via screenshot/mockup as i could not get your point 😅

**Comment by aldoyh** [comment]
The login tab in the bottom in the old version as shown in this screenshot:
![Screenshot_20200714_001736_com wehorseracing app](https://user-images.githubusercontent.com/5215449/87354720-b52ab600-c567-11ea-8905-a49f3815a9b1.jpg)

But here the latest version, notice the login has gone into the drawer:
![Screenshot_20200714_002250_com wehorseracing app](https://user-images.githubusercontent.com/5215449/87355105-721d1280-c568-11ea-9cf6-bb7d64ea11d4.jpg)
![Screenshot_20200714_002258_com wehorseracing app](https://user-images.githubusercontent.com/5215449/87355116-7812f380-c568-11ea-8755-936ef4337bbe.jpg)

How to bring it back like before?

**Comment by dttrung26** [comment]
Hi @aldoyh , 
modifying your config_[language].json file as bellow would solve your problem. 
Inside `TabBar` variable, add those code: 
`
   {
      "layout": "profile",
      "icon": "assets/icons/tabs/icon-user.png"
    }
`

Hope this helps.
Have a nice day!

**Comment by aldoyh** [comment]
Yep, it worked, seems that happened when I replaced the config_en.json with a new one from the FluxBuilder.

Now the second part of this ticket, I've already purchased Fluxnews and I want to display CTP (as replied in another ticket) so do I also need to purchase the FluxStore to be able to customize it myself?

**Comment by dttrung26** [comment]
Hi @aldoyh ,
can you give me more information about the ticket that you mentioned?

**Comment by minhcasi** [comment]
@aldoyh - we will move to support you about CPT on this ticket #4329 - thank you for your new purchase 🎖
