### ISSUE TITLE
Not able to place an order 

### ISSUE THREAD

**Issue by noufalv** [inspireui/support#4165]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues:   I purchased a mstore expo version opencart mobile app built in react native.while click on confirm order iam getting an error .Also payment methods and shipping methods are not display on the checkout screen
+ Product & version: mstore expo version for opencart
+ Flutter (or React Native) version: React native
+ Testing Device/Simulator:  Mobile Device
+ Screenshot issues (drag the file to attach here): 

(https://user-images.githubusercontent.com/3404620/87225128-7f34d880-c393-11ea-8642-c56b283ffd05.jpeg
(https://user-images.githubusercontent.com/3404620/87225135-95db2f80-c393-11ea-8fa1-58e0d2887384.jpeg)
)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhtruong315** [comment]
Hi @noufalv give me your skype. I will help you check via teamviewer.
Thanks

**Comment by noufalv** [comment]
noufalv786

**Comment by minhtruong315** [comment]
There is limitation from current mstore app that does not restrict the country/state which is required to complete the checkout process, if you select the wrong state/country the checkout will be fail - we have noted as feature upgrade and report to the team to fix it later - thank you!

**Comment by noufalv** [comment]
Last comments from your developer is..he is not able to fix this issue. I am in trouble now. Why do you put react native product for sale. This is cheet for customer.
Please tell your developer to fix this issue. or refund my money. I am useless your product.
