### ISSUE TITLE
Do not show something and the default language not works

### ISSUE THREAD

**Issue by heftipascal1** [inspireui/support#4166]
Hi, i need some help to hide something in the App:

1. Hide the Author from the Blog, how we can do it?
![Screenshot_1594496600](https://user-images.githubusercontent.com/67189625/87232461-8b368f80-c3bf-11ea-9037-fe654fee9141.png)

2. The Default Language is not working. 
![Screenshot_1594496740](https://user-images.githubusercontent.com/67189625/87232505-e8324580-c3bf-11ea-90b2-724afc72a696.png)
When we click on German, then the translation is working. But when the App starts, then the language is per default english... We have put in config.dart also " "DefaultCountryISOCode": "de","  How we can fix that?

3. The Login is required, "IsRequiredLogin": true,  but when we start the App, then click on Register or Login (Screenshot in German) then it switch directly to the App, without registration or login? How we can fix that?
![Screenshot_1594496871](https://user-images.githubusercontent.com/67189625/87232578-2def0e00-c3c0-11ea-8cfd-370b71ac1c84.png)

- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@heftipascal1 - pls keep your comment on this ticket #4117 so that our team could follow the issue
