### ISSUE TITLE
{ Flux-Woo } Appstore - need to update Compliance Information

### ISSUE THREAD

**Issue by suri1980** [inspireui/support#4169]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 

Need help in Export Compliance Information in App Store

Let me know whether the app use encryption or not?

+ Product & version: Fluxstore woo commerce, Version: 1.7.5
+ Flutter (or React Native) version: Flutter 1.17.5
+ Testing Device/Simulator: iPhone 11 Pro
+ Screenshot issues (drag the file to attach here): 

<img width="952" alt="Screenshot 2020-07-12 at 12 08 24 PM" src="https://user-images.githubusercontent.com/1085817/87238715-9aa5ef00-c438-11ea-9f55-5049e1a1e019.png">
<img width="590" alt="Screenshot 2020-07-12 at 12 08 32 PM" src="https://user-images.githubusercontent.com/1085817/87238717-9e397600-c438-11ea-913f-e0ded460d765.png">

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

I've already submitted it as part of #3869 

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
select `No` and click Next

**Comment by suri1980** [comment]
@minhcasi thanks,

**Comment by minhcasi** [comment]
let us know if you release the app successful - thank you!
