### ISSUE TITLE
[MStore] Basic Installation not working on mstore-expo

### ISSUE THREAD

**Issue by nkuranhy3** [inspireui/support#417]
**Required Info (please complete the following information):**
 - Product: Mstore-expo
 - Your Purchased Code: [get from https://codecanyon.net/downloads]
41a15692-aacc-457e-a826-e13987ff0a86

**Describe the bug**

The basic setup is not working here. 
I have installed all the plugins on http://hypacart.com backend.

When i change the customisations for ceBuilder it dont work.

Look at these screenshots.

**Screenshots**
![Screen Shot 2019-03-22 at 9 45 48 AM](https://user-images.githubusercontent.com/34389326/54816513-51062380-4c8c-11e9-87b1-59cc14156d1a.png)

I am changed the app name to hypacart
and the website to http://hypacart.com

But the customisation dont work. it says cannot get categories and tags
**Additional context**
Add any other detail logs about the problem here.
If possible please share your config.js that use for the app setting

![Screen Shot 2019-03-22 at 9 46 06 AM](https://user-images.githubusercontent.com/34389326/54816555-6d09c500-4c8c-11e9-8c5c-c73b98d74c0e.png)

And it runs forever after clicking ok

![Screen Shot 2019-03-22 at 9 58 54 AM](https://user-images.githubusercontent.com/34389326/54816574-7f83fe80-4c8c-11e9-87a3-469bbd49cbd8.png)

It has been running for hours.

Please can you help us in this?

Hear from you soon.

**Comment by Relimer-Technologies** [comment]
Hello, @nkuranhy3  I had faced the same problem when I tried the installation for the first time... Solution for this problem is Go to your Wordpress Dashboard -> Woocommerce -> Settings -> Advanced -> You will find Legacy API over there click on it, enable the Legacy API and Save Changes... That's it... I hope this will work for you... Thank You

**Comment by minhcasi** [comment]
@nkuranhy3 

1.  please update the latest cebuilder to 0.27 to work with latest mstore.

2.  It could also cause by missing config, pls check the document from https://docs.mstore.io/basic-app-setting

3. If it does not work please share your testing admin to our support email support@inspireui.com for further checking and investigating

Pls check these above solutions, thanks
