### ISSUE TITLE
Check out problems

### ISSUE THREAD

**Issue by easieber** [inspireui/support#4170]
Good day 

1. A few days ago I posted an issue related to the mapping of two extra fields in the checkout page. Soe of you recommend me to set ` "EnableOnePageCheckout": true,` but then the user experience is really bad as we load the checkout page of the website and is not so good. Is it possible to map the two fields that we are using from the extension plugin https://woocommerce.com/products/woocommerce-order-delivery/ as it is an official extension of the woocommerce plugin?.

<img width="386" alt="Screenshot 2020-07-12 at 04 56 44" src="https://user-images.githubusercontent.com/35961470/87242535-e010ef00-c42d-11ea-963e-b9c0f15fae33.png">

2. When I proceed to the Shipping step, none of my shipping methods is showed

<img width="384" alt="Screenshot 2020-07-12 at 04 56 26" src="https://user-images.githubusercontent.com/35961470/87242533-dab3a480-c42d-11ea-998b-e9b853d0d0dd.png">

**Comment by minhcasi** [comment]
@easieber - I'm sorry that we could add this option as the default fluxstore app, feel free to make you own customization. You could try to customize the native payment UX by following the previous Paypal payment.

Please help to raise your all comment to one open ticket #4168 - thank you for your time!
