### ISSUE TITLE
Products filter issue in the app

### ISSUE THREAD

**Issue by easieber** [inspireui/support#4171]
Good day,

I got a few problems related to the products and products filtering:

1. when I click this `See all` and the app send me to the next page with all the products, it is empty:

<img width="385" alt="Screenshot 2020-07-12 at 04 55 07" src="https://user-images.githubusercontent.com/35961470/87242572-3da53b80-c42e-11ea-91eb-a99c825602f6.png">

2. There is a way to remove or edit this filter option in the category section, because if you click on it you get an error:

<img width="376" alt="Screenshot 2020-07-12 at 04 54 27" src="https://user-images.githubusercontent.com/35961470/87242582-59104680-c42e-11ea-85fa-2b87b16c2808.png">

Error

<img width="383" alt="Screenshot 2020-07-12 at 04 54 46" src="https://user-images.githubusercontent.com/35961470/87242584-60375480-c42e-11ea-8fac-bd993ebdc690.png">

**Comment by codex-pro** [comment]
Even I m facing the same problem

**Comment by minhcasi** [comment]
1. you could config it is using latest release 1.7.5 as at the Recent section, we have hidden the Show all button.

2. you could use the Inspector to customize the app UI - https://www.youtube.com/watch?v=yGMt3Y20Zmg

Please help to raise your all comment to one open ticket #4168 - thank you for your time!
