### ISSUE TITLE
Change domain my site

### ISSUE THREAD

**Issue by eduardo9104** [inspireui/support#4173]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
Hello y change domain of site, and now can not use with new domain.
+ Product & version:
Fluxstore 1.7.5
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 
<img width="1680" alt="Screen Shot 2020-07-12 at 09 11 59" src="https://user-images.githubusercontent.com/30954514/87247178-2fe8b980-c420-11ea-980b-4a409522b8f4.png">

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
it's reset - pls try again - thank you!

**Comment by eduardo9104** [comment]
thank you
