### ISSUE TITLE
How to Change/add Text Label?

### ISSUE THREAD

**Issue by karmelcorn** [inspireui/support#4174]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues:  I want to change the text/label like instead of "Buy Now" to "Buy From Website" for the buy button
+ Product & version:  Fluxstore Shopify 1.7.5
+ Flutter (or React Native) version:  Flutter
+ Testing Device/Simulator: Android/iOS
![Simulator Screen Shot - iPhone 8 Plus - 2020-07-12 at 14 25 54](https://user-images.githubusercontent.com/45998347/87253791-d7c7ac80-c44b-11ea-94f3-8d1b7b6f9f1d.png)

+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
<img width="866" alt="Screen Shot 2020-07-13 at 09 42 22" src="https://user-images.githubusercontent.com/1459805/87265494-28431680-c4ed-11ea-8a13-010410cea3cd.png">

You could change on the .arb file, pls make sure to run the generate language file by following this guide https://docs.inspireui.com/fluxstore/multi-language/

Or you could hard text on this file 
<img width="1025" alt="Screen Shot 2020-07-13 at 09 45 13" src="https://user-images.githubusercontent.com/1459805/87265658-8ff96180-c4ed-11ea-9e12-9d9129b31d45.png">

**Comment by karmelcorn** [comment]
I already edited intl_en.arb. But what's the instructions to generate the language? I only find this in the link you provided


"To add a new language, please follow step below:
Go to lib/l10n/ the folder and copy the existing files to make a new one (you may see there are many languages demo from the app). Let’s take adding the new French (fr) Language for example, the format should be intl_fr.arb. We suggest using the Android Studio with Flutter Intl when inputting new language to support auto-generating the WidgetsLocalizations file lib/generated/i10n.dart."

Thank you for your help.

**Comment by karmelcorn** [comment]
Ok I got it to work. 

1. install flutter_intl plugin (https://plugins.jetbrains.com/plugin/13666-flutter-intl) in android studio
2. remove the current intl_en.arb
3. added new intl_en.arb

seems like editing it alone won't trigger flutter_intl to regenerate and you must remove and add the new arb file to trigger the regeneration.

**Comment by minhcasi** [comment]
Could you also run via script without installing that plugin 
```
flutter pub run intl_translation:extract_to_arb --output-dir=lib/l10n lib/main.dart
```

ref: https://flutter.dev/docs/development/accessibility-and-localization/internationalization

But install the plugin will help your job super easy

Let us know if you have any questions. Please help note that we may not support answering some technical questions for the regular license as per support policies - https://inspireui.com/support-policies/ - but we are trying to best to give extra miles with the supporting. Hope you enjoy the product :)
