### ISSUE TITLE
additional information of product details is not getting in the Fluxstore MV and Product filters is not yet perfect need urgent fix

### ISSUE THREAD

**Issue by Shopyloot** [inspireui/support#4175]
Woocommerce Products have attribute data, which will be displayed as additional information in the product details page but in the app these details are missing, please help to fetch these details even the mobile app

Check out the screenshot 
https://prnt.sc/tgk8nu

**Comment by minhcasi** [comment]
@tgloc96 - please help to investigate this feature

**Comment by Shopyloot** [comment]
is there any update please, i am not requesting any feature it's already been there in your code, Can you please cross check this again

**Comment by Alnaggar94** [comment]
@minhcasi Also the SKU number doesn't show, could you please also fetch it in the additional information?

**Comment by Shopyloot** [comment]
Hello any update ? as said above even the sku information is not showing and also the product filter is not yet good, it is showing all attributes. When can i get the support

**Comment by tgloc96** [comment]
@Shopyloot Thank you for your feedback, we investigated the issue and fixed this.
We will try to release the next version as soon as possible.

Thank you for choosing our product ^^.

**Comment by Shopyloot** [comment]
I have seen the update in the https://codecanyon.net/ how can i update this with my current files, should i replace everything and start from the scratch again or just a few files to replace. Help me to update the code

**Comment by minhcasi** [comment]
@Shopyloot - please follow this guide to handle the merge code on git to help you keep the features without losing your code - https://medium.com/@inspireui/how-to-upgrade-fluxstore-projects-by-using-git-cebde7489ea6

Allow us to close this ticket and move our conversation to #4345 (it's better to give your all comments to the same ticket that would help to focus all your issue) - thank  you!
