### ISSUE TITLE
see all tab not displaying any products

### ISSUE THREAD

**Issue by codex-pro** [inspireui/support#4176]
![Screenshot 2020-07-13 at 9 40 38 AM](https://user-images.githubusercontent.com/51110842/87270145-e9ad5c00-c4ec-11ea-90dd-60cdae7a47d8.png)

HI i m getting no products in "see all " 

I m using opencart . 
My site name is edibleshope.com

**Comment by minhcasi** [comment]
@codex-pro - could you use the latest release `1.7.6` - thank you!

**Comment by codex-pro** [comment]
not good i m getting same error

**Comment by codex-pro** [comment]
even after upgrading i m getting same error
