### ISSUE TITLE
I need sub category in category tab

### ISSUE THREAD

**Issue by santhoniral** [inspireui/support#4177]
**_Step 1 (require): describe detail issues & screenshots_**

![Screenshot at Jul 13 14-21-38](https://user-images.githubusercontent.com/32481586/87283333-d1e8ce80-c512-11ea-9285-fe8f805cc3b1.png)

+ Detail Issues: 

when category is clicked id like it to take you to sub category

+ Product & version:

Mstore expo and 4.0.0

+ Flutter (or React Native) version: 

Latest version

+ Testing Device/Simulator: 

Simulator
 
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**Comment by minhcasi** [comment]
@santhoniral - sorry this feature is not available from current Mstore app - you could try to customize this feature to make it work - thank you!

**Comment by santhoniral** [comment]
Hello

**Comment by santhoniral** [comment]
i will try to customize this feature..but can you give any tip and details...please

**Comment by santhoniral** [comment]
@minhcasi  @luyx2412 

please response

**Comment by luyx2412** [comment]
Hi @santhoniral 
- In `src/containers/Categories/index.js` line 120 you can filter with sub categories and edit in this file.
![image](https://user-images.githubusercontent.com/8909619/87565282-a10fc180-c6eb-11ea-9313-359dafb22011.png)

Thanks

**Comment by santhoniral** [comment]
thanks for your help...You have any idea about this function?
