### ISSUE TITLE
Cannot update user profile data

### ISSUE THREAD

**Issue by thimiradulakshitha** [inspireui/support#4179]
Issue  01 
	**Step 1** – logging to the app using google sign-in/ Facebook sign in or username/password.
	**Step 2** – tap on update data
	**Step 3** – after logged in to the system the user should complete the profile in update profile section. 
                             (Display name, Nice name, and URL) then tap the update button.
	**Step 4** – after that user can see the user name on settings above email.
	**Step 5** – clear all background apps on the mobile phone.
	**Step 6** – again login to the Fluxstore WooCommerce App and tap on the settings icon in the bottom 
   	                     the navigation bar and tap on the Update profile. In this case, we cannot see the user updated data

![Untitled](https://user-images.githubusercontent.com/44156968/87285020-a5ce4d00-c514-11ea-9c0f-837b9ba34aec.png)
![2222](https://user-images.githubusercontent.com/44156968/87285027-a8c93d80-c514-11ea-8bee-74dd4e70c13f.png)

Issue 2
        **Step 1** – logging to the app using google sign-in/ Facebook sign in or username/password.
	**Step 2** – Add products to the cart and tap on 'checkout' and Fill the user address and tap the button to continue to the 
                           shipping.
	**Step 3** – in shipping page cannot see any shipping options. therefore I can't move into the Preview and payment pages.

**Comment by philipvu30** [comment]
Hi,

1. This issue happens because the logic of the update profile is not well tested. We will try to fix this feature asap.
2. Have you added any shipping methods or do your shipping methods have any region restricted?

Thank you for

**Comment by thimiradulakshitha** [comment]
hello,  thank you for your quick response.

1. Is there any specific date we can get the update?
2. Yes, we have added region restrictions to shipping methods.

**Comment by philipvu30** [comment]
Hi,

1. Sorry, I can't tell but it will be soon updated.
2. Please check your shipping methods if they are correctly configured as I don't see your shipping methods in the rest API response..

**Comment by thimiradulakshitha** [comment]
I got a new error. the blue screen error with this message. :**error in exception: the initial value provided is not a supported iso code** when I added products to the cart and tap on checkout I got this. How can I fix this issue?

![WhatsApp Image 2020-07-22 at 9 47 07 AM (1)](https://user-images.githubusercontent.com/44156968/88133781-83b58880-cc00-11ea-8963-175fc46c3c3d.jpeg)

**Comment by philipvu30** [comment]
Hi,

May I know what ISO code did you put in this file lib/common/config/payments.dart?

![image](https://user-images.githubusercontent.com/54442328/88167700-72da3680-cc43-11ea-9e8e-2305b9326c67.png)

**Comment by philipvu30** [comment]
Closed as no response in 2 days.
