### ISSUE TITLE
[ListApp] how to add social media option in listing content page?  -mylisting theme

### ISSUE THREAD

**Issue by Pavithran10** [inspireui/support#418]
**We are looking for any contribution to improve the product features and quality, please let us know.**

**Mandatory Info (please complete the following information):**
Product:[ListApp]
Version:1.6.1
Theme: MyListing

hi, In our site social media icon option is avaiable. so, we plan to add that option in the listing app but, I don't know that option is there or not in your code we also check in mylisting.js and we couldn't find that option in code.
how to add the social icon into category list item page in mylisting.js ? 
and then we plan to fix that icon option below that related post in config/mylisting.js 
thanks

**Comment by minhcasi** [comment]
Hi, could you share your screenshot or the URL of your site so that we could check the solution to integration, the Listapp is support for native sharing at current version so that it may not same as your website, thank you!

**Comment by Pavithran10** [comment]
hi, please check our site url in below link
https://www.dancestudiyos.com/

**Comment by Pavithran10** [comment]
hi, I've attached last two before this feature request issue but didn't get any info from your side. please tell the solution ASAP. thanks
