### ISSUE TITLE
Opencart shipping issues

### ISSUE THREAD

**Issue by Mars-2030** [inspireui/support#4180]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues:  
1. error during checkout .. shipping page  is not retreiving shipping methods
2. select address does not fetch addresses from my account in the server
3. save address does not save addresses from the account on the server
+ Product & version: Fluxstore Pro 1.7.5 with Opencart 3.0
+ Flutter (or React Native) version:  Flutter latest
+ Testing Device/Simulator:  Iphone 11 simulator 
![Simulator Screen Shot - iPhone 11 - 2020-07-13 at 12 24 20]

+ Screenshot issues (drag the file to attach here): 
(https://user-images.githubusercontent.com/68222677/87288588-3a7c7f00-c504-11ea-8901-1e5685123cb3.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by Mars-2030** [comment]
I already submitted this form:  http://verify.inspireui.com

**Comment by minhcasi** [comment]
@Mars-2030 - thank you for reporting. I'm sorry that syn address feature to the server is not available from the current app

**Comment by Mars-2030** [comment]
How about this point here : error during checkout .. shipping page is not retreiving shipping methods

**Comment by Mars-2030** [comment]
I have upgraded to version 1.7.6 still I am having issue as shown in the image  (error during checkout .. shipping page is not retreiving shipping methods)
(https://user-images.githubusercontent.com/68222677/87288588-3a7c7f00-c504-11ea-8901-1e5685123cb3.png)

**Comment by Mars-2030** [comment]
I really appreciate your support here

**Comment by minhcasi** [comment]
@Mars-2030 - Please note that we may not support answering or support technical issues for the regular license as per support policies - https://inspireui.com/support-policies/ - but we are trying to best to give extra miles with the supporting. 


@minhtruong315 - pls help to suggest on this issue - thank you!

**Comment by Mars-2030** [comment]
thanks for trying to support 
I found the error here 
`Map<String, dynamic> toOpencartJson() {
    return {
      "zone_id": state,
      "country_id": '111',  **// here you should pass the country id not the country iso code?**
      "address_1": street ?? '',
      "address_2": block ?? '',
      "postcode": zipCode,
      "city": city,
      "firstname": firstName,
      "lastname": lastName,
      "email": email,
      "telephone": phoneNumber
    };
  }`

another question is the Tax supported within the app?

**Comment by Mars-2030** [comment]
you may close the ticket 
I solved the problem it was a bug in the code
also I found out that Tax is not supported within the app, I modified the backend to calculate and return the taxes

Thanks a lot the app is great ,, needs more work from the opencart side .. to get all the features that provided by opencart

**Comment by minhtruong315** [comment]
Hi @Mars-2030 do you have any issues now?

**Comment by Mars-2030** [comment]
thanks .. you may close the ticket
