### ISSUE TITLE
Issue in getting pub dependencies

### ISSUE THREAD

**Issue by GNAG1993** [inspireui/support#4182]
Its an issue as i open your code for the first time.

**warning: The include file package:pedantic/analysis_options.yaml in C:\src\source\analysis_options.yaml cannot be found. (include_file_not_found at [fstore] analysis_options.yaml:1)**

When I open pubspec.yaml and click on **Pub get**, process begins and i get a message **process finished with exit code 0.**

![Error 1](https://user-images.githubusercontent.com/58203387/87298225-afc56100-c4be-11ea-82bb-9ccb6b7c2b9f.png)
![Error 2](https://user-images.githubusercontent.com/58203387/87298259-beac1380-c4be-11ea-93bb-6b0612635e55.png)

**Comment by minhcasi** [comment]
@GNAG1993 - pls try to clean up the cache to fix the issue - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1
