### ISSUE TITLE
unable to copy state option in payment field 

### ISSUE THREAD

**Issue by rihtak2020** [inspireui/support#4183]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
i am using webview for payment gateway and when a user enters his address in the mobile app and continues it goes to webview and everything is copied to the website shipping page except the state option,, can you please tell me how to copy the state field in webview so that the user does not want to select it again.
+ Product & version: 1.7.5
+ Flutter (or React Native) version:  flutter

+ Screenshot issues (drag the file to attach here): 
![WhatsApp Image 2020-07-13 at 5 39 51 PM (1)](https://user-images.githubusercontent.com/65780159/87302928-e4bdcc00-c52f-11ea-9c27-2bddaa619ff0.jpeg)
![WhatsApp Image 2020-07-13 at 5 39 51 PM](https://user-images.githubusercontent.com/65780159/87302938-eab3ad00-c52f-11ea-9ca6-02619b1c5c71.jpeg)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

already verified 

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@rihtak2020 - you could try to match the state from config state json the same with your website

**Comment by rihtak2020** [comment]
> @rihtak2020 - you could try to match the state from config state json the same with your website

Can you please explain more? I have the same sate field in app and website then how to match it ?

**Comment by ameenbadri7** [comment]
this ticket its retaliated to woocommerce and WordPress customization. 
you should take a look at our [support-policies](https://inspireui.com/support-policies).
but as a solution to your issue, you could download [Woo Add Custom States
](https://wordpress.org/plugins/woo-add-custom-states/) to add states to your woocommerce and then you should create State Names and State Codes
like this 
```
State Name | State Code
AlKhobar | ALKHOBAR

```<img width="960" alt="create the states" src="https://user-images.githubusercontent.com/37524186/87338874-7b998100-c54e-11ea-8406-1967c359b776.png">

and also create a new file with the country name you want like I do with ` Saudia Arabia ` 

inside your project `lib\config\states` you can add `state_xx.json` aka `lib\config\states\state_sa.json` like this set the state names and codes inside it : 
<img width="960" alt="match state" src="https://user-images.githubusercontent.com/37524186/87339191-ea76da00-c54e-11ea-8971-a7cd306809dc.png">.

that's it .

BTW: if you want to use the woocommerce website as checkout option (web view for payment gateway) you should try to change your `lib\common\config\payments.dart`  from : 
```
  "EnableOnePageCheckout": false,
  "NativeOnePageCheckout": true,
```

to be like this to stop the native checkout and enable the woocommerce checkout : 
```
  "EnableOnePageCheckout": true,
  "NativeOnePageCheckout": false,
```

for more information, you can go to our [documentation](https://docs.inspireui.com/fluxstore).

**Comment by rihtak2020** [comment]
> this ticket its retaliated to woocommerce and WordPress customization.
> you should take a look at our [support-policies](https://inspireui.com/support-policies).
> but as a solution to your issue, you could download [Woo Add Custom States ](https://wordpress.org/plugins/woo-add-custom-states/) to add states to your woocommerce and then you should create State Names and State Codes
> like this
> 
> ```
> State Name | State Code
> AlKhobar | ALKHOBAR
> ```
> 
> <img alt="create the states" width="960" src="https://user-images.githubusercontent.com/37524186/87338874-7b998100-c54e-11ea-8406-1967c359b776.png">
> 
> and also create a new file with the country name you want like I do with `Saudia Arabia`
> 
> inside your project `lib\config\states` you can add `state_xx.json` aka `lib\config\states\state_sa.json` like this set the state names and codes inside it :
> <img alt="match state" width="960" src="https://user-images.githubusercontent.com/37524186/87339191-ea76da00-c54e-11ea-8971-a7cd306809dc.png">.
> 
> that's it .
> 
> BTW: if you want to use the woocommerce website as checkout option (web view for payment gateway) you should try to change your `lib\common\config\payments.dart` from :
> 
> ```
>   "EnableOnePageCheckout": false,
>   "NativeOnePageCheckout": true,
> ```
> 
> to be like this to stop the native checkout and enable the woocommerce checkout :
> 
> ```
>   "EnableOnePageCheckout": true,
>   "NativeOnePageCheckout": false,
> ```
> 
> for more information, you can go to our [documentation](https://docs.inspireui.com/fluxstore).

I think you have not understood my issue. I have the same state name in app and website but during check out i am not able to copy to webview when trying to check out. can you please help.

**Comment by minhcasi** [comment]
@rihtak2020 - could you try to update the latest mstore-api ?

The state will use the code to matching the value, not using the name - so that you need to make sure the select `code values` have the same:

<img width="945" alt="Screen Shot 2020-07-16 at 09 42 32" src="https://user-images.githubusercontent.com/1459805/87620408-ad763780-c748-11ea-9693-7e88c5a7079d.png">

**Comment by ameenbadri7** [comment]
I'm sorry to close this ticket as there is no response or active conversation.
please help to create a new one and link to this ticket if the problem is not solved.

thank you for your time ❤️
