### ISSUE TITLE
Change fluxtore shopify on fluxstore woocommerce

### ISSUE THREAD

**Issue by vverbovenko91** [inspireui/support#4184]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
My friend by fluxstore shopify, but his site on wordress.
May I change version for woocommerce version(shopify key not activate yet).
Thanks!
+ Product & version: fluxstore woocommerce
+ Flutter (or React Native) version: fluxstore 1.7.5
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@vverbovenko91 - i'm sorry that we could not support to exchange the product, please help to checkout our support policies. 

We sincerely apologize for the issue, and hope you are staying safe
