### ISSUE TITLE
I can't build for iOS

### ISSUE THREAD

**Issue by kyughost** [inspireui/support#4185]
Hello I need to side load my app and I can't. I have a free Developer account (I will be enrolled when the App is ready).
I'm using 
Fluxstore 1.7.5
Flutter 1.17.5
Dart 2.8.4

I get the error below
<img width="1189" alt="Screen Shot 2020-07-13 at 15 54 49" src="https://user-images.githubusercontent.com/30949306/87314115-10868500-c523-11ea-8ba1-b569e68a4a52.png">

**Comment by minhcasi** [comment]
Please add your account to the Team setting and also check `Automatically Manage Signing` from your XCode, we are not sure if it is support for free account but you could have a check to see if it works 

<img width="787" alt="Screen Shot 2020-07-14 at 08 18 35" src="https://user-images.githubusercontent.com/1459805/87369401-9ef21980-c5aa-11ea-9980-54df0df6768c.png">

**Comment by minhcasi** [comment]
Let us know if you have any feedback - thank you!

**Comment by kyughost** [comment]
Hello, thank you for your reply. I have already added that to my project.
<img width="1146" alt="Screen Shot 2020-07-15 at 10 25 47" src="https://user-images.githubusercontent.com/30949306/87522513-ff09be00-c685-11ea-9c16-8208972c0ad5.png">

**Comment by saud-kh** [comment]
why is this information not in the documentation? the delivery document (https://docs.inspireui.com/fluxstore/delivery/) barely has any information in it.

**Comment by kyughost** [comment]
> Let us know if you have any feedback - thank you!

Hello why did you close without solving my problem
