### ISSUE TITLE
Magento FluxStore: Payments method not working 1.7.6 & 1.7.5

### ISSUE THREAD

**Issue by xsamir** [inspireui/support#4186]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
I built the app on Magento 1.7.5 :
All payments methods show fine, but when  I choose one of them, it moves me directly to the complete purchasing page! without transfer me to the webview payment page!

On 1.7.6, when I move to the payment methods page, it shows an error: Exception: Error occurred during "shipping_address" Processing ...etc

![image](https://user-images.githubusercontent.com/7432001/87324132-bdbbc600-c540-11ea-8fee-ec91eaf379e7.png)

I tried to change the payment option between true and false, but same nothing changed!
![image](https://user-images.githubusercontent.com/7432001/87323403-c364dc00-c53f-11ea-8eef-83c33cc6217d.png)

For payment methods, I have the SDK files of the payment methods, is there's a tutorial on how to integrate it inside the app instead of the Magento review?

+ Product & version: 1.7.6
+ Flutter (or React Native) version: 1.17.4
+ Testing Device/Simulator: Pixel 2 - 29
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by xsamir** [comment]
I solve it by using the same code from 1.7.5 of lib/models/address.dart

But I'm still facing the problem with payment methods, not processed! just move me to Successfully payment screen :'(
It should open a webview screen for payments
![image](https://user-images.githubusercontent.com/7432001/87347171-d2f61c00-c563-11ea-92d3-e858263414c2.png)

**Comment by minhcasi** [comment]
@minhtruong315 - pls help with checking this issue

**Comment by xsamir** [comment]
PLZZZZZZZZZZZZZZZZZZZZZZZZZ HELP

**Comment by minhcasi** [comment]
We wanted to thank you for your patience during this busy time. We currently have reduced staff and a significantly higher volume of inquiries. 

Please note that we will not support answering or support technical issues for the regular license as per support policies - https://inspireui.com/support-policies/ - but we are trying to best to give extra miles with the supporting.

**Comment by xsamir** [comment]
Thank you for your reply
I think I should have a good position with Flux company because I bought three products from you (one of them is a premium license)
Also I have many projects in the future which will use your products.

So I hope that the problems can be solved so I can move to the next step of my business.
For me now I cannot do anything because of that problem.


Another question: did you provide a customization services, like integrating a new payment method by SDK files not Webview?

**Comment by minhtruong315** [comment]
Hi @xsamir can u send me full your source code via email: minhtruong315@gmail.com
I will help you check. Ping me when you shared.
Thanks

**Comment by xsamir** [comment]
Sent

**Comment by minhtruong315** [comment]
Hi @xsamir 
- Can u take me screenshot for which category not showing products?
- for magento, Fluxstore only support some payment gateways: paypal, tap, razorpay. Fluxstore doesnt support payment webview, so when you checkout with other payment gateways, it will move to success page.

**Comment by xsamir** [comment]
- The problem of the products shows with any category have more than 6 products

- Payments gateway, how can I hide the webview gateway and Integrate the payments through SDK files?
If there's no Documentation for that, Did you have a customization service?

Because I have a pending project, and I need to solve it ASAP

**Comment by minhtruong315** [comment]
@xsamir for product issue, you can replace parseProductFromJson function in services/magento.dart like this
```
Product parseProductFromJson(item) {
    final dateSaleFrom = MagentoHelper.getCustomAttribute(
        item["custom_attributes"], "special_from_date");
    final dateSaleTo = MagentoHelper.getCustomAttribute(
        item["custom_attributes"], "special_to_date");
    bool onSale = false;
    var price = item["price"];
    var salePrice = MagentoHelper.getCustomAttribute(
        item["custom_attributes"], "special_price");
    if (dateSaleFrom != null && dateSaleTo != null) {
      final now = DateTime.now();
      onSale = now.isAfter(DateTime.parse(dateSaleFrom)) &&
          now.isBefore(DateTime.parse(dateSaleTo));
      if (onSale && salePrice != null) {
        price = salePrice;
      }
    } else if (salePrice != null) {
      onSale = double.parse("${item["price"]}") > double.parse("$salePrice");
      price = salePrice;
    }
    final mediaGalleryEntries = item["media_gallery_entries"];
    var images = [MagentoHelper.getProductImageUrl(domain, item, "thumbnail")];
    if (mediaGalleryEntries != null && mediaGalleryEntries.length > 1) {
      for (var item in mediaGalleryEntries) {
        images
            .add(MagentoHelper.getProductImageUrlByName(domain, item["file"]));
      }
    }
    Product product = Product.fromMagentoJson(item);
    final description = MagentoHelper.getCustomAttribute(
        item["custom_attributes"], "description");
    product.description = description != null
        ? description
        : MagentoHelper.getCustomAttribute(
            item["custom_attributes"], "short_description");
    if (item["type_id"] == "configurable") {
      product.price = MagentoHelper.getCustomAttribute(
          item["custom_attributes"], "minimal_price");
      product.regularPrice = product.price;
    } else {
      product.price = "$price";
      product.regularPrice = "${item["price"]}";
    }

    product.salePrice = MagentoHelper.getCustomAttribute(
        item["custom_attributes"], "special_price");
    product.onSale = onSale;
    product.images = images;
    product.imageFeature = images[0];

    List<dynamic> categoryIds;
    if (item["custom_attributes"] != null &&
        item["custom_attributes"].length > 0) {
      for (var item in item["custom_attributes"]) {
        if (item["attribute_code"] == "category_ids") {
          categoryIds = item["value"];
          break;
        }
      }
    }
    product.categoryId = categoryIds.isNotEmpty ? "${categoryIds[0]}" : "0";
    product.permalink = "";

    List<ProductAttribute> attrs = [];
    final options = item["extension_attributes"] != null &&
            item["extension_attributes"]["configurable_product_options"] != null
        ? item["extension_attributes"]["configurable_product_options"]
        : [];

    List attrsList = kAdvanceConfig["EnableAttributesConfigurableProduct"];
    List attrsLabelList =
        kAdvanceConfig["EnableAttributesLabelConfigurableProduct"];
    for (var i = 0; i < options.length; i++) {
      final option = options[i];

      for (var j = 0; j < attrsList.length; j++) {
        final item = attrsList[j];
        final itemLabel = attrsLabelList[j];
        if (option["label"].toLowerCase() ==
            itemLabel.toString().toLowerCase()) {
          List values = option["values"];
          List optionAttr = [];
          if (attributes[item] != null) {
            for (var f in attributes[item].options) {
              final value = values.firstWhere(
                  (o) => o["value_index"].toString() == f["value"],
                  orElse: () => null);
              if (value != null) {
                optionAttr.add(f);
              }
            }
            attrs.add(ProductAttribute.fromMagentoJson({
              "attribute_id": attributes[item].id,
              "attribute_code": attributes[item].name,
              "options": optionAttr
            }));
          }
        }
      }
      attrsList.forEach((item) {});
    }

    product.attributes = attrs;
    product.type = item["type_id"];
    return product;
  }
```

**Comment by xsamir** [comment]
Thanks a lot for that, I will try it and let you know

What about the payment issue?

**Comment by minhtruong315** [comment]
We dont support customize payment gateway.

**Comment by xsamir** [comment]
Thanks for your support🙏🏻

I'm aware to use a freelancer to do that, because I don't want to give the source code to non customer, and maybe he can use it for him self in future
Because that I prefer if there's a customization service provided by you with a fair charge.
