### ISSUE TITLE
after generating release APK login registration not working 

### ISSUE THREAD

**Issue by DishankTech** [inspireui/support#4187]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues:  After releasing  signed APK  Login , Registration not working just keep loading infinitely 
+ Product & version:  Fluxstore- vendor 1.7.5
+ Flutter (or React Native) version: 1.17.4
+ Testing Device/Simulator:  Device
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 
-Thank you for your time!

**Comment by minhcasi** [comment]
@DishankTech - pls try to remove `/` on the website setting that could fix your issue - https://tppr.me/fBt7q

You could try to check the similar login issue from #3151

**Comment by DishankTech** [comment]
Check this images once ,

![Screenshot_2020-07-14-15-37-29-213_com.infoigy.internetdemo.jpg](https://user-images.githubusercontent.com/46589892/87413468-f82c6e00-c5e7-11ea-9084-c4dcf5d26ec6.jpg)


After submitting wrong credentials getting me the response, but when I enter valid credentials then not getting any response , its just keep loading infinity

**Comment by DishankTech** [comment]
Check out this video you can understand better
 What is the problem

https://drive.google.com/file/d/18NFowVwXNtNCrPvfJbI5UZ3dW47dl8-4/view?usp=drivesdk

**Comment by minhcasi** [comment]
@DishankTech - try login by the email instead - you could check this user exists from your WP site?

**Comment by DishankTech** [comment]
Check this video with same credentials with debug apk

https://drive.google.com/file/d/18_e9mIQ0Bf2UEhP2wXam9TZ-X8CGGBAH/view?usp=drivesdk

**Comment by minhcasi** [comment]
@DishankTech - could you confirm if it is working fine with debug mode bug fail on release mode? 

Do you mind to zip the source to google drive and send privately to support@inspireu.com - thank you!

**Comment by DishankTech** [comment]
Yes it's working fine on debug mode, having issue after release

**Comment by DishankTech** [comment]
Please check your mail

**Comment by DishankTech** [comment]
> @DishankTech - could you confirm if it is working fine with debug mode bug fail on release mode? 
> 
> Do you mind to zip the source to google drive and send privately to support@inspireu.com - thank you!

Check your mail

**Comment by minhcasi** [comment]
sorry, there is missing on our email - pls send to support@inspireui.com and inspireui.team@gmail.com - thank you for your time

**Comment by DishankTech** [comment]
> sorry, there is missing on our email - pls send to support@inspireui.com and inspireui.team@gmail.com - thank you for your time

Sorry,Check your email now

**Comment by minhcasi** [comment]
@DishankTech - sorry for disturb you, could i know your email address? We could not see the relate email from your username 'DishankTech' or ticket ID from the email.

**Comment by DishankTech** [comment]
dk.dishank123@gmail.com this is my email

**Comment by DishankTech** [comment]
> @DishankTech - sorry for disturb you, could i know your email address? We could not see the relate email from your username 'DishankTech' or ticket ID from the email.

I think you may have got the Google drive invitation

**Comment by DishankTech** [comment]
> @DishankTech - sorry for disturb you, could i know your email address? We could not see the relate email from your username 'DishankTech' or ticket ID from the email.

Hi,
Check your email once , I have mailed you one more time with ticket id

**Comment by DishankTech** [comment]
Hi,
 I have given Google drive access to minhcasi@gmail.com

**Comment by minhcasi** [comment]
@DishankTech - we got the file, pls give us a few days to investigate as it seems the weird issues - thank you!

**Comment by DishankTech** [comment]
@minhcasi Okay, No problem, Thank you

**Comment by minhcasi** [comment]
@DishankTech - my team report to fix this issue on latest `1.7.6` please help to give a try with the latest code and update `mstore-api` - let us know your checking - thank you!

**Comment by DishankTech** [comment]
@minhcasi Okay, I will check latest code and I'll inform you is it working or not.

**Comment by DishankTech** [comment]
> @DishankTech - my team report to fix this issue on latest `1.7.6` please help to give a try with the latest code and update `mstore-api` - let us know your checking - thank you!

@minhcasi  actually I already using 1.7.6 version

**Comment by DishankTech** [comment]
> @DishankTech - my team report to fix this issue on latest `1.7.6` please help to give a try with the latest code and update `mstore-api` - let us know your checking - thank you!

@minhcasi Where I will get Latest code

**Comment by minhcasi** [comment]
Please download it from https://codecanyon.net/downloads

You could also use this method to merge the code on our private gitlab - https://medium.com/@inspireui/how-to-upgrade-fluxstore-projects-by-using-git-cebde7489ea6

**Comment by DishankTech** [comment]
@minhcasi Still not working on android
