### ISSUE TITLE
I can't use my license y my last site

### ISSUE THREAD

**Issue by jvsamoa** [inspireui/support#4188]
Hello Team,

I have 2 websites  https://confitemarket.com (Desktop version) and  https://confite.market (mobile version). The first time i had installed Fluxstore was in my mobile version but I had needed to make a couple of proof in my desktop version. Now, I'm trying to put again my purchase code in MStore API plugin but i'm watching the following message:

Thank you for installing Mstore API plugins.
Your code is being used by https://confitemarket.com

I know that his license is only for single website, but the in my particular case it's the same website. Can you unlock my license for my mobile website, Please? If you check my log, you can see that i'am saying the true.

Best regards. Nice App.

![image](https://user-images.githubusercontent.com/25646978/87336501-3c653300-c542-11ea-93b5-3009ca819de8.png)

--

Thank you for installing Mstore API plugins.
Your code is being used by https://confitemarket.com

**Comment by minhcasi** [comment]
@jvsamoa - pls help to send the request Reset to support@inspireui.com - we will help to update it
