### ISSUE TITLE
Payment method doesn't getting loaded

### ISSUE THREAD

**Issue by davekedar** [inspireui/support#419]
- Product: MStore
 - Your Purchased Code: f9eaf46b-d573-484d-945f-4236e184eeaf

**Describe the bug**
Payment method is not getting loaded

**Screenshots**
![image](https://user-images.githubusercontent.com/11268363/54825869-8898be00-4cd4-11e9-90ac-13124d2be0f8.png)

Kindly help

**Comment by Relimer-Technologies** [comment]
Hello, @davekedar  Check for the following code in your Config.js file 

![Screenshot_5](https://user-images.githubusercontent.com/47352123/54828388-10cd9200-4cda-11e9-96cf-39ef62c8b301.png)

Here in the image above, I have set up the payment for Cash On Delivery (COD) and Razorpay
Maybe you might have accidentally deleted the code from the Config.js file... If you don't find the above code in the file kindly type this code after Home categories block in the File


Payments: {
    // bacs: require("@images/payment_logo/PayPal.png"),
    cod: require("@images/payment_logo/cash_on_delivery.png"),
  },



Hope it will work for you... Thank You

**Comment by minhcasi** [comment]
@davekedar also make your your list payment method is the same with the app setting - thanks

**Comment by davekedar** [comment]
Thank you problem is solved
