### ISSUE TITLE
How to configure API for custom website build in Laravel

### ISSUE THREAD

**Issue by netkeys** [inspireui/support#4191]
Dear Support,
we have some Queries about your product that we have purchased, I mention all my queries below
1)we want to create our eCommerce website using laravel and we want to use our own API's in a Mobile theme that we buy? can we do that? if we can do then how? if you have any document related to that then provide us
2) how we can customize the home screen in your app?because we try to customize the app home screen according to our product requirement we can not change it.kinndly guide us on how we can customize the app home screen accordingly to our own product
thanks.

**Comment by minhcasi** [comment]
@netkeys - thank you for the question

1. Yes, you could change the app API to change your own Laravel API. If you have Flutter develop background, you could know the source and customize it easy, we don't have document for this customize yet.

2. The homelayout is managed from this file - it is load dynamic via json file
<img width="1058" alt="Screen Shot 2020-07-14 at 14 48 41" src="https://user-images.githubusercontent.com/1459805/87399135-1d69ae00-c5e1-11ea-9ed4-ef2c1fa39031.png">
