### ISSUE TITLE
Shipping Method and Sign Up and Login Error

### ISSUE THREAD

**Issue by topmosth** [inspireui/support#4192]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
**Shipping Method:** 
The error below is showing when I'm trying to checkout from the app, also when the webview checkout is enabled, checkout button on cart page is stuck in loading. 

**Sign Up**
I'm getting the same error message when the user is trying to sign up. Google Sign in and Facebook sign in already working but when the user tries to Login, it's also stuck in loading button, when you pressed the back button, that is the only time that the user will know that they are currently logged in using the account they preferred to use.

One the third image, how can i change the privacy and policy text? 

+ Product & version: Fluxstore Multi Vendor - Flutter E-commerce Full App
+ Flutter (or React Native) version: Flutter
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 
Shipping Method
![image](https://user-images.githubusercontent.com/57655242/87399331-d46a2780-c5e9-11ea-915e-99bdd8082fad.png)

User Sign Up
![image](https://user-images.githubusercontent.com/57655242/87399488-0085a880-c5ea-11ea-8de0-560f72f2c379.png)

Privacy and Policy
![image](https://user-images.githubusercontent.com/57655242/87399518-0c716a80-c5ea-11ea-9fd6-04cf0a257d9d.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by ameenbadri7** [comment]
did you activate your mstore plugin in WordPress?

**Comment by topmosth** [comment]
Yes, Mstore API plugin is activated and updated to latest version

**Comment by minhcasi** [comment]
@topmosth - pls help to check the pre-config site here  - https://docs.inspireui.com/fluxstore/multi-vendor/#1-website-integration - we have fixed all the settings on this site so that you could use for reference 

Please note that we may not support answering or support technical issues for the regular license as per support policies - https://inspireui.com/support-policies/ - but we are trying to best to give extra miles with the supporting. 

Let us know your checking - thank you!

**Comment by topmosth** [comment]
Hi, I tried the pre-config site, after trying i am now getting this error when signing up 
![image](https://user-images.githubusercontent.com/57655242/87517713-d5668c00-c6b1-11ea-8b8c-4cab12747614.png)

**Comment by topmosth** [comment]
After registration that NoSuchMethodError shows on the sign up page, and the user are now registered. How can I fix this error so i will not show on the sign up page everytime the customer/vendor wish to sign up.
![image](https://user-images.githubusercontent.com/57655242/87518829-58d4ad00-c6b3-11ea-8cb6-30716749defa.png)
![image](https://user-images.githubusercontent.com/57655242/87519113-bd900780-c6b3-11ea-9da7-095863802c1a.png)

**Comment by philipvu30** [comment]
Hi,

Please send an admin account of your site to this email: toan@inspireui.com. I'll help you check the issue.

Thank you.

**Comment by topmosth** [comment]
Hi, I already sent an email to toan@inspireui.com thank you!

**Comment by philipvu30** [comment]
Hi,

There is a bug with registration on the latest MStore API. I'll forward this issue to our plugin engineer and will notify you when it is fixed.

Thank you.

**Comment by philipvu30** [comment]
Hi,

Please update the plugin to version 1.7.2. It should fix your issue.

Thank you.

**Comment by topmosth** [comment]
The app is working now. Thank you!
