### ISSUE TITLE
[MultiVendor] Vendor ID is Null when Loading Product Page

### ISSUE THREAD

**Issue by jinuem** [inspireui/support#4194]
**_Step 1 (require): describe detail issues & screenshots_**
**+ Detail Issues:** 
Inside Product Detail Page - Store details is not loading in few scenarios.
Vendor ID is coming as Null when I open the product from Category page. But If I Go to Products from Stores Tab, Vendor ID is coming correctly. 

**_Reproduce Steps:_**
Go to second tab(Category/Store) in the bottom. Choose Any Category. 
Click any Product. Inside Store detail is not loading.

When I debugged. I found STORE ID is Null, so its throwing error.  Check the Screenshots attached.
I can give access to my 1.7.3 Branch Git Repo.
https://github.com/jinuem/CameronMarket/tree/1.7.3
Already @minhtruong315 have access to my GIT repo.

**+ Product & version:**  
Flux Store Multi Vendor - 1.7.3.
**+ Flutter (or React Native) version:** 
Flutter 1.17.4
**+ Testing Device/Simulator:** 
iOS and Android Both Simulators

+ Screenshot issues (drag the file to attach here): 
<img width="1068" alt="Screenshot 2020-07-14 16 23 21" src="https://user-images.githubusercontent.com/3512723/87417925-7ee44980-c5ee-11ea-8d12-3f0658fe4f11.png">

![error](https://user-images.githubusercontent.com/3512723/87412630-e1d1e280-c5e6-11ea-8ab0-1ec1d4a5bcde.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

Submitted.
also Previous Verified Ticket: https://github.com/inspireui/support/issues/3092

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@jinuem - could you try with the latest 1.7.5 - using old version could cause these issue - thank you!

You could also try to merge the project without closing your customize by following this guide https://medium.com/@inspireui/how-to-upgrade-fluxstore-projects-by-using-git-cebde7489ea6

**Comment by jinuem** [comment]
1.7.5 is not Working.
When I try to run for the first time. I am getting following error. May I know what's the issue?
@minhcasi 
`Analyzing dependencies
Downloading dependencies
Installing AppAuth (1.3.0)
Installing BoringSSL-GRPC (0.0.7)
Installing FBAudienceNetwork (5.8.0)

[!] Error installing FBAudienceNetwork
[!] /usr/bin/curl -f -L -o /var/folders/5w/0jb0g09j427bx9_831ggx_bc0000gn/T/d20200715-47707-q4ruzt/file.zip https://developers.facebook.com/resources/FBAudienceNetwork-5.8.0.zip --create-dirs --netrc-optional --retry 2

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 5318k    0 5318k    0     0  87306      0 --:--:--  0:01:02 --:--:-- 58880
curl: (92) HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)


[!] Automatically assigning platform `iOS` with version `10.3` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

[!] Automatically assigning platform `iOS` with version `10.3` on target `OneSignalNotificationServiceExtension` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.`
