### ISSUE TITLE
[FluxStore] Product Variant Images

### ISSUE THREAD

**Issue by Mohamed20884** [inspireui/support#4195]
I would like to ask what happened with the following request as it has been over 6 months without any changes.

https://github.com/inspireui/support/issues/1869

It is really important feature that a lot of your customers can use especially for clothing stores.

**Comment by ameenbadri7** [comment]
we released the latest update 1.7.6 and now you won't have to hard-coded the Product Variant options and its updated automatically without any problems.

`Product Variant Images` it's not available yet.
download the latest it's really fast.

**Comment by Mohamed20884** [comment]
when will the product variant images be available it has been requested for over 6 months

**Comment by minhcasi** [comment]
@Mohamed20884 - we will upgrade it on next release `1.7.7`

**Comment by minhcasi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Upgrade Product Image Variant](https://trello.com/c/XtIC83KM/18-upgrade-product-image-variant)

**Comment by minhcasi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Upgrade Product Image Variant](https://trello.com/c/XtIC83KM/18-upgrade-product-image-variant)

**Comment by minhcasi** [comment]
moved to the backlog for next investigating - thank you!
