### ISSUE TITLE
#4042, Shipping methods 

### ISSUE THREAD

**Issue by Shiru-kun** [inspireui/support#4196]
![Screenshot_20200714-142038](https://user-images.githubusercontent.com/54008441/87425222-87805400-c5dd-11ea-80c1-42ecc4093be3.jpg)
+ Detail Issues: 
When i am on the checkout. i complete all needed data in address, but when i click to shipping , it shows this loading screen and i cant proceed the checkout  
+ Product & version:
fluxstore .7.5
+ Flutter (or React Native) version: 
flutter 1.17.3
+ Testing Device/Simulator: 
samsung A01

**Comment by ameenbadri7** [comment]
first of all, you could try to update to the latest 1.7.6 it's really powerful and very stable.

**Comment by Shiru-kun** [comment]
ok

**Comment by Shiru-kun** [comment]
suddenly it starts to work... 
but i saw something when i tried to buy products from different vendors and i get this:

**Comment by minhcasi** [comment]
@minhtruong315 - pls help to check this shipping issue

**Comment by Shiru-kun** [comment]
@minhtruong315 please check with my github repo

**Comment by Shiru-kun** [comment]
hello?

**Comment by Shiru-kun** [comment]
when i click shipping method 

![image](https://user-images.githubusercontent.com/54008441/87909110-e6bfe780-ca67-11ea-9333-2723a387b274.png)

**Comment by minhtruong315** [comment]
Hi @Shiru-kun can u send me github repo link?
Thanks

**Comment by Shiru-kun** [comment]
@minhtruong315
https://github.com/Shiru-kun/krolycnew

minhtruong315 <notifications@github.com> escreveu no dia segunda,
20/07/2020 à(s) 10:02:

**Comment by aishema2000** [comment]
Same issue here: #4279   I NEED ONLY ONE SHIPPING METHOD FOR ALL VENDORS!!!!!!

**Comment by minhtruong315** [comment]
Hi @Shiru-kun I fixed shipping method on your source code. pls pull the source code and check again.
Let me know the result

**Comment by aishema2000** [comment]
1. Can you please share the solution here so that i can apply it to my app too? I have this exact problem. I want one shipping method for ALL vendors.
2. I see @ameenbadri7 continue talking about version 1.7.6 where do we get it? Please provide download link.

Thanks.

**Comment by Shiru-kun** [comment]
i tested now 
its still showing

**Comment by Shiru-kun** [comment]
![Screenshot_20200720-225000](https://user-images.githubusercontent.com/54008441/87985509-07298980-cadc-11ea-98f8-66c9cb05815b.jpg)
![Screenshot_20200720-225005](https://user-images.githubusercontent.com/54008441/87985516-0a247a00-cadc-11ea-96e5-c4dcceac5ead.jpg)
![Screenshot_20200720-225010](https://user-images.githubusercontent.com/54008441/87985523-0c86d400-cadc-11ea-948d-c18480f27f9a.jpg)
![Screenshot_20200720-225152](https://user-images.githubusercontent.com/54008441/87985532-0e509780-cadc-11ea-9565-90275179a794.jpg)
![Screenshot_20200720-225200](https://user-images.githubusercontent.com/54008441/87985536-10b2f180-cadc-11ea-86aa-054d46d3c3f2.jpg)
![Screenshot_20200720-225206](https://user-images.githubusercontent.com/54008441/87985542-127cb500-cadc-11ea-8b7d-f42e5e4b5511.jpg)

**Comment by minhtruong315** [comment]
Hi @Shiru-kun You're using multi vendor. so the shipping methods have to show by store.

**Comment by Shiru-kun** [comment]
@minhtruong315 
but I want to
Disable that.
Do u have any workaround for that?
Cause my company,l does the delivery

**Comment by minhtruong315** [comment]
Hi @Shiru-kun Please check this solution.
- Add this config in common/config/payments.dart
```
const kPaymentConfig = {
  ....
  /// Disable show shipping methods by vendor
  "DisableVendorShipping": true
};
```
- Replace loadShippingMethods function in widgets/frameworks/dokan/index.dart and widgets/frameworks/wcfm/index.dart like this 
```
@override
  void loadShippingMethods(context, Address address, bool beforehand) {
    Future.delayed(Duration.zero, () {
      Map<String, Store> results = Map<String, Store>();
      if (kPaymentConfig["DisableVendorShipping"] == false) {
        final item = Provider.of<CartModel>(context, listen: false).item;
        item.values.toList().forEach((Product product) {
          if (product.store != null &&
              product.store.id != null &&
              results[product.store.id.toString()] == null) {
            results[product.store.id.toString()] = product.store;
          } else {
            results["-1"] = null;
          }
        });
      } else {
        results["-1"] = null;
      }
      Provider.of<VendorShippingMethodModel>(context, listen: false)
          .getShippingMethods(
              address: address, stores: results.values.toList());
    });
  }
```

**Comment by aishema2000** [comment]
Thanks @minhtruong315 . You are super genius, It works very nice. 

Thank you too @minhcasi for your kind support.

Best Regards,
