### ISSUE TITLE
Product Variation Bug Add to cart & Buy Now 

### ISSUE THREAD

**Issue by attare026** [inspireui/support#4198]
![bug](https://user-images.githubusercontent.com/34741721/87439874-1b204780-c613-11ea-9bc8-4327475b1329.gif)
1st time I will press buy now button here no select any size then again try 
2nd-time press buy button face the same problem then I thought to select any variation on
3rd time back and select XL size and press buy now button it was magic here select S size 
4th-time press again pressed XL size same problem now I was thinking to change the size 
5th-time press and size were select M oh man facing the same BUG. 
------------------------------------------------------------------------------------------------------
Now I am trying my phone here same problem as Flux store Builder 
Please, tell me how to fix it!! 
"This was a big Bug for me"
------------------------------------------------------------------------------------------------------

**Comment by attare026** [comment]
@minhcasi

**Comment by ameenbadri7** [comment]
you are using multi-vendor right? 
please could you use the ticket template so we can know what is the versions of your app and flutter and the emulator and other things that are inside it?

thank you

**Comment by attare026** [comment]
> you are using multi-vendor right?
> please could you use the ticket template so we can know what is the versions of your app and flutter and the emulator and other things that are inside it?
> 
> thank you

flux store mv 1.7.6
Device Note 7 pro

**Comment by minhcasi** [comment]
@vumanhsn97 - pls help to check the product variant issue - thank you!

**Comment by attare026** [comment]
Waiting for your response!

**Comment by vumanhsn97** [comment]
@attare026 
Can't find your issue. Can you send your config and product name to vumanhsn97@gmail.com?

**Comment by attare026** [comment]
> @attare026
> Can't find your issue. Can you send your config and product name to [vumanhsn97@gmail.com](mailto:vumanhsn97@gmail.com)?

Check your email

**Comment by vumanhsn97** [comment]
@attare026 
This is simple product. You need to change it to variant product in your site: https://tppr.me/ImOMq

**Comment by attare026** [comment]
> @attare026 
> This is simple product. You need to change it to variant product in your site: https://tppr.me/ImOMq
> 
> <blockquote><img src="https://tppr.s3.amazonaws.com/uploads/d654173df8875c784f7257a3b7053a08.png" width="48" align="right"><div><img src="/favicon-32x32.png" height="14"> tppr.me</div><div><strong><a href="https://tppr.me/ImOMq">Public - Screenshot_2020-07-17 09-35-07</a></strong></div></blockquote>

No same case on variable! I will change it to many time variable to simpal for testing why its not working

**Comment by vumanhsn97** [comment]
@attare026 
Can't find bug above: https://streamable.com/ambopv

**Comment by attare026** [comment]
Okay Thank you, bro, I can't add any default size that's why its problem

**Comment by attare026** [comment]
![image](https://user-images.githubusercontent.com/34741721/87856552-bda53700-c941-11ea-858e-564fbd728b9e.png)
I want only here text! no background images

**Comment by attare026** [comment]
https://streamable.com/p3ovwl
I want to like that on my app when past this code on my app show only 10 products!
How to show here all products! Like your demo!

**Comment by vumanhsn97** [comment]
@attare026 
Only show text: Remove this code in screens/card.dart https://tppr.me/tEZRE
Show only 10 products: Make sure you don't enableCache

**Comment by attare026** [comment]
Can you give me more explain how show my all products on home page!
Not only 10 products!

**Comment by vumanhsn97** [comment]
@attare026 
Change with this in your config_xx.json
"VerticalLayout": {
    "layout": "pinterest",
    "name": "Recent Collections"
  }
or you can follow in lib/example/dokan/config_theme3.json
Make sure you set isCaching: false in lib/common/config/general.dart https://tppr.me/uvuL

**Comment by attare026** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve com.google.android.gms:play-services-ads-identifier:[15.0.0, 16.0.99].
     Required by:
         project :app > com.onesignal:OneSignal:3.13.2
      > Failed to list versions for com.google.android.gms:play-services-ads-identifier.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/google/android/gms/play-services-ads-identifier/maven-metadata.xml.
            > Could not get resource 'https://jcenter.bintray.com/com/google/android/gms/play-services-ads-identifier/maven-metadata.xml'.
               > Could not GET 'https://jcenter.bintray.com/com/google/android/gms/play-services-ads-identifier/maven-metadata.xml'.
                  > jcenter.bintray.com
      > Failed to list versions for com.google.android.gms:play-services-ads-identifier.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/google/android/gms/play-services-ads-identifier/maven-metadata.xml.
            > Could not get resource 'https://jcenter.bintray.com/com/google/android/gms/play-services-ads-identifier/maven-metadata.xml'.
               > Could not GET 'https://jcenter.bintray.com/com/google/android/gms/play-services-ads-identifier/maven-metadata.xml'.
                  > jcenter.bintray.com
      > Failed to list versions for com.google.android.gms:play-services-ads-identifier.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/google/android/gms/play-services-ads-identifier/maven-metadata.xml.
            > Could not get resource 'https://jcenter.bintray.com/com/google/android/gms/play-services-ads-identifier/maven-metadata.xml'.
               > Could not GET 'https://jcenter.bintray.com/com/google/android/gms/play-services-ads-identifier/maven-metadata.xml'.
                  > jcenter.bintray.com
      > Failed to list versions for com.google.android.gms:play-services-ads-identifier.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/google/android/gms/play-services-ads-identifier/maven-metadata.xml.
            > Could not get resource 'https://jcenter.bintray.com/com/google/android/gms/play-services-ads-identifier/maven-metadata.xml'.
               > Could not GET 'https://jcenter.bintray.com/com/google/android/gms/play-services-ads-identifier/maven-metadata.xml'.
                  > jcenter.bintray.com
      > Failed to list versions for com.google.android.gms:play-services-ads-identifier.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/google/android/gms/play-services-ads-identifier/maven-metadata.xml.
            > Could not get resource 'https://jcenter.bintray.com/com/google/android/gms/play-services-ads-identifier/maven-metadata.xml'.
               > Could not GET 'https://jcenter.bintray.com/com/google/android/gms/play-services-ads-identifier/maven-metadata.xml'.
                  > jcenter.bintray.com
      > Failed to list versions for com.google.android.gms:play-services-ads-identifier.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/google/android/gms/play-services-ads-identifier/maven-metadata.xml.
            > Could not get resource 'https://jcenter.bintray.com/com/google/android/gms/play-services-ads-identifier/maven-metadata.xml'.
               > Could not GET 'https://jcenter.bintray.com/com/google/android/gms/play-services-ads-identifier/maven-metadata.xml'.
                  > jcenter.bintray.com
      > Failed to list versions for com.google.android.gms:play-services-ads-identifier.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/google/android/gms/play-services-ads-identifier/maven-metadata.xml.
            > Could not get resource 'https://jcenter.bintray.com/com/google/android/gms/play-services-ads-identifier/maven-metadata.xml'.
               > Could not GET 'https://jcenter.bintray.com/com/google/android/gms/play-services-ads-identifier/maven-metadata.xml'.
                  > jcenter.bintray.com
      > Failed to list versions for com.google.android.gms:play-services-ads-identifier.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/google/android/gms/play-services-ads-identifier/maven-metadata.xml.
            > Could not get resource 'https://jcenter.bintray.com/com/google/android/gms/play-services-ads-identifier/maven-metadata.xml'.
               > Could not GET 'https://jcenter.bintray.com/com/google/android/gms/play-services-ads-identifier/maven-metadata.xml'.
                  > jcenter.bintray.com
   > Could not resolve com.google.android.gms:play-services-base:[10.2.1, 16.1.99].
     Required by:
         project :app > com.onesignal:OneSignal:3.13.2
      > Failed to list versions for com.google.android.gms:play-services-base.
         > Unable to load Maven meta-data from https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-base/maven-metadata.xml.
            > Could not HEAD 'https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-base/maven-metadata.xml'.
               > dl.google.com
      > Failed to list versions for com.google.android.gms:play-services-base.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/google/android/gms/play-services-base/maven-metadata.xml.
            > Could not get resource 'https://jcenter.bintray.com/com/google/android/gms/play-services-base/maven-metadata.xml'.
               > Could not GET 'https://jcenter.bintray.com/com/google/android/gms/play-services-base/maven-metadata.xml'.
                  > jcenter.bintray.com
      > Failed to list versions for com.google.android.gms:play-services-base.
         > Unable to load Maven meta-data from https://plugins.gradle.org/m2/com/google/android/gms/play-services-base/maven-metadata.xml.
            > Could not get resource 'https://plugins.gradle.org/m2/com/google/android/gms/play-services-base/maven-metadata.xml'.
               > Could not GET 'https://jcenter.bintray.com/com/google/android/gms/play-services-base/maven-metadata.xml'.
                  > jcenter.bintray.com

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14m 51s

Exception: Gradle task assembleDebug failed with exit code 1


flutter doctor 
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.18363.959], locale en-GB)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[√] Android Studio (version 4.0)
[√] Connected device (1 available)

• No issues found!

I don't know where is my problem tomorrow work perfectly!

**Comment by attare026** [comment]
@vumanhsn97 
"VerticalLayout": {
"layout": "pinterest",
"name": "Recent Collections"
} 
after use this code I cant show on the wishlist button my home page product!

**Comment by vumanhsn97** [comment]
@attare026 
Can you explain your issue?

**Comment by minhcasi** [comment]
@attare026 - pls help to give your all comment into one open ticket support #4283 

Please note that we will not support answering or support technical issues for the regular license as per support policies - https://inspireui.com/support-policies/ - but we are trying to best to give extra miles with the supporting - thank you for your time
