### ISSUE TITLE
App performance and Caching issue

### ISSUE THREAD

**Issue by aishema2000** [inspireui/support#4199]
I have followed instructions on how to boost app performance but also how I can change the layout of my app without building app again.

1.  I set iscaching to true and 
2. I uploaded modified config_en,json using MStore Plugin in wordpress
3. I clean cach using REST Cache API
4. All plugins are updated.

**BUT** when I re-open my app, there is no changes.

WHAT CAN I DO??

**NOTE:** To verify me, please see #3151

**Comment by ameenbadri7** [comment]
hello, @aishema2000 welcome back.

based on our advanced team member @dttrung26 he said on [ticket 3662](https://github.com/inspireui/support/issues/3662#issuecomment-648008734).
```
The purpose of isCaching is to optimize the user's performance by not reloading config again when experiencing the app. That's why when you enable isCaching, the product layout will not be loaded again. 
However, the product detail screen always needs to be reloaded due to special data events. 
Therefore, please consider using this feature if your site is mostly "static". 
Otherwise, turn this one off if you need your data is always up-to-date.
```
I hope this info can help you with your problem!

**Comment by minhcasi** [comment]
@aishema2000 - did you check to see if the Cache hit is increased from the Rest API Caching setting ?

<img width="1252" alt="Screen Shot 2020-07-15 at 10 05 42" src="https://user-images.githubusercontent.com/1459805/87498756-c0becf80-c682-11ea-9f46-f51ecae50d94.png">

**Comment by ameenbadri7** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved. 

 - thank you for your time!
