### ISSUE TITLE
[CeNews] The post cannot show in home page

### ISSUE THREAD

**Issue by winwinmedia** [inspireui/support#42]
**Mandatory Info (please complete the following information):**
 - Product: CeNews - Multipurpose Wordpress React Native app
 - Your Purchased Code: [2f5e1fce-8b3b-4485-8382-894874ac2f2a]

**Describe the issues**
I've tried to install and set the settings, but it doesn’t work.I just need your help to check the settings in my WP site. I can upload app to app store by myslef. 
my test site: https://demo2.winwinmedia.com.tw/wp-admin
account: testapp
password: testappuser

**Screenshots**

The content can show in category, but cannot show in home page.
![s__71041046](https://user-images.githubusercontent.com/45336353/48981585-4e4a5600-f112-11e8-893a-aff3b54bd2df.jpg)

![s__71041047](https://user-images.githubusercontent.com/45336353/48981587-51dddd00-f112-11e8-819f-9ef6960d8dfb.jpg)

![1543124289691](https://user-images.githubusercontent.com/45336353/48981590-54d8cd80-f112-11e8-86c5-75c5677b145d.jpg)

**Additional context**
Add any other detail logs about the problem here.

**Comment by minhtruong315** [comment]
Hi @winwinmedia 
You can open this url on browser to see category ids. 
https://demo2.winwinmedia.com.tw/wp-json/wp/v2/categories

Then you need to edit Config.js file to show news on Home screen
for example:
HomeLayout: [
    { categories: [39], layout: Constants.Layout.banner, limit: 5 },
  ],

You need to change 39 to your category id
