### ISSUE TITLE
You can't add over 10 products

### ISSUE THREAD

**Issue by Relimer-Technologies** [inspireui/support#420]
Mandatory Info (please complete the following information):

Product: [e.g. MStore, ListApp]
M Store Pro
Purchase Code: d98eb201-aba4-4c76-a0a1-cbd67415737d
Your Purchased Code: [get from https://codecanyon.net/downloads]
(we may not reply if you are not our customer)
Describe the issues
Hello,

Good Morning, I have purchased M Store Pro from Envato. I have done all the setup required... I have installed all of the required tools... I am trying to add over 10 products to check bulk order... But I get an error "You can't add over 10 products"... I need this restriction to be removed.

I am using plugins for features like user role and Dynamic pricing based on Quantity on the Website... I am not able to see the price changes Dynamically reflected in the App. 

 Kindly help me out in the code or any other process to remove this restriction... Thank You

**Comment by minhcasi** [comment]
Hi, pls update the common/contants.js file and update the LimitAddToCart number (it's default 10)
