### ISSUE TITLE
"Your Cloud Firestore database has insecure rules"

### ISSUE THREAD

**Issue by stickypages** [inspireui/support#4202]
I received an email from Firebase today, saying "Your Cloud Firestore database has insecure rules". 

We need to look into the 'rules' for firebase. Need to tighten up the security a bit so it's not as loose.

Any thoughts on how to adjust the rules, and still function well?

**Comment by minhcasi** [comment]
@stickypages - yes there is no problem - thank you!

**Comment by minhcasi** [comment]
pls use this guide - https://cloud.google.com/firestore/docs/security/insecure-rules - we will update our document as well
