### ISSUE TITLE
Resize space in row products

### ISSUE THREAD

**Issue by jvsamoa** [inspireui/support#4203]
Hello,

I need to reduce the white space inter-row.
![image](https://user-images.githubusercontent.com/25646978/87487541-39e80380-c63e-11ea-8321-5e42aec5d011.png)
 
And upload my custom app icon and change his name.
I can change the Splashscreen, header logotype and menu icon. But I can't change the app icon.

**Comment by minhcasi** [comment]
@jvsamoa - pls use the latest `1.7.6` to fix the spacing issue

Also, follow this guide to generate the icon - https://docs.inspireui.com/fluxstore/delivery/#13-change-the-app-icon
