### ISSUE TITLE
Error Loading Page Domain undefind on Android

### ISSUE THREAD

**Issue by SuperXonic** [inspireui/support#4204]
Hello InspireUI Team,
I have an error on an android phone only when i try to open a webview page. It shows ” error loading page domain undefined, Error code: -6 … Description: net:ERR_CONNECTION_REFUSED” Could you tell me how to fix this issue? I really need it for uploading my app to the Play Store. For iOS works properly accept android. 
<img width="521" alt="Screen Shot 2020-07-15 at 9 25 03 AM" src="https://user-images.githubusercontent.com/52225482/87496106-1f814a80-c67d-11ea-8db1-4a7650a342bc.png">

Best Regards,

**Comment by luyx2412** [comment]
Hi @SuperXonic Please submit the form which included your config. I will check your config and reply you soon.

Thanks

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
