### ISSUE TITLE
FluxStore Shopify Home Product Card listing is not loading

### ISSUE THREAD

**Issue by Muad96** [inspireui/support#4205]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: the "[Product Card listing](https://docs.inspireui.com/fluxstore/home-layout/#4-product-card-listing)" is  not loading on Home activity.
As well as I have this issue  #4033
+ Product & version: 1.7.5
+ Flutter (or React Native) version: 1.19.0-4.3
+ Testing Device/Simulator: Pixel 3a XL API 30
+ Screenshot issues (drag the file to attach here): 

![image](https://user-images.githubusercontent.com/38084566/87499578-50548600-c663-11ea-8b08-2b5206d6e13e.png)
![image](https://user-images.githubusercontent.com/38084566/87499602-5d717500-c663-11ea-9fda-b556d42aef1c.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**
**DONE**

**Comment by minhcasi** [comment]
@Muad96 - could you try to check if it has the same on Fluxbuilder - http://fluxbuilder.com/?

After config the site on fluxbuilder, you could copy the JSON config to the project

**Comment by Muad96** [comment]
@minhcasi yes, at first I've built the app using Fluxbuilder v1.0.6 and was also having the same issue. However, the home activity preview within the Fluxbuilder is displaying all as expected.

**Comment by minhcasi** [comment]
i could be a minor UI issue, we will have a check and let you know

**Comment by Muad96** [comment]
@minhcasi @luyx2412
Could you please grant me access to the source code ?  I need to resolve the #4033 issue related to the category page.

**Comment by luyx2412** [comment]
Hi @Muad96 I just invited you to FluxShopify repo latest version which fixed your issue.

Thanks

**Comment by Muad96** [comment]
> Hi @Muad96 I just invited you to FluxShopify repo latest version which fixed your issue.
> 
> Thanks

Thank you for the invite. I've tried to merge the new codes [FIX] & [UPDATE] manually to my current project. It did solve the Home Activity issue and now my products are showing as well it fixed part of the category issue. Now if you go back to the category it will display again but the issue now is the category will only show the 1st 20 items (1st page). It won't load new items. (Fluxbuilder seems to not have this issue)

![load_new_items_issue](https://user-images.githubusercontent.com/38084566/87741574-86be0c80-c7ed-11ea-9c39-598787c3f1a2.gif)


I've tried to build new project using your demo and the last code and got the same issue.

One more thing, once drag down to refresh, it will try to load forever (this issue also occurs in Fluxbuilder )

![image](https://user-images.githubusercontent.com/38084566/87740921-0b0f9000-c7ec-11ea-9ad3-043fcca3985d.png)


**Kindly update me as soon as there is a fix to the loading new items issue.**

Thanks

**Comment by Muad96** [comment]
@luyx2412 There is another issue. filters does not seems to be working at all.
![image](https://user-images.githubusercontent.com/38084566/87762357-b126be80-c81b-11ea-9906-a1a3cd8bcd26.png)

**Comment by luyx2412** [comment]
Hi @Muad96 Thanks for your report, let me investigate and reply you soon.

Thanks

**Comment by shahzadshah123** [comment]
hello dear i purchase a code and getting error on product on home page  i filled a form

**Comment by luyx2412** [comment]
Hi @shahzadshah123 Please create your issue, i will support you.

Hi @Muad96 The issue related `cursor: null` which to query next version. This is a document about it https://shopify.dev/concepts/graphql/pagination. So can you send me your project via inspireui.team@gmail.com let me investigate your case.

Thanks

**Comment by Muad96** [comment]
@luyx2412 I've sent you my project files.

Please note that I found other issues related to checkout.
Does the native checkout works? 
- If I add multiple variants of the same product it will only increase the number of quantity and not add new line in the cart. This will lead to wrong item order + total amount of the order as it will multiply the qty*price of first variant.
- Shopping charges won't be calculated and won't be included in grand total.
- I wasn't able to enable my payments methods including COD.

And if the user logged-in then tried to checkout and while using Webview Checkout, the user will have to re-sign in again. This could lead to frustration.

**Comment by shahzadshah123** [comment]
I will share my code within just a 5 mins I am getting that cursor error
just

**Comment by shahzadshah123** [comment]
how and where to create an issue

**Comment by shahzadshah123** [comment]
cursor nul error , the product view on home page is blinked when run but
then disappeared please update me with proper working code, designed using
fluxbuilder

**Comment by Muad96** [comment]
> Hi @shahzadshah123 Please create your issue, i will support you.
> 
> Hi @Muad96 The issue related `cursor: null` which to query next version. This is a document about it https://shopify.dev/concepts/graphql/pagination. So can you send me your project via [inspireui.team@gmail.com](mailto:inspireui.team@gmail.com) let me investigate your case.
> 
> Thanks

@luyx2412 Any update ?

**Comment by Muad96** [comment]
@minhcasi
@luyx2412
1. Products list not loading all products of a category. Only 1st 21 items
1. Product list will load forever upon 'drag down to load'
1. Entering wrong credentials in the login activity  will return code error
1. Cart activity doesn't recognize Variant and will only multiple qty*(first variant added price)
1. Shipping method are fetched based on the country string (full name) not country code (**once the name of country change shipping method will load forever**)
1. Address saved on the app won't sync with the website and vice versa.
1. Reviews does not work in the app and won't be fetched
1. Related Product in the product activity is broken
1. Native payment method won't fetch active methods from the website


**The 1st 4 points are critical** 


These all the issue I'm facing and without them I can't release the app as it would be unusable, and for me the project seems unfinished and shouldn't be sold

I hope there is a timeline for when these will be fixed so I could know if I should wait or look for alterative

**Comment by minhcasi** [comment]
@Muad96 - note with investigating - thank you!

**Comment by Muad96** [comment]
@minhcasi
@luyx2412
Any update it's been 1 week already? How long it's gonna take?

**Comment by minhcasi** [comment]
We wanted to thank you for your patience during this busy time. We currently have reduced staff and a significantly higher volume of inquiries. We’re working as hard as we can to get to your request as soon as possible.

We sincerely apologize for the delay and hope you’re staying safe.

**Comment by luyx2412** [comment]
Hi @Muad96 Sorry about the delay. I just push new code which fixed
- Load more products
- Pull to refresh
- Can you give me the specific issue screenshot? i tested with your config and still work normal
- We will update variant issue soon
- Investigating
- The address sync with the website, we did not support this feature
- I hide review section in product detail, currently we did not support it
- Fixed related product
- Investigating

Thanks

**Comment by Muad96** [comment]
@luyx2412  Thank you for you update. I'll check fix and let you know how it goes.

Regarding the Signin issue find the screenshots below 

![image](https://user-images.githubusercontent.com/38084566/88474548-3e5ec700-cf30-11ea-820d-0108f2ebc5e8.png)

Console
![image](https://user-images.githubusercontent.com/38084566/88474583-a31a2180-cf30-11ea-9879-6e582fbdcf9e.png)

**Comment by Muad96** [comment]
@luyx2412 Any update regarding the variant issue?

**Comment by luyx2412** [comment]
Hi @Muad96 I just sent you the video login, please check email muaadh96@gmail.com. The login still work normal in Fluxshopify repo latest version. Please check it again.

Thanks

**Comment by Muad96** [comment]
@luyx2412 I'd appreciate if you don't mention my email.

Regarding the login issue, yes it's working fine and will let you sign-in. What I mentioned as an issue was if you typed in WRONG credentials, the error massage will be shown instead of something like "Wrong username or password"

**Comment by luyx2412** [comment]
Hi @Muad96 You can show the message if some exception case appear. Currently we just show default error of shopify response. We will improve your feedback with next version.

Thanks

**Comment by Muad96** [comment]
@luyx2412 @minhcasi 
I've notice that I no longer have access to GitLab Repo. I'm getting the following

![image](https://user-images.githubusercontent.com/38084566/89104327-42538300-d421-11ea-974a-a368fb38aca3.png)

And please let me let me know if there is any update regarding the variant issue. Thanks

**Comment by minhcasi** [comment]
@Muad96 - we are not sure on this issue, did you log in with different GitLab account? pls try to submit this link again - http://gitlab.inspireui.com

**Comment by Muad96** [comment]
> @Muad96 - we are not sure on this issue, did you log in with different GitLab account? pls try to submit this link again - http://gitlab.inspireui.com
> 
> > **[Google Forms - create and analyze surveys, for free.](http://gitlab.inspireui.com/)**Create a new survey on your own or with others at the same time. Choose from a variety of survey types and analyze results in Google Forms. Free from Google.

I'm using the same account that had access to the Gitlab repo.
@minhcasi I have emailed you regarding the issue, please grant access.

**Comment by minhcasi** [comment]
@Muad96 - pls help to submit this form - http://gitlab.inspireui.com - another team will send you the invitation - thank you!

**Comment by Muad96** [comment]
Done!

**Comment by minhcasi** [comment]
sent 👍

**Comment by Muad96** [comment]
@luyx2412 could you please let me know if I should expect a fix for the **Variant issue** this week ?
Thanks

**Comment by luyx2412** [comment]
Hi @Muad96 Can you give me the specific issue about the variant?

Thanks

**Comment by Muad96** [comment]
@luyx2412 "Cart activity doesn't recognize Variant and will only multiple qty*(first variant added price"

Check the following GIF to understand the issue.
![variant-issue-2020 08 05-23_30_55](https://user-images.githubusercontent.com/38084566/89461138-195e2580-d774-11ea-934d-6b82c14217bd.gif)

Thanks

**Comment by Muad96** [comment]
@luyx2412 Any update regarding the Variant issue?

**Comment by luyx2412** [comment]
Hi @Muad96 We are investigating and update the issue. I will mention you when finish.

Thanks

**Comment by luyx2412** [comment]
Hi @Muad96 Please pull latest code version in FluxShopify repo which fixed the issue.

Thanks

**Comment by minhcasi** [comment]
Let us know if you have any question - thank you!
