### ISSUE TITLE
Issue with Caching Plugin - Fluxstore MV

### ISSUE THREAD

**Issue by zubaerabdullah** [inspireui/support#4207]
My old ticket for verification = https://github.com/inspireui/support/issues/3998

My old ticket for verification = https://github.com/inspireui/support/issues/3998

My old ticket for verification = https://github.com/inspireui/support/issues/3998

https://github.com/inspireui/support/issues/3998

**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: I have installed the latest version of mstoreapi on the website and uploaded the json file for caching but when i tested the website it is giving error. URL: http://prostut.com/wp-json/mstore/v1/cache
+ Product & version: 1.7.5 MV
+ Flutter (or React Native) version: Latest
+ Testing Device/Simulator: Iphone 11 pro
+ Screenshot issues (drag the file to attach here): 
You can test this url to reproduce the issue

http://prostut.com/wp-json/mstore/v1/cache

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@minhtruong315 - pls help to check this issue - thank you!

**Comment by zubaerabdullah** [comment]
https://drive.google.com/file/d/1sJS-fXZIkk5i-FBWCMfKRaU9SPSeDmeW/view?usp=sharing


After updating mstoreapi, i have lost my products and stores page again.

Before i was able to see my products and store page and products in category.

I need to urgently solve this issue surely caused via updating mstore api. I need help. Please check the video and provide the solution. Thanks.

**Comment by minhtruong315** [comment]
Hi @zubaerabdullah can u send me full your source code via email: minhtruong315@gmail.com
Thanks

**Comment by zubaerabdullah** [comment]
zubaerabdullah11@gmail.com that send via this mail.

**Comment by zubaerabdullah** [comment]
please check from![Screenshot_2020-07-20-20-49-00-11.jpg](https://user-images.githubusercontent.com/67655001/87951570-8dd56b00-caca-11ea-99e7-4acd23ca754f.jpg)

**Comment by minhtruong315** [comment]
Hi @zubaerabdullah can u send me admin account via my email?
Thanks

**Comment by minhtruong315** [comment]
Hi @zubaerabdullah please update MStore Api plugin and try again

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
