### ISSUE TITLE
Erro Compiler in "flutter build apk" in new version 1.7.6

### ISSUE THREAD

**Issue by daboujey** [inspireui/support#4208]
**_Step 1 (require): describe detail issues & screenshots_**
Detail Issues: Page productos display list as default view, without having to select list on the filter page
Product & version: Version: 1.7.6
Screenshot issues (drag the file to attach here):

Error in "flutter build apk" in new version 1.7.6

Microsoft Windows [versão 10.0.18362.900]
(c) 2019 Microsoft Corporation. Todos os direitos reservados.

C:\DABOUJEY\APP_CHURROS_V3>flutter build apk
You are building a fat APK that includes binaries for android-arm, android-arm64, android-x64.
If you are deploying the app to the Play Store, it's recommended to use app bundles or split the APK to reduce the APK size.
    To generate an app bundle, run:
        flutter build appbundle --target-platform android-arm,android-arm64,android-x64
        Learn more on: https://developer.android.com/guide/app-bundle
    To split the APKs per ABI, run:
        flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
        Learn more on:  https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split
Running Gradle task 'assembleRelease'...

Compiler message:
Error: Could not resolve the package 'fstore' in 'package:fstore/widgets/home/search/home_search_page.dart'.
lib/route.dart:2:8: Error: Not found: 'package:fstore/widgets/home/search/home_search_page.dart'
import 'package:fstore/widgets/home/search/home_search_page.dart';
       ^
Error: Could not resolve the package 'fstore' in 'package:fstore/models/category/category_model.dart'.
Error: Could not resolve the package 'fstore' in 'package:fstore/models/filter_attribute.dart'.
Error: Could not resolve the package 'fstore' in 'package:fstore/models/filter_tags.dart'.
Error: Could not resolve the package 'fstore' in 'package:fstore/tabbar.dart'.
lib/screens/search/search.dart:4:8: Error: Not found: 'package:fstore/models/category/category_model.dart'
import 'package:fstore/models/category/category_model.dart';
       ^
lib/screens/search/search.dart:5:8: Error: Not found: 'package:fstore/models/filter_attribute.dart'
import 'package:fstore/models/filter_attribute.dart';
       ^
lib/screens/search/search.dart:6:8: Error: Not found: 'package:fstore/models/filter_tags.dart'
import 'package:fstore/models/filter_tags.dart';
       ^
lib/screens/search/widgets/filters/filter_search.dart:5:8: Error: Not found: 'package:fstore/models/category/category_model.dart'
import 'package:fstore/models/category/category_model.dart';
       ^
Error: Could not resolve the package 'fstore' in 'package:fstore/models/search.dart'.
lib/screens/settings/wishlist.dart:2:8: Error: Not found: 'package:fstore/tabbar.dart'
import 'package:fstore/tabbar.dart';
       ^

![erro0001](https://user-images.githubusercontent.com/64880213/87524974-3e70e400-c65f-11ea-8c32-e5d9d5e87b08.JPG)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@daboujey - pls make sure to keep the name `fstore` from pubspec.yaml

**Comment by daboujey** [comment]
Microsoft Windows [versão 10.0.18362.900]
(c) 2019 Microsoft Corporation. Todos os direitos reservados.

C:\DABOUJEY\APP_CHURROS_V3>flutter build apk
Running "flutter pub get" in APP_CHURROS_V3...                      6,3s
You are building a fat APK that includes binaries for android-arm, android-arm64, android-x64.
If you are deploying the app to the Play Store, it's recommended to use app bundles or split the APK to reduce the APK size.
    To generate an app bundle, run:
        flutter build appbundle --target-platform android-arm,android-arm64,android-x64
        Learn more on: https://developer.android.com/guide/app-bundle
    To split the APKs per ABI, run:
        flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
        Learn more on:  https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split
Running Gradle task 'assembleRelease'...
Invalid depfile: C:\DABOUJEY\APP_CHURROS_V3\.dart_tool\flutter_build\7fef6e46c321c8f59a25155dbcdc610d\kernel_snapshot.d
Invalid depfile: C:\DABOUJEY\APP_CHURROS_V3\.dart_tool\flutter_build\7fef6e46c321c8f59a25155dbcdc610d\kernel_snapshot.d
Invalid depfile: C:\DABOUJEY\APP_CHURROS_V3\.dart_tool\flutter_build\7fef6e46c321c8f59a25155dbcdc610d\kernel_snapshot.d
Invalid depfile: C:\DABOUJEY\APP_CHURROS_V3\.dart_tool\flutter_build\7fef6e46c321c8f59a25155dbcdc610d\kernel_snapshot.d
Invalid depfile: C:\DABOUJEY\APP_CHURROS_V3\.dart_tool\flutter_build\7fef6e46c321c8f59a25155dbcdc610d\kernel_snapshot.d
Invalid depfile: C:\DABOUJEY\APP_CHURROS_V3\.dart_tool\flutter_build\7fef6e46c321c8f59a25155dbcdc610d\kernel_snapshot.d
Invalid depfile: C:\DABOUJEY\APP_CHURROS_V3\.dart_tool\flutter_build\7fef6e46c321c8f59a25155dbcdc610d\kernel_snapshot.d
Invalid depfile: C:\DABOUJEY\APP_CHURROS_V3\.dart_tool\flutter_build\7fef6e46c321c8f59a25155dbcdc610d\kernel_snapshot.d
Invalid depfile: C:\DABOUJEY\APP_CHURROS_V3\.dart_tool\flutter_build\7fef6e46c321c8f59a25155dbcdc610d\kernel_snapshot.d
Invalid depfile: C:\DABOUJEY\APP_CHURROS_V3\.dart_tool\flutter_build\7fef6e46c321c8f59a25155dbcdc610d\kernel_snapshot.d
Invalid depfile: C:\DABOUJEY\APP_CHURROS_V3\.dart_tool\flutter_build\7fef6e46c321c8f59a25155dbcdc610d\kernel_snapshot.d
Invalid depfile: C:\DABOUJEY\APP_CHURROS_V3\.dart_tool\flutter_build\7fef6e46c321c8f59a25155dbcdc610d\kernel_snapshot.d

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     C:\DABOUJEY\APP_CHURROS_V3\android\app\src\main\AndroidManifest.xml:64:9-66:51: AAPT: error: resource color/notiColor (aka com.churros.liv:color/notiColor) not found.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 24m 35s
Running Gradle task 'assembleRelease'...
Running Gradle task 'assembleRelease'... Done                    1477,4s (!)
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
✏️  Creating `android\settings_aar.gradle`...
[!] Flutter tried to create the file `android\settings_aar.gradle`, but failed.
To manually update `settings.gradle`, follow these steps:

    1. Copy `settings.gradle` as `settings_aar.gradle`
    2. Remove the following code from `settings_aar.gradle`:

        def localPropertiesFile = new File(rootProject.projectDir, "local.properties")
        def properties = new Properties()

        assert localPropertiesFile.exists()
        localPropertiesFile.withReader("UTF-8") { reader -> properties.load(reader) }

        def flutterSdkPath = properties.getProperty("flutter.sdk")
        assert flutterSdkPath != null, "flutter.sdk not set in local.properties"
        apply from: "$flutterSdkPath/packages/flutter_tools/gradle/app_plugin_loader.gradle"

Please create the file and run this command again.

C:\DABOUJEY\APP_CHURROS_V3>

**Comment by minhcasi** [comment]
This could be the root cause on your pc: flutter.sdk not set in local.properties - pls check if you have config the flutter sdk on this file

<img width="898" alt="Screen Shot 2020-07-17 at 16 36 45" src="https://user-images.githubusercontent.com/1459805/87772289-b6036680-c84b-11ea-9e31-57e1a4c45661.png">

**Comment by daboujey** [comment]
Many errors after the android studio update, I need downgrade versions, android studio, flutter and dart, which android studio version used in the original app ? which flutter version and dart ???

I want to use the same versions that you used

**Comment by daboujey** [comment]
I believe it is errors after updating android studio flutter and give it to the last version

**Comment by daboujey** [comment]
![image](https://user-images.githubusercontent.com/64880213/87784972-b250ef00-c80d-11ea-9c32-483205ac7b8e.png)

**Comment by minhcasi** [comment]
@daboujey - pls also update the latest flutter plugin on android studio.

You could fix the cache issue by following this guide https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1
