### ISSUE TITLE
Run failed for android tools r8

### ISSUE THREAD

**Issue by TqwaAlTurki** [inspireui/support#4210]
Detail Issues: I cloned the project in other laptop and i got this error when i hit run. ( Note that i followed some instructions online that says delete .gradle and .idea folders so i deleted them and nothing happed, also i followed instructions that says add some code in the project\android\app\build.gradle file i added it and still nothing happened :| . i also followed your instructions here #3530 ). 
Now that i've done everything i could, i'm not sure what to do and need your help with my case please.
Product & version: Fluxstore WooCommerce version 1.7.4
Flutter version:  v1.17.2
Testing Device/Simulator: Android Emulators
Screenshot issues: 
The error i got:
![image](https://user-images.githubusercontent.com/34610407/87536965-2e2a2a80-c69a-11ea-8667-84fc954038ae.png)

 The code i added: 
![image](https://user-images.githubusercontent.com/34610407/87537872-9f1e1200-c69b-11ea-8835-eee211dc3ca3.png)

My SDK tools: 
![image](https://user-images.githubusercontent.com/34610407/87537923-bbba4a00-c69b-11ea-8e20-ee61d0e424b5.png)

 My project\android\gradle\wrapper\gradle-wrapper.properties:
![image](https://user-images.githubusercontent.com/34610407/87538293-48650800-c69c-11ea-98ae-3e7a1880e06e.png)

Flutter Doctor: 
![image](https://user-images.githubusercontent.com/34610407/87538768-186a3480-c69d-11ea-8903-cf2edd90c161.png)

**Comment by ameenbadri7** [comment]
sir download the latest version it's now 1.7.6 your version is too old .. before two months. 
thank you, sir.
send your GitLab email we will add you to request via our email minhcasi@gmail.com and inspireui-team@inspireui.com.
