### ISSUE TITLE
Where can I edit the text here? (Fluxnews)

### ISSUE THREAD

**Issue by TerWeWebStudio** [inspireui/support#4211]
+ Where can I edit the text here?
+ Fluxnews 1.4.1
+ Flutter 1.17.5
+ Testing Device/Simulator: Android Pixel 2 API 29
+ Screenshot : https://prnt.sc/ti7ab0

Thanks.

![Screenshot_7](https://user-images.githubusercontent.com/68330579/87539668-82e49a00-c6c8-11ea-8f1a-63044231a69d.png)

**Comment by realmultimedia** [comment]
I changed mine from lib/generated/intl/messages_en.dart 
line 231

(not sure if it's the correct usage, but it works)

**Comment by ameenbadri7** [comment]
@realmultimedia 
We're glad that it helps, 😊
please give us some feedback/rating to [this page](https://codecanyon.net/downloads), 
we are working hard to update more awesome and powerful features on the next coming version release. 
Let us know if you have any feedback. 
Thank you very much ❤️ 

please close this ticket if every thing works perfectly.

**Comment by TerWeWebStudio** [comment]
> I changed mine from lib/generated/intl/messages_en.dart
> line 231
> 
> (not sure if it's the correct usage, but it works)

Thanks.

**Comment by realmultimedia** [comment]
It doesn't make any sense though, as when you close and reopen the app, the "generated" files will be back as before.

**Comment by realmultimedia** [comment]
lib/l10n/intl_en.arb this is the main file that you need to modify to customise your UI text. 
(generated will be always overwritten, therefore, disregard the previous solution)
