### ISSUE TITLE
Product not showing when opening category for the second time (can you tell how to change backgound color of all screens ? its white at the moment)

### ISSUE THREAD

**Issue by RomeoDar** [inspireui/support#4213]
Detail Issues: When I click on any category after opening the app, I get product list for the first time but when I refresh or click on it again on the same category nothing displays, (it display no products) and the same for any other categories too, after opening app product is displayed once then it disappear.
the only modification I did is the website domain and the access key, i just purchases this project (that mean its latest)
Am I missing something?
(my problem is similar to #3949 and #4093)

+ Product & version: Version: 1.7.5 and its Fluxstore Shopify
+ Flutter (or React Native) version:  Flutter
+ Testing Device/Simulator: Oppo F7 and Emulator
+ Screenshot issues (drag the file to attach here): 
https://user-images.githubusercontent.com/52714884/87554839-179dc680-c6ce-11ea-8bb7-3ca643151446.jpeg

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by RomeoDar** [comment]
i've submitted the ticket twice...looking for solution, add hdar001@gmail.com in GitLab repo

**Comment by RomeoDar** [comment]
Still Waiting.......

**Comment by RomeoDar** [comment]
@luyx2412 @luyx2412  just me to fluxshopify repo so i can access latest version of the code in which you guys already solved this issue #4093.... i'm waiting its urgent

**Comment by luyx2412** [comment]
Hi @RomeoDar I just invited you to the FluxShopify latest repo which fixed the issue.

Thanks

**Comment by Pankaj-Sakariya** [comment]
Hey @minhcasi @luyx2412  Why you have closed this issue without resolving my issue? 

Product not showing when opening category for the second time #4217

Kindly reopen it or allow access to GitLab branch, so I can resolve it by myself.

**Comment by RomeoDar** [comment]
lemme test, i'll get back to you soon

**Comment by RomeoDar** [comment]
@luyx2412 Thanks it works, appreciate your support but i need to ask few question, why there is not any login with gmail and login with phone feature available in the app (i've bought fluxstore Pro and Fluxstore MV those projects use login with gmail and phone number), can you add login with gmail and phone authentication too ?

**Comment by RomeoDar** [comment]
and i need to change background color of the app (at the moment its white can you send me file name on which i'll change background color) just answer these question and you can close this ticket after answering (thanks, i always love ur support)

**Comment by RomeoDar** [comment]
everything work well, Thanks

**Comment by RomeoDar** [comment]
@luyx2412  can you tell how to change background (white) color of all screens ? its white at the moment
