### ISSUE TITLE
app name changed - app crashing

### ISSUE THREAD

**Issue by realmultimedia** [inspireui/support#4216]
Hi, 

After I finally managed to customise the app, it no longer works when I change the name.

changed name in:

debug/AndroidManifest.xml
main/AndroidManifest.xml
profile/AndroidManifest.xml
app/MainActivity.kt
folders renamed: com/christianstyle/app

res/values/strings - renamed
google-services.json - downloaded from firebase

<img width="1440" alt="Screenshot 2020-07-15 at 17 00 04" src="https://user-images.githubusercontent.com/68022923/87567825-a86ba680-c6bc-11ea-8388-d6b566e736c7.png">
<img width="1440" alt="Screenshot 2020-07-15 at 17 00 46" src="https://user-images.githubusercontent.com/68022923/87567926-c20cee00-c6bc-11ea-9ef6-394c86d8f099.png">

Any other advice?

**Comment by realmultimedia** [comment]
Edit: - iOS works. Android doesn't

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 
Thank you for your time!

**Comment by realmultimedia** [comment]
Form sent, however, you can replicate the error by using the 1.4.1 version and trying to change name, then build for android.

**Comment by minhcasi** [comment]
@realmultimedia - try to zip your android folder and share here - we will help for checking - thanks

**Comment by realmultimedia** [comment]
[android.zip](https://github.com/inspireui/support/files/4929882/android.zip)

**Comment by minhcasi** [comment]
you android folder seems config correctly - i've sent to the team for further investigating - thanks

**Comment by minhcasi** [comment]
@realmultimedia - could you zip the source and share private to inspireui.team@gmail.com - our team report all good with your android config - thank you!

**Comment by realmultimedia** [comment]
Hi, 
it's 4GB I cannot send it. (why is it so large?)

To replicate the issue:
- you download the latest source from themforest, you change the name and send it back.

As I said, iOS is working. The only issue is with the android.

**Comment by realmultimedia** [comment]
> @realmultimedia - could you zip the source and share private to [inspireui.team@gmail.com](mailto:inspireui.team@gmail.com) - our team report all good with your android config - thank you!

I have also sent a request to access the previous versions, days ago. No reply, no access yet. 
That's a bit disappointing.

**Comment by minhcasi** [comment]
We got your feedback, it's disappointing when dealing with the way that someone is helping you, we don't mind processing the refund your purchase products to save your time.
