### ISSUE TITLE
Product not showing when opening category for the second time

### ISSUE THREAD

**Issue by Pankaj-Sakariya** [inspireui/support#4217]
Detail Issues: When I click on any category after opening the app, I get product list for the first time but when I refresh or click on it again on the same category nothing displays, (it display no products) and the same for any other categories too, after opening app product is displayed once then it disappears.
the only modification I did is the website domain and the access key, i just purchase this project (that mean it is latest)
Am I missing something?
(my problem is similar to #3949 and #4093 #4213 )

Product & Version: Version: 1.7.5 and its Fluxstore Shopify
Flutter (or React Native) version: Flutter

Screenshot issues (drag the file to attach here):
https://user-images.githubusercontent.com/52714884/87554839-179dc680-c6ce-11ea-8bb7-3ca643151446.jpeg

Also, in Shopify code - why the blog is coming from WordPress? are we not supporting Shopify blog?

**Comment by Pankaj-Sakariya** [comment]
Also fill up form : http://verify.inspireui.com/

Kindly revert asap.

**Comment by Pankaj-Sakariya** [comment]
Hi @minhcasi 
Hope you are doing well. 

Meanwhile, you are checking on this issue, can anyone assign the access of GitLab repo? so I can also check parallel. 
Appreciate your quick response on access.

**Comment by minhcasi** [comment]
@Pankaj-Sakariya - thank you for the contact. 

As you are using our product to distribute as a commercial purpose via Fiverr channel, we request to upgrade the product to Extended License (for every single product), please help to check our support policies as well - https://inspireui.com/support-policies/

Thank you for your time!

**Comment by Pankaj-Sakariya** [comment]
@minhcasi  We are not reselling this, we are helping people to support in setup and all those who are not technical and also we are promoting clients to purchase your code and then and then we provide support. 

and one more thing - this code I've purchase first time, so there is no point of reselling this. 
I would like to get support on this ticket asap.
