### ISSUE TITLE
How to Remove Ads on Fluxnews

### ISSUE THREAD

**Issue by TerWeWebStudio** [inspireui/support#4218]
**_Step 1 (require): describe detail issues & screenshots_**
How to Remove Ads on Fluxnews
Fluxnews 1.4.1
Flutter 1.17.5
Testing Device/Simulator: Android Pixel 2 API 29

![Screenshot_9](https://user-images.githubusercontent.com/68330579/87583677-8860d500-c706-11ea-9b58-31065d902940.png)

Thanks.

**Comment by realmultimedia** [comment]
lib/common/config.dart

remove everything within the ""

const kAdConfig = {
  "type": kAdType.googleReward,
  // ----------------- Facebook Ads  -------------- //

  "hasdedIdTestingDevice": "",
  "bannerPlacementId": "",
  "interstitialPlacementId": "",
  "nativePlacementId": "",
  "nativeBannerPlacementId": "",

  // ------------------ Google Admob  -------------- //

  "androidAppId": "none",
  "androidUnitBanner": "none",
  "androidUnitInterstitial": "none",
  "androidUnitReward": "none",
  "iosAppId": "none",
  "iosUnitBanner": "none",
  "iosUnitInterstitial": "none",
  "iosUnitReward": "none",
  "waitingTimeToDisplayInterstitial": 3,
  "waitingTimeToDisplayReward": 3,
};

**Comment by TerWeWebStudio** [comment]
> lib/common/config.dart
> 
> remove everything within the ""
> 
> const kAdConfig = {
> "type": kAdType.googleReward,
> // ----------------- Facebook Ads -------------- //
> 
> "hasdedIdTestingDevice": "",
> "bannerPlacementId": "",
> "interstitialPlacementId": "",
> "nativePlacementId": "",
> "nativeBannerPlacementId": "",
> 
> // ------------------ Google Admob -------------- //
> 
> "androidAppId": "none",
> "androidUnitBanner": "none",
> "androidUnitInterstitial": "none",
> "androidUnitReward": "none",
> "iosAppId": "none",
> "iosUnitBanner": "none",
> "iosUnitInterstitial": "none",
> "iosUnitReward": "none",
> "waitingTimeToDisplayInterstitial": 3,
> "waitingTimeToDisplayReward": 3,
> };

Thanks.
