### ISSUE TITLE
How to Disable Comment And Button Login Comment In Fluxnews 

### ISSUE THREAD

**Issue by TerWeWebStudio** [inspireui/support#4219]
How to Disable Comment And Button Login Comment In Fluxnews
Fluxnews 1.4.1
Flutter 1.17.5
Testing Device/Simulator: Android Pixel 2 API 29

![Screenshot_10](https://user-images.githubusercontent.com/68330579/87586928-949b6100-c70b-11ea-963e-3e0aee8a5eb5.png)

Thanks.

**Comment by minhcasi** [comment]
@TerWeWebStudio - try to use the inspector tool to customize any UI from the app https://www.youtube.com/watch?v=yGMt3Y20Zmg

Please note that we may not support answering or support technical issues for the regular license as per support policies - https://inspireui.com/support-policies/ - but we are trying to best to give extra miles with the supporting. 

Hope you enjoy the product and stay safe 😊

**Comment by minhcasi** [comment]
There is the hidden comment config here - you could try it 

<img width="805" alt="Screen Shot 2020-07-16 at 09 18 39" src="https://user-images.githubusercontent.com/1459805/87618987-5753c500-c745-11ea-822d-8a729acb1f34.png">
