### ISSUE TITLE
Eror 404 when custom payment page

### ISSUE THREAD

**Issue by ElegantSoft** [inspireui/support#422]
MStore
Item Purchase Code:
8b86468a-13a0-49b3-afb2-68a30e59cb2f

Purchase Date:
2019-01-27 10:25:05 UTC

I have copied mstore to template folder and make new page 
https://derarstore.com/mstore-checkout/
and choose Template Mstore Checkout
and still get error 404 when using telr payment gateway

**Comment by minhcasi** [comment]
@ElegantSoft  let try to the second solution from https://github.com/inspireui/support/issues/38#issuecomment-441363940

**Comment by ElegantSoft** [comment]
I have tried Both

**Comment by ElegantSoft** [comment]
?? I need help
I have tried both solution and didn't work

**Comment by minhcasi** [comment]
hi, sorry as we are missing a comment on this ticket, could I have a quick check if you have passed the issues, otherwise we please send us the detailed access then we could help for the config.
