### ISSUE TITLE
MultiVendor App Issue

### ISSUE THREAD

**Issue by FaizalAndro** [inspireui/support#4220]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: I m using wcfm, did all the things that mentioned in doc but vendors are not visible in app
+ Product & version: 1.7.5
+ Flutter (or React Native) version: Flutter
+ Testing Device/Simulator: Both
+ Screenshot issues (drag the file to attach here): It shows blank

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
any screenshot to explain the issues pls ?

**Comment by FaizalAndro** [comment]
![Screenshot_1594891677](https://user-images.githubusercontent.com/37078576/87654933-36a36380-c775-11ea-85e1-9e9c3343bbac.png)
 I created two vendors, vendors store name visible below products but when clicking in Category section Store it shows just blank

**Comment by FaizalAndro** [comment]
Hi @minhcasi  Please help in this also give me access of fresh code. I already send request for gitlab code access

**Comment by minhcasi** [comment]
@FaizalAndro - it's sent - thank you!

**Comment by FaizalAndro** [comment]
Hi, Can you please check the issue, I created two vendors, vendors store name visible below products but when clicking in Category section Store it shows just blank

![Screenshot_1594891677](https://user-images.githubusercontent.com/37078576/87654933-36a36380-c775-11ea-85e1-9e9c3343bbac.png)
