### ISSUE TITLE
Vendor Shipping is not showing during checkout

### ISSUE THREAD

**Issue by mo-elkholy** [inspireui/support#4221]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: Vendor Shipping is not showing using checkout in MultiVendor with Dokan.
+ Product & version:1.7.5 + Dokan 3.0.3
+ Flutter (or React Native) version:  Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale en-AE)
+ Testing Device/Simulator: Android Studio (version 4.0) Android  10.0

+ Screenshot issues (drag the file to attach here): 
<img width="379" alt="Screen Shot 2020-07-16 at 12 34 39 AM" src="https://user-images.githubusercontent.com/46157642/87593310-5185c180-c6fc-11ea-85bc-d97c9fc5f7ef.png">
<img width="401" alt="Screen Shot 2020-07-16 at 12 34 03 AM" src="https://user-images.githubusercontent.com/46157642/87593328-59456600-c6fc-11ea-8f58-ee42379df564.png">

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**
[](https://github.com/inspireui/support/issues/4148
)

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by ameenbadri7** [comment]
if you use the woocommerce default shipping option it will show 100% but if you have other plugins you can use the woocommerce checkout by turn off the fluxstore checkout and turn on the woocommerce :
go to : `lib\common\config\payments.dart` 
change : 
```
  "EnableOnePageCheckout": false,
  "NativeOnePageCheckout": true,
```
to be : 
```
  "EnableOnePageCheckout": true,
  "NativeOnePageCheckout": false,
```

BTW: if you would like to use the custom plugin inside the fluxstore please know that we don't take customization requests for the regular license but you can buy the Extended License or Support Pack pls help to check our [support policies ](https://inspireui.com/support-policies) 
and email us with your request via our email minhcasi@gmail.com and inspireui-team@inspireui.com.

thank you.

**Comment by mo-elkholy** [comment]
I am not using any custom shipping plugins. Only the default WooCommerce shipping option. But it is not loading.

If I turn the "EnableOnePageCheckout": true,
  "NativeOnePageCheckout": false,

Then I will lose the native option, the web view is the last resort to me. I rather have the native screens than loading the webview.

What do you suggest I do Ameen?

Thank you
Mohamed

**Comment by ameenbadri7** [comment]
Currently we are very busy but our lead developer @minhcasi he will assist you about this issue.  
Thank you for your patience.

**Comment by minhcasi** [comment]
@philipvu30 - pls help to check if there is an issue from our app & pre-config site as well - thank you!

**Comment by philipvu30** [comment]
Hi,

Did you add any shipping methods in WooCommerce Settings?

**Comment by mo-elkholy** [comment]
Hi Philipvu30, yes I did screen shot bellow:

<img width="1616" alt="Screen Shot 2020-07-16 at 9 54 19 AM" src="https://user-images.githubusercontent.com/46157642/87632503-959fb300-c74a-11ea-807e-df93d6102d89.png">
<img width="1131" alt="Screen Shot 2020-07-16 at 9 54 37 AM" src="https://user-images.githubusercontent.com/46157642/87632511-9afcfd80-c74a-11ea-979f-a0a3ba8a2d4a.png">

**Comment by FaizalAndro** [comment]
same issue with me, please provide answer for this plz

**Comment by philipvu30** [comment]
Hi,

Have you submitted our [form](https://docs.google.com/forms/d/e/1FAIpQLScWOjkAJIWJ9rgb9alopfOqLsJrGKbFM5cCYj1JBfLKLsBblQ/viewform) yet? Because I can't find your config files anywhere so I am unable to help.
If you haven't, please do so.

Thank you.

**Comment by mo-elkholy** [comment]
> Hi,
> 
> Have you submitted our [form](https://docs.google.com/forms/d/e/1FAIpQLScWOjkAJIWJ9rgb9alopfOqLsJrGKbFM5cCYj1JBfLKLsBblQ/viewform) yet? Because I can't find your config files anywhere so I am unable to help.
> If you haven't, please do so.
> 
> Thank you.

It was submitted before, I submitted again , referencing this ticket.

Thanks

**Comment by mo-elkholy** [comment]
> > Hi,
> > Have you submitted our [form](https://docs.google.com/forms/d/e/1FAIpQLScWOjkAJIWJ9rgb9alopfOqLsJrGKbFM5cCYj1JBfLKLsBblQ/viewform) yet? Because I can't find your config files anywhere so I am unable to help.
> > If you haven't, please do so.
> > Thank you.
> 
> It was submitted before, I submitted again , referencing this ticket.
> 
> Thanks

yes I did hours ago. how come you are net receiving it?

<img width="683" alt="Screen Shot 2020-07-16 at 7 16 14 PM" src="https://user-images.githubusercontent.com/46157642/87689134-e63dfd00-c798-11ea-9a44-752ce2f8b3e4.png">

**Comment by mo-elkholy** [comment]
Hi Team, have you managed to locate the form?
if not I can email you the purchase code the the zip file of the common and config folders.
Thank you

**Comment by philipvu30** [comment]
Hi,

My apologies for the delayed response as we do not work on the weekends.
I've already received your files. I'll get back to you when there is a result.

Thank you for your time.

**Comment by philipvu30** [comment]
Hi,

In WooCommerce Shipping zone settings, you need to add the shipping methods also.

![image](https://user-images.githubusercontent.com/54442328/87914200-80a08800-ca9a-11ea-8387-afd8891da92a.png)

**Comment by mo-elkholy** [comment]
Hi, I tried with Vendor Shipping as well as flat rate, same result no shipping method loaded.

Is vendor shipping supported in the 1.7.5 MV?

<img width="1619" alt="Screen Shot 2020-07-20 at 4 07 19 PM" src="https://user-images.githubusercontent.com/46157642/87940075-0f68d100-caaa-11ea-9a43-e5defb801a07.png">
<img width="1221" alt="Screen Shot 2020-07-20 at 4 56 50 PM" src="https://user-images.githubusercontent.com/46157642/87940086-1263c180-caaa-11ea-8012-b14b032fb632.png">

**Comment by minhtruong315** [comment]
Hi @mo-elkholy can u send me full your source code via email: minhtruong315@gmail.com
Thanks

**Comment by mo-elkholy** [comment]
Done, zip file of all the source code sent via retransfer

**Comment by minhtruong315** [comment]
@mo-elkholy can u send me admin account via my email. Thanks

**Comment by mo-elkholy** [comment]
Done

**Comment by minhtruong315** [comment]
Hi @mo-elkholy I dont see any email. pls resend me admin account.
Thanks

**Comment by mo-elkholy** [comment]
Hi, I sent to minhtruong315@gmail.com , and I sent it again now.

**Comment by minhtruong315** [comment]
Can u give me your skype?
I dont see any email.

**Comment by mo-elkholy** [comment]
malkhouly

**Comment by minhtruong315** [comment]
Hi @mo-elkholy I messaged you on the skype. pls check
Thanks

**Comment by minhtruong315** [comment]
@mo-elkholy You need to create state files. it includes code and name.
for example: if your website support United Arab Emirates country. You need to create state_ae.json. it has more states 
```
[
  {
    "code": "DU",
    "name": "Dubai"
  }
]
```
<img width="1090" alt="Screen Shot 2020-07-27 at 9 18 10 PM" src="https://user-images.githubusercontent.com/10402500/88553067-10bc6f80-d04f-11ea-906c-57198839ba1c.png">

**Comment by mo-elkholy** [comment]
Thank you, Now it loads the Flat rate but showing AED 0 , instead of AED 20

**Comment by minhtruong315** [comment]
@mo-elkholy replace this  function in models/shipping_method.dart like  this
```
ShippingMethod.fromJson(Map<String, dynamic> parsedJson) {
    try {
      id = "${parsedJson["id"]}";
      title = isNotBlank(parsedJson["title"])
          ? parsedJson["title"]
          : parsedJson["method_title"];
      description = parsedJson["method_description"];
      methodId = parsedJson["method_id"];
      methodTitle = parsedJson["method_title"];
      cost = 0.0;
      if (parsedJson["settings"]["cost"] != null) {
        if (parsedJson["settings"]["cost"] is Map) {
          cost = double.parse(parsedJson["settings"]["cost"]["value"]);
        } else {
          cost = double.parse(parsedJson["settings"]["cost"]);
        }
      }
      parsedJson["settings"]["min_amount"] != null
          ? min_amount =
              double.parse(parsedJson["settings"]["min_amount"]["value"])
          : min_amount = null;
      Map settings = parsedJson["settings"];
      settings.keys.forEach((key) {
        if (key is String && key.contains("class_cost_")) {
          classCost = parsedJson["settings"][key]["value"];
        }
      });
    } catch (e) {
      printLog('error parsing Shipping method');
    }
  }
```

**Comment by mo-elkholy** [comment]
Thank you very much, this worked. Woohoo
