### ISSUE TITLE
The screen is blank again

### ISSUE THREAD

**Issue by miguelitolaparra** [inspireui/support#4222]
**_Step 1 (require): describe detail issues & screenshots_**

The screen is blank again

+ Detail Issues: 

Hi.

1 - I have installed BeoNews Pro again and starting a new project with my website (https://recetasdemiyaya.es) created for the application, with a new code, and I have the problems I had on another occasion, the screen is displayed blank without displaying any items.

I have reviewed the file App / Common / AppConfig.json and it shows as you told me on previous occasion:
{"Name": "Top Videos",
"categories": [34],
"layout": 5},

I take this opportunity to ask another question:

2 - What file should I modify so that the application shows the Categories I have on my website, not the ones shown in this code, for example: Kids Menu, Quick Recipes, Top Videos, Favorites Salads, etc? Can you help me with this? Thank you

2 - What file should I modify so that the application shows the Categories I have on my website, not the ones shown in this code, for example: Kids Menu, Quick Recipes, Top Videos, Favorites Salads, etc? Can you help me with this?

    
3 - From the Sign In - Sign Up screen, it is impossible to exit, the exit button is very high.
4 After running react-native run-ios 5 times, categories appear on the screen, and then disappear.

The application does not show anything that my website has

This is the website: https://recetasdemiyaya.es

I hope you can help me, I have reviewed the documentation many times, I cannot get it to work.

I imagine it will be a very simple thing that I'm doing wrong, but I can't find the solution

Thank you
+ Product & version: BeoNews Pro
+ Flutter (or React Native) version: React Native
+ Testing Device/Simulator:  iPhone X (12.4)
+ Screenshot issues (drag the file to attach here): 

<img width="455" alt="Captura de pantalla 2020-07-15 a las 23 47 37" src="https://user-images.githubusercontent.com/28591454/87601584-a96cfa00-c6f5-11ea-8fbf-2710f35e9c42.png">

<img width="455" alt="Captura de pantalla 2020-07-16 a las 0 25 23" src="https://user-images.githubusercontent.com/28591454/87606571-98bf8280-c6fb-11ea-8add-a1dcfc696f2b.png">

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by ameenbadri7** [comment]
It would be batter to use the documentation 
docs.inspireui.com/mstore/getting-started/
You could know alot about the app. 

To add a banner use this page 

https://docs.inspireui.com/mstore/customize-branding/

**Comment by minhcasi** [comment]
@luyx2412 - pls help with checking

**Comment by miguelitolaparra** [comment]
> @ luyx2412 - pls ayuda con la comprobación
Hi.
Thanks for your comments.
I don't understand what you mean,
Should I add more details so they can help me?
I have followed the BeoNews Pro documentation but cannot get a link to my website
  What details should I add to my question so they can help me?
Thank you

**Comment by luyx2412** [comment]
Hi @miguelitolaparra Can you check your config in wordpress website? I just checked your config and the api response wrong format.
![image](https://user-images.githubusercontent.com/8909619/87689267-35445c00-c7b2-11ea-9374-68ed3f4ec0f7.png)

Thanks

**Comment by miguelitolaparra** [comment]
> Hi @miguelitolaparra Can you check your config in wordpress website? I just checked your config and the api response wrong format.
> ![image](https://user-images.githubusercontent.com/8909619/87689267-35445c00-c7b2-11ea-9374-68ed3f4ec0f7.png)
> 
> Thanks
Hi. Thanks for your reply.


 My WP website settings are the same as shown in the instructions.

 I have put my url and the file App / Common / AppConfig.json are as the instructions say.

 I have installed the plugins mentioned in the documentation and this is the result I have.
 There is no more WordPress setting in the instructions.

 What am I doing wrong ?

However, if I run the application without modifying the URL, leaving http://news.inspireui.com, the application works perfectly. So, as you say, the error is on my website.

But I have followed the instructions as shown. Should I modify more files?
With the error that you show,
Where should I look for errors on my website?
I have only modified what these instructions say, which is the URL and I have installed and activated the plugins that are mentioned, I have modified the Permanent URL and I have not modified more things in WP, only what is shown [on this page.](https://docs.inspireui.com/beonews/wordpress-setting/)
I will keep looking, but I can go round and round, since I don't know what to look for. Thanks for your support.

**Comment by miguelitolaparra** [comment]
Hello again @luyx2412 , I have reviewed over and over and decided to start a new project.


I have started a project from scratch and managed to connect the application to my website.

Can you tell me what steps I need to take to display my website categories and my website recipes?

Should I follow exactly what the [documentation](https://docs.inspireui.com/beonews/customization/) says?
  Thank you

**Comment by luyx2412** [comment]
HI @miguelitolaparra Can you create new account with inspireui.team@gmail.com email in your wordpress dashboard, after that send via inspireui.team@gmail.com with title `4222`. Let me see your config and investigate.

Thanks

**Comment by miguelitolaparra** [comment]
> HI @miguelitolaparra ¿Puede crear una cuenta nueva con el [correo](mailto:inspireui.team@gmail.com) electrónico [inspireui.team@gmail.com](mailto:inspireui.team@gmail.com) en su panel de WordPress, luego envíe a través de [inspireui.team@gmail.com](mailto:inspireui.team@gmail.com) con el título `4222`. Déjame ver tu configuración e investigar.
> 
> Gracias
 Hi.
 Excuse me for being late to respond.
I've already created a USER in my WordPress dashboard for you, and sent you the credentials to connect.
The subject of my email is: 4222
As I already explained in my email, if it is not possible to show the website in the application, you let me know and show me which of your topics would be the one indicated to show my website with the list of cooking recipes and their categories .
I will buy the theme with which I can create my application and simply BeoNews, I will use it for another project.
I hope to create a Kitchen Recipes application, and get new customers to upload it to the app stores.
Read the message I sent to your email.

 Greetings and thanks for your support.

**Comment by luyx2412** [comment]
Hi @miguelitolaparra In each field or category you want to show on the home screen, please right id in AppConfig.json. I tested your categories and everything response empty products. So please publish product and add right category id in your AppConfig.json

Thanks

**Comment by miguelitolaparra** [comment]
Thanks for your reply.

But the categories that my application shows, are not those that the AppConfig.json file has, but rather that it shows the categories that are in the entries of my blog, as I show you in the capture categorysEntradas.png

<img width="1476" alt="categorysEntradas" src="https://user-images.githubusercontent.com/28591454/88476342-efb52b00-cf37-11ea-88af-a2aecc68125f.png">



 This is my AppConfig.json file:
```
{
  "URL": {
    "root": "https://recetasdemiyaya.es"
  },
  "HorizonLayout": [ 
    {
      "tags": [
        39
      ],
      "paging": true,
      "layout": 4
    },
    {
      "name": "Top Videos",
      "categories": [
        34
      ],
      "layout": 5
    },
    {
      "name": "Quick Recipes",
      "categories": [
        36
      ],
      "paging": true,
      "row": 3,
      "layout": 3
    },
    {
      "name": "Favorites Salads",
      "categories": [
        32
      ],
      "layout": 2
    },
    {
      "name": "Kids Menu",
      "categories": [
        37
      ],
      "layout": 11,
      "width": 120,
      "height": 250
    },
    {
      "name": "Drinks",
      "categories": [
        41
      ],
      "paging": true,
      "row": 3,
      "layout": 10
    },
    {
      "name": "Smoothies",
      "categories": [
        33
      ],
      "paging": true,
      "layout": 1
    }
  ],
  "MainColor": "#1CB5B4"
}
```

and the categories are not those that my application shows in the iPhone simulator It shows those categories, but it does not show the images that I have assigned those categories as you will see in the screenshots of my iPhone simulator.



<img width="474" alt="category1" src="https://user-images.githubusercontent.com/28591454/88476354-08bddc00-cf38-11ea-95a3-12a013527ba4.png">
<img width="474" alt="category2" src="https://user-images.githubusercontent.com/28591454/88476355-0d829000-cf38-11ea-8de4-46bb69a0744f.png">
<img width="474" alt="category3" src="https://user-images.githubusercontent.com/28591454/88476358-0eb3bd00-cf38-11ea-8d5b-e2ebc27b01a1.png">


 As I said before, I need the application to show the content of my website, not the content of the Blog and the blog posts (https://recetasdemiyaya.es/noticias/)
For example, the categories of my website are the following: https://recetasdemiyaya.es/categorias/

All recipes on my website are as follows: https://recetasdemiyaya.es/todas-recetas/

I ask you again the question I asked you last days:
Is it possible to display the content of my website in my application with BeoNews-Pro?
 What changes must I make in order for the application to display the content of the website?
I do not want to show the content of the Blog The theme is ready to easily create Cooking Recipes with a Plugin, the blog is to show entries, therefore, the recipes do not show their content.

 Can you help me with this ?

 I already told you, that I am willing to buy another of your themes with which I can display the content of my website, and not the content of the blog.
Just tell me with which of your themes I can display the content of my WordPress site, and I'll buy it today.

I do not ask that you give me another of your songs, I will buy and pay today.
This way I will have two projects to work on.
  With BeoNews-Pro I will create another application, for example news.

I hope you understand my needs, I'm just trying to create a Cooking Recipes app, and I have my WordPress site with lots of cooking recipes:

 https://recetasdemiyaya.es/

Thank you, I sincerely hope that you can help me.

Thanks for your support.

**Comment by miguelitolaparra** [comment]
Hello again.

Please excuse me for bothering you again @luyx2412 

  I am not sure you have read my message.

Can I correct the error and display the content of my website instead of the content of the blog with BeoNews- Pro?

  If this is not possible, there is no problem, I will use BeoNews-Pro for another project.

I just need you to tell me with which of your React Native products it is possible to get my project to show: recipes, categories, favorites, to be able to register, etc; all the content of my website https://recetasdemiyaya.es.

Tell me what is the indicated of your products, and I will buy it right now.
  I have almost finished my WordPress site and I am looking forward to creating the application.

  I just need to create the kitchen recipe app to show it to future customers of other apps


  Thank you, please excuse my insistence, I see that your team has a lot of work helping other users.

a greeting

**Comment by luyx2412** [comment]
HI @miguelitolaparra Can i know the recipes, categories, favorites which is categories or what is it? If it is the categories, you can show it with beonews pro.

Thanks

**Comment by miguelitolaparra** [comment]
Thanks for answering.

I need to show the content of my website, currently the application only shows the content of my Blog.

 With blog posts I can't show Recipes from my site, only posts are shown.

<img width="1476" alt="blogPosts" src="https://user-images.githubusercontent.com/28591454/88682716-487cf300-d0f3-11ea-9ed8-acda7a229d6c.png">


<img width="1476" alt="blogCategorys" src="https://user-images.githubusercontent.com/28591454/88682816-68acb200-d0f3-11ea-9153-c6fd0535b7a0.png">




I already have the recipes created on my site, you can see it https://recetasdemiyaya.es/todas-recetas/

And I have the categories of each recipe, you can see it https://recetasdemiyaya.es/categorias/

 Why does the application show the structure of the Blog? https://recetasdemiyaya.es/noticias/ ?

<img width="1476" alt="blogPosts" src="https://user-images.githubusercontent.com/28591454/88682902-811ccc80-d0f3-11ea-8022-524497f5dc23.png">


 How can I correct this?
 Initially, the application should display the content of the website.

 Can you help me correct this?

This is the content of my site, what the application should show:
You have access to the WP panel, you can see what I want to tell you



<img width="1476" alt="MTwebsite" src="https://user-images.githubusercontent.com/28591454/88683136-c8a35880-d0f3-11ea-8fe4-2616d8d3e82f.png">




<img width="1476" alt="webSiteCategorys" src="https://user-images.githubusercontent.com/28591454/88683177-d0fb9380-d0f3-11ea-9885-7f7d458fb086.png">

 I need to create this application to get another job, I must create an app for a store created with Prestashop, but I need to show the client what I am capable of building

 I hope you can help me, if I should not look for another RN topic to continue.

 BeoNews-Pro only shows the content of the posts section, which is the blog of the website

Thank you

**Comment by miguelitolaparra** [comment]
<img width="449" alt="appCategories" src="https://user-images.githubusercontent.com/28591454/88693434-90a21280-d0ff-11ea-9cb4-06039535c6f7.png">


This is what the application shows, it does not show nor the images that I have assigned to the categories of The Tickets.

I can't find a way to display my website.

  Does it have something to do with my WordPress settings?

Can I buy another theme that shows my website and all its content?

I can't find a way to get it with BeoNews, you can see my WP site, you can tell me if I have the wrong configuration check

**Comment by miguelitolaparra** [comment]
Good afternoon friend @luyx2412 

  Since I see that you are very busy, I don't want to bother you any more. Seeing that this cannot be solved and they have no other topic that I can buy to show the content of my site, I have been searching the market for other products.
  When I start working with BeoNews on another project, I am sure I have to ask for your help for any problem.

  Greetings, I wish you a happy day

**Comment by luyx2412** [comment]
Hi @miguelitolaparra Thanks for your clearly. Currently we just support Categories and did not another case Receipts,... . And i just checked the category image, but your website showed the issue. So can you check it.
![image](https://user-images.githubusercontent.com/8909619/89094484-a90b7900-d3ee-11ea-8d76-39465f9227ca.png)

Thanks

**Comment by miguelitolaparra** [comment]
Hi. @luyx2412 

The error displayed by my website is because I have modified it and made an error uploading a backup.

  In 2 hours it will be working again.

I am going to work with another React Native theme that I have bought, since I did not receive news from you giving me any idea, and with BeoNews I do not get my needs.

It is sad because when I asked before buying the item, you told me that if I could create a Food Recipes application.
   But there is no problem, I will use BeoNews-Pro for another project that I can think of later.
I must first create the Food Recipes application.
If you have no intention of helping me, you can close this support, when I start working with BeoNews-Pro again, if I need support I will open a new query.

Thank you, I wish you a happy day

**Comment by minhcasi** [comment]
@miguelitolaparra - sorry for the confusion about the food recipes - it is possible to make the Beonews app as the food receipt as we also use it for the demo app http://news.inspireui.com 

But if you would add more feature for recipes like showing the menu, recipes detail then it could require some customization :)

Let us know if you need any question 👍
