### ISSUE TITLE
Product variation in 0 main variation

### ISSUE THREAD

**Issue by juancamilocanal** [inspireui/support#4223]
Please refer to this ticket and reopen: https://github.com/inspireui/support/issues/3598

The issue still persists after upgrading to the latest code.

**Comment by ameenbadri7** [comment]
could you check if you are set your woocommerce product like these pictures :

<img width="935" alt="1" src="https://user-images.githubusercontent.com/37524186/87614089-c9151a00-c717-11ea-922f-5f9202204365.png">
<img width="951" alt="2" src="https://user-images.githubusercontent.com/37524186/87614106-cdd9ce00-c717-11ea-8187-48f50760c570.png">
<img width="954" alt="3" src="https://user-images.githubusercontent.com/37524186/87614110-cfa39180-c717-11ea-8189-9f2cd062affe.png">
<img width="947" alt="4" src="https://user-images.githubusercontent.com/37524186/87614112-d0d4be80-c717-11ea-99bd-2c179f894d23.png">

please check it and try again ...

**Comment by minhcasi** [comment]
@juancamilocanal - please try to use this pre-config site to help with the config or use for reference - https://docs.inspireui.com/fluxstore/woocommerce-setup/#1-website-integration

Please note that we may not support answering or support technical issues for the regular license as per support policies - https://inspireui.com/support-policies/ - but we are trying to best to give extra miles with the supporting.

**Comment by juancamilocanal** [comment]
How can I change the regular license for the extended license?

**Comment by minhcasi** [comment]
@juancamilocanal - there is the option to make the order on Envato (then after purchase you could process the refund for current Regular license)

<img width="756" alt="Screen Shot 2020-07-16 at 13 51 34" src="https://user-images.githubusercontent.com/1459805/87636801-79603e00-c76b-11ea-97cb-0fd8fd14ce59.png">

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
