### ISSUE TITLE
Apps change profile image

### ISSUE THREAD

**Issue by devienguilde** [inspireui/support#4224]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
1.How to change profile picture from apps for user and vendor?,
2. How do i change color skin like on settings menu base green color?

+ Product & version: MVstore & 1.5 
+ Flutter (or React Native) version: Lastest
+ Testing Device/Simulator: Samsung S10+
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@devienguilde - sorry this feature is not available from current fluxstore release, it could only use the default profile picture load from Wordpress side - thank you!
