### ISSUE TITLE
search not work

### ISSUE THREAD

**Issue by mohamedibrahim89** [inspireui/support#4225]
I finish my app everything is OK but suddenly search not work in app  I don't know why load without finish

![WhatsApp Image 2020-07-16 at 10 25 18 AM](https://user-images.githubusercontent.com/35544603/87646553-49a33d00-c74f-11ea-92b0-4fc02e802cfc.jpeg)

**Comment by FaizalAndro** [comment]
Hi @mohamedibrahim89 , Go to In lib/models/filer_attribute.dart change this code : https://tppr.me/h3VbK

**Comment by mohamedibrahim89** [comment]
very thxxx from where also can I change the white space above my banner color
the battery and clock area color
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-07-17 at 17 08 22](https://user-images.githubusercontent.com/35544603/87802141-0af5ab80-c851-11ea-8fd7-6621d47f45e8.png)

**Comment by ameenbadri7** [comment]
to change your app status bar color you can go to `lib\main.dart ` file and edit the code from this : 

```
 if (!kIsWeb) {
    await SystemChrome.setPreferredOrientations(
        [DeviceOrientation.portraitUp, DeviceOrientation.portraitDown]);

    SystemChrome.setSystemUIOverlayStyle(
      SystemUiOverlayStyle.dark.copyWith(statusBarColor: Colors.transparent),
    );
    }
```
to  be like this : 

```
if (!kIsWeb) {
    await SystemChrome.setPreferredOrientations(
        [DeviceOrientation.portraitUp, DeviceOrientation.portraitDown]);

    SystemChrome.setSystemUIOverlayStyle(
      SystemUiOverlayStyle.dark.copyWith(statusBarColor: Colors.transparent),
    );
    SystemChrome.setSystemUIOverlayStyle(
      SystemUiOverlayStyle.light.copyWith(statusBarColor: Colors.blue),
    );
  }
```

For the light theme, we add `SystemUiOverlayStyle.light.copyWith(statusBarColor: Colors.blue),` so it be our `blue `color.
You can change the blue to be any color you want.

You can also change the dark theme  `statusBarColor ` but keep it `Colors.transparent`  so you wont break the dark theme rules.

you could help us by giving your feedback/rating to [Codecanyon Market website](https://codecanyon.net/downloads), 
we are working hard to update more awesome and powerful features on the next coming version release. 
Let us know if you have any feedback. 

Thank you very much ❤️

**Comment by minhcasi** [comment]
Please note that we will not support answering or support technical issues for the regular license as per support policies - https://inspireui.com/support-policies/ - but we are trying to best to give extra miles with the supporting. 

Please help to upgrade the Extended License if you would like to request technical support from us - thank you for your time!

Hope you enjoy the product and stay safe 😊
