### ISSUE TITLE
HTTP Categories Loading But HTTPS its's not

### ISSUE THREAD

**Issue by swapnildesai5** [inspireui/support#4226]
I have set up the project and installed and enabled all the plugins and followed all the tutorials from :

https://docs.inspireui.com/fluxstore/multi-vendor/

!
![3](https://user-images.githubusercontent.com/37268415/87656353-0c947600-c762-11ea-910f-98bc3ce1af92.JPG)
![6](https://user-images.githubusercontent.com/37268415/87656371-11f1c080-c762-11ea-93ca-a184623bdac9.JPG)
![5](https://user-images.githubusercontent.com/37268415/87656376-1322ed80-c762-11ea-8ffd-4de3d6f6cd64.JPG)

[2](https://user-images.githubusercontent.com/37268415/87656324-03a3a480-c762-11ea-9fa0-0bfc3d31f446.JPG)

**Comment by swapnildesai5** [comment]
Products are not loading at all

**Comment by minhcasi** [comment]
@swapnildesai5 - did you active the mstore-api from Wordpress side?

**Comment by swapnildesai5** [comment]
![7](https://user-images.githubusercontent.com/37268415/87767121-d7039180-c822-11ea-8109-4ac97acbf048.JPG)


Plugin also enabled

**Comment by minhcasi** [comment]
@vumanhsn97 - pls help to suggest on this issue - thank you!

**Comment by vumanhsn97** [comment]
@swapnildesai5 
Your category id is incorrect. Please set other id or try with fluxbuilder https://tppr.me/cpSbq

**Comment by swapnildesai5** [comment]
Hey yes thats true but in the app if you want to load products by using category the peoducts are not loading eg if you click on category "Electronics" it shows no products found in the app

**Comment by swapnildesai5** [comment]
![Screenshot_20200720-124951](https://user-images.githubusercontent.com/37268415/87924567-bdaf4f00-ca87-11ea-9a2c-526bad55059b.jpg)
![Screenshot_20200720-124945](https://user-images.githubusercontent.com/37268415/87924574-bee07c00-ca87-11ea-8f28-6d402068d7fc.jpg)

**Comment by swapnildesai5** [comment]
it loads in flux builder but not in the app

**Comment by vumanhsn97** [comment]
@swapnildesai5 
It is working well: https://streamable.com/tuwev2

**Comment by swapnildesai5** [comment]
Check this video the category appliance loads but not other categories

https://streamable.com/onth2a

**Comment by swapnildesai5** [comment]
SOLVED The issue was assigning Products to a shop 

If you have such an issue assign all products to a store in Multivendor application
