### ISSUE TITLE
Xcode Build Error Firebase.h

### ISSUE THREAD

**Issue by macquack** [inspireui/support#4227]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
i can't build from xcode to device (on simulator work fine) it's said about Firebase.h missing 
i already try to change app name & bundleid via info.plist  but nothing change

+ Product & version:1.7.4
+ Flutter (or React Native) version: 1.17.1
+ Testing Device/Simulator: iPhone 7
+ Screenshot issues (drag the file to attach here): 
![image](https://user-images.githubusercontent.com/30103694/87658676-b980ea00-c786-11ea-8070-91c2431d7dc4.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**
my previous issue #4157 

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@macquack - try to clean up the cache and update cocopod to latest version - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

**Comment by macquack** [comment]
i already fixed it's my fault opening the .xcworkspace file instead of the .xcodeproj file. now it's work fine

**Comment by macquack** [comment]
but i have some problem on ipad version the product page not show image
![image](https://user-images.githubusercontent.com/30103694/87749955-4c239680-c824-11ea-89f5-251e7704039f.png)
![image](https://user-images.githubusercontent.com/30103694/87749968-56459500-c824-11ea-8758-f35bdb07e66b.png)

**Comment by minhcasi** [comment]
You could try to debug this file to see why the image is missing on your site

<img width="1129" alt="Screen Shot 2020-07-17 at 16 58 11" src="https://user-images.githubusercontent.com/1459805/87774630-003a1700-c84f-11ea-9530-92d6e49b8264.png">

**Comment by macquack** [comment]
this is my product_title.dart (flux store version 1.7.4) not contain code like you

import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:quiver/strings.dart';

import '../../common/config.dart';
import '../../common/tools.dart';
import '../../generated/l10n.dart';
import '../../models/app.dart';
import '../../models/product/product.dart';
import '../../models/product/product_model.dart';
import '../../models/product/product_variation.dart';
import '../../widgets/common/start_rating.dart';

class ProductTitle extends StatefulWidget {
  final Product product;

  ProductTitle(this.product);

  @override
  _ProductTitleState createState() => _ProductTitleState();
}

class _ProductTitleState extends State<ProductTitle> {
  @override
  Widget build(BuildContext context) {
    final ThemeData theme = Theme.of(context);
    ProductVariation productVariation;
    productVariation = Provider.of<ProductModel>(context).productVariation;
    final currency = Provider.of<AppModel>(context).currency;

    final regularPrice = productVariation != null
        ? productVariation.regularPrice
        : widget.product.regularPrice;
    final onSale = productVariation != null
        ? productVariation.onSale
        : widget.product.onSale;
    final price = productVariation != null
        ? productVariation.price
        : isNotBlank(widget.product.price)
            ? widget.product.price
            : widget.product.regularPrice;
    int sale = 100;
    if (regularPrice.isNotEmpty && double.parse(regularPrice) > 0) {
      sale = (100 - (double.parse(price) / double.parse(regularPrice)) * 100)
          .toInt();
    }

    return Column(
      mainAxisAlignment: MainAxisAlignment.start,
      children: <Widget>[
        SizedBox(height: 10),
        Container(
          width: MediaQuery.of(context).size.width,
          child: Text(
            widget.product.name,
            style: TextStyle(fontSize: 18, fontWeight: FontWeight.w600),
          ),
        ),
        SizedBox(height: 10),
        Row(
          children: <Widget>[
            Text(
              widget.product.type != 'grouped'
                  ? Tools.getCurrecyFormatted(price, currency: currency)
                  : Provider.of<ProductModel>(context).detailPriceRange,
              style: Theme.of(context).textTheme.subtitle1.copyWith(
                    fontSize: 17,
                    fontWeight: FontWeight.w400,
                    color: theme.accentColor,
                  ),
            ),
            if (onSale && widget.product.type != 'grouped')
              Row(
                crossAxisAlignment: CrossAxisAlignment.end,
                children: <Widget>[
                  SizedBox(width: 5),
                  Text(
                      Tools.getCurrecyFormatted(regularPrice,
                          currency: currency),
                      style: Theme.of(context).textTheme.subtitle1.copyWith(
                          fontSize: 14,
                          color: Theme.of(context).accentColor.withOpacity(0.6),
                          fontWeight: FontWeight.w400,
                          decoration: TextDecoration.lineThrough)),
                  SizedBox(width: 5),
                  Container(
                    padding:
                        const EdgeInsets.symmetric(horizontal: 5, vertical: 2),
                    decoration: BoxDecoration(
                        color: Colors.red,
                        borderRadius: BorderRadius.circular(5)),
                    child: Text(
                      S.of(context).sale('$sale'),
                      style: TextStyle(
                          color: Colors.white,
                          fontWeight: FontWeight.w400,
                          fontSize: 14),
                    ),
                  )
                ],
              )
          ],
        ),
        if (kAdvanceConfig['EnableRating'])
          Padding(
            padding: const EdgeInsets.symmetric(vertical: 10.0),
            child: SmoothStarRating(
              allowHalfRating: true,
              starCount: 5,
              spacing: 0.0,
              rating: widget.product.averageRating,
              size: 17.0,
              color: theme.primaryColor,
              borderColor: theme.primaryColor,
              label: Text(
                " (${widget.product.ratingCount})",
                style: Theme.of(context).textTheme.subtitle1.copyWith(
                      fontSize: 12,
                      color: Theme.of(context).accentColor.withOpacity(0.8),
                    ),
              ),
            ),
          ),
      ],
    );
  }
}

**Comment by macquack** [comment]
after I try if I upload galley image it will show fine 
it's possile just show product image 
![Screen Shot 2563-07-18 at 10 26 59](https://user-images.githubusercontent.com/30103694/87843762-4344ca80-c8e1-11ea-9709-4f19635b826e.png)

**Comment by minhcasi** [comment]
Hi, do you mean the feature product image? Could you share the screenshot of the detail product setting from Woocommerce?

**Comment by macquack** [comment]
like this?
![image](https://user-images.githubusercontent.com/30103694/87846252-b443ac80-c8f8-11ea-96df-56e0e285cf68.png)

**Comment by minhcasi** [comment]
<img width="1174" alt="Screen Shot 2020-07-20 at 19 30 54" src="https://user-images.githubusercontent.com/1459805/87937773-89578500-cabf-11ea-9817-9ee57fd92191.png">

@macquack - this is the default setting from our demo app, it is set up as features and gallery but still working fine, could you try to add more images to see if that is the root cause. 

I suspect if does not show on iPad because only the product has only one Feature Image?

**Comment by macquack** [comment]
yes if i added other image on galley section it's work fine

but most of my products has only 1 image it's possible to fixing?

**Comment by minhcasi** [comment]
@macquack - i'm checking your config and can see all the product is displaying well - did you fix the wordpress site?

![Simulator Screen Shot - iPhone 11 Pro - 2020-07-23 at 11 27 59](https://user-images.githubusercontent.com/1459805/88252238-9e0e6580-ccd7-11ea-8133-a257bb8790c2.png)

**Comment by macquack** [comment]
yes everything work fine only one problem that i got is Product view on iPad not show ant image. it will show when the product contain feature product image and gallery image. and not show any image if only feature image. and most of all product on my site about 500 item only have product feature image

This is when only have Product Feature Image
![image](https://user-images.githubusercontent.com/30103694/88370798-f3707280-cdbc-11ea-8808-e18c304d2e61.png)

This is when Product Feature Image and Galley image 
![image](https://user-images.githubusercontent.com/30103694/88370778-ea7fa100-cdbc-11ea-96ec-383d014869e6.png)

so the question is it's possible that i can show product feature image on ipad view

**Comment by minhcasi** [comment]
@macquack - you could try to move back the top feature image by customizing this file, remove the `kLayoutWeb` condition :)

<img width="1222" alt="Screen Shot 2020-07-25 at 13 35 54" src="https://user-images.githubusercontent.com/1459805/88450791-c767f680-ce7b-11ea-9d5d-74186862f401.png">

**Comment by macquack** [comment]
finally i got this by just edit ur common config on "source/lib/common/config/products.dart" changed 
`"showThumbnailAtLeast": 1,`
(default is 3)
![image](https://user-images.githubusercontent.com/30103694/88454046-b5e01800-ce96-11ea-8ab4-4ebd858c0ce3.png)

very appreciate for u always helpful i love this Project and u guy Dev Team

**Comment by minhcasi** [comment]
We're glad that it help, please give us some feedback/rating to this page https://codecanyon.net/downloads  if the product is helpful for your business, we are working hard to update more awesome and powerful features on next coming version release. Let us know if you have any feedback. Thank you very much 😊
