### ISSUE TITLE
When you guys are updating Fluxstore Multivendor for android R issue

### ISSUE THREAD

**Issue by GNAG1993** [inspireui/support#4228]
fluxstore Multivendor is also having the android R issue. Earlier you guys told that you guys are updating within 1-2 Days. But still its not updated.
When you guys gonna update.

**Comment by FaizalAndro** [comment]
@GNAG1993 Got to android folder then build.gradle
paste this code

subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"

    project.evaluationDependsOn(':app')

    afterEvaluate {project ->
        if (project.hasProperty("android") && project.property("android").compileSdkVersion.equals("android-R")) {
            android {
                compileSdkVersion 30
            }
        }
    }
}

**Comment by minhcasi** [comment]
@GNAG1993 - we will update new release in 1-2 days - thanks

**Comment by GNAG1993** [comment]
its been almost a week since you guys said for update for the error in 1-2 days. Now its been almost a week.

**Comment by minhcasi** [comment]
@GNAG1993 - there are some minors fix we would like to include this release so that it is delayed a few days - you could also use latest release on gitlab - thank you for your patience

**Comment by minhcasi** [comment]
@GNAG1993 - pls use the latest release on Gitlab ❤️
