### ISSUE TITLE
bitcode error fluxstore woocommerce

### ISSUE THREAD

**Issue by vverbovenko91** [inspireui/support#4229]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
Hello. Please help with error - when archive ios app, write bitcode error
+ Product & version: fluxstore woocommerce 1.7.5
+ Flutter (or React Native) version: Flutter
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

![Снимок экрана 2020-07-16 в 16 11 57](https://user-images.githubusercontent.com/6977576/87664688-1e384680-c77f-11ea-99bd-499fbd9a1085.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by realmultimedia** [comment]
Run this first 
<img width="1440" alt="Screenshot 2020-07-16 at 12 41 00" src="https://user-images.githubusercontent.com/68022923/87667059-a0b20d80-c761-11ea-884f-a1d1f92c31fc.png">
Then go to Xcode - Product - Archive

**Comment by vverbovenko91** [comment]
Where is in Visual Studio Code?

**Comment by realmultimedia** [comment]
terminal: flutter build ios

**Comment by vverbovenko91** [comment]
Thanks, that works
