### ISSUE TITLE
[MStore Pro] issue with android & IOS in v 3.7.1 

### ISSUE THREAD

**Issue by yosefasad** [inspireui/support#423]
Hello

I have a fresh installation for MAC OS, 
 I run the default setting for MStore 3.7.1 , no code modified . 

Please check the error for IOS and Android  here https://imgur.com/a/FW5ciWk

I have problem with IOS

 Failed to load bundle(http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false) with error:(Could not connect to development server.

Ensure the following:
- Node server is running and available on the same network - run 'npm start' from react-native root
- Node server URL is correctly set in AppDelegate
- WiFi is enabled and connected to the same network as the Node Server

for the Android I have the following error  on the Emulator

The development server returned response error code: 500
URL: http://10.0.2.2:8081/index.delta?platform=android&dev=true&minify=false

also got this message on the terminal 
oading dependency graph, done.

error: bundling failed: SyntaxError: /Users/yosefasad/Desktop/mstore-3.7.1/mstore-pro/node_modules/react-native/src/components/HorizonList/index.js: Identifier 'layouts' has already been declared (23:6)

Please check the error here https://imgur.com/a/FW5ciWk

Thanx

**Comment by minhcasi** [comment]
@yosefasad please try to override the common/Tools.js by this file https://www.dropbox.com/s/l5vav9l0t9l98s3/Tools.js?dl=0 - let us know your checking - thank you!

**Comment by yosefasad** [comment]
I override the file , and same error happened again

Thanks

**Comment by netappzone** [comment]
I am having exactly the same problem, please help expedite solution

**Comment by minhcasi** [comment]
@yosefasad @netappzone appreciated for reporting this issue, we have just updated the 3.7.2 for updating this issues, it about missing file when we create the build package - components/HorizonList/index.js
