### ISSUE TITLE
fluxbuilder + prestashop = api not connected

### ISSUE THREAD

**Issue by realmultimedia** [inspireui/support#4230]
Hi,

Downloaded the latest (1.7.4) prestashop version - changed the parameters inside /lib/common/config.dart - simulator app doesn't load the categories.
I have also tried both http:// and https:// for the webservice connection. 
Fluxbuilder - rest api not connected. (I have already confirmed the purchase and sent you screenshots)

Please advise

**Comment by minhcasi** [comment]
@realmultimedia - could you resend the PDF license for fluxstore prestashop to http://verify.inspireui.com/ - thank you!

**Comment by realmultimedia** [comment]
any info?

**Comment by minhcasi** [comment]
We got your feedback, it's disappointing when dealing with the way that someone is helping you, we don't mind processing the refund your purchase products to save your time.

**Comment by realmultimedia** [comment]
If you can’t handle honest reviews, close your business. In addition, do not release incomplete versions as I and many other are losing previous time with debugging your apps. I reported you to envato as your behaviour is unacceptable. Grow up and take responsibilities
