### ISSUE TITLE
MStore license 

### ISSUE THREAD

**Issue by ashraf-95** [inspireui/support#4231]
Dear support 
I would like to thank you for the amazing Item. and I want to ask you I just facing a problem that I have a website with domain:
http://coomamall.com
and I linked my license with it
after that my server SiteGround advice me to change my domain to:
https://www.coomamall.com
just by adding www and https with the same website
after that MStore plugin ask me for purchase code now when I want to add my purchase code it tells me that this code is being used by:
http://coomamall.com
screenshot: https://snipboard.io/m09fSE.jpg 
so how can I delete the code from the old domain to the new one?

Product and version: MStore Multi Vendor - Complete React Native template for WooCommerce v.1.3

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 

Thank you for your time!

**Comment by minhcasi** [comment]
@ashraf-95 - we have reseted the license, pls help to check again - this could be a bug from verify API - we will also check from our side as well - thank you!

**Comment by ashraf-95** [comment]
My issue is resolved now. Thank you!

**Comment by ashraf-95** [comment]
Hi there,
I have Electro theme and i need to edit (src) files to fix this issue (No route was found matching the URL and request method), Where i can upload mstore-mv-expo file?
Also I was following instruction as page here:
https://docs.inspireui.com/mstore-mv/getting-starte , But from where to get secret key of JWT Authentication or it's automatic generating?
Regards

**Comment by minhcasi** [comment]
@ashraf-95 - pls check this guide https://wordpress.org/plugins/jwt-auth/

**Comment by ashraf-95** [comment]
Hi there,
Thank you for your response, What about (src) files? Where can I upload (mstore-mv-expo)?

Regards

**Comment by minhcasi** [comment]
After building the final apk, you could upload to Google Play store

**Comment by minhcasi** [comment]
let us know if you have any further question - thank you!

**Comment by ashraf-95** [comment]
Hello there, 
I still facing this error "No route was found matching the URL and request method" when I want to log in or sign in as you can see in this screenshot 
 https://snipboard.io/cNHugQ.jpg 
can you help me to fix that, please
