### ISSUE TITLE
Adding and Editing Products using Phone as device

### ISSUE THREAD

**Issue by Benhur3000** [inspireui/support#4232]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
1) Getting message on side of screen saying overflow by 1.6 pixels. This on when I'm on the add a product screen using my phone as the device.  
![Screenshot_20200716-120809](https://user-images.githubusercontent.com/67126788/87710219-b1af4e80-c762-11ea-84bf-d589784c4830.jpg)

2) When I add a product I get stuck on the loading screen with message "waiting for product to post" along those lines. This again is when I use my phone as a device instead of using the emulators or fluxbuilder. 
![Screenshot_20200716-121252](https://user-images.githubusercontent.com/67126788/87710214-af4cf480-c762-11ea-94dc-10eebc42dfcc.jpg)

3) I can't find any options to EDIT an existing product. I can view products when I got to "my products" but no where does it show an option to EDIT/DELETE.

4) Will you be adding option for attributes and Inventory section from WCFM? See image "attributes" and "inventory" attached.
![Attributes](https://user-images.githubusercontent.com/67126788/87710118-93e1e980-c762-11ea-878c-b8f5a6e75866.PNG)
![Inventory](https://user-images.githubusercontent.com/67126788/87710127-96444380-c762-11ea-93dd-d4b5c59e29e3.PNG)

5) On my website products are optional for showing the add to cart using the "Catalog" mode. However they all show add to cart on the app. How can I make it so catalog items with the cart hidden reflect on the app? likewise when adding a product on the app how can I add this feature. 
![Catalog Mode](https://user-images.githubusercontent.com/67126788/87710704-516cdc80-c763-11ea-84c1-f1363e35addf.PNG)
![Catalog mode options](https://user-images.githubusercontent.com/67126788/87710709-5336a000-c763-11ea-82b7-6e2a5b5a3419.PNG)

+ Product & version: Fluxstore MV 1.7.6
+ Flutter (or React Native) version: Flutter 1.17.5
+ Testing Device/Simulator: Android Samsung galaxy s10+ and Android studio Emulator 
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by Benhur3000** [comment]
6) My apologies one last thing related to adding a product through the app...the category drop down shows all categories including sub categories. This makes it a long list to scroll through. Is there a way to make the sub menus only show when clicking on the parent category? see image for example. Basically make them nested,
![Parent category](https://user-images.githubusercontent.com/67126788/87711149-1dde8200-c764-11ea-8609-11220e38ae7c.png)
![sub categories](https://user-images.githubusercontent.com/67126788/87711153-1fa84580-c764-11ea-954b-5a0186c31060.png)

**Comment by minhcasi** [comment]
@Benhur3000 - Create a new product from Fluxstore only support for some basic feature, it does not support the product variant. We will upgrade the new feature to support Edit/Delete Vendor products on next release - thank you!

**Comment by Benhur3000** [comment]
Thank you. Any idea about questions number 1,2, 5, and 6?

**Comment by minhcasi** [comment]
@Benhur3000 - We sincerely apologize for the delay and hope you’re staying safe.

1. we will fix on next release

2. please help to check if you have enable the JWT plugin, it is supported to create new product

5. This catalog option is not available and requires to customize the model to hide the Cart option

6. The app supports different type of categories, please give a try with the config via Fluxbuilder

**Comment by Benhur3000** [comment]
1.  Thank you
2. The JWT plugin you say to use has not been updated in a year and is untested with my version of php - https://wordpress.org/plugins/jwt-authentication-for-wp-rest-api/
5. Is this customization you can do for cost? or do I have to find a developer? Unless you have some documentation how to add this as optional for vendors.
6. Hi I'm not sure you understood. I want the category drop down menu to be nested when adding a product because I have a LOT of categories. So example is the parent category is "Appliances" and the child category is "blender" so when I click on the category drop down when adding a product I should only see "Appliances" then maybe a plus icon or arrow icon and if I click it then you will see "Blender". Makes sense?

**Comment by minhcasi** [comment]
Please help to give your all comment to the same open ticket #4284 

Please note that we will not support answering or support technical issues for the regular license as per support policies - https://inspireui.com/support-policies/ - but we are trying to best to give extra miles with the supporting.
