### ISSUE TITLE
see_all not showing data in opencart

### ISSUE THREAD

**Issue by codex-pro** [inspireui/support#4233]
![Screenshot 2020-07-17 at 1 08 34 AM](https://user-images.githubusercontent.com/51110842/87714856-09cd6b80-c7ca-11ea-8528-2b2599cfb199.png)
this see all is empty 
Note : i have updated to latest version of opencart fluxtore and flutter . 
kindly provide solution

**Comment by minhcasi** [comment]
@codex-pro - could i confirm if you are using latest release `1.7.6` - thank you!

**Comment by codex-pro** [comment]
> @codex-pro - could i confirm if you are using latest release `1.7.6` - thank you!

yes it's updated to latest 1.7.6

**Comment by codex-pro** [comment]
hi please reply

**Comment by minhcasi** [comment]
@minhtruong315 - pls help to check this opencart issue

**Comment by codex-pro** [comment]
how ?

**Comment by codex-pro** [comment]
???? reply man very bad support

**Comment by minhtruong315** [comment]
Hi @codex-pro 
Can you fork from our git repo then invite me: minhtruong315@gmail.com?
 https://medium.com/@inspireui/how-to-upgrade-fluxstore-projects-by-using-git-cebde7489ea6
 I will help you check your issues. Ping me when you shared. 
Thanks

**Comment by codex-pro** [comment]
i dont know how to fork

**Comment by codex-pro** [comment]
hey kindly resolve see all issue

**Comment by codex-pro** [comment]
from 5 days i have not recieved any conceret solution

**Comment by codex-pro** [comment]
![Screenshot 2020-07-22 at 9 48 10 AM](https://user-images.githubusercontent.com/51110842/88133761-74ced600-cc00-11ea-96b7-65e70a04c413.png)
![Screenshot 2020-07-22 at 9 48 22 AM](https://user-images.githubusercontent.com/51110842/88133767-7b5d4d80-cc00-11ea-9892-60589b145950.png)

**Comment by minhcasi** [comment]
@codex-pro - we understand that could be the issues and we are willing to help on this open ticket. Could you help to update our rating as its impact on our business, I will update the ticket as a high priority and assigning to our technical lead for investigating.

it is possible to process the refund if you are not satisfied with our product so far - hope you could understand the problem under pandemic time. Thank you for your help!

**Comment by codex-pro** [comment]
no sir i do not want refund i have project delivery i ll loose my job please understand .

**Comment by minhcasi** [comment]
@codex-pro - thank you for a quick response.

@minhtruong315 - please help to investigate this issue

**Comment by minhtruong315** [comment]
@codex-pro I will check on our source code and let you know.
Thanks

**Comment by minhtruong315** [comment]
Hi @codex-pro please reinstall mstore extension in your website then try again
[mstore.ocmod.zip](https://github.com/inspireui/support/files/4959111/mstore.ocmod.zip)

**Comment by codex-pro** [comment]
hi i did that it's still not working.

**Comment by minhtruong315** [comment]
can u record screen? and send me full your source code via email: minhtruong315@gmail.com
I will check it

**Comment by codex-pro** [comment]
ok yes

**Comment by minhtruong315** [comment]
@codex-pro ping me when you sent.
Thanks

**Comment by codex-pro** [comment]
i hv mailed u

**Comment by codex-pro** [comment]
issue : 4 shipping rate changing on own even its set to default 50 /-
![Screenshot_2020-07-23-17-41-34-229_com inspireui fluxstore](https://user-images.githubusercontent.com/51110842/88285139-39b9c900-cd0c-11ea-9bc9-0ca8f7e614db.jpg)
![Screenshot_2020-07-23-17-41-37-565_com inspireui fluxstore](https://user-images.githubusercontent.com/51110842/88285147-3d4d5000-cd0c-11ea-8035-876d719e63ca.jpg)
![Screenshot_2020-07-23-17-41-47-439_com inspireui fluxstore](https://user-images.githubusercontent.com/51110842/88285150-3de5e680-cd0c-11ea-8062-337a5d3b11dd.jpg)
![Screenshot_2020-07-23-17-42-04-744_com inspireui fluxstore](https://user-images.githubusercontent.com/51110842/88285155-3e7e7d00-cd0c-11ea-8bf8-ac47171dc393.jpg)

**Comment by premod** [comment]
Can you please contact me on aquastore.in@gmail.com. i need to consult about this

**Comment by minhtruong315** [comment]
@codex-pro Can u send me admin account and full your source code via email: minhtruong315@gmail.com?

**Comment by codex-pro** [comment]
@minhtruong315  i. have mailed u video . login details cpanel details Please check asap

**Comment by codex-pro** [comment]
??????????????????????????????????????????????????????? any update?

**Comment by codex-pro** [comment]
> Can you please contact me on [aquastore.in@gmail.com](mailto:aquastore.in@gmail.com). i need to consult about this

do not purchase it's full with bug no one reply

**Comment by codex-pro** [comment]
issue 2 resolved 
issue three 
![shipping](https://user-images.githubusercontent.com/51110842/88477597-18045000-cf5f-11ea-9fbf-b508852e0488.png)

**Comment by minhtruong315** [comment]
@codex-pro I checked Fluxstore version 1.7.6 with your website. it's showing products when click "See All".
https://www.dropbox.com/s/nfqobevoa77ce4o/see_all.mov?dl=0

**Comment by premod** [comment]
> > Can you please contact me on [aquastore.in@gmail.com](mailto:aquastore.in@gmail.com). i need to consult about this
> 
> do not purchase it's full with bug no one reply

i knew, i have purchased this, but i couldn't do this properly, i was stuck on the shipping page. if you found any solution. please let me know.  and i will give you my work.

**Comment by minhcasi** [comment]
@codex-pro - try with the latest version to fix the issue

Let us know your checking, thanks

**Comment by codex-pro** [comment]
yes it is reolved .. but after placing order it's not showing address issue three

**Comment by codex-pro** [comment]
https://gitlab.com/inspireui/fluxstore-pro kindly approve my url srp170516@gmail.com

**Comment by minhtruong315** [comment]
@codex-pro I sent you the invitation.

**Comment by minhtruong315** [comment]
Hi @codex-pro For address issue.
- Update MStore extension on your website
[mstore.ocmod.zip](https://github.com/inspireui/support/files/4992130/mstore.ocmod.zip)
- Replace these files
[Archive.zip](https://github.com/inspireui/support/files/4992134/Archive.zip)

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
