### ISSUE TITLE
having trouble with firbase fluxstore mv 1.7.5 and product display errors

### ISSUE THREAD

**Issue by yasaavaise** [inspireui/support#4234]
hi ,
i have purchased yourfluxstore mv 1.7.5, i am running dokan pro and woocommerce,
i have been through all the issues i have seen here and almost got my app ready but i am dealing with some final issues,
.
issues,
1.i have tried using cached enabled in the app but the products takes time to get updated in the app,
2. product with no vendor gives error to correct that i put a ? in front of store and the issues is resolved but now the products which i have deleted from my site keep showing up with zero price,
3. i tried adding firbase push notifications but it it didnt workout i dont know why but it is not working,
4.how many stores i can add in multi vendor coz its not displaying all the stores,

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 

Thank you for your time!

**Comment by minhcasi** [comment]
@yasaavaise - there are some missing config data that could cause the issues, would you mind to use the pre-config site to prevent these setting issues - https://docs.inspireui.com/fluxstore/multi-vendor/ - thank you!

Please note that we will not support answering or support technical issues for the regular license as per support policies - https://inspireui.com/support-policies/ - but we are trying to best to give extra miles with the supporting. 
Hope you enjoy the product and stay safe 😊

**Comment by yasaavaise** [comment]
i have already gone through all the steps as mentioned in your docs,
my site and the app is both config accordingly,
but still i am not able to use firbase push notification ,
along with the ticket i have attached my common and config file
if you have any doubts you can check it,

**Comment by minhcasi** [comment]
@yasaavaise - could you help to double the guide https://docs.inspireui.com/fluxstore/firebase/ - there is detail video guide to help to setup the push notification - thank you!

**Comment by minhcasi** [comment]
Let us know if you have any further question - thank you!

**Comment by yasaavaise** [comment]
hi like you said i have some missing code  ,so I tried a fresh install , so i cleared cache in my website made a fresh API started fresh everything is working fine but I am not getting my products in categories 
here a list of error 
E/OneSignal( 3189): Error updating the user record because of th enull user id
I/flutter ( 3189): [2020-07-22 06:53:25.037697Z][Fluxstore][wocommerce_api][12:23:25.037382] getAsync END [endPoint:products/categories?exclude=311&per_page=100&page=1&lang=en] url:products/categories?exclude=311&per_page=100&page=1&lang=en
I/flutter ( 3189): WooCommerce Error: Invalid signature - provided signature does not match.
pls help is it because of your store API data , I also cleared cache there
