### ISSUE TITLE
Mstore

### ISSUE THREAD

**Issue by edmi14** [inspireui/support#4235]
error when I go to publish the app on the app store :

App Store Connect

Dear Developer,

We identified one or more issues with a recent delivery for your app, "Tutti's Pizza 6.0" 8.0.0 (2). Please correct the following issues, then upload again.

ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).

Best regards,

The App Store Team

**Comment by edmi14** [comment]
I have already verified the information

**Comment by ameenbadri7** [comment]
Hi @edmi14 please follow this article to fix the issue #[3832](https://github.com/inspireui/support/issues/3832)

Thanks

**Comment by edmi14** [comment]
I did what it says # 3832 and it doesn't work

**Comment by ameenbadri7** [comment]
Please provide a log for those errors and also screenshots for your issue. 

Thank you for your patience.

**Comment by edmi14** [comment]
I do everything that #3832 says and however I get the same error:
ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).

**Comment by luyx2412** [comment]
HI @edmi14 Can you share me your package.json and Podfile. Let me investigate about this issue.

Thanks

**Comment by luyx2412** [comment]
Closed ticket because no longer response.

P/S: Feel free to create new ticket issue.
