### ISSUE TITLE
Apple Sign in Error 1 Permission denied 

### ISSUE THREAD

**Issue by eraldix** [inspireui/support#4239]
**_Step 1 (require): describe detail issues & screenshots_**
Trying to add Apple sign in and having the issue down below, also i have added sign in by apple at xcode and firebase with my dev account as seen on the picture down below:
![Simulator Screen Shot - iPhone 11 - 2020-07-16 at 23 37 50](https://user-images.githubusercontent.com/44481659/87777812-724c3500-c82a-11ea-9bbd-02b08973a45a.png)
<img width="1680" alt="Screenshot 2020-07-17 at 12 40 17 PM" src="https://user-images.githubusercontent.com/44481659/87777934-b0e1ef80-c82a-11ea-9c57-3a7feb7f0ab1.png">

+ Detail Issues: 
+ Product & version: Multivendor
+ Flutter (or React Native) version: Latest
+ Testing Device/Simulator: iOS
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by eraldix** [comment]
Facebook and Google sign in work

**Comment by minhcasi** [comment]
@eraldix - pls help to double-check the firebase setting from Firebase - also have a look to our document guide https://docs.inspireui.com/fluxstore/sign-in/

Please note that we will not support answering or support technical issues for the regular license as per support policies - https://inspireui.com/support-policies/ - but we are trying to best to give extra miles with the supporting. 
Please help to upgrade the Extended License if you would like to request technical support from us - thank you for your time!

**Comment by eraldix** [comment]
In what page does the checkout redirect because I'm also getting error 404 on my website when I check out

**Comment by ameenbadri7** [comment]
1. Try to recreate the woocommerce checkout page:
2. Go to Dashboard > WooCommerce > Status
3. Click on Tools tab from the top left area
4. Scroll down to “Create default WooCommerce pages”
5. Click on Create Pages
6. After successfully completing the above steps you will see this message “All missing WooCommerce pages successfully installed.”

Please note that we will not support answering or support technical issues for the regular license as per support policies - https://inspireui.com/support-policies/ - but we are trying to best to give extra miles with the supporting.
