### ISSUE TITLE
Dynamic Pricing is not reflecting in the App

### ISSUE THREAD

**Issue by Relimer-Technologies** [inspireui/support#424]
Mandatory Info (please complete the following information):

Product: [e.g. MStore, ListApp]
M Store Pro
Purchase Code: d98eb201-aba4-4c76-a0a1-cbd67415737d
Your Purchased Code: [get from https://codecanyon.net/downloads]
(we may not reply if you are not our customer)
Describe the issues
Hello,

Good Morning, I have purchased M Store Pro from Envato. I have done all the setup required... I have installed all of the required tools... I am using plugins for features like user role and Dynamic pricing based on Quantity on the Website... I am not able to see the price changes Dynamically reflected in the App.

Kindly help me out with this... Thank You

**Comment by Relimer-Technologies** [comment]
Hello, @minhcasi  I have already registered this issue along with the other feature request in the below link

https://github.com/inspireui/support/issues/420

You provided me with the solution for the addition of more than 10 products feature but didn't provide me solution for this problem... Please help me out for this Dynamic Pricing Issue... Thank You

**Comment by Relimer-Technologies** [comment]
Hello, @minhcasi  If this feature request requires personal customization please let us know the pricing for this feature added in the app... Thank You

**Comment by minhcasi** [comment]
Hi, could you provide more detail screenshot or your web URL so that we could help for checking, as this feature is ready built-in on current version so that we will charge for more fee or customization? 

It could the integration on your website so that we need to check the issues, if possible you can also send your testing admin account to our support email: support@inspireui.com 

Thank you!

**Comment by Relimer-Technologies** [comment]
Hello, @minhcasi I have sent the Login details of WordPress over mail... Kindly reply me with the solution soon... Thank You

**Comment by Relimer-Technologies** [comment]
Hello @minhcasi 

Can I please know what is the updates on dynamic pricing feature?

**Comment by Relimer-Technologies** [comment]
Hello,

Good Morning... I am not using the variation feature for the app... I am using "Dynamic Pricing And Discounts For Woocommerce" plugin... What this plugin does is It will allow us to give different pricing for a product based on the quantity ordered... We need the product to display a certain price when the quantity ordered is below 25 units... Some other price when the quantity ordered is between 25-50 units and a different price for the quantity ordered is above  50 units... For this use case, the "Dynamic Pricing And Discounts For Woocommerce" plugin is working perfectly fine on the website... But it is not getting reflected in the app... Please try to get the solution for this issue as soon as possible... Thank You

**Comment by Relimer-Technologies** [comment]
Hello, @minhcasi 

Good Evening... I am waiting for your reply as it is urgent... kindly reply back soon... Thank You

**Comment by minhcasi** [comment]
@Relimer-Technologies as this is the extra plugin that is not ready support from the WooCommerce API so that i think it will not compatible with the app

**Comment by Relimer-Technologies** [comment]
Hello, @minhcasi 

Good Morning... If the plugin is not compatible with the app... Is any customization possible to support the plugin or to get the feature which I mentioned earlier of different pricing for different quantity ordered... If the customization is possible then what will be the cost for the customization... Please let me know as soon as possible... Thank You

**Comment by Relimer-Technologies** [comment]
Hello, @minhcasi 

Good Afternoon...  I am waiting for your reply as it is urgent... kindly reply back soon... Thank You
