### ISSUE TITLE
Cannot Login Gmail

### ISSUE THREAD

**Issue by harjono-flux** [inspireui/support#4240]
**_Step 1 (require): describe detail issues & screenshots_**

Hello.. I already do this https://stackoverflow.com/questions/58194425/platformexceptionsign-in-failed-com-google-android-gms-common-api-apiexception
but still cannot login with gmail. 
Can you help me?

Now im using 1.7.4 ; i try using 1.7.6 by copy paste "android" folder from 1.7.4 to 1.7.6 but stil same error

![Screen Shot 2020-07-17 at 19 55 02](https://user-images.githubusercontent.com/64935574/87783637-78acd200-c867-11ea-8835-530e3805fc8d.png)
![Screen Shot 2020-07-17 at 19 54 40](https://user-images.githubusercontent.com/64935574/87783640-7ba7c280-c867-11ea-906c-28666a3f064a.png)
<img width="605" alt="Screen Shot 2020-07-17 at 21 18 40" src="https://user-images.githubusercontent.com/64935574/87790870-d9420c00-c873-11ea-808e-e3841a4f5894.png">
<img width="691" alt="Screen Shot 2020-07-17 at 21 17 43" src="https://user-images.githubusercontent.com/64935574/87790878-dcd59300-c873-11ea-812a-4058dfde5e49.png">

**Comment by ameenbadri7** [comment]
Hi, @harjono-flux  welcome back.

After you build the app it has to be connected with an` SHA-1` & `SHA-256 ` but it may be changed to other key files not the old debug or release keys.

The main idea to fix this error is to open all keys you have inside your project and inside the .android folder.

There is a workaround to fix this: 
download[KeyStore Explorer](https://keystore-explorer.org/) this software will open up the android keys you have inside your PC.

If you have Fluxstore as I do then you would have two main places : 

1- `fluxsote\android\app`
you will find two keys `key.jks` and `mstore.jsk`

2- inside your user main folder :

windows `C:\Users\your_user_name\.android`
or mac `/Users/your_user_name/.android`
you will find one key `debug.keystore`

open those keys with the password you entered on the creating
if you forget you could try to use those 
`android` for the default android debug.keystore and  `123456` for the default mstore key.

after you get the ` SHA-1` & `SHA-256 ` replace them with firebase keys and try again with your app, you don't have to rebuild just hot restart it will be enough to try. 

of course, you would have to double-check our [official guide](https://docs.inspireui.com/fluxstore/sign-in/) to extract the keys for firebase installation. 

I hope this would help you to debug your issue.
and lets us know if you still have problems.

**Comment by minhcasi** [comment]
Please note that we will not support answering or support technical issues for the regular license as per support policies - https://inspireui.com/support-policies/ - but we are trying to best to give extra miles with the supporting. 

Please help to upgrade the Extended License if you would like to request further technical support from us - thank you for your time!

**Comment by harjono-flux** [comment]
Hooo nice... agree with this. Is the Extended License , can help us to customize the the program as we need? I mean, i dont know well about programming, if i upgrade to Extented License, there are InspireUI guy can help me to customize the program?


> Please note that we will not support answering or support technical issues for the regular license as per support policies - [https://inspireui.com/support-policies/ -](https://inspireui.com/support-policies/%C2%A0-) but we are trying to best to give extra miles with the supporting.
> 
> Please help to upgrade the Extended License if you would like to request further technical support from us - thank you for your time!

**Comment by harjono-flux** [comment]
> Hi, @harjono-flux welcome back.
> 
> After you build the app it has to be connected with an` SHA-1` & `SHA-256 ` but it may be changed to other key files not the old debug or release keys.
> 
> The main idea to fix this error is to open all keys you have inside your project and inside the .android folder.
> 
> There is a workaround to fix this:
> download[KeyStore Explorer](https://keystore-explorer.org/) this software will open up the android keys you have inside your PC.
> 
> If you have Fluxstore as I do then you would have two main places :
> 
> 1- `fluxsote\android\app`
> you will find two keys `key.jks` and `mstore.jsk`
> 
> 2- inside your user main folder :
> 
> on windows `C:\Users\your_user_name\.android`
> on mac `/Users/your_user_name/.android`
> 
> you will find one key: `debug.keystore`
> 
> Open those keys with the password you entered on the creating
> if you forget you could try to use those
> `android` for the default android debug.keystore and `123456` for the default mstore key.
> 
> After you get the ` SHA-1` & `SHA-256 ` replace them with firebase keys and try again with your app, you don't have to rebuild just hot restart it will be enough to try.
> 
> Of course, you would have to double-check our [official guide](https://docs.inspireui.com/fluxstore/sign-in/) to extract the keys for firebase installation.
> You could also try the solution inside [this.](https://github.com/inspireui/support/issues/3151)
> I hope this would help you to debug your issue.
> and lets us know if you still have problems.

its worksss - thx bro :)

**Comment by minhcasi** [comment]
@harjono-flux - customize the program require more coding knowledge and time which is not include from our support for extended license, you could try to use the Fluxbuilder to support for extra customization, we could help to explain any technical questions during you custom the app :)

**Comment by harjono-flux** [comment]
hooo i see. thx :)
