### ISSUE TITLE
Error while activating the license in FLUX BUILDER

### ISSUE THREAD

**Issue by suri1980** [inspireui/support#4242]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 

Unable to activate the license in FLUX Builder. I've already activated the license in Mstore plugin in my website.

+ Product & version: Flux Builder
+ Flutter (or React Native) version:   1.17.4
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

![fluxbuildererror](https://user-images.githubusercontent.com/1085817/87819844-84b48600-c89f-11ea-93db-25d2371687ab.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@suri1980 - pls make sure to download the latest Fluxbuilder `1.0.6` from the app stores or on this link https://github.com/inspireui/fluxbuilder/releases/tag/v1.0.6 - thank you!

**Comment by minhcasi** [comment]
Let us know if you have any question - thank you!

**Comment by suri1980** [comment]
Hi, Thanks. Its working now..
