### ISSUE TITLE
Refresh loading indicator does not stop spinning

### ISSUE THREAD

**Issue by karmelcorn** [inspireui/support#4243]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: Refresh spinner keeps spinning
+ Product & version: Fluxstore Shopify 1.7.5 (latest updated code from repo)
+ Flutter (or React Native) version: Flutter
+ Testing Device/Simulator: iOS
+ Screenshot issues (drag the file to attach here): 

![Simulator Screen Shot - iPhone 8 Plus - 2020-07-17 at 15 11 46](https://user-images.githubusercontent.com/45998347/87822821-299f7680-c840-11ea-964e-622f4bc6faf0.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**
Submitted earlier. #4174

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by luyx2412** [comment]
Hi @karmelcorn I just invited you to FluxShopify repo latest version, please merge with your source code which fixed the issue.

Thanks

**Comment by karmelcorn** [comment]
Hi @luyx2412 , the bug is still there. I just check based on the full code from the latest repo. 

The bug is happening somewhere inside 
ProductModel.getProductsList(..)

somehow after adding this
      if (this.categoryId == categoryId) {
        cursor = "";
        hasNextPage = false;
      }
in the recent update to fix the 'No products issue", now the spinner does not stop spinning after the code finishes ProductModel.getProductsList(...)

Can you please tell me where is the code that controls the spinning of the refresh icon?

Thank you.

**Comment by karmelcorn** [comment]
The bug is here in /lib/widgets/product/product_list.dart

if (widget.isFetching == false && oldWidget.isFetching == true) {

        print("update completed");
      _refreshController.refreshCompleted();
      _refreshController.loadComplete();
    }

for refresh widget.isFetching == false and oldWidget.isFetching == false
thus the update is never completed. 

Can you explain in what case would oldWidget.isFetching == true?

**Comment by karmelcorn** [comment]
So the problem is onloadmore, the productpage widget is rebuilt twice, hence able to satisfy the above condition. 

But for onRefresh, the ProductPage widget is only rebuilt once. thus it fails the above condition. 

Any insights why onloadmore, the widget is being rebuilt twice?

**Comment by karmelcorn** [comment]
If the bug can't be fixed, what's the fastest way to disable pull to refresh but keep load more.

**Comment by karmelcorn** [comment]
I think i fixed it. 

1. in productmodel, uncomment isEnd=true, because on refresh, product already exist, if we set isEnd=true, you will disable the loadmore function of smartRefresher. 
if (!isExisted) {
        if (page == 0 || page == 1) {
          print("first page");
          productsList = products;
        } else {
          // I think here they add on load more.
          print("not first page");
          productsList = [...productsList, ...products];
        }
      } else {
        //product already exist
       
        **//isEnd = true; //// uncomment out this line.** 

      }


2. in productList widget, just reset the controller when widget.isFetching == false

 void didUpdateWidget(ProductList oldWidget) {
    super.didUpdateWidget(oldWidget);

   
   // if (widget.isFetching == false && oldWidget.isFetching == true) {
    **if(widget.isFetching == false){**
      print("load completed");

      _refreshController.loadComplete();
      _refreshController.refreshCompleted();

    }

**Comment by minhcasi** [comment]
@karmelcorn - thank you for your sharing - we will check and keep upgrade this patching into the source as well

@luyx2412 - help to have a check

**Comment by luyx2412** [comment]
Hi @karmelcorn Please pull new code with Fluxshopify repo which fixed latest code.

Thanks
