### ISSUE TITLE
No carga los productos en aplicación publicada PlayStore

### ISSUE THREAD

**Issue by jrurbanoa** [inspireui/support#4245]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
Hello, all the steps to publish the application in PlayStore are ready, the option "isCaching" is set to true and when the application is installed, it does not load the products.

Another thing I have noticed is that when I click on the banner it only loads a few, but therefore the category, the home page and other parts don't load the products.

Hello, all the steps to publish the application in PlayStore are ready, the option "isCaching" is set to true and when the application is installed, it does not load the products.

Another thing I have noticed is that when I click on the banner it only loads a few, but therefore the category, the home page and other parts don't load the products.

When you set the "isCaching" option to false if you load the products.

+ Product & version: Fluxstore Pro
+ Flutter (or React Native) version:  Flutter 1.17.5
+ Testing Device/Simulator:  Android
+ Screenshot issues (drag the file to attach here): 
Video:
https://www.dropbox.com/s/qfb8vbd8hoacl0d/NoCargaProductos.mp4?dl=0

Fotos:
https://www.dropbox.com/s/o9ke26lpdpkfma6/Screenshot_20200717-141457.jpg?dl=0
https://www.dropbox.com/s/uuk3qx6n1lwxf61/Screenshot_20200717-141506.jpg?dl=0

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by ameenbadri7** [comment]
The purpose of `isCaching `is to optimize the user's performance by not reloading config again when experiencing the app. 
That's why when you enable `isCaching`, the product layout will not be loaded again. 
However, the `product detail screen` always needs to be `reloaded `due to special `data events`. 
Therefore, please consider using this feature if your site is mostly `"static"`. 
Otherwise, turn this one off if you need your data is always up-to-date.
Let me know if you still have any questions.
Best!

**Comment by minhcasi** [comment]
@jrurbanoa - pls give your comments into one open ticket #4181 - thanks for your time

**Comment by jurbanoa** [comment]
And the option "kIsResizeImage" as it should be if my page is not static?
