### ISSUE TITLE
Shopify - sideMenu Category doesn't show products data, Error in Additional Information and in Product Variant

### ISSUE THREAD

**Issue by RomeoDar** [inspireui/support#4246]
Detail Issues: First i had issue products are not showing second time ( #4213 ) but that was solved becaz i've access to your gitlab, now in category screen i'm having issue with (subCategories,animation and sideMenu), the issue is, when i open category screen, only category name(text) is displayed.... there is not any data of product on that screen (i used subCategories, animation and sideMenu), but when i use card or column everything works fine........ the issue is i want to use sideMenu but that doesn't show any product as you can clearly see from the screenshot.

![f7a73b54-2e04-40f9-a040-00b977958b06](https://user-images.githubusercontent.com/52714884/87833989-b549ef00-c8a2-11ea-8893-e7f76ef118f8.jpg)

Another issue is Product variant there is error in Additional Information and i want to remove "Title Default Title" as mention in the image

![WhatsApp Image 2020-07-18 at 2 45 32 AM](https://user-images.githubusercontent.com/52714884/87834115-035ef280-c8a3-11ea-9caa-a75cd80e96dd.jpeg)

Last i want to know how to change background color of each screen (currently its white, i want to change its color other than white ).

So 3 issues i'm facing, Product not displaying on some of categories section (sideMenu, subCategories and animation) i only want to use sideMenu
Another issue on product page (how to remove default title button and Title text) and There is error in Addition Information
Last how to change color of background of each screen ?

Please Help me out of this nightmare

NOTE: I'VE SUBMITTED THE TICKET DON'T ASK TO UPLOAD AGAIN
NOTE: I'VE YOUR GITLAB ACCESS OF THE LATEST CODE OF SHOPIFY
NOTE: PLEASE RUN THE CODE FROM GITLAB AND TELL ME EITHER THIS ISSUE IS FROM MY END OR YOUR END
NOTE: Every Categories works fine on fluxstore builder

NOTE: i've send you my complete project on email ( minhcasi@gmail.com , inspireui-team@inspireui.com and inspireui.team@gmail.com ) plus i've attached with the ticket
NOTE: I'VE ATTACHED MY CONFIG FOLDER IN TICKET

Product & version: Version: 1.7.5 and its Fluxstore Shopify
Flutter (or React Native) version: Flutter
Testing Device/Simulator: Oppo F7 and Emulator
Screenshot issues (drag the file to attach here):

![f7a73b54-2e04-40f9-a040-00b977958b06](https://user-images.githubusercontent.com/52714884/87831239-55e8e080-c89c-11ea-9b3f-1ebb6360073a.jpg)

**Comment by luyx2412** [comment]
Hi @RomeoDar I just invited you to latest FluxShopify repo, so please merge latest version with your source code to fix the issue.

Thanks

**Comment by RomeoDar** [comment]
you didn't read my post, kindly go through the issue and NOTES i mentioned (told you i've accesss to your latest FluxShopify Repo (fluxstore-shopify Project ID: 18149752 on gitlab)) there is issue with the code (sideMenu Category is not display any products, and there is Error Message in Additional Information of product variant)

**Comment by RomeoDar** [comment]
Kindly Try Latest FluxShopify Repo with following TabBar Code and do lemme know

"TabBar": [
    {
      "layout": "home",
      "icon": "assets/icons/tabs/icon-home.png",
      "pos":100
    },
    {
      "layout": "category",
      "categoryLayout": "subCategories",
      "icon": "assets/icons/tabs/icon-category.png"
    },
    {
      "layout": "search",
      "icon": "assets/icons/tabs/icon-search.png"
    },
    {
      "layout": "cart",
      "icon": "assets/icons/tabs/icon-cart2.png"
    },
    {
      "layout": "profile",
      "icon": "assets/icons/tabs/icon-user.png"
    }
  ],

**Comment by RomeoDar** [comment]
There is also a bug everything works fine, evverything displaying on home page but when i logged into the account product vanished from the home screen
check this video (Please solve this issue on priority basis)

https://drive.google.com/file/d/1u7q4EwxKGe3O210_A7cV-wB9YZTp7LCc/view?usp=sharing

**Comment by shahzadshah123** [comment]
getting this

https://drive.google.com/file/d/1DT9NClJ2NCMKRGi-Zoo0X1BMO753p0-X/view?usp=sharing

 instead of this product view

https://drive.google.com/file/d/1xpk-qBdsE2BWIZaJ7ZJ1HfdzLRMzH1Uw/view?usp=sharing

and my config file and comon file is

https://drive.google.com/file/d/12UfGIEZ04lE2IBGenMf8SgAKS1w9e1f0/view?usp=sharing

kindly please check it up and recover as soon as posible

**Comment by RomeoDar** [comment]
@minhcasi @luyx2412 still waiting for response

**Comment by shahzadshah123** [comment]
same

**Comment by shahzadshah123** [comment]
@minhcasi @luyx2412  please update us are you working on these issues or we will search for alternative. Please please......

**Comment by luyx2412** [comment]
Hi @shahzadshah123 Can you create your issue, i will help and invite you to new version which will fix the issue.
Hi @RomeoDar Are you pull latest version on gitlab repo? I fixed the issue.

Thanks

**Comment by shahzadshah123** [comment]
Issue resolved thankyou for your support..

**Comment by RogerantTshibangu** [comment]
Hi Guys,
I am also facing the same issue as above. Can you kindly assist me as well

**Comment by RogerantTshibangu** [comment]
@shahzadshah123 How did you resolve your issue?

**Comment by shahzadshah123** [comment]
create a new app then copy the same code on it

**Comment by RomeoDar** [comment]
@minhcasi  @luyx2412  can you please elaborate which issue you resolve becaz its still same, you didn't solve any issue i've mentioned......i'm afraid this product have alot of bugs/errors/issue and still you put it for sale....and now without reading my post you're keep wasting time by saying you fixed it

**Comment by luyx2412** [comment]
Hi @RomeoDar I just invited you to latest version Fluxshopify repo, so please merge with your code which fixed the issue.
Hi @RogerantTshibangu Please create your issue ticket and fill the form. I will support you.

Thanks

**Comment by RomeoDar** [comment]
![Capture](https://user-images.githubusercontent.com/52714884/88308417-6d095180-cd26-11ea-81c6-936e9f3e7914.PNG)
are you talking about this repo ? (i already joined this repo project 5 days ago and tried everything not working)

**Comment by luyx2412** [comment]
Hi @RomeoDar Yep this is the latest repo, the issue fixed. If your source code still appear the issue, so please send your source code via inspireui.team@gmail.com. Let me investigate about it.

Thanks

**Comment by RomeoDar** [comment]
NOTE: i've send you my complete project on email ( minhcasi@gmail.com and inspireui.team@gmail.com ) plus i've attached with the ticket search your email by the #4246 ticket number to access the source code

**Comment by luyx2412** [comment]
Hi @RomeoDar Thanks for your email, let me investigate and reply you soon.

**Comment by luyx2412** [comment]
Hi @RomeoDar I just checked your source code, and it is not the latest version with fluxshopify repo. So please pull latest version and merge with your code.
![image](https://user-images.githubusercontent.com/8909619/89094415-c724a980-d3ed-11ea-998d-b298f4d58b68.png)
This is image with new code in your project.

Thanks

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
