### ISSUE TITLE
Fluxstore app performance very low as compared to other apps fluxstore

### ISSUE THREAD

**Issue by Zeehshan** [inspireui/support#4248]
Hi, 
Sir, i purchased multivendor fluxstore app, and i integrated it with my website https://ma3on.com/, my website performance working very fast , butt on the app side working very slowly, 
https://play.google.com/store/apps/details?id=com.ma3on.app
Kindly let me know what is the issue why app working very slowly, i also uploaded config.json file to mstore plugin

**Comment by minhcasi** [comment]
@Zeehshan - could i know if you have tried this solution https://docs.inspireui.com/fluxstore/performance/

**Comment by Zeehshan** [comment]
Sir, i already completed all the step to improve performance of the app, i sent you everything to check.
Butt the performance still very slow.

**Comment by minhcasi** [comment]
@Zeehshan - could you share the whole source to inspireui.team@gmail.com - we may check and profiling your app 

Please note that we will not support answering or support technical issues for the regular license as per support policies - https://inspireui.com/support-policies/ - but we are trying to best to give extra miles with the supporting.

**Comment by Zeehshan** [comment]
![Screenshot 2020-07-20 at 7 51 47 PM](https://user-images.githubusercontent.com/25202051/87951787-74c8bc00-cac2-11ea-8ad8-f71265450528.png)
Sir i sent you invitation link for the code, please check and let me know what i am going wrong in this, sir i have managed many apps for fluxstore, i am also a flutter developer,butt i dont know why this app is working very slowely.
https://play.google.com/store/apps/details?id=com.zsbmall.app
https://play.google.com/store/apps/details?id=com.btech.kurdistan
https://play.google.com/store/apps/details?id=com.ma3on.app
https://play.google.com/store/apps/details?id=com.zed.makumbi
https://play.google.com/store/apps/details?id=com.digitalflow.app
https://play.google.com/store/apps/details?id=com.libyadiscounts.service

**Comment by minhcasi** [comment]
@Zeehshan - could you help to re-send the 6 PDF License of these apps to my email please hi@inspireui.com - we will verify and check the solution to fix it - thank you for your time!

**Comment by Zeehshan** [comment]
@minhcasi - i sent you pdf file and also i sent you invitation for the source code please let me know when you will check code, because i have issue with only one which i developed last time.
And i sent you source code to the  inspireui.team@gmail.com

**Comment by minhcasi** [comment]
@Zeehshan - could i send these all 6 Licenses?

**Comment by minhcasi** [comment]
@Zeehshan - pls send your all proof of purchase to email ASAP

**Comment by minhcasi** [comment]
we will continue with the support still you could proof the valid licenses - thank you for your time

**Comment by Zeehshan** [comment]
Sir i already sent you valid license pdf file and also i invite you for the source code,Please kindly if you cannot check just tell me clear
