### ISSUE TITLE
Fluxstore MV 1.7.6 issue

### ISSUE THREAD

**Issue by FaizalAndro** [inspireui/support#4250]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: Hi, Can you please check the issue, I created two vendors, vendors store name visible below products but when clicking in Category section Store it shows just blank
+ Product & version: 1.7.6
+ Flutter (or React Native) version: Flutter
+ Testing Device/Simulator: Both
+ Screenshot issues (drag the file to attach here): ![Screenshot_1594891677](https://user-images.githubusercontent.com/37078576/87654933-36a36380-c775-11ea-85e1-9e9c3343bbac.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

My Previous Ticket id #4220 

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@FaizalAndro - pls try this config example from our pre-config site - https://docs.inspireui.com/fluxstore/multi-vendor/#1-website-integration

**Comment by FaizalAndro** [comment]
I did all the things that mentioned in doc step by step, my products also fetched but only inside Store, vendor list not occurs. Please if possible check it at your side.

**Comment by minhcasi** [comment]
@philipvu30 - please help to investigate this issue - thank you!

**Comment by FaizalAndro** [comment]
Hi @philipvu30 , Please help ... That my skype username you can join there with me: creativetechapps

**Comment by philipvu30** [comment]
Hi,

It seems you deleted the consumer key and consumer secret in the config files you sent us.
In order to test, we need those keys. Please resend them to my email: toan@inspireui.com.
>Please help ... That my skype username you can join there with me: creativetechapps

Sorry, I am unable to do this as your license does not meet our new [Support Policies](https://inspireui.com/support-policies/).

**Comment by FaizalAndro** [comment]
@philipvu30 send you keys. Please check now

**Comment by philipvu30** [comment]
Hi,

They are still incorrect. Please generate new keys and try again because I keep getting this error "woocommerce_rest_cannot_view".

**Comment by FaizalAndro** [comment]
Hi @philipvu30 , please check your mail.

**Comment by philipvu30** [comment]
Sent you the lib folder that works.
![image](https://user-images.githubusercontent.com/54442328/88273396-55b96c80-cd04-11ea-8392-a5f230ebd74c.png)
![image](https://user-images.githubusercontent.com/54442328/88273425-5fdb6b00-cd04-11ea-8482-41dba46379cc.png)
![image](https://user-images.githubusercontent.com/54442328/88273452-6833a600-cd04-11ea-8675-bc084353fede.png)

**Comment by FaizalAndro** [comment]
Hi @philipvu30, I replace complete lib folder but I faced one error please have a look at it.
![Capture5](https://user-images.githubusercontent.com/37078576/88280503-8f3da800-cd03-11ea-84bf-5e9e351e0c18.PNG)

**Comment by philipvu30** [comment]
Hi,

My apologies for my mistake. The lib I sent is in development and is unstable.
I've sent the released one. Please check your email.

Thank you.

**Comment by minhcasi** [comment]
@FaizalAndro - pls try the latest release from https://codecanyon.net/downloads or from our gitlab - `v1.7.6`

**Comment by FaizalAndro** [comment]
Thanks @minhcasi , I create my project with the newer code 1.7.6 version. But I got two issues -
1. I created 3 vendors but only 1 vendor displayed 
![WhatsApp Image 2020-07-26 at 12 49 42 AM (1)](https://user-images.githubusercontent.com/37078576/88464622-f90faa80-ced9-11ea-8bb6-daa933c26eaa.jpeg)

![Screenshot](https://user-images.githubusercontent.com/37078576/88464620-f57c2380-ced9-11ea-8299-9cda7922349f.png)

2. Vendor Product doesn't shows
![WhatsApp Image 2020-07-26 at 12 49 42 AM](https://user-images.githubusercontent.com/37078576/88464616-f01ed900-ced9-11ea-834f-00bb83ac5698.jpeg)

**Comment by philipvu30** [comment]
Hi,

1. Your vendors don't have geolocation (i.e latitude and longitude)
2. Incorrect WooCommerce REST API keys.
3. Same as 2.
Please create new keys with read/write permissions.

Thanks.

**Comment by FaizalAndro** [comment]
Hi @philipvu30 , I tried again and all logins just processing please check

**Comment by philipvu30** [comment]
Hi,

I successfully logged in with your config files and our demo app. I suggest re-downloading the google-services.json/GoogleService-Info.plist and apply it again.

**Comment by FaizalAndro** [comment]
But my config file that I was submitted old, recently I updated my app through newer codecanyon update code.

**Comment by philipvu30** [comment]
Hi,

Sorry I cannot help with only apk file as I need to debug and read the error log.
To remind you, according to our [Support Policy](https://inspireui.com/support-policies/) and your license, if your config files run well on our demo app, then we'll consider the case is solved.

**Comment by FaizalAndro** [comment]
@philipvu30 It's totally strange, I can show you proof. Check out the video, progress bar just loading and loading even it logged in. Please provide support instead of letting us know the policies, if things perfect then obviously we'll appreciate your work and rate 5 star. I already rate fluxstore woocommerce 5 star because of this guy Truong Nguyen. He provided me amazing support.

https://drive.google.com/file/d/1RmS1mwhaUWwzlqPIP3uaX4qI-E4-19-V/view?usp=sharing

**Comment by philipvu30** [comment]
Hi,

It's not like I'm not helping as I gave you the result with your config for each of my answers.
1. I cannot help with only apk file as I need to debug and read the error log.
2. The video you sent is not accessible.
3. Sure that Mr. Truong Nguyen gave you amazing support, that is what we're all trying to do. However, we've announced our Support Policy on 1/7/2020 and it is valid from then, and your FluxStore MV regular license was purchased after that date (10/07/2020), my apologies that I cannot help you any further. 

If you want a better support experience, please consider purchasing an extended license. For more detail about what you'll get when upgrading to extended license, check it [here](https://inspireui.com/support-policies/).

**Comment by minhcasi** [comment]
@FaizalAndro - there is a known issue related to wcfm that loading missing stores - pls give a try with this solution https://github.com/inspireui/support/issues/4346#issuecomment-664844336

**Comment by FaizalAndro** [comment]
Hi @minhcasi , Please check this video https://drive.google.com/file/d/1RmS1mwhaUWwzlqPIP3uaX4qI-E4-19-V/view?usp=sharing
My issue is progress bar just loading and loading even it logged in.

**Comment by FaizalAndro** [comment]
@minhcasi , please provide some solution. It's been 5 days, and I have login progress bar issues.

**Comment by minhcasi** [comment]
@minhtruong315 - please help to check to see if it is related to `mstore-api` issue - thank you!

**Comment by minhtruong315** [comment]
Hi @FaizalAndro can u send me full your source code via email: minhtruong315@gmail.com
ping me when you sent.
Thanks

**Comment by FaizalAndro** [comment]
@minhtruong315  Mail sent, Please check

**Comment by minhtruong315** [comment]
Hi @FaizalAndro can u send me PrataP.jks ?

**Comment by FaizalAndro** [comment]
@minhtruong315 sent

**Comment by minhtruong315** [comment]
@FaizalAndro can u add me add to your firebase? Thanks

**Comment by FaizalAndro** [comment]
@minhtruong315 Done

**Comment by minhtruong315** [comment]
@FaizalAndro https://www.youtube.com/watch?v=C_9mk_MmvOQ&t=608s
Please follow this guide to setup firebase for your project.

**Comment by FaizalAndro** [comment]
Hi @minhtruong315 , Did you check this video https://drive.google.com/file/d/1RmS1mwhaUWwzlqPIP3uaX4qI-E4-19-V/view?usp=sharing

Problem is in only Progress bar, I already set sha1 of both my dubug system key and PrataP key. It just shows progress bar for a long and when I press back then it's already login. Please have a look at refer video.

**Comment by minhtruong315** [comment]
@FaizalAndro when you login account on Fluxstore. it will login to firebase to use Chat function. so if you dont setup your firebase like my video. you can't login to firebase. so it will show loading forever.

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!

**Comment by FaizalAndro** [comment]
@minhtruong315 , Thanks a lot brother Problem solved
