### ISSUE TITLE
Sms Login

### ISSUE THREAD

**Issue by harjono-flux** [inspireui/support#4251]
Thx for fast support for this case https://github.com/inspireui/support/issues/4240
After succes login with gmail, i try login with sms, but fail. Can you help me? (again) 
Many thanks before

![IMG-20200718-WA0000](https://user-images.githubusercontent.com/64935574/87854107-e9c0b800-c941-11ea-9780-ea139d354963.jpg)

**Comment by ameenbadri7** [comment]
you are welcome, 
can you double-check your firebase setting by : 
enable SMS login 

<img width="960" alt="are those enabled !" src="https://user-images.githubusercontent.com/37524186/87854327-e44f7780-c919-11ea-97f8-708adaa5ff44.png">

also, add your SHA-1 & SHA-256  both of them.
let us know if you still have issues. 

thank you.

**Comment by harjono-flux** [comment]
> You are welcome,
> Can you double-check your firebase setting by :
> Enable SMS login
> 
> <img alt="are those enabled !" width="960" src="https://user-images.githubusercontent.com/37524186/87854327-e44f7780-c919-11ea-97f8-708adaa5ff44.png">
> 
> Also, add your SHA-1 & SHA-256 to both of them.
> 
> If it's not working then update your mstore plugin on your WordPress site and also activate the plugin until you see :
> `Your website has been license and all the API features are unlocked. `
> Let us know if you still have issues.
> 
> Thank you.

Walao... the problem from mstore plugin. After i update, it succes login from sms. Problem Solved
Once again thx bro

**Comment by ameenbadri7** [comment]
Glad that this fixes your issue, and remember you can speak with our team about customizing the app as you like, fluxstore its a big app with a lot of capabilities.  

You could also help us by giving your feedback/rating to [Codecanyon Market website](https://codecanyon.net/downloads), 
we are working hard to update more awesome and powerful features on the next coming version release. 
Let us know if you have any feedback. 

Thank you very much ❤️
