### ISSUE TITLE
Mstore Pro 4.0.0 React Native App  Login Screen Stuck and Cart is not synced with Wordpress Cart

### ISSUE THREAD

**Issue by aqibyaqoob1234** [inspireui/support#4252]
I just Purchased Mstore Pro theme and added the Woocommerce API Auth and APP key in the application. I am unable to log in. Login Screen gets stuck there and not responding to any thing. I am unable to login with registered users. Also facing issue related to Cart not synced with the WordPress Woocomerce Cart items. 

Product and Version = Mstore Pro 4.0.0 React Native
Doing Testing using Expo Application.
![WhatsApp Image 2020-07-18 at 18 48 26](https://user-images.githubusercontent.com/68470600/87854126-ff75b380-c928-11ea-9dc2-b44864df7bc6.jpeg)

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 

Thank you for your time!

**Comment by aqibyaqoob1234** [comment]
Hello , I already submitted this form

‪On Sat, Jul 18, 2020 at 7:07 PM ‫amin badri أمين بدري‬‎ <
notifications@github.com> wrote:‬

**Comment by aqibyaqoob1234** [comment]
Hello, any solution to this?

**Comment by luyx2412** [comment]
Hi @aqibyaqoob1234 I just checked your config, and everything worked normal. So can you give me the screenshot or video issue, let me investigate easier. Please see the video
https://drive.google.com/file/d/1oP7MRhIGVSuJKWQV48qi2r_I0a4K9D8q/view?usp=sharing

Thanks

**Comment by aqibyaqoob1234** [comment]
Hi @luyx2412, Thanks for your reply. I am sharing the video where u can see the that on login screen i get stuck and i am unable to proceed. Even when get back to the login screen again it still doesn't allow to submit the form.
https://drive.google.com/file/d/1Dh_8BAKspqVQpqgP68XJZoXzRq0a5OTn/view?usp=sharing

**Comment by aqibyaqoob1234** [comment]
Also please do let me know that cart will not be synced with woocomerce cart API ? Like if on the web I have added 2 to 3 products on cart and will it not reflect on the Mobile application side when I will log in with the same user on mobile application?

**Comment by aqibyaqoob1234** [comment]
Hello @luyx2412, Any solution to this?

**Comment by luyx2412** [comment]
Hi @aqibyaqoob1234 
- The login issue, please upgrade latest version Mstore-api plugin in your wordpress website.
- We did not support sync the cart with mobile application. 

Thanks

**Comment by aqibyaqoob1234** [comment]
Hello @luyx2412,  I just updated the Mstore-api  plugin on the WordPress website. Still having the same issue. Login Screen get stuck. can u help me out on this? I have to meet some deadlines. Thanks

**Comment by luyx2412** [comment]
Hi @aqibyaqoob1234 Please in your side i just tested your config and everything worked normal https://drive.google.com/file/d/16AFtFnh9gr72rul4WshY9W47Ci4Kuvhz/view?usp=sharing

Thanks

**Comment by aqibyaqoob1234** [comment]
i am testing it on Expo Application. Login Get stuck.

**Comment by aqibyaqoob1234** [comment]
Can I share a project with you? If u can check because something is not working properly.

**Comment by luyx2412** [comment]
HI @aqibyaqoob1234 Great, please share your project via inspireui.team@gmail.com. Let me check and reply you soon.

Thanks

**Comment by aqibyaqoob1234** [comment]
Ok i'll sharing you. I am not getting Favourite Products List on Home Page and Login is not working properly.

**Comment by luyx2412** [comment]
Hi @aqibyaqoob1234 Can you resend me again via inspireui.team@gmail.com and with title `4252`? I did not see your project in email.

Thanks

**Comment by aqibyaqoob1234** [comment]
I sent it again. with title 4252 having Link to download project from We transfer.

**Comment by luyx2412** [comment]
Hi @aqibyaqoob1234 Please replace this file with `src/containers/Login/index.js` to fix the issue.

[index.js.zip](https://github.com/inspireui/support/files/5012191/index.js.zip)

Thanks

**Comment by minhcasi** [comment]
@aqibyaqoob1234 - let us know your checking, thank you!

**Comment by aqibyaqoob1234** [comment]
@minhcasi @luyx2412 Thanks for ur help. Login issue is resolved Thanks.
