### ISSUE TITLE
Firebase real time chat issues 

### ISSUE THREAD

**Issue by ssathamenterprises** [inspireui/support#4255]
![102882E0-659E-443F-9462-2D830102EDE3](https://user-images.githubusercontent.com/68118999/87860972-5e144f00-c974-11ea-8e16-fc3870b0540d.jpeg)
![6ECAA239-766A-443D-BA6A-54C6955B3F81](https://user-images.githubusercontent.com/68118999/87860974-62d90300-c974-11ea-8b4a-d7acff23cce6.jpeg)

Attached proof of purchase 

Hello I have issues with real time firebase chat 

I done everything follow the video but have issues 

1. I send one message to one store ( but the same message shows in all stores in my side )

2. The vendor also not received the message

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 

Thank you for your time!

**Comment by ssathamenterprises** [comment]
I submitted the proof already

**Comment by minhcasi** [comment]
@ssathamenterprises - could i check i you have follow this guide to setup the Firebase - https://docs.inspireui.com/fluxstore/firebase/ ? Thank you!

**Comment by ssathamenterprises** [comment]
Yes I follow this guide and video also but not works have the issues which one I mention

**Comment by ssathamenterprises** [comment]
hello can any one help on this please

**Comment by minhcasi** [comment]
@ssathamenterprises - please try your best with the video guide that we have provided from the guide

Some videos guide here will also be helpful - https://www.youtube.com/playlist?list=PLcF-HiQy-jOLumZ3Pedj_MNLZfwI4yLQy

**Comment by ssathamenterprises** [comment]
@minhcasi  - please check the following video, help me please the firebase received the chat intimations all but the vendor only not receive it help me 

https://www.loom.com/share/1708fbf45c704ad4991028aab2157406

**Comment by minhcasi** [comment]
@ssathamenterprises - I'm sorry that we could not go farther to check for this issue as it is the limit scope of the regular license, please help to upgrade to Extended License to get more offer support from us, for more detail please check this detail support policy - https://inspireui.com/support-policies/

Thank you for your time!

**Comment by ssathamenterprises** [comment]
Actually I saw your support policy, I never asked anything about new features and customise  , I ask yours because of its bug ( note : this issue in the code . in regular license you provide code and supported documents I follow your document it’s not works means there is some bug in your code , so this one your team only able to support for fix the bug )

**Comment by minhcasi** [comment]
It could cause some of your missings, please try your best with our video guide again, it's all clarify there

**Comment by minhcasi** [comment]
Please also help to check with the latest release `1.7.6` - thank you!
