### ISSUE TITLE
Fluxstore MV 1.7.6

### ISSUE THREAD

**Issue by grnas00** [inspireui/support#4256]
Hello dear ,, 

i see an issue open with 1.7.6 version but the last update i get it 1.7.5 

another things i tired to build ios app but faced Error in FBnetworkaudince error

**Comment by minhcasi** [comment]
@grnas00 - the latest 1.7.6 is still in gilab for processing the testing, we will update new release on early next week - please help us to give your all comment into one open ticket #3976 - thank you!
