### ISSUE TITLE
Fluxnews 1.4.1 vertical list view.

### ISSUE THREAD

**Issue by admincode1** [inspireui/support#4259]
Hello,

+ Detail Issues: 
I'm using only vertical simple list on home page & it showing only the latest 10 blogs.
How can I change it to show all blogs? 

+ Product & version:
Fluxnews 1.4.1

+ Flutter (or React Native) version: 
Latest (flutter doctor -v no issues).

+ Testing Device/Simulator: 
Samsung phone.

+ Screenshot issues (drag the file to attach here): 
![Screenshot_20200719-023843](https://user-images.githubusercontent.com/67590385/87864017-53a18780-c96b-11ea-82b7-fb26f517f576.jpg)

**Comment by minhcasi** [comment]
@admincode1 - thank you for the feedback, it seems it is the missing feature that we did not implement for the vertical list.

Is it possible to show the "See All" label to display all posts on the next screens?

**Comment by admincode1** [comment]
There is no "See All" label above the vertical simple list.
![Screenshot_20200719-083353](https://user-images.githubusercontent.com/67590385/87868104-9c713480-c99b-11ea-8012-6d741c5ba427.jpg)

**Comment by minhcasi** [comment]
Let us have a check and give you the solution to fix this issue - thank you!

**Comment by dttrung26** [comment]
Hi @admincode1 ,
replacing the attached file into your /lib/widgets/blog/vertical/ would fix your problem. A permanent solution will be provided in FluxNews next patch. 
Happy coding!
[issue#4259.zip](https://github.com/inspireui/support/files/4951045/issue.4259.zip)

**Comment by admincode1** [comment]
Hi dttrung2,
It changed to load continuously which what I need, but it repeating the same first 10 blogs in blog 11 - 20, blog 21 - 30 etc...

**Comment by dttrung26** [comment]
Hi @admincode1 , 
I'm quite not sure about your response. Did it fix infinite load in vertical layout, may I ask?

**Comment by admincode1** [comment]
Yes it fixed the load in vertical layout but it showing the same 10 blogs only.
For example, instead of showing blog-11, it shows blog-1!
The load just repeating the first 10 blogs.

**Comment by dttrung26** [comment]
Hi @admincode1 , 
if you haven't modified your wordpress.dart file, then replacing attached file into your /lib/services/wordpress.dart would fix your issue. 
[issue#4259.zip](https://github.com/inspireui/support/files/4957559/issue.4259.zip)

Let me know if it helps,
Happy coding!

**Comment by admincode1** [comment]
Hi dttrung26,

Okay, it fixed the issue but it doesn't have the right order, see the screenshot example: 
starts from blog-9 to blog-18 then from blog-1 to blog-10 :
The order method in WordPress starts from the newest blogs first and I do have the right order, blog-1 is the newest & last blog is the oldest...

![Screenshot_20200722-073228 (1)](https://user-images.githubusercontent.com/67590385/88136903-ff103d80-cbf2-11ea-8cd8-d31243bcbd77.jpg)

Thanks.

**Comment by dttrung26** [comment]
Hi @admincode1 , 
the main purpose of vertical layout is just to display blogs in vertical. In order to change blog order, it depends on WordPress set up including page, number of blog per page, etc. For example, currently, FluxNews is displaying 10 blog at 1 loading time to optimize the performance. As a result, the order of blogs could be customized within those 10 blogs only. Your customizing request depends on page setup, number of pages, performance effect, etc. Therefore, I can't help you with that customization. 
If you wish to implement that feature, please play around with [WordPress API Endpoints](https://developer.wordpress.org/rest-api/reference/posts/) and modify the `fetchBlogLayout` function located at /lib/services/wordpress.dart 
Let me know if you still have any question.
Best!

**Comment by admincode1** [comment]
Hi dttrung26,
I changed Wordpress post per page to -1 (unlimited) and working fine but I couldn't change per_page on wordpress.dart to more than 100, I have 134 blogs.. I tried to work around fetchBlogLayout, but everything above 100 failed... thanks for your help @dttrung26 @minhcasi.
