### ISSUE TITLE
purchased a code getting product view error

### ISSUE THREAD

**Issue by shahzadshah123** [inspireui/support#4262]
getting this

https://drive.google.com/file/d/1DT9NClJ2NCMKRGi-Zoo0X1BMO753p0-X/view?usp=sharing

 instead of this product view

https://drive.google.com/file/d/1xpk-qBdsE2BWIZaJ7ZJ1HfdzLRMzH1Uw/view?usp=sharing

and my config file and comon file is

https://drive.google.com/file/d/12UfGIEZ04lE2IBGenMf8SgAKS1w9e1f0/view?usp=sharing

kindly please check it up and recover as soon as posible

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 

Thank you for your time!

**Comment by shahzadshah123** [comment]
48 hours passed butt didnot got any quality responce

‪On Sun, Jul 19, 2020 at 6:42 AM ‫amin badri أمين بدري‬‎ <
notifications@github.com> wrote:‬

**Comment by minhcasi** [comment]
@shahzadshah123 - could i know if you have submitted the proof of purchase from step 2 of this ticket - thank you for your time

**Comment by minhcasi** [comment]
<img width="682" alt="Screen Shot 2020-07-20 at 10 06 12" src="https://user-images.githubusercontent.com/1459805/87895835-a9138c80-ca70-11ea-8aca-67e01ec20e21.png">

pls note the ticket you have raised only 18 hours ago, thank you!

**Comment by shahzadshah123** [comment]
Yes I have the purchase code I fill the form

**Comment by shahzadshah123** [comment]
I have to deliver a project to client please fixed it ap asap..

**Comment by minhcasi** [comment]
@shahzadshah123 - could you able to use the Fluxbuilder to config the homepage on your app - http://fluxbuilder.com/

It will help to config you the app super easy, more document guide https://docs.inspireui.com/fluxbuilder

**Comment by shahzadshah123** [comment]
i designed an app using fluxbuilder and its proper working on it but when i
copy paste the json code on config.en then its not working on mobile app

**Comment by minhcasi** [comment]
@shahzadshah123 - could you give a try with the latest version from gitlab - pls submit to http://gitlab.inspireui.com/ - thank you!

**Comment by shahzadshah123** [comment]
submitted what is the next step?

**Comment by shahzadshah123** [comment]
filled a form more then 4 times and provide a purchases license but no any
action created kindly please please fixed my issue or give me any official
or professional fresponce otherwise return my money back

**Comment by minhcasi** [comment]
@shahzadshah123 - pls check the email, we have sent the invitation. Let give a try and let us know :)

**Comment by shahzadshah123** [comment]
Exception: [!] Your app is using an unsupported Gradle project. To fix this
problem, create a new project by running `flutter create -t app
<app-directory>` and then move the dart code, assets and pubspec.yaml to
the new project.

getting this error kindly check it up please

**Comment by minhcasi** [comment]
Hi, pls check following solutions: 

1. try to run "flutter pub get" from the project folder - or you could start it with the android studio 

2. clean up the cache to fix the issue - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

**Comment by shahzadshah123** [comment]
thanks i will get it up i will gave you 5 star on codecynon

**Comment by minhcasi** [comment]
@shahzadshah123 - thank you so much for your help - let us know if you have any question :)
