### ISSUE TITLE
Updating without losing old changes

### ISSUE THREAD

**Issue by TqwaAlTurki** [inspireui/support#4263]
Detail Issues: Hi there, as per suggested by you i moved to Fluxstore WooCommerce  version1.6.7 , but i want to import all the changes that i did on the last version i used 1.6.4. so how can i do that?
appreciate work amazing work, thank you.
Product & version: Fluxstore WooCommerce  version1.6.7 
Flutter  version:  v1.17.2,
Testing Device/Simulator: Android Emulators

**Comment by minhcasi** [comment]
@TqwaAlTurki - pls help to check this guide - https://medium.com/@inspireui/how-to-upgrade-fluxstore-projects-by-using-git-cebde7489ea6 - thank you!

**Comment by TqwaAlTurki** [comment]
@minhcasi i didn't find any projects to fork, also i don't know where to request access for woocommerce fluxstore 🙄
![image](https://user-images.githubusercontent.com/34610407/87914509-07406f80-ca71-11ea-98c2-4f17ca158650.png)

**Comment by minhcasi** [comment]
pls submit access to http://gitlab.inspireui.com
