### ISSUE TITLE
FluxStore [1.7.6] Webview Checkout 404 page not found.

### ISSUE THREAD

**Issue by esolksaapp** [inspireui/support#4264]
I have 2 Issues regarding Fluxstore 1.7.5 and 1.7.6
and 1 Request Feature

Fluxstore version 1.7.5

1 :  With caching enabled, Onepage Checkout = true. Version Fluxstore 1.7.5 
 Issue : My App is published on the playstore version 1.7.5 and users are complaining that they are getting empty checkout
but if I change the api keys to demo website the cart is not empty so there is something in my WP. I'll give you access to my WP to see if there is any plugin or what is causing the empty cart.  Please download the app and see it for yourself
This issue came up few days ago I tested it before publishing but don't know whats happened. 
please put  3000pkr in the cart and name the order as testorder if you were able to see the checkout form 
https://play.google.com/store/apps/details?id=com.saudasulf.app 

Fluxstore version 1.7.6

2 :  On the Onepage Checkout (webview) I am getting 404 page not found. I have Tested it on my Website and 
 demo.mstore.io as well I am getting the same error. 

3: This is a request Feature : Please make Caching property enable for multi languages. You have done a great job in 1.7.6 but please refine it more and fix the 404 checkout error asap My app is published and users are complaining.
 
ScreenShots 

with 1.7.5  This is uploaded to playstore https://play.google.com/store/apps/details?id=com.saudasulf.app

![WhatsApp Image 2020-07-19 at 3 47 10 PM](https://user-images.githubusercontent.com/68499329/87873002-2985af00-c9d7-11ea-859b-3149c1dd5a26.jpeg)

With 1.7.6 this is not published but I want to publish this app ASAP
<img width="456" alt="Screenshot 2020-07-19 at 3 44 33 PM" src="https://user-images.githubusercontent.com/68499329/87872970-c267fa80-c9d6-11ea-8551-cb70218f303a.png">

My Proof of Purchase
!!!!!!!!!

Thanks,

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 

Thank you for your time!

BTW: I have removed your license number from this ticket please only send it to us in privet channels like the email or the support site.

**Comment by esolksaapp** [comment]
Please check I have did what you said

**Comment by esolksaapp** [comment]
Ignore the 1st issue I have solved it. It was some problem in the WP but please give update on 404 error page not found. I need to republish the app ASAP!

**Comment by minhcasi** [comment]
@esolksaapp - could you share the full source code to inspireui.team@gmail.com - we will help to investigate the 404 issue - thank you!

**Comment by jurbanoa** [comment]
Hello, the same thing happened to me, I solved it by editing the name of the payment page to "Checkout" in wordpress.
![image](https://user-images.githubusercontent.com/67361627/87906702-c91f5d80-ca28-11ea-8fa2-3876e3ead57b.png)

Mr. Minhcasi, could you tell me where I can change the word "Checkout"? and put, for example: "make payment" or another name.
When they want to pay from the application and I change this word "Checkout" on my page, it will cause that 404 error since in the application it points to that page called "Checkout".

**Comment by esolksaapp** [comment]
@minhcasi I have asked my developer to send your team the code at inspireui.team@gmail.com and details of the issue. 
with this support ticket : https://github.com/inspireui/support/issues/4264

**Comment by esolksaapp** [comment]
@jurbanoa which payment page you are referring to to change the name to "checkout" I don't have a payment page and my checkout page is already named as  "checkout". can you please elaborate how did you solve it?

**Comment by minhtruong315** [comment]
Hi @esolksaapp Can you give me your skype? I will help you check the issue remotely.
Thanks

**Comment by esolksaapp** [comment]
Hello @minhtruong315 This is my developer's skype : tahir.024

**Comment by esolksaapp** [comment]
Thank you Very much for this support ! please look forward to my request feature
