### ISSUE TITLE
Paypal error - Invalid Arguments

### ISSUE THREAD

**Issue by fasttend** [inspireui/support#4267]
I got the error while selecting Paypal payment method. The error message is : Invalid Arguments

**Note**: To Verify see the previous ticket #3868

**Comment by minhcasi** [comment]
The previous ticket is shown other error #3868 - could you share the new screenshot issue again? Does the Paypal work on your country?

**Comment by fasttend** [comment]
@minhcasi yes paypal gateway is working in India. Also its works fine on my website.
![paypal error1](https://user-images.githubusercontent.com/63434487/87929692-75525a00-caa4-11ea-8944-b530e0e72e3e.jpeg)

**Comment by fasttend** [comment]
![Untitled](https://user-images.githubusercontent.com/63434487/87930083-1214f780-caa5-11ea-8854-117f51a396d9.png)

**Comment by minhcasi** [comment]
okie, let us have a check and let you know - thank you!

**Comment by minhtruong315** [comment]
Hi @fasttend can u send me full your source code via email: minhtruong315@gmail.com
Let me know when you shared.
Thanks

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!

**Comment by fasttend** [comment]
Hi,
How can you closed the ticket without resolving the problem? I have been asked to send the source code by email and I did the same. But now you have closed the ticket without resolve the issue. Kindly check your mail and do the needful.

**Comment by minhtruong315** [comment]
You're using Fluxstore 1.7.4. it's so old. We released version 1.7.6.
Please check your issue in the latest version

**Comment by fasttend** [comment]
I have upgrade my project to version 1.7.6.
Now paypal is working fine in debug mode. But I am not able to build apk. Please see the error screen shoot as below.

![image](https://user-images.githubusercontent.com/63434487/88462009-15095100-cec6-11ea-835f-6e8ee3690763.png)

**Comment by minhtruong315** [comment]
@fasttend can u send me full your source code again via my email?
Let me know when you sent.
Thanks

**Comment by fasttend** [comment]
Mail sent. Please check now.

**Comment by fasttend** [comment]
Waiting for the solution. Please respond.

**Comment by minhtruong315** [comment]
Hi @fasttend can u give me your skype?
I will support you via teamviewer
Thanks

**Comment by fasttend** [comment]
Hi @minhtruong315 My Anydesk ID is: 151 245 383
Can you please connect now?

**Comment by fasttend** [comment]
TeamViewer ID: 213 734 393

**Comment by minhtruong315** [comment]
Hi @fasttend pls open AnyDesk

**Comment by fasttend** [comment]
Hi @minhtruong315 Please connect. I am online now

**Comment by fasttend** [comment]
Hi @minhtruong315 are you able to connect now? Please confirm. I am waiting.

**Comment by minhtruong315** [comment]
I'm sorry, i have tried my best but could not figure out the problem on your window. We are happy with the refund it could not run on your window, this issue is rarely happen with some Window OS (https://flutter.dev/desktop)

**Comment by fasttend** [comment]
Please tell me the refund process.

**Comment by minhtruong315** [comment]
@fasttend send email to support@inspireui.com

**Comment by fasttend** [comment]
can you please build the app bundle and send me the file? because I don't
want to take a refund.

**Comment by fasttend** [comment]
Hi,
Happy to inform you that now I am able to build apk after removing the
following code from android\app\build.gradle.
But the issue is app crashes in startup. App keeps stopping. Please help.

//Fix android-r issue
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(':app')
    afterEvaluate {project ->
        if (project.hasProperty("android") &&
project.property("android").compileSdkVersion.equals("android-R")) {
            android {
                compileSdkVersion 30
            }
        }
    }
}
