### ISSUE TITLE
[MStore Pro] after successful build- "error: bundling failed: SyntaxError: "

### ISSUE THREAD

**Issue by 04Ank** [inspireui/support#427]
**Mandatory Info (please complete the following information):**
 - Product: - Mstore Pro
 - Your Purchased Code: a356d2b4-3c3b-4fa3-89cd-e710b8d96e64

please see image.

![Untitled](https://user-images.githubusercontent.com/48328340/54875177-d79f3a00-4e1f-11e9-8d94-fb9261557953.png)

**Comment by minhcasi** [comment]
Hi, pls double check to download it again as it's ok with our checking the package on Envato, the folder should be 3.7.2 - there is some minor bug fix on that file https://gyazo.com/479fd736353dd721090db247b9c60011

**Comment by 04Ank** [comment]
error again in 3.7.2
![WhatsApp Image 2019-03-24 at 17 49 32](https://user-images.githubusercontent.com/48328340/54879289-46e74f00-4e5d-11e9-9321-d0210161ba36.jpeg)
![WhatsApp Image 2019-03-24 at 17 49 32 (1)](https://user-images.githubusercontent.com/48328340/54879292-48b11280-4e5d-11e9-9ff6-98555ae2bfe3.jpeg)

![eror](https://user-images.githubusercontent.com/48328340/54879243-ac870b80-4e5c-11e9-95a9-7e6fc1ae3107.png)

**Comment by luyx2412** [comment]
Hi @04Ank Your issue related react-native script. Please make use you installed react-native latest version. And before rebuild, please clean your project and metro.

Thanks

**Comment by yosefasad** [comment]
Fresh installation of Mstore 3.7.2, React native 0.5,9 cleared the project and the issue still exist , ... 

Please check the screenshot .    https://imgur.com/a/ETthgLF

waiting for a solution

Thanx

**Comment by minhcasi** [comment]
@yosefasad try to run: react-native link

And run the ios simulator via XCode, then send us your screenshot of the error on XCode

**Comment by yosefasad** [comment]
Please check the screenshot

https://imgur.com/a/IaWY5qe

`thanx

**Comment by luyx2412** [comment]
Hi @04Ank Please follow the comment to fix this issue. https://github.com/facebook/react-native-fbsdk/issues/401#issuecomment-435312536

Thanks

**Comment by yosefasad** [comment]
I still got this error .    https://imgur.com/a/lW5Ztrq

please check these configuration .     https://imgur.com/a/OXzIaXu

Thanx

**Comment by luyx2412** [comment]
Hi @yosefasad Please make sure you linked the library to xcode `react-native link`. I saw the issue related https://imgur.com/a/lW5Ztrq did not link the library.
- https://imgur.com/a/OXzIaXu please do not change anything in default configuration, because we will difficult to check the issue.

Thanks

**Comment by yosefasad** [comment]
Hello
This what I did  .. 

Fresh installation of Mstore 3.7.2, run iOS setup in CEBuilder
Got this Error    https://imgur.com/a/o3rkkaY

Open mstore.xcworkspace and build successfully  but still get an error 
Please check the screenshot.    https://imgur.com/a/RkRDkp8

mstore.xcodepro
-  Open mstore.xcodeproj  and found error    https://imgur.com/a/gdzTKtX

-  Clean build folder and build again got this error    https://imgur.com/a/JL5A9k3

- Change to  $(HOME)/Documents/FacebookSDK in framework search path
https://imgur.com/a/2TrE6M9
      Clean build folder and build again got this error     https://imgur.com/a/iK7NNCk

    - run   react-native link
      Clean build folder and build again same previous error 


Any suggestion to solve this issue? 


Thanks

**Comment by yosefasad** [comment]
simply you need to run 
yarn install
yarn start
react-native run-ios

Also make sure you install cocoapods 
check your Environment , maybe something is not setup right.

Please see the video     https://youtu.be/RLKbUNzVc00

I hope this help others to face such this simple issue :) 

Thanks

**Comment by luyx2412** [comment]
HI @yosefasad 
- The issue related do not open your develop server, please follow the comment to fix https://stackoverflow.com/questions/42064283/react-nativecould-not-connect-to-development-server-on-android
- Please open `mstore.xworkspace`, because Mstore pro used cocoapod to install some native library.

I think every issues related open `mstore.xcodeproj`. Please open workspace to fix the issues.

Thanks

**Comment by yosefasad** [comment]
I opened mstore.xworkspac and opened Android studio for both IOS simulator and Android emulator...

I realize the following : 

If I don’t  type  “ yarn start” manually , I got the below  error on both android and IOS 

————————————
The development server returned response error code: 500

URL: http://10.0.2.2:8081/index.delta?platform=android&dev=true&minify=false

Body:
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Error: Unable to resolve module `./index` from `/Users/yosefasad/Desktop/mstore-3.7.2/mstore-pro/node_modules/react-native/.`: The module `./index` could not be found from `/Users/yosefasad/Desktop/mstore-3.7.2/mstore-pro/node_modules/react-native/.`. Indeed, none of these files exist:<br> &nbsp;* `/Users/yosefasad/Desktop/mstore-3.7.2/mstore-pro/node_modules/react-native/index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`<br> &nbsp;* `/Users/yosefasad/Desktop/mstore-3.7.2/mstore-pro/node_modules/react-native/index/index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`<br> &nbsp; &nbsp;at ModuleResolver.resolveDependency (/Users/yosefasad/Desktop/mstore-3.7.2/mstore-pro/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:163:15)<br> &nbsp; &nbsp;at ResolutionRequest.resolveDependency (/Users/yosefasad/Desktop/mstore-3.7.2/mstore-pro/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)<br> &nbsp; &nbsp;at DependencyGraph.resolveDependency (/Users/yosefasad/Desktop/mstore-3.7.2/mstore-pro/node_modules/metro/src/node-haste/DependencyGraph.js:283:16)<br> &nbsp; &nbsp;at /Users/yosefasad/Desktop/mstore-3.7.2/mstore-pro/node_modules/metro/src/lib/transformHelpers.js:261:42<br> &nbsp; &nbsp;at Server.&lt;anonymous&gt; (/Users/yosefasad/Desktop/mstore-3.7.2/mstore-pro/node_modules/metro/src/Server.js:1038:41)<br> &nbsp; &nbsp;at Generator.next (&lt;anonymous&gt;)<br> &nbsp; &nbsp;at asyncGeneratorStep (/Users/yosefasad/Desktop/mstore-3.7.2/mstore-pro/node_modules/metro/src/Server.js:99:24)<br> &nbsp; &nbsp;at _next (/Users/yosefasad/Desktop/mstore-3.7.2/mstore-pro/node_modules/metro/src/Server.js:119:9)</pre>
</body>
</html>

processBundleResult
    BundleDownloader.java:296
access$200
    BundleDownloader.java:37
onResponse
    BundleDownloader.java:174
execute
    RealCall.java:206
run
    NamedRunnable.java:32
runWorker
    ThreadPoolExecutor.java:1167
run
    ThreadPoolExecutor.java:641
run
    Thread.java:764

———————————



If I type yarn start manually , IIOS simulator will work , but Android emulator will give the following  error : 


————————————
null is not an object (evaluating 'blob.data')
readAsText
    ReactNativeRenderer-dev.js:13212:10
d
    
<unknown>
    ScrollResponder.js:405:6
dispatchEvent
    ReactNativeRenderer-dev.js:10746:10
setReadyState
    ReactNativeRenderer-dev.js:10481:6
__didCompleteResponse
    ReactNativeRenderer-dev.js:10326:13
emit
    
__callFunction
    
<unknown>
    
__guard
    
callFunctionReturnFlushedQueue
    ReactNativeART.js:61:3

—————————————


I followed the following steps and still got same error (null is not an object (evaluating 'blob.data’))  on android 

1) Start adb server. For this run "adb start-server" command.
2) Then check the connected devices with "adb devices" command. It will give you devices list
3) Then make a connection with this command: "adb -s device_id_got_from_step_2 reverse ctp:8081 tcp:8081".
4) Then try the Hot reload (in iOS press Command+R in Android press Command+M).
5) If Hot reloading doesn't connects then restart the app with Android & Xcode IDE or command line like "react-native run android/ios".


any help ?

**Comment by luyx2412** [comment]
HI @yosefasad 
- The first you need clean your project and re-install again. I think something was wrong when install project.
- The second please use CeBuilder to install project on Window easier.

Thanks
