### ISSUE TITLE
How do I change menu icon and delete whitespace directly

### ISSUE THREAD

**Issue by jvsamoa** [inspireui/support#4270]
Hi Team,

I need to change the menu icon for a classic burger icon. I found the burger icon but I don't know exactly how to change it.
I was following  https://docs.inspireui.com/fluxstore/customization/https://docs.inspireui.com/fluxstore/customization/
but I don't use the inspector because I run Fluxstore directly on my real device.

And I need to change this whitespace, but when I tried to update Fluxstore to 1.7.6 I have a lot of issues again and I need finish this project. Please help me.
![image](https://user-images.githubusercontent.com/25646978/87890253-fde5e180-ca35-11ea-86eb-65e1668d4d39.png)

**Comment by minhcasi** [comment]
1. you could edit this file `lib/widget/home/logo.dart`
<img width="1063" alt="Screen Shot 2020-07-20 at 10 14 46" src="https://user-images.githubusercontent.com/1459805/87896240-d876c900-ca71-11ea-9737-e47f3f9f5ee0.png">

2. we will investigate to remove the spacing on this UI - @tgloc96 - pls give suggestion

**Comment by minhcasi** [comment]
@jvsamoa - pls help us to raise you all comment into one open ticket support #4299 - thank you!
