### ISSUE TITLE
404 error page when process the payment on checkout

### ISSUE THREAD

**Issue by mvin10** [inspireui/support#4271]
Fluxtore woocommerce
Version 1.7.3
Testing in ios simulator and android 
Purchase Verified id here #Ticket-ID #3670
---------------------------------------------------------

404 error page when process the payment, i have followed this page to solve it https://docs.inspireui.com/mstore/questions/#404-error-page-when-process-the-payment. 

I have created Mstore Checkout with mstore api template and not works, also tested with second answer  creating a mstore checkout template, my mstore plugin is up to date , not works, let me know if you need some files from me or admin access to my wordpress site.

I would like to not show my website, i would like all process works on app, no show website anyway.

![test1](https://user-images.githubusercontent.com/8391284/87896950-0c68d480-ca07-11ea-9380-fd32f60d41d6.png)

Also i have tested here, but not works:
<img width="931" alt="Captura de Pantalla 2020-07-19 a la(s) 21 31 57" src="https://user-images.githubusercontent.com/8391284/87897046-5e115f00-ca07-11ea-9bcf-de135786ff19.png">

**Comment by minhcasi** [comment]
@mvin10 - could you help to give a try to check with our pre-config site setting - https://docs.inspireui.com/fluxstore/woocommerce-setup/#1-website-integration

**Comment by mvin10** [comment]
Hi, to check that demo site,  do i need only these 3 fields ?

"consumerKey": "ck_b7594bc4391db4b56c635fe6da1072a53xxxxx",
"consumerSecret": "cs_980b9edb120e15bd2a8b668cacc734f7xxxxx",
"url": "http://demo.mstore.io",

Is that correct? check keys, there are xxxx at the end, or where do i get the corrects?
thank you

**Comment by ameenbadri7** [comment]
export 'config/advertise.dart';
export 'config/general.dart';
export 'config/onboarding.dart';
export 'config/payments.dart';
export 'config/products.dart';
export 'config/smartchat.dart';

/// Server config demo for WooCommerce
/// Get more example for Opencart / Magento / Shopify from the example folder
const serverConfig = {
  "type": "woo",
  "url": "https://mstore.io",

  /// document: https://docs.inspireui.com/fluxstore/woocommerce-setup/
  "consumerKey": "ck_c16d601d14a44c8080418c1ab9336b72ae8faff2",
  "consumerSecret": "cs_1c11c4d0ee3bef861421bf3622f20f6b49c8497a",

  /// Your website woocommerce. You can remove this line if it same url
  "blog": "https://mstore.io",

  /// set blank to use as native screen
  "forgetPassword": "http://demo.mstore.io/wp-login.php?action=lostpassword"
};

IT SHOULD BE LIKE THIS JUST REPLACE THEM WITH YOUR SECRETS KEYS AND WEBSITE URL. 

and try to check if you have a checkout page or not !

Try the link that minh give you and do it to add the missing pages or configurations.

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
