### ISSUE TITLE
MStore API activation

### ISSUE THREAD

**Issue by sadeq90** [inspireui/support#4272]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
![image](https://user-images.githubusercontent.com/32711146/87906518-6e5b2580-ca6b-11ea-8d4d-7e81077260d7.png)

the domain is same, I just restore a backup and now could not verify the purchase code.

+ Product & version: 
Fluxstore MV
+ Flutter (or React Native) version: 
Flutter
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@sadeq90 - we have reset it, pls try to check again - thank you!
