### ISSUE TITLE
Still having problem with the WPML and OnePageCheckout: true

### ISSUE THREAD

**Issue by easieber** [inspireui/support#4273]
Last week i reported this issue and someone sent me a lib folder with the fix. But i tried and i am still having the problem.. I tried to replied him and comment the previous ticket, but you closed it m( 24 hours to reply is nothing)..

i am reopening this issue so far:

the spanish and english language are not working right, when i have the app in spanish the checkout is in english, and when i have the app in english the checkout is in german. You can check the video

https://recordit.co/vrHHZC1i92

**Comment by minhcasi** [comment]
@minhtruong315 - please help to check this issue

**Comment by minhtruong315** [comment]
Hi @easieber please change CheckoutPageSlug in common/config/payments.dart like this
``` 
//This config is same with checkout page slug in the website
  "CheckoutPageSlug": {"en": "en/checkout", "de": "kasse", "es": "es/confirmar"},
```

**Comment by easieber** [comment]
Now it works, thank you!
