### ISSUE TITLE
Color View change from row to column

### ISSUE THREAD

**Issue by destek-harshadapatil** [inspireui/support#4274]
Hello team,

I wanted to change the view of color palet showing on the buy now and add cart screen. As it is now placed in horizontal manner but I wanted to show that in vertical view. 

Below I have added the image where you can see the 4 color in horizontal view. I wanted to show the same in vertical view or you can say in linear manner i have shown it with arrow.  Please help me with this.

![20200720_130440](https://user-images.githubusercontent.com/62869560/87911673-a5d8ca80-ca89-11ea-90c6-6b4b8bc24dbb.jpg)

+ Product & version: Fluxstore WooCommerce - Flutter E-commerce Full App 1.7.4
+ Testing Device: Samsung A7
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

I can not open the site http://verify.inspireui.com_ .... as it is saying IP address not found...so please tellme where i can submit the purchasing license for the same.

**Comment by minhcasi** [comment]
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission.  Thank you for your time!

**Comment by destek-harshadapatil** [comment]
Hello Inspireui/Support,

Thank you for your response. I tried the link you share with the email but
still it only shows the connecting option. the site is still not opening.
Please help me with this issue.

Thanks and regards

**Comment by destek-harshadapatil** [comment]
Here i am uploading the screenshot. Please check it or give me any alternative to share the license.

![Screenshot from 2020-07-20 16-37-59](https://user-images.githubusercontent.com/62869560/87931434-6d47e980-caa7-11ea-9c38-cc620c2604ef.png)

**Comment by destek-harshadapatil** [comment]
And I am also facing the issue with checkout process. As the process can not get completed.So please help me with the issues ASAP. I have attached the image for same here.

![20200720_164335](https://user-images.githubusercontent.com/62869560/87931970-5229a980-caa8-11ea-9394-64f0fa766ecc.jpg)

Thanks and Regards.

**Comment by ameenbadri7** [comment]
https://accounts.google.com/signin/v2/identifier?service=wise&passive=1209600&continue=https%3A%2F%2Fdocs.google.com%2Fforms%2Fd%2Fe%2F1FAIpQLScWOjkAJIWJ9rgb9alopfOqLsJrGKbFM5cCYj1JBfLKLsBblQ%2Fviewform&followup=https%3A%2F%2Fdocs.google.com%2Fforms%2Fd%2Fe%2F1FAIpQLScWOjkAJIWJ9rgb9alopfOqLsJrGKbFM5cCYj1JBfLKLsBblQ%2Fviewform&ltmpl=forms&flowName=GlifWebSignIn&flowEntry=ServiceLogin


go here and sign your email and continue.

**Comment by destek-harshadapatil** [comment]
Thank you team for your response. I have shared the details on above
support ticket website.

Thanks and Regards



‪On Mon, Jul 20, 2020 at 11:39 PM ‫amin badri أمين بدري‬‎ <
notifications@github.com> wrote:‬

**Comment by minhcasi** [comment]
1. you could fix the color vertical by adding this code
<img width="1180" alt="Screen Shot 2020-07-22 at 11 14 39" src="https://user-images.githubusercontent.com/1459805/88133569-9afa7300-cc0c-11ea-87df-310603314532.png">

2. pls double-check the shipping setting from your woocommerce site, example:
<img width="1274" alt="Screen Shot 2020-07-22 at 11 16 25" src="https://user-images.githubusercontent.com/1459805/88133654-cb421180-cc0c-11ea-9524-af858cb3e2a1.png">

**Comment by destek-harshadapatil** [comment]
Thank you team ! 
I have done the changes and its working fine.

**Comment by ameenbadri7** [comment]
You could help us by giving your feedback/rating to [Codecanyon Market website](https://codecanyon.net/downloads), 
we are working hard to update more awesome and powerful features on the next coming version release. 
Let us know if you have any feedback. 

Thank you very much ❤️

**Comment by destek-harshadapatil** [comment]
Sure, I will do that.

Thank you.



‪On Wed, Jul 22, 2020 at 7:06 PM ‫amin badri أمين بدري‬‎ <
notifications@github.com> wrote:‬

**Comment by ameenbadri7** [comment]
You are welcome  @destek-harshadapatil 

thank you ❤️

**Comment by destek-harshadapatil** [comment]
Hello Inspireui/Support,

I wanted to do some changes in UI and functionality part.
As I have shown in the image I want to add a color name after the colors
and next to it a counter so that if i select a particular color then I will
be able to add or remove the number of clothes of that type. If I press add
(+) then the counter increases from 0 to 1 and vice versa.
Please help me with this.

[image: IMG-20200729-WA0001.jpg]

Thanks and Regards,



‪On Wed, Jul 22, 2020 at 7:17 PM ‫amin badri أمين بدري‬‎ <
notifications@github.com> wrote:‬

**Comment by destek-harshadapatil** [comment]
Hello team,

I just wanted to ask that can I shift my project back end from woo-commerce to PHP ??
As I am Unable to do some customisation in woo-commerce so I wanted to use PHP as back end.
Please help me with this. And let me know how will it possible.
And if its possible then please let me know that which steps i have to follow.

Thanks & Regards.
