### ISSUE TITLE
Erro in build apk new version 1.7.6

### ISSUE THREAD

**Issue by daboujey** [inspireui/support#4276]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
+ Product & version: 1.7.6
+ Flutter (or React Native) version: 1.17.4
+ Testing Device/Simulator: Pixel 6
+ Screenshot issues (drag the file to attach here): 

Erro in compiler new version 1.7.6

![TELA DE ERRO 200720](https://user-images.githubusercontent.com/64880213/87929095-444e3700-ca5c-11ea-8d6f-f034e456c299.jpg)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by daboujey** [comment]
Now

![image](https://user-images.githubusercontent.com/64880213/87939328-4de09a80-ca6e-11ea-9479-e5e69e20f4f4.png)

**Comment by ameenbadri7** [comment]
please double check this guide to fix your problem.
https://github.com/inspireui/support/issues/3708
and this 
https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

**Comment by ameenbadri7** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved 
- thank you for your time!
