### ISSUE TITLE
VERY URGENT: Define ONLY one SHIPPING method for ALL Vendors (WCFM)

### ISSUE THREAD

**Issue by aishema2000** [inspireui/support#4279]
Purchase verification see ticket #3151 

My App has been finally published on Play store after 3 months of struggle. I am using MultiVendor App, But, I got a surpise. During Checkout, the user is asked to select shipping method based on the Vendor. I WANT  ONE SHIPPING METHOD FOR ALL VENDORS, BASED ONLY ON ADMIN SETTINGS, NOT shipping based on each vendor. ALL VENDORS WILL USE ONE SINGLE SHIPPING METHOD DEFINED IN WOOCOMMERCE SHIPPING SETTINGS

See screenshot
![EWEWEWWEWE](https://user-images.githubusercontent.com/15066381/87945699-67e7a080-caa1-11ea-9c42-55a6ba485ae4.png)

This is very urgent as my app has started being downloaded by a lot of users, How do I go for it?

**Comment by ameenbadri7** [comment]
Please note that we may not support answering or support technical issues for the regular license as per support policies - https://inspireui.com/support-policies/ 
- but we are trying to best to give extra miles with the supporting.

Thank you for your time sir.

**Comment by minhcasi** [comment]
@minhtruong315 - pls add the option config to allow switching 2 modes (default Woocommerce and vendor shipping)

**Comment by aishema2000** [comment]
Thank you so much @minhcasi . Waiting for @minhtruong315 kind support!

**Comment by minhtruong315** [comment]
Hi @aishema2000 check this solution
https://github.com/inspireui/support/issues/4196#issuecomment-661953567

**Comment by aishema2000** [comment]
Hi @minhtruong315 the solution you provided was perfect. Now i can assign a single shipping method to all vendors. Again thank you for your professionalism.
