### ISSUE TITLE
Apple Reject the App for Review for Apple Login Error

### ISSUE THREAD

**Issue by omman** [inspireui/support#4281]
Jul 20, 2020 at 3:57 PM
From Apple
2. 1 Performance: App Completeness
Guideline 2.1 - Performance - App Completeness

We discovered one or more bugs in your app when reviewed on iPhone and iPad running iOS 13.6 on Wi-Fi.

Specifically, an error message appears when user attempts to sign in with Sign In with Apple option.

Next Steps

To resolve this issue, please run your app on a device to identify any issues, then revise and resubmit your app for review.

If we misunderstood the intended behavior of your app, please reply to this message in Resolution Center to provide information on how these features were intended to work.

For new apps, uninstall all previous versions of your app from a device, then install and follow the steps to reproduce the issue. For updates, install the new version as an update to the previous version, then follow the steps to reproduce the issue.

Resources

For information about testing your app and preparing it for review, please see Technical Note [TN2431: App Testing Guide.](https://developer.apple.com/library/archive/technotes/tn2431/_index.html)

For a networking overview, please review [About Networking.](https://developer.apple.com/library/archive/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/Introduction/Introduction.html)

Guideline 2.1 - Information Needed

We have started your app's review, but we were unable to successfully access all or part of your app.

In order for us to continue the review, we need to have a way to verify all app features and functionality. Typically this is done by providing a demo account that has access to all features and functionality in your app. It is also acceptable to include a demonstration mode that exhibits your app’s full features and functionality. Note that providing a demo video showing your app in use is not enough for us to continue the review.

Next Steps

To help us proceed with the review of your app, please provide a user name and password in the App Review Information section of App Store Connect. Please be sure that the demo account includes content that demonstrates the features and functionality available in your app.

To provide demo account information:

- Log in to App Store Connect
- Click "My Apps"
- Select your app
- Click on the app version on the left side of the screen
- Scroll down to "App Review Information"
- Select the "Sign-in required" box
- Enter demo credentials in the "User name" and "Password" fields
- Once you've completed all changes, click the "Save" button at the top of the Version Information page

**Comment by omman** [comment]
Hi, Again Apple They Send Screenshot For this Error [Screenshot](https://iosapps-ssl.itunes.apple.com/itunes-assets/Purple114/v4/96/45/0c/96450c76-aa35-355f-f8e3-563d2045df6b/attachment.Screenshot-0720-131557.png?accessKey=1595538793_5974930179824745525_sxQUBxtmDLnkeogfqB2k67qsfNkqOTpULuFKqrYXeMsJCrh7LOHeM4aJC%2B1RgdSWX16d12gjkikt1CBA9Xx1wFDT4d%2FLkes1BqXHQ6CLl0r97n8Sy%2FzXLkFCshEmxjmIbphVPk6th28jOxcxe%2FPR7ZNknKesABE7alz3lpm9DtN1BOsUEfZ3EGUN4aqeZgkd)

**Comment by ameenbadri7** [comment]
Could you check the firebase setting and apple developers account setting that are mentioned inside this link :

https://medium.com/@inspireui?source=post_page-----8c767fe64e54---------------------

- Active the apple login from apple and firebase. 
- Firebase database .read and .write rules should be true. 
You will find them inside the database security rules. 
![84484683-842f3b00-acb4-11ea-836f-284e7130b5eb](https://user-images.githubusercontent.com/37524186/87998451-a6f90e80-cb00-11ea-9be7-de2314ed2c03.png)
![Uploading 84484589-6530a900-acb4-11ea-9b80-2e1cfbf225b7.png…]()

**Comment by ameenbadri7** [comment]
Could you check the firebase setting and apple developers account setting that are mentioned inside this link :

https://medium.com/@inspireui?source=post_page-----8c767fe64e54---------------------

- Active the apple login from apple and firebase. 
- Firebase database .read and .write rules should be true. 
You will find them inside the database security rules. 

![84484683-842f3b00-acb4-11ea-836f-284e7130b5eb](https://user-images.githubusercontent.com/37524186/87998583-0820e200-cb01-11ea-98b1-23bd3b93f4a0.png)
![84484589-6530a900-acb4-11ea-9b80-2e1cfbf225b7](https://user-images.githubusercontent.com/37524186/87998593-0b1bd280-cb01-11ea-93a7-6d464dc3ea02.png)

**Comment by omman** [comment]
Hi, There is another issue with new version 1.7.6 Not Showing again, My all categories also see all products not working.. I want to update my project 1.7.5 to 1.7.6 but i don't know how to fix this because last time this issue was fixed but when i am trying with updated version it's not working...Please check this bellow and tell me how to fix so that every time i will not ask for same issues.

- Problem No (1): Categories Limit 10
Site Categories List: https://i.imgur.com/O6rwwVu.jpg
Site Drawer showing only 10
Categories tab only showing 10
Filter Menu only showing 10
- Problem No (2): "See All" Not Working:
After Click "See All" No Product Shown

**Comment by omman** [comment]
https://github.com/inspireui/support/issues/4281#issuecomment-661611046 this issue i fixed with 

1) lib/services/woo_commerce.dart
1.6.4 code - `"products/categories?exclude=$kExcludedCategory&per_page=100&page=$page&hide_empty=true";`
Fix -  `"products/categories?categories_exclude=$kExcludedCategory&per_page=100&page=$page&hide_empty=true";`

2) lib/services/woo_commerce.dart
1.6.4 -  `if (categoryId != null) {`
Fix -  `if (categoryId != null && categoryId.isNotEmpty && categoryId.toString() != '0') {`

**Comment by omman** [comment]
Hi, I find a new issues which is showing all shipping method from woo-commerce from payment method zone,
I didn't enable 
`pickup from store` options,
 and `free delivery`

**Comment by ameenbadri7** [comment]
`Apple Reject the App for Review for Apple Login Error ` is this problem solved?

**Comment by omman** [comment]
@ameenbadri7 not yet because i think need to update 1.7.6

**Comment by omman** [comment]
**Hi, Please tell me how to fix this Issues with Version 1.7.6:**

- **No: 1 - `Showing all the payment method even in the website not enable but in mobile native screen all showing.`**
- **No: 2 - `When I purchase with card payment using second language web-view page not redirecting/showing also second Language. Always Redirecting / Showing default Website language.`**

Note:- I Need to update my app please tell me how to fix because old version there is lot of things not working also apple signin i have to check with latest version so please give me fixing code for fix this 2 issues.

Thanks.

**Comment by ameenbadri7** [comment]
**We updated out common files also:** 
**To fix issue 1:** 
I guess you have to change the `lib\common\config\payments.dart` to this:
/// Enable Payment option
  "EnableOnePageCheckout": true,
  "NativeOnePageCheckout": false,
If this not work with you please send us a screenshot to see your problem.

**To fix issue 2:** 
We have added new config on `lib\common\config\payments.dart` to show the multi-language checkout pages:
`  "CheckoutPageSlug": "checkout", 
`
change it to some like this:
//This config is same with checkout page slug in the website
  "CheckoutPageSlug": {"en": "en/checkout", "de": "kasse", "es": "es/confirmar"},
refer to [4273 issue](https://github.com/inspireui/support/issues/4273).


for issue: 3 - maybe your onboard setting is one the lib\config\config_en.json : 
add it like this : 

 ```
// after the search on the config file 
 "searchSuggestion": [
    "Fish",
    "Shrimp",
    "sea",
    "food"
  ],

// you add those 

"OnBoarding": {
    "data": [
      {
        "title": "Welcome to Fish Wasel Shop",
        "image": "assets/images/fogg-delivery-1.png",
        "desc": "Fish Wasel is on the way to serve you. ",
        "background": "#FFF3F2"
      },
      {
        "title": "Fresh Seafood",
        "image": "assets/images/fogg-uploading-1.png",
        "desc": "See all Our product you want by a click in your phone. Fast, convenient and clean.",
        "background": "#F2FFFC"
      },
      {
        "title": "Let's Get Started",
        "image": "fogg-order-completed.png",
        "desc": "Waiting no more, let's see what we get!",
        "background": "#F9F2FF"
      }
    ]
  }
```
**remember to remove my comments // because JSON files don't except comments.**

Or you can go to this ticket [to see it](https://github.com/inspireui/support/issues/3910).

please see our new updates on the documentation: 

[common-question](https://docs.inspireui.com/fluxstore/common-question/)
[common-issues]()https://docs.inspireui.com/fluxstore/common-issues/)

**Comment by omman** [comment]
Hi @ameenbadri7 please try understand 
No: 1 - Shipping method from woo-commerce from Shipping method zone, I didn't enable, but `**Pickup from store**` options, and `**Free delivery**` are showing all shipping method. sorry not payment method and we are using native payment screen so we use   /// Enable Payment option
  "EnableOnePageCheckout": false,
  "NativeOnePageCheckout": true,
[Screenshot: 1](https://imgur.com/YjTgOce)
[Screenshot: 2](https://imgur.com/z9pIhYT)

No: 2 - Still Same Problem not redirecting i am using this code:
```
  // "CheckoutPageSlug": "checkout",
  "CheckoutPageSlug": {"en": "checkout", "ar": "ar/checkout"},

```
No: 3 - Still Same Problem Not Showing My On boarding Screen it's Directly open home screen : here is my cod:
```
{
  "HorizonLayout":[
    {
      "layout":"logo",
      "showMenu":true,
      "showSearch":true,
      "showLogo":true
    },
    {
      "isSafeArea":true,
      "showSearch":false,
      "rotate":[
        "Fresh Vegetables",
        "Fresh Fruits",
        "Door to Door Home Delivery",
        "Weekly Pack Offer",
        "Special Offer",
        "Select Items & Buy Now"
      ],
      "type":"color",
      "height":0.13,
      "padding":30.0,
      "fontSize":23.0,
      "layout":"header_text"
    },
    {
      "layout":"header_search",
      "text":"Search for a product"
    },
    {
      "layout":"bannerImage",
      "isSlider":true,
      "autoPlay":true,
      "showNumber":false,
      "design":"default",
      "showBackGround":true,
      "padding":20.0,
      "radius":20.0,
      "items":[
        {
          "category":15,
          "image":"https://www.qutoof.qa/app/images/slider/s1_en.jpg"
        },
        {
          "category":205,
          "image":"https://www.qutoof.qa/app/images/slider/s2_en.jpg"
        },
        {
          "category":311,
          "image":"https://www.qutoof.qa/app/images/slider/s3_en.jpg"
        },
        {
          "category":204,
          "image":"https://www.qutoof.qa/app/images/slider/s4_en.jpg"
        }
      ]
    },
    {
      "layout":"bannerImage",
      "items":[
        {
          "category":213,
          "image":"https://www.qutoof.qa/app/images/banner/b1_en.jpg",
          "padding":15.0,
          "radius":20.0
        }
      ]
    }
  ],
  "Setting":{
    "MainColor":"#FB8C00",
    "ProductListLayout":"list",
    "StickyHeader":true
  },
  "TabBar":[
    {
      "layout":"home",
      "icon":"assets/icons/tabs/icon-home.png",
      "pos":100
    },
    {
      "layout":"category",
      "categoryLayout":"subCategories",
      "icon":"assets/icons/tabs/icon-category.png"
    },
    {
      "layout":"search",
      "icon":"assets/icons/tabs/icon-search.png",
      "pos":300,
      "url":"https://www.qutoof.qa",
      "title":"",
      "data":""
    },
    {
      "layout":"cart",
      "icon":"assets/icons/tabs/icon-cart2.png",
      "pos":400
    },
    {
      "layout":"profile",
      "icon":"assets/icons/tabs/icon-user.png",
      "pos":500,
      "settings":[
        "wishlist",
        "notifications",
        "language",
        "currencies",
        "order",
        "rating",
        "privacy",
        "about",
        "darkTheme"],
      "data":"",
      "url":"https://www.qutoof.qa",
      "title":"",
      "background":"null"
    }
  ],
  "Drawer":{
    "logo":null,
    "background":"assets/images/background/background-1.jpg",
    "items":[
      {
        "type":"home",
        "show":true
      },
      {
        "type":"blog",
        "show":false
      },
      {
        "type":"language",
        "show":true
      },
      {
        "type":"login",
        "show":true
      },
      {
        "type":"category",
        "show":true
      }
    ]
  },
  "Background":{
    "height":0.3,
    "image":"https://www.qutoof.qa/app/images/search/search_bg.jpg",
    "layout": "list"
  },
  "VerticalLayout":{
    "key":"thcld1ftf8",
    "layout":"list",
    "name":"All Items"},

  "searchSuggestion": [
    "Mango",
    "Apple",
    "Carrot",
    "Lemon",
    "Potato"
  ],

  "OnBoarding": {
    "data": [{
      "title": "Welcome to Qutoof",
      "image": "assets/images/fogg-delivery-1.png",
      "desc": "Stay home and leave it on us.",
      "background": "#FFF3F2"
    },
      {
        "title": "From all over the world",
        "image": "assets/images/fogg-uploading-1.png",
        "desc": "We make sure to bring you the best quality fresh products.",
        "background": "#F2FFFC"
      },
      {
        "title": "Let's Get Started",
        "image": "fogg-order-completed.png",
        "desc": "Waiting no more, let's see what we get!",
        "background": "#F9F2FF"
      }
    ]
  }
}
```

No: 4 - Today i got new issue after i update there some text font not changing when i change language and minimize application then rep-open. every time i have to clear cache then change translation. 


Note: Please give me your email so that i can send the source.
Thanks

**Comment by ameenbadri7** [comment]
Please send any thing in private Channels only via our main email 
minh@inspireui.com. 

Skype me we could fix your problem today if I have time. 
live:9867598668da2ddc

**Comment by omman** [comment]
Hi, Please check apple login issue [Screenshot](https://imgur.com/DOe1Qhe) ios apple store reject for this issue also ios sms invalid host error.

**Comment by omman** [comment]
Hi, @ameenbadri7 Please check my source and fix this [issues](https://github.com/inspireui/support/issues/4281#issuecomment-662782830)

**Comment by minhcasi** [comment]
@omman - please note that most of the issues you have raised related to your website integration, example #3536

As explained from the email, we could not provide to help to check on your site again as it has been taking us a lot of time, please help to get detail offer from our support policies - https://inspireui.com/support-policies/

Hope you could understand the situation here, thank you for your time!

**Comment by omman** [comment]
Hi, we submit a issue for common setting not customization why i will make extend license, this is a issue or bugs from your item problem. If not issue or bugs then we will extend or if we need customize from default fatures then but this is a issue for the item. Sorry we will not extend license for the issue. we can develop our own project flutter for woocommerce. And we will submit for the themeforest and complaign against the item why for the issue inspireui forcing to extend the license for the business. We pay for what. We have proof that when we buy item author said which is they shown to us it has all and they support for their default option only and customization fetures not in support, so my github issue not fix and i give my source with my business credintials.

**Comment by omman** [comment]
Hi, This issues/bugs is different from this issues [https://github.com/inspireui/support/issues/3536](https://github.com/inspireui/support/issues/3536) we checked already 
We need update for fix this issues that you said https://github.com/inspireui/support/issues/3825#issuecomment-657515245

No: 1 - Shipping method from woo-commerce from Shipping method zone, I didn't enable, but `**Pickup from store**` options, and `**Free delivery**` are showing all shipping method. sorry not payment method and we are using native payment screen so we use   /// Enable Payment option
  "EnableOnePageCheckout": false,
  "NativeOnePageCheckout": true,
[Screenshot: 1](https://imgur.com/YjTgOce)
[Screenshot: 2](https://imgur.com/z9pIhYT)

No: 2 - Still Same Problem not redirecting i am using this code:
```
  // "CheckoutPageSlug": "checkout",
  "CheckoutPageSlug": {"en": "checkout", "ar": "ar/checkout"},

```
No: 3 - Still Same Problem Not Showing My On boarding Screen it's Directly open home screen : here is my cod:
```
{
  "HorizonLayout":[
    {
      "layout":"logo",
      "showMenu":true,
      "showSearch":true,
      "showLogo":true
    },
    {
      "isSafeArea":true,
      "showSearch":false,
      "rotate":[
        "Fresh Vegetables",
        "Fresh Fruits",
        "Door to Door Home Delivery",
        "Weekly Pack Offer",
        "Special Offer",
        "Select Items & Buy Now"
      ],
      "type":"color",
      "height":0.13,
      "padding":30.0,
      "fontSize":23.0,
      "layout":"header_text"
    },
    {
      "layout":"header_search",
      "text":"Search for a product"
    },
    {
      "layout":"bannerImage",
      "isSlider":true,
      "autoPlay":true,
      "showNumber":false,
      "design":"default",
      "showBackGround":true,
      "padding":20.0,
      "radius":20.0,
      "items":[
        {
          "category":15,
          "image":"https://www.qutoof.qa/app/images/slider/s1_en.jpg"
        },
        {
          "category":205,
          "image":"https://www.qutoof.qa/app/images/slider/s2_en.jpg"
        },
        {
          "category":311,
          "image":"https://www.qutoof.qa/app/images/slider/s3_en.jpg"
        },
        {
          "category":204,
          "image":"https://www.qutoof.qa/app/images/slider/s4_en.jpg"
        }
      ]
    },
    {
      "layout":"bannerImage",
      "items":[
        {
          "category":213,
          "image":"https://www.qutoof.qa/app/images/banner/b1_en.jpg",
          "padding":15.0,
          "radius":20.0
        }
      ]
    }
  ],
  "Setting":{
    "MainColor":"#FB8C00",
    "ProductListLayout":"list",
    "StickyHeader":true
  },
  "TabBar":[
    {
      "layout":"home",
      "icon":"assets/icons/tabs/icon-home.png",
      "pos":100
    },
    {
      "layout":"category",
      "categoryLayout":"subCategories",
      "icon":"assets/icons/tabs/icon-category.png"
    },
    {
      "layout":"search",
      "icon":"assets/icons/tabs/icon-search.png",
      "pos":300,
      "url":"https://www.qutoof.qa",
      "title":"",
      "data":""
    },
    {
      "layout":"cart",
      "icon":"assets/icons/tabs/icon-cart2.png",
      "pos":400
    },
    {
      "layout":"profile",
      "icon":"assets/icons/tabs/icon-user.png",
      "pos":500,
      "settings":[
        "wishlist",
        "notifications",
        "language",
        "currencies",
        "order",
        "rating",
        "privacy",
        "about",
        "darkTheme"],
      "data":"",
      "url":"https://www.qutoof.qa",
      "title":"",
      "background":"null"
    }
  ],
  "Drawer":{
    "logo":null,
    "background":"assets/images/background/background-1.jpg",
    "items":[
      {
        "type":"home",
        "show":true
      },
      {
        "type":"blog",
        "show":false
      },
      {
        "type":"language",
        "show":true
      },
      {
        "type":"login",
        "show":true
      },
      {
        "type":"category",
        "show":true
      }
    ]
  },
  "Background":{
    "height":0.3,
    "image":"https://www.qutoof.qa/app/images/search/search_bg.jpg",
    "layout": "list"
  },
  "VerticalLayout":{
    "key":"thcld1ftf8",
    "layout":"list",
    "name":"All Items"},

  "searchSuggestion": [
    "Mango",
    "Apple",
    "Carrot",
    "Lemon",
    "Potato"
  ],

  "OnBoarding": {
    "data": [{
      "title": "Welcome to Qutoof",
      "image": "assets/images/fogg-delivery-1.png",
      "desc": "Stay home and leave it on us.",
      "background": "#FFF3F2"
    },
      {
        "title": "From all over the world",
        "image": "assets/images/fogg-uploading-1.png",
        "desc": "We make sure to bring you the best quality fresh products.",
        "background": "#F2FFFC"
      },
      {
        "title": "Let's Get Started",
        "image": "fogg-order-completed.png",
        "desc": "Waiting no more, let's see what we get!",
        "background": "#F9F2FF"
      }
    ]
  }
}
```

No: 4 - Today i got new issue after i update there some text font not changing when i change language and minimize application then rep-open. every time i have to clear cache then change translation. 

Thanks
