### ISSUE TITLE
Product Page list view not working

### ISSUE THREAD

**Issue by Benhur3000** [inspireui/support#4284]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues:  Product archive page won't display list view. Getting an error but all other views work.
+ Product & version: Fluxstore MV 1.7.6 
+ Flutter (or React Native) version: Flutter 1.17.5
+ Testing Device/Simulator: Android Samsung galaxy s10+ and Android studio Emulator and Fluxbuilder 
+ Screenshot issues (drag the file to attach here): 
![Screenshot_20200720-104524](https://user-images.githubusercontent.com/67126788/87964356-57223500-ca77-11ea-9dfd-3e06b4acc192.jpg)
![Screenshot_20200720-104838](https://user-images.githubusercontent.com/67126788/87964361-57bacb80-ca77-11ea-8d9a-82a8fc3e4a8f.jpg)
![Fluxbuilder](https://user-images.githubusercontent.com/67126788/87964362-58536200-ca77-11ea-9650-76a38f5f4042.PNG)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by ameenbadri7** [comment]
You could fix this by add new ratio config to config json file  inside lib\config

"Setting": {
    ...
    "ProductListLayout": "list",
    "ratioImageProduct": 2,
    "ratioInfoProduct": 1
    ...
  }

Try this and let us know about your project.  
Thank you

**Comment by Benhur3000** [comment]
Thanks for getting back to me. Unfortunately this code did not work.

**Comment by ameenbadri7** [comment]
As a temporary option to fix this issue until our team fix it , you can remove this option and keep the other 4 options. 
From `lib/common/constants/images.dart`

```
const kProductListLayout = [
  {"layout": "list", "image": "assets/icons/tabs/icon-list.png"},
  {"layout": "columns", "image": "assets/icons/tabs/icon-columns.png"},
  {"layout": "card", "image": "assets/icons/tabs/icon-card.png"},
  {"layout": "horizontal", "image": "assets/icons/tabs/icon-horizon.png"},
  {"layout": "listTile", "image": "assets/icons/tabs/icon-lists.png"},
];
```

To be like this : 
```
const kProductListLayout = [
  {"layout": "columns", "image": "assets/icons/tabs/icon-columns.png"},
  {"layout": "card", "image": "assets/icons/tabs/icon-card.png"},
  {"layout": "horizontal", "image": "assets/icons/tabs/icon-horizon.png"},
  {"layout": "listTile", "image": "assets/icons/tabs/icon-lists.png"},
];
```
Thank you for your time !

**Comment by Benhur3000** [comment]
The app is not live right now so I won't remove the option. I would like to see what the list view looks like however. Is there an ETA on when the next fluxstore update will be ready?

**Comment by minhcasi** [comment]
@Benhur3000 - we will update the latest version within this week - thank you!

**Comment by minhcasi** [comment]
we have released the latest version on gitlab - thank you!
