### ISSUE TITLE
Common issues to be resolved - Fluxstore for Woocommerce

### ISSUE THREAD

**Issue by akashsharnarthi** [inspireui/support#4285]
1) How do I change the loader/progress bar?
2) I have an existing app live on Playstore, So now how can I release an APK using the existing keystore file?

Thank you!

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support http://verify.inspireui.com/ 
- please don't share the purchase code or screenshot public here as another user will use it for activation.
We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 
Thank you for your time!

**Comment by akashsharnarthi** [comment]
I have submitted, please check and answer ASAP! 

Appreciated :)

**Comment by ameenbadri7** [comment]
We wanted to thank you for your patience during this busy time. 
We currently have reduced staff and a significantly higher volume of inquiries.

Please note that we will not support answering or support technical issues for the regular license as per support policies - https://inspireui.com/support-policies/ 

- But we are trying to best to give extra miles with the supporting

Thank you sir.

**Comment by minhcasi** [comment]
1. you could conifg this file
<img width="810" alt="Screen Shot 2020-07-22 at 11 11 34" src="https://user-images.githubusercontent.com/1459805/88133380-1dcefe00-cc0c-11ea-892b-d5675fb0a9a2.png">

2. Yes, you could use the same keystore file and same bundle ID 

Thank you so much for the rating :)

**Comment by minhcasi** [comment]
Let us know if you have any question 😊

**Comment by akashsharnarthi** [comment]
Yes, how can I add more options in Settings screen?
I have followed your docs but it doesn't showing the after installing the
apk
