### ISSUE TITLE
fluxstore mv home page 

### ISSUE THREAD

**Issue by ssathamenterprises** [inspireui/support#4286]
<img width="782" alt="proof of purchase" src="https://user-images.githubusercontent.com/68118999/88004476-aaf55280-cb39-11ea-940d-cbf546dfed56.PNG">

hello above is my proof of purchase

i have few issues please help on this 

1. in home page the products image are not perfect looks because of image size ( need to make batter view pls help this )
[
<img width="415" alt="1 issue" src="https://user-images.githubusercontent.com/68118999/88004677-15a68e00-cb3a-11ea-8d9a-f4af74176cab.PNG">
](url)

2. i want to change color for price and in stock ( both color how to change ) 
<img width="357" alt="2" src="https://user-images.githubusercontent.com/68118999/88004879-906fa900-cb3a-11ea-8ffe-7f4c2bda35d2.PNG">

3. where able to change this color ( please refer the image )

<img width="186" alt="3" src="https://user-images.githubusercontent.com/68118999/88004922-a67d6980-cb3a-11ea-9f51-a7bb7b532df2.PNG">

**Comment by minhcasi** [comment]
1. try to change the boxfit from product_card_view.dart - https://tppr.me/Spj8e
2-3. you could change the primary color from config_en.json - this could be done via fluxbuilder as well http://fluxbuilder.com/

Please note that we will not support answering or support technical issues for the regular license as per support policies - https://inspireui.com/support-policies/ - but we are trying to best to give extra miles with the supporting.
