### ISSUE TITLE
App showing blank after welcome screen

### ISSUE THREAD

**Issue by miskayapp** [inspireui/support#4289]
I cleared wp rest cache on wordpress, and my app dosent show anything after spash screen, i have reupload the previous config.en , but same thing
![188075E0-B17A-4C7E-B134-E9F6EDB57AD0](https://user-images.githubusercontent.com/64660378/88023254-a3797d80-cb28-11ea-9df6-33e96fda4a97.png)

**Comment by ameenbadri7** [comment]
you can debug your issue by disabling "isCaching": false,
 inside `lib\common\config\general.dart`.
if that not helping please try to rebuild your app and clean your build-cache before the build.
[Cleaning the cache](https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1
)
