### ISSUE TITLE
Help needed to reduce mstore pro APK size

### ISSUE THREAD

**Issue by lyrathaprinces** [inspireui/support#429]
Product: MstorePro
Your Purchased Code: e1c19d73-87c3-4bee-afb4-9451b95dbc45

Plz look at the size is f play store app,,,it's 30 mb,,,
My app after modifications,,APK size is 35 mb.
Is there any way to reduce the size,,, seriously the s is very serious issues,,,
Who wants keep app that eat up thier valuable memory,,,
Plz look into it asap,,
Thanks

**Comment by minhcasi** [comment]
Hey, the delivery under 100mb it still a small package size, we could not reduce it due to the core library of React Native - thanks
