### ISSUE TITLE
FluxBuilder Stuck on Loading.... in both MacBook & Windows PC

### ISSUE THREAD

**Issue by swapnildesai5** [inspireui/support#4291]
FluxBuilder is not logging in or sign up or any function in my both my macbook and windows there is an issue please resolve 

![Uploading IMG_20200721_131045.jpg…]()
![IMG_20200721_131042](https://user-images.githubusercontent.com/37268415/88042336-7347d400-cb54-11ea-9c62-7396add8407f.jpg)

**Comment by ameenbadri7** [comment]
hello, @swapnildesai5 welcome back.

uninstall your app and download the latest version `https://github.com/inspireui/fluxbuilder/releases/tag/v1.0.6 `
it's working perfectly.

**Comment by minhcasi** [comment]
@swapnildesai5 - there is any issue with our server on yesterday that it was stope on few hours, pls try to check again
