### ISSUE TITLE
Onboarding lottie is not working

### ISSUE THREAD

**Issue by Yusadolat** [inspireui/support#4292]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: Onboarding Lottie is not dislaying on build
+ Product & version: 3.0.6
+ Flutter (or React Native) version:  React Native
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 

Thank you for your time!

**Comment by Yusadolat** [comment]
I have filled the Form Already

**Comment by minhcasi** [comment]
@Yusadolat - would you mind to share the screenshot issues? Thank you!

**Comment by Yusadolat** [comment]
![WhatsApp Image 2020-07-22 at 04 58 14](https://user-images.githubusercontent.com/10975011/88132873-84d2bf80-cbd8-11ea-8aef-5b7e5a13093d.jpeg)

**Comment by Yusadolat** [comment]
After running react-native run-android --variant=release  once it installs everything else went blank.

**Comment by Yusadolat** [comment]
I just ran the command without release argument now, it went blank even on debug

**Comment by luyx2412** [comment]
Hi @Yusadolat I saw your screenshot which is Home screen, can you send me the screenshot onboarding screen?

Thanks

**Comment by Yusadolat** [comment]
Onboarding isn't included. That was what I was telling you.

**Comment by Yusadolat** [comment]
Even the Create post is not included in the download content.

**Comment by Yusadolat** [comment]
Sure, what exactly should I share?

**Comment by Yusadolat** [comment]
The files I downloaded from themeforest?

**Comment by luyx2412** [comment]
Hi @Yusadolat I saw your source code and it is old version, so please upgrade to latest version beonews 3.0.7.

Thanks

**Comment by Yusadolat** [comment]
Hi @luyx2412 How do I upgrade please?

**Comment by luyx2412** [comment]
Hi @Yusadolat I just email you about latest version.

Thanks

**Comment by Yusadolat** [comment]
Great,I will check right away. Thanks
