### ISSUE TITLE
fluxstore Ecommerce app issue 

### ISSUE THREAD

**Issue by Marwa229** [inspireui/support#4294]
![sc3](https://user-images.githubusercontent.com/59913375/88060444-911e3480-cb66-11ea-9959-9d564a2fff4b.jpg)
![sc2](https://user-images.githubusercontent.com/59913375/88060503-a72bf500-cb66-11ea-9891-f609de007397.jpg)
![sc1](https://user-images.githubusercontent.com/59913375/88060518-ab581280-cb66-11ea-9459-428af0032427.jpg)

+i need help in a real problem my product have 20% discount but only real price applied .could you help me to solve that issue please and i used points and rewards plugin my points appears correctly but i can't redeem my points in the checkout
+ Product & version:1.7.1+3001
+ Flutter v1.17.5
+ Testing Device/Simulator: my device samsung galaxy j5 prime
+ Screenshot issues (drag the file to attach here):

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 

Thank you for your time!

**Comment by minhcasi** [comment]
@Marwa229 - thank you for reporting, we will have a check on the coupon issue - but the redeem the points will be upgraded later

**Comment by simonpham** [comment]
Hi @Marwa229,

The discount problem has been fixed in version 1.7.7. We will release this in 1-2 days. Since then, you can download the new version on GitLab.

Thank you for using our products.

**Comment by Marwa229** [comment]
> Hi @Marwa229,
> 
> The discount problem has been fixed in version 1.7.7. We will release this in 1-2 days. Since then, you can download the new version on GitLab.
> 
> Thank you for using our products.

ok, Thanks alot but i have been working on my project and i made so many changes how could i update without affecting my work ?

**Comment by simonpham** [comment]
@Marwa229 you should use a VCS (Version control systems) such as Git to manage your changes to the project.

**Comment by simonpham** [comment]
@Marwa229 you can check out this article, we have a tutorial on how to upgrade FluxStore using Git.

[https://medium.com/@inspireui/how-to-upgrade-fluxstore-projects-by-using-git-cebde7489ea6](https://medium.com/@inspireui/how-to-upgrade-fluxstore-projects-by-using-git-cebde7489ea6)
