### ISSUE TITLE
Social login Issue with AppleSignin and Google signin in IOS

### ISSUE THREAD

**Issue by easieber** [inspireui/support#4295]
Currently i am having a problem with Apple Login and google login that i had not before here a video so you can see the behaviour of both login process. Some idea?

Video: https://recordit.co/Sk91xkBxI8

**Comment by ameenbadri7** [comment]
hello, @easieber welcome back.

I have a tip maybe it could help you.

Yesterday I received a massage after 30 days of using firebase in test mode, you will have messages inside your connected email that will say we stopped the test development for your database. 

They set the database to `read: false, wright: false.` could you go to the firebase setting and see the database security rules. 
is it read true write true or not!

Sure if that's not helping pls double-check the firebase setting from Firebase - also have a look to our document guide https://docs.inspireui.com/fluxstore/sign-in/

Thank you.

**Comment by easieber** [comment]
Hello,

I am not sure where to check this firebase database as i am not using a database there (i went to the database section and actually i need to create one to activate that) but in your documentation there is nothing related to create a database there... I went thru your documentation again in the signin with social media and i did the steps again and nothing.. for example in android login with google and facebook is working and in ios only facebook is working.. i can see that in ios is more a permission error but google signin close the app automatically and that is weird... but so far no solution.

**Comment by minhcasi** [comment]
@easieber - you could try to use other testing apple account and login to see if it is working?

**Comment by easieber** [comment]
@minhcasi with apple sign in is working now, i tried with the @cloud.com email that they offer and it worked, then back again with mine and all good. But google Signin still crash my app... i dont know if it is firebase because the push notifications and facebook login is working fine.

**Comment by easieber** [comment]
ok about google sign in i found the issue @minhcasi ineed to add the new `REVERSED_CLIENT_ID` of the Google Service-Info.plist to the URL Types scheme in the runner of the ios. There was another ulr. I assume that it didnt update after i change the Google Service-Info.plist. I still keep the old one because i dont know if i remove it i break my app. 😅  But here was the problem.

**Comment by easieber** [comment]
@minhcasi btw, how can i add some padding to the privacy Terms and blogs pages?? the text is not so pretty and go until the borders of the screens, in this curved phones it is hard to read when you embed this text from posts and pages

**Comment by minhcasi** [comment]
@easieber - we suggest to use the Inspector to customize any UI from the app - https://www.youtube.com/watch?v=yGMt3Y20Zmg

Pls help us to use one open ticket and add your all comments, instead of creating multi one  - thank you!

**Comment by minhcasi** [comment]
#4316
