### ISSUE TITLE
getting exception after adding address 

### ISSUE THREAD

**Issue by codex-pro** [inspireui/support#4296]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: getting exception after adding address .exception please select state region 

![Screenshot 2020-07-21 at 9 16 10 PM](https://user-images.githubusercontent.com/51110842/88076198-67c9cc80-cb97-11ea-9944-231b14aa3405.png)

+ Product & version:fluxtore updated verion 
+ Flutter (or React Native) version: flutter updated version
+ Testing Device/Simulator: Pixel 2 api 28
+ Screenshot issues (drag the file to attach here): 
added

**Comment by ameenbadri7** [comment]
Please note that we may not support answering or support technical issues for the regular license as per support policies - https://inspireui.com/support-policies/ 
- but we are trying to best to give extra miles with the supporting.

**Comment by minhcasi** [comment]
The state/city did not select from your previous screen that causes the issue

pls help to give your all comment to the one open ticket support #4233
