### ISSUE TITLE
Build Error - mStore Multi Vendor

### ISSUE THREAD

**Issue by maheshrayudu** [inspireui/support#4297]
Applicaiton is not building at all based on documentation that is provided in the site.
<img width="1680" alt="Screen Shot 2020-07-21 at 9 43 11 AM" src="https://user-images.githubusercontent.com/25511479/88079732-bfd6e380-cb43-11ea-90db-6a69620d0504.png">

Can you please provide what would be my next steps?

**Comment by ameenbadri7** [comment]
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.
We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by hdecode** [comment]
I got the same thing, I pass it by `npm install grpc -g`

**Comment by maheshrayudu** [comment]
Hi ameenbadri7 - The above-noted link is unknown, Can you please provide a valid link? Thank you

**Comment by maheshrayudu** [comment]
Hi minhcasi - Can you please provide what information you still waiting on? Thank you

**Comment by hdecode** [comment]
I got another answer from my issue, You need to build with nodejs 10 :( @maheshrayudu

**Comment by minhcasi** [comment]
@maheshrayudu - there is an issue with the nodejs 12.x and 13.x - please try to use nodejs 10.x - https://nodejs.org/dist/latest-v10.x/

**Comment by maheshrayudu** [comment]
Thanks for the suggestion. Application successfully build on nodejs10.
Getting the below error:

SyntaxError: <app root folder>/src/Router.js: Support for the experimental syntax 'decorators-legacy' isn't currently enabled (23:1):

  21 | import { toast, closeDrawer, Reactotron } from "./Omni";
  22 | 
> 23 | @withTheme
     | ^
  24 | class Router extends React.PureComponent {
  25 |   state = {
  26 |     loading: true,
Failed building JavaScript bundle.

**Comment by minhcasi** [comment]
@maheshrayudu - please have a check if you have removed any hidden file from the download package?

**Comment by maheshrayudu** [comment]
it worked with latest code download.
