### ISSUE TITLE
MV FluxStore 1.7.6

### ISSUE THREAD

**Issue by enriqueleon80** [inspireui/support#4298]
Hello,

In reviewing some issues submitted by other customers I saw one talking about MV STORE version 1.7.6.  However, as far as I can tell this version hasn't been released or has it?

If it hasn't any idea when we can expect it? Or if it's already out I suspect it's the code available on the GITLAB repo.

Thanks!
 
ELEON

**Comment by ameenbadri7** [comment]
Please help to submit access to http://gitlab.inspireui.com .
![20200722_013848](https://user-images.githubusercontent.com/37524186/88114298-3dd6d100-cbbc-11ea-8ddd-5d86f0c9742f.jpg)

Its now `release pre-1.7.6`.

**Comment by enriqueleon80** [comment]
> Please help to submit access to http://gitlab.inspireui.com .
> ![20200722_013848](https://user-images.githubusercontent.com/37524186/88114298-3dd6d100-cbbc-11ea-8ddd-5d86f0c9742f.jpg)
> 
> Its now `release pre-1.7.6`.
> 
> > **[Google Forms - create and analyze surveys, for free.](http://gitlab.inspireui.com/)**Create a new survey on your own or with others at the same time. Choose from a variety of survey types and analyze results in Google Forms. Free from Google.

Note sure I understand your comment? It's pre 1.7.6 which means it's not a full 1.7.6 release, as far as I can see?

**Comment by ameenbadri7** [comment]
Hi,
It seems there is a lot of bugs in version 1.7.5 but most of them we've already solved at the latest version. 
Please consider using GitLab to pull the pre-release 1.7.6 version or wait for the update on Codecanyon in a couple of days.

Thank you.

**Comment by ameenbadri7** [comment]
I'm sorry to close this ticket as there is no response or active conversation.

Please help to create a new one and link it to this ticket if the problem is not solved.

thank you for your time ❤️
