### ISSUE TITLE
Register screen issue

### ISSUE THREAD

**Issue by jvsamoa** [inspireui/support#4299]
Hi,

I have the following issue: my register screen is showing this message: "overflowed right XX pixels"
![image](https://user-images.githubusercontent.com/25646978/88096071-61872080-cb96-11ea-9425-db8fd62c5b84.png)

Aditional please can you explain me how I can redirect (when i press Shop menu item) to categories?

**Comment by jvsamoa** [comment]
Hi, 
I need to change this whitespace, but when I tried to update Fluxstore to 1.7.6 I have a lot of issues again and I need finish this project. 

Thanks a lot
![image](https://user-images.githubusercontent.com/25646978/88136743-362e2100-cbea-11ea-8002-b114db19aabc.png)

**Comment by ameenbadri7** [comment]
[How to Customize any UI from App](https://docs.inspireui.com/fluxstore/customization/#1-how-to-customize-any-ui-from-app).

thank you sir.

**Comment by jvsamoa** [comment]
To you Master.

Another question. 
Have you any solution for:
![image](https://user-images.githubusercontent.com/25646978/88200611-ae2a3480-cc46-11ea-9635-1bb36641c73d.png)

It's not a customization.
Pls
Regards

**Comment by ameenbadri7** [comment]
whats happened is the translation for the word (   "agreeWithPrivacy": "Acuerdo de Privacidad",) inside es file on `lib\l10n\intl_es.arb` is to big. you can change it to a shortcut name like: de Privacidad.
Btw: 
To fix it you have a lot of ways: 
go to `lib\screens\users\registration.dart` on line 183
you will find : 
```
 Row(
                          children: <Widget>[
                            Checkbox(
                              value: isChecked,
                            ...........................................
```

change the Row to Wrap it will fix your issue.

```
 Wrap(
                          children: <Widget>[
                            Checkbox(
                              value: isChecked,
                            ...........................................
```

If you use the inspector you could know all that on your own.

Thank you sir.

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
