### ISSUE TITLE
No such module ‘one signal’

### ISSUE THREAD

**Issue by miskayapp** [inspireui/support#4300]
When i try to build or archive, i get this error no such module onesignal
![9827746D-118C-4B56-B3CB-6AB8F6B99B3E](https://user-images.githubusercontent.com/64660378/88113405-a49ebf00-cba9-11ea-849e-29479a64995a.jpeg)

**Comment by ameenbadri7** [comment]
We have tested twice before releasing the package, please try to clean up the cache by following this solution https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1 

Please notes that we may not support answering some technical questions for the regular license as per support policies - https://inspireui.com/support-policies/ 
- But we are trying to best to give extra miles with the supporting.
Hope you enjoy the product. 

- Thank you!

**Comment by miskayapp** [comment]
i cant open the link shared

‪On Tue, Jul 21, 2020 at 11:58 PM ‫amin badri أمين بدري‬‎ <
notifications@github.com> wrote:‬

**Comment by ameenbadri7** [comment]
https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1%C2%A

https://inspireui.com/support-policies/%C2%A0

Copy them to your browser to open it !

**Comment by miskayapp** [comment]
this is the error i'm getting now 

[!] Could not automatically select an Xcode workspace. Specify one in your Podfile like so:

    workspace 'path/to/Workspace.xcworkspace'


[!] The Podfile does not contain any dependencies.
