### ISSUE TITLE
States are not getting fetched from opencart 

### ISSUE THREAD

**Issue by umargigani** [inspireui/support#4301]
i already opened 2 tickets
#4066 
#3396 
After this update in change log i can see states fetch and saved in website using rest api

but i uninstalled old extension and installed new one from latest version from code canoyan store

getting this issues not done any edits just changed the source from woo to opencart 

![Untitled](https://user-images.githubusercontent.com/22342007/88120190-feba7700-cbdf-11ea-94ff-03d0d6e5e5a4.png)

**Comment by minhtruong315** [comment]
@umargigani can u send me your website?

**Comment by umargigani** [comment]
you need admin access?

**Comment by minhtruong315** [comment]
Yes. send me admin account info via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/4301

**Comment by umargigani** [comment]
done email sent

**Comment by umargigani** [comment]
any updates?

**Comment by minhtruong315** [comment]
@umargigani I'm checking. I will let u know today.
Thanks

**Comment by umargigani** [comment]
ok

**Comment by minhtruong315** [comment]
Hi @umargigani Did you set DefaultCountryISOCode in common/payments.dart like this?
```"DefaultCountryISOCode": "IN",```

**Comment by umargigani** [comment]
no i didnt edited a thing in app just downloaded latest version from code canyon website and install new api and changed config file from woo to oc that it

**Comment by umargigani** [comment]
my store db have only india

**Comment by umargigani** [comment]
i guess dont bother now with any thing we are planning to switch from oc to woo soon so its not the point taking a headache
will update u when we get any issue while using woo with your app 
thank you for your support
