### ISSUE TITLE
Shopify - Product not showing up when you access them the second time and others for the first time

### ISSUE THREAD

**Issue by RogerantTshibangu** [inspireui/support#4302]
+Detail Issues: When I click on any category after opening the app, I get product list for the first time but when I refresh or click on it again on the same category nothing displays, (it display no products) and the same for any other categories too, after opening app product is displayed once then it disappears.
the only modification I did is the website domain and the access key, i just purchase this project (that mean it is latest)
Am I missing something?
(my problem is similar to #3949 and #4093 #4213 )

Product & Version: Version: 1.7.5 and its Fluxstore Shopify
Flutter (or React Native) version: Flutter

Screenshot issues (drag the file to attach here):
![WhatsApp Image 2020-07-22 at 02 24 42](https://user-images.githubusercontent.com/66641456/88120492-51396a80-cbc3-11ea-9b96-d977411f95a8.jpeg)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by luyx2412** [comment]
Hi @RogerantTshibangu I just invited you to fluxshopifuy latest version repo, so please merge with your code which fixed the issue.

Thanks

**Comment by RogerantTshibangu** [comment]
Hi @luyx2412 I just downloaded the latest version as requested and merged it with my code but the bug is not fixed. 
It is still doing the same thing.

**Comment by RogerantTshibangu** [comment]
Thank you I am sorted, all fixed.
