### ISSUE TITLE
products didnot show

### ISSUE THREAD

**Issue by ANaSHaker** [inspireui/support#4303]
**_Step 1 (require): describe detail issues & screenshots_**
hi i used fluxstore shopify and i have 3 problems in it

1- recent collection show (loading) but no show products
and i try it in fluxbuilder and it worked and when i take the code and try it not working

![WhatsApp Image 2020-07-22 at 3 51 36 AM](https://user-images.githubusercontent.com/54468670/88125424-9368a900-cbcf-11ea-9807-ee3cfb6b8f33.jpeg)

2- when i open any catagory show that there is no catagory
and also i try it in fluxbuilder and it worked and when i take the code and try it not working

![WhatsApp Image 2020-07-22 at 3 51 36 AM (1)](https://user-images.githubusercontent.com/54468670/88125465-a7aca600-cbcf-11ea-8078-edf29fee0d32.jpeg)

3- sidemenu in catagory page stop in loading and not continue 
and also i try it in fluxbuilder and it worked and when i take the code and try it not working

![WhatsApp Image 2020-07-22 at 3 51 36 AM (2)](https://user-images.githubusercontent.com/54468670/88125488-aed3b400-cbcf-11ea-95d0-914cbc2d2f57.jpeg)

**_Step 2 (require): submit proof of purchasing the license on (http://verify.inspireui.com)_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by ANaSHaker** [comment]
step 2 done also

i hope you help me quickly

**Comment by minhcasi** [comment]
@ANaSHaker - pls help to submit again as we could not get the form of your ticket - thank you for your time!

https://docs.google.com/forms/d/e/1FAIpQLScWOjkAJIWJ9rgb9alopfOqLsJrGKbFM5cCYj1JBfLKLsBblQ/viewform

**Comment by ANaSHaker** [comment]
i submit it again 

i just have a question 

what will happen now ? do you will try to solve the problem in your desktop then send me the correct files

or you will just see the files which i sent and then open team viewer with me and solve it in my computer 

and thank you for your time

**Comment by ANaSHaker** [comment]
So !?

**Comment by minhcasi** [comment]
@ANaSHaker - thank you for quick response, we're checking your product issue and will get back shortly - thank you!

@luyx2412 - pls help with checking

**Comment by ANaSHaker** [comment]
Ok

**Comment by luyx2412** [comment]
Hi @ANaSHaker I just invited you the latest Fluxshopify repo. Please merge with your code which fixed this issue.

Thanks

**Comment by ANaSHaker** [comment]
Ah i didnot recieve any thing in gitlab or github or i my email

Are you sure !?
This is my email

Gustblack36@gmail.com

And thank you for solving it by the way

**Comment by ANaSHaker** [comment]
???

**Comment by ANaSHaker** [comment]
Hay @luyx2412 
Where are you

**Comment by luyx2412** [comment]
HI @ANaSHaker I am here, i just invited Gustblack36@gmail.com to fluxshopify latest version repo. Please merge with your code which fixed the issue.

Thanks

**Comment by ANaSHaker** [comment]
hi merge it and problem 1 and 2 which i send didnot work 

only 3 solved

**Comment by ANaSHaker** [comment]
i know you are busy but i hope you help me more quickly because that's only what i wait to publish the app in the store

**Comment by ANaSHaker** [comment]
@luyx2412  @minhcasi 

There is also new problem i desover it now

I cannot do payment 
When i try thats what happen
![Screenshot_٢٠٢٠٠٧٢٦-٠٦٢٥١٠](https://user-images.githubusercontent.com/54468670/88471369-f5dfe300-cf08-11ea-9db7-0b168e0b73a6.jpg)

**Comment by luyx2412** [comment]
Hi @ANaSHaker Please pull latest code in Fluxshopify repo which was invited you. 
- With the native credit card payment, please read the article https://community.shopify.com/c/Shopify-APIs-SDKs/CheckoutCompleteWithCreditCardV2-access-denied/m-p/567430/highlight/true#M37756. 

Thanks

**Comment by ANaSHaker** [comment]
i did it and pull latest code which you send it to me in gitlab

for payment ok i will see what you send thank you

but please help me in the first problem

**Comment by ANaSHaker** [comment]
؟؟؟

**Comment by ANaSHaker** [comment]
@luyx2412 @minhcasi

**Comment by minhcasi** [comment]
@ANaSHaker - We sincerely apologize for the delay and hope you’re staying safe.

Could I confirm you still have the issue with Recent Collection, do you setup it load from the category or from the Navigation History?

**Comment by luyx2412** [comment]
Hi @ANaSHaker Please pull latest code in Fluxshopify repo which fixed your first issue.

Thanks

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
