### ISSUE TITLE
Activation Problem on MStore API 2.3.9

### ISSUE THREAD

**Issue by maruata** [inspireui/support#4304]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: I cannot activate the MStore API
+ Product & version: 2.3.9 MStore API
+ Flutter (or React Native) version: Flutter
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 
![error](https://user-images.githubusercontent.com/57096001/88131917-bd37c500-cbfb-11ea-845e-adb40d2c3eac.PNG)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**
![pop](https://user-images.githubusercontent.com/57096001/88132011-fa03bc00-cbfb-11ea-9251-c294d01d019f.PNG)

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@maruata - please help to update to latest mstore-api from the Wordpress plugins to fix this issue - 

Also, help us to raise your all question to one open ticket - thank you!

**Comment by minhcasi** [comment]
#4306

**Comment by maruata** [comment]
> @maruata - please help to update to latest mstore-api from the Wordpress plugins to fix this issue -
> 
> Also, help us to raise your all question to one open ticket - thank you!

The update is not shown in the wordpress. Do I need to wait for more time.
