### ISSUE TITLE
some questions for flux-store multi vendor 

### ISSUE THREAD

**Issue by ahmedemad2345** [inspireui/support#4307]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
+ Product & version: fluxstore multi vendor with dokan plugin
+ Flutter (or React Native) version: flutter
+ Testing Device/Simulator: both
+ Screenshot issues (drag the file to attach here): 

hello I'm working to add more features to this app and its working well but I have some questions and hope you will explain them 

1-how to exclude some categories from categories page based on the language so when I select the English language I need showing only English categories and when I change the language to Arabic, for example, I want only Arabic categories appears because there are different product in the site and we don't need to use wpml or any multilanguage plugin  

2- I have made a new case in the tab bar to duplicate the home screen and categories screen because I want to add one screen for categories only and another one to stores only and remove the tab button in the header for the two screens and if it possible to add heading text instead of them  

also if possible to change the stores screen layout, I want to make them as a two-column

3- I need some information to add a new ststic screen and connect it with the static screen I have added to the tab bar 
also I need this for HTML page and web view page 

4- in the home page I have replaced the search icon in the header with shopping cart icon and navigate this to the cart screen and its work very well but when I add some product to the cart the number of the products in the cart not appear in the icon with red background circle as happened to that icon in the tab bar also the back to home button not working after i moved this screen to the header

5- how can I add new web view screen like about us screen and add this screen with a custom name to open new URL page

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by ameenbadri7** [comment]
We currently have reduced staff and a significantly higher volume of inquiries. We’re working as hard as we can to get our customer's requests as soon as possible.
We sincerely apologize for not answering this issue as it is related to the customization that will not include from our support scope, pls help to check our support policies on [this page](https://codecanyon.net/item/fluxstore-multi-vendor-flutter-ecommerce-full-app/25013325/support).

 
But let me note that that questions you ask can be solved if you just read our [documentation website](https://docs.inspireui.com/fluxstore/) 👍

Please read it and customize your site as you like.

You can buy the [Extended License](https://inspireui.com/support-policies) or Support Pack and email us with your request via our email minhcasi@gmail.com and inspireui-team@inspireui.com.

**Comment by ahmedemad2345** [comment]
Hello thank you for reply 
I'm sad to here this for the support policy, i think you should highlight it in the product page.
Also i don't need to customize my app 
I want to know where's the file should i edit to make these changes and tell me if these edits possible or not 
I think these answers are my right so please reply with clear answers

**Comment by ameenbadri7** [comment]
Don't worry @Ahmed I will assist you directly to get knowledge about our app. 
Also in arabic language. 
Add me on skype:  9867598668da2ddc

**Comment by ahmedemad2345** [comment]
Ok thank you, i sent you check your Skype

**Comment by ahmedemad2345** [comment]
I'm waiting above 12 hours 
I sent you on Skype

**Comment by ahmedemad2345** [comment]
@ameenbadri7 can you check your Skype please
