### ISSUE TITLE
Link App to My Listing Website

### ISSUE THREAD

**Issue by nuhouse** [inspireui/support#4308]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: Hello I have installed everything and it is all working fine, I want to link the code to my website & not use the demo content, can you advise how i do that. My website is https://esdauk.co.uk/

This website is a listing wordpress website & has all its own core functionality so i just want it to operate as it does responsively

+ Product & version: Latest
+ Flutter (or React Native) version: Latest
+ Testing Device/Simulator: Ios & Android
+ Screenshot issues (drag the file to attach here): None Yet

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**
Purchase Code: 4b3a2435-f3a7-4602-a90b-c5b498998a84 

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by nuhouse** [comment]
Hello I submitted the form now, please let me know if you need any further information.

**Comment by minhcasi** [comment]
@nuhouse - after config, the plugin on your site then copy the config into config.dart to connect the app to your own website, please help to use this guide https://docs.inspireui.com/fluxstore/listing-directory/#3-setup-your-own-website

**Comment by minhcasi** [comment]
Hi sir, let us know if you have any questions. 

Feel free to reopen the ticket or post the new one if you have any queries

**Comment by nuhouse** [comment]
Hello,

I am still in the process of setting this up, can you advise where i will get:

Issue 1:

  "consumerKey": "ck_58c3f8cac9c5cd7e15b2bd334824de69fc0f802f",

  "consumerSecret": "cs_c2d4411dfd71a94075158684abd6b903e0a0a1da”,

For step 3 of the setup


Issue 2:
I am linking to a current website https://esdauk.co.uk/ <https://esdauk.co.uk/> My homepage is a page & not populated with only a category

Open lib/common/config_xx.json. Under the HorizonLayout is the setting to display the homepage layout, replace the category with your own category ID (this ID can get when editting from the category in admin site):


Can you advise what step i should start at here: https://docs.inspireui.com/fluxstore/listing-directory/#step-3-setup-listing-website <https://docs.inspireui.com/fluxstore/listing-directory/#step-3-setup-listing-website>

I am linking to my wordpress theme which is not one of your listed themes but is supported as i messaged you before i purchased & you said it was supported.

My site is here: https://esdauk.co.uk/ <https://esdauk.co.uk/>

My theme is: https://mylistingtheme.com/ <https://mylistingtheme.com/>


Thanks
Andre Clarke

P: 086 1596040
E: andre@nuhouse.ie <mailto:andre@nuhouse.ie>
W: www.nuhouse.ie <http://www.nuhouse.ie/>

 <http://www.nuhouse.ie/>

 <https://www.facebook.com/nuhouse.ie/>  <https://www.linkedin.com/company/nuhouse-design> 

   

The information contained in this message and or attachments is intended only for the person or entity to which it is addressed and may contain confidential information and or privileged material. Any review, retransmission, dissemination or other use of, or taking of any action in reliance upon, this information by persons or entities other than the intended recipient is prohibited. If you received this in error please contact the sender and delete the material from any system and destroy any copies.

**Comment by nuhouse** [comment]
Hello I have replied already but i need urgent help.

I am trying to link it to my wordpress website.

Can you send me the instructions on how to link it only to my wordpress website.

The instructions seem to be to link it to the demo information which i do not want to link to.

When i have all the amends done i presume i will be able to see my app in the simulator???

Which i cannot do now.

This is quite urgent as i need to get everything done by tuesday.



Thanks
Andre Clarke

P: 086 1596040
E: andre@nuhouse.ie <mailto:andre@nuhouse.ie>
W: www.nuhouse.ie <http://www.nuhouse.ie/>

 <http://www.nuhouse.ie/>

 <https://www.facebook.com/nuhouse.ie/>  <https://www.linkedin.com/company/nuhouse-design> 

   

The information contained in this message and or attachments is intended only for the person or entity to which it is addressed and may contain confidential information and or privileged material. Any review, retransmission, dissemination or other use of, or taking of any action in reliance upon, this information by persons or entities other than the intended recipient is prohibited. If you received this in error please contact the sender and delete the material from any system and destroy any copies.
