### ISSUE TITLE
Request to Gitlab repo access.

### ISSUE THREAD

**Issue by kpmulillyc** [inspireui/support#4309]
I have submitted the request form to gitlab.inspireui.com and sent an email to minhcasi@gmail.com weeks ago. 
Have not received email nor any notifications yet. Can someone help ?

Thanks

**Comment by minhcasi** [comment]
@kpmulillyc - could i know your email submit pls

**Comment by minhcasi** [comment]
it's sent - pls help to check again - thank you!
