### ISSUE TITLE
When I Open Fresh Code Downloaded Of Fluxstore Multi Vendor for the first time

### ISSUE THREAD

**Issue by GNAG1993** [inspireui/support#4310]
+ Detail Issues: 
When I open the source code for the first time, why does it happen. More than 13k errors?
+ Product & version: Fluxstore Multivendor (1.7.5)

![001](https://user-images.githubusercontent.com/58203387/88144852-68ba2880-cbae-11ea-84ba-f612309df1ed.png)

**Comment by minhcasi** [comment]
<img width="579" alt="Screen Shot 2020-07-22 at 17 16 49" src="https://user-images.githubusercontent.com/1459805/88164967-22f97080-cc3f-11ea-825f-f7d4e07b44e1.png">

@GNAG1993 - pls try to remove this line from the `pubspec.yaml` to fix the issue

**Comment by GNAG1993** [comment]
ok, let me try

**Comment by GNAG1993** [comment]
now I'm getting a new issue,
gradle tasks ends with an error:
Exception: Gradle task assembleDebug failed with exit code -1

**Comment by minhcasi** [comment]
@GNAG1993  - pls try with the latest one from Gitlab 👍

**Comment by minhcasi** [comment]
Also latest download source on Envato - thank you!
