### ISSUE TITLE
2 Issues in checkout, Total order's value must be at least and Error in format exception, Invalid double

### ISSUE THREAD

**Issue by nucl123** [inspireui/support#4313]
Hi,
we are facing 2 issues in checkout,
1. There is a message which allows only 100$+ purchases, how can we disable this?
2. While check out, after entering the address , it shows this error message,

![image](https://user-images.githubusercontent.com/51371138/88158038-317e6280-cc14-11ea-8ca1-2edcaed446bd.png)

How to fix both? please help.

**Comment by minhtruong315** [comment]
Hi @nucl123 
1. You can change minAllowTotalCartValue in common/config/products.dart
2. Send me common folder.
