### ISSUE TITLE
Push notifications

### ISSUE THREAD

**Issue by easieber** [inspireui/support#4316]
1. I have a little issue with the push notifications. In Ios is working because in the notifications list i get the new notifications but you dont get a pop up or badge in the iphone that notifies you that in the app is a new notification. Some idea?

2. And is possible to trigger an automatic notifications when a new blog is posted?

3. How i change this logo to mine in android?:

![Screenshot 2020-07-22 at 14 09 18](https://user-images.githubusercontent.com/35961470/88174726-110ad400-cc25-11ea-88e3-b02578bca738.png)

**Comment by ameenbadri7** [comment]
Hi, @easieber 
for issue 1- @minhcasi can you help here. thank you

2- We sincerely apologize for the issue as it is related to the customization that will not include from our support scope.

For issue 3:
You can go to `android\app\src\main\res\drawable` inside your project and then replace the logo with your logo. keep it at the same size.

You can learn more about the customization from here :
https://firebase.google.com/docs/cloud-messaging/android/receive

**Comment by minhcasi** [comment]
@easieber - pls help to check the video from this blog https://medium.com/@inspireui/setup-firebase-cloud-messaging-fcm-push-notification-for-flutter-apps-8c767fe64e54

**Comment by easieber** [comment]
I did.. still the same, and i noticed that in your documentation you have some extra steps that i didnt follow yet because now i am not sure and maybe i break the app.. you have some section in your documentation and tutorials that are out of date.. but so far i follow again you ios steps and nothing..

**Comment by minhcasi** [comment]
@easieber - could you have a quick check the Push Notification from your iPhone to see if it is disabled by somehow?

**Comment by easieber** [comment]
they are allowed: https://recordit.co/W4uzyaPhgU

**Comment by minhcasi** [comment]
@easieber - try to use the real device pls, on simulator this feature will not work fine

**Comment by easieber** [comment]
@minhcasi i tried in my old iphone and still nothing :( but the notification is inside the app, but no pop up badge or something and i allowed notifications

**Comment by minhcasi** [comment]
@trunghieuvn - pls suggest for this issue

**Comment by trunghieuvn** [comment]
hi @easieber, if you build and have an error and cannot push notifications in the background and the log returns on Xcode `Can't end BackgroundTask ... ` then you may be experiencing errors with iOS versions smaller than version 13.4 and Xcode from version 11. You can view this error at [https://forums.developer.apple.com/thread/121990](https://forums.developer.apple.com/thread/121990) 
Until iOS 13.4, this problem was fixed.
you please check if the error is the same?

**Comment by minhcasi** [comment]
Let us know if you have any question - thank you!

**Comment by easieber** [comment]
@minhcasi i already tried:
creating again the IOS app in firebase
new keys in the developer section of apple developer
deleting this "extra code" 
Checking everything in the workspace with Xcode that is the same as your video tutorial and manual setup documentation and still nothing... 
I even delete the app and install it again allowing the notifications in the pop up and still.


This badges are still missing in the device, but the message is there in the notification center

**Comment by easieber** [comment]
Some screenshots of xcode workspace:

<img width="669" alt="Screenshot 2020-07-29 at 10 59 56" src="https://user-images.githubusercontent.com/35961470/88780099-c93afe00-d18a-11ea-916f-b83c573edda6.png">
<img width="865" alt="Screenshot 2020-07-29 at 10 59 15" src="https://user-images.githubusercontent.com/35961470/88780107-cb9d5800-d18a-11ea-84e7-859c868d95cc.png">
<img width="858" alt="Screenshot 2020-07-29 at 10 58 54" src="https://user-images.githubusercontent.com/35961470/88780110-ccce8500-d18a-11ea-966a-20bf48012e24.png">

**Comment by trunghieuvn** [comment]
Hi @easieber 
There is a problem with Xcode 11 and IOS 13, so virtual devices and real device with ios version less than 13.4 will not work (if the app is built with xcode 11). You can read the article write [here](https://forums.developer.apple.com/thread/121990).

To ensure you have the correct configuration. You can use a real device to check push notifications. 
Recommendation that the device can be updated to version iOS 13.4 or higher.

**Comment by easieber** [comment]
i tested with my iphone 6 version 12.. still..

I will give a second try  then

**Comment by easieber** [comment]
@trunghieuvn thank you, i took a iphone from a friend (Iphone Xs) and there it works... Sorry for the inconvenient!

**Comment by trunghieuvn** [comment]
Nice to help you <3 . 
Please help me close the ticket and if you feel satisfied please give me 5 stars https://codecanyon.net/downloads .
Thank you very much.
