### ISSUE TITLE
need to remove zip code from checkout and make state dropbox with specific area

### ISSUE THREAD

**Issue by mohamedibrahim89** [inspireui/support#4317]
hello
first need to remove zip code from checkout address
second need to make sate dropdown with specific area
thxxx

**Comment by ameenbadri7** [comment]
hello @mohamedibrahim89 

1- Please help us by using the [Inspector ](https://www.youtube.com/watch?v=yGMt3Y20Zmg) to customize any UI from the app.
2- you can add states to your app by using this [guide ](https://docs.inspireui.com/fluxstore/common-issues/#-whats-happen-if-my-shipping-methods-does-not-display).

Please notes that we don't take customization requests for the regular license but you can buy the Extended License or Support Pack, please help to check our [Support Policies](https://inspireui.com/support-policies) and email us with your request.

Thank you

**Comment by ameenbadri7** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved. 
 - thank you for your time!
