### ISSUE TITLE
Error pulling products from Shopify

### ISSUE THREAD

**Issue by ediruzza** [inspireui/support#4318]
Getting this error after compiling into APK

I/flutter ( 8466): ::::fetchProductsByCategory shopify error
I/flutter ( 8466): NoSuchMethodError: The method '[]' was called on null.
I/flutter ( 8466): Receiver: null
I/flutter ( 8466): Tried calling: []("products")

I/flutter ( 8466): {{node: null}}

Latest Verion
Flutter
Android Studio

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_
**

**Comment by ameenbadri7** [comment]
hello, @ediruzza 
You are verified don't send your license key to here on GitHub only send it to our privet link.

Our team will follow with you to fix your problem soon.

Thank you for your time!

**Comment by minhcasi** [comment]
@ediruzza - could you help to give a try with the fluxbuilder to check if it has the same issue - http://fluxbuilder.com ? Thank you!

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
