### ISSUE TITLE
deploy to IOS Store BUG

### ISSUE THREAD

**Issue by hakihosting** [inspireui/support#432]
HELLO  i would like to deploy my app but i have two errors
<img width="739" alt="distributionErrorChakcwear" src="https://user-images.githubusercontent.com/47614045/54892837-6e690680-4eb3-11e9-924b-e9d7fac6daac.png">

**Comment by hakihosting** [comment]
It's done , it must be require fullscreen

**Comment by luyx2412** [comment]
Closed! :D
