### ISSUE TITLE
Build on macOS with Android Studio doesn´t work

### ISSUE THREAD

**Issue by heftipascal1** [inspireui/support#4321]
+ Detail Issues: Build iOS App with Android Studio doesn´t work
+ Testing Device/Simulator:   macOS 

Flutter Doctor "No issues found"

Follow  failure is when i build it:

Launching lib/main.dart on sdk gphone x86 in debug mode...
Running Gradle task 'assembleDebug'...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

 

FAILURE: Build failed with an exception.

 

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> java.net.URISyntaxException: Illegal character in opaque part at index 2: M:\\Oe Gourmet\\app\\source\\build\\app\\intermediates\\flutter\\debug\\flutter_assets\\AssetManifest.json

 

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

 

* Get more help at https://help.gradle.org

 

BUILD FAILED in 2s

i don´t know how we can fix that??

**Comment by ameenbadri7** [comment]
This is a common issue you could fix it by deleting the building cache try to read this fix :

https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
