### ISSUE TITLE
Shipping zones for multi country not appear 

### ISSUE THREAD

**Issue by digital0life** [inspireui/support#4322]
Hello all 
in woocommerce 
 i have issue on shipping zones, i have 2 country each country  they have own zones like below 

Country 1 :
  -- Zone A
  -- Zone B

Country 2: 
  -- Zone C

at app when i choose country A the zones form country A its come correctly

But there is issue if i select country 2 .. not zone come ...

how i can fixed this issue ? 

Thanks

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 

Thank you for your time!

**Comment by digital0life** [comment]
> Thank you for the feedback.
> 
> Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.
> 
> We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission.
> 
> After you submit to the link please provide details screenshots about your problem.
> 
> Thank you for your time!

done

**Comment by minhcasi** [comment]
verified ✅

@digital0life - could you take the screenshot of your Shipping setting from woocommerce site?

**Comment by digital0life** [comment]
Hello 

Kindly find attached it will be as 
3 countries each country have own shipping 
https://imgur.com/5fPi23x

Zone 1 for country X
  - Flat rate 1
  - Flat rate 2
  - Free shipping 

this one only working fine 
https://imgur.com/lGmMtjH

Zone 2 for country Y
- Flat rate 

non-return anything when select country Y 
https://imgur.com/gmZOJFn


Zone 3 for country C
- Flat rate 

non-return anything when select country Y 
https://imgur.com/VSQOurq

Thanks

**Comment by minhcasi** [comment]
@minhtruong315 - pls help to check this shipping issue - thank you!

**Comment by digital0life** [comment]
Hello

Is there any feedback

Thanks

**Comment by digital0life** [comment]
> @minhtruong315 - pls help to check this shipping issue - thank you!

Hello .. is there any update ...

Thanks

**Comment by minhtruong315** [comment]
Hi @digital0life can u send me common folder?

**Comment by digital0life** [comment]
Here ?

**Comment by digital0life** [comment]
> Hi @digital0life can u send me common folder?

Where u want shear folder with u ?

**Comment by minhtruong315** [comment]
can u send me via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/4322

**Comment by digital0life** [comment]
> can u send me via email: [truong@inspireui.com](mailto:truong@inspireui.com)
> with subject: #4322

Sent .. thanks

**Comment by minhtruong315** [comment]
@digital0life It's working well on Fluxstore version 1.7.6
https://www.dropbox.com/s/82or0j3f739q2t7/shipping.mov?dl=0
What is the version you're using?

**Comment by digital0life** [comment]
> @digital0life It's working well on Fluxstore version 1.7.6
> https://www.dropbox.com/s/82or0j3f739q2t7/shipping.mov?dl=0
> What is the version you're using?
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/e10359dcbd08dd8f24b1a353c63665bcfddc3f83/68747470733a2f2f7777772e64726f70626f782e636f6d2f74656d705f7468756d625f66726f6d5f746f6b656e2f732f38326f72306a3366373339713274373f70726573657276655f7472616e73706172656e63793d46616c73652673697a653d3132303078313230302673697a655f6d6f64653d34">Dropbox**[shipping.mov](https://www.dropbox.com/s/82or0j3f739q2t7/shipping.mov?dl=0)**Shared with Dropbox

That mean there is issue in version 1.7.4 ?

**Comment by minhtruong315** [comment]
please update version 1.7.6. it's newest version.

**Comment by digital0life** [comment]
> please update version 1.7.6. it's newest version.

It's complex to update coz we made our some work .. and update not easy from 1.7.4 to 1.7.6 

Can u till me what the issue in 1.7.4.. or a clear steps for update .. coz the update video not clear

**Comment by minhtruong315** [comment]
try to replace this version in services/woo_commerce.dart
```
@override
  Future<List<ShippingMethod>> getShippingMethods(
      {Address address, String token, String checkoutId}) async {
    try {
      Map<String, dynamic> params = {
        "destination": {
          "country": address.country,
          "state": address.state,
          "postcode": address.zipCode
        },
      };
      List<ShippingMethod> list = [];
      final http.Response response = await http.post(
          "$url/wp-json/wc/v2/flutter/shipping-methods",
          body: convert.jsonEncode(params));
      final body = convert.jsonDecode(response.body);
      if (response.statusCode == 200) {
        for (var item in body) {
          list.add(ShippingMethod.fromJson(item));
        }
      } else if (body["message"] != null) {
        throw Exception(body["message"]);
      }
      return list;
    } catch (err) {
      rethrow;
    }
  }
```

**Comment by digital0life** [comment]
not work it gives us error

**Comment by minhtruong315** [comment]
@digital0life pls download version 1.7.6 on codecanyon and try again.

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!

**Comment by digital0life** [comment]
But the issue not solved and not given a clear answer for issue 

Thanks

**Comment by digital0life** [comment]
Hello

Kindly need ur help
if i enable woocommerce brands plugin the coupon not work it give me error
.. can u plz advice me


Thanks
