### ISSUE TITLE
Error in build gradle file

### ISSUE THREAD

**Issue by owais91411** [inspireui/support#4323]
Hi, the build gradle file under app folder is showing errors. It’s showing this – flutter sdk not found. define location with flutter.sdk in the local.properties file

I'm using fluxstore woocommerce
Username for codecanyon - owais9141

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ 
- please don't share the purchase code or screenshot public here as another user will use it for activation.
We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 
Thank you for your time!

**Comment by minhcasi** [comment]
@owais91411 - pls try to config the flutter sdk from android studio

<img width="972" alt="Screen Shot 2020-07-23 at 10 34 20" src="https://user-images.githubusercontent.com/1459805/88249912-13763800-ccd0-11ea-8103-74a2c30efdee.png">

Also, refer to this solution to clean up the flutter cache - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

**Comment by minhcasi** [comment]
@owais91411 - also try to check the solution on this link https://github.com/flutter/flutter/issues/29608 - let us know if you have any questions - thank you!
