### ISSUE TITLE
Error in build gradle file also i need add icon on menu also checkout guest plz

### ISSUE THREAD

**Issue by iqmtgar** [inspireui/support#4324]
hi how are you all
i need add fix android st
and i want add icon on category
on img  number 1 only now i know how to change number 2 and 3 just number 1 what icon size 
and 
also i need checkout guest plz on woocomerce
![img1](https://user-images.githubusercontent.com/33340985/88243588-831d0080-cc99-11ea-94a3-36b3dd2ecb9c.jpg)

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.
We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 
Thank you for your time!

**Comment by iqmtgar** [comment]
> Thank you for the feedback.
> 
> Please help us to submit this form and fill all required info to continue with the support - [http://verify.inspireui.com/ -](http://verify.inspireui.com/%C2%A0-) please don't share the purchase code or screenshot public here as another user will use it for activation.
> We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission.
> Thank you for your time!

I read your comment on a previous problem
And I sent everything on this link http://verify.inspireui.com/

**Comment by minhcasi** [comment]
@iqmtgar - please help to give a try to use our free Fluxbuilder tool to support for these customization - http://fluxbuilder.com

**Comment by iqmtgar** [comment]
> @iqmtgar - please help to give a try to use our free Fluxbuilder tool to support for these customization - http://fluxbuilder.com

fluxbuilder can create using checkout guest ?

**Comment by minhcasi** [comment]
@iqmtgar - it may not work at this time as the fluxbuilder is mostly suitable for the preview and customize UI - we will investigate to upgrade it later - thank you

**Comment by iqmtgar** [comment]
I tell you how to create checkout ghust i want buy customer without
register can or not?
Plz

في السبت، ٢٥ يوليو، ٢٠٢٠ ٩:٢٣ ص Minh Pham <notifications@github.com> كتب:

**Comment by ameenbadri7** [comment]
@iqmtgar 
you can do that by enabling this feature from the `lib\common\config\payments.dart` on line 20:
`  "GuestCheckout": true,`

feel free to close this issue if you're satisfied with the finishe result.
