### ISSUE TITLE
License control for development environment.

### ISSUE THREAD

**Issue by enoncie** [inspireui/support#4326]
Hi,

We have 2 wordpress servers. One for development&testing and the other for the production.

I would like to know if I need to buy the other license if I want to put it on wordpress production server?

Thank you for your support. :-)

**Comment by minhcasi** [comment]
@enoncie - it is possible to reset the previous active License from your testing/development website and change it to production mode - please send reset to support@inspireui.com 

If you need 2 sites active at the same time, please help to purchase 2 licenses - thank you!
