### ISSUE TITLE
[FluxStore Listing] Unable to get the featured image

### ISSUE THREAD

**Issue by aldoyh** [inspireui/support#4329]
Hello,

I'm very excited to get this project running I recently purchased! 🥇 
(Proof of purchase attached)

<img width="1148" alt="Screen Shot 2020-07-23 at 11 35 38" src="https://user-images.githubusercontent.com/5215449/88267072-f5610580-ccd8-11ea-9c83-0efee5df45af.png">

My returned JSON data attached here:

[nr-properties.json.zip](https://github.com/inspireui/support/files/4964739/nr-properties.json.zip)

I've tried everything but I can't get the Featured Image of each "item/product" to show up using this map wiring definition, and even WP BFI isn't showing within my JSON return of the CPT (not found in the above attached):

`  "featured_media": "_embedded.wp:featuredmedia.source_url"
`
I think it might be the colon (:) after "wp", I need help, please.

**Comment by minhcasi** [comment]
@aldoyh - you could try to use this lib https://wordpress.org/plugins/better-rest-api-featured-images/

**Comment by aldoyh** [comment]
Thank you, I will try and get back to you for the plugin, but do you think it's healthy to keep having a plugin for such thing? additionally to that, the "source_url" is provided in the returned data.

**Comment by minhcasi** [comment]
Yes, we will migrate it into mstore-api soon :)

**Comment by aldoyh** [comment]
Great news, meanwhile I'd like to suggest this solution.

Add this code to the functions.php of your theme as workaround for now to retrieve the featured image of any custom post type.

```

add_action( 'rest_api_init', 'add_thumbnail_to_JSON' );

function add_thumbnail_to_JSON() {
//Add featured image
register_rest_field( 
    'property', // Where to add the field (Here, blog posts. Could be an array)
    'flux_featuredimage', // Name of new field (You can call this anything)
    array(
        'get_callback'    => 'get_image_src',
        'update_callback' => null,
        'schema'          => null,
         )
    );
}

function get_image_src( $object, $field_name, $request ) {
  $feat_img_array = wp_get_attachment_image_src(
    $object['featured_media'], // Image attachment ID
    'thumbnail',  // Size.  Ex. "thumbnail", "large", "full", etc..
    true // Whether the image should be treated as an icon.
  );
  return $feat_img_array[0];
}
```

The above solution is instead of installing the plugin mentioned.

Hope that helps.

**Comment by minhcasi** [comment]
@aldoyh - thank you so much for your sharing

@minhtruong315 - please help to investigate this solution and upgrade for both `mstore-api` and `listapp-manager` plugin, we could update new document as well

**Comment by minhtruong315** [comment]
Hi @aldoyh sorry for delay. can u send me common folder and admin account to login your website via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/4329

**Comment by aldoyh** [comment]
Done, thanks in advance.

**Comment by minhtruong315** [comment]
Hi @aldoyh I checked your config. The type "property" doesn't support in Fluxstore Listing. Fluxstore Listing only supports types: listeo, listpro, mylisting and google-sheet. Please check again and let me know. Thanks
```
 "type": "property",
  "url": "https://nasser-real.com",
```

**Comment by aldoyh** [comment]
Thanks, but my custom type post is property .. where shall I set that? And to what should I set the type in the config? 

Sent from Yahoo Mail on Android 
 
  On Wed, Aug 5, 2020 at 2:17 AM, minhtruong315<notifications@github.com> wrote:   


Hi @aldoyh I checked your config. The type "property" doesn't support in Fluxstore Listing. Fluxstore Listing only supports types: listeo, listpro, mylisting and google-sheet. Please check again and let me know. Thanks
 "type": "property",
  "url": "https://nasser-real.com",

**Comment by minhtruong315** [comment]
Hi @aldoyh please check our document https://docs.inspireui.com/fluxstore/listing-directory/
Fluxstore listing only supports 4 templates now.

**Comment by aldoyh** [comment]
But it's working for that type with few edits around, if you could just show me where they're wired specifically which files to work with? 

Note the screenshot, the customization is working but need help to make it perfect. 

![Screenshot_1596490713](https://user-images.githubusercontent.com/5215449/89508512-ae920600-d7d6-11ea-9be6-68e5fb28aa52.png)

**Comment by minhtruong315** [comment]
@aldoyh We only support for integration, we dont support for customize server type.

**Comment by aldoyh** [comment]
It's not customized type my friend, it's an existing public plugin on WordPress, you don't have to integrate the whole thing.. just guide me through the files, please?

**Comment by minhcasi** [comment]
@aldoyh - please help to share your current customize to inspireui.team@gmail.com - or add this email to your private GitHub - we are willing to add support for this property listing 👍 

If it is possible please share your admin login as well. 

As this is a new feature, give us some time to review and update the development stuff

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
