### ISSUE TITLE
method delivery dont load

### ISSUE THREAD

**Issue by daboujey** [inspireui/support#4330]
In app don't display method delivery in checkout
In website woocommerce display 

**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
+ Product & version: 1.7.5
+ Flutter (or React Native) version: 1.17.5
+ Testing Device/Simulator: pixel 6
+ Screenshot issues (drag the file to attach here): 

![Screenshot_20200723-055917281](https://user-images.githubusercontent.com/64880213/88273586-cc2c7f00-ccb0-11ea-8031-96b3cd17cff5.png)

![Screenshot_20200723-060031364](https://user-images.githubusercontent.com/64880213/88273734-00a03b00-ccb1-11ea-9a68-499d1f187bb9.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by daboujey** [comment]
![Screenshot_20200723-070157682](https://user-images.githubusercontent.com/64880213/88274871-d2235f80-ccb2-11ea-8268-7574349f0c3b.png)

![Screenshot_20200723-070534450~2](https://user-images.githubusercontent.com/64880213/88274905-e23b3f00-ccb2-11ea-9c75-b6405f8c77f2.png)

**Comment by ameenbadri7** [comment]
Enable webview payment option it will show exactly as you want.
Go to `lib\common\config\payments.dart` and then 
change the payment option to this :
```
 "EnableOnePageCheckout": true,
  "NativeOnePageCheckout": false,
```

THANK YOU.

**Comment by daboujey** [comment]
Error in next page

![Capturar123456](https://user-images.githubusercontent.com/64880213/88338954-91a5ff00-cd0f-11ea-9fb3-c6dc45581959.JPG)

**Comment by ameenbadri7** [comment]
Download the latest update 1.7.6 its fixes most of the bugs you see now .
Thank you

**Comment by daboujey** [comment]
New version dont compiler
Error

![ERROR12345](https://user-images.githubusercontent.com/64880213/88387040-087ede80-cd88-11ea-94cf-57d657f51205.JPG)

**Comment by ameenbadri7** [comment]
Refer to this solution to clean up the flutter cache - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1
Also try to check the solution on this link flutter
https://github.com/flutter/flutter/issues/29608

Dont forget to config your sdk from android studio UI 

<img width="972" alt="88249912-13763800-ccd0-11ea-8103-74a2c30efdee" src="https://user-images.githubusercontent.com/37524186/88443283-60692400-ce20-11ea-9954-8d1ad03eb8b6.png">

let us know if you have any questions - thank you!

**Comment by daboujey** [comment]
Continue error

![image](https://user-images.githubusercontent.com/64880213/88456574-eb641180-ce54-11ea-9317-bee89bf2e0f7.png)

**Comment by daboujey** [comment]
In version 1.7.5 error 404 
![image](https://user-images.githubusercontent.com/64880213/88456729-7a255e00-ce56-11ea-9e5c-c2d56368a789.png)

**Comment by minhtruong315** [comment]
Hi @daboujey Can u try to change "CheckoutPageSlug" in  common/config/payments.dart same with your website?
<img width="1644" alt="Screen Shot 2020-07-26 at 9 56 02 PM" src="https://user-images.githubusercontent.com/10402500/88482389-33855000-cf8b-11ea-8eea-a22a843a9e7d.png">

**Comment by daboujey** [comment]
Name page checkout is "check-ou" I change in Dart to check-out ...
continue erro

If clic in cart icon page delivery open correctly 

 https://youtu.be/GEU6nIMq_Eo

**Comment by minhtruong315** [comment]
@daboujey can u send me common folder via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/4330

**Comment by minhtruong315** [comment]
Hi @daboujey send me admin account to login your website. 
Thanks

**Comment by minhcasi** [comment]
'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
