### ISSUE TITLE
On_Boarding Screen Customizations

### ISSUE THREAD

**Issue by TqwaAlTurki** [inspireui/support#4332]
Detail Issues: Hello there, thanks for your amazing work. 
I'm looking for a way to make the on boarding image to be full size, i don't want the black space in the sides, the setting of the intro slider doesn't provide that, how can you help?
Product & version: Fluxstore WooCommerce version1.6.7
Flutter version: v1.17.2,
Testing Device/Simulator: Android Emulators
Screen Shots: 
![image](https://user-images.githubusercontent.com/34610407/88283368-8640dc80-cceb-11ea-93c8-cca81a81cac4.png)

**Comment by minhcasi** [comment]
@TqwaAlTurki - you could try to replace the current `pathImage` by `backgroundImage` from  https://pub.dev/packages/intro_slider 

<img width="926" alt="Screen Shot 2020-07-24 at 10 57 41" src="https://user-images.githubusercontent.com/1459805/88359345-82b95e00-cd9c-11ea-88b7-bb30b763fb83.png">

**Comment by TqwaAlTurki** [comment]
Hello again @minhcasi  , see my code here: 
![image](https://user-images.githubusercontent.com/34610407/88474002-2c2a5c00-cf23-11ea-8f7a-b00d9a7ab838.png)

**Comment by TqwaAlTurki** [comment]
@minhcasi  also i'm getting this issue :|. i'm pretty sure i'm connected to the internet. 
![image](https://user-images.githubusercontent.com/34610407/88477477-90a7e400-cf40-11ea-9bfd-0957e62c0e8b.png)

**Comment by TqwaAlTurki** [comment]
alsoo 🤭 sorry but i added a side drawer in my cart screen, it used to work in previous versions, and it did worked in this version when i added it on my wish list screen and setting screen but here in my cart screen it won't open. can i know why? 
![image](https://user-images.githubusercontent.com/34610407/88477578-89cda100-cf41-11ea-9807-1c0d4d11155f.png)
this is the code i added: 
![image](https://user-images.githubusercontent.com/34610407/88477594-bb466c80-cf41-11ea-95da-d116d14fd119.png)

**Comment by ameenbadri7** [comment]
We wanted to thank you for your patience during this busy time.
We currently have reduced staff and a significantly higher volume of inquiries. 
We’re working as hard as we can to get to your requests as soon as possible, pls help to check our support policies on [this page](https://codecanyon.net/item/fluxstore-multi-vendor-flutter-ecommerce-full-app/25013325/support).

**Comment by minhcasi** [comment]
@TqwaAlTurki - could you check to see if these screens have the same `context`

**Comment by TqwaAlTurki** [comment]
Hello again @minhcasi  wish you a good day.
about the context i'm not sure how to verify that, but apparently they both have the same context those are the screen shots: 
first mycart.dart file:
![image](https://user-images.githubusercontent.com/34610407/88645350-4d767e00-d0c4-11ea-9e45-1db16487375e.png)
wishlist.dart file:
![image](https://user-images.githubusercontent.com/34610407/88647049-f2458b00-d0c5-11ea-9529-f6700657906e.png)

**Comment by TqwaAlTurki** [comment]
i'm encountering another issues, the app seems to be slow, slow in switching languages it takes more than ten seconds to switch b\w languages how can i fix that? 
![image](https://user-images.githubusercontent.com/34610407/88648099-f1612900-d0c6-11ea-8386-8c43bf30e6a0.png)
and it takes forever to load product images and that's very annoying 
 
![image](https://user-images.githubusercontent.com/34610407/88648542-5e74be80-d0c7-11ea-9a6a-dbe9a69c983f.png)

**Comment by simonpham** [comment]
@TqwaAlTurki are you still encountering any issues?
We suggest updating FluxStore to the latest version which has improved performance, bug fixes, and new features.

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
