### ISSUE TITLE
Having issue building and running ListApp React Native (Expo) version

### ISSUE THREAD

**Issue by gfunkerwin** [inspireui/support#4334]
Hi @gfunkerwin Can you give me the list app version? Expo or React native original.

Thanks

_Originally posted by @luyx2412 in https://github.com/inspireui/support/issues/4265#issuecomment-661639631_

The ListApp is Expo version and this is what I got when running build on Expo

Unable to resolve "react-native-screens" from "node_modules/react-navigation-tabs/lib/module/navigators/createBottomTabNavigator.js

Thanks

**Comment by minhcasi** [comment]
@gfunkerwin - pls try to run this script `expo install react-native-screens` 

relate ticket #3123

**Comment by gfunkerwin** [comment]
ok let me try

**Comment by gfunkerwin** [comment]
didn't work, I got these error messages:

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.20.0 install: `node-pre-gyp install --fallback-to-build --library=static_library`

**Comment by gfunkerwin** [comment]
It seems the build errors have issues with dependencies, this is the log:

npm WARN deprecated react-navigation-stack@1.10.3: This version of React Navigation Stack is no longer supported. Please upgrade to 2.x.x. See https://reactnavigation.org/docs/4.x/upgrading-from-3.x#react-navigation-stack for instructions.
npm WARN deprecated core-js@1.2.7: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated @hapi/joi@15.1.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated react-native-sentry@0.42.0: Please use @sentry/react-native


at the end of the build, this is what I received:

> grpc@1.23.3 install /Users/geraiku/Documents/DEV-FOLDERS/QETEMU-APP/ListApp 1.7.5/source/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

sh: node-pre-gyp: command not found

npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! grpc@1.23.3 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the grpc@1.23.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by gfunkerwin** [comment]
however when I ran using Expo directly, the app installed and working with these warnings:

Require cycle: App/Components/index.js -> App/Components/BannerImage/index.js -> App/Components/index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
- node_modules/expo/build/environment/muteWarnings.fx.js:18:23 in warn
- node_modules/metro/src/lib/polyfills/require.js:118:8 in metroRequire
* http://192.168.0.12:19001/node_modules/expo/AppEntry.bundle?platform=android&dev=true&minify=false&hot=false:371444:32 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:322:6 in loadModuleImplementation
* http://192.168.0.12:19001/node_modules/expo/AppEntry.bundle?platform=android&dev=true&minify=false&hot=false:199294:57 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:322:6 in loadModuleImplementation
* http://192.168.0.12:19001/node_modules/expo/AppEntry.bundle?platform=android&dev=true&minify=false&hot=false:198845:32 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:322:6 in loadModuleImplementation
* http://192.168.0.12:19001/node_modules/expo/AppEntry.bundle?platform=android&dev=true&minify=false&hot=false:128122:55 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:322:6 in loadModuleImplementation
- node_modules/expo/AppEntry.js:5:0 in <global>
- node_modules/metro/src/lib/polyfills/require.js:322:6 in loadModuleImplementation
- node_modules/metro/src/lib/polyfills/require.js:201:45 in guardedLoadModule
* App/Components/LeftMenu/MenuAndroid.js:13:3 in MenuAndroid

**Comment by gfunkerwin** [comment]
For the above I was using CE Builder

**Comment by luyx2412** [comment]
Hi @gfunkerwin Can you share me your node, expo-cli and yarn version?

Thanks

**Comment by gfunkerwin** [comment]
Yarn v1.22.4
Node v14.5.0
Expo 3.22.3

**Comment by luyx2412** [comment]
Hi @gfunkerwin Please move node version to 10.x.x. You can use nvm to manage node version https://github.com/nvm-sh/nvm. Because the React native did not work some case in another node version.

Thanks

**Comment by gfunkerwin** [comment]
ok, allow me to try those

**Comment by gfunkerwin** [comment]
okay, it works. Thank you.

Quick question, are you guys going to update CE Builder?

**Comment by minhcasi** [comment]
We may not upgrade the cebulider at this time, but you could try to download the previous release from https://github.com/inspireui/cebuilder/releases/tag/0.40.1

Let us know if you have any question :)
