### ISSUE TITLE
Problem with product's WCFM

### ISSUE THREAD

**Issue by gonzalovvt** [inspireui/support#4336]
In WCFM stores there is an error in the products area, they do not load complete, they only load about 12 and they are repeated when scrolling.. 

Please help on this.

Fluxstore Multi vendor: 1.7.5

**Comment by ameenbadri7** [comment]
Download the latest as that could fix your problem. 
It released before 8 Hours on our privet Gitlab repo.
If you are not add yet Please help to submit access to [HERE](http://gitlab.inspireui.com)
Thank you

**Comment by gonzalovvt** [comment]
Done! Thanks you! 😊

**Comment by gonzalovvt** [comment]
I already made the solitude.

My email is: gonzalovvt@gmail.com

And send already the request 👍

**Comment by minhcasi** [comment]
gitlab invitation is sent - thanks

**Comment by minhcasi** [comment]
please also use the latest release from `1.7.6` as well - let us know if you have any issues 👍

**Comment by gonzalovvt** [comment]
There is a problem now, vendor store logo is the same as vendor banner logo, same image are displayed
