### ISSUE TITLE
Build failed with an exception. flux store

### ISSUE THREAD

**Issue by teampotlot** [inspireui/support#4337]
I can not release the application. Can you help me 

![image](https://user-images.githubusercontent.com/66760408/88338467-fa6e9500-cd6a-11ea-8432-fe1eb10a9418.png)

**Comment by ameenbadri7** [comment]
Copy your source files to  `C ` Disk and create a new folder like `src ` and paste the fluxstore source code there and then clear the build cache by using `flutter clean` and then build again.

You are having issues with the windows permissions for your folders.
If this not working please let us know.
Thank you

**Comment by teampotlot** [comment]
I couldn't do a flutter clean on my project. Please help her. Do you remote My Computer 

![image](https://user-images.githubusercontent.com/66760408/88343760-b2ed0680-cd74-11ea-80bb-cb033fdd495e.png)

**Comment by ameenbadri7** [comment]
Please read my comment again, you should move your source folder to C disk to work our this issue. 

Thank you

**Comment by ameenbadri7** [comment]
I'm sorry to close this ticket as there is no response or active conversation. 

Please help to create a new one and link to this ticket if the problem is not solved. 

- Thank you for your time!
