### ISSUE TITLE
ipad bugs 

### ISSUE THREAD

**Issue by abedfatafta** [inspireui/support#4338]
**_Step 1 (require): describe detail issues & screenshots_**
bottom menu not showing on ipad all versions 
top menu close and open not working when you click on it 
visit store  -return you to home screen 

<img width="666" alt="Screen Shot 2020-07-24 at 1 52 30 AM" src="https://user-images.githubusercontent.com/16276919/88346281-9fc83f80-cd50-11ea-968f-85144ee377aa.png">

![Simulator Screen Shot - iPad Air (3rd generation) - 2020-07-24 at 01 51 39](https://user-images.githubusercontent.com/16276919/88346302-a9ea3e00-cd50-11ea-937d-96812824e676.png)nu 

![Simulator Screen Shot - iPad Air (3rd generation) - 2020-07-24 at 01 50 30](https://user-images.githubusercontent.com/16276919/88346294-a5be2080-cd50-11ea-8aa3-a932ad7ecf3e.png) 
'

+ Detail Issues: 
bottom menu not showing on ipad 3 
top menu close and open not working when you click on it 

+ Product & version:1.7.5
+ Flutter (or React Native) version: flutter
+ Testing Device/Simulator: simulator 
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

old ticket: 4268

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@abedfatafta - you could set the if statement to false if don't like to use the ipad layout, then it will back to the mobile layout. We will upgrade to move all the menu item from bottom navigate to the left side or move back the tab menu on next release

<img width="1032" alt="Screen Shot 2020-07-24 at 11 23 08" src="https://user-images.githubusercontent.com/1459805/88360487-0e80b980-cda0-11ea-8b86-b8b6b70bbb65.png">


Please help to move your all conversation to the same ticket support #4268
