### ISSUE TITLE
On Offer Widget in Home

### ISSUE THREAD

**Issue by jvsamoa** [inspireui/support#4339]
Hi,
I am again. I hope finish the project soon LoL

I need show all in offer products, I mean if I create a new category call: OnOffer and tag all my products on Discount there I going to display all Offerts products.

"VerticalLayout":{
    "layout":"list",
    "name":"Discounts",
    "key":"bsrbh4p5bo",
    "category":inoffer}}

My question is: have you another way to show it.

Regards.
Thanks for support to me

**Comment by ameenbadri7** [comment]
Hello again
Yes you can,
For products with star on woocommerce (featured product) you can show them like this: 

```
{
      "name": "Our Top Products",
      "layout": "twoColumn",
      "isSnapping": true,
      "featured": true,
      "onSale": false
    },
```

For products with special pricing like (old price 100 new price 60) you can show it like this : 

```
{
      "name": "On Sale Products",
      "layout": "twoColumn",
      "isSnapping": true,
      "featured": false,
      "onSale": true
    },
```


Remeber to add them inside
  `"HorizonLayout": [   ]`

All hopes to finish your project. 

Thank you.

**Comment by minhcasi** [comment]
@jvsamoa - pls move your all comment into one ticket support #4299 - thank you!
