### ISSUE TITLE
[Mstore] Home not Loading after viewing a custom page and Shipping method not Validating.

### ISSUE THREAD

**Issue by hellogossh** [inspireui/support#434]
**Required Info (please complete the following information):**
• Product: [MStore]
• Build: 3.6.7
• Your Purchased Code: [8636fad5-9c9b-45c9-99fd-9d0fa473fa3e]

**Custom page and Tab Bar Home**

If you are viewing the home section and then if the user either goes to the side menu or profile menu and selects a custom page like contact us, the page loads like it should.

But if the user wants to go back to the home section, selecting the home icon on the tab bar does not load the home section and there is no way of removing that custom page from view.

**Shipping Validation **

Is there a way to make sure the user selects a Shipping Method before proceeding to the payment screen?

At the moment, 1 of the 3 shipping options is preselected, but the user can proceed to the next screen with out selecting an option. But the preselected shipping method is not updated on the payment screen and shows a $0.00 amount from shipping.

**Comment by luyx2412** [comment]
Hi @hellogossh 
- We will try update the issue in next version
- Yes, you can check when click next screen, show error or warning user must select a Shipping method first. in `src/containers/Cart/Delivery/index.js` --> line 425 with `nextStep` function 

![image](https://user-images.githubusercontent.com/8909619/54968160-3ee9f500-4fac-11e9-8f35-650f6879b088.png)


Thanks
