### ISSUE TITLE
QUESTION: Variants without specific values

### ISSUE THREAD

**Issue by enriqueleon80** [inspireui/support#4341]
Hello,

This is more of a question than anything else.

I am running WooCommerce and FLUXSTORE 1.7.3.  I have created a product that has two attributes Size and Color.  Each has three options Small/Medium/Large and Red/White/Blue.  Both of these attributes are marked as variations so they show up on the app.  However, one of them is set to use ANY value because it doesn't impact price.  This means that there are only three variations Large & Any color, Medium & Any Color, and Small & Any Color.

Now, when I run the FLUXSTORE and I call the checkout cart using the WebView the JSON transferred to WooCommerce only includes the variant ID.  Because my three variants only specific size and not color, the color isn't showing up in the CHECKOUT.   This is a huge problem of course.

So my question is, does this app NOT support variant attributes that don't have values for each possible combination?  I must then create all these different combinations?  Any alternative to have customers select options for a product without using WooCommerce variations?

Appreciate the guidance.

**Comment by minhcasi** [comment]
@enriqueleon80 - we will investigate this issue and will let you know - thank you!

**Comment by enriqueleon80** [comment]
@minhcasi This was quite critical for us, since variations are truly driving price.  Tried to fix what was there, but to be honest I feel like it's missing quite a lot.  Here's a replacement I built for updateVariation which now seems to work.  I thought about updating @ the model, but I had no visibility to product attributes nor mapAttributes which I believe is needed to build out the new variants.

The issue is woo commerce sends you defined variants.  You then have to build new variants from product attributes, kinda messy.  No doubt you'll find a better way to do this.

Interestingly enough, the wordpress plugin did have some code to bring attributes in even though they weren't sent.  I just updated the ORDER->TO_JSON method to include the attributes.  Viola, seems to be working.  I guess I'll find out soon enough.

mixin ProductVariantMixin {
  ProductVariation updateVariation(variations, mapAttribute) {
    ProductVariation variantParent;
    int variantParentScore = 0;

    if (variations != null) {
      //Fetch variation that matches exact values provided in mappAttribute
      var variation = variations.firstWhere((currVariation) {
        bool isExistVariantForMapAtts = true;
        int currVariantScore = 0;

        //Find variation where the mapAttributes match
        for (var attribute in currVariation.attributes) {
          if (mapAttribute[attribute.name].isEmpty ||
              !mapAttribute.keys.contains(attribute.name) ||
              attribute.option != mapAttribute[attribute.name]) {
            currVariantScore -= 1;
            isExistVariantForMapAtts = false;
          } else {
            currVariantScore += 1; //Matched an attribute!
          }
        }

        if (currVariation.attributes.length != mapAttribute.keys.length) {
          currVariantScore = currVariantScore + (mapAttribute.keys.length - currVariation.attributes.length);
          isExistVariantForMapAtts = false;
        }

        //Return this variant, perfect match
        if (variantParent == null ||
            currVariantScore > variantParentScore ||
            (currVariantScore == variantParentScore)) {
              //  && ( currVariation != null && currVariation.price > variantParent.price))) {
          variantParent = currVariation;
          variantParentScore = currVariantScore;
        }
        return isExistVariantForMapAtts;
      }, orElse: () {
        //return null;
      });

      //If no variation found, we must then create a new one
      //NOTE: We identify which variant to use based on variant score above
      if (variation == null) {
        Map<String, dynamic> itemJson = variantParent.toJson();
        ProductVariation newVariation = ProductVariation.fromJson(itemJson);
        newVariation.regularPrice = variantParent.regularPrice;

        //Map all attributes
        newVariation.attributes.clear();
        for (var mapAttr_key in mapAttribute.keys.toList()) {
          Attribute att = Attribute()
            ..id = null
            ..name = mapAttr_key
            ..option = mapAttribute[mapAttr_key];
          newVariation.attributes.add(att);
        }
        //Add new variation to global data
        variation = newVariation;
        variations.add(newVariation);
      }

      if (variation == null && variations.isNotEmpty) variation = variations[0];
      return variation;
    }
    return null;
  }

**Comment by minhcasi** [comment]
@enriqueleon80 - thank you so much for your sharing, let us do some testing and will get back you soon

**Comment by and-eee** [comment]
This looks like it is the same issue as you're working on for me on ticket #4003 

Eagerly awaiting a solution.

**Comment by minhcasi** [comment]
@minhtruong315 - pls focus to check the root cause from this ticket and #4003

**Comment by minhtruong315** [comment]
@enriqueleon80 please use Fluxstore 1.7.7 then send me full your source code via email: minhtruong315@gmail.com
I will help you fix this issue on version 1.7.7
Ping me when you sent.
Thanks

**Comment by minhtruong315** [comment]
How @enriqueleon80

**Comment by enriqueleon80** [comment]
Howdy, sorry but I'm still on 1.7.3 given the number of mods.  I have the issue fixed with my own custom code, but once you issue you fix I will replace my own code with yours.

**Comment by minhtruong315** [comment]
@enriqueleon80 so can you check product variant on next release 1.7.8?

**Comment by enriqueleon80** [comment]
Sure, when is this expected?

Enrique Leon

**Comment by minhtruong315** [comment]
@enriqueleon80 I dont know. I think about 1->2 weeks later.
We're working hard to fix issues and add more features

**Comment by minhcasi** [comment]
Greetings from InspireUI 🎉
To improve user experience during support, we are announcing that a new ticket support system is available on this link https://support.inspireui.com 

Please help to move your next comment on the new support system (you could mention this ticket so that the team could know more about the ticket's history) - thank you for your time!
