### ISSUE TITLE
Inspireui forcing for extend license to people and not fix the common issues which is item default feturesP

### ISSUE THREAD

**Issue by omman** [inspireui/support#4342]
Hi, we submit a issue for common setting not customization why i will make extend license, this is a issue or bugs from your item problem. If not issue or bugs then we will extend or if we need customize from default fatures then but this is a issue for the item. Sorry we will not extend license for the issue. we can develop our own project flutter for woocommerce. And we will submit for the themeforest and complaign against the item why for the issue inspireui forcing to extend the license for the business. We pay for what. We have proof that when we buy item author said which is they shown to us it has all and they support for their default option only and customization fetures not in support, so my github issue not fix and i give my source with my business credintials. https://github.com/inspireui/support/issues/4281#issuecomment-662782830

**Comment by minhcasi** [comment]
reported as spam
