### ISSUE TITLE
Upgrading 1.7.5 to 1.7.6 get New issues.

### ISSUE THREAD

**Issue by omman** [inspireui/support#4343]
This Comment issue Please check this I explain here [https://github.com/inspireui/support/issues/4343#issuecomment-664178335](https://github.com/inspireui/support/issues/4343#issuecomment-664178335)

**Comment by minhcasi** [comment]
@omman - we will help the latest time to check your integration issues but you need to remove your all previous spamming comments - thanks

**Comment by omman** [comment]
@minhcasi Please help and fix your issues so that we will not comment you providing us for support just fix your items if updating have any issues. I am certified developer also selling items but not like this that you have done with us. I am not only one who get this problem i give you my 4 customer and they also suffering from your items after buying this, anyway we just inform you when we try to upgrading the items there is many things not working above [comments](https://github.com/inspireui/support/issues/4343#issue-665037031) i provided. If honestly fix this issues we will not comments for you.

**Comment by minhcasi** [comment]
Please remove your spam comments ASAP, otherwise, we will report to Envato.

I also sent to the team to investigate your above issues - thanks

**Comment by omman** [comment]
Hi, we do apologies about the comments in themeforest but that comments we asking this fixing the items issues i mentioned, however you are start investigate the issues after the comments, so if there is any option link that can edit or delete the comments so provide us we will delete for yoy don't worry. 
Specially Thanks for Investigate the issues.

**Comment by omman** [comment]
Apple Signing Error publishing in apple Store We got this Message:  


Hello,

Thank you for your resubmission. However, upon further review, we found that your app is out of compliance with the following guideline(s):
Guideline 2.1 - Performance - App Completeness
We discovered one or more bugs in your app when reviewed on iPad and iPhone running iOS 13.6 on Wi-Fi.
Specifically, an error message appears when user attempts to sign in with Sign In with Apple option.
Next Steps
To resolve this issue, please run your app on a device to identify any issues, then revise and resubmit your app for review.
If we misunderstood the intended behavior of your app, please reply to this message in Resolution Center to provide information on how these features were intended to work.
For new apps, uninstall all previous versions of your app from a device, then install and follow the steps to reproduce the issue. For updates, install the new version as an update to the previous version, then follow the steps to reproduce the issue.
Resources
For information about testing your app and preparing it for review, please see Technical Note TN2431: App Testing Guide.
For a networking overview, please review About Networking.

Please see attached screenshot for details.
![attachment Screenshot-0724-063320](https://user-images.githubusercontent.com/18089254/88432244-81bc1700-ce04-11ea-8e5e-8cbe0e0a0431.png)

**Comment by minhcasi** [comment]
@omman - you need to delete your all comments on Codecayon first, you know that will be impact to other user with these comments !!!

**Comment by omman** [comment]
@minhcasi i delete the comments as your request please also finish my request to help your latest version issues that i mention with this issues.
Thanks

**Comment by omman** [comment]
Hi, 
When you fix this issues can you tell me please it's too much wait for the issues we need update that version.
This issues/bugs is different from this issues [https://github.com/inspireui/support/issues/3536](https://github.com/inspireui/support/issues/3536) we checked already 
We need update for fix this issues that you said https://github.com/inspireui/support/issues/3825#issuecomment-657515245

No: 1 - Shipping method from woo-commerce from Shipping method zone, I didn't enable, but `**Pickup from store**` options, and `**Free delivery**` are showing all shipping method. sorry not payment method and we are using native payment screen so we use   /// Enable Payment option
  "EnableOnePageCheckout": false,
  "NativeOnePageCheckout": true,
[Screenshot: 1](https://imgur.com/YjTgOce)
[Screenshot: 2](https://imgur.com/z9pIhYT)

No: 2 - Still Same Problem not redirecting i am using this code:
```
  // "CheckoutPageSlug": "checkout",
  "CheckoutPageSlug": {"en": "checkout", "ar": "ar/checkout"},

```
No: 3 - Still Same Problem Not Showing My On boarding Screen it's Directly open home screen : here is my cod:
```
{
  "HorizonLayout":[
    {
      "layout":"logo",
      "showMenu":true,
      "showSearch":true,
      "showLogo":true
    },
    {
      "isSafeArea":true,
      "showSearch":false,
      "rotate":[
        "Fresh Vegetables",
        "Fresh Fruits",
        "Door to Door Home Delivery",
        "Weekly Pack Offer",
        "Special Offer",
        "Select Items & Buy Now"
      ],
      "type":"color",
      "height":0.13,
      "padding":30.0,
      "fontSize":23.0,
      "layout":"header_text"
    },
    {
      "layout":"header_search",
      "text":"Search for a product"
    },
    {
      "layout":"bannerImage",
      "isSlider":true,
      "autoPlay":true,
      "showNumber":false,
      "design":"default",
      "showBackGround":true,
      "padding":20.0,
      "radius":20.0,
      "items":[
        {
          "category":15,
          "image":"https://www.qutoof.qa/app/images/slider/s1_en.jpg"
        },
        {
          "category":205,
          "image":"https://www.qutoof.qa/app/images/slider/s2_en.jpg"
        },
        {
          "category":311,
          "image":"https://www.qutoof.qa/app/images/slider/s3_en.jpg"
        },
        {
          "category":204,
          "image":"https://www.qutoof.qa/app/images/slider/s4_en.jpg"
        }
      ]
    },
    {
      "layout":"bannerImage",
      "items":[
        {
          "category":213,
          "image":"https://www.qutoof.qa/app/images/banner/b1_en.jpg",
          "padding":15.0,
          "radius":20.0
        }
      ]
    }
  ],
  "Setting":{
    "MainColor":"#FB8C00",
    "ProductListLayout":"list",
    "StickyHeader":true
  },
  "TabBar":[
    {
      "layout":"home",
      "icon":"assets/icons/tabs/icon-home.png",
      "pos":100
    },
    {
      "layout":"category",
      "categoryLayout":"subCategories",
      "icon":"assets/icons/tabs/icon-category.png"
    },
    {
      "layout":"search",
      "icon":"assets/icons/tabs/icon-search.png",
      "pos":300,
      "url":"https://www.qutoof.qa",
      "title":"",
      "data":""
    },
    {
      "layout":"cart",
      "icon":"assets/icons/tabs/icon-cart2.png",
      "pos":400
    },
    {
      "layout":"profile",
      "icon":"assets/icons/tabs/icon-user.png",
      "pos":500,
      "settings":[
        "wishlist",
        "notifications",
        "language",
        "currencies",
        "order",
        "rating",
        "privacy",
        "about",
        "darkTheme"],
      "data":"",
      "url":"https://www.qutoof.qa",
      "title":"",
      "background":"null"
    }
  ],
  "Drawer":{
    "logo":null,
    "background":"assets/images/background/background-1.jpg",
    "items":[
      {
        "type":"home",
        "show":true
      },
      {
        "type":"blog",
        "show":false
      },
      {
        "type":"language",
        "show":true
      },
      {
        "type":"login",
        "show":true
      },
      {
        "type":"category",
        "show":true
      }
    ]
  },
  "Background":{
    "height":0.3,
    "image":"https://www.qutoof.qa/app/images/search/search_bg.jpg",
    "layout": "list"
  },
  "VerticalLayout":{
    "key":"thcld1ftf8",
    "layout":"list",
    "name":"All Items"},

  "searchSuggestion": [
    "Mango",
    "Apple",
    "Carrot",
    "Lemon",
    "Potato"
  ],

  "OnBoarding": {
    "data": [{
      "title": "Welcome to Qutoof",
      "image": "assets/images/fogg-delivery-1.png",
      "desc": "Stay home and leave it on us.",
      "background": "#FFF3F2"
    },
      {
        "title": "From all over the world",
        "image": "assets/images/fogg-uploading-1.png",
        "desc": "We make sure to bring you the best quality fresh products.",
        "background": "#F2FFFC"
      },
      {
        "title": "Let's Get Started",
        "image": "fogg-order-completed.png",
        "desc": "Waiting no more, let's see what we get!",
        "background": "#F9F2FF"
      }
    ]
  }
}
```

No: 4 - After i update there some text font not changing when i change language and minimize application then rep-open. every time i have to clear cache then change translation. 

No: 5 - Search Suggestions not working
No: 6 - Reject Apple store because of Apple Sign in Issues,

apple Signing Error publishing in apple Store We got this Message:  
---------------------
Hello,
Thank you for your re submission. However, upon further review, we found that your app is out of compliance with the following guideline(s):
Guideline 2.1 - Performance - App Completeness
We discovered one or more bugs in your app when reviewed on iPad and iPhone running iOS 13.6 on Wi-Fi.
Specifically, an error message appears when user attempts to sign in with Sign In with Apple option.
Next Steps
To resolve this issue, please run your app on a device to identify any issues, then revise and resubmit your app for review.
If we misunderstood the intended behavior of your app, please reply to this message in Resolution Center to provide information on how these features were intended to work.
For new apps, uninstall all previous versions of your app from a device, then install and follow the steps to reproduce the issue. For updates, install the new version as an update to the previous version, then follow the steps to reproduce the issue.
Resources
For information about testing your app and preparing it for review, please see Technical Note TN2431: App Testing Guide.
For a networking overview, please review About Networking.

Please see attached screenshot for details.
![attachment Screenshot-0724-063320](https://user-images.githubusercontent.com/18089254/88432244-81bc1700-ce04-11ea-8e5e-8cbe0e0a0431.png)

Thanks

**Comment by minhcasi** [comment]
@tgloc96 - pls help to check these issues

**Comment by omman** [comment]
Hi @minhcasi , 
There is new issue with ios app just release in app store our app [https://apps.apple.com/app/id1524135426](https://apps.apple.com/app/id1524135426) 
No: 1- but Not show the page if i click on card payment method, 
![IMG_0001](https://user-images.githubusercontent.com/18089254/88515719-d1f9cb80-cff4-11ea-8595-ce8b397bcacc.PNG)
![IMG_0002](https://user-images.githubusercontent.com/18089254/88515716-d0c89e80-cff4-11ea-8d09-a228066e9db1.PNG)
No: 2- also face recognize Iphone Latest Device phone can't signing with apple id because face recognize signing giving Null Value.
![WhatsApp Image 2020-07-23 at 10 33 17 AM](https://user-images.githubusercontent.com/18089254/88515776-e50c9b80-cff4-11ea-8ea2-8a65f4d2105a.jpeg)
No: 3 - Shipping method from woo-commerce from Shipping method zone, I didn't enable, but `**Pickup from store**` options, and `**Free delivery**` are showing all shipping method. sorry not payment method and we are using native payment screen so we use   /// Enable Payment option
  "EnableOnePageCheckout": false,
  "NativeOnePageCheckout": true,

![YjTgOce](https://user-images.githubusercontent.com/18089254/88516041-58161200-cff5-11ea-91a0-7698bb389b09.png)
![z9pIhYT](https://user-images.githubusercontent.com/18089254/88516045-59473f00-cff5-11ea-9316-8f69d061c628.jpg)


No: 4 - Not redirecting Second Language  or other language cart Page:
```
  // "CheckoutPageSlug": "checkout",
  "CheckoutPageSlug": {"en": "checkout", "ar": "ar/checkout"},

```
No: 5 - Not Showing My On boarding Screen it's Directly open home screen:
If i change the URL in lib/common/config.dart file Not showing On boarding Display

No: 6 - After i update there some text font not changing when i change language and minimize application then rep-open. every time i have to clear cache then change translation. 

Please Fix this issues

**Comment by minhcasi** [comment]
noted with investigating - could you send your final source and admin login to inspireui.team@gmail.com - we could not reproduce this issue on our latest code - thank you!

**Comment by omman** [comment]
Hi @minhcasi , Please check email inspireui.team@gmail.com i have send already. Thanks

**Comment by omman** [comment]
Hi @minhcasi ,

Can you please fix this issues that i mentioned because our ios app it's not working properly with the 1.7.6 version which is we update.

Thanks InspireUI

**Comment by minhcasi** [comment]
We wanted to thank you for your patience during this epidemic time. We currently have reduced staff and a significantly higher volume of inquiries. We’re working as hard as we can to get to your request as soon as possible.

@simonpham - please help to investigate on this issue

**Comment by omman** [comment]
@minhcasi thanks for your kind. We really very appreciate for you. 
Best Regards

**Comment by omman** [comment]
Hi plz check the issue it's already too late for us.

**Comment by simonpham** [comment]
Hi @omman 

We wanted to thank you for your patience during this busy time. We currently have reduced staff and a significantly higher volume of inquiries. We are working as hard as we can to reply to your request as soon as possible.

Regarding your issues, we are still investigating. Please stay tuned.

Thank you for using our products.

**Comment by omman** [comment]
Hi @simonpham , 

Thanks for your replying, yes we are waiting..we really appreciate and hope fix fix this issues as soon as possible because we already waiting too long we just asking because of we already publish the app with issues so public they are facing that issues. Thanks to InspireUI we love their all products. 

Best Regards

**Comment by omman** [comment]
hi @simonpham , Please inform us when we will receive this fix the[issues](https://github.com/inspireui/support/issues/4343#issuecomment-664178335)

**Comment by omman** [comment]
Hi @minhcasi @simonpham , there is new updates can i update this ? Then issues will fix? Please reply me.

**Comment by minhcasi** [comment]
@omman - we have fix the Shipping/Coupon and Login issue on latest `1.7.7` - pls try to update and let us know your checking - thanks

**Comment by minhcasi** [comment]
@omman - let us know your checking - thanks

**Comment by omman** [comment]
I can't run the version: 1.7.7 

`C:\src\flutter\flutter\bin\flutter.bat --no-color pub get
Running "flutter pub get" in source...                          

Because flutter_svg 0.18.0 depends on xml ^4.1.0 and every version of flutter_test from sdk depends on xml 3.6.1, flutter_svg 0.18.0 is incompatible with flutter_test from sdk.
So, because fstore depends on both flutter_test any from sdk and flutter_svg 0.18.0, version solving failed.
pub get failed (1; So, because fstore depends on both flutter_test any from sdk and flutter_svg 0.18.0, version solving failed.)
Process finished with exit code 1`
