### ISSUE TITLE
Stores not displayed in FLuxstore 1.7.6 with WCFM

### ISSUE THREAD

**Issue by aishema2000** [inspireui/support#4346]
**First of all Congratulations to the developers team for this fresh new version 1.7.6**

You can verify me with ticket #3151 

The issue is that the stores are not being displayed on the categories tab when using version 1.7.6. See the screenshot below:
![WhatsApp Image 2020-07-24 at 15 15 31](https://user-images.githubusercontent.com/15066381/88395082-c9b94a80-cdc0-11ea-9a76-c9d5a41b4d1e.jpeg)

It works very well with 1.7.5 version:
![WhatsApp Image 2020-07-24 at 15 16 40](https://user-images.githubusercontent.com/15066381/88395265-169d2100-cdc1-11ea-9e47-ff62b8d0e722.jpeg)

What Can I do?

**Comment by minhcasi** [comment]
@aishema2000 - we will investigate this issue and let you know

Would  you mind to share your project to inspireui.team@gmail.com? Thank you!

**Comment by aishema2000** [comment]
Dear @minhcasi thanks for your fast reply. I have sent you my project via email: inspireui.team@gmail.com as per your request. 

I am waiting for your usual kind support. :)

**Comment by aishema2000** [comment]
Dear @minhcasi any progress on the above issue?

**Comment by tgloc96** [comment]
Hello @aishema2000,
We were fixed this, please you download the file below and extract this file, you will see 2 files:
- **store_model.dart**
- **map_screen.dart**
Continue, overwrite these files with the following path:
- **store_mode.dart** in _lib/vendor/store/store_model.dart_
- **map_screen.dart** in _lib/vendor/stores_map/map_screen.dart_

[fix store.zip](https://github.com/inspireui/support/files/4986773/fix.store.zip)

**Comment by aishema2000** [comment]
Thank you, I am downloading right now, and will tell you the output

**Comment by aishema2000** [comment]
Dear @tgloc96 it is alright, I can see the list of vendors now.... BUT why the search form returns the list of vendors even if he has nothing to do with the searched terms?

See attached screen:
![WhatsApp Image 2020-07-28 at 10 17 25](https://user-images.githubusercontent.com/15066381/88638462-d341fb80-d0bb-11ea-9e36-16073ff96fc6.jpeg)

**Comment by tgloc96** [comment]
> Dear @tgloc96 it is alright, I can see the list of vendors now.... BUT why the search form returns the list of vendors even if he has nothing to do with the searched terms?
> 
> See attached screen:
> ![WhatsApp Image 2020-07-28 at 10 17 25](https://user-images.githubusercontent.com/15066381/88638462-d341fb80-d0bb-11ea-9e36-16073ff96fc6.jpeg)

Thank you for your feedback, I saw the problem and I am fixing this.

**Comment by minhcasi** [comment]
@minhtruong315 - please help to check the wcfm search endpoint from mstore-api, it could have an issue with the Search API - thank you!

**Comment by minhtruong315** [comment]
Hi @aishema2000 please update MStore Api plugin and try again

**Comment by aishema2000** [comment]
Hey @minhtruong315 . Thank you, the issue seems to be solved now.

Dear @minhcasi i have some suggestions:

1. On stores page, if we type a given product in tje search field, the search results should return a list of vendors having that product in their store.

2. On Search page, results should consider not only the product name but also many other elements such as descriptions, tags, categories, etc... that way the search function will be perfect and display accurate and meaningful results.

Again thank you for your kind support

**Comment by minhcasi** [comment]
@aishema2000 - thank you for your suggestion, we have noted these suggestions and send to the team to investigate the UX - very best

**Comment by aishema2000** [comment]
Hello, the fix provided above does not work with the new Version 1.7.7. 

![image](https://user-images.githubusercontent.com/15066381/90245362-d1559780-de32-11ea-9080-4f6a21dae16c.png)
Please check and let us know what do to
