### ISSUE TITLE
Support for ListingPro Bookings

### ISSUE THREAD

**Issue by crypto-vault** [inspireui/support#4347]
In Fluxstore Listing App will you add support for ListingPro Appointments now that it supports Bookings? Or for now only Listeo bookings are supported?

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 

Thank you for your time!

**Comment by minhcasi** [comment]
Yes, it is only support booking for the Listeo theme only, we will consider to upgrade this feature later - thank you!
