### ISSUE TITLE
FluxNews - All Categories not showing

### ISSUE THREAD

**Issue by debashisdey** [inspireui/support#4348]
Hi,

I am trying to build an android app with your Fluxnews code. I have installed the latest Flux Builder V 1.06 (12). I have  35 categories in wordpress (including sub categories) but I can only see 20 in the Flux builder and they are arranged alphabetically. 

Please help to show all categories.

Thanks.

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 
and please provide screenshots about your problem.
Thank you for your time!

**Comment by minhcasi** [comment]
@debashisdey - thank you for reporting, we will investigate this issue and let you know

**Comment by debashisdey** [comment]
I will clarify my question further. Since my site is a news site, I want to show all categories on the left drawer. Currently when I use the Flux builder , it shows only the home page categories which, I have chosen. 

Thanks.

**Comment by debashisdey** [comment]
Hi,

I have solved this issue - now I can see all categories. But I expected a fast reply to simple problems like this.

Now, I need help with one more thing:

How to completely disable the wishlist function - wishlist is ok for Fluxstore - but if you are selling this as a news app then wishlist is of no use altogether.

An early response will be much appreciated.

Thanks.

**Comment by dttrung26** [comment]
Hi @debashisdey , 
removing wisth list configuration at your config_[language].json file would disable this feature as you wish. You can find the wish list  config as under TabBar setting: 
```
 {
      "layout": "wishlist",
      "icon": "assets/icons/tabs/icon-heartthin.png"
    },
``` 
Let me know if it helps. 
Happy coding!

**Comment by debashisdey** [comment]
This will only remove the icon from the bottom bar, I want to remove the 'wishlist' function and all "heart" icons from all images and pages.

Thanks.

**Comment by dttrung26** [comment]
Hi @debashisdey ,
the wishlist function includes a wishlist screen and heart icons. If you remove the icon wishlist on tab bar and heart icons, this feature could be considered completely disabled. However, we haven't added remove heart icon configuration yet. You can find a way to work around that by using [Inspector Tool](https://flutter.dev/docs/development/tools/devtools/inspector) to identify heart icons on specific layout, then remove its code. Or you can wait for the next patch which will probably be released in next month. We will add this feature in next patch. 
If you are really in need of this feature but don't know how to use Inspector Tool, you can drop me the layouts you use on homepage. I'll remove those heart icons' code temporary for you when waiting for next update. 
Best!

**Comment by debashisdey** [comment]
Thanks, I can do that - removing the heart icon from all images. 

Right now, I have disabled the login function and market it false. But I am getting the sign in / login prompt on the third onboarding screen - **hep me to remove it.** 

There are lot of functions (inherited from fluxstore I believe which are unnecessary for a news app). This is also making the app complicated and heavy. The Fluxbuilder needs to be updated also. I hope you will take care of all these in the next release. If you want I can send a list of things which are not needed / option for a news app.

Regards.

**Comment by dttrung26** [comment]
Hi @debashisdey , 
Replacing the below file into your /lib/screens/home/ would remove login and register buttons. 
[Uploading issue#4348.zip…]()

Yes you are right, FluxNews is built from core code from FluxStore, which you may see some similar functionalities from FluxStore. If you could point out those errors or things that need to be fixed/updated, then your help would be very appreciated.
Please drop us an email via trung@inspireui.com about your suggestions. 

Cheers!

**Comment by debashisdey** [comment]
Thanks, I will send you the mail - there are many things which need to be listed :)

The app is looking great so far. I have removed all heart icons. 

Now, I need help with admob.

As a news app we cannot run reward ads. So I would request you to help me with two codes - I think everyone can benefit from this.

1. Admob banner code in the footer - global for all pages.
2. Interstitial ad with a duration control.

Thanks.

**Comment by dttrung26** [comment]
Hi @debashisdey, 
please  go to `/lib/common/config.dart`, at `kAdConfig`, change `"type": kAdType.googleBanner,` and don't forget to fill out all required id field listed below. As long as your configuration on Google Admob is correct, then you are good to go. 
Let me know if it helps,
Best!

**Comment by debashisdey** [comment]
Thanks for your help.

Actually, I am using it for Interstitials now: kAdType.googleInterstitial

Just wanted to add a banner at the footer of the detail post view page, as mentioned above.

Thanks.

**Comment by dttrung26** [comment]
Dear @debashisdey , 
currently FluxNews is able to display 1 advertisement type only. I'm truly sorry to say that your requirement is not available at the moment sir. 
Let me know if you still have any question.
Best.

**Comment by debashisdey** [comment]
Thanks, maybe you can help in the next update!

Can you give me the mdified code to move the tab bar just below the app bar / below the logo bar on top? 

I am attaching the tabbar.dart file in zip format.

Thanks again.
[tabbar.dart.zip](https://github.com/inspireui/support/files/4993144/tabbar.dart.zip)

**Comment by imbritto** [comment]
> Hi,
> 
> I have solved this issue - now I can see all categories. But I expected a fast reply to simple problems like this.
> 
> Now, I need help with one more thing:
> 
> How to completely disable the wishlist function - wishlist is ok for Fluxstore - but if you are selling this as a news app then wishlist is of no use altogether.
> 
> An early response will be much appreciated.
> 
> Thanks.

How did you fix the Categories issue? Mine is only showing 5 in emulator and 15 in fluxbuilder.

**Comment by debashisdey** [comment]
> > Hi,
> > I have solved this issue - now I can see all categories. But I expected a fast reply to simple problems like this.
> > Now, I need help with one more thing:
> > How to completely disable the wishlist function - wishlist is ok for Fluxstore - but if you are selling this as a news app then wishlist is of no use altogether.
> > An early response will be much appreciated.
> > Thanks.
> 
> How did you fix the Categories issue? Mine is only showing 5 in emulator and 15 in fluxbuilder.

The fluxbuilder is still under development - better to check on a emulator or device. 

I did some changes in the file >>  lib/services/wordpress.dart in the highlighted number to match number of categories.

`}

  Future<List<Category>> getCategories({lang = "en"}) async {
    try {
      var response = await blogApi
          .getAsync("categories?per_page=**20**&hide_empty=0&exclude=10");
      print('responseee $response');
      List<Category> list = [];
      for (var item in response) {
        if (item['slug'] != "uncategorized" && item['count'] > 0) {
          list.add(Category.fromJson(item));`

Also, I used the 'sidemenu' style in the tabbar at the bottom to get all categories in the tab. 

Hope this helps.

**Comment by imbritto** [comment]
Thanks for your help. its working
I have done this: 
categories?per_page=100&hide_empty=0&exclude=61,64,66,68,70,71,73,29,74,31,32,34,38,954,40,42,43,46,967,49,52,54,55")

**Comment by imbritto** [comment]
This is a bug/ misconfiguration, It should be added to the next update.

**Comment by debashisdey** [comment]
> This is a bug/ misconfiguration, It should be added to the next update.

I think it's the default configuration.

**Comment by debashisdey** [comment]
Hi dttrung26

I have solved almost all issues and ready to publish. The app looks good.  Just two questions , will be happy if you can guide me.

1. I have disabled login - is it possible to show the day/night theme button to the user > drawer or anywhere on the app .

2. The images are cached currently but it takes time to load. is it possible to use the fadeinimage function ? If yes, then where should I place the code. 

I will send you the list of changes required to make this a proper/news magazine app.

Thanks.

**Comment by minhcasi** [comment]
@debashisdey 

1. It's possible, you could copy the function from Setting page to apply to the Drawer from `tabbar.dart`

2. pls update `lib/common/tools.dart` the function `image`

**Comment by debashisdey** [comment]
Hi Minchasi,

I am new to flutter, but I will try the drawer part. Need help with the transparentimage code in tools.dart. File attached.

Please help.

[tools.zip](https://github.com/inspireui/support/files/5006146/tools.zip)

**Comment by debashisdey** [comment]
Hi,

I have done the dark/light theme on the drawer part.

I have also done the faded image part - but it happens only when the image loads in the final stage.. prior to that there is a blank placeholder which looks bad... can you help me there ?

Thanks.

**Comment by debashisdey** [comment]
Hi,

One more issue. Since I have disabled login, how do I activate the Notification by default ?

Thanks.

**Comment by minhcasi** [comment]
@debashisdey - we will investigate these issues and let you know

**Comment by debashisdey** [comment]
> @debashisdey - we will investigate these issues and let you know

What I think is you need to improve your support system. There is no question of investigating your own code. Most of the queries are remaining unanswered.

First, you have converted a store app into a news app without proper modification which is creating trouble for everyone. Next the guide does not address all issues and quite often points to external link. Also, its nowhere mentioned that one needs to know coding in Flutter at expert level to use this code and that it cannot be used out of the box.

If the code is written and developed by your team, then this answers should come instantly.

I hope you will improve the support for better sales and rating of your products.

Thanks.

**Comment by minhcasi** [comment]
@debashisdey - thank you for the feedback, our team is working hard to update more feature for the app and also upgrade more detail documents 😊

**Comment by dttrung26** [comment]
Hi @debashisdey ,

first of all, I truly apologize for any inconvenience that you are encountering when using FluxNews. After that, could you please list below all of problems that you are experiencing at the moment? I'll try you fix it first for temporary and update it in FluxNews as a permanent solution. 
Besides, I just want to let you know that I'm still looking for your suggestion on upgrading FluxNews via trung@inspireui.com. 😄 

Have a beautiful day!
