### ISSUE TITLE
Fluxnews-Issues with Profile/settings tab

### ISSUE THREAD

**Issue by imbritto** [inspireui/support#4349]
Hi there,

There are few issues with the Profile/settings tab.

1. Although IsRequiredLogin is set to false, I have to log in to access the Profile/settings tab. On the documentation, it says to change config/general.dart but there is actually no file called general.dart in fluxnews. 
2. Even if I log in, after leaving the app and launching the app again then clicking on the Profile/settings tap asks to login again. But before clicking on the Profile/settings tab if i click on any other tab (Categories/Search/Wishlist) then it doesn't ask to login again. Here is a video: https://youtu.be/qNGnqoAeZmU

Also not a bug but do you think I can change logging to comment function to a simple form like WordPress where user can fill name, email to comment? If yes, any help/guide would be much appreciatable.

Thanks for an awesome app.

**Comment by ameenbadri7** [comment]
Thank you for the feedback.
plesae use our template and take screenshots about your problem so we can know more about your problem sir.

And also lease help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 

Thank you for your time!

**Comment by imbritto** [comment]
> Thank you for the feedback.
> plesae use our template and take screenshots about your problem so we can know more about your problem sir.
> 
> And also lease help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.
> 
> We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission.
> 
> Thank you for your time!
> 
> > **[Google Forms - create and analyze surveys, for free.](http://verify.inspireui.com/)**Create a new survey on your own or with others at the same time. Choose from a variety of survey types and analyze results in Google Forms. Free from Google.

Done.

**Comment by haidarsalim** [comment]
I have the same problem and support could not solve the problem
https://github.com/inspireui/support/issues/4106
https://vimeo.com/436229643
I stopped the project because of it

**Comment by imbritto** [comment]
> I have the same problem and support could not solve the problem
> #4106
> https://vimeo.com/436229643
> I stopped the project because of it
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/c18f6972442b8ac6eface814b925c214fbdce3b7/68747470733a2f2f692e76696d656f63646e2e636f6d2f66696c7465722f6f7665726c61793f737263303d6874747073253341253246253246692e76696d656f63646e2e636f6d253246766964656f2532463932303833383130335f3132383078323736382e6a706726737263313d6874747073253341253246253246662e76696d656f63646e2e636f6d253246696d616765735f76362532467368617265253246706c61795f69636f6e5f6f7665726c61792e706e67">Vimeo**[trim8F52D28A-C81F-4B68-9A1E-F0652C4B5763](https://vimeo.com/436229643)**This is "trim8F52D28A-C81F-4B68-9A1E-F0652C4B5763" by 12312 123123 on Vimeo, the home for high quality videos and the people who love them.

Strange, If you download the fluxnews app from the appstore/playstore then it works fine. I hope support can fix it.

**Comment by dttrung26** [comment]
Hi @imbritto , 
1. Currently, `IsRequiredLogin` configuration just can strict user at OnBoardingScreen only in FluxNews. In terms of misunderstanding in docs, I think you may get those instructions in FluxStore docs, not FluxNews, which leave you confused. However, your report makes sense somehow. We will update this feature for FluxNews at next patch.
2. Thanks for reporting this bug. This is already added in bug fixing list and will be fixed in next patch. 
3. For the  simple form request, if more users wish to have this feature, we will consider implement it in the near future. 
Let me know if you still have any questions.
Happy coding!

**Comment by dttrung26** [comment]
Hi @haidarsalim , 
I'm sorry for misunderstanding your bug report at previous ticket. This bug will be fixed in next patch.
Hope you can stay with FluxNews in the near future. 
Happy coding!

**Comment by imbritto** [comment]
Thanks, I will be waiting for the update. Any ETA?

**Comment by dttrung26** [comment]
Hi @imbritto , it will be probably released the next month. 
Best!
