### ISSUE TITLE
Header Background Opaque Color, Bottom Navigation Text Under Icons

### ISSUE THREAD

**Issue by nucl123** [inspireui/support#4350]
Hi,
How can we achieve the below:

![image](https://user-images.githubusercontent.com/51371138/88421067-8a0a5700-cdf0-11ea-8d6e-be0431559455.png)

Please let us know, unable to find such option in fluxbuilder,

Thanks

**Comment by ameenbadri7** [comment]
You can add colors to the header by editing the `config_en.json` on  `lib\config\config_en.json` :
```
 "HorizonLayout": [
    {
      "layout": "logo",
      "showMenu": true,
      "showSearch": true,
      "showLogo": false,
      "color": "#4fc0e1"
    },

```

<img width="954" alt="111" src="https://user-images.githubusercontent.com/37524186/88432687-5ede3280-ce05-11ea-8834-06a795e1afef.png">


Also, you can make it sticky by activating the sticky header on  `config_en.json` file:
```
"Setting": {
..........
..........
    "StickyHeader": false
  },

```
<img width="959" alt="222" src="https://user-images.githubusercontent.com/37524186/88431800-b8ddf880-ce03-11ea-9e5f-763e2c08eda2.png">

To show text under the tab bar icons you have to change your config_en.json file like this : 
add 
 ```
"TabBar": [
    {
      "layout": "home",
      "label": "Home",
      "icon": "assets/icons/tabs/icon-home.png"
    },
    {
      "layout": "category",
      "label": "Category",
      "categoryLayout": "card",
      "isDisplay": true,
      "icon": "assets/icons/tabs/icon-category.png"
    },
    {
      "layout": "search",
      "label": "Search",
      "icon": "assets/icons/tabs/icon-search.png"
    },
    {
      "layout": "cart",
      "label": "Cart",
      "icon": "assets/icons/tabs/icon-cart2.png"
    },
    {
      "layout": "profile",
      "label": "Settings",
      "icon": "assets/icons/tabs/icon-user.png",
      "showChat": true
    }
  ],
```

For more info about this feature, you read about it inside our [documentation](https://docs.inspireui.com/fluxstore).

Thank you.

**Comment by nucl123** [comment]
> You can add colors to the header by editing the `config_en.json` on `lib\config\config_en.json` :
> 
> ```
>  "HorizonLayout": [
>     {
>       "layout": "logo",
>       "showMenu": true,
>       "showSearch": true,
>       "showLogo": false,
>       "color": "#4fc0e1"
>     },
> ```
> 
> <img alt="111" width="954" src="https://user-images.githubusercontent.com/37524186/88432687-5ede3280-ce05-11ea-8834-06a795e1afef.png">
> 
> Also, you can make it sticky by activating the sticky header on `config_en.json` file:
> 
> ```
> "Setting": {
> ..........
> ..........
>     "StickyHeader": false
>   },
> ```
> 
> <img alt="222" width="959" src="https://user-images.githubusercontent.com/37524186/88431800-b8ddf880-ce03-11ea-9e5f-763e2c08eda2.png">
> 
> To show text under the tab bar icons you have to change your config_en.json file like this :
> add
> 
> ```
> "TabBar": [
>    {
>      "layout": "home",
>      "label": "Home",
>      "icon": "assets/icons/tabs/icon-home.png"
>    },
>    {
>      "layout": "category",
>      "label": "Category",
>      "categoryLayout": "card",
>      "isDisplay": true,
>      "icon": "assets/icons/tabs/icon-category.png"
>    },
>    {
>      "layout": "search",
>      "label": "Search",
>      "icon": "assets/icons/tabs/icon-search.png"
>    },
>    {
>      "layout": "cart",
>      "label": "Cart",
>      "icon": "assets/icons/tabs/icon-cart2.png"
>    },
>    {
>      "layout": "profile",
>      "label": "Settings",
>      "icon": "assets/icons/tabs/icon-user.png",
>      "showChat": true
>    }
>  ],
> ```
> 
> For more info about this feature, you read about it inside our [documentation](https://docs.inspireui.com/fluxstore).
> 
> Thank you.

thanks

**Comment by nucl123** [comment]
![image](https://user-images.githubusercontent.com/51371138/88446839-1b4fec80-ce36-11ea-8466-864296de43c4.png)
Actually, just tried it, but it does not make a difference, the transparency remains same still.
