### ISSUE TITLE
CanNot add Listing type MyListing theme Fluxstore listing

### ISSUE THREAD

**Issue by waleedElleithi** [inspireui/support#4351]
There is no options in Fluxstore listing to add A Listing type, I prefer to add it instead of categories as the listing type are both Arabic and English so I can control what appears in the Arabic view and what appear in the English view 
if there is no options to show the Listing type , I want to display only the English categories in the English view and the Arabic categories in the Arabic view.

I appreciate your fast response 

![Screenshot_20200724-202346](https://user-images.githubusercontent.com/56982458/88423753-92609300-cdec-11ea-8dd9-5f5addfebd63.png)

**Comment by waleedElleithi** [comment]
I have already submitted the verification on  http://verify.inspireui.com

**Comment by minhcasi** [comment]
@waleedElleithi - thank you for your feedback, we will add the 'Create New Listing' on later version. 

Could you know if you are using the WMPL to support for the translation ?

**Comment by waleedElleithi** [comment]
yes,  I use WPML

**Comment by waleedElleithi** [comment]
hi team. plz update what is new with the issue

**Comment by philipvu30** [comment]
Hi,

Sorry for the delayed response as we don't work at the weekends.
About the issues you are facing, I quite don't get what you mean. What I understand are:
- You want to replace the categories with Listing types. -> Currently not support.
- If the option above is not supported, you want to distinguish the categories in English and Arabic. As the image you sent is the combination of English and Arabic categories. -> Need to inspect more on this issue.
Do I understand your ideas correctly?

**Comment by waleedElleithi** [comment]
yes, you understood correctly, The only way on Mylisting theme to distinguish English from Arabic is through the listing type.... Since your app is not supporting the Listing type feature so, what modifications I can apply in codes to distinguish English category from the Arabic category

**Comment by philipvu30** [comment]
Hi,

To achieve your goal, you have to modify both ListApp Mobile Manager plugin + FluxStore Listing app.
- Because the default endpoint of mylisting theme does not allow to filter by type. You have to write your own function and add it to the endpoint by yourself. Do this in ListApp Mobile Manager.
- In this file lib/services/listing.dart, you can start to modify the fetchProductsByCategory function to match the endpoint you created.

**Comment by waleedElleithi** [comment]
In this file lib/services/listing.dart, you can start to modify the fetchProductsByCategory function to match the endpoint you created.   **(Please give me one example)**

Plus
Unlike fluxstore for ecommerce, there are no Config_en.json and Config_ar.json to have different layout for each language
**How can I have different layout for each language?**
thanks

**Comment by waleedElleithi** [comment]
Guys, 

My request is very simple and logic, I tried fluxstore for ecommerce before and I didn;t go through such pain, you need to have detailed customization for Fluxstore Listing

I should see what is i**n Arabic in the Arabic view and what is English in the English** view (such as categories and other details under categories) and this is not the case in your app

I only see the English view everywhere however it is translated by WPML in the website, I even change Myisting to Listeo because you recommend it
So I want:
1- each language has its own category and detail as in the website 
2- Builder is not working with Listeo, any recommendation to solve the issue

Please check the screenshots 

hope you answer asap 
![sc1](https://user-images.githubusercontent.com/56982458/89758620-89f4a180-dae8-11ea-8218-92e34f411001.jpg)
![sc2](https://user-images.githubusercontent.com/56982458/89758633-8f51ec00-dae8-11ea-931b-a11bf85b7c16.jpg)
![Screenshot_20200810-084925](https://user-images.githubusercontent.com/56982458/89758663-9da00800-dae8-11ea-893d-c5c8f31b49e4.png)
![Screenshot_20200810-084915](https://user-images.githubusercontent.com/56982458/89758677-a55fac80-dae8-11ea-8eb3-6fcf96d4080f.png)
![Screenshot_20200810-084841](https://user-images.githubusercontent.com/56982458/89758687-a98bca00-dae8-11ea-8b90-e9c45c08a7fb.png)
![Screenshot_20200810-084822](https://user-images.githubusercontent.com/56982458/89758691-adb7e780-dae8-11ea-876a-4bd30d6370fa.png)

**Comment by waleedElleithi** [comment]
Hi team, 
any updates?

**Comment by waleedElleithi** [comment]
Hello team, 
I have been waiting for three days without a response from your side!!

**Comment by minhcasi** [comment]
@waleedElleithi - we will update the latest `1.4.3` to fix this issue - it will be ready in 1-2 days - thank you for your patience

**Comment by waleedElleithi** [comment]
Alright, I will be waiting, thank you

**Comment by minhcasi** [comment]
@waleedElleithi - the latest version is ready for download, please give a try and let us know your checking. 

You could use this method to merge with your previous code via Gitlab - https://medium.com/@inspireui/how-to-upgrade-fluxstore-projects-by-using-git-cebde7489ea6

**Comment by minhcasi** [comment]
Let us know if you have any question - thank you!
