### ISSUE TITLE
FluxStore license issue

### ISSUE THREAD

**Issue by Jegufull** [inspireui/support#4352]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

Hello, I want to inform you that my FluxStore license is being used on another website, which is not my property and is not allowing me to use the MStore API Plugin, I request that you change the ownership of this license to the merquex.com domain

Thank you very much for your help.

Jeimer

<img width="1440" alt="Captura de Pantalla 2020-07-24 a la(s) 4 34 54 p  m" src="https://user-images.githubusercontent.com/47310507/88437224-a47e0980-cdcb-11ea-9923-f0a62f73c9da.png">

<img width="1440" alt="Captura de Pantalla 2020-07-24 a la(s) 4 42 03 p  m" src="https://user-images.githubusercontent.com/47310507/88437711-a5636b00-cdcc-11ea-8d15-4c1a47a1c70f.png">

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@Jegufull - we have reset the license on your site, please help to active it again - i'm not sure why it is activation by other site but we will track the reason from our logs.

Thank you so much for your rating, i've upgraded your ticket to priority so that the team could be focus for the supporting, let us know if the code is working :)

**Comment by Jegufull** [comment]
@minhcasi Hello, I have activated the license and it works correctly, thank you very much for your support 👍🏼

**Comment by minhcasi** [comment]
Thank you for quick reply, let us know if you have any question ☺️
