### ISSUE TITLE
How to Chek version fluxtore ?

### ISSUE THREAD

**Issue by fahmiffa** [inspireui/support#4354]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by ameenbadri7** [comment]
Thank you for the feedback.
To find the version number : 
Open your fluxstore peoject file and go to `pubspec.yaml`file , on the line 14 you will find the  version number of fluxstore like this `version: 1.7.6+3001`.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ 
- please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 
Thank you for your time!

**Comment by fahmiffa** [comment]
ok thanks
