### ISSUE TITLE
not show additional infomartion ?

### ISSUE THREAD

**Issue by fahmiffa** [inspireui/support#4355]

**Comment by ameenbadri7** [comment]
Again Mr @fahmiffa 

Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 

Thank you for your time!
