### ISSUE TITLE
Rest API Issue 

### ISSUE THREAD

**Issue by ekramul-1** [inspireui/support#4357]
The REST API & Loopback requests failed due to an error.

**Comment by ekramul-1** [comment]
![image](https://user-images.githubusercontent.com/63785688/88448957-afcf4480-ce60-11ea-84b5-2a8064f05978.png)

**Comment by minhcasi** [comment]
@ekramul-1 - could I know what is the issues you are using to detect the REST API issue?

**Comment by ekramul-1** [comment]
@minhcasi  Pllease help me. the below things I checked already :-
![image](https://user-images.githubusercontent.com/63785688/88450423-6c7ad300-ce6c-11ea-9bb3-dd05ccd21f24.png)

**Comment by ekramul-1** [comment]
@minhcasi @luyx2412 
Please have a look

**Comment by minhcasi** [comment]
@ekramul-1 - this mostly cause from the server hosting site, please help to check with the hosting provider to upgrade your server setting, this issue could be similar with yours - https://www.dedoimedo.com/computers/wordpress-site-health-curl-error-28.html

**Comment by ekramul-1** [comment]
Found the issue, it's issue from razor pay plugins.

Thank you so much for your attention, but you took longer time to respond. Is their any way to get faster response.

**Comment by minhcasi** [comment]
Congratulation @ekramul-1  🎉

Please give us maximum 24h to response the ticket, we also support the private chat support via `MS Team` if you have purchased the extended License https://inspireui.com/support-policies/ - Hope you enjoy the product and stay safe 😊
