### ISSUE TITLE
Shipping Method Issue Amount Showing "0" zero. Fluxstore for woocommerce 

### ISSUE THREAD

**Issue by praveenasok** [inspireui/support#4359]
The shipping method after filling in the address is showing "0" zero in Fluxstore for woocommerce. The screen shot is attached below:

Product & version: FluxStore-woo-1.7.6
Flutter (or React Native) version: flutter_windows_1.17.5-stable
![sss](https://user-images.githubusercontent.com/68604976/88452788-40b51880-ce7f-11ea-81b0-2a4fdc0c229b.JPG)

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 

Thank you for your time!

**Comment by praveenasok** [comment]
Already done that

**Comment by minhcasi** [comment]
@praveenasok - could i know if you are using extra Shipping plugin, instead of using default woocommerce shipping?

Please note that using the extra plugin will not compatible with the default setting, then you need to use the OnePageCheckout setting - thank you!

**Comment by praveenasok** [comment]
I am using woocommerce table rate plugin.

**Comment by praveenasok** [comment]
It is not working on native screen. It does work on onepage checkout. But in one page checkout the header with the website menu also shows. 

![Screenshot_20200726-074750.jpg](https://user-images.githubusercontent.com/68604976/88469953-70623000-cf14-11ea-9836-136b66781853.jpg)

Is there a way to remove mobile menu

**Comment by ameenbadri7** [comment]
to make your custom payment method work use the webview option.
by editing your` lib\common\config\payments.dart` file: 

```
  "EnableOnePageCheckout": true,
  "NativeOnePageCheckout": false, 
```

and you can remove the menu from your UI layout by editing your `lib\config\config_en.json` file : 
```
 {
      "layout": "logo",
      "showMenu": false,
      "showSearch": true,
      "showLogo": true
    },
```

Thank you.

**Comment by praveenasok** [comment]
I am primarily not having an issue with Payment Option. The issue is with shipping method. It is understood now that you do not support woocommerce shipping plugins. 

Can I have a cone page checkout option and the menu of the desktop webview is hidden.

**Comment by minhcasi** [comment]
@praveenasok - yes - please give a try with the EnableOnePageCheckout then you could use with extra shipping plugin,  i'm not sure your idea from `the menu of the desktop webview is hidden` ?

**Comment by minhcasi** [comment]
Let us know if you have any question - thank you!
