### ISSUE TITLE
[Evastore] Query does not apply to a fresh store

### ISSUE THREAD

**Issue by cdalsoniii** [inspireui/support#436]
**Required Info (please complete the following information):**
 - Product: EvaStore
 - Your Purchased Code: ec8a5f43-b54d-418d-9bdf-df106d523b6d
(we may not reply if you are not our customer)

**Describe the bug**
Would it be possible to copy the beo shopify store? My queries and shopify categories likely do not sync up and it is creating som errors.

**Screenshots**

**Additional context**
Add any other detail logs about the problem here.
If possible please share your config.js that use for the app setting

**Comment by luyx2412** [comment]
Hi @cdalsoniii can you share me your screenshot?

Thanks

**Comment by cdalsoniii** [comment]
Can you provide an export of how categories are setup and products?

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by cdalsoniii** [comment]
I got an index of Array error because the query is not returning results. Can you give me a export of the categories and products on the beostore?

The categoryid does not seem to back up How did you get this value for category id?

categoryId: "Z2lkOi8vc2hvcGlmeS9Db2xsZWN0aW9uLzQyMTg1ODM4MQ==",

**Comment by cdalsoniii** [comment]
I see why you guys stopped developing the app. The query cost exceeds the max information allowed per request. If you allow people to copy the shopify store you created it should be fine but without that everyone will run into major issues trying to connect up the app to their store.

**Comment by luyx2412** [comment]
HI @cdalsoniii The reason we did not update new version, because we did not collect enough new feature and issues. And the app still work normal. Please make sure you installed right way follow the video https://www.youtube.com/playlist?list=PLcF-HiQy-jOLpn4F8p1nCpEdplyDM9kZQ

Thanks

**Comment by cdalsoniii** [comment]
I am still getting errors:

Invariant Violation: Objects are not valid as a React child (found: TypeError: undefined is not an object (evaluating 'json.error')). If you meant to render a collection of children, use an array instead.
    in RCTText (at Text.js:145)
    in TouchableText (at Text.js:268)
    in RCTView (at View.js:44)
    in AnimatedComponent (at TouchableOpacity.js:256)
    in TouchableOpacity (at MyToastContainer.js:57)
    in RCTView (at View.js:44)
    in MyToast (created by Connect(MyToast))
    in Connect(MyToast) (at Router.js:57)
    in RCTView (at View.js:44)
    in RCTView (at View.js:44)
    in AnimatedComponent (at react-native-drawer/index.js:713)
    in RCTView (at View.js:44)
    in Drawer (at MenuScale.js:33)
    in MenuScale (at LeftMenuContainer.js:77)
    in LeftMenuContainer (created by Connect(LeftMenuContainer))
    in Connect(LeftMenuContainer) (at Router.js:48)
    in Router (created by Connect(Router))
    in Connect(Router) (at App.js:108)
    in PersistGate (at App.js:107)
    in Provider (at App.js:106)
    in App (at registerRootComponent.js:17)
    in RootErrorBoundary (at registerRootComponent.js:16)
    in ExpoRootComponent (at renderApplication.js:34)
    in RCTView (at View.js:44)
    in RCTView (at View.js:44)
    in AppContainer (at renderApplication.js:33)

This error is located at:
    in RCTText (at Text.js:145)
    in TouchableText (at Text.js:268)
    in RCTView (at View.js:44)
    in AnimatedComponent (at TouchableOpacity.js:256)
    in TouchableOpacity (at MyToastContainer.js:57)
    in RCTView (at View.js:44)
    in MyToast (created by Connect(MyToast))
    in Connect(MyToast) (at Router.js:57)
    in RCTView (at View.js:44)
    in RCTView (at View.js:44)
    in AnimatedComponent (at react-native-drawer/index.js:713)
    in RCTView (at View.js:44)
    in Drawer (at MenuScale.js:33)
    in MenuScale (at LeftMenuContainer.js:77)
    in LeftMenuContainer (created by Connect(LeftMenuContainer))
    in Connect(LeftMenuContainer) (at Router.js:48)
    in Router (created by Connect(Router))
    in Connect(Router) (at App.js:108)
    in PersistGate (at App.js:107)
    in Provider (at App.js:106)
    in App (at registerRootComponent.js:17)
    in RootErrorBoundary (at registerRootComponent.js:16)
    in ExpoRootComponent (at renderApplication.js:34)
    in RCTView (at View.js:44)
    in RCTView (at View.js:44)
    in AppContainer (at renderApplication.js:33)

throwOnInvalidObjectType
    ReactNativeRenderer-dev.js:8779:6
reconcileChildFibers
    ReactNativeRenderer-dev.js:9842:31
reconcileChildren
    ReactNativeRenderer-dev.js:10306:6
updateHostComponent
    ReactNativeRenderer-dev.js:10734:4
performUnitOfWork
    ReactNativeRenderer-dev.js:14091:21
workLoop
    ReactNativeRenderer-dev.js:14129:41
renderRoot
    ReactNativeRenderer-dev.js:14226:15
performWorkOnRoot
    ReactNativeRenderer-dev.js:15193:17
performWork
    ReactNativeRenderer-dev.js:15090:24
performSyncWork
    ReactNativeRenderer-dev.js:15047:14
requestWork
    ReactNativeRenderer-dev.js:14925:19
scheduleWork
    ReactNativeRenderer-dev.js:14711:16
enqueueSetState
    ReactNativeRenderer-dev.js:7700:17
setState
    react.development.js:364:31
onStateChange
    connectAdvanced.js:220:24
notify
    Subscription.js:27:8
notifyNestedSubs
    Subscription.js:66:4
onStateChange
    connectAdvanced.js:217:10
dispatch
    redux.js:220:14
<unknown>
    operations.js:24:17
tryCatch
    es6-promise.js:410:20
invokeCallback
    es6-promise.js:425:21
publish
    es6-promise.js:393:21
publishRejection
    es6-promise.js:335:10
flush
    es6-promise.js:121:13
_callTimer
    JSTimers.js:152:14
callTimers
    JSTimers.js:405:17
__callFunction
    MessageQueue.js:349:47
<unknown>
    MessageQueue.js:106:26
__guard
    MessageQueue.js:297:10
callFunctionReturnFlushedQueue
    MessageQueue.js:105:17

**Comment by cdalsoniii** [comment]
Is there a way your team can do an install for me?

**Comment by cdalsoniii** [comment]
This is the format of the new category:

categoryId: "gid://shopify/Collection/68566188095",

Also, available for sale is not on the product object. Have you tested these queries with the newest version of the graphql shopify schema?

**Comment by luyx2412** [comment]
Hi @cdalsoniii 
- We did not support install, you can check service https://inspireui.com/services/
- Your category id was wrong format. Please follow and check again how to get category id. This is specific video about get category id https://www.youtube.com/watch?v=nE7a_yx5Q9w&list=PLcF-HiQy-jOLpn4F8p1nCpEdplyDM9kZQ&index=4&t=0s

Thanks

**Comment by cdalsoniii** [comment]
Attached is my Config.js file. Am I setting something up wrong?

vigint.io is my store. Please let me know if you need an invite to my store.

`/** @format */

import Images from "./Images";
import Constants from "./Constants";
import Icons from "./Icons";

export default {
  /**
   * Step 1: change to your website shopify URL, apiKey, graphqlUrl, and storeAccessToken
   * https://help.shopify.com/en/api/custom-storefronts/storefront-api/getting-started
   */
   /*
  Shopify: {
    url: "beostore.myshopify.com",
    apiKey: "6ca99f4aa9683d9b813ee06b182a897d",
    graphqlUrl: "https://beostore.myshopify.com/api/graphql",
    storeAccessToken: "3e702f1189b419b9899f9e86c9a615a9",
  },
*/
Shopify: {
url: "vigint.myshopify.com",
apiKey: "e6197727f1ddd90e3434d0286472d71f",
graphqlUrl: "vigint.myshopify.com/api/graphql",
storeAccessToken: "9dd7fb2fb89dcb893312004d67a88de4",
},
  // to config custompage
  Wordpress: {
    url: "http://mstore.io",
  },

  /**
     Step 2: Setting Product Images
     - ProductSize: Explode the guide from: update the product display size: https://mstore.gitbooks.io/mstore-manual/content/chapter5.html
     The default config for ProductSize is disable due to some problem config for most of users.
     If you have success config it from the Wordpress site, please enable to speed up the app performance
     - HorizonLayout: Change the HomePage horizontal layout - https://mstore.gitbooks.io/mstore-manual/content/chapter6.html
     */
  ProductSize: {
    enable: false,
    CatalogImages: { width: 300, height: 360 },
    SingleProductImage: { width: 600, height: 720 },
    ProductThumbnails: { width: 180, height: 216 },
  },

  /**
   * Step 3: Setting Home screen, category screen
   * Follow this article to use Graphql https://help.shopify.com/en/api/custom-storefronts/storefront-api/graphql
   * Video tutorial https://www.dropbox.com/s/m4kmp0quh8qplz3/Screen%20Recording%202018-11-05%20at%202.22.21%20PM.mov?dl=0
   */
  SpaceLayout: 15, // setting align right
  HorizonLayout: [
    {
      //categoryId: "Z2lkOi8vc2hvcGlmeS9Db2xsZWN0aW9uLzQyMTg1ODM4MQ==",
      categoryId: "Z2lkOi8vc2hvcGlmeS9Db2xsZWN0aW9uLzY4NTY2ODEwNjg3",
      paging: true,
      layout: Constants.Layout.miniBanner,
    },
    {
      name: "Feature Products",
      //categoryId: "Z2lkOi8vc2hvcGlmeS9Db2xsZWN0aW9uLzQzOTA1MTUzMw==",
      categoryId: "Z2lkOi8vc2hvcGlmeS9Db2xsZWN0aW9uLzY4NTY2ODEwNjg3",
      layout: Constants.Layout.threeColumn,
    },
    {
      name: "Bags",
      categoryId: "Z2lkOi8vc2hvcGlmeS9Db2xsZWN0aW9uLzY4NTY2ODEwNjg3",
      layout: Constants.Layout.twoColumn,
    },
    {
      name: "Woman",
      categoryId: "Z2lkOi8vc2hvcGlmeS9Db2xsZWN0aW9uLzY4NTY2ODEwNjg3",
      layout: Constants.Layout.twoColumnHigh,
    },
    {
      name: "Man",
      categoryId: "Z2lkOi8vc2hvcGlmeS9Db2xsZWN0aW9uLzY4NTY2ODEwNjg3",
      layout: Constants.Layout.card,
    },
    {
      name: "News",
      type: "article",
      layoutType: "post", // "post" or "product" is default
      layout: Constants.Layout.threeColumn,
    },
  ],

  CategoryLayout: {
    ListMode: "ListMode",
    GridMode: "GridMode",
    CardMode: "CardMode",
  },

  /**
   * Now we only support Webview payment, so disable this feature
   * In the furture we will try support this feature
   */
  Payments: [
    // {
    //   name: "Cash on Delivery",
    //   imageUrl: require("@images/payment_logo/cash_on_delivery.png"),
    //   enabled: true,
    // },
    // {
    //   type: "card",
    //   name: "Credit Card",
    //   imageUrl: require("@images/payment_logo/credit_card.png"),
    //   enabled: true,
    // },
  ],

  /**
     Step 4: Advance config:
     - showShipping: option to show the list of shipping method
     - showStatusBar: option to show the status bar, it always show iPhoneX
     - LogoImage: The header logo
     - CustomPages: Update the custom page which can be shown from the left side bar (Components/Drawer/index.js)
     - intro: The on boarding intro slider for your app
     - menu: config for left menu side items (isMultiChild: This is new feature from 3.4.5 that show the sub products categories)
     * */
  shipping: {
    visible: true,
    time: {
      free_shipping: "4 - 7 Days",
      flat_rate: "1 - 4 Days",
      local_pickup: "1 - 4 Days",
    },
  },
  showStatusBar: true,
  LogoImage: require("@images/logo.png"),
  CustomPages: { contact_id: 10941 },

  /**
   * Config Menu Side Drawer
   * @param goToScreen 3 Params (routeName, params, isReset = false)
   * BUG: Language can not change when set default value in Config.js ==> pass string to change Languages
   */
  menu: {
    // has child categories
    isMultiChild: true,
    // Unlogged
    listMenuUnlogged: [
      {
        text: "Login",
        routeName: "Login",
        params: {
          isLogout: false,
        },
        icon: Icons.MaterialCommunityIcons.SignIn,
      },
    ],
    // user logged in
    listMenuLogged: [
      {
        text: "Logout",
        routeName: "Login",
        params: {
          isLogout: true,
        },
        icon: Icons.MaterialCommunityIcons.SignOut,
      },
    ],
    // Default List
    listMenu: [
      {
        text: "Shop",
        routeName: "Default",
        icon: Icons.MaterialCommunityIcons.Home,
      },
      {
        text: "About",
        routeName: "CustomPage",
        params: {
          url: "http://inspireui.com",
        },
        icon: Icons.MaterialCommunityIcons.Email,
      },
    ],
  },
};
`

**Comment by cdalsoniii** [comment]
This is a more readable version.

[Config.txt](https://github.com/inspireui/support/files/3073271/Config.txt)

**Comment by cdalsoniii** [comment]
I do not understand what part after and cursor play in the query. AvailableforSale also does not exist on my products. I had to remove all of those things to get the queries to run on my store. 

This is my modified Schema.js file. I also do not know where you log to the console 

[Schema.txt](https://github.com/inspireui/support/files/3073323/Schema.txt)

**Comment by luyx2412** [comment]
Hi @cdalsoniii you can read the document to understand about `cursor` https://graphql.org/learn/pagination/ and read the article about graphql in Shopify https://help.shopify.com/en/api/getting-started/shopify-and-graphql/mutations. 

P/S: Sorry about reply you late and feel free when open the issue.

Thanks
