### ISSUE TITLE
When user Clicks on bottom nav bar, I get this error

### ISSUE THREAD

**Issue by cloudfrontfactory** [inspireui/support#4364]
![mistore](https://user-images.githubusercontent.com/64742281/88458674-62c58f80-cead-11ea-915c-774326190fb0.jpeg)

check the url for the error, I need refund. The UI looks pathetic. 

Thanks
Chandra
Verified Buyer.

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 

Thank you for your time!

**Comment by minhcasi** [comment]
refunded
