### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by tammam-963** [inspireui/support#4365]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

there is an issue with the app during request the data, 
please contact the admin for fixing the issues 
**NoSuchMethodError: The getter 'methodid' was called on null Receiver: null**

***multi vendor app v1.7.6 flutter**

***testing on physical device**

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 

Thank you for your time!

**Comment by MorisTech** [comment]
> **_Step 1 (require): describe detail issues & screenshots_**
> 
> * Detail Issues:
> * Product & version:
> * Flutter (or React Native) version:
> * Testing Device/Simulator:
> * Screenshot issues (drag the file to attach here):
> 
> there is an issue with the app during request the data,
> please contact the admin for fixing the issues
> **NoSuchMethodError: The getter 'methodid' was called on null Receiver: null**
> 
> ***multi vendor app v1.7.6 flutter**
> 
> ***testing on physical device**
> 
> **_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**
> 
> **_Important Note:_**
> 
> * Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
> * Kindly create only _One Ticket_ & includes all the issues, that would help us focus to resolve it better.
> * If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID
> 
> Thank you so much for your time 😊

is it when you register?

**Comment by minhcasi** [comment]
verified ✅

**Comment by minhcasi** [comment]
@tammam-963 - could you help to share the screenshot issue? 

Please give a try to test if you Device could open your website URL, if you are using localhost please make sure to follow this guide https://www.youtube.com/watch?v=CEyfZmzBMTw&t=814s

**Comment by tammam-963** [comment]
mobile app open checkout on the web i need native payment within the app

because if the web checkout open the user cant use address search using google map 

my problem when i make checkout choosing address -> review -> **payment (here is my problem)** 

 - then i disable razorpay because of webhook or webview.

 also paypal or pay on delivery is not showing as native

i am not using localhost

**Comment by tammam-963** [comment]
![Simulator Screen Shot - iPhone 11 Pro - 2020-07-26 at 05 22 50](https://user-images.githubusercontent.com/47929858/88470788-5a973f80-cf01-11ea-91b7-47ee1adc3ad8.png)

**Comment by tammam-963** [comment]
════════ Exception caught by gesture ═══════════════════════════════════════════
The following NoSuchMethodError was thrown while handling a gesture:
The getter 'isNotEmpty' was called on null.
Receiver: null
Tried calling: isNotEmpty

When the exception was thrown, this was the stack
#0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:53:5)
#1      _PaymentMethodsState.placeOrder 
package:fstore/…/checkout/payment_screen.dart:343
#2      _PaymentMethodsState.build.<anonymous closure> 
package:fstore/…/checkout/payment_screen.dart:243
#3      _InkResponseState._handleTap 
package:flutter/…/material/ink_well.dart:779
#4      _InkResponseState.build.<anonymous closure> 
package:flutter/…/material/ink_well.dart:862
...
Handler: "onTap"
Recognizer: TapGestureRecognizer#6beba
    debugOwner: GestureDetector
    state: ready
    won arena
    finalPosition: Offset(171.3, 488.3)
    finalLocalPosition: Offset(156.3, 26.8)
    button: 1
    sent tap down

**Comment by tammam-963** [comment]
it's work after i delete razorpay plugin

how about stripe payment gateway

**Comment by minhcasi** [comment]
The stripe payment will work as the same via WebView - thank you!

**Comment by tammam-963** [comment]
i am stuck at app release can you take a look i use macincloud for using ios and android

**Comment by minhcasi** [comment]
Let us know if you have any questions and screenshots issues. Please note that we will not support answering or support technical issues for the regular license as per support policies - https://inspireui.com/support-policies/ - Hope you enjoy the product and stay safe 😊

**Comment by tammam-963** [comment]
I AM RUNNING APP ON XCODE 11.5 SIMULATOR IOS VERSION 13.6 AND APP STUCK AT SPLASH-SCREEN 

WHAT SHOULD I DO ?

**Comment by tammam-963** [comment]
![mypic1](https://user-images.githubusercontent.com/47929858/88664605-5c722600-d0ee-11ea-9d08-5f10793305a1.png)
![mypic2](https://user-images.githubusercontent.com/47929858/88664608-5e3be980-d0ee-11ea-958f-df2b2ca15af4.png)

**Comment by tammam-963** [comment]
a lot of deprecated libraries

**Comment by tammam-963** [comment]
if no solutions i will build again from zero all customization i have done it

**Comment by tammam-963** [comment]
![mypic3](https://user-images.githubusercontent.com/47929858/88713394-4b480a00-d12c-11ea-94db-b59c531b78e9.png)


i have follow this https://documentation.onesignal.com/docs/flutter-sdk-setup 

and generate app id for both android and ios now i stopped at oneSignalNotificationServiceExtension error in last picture

**Comment by minhcasi** [comment]
It seems you have not downloaded this file

<img width="1153" alt="Screen Shot 2020-07-29 at 14 17 54" src="https://user-images.githubusercontent.com/1459805/88769195-517acc80-d1a6-11ea-8659-91def25d2f04.png">

**Comment by tammam-963** [comment]
![mypic4](https://user-images.githubusercontent.com/47929858/88772731-3aca7a80-d192-11ea-8a2a-887d02a4ba90.png)

**Comment by tammam-963** [comment]
i write command in terminal 

flutter clean 

flutter pub get

flutter pub upgrade 

flutter build ios

**Comment by tammam-963** [comment]
![mypic5](https://user-images.githubusercontent.com/47929858/88773184-df4cbc80-d192-11ea-97d9-62085a80c0dc.png)

**Comment by tammam-963** [comment]
flutter clean

flutter run


![mypic6](https://user-images.githubusercontent.com/47929858/88773812-abbe6200-d193-11ea-88d1-ba0e82d1a0e8.png)

**Comment by tammam-963** [comment]
i start from zero 

i open tools/change-bundleid.conf

change the android package name

and in terminal as mentioned 

bash tools/change-bundleid.sh

same for ios package

**Comment by tammam-963** [comment]
what should i do 

remove ios file and run 

flutter create ios ?

**Comment by tammam-963** [comment]
i solve the problem it was from name of the file  :)

**Comment by tammam-963** [comment]
when i solve problem for ios version another for android released  

if there is any kind of authentication variable between server and the app tell about it i will not touch it

**Comment by tammam-963** [comment]
Thread 1: Exception: "Google Maps SDK for iOS requires GoogleMaps.bundle to be part of your target under 'Copy Bundle Resources'"

**Comment by minhcasi** [comment]
@tammam-963 - pls try to clean up the cache - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

**Comment by tammam-963** [comment]
OK now one last thing how to put location for store 

from dokan plugin or from flutter code

**Comment by minhcasi** [comment]
We're glad that it help, please give us some feedback/rating to this page https://codecanyon.net/downloads  if the product is helpful for your business, we are working hard to update more awesome and powerful features on next coming version release. Let us know if you have any feedback. Thank you very much 😊

**Comment by tammam-963** [comment]
Your Android App Bundle is signed with the wrong key. Ensure that your App Bundle is signed with the correct signing key and try again:SHA1: 18:65:83:17:FF:BB:85:A8:8E:45:E6:D5:2D:54:90:B3:68:41:3B:CD.

**Comment by tammam-963** [comment]
1.0 Binary Rejected 

how to resolve this issue
