### ISSUE TITLE
Error in FluxNews

### ISSUE THREAD

**Issue by kinan9011** [inspireui/support#4366]
Hi 

I am using FluxNews and I have this questions:

**1- When I try to change to dark mode or to change the language I get this Error:**
 **Update:** the flare animation file (splashscreen.flr) cause this error. so for now I can only use splashscreen.png.
please fix this.

![Screenshot_20200726-022418 resized](https://user-images.githubusercontent.com/68794874/88468187-1cd5ef00-cee0-11ea-9c2c-3ff72b5874ef.png)

[Solved] 2- I can't see the settings without registration ( "IsRequiredLogin": false,). and I don't want to force the user to register
[Solved] 3- how can I use url_launcher in drawer, (i want to use url_launcher instead of WebView):
[Solved] 4- is it possible to add menu in a drawer ? (like categories menu)** 
[Solved] 5- Is it possible to active smartchat in every tab?

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
Thank you for the feedback. Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission.

Note: we will not support answering or support technical issues for the regular license as per support policies - https://inspireui.com/support-policies/

Thank you for your time!

**Comment by minhcasi** [comment]
verified ✅

@dttrung26 - please help to check the dark mode issue

**Comment by dttrung26** [comment]
Fixed in FluxNews next patch. For any issue, please refer to our new support system: [support.inspireui.com](https://support.inspireui.com/help-center)
