### ISSUE TITLE
FluxStore Pro Prestashop - Issue with on sale price showing negative but website showing the right price

### ISSUE THREAD

**Issue by wassimdossani13** [inspireui/support#4367]
**_Step 1 (require): describe detail issues & screenshots_**

Website showing the right price for the item. But mobile app is showing negative price for the products.

<img width="361" alt="Screen Shot 2020-07-25 at 8 42 35 PM" src="https://user-images.githubusercontent.com/68796840/88469468-7fff5b80-ceb7-11ea-9636-34b5c9790345.png">

FluxStore Prestashop version 1.7.6

[Stumpler](https://www.stumpler.com) website stumpler.com

+ Detail Issues: 

Products which have special pricing are showing negative price, but products without special pricing it is good.

+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 

Simulator: iPhone 11 Pro Max

+ Screenshot issues (drag the file to attach here): 

<img width="361" alt="Screen Shot 2020-07-25 at 8 42 35 PM" src="https://user-images.githubusercontent.com/68796840/88469539-0a47bf80-ceb8-11ea-9442-7b80733fd29b.png">

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**
verified ✅

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@vumanhsn97 - please help to check the issues

@wassimdossani13 - would you mind to share your config file to inspireui.team@gmail.com - thank you!

**Comment by wassimdossani13** [comment]
Sent

**Comment by wassimdossani13** [comment]
Sorry just wanted to check if you received my e-mail. Thanks & Regards

**Comment by wassimdossani13** [comment]
@vumanhsn97 

Hello,

I wanted to check if you received my e-mail regards the issue. I emailed the config file to you.

Thanks & Regards,

Wassim Dossani

**Comment by vumanhsn97** [comment]
@wassimdossani13 
Your email has been received. Update this module to fix sale price issue: 
[customapi.zip](https://github.com/inspireui/support/files/4979890/customapi.zip)
Thanks!

**Comment by wassimdossani13** [comment]
@vumanhsn97 

Thank you that worked.

Another issue that i am having is getting the push notification to work with onesignal as that was already installed on ios

**Comment by wassimdossani13** [comment]
it keeps saying 

WARNING: OneSignal has detected that your application delegate implements a deprecated method (application:didReceiveLocalNotification:). Please note that this method has been officially deprecated and the OneSignal SDK will no longer call it. You should use UNUserNotificationCenter instead

**Comment by minhcasi** [comment]
no worry about the warning, it will be fixed when update upgrades the onesignal flutter library from `pubspec.yalm` - thank you!

**Comment by wassimdossani13** [comment]
Thank you for quick reply @minhcasi 

But my iphone does not receive any push notification when i try to send it. And when i checked at onesignal it tells me Apns Delegate Never Fired

**Comment by wassimdossani13** [comment]
Just and update I decided to use the firebase as push notification and solved. Thank you so much @minhcasi 

But just wanted to know if there is a guide to use webview payment method for fluxstore prestashop and if there is guide to it that I can follow to set it up. Thank you so much and appreciate the help.

**Comment by wassimdossani13** [comment]
Hello,

Sorry to bother, but as the web view checkout is not available on this product. I was wondering if you have a guide to remove the stripe payment option and the cod payment option from the checkout screen, so I can launch the mobile app. I would greatly appreciate any help that I can get for this please. 

Thank you

**Comment by vumanhsn97** [comment]
@wassimdossani13 
You can disable from your site by this step:
 - install this module: 
[customapi.zip](https://github.com/inspireui/support/files/4998631/customapi.zip)
 - set your payment module active = 0 in ps_module table https://tppr.me/FxGNo
You can disable from your app by replacing this code in lib/services/prestashop.dart https://tppr.me/XgszA
  @override
  Future<List<PaymentMethod>> getPaymentMethods(
      {Address address, ShippingMethod shippingMethod, String token}) async {
    List<PaymentMethod> lists = [];
    List<int> idDisable = [1, 2, 3]; //id your module need to disable
    var payment = await prestaApi.getAsync('payment?display=full');
    for (var item in payment['taxes']) {
      if (idDisable.firstWhere(
              (element) => element.toString() == item['id'].toString(),
              orElse: () => null) !=
          null) continue;
      lists.add(PaymentMethod.fromPrestaJson(item));
    }
    return lists;
  }

**Comment by wassimdossani13** [comment]
Thank you for the advice and the correction, but soon as I tried that I got another error trying to install on the phone. I have attached the screen shot along. Please advice.
![Screen Shot 2020-07-30 at 12 53 58 AM 1](https://user-images.githubusercontent.com/68796840/88886103-659ee800-d1ff-11ea-9dc3-ea70ff46e9aa.png)

**Comment by wassimdossani13** [comment]
Also Just realized products with combinations such as color or size cannot be added to cart all it says loading on the mobile app. Please if you could help me with this. Again appreciate all the help that I am getting from you. thank you @vumanhsn97

**Comment by wassimdossani13** [comment]
@vumanhsn97 @minhcasi 

**Thank you for the payment thing update**. After I realized properly what you were asking to do it did work but without the api update that you send I used the old one, or else it was giving me error on the shipping method selection on the checkout screen. But all working now. Again Thank you so much for that.

I know and understand that you are helping as much as possible, but there is issues with the app itself for launching. Please if I could get priority help I would really appreciate it. And willing to pay extra for help. Just need to get this thing going. 

I will list all the issues that I see for now:

**1) Search Not Working**
![Screen Shot 2020-07-30 at 4 15 14 AM](https://user-images.githubusercontent.com/68796840/88904920-4ca43000-d21b-11ea-8bf2-6db368bd6b68.png)

**2) Not pulling the address from the Login automatically which is store on the prestashop database for the customer.**
![Screen Shot 2020-07-30 at 4 17 21 AM](https://user-images.githubusercontent.com/68796840/88905144-99880680-d21b-11ea-87eb-5ccbeb881c0b.png)

**3) Product Cannot Be Added to Cart If it has attributes such as color or size, but other products without that it works.**
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-07-30 at 04 25 36](https://user-images.githubusercontent.com/68796840/88906173-bbce5400-d21c-11ea-869b-4b56ffed7bfb.png)

**4) Even after I set hideourofstock from lib/common/config/general.dart**
It does not hide those products.
![Screen Shot 2020-07-30 at 4 30 54 AM](https://user-images.githubusercontent.com/68796840/88906796-7bbba100-d21d-11ea-965a-f5a1a99d3d9b.png)

**5) Push Notifications not working on real device**
Push notification does get delivered inapp through firebase. 
But when using OneSignal push notification not working.
![Screen Shot 2020-07-30 at 4 35 07 AM](https://user-images.githubusercontent.com/68796840/88907361-25029700-d21e-11ea-945d-892a66f2e8ed.png)

I understand, I do have a list to get fixed but I will really appreciate the help, and as mentioned I don't mind paying for the priority help.

Thanks & Regards,

Wassim Dossani

**Comment by wassimdossani13** [comment]
Sorry for cont.....

Another issue which is with android

**1) App keeps crashing soon as the install**

**Comment by wassimdossani13** [comment]
Hello,

I do have most of it fixed the only things pending from the list is 

1) Search Not Working

![](https://user-images.githubusercontent.com/68796840/88904920-4ca43000-d21b-11ea-8bf2-6db368bd6b68.png)

2) Push Notification

![](https://user-images.githubusercontent.com/68796840/88907361-25029700-d21e-11ea-945d-892a66f2e8ed.png)


3) Product Cannot Be Added to Cart If it has attributes such as color or size, but other products without that it works.

![](https://user-images.githubusercontent.com/68796840/88906173-bbce5400-d21c-11ea-869b-4b56ffed7bfb.png)


Please if you could help Number 3 problem is very urgent and then 2 and then 1.

Thanks & Regards

**Comment by vumanhsn97** [comment]
@wassimdossani13 
update this module to fix issue 3: 
[customapi.zip](https://github.com/inspireui/support/files/5005440/customapi.zip)
issue 2: try to check by your self
issue 1: it is working well. May be fixed in other issue. Please waiting for next release https://tppr.me/Ye5Qo
Thank!

**Comment by wassimdossani13** [comment]
Hello @vumanhsn97 

Thank you for the module but on the checkout screen under shipping method selection I get error
type 'String' is not a subtype of type 'int' of 'index'

![IMG_0411](https://user-images.githubusercontent.com/68796840/89006982-7d44a200-d2cd-11ea-93e8-0ff4e5c1b997.PNG)

Thanks & Regards

**Comment by wassimdossani13** [comment]
If I use the old customapi.zip then the shipping works and the product to cart stops working, but when I use the new customapi.zip that you sent yesterday problem 3 fixes but starts the new problem with the shipping method "type 'string' is not a subtype of type 'int' of 'index'

Thanks

**Comment by wassimdossani13** [comment]
Hello @vumanhsn97 

Sorry to keep bothering you. But do you have any update how to fix that issue with the shipping method. As that is the only thing preventing me from publishing the app now.

Thanks & Regards

**Comment by wassimdossani13** [comment]
Hello @vumanhsn97 

Thank you so much, I was able to fix it using the old customapi and the new customapi that you sent. App all working, just waiting for the new update for the search to work. Also I don't have the gitlab as never got the e-mail for that.

Thanks & Regards

**Comment by minhcasi** [comment]
@wassimdossani13 - would you mind to resent the form again via http://gitlab.inspireui.com - it seems the team misses your request so that they did not update gitlab account - thank you!

**Comment by wassimdossani13** [comment]
Hello @minhcasi 

is there a guide to doing web view payments setup for other carriers? If you don't mind guiding me in the right direction please.

Thanks & Regards

**Comment by wassimdossani13** [comment]
Sorry to bother again but major issue on product page

<img width="364" alt="Screen Shot 2020-08-03 at 3 31 31 AM" src="https://user-images.githubusercontent.com/68796840/89162600-ee888d00-d539-11ea-9198-68943ad26f70.png">

**Comment by minhcasi** [comment]
sorry i'm not sure to understand this point `web view payments setup for other carriers` - could you give the screenshot of this screen your website?

**Comment by wassimdossani13** [comment]
I mean like we use secure submit payment gateway or acima financing. Is there a way to process those payments through webview or somehow on the mobile app. if there is a guide to doing that I would appreciate so I can work with something.

![Screen Shot 2020-08-03 at 10 51 19 PM](https://user-images.githubusercontent.com/68796840/89251201-0f092380-d5dc-11ea-8ca4-9d03b1ba8b0f.png)

**Comment by minhcasi** [comment]
@wassimdossani13 - pls try to update this option from `config/payment.dart` to enable the one page checkout

```
  "EnableOnePageCheckout": true,
  "NativeOnePageCheckout": false,
```

**Comment by wassimdossani13** [comment]
if I do that, lets say if I am using pay by credit card (secure submit) then it will just send me to confirmation page without asking for credit card information to charge the credit card from the purchase.

**Comment by minhcasi** [comment]
"it will just send me to confirmation page without asking for credit card information" -> could you help to take the screenshot of these issues? Do these steps happen when enabling the payment with Webview?

**Comment by wassimdossani13** [comment]
Hello,

I have attached 2 videos along with this. 
1) mobile app the web view payments right after shipping, I can select the payment method such as stripe, PayPal or Acima. 
But the issue is the only thing working is PayPal where customer goes to pay via credit card. But if they choose stripe or Acima the order just goes through without asking for the credit card, or the information needed to process the payment.

https://stumpler.com/video/videophone.mov

2) Working of all the payment module on the website, so you can see the flow that its working online but just not in the mobile app.

https://stumpler.com/video/videowebsite.mov

I have to upload the video to our server because GitHub didn't allow me to attach it in here.

**Comment by minhcasi** [comment]
@wassimdossani13 - please help to update the latest release with some bug fix. 

The current release of Fluxstore Prestashop is not fully supported for Webview, we will investigate the Prestashop API and keep upgrade on this feature - thank you!

**Comment by minhcasi** [comment]
Let us know if you have any further questions - thank you!
