### ISSUE TITLE
 Android build build issue on Pixel

### ISSUE THREAD

**Issue by saud-kh** [inspireui/support#4368]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: The app was working fine, and was even submitted to the play store, but something happened after updating to the new Android Studio version and I am unable to debug why its instantly crashing after building for Android. So i am positive its not the key or some other settings for the app as it worked fine up until the update. I am using flutter stable version on macos 10.15.6
+ Product & version: Fluxstore 1.7.6
+ Flutter (or React Native) version: Flutter
+ Testing Device/Simulator: Pixel 3a, Android Studio
+ Screenshot issues (drag the file to attach here): The app crashes instantly after installing the apk or bundle

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 

Thank you for your time!

**Comment by saud-kh** [comment]
Hello @ameenbadri7 I have already filled the verify link. and i cant provide screenshots because as i had mentioned the app crashes before it start. would you like to see specific screenshots of the code??

**Comment by minhcasi** [comment]
@saud-kh - could you help to share your source to inspireui.team@gmail.com - we will help to investigate the root cause - thank you!

**Comment by saud-kh** [comment]
@minhcasi done, i've just emailed it. thank you.

**Comment by minhcasi** [comment]
Thank you for quick response, we will investigate and let you know

**Comment by saud-kh** [comment]
any update on the above?

**Comment by minhcasi** [comment]
We wanted to thank you for your patience during this busy time. We currently have reduced staff and a significantly higher volume of inquiries. Although checking this Integration Issue is not included from our support scope - https://inspireui.com/support-policies/, but we’re working as hard as we can to reply to your request as soon as possible.

We sincerely apologize for the delay and hope you’re staying safe.

**Comment by minhcasi** [comment]
@saud-kh - thank you for your feedback with the document suggestions, our team is working hard to update it more detail and useful. 

Could you consider updating the rating as it will impact our business? The team is working hard to help to check your issue but really disappointed to get a bad rating. Thank you for your understanding. 

Btw, congratulation with your app on Google Play store!

**Comment by saud-kh** [comment]
@minhcasi the reason why I got the google app working is because i had to start from scratch several times to reconfigure the app the many files that you failed to document in any of the steps. (the problem was the package name in one of the many names that need to be modified btw) and because I was waiting 7 days for a proper response on this ticket.

I have modified the app so much at this stage I may have well just used one of the many free flutter woocommerce apps.

the fact that I had to purchase this and tell my client he cannot use login with apple or login with google or push notification because there is next to ZERO documentation aside from the basic setup is just not acceptable and I am at this point just looking into other solutions despite paying for this app which will waste even more time.

If you're at least willing to fix the issues in regard to push notification and login (firebased config) or at least publish a document explaining the full steps, I am not going to change my rating, its only fair to anyone before buying the app that they should know what they are buying.

**Comment by minhcasi** [comment]
@saud-kh - we will spend more time to upgrade the documents and keep the update on this ticket - thank you!

**Comment by saud-kh** [comment]
this issue was obviously not resolved, its been over a month and no response and the new version of the app is an even bigger nightmare to setup

**Comment by minhcasi** [comment]
@saud-kh - we have been working hard to update the app more detail https://docs.inspireui.com/fluxstore/install-checklist/ - please consider to update our rating

If you are not happy with our product, kindly process the refund to save time! Thank you!

**Comment by minhcasi** [comment]
@saud-kh - you guys also success release the app on Appstore - https://apps.apple.com/us/app/id1524383065 

and Google Play store  - https://play.google.com/store/apps/details?id=com.saudkh.yuehlia&hl=en

but does not happy with the product?
