### ISSUE TITLE
[MStore] Getting Error while loading project for the first time

### ISSUE THREAD

**Issue by davekedar** [inspireui/support#437]
Item Purchase Code:
f9eaf46b-d573-484d-945f-4236e184eeaf

![image](https://user-images.githubusercontent.com/11268363/54975657-cf7d0100-4fbd-11e9-97d9-b404280dbfc3.png)

Please help

**Comment by luyx2412** [comment]
Hi @davekedar Can you re-install again the library `yarn install`. The issue related to decorators-legacy style. Make sure your `.babelrc` file look like https://github.com/facebook/react-native/issues/21320#issuecomment-431884199

Thanks
