### ISSUE TITLE
Prepurchase Query on Prestashop app

### ISSUE THREAD

**Issue by nucl123** [inspireui/support#4370]
Hi,
We are currently having fluxstore pro app and is interested in another purchase of prestashop version, just 1 pre-purchase question:
1.How is the checkout processed? is it same like fluxstore pro, where all the available gateways as per the website will be listed and in the final step, it gets processed through a web view, is it the same flow in prestashop version also? any demo is available, I can see that the listed demo on codecanyon is for general fluxstore app, not for prestashop.
please let us know
Thanks

**Comment by minhcasi** [comment]
@nucl123 - thank you for the question, the current release of Prestashop is based on Fluxstore Pro core but it only support for COD on the first release - we will investigate and add more payments solution on next release - very best!
