### ISSUE TITLE
can't see shipping options

### ISSUE THREAD

**Issue by rabeehlive** [inspireui/support#4372]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

i have released a android app, but i can't see any shipping options which is available on the website in the at checkout section

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by rabeehlive** [comment]
flutter woocommerce app version 1.7.6

**Comment by rabeehlive** [comment]
please help me to solve

**Comment by ameenbadri7** [comment]
hello sir,
please provide a screenshot for your and details about your issue.

Thank you.

**Comment by rabeehlive** [comment]
i have 2 shipping options  which works very well on my website, but i can't see anything on app
https://ibb.co/SyyvCBz

**Comment by ameenbadri7** [comment]
do you use the default woocommerce shipping methods?

**Comment by rabeehlive** [comment]
yes,

**Comment by rabeehlive** [comment]
https://ibb.co/LrjvfLw

**Comment by rabeehlive** [comment]
https://ibb.co/rvtmbqY

**Comment by rabeehlive** [comment]
I found that the application is working good while running with other website credentials.
Steps i did:
1: installed wordpress and woocommerce on a another domain 
2: installed mstore api plugin but not activated 
3: checked with app
It's working good. 
But it's not working with my purchase code activated website. 

Please help me. No reply?

**Comment by rabeehlive** [comment]
Please reply

**Comment by rabeehlive** [comment]
@ameenbadri7 please reply

**Comment by rabeehlive** [comment]
then please reply, iam still watiting for your reply

**Comment by minhcasi** [comment]
@minhtruong315 - pls investigate this shipping issue

**Comment by rabeehlive** [comment]
2 daya no solution

**Comment by rabeehlive** [comment]
Still no response even after 3 days, please help. I have no other choice. I purchased this app from you. You guys are really bad

**Comment by minhcasi** [comment]
We wanted to thank you for your patience during this busy time. We currently have reduced staff and a significantly higher volume of inquiries. Although checking this Integration Issue is not included from our support scope - https://inspireui.com/support-policies/, but we’re working as hard as we can to reply to your request as soon as possible.

We sincerely apologize for the delay and hope you’re staying safe.

**Comment by minhtruong315** [comment]
Hi @rabeehlive can u send me common folder via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/4372

**Comment by rabeehlive** [comment]
solved,

**Comment by rabeehlive** [comment]
thank you for your response

**Comment by MorisTech** [comment]
@rabeehlive 
What was the solution?

**Comment by rabeehlive** [comment]
solution:
Change DefaultCountryISOCode in common/config/payments.dart like this
"DefaultCountryISOCode": "IN",
Change config/states/state_in.json like this
[
  {
    "code": "MP",
    "name": "Madhya Pradesh"
  }
]
it needs "code" in your website to checkout

**Comment by rabeehlive** [comment]
i need a help, iam selling products in a single state only. so i want to make my state as default one like country.
currently i used "DefaultCountryISOCode": "IN", so it auto loads INDIA as default. i want  to auto load state as well.
please help me to do this

**Comment by MorisTech** [comment]
@rabeehlive 
I don't quite understand
I'm in Nigeria, So how will the setup be.

**Comment by rabeehlive** [comment]
@minhtruong315 please help

**Comment by minhcasi** [comment]
I'm not sure if this solution work, but you could try to hard code this line from the `shipping_address.dart`

<img width="930" alt="Screen Shot 2020-07-30 at 16 33 38" src="https://user-images.githubusercontent.com/1459805/88907080-6dec3700-d282-11ea-9f9e-ce453dda5a19.png">

**Comment by minhtruong315** [comment]
@rabeehlive replace config/states/state_in.json like this
```
[
  {
    "code": "AC",
    "name": "Daerah Istimewa Aceh"
  },
  {
    "code": "SU",
    "name": "Sumatera Utara"
  },
  {
    "code": "SB",
    "name": "Sumatera Barat"
  },
  {
    "code": "RI",
    "name": "Riau"
  },
  {
    "code": "KR",
    "name": "Kepulauan Riau"
  },
  {
    "code": "JA",
    "name": "Jambi"
  },
  {
    "code": "SS",
    "name": "Sumatera Selatan"
  },
  {
    "code": "BB",
    "name": "Bangka Belitung"
  },
  {
    "code": "BE",
    "name": "Bengkulu"
  },
  {
    "code": "LA",
    "name": "Lampung"
  },
  {
    "code": "JK",
    "name": "DKI Jakarta"
  },
  {
    "code": "JB",
    "name": "Jawa Barat"
  },
  {
    "code": "BT",
    "name": "Banten"
  },
  {
    "code": "JT",
    "name": "Jawa Tengah"
  },
  {
    "code": "JI",
    "name": "Jawa Timur"
  },
  {
    "code": "YO",
    "name": "Daerah Istimewa Yogyakarta"
  },
  {
    "code": "BA",
    "name": "Bali"
  },
  {
    "code": "NB",
    "name": "Nusa Tenggara Barat"
  },
  {
    "code": "NT",
    "name": "Nusa Tenggara Timur"
  },
  {
    "code": "KB",
    "name": "Kalimantan Barat"
  },
  {
    "code": "KT",
    "name": "Kalimantan Tengah"
  },
  {
    "code": "KI",
    "name": "Kalimantan Timur"
  },
  {
    "code": "KS",
    "name": "Kalimantan Selatan"
  },
  {
    "code": "KU",
    "name": "Kalimantan Utara"
  },
  {
    "code": "SA",
    "name": "Sulawesi Utara"
  },
  {
    "code": "ST",
    "name": "Sulawesi Tengah"
  },
  {
    "code": "SG",
    "name": "Sulawesi Tenggara"
  },
  {
    "code": "SR",
    "name": "Sulawesi Barat"
  },
  {
    "code": "SN",
    "name": "Sulawesi Selatan"
  },
  {
    "code": "GO",
    "name": "Gorontalo"
  },
  {
    "code": "MA",
    "name": "Maluku"
  },
  {
    "code": "MU",
    "name": "Maluku Utara"
  },
  {
    "code": "PA",
    "name": "Papua"
  },
  {
    "code": "PB",
    "name": "Papua Barat"
  }
]
```

**Comment by rabeehlive** [comment]
@minhtruong315  already done

**Comment by rabeehlive** [comment]
@minhcasi I tried that hard method but its not working, please help

**Comment by minhtruong315** [comment]
@rabeehlive replace these files and try again
[lib.zip](https://github.com/inspireui/support/files/5007219/lib.zip)

**Comment by rabeehlive** [comment]
@minhtruong315 thank you for your efforts. Let me check

**Comment by rabeehlive** [comment]
@minhtruong315 no working bro, i tried. what to do

**Comment by minhcasi** [comment]
@rabeehlive - could you resend the screenshot issue? Did you try to clean up the flutter cache when applying new patch - pls give a try with this guide as well - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

**Comment by minhtruong315** [comment]
Hi @rabeehlive send me full your  source code via email: minhtruong315@gmail.com
ping me when you sent.
Thanks

**Comment by rabeehlive** [comment]
iam trying to upload the file, when its reday, i will inform you

**Comment by minhtruong315** [comment]
ok. thanks

**Comment by rabeehlive** [comment]
@minhtruong315 please check your mail

**Comment by minhtruong315** [comment]
please check your email. I sent fixed files
