### ISSUE TITLE
Exposure of secure keys in the flutter application + network traffic.

### ISSUE THREAD

**Issue by httpsOmkar** [inspireui/support#4373]
** Exposure of secure keys in the flutter application + network traffic.**
+ Detail Issues: As per the documentation. There is a step to create the key which has admin write access to the store.
+ Product & version: Flex store version 1.7.5+3001
+ Flutter version: 1.20.0-7.2.pre
+ Testing Device/Simulator: OnePlus 7
+ Screenshot issues (drag the file to attach here): 

![DeepinScreenshot_select-area_20200726150243](https://user-images.githubusercontent.com/29942725/88477439-1af84400-cf51-11ea-9da8-e6d7d89efae1.png)

If you use these keys to query to your demo server. [Example](https://mstore.io/wp-json/wc/v2/orders?exclude=311&per_page=100&page=1&lang=en&consumer_key=ck_c16d601d14a44c8080418c1ab9336b72ae8faff2&consumer_secret=cs_1c11c4d0ee3bef861421bf3622f20f6b49c8497a)
We are able to retrieve all customer order details from the endpoint without any authentication. Also this endpoint is using *GET* method which makes it more insecure.

If some attacker intercept the network traffic he will able to access all the sites including settings. Which is not good for any business.

**Comment by minhcasi** [comment]
@httpsOmkar - thank you for your sharing, do you have any recommendations to enhance the security for Rest API - very best!

**Comment by httpsOmkar** [comment]
@minhcasi Actually I am doing research on this. But with current approach anybody can access anything. It doesn't feel good.
Is there any channel where I can report the security vulnerabilities. I don't want post it publicly.

**Comment by httpsOmkar** [comment]
This kind of plugin can solve your issue for the secret key.

https://wordpress.org/plugins/wp-rest-api-authentication/

**Comment by minhcasi** [comment]
@httpsOmkar - thank you for sharing, I will assign to the team for investigating deeply to enhance the API 

would you mind to verify to submit this form http://verify.inspireui.com/ so that we could add your git usename to our purchase customer - thank you for your time!

**Comment by httpsOmkar** [comment]
Is this really closed?
