### ISSUE TITLE
Issue after changing package name

### ISSUE THREAD

**Issue by GNAG1993** [inspireui/support#4374]
**This is the error i'm facing after changing package names**

Launching lib\main.dart on Infinix X626B in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
> No matching client found for package name 'com.vioeltkart.market.kool'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 53s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by ameenbadri7** [comment]
Hi @GNAG1993 

could try by replacing your `gogle-services.json` based on this [tutorial](https://docs.inspireui.com/fluxstore/sign-in/).
make sure that the name of your app inside the firebase is the same as your app bundle name.
hope that's help.

**Comment by GNAG1993** [comment]
I sorted out that, the issue now i'm getting is i'm using the code provided by you guys with app name com.inspireui.fluxstore.vendor
I'm trying to connect it with firebase with own google-services.json with appname com.xxx.vendors.mk

but firebase not verifying the app

**Comment by minhcasi** [comment]
@GNAG1993 - pls double-check this guide to make sure you have changed all the bundle id - https://docs.inspireui.com/fluxstore/delivery-android/#11-change-the-app-name

Try to search the android folder with keyword `com.inspireui.fluxstore.vendor` to see if you have missed any config?

**Comment by GNAG1993** [comment]
oky, I.m done with that too

**Comment by minhcasi** [comment]
@GNAG1993 - could you share the screenshot of your current issue? Thank you!

**Comment by GNAG1993** [comment]
I mean I resolved the issue.
Now I'm getting another issue, I registered on firebase and everything went fine. after configuring google-services.json,
Login works but as I login it keeps logging in on the login screen, and then I have to press back key and when I check after that in Setting option, It shows logged in.

**Comment by GNAG1993** [comment]
anyone there?

**Comment by minhcasi** [comment]
@GNAG1993 - could you have the video screenshot of this isssues "Login works but as I login it keeps logging in on the login screen, and then I have to press back key and when I check after that in Setting option, It shows logged in." ?

Also, share your source file to inspireui.team@gmail.com - thanks

**Comment by GNAG1993** [comment]
Sure, I'll share within 15 minutes

**Comment by GNAG1993** [comment]
Please Check, i have mailed

**Comment by GNAG1993** [comment]
I have mailed you the details, also I'm unable to see any other option like my orders and add product anything.

**Comment by GNAG1993** [comment]
I'm still waiting for response, unable to move forward in development.

**Comment by minhcasi** [comment]
Thanks, we will help to check

**Comment by GNAG1993** [comment]
Okay, please asap as I'm stuck due to this. Nothing is shown like if it login as You can see in video, it doesn't show vendor options, profile, my orders anything.

**Comment by minhcasi** [comment]
@GNAG1993 - note with investigating

@tgloc96 - pls help to investigate this issue (also check the video from the email https://tppr.me/gVeJQ)

**Comment by GNAG1993** [comment]
any update?

**Comment by minhcasi** [comment]
@GNAG1993 - We’re working as hard as we can to get to your request as soon as possible.

**Comment by GNAG1993** [comment]
Okay, actually I'm stuck on this unable to proceed in anyway

**Comment by tgloc96** [comment]
Hi @GNAG1993,
I replied to your email, please check your email.
Thank you for your time.

**Comment by minhcasi** [comment]
Let us know if you have any feedback - thank you!
