### ISSUE TITLE
FluxStore Multivendor - Gmail authentication error

### ISSUE THREAD

**Issue by juanmanuel0963** [inspireui/support#4375]
Hi,
I bought FluxStore Multivendor yesterday, and today I did all the steps describe in this video to setup Google Login,
https://docs.inspireui.com/fluxstore/sign-in/

but when running the app on Flutter Emulator or my Android device,
throws the error of the image

![IMG_20200726_194404](https://user-images.githubusercontent.com/44442325/88493916-3f681680-cf79-11ea-8ed0-051130bd77d9.jpg)

**Comment by minhcasi** [comment]
@juanmanuel0963 - pls help us to raise your all comment into one open ticket - #4369

Please share your proof or purchase asap by submitting this form http://verify.inspireui.com/ 

Thank you for your time
