### ISSUE TITLE
Cache Issue : Woocommerce Fluxstore

### ISSUE THREAD

**Issue by amitiitd999** [inspireui/support#4376]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: Changes done in config.json file are not reflecting. I have changed the home page banner in config.json file and uploaded the latest config.json file in mstore API plugin and regenerated the thumbnails. But the changes are not reflecting.
Note: Ischacing is enabled in general.dart file
+ Product & version: 1.6.6b
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@amitiitd999 - could you try to use latest release `1.7.6` as the old 1.6.6 could be much difference with the latest release - thank you!

**Comment by amitiitd999** [comment]
can u please tell me the path in which config.json file get uploaded on the server?

**Comment by ssathamenterprises** [comment]
@amitiitd999   hi  last time i have same issue, i have done following
1. your design .json file with (config_en.json) this name 
2. rest  cache in your wordpress
3. upload your (config_en.json) file in wordpress mstore api
4. after check it will reflect

**Comment by minhcasi** [comment]
@amitiitd999 the file is located from `lib/config/config_en.json`

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
