### ISSUE TITLE
Margin between products

### ISSUE THREAD

**Issue by jvsamoa** [inspireui/support#4377]
Hi,
Thank you for your support.

I can't found the specific line of code for delete or reduce the space between two rows of product. I tried using the Inspector Tools from Android Studio but I am using my real device directly.

Can you help me, please?
![image](https://user-images.githubusercontent.com/25646978/88503222-4e7ab300-cfd1-11ea-9427-7d73c6370a21.png)

**Comment by minhcasi** [comment]
@jvsamoa - could I know if you are using the latest release `1.7.6`? Thank you!

**Comment by jvsamoa** [comment]
No dude... when i tried to upgrade i had some errors. I don't have time to solve issues again, again and again. -.-

I need to delete this margin, only that. I wrote in 4 opportunities for this reason. Help me pls

**Comment by simonpham** [comment]
@jvsamoa could you tell me **which version** are you using?

**Comment by jvsamoa** [comment]
Hi, 
1.7.5 is my version.

**Comment by minhcasi** [comment]
@jvsamoa - pls give a try with latest Fluxstore `1.7.6` - the team have confirmed to fix it on this release - thanks

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
