### ISSUE TITLE
Youtube Embeds

### ISSUE THREAD

**Issue by rmonst3r** [inspireui/support#4378]
Hello,

We're having an issue with YouTube embeds now showing up in our Fluxnews app.

Here's the code for the embed:

`<div class="td-post-content">
<div class="wpb_video_wrapper">
<iframe id="td_youtube_player" width="100%" height="560" src="https://www.youtube.com/embed/24Kk3TrdyNE?enablejsapi=1&amp;feature=oembed&amp;wmode=opaque&amp;vq=hd720" frameborder="0" allowfullscreen="" style="height: 391.5px;"></iframe>
</div>`

Do we have to adjust anything within in the app for this to work? It's the Newspaper Wordpress theme.

Here's an example of a video page that not's showing the Youtube  player in the app:
shorturl.at/puMQX

Thanks.

**Comment by minhcasi** [comment]
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by rmonst3r** [comment]
Sent

**Comment by minhcasi** [comment]
we got it, could you share your website URL of the content that you have embedded the iframe? We will help to investigate and let you know

**Comment by rmonst3r** [comment]
Yep, here to go https://www.cnc3.co.tt/weather-update-tropical-storm-gonzalo/

**Comment by rmonst3r** [comment]
Hi, any updates here?

**Comment by dttrung26** [comment]
Hi @rmonst3r ,
as I checked your embedded video is still displayed fine. Please keep in mind that video display just only supported in oneQuarterImageType detail blog layout. Please change to this detailed layout to see if it works.
Let me know if it helps. 
Happy coding!

**Comment by rmonst3r** [comment]
Thanks I changed that but the Hero image is still showing only.

No video player.

const kAdvanceConfig = {
  "DefaultLanguage": "en",
  "IsRequiredLogin": false,
  "GuestCheckout": true,
  "EnableShipping": false,
  "GridCount": 3,
  "DetailedBlogLayout": "oneQuarterSizeImageType",
  "EnablePointReward": false,
  "HeartButtonType": kHeartButtonType.cornerType,
  "isCaching": false,
  "OnBoardOnlyShowFirstTime": true,
};

**Comment by dttrung26** [comment]
Hi @rmonst3r , 
please try to add video url text into your post content to see if it works. It seems like the video iframe does not work in FluxNews at the moment. 
Let me know your checking, 
Best!

**Comment by rmonst3r** [comment]
@dttrung26 yes this works but it shows up twice on our website.

Is there a way to get Flux news to show the video through a patch or another method?

**Comment by rmonst3r** [comment]
Also after adding the link, there's extra code shown on the app:

https://ibb.co/Xt56smH

**Comment by dttrung26** [comment]
Hi @rmonst3r ,
The video display works by taking any first acceptable video URL and then display it in the top image, and sadly this is the only way. We'll consider support video display from iframe soon. 
Let me know if you have any questions.

**Comment by minhcasi** [comment]
#4427
