### ISSUE TITLE
No Shipping Method error for Opencart

### ISSUE THREAD

**Issue by atamilvannan** [inspireui/support#4379]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: No Shipping Method error for Opencart. i have shipping method as weight based shipping based on geo zones. if i select free shipping or flat shipping using all zones it shows but not for weight based shipping on custom zones
+ Product & version: Opencart 3.0. I Have Purchased from Codecanyon
+ Flutter (or React Native) version: Fluxstore Pro
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 
Also, provide a screenshot of your issue.

Thank you for your time!

**Comment by atamilvannan** [comment]
Submitted already

**Comment by minhtruong315** [comment]
@atamilvannan can u  record screen? and give me your website.
Thanks

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
