### ISSUE TITLE
[MStore] I have a problem I can not run an application

### ISSUE THREAD

**Issue by 3LaHoonK** [inspireui/support#438]
I have a problem I can not run an application

I have a problem

![Untitl3332ed](https://user-images.githubusercontent.com/30515994/54986343-8334bf80-4fc3-11e9-851d-6f259d685169.png)
![Untitle33422d](https://user-images.githubusercontent.com/30515994/54986345-8334bf80-4fc3-11e9-8697-ea3e46902ddb.png)

**Comment by luyx2412** [comment]
Hi @3LaHoonK Please provide your purchase code.

Thanks

**Comment by 3LaHoonK** [comment]
Hi .. @luyx2412 
Purchase Code: f668f72b-a814-4146-9886-515fe18034c1
