### ISSUE TITLE
Shipping Options

### ISSUE THREAD

**Issue by topmosth** [inspireui/support#4380]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
Shipping option does reflect on the app but not accurate. We are currently using a volume based shipping plugin (Fish and Ships). In our shipment setting, are only applicable for all orders above 20,000. Free shipping can still be selected even the total cart amount is below 20,000. Shipping class is also not detected by the app. Shipping class cost are currently activated in Dokan. Do you have any supported plugin Shipping Plugin for this kind of setup? 
+ Product & version: Fluxstore Multi Vendor - Flutter E-commerce Full App 1.75
+ Flutter (or React Native) version: Flutter
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

![image](https://user-images.githubusercontent.com/57655242/88523199-210e2380-d02a-11ea-93ff-442c0821377c.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhtruong315** [comment]
Hi @topmosth for shipping option, you can use OnePageCheckout. for native checkout doesn't support shipping option now.
Please change EnableOnePageCheckout and CheckoutPageSlug in common/config/payments.dart
```
/// Enable Payment option
  "EnableOnePageCheckout": true,

  //This config is same with checkout page slug in the website
  "CheckoutPageSlug": "checkout",
```
CheckoutPageSlug must be same in your website

**Comment by minhcasi** [comment]
'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
