### ISSUE TITLE
delivery choice problems do not arise fluxstore 1.7.6 

### ISSUE THREAD

**Issue by samz29** [inspireui/support#4382]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by samz29** [comment]
please help in version 1.7.6 this delivery option does not appear but version before it appears
![photo_2020-07-27 16 54 19](https://user-images.githubusercontent.com/60650955/88529279-f91ec000-d029-11ea-8bd1-c5a6c374dfae.jpeg)

**Comment by rabeehlive** [comment]
me2 have same issue

**Comment by minhtruong315** [comment]
@samz29 can u send me common folder via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/4382

**Comment by samz29** [comment]
@minhtruong315 which folder do I want to send

**Comment by samz29** [comment]
@minhtruong315 i send email to you

**Comment by minhtruong315** [comment]
@samz29 Add state_id.json on config/states folder and try again
[state_id.json.zip](https://github.com/inspireui/support/files/4998726/state_id.json.zip)
<img width="489" alt="Screen Shot 2020-07-30 at 11 06 51 AM" src="https://user-images.githubusercontent.com/10402500/88879614-eb994e00-d254-11ea-956f-13061745d629.png">
