### ISSUE TITLE
on boarding not works after update

### ISSUE THREAD

**Issue by ssathamenterprises** [inspireui/support#4384]
please help me i updated my app to latest version now my app on boarding not works

**Comment by minhcasi** [comment]
@ssathamenterprises - try to remove this option if you would like to show the onboard always, by default it is only supported to show at the first time loading from the app (you could try to remove the app on the simulator to check this feature)

<img width="1054" alt="Screen Shot 2020-07-28 at 10 23 26" src="https://user-images.githubusercontent.com/1459805/88615549-61b67d00-d0bc-11ea-995c-ddb1cfa966f1.png">

**Comment by ssathamenterprises** [comment]
The new release first on board not shows , ( I no need on board screen for always) only need on board on first time

**Comment by minhcasi** [comment]
@ssathamenterprises - could you confirm it happens on the latest version `1.7.6`?

**Comment by ssathamenterprises** [comment]
its works in your release have issue in my edit
