### ISSUE TITLE
Checkout redirect to website

### ISSUE THREAD

**Issue by nomicool** [inspireui/support#4387]
When to add products cart and buy them it loads and moves to website how to fix it to remain in the app to perform order

**Comment by ameenbadri7** [comment]
hi @nomicool 
Please provide us more details perhaps screenshots of video to describe your problem.
Thank you.

**Comment by nomicool** [comment]
[video shot.zip](https://github.com/inspireui/support/files/4987084/video.shot.zip)
have a look after checkout loads its moves to the website itself

**Comment by minhcasi** [comment]
<img width="789" alt="Screen Shot 2020-07-29 at 10 24 19" src="https://user-images.githubusercontent.com/1459805/88753126-ab1ecf00-d185-11ea-9025-d651c9c7fa6f.png">

**Comment by minhcasi** [comment]
@nomicool - please try to update the NativeOnePageCheckout to true/false to see if there is any difference? Thanks

**Comment by minhcasi** [comment]
#4426
