### ISSUE TITLE
Cache Problem: Woocommerce Fluxstore

### ISSUE THREAD

**Issue by akashsharnarthi** [inspireui/support#4388]
Varified purchased code, Ticket ID: #4285

It was working fine, but I just opened the app and tried to track a random order (with test order).
it was loading too much so when I checked the Home page all the banners are working fine but the Category section, Product section I used while building the app UI using flex builder are showing "No products found", I even checked the Categories. Its also showing the same issue.

NOte: in code isCahching: "true". i have set this.
Screenshot: https://prnt.sc/tpgy3g
Screenshot of Endpoint API caches: https://prnt.sc/tph5qd

The app is already published on Playstore: https://play.google.com/store/apps/details?id=com.theviriaks.thefreakykart

What I did: I cleared the cache, Again uploaded the config_en.json file, I am using the latest version code, Updated the Store API, and still facing the same. please resolve asap as the app is already published and using by1000s of users.

**Comment by ameenbadri7** [comment]
Hi, @akashsharnarthi  welcome back.

The purpose of `isCaching `is to optimize the user's performance by not reloading config again when experiencing the app. 
That's why when you enable `isCaching`, the product layout will not be loaded again. 
However, the `product detail screen` always needs to be `reloaded `due to special `data events`. 
Therefore, please consider using this feature if your site is mostly `"static"`. 
Otherwise, turn this one off if you need your data is always up-to-date.
Let me know if you still have any questions.
Best!

**Comment by akashsharnarthi** [comment]
Dear sir, Thanks for your explanation.

I asked you to let me know what solution fits the best, So check and let me know what can I do to get the black screen mentioned in the screenshot to be resolved.
Note: My website is static itself. therefore I am using this feature.

**Comment by akashsharnarthi** [comment]
I am very tempered with your code now, it worked well while testing and after few hours of release in play store but thereafter it's not working well. 
I need a immediate solution for this as plenty of my customers are already installed it

**Comment by akashsharnarthi** [comment]
And please dont explain the things now, just let me know a better step to get it resolved.

**Comment by akashsharnarthi** [comment]
Even order history is not working, all pages are black expect the BLOG page

**Comment by minhcasi** [comment]
@akashsharnarthi - could you share the source and website admin login to inspireui.team@gmail.com - we will help to check the root cause of this issue - thank you!

**Comment by akashsharnarthi** [comment]
I have mailed the admin details from 0123psp@gmail.com
Check.

And I have already told you what I have done with the code so currently, i can't share the code as it holds 300-500MB with me. :/

**Comment by akashsharnarthi** [comment]
and hope you red that the app is already published so quick resolve will be appreciated, moreover i have shared config.en.json file too on email

**Comment by akashsharnarthi** [comment]
Anyone up?

**Comment by akashsharnarthi** [comment]
I will be waiting for your response for the next 4 hours. I can't tolerate the negative reviews on play store for my app

**Comment by minhcasi** [comment]
Hi, pls try to check the App API from your server side as the root cause is not from the app, is there any website plugin that blocked the API?

We are willing to help you with the checking but it is not worth a bad rating

**Comment by akashsharnarthi** [comment]
Not a problem, I had purchased Fluxstore two times taking into consideration that i could get better support here. 
No issues at all. i know what i can do the next till you resolved the problem. 

Thank you :D

**Comment by akashsharnarthi** [comment]
And dont worry that I will spam your comment sections on Codecanyon hahaha!

**Comment by akashsharnarthi** [comment]
I am continuously getting messages from our clients, moreover, I am not going to remove the rating till the issues get resolved.

**Comment by akashsharnarthi** [comment]
Dear, I have purchased your code two times and mentioning "Priority Ticket" and letting the client awaited does not make sense, I will delete the rating right now. make sure to resolve the problem

**Comment by akashsharnarthi** [comment]
I have invested 100+$ with you, if I had known your behavior like this, I dont even have purchased it :')
PS: deleted the rating
