### ISSUE TITLE
Language error and ios builder

### ISSUE THREAD

**Issue by Marcleiton** [inspireui/support#4389]
Hello, I'm 3 months full of errors and always coming here, I couldn't finish the app due to the bugs I find, most bugs are simple bugs but you give several solutions that don't work at all.

The application only uses the native language in English, I changed it to Portuguese and nothing.

on iOS https://imgur.com/a/UPR6Fhx

**Comment by minhcasi** [comment]
@Marcleiton - try to clean up the cache to fix the issue - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

Did you could able to run the Test Drive on your ios device as well - https://flutter.dev/docs/get-started/test-drive?tab=vscode

We could process the refund if you are not satisfied with the product, thank you for your time here

**Comment by Marcleiton** [comment]
Hello, in fact I would really like to be able to generate the app, as it is a very good system that you created, but the errors I have are complicated and that have no resolution.

The language, for example, cannot be changed, it is always in English, and I would like to leave it in another language natively when the user opens the app, but I can't get it in any way.

**Comment by minhcasi** [comment]
@Marcleiton - could you share the detailed screenshot and send your project to inspireui.team@gmail.com? We will have a look to see if we could help.

Please make sure you have noted updated and added heavy customization that breaks the core features

**Comment by Marcleiton** [comment]
Sent

**Comment by minhcasi** [comment]
our team will have a check and let you know - thanks

**Comment by simonpham** [comment]
Hi @Marcleiton

For the error while generating the app, please make sure you select `Generic iOS Devices` before click Archive. (see below)
![image](https://user-images.githubusercontent.com/8846657/88896220-bea86380-d273-11ea-9a24-a8c038c0285c.png)

Hope this will solve your issue.

Thank you for using our product.

**Comment by minhcasi** [comment]
@Marcleiton - Portuguese is working fine with our testing on the demo app, could you try to check the download package and compare it with your customize project? Are you using the country code `pt`? Thank you!

**Comment by Marcleiton** [comment]
hello I used br as it appears in the documentation

**Comment by minhcasi** [comment]
@Marcleiton - try to use `pt` as from the demo, `br` is not correct country code from the current language app

**Comment by minhcasi** [comment]
Could you resolve the issue so far?

**Comment by Marcleiton** [comment]
Hello, sorry for the delay I can't test I had problems, I'll be testing tomorrow
