### ISSUE TITLE
[ListApp] App kees crushing on the launch

### ISSUE THREAD

**Issue by urasuji** [inspireui/support#439]
**Required Info (please complete the following information):**
 - Product: ListApp
 - Your Purchased Code: 356e79dc-c9af-45f2-9b27-ef1b52ca6088
(we may not reply if you are not our customer)

**Describe the bug**
App keeps crushing after the launch

**Screenshots**
https://photos.app.goo.gl/ezDg7e7HttSHJr2Q9
https://photos.app.goo.gl/DS2KtnapDzmbh2ti6

**Additional context**
I think I followed your manual step by step but both expo apps are still not working properly...

**Comment by thangvo9x** [comment]
Please give me your AppConfig.json for checking. Thanks

**Comment by urasuji** [comment]
[AppConfig.json.zip](https://github.com/inspireui/support/files/3012359/AppConfig.json.zip)

**Comment by urasuji** [comment]
I think you need to make this thread as private

**Comment by thangvo9x** [comment]
or send thang@inspireui.com with subject id is 439.

**Comment by urasuji** [comment]
I sent. Thank you,

**Comment by thangvo9x** [comment]
Hi. Please check the url your-domain/wp-json/2p/v2/job_listing is not working.

**Comment by urasuji** [comment]
What should I do to make it work properly?

Do I have to Specify a base URL for JSON API?

**Comment by thangvo9x** [comment]
We saw your URL is working then we'll close it.

**Comment by urasuji** [comment]
But it still keeps crushing

2019年4月1日(月) 10:21 Tony Vo <notifications@github.com>:
