### ISSUE TITLE
Two problems in FluxStore Pro v1.7.6 Please solve them

### ISSUE THREAD

**Issue by MostafaSheriif** [inspireui/support#4390]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: I have two problems with FluxStore Pro v1.7.6 with woocommerce website:

**1- The first one is when i have a product with title name in arabic it appears in the app like boxes not appears by the arabic letters (see the attached screenshots).**

**2- Second problem when i have a (variable product) in woocommerce with special price it appears like zero discount in the category page of the product and this problem started from v1.6.5 and never solved until now (see the attached screenshots to understand me more).**

+ Product & version: v1.7.6
+ Flutter (or React Native) version: Flutter
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

![1](https://user-images.githubusercontent.com/62574842/88588925-9ee92380-d058-11ea-8217-02965ea00a9f.PNG)

![2](https://user-images.githubusercontent.com/62574842/88588940-a7415e80-d058-11ea-9829-16a6499b7872.PNG)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**
**Done**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 

Thank you for your time!

**Comment by MostafaSheriif** [comment]
> Thank you for the feedback.
> 
> Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.
> 
> We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission.
> 
> Thank you for your time!
> 
> > **[Google Forms - create and analyze surveys, for free.](http://verify.inspireui.com/)**Create a new survey on your own or with others at the same time. Choose from a variety of survey types and analyze results in Google Forms. Free from Google.

Already submitted the verification files when i started the thread!!

**Comment by minhcasi** [comment]
@MostafaSheriif - thank you for quick response, we got the verify

@ameenbadri7 - pls suggest for the Arabic font issue - thanks

**Comment by MostafaSheriif** [comment]
> @MostafaSheriif - thank you for quick response, we got the verify
> 
> @ameenbadri7 - pls suggest for the Arabic font issue - thanks

Thank you for your response, **and what about the second problem?** the variable product special price in the category page is the equal to the real price!!

**Comment by ameenbadri7** [comment]
@MostafaSheriif 
Are you using a custom font on your WordPress or your fluxstore project, our did you try to edit something inside the code that Is related to the fonts?
Because it's working with my Arabic site and my clients also without any problem.
Please help us by sending a zip copy of your common and config folder 
to my email ameenbadri7@gmail.com, I will look for a fix your issue.
Thank you.

**Comment by MostafaSheriif** [comment]
@ameenbadri7 
No i'm not using any custom font on both wordpress and fluxstore, I also sent the common and config folder to your email

**### _The second problem:  my second problem which is: In the category page, any variable product with special price appears like the discount is the same (as an example the banana in category page before the sale is for 49$ and after the sale is also 49$) but it appears correctly in the product details only(Look for the attached screenshot to understand what i mean please)_**

![aa](https://user-images.githubusercontent.com/62574842/88680781-297d6180-d0f1-11ea-898d-2c5313d19ff8.PNG)

**Comment by ameenbadri7** [comment]
Thank you, sir, I have received it I will be working on it ASAP!

**Comment by MostafaSheriif** [comment]
Thank you @ameenbadri7 , i really appreciate your hard work, really thank you.

**Comment by ameenbadri7** [comment]
Thank you, sir, I have received it I will be working on it ASAP!

**Comment by ameenbadri7** [comment]
I put your config files inside a fresh fluxstore 1.7.6 and no problem happens.
change your emulator to be your real device.
I suggest you should use our [pre-configed ](https://docs.inspireui.com/fluxstore) website with the config files that show you all products with banners to learn more about the app before you go to the testing. 
fluxstore supports fully Arabic apps and other languages just build your config file right with the [fluxbuilder](https://fluxbuilder.com/#download_section) or [manually ](https://docs.inspireui.com/fluxstore/woocommerce-setup/#2-app-integration) and then use the wpml to change the language.
it's working!
I will put here screenshots for both the Arabic and English language pages and how the product is reflecting your real products without any errors.
![Screenshot_20200729-034454](https://user-images.githubusercontent.com/37524186/88744908-582b2480-d151-11ea-865e-620425796a5f.jpg)
![Screenshot_20200729-034602](https://user-images.githubusercontent.com/37524186/88744917-5f523280-d151-11ea-996b-f535d50e4087.jpg)
![Screenshot_20200729-034926](https://user-images.githubusercontent.com/37524186/88744925-637e5000-d151-11ea-9061-75da050ebe39.jpg)
![Screenshot_20200729-035140](https://user-images.githubusercontent.com/37524186/88744936-6a0cc780-d151-11ea-965b-5ef4f7582bd6.jpg)
![Screenshot_20200729-040421](https://user-images.githubusercontent.com/37524186/88744943-6ed17b80-d151-11ea-9333-8c901d22fe14.jpg)

variable product issue it's like the price reflects on some languages like Arabic. In the product filter page, our team will look at this problem.


كل عام وانت بخير ...

**Comment by ameenbadri7** [comment]
Hi ,

I'm sorry to close this ticket as there is no response or active conversation.
