### ISSUE TITLE
Failed to find Platform SDK with path: platforms;android-R

### ISSUE THREAD

**Issue by meeraforefront** [inspireui/support#4393]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 
I purchased Fluxstore Multi vendor WooCommerce and Docken   supported Flutter App. Using version: 1.7.4.
![Flutter issue](https://user-images.githubusercontent.com/52703310/88617669-d7b6e600-d0b4-11ea-8d80-f1d89f56052e.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**
already submited

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@meeraforefront - please update the latest `1.7.6` has fixed this issue

You could also try this solution https://github.com/inspireui/support/issues/3708

**Comment by meeraforefront** [comment]
ok lets try

**Comment by minhcasi** [comment]
Let us know your checking - thank you!
