### ISSUE TITLE
Cannot view bank transfer screen

### ISSUE THREAD

**Issue by thimiradulakshitha** [inspireui/support#4394]
we added 2 options for the app, bank transfer and cash on delivery. COD works fine. but if I select bank transfer it redirects to the web view and shows the webview place order screen.
+ Issues
    **step 1** :  Login to the system and add some products to the cart.
    **step 2** :  go to the cart and check the products and tap checkout.
    **step 3** :  fill the name, and deliver address tap on 'continue to shipping'
    **step 4** : select flat rate on shipping method and preview.
    **step 5** : select bank transfer in payment view. it redirects to the webview.

+ Flutter version 1.7.5 - **Fluxstore woocommerce**
+ Samsung Galaxy S9

![Untitled-4](https://user-images.githubusercontent.com/44156968/88625178-e22dab80-d0c5-11ea-8db4-fa91ba75d7f1.jpg)

**Comment by minhcasi** [comment]
@thimiradulakshitha - this payment option is only supported to process via Webview payment

**Comment by minhcasi** [comment]
Let us know if you have any extra question - thank you!

**Comment by thimiradulakshitha** [comment]
yeah. but the problem is, when we select the **bank transfer**, it goes to the default checkout webview screen instead of the bank transfer screen. cash on delivery is already working. but I want to fix the bank transfer option.  

the thing I want, when I select bank transfer it should open the bank transfer view. not the default checkout view.
