### ISSUE TITLE
charles 

### ISSUE THREAD

**Issue by chalonalendra** [inspireui/support#4395]
hello , first i wanna say congrats for a job well done . i just purchased my.   Fluxstore Pro - Flutter E-commerce Full App for Magento, Opencart, and Woocommerce. however my issue is i wanna use the pre configured web ,could you be kind enough to upload it in my hosting ?  thanks in advance

**Comment by minhcasi** [comment]
Thank you for the feedback. Yes, the pre-config site is ready for upload to your hosting, please follow this guide https://docs.inspireui.com/fluxstore/woocommerce-setup/#1-website-integration

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by chalonalendra** [comment]
thanks iv seen the form but cant submit since my website is not live and its reading cant cant connect , 

https://prnt.sc/tptx24

**Comment by chalonalendra** [comment]
did it ! just managed to submit the form

**Comment by minhcasi** [comment]
@chalonalendra - pls try to include http from the URL to see if it works? example `https://www.kauflich.ch`

**Comment by chalonalendra** [comment]
i managed and submitted the form already

**Comment by chalonalendra** [comment]
my question is at what point exactly do i import the website in my wordpress ? where exactly do i do that ?

**Comment by chalonalendra** [comment]
hello there again . kindly show me where and how to activate the website in my wordpress dashboard 
after i downloaded it ?   

https://prnt.sc/tqnslm 


i did download the website from the repo and uploaded it in my hosting but how to connect the two is my dilema 

https://prnt.sc/tqnuz8
 kind regards

**Comment by minhcasi** [comment]
@chalonalendra - after download pre config site, and install this plugin to the latest version - https://wordpress.org/plugins/mstore-api

You could also try to connect with your site via fluxbuilder to check the connection - http://fluxbuilder.com/

**Comment by chalonalendra** [comment]
hello sir , my issue is not how to connect the web to the app like your answers suggest. i am having issues with building and uploading the website to my server . i have placed the files in my cpanel    https://prnt.sc/tqnuz8 but still don't know how to make that web display in my website ..    https://prnt.sc/tqzsdp

**Comment by minhcasi** [comment]
@Carlosdmendoza - could you help to check these simple steps on this link https://docs.inspireui.com/fluxstore/woocommerce-setup/#1-website-integration - thank you!

**Comment by chalonalendra** [comment]
sir i have followed all the ten steps on website integration but still cant have the website showing in my url , is there a way out ?

**Comment by minhcasi** [comment]
@chalonalendra - you give a try to test if your WooCommerce REST API is working? you could check it from the PostMan - https://github.com/woocommerce/woocommerce/wiki/Getting-started-with-the-REST-API

**Comment by minhcasi** [comment]
Let us know your checking - thank you 😊
