### ISSUE TITLE
how to change app loading icon 

### ISSUE THREAD

**Issue by nomicool** [inspireui/support#4396]
When i click checkout ap loads fluxstore icon how to change it

**Comment by ameenbadri7** [comment]
Kindly, please provide screenshots about your problem.
Thank you

**Comment by nomicool** [comment]
here is highlighted logo loading logo I asked for 
![Screenshot_1595949017](https://user-images.githubusercontent.com/25566185/88684530-6c016700-d10e-11ea-9c6e-3203e876bf0e.png)

**Comment by minhcasi** [comment]
You could change this file - thank you!

<img width="1043" alt="Screen Shot 2020-07-29 at 09 24 38" src="https://user-images.githubusercontent.com/1459805/88749392-61ca8180-d17d-11ea-9fa1-848283b935be.png">

**Comment by nomicool** [comment]
How do I change the icon with this file because I di not find the way to link another logo

**Comment by nomicool** [comment]
please let me know?
