### ISSUE TITLE
Parameters format not correct in running on Andoid Studio

### ISSUE THREAD

**Issue by EISAGHANI** [inspireui/support#4398]
I am facing this problem every time i run my code...
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
Parameter format not correct -
Exception: Gradle build failed to produce an .apk file. It's likely that this file was generated under C:\Users\Eisa Ghani\Desktop\codecanyon-KR3ZqdhA-fluxstore-multi-vendor-flutter-ecommerce-full-app\FluxStore-vendor-1.7.5\source\build, but the tool couldn't find it.

**Comment by ameenbadri7** [comment]
Please help us to submit this form and fill all the required info to continue with the support - http://verify.inspireui.com.

Don't open other tickets without submitting to the link above.

**Comment by minhcasi** [comment]
@EISAGHANI - pls help to use the latest release `1.7.6` to fix the build issue, also make sure to clean up the Flutter cache by using this guide - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1 - thank you!

**Comment by minhcasi** [comment]
verified purchase at #4400 ✅

**Comment by ameenbadri7** [comment]
Hi ,

I'm sorry to close this ticket as there is no response or active conversation. 

Please help to create a new one and link to this ticket if the problem is not solved. 

- Thank you for your time!
