### ISSUE TITLE
Because flutter_html 1.0.0 depends on flutter_svg ^0.17.4 and no versions of flutter_html match >1.0.0 <2.0.0, flutter_html ^1.0.0 requires flutter_svg ^0.17.4.

### ISSUE THREAD

**Issue by AbimaelASilva** [inspireui/support#4399]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 

+ Product & version: 1.7.6

+ Flutter (or React Native) version: Flutter 1.20.0-7.2.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision a2bde82fbd (10 days ago) • 2020-07-18 15:16:35 -0700
Engine • revision 60b269d898
Tools • Dart 2.9.0 (build 2.9.0-21.2.beta)

+ Testing Device/Simulator: 

+ Screenshot issues (drag the file to attach here): 

----------------------------------------------------------------------------------------------------------------------------------------------
Good Morning.

The current problem seems to have started after I updated the flutter.

After the update when I run the "flutter run" he started giving the error error below:

C:\ProjetosFlutter\flux>flutter run
Running "flutter pub get" in flux...                                5,3s
Using hardware rendering with device Android SDK built for x86. If you notice graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
Launching lib\main.dart on Android SDK built for x86 in debug mode...
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:88:26: Error: Type 'DiagnosticableMixin' not found.
class PictureStream with DiagnosticableMixin {
                         ^^^^^^^^^^^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:192:44: Error: Type 'DiagnosticableMixin' not found.
abstract class PictureStreamCompleter with DiagnosticableMixin {
                                           ^^^^^^^^^^^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:88:7: Error: The type 'DiagnosticableMixin' can't be mixed in.
class PictureStream with DiagnosticableMixin {
      ^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:192:16: Error: The type 'DiagnosticableMixin' can't be mixed in.
abstract class PictureStreamCompleter with DiagnosticableMixin {
               ^
Running Gradle task 'assembleDebug'...
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:167:11: Error: Superclass has no method named 'debugFillProperties'.
    super.debugFillProperties(properties);
          ^^^^^^^^^^^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:171:30: Error: The method 'toStringShort' isn't defined for the class 'PictureStreamComplet
er'.
 - 'PictureStreamCompleter' is from 'package:flutter_svg/src/picture_stream.dart' ('/C:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart').
Try correcting the name to the name of an existing method, or defining a method named 'toStringShort'.
      ifPresent: _completer?.toStringShort(),
                             ^^^^^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:266:11: Error: Superclass has no method named 'debugFillProperties'.
    super.debugFillProperties(description);
          ^^^^^^^^^^^^^^^^^^^

FAILURE: Build failed with an exception.

* Where:
Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 896

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 25s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                       147,2s (!)
Exception: Gradle task assembleDebug failed with exit code 1

C:\ProjetosFlutter\flux>

![flutter_problem](https://user-images.githubusercontent.com/18286517/88668726-86b5ea80-d0d2-11ea-8a19-4b43e1cb64e0.png)

------------------------------------------------------------------------------------------------------------------------------------------
To try to solve the error I added the dependency "flutter_svg: ^ 0.17.4" but it gives the same error listing above, so I changed the plugin version to "flutter_svg: 0.18.0" and it eliminated some errors, but when running " flutter pub get "now displays the error described below:

C:\flutter\bin\flutter.bat --no-color packages get
Running "flutter pub get" in flux...                            
Because flutter_html 1.0.0 depends on flutter_svg ^0.17.4 and no versions of flutter_html match >1.0.0 <2.0.0, flutter_html ^1.0.0 requires flutter_svg ^0.17.4.

So, because fstore depends on both flutter_html ^1.0.0 and flutter_svg ^0.18.0, version solving failed.
pub get failed (1; So, because fstore depends on both flutter_html ^1.0.0 and flutter_svg ^0.18.0, version solving failed.)
Process finished with exit code 1

![flutter_problem2](https://user-images.githubusercontent.com/18286517/88668749-8ddcf880-d0d2-11ea-88ff-a2cb048588c2.png)

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 

Thank you for your time!

**Comment by minhcasi** [comment]
@AbimaelASilva - try to use flutter stable channel 
```
flutter channel stable
flutter upgrade --force
```

**Comment by minhcasi** [comment]
@kenngigz - let us know if you have any further issues 👍 - thank you!
