### ISSUE TITLE
[EvaStore] - Error on loading Wish List

### ISSUE THREAD

**Issue by leotseng159** [inspireui/support#44]
EvaStore - Shopify mobile store by React Native and GraphQL

5b34e5b9-c0cf-4d52-9fae-1ff1168746f2
Describe the bug

When i trying to load the wish list its get error. TypeError: undefined is not an object (evaluating ‘product.id’)

Screenshots
https://www.dropbox.com/s/a3op5wevc8vvkwq/IMG_2581.PNG?dl=0

Thank you!

**Comment by luyx2412** [comment]
Fixed with next version. Closed
