### ISSUE TITLE
[ListApp]Can`t run on android emulator

### ISSUE THREAD

**Issue by Pars1vaLl** [inspireui/support#440]
**Mandatory Info (please complete the following information):**
 - Product:  ListApp
- Your Purchased Code: 85059e37-2ddd-478d-899b....

**Describe the issues**
I got such error trying to launch the app on android emulator: ![Screenshot_2](https://user-images.githubusercontent.com/45024483/54991648-35c64b80-4fdf-11e9-8b59-7484a64af787.png)

How to enable Wp auth in JSON api settings. There isn`t auth line in my case: ![Screenshot_3](https://user-images.githubusercontent.com/45024483/54991808-85a51280-4fdf-11e9-9bea-9b8040f22fd2.png)

Thanks

**Comment by thangvo9x** [comment]
Yes. You enabled it. Can you share your AppConfig file for checking, plz? such as give full purchase code.

**Comment by Pars1vaLl** [comment]
Hi, I have sent AppConfig and full purchase code to this email: thangvo5969@gmail.com

**Comment by Pars1vaLl** [comment]
@thangvo9x  Hello, did you check it?

**Comment by thangvo9x** [comment]
Hi. i didn't receive your email. please run yarn install on your folder.

**Comment by Pars1vaLl** [comment]
> Hi. i didn't receive your email. please run yarn install on your folder.

Hi! I have sent it again. Please check.
Yarn install stacks in Fetching packages.

Thanks

**Comment by thangvo9x** [comment]
Hi. I checked your source. It works normally. You have only updated to the last version of the yarn package. Try to remove node_modules and run "yarn install" again from the command line.
P/s: Your domain is differencing to the previous ticket.

**Comment by Pars1vaLl** [comment]
Hi. I will try it. Thanks.
P.S. Hmm,maybe there was my sub-domain which I use for testing? Because I don`t have any other sites:) I can share it with you If needed:)
