### ISSUE TITLE
Parameter format incorrect

### ISSUE THREAD

**Issue by EISAGHANI** [inspireui/support#4400]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
Every time i run my code in Android studio i see this error, i don’t know what to do? Launching lib\main.dart on Android SDK built for x86 in debug mode… Running Gradle task ‘assembleDebug’... Parameter format not correct - Exception: Gradle build failed to produce an .apk file. It’s likely that this file was generated under C:\Users\Eisa Ghani\Desktop\codecanyon-KR3ZqdhA-fluxstore-multi-vendor-flutter-ecommerce-full-app\FluxStore-vendor-1.7.5\source\build, but the tool couldn’t find it.
+ Product & version:
Android Studio
+ Flutter (or React Native) version: 
1.17.5-stable
+ Testing Device/Simulator:
Android Emulator 
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by ameenbadri7** [comment]
Please help us to submit this form and fill all the required info to continue with the support - http://verify.inspireui.com.

Don't open other tickets without submitting to the link above.
If you continue to open tickets without any verification I will report on your account as spam.
This is your last warning! 

Thank you!

**Comment by EISAGHANI** [comment]
Dear i have already submitted the form

**Comment by ameenbadri7** [comment]
Copy the folder `FluxStore-vendor-1.7.5\source\` to new folder inside the C:\newsrc
and then build your project app from the new folder inside the C partition.

let us know if you still have problems.
