### ISSUE TITLE
wcfm stores not showing

### ISSUE THREAD

**Issue by kenngigz** [inspireui/support#4402]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 
 
i am using wcfm and its not showing stores in my app. 
![image](https://user-images.githubusercontent.com/57593885/88703663-a91d2780-d115-11ea-94ff-6d3ebd6b8699.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

![image](https://user-images.githubusercontent.com/57593885/88703953-13ce6300-d116-11ea-8de5-a8e85535b2d8.png)

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by ameenbadri7** [comment]
Hi, @kenngigz 
Please use our [documentaion ](https://docs.inspireui.com/fluxstore/woocommerce-setup/) to setup your website.

**Comment by kenngigz** [comment]
> Hi, @kenngigz
> Please use our [documentaion ](https://docs.inspireui.com/fluxstore/woocommerce-setup/) to setup your website.

I  ALREADY DID THIS. BUT STILL DOESNT WORK

**Comment by minhcasi** [comment]
@kenngigz - please help to fix by this solution - https://github.com/inspireui/support/issues/4346#issuecomment-664844336

**Comment by minhcasi** [comment]
@kenngigz - let us know if you have any further issues 👍 - thank you!
