### ISSUE TITLE
Font on Custom Page too can't be seen

### ISSUE THREAD

**Issue by Yusadolat** [inspireui/support#4405]
**_Step 1 (require): describe detail issues & screenshots_**
Text on the Custom page (both About Us and Contact page) can't be seen on a real device. It's too small to view
+ Detail Issues: 
+ Product & version: 3.0.7
+ Flutter (or React Native) version:  React Native
+ Testing Device/Simulator: Real Device
+ Screenshot issues (drag the file to attach here): 
![Screenshot_1595848398](https://user-images.githubusercontent.com/10975011/88717648-bf78b280-d118-11ea-9ee6-2ba16801e346.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by luyx2412** [comment]
Hi @Yusadolat You can change font size bigger in `src/components/WebView/WebView.js` line 38
![image](https://user-images.githubusercontent.com/8909619/88804868-b51ded80-d1d8-11ea-9cfe-9c2014d76510.png)

Or you can create About us or Contact us screen and add text to it which will control better than using Webview.

Thanks

**Comment by Yusadolat** [comment]
Thanks for your answer @luyx2412

**Comment by Yusadolat** [comment]
How do I go about creating about us and contact us screen?
