### ISSUE TITLE
FluxStore Pro Prestashop - Issue with create order not showing products on website backoffice

### ISSUE THREAD

**Issue by benzhir** [inspireui/support#4406]
FluxStore Prestashop 1.7.6
Flutter v 1.17.5
Testing Device
![Capture du 2020-07-28 21-30-24](https://user-images.githubusercontent.com/44715941/88718553-fa2f1a80-d119-11ea-95f1-a94215dafd4a.png)

**Comment by ameenbadri7** [comment]
Hi, Please add the new tickets to your last [ticket ](https://github.com/inspireui/support/issues/4385).
So we can answer you faster.

Thank you.
