### ISSUE TITLE
Shipping not display

### ISSUE THREAD

**Issue by MorisTech** [inspireui/support#4407]
@philipvu30 @minhcasi 

Here was my issue that was fixed
https://github.com/inspireui/support/issues/4128

Now my customers are having issues with the shipping page
![WhatsApp Image 2020-07-29 at 1 40 32 AM](https://user-images.githubusercontent.com/31305956/88743505-c9141180-d13c-11ea-93a9-959c1a5ec3d4.jpeg)

It's not showing a shipping method

**Comment by rabeehlive** [comment]
Iam also looking for same solution

**Comment by minhcasi** [comment]
@minhtruong315 - pls check the shipping issue

**Comment by minhtruong315** [comment]
@MorisTech Can u send me common folder via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/4407

**Comment by MorisTech** [comment]
Sent to your mail @minhtruong315

**Comment by alexrali** [comment]
same problem here, please help!

**Comment by MorisTech** [comment]
No one as replied me @minhtruong315 @minhcasi

**Comment by minhtruong315** [comment]
Hi @MorisTech pls send me admin account as well.
Thanks

**Comment by MorisTech** [comment]
Wordpress?

**Comment by minhtruong315** [comment]
yes.

**Comment by minhtruong315** [comment]
Hi @MorisTech add state_ng.json in config/states folder
[state_ng.json.zip](https://github.com/inspireui/support/files/5004478/state_ng.json.zip)

**Comment by MorisTech** [comment]
Alright 
Will do..

Thanks

**Comment by minhtruong315** [comment]
@MorisTech let me know the result. thanks

**Comment by minhcasi** [comment]
'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
