### ISSUE TITLE
Fluxstore I need some adjustments to the shipping address

### ISSUE THREAD

**Issue by haidarsalim** [inspireui/support#4408]
Fluxstore Version: 1.7.6
Flutter : v1.17.5

I need some adjustments to the shipping address

1- Hide address search button     Disabling site services permissions, if possible
2- Hide country selection and make Iraq a default address
3- Hide the zip code field Or ext make it not required
![1111111111](https://user-images.githubusercontent.com/54249914/88763467-d997ac80-d17b-11ea-8678-46d76490c4ad.PNG)

**Comment by minhcasi** [comment]
1. update 'allowSearchingAddress': false - https://tppr.me/hFCei

2. update this setting https://tppr.me/49qtq 

3. Please try your best to investigate the source code and make customization for these features by using Inspector Tools - https://www.youtube.com/watch?v=yGMt3Y20Zmg

Allow us to close the ticket as this is not related to the issues of the app. Please note that we will not support answering or support technical issues for the regular license as per support policies - https://inspireui.com/support-policies/ - Hope you enjoy the product and stay safe 😊
