### ISSUE TITLE
Bank Tranfer Checkout no works 2

### ISSUE THREAD

**Issue by politos89** [inspireui/support#4411]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: Ticket 4340
https://github.com/inspireui/support/issues/4340
Hello apologies for the response time. In the previous ticket they asked me for the common folder. Attached to the new ticket.
+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by ameenbadri7** [comment]
Hi @politos89 
I have reopened your issue you can comment about your issue thair.
I will close this to continue their, our team will help dont worry. 
THANK YOU!
