### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by MaNoOoz** [inspireui/support#4417]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
it's my first build after I open the project on android studio something wrong  with third party libraries u guys use a lot of them xD 
 The Error: 
```
BUILD FAILED in 3m 14s
Exception: Gradle task assembleDebug failed with exit code 1
```
+ Product & version:
\FluxStore-pro-1.7.6

+ Flutter (or React Native) version: 
`[√] Flutter (Channel stable, v1.17.4, on Microsoft Windows [Version 10.0.18363.959], locale en-US)`

+ Testing Device/Simulator: 

+ Screenshot issues (drag the file to attach here): 
```
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
Target debug_android_application failed: FileSystemException: Cannot copy file to 'H:\WORK\FreeLance\codecanyon-G146ryl1-fluxstore-the-universal-woocommerce-magento-opencart-mobile-app-by-flutter-framework\FluxStore-pro-1.7.6\source\build\app\intermediates\flutter\debug\flutter_assets\packages/awesome_card/images/card_provider/master_card.png', path = 'H:\FlutterSDK\.pub-cache\hosted\pub.dartlang.org\awesome_card-1.1.0\images\card_provider\master_card.png' (OS Error: The system cannot find the path specified.
, errno = 3)
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'H:\FlutterSDK\packages\flutter_tools\gradle\flutter.gradle' line: 882

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'H:\FlutterSDK\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 14s
Exception: Gradle task assembleDebug failed with exit code 1

```
I don't know if the project will build even if this issue fixed so maybe i reopen this ticket 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@MaNoOoz - please get started with this document first to set up your Flutter environment - https://flutter.dev/docs/get-started/install

Or see our video guide - https://docs.inspireui.com/fluxstore/woocommerce-setup/

**Comment by MaNoOoz** [comment]
yes i solve the problem by moving  the source folder to another path
