### ISSUE TITLE
Search result show regular price only

### ISSUE THREAD

**Issue by samer-ibrahim** [inspireui/support#4419]
Dear InspirUI team,
(Fluxstore woocommerce) Flutter version 1.7.5
Previous ticket # #3753

Regarding  home screen, search bar, the results of search show only regular price (simple list view) can we change something in code that let the results show both prices regular and sale price ?

![1](https://user-images.githubusercontent.com/66953736/88910335-0673be80-d265-11ea-89c6-64c09abeb402.jpg)

![2](https://user-images.githubusercontent.com/66953736/88910365-0d023600-d265-11ea-83e6-941f65b06098.jpg)

![3](https://user-images.githubusercontent.com/66953736/88910381-125f8080-d265-11ea-8a36-aea79f83db89.jpg)

**Comment by minhcasi** [comment]
@samer-ibrahim - we will investigate and keep upgrade on this feature, it seems there is a missing sale price on the search result.

**Comment by simonpham** [comment]
Hi @samer-ibrahim 

This will be available in the next version 1.7.7.

Thank you for your suggestion.

**Comment by samer-ibrahim** [comment]
Thanks and good luck in next update.
Thank you for everyone.
