### ISSUE TITLE
[CeStore] Missing mongodb_bk folder

### ISSUE THREAD

**Issue by deepakjain29** [inspireui/support#442]
**Required Info (please complete the following information):**
 - Product: [CeStore]
 - Your Purchased Code: [**4509e66c-d8d4-XXXX-ba43-XXca32aaa067**]
(I have hid some part of it)

**Describe the bug**
we have installed the web App , but couldnt load default data as we couldnt find mongodb_bk folder in the downloaded project files.

regards
javinindia

**Comment by deepakjain29** [comment]
1. We have installed the Cestore as per the documentation , but we havent received MongoDB Data for products and categories in the website.
2. Also cart and checkout pages are not working
3. We are unable to install Theme from the Admin panel as we have no Theme Zip folder in the project file.
Are we missing something here 
please check this link - 139.59.91.132:3000
my Skype Id is - deepakjain29

**Comment by deepakjain29** [comment]
We are getting the below error 
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at ‘http://139.59.91.132:3001/ajax/products?fields=path%2Cid%2Cname%2Ccategory_id%2Ccategory_name%2Csku%2Cimages%2Cenabled%2Cdiscontinued%2Cstock_status%2Cstock_quantity%2Cprice%2Con_sale%2Cregular_price%2Cattributes%2Ctags&limit=8&offset=0&search&sort=-date_updated’. (Reason: Credential is not supported if the CORS header ‘Access-Control-Allow-Origin’ is ‘*’).[Learn More]

I think port 3000 & 3001 are not able to communicate with each other
regards
Deepak
javin.retails@gmail.com

**Comment by minhtruong315** [comment]
Hi @deepakjain29 
The mongodb_bk folder is in source code. pls check it again. 
The install theme doesn't support now.
