### ISSUE TITLE
npm install error on api-ecommerce package

### ISSUE THREAD

**Issue by AsifiweM** [inspireui/support#4420]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
Downloaded the Mstore MultiVendor template and did npm install but api-ecommerce package has errors
+ Product & version:
Mstore Multi Vendor v1.3
+ Flutter (or React Native) version: 
Expo v3.15.5
+ Testing Device/Simulator: 
Honor 7c
+ Screenshot issues (drag the file to attach here): 
![Untitled](https://user-images.githubusercontent.com/50745253/88916602-a716ae00-d266-11ea-910f-9d641bc00299.png)

Verbose Error log

> grpc@1.20.0 install C:\Users\TOSHIBA\Documents\KStorez\KStorez\mstore-mv-expo\node_modules\grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://node-precompiled-binaries.grpc.io/grpc/v1.20.0/node-v72-win32-x64-unknown.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for grpc@1.20.0 and node@12.14.1 (node-v72 ABI, unknown) (falling back to source compile with node-gyp) 
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Users\TOSHIBA\Documents\KStorez\KStorez\mstore-mv-expo\node_modules\grpc\build\WINDOWS_BUILD_WARNING.vcxproj(20,3): error MSB4019: The imported p
roject "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on dis
k.
C:\Users\TOSHIBA\Documents\KStorez\KStorez\mstore-mv-expo\node_modules\grpc\build\boringssl.vcxproj(20,3): error MSB4019: The imported project "C:\M
icrosoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
C:\Users\TOSHIBA\Documents\KStorez\KStorez\mstore-mv-expo\node_modules\grpc\build\gpr.vcxproj(20,3): error MSB4019: The imported project "C:\Microso
ft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
C:\Users\TOSHIBA\Documents\KStorez\KStorez\mstore-mv-expo\node_modules\grpc\build\grpc.vcxproj(20,3): error MSB4019: The imported project "C:\Micros
oft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
C:\Users\TOSHIBA\Documents\KStorez\KStorez\mstore-mv-expo\node_modules\grpc\build\z.vcxproj(20,3): error MSB4019: The imported project "C:\Microsoft
.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=C:\\Users\\TOSHIBA\\Documents\\KStorez\\KStorez\\mstore-mv-expo\\node_modules\\grpc\\src\\node\\extension_binary\\node-v72-win32-x64-unknown\\grpc_node.node" "--module_name=grpc_node" "--module_path=C:\\Users\\TOSHIBA\\Documents\\KStorez\\KStorez\\mstore-mv-expo\\node_modules\\grpc\\src\\node\\extension_binary\\node-v72-win32-x64-unknown" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd C:\Users\TOSHIBA\Documents\KStorez\KStorez\mstore-mv-expo\node_modules\grpc
gyp ERR! node -v v12.14.1
gyp ERR! node-gyp -v v5.1.1
gyp ERR! not ok
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --library=static_library --module=C:\Users\TOSHIBA\Documents\KStorez\KStorez\mstore-mv-expo\node_modules\grpc\src\node\extension_binary\node-v72-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=C:\Users\TOSHIBA\Documents\KStorez\KStorez\mstore-mv-expo\node_modules\grpc\src\node\extension_binary\node-v72-win32-x64-unknown --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\TOSHIBA\Documents\KStorez\KStorez\mstore-mv-expo\node_modules\grpc\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
node-pre-gyp ERR! System Windows_NT 10.0.18363
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\TOSHIBA\\Documents\\KStorez\\KStorez\\mstore-mv-expo\\node_modules\\grpc\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd C:\Users\TOSHIBA\Documents\KStorez\KStorez\mstore-mv-expo\node_modules\grpc
node-pre-gyp ERR! node -v v12.14.1
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --library=static_library --module=C:\Users\TOSHIBA\Documents\KStorez\KStorez\mstore-mv-expo\node_modules\grpc\src\node\extension_binary\node-v72-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=C:\Users\TOSHIBA\Documents\KStorez\KStorez\mstore-mv-expo\node_modules\grpc\src\node\extension_binary\node-v72-win32-x64-unknown --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)  
npm WARN @react-native-community/masked-view@0.1.5 requires a peer of react-native@^0.57 but none is installed. You must install peer dependencies yourself.
npm WARN modal-react-native-web@0.2.0 requires a peer of react-art@16.x.x but none is installed. You must install peer dependencies yourself.
npm WARN modal-react-native-web@0.2.0 requires a peer of react-dom@16.x.x but none is installed. You must install peer dependencies yourself.        
npm WARN modal-react-native-web@0.2.0 requires a peer of react-native-web@0.9.x but none is installed. You must install peer dependencies yourself.  
npm WARN react-instantsearch-dom@6.7.0 requires a peer of react-dom@>= 16.3.0 < 17 but none is installed. You must install peer dependencies yourself.
npm WARN react-native@0.61.4 requires a peer of react@16.9.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-country-picker-modal@1.10.0 requires a peer of react-dom@* but none is installed. You must install peer dependencies yourself.
npm WARN react-native-country-picker-modal@1.10.0 requires a peer of react-native-web@* but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\@jest\core\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\@jest\reporters\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\@jest\test-sequencer\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\@jest\transform\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\jest-runtime\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.20.0 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@1.20.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\TOSHIBA\AppData\Roaming\npm-cache\_logs\2020-07-30T10_07_29_938Z-debug.log

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by luyx2412** [comment]
Hi @AsifiweM Please change to yarn to install and make sure node version is 10.x.x https://yarnpkg.com/

Thanks

**Comment by AsifiweM** [comment]
Hi @luyx2412, Thank you for the recommendation. I fixed it by upgrading to api-ecommerce version 0.0.36
