### ISSUE TITLE
Module 'Mstore_Catalog ' is not correctly registered. Magento 2.2.6

### ISSUE THREAD

**Issue by Alone225** [inspireui/support#4424]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
Delivery method on admin panel i have an error Exception #0 (InvalidArgumentException): Module ‘Mstore_Catalog ’ is not correctly registered.
+ Product & version: Fluxtore pro 1.7.6
+ Flutter (or React Native) version: 1.17.2 Magento 2.2.6
+ Testing Device/Simulator:  Simulator
+ Screenshot issues (drag the file to attach here): 
![issusfluxstore](https://user-images.githubusercontent.com/13910648/88927801-7e42e880-d267-11ea-9e99-52c2eeef825f.PNG)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 

Thank you for your time!

**Comment by Alone225** [comment]
Hi. I Already submitted the form

‪Le jeu. 30 juil. 2020 à 17:38, ‫amin badri أمين بدري‬‎ <
notifications@github.com> a écrit :‬

**Comment by minhcasi** [comment]
@minhtruong315 - please help to investigate this issue

**Comment by Alone225** [comment]
Please help me solve the problem .

**Comment by minhtruong315** [comment]
@Alone225 can u send me account to login to your host via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/4424

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!

**Comment by Alone225** [comment]
I have reproduced the issu look at this video
https://www.loom.com/share/6c415b27d8d942dc812c8d0b65a418a3

Please reopen the issu.

Le mar. 4 août 2020 à 22:42, minhtruong315 <notifications@github.com> a
écrit :
