### ISSUE TITLE
Version solving failed after app update

### ISSUE THREAD

**Issue by Fovorno** [inspireui/support#4425]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

![image](https://user-images.githubusercontent.com/27883324/88949527-5c466780-d261-11ea-80df-e8a1d4690753.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

So I downloaded recent app update, but it fails to run in Android, the older app version opens and works just fine but the new one does not. 

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by ameenbadri7** [comment]
Hi, @Fovorno 
Update your flutter to the latest stable version also use this [guide ](https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1) to fix all your build problems.
It's working will all our customers just try to update your development environment.

Thank you, sir.

**Comment by ameenbadri7** [comment]
I'm sorry to close this ticket as there is no response or active conversation. 

Please help to create a new one and link to this ticket if the problem is not solved. 

- Thank you for your time!
