### ISSUE TITLE
FLuxstore color change app

### ISSUE THREAD

**Issue by nomicool** [inspireui/support#4426]
In color.dart I was only able to change settings page color and stores color how to change colors of all pages and buttons float buttons everything current color to my own color

**Comment by ameenbadri7** [comment]
go to `lib\config\config_en.json` and change the `MainColor` to the color you want:
```
"Setting": {
    "MainColor": "#3FC1BE",
    "ProductListLayout": "list",
    "StickyHeader": true
  },
```
You could try to use the [Inspector ](https://www.youtube.com/watch?v=yGMt3Y20Zmg)Tools to support the customization of your app.

Please read all fluxstore [documentation ](https://docs.inspireui.com/fluxstore)so you can fix any problems you have.

Thank you !

**Comment by ameenbadri7** [comment]
I'm sorry to close this ticket as there is no response or active conversation. 

Please help to create a new one and link to this ticket if the problem is not solved. 

- Thank you for your time!
