### ISSUE TITLE
One Signal Push notifications

### ISSUE THREAD

**Issue by rmonst3r** [inspireui/support#4427]
Hello,

 I have Fluxnews and One Signal set up on Wordpress and the app.

When I send a push notification from Wordpress, the app receives it but when I tap on the notification on device, it opens the website article rather than the deep link within the app.

How can this be resolved? thanks!

**Comment by minhcasi** [comment]
@rmonst3r 

you may could not open the post directly when receiving the message, instead of opening the Webview from the app. To fix this issue, please update the functions.php file from the Wordpress site:

```
function onesignal_send_notification_filter($fields, $new_status, $old_status, $post)
{
    $fields['isAndroid'] = true;
    $fields['isIos'] = true;
    $fields['isAnyWeb'] = false;
    $fields['isChrome'] = false;
    $fields['data'] = array(
        "id" => $post->ID,
    );
    /* Unset the URL to prevent opening the browser when the notification is clicked */
    unset($fields['url']);
    return $fields;
}
add_filter('onesignal_send_notification', 'onesignal_send_notification_filter', 10, 4);
```

**Comment by rmonst3r** [comment]
Thanks I will try it today and update

**Comment by rmonst3r** [comment]
Ok the app now opens the article put the image field is blank and there is a white box on the bottom. 
see pic: https://ibb.co/0yy1mw1

**Comment by minhcasi** [comment]
@rmonst3r - pls try to check if you have run the Regenerate image to optimize the image  - https://docs.inspireui.com/fluxnews/getting-started/#setup-the-regenerate-thumbnails-plugin? 

Does it appear image normally on another screen, or just happen on push notification screen?

**Comment by rmonst3r** [comment]
It happens only for push notifications.

It looks like the white bar below is the related stories that don't load either.

I will pull the log from Android Studio for you and post it here.

> @rmonst3r - pls try to check if you have run the Regenerate image to optimize the image - https://docs.inspireui.com/fluxnews/getting-started/#setup-the-regenerate-thumbnails-plugin?
> 
> Does it appear image normally on another screen, or just happen on push notification screen?

**Comment by imbritto** [comment]
Ok with this fix Notification opens the actual article. But the image doesn't load also "Things you might love" section gives "Error getting data"
![Screenshot 2020-08-01 at 15 20 12](https://user-images.githubusercontent.com/45955188/89103603-d534f300-d40a-11ea-9257-7fcae3740d99.png)
![Screenshot 2020-08-01 at 15 19 46](https://user-images.githubusercontent.com/45955188/89103604-d6662000-d40a-11ea-9e4e-55769219c512.png)

**Comment by rmonst3r** [comment]
Here's the log:

`flutter: {
  "payload": "{
  "aps": {
    "alert": {
      "title": "CNC3",
      "body": "UNC Couva staffer’s husband COVID-positive"
    },
    "mutable-content": 1,
    "sound": "default"
  },
  "custom": {
    "a": {
      "id": 18066
    },
    "i": "b8afed83-6ccc-49ec-9e9c-0cc9723f96e4"
  }
}",
  "displayType": 2,
  "shown": true,
  "appInFocus": false,
  "silent": false
}
[http] #1 • GET https://www.cnc3.co.tt/wp-json/wp/v2/posts/18066 • open
[http] #1 • GET https://www.cnc3.co.tt/wp-json/wp/v2/posts/18066 • request ready
[http] #1 • GET https://www.cnc3.co.tt/wp-json/wp/v2/posts/18066 • 200 OK
       {
         "connection": "keep-alive",
         "cache-control": "public, max-age\u003d1800",
         "set-cookie": "__cfduid\u003dddc1c67d930eb6e54027c14c35297dc1d1596300913; expires\u003dMon, 31-Aug-20 16:55:13 GMT; path\u003d/; domain\u003d.cnc3.co.tt; HttpOnly; SameSite\u003dLax",
         "cf-request-id": "044c8c048c000011816f3f0200000001",
         "transfer-encoding": "chunked",
         "date": "Sat, 01 Aug 2020 16:55:15 GMT",
         "content-encoding": "gzip",
         "vary": "Accept-Encoding,Cookie,Origin",
         "x-robots-tag": "noindex",
         "access-control-expose-headers": "X-WP-Total, X-WP-TotalPages",
         "cf-cache-status": "MISS",
         "expect-ct": "max-age\u003d604800, report-uri\u003d\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"",
         "content-type": "application/json; charset\u003dUTF-8",
         "server": "cloudflare",
         "link": "\u003chttps://www.cnc3.co.tt/unc-couva-staffers-husband-covid-positive/\u003e; rel\u003d\"alternate\"; type\u003dtext/html",
         "x-powered-by": "PHP/7.2.24",
         "access-control-allow-headers": "Authorization, Content-Type",
         "alt-svc": "h3-27\u003d\":443\"; ma\u003d86400, h3-28\u003d\":443\"; ma\u003d86400, h3-29\u003d\":443\"; ma\u003d86400",
         "cf-ray": "5bc115e7493b1181-MIA",
         "x-content-type-options": "nosniff",
         "allow": "GET",
         "expires": "Sat, 01 Aug 2020 17:25:15 GMT"
       }
flutter: snapshot.dataaa Blog { id: 18066 date: 2020-08-01T00:00:00 name: UNC Couva staffer’s husband COVID-positive cateid null}
[http] #1 • GET https://www.cnc3.co.tt/wp-json/wp/v2/posts?_embed&categories=null • open
[http] #1 • GET https://www.cnc3.co.tt/wp-json/wp/v2/posts?_embed&categories=null • request ready
[http] #1 • GET https://www.cnc3.co.tt/wp-json/wp/v2/posts?_embed&categories=null • 400 Bad Request
       {
         "connection": "keep-alive",
         "set-cookie": "__cfduid\u003ddcdb22e524dba17b78143ee46d117dfeb1596300916; expires\u003dMon, 31-Aug-20 16:55:16 GMT; path\u003d/; domain\u003d.cnc3.co.tt; HttpOnly; SameSite\u003dLax",
         "cf-request-id": "044c8c0ead000011816922b200000001",
         "transfer-encoding": "chunked",
         "date": "Sat, 01 Aug 2020 16:55:18 GMT",
         "vary": "Accept-Encoding,Cookie,Origin",
         "x-robots-tag": "noindex",
         "access-control-expose-headers": "X-WP-Total, X-WP-TotalPages",
         "cf-cache-status": "MISS",
         "expect-ct": "max-age\u003d604800, report-uri\u003d\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"",
         "content-type": "application/json; charset\u003dUTF-8",
         "server": "cloudflare",
         "link": "\u003chttps://www.cnc3.co.tt/wp-json/\u003e; rel\u003d\"https://api.w.org/\"",
         "x-powered-by": "PHP/7.2.24",
         "access-control-allow-headers": "Authorization, Content-Type",
         "alt-svc": "h3-27\u003d\":443\"; ma\u003d86400, h3-28\u003d\":443\"; ma\u003d86400, h3-29\u003d\":443\"; ma\u003d86400",
         "cf-ray": "5bc115f779b61181-MIA",
         "x-content-type-options": "nosniff",
         "allow": "GET"
       }`

**Comment by minhcasi** [comment]
@rmonst3r - there is any issue to get your image post feature, please try the following solutions:

1. Install and ative this plugin - https://wordpress.org/plugins/better-rest-api-featured-images/

2. Update the blog_new.dart model by adding these code:
```
if (imageFeature == null && parsedJson['jetpack_featured_media_url']!= null) {
        imageFeature = parsedJson['jetpack_featured_media_url'];
      }
```
<img width="1161" alt="Screen Shot 2020-08-02 at 09 03 11" src="https://user-images.githubusercontent.com/1459805/89113743-00692200-d49f-11ea-8825-de8f86898362.png">

**Comment by rmonst3r** [comment]
Thank you will try and post results.

**Comment by rmonst3r** [comment]
Plugin installed and code inserted into the blog_news.dart but it's still happening.

Interestingly, the image is now grey instead of white:
https://ibb.co/ByDZHhQ


flutter: {
  "payload": "{
  "aps": {
    "alert": {
      "title": "CNC3",
      "body": "Stuart threatens"
    },
    "mutable-content": 1,
    "sound": "default"
  },
  "custom": {
    "a": {
      "id": 18166
    },
    "i": "422fdcb7-bfd6-4e35-888b-1073b8e6ea91"
  }
}",
  "displayType": 2,
  "shown": true,
  "appInFocus": true,
  "silent": false
}
[http] #1 • GET https://www.cnc3.co.tt/wp-json/wp/v2/posts/18166 • open
[http] #1 • GET https://www.cnc3.co.tt/wp-json/wp/v2/posts/18166 • request ready
[http] #1 • GET https://www.cnc3.co.tt/wp-json/wp/v2/posts/18166 • 200 OK
       {
         "connection": "keep-alive",
         "cache-control": "public, max-age\u003d1800",
         "set-cookie": "__cfduid\u003dd0c6d3705e4717498444e28471cb1d4141596412633; expires\u003dTue, 01-Sep-20 23:57:13 GMT; path\u003d/; domain\u003d.cnc3.co.tt; HttpOnly; SameSite\u003dLax",
         "cf-request-id": "045334b9780000118164804200000001",
         "transfer-encoding": "chunked",
         "date": "Sun, 02 Aug 2020 23:57:15 GMT",
         "content-encoding": "gzip",
         "vary": "Accept-Encoding,Cookie,Origin",
         "x-robots-tag": "noindex",
         "access-control-expose-headers": "X-WP-Total, X-WP-TotalPages",
         "cf-cache-status": "MISS",
         "expect-ct": "max-age\u003d604800, report-uri\u003d\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"",
         "content-type": "application/json; charset\u003dUTF-8",
         "server": "cloudflare",
         "link": "\u003chttps://www.cnc3.co.tt/stuart-threatens/\u003e; rel\u003d\"alternate\"; type\u003dtext/html",
         "x-powered-by": "PHP/7.2.24",
         "access-control-allow-headers": "Authorization, Content-Type",
         "alt-svc": "h3-27\u003d\":443\"; ma\u003d86400, h3-28\u003d\":443\"; ma\u003d86400, h3-29\u003d\":443\"; ma\u003d86400",
         "cf-ray": "5bcbbd6f2f0b1181-MIA",
         "x-content-type-options": "nosniff",
         "allow": "GET",
         "expires": "Mon, 03 Aug 2020 00:27:15 GMT"
       }
flutter: snapshot.dataaa Blog { id: 18166 date: 2020-08-02T00:00:00 name: Stuart threatens cateid null}
[http] #1 • GET https://www.cnc3.co.tt/wp-json/wp/v2/posts?_embed&categories=null • open
[http] #1 • GET https://www.cnc3.co.tt/wp-json/wp/v2/posts?_embed&categories=null • request ready
[http] #1 • GET https://www.cnc3.co.tt/wp-json/wp/v2/posts?_embed&categories=null • 400 Bad Request
       {
         "connection": "keep-alive",
         "set-cookie": "__cfduid\u003dd465a8b4b2dd0e7dcb1f1db31227f50b71596412636; expires\u003dTue, 01-Sep-20 23:57:16 GMT; path\u003d/; domain\u003d.cnc3.co.tt; HttpOnly; SameSite\u003dLax",
         "cf-request-id": "045334c3e1000011817021f200000001",
         "transfer-encoding": "chunked",
         "date": "Sun, 02 Aug 2020 23:57:18 GMT",
         "vary": "Accept-Encoding,Cookie,Origin",
         "x-robots-tag": "noindex",
         "access-control-expose-headers": "X-WP-Total, X-WP-TotalPages",
         "cf-cache-status": "MISS",
         "expect-ct": "max-age\u003d604800, report-uri\u003d\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"",
         "content-type": "application/json; charset\u003dUTF-8",
         "server": "cloudflare",
         "link": "\u003chttps://www.cnc3.co.tt/wp-json/\u003e; rel\u003d\"https://api.w.org/\"",
         "x-powered-by": "PHP/7.2.24",
         "access-control-allow-headers": "Authorization, Content-Type",
         "alt-svc": "h3-27\u003d\":443\"; ma\u003d86400, h3-28\u003d\":443\"; ma\u003d86400, h3-29\u003d\":443\"; ma\u003d86400",
         "cf-ray": "5bcbbd7fcaf81181-MIA",
         "x-content-type-options": "nosniff",
         "allow": "GET"
       }

**Comment by rmonst3r** [comment]
We'd appreciate your help in solving this notification issue since this is the only thing holding us back from launching our app.

**Comment by rmonst3r** [comment]
I believe there's a problem loading certain data when the story opens from the push notification since the related categories don't load either.

**Comment by minhcasi** [comment]
@trunghieuvn - please help to investigate this issue 👍

**Comment by rmonst3r** [comment]
Hi guys any update?

**Comment by trunghieuvn** [comment]
Sr for delay,
My email: hieu.trantrung1204@gmail.com

Please add me to access source code git and share me postman can push notification. I will investigate issue when click to noti app will handle deeplink ![Uploading 89261317...]()

**Comment by rmonst3r** [comment]
We're in the process of setting up the GitHub and will reply in a bit when done. 

Thanks for the reply.

**Comment by rmonst3r** [comment]
@trunghieuvn We've invited you to the GitHub and Postman team. Please advise soonest.

Thanks.

**Comment by rmonst3r** [comment]
Hi guys I haven't gotten a reply as yet on email or here. It has been a few days.

**Comment by dttrung26** [comment]
Hi @rmonst3r ,
I'm currently working on your issue and i'll get you back in today. 
So sorry for letting you wait and any inconvinence may cause.

**Comment by rmonst3r** [comment]
Ok thanks much👍

**Comment by dttrung26** [comment]
Hi @rmonst3r , could you please attach your information via verify.inspireui.com and send me your admin access via trung@inspireui.com? Some configurations need to be tested on your own site. 
Nice day.

**Comment by rmonst3r** [comment]
Thanks. Sent.

**Comment by dttrung26** [comment]
Support via Skype.
