### ISSUE TITLE
Error about ratings

### ISSUE THREAD

**Issue by smartbionix** [inspireui/support#4428]
**_Step 1 (require): describe detail issues & screenshots_**
I've tried everything you guys say we should try. Invalidate and restart. Remove pubspec.log and still getting errors. Can't connect it to my virtual phone to even show your app.
+ Detail Issues: 

Compiler message:
../../flutter/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0.6.0+2/lib/src/dialogs.dart:272:17: Error: No named parameter with the name 'onRatingChanged'.
                onRatingChanged: (rating) {
                ^^^^^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/smooth_star_rating-1.1.1/lib/smooth_star_rating.dart:24:3: Context: Found this candidate, but the arguments don't match.
  SmoothStarRating({
  ^^^^^^^^^^^^^^^^

Compiler message:
../../flutter/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0.6.0+2/lib/src/dialogs.dart:272:17: Error: No named parameter with the name 'onRatingChanged'.
                onRatingChanged: (rating) {
                ^^^^^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/smooth_star_rating-1.1.1/lib/smooth_star_rating.dart:24:3: Context: Found this candidate, but the arguments don't match.
  SmoothStarRating({
  ^^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script '/Users/estherc/Downloads/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 882

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/estherc/Downloads/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 53s
Exception: Gradle task assembleDebug failed with exit code 1

+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 
<img width="917" alt="Screen Shot 2020-07-30 at 10 40 05 PM" src="https://user-images.githubusercontent.com/69021830/88994865-50859000-d2b7-11ea-960c-1866c0a2650e.png">

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

Purchase codes
Authors may ask you for a purchase code to verify that you’ve purchased this item.

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@smartbionix 

Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
@smartbionix - sorry for late response, could you help to check the following solutions:

1. using the latest Fluxnew version and flutter stable channel 

2. Clean up the flutter cache by using this guide - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1 - (also try to upgrade the pod library)

**Comment by minhcasi** [comment]
Let us know if you have any further issue - thank you!
