### ISSUE TITLE
Weight Based Shipping not working in Opencart

### ISSUE THREAD

**Issue by atamilvannan** [inspireui/support#4429]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: in our opencart store we use weight-based shipping for geo zones based. but in your fluxstore pro i can't able to see the shipping method. shows error like no shipping method found. if I select flat shipping or free shipping it works. y weight-based shipping is not working kindly solve it soon. 
+ Product & version: Fluxstore Pro (Opencart)
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: Andriod (Tested in REDMI NOTE PRO 5)
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@atamilvannan - the weight-based shipping for geo zones based is not supported for opencart, we will investigate and upgrade it later - thanks

**Comment by miskayapp** [comment]
kindly reopen #4328

**Comment by atamilvannan** [comment]
When can I expect your upgrade ?

**Comment by minhcasi** [comment]
@atamilvannan - we need to investigate the feature first, then will confirm the release on which version - thank you!

**Comment by atamilvannan** [comment]
until that i cant use your product right ?

**Comment by minhcasi** [comment]
@atamilvannan - we will confirm when this feature is ready, in the meantime, you could ignore the `Weight Based Shipping` - thank you!

**Comment by atamilvannan** [comment]
If I ignore weight based shipping. We can't able to serve our customers. Kindly make this issue priority and solve it

**Comment by minhcasi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Opencart: Weight Based Shipping upgrade](https://trello.com/c/sC1nr5xH/67-opencart-weight-based-shipping-upgrade)

**Comment by minhcasi** [comment]
i've moved this ticket to Trello Request ticket and sent to the team for investigating - we will notify on the ticket when it is ready for testing - thank you!

**Comment by atamilvannan** [comment]
Any update ? Still am waiting after my purchase so long ago.

**Comment by atamilvannan** [comment]
?
