### ISSUE TITLE
[Mstore] Layout Error not display all languages

### ISSUE THREAD

**Issue by hakihosting** [inspireui/support#443]
Hello when i change the language in french , The layout of the cebuilder is correct but when i change to another language the layout dissipear.

>VIDEO : 
https://streamable.com/w9wz6

**Comment by luyx2412** [comment]
HI @hakihosting Please follow the template issue and provide your purchase code.

Thanks

**Comment by hakihosting** [comment]
Purchase code : ac9d522a-a783-4f9c-a882-7dc694488d5d

**Comment by luyx2412** [comment]
Hi @hakihosting Please use the debug tools to check your api response https://docs.mstore.io/api-and-project-structure#debug-app-with-reacttotron

Thanks

**Comment by hakihosting** [comment]
Hello i have the API response : 
http://chakcwear.com/wp-json/wc/v2/products/?oauth_consumer_key=ck_7c00db526a82083e44f94b07a80f7e41600e8235&oauth_nonce=qv8SdJq93CM9SJyEjdYQXKsfodQQzzh8&oauth_signature_method=HMAC-SHA256&oauth_timestamp=1553772698&oauth_version=1.0&per_page=10&page=1&purchasable=true&status=publish&category=89&lang=en&oauth_signature=v+pK/6xdKXZBzMb8ghiLP18clOxfoeHTj2TlZ37j4AQ=
Status Code
401
Method
GET
Duration (ms)
3210
code:woocommerce_rest_authentication_error
message:Invalid signature - provided signature does not match.
status:401

**Comment by luyx2412** [comment]
Hi @hakihosting Are your show English language version in your wordpress website? Because the request api alway set `lang=[Your_language]`, so you need language version in your website to show it.

![image](https://user-images.githubusercontent.com/8909619/55205542-edd53d80-5205-11e9-934a-a9d15c0b16b4.png)

Thanks

**Comment by hakihosting** [comment]
Hello yes there is three language on my website

**Comment by hakihosting** [comment]
you can look : http://chakcwear.com/?lang=en

**Comment by luyx2412** [comment]
Hi @hakihosting Please check into your wordpress admin, and make sure three languages translated. And currently we did not document about that, we will update document soon.

Thanks

**Comment by hakihosting** [comment]
Yes , you can see by yourself go to www.chakcwear.com and go in to the three languages

**Comment by hakihosting** [comment]
SOme news about that in version 3.8 still the problem
