### ISSUE TITLE
Need a WebView to a page of website in Drawer

### ISSUE THREAD

**Issue by joepaper** [inspireui/support#4431]
Hello, 
1. Please guide me how to add a list tile to a webview of a page in website in Drawer.
2. Guide me to change the Status Bar color in Home Screen
3. Want to hide filters / attributes irrelevant to categories. Please guide.

I am using Fluxstore 1.7.6

**Comment by minhcasi** [comment]
@joepaper 
We suggest using the Inspector Tool to find the UI you need to customize - https://www.youtube.com/watch?v=yGMt3Y20Zmg

1. edit the `menu.dart` and add the code similar to
<img width="1106" alt="Screen Shot 2020-08-01 at 10 01 03" src="https://user-images.githubusercontent.com/1459805/89092661-eca9b700-d3dd-11ea-8488-7f55ff5f4667.png">

2. change the `MainColor` from config_en.json

3. remove some widget on this file `backdrop_menu.dart`
<img width="1209" alt="Screen Shot 2020-08-01 at 10 37 53" src="https://user-images.githubusercontent.com/1459805/89093278-0f8a9a00-d3e3-11ea-8ab4-e15384278ee1.png">

Please note that we will not support answering or support technical issues for the regular license as per support policies - https://inspireui.com/support-policies/ - Hope you enjoy the product and stay safe 😊

**Comment by minhcasi** [comment]
Let us know if you have any question - thank you!
