### ISSUE TITLE
WooCommerce Error: Sorry, you cannot list resources

### ISSUE THREAD

**Issue by TAMS2018** [inspireui/support#4432]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: I/flutter ( 6599): “I/flutter ( 4475): WooCommerce Error: Sorry, you cannot list resources”. after the wordpress update? the app is live now but unfortunately the categories and products and not all vendors are not displaying on the app.
The rest API is properly configured.

+ Product & version: 7.5
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: android
+ Screenshot issues (drag the file to attach here): 

![image](https://user-images.githubusercontent.com/66580664/89039391-90f71380-d374-11ea-80d1-e1cc05587422.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

![image](https://user-images.githubusercontent.com/66580664/89039661-0a8f0180-d375-11ea-970d-091e9155dc23.png)

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@TAMS2018 - this issue is caused by Rest API is not working correctly. Please help to check the following solutions from the server-side:
1. Check the Rest API via Postman app, pls refer https://github.com/woocommerce/woocommerce/wiki/Getting-started-with-the-REST-API 

2. Resolve 401 Unauthorized issues by using this guide - https://github.com/woocommerce/woocommerce/wiki/Getting-started-with-the-REST-API#401-unauthorized

Let us know your checking, thank you!

**Comment by TAMS2018** [comment]
thank you for response, ill check this reference.

**Comment by TAMS2018** [comment]
Still no work, please any recommendation? i followed all instructions but its no work.

**Comment by minhcasi** [comment]
if it is possible please share your hosting login account to support@inspireui.com - we will help to investigate your server issue - thank you!

**Comment by TAMS2018** [comment]
Thank you for all support, the issue is resolved by reinstalling the WP.

**Comment by minhcasi** [comment]
Congratulation - let us know if you have any question
