### ISSUE TITLE
Save Data into wordpress database

### ISSUE THREAD

**Issue by nahuelbourdichon** [inspireui/support#4433]
Hello,
A few days ago I asked for your support to add some extra field into de fluxstore app. I got an response for your team that you can't  do it , so I made the changes .. but i can't  found the class , service or method that store the information into wordpress database , you would be so kind to tell me which file , contain the method or service that  store this information into data base. 

Regards.

**Comment by minhcasi** [comment]
Hi, please check the `lib/service/woo_commerce.dart` and refer to this document, if you would like to update the data, using POST method to the server, example: https://woocommerce.github.io/woocommerce-rest-api-docs/#create-an-order

**Comment by nahuelbourdichon** [comment]
Thanks to answer , and now i have an issue with my license , I updated the Mstore plugin and now i have a problem with the validation purchase code, 
![image](https://user-images.githubusercontent.com/16769047/89111761-0d9af800-d430-11ea-9cd5-26cc92bd2087.png)

it say that other site is using my license

**Comment by minhcasi** [comment]
@nahuelbourdichon - is it your previous active website? It is possible to reset the License code one time by using the Fluxbuilder tool - http://fluxbuilder.com/ - thank you!

**Comment by nahuelbourdichon** [comment]
Thanks , just one last question of course if you can give me a hand , I need store in wordpress database this information like a meta_data... example
  "meta_data": [        
         {
            "id": 28964,
            "key": "my_field_name",
            "value": "Farmacia Leal"
        },
        {
            "id": 28965,
            "key": "dni",
            "value": "33251697"
        },
        {
            "id": 28966,
            "key": "tn",
            "value": "0000"
         }
    ], 

I can do that by postman software. but i can't do that in flutter..
if you can help me I would be grateful is not , doesn't matter.. 
thanks for all.

**Comment by minhcasi** [comment]
@nahuelbourdichon - you could refer to some POST function from the `woo_commerce.dart` file to update the meta_data. 

<img width="955" alt="Screen Shot 2020-08-03 at 11 27 01" src="https://user-images.githubusercontent.com/1459805/89145893-42b46100-d57c-11ea-8a11-dc74b6b3055a.png">

Or using this document could be help https://developer.wordpress.org/rest-api/extending-the-rest-api/adding-rest-api-support-for-custom-content-types/

**Comment by minhcasi** [comment]
Let us know if you have any question 😊
