### ISSUE TITLE
[Woocommerce] Dynamic and multi-currency shipping cost

### ISSUE THREAD

**Issue by gantavya1** [inspireui/support#4434]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
# [Woocommerce] Dynamic and multi-currency shipping cost

If I define my shipping cost **dynamic** i.e. based on product quantity then returns the same in REST api (wp-json/wc/v2/shipping/zones/6/methods) and fultter parse the same as *zero*.

eg: If I define my shipping cost as *60 * [qty]*, Then api also return the same  literal as response and fultter code is not able to parse it.

Also I have enabled **multi-currency** and installed **WPML** plugin as well, but as shipping cost is returning as it is, then it is showing in primary currency only. Kindly suggest show to convert and show shipping cost in multi-currency.

+ Product & version:
Wordpress :- 5.4.1
Fluxstore WooCommerce - Flutter E-commerce Full App ;- 1.7.4

+ Flutter (or React Native) version: 
+ Testing Device/Simulator: Apple iPhone X and Xiami Note 9 Pro
+ Screenshot issues (drag the file to attach here): 1.17.5

Shipping not working in App as Intended 
![we](https://user-images.githubusercontent.com/68089232/89054639-c866bf80-d376-11ea-8680-12b5aa50b573.jpg)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhtruong315** [comment]
Hi @gantavya1 can u send me common folder and admin account to login your website via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/4434

**Comment by gantavya1** [comment]
Hello , Thanks a lot for starting review of my issue. 
I have sent you mail with the requested information. 

Let me know if any further information is required.

**Comment by minhtruong315** [comment]
Hi @gantavya1 I checked your source code. it's old version. so please update the latest version 1.7.6.

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
