### ISSUE TITLE
Completely blank screen and other link elements have gone white.

### ISSUE THREAD

**Issue by advaitn** [inspireui/support#4435]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
`As said, cannot see anything on the screen. Please refer screenshots.`
+ Product & version:
`Fluxstore WooCommerce - Flutter E-commerce Full App version 1.7.6 – 12 Jul 2020`
+ Flutter (or React Native) version: 
`Flutter`
+ Testing Device/Simulator: 
`Xiaomi POCO F1 / Asus Zenfone Max Pro M1/ OnePlus 7T`
+ Screenshot issues (drag the file to attach here): 
![WhatsApp Image 2020-07-26 at 3 01 51 PM](https://user-images.githubusercontent.com/29460487/89055808-aff7a480-d378-11ea-9fa8-35ba4fd946df.jpeg)
![ezgif-4-36d75dc9bc99](https://user-images.githubusercontent.com/29460487/89055857-c0a81a80-d378-11ea-86ce-6d444cb19746.gif)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@advaitn - could I check if you are using the default config from the demo site or integrate with your own website?

Also, try to check if the Woocommerce REST API is working fine? Please also refer to this guide https://github.com/woocommerce/woocommerce/wiki/Getting-started-with-the-REST-API

**Comment by minhcasi** [comment]
Let us know your checking - thank you! 😊

**Comment by advaitn** [comment]
> @advaitn - could I check if you are using the default config from the demo site or integrate with your own website?
> 
> Also, try to check if the Woocommerce REST API is working fine? Please also refer to this guide https://github.com/woocommerce/woocommerce/wiki/Getting-started-with-the-REST-API
> 
> > <img alt="" width="48" src="https://avatars3.githubusercontent.com/u/473596?s=400&amp;v=4"><img alt="" height="14" src="https://camo.githubusercontent.com/040b5519c6d1891329f5f6d3e511003657131cf2/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[woocommerce/woocommerce](https://github.com/woocommerce/woocommerce)**An open source eCommerce plugin for WordPress. Contribute to woocommerce/woocommerce development by creating an account on GitHub.

Integrated with own. And REST is working fine.

**Comment by minhcasi** [comment]
@advaitn - pls help to give a try with our pre-config site here - https://docs.inspireui.com/fluxstore/woocommerce-setup/#1-website-integration
