### ISSUE TITLE
kindly re-open  #4328. or reply

### ISSUE THREAD

**Issue by miskayapp** [inspireui/support#4436]
there is a bug in your app when using variations, as hideoutofstock is set to true on the app and wordpress, but its still displaying outofstock variations on the app

**Comment by minhcasi** [comment]
Duplicate of #4328 - this issue could not reproduce please double check your data

@miskayapp - pls note you still have own us the payment, you have requested as urgent request to support resolve the release issue but not send the payment, it is 2 weeks 😷 - thanks

**Comment by tskmark** [comment]
> Duplicate of #4328 - this issue could not reproduce please double check your data
> 
> @miskayapp - pls note you still have own us the payment, you have requested as urgent request to support resolve the release issue but not send the payment, it is 2 weeks 😷 - thanks

noted

**Comment by tskmark** [comment]
I have checked everything, and its all set to hideoutofstock, but your app
still shows out of stock products, i dont think your app works with
variations
