### ISSUE TITLE
unable to build apk

### ISSUE THREAD

**Issue by tayyabtex** [inspireui/support#4437]
**_Step 1 (require): describe detail issues & screenshots_*I bought flux store shopify and integrate it with my shopify sucessfully but when i tried to generate apk file it shows error i though that i did something wrong and i downloaded again the tempalte and didnt change anything and tried to build apk it shows same error attaching screenshot i contacted local developer they said there are some issues in code

Please check And fix it
even if some fees required i am ready to pay but i want this app to be working
i can show it on Team viewer also any time

<img width="1680" alt="Screen Shot 2020-08-01 at 3 41 30 AM" src="https://user-images.githubusercontent.com/21078970/89086928-d4b93f80-d3ab-11ea-8614-f19d9992f9b6.png">

<img width="1680" alt="Screen Shot 2020-07-31 at 10 04 25 PM" src="https://user-images.githubusercontent.com/21078970/89086877-ab98af00-d3ab-11ea-9c03-95fea8a6c0a6.png">
<img width="1680" alt="Screen Shot 2020-07-31 at 10 04 48 PM" src="https://user-images.githubusercontent.com/21078970/89086891-b5baad80-d3ab-11ea-89f1-821596db0344.png">
<img width="1680" alt="Screen Shot 2020-08-01 at 3 41 30 AM" src="https://user-images.githubusercontent.com/21078970/89086907-bc492500-d3ab-11ea-9288-8ecc1f47c9de.png">
<img width="1680" alt="Screen Shot 2020-07-31 at 10 04 25 PM" src="https://user-images.githubusercontent.com/21078970/89086920-cd923180-d3ab-11ea-94cd-6d7dd2b5ab55.png">
<img width="1680" alt="Screen Shot 2020-07-31 at 10 04 48 PM" src="https://user-images.githubusercontent.com/21078970/89086926-d420a900-d3ab-11ea-846e-069ad4d52d41.png">

*
+ Detail Issues: 
+ Product & version: Flux store shopify
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

[59938518-fluxstore-shopify-the-best-flutter-ecommerce-app-license.pdf](https://github.com/inspireui/support/files/5009329/59938518-fluxstore-shopify-the-best-flutter-ecommerce-app-license.pdf)

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@tayyabtex - could you help to try this solution to fix the Android-R issue - https://github.com/inspireui/support/issues/3708#issuecomment-645109445

**Comment by tayyabtex** [comment]
I tried it its not working
![17A7CF9D-70C7-4A26-9FD2-A824ED48D093](https://user-images.githubusercontent.com/21078970

**Comment by tayyabtex** [comment]
I tried it still not working screenshot attached
<img width="1680" alt="9D5EBC3A-5ED6-49B0-90E4-8F154FE1A679" src="https://user-images.githubusercontent.com/21078970/89099732-d5cd8980-d40a-11ea-9314-ab304494e3bd.png">

**Comment by tayyabtex** [comment]
I tried it still not working screenshot attached
<img width="1680" alt="7DA198EB-1673-408D-A473-6E6683756605" src="https://user-images.githubusercontent.com/21078970/89101091-7d9c8480-d416-11ea-9841-42d8938e7e62.png">

**Comment by minhcasi** [comment]
@tayyabtex - could you give a try with latest release on gitlab? If you don't have the account please submit to http://gitlab.inspireui.com/ - thank you!

**Comment by tayyabtex** [comment]
Sorry I don’t understand
Please guide clearly

Sent from my iPhone

On 02-Aug-2020, at 7:12 AM, Minh Pham <notifications@github.com> wrote:

﻿

@tayyabtex<https://github.com/tayyabtex> - could you give a try with latest release on gitlab? If you don't have the account please submit to http://gitlab.inspireui.com/ - thank you!

Google Forms - create and analyze surveys, for free.<http://gitlab.inspireui.com/>
Create a new survey on your own or with others at the same time. Choose from a variety of survey types and analyze results in Google Forms. Free from Google.

**Comment by tayyabtex** [comment]
i Created account on Gitlab and submit all details in form waiting for quick response

**Comment by minhcasi** [comment]
it's updated - pls check the invitation from your inbox - thank you!

**Comment by tayyabtex** [comment]
i Check and downloaded folder from there and tried to rebuild apk but new error showed up please check and guide me 
<img width="1680" alt="Screen Shot 2020-08-03 at 8 08 59 PM" src="https://user-images.githubusercontent.com/21078970/89197495-3c96a280-d5c5-11ea-9aa2-fa37b8a115b8.png">

**Comment by minhcasi** [comment]
@tayyabtex - could you send us your result by running this script `flutter doctor`?

**Comment by tayyabtex** [comment]
here is screenshot of flutter doctor

<img width="1680" alt="Screen Shot 2020-08-04 at 2 08 24 PM" src="https://user-images.githubusercontent.com/21078970/89275699-0c4e1300-d65c-11ea-8b26-50145c07dc18.png">

**Comment by minhcasi** [comment]
@tayyabtex - it is setting correctly 

We suggest giving a try to run a project by Android Studio, on VS Code you need to run the script to build the project. 

Make sure your could run this Test Drive before using the Fluxstore - https://flutter.dev/docs/get-started/test-drive?tab=vscode (this is first required user guide to help you set up the flutter correctly) - thanks

**Comment by tayyabtex** [comment]
i tried it on android studio
if we create new app and start flutter run it works fine with blank app ( attaching screenshot )
but when we open fluxstore shopify project and start flutter run command it gaves error attaching screen shot
<img width="1680" alt="Screen Shot 2020-08-05 at 11 23 25 AM" src="https://user-images.githubusercontent.com/21078970/89379179-c0a87180-d70e-11ea-8f03-f0e3e75db748.png">
<img width="1680" alt="Screen Shot 2020-08-05 at 11 25 43 AM" src="https://user-images.githubusercontent.com/21078970/89379183-c1d99e80-d70e-11ea-8f08-0250b4f5d56e.png">

**Comment by minhcasi** [comment]
@tayyabtex - try to run `flutter pub get` to update the library first - You could try to click the green-play button as well.

Also, have a look to this video https://www.youtube.com/watch?v=ReAUZDIgh2I

**Comment by tayyabtex** [comment]
Dear 
Flutter is perfectly installed on my system and i tried all the commands and all the ways
But its not working
If you Dont believe i can give you team viewer of anydesk iD you can check it yourself
Its now about 2 weeks i am trying but still its not working
And today you are saying me that install flutter
Dont you watch previous screenshot where i run Flutter doctor command
Please make things Easy
Its irritating now

**Comment by minhcasi** [comment]
Hi Dear, 
Please try your best with the following solutions:

- Please try to run the app successfully on your simulator (with the fresh download package) before building final APK by using this guide - https://docs.inspireui.com/fluxstore/delivery-android/ (as build final APK will require to change the bundle id). If you have success install Flutter, then the installing Fluxstore is easy by open Android Studio and run the Green-Play button (try to run `flutter clean` to clear your caching)

- Refer to these videos support for the installing:
1. https://docs.inspireui.com/fluxstore/fluxstore-shopify/
2. basic Flutter install on this link https://docs.inspireui.com/fluxstore/getting-started/

- It is possible to process refund if you could not use the product so far, thank you for your time!

**Comment by tayyabtex** [comment]
i recheck all things reinstalled flutter redo every thing but still i am unable to build apk this app is not working for me 
please process my refund as i am unable to use it
thanks

**Comment by minhcasi** [comment]
@tayyabtex - you could refund on [this link ](https://help.market.envato.com/hc/en-us/articles/202821460-Can-I-Get-A-Refund-)

Thank you for your time

**Comment by tayyabtex** [comment]
i submitted refund request but no reply
