### ISSUE TITLE
Try to update Fluxstore Woocommerce Multi Stores and get this error type 'List<dynamic>' is not a subtype of type 'List<Product>'

### ISSUE THREAD

**Issue by gfunkerwin** [inspireui/support#4439]
Hi,

I've got my app live online and made some changes to upgrade the app, when I built it although successfully, I got this message

type 'List<dynamic>' is not a subtype of type 'List<Product>'

And the layout that I made in file config_en.json does not match as the one on phone nor on AVD even though I did Flutter Clean, Pub Get, etc.

Made the layout using FluxBuilder

Need help, thank you

**Comment by minhcasi** [comment]
@gfunkerwin - could you share some screenshot issue and send the project files to inspireui.team@gmail.com - we will help to investigate the issue

Please share your live online app here, we will give some good rating :)

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
