### ISSUE TITLE
[Mstore] Bug more than one CustomPages on Left Menu Side Drawer

### ISSUE THREAD

**Issue by juraganwp** [inspireui/support#444]
How to replicate : Create more than one CustomPages to url in config, when user open the left menu side drawer and click the first CustomPages with url it loads successfully but when user open the left menu side drawer again and immediately click the second CustomPages it will not load the new url.

Its not happen when theres two CustomPages on profile page tab.

**Comment by luyx2412** [comment]
Hi @juraganwp Please provide your purchase code.

Thanks
