### ISSUE TITLE
Sale Price is Null

### ISSUE THREAD

**Issue by devienguilde** [inspireui/support#4440]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 1. Hello there, i want user to create Regular Price only, and Sales price is optional how do i solved this
2. I want to change background image on Settings page, and Color Background (Please check Screenshoot)
3. and finally how do i change Text on slider Menu? or add Custom page blank page, or webview page?
+ Product & version: V1.6
+ Flutter (or React Native) version: Lastest 
+ Testing Device/Simulator: Pixel3a
+ Screenshot issues (drag the file to attach here): 
![Sale](https://user-images.githubusercontent.com/50396726/89102502-1988b900-d434-11ea-8cc5-88b4b6f51b62.PNG)
![image](https://user-images.githubusercontent.com/50396726/89102511-36bd8780-d434-11ea-874c-d95b79bfdd6d.png)
![image](https://user-images.githubusercontent.com/50396726/89102512-44730d00-d434-11ea-8b28-0239877e1db8.png)
![image](https://user-images.githubusercontent.com/50396726/89102531-7d12e680-d434-11ea-894e-3b481bc23daa.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@devienguilde - sorry this is the small UX issue, we will fix it on next release - thank you!

**Comment by devienguilde** [comment]
Hey what about Create feature one, I want the user to create Regular Price only, and Sales price is optional

**Comment by devienguilde** [comment]
another bug , it's loading forever using payment with COD WCFM
![image](https://user-images.githubusercontent.com/50396726/89117582-0d027000-d4c9-11ea-8641-32f998daa0bd.png)

**Comment by devienguilde** [comment]
Now i got an issue after updatating to 1.7 .6, product didn't show but on category and store it's show up

**Comment by minhtruong315** [comment]
@devienguilde can u send me common folder via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/4440

**Comment by devienguilde** [comment]
> truong@inspireui.com

sended

**Comment by devienguilde** [comment]
So how to solved it?, the sale price and not showing product

**Comment by minhtruong315** [comment]
I'm checking @devienguilde

**Comment by minhtruong315** [comment]
@devienguilde You need to verify purchase code to use MStore Api plugin
https://bibcart.id/wp-admin/admin.php?page=mstore-plugin

**Comment by minhtruong315** [comment]
@devienguilde Sales price is not required when create the product in version 1.7.6. I think you're using old version. please download the latest version on codecanyon and check again your issues.
Thanks

**Comment by devienguilde** [comment]
![image](https://user-images.githubusercontent.com/50396726/89888670-85b8a900-dbfa-11ea-9a11-869473510aa4.png)
it's active now, but still no product show

**Comment by devienguilde** [comment]
it's said error in range Error(index) invalid value

**Comment by minhtruong315** [comment]
@devienguilde can u take me screenshot in app?

**Comment by devienguilde** [comment]
Nevermind it's work when i move to pc, but i got this problem on new Shop Orders by WCFM
![image](https://user-images.githubusercontent.com/50396726/89959344-67889280-dc66-11ea-83af-53e916a8c793.png)

**Comment by minhtruong315** [comment]
@devienguilde I fixed shop orders on our source code. it will be available in next release.

**Comment by devienguilde** [comment]
when it'll release sir?

**Comment by minhtruong315** [comment]
@devienguilde I think today. but we uploaded version 1.7.7 to gitlab. if you want to check it, you can request the permission to this email: support@inspireui.com

**Comment by minhtruong315** [comment]
@devienguilde we released Fluxstore MV 1.7.7. it fixed shop orders. please try this version and remember to update MStore Api plugin as well

**Comment by devienguilde** [comment]
<img width="1111" alt="image" src="https://user-images.githubusercontent.com/50396726/90200477-2a590780-de02-11ea-91b1-d15c93edbd26.png">
just try downliad new version and pub get not work?
