### ISSUE TITLE
unable to login to app 

### ISSUE THREAD

**Issue by nomicool** [inspireui/support#4441]
when someone register to the website apps gets logged in itself when log out and try to log in it again it doesn't log in shows the error. even I have followed this link https://github.com/Tmeister/wp-api-jwt-auth/issues/59
![88918473-ec48d900-d282-11ea-930c-96ef9d4526f5](https://user-images.githubusercontent.com/25566185/89106176-1ba54480-d441-11ea-863f-bc6755a5e45f.png)

**Comment by minhcasi** [comment]
@nomicool - pls try to disable the debug mode from your wordpress side by update the `wp-config.php` file or you could disable the notice/warning from `php.ini`

**Comment by nomicool** [comment]
debug mode was already disabled in wp-config and there is no php.ini file created in wordpress or server

**Comment by nomicool** [comment]
Please try to respond to me today it's been long time I need to fix this

**Comment by minhcasi** [comment]
@nomicool - could you give a try to use our pre-config site that setup data for the app - https://docs.inspireui.com/fluxstore/multi-vendor/#1-website-integration - thank you!

**Comment by nomicool** [comment]
Hey I followed it one plugin was not license added I added it and point number 4 options importer I fixed that but still not log in working

**Comment by minhcasi** [comment]
@nomicool - could you share the latest screenshot issue? It is possible to send your website admin to inspireui.team@gmail.com - so that we could help with checking. - thanks

**Comment by nomicool** [comment]
Heu I have added that mail inspireui.team@gmail.com as editor to website you can check and here is the screenshot
![89106176-1ba54480-d441-11ea-863f-bc6755a5e45f](https://user-images.githubusercontent.com/25566185/89515440-84e5d880-d7f0-11ea-852b-64b1a46c3d49.png)

**Comment by nomicool** [comment]
website name marketafrique

**Comment by ahmedessid** [comment]
Same problem with social login also :(

**Comment by minhcasi** [comment]
@minhtruong315 - could you suggest this login issue, is it related to mstore-api issue?

**Comment by nomicool** [comment]
Yes, its about mstore API issue. please check I have made you admin on the website also please fix that issue.

**Comment by minhtruong315** [comment]
@nomicool can u send admin account to login your admin panel via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/4441

**Comment by nomicool** [comment]
Hey I have made you admin on this mail again

**Comment by minhtruong315** [comment]
I dont see any email. pls send me admin account info
thanks

**Comment by nomicool** [comment]
I have sent you the mail with details please check subject  is the issue id 4441

**Comment by minhtruong315** [comment]
@nomicool I dont have the permission to see your plugins. But I think you installed a plugin to verify captcha. so it can't work with MStore Api plugin. please remove that plugin and try again

**Comment by nomicool** [comment]
Great i have disabled the plugins its fixed thanks captcha plugin were causing the issue you may close now
