### ISSUE TITLE
Blog issue

### ISSUE THREAD

**Issue by giriv11** [inspireui/support#4442]
Blog articles not showing in app.
Blank white space.

Product: fluxstore woocommerce

**Comment by minhcasi** [comment]
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
@giriv11 - could you share the website url and the screenshot issue here so that we could know your detail issue - thank you!

**Comment by giriv11** [comment]
Hi,

I realized issue. 
I was using blog url example.com/blog
Problem solved after url change
New url example.com

Thanks

**Comment by giriv11** [comment]
I am getting new issue
I am not getting new order notifications via firebase fcm.
I already downloaded google-services file in project.

I am not getting notifications

How to solve this problem

**Comment by minhcasi** [comment]
@giriv11 - pls help to check this guide - https://medium.com/@inspireui/setup-firebase-cloud-messaging-fcm-push-notification-for-flutter-apps-8c767fe64e54

**Comment by minhcasi** [comment]
Let us know your checking - thanks
