### ISSUE TITLE
products not showing

### ISSUE THREAD

**Issue by goelrajiv75** [inspireui/support#4443]
My Fluxstore 1.7.6 MV not showing products on main screen..
Screen Shot:
![Pics Not Showing](https://user-images.githubusercontent.com/65877361/89117090-96f60d00-d4b8-11ea-8339-6ea01711e4d2.jpg)

but when i click any empty pic, pic is opening. pls help
screen shot
![pic open](https://user-images.githubusercontent.com/65877361/89117102-ba20bc80-d4b8-11ea-9abb-f3338c8c0e86.jpg)

product version Fluxstore MV 1.7.6
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

Proof of Purchase
![Proof](https://user-images.githubusercontent.com/65877361/89117134-09ff8380-d4b9-11ea-94d4-ee76f52e6c43.jpg)

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
We wanted to thank you for your patience during this epidemic time. We currently have reduced staff and a significantly higher volume of inquiries. We’re working as hard as we can to get to your request as soon as possible.

@minhtruong315 - please help with investigating

**Comment by minhtruong315** [comment]
Hi @goelrajiv75 can u send me common folder and config folder via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/4443

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
