### ISSUE TITLE
fluxlisting issue

### ISSUE THREAD

**Issue by nuhouse** [inspireui/support#4444]
Hello my last issue was closed before its was resolved, can this be kept open until i have the app setup & submitted to the app store as i am having difficulty setting this up, below are my comments which relate to my last ticket also:

Hello,

I am still in the process of setting this up, can you advise where i will get:

Issue 1:

  "consumerKey": "ck_58c3f8cac9c5cd7e15b2bd334824de69fc0f802f",

  "consumerSecret": "cs_c2d4411dfd71a94075158684abd6b903e0a0a1da”,

For step 3 of the setup

Issue 2:
I am linking to a current website https://esdauk.co.uk/ <https://esdauk.co.uk/> My homepage is a page & not populated with only a category

Open lib/common/config_xx.json. Under the HorizonLayout is the setting to display the homepage layout, replace the category with your own category ID (this ID can get when editting from the category in admin site):

Can you advise what step i should start at here: https://docs.inspireui.com/fluxstore/listing-directory/#step-3-setup-listing-website <https://docs.inspireui.com/fluxstore/listing-directory/#step-3-setup-listing-website>

I am linking to my wordpress theme which is not one of your listed themes but is supported as i messaged you before i purchased & you said it was supported.

My site is here: https://esdauk.co.uk/ <https://esdauk.co.uk/>

My theme is: https://mylistingtheme.com/ <https://mylistingtheme.com/>

**Comment by nuhouse** [comment]
Hello I have replied already but i need urgent help.

I am trying to link it to my wordpress website.

Can you send me the instructions on how to link it only to my wordpress website.

The instructions seem to be to link it to the demo information which i do not want to link to.

When i have all the amends done i presume i will be able to see my app in the simulator???

Which i cannot do now.

This is quite urgent as i need to get everything done by tuesday.

**Comment by minhcasi** [comment]
@nuhouse - we will investigate and let you know soon - thanks

**Comment by nuhouse** [comment]
Guys I am under a bit of pressure to get this app submitted to the app store, can you let me knowhow i configure the app soon as i need to get it to the app store ASAP.

**Comment by nuhouse** [comment]
Ok guys when i purchased this app i was advised it was easy to setup & configure.
My last issue was closed before it was resolved so i opened a new case 3 days ago & have heard nothing.
Please advise if this can be resolved today as i need to get my app to the app store Immediately.
If not also let me know & i will request a refund as this support is not good enough.
Please advise.
Thanks Andre

**Comment by philipvu30** [comment]
Hi,

Sorry for the delayed response. Your website is down at the moment so I couldn't help you.
Please inform when it's up.

Thank you.

**Comment by nuhouse** [comment]
Sorry I am using https://esdauk.com/ <https://esdauk.com/> as the main domain now.

I will look at the other domain now also.



Thanks
Andre Clarke

P: 086 1596040
E: andre@nuhouse.ie <mailto:andre@nuhouse.ie>
W: www.nuhouse.ie <http://www.nuhouse.ie/>

 <http://www.nuhouse.ie/>

 <https://www.facebook.com/nuhouse.ie/>  <https://www.linkedin.com/company/nuhouse-design> 

   

The information contained in this message and or attachments is intended only for the person or entity to which it is addressed and may contain confidential information and or privileged material. Any review, retransmission, dissemination or other use of, or taking of any action in reliance upon, this information by persons or entities other than the intended recipient is prohibited. If you received this in error please contact the sender and delete the material from any system and destroy any copies.

**Comment by philipvu30** [comment]
Hi,

Would you mind telling me what is your issue again? As I tested your website and everything seems fine to me except the images do not load. 
The image urls always redirect me to your homepage so I don't know what's wrong. Maybe one of your plugins is the cause.

Thank you.

![image](https://user-images.githubusercontent.com/54442328/89420603-23285e80-d75d-11ea-8076-94646d0baf66.png)

**Comment by nuhouse** [comment]
Ok i do not see what you are seeing, can you forward me on the files so that i can test my end??

The tutorial I was following was for some different listing store & none of the information made any sense to me.

On the plugins the Mstore API plugin is giving an error, see attached.

Do you think this could be the issue & do you know how we resolve this????

This is my first time doing an app like this but if i can get this to work i have another 2 websites that are the exact same so I will buy 2 more licenses.

If you can forward me the files you used for testing so i can test or alternatively tell me where i can get the correct tutorial please.

Thanks.




Thanks
Andre Clarke

P: 086 1596040
E: andre@nuhouse.ie <mailto:andre@nuhouse.ie>
W: www.nuhouse.ie <http://www.nuhouse.ie/>

 <http://www.nuhouse.ie/>

 <https://www.facebook.com/nuhouse.ie/>  <https://www.linkedin.com/company/nuhouse-design> 

   

The information contained in this message and or attachments is intended only for the person or entity to which it is addressed and may contain confidential information and or privileged material. Any review, retransmission, dissemination or other use of, or taking of any action in reliance upon, this information by persons or entities other than the intended recipient is prohibited. If you received this in error please contact the sender and delete the material from any system and destroy any copies.

**Comment by philipvu30** [comment]
Sure.

Please submit this [form](https://docs.google.com/forms/d/e/1FAIpQLScWOjkAJIWJ9rgb9alopfOqLsJrGKbFM5cCYj1JBfLKLsBblQ/viewform) first as I don't see your information on our database.
I'll send you the lib folder via your email when I see it's on our database.

Thank you.

**Comment by nuhouse** [comment]
Thank you philip.

I have filled in that form now.

Is the Image issue resolved or do you nee access to the website to have a look at why this is not working??



Thanks
Andre Clarke

P: 086 1596040
E: andre@nuhouse.ie <mailto:andre@nuhouse.ie>
W: www.nuhouse.ie <http://www.nuhouse.ie/>

 <http://www.nuhouse.ie/>

 <https://www.facebook.com/nuhouse.ie/>  <https://www.linkedin.com/company/nuhouse-design> 

   

The information contained in this message and or attachments is intended only for the person or entity to which it is addressed and may contain confidential information and or privileged material. Any review, retransmission, dissemination or other use of, or taking of any action in reliance upon, this information by persons or entities other than the intended recipient is prohibited. If you received this in error please contact the sender and delete the material from any system and destroy any copies.

**Comment by philipvu30** [comment]
Hi Andre,

I've already sent you the lib folder via your email. Please check.
All you have to do is replacing the category ids, images link in the config.json file.
About the image issue, it seems that you are enabling the hotlinking protection. For this issue, please contact your hosting provider for assistance.

Thank you.

**Comment by nuhouse** [comment]
Philip thanks very much for your support.

I have replaced the lib folder with what you supplied with the correct configuration.

I am getting this error in Android Studio:

**10:34	Invalid VCS root mapping
			The directory ~/App_Development/ESDA_UK is registered as a Git root, but no Git repositories were found there.
			Configure…**


Can you also advise on the plugin that will not activate on my wordpress website (Mstore API)???

See attached.

[Screenshot 2020-08-06 at 10.53.52.pdf](https://github.com/inspireui/support/files/5034104/Screenshot.2020-08-06.at.10.53.52.pdf)

In Android studio, the console seems to be looking for images here:

**flutter: Bad state: Failed to load http://andrec8.sg-host.com/wp-content/uploads/2018/08/4.2.2_dolbycinema_innovativeseating_promo4V2.jpg.**

The domain name is not correct, it should be: https://esdauk.com/

See attached.
[Screenshot 2020-08-06 at 11.06.36.pdf](https://github.com/inspireui/support/files/5034142/Screenshot.2020-08-06.at.11.06.36.pdf)

The most important part or my website is the discount image but this is not displaying in the app????

It needs to display, please advise.

[Screenshot 2020-08-06 at 11.15.11.pdf](https://github.com/inspireui/support/files/5034190/Screenshot.2020-08-06.at.11.15.11.pdf)

**Comment by philipvu30** [comment]
Hi,

> Invalid VCS root mapping

In App_Development/ESDA_UK, please remove any files that have .git extension.
>Can you also advise on the plugin that will not activate on my wordpress website (Mstore API)???

For Flux Listing, you only need these plugins:
- ListApp Manager
- Regenerate Thumbnails
- Rest API Controller (We will exclude this in the future)
- Better REST API Featured Images (We will exclude this in the future)

>The domain name is not correct, it should be: https://esdauk.com/

Please make sure your images are correct because this is the response I receive from your website
![image](https://user-images.githubusercontent.com/54442328/89528059-96d97280-d814-11ea-811d-8563c3470cc4.png)

>The most important part or my website is the discount image but this is not displaying in the app????

In your config.dart, please change this line from "featured_media": "listing_data._job_cover" to "featured_media": "listing_data._job_logo",

**Comment by nuhouse** [comment]
Philip i don’t seem to have any files with the .git extension on my machine at all????

I have my Hosting people looking into the url configuration so this should be resolved soon.

I have changed “config.dart,” file as you will see here but it still odes not show the offer, can you advise. I have shown you where i changed it & in what directory. Can you confirm that this is correct????

I have some other issues:

1. My logo is not visible in the app

2. The search bar is not the correct search bart that i have on my home page.

3. The homepage image is not appearing either.

4. I will need to change the colours of this to match my brand can you advise how i do this also?

I have 1 massive problem.

When i login on the app i am meant to see my wordpress dashboard, this is not the case as when i login i see a totally different dashboard that has no relevance to my listing website & does not have any of the features to manage your listing??????

Can you advise on this immediately.








Thanks
Andre Clarke

P: 086 1596040
E: andre@nuhouse.ie <mailto:andre@nuhouse.ie>
W: www.nuhouse.ie <http://www.nuhouse.ie/>

 <http://www.nuhouse.ie/>

 <https://www.facebook.com/nuhouse.ie/>  <https://www.linkedin.com/company/nuhouse-design> 

   

The information contained in this message and or attachments is intended only for the person or entity to which it is addressed and may contain confidential information and or privileged material. Any review, retransmission, dissemination or other use of, or taking of any action in reliance upon, this information by persons or entities other than the intended recipient is prohibited. If you received this in error please contact the sender and delete the material from any system and destroy any copies.

**Comment by nuhouse** [comment]
[Screenshot 2020-08-06 at 15.46.57.pdf](https://github.com/inspireui/support/files/5036076/Screenshot.2020-08-06.at.15.46.57.pdf)
[Screenshot 2020-08-06 at 15.56.22.pdf](https://github.com/inspireui/support/files/5036104/Screenshot.2020-08-06.at.15.56.22.pdf)
[Screenshot 2020-08-06 at 15.57.28.pdf](https://github.com/inspireui/support/files/5036107/Screenshot.2020-08-06.at.15.57.28.pdf)

**Comment by nuhouse** [comment]
Philip I have all the links fixed now.

Do you have any update on my other issues????

**Comment by philipvu30** [comment]
Hi,

It seems you have misunderstood the concept of our app. It is nothing related to My Listing theme's company. We just base on its database to develop the Flux Listing App. So if you want it to be exactly or similarly to your website, this app might be not for you.

**Comment by philipvu30** [comment]
>I have some other issues:
1. My logo is not visible in the app
2. The search bar is not the correct search bart that i have on my home page.
3. The homepage image is not appearing either.
4. I will need to change the colours of this to match my brand can you advise how i do this also?

Please provide images regarding to your issues so I can give you assistance. 

Thank you.

**Comment by nuhouse** [comment]
Ok, well i did ask was it compatible with my theme before i purchased.

I can sacrifice some elements of the website but some elements are crucial to its management.

So can i ask if it is possible to do the below:

1. Have the navigation from the website in a hamburger fashion so that customers can manage their listing page from the app.

2. Have my logo on the top of the page

3. Customise the colours

4. Have the search bar from my website on the homepage of the app.

5. When you click on a category to have the same search function as the website.


Are any of the above possible with this app????

If not how much would it cost to get them inserted into the app????

**Comment by philipvu30** [comment]
Hi Andre,

Yes it did compatible with your theme, but only the data not the design.
1. Do you mean like this?
![image](https://user-images.githubusercontent.com/54442328/89631314-d2367880-d8ca-11ea-936a-7aa148706aa5.png)
2. You can change your logo in lib/common/constants.dart. Change the kLogoImage.
3. You can change colors in lib/common/styles.dart. Or use Inspector tool to determine the widget and change it to your preferred color.
4. You need to customize it yourself.
5. Same as above.

I'm sorry but right now we don't have Customization Service.

**Comment by nuhouse** [comment]
Ok Philip so unfortunately i do not have the knowledge to be able to adjust the code to make this work.

When i purchased the theme & asked the pre-sale question it was for everything functionality & aesthetics.

The main areas of my website are the search bars on the home page & the explore page also the disocount badge as this is a discount app so it has to display the discount.

The other area would be the login area that would have to match the website also.

Are you saying this cannot be done with the app at present????

Do you have anyone who could give me an estimate on how much it would cost to get done???

If not can i request a refund on themeforest as it is within 30 days & the app although is brilliant it doesn't work for me & when i bought it i was a advised that i could get a refund within 30 days of purchase???

**Comment by philipvu30** [comment]
Hi,

Sure. Please make your request [here](https://help.market.envato.com/hc/en-us/articles/202821460-Can-I-Get-A-Refund-).

Thank you for your interest.

**Comment by nuhouse** [comment]
I have done that now Philip thanks.



Thanks
Andre Clarke

P: 086 1596040
E: andre@nuhouse.ie <mailto:andre@nuhouse.ie>
W: www.nuhouse.ie <http://www.nuhouse.ie/>

 <http://www.nuhouse.ie/>

 <https://www.facebook.com/nuhouse.ie/>  <https://www.linkedin.com/company/nuhouse-design> 

   

The information contained in this message and or attachments is intended only for the person or entity to which it is addressed and may contain confidential information and or privileged material. Any review, retransmission, dissemination or other use of, or taking of any action in reliance upon, this information by persons or entities other than the intended recipient is prohibited. If you received this in error please contact the sender and delete the material from any system and destroy any copies.
