### ISSUE TITLE
change options in Setting Screen

### ISSUE THREAD

**Issue by GNAG1993** [inspireui/support#4445]
Hello,
I'm trying to remove some options from settings screen: Language & currencies because both will be single options by default  so there is nothing to select in that. I also need to add some webview links like about us. But whenever I remove any option screen displays Data Empty instead of Removing that option and when I add some new option that is also not reflecting on settings screen.

**Comment by minhcasi** [comment]
@GNAG1993 - please try to share your setting file here so that we could have a quick look at your setting.

Please note that we will not help to support the technical question (per our support policies https://inspireui.com/support-policies), please help to consider an upgrade to Extended License if you will use the project as Commercial purpose or have more technical questions need to be supported - hope you could understand and enjoy the product 😊

**Comment by GNAG1993** [comment]
hello, that's okay, I understand your policies. i'm just asking like I need to add some new option in the settings screen just its already having about us, I need to add FAQs, Policies etc. and also need to remove some options like currencies and language.

**Comment by minhcasi** [comment]
@GNAG1993 - you could share your modified setting.dart here - we will quickly check the root cause and give solution to fix it 👍

**Comment by GNAG1993** [comment]
Hello, please check it,

[settings.zip](https://github.com/inspireui/support/files/5020274/settings.zip)

**Comment by minhcasi** [comment]
@GNAG1993 -your setting is correctly - you could add new option to this file config and make sure the faq text is ready from from the .arb file 

<img width="972" alt="Screen Shot 2020-08-05 at 12 52 27" src="https://user-images.githubusercontent.com/1459805/89376671-8775fe80-d71a-11ea-9663-cdf9bbcaacd8.png">

**Comment by GNAG1993** [comment]
I didn't understand **ready in .arb file**.

**Comment by minhcasi** [comment]
pls check this guide https://docs.inspireui.com/fluxstore/multi-language/

**Comment by GNAG1993** [comment]
okay, I got it actually I need to remove the language option and currency option and put new options instead of them. I'll give it a try today. please check my this ticket too https://github.com/inspireui/support/issues/4469 , as due to this I'm unable to release my app. Other this can be changed in an update.

**Comment by GNAG1993** [comment]
@minhcasi Okay done, thanx for the ultimate support.
@
