### ISSUE TITLE
error + product details not open +font change

### ISSUE THREAD

**Issue by mahmoodee** [inspireui/support#4447]
Hello,
I am using last version Fluxstore WooCommerce 1.7.6
I have tested my app on android studio and on real android devise
I have three issues :
1- product details not open if I click on product name .It only open if I click on product image, I want to open product details when click on product title too.
2- when I change the products layout to list layout I get error

![s1](https://user-images.githubusercontent.com/10657185/89121254-fd355c80-d4c5-11ea-9ab3-6a540bbbb231.png)

the error

![s2](https://user-images.githubusercontent.com/10657185/89121258-09211e80-d4c6-11ea-8fcd-9a4f8b539425.png)

3-
I have changed the font type for arabic language

![s6](https://user-images.githubusercontent.com/10657185/89121274-28b84700-d4c6-11ea-8dc5-d08c43f8701a.png)

It changed correctly but there are some places the font not changed like:
I can use the flutter inspector to add font to places which fonts not changed.
but How I can change font only for arabic language

![s3](https://user-images.githubusercontent.com/10657185/89121295-57362200-d4c6-11ea-8576-54602f2423fa.png)
![s4](https://user-images.githubusercontent.com/10657185/89121298-5b623f80-d4c6-11ea-8876-a5148d6ef839.png)
![s5](https://user-images.githubusercontent.com/10657185/89121299-5e5d3000-d4c6-11ea-8080-1ad57a6bff60.png)

I can use the flutter inspector to add font to places which fonts not changed.
but How I can change font only for arabic language

thank you

**Comment by simonpham** [comment]
Hi @mahmoodee,

We are so sorry for this inconvenience.
Our team has fixed these issues and it will be available in the next version (1.7.7).

If this is urgent, you can add this line to build method of `lib/widgets/product/product_list.dart`, inside `if (widget.layout == "listTile")` scope like below:

```
      widthContent = widthScreen;
```

![image](https://user-images.githubusercontent.com/8846657/89163857-73a68d00-d5a0-11ea-9dc5-6e706f43e9d6.png)



Thank you for using our products.

**Comment by mahmoodee** [comment]
thank you
what about the  first issue and third issue

**Comment by mahmoodee** [comment]
Please , I am Waiting for solving the rest of the problems.
thank you

**Comment by simonpham** [comment]
@mahmoodee We are sorry for the late reply.
For the font problem, the font you are using is `Almarai`, which only have 4 weights:

> Light 300
> Regular 400
> Bold 700
> Extra-bold 800
> https://fonts.google.com/specimen/Almarai#standard-styles

You don't need to set the fontFamily. Just need to set the `fontWeight` to one of 4 weights which supported by the font `Almarai`.

Hope this will solve your issue.

For the first issue, we will investigate on it.

**Comment by minhcasi** [comment]
@mahmoodee - let us know if you have any issues - thank you!
