### ISSUE TITLE
Onboarding Show Always

### ISSUE THREAD

**Issue by nucl123** [inspireui/support#4448]
Hi,
How can we enable onBoarding, to show always,
Have tried as per documentation :
 "OnBoardOnlyShowFirstTime": true, to false, it doesn't seem to work.

**Comment by simonpham** [comment]
Hi @nucl123,

We are so sorry for this inconvenience.
Our team has fixed this issue and it will be available in the next version (1.7.7).

If this is urgent, you can add these lines to `checkFirstScreen()` function in `lib/app_init.dart` as below:
```
    if (kAdvanceConfig['OnBoardOnlyShowFirstTime'] != true) {
      return false;
    }
```

![image](https://user-images.githubusercontent.com/8846657/89145063-bd2fb180-d579-11ea-8647-14464dce8913.png)

Thank you for using our products.
