### ISSUE TITLE
Stores not showing in WCFM

### ISSUE THREAD

**Issue by GNAG1993** [inspireui/support#4449]
Hello,
No stores are showing in latest Fluxstore MV 1.7.6 update. Only categories are showing.

**Comment by minhcasi** [comment]
@GNAG1993 - please help to check this solution https://github.com/inspireui/support/issues/4346#issuecomment-664844336

Please help us to include your questions into one open ticket, instead of open multi tickets 👍

**Comment by GNAG1993** [comment]
You know what, that's why I love you guys. **An incredible support for the awesome products. Thanks a lot.**
