### ISSUE TITLE
[MStore Multi Vendor] I can not install CeBuilder

### ISSUE THREAD

**Issue by almansori1** [inspireui/support#445]
- Product: MStore Multi-Vendor
 - Your Purchased Code: [I can't fund the Purchased Code]

**Describe the issues**
I can not install CeBuilder in your page it has an error link"This site can’t be reached"

**Comment by thangvo9x** [comment]
I can't see your purchase code, please input again. 
Download CeBuilder, https://inspireui.com/

**Comment by minhcasi** [comment]
https://help.market.envato.com/hc/en-us/articles/202822600-Where-Is-My-Purchase-Code-

**Comment by almansori1** [comment]
I found it.
Item Purchase Code: 373d17f2-6bb4-4e9e-83b5-532cd649e762
