### ISSUE TITLE
App crashes on startup. App keep stopping. Version 1.7.6

### ISSUE THREAD

**Issue by fasttend** [inspireui/support#4450]
App crashes on startup. App keep stopping. Version 1.7.6

To verify purchase licence please see previous ticket #4267

**Comment by minhcasi** [comment]
Crashing issue could cause by your bundle id, did you change new bundle or keep the default demo? Please double-check this guide https://docs.inspireui.com/fluxstore/delivery-android/#12-change-the-app-bundle-id-package-name

**Comment by fasttend** [comment]
Hi @minhcasi I have checked that all details are correct. But the same problem occurred.

**Comment by minhcasi** [comment]
@fasttend - could you zip the `android` folder and share here, i will check your bundle id to see if all correct or not

**Comment by fasttend** [comment]
[android.zip](https://github.com/inspireui/support/files/5022446/android.zip)

**Comment by minhcasi** [comment]
Also try to rename this bundle id on this file to see if it could be fix?

<img width="1014" alt="Screen Shot 2020-08-05 at 12 47 51" src="https://user-images.githubusercontent.com/1459805/89376415-e1c28f80-d719-11ea-961e-4b36fb4fccef.png">

You could try to enable the logcat from android studio and monitor the detail log issues

**Comment by fasttend** [comment]
Hi @minhcasi. I have changed the bundle id on the above file but the same error coming. Debug app is working fine but the problem arising in the apk or app bundle.

**Comment by minhcasi** [comment]
@fasttend - could i know what the device you are using for testing. 

Please note that Flutter app will crash on some Mi and Huawei devices

**Comment by fasttend** [comment]
Hi,
I am using Mi and OPPO mobiles for testing.

Regards

Tusshar Bastia

________________________________

**Comment by fasttend** [comment]
Hi,
Please find the error summary screenshot of the Mi device.

[Image]
________________________________

**Comment by minhcasi** [comment]
@fasttend - pls share the screenshot and error again, we could not read it - thank you!

Btw, there are a lot of rash issue on Mi phone with the flutter core library - you could refer to this link https://github.com/flutter/flutter/search?q=redmi+crash+android&unscoped_q=redmi+crash+android&type=Issues

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
