### ISSUE TITLE
Issues with Razorpay Payment

### ISSUE THREAD

**Issue by RatnApp** [inspireui/support#4451]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 

   1. I know there is build issue for RazorPay plugin for iOS, however, as we are targetting only for android, could you enable this 
     for android atleast?

        I tried commenting "payment_razopay.dart" but from there we get into multiple other issues such as order_model.dart is 
        not defined etc. Coudl you provide a stream lined file without any issues, if we have to re-use "payment_razopay.dart"  
        please?

    2. With navigating to web version of the store, user is again navigated to login page, is there any easy way to by pass this? as 
    user is already authenticated in the app, we should be able to use the earlier token and authenticate ?

    3. Can login with SMS be enabled for Shopify fluxstore?

+ Product & version:
    **Product**: Shopify-Fluxstore

    **Version**: **1.7.5**

+ Flutter (or React Native) version: 
    **Flutter version**: 1.21.0-5.0.pre

+ Testing Device/Simulator: 
     Testing on Device

+ Screenshot issues (drag the file to attach here): 

    Known issue, not required

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by RatnApp** [comment]
Hi Team,

Submitted purchase verification documents on :
http://verify.inspireui.com

Thanks.

**Comment by minhcasi** [comment]
Sorry, the Razorpay and SMS login is not available for the Fluxstore Shopify due to the limit of Shopify API.

Please help to share the screenshot for the second question as we are not quite clear :)

**Comment by RatnApp** [comment]
Hi minhcasi,
Please see below details:

1. Could you share your Razorpay integration recommendation (possibly a blog) to integrate without impacting any future upgrades. Is there any easy .dart file drops to enable this easily?
2. For second query, when I enable setting as "  "EnableOnePageCheckout": true,", when clicked on "CHECKOUT" (from Cart screen), app navigates to webpage version of the store and asks for login, as shown in the attached screenshot, coudl you recommend any steps to bypass this authentication?

![Screenshot_2020-08-03-14-56-38-428_com inspireui fluxstore](https://user-images.githubusercontent.com/69118014/89191396-62568400-d592-11ea-82d4-990c27dbf439.png)
![Screenshot_2020-08-03-14-56-49-150_com inspireui fluxstore](https://user-images.githubusercontent.com/69118014/89191397-62ef1a80-d592-11ea-923f-abb8883391b3.png)
Thanks.

**Comment by RatnApp** [comment]
Also, any recommendation around SMS login will be really helpfull.

Thanks

**Comment by minhcasi** [comment]
@luyx2412 - please help to provide solution to show the Payment webview - than kyou!

**Comment by RatnApp** [comment]
@luyx2412 - Any luck with teh request.

**Comment by RatnApp** [comment]
Hi @minhcasi @luyx2412  Any updates on the issue please.

**Comment by luyx2412** [comment]
Hi @RatnApp Please fill the form and provide the Config file. I will investigate about the issue.

Thanks

**Comment by RatnApp** [comment]
> Hi @RatnApp Please fill the form and provide the Config file. I will investigate about the issue.
> 
> Thanks

@luyx2412 - Could you please let me know where to upload the config file and do you just need config file in below location and any other files are required?
**location**: ./lib/config/config_en.json

Please note that I have already verified the purchase, do you want me to verify again?

Also, what is the license around soem of teh image / icon assets which are pre-packaged with teh source, can we use them in release apk uploaded togoogle playstore?

Thanks.

**Comment by RatnApp** [comment]
@luyx2412 - Could you please let me know above queries, I will upload ASAP

**Comment by RatnApp** [comment]
@luyx2412 - Hi, assuming you are looking for lib folder, I have resubmitted the verification form with lib folder, could you please verify and let me know, thanks.

**Comment by RatnApp** [comment]
Hi @minhcasi @luyx2412 , any updates on this please, please let me know if you need more details from me.

**Comment by luyx2412** [comment]
Hi @RatnApp Sorry about reply you late. It happen some issues, you can read this article about it https://community.shopify.com/c/Shopify-APIs-SDKs/Storefront-Weburl-Checkout-Logged-In/td-p/574274. We are investigating and fix it soon.

Thanks
