### ISSUE TITLE
MV-App always send me to web checkout form after choosing payment method, instead of app native

### ISSUE THREAD

**Issue by mauriciozuniga** [inspireui/support#4452]
+ Detail Issues: 
When the user checkout on the app, it always send him to web Checkout, it doesn't matter what value do I configure on payments.dart / NativeOnePageCheckout.
I had tried all possible configurations and  have always the same result, after choosing payment method (cash/stripe or PayPal), it send me to web to my checkout form.

  "EnableOnePageCheckout": false,
  "NativeOnePageCheckout": true,

+ Product & version:
FluxStore Multivendor 1.7.6

+ Flutter (or React Native) version: 
Flutter 1.17.1

+ Testing Device/Simulator: 
iOS multiple versions (simulator and real device)

+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@mauriciozuniga - the final step of NativeOnePageCheckout (true or false) will be open the Webview to delegate the final checkout to the website so that it could support the multi-payment - same as on your website

So this is not a bug, let us know if you have any questions.

**Comment by mauriciozuniga** [comment]
Thanks Minhcasi, so, currently, the app doesn't support the payment (even for 1 vendor only) with native screens? I will always need to send to website to complete a purchase? Or do I need to remove something to allow "all-native" experience.

Thanks!

**Comment by mauriciozuniga** [comment]
Also, sorry, I include another issue, please let me know if it can be included here or do I need to create a new one....

I have several vendors register on mi store (like 25 already active), but on the app, on the "Stores" tab, it only show me 10 of them... Do you know what could it be? their prorducts are correctly shown on the products category section, but the vendors are not shown on Stores list.

Thnks

**Comment by minhcasi** [comment]
@minhtruong315 - please help to check the vendor list issue - thank you!

**Comment by minhtruong315** [comment]
Hi @mauriciozuniga Fluxstore MV supports paypal native payment. other payment must be used webview to checkout.
if you want to enable paypal native. you need to check enabled:true and paymentMethodId must be same in your website
```
const PaypalConfig = {
  "clientId":
      "ASlpjFreiGp3gggRKo6YzXMyGM6-NwndBAQ707k6z3-WkSSMTPDfEFmNmky6dBX00lik8wKdToWiJj5w",
  "secret":
      "ECbFREri7NFj64FI_9WzS6A0Az2DqNLrVokBo0ZBu4enHZKMKOvX45v9Y1NBPKFr6QJv2KaSp5vk5A1G",
  "production": false,
  "paymentMethodId": "paypal",
  "enabled": true,
  "returnUrl": "http://return.example.com",
  "cancelUrl": "http://cancel.example.com",
};
```

**Comment by minhtruong315** [comment]
@mauriciozuniga let me know the result. Thanks

**Comment by mauriciozuniga** [comment]
I use stripe, so I will keep web view for now. The only other issue remaining so far is the vendor list, that only shows 10 vendors and I have 25 active....

Also, do you know how can I change the menu icon?

Thanks!

**Comment by mauriciozuniga** [comment]
Ok, I already found how to change the menu icon, thanks! only the vendor list issue remaining!

**Comment by minhtruong315** [comment]
Can u send me common/config.dart?

**Comment by mauriciozuniga** [comment]
Sure! Done... I just sent it to you to your inspireui.com email!  Please let me know if you get it or if I need to upload here... Also, I uploaded to this ticket when I opened it.

**Comment by minhtruong315** [comment]
Hi @mauriciozuniga replace vendor/store/store_screen.dart and vendor/store/store_model.dart and try again
[Archive.zip](https://github.com/inspireui/support/files/5025636/Archive.zip)

**Comment by mauriciozuniga** [comment]
Thanks!!

It seems it works perfectly!
Cheers!
