### ISSUE TITLE
Deceptive Ads policy

### ISSUE THREAD

**Issue by swapnildesai5** [inspireui/support#4453]
Issue details

We found an issue in the following area(s):
In-app experience: Please see attached screenshot com.vistatech.vistamallflux-InAppExperience-36.png

![com vistatech vistamallflux-InAppExperience-36 (1)](https://user-images.githubusercontent.com/37268415/89132791-6bf2d400-d51f-11ea-8bb6-ae23b7fb6cbf.png)

**Comment by swapnildesai5** [comment]
Playstore Publish Issue how to change the rate this app link to my app

**Comment by minhcasi** [comment]
@swapnildesai5 - you could fix the update this setting to your own bundle id

<img width="813" alt="Screen Shot 2020-08-03 at 09 30 25" src="https://user-images.githubusercontent.com/1459805/89140494-f95c1580-d56b-11ea-870a-a0557393b901.png">

**Comment by minhcasi** [comment]
Let us know your checking - thank you!
