### ISSUE TITLE
Shop orders not displaying rather its showing shop list

### ISSUE THREAD

**Issue by kenngigz** [inspireui/support#4454]
![IMG_20200803_082013_283](https://user-images.githubusercontent.com/57593885/89148366-4a670c00-d562-11ea-9957-e72d309cc10c.jpg)
![Screenshot_2020-08-03-08-19-33](https://user-images.githubusercontent.com/57593885/89148347-37ecd280-d562-11ea-8d75-08266aaa68a4.png)

**Comment by kenngigz** [comment]
Hi ! Its been a while no updates

**Comment by minhcasi** [comment]
@tgloc96 - pls help to suggest this issue

**Comment by devienguilde** [comment]
Follow

**Comment by kenngigz** [comment]
Any updates. Its been a while now.

**Comment by minhtruong315** [comment]
@kenngigz I'm checking and let you know today

**Comment by kenngigz** [comment]
Waiting.

**Comment by minhtruong315** [comment]
I updated this functions for dokan already. I'm working on wcfm then you can check it in next release

**Comment by devienguilde** [comment]
So 1.7.6 not support wcfm?

**Comment by eraldix** [comment]
any news on this issue?

**Comment by minhtruong315** [comment]
@kenngigz We released Fluxstore MV 1.7.7. it fixed shop orders. please try on that version.
