### ISSUE TITLE
Woocommerce data not showing on apps 

### ISSUE THREAD

**Issue by GreenShopBD** [inspireui/support#4456]
Hello all 
We have submitted all the prof at our last ticket but unfortunately it’s closed for late replay here is the last ticket link https://github.com/inspireui/support/issues/4383

@minhcasi  at last time you give us some instructions and we have done it all 
Now here is new issue pls check 
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve com.google.firebase:firebase-iid:[20.0.1].
     Required by:
         project :app > com.google.firebase:firebase-messaging:20.0.1
      > Failed to list versions for com.google.firebase:firebase-iid.
         > Unable to load Maven meta-data from https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-iid/maven-metadata.xml.
            > org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.

Thank you 
![3ADAAB3E-379D-4F26-982E-B6BA3681D368](https://user-images.githubusercontent.com/68589110/89165107-e8c29400-d599-11ea-9614-86581088496d.jpeg)

**Comment by GreenShopBD** [comment]
![EE3F0E47-8A3C-497C-BD55-4A9281FBCF5B](https://user-images.githubusercontent.com/68589110/89165061-d21c3d00-d599-11ea-925c-817c7f2f2af1.jpeg)

**Comment by minhcasi** [comment]
@GreenShopBD - please try to keep the original grade file from download package, don't try to upgrade the library that could break the build. Also, make sure to clean up the flutter cache from Android Studio and using the latest `stable` version - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

**Comment by dreamtouchapp** [comment]
We don't change grade file .and we have done almost everything from this link https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1
please suggest us if any other solution you have . Thank you

**Comment by GreenShopBD** [comment]
Hello @minhcasi  Till No any Replay from you, How do we fixed the issue, where we have checked all the following solution link " https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1"  you sending us.
please help to solving the issue. we are still not able to run the code, we are getting too late, pls help us. 
thank you

**Comment by minhcasi** [comment]
@GreenShopBD - you could run `flutter clean` and share the source to inspireui.team@gmail.com - we will help to check the issue - thanks

**Comment by GreenShopBD** [comment]
@minhcasi  Thank you 
pls wait we will send you the source to the email address 

Thanks

**Comment by GreenShopBD** [comment]
@minhcasi 
Please check your ( inspireui.team@gmail.com)  email, we have shared the source 
thank you

**Comment by minhcasi** [comment]
@simonpham - pls help to investigate this issue

**Comment by GreenShopBD** [comment]
Hello @simonpham 
Pls help us 
Thank you

**Comment by GreenShopBD** [comment]
@minhcasi 
@simonpham  
Hello all, do we have any update? 
Thank you

**Comment by GreenShopBD** [comment]
Hello 
@minhcasi  hope you are well, from last day we did not have any update from you? is the issue investigation is on going or not ?
Seeking your replay 
Thank you

**Comment by minhcasi** [comment]
@GreenShopBD - we are investigating your issue and will get back ASAP - thanks

**Comment by GreenShopBD** [comment]
okay than you

**Comment by GreenShopBD** [comment]
Hello @minhcasi 
Do we have any update? 
It’s long time no any replay

**Comment by minhcasi** [comment]
@GreenShopBD - there was some issue with the latest flutter `1.20.1` that cause the build grade issue, we will update new patching on 1-2 days - thank you!

**Comment by GreenShopBD** [comment]
Thank you @minhcasi 
Please do your best.

Thank you

**Comment by GreenShopBD** [comment]
Hello 
@minhcasi 
any update ?
thank you

**Comment by minhcasi** [comment]
@GreenShopBD - the latest version is ready for download, please keep the update and let us know if you have any question

**Comment by GreenShopBD** [comment]
Hello 
@minhcasi  
Yes we have already notified from envato, and we are trying and working on this we will let you know the results  as soon as possible. 

Thank you

**Comment by minhcasi** [comment]
Let us know if you have any question 👍
