### ISSUE TITLE
Product gallery not showing

### ISSUE THREAD

**Issue by bvisible** [inspireui/support#4458]
Hello,

I'm using fluxstore linked to woocommerce and I've products with images gallery but in the app, when I'm on a product page, I only see the featured image.

In lib/models/product/product.dart the printed value of images list from Product.fromJson is the featured image and there's nothing more

**Comment by bvisible** [comment]
Ok so basically, I found where is the problem. We have the default language ID which has the gallery images and the translated ID's doesn't have them. Is there an easy way to get the images from the default language ID?

**Comment by devienguilde** [comment]
how u solved it did u use wcfm?

**Comment by minhcasi** [comment]
@bvisible 

Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
@bvisible - please try to config this value to 0 or 1 - we have limited the minimum number to show the image galleries 

<img width="740" alt="Screen Shot 2020-08-05 at 11 19 34" src="https://user-images.githubusercontent.com/1459805/89371432-8c808100-d70d-11ea-891b-a0b7f7caa2fc.png">

**Comment by bvisible** [comment]
> @bvisible - please try to config this value to 0 or 1 - we have limited the minimum number to show the image galleries
> 
> <img alt="Screen Shot 2020-08-05 at 11 19 34" width="740" src="https://user-images.githubusercontent.com/1459805/89371432-8c808100-d70d-11ea-891b-a0b7f7caa2fc.png">

Thank you for your answer. Unfortunately it still doesn't work. The main issue is this one :
We have multi-language website. The woocommerce products are translated too. For example a product in the main website language has the ID 145 and in another language it will have 2041 for example. Since the gallery images are stored in the ID 145 and not 2041, when we are not it the main language, the gallery cannot be show as the translated product doesn't have them. Is there anyway to tell the app to search images from the main product ID?

**Comment by minhcasi** [comment]
@bvisible - could i know if you are using WCFM plugin?

PLease share the admin login to inspireui.team@gmail.com so that we could help with checking this case - thanks

**Comment by minhcasi** [comment]
Let us know your checking - thanks

**Comment by bvisible** [comment]
Hello,

I partially solved the problem. In the functions fetchProductsLayout, fetchProductsByCategory and searchProducts from lib/services/woo_commerce.dart

after this calls : var response = await wcApi.getAsync(endPoint);

I added:
      if(lang != 'fr-ch') {
        for (var i = 0; i < response.length; i++) {
          String originalId = (response[i]["translations"]["fr-ch"]);
          String endpointOriginal = "products/$originalId";
          var originalResponse = await wcApi.getAsync(endpointOriginal);
          response[i]["images"] = originalResponse["images"];
        }
      }

But now it seems like there's quite a lot of requests and the app crash because of memory issue

**Comment by minhcasi** [comment]
@bvisible - could i know what is the device you are using for testing?

Please note that there are some know crash issue on some Android Mi device with the flutter core library - https://github.com/flutter/flutter/search?q=redmi+crash+android&unscoped_q=redmi+crash+android&type=Issues

**Comment by bvisible** [comment]
@minhcasi On IOS 13.6. I haven't tested Android yet.

**Comment by bvisible** [comment]
@minhcasi Hello, I've seen that you released the version 1.7.7
Is there any changes involving this topic?

**Comment by minhcasi** [comment]
@bvisible - yes, please give a try to update the latest version as we have fixed a lot of bugs
