### ISSUE TITLE
[MStore] When I click Shop tab but after some seconds I got error

### ISSUE THREAD

**Issue by mkashifrazzaq11** [inspireui/support#446]
**Required Info (please complete the following information):**
 - Product: [e.g. MStore, ListApp]
f8d919b7-3308-4d8c-a454-6b2685fbae9c
(we may not reply if you are not our customer)

**Describe the bug**

When I click shop tab button after 2 to 3 seconds i got this error and app restart.

**Screenshots**
![WhatsApp Image 2019-03-23 at 20 55 27](https://user-images.githubusercontent.com/5534583/55028595-efe2a500-5029-11e9-8214-dc2407528133.jpeg)

**Additional context**
Add any other detail logs about the problem here.
If possible please share your config.js that use for the app setting
[common.zip](https://github.com/inspireui/support/files/3010040/common.zip)

**Comment by luyx2412** [comment]
HI @mkashifrazzaq11 Can you provide the Mstore expo version? The issue related animation library, so can you try re-install the library again with `rm -rf node_module && yarn install`

Thanks
