### ISSUE TITLE
External config json does not work FluxStore 1.7.6

### ISSUE THREAD

**Issue by samik9** [inspireui/support#4460]
Hello on version 1.7.6 i got white screen on android when loading external json. I test using the same data as lib/config/config_en.json and got this error message https://gzodigital.d.pr/emj2tM
![source  ~_Downloads_FluxStore -1 7-2 Test_source  -  _lib_common_config_general dart 2020-07-31 18-05-14](https://user-images.githubusercontent.com/50071744/89232526-33014080-d5ad-11ea-9867-d60c5814497f.png)

**Comment by minhcasi** [comment]
could you share the external JSON here so that we could have a check? it seems the JSON format is broken

**Comment by samik9** [comment]
I copied the same json that is by default on the code https://gzeideas.com/shop/tienda/config_en.json

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
