### ISSUE TITLE
When I open my app my whole site down 

### ISSUE THREAD

**Issue by ssathamenterprises** [inspireui/support#4462]
Hello sir please help on this , my site normally works in browsers and when I open my mobile app the total Wordpress site down ( loading only ) mobile app also some time works some time not works 

I attached proof of purchase

**Comment by minhcasi** [comment]
@ssathamenterprises - could you share the screenshot issues?

**Comment by ssathamenterprises** [comment]
https://drive.google.com/file/d/1jssNBkN1KIb7fpiex3gbcobHdzZRs8ld/view?usp=drivesdk

Please check the video sir 

When I open my mobile app the whole site down 

This issue from few days before

**Comment by ssathamenterprises** [comment]
There is any issue after I update Wordpress plugin ( mobile store api and redux lite ) ?

**Comment by minhcasi** [comment]
@minhtruong315 - pls help to investigate to see if it cause by new mstore-api update - thank you!

**Comment by minhtruong315** [comment]
Hi @ssathamenterprises is your issue the login is loading forever?

**Comment by ssathamenterprises** [comment]
Loading

**Comment by ssathamenterprises** [comment]
Loading forever

**Comment by minhtruong315** [comment]
@ssathamenterprises pls check this guide to setup the firebase project
https://www.youtube.com/watch?v=C_9mk_MmvOQ

**Comment by ssathamenterprises** [comment]
You mean this loading issue cause by firebase 

Actually yesterday I do MStore api update now everything works good
