### ISSUE TITLE
Firebase Authentication Not Working

### ISSUE THREAD

**Issue by GNAG1993** [inspireui/support#4463]
I have verified my app on firebase with SHA1 and SHA256 still app always shows error in login. 
When I use SMS, it shows: " **This app is not authorized to use Firebase Authentication."**
When I use E-Mail, it shows: **" This app is not authorized to use Firebase Authentication."**
When I try to login with Google sign In, it shows: **"Warning: There is an issue with the app during request the data, please contact admin for fixing the app issues: PlatformExchange(sign_in_failed,com.google.android.gms.common.api.ApiException: 10: ,null)**
When i white list a phone number in Firebase and try to login using SMS, app sends me to the screen for entering OTP, but when I put the OTP i saved in Firebase Console, it shows a new error: **'package:flutter/src/widgets/localization.dart': Failed assertion: line 447 pos 12: 'context != null': is not true.**

when I use cloud messaging through Firebase, it sends the notification, even I get notification on top notification panel in my cellphone, but when I open Notifications in app, that options is blank. By the way I'm in debug mode.

**Comment by minhcasi** [comment]
@GNAG1993 - pls help to check this link https://github.com/inspireui/support/issues/3151#issuecomment-633489369 

Also pls help to give you all comments into one ticket support #4445

**Comment by GNAG1993** [comment]
Hello, I have done with that solution only, now app always shows authorization Header not found

**Comment by GNAG1993** [comment]
Okay an update
Even users who are trying to log in or sign up, they are showing up in Firebase Console. but in the app its showing Exception:Authorization Header not **found**
