### ISSUE TITLE
Rest API is working but not found any product in app

### ISSUE THREAD

**Issue by ekramul-1** [inspireui/support#4464]
I would like to request you to have a look into the issue if possible.
I have send one mail into the support team & your personal mail for www.bbmall.in access.

_Originally posted by @minhcasi in https://github.com/inspireui/support/issues/4357#issuecomment-664760723_

**Comment by ekramul-1** [comment]
I would humbly request to please have a look into this @minhcasi

**Comment by minhcasi** [comment]
support via email - thanks
