### ISSUE TITLE
Searching is not working from last  day. we are using opencart site for data

### ISSUE THREAD

**Issue by chinchujosea** [inspireui/support#4466]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: Searching is stop working from last day earlier it was working fine we did not change anything  in code rather than config.en . but in flux builder searching is working fine while in emulator it is not working
+ Product & version:flux builder 1.0.6
+ Flutter (or React Native) version: flutter
+ Testing Device/Simulator: Pixel 3xl 
+ Screenshot issues (drag the file to attach here): Please find the attachment
![Screenshot_1596518562](https://user-images.githubusercontent.com/69184211/89256203-2dedd100-d641-11ea-9c9f-c821b8cf9488.png)

Log:
Bad state: No element

When the exception was thrown, this was the stack: 
#0      List.first (dart:core-patch/growable_array.dart:219:5)
#1      _FilterSearchAttributesState.afterFirstLayout (package:fstore/screens/search/widgets/filters/filter_search_attributes.dart:68:52)
#2      AfterLayoutMixin.initState.<anonymous closure> (package:after_layout/after_layout.dart:10:38)
#3      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1113:15)
#4      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1060:9)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
move to #4465 - pls help to create just one ticket for your all comments issues
