### ISSUE TITLE
Need  more customization on Add to cart page

### ISSUE THREAD

**Issue by chinchujosea** [inspireui/support#4467]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: We need to display different options  for particular single image but while we build app through fluxstore we didn't get that field. please find the  screenshots attached. 
+ Product & version:flux store version 1.0.6 prefer opencart for data
+ Flutter (or React Native) version: flutter
+ Testing Device/Simulator: Google pixel 3xl
What we are needed is:
![site](https://user-images.githubusercontent.com/69184211/89257268-74442f80-d643-11ea-8991-ce1e4585419e.png)
and what we have getting is
![Screenshot_1596520006](https://user-images.githubusercontent.com/69184211/89257535-01878400-d644-11ea-9cb1-f8cb8688113e.png)

+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
move to #4465 - pls help to create just one ticket for your all comments issues

**Comment by chinchujosea** [comment]
I have update the ticket. Please look on it

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
