### ISSUE TITLE
All Logins are not working, Firebase, 

### ISSUE THREAD

**Issue by GNAG1993** [inspireui/support#4469]
Hello,
I have set up everything in Firebase & Google Consent. IUsers are showing in my Firebase Console also, after that too, I'm getting issue.

**when I try to Login with SMS**

![login-sms](https://user-images.githubusercontent.com/58203387/89266115-26372800-d653-11ea-9d90-0c89a4052229.png)

**when I try to login with email**
![login-email](https://user-images.githubusercontent.com/58203387/89266157-2f27f980-d653-11ea-93e2-dc22ecad50ca.png)

**when i try to login with google**

![login-google](https://user-images.githubusercontent.com/58203387/89266188-3949f800-d653-11ea-9f6a-5da3e4942aaa.png)

**when I try to sign Up**
![sign Up](https://user-images.githubusercontent.com/58203387/89266211-3fd86f80-d653-11ea-8c2b-bee02be3ea75.png)

**This is my Firebase Console Screen. i can see the user with which I am trying to Login.**
![issue login](https://user-images.githubusercontent.com/58203387/89265657-71047000-d652-11ea-8b83-27e7ca25754a.png)

Please help me out as I got many of the errors in this Sign In part and removed them this is just the last where I'm stuck.

**Comment by GNAG1993** [comment]
In **android/build.gradle**, I had to change 
**dependencies {
        ..
        classpath 'com.google.gms:google-services:4.3.2'
        ..
        ..
    }
}**
to
**dependencies {
        ..
        classpath 'com.google.gms:google-services:4.3.3'
        ..
        ..
    }
}**
as firebase has updated version now on console

**Comment by GNAG1993** [comment]
Any update?

**Comment by GNAG1993** [comment]
@tgloc96 Hey, you guys have been supporting us very well and really you guys are doing great. Please check my issue request and try to figure it & get it solved by today. i have to upload this on the play store by today evening.

**Comment by GNAG1993** [comment]
Okay an update, seems like issue is with connecting app to website.

**Comment by GNAG1993** [comment]
Hello, now its logging in but the issue is like what I shared a video earlier in ticket https://github.com/inspireui/support/issues/4374

**Comment by GNAG1993** [comment]
@minhcasi @tgloc96 please help me out. @tgloc96 You have asked me to send the code, i have to send complete source code file or what?

**Comment by GNAG1993** [comment]
@minhcasi finally issue sorted out the issue by creating firebase database. you guys are saying any newbie can create app with your tutorials using fluxbuilder. You guys should include creating Firebase database in the video & tutorials for Firebase Login. i was checking other issue related to my issue. Finally just got a hint from this issue https://github.com/inspireui/support/issues/4097

**Comment by GNAG1993** [comment]
now the issue is, when login through mobile number, email is being created like: Countrycode-mobilenumber@websitedomain. Ex.:91xxxxxxxxxx@xxxx.com

**Comment by MaNoOoz** [comment]
anyone knows how to fix this https://github.com/inspireui/support/issues/4477#issuecomment-669765145
same proplem i cant login to the app

**Comment by MaNoOoz** [comment]
I have problem with login in all platforms I tried all the solutions in  #3151 and my previous support ticket is #4417 
![device-2020-08-06-105200](https://user-images.githubusercontent.com/26860253/89505816-df703c00-d7d2-11ea-934c-1868a2183981.png)
please help @minhcasi

**Comment by GNAG1993** [comment]
@minhcasi 
Hello, why don't you guys are showing address book option in the app, even you guys have imported the endpoints for shipping & billing address.


![](https://user-images.githubusercontent.com/58203387/89540595-e1f68400-d81a-11ea-813b-eb954d4868ed.png)

**Comment by GNAG1993** [comment]
@minhcasi why app is creating automated email for the customer mobilenumber@websitedomain.com , if customer login through sms

**Comment by tgloc96** [comment]
> @minhcasi why app is creating automated email for the customer [mobilenumber@websitedomain.com](mailto:mobilenumber@websitedomain.com) , if customer login through sms

Have you any suggestions for that case? Because we need the email for register user.

**Comment by GNAG1993** [comment]
There are 2 scenerios, which can help us

1. Make email field updatable in app, so that user can update his email. 
2. whenever user checkout for the first time, he/she will enter his/her proper email for notifications, so that can be saved as default by asking user.

I would prefer we should implement the first one, then its good to go, cos I have done this. But dont know why I'm unable to change the email. I'm working on it.

**Comment by GNAG1993** [comment]
Hello, please look at this. Why Mstore API Section is like this, when I try to upload updated config.json file
![Mstore API](https://user-images.githubusercontent.com/58203387/89626150-92659600-d8b6-11ea-9360-0b75a5bba240.png)

**Comment by GNAG1993** [comment]
Hi, I have a suggestion also for SMS Login, like you should give option to also add a password in this, I mean to say Login with SMS should work like Sign Up with SMS, where user also have to enter a password for his/her account. After that on login screen, where app asking for email/username, app ask like-email/username/mobile number.

**Comment by GNAG1993** [comment]
@minhcasi @tgloc96 no reply?

**Comment by minhcasi** [comment]
@GNAG1993 - we are checking and will get back you in 1-2 days - thanks

**Comment by GNAG1993** [comment]
okay, i'm waiting

**Comment by tgloc96** [comment]
> Hi, I have a suggestion also for SMS Login, like you should give option to also add a password in this, I mean to say Login with SMS should work like Sign Up with SMS, where user also have to enter a password for his/her account. After that on login screen, where app asking for email/username, app ask like-email/username/mobile number.

Thanks so much for these suggestions, We will upgrade this at release version 1.7.8

**Comment by GNAG1993** [comment]
@tgloc96 Did you go through my issues? Any update regarding that?

**Comment by GNAG1993** [comment]
> Hello, please look at this. Why Mstore API Section is like this, when I try to upload updated config.json file
> ![Mstore API](https://user-images.githubusercontent.com/58203387/89626150-92659600-d8b6-11ea-9360-0b75a5bba240.png)

@tgloc96 @minhcasi Any update?

**Comment by GNAG1993** [comment]
@minhcasi I'm unable to upload config json to my site? its been more than three days? what's the issue going on?

**Comment by GNAG1993** [comment]
@tgloc96 app is for ecommerce, that too a marketplace app, don't you think it should have these options:

1. Sort Items by Price
2. Multiple Attributes/Filters Should Be Selected. Like If I want a men's shirt in Red color in size M. So how do I Find then? If Multiple Attributes Can Be Selected I'll Directly Go To Filters and Select Men's in Gender, Red in Color, M in Size. So I'll get the list of items exactly matching my requirement. Every m-commerce app have this option.
3. Price Filter should be according to the category or products like if a customer is looking a category which has products from rs. 20 to rs. 100, price filter should have minimum on 20 & max on 100. customer can drag and change his budget between this range. Because each category has different price range.

**Comment by minhcasi** [comment]
@GNAG1993 - you try to activate again the License on Mstore-api for `violetart` to see if it is fixed the verify issue?

The sort and advance filter are not available on the Fluxstore app due to limit of the REST API so that we could not upgrade it, you could try to customize these features to meet your requirements.

**Comment by GNAG1993** [comment]
@minhcasi okay, License activated now after getting an update to Mstore-api

@minhcasi Don't mind, there are many other flutter bases app for wcfm which are having these features- advance filters & sorting.
Only the thing is I don't know how they are doing this.
We should try doing it together for the benefit of everyone using Fluxstore.

**Comment by GNAG1993** [comment]
@minhcasi why app is requesting for permission
android.permission.RECORD_AUDIO

**Comment by GNAG1993** [comment]
@minhcasi Does fluxstore MV captures user's latitude-longitude at checkout. We want to connect a delivery driver app to fluxstore actually.

**Comment by minhcasi** [comment]
@GNAG1993 - you could remove the RECORD_AUDIO setting on Android - it seems not be used for any features.

On the Address shipping, there is the Request Long/Lat location to pick up user address, you could pick user location and request for the Delivery app

**Comment by GNAG1993** [comment]
@minhcasi After updating Mstore API, categories are not showing in app. App unable to connect with categories

**Comment by GNAG1993** [comment]
Any response? I have submitted my app for production release and now after updating api, none of the products & categories are showing in app.

**Comment by GNAG1993** [comment]
Don't mind, but You guys don't allow creating new tickets to a buyer if he is already having a ticket opened, even if he is opening a ticket for a different issue. 
And the main thing you guys always respond on time to the new tickets raised and the old tickets, they just keep asking for support.
I always said you guys are giving very good support. i was really impressed. But From last 1 week, I'm really disappointed with such a behavior.

**Comment by GNAG1993** [comment]
I'm having many issues opened in this same ticket. And almost I finally sorted myself. Because you guys took too long to respond to these old tickets.

**Comment by minhcasi** [comment]
@GNAG1993 - pls try with the latest release with new bug fix and performance improve - thank you!

**Comment by GNAG1993** [comment]
I tried that too, categories not showing up

**Comment by minhcasi** [comment]
@GNAG1993 - you could try to check the reason by using latest Fluxbuilder 1.0.7, we have upgraded the tools to troubleshoot the integration issue - https://github.com/inspireui/fluxbuilder/releases/tag/v1.0.7

**Comment by minhcasi** [comment]
Let us know your checking, thanks

**Comment by GNAG1993** [comment]
Okay, it was my mistake. Sorry guys. We had no product so categories disappeared.
