### ISSUE TITLE
[Mstore] checkout error on App : Domain

### ISSUE THREAD

**Issue by luisalexhg** [inspireui/support#447]
Hi, When I use my woocommerce payment "Payulatam" I get an error on the screeen:
"Error Loading page"

![Captura de pantalla 2019-03-26 a la(s) 15 44 57](https://user-images.githubusercontent.com/28818275/55032248-7d000c80-4fde-11e9-8039-55ac2111f0a9.png)

Wordpress config 
![Captura de pantalla 2019-03-26 a la(s) 15 48 01](https://user-images.githubusercontent.com/28818275/55035396-de77a980-4fe5-11e9-9ea8-64815fb41484.png)

Please, Help!

**Comment by luyx2412** [comment]
Hi @luisalexhg Please provide your purchase code.

Thanks

**Comment by luisalexhg** [comment]
Hi, my code is 993e4b07-50d6-4861-a282-c580c19a685e

**Comment by luyx2412** [comment]
Hi @luisalexhg Can you use debug tools to show error checkout and take the screenshot?

Thanks
