### ISSUE TITLE
Country selection issue in mstore mv react 

### ISSUE THREAD

**Issue by kevadiya** [inspireui/support#4470]
I have an issue at place order in react native mstore mv application.

When I select country from your modal form country but that not selected. So I can not checkout.

I have uploaded my screenshot

![Screenshot_20200804-132418~2](https://user-images.githubusercontent.com/4812340/89268907-cfcbe880-d656-11ea-86b8-51f3c5fee46c.png)

Please check and reply me as soon as possible

Thanks

**Comment by minhcasi** [comment]
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
@luyx2412 - pls help to investigate the issue

**Comment by luyx2412** [comment]
Hi @kevadiya Please replace this file to `src/containers/Cart/Delivery/index.js` to fix the issue.
[index.js.zip](https://github.com/inspireui/support/files/5022902/index.js.zip)

Thanks

**Comment by minhcasi** [comment]
@kevadiya - any update on this issue - pls help to open one ticket for your all issue - thank you for your time

**Comment by kevadiya** [comment]
hello sir,

I have an issue in mstore mv react.
when i run app with "expo start" command then i have scan qr code and javascript bundle build 100%.

after of that it gives me this screen shot error.
bfeb26e8-0758-479c-91f4-1e81ba7c6e3a

how can i resolve them

please reply me as soon as possible.
![bfeb26e8-0758-479c-91f4-1e81ba7c6e3a](https://user-images.githubusercontent.com/4812340/89710007-332e8100-d99d-11ea-98f4-435488c2ecf5.jpg)

**Comment by luyx2412** [comment]
Hi @kevadiya Please fill the form and upload your AppConfig.json and Config.js file. Let me investigate about the issue easier. 

Thanks

**Comment by kevadiya** [comment]
OK.
I have share you file in your form..
(for above reply)
===============================
**This one is new issue that i have found**
i have some other issue like. 
1. i want phone number like (91) 9427278524 (means country code & 10 digit) right now your app accept only country code & 9 digit only. (i am talking about at checkout time customer information "src/containers/Cart/Delivery/index.js")

2. when i open specific vendor at that time vendor info showing but there product not showing. while in your demo product is showing.

3. your app does not have forget password that's the major point. how can i add them. or you may also help. because it's compulsory features.

4. I have setup onesignal and firebase  as you say but notification not work...

Please help me 

as soon as possible.

**Comment by kevadiya** [comment]
Hello, are you interested in this issue?

**Comment by minhcasi** [comment]
@luyx2412 - please keep follow up this issue -thank you!

**Comment by kevadiya** [comment]
Which issue to follow

**Comment by luyx2412** [comment]
Hi @kevadiya Sorry about reply you late.
1. In `src/common/Validator.js` line 26. Please change the validate the phone same the screenshot.
![image](https://user-images.githubusercontent.com/8909619/90405625-3678e980-e0ce-11ea-89e6-d90c7d9e0ed9.png)
2. Can you share me the specific screenshot about this issue?
3. You can use the webview to handle forgot password.
4. Please send me your config file again. Let me investigate about this issue.

Thanks

**Comment by kevadiya** [comment]
ISSUE 1: i want phone number like (91) 9427278524 (means country code & 10 digit) right now your app accept only country code & 9 digit only. (i am talking about at checkout time customer information "src/containers/Cart/Delivery/index.js")
SEE https://www.youtube.com/watch?v=PeTt9Zdl_tQ&feature=youtu.be

**Comment by kevadiya** [comment]
ISSUE 2: when i open specific vendor at that time vendor info showing but there product not showing. while in your demo product is showing. also showing "Vendor" Text at the place of vendor name
![Screenshot_1](https://user-images.githubusercontent.com/4812340/90508474-7050fb00-e175-11ea-961b-6ca83094fdbb.jpg)

**Comment by kevadiya** [comment]
ISSUE 3: your app does not have forget password that's the major point. how can i add them. or you may also help. because it's compulsory features.

GUIDE ME SO I CAN IMPLEMENT WEBVIEW TO FORGET PASSWORD. ANY VIDEO??

**Comment by kevadiya** [comment]
ISSUE 4: I have setup onesignal and firebase as you say but notification not work...

I have already send files to you.

**Comment by kevadiya** [comment]
ISSUE 5: Variable product work on website while not work in app. I have added one dress with age variation. 

Video link: https://youtu.be/s6tA63YeGi0

**Comment by luyx2412** [comment]
Hi @kevadiya Please fill the form and share me your config file which will investigate easier.

Thanks

**Comment by kevadiya** [comment]
I have already send. But send me link again so I will share you again..

Please

**Comment by minhcasi** [comment]
@luyx2412 - pls suggest on this issue

**Comment by luyx2412** [comment]
Hi @kevadiya 
1. You need change the validate phone to your rule. So please see this comment https://github.com/inspireui/support/issues/4470#issuecomment-674906599
2. The issues appear 2 problems, the first please change `this.page = props.page ? props.page : 0;` to `this.page = props.page ? props.page : 1;` in `src/components/ProductList/VendorProducts.js` line 25. And Please check your vendor product, because the vendor response empty vendors http://smartlady.co.in/wp-json/dokan/v1/stores/4/products/?per_page=20&page=1&status=draft.
3. You can add your forgot password url same the example doc https://github.com/react-native-community/react-native-webview#usage
4. You meant you setup onesignal with firebase about the notification?
5. Thanks for your issue report, we will try fix the issue and release in next version.

Thanks

**Comment by kevadiya** [comment]
4. You meant you setup onesignal with firebase about the notification?

Yes

**Comment by luyx2412** [comment]
Hi @kevadiya The firebase and onesignal is different, so please setup only onesignal. This is a document to setup https://documentation.onesignal.com/docs/react-native-sdk-setup

Thanks

**Comment by luyx2412** [comment]
Closed! Because no longer response.

P/S: Feel free to create new issue.
