### ISSUE TITLE
#4196 Error while validate app to  app store 

### ISSUE THREAD

**Issue by Shiru-kun** [inspireui/support#4471]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
When i try to validate the app to distribute i got an error related to an app icon... that cant be transparent or alpha channel 
+ Product & version: 
1.7.6
+ Flutter (or React Native) version: 
1.17
+ Testing Device/Simulator: 
building to generic devices  
+ Screenshot issues (drag the file to attach here): 
![image](https://user-images.githubusercontent.com/54008441/89273246-95a31c80-d63f-11ea-9ced-8c797cc48483.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
- try to use this script to generate app icon - https://docs.inspireui.com/fluxstore/delivery/#13-change-the-app-icon

- make sure to remove the 'anpha from png' - https://stackoverflow.com/questions/26171739/remove-alpha-channel-in-an-image

**Comment by Shiru-kun** [comment]
already fixed it 
thank u
