### ISSUE TITLE
Attributes not showing in filters

### ISSUE THREAD

**Issue by sabieworld** [inspireui/support#4473]
+ Detail Issues: Attributes are not showing in filter menu (category page & Search). when i check getFilterAttributes() function in services/prestashop.dart, it is incomplete and does nothing (just returns null).

+ Product & version: Fluxstore Prestashop - Flutter E-commerce Full App 1.7
+ Flutter (or React Native) version: flutter 1.17.5
+ Testing Device/Simulator: Nexus 6

**Comment by vumanhsn97** [comment]
@sabieworld 
Please waiting for next version or try with this:
- replace in file in this attachment: 
[archive.zip](https://github.com/inspireui/support/files/5055183/archive.zip)
- update this module:
[customapi.zip](https://github.com/inspireui/support/files/5055186/customapi.zip)

**Comment by sabieworld** [comment]
@vumanhsn97 files you sent are also incomplete. check line:217 in services/prestashop.dart. it is still returning null. so attributes are not working even after file replace.
also you updated arguments in getShippingMethods() in services/prestashop.dart but didn't made corresponding changes in the files from where the function is called (base service, widgets,etc.) . so it causes build error.
can u send me the files with those issues fixed..?

**Comment by vumanhsn97** [comment]
@sabieworld 
You can check in this attachment: 
[archive.zip](https://github.com/inspireui/support/files/5056233/archive.zip)
In services/prestashop.dart replace functions: getSubAttributes, getFilterAttributes, fetchProductsByCategory, getProductOptions, searchProducts
