### ISSUE TITLE
prestashop chinese category name garbled

### ISSUE THREAD

**Issue by tao0103** [inspireui/support#4474]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues:  prestashop chinese category name garbled
+ Product & version:  
+ Flutter (or React Native) version: flutter 1.17.5
+ Testing Device/Simulator: pixel 3 xl
+ Screenshot issues (drag the file to attach here): 
![1596557457(1)](https://user-images.githubusercontent.com/26236559/89317724-14b74580-d67e-11ea-80e7-0584b49ba3f8.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@tao0103 - could you try to change the google font for Chinese on this file:

<img width="939" alt="Screen Shot 2020-08-05 at 11 10 20" src="https://user-images.githubusercontent.com/1459805/89370975-41b23980-d70c-11ea-8056-e70d9fa274d7.png">

**Comment by minhcasi** [comment]
Let us know your checking - thanks

**Comment by minhcasi** [comment]
Let us know your checking - thanks

**Comment by tao0103** [comment]
Still no work

**Comment by tao0103** [comment]
> Let us know your checking - thanks

Still no work

**Comment by tao0103** [comment]
Hi, I solved it. It's a decode problem. 
add utf8 decode way:
json.decode(utf8.decode(response.bodyBytes));
