### ISSUE TITLE
Apple login not working

### ISSUE THREAD

**Issue by rabeehlive** [inspireui/support#4477]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

Apple login not working. Need arjent assistants
<img width="768" alt="attachment Screenshot-0804-121743" src="https://user-images.githubusercontent.com/68809928/89360366-d81f3480-d6e5-11ea-8051-4a9482b6e0bb.png">

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by rabeehlive** [comment]
#4372 my previous verified ticket id

**Comment by Shiru-kun** [comment]
@minhcasi  im getting that issue too, and i dont know how to setup this, my app got reject by apple

**Comment by rabeehlive** [comment]
@tgloc96 please reply

**Comment by MaNoOoz** [comment]
I have problem with login in all platforms I tried all the solutions in  #3151 and my previous support ticket is #4417 @minhcasi 
logcat: 
```
D/ViewRootImpl@853c90c[SignInHubActivity](21287): MSG_WINDOW_FOCUS_CHANGED 1
V/InputMethodManager(21287): Starting input: tba=android.view.inputmethod.EditorInfo@781134b nm : com.callsisters.callsisters ic=null
I/InputMethodManager(21287): startInputInner - mService.startInputOrWindowGainedFocus
D/ViewRootImpl@1af9d79[MainActivity](21287): MSG_WINDOW_FOCUS_CHANGED 1
V/InputMethodManager(21287): Starting input: tba=android.view.inputmethod.EditorInfo@cd84128 nm : com.callsisters.callsisters ic=null
I/InputMethodManager(21287): startInputInner - mService.startInputOrWindowGainedFocus
D/ViewRootImpl@853c90c[SignInHubActivity](21287): MSG_WINDOW_FOCUS_CHANGED 0
I/flutter (21287): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
I/flutter (21287): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
I/flutter (21287): <asynchronous suspension>
I/flutter (21287): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
I/flutter (21287): #3      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:356:48)
I/flutter (21287): #4      MethodChannelGoogleSignIn.signIn (package:google_sign_in_platform_interface/src/method_channel_google_sign_in.dart:45:10)
I/flutter (21287): #5      GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart:233:42)
I/flutter (21287): <asynchronous suspension>
I/flutter (21287): #6      GoogleSignIn._addMethodCall (package:google_sign_in/google_sign_in.dart:288:18)
I/flutter (21287): #7      GoogleSignIn.signIn (package:google_sign_in/google_sign_in.dart:359:9)
I/flutter (21287): #8      UserModel.loginGoogle (package:fstore/models/user/user_model.dart:140:53)
I/flutter (21287): #9      _LoginPageState.build._loginGoogle (package:fstore/screens/users/login.dart:244:60)
I/flutter (21287): <asynchronous suspension>
I/flutter (21287): PlatformException(network_error, com.google.android.gms.common.api.ApiException: 7: , null)
I/System.out(21287): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(21287): (HTTPLog)-Static: isSBSettingEnabled false
D/ViewRootImpl@1af9d79[MainActivity](21287): Relayout returned: old=[0,0][1440,2560] new=[0,0][1440,2560] result=0x1 surface={valid=true 545314910208} changed=false
D/OpenGLRenderer(21287): eglDestroySurface = 0x7f10c22a00
D/ViewRootImpl@853c90c[SignInHubActivity](21287): Relayout returned: old=[0,0][1440,2560] new=[0,0][1440,2560] result=0x5 surface={valid=false 0} changed=true
D/ViewRootImpl@853c90c[SignInHubActivity](21287): dispatchDetachedFromWindow
D/InputEventReceiver(21287): channel '2474e48 com.callsisters.callsisters/com.google.android.gms.auth.api.signin.internal.SignInHubActivity (client)' ~ Disposing input event receiver.
D/InputEventReceiver(21287): channel '2474e48 com.callsisters.callsisters/com.google.android.gms.auth.api.signin.internal.SignInHubActivity (client)' ~NativeInputEventReceiver.
```
firebase can verify my app I can send  notifications to the app and i think my sha1 is working correctly 
**do i need to upgrade any dependiencies on the pubspec.yaml file ?**

**Comment by GNAG1993** [comment]
Did you followed all the tutorial regarding Firebase Authentication properly. go through that again, and after that you have to create database in Firebase to get Logins working

**Comment by MaNoOoz** [comment]
> Did you followed all the tutorial regarding Firebase Authentication properly. go through that again, and after that you have to create database in Firebase to get Logins working
database ??? do u mean auth

**Comment by GNAG1993** [comment]
> > Did you followed all the tutorial regarding Firebase Authentication properly. go through that again, and after that you have to create database in Firebase to get Logins working
> > database ??? do u mean auth

no, In firebase console , you have to create database

**Comment by MaNoOoz** [comment]
@GNAG1993 I followed all the tutorials it's not working 
i can send notification to the app Thu

**Comment by MaNoOoz** [comment]
> > > Did you followed all the tutorial regarding Firebase Authentication properly. go through that again, and after that you have to create database in Firebase to get Logins working
> > > database ??? do u mean auth
> 
> no, In firebase console , you have to create database

can  u share screenshot, please

**Comment by MaNoOoz** [comment]
@GNAG1993 they never mention that in the docs

**Comment by MaNoOoz** [comment]
@GNAG1993  what kind of database firestore or firebase ?

**Comment by rabeehlive** [comment]
Please reply me

**Comment by GNAG1993** [comment]
sharing you the link to there youtube video, just follow till creating Firebase Database. 

https://www.youtube.com/watch?v=C_9mk_MmvOQ

follow steps from 00:20 to 03:02

**Comment by GNAG1993** [comment]
> @GNAG1993 they never mention that in the docs
Even I was getting frustrated from a week regarding this

**Comment by GNAG1993** [comment]
> Please reply me

Are other logins working?

**Comment by MaNoOoz** [comment]
> > Please reply me
> 
> Are other logins working?

No nothing works

**Comment by MaNoOoz** [comment]
> sharing you the link to there youtube video, just follow till creating Firebase Database.
> 
> https://www.youtube.com/watch?v=C_9mk_MmvOQ
> 
> follow steps from 00:20 to 03:02
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/5085acaa6059d682788a5bb607417d66ac6a66af/68747470733a2f2f692e7974696d672e636f6d2f76692f435f396d6b5f4d6d764f512f6d617872657364656661756c742e6a7067"><img alt="" height="14" src="/yts/img/favicon_144-vfliLAfaB.png"> YouTube**[Setup Firebase RealTime Chat For Fluxstore Multi Vendor (Flutter E-Commerce App In 10 Minutes)](https://www.youtube.com/watch?v=C_9mk_MmvOQ)**Learn how to set up the Firebase realtime Chat on both ios and android for Fluxstore Multi-Vendor (WooCommerce), this is a great feature to support Chating b...

ok i will test and tell u

**Comment by GNAG1993** [comment]
You need to verify your app again with firebase, make sure you followed a,ll the steps from Firebase Login tutorial, and everything worked fine during that

**Comment by MaNoOoz** [comment]
> You need to verify your app again with firebase, make sure you followed a,ll the steps from Firebase Login tutorial, and everything worked fine during that

ok i will try

**Comment by GNAG1993** [comment]
> > sharing you the link to there youtube video, just follow till creating Firebase Database.
> > https://www.youtube.com/watch?v=C_9mk_MmvOQ
> > follow steps from 00:20 to 03:02
> > > <img alt="" width="48" src="https://camo.githubusercontent.com/5085acaa6059d682788a5bb607417d66ac6a66af/68747470733a2f2f692e7974696d672e636f6d2f76692f435f396d6b5f4d6d764f512f6d617872657364656661756c742e6a7067"><img alt="" height="14" src="/yts/img/favicon_144-vfliLAfaB.png"> YouTube**[Setup Firebase RealTime Chat For Fluxstore Multi Vendor (Flutter E-Commerce App In 10 Minutes)](https://www.youtube.com/watch?v=C_9mk_MmvOQ)**Learn how to set up the Firebase realtime Chat on both ios and android for Fluxstore Multi-Vendor (WooCommerce), this is a great feature to support Chating b...
> 
> ok i will test and tell u
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/5085acaa6059d682788a5bb607417d66ac6a66af/68747470733a2f2f692e7974696d672e636f6d2f76692f435f396d6b5f4d6d764f512f6d617872657364656661756c742e6a7067"><img alt="" height="14" src="/yts/img/favicon_144-vfliLAfaB.png"> YouTube**[Setup Firebase RealTime Chat For Fluxstore Multi Vendor (Flutter E-Commerce App In 10 Minutes)](https://www.youtube.com/watch?v=C_9mk_MmvOQ)**Learn how to set up the Firebase realtime Chat on both ios and android for Fluxstore Multi-Vendor (WooCommerce), this is a great feature to support Chating b...

are you able to receive otp in sms login. if not, then you need to check your firebase setting for the app. Surely you missed some point

**Comment by rabeehlive** [comment]
> > Please reply me
> 
> Are other logins working?

Yes, except apple login

**Comment by MaNoOoz** [comment]
@GNAG1993  I think u have a different product I have flux store pro still not working :(

**Comment by rabeehlive** [comment]
Then why are you here, go an create a ticket for your issue

**Comment by tgloc96** [comment]
Hello @rabeehlive ,

Can you send me your source code or add me to your git project and add me to your firebase project?

Sorry for the delayed response to you.

**Comment by rabeehlive** [comment]
@tgloc96 i can share my source code, please send me your mail id

**Comment by minhcasi** [comment]
@rabeehlive - pls send to inspireui.team@gmail.com or you could add this email to your private gitlab - thanks

**Comment by rabeehlive** [comment]
I have solved the apple login issue,
Help me with other one. 

I want to change the default sign in method, by replacing the username and password screen with mobile number login screen.

**Comment by rabeehlive** [comment]
@minhcasi please reply,

**Comment by rabeehlive** [comment]
@tgloc96 please reply me

**Comment by minhcasi** [comment]
@rabeehlive - could you check if you could fix by using this solution - https://github.com/inspireui/support/issues/3871#issuecomment-648547301

**Comment by rabeehlive** [comment]
But after this,can't see social login options

**Comment by rabeehlive** [comment]
@minhcasi mobile ligin not working in ios, getting this error when clicking sign in button after enetering mobile number

" if app delegate swizzling is desabled, remote notification received by UIApplicationDelegate need to be forwarded to FIRAuth's canHandleNotification: method."

**Comment by rabeehlive** [comment]
all other login methods are working, but mobile number login not working in iOS APP

**Comment by tgloc96** [comment]
Hi @rabeehlive, please send to inspireui.team@gmail.com or you could add this email to your private GitLab - thanks

**Comment by rabeehlive** [comment]
mail send, please check

**Comment by rabeehlive** [comment]
Any updates?

**Comment by tgloc96** [comment]
I was check mail and I don't see anything. Please send me your source code again or add me to your project via email tgloc96@gmail.com

**Comment by rabeehlive** [comment]
@tgloc96 mail send.please check

**Comment by tgloc96** [comment]
> @tgloc96 mail send.please check

I received and I am investigating

**Comment by tgloc96** [comment]
Hi @rabeehlive ,
I have checked your source code and is in quite old version, we have fixed this error in newer versions, Please update your source code to the latest version according to this tutorial: https://medium.com/@inspireui/how-to-upgrade-fluxstore-projects-by-using-git-cebde7489ea6

**Comment by rabeehlive** [comment]
NO, ITS LATEST 1.7.6. AND I DON'T HAVE ACCESS TO
https://gitlab.com/inspireui/fluxstore-pro. WHAT'S NEXT

**Comment by rabeehlive** [comment]
@tgloc96 I THINK 1.7.5 IS THE LATEST VERSION AVAILABLE ON https://codecanyon.net/

**Comment by tgloc96** [comment]
We are releasing the version 1.7.7, please wait a second.

> @tgloc96 I THINK 1.7.6 IS THE LATEST VERSION AVAILABLE ON https://codecanyon.net/
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/c5a18223816825ebf6c0fec648742882ecbb6a7b/68747470733a2f2f6173736574732e73686f7066726f6e742e656e7661746f2d7374617469632e636f6d2f696d616765732f6d6574612f6c6f676f732f636f646563616e796f6e2e706e67"><img alt="" height="14" src="https://camo.githubusercontent.com/c75d968dba11187d74e09644791494a4418ce2d8/68747470733a2f2f6173736574732e73686f7066726f6e742e656e7661746f2d7374617469632e636f6d2f69636f6e732f636f646563616e796f6e2e6e65742f66617669636f6e2e69636f"> CodeCanyon**[Buy Plugins & Code from CodeCanyon](https://codecanyon.net/)**Discover 34,214 Plugins, Code and Script for Bootstrap, Javascript, PHP, Wordpress, HTML5 and more. Save time, buy Code on CodeCanyon!

**Comment by rabeehlive** [comment]
@tgloc96 waiting

**Comment by rabeehlive** [comment]
@tgloc96 when the update will release?

**Comment by minhcasi** [comment]
@rabeehlive -the latest version `1.7.7` is ready for download, please keep the update and let us know if you have any question - thank you!

**Comment by rabeehlive** [comment]
that error solved, now iam able to recieve otp. but there is a another problem.
it's opening a safari browser window and howin recaptha when confirming the otp. why this is happening?

**Comment by rabeehlive** [comment]
@tgloc96 @minhcasi i just mailed a screen record of the issue to tgloc96@gmail.com. please reply

**Comment by rabeehlive** [comment]
@minhcasi @tgloc96 any updates?

**Comment by minhcasi** [comment]
> it's opening a safari browser window and howin recaptha when confirming the otp. why this is happening?

Could you help to make a video screenshot for this issue? We have tried to reproduce the issue be could replicate the problem - thank you for your time

**Comment by rabeehlive** [comment]
@minhcasi @tgloc96 https://drive.google.com/file/d/1Pa95rpZo4Qufh_AZQ8oGmZtJwgQSM5JN/view?usp=sharing

**Comment by minhcasi** [comment]
But at finally could you able to login with SMS with the confirm OPT? 

We are using this library for this feature, could give a try to check the params from `PinCodeTextField` to see if could improve the UX (they have some example with the flair animation still)  https://pub.dev/packages/pin_code_fields

**Comment by rabeehlive** [comment]
yes, iam able to confirm sms and sign in. but i have to remove the redirecting recapctha window. i didn't understand this: https://pub.dev/packages/pin_code_fields

@minhcasi please help me solve this issue

**Comment by rabeehlive** [comment]
in android is good, the problem is with ios only. i don't nkow how to use this parameters. please reply @tgloc96 @minhcasi

**Comment by rabeehlive** [comment]
please reply

**Comment by minhcasi** [comment]
@rabeehlive - it could be the security to force to recapctha on ios, we could not check the reason, it thinks it is not impacted to the UX - thanks

**Comment by rabeehlive** [comment]
@minhcasi then what is the solution for this?

**Comment by minhcasi** [comment]
@rabeehlive - if you could login fine, then we don't think it is the issue sir?

**Comment by rabeehlive** [comment]
I have to remove the recaptcha window. That's the problem. I already uploaded a screen record.

**Comment by rabeehlive** [comment]
@minhcasi again bug, apple rejected my application. Side menu buttons not giving any actions in ipads. nothing happens after clicking on it, shop, blog, sign in button, works well in iphones, but not working in iphones. need solution

**Comment by minhcasi** [comment]
@rabeehlive - could you share the detail report issues from Apple and also share the screen record for the recaptcha issue (it seems you forgot to attach the image) - thank you!

**Comment by rabeehlive** [comment]
SOLVED

**Comment by minhcasi** [comment]
@rabeehlive - could you share your solution?

**Comment by rabeehlive** [comment]
There is no solution, i removed those options from ios application, weiting
for reply from support is waste. So i removed those options.
