### ISSUE TITLE
Products with combinations out of stock, tax problem

### ISSUE THREAD

**Issue by gentianziu03** [inspireui/support#4478]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
1) Products with combinationns shows out of stock
2)back office orders shows without title of products
3) tax is not counted on final price on app
+ Product & version: 1.6.7
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

![85851205-8d3d0380-b7ae-11ea-8c85-5e583ad21462](https://user-images.githubusercontent.com/46620232/89396147-7cb56c80-d70e-11ea-91d0-586d9230741f.gif)

![88781710-030d0400-d18d-11ea-9d98-a1fe038628ef](https://user-images.githubusercontent.com/46620232/89396330-b4bcaf80-d70e-11ea-8831-4677f3eb2def.jpg)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@gentianziu03 - could you help to share the admin login to the website (sent to inspireui.team@gmail.com) - we will help to investigate this issue - thank you!

**Comment by gentianziu03** [comment]
Yes, i sent it

**Comment by minhcasi** [comment]
@vumanhsn97 - pls help to investigate this issue

**Comment by gentianziu03** [comment]
Hello, any news?

**Comment by vumanhsn97** [comment]
@gentianziu03 e
We have been fixed taxes issue in your site. Please check
Thanks!
[customapi.zip](https://github.com/inspireui/support/files/5073694/customapi.zip)

**Comment by gentianziu03** [comment]
hello the tax is showing on app

but on back end shows the wrong price

for first product the price is 1152 leke
![12](https://user-images.githubusercontent.com/46620232/90245427-f0542980-de32-11ea-8fad-2d5fa5cd5500.JPG)

second product 480 leke
![45](https://user-images.githubusercontent.com/46620232/90245431-f518dd80-de32-11ea-8f84-8ee4466f7e12.JPG)


on back end is 1200 for first product
and second is 500

also the total is wrong
![backend](https://user-images.githubusercontent.com/46620232/90245243-96536400-de32-11ea-8906-19659d942fe7.JPG)

**Comment by minhcasi** [comment]
we have fixed this issue on the latest release `1.7.7` - let us know if you have any questions - thank you!
