### ISSUE TITLE
Issues in Performance and Theme

### ISSUE THREAD

**Issue by vipsouq** [inspireui/support#4479]
Hi, 
I purchased Flux store MV and love the product,
I have minor issues or bugs, I'll list it down please provide suggestions or solutions, Thanks

1. Splash screen - There is issue as it takes 2 or 3 seconds to load after the white screen and after that the onboarding screen is not showing

2. And the overall Application is slow and not smoother in some areas

3. When one login with SMS it automatically assign their email as "phonenumber@domain.com" any suggestion to change this

4. the Setting Topbar is not taking the color from Primary color

5. (Attached Screenshot) The Filter Layout when i select list its showing some error listed in the image

![WhatsApp Image 2020-08-05 at 2 48 48 PM](https://user-images.githubusercontent.com/69245798/89409978-9b762c00-d72b-11ea-8a20-9c545587c622.jpeg)
![WhatsApp Image 2020-08-05 at 2 48 48 PM(1)](https://user-images.githubusercontent.com/69245798/89409993-9f09b300-d72b-11ea-85a5-e2dc56ff1615.jpeg)

**Comment by minhcasi** [comment]
@tgloc96 - please help to investigate these issues - thank you!

**Comment by tgloc96** [comment]
Hello @vipsouq,
To fix this problem, please download the attachment below and extract it, you will receive 2 files, please copy and replace 2 files at the path: _lib/widgets/product_

[fix list layout.zip](https://github.com/inspireui/support/files/5034081/fix.list.layout.zip)

**Comment by vipsouq** [comment]
Any suggestions on the others

**Comment by tgloc96** [comment]
Everything is OK?

**Comment by vipsouq** [comment]
Other issues I'm facing, Like the splash screen and onboarding.dart not working

**Comment by tgloc96** [comment]
> Other issues I'm facing, Like the splash screen and onboarding.dart not working

Please send to tgloc96@gmail.com your source code or you could add this email to your private GitLab - Thanks

**Comment by minhcasi** [comment]
@rabeehlive -the latest version `1.7.7` is ready for download, please keep the update and let us know if you have any question - thank you!

**Comment by vipsouq** [comment]
Hi, I have another issue in latest update

![image](https://user-images.githubusercontent.com/69245798/90309082-a0866880-deed-11ea-876a-f4309c89c9e3.png)

**Comment by vipsouq** [comment]
error: Undefined name 'KSplashScreen'. (undefined_identifier at [fluxstore_vendor] lib\app_init.dart:166)

**Comment by vipsouq** [comment]
> > Other issues I'm facing, Like the splash screen and onboarding.dart not working
> 
> Please send to [tgloc96@gmail.com](mailto:tgloc96@gmail.com) your source code or you could add this email to your private GitLab - Thanks

I send to you the source code please review it

**Comment by minhcasi** [comment]
@vipsouq - could you check if using the same app_ini file, like this one:

[app_init.dart.txt](https://github.com/inspireui/support/files/5079869/app_init.dart.txt)

**Comment by vipsouq** [comment]
Yes its the same but still Ksplashscreen has problem

**Comment by vipsouq** [comment]
Please can you solve this issue i have already sent you the source file also in mail

**Comment by vipsouq** [comment]
> 
> 
> @vipsouq - could you check if using the same app_ini file, like this one:
> 
> [app_init.dart.txt](https://github.com/inspireui/support/files/5079869/app_init.dart.txt)

The same one Please help as im not getting response from InspireUI

**Comment by vipsouq** [comment]
and I also got this error

FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 896

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.

**Comment by vipsouq** [comment]
Anyone there to response?

**Comment by vipsouq** [comment]
@tgloc96 please help me i have sent you mail of my source code

**Comment by vipsouq** [comment]
@tgloc96 @minhcasi Anyone please respond

**Comment by minhcasi** [comment]
@vipsouq - we will try our best to update you as soon as possible - thank you for your patience 

@tgloc96

**Comment by vipsouq** [comment]
![WhatsApp Image 2020-08-17 at 5 25 00 PM](https://user-images.githubusercontent.com/69245798/90407093-b98a4780-e0ae-11ea-9529-da025ae716f1.jpeg)

Why the thumbnails are blurred, Some are same as on website some are blurred and can't change the product images, Please add this too in the issues

**Comment by vipsouq** [comment]
And the problem with filter not working according to price range its just shows fixed price irrelevant of product pricing

![WhatsApp Image 2020-08-17 at 6 32 09 PM](https://user-images.githubusercontent.com/69245798/90414208-29510000-e0b8-11ea-84b6-0be5491f8751.jpeg)
![WhatsApp Image 2020-08-17 at 6 32 09 PM(1)](https://user-images.githubusercontent.com/69245798/90414213-2a822d00-e0b8-11ea-8af8-eb8f30f71c0f.jpeg)

**Comment by vipsouq** [comment]
[WhatsApp Video 2020-08-18 at 1.01.46 PM.zip](https://github.com/inspireui/support/files/5089667/WhatsApp.Video.2020-08-18.at.1.01.46.PM.zip)

Please find this video as login is not working and just loads and doesn't gives any result but the login has been happened

**Comment by tgloc96** [comment]
> [WhatsApp Video 2020-08-18 at 1.01.46 PM.zip](https://github.com/inspireui/support/files/5089667/WhatsApp.Video.2020-08-18.at.1.01.46.PM.zip)
> 
> Please find this video as login is not working and just loads and doesn't gives any result but the login has been happened

Ok, I will check right now

**Comment by vipsouq** [comment]
how to remove the attributes thats not necessary in filter section?

**Comment by tgloc96** [comment]
Excuse me, can you tell me flutter version you are using?

**Comment by vipsouq** [comment]
Flutter 1.20.2 channel stable

**Comment by tgloc96** [comment]
Hello @vipsouq,
- The first issue, I was fixed and will send back to you the full source code right now.
- The Second issue, please tell me about detail areas.
- The third issue, We are fixed this in the release version 1.7.8
- The fourth issue, You open the file at _"lib/common/constants/colors.dart" and change field **_kBackgroundAppBar_** like image below
<img width="439" alt="image" src="https://user-images.githubusercontent.com/46434718/90594250-29661280-e214-11ea-85ba-a8a3e3de4776.png">
_

**Comment by vipsouq** [comment]
I lost the numbers on the issues and is there fix for Ksplashscreen?
and the source code you are sending its updated to 1.7.8 right?
if not how to is there any guide for this

**Comment by tgloc96** [comment]
> I lost the numbers on the issues and is there fix for Ksplashscreen?
> and the source code you are sending its updated to 1.7.8 right?
> if not how to is there any guide for this

I was fixed Ksplashscreen and We'll be releasing version 1.7.8 in a couple of weeks.

**Comment by vipsouq** [comment]
Any sooner way to get 1.7.8 as i need to launch the app today

**Comment by tgloc96** [comment]
I sent you full source code via email, please check it.

**Comment by tgloc96** [comment]
> Any sooner way to get 1.7.8 as i need to launch the app today

I wish I can, I wish I could, maybe we'll have this feature done in a few days.

**Comment by vipsouq** [comment]
any issue clearence on login bug?

**Comment by vipsouq** [comment]
I need this one also
how to remove the attributes thats not necessary in filter section?

**Comment by tgloc96** [comment]
> I need this one also
> how to remove the attributes thats not necessary in filter section?

Can you please describe it in more detail?

**Comment by vipsouq** [comment]
In the collection page of the app every attributes of the product thats not in the specific collection is displayed,
How can i remove or alter them


Also still the login has issues, please fix that

**Comment by tgloc96** [comment]
> In the collection page of the app every attributes of the product thats not in the specific collection is displayed,
> How can i remove or alter them
> 
> Also still the login has issues, please fix that

I still do not understand your problem. Can you take a screenshot and detailed description on it?
As for the login problem, do you mean login via SMS?

**Comment by vipsouq** [comment]
and app keeps stopping and rest API not working

Launching lib\main.dart on POCOPHONE F1 in debug mode...
Running Gradle task 'assembleDebug'...
Parameter format not correct -
✓ Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...
Waiting for POCOPHONE F1 to report its views...
Debug service listening on ws://127.0.0.1:52190/D1DKl6wvEOU=/ws
Syncing files to device POCOPHONE F1...
E/FlutterFcmService(22947): Fatal: failed to find callback
I/souq.fusiontec(22947): ProcessProfilingInfo new_methods=3338 is saved saved_to_disk=1 resolve_classes_delay=8000
I/flutter (22947): [2020-08-24 17:34:28.598173Z][Vipsouq][main] ============== main.dart START ==============
I/flutter (22947): [2020-08-24 17:34:28.761828Z][Vipsouq][AppState] initState
I/flutter (22947): [2020-08-24 17:34:28.777410Z][Vipsouq][AppState] build
I/flutter (22947): [2020-08-24 17:34:28.822880Z][Vipsouq][AppState] build Theme
I/flutter (22947): [2020-08-24 17:34:29.898889Z][Vipsouq]screenName /
I/flutter (22947): [2020-08-24 17:34:30.168111Z][Vipsouq][AppState] Inital Data
I/flutter (22947): [2020-08-24 17:34:30.497303Z][Vipsouq][Services] setAppConfig: --> wcfm <--
I/flutter (22947): [2020-08-24 17:34:30.555860Z][Vipsouq][AppState] init mobile modules ..
I/flutter (22947): [2020-08-24 17:34:30.566489Z][Vipsouq][AppState] register modules .. DONE
E/OneSignal(22947): promptPermission() is not applicable in Android
I/flutter (22947): [2020-08-24 17:34:30.594877Z][Vipsouq]#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1404:5)
I/flutter (22947): #1      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:934:48)
I/flutter (22947): #2      _parseJson (dart:convert-patch/convert_patch.dart:40:10)
I/flutter (22947): #3      JsonDecoder.convert (dart:convert/json.dart:505:36)
I/flutter (22947): #4      JsonCodec.decode (dart:convert/json.dart:156:41)
I/flutter (22947): #5      jsonDecode (dart:convert/json.dart:96:10)
I/flutter (22947): #6      AppModel.loadAppConfig (package:fstore/models/app.dart:148:25)
I/flutter (22947): <asynchronous suspension>
I/flutter (22947): #7      _AppInitState.loadInitData (package:fstore/app_init.dart:67:63)
I/flutter (22947): #8      _rootRunUnary (dart:async/zone.dart:1198:47)
I/flutter (22947): #9      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
I/flutter (22947): #10     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
I/flutter (22947): #11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
I/flutter (22947): #12     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
I/flutter (22947): #13     Future._completeWithValue (dart:async/future_impl.dart:529:5)
I/flutter (22947): #
I/flutter (22947): [2020-08-24 17:34:30.604521Z][Vipsouq][AppState] Init Data Finish
I/flutter (22947): [2020-08-24 17:34:30.615410Z][Vipsouq][Category] getCategories
I/flutter (22947): [2020-08-24 17:34:30.632586Z][Vipsouq][wocommerce_api][20:34:30.631572] getAsync START [endPoint:products/categories?exclude=311&per_page=100&page=1&hide_empty=true&lang=en] url:https://vipsouq.com/wp-json/wc/v2/products/categories?exclude=311&per_page=100&page=1&hide_empty=true&lang=en&consumer_key=*********&consumer_secret=***************************
I/flutter (22947): [2020-08-24 17:34:30.742361Z][Vipsouq][wocommerce_api][20:34:30.742156] getAsync START [endPoint:products/tags] url:https://vipsouq.com/wp-json/wc/v2/products/tags?consumer_key=***************&consumer_secret=****************************
I/flutter (22947): [2020-08-24 17:34:30.756755Z][Vipsouq][wocommerce_api][20:34:30.756559] getAsync START [endPoint:products/attributes] url:https://vipsouq.com/wp-json/wc/v2/products/attributes?consumer_key=************************&consumer_secret=*******************************
I/flutter (22947): [2020-08-24 17:34:30.786180Z][Vipsouq][FCM]--> token: [ dyKrfGmrNqw:APA91bF0d4BhiND6y0D63J2C2SWS24GzaCCaNOS4PjRfbedcJH9keWUfPZqIHDgoMARt5Jsb78efRJXvQs-g_5BXlSPCuXagqt7ubV36pdeURUkb3vZzYnp46rBYUGM4upok6wGF3w82 ]
I/flutter (22947): [2020-08-24 17:34:30.811296Z][Vipsouq][AppState] build Theme
I/flutter (22947): [2020-08-24 17:34:31.199885Z][Vipsouq][AppState] init mobile modules ..
I/flutter (22947): [2020-08-24 17:34:31.206289Z][Vipsouq][AppState] register modules .. DONE
I/flutter (22947): [2020-08-24 17:34:31.266147Z][Vipsouq][MyConnectivity] online
I/flutter (22947): [2020-08-24 17:34:31.275201Z][Vipsouq][App] internet issue change: {ConnectivityResult.mobile: true}
I/flutter (22947): [2020-08-24 17:34:31.282270Z][Vipsouq][MyConnectivity] online
I/flutter (22947): [2020-08-24 17:34:31.282618Z][Vipsouq][App] internet issue change: {ConnectivityResult.mobile: true}
I/flutter (22947): [2020-08-24 17:34:32.498881Z][Vipsouq]screenName null
I/flutter (22947): [2020-08-24 17:34:32.565316Z][Vipsouq][tabbar] ============== tabbar.dart DASHBOARD ==============

══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
The following NoSuchMethodError was thrown during a scheduler callback:
The method '[]' was called on null.
Receiver: null
Tried calling: []("TabBar")

When the exception was thrown, this was the stack:
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      MainTabsState.loadTabBar (package:fstore/tabbar.dart:168:66)
#2      MainTabsState.afterFirstLayout (package:fstore/tabbar.dart:99:5)
#3      AfterLayoutMixin.initState.<anonymous closure> (package:after_layout/after_layout.dart:10:38)
#4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
#5      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1064:9)
#6      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:972:5)

════════ Exception caught by scheduler library #10     _invoke (dart:ui/hooks.dart:253:10)
#11     _drawFrame (dart:ui/hooks.dart:211:3)
(elided 3 frames from dart:async)
════════════════════════════════════════════════════════════════════════════════════════════════════
═════════════════════════════════════════════════════
The following NoSuchMethodError was thrown during a scheduler callback:
The method '[]' was called on null.
Receiver: null
Tried calling: []("TabBar")

When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      MainTabsState.loadTabBar (package:fstore/tabbar.dart:168:66)
#2      MainTabsState.afterFirstLayout (package:fstore/tabbar.dart:99:5)
#3      AfterLayoutMixin.initState.<anonymous closure> (package:after_layout/after_layout.dart:10:38)
#4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
...
════════════════════════════════════════════════════════════════════════════════

**Comment by vipsouq** [comment]
Please help as soon as possible as i dont have much time the app is live on google play and this has SO MANY ISSUES

**Comment by vipsouq** [comment]
The following NoSuchMethodError was thrown during a scheduler callback:
The method '[]' was called on null.
Receiver: null
Tried calling: []("TabBar")

**Comment by vipsouq** [comment]
this is the issue

**Comment by vipsouq** [comment]
![Screenshot_2020-08-26 Overview](https://user-images.githubusercontent.com/69245798/91303403-a400d600-e7b0-11ea-937a-447f8cabd93f.png)
 please resolve this

**Comment by vipsouq** [comment]
![Screenshot_2020-08-26 Overview(1)](https://user-images.githubusercontent.com/69245798/91303455-ba0e9680-e7b0-11ea-8960-54c797286eb9.png)

**Comment by tgloc96** [comment]
I ran the source code that I sent you a few days ago and I check that there was no error at all. Can you resend me full source code again so I can check it out for you.

**Comment by vipsouq** [comment]
> 
> 
> I ran the source code that I sent you a few days ago and I check that there was no error at all. Can you resend me full source code again so I can check it out for you.

I have sent you the source code please review it 

thanks

**Comment by vipsouq** [comment]
Also how to send notification to open a page in the application, Is there any guide for this

**Comment by vipsouq** [comment]
any updates on the bugs?

**Comment by minhcasi** [comment]
@vipsouq - could I know if you have checked this guide for the push notification - https://docs.inspireui.com/fluxstore/firebase ?

Please note the crashing could cause by many root causes, most of the reasons are from the missing data config or incompletely data, could you try to make more testing from the debug mode before release to the production app?

Please note that the default download app is working smoothly without crashing.

**Comment by vipsouq** [comment]
How to do that? in Debug?

**Comment by vipsouq** [comment]
I followed the Guide, The push notification is working, I'm asking is there any way to send push notification to land on the product page of the application?

**Comment by minhcasi** [comment]
Hi sir, thank you for quick response: 

- the deep-link push notification for product detail is not ready supported on fluxstore.

- you could try to check and test the app with the simulator (on debug mode) to see if there is any crashing issue

**Comment by vipsouq** [comment]
I try to use in simulator its working fine even the generated apk is working fine except for the Google play

**Comment by vipsouq** [comment]
i have sent the source code to @tgloc96 Still no reply please reply faster or take some action

**Comment by vipsouq** [comment]
I'm Losing business here, for Every day I'm sitting with this app, Please do something or pass some guide

**Comment by vipsouq** [comment]
> 
> 
> ![Screenshot_2020-08-26 Overview](https://user-images.githubusercontent.com/69245798/91303403-a400d600-e7b0-11ea-937a-447f8cabd93f.png)
> please resolve this

refer this and give solution

**Comment by vipsouq** [comment]
> 
> 
> ![Screenshot_2020-08-26 Overview(1)](https://user-images.githubusercontent.com/69245798/91303455-ba0e9680-e7b0-11ea-8960-54c797286eb9.png)

**Comment by minhcasi** [comment]
@vipsouq - the crash issue on your android due to to the Google Map issues, please try to double-check your google API key setting by using this guide - https://docs.inspireui.com/fluxstore/google-map/

Make sure to update the latest Fluxstore MV to compatible with flutter 1.20.x

Ref to original library guide could be helpful - https://pub.dev/packages/google_maps_flutter

**Comment by vipsouq** [comment]
The Google Map Api was configured correctly and working in apps installed in Emulator

I have made many changes in the app currently how to update to latest Fluxstore MV without losing the changes

**Comment by tgloc96** [comment]
> The Google Map Api was configured correctly and working in apps installed in Emulator
> 
> I have made many changes in the app currently how to update to latest Fluxstore MV without losing the changes

You can follow the [URL](https://medium.com/@inspireui/how-to-upgrade-fluxstore-projects-by-using-git-cebde7489ea6) for update your source code to the latest version.

**Comment by vipsouq** [comment]
> 
> 
> > The Google Map Api was configured correctly and working in apps installed in Emulator
> > I have made many changes in the app currently how to update to latest Fluxstore MV without losing the changes
> 
> You can follow the [URL](https://medium.com/@inspireui/how-to-upgrade-fluxstore-projects-by-using-git-cebde7489ea6) for update your source code to the latest version.

Its Saying Page not found

**Comment by tgloc96** [comment]
> > > The Google Map Api was configured correctly and working in apps installed in Emulator
> > > I have made many changes in the app currently how to update to latest Fluxstore MV without losing the changes
> > 
> > 
> > You can follow the [URL](https://medium.com/@inspireui/how-to-upgrade-fluxstore-projects-by-using-git-cebde7489ea6) for update your source code to the latest version.
> 
> Its Saying Page not found

https://medium.com/@inspireui/how-to-upgrade-fluxstore-projects-by-using-git-cebde7489ea6

It's still working normally.

**Comment by vipsouq** [comment]
no this URL

 https://gitlab.com/inspireui/fluxstore-pro
Please I'm New to gitlab

**Comment by vipsouq** [comment]
![Annotation 2020-09-01 104722](https://user-images.githubusercontent.com/69245798/91822498-9039f180-ec40-11ea-8e33-53830c94ab0a.jpg)

**Comment by tgloc96** [comment]
> no this URL
> 
> https://gitlab.com/inspireui/fluxstore-pro
> Please I'm New to gitlab
> 
> > **[Checking your Browser - GitLab](https://gitlab.com/inspireui/fluxstore-pro)**

Make sure to send the request to access the Gitlab after purchased the source.

**Comment by vipsouq** [comment]
how to?

> 
> 
> > no this URL
> > https://gitlab.com/inspireui/fluxstore-pro
> > Please I'm New to gitlab
> > > **[Checking your Browser - GitLab](https://gitlab.com/inspireui/fluxstore-pro)**
> 
> Make sure to send the request to access the Gitlab after purchased the source.
> 
> > **[Checking your Browser - GitLab](https://gitlab.com/inspireui/fluxstore-pro)**

**Comment by tgloc96** [comment]
> how to?
> 
> > > no this URL
> > > https://gitlab.com/inspireui/fluxstore-pro
> > > Please I'm New to gitlab
> > > > **[Checking your Browser - GitLab](https://gitlab.com/inspireui/fluxstore-pro)**
> > 
> > 
> > Make sure to send the request to access the Gitlab after purchased the source.
> > > **[Checking your Browser - GitLab](https://gitlab.com/inspireui/fluxstore-pro)**
> 
> > **[Checking your Browser - GitLab](https://gitlab.com/inspireui/fluxstore-pro)**
Please you submit form. Thank you.
http://gitlab.inspireui.com

**Comment by vipsouq** [comment]
submitted

**Comment by vipsouq** [comment]
Can you give the permission for this ASAP

> submitted

**Comment by minhcasi** [comment]
sent invitation - thanks

**Comment by minhcasi** [comment]
Let us know if you have any questions - thank you!

**Comment by vipsouq** [comment]
Yeah i have some questions I have changed some file in src/flutter 
Extended_raw_image to make the product aligned correctly but now everything is different after flutter upgrade -- force is done

Can i make the changes in the product image in flux store code itself if so, how?

I need the images to 200px height and width none

**Comment by vipsouq** [comment]
Hi,
 Please help me on this when i archive the build in xcode it is saying this error


I think this line shows the error:

Codepoint 58848 not found in font, aborting
