### ISSUE TITLE
how to activate Tap Payment Gateway?

### ISSUE THREAD

**Issue by saber93** [inspireui/support#4482]
Dear inspireui team,
Greetings,

Kindly find my questions below and please provide clearly references to help me solve my problems as soon as possible because I'm facing much more times and I didn't find any references for all issues;

1. How to reset the License code by using the Fluxbuilder tool.
2. How to buy another license code and\or multi-apps license code.
3. how to activate Tap Payment Gateway.

![Screen Shot 2020-08-06 at 2 12 41 AM](https://user-images.githubusercontent.com/45682263/89470999-1ec86980-d78e-11ea-8f0e-3c8798f94eb8.png)
![Screen Shot 2020-08-06 at 2 37 24 AM](https://user-images.githubusercontent.com/45682263/89471024-2851d180-d78e-11ea-9d64-586cb546c8b9.png)

**Comment by minhcasi** [comment]
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
Thank you for purchasing multi-product from us, I've updated the ticket as high priority support ⭐️

1. Please refer to this link to use Fluxbuilder to reset your purchase code - https://docs.inspireui.com/fluxbuilder/guide-to-use/#deactivate-the-purchase-code - it is supported to reset one time to help switching product from testing/develop into production mode.

2. You could purchase extra License from the Codecayon Fluxstore product.

3. Please enable Tap payment on this file
<img width="890" alt="Screen Shot 2020-08-07 at 08 37 23" src="https://user-images.githubusercontent.com/1459805/89599253-3a646a80-d889-11ea-92a0-dc49f9affc18.png">

**Comment by saber93** [comment]
Thank you for your support, 
Unfortunately I'm still facing some issues in my app;
1. Deactivate not showing because the old website not working now so FluxBuilder can't deactivate the code.
2. Mstore plugin updated today and no longer give me any message for the old activated website!
3. Login function giving me an error which I thought that it's regarding to activation code.

So if I may that you reset my purchase code from your end and help me to find out why this login error happened

![Screen Shot 2020-08-07 at 7 30 42 AM](https://user-images.githubusercontent.com/45682263/89609366-b0b49d00-d888-11ea-87f9-bbe12d49180a.png)

**Comment by saber93** [comment]
@minhcasi Please let me know about my issue as soon as possible

**Comment by minhcasi** [comment]
@saber93 - you could try to request the purchase code reset to support@inspireui.com - this issue could be related to the API issue - thanks

**Comment by saber93** [comment]
@minhcasi That's meaning if I could reset purchase code should login without issues?
- I have another issue for another app, please find screenshot below to help me fix it.

Thank you in advance for your kind efforts.

![Screen Shot 2020-08-07 at 11 25 22 PM](https://user-images.githubusercontent.com/45682263/89700503-5fb3b000-d93f-11ea-9b3b-a9ba1ec3fab6.png)

**Comment by minhcasi** [comment]
@saber93 - we have reset the code, please try again - thank you!

**Comment by saber93** [comment]
@minhcasi - Thanks for your support, code now working and API, but  user not completely login, it's infinite loading  until I press back then logout appears without user info;
kindly find attached screenshots;

![Screen Shot 2020-08-08 at 1 22 29 PM](https://user-images.githubusercontent.com/45682263/89707002-a58e6980-d97b-11ea-8a6d-99bfd810b43c.png)
![Screen Shot 2020-08-08 at 1 22 56 PM](https://user-images.githubusercontent.com/45682263/89707004-a9ba8700-d97b-11ea-9d29-0dee30d5c38c.png)
![Screen Shot 2020-08-08 at 1 24 48 PM](https://user-images.githubusercontent.com/45682263/89707005-aaebb400-d97b-11ea-9357-72a4b97e2504.png)

**Comment by minhcasi** [comment]
@saber93 - would you mind debug the request server after complete the SMS verify, it could cause by the request to register a new user? Try to add a breakpoint on this line:

<img width="936" alt="Screen Shot 2020-08-09 at 10 14 13" src="https://user-images.githubusercontent.com/1459805/89724104-163f8f80-da29-11ea-96a2-f9d55d718c0b.png">

**Comment by saber93** [comment]
@minhcasi - Thanks for your support, but this error happened for all login models, I remember that I met this error in previous version before. At the same time there is horrible performance totally rendering the app.
So please let me know if you have an update for this version as soon as possible.

**Comment by minhcasi** [comment]
we will update latest `1.7.7` in today - thank you!

**Comment by minhcasi** [comment]
@AmeerEbrahim - the latest version `1.7.7` is ready for download, please keep the update and let us know if you have any question - thank you!

**Comment by saber93** [comment]
Hello @minhcasi - I tried it, everything is working fine but facebook login, I followed video guide but there is something wrong;

Kindly find attached screenshot.

![Screen Shot 2020-08-15 at 11 28 33 AM](https://user-images.githubusercontent.com/45682263/90308401-505cd580-def0-11ea-8934-86c79fea7110.png)

Thanks.
