### ISSUE TITLE
Error when try to Build for upload to play store

### ISSUE THREAD

**Issue by macquack** [inspireui/support#4483]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
Error when try to Build for upload to play store

when I try this command line 
`flutter build appbundle`
or this
`flutter build apk --split-per-abi`
`FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Could not determine the dependencies of task ':app_settings:compileReleaseKotlin'.
> Failed to find Platform SDK with path: platforms;android-R            
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 3s                                                      
Running Gradle task 'bundleRelease'...                                  
Running Gradle task 'bundleRelease'... Done                         4.6s
Gradle task bundleRelease failed with exit code 1
mac@macs-Mac ios % 
`
+ Product & version:1.7.4
+ Flutter (or React Native) version: 1.17.1
+ Testing Device/Simulator: iPhone8
+ Screenshot issues (drag the file to attach here): 
![Screen Shot 2563-08-06 at 09 05 46](https://user-images.githubusercontent.com/30103694/89482414-0b37f580-d7c4-11ea-9574-04816a6844ac.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**
#4227 

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@macquack - pls try to use the latest Fluxstore version or refer to this solution to update build grade file - #3708

**Comment by macquack** [comment]
thanks it's work
