### ISSUE TITLE
Fluxstore Woocommerce Multi Stores, my new config is not showing on new build

### ISSUE THREAD

**Issue by gfunkerwin** [inspireui/support#4484]
Hi,

I made some adjustment to config_en.json and placed the file inside the web using mStore.api plugin but not showing any changes on the actual app.

Also, when the same config is edited using Android Studio same thing happened, then this part showed up (see pic)

<img width="950" alt="Screenshot 2020-08-06 at 12 53 28" src="https://user-images.githubusercontent.com/18148819/89496892-68906e80-d7e5-11ea-89fa-9b9c9f24cc88.png">

Please help, thank you

**Comment by minhcasi** [comment]
@gfunkerwin - there could be the incorrect format from config json, please share the file here so that we could help to quick check the issue

**Comment by gfunkerwin** [comment]
Hi @Minh <minh@inspireui.com>

Please find the attached config.json file for your perusal
<https://about.me/gfunkerwin?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=gmail_api>
Herwinto Chandra Sutantyo
about.me/gfunkerwin
<https://about.me/gfunkerwin?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=gmail_api>

**Comment by minhcasi** [comment]
@gfunkerwin - the config seems correct - would you mind to send the url and consume keys as well, we will check the API to see if there is any issue - thank you!

**Comment by gfunkerwin** [comment]
Hi @Minh <minh@inspireui.com>

Following is the URL https://direct2home.id

Consumer Key

ck_05414d6024a6f65aa01777dbe8a550a494ca54f0


Consumer Secret

cs_f1ec77c04bb4f637084bcf3e45a63b7aa61ada6d


Thank you
<https://about.me/gfunkerwin?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=gmail_api>
Herwinto Chandra Sutantyo
about.me/gfunkerwin
<https://about.me/gfunkerwin?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=gmail_api>

**Comment by gfunkerwin** [comment]
hi @Minh <minh@inspireui.com>

it works now for the wordpress site, but the same purchase code is taking a
long time when I input into FluxBuilder app, it just keep spinning
<https://about.me/gfunkerwin?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=gmail_api>
Herwinto Chandra Sutantyo
about.me/gfunkerwin
<https://about.me/gfunkerwin?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=gmail_api>

**Comment by minhcasi** [comment]
@gfunkerwin - there was some issue with our server to verify the code on yesterday, it's happened few hours - it should be worked as normal now, please help to check it again 👍

**Comment by minhcasi** [comment]
It seems working fine with your site, let us know if you have any issue :)

<img width="1431" alt="Screen Shot 2020-08-08 at 12 47 23" src="https://user-images.githubusercontent.com/1459805/89703479-55140d80-d975-11ea-8382-29edde5967f3.png">

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
