### ISSUE TITLE
Currency Exchange issues

### ISSUE THREAD

**Issue by kibbyboi** [inspireui/support#4486]
I need help to fix Currency exchange issues on the app, I have followed everything according to the instruction document but the currency exchange does not work on my app.

**Comment by ameenbadri7** [comment]
hello, @kibbyboi  welcome back.
Would you mind send us a screenshot for your issue?
Also, use our ticket template so we can know the most important details about your coding environment.
Thank you.

**Comment by ameenbadri7** [comment]
I'm sorry to close this ticket as there is no response or active conversation.

Please help to create a new one and link it to this ticket if the problem is not solved.

thank you for your time ❤️

**Comment by kibbyboi** [comment]
I really don't understand you guys, I reported this issue two weeks ago you
told me send screenshots, I sent you screenshots then you told me to create
an issue on GitHub, I did then you asking me to do the same things which I
did.

**Comment by kibbyboi** [comment]
Please reopen this

**Comment by kibbyboi** [comment]
Hello

**Comment by kibbyboi** [comment]
Hello

**Comment by kibbyboi** [comment]
Hello
