### ISSUE TITLE
How can I enable Multi Currency in FluxStore Multivendor

### ISSUE THREAD

**Issue by amitsahaiotait** [inspireui/support#4487]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: I want to enable multi-currency in my Fluxstore Multivendor Application. I already enable in profile page. But When I click on it currency is not changing. May I know what i need to do 
+ Product & version: Fluxstore Multivendor ( 1.7.6 )
+ Flutter (or React Native) version: Flutter
+ Testing Device/Simulator: OnePlus 7 Pro
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 

Thank you for your time!

**Comment by minhcasi** [comment]
@amitsahaiotait - pls check this guide https://docs.inspireui.com/fluxstore/customization/#9-product-advance-options - there is the config section allow to config multi-currency

**Comment by amitsahaiotait** [comment]
@ameenbadri7 I already submitted the proof. Please check & let me know.

**Comment by amitsahaiotait** [comment]
@minhcasi I follow this but this is only change my currency symbol not the value. I am asking for how can I change the value? Can you please help me to do that ?

**Comment by ameenbadri7** [comment]
you could use the [Currency Switcher](https://docs.inspireui.com/fluxstore/multi-language/#currency-switcher) to know more about implementing this feature.
you have to install the wpml plugin to have multi-currency inside your website.

please use our [documentation ](https://docs.inspireui.com/fluxstore/) to know more about the app.

Thank you.

**Comment by amitsahaiotait** [comment]
I am closing this issue but sorry to say I am not finding any good solution here. Documentation is not good. Hopefully you will improve your documentation very soon. 

thank you
