### ISSUE TITLE
purchase code

### ISSUE THREAD

**Issue by tozgan** [inspireui/support#4489]
Hi

purchase code is not activated.
Can you please help.

**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by ameenbadri7** [comment]
Hello, @tozgan 

don't worry we will fix your problem just please don't share the purchase code or screenshot public here as another user will use it for activation.
send us all the information privately to our email inspireui-team@inspireui.com.
Thank you.

**Comment by minhcasi** [comment]
pls send this request reset license to support@inspireui.com
