### ISSUE TITLE
[Listpro] lots of errors in 1.3 version

### ISSUE THREAD

**Issue by chad-the-first** [inspireui/support#449]
- Product: [Listpro]
 - Your Purchased Code: 65e47917-78fa-4b8e-97ec-80bf8345f72a

**Describe the bug**
lots of errors in the new version, for example when I click on a listing I get an error, when I click on the the map section I get an error, and I don't think that the home page is rendering in the way it meant to, because the categories are rendered in a weird colorful boxes. I was waiting for this version to fix the problems I had in the previous version, so please tell me when it will be fixed.

**Comment by chad-the-first** [comment]
I didn't give any details about my project because these error are happening even with the demo app

**Comment by minhcasi** [comment]
@chad-the-first - could you share the screenshot of the issues please, as it could be a cache from your Expo app? Thanks

**Comment by chad-the-first** [comment]
It's not cache problem because I cleared the cache and tried, and here is the screenshots from the main project, i didn't change a thing:
here you can the weird categories:
![Sketch](https://user-images.githubusercontent.com/17035853/55099655-c036aa00-50c8-11e9-9edd-5ca2fa9c7efb.png)

and here when I click on any listing under recent experiences I get this error:
![Sketch1](https://user-images.githubusercontent.com/17035853/55099804-0f7cda80-50c9-11e9-97ad-08063bb592f1.png)
![Sketch2](https://user-images.githubusercontent.com/17035853/55099839-1c013300-50c9-11e9-893d-539234aef3aa.png)

and when I enter the categories section and I click on any listing I get this error, and I get the same error when I click on the map section:
![Sketch3](https://user-images.githubusercontent.com/17035853/55099899-4226d300-50c9-11e9-92a8-786903e30e00.png)

**Comment by thangvo9x** [comment]
let me your email. We've hotfix.

**Comment by chad-the-first** [comment]
chadwebdev@gmail.com

**Comment by chad-the-first** [comment]
why closing the ticket while the issue still exists?!!
