### ISSUE TITLE
Use of unresolved identifier 'Auth'

### ISSUE THREAD

**Issue by tammam-963** [inspireui/support#4490]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by tammam-963** [comment]
https://testflight.apple.com/join/yEH1dEnS

i have already publish my app to test-flight then when i need to update the application i got library deprecated and so on how to resolve this issue

**Comment by ameenbadri7** [comment]
Hello, @tammam-963 welcome back.

You could three things as they may fix your problem :

1- [Clean the builds and update the pods](https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1).
2- Check if you have the latest update of the fluxstore multivendor also follow replaced the right field based on this [guide](https://docs.inspireui.com/fluxstore/sign-in/#2-google-sign-in), 
3- Also check if `import Firebase` is inside the header of `Runner\AppDelegate.swift` and you download the correct `GoogleService-Info.plist`.

Let us know if you still have problems.

Thank you.

**Comment by minhcasi** [comment]
pls try to share `library deprecated` screenshot issue here

**Comment by tammam-963** [comment]
**i got this error after i upgrade flutter**

../../Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:88:26: Error: Type 'DiagnosticableMixin' not found.
class PictureStream with DiagnosticableMixin {
                         ^^^^^^^^^^^^^^^^^^^
../../Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:192:44: Error: Type 'DiagnosticableMixin' not found.
abstract class PictureStreamCompleter with DiagnosticableMixin {
                                           ^^^^^^^^^^^^^^^^^^^
../../Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:88:7: Error: The type 'DiagnosticableMixin' can't be mixed in.
class PictureStream with DiagnosticableMixin {
      ^
../../Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:192:16: Error: The type 'DiagnosticableMixin' can't be mixed in.
abstract class PictureStreamCompleter with DiagnosticableMixin {
               ^
../../Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:167:11: Error: Superclass has no method named 'debugFillProperties'.
    super.debugFillProperties(properties);
          ^^^^^^^^^^^^^^^^^^^
../../Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:171:30: Error: The method 'toStringShort' isn't defined for the class 'PictureStreamCompleter'.
 - 'PictureStreamCompleter' is from 'package:flutter_svg/src/picture_stream.dart' ('../../Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart').
Try correcting the name to the name of an existing method, or defining a method named 'toStringShort'.
      ifPresent: _completer?.toStringShort(),
                             ^^^^^^^^^^^^^
../../Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:266:11: Error: Superclass has no method named 'debugFillProperties'.
    super.debugFillProperties(description);
          ^^^^^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception
Failed to build bundle.

**Comment by minhcasi** [comment]
@tammam-963 - we suspect the issue with later flutter `1.20.1.` which has just released a few days ago, we are checking the issue and get back you shortly

**Comment by minhtruong315** [comment]
@tammam-963 We released Fluxstore 1.7.7. it's working for flutter 1.20.1 well. please download Fluxstore 1.7.7 on codeanyon and update MStore Api plugin in the wordpress website as well

**Comment by minhcasi** [comment]
Confirmed fix on latest `1.7.7` - please keep update and let us know if you have any questions
