### ISSUE TITLE
Address Book in Fluxstore MV

### ISSUE THREAD

**Issue by GNAG1993** [inspireui/support#4491]
Hello, why don't you guys are showing address book option in the app, even you guys have imported the endpoints for shipping & billing address.

![shipping](https://user-images.githubusercontent.com/58203387/89540595-e1f68400-d81a-11ea-813b-eb954d4868ed.png)

for verification, please go through my other tickets with name GNAG1993

**Comment by minhcasi** [comment]
Duplicate of #4469 - pls give your all comment to that ticket
