### ISSUE TITLE
Have an issue in login with google, always getting user object null ?

### ISSUE THREAD

**Issue by benzhir** [inspireui/support#4492]
FluxStore Prestashop 1.7.6
Flutter v 1.17.5
Testing Device

Screenshot:
https://drive.google.com/file/d/1HBeJEDnFDJnr6df-euBjuwB-F2nbWrId/view?usp=sharing

**Comment by ameenbadri7** [comment]
Hello, @benzhir 
You could : 
- Update the mstore plugin and activate it again or completely remove it and then download the latest.
- Double-check this this [guide ](https://docs.inspireui.com/fluxstore/sign-in/#2-google-sign-in). 

let us know if you still have problems. 

Thank you.

**Comment by minhcasi** [comment]
@vumanhsn97 - please help to investigate this feature

**Comment by minhcasi** [comment]
@benzhir  - we have fixed this issue on the latest release `1.7.7` - let us know if you have any questions - thank you!
