### ISSUE TITLE
Fluxstore 1.7.6 - prestashop - Mobile app showing prices without Tax

### ISSUE THREAD

**Issue by benzhir** [inspireui/support#4493]
I have set tax class in opencart. The price in the e-commerce website is shown with tax added. The mobile app doesn't show the price with tax. As per regulation in my region, all prices to be displayed with tax. Is there a configuration to display price with tax ?

Tax is 20%.

**Comment by ameenbadri7** [comment]
Thanks for your report. Fluxstore doesn't support tax prices now. We will note it backlog and update it on the next release.
It's on our features requests list.

Please in the future, could you collect all your tickets to one ticket so we can help you more, don't open other tickets while you still have others not solve or collect them on one ticket!
Thank you.

**Comment by minhcasi** [comment]
noted as `feature quest` to investigate later

**Comment by minhcasi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update Tax](https://trello.com/c/UwRNZYGR/65-update-tax)

**Comment by minhcasi** [comment]
moved to backlog
