### ISSUE TITLE
Shipping bypass without selecting flat rate

### ISSUE THREAD

**Issue by FaizalAndro** [inspireui/support#4494]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: Shipping screen bypass without selecting flat rate
+ Product & version: 1.7.6
+ Flutter (or React Native) version: Flutter
+ Testing Device/Simulator: Both
+ Screenshot issues (drag the file to attach here): https://drive.google.com/file/d/1Aztjh_h1RuTnIjbq_DzO7i7YEKEUzMf1/view?usp=sharing

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**
Previous Ticket ID #4143

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by ameenbadri7** [comment]
Hi, @FaizalAndro 

 Thanks for your report. Our team will investigate this problem.

Thank you.

**Comment by FaizalAndro** [comment]
I m facing one more issue, I updated just now MStore Plugin to 1.7.9. When I enter purchase code to activate nothing happened either not showing any error and activating.

**Comment by FaizalAndro** [comment]
@ameenbadri7 @minhcasi @minhtruong315 , Please solve this shipping screen bypass issue. My customers able to place order without selecting flat rate shipping. In your previous code, it was selected automatically.

**Comment by minhtruong315** [comment]
@FaizalAndro I'm checking. I will let you know

**Comment by minhtruong315** [comment]
@FaizalAndro replace screens/checkout/shipping_method.dart and try again
[shipping_method.dart.zip](https://github.com/inspireui/support/files/5046645/shipping_method.dart.zip)

**Comment by FaizalAndro** [comment]
Hi @minhtruong315 , Thanks for your help. When I replaced there is 3 errors.
![Capture](https://user-images.githubusercontent.com/37078576/89725390-b5b25180-da2c-11ea-848b-4e90be150b05.PNG)
![Capture2](https://user-images.githubusercontent.com/37078576/89725391-b77c1500-da2c-11ea-8218-71c962392222.PNG)

**Comment by minhtruong315** [comment]
@FaizalAndro what is the Fluxstore version you're using?

**Comment by FaizalAndro** [comment]
1.7.6

**Comment by minhtruong315** [comment]
share me teamviewer

**Comment by FaizalAndro** [comment]
@minhtruong315 check skype

**Comment by FaizalAndro** [comment]
Thanks a lot @minhtruong315

**Comment by FaizalAndro** [comment]
Please help me in this variant issue as well, Marked price display as same regular price.
I created 3 variants, Small, Medium, Large. I set marked price same for all as Rs. 200. But it display selling price when it shows in listing
![InkedScreenshot_1597090415_LI](https://user-images.githubusercontent.com/37078576/89826958-9de5e500-db74-11ea-877f-e3fb057de280.jpg)

But when I open product then it's fine. 
![InkedScreenshot_1597090429_LI](https://user-images.githubusercontent.com/37078576/89827109-e0a7bd00-db74-11ea-91e0-d9d91413f6ad.jpg)

**Comment by minhtruong315** [comment]
@FaizalAndro this product is variant product.  in product detail, the price is showing by variation "S" correctly. but in product list screen, woo commerce api doesn't support to show the price by variation "S"

**Comment by FaizalAndro** [comment]
@minhtruong315 , ok got it brother. Again Thanks a ton for your amazing support.
