### ISSUE TITLE
Cash on delivery payment method

### ISSUE THREAD

**Issue by cenkgulgun** [inspireui/support#4495]
Thanks for everything. Adress, onboarding and default state is now working very well. I have a few question. 
1- After confirming the order on the payment screen, it switches the order status to pending. The method of payment is cash on delivery. When you select the payment cod , the order status should be processing.

2- Pageview is not working. I did as described but it doesn't work. I uploaded the screenshots.

3- It displays the prices of some products incorrectly on the main screen. It shows properly when it goes to the product page. As far as I understand, it shows the price incorrectly in variable products. I uploaded the screenshots.

4- How can i show onboarding always?

5- And finally, when opening the application, the splashscreen opens 2-3 seconds late. I am waiting about 2-3 seconds white screen. After splash screen is coming.

![IMG_1354](https://user-images.githubusercontent.com/68585317/89506743-3d515380-d7d4-11ea-9c47-93ddc45a271e.jpg)
![Screenshot_1](https://user-images.githubusercontent.com/68585317/89506801-4fcb8d00-d7d4-11ea-9cf7-80bfbf2f2c67.png)

![InkedIMG_1355_LI](https://user-images.githubusercontent.com/68585317/89507094-b81a6e80-d7d4-11ea-8362-fded005a9010.jpg)
![InkedIMG_1356_LI](https://user-images.githubusercontent.com/68585317/89507112-be104f80-d7d4-11ea-9f8d-0f4a9b1f3dd1.jpg)

_Originally posted by @cenkgulgun in https://github.com/inspireui/support/issues/4457#issuecomment-669778795_

**Comment by ameenbadri7** [comment]
1- update the inside `lib\common\config\payments.dart`  on :
```
/// Enable update order status to processing after checkout by COD on woo commerce
  "UpdateOrderStatus": true,
```
2- could you double check our [guide ](https://docs.inspireui.com/fluxstore/customization/#12-page-view-settings-screen).

3- this problem happens with the variable products on the wpml plugin when the customer changes the language. I guess that our team will fix it in the next release. 

4- refer to this [ticket ](https://github.com/inspireui/support/issues/4448) to solve your issue.

5- my advice to you: use fewer plugins, use CDN, convert the images to webp.  also check out [performance notes](https://docs.inspireui.com/fluxstore/performance/). 
hope this help you.

Please notes that we don't take customization requests for the regular license but you can buy the Extended License or Support Pack, please help to check our [Support Policies](https://inspireui.com/support-policies) 
and email us with your request.

You could help us by giving your feedback/rating to [Codecanyon Market website](https://codecanyon.net/downloads), 
we are working hard to update more awesome and powerful features on the next coming version release. 
Let us know if you have any feedback. 

Thank you.

**Comment by ameenbadri7** [comment]
I'm sorry to close this ticket as there is no response or active conversation.

Please help to create a new one and link it to this ticket if the problem is not solved.

thank you for your time ❤️
