### ISSUE TITLE
FluxShopify problem with coupon code in cart.

### ISSUE THREAD

**Issue by akshaykumar04** [inspireui/support#4496]
Anything that is being entered in the coupon code field gets applied after pressing the apply button and the total cart amount goes into negative. 
+ FluxShopify 1.7.2
+ Flutter version 
+ Tested on OnePlus 6T 
+ Screenshot :

![fluxshopify](https://user-images.githubusercontent.com/25170390/89595655-b901dd80-d872-11ea-8cbe-f0e88d3f1403.jpeg)

**Comment by ameenbadri7** [comment]
Please make all your tickets inside one ticket so we can help you much faster, please close the other ticket!

Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 

Thank you for your time!

**Comment by akshaykumar04** [comment]
okay I will merge it with other ticket

**Comment by akshaykumar04** [comment]
merged with #4497
