### ISSUE TITLE
FluxShopify issue with product variation in recentview and wishlist.

### ISSUE THREAD

**Issue by akshaykumar04** [inspireui/support#4497]
**ISSUE 1**
Opening any product from recent view or wishlist and then adding it to cart will give null id error on pressing the checkout button on cart page. This is happening because the json method `toJson()` that is being used to save recent view and wishlist items locally is not containing  `"List<ProductVariation>"` ` "variants": variations,` thus after the app is launched again the method used to populate recent view and wishlist `fromLocalJson()` is giving "Instance of Variation" as null.
+ FluxShopify 1.7.2
+ Flutter version 
+ Tested on OnePlus 6T 
+ Screenshot :

![fluxshopify 2](https://user-images.githubusercontent.com/25170390/89596356-8ce75c00-d874-11ea-924b-9b95714e4671.jpeg)

**ISSUE 2**

Anything that is being entered in the coupon code field gets applied after pressing the apply button and the total cart amount goes into negative.

![fluxshopify](https://user-images.githubusercontent.com/25170390/89597840-e18cd600-d878-11ea-8a28-34d865d33eb3.jpeg)

**Comment by akshaykumar04** [comment]
edit: merged with #4496

**Comment by minhcasi** [comment]
@akshaykumar04 - please help us to submit the form again http://verify.inspireui.com/ as the PDF License is empty with our checking, there could be a network issue - thank you for your time

**Comment by akshaykumar04** [comment]
@minhcasi filled again..

**Comment by minhcasi** [comment]
@akshaykumar04 - thank you for quick response, it's verified 👍

@luyx2412 - pls help to investigate this issue

**Comment by luyx2412** [comment]
Hi @akshaykumar04 Sorry about reply you late, we are investigating about the variant issue. Let me mention you when resolve it.

Thanks

**Comment by akshaykumar04** [comment]
@luyx2412 Thanks and let me know when the issue gets resolved

**Comment by akshaykumar04** [comment]
@luyx2412 any updates?

**Comment by luyx2412** [comment]
Hi @akshaykumar04 I just invited you to the latest FluxShopify repo which fixed the issue. So please pull latest code and merge with your project.

Thanks

**Comment by akshaykumar04** [comment]
Thanks @luyx2412, As I can check I have been assigned guest role in the repo & gitlab doesn't allow guest users to view/pull code from private repo. Please check

**Comment by luyx2412** [comment]
Hi @akshaykumar04 Sorry about the issue, i just changed your role. So please check the repo again.

Thanks

**Comment by akshaykumar04** [comment]
@luyx2412 @minhcasi I have checked the repo & found that both the issues are still there, re-open the app again & add items to cart from wishlist and recent view will show error "id" null error, also I am still facing coupon code error.
Please Check

**Comment by luyx2412** [comment]
Hi @akshaykumar04 Can you give me the specific issue screenshot or video? 

Thanks

**Comment by akshaykumar04** [comment]
Hi @luyx2412 Screenshots I've already uploaded, I will send you a video shortly

**Comment by akshaykumar04** [comment]
@luyx2412 @minhcasi  Please refer to this video for detailed info https://youtu.be/wYKIamOgEXE

**Comment by akshaykumar04** [comment]
@luyx2412 any updates?

**Comment by luyx2412** [comment]
Hi @akshaykumar04 Please pull latest code in Fluxshopify repo and recheck again, or clone only this repo and check about it. Because i just tested and it worked normal.

Thanks

**Comment by akshaykumar04** [comment]
@luyx2412 okay thanks I will check again, please add me again on gitlab

**Comment by minhcasi** [comment]
@akshaykumar04 - pls also submit on this link http://gitlab.inspireui.com/ - thank you!

**Comment by minhcasi** [comment]
Let us know if you have any issue - thanks

**Comment by akshaykumar04** [comment]
please investigate about the ISSUE 1

**Comment by luyx2412** [comment]
Hi @akshaykumar04 Can you send your project via inspireui.team@gmail.com. Let me investigate about it, because in my side did not exist this issue.

Thanks

**Comment by akshaykumar04** [comment]
Okay I will send you shortly

**Comment by luyx2412** [comment]
Closed! Because no longer response.

P/S: Feel free to open new issue.

Thanks
