### ISSUE TITLE
Fluxbuilder loading licence

### ISSUE THREAD

**Issue by avineshkumar2** [inspireui/support#4498]
Hi

I am trying to activate my licence on the fluxbuilder but the Loading.. keeps showing and the licence does not seem to get activated.

![image](https://user-images.githubusercontent.com/1459266/89603073-546b7080-d8bc-11ea-8d05-b08618acd61c.png)

Please assist.

regards
avinesh

**Comment by ameenbadri7** [comment]
Please send this request reset license to support@inspireui.com.

Thank you

**Comment by minhcasi** [comment]
@avineshkumar2 - there was an issue with the server in 1-2 hours- you could active now - thank you

**Comment by avineshkumar2** [comment]
Hi

I am still not able to activate.

Please assist.

Avinesh Kumar
