### ISSUE TITLE
[ListApp] Category & Custom Taxonomy Issue

### ISSUE THREAD

**Issue by rontiew** [inspireui/support#450]
**Mandatory Info (please complete the following information):**
 - Product: Listapp
 - Your Purchased Code: ed662c70-7bca-4607-b606-aceb3eafe343
**Describe the issues**
Hi, I have just purchased Listapp and have few issues:
1. I would like to use Listing Type or categories to show listing on Listapp, Im trying to use categoryListingId and TypeId, but it seems like both are not working, and it will show all my latest listings when using these, may I know why?

2. I have custom taxonomy and would like to show it on Listapp, but when I click enable on my wordpress site, after click save it will disable again, may I know the reason too?

3. May I know how to set the menu as transparent without showing the white bar like demo app?

4. May I know how to link to Listing/search page on Home page like "Browse More Places"?

5. Whenever I click Category on Search/Map page, it will show all listings, but not the specific listings, is it I have any misconfigure?

Hopefully I can get your replied as soon. Thank you. :)

**Screenshots**

**Additional context**
Add any other detail logs about the problem here.

**Comment by thangvo9x** [comment]
Hi. Thanks for your choice.
1. I would like to use Listing Type or categories to show listing on Listapp, Im trying to use categoryListingId and TypeId, but it seems like both are not working, and it will show all my latest listings when using these, may I know why?
=> Send AppConfig.json such as your theme on MyListing/Listify/Listable.js in Config folder.
2. I have custom taxonomy and would like to show it on Listapp, but when I click enable on my wordpress site, after click save it will disable again, may I know the reason too?
=> I don't understand your this problem, brief more ...
3. May I know how to set the menu as transparent without showing the white bar like demo app?
=> You can edit it in Components/Toolbar/index.js
4. May I know how to link to Listing/search page on Home page like "Browse More Places"?
=> You can fix it Navigation/HomeScreen.index at onViewMap={...}
5. Whenever I click Category on Search/Map page, it will show all listings, but not the specific listings, is it I have any misconfigure?
=> Same 1. Send AppConfig.json such as ...
Thanks

**Comment by rontiew** [comment]
Hi, thank you for your replied.

1 & 5. Kindly refer to the attachments for the AppConfig.json & MyListing.js.
[Listapp.zip](https://github.com/inspireui/support/files/3019441/Listapp.zip)

2.  My listing have the custom taxonomy like Services, Food Type, Payment, Cuisine etc, I would show all of these on listing content at ListApp, it is possible to enable it via Rest API controller, right? But after I enable and click save, it will not enable too, may I know how to enable to show it on my listing details?

You may see my screenshot for the details:
![Screenshot 2019-03-29 01 42 26](https://user-images.githubusercontent.com/20296186/55180216-19373880-51c4-11e9-8e9a-8ed94ed5257f.png)

3. I have checked it, the background color is transparent, but on Home page toolbar, it is still showing with white color bar, may I know how to remove it? I mean on homepage, not listing page.

4. May I know how could I fix it on onViewMap={...}? What i need to do to enable it?

5. Is it possible I can show first image from my gallery on listings/home page (banner or 2/3 column listings layout)? As currently I do not have feature image on my over 100 listings, I wish it can show my first image instead of feature image.

Together I attached the JWT setting for your checking, is it I do it correctly?
[JWT.zip](https://github.com/inspireui/support/files/3019482/JWT.zip)

Thanks. :)

**Comment by rontiew** [comment]
Hi, any update? Thanks.

**Comment by thangvo9x** [comment]
I checked your AppConfig.
1. Please go to Tools->rest api controller -> enable job_listing_category. if your site has.
2. Our app can't not get them in listing detail
3.4.5. This is out of scope supporting. 
Thanks

**Comment by minhcasi** [comment]
@rontiew it will be displayed from the JSON listing detail - https://gyazo.com/b2f1d7afd46419705478451ce3e09225

and you can map these listing detail data into your config file - https://gyazo.com/bc804f55bd088c8350cbed1c6b29d31d

Then it will display automatically on the app UI
