### ISSUE TITLE
home screen categories error in mstore mv react

### ISSUE THREAD

**Issue by kevadiya** [inspireui/support#4501]
hello sir,

I have an issue in mstore mv react.
when i run app with "expo start" command then i have scan qr code and javascript bundle build 100%. 

after of that it gives me this screen shot error.
![bfeb26e8-0758-479c-91f4-1e81ba7c6e3a](https://user-images.githubusercontent.com/4812340/89613638-56273b00-d8a0-11ea-91ba-1e2d11f7dda3.jpg)

how can i resolve them

please reply me as soon as possible.

**Comment by minhcasi** [comment]
@kevadiya - could you give your comment on this option ticket #4470 ? - pls help to open one ticket for your all issue - thank you for your time
