### ISSUE TITLE
 problem to upload APK to google play I need to update android API to 29 and fluxstore is in API 28

### ISSUE THREAD

**Issue by victor1409** [inspireui/support#4502]
trying to solve this I get the following error when I run the command:  flutter build appbundle

<img width="1064" alt="Captura de Pantalla 2020-08-07 a la(s) 1 42 52 a  m" src="https://user-images.githubusercontent.com/67571967/89617250-7da1e780-d84f-11ea-808c-db79f75e0d49.png">

**Comment by victor1409** [comment]
@minhcasi 
can you help me with this i just need this to compile my project on android

**Comment by victor1409** [comment]
<img width="964" alt="Captura de Pantalla 2020-08-06 a la(s) 10 25 32 p  m" src="https://user-images.githubusercontent.com/67571967/89621799-93b3a600-d857-11ea-88fd-b05b85e9c984.png">

**Comment by victor1409** [comment]
<img width="1059" alt="Captura de Pantalla 2020-08-07 a la(s) 3 12 32 a  m" src="https://user-images.githubusercontent.com/67571967/89624450-dd9e8b00-d85b-11ea-977a-f7e982011f42.png">

**Comment by victor1409** [comment]
since last August 3, 2020 the android API needs to be at least 29

**Comment by minhcasi** [comment]
@tgloc96 - pls help to check this issue - it could be related to latest Flutter update `1.20.x` - thanks

**Comment by victor1409** [comment]
@minhcasi @tgloc96 , Hello Can I help me with this today???

**Comment by victor1409** [comment]
@tgloc96 @minhcasi Guys I need your help today with this please

**Comment by victor1409** [comment]
@minhcasi @ameenbadri7 ?

**Comment by minhcasi** [comment]
we're checking the issue and will get back today - thx

**Comment by edailton** [comment]
Same here, flutter on version 1.20.1

**Comment by victor1409** [comment]
@edailton 
down to the previous version, flutter downgrade command

**Comment by victor1409** [comment]
@edailton 
go back to the previous version comand:  flutter downgrade

**Comment by edailton** [comment]
@victor1409 thank you, solved for me.
