### ISSUE TITLE
Issues on Mstore Opencart App

### ISSUE THREAD

**Issue by walexanderos** [inspireui/support#4507]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 

i. I get "Cant get data from server " error when trying to load categories/products
ii. Server don't respond correctly when trying to register or login
iii. Login form is being pushed up when typing

+ Product & version:  Mstore Opencart v1.2.0
+ Flutter (or React Native) version:  React Native
+ Testing Device/Simulator:  Android Device
+ Screenshot issues (drag the file to attach here): 
![image](https://user-images.githubusercontent.com/36700043/89628126-c3809f00-d893-11ea-9116-b7ea5479e5b6.png)
![WhatsApp Image 2020-08-07 at 9 58 29 AM](https://user-images.githubusercontent.com/36700043/89628810-bf08b600-d894-11ea-9ae6-c6b4091cbd39.jpeg)
![WhatsApp Image 2020-08-07 at 9 58 29 AM (1)](https://user-images.githubusercontent.com/36700043/89628815-c039e300-d894-11ea-90a0-e5705c7585cd.jpeg)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 

Thank you for your time!

**Comment by minhcasi** [comment]
@walexanderos - this product is already refunded, pls provide other proof of purchase License - thanks

**Comment by walexanderos** [comment]
@minhcasi I think there is a mix up somewhere. The refunded product is the woocommerce version of mstore. The refund was used to purchase the opencart version of mstore. The submitted license is the only proof of purchase I have

**Comment by laoluolapegba** [comment]
@minhcasi and @ameenbadri7 
My colleague has filled the form, we have no feedback from you.
![image](https://user-images.githubusercontent.com/9108901/89734933-f45d0180-da56-11ea-99c2-1c00cc00c1a4.png)

The image above is a screenshot of our Envato download page. the MStore product is NOT the refunded one. We purchased the wrong product and the refund was used to purchase the opencart Mstore.
This issue affects our customers and If we do not get a response from you in 24 hours, you leave me no choice but to seek redress from directly from envato/ themeforest.
Regards.
