### ISSUE TITLE
Cannot install app while on archive build

### ISSUE THREAD

**Issue by kirancchand** [inspireui/support#4509]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 
App is working fine on android device and Simulator.But when i try device on real ios device It opens and close automatically,Previously It shows unable to install app.

I took a direct run build to a real device, and that time it is working and app is installed on my phone. But when I open the same app after disconnecting the connection between phone and Xcode, or when open after killing the direct run, it is simply opening the app and immediately closing. And showing no errors.
And I took an archive build, using diawi.com I convert .ipa file into a link, and when I try to install the app, after showing the animation of downloading and installing the app turns to a disable look(app icon changed to grey color) and when I open the app it says, cannot install the app. I don't know why it is happening. I tried through Automatically and manually code signing style. But in both case I'm getting this issue. But when I run a simulator there is no issue. Please help me to fix this.

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@kirancchand - could you share some screenshots issues so that we could understand more on the problem

**Comment by hilajqinnovation** [comment]
Please see the attached Image for more info of the issue.

![WhatsApp Image 2020-08-02 at 1 41 59 PM](https://user-images.githubusercontent.com/34735898/89715773-db584000-d9c5-11ea-99e3-ed26cbeb48e2.jpeg)
![WhatsApp Image 2020-08-05 at 10 25 11 PM](https://user-images.githubusercontent.com/34735898/89715782-e90dc580-d9c5-11ea-8973-00145036c429.jpeg)

**Comment by minhcasi** [comment]
@kirancchand - we have not tried this method `archive build, using diawi.com I convert .ipa file into a link` and not recommend to test by this way.

- You could test on real device with the debug mode by plugin the iphone device into macbook and run directly from Android Studio.
- To build with archive mode, make sure to run `flutter build ios` and update your bundle id, Signing with your Apple Developer Account and upload to Test Flight - ref detail from our document https://docs.inspireui.com/fluxstore/delivery/
