### ISSUE TITLE
[Mstore multiverndor app] Login , Language issue and others

### ISSUE THREAD

**Issue by MrFaisal100** [inspireui/support#451]
**Required Info (please complete the following information):**
 - Product: Mstore Multivendor 
 - Your Purchased Code: bd25c21b-0cdc-49dc-9b41-42c9c9071557
(we may not reply if you are not our customer)

**Describe the bug**
1. I can login as a vendor but cannot as a client? I tried with several accounts without success
2. I set the default language as ar and rtl is default.. but it did not work in a newly installed emulator
3. I translated some texts in the ar in the languages.js but it is not reflected in the app

**questions**
4. I want to hide the add new product option for the vendor and all related vendor option how to do that.
5. I want to hide facebook login (where is the file to hide the UI)
6. I want to remove product description, vendor, reviews) from the product details page
7. under categories I want to add the seller name under the product (in which page)
8.  the app did not get all payment methods I have .. what should I do to add mine  

**Screenshots**

**Additional context**
Add any other detail logs about the problem here.
If possible please share your config.js that use for the app setting

**Comment by thangvo9x** [comment]
Bugs:
1. If you create an account on your website. you must change password before login on your app.
2. Try move ar: {...} to first in list.
3. Send AppConfig file . We'll check help you.
Q & A : 
4. You must edit code. send email to support@inspireui.com and brief your requirements.
5. You can remove it in Container/Signin/index.js and remove a block with facebook login
6. same as 4.
7. Go to Container/Categories/index.js
8. Send AppConfig such as your crediential on your website.
Thanks

**Comment by MrFaisal100** [comment]
thanks a lot for this prompt response 
here is the app config
[AppConfig.json.zip](https://github.com/inspireui/support/files/3017318/AppConfig.json.zip)

**Comment by MrFaisal100** [comment]
Hi,
9. I want to show the shopping cart in the bottom menu  as in the demo app
how can I do that

**Comment by MrFaisal100** [comment]
also
I want to remove
about us and contact us from the drawer menu
from which page is that

**Comment by MrFaisal100** [comment]
Hi ???

**Comment by MrFaisal100** [comment]
I would appreciate your feedback
