### ISSUE TITLE
Google Play reject App because of webview

### ISSUE THREAD

**Issue by Yusadolat** [inspireui/support#4511]
**_Step 1 (require): describe detail issues & screenshots_**
Hello, How do I fix the Google rejection on my App? They claim the rejection is based on the fact that the App Uses Webview
+ Detail Issues: 
+ Product & version: 3.0.7
+ Flutter (or React Native) version:  React Native
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 
![Screen Shot 2020-08-07 at 11 33 37 AM](https://user-images.githubusercontent.com/10975011/89637557-414ba700-d8a2-11ea-87e1-89daf384a867.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@Yusadolat - could you try to share some screenshot of the app?

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
