### ISSUE TITLE
Problem in Fluxstore integration with Magento Site: (Rest Api is not connected) 

### ISSUE THREAD

**Issue by ShahnazABH** [inspireui/support#4512]
Our magento site is configured with the FluxstorePro-1.7.6. On connecting in Fluxbuilder-v1.0.6, it is showing the error as shown in the attached screenshot. Looking forward for some support. Thank you!

<img width="708" alt="Screenshot (42)" src="https://user-images.githubusercontent.com/61077992/89604397-07d25780-d820-11ea-822a-34366b065034.png">

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 

You can try to fix your problem by double-checking our [guide  ](https://docs.inspireui.com/fluxstore/magento-setup/) to config your site.

Thank you for your time!

**Comment by ShahnazABH** [comment]
@ameenbadri7 Please note that i have already submitted the form and please check and confirm.

**Comment by minhtruong315** [comment]
@ShahnazABH can u send me your hosting account via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/4512

**Comment by minhtruong315** [comment]
Hi @ShahnazABH we released Fluxstore Pro 1.7.7. please check your config website on that version.
