### ISSUE TITLE
Fluxstore prestashop app issue -- bottom overflow, 

### ISSUE THREAD

**Issue by nucl123** [inspireui/support#4513]
Hi,
We just purchased fluxstore prestashop app and tried to run it , however, there is issues with some UI elements as shown in the below screenshot.
Also, in fluxstore pro same issue is occurring for some elements like category icons.
Please check and let us know asap.

![image](https://user-images.githubusercontent.com/51371138/89642754-128efa00-d8bd-11ea-979d-e250b0e295cd.png)

**Comment by ameenbadri7** [comment]
Could I comfort that you are using the latest version?
 and please could you edit your ticket to be like our main ticket template so we know more about your problem.

Thank you

**Comment by minhcasi** [comment]
@nucl123 - pls help us to send the proof purchase for Fluxstore Prestashop again - http://gitlab.inspireui.com/ - thank you!

**Comment by nucl123** [comment]
@minhcasi  done
![image](https://user-images.githubusercontent.com/51371138/89705666-be8d1f80-d967-11ea-9ccb-55016488de48.png)

**Comment by nucl123** [comment]
@ameenbadri7 

> Could I comfort that you are using the latest version?
> and please could you edit your ticket to be like our main ticket template so we know more about your problem.
> 
> ```
> **_Step 1 (require): describe detail issues & screenshots_** >> ### **Issue as per the attached screenshot above, the layout is messed up, on the first run of the app itself, no changes made in the freshly downloaded file**
> + Detail Issues: 
> + Product & version: **Fluxstore prestashop latest version as already mentioned above.  Version: 1.7.6** 
> + Flutter (or React Native) version:  **Flutter 1.17.5**
> + Testing Device/Simulator: **Both Simulator (geny motion , tried with all latest 4 android api versions) and device (samsung galaxy - s9)**
> + Screenshot issues (drag the file to attach here):  **check above**
> ```
> 
**### Waiting for a urgent fix**

**Comment by minhcasi** [comment]
@vumanhsn97 - please help to suggest on this issue - thank you!

**Comment by vumanhsn97** [comment]
@nucl123 
Can you zip app folder and send to vumanhsn97@gmail.com?

**Comment by minhcasi** [comment]
@nucl123 - we have fixed this issue on the latest release `1.7.7` - let us know if you have any questions - thank you!
