### ISSUE TITLE
Blank Screen

### ISSUE THREAD

**Issue by attare026** [inspireui/support#4514]
When I go **'lib/config/config_en.json'** path app was working perfectly
then I replace like that **https://mywebsiteurl/uploads/2000/01/config.json** my screen was blank 
I use Latest version on this source code
check video **https://streamable.com/b11ztl**

**Comment by ameenbadri7** [comment]
did you change the path inside `lib\common\config\general.dart`

`const kAppConfig = 'lib/config/config_en.json';
`
to this
`const kAppConfig = 'https://mywebsiteurl/uploads/2000/01/config.json';

you can fix this issue by going to our [documentation site](https://docs.inspireui.com/fluxstore/config/).

Thank you

**Comment by attare026** [comment]
```
Future<Map> loadAppConfig({isSwitched = false}) async {
    try {
      if (!isInit) {
        await getConfig();
      }
      final LocalStorage storage = LocalStorage('builder.json');
      var config = await storage.getItem('config');
      if (config != null) {
        appConfig = config;
      }

```
if I use **true** this line **{isSwitched = false}**
Same Problem I was facing the blank screen 
My website gets me this data const **kAppConfig = 'https://mywebsiteurl/uploads/2000/01/config.json';**
How can I fixed it?

**Comment by ameenbadri7** [comment]
you can use our guide and upload the config file to surge.sh 
see the common question here 
https://docs.inspireui.com/fluxstore/common-issues/#-open-app-after-uploading-nowsh-web

I just try it it's working perfectly fast.

**Comment by attare026** [comment]
Thanks For your support Razorpay is not working after save my keyId
when I check it code 
![razorpay](https://user-images.githubusercontent.com/34741721/89741018-94467980-daaf-11ea-92d7-0b201c7176ab.png)

here code is a comment
how can I fix it?

**Comment by attare026** [comment]
Hey any solution??

**Comment by ameenbadri7** [comment]
please could you double-checking this guide https://docs.inspireui.com/fluxstore/multi-payment/ before trying anything else?

Thank you.

**Comment by attare026** [comment]
> please could you double-checking this guide https://docs.inspireui.com/fluxstore/multi-payment/ before trying anything else?
> 
> Thank you.
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/c1f5c35bdee2cf5a71b0e35ef38becdf8ec89d72/68747470733a2f2f646f63732e696e737069726575692e636f6d2f696d616765732f6d6574612f47686f73742d446f63732e6a7067">InspireUI Document**[FluxStore - Universal mobile commerce Flutter app for Magento, WooCommerce and Opencart](https://docs.inspireui.com/fluxstore/multi-payment/)**Fluxstore is universal app that fully integration with the Woocommerce, Mangeto and Opencart

If I want active what should do?

**Comment by attare026** [comment]
@minhcasi bro help me to active native Razorpay oppestion

**Comment by minhcasi** [comment]
ok, i will make the detail Blog post - thank you!

**Comment by attare026** [comment]
> ok, I will make the detail Blog post - thank you!

Waiting for your blog post! Gives me a link also this description!

**Comment by attare026** [comment]
@minhcasi how to remove header and footer on webview checkout?

**Comment by minhcasi** [comment]
@attare026 - you could try to update the JS/CSS from the Webview Payment widget

<img width="1025" alt="Screen Shot 2020-08-15 at 10 59 02" src="https://user-images.githubusercontent.com/1459805/90304871-564db900-dee6-11ea-9037-77f1c02d32ba.png">

Please follow up the Blog Post here - https://medium.com/@inspireui - we will update the guide for Razorpay
