### ISSUE TITLE
Product variation Fluxstore bug

### ISSUE THREAD

**Issue by samik9** [inspireui/support#4515]
Hello, I found a bug with product variations, I understand the whole concept and I noticed that in this example I did not create a ** amarillo**  color  with  **M** Size, but on the app it shows app like normal. Also Wordpress allows to select a default variation when product page loads but Is not working neither. 
![Editar producto - Mood Style 2020-08-07 18-10-58_2000x1139](https://user-images.githubusercontent.com/50071744/89695529-e9c92d80-d8d9-11ea-8d7a-b9e87e1d6fd3.jpg)

**Comment by minhcasi** [comment]
noted with investigating this issue - thank you for reporting @samik9

**Comment by philipvu30** [comment]
Hi,

Please send your config.dart + config_en.json to my email: toan@inspireui.com.

Thank you.

**Comment by samik9** [comment]
@philipvu30  @minhcasi  email sent, thank you

**Comment by samik9** [comment]
Also the position of the sizes and colors on the WooCommerce does not match with the app
<img width="729" alt="image" src="https://user-images.githubusercontent.com/50071744/90196137-ac104d00-dd90-11ea-97aa-7dfa2faf1ab2.png">

**Comment by minhcasi** [comment]
@tgloc96 - please help to investigate this issue - thank you!

**Comment by minhcasi** [comment]
@samik9 - sorry to disturb you, we confirm to fix this bug on the latest code of our git but would like to test this case again on your site. 

Would you mind to share the admin login and your latest `config.dart` file so that we could test and confirm if it is fixed - thank you for your time!

**Comment by samik9** [comment]
@minhcasi hi! Where I can send the wp login details?

**Comment by samik9** [comment]
@minhcasi i sent email to minhcasi@gmail.com

**Comment by minhcasi** [comment]
@samik9 - thank you for quickly response 

@simonpham - pls help to investigate this issue

**Comment by simonpham** [comment]
@samik9 I'm checking this issue. I will get back to you ASAP.

**Comment by simonpham** [comment]
Hi @samik9, please send us your latest `config.dart` to `inspireui.team@gmail.com`. The sent file is not matched with your site info.

**Comment by samik9** [comment]
Hello @simonpham i just sent the email , please check

**Comment by simonpham** [comment]
Hi @samik9, we tried with your config file but it doesn't work. Please Run it to make sure you have the correct consumerKey & consumerSecret. For more convenient, please send us both `lib/common` folder & `lib/config` folder. Thank you!

**Comment by samik9** [comment]
@minhcasi @simonpham i just sent you email. Please check  ![image](https://user-images.githubusercontent.com/50071744/90471082-d3458200-e0e2-11ea-85f0-3684a7ee0ec9.jpeg)

**Comment by simonpham** [comment]
@samik9 
We have checked and confirm [this bug](https://github.com/inspireui/support/issues/4515#issue-675338984) exists in our latest code. It will take us time to fix this bug. We will get back with you in a few days.

About [the position of the sizes and colors](https://github.com/inspireui/support/issues/4515#issuecomment-673754704), we have checked the API, it only supports positioning by id (example: from smallest value to largest value). Ids are the number like below screenshot:
![image](https://user-images.githubusercontent.com/8846657/90483827-8b187500-e15f-11ea-9091-6b74afdb2ead.png)

Thank you for your support.

**Comment by samik9** [comment]
Thank you , I hope this can be solved soon

**Comment by samik9** [comment]
@minhcasi  @simonpham  can i get beta future versions to help finding issues?

**Comment by minhcasi** [comment]
@samik9 - let us know if you could access to our gitlab repo - http://gitlab.inspireui.com/ - thank you!

**Comment by samik9** [comment]
@minhcasi I already send the required application

**Comment by minhcasi** [comment]
we have sent invite to your email - not sure if it is correct `.con`
<img width="463" alt="Screen Shot 2020-08-24 at 16 46 26" src="https://user-images.githubusercontent.com/1459805/91030365-5c9c0d80-e629-11ea-94c0-704a84f06bb8.png">

**Comment by samik9** [comment]
@minhcasi my email is **samik9@icloud.com** yeah is a type error

**Comment by samik9** [comment]
hello, i haven't got the invite, also, how are the bugs going?

**Comment by minhcasi** [comment]
I'm sorry that missed your comment, please help to check the email - https://tppr.me/6gXKr 

You could follow this guide to merge with your project - https://medium.com/@inspireui/how-to-upgrade-fluxstore-projects-by-using-git-cebde7489ea6

Let us know your checking

**Comment by samik9** [comment]
Thank you ! When do you think those issues will be fixed ?

**Comment by simonpham** [comment]
Hi @samik9,

We wanted to thank you for your patience during this epidemic time. We currently have reduced staff and a significantly higher volume of inquiries. We’re working as hard as we can to get to your request as soon as possible.

Thank you for your patience.

**Comment by minhcasi** [comment]
Greetings from InspireUI 🎉
To improve user experience during support, we are announcing that a new ticket support system is available on this link https://support.inspireui.com 

Please help to move your next comment on the new support system (you could mention this ticket so that the team could know more about the ticket's history) - thank you for your time!
