### ISSUE TITLE
product Variable

### ISSUE THREAD

**Issue by iqmtgar** [inspireui/support#4516]
hi how are you 
i have problem 
When I add a multi-type product it doesn't work in an app 
not change price and not change img ?
Also if you buy it, it only sends one color, not two
I see on the woocommerce admin panel requesting only one color product How can this be solved?
I have sent you a multi-type product that works with the website without problems
But it doesn't work with an application
product :
https://zoom-iq.com/product/test-color-black-and-red/
![47e5ab1f-2590-40a1-a7c8-bb5c20091344](https://user-images.githubusercontent.com/33340985/89696595-469c0680-d921-11ea-854e-8f4194dc6101.jpg)
![62004c6d-4e6d-45fc-a2c4-c5dfa739f348](https://user-images.githubusercontent.com/33340985/89696596-47cd3380-d921-11ea-841f-b9bac58c8e67.jpg)
![wp](https://user-images.githubusercontent.com/33340985/89696597-47cd3380-d921-11ea-89ac-89b09f9c4c9e.JPG)

**Comment by ameenbadri7** [comment]
From what I can see you did not setup your site or your app probably for the variation products.

Check this guide https://docs.inspireui.com/fluxstore/multi-language/

And try to use this pre-config site to help with the config or use for reference - https://docs.inspireui.com/fluxstore/woocommerce-setup/#1-website-integration

Also, refer to [this ticket ](https://github.com/inspireui/support/issues/4223). 

Please note that we may not support answering or support technical issues for the regular license as per support policies - https://inspireui.com/support-policies/ - but we are trying to best to give extra miles with the supporting.

**Comment by iqmtgar** [comment]
I installed all the information and the application and it works without any problems
I just need to explain the method of various types of products, how to install it

**Comment by ameenbadri7** [comment]
To show the colors inside your app you have to create a color attribute with the name `color` also create inside it `Terms` that they are exactly as what you have in inside your app folder `lib\common\constants\colors.dart` 

<img width="910" alt="123123" src="https://user-images.githubusercontent.com/37524186/89700523-56bee080-d937-11ea-8aec-f026cf55fff6.png">

if you are using the multi-language option you should check this [guide ](https://docs.inspireui.com/fluxstore/multi-language/
)
You have to install the wpml plugin and other related stuff to make it work. 

Thank you.

**Comment by iqmtgar** [comment]
A very complex topic, we need to explain in detail or Short video on YouTube Because the matter is very important
If i  install plugin wpml
Will i solve problems? With products variable?

**Comment by iqmtgar** [comment]
i dont need multi lang i using app only with arabic lang but my problem not lang 
my problem product when i using multi color each product color not see on app multi img or color just 
options but not work 
for ex when click on buttom color black i see same price and same img when click on color green i see same img and same price why >?
how to solve that plz

**Comment by iqmtgar** [comment]
this video work on fluxstore or only 
mstore ?
https://www.youtube.com/watch?v=j2--F4_sM_A
i need this same idea on video not work for me i dont know how to solve

**Comment by iqmtgar** [comment]
now its work >> just I need a translation to arabic ? how to that ! red = أحمر 
![image](https://user-images.githubusercontent.com/33340985/89702244-d9e83280-d947-11ea-9b37-87b3bd391a86.png)

**Comment by ameenbadri7** [comment]
Check out this [guide ]( https://docs.inspireui.com/fluxstore/multi-language/) to translate your site.
If you do that could send me a screenshot from your WooCommerce Multilingual plugin page inside your domain.

**Comment by ameenbadri7** [comment]
I'm sorry to close this ticket as there is no response or active conversation. 

Please help to create a new one and link to this ticket if the problem is not solved. 

Thank you for your time!
