### ISSUE TITLE
Different layout for each language 

### ISSUE THREAD

**Issue by waleedElleithi** [inspireui/support#4519]
In this file lib/services/listing.dart, you can start to modify the fetchProductsByCategory function to match the endpoint you created.   **(Please give me one example)**

Plus
Unlike fluxstore for ecommerce, there are no Config_en.json and Config_ar.json to have different layout for each language
**How can I have different layout for each language?**
thanks

_Originally posted by @waleedElleithi in https://github.com/inspireui/support/issues/4351#issuecomment-670830487_

**Comment by minhcasi** [comment]
@waleedElleithi - thank you for the feedback, the multi-layout for different languages is not supported for the FluxListing pro - you could try to refer the Fluxstore and approach for the same solution.

Let us know if you have any questions - very best 👍

**Comment by waleedElleithi** [comment]
Hi,
First, You have not answered the first part of my question, which related to issue  #4351, 
Second, you said " **you could try to refer the Fluxstore and approach for the same solution**." please , elaborate

**Comment by waleedElleithi** [comment]
Hi 
Related to the issue  #4351 , I changed ,,my theme to Listeo, and I still face the same problem, there is no way to display the English categories in the English View and the Arabic categories in the Arabic view
So what I want:
1- Only English category appear in the English view and Arabic category appear in the Arabic view
2- You mentioned earlier that the builder support Listeo, however it is not as I tested, is there another builder do you have or how to figuer this out 

Please review issue  #4351 and answer me as soon as possible 

thank you

**Comment by minhcasi** [comment]
@waleedElleithi - pls give your all comment to one open ticket and move to #4351 - thank you for your time
