### ISSUE TITLE
[MStore] Error 500, couldn't found index

### ISSUE THREAD

**Issue by DaviDawn** [inspireui/support#452]
- Product: [MStore]
 - Your Purchased Code: [ff572917-25b2-4bd6-809c-125bf5b11d60]

We've link our wordpress with WooCommerce to our MStore, should be the server in the same wordpress server ( we have separately )

Should we create a file called index?

The IP and Port that shows at beginning of the error isn't our page, and we haven't put it in any file/configuration. May is that the error? Where can I can change that IP? 

 -- This is our directory react-native/scripts/
![capturaDirectorioScripts](https://user-images.githubusercontent.com/38453878/55147422-a471e900-5146-11e9-8994-2cf87c79feb5.PNG)

 -- Screenshot
![capturaDispotivoError500](https://user-images.githubusercontent.com/38453878/55147244-5230c800-5146-11e9-9fe9-b4cd8d00cbfa.PNG)

 -- The all error
The development server returned response error code: 500

URL: http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false

Body:
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Error: Unable to resolve module `./index` from `C:\Users\david\OneDrive\Escritorio\MStore\mstore-3.7.2\mstore-pro\node_modules\react-native\scripts/.`: The module `./index` could not be found from `C:\Users\david\OneDrive\Escritorio\MStore\mstore-3.7.2\mstore-pro\node_modules\react-native\scripts/.`. Indeed, none of these files exist:<br> &nbsp;* `C:\Users\david\OneDrive\Escritorio\MStore\mstore-3.7.2\mstore-pro\node_modules\react-native\scripts\index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`<br> &nbsp;* `C:\Users\david\OneDrive\Escritorio\MStore\mstore-3.7.2\mstore-pro\node_modules\react-native\scripts\index\index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`<br> &nbsp; &nbsp;at ModuleResolver.resolveDependency (C:\Users\david\OneDrive\Escritorio\MStore\mstore-3.7.2\mstore-pro\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:163:15)<br> &nbsp; &nbsp;at ResolutionRequest.resolveDependency (C:\Users\david\OneDrive\Escritorio\MStore\mstore-3.7.2\mstore-pro\node_modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:52:18)<br> &nbsp; &nbsp;at DependencyGraph.resolveDependency (C:\Users\david\OneDrive\Escritorio\MStore\mstore-3.7.2\mstore-pro\node_modules\metro\src\node-haste\DependencyGraph.js:283:16)<br> &nbsp; &nbsp;at C:\Users\david\OneDrive\Escritorio\MStore\mstore-3.7.2\mstore-pro\node_modules\metro\src\lib\transformHelpers.js:261:42<br> &nbsp; &nbsp;at Server.&lt;anonymous&gt; (C:\Users\david\OneDrive\Escritorio\MStore\mstore-3.7.2\mstore-pro\node_modules\metro\src\Server.js:1038:41)<br> &nbsp; &nbsp;at Generator.next (&lt;anonymous&gt;)<br> &nbsp; &nbsp;at asyncGeneratorStep (C:\Users\david\OneDrive\Escritorio\MStore\mstore-3.7.2\mstore-pro\node_modules\metro\src\Server.js:99:24)<br> &nbsp; &nbsp;at _next (C:\Users\david\OneDrive\Escritorio\MStore\mstore-3.7.2\mstore-pro\node_modules\metro\src\Server.js:119:9)</pre>
</body>
</html>

processBundleResult
    BundleDownloader.java:296
access$200
    BundleDownloader.java:37
onResponse
    BundleDownloader.java:174
execute
    RealCall.java:206
run
    NamedRunnable.java:32
runWorker
    ThreadPoolExecutor.java:1112
run
    ThreadPoolExecutor.java:587
run
    Thread.java:818

**Comment by luyx2412** [comment]
HI @DaviDawn Can you give me the MStore version?

Thanks

**Comment by DaviDawn** [comment]
MStore Version -> 3.7.2
CeBuilder Version -> 0.28.0

**Comment by nguyenlqxx82nb** [comment]
i had same this error

**Comment by luyx2412** [comment]
HI @DaviDawn i saw your error which missed some file, please make sure your project full code, after that clean your project and re-install again the library.

Thanks
