### ISSUE TITLE
Failed to run app in chrome debug mode

### ISSUE THREAD

**Issue by mkarci26** [inspireui/support#4520]
Launching lib\main.dart on Chrome in debug mode...
Syncing files to device Chrome...
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:88:26: Error: Type 'DiagnosticableMixin' not found.
class PictureStream with DiagnosticableMixin {
                         ^^^^^^^^^^^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:192:44: Error: Type 'DiagnosticableMixin' not found.
abstract class PictureStreamCompleter with DiagnosticableMixin {
                                           ^^^^^^^^^^^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:88:7: Error: The type 'DiagnosticableMixin' can't be mixed in.
class PictureStream with DiagnosticableMixin {
      ^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:192:16: Error: The type 'DiagnosticableMixin' can't be mixed in.
abstract class PictureStreamCompleter with DiagnosticableMixin {
               ^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:167:11: Error: Superclass has no method named 'debugFillProperties'.
    super.debugFillProperties(properties);
          ^^^^^^^^^^^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:171:30: Error: The method 'toStringShort' isn't defined for the class 'PictureStreamCompleter'.
 - 'PictureStreamCompleter' is from 'package:flutter_svg/src/picture_stream.dart' ('/C:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart').
Try correcting the name to the name of an existing method, or defining a method named 'toStringShort'.
      ifPresent: _completer?.toStringShort(),
                             ^^^^^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:266:11: Error: Superclass has no method named 'debugFillProperties'.
    super.debugFillProperties(description);
          ^^^^^^^^^^^^^^^^^^^
Unhandled exception:
NoSuchMethodError: The getter 'name' was called on null.
Receiver: null
Tried calling: name
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      ProgramCompiler._emitSuperTarget (package:dev_compiler/src/kernel/compiler.dart:4777:41)
#2      ProgramCompiler.visitSuperMethodInvocation (package:dev_compiler/src/kernel/compiler.dart:4770:24)
#3      SuperMethodInvocation.accept (package:kernel/ast.dart:4024:44)
#4      ProgramCompiler._visitExpression (package:dev_compiler/src/kernel/compiler.dart:3411:20)
#5      ProgramCompiler.visitExpressionStatement (package:dev_compiler/src/kernel/compiler.dart:3492:12)
#6      ExpressionStatement.accept (package:kernel/ast.dart:5784:43)
#7      ProgramCompiler._visitStatement (package:dev_compiler/src/kernel/compiler.dart:3339:20)
#8      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
#9      ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
#10     new List.from (dart:core-patch/array_patch.dart:38:29)
#11     new List.of (dart:core-patch/array_patch.dart:68:17)
#12     ListIterable.toList (dart:_internal/iterable.dart:211:44)
#13     ProgramCompiler.visitBlock (package:dev_compiler/src/kernel/compiler.dart:3505:62)
#14     Block.accept (package:kernel/ast.dart:5823:43)
#15     ProgramCompiler._visitStatement (package:dev_compiler/src/kernel/compiler.dart:3339:20)
#16     ProgramCompiler._emitFunctionScopedBody (package:dev_compiler/src/kernel/compiler.dart:3350:18)
#17     ProgramCompiler._emitSyncFunctionBody.<anonymous closure> (package:dev_compiler/src/kernel/compiler.dart:3159:17)
#18     ProgramCompiler._withLetScope (package:dev_compiler/src/kernel/compiler.dart:2098:25)
#19     ProgramCompiler._withCurrentFunction (package:dev_compiler/src/kernel/compiler.dart:3193:18)
#20     ProgramCompiler._emitSyncFunctionBody (package:dev_compiler/src/kernel/compiler.dart:3155:17)
#21     ProgramCompiler._emitFunction (package:dev_compiler/src/kernel/compiler.dart:2958:11)
#22     ProgramCompiler._emitMethodDeclaration (package:dev_compiler/src/kernel/compiler.dart:1717:12)
#23     ProgramCompiler._emitClassMethods (package:dev_compiler/src/kernel/compiler.dart:1658:23)
#24     ProgramCompiler._emitClassDeclaration (package:dev_compiler/src/kernel/compiler.dart:559:21)
#25     ProgramCompiler._emitClass (package:dev_compiler/src/kernel/compiler.dart:501:21)
#26     List.forEach (dart:core-patch/growable_array.dart:302:8)
#27     ProgramCompiler._emitLibrary (package:dev_compiler/src/kernel/compiler.dart:450:23)
#28     List.forEach (dart:core-patch/growable_array.dart:302:8)
#29     ProgramCompiler.emitModule (package:dev_compiler/src/kernel/compiler.dart:341:15)
#30     JavaScriptBundler.compile (package:frontend_server/src/javascript_bundle.dart:142:33)
<asynchronous suspension>
#31     FrontendCompiler.writeJavascriptBundle (package:frontend_server/frontend_server.dart:661:20)
<asynchronous suspension>
#32     FrontendCompiler.compile (package:frontend_server/frontend_server.dart:561:15)
<asynchronous suspension>
#33     _FlutterFrontendCompiler.compile (package:flutter_frontend_server/server.dart:43:22)
#34     listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1201:26)
#35     _RootZone.runUnaryGuarded (dart:async/zone.dart:1384:10)
#36     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#37     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#38     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:69:11)
#39     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#40     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#41     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:155:13)
#42     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:130:5)
#43     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#44     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:121:24)
#45     _RootZone.runUnaryGuarded (dart:async/zone.dart:1384:10)
#46     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#47     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#48     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:69:11)
#49     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#50     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#51     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#52     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:317:20)
#53     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:310:5)
#54     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#55     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:121:24)
#56     _RootZone.runUnaryGuarded (dart:async/zone.dart:1384:10)
#57     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#58     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#59     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#60     _StreamController._add (dart:async/stream_controller.dart:682:7)
#61     _StreamController.add (dart:async/stream_controller.dart:624:5)
#62     _Socket._onData (dart:io-patch/socket_patch.dart:2020:41)
#63     _RootZone.runUnaryGuarded (dart:async/zone.dart:1384:10)
#64     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#65     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#66     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#67     _StreamController._add (dart:async/stream_controller.dart:682:7)
#68     _StreamController.add (dart:async/stream_controller.dart:624:5)
#69     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1556:33)
#70     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1052:14)
#71     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#72     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#73     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#74     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
Finished with error: the Dart compiler exited unexpectedly.
Failed to compile application.

**Comment by minhcasi** [comment]
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by mkarci26** [comment]
I am able to run app after downloading flutter to stable version. and pointed pub-cache DiagnosticableMixin to Diagnosticable. This issue is resolved now. but when run app in chrome, i am getting firebase error and not building in android apk

**Comment by mkarci26** [comment]
Closing issue Since I figured out the issue
