### ISSUE TITLE
Can't add product to cart which have multiple attribute. 

### ISSUE THREAD

**Issue by amitsahaiotait** [inspireui/support#4521]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: I can't add product which have to select multiple attribute. It's shows always loading & price is showing incorrectly. 
+ Product & version: Fluxstore Multivendor ( 1.7.6 )
+ Flutter (or React Native) version:  Flutter
+ Testing Device/Simulator: OnePlus 7 Pro
+ Screenshot issues (drag the file to attach here): Here is the video demonstration :- https://drive.google.com/file/d/11iZkVA9xFwRv6w3DhITFY-1PZvYT8JU4/view?usp=sharing

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by amitsahaiotait** [comment]
I already submit verify from Please check

**Comment by minhcasi** [comment]
@amitsahaiotait - could you help to share the detailed screenshot or video so that we could reproduce the issues? Thank you!

**Comment by amitsahaiotait** [comment]
Here is the video. I already added in my post 

https://drive.google.com/file/d/11iZkVA9xFwRv6w3DhITFY-1PZvYT8JU4/view?usp=sharing

**Comment by minhcasi** [comment]
note with investigating - thank you!

**Comment by tgloc96** [comment]
Hi @amitsahaiotait,
Can you please send me your source code or add me to your git project via email tgloc96@gmail.com.

Thank you for your time.

**Comment by amitsahaiotait** [comment]
Hello @tgloc96 

I added you the project in git project name " health_superbuy " Please check. 

Thank your for get back to me.

**Comment by tgloc96** [comment]
> health_superbuy

Excuse me, but I don't see anything. Please help me check again. Thank you so much.

**Comment by amitsahaiotait** [comment]
@tgloc96 here is the invitation link :- https://github.com/amitsahaiotait/health_superbuy/invitations

**Comment by minhcasi** [comment]
the latest version `1.7.7` is ready for download, please keep the update and let us know if you have any question - thank you!

**Comment by amitsahaiotait** [comment]
Ok let me check that. If same issue happening again i will let you know

**Comment by minhcasi** [comment]
@amitsahaiotait - let us know if you have any question, feel free to reopen the ticket if it could not be resolved - thank you!
