### ISSUE TITLE
Woo-commerce setup

### ISSUE THREAD

**Issue by destek-harshadapatil** [inspireui/support#4524]
Hello team,

I just wanted to ask that can I shift my project back end from woo-commerce to PHP ??
As I am Unable to do some customisation in woo-commerce so I wanted to use PHP as back end.
Please help me with this. And let me know how will it possible.
And if its possible then please let me know that which steps i have to follow.

Thanks & Regards.

_Originally posted by @destek-harshadapatil in https://github.com/inspireui/support/issues/4274#issuecomment-670922394_

**Comment by minhcasi** [comment]
@destek-harshadapatil - it is possible to change the woo commerce API from the app (you could check the services/woocommerce.dart) and update the model to map your new product field (check the models folder) - could i know if you are using any PHP open-source or adding your own PHP backend?

**Comment by minhcasi** [comment]
@destek-harshadapatil - pls help us to move your all comments to the same ticket support #4523 👍

**Comment by destek-harshadapatil** [comment]
Thank you team for your help.

We are adding our own PHP backend for that we wanted to use 

Framework - code ignitor framework or we can also use lara well framwork &
API - Rest API 

So, How could I replace or add my API's ?  please help.

Thanks and Regards!
