### ISSUE TITLE
ı cant install cocoapods

### ISSUE THREAD

**Issue by kumanli** [inspireui/support#4526]
<img width="1029" alt="error" src="https://user-images.githubusercontent.com/3662438/89714332-63c6e880-d9a6-11ea-99a6-de930d9caa20.png">

**Comment by minhcasi** [comment]
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
@kumanli - would you mind to send us your result by running `flutter doctor`

Please try your best to check the detail document to fix the Flutter SDK issue - https://flutter.dev/docs/get-started/install

**Comment by kumanli** [comment]
<img width="950" alt="flutter doctor" src="https://user-images.githubusercontent.com/3662438/90140816-f38fdc80-dd82-11ea-9618-6323e9daf4ba.png">
