### ISSUE TITLE
MV-Error using PayPal native payment option and geolocalization on store list

### ISSUE THREAD

**Issue by mauriciozuniga** [inspireui/support#4529]
+ Detail Issues: 
Hi!

I have two issues with Multivendor 1.7.6 that I need help with (**I have uploaded common and config files on verify.inspireui.com for your review**...):

**1) Paypal native issue**: I have "PaypalConfig" native feature active (with a sandbox account), but when I try to made a Payment, it sends an "INVALID_CURRENCY_AMOUNT_FORMAT" error. I'm using Mexican pesos (MXN iso code), and I have fixed tools.dart to use the correct locale and show the amounts with the correct format (comma for thousand separators and points for decimals $12,980.00 )

final formatCurrency = NumberFormat.currency(locale: "es_MX",
        symbol: "", decimalDigits: defaultCurrency['decimalDigits']);

The amounts looks good on all the app, with the correct format, but PayPal keeps failing. I had tried with locale "en_US" and "es_MX". I am attaching screenshot
<img width="395" alt="Captura de Pantalla 2020-08-08 a la(s) 12 19 37" src="https://user-images.githubusercontent.com/8905579/89716419-76bfc580-d972-11ea-941f-f9ecc7867e28.png">

2) Geolocalization: When I open store list, and I choose the geolocalization icon at top right corner, it send the position of the map to the coast of Africa, and I am at Mexico (when I zoom out and go to Mexico, my marker its fine at Mexico). Do you know what this happens?

+ Product & version:
FluxStore Multivendor 1.7.6
+ Flutter (or React Native) version: 
Flutter 1.17.1

+ Testing Device/Simulator: 
iOS several devices (iPhone X, iPhone 8)

+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@mauriciozuniga 

1. Please try to double-check the Amount format - example correct format: 100.05 (with to decimal format) if you return 100.050, Paypal will return this exception - ref: https://stackoverflow.com/questions/59564439/paypal-field-and-decimal-error-in-node-js

2. It could be the issue with initialCameraPosition, you try to set hardcode on Mexico - ref: https://pub.dev/packages/google_maps_flutter

Hope it helps with the answer - thank you!

**Comment by mauriciozuniga** [comment]
thnks! we will check it tomorrow morning and let you know!

**Comment by mauriciozuniga** [comment]
Hi minhcasi!
We debugged the app, and we see that actually, when calling PayPal Api, the formatPrice method on payment/ paypal/index.dart, the amount is returned on the incorrect format with a "coma" for the decimals (for example 200.00 is passed as 200,00) and I think that is why PayPal is returning the error. 
We already fixed this to show the amounts correctly on tools.dart, but I see I need to change it in several places of the code... Is there a way we can configure the correct Locale to use on all the application?  So it uses the correct amount format on all places?

Thanks!!

PS: we are still checking the geolocalization issue, we will let you know our findings

**Comment by mauriciozuniga** [comment]
Hi minhcasi!

Paypal error was solved changing the currency locale on formatCurrency of paypal/index.dart file, and mexico coordenates was hardcoded on map_screen.dart file.

But we have detected another issue that is critícal, hope you can help me.
When you select your shipping method,your address
and so on, but then select a payment method NOT supported by native, like Stripe, it sends you to webview checkout but CHANGES the shipping method to the first one of the list... So, if for example, the user choose “delivery flat rate” on app and then choose pay with stripe, in webview it automatically chooses the first shipping method on the list, for example, local pickup, ignoring previous choice, and if this happens, the
order is saved as “local pickup” so the store never send the item... 
could you help with the fix?

thanks!

**Comment by angelohu** [comment]
@mauriciozuniga  can you help ? please.

**Comment by mauriciozuniga** [comment]
Hi @angelohu , in what?

**Comment by angelohu** [comment]
Paypal Payment IVALID_FORMAT_CURRENCY    发件人: mauriciozuniga发送时间: 2020年8月11日 20:23收件人: inspireui/support抄送: angelohu; Mention主题: Re: [inspireui/support] MV-Error using PayPal native payment option and geolocalization on store list (#4529) Hi @angelohu , in what?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by minhcasi** [comment]
@mauriciozuniga - i will have a check with next release `1.7.7` in 1-2 days - thank you!

**Comment by minhtruong315** [comment]
@mauriciozuniga We released Fluxstore 1.7.7. it's working for flutter 1.20.1 well. please download Fluxstore 1.7.7 on codeanyon and update MStore Api plugin in the wordpress website as well

**Comment by mauriciozuniga** [comment]
Thanks!
I already updated the app, but the issue with the shipping method persists when changing to webview after choosing stripe, it just doesn’t select the option the user selected before on native options and always select the first one.Also, in webview, it puts the text of “apartment” field on the “company” field of webview

could you help us?
thnks!!
cheers

**Comment by minhtruong315** [comment]
Can u send me common folder and record video for your issue via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/4529

**Comment by mauriciozuniga** [comment]
Done! you should have it on your inbox now!

Thanks in advance!

**Comment by minhtruong315** [comment]
@mauriciozuniga I sent you the email. pls check. thanks

**Comment by minhtruong315** [comment]
Hi @mauriciozuniga I sent you updates via the email. please check

**Comment by minhcasi** [comment]
Let us know if you have any question - thank you!
