### ISSUE TITLE
[MStore] Product Variation stock quantity error

### ISSUE THREAD

**Issue by hakihosting** [inspireui/support#453]
Purchase code : ac9d522a-a783-4f9c-a882-7dc694488d5d

Hello there is not syncing stock with the woocomerce quantity : 
i share you a video : https://streamable.com/28x6t
on the website there is out of stock but in the app you can order it. 
How to resolve that.

**Comment by luyx2412** [comment]
HI @hakihosting thanks for your feedback, we will a check improve the issue with next version. You can quick fix the issue in `src/containers/Detail/index.js` --> line 488. Add check function to show out of stock.

![image](https://user-images.githubusercontent.com/8909619/55205309-e3ff0a80-5204-11e9-88f3-ce0c81303c46.png)

Thanks.

**Comment by hakihosting** [comment]
and what is the correct adapation to do . I would like to fix this

**Comment by luyx2412** [comment]
Hi @hakihosting you can check the product which have empty quantity and show `out of stock`. https://docs.mstore.io/api-and-project-structure#debug-app-with-reacttotron and please use the debug tools to check api response to know the field quantity.

Thanks

**Comment by hakihosting** [comment]
Hello is not the product , but the variation of the product !

**Comment by luyx2412** [comment]
Hi @hakihosting Please merge to one issue to answer issue.
Thanks
