### ISSUE TITLE
 Fluxstore Multi Vendor - Flutter E-commerce Full App Build Field

### ISSUE THREAD

**Issue by joemark0008** [inspireui/support#4530]
**_Step 1 (require): describe detail issues & screenshots_**

+ Detail Issues:  field upon running command  flutter run

+ Product & version:FluxStore-vendor-1.7.6

+ Flutter (or React Native) version: 
Flutter 1.20.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2ae34518b8 (3 days ago) • 2020-08-05 19:53:19 -0700
Engine • revision c8e3b94853
Tools • Dart 2.9.0

+ Testing Device/Simulator: 

+ Screenshot issues (drag the file to attach here): 
![flutter](https://user-images.githubusercontent.com/41988621/89726310-a7bff900-da4b-11ea-9020-d2fe80e67a6c.JPG)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@joemark0008 - this issue could cause by latest release from flutter version `1.20.1` - we will have a check and update in 1-2 days - very best!

**Comment by joemark0008** [comment]
Yes I read.. for now I just down grade the version of my flutter

**Comment by minhtruong315** [comment]
Hi @joemark0008 We released Fluxstore 1.7.7. it's working for flutter 1.20.1 well. please download Fluxstore 1.7.7 on codeanyon and update MStore Api plugin in the wordpress website as well

**Comment by minhcasi** [comment]
The latest version `1.7.7` is ready for download, please keep the update and let us know if you have any question - thank you!
