### ISSUE TITLE
Hi, the search bar is only loading, it’s not showing any results

### ISSUE THREAD

**Issue by owais91411** [inspireui/support#4532]
Hi, the search bar is only loading, it’s not showing any results
I'm using fluxstore woocommerce.
![Screenshot_20200809-120045](https://user-images.githubusercontent.com/68670738/89726438-3a569d00-da38-11ea-9597-60e5252b276b.jpg)
The search results just keeps on loading even after typing keywords.

**Comment by minhcasi** [comment]
@owais91411 - could I know which fluxstore version you are using?

**Comment by owais91411** [comment]
Fluxstore 1.7.6 latest version

**Comment by owais91411** [comment]
Hi, please help me out

**Comment by minhcasi** [comment]
@owais91411 - please help to zip the common + config folder and send to inspireui.team@gmail.com - we suspect it could be a bug when integrating with your site - thank you for your time!

**Comment by owais91411** [comment]
So both common & config folder I've to mail you?

**Comment by owais91411** [comment]
Hi, I've mailed the folders in rar format please check it.

**Comment by minhcasi** [comment]
@owais91411 - we have upgraded to latest release `1.7.7` to fix this bug, please help to use the latest version

You could use this method to merge the source code - https://medium.com/@inspireui/how-to-upgrade-fluxstore-projects-by-using-git-cebde7489ea6
