### ISSUE TITLE
Change default sign in method

### ISSUE THREAD

**Issue by rabeehlive** [inspireui/support#4533]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

I want to change the default sign in method, by replacing the username and password screen with mobile number login screen. 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

My previous ticket 
4477

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by rabeehlive** [comment]
I think you will help me, my previous ticket is still open. No one helped me yet.

**Comment by minhcasi** [comment]
@rabeehlive - pls help to give comment on #4477 - our team will have a check and let you know
