### ISSUE TITLE
Multiple Errors Reported in the terminal

### ISSUE THREAD

**Issue by jakulz** [inspireui/support#4534]
Hello, I am trying to run my fluxstore Woocoomerce app and I am get multiple errors. I have attached screenshots.

![scrnsht1](https://user-images.githubusercontent.com/35921309/89728024-adcbc080-d9de-11ea-989a-3fe8cdca4ea0.png)
![scrnsht2](https://user-images.githubusercontent.com/35921309/89728027-b3290b00-d9de-11ea-94c6-8954690a39e9.png)
![scrnsht3](https://user-images.githubusercontent.com/35921309/89728028-b4f2ce80-d9de-11ea-8393-c75d49bfa253.png)
![scrnsht4](https://user-images.githubusercontent.com/35921309/89728029-b623fb80-d9de-11ea-8708-096ef43c703b.png)
![scrnsht5](https://user-images.githubusercontent.com/35921309/89728030-b7edbf00-d9de-11ea-8cc3-6e1dcfaaabf4.png)
![scrnsht6](https://user-images.githubusercontent.com/35921309/89728031-b91eec00-d9de-11ea-98a5-3c0468d9f2a5.png)

**Comment by tskmark** [comment]
i'm getting same error

**Comment by tskmark** [comment]
ANY FIX YET?

**Comment by jakulz** [comment]
NO FIX YET

**Comment by mkarci26** [comment]
I was facing the same issue. I renamed DiagnosticableMixin to Diagnosticable. Now this issue is resolved for me.

**Comment by attare026** [comment]
Problem with flutter upgrade
Change DiagnosticableMixin to Diagnosticable in D:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart
https://github.com/inspireui/support/issues/4539#issuecomment-671061224
@jakulz #4539

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 

Thank you for your time!

**Comment by jakulz** [comment]
Renaming DiagnosticableMixin to Diagnosticable solved the issue for me.
Thank you!

‪On Sun, Aug 9, 2020 at 11:11 AM ‫amin badri أمين بدري‬‎ <
notifications@github.com> wrote:‬
