### ISSUE TITLE
UK Address Format  & Wishlist

### ISSUE THREAD

**Issue by niranjan62** [inspireui/support#4535]
- [x] **1. How to add product quantity to My Wishlist page?**

![Wishlist---add-count(1)](https://user-images.githubusercontent.com/69341826/89728053-361f8500-da22-11ea-8d7e-e42902447c14.png)

******************************************************************************************************

- [x] When selecting the United Kingdom as Shipping Address, the format should be like the below order.
  * Address line 1
  * Address line 2
  * City
  * **Post Code**

UK postcodes have Numbers and text. Currently postcode (Zip_code) textfield only allows numbers.
    Please change Keypad format to add text for Postcode field
    Please change the UK Address format.

![UK-Address-format(1)](https://user-images.githubusercontent.com/69341826/89728097-a1695700-da22-11ea-876a-4c11a0ac9285.png)

******************************************************************************************************

- [x] We deliver only selected postcode ranges. Using the woocommerce default function for that. But apps allows to purchase with different postcodes that are not in the range. 

![Screenshot_2020-07-22 WooCommerce settings ‹ My Local Grab — WordPress](https://user-images.githubusercontent.com/69341826/89728138-db3a5d80-da22-11ea-99ff-921feb47c105.png)

- [x] Footer Checkout icon showing quantity of the total products. can you change that function to show total products count (Don't use quantity field)

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 

Thank you for your time!

**Comment by niranjan62** [comment]
Uploaded Proof of purchased License PDF file

**Comment by minhcasi** [comment]
@niranjan62 - thank you so much for the feedback

I've noted add new feature quest and keep upgrade on next release version - thank you!

**Comment by niranjan62** [comment]
@minhcasi Uk Address Format is main part to release my App 
Let me know about that part.

**Comment by minhcasi** [comment]
There is new upgrade for the Address form on next `1.7.7` - we will update this release in 1-2 days - thank you!

**Comment by niranjan62** [comment]
@minhcasi What are the files need to replace on previous version?

or let me know how to update new version with all the changes made already?

**Comment by minhcasi** [comment]
@niranjan62 - please give a try to merge the project by using Git - https://medium.com/@inspireui/how-to-upgrade-fluxstore-projects-by-using-git-cebde7489ea6

**Comment by minhcasi** [comment]
Let us know if you have any questions

**Comment by niranjan62** [comment]
@minhcasi I have downloded 1.7.7 and checked UK Address Format. 
It's same as old. Not allowing to add Letters, It's showing "Numbers only keypad"
