### ISSUE TITLE
Fluxstore multivendor - Downloadable product

### ISSUE THREAD

**Issue by marknestor261** [inspireui/support#4537]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
- The download button instead shares but doesn't download the digital product, please help me out here.
- Also, is it possible for product to be immediately downloaded right after purchase.

+ Product & version: 1.7.6
+ Flutter (or React Native) version: 1.17.1
+ Testing Device/Simulator: Tecno camon 11 Air (Android)
+ Screenshot issues (drag the file to attach here): 
![Screenshot_20200809-124756](https://user-images.githubusercontent.com/46901102/89729515-27939680-da3f-11ea-98ad-e5992d26170a.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@marknestor261 - it will open the download link to allow user download, does feature not work on your site? Could you share the product URL after clicking to the sharing? Example tap the Save to Google Drive

**Comment by marknestor261** [comment]
Is it possible for Download button to be direct Download.

**Comment by minhcasi** [comment]
no, it is not available - it will open the native popup so that you could pick the default download app

**Comment by minhcasi** [comment]
Let us know if you have any question - thanks
