### ISSUE TITLE
[MStore] How to publish for Web?

### ISSUE THREAD

**Issue by imsajjid** [inspireui/support#454]
**Mandatory Info (please complete the following information):**
 - Product: MStore
 - Your Purchased Code: 6e0b4254-5826-4be9-b77c-6e55cf6c13b7
(we may not reply if you are not our customer)

**Describe the issues**
I am on macOS 10.14 (18A391). Downloaded CeBuilder - v0.27.0 beta. Placed the download copy of the codecanyon in Downloads folder. Have two version mstore-expo and mstore-pro. Selected mstore-expo (attached are screenshots). When try to 'Run setup'. Get error in terminal and iOS simulator shows red warning messages. Don't know how to resolve it so the app run fine on simulator.

Secondly and most importantly. How to make this uploaded and connected with woocommerce (though i have added woocommerce api and secret which seem to pull categories correctly). But, i don't see any manual or guide how to publish it on webserver? How to integrate with a running website of wordpress? How to make a delivery to my client so it serves the purpose. Weak documentation is available on mstore official site. No help guide from scratch till deployment.

Red warning comes right after the app start generating view.

**Screenshots**
![Screenshot 2019-03-28 at 10 10 13 PM](https://user-images.githubusercontent.com/8928188/55178527-5e00a680-51a7-11e9-83eb-c4ef4bda5a2a.png)
![Screenshot 2019-03-28 at 10 10 40 PM](https://user-images.githubusercontent.com/8928188/55178530-5e00a680-51a7-11e9-84ba-46c54052bf88.png)
![Screenshot 2019-03-28 at 10 11 00 PM](https://user-images.githubusercontent.com/8928188/55178533-5e993d00-51a7-11e9-9b70-014dd7d8996e.png)
![Screenshot 2019-03-28 at 10 13 04 PM](https://user-images.githubusercontent.com/8928188/55178536-5e993d00-51a7-11e9-8b70-cc099b06f9ba.png)
![Screenshot 2019-03-28 at 10 15 31 PM](https://user-images.githubusercontent.com/8928188/55178537-5e993d00-51a7-11e9-8e17-4ad80a0add41.png)
![Screenshot 2019-03-28 at 10 15 45 PM](https://user-images.githubusercontent.com/8928188/55178538-5f31d380-51a7-11e9-99e5-49a0e249407d.png)
![Screenshot 2019-03-28 at 10 16 41 PM](https://user-images.githubusercontent.com/8928188/55178539-5f31d380-51a7-11e9-9169-077ee15a3e8f.png)
![Screenshot 2019-03-28 at 10 16 59 PM](https://user-images.githubusercontent.com/8928188/55178540-5fca6a00-51a7-11e9-95bf-579c0bfb0d11.png)

**Additional context**
TypeError: (0,b.warn) is not a function. (In '(0,b.warn)(s)', '(0,b.warn)' is undefined)

This error is located at:
    in l
    in n
    in RCTView
    in c
    in RCTScrollContentView
    in RCTScrollView
    in ScrollView
    in T
    in b
    in RCTView
    in n
    in p
    in withTheme(n)
    in RCTView
    in c
    in RCTScrollContentView
    in RCTScrollView
    in ScrollView
    in T
    in b
    in f
    in o
    in p
    in withTheme(o)
    in withNavigation(withTheme(o))
    in Connect(withNavigation(withTheme(o)))
    in RCTView
    in n
    in Connect(n)
    in p
    in withTheme(Connect(n))
    in RCTView
    in o
    in p
    in withTheme(o)
    in v
    in RCTView
    in f
    in RCTView
    in f
    in C
    in n
    in P
    in RCTView
    in n
    in RCTView
    in f
    in S
    in y
    in L
    in RCTView
    in _
    in C
    in k
    in v
    in v
    in RCTView
    in RCTView
    in l
    in RCTView
    in n
    in RCTView
    in n
    in _
    in k
    in L
    in RCTView
    in RCTView
    in f
    in RCTView
    in n
    in t
    in p
    in withTheme(t)
    in Connect(withTheme(t))
    in p
    in f
    in Connect(f)
    in c
    in s
    in w
    in v
    in RCTView
    in RCTView
    in c

getPriceIncluedTaxAmount
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false&assetPlugin=%2FUsers%2Farshmaan%2FDownloads%2FClient-Documents%2Ftornado%2Fmstore-3.7.1%2Fmstore-expo%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:1271:3184
value
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false&assetPlugin=%2FUsers%2Farshmaan%2FDownloads%2FClient-Documents%2Ftornado%2Fmstore-3.7.1%2Fmstore-expo%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:1624:646
ir
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false&assetPlugin=%2FUsers%2Farshmaan%2FDownloads%2FClient-Documents%2Ftornado%2Fmstore-3.7.1%2Fmstore-expo%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:96:43345
Wr
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false&assetPlugin=%2FUsers%2Farshmaan%2FDownloads%2FClient-Documents%2Ftornado%2Fmstore-3.7.1%2Fmstore-expo%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:96:57270
Dr
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false&assetPlugin=%2FUsers%2Farshmaan%2FDownloads%2FClient-Documents%2Ftornado%2Fmstore-3.7.1%2Fmstore-expo%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:96:57716
gi
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false&assetPlugin=%2FUsers%2Farshmaan%2FDownloads%2FClient-Documents%2Ftornado%2Fmstore-3.7.1%2Fmstore-expo%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:96:62917
mi
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false&assetPlugin=%2FUsers%2Farshmaan%2FDownloads%2FClient-Documents%2Ftornado%2Fmstore-3.7.1%2Fmstore-expo%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:96:62465
Fr
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false&assetPlugin=%2FUsers%2Farshmaan%2FDownloads%2FClient-Documents%2Ftornado%2Fmstore-3.7.1%2Fmstore-expo%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:96:60817
enqueueSetState
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false&assetPlugin=%2FUsers%2Farshmaan%2FDownloads%2FClient-Documents%2Ftornado%2Fmstore-3.7.1%2Fmstore-expo%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:96:31096
setState
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false&assetPlugin=%2FUsers%2Farshmaan%2FDownloads%2FClient-Documents%2Ftornado%2Fmstore-3.7.1%2Fmstore-expo%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:64:2084
<unknown>
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false&assetPlugin=%2FUsers%2Farshmaan%2FDownloads%2FClient-Documents%2Ftornado%2Fmstore-3.7.1%2Fmstore-expo%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:918:732
j
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false&assetPlugin=%2FUsers%2Farshmaan%2FDownloads%2FClient-Documents%2Ftornado%2Fmstore-3.7.1%2Fmstore-expo%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:928:4370
<unknown>
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false&assetPlugin=%2FUsers%2Farshmaan%2FDownloads%2FClient-Documents%2Ftornado%2Fmstore-3.7.1%2Fmstore-expo%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:1389:1350
f
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false&assetPlugin=%2FUsers%2Farshmaan%2FDownloads%2FClient-Documents%2Ftornado%2Fmstore-3.7.1%2Fmstore-expo%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:43:155
<unknown>
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false&assetPlugin=%2FUsers%2Farshmaan%2FDownloads%2FClient-Documents%2Ftornado%2Fmstore-3.7.1%2Fmstore-expo%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:43:882
k
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false&assetPlugin=%2FUsers%2Farshmaan%2FDownloads%2FClient-Documents%2Ftornado%2Fmstore-3.7.1%2Fmstore-expo%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:112:657
y
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false&assetPlugin=%2FUsers%2Farshmaan%2FDownloads%2FClient-Documents%2Ftornado%2Fmstore-3.7.1%2Fmstore-expo%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:112:904
callImmediates
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false&assetPlugin=%2FUsers%2Farshmaan%2FDownloads%2FClient-Documents%2Ftornado%2Fmstore-3.7.1%2Fmstore-expo%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:112:3099
value
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false&assetPlugin=%2FUsers%2Farshmaan%2FDownloads%2FClient-Documents%2Ftornado%2Fmstore-3.7.1%2Fmstore-expo%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:28:2902
<unknown>
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false&assetPlugin=%2FUsers%2Farshmaan%2FDownloads%2FClient-Documents%2Ftornado%2Fmstore-3.7.1%2Fmstore-expo%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:28:1274
value
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false&assetPlugin=%2FUsers%2Farshmaan%2FDownloads%2FClient-Documents%2Ftornado%2Fmstore-3.7.1%2Fmstore-expo%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:28:2594
value
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false&assetPlugin=%2FUsers%2Farshmaan%2FDownloads%2FClient-Documents%2Ftornado%2Fmstore-3.7.1%2Fmstore-expo%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:28:1244

**Comment by luyx2412** [comment]
HI @imsajjid 
1. Please download new version Mstore 3.7.2 to fix the issue.
2. I don't understand what you mean. You set up in CeBuilder about your wordpress website.

![image](https://user-images.githubusercontent.com/8909619/55205491-a9e23880-5205-11e9-8524-e0a1394cd16a.png)

Thanks

**Comment by imsajjid** [comment]
Alright @luyx2412 , i'll download it but i don't think so it will resolve the issue.

Yes, i want to list my client website categories and data into the app. That is the reason why i have used his site url and api key , secret.

**Comment by luyx2412** [comment]
Hi @imsajjid Please use debug tool to check your client api response https://docs.mstore.io/api-and-project-structure#debug-app-with-reacttotron

Thanks

**Comment by imsajjid** [comment]
Can you tell me how to resolve this issue?

======
![Screenshot 2019-04-02 at 11 09 31 PM](https://user-images.githubusercontent.com/8928188/55425673-75230800-559c-11e9-84e8-91e8648c01d4.png)
![Screenshot 2019-04-02 at 11 09 43 PM](https://user-images.githubusercontent.com/8928188/55425674-75bb9e80-559c-11e9-860f-79f1f164603f.png)

**Comment by luyx2412** [comment]
Hi @imsajjid The issue is related `Text` component showed wrong format, because `Text` component only allow type string. So make sure your `Text` component do not anything another format. https://facebook.github.io/react-native/docs/text

Thanks

**Comment by imsajjid** [comment]
I have figured that out thank you. Can you please help me understand why
price is coming as 0?
Also, i don't see shipping method listed or price getting from woocommerce

**Comment by luyx2412** [comment]
HI @imsajjid You can check in the shipping method on your website. Or using the debug tool to check api response which help you understand the app easier.

Thanks
