### ISSUE TITLE
FluxStore Magento Warehouse Selection

### ISSUE THREAD

**Issue by mhdag1** [inspireui/support#4540]
Dear Support Team,

I have successfully linked FluxStore Pro to my Magento site. However, I am facing issues with the stock levels. My platform has three warehouses, along with the fourth default one. FluxStore is only checking the stock levels from the default warehouse. I need it to fetch the data from a different warehouse (across the entire app; I do not need the facility to select the warehouse, as along as it is preset to the one I need).

If you require any further details please let me know.

Regards,
Mohammad

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 

Thank you for your time!

**Comment by mhdag1** [comment]
Hello Ameen,

Thank you for your response.

I have submitted the verification.

Regards,
Mohammad

**Comment by minhcasi** [comment]
@mhdag1 - it is verified - could you share some screenshot of these features to explain more on your idea? It seems it is not available from the Fluxstore app. Thank you!

**Comment by mhdag1** [comment]
Hello there,

In the provided screenshot, you can see that the stocks are managed in different warehouses. We want to the stock, category and product data to be pulled from a single warehouse.

At this moment, the data is pulled as follows:
- Categories across the board without taking warehouses into account.
- Product Availability/Stock level from the default warehouse.

What is required is:
- Categories based on the product availability of one warehouse (taking Syria as an example).
- Product Availability/Stock level based on that same warehouse.

If that is successful, it is very likely that we will make additional purchases of the application to roll out versions to different regions.

If you require any additional information please let me know. Furthermore, if you need a token for testing, let me know the minimum privileges needed to carry that out, and I will share it with you in a private message.

![WhatsApp Image 2020-08-11 at 12 34 08](https://user-images.githubusercontent.com/57035209/90043774-a1e14680-dcdd-11ea-9597-a4bcc1936213.jpeg)

**Comment by minhcasi** [comment]
@mhdag1 - sorry this feature is kind of advanced features that is not supported by the current Magento API from the Fluxstore app. You could try to customize the app to make it work with your site - thank you!

**Comment by minhcasi** [comment]
Let us know if you have any questions need to support thank you.
