### ISSUE TITLE
Firebase on Android doesn't work 

### ISSUE THREAD

**Issue by vuln3r** [inspireui/support#4542]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
- [1] first issue
I'm trying to register firebase on android but wasn't able to do it. I got stuck on this:

![image](https://user-images.githubusercontent.com/13506241/89739604-46674c80-da82-11ea-9811-9bc7807d2681.png)

I followed the tutorial from here: https://docs.inspireui.com/fluxstore/firebase/

- [2] second issue

Also, onesignal notifications are not working but I think it is connected with firebase and once firebase starts to work onesignal will work too.

![image](https://user-images.githubusercontent.com/13506241/89739637-a0681200-da82-11ea-9aa5-46cd5905c717.png)

+ Product & version: 1.7.6 Fluxstore
+ Flutter (or React Native) version: 1.20.1
+ Testing Device/Simulator: Android 10 (API 29) (emulator)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**
I did verify myself in the previous ticket.

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by ameenbadri7** [comment]
Hi, @vuln3r 
Use those guidelines to help with setting the app. 

https://docs.inspireui.com/fluxstore/sign-in/

https://docs.inspireui.com/fluxstore/firebase/

Thank you for your time.

**Comment by vuln3r** [comment]
Hi @ameenbadri7, like I said I've followed the firebase tutorial but still it doesn't work here is what I'm getting in the console:

`W/FirebaseMessagingPlugin( 8474): getToken, error fetching instanceID: 
W/FirebaseMessagingPlugin( 8474): java.io.IOException: SERVICE_NOT_AVAILABLE
W/FirebaseMessagingPlugin( 8474):       at com.google.firebase.iid.zzl.zza(com.google.firebase:firebase-iid@@20.0.1:60)
W/FirebaseMessagingPlugin( 8474):       at com.google.firebase.iid.zzl.zza(com.google.firebase:firebase-iid@@20.0.1:84)
W/FirebaseMessagingPlugin( 8474):       at com.google.firebase.iid.zzp.then(com.google.firebase:firebase-iid@@20.0.1:4)
W/FirebaseMessagingPlugin( 8474):       at com.google.android.gms.tasks.zzd.run(Unknown Source:5)
W/FirebaseMessagingPlugin( 8474):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/FirebaseMessagingPlugin( 8474):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/FirebaseMessagingPlugin( 8474):       at java.lang.Thread.run(Thread.java:923)
W/FirebaseInstanceId( 8474): Token retrieval failed without exception message. Will retry token retrieval`

**Comment by ameenbadri7** [comment]
Did you try that with your real device or just the emulator sir?
It's working with all customers on the latest update.
Some times its happened to miss a spot in the tutorial please double check it.

**Comment by vuln3r** [comment]
Hi @ameenbadri7,  I'm using an emulator for it and I manage it to work - it was something broken because of the merge conflict that I had. (Firebase and OneSignal on Android are fine)

But OneSignal on iOS still doesn't work... I'm getting this error in Xcode 

`2020-08-10 22:22:19.455407+0200 Runner[8788:2695839] WARNING: OneSignal has detected that your application delegate implements a deprecated method (application:didReceiveLocalNotification:). Please note that this method has been officially deprecated and the OneSignal SDK will no longer call it. You should use UNUserNotificationCenter instead`

For testing this I'm using iPhone XS real device on iOS 13.6.0

**Comment by ameenbadri7** [comment]
Please note that we may not support answering or support technical issues for the regular license as per support policies - https://inspireui.com/support-policies/ 
- but we are trying to best to give extra miles with the supporting.

**Comment by vuln3r** [comment]
I understand that and I didn't ask for it 😉 ... just saying that OneSignal on iOS doesn't work and that are the errors I get in the console, perhaps it would help to solve the problem quickly.

**Comment by vuln3r** [comment]
I've solved it on my own... the issue was that in `AppDelegate.swift` Firebase uses APNs for registration and that's blocking OneSignal to get APNs. 

You need just to delete the code here and it works as it should:
![image](https://user-images.githubusercontent.com/13506241/89865183-8a0aa500-dbad-11ea-90f9-3a845bb8bbf9.png)

**Comment by ameenbadri7** [comment]
Thank you @vuln3r 
I searched now for your problem, from my point of view that you are doing something extra or less than our recommended settings, that we write in the tutorials.
Please, sir, try update to fluxstore latest version 1.7.7 it came out yesterday, the main features about it that it support the new flutter and dart update 1.20.1 and a lot of powerful fixes.
Please note: we all using the fluxstore in our sites and our customer's sites, and the notification it's working perfectly.
Try your best to integrate the your notification.

Happy coding !
