### ISSUE TITLE
Store map not works according Wordpress dokan location 

### ISSUE THREAD

**Issue by ssathamenterprises** [inspireui/support#4543]
1. The store location always show other country location, ( always shows Ho Chi Minh city )

2. When I click direction also it’s shows Ho Chi Minh city

Not syncing with dokan store location 

Please help on this my proof of purchase screenshot I attached here
![7A11D1C5-BD3D-455B-B26D-F8ABB931AED7](https://user-images.githubusercontent.com/68118999/89745074-ed300500-dae3-11ea-9a54-00cd9d08783d.jpeg)

**Comment by tgloc96** [comment]
Hi @ssathamenterprises 
Can you please post an image or video about this error?
Thank you for your time.

**Comment by ssathamenterprises** [comment]
This one shows wrong direction my all shop stores located at india ( tamilnadu ) but when I try to use fluxstore mv to check the location of store it’s always shows minh city other country 


You can check my app ( in drive I attached the apk )

https://drive.google.com/file/d/1CYaqYq0mit-M5NnTDkiB4L8eiva2CU-E/view?usp=drivesdk

**Comment by tgloc96** [comment]
> https://drive.google.com/file/d/1CYaqYq0mit-M5NnTDkiB4L8eiva2CU-E/view?usp=drivesdk

Excuse me, but I cannot install the app from this file. Please check again.

**Comment by ssathamenterprises** [comment]
please help on this sir
last stage of my mobile app setup , please

**Comment by minhcasi** [comment]
@ssathamenterprises - could you give a try with latest stable version `1.7.7` - thanks

**Comment by ssathamenterprises** [comment]
Same issues sir not loading the correct location, in this version I attached some photos I tried with new version please help me sir , last 7 months I try to complete the app But still I can’t please help me sir 
![A7205DF7-14AA-49D6-9331-530311F07D02](https://user-images.githubusercontent.com/68118999/90325282-384a8c00-dfac-11ea-853a-9c2ac70f941f.jpeg)
![19DD9DB0-9F88-4379-AA6D-D6A3177445D3](https://user-images.githubusercontent.com/68118999/90325284-426c8a80-dfac-11ea-942f-c90198c8d21a.jpeg)
![FB182B8A-846B-4EC5-BB71-1DC042B5AD62](https://user-images.githubusercontent.com/68118999/90325286-44364e00-dfac-11ea-950e-eef47e02bf34.jpeg)
![9A2E74D5-B9B2-4145-876B-A5B9E0087837](https://user-images.githubusercontent.com/68118999/90325287-45677b00-dfac-11ea-897e-6ec14a6074d9.jpeg)

**Comment by tgloc96** [comment]
We are investigating, please wait. Thank you for your time.

**Comment by ssathamenterprises** [comment]
Ok sir

**Comment by ssathamenterprises** [comment]
sorry to disturb sir , still not works , actually my dokan multi vendor site  rest api only gave to your team for test this geo features, please help on this 
![Screenshot (22)](https://user-images.githubusercontent.com/68118999/91053801-f8437300-e655-11ea-8ff9-4c98c9319d6e.png)
<img width="960" alt="Screenshot (23)" src="https://user-images.githubusercontent.com/68118999/91053812-faa5cd00-e655-11ea-8d88-dbb2c2142cd3.png">

**Comment by tgloc96** [comment]
Can you send me your full source code so I can check it out?

**Comment by tgloc96** [comment]
Please send your full source code via email tgloc96@gmail.com. Thank you.

**Comment by ssathamenterprises** [comment]
source send to your email sir  ssathementerprises@gmail.com  use mydrive

**Comment by tgloc96** [comment]
> source send to your email sir [ssathementerprises@gmail.com](mailto:ssathementerprises@gmail.com) use mydrive

I was received and downloading....

**Comment by ssathamenterprises** [comment]
ok sir

**Comment by tgloc96** [comment]
@ssathamenterprisesI ran your source code and tested it and it still works normally.

**Comment by ssathamenterprises** [comment]
But the mobile App Store location always shows wrong ( it’s always shows random location Minh city )

**Comment by ssathamenterprises** [comment]
In my app there is few stores , the stores location shows wrong

**Comment by ssathamenterprises** [comment]
![71E32062-E935-4D26-9B5C-EA9DE158C7DF](https://user-images.githubusercontent.com/68118999/91381320-b8e57400-e859-11ea-8338-a015aac4e179.jpeg)

My stores are located at india tamilnadu 

But it’s always show wrong i attached the image

**Comment by ssathamenterprises** [comment]
https://tamizhashop.in/store-listing/

**Comment by tgloc96** [comment]
I saw the error and fixing it.

**Comment by ssathamenterprises** [comment]
Can send me sir ssathamenterprises@gmail.com

**Comment by ssathamenterprises** [comment]
Ok sir

**Comment by ssathamenterprises** [comment]
I received the source code sir , today I check this

**Comment by tgloc96** [comment]
> I received the source code sir , today I check this

Looking forward to hearing from you soon. Thank you for your time.

**Comment by ssathamenterprises** [comment]
Once I chekc and update here sir

**Comment by ssathamenterprises** [comment]
sir the location works perfectly now thanks lot  , if you dont min may i know the issue , next time any issue like this i will do myself

**Comment by tgloc96** [comment]
Thank you for choosing our product ^^.

**Comment by ongaki8** [comment]
Hello @tgloc96 ,
I'm having the same issue with the Store Dokan Location showing a random city in Vietnam. What is the fix?

**Comment by tgloc96** [comment]
> Hello @tgloc96 ,
> I'm having the same issue with the Store Dokan Location showing a random city in Vietnam. What is the fix?

Hello, please download and extract the file below, after that override this file at _"lib/vendor/store/store_model.dart"_
[store_model.dart.zip](https://github.com/inspireui/support/files/5153898/store_model.dart.zip)

**Comment by ongaki8** [comment]
Noted. Thank you

**Comment by tgloc96** [comment]
> Noted. Thank you

Looking forward to hearing from you soon. Thank you for your time.

**Comment by ongaki8** [comment]
My store list map and store lists are now blank after changing that. Am I missing something?

**Comment by ongaki8** [comment]
Is it possible to arrange a live session so that I can share my screen?

**Comment by tgloc96** [comment]
@ongaki8  Please create a new ticket with describing detail your problem and version you are using and Please help us to submit this form and fill all required info to continue with the support https://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation).

**Comment by ongaki8** [comment]
I already have. Check the ticket

https://github.com/inspireui/support/issues/4818
