### ISSUE TITLE
Fluxstore woocommerce search not displaying

### ISSUE THREAD

**Issue by twt93** [inspireui/support#4544]
![Screenshot_20200809-211500.jpg](https://user-images.githubusercontent.com/29052044/89779096-3d898000-db41-11ea-9958-54450845e436.jpg)

**Comment by ameenbadri7** [comment]
Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

**Comment by twt93** [comment]
done i send information
![done](https://user-images.githubusercontent.com/29052044/89794392-91a05e80-db59-11ea-82bc-dd17c621fe51.png)

**Comment by twt93** [comment]
what can i do to solve ?

**Comment by minhcasi** [comment]
it's verified - thank you for your time.

we have tried to test this feature and could not reproduce the issue 
Could i know if you are using the latest Fluxstore `1.7.6` - please note that you could use the latest `1.7.7` on Gitlab as well -

**Comment by twt93** [comment]
I use fluxstore 1.7.6

**Comment by twt93** [comment]
Where i can get the latest version?

**Comment by minhcasi** [comment]
pls submit this form - http://gitlab.inspireui.com/ - the new package will be notified via email soon

**Comment by twt93** [comment]
![Screenshot_20200812-224731_Samsung Internet.jpg](https://user-images.githubusercontent.com/29052044/90029825-e379ed80-dced-11ea-9849-571686c09263.jpg)
Done

**Comment by minhcasi** [comment]
sent, pls update the latest release from Codecayon as well - thank you!

**Comment by twt93** [comment]
okay... i try... thanks

**Comment by twt93** [comment]
![image](https://user-images.githubusercontent.com/29052044/90311693-596d9700-df30-11ea-9c6f-009b41aea2bb.png)
i run pub get in fluxstore 1.7.7 but the message..
can you help me?
