### ISSUE TITLE
[Fluxstore -Woocommerce] :IOS build getting failed in code magic 

### ISSUE THREAD

**Issue by Lokeswara-betha** [inspireui/support#4545]
I am getting the below error while triggering the build for IOS.

❌  error: OneSignalNotificationServiceExtension has conflicting provisioning settings. OneSignalNotificationServiceExtension is automatically signed for development, but a conflicting code signing identity iPhone Distribution has been manually specified. Set the code signing identity value to "iPhone Developer" in the build settings editor, or switch to manual signing in the Signing & Capabilities editor. (in target 'OneSignalNotificationServiceExtension' from project 'Runner')

❌  error: Provisioning profile "XC com nutplanet app app_store 1596980362" doesn't support the App Groups and Associated Domains capability. (in target 'Runner' from project 'Runner')

❌  error: Provisioning profile "XC com nutplanet app app_store 1596980362" doesn't support the group.com.nutplanet.app.onesignal App Group. (in target 'Runner' from project 'Runner')

❌  error: Provisioning profile "XC com nutplanet app app_store 1596980362" doesn't include the com.apple.developer.associated-domains and com.apple.security.application-groups entitlements. (in target 'Runner' from project 'Runner')

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission.

Thank you for your time!

**Comment by minhcasi** [comment]
@Lokeswara-betha - please help to clean up the cache to see it can fix the issue - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

**Comment by ameenbadri7** [comment]
Also after you clean your cache you should try your best to take the right steps by building your IOS app in a real mac even just for one time use the Xcode automatic sign-in, there are a lot of settings you have to do to make it work.

Thank you.
