### ISSUE TITLE
Checkout page redirect to web page of website to complete payment.

### ISSUE THREAD

**Issue by ap26091995** [inspireui/support#4546]
When i add products to cart and checkout, after submitting place my order button it redirect to web page of my website to continue to payment and place order. I didn't want to redirect to web page, instead of web page i want to redirect to app based payment page from where i can place an order. No need to go to website and checkout.
![Simulator Screen Shot - iPhone 11 Pro - 2020-08-10 at 18 08 16](https://user-images.githubusercontent.com/50094453/89783644-eb426200-db34-11ea-9529-7d7f4fd9e22f.png)

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission.

Thank you for your time!

**Comment by ap26091995** [comment]
I have submitted the form. Also username and  certificate attached to the
form

**Comment by minhcasi** [comment]
@ap26091995 - it's verified 

please note that the app only supports native payment for COD, Paypal, Tap. If you use other payment gateways then it will open the Webview to handle the payment as clarifying from this guide https://docs.inspireui.com/fluxstore/multi-payment/

Thank you!

**Comment by ap26091995** [comment]
But the user details that have enter in app during checkout like name, address, etc, that are not showing same as in web view. In web view it again asking for the user details.

**Comment by ap26091995** [comment]
![Simulator Screen Shot - iPhone 11 Pro - 2020-08-11 at 11 41 21](https://user-images.githubusercontent.com/50094453/89863398-a582a980-dbc7-11ea-8416-1533ea48ccfe.png)
Here i am unable to select country. the dropdown menu not showing.

**Comment by ameenbadri7** [comment]
You can disable the address page to go directly to the webview as our customers do for their apps.
On your project file go to `lib\common\config\payments.dart` and edit the file.
I encourage you to change your settings as the following:

"EnableShipping": false,

```
  /// Enable the Google Map picker
  "EnableAddress": false,

  /// Enable the product review option
  "EnableReview": false,

  /// enable the google map picker from Billing Address
  'allowSearchingAddress': false,
  "GuestCheckout": false,

  /// Enable Payment option
  "EnableOnePageCheckout": true,
  "NativeOnePageCheckout": false,

  /// This config is same with checkout page slug in the website
  "CheckoutPageSlug": {"en": "checkout"},

  /// Enable Credit card payment (only available for zeymc Shopipfy)
  "EnableCreditCard": false,

  /// Enable update order status to processing after checkout by COD on woo commerce
  "UpdateOrderStatus": true,

  /// Show Refund and Order button on Order Detail
  "EnableRefundCancel": false
```

Thank you.

**Comment by ap26091995** [comment]
> ![Simulator Screen Shot - iPhone 11 Pro - 2020-08-11 at 11 41 21](https://user-images.githubusercontent.com/50094453/89863398-a582a980-dbc7-11ea-8416-1533ea48ccfe.png)
> Here i am unable to select country. the dropdown menu not showing.

**Comment by ap26091995** [comment]
How can be layout can be arranged on homepage like show product by latest, bestsellers, and specials like in website?

**Comment by ap26091995** [comment]
Anyone there.? I need to solve above one by urgent.

**Comment by minhcasi** [comment]
@ap26091995 - you could try to use the Fluxbuilder to update the homepage customization - http://fluxbuilder.com/ - thank you!

**Comment by ap26091995** [comment]
> FluxBuilder - An Ultimate Approach For Flutter Mobile Apps

And For Country select drop down? I am unable to select country during checkout

**Comment by ap26091995** [comment]
How can i add phone number during registration in app?

**Comment by ap26091995** [comment]
anyone there who could help me?

**Comment by ameenbadri7** [comment]
you can use the [documentation ](https://docs.inspireui.com/fluxstore/customization/)to know more about config your app.
if you want to add SMS verification you will find a separate guide inside the [documentation](https://docs.inspireui.com/fluxstore/sign-in/) 

also, you can find answers to all your question if you read the documentation.

so I will go ahead and close this thread.
If you continue to have the current issue please reply and let us know, otherwise if you have a new issue open a new thread.
