### ISSUE TITLE
Unable to connect to WooCommerce API

### ISSUE THREAD

**Issue by SingHar** [inspireui/support#4548]
**FlutterBuilder of InspireUI** is unable to connect to **WooCommerce API**.

I have verified the API using `Postman` and the API is working fine.

_PS_: Installed Mstore API (Version 2.8.3) from WordPress repo. Activated the same using purchase code from Envato.

![Screenshot 2020-08-10 at 8 34 53 PM](https://user-images.githubusercontent.com/7950574/89797808-028b4a80-db49-11ea-82d8-de7bbb868c2c.png)

![Screenshot 2020-08-10 at 8 31 21 PM](https://user-images.githubusercontent.com/7950574/89798083-5c8c1000-db49-11ea-8e12-93a44d06c6d9.png)

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 

Thank you for your time!

**Comment by SingHar** [comment]
Submitted additional data through Google Forms.

**Comment by minhcasi** [comment]
@SingHar - this could be the bug from Fluxbuilder - we will have a check and include the fix on next Fluxbuilder `1.0.7` in 1-2 days - thank you!

**Comment by minhcasi** [comment]
It's ready for downloading, please keep new update - https://github.com/inspireui/fluxbuilder/releases/tag/v1.0.7 - thank you!

**Comment by SingHar** [comment]
I have updated to the latest version. The interface is better and I was able to pin down the issue.

FluxBuilder is using `WooCommerce` API `v2` instead of latest `v3` so I need to enable `Legacy API`

However, the app is still not connecting to back-end properly. The API keys are being rejected.

But same keys are working if I use it through Postman. Please see the screenshot where I am trying to update product title using API (to test read/write access of keys). Its working fine.

## Using same API keys
![Screenshot 2020-08-15 at 7 35 17 PM](https://user-images.githubusercontent.com/7950574/90315352-802fcb80-df38-11ea-8077-7b32816d6947.png)

## Data updated
![Screenshot 2020-08-15 at 8 45 42 PM](https://user-images.githubusercontent.com/7950574/90315349-7c03ae00-df38-11ea-98f1-30c2eecc5bef.png)

## Same API keys are failing in FluxBuilder 
![Screenshot 2020-08-15 at 7 42 24 PM](https://user-images.githubusercontent.com/7950574/90315353-81f98f00-df38-11ea-9987-6d566920a688.png)
