### ISSUE TITLE
How to edit GraphQL in Shopify?

### ISSUE THREAD

**Issue by Puie** [inspireui/support#4549]
Where to find GraphQL editor for Shopify like your tutorial video? Please help me out. Thank you.

![Google Chrome_2020-08-10 21-42-31@2x](https://user-images.githubusercontent.com/35200707/89801473-39b42880-db56-11ea-8483-9b01bec38c1f.png)

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 

Thank you for your time!

**Comment by minhcasi** [comment]
@Puie - you could install this tool https://www.electronjs.org/apps/graphiql or any app that could run GraphQL query
