### ISSUE TITLE
[ListApp] Add Listing Map - 

### ISSUE THREAD

**Issue by aymanshawky0001** [inspireui/support#455]
**Required Info (please complete the following information):**
 - Product: [ListApp]
 - Your Purchased Code: [bdbfc344-e591-426d-8772-271220acdc47]
(we may not reply if you are not our customer)

**Describe the bug**
1- My Categories without Photo
2- if you press back button nothing happen
3- add listing map error on second phase and close my app
4- how i add my logo on the app interface?
5- after click on news or posts it return to close and open my app

**Screenshots**

**Additional context**
Add any other detail logs about the problem here.
If possible please share your config.js that use for the app setting

**Comment by webbosolutions** [comment]
https://1drv.ms/u/s!AgeUYtNV693Igqp78ET1GOGI_H-JAg
Screenshot

**Comment by webbosolutions** [comment]
https://1drv.ms/u/s!AgeUYtNV693Igqp8HCp1qrZjYZnsWg

**Comment by thangvo9x** [comment]
Try go to Container/Categories/index.js and comment this line 
<img width="494" alt="issue" src="https://user-images.githubusercontent.com/23457178/55449049-52bcd900-55f4-11e9-8e2d-a7d996b86541.png">

**Comment by aymanshawky0001** [comment]
https://1drv.ms/u/s!AgeUYtNV693Igqp7cd7-v89cMQrdLw

thanks for reply
what about this problem after select location on map in  add listing
please

**Comment by thangvo9x** [comment]
Select location isn't autocompleted & generate address fill into text. you must have click on the map.
You can send email to support@inspireui.com with the subject is id 455 for helping. Thanks.
