### ISSUE TITLE
App Session Logs out In Magento 2.3.5

### ISSUE THREAD

**Issue by mailfordipak** [inspireui/support#4550]
While Using App With Magento 2.3.5 if we close the app , multiple tabs app gets auto logged out.
Client have to re log in to app again while using the app for shopping.

**Comment by minhcasi** [comment]
Could you share the screenshot/video issues? Thank you!

**Comment by mailfordipak** [comment]
@minhcasi minhcasi @ameenbadri7 Please Check attached Video.

[ISSUE RECORDING.zip](https://github.com/inspireui/support/files/5055684/ISSUE.RECORDING.zip)

Regards

**Comment by mailfordipak** [comment]
> 
> 
> @minhcasi minhcasi @ameenbadri7 Please Check attached Video.
> 
> [ISSUE RECORDING.zip](https://github.com/inspireui/support/files/5055684/ISSUE.RECORDING.zip)
> 
> Regards

@minhcasi @luyx2412 @trunghieuvn @ameenbadri7 

Please check the attached video recording for the issue , thats causing the app auto logout.

**Comment by minhcasi** [comment]
@minhtruong315 - pls help to check this issue

**Comment by minhtruong315** [comment]
Hi @mailfordipak You need to set expired token time to fix this issue. you can follow below path:
1. Admin -> Stores -> Configurations -> Services -> OAuth -> 
2. select tab: "Access Token Expiration"
3. Will get 2 settings: customer Token LifeTime and admin Token LifeTime.
4. Set both its values to 0 ( token do not expired). You may have to uncheck "Use system value" checkbox to change its default values.

**Comment by mailfordipak** [comment]
> 
> 
> Hi @mailfordipak You need to set expired token time to fix this issue. you can follow below path:
> 
>     1. Admin -> Stores -> Configurations -> Services -> OAuth ->
> 
>     2. select tab: "Access Token Expiration"
> 
>     3. Will get 2 settings: customer Token LifeTime and admin Token LifeTime.
> 
>     4. Set both its values to 0 ( token do not expired). You may have to uncheck "Use system value" checkbox to change its default values.

@minhcasi @minhtruong315  Hello , Tried Your Solution That Didnt Worked !!!

Please Understand the Issue , Once Logged in app unless we manually signout it shouldnt logout a user , even if they close the app.

**Comment by minhtruong315** [comment]
@mailfordipak give me your skype. I will help u check remotely

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
