### ISSUE TITLE
How can I remove contact from seller profile ...?

### ISSUE THREAD

**Issue by eraldix** [inspireui/support#4551]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: How to remove Contact from seller page and the map icon on the categories/store page as seen on the screen shots. Also when i translate the review The R in the middle is uppercase, how can I fix that
- [x] first issue
- [x] second issue
- [x] third issue

+ Product & version:Multivendor
+ Flutter (or React Native) version:flutter latest 
+ Testing Device/Simulator: both
+ Screenshot issues (drag the file to attach here): 
![Screenshot_1597080929](https://user-images.githubusercontent.com/44481659/89814285-319ebd80-db43-11ea-80f1-b94dc4525cc2.png)
![Screenshot_1597081104](https://user-images.githubusercontent.com/44481659/89814290-34011780-db43-11ea-9705-8d71d20de488.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@eraldix - you could try to use the Inspector to find the related file and made this customization - please refer to https://www.youtube.com/watch?v=yGMt3Y20Zmg - thank you!

**Comment by ameenbadri7** [comment]
Hi, @eraldix

We haven’t heard back from you in a while, so I’m going to mark this ticket as resolved – if you have any further questions, you can start a new ticket.

Thank you very much ❤️
