### ISSUE TITLE
woo-commerce setup

### ISSUE THREAD

**Issue by destek-harshadapatil** [inspireui/support#4552]
Thank you team for your help.

We are adding our own PHP backend for that we wanted to use 

Framework - code ignitor framework or we can also use lara well framwork &
API - Rest API 

So, How could I replace or add my API's ?  please help.

Thanks and Regards!

_Originally posted by @destek-harshadapatil in https://github.com/inspireui/support/issues/4524#issuecomment-671174923_

**Comment by minhcasi** [comment]
@destek-harshadapatil - you could customize the app API 

Example: fetch the category from other API you need to:
- update service file - https://tppr.me/28us6 and also 
- update model file - https://tppr.me/siNKZ

Please help to give your comments to one ticket support - #4523
