### ISSUE TITLE
Splash screen size issue

### ISSUE THREAD

**Issue by destek-harshadapatil** [inspireui/support#4553]
Sure sir I will give you a demo image shortly for the UI feature which you have asked for.

I want to set my splash-screen image but I am not getting exact size for it. I have created many images but sometimes the image height is not perfectly set or sometimes the width. For your reference I have attached one splash-screen image screenshot and size of that image.
In below image you can see the height is not perfectly covered. 
Size - 928*1,792 PNG

Please guide me where should I set the height and width or I have to change in file that the splash-screen will show perfectly.

![Screenshot_20200810-150836](https://user-images.githubusercontent.com/62869560/89770166-005ec700-db1c-11ea-9469-ecb52cdac737.jpg)

_Originally posted by @destek-harshadapatil in https://github.com/inspireui/support/issues/4523#issuecomment-671260566_

**Comment by minhcasi** [comment]
@destek-harshadapatil - we got your comment from this ticket #4523 👍
