### ISSUE TITLE
Fluxstore Common Question and Thank-You

### ISSUE THREAD

**Issue by esolksaapp** [inspireui/support#4554]
Hello @minhcasi I have Just left my review to Fluxstore and will also leave my review for other products as well which I have License of 
I just have these few Questions please help me ! 

<img width="616" alt="Screenshot 2020-08-11 at 10 53 42 AM" src="https://user-images.githubusercontent.com/68499329/89862301-17a3c000-dbc1-11ea-97a9-ce10f982ec2f.png">

**Question 1:  
I want to Use dynamic links to show products via Push Notifications so Whenever user Clicks on the PushNotification app should take him to that specific product Using one signal or firebase .  Using one signal I am able to open my desired url but it’s in the browser I want to open it in the app.  
I have seen the docs and  deeplink_item.dart and found out that you guys have coded deep link to be only for the using the blog posts. 

Question 2: >> Mocks folder 
What is the usage of mocks folder under lib / mocks and how I can use it in my project? 

Question 3 :   How much time will it take to make M-store API take 2 or more config files for caching like config_en.json and config_ar.json at the same time ?**

**Comment by minhcasi** [comment]
@esolksaapp - thank you so much for the rating, we are happy to upgrade the ticket as high priority support. 

The mock option is used for testing the local data once you don't have the server, it will load the local JSON to display on the app, you could enable the `woo-mock` from the `config.dart` file (we will update this guide on our document)

The question-1 and 2 are not available features, I'm checking with the team to upgrade it on the next release - we will notify on this ticket when it is ready for testing.

**Comment by minhcasi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Feature: support multi language config](https://trello.com/c/eLJQaYFl/61-feature-support-multi-language-config)

**Comment by minhcasi** [comment]
moved to Trello update and we will update 2 requests on next `1.7.8` release - thank you!
