### ISSUE TITLE
ListTile widget layout throws assertion error

### ISSUE THREAD

**Issue by jibrail-idris** [inspireui/support#4555]
The list layout throws an assertion error due to variable widthContent having the value 0. The else-if (widget.layout == "listTile") does not compute the width content and store it in widthContent variable, hence the error.

/source/lib/widgets/product/product_list.dart

```
    var widthScreen = widget.width != null ? widget.width : screenSize.width;
    var widthContent = 0.0;
    var crossAxisCount = 1;
    var childAspectRatio = 0.8;

    if (kLayoutWeb) {
      widthScreen -= BackdropConstants.drawerWidth;
    }
    if (widget.layout == "card") {
      crossAxisCount = isTablet ? 2 : 1;
      widthContent = isTablet ? widthScreen / 2 : widthScreen; //one column
    } else if (widget.layout == "columns") {
      crossAxisCount = isTablet ? 4 : 3;
      widthContent =
          isTablet ? widthScreen / 4 : (widthScreen / 3); //three columns
    } else if (widget.layout == "listTile") {
      crossAxisCount = isTablet ? 2 : 1;

      // BUG: widthContent not computed


    } else {
      /// 2 columns on mobile, 3 columsn on ipad
      crossAxisCount = isTablet ? 3 : 2;
      //layout is list
      widthContent =
          isTablet ? widthScreen / 3 : (widthScreen / 2); //two columns
    }

    // ISSUE NOTE: childAspectRatio is 0 because widthContent is 0.

    childAspectRatio =
        (isTablet ? 0.94 : 1) * widthContent / (widthContent * 1.2 + 119);
```

```
...
...
return SmartRefresher(
      header: MaterialClassicHeader(
        backgroundColor: Theme.of(context).backgroundColor,
      ),
      enablePullDown: true,
      enablePullUp: !widget.isEnd,
      controller: _refreshController,
      onRefresh: _onRefresh,
      onLoading: _onLoading,
      footer: kCustomFooter(context),
      child: widget.layout != "pinterest"
          ? GridView.builder(
              gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
                crossAxisCount: crossAxisCount,
                childAspectRatio: childAspectRatio,
              ),
```
...
...

```
const SliverGridDelegateWithFixedCrossAxisCount({
    @required this.crossAxisCount,
    this.mainAxisSpacing = 0.0,
    this.crossAxisSpacing = 0.0,
    this.childAspectRatio = 1.0,
  }) : assert(crossAxisCount != null && crossAxisCount > 0),
       assert(mainAxisSpacing != null && mainAxisSpacing >= 0),
       assert(crossAxisSpacing != null && crossAxisSpacing >= 0),
       assert(childAspectRatio != null && childAspectRatio > 0);
```

![image](https://user-images.githubusercontent.com/3234559/89867149-50549100-dbe3-11ea-896c-ca5569437faf.png)

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 

Thank you for your time!

**Comment by jibrail-idris** [comment]
> Thank you for the feedback.
> 
> Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.
> 
> We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission.
> 
> Thank you for your time!
> 
> > **[Google Forms - create and analyze surveys, for free.](http://verify.inspireui.com/)**Create a new survey on your own or with others at the same time. Choose from a variety of survey types and analyze results in Google Forms. Free from Google.

Done

**Comment by ameenbadri7** [comment]
Hi, @jibrail-idris 
In the latest version, we fix this error.
Could you please download the 1.7.7 version and see if your problem solved.
Thank you.

**Comment by jibrail-idris** [comment]
> Hi, @jibrail-idris
> In the latest version, we fix this error.
> Could you please download the 1.7.7 version and see if your problem solved.
> Thank you.

Where do I download 1.7.7? CodeCanyon has 1.7.6.

**Comment by ameenbadri7** [comment]
hello,
Please help to submit access to [gitlab](http://gitlab.inspireui.com .)
Thank you.

**Comment by jibrail-idris** [comment]
> hello,
> Please help to submit access to [gitlab](http://gitlab.inspireui.com .)
> Thank you.
> 
> > **[Google Forms - create and analyze surveys, for free.](http://gitlab.inspireui.com/)**Create a new survey on your own or with others at the same time. Choose from a variety of survey types and analyze results in Google Forms. Free from Google.

Done!

It says that waiting time is about 1 to 2 weeks.

**Comment by ameenbadri7** [comment]
We are trying our best to send the invitation to you ASAP.

So I’m going to mark this ticket as resolved – if you have any further questions, you can start a new thread.

Thank you.
