### ISSUE TITLE
#4196 Products not showing the price and vendor.  

### ISSUE THREAD

**Issue by Shiru-kun** [inspireui/support#4557]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
- [ ] first issue
 I got a  plugin in my website named yith catalog that show a button to send the user to a social media app. 
but inside the fluxstore app it shows with price 0.0 and i can even add it with other products inside cart. 
THere is a way to not show such products... or make add to cart unavailable. 

- [ ] second issue
For some products i cant see the vendors. as show in screenshot

- [ ] third issue
I want to have the social login methods in the register screen can u help me that? 
i want it both in login screen and register screen. 

+ Product & version:
Fluxstore 1.7.6 
+ Flutter (or React Native) version: 
Flutter 1.20
+ Testing Device/Simulator: 
real device samsung galaxy  A01 android 10
+ Screenshot issues (drag the file to attach here): 

issue 01 
![01](https://user-images.githubusercontent.com/54008441/89868537-40bd5400-dbb3-11ea-917f-d8580c07315f.jpg)
  
Issue 02 
![02](https://user-images.githubusercontent.com/54008441/89868656-782c0080-dbb3-11ea-99fd-ddd0018fdd79.jpg)

issue 03 
![03](https://user-images.githubusercontent.com/54008441/89869612-e3c29d80-dbb4-11ea-8667-4446a70ec71b.jpg)
![04](https://user-images.githubusercontent.com/54008441/89869632-ea511500-dbb4-11ea-8329-bd74fce4e884.jpg)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@Shiru-kun - thank you for detail explanation and screenshot quetions

Could I confirm you are using the Fluxstore Multi-Vendor to display the vendor while the ticket is reported for Fluxstore product?

It's possible please share your source to inspireui.team@gmail.com - we will help to check some point in the 1-2 question, the social login on registration is not ready but we will add this option on next release

**Comment by Shiru-kun** [comment]
Sorry its the mutivendor.
 i'll send asap.
Thank you.

>

**Comment by Shiru-kun** [comment]
@minhcasi check your email

**Comment by minhcasi** [comment]
@tgloc96 - pls help with checking

**Comment by Shiru-kun** [comment]
I already send to the inspireui email support

**Comment by Shiru-kun** [comment]
@tgloc96

**Comment by tgloc96** [comment]
Hi @Shiru-kun ,
- The first issue: May sound you want to change the status of the product is out of stock, If you want that, you have to configure a property of product following an image below
<img width="1114" alt="image" src="https://user-images.githubusercontent.com/46434718/90310171-426f7a80-df19-11ea-9600-1d55193b1084.png">

- The second issue, I think you don't configure vendor for the product, please you check again.
- The third issue, I will put the icon login social at the screen sign up, but if you click to the icon, it will back to the login screen  and use method login you were clicking before.

**Comment by Shiru-kun** [comment]
hello about solution u purpose its not that
 i tried it too. .
in my website it shows like this: 
![image](https://user-images.githubusercontent.com/54008441/90314349-629c3b00-df13-11ea-88f7-25f9efe86975.png)
 translated its  "more info".

**Comment by tgloc96** [comment]
> hello about solution u purpose its not that
> i tried it too. .
> in my website it shows like this, i have a plugin installed that show for the user this message as show below.:
> ![image](https://user-images.githubusercontent.com/54008441/90314349-629c3b00-df13-11ea-88f7-25f9efe86975.png)
> translated its "more info".

For now, we just support the change status of the product is in of stock or out of stock and this means to hide or show button add to cart, and about the feature you suggest above is not available, but you could try to customize it.

**Comment by Shiru-kun** [comment]
ok i understand... thank u
