### ISSUE TITLE
Showing "No Products" when i reopen particular category

### ISSUE THREAD

**Issue by akhiltrivedi** [inspireui/support#4559]
Hello I purchased flux store Shopify app, connected my store with app and it seems to be connected as I can see list of products under different categories as my store, but I noticed one issue like when I click on particular category for eg: flavours, it will show me a list of products in it, but once I come back on the home screen and click on that category again it will show me "No Products". I am attaching video link I have recorded my screen for it.

https://drive.google.com/file/d/1d-2N1DKUCV-Ias012FxUlS5auDiT5pJk/view?usp=sharing

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 

Thank you for your time!

**Comment by akhiltrivedi** [comment]
Hello submitted details in google forms 

![image](https://user-images.githubusercontent.com/7479005/89937938-638f4d00-dc33-11ea-8466-7913ab73f846.png)

**Comment by minhcasi** [comment]
@luyx2412 - pls help to suggest on this issue

**Comment by luyx2412** [comment]
Hi @akhiltrivedi I just invited you to the latest version repo of Fluxshopify. Please pull and merge with your current code which will fix the issue.

Thanks

**Comment by akhiltrivedi** [comment]
Okay @luyx2412 will check it and get back on this ticket if issue remains same.

Thanks

**Comment by akhiltrivedi** [comment]
Hello i can't see any request , can you send me again ?

**Comment by luyx2412** [comment]
Hi @akhiltrivedi I invited via this email, please check it
![image](https://user-images.githubusercontent.com/8909619/90144491-1503bf00-dda9-11ea-932a-7b6812b192ee.png)

Thanks

**Comment by akhiltrivedi** [comment]
Okay, I accepted the request and joined but can't see from where exactly should I pull the files? @luyx2412

**Comment by luyx2412** [comment]
Hi @akhiltrivedi Please clone the project and merge with your current project.

Thanks
