### ISSUE TITLE
[MStore] How to debug mstore expo app

### ISSUE THREAD

**Issue by rajendar123** [inspireui/support#456]
Hi,
Product -MStore expo app
purse code is : c01d05d8-013a-41e7-acd3-79a6847fdc13
Is there any better option debug code.
expo taking more time
--------------
MStore app is very slow.
>> Is problem from react-native ?
>> MStore app ?
>> or with server ?
Is there any way to check this?

**Comment by luyx2412** [comment]
HI @rajendar123 You meant want to change expo version to original react native, please use Mstore pro which original react native app.

Thanks
