### ISSUE TITLE
sign up with email and passwd doesn't work

### ISSUE THREAD

**Issue by tao0103** [inspireui/support#4562]
**_Step 1 (require): describe detail issues & screenshots_**

Can't submit registion data to prestashop by webservice.I checked the common issue https://docs.inspireui.com/fluxstore/common-issues/#-unexpected-character-at-character-1, but I always use https. 

+ Product & version: flux store prestashop 1.7.6
+ Flutter (or React Native) version:   flutter 1.17.5
+ Testing Device/Simulator:   simulator
+ Screenshot issues (drag the file to attach here): 
![image](https://user-images.githubusercontent.com/26236559/89886891-a7e80200-dbcd-11ea-89e0-49169fd974a8.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by ameenbadri7** [comment]
Can you provide screenshots from the app, please?

Thank you.

**Comment by tao0103** [comment]
> Can you provide screenshots from the app, please?
> 
> Thank you.

![image](https://user-images.githubusercontent.com/26236559/89987234-fce35100-dc7d-11ea-8fa7-f9f18856abe0.png)

**Comment by vumanhsn97** [comment]
@tao0103 
Can you share your webservice key?

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
