### ISSUE TITLE
SMS Login

### ISSUE THREAD

**Issue by skalumek** [inspireui/support#4564]
Hello
I am having an issue with SMS login.
I am getting an error that this app is not authorized to use Firebase authentication, please check SHA-1.... App validation failed, for a phone number that is not registered on Firebase.

For existing number that is on Firebase, it doesn't move to next step after clicking sign in.

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission.

Thank you for your time!

**Comment by minhcasi** [comment]
@skalumek - pls follow this solution to fix the login issue - https://github.com/inspireui/support/issues/3151#issuecomment-633489369

**Comment by skalumek** [comment]
Am getting similar error on Android
Error: 'package:flutter/src/widgets/localizations.dart': Failed assertion: line 453 pos 12: 'context != null': is not true. after entering sms validation code., please assist

**Comment by skalumek** [comment]
Hello team, anyone with solution for the issue?

**Comment by skalumek** [comment]
Sign up also is not working, it gives an error, You are allowed to do this. 
Guys I have not not moved since I purchased this source, it's abit frustrating, nothing works..and support requests, no one replies!!

**Comment by ameenbadri7** [comment]
We upgrade our multivendor app to `Release 1.7.7 ` could please download the new update and see if your problem solved.
Please help to submit access to http://gitlab.inspireui.com if you haven't yet been added.

Thank you.

**Comment by skalumek** [comment]
I am using the latest version 1.7.7, same error.

**Comment by skalumek** [comment]
Hello
please advise, if yours is working fine, tell me what to do.

Error: 'package:flutter/src/widgets/localizations.dart': Failed assertion: line 453 pos 12: 'context != null': is not true. after entering sms validation code., please assist

**Comment by Mehdi94i** [comment]
> Bonjour
> s'il vous plaît aviser, si le vôtre fonctionne bien, dites-moi quoi faire.
> 
> Erreur: 'package: flutter / src / widgets / localisations.dart': Échec de l'assertion: ligne 453 pos 12: 'context! = Null': n'est pas vrai. après avoir entré le code de validation sms., veuillez aider

same error to me too please help me
