### ISSUE TITLE
Fluxnews - Pull To Refresh

### ISSUE THREAD

**Issue by rmonst3r** [inspireui/support#4565]
Hi Guys,

A new issue here that we discovered.

After the app has been running in the background for a while and opened again, it shows old stories.
When a user pulls to refresh nothing happens on the home screen but when pulling to refresh on

+ Product & version: Fluxnews latest
+ Flutter (or React Native) version: 1.17.5
+ Testing Device/Simulator: iPhone 11 Pro Max
+ Screenshot issues (drag the file to attach here): https://streamable.com/r9j2xv

**Comment by ahmadhassan7** [comment]
Hi @rmonst3r can you guide how to connect fluxnews to wordpress site. I dont have access to the site i only got its url. The documentation is poor it tells nothing.

**Comment by minhcasi** [comment]
@dttrung26 - pls help to investigate the issue

**Comment by dttrung26** [comment]
The solution will be provided permanently in the next patch.
