### ISSUE TITLE
Not sending e-mail to cliente and store

### ISSUE THREAD

**Issue by dinaramalho** [inspireui/support#4566]
After the user checks out the purchase, the Fluxstore app, connected to the opencart, does not send any email to the customer to confirm the purchase or to the store. Do I need to configure anything in the application? I already put it in the opencart backoffice but it doesn't work.

**Comment by minhcasi** [comment]
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by dinaramalho** [comment]
I have already submitted the form as requested. Thanks

**Comment by minhcasi** [comment]
@dinaramalho - thank you for quick response, it is verified ✅

@minhtruong315 - please help to check the notification email after the user register to the app (opencart issue) - thank you!

**Comment by dinaramalho** [comment]
@minhcasi - When the user creates the account, the app is sending the email correctly. But when make the purchase, still don't send the email. Would it be possible to help solve the problem? Thanks

**Comment by minhcasi** [comment]
@dinaramalho - sorry this is limited from the Opencart API that does not support for push notification after purchase, could you help to check if it is happened the same when purchasing on your website?

**Comment by dinaramalho** [comment]
@minhcasi - I had already tested it, so I decided to open the ticket, because when we make the purchase through the website it sends the email to the customer. Thanks

**Comment by minhcasi** [comment]
@dinaramalho - could you help to download the latest release `1.7.7` - we have improve the config https://tppr.me/NBpDQ and update some bug fix (it has just released on yesterday) - thank you!

**Comment by dinaramalho** [comment]
@minhcasi - The images you published are from Prestashop, and in my case, the store is on the opencart. Were any changes made in opencart api? Thanks

**Comment by minhcasi** [comment]
@dinaramalho - sorry it's my fault 

The Opencart API is not ready support for this feature, I have noted as feature request for further investigating - thank you!

**Comment by minhcasi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Opencart: send email to client & store owner](https://trello.com/c/gaVGaPY5/68-opencart-send-email-to-client-store-owner)

**Comment by minhcasi** [comment]
moved to team's trello board
