### ISSUE TITLE
product Variable #4516

### ISSUE THREAD

**Issue by iqmtgar** [inspireui/support#4567]
hi how are you
I am tired of this problem and I don’t know how to fix it
Sometimes this feature works, and sometimes it doesn't
I don't know the reason
![image](https://user-images.githubusercontent.com/33340985/89938953-ead2c580-dc1f-11ea-963c-b1b06838f27f.png)
When I pick a specific type
Choose something else auto
Sometimes it works without problems?

**Comment by iqmtgar** [comment]
Also when I exit a product
And I enter it again
It works without problems
But if, for example, you choose
Red color
And then I chose black
It automatically selects a red color
not black

**Comment by minhcasi** [comment]
@tgloc96 - please help to investigate this issue

**Comment by tgloc96** [comment]
Hello @iqmtgar,
Please send to tgloc96@gmail.com your source code or you could add this email to your private GitLab - Thanks

**Comment by minhcasi** [comment]
@iqmtgar - let us know your update - thank you!

**Comment by minhcasi** [comment]
@iqmtgar - would you mind to share the website login admin also resend your latest code update to inspireui.team@gmail.com 

Please note that there is a new release version `1.7.7` that includes some bug fix and performance improvement

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
