### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by maurovanschaik** [inspireui/support#4569]
Hi! We have another problem with some failures:

FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':app:processDebugResources'.
A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
Android resource linking failed
C:\Users\Usuario\Documents\FluxStore-listing 1.4.2-20200714T041041Z-001\FluxStore-listing 1.4.2\source\android\app\src\main\AndroidManifest.xml:12:5-72:19: AAPT: error: resource mipmap/launcher_icon (aka com.inspireui.fluxlisting:mipmap/launcher_icon) not found.

 C:\Users\Usuario\Documents\FluxStore-listing 1.4.2-20200714T041041Z-001\FluxStore-listing 1.4.2\source\android\app\src\main\AndroidManifest.xml:17:9-56:20: AAPT: error: resource style/LaunchTheme (aka com.inspireui.fluxlisting:style/LaunchTheme) not found.

 C:\Users\Usuario\Documents\FluxStore-listing 1.4.2-20200714T041041Z-001\FluxStore-listing 1.4.2\source\android\app\src\main\AndroidManifest.xml:57:9-59:49: AAPT: error: resource string/fb_app_id (aka com.inspireui.fluxlisting:string/fb_app_id) not found.

 C:\Users\Usuario\Documents\FluxStore-listing 1.4.2-20200714T041041Z-001\FluxStore-listing 1.4.2\source\android\app\src\main\AndroidManifest.xml:60:9-62:48: AAPT: error: resource string/app_name (aka com.inspireui.fluxlisting:string/app_name) not found.

 C:\Users\Usuario\Documents\FluxStore-listing 1.4.2-20200714T041041Z-001\FluxStore-listing 1.4.2\source\android\app\src\main\AndroidManifest.xml:63:9-65:55: AAPT: error: resource string/ak_client_token (aka com.inspireui.fluxlisting:string/ak_client_token) not found.

 C:\Users\Usuario\Documents\FluxStore-listing 1.4.2-20200714T041041Z-001\FluxStore-listing 1.4.2\source\android\app\src\main\AndroidManifest.xml:31:13-32:74: AAPT: error: resource string/api_key (aka com.inspireui.fluxlisting:string/api_key) not found.

 C:\Users\Usuario\Documents\FluxStore-listing 1.4.2-20200714T041041Z-001\FluxStore-listing 1.4.2\source\android\app\src\main\AndroidManifest.xml:69:9-71:48: AAPT: error: resource string/admob_api (aka com.inspireui.fluxlisting:string/admob_api) not found.
Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

Get more help at https://help.gradle.org

BUILD FAILED in 45s

Do you have a repair service? Could you make it works?

Best regards, Mauro
![ERROR APP 2](https://user-images.githubusercontent.com/67668916/89959413-ba385f00-dc12-11ea-9eac-29ff27237a4b.jpg)
![ERROR APP](https://user-images.githubusercontent.com/67668916/89959417-bc9ab900-dc12-11ea-9350-81ea79d916c1.jpg)

**Comment by minhcasi** [comment]
you could remove these setting from the AndroidManifest if does not use the key, example the key for google map api, account kit...

We will upgrade this config on next release to remove some un-use key 👍

**Comment by maurovanschaik** [comment]
Do you have a install service? We are having some troubles with that.

**Comment by maurovanschaik** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     C:\Users\Lito\Documents\FluxStore-listing 1.4.2\source\android\app\src\main\AndroidManifest.xml:12:5-58:19: AAPT: error: resource mipmap/launcher_icon (aka com.inspireui.fluxlisting:mipmap/launcher_icon) not found.

     C:\Users\Lito\Documents\FluxStore-listing 1.4.2\source\android\app\src\main\AndroidManifest.xml:17:9-56:20: AAPT: error: resource style/LaunchTheme (aka com.inspireui.fluxlisting:style/LaunchTheme) not found.

**Comment by minhcasi** [comment]
The latest version is ready for download, please give a try and let us know your checking. 

You could use this method to merge with your previous code via Gitlab - https://medium.com/@inspireui/how-to-upgrade-fluxstore-projects-by-using-git-cebde7489ea6

**Comment by minhcasi** [comment]
Let us know if you have any question - thank you!
