### ISSUE TITLE
[Listpro] Blank Page, No icons, No images

### ISSUE THREAD

**Issue by egebese** [inspireui/support#457]
My purchase code: f62282cf-fe1f-447d-9c9d-1df9eeae993c
Codecanyon

**I updated to 1.3.1 btw, still same problems.**

I have this problem, i followed all the steps on doc.

I can see my listings on app but I can't see listing images when i'm not logged in,
My htaccess is right, i did all JWT settings correct, i followed their and your documantation.
Plugin settings done by looking at documantation so there is no wrong setting.
I resized and regenerated all the images.
I can't see even the icons on nav bar or profile or menu. I can't see nothing!

And this is the red error screen shows up when i click on any listing.
`TypeError: undefined is not an object (evaluating 'postList.filter')

This error is located at:
in Index (created by Connect(Index))
in Connect(Index) (at PostDetailScreen.js:40)
in PostDetailScreen (at react-native-safe-area-view/index.js:365)
in RCTView (at View.js:44)
in AnimatedComponent (at react-native-safe-area-view/index.js:153)
in SafeView (at withOrientation.js:54)
in withOrientation (at react-native-safe-area-view/index.js:364)
in withSafeArea (created by Connect(withSafeArea))
in Connect(withSafeArea) (created by SceneView)
in SceneView (at createTabNavigator.js:39)
in RCTView (at View.js:44)
in RCTView (at View.js:44)
in ResourceSavingScene (at createBottomTabNavigator.js:113)
in RCTView (at View.js:44)
in ScreenContainer (at createBottomTabNavigator.js:103)
in RCTView (at View.js:44)
in TabNavigationView (at createTabNavigator.js:197)
in NavigationView (created by Navigator)
in Navigator (at createAppContainer.js:388)
in NavigationContainer (at RootRouter.js:70)
in RCTView (at View.js:44)
in AnimatedComponent (at react-native-drawer/index.js:632)
in RCTView (at View.js:44)
in Drawer (at MenuOverlay.js:39)
in MenuOverlay (created by Connect(MenuOverlay))
in Connect(MenuOverlay) (at RootRouter.js:83)
in RCTView (at View.js:44)
in RootRouter (created by Connect(RootRouter))
in Connect(RootRouter) (at App.js:217)
in Provider (at App.js:216)
in App (at react-native-safe-area-view/index.js:365)
in RCTView (at View.js:44)
in AnimatedComponent (at react-native-safe-area-view/index.js:153)
in SafeView (at withOrientation.js:54)
in withOrientation (at react-native-safe-area-view/index.js:364)
in withSafeArea (at withExpoRoot.js:22)
in RootErrorBoundary (at withExpoRoot.js:21)
in ExpoRootComponent (at renderApplication.js:34)
in RCTView (at View.js:44)
in RCTView (at View.js:44)
in RootSiblingsWrapper (at AppContainer.js:112)
in RCTView (at View.js:44)
in AppContainer (at renderApplication.js:33)

renderContent
AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fegebese%2FSource%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:258070:35
render
AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fegebese%2FSource%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:258149:30
finishClassComponent
AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fegebese%2FSource%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:17185:43
performUnitOfWork
AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fegebese%2FSource%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:19853:27
workLoop
AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fegebese%2FSource%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:19885:47
renderRoot
AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fegebese%2FSource%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:19948:21
performWorkOnRoot
AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fegebese%2FSource%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:20639:23
performWork
AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fegebese%2FSource%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:20563:30
performSyncWork
AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fegebese%2FSource%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:20538:20
batchedUpdates$1
AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fegebese%2FSource%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:20739:28
batchedUpdates
AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fegebese%2FSource%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:11813:37
_receiveRootNodeIDEvent
AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fegebese%2FSource%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:11870:23
receiveTouches
AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fegebese%2FSource%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:11900:34
__callFunction
AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fegebese%2FSource%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:3654:49

AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fegebese%2FSource%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:3427:31
__guard
AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fegebese%2FSource%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:3608:15
callFunctionReturnFlushedQueue
AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fegebese%2FSource%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:3426:21`

**Comment by egebese** [comment]
Ok, i got mail from support, one part of the problem is caused by the expo. Production mode solved it.

But still when i click on any listing, it gives error and red screen.

**Comment by egebese** [comment]
Hello?

**Comment by thangvo9x** [comment]
Please provide your AppConfig.json file.

**Comment by egebese** [comment]
{
  "Website": {
    "url": "https://rehbeer.co",
    "consumerKey": "ck_23d3372ffecbe925f07872c5261ddd78d1ea00d3",
    "consumerSecret": "cs_0b0ff89a8f8a231fe7351c1926fb8051095abf14"
  },
  "Theme": "restaurant",
  "MainColor": {
    "tabbarTint": "rgb(27, 229, 141)",
    "tabbarColor": "#D5D8DE",
    "mainColorTheme": "rgb(27, 229, 141)",
    "tabbar": "#FFF"
  }
}

do i have to install woocommerce? you didn't say it on anywhere.

**Comment by egebese** [comment]
and 2-3 times ago i installed the woocommerce, entered the consumer keys still same problems.

**Comment by thangvo9x** [comment]
Do you have change categoryListingId on Restaurant.js in Config folder.
You must have change it to your categoryListingId to display.
