### ISSUE TITLE
Product Guide / Suggestions, Not an issue

### ISSUE THREAD

**Issue by stickypages** [inspireui/support#4571]
I finally got approval on my app for Apple Store + Google Play, and thought I would give my 2 scents. 

Firstly, big thanks for the team in providing a great product. There still are lots of bugs and issues that need dealing with, but for a version 1 of my app I'm calling it a success. It wasn't an easy road. A lot of my comments are usually just rule of thumb IMO how to go about things. And might seem self-explanatory, but it helped me launch the app with WooCommerce. SIDENOTE (I did suggest/make changes to their GitLab) for some of the code.

_Precursor, this was my first time using flutter/dart and purchased through Envato._

**Considerations Before Starting**
- Expect things to not go smooth and everything to 'just work'
- Don't expect the 'builder' to do everything for you
- Make some time to learn and understand the code given to you

**What I adjusted/did**
- Setup the config to do as much as you can
- When there was an issue, don't post into the forum right away, search Inspire docs/Google/StackOverflow/Medium for some decent articles on Dart/Flutter
- If a feature wasn't working quite the way I expected it, I removed it from the display (ie: sign in through SMS), it wasn't mandatory for me, and I prefer sign up with email / social anyways
- When setting things up like Firebase, social logins and some of the main other features, ensure you stay consistent with your words and setup. Review the tutorials (all), for each situation, (ie: How to setup social login for Facebook on Android, also watch the iOS versions) as there is sometime slightly different things to see and understand with the signing. 
- Go through the process of 'signing your app' multiple times to ensure you understand the process, and keep the key nearby. You will need to sign it using the same key again if you need to create an 'update'.
- NEW features, download the most recent code, and find a product that you can 'COMPARE' files with. This will search your documents with the new downloaded files and compare the contents, and review each of the main files in 'lib', to ensure that the changes you are implementing will blend/merge with your code. Don't overwrite important files (keys, configs etc, build folders)

**Debugging**
- If you make a change to the code and it's still not showing in the emulator
-- 1, flutter clean
-- 1.1, flutter pub get
-- 1.2, still not working, build on a clean emulator or device
-- 2, flutter build

**Other debugging issues**
- On iOS, try to remove the packages, and re-installing them
- On iOS, make coding changes in VS Code... right-click the ios folder, and click "Open in Xcode", and go to Product->Archive->Distribute App after done archiving

**App Review**
- Android was the easy app to get online, no major issues here
- iOS, was a pain, ensure you have all the little details in place, from all the various screenshots, and ensure to use a specific ios device per screenshot iPhone / iPad (Download some templates from Envato to get you started)
- iOS, ensure that you have Apple Login setup, otherwise it will get rejected

For now, that's all I can think of. I thought it might be helpful to some others, Cheers, best of luck. If anything else comes up, I will try to edit this post.

**Comment by minhcasi** [comment]
@stickypages - thank you so much for sharing your experience and congratulation 🎉 - could i know your success app URL on Appstore / Google Play store - we will give some great feedbacks ⭐️
