### ISSUE TITLE
problems happened after update [fluxstore]

### ISSUE THREAD

**Issue by bananweb** [inspireui/support#4572]
- [ ] after we update source coude we got these problems
![image](https://user-images.githubusercontent.com/48653804/89994601-a6c7db00-dc88-11ea-97fe-f1e8ea63bb21.png)
![image](https://user-images.githubusercontent.com/48653804/89994641-b2b39d00-dc88-11ea-8db9-548a82c4d1b6.png)
![image](https://user-images.githubusercontent.com/48653804/89994665-bcd59b80-dc88-11ea-84ac-700f4a0905da.png)
can you help us please ?

**Comment by jakulz** [comment]
I had the same issue and found the solution on ticket #4539

**Comment by minhcasi** [comment]
@bananweb pls help to move your all comments  to this ticket #4577
