### ISSUE TITLE
firebase issues 

### ISSUE THREAD

**Issue by emad-masood** [inspireui/support#4573]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
- [x] first issue
- [x] second issue
- [x] third issue

+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

Hi  

thank you for a wondfull app you make is what i need and more

i have same issues 

1- firebase sms sign in and google for android not working
 ios is ok working fine

![Screenshot_1597225388](https://user-images.githubusercontent.com/68939548/90002533-6d4c9b00-dc9b-11ea-87c8-7c1f9de7770e.png)

![Screenshot_1597225348](https://user-images.githubusercontent.com/68939548/90002711-b3096380-dc9b-11ea-9a1c-c82224988004.png)

2- push Notifications firebase not workin both ios and android 
there is no errors messages or something show up so i don't why or what i have to do
<img width="968" alt="Screen Shot 2020-08-12 at 1 01 57 PM" src="https://user-images.githubusercontent.com/68939548/90002937-0a0f3880-dc9c-11ea-9b30-27767dcbf0f7.png">

3- this is not a problems but i hope you can do something about if passable
Google font not every where i search using inspector but no luck 
![Screenshot_1597225731](https://user-images.githubusercontent.com/68939548/90003507-d97bce80-dc9c-11ea-900b-1547bcc319a6.png)

4- page checkout

` /// Enable Payment option
  "EnableOnePageCheckout": true,
  "NativeOnePageCheckout": true,

  //This config is same with checkout page slug in the website
  "CheckoutPageSlug": "checkout",`

this solution  is perfect but well be nice if i can add checkout page for each language or make that happen with mstore api 
 
and also with smart chat

`const smartChat = [
  {'app': 'https://wa.me/12345678', 'iconData': FontAwesomeIcons.whatsapp},
  {'app': 'tel:12345678', 'iconData': FontAwesomeIcons.phone},
  {'app': 'sms://+12345678', 'iconData': FontAwesomeIcons.sms},
  {
    'app': 'https://tawk.to/chat/abcda123abca234abs/default',
    'iconData': FontAwesomeIcons.facebookMessenger
  }
];`

i have two widgets on arabic and one english
if i can put widgets for each language will be nice

i use FluxStore  pro 1.7.6

Thank you

**Comment by minhcasi** [comment]
@emad-masood - please help to check detail solution for the login issue on this ticket https://github.com/inspireui/support/issues/3151

**Comment by ameenbadri7** [comment]
Hi, @emad-masood 
We haven’t heard back from you in a while, so I’m going to mark this ticket as resolved – if you have any further questions, you can start a new ticket.

Thank you very much ❤️
