### ISSUE TITLE
notification issue [fluxstore]

### ISSUE THREAD

**Issue by bananweb** [inspireui/support#4577]
we don't receive notification when app is opened.. when it closed, notification recieved but not shown in notification page..
how can we fix this ?

**Comment by minhcasi** [comment]
@bananweb - could you help to check this guide https://medium.com/@inspireui/setup-firebase-cloud-messaging-fcm-push-notification-for-flutter-apps-8c767fe64e54 - also try to test the notification on the real device, on simulator could fail some cases.

**Comment by bananweb** [comment]
we already followed these steps, notifications already is working when app is closed or running in the  background.. but when it is running, notification is not recieved.
second issue is it is not listed in notification list page.
we already test on real device

**Comment by bananweb** [comment]
Awaiting for your responce

**Comment by bananweb** [comment]
Awaiting for your response,
Also, i need to update source code with gitlab, i sent request to form with my email, but there is no response.
Last thing, we followed this doc to change font https://docs.inspireui.com/fluxstore/multi-language/
but there is an issue with font, we changed it but it didn't apply to all application, there is some contents don't apply the font we specified

**Comment by bananweb** [comment]
@minhcasi

**Comment by Alnaggar94** [comment]
@minhcasi - same issue in latest version from Gitlab

**Comment by minhcasi** [comment]
@bananweb - @Alnaggar94 - we will investigate this issue and get back later - thanks

**Comment by minhtruong315** [comment]
@bananweb can u give me your skype? I will help you check remotely
Thanks

**Comment by bananweb** [comment]
@minhtruong315 
https://join.skype.com/gFVom4t8tEQj

**Comment by minhtruong315** [comment]
@bananweb You're using old Fluxstore version. Please download version 1.7.7 to fix this issue

**Comment by minhtruong315** [comment]
@bananweb replace this function in models/notification.dart and try again
```
FStoreNotification.fromJsonFirebase(Map<String, dynamic> json) {
    try {
      final data = json['data'];
      final notification =
          data != null && data.keys.isNotEmpty && data["title"] != null
              ? data
              : json['notification'];
      body = notification['body'];
      title = notification['title'];
      seen = false;
      date = DateTime.now().toString();
    } catch (e) {
      printLog(e.toString());
    }
  }
```
