### ISSUE TITLE
[ListPro] compiled but cant get app to run

### ISSUE THREAD

**Issue by Pythaclassic** [inspireui/support#458]
**Mandatory Info (please complete the following information):**
 - Product: [ListPro]
 - Your Purchased Code: [619c1ff4-77f0-4da6-ac2c-78d35f4ec5b2]
(we may not reply if you are not our customer)

**Describe the issues**
So these were the steps I took and still I cannot get the application working with my site

1. Installed woocommerce plugin on my listing pro default classic theme site 
2. Generated the customer key and customer secret from the plugin
3. Use cebuilder to select the app directory (selected the source directory in the listpro 1.3 root directory downloaded from codecayon) 
4. In the Cebuilder I Setup my app name, website (http://test.everythinglib.com) , the customer key and secret (as I got from my wp site) and saved. 
5. I then went to the customization tab and selected Default Classic and setup the other requirement 
6. When I was done with that, I clicked the “Run Setup” in cebuilder 
7. After setup ran successfully 
8. I ran the command “expo start” 
9. I then went to cebuilder and click the “build” android under delivery. 
10. Building was successful, however the app wont be accessible via envo even if I scan the qr code or try accessing it via the envo android app. 
11. I downloaded the app and installed it but its stuck in the welcome screen with listpro splashscreen and then I just receive the bluescreen expo error message “something went wrong”

I have tried repeatedly but still lands at the same error. Is there something I am doing wrong? Please help me out

**Screenshots**
![image](https://user-images.githubusercontent.com/49073021/55247020-75d73980-523e-11e9-9bd2-8ea75833bc6f.png)

**Additional context**
Add any other detail logs about the problem here.

**Comment by Pythaclassic** [comment]
hi, any update on this issue?

**Comment by minhcasi** [comment]
@Pythaclassic - could you click the error log detail form the screen and send us the detail logs.

Also, try to double check the require Wordpress plugins setting - https://inspireui.github.io/listapp/docs/setup

And make your your mobile simulator can reach to your website setting

Let us know your checking - thank you!
