### ISSUE TITLE
Maps not loading

### ISSUE THREAD

**Issue by Bozso21** [inspireui/support#4580]
Hi

I configured the google maps api based on the tutorial you provided us, but I still see this
![Screen Shot 2020-08-12 at 19 31 37](https://user-images.githubusercontent.com/68916073/90047849-e3202900-dcd2-11ea-8572-a69007670a5f.png)

Do you have any idea what might be the problem?

**Comment by minhcasi** [comment]
@Bozso21 - please help us to move this comment to this opening ticket support - #4455
