### ISSUE TITLE
QUESTION: Support for Woo-Commerce Product Add-on plugin

### ISSUE THREAD

**Issue by enriqueleon80** [inspireui/support#4581]
Hi All,

This is more of a question than anything else.

I'm using Dokan on Multi-Vendor 1.7.3, which has a module titled Product Addon's which builds on the Woocommerce standard plug-in for Product Addon's.  It lets you add checkboxes and other such Addon's for products.  My question is, does FLUXSTORE support this WooCommerce plugin? From what I can see, it does not.  Only regular variants are supported.

Just needed to get this in writing.  If it's not supported, any plan to include it in later releases? One can only create so much complexity with standard WooCommerce variants and they are a total pain to maintain.

THANKS

https://wedevs.com/docs/dokan/modules/product-addon/
https://docs.woocommerce.com/document/product-add-ons/

EnriqueLeon80@gmail.com

**Comment by and-eee** [comment]
I totally agree with @enriqueleon80 , this is a function that would improve FluxStore's functionality and speed enormously. Will be very interested in the answer and I hope it's put into release planning.

**Comment by minhcasi** [comment]
@enriqueleon80 - the Product Add-Ons is over favorites integration and our team is investigating to the solution, hope it will be ready soon - thank you!

**Comment by enriqueleon80** [comment]
Sorry @minhcasi not sure I understood? What is favorites integration?

**Comment by minhcasi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Integrate with Product Add-On](https://trello.com/c/0mLknuzx/66-integrate-with-product-add-on)

**Comment by minhcasi** [comment]
@enriqueleon80 - it mean we are interested in this feature and will focus on the update - we will update via Trello board Feature Request - thank you!
