### ISSUE TITLE
Building APK Error

### ISSUE THREAD

**Issue by joemark0008** [inspireui/support#4582]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues:  

Building APK Error

+ Product & version: Fluxstore Vebdor 1.7.6
+ Flutter (or React Native) version:  1.20.1
+ Testing Device/Simulator: Android Real Device
+ Screenshot issues (drag the file to attach here): 

Codepoint 58848 not found in font, aborting.

FAILURE: Build failed with an exception.

Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 896

What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.

Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

Get more help at https://help.gradle.org

BUILD FAILED in 1m 23s
Running Gradle task 'assembleRelease'...
Running Gradle task 'assembleRelease'... Done 83.9s
Gradle task assembleRelease failed with exit code 1

![image](https://user-images.githubusercontent.com/41988621/90073808-79346d80-dd2c-11ea-91fb-aebac0fba082.png)

**Comment by ameenbadri7** [comment]
try your best to clear the [build cache ](https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1) and please double-check this installation [guide ](https://docs.inspireui.com/fluxstore/getting-started/) to fix your issue.

Thank you.

**Comment by joemark0008** [comment]
I already tried all possible way..

all my concerns fixed in 1.7.7 version

Thanks

**Comment by ameenbadri7** [comment]
Happy that your problem solved.
You could help us by giving your feedback/rating to [Codecanyon Market website](https://codecanyon.net/downloads), 
we are working hard to update more awesome and powerful features on the next coming version release. 
Let us know if you have any feedback. 

Thank you very much ❤️

**Comment by joemark0008** [comment]
sure
