### ISSUE TITLE
The purchase code is incorrect.

### ISSUE THREAD

**Issue by ornekali** [inspireui/support#4592]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
Hi, I'm having trouble with the confirmation code, I'd like you to help.

![11](https://user-images.githubusercontent.com/69655669/90198030-249afc00-ddd9-11ea-9c61-cd0a5e1d00df.png)
![1](https://user-images.githubusercontent.com/69655669/90198032-25cc2900-ddd9-11ea-86e5-5bd8d8ed519e.jpg)

- [ ] first issue
- [ ] second issue
- [ ] third issue

+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 

Thank you for your time!

**Comment by ornekali** [comment]
http://verify.inspireui.com/ -the purchase file has been shared through this site, I would like to ask you to help.

**Comment by ornekali** [comment]
> Geri bildirim için teşekkür ederiz.
> 
> Lütfen bu formu göndermemize ve desteğe devam etmek için gerekli tüm bilgileri doldurmamıza yardımcı olun - http://verify.inspireui.com/ - lütfen satın alma kodunu veya ekran görüntüsünü burada paylaşmayın, çünkü başka bir kullanıcı aktivasyon için kullanacaktır.
> 
> Bu bileti 24 saat içinde kapatacağız, eğer yeterli ayrıntı sağlanmazsa, formu gönderdikten sonra lütfen bileti tekrar açın.
> 
> Zaman ayırdığınız için teşekkür ederiz!
> 
> > **[Google Forms-ücretsiz anketler oluşturun ve analiz edin.](http://verify.inspireui.com/)**Kendi başınıza veya başkalarıyla aynı anda yeni bir anket oluşturun. Çeşitli anket türleri arasından seçim yapın ve sonuçları Google Forms'ta analiz edin. Google'dan ücretsiz.

http://verify.inspireui.com / - satın alma dosyası bu site üzerinden paylaşıldı, sizden yardım istemek istiyorum.

**Comment by minhcasi** [comment]
verified ✅

@ornekali - could you help to update latest mstore-api and fluxbuilder `1.0.7` to fix this issue - thank you!

**Comment by minhcasi** [comment]
Let us know if you have any question - thank you!
