### ISSUE TITLE
Sale price is null on Mac android Studio

### ISSUE THREAD

**Issue by devienguilde** [inspireui/support#4594]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
- the problem of the product didn't come out is only on mac, i try on windows it's work properly
- i try with visual studio it's not work too

+ Product & version: 1.7.7
+ Flutter (or React Native) version:  lastest
+ Testing Device/Simulator: Nexus 6 Api
+ Screenshot issues (drag the file to attach here): 
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/50396726/90208575-57fa7c80-de13-11ea-8729-e8b2dd405419.png">

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by tgloc96** [comment]
Hello @devienguilde,
Sorry for the delay in response, could you please send me your source code or add me to your git project via tgloc96@gmail.com.

**Comment by tgloc96** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
