### ISSUE TITLE
Payment method with web view & No result for Searching Arabic names products  

### ISSUE THREAD

**Issue by midotaha** [inspireui/support#4595]
**Greetings!!**
i have 2 issues at WooCommerce 1.7.6 & 1.7.7 , the 2nd issue is extremely important please help me to fix it immediately , 3 products was purchased from you and i faces the same problems {Fluxstore Multi Vendor , Fluxstore Pro , finally Fluxstore WooCommerce}
- [ ] **First issue >>> i have issue with searching , if i made any searching with Arabic for any product name , i got zero result, or long time loading without any result** ,  **[i tried to used this solution but not working with me](https://github.com/inspireui/support/issues/4225#issuecomment-659253644)** 
![Screen Shot 2020-08-14 at 09 54 02](https://user-images.githubusercontent.com/19406537/90223062-03a4cc00-de16-11ea-9dec-9efad4c54d71.png)
**ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ**

- [ ] **Second issue >>> Another payment method (with web view ) Not working at all , i add all configuration right step by step to TapConfig section , another long time loading for payment method , without showing the area or page to input information to confirm checkout, it's working perfect at website There are no errors in it, i tried default source code without any editing but not working , also tried to [imitation this video](https://www.youtube.com/watch?time_continue=163&v=MrDq3CqRphY&feature=emb_logo) but i'm changed the name or id for payment and add my SecretKey or Publishable API Key , unfortunately not working , [i followed all steps Hundreds of times at this link but not helpful for me ](https://docs.inspireui.com/fluxstore/multi-payment/)** 
![Screen Shot 2020-08-14 at 09 54 53](https://user-images.githubusercontent.com/19406537/90223080-0ef7f780-de16-11ea-8cef-eb3d0ad134f0.png)
**ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ**
- **Product & version: woocommerce 1.7.6 & (1.7.7 last update 13/08/2020)**
- **Flutter version:** 1.17.5 & and make upgrade to flutter 1.20.1 but didn't help
![Screen Shot 2020-08-03 at 15 48 50](https://user-images.githubusercontent.com/19406537/89184105-f29bc580-d5a0-11ea-9a69-f1eef3489b05.png) 
- **Devices :- physical iPhone Xs Max & Simulator:- iPhone 11 Pro Max & Emulator:- Nexus 6 API 30**
I hope to help me very fast to fixe all of them ,because i spent lot of time to fixe it and i lose many of customers for this reason (payment method not working )

**Comment by minhcasi** [comment]
@minhtruong315 - please help to investigate this ticket as high priority - thank you!

**Comment by minhtruong315** [comment]
Hi @midotaha can u send me common folder and admin account to login your website via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/4595

**Comment by midotaha** [comment]
Hi Dear sir 
message was sent to your mail , please check it , Many thanks for you

**Comment by midotaha** [comment]
Hi Dear @minhtruong315 , is there any news about my payment issue ?!  still waiting

**Comment by minhtruong315** [comment]
Hi @midotaha I'm checking it now. and let you know the result soon

**Comment by minhtruong315** [comment]
Hi @midotaha ,
I'm checking your website in my source code. it's not showing loading in search screen.
What is Fluxstore version you're using?

**Comment by midotaha** [comment]
Greetings!! 
i use WooCommerce 1.7.6 & also i tried 1.7.7 
and the second  Payment Gateway that i use it ?! not working , i reactivated it to you now

**Comment by minhtruong315** [comment]
@midotaha but you sent me the source code version 1.7.6. I only can check the issue on the latest version. please check your issue in the latest version and send me the latest source code if you have any issues.

**Comment by midotaha** [comment]
@minhtruong315  the same problem in the new version sir..... the second payment method not working  and the same thing search have issue , not working
for note Dear .. i told you before the important issue i must to fix it Second payment method , the solution will found on version 1.7.6 or 1.7.7 there is no problem , it must be fixed sir ,,, because i have a big problems with my customers 
i'm waiting your answer Dear sir
many thanks for you

**Comment by minhtruong315** [comment]
@midotaha for search issue, you can try to replace loadProduct function in models/search.dart like this
```
Future<void> loadProduct({String name, bool hasFilter = false}) async {
    if (name != _currentName || hasFilter) {
      _currentName = name;
      _page = 1;
      products = null;
      _isEnd = false;
    } else {
      _page++;
    }

    if (!hasFilter) {
      if (_isEnd) return;

      if (isLoading) return;
    }

    isLoading = true;
    notifyListeners();

    var newProducts = await _searchProducts(
      name: name,
      page: _page,
    );

    if (newProducts == null) {
      products = <Product>[];
      isLoading = false;
      _isEnd = true;
      notifyListeners();
      return;
    }

    if (newProducts.isEmpty) {
      products = <Product>[];
      _isEnd = true;
      isLoading = false;
      notifyListeners();
      return;
    }

    if (products == null) products = <Product>[];

    products.addAll(newProducts);

    isLoading = false;
    notifyListeners();
  }
```

**Comment by minhtruong315** [comment]
@midotaha for second payment gateway, it's using Webview. Fluxstore only supports some native payment gateway: paypal, razorpay, tap. others are using webview for checkout

**Comment by midotaha** [comment]
@minhtruong315  that payment i need it to run on my app it's used [Webview and this document for it Sir,  if you like to get a look on it ](https://moyasar.com/docs/payments/mobile-apps-integration/) maybe help us to solve this issue

**Comment by minhtruong315** [comment]
@midotaha We doesn't support customize code for Fluxstore. if you want to extra request, you can email to support@inspireui.com

**Comment by midotaha** [comment]
@minhtruong315 why you  closing my Ticket ................. for the code tat you send it to fix search issue does not work ....i think you should to close it until you give me the right solution ..........
what are you did it put any code then close ticket and run .....This is not a good way to deal with clients

**Comment by minhcasi** [comment]
@midotaha - I'm sorry for the issue, let me discuss with the team and provide the solution to fix this issue - thank you!

**Comment by minhtruong315** [comment]
@midotaha please check the video https://drive.google.com/file/d/1J6w4bJa_rxCuc7WNzOMyAAA4w4S4sOfK/view?usp=sharing
I checked your website on the solution that i sent you. it's working well

**Comment by minhtruong315** [comment]
rcan u record me the issue?

**Comment by minhtruong315** [comment]
@midotaha pls record screen

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!

**Comment by midotaha** [comment]
Hi @minhtruong315  , Greetings ! 
Just i want you to open [My previous ticket](https://github.com/inspireui/support/issues/3966) and fix your Opencart codes, which that created about two months ago , i think that is very important and required , What I need it's very short :ـ 
Correctly add and calculate price for products which have many variables Without the appearance of the bill negative, there was one of your team members accessed my Pc and see what's happened and What i'm talking about , he told me "there is a lot of codes must be change , wait for up date" ..... i think it's very long time to wait 2 month for update to solve this problem , also Woo-commerce is very very slow with me to work on it , Opencart is comfortable to my at work and fast, if any one from your team need to access again to my pc to watch or remember this big problem I am ready and prepared
i'm waiting you replay Sir
Thanks for you
