### ISSUE TITLE
Error in Fluxstore Woocomerce 1.7.7

### ISSUE THREAD

**Issue by jakulz** [inspireui/support#4596]
* What went wrong:
Execution failed for task ':app:mergeDebugAssets'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not download audience-network-sdk.aar (com.facebook.android:audience-network-sdk:5.10.0)
      > Could not get resource 'https://jcenter.bintray.com/com/facebook/android/audience-network-sdk/5.10.0/audience-network-sdk-5.10.0.aar'.
         > Could not GET 'https://d29vzk4ow07wi7.cloudfront.net/11b0af8ee5d8f70affed92d245eda9ea5a776cf8c75f738b79f9850d4540bbd1?response-content-disposition=attachment%3Bfilename%3D%22audience-network-sdk-5.10.0.aar%22&Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHAqOi8vZDI5dnprNG93MDd3aTcuY2xvdWRmcm9udC5uZXQvMTFiMGFmOGVlNWQ4ZjcwYWZmZWQ5MmQyNDVlZGE5ZWE1YTc3NmNmOGM3NWY3MzhiNzlmOTg1MGQ0NTQwYmJkMT9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPWF0dGFjaG1lbnQlM0JmaWxlbmFtZSUzRCUyMmF1ZGllbmNlLW5ldHdvcmstc2RrLTUuMTAuMC5hYXIlMjIiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE1OTczNTc2Njh9LCJJcEFkZHJlc3MiOnsiQVdTOlNvdXJjZUlwIjoiMC4wLjAuMC8wIn19fV19&Signature=cf9lavC1HpoLf2RkmvyVn0ogC0Y0ZMna6HLX-qdxZgxgBhcTx4emPJlFKE017bZxiMgZMQpPqC5qCsQrsSF1~ncsLLbqcB6BWsSX-RndrxkgC4oLvxVixd~7p0ZHePguwEJby2OY45TmUL2zXpu0hSXaTPmd2JfFdD39i3CPxwrg2n9yLQ2xEs7zYOCu034We92OS6Y8DoahHNUap818iYoAg6TfVWUo7iZa4VPgWANi4wDcMkvB8qqq1DULyiVVRaHVofh1Ce5hSKklze8ZBglP0Dp06AaOzRUJiShloSepo7TtaPtFRSO030nEtH1CA0FcjpzcvFtmpMKKZnNDFA__&Key-Pair-Id=APKAIFKFWOMXM2UMTSFA'.
            > Received close_notify during handshake

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by minhcasi** [comment]
@jakulz - could you help to share the detail screenshot issue, also help to send us the result from `flutter doctor` to check your flutter environment, we suspect there are some issues with your setup. 

Thank you!

**Comment by jakulz** [comment]
![doctor](https://user-images.githubusercontent.com/35921309/90244037-d8ee4f80-dde4-11ea-8fc5-8a82471f8d89.png)
![err](https://user-images.githubusercontent.com/35921309/90244045-dbe94000-dde4-11ea-8937-ccd86b74dfc1.png)

**Comment by minhcasi** [comment]
@jakulz - this could be the issues with your network that it could not download from the cloudfront to update the library require from the app, please try to check with other network connection or remove firewall from your current network/company network gateway - thank you!

**Comment by minhcasi** [comment]
Let us know if you have any question - thank you!
