### ISSUE TITLE
product_grouped.dart - No context passed to cartModel.addProductToCart() call

### ISSUE THREAD

**Issue by jibrail-idris** [inspireui/support#4597]
The context object is not passed in the function call cartModel.addProductToCart(), causing an assertion error. In contrast, product_variant_mixin.dart handles the adding of a single simple product with context. (Refer to screenshots)
```
════════ Exception caught by gesture ═══════════════════════════════════════════════════════════════
The following assertion was thrown while handling a gesture:
'package:flutter/src/widgets/localizations.dart': Failed assertion: line 453 pos 12: 'context != null': is not true.

When the exception was thrown, this was the stack: 
#2      Localizations.of (package:flutter/src/widgets/localizations.dart:453:12)
#3      S.of (package:fstore/generated/l10n.dart:33:26)
#4      CartModelWoo.addProductToCart (package:fstore/models/cart/cart_model_woo.dart:178:21)
#5      _GroupedProductState.addToCart (package:fstore/screens/detail/product_grouped.dart:32:32)
#6      _GroupedProductState.addToCartWidget.<anonymous closure> (package:fstore/screens/detail/product_grouped.dart:102:37)
```

![image](https://user-images.githubusercontent.com/3234559/90232320-14bdff00-de4f-11ea-8db9-5ec686bd5299.png)
![image](https://user-images.githubusercontent.com/3234559/90232830-cbba7a80-de4f-11ea-9e25-bfee76467f37.png)

**Comment by minhcasi** [comment]
@jibrail-idris - could i know if you have clean up the cache by using this guide - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

Does it happen when you click add-to-cart button?

**Comment by jibrail-idris** [comment]
> @jibrail-idris - could i know if you have clean up the cache by using this guide - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1
> 
> Does it happen when you click add-to-cart button?
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/0aeb324a3445c618a67c0140da8216d28af304fa/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f696d616765732f6d6f64756c65732f67697374732f676973742d6f672d696d6167652e706e67"><img alt="" height="14" src="https://camo.githubusercontent.com/040b5519c6d1891329f5f6d3e511003657131cf2/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> Gist**[These are common issues on Flutter and solutions to fix](https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1)**These are common issues on Flutter and solutions to fix - Flutter Clean.md

Yes, it happens when I clicked on add-to-cart button for grouped products. As you can see from the screenshot, the context object was not passed in addToCart() as argument. Hence, the error.

**Comment by minhcasi** [comment]
@jibrail-idris - please help to try download the latest package `1.7.7` or from our latest source on Gitlab to see if it is the same. 

We have double-checked the bundle product on the demo but could not reproduce the issue - thanks

**Comment by jibrail-idris** [comment]
> @jibrail-idris - please help to try download the latest package `1.7.7` or from our latest source on Gitlab to see if it is the same.
> 
> We have double-checked the bundle product on the demo but could not reproduce the issue - thanks

How do I get access to your Gitlab repo>?

**Comment by minhcasi** [comment]
@jibrail-idris - our team will send the invitation soon

You could download from this link as well https://codecayon.net/downloads

Let us know if you have any question - thank you!
