### ISSUE TITLE
Andoid Build Error, Vector Math

### ISSUE THREAD

**Issue by RomeoDar** [inspireui/support#4598]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
- while compiling (going for build apk and debugging) it's giving vector math errors, i updated flutter recently and now not able to debug or make build. i bought 3 of your other products too, try to run fluxstore news and it's giving same error. so kindly solve this issue

(IT WAS WORKING FINE, THIS ERROR CAME RECENTLY)

**my pubspec.yaml**

name: fstore
description: Hamza Dar Flutter App
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  logs:
    git: https://github.com/pq/logs
  flutter:
    sdk: flutter
  http: 0.12.0+4
  html_unescape: 1.0.1+3
  provider: 4.0.4
  after_layout: 1.0.7+2
  font_awesome_flutter: 8.8.1
  path: 1.6.4
  vector_math: ^2.1.0-nullsafety.2
  carousel_pro: 1.0.0
  flutter_widget_from_html: 0.3.2+2
  configurable_expansion_tile: 1.0.0
  timeago: 2.0.26
  share: 0.6.3+6
  validate: 1.7.0
  country_pickers: 1.2.0
  shared_preferences: 0.5.6+3
  firebase_messaging: 6.0.12
  firebase_analytics: 5.0.11
  transparent_image: 1.0.0
  pull_to_refresh: 1.5.8
  localstorage: 3.0.1+4
  notification_permissions: 0.4.4
  flare_splash_screen: 3.0.1
  rate_my_app: 0.6.0+2
  page_indicator: 0.3.0
  extended_image: 0.9.0
  intro_slider: 2.2.9
  url_launcher: 5.4.2
  firebase_core: 0.4.4 # keep these version as there is new issue
  firebase_auth: 0.15.3 # with the latest firebase https://github.com/FirebaseExtended/flutterfire/issues/2084
  flutter_webview_plugin: 0.3.10+1
  connectivity: 0.4.8+2
  random_string: 2.0.1
  google_maps_flutter: 0.5.25+3
  place_picker: 0.9.11
  cached_network_image: 2.0.0
  image_picker: 0.6.4
  uuid: 2.0.4
  uni_links: 0.2.0
  flutter_staggered_grid_view: 0.3.0
  device_apps: 1.0.9
  auto_size_text: 2.1.0
  flutter_swiper: 1.1.6
  flutter_widgets: 0.1.12
  video_player: 0.10.8+1
  flutter_spinkit: 4.1.2+1
  percent_indicator: 2.1.1+1
  animated_text_kit: 2.0.0
  wave: 0.0.8
  http_auth: 0.2.9
  firebase_admob: 0.9.1
  facebook_audience_network: 0.5.0
  pin_code_fields: 2.4.0
  flutter_facebook_login: 3.0.0
  webview_flutter: 0.3.19+9
  rubber: 0.4.0
  flutter_localizations:
    sdk: flutter
  custom_splash: 0.0.2
  apple_sign_in: 0.1.0
  google_sign_in: 4.4.0
  google_fonts: 0.3.10
  flutter_statusbarcolor: 0.2.3
  app_settings: 3.0.1
  animated_splash: 1.0.0
  firebase_database: 3.1.3
  event_bus: 1.1.1
  country_code_picker: 1.3.7
  flutter_typeahead: 1.8.0
  flash: 1.2.3

dev_dependencies:
  flutter_launcher_icons: 0.7.4
  flutter_test:
    sdk: flutter
  pedantic: 1.8.0+1 # Analysis

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - lib/config/
    - lib/config/mocks/
    - lib/config/states/
    - assets/icons/categories/
    - assets/icons/tabs/
    - assets/icons/profile/
    - assets/icons/payment/
    - assets/images/
    - assets/images/country/
    - assets/images/favicon/
    - assets/html/
    - assets/images/background/
  fonts:
    - family: MaterialIcons
      fonts:
        - asset: assets/fonts/MaterialIcons.ttf
    - family: Entypo
      fonts:
        - asset: assets/fonts/Entypo.ttf
    - family: FontAwesome
      fonts:
        - asset: assets/fonts/FontAwesome.ttf
    - family: MaterialCommunityIcons
      fonts:
        - asset: assets/fonts/MaterialCommunityIcons.ttf
    - family: Feather
      fonts:
        - asset: assets/fonts/Feather.ttf

flutter_intl:
  enabled: true

+ Product & version: Fluxstore pro
+ Flutter (or React Native) version: flutter
+ Testing Device/Simulator: real device
+ Screenshot issues (drag the file to attach here): 

(Purchase code done)

![Capture](https://user-images.githubusercontent.com/52714884/90232638-67d78800-de36-11ea-9439-8c57024d04da.PNG)

Doctor Flutter

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, 1.21.0-9.0.pre, on Microsoft Windows [Version 10.0.18363.959], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 3.5)

[√] VS Code (version 1.43.2)
[√] Connected device (3 available)

**Comment by RomeoDar** [comment]
@minhcasi its not shopify, its fluxstore pro and also i'm having same error on fluxstore news project

**Comment by RomeoDar** [comment]
Because every version of flutter_test from sdk depends on vector_math 2.0.8 and fstore depends on vector_math ^2.1.0-nullsafety.2, flutter_test from sdk is forbidden.
So, because fstore depends on flutter_test any from sdk, version solving failed. this error

encounter these errors recently, recently i upgraded flutter

**Comment by minhcasi** [comment]
@RomeoDar - pls give a try to download latest version `1.7.7` to fix the build issue 

Also, make sure to clean the flutter cache - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

**Comment by minhcasi** [comment]
Let us know your checking - thanks

**Comment by prophpgeek** [comment]
@minhcasi I am also getting this error and cannot move past this. If I download the latest version how do I merge my changes with the new code base?
