### ISSUE TITLE
Not able to use existing user credentials to login, signup and checkout is gated

### ISSUE THREAD

**Issue by krdvijay** [inspireui/support#4599]
App: Fluxstore-woo 1.7.6

Precondition: Existing Woocommerce Integration

Android App

Issue 1:
On adding product to cart and moving to checkout
user credentials not working of existing users
Error: FormatException: Unexpected character (at character 1)

Tried all methods like https://, but not working

Issue 2:
Not able to use firebase app authentication methods to login. I have created app and followed instructions of blog.

Issue3:
Reset pwd when accessed through native screen by not providing url in config.dart(as per documentation). Its giving error that URI missing.

Please do mention clear instructions for android app creation and integration so that the process should be smooth.

**Comment by minhcasi** [comment]
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by krdvijay** [comment]
Above issue is resolved with some changes.

Can you suggest 
me on weight based flexible shipping is giving 0 shipping charge. Though flexible shipping plugin is perfectly working on web. 

1. Does fluxstore woocom supports weight based flexible shipping? If yes then what configurations need to be done?
2. How can I achieve native razorpay and paytm integrations or else if webview of payment screen then how to directly move to razorpay and paytm webview screens from applications native screen.

**Comment by minhcasi** [comment]
@krdvijay 
I'm sorry to close this ticket as it is not provided enough proof of purchase, please help to create a new one with full information on step2 - thank you for your time!
