### ISSUE TITLE
[MStore Multi Vendor] React native template without expo 

### ISSUE THREAD

**Issue by titoapp** [inspireui/support#460]
- Product: MStore Multi Vendor - Complete React Native template for WooCommerce
 - Your Purchased Code: c187dd82-7ecc-443a-af91-34195c65a457

**Describe the issues**
I've purchased MStore Multi Vendor - Complete React Native template
and i need to get the react native without expo,
Please detach expo and send me react native version of the app, 
Make sure that is working effectively

Email: 
ahmeddinasaad@gmail.com

Please dont be late as u mentioned to be on This Monday

<img width="468" alt="Screen Shot 2019-03-30 at 12 27 58 PM" src="https://user-images.githubusercontent.com/25744521/55274981-8db6c800-52e7-11e9-853f-8b98aa42d7a8.png">

and send you a message at https://codecanyon.net/item/mstore-multi-vendor-complete-react-native-template-for-ecommerce/22278924/comments

Message details
Hi, i purchased the MStore Multi Vendor, May you send me the react native version with one signal, by detaching the expo from it and send it directly to my purchased email as soon as possible. When will u be able to send it to me as we cant detach the expo properly.

InspireUI
InspireUI AUTHOR

about 19 hours ago Flag
okay, please share your email here, we will send as private package, we may send on Monday as the team is out of the office now, you can create the request ticket to Github – https://github.com/inspireui/support/issues – for follow up the update – thanks

**Comment by minhcasi** [comment]
@titoapp could you share your email here, we will send via the private email - thanks

**Comment by MrFaisal100** [comment]
can you send it to me too, how can I share my email with you

**Comment by minhcasi** [comment]
@thangvo9x please forward the detach version to ahmeddinasaad@gmail.com - thank you!

**Comment by thangvo9x** [comment]
Sent , Please check
