### ISSUE TITLE
Fluxstore ecommerce 2 issues range and search error

### ISSUE THREAD

**Issue by nomicool** [inspireui/support#4601]
1 while searching products it remains stuck on the loading screenshot attached.
2 selecting range cases following error please check the screenshot
![isssue 1](https://user-images.githubusercontent.com/25566185/90281708-79488080-de86-11ea-9ed2-aef44e8d2fae.png)
![issue 2](https://user-images.githubusercontent.com/25566185/90281711-7b124400-de86-11ea-8a26-86b44fc087a7.png)

**Comment by minhcasi** [comment]
@nomicool - could i know which version you are testing? Please try the latest stable `1.7.7` - thank you!

**Comment by nomicool** [comment]
on your 1.7.7 version when we run command for package get pub its shows some sdk issues that's why I am using the 1.7.6

**Comment by nomicool** [comment]
![Screenshot (199)](https://user-images.githubusercontent.com/25566185/90311515-020dfd80-df15-11ea-82f4-daebc47abb1c.png)

**Comment by nomicool** [comment]
look it failed to load packages and playstore also not accepting apps less than 28 sdk

**Comment by minhcasi** [comment]
- Try to use latest `1.7.7` as we have fix the build issue related to flutter_svg 

- There is no problem with the build APK as we also updated on our demo, try to keep the default grade build file, not change or upgrade the default one

**Comment by minhcasi** [comment]
Also, give a try to change both compileSdkVersion and targetSdkVersion to 29 if it fix your issue:

<img width="974" alt="Screen Shot 2020-08-16 at 08 38 32" src="https://user-images.githubusercontent.com/1459805/90324678-df72f780-df9b-11ea-846e-5f7a532f0342.png">

**Comment by nomicool** [comment]
I have updated flutter but apk run takes too long flutter build takes too long even don't build so I tried vs code run was working but building apk takes too long even don't build

**Comment by minhcasi** [comment]
@nomicool - you could follow up the solution from Google team - https://github.com/flutter/flutter/issues/54382

For me, the default package still work fine when we upload to Google Play store - thank you!

**Comment by minhcasi** [comment]
Let us know if you have any further question - thank you!

**Comment by nomicool** [comment]
Please dont close it i have still not tried to change sdk version because updating flutter causes errors on projects of fluxstore when ever I execute new project without editing it takes huge to build apk and after edting it shows error many folders under lib importing dependencies did not resolved now I have also tried previous flutter sdk version what to do now please

**Comment by nomicool** [comment]
![Screenshot (2)](https://user-images.githubusercontent.com/25566185/90487508-6be1ff00-e0ef-11ea-8448-415d02c1b8c4.png)
![Screenshot (3)](https://user-images.githubusercontent.com/25566185/90487517-6edcef80-e0ef-11ea-9b8b-da903aab664f.png)
even creating sample app from the android studio is working well and same issues are causing on vs code

**Comment by nomicool** [comment]
running pub get from vs code android studio and terminal causing this is an 
![Screenshot (4)](https://user-images.githubusercontent.com/25566185/90487854-e0b53900-e0ef-11ea-8ec9-e058cf597e23.png)
the issue may these all are the reason for it
