### ISSUE TITLE
Package not found in version 1.7.7

### ISSUE THREAD

**Issue by EdelcioBatista** [inspireui/support#4604]
Hi,

![image](https://user-images.githubusercontent.com/17519814/90290528-6ddc6180-de54-11ea-9bf2-2702c8a07151.png)

I am using VS Code, windows

**Comment by Mrqozy** [comment]
Remove your purchase code!

**Comment by minhcasi** [comment]
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
Also, try to clean up the cache - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one with full information - thank you for your time!
