### ISSUE TITLE
Many errors in Version 1.7.7

### ISSUE THREAD

**Issue by EdelcioBatista** [inspireui/support#4605]
Hi,

I am VS CODE in windows and have many errors:

Launching lib\main.dart on ASUS Z012DC in debug mode...
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\facebook_audience_network-0.7.0\android\src\main\java\com\dsi\facebook_audience_network\FacebookInStreamVideoAdPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\connectivity-0.4.9\android\src\main\java\io\flutter\plugins\connectivity\ConnectivityBroadcastReceiver.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_admob-0.9.3+4\android\src\main\java\io\flutter\plugins\firebaseadmob\AdRequestBuilderFactory.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\uni_links-0.4.0\android\src\main\java\name\avioli\unilinks\UniLinksPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-5.5.0\android\src\main\java\io\flutter\plugins\urllauncher\WebViewActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\webview_flutter-0.3.22+1\android\src\main\java\io\flutter\plugins\webviewflutter\FlutterWebView.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\video_player-0.10.11+2\android\src\main\java\io\flutter\plugins\videoplayer\VideoPlayerPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
✓ Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...
Error: ADB exited with exit code 1
Uninstalling old version...
Performing Streamed Install

adb: failed to install C:\Users\edelc\Desktop\PanthoAPP\FluxStore-woo-1.7.7\source\build\app\outputs\flutter-apk\app.apk: Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package com.inspireui.fluxstore signatures do not match the previously installed version; ignoring!]
Installing build\app\outputs\flutter-apk\app.apk...
Error: ADB exited with exit code 1
Performing Streamed Install

adb: failed to install C:\Users\edelc\Desktop\PanthoAPP\FluxStore-woo-1.7.7\source\build\app\outputs\flutter-apk\app.apk:
Error: Failed to install APK again.
Error launching application on ASUS Z012DC.
Exited (sigterm)

I need help

Tks

**Comment by RomeoDar** [comment]
these are not errors, these are warnings
delete build folder
delete .package file
run flutter clean

uninstall old apk installed in ur phone

then run again

**Comment by minhcasi** [comment]
@EdelcioBatista - pls help to create on one ticket for your all comment on #4604
