### ISSUE TITLE
Problems with shipping and add new language

### ISSUE THREAD

**Issue by Trustedbrands** [inspireui/support#4606]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
- [ ] first issue
I do not get any shipping options, only error message comes up:
exception: sorry, you are not allowed to do that

When I check the server log I get a lot of 401 error

![Simulator Screen Shot - iPhone 11 - 2020-08-15 at 00 12 17](https://user-images.githubusercontent.com/69647853/90296639-53be7580-de8c-11ea-9920-b685b27a69ca.png)

- [ ] second issue
I'm trying to add a new language, but I'm not getting it to work. In the documentation I have to change the file tools.dart

"name": context! = null? S.of (context) .norwegian: "Norwegian",
This one turns red as norwegian does not exist in l10n.dart
Trying to add it manually, but it just gets removed.

<img width="1179" alt="Skjermbilde 2020-08-15 kl  00 17 30" src="https://user-images.githubusercontent.com/69647853/90296795-dd6e4300-de8c-11ea-8d5e-201eed70733a.png">

- [ ] third issue
I also see that I have to add state, city, or province of the country.
In Norway we do not use this, so how can I remove it?

+ Product & version: Fluxstore V 1.7.7
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@Trustedbrands 

- [x] pls make sure to activate the license from mstore-api
- [x] you need to change the .arb file - more detail https://docs.inspireui.com/fluxstore/multi-language/
- [x] It is ok to set the state is blank, you could remove the state config folder

Please help us to give your all comments to the same open ticket - #4591 - thank you!
