### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by aeromatico** [inspireui/support#4607]
![gffgdfg](https://user-images.githubusercontent.com/1625864/90302461-45fcf600-de74-11ea-8228-9c6257d0bd9b.png)

Error while compile.

Please help me. Thank you!

**Comment by minhcasi** [comment]
@aeromatico - this is a missing import from app_init.dart file - we have updated the patching

<img width="981" alt="Screen Shot 2020-08-15 at 10 00 39" src="https://user-images.githubusercontent.com/1459805/90304075-2ef2ee00-dede-11ea-9555-ba5de183803b.png">
