### ISSUE TITLE
app not working after create the apk 

### ISSUE THREAD

**Issue by effec-tline** [inspireui/support#4608]
hey

the app working good on emulator
but after create the apk and app bundle we test the apk on the mobile its not working the give us just the splashscreen

and upload it also to google play and its approved and when anyone download it give just the splash screen and app not opened

how we can resolve it

thanks

Product & version: FluxStore 1.7.5
Flutter (or React Native) version: Flutter 1.17.3-stable
Testing Device/Simulator: android studio last version / simulator nexus 6

Step 2: Please verify license and sharing config files by submitting on this google form, http://verify.inspireui.com, (done )

**Comment by minhcasi** [comment]
@effec-tline - could you check the following solutions:
- The bundle ID should be change to new bundle id, search all `android` folder to see if you have missing place need to be replace `inspireui.com.fluxstore`

- Use the latest `pubspec.yaml` from latest release `1.7.7` - as there is some latest library is updated to compatible with flutter `1.20.x`

**Comment by minhcasi** [comment]
Let us know if you have any question, thanks

**Comment by effec-tline** [comment]
hey

i download the new version and try to upgrade to it and use it from scratch

but when we  do pup get give me this

/Users/user179283/Desktop/flutter/bin/flutter --no-color pub get
Running "flutter pub get" in source-3...                        

Warning: You are using these overridden dependencies:
! flutter_svg 0.18.0
Running "flutter pub get" in source-3...                            1.4s
Process finished with exit code 0


and when running the fluxstore app on the first time without do any update on it give me this error

Launching lib/main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
modules/common_library/lib/widgets/story/story_widget.dart:7:8: Error: Error when reading 'modules/common_library/lib/widgets/story/models/story_config.dart': No such file or directory
import 'models/story_config.dart';
       ^
modules/common_library/lib/widgets/story/story_card.dart:6:8: Error: Error when reading 'modules/common_library/lib/widgets/story/widgets/story_text.dart': No such file or directory
import './widgets/story_text.dart';
       ^
modules/common_library/lib/widgets/story/story_card.dart:7:8: Error: Error when reading 'modules/common_library/lib/widgets/story/models/story.dart': No such file or directory
import 'models/story.dart';
       ^
modules/common_library/lib/widgets/story/story_collection.dart:3:8: Error: Error when reading 'modules/common_library/lib/widgets/story/widgets/page_indicator.dart': No such file or directory
import './widgets/page_indicator.dart';
       ^
modules/common_library/lib/widgets/story/story_widget.dart:30:3: Error: Type 'StoryConfig' not found.
  StoryConfig _storyConfig;
  ^^^^^^^^^^^
modules/common_library/lib/widgets/story/story_card.dart:12:9: Error: Type 'Story' not found.
  final Story story;
        ^^^^^
modules/common_library/lib/widgets/story/story_widget.dart:30:3: Error: 'StoryConfig' isn't a type.
  StoryConfig _storyConfig;
  ^^^^^^^^^^^
modules/common_library/lib/widgets/story/story_widget.dart:34:22: Error: The getter 'StoryConfig' isn't defined for the class '_StoryWidgetState'.
 - '_StoryWidgetState' is from 'package:inspireui/widgets/story/story_widget.dart' ('modules/common_library/lib/widgets/story/story_widget.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'StoryConfig'.
      _storyConfig = StoryConfig.fromJson(config);
                     ^^^^^^^^^^^
modules/common_library/lib/widgets/story/story_card.dart:12:9: Error: 'Story' isn't a type.
  final Story story;
        ^^^^^
modules/common_library/lib/widgets/story/story_card.dart:113:40: Error: The method 'StoryText' isn't defined for the class '_StoryCardState'.
 - '_StoryCardState' is from 'package:inspireui/widgets/story/story_card.dart' ('modules/common_library/lib/widgets/story/story_card.dart').
Try correcting the name to the name of an existing method, or defining a method named 'StoryText'.
                                child: StoryText(
                                       ^^^^^^^^^
modules/common_library/lib/widgets/story/story_collection.dart:99:26: Error: The method 'ScrollingPageIndicator' isn't defined for the class '_StoryCollectionState'.
 - '_StoryCollectionState' is from 'package:inspireui/widgets/story/story_collection.dart' ('modules/common_library/lib/widgets/story/story_collection.dart').
Try correcting the name to the name of an existing method, or defining a method named 'ScrollingPageIndicator'.
                  child: ScrollingPageIndicator(
                         ^^^^^^^^^^^^^^^^^^^^^^


FAILURE: Build failed with an exception.

* Where:
Script '/Users/user179283/Desktop/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 896

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/user179283/Desktop/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 35s
Exception: Gradle task assembleDebug failed with exit code 1



Product & version: FluxStore 1.7.7
Testing Device/Simulator: android studio last version / simulator nexus 6

use android studio on mac os catalina 10.15

**Comment by effec-tline** [comment]
hey

please need resolve to this problem on the new app
