### ISSUE TITLE
[ListApp] SMS permission google play console error

### ISSUE THREAD

**Issue by namtrik** [inspireui/support#461]
- Product: ListApp
 - Your Purchased Code: ccded53c-5f90-41ff-8c6a-fac4faae1017

**Description**
Good afternoon, I have a problem and is that by uploading the signed apk to the Google Play Console tells me that I am requesting SMS permissions for which I must declare why, but I do not use SMS at all, I would like to know in which part of the code are those permissions to disable them and not have that problem when going to the store. Thanks

**Screenshots**
<img width="958" alt="Captura de pantalla 2019-03-30 a la(s) 11 30 14 a  m" src="https://user-images.githubusercontent.com/44480034/55278865-cd79b180-52df-11e9-83eb-9e181987869a.png">

**Comment by thangvo9x** [comment]
Try open app.json file and check the android property. Thanks
