### ISSUE TITLE
Troubleshoot Connectivity Issues in FluxBuilder

### ISSUE THREAD

**Issue by mpsb** [inspireui/support#4610]
**Issues:** 
- Regenerated Thumbnails is not working
- WCFM Connectivity unable to connect to WCLovers API

**Product & version:** Fluxstore Multi Vendor 1.7.7
**Flutter version:** 1.20.2
**Testing Device/Simulator:** Pocophone F1
**Screenshots:**

![regenerate-thumbnails](https://user-images.githubusercontent.com/22747352/90314695-30590080-df48-11ea-8887-461c01d7fd51.JPG)
![wcfm-connectivity](https://user-images.githubusercontent.com/22747352/90314696-32bb5a80-df48-11ea-94c7-a408e01c0a89.JPG)

**Comment by minhcasi** [comment]
@mpsb - thank you for your purchase our Extended License, we have updated the ticket as high priority support 🥇 

Could you help to share your website URL and related Keys to inspireui.team@gmail.com - this issue could be related to missing WCFM plugin API and the Regenerate Image it not updated - https://docs.inspireui.com/fluxstore/multi-vendor/#3-setup-the-regenerate-image-plugin

**Comment by mpsb** [comment]
Hi @minhcasi, I checked again and the Regenerated Thumbnails are working now. I think it just needed time to refresh properly. WCFM Connectivity still doesn't work though. I've already sent my URL through the Google Forms for submitting private files for support tickets. Please check there. Do you need my Woocommerce keys as well? May I ask why?

**Comment by mpsb** [comment]
Also for your reference, I'm using the Demo Products. I'm also using the free version of WCFM, not WCFM Ultimate.

**Comment by mpsb** [comment]
It's all good now, I've just installed the WC Lovers API. Thank you for your help.
