### ISSUE TITLE
MStore pro 4.0.0 -  problem running with expo

### ISSUE THREAD

**Issue by franklinbinauraldev** [inspireui/support#4614]
Best regards

I have a problem running the project with expo. I have installed the following technologies on my local machine. The other thing I want to mention is that it surprises me that the project is not dockerizer, since the project has many dependencies.

- Node 10.22.0 ( i test with the latest version, it dosen't work ).
- Add expo to project pro expo@38.0.9
- Expo cli 3.22.3

Finally install the dependencies with yarn, according to the documentation you have. and run the Expo command.

The reason why I want to use Expo in the pro version is due to the faster development speed, unlike running it native. But I also want to compile it native without depending on Expo to implement CI/CD.

This is the error when running `expo start -c`

![screenshot-2020-08-15_17 01 18 173](https://user-images.githubusercontent.com/69120282/90321577-13f19f80-df19-11ea-991d-112bc330a527.png)

**Comment by minhcasi** [comment]
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by franklinbinauraldev** [comment]
@minhcasi 
Sir, I have created two issues with enough information, and you have closed them. You seem to be unaware of what I just wrote.
