### ISSUE TITLE
Trying to revoke the license to the live website

### ISSUE THREAD

**Issue by el2adiii** [inspireui/support#4615]
Hi, I've activated the license of Fluxstore Woocommerce App on a staging website.
However, I'm migrating to the live one but I can't process with the steps in https://docs.inspireui.com/fluxbuilder/guide-to-use/#deactivate-the-purchase-code
The activation button shows "loading" forever, as per the screenshot.
![Screen Shot 2020-08-16 at 1 59 14 AM](https://user-images.githubusercontent.com/24272642/90323642-483e7d80-df64-11ea-9103-3e40b28265d3.png)

+ Product & version: FluxBuilder
+ Testing Device/Simulator: macOS

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@el2adiii - we have reset the code, please help to try again. 

If it does not work please send us an email to support@inspireui.com with your purchase code - thank you!

**Comment by minhcasi** [comment]
There is also a new release of Fluxbuilder 1.0.7 - please help to download with new branding design 👍

**Comment by el2adiii** [comment]
All Worked! Thank you 👍
