### ISSUE TITLE
Weight based shipping and payment integrations

### ISSUE THREAD

**Issue by krdvijay** [inspireui/support#4616]
**_Step 1 (require): describe detail issues & screenshots_
1. Can you suggest me on weight based flexible shipping, it is giving 0 shipping charge. Though flexible shipping plugin is perfectly working on web.

Does fluxstore woocom support weight based flexible shipping? If yes then what configurations need to be done?

2. Disabled shipping methods are displayed in app. On web they are not displayed as not enabled from woocommerce admin.

3. How can I achieve native razorpay and paytm integrations or else if webview of payment screen then how to directly move to razorpay and paytm webview screens from applications native screen.

+ Product & version: Fluxstore Woocom 1.7.6
+ Flutter (or React Native) version: Flutter
+ Testing Device/Simulator: Android Smart Phone

I have uploaded proof of purchase.

**Comment by minhcasi** [comment]
1. The weight base shipping is not available from the Fluxstore app, but you could try to enable `  "EnableOnePageCheckout": true,` to support process payment via Webview, some extra plugins could be worked fine by using this approache.

2. it seems the team have fix this issue on latest `1.7.7` - pls give a try and let us know

3. you could try the one of these option to support for Webview payment
```
  "EnableOnePageCheckout": false,
  "NativeOnePageCheckout": true,
```

Let us know if you have any question

**Comment by krdvijay** [comment]
How can we achieve #1 as it's required for our business, also this is must have feature for ecommerce to ship varying sizes and shipping rates vary accordingly. Any workaround for flexible weight based shipping?pls mention.

2. Will check and confirm

3. Can you provide details for both of the syntax. That how these are driving changes.

Also it's been observed that ratings (Stars) are not updated after user submitted a review with stars. Though review gets updated and ally gets approved.

Secondly reply of any review appears as another review. Not under the review for which reply has been submitted.

**Comment by krdvijay** [comment]
I am waiting for your response

**Comment by minhcasi** [comment]
1.2 - please give a try to enable this option and test the shipping feature on your site - https://tppr.me/Vou1H

3 - Also it's been observed that ratings (Stars) are not updated after user submitted a review with stars. Though review gets updated and ally gets approved - it could be the caching issues from the site as the app loading previous product data, try to update by Pull to Refresh or restart the app.

4. Secondly, reply of any review appears as another review. Not under the review for which reply has been submitted - we could not reproduce this issue, could you help to verify from the admin site to see if the review belongs to correct product, the review only appear once the admin approve the rating.

5. We will check the rating again, could i know if you are using the default rating from woocommerce ?

6. Can we define Tax segregated on cart and checkout screens - the tax is only supported after the process the Payment on the final step, or it works with OnePageCheckout on 1st question above.

7. Forgot Pwd email is not sent - try to test with 2 options (set the blank forgot password from config.dart or adding to the URL point to Forgot password)

**Comment by krdvijay** [comment]
> 3 - Also it's been observed that ratings (Stars) are not updated after user submitted a review with stars. Though review gets updated and ally gets approved - it could be the caching issues from the site as the app loading previous product data, try to update by Pull to Refresh or restart the app.


Root cause has been identified regarding this particular #3 issue: Here is stepwise STR:
i. User submits a review with rating
ii. Review gets approved automatically on woocommerce admin without requiring administrator to approve. 
Result: Review start to display under review section but rating is not getting updated

iii. When administrator explicitly unapprove (as it got automatically approved) and then approve.
Result: Rating and Review count gets updated.

So the issue is that review gets approved automatically, which should not happen. And removing this automatic action of approval should fix this issue.

Please have a look and provide me with the fix.

**Comment by minhcasi** [comment]
@krdvijay - thank you for quickly feedback, we will investigate the rating and let you know.

**Comment by minhtruong315** [comment]
Hi @krdvijay give me your skype? I will help you check remotely
Thanks

**Comment by krdvijay** [comment]
Hi @minhtruong315  here is my skype id vijayendra.dubey , please connect to discuss

**Comment by krdvijay** [comment]
Could you pls provide me access to Gitlab repository, I have already requested for the same my email id vijayendra.vj@gmail.com.

**Comment by minhtruong315** [comment]
@krdvijay I added your skype. pls accept. 
for webview checkout, it will checkout on your website. so you need to update your website to hide header, footer.

**Comment by krdvijay** [comment]
> @krdvijay You can try this solution to fix review issue
> 
> * Change createReview function in services/woo_commerce.dart like this
> 
> ```
> @override
>   Future<Null> createReview(
>       {String productId, Map<String, dynamic> data}) async {
>     try {
>       data["product_id"] = productId;
>       var response =
>           await wcApi.postAsync("products/reviews", data, version: 3);
>       if (response is Map && isNotBlank(response["message"])) {
>         throw Exception(response["message"]);
>       } else {
>         return;
>       }
>     } catch (e) {
>       rethrow;
>     }
>   }
> ```
> 
> * Change sendReview function in screens/detail/review.dart like this
> 
> ```
> void sendReview() {
>     if (rating == 0.0) {
>       final snackBar = SnackBar(content: Text(S.of(context).ratingFirst));
>       Scaffold.of(context).showSnackBar(snackBar);
>       return;
>     }
>     if (comment.text == null || comment.text.isEmpty) {
>       final snackBar = SnackBar(content: Text(S.of(context).commentFirst));
>       Scaffold.of(context).showSnackBar(snackBar);
>       return;
>     }
>     final user = Provider.of<UserModel>(context, listen: false);
>     services.createReview(productId: productId, data: {
>       "review": comment.text,
>       "reviewer": user.user.name,
>       "reviewer_email": user.user.email,
>       "rating": rating,
>       "status":
>           kAdvanceConfig["EnableApprovedReview"] == true ? "approved" : "hold"
>     }).then((onValue) {
>       getListReviews();
>       setState(() {
>         rating = 0.0;
>         comment.text = "";
>       });
>     });
>   }
> ```
> 
> * Add "EnableApprovedReview" config in common/config/general/dart
> 
> ```
> const kAdvanceConfig = {
>      "DefaultLanguage": "en",
>       ........
>       //if the woo commerce website supports multi languages. set false if the website only have one language
>      "isMultiLanguages": true,
> 
>       ///Review gets approved automatically on woocommerce admin without requiring administrator to approve.
>       "EnableApprovedReview": false
> }
> ```

I will try and get back to you, just confirming does this solution also provide fix for aforesaid below issue?
#4. Secondly, reply of any review appears as another review. Not under the review for which reply has been submitted.

**Comment by minhtruong315** [comment]
@krdvijay Fluxstore doesn't support reply review UI now. we will note to backlog and upgrade it later.

**Comment by krdvijay** [comment]
> > @krdvijay You can try this solution to fix review issue
> > 
> > * Change createReview function in services/woo_commerce.dart like this
> > 
> > ```
> > @override
> >   Future<Null> createReview(
> >       {String productId, Map<String, dynamic> data}) async {
> >     try {
> >       data["product_id"] = productId;
> >       var response =
> >           await wcApi.postAsync("products/reviews", data, version: 3);
> >       if (response is Map && isNotBlank(response["message"])) {
> >         throw Exception(response["message"]);
> >       } else {
> >         return;
> >       }
> >     } catch (e) {
> >       rethrow;
> >     }
> >   }
> > ```
> > 
> > 
> > 
> > * Change sendReview function in screens/detail/review.dart like this
> > 
> > ```
> > void sendReview() {
> >     if (rating == 0.0) {
> >       final snackBar = SnackBar(content: Text(S.of(context).ratingFirst));
> >       Scaffold.of(context).showSnackBar(snackBar);
> >       return;
> >     }
> >     if (comment.text == null || comment.text.isEmpty) {
> >       final snackBar = SnackBar(content: Text(S.of(context).commentFirst));
> >       Scaffold.of(context).showSnackBar(snackBar);
> >       return;
> >     }
> >     final user = Provider.of<UserModel>(context, listen: false);
> >     services.createReview(productId: productId, data: {
> >       "review": comment.text,
> >       "reviewer": user.user.name,
> >       "reviewer_email": user.user.email,
> >       "rating": rating,
> >       "status":
> >           kAdvanceConfig["EnableApprovedReview"] == true ? "approved" : "hold"
> >     }).then((onValue) {
> >       getListReviews();
> >       setState(() {
> >         rating = 0.0;
> >         comment.text = "";
> >       });
> >     });
> >   }
> > ```
> > 
> > 
> > 
> > * Add "EnableApprovedReview" config in common/config/general/dart
> > 
> > ```
> > const kAdvanceConfig = {
> >      "DefaultLanguage": "en",
> >       ........
> >       //if the woo commerce website supports multi languages. set false if the website only have one language
> >      "isMultiLanguages": true,
> > 
> >       ///Review gets approved automatically on woocommerce admin without requiring administrator to approve.
> >       "EnableApprovedReview": false
> > }
> > ```
> 
> I will try and get back to you, just confirming does this solution also provide fix for aforesaid below issue?
> #4. Secondly, reply of any review appears as another review. Not under the review for which reply has been submitted.

Issue still persists. Root cause remains the same. Any review given gets automatically approved which is causing this issue. Reviews provided should be in unapproved state, once moderated and approved by admin should be approved only.
Kindly look into it

**Comment by krdvijay** [comment]
> > > @krdvijay You can try this solution to fix review issue
> > > 
> > > * Change createReview function in services/woo_commerce.dart like this
> > > 
> > > ```
> > > @override
> > >   Future<Null> createReview(
> > >       {String productId, Map<String, dynamic> data}) async {
> > >     try {
> > >       data["product_id"] = productId;
> > >       var response =
> > >           await wcApi.postAsync("products/reviews", data, version: 3);
> > >       if (response is Map && isNotBlank(response["message"])) {
> > >         throw Exception(response["message"]);
> > >       } else {
> > >         return;
> > >       }
> > >     } catch (e) {
> > >       rethrow;
> > >     }
> > >   }
> > > ```
> > > 
> > > 
> > > 
> > > * Change sendReview function in screens/detail/review.dart like this
> > > 
> > > ```
> > > void sendReview() {
> > >     if (rating == 0.0) {
> > >       final snackBar = SnackBar(content: Text(S.of(context).ratingFirst));
> > >       Scaffold.of(context).showSnackBar(snackBar);
> > >       return;
> > >     }
> > >     if (comment.text == null || comment.text.isEmpty) {
> > >       final snackBar = SnackBar(content: Text(S.of(context).commentFirst));
> > >       Scaffold.of(context).showSnackBar(snackBar);
> > >       return;
> > >     }
> > >     final user = Provider.of<UserModel>(context, listen: false);
> > >     services.createReview(productId: productId, data: {
> > >       "review": comment.text,
> > >       "reviewer": user.user.name,
> > >       "reviewer_email": user.user.email,
> > >       "rating": rating,
> > >       "status":
> > >           kAdvanceConfig["EnableApprovedReview"] == true ? "approved" : "hold"
> > >     }).then((onValue) {
> > >       getListReviews();
> > >       setState(() {
> > >         rating = 0.0;
> > >         comment.text = "";
> > >       });
> > >     });
> > >   }
> > > ```
> > > 
> > > 
> > > 
> > > * Add "EnableApprovedReview" config in common/config/general/dart
> > > 
> > > ```
> > > const kAdvanceConfig = {
> > >      "DefaultLanguage": "en",
> > >       ........
> > >       //if the woo commerce website supports multi languages. set false if the website only have one language
> > >      "isMultiLanguages": true,
> > > 
> > >       ///Review gets approved automatically on woocommerce admin without requiring administrator to approve.
> > >       "EnableApprovedReview": false
> > > }
> > > ```
> > 
> > 
> > I will try and get back to you, just confirming does this solution also provide fix for aforesaid below issue?
> > #4. Secondly, reply of any review appears as another review. Not under the review for which reply has been submitted.
> 
> Issue still persists. Root cause remains the same. Any review given gets automatically approved which is causing this issue. Reviews provided should be in unapproved state, once moderated and approved by admin should be approved only.
> Kindly look into it

I just observed there was error in one of the files, issue seems resolved, thanks for your support

**Comment by minhtruong315** [comment]
@krdvijay so are your issues resolved?

**Comment by krdvijay** [comment]
@minhtruong315- An issue observed
coupon code once applied on cart page on navigating to webview checkout its not reflecting and no coupons are shown applied.

please check

**Comment by minhtruong315** [comment]
@krdvijay I checked your website. it's working well with coupon. are you using fluxstore 1.7.7?
![Simulator Screen Shot - iPhone 11 - 2020-08-26 at 14 35 48](https://user-images.githubusercontent.com/10402500/91274819-77958b80-e7a9-11ea-95bd-4bcbddf16fc4.png)

**Comment by krdvijay** [comment]
> @krdvijay I checked your website. it's working well with coupon. are you using fluxstore 1.7.7?
> ![Simulator Screen Shot - iPhone 11 - 2020-08-26 at 14 35 48](https://user-images.githubusercontent.com/10402500/91274819-77958b80-e7a9-11ea-95bd-4bcbddf16fc4.png)

I have upgraded to 1.7.7, this particular issue got resolved... Thanks.
Please keep this ticket active as any new observation will be listed here.

**Comment by krdvijay** [comment]
Hi @minhtruong315- Can we create custom message for no internet
![image](https://user-images.githubusercontent.com/69688125/91374502-f6380a80-e835-11ea-9d9a-2ee5b9213bd6.png)

**Comment by krdvijay** [comment]
> @minhtruong315

@minhtruong315- Hi waiting for your response... pls provide a resolution.

**Comment by minhtruong315** [comment]
@krdvijay I sent you updates to fix no internet connection. please check and let me know

**Comment by minhcasi** [comment]
@krdvijay - let us know if you have any question

**Comment by krdvijay** [comment]
> @krdvijay - let us know if you have any question

@minhcasi- Hi This issue is not resolved. giving errors on updating with new files provided
@minhtruong315- Hi, the code provided is giving another compilation error. 

{
	"resource": "/XXXX/FluxStore-woo-1.7.7/source/lib/services/index.dart",
	"owner": "dart",
	"code": {
		"value": "undefined_identifier",
		"target": {
			"$mid": 1,
			"external": "https://dart.dev/tools/diagnostic-messages#undefined_identifier",
			"path": "/tools/diagnostic-messages",
			"scheme": "https",
			"authority": "dart.dev",
			"fragment": "undefined_identifier"
		}
	},
	"severity": 8,
	"message": "Undefined name 'MyConnectivity'.\nTry correcting the name to one that is defined, or defining the name.",
	"source": "dart",
	"startLineNumber": 530,
	"startColumn": 14,
	"endLineNumber": 530,
	"endColumn": 28,
	"tags": []
}
