### ISSUE TITLE
Fluxstore 1.7.7 code run issue

### ISSUE THREAD

**Issue by Marwa229** [inspireui/support#4617]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
I have a problem I ,Can't run code in android studio it got me this issue
Because flutter_svg >=0.18.0 depends on xml ^4.1.0 and every version of flutter_test from sdk depends on xml 3.6.1, flutter_svg >=0.18.0 is incompatible with flutter_test from sdk.

So, because fstore depends on both flutter_test any from sdk and flutter_svg 0.18.0, version solving failed.
pub get failed (1; So, because fstore depends on both flutter_test any from sdk and flutter_svg 0.18.0, version solving failed.)

+ Product & version:1.7.7
+ Flutter (or React Native) version: 1.21.0-9.0.pre 
+ Testing Device/Simulator: Samsung A20S
+ Screenshot issues (drag the file to attach here): 

![Screenshot (124)](https://user-images.githubusercontent.com/59913375/90331489-0e499780-dfb5-11ea-9d5e-0608a73e3367.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com
![Screenshot (124)](https://user-images.githubusercontent.com/59913375/90331480-fbcf5e00-dfb4-11ea-8868-6f05311b9a40.png)
_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@Marwa229 - pls use the flutter stable channel 

```
flutter stable channel
flutter upgrade --force
```

**Comment by minhcasi** [comment]
Let us know if you have any question - thank you!
