### ISSUE TITLE
Woocommerce data is not showing and build error 

### ISSUE THREAD

**Issue by GreenShopBD** [inspireui/support#4618]
https://github.com/inspireui/support/issues/4456
On the previous issue we have submitted all the proof 
@minhcasi 
And we have updated the latest version of fluxesStote
 Fluxstore Pro - Flutter E-commerce Full App for Magento, Opencart, and Woocommerce

We have discussed from last one month for lots of issue if one fixed another is ready 
Last time we have faced build error and the problem is still happening....

Pls check the issue and fixed as soon as possible or pls tell me the refund process 

Thank you 

Error is : 

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve com.google.firebase:firebase-iid:[20.0.1].
     Required by:
         project :app > com.google.firebase:firebase-messaging:20.0.1
      > Failed to list versions for com.google.firebase:firebase-iid.
         > Unable to load Maven meta-data from https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-iid/maven-metadata.xml.
            > org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.

 
![39450A22-F015-44B7-9EF3-3BC298FD299A](https://user-images.githubusercontent.com/68589110/90333038-2edd1600-dfe4-11ea-9164-f1b9f5ae7ae6.jpeg)

**Comment by minhcasi** [comment]
@GreenShopBD try to clean up the cache by using this guide - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

Keep using the default build grade and config from the download package, don't try to upgrade the building grade for config from Android folder

**Comment by GreenShopBD** [comment]
Hello 
@minhcasi 
We are trying as the guideline and let you know

**Comment by dreamtouchapp** [comment]
@minhcasi  We have followed all the instructions in common issues link you provided. 
I am sorry to inform you that we are still having the same issue...which is FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve com.google.firebase:firebase-iid:[20.0.1].
     Required by:
         project :app > com.google.firebase:firebase-messaging:20.0.1
      > Failed to list versions for com.google.firebase:firebase-iid.
         > Unable to load Maven meta-data from https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-iid/maven-metadata.xml.
            > org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
      > Failed to list versions for com.google.firebase:firebase-iid.
         > Unable to load Maven meta-data from https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-iid/maven-metadata.xml.
            > org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
      > Failed to list versions for com.google.firebase:firebase-iid.
         > Unable to load Maven meta-data from https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-iid/maven-metadata.xml.
            > org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
      > Failed to list versions for com.google.firebase:firebase-iid.
         > Unable to load Maven meta-data from https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-iid/maven-metadata.xml.
            > org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
      > Failed to list versions for com.google.firebase:firebase-iid.
         > Unable to load Maven meta-data from https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-iid/maven-metadata.xml.
            > org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
      > Failed to list versions for com.google.firebase:firebase-iid.
         > Unable to load Maven meta-data from https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-iid/maven-metadata.xml.
            > org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
      > Failed to list versions for com.google.firebase:firebase-iid.
         > Unable to load Maven meta-data from https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-iid/maven-metadata.xml.
            > org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
      > Failed to list versions for com.google.firebase:firebase-iid.
         > Unable to load Maven meta-data from https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-iid/maven-metadata.xml.
            > org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
      > Failed to list versions for com.google.firebase:firebase-iid.
         > Unable to load Maven meta-data from https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-iid/maven-metadata.xml.
            > org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
      > Failed to list versions for com.google.firebase:firebase-iid.
         > Unable to load Maven meta-data from https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-iid/maven-metadata.xml.
            > org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
      > Failed to list versions for com.google.firebase:firebase-iid.
         > Unable to load Maven meta-data from https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-iid/maven-metadata.xml.
            > org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
      > Failed to list versions for com.google.firebase:firebase-iid.
         > Unable to load Maven meta-data from https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-iid/maven-metadata.xml.
            > org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
      > Failed to list versions for com.google.firebase:firebase-iid.
         > Unable to load Maven meta-data from https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-iid/maven-metadata.xml.
            > org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
      > Failed to list versions for com.google.firebase:firebase-iid.
         > Unable to load Maven meta-data from https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-iid/maven-metadata.xml.
            > org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
      > Failed to list versions for com.google.firebase:firebase-iid.
         > Unable to load Maven meta-data from https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-iid/maven-metadata.xml.
            > org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
      > Failed to list versions for com.google.firebase:firebase-iid.
         > Unable to load Maven meta-data from https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-iid/maven-metadata.xml.
            > org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
      > Failed to list versions for com.google.firebase:firebase-iid.
         > Unable to load Maven meta-data from https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-iid/maven-metadata.xml.
            > org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
      > Failed to list versions for com.google.firebase:firebase-iid.
         > Unable to load Maven meta-data from https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-iid/maven-metadata.xml.
            > org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
      > Failed to list versions for com.google.firebase:firebase-iid.
         > Unable to load Maven meta-data from https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-iid/maven-metadata.xml.
            > org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
      > Failed to list versions for com.google.firebase:firebase-iid.
         > Unable to load Maven meta-data from https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-iid/maven-metadata.xml.
            > org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
      > Failed to list versions for com.google.firebase:firebase-iid.
         > Unable to load Maven meta-data from https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-iid/maven-metadata.xml.
            > org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
      > Failed to list versions for com.google.firebase:firebase-iid.
         > Unable to load Maven meta-data from https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-iid/maven-metadata.xml.
            > org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
      > Failed to list versions for com.google.firebase:firebase-iid.
         > Unable to load Maven meta-data from https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-iid/maven-metadata.xml.
            > org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
      > Failed to list versions for com.google.firebase:firebase-iid.
         > Unable to load Maven meta-data from https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-iid/maven-metadata.xml.
            > org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
      > Failed to list versions for com.google.firebase:firebase-iid.
         > Unable to load Maven meta-data from https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-iid/maven-metadata.xml.
            > org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
      > Failed to list versions for com.google.firebase:firebase-iid.
         > Unable to load Maven meta-data from https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-iid/maven-metadata.xml.
            > org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
      > Failed to list versions for com.google.firebase:firebase-iid.
         > Unable to load Maven meta-data from https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-iid/maven-metadata.xml.
            > org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
      > Failed to list versions for com.google.firebase:firebase-iid.
         > Unable to load Maven meta-data from https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-iid/maven-metadata.xml.
            > org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
      > Failed to list versions for com.google.firebase:firebase-iid.
         > Unable to load Maven meta-data from https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-iid/maven-metadata.xml.
            > org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
      > Failed to list versions for com.google.firebase:firebase-iid.
         > Unable to load Maven meta-data from https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-iid/maven-metadata.xml.
            > org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
      > Failed to list versions for com.google.firebase:firebase-iid.
         > Unable to load Maven meta-data from https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-iid/maven-metadata.xml.
            > org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
      > Failed to list versions for com.google.firebase:firebase-iid.
         > Unable to load Maven meta-data from https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-iid/maven-metadata.xml.
            > org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
      > Failed to list versions for com.google.firebase:firebase-iid.
         > Unable to load Maven meta-data from https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-iid/maven-metadata.xml.
            > org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
      > Failed to list versions for com.google.firebase:firebase-iid.
         > Unable to load Maven meta-data from https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-iid/maven-metadata.xml.
            > org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 4s
Exception: Gradle task assembleDebug failed with exit code 1

please help us to overcome

**Comment by GreenShopBD** [comment]
****Urgent replay pls**** 
Hello dear @minhcasi  from almost last 2 months we are try to build the app but we can not, and you’re also doing the Best But the issue is not fixed, so we are losing our time and we lose our money also due the late build the apps. If the issue is not fixed this time pls refund me my amount and pls let me know the refund process. 
I can not wait more I have to go another apps
@dreamtouchapp 

Regards 
GreenTechBD

**Comment by minhcasi** [comment]
Hi @GreenShopBD - please try your best, give a try with fresh Flutter Example guide - https://flutter.dev/docs/get-started/test-drive

If you could not use the product so far, it's ok to refund on this link https://help.market.envato.com/hc/en-us/articles/202821460-Can-I-Get-A-Refund- - thank you for your time!

**Comment by GreenShopBD** [comment]
@dreamtouchapp 
Asif pls follow the guidelines and check
