### ISSUE TITLE
No Proper Documentation for Upgrading the code after new release in the codecanyon 

### ISSUE THREAD

**Issue by Shopyloot** [inspireui/support#4619]
I found a documentation which is not very helpful i mean not able to understand how to merge code. Please help with a clear and best way to update the source code with out loosing previous changes.

I already have the project folder now what to do ? 

Steps did 
1. Clicked the Fork button to fork our FluxStore-Pro repo to our Git repo
2. After fork process Cloned the source from our Fork repository on a new folder
3. Installed Sourcetree
4. Now which project folder should i improt in the sourcetree ? the previous one that i made all the necessary changes with my website credentials or the new cloned project folder ? this is where i stucked.

Please help

**Comment by and-eee** [comment]
I agree, I haven't been able to follow the instructions. Both video and written are not clear or appropriate for someone who isn't familiar with git and sourcetree.

**Comment by minhcasi** [comment]
@Shopyloot @and-eee - let us know if this guide and video here is missing something - https://medium.com/@inspireui/how-to-upgrade-fluxstore-projects-by-using-git-cebde7489ea6

As the source has been changed a lot of files, there is the only way to merge the source via git, we don't have a better solution so far :)

**Comment by minhcasi** [comment]
Let us know if you have any further question - thank you for your time!
