### ISSUE TITLE
[MStore] Facebook error implementation

### ISSUE THREAD

**Issue by hakihosting** [inspireui/support#462]
![image](https://user-images.githubusercontent.com/47614045/55280769-1191a400-532a-11e9-8e12-100dcbc60a5f.png)

I have this error on ipad

**Comment by thangvo9x** [comment]
Please provide your purchase code.

**Comment by hakihosting** [comment]
Purchase code : ac9d522a-a783-4f9c-a882-7dc694488d5d

**Comment by luyx2412** [comment]
Closed! create many issues.

**Comment by hakihosting** [comment]
OK but it's ok to close my ticket ,but the problem still be there

**Comment by imshashank** [comment]
What was the solution?

**Comment by hakihosting** [comment]
Nothing , i am still blocked , app store didn't approve because i have this problem
