### ISSUE TITLE
Unit tests fail - Dependency problems

### ISSUE THREAD

**Issue by franklinbinauraldev** [inspireui/support#4620]
Unit tests fail for both projects

MStore - Expo

![Captura de pantalla de 2020-08-15 23-21-36](https://user-images.githubusercontent.com/69120282/90335653-61ffb500-dfa4-11ea-899e-9eba5adc0b85.png)

MStore - Pro

![Captura de pantalla de 2020-08-15 23-31-29](https://user-images.githubusercontent.com/69120282/90335655-662bd280-dfa4-11ea-8d07-23014baad389.png)

**Comment by minhcasi** [comment]
@franklinbinauraldev - sorry we did not apply the unit test for the Mstore Pro project 😅

**Comment by minhcasi** [comment]
Let us know if you have any questions - thank you!
