### ISSUE TITLE
some of my catagories in fluxstore mv is not showing all of its products ,

### ISSUE THREAD

**Issue by yasaavaise** [inspireui/support#4623]
hi,
my app and website are both live ,
application is working fine i am using version 1.7.5,
i am yet to upgrade to 1.7.7
so the thing is some of my products is not showing in the products categories and sub categories,
rest api and app are both working fine without any errors but my products are still missing from the product page,
but it can be seen in the vendor store ,
please help me i am not able to figure out the exact reason behind it,
because 80% of my product categorizes is showing all the products they have,
example:- "mens shirt" have 108 products but it shows only 59
                 "smartphone" have 28 products but it shows only 15,
i have tried everything which i can my app is live on play store ,
and i have to fix it to decrease retention rate,
so plz help me if you can and as soon as you can,
one more thing,
if you can able to put search in the product page as well that would be really nice hope you take care of it in future update ,
and is there any way i can set 3 column grid view as default instead of 2 column grid of my products , in the product page .....?,
its not shown in your docs,

its a request please dont delete solved issues i was solving all the issues just by reading those and now i am not able to find any related issues

**Comment by minhcasi** [comment]
@yasaavaise - congratulation to go live app, could you share the app URL here so that we could give some testing and feedback

You could give a try to use the Fluxbuilder and test the Integration issues on your website - http://fluxbuilder.com/ - this tool is free for use

**Comment by yasaavaise** [comment]
sure ,
i added Vietnam to the release country list,
i am sure within some hours you will be able to see my app,
i also put the website webview link in the app setting drawer in case you wanna visit my website as well,
my website url is-https://betuldeliveries.com
here is the app url-https://play.google.com/store/apps/details?id=com.jaihindtech.Betuldeliveries.vendor,
while i was trying to resolve my issue i found that if i republish my products while making it visible in both search and catalog and change my particular category setting  to both sub categories and products in wp ,
i was able to get all the product for 3/5 categories on which every products is not shown,
but 2 of my categories are still not able to get all of its products ,
i am sure it is because of some of the setting in wp,
but i have followed every instruction of your website precisely regarding setting up my wordpress website,
one more thing i notice the home page search works terrible it does not show all the products and it shows them in list view while search in bottom navigational drawer works excellent and it shows all the  products  while being in grid view,
if you want i can give you username password of my wordpress admin panel in your email just so that you can see if i have missed anything there,

**Comment by minhcasi** [comment]
@yasaavaise - love your app homepage customize - it looks very good 🎉

<img width="230" alt="Screen Shot 2020-08-18 at 14 20 45" src="https://user-images.githubusercontent.com/1459805/90482829-037e3680-e15e-11ea-9853-9598e75516d5.png">

Please share the screenshot detail issues regarding to the Category and share the private login to inspireui.team@gmail.com

**Comment by minhcasi** [comment]
Let us know if you have any update - thank you!

**Comment by yasaavaise** [comment]
thanks to your source code i am able to put this awesome looking app,
so the thing is the categories have some issues i made some new category and now its working fine,
and i decided to remove both of the home screen search so that user can opt for bottom navigational drawer search,
and i have some of these broken category icon in my home screen
i changed my config file and thought of updating my app in play store,
but i ran into some new issues-
i had upgraded my flutter and now when i am building release it shows me this error,
"Codepoint 58848 not found in font, aborting".
'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 896
i know its not your fault since i am guessing either i need to downgrade any dependencies ,
or i need to upgrade any of my sdk
i am currently compiling my app on andriod-r sdk 30,
but i am not running its latest version,
my laptop and internet connection is not powerful enough to upgrade all this stuff overnight,
so is it possible if i upload my config.json file in your mstore api ,
it will update my app homescreen ,
i have disabled caching in my app settings (iscachingenabled : false),
you know my app is live so i am not taking risk of messing with mstore api,
and if its not possible than 
 would you be able to tell me which of the dependencies i need to downgrade to build my release,

**Comment by yasaavaise** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 10.0.18363.1016], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    X Android SDK file not found: C:\Users\Rimsha Humaira\AppData\Local\Android\sdk\build-tools\30.0.2\aapt.
[√] Android Studio (version 4.0)
[√] VS Code (version 1.47.3)
[!] Connected device
    ! No devices available

**Comment by yasaavaise** [comment]
this is the code written in line 896 of flutter.gradle
project.exec {
            logging.captureStandardError LogLevel.ERROR
            executable flutterExecutable.absolutePath
            workingDir sourceDir
            if (localEngine != null) {
                args "--local-engine", localEngine
                args "--local-engine-src-path", localEngineSrcPath
            }
            if (verbose) {
                args "--verbose"
            } else {
                args "--quiet"
            }
            args "assemble"
            args "--depfile", "${intermediateDir}/flutter_build.d"
            args "--output", "${intermediateDir}"
            if (performanceMeasurementFile != null) {
                args "--performance-measurement-file=${performanceMeasurementFile}"
            }
            if (!fastStart || buildMode != "debug") {
                args "-dTargetFile=${targetPath}"
            } else {
                args "-dTargetFile=${Paths.get(flutterRoot.absolutePath, "examples", "splash", "lib", "main.dart")}"
            }
            args "-dTargetPlatform=android"
            args "-dBuildMode=${buildMode}"
            if (trackWidgetCreation != null) {
                args "-dTrackWidgetCreation=${trackWidgetCreation}"
            }
            if (splitDebugInfo != null) {
                args "-dSplitDebugInfo=${splitDebugInfo}"
            }
            if (treeShakeIcons == true) {
                args "-dTreeShakeIcons=true"
            }
            if (dartObfuscation == true) {
                args "-dDartObfuscation=true"
            }
            if (dartDefines != null) {
                args "--DartDefines=${dartDefines}"
            }
            if (bundleSkSLPath != null) {
                args "-iBundleSkSLPath=${bundleSkSLPath}"
            }
            if (extraGenSnapshotOptions != null) {
                args "--ExtraGenSnapshotOptions=${extraGenSnapshotOptions}"
            }
            if (extraFrontEndOptions != null) {
                args "--ExtraFrontEndOptions=${extraFrontEndOptions}"
            }
            args ruleNames
        }
    }
}

**Comment by minhcasi** [comment]
@yasaavaise - could you try to compare with the latest `build.grade` and update all library `pubspec.yaml` from `1.7.7`, then update to your own config? 

We have test and update the fluxstore 1.7.7 to compatible with latest flutter 1.20.x - you could get detail modified file from our gitlab

**Comment by minhcasi** [comment]
Let us know your checking - thank you!

**Comment by minhcasi** [comment]
Hi sir, let us know if you have any question, feel free to reopen the ticket if you need any support - thank you!
