### ISSUE TITLE
In order history section, order notes are coming which is showing all details of Woocommerce Product Updation

### ISSUE THREAD

**Issue by rawaniharsh** [inspireui/support#4625]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
1. I want to choose 10 categories in the category section but all categories are coming by default and I unable to remove it.
2. I want to change the preloader of App, please guide me the process.
3. In the order history section, order notes are coming which showing all details of woocommerce product updation and I want to remove it.

+ Product & version: FluxStore-woo-1.7.6
+ Flutter (or React Native) version: 1.17.5

+ Screenshot issues (drag the file to attach here): 
![2](https://user-images.githubusercontent.com/34198228/90357689-778ee080-e071-11ea-9783-382964d0e5f7.jpeg)
![9](https://user-images.githubusercontent.com/34198228/90357917-1c112280-e072-11ea-9394-0e2e8365e1ba.jpeg)
![8](https://user-images.githubusercontent.com/34198228/90357936-30edb600-e072-11ea-80dd-b162245956da.jpeg)

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@rawaniharsh - thank you for the question

1. you could try to use the Fluxbuilder to customize the list category - http://fluxbuilder.com/

2. it could update from this file https://tppr.me/w3m0p

3. it could update the file status for order note from this file - https://tppr.me/doAEa 

Thank you!

**Comment by minhcasi** [comment]
Let us know if you have any question - thank you!

**Comment by rawaniharsh** [comment]
I tried to edit category section through fluxbuilder but I unable to do it. Whenever I am clicking on any category under category section, nothing is happening.

**Comment by minhcasi** [comment]
@rawaniharsh - could you share the screenshot/video issues, pls make sure to use the latest Fluxbuilder version https://github.com/inspireui/fluxbuilder/releases/tag/v1.0.8

And login to the fluxbuilder so that it could save your section

**Comment by minhcasi** [comment]
Hi Sir, let us know if you have any update - thank you!

**Comment by rawaniharsh** [comment]
I updated the images in the category section but still, images are not showing. Please f
![10](https://user-images.githubusercontent.com/34198228/90761098-87702400-e300-11ea-8dc4-fc0a833f53b0.jpeg)
ix it!

**Comment by minhcasi** [comment]
@rawaniharsh - you could manage the Image from your Woocommerce side - edit category and upload new image - thanks

**Comment by rawaniharsh** [comment]
I uploaded the images but still images are not showing.

**Comment by minhcasi** [comment]
Hi sir, let us know if you have any question, feel free to reopen the ticket if you need any support - thank you!

**Comment by rawaniharsh** [comment]
1. How to remove your account and back to shop section from order success page.
![3](https://user-images.githubusercontent.com/34198228/91257780-5ff9db00-e788-11ea-99d1-831a3bb4f00d.jpeg)

2. How to change "continue to review text".
![5](https://user-images.githubusercontent.com/34198228/91257835-7e5fd680-e788-11ea-83f5-e0f274f8c48d.jpeg)

**Comment by minhcasi** [comment]
@rawaniharsh - pls try to use this Inspector tool - https://www.youtube.com/watch?v=yGMt3Y20Zmg - you could customize any UI from the app by using it

Ref doc: https://docs.inspireui.com/fluxstore/customization/

**Comment by rawaniharsh** [comment]
Thanks

**Comment by rawaniharsh** [comment]
I am new in Flutter that's why I am getting trouble in it.

Whenever I am trying to use the flutter inspector tool, the corresponding file is not opening.
I enclosed the video below in zip.
[inspector.zip](https://github.com/inspireui/support/files/5136614/inspector.zip)

**Comment by minhcasi** [comment]
@rawaniharsh - could you try right-click from the Tree of Inspector and select jump to source

**Comment by minhcasi** [comment]
Let us know if you have any question - thank you!

**Comment by rawaniharsh** [comment]
Hi team, I have some queries. Please help me!

1. I only want to show native payment, not webview payment. How to do this please help me in details.

2. Search bar is not working correctly.

3. I want to add logo which redirect to home page in the product page and category page. How to do this please help.

**Comment by rawaniharsh** [comment]
One more question.

1. Product title is showing in line which is cutting title parts but we want to show the title in two lines same as Amazon.

**Comment by minhcasi** [comment]
@rawaniharsh - please share some screenshot issues so that we could understand more on your issues - thank you!

**Comment by rawaniharsh** [comment]
![3](https://user-images.githubusercontent.com/34198228/92907602-175a4700-f443-11ea-8139-d12270e81365.jpeg)
![2](https://user-images.githubusercontent.com/34198228/92907639-1fb28200-f443-11ea-9b80-2b690b35f451.jpeg)
![4](https://user-images.githubusercontent.com/34198228/92907646-20e3af00-f443-11ea-89f5-6bde98b15135.jpeg)
![5](https://user-images.githubusercontent.com/34198228/92907651-217c4580-f443-11ea-9809-85d1d5c67d65.jpeg)
![6](https://user-images.githubusercontent.com/34198228/92907654-22ad7280-f443-11ea-8edf-1e1e4ab57f5b.jpeg)
![7](https://user-images.githubusercontent.com/34198228/92907658-23460900-f443-11ea-801c-3bc620eb0934.jpeg)
![1](https://user-images.githubusercontent.com/34198228/92907661-23de9f80-f443-11ea-922e-ac00e27fec0b.jpeg)

1. We dont want webview payment because it is not app friendly at all. Let us know the alternatives!
2. We want logo in the header on all the pages.
3. We want full product title in the home page also, it is showing half title in the home page.

**Comment by minhcasi** [comment]
@rawaniharsh - could i confirm it is used latest Fluxstore 1.7.7 - the spacing is already fixed on the latest release - thank you!

**Comment by rawaniharsh** [comment]
1. Also I want to  use logo in all the page which redirect to home page.
2. See in the screenshot, I purchased two products at a time from different vendors. After successful order, It is showing three orders in the my order page. One order for each vendor and one aggregate vendor. I just want to show two order(for two vendors) not three.

![WhatsApp Image 2020-09-12 at 3 05 54 PM](https://user-images.githubusercontent.com/34198228/92992621-e264f780-f509-11ea-8376-9fa52d553eec.jpeg)

**Comment by minhcasi** [comment]
1. try to customize and show the AppBar for all screen

2. Did you get same order issue listing on your website? do you mean the order have been duplicated?

**Comment by rawaniharsh** [comment]
1. What we want to say is, suppose there are two vendors in the website and a customer bought items from both the vendors then in that situation woocommerce is showing suborders but in app it is showing 3 different orders.

2. We hide all the out of stock products from the website panel but it is still showing in the app.

3.  For partial shipping, suppose there are some products not available and we partially shipped it then we want to give the option for refund and cancellation for only that product.

4. Zip code confirmation is also not in the app.

**Comment by minhcasi** [comment]
Thank you for your quick response: 

1. I see, it could the app issue, i've sent to the team for investigating

2. enable this option - https://tppr.me/EzcYu to fix the stock

3. The refund/cannel option is not available on fluxstore app.

4. Yes, we will investigate it later. 

For the next ticket request, please help us to post to our new ticket support http://support.inspireui.com/ - thank you!

**Comment by rawaniharsh** [comment]
1. After order completed, products delivered to customer house but still refund option is showing in the app, by what the user can easily get the refund. It's dangerous

**Comment by minhcasi** [comment]
@rawaniharsh - there is the limit of the WooCommerce API on the refund feature so that we suggest to keep it hidden at this time - thanks

**Comment by rawaniharsh** [comment]
1. But cancel button is important because user may cancel the product until they received the product after delivery we are not allowing for cancel and refunds. No cancellation policy system. But as per your documentation we can hide both the things (refund and cancel) but we only want to hide the refund button and cancellation is possible before order status changed to processing.

**Comment by rawaniharsh** [comment]
1. Updated the fluxstore app but full title is still not showing in the home page it is cutting to half. Please fix it. Due to this, customer will never get what they want.

2. I hide out of stock product but it is still showing in the app. What's wrong with this?

**Comment by minhcasi** [comment]
Please help to move the new conversation to new Ticket Support http://support.inspireui.com (you could mention on this ticket history) - thank you!
