### ISSUE TITLE
fluxstore woocommerce app issue images and categories part is not seen in app which is design by using fluxbuilder

### ISSUE THREAD

**Issue by alokmalewar** [inspireui/support#4626]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
- [x] first issue
- [x] second issue
- [x] third issue

+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
HI @alokmalewar - could you help to share a detail screenshot issue - thank you!

**Comment by alokmalewar** [comment]
Thanku for your support i have upgrade your source code and now it works fine

**Comment by alokmalewar** [comment]
This are the screenshots 
![Screenshot_2020-08-17-19-19-29-430_com inspireui fluxstore](https://user-images.githubusercontent.com/69632534/90403685-efcfc300-e0be-11ea-9462-c21afd8c7d60.jpg)

**Comment by alokmalewar** [comment]
The icons are not showing on mobile app it is only showing in fluxbuilder.

**Comment by minhcasi** [comment]
@alokmalewar - could you share the config json here so that we could have a quick check - thank you!

**Comment by alokmalewar** [comment]
ok this is the config file
[config_en.zip](https://github.com/inspireui/support/files/5088992/config_en.zip)

**Comment by vumanhsn97** [comment]
@alokmalewar 
Try to replace this:
- folder modules: 
[modules.zip](https://github.com/inspireui/support/files/5094858/modules.zip)
- file lib/tabbar.dart
[tabbar.dart.zip](https://github.com/inspireui/support/files/5094862/tabbar.dart.zip)
Thanks!

**Comment by minhcasi** [comment]
@alokmalewar - let us know your checking -thank you!

**Comment by alokmalewar** [comment]
yes checked it is working fine thanks for your time.

**Comment by minhcasi** [comment]
We're glad that it help, please give us some feedback/rating to this page https://codecanyon.net/downloads  if the product is helpful for your business, we are working hard to update more awesome and powerful features on next coming version release. Let us know if you have any feedback. Thank you very much 😊
