### ISSUE TITLE
Store List In multivendor App

### ISSUE THREAD

**Issue by destek-harshadapatil** [inspireui/support#4627]
Hello Team, 
I am facing some issues in Multi vendor application.
Issues : 
1. I have integrated URL , Consumer key & consumer secret as type WCFM in the code but store list is not showing on the page. Attaching the screenshot for the issue.

2. When I create new account and login using the credentials the loader is continuously showing on the screens.

+ Product & version:  Fuxstore Multi vendor app
+ Flutter (or React Native) version:  FluxStore-vendor-1.7.6

submit proof of purchasing the license : Sorry but I am unable to open the link.
Attaching screenshot here.Please give any alternative.

![Screenshot_20200817-124202](https://user-images.githubusercontent.com/62869560/90368333-7cf72580-e087-11ea-96a6-47b6af7128e5.jpg)

![Screenshot from 2020-08-15 11-38-41](https://user-images.githubusercontent.com/62869560/90368463-b039b480-e087-11ea-85a9-d436b3ce002f.png)

Thank you!

**Comment by minhcasi** [comment]
@destek-harshadapatil - please help to try this link - https://docs.google.com/forms/d/e/1FAIpQLScWOjkAJIWJ9rgb9alopfOqLsJrGKbFM5cCYj1JBfLKLsBblQ/viewform - thank you!

**Comment by destek-harshadapatil** [comment]
I have submitted the details.Please check.
Thank you!

**Comment by minhcasi** [comment]
@destek-harshadapatil - could you help to try the latest Fluxstore MV `1.7.7` release to see if it has the same issue?

Also, give a try to test the Integration Issue by using Fluxbuilder app - http://fluxbuilder.com

**Comment by destek-harshadapatil** [comment]
ok, I will do that.
Thank You!

**Comment by minhcasi** [comment]
Let us know if you have any further question, feel free to reopen the ticket if the issue is not fixed - thank you for time!

**Comment by destek-harshadapatil** [comment]
Sure, Thank you!

**Comment by destek-harshadapatil** [comment]
Hello Inspireui/Support,
                 I have updated the code to 1.7.7 as per you given the
solution and the login and sign up is working fine. But when I use the
plugin as "WCFM" the store list is not showing again. And when I change my
backend setup to "dokan" all works fine.
I wanted to use "WCFM" as my type so what should I do? I have integrated
all the plugins as per given in your document.

Please help me with this.

Thanks and Regards,
