### ISSUE TITLE
[MStore] Launching app , automatic updates

### ISSUE THREAD

**Issue by hakihosting** [inspireui/support#463]
Hello , 
Is it possible that when you open the application, when there is a new update of the application that the user is forced to install it?

**Comment by thangvo9x** [comment]
Please provide your purchase code.

**Comment by luyx2412** [comment]
Hi @hakihosting Please merge your ticket to one. And please provide your purchase code.

Thanks

**Comment by hakihosting** [comment]
Ok no problem : Purchase code : ac9d522a-a783-4f9c-a882-7dc694488d5d
