### ISSUE TITLE
Images not displaying when connect to opencart url of us

### ISSUE THREAD

**Issue by muthuarcus97** [inspireui/support#4630]
If I connect using my opencart url images are not displaying in product list .
Screenshot_2020-08-08-14-21-57-325_host exp exponent
Screenshot_2020-08-08-14-22-09-109_host exp exponent
Screenshot_2020-08-08-14-20-27-737_host exp exponent

Give some solutions for that.

**Comment by minhcasi** [comment]
Duplicate of #4556

Hi - i've reopened the ticket 4556, please keep following the comment so that the team could support you
