### ISSUE TITLE
version 17.7 build iOS error - No such module 'OneSignal'

### ISSUE THREAD

**Issue by chichunfung** [inspireui/support#4631]
How to fix OneSignal bug?
can I remove it?

fstore version 17.7
![Screenshot 2020-08-17 at 5 42 45 PM](https://user-images.githubusercontent.com/26058578/90382403-47ffc880-e0b1-11ea-909a-af684464f00f.png)

**Comment by minhcasi** [comment]
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by chichunfung** [comment]
> same error here, how did you resolve it?

I upgraded my cocoapods, and run againg
