### ISSUE TITLE
#4196  white screen after update to 1.7.7

### ISSUE THREAD

**Issue by Shiru-kun** [inspireui/support#4632]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
- [x] first issue
I  pulled to my pc the new version of fluxstore mv, and i fix all conflicts accepting all incoming changes. but now when i build the apk. it shows a white screen, and i cant do anything.. 
+ Product & version:
1.7.7
+ Flutter (or React Native) version: 
1.20
+ Testing Device/Simulator: 
Real device Samsung A01 android 10 
+ Screenshot issues (drag the file to attach here): 

![Screenshot_20200817-123259](https://user-images.githubusercontent.com/54008441/90391235-12e17f00-e08d-11ea-8089-f67fe2bf9a87.jpg)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com **

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
HI, please try to check the app_init.dart and related splashscreen - it could cause by missing conflict.

**Comment by Shiru-kun** [comment]
but i didnt change this file

**Comment by Shiru-kun** [comment]
i solved all conflicts

**Comment by fasttend** [comment]
@Shiru-kun - have you resolved the issue ? Because I have the same issue with fluxstore.

**Comment by Shiru-kun** [comment]
I didnt

**Comment by Shiru-kun** [comment]
@minhcasi can u help me fix this?

**Comment by Shiru-kun** [comment]
![image](https://user-images.githubusercontent.com/54008441/90523698-7e9b1900-e16d-11ea-9b68-b4f4b60482be.png)
and im getting this bug when i try to build in xcode...

**Comment by minhcasi** [comment]
@Shiru-kun - could i check if you have cleaned up the cache - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1 - and try with latest Flutter stable release
```
flutter channel stable
flutter upgrade --force
```

**Comment by Shiru-kun** [comment]
i did that but still

**Comment by Shiru-kun** [comment]
@minhcasi  i cleaned the cache and  updated the pods, but i still get this error.. 
and im still get same issue in android.

**Comment by minhcasi** [comment]
@Shiru-kun - could you give a try with the default fresh download package from fluxstore to see if happened the same? We suspect could be the missing code after you merge with your previous project - thank you!

**Comment by Shiru-kun** [comment]
@minhcasi  i tried it with a fresh download and its working good, but when i added my remote and  pull from it i get the same error... 
even i fixed all conflicts...

**Comment by Shiru-kun** [comment]
![image](https://user-images.githubusercontent.com/54008441/90733743-4579ba80-e2cd-11ea-9a42-533bbe32c687.png)

**Comment by Shiru-kun** [comment]
i see this error in console

**Comment by Shiru-kun** [comment]
![image](https://user-images.githubusercontent.com/54008441/90735777-d781c300-e2cd-11ea-9fca-ae164a9bc02e.png)

**Comment by fasttend** [comment]
@Shiru-kun -
please update const kSplashScreenType = 'animated';

**Comment by Shiru-kun** [comment]
already fixed

**Comment by Shiru-kun** [comment]
but i need one more help 
![image](https://user-images.githubusercontent.com/54008441/90755965-128af300-e2dc-11ea-97bf-9748c64ae886.png)

**Comment by Shiru-kun** [comment]
i already deleted this website

**Comment by Shiru-kun** [comment]
@fasttend  i did something else i erased the method for splashscreen and replaced with a new one.

**Comment by minhcasi** [comment]
@Shiru-kun - you could send the request Purchase Code to support@inspireui.com - we will to help to reset and you could active on new site

**Comment by Shiru-kun** [comment]
@minhcasi check it 
already send it.

**Comment by minhcasi** [comment]
@Shiru-kun - i got the confirm it is working, so should i reset it again? 

<img width="534" alt="Screen Shot 2020-08-24 at 10 47 45" src="https://user-images.githubusercontent.com/1459805/91001888-407f7880-e5f7-11ea-939b-ae4d4ace2c1f.png">

**Comment by Shiru-kun** [comment]
No need to reset again. Its working..
Thank u
