### ISSUE TITLE
Smartchat on Homescreen

### ISSUE THREAD

**Issue by bigjuju4fr** [inspireui/support#4633]
Hello,
i successfully followed your instructions to setting up the configuration for smart chat (i.e Whatsapp, facebook and so on)
Now i want to display the icon for example on the right downside of the home screen.
![smartchat](https://user-images.githubusercontent.com/69798792/90394679-6060ea80-e093-11ea-8167-88e54f943459.png)

Please could you help me how to do that? 
Thank you.

Best regards

**Comment by minhcasi** [comment]
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
@bigjuju4fr - sorry adding new SmartChat on Homepage is not ready support on Fluxstore app, we have tried this feature but it will cause performance issue so that it is not recommend 👍

**Comment by minhcasi** [comment]
Let us know if you have any further questions - thank you!
