### ISSUE TITLE
After Place My Order Shopping cart empty in Webview 

### ISSUE THREAD

**Issue by codex-pro** [inspireui/support#4634]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
- After Place My Order Shopping cart empty in Webview. 
Nothing Happens 

+ Product & version:
+ Flutter (or React Native) version: Updated latest one
+ Testing Device/Simulator: Redmi Note 7
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com ** done

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊
![2error](https://user-images.githubusercontent.com/51110842/90395438-2f43e280-e0b2-11ea-8ad7-3ded5246af86.png)
![1error](https://user-images.githubusercontent.com/51110842/90395442-310da600-e0b2-11ea-978d-86221b682a7c.png)

**Comment by Carlosdmendoza** [comment]
That happened to me and the issue was that I was using a custom plugin for checkout on wordpress side, instead of the woocommerce default one, I disabled the plugin and problem fixed.

**Comment by minhcasi** [comment]
Yes, it only supports the default Payment COD from WooCommerce - thanks

**Comment by codex-pro** [comment]
it was working before after this update its too buggy . also when i disable the plugin i m getting same error

**Comment by codex-pro** [comment]
i m not using woocommerce ....

**Comment by codex-pro** [comment]
I have resolved earlier issue not I m getting new issue ORder history not fetching up 
even in old everion address order details was not visible now this error /bug .kindly resolve it on immediate basis 
![orderhistory](https://user-images.githubusercontent.com/51110842/90512988-9c23af00-e17c-11ea-8731-d145ff98ea97.png)

**Comment by minhcasi** [comment]
@codex-pro - so you are using Opencart or Magento?

**Comment by minhcasi** [comment]
@minhtruong315 - please help to check this opencart issue

**Comment by codex-pro** [comment]
ORder history not fetching up
even in old everion address order details was not visible now this error /bug .kindly resolve it on immediate basis

**Comment by minhtruong315** [comment]
@codex-pro can you send me common folder and admin account to login your website via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/4634

**Comment by minhtruong315** [comment]
@codex-pro please check order history again. I updated mstore extension on your website. it's working now
![Simulator Screen Shot - iPhone 11 - 2020-08-20 at 10 16 07](https://user-images.githubusercontent.com/10402500/90712872-2d566b00-e2ce-11ea-9d99-2bde01540ab1.png)

**Comment by codex-pro** [comment]
@minhtruong315 minhtruong315  yes it working could you send me mstore updated files if i change the theme or fresh installation i ll need it 


ALso when i m changing splash screen it goes white screen

**Comment by codex-pro** [comment]
All issues resolved splash screen also thank you so much ..please add updated mstore plugin here thank you

**Comment by minhtruong315** [comment]
@codex-pro 
[mstore.ocmod.zip](https://github.com/inspireui/support/files/5101735/mstore.ocmod.zip)

**Comment by tskmark** [comment]
Please how did you fix your app returning empty cart after checkout, its very urgent...
