### ISSUE TITLE
Fluxlisting app issues of V 1.4.2 have not been fixed yet on V1.4.3. Please help!! 

### ISSUE THREAD

**Issue by jinaldo** [inspireui/support#4636]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 

Hi, my fluxlisting app v1.4.2 issues were the following.  
https://github.com/inspireui/support/issues/4421
You wrote to me that the issues would be fixed on next version.

But I see there are same issues on v1.4.3 still.
And on V1.4.3 fluxlisting, I can't even login anyway.(facebook, google, email)
Please check it and let me know if the issues had been fixed or still implementing now.

+ Product & version: 1.4.3
+ Flutter (or React Native) version: Flutter
+ Screenshot issues (drag the file to attach here): 

You can see the yellow/black part, and the review rating 5, but in the detail page, you can see "No reviews".

![Screenshot_20200817-165828_20200817_165928759](https://user-images.githubusercontent.com/45912411/90404930-bfcaf480-e0ab-11ea-99cb-dd2ad38c8708.jpg)

Here, you can see 5 marks rating.
![Screenshot_20200817-170120_20200817_171855340 copy](https://user-images.githubusercontent.com/45912411/90406595-13d6d880-e0ae-11ea-8eb6-04929cb0575b.jpg)

But here, there is no review.

![Screenshot_20200817-170125_20200817_170215882](https://user-images.githubusercontent.com/45912411/90404935-c2c5e500-e0ab-11ea-91e7-0ad81d62483b.jpg)
![Screenshot_20200817-170148_20200817_170215974](https://user-images.githubusercontent.com/45912411/90404940-c35e7b80-e0ab-11ea-9e64-4298300e9718.jpg)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com **

https://docs.google.com/forms/d/e/1FAIpQLScWOjkAJIWJ9rgb9alopfOqLsJrGKbFM5cCYj1JBfLKLsBblQ/viewform?usp=mail_form_link

**Comment by minhcasi** [comment]
Thank you for reporting, we will investigate and let you know - very best!

**Comment by jinaldo** [comment]
Hello, When can I receive your help message?
 It has been 7 days since the last message. 
And I have another problem.  How can I change the "rate this app" texts to spanish?
I can't find the file. please check this your doc url. https://docs.inspireui.com/fluxstore/customization/#4-app-rating
I'm looking forward to your reply.

**Comment by jinaldo** [comment]
Second problem, I have faced this problem again. Please check this issue.
https://github.com/inspireui/support/issues/4421#issuecomment-670405322
At that time, the issue was solved by the supporter. But now the issue happened again.

**Comment by minhcasi** [comment]
@jinaldo - could you help to quick check if there is any draft status product belong to `gastronomia` ?

I'm checking other issues and will update you soon - thank you!

**Comment by jinaldo** [comment]
@minhcasi  Hi, where can I check the draft status product?

**Comment by minhcasi** [comment]
@jinaldo - you could go to the Listing from wordpress and filer all the product by `gastronomia` - would you mind to share the admin login to inspireui.team@gmail.com - we will help to have a look on this issue - thanks

**Comment by jinaldo** [comment]
Hello, @minhcasi .  I have faced another issues.
To get all the caegories, I put this code "print(categories)" as you wrote on the fluxstore doc.(https://docs.inspireui.com/static/00a6a356f73b9747bedf3c6cb627f9de/d4033/debug-category.png)
But there are 9 categories on backend, but the api returns only 3 and the counts of items per category are different with actual counts on backend. This makes crazy.  Please help me.  I have sent the login credential for wp backend to your gmail.

**Comment by jinaldo** [comment]
![Screen Shot 2020-08-28 at 6 10 17 PM](https://user-images.githubusercontent.com/45912411/91583544-0d701880-e95a-11ea-80bf-f012a1204987.png)
![Screen Shot 2020-08-28 at 6 08 53 PM](https://user-images.githubusercontent.com/45912411/91583553-119c3600-e95a-11ea-8ca8-50519da592d7.png)

**Comment by minhcasi** [comment]
@jinaldo - thank you for the quick response, i will investigate the root cause and let you know.

Could i know your email address as i could not search your detail email from my inbox?

**Comment by jinaldo** [comment]
Hi, @minhcasi. Thanks for your reply.
My email is joseojeda417@gmail.com

**Comment by minhcasi** [comment]
@jinaldo - pls help to resend again to inspireui.team@gmail.com 

we only got your form request via that email - https://tppr.me/rXlyh

**Comment by jinaldo** [comment]
Hi, @minhcasi .  I resent my mail to inspireui.team@gmail.com now. Please check it and let me know.

**Comment by minhcasi** [comment]
@jinaldo - pls share your email address as I could not search with title 4636 

But there is this email that could be yours? - https://tppr.me/zPOPu

**Comment by jinaldo** [comment]
Hi, @minhcasi.   Sorry for my misunderstanding.  Which email should I send you? my Envato email? or now my GitHub email?

**Comment by jinaldo** [comment]
I just sent the credential for my github mail to inspireui.team@gmail.com.

**Comment by minhcasi** [comment]
@jinaldo - sorry could confirm this is your email jinaldo22xx@hotmail.com? As we have a bunch of email from the inbox but could not search the email relate to this github?

**Comment by jinaldo** [comment]
Hi, @minhcasi. yes, it is my email. jinaldo22XX@hotmail.com.

**Comment by philipvu30** [comment]
Hi jinaldo,

I don't know if you have solved your issues yet. But here are the results after investigation.

1. The yellow part is caused by the small screen’s phone. You can go to this file lib/screens/detail/listing/product_title.dart and remove this font size on line 143.

2. The 5 stars you see on our Listing but there is none review because the reviews are already been deleted and the data for that listing is already messed up when we were testing. So this is not an issue though.

3. For the sign-in issue, please follow this [link](https://www.appdome.com/no-code-mobile-integration-knowledge-base/extracting-a-sha-fingerprint-from-the-google-play-app-signing-certificate/) and get the SHA-1 and SHA-256, after that, replace them in your firebase console then download the latest google-services.json and replace it with the one in your Flutter project.

4. I don’t find any errors related to the category count issue you stated. Did you fix it yourself?

**Comment by jinaldo** [comment]
Hello, @philipvu30.
I couldn't solve the category count issue still.
Now I have new 2 issues.
I.  Google map shows blank page in iOS. But in Android it's okay. 

![Screen Shot 2020-09-16 at 2 29 23 PM](https://user-images.githubusercontent.com/45912411/93331564-28330000-f829-11ea-8e9c-71c9d4ae13a5.png)

2. Some listings don't show the images on their detail pages.
   Let me explain it more clearly.
  For example, When I select the listing "Toby" on search tab category, it goes detail page, and it shows all images exactly.

 
![Screen Shot 2020-09-16 at 2 40 10 PM](https://user-images.githubusercontent.com/45912411/93332807-12bed580-f82b-11ea-8d03-5cbbd9fa3915.png)
![Screen Shot 2020-09-16 at 2 43 31 PM](https://user-images.githubusercontent.com/45912411/93332812-13f00280-f82b-11ea-9847-189cfe144701.png)




  By the way, when I select the listing "Toby" on other pages, like on  home tab page, and it goes detail page and don't show images and shows the erro message on console.
![Screen Shot 2020-09-16 at 2 50 13 PM](https://user-images.githubusercontent.com/45912411/93333744-739add80-f82c-11ea-954a-d05dd47ca25d.png)
![Screen Shot 2020-09-16 at 2 45 52 PM](https://user-images.githubusercontent.com/45912411/93333756-785f9180-f82c-11ea-8130-d8f2c9b803d5.png)

Please help with these issues. Because the client is asking me to fix those issues right now. Thanks in advance.

**Comment by philipvu30** [comment]
Hi,

1. Google map cannot work on iPhone Simulator. Please test it on a real phone.
2. This issue does not happen on our demo. You can try going to this file and replace its content with this [class.api.fields.php.zip](https://github.com/inspireui/support/files/5235913/class.api.fields.php.zip)

![image](https://user-images.githubusercontent.com/54442328/93413416-6f70cd80-f8c9-11ea-9512-e01087345a14.png)

**Comment by jinaldo** [comment]
Hi
1. Google map doen't work on real iPhone devce still.
2. I have replaced the file, but not showing any difference.
Will you check my wp backend?  I suppose it could occur the issues.
I can send the credentials for the wp backend.
Thanks.

**Comment by philipvu30** [comment]
Sure. Please send your config files and your WP credential to this email: toan@inspireui.com.

**Comment by jinaldo** [comment]
Hi, I've just sent the info and files. my mail is jinaldo223@hotmai.com

**Comment by minhcasi** [comment]
Greetings from InspireUI 🎉
To improve user experience during support, we are announcing that a new ticket support system is available on this link https://support.inspireui.com 

Please help to move your next comment on the new support system (you could mention this ticket so that the team could know more about the ticket's history) - thank you for your time!
