### ISSUE TITLE
Splash Screen error

### ISSUE THREAD

**Issue by vuln3r** [inspireui/support#4638]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
- [x] first issue
After app builds, I get this kind of error:
 `[VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: setState() called after dispose(): _FlareLoadingState#593db(lifecycle state: defunct, not mounted)
This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
#0      State.setState.<anonymous closure> (package:flutter/src/widgets/fra<…>
`

- [ ] second issue
- [ ] third issue

+ Product & version: 1.7.7
+ Flutter (or React Native) version:  Flutter
+ Testing Device/Simulator: iPhone Pro Max 13.4 & 13.6
+ Screenshot issues (drag the file to attach here): 
![image](https://user-images.githubusercontent.com/13506241/90438318-0f251b00-e0d4-11ea-93dd-3d041b1d977d.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com **

Did already

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by emad-masood** [comment]
i have same problem exactly

**Comment by minhcasi** [comment]
@dttrung26 - please help to investigate this issue

**Comment by dttrung26** [comment]
Hi @vuln3r , 
could you please fill our form http://verify.inspireui.com/ again and attach your common folder in it for further investigation? 
Best!

**Comment by vuln3r** [comment]
> Hi @vuln3r ,
> could you please fill our form http://verify.inspireui.com/ again and attach your common folder in it for further investigation?
> Best!
> 
> > **[Google Forms - create and analyze surveys, for free.](http://verify.inspireui.com/)**Create a new survey on your own or with others at the same time. Choose from a variety of survey types and analyze results in Google Forms. Free from Google.

Done!

**Comment by codex-pro** [comment]
even i m getting this error after update nothing is working

**Comment by emad-masood** [comment]
Hi
the problem was from config file config_xx.json I suppose every one has same error was manually editing the file for testing use a a demo file or make a new fresh copy from FluxBuilder without any editing  and gave us a feedback please that what i did and is work again

**Comment by dttrung26** [comment]
Hi @vuln3r  and everyone who might get this issue, 
there is a missing config in config_[language].json file in checking splash screen condition. In order to fix this, please download and replace attached below file into your `/lib/` folder. This will disable splashscreen data in config_[language.json file and take the splashscreen data in `kSplashScreen` and `kSplashScreenType` in your `/lib/common/constants/images.dart` to display as default. (so please don't forget to fill out those values when you are using this way)
[issue#4638.zip](https://github.com/inspireui/support/files/5090259/issue.4638.zip)
Please kindly confirm if it works,
Happy coding!

**Comment by emad-masood** [comment]
now is work with my old config  file with no problem

**Comment by dinaramalho** [comment]
> Hi @vuln3r and everyone who might get this issue,
> there is a missing config in config_[language].json file in checking splash screen condition. In order to fix this, please download and replace attached below file into your `/lib/` folder. This will disable splashscreen data in config_[language].json file and take the splashscreen data in `kSplashScreen` and `kSplashScreenType` in your `/lib/common/constants/images.dart` to display as default. (so please don't forget to fill out those values when you are using this way)
> [issue#4638.zip](https://github.com/inspireui/support/files/5090259/issue.4638.zip)
> Please kindly confirm if it works,
> Happy coding!

I had the same problem, replace the file and it already works. Thanks.

**Comment by vuln3r** [comment]
> Hi @vuln3r and everyone who might get this issue,
> there is a missing config in config_[language].json file in checking splash screen condition. In order to fix this, please download and replace attached below file into your `/lib/` folder. This will disable splashscreen data in config_[language].json file and take the splashscreen data in `kSplashScreen` and `kSplashScreenType` in your `/lib/common/constants/images.dart` to display as default. (so please don't forget to fill out those values when you are using this way)
> [issue#4638.zip](https://github.com/inspireui/support/files/5090259/issue.4638.zip)
> Please kindly confirm if it works,
> Happy coding!

Thank you! After replacing the `app_init.dart` works as it should ^^
