### ISSUE TITLE
New app version problem

### ISSUE THREAD

**Issue by Carlosdmendoza** [inspireui/support#4639]
Hi I have updated the app from the Gitlab Repo just to fix an issue with the store list not being displayed following this ticket https://github.com/inspireui/support/issues/4064#issue-650976110 but the problem now is that seems like flutter version has changed or something but is not working for me I am having this error when I try to compile the app 

![image](https://user-images.githubusercontent.com/46724211/90450961-0b7b9f00-e0a8-11ea-93ae-069b31647c79.png)

This is a copy of my pubsec.yaml

name: fluxstore_vendor
description: Mobile commerce app by Flutter

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.7.7+3001

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  inspireui:
    path: ./modules/common_library
  flutter:
    sdk: flutter
  http: 0.12.2
  html_unescape: 1.0.1+3
  provider: 4.3.2
  after_layout: 1.0.7+2
  font_awesome_flutter: 8.8.1
  vector_math: 2.0.8
  carousel_pro: 1.0.0
  flutter_widget_from_html: 0.4.3
  configurable_expansion_tile: 1.0.0
  timeago: 2.0.26
  share: 0.6.4+3
  validate: 1.7.0
  country_pickers: 1.3.0
  shared_preferences: 0.5.8
  firebase_messaging: 6.0.16
  firebase_analytics: 5.0.16
  transparent_image: 1.0.0
  pull_to_refresh: 1.6.1
  localstorage: 3.0.2+5
  notification_permissions: 0.4.7
  flare_splash_screen: 3.0.1
  rate_my_app: 0.7.0
  page_indicator: 0.3.0
  intro_slider: 2.3.1
  url_launcher: 5.5.0
  extended_image: 1.1.0
  firebase_core: 0.4.5
  firebase_auth: 0.16.1
  flutter_webview_plugin: 0.3.11
  connectivity: 0.4.9
  random_string: 2.1.0
  google_maps_flutter: 0.5.30
  cached_network_image: 2.2.0+1
  uuid: 2.2.0
  uni_links: 0.4.0
  flutter_staggered_grid_view: 0.3.2
  auto_size_text: 2.1.0
  flutter_swiper: 1.1.6
  flutter_widgets: 0.1.12
  video_player: 0.10.11+2
  flutter_spinkit: 4.1.2+1
  percent_indicator: 2.1.5
  animated_text_kit: 2.2.0
  wave: 0.0.8
  http_auth: 0.3.0
  firebase_admob: 0.9.3+4
  facebook_audience_network: 0.7.0
  pin_code_fields: 4.0.0
  flutter_facebook_login: 3.0.0
  webview_flutter: 0.3.22+1
  rubber: 0.4.0
  flutter_localizations:
    sdk: flutter
  custom_splash: 0.0.2
  apple_sign_in: 0.1.0
  google_sign_in: 4.5.1
  google_fonts: 1.1.0
  flutter_statusbarcolor: 0.2.3
  app_settings: 4.0.2
  animated_splash: 1.0.0
  firebase_database: 3.1.6
  event_bus: 1.1.1
  cloud_firestore: 0.13.7
  firestore_ui: 1.10.0
  image_picker: 0.6.7+4
  country_code_picker: 1.4.0
  flutter_typeahead: 1.8.7
  flash: 1.3.1
  location: 3.0.2
  liquid_swipe: 1.5.0
  sticky_headers: 0.1.8+1
  onesignal_flutter: 2.6.0
  zoom_widget: 0.1.3
  awesome_card: 1.1.0
  flutter_html: 1.0.2
  universal_platform: ^0.1.3

dependency_overrides:
  flutter_svg: 0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: 0.7.5
  pedantic: 1.8.0+1 # Analysis
  flutter_driver:
    sdk: flutter
  mockito: ^4.1.1 # Testing

# Run this script to generate the app icon: flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - lib/config/
    - lib/config/states/
    - lib/config/stories/
    - assets/icons/categories/
    - assets/icons/tabs/
    - assets/icons/profile/
    - assets/icons/payment/
    - assets/images/
    - assets/images/country/
    - assets/images/favicon/
    - assets/html/
    - assets/images/background/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
flutter_intl:
  enabled: true

And this are the results I am getting when running flutter doctor any ideas?

Downloading android-arm-profile/windows-x64 tools...                2.2s
Downloading android-arm-release/windows-x64 tools...                1.1s
Downloading android-arm64-profile/windows-x64 tools...              1.4s
Downloading android-arm64-release/windows-x64 tools...              1.2s
Downloading android-x64-profile/windows-x64 tools...                1.6s
Downloading android-x64-release/windows-x64 tools...                1.2s
[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [VersiÃ³n 10.0.18363.1016], locale es-US)
    • Flutter version 1.17.5 at C:\Users\HP Pavilion\Desktop\David\flutter_windows_1.17.5-stable\flutter
    • Framework revision 8af6b2f038 (7 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:/Users/HP Pavilion/AppData/Local/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:/Users/HP Pavilion/AppData/Local/Android/Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
Process finished with exit code 0

I am using the Multivendor app that I have purchased about two months ago and since then I have tried everything still haven't make it work as it's supposed with three different versions is there any way you can have someone to help me through skype? I will really appreciate it.

**Comment by Carlosdmendoza** [comment]
Update on this after four hours of different trials manage to create an apk sample for it, but I am still having 2 problems with it it's like in every update one bug is fix but some others show up

Problem 1: On vendors store just 10 products per store are displaying I am not sure why. 

Problem 2: All the stores are showing up now at least but the search bar in stores pages is not working it just keeps loading and loading.

I haven't change any of the code pertaining to that area so it's basically the same code you have on gitlab repo can you help me with this?

**Comment by minhcasi** [comment]
@Carlosdmendoza - could you help to give a try to test the integration with Fluxbuilder app - http://fluxbuilder.com/ and share us some current screenshot issues - thank you!

**Comment by Carlosdmendoza** [comment]
Hi @minhcasi  actually it did work as I stated thank you for your quick response, just those minor bugs I told you about.

**Comment by Carlosdmendoza** [comment]
![image](https://user-images.githubusercontent.com/46724211/90466634-87d5a880-e0cf-11ea-8a93-6f4d07f91e01.png)


By the way here is the screenshot of the integration.

**Comment by kenngigz** [comment]
![image](https://user-images.githubusercontent.com/57593885/90511799-b8682180-e165-11ea-8a2d-1291419dc9c3.png)

updated to 1.7,7 and having this issue. Do you have any solution?

**Comment by Carlosdmendoza** [comment]
@kenngigz  what I did regarding that was to lower the flutter_svg version to 0.17.0 but I am having trouble on building the apk because when it's completed there is an issue with the menu bar at the bottom and also the vendor stores are only showning 10 products each and the store search bear does not work. I am hoping they can solve that.

**Comment by kenngigz** [comment]
Thank you.

**Comment by minhcasi** [comment]
@Carlosdmendoza @kenngigz 

please make sure to use the flutter stable channel `1.20.x` by running

```
flutter channel stable
flutter upgrade --force
```

**Comment by Carlosdmendoza** [comment]
@minhcasi that allowed me to buld the app thank you, but as I stated I am still having the two problems I told you about yesterday any suggestions for that? 

1. Problem 1: On vendors store just 10 products per store are displaying I am not sure why.

2. Problem 2: All the stores are showing up now at least but the search bar in stores pages is not working it just keeps loading and loading.

I haven't change any of the code pertaining to that area so it's basically the same code you have on gitlab repo can you help me with this?

**Comment by minhcasi** [comment]
@Carlosdmendoza - you could help to test the latest fluxbuilder - https://github.com/inspireui/fluxbuilder/releases/tag/v1.0.8 and also Fluxstore 1.7.7 so see if it have the same issues?

**Comment by Carlosdmendoza** [comment]
Same issue in new fluxbuilder 
![image](https://user-images.githubusercontent.com/46724211/90782644-566e0000-e2bc-11ea-9750-0fa2f9ab658e.png)

That is also happening when I build the app I do not thing fluxbuilder has anything to do with it. However I tried it as you say same result..

**Comment by Carlosdmendoza** [comment]
Once again this are my problems
Problem 1: On vendors store just 10 products per store are displaying I am not sure why.

Problem 2: All the stores are showing up now at least but the search bar in stores pages is not working it just keeps loading and loading.

I haven't change any of the code pertaining to that area so it's basically the same code you have on gitlab repo can you help me with this?

**Comment by minhcasi** [comment]
We have fixed this issue on latest git.

@vumanhsn97 - please suggest the Patching file for this issues

**Comment by Carlosdmendoza** [comment]
@minhcasi @vumanhsn97  I would really appreciate it

**Comment by minhcasi** [comment]
@Carlosdmendoza - we are working on the issue and will update you soon, sorry for some delay as the team does not work over the weekend - thank you!

**Comment by Carlosdmendoza** [comment]
Oh alright, thank you

**Comment by vumanhsn97** [comment]
@Carlosdmendoza 
Problem 1: Can you send your server config (config.dart) to inspireui.team@gmail.com? 
Problem 1: Try to replace this file in lib/vendor/store/store_screen.dart: 
[store_screen.dart.zip](https://github.com/inspireui/support/files/5116387/store_screen.dart.zip)

**Comment by Carlosdmendoza** [comment]
Alright, I just send it at you let me know if you got it, I will try with the file you send at me and let you know.

**Comment by vumanhsn97** [comment]
@Carlosdmendoza 
Please check attachment in your email
Thanks!

**Comment by Carlosdmendoza** [comment]
I am trying to debug some minor problems on the flutter installation right now I'll keep you informed how that goes.

**Comment by Carlosdmendoza** [comment]
By the way were can I change the default language the app has?

**Comment by Carlosdmendoza** [comment]
May I ask you if in this image located in general.dart that Api key is that for the google map integration? 
![image](https://user-images.githubusercontent.com/46724211/91524536-b2d4af00-e8bc-11ea-84f5-5fe0ec7a786f.png)

**Comment by Carlosdmendoza** [comment]
I also have another question how can I add a share button to a vendor store?

**Comment by Carlosdmendoza** [comment]
I am glad to inform that the vendors store are working now, as well as the vendors list, there is a bug when you buy more than one product from a specific vendor it shows the same vendor's shipping methods twice any idea on how to fix that? 

![WhatsApp Image 2020-08-28 at 6 37 09 PM (1)](https://user-images.githubusercontent.com/46724211/91624535-27abf580-e95e-11ea-8fbf-8017230fc37f.jpeg)

**Comment by Carlosdmendoza** [comment]
The third small detail that I have found is that when a vendor publishes a product from the app it uploads it as a draft and we have to update it manually from the website for it to change as published. Do you have any solution for it to be published automatically?

**Comment by Carlosdmendoza** [comment]
Regarding the 2nd problem I think the problem might be something aroung this part of the code I've found it in another ticket 
![image](https://user-images.githubusercontent.com/46724211/91644870-6775ea00-e9fd-11ea-8175-7db248082be2.png)

Where the "For" validation is made for each Product (Product) I think it should only load the vendor's shipping method once for all the products not once for every product you know what I mean?

**Comment by Carlosdmendoza** [comment]
I am also following a video integration here when we are speaking android scheme and host what do I put there the host name for my website store? **
![image](https://user-images.githubusercontent.com/46724211/91647792-1a554080-ea1c-11ea-991a-d52596336fed.png) Or I can setup a variable according to what I want?

**

**Comment by vumanhsn97** [comment]
@Carlosdmendoza 
- google map: follow this document https://docs.inspireui.com/fluxstore/google-map/
- shipping: try with solution above or waiting for next release
- create product with publish status: in lib/models/product/product_model.dart add this line: https://tppr.me/dGIO6

**Comment by Carlosdmendoza** [comment]
@vumanhsn97  I appreviate your response into this about the shipping I have checked the solution above unfortunately it didn't worked since is still loading shipping methods for ever product a vendor has.

The google map integration worked fine thank you for your help regarding that.

I haven't tried yet the third solution but it seems promising I will let you know how that goes. 

Let me ask you how about the question if you think if there is a way to add a share button to a vendor store page so they can share it in social media for example and that when an user clicks on it it opens up directly that store in the app I know that is extra customization you are not suppose to do but if you could give me an idea or a code example I might figure it out.

Thanks again for all your help in this

**Comment by vumanhsn97** [comment]
@Carlosdmendoza 
Try to use this widget: https://pub.dev/packages/uni_links

**Comment by Carlosdmendoza** [comment]
Great thank you I will let you know how everything goes
