### ISSUE TITLE
[MStore] Many issues

### ISSUE THREAD

**Issue by hakihosting** [inspireui/support#464]
Hello 

It's possible to have a modern layout like this ? 
![WhatsApp Image 2019-03-31 at 21 41 09](https://user-images.githubusercontent.com/47614045/55294080-db255900-53fd-11e9-938d-5e95cdcc0bd7.jpeg)

**Comment by luyx2412** [comment]
HI @hakihosting Yeah you can edit the app look like the photo.

Thanks

**Comment by hakihosting** [comment]
can you give me some more informations how to modify the template ?

**Comment by hakihosting** [comment]
or it's possible with the new version to have a new layout ?

**Comment by luyx2412** [comment]
HI @hakihosting Sorry we will not support new layout in next version, I could not give you the detail about it. Please read the code and document to understand how the project work https://docs.mstore.io/

Thanks

**Comment by hakihosting** [comment]
ok i think it must be a good point for the project

**Comment by hakihosting** [comment]
You would like i merge the issue ok : 
Purchase code : ac9d522a-a783-4f9c-a882-7dc694488d5d


Product Variation stock quantity error : 

Hello there is not syncing stock with the woocomerce quantity :
i share you a video : https://streamable.com/28x6t
on the website there is out of stock but in the app you can order it.
How to resolve that.

Hello is not the product , but the variation of the product !


----------------------------------------------------------------------------
Facebook error implementation  IOS 
![image](https://user-images.githubusercontent.com/47614045/55376797-46604f80-5512-11e9-961e-f9131e63e9ed.png)

---------------------------------------------------------------------------------
Launching app , automatic updates
How to allow users to check for the latest app version from inside the app?

**Comment by luyx2412** [comment]
HI @hakihosting Sorry about reply late. Are you use the debug tool to check the issue?

Thanks

**Comment by hakihosting** [comment]
Yes

**Comment by luyx2412** [comment]
Hi @hakihosting So can you take me the screenshot about your response api when login with facebook and products.

Thanks

**Comment by hakihosting** [comment]
For the product variations , when i click for exemple : Large i see not api response

**Comment by hakihosting** [comment]
I would like to deploy the new version of the app : 
Apple store send me this 

Missing Purpose String in Info.plist File - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSLocationAlwaysUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data will be required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs

**Comment by luyx2412** [comment]
Hi @hakihosting 
- Please provide the screenshot to understand easier your issue.
- Follow the document new react-native version, please open `NSLocationAlwaysUsageDescription ` look like the document. 

P/S: The library did not related MStore app, but follow it to fix new version react-native.

Thanks

**Comment by hakihosting** [comment]
look : https://streamable.com/28x6t

**Comment by hakihosting** [comment]
which document ?

**Comment by luyx2412** [comment]
HI @hakihosting Currently we did not support this feature, you can add this feature from response api when selected variant.

Thanks

**Comment by hakihosting** [comment]
Ok so you stock quantity is only for simple product ?

**Comment by luyx2412** [comment]
Hi @hakihosting Thanks for your feedback, let me note and will improve in next version.

Thanks

**Comment by hakihosting** [comment]
Ok thanks  I have found another problem : when i insert a code promo in lower case it works but if y insert in Upercase : CODE promo is invalid 
How to fix that : if the user type Uper or lowercase

**Comment by luyx2412** [comment]
HI @hakihosting You can edit in input function look like the image. Always upper case when change text.
![image](https://user-images.githubusercontent.com/8909619/55926861-2bda5480-5c3d-11e9-8624-ee9af9eb179b.png)

Thanks
