### ISSUE TITLE
Integrated with payment gateway

### ISSUE THREAD

**Issue by twt93** [inspireui/support#4642]
Hello.. canyou help me integrated my fluxstore with my payment gateway midtrans??

**Comment by minhcasi** [comment]
@twt93 - please give a try with this guide - https://docs.inspireui.com/fluxstore/multi-payment/ thank you!

**Comment by djks74** [comment]
Yes, we need it too,
this is an example here https://github.com/apinprastya/flutrans

hope inspireui can integrate this.  Thanks.

**Comment by minhcasi** [comment]
@twt93 @djks74 - please try with the WebView solution in the meantime

We will move this feature request to the team Backlog for further investigating 👍

**Comment by minhcasi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Woo: midtrans payment integration](https://trello.com/c/RKwlPLSV/69-woo-midtrans-payment-integration)
