### ISSUE TITLE
Google play store Error to target atleast api level 29

### ISSUE THREAD

**Issue by vsifiwe** [inspireui/support#4643]
Hello

**_Step 1 (require): describe detail issues & screenshots_**

I setup everything on Mstore-MV and built an apk for distribution. 
When I was uploading it on play console I met the following error

`Your app currently targets API level 28 and must target at least API level 29 to ensure it is built on the latest APIs optimized for security and performance. Change your app's target API level to at least 29`

How should I proceed?

+ Product & version: Mstore Multi Vendor
+ Flutter (or React Native) version:  React Native version 0.62.2 & Expo version 3.24.0
+ Testing Device/Simulator:  Honor 7c
+ Screenshot issues (drag the file to attach here): 

![12](https://user-images.githubusercontent.com/50745253/90492778-db80da00-e141-11ea-964e-ada636b149ce.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com **

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by vsifiwe** [comment]
After some research I discovered that I should upgrade using `expo upgrade`.

Doing that produced another error pictured below

![WhatsApp Image 2020-08-19 at 11 16 56](https://user-images.githubusercontent.com/50745253/90616537-d5582f80-e20d-11ea-8e6a-9e0570d9d73f.jpeg)

This new error is caused by the react-native-gifted-chat package.

**Comment by luyx2412** [comment]
Hi @vsifiwe You can fork or pull request the library to fix the issues. 

Thanks
