### ISSUE TITLE
Couldn't add purchase code in mstore api

### ISSUE THREAD

**Issue by mkarci26** [inspireui/support#4644]
when I add purchase code in mstore api (wordpress admin), I am getting below error.

_Your code is being used by https://mstore.io

![image](https://user-images.githubusercontent.com/7647242/90508118-ba85ac80-e174-11ea-848e-ef1e6f2e7b25.png)

**Comment by qozia3** [comment]
im having a similar issue. the rest api says im not authenticated.

**Comment by minhcasi** [comment]
@mkarci26 - we have reset the purchase code - could you help to try again - thank you!
