### ISSUE TITLE
Mobile list issue

### ISSUE THREAD

**Issue by surendranekkanti188** [inspireui/support#4646]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
- [ ] Need dropdown mobile list in the app. I'm sharing both my website and Fluxstore app options. 
i'm sharing the link for your reference. ( https://superhumour.com/product/rebel-mobile-case ) please have a look.

+ Product & version:
+ Flutter  version: 1.1.7
+ Testing Device/Simulator: Pixel 3A

![My website view( i need like this)](https://user-images.githubusercontent.com/69853255/90514120-98107680-e115-11ea-9597-2a53eac26dcb.jpeg)

![Fluxstore App View](https://user-images.githubusercontent.com/69853255/90514122-9941a380-e115-11ea-9dc3-e2549b46eff9.png)

**Comment by minhcasi** [comment]
@surendranekkanti188 - you could change that attribute to the `Option` layout

<img width="823" alt="Screen Shot 2020-08-19 at 10 05 24" src="https://user-images.githubusercontent.com/1459805/90587407-81484d80-e203-11ea-9aa1-fc9c70a1ab8f.png">

**Comment by surendranekkanti188** [comment]
> @surendranekkanti188 - you could change that attribute to the `Option` layout
> 
> <img alt="Screen Shot 2020-08-19 at 10 05 24" width="823" src="https://user-images.githubusercontent.com/1459805/90587407-81484d80-e203-11ea-9aa1-fc9c70a1ab8f.png">

By default it is Option itself.    :(

**Comment by minhcasi** [comment]
@surendranekkanti188 - i suspect it could be a bug, let me confirm and check with the team - thank you!

@simonpham

**Comment by simonpham** [comment]
Hi @surendranekkanti188,
I will check this issue and notify you ASAP.
Thank you for using our product.

**Comment by surendranekkanti188** [comment]
Thanks

**Comment by simonpham** [comment]
Hi @surendranekkanti188,

We have checked and confirmed this is not a bug.
You can try to copy your Attribute name from WP-admin and add to the config as below:

For example, your attribute name is `Width`:

![image](https://user-images.githubusercontent.com/8846657/90789661-5b20cb80-e331-11ea-9832-a217cf72683b.png)

You need to copy `Width`, **change it to lowercase** (`width`) and add to `ProductVariantLayout` in the config file as below:

![image](https://user-images.githubusercontent.com/8846657/90789849-928f7800-e331-11ea-9173-a991bd9aa620.png)

Hope this will solve your issue. Good luck!

**Comment by surendranekkanti188** [comment]
Hello waiting for your reply

**Comment by simonpham** [comment]
Hi @surendranekkanti188, please go to https://github.com/inspireui/support/issues/4646 and reply with the attached screenshots.
If you reply by email, we cannot see the attachments. Thank you.

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Comment by surendranekkanti188** [comment]
Please make a video of 1.2. Change the app Bundle ID (package name):2.
Generate APK filewe are unable to pass these steps, please make a video on
Android studio and upload it.

**Comment by simonpham** [comment]
@surendranekkanti188

Thank you for your suggestion. We will check with our team and notify you as soon as possible.
