### ISSUE TITLE
search in wishlist screen

### ISSUE THREAD

**Issue by emad-masood** [inspireui/support#4648]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
- [ ] first issue
- [ ] second issue
- [ ] third issue

+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com **

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

Hi
wishlist screen when you choose search button inside it you can't go out
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-08-18 at 18 02 54](https://user-images.githubusercontent.com/68939548/90530478-9c707a00-e17d-11ea-9d0c-8eedad6f72bf.png)

**Comment by emad-masood** [comment]
that screen i talk about
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-08-18 at 18 09 50](https://user-images.githubusercontent.com/68939548/90530854-0721b580-e17e-11ea-8cb6-21ea93919a16.png)

**Comment by minhcasi** [comment]
@emad-masood - sorry could you explain more detail, we are not sure to get your idea

**Comment by emad-masood** [comment]
![Screen Recording](https://user-images.githubusercontent.com/68939548/90591542-0aec2100-e1ec-11ea-84d9-aa085889a0bd.gif)

**Comment by minhcasi** [comment]
@emad-masood - got your idea - thank you for the video, we will update the back button on this case for the Search Screen

**Comment by simonpham** [comment]
Hi @emad-masood,

Our team has just fixed this issue. We will notify you when the new update is available.

Thank you for your support.

**Comment by minhcasi** [comment]
Greetings from InspireUI 🎉
To improve user experience during support, we are announcing that a new ticket support system is available on this link https://support.inspireui.com 

Please help to move your next comment on the new support system (you could mention this ticket so that the team could know more about the ticket's history) - thank you for your time!
