### ISSUE TITLE
Splashscreen error in android ans ios when i build.

### ISSUE THREAD

**Issue by smark98** [inspireui/support#4649]
My last ticket. (4059)

Hi,

I have a problem with new 1.7.7 version.

When I build I got the following error.

I got error also in android and IOS. (both images attached.)

![Képernyőfotó 2020-08-18 - 17 46 40](https://user-images.githubusercontent.com/37720115/90535128-d724e300-e17a-11ea-8b9a-870bff0b75b1.png)

![Képernyőfotó 2020-08-18 - 17 42 30](https://user-images.githubusercontent.com/37720115/90534654-4948f800-e17a-11ea-87c9-b36fc2efb70f.png)
![Képernyőfotó 2020-08-18 - 17 40 24](https://user-images.githubusercontent.com/37720115/90534663-4c43e880-e17a-11ea-884c-a2059b3747d7.png)

**Comment by dttrung26** [comment]
Hi @smark98 , 
please double-check on this ticket: https://github.com/inspireui/support/issues/4638 and kindly confirm if it works for you.
