### ISSUE TITLE
[MStore] Auth issue

### ISSUE THREAD

**Issue by qbizns** [inspireui/support#465]
- Product: MStore
- Purchased Code: 0aac5945-b67f-4fdc-a207-ba41a2e0c656

I have problem with login and register and facebook-login
i install the app and make all configuration as documentation said on web site and on react-native files every thing work fine except auth

the main function that handle requests "request" return undefined when returning response.json();
so i investigate and try to pop up alert in this function to print just response so i found it return status 503 as you can see in screenshot blow

but when i call this link directly from browser with valid login data it return valid response
http://shyakty.com/api/mstore_user/genrate_auth_cookie/?second=600000000000&username=*****&password=********&insecure=cool

**Screenshots**
![Screenshot_20190401-031320](https://user-images.githubusercontent.com/2733045/55313235-f630b100-546f-11e9-8614-75f2c9aae2a7.png)

so can you guide me why auth not work and i activate json-api and install all plugins and how can i fix this 
thanks

**Comment by luyx2412** [comment]
HI @qbizns can you use the debug tool to investigate this issue https://docs.mstore.io/api-and-project-structure#debug-app-with-reacttotron

Thanks
