### ISSUE TITLE
Failure to find product in your shopping cart

### ISSUE THREAD

**Issue by ornekali** [inspireui/support#4650]
when I continue shopping through the app, it redirects to webviev after the payment screen, and gives the error of not having a product in your shopping cart. can help about this problem?

**Comment by minhcasi** [comment]
@ornekali - could you help to share the screenshot issue - thank you!

**Comment by minhcasi** [comment]
Let us know your updating - thank you!

**Comment by minhcasi** [comment]
move to #4685
