### ISSUE TITLE
Console logs are not displayed

### ISSUE THREAD

**Issue by franklinbinauraldev** [inspireui/support#4651]
Receive a warm greeting

How can I see console.log ('Hello World') as in other **React Native projects**? Install **React Devtools** and it doesn't work, I need to see the logs.

**Comment by franklinbinauraldev** [comment]
**Receive a warm greeting @luyx2412**

I have tried to print the logs, I have also deactivated the option that you mentioned in an issue I do not remember which one.

`useReactotron: false`

When I run the application, I run the following command:

- `react-native start`
- `react-native run-android`
- `react-native log-android`

But it only informs me of the states of the application or in the views where I am.

![Captura de pantalla de 2020-08-19 16-59-46](https://user-images.githubusercontent.com/69120282/90689066-71e5f600-e23d-11ea-9f5e-00bec1e53a11.png)

It is usually consumed from the REST API, and I can't really see the data, this is extremely essential.

Please I need help with this.
I would appreciate it very much.

**Comment by luyx2412** [comment]
Closed! Because no longer response.

P/S: Feel free to reopen or create new issues.
