### ISSUE TITLE
Crash on shipping step in checkout process

### ISSUE THREAD

**Issue by vuln3r** [inspireui/support#4654]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
- [x] first issue
After adding a product and going trough checkout I got a crash on the `Shipping` which says that I don't have full access to the api.

![image](https://user-images.githubusercontent.com/13506241/90561953-c63b9800-e1a1-11ea-9c50-a2d85a443e7a.png)

and here it says that I got full access: 

![image](https://user-images.githubusercontent.com/13506241/90562009-d9e6fe80-e1a1-11ea-9dea-1d42ec0569e6.png)

+ Product & version: 1.7.7
+ Flutter (or React Native) version: Flutter 1.20.1
+ Testing Device/Simulator: Android Emulator API 29

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com **

Already did in my previous ticket 

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by djks74** [comment]
Mine too, 
but since Im using midtrans, the error cannot purchase and said "you cannot continue, its already paid".

I think its because since new mstore api update.

**Comment by minhtruong315** [comment]
@vuln3r can u send me common folder and admin account to login your website via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/4654

**Comment by vuln3r** [comment]
> @vuln3r can u send me common folder and admin account to login your website via email: [truong@inspireui.com](mailto:truong@inspireui.com)
> with subject: #4654

I'll send it to you today

**Comment by minhtruong315** [comment]
<img width="1219" alt="Screen Shot 2020-08-21 at 3 36 06 PM" src="https://user-images.githubusercontent.com/10402500/90870631-1003c880-e3c4-11ea-857f-14d478a4a862.png">
@vuln3r please deactive this plugin and try again

**Comment by vuln3r** [comment]
> <img alt="Screen Shot 2020-08-21 at 3 36 06 PM" width="1219" src="https://user-images.githubusercontent.com/10402500/90870631-1003c880-e3c4-11ea-857f-14d478a4a862.png">
> 
> @vuln3r please deactive this plugin and try again

It works 🎉  even works with my shipping plugin amazing !!! Thank you! 

I didn't check that because everything else works fine in construction mode, so I thought it is something wrong in the app itself.
