### ISSUE TITLE
Webview cannot connect deeplink (Fluxstore MV)

### ISSUE THREAD

**Issue by djks74** [inspireui/support#4656]
Dear Minh,
I think there is permission or intent we need to set on androidmanifest or config? 
Im using midtrans webview, then when we pay using gopay, it connect link to gojek app.

![WhatsApp Image 2020-08-19 at 12 51 46](https://user-images.githubusercontent.com/26361171/90597433-4b16c800-e21b-11ea-9138-6032ca11de84.jpeg)
webview not opening link to Gojek as shown.

it look like security or permission (whitelist)
please help! Thanks.

**Comment by minhcasi** [comment]
@djks74 - pls move your all comment into one open ticket #4655
