### ISSUE TITLE
Shipping method showing double for product/vendors (Fluxstore MV)

### ISSUE THREAD

**Issue by djks74** [inspireui/support#4657]
![WhatsApp Image 2020-08-19 at 13 05 01](https://user-images.githubusercontent.com/26361171/90598152-b7de9200-e21c-11ea-9f99-a76bbc119bda.jpeg)
Its good to have woocommerce shipping add-on is working, but Its displaying double when has 2 vendors/product.

![WhatsApp Image 2020-08-19 at 12 58 34](https://user-images.githubusercontent.com/26361171/90597668-c5dfe300-e21b-11ea-8b2d-383c4bbd1e47.jpeg)

It need to seperate vendor for seperate shipping fee each vendor. but this one shown all in 1 vendor.

could you please help with it? thanks

**Comment by minhcasi** [comment]
@djks74 - pls move your all comment into one open ticket #4655
