### ISSUE TITLE
Updating Application Id results in Crash

### ISSUE THREAD

**Issue by Gag1011** [inspireui/support#4660]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
- [ ] first issue
I have followed the documented steps on https://docs.inspireui.com/fluxstore/delivery-android/ on how to update my application Id without it crashing. My app started crashing as soon as I changed the bundle Id. I have updated the googleservices.json as specified as well. I have tried to run the bash id update script included but can't get it to work. I think I am missing something though.

![Main Manifest](https://user-images.githubusercontent.com/67577702/90602085-75578e00-e1f9-11ea-9608-b1414be3d686.png)
![appbuild gradle](https://user-images.githubusercontent.com/67577702/90602111-82747d00-e1f9-11ea-9f6d-ddc75c4d35f3.png)
![debugmanifest](https://user-images.githubusercontent.com/67577702/90602113-83a5aa00-e1f9-11ea-82e6-569c51a83406.png)
![googleservices](https://user-images.githubusercontent.com/67577702/90602116-843e4080-e1f9-11ea-8318-12d140f631a3.png)
![mainactivity](https://user-images.githubusercontent.com/67577702/90602118-84d6d700-e1f9-11ea-8359-e11b01e760ad.png)
![Profile manifest](https://user-images.githubusercontent.com/67577702/90602120-84d6d700-e1f9-11ea-83a6-2fc0916d9d63.png)

+ Product & version:
FluxStore Pro Multi Vendor 1.7.6 using wcfm
+ Flutter (or React Native) version: 
Flutter (Channel stable, v1.17.3, on Microsoft Windows [Version 10.0.18362.535], locale en-ZA)
+ Testing Device/Simulator: 
 Android Studio (version 4.0)
Simulated Pixel 3 XL API 30 x86_64

+ Screenshot issues 

![Crash](https://user-images.githubusercontent.com/67577702/90602911-c2882f80-e1fa-11ea-9b4a-943866458ead.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com **

Please Please assist. I only have a day or two before deadline!

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@Gag1011 - could you zip and share your android folder here - we will help to check your setting issue - thanks

**Comment by Gag1011** [comment]
[android.zip](https://github.com/inspireui/support/files/5097123/android.zip)
Here as requested is my Zipped android folder

**Comment by minhcasi** [comment]
@Gag1011 - the issues are you have upgrade the build grade that not compatible with the Flutter app, try to use the default one and only change your bundle id name

<img width="1117" alt="Screen Shot 2020-08-20 at 11 52 25" src="https://user-images.githubusercontent.com/1459805/90718246-9f817c80-e2db-11ea-9be5-eadfd0ecbff3.png">
<img width="1109" alt="Screen Shot 2020-08-20 at 11 52 34" src="https://user-images.githubusercontent.com/1459805/90718252-a4463080-e2db-11ea-962d-900ce7dd33ba.png">
<img width="1164" alt="Screen Shot 2020-08-20 at 11 52 55" src="https://user-images.githubusercontent.com/1459805/90718267-b0ca8900-e2db-11ea-8f0f-ace6fd245edd.png">

**Comment by Gag1011** [comment]
I have made the fixes suggested above. and am waiting for the project to build on my emulator. should it be taking such a long time to build?

**Comment by Gag1011** [comment]
The App is still crashing. Please have a look at my updated zipped android folder.
[android.zip](https://github.com/inspireui/support/files/5103672/android.zip)

**Comment by minhcasi** [comment]
@Gag1011 - we are not sure why you need to update these dependecies, pls make sure to use the default one.

<img width="556" alt="Screen Shot 2020-08-21 at 14 24 07" src="https://user-images.githubusercontent.com/1459805/90863924-feb5be80-e3b9-11ea-8da8-d0978e144e4e.png">

Also try to update the default `pubspecs.yaml` from latest release `1.7.7`

**Comment by Gag1011** [comment]
I will try them again. Should I leave my application Id as is or change it back to the original too?

**Comment by minhcasi** [comment]
@Gag1011 - you current android folder seems config correctly, the root cause could be other reasons - please send your whole source code to inspireui.team@gmail.com - we will help to check this issue (make sure to run `flutter clean`)

**Comment by Gag1011** [comment]
Hi there, the zipped source file is too large large to upload here. I have uploaded it to mega. Please follow this link to download it:
https://mega.nz/file/juREAYYC#xbiFjxe0-t6cPGyChzadnIMRbm5uXmLYXR5SijFmqeQ

The app was working with the updated dependencies. It only started crashing when I updated the applicationId as stated above.

**Comment by Gag1011** [comment]
Hey Minh,

 

Here is a link to my source code:

 

https://mega.nz/file/juREAYYC#xbiFjxe0-t6cPGyChzadnIMRbm5uXmLYXR5SijFmqeQ

 

Kind Regards,

Gareth Winchester

**Comment by minhcasi** [comment]
@Gag1011 - pls help to run `flutter clean` delete the `build` folder and send that link to the email inspireui.team@gmail.com 

PLEASE DONT SHARE THE CODE PUBLIC HERE

**Comment by minhcasi** [comment]
@vumanhsn97 - pls help to check the root cause of issue from the source of email (search title 4660)

**Comment by Gag1011** [comment]
I'm so sorry but what do you mean? Search 4660? Where?

**Comment by vumanhsn97** [comment]
@Gag1011 
Please check your email.
Thanks!

**Comment by Gag1011** [comment]
Thank you so much for your help guys. You really are Super! What was the issue if I may ask?

**Comment by vumanhsn97** [comment]
@Gag1011 
Your issue in AndroidManifest.xml and key.properties files

**Comment by minhcasi** [comment]
Let us know if you have any issues - thank you!
