### ISSUE TITLE
Web build is not responsive

### ISSUE THREAD

**Issue by mkarci26** [inspireui/support#4662]
Hi Team,

Created web build, It is not responsive for mobile browser. Can you please check that out, any css needs to be added here?
![image](https://user-images.githubusercontent.com/7647242/90615235-73a5be80-e229-11ea-88cf-1752783901b0.png)

**Comment by minhcasi** [comment]
@mkarci26 - we will notify with the team, did you try to load on real iPhone device for that PWA version?

Please note that the web version is not ready for production as it could cause performance issues - thank you!

**Comment by mkarci26** [comment]
Hi @minhcasi, 
No issues on mobile builds. But web version having problem with responsiveness. We need web version too for fluxstore, otherwise choosing PWA is worthless..

**Comment by mkarci26** [comment]
Any updates on fluxstore web version?

**Comment by minhcasi** [comment]
@mkarci26 - it will be available in next 1.7.8

@tgloc96 - please provide the patching files when this issue is fixed

**Comment by mkarci26** [comment]
thanks, will check and let you know

**Comment by mkarci26** [comment]
@tgloc96 

Thanks for your support. This works fine. Great work.

**Comment by tgloc96** [comment]
Thank you for choosing our product ^^.
