### ISSUE TITLE
white screen on wordpress admin panel

### ISSUE THREAD

**Issue by myu98198** [inspireui/support#4664]
I installed all required plugins, when I go to mstore-api plugin it returns the white screen, please help.

**Comment by minhcasi** [comment]
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by myu98198** [comment]
i also have a small issue with flux builder, my demo site was on my subdomain and I used it and activate it with purchase code now I'm using my final domain then it gives me validation error that this purchase code is used in my subdomain, what should i do now?

**Comment by minhcasi** [comment]
@myu98198 - we have reset the license key so that you could activate it on the new production site now, please make sure to update to latest mstore-api plugin - thank you!

**Comment by myu98198** [comment]
okay thank you 
and what about wordpress plugin issue ?

**Comment by myu98198** [comment]
What about wordpress plugin issue ?

**Comment by minhcasi** [comment]
@myu98198 - could you help to enable the debug mode from wp-config.php and share the screenshots issue on your wordpress site so that i could check with the backend team?

**Comment by myu98198** [comment]
I try debug mode on but still no warning no error message just blank white
screen

**Comment by minhtruong315** [comment]
@myu98198 can u send me admin account to login your website via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/4664

**Comment by minhtruong315** [comment]
Hi @myu98198 I see it's showing. what is your issue?
<img width="1625" alt="Screen Shot 2020-08-25 at 9 59 52 PM" src="https://user-images.githubusercontent.com/10402500/91190960-62bfe600-e71e-11ea-9929-dca2ab27f0a6.png">

**Comment by myu98198** [comment]
it is working now previously it was not working
now 1 more issue is there
website cart page and application cart page is not synchronized if I put
some products in the website's cart it won't show in the application's cart
likewise cart items from application won't show in the website's cart page.
how to fix that?

**Comment by minhtruong315** [comment]
@myu98198 Fluxstore 1.7.7 doesn't support sync cart with website. we're working on that. it'll be available in next release.

**Comment by minhcasi** [comment]
Greetings from InspireUI 🎉
To improve user experience during support, we are announcing that a new ticket support system is available on this link https://support.inspireui.com 

Please help to move your next comment on the new support system (you could mention this ticket so that the team could know more about the ticket's history) - thank you for your time!
