### ISSUE TITLE
checkout page customize

### ISSUE THREAD

**Issue by bananweb** [inspireui/support#4666]
hi 
- we need to customize the native checkout page, we need to hide some unnecesary fields to simplize checkout process, 
which files we have to customize ?
- there is limit for total price in cart, it should't be less than 100, we need to edit it, how ?

**Comment by minhcasi** [comment]
"there is limit for total price in cart, it should't be less than 100, we need to edit it, how " - could you share this screenshot issues? 

Feel free to customize to add any native checkout payment as you have got the full source to customization 👍

**Comment by bananweb** [comment]
![image](https://user-images.githubusercontent.com/48653804/90641719-d7cc8080-e231-11ea-9a5d-0993f32b5193.png)

**Comment by bananweb** [comment]
also we tried to get price value after price number as the right direction in arabic language but we couldn't. 
@minhcasi
