### ISSUE TITLE
flutter update issue

### ISSUE THREAD

**Issue by nomicool** [inspireui/support#4667]
updating flutter causes errors on projects of fluxstore when ever I execute new project without editing it takes huge to build apk and after edting it shows error many folders under lib importing dependencies did not resolved now I have also tried previous flutter sdk version what to do now please
![90487508-6be1ff00-e0ef-11ea-8448-415d02c1b8c4](https://user-images.githubusercontent.com/25566185/90631704-0a498f80-e1d8-11ea-8919-3b9016f9e3db.png)
![Screenshot (8)](https://user-images.githubusercontent.com/25566185/90631731-13d2f780-e1d8-11ea-8e0d-c12ca95adb92.png)
now last screenshot app after configuration makes apk but blank on emulator nothing shows without configuration it shows same

**Comment by nomicool** [comment]
![Screenshot (9)](https://user-images.githubusercontent.com/25566185/90631801-39f89780-e1d8-11ea-98f2-5dc6d150d985.png)
i have upsed updated flutter sdk and plugins vs code everything it samples app working fine but fluxstore causing issue

**Comment by minhcasi** [comment]
@nomicool - is it happen on the default Fluxstore source or your customization project?

Also, try to send us your current `flutter doctor`

**Comment by nomicool** [comment]
this error happened after configuring the package name changing API keys in config works fine after changing the package name building APK and running app takes huge time also on this update flutter running building apk take s much time and I am also attaching doctor screenshot and moreover I should tell your previous version 1.7.6 all old edited apps dependencies does not fetch it shows error under all main folder of lib/ and the new one dependencies overridden too.
![Screenshot (11)](https://user-images.githubusercontent.com/25566185/90661581-3aa32500-e1fc-11ea-8bf0-e46548024584.png)

**Comment by nomicool** [comment]
Hello please try to respond quickly

**Comment by nomicool** [comment]
dependencies overridden was added already in packages but still facing the issue is m stuck all of this issue
![Screenshot (1)](https://user-images.githubusercontent.com/25566185/90803848-ce770d00-e332-11ea-802c-09608f1ddadb.png)
 please help

**Comment by minhcasi** [comment]
@nomicool - pls try following solutions

- try to move the project to C: hard drive to prevent the permission issues on your window.
- try to clean up the cache by running `flutter clean` or follow this guide - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1
- try to run Test Drive to see if there is any issue - https://flutter.dev/docs/get-started/test-drive

Please try your best, if you could not use the app after these checking, we could help to process the refund as you could not on your Window - thank you for your time!

**Comment by minhcasi** [comment]
@simonpham - please help to investigate the white issue

**Comment by nomicool** [comment]
Please try to find out today

**Comment by simonpham** [comment]
Hi @nomicool,
About your "screen clean white" problem, you can refer to this issue:
https://github.com/inspireui/support/issues/4711#issuecomment-678886785

> You can try to replace `PNG` with `png` in `kSplashScreen` config
> Example:
> replace `const kSplashScreen = "assets/images/splashscreen.PNG"`
> with `const kSplashScreen = "assets/images/splashscreen.png"`

**Comment by nomicool** [comment]
its already png 
![Screenshot (13)](https://user-images.githubusercontent.com/25566185/91029409-26a25d80-e618-11ea-9875-1b4d1f709f36.png)

**Comment by nomicool** [comment]
the app is completly white its not the single white its not working

**Comment by nomicool** [comment]
try to fix my issue today I can wait a day long for a single answer, please

**Comment by simonpham** [comment]
Hi @nomicool,
You need to set const kSplashScreenType = "static"; to use static image as splash screen.
Hope this will solve your issue. Good luck!

**Comment by nomicool** [comment]
@simonpham look dear tea. I have explained to you several times again your solution did not work again. I continuously explain that after this flutter update whole ap is blank white not the splash screen issue my whole app is blank it's not working after customization before customization it's working fine

**Comment by nomicool** [comment]
NOw the whole app is taking 5 to 6 seconds to get rid of the white screen please now let me know about this its taking around 5 to 6 seconds to show the screen after white

**Comment by nomicool** [comment]
the app takes 15 seconds after the white screen. and 2nd issue I have multi-vendor flux store version 1.7.6 in this I just needs to change currency I  have done change test debug work fine but build singed apk it shows this error screenshot below please let me know both
![Screenshot (26)](https://user-images.githubusercontent.com/25566185/91200094-24272d00-e718-11ea-8f85-75230755c796.png)

**Comment by simonpham** [comment]
Hi @nomicool,

About the splash screen duration, we have a delay of 2.5 seconds (2500 milliseconds) to show the splashscreen.

You can change it by set `duration: 0` in `lib/app_init.dart` like below:

![image](https://user-images.githubusercontent.com/8846657/91200086-e41c7600-e728-11ea-8748-36fe6e175437.png)

Thank you for using out product.

**Comment by simonpham** [comment]
Hi @nomicool,
About the build problem, please try to remove any special characters and spaces in the path.

![image](https://user-images.githubusercontent.com/8846657/91200724-b5eb6600-e729-11ea-9808-429496ed41ef.png)
For example: change it to `E:\Projects\dugbana_marketafrique\flutter`

Hope this will solve your issue. Good luck!

**Comment by nomicool** [comment]
removing space and special characters does not work
![Screenshot (29)](https://user-images.githubusercontent.com/25566185/91221309-ea195380-e736-11ea-9706-9d55307b7109.png)

**Comment by simonpham** [comment]
@nomicool
Please try to run `flutter channel beta && flutter upgrade -- force && flutter clean`
then build again.
Hope this will solve your issue. Good luck!

**Comment by nomicool** [comment]
now faced this 
![Screenshot (30)](https://user-images.githubusercontent.com/25566185/91288086-00142c00-e7aa-11ea-93f2-6f732a844084.png)

**Comment by nomicool** [comment]
![Screenshot (32)](https://user-images.githubusercontent.com/25566185/91290066-99444200-e7ac-11ea-84c5-d791d52f07f0.png)
Switching back to stable cause me this error

**Comment by nomicool** [comment]
your solution did not worked with 1.7.6 preious multivendor version please

**Comment by nomicool** [comment]
Please respond me the issue???????????

**Comment by simonpham** [comment]
> removing space and special characters does not work
> ![Screenshot (29)](https://user-images.githubusercontent.com/25566185/91221309-ea195380-e736-11ea-9706-9d55307b7109.png)

Hi @nomicool , please use our latest version 1.7.7 which already fixed this build issue (`codepoint 58848 not found in font`).

**Comment by nomicool** [comment]
But its already on store i just need to made a single i can't make it from scratch again please provide any solution please with this version

**Comment by simonpham** [comment]
@nomicool, you can try to replace your current Flutter version (1.20.2) with [Flutter version 1.17.5] (https://storage.googleapis.com/flutter_infra/releases/stable/windows/flutter_windows_1.17.5-stable.zip).
It doesn't have `codepoint 58848 not found in font` issue when building release apk.

I suggest to run `flutter build appbundle` instead of `flutter build apk`.

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
