### ISSUE TITLE
Regarding Product Description

### ISSUE THREAD

**Issue by GNAG1993** [inspireui/support#4668]
Hello,
 We are having Custom Fields added to Product Description, but they are not showing up in the app description.
Any reference or guidance regarding that.

For verification you can go with my other tickets: https://github.com/inspireui/support/issues/4469

**Comment by minhcasi** [comment]
@GNAG1993 - pls try your best with this customization and using Debug tool - https://flutter.dev/docs/testing/debugging - you could try to upgrade your skills from the flutter codelab to have more knowledge to custom the Flutter app

Using network tools to check the JSON api is also good solution to start your customized

Let us know if you have any questions!

**Comment by GNAG1993** [comment]
You didn't get my point and just closed the ticket. 
I meant i have added custom fields in my website like product size, color etc. Not as attributes but as fields. They are not showing up in Fluxstore MV app.
