### ISSUE TITLE
Unable to setup WordPress website with Fluxstore Multi Vendor Flutter App and FluxBuilder 

### ISSUE THREAD

**Issue by quanticteq01** [inspireui/support#4669]
Hello I am trying to setup my WCFM based wordpress website on Fluxstore Multi Vendor Flutter App and FluxBuilder 

I have followed all the valid steps mentioned on  https://docs.inspireui.com/fluxstore/multi-vendor/  to configure my WordPress setup

**Issue with Flux Building** 
after installing all require Wordpress plugin for WCFM and Fluxstore multivendor, when I try to connect my store on Fluxbuild i am getting below errors 

![image](https://user-images.githubusercontent.com/69906951/90642105-9b0f8200-e24f-11ea-8a7c-a96015c761a9.png)

1. Regenerated Thumbnail: To removed Regenarated Thumbnail issues, I/ve already regenerated thumbnails 3 times and confirmed in Wordpress admin still getting error.

2. CS & CK  authorisation and validation: to resolve this issue  I checked and rechecked my REST API keys multiple times. I've also gone through your common encounter issues and updated my htaccess file with " RewriteCond %{HTTP:Authorization} ^(.) RewriteRule ^(.) - [E=HTTP_AUTHORIZATION:%1]"  

**Issue with Fluxstore Multi Vendor Flutter App**
While building app i am getting 401 authorisation error : my products are not getting loaded 
![image](https://user-images.githubusercontent.com/69906951/90646348-bf219200-e254-11ea-8813-bc542b95f4dd.png)

Let me know how i can fix this issues.

**Comment by minhcasi** [comment]
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
This issue is caused by Rest API is not working correctly. Please help to check the following solutions from the server-side:

- Check the Rest API via Postman app, pls refer https://github.com/woocommerce/woocommerce/wiki/Getting-started-with-the-REST-API
- Resolve 401 Unauthorized issues by using this guide - https://github.com/woocommerce/woocommerce/wiki/Getting-started-with-the-REST-API#401-unauthorized
- Try some solutions on this guide - https://robotninja.com/blog/fix-common-woocommerce-rest-api-issues/

**Comment by quanticteq01** [comment]
From last 3 days before submitting support ticket I have already tried all the available solutions for 401.

I have even contacted my hosting server support to find any resolution since i am using a VPS server they are claiming everything is fine at server side.

I have followed followed all step by step instruction to install all required plugins to run fluxstore for WCFM. but i am getting above mentioned issue connecting fluxbilder and flutter app.

I have filled the google form for license validation from the provided link also sent any email day ago on support@inspireui.com which content my WordPress website admin login details.

Request you to take a look

**Comment by minhcasi** [comment]
@quanticteq01 - please try your best as it is about the REST API issue on your Website server

- you could try to reinstall other Wordpress instance to see if can be fixed - ref: https://github.com/inspireui/support/issues/4432
- try to change to there PHP versions to see if can be fixed

**Comment by vumanhsn97** [comment]
@quanticteq01 
Please download this version: https://github.com/inspireui/fluxbuilder/releases/tag/v1.0.8
Thanks!

**Comment by quanticteq01** [comment]
Hello @vumanhsn97 new version help resolved getting started with MV app on fluxbuilder.

All of my issues related to app initialisation has been resolved, thanks for the prompt support.
