### ISSUE TITLE
[ListApp] Can`t launch the app

### ISSUE THREAD

**Issue by Pars1vaLl** [inspireui/support#467]
**Mandatory Info (please complete the following information):**
 - Product: ListApp
 - Your Purchased Code: 85059e37-2ddd-478d-899b....

Hi,
Guys, are you going to help me? Here is my question: https://github.com/inspireui/support/issues/440

Waiting about a week.

Thanks

**Comment by thangvo9x** [comment]
https://github.com/inspireui/support/issues/440
