### ISSUE TITLE
Layout and product catalog fluxstore

### ISSUE THREAD

**Issue by skalumek** [inspireui/support#4672]
![IMG_20200819_200916](https://user-images.githubusercontent.com/69422644/90668081-2db41f00-e258-11ea-9311-8318970b1888.jpg)

How Can I achieve a layout and a product catalog similar to the attached image?

**Comment by skalumek** [comment]
Hi, so what is the solution?

**Comment by minhcasi** [comment]
@skalumek - do you mean the product detail gallery image or the product list on Homepage ? 

This is interested UI feature that we could help to upgrade on next release - thank you!

**Comment by minhcasi** [comment]
in the meantime, you could try this lib - https://pub.dev/packages/galleryimage

**Comment by skalumek** [comment]
I want that on home page.

**Comment by skalumek** [comment]
Hi, thanks.
Is it possible to add an extra Field on orders to show who ordered an item?

Secondly, Address Country is defaulting to Vietnam, where do I change it?
Third, how to I get the product image URL?

**Comment by skalumek** [comment]
Auto option is not working. Share full code.

**Comment by minhcasi** [comment]
@skalumek - could you share some screenshot issue so that we could understand the issues more?

**Comment by skalumek** [comment]
Am using this layout i wanted the images on the header(slider) to auto slide.
![Capture](https://user-images.githubusercontent.com/69422644/91013124-e5965300-e5ef-11ea-8825-19ce7ce9a7a0.PNG)

**Comment by minhcasi** [comment]
Could you share your config json? It is possible to enable the `autoPlay: true` to trigger the auto slide feature

<img width="661" alt="Screen Shot 2020-08-25 at 09 51 08" src="https://user-images.githubusercontent.com/1459805/91117311-818b9180-e6b8-11ea-91cb-b0d0f9cb6c2a.png">

**Comment by minhcasi** [comment]
Let us know if you could resolve the issue - thanks

**Comment by skalumek** [comment]
He,

Still not working, here is the config

{
  "HorizonLayout": [
    {
      "layout": "bannerImage",
      "isSlider": true,
      "isBlur": true,
      "showBackground": true,
      "padding": 20.0,
      "radius": 20.0,
      "title": "Ecommerce",
      "fontSize": 26.0,
      "isSafeArea": true,
      "showSearch": true,
      "autoPlay": true,
      "items": [
        {
          "category": 25,
          "image": "https://jazajaza.com/images/Bedding.jpg"
        },
        {
          "category": 23,
          "image": "https://jazajaza.com/images/newbaby.jpg"
        },
        {
          "category": 26,
          "image": "https://jazajaza.com/images/plainbedsheets.jpg"
        }
      ]
    }
  ],
  "VerticalLayout": {
    "layout": "pinterest",
    "name": "Trending Collections"
  },
  "Setting": {
    "MainColor": "#3FC1BE",
    "ProductListLayout": "list"
  },
  "TabBar": [
    {
      "layout": "home",
      "icon": "assets/icons/tabs/icon-home.png"
    },
    {
      "layout": "category",
      "categoryLayout": "card",
      "icon": "assets/icons/tabs/icon-category.png"
    },
    {
      "layout": "search",
      "icon": "assets/icons/tabs/icon-search.png"
    },
    {
      "layout": "cart",
      "icon": "assets/icons/tabs/icon-cart2.png"
    },
    {
      "layout": "profile",
      "icon": "assets/icons/tabs/icon-user.png"
    }
  ]
}

**Comment by minhcasi** [comment]
@tgloc96 - pls help to check the auto play issue on this ticket

**Comment by tgloc96** [comment]
> Am using this layout i wanted the images on the header(slider) to auto slide.
> ![Capture](https://user-images.githubusercontent.com/69422644/91013124-e5965300-e5ef-11ea-8825-19ce7ce9a7a0.PNG)

Hello @skalumek , please you try open file at "_lib/models/app.dart_" and remove block code below and delete app was build on the simulator or real device and build the app again
<img width="818" alt="image" src="https://user-images.githubusercontent.com/46434718/91525205-2ca38180-e92b-11ea-9c0d-c5074ea5ff42.png">

**Comment by minhcasi** [comment]
Let us know your checking to see if the solution is worked?
