### ISSUE TITLE
Fluxstore License is not matching our requirements & team not resolving issues

### ISSUE THREAD

**Issue by shubhamsurvase** [inspireui/support#4675]
Hi We have purchased fluxstore license but its not matching our requirements.
We had raised multiple tickets but the @inspireUI team is not able to resolve those issue too.

WE would want to discontinue the license and request refund.

**Comment by minhcasi** [comment]
@shubhamsurvase - you could process on this link https://help.market.envato.com/hc/en-us/articles/202821460-Can-I-Get-A-Refund- - thank you!
