### ISSUE TITLE
3 Little issue: visualize only father categories, quantity label position and dark icon menu is not showing correctly.

### ISSUE THREAD

**Issue by jvsamoa** [inspireui/support#4676]
Hi everybody, very long time go by without writing to you.
My best regards...

At this time, i have 3 questions:

1. How can I visualize only father categories in Categories?
![image](https://user-images.githubusercontent.com/25646978/90688040-21d35780-e26e-11ea-9dc9-2f4c13ab9da0.png)

2. Inside the cart section, the product quantity label is above the product thumbnail image, I need to move it below to the price label.
![image](https://user-images.githubusercontent.com/25646978/90688009-14b66880-e26e-11ea-90bd-3f52bafab10f.png)

3. In dark mode, I can´t see the icon menu.
![image](https://user-images.githubusercontent.com/25646978/90688077-33b4fa80-e26e-11ea-86aa-56109da7589f.png)

Little details, I supposed that if I upgrade the app for the latest version may be a lot of these issues will be solved...

**Comment by simonpham** [comment]
Hi @jvsamoa,

Regarding your concern:
1. You can check [our documentation](https://docs.inspireui.com/fluxstore/home-layout/#4-category-layout) to change the category layout.
2. I will check and reply you ASAP.
3. Currently we doesn't support different images for light/dark theme. You can consider to use transparent PNG image or just open lib/common/styles.dart and change the color in `buildDarkTheme` -> `appBarTheme` -> `iconTheme` -> `color` to whatever color you want. For example: `kLightAccent` or `Colors.black`
![image](https://user-images.githubusercontent.com/8846657/90718100-52050f80-e2db-11ea-9a20-71ef43cb5c96.png)

Thank you for using our products.

**Comment by simonpham** [comment]
Hi @jvsamoa,

For the 2nd issue, you can send us your `lib/widgets/product/cart_item.dart` to inspireui.team@gmail.com.
Our team will help you to change it.

Thank you for using our proudct.

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
