### ISSUE TITLE
About features 

### ISSUE THREAD

**Issue by ssathamenterprises** [inspireui/support#4678]
Hello any options to show purchase products images in order page

**Comment by minhcasi** [comment]
@ssathamenterprises - sorry we could not as it is limit with the order API from WooCommerce. 

We could upgrade to customize the API to support for this feature - let me note as a feature request and upgrade it later (as it will take time on both api and mobile)

**Comment by minhcasi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Feature: show Image Product Order](https://trello.com/c/LMU2B6Ym/70-feature-show-image-product-order)
