### ISSUE TITLE
[ListApp] App kees crushing on the launch

### ISSUE THREAD

**Issue by urasuji** [inspireui/support#468]
Required Info (please complete the following information):

Product: ListApp
Your Purchased Code: 356e79dc-c9af-45f2-9b27-ef1b52ca6088
(we may not reply if you are not our customer)
Describe the bug
App keeps crushing after the launch

Screenshots
https://photos.app.goo.gl/ezDg7e7HttSHJr2Q9
https://photos.app.goo.gl/DS2KtnapDzmbh2ti6

Additional context
I think I followed your manual step by step but both expo apps are still not working properly...

**Comment by urasuji** [comment]
How could you close the previous issue so fast? Besides you didn't get what exactly our issue is.
Please do care about your customer even after the purchase.

**Comment by thangvo9x** [comment]
Do you have change categoryListingId in yourtheme.js in Config folder
Make sure your app is connected to your site. 
document here : 
https://inspireui.github.io/listapp/docs/quickstart
Thanks
