### ISSUE TITLE
error with apple login

### ISSUE THREAD

**Issue by ahmed-foulad20** [inspireui/support#4681]
i have this error when i try to sign in with apple login

the method '[]' was called on null

![WhatsApp Image 2020-08-20 at 12 42 40 PM](https://user-images.githubusercontent.com/69421088/90776307-9c4db700-e302-11ea-8d0c-e953f4639771.jpeg)

**Comment by ahmed-foulad20** [comment]
i use static type in splash screen

**Comment by minhcasi** [comment]
@minhtruong315 - pls help to investigate the issue

**Comment by ahmed-foulad20** [comment]
also  if i place new order the shipping price come to zero when i chose Cash on delivery
its work ok on my site and all settings ok in woocommerce 
![Screenshot_1598253545](https://user-images.githubusercontent.com/69421088/91015160-58ed9400-e5f3-11ea-811e-260694e0e6d3.png)
![Screenshot_1598253564](https://user-images.githubusercontent.com/69421088/91015175-6014a200-e5f3-11ea-83a5-3b34685c6469.png)

**Comment by minhtruong315** [comment]
@ahmed-foulad20 give me your skype. I will contact you to check remotely 
Thanks

**Comment by ahmed-foulad20** [comment]
@minhtruong315 i send it to you . thanks

**Comment by minhtruong315** [comment]
@ahmed-foulad20 please replace file models/user/user_model.dart. then run app on real device and test apple login again
[user_model.dart.zip](https://github.com/inspireui/support/files/5130867/user_model.dart.zip)
for shipping issue, I see you're config "wcfm" in app, but I dont see any wcfm plugin in your website.

**Comment by ahmed-foulad20** [comment]
@minhtruong315 still login not working . and the shipping issue still same after change to 'dokan'

**Comment by minhtruong315** [comment]
@ahmed-foulad20 did you check it in real device?

**Comment by minhtruong315** [comment]
please record me issue about apple login and shipping?

**Comment by ahmed-foulad20** [comment]
@minhtruong315 login with apple now working ok , but shipping issue still .

**Comment by minhtruong315** [comment]
@ahmed-foulad20 replace models/shipping_method.dart and models/order/order.dart
[shipping_method.dart.zip](https://github.com/inspireui/support/files/5136638/shipping_method.dart.zip)
[order.dart.zip](https://github.com/inspireui/support/files/5136639/order.dart.zip)

**Comment by ahmed-foulad20** [comment]
> @ahmed-foulad20 replace models/shipping_method.dart and models/order/order.dart
> [shipping_method.dart.zip](https://github.com/inspireui/support/files/5136638/shipping_method.dart.zip)
> [order.dart.zip](https://github.com/inspireui/support/files/5136639/order.dart.zip)

@minhtruong315 still not working

**Comment by ahmed-foulad20** [comment]
thanks bro its work fine now
