### ISSUE TITLE
the app is crashed and show the logo screen

### ISSUE THREAD

**Issue by ahmed-foulad20** [inspireui/support#4682]
i have 2 problems in my multiVendor app version 1.7.7
first one : the shipping price saved as 0 when i place new order 
![Screenshot_1597935233](https://user-images.githubusercontent.com/69421088/90788799-d45af700-e30e-11ea-9f29-8495bda40bee.png)
![Screenshot_1597935278](https://user-images.githubusercontent.com/69421088/90788901-ef2d6b80-e30e-11ea-8015-bf04755ae821.png)

------------

**second : the app is crashed and show the logo screen when i place new order and press the back to shop button
i use static type for logo**

![Screenshot_1597931189](https://user-images.githubusercontent.com/69421088/90788938-fb192d80-e30e-11ea-8b37-0e796028b606.png)
![Screenshot_1597931229](https://user-images.githubusercontent.com/69421088/90788989-08ceb300-e30f-11ea-84e2-2c8b744d4f7f.png)

**Comment by minhcasi** [comment]
@ahmed-foulad20 - please help us to give your all comment into one open ticket #4681 - thank  you for your time!
