### ISSUE TITLE
problem with run fluxstore pro on android studio

### ISSUE THREAD

**Issue by hdakei** [inspireui/support#4684]
**_Step 1 (require): describe detail issues & screenshots_**
![Issue](https://i.ibb.co/wNMKzCB/error.png)

I followed instruction after finish everything when I click on the run on my android studio,it shows some errors as image you see,so could you give me support to this issue please ?

+ Product & version:1.7.7b
+ Flutter (or React Native) version: Flutter
+ Testing Device/Simulator: Android Simulator (API 29 Android 10)
+ Screenshot issues (drag the file to attach here): 
`https://i.ibb.co/wNMKzCB/error.png`

**Comment by hdakei** [comment]
refer to my form submitted for the license, our project is on developing right now and we are on QA on this time so I can't register our website on this time , my envato's username is szkcompany could

**Comment by minhcasi** [comment]
@hdakei - could you send us your result from `flutter doctor`

Also try to run the Test Drive example to check your Flutter envoriment - https://docs.inspireui.com/fluxstore/getting-started/#2-run-example-test-drive

**Comment by hdakei** [comment]
for first, thank you for your response, I already have some flutter projects and they work correctly on my system, my screenshot of flutter doctor is mention below:
![Fluttter doctor Result](https://i.ibb.co/7JVwm0D/flutter.png)

**Comment by hdakei** [comment]
> 
> 
> for first, thank you for your response, I already have some flutter projects and they work correctly on my system, my screenshot of flutter doctor is mention below:
> ![Fluttter doctor Result](https://camo.githubusercontent.com/7173d5085249ee78bd2b7b466ce17ac4acff36dd/68747470733a2f2f692e6962622e636f2f374a56776d30442f666c75747465722e706e67)

also full result is this:




![Issue](https://i.ibb.co/YhGSpZc/flutter-full-result.png)

**Comment by minhcasi** [comment]
Hi sir, let us know if you have any question, feel free to reopen the ticket if you need any support - thank you!
