### ISSUE TITLE
[MStore] Close button or Back button on webpage view

### ISSUE THREAD

**Issue by sashaba** [inspireui/support#469]
**We are looking for any contribution to improve the product features and quality, please let us know.**
A clear and concise description of what the idea is. Ex. I would love to have this feature [...]

**Mandatory Info (please complete the following information):**
 - Product: MStore Pro

Hello, 
When we open a webpage on the app, there is not close or back button at the top, if we press the phone back button(Android) it will take us to the home page of the app and not the previous screen. 

Pages like: Privacy Policy, Contact us, terms of service and more... 

There should be a Close button on the webpage view like the one on the checkout view.
Thanks.

**Comment by sashaba** [comment]
I forgot to add:
It will be awesome to have a Text Block or Text layout for Titles and descriptions, and a Image slider Layout ( like the banner slider but with images no products) I tried to add them but fail. 
Thank you

**Comment by luyx2412** [comment]
HI @sashaba Thanks for your feedback, currently we did not support this feature. We will try improve in next version.
