### ISSUE TITLE
Regarding product description

### ISSUE THREAD

**Issue by GNAG1993** [inspireui/support#4692]
Hello,
Please refer to my earlier issue https://github.com/inspireui/support/issues/4668 . We have added custom data fields to product like brand, size etc. But they are not showing up in product details. At least understand what I'm asking about before closing ticket. Closing tickets will decrease the opened issues, but will get negative feedback. So before closing any ticket you guys should wait for the response by the ticket creator.

For verification get a look on my other tickets https://github.com/inspireui/support/issues/4469

**Comment by minhcasi** [comment]
@GNAG1993 - my team is working on a new upgrade to support the complex variant on the next upgrade `1.7.8`, you could try to wait for the next version. 

As you can see if we do not support for any question regarding the Integration issues due to limitations of the scope of support from Regular License (https://inspireui.com/support-policies/) - but if you could look back on 13 ticket supports - we have tried our best with outstanding supporting. 

If you are using the project as a commercial purpose to build the marketplace site, consider upgrading as extend license to meet with the Envato policies - thank you for your time!

**Comment by GNAG1993** [comment]
@minhcasi You are not getting my point. Its not about variants at first. I'm saying we have created custom fields for product description. How can those fields be shown in app with product description.

**Comment by minhcasi** [comment]
@GNAG1993 - pls share some screenshot of the product description on your website so that we could understand more about your question - thanks

**Comment by minhcasi** [comment]
@GNAG1993 - any update sir?

**Comment by GNAG1993** [comment]
@minhcasi  **Sorry for delayed response.  I'm sharing screenshots from  back-end so that you can understand them better.**

**First Screenshot is from woocommerce back-end.** You can see. We created a new field group & field name
![Field](https://user-images.githubusercontent.com/58203387/91137633-48f5b300-e6cc-11ea-9d8c-4c57a3dc617c.png)



**Second Screenshot is from woocommerceWCFM back-end.** You can see. We created a new field group & field name
![Field WCFM](https://user-images.githubusercontent.com/58203387/91137560-43986880-e6cc-11ea-85ab-8d931d5b8a72.png)

**Comment by minhcasi** [comment]
@GNAG1993 - i think that field will be set inside the meta_data from the product, please try to add the breakpoint from product model and explore to see if there is include from the JSON?

<img width="1303" alt="Screen Shot 2020-08-26 at 11 00 26" src="https://user-images.githubusercontent.com/1459805/91253986-5b82f180-e78b-11ea-8154-c4614a35ffee.png">

**Comment by GNAG1993** [comment]
Ok, I'm trying. lets see what happens.

**Comment by GNAG1993** [comment]
_hsn_code is slug of that hsn code field.

**Comment by minhcasi** [comment]
cool, you could try to define new field for this value on the product model and display it on the product detail UI

**Comment by GNAG1993** [comment]
@minhcasi I was unable to define that. Actually I'm not too good at flutter. Can you just help me in defining and displaying a field? According to that I'll display my all fields then.

**Comment by minhcasi** [comment]
@GNAG1993 - I'm sorry that we could not support this customization, you could try to see some similar mapping field and make the same approach

**Comment by GNAG1993** [comment]
@minhcasi I understand. Can you just tell me any similar mapping field so that I can get a reference. This would be too helpful for me.

**Comment by minhcasi** [comment]
example: get the _minmax_product_max_quantity - https://tppr.me/4LK30

or video_url: https://tppr.me/KphjH

**Comment by GNAG1993** [comment]
@minhcasi According to this will I have to parse each field? Because I'm having more than 100 custom fields in total.

**Comment by minhcasi** [comment]
Sorry - i've got your point. Do you mean having the same custom fields like `HSN Code`?

<img width="866" alt="Screen Shot 2020-08-30 at 08 45 17" src="https://user-images.githubusercontent.com/1459805/91649340-23d2bd00-ea9d-11ea-865c-46d19414839d.png">

**Comment by minhcasi** [comment]
Let us know your clarification so that we could know more about the request - thanks

**Comment by GNAG1993** [comment]
Yes, Please go through this plugin, https://www.advancedcustomfields.com/
This is compatible with wcfm.
we are creating Custom fields through this for more product details like RAM/Screen Size/Fabric/HSN Code etc.

**Comment by minhcasi** [comment]
@GNAG1993 - you could try to investigate this API to see if it could load as a dynamic field - https://wordpress.org/plugins/acf-to-rest-api/

**Comment by minhcasi** [comment]
Let us know if you have successfully integrate with that plugin - thankx

**Comment by GNAG1993** [comment]
@minhcasi I'll try this today and tell you

**Comment by GNAG1993** [comment]
@minhcasi Instead of using that plugin, I have used a snippet which is exposing ACF Fields in Rest API. I'm sharing the code here. Please try to check can we go with this code.

function acf_to_rest_api($response, $post, $request) {
    if (!function_exists('get_fields')) return $response;

    if (isset($post)) {
        $acf = get_fields($post->id);
        $response->data['acf'] = $acf;
    }
    return $response;
}
add_filter('rest_prepare_post', 'acf_to_rest_api', 10, 3);


This code is exposing ACF fields on this url:   https://site-name/wp-json/acf/v3

**Comment by minhcasi** [comment]
Yes, that is also a good solution to add your custom field for ACF

**Comment by minhcasi** [comment]
hi mate, pls share your update on the solution, thank you!

**Comment by GNAG1993** [comment]
Hi @minhcasi , as I told you above that now fields are showing in rest api, but still I'm unable to get them into fluxstore app as i'm not a flutter or dart expert. It would be really helpful if you help me out. As this will help out many of your users.

**Comment by minhcasi** [comment]
@GNAG1993 - try to send your the `config.dart` file to inspireui.team@gmail.com - we will help to investigate and let you know

**Comment by GNAG1993** [comment]
@minhcasi thanks a lot. I'm sharing that now.

**Comment by minhcasi** [comment]
Got your email, we will have a check and let you know 👍

**Comment by GNAG1993** [comment]
Okay

**Comment by GNAG1993** [comment]
Hi @minhcasi did you get little time to check that?

**Comment by minhcasi** [comment]
@GNAG1993 - sorry for the late response on this ticket, our team have tried your source but could not find the best solution to populate the data in the app due to the complexity of the `acf`  data.

I think you could hard-code some field to map with the specific fields for ACF, it could be done by dynamic loading and update on fluxstore app 

Pls move the future question to https://support.inspireui.com/mailbox/tickets/tag/1/ticket/131
