### ISSUE TITLE
How to change the loginpage logo in fluxstore app and recently view products portion is not showing in app which is showing in fluxbuilder

### ISSUE THREAD

**Issue by alokmalewar** [inspireui/support#4693]
This is the Screenshot
![screenshot](https://user-images.githubusercontent.com/69632534/90880277-d6cc5800-e3c5-11ea-9af5-7ef72a5e89da.png)
and this is of the login page of how to change the logoimage
![login](https://user-images.githubusercontent.com/69632534/90880510-2e6ac380-e3c6-11ea-98ab-89f4088bf8d7.png)

**Comment by alokmalewar** [comment]
1.fluxbuilder screenshot recently viewed portion is in it.
![scr1](https://user-images.githubusercontent.com/69632534/91040125-56a72c00-e62b-11ea-87b9-23801529bd20.png)
mobile app recently viewed portion is not in it why it is happening
![WhatsApp Image 2020-08-24 at 4 56 13 PM](https://user-images.githubusercontent.com/69632534/91040185-6de61980-e62b-11ea-8841-4f043a70e16d.jpeg)
2.it is showing an error while user sign up
![WhatsApp Image 2020-08-24 at 4 56 13 PM (1)](https://user-images.githubusercontent.com/69632534/91040267-8c4c1500-e62b-11ea-83bd-4602dcc71f63.jpeg)

**Comment by alokmalewar** [comment]
one more issue is found during shipping 
![WhatsApp Image 2020-08-24 at 6 01 28 PM](https://user-images.githubusercontent.com/69632534/91045200-244dfc80-e634-11ea-8fdc-1646d80a9471.jpeg)

**Comment by ameenbadri7** [comment]
Update the mstore plugin on your WordPress website and make sure that the plugin is activated.
as this problem is related to the website set up common problems new customers could have.
see our project example to learn more.
https://docs.inspireui.com/fluxstore/woocommerce-setup/
Thank you.
