### ISSUE TITLE
After checkout it is going to the website checkout page instead of Payfast payment gateway

### ISSUE THREAD

**Issue by DevKish23** [inspireui/support#4694]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
- [ ] first issue
- [ ] second issue
- [ ] third issue

+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com **

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@DevKish23 - current fluxstore app only support for these payments via webview, if you would like to implement as the native payment, please try to customize with integration with Payfast API (refer to the similar demo for Paypal from the app) - thank you!

**Comment by minhcasi** [comment]
Let us know if you have any questions - thank you for your time!
