### ISSUE TITLE
flux store Shopify app error

### ISSUE THREAD

**Issue by vijayalaxman** [inspireui/support#4697]
**_Step 1 (require): describe detail issues & screenshots_**
**+ Detail Issues:** 
- Done everything as shown in your video, including installing graphi ql
- Configured app
- when creating build it is getting error,

I kindly  request inspire ui to resolve this, further i may request you for customized modifications, please check out this , thank you

+ Product & version:
+ Flutter (or React Native) version: latest
+ Testing Device/Simulator: Android 8/9/10 AVD device
+ Screenshot issues (drag the file to attach here
![error](https://user-images.githubusercontent.com/42832973/90887438-fb2e3180-e3d1-11ea-9c17-00b089e113d0.jpg)
): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com **

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by luyx2412** [comment]
Closed! Because no longer response.

P/S: Feel free to create new issue.
