### ISSUE TITLE
"No Products" when i reopen category

### ISSUE THREAD

**Issue by Arnaldo4ever** [inspireui/support#4698]
Hello, I bought the Shopify application from the flux store, I connected my store with the application and when I enter a category the products appear, when I return home and re-enter the category I show No products screen, could you help me?

<a href="https://ibb.co/HH4BYx6"><img src="https://i.ibb.co/YLQP8ym/Captura-de-Pantalla-2020-08-21-a-la-s-12-37-04-p-m.png" alt="Captura-de-Pantalla-2020-08-21-a-la-s-12-37-04-p-m" border="0"></a>

**Comment by luyx2412** [comment]
Hi @Arnaldo4ever I just invited you to the latest version fluxshopify repo, so please pull and merge with current project to fix the issues.

Thanks

**Comment by minhcasi** [comment]
Let us know if you have any question - thank you!
