### ISSUE TITLE
"Version Solving Failed"

### ISSUE THREAD

**Issue by Cydo73** [inspireui/support#4699]
![Capture](https://user-images.githubusercontent.com/69629505/90925585-2dec2000-e3fa-11ea-9f37-7c2a16902ec7.JPG)
![2](https://user-images.githubusercontent.com/69629505/90925592-32183d80-e3fa-11ea-99e1-52489aeb5aae.JPG)

I get these errors when i just opened up my android studio and "Run" the app on the emulator. Nothing shows on the emulator. I tried using dependency overrides, but another error "XmlEventAttribute not found" loads when i run the program.
Please let me know what i can do, because i haven't changed the source code or edited anything, and this is very urgent. I hope to hear from you

**Comment by Cydo73** [comment]
i worked on the issue, thank you for the tip. The app loaded fine.
In the instruction manual, you ask us to access lib/config/config_xx.json,
which i can't seem to locate in the source code
Is there something am missing?


‪On Sun, Aug 23, 2020 at 5:11 PM ‫amin badri أمين بدري‬‎ <
notifications@github.com> wrote:‬

**Comment by ameenbadri7** [comment]
<img width="574" alt="Screen Shot 2020-08-24 at 8 26 25 PM" src="https://user-images.githubusercontent.com/37524186/91076476-3f2a6c00-e648-11ea-9f04-27929c64209f.png">

if it deleted you cannot open the app as it the main essential assets inside the app.
double-check our [documentation](https://docs.inspireui.com/fluxstore/customization/) also the videos to know more about the app.

Thank you.

**Comment by Cydo73** [comment]
Hello again.. Forgive me, I keep landing on the wrong side of things.
I have followed the required instructions on installing Flux Builder,
because I prefer editing my app with the tool rather code, because am not a
tech expert.
I used it for about one session, but it's becoming annoyingly slow
Everytime I open my project
I tried cleaning up my disk space, uninstalling and reinstalling it, doing
whatever I could think of.
Please let me know what you think I can do to make it more responsive.
Thank you!
