### ISSUE TITLE
[ListApp] ListApp manager plugin issue

### ISSUE THREAD

**Issue by Pars1vaLl** [inspireui/support#47]
**Required Info (please complete the following information):**
 - Product: ListApp
 - Your Purchased Code: 85059e37-2ddd-478d-899b-6db006280782

**Describe the bug**
ListApp plugin is not working. I cant install it with WP,so I did it manually,but it deactivated automaticly. It says "Plugin listapp-manager-master/listapp-manager.php was deactivated.Cant find plugins file"

**Screenshots**

**Additional context**
Add any other detail logs about the problem here.
If possible please share your config.js that use for the app setting

**Comment by thangvo9x** [comment]
Hi. Try remove & re-install the plugin again 
let me know if it works. Thanks

**Comment by Pars1vaLl** [comment]
Hi!  I did it, but here what it says now: 
"Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'pim_draw_notice_json_api' not found or invalid function name in "

**Comment by thangvo9x** [comment]
You must have install plugin JSON-API before, here 
https://github.com/inspireui/mstore/tree/master/plugins

**Comment by Pars1vaLl** [comment]
Great! JSON-api was deactivated. Thank you:)

**Comment by thangvo9x** [comment]
Solved !
