### ISSUE TITLE
[MStore] Images NOT displaying

### ISSUE THREAD

**Issue by PON4UK1** [inspireui/support#470]
**Mandatory Info (please complete the following information):**
 - Product:MStore
 - Your Purchased Code: e5b481e6-875a-4eb2-9303-3b696bda1d60

**Describe the issues**
I tried every single way and checked previous issues similar to mine and nothing helped. (changed config.js  ProductSize to false but it didn't help)

**Screenshots**

**Additional context**
Add any other detail logs about the problem here.

**Comment by luyx2412** [comment]
Hi @PON4UK1 Can you provide your Mstore version?

Thanks

**Comment by PON4UK1** [comment]
Thanks for the quick reply. 
My current store version is 3.7.2

Thanks

**Comment by luyx2412** [comment]
Hi, please use the debug tool to check your request api. https://docs.mstore.io/api-and-project-structure

Thanks
