### ISSUE TITLE
Build Error 

### ISSUE THREAD

**Issue by seventhsonmizo** [inspireui/support#4700]
![flutererror](https://user-images.githubusercontent.com/51083588/90948029-4ab74080-e458-11ea-89b6-b4c7ea797f6f.PNG)

I just bought the FluxstoreMV and start running the app. This is my first time to used flutter. I think I have done it step by step from your guide, but I got this error in building.
Gradle:  6.1.1
Flutter:  1.20.2
Dart: 2.9.1

I'm stuck here..

**Comment by minhcasi** [comment]
Hi sir, let us know if you have any update - thanks
