### ISSUE TITLE
FluxNews Bug - Author name returning null and only 15 categories are displaying

### ISSUE THREAD

**Issue by RomeoDar** [inspireui/support#4701]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
- [author name returning null, (screenshot is attached below). i want to display arthor name on blogs. my website displaying author name but on mobile app its returning null  ] first issue
- [ only 15 categories are displaying on category section and sidedrawer but there are more than 30 categories on my wordpress site, please provide guideline how to display all categories ] second issue

**Proof of Purchase done **

+ Product & version: FluxNews 1.4.1
+ Flutter (or React Native) version: Flutter
+ Testing Device/Simulator: Real

![WhatsApp Image 2020-08-22 at 9 43 30 AM (1)](https://user-images.githubusercontent.com/52714884/90948842-2eb59e00-e45c-11ea-8560-9df68917e52f.jpeg)

**Comment by minhcasi** [comment]
@RomeoDar - it could be the bug with the author name from previous `1.4.1` - could you help to download the latest `1.4.3` to see if it could be fixed, otherwise - i will report to the team for investigating this issue and fix it on next release - thank you!

**Comment by minhcasi** [comment]
Let us know if you have any update sir

**Comment by RomeoDar** [comment]
Sir if there is bug for author then i've also mentioned that only 15 categories are displaying why did you ignore that ? its not first time, all always do the same. its not first thread, i've to come up with new solutions or exclude the whole module.

kindly stop providing proper support, still facing both problem, 15 categories are displaying.

**Comment by RomeoDar** [comment]
@minhcasi
