### ISSUE TITLE
Login Issue in fluxstore pro 1.7.7

### ISSUE THREAD

**Issue by iidaindia** [inspireui/support#4702]
I am getting login issues with Fluxstore 1.7.7

1. SMS LOGIN
![Simulator Screen Shot - iPhone 7 - 2020-08-22 at 12 34 59](https://user-images.githubusercontent.com/69832518/90951060-e48ce680-e474-11ea-9059-f55b215b2af2.png)

2. Google Login
![Simulator Screen Shot - iPhone 7 - 2020-08-22 at 12 36 12](https://user-images.githubusercontent.com/69832518/90951073-fa021080-e474-11ea-8652-fcd3758e5325.png)

3. Facebook Login

![Simulator Screen Shot - iPhone 7 - 2020-08-22 at 12 37 07](https://user-images.githubusercontent.com/69832518/90951084-0dad7700-e475-11ea-88a6-46ccc6df82ea.png)

+ Product & version: FLUXSTORE 1.7.7
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: ANDROID PIXEL 3L AND IPHONE 7
+ Screenshot issues (drag the file to attach here): FILES ATTACHED.

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com ** PROOF OF PURCHASE

SAME IS WORKING IN FLUXSTORE MV. 

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by iidaindia** [comment]
yes, i forgot it. thanks

**Comment by minhcasi** [comment]
Hi sir, let us know if you have any question, thank you!
