### ISSUE TITLE
checkout page returning empty on webview

### ISSUE THREAD

**Issue by tskmark** [inspireui/support#4703]

**Comment by tskmark** [comment]
I recently migrated to a new hosting too, i dont know if that might be the cause.... i think this started after that or after your plugin update, I’m not really sure

**Comment by minhcasi** [comment]
miskayapp - our system report your user as spam via email (+100 email) and several tickets support, pls try to stop spamming and use one channel to contact us

**Comment by tskmark** [comment]
You guys reply mails once a day, sometimes 2-3days to get a reply, i get you are busy... but common its frustrating for us users, this is the 4th month trying to get this app right, now suddenly my app starts returning empty cart and youre closing the issue without a response to my last reply, you guys are killing me here.

**Comment by tskmark** [comment]
You guys reply mails once a day, sometimes 2days to get a reply, i get you are busy... but common its frustrating for us users, i

**Comment by tskmark** [comment]
I only have this complaint and the last 4 unanswered mails, I’m sorry for spaminh your mails.
