### ISSUE TITLE
Notification from inspireui

### ISSUE THREAD

**Issue by Bozso21** [inspireui/support#4704]
Hi. Please help me out with this, we don't want such notifications to be displayed to our users
![IMG_1655](https://user-images.githubusercontent.com/68916073/90953727-5ada1a80-e46e-11ea-9a6a-c042674fad74.jpg)

**Comment by minhcasi** [comment]
Let us know if you have any question, feel free to reopen the ticket if you need any support - thank you!

**Comment by alexrali** [comment]
@minhcasi, in my case, I did not remove that line

**Comment by Bozso21** [comment]
Hi, in my case it was removed - do you have any idea how this could have happened?
