### ISSUE TITLE
Disable languages + blog images do not appear

### ISSUE THREAD

**Issue by danimmg** [inspireui/support#4706]
Hello
1 - After the FluxListing update, the blog images are no longer showing.

![Capture22-08-2020-07 04 30](https://user-images.githubusercontent.com/59834619/90953940-39fdcf00-e446-11ea-85a1-3b4b7f0f17ea.jpg)
![Capture22-08-2020-07 04 52](https://user-images.githubusercontent.com/59834619/90953941-3b2efc00-e446-11ea-89c1-6ff9bcea85d2.jpg)

2 - I don't need to use additional languages, before the update I followed this manual and it worked now the code has been changed and I can't find the lines that should be disabled

<img width="624" alt="40" src="https://user-images.githubusercontent.com/59834619/90953972-8e08b380-e446-11ea-9e8b-4753c0c5a63a.png">

Current code

![Capture22-08-2020-07 07 03](https://user-images.githubusercontent.com/59834619/90953976-9cef6600-e446-11ea-9ac8-ebdd5f8ca581.jpg)

Thanks

**Comment by minhcasi** [comment]
Hi sir, let us know if you have any question, feel free to reopen the ticket if you need any support - thank you!
