### ISSUE TITLE
App not running on emulator

### ISSUE THREAD

**Issue by ceofvo** [inspireui/support#4707]
**_Step 1 (require): describe detail issues & screenshots_**
When I run yarn start then try to run on emulator I get the below error message
"ERROR
11:42
Unable to resolve "./vendor/react-native-vector-icons/glyphmaps/MaterialCommunityIcons.json" from "src\Expo\vector-icons\MaterialCommunityIcons.js"
ERROR
11:42
Building JavaScript bundle: error"
+ Detail Issues: 
- [ ] first issue
- [ ] second issue
- [ ] third issue

+ Product & version: MStore Multi Vendor-v1.3.3
+ Flutter (or React Native) version: React Native Version
+ Testing Device/Simulator: Android
+ Screenshot issues (drag the file to attach here): 
![Capture1](https://user-images.githubusercontent.com/29120743/90954834-f1f3a200-e46f-11ea-9b4d-3b0da5094c35.PNG)
![Capture2](https://user-images.githubusercontent.com/29120743/90954840-f9b34680-e46f-11ea-9155-34f80ee00d4c.PNG)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com **

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhtruong315** [comment]
@ceofvo can u send me full your source code via email: minhtruong315@gmail.com
ping me when you sent.
Thanks

**Comment by ceofvo** [comment]
@minhtruong315 sent to your email

**Comment by ceofvo** [comment]
@minhtruong315  your email blocked the files I sent to your email. See below. Are there any other means I can send it to you?

Sorry, we were unable to deliver your message to the following address.

<minhtruong315@gmail.com>:
552: 5.7.0 This message was blocked because its content presents a potential
5.7.0 security issue. Please visit
5.7.0  https://support.google.com/mail/?p=BlockedMessage to review our
5.7.0 message content and attachment content guidelines. r9si9813606plo.43 - gsmtp

**Comment by minhtruong315** [comment]
@ceofvo can u upload source code to github and invite my email?

**Comment by ceofvo** [comment]
@minhtruong315 I have sent to your email with a file sharing service (wetransfer.com), check your email for the files

**Comment by minhtruong315** [comment]
@ceofvo replace src/Expo folder and try again
[Expo.zip](https://github.com/inspireui/support/files/5139602/Expo.zip)

**Comment by ceofvo** [comment]
@minhtruong315  its working now, but images are not loading and the cart icon and account icon are not showing. Also I saw CeBuilder somewhere on your themeforest page but I can't any instruction on how to use it on your site. Will Fluxbuilder work with Mstore?

![Capture 3](https://user-images.githubusercontent.com/29120743/91556167-3082d400-e92a-11ea-90e9-84beea0bf046.PNG)

**Comment by minhcasi** [comment]
@ceofvo - pls try to run Regenerate image by following this guide https://docs.inspireui.com/mstore-mv/getting-started/

**Comment by minhcasi** [comment]
Let us know your checking, thank you!

**Comment by ceofvo** [comment]
Hello, the images are loading but you did not address the cart, and the account icons not showing issue. Also no comment on my inquiry on CeBuilder
