### ISSUE TITLE
Codepoint 58848 not found in font, aborting, Error on product opening and cant sign in or sign up in the app

### ISSUE THREAD

**Issue by lakshayb121** [inspireui/support#4713]
This errors are in FluxStore shopify

![Annotation 2020-08-23 163713](https://user-images.githubusercontent.com/55995898/90976938-18dcd180-e55f-11ea-8ad6-b53ff48f96f6.png)
I get this message on the product page

2nd error when i try to build apk it shows the error Codepoint 58848 not found in font, aborting.

3rd error customers cant sign in or sign up in the app
![Screenshot_2020-08-23-16-40-56](https://user-images.githubusercontent.com/55995898/90976985-90aafc00-e55f-11ea-8dca-dd4d69630981.png)

**Comment by minhcasi** [comment]
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by lakshayb121** [comment]
When can i expect a reply?

**Comment by IbrahimHd** [comment]
Hi, 
While building APK, error `Codepoint 58848 not found in font, aborting` happens in FluxStore PRO 1.7.7 (even after cleaning the Cache, but works well with the emulator)

Thanks you for your prompt action.

**Comment by luyx2412** [comment]
Hi @lakshayb121 Can you fill the form http://verify.inspireui.com/ and upload your config? We can investigate easier.

Thanks

**Comment by lakshayb121** [comment]
> Hi @lakshayb121 Can you fill the form http://verify.inspireui.com/ and upload your config? We can investigate easier.
> 
> Thanks
> 
> <blockquote><div><strong><a href="http://verify.inspireui.com/">Google Forms - create and analyze surveys, for free.</a></strong></div><div>Create a new survey on your own or with others at the same time. Choose from a variety of survey types and analyze results in Google Forms. Free from Google.</div></blockquote>

I have already filled this form why this support is so worst i have asked you about errors which are common to many users so i think it dont have anything with my config file you should update the code. But still if you need my config file give me link where i can upload it

**Comment by luyx2412** [comment]
Hi @lakshayb121 Thanks for your quick reply. I just invited you to fluxshopify latest repo. So please pull latest code and merge with your current project to fix the issue.

Thanks

**Comment by lakshayb121** [comment]
> Hi @lakshayb121 Thanks for your quick reply. I just invited you to fluxshopify latest repo. So please pull latest code and merge with your current project to fix the issue.
> 
> Thanks

Where you sent the invitation? To my email?

**Comment by luyx2412** [comment]
Yep i invited this email lakshaybomotra@gmail.com.

**Comment by lakshayb121** [comment]
> Yep i invited this email lakshaybomotra@gmail.com.

Ok thanks. Can i know which of my errors are covered in the latest code?

**Comment by lakshayb121** [comment]
![IMG20200825233933.jpg](https://user-images.githubusercontent.com/55995898/91211345-43c85080-e72c-11ea-8933-c75cc9222ca6.jpg)

I got a new error when tried to build apk with latest code from gitlab repo

**Comment by lakshayb121** [comment]
> Yep i invited this email lakshaybomotra@gmail.com.

Hey please reply i dont expect this kind of behaviour

**Comment by lakshayb121** [comment]
You not going to reply?

**Comment by luyx2412** [comment]
Hi @lakshayb121 Sorry about reply you late. Please follow the article to fix your issue https://github.com/flutter/flutter/issues/23777

Thanks

**Comment by minhcasi** [comment]
@lakshayb121 - pls give a try with latest release 1.7.7 - thanks

**Comment by lakshayb121** [comment]
> @lakshayb121 - pls give a try with latest release 1.7.7 - thanks

Ok i will try

**Comment by lakshayb121** [comment]
@luyx2412 @minhcasi Hi i want to remove this part how can I?![IMG_20200830_153421.jpg](https://user-images.githubusercontent.com/55995898/91656447-62389e00-ead6-11ea-981a-692b0e2174ee.jpg)

**Comment by IbrahimHd** [comment]
Hi @lakshayb121 

You can remove this part from the config file(s):
file: /lib/config/config_xx.json
`      ,
        {
            "name": "Our Blog Posts",
            "layout": "blog"
        }
`

By the way, I'm still facing the error `Codepoint 58848 not found in font, aborting.` even with v1.7.7.   Could you let me how did you fix it?

**Comment by lakshayb121** [comment]
> Hi @lakshayb121 
> 
> You can remove this part from the config file(s):
> file: /lib/config/config_xx.json
> `      ,
>         {
>             "name": "Our Blog Posts",
>             "layout": "blog"
>         }
> `
> 
> By the way, I'm still facing the error `Codepoint 58848 not found in font, aborting.` even with v1.7.7.   Could you let me how did you fix it?

When i remove it from config_xx file the app dont work it stucks at white screen


The error of codepoint is fixed in latest version

**Comment by lakshayb121** [comment]
@luyx2412 what should be the splash screen type if i change it to png file

**Comment by minhcasi** [comment]
@lakshayb121 - please give a try to customize the app UI by using Fluxbuilder tool - http://fluxbuilder.com/ - then copy the content of config json into your app - let us know your checking - thank you!

**Comment by lakshayb121** [comment]
> @lakshayb121 - please give a try to customize the app UI by using Fluxbuilder tool - http://fluxbuilder.com/ - then copy the content of config json into your app - let us know your checking - thank you!
> 
> <blockquote><div><strong><a href="http://fluxbuilder.com/">FluxBuilder - An Ultimate Approach For Flutter Mobile Apps</a></strong></div><div>FluxBuilder is a drag-and-drop tool which guides non-tech users in building their own mobile apps in just 3 simple steps: Integrate, Design and Publish.</div></blockquote>

Thanks this worked for me just tell me about how to change splashscreen when i make it splashscreen.png it is stuck at a white screen when i start the app. I see Thier is an option of splashscreen type="flare" can you tell me what should be the splashscreen type?

**Comment by IbrahimHd** [comment]
`const kSplashScreenType = 'static'`

**Comment by lakshayb121** [comment]
> `const kSplashScreenType = "static";`

Thanks this works

**Comment by lakshayb121** [comment]
Can i use dark theme as initial theme and if user want they can change to light theme? And can remove left drawer menu?

**Comment by lakshayb121** [comment]
![Screenshot_2020-08-31-00-30-58-90_2718f369eb4146d6b352274f60f83e87.jpg](https://user-images.githubusercontent.com/55995898/91667321-4f978680-eb21-11ea-9fff-bfeda5db5017.jpg)

Getting this error when clicking on checkout please give solution

**Comment by mwambajoshua** [comment]
hello I am also facing this issue when I run - flutter build apk 

 **Codepoint 58848 not found in font, aborting.**
Any solutions yet? I guess something to do with _MaterialIcons.ttf_ file?

**Comment by lakshayb121** [comment]
> hello I am also facing this issue when I run - flutter build apk 
> 
>  **Codepoint 58848 not found in font, aborting.**
> Any solutions yet? I guess something to do with _MaterialIcons.ttf_ file?
> 
> 

This is solved in latest version

**Comment by minhcasi** [comment]
@lakshayb121 - let us know if you have any further question - thank you!

**Comment by lakshayb121** [comment]
> @lakshayb121 - let us know if you have any further question - thank you!

Are you guys crazy i have asked so many questions above and you just close this issue. Worst support ever faced.
