### ISSUE TITLE
Error after compile to apk project

### ISSUE THREAD

**Issue by twt93** [inspireui/support#4714]
Can you help me... i get error after compile![Screenshot_20200823-192113.jpg](https://user-images.githubusercontent.com/29052044/90977179-fbffc880-e575-11ea-8912-304979856c78.jpg)

**Comment by vumanhsn97** [comment]
@twt93 
Can you share your config.json file?

**Comment by minhcasi** [comment]
@twt93 - pls fix by using this solution https://github.com/inspireui/support/issues/4638 - thanks
