### ISSUE TITLE
category issue

### ISSUE THREAD

**Issue by ammarsowaid** [inspireui/support#4715]
i have connected fluxstore to my opencart 2.2.0.0 website but and changed the categories ID in the json file to match my categories but the app shows no product

+ Detail Issues: the categories do not show in the app
- [ ] first issue
- [ ] second issue
- [ ] third issue

+ fluxstore 17.6
+ Flutter  version: 17.5
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

![2020-08-23 (2)](https://user-images.githubusercontent.com/14929672/90979450-cbac3000-e55d-11ea-9d8e-4ac848610627.png)
![2020-08-23](https://user-images.githubusercontent.com/14929672/90979454-cd75f380-e55d-11ea-90d8-443e65561f63.png)
![2020-08-23 (1)](https://user-images.githubusercontent.com/14929672/90979457-d1a21100-e55d-11ea-9117-2f8559279204.png)

**Comment by minhtruong315** [comment]
@ammarsowaid can u send me common folder?
Thanks

**Comment by ammarsowaid** [comment]
> @ammarsowaid can u send me common folder?
> Thanks

ok
[common.zip](https://github.com/inspireui/support/files/5130782/common.zip)

**Comment by ammarsowaid** [comment]
> @ammarsowaid can u send me common folder?
> Thanks
this is the common folder
[common.zip](https://github.com/inspireui/support/files/5130807/common.zip)

**Comment by minhtruong315** [comment]
Hi @ammarsowaid did you change category ID in config_en.json? please send it to me.
Thanks

**Comment by ammarsowaid** [comment]
> Hi @ammarsowaid did you change category ID in config_en.json? please send it to me.
> Thanks

yes i change it

 {
  "HorizonLayout": [
    {
      "layout": "logo",
      "showMenu": true,
      "showSearch": true,
      "showLogo": true
    },
    {
      "layout": "bannerImage",
      "isSlider": true,
      "autoPlay": false,


      "items": [
        {
          "product": 9237,
          "image": "https://sowaid.com/benner/New%20folder/benner5.png",
          "padding": 15.0
        },
        {
          "category": 20,
          "image": "https://sowaid.com/benner/New%20folder/benner1.png",
          "padding": 15.0
        },
        {
          "category": 18,
          "image": "https://sowaid.com/benner/New%20folder/benner2.png",
          "padding": 15.0
        }
      ]
    },
    {
      "layout": "bannerImage",
      "items": [
        {
          "category": 25,
          "image": "https://sowaid.com/benner/New%20folder/benner3.png",
          "padding": 5.0
        }
      ]
    },
    {
      "layout": "bannerImage",
      "items": [
        {
          "category": 57,
          "image": "https://sowaid.com/benner/New%20folder/benner4.png",
          "padding": 5.0
        },
        {
          "category": 24,
          "image": "https://sowaid.com/benner/New%20folder/benner3.png",
          "padding": 5.0
        }
      ]
    },
    {
      "name": "Home Appliances",
      "image": "",
      "layout": "threeColumn",
      "category":"Home Appliances",
      "isSnapping": true
    },
    {
      "name": "Air Conditioning",
      "image": "",
      "layout": "twoColumn",
      "category": "Air Conditioning",

    },
    {
      "name": "Our Blog Posts",
      "layout": "blog"
    }
  ],
  "VerticalLayout": {
    "layout": "pinterest",
    "name": "Recent Collections",
    "image": ""
  },
  "Setting": {
    "MainColor": "#3FC1BE",
    "ProductListLayout": "list",
    "StickyHeader": true
  },
  "TabBar": [{
    "layout": "home",
    "icon": "assets/icons/tabs/icon-home.png"
  },
    {
      "layout": "category",
      "categoryLayout": "card",
      "icon": "assets/icons/tabs/icon-category.png"
    },
    {
      "layout": "search",
      "icon": "assets/icons/tabs/icon-search.png"
    },
    {
      "layout": "cart",
      "icon": "assets/icons/tabs/icon-cart2.png"
    },
    {
      "layout": "profile",
      "icon": "assets/icons/tabs/icon-user.png"
    }
  ],
  "searchSuggestion": [
    "man",
    "dress",
    "Stitch",
    "ma"
  ],
  "OnBoarding": {
    "data": [
      {
        "title": "Welcome to SowaidStore",
        "image": "assets/images/fogg-delivery-1.png",
        "desc": "Sowaidstore is on the way to serve you. ",
        "background": "#FFF3F2"
      },
      {
        "title": "Connect Surrounding World",
        "image": "assets/images/fogg-uploading-1.png",
        "desc": "See all things happening around you just by a click in your phone. Fast, convenient and clean.",
        "background": "#F2FFFC"
      },
      {
        "title": "Let's Get Started",
        "image": "fogg-order-completed.png",
        "desc": "Waiting no more, let's see what we get!",
        "background": "#F9F2FF"
      }
    ]
  }
}

**Comment by ammarsowaid** [comment]
> Hi @ammarsowaid did you change category ID in config_en.json? please send it to me.
> Thanks

Yes I have change it 
 
 
 
 
 
{
"HorizonLayout": [
{
"layout": "logo",
"showMenu": true,
"showSearch": true,
"showLogo": true
},
{
"layout": "bannerImage",
"isSlider": true,
"autoPlay": false,
  "items": [
    {
      "product": 9237,
      "image": "https://sowaid.com/benner/New%20folder/benner5.png",
      "padding": 15.0
    },
    {
      "category": 20,
      "image": "https://sowaid.com/benner/New%20folder/benner1.png",
      "padding": 15.0
    },
    {
      "category": 18,
      "image": "https://sowaid.com/benner/New%20folder/benner2.png",
      "padding": 15.0
    }
  ]
},
{
  "layout": "bannerImage",
  "items": [
    {
      "category": 25,
      "image": "https://sowaid.com/benner/New%20folder/benner3.png",
      "padding": 5.0
    }
  ]
},
{
  "layout": "bannerImage",
  "items": [
    {
      "category": 57,
      "image": "https://sowaid.com/benner/New%20folder/benner4.png",
      "padding": 5.0
    },
    {
      "category": 24,
      "image": "https://sowaid.com/benner/New%20folder/benner3.png",
      "padding": 5.0
    }
  ]
},
{
  "name": "Home Appliances",
  "image": "",
  "layout": "threeColumn",
  "category":"Home Appliances",
  "isSnapping": true
},
{
  "name": "Air Conditioning",
  "image": "",
  "layout": "twoColumn",
  "category": "Air Conditioning",
 
},
{
  "name": "Our Blog Posts",
  "layout": "blog"
}
],
"VerticalLayout": {
"layout": "pinterest",
"name": "Recent Collections",
"image": ""
},
"Setting": {
"MainColor": "#3FC1BE",
"ProductListLayout": "list",
"StickyHeader": true
},
"TabBar": [{
"layout": "home",
"icon": "assets/icons/tabs/icon-home.png"
},
{
"layout": "category",
"categoryLayout": "card",
"icon": "assets/icons/tabs/icon-category.png"
},
{
"layout": "search",
"icon": "assets/icons/tabs/icon-search.png"
},
{
"layout": "cart",
"icon": "assets/icons/tabs/icon-cart2.png"
},
{
"layout": "profile",
"icon": "assets/icons/tabs/icon-user.png"
}
],
"searchSuggestion": [
"man",
"dress",
"Stitch",
"ma"
],
"OnBoarding": {
"data": [
{
"title": "Welcome to SowaidStore",
"image": "assets/images/fogg-delivery-1.png",
"desc": "Sowaidstore is on the way to serve you. ",
"background": "#FFF3F2"
},
{
"title": "Connect Surrounding World",
"image": "assets/images/fogg-uploading-1.png",
"desc": "See all things happening around you just by a click in your phone. Fast, convenient and clean.",
"background": "#F2FFFC"
},
{
"title": "Let's Get Started",
"image": "fogg-order-completed.png",
"desc": "Waiting no more, let's see what we get!",
"background": "#F9F2FF"
}
]
}
}
 
 
Sent from Mail for Windows 10
 
 
From: GitHub <noreply@github.com>
Sent: Friday, August 28, 2020 6:54:46 PM
To: ammar sowaid <ammarsowaid@hotmail.com>
Subject: [GitHub] Please verify your device 
 
Hey ammarsowaid!

A sign in attempt requires further verification because we did not recognize your device. To complete the sign in, enter the verification code on the unrecognized device.

Device: Chrome on Windows
Verification code: 380826

If you did not attempt to sign in to your account, your password may be compromised. Visit https://github.com/settings/security to create a new, strong password for your GitHub account.

If you'd like to automatically verify devices in the future, consider enabling two-factor authentication on your account. Visit https://docs.github.com/articles/configuring-two-factor-authentication to learn about two-factor authentication.

If you decide to enable two-factor authentication, ensure you retain access to one or more account recovery methods. See https://docs.github.com/articles/configuring-two-factor-authentication-recovery-methods in the GitHub Help.

Thanks,
The GitHub Team

**Comment by ammarsowaid** [comment]
> Hi @ammarsowaid did you change category ID in config_en.json? please send it to me.
> Thanks

Yes I have change it 
 
 
 
 
 
{
"HorizonLayout": [
{
"layout": "logo",
"showMenu": true,
"showSearch": true,
"showLogo": true
},
{
"layout": "bannerImage",
"isSlider": true,
"autoPlay": false,
  "items": [
    {
      "product": 9237,
      "image": "https://sowaid.com/benner/New%20folder/benner5.png",
      "padding": 15.0
    },
    {
      "category": 20,
      "image": "https://sowaid.com/benner/New%20folder/benner1.png",
      "padding": 15.0
    },
    {
      "category": 18,
      "image": "https://sowaid.com/benner/New%20folder/benner2.png",
      "padding": 15.0
    }
  ]
},
{
  "layout": "bannerImage",
  "items": [
    {
      "category": 25,
      "image": "https://sowaid.com/benner/New%20folder/benner3.png",
      "padding": 5.0
    }
  ]
},
{
  "layout": "bannerImage",
  "items": [
    {
      "category": 57,
      "image": "https://sowaid.com/benner/New%20folder/benner4.png",
      "padding": 5.0
    },
    {
      "category": 24,
      "image": "https://sowaid.com/benner/New%20folder/benner3.png",
      "padding": 5.0
    }
  ]
},
{
  "name": "Home Appliances",
  "image": "",
  "layout": "threeColumn",
  "category":"Home Appliances",
  "isSnapping": true
},
{
  "name": "Air Conditioning",
  "image": "",
  "layout": "twoColumn",
  "category": "Air Conditioning",
 
},
{
  "name": "Our Blog Posts",
  "layout": "blog"
}
],
"VerticalLayout": {
"layout": "pinterest",
"name": "Recent Collections",
"image": ""
},
"Setting": {
"MainColor": "#3FC1BE",
"ProductListLayout": "list",
"StickyHeader": true
},
"TabBar": [{
"layout": "home",
"icon": "assets/icons/tabs/icon-home.png"
},
{
"layout": "category",
"categoryLayout": "card",
"icon": "assets/icons/tabs/icon-category.png"
},
{
"layout": "search",
"icon": "assets/icons/tabs/icon-search.png"
},
{
"layout": "cart",
"icon": "assets/icons/tabs/icon-cart2.png"
},
{
"layout": "profile",
"icon": "assets/icons/tabs/icon-user.png"
}
],
"searchSuggestion": [
"man",
"dress",
"Stitch",
"ma"
],
"OnBoarding": {
"data": [
{
"title": "Welcome to SowaidStore",
"image": "assets/images/fogg-delivery-1.png",
"desc": "Sowaidstore is on the way to serve you. ",
"background": "#FFF3F2"
},
{
"title": "Connect Surrounding World",
"image": "assets/images/fogg-uploading-1.png",
"desc": "See all things happening around you just by a click in your phone. Fast, convenient and clean.",
"background": "#F2FFFC"
},
{
"title": "Let's Get Started",
"image": "fogg-order-completed.png",
"desc": "Waiting no more, let's see what we get!",
"background": "#F9F2FF"
}
]
}
}

**Comment by minhtruong315** [comment]
@ammarsowaid please use this config_en.json and try again
```
{
  "HorizonLayout": [
    {
      "layout": "logo",
      "showMenu": true,
      "showSearch": true,
      "showLogo": true
    },
    {
      "layout": "bannerImage",
      "isSlider": true,
      "autoPlay": false,
      "items": [
        {
          "product": 9237,
          "image": "https://sowaid.com/benner/New%20folder/benner5.png",
          "padding": 15.0
        },
        {
          "category": 20,
          "image": "https://sowaid.com/benner/New%20folder/benner1.png",
          "padding": 15.0
        },
        {
          "category": 18,
          "image": "https://sowaid.com/benner/New%20folder/benner2.png",
          "padding": 15.0
        }
      ]
    },
    {
      "layout": "bannerImage",
      "items": [
        {
          "category": 25,
          "image": "https://sowaid.com/benner/New%20folder/benner3.png",
          "padding": 5.0
        }
      ]
    },
    {
      "layout": "bannerImage",
      "items": [
        {
          "category": 57,
          "image": "https://sowaid.com/benner/New%20folder/benner4.png",
          "padding": 5.0
        },
        {
          "category": 24,
          "image": "https://sowaid.com/benner/New%20folder/benner3.png",
          "padding": 5.0
        }
      ]
    },
    {
      "name": "Home Appliances",
      "image": "",
      "layout": "threeColumn",
      "category":"Home Appliances",
      "isSnapping": true
    },
    {
      "name": "Air Conditioning",
      "image": "",
      "layout": "twoColumn",
      "category": "Air Conditioning"
    },
    {
      "name": "Our Blog Posts",
      "layout": "blog"
    }
  ],
  "VerticalLayout": {
    "layout": "pinterest",
    "name": "Recent Collections",
    "image": ""
  },
  "Setting": {
    "MainColor": "#3FC1BE",
    "ProductListLayout": "list",
    "StickyHeader": true
  },
  "TabBar": [{
    "layout": "home",
    "icon": "assets/icons/tabs/icon-home.png"
  },
    {
      "layout": "category",
      "categoryLayout": "card",
      "icon": "assets/icons/tabs/icon-category.png"
    },
    {
      "layout": "search",
      "icon": "assets/icons/tabs/icon-search.png"
    },
    {
      "layout": "cart",
      "icon": "assets/icons/tabs/icon-cart2.png"
    },
    {
      "layout": "profile",
      "icon": "assets/icons/tabs/icon-user.png"
    }
  ],
  "searchSuggestion": [
    "man",
    "dress",
    "Stitch",
    "ma"
  ],
  "OnBoarding": {
    "data": [
      {
        "title": "Welcome to SowaidStore",
        "image": "assets/images/fogg-delivery-1.png",
        "desc": "Sowaidstore is on the way to serve you. ",
        "background": "#FFF3F2"
      },
      {
        "title": "Connect Surrounding World",
        "image": "assets/images/fogg-uploading-1.png",
        "desc": "See all things happening around you just by a click in your phone. Fast, convenient and clean.",
        "background": "#F2FFFC"
      },
      {
        "title": "Let's Get Started",
        "image": "fogg-order-completed.png",
        "desc": "Waiting no more, let's see what we get!",
        "background": "#F9F2FF"
      }
    ]
  }
}
```

**Comment by minhtruong315** [comment]
![Simulator Screen Shot - iPhone 11 - 2020-08-31 at 11 39 04](https://user-images.githubusercontent.com/10402500/91683354-95cf0300-eb7e-11ea-9499-38dc49401117.png)
it's showing products now. 
if you change the language to Arabic. you must update config_ar.json as well.

**Comment by ammarsowaid** [comment]
> ![Simulator Screen Shot - iPhone 11 - 2020-08-31 at 11 39 04](https://user-images.githubusercontent.com/10402500/91683354-95cf0300-eb7e-11ea-9499-38dc49401117.png)
> it's showing products now.
> if you change the language to Arabic. you must update config_ar.json as well.

how about this error 
![2020-09-01 (1)](https://user-images.githubusercontent.com/14929672/91856858-c6db3080-ec6f-11ea-881c-2abbcc1b06d5.png)
![2020-09-01](https://user-images.githubusercontent.com/14929672/91856859-c6db3080-ec6f-11ea-903e-76aa6bb020e4.png)

**Comment by ammarsowaid** [comment]
> ![Simulator Screen Shot - iPhone 11 - 2020-08-31 at 11 39 04](https://user-images.githubusercontent.com/10402500/91683354-95cf0300-eb7e-11ea-9499-38dc49401117.png)
> it's showing products now.
> if you change the language to Arabic. you must update config_ar.json as well.

can you give the user and pass of the demo in opencart

**Comment by ammarsowaid** [comment]
> > ![Simulator Screen Shot - iPhone 11 - 2020-08-31 at 11 39 04](https://user-images.githubusercontent.com/10402500/91683354-95cf0300-eb7e-11ea-9499-38dc49401117.png)
> > it's showing products now.
> > if you change the language to Arabic. you must update config_ar.json as well.
> 
> can you give me the user and pass of the demo in opencart

**Comment by minhtruong315** [comment]
> > ![Simulator Screen Shot - iPhone 11 - 2020-08-31 at 11 39 04](https://user-images.githubusercontent.com/10402500/91683354-95cf0300-eb7e-11ea-9499-38dc49401117.png)
> > it's showing products now.
> > if you change the language to Arabic. you must update config_ar.json as well.
> 
> how about this error
> ![2020-09-01 (1)](https://user-images.githubusercontent.com/14929672/91856858-c6db3080-ec6f-11ea-881c-2abbcc1b06d5.png)
> ![2020-09-01](https://user-images.githubusercontent.com/14929672/91856859-c6db3080-ec6f-11ea-903e-76aa6bb020e4.png)

send me config_ar.json to me check

**Comment by minhtruong315** [comment]
@ammarsowaid how?

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
