### ISSUE TITLE
Pub get issue

### ISSUE THREAD

**Issue by winworld** [inspireui/support#4717]
Hi there

I am getting the following error when build. Can anyone help, please?

https://www.screencast.com/t/tbTqCKNJpO

Thanks

**Comment by minhcasi** [comment]
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
@winworld - this is just the warning, we use this solution to fix the issue from svg library - please ignore the warning if you could build the app normally

**Comment by winworld** [comment]
Still I cannot build the app. 
Here's my step..
I create a new Flutter application. 
Copy your source directory. 
then do pub get and iam getting the following error. 
https://www.screencast.com/t/NGpvb8EMWhQ9

**Comment by winworld** [comment]
i am also getting this error
==
Your Flutter application is created using an older version of the Android embedding. It's being deprecated in favor of Android embedding v2. Follow the steps on https://flutter.dev/go/android-project-migration to migrate your project.

**Comment by minhcasi** [comment]
@winworld - pls try to update to flutter stable channel by running this script
```
flutter channel stable
flutter upgrade --force
```

Also, try to clean the cache by following this guide https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1 - thank you!

**Comment by minhcasi** [comment]
Let us know if you have any update - thank you!

**Comment by winworld** [comment]
That seems working.. Somehow, I cannot install the app on my phone which got Android version 10. Is that the issue.??
