### ISSUE TITLE
Pub Get Not working

### ISSUE THREAD

**Issue by silamutungi** [inspireui/support#4718]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 

Because every version of flutter_test from sdk depends on vector_math 2.1.0-nullsafety.2 and fstore depends on vector_math 2.0.8, flutter_test from sdk is forbidden.
So, because fstore depends on flutter_test any from sdk, version solving failed.
pub get failed (1; So, because fstore depends on flutter_test any from sdk, version solving failed.)
Process finished with exit code 1

Can not get past this step although I have set up Flutter SDK in preference as Instructed
<img width="1014" alt="Screen Shot 2020-08-23 at 10 12 58 AM" src="https://user-images.githubusercontent.com/7536714/90984363-3bec8e80-e529-11ea-8ee2-56a453c52da5.png">

+ Product & version:
FluxStore-listing 1.4.3
+ Flutter (or React Native) version: 
Flutter
+ Testing Device/Simulator: 
Android 
+ Screenshot issues (drag the file to attach here): 
<img width="673" alt="Screen Shot 2020-08-23 at 10 11 46 AM" src="https://user-images.githubusercontent.com/7536714/90984334-0f387700-e529-11ea-9d78-e463bd06134b.png">

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com **

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@silamutungi - pls try to use the flutter stable - using dev channel is not recommend

```
flutter stable channel
flutter upgrade --force
```

**Comment by silamutungi** [comment]
How do I change from Dev channel to Stable

**Comment by minhcasi** [comment]
you could run above script 👆

or reinstall from this guide - https://flutter.dev/docs/get-started/install/macos#get-sdk - latest stable is `1.20.x`

**Comment by silamutungi** [comment]
@minhcasi I"m getting this new error:
Warning: You are using these overridden dependencies:
! flutter_svg 0.18.0
