### ISSUE TITLE
The purchase code is incorrect.

### ISSUE THREAD

**Issue by MH-sabu** [inspireui/support#4719]
When i try to put purchase code in the Mstore Api Plugin error pops up as "The purchase code is incorrect." with an error showing "string(94) "{"error":"Please fill the Email and App Name, also update to the latest Fluxbuilder release!"}""
why is this happening ?
can you please help me.
Thanks

**Comment by minhcasi** [comment]
@MH-sabu - could i know if you are using latest mstore-api? thanks

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by MH-sabu** [comment]
my mstore-api version 2.2.0

**Comment by minhcasi** [comment]
@MH-sabu - pls try to update the latest mstore-api and active the purchase code from plugin setting to active the API - thank you!

**Comment by minhcasi** [comment]
Let us know if you have any update - thank you!

**Comment by MH-sabu** [comment]
> 
> 
> Let us know if you have any update - thank you!

Is there any other way without Updating latest mstore-api? Thank you!

**Comment by MH-sabu** [comment]
> 
> 
> Let us know if you have any update - thank you!

Mstore-api has been updated but I am facing another problem, I had used the purchase code in a site named www.vendorapp.mydomain.com( wordpress multisite) , this domain is  changed into modestgirls.shop and template has been updated so data is deleted. now when i am using the purchase code in modestgirls.shop it is showing that the code is used in www.vendorapp.mydomain.com. what can i do now? please help. thank you
@minhcasi

**Comment by minhcasi** [comment]
@MH-sabu - could you try to reset the purchase code - https://docs.inspireui.com/fluxbuilder/guide-to-use/#deactivate-the-purchase-code and update to new domain - thank you!

**Comment by MH-sabu** [comment]
> 
> 
> @MH-sabu - could you try to reset the purchase code - https://docs.inspireui.com/fluxbuilder/guide-to-use/#deactivate-the-purchase-code and update to new domain - thank you!
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/c1f5c35bdee2cf5a71b0e35ef38becdf8ec89d72/68747470733a2f2f646f63732e696e737069726575692e636f6d2f696d616765732f6d6574612f47686f73742d446f63732e6a7067"><img alt="" height="14" src="/favicon-32x32.png?v=018eb54c8a1daacdda1176a4d241e62d"> InspireUI Document**[FluxBuilder - A greatest tool for Flutter apps as Fluxstore Pro, Fluxstore Woocommerce, Fluxstore Listing, Fluxstore Multi Vendor, FluxNews, Fluxstore Shopify](https://docs.inspireui.com/fluxbuilder/guide-to-use/)**FluxBuilder is a drag-and-drop tool which guides non-tech users in building their own mobile apps in just 3 simple steps: Integrate, Design and Publish

![Annotation 2020-08-28 135204](https://user-images.githubusercontent.com/14260461/91535921-b9533d00-e935-11ea-9391-74146e6095be.png)
no publish option and deactivate option @minhcasi

**Comment by MH-sabu** [comment]
> 
> 
> @MH-sabu - could you try to reset the purchase code - https://docs.inspireui.com/fluxbuilder/guide-to-use/#deactivate-the-purchase-code and update to new domain - thank you!
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/c1f5c35bdee2cf5a71b0e35ef38becdf8ec89d72/68747470733a2f2f646f63732e696e737069726575692e636f6d2f696d616765732f6d6574612f47686f73742d446f63732e6a7067"><img alt="" height="14" src="/favicon-32x32.png?v=018eb54c8a1daacdda1176a4d241e62d"> InspireUI Document**[FluxBuilder - A greatest tool for Flutter apps as Fluxstore Pro, Fluxstore Woocommerce, Fluxstore Listing, Fluxstore Multi Vendor, FluxNews, Fluxstore Shopify](https://docs.inspireui.com/fluxbuilder/guide-to-use/)**FluxBuilder is a drag-and-drop tool which guides non-tech users in building their own mobile apps in just 3 simple steps: Integrate, Design and Publish

![Annotation 2020-08-28 135204 (2)](https://user-images.githubusercontent.com/14260461/91538138-27e5ca00-e939-11ea-9c04-13367ea9326b.png)
no publish option and no deactivate option @minhcasi

**Comment by minhcasi** [comment]
@MH-sabu - pls select Build menu

Btw, we have reset it - pls check again

**Comment by minhcasi** [comment]
Let us know your checking - thanks

**Comment by MH-sabu** [comment]
> 
> 
> Let us know your checking - thanks

problem solve, thank you @minhcasi
