### ISSUE TITLE
Shipping address

### ISSUE THREAD

**Issue by ap26091995** [inspireui/support#4721]
After complete my order and payment, when i view my order in order history the shipping address is not showing. But on opencart backend my order is showing with billing address. and sometime some of fields not updated.

**Comment by minhcasi** [comment]
@ap26091995 - could you share the screenshot issues on both app and website so that we could reproduce the issues - thanks

**Comment by ap26091995** [comment]
You can see no shipping address shows below title in app. Where in website there is shipping address shows.but phone number which i enter in address field is not the same its show 123 in phone number
![Screenshot 2020-08-24 at 7 11 11 PM](https://user-images.githubusercontent.com/50094453/91120656-c82abd00-e6b3-11ea-850c-bd3704856e0c.png)
.
![Simulator Screen Shot - iPhone 11 Pro - 2020-08-25 at 09 15 05](https://user-images.githubusercontent.com/50094453/91120531-839f2180-e6b3-11ea-9e7c-6ae90a32e683.png)

**Comment by ap26091995** [comment]
![Simulator Screen Shot - iPhone 11 Pro - 2020-08-25 at 09 18 27](https://user-images.githubusercontent.com/50094453/91120722-f5776b00-e6b3-11ea-837d-784915ad04e7.png)

**Comment by ap26091995** [comment]
In woocommerce its showing shipping details but when its opencart its not showing.

**Comment by ap26091995** [comment]
Please help me in this

**Comment by minhtruong315** [comment]
[mstore.ocmod.zip](https://github.com/inspireui/support/files/5133383/mstore.ocmod.zip)
@ap26091995 please install mstore extension and try again
