### ISSUE TITLE
Exception caught by rendering library

### ISSUE THREAD

**Issue by tahype** [inspireui/support#4722]
**_Step 1 (require): is not showing the images of the list (internal) the grid is wrong. dont show the maps, features etc of the list
+ Detail Issues: https://prnt.sc/u4zyp3
- [ ] first issue: he following assertion was thrown building Consumer<CategoryModel>(dirty, dependencies: [_InheritedProviderScope<CategoryModel>]):
A build function returned null.

The offending widget is: Consumer<CategoryModel>
Build functions must never return null.

To return an empty space that causes the building widget to fill available room, return "Container()". To return an empty space that takes as little room as possible, return "Container(width: 0.0, height: 0.0)".

The relevant error-causing widget was: 
  Consumer<CategoryModel> file:///D:/Nova/Blumenau/app/FluxStore-listing%201.4.3/source/lib/widgets/backdrop_menu.dart:42:16
When the exception was thrown, this was the stack: 
#0      debugWidgetBuilderValue.<anonymous closure> (package:flutter/src/widgets/debug.dart:300:7)
#1      debugWidgetBuilderValue (package:flutter/src/widgets/debug.dart:321:4)
#2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4551:7)
#3      Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#4      StatelessElement.update (package:flutter/src/widgets/framework.dart:4627:5)
...

**- [ ] second issue:** ════════ Exception caught by rendering library ═════════════════════════════════════════════════════
'package:flutter/src/rendering/box.dart': Failed assertion: line 322 pos 12: 'width > 0.0': is not true.
The relevant error-causing widget was: 
  FittedBox file:///D:/Nova/Blumenau/app/FluxStore-listing%201.4.3/source/lib/widgets/product/product_list.dart:138:36

- [ ] third issue: I/flutter (11266): err when parsed json MyListing type 'List<dynamic>' is not a subtype of type 'Map<dynamic, dynamic>'

+ Product & version: Fluxstore Listing app Flutter: 1.4.3
+ Flutter (or React Native) version: Flutter
+ Testing Device/Simulator: AV and Moto G8 Power
+ Screenshot issues (drag the file to attach here): https://prnt.sc/u4zyp3 , https://prnt.sc/u5011w , https://prnt.sc/u501eg

![image](https://user-images.githubusercontent.com/70150637/91055331-e08ad100-e5fa-11ea-9e76-c59b58a768be.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com **

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@tahype - thank you for reporting the issue - we will investigate and let you know with the solution - very best!

**Comment by tahype** [comment]
> @tahype - thank you for reporting the issue - we will investigate and let you know with the solution - very best!

Hi, any solution?

**Comment by vumanhsn97** [comment]
@tahype 
Try to replace files in this attachment: 
[archive.zip](https://github.com/inspireui/support/files/5128235/archive.zip)

**Comment by tahype** [comment]
It works, thanks 👍
