### ISSUE TITLE
REST-API OnePageCheckout Cart mixing between users

### ISSUE THREAD

**Issue by glamble007** [inspireui/support#4723]
When multiple customers try to checkout on OnePageCheckout, the cart of admin account (API key account) + another customer's is SAME. Cart is getting MIXED. How can you publish such a buggy app? Try login with any customer-account. REST-API key is of admin anyway. 

Try checkout 100 times – all-time admin cart has customer cart items.

Its a serious bug because when 3 customers try checkout, their carts can mix. Orders can get wrong. HORRIBLE !!

Step to reproduce:
Configure app. Add admin consumer & secret key of woocommerce.
Enable OnePageCheckout.
Build the app. Login any normal customer account.
Add product to cart and go to the checkout page.
WAIT THERE.

Now open the normal browser, login to admin account (from where api-key is generated).
Go to CART PAGE.
You will see the same items in the cart as the customer has on mobile.

Login on the other phone with the customer-2 account, and try checkout.
SAME ITEMS in admin cart, customer 1 cart, and customer-2 cart!!!

The app has 2000 customers and downloads, are you serious about such a bug?!

**Comment by ameenbadri7** [comment]
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
@glamble007 - we suggest using a positive world on your comments, we are willing to support with the fixing with contribution spirit.

If you have a screenshot that would be great to troubleshoot the issues.

**Comment by glamble007** [comment]
Guy, I am wanting to be positive. But I cannot entertain this when my dozen customers have suffered. I cannot provide them solution because we do not know their cart items, we do not know what happened. They spend 30 mins to prepare 1 cart, and then on payment they see different items.

They come to us complaining and spread bad word on social media.

First you face this, and then try be positive.

**Comment by glamble007** [comment]
@minhcasi SPAM Warning? Are you mad? Just follow the steps and you can SEE IT!
This author is full of shit. There is a serious bug and he is closing the ticket, instead of talking properly and fixing it.

**Comment by glamble007** [comment]
[](url)

> @glamble007 - we suggest using a positive world on your comments, we are willing to support with the fixing with contribution spirit.
> 
> If you have a screenshot that would be great to troubleshoot the issues.

If you were willing to support, do not close the ticket. I have provided steps to reproduce.

You have to login in customer account on app. Add items to cart and go to OnePageCheckout (webview).
On the browser, go to the admin account from where the rest-api key were generated and check the cart. It will be same as the above customer account's cart.
