### ISSUE TITLE
Fluxshopify Products and Product Variation add to cart..

### ISSUE THREAD

**Issue by hamzachughtai** [inspireui/support#4724]
Hey there,
1- Products on vertical list on home page not displaying prices... Products when adding into cart from the product card cart icon giving issue of null at checkout seems like problem with variations.. Android app going blank when opening products or a page twice..
2-Tiles on flux builder not displaying properly...
3- FluxShopify does have one page checkout..?

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com **

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by hamzachughtai** [comment]
https://verify.inspireui.com/ not working giving error of invalid ssl

**Comment by ameenbadri7** [comment]
It's working I just try it now.
You could change the browser to other like firefox or safari.

**Comment by hamzachughtai** [comment]
verify.inspireui.com normally uses encryption to protect your information. When Google Chrome tried to connect to verify.inspireui.com this time, the website sent back unusual and incorrect credentials. This may happen when an attacker is trying to pretend to be verify.inspireui.com, or a Wi-Fi sign-in screen has interrupted the connection. Your information is still secure because Google Chrome stopped the connection before any data was exchanged.

**Comment by hamzachughtai** [comment]
On chrome its giving out this error and I tried on Opera firefox error with option to proceed...

**Comment by minhcasi** [comment]
@hamzachughtai - no worries, we got the verify info on the previous ticket - thanks

@luyx2412 - please help to investigate this issues

**Comment by hamzachughtai** [comment]
Thanks Minhcasi for verification

**Comment by luyx2412** [comment]
Hi @hamzachughtai Can i ask about the issues, everything issues related fluxbuilder?

Thanks

**Comment by hamzachughtai** [comment]
1.
![3](https://user-images.githubusercontent.com/50984924/91230761-85192a00-e745-11ea-99f5-b5fced8b1539.png)
2.
![1](https://user-images.githubusercontent.com/50984924/91230763-86e2ed80-e745-11ea-90cf-a5efbf7fdc6e.png)
3.
![2](https://user-images.githubusercontent.com/50984924/91230769-88141a80-e745-11ea-8c69-992a7bd58c5c.png)

**Comment by hamzachughtai** [comment]
1. Flux builder list tiles not working and also vertical layout is not saving I have used coding to get vertical layout provided in the docs but flux builder not saving that option.
2. Price not displaying on product cart of vertical checkout
3. Mobile app added product via cart icon on the product cards not going through checkout (seems like product variation or id going null.)
4. Loading product category page or product pages twice will make app go blank on ANDROID DEVICES and sometimes tabs also gone blank... 

Questions about features:
1. Is one page checkout is available in flux shopify mobile app...? if yes please provide link to reference doc.
2. In flutter we can stick a container on top of any section is it possible to do the same with vertical layout home page categories..?

**MOST IMPORTANT**

1. Version or Channel of flutter you used to build ios and android (In some issues that I encountered I found the issue is just the channel used to compile the builds)
2. Versions of Xcode & Android you used

**Comment by hamzachughtai** [comment]
I was also facing font tree shaking build faild when trying to build ios which I encountered with
flutter build ios --no-tree-shake-icons

But can you suggest me more better solution for this...

**Comment by hamzachughtai** [comment]
Anything on these issues and queries...

**Comment by hamzachughtai** [comment]
I have not tested the new release fully but ajax cart is still giving null value at checkout

**Comment by minhcasi** [comment]
Please also give a try with the latest release 1.7.7 - thank you!

**Comment by hamzachughtai** [comment]
I have tested the latest release and ajax cart issue still presist please check the variation which is going null in cart

**Comment by minhcasi** [comment]
@luyx2412 - pls help to verify this remain issues

**Comment by luyx2412** [comment]
Hi @hamzachughtai Can you send your project again via inspireui.team@gmail.com. Let me investigate easier. Sorry about inconvenience.

Thanks

**Comment by hamzachughtai** [comment]
I have send my project to you but its the basic one giving this issue like I build and run everything from the release 1.7.7 files and the checkout is going null

**Comment by hamzachughtai** [comment]
I have sent out an email with issues and quries

**Comment by lakshayb121** [comment]
> I have sent out an email with issues and quries

Got any solution for null at checkout?

**Comment by luyx2412** [comment]
Hi @hamzachughtai Sorry about reply you late. I am investigating your project, and reply you soon.
Hi @lakshayb121 Please create your issue, let me support you easier. And please make sure download latest version 1.7.7.

Thanks

**Comment by hamzachughtai** [comment]
Anything on this you told this guy for latest repo
https://github.com/inspireui/support/issues/4863
but not fixed my problem

**Comment by luyx2412** [comment]
HI @hamzachughtai Sorry about mention you again. But can you fill the form again http://verify.inspireui.com/. Because i need your email to invite to the repo which fixed the issue. 

Thanks

**Comment by hamzachughtai** [comment]
Please share this today kindly

**Comment by hamzachughtai** [comment]
Anyone on this

**Comment by minhcasi** [comment]
Our team is checking and will get back to you soon - thank you

@luyx2412

**Comment by hamzachughtai** [comment]
@minhcasi Its been 17 odd days and your team still looking into this and the update you did on the app on 9 Sept still didn't fix the issue and also the address is called nulled error when checking out is a new one...

**Comment by lakshayb121** [comment]
> @minhcasi Its been 17 odd days and your team still looking into this and the update you did on the app on 9 Sept still didn't fix the issue and also the address is called nulled error when checking out is a new one...

Worst support

**Comment by hamzachughtai** [comment]
@minhcasi When you guys will respond...?

**Comment by hamzachughtai** [comment]
I/flutter (10507): [2020-09-10 13:07:20.325548Z][Fluxstore]fromShopifyJson user {id: Z2lkOi8vc2hvcGlmeS9DdXN0b21lci8zOTk4OTgxMDk1NTc3, email: someone@gmail.com, createdAt: 2020-09-10T09:46:03Z, displayName: Test flux, phone: null, firstName: Test, lastName: flux, defaultAddress: null, addresses: {pageInfo: {hasNextPage: false, hasPreviousPage: false}, edges: []}}

Bug at checkout

**Comment by hamzachughtai** [comment]
please can you resolve these issues first they still presist 

> ![3](https://user-images.githubusercontent.com/50984924/91230761-85192a00-e745-11ea-99f5-b5fced8b1539.png)
> 2.
> ![1](https://user-images.githubusercontent.com/50984924/91230763-86e2ed80-e745-11ea-90cf-a5efbf7fdc6e.png)
> 3.
> ![2](https://user-images.githubusercontent.com/50984924/91230769-88141a80-e745-11ea-8c69-992a7bd58c5c.png)

**Comment by luyx2412** [comment]
Hi @hamzachughtai Please send latest source code via inspireui.team@gmail.com with 4724. Or invite to your repo via inspireui.team@gmail.com email. Let me support you easier.

Thanks

**Comment by hamzachughtai** [comment]
Sending right now to the email address its uploading

**Comment by hamzachughtai** [comment]
Send my code to you please respond and dont throw me off with these uploads stuff

**Comment by hamzachughtai** [comment]
Anything on this

**Comment by luyx2412** [comment]
Hi @hamzachughtai I just emailed about the folder, please check it.

Thanks

**Comment by hamzachughtai** [comment]
I/flutter (16573): [2020-09-11 17:08:40.826006Z][Fluxstore]addItemsToCart productsInCart {Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzU1MTUwNDY5MTIxNTM=: 9, Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzU1MTUwNzcxMjQyNDk=: 1}
I/flutter (16573): [2020-09-11 17:08:40.828299Z][Fluxstore]addItemsToCart productVariationInCart {Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzU1MTUwNDY5MTIxNTM=: null, Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzU1MTUwNzcxMjQyNDk=: null}
I/flutter (16573): [2020-09-11 17:08:40.828409Z][Fluxstore]addItemsToCart null
I/flutter (16573): [2020-09-11 17:08:40.828525Z][Fluxstore]::::addItemsToCart shopify error
I/flutter (16573): [2020-09-11 17:08:40.828716Z][Fluxstore]NoSuchMethodError: The getter 'id' was called on null.

When Ajax checkout using cart still not fixed I have raised this 19 days ago man

**Comment by hamzachughtai** [comment]
Okay the fixed you did is removing the address one page checkout completely from the application and giving me what I have didnt fixed anything at all So 19 days wasted Thankyou useless support

**Comment by hamzachughtai** [comment]
One fix is loading price on menu card I must mention 19 days and one issue is fixed well done

**Comment by hamzachughtai** [comment]
I dropped my feedback but Ajax cart still not fixed can you point me in the
right direction? So I can also try to fix this Ajax issue from product card

**Comment by Numan11** [comment]
Hi bro i need your help regarding checkout page i face same issue did you solve this ?

**Comment by luyx2412** [comment]
Hi @hamzachughtai Because you enable the NativeOnePageCheckout. Currently we did not support this payment. Please make sure your payment config like the screenshot to work normal.
![image](https://user-images.githubusercontent.com/8909619/93100704-ada49c00-f6d3-11ea-8c9d-1877711fba9a.png)

Thanks

**Comment by hamzachughtai** [comment]
I didnt you did that in your release and yeah what about ajax checkout from product card why they are still landing to checkout null error Dont do this blaming stuff...

**Comment by luyx2412** [comment]
HI @hamzachughtai Sorry about missing. Please replace this file in `lib/models/cart/cart_model_shopify.dart` to fix the issue.
[cart_model_shopify.dart.zip](https://github.com/inspireui/support/files/5219351/cart_model_shopify.dart.zip)

Thanks for your patient.

**Comment by hamzachughtai** [comment]
Still same issue even worse now Add to Cart is not working... Are you sure you can fix this issue ...? I am in great stress because of you....

**Comment by minhcasi** [comment]
@hamzachughtai - please give a try to follow this guide to merge with the private repo to prevent the customize issue when getting new upgrade - https://medium.com/@inspireui/how-to-upgrade-fluxstore-projects-by-using-git-cebde7489ea6

**Comment by hamzachughtai** [comment]
Can you please invite me to latest repo on gitlab

**Comment by hamzachughtai** [comment]
The one you think is perfectly fine you have my email address....

**Comment by hamzachughtai** [comment]
I confirmed my issues are all resolved
