### ISSUE TITLE
[long text remove]

### ISSUE THREAD

**Issue by alokmalewar** [inspireui/support#4728]
There is no cancel option available in fluxstore woocommerce app if buyer want to cancel his order please solve this issue and why there is the white screen for too muchtime before splash image during loading and how to remove the white screen of loading

+ Detail Issues: 
- [ ] first issue
- [ ] second issue
- [ ] third issue

+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com **

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@alokmalewar - could you share some screenshot/video issues for the splash screen? 

The cancel option is not available on current release - thanks

**Comment by alokmalewar** [comment]
the blank white screen before splash image 
![WhatsApp Image 2020-08-25 at 1 20 33 PM](https://user-images.githubusercontent.com/69632534/91147662-31bbc300-e6d6-11ea-9750-344916a174b7.jpeg)

**Comment by alokmalewar** [comment]
it takes too much time before loading splash image

**Comment by alokmalewar** [comment]
You are saying that the cancel option is not available on your release but we want that option then how we will gonna implement in it.Give us the necessary steps to implement it

**Comment by minhcasi** [comment]
@alokmalewar - you could try to test this feature by enable this option from the config file - so far the Rest API is limited with the Cancel feature without getting approval from the Admin 

<img width="1307" alt="Screen Shot 2020-08-26 at 11 13 49" src="https://user-images.githubusercontent.com/1459805/91254688-38594180-e78d-11ea-9cc8-d5e2c4d496e1.png">

We will investigate the splash image, could i know what type of splash screen have you setup with the app, is it static or animate flare screen?

**Comment by alokmalewar** [comment]
It is animate

**Comment by alokmalewar** [comment]
i have enable the refund cancel from config file but then also i am not getting any option of cancelling the order during processing of the order or completed of the order from user side

**Comment by minhcasi** [comment]
@alokmalewar - could you help to share the Detail Order screen after enabling this option, sir?

**Comment by alokmalewar** [comment]
now the cancel option is enabled thanks sir but what about the splash screen part sir

**Comment by minhcasi** [comment]
i could not reproduce the blank splash screen, what's the type of splash screen you are using? is it static or flare animate? 

you could share the screenshot of your modify splash screen so that we could know the problem

**Comment by alokmalewar** [comment]
there is any option of removing the launch screen

**Comment by alokmalewar** [comment]
one more issue while deactiving the license for another website it is showing error your code has been reseted before please contact support@inspireui.com

**Comment by minhcasi** [comment]
@alokmalewar - we have reset it - pls try again - thanks

**Comment by alokmalewar** [comment]
Thanku sir

**Comment by alokmalewar** [comment]
There is an issue with the categories item it is taking categories from another website on which the  purchase code is previously use and  fluxbuilder is not allowing to deactive the license from the previous website as it is allowing other website to active the license

**Comment by minhcasi** [comment]
@alokmalewar - pls share the screenshot for these issues so that i could forward to the team for checking - thank you!

**Comment by minhcasi** [comment]
Let us know your checking, thank you!

**Comment by alokmalewar** [comment]
that issue is solved when download the latest version of fluxbuilder

**Comment by alokmalewar** [comment]
thanks for your time

**Comment by alokmalewar** [comment]
The Recent View Column Function is not Working  in fluxbuilder .If i try to make a column of recent view in fluxbuilder,the save option button is not working there

**Comment by alokmalewar** [comment]
the app is taking too much time for loading categories and all and after some time it doesnt show anything just blank for that category

**Comment by minhcasi** [comment]
Hi, the Recent View may not work completely on Fluxbuilder as it gets the history of navigation products from the app, you could try to test on the fluxstore app. 

Please help to follow this guide to speed up the app performance - https://docs.inspireui.com/fluxstore/performance/

**Comment by alokmalewar** [comment]
Thanks the performance of app is littlebit improved

**Comment by minhcasi** [comment]
Also try to check the response time from your server-side https://flutter.dev/docs/development/tools/devtools/network

**Comment by alokmalewar** [comment]
ok thanks i will look into it

**Comment by minhcasi** [comment]
Let us know your checking - thank you!

**Comment by alokmalewar** [comment]
yes the speed is increase thanks
