### ISSUE TITLE
[Listapp] error An unexpected error occurred: "EPERM: operation not permitted, scandir

### ISSUE THREAD

**Issue by wcreativo** [inspireui/support#473]
- Product: ListApp
 - Your Purchased Code: 1e6cd72c-1130-4c96-a7f3-0fce5a57062b

**Describe the issues**
error An unexpected error occurred: "EPERM: operation not permitted, scandir

**Screenshots**
https://i.ibb.co/T2qbqLC/EPERM.png

**Comment by thangvo9x** [comment]
please update the latest version of npm package or try using yarn instead of. 
Refer here : https://yarnpkg.com/en/docs/usage
Thanks

**Comment by thangvo9x** [comment]
https://github.com/inspireui/support/issues/472
