### ISSUE TITLE
Component AgendaCalender Not Found

### ISSUE THREAD

**Issue by faisnasrullah** [inspireui/support#4731]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
- [ ] Component AgendaCalender Not Found

+ Product & version: ListApp - Listing Directory Mobile App v1.7.5
+ Flutter (or React Native) version: React Native 
+ Testing Device/Simulator: Android Simulator
+ Screenshot issues (drag the file to attach here):
![ListApp AgendaCalendar Not Found](https://user-images.githubusercontent.com/19532143/91164644-963c4980-e6f9-11ea-99ef-04254991048d.png)

**Comment by minhcasi** [comment]
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by faisnasrullah** [comment]
> Thank you for the feedback.
> Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)
> 
> We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!
> 
> > **[Google Forms - create and analyze surveys, for free.](http://verify.inspireui.com/)**Create a new survey on your own or with others at the same time. Choose from a variety of survey types and analyze results in Google Forms. Free from Google.

Already sent.

**Comment by minhcasi** [comment]
@luyx2412 - pls help to suggest on this issue - thank you!

**Comment by luyx2412** [comment]
Hi @faisnasrullah Please see the screenshot to find this component.
![image](https://user-images.githubusercontent.com/8909619/91633785-520cba00-ea15-11ea-9d84-d569051f82d5.png)

Thanks

**Comment by luyx2412** [comment]
Closed! Because no longer response.

P/S: Feel free to create new issue.
