### ISSUE TITLE
#4632 app rejected due the login with google 

### ISSUE THREAD

**Issue by Shiru-kun** [inspireui/support#4732]
**_Step 1 (require): describe detail issues & screenshots_**
![image](https://user-images.githubusercontent.com/54008441/91166444-ac82df00-e6d2-11ea-9e20-d88ae1af1e5f.png)

+ Detail Issues: 
I just enabled the login with apple in general.dart  but was reject by apple. 
- [ ] first issue
- [ ] second issue
- [ ] third issue

+ Product & version:
Fluxstore MV 1.7.7 
+ Flutter (or React Native) version: 
1.20.1
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com **

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@Shiru-kun - could you share the iPad screenshot login issue (the attachment file from apple)?

**Comment by Shiru-kun** [comment]
@minhcasi check it please 
![attachment 3fa97c8132243e7bf33642fb2934fc49c2218532](https://user-images.githubusercontent.com/54008441/91259572-16e95d00-e76f-11ea-8ae8-2a3acd9358da.png)

**Comment by Shiru-kun** [comment]
@minhcasi check it please 
![1](https://user-images.githubusercontent.com/54008441/91259694-47c99200-e76f-11ea-9a36-784eac531a5d.png)

**Comment by Shiru-kun** [comment]
![image](https://user-images.githubusercontent.com/54008441/91259755-66c82400-e76f-11ea-9633-09c766f5284c.png)

**Comment by minhcasi** [comment]
@tgloc96 - pls suggest on this issue

**Comment by Shiru-kun** [comment]
@tgloc96 @minhcasi  ???

**Comment by minhcasi** [comment]
@Shiru-kun 
We have double-check the latest source and it working fine.

Could you help to zip the source and share to inspireui.team@gmail.com - we will try to reproduce the issues

**Comment by Shiru-kun** [comment]
@minhcasi already it

**Comment by tgloc96** [comment]
Hello @Shiru-kun, Can you add me to your firebase project tgloc96@gmail.com?

**Comment by Shiru-kun** [comment]
@tgloc96 check your email... 
already added

**Comment by Shiru-kun** [comment]
@janiodrey

**Comment by tgloc96** [comment]
> @tgloc96 check your email...
> already added
> whats the role you need on the firebase console?

I need all permissions.

**Comment by Shiru-kun** [comment]
> @tgloc96 Already gave u all permissions 
> 
Check it please....

**Comment by tgloc96** [comment]
@Shiru-kun I configured again some setting on your firebase project, please you download again file GoogleService-Info.plist and override the same file in the project. Notice I see you enable sign-in Google method on the app but you don't enable it on firebase, I have enabled this feature on firebase. If you want to enable Google Sign-in on your app, please configure again info.plist file and set up again for android. But if you don't want to enable the Google Sign-in method on your app, please turn it off on your app if you don't want Apple to reject your app one more time.

**Comment by tgloc96** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
