### ISSUE TITLE
Error With  Fluxbuilder,

### ISSUE THREAD

**Issue by naveenaryag** [inspireui/support#4733]
Dear Team,
I am trying to Use Fluxbuilder, But Getting This error and cant go further
Can you help me with error .?

https://pasteboard.co/Jo0P7PR.png
https://pasteboard.co/JnZqeVJ.png

Thanks

**Comment by minhcasi** [comment]
Duplicate of #4730

**Comment by naveenaryag** [comment]
Kindly Help for this
