### ISSUE TITLE
Console logs are not displayed

### ISSUE THREAD

**Issue by franklinbinauraldev** [inspireui/support#4735]
**Receive a warm greeting**

The logs are not shown, I only get information about the status of the app, surely they have some special configuration to disable this, and that is like a normal project.

I have printed logs all over the code and mine is not showing

I'm using **Mstore pro 4.0.0**

![Captura de pantalla de 2020-08-25 17-49-48](https://user-images.githubusercontent.com/69120282/91231548-6f7f1280-e6fb-11ea-9b41-e8f214e27c3b.png)

**Comment by franklinbinauraldev** [comment]
Regards @luyx2412 

Could you give me an indication of how to print the logs?

I'm printing it in the root of the project in App.js but I don't understand why it doesn't print.

I think there is something blocking that.

The development has really been quite uncomfortable.

Please I need help with this.

**Comment by minhcasi** [comment]
@franklinbinauraldev - could you try to use the flipper debug tool - https://medium.com/@inspireui/mstore-pro-4-0-changelogs-d80d5601ff0a

**Comment by franklinbinauraldev** [comment]
thanks for answering @minhcasi 

I was reviewing the tool and it is good. But it is not printing the console.logs.

I am currently developing on a device, and I have several logs because I have tried several times.

Anyway I show you the information, it is not relevant to locate me in the code.

- On the option **Hermes Debugger (RN)** ![Captura de pantalla de 2020-08-28 11-05-32](https://user-images.githubusercontent.com/69120282/91582900-7afe5380-e91e-11ea-85c5-31bcd0f4d8a5.png)

- **Logs** ![Captura de pantalla de 2020-08-28 11-07-13](https://user-images.githubusercontent.com/69120282/91583100-b4cf5a00-e91e-11ea-8f70-4251cd636657.png)

- On the option **React DevTools** it doesn't work.

On the **Dev Plugin**

- **Logs** - There I used the search engine to find my logs, but i don't find them. 
![Captura de pantalla de 2020-08-28 11-10-48](https://user-images.githubusercontent.com/69120282/91583829-bc433300-e91f-11ea-956f-744a4d5d4f88.png)

I am using MStore-Pro 4.0.0, I really don't understand why printing a log is so complicated. I am almost certain that there is a special setting that prevents my logs. It has nothing to do with Reactotron?

**Comment by luyx2412** [comment]
Hi @franklinbinauraldev Please using the Reactotron to see the log or disable `useReactotron: false` line 13 to see the log.
![image](https://user-images.githubusercontent.com/8909619/91627074-e4459b80-e9de-11ea-9ff2-de6175fede17.png) 

Thanks

**Comment by franklinbinauraldev** [comment]
Hi @luyx2412 

I did what you told me but it still won't print my logs
![Captura de pantalla de 2020-08-28 23-08-07](https://user-images.githubusercontent.com/69120282/91627192-c0a13780-e983-11ea-874d-a4d60e3e5433.png)

But look at this
![Captura de pantalla de 2020-08-28 23-12-01](https://user-images.githubusercontent.com/69120282/91627214-e75f6e00-e983-11ea-9665-4f1681337adb.png)

That information where is being printed?

**Comment by luyx2412** [comment]
Hi @franklinbinauraldev Can you send your project via inspireui.team@gmail.com. Let me investigate about your project, because current our project still see the log.

Thanks

**Comment by luyx2412** [comment]
Closed! Because no longer response.

P/S: Feel free to create new issue.

Thanks
