### ISSUE TITLE
Range Error (index) no loading products

### ISSUE THREAD

**Issue by Priyansu67** [inspireui/support#4736]
I applied all the plugins and regenerated thumbnails still no products are loading in the app and also it shows something called a range error. Everything loads perfectly on Fluxbuilder but after running the source code on android studio products won't load.

+ Product & version: 1.7.7
+ Flutter (or React Native) version: 1.20.2
+ Testing Device/Simulator: Black Shark 2 Android 10 and Emulator Pixel 5 XL Android 9
+ Screenshot issues (drag the file to attach here): 
![Screenshot_2020-08-25-16-18-40-500_com inspireui fluxstore](https://user-images.githubusercontent.com/25521478/91237550-961f6680-e758-11ea-8c5f-5762852a0ae4.jpg)

http://verify.inspireui.com not working due to security issue on the website.

**Comment by minhcasi** [comment]
note with investigating - thank you!

**Comment by minhcasi** [comment]
@Priyansu67 - pls try to submit the verify on this link https://docs.google.com/forms/d/e/1FAIpQLScWOjkAJIWJ9rgb9alopfOqLsJrGKbFM5cCYj1JBfLKLsBblQ/viewform?pli=1

**Comment by Priyansu67** [comment]
I am using FluxStore.

**Comment by Priyansu67** [comment]
I have submitted the verify files through company email of bookyberg. Hope everything looks good.

**Comment by minhcasi** [comment]
@Priyansu67 - thank you for quick response sir, it's verified

Could you help to use the Fluxbuilder app to support for this customization and checking the issue - http://fluxbuilder.com/

There could be the REST API from your site that causes the systax error

**Comment by Priyansu67** [comment]
In Fluxbuilder everything looks fine and all the products and categories loads perfectly so REST API is not causing the issue. Only when I try to run the app on emulater or a physical device I see this range error.

**Comment by Priyansu67** [comment]
If the products section is listview.builder I think it's unable to determine it's range due to itemcount parameter missing hence giving a range error.

**Comment by minhcasi** [comment]
Good point, could you help to share the source to inspireui.team@gmail.com - we will debug this issue and let you know - very best

**Comment by Priyansu67** [comment]
Sure

**Comment by minhcasi** [comment]
let us know if you have sent it, pls marked with title '4736' for the email - thanks

**Comment by Priyansu67** [comment]
Yes I have sent it and named the title as "issue 4736"

**Comment by minhcasi** [comment]
@dttrung26 - please help to investigate this issue

**Comment by dttrung26** [comment]
Hi @Priyansu67 ,
after testing your common folder, I found that the vertical layout itself does not cause a problem. The problem is in the tabbar config. 
Please try to replace your config_en.json by this file and kindly confirm if it works.
Happy coding!
[config_en.json.zip](https://github.com/inspireui/support/files/5154902/config_en.json.zip)

**Comment by Priyansu67** [comment]
Yes this works but why are my products still not loading. I can see the logcat is calling the mstore api correctly with the consumer key and consumer secret everything looks good but still my categories and products are null.

**Comment by dttrung26** [comment]
Hi @Priyansu67 ,
please double check on config.dart file, the integrated website is still our demo site which is `"url": "https://mstore.io",`

**Comment by Priyansu67** [comment]
Oh totally my fault sorry about that, let me correct it and I will let you know if that works.

**Comment by Priyansu67** [comment]
Yes now everything works thank you so much for the help.

**Comment by Priyansu67** [comment]
Issue is with Fluxstore Woocommerce v1.7.7 .
So the app runs fine but the banner images which are loading is too blurry. I compared it with website but image looks fine on website but looks very low quality on app.
![Screenshot_2020-09-15-11-22-27-079_com bookyberginc bookyberg](https://user-images.githubusercontent.com/25521478/93170962-d36a8900-f745-11ea-83d7-28b995a0673b.jpg)

Look at the banner image and slider image.

And now look how it is on website.
![Screenshot_2020-09-15-11-22-12-953_com android chrome](https://user-images.githubusercontent.com/25521478/93171027-f4cb7500-f745-11ea-89af-1a9d26abf9ba.jpg)

Also I want to remove the drawer from the app. Can it be disabled.

**Comment by dttrung26** [comment]
Close due to support service migration!
https://github.com/inspireui/support/issues/5006
