### ISSUE TITLE
FluxNews 1.4.3 keyboard disappears immediately when typing in text fields

### ISSUE THREAD

**Issue by admincode1** [inspireui/support#4737]
Keyboard disappears immediately when typing in text fields in search page.
Not the search in TabBar, the search in AppBar when enable it from config_xx.json ("showSearch": true).

FluxNews 1.4.3

[√] Flutter (Channel stable, 1.20.1, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
    • Flutter version 1.20.1 at C:\flutter
    • Framework revision 2ae34518b8 (3 weeks ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\user\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = C:\Users\user\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.48.0)
    • VS Code at C:\Users\user\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[√] Connected device (1 available)
    • SM A705FN (mobile) • android-arm64 • Android 10 (API 29)

• No issues found!

Thank you 😊

**Comment by vumanhsn97** [comment]
@admincode1 
It is working well. You can see in this video record: https://streamable.com/oj2duf

**Comment by admincode1** [comment]
Hi @vumanhsn97,

If you see the same video record again, the keyboard disappeared immediately after typing the letter "s" and didn't wait until finish typing the entire word... 
For example, if you want to search for word "stand" you have to touch the search field 4 or 5 times to get the keyboard back.

**Comment by vumanhsn97** [comment]
@admincode1 
In lib/blog/search/custom_search.dart: remove 'else { ... }' https://tppr.me/Jfqqk
Thanks!

**Comment by admincode1** [comment]
@vumanhsn97,
Works great, I really appreciate it.
