### ISSUE TITLE
app landing screen is loading 2 times

### ISSUE THREAD

**Issue by mkarci26** [inspireui/support#4738]
Hi,

App landing screen is loading 2 times.
![image](https://user-images.githubusercontent.com/7647242/91268660-5aee5900-e793-11ea-8292-ad05eaff2516.png)

Can you please address this.

Regards
Karthick

**Comment by mkarci26** [comment]
label: flutter-web

**Comment by minhcasi** [comment]
@mkarci26 - I'm sorry that we could not support extra question or technical issues for the Flutter Web version as it is not ready on production yet, please try with experiment or learning purpose - thank you for your time!
