### ISSUE TITLE
URL rewriting

### ISSUE THREAD

**Issue by mkarci26** [inspireui/support#4739]
How to achieve URL rewriting?
I want website to load like below
http://xample.com/#/home
http://xample.com/#/login
http://xample.com/#/products

etc. Please help

**Comment by mkarci26** [comment]
label: flutter-web

**Comment by minhcasi** [comment]
@mkarci26 - I'm sorry that we could not support extra question or technical issues for the Flutter Web version as it is not ready on production yet, please try with experiment or learning purpose - thank you for your time!
