### ISSUE TITLE
My ticket 4107 is closed but was not resolved

### ISSUE THREAD

**Issue by shamar112** [inspireui/support#4741]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: my ticket https://github.com/inspireui/support/issues/4107 was not resolved but was closed, the last conversation we had was i sent you a video of my issue and you responded saying you will investigate and update me, only to see my my ticket is closed why is that and your the one who said the team is going to investigate. Am also seeing other persons replying under my ticket and getting help under my ticket that i created.

Since my issues i cannot even use 1.7,7 because of bugs only 1.7.5 is the most stable form.But I really want these issues to clear on the latest version.
- [ ] first issue
- [ ] second issue
- [ ] third issue

+ Product & version: fluxstore pro 1.7.7
+ Flutter (or React Native) version: flutter
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

I already did verification on my ticket https://github.com/inspireui/support/issues/4107

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com **

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@shamar112 - thank you for the feedback, as i can see the latest message is from the support team without your response, pls give a try with the solution and let us know 

<img width="1090" alt="Screen Shot 2020-08-26 at 18 23 38" src="https://user-images.githubusercontent.com/1459805/91297881-4462f480-e7c9-11ea-9819-3ab156d89dcf.png">

You could also reopen the ticket as well 👍

**Comment by shamar112** [comment]
The latest response from support was not for me it's for a user that commented under my ticket (completely two different usernames) and support mentioned him/her and a gave solution about (minimum cart value and quantity), I don't have that issue that the user commented that was set a long time ago. As you can see from the video and scenarios I typed in the ticket these are completely two different issues. I was only awaiting your update on the cart calculation support was investigating.

Let me refresh
**here is my issue:**
![tick1](https://user-images.githubusercontent.com/44536258/91320261-532ab680-e78b-11ea-97b0-22140f011213.png)

**This is support reply: which am still awaiting the update**
![tick2](https://user-images.githubusercontent.com/44536258/91320340-650c5980-e78b-11ea-81df-129f2fab6f26.png)

**Now a different user commented under my ticket**
![tick3](https://user-images.githubusercontent.com/44536258/91320453-88370900-e78b-11ea-8c6b-26b6df7dc3ae.png)

**Support replied and only mentioned him/her, please note if I was having this issue that this user commented I would have seen this error in the app on my screen, my values were already set.**

![tick4](https://user-images.githubusercontent.com/44536258/91320714-d946fd00-e78b-11ea-9358-4942e07aafe9.png)

**Comment by minhcasi** [comment]
sorry for the issue, I thought he is the same team with you and there is not response on that ticket as well 

@minhtruong315 - please give your suggestion on this issue

**Comment by minhtruong315** [comment]
@shamar112 I messaged you on the skype. pls check

**Comment by shamar112** [comment]
thanks, I replied

**Comment by minhcasi** [comment]
moved to skype support
