### ISSUE TITLE
Problem: Out of stock all products with combination

### ISSUE THREAD

**Issue by gentianziu03** [inspireui/support#4742]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
- [ ] first issue:   all products with combination shows Out of stock
- [ ] second issue: Tax problem on the invoice
- [ ] third issue

+ Product & version: Latest version 1.7
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

PROBLEM WITH TAX
![GITHUBTAX](https://user-images.githubusercontent.com/46620232/91285339-65a5ef80-e78d-11ea-9ac7-21df06dedf96.jpg)
![1111](https://user-images.githubusercontent.com/46620232/91285688-d2b98500-e78d-11ea-9d9d-5ca816e90cfc.JPG)

Out of stock PROBLEM
![SPP](https://user-images.githubusercontent.com/46620232/91286384-b0743700-e78e-11ea-8836-6e7100b731e0.JPG)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com **

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by vumanhsn97** [comment]
@gentianziu03 
Please update this module: 
[customapi.zip](https://github.com/inspireui/support/files/5129788/customapi.zip)

**Comment by gentianziu03** [comment]
Hello, still the same problem

![navit](https://user-images.githubusercontent.com/46620232/91429075-e5e85580-e85e-11ea-9da0-555f4d7e5f6c.JPG)
![freza](https://user-images.githubusercontent.com/46620232/91429087-e680ec00-e85e-11ea-96f7-0d293749cb38.JPG)

**Comment by vumanhsn97** [comment]
@gentianziu03 
- tax issue: update this module
[customapi.zip](https://github.com/inspireui/support/files/5148198/customapi.zip)
- combination issue: Can you send admin account to inspireui.team@gmail.com? We can't access to your site with test@mail.com
Thanks!

**Comment by gentianziu03** [comment]
hello, yes i just sent

**Comment by vumanhsn97** [comment]
@gentianziu03 
We have been fixed your issues. Please check your site!
Thanks!
[customapi.zip](https://github.com/inspireui/support/files/5149978/customapi.zip)

**Comment by gentianziu03** [comment]
hello, the issue with stock is fixes thanks, but the title of product on back end is not showing

**Comment by vumanhsn97** [comment]
@gentianziu03 
The title of product is fixed. Please check!
[customapi.zip](https://github.com/inspireui/support/files/5153710/customapi.zip)

**Comment by gentianziu03** [comment]
hello, yes. Its ok the title is showing now

![total](https://user-images.githubusercontent.com/46620232/91811185-65936d00-ec2f-11ea-925e-73053fc80be6.JPG)

1) the total is wrong
330+960 + 200 delivery = 1490 in the back office is showing the 1690


2) i want to change currency in Lekë ose ALL  and i want to change the language

**Comment by vumanhsn97** [comment]
@gentianziu03 
in lib/services/prestashop.dart: https://tppr.me/z3RG6
- total: update this line String total_products = cartModel.getSubTotal().toString();
- currency: change id_currency and current_state

**Comment by gentianziu03** [comment]
hello, all is working fine now

i want to remove those fields that i have marked, can we remove those?
![addres](https://user-images.githubusercontent.com/46620232/92107974-eea0d480-ede6-11ea-9627-112fd5747c27.JPG)

**Comment by vumanhsn97** [comment]
@gentianziu03 
You can customize in lib/screen/checkout/shipping_address.dart https://tppr.me/6VVoc.
