### ISSUE TITLE
Vendor Add product - SmartChat push notification - Dark logo and titles problems!

### ISSUE THREAD

**Issue by Youssef-Harby** [inspireui/support#4743]
+ Detail Issues: 
- [Solved]  i cannot see the screen like your demo app (The Vendor can add products and see orders)
like this (Your Demo App) 
![image](https://user-images.githubusercontent.com/13020265/91288670-8f611580-e791-11ea-8b9d-226717a63f74.png)

- [] SmartChat firebase function deployed but i cannot get notification from messages with vendor (Tried payload.data instead of payload.notification with no luck)] second issue
![image](https://user-images.githubusercontent.com/13020265/91288739-a30c7c00-e791-11ea-9e5d-9b071e314a52.png)

- [] Dark Mode Text in Store/Categories Header is black not white 
and it should be two versions of logo (Black and White)
![image](https://user-images.githubusercontent.com/13020265/91288777-aef83e00-e791-11ea-8b36-be778deb9a95.png)
![image](https://user-images.githubusercontent.com/13020265/91288790-b28bc500-e791-11ea-987e-c643f5bbeb45.png)

- [Solved] I have a big conflict in my site between your plugin (MStore Api) and (WPML+WCFM) 
i tried to disable and enable all plugins, at the end your plugin is the problem 
The problem is 500 Internal Server Error when i switch to the second language (ar) and got to any page it gives me the error below

** If i disabled MStore Api plugin, My site works perfectly **] fourth issue
![image](https://user-images.githubusercontent.com/13020265/91289307-7ad14d00-e792-11ea-84c3-2e1b11894c34.png)

-[] Deep Linking for https://example.com/ ?=Slug name of product or vendor ( Important )
-[] cannot add photos offline from assets folder in config_en/ar.json , i can add it only from https links uploaded to other servers which make app very slow
-[] please check iPad version have a lot of bugs
-[] if we can change global chat appears on product screen by chat with vendor whose product it will be great
-[Suggestion] to add Image Attachment to Vendor Chat because a lot of customization on product (Handmade) will be done between Vendor and Clint .

+ Product & version: Fluxstore MV - 1.7.7
+ Flutter (or React Native) version: Flutter 1.20.2 - channel stable - Dart 2.9.1
+ Testing Device/Simulator:Alienware 15 R4 (Win10)/Macbook Pro Mid 2015(Catalina10.15.6) - OnePlus 7 Pro / iPhone 6S
+ Screenshot issues (drag the file to attach here): included above 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com **
**### i sent email to support@inspireui.com explained my issues and my license**

**Comment by minhcasi** [comment]
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
@Youssef-Harby - thank you so much for the rating, I'm happy to upgrade this ticket as high priority support to thank you for your help.

@minhtruong315 - please help with a suggestion on this issue

**Comment by minhtruong315** [comment]
Hi @Youssef-Harby give me your skype. I will contact you to check remotely
Thanks

**Comment by Youssef-Harby** [comment]
@minhtruong315 Hello,
My skype name is live:youssef.harby

**Comment by minhtruong315** [comment]
@Youssef-Harby I added your skype. pls accept. thanks

**Comment by Youssef-Harby** [comment]
@minhtruong315 I accepted and trying to reach you , Thanks

**Comment by dasdev** [comment]
Can't add products and also my products not showing. Getting error please help. And blog post not showing in app. What too do?

**Comment by Youssef-Harby** [comment]
The best support ever @minhtruong315 @minhcasi

**Comment by Youssef-Harby** [comment]
-[] Push notification for vendor chat android/ios (Firebase Function)
-[] Dark mode logo and stores/categories  header title
-[] Deep Linking for https://example.com/ ?=Slug name of product or vendor ( Important )
-[] cannot add photos offline from assets folder in config_en/ar.json , i can add it only from https links uploaded to other servers which make app very slow
-[] please check iPad version have a lot of bugs
-[] if we can change global chat appears on product screen by chat with vendor whose product it will be great
-[Suggestion] to add Image Attachment to Vendor Chat because a lot of customization on product (Handmade) will be done between Vendor and Clint .

**Comment by minhcasi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Feature: upgrade feedbacks](https://trello.com/c/kpU9ZItO/71-feature-upgrade-feedbacks)

**Comment by minhcasi** [comment]
@Youssef-Harby - thank you for the great feedback, I'm moving these request to our Trello backlog
