### ISSUE TITLE
UI changes

### ISSUE THREAD

**Issue by destek-harshadapatil** [inspireui/support#4745]
Hello Team,
As you told me about the referance UI in our last conversation for UI changes I am attaching the image here for that.
I wanted to change my UI screen like the shown in the below image. Can I change the screen like this ? Please tell me how will I change the screen.
Please Help.
Thanks and Regards!
![IMG-20200826-WA0003](https://user-images.githubusercontent.com/62869560/91300663-4a54d780-e7c1-11ea-9e5a-7e8d221376ed.jpg)

**Comment by minhcasi** [comment]
@destek-harshadapatil - it's possible to customize the fluxstore show as providing screenshot, but you need to spend more time with the customization - require flutter programming skills for this UI customize - thanks

**Comment by destek-harshadapatil** [comment]
OK,
Thank you !
I will try to customise this. If I stuck or need any suggestion can I ask that ?

**Comment by minhcasi** [comment]
@destek-harshadapatil - actually we will not support for any customize or technical question due to the limit of scope support from Regular License - https://inspireui.com/support-policies/

But feel free to ask if you have trouble, if we know the solution then we could share - thank you!

**Comment by destek-harshadapatil** [comment]
Ok
Thank you !!
Just want to clear I have purchased an Extended License and already shared
on the link which you have given earlier with the username
destekinfosolutions. Please check that once.

Thanks & Regards,
