### ISSUE TITLE
pub get

### ISSUE THREAD

**Issue by amin5400** [inspireui/support#4746]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
- [ackage:pedantic/analysis_options.yaml] first issue
- [Error: No pubspec.yaml file found.
This command should be run from the root of your Flutter project.
Do not run this command from the root of your git clone of Flutter.
] second issue
- [where i can add code license ] third issue

+ Product & version: Fluxstore Pro Flutter (or React Native) version: 
+ Testing Device/Simulator: ok
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com ** 👈🏻  not open because not https

**Comment by amin5400** [comment]
Error: No pubspec.yaml file found.
This command should be run from the root of your Flutter project.
Do not run this command from the root of your git clone of Flutter

**Comment by minhcasi** [comment]
Duplicate of #4753
