### ISSUE TITLE
splash screen null give me error after update keys

### ISSUE THREAD

**Issue by san2pedro** [inspireui/support#4747]
**after update keys on config like in doc give me error of splash screen null**
![0](https://user-images.githubusercontent.com/13208693/91320664-7cb50380-e7c6-11ea-9fb7-afa12cb3cc48.jpg)
![Screenshot_1](https://user-images.githubusercontent.com/13208693/91320774-92c2c400-e7c6-11ea-80cf-aefa9d96babc.png)

+ Product & version: 1.7.7
+ Flutter (or React Native) version:  Flutter 
+ Testing Device/Simulator:  Real Device
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com **

![Screenshot_2](https://user-images.githubusercontent.com/13208693/91320925-c30a6280-e7c6-11ea-8d2b-255185b1cf47.png)

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by RomeoDar** [comment]
Following this post (same error)

**Comment by san2pedro** [comment]
yup try use your post but dosnt work

**Comment by san2pedro** [comment]
try static for png same error
![Screenshot_3](https://user-images.githubusercontent.com/13208693/91324130-614bf780-e7ca-11ea-8d27-c441eda907f6.png)

**Comment by RomeoDar** [comment]
https://github.com/inspireui/support/issues/4611

https://github.com/inspireui/support/issues/4638

try this

**Comment by san2pedro** [comment]
ok work #4638 ty can close
