### ISSUE TITLE
Mstore api plugins

### ISSUE THREAD

**Issue by ap26091995** [inspireui/support#4748]
I want to use purchase code of my product(Fluxstore ) which i purchased from envato. Currently mstore is active one of my site, but i want to deactivate that and use in another website. How can i use that?

**Comment by minhcasi** [comment]
@ap26091995 - it only supports to active one website at the same time and it could be reset 1 time to change from testing to product site - pls use the fluxbuilder to reset the License - http://fluxbuilder.com

Pls move your all further comment to the same open ticket #4721

**Comment by ap26091995** [comment]
How to reset from fluxbuilder? any steps?
