### ISSUE TITLE
Only 15 Categories are displaying, there are 30 categories on website

### ISSUE THREAD

**Issue by RomeoDar** [inspireui/support#4749]
there are more than 30 categories on my website, while only 15 are displaying in application, kindly guide me how to display all categories

https://github.com/inspireui/support/issues/4701

reopen my old thread

(i did't post ticket for this thread, reopen my old thread #4701)

**Comment by minhcasi** [comment]
@vumanhsn97 - pls help to investigate missing category from fluxnews for the site - https://thenassauguardian.com

**Comment by vumanhsn97** [comment]
@RomeoDar 
Try to replace this file in lib/services/wordpress.dart: 
[wordpress.dart.zip](https://github.com/inspireui/support/files/5133968/wordpress.dart.zip)

**Comment by minhcasi** [comment]
Let us know if you have any issues - thank you!
