### ISSUE TITLE
[FluxNews] OneSignal build error

### ISSUE THREAD

**Issue by aldoyh** [inspireui/support#4750]
Hello guys, I'm on the latest version from FluxNews but upon build, I got this error:

` '/Users/.../Runner-fcbaymgpvutlawcznocwtssouzfq/Build/Products/Debug-iphoneos/Pods_OneSignalNotificationServiceExtension.framework/Pods_OneSignalNotificationServiceExtension(Pods-OneSignalNotificationServiceExtension-dummy.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/.../Runner-fcbaymgpvutlawcznocwtssouzfq/Build/Products/Debug-iphoneos/Pods_OneSignalNotificationServiceExtension.framework/Pods_OneSignalNotificationServiceExtension' for architecture armv7
`

Here's proof of purchase
<img width="1033" alt="Screen Shot 2020-08-26 at 9 08 55 PM" src="https://user-images.githubusercontent.com/5215449/91340254-6025c500-e7e0-11ea-8809-451efe9c3482.png">

**Comment by minhcasi** [comment]
@aldoyh - could i know if you have upgraded your Flutter to latest `1.20.x`? Thanks

**Comment by minhcasi** [comment]
Let us know your update - thank you!

**Comment by aldoyh** [comment]
Yes.

```

/Users/aldoyh/development/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.6 19G2021, locale en-US)
    • Flutter version 1.20.2 at /Users/aldoyh/development/flutter
    • Framework revision bbfbf1770c (2 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/aldoyh/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.10.0.beta.2

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
Process finished with exit code 0
```

**Comment by minhcasi** [comment]
@aldoyh - pls try to go to XCode to update this option to fix the issue (select No Bitcode from onesignal)

<img width="1142" alt="Screen Shot 2020-08-29 at 15 41 07" src="https://user-images.githubusercontent.com/1459805/91632882-2c2fe700-ea0e-11ea-88e1-26ec610d5106.png">

**Comment by minhcasi** [comment]
Let us know your checking 👍

**Comment by khalid-al-shehri** [comment]
I had same issue and I changed bitcode to NO and still same issue
