### ISSUE TITLE
Categories Missing

### ISSUE THREAD

**Issue by Riorich** [inspireui/support#4751]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
- [x] first issue
I have already set up my app and strangely categories are not showing up. The other features are working well but only Categories. Can you help to solve for me? Thanks. 
- [ ] second issue
- [ ] third issue

+ Product & version: 1.7.7 Fluxstore Woocommerce
+ Flutter (or React Native) version:  1.20.2
+ Testing Device/Simulator: Android Emulator
+ Screenshot issues (drag the file to attach here): 
![Screenshot_1598452715](https://user-images.githubusercontent.com/39195214/91340409-fd432680-e7fd-11ea-9324-18aa0e7e1837.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com **

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@Riorich - pls try following solutions would be helpful 

1. update the site with pre-config site data - https://docs.inspireui.com/fluxstore/woocommerce-setup/#1-website-integration

2. using fluxbuilder to check the integration and customize on your site - http://fluxbuilder.com

**Comment by Riorich** [comment]
@minhcasi  Thanks you. Solved it!
