### ISSUE TITLE
Running "flutter pub get" in source..

### ISSUE THREAD

**Issue by amin5400** [inspireui/support#4753]
+ Detail Issues: 
- [Running "flutter pub get" in source...                          

Warning: You are using these overridden dependencies:
! flutter_svg 0.18.0
Running "flutter pub get" in source...] first issue
- [ ] second issue
- [ ] third issue
 my purchase fluxstore pro

**Comment by minhcasi** [comment]
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
@amin5400 - the link http://verify.inspireui.com should work fine know - pls try again

**Comment by minhcasi** [comment]
@amin5400 - thank you for the rating 

Could i know if could run the project smoothly so far? Please not that the flutter_svg warning will not impact to the app features, it is the config from flutter that we use to override the library.

**Comment by amin5400** [comment]
I delete every thing I was think same wrong my android or flutter I have question  what must I did in flutter mac to connect with my woocommerce and  edit logo and edit my project with flutterAny tutorial video I just see video for windows what about mac osFrom: Minh PhamSent: ‏28 ‏أغسطس,‏ ‏2020 ‏07:28 ‏صTo: inspireui/supportCc: amin5400; MentionSubject: Re: [inspireui/support] Running "flutter pub get" in source.. (#4753) @amin5400 - thank you for the ratingCould i know if could run the project smoothly so far? Please not that the flutter_svg warning will not impact to the app features, it is the config from flutter that we use to override the library.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by minhcasi** [comment]
@amin5400 - please share us the screenshot of your current issues. 

Also, try to clean up the cache by following this guide - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1 and https://docs.inspireui.com/fluxstore/woocommerce-setup/

Please share your result by running `flutter doctor` if you could not run the app so far, follow the Test Drive could be helpful https://flutter.dev/docs/get-started/test-drive?tab=androidstudio

**Comment by minhcasi** [comment]
@amin5400 - pls keep your all comment here - let us know your checking, thank you!
