### ISSUE TITLE
QUESTION: What's the best backend?

### ISSUE THREAD

**Issue by enriqueleon80** [inspireui/support#4754]
Hello team!

As someone who is running on Woocommerce/Dokan with Wordpress, I'm curious to know what you all believe what the best backend is.  Having experience in all of them and given I'm considering a migration I would greatly appreciate your inputs.

PS: I create an issue because I don't know of any forum or better place to create this post.  I'm sorry if this is inconvenient, please let me know where you'd rather I post in the future.

Thank you.

Enrique L.

**Comment by minhcasi** [comment]
You could use some VPS servers like Digital Ocean, Lightsail from AWS, or Google Cloud.

Another option by using any Sharing Hosting is also ok with small user base. 

You could add your all questions to the current open ticket #4341 

Let us know if you have any question sir ❤️
