### ISSUE TITLE
Gradle task assembleDebug failed with exit code 1

### ISSUE THREAD

**Issue by dibbo-ru** [inspireui/support#4755]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
- [I can't build app on Android. ] first issue
- [ ] second issue
- [ ] third issue

+ Product & version: Fluxlisting 1.4.2
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

![fsdgdsg](https://user-images.githubusercontent.com/19253603/91369027-6cd00a80-e82c-11ea-99b1-ae1d8576e232.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com **
I have submitted proofed a few days ago

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@dibbo-ru - pls make sure upgrade your flutter to the stable channel

```
flutter channel stable
flutter upgrade --force
```

Or using clean cache solution https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

**Comment by dibbo-ru** [comment]
![SXcdXZc](https://user-images.githubusercontent.com/19253603/91406143-f0591e00-e863-11ea-9832-068f4ff70e04.png)

**Comment by dibbo-ru** [comment]
![Untitled 2](https://user-images.githubusercontent.com/19253603/91487691-f553b700-e8cf-11ea-9616-3d7d18fcf829.png)

**Comment by minhcasi** [comment]
@dibbo-ru - try to use latest fluxstore listing 1.4.3 that compatible with Flutter 1.20.x

The 1.4.2 is used for flutter 1.19.x - thanks

**Comment by minhcasi** [comment]
Let us know your checking 👍

**Comment by dibbo-ru** [comment]
How can I update it? Will I need to configure all the things again?

**Comment by minhcasi** [comment]
@dibbo-ru - please try to merge code by following this guide - https://medium.com/@inspireui/how-to-upgrade-fluxstore-projects-by-using-git-cebde7489ea6 - thank you!

**Comment by minhcasi** [comment]
Let us know if you have any issues
