### ISSUE TITLE
Error occurred when pressed checkout button

### ISSUE THREAD

**Issue by Theappnow** [inspireui/support#4756]
When checkout button was pressed, an error occurred. I run app as debug mode, when execute function addItemsToCart(CartModel cartModel, String token) at lib/services/magento.dart, an exception occured, with detail as below:
- Api endpoint: carts/mine/items
- body: {\"cartItem\":{\"qty\":1,\"quote_id\":163,\"sku\":\"dauanmaslen1lit\"}}
- contentType: application/json
- exception: <br />
<b>Fatal error</b>:  Uncaught Error: Call to a member function getValue() on null in /usr/share/nginx/vendor/magento/module-configurable-product/Model/Quote/Item/CartItemProcessor.php:86
Stack trace:
#0 /usr/share/nginx/generated/code/Magento/ConfigurableProduct/Model/Quote/Item/CartItemProcessor/Proxy.php(103): Magento\ConfigurableProduct\Model\Quote\Item\CartItemProcessor-&gt;processOptions(Object(Magento\Quote\Model\Quote\Item))
#1 /usr/share/nginx/vendor/magento/module-quote/Model/Quote/Item/CartItemOptionsProcessor.php(84): Magento\ConfigurableProduct\Model\Quote\Item\CartItemProcessor\Proxy-&gt;processOptions(Object(Magento\Quote\Model\Quote\Item))
#2 /usr/share/nginx/vendor/magento/module-quote/Model/Quote/Item/CartItemPersister.php(115): Magento\Quote\Model\Quote\Item\CartItemOptionsProcessor-&gt;addProductOptions('configurable', Object(Magento\Quote\Model\Quote\Item))
#3 /usr/share/nginx/vendor/magento/module-quote/Model/Quote in <b>/usr/share/nginx/vendor/magento/module-configurable-product/Model/Quote/Item/CartItemProcessor.php</b> on line <b>86</b><br />
{"messages":{"error":[{"code":500,"message":"Server internal error. See details in report api\/831184914782"}]}}

I'm using Fluxstore lastest version 1.7.7 and magento 2.3
Thanks.

**Comment by minhcasi** [comment]
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support https://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by Theappnow** [comment]
I've summited information

**Comment by minhcasi** [comment]
@minhtruong315 - pls help to investigate this issue

**Comment by minhtruong315** [comment]
@Theappnow can u send me common folder and account to login your hosting via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/4756

**Comment by minhcasi** [comment]
@Theappnow - let us know your update on this ticket - thank you!

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
