### ISSUE TITLE
Getting my app on mobile search when searching inspireui on google

### ISSUE THREAD

**Issue by tjain90** [inspireui/support#4757]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
- [ ] first issue
- [ ] second issue
- [ ] third issue

+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

Right now Google is suggesting fluxstore and my brand app when searching for inspireui. How can update this for my brand. For example when we search our brand then chrome will suggest to open that link in app. Attached snapshot for refrence.
![Screenshot_20200827-074204](https://user-images.githubusercontent.com/6376301/91376252-49ac5780-e83a-11ea-833c-dcc138c11122.jpg)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com **

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@tjain90 - it's about the deeplink feature, try to config by following this guide https://pub.dev/packages/uni_links
