### ISSUE TITLE
Please upload a valid JSON file

### ISSUE THREAD

**Issue by aralom** [inspireui/support#4758]
Hello, According your documentation already donwnload the import plugin (https://drive.google.com/file/d/1SsaprjAISyHIrgksMHLB_t6StDnnST3Y/view?usp=sharing) activate and download the Demo Options (https://drive.google.com/file/d/1Trb0H7iAWQ4UZbZVZAvKuhUReFZLvm1c/view?usp=sharing).
When try to upload the json file give this error: Sorry, there has been an error.
The uploaded options.json.txt file is not supported. Please upload a valid JSON file
![Screenshot_2020-08-26WordPress](https://user-images.githubusercontent.com/6155938/91382778-b64a3680-e7e7-11ea-9f29-a9ea8adb6b40.png)
What I need to do? searching in your entire site and documentation there is no infomation about this issue.

Best Regards!

**Comment by minhcasi** [comment]
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support https://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
@aralom - would you mind to rename the file `options.json.txt` to `options.json` and upload again to see if it works?

**Comment by aralom** [comment]
Hello, already made that testing with mac and win 10, the file options.json is downloaded fine made a doble check .json but looks like WP plugin is changing at .json.txt

**Comment by minhcasi** [comment]
could you share some screenshot issues on your website sir? thanks

**Comment by aralom** [comment]
The issue is I can't upload the .json file at wp the error is already show in the image previously upload when open this ticket.

**Comment by minhcasi** [comment]
it's working with our testing on the same server

Could you try to share the admin access to inspireui.team@gmail.com - we will help to check - thank you!

**Comment by aralom** [comment]
Already send email, please check!

**Comment by minhcasi** [comment]
@tgloc96 - pls help to investigate the issue

**Comment by aralom** [comment]
Any news about this issue?

**Comment by tgloc96** [comment]
We are investigating.

**Comment by aralom** [comment]
Thank you! I'll be waiting!

**Comment by minhcasi** [comment]
@aralom - we're sorry that could not find out the root cause of this issue, we suspect it is caused by some existing plugins your site that it does not support the JSON during importing. As explained from the document, this step only requires for fresh setting up the website, your website already has the data so that is not required to follow these step.

Btw, You could also use the Fluxbuilder 1.0.8 to check the Integration Issues and Customize the app, let us know if you have any question.

**Comment by aralom** [comment]
Hello @minhcasi.
Thank you for the help.
Br
