### ISSUE TITLE
How to remove or change the Nice name option & Oranges image in settings Screen

### ISSUE THREAD

**Issue by usaitech** [inspireui/support#4759]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
- [x] I want to remove the Nice name option in Settings screen. How to do it?
- [x] Oranges Image in the settings screen should be changed.

+ Product & version:
+ Flutter version: 1.17.5

+ Screenshot issues (drag the file to attach here): 
![Screenshot_1598507161](https://user-images.githubusercontent.com/67885653/91392107-79b62380-e857-11ea-8613-8c66fc3c2786.png)

I want to change the Orange picture in settings screen. But cant find anything related to it. 

**_Step 2 (require): submit proof of purchasing the license on https://verify.inspireui.com **

![Screenshot_1598507260](https://user-images.githubusercontent.com/67885653/91390214-f4327380-e856-11ea-9fc2-52b27977f312.png)

And also need to remove the nice name option in Settings screen. Also there's an issue with updating the names. When update names It doesn't appear on the settings screen. Any solution for this? 
Thanks & Regards.

**Comment by minhcasi** [comment]
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support https://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by usaitech** [comment]
> Thank you for the feedback.
> Please help us to submit this form and fill all required info to continue with the support https://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)
> 
> We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!
> 
> > **[Google Forms - create and analyze surveys, for free.](https://verify.inspireui.com/)**Create a new survey on your own or with others at the same time. Choose from a variety of survey types and analyze results in Google Forms. Free from Google.

I already submitted the documents and details through your link. So please answer this qeuestions. I have a copy of the google form which i submitted through this link.

**Comment by minhcasi** [comment]
@usaitech - pls try to use this guide so know the related file for these customize - https://docs.inspireui.com/fluxstore/customization/#1-how-to-customize-any-ui-from-app - thank you!

**Comment by minhcasi** [comment]
Let us know your checking - thanks
