### ISSUE TITLE
[ListApp] Listing Map

### ISSUE THREAD

**Issue by Sherif-Magdy** [inspireui/support#476]
I have got this error when swipe the listing in map screen

Screenshots:
 - https://www.mediafire.com/view/nh881pq2liaaf7f/Simulator_Screen_Shot_-_iPhone_6_-_2019-04-04_at_10.44.31.png/file
- http://www.mediafire.com/view/97ol58ths51oscz/Simulator%20Screen%20Shot%20-%20iPhone%206%20-%202019-04-04%20at%2010.44.11.png

**Comment by thangvo9x** [comment]
Hi. Please provide your purchase code. Which theme are you using?

**Comment by Sherif-Magdy** [comment]
purchase code: [d4aa5cca-d50e-4521-a98f-62cce87bf148]
 Theme: 'myListing'

**Comment by thangvo9x** [comment]
Hi. Do you have try updated latitude & longtitude from your domain?
