### ISSUE TITLE
Few Small issues on Fluxstore-PRo

### ISSUE THREAD

**Issue by goelrajiv75** [inspireui/support#4760]
1. When Entering Shipping address, its not taking email addresses with dot in it for ex. (abc.xyz@gmail.com)..It only taking simple email addresses for ex. abcxyz@gmail.com....not accepting dot it it.
2. in Woocommerce we have give few zones in shipping rates according to city will state wise or pic code wise. but its picking only one, the highest on.
3. When click on 
- [ ] first issue
- [ ] second issue
- [ ] third issue

+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on https://verify.inspireui.com **

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@goelrajiv75 - could you help to share the screenshot of issues 2 and 3, it seems you have missing typing before submitting the ticket

**Comment by minhcasi** [comment]
Let us know your update on this ticket - thank you!
