### ISSUE TITLE
can't build ios app

### ISSUE THREAD

**Issue by AhmedMaherPro** [inspireui/support#4761]
when try to run ios app this error show to me 
i already install everything and try many solutions but nothing working
![builderror](https://user-images.githubusercontent.com/25661721/91416036-1b854280-e84f-11ea-9203-e340c09c32aa.PNG)
![flutterdoctor](https://user-images.githubusercontent.com/25661721/91416202-5a1afd00-e84f-11ea-8676-7e439a634aba.PNG)

**Comment by AhmedMaherPro** [comment]
full build errors
../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/pic
    ture_stream.dart:88:26: Error: Type 'DiagnosticableMixin' not found.
    class PictureStream with DiagnosticableMixin {
                             ^^^^^^^^^^^^^^^^^^^
    ../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/pic
    ture_stream.dart:192:44: Error: Type 'DiagnosticableMixin' not found.
    abstract class PictureStreamCompleter with DiagnosticableMixin {
                                               ^^^^^^^^^^^^^^^^^^^
    ../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_cupertino_date_picker-
    1.0.26+2/lib/src/date_picker_theme.dart:23:32: Error: Type
    'DiagnosticableMixin' not found.
    class DateTimePickerTheme with DiagnosticableMixin {
                                   ^^^^^^^^^^^^^^^^^^^
    ../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/pic
    ture_stream.dart:88:7: Error: The type 'DiagnosticableMixin' can't be mixed
    in.
    class PictureStream with DiagnosticableMixin {
          ^
    ../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/pic
    ture_stream.dart:192:16: Error: The type 'DiagnosticableMixin' can't be
    mixed in.
    abstract class PictureStreamCompleter with DiagnosticableMixin {
                   ^
    ../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_cupertino_date_picker-
    1.0.26+2/lib/src/date_picker_theme.dart:23:7: Error: The type
    'DiagnosticableMixin' can't be mixed in.
    class DateTimePickerTheme with DiagnosticableMixin {
          ^
    ../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/pic
    ture_stream.dart:167:11: Error: Superclass has no method named
    'debugFillProperties'.
        super.debugFillProperties(properties);
              ^^^^^^^^^^^^^^^^^^^
    ../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/pic
    ture_stream.dart:171:30: Error: The method 'toStringShort' isn't defined for
    the class 'PictureStreamCompleter'.
     - 'PictureStreamCompleter' is from
     'package:flutter_svg/src/picture_stream.dart'
     ('../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/
     picture_stream.dart').
    Try correcting the name to the name of an existing method, or defining a
    method named 'toStringShort'.
          ifPresent: _completer?.toStringShort(),
                                 ^^^^^^^^^^^^^
    ../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/pic
    ture_stream.dart:266:11: Error: Superclass has no method named
    'debugFillProperties'.
        super.debugFillProperties(description);
              ^^^^^^^^^^^^^^^^^^^

    Command PhaseScriptExecution failed with a nonzero exit code

**Comment by AhmedMaherPro** [comment]
![flutterinfo](https://user-images.githubusercontent.com/25661721/91451612-e0e6ce80-e87d-11ea-8612-ab0e8e890ac6.PNG)

**Comment by nishantbhandari** [comment]
Have you tried downgrading it to flutter 0.18.0?

**Comment by AhmedMaherPro** [comment]
downgrade what to 0.18.0 ??!

**Comment by minhcasi** [comment]
@AhmedMaherPro - try to download the latest Fluxstore 1.7.7 and override the pubspec.yam to your project to fix the issue

**Comment by minhcasi** [comment]
Let us know your update - thank you!

**Comment by AhmedMaherPro** [comment]
sorry about late response 
error for flutter_svg is solved but this error still not solved (date_picker_theme.dart)
![errors](https://user-images.githubusercontent.com/25661721/91654527-d14bcd80-eaa9-11ea-9f36-62b718315d6e.PNG)
