### ISSUE TITLE
config.json not working

### ISSUE THREAD

**Issue by sofiane8844** [inspireui/support#4762]
Hello the great team

I tried to set up the config.json, (the product Fluxstore WooCommerce - Flutter E-commerce Full App), once uploaded on my site, it doesn't work, it gives a blank page in the app. however I already worked on the first application and it works well.

the site in question is cfrenchy.fr, and in fact it works from the code, and not by putting it online.

can you please help me with this

cordially

**Comment by minhcasi** [comment]
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support https://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
Hi @sofiane8844 - could you help to check the Integrate Analyze of your website with the Fluxstore app by using Fluxbuilder tool - http://fluxbuilder.com/ - thank you!

**Comment by sofiane8844** [comment]
fluxbuilder work fine, when i generate code, and upload it to server
app showing blank page after welcom message

**Comment by minhcasi** [comment]
Could you help to share the screenshot/video of these issues so that we could get your detail problems - thank you!

**Comment by sofiane8844** [comment]
this is website cfrenchy.fr, you can check config file 
no errors messages, just app run, welcom message is ok, after that , blank page nothing is shown and can't even return back
it means app is blocked in this step

**Comment by minhcasi** [comment]
@sofiane8844 - sorry we could not help without the consumse key to connect to your site

Could you share your common and config folder here, we will help to check this issue (you could share private to inspireui.team@gmail.com) - thank you!

**Comment by sofiane8844** [comment]
Email sended

**Comment by minhcasi** [comment]
@simonpham - please help to investigate this issue

**Comment by simonpham** [comment]
Hi @sofiane8844,

1. Please rename the file from `config.json` to `config_en.json`. You can add other JSON for different locales (example: `config_fr.json`). The correct file will be accessible at `https://cfrenchy.fr/config_en.json`

2. Please make sure the link (https://cfrenchy.fr/) is correctly inserted in `lib/common/config/general.dart` as below:

![image](https://user-images.githubusercontent.com/8846657/91790364-c6747280-ec3a-11ea-9d87-7db729165c7c.png)

Hope this will solve your issue. Thank you for using our products!

**Comment by minhcasi** [comment]
Let us know if you have any question - thank you!

**Comment by sofiane8844** [comment]
I sent you an email with sensitive information that I can't share here.

and the link of this ticket 

please confirm

tarik

**Comment by simonpham** [comment]
Hi @sofiane8844,

Have you tried the above solution? https://github.com/inspireui/support/issues/4762#issuecomment-684172694
Could you tell me if it's working?

Thank you very much!

**Comment by sofiane8844** [comment]
yes and i send you a email 
config file works but still have bug with synchronisation and icons tab showing strange caracter

i send you mail from my mail, with secret key and apk and config file

**Comment by simonpham** [comment]
Hi @sofiane8844,

For loadingWidget, please find it in `lib/common/constants/loading.dart`:

![image](https://user-images.githubusercontent.com/8846657/92224579-351c2f00-eecc-11ea-9b98-5be1259fb5af.png)

About the icon issue, please run `flutter doctor -v` and give us a screenshot of the result. Thank you.

**Comment by sofiane8844** [comment]
thank you 
still need assistance for icon and categories

**Comment by simonpham** [comment]
Hi @sofiane8844,

> About the icon issue, please run flutter doctor -v and give us a screenshot of the result. Thank you.

**Comment by sofiane8844** [comment]
![image](https://user-images.githubusercontent.com/70319472/92236323-21ad9b80-eead-11ea-814a-e38b42ba1ffa.png)

**Comment by sofiane8844** [comment]
i try to edit config file 
this is new version cfrenchy.fr/config_fr.json

but still page not working
