### ISSUE TITLE
com.apple.AuthenticationServices.AuthorizationError error 1000

### ISSUE THREAD

**Issue by emad-masood** [inspireui/support#4763]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
- [ ] first issue
- [ ] second issue
- [ ] third issue

+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on https://verify.inspireui.com **

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

Hi
apple sign-in is not working i don't see any guide or docts or video to know how to fix it
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-08-27 at 11 51 36](https://user-images.githubusercontent.com/68939548/91420307-3068d280-e85d-11ea-9bc5-f7e956a73dcc.png)

<img width="1512" alt="Screen Shot 2020-08-27 at 11 55 33 AM" src="https://user-images.githubusercontent.com/68939548/91420351-41b1df00-e85d-11ea-8dc0-25e1c76cb80d.png">

<img width="1640" alt="Screen Shot 2020-08-27 at 11 58 23 AM" src="https://user-images.githubusercontent.com/68939548/91425101-601ad900-e863-11ea-8f6d-389bc675520e.png">

fluxstore 1.7.7

**Comment by minhtruong315** [comment]
@emad-masood 
- Apple login can't test on simulator, so you need to test on iPhone
- Please enable Real database in firebase
- Delete MStore Api plugin in your website and install this package mstore-api.zip
[mstore-api.zip](https://github.com/inspireui/support/files/5140042/mstore-api.zip)
- Open up the Setting app in your iPhone and tap on your name at the top. Then press Password & Security, then Apps using Apple ID They listed all the apps there and you can delete your app to revoke access.
- Then try to check apple login again on the iPhone

**Comment by emad-masood** [comment]
thank you is working now
