### ISSUE TITLE
Unable to change onBoarding image and unable to add new product listing to home layout

### ISSUE THREAD

**Issue by akhiltrivedi** [inspireui/support#4765]
-------- 1st Issue --------

I am setting new images to onboarding page

1 - not able to set 3rd image my 3rd image is different still it is showing me old image
2 - how to increase image box height as right now my images looks like they have been cut half

this image should be here i don't know why it is not coming, other 2 are coming

-------- 2nd Issue --------

i want to add new category listing to home layout, but it is not coming

if i change layout to : simpleVerticalListItems

it is showing me something but that also without any products and other layouts are not working,

NOTE :  CATEGORY ID IS WORKING BCOZ THAT ID I ALREADY GIVEN TO ABOVE IMAGE AND IT IS REDIRECTING WELL TO PROPER PAGE

Google Drive link of video - https://drive.google.com/file/d/1QHaAEChWzNKufi5_2gAp_i2zs3WOty7N/view?usp=sharing

**Comment by minhcasi** [comment]
@akhiltrivedi - thank you for the detailed video 

@luyx2412 - please help with checking

**Comment by luyx2412** [comment]
Hi @akhiltrivedi Thanks for specific video. Please fill the form and upload your config, let me investigate about the issues.

Thanks

**Comment by akhiltrivedi** [comment]
Hi @luyx2412  which form ?

**Comment by akhiltrivedi** [comment]
please send me form link so I can fill the form

**Comment by minhcasi** [comment]
@akhiltrivedi - pls help to submit this link https://gitlab.inspireui.com/

**Comment by akhiltrivedi** [comment]
form submitted I will upload config file soon. 

thank you

**Comment by akhiltrivedi** [comment]
Hello please find a zip containing config.json
[config.zip](https://github.com/inspireui/support/files/5160473/config.zip)

**Comment by akhiltrivedi** [comment]
I have attached config.json and config.dart file in this zip

[config.zip](https://github.com/inspireui/support/files/5160614/config.zip)

**Comment by akhiltrivedi** [comment]
any update ?

**Comment by luyx2412** [comment]
Hi @akhiltrivedi Sorry about reply you late.
1. Please uninstall app and reinstall again, the issue related your cache.
2. Please update to latest version 1.7.7 to fix the issue. In `lib/screens/home/onboard_screen.dart` line 85. Please follow the screenshot to edit image size.
![image](https://user-images.githubusercontent.com/8909619/92259515-7975f200-ef01-11ea-8fea-94e016b58b96.png)
3. The layout type `simpleVerticalListItems` worked normal. Please wait or run again to see that.
![image](https://user-images.githubusercontent.com/8909619/92260268-da052f00-ef01-11ea-928f-1d9152541f45.png)

Thanks
