### ISSUE TITLE
Migrating WordPress configuration and Mstore Api plugin 

### ISSUE THREAD

**Issue by olorunfemi007** [inspireui/support#4767]
I have completed my development in WordPress test system and I want to migrate Mstore Api plugin to my production system. How do I handle the authorization of the Mstore Api plugin in my production WordPress installation.
Thanks

**Comment by minhcasi** [comment]
@olorunfemi007 - you could deactivate the code from Testing Site and migrate wot new production site - https://docs.inspireui.com/fluxbuilder/guide-to-use/#deactivate-the-purchase-code

**Comment by minhcasi** [comment]
Let us know if you have any question - thank you!
