### ISSUE TITLE
Exit "Yes" Takes me to the "splashscreen" of the app

### ISSUE THREAD

**Issue by munna-online** [inspireui/support#4769]
Okay, so we are using Fluxstore woocommerce app and when I click on back button then ask exit app or not. That is good but when I click on "Yes" it doesn't close the app but go to splashscreen. Same thing happens when I click on 'Back to shopping or something that shows after successful purchase. That button after the thank you message ON Arabic version of the app. I repeat Arabic. Where I can find the code to redirect that button to home. And, on English or any other language how to close the app after clicking on Yes on exit popup? Please help

**Comment by Alnaggar94** [comment]
Same issue

**Comment by alexrali** [comment]
same here

**Comment by minhcasi** [comment]
@mhofficial1 
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support https://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by munna-online** [comment]
I have submitted the form. Kindly check :)

**Comment by minhcasi** [comment]
@munna-online - thank you for quick response, we will investigate and let you know - very best!

**Comment by tgloc96** [comment]
Hello @munna-online, Can you please tell me what version you are using and can you record the screen when the error occurred. Because I have tested this feature and it is working properly in the latest version.

**Comment by munna-online** [comment]
We are using the "FluxStore-woo-1.7.7" version (latest). Looks like every exit/cross button is taking back to the splash screen. Here is the video (Watch till the last because I also recorded the Cross issue that also redirect to splash screen. And you have to press the back button again to exit. Why is that?): https://streamable.com/8qhbgw

**Comment by tgloc96** [comment]
> We are using the "FluxStore-woo-1.7.7" version (latest). Looks like every exit/cross button is taking back to the splash screen. Here is the video (Watch till the last because I also recorded the Cross issue that also redirect to splash screen. And you have to press the back button again to exit. Why is that?): https://streamable.com/8qhbgw 
> 
> <blockquote><img src="https://cdn-cf-east.streamable.com/image/8qhbgw.jpg?Expires=1599129300&Signature=axO2CR9msVax7NCMazcEqHaO2Bjt8n83Zyu0HZUljNzCLyQcvsaBS4MF41Y3ut2sM27zxHC4CVv8y2STaV3vOA0Q1L71iiTE8RX3unQeAIeM0eJRUhcWwaccBl67~9Rx5bc0fdc4DB5fDwmZPJQjRW4c84WzVxckt4lbrazV8zhmT2Ql~9aDgyhasrkvv4ylqCpsR8cWj7OX2EYDHAnn3Uk7xQpKMlzvxLKDQ6UmjNZUpJMWY~-yy9amCtc5zuwr33ayIZtu2i06PLKoJi~Lt0Os0zG6V8h6d7~djYL-byENctVzX1XyMMr-uQ9qtd4GIMxfrYHtJChwtIwmKYjY2w__&Key-Pair-Id=APKAIEYUVEN4EVB2OKEQ" width="48" align="right"><div>Streamable</div><div><strong><a href="https://streamable.com/8qhbgw">Streamable Video</a></strong></div><div>Watch this video on Streamable.</div></blockquote>


Can you please send me your full source code to tgloc96@gmail.com, I will investigate the issue.

**Comment by munna-online** [comment]
Done, please check your mail :)

**Comment by tgloc96** [comment]
> Done, please check your mail :)

I received and investigating the issue

**Comment by tgloc96** [comment]
@munna-online, Sorry but I can not run your the source code, please send me again the source code you can run. Thank you.

**Comment by munna-online** [comment]
I have resent the code I am using. Also, I have sent a video showing that the code works on Android Studio.

**Comment by tgloc96** [comment]
@munna-online I can build an app with the source code you send. You have modified something. You changed something in the config files of the android directory and made it impossible to build the new app.

**Comment by munna-online** [comment]
> @munna-online I can build an app with the source code you send. You have modified something. You changed something in the config files of the android directory and made it impossible to build the new app.

I don't know if I have done that. But, I think I didn't. Still, if that the issue then please try replacing those with a fresh one and see if that works. However, that "Exit" issue should not be there because of the Android Directory changes.

**Comment by tgloc96** [comment]
@munna-online Can you run the command `flutter clean" and build app again.

**Comment by munna-online** [comment]
> @munna-online Can you run the command `flutter clean" or delete the build folder after that build the app again.

After running the flutter clean command then build APK I get this error.
Please help :)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform libs.jar to match attributes {artifactType=processed-jar, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for JetifyTransform: A:\App Development\YOSHOES FLUXSTORE\source\source\source\build\app\intermediates\flutter\debug\libs.jar.
         > Transform's input file does not exist: A:\App Development\YOSHOES FLUXSTORE\source\source\source\build\app\intermediates\flutter\debug\libs.jar. (See https://issuetracker.google.com/issues/158753935)

**Comment by tgloc96** [comment]
> > @munna-online Can you run the command `flutter clean" or delete the build folder after that build the app again.
> 
> After running the flutter clean command then build APK I get this error.
> Please help :)
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
>   Execution failed for task ':app:lintVitalRelease'.
> 
> > Could not resolve all artifacts for configuration ':app:debugRuntimeClasspath'.
> > Failed to transform libs.jar to match attributes {artifactType=processed-jar, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
> > > Execution failed for JetifyTransform: A:\App Development\YOSHOES FLUXSTORE\source\source\source\build\app\intermediates\flutter\debug\libs.jar.
> > > Transform's input file does not exist: A:\App Development\YOSHOES FLUXSTORE\source\source\source\build\app\intermediates\flutter\debug\libs.jar. (See https://issuetracker.google.com/issues/158753935)
> 
> > **[Sign in - Google Accounts](https://issuetracker.google.com/issues/158753935)**

Yes, I want to show you that your source code is having problems because it's cannot build the new versions and always to run the already build file, the "flutter clean" command has removed the old build and it cannot build the new version and as you see, it's cannot build a new version.

**Comment by munna-online** [comment]
If I am not wrong you are a flutter+Android Studio developer, right? So, you should have the answer how to solve this problem. Otherwise what is the use of buying this?

**Comment by minhcasi** [comment]
@munna-online - please also give a try with the latest source on Gitlab - if you don't have an account, please submit to http://gitlab.inspireui.com/ - thank you!

**Comment by munna-online** [comment]
Build issues fixed. Now, you can build an app with the new code. Where should I send it so that you can check the Exit app issue (it is still there)? Should I send the code to the same email I sent before?

**Comment by munna-online** [comment]
Hello! I haven't got any answer. I have sent the new code to the old email you provided. Please check

**Comment by tgloc96** [comment]
Hello @munna-online, I fixed the issue and send back the full source code to you via email, please check it.

**Comment by Alnaggar94** [comment]
@tgloc96 - Could you please share the solution here as I have the same problem

**Comment by tgloc96** [comment]
> @tgloc96 - Could you please share the solution here as I have the same problem

Hello @Alnaggar94, Are you using a splash screen static?

**Comment by tgloc96** [comment]
@munna-online We have resolved this issue via email so I would like to allow to close this ticket.

**Comment by munna-online** [comment]
Sure, thank you for resolving the issue 👍
