### ISSUE TITLE
[MStore Pro] Can't see some Categories and Tags in Dropdown list - Can't login

### ISSUE THREAD

**Issue by BriceGboyou** [inspireui/support#477]
- Product: MStore Pro (using expo version)
 - Purchased Code: 2bbc8a64-6a41-498e-8c5b-eb6cf50a0565

**Describe the issues**
I'm using CeBuilder V30.0.
1- I can't see some Categories and Tags in Dropdown list in Customization tab. And some are duplicated.
2- I can't login on the app (username/email/password not valid)

**Screenshots**
https://prnt.sc/n7flzq

**Comment by luyx2412** [comment]
Hi @BriceGboyou Please use debug tool to check your response api https://docs.mstore.io/api-and-project-structure#debug-app-with-reacttotron and understand why your categories did not show and duplicated.

Thanks
