### ISSUE TITLE
Vertical layout not displaying on mstore Pro- React native woocommerce

### ISSUE THREAD

**Issue by sashaba** [inspireui/support#4770]
Hello team
I've been a fan of the horizontal layout for a couple years. Today I tried to redesign my app using just vertical layout, but its not working. is there a reason why the vertical layout is not working in MstorePro -woocommerce any more?
I followed all steps:
copied the banner high and vertical cad.json to my AppConfig.json
but only the banner is displaying, the vertical layout is not showing. I tested all others layouts and any possible combination and nothing happened.
would you please help me, am I doing something wrong?

"HorizonLayout": [
    {
      "layout": "bannerHigh",
      "tag": 273
    }
  ],

  "VerticalLayout": {
    "name": "Recents",
    "layout": "card"
  },
  
  "MainColor": "#673AB7"
}

**Comment by sashaba** [comment]
it doesn't work on your app either.  no matter what theme layout you use on AppConfig.json , the home layout doesn't change. its stuck on the default.
im testing your demo, recently installed.

**Comment by luyx2412** [comment]
Hi @sashaba Please fill the form and give me specific screenshot or video about the issue. Let me investigate easier.

Thanks

**Comment by sashaba** [comment]
Hi @luyx2412 
Thank you for replying, I've always posted my comment and you guys have helped me right away.  should I open a new issue with the form? I tried editing this and I don't see any form here. 

You can close this issue, I figured something out. im not gonna use the vertical layout. but still not working.

**Comment by luyx2412** [comment]
Hi @sashaba I remember you, but i don't have your app information. So please fill the form http://verify.inspireui.com/. Let me help you easier.

Thanks

**Comment by minhcasi** [comment]
Let us know if you have any questions - thank you!
