### ISSUE TITLE
Showing Bottom Overflowed by 1pixel in Samsung A51 Device 

### ISSUE THREAD

**Issue by amitsahaiotait** [inspireui/support#4771]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: I am seeing Bottom Overflowed by 1 pixel in Product List page. Please see the Screenshot to understand the issue.

+ Product & version: FluxStore MultiVendor 1.7.7
+ Flutter (or React Native) version: Flutter
+ Testing Device/Simulator: Samsung A51
+ Screenshot issues (drag the file to attach here): 
![Screenshot_20200827-211616](https://user-images.githubusercontent.com/50100454/91485750-267eb800-e8cd-11ea-808e-17b821516be2.jpg)

**_Step 2 (require): submit proof of purchasing the license on https://verify.inspireui.com **

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by amitsahaiotait** [comment]
I already submitted the verification process

**Comment by minhcasi** [comment]
@tgloc96 - please help to check the issue

**Comment by tgloc96** [comment]
Hello @amitsahaiotait, you can follow the document below to fix this issue: https://docs.inspireui.com/fluxstore/customization/#15-layout-list-product

**Comment by amitsahaiotait** [comment]
Thank you let me check, Hopefully it will work on my site. I will update you in shortly.

**Comment by minhcasi** [comment]
Let us know your checking - thanks

**Comment by amitsahaiotait** [comment]
This issue is solved. Thank You
