### ISSUE TITLE
Sign into  To The App 

### ISSUE THREAD

**Issue by MaNoOoz** [inspireui/support#4772]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
- [ ] I have problem with login in all platforms I tried all the solutions in   #3151 and i test most of the solutions (Not Working)
- [ ] google fonts didnt apply to all text for example ("show all" text) in categories still used different font family 
Question: I use google login before connect my WordPress site and using the mstore plugin is it  ok? 
 my previous support ticket is #4417 

+ Product & version: Fluxstore pro
+ Flutter (or React Native) version: 1.20 stable
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

![device-2020-08-06-105200](https://user-images.githubusercontent.com/26860253/89505816-df703c00-d7d2-11ea-934c-1868a2183981.png)
please help @minhcasi

**Comment by minhtruong315** [comment]
@MaNoOoz send me full your source code via email: minhtruong315@gmail.com
thanks

**Comment by MaNoOoz** [comment]
> 
> 
> @MaNoOoz send me full your source code via email: [minhtruong315@gmail.com](mailto:minhtruong315@gmail.com)
> thanks

i just added u to my private repo ok, please check your email

**Comment by MaNoOoz** [comment]
any good news ? @minhtruong315

**Comment by minhtruong315** [comment]
Hi @MaNoOoz I checked your source code. it's old version. please download the latest version on codecanyon and check again

**Comment by MaNoOoz** [comment]
@minhtruong315  i tried the new version same error bro

**Comment by minhtruong315** [comment]
@MaNoOoz send me new source code, share me admin account to login your website and invite me to firebase console.

**Comment by minhtruong315** [comment]
@MaNoOoz Did you send me admin account and invite me to firebase project?

**Comment by minhtruong315** [comment]
@MaNoOoz Your issues are in android or iOS?

**Comment by MaNoOoz** [comment]
Yes i sent u invite for firebase project 
Android for now I didn't test on ios yet

**Comment by MaNoOoz** [comment]
minh.inspireui@gmail.com IS THIS YOUR EMAIL ? i sent invite to this one

**Comment by MaNoOoz** [comment]
the project on my other email firebase console directsisters@gmail.com

**Comment by minhtruong315** [comment]
@MaNoOoz my email: minhtruong315@gmail.com.
can u send me this file C:/Users/MaNoOox/key.jks
You're using this file in your app. I dont have this file so I can't build your source code

**Comment by minhcasi** [comment]
@MaNoOoz - let us know your updating - thank you!

**Comment by MaNoOoz** [comment]
i send u the file bro

**Comment by minhtruong315** [comment]
Hi @MaNoOoz please pull the source code and check your issues again.

**Comment by MaNoOoz** [comment]
@minhtruong315  ok bro now its working can u please explain the problem and how i fixed,, on my own oath and key thanks

**Comment by minhtruong315** [comment]
You generated wrong SHA-1 key to add to firebase project. so I generated SHA-1 key again.

**Comment by MaNoOoz** [comment]
@minhtruong315  hey bro there is another problem when I exit the app and re-run I have to login again is that normal?
