### ISSUE TITLE
Component Functionality Documentation - MStore 4.0.0

### ISSUE THREAD

**Issue by franklinbinauraldev** [inspireui/support#4773]
Receive a warm greeting.

I was wondering if you have information on the functionality of each component, reducer and navigation.

I would like to further customize the functionality of the template according to my needs, in addition to changing the main flow. On your page you have documentation, but it is very general and does not cover details.

I would like you to share it, to make the modifications a little faster. I think I waste too much time reading code, and the behavior of the components. That way I would make changes right to the point.

Thank you very much.

**Comment by minhcasi** [comment]
@franklinbinauraldev - thank you for the question, please help to give the comment on the same ticket #4735 My react native team will help to clarify the detail. 

Please note that to control well the Mstore project, it is required to know the Redux then you could customize it more easily
