### ISSUE TITLE
Payment Page shows 404 error on App

### ISSUE THREAD

**Issue by kathitgandhi** [inspireui/support#4778]
Hello! I have been using mstore pro for my wordpress site and all the configuration are working ok but at the time of checkout 404 error page not found issue is coming. i have also made mstore-checkout page on my wordpress site and also template type is assigned mstore-api. I have been using cache clear plugin which also i disabled but still checkout page doesn't appear. So please look into my issue as soon as possible as my launch deadline is very near.

**Comment by minhcasi** [comment]
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support https://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support https://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by kathitgandhi** [comment]
I have provided all the details on the given form. looking forward for your help as soon as possible. Thanks

**Comment by kathitgandhi** [comment]
Looking forward for update. Please help me to solve the payment page issue as soon as possible.

**Comment by kathitgandhi** [comment]
I am facing problem with the payment page still after following all the steps of creating Mstore Api template. Looking for support on that issue. Please take my issue as urgent as my launch deadline is very near. @minhcasi @luyx2412

**Comment by luyx2412** [comment]
Hi @kathitgandhi If your url payment is 404, maybe you install lack of the libraries. So please follow the document to complete setup https://docs.inspireui.com/mstore/wordpress-setting/

Thanks

**Comment by kathitgandhi** [comment]
Hi @luyx2412 . Thanks for the update. I have done all the configuration given on above documentation. My App is completely working other then on checkout page Payment page shows 404 Error. I have also made mstore-checkout page and my purchase code is also activated and i have uploaded my AppConfig.json file on wordpress also. Still issue is not resolved. Please look into it. 
Thanks

**Comment by kathitgandhi** [comment]
Hi! @luyx2412 @minhcasi . Looking forward for updates from your side. Please help me regarding payment page issues. I have launch deadline very soon. Need Urgent Help.

**Comment by kathitgandhi** [comment]
Hello @luyx2412 @minhcasi . Please update me regarding the issue I am facing during payment checkout page. I hope you understand the urgent release issue of developers. If you don't want to solve the issue then i would like to have refund for the amount that i have paid. So kindly consider this as urgent and support.

**Comment by luyx2412** [comment]
HI @kathitgandhi Please fill the form and upload your config http://verify.inspireui.com/. Let me investigate easier.

Thanks and sorry about reply you late.

**Comment by kathitgandhi** [comment]
Hi @luyx2412 . Thanks for the reply. I have submitted my config file to the above link. Please review and let me know as soon as you can. Thanks

**Comment by kathitgandhi** [comment]
Hello @luyx2412 . Looking forward for the update. It's already 3 days since i have submitted all the required details. Please help to resolve this issue as soon as possible.

**Comment by luyx2412** [comment]
Hi @kathitgandhi Please upload your config again, or send via inspireui.team@gmail.com. Because i did not see your config.
![image](https://user-images.githubusercontent.com/8909619/92487435-6fad0100-f217-11ea-83a1-b5a7ce7fa9ac.png)

Thanks

**Comment by kathitgandhi** [comment]
HI @luyx2412 . Please check the mailbox. I have sent you config file to the mail. Looking for the response as soon as possible.
Thanks

**Comment by luyx2412** [comment]
Hi @kathitgandhi Can you send me the issue screenshot or video? Because i don't know what 404 payment.

Thanks

**Comment by kathitgandhi** [comment]
Hi @luyx2412 . I have shared my website login details with you since more than 3 days. Still there is no update. Please let me know the updates. It's taking more time for you to resolve such a small issue. I expected shorter duration to resolve this issue.

**Comment by kathitgandhi** [comment]
Hi @luyx2412 . Can you please share update over my issue? I have already provided admin panel access to my site. If you can not provide support for such an small issue then i would like to use different script for my application. I hope you can understand my problem and try to solve as soon as possible. Please look into this matter seriously. @minhcasi @luyx2412

**Comment by luyx2412** [comment]
Hi @kathitgandhi Sorry about reply you late. I checked your config and everything is normal, maybe the issue related the hosting, so we are investigating your issue and reply you soon.

Thanks

**Comment by kathitgandhi** [comment]
hi @luyx2412. Till what time can you update me since i have already launched the app on play store and users are facing issue for payment. Please let me know as soon as possible. @minhcasi @luyx2412 .

**Comment by luyx2412** [comment]
@minhtruong315 Please investigate about the issue. 

Thanks

**Comment by minhtruong315** [comment]
Hi @kathitgandhi can u send me admin account to login your website via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/4778
Thanks

**Comment by minhcasi** [comment]
Greetings from InspireUI 🎉
To improve user experience during support, we are announcing that a new ticket support system is available on this link https://support.inspireui.com 

Please help to move your next comment on the new support system (you could mention this ticket so that the team could know more about the ticket's history) - thank you for your time!
