### ISSUE TITLE
sync config to cloude

### ISSUE THREAD

**Issue by attare026** [inspireui/support#4779]
Which api key i will add here?
![image](https://user-images.githubusercontent.com/34741721/91547424-c0982d80-e8d8-11ea-84af-b767fd1da7f1.png)

**Comment by minhcasi** [comment]
@attare026 - you could try to download the config JSON file and upload it to your mstore-api plugin at this time - https://docs.inspireui.com/fluxbuilder/guide-to-use/#change-the-app-design-without-re-publish-to-app-stores

This uploading feature is still on beta and not ready for use, sorry for the confusion as the team did not hide this option.
