### ISSUE TITLE
 A issue while deactiving the license for another website it is showing error your code has been reseted before please contact support@inspireui.com 

### ISSUE THREAD

**Issue by alokmalewar** [inspireui/support#4783]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
- [ ] first issue
- [ ] second issue
- [ ] third issue

+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on https://verify.inspireui.com **

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@alokmalewar - please send your detailed screenshot issue and send the request to reset purchase code to support@inspireui.com - thank you for your time!

**Comment by alokmalewar** [comment]
Screenshot attached
![s](https://user-images.githubusercontent.com/69632534/91630092-3b9e3880-e9ec-11ea-8cad-94b0ce14c4d1.png)
