### ISSUE TITLE
PRoduct share option not working 

### ISSUE THREAD

**Issue by codex-pro** [inspireui/support#4784]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
- [x] first issue
- [x] second issue
- [x] third issue

+ Product & version:
+ Flutter (or React Native) version:  latest
+ Testing Device/Simulator:  redmi note 7
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on https://verify.inspireui.com **-done

share.dart 

// Copyright 2019 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'dart:async';
import 'dart:ui';

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show visibleForTesting;

/// Plugin for summoning a platform share sheet.
class Share {
  /// [MethodChannel] used to communicate with the platform side.
  @visibleForTesting
  static const MethodChannel channel =
      MethodChannel('plugins.flutter.io/share');

  /// Summons the platform's share sheet to share text.
  ///
  /// Wraps the platform's native share dialog. Can share a text and/or a URL.
  /// It uses the `ACTION_SEND` Intent on Android and `UIActivityViewController`
  /// on iOS.
  ///
  /// The optional [subject] parameter can be used to populate a subject if the
  /// user chooses to send an email.
  ///
  /// The optional [sharePositionOrigin] parameter can be used to specify a global
  /// origin rect for the share sheet to popover from on iPads. It has no effect
  /// on non-iPads.
  ///
  /// May throw [PlatformException] or [FormatException]
  /// from [MethodChannel].
  static Future<void> share(
    String text, {
    String subject,
    Rect sharePositionOrigin,
  }) {
    assert(text != null);
    assert(text.isNotEmpty);
    final Map<String, dynamic> params = <String, dynamic>{
      'text': text,
      'subject': subject,
    };

    if (sharePositionOrigin != null) {
      params['originX'] = sharePositionOrigin.left;
      params['originY'] = sharePositionOrigin.top;
      params['originWidth'] = sharePositionOrigin.width;
      params['originHeight'] = sharePositionOrigin.height;
    }

    return channel.invokeMethod<void>('share', params);
  }
}
  

logat : 
  assert(text != null);
    assert(text.isNotEmpty);
    final Map<String, dynamic> params = <String, dynamic>{
      'text': text,
      'subject': subject,
    };

showing null as false

**Comment by codex-pro** [comment]
?

**Comment by codex-pro** [comment]
and also send me detail process to activate razarpay again for android ....

**Comment by dttrung26** [comment]
Hi @codex-pro code ,
could you tell me more detail what you are experiencing when using share function? 
In terms of razor payment, detailed documents and changes in source code will be provided to all users in the next patch. Please stay tuned.
Have a nice day.

**Comment by codex-pro** [comment]
Share function is non reponsive ... its not doing anything ...check code and log i have posted

**Comment by dttrung26** [comment]
HI @codex-pro ,
according to what I check, sharing function still works fine on both iOS and Android. 
If you test this function in physical devices, more options will also be available.
<img width="390" alt="Screen Shot 2020-09-01 at 17 45 21" src="https://user-images.githubusercontent.com/32586676/91840689-4ae6e580-ec7b-11ea-889b-18014db287e4.png">

<img width="410" alt="Screen Shot 2020-09-01 at 17 47 12" src="https://user-images.githubusercontent.com/32586676/91840676-46223180-ec7b-11ea-813c-7135687f44c7.png">
Best!

**Comment by codex-pro** [comment]
thanx for reply ..i chcked n two devices  logat :
assert(text != null);
assert(text.isNotEmpty);
final Map<String, dynamic> params = <String, dynamic>{
'text': text,
'subject': subject,
}; this is error while we click on share

**Comment by codex-pro** [comment]
?????

**Comment by dttrung26** [comment]
Could you record me a video for what you are saying @codex-pro ? I kinda cannot get your point.

**Comment by codex-pro** [comment]
https://www.dropbox.com/s/ocg3ig9eikrxieh/download.mp4?dl=0

**Comment by codex-pro** [comment]
waiting for reply ????

**Comment by codex-pro** [comment]
any update ?

**Comment by dttrung26** [comment]
Hi @codex-pro ,
sorry for the delay in weekends. Could you please send me your whole project (after deleting build folder) and send to me via: trung@inspireui.com? At the moment, I still find no issue in sharing. 
Best!

**Comment by codex-pro** [comment]
ok

**Comment by dttrung26** [comment]
Hi @codex-pro ,
I just want to update the situation that I still haven't got your project via my mail. Please double check.

**Comment by dttrung26** [comment]
Closed due to no response. Feel free to reopen this ticket when you are active.
