### ISSUE TITLE
reference #4726

### ISSUE THREAD

**Issue by qorane099** [inspireui/support#4785]
I used this format: assets/images.xx.png but the images still is not appear on the screen

**Comment by qorane099** [comment]
I mean reference number #4729

**Comment by qorane099** [comment]
i am facing hard time getting correct Asha-1 finger print.

i was using this directory:

keytool -list -v \
-alias key -keystore ~/.android/app/certs/key.jks

but not working.

please see the screenshot, what am l missing.

<img width="1204" alt="Screenshot 2020-08-29 at 3 29 38 PM" src="https://user-images.githubusercontent.com/39888242/91634275-d149c000-ea0c-11ea-936d-ad74dce68b30.png">

**Comment by qorane099** [comment]
it keeps saying the file does not exist.
<img width="1415" alt="Screenshot 2020-08-29 at 5 00 11 PM" src="https://user-images.githubusercontent.com/39888242/91635820-37d4db00-ea19-11ea-9837-10885a23ed8a.png">

**Comment by minhcasi** [comment]
@qorane099 - try to use the full path or copy the .jks file into android folder.

Try to move the png image file to `assets/images/` folder, as this folder already register with the asset folder - https://tppr.me/bZtNQ

**Comment by qorane099** [comment]
Dear Minhcase,

The file is already in assets.images/


I called it as:

"layout": "bannerImage",
      "items": [
        {
          "category": 537,
          "image": "assets/images/Banner.png",
          "padding": 5.0


Note: Banner.png is in assets/images folder

**Comment by qorane099** [comment]
also if l paste: keytool -list -v \
-alias androiddebugkey -keystore ~/.android/debug.keystore


to terminal l am getting SHA-1 and SHA-2 but l dont if that the correct once since the app is not function well even after l added these fingerprint.

in your comment above, you said, use full how can l use a full part.

**Comment by Kindakart** [comment]
Dear minhcasi,

Please assist me through teamviewer,

please give me 2 mintues of your valuable time.

thank you

**Comment by dttrung26** [comment]
Hi @qorane099 ,
If you are Windows user, please follow those instructions to get SHA1: 
- Run your project
- Click on Gradle menu (right-hand side bar)
- Expand Gradle Tasks tree
- Double click on android -> signingReport 
- SHA1 will be displayed on the Run tab
If you are MacOS user, please use: 
`keytool -list -v -keystore ~/.android/debug.keystore -alias androiddebugkey -storepass android -keypass android`

For the image problem, 
as I can see, your are trying to replace banner image by local asset images. However, banner image just supports image from URL only. We will fix the documents for this part. 

Have a nice day!

**Comment by dttrung26** [comment]
Hi @Kindakart ,
I would like to inform you that InspireUI support does not work in that way sir. 
Please create a new ticket, including relevant information, and fill out the form to verify. 
Best!

**Comment by Kindakart** [comment]
The app use to use banner from local directory what happen this time.
is it issue with the latest update, please note that fetching the banners from servers is hard i mean, if we place banners from server like unplash, some users will not be get banner after they do download the app

**Comment by Kindakart** [comment]
also please check this screenshot.

if l try to sign up, the app generates this issue
<img width="422" alt="screen" src="https://user-images.githubusercontent.com/70471823/91857503-9e5e3100-ec85-11ea-8b1e-8c23deec6312.png">
