### ISSUE TITLE
OneSignalNotificationServiceExtension

### ISSUE THREAD

**Issue by amin5400** [inspireui/support#4786]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: Run Main Dart
- [[!] Automatically assigning platform `iOS` with version `10.3` on target `OneSignalNotificationServiceExtension` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`. ] first issue
- [ ] second issue
- [ ] third issue

+ Product & version: FluxStore Pro
+ Flutter (or React Native) version: flutter
+ Testing Device/Simulator: yes
+ Screenshot issues (drag the file to attach here):

**Comment by minhcasi** [comment]
@amin5400 - pls help to share the full log and include the screenshot of the issue, the sharing warning may not be related to the issues

Pls continuous with your open ticket support instead of open the new one - #4753
