### ISSUE TITLE
Technical issues in signup and placing orders

### ISSUE THREAD

**Issue by subham54321** [inspireui/support#4788]
I have purchased flux store for woo commerce(Version-FluxStore-woo-1.7.7), I m facing two issues kindly help me in resolving these two major issues.

1- while signing up, nor the user or the admin of the website is receiving the notification ( kindly tell me the steps to modify the API calls so that I can modify to notify both ).

2- I am unable to place the order that is unable to review the orders after providing the address(when clicked on continue to review order it doesn't show any activity), also since I have selected India as my country I am unable to get Indian [city.]

![Screenshot_20200828-022235](https://user-images.githubusercontent.com/24961400/91636085-8edbaf80-ea1b-11ea-8b2e-72c31df07374.jpg)
![Screenshot_20200828-022224](https://user-images.githubusercontent.com/24961400/91636088-9307cd00-ea1b-11ea-92e5-b02a261bc3de.jpg)

Attaching the screenshot.

Beg you to kindly solve my problem for which I shall be obliged to you.

**Comment by minhcasi** [comment]
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support https://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by subham54321** [comment]
I have filled the form, now kindly resolve the issue

**Comment by subham54321** [comment]
Hello sir, kindly help me solving the problem. I am unable to place order from the application due the above stated error. I am unable to process further after shipping method option.

**Comment by minhtruong315** [comment]
@subham54321 can u send me common folder and admin account to login your website via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/4788

**Comment by subham54321** [comment]
@minhtruong315  I have dropped the common folder as well as the admin account to the given email id.

Please resolve the issue ASAP.

**Comment by subham54321** [comment]
You can login in(and then can go to dashboard) by going through this url https://www.utkalmerchandise.com/my-account/

**Comment by subham54321** [comment]
Sir, please solve this issue on urgent basis. Please it's urgently required

**Comment by subham54321** [comment]
I have found the solution to this problem but the thing is while placing the orders my orders status isn't under processing rather it's under pending payment. I want it to be under processing how can I do it?

**Comment by minhtruong315** [comment]
@subham54321 you can enable "UpdateOrderStatus" in common/config/payments.dart

**Comment by subham54321** [comment]
Still the new user isn't notified while creating new user via email. I think the notification parameter is set to false, from where can I change this parameter.

**Comment by minhtruong315** [comment]
> I have found the solution to this problem but the thing is while placing the orders my orders status isn't under processing rather it's under pending payment. I want it to be under processing how can I do it?

**Comment by minhtruong315** [comment]
> Still the new user isn't notified while creating new user via email. I think the notification parameter is set to false, from where can I change this parameter.
> 
> And secondly I am unable to use the coupons which is there in my website

I dont understand. You're asking about orders status?

**Comment by subham54321** [comment]
> > Still the new user isn't notified while creating new user via email. I think the notification parameter is set to false, from where can I change this parameter.
> > And secondly I am unable to use the coupons which is there in my website
> 
> I dont understand. You're asking about orders status?

I mean to say that when the new user is signing up (registering) in our website through the mobile application(flux store) then the user must get the confirmation of successful registration through email but they aren't receiving. 

Second issue is the users aren't not able to apply the COUPON CODE which is provided by our website.

Kindly help me in the above stated issues, for which I shall be obliged to you.

**Comment by minhtruong315** [comment]
> I have found the solution to this problem but the thing is while placing the orders my orders status isn't under processing rather it's under pending payment. I want it to be under processing how can I do it?

how about this issue? it's resolved?

**Comment by subham54321** [comment]
> > I have found the solution to this problem but the thing is while placing the orders my orders status isn't under processing rather it's under pending payment. I want it to be under processing how can I do it?
> 
> how about this issue? it's resolved?

Yes this exact problem has been resolved.

**Comment by subham54321** [comment]
> I have purchased flux store for woo commerce(Version-FluxStore-woo-1.7.7), I m facing two issues kindly help me in resolving these two major issues.
> 
> 1- while signing up, nor the user or the admin of the website is receiving the notification ( kindly tell me the steps to modify the API calls so that I can modify to notify both ).
> 
> 2- I am unable to place the order that is unable to review the orders after providing the address(when clicked on continue to review order it doesn't show any activity), also since I have selected India as my country I am unable to get Indian [city.]
> 
> ![Screenshot_20200828-022235](https://user-images.githubusercontent.com/24961400/91636085-8edbaf80-ea1b-11ea-8b2e-72c31df07374.jpg)
> ![Screenshot_20200828-022224](https://user-images.githubusercontent.com/24961400/91636088-9307cd00-ea1b-11ea-92e5-b02a261bc3de.jpg)
> 
> Attaching the screenshot.
> 
> Beg you to kindly solve my problem for which I shall be obliged to you.

Here the first stated issue has not been solved.
Kindly solve this issue and the coupon issue too ,for which I shall be obliged to you.

**Comment by minhtruong315** [comment]
<img width="945" alt="Screen Shot 2020-09-02 at 4 30 44 PM" src="https://user-images.githubusercontent.com/10402500/91964705-ad9eb680-ed39-11ea-9828-892a4dc97ffd.png">
You selected wrong state. please choose Orissa. You can check list state in config/states/state_in.json. it needs to map with your website

**Comment by subham54321** [comment]
> <img alt="Screen Shot 2020-09-02 at 4 30 44 PM" width="945" src="https://user-images.githubusercontent.com/10402500/91964705-ad9eb680-ed39-11ea-9828-892a4dc97ffd.png">
> 
> You selected wrong state. please choose Orissa. You can check list state in config/states/state_in.json. it needs to map with your website. or you can delete state_in.json file to get list states in the website

I have already sorted this out, kindly help me with the issues I have stated in the above replies

**Comment by subham54321** [comment]
> > > Still the new user isn't notified while creating new user via email. I think the notification parameter is set to false, from where can I change this parameter.
> > > And secondly I am unable to use the coupons which is there in my website
> > 
> > 
> > I dont understand. You're asking about orders status?
> 
> I mean to say that when the new user is signing up (registering) in our website through the mobile application(flux store) then the user must get the confirmation of successful registration through email but they aren't receiving.
> 
> Second issue is the users aren't not able to apply the COUPON CODE which is provided by our website.
> 
> Kindly help me in the above stated issues, for which I shall be obliged to you.

Kindly solve this issue, please

**Comment by minhtruong315** [comment]
@subham54321 can u upload your source code to github and invite me: minhtruong315@gmail.com
send me admin account to login your website as well.
I will help you check coupon issue.
Thanks

**Comment by subham54321** [comment]
Please help me today, I want my app to publish

**Comment by minhtruong315** [comment]
Did you upload the source code to github and invite me?

**Comment by subham54321** [comment]
No, tell me which code do you want

**Comment by minhtruong315** [comment]
full your source code. Are you using Fluxstore 1.7.7?

**Comment by subham54321** [comment]
Yes it's 1.7.7 It's around 1 gb of file, should I upload it.

**Comment by minhtruong315** [comment]
pls delete build folder and ios/Pods folder then upload it

**Comment by subham54321** [comment]
Can you help me solve the issues now, I'll publish it in playstore

**Comment by subham54321** [comment]
It's urgent

**Comment by subham54321** [comment]
Sir please tell me

**Comment by minhtruong315** [comment]
@subham54321 You dont upload the source code to github and invite me. how to check and fix it?

**Comment by subham54321** [comment]
Okay sir I m uploading. Till then I m facing a new issue that is when ever the internet is switched off I am not getting the splash screen instead I am getting a error screen.
![Screenshot_20200823-171549](https://user-images.githubusercontent.com/24961400/92068752-5fcf9000-edc5-11ea-9b06-a10ff57829c1.jpg)

**Comment by subham54321** [comment]
> @subham54321 You dont upload the source code to github and invite me. how to check and fix it?

here's the link to my repository, kindly check and tell me the required changes.
https://github.com/subham54321/utkalmerchandise

**Comment by minhtruong315** [comment]
@subham54321 pls make it private and upload source code folder. not zip it

**Comment by subham54321** [comment]
> @subham54321 pls make it private and upload source code folder. not zip it

give me your mail id ill add you as the collaborator

**Comment by minhtruong315** [comment]
minhtruong315@gmail.com

**Comment by subham54321** [comment]
sent you the invite

**Comment by subham54321** [comment]
please check the zipped files, i am unable to upload the full folder at once

**Comment by minhtruong315** [comment]
@subham54321 I fixed coupon issue in your source code. pls pull the source code and check again

**Comment by subham54321** [comment]
may i know what was the issue?

**Comment by subham54321** [comment]
> Okay sir I m uploading. Till then I m facing a new issue that is when ever the internet is switched off I am not getting the splash screen instead I am getting a error screen.
> ![Screenshot_20200823-171549](https://user-images.githubusercontent.com/24961400/92068752-5fcf9000-edc5-11ea-9b06-a10ff57829c1.jpg)

and also please solve this issue too .

**Comment by minhtruong315** [comment]
Fixed. pls check again

**Comment by subham54321** [comment]
> Fixed. pls check again

@minhtruong315 pl tell me where to change the code so that I'll do the required changes here

**Comment by subham54321** [comment]
I have followed the your youtube tutorials on push messaging using fire base(https://www.youtube.com/watch?v=rcJEB-tcLNU&list=PLcF-HiQy-jOJAD8btGgr_CHcUmYyN8GgY&index=19), but i am unable to receive the push message.

**Comment by subham54321** [comment]
@minhtruong315  please help

**Comment by minhtruong315** [comment]
> > Fixed. pls check again
> 
> I want to modify the screen which is shown to the user when there mobile data isnt ON.

We dont support customize code

**Comment by minhtruong315** [comment]
> I have followed the your youtube tutorials on push messaging using fire base(https://www.youtube.com/watch?v=rcJEB-tcLNU&list=PLcF-HiQy-jOJAD8btGgr_CHcUmYyN8GgY&index=19), but i am unable to receive the push message.
> 
> I have successfully changed the bundle id, package name and google services.json file looking at the docs provided.

Add my email: minhtruong315@gmail.com to your firebase project

**Comment by subham54321** [comment]
> > I have followed the your youtube tutorials on push messaging using fire base(https://www.youtube.com/watch?v=rcJEB-tcLNU&list=PLcF-HiQy-jOJAD8btGgr_CHcUmYyN8GgY&index=19), but i am unable to receive the push message.
> > I have successfully changed the bundle id, package name and google services.json file looking at the docs provided.
> 
> Add my email: [minhtruong315@gmail.com](mailto:minhtruong315@gmail.com) to your firebase project

Added you as an editor.
Please tell me what changes you wanted to do so that I can also learn and deploy it myself next time.
Since your YouTube tutorial isn't working for me.

**Comment by subham54321** [comment]
> > > Fixed. pls check again
> > 
> > 
> > I want to modify the screen which is shown to the user when there mobile data isnt ON.
> 
> We dont support customize code

When the mobile data is switched off the user should be shown a screen "not connected to internet" .

**Comment by subham54321** [comment]
> > > I have followed the your youtube tutorials on push messaging using fire base(https://www.youtube.com/watch?v=rcJEB-tcLNU&list=PLcF-HiQy-jOJAD8btGgr_CHcUmYyN8GgY&index=19), but i am unable to receive the push message.
> > > I have successfully changed the bundle id, package name and google services.json file looking at the docs provided.
> > 
> > 
> > Add my email: [minhtruong315@gmail.com](mailto:minhtruong315@gmail.com) to your firebase project
> 
> Added you as an editor.
> Please tell me what changes you wanted to do so that I can also learn and deploy it myself next time.
> Since your YouTube tutorial isn't working for me.

Please solve the issues sir, I want to publish this app with immediate effect

**Comment by subham54321** [comment]
When is my issue going to be resolved?

**Comment by subham54321** [comment]
Sir please try to understand and kindly provide me the support

**Comment by minhcasi** [comment]
@subham54321 - we are checking the issue and will let you know - thank you!

**Comment by subham54321** [comment]
I have two more problems I m unable to fit the full image in the slider as shown in the attachment. Though I have kept the same dimensions as you have kept in the demo version of flux store.

Secondly I am unable to add text in the bottom part of the navigation menu drawer, kindly help me with these so that I'll proceed further.
![Screenshot_20200905-100446](https://user-images.githubusercontent.com/24961400/92297723-d1dbdc80-ef5f-11ea-99d9-17b6d3980e07.jpg)

**Comment by subham54321** [comment]
@minhtruong315 @minhcasi  its very painful to say that I am not geting the lind of support i should get. My organization is willing to buy more of your products but if this is the scenario how can we proceed. We have invested the money and facing a lot of issues gradually.

Today when i tried building the app with the below mentioned i am getting the error as there in the screenshot.

steps:

1- creation of key store file   using keytool -genkey -v -keystore d:/key.jks -storetype JKS -keyalg RSA -keysize 2048 -validity 10000 -alias key
2- updating the key.properties file (storePassword,
keyPassword,
keyAlias,
storeFile=android/app/key.jks)
3-replacing  key.jks file to source/certs folder with the newly generated key file.
4-flutter build apk --split-per-abi

I am getting the build error as below:
![image](https://user-images.githubusercontent.com/24961400/92300145-238f6180-ef76-11ea-8561-0b52346f2183.png)

at least resolve this issue today so that i can publish the app. I would be obliged to you always for this help.

**Comment by minhtruong315** [comment]
@subham54321 Your keystore is in d:/key.jks or android/app/key.jks?
```
keytool -genkey -v -keystore d:/key.jks -storetype JKS -keyalg RSA -keysize 2048 -validity 10000 -alias key
```
```
storeFile=android/app/key.jks
```

**Comment by subham54321** [comment]
I have found several bugs in the application, kindly resolve it, i have already rolled out the application which I think I shouldn't have done since this framework is too bugy for now to release.

Kindly solve the stated bugs and also tell me the procedure of updating the app in playstore.

Bugs:-
1- though I have updated WhatsApp number, smart chat isn't redirecting to my WhatsApp number when clicked.
2- I can't rate the products.
3- shop button on the drawer (navigation menu) isn't working.
4- when clicked on a category, after going on category tab in the footer widget, located after the home the black screen is flashed, and when the app is restarted it opens 
5- still when the new user register using their email ids they don't receive their confirmation of registration via email.

Kindly solve the problem and atleast reply and be responsible since I have bearing the losses due to these problems.

Request you to kindly assist.

**Comment by subham54321** [comment]
> I have found several bugs in the application, kindly resolve it, i have already rolled out the application which I think I shouldn't have done since this framework is too bugy for now to release.
> 
> Kindly solve the stated bugs and also tell me the procedure of updating the app in playstore.
> 
> Bugs:-
> 1- though I have updated WhatsApp number, smart chat isn't redirecting to my WhatsApp number when clicked.
> 2- I can't rate the products.
> 3- shop button on the drawer (navigation menu) isn't working.
> 4- when clicked on a category, after going on category tab in the footer widget, located after the home the black screen is flashed, and when the app is restarted it opens
> 5- still when the new user register using their email ids they don't receive their confirmation of registration via email.
> 
> Kindly solve the problem and atleast reply and be responsible since I have bearing the losses due to these problems.
> 
> Request you to kindly assist.

Supporting screenshots
![Screenshot_20200906-113405](https://user-images.githubusercontent.com/24961400/92319467-2c476c80-f036-11ea-8eb6-203287e62f21.jpg)
![Screenshot_20200906-113300](https://user-images.githubusercontent.com/24961400/92319469-2fdaf380-f036-11ea-8b55-fb9147d619fd.jpg)
![Screenshot_20200906-113400](https://user-images.githubusercontent.com/24961400/92319470-30738a00-f036-11ea-8a8c-c9db14df991a.jpg)

**Comment by wisharabia** [comment]
Can you please share how you solved the coupon issue as im having the same issue on my end?

**Comment by subham54321** [comment]
> > I have found several bugs in the application, kindly resolve it, i have already rolled out the application which I think I shouldn't have done since this framework is too bugy for now to release.
> > Kindly solve the stated bugs and also tell me the procedure of updating the app in playstore.
> > Bugs:-
> > 1- though I have updated WhatsApp number, smart chat isn't redirecting to my WhatsApp number when clicked.
> > 2- I can't rate the products.
> > 3- shop button on the drawer (navigation menu) isn't working.
> > 4- when clicked on a category, after going on category tab in the footer widget, located after the home the black screen is flashed, and when the app is restarted it opens
> > 5- still when the new user register using their email ids they don't receive their confirmation of registration via email.
> > Kindly solve the problem and atleast reply and be responsible since I have bearing the losses due to these problems.
> > Request you to kindly assist.
> 
> Supporting screenshots
> ![Screenshot_20200906-113405](https://user-images.githubusercontent.com/24961400/92319467-2c476c80-f036-11ea-8eb6-203287e62f21.jpg)
> ![Screenshot_20200906-113300](https://user-images.githubusercontent.com/24961400/92319469-2fdaf380-f036-11ea-8b55-fb9147d619fd.jpg)
> ![Screenshot_20200906-113400](https://user-images.githubusercontent.com/24961400/92319470-30738a00-f036-11ea-8a8c-c9db14df991a.jpg)

It has been around 6 days since I posted an issue, are you going to resolve it?

**Comment by minhtruong315** [comment]
@subham54321 can u help me record video for your issues. it's easy to understand. Thanks

**Comment by subham54321** [comment]
I can't login using Google and fb, kindly check the issue.
![Screenshot_20200916-175311](https://user-images.githubusercontent.com/24961400/93336692-bae19800-f845-11ea-893a-01bcd07a8b9b.jpg)

**Comment by subham54321** [comment]
> I can't login using fb, kindly check the issue.
> 
> ![Screenshot_20200916-175723](https://user-images.githubusercontent.com/24961400/93337032-304d6880-f846-11ea-9234-8ac749c8d8b2.jpg)

Can you please help me fix this issue @minhtruong315

**Comment by subham54321** [comment]
I kindly request you to Please resolve the issues asap

**Comment by subham54321** [comment]
> @subham54321 I fixed coupon issue in your source code. pls pull the source code and check again

Cashback coupons aren't working properly. It should be added as a cashback rather than giving direct discount. Cashback coupons are giving direct discount.
Try the coupon UM50 it's giving cashback in website but not in mobile application.

**Comment by subham54321** [comment]
Will you help me to solve the problem?

**Comment by minhcasi** [comment]
Greetings from InspireUI 🎉
To improve user experience during support, we are announcing that a new ticket support system is available on this link https://support.inspireui.com 

Please help to move your next comment on the new support system (you could mention this ticket so that the team could know more about the ticket's history) - thank you for your time!
