### ISSUE TITLE
[MStore Multi vendor]couple issues with the app

### ISSUE THREAD

**Issue by lotfinoluffy** [inspireui/support#479]
**Required Info (please complete the following information):**
 - Product: MStore Multi vendor
 - Your Purchased Code: 00cdcfXX-e5XX-4046-XX21-e99XXb468368 (edited a bit)
(we may not reply if you are not our customer)

**Describe the bug**
- rebuilder won't save the detail of my install at all
- when I go trough and edit the appconfig trough atom, signed as a vendor, I can't post any product and even with the http://dokan.mstore.io/ install (user have the right to add products) and won't work even from your demo
- have to click on return (clicking outside to get the next button or confirm) doesn't work, and then the next button is barely visible to click on it
- images won't load (some do for the 3 products layout) from my install and take forever to load from the demo (images are served from wp cdn or wpmudev one
- images on the payment or delivery methods are so big on the ipad 
- while using the eject command, and trying to build the app, I get error and build just fail

**Screenshots**

https://imgur.com/YNJpLGb
https://imgur.com/bZWsKXz
https://imgur.com/yYIkIaQ
https://imgur.com/0j7BERC
https://imgur.com/I4RaQHD
https://imgur.com/vwTQxrl
https://imgur.com/3W8wtYI
https://imgur.com/sWe8U2p
https://imgur.com/wdYwGbJ

**Additional context**
Add any other detail logs about the problem here.
If possible please share your config.js that use for the app setting

https://drive.google.com/open?id=1Nm1s-fqkCVNWjwJBRxyvGbdPJSouAKvq
https://drive.google.com/open?id=1G58PIYSxWCBWdE1W3A8ieuIKFh26xtHT

**Comment by thangvo9x** [comment]
Please check your Config with plugin  JWT Plugin 
you can refer here: https://wordpress.org/plugins/jwt-authentication-for-wp-rest-api/
The error will be gone when the config is correct.
Thanks

**Comment by lotfinoluffy** [comment]
I deactivate it the plugin so im not really relying on it, also all these issues will be solved by just that

id appreciate it if you could actually spend a bit of time to read the issues and help fixing them, don't want to spend weeks over this

thanks

**Comment by thangvo9x** [comment]
Thanks but you can not create a new listing when not using that plugin - JWT.

**Comment by lotfinoluffy** [comment]
ok so that's about posting articles (and even with your demo) its doesn't work
or an easy way to configure the plugin !?

any fixes for the other issues tho ?
thanks

**Comment by lotfinoluffy** [comment]
also im on an nix server so not sure how it should be configured without an htaccess file

**Comment by lotfinoluffy** [comment]
the chat feature isn't working either 

![IMG_0377](https://user-images.githubusercontent.com/25268600/55683667-19f56a80-593a-11e9-9f2b-d5576e7e99f4.png)

**Comment by thangvo9x** [comment]
Hi. 
1. You can reference here for NGINX 
https://codex.wordpress.org/Nginx
2. That error is coming from the account info. You must have filled in that account information.
Thanks

**Comment by lotfinoluffy** [comment]
This doesn’t help at all
Your emails are just getting shorter and shorter, do you even want to help ?!!?

I have many issues with the app not just the JWT plugin

You just added according to the changelog, so the least you can do is actually pointing me to the right documentation, or part of it, not the whole thing and just wait for the next part of the answer

Thank you

**Comment by thangvo9x** [comment]
Hi, Sorry about that. You can share those problems here. If you are unhappy. You can request a ticket for this refund. Thanks

**Comment by lotfinoluffy** [comment]
do you wanna drive me nuts on purpose on what !?
I clearly mentioned most here already, if you can actually read and then reply to one issue at the time id appreciate it
so far im getting one liners without any results

**Comment by lotfinoluffy** [comment]
any answer soon !?

**Comment by thangvo9x** [comment]
As the previous comment, I must config NGINX on your server such as link which was sent.
https://codex.wordpress.org/Nginx
Thanks .

**Comment by lotfinoluffy** [comment]
Hi

You or I must configure it ?

And I contacted also the host and wpmudev and they tried the rules of the plugins but it doesn’t work
Don’t you have have a clear config rules to just add ?

Thanks

**Comment by lotfinoluffy** [comment]
![Screen Shot 2019-04-16 at 9 49 22 AM](https://user-images.githubusercontent.com/25268600/56195551-1d20e280-602d-11e9-8eb9-7605c717316c.png)

**Comment by lotfinoluffy** [comment]
and any solution about the rest of the issues ?

**Comment by thangvo9x** [comment]
https://github.com/inspireui/support/issues/500

**Comment by ZamanGoraya** [comment]
i do login in my app but it always run as vender ... how i can run it as customer...?

**Comment by ZamanGoraya** [comment]
i do login in my app but it always run as vender ... how i can run it as customer...?

even i loged in with customer id...
