### ISSUE TITLE
Issue App Store Connect

### ISSUE THREAD

**Issue by heftipascal1** [inspireui/support#4791]
Hi, we have trouble to put the app in the App Store see the pictures
![Bildschirmfoto 2020-08-22 um 12 09 52](https://user-images.githubusercontent.com/67189625/91639181-238edf00-ea15-11ea-9079-ea48c73ba41a.png)
![Bildschirmfoto 2020-08-22 um 12 10 39 (1)](https://user-images.githubusercontent.com/67189625/91639182-24c00c00-ea15-11ea-810c-da98e3e8e4bd.png)
![Bildschirmfoto 2020-08-22 um 12 12 56 (1)](https://user-images.githubusercontent.com/67189625/91639183-24c00c00-ea15-11ea-9f96-256e1f860b9b.png)

We think, that Apple was the problem, but we have asked them and they said that the code is not correct? 

![Unbenannt](https://user-images.githubusercontent.com/67189625/91639214-52a55080-ea15-11ea-9f5b-c3d0faca66d4.JPG)

What Problem is that?

**Comment by minhcasi** [comment]
Pls check following solutions:

- try to check the option "Automatically manage signing"

- make sure to run `flutter build ios` before running archive the project

- clean up the XCode caching. 

- not change the app name direct from XCode, change it from the info.plist file - https://docs.inspireui.com/fluxstore/delivery/

**Comment by minhcasi** [comment]
Let us know your checking, thank you!
