### ISSUE TITLE
Shipping, Payment and Search don't work

### ISSUE THREAD

**Issue by kahloot** [inspireui/support#4792]
1- Shipping methods only appear, which is free shipping, noting that I did not activate them in the store
2- Payment shows an error that there is no API as shown in the Postman See the following line:
( https://www.hws.sa/index.php?route=extension/mstore/payment_method
{"success":1,"error":[],"data":{"error_warning":"Warning: No Payment options are available. Please <a
  href=\"http:\/\/www.hws.sa\/index.php?route=information\/contact\">contact us<\/a> for
  assistance!","payment_methods":[],"code":"","comment":"no comment"}} )
3- The search does not work as it is in the image, no results are shown

**Comment by kahloot** [comment]
![bad57c96-9b05-4c14-ac5a-fc5e0f53948f](https://user-images.githubusercontent.com/45464105/91639418-1971de00-ea1f-11ea-9df8-702fba523c55.jpg)
![876d3502-47b0-480c-a656-ead308232584](https://user-images.githubusercontent.com/45464105/91639420-1a0a7480-ea1f-11ea-8c4d-7132777bd6ce.jpg)
![00454705-d7fa-4484-bcbb-399a84824c5b](https://user-images.githubusercontent.com/45464105/91639422-1aa30b00-ea1f-11ea-951b-11c21e90a518.jpg)

**Comment by kahloot** [comment]
![6111c421-28c3-4a7f-895e-29a2b26cd4f2](https://user-images.githubusercontent.com/45464105/91639797-b0d83080-ea21-11ea-86cf-690095770d15.jpg)

**Comment by minhcasi** [comment]
Hi @kahloot - could i know this ticket related to opencart issue?

**Comment by minhcasi** [comment]
Thank you so much for your rating on our product, i've upgraded the ticket as high-priority support.

@minhtruong315 - please help to investigate the issue

**Comment by kahloot** [comment]
yes opencart

**Comment by kahloot** [comment]
kahloot commented 5 hours ago

**Comment by minhcasi** [comment]
@minhtruong315 - please help to investigate this issue - thank you!

**Comment by kahloot** [comment]
`please help to investigate this issue - thank you!`
how can I help

**Comment by kahloot** [comment]
It seems that you do not have solutions to the error, since yesterday I opened the issues, so please return the amount and cancel the license.
I'm in a hurry

**Comment by kahloot** [comment]
kahloot commented 2 days ago

**Comment by minhtruong315** [comment]
@kahloot can u send me admin account via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/4792

**Comment by kahloot** [comment]
sent

**Comment by minhtruong315** [comment]
Hi @kahloot I see your website is showing payment methods. Can u record screen?
![Simulator Screen Shot - iPhone 11 - 2020-08-31 at 16 03 26](https://user-images.githubusercontent.com/10402500/91702858-87dfa900-eba3-11ea-9414-5b0a2e2f0b51.png)

**Comment by kahloot** [comment]
I do not show these options
In any case, there are options that are not available, such as SMSA charging
But the payment is correct. All options are available through the picture that you attached

**Comment by kahloot** [comment]
I do not show these options
And in all cases there is found choices such as shipping Semsa
But the payment is correct. All options are available through the picture that you attached

**Comment by kahloot** [comment]
I also need to add brands to shop across brands

**Comment by minhtruong315** [comment]
@kahloot I only support you integration issues. I dont support customize code. So can u list me issues for integration?

**Comment by kahloot** [comment]
ٍshipping method Semsa supposed to show all States
But it has never shown

**Comment by kahloot** [comment]
samsa

**Comment by minhtruong315** [comment]
<img width="923" alt="Screen Shot 2020-08-31 at 4 58 46 PM" src="https://user-images.githubusercontent.com/10402500/91708239-418e4800-ebab-11ea-8b8f-195049889a07.png">
I see on your website doesn't config to allow all countries

**Comment by kahloot** [comment]
> <img alt="Screen Shot 2020-08-31 at 4 58 46 PM" width="923" src="https://user-images.githubusercontent.com/10402500/91708239-418e4800-ebab-11ea-8b8f-195049889a07.png">
> 
> I see on your website doesn't config to allow all countries
my store is not for all countries 
only for Saudi Arabia

**Comment by kahloot** [comment]
If the client does not complete the profile and did not add its title you should show him the error message asking him to add title
But the situation is currently in the application and the page will not work if he has not added its address

**Comment by kahloot** [comment]
The customer should see two shippment methods
How to add the add-on if the customer in Riyadh sees two shipping methods
1 Shipping by Riyadh Shipping
2 Shipping via SMSA
If it is outside the city of Riyadh
1 Shipping via SMSA
2 Ship by normal shipping

**Comment by minhtruong315** [comment]
> If the client does not complete the profile and did not add its title you should show him the error message asking him to add title
> But the situation is currently in the application and the page will not work if he has not added its address

I dont understand

**Comment by minhtruong315** [comment]
> The customer should see two shippment methods
> How to add the add-on if the customer in Riyadh sees two shipping methods
> 1 Shipping by Riyadh Shipping
> 2 Shipping via SMSA
> If it is outside the city of Riyadh
> 1 Shipping via SMSA
> 2 Ship by normal shipping

Can u record video for your website for this business?
it's easy to understand

**Comment by kahloot** [comment]
[ScreenRecorderProject2.zip](https://github.com/inspireui/support/files/5155050/ScreenRecorderProject2.zip)
as attached

**Comment by kahloot** [comment]
no answer

**Comment by minhtruong315** [comment]
@kahloot I will investigate and let u know

**Comment by minhtruong315** [comment]
We have spent sometime to check the integration on your site, but unfortunately the site is using advance shipping Opencart extension that does not support on current Fluxstore version - we will investigate to resolve it in the future upgrade, but in the meantime you may customize this feature - thank you for your time

**Comment by kahloot** [comment]
We have spent sometime to check the integration on your site, but
unfortunately the site is using advance shipping Opencart extension that
does not support on current Fluxstore version - we will investigate to
resolve it in the future upgrade, but in the meantime you may customize
this feature - thank you for your time

so what now
refund please

‫في الأحد، 6 سبتمبر 2020 في 6:39 ص تمت كتابة ما يلي بواسطة ‪minhtruong315‬‏
<‪notifications@github.com‬‏>:‬
