### ISSUE TITLE
MStore Pro Setup Problem

### ISSUE THREAD

**Issue by JokerZ01** [inspireui/support#4793]
Hello,
I bought Mstore Pro and installed CEBuilder. When I selected folder in Setup on CEBuilder, I had a type error like : Cannot read property 'url' of defined.
Also, I have already watched Youtube videos on your channel.

https://i.snipboard.io/ECrfW5.jpg

**Comment by minhcasi** [comment]
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support https://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by JokerZ01** [comment]
I installed Wordpress, and WooCommerce inside. I made some changes with url, consumer key and consumer secret in config.js. Now, I can see the products but register and login part are broken.

**Comment by parimalpanchal90** [comment]
Hello JokerZ01,

I installed Wordpress, and WooCommerce inside. I made some changes with url, consumer key and consumer secret in config.js. Now, I can see the products but register and login part are broken.

**How you solved this issue?**

Thank you in advance

**Comment by JokerZ01** [comment]
Hi @parimalpanchal90,
I couldn't solve it. You can follow the topic here:
https://github.com/inspireui/support/issues/4871
Do you have the same problem? Could you solve it?

**Comment by parimalpanchal90** [comment]
Hello @JokerZ01 
Yes, getting same error but i also couldn't solve it yet.

**Comment by parimalpanchal90** [comment]
Hello @JokerZ01

Login/registration broken issue resolved from my side.
You can check our conversion between me and minhcasi

https://github.com/inspireui/support/issues/4901

Thank you
