### ISSUE TITLE
Coupon issue not working if i enable Woocommerce Brands plugins 

### ISSUE THREAD

**Issue by digital0life** [inspireui/support#4794]
Hello 

I have isuse on APP the issue as following when I enable plugins called WooCommerce Brands
the placed order not working and give me error .. HTML response as below 

=======================
`<!DOCTYPE html>
<html lang="en-US">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="viewport" content="width=device-width">
<meta name='robots' content='noindex,follow' />
<title>WordPress &rsaquo; Error</title>
<style type="text/css">
		html {
			background: #f1f1f1;
		}
		body {
			background: #fff;
			color: #444;
			font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
			margin: 2em auto;
			padding: 1em 2em;
			max-width: 700px;
			-webkit-box-shadow: 0 1px 3px rgba(0, 0, 0, 0.13);
			box-shadow: 0 1px 3px rgba(0, 0, 0, 0.13);
		}
		h1 {
			border-bottom: 1px solid #dadada;
			clear: both;
			color: #666;
			font-size: 24px;
			margin: 30px 0 0 0;
			padding: 0;
			padding-bottom: 7px;
		}
		#error-page {
			margin-top: 50px;
		}
		#error-page p,
		#error-page .wp-die-message {
			font-size: 14px;
			line-height: 1.5;
			margin: 25px 0 20px;
		}
		#error-page code {
			font-family: Consolas, Monaco, monospace;
		}
		ul li {
			margin-bottom: 10px;
			font-size: 14px ;
		}
		a {
			color: #0073aa;
		}
		a:hover,
		a:active {
			color: #006799;
		}
		a:focus {
			color: #124964;
			-webkit-box-shadow:
				0 0 0 1px #5b9dd9,
				0 0 2px 1px rgba(30, 140, 190, 0.8);
			box-shadow:
				0 0 0 1px #5b9dd9,
				0 0 2px 1px rgba(30, 140, 190, 0.8);
			outline: none;
		}
		.button {
			background: #f7f7f7;
			border: 1px solid #ccc;
			color: #555;
			display: inline-block;
			text-decoration: none;
			font-size: 13px;
			line-height: 2;
			height: 28px;
			margin: 0;
			padding: 0 10px 1px;
			cursor: pointer;
			-webkit-border-radius: 3px;
			-webkit-appearance: none;
			border-radius: 3px;
			white-space: nowrap;
			-webkit-box-sizing: border-box;
			-moz-box-sizing:    border-box;
			box-sizing:         border-box;

			-webkit-box-shadow: 0 1px 0 #ccc;
			box-shadow: 0 1px 0 #ccc;
			vertical-align: top;
		}

		.button.button-large {
			height: 30px;
			line-height: 2.15384615;
			padding: 0 12px 2px;
		}

		.button:hover,
		.button:focus {
			background: #fafafa;
			border-color: #999;
			color: #23282d;
		}

		.button:focus {
			border-color: #5b9dd9;
			-webkit-box-shadow: 0 0 3px rgba(0, 115, 170, 0.8);
			box-shadow: 0 0 3px rgba(0, 115, 170, 0.8);
			outline: none;
		}

		.button:active {
			background: #eee;
			border-color: #999;
			-webkit-box-shadow: inset 0 2px 5px -3px rgba(0, 0, 0, 0.5);
			box-shadow: inset 0 2px 5px -3px rgba(0, 0, 0, 0.5);
		}

			</style>
</head>
<body id="error-page">
<div class="wp-die-message"><p>There has been a critical error on your website.</p><p><a href="https://wordpress.org/support/article/debugging-in-wordpress/">Learn more about debugging in WordPress.</a></p></div></body>
</html>`
=======================

from debug,, i got the below 
-----------------------------------------------
[28-Aug-2020 19:30:02 UTC] PHP Fatal error:  Uncaught Error: Call to a member function is_empty() on null in /var/www/vhosts/tas/httpdocs/wp-content/plugins/woocommerce-brands/includes/class-wc-brands-coupons.php:130
Stack trace:
#0 /var/www/vhosts/tas/httpdocs/wp-includes/class-wp-hook.php(287): WC_Brands_Coupons->brand_exclusion_error()
#1 /var/www/vhosts/tas/httpdocs/wp-includes/plugin.php(206): WP_Hook->apply_filters()
#2 /var/www/vhosts/tas/httpdocs/wp-content/plugins/woocommerce/includes/class-wc-discounts.php(971): apply_filters()
#3 /var/www/vhosts/tas/httpdocs/wp-content/plugins/woocommerce/includes/class-wc-discounts.php(250): WC_Discounts->is_coupon_valid()
#4 /var/www/vhosts/tas/httpdocs/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-order.php(1130): WC_Discounts->apply_coupon()
#5 /var/www/vhosts/tas/httpdocs/wp-content/plugins/woocommerce/packages/woocommerce-rest-api/src/Controllers/Version3/class-wc-rest-orders-controller.php(53): WC_Abstract_Order->apply_coupon()
#6 /var/ww in /var/www/vhosts/tas/httpdocs/wp-content/plugins/woocommerce-brands/includes/class-wc-brands-coupons.php on line 130
-----------------------------------------------

it look like there is something missed in mStore API to handle that ?  coz the coupon process working fine on website ... can u plz anyone advice me what I should do to fix it ?

APP ver:1.7.4

Thanks

**Comment by minhcasi** [comment]
it seems the issues by brand plugin `/var/ww in /var/www/vhosts/tas/httpdocs/wp-content/plugins/woocommerce-brands/includes/class-wc-brands-coupons.php on line 130` - pls try to debug this wordpress plugin to find out the root cause - thank you!

**Comment by digital0life** [comment]
Hi @minhcasi 

thank u for ur quick response, we try to do that but no luck... the issue is everything is working on website but not work on mobile app side .. so can u plz give us some help 


Thanks

**Comment by minhcasi** [comment]
@digital0life - pls give a try to use other Brand plugins to see if it could resolve your issue. 

Sorry as we are not strong on Wordpress backend side so that could not give values solutions to fix this PHP issue 😅
