### ISSUE TITLE
Error FBAudienceNetwork missing.

### ISSUE THREAD

**Issue by kcrbsd** [inspireui/support#4795]
ameenbadri7 We done your commands and other no result  same error FBAudienceNetwork missing. 

Then we some how build app via Xcode but again getting error on publish app on XCode 
No such module 'FBAudienceNetwork' it's same error 

how to fix this.. follow error screen for more details 
<img width="1035" alt="Screenshot 2020-08-29 at 23 28 55" src="https://user-images.githubusercontent.com/27732360/91643292-74232e00-ea4f-11ea-8f9f-d6a6281aea23.png">
<img width="1023" alt="Screenshot 2020-08-29 at 23 24 13" src="https://user-images.githubusercontent.com/27732360/91643298-7b4a3c00-ea4f-11ea-8636-29f5d69e1931.png">

_Originally posted by @kcrbsd in https://github.com/inspireui/support/issues/4708#issuecomment-683323152_

**Comment by kcrbsd** [comment]
Update 
<img width="1042" alt="Screenshot 2020-08-30 at 00 21 12" src="https://user-images.githubusercontent.com/27732360/91644118-bdc34700-ea56-11ea-8770-40dd6f5e675c.png">

**Comment by minhcasi** [comment]
@kcrbsd - could i know if you are using the latest Fluxstore `1.7.7`

**Comment by kcrbsd** [comment]
yes. i'm using fluxstore 1.7.7 and i try with 1.7.6 both same.. 
<img width="407" alt="Screenshot 2020-08-30 at 16 00 03" src="https://user-images.githubusercontent.com/27732360/91656880-f6583480-ead9-11ea-8b55-5eceef055fb3.png">

**Comment by minhcasi** [comment]
If you have tried both versions but did not work, the root cause could be from your pod file issues.  

Please try to follow this guide https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1 

Thank you!

**Comment by minhcasi** [comment]
Let us know your checking - thank you!
