### ISSUE TITLE
Firebase issue and other

### ISSUE THREAD

**Issue by SagarBIjja-trilocode** [inspireui/support#4796]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
- [ firebase login issue ] first issue
- [ sub products are not showing in category or in all products ] second issue
- [banner are static or dynamic? Coz my opencart website has a banner so I have to fetch that banner only whenever i uploads new one it will show same as website in app ] third issue

+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

![image](https://user-images.githubusercontent.com/20185387/91644177-56f25d80-ea57-11ea-990c-76ec990e6e21.jpeg)

**_Step 2 (require): submit proof of purchasing the license on https://verify.inspireui.com **

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@SagarBIjja-trilocode - pls try to follow this guide https://medium.com/@inspireui/setup-google-login-for-flutter-apps-fedc58a490b8 - make sure to update SHA-1 key to your firebase

**Comment by SagarBIjja-trilocode** [comment]
Hello i did everything but same issue

**Comment by minhcasi** [comment]
@SagarBIjja-trilocode - pls try your best to follow the blog guide carefully, this is a common login issue with the Google 
The important is getting the SHA-1 key to register with your Firebase, define on Google Cloud Consent  

Some refer:
- https://www.youtube.com/watch?v=9C4H8-IqVI4 
- https://www.youtube.com/watch?v=i1PvZqGxo84

**Comment by SagarBIjja-trilocode** [comment]
Sorry its not working 
i have done  everything

**Comment by SagarBIjja-trilocode** [comment]
Hi its working now thanks but i got other issue shall i create new one ticket 
for that ?

**Comment by SagarBIjja-trilocode** [comment]
The relevant error-causing widget was: 
  Container file:///E:/Shopfest/lib/widgets/home/category/category_icon_items.dart:94:19
When the exception was thrown, this was the stack: 
#2      Gradient._impliedStops (package:flutter/src/painting/gradient.dart:189:12)
#3      LinearGradient.createShader (package:flutter/src/painting/gradient.dart:422:15)
#4      _BoxDecorationPainter._getBackgroundPaint (package:flutter/src/painting/box_decoration.dart:408:45)
#5      _BoxDecorationPainter._paintBackgroundColor (package:flutter/src/painting/box_decoration.dart:447:31)
#6      _BoxDecorationPainter.paint (package:flutter/src/painting/box_decoration.dart:482:5)
...
The following RenderObject was being processed when the exception was fired: RenderDecoratedBox#106c2 relayoutBoundary=up1
...  parentData: offset=Offset(16.3, 0.0); flex=null; fit=null (can use size)
...  constraints: BoxConstraints(0.0<=w<=70.0, 0.0<=h<=Infinity)
...  size: Size(37.4, 37.4)
...  decoration: BoxDecoration
...    borderRadius: BorderRadius.circular(50.0)
...    gradient: LinearGradient(centerLeft, centerRight, [Color(0x1e0d47a1)], null, TileMode.clamp)
...  configuration: ImageConfiguration(bundle: PlatformAssetBundle#0ce78(), devicePixelRatio: 2.0, locale: en, textDirection: TextDirection.ltr, platform: android)
RenderObject: RenderDecoratedBox#106c2 relayoutBoundary=up1
  parentData: offset=Offset(16.3, 0.0); flex=null; fit=null (can use size)
  constraints: BoxConstraints(0.0<=w<=70.0, 0.0<=h<=Infinity)
  size: Size(37.4, 37.4)
  decoration: BoxDecoration
    borderRadius: BorderRadius.circular(50.0)
    gradient: LinearGradient(centerLeft, centerRight, [Color(0x1e0d47a1)], null, TileMode.clamp)
  configuration: ImageConfiguration(bundle: PlatformAssetBundle#0ce78(), devicePixelRatio: 2.0, locale: en, textDirection: TextDirection.ltr, platform: android)
...  child: RenderPadding#7c93f relayoutBoundary=up2 NEEDS-PAINT
...    parentData: <none> (can use size)
...    constraints: BoxConstraints(0.0<=w<=70.0, 0.0<=h<=Infinity)
...    size: Size(37.4, 37.4)
...    padding: EdgeInsets.all(9.0)
...    textDirection: ltr
...    child: RenderSemanticsAnnotations#1a611 relayoutBoundary=up3 NEEDS-PAINT
...      parentData: offset=Offset(9.0, 9.0) (can use size)
...      constraints: BoxConstraints(0.0<=w<=52.0, 0.0<=h<=Infinity)
...      size: Size(19.4, 19.4)
...      child: RenderImage#c1ef7 relayoutBoundary=up4 NEEDS-PAINT
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(0.0<=w<=52.0, 0.0<=h<=Infinity)
...        size: Size(19.4, 19.4)
...        image: [26×26]
...        width: 19.4
...        height: 19.4
...        color: Color(0xff0d47a1)
...        alignment: center
...        invertColors: false
...        filterQuality: low

**Comment by minhcasi** [comment]
`lib/widgets/home/category/category_icon_items.dart` pls try to check the bug on this file, it could be wrong config from your json file, you could try to generate the json via Fluxbuilder Tool http://fluxbuilder.com/

Also to make sure using the latest Fluxstore `1.7.7` - thank you!
