### ISSUE TITLE
display any images issue & products not publish 

### ISSUE THREAD

**Issue by rabahaldoori** [inspireui/support#4798]
When i upload from vendor account its showing flip on right side 180 degree you see the video.and second thing when its uploaded its not showing.

https://www.youtube.com/watch?v=DdNV1ckn-iQ&feature=youtu.be

<img width="1248" alt="Screen Shot 2020-08-29 at 3 38 13 PM" src="https://user-images.githubusercontent.com/31085177/91646389-4240a600-ea14-11ea-849f-3f1ae95534c1.png">

**Comment by minhcasi** [comment]
The product upload via app needs to be approved from admin side before publishing to the app.

The degree could be caused by your mobile phone, just try to rotate to correct dimension/size before uploading to the website

**Comment by rabahaldoori** [comment]
@minhcasi i didn't take any picture from my phone so i don't need to rotate my phone . i choose any picture you can try your self . and their is any way could the vendor post and publishing direct from vendor ?

**Comment by minhcasi** [comment]
@rabahaldoori - please me double-check on this UX and will confirm the solution - thank you!

**Comment by simonpham** [comment]
Hi @rabahaldoori,

For rotation problem:

A previous version of Flutter has the problem with rotation so we need to handle it in our code. I guess they have fixed it in the latest version.

You can go to `lib/vendor/products/widgets/select_image.dart` and delete or comment out (add // to the begining of the line) this selected code:

![image](https://user-images.githubusercontent.com/8846657/91715780-984e4e80-ebb8-11ea-9d02-d46a475bd298.png)

Thank you for using our product.

**Comment by simonpham** [comment]
About the new product's status is set as Draft on created, please provide us your current version of Dokan and the screenshots of all Dokan configurations.

You can try to disable SEO WordPress plugin first (if installed).

Thank you.

**Comment by rabahaldoori** [comment]
@simonpham 

image issue work thank you. and this is for dolan ,

<img width="1075" alt="Screen Shot 2020-08-31 at 8 33 39 PM" src="https://user-images.githubusercontent.com/31085177/91784829-701b1b80-ebc9-11ea-8d68-47dd5beec69b.png">
<img width="1111" alt="Screen Shot 2020-08-31 at 8 33 49 PM" src="https://user-images.githubusercontent.com/31085177/91784830-71e4df00-ebc9-11ea-9f7d-24e2cb667f61.png">
<img width="1060" alt="Screen Shot 2020-08-31 at 8 34 20 PM" src="https://user-images.githubusercontent.com/31085177/91784833-73160c00-ebc9-11ea-9c75-fa82c2b500b9.png">

**Comment by simonpham** [comment]
Hi @rabahaldoori,

When the vendors upload the new products, admins need to review and publish them.
There is an option to publish it directly but it's only available in Dokan Pro:

![image](https://user-images.githubusercontent.com/8846657/91786311-8c52a300-ec31-11ea-9e94-5816fd28be74.png)

**Comment by simonpham** [comment]
Hi @rabahaldoori,

I found this answer from https://wordpress.org/support/topic/adding-a-new-product-issues/#post-12124940
You can try this

> In Dokan Lite you can allow a vendor to publish his product immediately by enabling this from wp-admin > users > edit the vendor > http://prntscr.com/pw5a8r. 
> ![image](https://user-images.githubusercontent.com/8846657/91786647-4b0ec300-ec32-11ea-9d2d-cc66f0cc12f0.png)

**Comment by rabahaldoori** [comment]
hi @simonpham i already did that and make the vendor"Publish product Directly " but when i use the website its Publish product , but if i use the app didn't do it . you can send me your email i can send you the login to my website so you can check.

**Comment by simonpham** [comment]
Hi @rabahaldoori, you can send it to `inspireui.team@gmail.com`
Thank you!

**Comment by rabahaldoori** [comment]
@simonpham i sent it 

Thank you

**Comment by simonpham** [comment]
I will check with the team and respond to you as soon as possible.
Thank you for your patience.

**Comment by rabahaldoori** [comment]
@simonpham any update
thank you

**Comment by simonpham** [comment]
Hi @rabahaldoori,

You can open `lib/models/product/product_model.dart`, then search for `Future<void> createProduct` function and make the change as below:

• Search for this:

![image](https://user-images.githubusercontent.com/8846657/92096817-8c090200-ee01-11ea-89cd-98e6e530e819.png)

• Add below line

```
"status": "published",
```

• Result will be like this:

![image](https://user-images.githubusercontent.com/8846657/92096777-7a275f00-ee01-11ea-880a-8f90289374c5.png)


Hope this can solve your issue. Good luck!

**Comment by rabahaldoori** [comment]
hi @simonpham didn't work when i did its didn't even post the product as Draft at all

**Comment by simonpham** [comment]
> hi @simonpham didn't work when i did its didn't even post the product as Draft at all

Could you try again with this:
`"status": "publish",`

**Comment by rabahaldoori** [comment]
@simonpham work Thank you
