### ISSUE TITLE
Error While Building apk for play store release 

### ISSUE THREAD

**Issue by notthatparker** [inspireui/support#4799]
**Today whilst  trying to get things ready for the publishing tried building apks following the instructions on the website but im facing issues with the build to be specific below is the output :
![Screen Shot 2020-08-30 at 05 26 52](https://user-images.githubusercontent.com/34457302/91649123-6d151380-ea81-11ea-8b6a-350ea25e50a6.png)**

I went thru couple posts on here and tried most but non worked for me . 

+ flux listing
+ Flutter

**Comment by minhcasi** [comment]
pls try following solutions

- check flutter issues `flutter doctor`

- clean up the caching - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1 

- make sure to update latest flutter `1.20.x` that compatible with latest fluxlisting

- check your flutter PATH by referring to this guide - https://flutter.dev/docs/get-started/install/macos#update-your-path

**Comment by minhcasi** [comment]
Let us know your checking, thank you!
