### ISSUE TITLE
[MStore Multi Vendor] endpoint "/api/mstore_user" not found 404

### ISSUE THREAD

**Issue by lcassiol** [inspireui/support#480]
- Product: MStore Multi Vendor - Complete React Native template for WooCommerce
 - Your Purchased Code: 4cd001fd-62ec-4131-86fa-b60cf647c215

 Hello, I recently purchased MStore Multi Vendor - Complete React Native template for WooCommerce from codecanyon and **I followed all the steps to install the app as well as the plugins for wordpress.** 
   
   When I installed the app on the device **I was able to list the products but could not log in or create a user, the route called for login and user creation does not exist (404).** 
  
   In the App code I noticed that the url is as follows: `${url}/api/mstore_user/generate_auth_cookie /?Second=${cookieLifeTime}&username=${username}&password=${password}${secure}`;

Even with the mstore-checkout plugin installed in the most current version of github: * Version: 1.1.4
https://github.com/inspireui/mstore/blob/master/plugins/mstore-checkout.zip

I followed this tutorial https://inspireui.github.io/mstore-mv/docs/configwordpress

I'm still without this endpoint, am I doing something wrong?

**Comment by thangvo9x** [comment]
Hi. Thanks for your purchase. You must have to go to the Settings menu -> JSON API. and enable it.

**Comment by lcassiol** [comment]
Hi thank you but the plugin it's already activated. 

![pluginActivated](https://user-images.githubusercontent.com/9991290/55690583-d3b7ff80-5969-11e9-9a9d-605c91d0698f.PNG)

Do you have any suggestion?

**Comment by thangvo9x** [comment]
Do you try to remove the previous plugin JSON and re-install it, plz? 
send AppConfig.json for me to test. Thanks

**Comment by lcassiol** [comment]
Yes I did =/. I'm using  this JSON API version https://wordpress.org/plugins/json-api/

Here is my AppConfig.json
https://notepad.pw/1f54zw7

Sorry github doesn't support json extension for upload so I uploaded it on notepad.pw

**Comment by thangvo9x** [comment]
Hi. You must install JSON from here
https://github.com/inspireui/mstore/tree/master/plugins 
Try again. and let me know if it works. Thanks

**Comment by lcassiol** [comment]
Wow, that's fine now, I've installed the same plugins that you recommended in the link above. Thank you very much for your attention.
