### ISSUE TITLE
Buzz App

### ISSUE THREAD

**Issue by easln** [inspireui/support#4800]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
- [x] first issue
- [ ] second issue
- [ ] third issue

+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on https://verify.inspireui.com **

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by easln** [comment]
Hello, post text are displayed on my wordpress site, but the pictures, twitter, instagram, youtube embedded contents in the post do not appear. How can I solve this problem. Good work.

**Comment by minhcasi** [comment]
@easln - could you help to share some screenshots issues and your website URL so that that we could check the root cause - thank you!

**Comment by easln** [comment]
videos, twitter, instagram embedded content and post pictures are not visible. 
website url: https://mioldu.com


<img width="350" alt="Ekran Resmi 2020-08-30 06 17 20" src="https://user-images.githubusercontent.com/65802151/91650476-bd43a400-ea88-11ea-97a1-13f96a097586.png">

**Comment by minhcasi** [comment]
@easln - the embedded content could only display if it loaded via iframe, if you are using the shortcode it could not display - thank you!

**Comment by easln** [comment]
When I click on the settings tab, this error screen appears. what should I do.
<img width="380" alt="Ekran Resmi 2020-08-31 17 50 15" src="https://user-images.githubusercontent.com/65802151/91733804-bd3fc300-ebb2-11ea-8147-ba5cd7dbe3f4.png">

**Comment by easln** [comment]
Why are the post pictures not showing?

**Comment by minhcasi** [comment]
@easln - could i know if you have installed and active all Wordpress plugins - https://docs.inspireui.com/buzzapp/getting-started/#2-install-wordpress-plugins

**Comment by easln** [comment]
yes plugins installed

**Comment by easln** [comment]
not visible in the pictures inside the posts
<img width="350" alt="Ekran Resmi 2020-08-30 06 17 20" src="https://user-images.githubusercontent.com/65802151/91939406-73fc8a00-ecfe-11ea-913c-310e70fe158f.png">
<img width="1228" alt="Ekran Resmi 2020-09-02 09 28 37" src="https://user-images.githubusercontent.com/65802151/91939660-e53c3d00-ecfe-11ea-9706-ac616b38a1af.png">

**Comment by minhcasi** [comment]
@easln - it seems your post have not config correctly, try to remove the figure shortcode and add the normal Image tag

**Comment by easln** [comment]
Thanks. When I click on the Settings tab after logging in, I get this error.plugins installed.
<img width="380" alt="Ekran Resmi 2020-08-31 17 50 15" src="https://user-images.githubusercontent.com/65802151/92188613-bdb3b480-ee65-11ea-9820-7bb719d1814e.png">

**Comment by minhcasi** [comment]
noted with investigating - thank you!

**Comment by easln** [comment]
How will we view the quiz and pool on the bimber theme?
<img width="364" alt="Ekran Resmi 2020-09-04 07 38 06" src="https://user-images.githubusercontent.com/65802151/92200159-c5815200-ee81-11ea-8cb0-2776e927395a.png">

**Comment by easln** [comment]
When I enter the more -headlines tab and click on an rss content, this error screen appears.
<img width="373" alt="Ekran Resmi 2020-09-05 03 07 43" src="https://user-images.githubusercontent.com/65802151/92292295-14cc8e80-ef25-11ea-86a9-d5e512906df1.png">

**Comment by minhcasi** [comment]
Thank you for your sharing, note with investigating - very best!

**Comment by minhtruong315** [comment]
@easln can u send me full your source code via email: minhtruong315@gmail.com
Thanks

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
