### ISSUE TITLE
Project update

### ISSUE THREAD

**Issue by haidarsalim** [inspireui/support#4801]
Fluxstore Version: 1.7.7
Flutter : v1.20.2

I have a question, how can you update the project with previous modifications
From version 1.7.6 to the new version 1.7.7
Starting over takes a lot of time

**Comment by minhcasi** [comment]
@haidarsalim - pls refer to this guide https://medium.com/@inspireui/how-to-upgrade-fluxstore-projects-by-using-git-cebde7489ea6

**Comment by haidarsalim** [comment]
It's complicated, is there an easier way than that by replacing files?

**Comment by minhcasi** [comment]
@haidarsalim - you could try to override the `lib` folder but we suggest to init your project by using git as well

**Comment by minhcasi** [comment]
sorry, pls help to give your all comment to the same ticket, let's move to #4807

**Comment by amin5400** [comment]
الصفحه غير موجودة
