### ISSUE TITLE
ios build error

### ISSUE THREAD

**Issue by AhmedMaherPro** [inspireui/support#4802]
when simulator open this error show

![placeholder](https://user-images.githubusercontent.com/25661721/91659023-36fd8100-eacd-11ea-990d-505ac0208165.PNG)

**Comment by minhcasi** [comment]
@AhmedMaherPro - could i know if you have followed this guide to update the bundle and app name - https://docs.inspireui.com/fluxstore/delivery/

**Comment by AhmedMaherPro** [comment]
i solve the problem thank you
