### ISSUE TITLE
could not resolve the package 'firebase_admob'

### ISSUE THREAD

**Issue by zahidahamed** [inspireui/support#4804]
Hi 

Im having a admob error when im running the app, please check the screenshots

my pubspec.yaml file as below : 

name: fstore
description: Mobile commerce app by Flutter

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.7.7+3001

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  inspireui:
    path: ./modules/common_library
  flutter:
    sdk: flutter
  http: 0.12.2
  html_unescape: 1.0.1+3
  provider: ^4.3.2+1
  after_layout: 1.0.7+2
  font_awesome_flutter: 8.8.1
  vector_math: 2.0.8
  carousel_pro: 1.0.0
  flutter_widget_from_html: 0.4.3
  configurable_expansion_tile: 1.0.0
  timeago: ^2.0.27
  share: ^0.6.5
  validate: 1.7.0
  country_pickers: 1.3.0
  shared_preferences: ^0.5.10
  firebase_messaging: ^7.0.0
  firebase_analytics: ^6.0.0
  transparent_image: 1.0.0
  pull_to_refresh: 1.6.1
  localstorage: 3.0.2+5
  notification_permissions: 0.4.7
  flare_splash_screen: 3.0.1
  rate_my_app: ^0.7.0+1
  page_indicator: 0.3.0
  intro_slider: 2.3.1
  url_launcher: 5.5.0
  extended_image: ^1.1.1
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  flutter_webview_plugin: 0.3.11
  connectivity: ^0.4.9+2
  random_string: 2.1.0
  google_maps_flutter: 0.5.30
  cached_network_image: ^2.3.1
  uuid: ^2.2.2
  uni_links: 0.4.0
  flutter_staggered_grid_view: 0.3.2
  auto_size_text: 2.1.0
  flutter_swiper: 1.1.6
  flutter_widgets: 0.1.12
  video_player: ^0.10.12+2
  flutter_spinkit: 4.1.2+1
  percent_indicator: 2.1.5
  animated_text_kit: 2.2.0
  wave: 0.0.8
  http_auth: 0.3.0

  facebook_audience_network: 0.7.0
  pin_code_fields: ^5.0.1
  flutter_facebook_login: 3.0.0
  webview_flutter: 0.3.22+1
  rubber: 0.4.0
  flutter_localizations:
    sdk: flutter
  custom_splash: 0.0.2
  apple_sign_in: 0.1.0
  google_sign_in: ^4.5.3
  google_fonts: 1.1.0
  flutter_statusbarcolor: 0.2.3
  app_settings: ^4.0.3
  animated_splash: 1.0.0
  firebase_database: ^4.0.0
  event_bus: 1.1.1
  country_code_picker: 1.4.0
  flash: 1.3.1
  graphql: 3.1.0
  location: 3.0.2
  liquid_swipe: 1.5.0
  sticky_headers: 0.1.8+1
  onesignal_flutter: ^2.6.1
  zoom_widget: 0.1.3
  awesome_card: 1.1.0
  flutter_html: 1.0.2
  universal_platform: ^0.1.3

dependency_overrides:
  flutter_svg: 0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: 0.7.5
  pedantic: 1.8.0+1 # Analysis
  mockito:  4.1.1

# Run this script to generate the app icon: flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - lib/config/
    - lib/config/mocks/
    - lib/config/states/
    - lib/config/stories/
    - assets/icons/categories/
    - assets/icons/tabs/
    - assets/icons/profile/
    - assets/icons/payment/
    - assets/images/
    - assets/images/country/
    - assets/images/favicon/
    - assets/html/
    - assets/images/background/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
flutter_intl:
  enabled: true
![Untitled](https://user-images.githubusercontent.com/27573373/91657649-4508cd00-eae0-11ea-9331-ca5b66313cc3.jpg)

**Comment by minhcasi** [comment]
@zahidahamed - please give a try to clean up the cache by using this guide https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

Also, make sure to run `flutter pub get` to install the required library and check the flutter error by running `flutter doctor` 

Thank you!

**Comment by zahidahamed** [comment]
Hi,

I have already cleared cache and done everything, i have run the pub get as
well, but won't working, please help me im steuggling with, can any of your
developer come online on a zoom call please ???

**Comment by minhcasi** [comment]
I'm sorry that we do not support for remote support with the Regular License basic - https://inspireui.com/support-policies/

Please try your best by checking the followings solution: 
1. make sure you could run the Test Drive app - https://flutter.dev/docs/get-started/test-drive?tab=androidstudio

2. update to latest Flutter stable channel `flutter stable channel`

3. Send us your result by running `flutter doctor`

Thank you for your time sir.

**Comment by zahidahamed** [comment]
Im having the following error when run the app, i have updated everything as you guided, please help me to rid of this error



Invalid depfile: D:\buymobile android app\codecanyon-kcqZITR4-fluxstore-woocommerce-flutter-ecommerce-full-app\FluxStore-woo-1.7.7\source\.dart_tool\flutter_build\be1b65a3fb32cde159db98579dd065fa\kernel_snapshot.d
Invalid depfile: D:\buymobile android app\codecanyon-kcqZITR4-fluxstore-woocommerce-flutter-ecommerce-full-app\FluxStore-woo-1.7.7\source\.dart_tool\flutter_build\be1b65a3fb32cde159db98579dd065fa\kernel_snapshot.d
Error: Could not resolve the package 'firebase_admob' in 'package:firebase_admob/firebase_admob.dart'.
lib/models/advertisement.dart:2:8: Error: Not found: 'package:firebase_admob/firebase_admob.dart'
import 'package:firebase_admob/firebase_admob.dart';
       ^
lib/models/advertisement.dart:9:10: Error: Type 'InterstitialAd' not found.
  static InterstitialAd _interstitialAd;
         ^^^^^^^^^^^^^^
lib/models/advertisement.dart:10:10: Error: Type 'BannerAd' not found.
  static BannerAd _bannerAd;
         ^^^^^^^^
lib/models/advertisement.dart:11:10: Error: Type 'MobileAdTargetingInfo' not found.
  static MobileAdTargetingInfo _targetingInfo;
         ^^^^^^^^^^^^^^^^^^^^^
lib/models/advertisement.dart:12:3: Error: Type 'BannerAd' not found.
  BannerAd myBanner;
  ^^^^^^^^
lib/models/advertisement.dart:72:10: Error: Type 'BannerAd' not found.
  static BannerAd createBannerAd() {
         ^^^^^^^^
lib/models/advertisement.dart:102:10: Error: Type 'InterstitialAd' not found.
  static InterstitialAd createInterstitialAd() {
         ^^^^^^^^^^^^^^
lib/models/user/user_model.dart:13:1: Error: 'User' is imported from both 'package:firebase_auth/firebase_auth.dart' and 'package:fstore/models/user/user.dart'.
import 'user.dart';
^^^^
lib/screens/users/registration.dart:9:1: Error: 'User' is imported from both 'package:firebase_auth/firebase_auth.dart' and 'package:fstore/models/user/user.dart'.
import '../../models/user/user_model.dart';
^^^^
lib/models/advertisement.dart:9:10: Error: 'InterstitialAd' isn't a type.
  static InterstitialAd _interstitialAd;
         ^^^^^^^^^^^^^^
lib/models/advertisement.dart:10:10: Error: 'BannerAd' isn't a type.
  static BannerAd _bannerAd;
         ^^^^^^^^
lib/models/advertisement.dart:11:10: Error: 'MobileAdTargetingInfo' isn't a type.
  static MobileAdTargetingInfo _targetingInfo;
         ^^^^^^^^^^^^^^^^^^^^^
lib/models/advertisement.dart:12:3: Error: 'BannerAd' isn't a type.
  BannerAd myBanner;
  ^^^^^^^^
lib/models/advertisement.dart:52:7: Error: Getter not found: 'FirebaseAdMob'.
      FirebaseAdMob.instance.initialize(
      ^^^^^^^^^^^^^
lib/models/advertisement.dart:55:30: Error: Method not found: 'MobileAdTargetingInfo'.
      _targetingInfo = const MobileAdTargetingInfo(
                             ^^^^^^^^^^^^^^^^^^^^^
lib/models/advertisement.dart:81:15: Error: Getter not found: 'AdSize'.
        size: AdSize.smartBanner,
              ^^^^^^
lib/models/advertisement.dart:82:20: Error: 'MobileAdEvent' isn't a type.
        listener: (MobileAdEvent event) {
                   ^^^^^^^^^^^^^
lib/models/advertisement.dart:74:14: Error: Method not found: 'BannerAd'.
      return BannerAd(
             ^^^^^^^^
lib/models/advertisement.dart:93:34: Error: Getter not found: 'AnchorType'.
      _bannerAd.show(anchorType: AnchorType.bottom);
                                 ^^^^^^^^^^
lib/models/advertisement.dart:108:22: Error: 'MobileAdEvent' isn't a type.
          listener: (MobileAdEvent event) {
                     ^^^^^^^^^^^^^
lib/models/advertisement.dart:104:14: Error: Method not found: 'InterstitialAd'.
      return InterstitialAd(
             ^^^^^^^^^^^^^^
lib/models/advertisement.dart:123:23: Error: Getter not found: 'AnchorType'.
          anchorType: AnchorType.bottom,
                      ^^^^^^^^^^
lib/models/advertisement.dart:138:7: Error: Getter not found: 'RewardedVideoAd'.
      RewardedVideoAd.instance.load(
      ^^^^^^^^^^^^^^^
lib/models/advertisement.dart:145:15: Error: Getter not found: 'RewardedVideoAd'.
        await RewardedVideoAd.instance.show();
              ^^^^^^^^^^^^^^^
lib/models/user/user_model.dart:112:73: Error: Too few positional arguments: 1 required, 0 given.
          AuthCredential credential = FacebookAuthProvider.getCredential(
                                                                        ^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth_platform_interface-2.0.1/lib/src/providers/facebook_auth.dart:92:25: Context: Found this candidate, but the arguments don't match.
  static AuthCredential getCredential(String token) {
                        ^^^^^^^^^^^^^
lib/models/user/user_model.dart:183:18: Error: 'User' is imported from both 'package:firebase_auth/firebase_auth.dart' and 'package:fstore/models/user/user.dart'.
          user = User.fromLocalJson(json);
                 ^^^^
lib/tabbar.dart:183:43: Error: 'currentUser' isn't a function or method and can't be invoked.
      final user = await _auth.currentUser();
                                          ^^^^...
lib/screens/users/login_sms/index.dart:143:51: Error: 'AuthException' isn't a type.
      final PhoneVerificationFailed veriFailed = (AuthException exception) {
                                                  ^^^^^^^^^^^^^
U
nhandled exception:
FileSystemException(uri=org-dartlang-untranslat
able-uri:package%3Afirebase_admob%2Ffirebase_admob.dart; message=StandardFileSystem only supports file:* and data:* URIs)
#0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:33:7)
#1      asFileUri (package:vm/kernel_f
ront_end.dart:659:37)
<asynchronous suspension>
#2      writeDepfile (package:vm/kernel_front_end.dart:
853:21)
<asynchronous suspension>
#3      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:574:15)
<asynchronous suspension>
#4      _FlutterFrontendCompiler.compile (package:flutter_frontend_serv
e
r/server.dart:43:22)
#5      starter (package:flutter_frontend_server/server.dart:182:27)
#6      main (file:///C:/b/s/w/ir/cache/builder/src/flutter/flutter_frontend
_server/bin/starter.dart:9:30)
#7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#8
      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)



FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 896

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 44s
Exception: Gradle task assembleDebug failed with exit code 1
