### ISSUE TITLE
Cash on delivery Not working +more issues 1.7.7 MV

### ISSUE THREAD

**Issue by eraldix** [inspireui/support#4805]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
- [ ] first issue
Cash on delivery doesn't work on MV 1.7.7 show's null as seen on screenshot below
![Screenshot_1598797322](https://user-images.githubusercontent.com/44481659/91661598-57cdd280-eadd-11ea-9c80-4aa38d3a6ec1.png)

- [ ] second issue
If I make checkout on webpage   **"EnableOnePageCheckout": true,** it doesn't carry with itself the Attributes, If I select for example a Product with color white it doesn't show through checkout and I as a seller cant see on the order details.
- [ ] third issue
The store Tabs shows Cover photo as Profile photo ,if I don't add store photo it show's profile photo as store cover photo. This need urgent fix.

+ Product & version: MV 1.7.7
+ Flutter (or React Native) version: Flutter Latest
+ Testing Device/Simulator: Both
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on https://verify.inspireui.com **

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by eraldix** [comment]
i forgot to mention I'm using WCFM

**Comment by eraldix** [comment]
Can anyone adress this issue??

**Comment by eraldix** [comment]
@minhcasi ??

**Comment by minhtruong315** [comment]
@eraldix can u upload your source code to github then invite me: minhtruong315@gmail.com
ping me when you invited
Thanks

**Comment by eraldix** [comment]
> minhtruong315@gmail.com

Added

**Comment by minhtruong315** [comment]
Hi @eraldix I checkout your source code. But you should upload folder, shouldn't zip source code. I can't unzip it. pls upload the folder

**Comment by minhtruong315** [comment]
Please use this version and reinstall MStore Api plugin on your website 
[mstore-api.zip](https://github.com/inspireui/support/files/5165465/mstore-api.zip)

**Comment by eraldix** [comment]
> Please use this version and reinstall MStore Api plugin on your website
> [mstore-api.zip](https://github.com/inspireui/support/files/5165465/mstore-api.zip)

Nothing has changed, the app shows Attributes but when I buy on the app cant see on my panel, This is a big problem.

**Comment by eraldix** [comment]
> minhtruong315@gmail.com

Added again. The problem that needs urgent fix is:
When I select the attribute on app it doesn't show on my order tab on woocommerce. And I don't know what color or size the client wants. 
Also when  I make checkout on webpage "EnableOnePageCheckout": false, the shipping goes $0. (This is secondary problem because can get away with web-view.

**Comment by eraldix** [comment]
Hello, I need urgent fix on this issue, I can't get my app out if the attributes cant go through checkout.

**Comment by minhtruong315** [comment]
@eraldix please pull the source code and check again.

**Comment by eraldix** [comment]
> @eraldix please pull the source code and check again. 

I have added you to my code again

**Comment by eraldix** [comment]
This is not a great support, you are making me go and give you bad reviews over codecanyon, you know the problem and you do nothing about it. This is an urgent task.

**Comment by minhtruong315** [comment]
@eraldix I dont understand. You added me to your repo. I fixed issues on that.

**Comment by eraldix** [comment]
> @eraldix I dont understand. You added me to your repo. I fixed issues on that. 

Sorry it didn't show up on my github, checking it out now

**Comment by eraldix** [comment]
> @eraldix I dont understand. You added me to your repo. I fixed issues on that.

Still the attributes doesn't go through, try it by yourself with this product please:
![Simulator Screen Shot - iPhone 11 - 2020-09-05 at 01 33 23](https://user-images.githubusercontent.com/44481659/92291221-e1373780-ef17-11ea-8f2d-61005a94de30.png)

**Comment by minhtruong315** [comment]
@eraldix pls pull the source code and check again. I fixed it
<img width="477" alt="Screen Shot 2020-09-06 at 8 38 39 AM" src="https://user-images.githubusercontent.com/10402500/92316332-7e7b9400-f01c-11ea-96fd-2a509b860a25.png">
