### ISSUE TITLE
Problems opening the project on Xcode

### ISSUE THREAD

**Issue by haidarsalim** [inspireui/support#4807]
Fluxstore Version: 1.7.7
Flutter : v1.20.2
xcode

Problems opening the project on Xcode. I need to solve the problem, and are there steps to follow to avoid the problem?

![2222](https://user-images.githubusercontent.com/54249914/91665975-1ac80700-eb02-11ea-8c7d-26503975b2f7.PNG)

![Screen Shot 2020-08-30 at 3 44 41 AM](https://user-images.githubusercontent.com/54249914/91665933-c755b900-eb01-11ea-9185-d995e1d26ffd.png)

 You have verified https://github.com/inspireui/support/issues/4801

**Comment by dttrung26** [comment]
Hi @haidarsalim , 
please try to run Fluxstore in Android Studio while running it in Xcode to completely generate ios folder. 
Kindly confirm if it works,
Best!

**Comment by haidarsalim** [comment]
what is wrong
![222](https://user-images.githubusercontent.com/54249914/91682685-0bc17300-eb5b-11ea-8437-41cba114ed0a.PNG)

**Comment by haidarsalim** [comment]
Launching lib/main.dart on haidar in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: 4293TP954W
Running Xcode build...
Xcode build done.                                            9.4s
Failed to build iOS app
Error output from Xcode build:
↳
Could not build the precompiled application for the device.

Error launching application on haidar.
** BUILD FAILED **


Xcode's output:
↳
/Users/haidar/flutter/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0.6.1+6/ios/Classes/RateMyAppPlugin.m:15:30: warning: 'requestReview' is only available on iOS 10.3 or newer [-Wunguarded-availability]
    [SKStoreReviewController requestReview];
                             ^~~~~~~~~~~~~~
In module 'StoreKit' imported from /Users/haidar/flutter/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0.6.1+6/ios/Classes/RateMyAppPlugin.m:2:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.6.sdk/System/Library/Frameworks/StoreKit.framework/Headers/SKStoreReviewController.h:22:1: note: 'requestReview' has been marked as being introduced in iOS 10.3 here, but the deployment target is iOS 8.0.0
+ (void)requestReview API_AVAILABLE(ios(10.3), macos(10.14)) API_UNAVAILABLE(watchos) __TVOS_PROHIBITED;
^
/Users/haidar/flutter/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0.6.1+6/ios/Classes/RateMyAppPlugin.m:15:30: note: enclose 'requestReview' in an @available check to silence this warning
    [SKStoreReviewController requestReview];
                             ^~~~~~~~~~~~~~
/Users/haidar/flutter/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0.6.1+6/ios/Classes/RateMyAppPlugin.m:15:6: warning: 'SKStoreReviewController' is only available on iOS 10.3 or newer [-Wunguarded-availability]
    [SKStoreReviewController requestReview];
     ^~~~~~~~~~~~~~~~~~~~~~~
In module 'StoreKit' imported from /Users/haidar/flutter/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0.6.1+6/ios/Classes/RateMyAppPlugin.m:2:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.6.sdk/System/Library/Frameworks/StoreKit.framework/Headers/SKStoreReviewController.h:14:110: note: 'SKStoreReviewController' has been marked as being introduced in iOS 10.3 here, but the deployment target is iOS 8.0.0
SK_EXTERN_CLASS API_AVAILABLE(ios(10.3), macos(10.14)) API_UNAVAILABLE(watchos) __TVOS_PROHIBITED @interface SKStoreReviewController : NSObject
                                                                                                             ^
/Users/haidar/flutter/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0.6.1+6/ios/Classes/RateMyAppPlugin.m:15:6: note: enclose 'SKStoreReviewController' in an @available check to silence this warning
    [SKStoreReviewController requestReview];
     ^~~~~~~~~~~~~~~~~~~~~~~
2 warnings generated.
Command MergeSwiftModule failed with a nonzero exit code
Command MergeSwiftModule failed with a nonzero exit code
/Users/haidar/Desktop/FluxStore 1.7.6/source/ios/OneSignalNotificationServiceExtension/NotificationService.swift:3:8: error: no such module 'OneSignal'
import OneSignal
       ^
note: Using new build system
note: Building targets in parallel
note: Planning build
note: Constructing build description

![11](https://user-images.githubusercontent.com/54249914/91694010-9f536d80-eb74-11ea-911d-b790c918bb14.png)

**Comment by dttrung26** [comment]
Hi @haidarsalim ,
are you using the latest FluxStore version which is 1.7.7 released on August 18th?

**Comment by haidarsalim** [comment]
Fluxstore Version: 1.7.6
More than two months have passed since I have been working on the app and the Android version has been released
I don’t want to go back from the start. I don’t know how to upgrade the code as the changes remain

**Comment by haidarsalim** [comment]
Version: 1.7.7
There is an error even when using the new version
![Screen Shot 2020-08-31 at 2 28 45 AM](https://user-images.githubusercontent.com/54249914/91705562-fd129600-eb31-11ea-8829-2ce32d778537.png)

Launching lib/main.dart on iPhone SE (2nd generation) in debug mode...
Running Xcode build...
Xcode build done.                                            9.4s
Failed to build iOS app
Could not build the application for the simulator.
Error launching application on iPhone SE (2nd generation).
Error output from Xcode build:
↳
** BUILD FAILED **


Xcode's output:
↳
While building module 'OneSignal' imported from /Users/haidar/flutter/.pub-cache/hosted/pub.dartlang.org/onesignal_flutter-2.6.0/ios/Classes/OneSignalPlugin.h:29:
In file included from <module-includes>:1:
/Users/haidar/Desktop/FluxStore-new-1.7.7/source/ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/Headers/OneSignal.h:561:4: warning: 'UNMutableNotificationContent' is only available on iOS 10.0 or newer [-Wunguarded-availability]
+ (UNMutableNotificationContent*)didReceiveNotificationExtensionRequest:(UNNotificationRequest*)request withMutableNotificationContent:(UNMutableNotificationContent*)replacementContent;
   ^
In module 'UserNotifications' imported from /Users/haidar/Desktop/FluxStore-new-1.7.7/source/ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/Headers/OneSignal.h:45:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.6.sdk/System/Library/Frameworks/UserNotifications.framework/Headers/UNNotificationContent.h:63:12: note: 'UNMutableNotificationContent' has been marked as being introduced in iOS 10.0 here, but the deployment target is iOS 8.0.0
@interface UNMutableNotificationContent : UNNotificationContent
           ^
While building module 'OneSignal' imported from /Users/haidar/flutter/.pub-cache/hosted/pub.dartlang.org/onesignal_flutter-2.6.0/ios/Classes/OneSignalPlugin.h:29:
In file included from <module-includes>:1:
/Users/haidar/Desktop/FluxStore-new-1.7.7/source/ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/Headers/OneSignal.h:561:1: note: annotate 'didReceiveNotificationExtensionRequest:withMutableNotificationContent:' with an availability attribute to silence this warning
+ (UNMutableNotificationContent*)didReceiveNotificationExtensionRequest:(UNNotificationRequest*)request withMutableNotificationContent:(UNMutableNotificationContent*)replacementContent;
^
                                                                                                                                                                                         API_AVAILABLE(ios(10.0))
/Users/haidar/Desktop/FluxStore-new-1.7.7/source/ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/Headers/OneSignal.h:561:74: warning: 'UNNotificationRequest' is only available on iOS 10.0 or newer [-Wunguarded-availability]
+ (UNMutableNotificationContent*)didReceiveNotificationExtensionRequest:(UNNotificationRequest*)request withMutableNotificationContent:(UNMutableNotificationContent*)replacementContent;
                                                                         ^
In module 'UserNotifications' imported from /Users/haidar/Desktop/FluxStore-new-1.7.7/source/ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/Headers/OneSignal.h:45:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.6.sdk/System/Library/Frameworks/UserNotifications.framework/Headers/UNNotificationRequest.h:16:12: note: 'UNNotificationRequest' has been marked as being introduced in iOS 10.0 here, but the deployment target is iOS 8.0.0
@interface UNNotificationRequest : NSObject <NSCopying, NSSecureCoding>
           ^
While building module 'OneSignal' imported from /Users/haidar/flutter/.pub-cache/hosted/pub.dartlang.org/onesignal_flutter-2.6.0/ios/Classes/OneSignalPlugin.h:29:
In file included from <module-includes>:1:
/Users/haidar/Desktop/FluxStore-new-1.7.7/source/ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/Headers/OneSignal.h:561:1: note: annotate 'didReceiveNotificationExtensionRequest:withMutableNotificationContent:' with an availability attribute to silence this warning
+ (UNMutableNotificationContent*)didReceiveNotificationExtensionRequest:(UNNotificationRequest*)request withMutableNotificationContent:(UNMutableNotificationContent*)replacementContent;
^
                                                                                                                                                                                         API_AVAILABLE(ios(10.0))
/Users/haidar/Desktop/FluxStore-new-1.7.7/source/ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/Headers/OneSignal.h:561:137: warning: 'UNMutableNotificationContent' is only available on iOS 10.0 or newer [-Wunguarded-availability]
+ (UNMutableNotificationContent*)didReceiveNotificationExtensionRequest:(UNNotificationRequest*)request withMutableNotificationContent:(UNMutableNotificationContent*)replacementContent;
                                                                                                                                        ^
In module 'UserNotifications' imported from /Users/haidar/Desktop/FluxStore-new-1.7.7/source/ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/Headers/OneSignal.h:45:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.6.sdk/System/Library/Frameworks/UserNotifications.framework/Headers/UNNotificationContent.h:63:12: note: 'UNMutableNotificationContent' has been marked as being introduced in iOS 10.0 here, but the deployment target is iOS 8.0.0
@interface UNMutableNotificationContent : UNNotificationContent
           ^
While building module 'OneSignal' imported from /Users/haidar/flutter/.pub-cache/hosted/pub.dartlang.org/onesignal_flutter-2.6.0/ios/Classes/OneSignalPlugin.h:29:
In file included from <module-includes>:1:
/Users/haidar/Desktop/FluxStore-new-1.7.7/source/ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/Headers/OneSignal.h:561:1: note: annotate 'didReceiveNotificationExtensionRequest:withMutableNotificationContent:' with an availability attribute to silence this warning
+ (UNMutableNotificationContent*)didReceiveNotificationExtensionRequest:(UNNotificationRequest*)request withMutableNotificationContent:(UNMutableNotificationContent*)replacementContent;
^
                                                                                                                                                                                         API_AVAILABLE(ios(10.0))
/Users/haidar/Desktop/FluxStore-new-1.7.7/source/ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/Headers/OneSignal.h:562:4: warning: 'UNMutableNotificationContent' is only available on iOS 10.0 or newer [-Wunguarded-availability]
+ (UNMutableNotificationContent*)serviceExtensionTimeWillExpireRequest:(UNNotificationRequest*)request withMutableNotificationContent:(UNMutableNotificationContent*)replacementContent;
   ^
In module 'UserNotifications' imported from /Users/haidar/Desktop/FluxStore-new-1.7.7/source/ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/Headers/OneSignal.h:45:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.6.sdk/System/Library/Frameworks/UserNotifications.framework/Headers/UNNotificationContent.h:63:12: note: 'UNMutableNotificationContent' has been marked as being introduced in iOS 10.0 here, but the deployment target is iOS 8.0.0
@interface UNMutableNotificationContent : UNNotificationContent
           ^
While building module 'OneSignal' imported from /Users/haidar/flutter/.pub-cache/hosted/pub.dartlang.org/onesignal_flutter-2.6.0/ios/Classes/OneSignalPlugin.h:29:
In file included from <module-includes>:1:
/Users/haidar/Desktop/FluxStore-new-1.7.7/source/ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/Headers/OneSignal.h:562:1: note: annotate 'serviceExtensionTimeWillExpireRequest:withMutableNotificationContent:' with an availability attribute to silence this warning
+ (UNMutableNotificationContent*)serviceExtensionTimeWillExpireRequest:(UNNotificationRequest*)request withMutableNotificationContent:(UNMutableNotificationContent*)replacementContent;
^
                                                                                                                                                                                        API_AVAILABLE(ios(10.0))
/Users/haidar/Desktop/FluxStore-new-1.7.7/source/ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/Headers/OneSignal.h:562:73: warning: 'UNNotificationRequest' is only available on iOS 10.0 or newer [-Wunguarded-availability]
+ (UNMutableNotificationContent*)serviceExtensionTimeWillExpireRequest:(UNNotificationRequest*)request withMutableNotificationContent:(UNMutableNotificationContent*)replacementContent;
                                                                        ^
In module 'UserNotifications' imported from /Users/haidar/Desktop/FluxStore-new-1.7.7/source/ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/Headers/OneSignal.h:45:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.6.sdk/System/Library/Frameworks/UserNotifications.framework/Headers/UNNotificationRequest.h:16:12: note: 'UNNotificationRequest' has been marked as being introduced in iOS 10.0 here, but the deployment target is iOS 8.0.0
@interface UNNotificationRequest : NSObject <NSCopying, NSSecureCoding>
           ^
While building module 'OneSignal' imported from /Users/haidar/flutter/.pub-cache/hosted/pub.dartlang.org/onesignal_flutter-2.6.0/ios/Classes/OneSignalPlugin.h:29:
In file included from <module-includes>:1:
/Users/haidar/Desktop/FluxStore-new-1.7.7/source/ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/Headers/OneSignal.h:562:1: note: annotate 'serviceExtensionTimeWillExpireRequest:withMutableNotificationContent:' with an availability attribute to silence this warning
+ (UNMutableNotificationContent*)serviceExtensionTimeWillExpireRequest:(UNNotificationRequest*)request withMutableNotificationContent:(UNMutableNotificationContent*)replacementContent;
^
                                                                                                                                                                                        API_AVAILABLE(ios(10.0))
/Users/haidar/Desktop/FluxStore-new-1.7.7/source/ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/Headers/OneSignal.h:562:136: warning: 'UNMutableNotificationContent' is only available on iOS 10.0 or newer [-Wunguarded-availability]
+ (UNMutableNotificationContent*)serviceExtensionTimeWillExpireRequest:(UNNotificationRequest*)request withMutableNotificationContent:(UNMutableNotificationContent*)replacementContent;
                                                                                                                                       ^
In module 'UserNotifications' imported from /Users/haidar/Desktop/FluxStore-new-1.7.7/source/ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/Headers/OneSignal.h:45:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.6.sdk/System/Library/Frameworks/UserNotifications.framework/Headers/UNNotificationContent.h:63:12: note: 'UNMutableNotificationContent' has been marked as being introduced in iOS 10.0 here, but the deployment target is iOS 8.0.0
@interface UNMutableNotificationContent : UNNotificationContent
           ^
While building module 'OneSignal' imported from /Users/haidar/flutter/.pub-cache/hosted/pub.dartlang.org/onesignal_flutter-2.6.0/ios/Classes/OneSignalPlugin.h:29:
In file included from <module-includes>:1:
/Users/haidar/Desktop/FluxStore-new-1.7.7/source/ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/Headers/OneSignal.h:562:1: note: annotate 'serviceExtensionTimeWillExpireRequest:withMutableNotificationContent:' with an availability attribute to silence this warning
+ (UNMutableNotificationContent*)serviceExtensionTimeWillExpireRequest:(UNNotificationRequest*)request withMutableNotificationContent:(UNMutableNotificationContent*)replacementContent;
^
                                                                                                                                                                                        API_AVAILABLE(ios(10.0))
6 warnings generated.
6 warnings generated.
/Users/haidar/Desktop/FluxStore-new-1.7.7/source/ios/OneSignalNotificationServiceExtension/NotificationService.swift:3:8: error: no such module 'OneSignal'
import OneSignal
       ^
note: Using new build system
note: Building targets in parallel
note: Planning build
note: Constructing build description

**Comment by haidarsalim** [comment]
![Screen Shot 2020-08-31 at 2 34 10 AM](https://user-images.githubusercontent.com/54249914/91705956-8b871780-eb32-11ea-9aec-1be48c236895.png)

**Comment by haidarsalim** [comment]
I think the problem is in OneSignal

**Comment by dttrung26** [comment]
Hi @haidarsalim ,
I don't think OneSingal causing this problem because things still run fine as I tested. Please try: 
```
cd ios
pod deintegrate
rm -rf Podfile.lock
pod install
```
then
```
flutter clean 
flutter pub get
```
and run the project again.
Hope this helps!

**Comment by haidarsalim** [comment]
It didn't work I'm still having a problem


-------
Launching lib/main.dart on haidar in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: 4293TP954W
Running pod install...
Running Xcode build...
Xcode build done.                                            7.6s
Failed to build iOS app
Error output from Xcode build:
↳
Could not build the precompiled application for the device.

Error launching application on haidar.
** BUILD FAILED **


Xcode's output:
↳
6 warnings generated.
/Users/haidar/Desktop/FluxStore 1.7.6/source/ios/OneSignalNotificationServiceExtension/NotificationService.swift:3:8: error: no such module 'OneSignal'
import OneSignal
       ^
note: Using new build system
note: Building targets in parallel
note: Planning build
note: Constructing build description

**Comment by haidarsalim** [comment]
Fluxstore Version: 1.7.7
Flutter : v1.20.2
---

Launching lib/main.dart on haidar in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: 4293TP954W
Running pod install...
Running Xcode build...
Xcode build done.                                            7.5s
Failed to build iOS app
Error output from Xcode build:
↳
Could not build the precompiled application for the device.

Error launching application on haidar.
** BUILD FAILED **


Xcode's output:
↳
/Users/haidar/Desktop/FluxStore-new-1.7.7/source/ios/OneSignalNotificationServiceExtension/NotificationService.swift:3:8: error: no such module 'OneSignal'
import OneSignal
       ^
note: Using new build system
note: Building targets in parallel
note: Planning build
note: Constructing build description

**Comment by dttrung26** [comment]
Hi @haidarsalim , 
can you update your current situation, please? 
If it still doesn't work, please try my above suggestion and run `pod repo update`

**Comment by haidarsalim** [comment]
I am still facing the same problem
Can OneSignal be canceled
Maybe my problem will be solved
I'll be using firebase notifications

**Comment by dttrung26** [comment]
Actually I don't think removing OneSignal is a good idea because it could cause error to other features and I don't know how this solution doesn't work for you. 
Could you try to run project on a physical devices / or try with other simulator?
If it still doesn't work, please try OneSignal with latest version`onesignal_flutter: ^2.6.1` "
In the worst case, removing ` onesignal_flutter: 2.6.0` at pubspec.yaml file, running `flutter pub get`, and deleting irrelevant code showed in Dart Analysis would remove OneSignal completely, but once again, it's not highly recommended.
Best!

**Comment by haidarsalim** [comment]
You delete onesignal
A new error appeared to me
![Screen Shot 2020-09-05 at 12 22 34 AM](https://user-images.githubusercontent.com/54249914/92300217-176fb980-ef0e-11ea-8489-eb8a275a8873.png)

**Comment by minhcasi** [comment]
@haidarsalim - try your merge with the latest Fluxstore 1.7.7 to use with flutter 1.20.x

If you keep version 1.7.6 it could only use with previous flutter 1.19.x

**Comment by haidarsalim** [comment]
I'm going to try it

**Comment by haidarsalim** [comment]
@dttrung26 @minhcasi 

Fluxstore 1.7.7 to use with flutter 1.20.x

![Screen Shot 2020-09-08 at 5 14 29 PM](https://user-images.githubusercontent.com/54249914/92539660-f7cede80-f1f6-11ea-9d94-b53152c33bb3.png)

**Comment by dttrung26** [comment]
Hi @haidarsalim , could you show me the result when you're running in on Android Studio as well please?

**Comment by haidarsalim** [comment]
@dttrung26 
The code does not work on Android Studio

![Screen Shot 2020-09-09 at 10 50 49 AM](https://user-images.githubusercontent.com/54249914/92635339-82145280-f28a-11ea-8b11-4f2bd63c8eb7.png)

**Comment by dttrung26** [comment]
Please send me your whole project 1.7.7 (after deleting build folder) via trung@inspireui.com with title #4807. I'll take a look. 
Best!

**Comment by haidarsalim** [comment]
@dttrung26 
I deleted OneSignal xcode version and now it works on iPhone
But it does not work on Android Studio
flutter_windows_1.20.3
FluxStore-woo-1.7.7 

![2434](https://user-images.githubusercontent.com/54249914/92934049-ae2d0080-f44f-11ea-8c00-562563ac83e6.PNG)

**Comment by haidarsalim** [comment]
I deleted OneSignal xcode version and now it works on iPhone

**Comment by haidarsalim** [comment]
I deleted OneSignal xcode version and now it works on iPhone
