### ISSUE TITLE
After Installing Mstore API Get Error When Running WPCLI Commands

### ISSUE THREAD

**Issue by roshansamasi** [inspireui/support#4808]
Dear Team,
After Installing MSTOREAPI for Woocommerce get the following error when running WPCLI Commands. Works perfectly if i disable MSTORE API

"PHP Warning:  copy(/opt/bitnami/apps/wordpress/htdocs/wp-content/themes/electro/templates/mstore-api-template.php): failed to open stream: Permission denied in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/mstore-api/mstore-api.php on line 44
Warning: copy(/opt/bitnami/apps/wordpress/htdocs/wp-content/themes/electro/templates/mstore-api-template.php): failed to open stream: Permission denied in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/mstore-api/mstore-api.php on line 44"

**Comment by minhcasi** [comment]
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support https://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by roshansamasi** [comment]
Done

**Comment by roshansamasi** [comment]
Still waiting for response

**Comment by roshansamasi** [comment]
Wow still no response

**Comment by minhcasi** [comment]
@roshansamasi - could you help to try to disable the debug mode from wp-config.php from the Wordpress site. 

@minhtruong315 - please help suggest to fix this warning issue

**Comment by roshansamasi** [comment]
Hi Minhcasi it was already disabled.

**Comment by minhtruong315** [comment]
Hi @roshansamasi can u try to reinstall this version?
[mstore-api.zip](https://github.com/inspireui/support/files/5165496/mstore-api.zip)

**Comment by roshansamasi** [comment]
PHP Warning:  copy(/opt/bitnami/apps/wordpress/htdocs/wp-content/themes/electro/templates/mstore-api-template.php): failed to open stream: Permission denied in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/trunk/mstore-api.php on line 97
Warning: copy(/opt/bitnami/apps/wordpress/htdocs/wp-content/themes/electro/templates/mstore-api-template.php): failed to open stream: Permission denied in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/trunk/mstore-api.php on line 97

**Comment by minhtruong315** [comment]
@roshansamasi can you give me your skype? I will contact you to check remotely.
Thanks

**Comment by roshansamasi** [comment]
live:roshansamasi

**Comment by minhtruong315** [comment]
Hi @roshansamasi I ping you on the skype. pls check

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
