### ISSUE TITLE
[CeStore] Hi, I’m having difficulty installing dependencies

### ISSUE THREAD

**Issue by SallonX** [inspireui/support#481]
- Product: Cestore
 - Your Purchased Code: [542a69ca-89bc-4b64-b7b8-910c754fd5ad]

Hi, I’m having difficulty installing dependencies. after giving the “Yarn Install” layer loads up [4/4] Building fresh packages …

And gives the following error:

https://drive.google.com/file/d/1LsZyHoFpq_FnspahXaZckLRNWVD8Pr3_/view?usp=sharing

Conversation on codecanyon:
------------------
InspireUI AUTHOR

about 9 hours ago Flag

hi, could you try with: npm install

Then run: npm run build:watch

pm2 start process.json

------------------

about 6 hours ago Flag
Hi, I had the following errors.

CMD> Mobile-full - https://drive.google.com/file/d/1vmxAjEbdqZwYYYNi4lljTdFLyxur_eSQ/view?usp=sharing
CMD> EvaStore - https://drive.google.com/open?id=1M9TodZE8FAZHqEGbZblUNp61GGNYMMJR
------------------
InspireUI AUTHOR

about 13 hours ago Flag

Hi, first please try to update your node library by download from this site – https://nodejs.org/en/ – then try again with the installing, please also help to create new ticket support to https://github.com/inspireui/support/issues for easier to follow up your issues – thank you!

---------------

errors continue...

help?

**Comment by minhtruong315** [comment]
Hi @SallonX Can you share me teamviewer? I will help you check it

**Comment by SallonX** [comment]
Hi @minhtruong315 

1 147 253 320
pm8z73

**Comment by minhtruong315** [comment]
I sent a message to your skype. pls check it
