### ISSUE TITLE
api  working ok still range error

### ISSUE THREAD

**Issue by nomicool** [inspireui/support#4811]
API are enable working okay i still receive the range error
![Screenshot_1598850600](https://user-images.githubusercontent.com/25566185/91685065-a8dbd600-eb72-11ea-88c1-c5cb9d1843e2.png)

**Comment by minhcasi** [comment]
@nomicool - could you give a try to check if that JSON config working same as on the Fluxbuilder tool - http://fluxbuilder.com/ - thank you!

**Comment by nomicool** [comment]
hey its not working on fluxstore toll builder what's that 
![Screenshot (50)](https://user-images.githubusercontent.com/25566185/91710112-2f0d1200-eb9d-11ea-898e-8941096bf002.png)solution please 

![Screenshot (49)](https://user-images.githubusercontent.com/25566185/91710104-2c122180-eb9d-11ea-8b08-40a7262da3a5.png)

**Comment by nomicool** [comment]
also, the second question I need to use single currency ho to disable all others even the disable currency page

**Comment by minhcasi** [comment]
@nomicool - could you share your detail website url and the consumse/secret key to inspireui.team@gmail.com - we will help to check this issue - thank you!

**Comment by nomicool** [comment]
@minhcasi check mail please with subject is ticket id

**Comment by minhcasi** [comment]
@nomicool - could you resend the PDF License for this ticket ID? Your previous active support is for www.pskirana.com

**Comment by nomicool** [comment]
I have set you the license key new one

**Comment by nomicool** [comment]
please try to respond me today to save time

**Comment by minhcasi** [comment]
@nomicool - why your two licenses have different envato username, please explain?

Pls give new comments on this link to verify your purchase again - https://codecanyon.net/item/fluxstore-multi-vendor-flutter-ecommerce-full-app/25013325 

Sorry for the inconvenience.

**Comment by nomicool** [comment]
I am configuring the app for my client that's why different username and I have posted also comment now try to respond me today single reply takes a day long

**Comment by minhcasi** [comment]
@nomicool - this issue is caused by incorrect consume/secret key, please make sure it is config correctly.

Also, try to check the 401 issues from this solution https://github.com/woocommerce/woocommerce/wiki/Getting-started-with-the-REST-API/8e69ca78f418858ae95e6c7352cdc8b4e6a5f9b2#401-unauthorized

**Comment by minhcasi** [comment]
Let us know your checking - thanks
