### ISSUE TITLE
Social Login Errors, Login by email and No Data Display error on Settings Screen

### ISSUE THREAD

**Issue by Gag1011** [inspireui/support#4812]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
- [ ] first issue: I have followed your documentation on https://docs.inspireui.com/fluxstore/sign-in/ neither the Facebook login Or the Google Sign in are working. Please see attached screen shots: 
![Fb login Error](https://user-images.githubusercontent.com/67577702/91695056-de31f500-eb6d-11ea-82d1-5cdc46e85552.jpg)
![Google login Error](https://user-images.githubusercontent.com/67577702/91695076-e38f3f80-eb6d-11ea-8498-21b1f50659f1.jpg)

- [ ] second issue: The standard email login Signs the user in but does not take them to the home screen of the app. instead, it hangs at the login screen with the circle of death. if one navigates back, they can see that they have in fact signed in. This is very confusing for all users. please see Attached screenshot
![Email Login Circle of Death](https://user-images.githubusercontent.com/67577702/91695308-3832ba80-eb6e-11ea-9a60-042c69aa5f8d.jpg)

- [ ] third issue: Certain Items on the settings screen display "No-data" They should display custom names for each tab and and then when touched they should display the relevant information, such as points or rate us function and contact us form. Please see attached screen shot:
![Screenshot_20200827-133945](https://user-images.githubusercontent.com/67577702/91695658-c9099600-eb6e-11ea-816e-1b7881018e91.jpg)

Please assist?

+ Product & version: Fluxstore Multi Vendor - Flutter E-commerce Full App 1.7.7
+ Flutter (or React Native) version: Flutter 1.0.0
+ Testing Device/Simulator: Android Studio emulator: pixel 3 with both arms

**_Step 2 (require): submit proof of purchasing the license on https://verify.inspireui.com **

#Ticket-Id: #4660 

I have read the support guidelines.

**Comment by minhcasi** [comment]
- pls try follow this guide carefully to fix the first issue - https://medium.com/@inspireui/setup-google-login-for-flutter-apps-fedc58a490b8

- try to update latest mstore-api and fluxstore app to see if it could fix the issue

- could i know if you have customized the Setting screens and add more menu items?

**Comment by Gag1011** [comment]
This issue is not closed, please re open

**Comment by Gag1011** [comment]
All I have done to the settings screen is to customise the names of some of the tabs. I have not removed or edited anything else on the settings screen. Also I have got the google login in working but it does not redirect the user to the app home screen upon successful login. Please advise?

**Comment by Gag1011** [comment]
I have followed your instructions for the fb login and still receive the same key hash error. Even after generating the key hash from the terminal in android studios.
