### ISSUE TITLE
Mobile Cases Dropdown menu error

### ISSUE THREAD

**Issue by surendranekkanti188** [inspireui/support#4814]
Need dropdown mobile list in the app. I'm sharing both my website and Fluxstore app options.
i'm sharing the link for your reference. ( https://superhumour.com/product/rebel-mobile-case ) please have a look.
Product & version:
Flutter version: 1.1.7
Testing Device/Simulator: Pixel 3A

As per your instructions i have ADDED "width" in ProductVariantLayout ={
it works fine now but the problem is it shows only few models. I have more than 130 model cases list. For your reference i'm adding the screenshots
![7](https://user-images.githubusercontent.com/69853255/91714342-5e416600-eb40-11ea-8d3f-d9e71d3a97f2.png)
![8](https://user-images.githubusercontent.com/69853255/91714347-600b2980-eb40-11ea-95ab-3de8f2e28ec0.png)
![6](https://user-images.githubusercontent.com/69853255/91714349-600b2980-eb40-11ea-90ee-707d21de4fd4.png)

.

**Comment by simonpham** [comment]
Hi @surendranekkanti188,

Thank you for reporting this issue. We will fix it and release it in a future version.

For now, you can try these steps to fix it by yourself:

<details><summary>Steps to fix in the code (click to expand)</summary>
<p>


1. Open `lib/widgets/product/product_variant.dart`.
2. Go to `showOptions` method of `OptionSelection` widget then add `isScrollControlled: true,` as below:

<details><summary>Screenshot:</summary>
<p>

![image](https://user-images.githubusercontent.com/8846657/91792102-f0c82f00-ec3e-11ea-96ae-88444716576a.png)

</p>
</details>

3. Then right-click at Column, click Show context action:

<details><summary>Screenshot:</summary>
<p>

![image](https://user-images.githubusercontent.com/8846657/91792181-253beb00-ec3f-11ea-8aec-e4c7ea3e2479.png)

</p>
</details>

4. Click Wrap with widget...

<details><summary>Screenshot:</summary>
<p>

![image](https://user-images.githubusercontent.com/8846657/91792234-43a1e680-ec3f-11ea-9dc1-33ebb4d6cc11.png)

</p>
</details>

5. Type `SingleChildScrollView` then press Enter.

<details><summary>The final code will be like this</summary>
<p>

![image](https://user-images.githubusercontent.com/8846657/91792291-616f4b80-ec3f-11ea-9ccd-15f09ba4ab44.png)

</p>
</details>

</p>
</details>

Hope this can solve your issue. Thank you for using our product.

**Comment by surendranekkanti188** [comment]
Thank you so much. My problem solved. 🙏
