### ISSUE TITLE
I would like to know how to create a new page inside the app

### ISSUE THREAD

**Issue by macromealsapp** [inspireui/support#4815]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: Hello There I purchased the Fluxstore code for shopify from Codecanyon, I want to know can we create a new additional page inside the app, We want a New Screen to be opened, where that will be having only two big static images that seperates entire screen one will redirecting to the existing home page and the other will be redirecting to one collection. I would like to know can we do it. 

Thanks and Regards
Pavan Reddy

**Comment by minhcasi** [comment]
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support https://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by macromealsapp** [comment]
I uploaded the licenses file in the Google Drive, I actually purchased the code and assigned to a freelancer, I'm not a developer, Let me explain my requirement,
The Existing homepage with FLux Store works fine,
Now we need to change the home page, creating a new home page and that consists two static images of different brands, after clicking on the banner will make the app move forward.
1. The First banner should redirect to the previous Home page we used to have
2. The Second Banner should Redirect to a Collection
My Developer says, we can't create like that, I want to know how extent we can make the changes and customise as per our requirement

Thanks for your time

**Comment by minhcasi** [comment]
@macromealsapp - pls give try to use the Fluxbuilder app to support for these customization - http://fluxbuilder.com

Or you could manually update via config json file by using this guide https://docs.inspireui.com/fluxstore/home-layout/#2-banner-slider-image

**Comment by minhcasi** [comment]
Let us know your checking - thanks
