### ISSUE TITLE
OneSignal for iOS

### ISSUE THREAD

**Issue by ongaki8** [inspireui/support#4818]
Hello, I can't seem to get OneSignal to work for iOS.

**Comment by minhcasi** [comment]
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support https://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by ongaki8** [comment]
I've submitted the form already.

**Comment by ongaki8** [comment]
Also, my map is blank and the store list is empty. Can we arrange for a live session to quickly sort out these two issues?

**Comment by ongaki8** [comment]
Issue 3.

Chat notifications between customer and vendor. I can't see or receive them.

**Comment by T3kken** [comment]
> Also, my map is blank and the store list is empty. Can we arrange for a live session to quickly sort out these two issues?

Mate I think its a problem with this version and do not use OneSignal with this for now as you will end up in big issues as I have.

**Comment by ongaki8** [comment]
It's really frustrating. They take too long to respond.

**Comment by minhcasi** [comment]
@ongaki8 - could I know if you are using latest fluxstore MV 1.7.7 and the latest Flutter stable 1.20.x ?

Also, share some screenshot issues so that we could know more about the issues, thank you for your time!

**Comment by minhcasi** [comment]
Let us know your updating - thanks
