### ISSUE TITLE
What to do if Codepoint 58848 error persists with v1.7.7?

### ISSUE THREAD

**Issue by IbrahimHd** [inspireui/support#4819]
Hi,

[Product: FluxStore PRO 1.7.7]

I've refered to all your answers to the error `Codepoint 58848 not found in font, aborting`  and the answer was "solved in v1.7.7". My question is: What should it be done if the error persists with v**1.7.7** and all the below mentioned actions have been done?

-  Upgraded to v1.7.7
- `pubspec.lock` removed
- Tools->Flutter->Clean
- File -> Invalidate Caches / Restart
- remove the `.grade` folder
- `flutter channel stable && flutter upgrade -- force`
- flutter doctor => NO ISSUES

Both `flutter build apk --split-per-abi`  and `flutter build appbundle` don't work.

Looking for your prompt response.
thanks

**Comment by minhcasi** [comment]
@IbrahimHd - it's working fine with our testing, could you try to use this pubspec.yaml to see if it could fix the issue ?

[pubspec.yaml.txt](https://github.com/inspireui/support/files/5160402/pubspec.yaml.txt)

**Comment by minhcasi** [comment]
Let us know your updating - thanks

**Comment by IbrahimHd** [comment]
Thank you @minhcasi for sharing.

The `pubspec.yaml` file you shared needs some Fixes:

- `inspireui:
    path: ./modules/common_library` is missed

- `google_maps_flutter: 0.5.29` is missed

- As you updated from `rate_my_app: 0.6.1+7` to `rate_my_app: 0.7.0` => `ignoreIOS: false,` (in settings.dart) is no longer supported. I jsut commented it out.

On the other hand, this needs to be updated:
/android/app/build.gradle file: `targetSdkVersion 28` replace 28 with **29**

After applying theses FIXES, It WORKS!

However, what about the removed fonts/icons, **MaterialIcons** and other ones? (I didn't test it the generated bundle yet as I'm still waiting for google review process)

Looking for your answer.
Thanks,
Ibrahim

**Comment by minhcasi** [comment]
the fonts/icons, MaterialIcons already support from flutter core so that we don't need to add to the library.

We have updated the  targetSdkVersion on the next release, and also update all libraries to the latest one.
