### ISSUE TITLE
[MStore] Unknown controller 'mtore_user'

### ISSUE THREAD

**Issue by nkuranhy3** [inspireui/support#482]
**Required Info (please complete the following information):**
 - Product: Mstore Expo
 - Your Purchased Code: [get from https://codecanyon.net/downloads]
41a15692-aacc-457e-a826-e13987ff0a86

**Describe the bug**
### I get Unknown controller 'mtore_user' when i try to login or sign up

**Screenshots**
![WhatsApp Image 2019-04-05 at 20 43 05](https://user-images.githubusercontent.com/34389326/55664417-bb869a00-581c-11e9-9e26-d2dbf033b262.jpeg)
![WhatsApp Image 2019-04-06 at 03 31 09](https://user-images.githubusercontent.com/34389326/55664418-bc1f3080-581c-11e9-9a4c-9342d0f73074.jpeg)

**Additional context**
I have installed all the packages and the app settings

If possible please share your config.js that use for the app setting

[Config.js.zip](https://github.com/inspireui/support/files/3050119/Config.js.zip)

**Comment by thangvo9x** [comment]
Try update plugin mstore-checkout from here 
https://github.com/inspireui/mstore/tree/master/plugins

**Comment by hynra** [comment]
I have updated the plugin, but still, this error appears. What else should I do?

<img width="790" alt="already" src="https://user-images.githubusercontent.com/3982650/60530110-42ff7e80-9d22-11e9-81f0-4aa6fa4d7c49.PNG">

**Comment by wellbeck190** [comment]
I have same issue with @hynra

**Comment by danasugu** [comment]
Hi! I have the same issue: Exception: Unknown controller 'mstore_user'.

**Comment by Halkaramov2019** [comment]
I have same problem too, any solution?
