### ISSUE TITLE
Can i use dark theme as initial theme and if user want they can change to light theme? And can remove left drawer menu?

### ISSUE THREAD

**Issue by lakshayb121** [inspireui/support#4820]
Can i use dark theme as initial theme and if user want they can change to light theme? And can remove left drawer menu?

_Originally posted by @lakshayb121 in https://github.com/inspireui/support/issues/4713#issuecomment-683454838_

**Comment by minhcasi** [comment]
Hi, you could update this value to true to set dark theme as default. 

<img width="891" alt="Screen Shot 2020-09-02 at 12 54 24" src="https://user-images.githubusercontent.com/1459805/91937095-73262100-ed1b-11ea-8138-52901db3c5e6.png">

Set hideMenu: true on the config json file to hide menu - https://docs.inspireui.com/fluxstore/home-layout/#1-logo-item

**Comment by minhcasi** [comment]
Let us know if you have any question - thanks
