### ISSUE TITLE
archive app error

### ISSUE THREAD

**Issue by AhmedMaherPro** [inspireui/support#4821]
app is working good , but when try to archive app this error show to me 
![onesignalerror](https://user-images.githubusercontent.com/25661721/91853220-2b8f8e80-ec62-11ea-8772-e649ecb12312.PNG)

**Comment by AhmedMaherPro** [comment]
and when try to change build system to legacy this errors show to me
![errorlegacy](https://user-images.githubusercontent.com/25661721/91841859-56beb180-ec53-11ea-9514-08ccb5a9c782.PNG)

**Comment by AhmedMaherPro** [comment]
i solve it 
solution : set Bit code in one signal target to No

**Comment by minhcasi** [comment]
@AhmedMaherPro - thank you so much for your sharing, we will update this setting on next release
