### ISSUE TITLE
Issues with loading products details

### ISSUE THREAD

**Issue by YahyaYousef** [inspireui/support#4823]
+ Detail Issues: 
- [ ] **When i'm showing some product i have in my website in still loading like this image below also i cant add this product to cart**

![Screenshot_1598958667](https://user-images.githubusercontent.com/55236141/91842703-2f6ce200-ec5d-11ea-8440-d2d7cc53f3d9.png)

- [x] **Many product the app load there price 0.00 but in back-end the price is different**

![InkedScreenshot_1598958915_LI](https://user-images.githubusercontent.com/55236141/91843291-39431500-ec5e-11ea-8b23-7f23cd36d9b8.jpg)
![Capture](https://user-images.githubusercontent.com/55236141/91843294-3b0cd880-ec5e-11ea-8f10-d68fedcf656e.JPG)

+ Product & version: **FluxStore-woo-1.7.7**
+ Flutter (or React Native) version: **Flutter**
+ Testing Device/Simulator: **Both**

**Comment by minhcasi** [comment]
@YahyaYousef - could you give a try to test with fluxbuilder app to see if it have the same issue - http://fluxbuilder.com ?

**Comment by YahyaYousef** [comment]
@minhcasi Yes I tried it and it have the same issue

**Comment by minhcasi** [comment]
Could you share your website URL and consume/secret key to inspireui.team@gmail.com - thanks

**Comment by YahyaYousef** [comment]
I send it

**Comment by minhcasi** [comment]
@simonpham - pls help to investigate this issue

**Comment by simonpham** [comment]
Hi @YahyaYousef,

We are sorry for the late reply.
Please send us your `lib/common` and `/lib/config` folder to _simon@inspireui.com_
We will help you to check the problems.

Thank you for using our products!

**Comment by YahyaYousef** [comment]
@simonpham 
I send it
 please check it as fast as possible so I can refund if its not working

**Comment by simonpham** [comment]
Hi @YahyaYousef,

For your problem, please help us go to `lib/models/product.dart` and add `?` before `.forEach` of `parsedJson["attributesData"].forEach` and `parsedJson["attributesData"]?.forEach` so it will look like below:

![image](https://user-images.githubusercontent.com/8846657/92377002-a9094200-f12d-11ea-8928-ea0952c16d8a.png)

Hope this can solve your issue.
We will include this fix in the future version. Thank you for using our product!

**Comment by YahyaYousef** [comment]
@simonpham 
**I did but still facing same issue**
![Screenshot_1599474674](https://user-images.githubusercontent.com/55236141/92378471-8582cf00-f10e-11ea-9a46-3e30e9f70680.png)

**Here is what I did**

![Capture](https://user-images.githubusercontent.com/55236141/92378539-9c292600-f10e-11ea-9fad-0b28cb2ee86c.JPG)

**Comment by simonpham** [comment]
@YahyaYousef,
Since we cannot reproduce it on our side, please run `flutter clean` and send us your full source code.
We will check it for you.
Thank you!

**Comment by YahyaYousef** [comment]
@simonpham 
I sent full source code to simon@inspireui.com

**Comment by simonpham** [comment]
Hi @YahyaYousef,

I have just checked your problem.
You are using the same category ids for both English & Arabic language which is not correct.
If you change the app language to English, it is working fine because the category ids of `config_en.json` are correct.

**The same category can have different ids for different languages. Please check your wp-admin and correct the category ids in `config_ar.json`.**

Hope this can solve your issue. Good luck!

below is a screenshot of category ids in config json
![image](https://user-images.githubusercontent.com/8846657/92451199-a0287700-f1e6-11ea-912d-ce028f10610f.png)

**Comment by YahyaYousef** [comment]
@simonpham 
This didn't work
Also I'm facing another problem with creating user
The user created on firebase authentication successfully but in woocommerce not created

**Comment by simonpham** [comment]
Hi @YahyaYousef,

Please send me your latest config_ar.json and wp-admin login account to `simon@inspireui.com`
I will help you to check the issue.

Thank you.

**Comment by YahyaYousef** [comment]
I sent it

**Comment by simonpham** [comment]
Hi @YahyaYousef,

I have checked and found that the stock quantity is missing from the product.
Please add a stock quantity to the products that have the problem.

Hope this can solve your issues. Good luck!

**Comment by YahyaYousef** [comment]
@simonpham 
I have tried to add quantity to products also **it didn't work for me**,
Also I'm facing some Issues in login and loading home page

**Comment by minhcasi** [comment]
@YahyaYousef - let us know what is your detailed screenshot issues on the login and loading homepage.

**Comment by minhcasi** [comment]
As I can see they have tried their best with your support Integration Issue which is actually not included from our support scope, please help to check out our support policies for more detail - https://inspireui.com/support-policies 

Btw, you could refund on this link if not satisfied with the product so far - https://help.market.envato.com/hc/en-us/articles/202821460-Can-I-Get-A-Refund- - thank you for your time
