### ISSUE TITLE
FluxStore-listing 1.4.2 .bugs

### ISSUE THREAD

**Issue by tariq-alskran** [inspireui/support#4824]
FluxStore-listing 1.4.2 .bugs 
 
 When integrating products "My listings " with App
 Sign in and  Sign up  not working in App We want to integrate Sign in and  Sign up
 from the website with the application
 note  : using ap i not firebase authentication

**Comment by minhcasi** [comment]
@tariq-alskran - please make sure to install these plugins then the login feature will be compatible with your website - https://docs.inspireui.com/fluxstore/listing-directory/#step-2-install-the-required-plugins

**Comment by minhcasi** [comment]
Let us know your checking - thanks
