### ISSUE TITLE
Colours not visible on App 

### ISSUE THREAD

**Issue by surendranekkanti188** [inspireui/support#4825]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
- [ ] Colours not visible on App 

+ Product & version:
+ Flutter (or React Native) version:  1.1.7
+ Testing Device/Simulator: Pixel 3A
![2](https://user-images.githubusercontent.com/69853255/91852249-6a4b2780-ec15-11ea-87a7-c2e14d95c26e.png)

+ Screenshot issues (drag the file to attach here): 

Hi in the product variants, colors are not visible in the app. i have added all the colour codes too but still not visible, Please have a look.

**Comment by minhcasi** [comment]
the kNametoHex should match with the slug name from color attribute - https://tppr.me/H5kfg

**Comment by surendranekkanti188** [comment]
Hi i have changed the names as Slug names and done flutter clean also but same problem colors are not visible just MAROON & BLACK colors are visible, others are not visible it shows just white.  i'm sharing a screenshot have a look.
![1a](https://user-images.githubusercontent.com/69853255/91966295-7d6a0000-ecc6-11ea-8247-32adc7d2b5fb.png)

**Comment by minhcasi** [comment]
@surendranekkanti188 - could you take the screenshot of your slug attribute setting from the WordPress site - thank you!

**Comment by surendranekkanti188** [comment]
Please Have a look.
![11](https://user-images.githubusercontent.com/69853255/92076534-924e9e00-ed6f-11ea-9f67-fe66cae75ec2.png)
![10](https://user-images.githubusercontent.com/69853255/92076539-94186180-ed6f-11ea-902d-d32418501206.png)

**Comment by minhcasi** [comment]
Please try to fix the file `lib/widgets/product/product_variant.dart` by adding `item.toUpperCase() == value.toUpperCase()` - we suspect it could be case sensitive issue

<img width="1173" alt="Screen Shot 2020-09-04 at 10 50 52" src="https://user-images.githubusercontent.com/1459805/92197626-844a6b80-ee9c-11ea-9903-77b5b8e4b3d9.png">

If it does not work, try to test the `SKY BLUE` - add more spacing

**Comment by surendranekkanti188** [comment]
The above code is not working. 

[If it does not work, try to test the SKY BLUE - add more spacing] i didn't get about spacing. here i'm sharing my color codes, please guide me how to add spacing.

const kNameToHex = {
  "black": "#000000",
  "white": "#ffffff",
  "pink": "#FC46A8",
  "petrol-blue": "#173644",
  "sky-blue": "#87CEEB",
  "maroon": "#800000",
  "bottle-green": "#003B2B",
  "golden-yellow": "#ffcc00",
  "steel-grey": "#394242",
  "coffee-brown": "#301f19",
  "royal-blue": "#002366",
  "brick-red": "#c7321a",
  "purple": "#800080"
};

**Comment by minhcasi** [comment]
Pls zip your whole common and config folder and send to inspireui.team@gmail.com - we will help for checking - thank you!

**Comment by surendranekkanti188** [comment]
Sent. Please check for your inbox.

**Comment by surendranekkanti188** [comment]
Sent. Please check for your inbox.

**Comment by minhcasi** [comment]
Thank you, we will have a check and let you know

**Comment by surendranekkanti188** [comment]
![IMG_20200902_144823](https://user-images.githubusercontent.com/69853255/92326770-3f782d80-f072-11ea-8284-e8a91c02504c.jpg)
![Screenshot_2020-09-02-14-48-26-477_com hosting superhumour](https://user-images.githubusercontent.com/69853255/92326773-4141f100-f072-11ea-89f5-f333e4ef8776.jpg)
![IMG_20200902_144843](https://user-images.githubusercontent.com/69853255/92326774-41da8780-f072-11ea-9c32-dc1968ce5188.jpg)


Along with above issue. Even product selection also goes wrong. When we select iphone 8. In checkout it takes XIAOMI Y2. Please have a look.

**Comment by minhcasi** [comment]
Thank you - we will check this issue as well

**Comment by surendranekkanti188** [comment]
Waiting for ur response. Its been more than 10days still problem
not resolved.

**Comment by simonpham** [comment]
Hi @surendranekkanti188,
For the colours problem,
Please try to use **name** instead of the **slug** for the config. For example, with this color:

![image](https://user-images.githubusercontent.com/8846657/92674615-e9dca300-f347-11ea-9b14-9a773bc545ae.png)

You need to add `"petrol blue": "#173644",`
not `"petrol-blue": "#173644",`

Hope this can solve your issue. Good luck!

**Comment by surendranekkanti188** [comment]
Problem still not solved. its been more than 2 weeks. there is no proper guidance from you. there are so many bugs. we are not satisfied we thought we will buy another 4 licenses but the very first project is stopped like this and our client is unable to wait for more time. We want immediate solution for 1) Colors 2)Product Variant checkout problem & 3)Product discount price glitch.

**Comment by surendranekkanti188** [comment]
I have solved my problem by removing Space between words in wordpress and in fluxstore also.
