### ISSUE TITLE
How to create a step-by-step drop-down list

### ISSUE THREAD

**Issue by madyrstore** [inspireui/support#4827]
+ Detail Issues: 

How to create a step-by-step drop-down list

+ Product & version: fluxstore shopify
+ Flutter (or React Native) version: 1.7.7
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here):
![WhatsApp Image 2020-09-01 at 3 19 29 PM](https://user-images.githubusercontent.com/69593196/91861389-6d760000-ec75-11ea-9698-d2e30c8a936f.jpeg)

thank you advise

**Comment by minhcasi** [comment]
@madyrstore - this UI is not available from fluxstore shopify app due to some limitations of the Shopify API, we will upgrade it later

**Comment by luyx2412** [comment]
Hi @madyrstore Please read the document to use dropdown https://api.flutter.dev/flutter/material/DropdownButton-class.html

Thanks

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
