### ISSUE TITLE
كل كود فيه مشكله اش الحل صار اسبوع  ومافتح البرنامج

### ISSUE THREAD

**Issue by amin5400** [inspireui/support#4829]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
- [ Error: CocoaPods's specs repository is too out-of-date to satisfy dependencies.
To update the CocoaPods specs, run:
  pod repo update

Error running pod install
Error launching application on iPhone 11 Pro.] first issue
- [ ] second issue
- [ ] third issue

+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on https://verify.inspireui.com **

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by amin5400** [comment]
[!] Automatically assigning platform `iOS` with version `10.3` on target `Runner` because no
    platform was specified. Please specify a platform for this target in your Podfile. See
    `https://guides.cocoapods.org/syntax/podfile.html#platform`.

    [!] Automatically assigning platform `iOS` with version `10.3` on target
    `OneSignalNotificationServiceExtension` because no platform was specified. Please specify a
    platform for this target in your Podfile. See
    `https://guides.cocoapods.org/syntax/podfile.html#platform`.

Error running pod install
Error launching application on iPhone 11 Pro.

**Comment by amin5400** [comment]
i can't run flutter

**Comment by minhcasi** [comment]
@amin5400 - please try the following solution to clean up your flutter caching - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1 - thank you!

**Comment by minhcasi** [comment]
Let us know your checking - thanks
