### ISSUE TITLE
fluxlisting issue

### ISSUE THREAD

**Issue by silamutungi** [inspireui/support#4831]
Getting the error above when trying to search on the app. My define( 'WP_DEBUG', false ); is set as false.

+ Product & version:
Fluxstore Listing vs 1.4.2

+ Flutter (or React Native) version: 

Flutter
+ Testing Device/Simulator: 
Android 
+ Screenshot issues (drag the file to attach here): 
![Screenshot_20200901-195111](https://user-images.githubusercontent.com/7536714/91928393-c43d0300-ec90-11ea-9b62-ff1dd057c73c.png)

**_Step 2 (require): submit proof of purchasing the license on https://verify.inspireui.com **
See ticket: #4718

**Comment by minhcasi** [comment]
@silamutungi - please follow this guide to set up the require plugin four your template, also share your website URL here so that we could help for checking - thank you!

**Comment by silamutungi** [comment]
Can you share the guide please. Website is uzamart.com. It’s a listingpro site.

**Comment by minhcasi** [comment]
We will have a check and let you know - thanks

**Comment by minhcasi** [comment]
could you help to rename this code to `ListingApi().searchSearch = 'search/v1/listing';` as your site is using searching from this url `https://uzamart.com/wp-json/search/v1/listing`

<img width="1046" alt="Screen Shot 2020-09-04 at 11 20 52" src="https://user-images.githubusercontent.com/1459805/92199214-b362dc00-eea0-11ea-927e-4e01f2118046.png">

**Comment by silamutungi** [comment]
That worked! Thank you so much for your help. Love your work and amazing
support!
