### ISSUE TITLE
rest api issue

### ISSUE THREAD

**Issue by ahmedseddiq-casheto** [inspireui/support#4834]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
i try to connect my fluxstore multivendor to my website but rest api not connecting and appear this message on fluxbuilder

consumer key and consumer secret not auth
and when i try to go through curl
https://www.website.com/wp-json/wc/v3/orders
its appear that following error
{"code":"woocommerce_rest_cannot_view","message":"Sorry, you cannot list resources.","data":{"status":401}}
but when i enter consumer key and sk in url like that
https://www.website.com/wp-json/wc/v3/orders?consumer_key=ck&consumer_secret=cs
it get back all endpoints 
i want a solution for that to connect the app even for andriod studio not only fluxbuilder as i search there are alot of problem with fluxbuilder and i try alot of htaccess solutions but with nothing
+ Product & version: FluxStore-vendor-1.7.7
+ Flutter (or React Native) version: flutter latest version 1.2
+ Testing Device/Simulator:  fluxbuilder and pixel 3a
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on https://verify.inspireui.com **

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by Nick-tech-2691** [comment]
I also bumped with the same issue, it was working fine 2 days back but when I tried today nothing in hand. did all the solutions which were given by the community but still empty-handed.

**Comment by minhcasi** [comment]
@ahmedseddiq-casheto - could you try to check the integration with your site by using Fluxbuilder tool - http://fluxbuilder.com/

**Comment by ahmedseddiq-casheto** [comment]
yes i try fluxbuilder and their are screenshots of errors and i try dokan too to see the the error and i also contact my bluehost server and there are their reply 
{Hello Ahmed,

Thank you for your patience in this matter. This email is in response to case #25475347 submitted for not being able to connect to get api.  I do sincerely apologize for the trouble that you are experiencing with your Woocommerce API issue and I am more than happy to provide the next steps.

According to WooCommerce REST API documentation: http://woocommerce.github.io/woocommerce-rest-api-docs/?shell#rest-api-keys . 

Occasionally some servers may not parse the Authorization header correctly (if you see a “Consumer key is missing” error when authenticating over SSL, you have a server issue). In this case, you may provide the consumer key/secret as query string parameters instead.

HTTP Basic Auth example
curl https://www.example.com/wp-json/wc/v3/orders \
    -u consumer_key:consumer_secret
Occasionally some servers may not parse the Authorization header correctly (if you see a "Consumer key is missing" error when authenticating over SSL, you have a server issue). In this case, you may provide the consumer key/secret as query string parameters instead.

Example for servers that not properly parse the Authorization header:
curl https://www.example.com/wp-json/wc/v3/orders?consumer_key=123&consumer_secret=abc

Check that orders parameters are in the same order as examples, no space. Or you would use basic HTTPS authentication, that's how we communicate using https. Also, it is advisable to Regenerate the Consumer key and try to authenticate with both methods. It should work fine. 

You can also refer below article for solved similar cases: 
https://github.com/woocommerce/wc-api-python/issues/16

Please confirm this on your end and do get back to us if you have any questions. My team and I will be monitoring this case for your response, we are happy to help you. 

Please note we address the tickets to the information that's submitted to us. Sometimes we receive incomplete information from these escalated notes. If there is something that we may have missed feel free to reply to this correspondence explaining what wasn't addressed and we'll definitely do what we can to help.

Regards,
Rithesh K
Escalated Support
![Screenshot (50)](https://user-images.githubusercontent.com/66135124/92076669-43c6f100-edbb-11ea-9c9c-72f575b24f16.png)
![Screenshot (67)](https://user-images.githubusercontent.com/66135124/92076675-44f81e00-edbb-11ea-88aa-02c804ee72e6.png)

**Comment by ahmedseddiq-casheto** [comment]
n there are other problem may be its related to the same issue
mstore-user has error too



![mstoreuser](https://user-images.githubusercontent.com/66135124/92100347-fc049180-eddb-11ea-9cc9-8b592953af85.png)

**Comment by ahmedseddiq-casheto** [comment]
is ther any help? im just buy that fluxstore a week ago i need help

**Comment by minhcasi** [comment]
@ahmedseddiq-casheto - pls note that the fluxstore is not compatible with the json api any more and mstore_user is no longer use, you could try to update to the latest mstore-api plugin - https://wordpress.org/plugins/mstore-api/, and following this guide to install require plugins - https://docs.inspireui.com/fluxstore/multi-vendor/ 

Also, make sure to config the consumse/secret key correctly, you could also share your admin login to insprieui.team@gmail.com - we will help to check the API config - thanks

**Comment by ahmedseddiq-casheto** [comment]
im install the latest version but i use https://wordpress.org/plugins/jwt-auth/ plugin , i will do all of that again n check and i send you the mail with issue number

**Comment by ahmedseddiq-casheto** [comment]
please note email inspireui.team@gmail.com not correct so i send it to your mail minhcasi@gmail.com please check

**Comment by ahmedseddiq-casheto** [comment]
it fixed now and i dont know why :)
