### ISSUE TITLE
Mobile Case model Checkout problem 

### ISSUE THREAD

**Issue by surendranekkanti188** [inspireui/support#4836]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
- [ ] Mobile case model changes while checking out. 

+ Product & version:
+ Flutter (or React Native) version: 1.1.7
+ Testing Device/Simulator: Pixel 3A
+ Screenshot issues (drag the file to attach here): 
![IMG_20200902_144843](https://user-images.githubusercontent.com/69853255/91965003-7f1ade80-ed2d-11ea-9ae9-a6df5ffdc208.jpg)
![Screenshot_2020-09-02-14-48-26-477_com hosting superhumour](https://user-images.githubusercontent.com/69853255/91965006-80e4a200-ed2d-11ea-8db4-6a9432884d3c.jpg)
![IMG_20200902_144823](https://user-images.githubusercontent.com/69853255/91965008-8215cf00-ed2d-11ea-89b3-55bbe030ef0f.jpg)

Hi in mobile cases we have selected Apple Iphone 8 model, but in checkout page it is changing automatically to XIAOMI REDMI Y2. Please have a look, I think it's a bug. Waiting for solution.

**Comment by minhcasi** [comment]
pls post your all comment into one OPEN ticket support #4825 - thank you!
