### ISSUE TITLE
Fluxstore Woocommerce [ ERROR in Checkout Page ] - FormatException : Unexpected Character ( at character 1 ) <br/> ^

### ISSUE THREAD

**Issue by swspro** [inspireui/support#4837]
Hi @minhcasi @trunghieuvn ,

Hope you are doing well.

Here is the new type of ERROR my client is getting after a long time in the APP in the CHECKOUT PAGE.

You can find the SCREENSHOT in the ATTACHMENT.

### ERROR MESSAGE

**FormatException : Unexpected Character ( at character 1 ) 

![WhatsApp Image 2020-09-02 at 14 53 18](https://user-images.githubusercontent.com/15525566/91964790-37945280-ed2d-11ea-9da6-fdb714d69168.jpeg)

 People are Placing the Order through **"Cash On Delivery "** in the checkout page , but then this ERROR message is Appearing 

Please suggest what to do..

**Sam**

**Comment by minhcasi** [comment]
@swspro - could you help to submit 6 PDF licenses for these mobile apps on your Google Play Store ? 

https://play.google.com/store/apps/details?id=com.freshwayonline.freshway
https://play.google.com/store/apps/details?id=com.mydo.mydoapp
https://play.google.com/store/apps/details?id=com.freshnmartonline.freshnapp
https://play.google.com/store/apps/details?id=com.mybazar.mybazarapp
https://play.google.com/store/apps/details?id=com.seafood.seafoodapp
https://play.google.com/store/apps/details?id=com.barabatifresh.barabatiapp

**Comment by minhcasi** [comment]
pls move your all comment to #4841

**Comment by swspro** [comment]
The Problem is FIXED now ...

The SMS Alert Plugin which we had installed was creating problem while placing the order.

So we un-installed the SMS Alert Plugin and it worked fine.

Thanks,
Sam
