### ISSUE TITLE
Estimate shipping method return empty data

### ISSUE THREAD

**Issue by dukec2020** [inspireui/support#4839]
Hi,
We got issue when requesting shipping methods - the request return empty array.
Was check the API document and see cart id is require on this request but in code I don't see it passed to

Ref:lib/services/magento.dart
Method: Future<List<ShippingMethod>> getShippingMethods(

API document:
https://devdocs.magento.com/swagger/index_22.html#/quoteShippingMethodManagementV1/quoteShippingMethodManagementV1EstimateByAddressIdPost

**Comment by minhcasi** [comment]
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support https://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
@minhtruong315 - pls suggest the solution for this issue

**Comment by minhtruong315** [comment]
@dukec2020 can u send me common folder and admin account to login your website via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/4839
Thanks

**Comment by dukec2020** [comment]
Don't know why but know it works properly without cart_id parameter.
Pls abandon this ticket.
