### ISSUE TITLE
Can´t activate List Manager Plugin in Wordpress

### ISSUE THREAD

**Issue by Nachbarsaft** [inspireui/support#484]
- Product: ListApp
 - Your Purchased Code: I purchased MyList App on Envato 29th/11 purchase code ends with: 49bc14f56289 (don´t want to publically post the whole number here)

**Describe the issues**
I can´t activate the list manager Plugin in Wordpress. This is the message I receive:

> Plugin could not be activated because it triggered a fatal error.

> Fatal error: Cannot declare class Template, because the name is already in use in /hp/cu/aa/kv/www/My-Guyd_com/wp-content/plugins/listapp-mobile-manager/rest-api/class.api.fields.php on line 
**Screenshots**
<img width="872" alt="Can´t activate ListApp Manager" src="https://user-images.githubusercontent.com/38483515/55671858-d0067900-5894-11e9-819b-a9ada09da198.PNG">
**Additional context**
Hi Guys,
Please help me. What exactly do I need to do? 

Please find here my wpconfig file: https://1drv.ms/u/s!Aq6Mvuxj9CAnhZpmbmNuC0nswOD_-g

Thx

**Comment by thangvo9x** [comment]
https://github.com/inspireui/support/issues/485

**Comment by Nachbarsaft** [comment]
Why did you close this? This hasn´t been solved?
