### ISSUE TITLE
Fluxstore Woocommerce [ Version 1.7.7 ] - Homepage Categories Product Listing Issue

### ISSUE THREAD

**Issue by swspro** [inspireui/support#4841]
Dear @minhcasi @trunghieuvn ,

The New Version of Fluxstore Woocomerce ( version 1.7.7 ) homepage loading issue 

To explain this I am sharing with you the Screenshots and the Screen Recording Video Link 

### 1 ) HOMEPAGE SCREEN 

**-  FIRST TIME WHEN THE APP IS INSTALLED AND OPENED** 

**-  ALL PRODUCTS ARE LISTED**

![WhatsApp Image 2020-09-02 at 15 38 02](https://user-images.githubusercontent.com/15525566/91973507-00786e00-ed3a-11ea-9fe1-b0ca78f54634.jpeg) <br/><br/>

![WhatsApp Image 2020-09-02 at 15 38 02-2](https://user-images.githubusercontent.com/15525566/91973530-0706e580-ed3a-11ea-848a-2520b92ace1d.jpeg)
<br/><br/>

![WhatsApp Image 2020-09-02 at 15 38 02-3](https://user-images.githubusercontent.com/15525566/91973536-08381280-ed3a-11ea-9f62-50efba6e80ac.jpeg)

<br/><br/><br/><br/>

### 2 ) BLANK HOME SCREEN [ ON CLOSING & REOPENING THE APP ] ( Watch the SCREEN RECORDING Video **@ https://youtu.be/7qtcCmu8NKg** ) 

- THE HOMESCREEN BECOMES ALMOST BLANK 

- Everyone who has download the APP faces the same problem.

- Category Page Sometime does not loads, and when it load by chance the all products are listed

- In the HOMESCREEN even though the Categories product listing shows blank , but if you click on "View All " , it will display all items

-  Look at the Screenshot below and suggest what to do

![WhatsApp Image 2020-09-02 at 15 38 02-5](https://user-images.githubusercontent.com/15525566/91974473-74674600-ed3b-11ea-88c5-421e456bf339.jpeg)<br/><br/>

![WhatsApp Image 2020-09-02 at 16 51 27](https://user-images.githubusercontent.com/15525566/91975178-a0cf9200-ed3c-11ea-864c-82639bc78a54.jpeg)

![WhatsApp Image 2020-09-02 at 15 38 02-4](https://user-images.githubusercontent.com/15525566/91974788-f192bb00-ed3b-11ea-9ebe-20efce6c2c10.jpeg)

**Comment by minhcasi** [comment]
Hi, could you share your app URL here so that we could test this issue?

**Comment by minhcasi** [comment]
@swspro - could you help to submit 6 PDF licenses for these mobile apps on your Google Play Store ?

https://play.google.com/store/apps/details?id=com.freshwayonline.freshway
https://play.google.com/store/apps/details?id=com.mydo.mydoapp
https://play.google.com/store/apps/details?id=com.freshnmartonline.freshnapp
https://play.google.com/store/apps/details?id=com.mybazar.mybazarapp
https://play.google.com/store/apps/details?id=com.seafood.seafoodapp
https://play.google.com/store/apps/details?id=com.barabatifresh.barabatiapp

**Comment by swspro** [comment]
hi @minhcasi ,

Should I attach all the PDFs here or should email you ?

- For your information we buy license on behalf of our Clients , so in the last ticket I request for BULK LICENSE PURCHASE which you didnt responded. [ Refer Attachment ]

- So we started Purchasing Individual Clients 

![lnspireui](https://user-images.githubusercontent.com/15525566/92070737-80e6af80-edca-11ea-9e03-a03236acd989.PNG)

**Comment by swspro** [comment]
Ok ..

**Comment by swspro** [comment]
hi @minhcasi email sent to support@inspireui.com with following subject line

### Sub Line : Fluxstore License Issue : Ticket No. 4841

**Comment by swspro** [comment]
Hi @minhcasi 

As people are not able to order since last two days 

Can you please suggest first on Format Exception Issue at https://github.com/inspireui/support/issues/4837

Sam

**Comment by minhcasi** [comment]
@swspro - you could zip this project and send to `inspireui.team@gmail.com` - we will help to investigate the issue (make sure to run `flutter clean` before compressing the source)

**Comment by swspro** [comment]
Ok @minhcasi

**Comment by swspro** [comment]
Hi @minhcasi 

The formatException issue is fixed.
https://github.com/inspireui/support/issues/4837

The problem was with SMS Alert Plugin which was initiated on placing the order.

So when I deleted that Plugin it worked

Thanks for your time on that issue. It is highly appreciated.

Please look into the Above issues on category products not loading on HomePage.

For your information 

We are using REDIS Object Cache Plugins along with WP REST Cache.

For some of the Apps We have Disabled WP REST Cache Plugins and only using REDIS Object Cache Plugin . And is working fine.

On the Fluxstore Latest Version 1.7.7 

There is an option **kIsResizeImage**": **true**

We have regenerated the images using Regenerate Thumbnail Plugin

What I feel is after making this kIsResizeImage": true I am facing the loading problem.

Other Apps is  kIsResizeImage": false

Also one more thing comes into my mind 

Is More number of  category products listing is creating the problem ?

If you want I can give you the admin panel login details of FreshNMartOnline.com


**I have listed 4 to 5 more issues**

Which I will create separate tickets with relevant Title later you can connect with this ticket .

This will help users to find their issue while search for information here in your support system.

Thanks again for all your help and support.

Sam

**Comment by minhcasi** [comment]
The kIsResizeImage will not work completely for all sites so that it is set up as configurable, you could try to use it as false if already have the Caching system.

Please try your best with the config as you have a lot of experience from the previous app set up.

**Comment by swspro** [comment]
Hi @minhcasi 

I have made the kIsResizeImage=false but still the App when installed first time is loading but the second time it's having issue 

You can refer the same YouTube link https://youtu.be/7qtcCmu8NKg

The New Version has this loading issue

Sam

**Comment by swspro** [comment]
If you want I can email you admin panel login and zip file

Pls let me know which email address should I send ?

Sam

**Comment by swspro** [comment]
@minhcasi one more thing for your reference ..

1 ) I am loading the Categories ICON in the HOME PAGE SCREEN Dynamically from the Server.

2 ) Categories Label are also being loaded dynamically 

As there are more than 5 Categories ICON listed in the HomeScreen which are loaded dynamically might have been one of the reason for delay or skipping in loading the Category Products listings

What do you thing ?

Please suggest 

Every users are having the same complain that products are not loading 

Sam

**Comment by minhcasi** [comment]
Try to increase `cacheExtent: 100000.0,` to see if it could fix the product missing image issue

<img width="936" alt="Screen Shot 2020-09-05 at 14 31 52" src="https://user-images.githubusercontent.com/1459805/92300371-8be53f80-ef84-11ea-93a7-e1fcaf8f93a3.png">

**Comment by swspro** [comment]
Ok @minhcasi will try and test it today.

If that works fine will update you here.

Sam

**Comment by minhcasi** [comment]
How is your checking, thank you!

**Comment by swspro** [comment]
Hi @minhcasi 

I had made the changes as per your suggestion.

In the dedbug apk it's working fine most of the time. Some time it's not loading.

I have uploaded the updated  release version in the PlayStore. It will get Live today within few hours.

Want to see how it's working with users phone in the release version


Will update you once I do the testing with users 

Sam

**Comment by swspro** [comment]
Hi @minhcasi 

It's working fine at least 80% time it's loading all items , and 20% time it's not loading which is ok as of now..

If you want to suggest anything please let me know.

Sam

**Comment by swspro** [comment]
Hi @minhcasi 

We have tested the Rate the App section ..

It's really not working..

The Rate the App Link is not clickable

Should send you the Screenshot of the Pages where the Rate The App Setups are done.

Sam

**Comment by minhcasi** [comment]
@swspro - could give a try with the example from this lib https://pub.dev/packages/rate_my_app - we are using this library to support the rating. 

Did you test on Apple or Android devices?

**Comment by swspro** [comment]
**#RateTheAppIssue**

- Ok @minhcasi will give try again.

- We are doing it for Android ..

**#FluxstoreHomePageItemLoading**

- The Category item  Loading issue (  )  in the Homepage is arising again after using for some days. 

If you want I can give you admin Login or you give other suggestions to make  changes in the CoDe.

70% time not all the items are loading , 30% time items are loading when slowly scrolled the HomeScreen

Sam

**Comment by swspro** [comment]
Hi @minhcasi 

Here is another issue on Product Rating or Review.

**#FluxstoreProductRatingIssue**

- Whenever the users are trying to give a product Review it's anot submitting and showing Alert Message

- Here is the App Screen Recording Video at **https://youtu.be/sa7kn-YWo-U**


Please Suggest 

Sam

**Comment by swspro** [comment]
@minhcasi the Product Ratings has Submitting issues

I tried submitting once , but when there was a delay I tried clicking the Submit Rocket Button Multiple Times . 

As a result of which after sometime it displayed same review multiple times.

There is delay in the click . Please comment on this 🙏

![Screenshot_2020-09-10-19-31-21-43_1cd9ce526f36f7f4432a5a5a44659136.jpg](https://user-images.githubusercontent.com/15525566/92741752-90eb2a00-f39c-11ea-8509-53d7b56dd0a5.jpg)

**Comment by minhcasi** [comment]
@swspro - pls share your source to inspireui.team@gmail.com - we're happy to check the missing image issues - thanks

**Comment by swspro** [comment]
Thanks @minhcasi for your quick response.

Will email you in detail

**Comment by swspro** [comment]
Dear @minhcasi 

I have emailed you as per your request with **Subject Line : Fluxstore Woocommerce [ Version 1.7.7 ] Multiple Major Issues - Refer Ticket No. 4841**  from samareshbisoi@gmail.com

Regards
Sam

**Comment by minhcasi** [comment]
@swspro - give us some time with checking and get back you soon - thank you!

**Comment by swspro** [comment]
Sure @minhcasi please take your time..

Will be waiting for your solution. Hope I explained the issues properly.

The Fluxstore Woocommerce product is getting better day by day .

Great work by you and your Team 👍.

Excellent Support System, Highly appreciated 🙏

Sam

**Comment by swspro** [comment]
Hi @minhcasi 

Just sharing with you regarding the clients feedback .

Users are getting angry on the loading issues . 

We are using Dedicated server.

Really need to fix this ..

I know it's a good product , but after the new version is updated there is loading issue.

![IMG-20200911-WA0004.jpeg](https://user-images.githubusercontent.com/15525566/92999955-9b472880-f542-11ea-83b3-72ecab45e9dc.jpeg)

![Screenshot_2020-09-12-21-47-26-02.jpg](https://user-images.githubusercontent.com/15525566/92999873-3c81af00-f542-11ea-8eaf-2f16a4146116.jpg)

![Screenshot_2020-09-12-21-08-21-42_14eae2955cf98c73484320ff02e66f2b.jpg](https://user-images.githubusercontent.com/15525566/92999888-53c09c80-f542-11ea-9708-a1c363440d30.jpg)

![IMG-20200912-WA0008.jpg](https://user-images.githubusercontent.com/15525566/92999893-5f13c800-f542-11ea-9012-c4d119c955b9.jpg)

**Comment by minhcasi** [comment]
@swspro - did you try to test the category issues by using Fluxbuilder tool - http://fluxbuilder.com ?

**Comment by swspro** [comment]
Hi @minhcasi 

I tried using the Fluxbuilder once , but it only gave a one page code which we only used in config_en 

Other page codes were missing.

In the email I have share two App files and the SPECIFIC Issues and Common Issues.

If you can Review and Run those codes you can see the exact problem.

Also I have shared the Admin Panel username and password in the email , so that you can see the issue which may be related to CACHE And Image loading


Sam

**Comment by swspro** [comment]
I have test loading ..

Same loading issue ..

HomeScreen and product listing page loading more than 12 seconds

And most of the time nothing is appearing.. skipping section in the homepage

Sam

**Comment by minhcasi** [comment]
It could the network issues, could you try to observe the response time from the server by using this tool https://flutter.dev/docs/development/tools/devtools/network

**Comment by swspro** [comment]
Hi @minhcasi ,

There is no NETWORK issue.. even we have tried using the FAST BROADBAND Connection to TEST.

Here we have Highspeed 4G Connections . All other APPS are loading in 2 seconds..

EVENT the FLUXSTORE DEMO APP is loading in 2 to 3 Seconds.

WE are currently using the DEDICATED SERVER and its CONFIGURATION I have share in the above posts

### Which server you are using ?

**We have options** 

1 ) Shared Hosting 
2 ) Semi Dedicated Hosting 
3 ) Dedicated Hosting
4 ) VPS Hosting

### WE ARE USING DEDICATED HOSTING

Sam

**Comment by minhcasi** [comment]
Did you check with the network tools- https://flutter.dev/docs/development/tools/devtools/network ? pls share the screenshot

**Comment by swspro** [comment]
Hi @minhcasi 

**Below is the SCREENSHOT of the use NETWORK TOOLS for SEA FOOD APP**

![SEA FOOD NETWORK VIEW](https://user-images.githubusercontent.com/15525566/93971861-c3c6f200-fd8e-11ea-82ec-4762bcda96c6.PNG)

This Homepage loading has now become the MAJOR issue for all our APPS

Apart from that we have also listed assistance on other issue which are mentioned above.

Please have a look into it and help us with a best solution

Regards,.
Sam

**Comment by minhcasi** [comment]
Please help to move the new conversation to new Ticket Support http://support.inspireui.com (you could mention on this ticket history) - thank you!
