### ISSUE TITLE
Issue log in using Sign in with Apple.

### ISSUE THREAD

**Issue by abdullahamer11** [inspireui/support#4842]
Apple store reject the app regrading issue on  log in using Sign in with Apple.
this is the message :

We discovered one or more bugs in your app when reviewed on iPad running iOS 13.6.1 on Wi-Fi.

Specifically, we received an error message when we tried to log in using Sign in with Apple.

Screenshot: https://prnt.sc/ua8gjt

**Comment by minhcasi** [comment]
pls help to post your all comment into 1 open ticket support #4840
