### ISSUE TITLE
[ListAPP] Deprecated API Usage - Apple's App Store  #UIWebView

### ISSUE THREAD

**Issue by Metacowboy** [inspireui/support#4843]
ListApp IOS Build will not be accepted by Store Conect 
Reason 
ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).

expo build:ios

Your app needs SDK 36 -. SDK 37 Upgrade to get rid of UIWebView
UIWebView is not in used in the app but in the packages the app use

**Comment by minhcasi** [comment]
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support https://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by Metacowboy** [comment]
Google form updatet with account details  plus developer Email

**Comment by minhcasi** [comment]
@Metacowboy - could i know what the version you are using for Listapp?

**Comment by Metacowboy** [comment]
I use Listapp V 1.7.4   that use SDK 36  
according to expo it would need at least SDK 37 where the desperate UIWebView is removed

**Comment by minhcasi** [comment]
@luyx2412 - please help to update to latest Expo SDK to fix the UiWEbview issue

**Comment by luyx2412** [comment]
Hi @Metacowboy Please send your project via inspireui.team@gmail.com with title `4843`, i will upgrade and resend you.

Thanks

**Comment by luyx2412** [comment]
Closed! Because no longer response.

P/S: Feel free to open new issue.

Thanks
