### ISSUE TITLE
I have purchased already  fluxstore-multi-vendor-flutter-ecommerce-full-app & subscribed at shopify.com as Trial

### ISSUE THREAD

**Issue by MuhammadJavaid** [inspireui/support#4844]
Hi I am new user, I have purchased already  codecanyon-usZbNIgp-fluxstore-multi-vendor-flutter-ecommerce-full-app in USD 80/-
(1. Getting started) First Tutorial works fine and I loaded the Fluxstore app.
(2. Install the Fluxstore Shopify app) Second Tutorial I stuck with an Error on my mobile with red back ground says " NoSuchMethodError: The method '[ ]' was called on null. Receiver : null Tried Calling: [ ] ("SplashScreen") See also https://flutter.dev/docs/testing/errors

I subscribed at shopify.com as Trial / free store, (is this the issue that I have my store url different than in video tutorial) ?
and selected store for clothing.. where is error plz guide.

**Comment by minhcasi** [comment]
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support https://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by MuhammadJavaid** [comment]
Hi I have submitted the Google form m waiting for the reply. thank you.

**Comment by minhcasi** [comment]
@MuhammadJavaid - thank you for quick response, please note that the product you have purchased does not support the Shopify store, please refer to this [Fluxstore Shopify app](https://1.envato.market/JX4P7)

**Comment by minhcasi** [comment]
you could also give a try to setup the setting by using Fluxbuilder tool - http://fluxbuilder.com/

**Comment by minhcasi** [comment]
Let us know your checking, thank you!
