### ISSUE TITLE
Updating the application layout without redeploy

### ISSUE THREAD

**Issue by RatnApp** [inspireui/support#4846]
Hi Team,

Could you please let us know how to update your without redeploying the app in case of Shopify backend.

I have followed below blog, however it is for mstore, where is the recommended place to upload the config_en.json in case of Shopify?

https://youtu.be/mpI4vNrBYKE

The video seems to suggest as long as file is hosted publicly, app would be able to download, if yes is there any security risk of hosting Configure file publicly?

Thanks.

**Comment by minhcasi** [comment]
<img width="994" alt="Screen Shot 2020-09-03 at 09 20 05" src="https://user-images.githubusercontent.com/1459805/92063979-aa054100-edc6-11ea-9830-91ac6d9507c0.png">

You could upload this json config to Cloud and update this config to the URL, there is no security risk as the token is stored inside the config.dart  - we are working new feature to allow this feature could be uploaded via Fluxbuilder on next coming release of the Fluxbuilder

**Comment by minhcasi** [comment]
pls help us to give your all comment to one OPEN ticket support #4712
