### ISSUE TITLE
Error in Checkot Shipping Method In Release Build.

### ISSUE THREAD

**Issue by mohan1149** [inspireui/support#4847]
In release build Checkout Shipping , i am getting the following error.
![WhatsApp Image 2020-09-02 at 22 05 26](https://user-images.githubusercontent.com/61935068/92026888-61b83580-ed6a-11ea-966f-326e5499030c.jpeg)

**Comment by minhcasi** [comment]
@minhtruong315 - pls help to investigate this issue

**Comment by mohan1149** [comment]
in development mode everything is working , when we test from Test flight , its getting above error.

**Comment by minhtruong315** [comment]
@mohan1149 can u upload your source code to github and invite my email: minhtruong315@gmail.com

**Comment by mohan1149** [comment]
Given access and COD is not working , when i clicked on COD its going to other payment methods.

**Comment by minhtruong315** [comment]
@mohan1149 did you add me to your source code to check?
Can u record screen for the issue?
Thanks

**Comment by mohan1149** [comment]
I have sent you invitation. Source code is in Gitlab not Github.
And when there is not internet during checkout, we are getting generic error. Instead of that how can we show "Internet is not available" kind of message.
Below is the screenshot.
![WhatsApp Image 2020-09-04 at 22 20 49](https://user-images.githubusercontent.com/61935068/92278228-77119900-eefd-11ea-8d64-3380af599189.jpeg)

**Comment by minhtruong315** [comment]
Hi @mohan1149 I dont see any invitation. can u send me the link repo?

**Comment by mohan1149** [comment]
https://gitlab.com/owlconcepts/bboutique

**Comment by minhtruong315** [comment]
hi @mohan1149 I fixed your issues. pls checkout branch "develop" and check again

**Comment by mohan1149** [comment]
That will be very helpful.

How can I get push notification on Mobile when I change order status in website.

**Comment by minhtruong315** [comment]
@mohan1149 That function doesn't support now.
