### ISSUE TITLE
Product Stock Status not refreshing on Home Screen

### ISSUE THREAD

**Issue by Bozso21** [inspireui/support#4848]
Hi - I'm using list view on the home screen to display some products - I also added displaying availability function to show users if the products are available or not - but this status only refreshes if the user restarts the application. Do you have any dieas about this?

**Comment by minhcasi** [comment]
@Bozso21 - could you share the screenshot issues so that we could understand more about the issue - thanks

**Comment by Bozso21** [comment]
Hi, yes of course
![1_Munch hu_AppScreenshot_i11](https://user-images.githubusercontent.com/68916073/92080117-4b899400-edc1-11ea-8ea4-1d54ace90b3f.png)
It's on this screen - so for instance, you can see that the "Friss Déli Munch" is available, despite the fact that I set its quantity to 0. When I restart the app, its working - it disappears, however, until I restart it's not working properly.

**Comment by minhcasi** [comment]
@Bozso21 - you could zip this project and send to inspireui.team@gmail.com - we will help to investigate the issue (make sure to run flutter clean before compressing the source)

**Comment by minhcasi** [comment]
Let us know your updating - thanks

**Comment by Bozso21** [comment]
hi, we will test another view tomorrow

Minh Pham <notifications@github.com> ezt írta (időpont: 2020. szept. 5.,
Szo, 5:46):

**Comment by minhcasi** [comment]
how is your checking? Thank you!

**Comment by Bozso21** [comment]
This week we will get the update accepted I will respond to you asap

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by minhcasi** [comment]
Let us know your updating - thank you!

**Comment by minhcasi** [comment]
Feel free to reopen the ticket if you need any update - thank you!
