### ISSUE TITLE
Fluxstore multivendor app minor issues 

### ISSUE THREAD

**Issue by alazar-aklilu** [inspireui/support#4849]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
- [ ] first issue
- [ ] second issue
- [ ] third issue
1. i want to enable cash on delivery as the only payment system but i can't do that it brings all the getways on the site even if i only have cash on delivery on payments.dart
2. i don't want the map that is on the top right corner of store/category page
3. i want to edit the checkout page fields 
4.  i don't want vendors to sign-up on the app, i want them to create an account the website first and remove "register as vendor user"
5. can you please give me info on google map api is setting up an account necessary? and will i get lattitude and longitude after setting up the account?

+ Product & version: 
1.7.7 fluxstore multivendor
+ Flutter (or React Native) version: 
flutter
+ Testing Device/Simulator: 
samsung galaxy s8+ on android studio
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on https://verify.inspireui.com **

#3357 

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID
#3357 

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
1. The payment method is loaded dynamically from your site, if you would like to limit only COD, you could customize this file https://tppr.me/O0XVH

2+3+4. pls try your best to customize the UI by using Inspector Tool - https://docs.inspireui.com/fluxstore/customization/

5. The current feature only get the user location when they process the payment from the Address screen - https://tppr.me/TcX3D

**Comment by alazar-aklilu** [comment]
@minhcasi 
1. can you please clarify which part i edit it is not clear from the picture you sent
2, 3, 4  i will try and notify you of the result
5. okay i understand now

**Comment by minhcasi** [comment]
the example you could filter the payment method and only allow to view CDO on the UI

**Comment by minhcasi** [comment]
Let us know if you have any question 🥇

**Comment by alazar-aklilu** [comment]
@minhcasi I have fixed 2,3,4 but issue number 1. the payment method i couldn't figure it out. if you can please give me more info or anything on how to only view cash on delivery it would be very great. thanks

**Comment by alazar-aklilu** [comment]
![Screenshot_20200906-224955](https://user-images.githubusercontent.com/60713664/92334081-5bd89200-f093-11ea-8ce5-9128881da266.jpg)
i get this error after removing most of the checkout fields, the map and the register as vendor checkbox using inspector tool
