### ISSUE TITLE
[ListApp] App doesn´t have my content

### ISSUE THREAD

**Issue by Nachbarsaft** [inspireui/support#485]
- Product: ListApp
 - Your Purchased Code: I purchased MyList App on Envato 29th/11 purchase code ends with: 49bc14f56289 (don´t want to publically post the whole number here)

**Describe the issues**
I´ve managed to create something. But there is nothing of my content in there. Here is the app that I´ve created: https://expo.io/@myguyd/listapp-listable

**Screenshots**
Are my settings correct or do I need to include other Keys? If yes, where do I find them?
<img width="534" alt="App Config" src="https://user-images.githubusercontent.com/38483515/55672045-b1a17d00-5896-11e9-9ac8-87ede89d49db.PNG">

Do I need to define other adresses for IOS Bundle identifier & Android Package?
<img width="543" alt="List App Delivery Settings" src="https://user-images.githubusercontent.com/38483515/55672058-d72e8680-5896-11e9-85d6-6d73eb6bdc73.PNG">

**Additional context**
Here are some more screenshots: 
<img width="964" alt="Features not available in JSon settings" src="https://user-images.githubusercontent.com/38483515/55672074-f7f6dc00-5896-11e9-8d7f-e087eb6097bf.PNG">
<img width="1020" alt="many warnings" src="https://user-images.githubusercontent.com/38483515/55672075-f88f7280-5896-11e9-99ae-e4d11b1f774f.PNG">
<img width="1090" alt="more warnings and errors" src="https://user-images.githubusercontent.com/38483515/55672076-f88f7280-5896-11e9-9bde-c3f78a9cc62c.PNG">

And here is my wp-content file: https://1drv.ms/u/s!Aq6Mvuxj9CAnhZpmbmNuC0nswOD_-g

thank you for your help

**Comment by thangvo9x** [comment]
Do you have to try change categoryListingId in your Config ? 
you must have to change it for mapping to your website.

**Comment by Nachbarsaft** [comment]
> Do you have to try change categoryListingId in your Config ?
> you must have to change it for mapping to your website.

Could you please be a bit more precise. Where do I need to change the category Listing ID exactly? 

Did you look at the screenshots? do the settings look good?

**Comment by thangvo9x** [comment]
Hi. You should create one ticket for these problem.
1. You can change it in Config folder , (listable.js if you're using listapp theme, etc... )
2. I saw screenshots. 
3. You can share your admin to checking.
Thanks

**Comment by Nachbarsaft** [comment]
1.a do you mean in FTP? I don´t find the right file, or do you mean in the App Folder that I´ve downloaded? 
![image](https://user-images.githubusercontent.com/38483515/55842049-29d79f00-5b32-11e9-8710-d4d8d62deebf.png) 
1b. how do I need to change the categoryListingID? what would be the right ID?

2. Is everything correct?
3. Username: AppHelp
PW: smp0a2uesG@3zou%9pdDH@gj
Login: my-guyd.com/wp-admin

Please mark this private, as I don´t want everyone to see the admin login details.

**Comment by thangvo9x** [comment]
Please let me know your email. you can provide your ftp to that.

**Comment by Nachbarsaft** [comment]
Hi there,

here is my email: rschleu@hotmail.de<mailto:rschleu@hotmail.de>


the FTP Access Details are These:


Server:

webhosting76.1blu.de


Username: ftp269815-program
Passwort: program@MyGuyd2019!


Please let me know about the following steps.

Cheers,

Raphael
________________________________
Von: Tony Vo <notifications@github.com>
Gesendet: Tuesday, April 16, 2019 8:50:06 AM
An: inspireui/support
Cc: Nachbarsaft; Author
Betreff: Re: [inspireui/support] [ListApp] App doesn´t have my content (#485)


Please let me know your email. you can provide your ftp to that.

**Comment by thangvo9x** [comment]
Hi guys, I sent the source to you, please check your inbox. Thanks.

**Comment by Nachbarsaft** [comment]
No Problem has been solved, the website is super slow now and I basically can´t use it. Even Wp-ADmin area is slow after your changes!
