### ISSUE TITLE
Webview Checkout issue and header dark mode issue

### ISSUE THREAD

**Issue by jvsamoa** [inspireui/support#4853]
Hi Team, me here again.

In flux store 1.7.5 the webview checkout was available, but now before I upgrade to lastest version checkout button stay loading but it doesn´t go to my website.  Can you help me?

![image](https://user-images.githubusercontent.com/25646978/92069533-e5dddd80-eda9-11ea-9e7d-c5a6eb604f97.png)

![image](https://user-images.githubusercontent.com/25646978/92068854-4409c100-eda8-11ea-823d-5420000ffc4d.png)

Also, in dark version, the app icon and welcome text (header text) is not showing correctly.
![image](https://user-images.githubusercontent.com/25646978/92068837-3d7b4980-eda8-11ea-82b6-44dedf231896.png)

Regards.

**Comment by minhcasi** [comment]
@jvsamoa - pls try to update `NativeOnePageCheckout: true`

**Comment by jvsamoa** [comment]
![image](https://user-images.githubusercontent.com/25646978/92181680-20975280-ee4a-11ea-87ac-75df2da150e3.png)

Hi, thanks for your anwser. But can you help me with my second question, the icon and header text is white and I can´t visualize my welcome phrase.

**Comment by minhcasi** [comment]
Could i know what type of widget for that Header Text? You could try to add the color value to see if it could be fixed?

**Comment by minhcasi** [comment]
Let us if you have any question or update on this ticket - thank you! 👍

**Comment by jvsamoa** [comment]
Hi, sorry for my delay.
This is a widget composition inside of the config_xx file. 

{
      "title": "Bienvenidos a nuestra app",
      "fontSize":19,
      "showSearch":false,
      "height":0.13,
      "isSafeArea":true,
      "layout":"header_text",
      "padding":30
    },
