### ISSUE TITLE
Products are getting duplicated 

### ISSUE THREAD

**Issue by febinmhd** [inspireui/support#4856]
i have added for eg. 3 products but when i view the products they are duplicated and i see 2 of each 6 products. please advice
![IMG_6351](https://user-images.githubusercontent.com/51330162/92091052-dd50cb80-edd8-11ea-8583-c65a059a11bd.PNG)
![IMG_6350](https://user-images.githubusercontent.com/51330162/92091065-e0e45280-edd8-11ea-9513-236e247072c6.PNG)

**Comment by minhcasi** [comment]
@febinmhd - pls help to comments into one open ticket #4855 - thank you!
