### ISSUE TITLE
WooCommerce Error: Invalid signature - provided signature does not match.

### ISSUE THREAD

**Issue by MobileAppGwt** [inspireui/support#4857]
Hi,
I'm using Fluxstore 1.7.7 Woocommerce, while try to access rest api I'll get this WooCommerce Error: Invalid signature - provided signature does not match. I have configured as per the docs from [https://docs.inspireui.com/fluxstore/woocommerce-setup/#2-app-integration](url), kindly help to resolve this error. Thanks in advance :1st_place_medal:

**Comment by minhcasi** [comment]
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support https://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
@MobileAppGwt - could you try to download fluxbuilder app and verify the integration issue with your website - http://fluxbuilder.com/ - thank you!

**Comment by MobileAppGwt** [comment]
![Screenshot (2)](https://user-images.githubusercontent.com/68996868/92219169-d351ca00-eeb7-11ea-97dd-10027cf34ffc.png)
This error get thrown while connecting with fluxbuilder.

**Comment by MobileAppGwt** [comment]
And this warnings are shown in mstore api config in website
![flux](https://user-images.githubusercontent.com/68996868/92219484-3f343280-eeb8-11ea-864d-90a44e02da88.jpg)

**Comment by minhcasi** [comment]
@minhtruong315 - pls help to fix this warning from mstore-api

**Comment by MobileAppGwt** [comment]
Yeah we are currently working on it @minhcasi

**Comment by minhtruong315** [comment]
Hi @MobileAppGwt Can u try to reinstall this version for MStore Api plugin?
[mstore-api.zip](https://github.com/inspireui/support/files/5178934/mstore-api.zip)

**Comment by MobileAppGwt** [comment]
Actually the issue is because I have followed the wrong authentication method , after I refer this docs I understand the mistake and it's resolved https://woocommerce.github.io/woocommerce-rest-api-docs/v3.html?javascript#authentication, Thank you :100:
