### ISSUE TITLE
Mstore mv specific vendor product list not display

### ISSUE THREAD

**Issue by kevadiya** [inspireui/support#4859]
http://smartlady.co.in/wp-json/dokan/v1/stores/20/products

Please check this one

**Comment by minhcasi** [comment]
@kevadiya - could you help to share your screenshot issue - thank you!

**Comment by kevadiya** [comment]
![Screenshot_20200905-142103](https://user-images.githubusercontent.com/4812340/92301673-1fb60c00-ef83-11ea-95b2-2009c60e3c93.png)
This is vendor page. At this page vendor product is not shown. 

I HAVE ALSO THIS ONE
The issues appear 2 problems, the first please change this.page = props.page ? props.page : 0; to this.page = props.page ? props.page : 1; 

http://smartlady.co.in/wp-json/dokan/v1/stores/20/products

**Comment by luyx2412** [comment]
HI @kevadiya Can you explain your issue? You meant you replace `this.page = props.page ? props.page : 0;` to `this.page = props.page ? props.page : 1;` and the issue still exist?

Thanks

**Comment by kevadiya** [comment]
Yes sir

**Comment by kevadiya** [comment]
Still there is an issue

**Comment by rudraumapp** [comment]
Awaiting for your reply?

**Comment by luyx2412** [comment]
Hi @kevadiya Can you send your project via inspireui.team@gmail.com with title `4859`, let me investigate and reply you soon.

Hi @rudraumapp Please create your issue, and fill the form http://verify.inspireui.com/. Let me investigate easier.

Thanks

**Comment by rudraumapp** [comment]
@kevadiya have mailed you. we both are doing this project. also check in my profile page we have setup a label called "Whatsapp Us", the function is working but the label text is not showing. Please Check!

**Comment by kevadiya** [comment]
Mail sent. Please checkout

**Comment by kevadiya** [comment]
> @kevadiya have mailed you. we both are doing this project. also check in my profile page we have setup a label called "Whatsapp Us", the function is working but the label text is not showing. Please Check!

Also see this one

**Comment by rudraumapp** [comment]
Any update? Also do check onesignal problem... It's not working!

**Comment by rudraumapp** [comment]
When can we receive the update as we have already sent you the code!?

**Comment by minhcasi** [comment]
@rudraumapp 
We wanted to thank you for your patience during this epidemic time. We currently have reduced staff and a significantly higher volume of inquiries. We’re working as hard as we can to get to your request as soon as possible.
We sincerely apologize for the delay and hope you’re staying safe.

@luyx2412 - please help to check the ticket as a high priority

**Comment by rudraumapp** [comment]
Thanks for the reply. Please look into this as my last ticket was closed by you but that error remained same and now you have asked me to share the code and I did that, now pls resolve this

**Comment by luyx2412** [comment]
Hi @rudraumapp I reply you via email, please check and download the source code to fix the issue.

Thanks

**Comment by minhcasi** [comment]
@kevadiya @rudraumapp - How is your checking??

**Comment by rudraumapp** [comment]
We are checking right now

**Comment by rudraumapp** [comment]
still i'm unable to view the products on vendor selection page!!!

**Comment by rudraumapp** [comment]
there are products in vinith jain, muskan vendors but it's not showing
![WhatsApp Image 2020-09-15 at 12 15 19](https://user-images.githubusercontent.com/70805211/93175453-46c3c900-f74d-11ea-88c0-8e2846200ab8.jpeg)

**Comment by rudraumapp** [comment]
Also Whatsapp us label not appearing still!!!!! None of the problem got resolved, it is still same!!!!!!
![WhatsApp Image 2020-09-15 at 12 17 50](https://user-images.githubusercontent.com/70805211/93175624-8be7fb00-f74d-11ea-81bc-f131ad74afee.jpeg)

**Comment by kevadiya** [comment]
We have seen Google drive source there is no changes.
Also no menu seen user profile page

**Comment by luyx2412** [comment]
Hi @kevadiya Please list the issue, let me fix and send you source code. I forgot send you the link via email, i will send right now.
HI @rudraumapp Who are you? Please answer me one people, i will miss the issue. So please do not spam.

Thanks

**Comment by rudraumapp** [comment]
Ok... @kevadiya will answer you from now onwards.

**Comment by kevadiya** [comment]
Issues:
1. Unable to view the products on vendor/Store page.
2. Whatsapp Us label not viewing on profile page.
3. Unable to connect with onesignal even after adding the app id from onesignal.

**Comment by minhcasi** [comment]
@luyx2412 - pls help to investigate

**Comment by kevadiya** [comment]
how can I change the background color of app which is light grey? I have searched and found that in color.js everything gets changed but for background there is no option. https://imgur.com/f3G4AlQ

**Comment by kevadiya** [comment]
Also check mail

**Comment by kevadiya** [comment]
one more bug, only 10 vendors are showing

Add function to show more on scroll

**Comment by luyx2412** [comment]
Hi @kevadiya 
- The issue resolve with source code sent via email
- Please add this code in `src/containers/UserProfile/index.js` line 99 same the screenshot
```
          case "WhatsappUs":
            items.push({
              ...item,
              label: `WhatsApp`,
            });
            break;
```
![image](https://user-images.githubusercontent.com/8909619/93353480-2dfb0680-f866-11ea-965f-10dd6cd0b911.png)
- Please read the document to setup onesignal for expo project https://documentation.onesignal.com/docs/react-native-sdk-setup
- Current we just support load 10 vendors. You can implement yourself about the load more option.

Thanks

**Comment by rudraumapp** [comment]
“Current we just support load 10 vendors. You can implement yourself about the load more option.” this was the answer I have received and this is not at all appropriate, my vendors are keep on calling me that their names are not been listed on the app? 

What about background changing

**Comment by rudraumapp** [comment]
It's humble request to fix the bug asap!

**Comment by rudraumapp** [comment]
![Capture](https://user-images.githubusercontent.com/70805211/93592387-b6e18180-f9cf-11ea-806c-f09c4bb82fe8.PNG)

**Comment by rudraumapp** [comment]
No updates from last many days?

**Comment by luyx2412** [comment]
HI @rudraumapp we are implementing the pagination for vendors tab, we will send you the source code soon.

Thanks

**Comment by rudraumapp** [comment]
thanks

**Comment by rudraumapp** [comment]
when can I expect to receive it!

**Comment by minhcasi** [comment]
Our team is working hard to support you, even helping over our weekend, but it would be nice if stopping sending spam on the product rating, thanks for your time!

**Comment by luyx2412** [comment]
Hi @rudraumapp I just emailed the source code which added vendor pagination. So please check email.

Thanks

**Comment by rudraumapp** [comment]
Thanks. I'll get back to you once I check it.

**Comment by rudraumapp** [comment]
Hey! still 10 vendors are only showing

![10](https://user-images.githubusercontent.com/70805211/93669059-cd123f00-faae-11ea-91ff-9e186d90d701.jpg)

**Comment by luyx2412** [comment]
Hi @rudraumapp Please scroll to bottom to see more.

Thanks

**Comment by rudraumapp** [comment]
please check this video.....
https://youtu.be/rHPzur1yWQI

**Comment by rudraumapp** [comment]
Hello Sir, I think you have mailed us the old code link which you have given us few days before.  Kindly check!

**Comment by kevadiya** [comment]
Hello, where is download link of source code. You send me mail you forgotten link.

Send me source code link

As soon as possible

**Comment by rudraumapp** [comment]
Gentle Reminder! Any update guys?

**Comment by luyx2412** [comment]
Hi @rudraumapp I sent email, please check it
![image](https://user-images.githubusercontent.com/8909619/93850144-b4d13880-fcd7-11ea-9925-4b62634d691c.png)

Thanks

**Comment by kevadiya** [comment]
Vendor pagination successful completed. But I have seen new error when I open specific vendor at that time show only 20 product. So I need pagination at there.

Because it's major bug

So solve as soon as possible

And inform me

**Comment by minhcasi** [comment]
we are announcing that a new ticket support system is available on this link https://support.inspireui.com 

Please help to move your next comment on the new support system (you could mention this ticket so that the team could know more about the ticket's history) - thank you for your time!
