### ISSUE TITLE
payment cancel total app keep loading

### ISSUE THREAD

**Issue by ssathamenterprises** [inspireui/support#4860]
hello sir 

i done my all setup upload in playstore and apple store 

but i found one issue

in native paypal method when i cancel the payment  ( after that its always keep loading )

here i attach my proof of purchase and issue image
![Screenshot (24)](https://user-images.githubusercontent.com/68118999/92124489-6e06c600-ee30-11ea-8406-d2574ac12b53.png)

<img width="782" alt="proof of purchase" src="https://user-images.githubusercontent.com/68118999/92124547-7eb73c00-ee30-11ea-9ca4-10e723559028.PNG">

**Comment by minhcasi** [comment]
@ssathamenterprises - thank you for reporting

@tgloc96 - please help to upgrade this UX issue for both fluxstore core & MV version

**Comment by ssathamenterprises** [comment]
@minhcasi  thanks 

 I ask one developer fixed the loading issue  today , but currently when I cancel payment it’s back to checkout page ( in order page not shows the order  cancel details) in payment gateway they capture the failed transaction please help on this sir ( I attached one image for cancel payment order This order cancel from website so it’s shows in order page but use mobile app cancel the payment it’s not display in order page )
![3F8DB38E-7BB1-4AA7-8236-B38207B54DE5](https://user-images.githubusercontent.com/68118999/92192350-65e27100-ee98-11ea-994d-650af728f535.jpeg)

**Comment by minhcasi** [comment]
@ssathamenterprises - could you help to share the solution for fixing `loading issue` - i will include that fix on the project as well. 

You could try to enable the `EnableRefundCancel` to see if it could enable the refund feature:
<img width="799" alt="Screen Shot 2020-09-07 at 10 00 20" src="https://user-images.githubusercontent.com/1459805/92344544-f3b89900-f0f0-11ea-8f37-6a30af282c92.png">

**Comment by ssathamenterprises** [comment]
I ask the developer, I will update here

**Comment by ssathamenterprises** [comment]
In shipping when i select country india ( state shows wrong ) it shows other country states .

only this issue when i select india

i attached video here 

https://drive.google.com/file/d/1AyN7gdBTdx62lnn_l2DQ6FRMhYl5bZDb/view?usp=sharing

**Comment by ssathamenterprises** [comment]
@minhcasi  when i select country  india its shows all Indonesia states

**Comment by ssathamenterprises** [comment]
My developer said he make some changes in payment-screen ( for the loading issue) I don’t know the exact what he did
