### ISSUE TITLE
social login for Sha-1 error

### ISSUE THREAD

**Issue by ornekali** [inspireui/support#4862]
Hello, I tried to run this page
https://medium.com/@inspireui/setup-google-login-for-flutter-apps-fedc58a490b8

I have an error - (key-debug.properties), (.keystore) could not be found and the video may be outdated.

and I don't have any file with extension .keystore, I have .jks

I tried to make the codes in the video according to my software, but I could not reach SHA-1.

What kind of code should I write for the terminal in this version? I would like you to help me.

[
![InkedIMG_7143_LI](https://user-images.githubusercontent.com/69655669/92142601-c46a0980-ee1c-11ea-990d-25ae6fdf13f5.jpg)
](url)

+ Product & version:1.7.7

**Comment by minhcasi** [comment]
@ornekali - you could create new local.properties file - pls check out more detail about the keystore on this link https://flutter.dev/docs/deployment/android

**Comment by minhcasi** [comment]
Let us know your checking - thank you!

**Comment by ornekali** [comment]
> Let us know your checking - thank you!


405/5000
Which of these steps should I do?
Is there a tutorial video lesson for this?
So far everything is going well, but it is very sad that this is not happening between the courses, I tried by reinstalling the latest update package, but I am facing the problem again,
I would like to enlighten me on this subject, if possible I would be very happy if you could connect remotely or add a video tutorial about it.

**Comment by ornekali** [comment]
> @ornekali - you could create new local.properties file - pls check out more detail about the keystore on this link https://flutter.dev/docs/deployment/android
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/b79d5f795eac013611f2dac92850a689fc9d3d46/68747470733a2f2f666c75747465722e6465762f696d616765732f666c75747465722d6c6f676f2d73686172696e672e706e67">**[Build and release an Android app](https://flutter.dev/docs/deployment/android)**How to prepare for and release an Android app to the Play store.

I need the SHA-1 code to complete sosya entries like Google Facebook in Firebase, isn't there an easier way to do that?

**Comment by minhcasi** [comment]
@ornekali - you could check this solution to get SHA1 - https://stackoverflow.com/questions/51845559/generate-sha-1-for-flutter-app

**Comment by minhcasi** [comment]
Let us know your checking - thanks

**Comment by ornekali** [comment]
> @ornekali-SHA1 almak için bu çözümü kontrol edebilirsiniz - https://stackoverflow.com/questions/51845559/generate-sha-1-for-flutter-app
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/2c037ef1f96dacaa2d1a1764a49f8dbd5b6a3316/68747470733a2f2f63646e2e737374617469632e6e65742f53697465732f737461636b6f766572666c6f772f496d672f6170706c652d746f7563682d69636f6e40322e706e673f763d373364373961383962646564">Yığın Taşması**[Flutter uygulaması için SHA-1 oluşturun](https://stackoverflow.com/questions/51845559/generate-sha-1-for-flutter-app)**Android Studio'nun Google oturum açmasını desteklemesi için bir Flutter uygulaması için bir SHA-1 oluşturmaya çalışıyorum, ancak bunu nasıl yapacağımı bilmiyorum, bir komut çalıştırmayı gösteren bazı mesajlar gördüm, ama orada ihtiyacım var ...

Thank you minhcasi problem solved :)
