### ISSUE TITLE
Check out not working

### ISSUE THREAD

**Issue by lakshayb121** [inspireui/support#4863]
Hey i have already verified my purchase so don't ask me that again, i get this error when i click on checkout please give a solution asap.
![Screenshot_2020-09-03-19-51-38-65_9a2726ec10114b0f6a0ccb9b85fcd26f.jpg](https://user-images.githubusercontent.com/55995898/92148722-97c4ea80-ee3a-11ea-8275-f91b0fc47c32.jpg)

And one more thing is their anyway i can make images of the products of same size?

And i asked to remove the side menu i did what was told to me but still the menu opens if i slide to right on homepage and menu button is still on settings tab
![Uploading Screenshot_2020-09-03-20-36-49-27_9a2726ec10114b0f6a0ccb9b85fcd26f.jpg …]()![Uploading Screenshot_2020-09-03-20-36-52-97_9a2726ec10114b0f6a0ccb9b85fcd26f.jpg …]()![Screenshot_2020-09-03-20-36-57-45_9a2726ec10114b0f6a0ccb9b85fcd26f.jpg](https://user-images.githubusercontent.com/55995898/92148897-d8246880-ee3a-11ea-81c0-e087b59fb5d6.jpg)

**Comment by minhcasi** [comment]
@lakshayb121 - could i know if you are using the latest release `1.7.7` - thank you!

**Comment by lakshayb121** [comment]
> @lakshayb121 - could i know if you are using the latest release `1.7.7` - thank you!

@luyx2412 yes i am using the latest version 1.7.7

**Comment by luyx2412** [comment]
Hi @lakshayb121 I just invited you to the fluxshopify repo which fixed the issue. Before run it, please uninstall the app and reinstall again to clear cache.

Thanks

**Comment by lakshayb121** [comment]
> Hi @lakshayb121 I just invited you to the fluxshopify repo which fixed the issue. Before run it, please uninstall the app and reinstall again to clear cache.
> 
> Thanks

@luyx2412 ok i will check the latest repo and can you instruct me to remove drawer menu? I coded it as hidemenu=true, but it still opens the menu if anyone right swipe in app

**Comment by madilsharief** [comment]
I got same issue. was this solved? whats the solution. I have updated version/repos/and dependencies everything is updated.

**Comment by lakshayb121** [comment]
> I got same issue. was this solved? whats the solution. I have updated version/repos/and dependencies everything is updated. 

This is the worst support dont rely on them.

**Comment by luyx2412** [comment]
Hi @lakshayb121 Sorry about that. I have some personal reason, so i could not support you well. If you not happy about it, please submit the refund http://themeforest.net/refund_requests/new.

Thanks

**Comment by madilsharief** [comment]
Kindly do not close the issue cause others are also facing this. I have filled the form and submitted to you. Kindly let me know what to do next about this
