### ISSUE TITLE
Mobile number sign up not working

### ISSUE THREAD

**Issue by lakshayb121** [inspireui/support#4864]
I enabled mobile number sign ups in firebase but it shows an error when i login. It is successfully linked with firebase as i get the otp code. But when i fill the otp it shows this error. My product is fluxstore shopify.
![Screenshot_2020-09-04-01-01-40-70_2718f369eb4146d6b352274f60f83e87.jpg](https://user-images.githubusercontent.com/55995898/92159166-98fe1380-ee4a-11ea-8445-bde8a5976328.jpg)

**Comment by minhcasi** [comment]
@lakshayb121 - sorry the SMS Login on Fluxstore Shopify it not ready support due to limit of the Shopify API - it only supports to work with default email/password from Shopify 

Pls help to move you all comment into one open ticket - #4863 - thank you!
