### ISSUE TITLE
 Instagram content does not load and generates errors

### ISSUE THREAD

**Issue by lpzczar** [inspireui/support#4866]
Hi, I'm looking for help with a problem in the fluxnews app. Thanks in advance

**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
- [ ] first issue
In the v1.4.3 of fluxnews the instagram Posts show an error
- [ ] second issue
in the v1.4.0 of fluxnews this post with instagram content only loads the image of  the post
- [ ] third issue

+ Product & version: fluxnews v1.4.0 & 1.4.3
+ Flutter (or React Native) version:  1.20.2
+ Testing Device/Simulator: iPhone 11 Pro Max / Android 10
+ Screenshot issues (drag the file to attach here): 
v1.4.0
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-09-03 at 16 35 15](https://user-images.githubusercontent.com/19940455/92176213-a04dfe80-ee03-11ea-8fcb-bf223fa2105f.png)

v1.4.3
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-09-03 at 16 34 23](https://user-images.githubusercontent.com/19940455/92176236-ab089380-ee03-11ea-942e-145665e0a93c.png)

**_Step 2 (require): submit proof of purchasing the license on https://verify.inspireui.com **

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@lpzczar - sorry the Fluxnews is not supported for the Instagram embed code, you could try to embed the Instagram inside the iframe, then it could be worked
