### ISSUE TITLE
No data on the "notify messages" screen

### ISSUE THREAD

**Issue by Justnopeople** [inspireui/support#4868]
![image](https://user-images.githubusercontent.com/49190031/92198935-ebb5ea80-ee9f-11ea-8320-6c2628eafa4b.png)
image 1

Image 1 : When sending a notification message from the firebase dashboard the top notification bar is appear. But when it come to the "notify messages" screen, there is no notification message, as shown in image 2.

![image](https://user-images.githubusercontent.com/49190031/92199241-c70e4280-eea0-11ea-89f6-459a63334833.png)
image 2

Pls help me to fix this problem as soon as possible. Thx

**Comment by minhcasi** [comment]
@Justnopeople - could i know if you are using the latest Fluxstore 1.7.7?

**Comment by Justnopeople** [comment]
no, i still using version 1.7.3

**Comment by minhcasi** [comment]
Pls try to use the latest Fluxstore 1.7.7 to fix this issue

**Comment by Justnopeople** [comment]
i want to update it to version 1.7.7 but i has editfull that app version
1.7.3 according to the wishes of my company

**Comment by minhcasi** [comment]
You could try to update manually the pubspec library from 1.7.7 to make your app compatible with the latest flutter and copy some features to fix the issues, for example current push notification issue.

This blog post could be helpful - https://medium.com/@inspireui/how-to-upgrade-fluxstore-projects-by-using-git-cebde7489ea6

**Comment by Justnopeople** [comment]
I have tried using the latest version 1.7.7 but it still doesn't work. Can
only show notification in the top bar but on the "Notifiy Messages" screen
still does not display anything

**Comment by minhcasi** [comment]
@Justnopeople - could i know if you are testing on the real device? It's working fine with our testing - thank you!

**Comment by Justnopeople** [comment]
I have tested both using real device and emulator but it still doesn't
work. Is there a possible missing configuration?

**Comment by minhcasi** [comment]
@Justnopeople - let me confirm with the team to see if they have fixed on the latest release 1.7.8

**Comment by Alnaggar94** [comment]
@minhcasi - I confirm it doesn't work please fix it in the coming version

**Comment by Justnopeople** [comment]
I will be patiently waiting for the latest release to fix it 😊

**Comment by minhcasi** [comment]
Confirmed fixed on the latest release, we will update it on next couple of days.

Please help to move the new conversation to new Ticket Support http://support.inspireui.com (you could mention on this ticket history) - thank you!
