### ISSUE TITLE
BLANK HOME PAGE 2

### ISSUE THREAD

**Issue by iqmtgar** [inspireui/support#487]
Purchase code: 886b666c-7336-4a0e-b5c6-95e0a80c7d61

1.installed CE builder and verified licence and run setup its installed the node_modules
2.after changed
a.listapp/App/Common/Appconfig.js website url and keys
b. am using mylisting theme

3.after changed index.js and mylistingjs app/common/config /folder
4.installed all the plugins WordPress comes with codecanyon downloads .
5.run expo start and published the project .
6.when i run the app home page is blank only WordPress post is showing
https://user-images.githubusercontent.com/47878412/53220310-b4af1980-3618-11e9-8102-5a03070a2eee.jpeg
I know there is a problem
Same problem
I apologize but could not solve it?
Thank you

**Comment by thangvo9x** [comment]
Hi. I can't check your purchase code. Do you miss it? 
You can change categoryListing to your website?
Thanks

**Comment by iqmtgar** [comment]
You can change categoryListing to your website?
Please
how can that?
Purchase code: aa4a0386-d773-4046-b308-72e1a693f047

**Comment by thangvo9x** [comment]
Go to Config/MyListing.js, go to horizontalLayout property
if you're using MyListing theme.
p/s : I still can't check your purchase code.
Thanks

**Comment by iqmtgar** [comment]
You've purchased these apps
I'm having trouble installing them
Hope helped me even though
im using theme Listify
https://d.top4top.net/p_11936gy4m1.png

**Comment by thangvo9x** [comment]
Hi. Can you share your AppConfig for integrating help u, plz?
