### ISSUE TITLE
MStore Pro Login-Register Issue

### ISSUE THREAD

**Issue by JokerZ01** [inspireui/support#4871]
By following Mstore Pro documentation, installation was completed. I have no problem with adding new products or categorization. However, when I tried to register or login, I got an error message: " No route was found  matching the URL and request method."  

Product & version: MStore Pro
Testing Device/Simulator: Android

Screenshot:
![photo](https://user-images.githubusercontent.com/19242572/92211090-8f030180-ee98-11ea-9097-da909849dd12.jpg)

The previous  verified ID:
https://github.com/inspireui/support/issues/4793

**Comment by JokerZ01** [comment]
Dear @luyx2412 , this is really important for me. So, I will be very glad if you can help, as soon as you can, please. Thanks.

**Comment by JokerZ01** [comment]
Hey, I filled it 2 days ago. Is there anything new?

**Comment by luyx2412** [comment]
Hi @JokerZ01 Please send your website information or invite inspireui.team@gmail.com to your wordpress admin website. Let me investigate and reply you soon. Because the config website setup something was wrong.

Thanks

**Comment by JokerZ01** [comment]
Hey @luyx2412 , I added this email to admin website.

**Comment by luyx2412** [comment]
Hi @JokerZ01 Please email account information and add the title `4871`, i did not see invitation email. And please upgrade to MStore 4.0, i just checked your Config and it is old version.

Thanks

**Comment by JokerZ01** [comment]
I sent an email. Subject is the issue number. @luyx2412

**Comment by luyx2412** [comment]
Hi @JokerZ01 I saw your website is http, so please enable ssl to secure your website. The issue related ssl.

Thanks

**Comment by JokerZ01** [comment]
How can I upgrade? @luyx2412

**Comment by luyx2412** [comment]
Hi @JokerZ01 Please connect your domain website where you bought it, and they will help you. 

Thanks

**Comment by JokerZ01** [comment]
Sorry, I mean that how can I upgrade to Mstore 4.0? @luyx2412

**Comment by luyx2412** [comment]
Please check in your codecanyon account about the Mstore.

Thanks

**Comment by JokerZ01** [comment]
I downloaded the latest package. And it is named as "mstore-4.0.0". Also, SSL is active now. @luyx2412

**Comment by minhcasi** [comment]
refunded
