### ISSUE TITLE
White screen, app builds but does not Launch FluxstoreMV 1.7.7

### ISSUE THREAD

**Issue by T3kken** [inspireui/support#4873]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
I have tried to test and build and android app but on this version it seems everything is going wrong. As per details below the app generates but products do not show all I have is a white screen. For the iOS app its a complete failure. I had succeeded with version 1.7.6 to build the android app but for security reason as per google play changes apk was not uploaded, again the ios was never a success. It seems version 1.7.7 has so many issues according to the support tickets. 
All developer's environment on my Mac is update.

**************I have included the debug information below.*********** 
Launching lib/main.dart on sdk gphone x86 in debug mode...
Running Gradle task 'assembleDebug'...
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Waiting for sdk gphone x86 to report its views...
Debug service listening on ws://127.0.0.1:50117/e2S0dLxkQ-Y=/ws
Syncing files to device sdk gphone x86...
I/luxstore.venda(13829): The ClassLoaderContext is a special shared library.
I/luxstore.venda(13829): Waiting for a blocking GC ClassLinker
I/luxstore.venda(13829): WaitForGcToComplete blocked ClassLinker on ClassLinker for 30.017ms
I/cr_LibraryLoader(13829): Loaded native library version number "83.0.4099.5"
I/cr_CachingUmaRecorder(13829): Flushed 3 samples from 3 histograms.
W/luxstore.venda(13829): Accessing hidden method Llibcore/io/Memory;->peekLong(JZ)J (greylist, reflection, allowed)
W/luxstore.venda(13829): Accessing hidden method Llibcore/io/Memory;->pokeLong(JJZ)V (greylist, reflection, allowed)
W/luxstore.venda(13829): Accessing hidden method Llibcore/io/Memory;->pokeInt(JIZ)V (greylist, reflection, allowed)
W/luxstore.venda(13829): Accessing hidden method Llibcore/io/Memory;->peekInt(JZ)I (greylist, reflection, allowed)
W/luxstore.venda(13829): Accessing hidden method Llibcore/io/Memory;->pokeByte(JB)V (greylist, reflection, allowed)
W/luxstore.venda(13829): Accessing hidden method Llibcore/io/Memory;->peekByte(J)B (greylist, reflection, allowed)
W/luxstore.venda(13829): Accessing hidden method Llibcore/io/Memory;->pokeByteArray(J[BII)V (greylist, reflection, allowed)
W/luxstore.venda(13829): Accessing hidden method Llibcore/io/Memory;->peekByteArray(J[BII)V (greylist, reflection, allowed)
W/luxstore.venda(13829): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, reflection, allowed)
W/luxstore.venda(13829): Accessing hidden field Ljava/nio/Buffer;->address:J (greylist, reflection, allowed)
W/luxstore.venda(13829): Accessing hidden method Lsun/misc/Unsafe;->arrayBaseOffset(Ljava/lang/Class;)I (greylist,core-platform-api, reflection, allowed)
W/luxstore.venda(13829): Accessing hidden method Lsun/misc/Unsafe;->arrayIndexScale(Ljava/lang/Class;)I (greylist,core-platform-api, reflection, allowed)
W/luxstore.venda(13829): Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist,core-platform-api, reflection, allowed)
W/luxstore.venda(13829): Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist,core-platform-api, reflection, allowed)
W/luxstore.venda(13829): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, reflection, allowed)
W/luxstore.venda(13829): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist,core-platform-api, reflection, allowed)
W/luxstore.venda(13829): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist,core-platform-api, reflection, allowed)
W/luxstore.venda(13829): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist,core-platform-api, reflection, allowed)
I/luxstore.venda(13829): Waiting for a blocking GC ProfileSaver
W/luxstore.venda(13829): Accessing hidden method Landroid/view/accessibility/AccessibilityNodeInfo;->getSourceNodeId()J (greylist, reflection, allowed)
W/luxstore.venda(13829): Accessing hidden method Landroid/view/accessibility/AccessibilityRecord;->getSourceNodeId()J (greylist, reflection, allowed)
W/luxstore.venda(13829): Accessing hidden field Landroid/view/accessibility/AccessibilityNodeInfo;->mChildNodeIds:Landroid/util/LongArray; (greylist, reflection, allowed)
W/luxstore.venda(13829): Accessing hidden method Landroid/util/LongArray;->get(I)J (greylist, reflection, allowed)
D/HostConnection(13829): HostConnection::get() New Host Connection established 0xf1e204d0, tid 13876
D/HostConnection(13829): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_3_0 
W/OpenGLRenderer(13829): Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
I/Gralloc4(13829): mapper 4.x is not supported
D/EGL_emulation(13829): eglCreateContext: 0xf1c24890: maj 3 min 0 rcv 3
D/EGL_emulation(13829): eglMakeCurrent: 0xf1c24890: ver 3 0 (tinfo 0xb41cde10)
D/HostConnection(13829): createUnique: call
D/HostConnection(13829): HostConnection::get() New Host Connection established 0xf1e1f270, tid 13888
D/eglCodecCommon(13829): allocate: Ask for block of size 0x100
D/eglCodecCommon(13829): allocate: ioctl allocate returned offset 0x3fdab1000 size 0x2000
D/HostConnection(13829): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_3_0 
I/FA      (13829): Tag Manager is not found and thus will not be used
D/HostConnection(13829): HostConnection::get() New Host Connection established 0xf1e213d0, tid 13888
D/HostConnection(13829): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_3_0 
D/EGL_emulation(13829): eglMakeCurrent: 0xf1c21870: ver 3 0 (tinfo 0xbccc4c70)
I/luxstore.venda(13829): Background young concurrent copying GC freed 5434(655KB) AllocSpace objects, 3(60KB) LOS objects, 29% free, 4506KB/6437KB, paused 1.055ms total 1.356s
I/luxstore.venda(13829): WaitForGcToComplete blocked ProfileSaver on ClassLinker for 1.294s
I/luxstore.venda(13829): Background concurrent copying GC freed 19668(1441KB) AllocSpace objects, 12(528KB) LOS objects, 49% free, 5461KB/10MB, paused 2.415ms total 294.637ms
D/EGL_emulation(13829): eglMakeCurrent: 0xf1c24890: ver 3 0 (tinfo 0xb41cde10)
I/Choreographer(13829): Skipped 230 frames!  The application may be doing too much work on its main thread.
I/flutter (13829): [2020-09-04 08:46:59.575955Z][Fluxstore][main] ============== main.dart START ==============
D/EGL_emulation(13829): eglMakeCurrent: 0xf1c21870: ver 3 0 (tinfo 0xbccc4c70)
I/flutter (13829): [2020-09-04 08:47:00.820464Z][Fluxstore][AppState] initState
I/flutter (13829): [2020-09-04 08:47:00.878202Z][Fluxstore][AppState] build
I/flutter (13829): [2020-09-04 08:47:01.075178Z][Fluxstore][AppState] build Theme
I/flutter (13829): [2020-09-04 08:47:03.203938Z][Fluxstore]screenName /
I/flutter (13829): [2020-09-04 08:47:03.588781Z][Fluxstore][AppState] Inital Data
I/flutter (13829): [2020-09-04 08:47:04.170124Z][Fluxstore][AppState] init mobile modules ..
I/flutter (13829): [2020-09-04 08:47:04.201105Z][Fluxstore][AppState] register modules .. DONE
I/flutter (13829): [2020-09-04 08:47:04.311925Z][Fluxstore][Services] setAppConfig: --> dokan <--
E/OneSignal(13829): promptPermission() is not applicable in Android
I/flutter (13829): [2020-09-04 08:47:04.694171Z][Fluxstore][FCM]--> token: [ c9Y3AxVK5s0:APA91bHDaHaIY8d_WRNFlAac7a56xvz_cy57XUZbKDOKGiHByEq495phI8iRcZa6rJCsvqllb
![9DD49F05-7BF0-4D9A-A89E-1788C8490DE3](https://user-images.githubusercontent.com/20121759/92223100-ddfc6700-ee97-11ea-8a81-8e057c63aad2.jpeg)
_LTadkEYgZ38rEl3smVRKbGW2atBrMMbcJX-Kg-JjXfPGFntbQrbjc_mbeb_--ixnBu ]
I/flutter (13829): [2020-09-04 08:47:04.990214Z][Fluxstore][AppState] init mobile modules ..
I/flutter (13829): [2020-09-04 08:47:05.010263Z][Fluxstore][AppState] register modules .. DONE
W/SQLiteLog(13829): (28) double-quoted string literal: "notification"
I/luxstore.venda(13829): Background young concurrent copying GC freed 59020(3358KB) AllocSpace objects, 22(1320KB) LOS objects, 46% free, 5819KB/10MB, paused 736us total 193.373ms
I/flutter (13829): [2020-09-04 08:47:06.699370Z][Fluxstore][MyConnectivity] online
I/flutter (13829): [2020-09-04 08:47:06.755426Z][Fluxstore][App] internet issue change: {ConnectivityResult.wifi: true}
I/flutter (13829): [2020-09-04 08:47:06.797864Z][Fluxstore][MyConnectivity] online
I/flutter (13829): [2020-09-04 08:47:06.798315Z][Fluxstore][App] internet issue change: {ConnectivityResult.wifi: true}
I/flutter (13829): [2020-09-04 08:47:08.909526Z][Fluxstore][Debug] Finish Load AppConfig
I/flutter (13829): [2020-09-04 08:47:08.940503Z][Fluxstore][AppState] Init Data Finish
I/flutter (13829): [2020-09-04 08:47:08.948342Z][Fluxstore][AppState] build Theme
I/flutter (13829): [2020-09-04 08:47:09.216273Z][Fluxstore][Category] getCategories
I/flutter (13829): [2020-09-04 08:47:09.254011Z][Fluxstore][wocommerce_api][09:47:09.252858] getAsync START [endPoint:products/tags] url:https://**deleted for security**/wp-json/wc/v2/products/tags?consumer_key=**deleted for security**
I/flutter (13829): [2020-09-04 08:47:09.263820Z][Fluxstore][wocommerce_api][09:47:09.263727] getAsync START [endPoint:products/attributes] url:https://**deleted for security**/wp-json/wc/v2/products/attributes?consumer_key=**deleted for security**
E/flutter (13829): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: Exception: FormatException: Unexpected character (at character 1)
E/flutter (13829): PNG
E/flutter (13829): ^
E/flutter (13829): 
E/flutter (13829): #0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1404:5)
E/flutter (13829): #1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1271:9)
E/flutter (13829): #2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:936:22)
E/flutter (13829): #3      _parseJson (dart:convert-patch/convert_patch.dart:40:10)
E/flutter (13829): #4      JsonDecoder.convert (dart:convert/json.dart:505:36)
E/flutter (13829): #5      JsonCodec.decode (dart:convert/json.dart:156:41)
E/flutter (13829): #6      jsonDecode (dart:convert/json.dart:96:10)
E/flutter (13829): #7      Actor.load (package:flare_dart/actor.dart:134:27)
E/flutter (13829): #8      FlutterActor.loadFromByteData (package:flare_flutter/flare.dart:765:17)
E/flutter (13829): #9      _IsolateConfiguration.apply (package:flutter/src/foundation/_isolates_io.dart:83:34)
E/flutter (13829): #10     _spawn.<anonymous closure> (package:flutter/src/foundation/_isolates_io.dart:90:65)
E/flutter (13829): #11     Timeline.timeSync (dart:developer/timeline.dart:163:22)
E/flutter (13829): #12     _spawn (package:flutter/src/foundation/_isolates_io.dart:87:35)
E/flutter (13829): #13     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:304:17)
E/flutter (13829): #14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter (13829): 
I/flutter (13829): [2020-09-04 08:47:11.292286Z][Fluxstore][wocommerce_api][09:47:11.292139] getAsync END [endPoint:products/tags] url:products/tags
I/flutter (13829): [2020-09-04 08:47:11.370920Z][Fluxstore][wocommerce_api][09:47:11.370848] getAsync END [endPoint:products/attributes] url:products/attributes
I/flutter (13829): [2020-09-04 08:47:11.393740Z][Fluxstore][wocommerce_api][09:47:11.393666] getAsync START [endPoint:products/attributes/1/terms?per_page=100&page=1] url:https://**deleted for security**/wp-json/wc/v2/products/attributes/1/terms?per_page=100&page=1&consumer_key=**deleted for security**
E/flutter (13829): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: FormatException: Unexpected character (at character 1)
E/flutter (13829): <!DOCTYPE html>
E/flutter (13829): ^
E/flutter (13829): 
E/flutter (13829): #0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1404:5)
E/flutter (13829): #1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1271:9)
E/flutter (13829): #2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:936:22)
E/flutter (13829): #3      _parseJson (dart:convert-patch/convert_patch.dart:40:10)
E/flutter (13829): #4      JsonDecoder.convert (dart:convert/json.dart:505:36)
E/flutter (13829): #5      JsonCodec.decode (dart:convert/json.dart:156:41)
E/flutter (13829): #6      jsonDecode (dart:convert/json.dart:96:10)
E/flutter (13829): #7      Blog.getBlogs (package:fluxstore_vendor/models/blogs/blog.dart:86:12)
E/flutter (13829): <asynchronous suspension>
E/flutter (13829): #8      BlogModel.getBlogs (package:fluxstore_vendor/models/blogs/blog.dart:21:29)
E/flutter (13829): #9      _AppInitState.loadInitData.<anonymous closure> (package:fluxstore_vendor/app_init.dart:85:58)
E/flutter (13829): #10     new Future.delayed.<anonymous closure> (dart:async/future.dart:325:39)
E/flutter (13829): #11     _rootRun (dart:async/zone.dart:1182:47)
E/flutter (13829): #12     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (13829): #13     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (13829): #14     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (13829): #15     _rootRun (dart:async/zone.dart:1190:13)
E/flutter (13829): #16     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (13829): #17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021:23)
E/flutter (13829): #18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
E/flutter (13829): #19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)
E/flutter (13829): #20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
E/flutter (13829): #21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter (13829): 
I/flutter (13829): [2020-09-04 08:47:12.630280Z][Fluxstore][wocommerce_api][09:47:12.630124] getAsync END [endPoint:products/attributes/1/terms?per_page=100&page=1] url:products/attributes/1/terms?per_page=100&page=1
I/flutter (13829): [2020-09-04 08:47:12.634128Z][Fluxstore][wocommerce_api][09:47:12.634056] getAsync START [endPoint:products/attributes/1/terms?per_page=100&page=2] url:https://**deleted for security**/wp-json/wc/v2/products/attributes/1/terms?per_page=100&page=2&consumer_key=**deleted for security**
I/flutter (13829): [2020-09-04 08:47:13.481942Z][Fluxstore][wocommerce_api][09:47:13.481882] getAsync END [endPoint:products/attributes/1/terms?per_page=100&page=2] url:products/attributes/1/terms?per_page=100&page=2
W/System.err(13829): java.lang.InterruptedException
W/System.err(13829): 	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireInterruptibly(AbstractQueuedSynchronizer.java:1248)
W/System.err(13829): 	at java.util.concurrent.locks.ReentrantLock.lockInterruptibly(ReentrantLock.java:344)
W/System.err(13829): 	at java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:384)
W/System.err(13829): 	at com.onesignal.OneSignalSyncServiceUtils$SyncRunnable.run(OneSignalSyncServiceUtils.java:236)
W/System.err(13829): 	at java.lang.Thread.run(Thread.java:923)
E/OneSignal(13829): Error updating the user record because of the null user id
I/luxstore.venda(13829): Background concurrent copying GC freed 100356(4585KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 4692KB/9385KB, paused 747us total 167.848ms
W/System.err(13829): java.lang.InterruptedException
W/System.err(13829): 	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireInterruptibly(AbstractQueuedSynchronizer.java:1248)
W/System.err(13829): 	at java.util.concurrent.locks.ReentrantLock.lockInterruptibly(ReentrantLock.java:344)
W/System.err(13829): 	at java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:384)
W/System.err(13829): 	at com.onesignal.OneSignalSyncServiceUtils$SyncRunnable.run(OneSignalSyncServiceUtils.java:236)
W/System.err(13829): 	at java.lang.Thread.run(Thread.java:923)
E/OneSignal(13829): Error updating the user record because of the null user id
W/System.err(13829): java.lang.InterruptedException
W/System.err(13829): 	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireInterruptibly(AbstractQueuedSynchronizer.java:1248)
W/System.err(13829): 	at java.util.concurrent.locks.ReentrantLock.lockInterruptibly(ReentrantLock.java:344)
W/System.err(13829): 	at java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:384)
W/System.err(13829): 	at com.onesignal.OneSignalSyncServiceUtils$SyncRunnable.run(OneSignalSyncServiceUtils.java:236)
W/System.err(13829): 	at java.lang.Thread.run(Thread.java:923)
E/OneSignal(13829): Error updating the user record because of the null user id
W/System.err(13829): java.lang.InterruptedException
W/System.err(13829): 	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireInterruptibly(AbstractQueuedSynchronizer.java:1248)
W/System.err(13829): 	at java.util.concurrent.locks.ReentrantLock.lockInterruptibly(ReentrantLock.java:344)
W/System.err(13829): 	at java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:384)
W/System.err(13829): 	at com.onesignal.OneSignalSyncServiceUtils$SyncRunnable.run(OneSignalSyncServiceUtils.java:236)
W/System.err(13829): 	at java.lang.Thread.run(Thread.java:923)
E/OneSignal(13829): Error updating the user record because of the null user id
I/luxstore.venda(13829): Background concurrent copying GC freed 96854(4489KB) AllocSpace objects, 14(344KB) LOS objects, 49% free, 4449KB/8899KB, paused 7.527ms total 269.355ms

+ Product & version: FluxstoreMV 1.7.7
+ Flutter (or React Native) version: Current
+ Testing Device/Simulator: Pixel 3 API R
+ Screenshot issues (drag the file to attach here): 
![9DD49F05-7BF0-4D9A-A89E-1788C8490DE3](https://user-images.githubusercontent.com/20121759/92223146-ef457380-ee97-11ea-99ad-518db0144b6c.jpeg)

I hope you can help to resolve this.

Thanks

**_Step 2 (require): submit proof of purchasing the license on https://verify.inspireui.com **

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@T3kken - make sure to update to latest flutter 1.20.x and clean up the cache https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

**Comment by T3kken** [comment]
Hi there
I followed the instructions again and again.....The issue remains the same!!!
I just cant understand why! and also you guys should stop claiming how easy it is to use your codes!!!! 

Can you help solve this please.

Thanks

**Comment by minhcasi** [comment]
@T3kken - you could share your current source to inspireui.team@gmail.com - we will help to check your issue - thanks

**Comment by T3kken** [comment]
I sent you the source codes as requested.

Thanks

**Comment by minhcasi** [comment]
@tgloc96 - please help with investigating - thank you!

**Comment by T3kken** [comment]
Still not got any answers nor reply from the email I sent!!!!

Can you sort something out.

**Comment by tgloc96** [comment]
I am investigating and will get back to you soon.

**Comment by tgloc96** [comment]
I have seen the caught of the error, this comes from you are using splash screen is the image but the type of splash screen you set it is 'flare' and it is not right. And to fix the issue, you just change the type of splash screen from 'flare' to 'static'. You open file `lib/common/constants/images.dart` and at line 5, change value of `kSplashScreenType' to `static' like image below.
![image](https://user-images.githubusercontent.com/46434718/93164299-62c26d00-f743-11ea-81e6-72d19b1471cd.png)

**Comment by tgloc96** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
