### ISSUE TITLE
Fluxstore sale price and deep linking issue with woocommerce

### ISSUE THREAD

**Issue by kermalk** [inspireui/support#4874]
So we have launched our application successfully. I have some questions that I need your support in

1. We have issue with the products on sale in the home page as it show the same price for both original and after sale. (image attached)

2. Also when someone click on product link it open in the WordPress desktop version not on the mobile app. How we can force redirecting to mobile app.

Best Regards, 
Mohamed 
![Screenshot_20200904-110935](https://user-images.githubusercontent.com/62398663/92224624-1f4e4000-eeb3-11ea-8d02-e3da674ac1ec.jpg)

**Comment by minhcasi** [comment]
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support https://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by kermalk** [comment]
Dear Minh,

The form has been submited.

Thanks,
Mohamed Adel
KSA Operations Lead
 
 <https://www.zmarketers.com/>	
M: +971 54 555 2162 | +966 544485364
ma@zmarketers.com <mailto:ma@zmarketers.com> - www.zmarketers.com <http://www.zmarketers.com/>
Dubai Silicon Oasis, 09 58-500, UAE

**Comment by minhcasi** [comment]
@kermalk - could I now if you are using the latest Fluxstore `1.7.7`?

If it is possible pls share your source to inspireui.team@gmail.com - we will help to debug this issue - thank you!

**Comment by surendranekkanti188** [comment]
It is the latest version. Even we are facing same issue. Inspire UI team please fix this issue.

**Comment by minhcasi** [comment]
@surendranekkanti188 - it's working fine with our testing on the default source - could you send the project to inspireui.team@gmail.com? It could cause by user-data issue - thanks

**Comment by surendranekkanti188** [comment]
How to send full source code? Because I think it is above 1gb.

**Comment by simonpham** [comment]
> How to send full source code? Because I think it is above 1gb.

Hi @surendranekkanti188, to send the full source code, here are the steps:
1. In your project folder, run this command: `flutter clean`
2. Then archive the project folder to .ZIP file
3. Upload it to Google Drive then share the link to us via email.

Thank you!

**Comment by kermalk** [comment]
Dear @simonpham I have shared the code with you
Kindly note that the push notification is not working on the ios version as well.
It would be appreciated if you managed to fix it while you are debugging

**Comment by surendranekkanti188** [comment]
https://drive.google.com/drive/folders/1zu-SWSfFzwDHM_u2u0BX4XHvm3IEoJwe?usp=sharing

Hi i have shared my project file please check it.

**Comment by surendranekkanti188** [comment]
Ok thank you.

**Comment by ahmed-foulad20** [comment]
i face same problem with deeplink in ios not working - my app multivendor 1.7.7

**Comment by kermalk** [comment]
Hi,

Any updates on the sale discount issue, it's really important for us to fix it asap

**Comment by simonpham** [comment]
Hi @kermalk,

Could you send us your wp-admin login account to `simon@inspireui.com`?

Thank you!

**Comment by surendranekkanti188** [comment]
Still how many days we need to wait for fix? for another year?

**Comment by kermalk** [comment]
Kindly note that i have a serious bug in my app, it is the same in 
https://github.com/inspireui/support/issues/4515

Also  i have attached two videos for this issue (i have disabled the products that has the problem, but i sent you admin access so you (to simion) can activate them when you debug. 
The products model names are 1400 and 1410 and 1300

Now we have four critical issues with the app
1- the after sale pricing not showing correctly
2- the deeplinking not working on ios
3- the size issues (Most critical)
4- the push notifications not working on ios

Please tackle these issue ASAP because we are in our main sale season and the customers are taking bad impression about the app.

[Issue.zip](https://github.com/inspireui/support/files/5200203/Issue.zip)

**Comment by simonpham** [comment]
Hi @kermalk,

2- About iOS deep link, you can choose either [Universal Links](https://developer.apple.com/documentation/safariservices/supporting_associated_domains) (recommended) or [Custom URL schemes](https://developer.apple.com/documentation/xcode/allowing_apps_and_websites_to_link_to_your_content/defining_a_custom_url_scheme_for_your_app) (check **Register Your URL Scheme** section).
Note: Universal Links can work with https scheme (example: https://your-website.com), but will require to upload a file to your host.

4- For iOS push notification, you can follow our guide here.
https://youtu.be/rFCcWNRPrSk

For other issues, we are checking and will respond to you ASAP.

Thank you!

**Comment by kermalk** [comment]
Dear Simon,

Till now we didn’t manage to fix the push notifications or the deeplinking despite we spent 3 working days to try to solve them.
Also, we didn’t hear from you back on the other two issues.

Please assist us in getting these solved ASAP as we are launching big sale season this thursday.

Regards,

Mohamed Adel
KSA Operations Lead
 
 <https://www.zmarketers.com/>	
M: +971 54 555 2162 | +966 544485364
ma@zmarketers.com <mailto:ma@zmarketers.com> - www.zmarketers.com <http://www.zmarketers.com/>
Dubai Silicon Oasis, 09 58-500, UAE

**Comment by simonpham** [comment]
Hi @kermalk,

We have checked the sale price issue.
The woo-commerce API doesn't provide a regular price for on-sale products with product variations, so we have to hide the regular price in the future version of FluxStore.

You can wait for the next version or, you can hide it now by changing these below code from `lib/model/product/product.dart` as below:

<details>
<summary>Click to show</summary>
<p>

Remove this code:
```dart
      onSale = parsedJson["on_sale"];
```
Add this code:
```dart
      onSale = parsedJson["price"] != parsedJson["regular_price"] &&
          isNotBlank(parsedJson["regular_price"]) &&
          double.parse(parsedJson["regular_price"]) >
              double.parse(parsedJson["price"]);
```

The result will be like:
![image](https://user-images.githubusercontent.com/8846657/93416548-2ec88280-f8d0-11ea-8b0d-832673e3d259.png)

</p>
</details>

**Comment by kermalk** [comment]
Hi,

I need to get it fixed ASAP, today we launched our biggest sale this year (Saudi National Day Sale) and we need to get it solved now even if you need money to get it done.
I have already shared with you the code. let me know what it takes to get it fixed.

This is really critical and i would rate you 5 stars on codecanyon if you solved it ASAP.

Regards,



Mohamed Adel
KSA Operations Lead
 
 <https://www.zmarketers.com/>	
M: +971 54 555 2162 | +966 544485364
ma@zmarketers.com <mailto:ma@zmarketers.com> - www.zmarketers.com <http://www.zmarketers.com/>
Dubai Silicon Oasis, 09 58-500, UAE

**Comment by simonpham** [comment]
Hi @kermalk,

Integration issues (Deeplink, Push notifications,...) are actually not included in our support scope, please help to check out our support policies for more detail - [https://inspireui.com/support-policies](https://inspireui.com/support-policies)

Thank you!

**Comment by kermalk** [comment]
Hi Simon

Regarding the Sale price solution you shared. We tried it and it has
removed the regular price and the sale label from the products. How can I
show the sale label so customers can understand that we have sale.

Best Regards

**Comment by kermalk** [comment]
Hi @simonpham & @minhcasi ,

I am facing huge issue with the sizes of the newly added products (issue number 3- the size issues (Most critical))
i am urging you to assist in fixing this critical bug ASAP.

P.S: I have already updated the latest MStore plugin but the problem is still existed. 
Also, i have attached a fresh video for it

[RPReplay_Final1600499978.MP4.zip](https://github.com/inspireui/support/files/5249251/RPReplay_Final1600499978.MP4.zip)

Regards,
Mohamed

**Comment by simonpham** [comment]
Hi @kermalk,

For the size issue, please try the following solution:
https://github.com/inspireui/support/issues/4959#issuecomment-692557126

About the sale price issue, we will have a fix in a future version.

Thank you!

**Comment by kermalk** [comment]
Hi @simonpham 
Thanks, we will try this fix today.

What about the sale issue, have you read the below comment

**Comment by kermalk** [comment]
One more question, Our prices are showing in the app without the taxes despite that we are showing it on the website inclusive of VAT. How we can solve this and show it inclusive of taxes in the app as well?

**Comment by kermalk** [comment]
@simonpham  a gentle reminder on my previous questions

1-Regarding the Sale price solution you shared. We tried it and it has removed the regular price and the sale label from the products. How can I show the sale label so customers can understand that we have sale. Best Regards

2- Our prices are showing in the app without the taxes despite that we are showing it on the website inclusive of VAT. How we can solve this and show it inclusive of taxes in the app as well?

**Comment by simonpham** [comment]
Hi @kermalk,

For the sale price problem, we are investigating and will have an optimized solution in a future version. Thank you for your suggestion.
About the taxes, it will show the amount of taxes when the user is checking out the cart & when the user is on payment screen.

**Comment by kermalk** [comment]
Hi Simon,

Is there away to show the prices including taxes in the product page as it is mandatory by country law.

Mohamed Adel
KSA Operations Lead
 
 <https://www.zmarketers.com/>	
M: +971 54 555 2162 | +966 544485364
ma@zmarketers.com <mailto:ma@zmarketers.com> - www.zmarketers.com <http://www.zmarketers.com/>
Dubai Silicon Oasis, 09 58-500, UAE

**Comment by minhcasi** [comment]
Greetings from InspireUI 🎉
To improve user experience during support, we are announcing that a new ticket support system is available on this link https://support.inspireui.com 

Please help to move your next comment on the new support system (you could mention this ticket so that the team could know more about the ticket's history) - thank you for your time!
