### ISSUE TITLE
Caching not enable after installing Mstore API for Mstore

### ISSUE THREAD

**Issue by febinmhd** [inspireui/support#4877]
I have activated the Mstore API plugin in Wordpress but I cannot cache and change the layout nor is it showing caching enabled . please advice

![IMG_6349](https://user-images.githubusercontent.com/51330162/92257530-0dce5d80-eede-11ea-8b1e-b8101b948465.JPG)

**Comment by minhcasi** [comment]
@febinmhd - please help to move your all comment into one open ticket #4878

**Comment by febinmhd** [comment]
Hi sir, i have moved all my comment into 1 ticket   #4887

**Comment by febinmhd** [comment]
this is the url https://github.com/inspireui/support/issues/4887 please
advice. thankyou
