### ISSUE TITLE
Products duplicating when searching and error showing while making order

### ISSUE THREAD

**Issue by febinmhd** [inspireui/support#4878]
I have added 3 products in my Woocommerce a for category but hen I open it in Mstore 3 products et duplicated and it shows 6 products. please advice . also when I make the order shows the error undefined is not an object.Please advice

<img width="317" alt="Screen Shot 2020-09-04 at 7 02 23 PM" src="https://user-images.githubusercontent.com/51330162/92260832-2f7d1400-eee1-11ea-9f79-fcd0043b2436.png">
 user.billing.first_name 

<img width="317" alt="Screen Shot 2020-09-04 at 6 35 03 PM" src="https://user-images.githubusercontent.com/51330162/92258172-170bfa00-eedf-11ea-8bac-fe4c5a7f9a36.png">

![IMG_6350](https://user-images.githubusercontent.com/51330162/92258291-46226b80-eedf-11ea-85d3-b94abaefc39c.PNG)

![IMG_6351](https://user-images.githubusercontent.com/51330162/92259408-da8cce00-eedf-11ea-9b01-cbeb653f6cb4.PNG)

**Comment by febinmhd** [comment]
Any updates pleass

**Comment by luyx2412** [comment]
Hi @febinmhd Please fill the form http://verify.inspireui.com/ and upload your config. We will investigate and reply you soon.

Thanks

**Comment by febinmhd** [comment]
hi I have submitted the form . please look into it

**Comment by luyx2412** [comment]
Hi @febinmhd Please uninstall app and reinstall again. Because i just checked in my side, and everything worked normal.
![image](https://user-images.githubusercontent.com/8909619/92485978-c9acc700-f215-11ea-90d3-66ab2d8d627a.png)

Thanks

**Comment by febinmhd** [comment]
Hi there,

When we open the categories the first time its normal , but if we go back and open categories again it happens..the second time you open it reloads with duplicated products please advice
![image](https://user-images.githubusercontent.com/51330162/92526561-624f4100-f22e-11ea-9550-19cead9d3464.jpeg)![image](https://user-images.githubusercontent.com/51330162/92526587-6a0ee580-f22e-11ea-8730-615630687688.jpeg)

**Comment by febinmhd** [comment]
Is there any update??

**Comment by luyx2412** [comment]
Hi @febinmhd I just tested it, and everything worked normal. Please see the video
https://drive.google.com/file/d/1D8stGK6lCIN5IEoxVUZ7_eVe9BLXZlSN/view?usp=sharing

So can you share your project via inspireui.team@gmail.com with title `4878`. Let me investigate about that.

Thanks

**Comment by luyx2412** [comment]
Closed! Because no longer response.

P/S: Feel free to open new issue.

Thanks
