### ISSUE TITLE
Login does not work and the application is blank

### ISSUE THREAD

**Issue by miguelitolaparra** [inspireui/support#4879]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
- [ ] first issue

I cannot enter the application as a user, the application responds: invalid email or password .

2 - Written comments do not reach my WordPress panel The console returns the following: WARN postNewsContent LOG {"code": "rest_post_invalid_page_number", "data ": {" status ": 400}," message ":" The requested page number is greater than the number of available pages. "}

- [ ] second issue
Home screen remains empty

- [ ] third issue

The application does not connect with Firebase
+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

<img width="1298" alt="debug" src="https://user-images.githubusercontent.com/28591454/92264584-c6949c80-eede-11ea-9ba9-8a8272b003d5.png">
<img width="351" alt="startingScreen" src="https://user-images.githubusercontent.com/28591454/92264654-e1671100-eede-11ea-923e-92c1b34582a7.png">
<img width="1969" alt="menuItems" src="https://user-images.githubusercontent.com/28591454/92264725-fba0ef00-eede-11ea-9b5a-4081063cd219.png">
<img width="1298" alt="debug" src="https://user-images.githubusercontent.com/28591454/92264840-268b4300-eedf-11ea-9e75-161e619d5c97.png">

**_Step 2 (require): submit proof of purchasing the license on https://verify.inspireui.com **

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊
I am not sure which file I need to modify to get what is shown [in MStore .8. Banner High and Vertical Card List](https://docs.inspireui.com/mstore/home-theme/)

What files should I modify to achieve this? I just need to know what the files are

How to discover WordPress IDs to get recent news to Banner High. ?
I'm not asking for customization, but the documentation is confusing, and I can't understand.

<img width="1073" alt="BannerHighVerticalCardList" src="https://user-images.githubusercontent.com/28591454/92313022-f7e89780-efc6-11ea-80ad-6b7ca4d341d3.png">

**Comment by minhcasi** [comment]
@luyx2412 - please help to investigate this issue

**Comment by miguelitolaparra** [comment]
Hi.
Thanks for your support.
Please excuse me for opening another response. I have made a mistake, and it is that I was following the inssues number [#4652](https://github.com/inspireui/support/issues/4652), since it has something similar to mine, and therefore, I registered in this question ([#4652](https://github.com/inspireui/support/issues/4652)) to see the evolution that it took and if I could benefit from the answers that they gave in, and solve my problems.
   Being subscribed, I receive email when someone writes a comment and you closed that query (# 4652) and I, without actually reading the beginning of the topic, I thought you closed my question ([#4780](https://github.com/inspireui/support/issues/4780)).

Well, we'll continue on this one.
The rating is what the theme deserves, the application is great, the problem is mine, since I do not understand the documentation well.
I want to finish this application soon, to start a project that I have with which I will earn money

**Comment by luyx2412** [comment]
HI @miguelitolaparra Can you include all issues in one ticket. Let me support you later. And i was invited to your repo, so please clear the issues, i will fix and explain the issue. 

Thanks

**Comment by miguelitolaparra** [comment]
> HI @miguelitolaparra Can you include all issues in one ticket. Let me support you later. And i was invited to your repo, so please clear the issues, i will fix and explain the issue.
> 
> Thanks

Hi.

Excuse me, read my explanation well.
Create a new ticket by mistake. The problems are explained above.
Believe me, I have tried these days to solve, without success, so I ask for your help.
I have spent days reviewing all the ticks and questions that are here on GitHub about BeoNews and MStore in search of solutions to my problems, even in the closed ticks I show you the problems I have, and the screenshots, are already in my first comment.

1 - My screen doesn't show anything, you can see it in the screenshot above.
2 - I cannot register any user, I cannot enter the application as a user, the application responds: invalid email or password.
3 - The buttons of the menu that I show and mark with the red arrow, are inactive, you can see in the screenshots the result of the console when Debug
4 - I can't connect to Firebase, I have put my Firebase configuration in the project in Config.js
5 - Can you tell me which file I should modify to get a configuration like the one I show in section 8 of the MStore documentation. ?

I show you link and screenshot above, to get my application to display:
8. Banner High and Vertical Card List
I hope you can help me, this will be easy for you, but I can't solve it.
Thank you very much for your support and I apologize again for opening a new ticket, it was without any bad intention, I don't want to put problems in your work.
Thank you.

**Comment by miguelitolaparra** [comment]
Question number 1, you can forget it, my application already shows images.

For question number 5, I have modified the AppConfig.json file in the way that I show below, but I have taken it from another ticket(#4038) created by another MStore user and it only shows what you see below, and I want to get what you get in this section: [8. Banner High and Vertical Card List](https://docs.inspireui.com/mstore/home-theme/) , but nevertheless, it only shows what I know in the image below, and you can check that on my website, I have more entries that you can see: https://agricolaparra.com/blog/

What is the structure that I must follow in AppConfig.json to achieve this in BeoNews?

As you can see, I am trying to solve my problems myself, but it is very difficult for me, so I ask for your help.

I will keep looking for solutions and if I make more progress I will let you know.


```
{
  "URL": {
    "root": "https://agricolaparra.com"
  },
  "HorizonLayout": [
    {
      "layaut": "bannerSlider",
        "tag": 67
    },
    {
      "layout": "circleCategory"
    },
    {
      "layout": "banner",
      "category": 74
    },
    {
      "name": "featureProducts",
      "image": "",
      "layout": "twoColumn",
      "category": 71
    },
    {
      "layout": "banner"   
    }
  ],

  "VerticalLayout": {
    "name": "Recents",
    "layout": "simple",
    "category": 54
  },
  "MainColor": "#1CB5B4"
}
```


<img width="565" alt="pantallaInicio" src="https://user-images.githubusercontent.com/28591454/92416326-387a1980-f15d-11ea-9f33-c0990c5c65fa.png">

**Comment by luyx2412** [comment]
HI @miguelitolaparra Sorry about reply you very late. Can you give me the specific branch, let me see and fix the issue soon.

Thanks

**Comment by miguelitolaparra** [comment]
> the specific branch
Don't worry, I'm behind on the project, but I understand that you have a lot of work to do. I just hope you can help me, saying that I need to modify. I don't understand what you mean by t**_he specific branch_**, I don't have any projects on GitHub. If you can give me more details. Thank you.

**Comment by miguelitolaparra** [comment]
I just want to get my application to display as shown in section number 8 of [the following link:](https://docs.inspireui.com/mstore/home-theme/)
Show categories in circles at the top of the screen, 
**- Circle Category**

**- Banner High**

**- Vertical banner with Card list**

Just tell me which files to edit. Thank you @luyx2412

**Comment by luyx2412** [comment]
Hi @miguelitolaparra Please follow the config same it to show with section 8.
```
{
  "URL": {
    "root": "https://www.sviluppoapp.me"
  },
  "HorizonLayout": [
    {
      "layout": "circleCategory" 
    },
    {
      "layout": "bannerHigh",
      "tag": 273
    }
  ],

  "VerticalLayout": {
    "name": "Recents",
    "layout": "card"
  },
  "MainColor": "#1CB5B4"
}
```

Thanks

**Comment by miguelitolaparra** [comment]
Hi. Thanks for your suppor @luyx2412 

I have tested your code but the result is not the same as I need, you can see for yourself what I have achieved with that code.

<img width="528" alt="14-09-2020-homeApp" src="https://user-images.githubusercontent.com/28591454/93124261-a11b4600-f6c9-11ea-98ca-67aeeed6dfe2.png">


 
I'm starting to think that my project is not right.
I have followed the documentation, but still, I have all the errors that I show here.
Your code doesn't work.
I'll keep studying the documentation, but you should know how to do this.
I show you a screenshot of JSON Api,

<img width="1326" alt="apiJSON" src="https://user-images.githubusercontent.com/28591454/93124280-a8daea80-f6c9-11ea-9f3c-b8dee0af4507.png">




> 1 - My screen doesn't show anything, you can see it in the screenshot above.
> 2 - I cannot register any user, I cannot enter the application as a user, the application responds: invalid email or password.
> 3 - The buttons of the menu that I show and mark with the red arrow, are inactive, you can see in the screenshots the result of the console when Debug
> 4 - I can't connect to Firebase, I have put my Firebase configuration in the project in Config.js
> 5 - Can you tell me which file I should modify to get a configuration like the one I show in section 8 of the MStore documentation. ?
> 
> I show you link and screenshot above, to get my application to display:
> 8. Banner High and Vertical Card List
> I hope you can help me, this will be easy for you, but I can't solve it.
> Thank you very much for your support and I apologize again for opening a new ticket, it was without any bad intention, I don't want to put problems in your work.
> Thank you.


Since with this she cannot help me,.





Can you help me with the rest of the queries?

**Comment by luyx2412** [comment]
Hi @miguelitolaparra Sorry about the missing. The section 8 only work in Mstore project, it not support for Beonews. And i don't understand your question "Can you help me with the rest of the queries?". Can you explain it?

Thanks

**Comment by miguelitolaparra** [comment]
Hi @luyx2412 . Do not worry about being missing, in the end everything ends up appearing ...):):




> The section 8 only work in Mstore project, it not support for Beonews.


Regarding this query, please don't worry, but you can help me in another way.
I'd be happy if I can get all my website entries to display in two columns, as they were in the app, before they updated the app, remember?

I want to display all the entries of my website in TWO Columns. I show you an image capture as the application was shown before.
Using the same code in AppConfig.json, I can't get my site posts to display in two columns.
Can you tell me what code I should use to achieve this?

How do I know the ID of my login in WordPress?
Thank you, now I explain the other questions




<img width="585" alt="twoColumns" src="https://user-images.githubusercontent.com/28591454/93387293-4587be80-f869-11ea-849a-286df070cc81.png">

**Comment by miguelitolaparra** [comment]
Regarding the rest of the queries, I have the following problems, and above you can see the screenshots and below I leave a screenshot, but the console errors, you can see them in the screenshots at the top. I hope you can help me correct this and be able to upload my app to the stores soon, I must start another project.



2 - I cannot register any user, I cannot enter the application as a user, the application responds: invalid email or password.
3 - The buttons of the menu that I show and mark with the red arrow, are inactive, you can see in the screenshots the result of the console when Debug
4 - I can't connect to Firebase, I have put my Firebase configuration in the project in Config.js
5 - Written comments do not reach my WordPress panel The console returns the following: WARN postNewsContent LOG {"code": "rest_post_invalid_page_number", "data ": {" status ": 400}," message ":" The requested page number is greater than the number of available pages. "}
Thank you

<img width="1969" alt="menuItems" src="https://user-images.githubusercontent.com/28591454/93389377-600f6700-f86c-11ea-82fd-7f6c5894918e.png">

**Comment by miguelitolaparra** [comment]
Hello
I haven't heard from you for days @luyx2412 
Will you help me with my problems?
You do not know how to solve the errors that my application has, let me know to find another job and another topic, this is proving a bit frustrating.
There are many days waiting and I cannot correct the mistakes, and I am wasting a lot of time on this project.

Thank you

**Comment by minhcasi** [comment]
Greetings from InspireUI 🎉
To improve user experience during support, we are announcing that a new ticket support system is available on this link https://support.inspireui.com 

Please help to move your next comment on the new support system (you could mention this ticket so that the team could know more about the ticket's history) - thank you for your time!
