### ISSUE TITLE
[CeStore] Error on  refresh the category and product page 

### ISSUE THREAD

**Issue by aniketsiet50** [inspireui/support#488]
**Required Info (please complete the following information):**
 - Product: cestore
 - Your Purchased Code: c5be65c8-f5d3-4682-bd0f-9afa1961c377
(we may not reply if you are not our customer)

**Describe the bug**
application is run fine , but if i refresh  any category and product page  it shows {};

**Screenshots**
![error](https://user-images.githubusercontent.com/48587831/55704737-8c2d8400-59fa-11e9-8e3a-3edf01139091.png)

**Additional context**

**Comment by aniketsiet50** [comment]
have any update on the issues?

**Comment by minhcasi** [comment]
@minhtruong315 - pls help to check - thank you!

**Comment by aniketsiet50** [comment]
any update ?

**Comment by aniketsiet50** [comment]
7 day pass but i don't get any update

**Comment by minhcasi** [comment]
Hi, i'm sorry for the late response as we have some issues with the resources, could we have a quick check it is happening on the latest download package without any modification? 

We have a check from the build but could not replicate the issues, also from the demo site - http://cestore.inspireui.com

Please help to clarify

**Comment by aniketsiet50** [comment]
have you send me the file , which work on your side ?
 because i had not change anything in the file except the config file.

**Comment by minhtruong315** [comment]
Hi @aniketsiet50 
Did you check this video? https://www.youtube.com/watch?v=HF1aQzVHEPQ&t=18s
If you followed by that video, but still have issues. pls record your screen and send me.
Thanks
