### ISSUE TITLE
Currency exchange rate does not change when you switch

### ISSUE THREAD

**Issue by kibbyboi** [inspireui/support#4880]
Hello, I want to report this issue once more, I started in June asking for help but nothing has been done yet. 

Our ecommerce needs support for currency exchange in order for us to business, on the app when you switch currencies nothing happens it only changes the symbol of the currency but the exchange rate does not change too, I have done everything I could but nothing, please look into this issue because we really need it.

Our business has been down on the app since we launched on play store because people do not know the actual prices, we price everything in dollars but we want our Customers from other nations to change currencies according to the country their in.

I tried this feature on your app on playstore it shows that it too does not work, check screenshot I have sent you of your own app of Play Store
![Screenshot_2020-09-04-18-48-05-237_com inspireui fluxstore](https://user-images.githubusercontent.com/4435840/92267719-68b58400-eee1-11ea-90ce-4d28d51713c2.jpg)
![Uploading Screenshot_2020-09-04-18-47-52-519_com.inspireui.fluxstore.jpg…]()

**Comment by minhcasi** [comment]
@kibbyboi - could i know if you follow this guide to set up the currency by using WMPL plugin? https://docs.inspireui.com/fluxstore/multi-language/#currency-switcher

**Comment by kibbyboi** [comment]
Yes I did , everything.

**Comment by kibbyboi** [comment]
Even your own app on google play store doesn't work when you switch
currencies, it just changes currency symbol but the amount remains the
same.check these attachments

**Comment by minhcasi** [comment]
our demo app on google store is out-date we will update it shortly - but confirm that this issue is fixed on the latest release 1.7.7  - thank you!

**Comment by minhcasi** [comment]
@kibbyboi - please confirm if you are using the latest version - thank you!

**Comment by kibbyboi** [comment]
I am using the latest version

**Comment by minhcasi** [comment]
@kibbyboi - could you share the screenshot of this issues. Also include the common+config folder+ admin website login to inspireui.team@gmail.com - we will help to investigate the issue - thank you!

**Comment by kibbyboi** [comment]
Noted I will Soon
