### ISSUE TITLE
language issue with multivendor fluxstore app

### ISSUE THREAD

**Issue by bigjuju4fr** [inspireui/support#4881]
Hello, 
thanks for this great app. i have a question regarding the language selection. i followed your documentation for changing the default language when the apps starts.

I tried to change it in the “general.dart” file and replace the following in const kAppConfig = ‘lib/config/config_de.json’ and in const KAdvanceConfig = { “DefaultLanguage”: de,

But the App couldn’t start anymore after this change and crash. Why?
Here is the screenshot: https://tppr.me/bnuT7

But if am leaving the defaultlanguage: en, it is working again. Does it mean that the app couldn't start in other language? i want to have the app only in german. Is it possible?

Thank you for your help

**Comment by minhcasi** [comment]
@bigjuju4fr - pls follow this link to fix the splash screen issue - https://github.com/inspireui/support/issues/4638#issuecomment-675443139

**Comment by bigjuju4fr** [comment]
Hello,
thanks for your help. it is working great now.

Best regards
