### ISSUE TITLE
License

### ISSUE THREAD

**Issue by rodrigomeyer** [inspireui/support#4882]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
- [X] first issue
- [ ] second issue
- [ ] third issue

+ Product & version: MStore API 2.9.4

**_Step 2 (require): submit proof of purchasing the license on https://verify.inspireui.com **

I install for test license in http://atacados.zarsolutions.com.br:8280 but I need cancel this, because license is another website. This correct https://edtintas.zar.app.br

**Comment by minhcasi** [comment]
Please refer to "Deactivate the purchase code” part in https://docs.inspireui.com/fluxbuilder/guide-to-use/#deactivate-the-purchase-code
Please be careful because you can deactivate only One time.

**Comment by midasmkt** [comment]
Hello. The same thing happens to me. Why is Mstore api not working?

**Comment by minhcasi** [comment]
@rodrigomeyer - let us know your checking

If it does not work, pls send  your purchase code request to support@inspireui.com
