### ISSUE TITLE
TypeError on my prestashop shipping screen 

### ISSUE THREAD

**Issue by majedqatousa** [inspireui/support#4883]
**i get TypeError on my orestashop shipping screen **
#### thank you for this great app , i get this problem and my app is stop after go to shipping screen . 
+ Detail Issues: 
- [ ] first issue

![error1](https://user-images.githubusercontent.com/44095809/92291529-d681a000-ef21-11ea-86e3-f06ad0ade336.jpg)
![error2](https://user-images.githubusercontent.com/44095809/92291599-1e082c00-ef22-11ea-91f9-7c5cd1d58249.jpg)

**Comment by minhcasi** [comment]
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support https://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
@majedqatousa - could i confirm you are using the latest release 1.7.7? Thank you!

@vumanhsn97 - please help to investigate this issue

**Comment by majedqatousa** [comment]
yes i have 1.7.7 fluxStore prestashop  .

**Comment by majedqatousa** [comment]
@minhcasi yes i have 1.7.7 fluxStore prestashop .

**Comment by vumanhsn97** [comment]
@majedqatousa 
Can you send your admin account to inspireui.team@gmail.com?
Thanks!

**Comment by majedqatousa** [comment]
@vumanhsn97  Admin account for my prestashop , right ?

**Comment by majedqatousa** [comment]
@vumanhsn97  done

**Comment by vumanhsn97** [comment]
@majedqatousa 
Your issue have been fixed. Please check!

**Comment by majedqatousa** [comment]
yes , my issue have been fixed .  thank you

**Comment by majedqatousa** [comment]
@vumanhsn97  my issue have been fixed . 
but I have different names for shipping than what is in the store .

**Comment by vumanhsn97** [comment]
@majedqatousa 
Can you explain your issue? Make sure you set shipping method is free shipping https://tppr.me/Y66N0, if it have total cost = 0.0

**Comment by majedqatousa** [comment]
@vumanhsn97  No its not free shipping . 
![Capture](https://user-images.githubusercontent.com/44095809/92680824-8c8b2680-f334-11ea-9122-f587ea4f70e5.JPG)

**Comment by vumanhsn97** [comment]
@majedqatousa 
if it is not free shipping, please set cost greater than 0.0 https://tppr.me/Qa8SQ

**Comment by majedqatousa** [comment]
@vumanhsn97 thank you . 
i have another problem on payment Method . 
when i chose my payment method and tap on PLACE MY ORDER button  . 
i  get this error  > NoSuchMethodError - the getter id was called on null. 
What caused this problem  ?? 

screen :  - 

![119083879_694139297843610_5993683831446881718_n](https://user-images.githubusercontent.com/44095809/92718658-c2e39880-f36a-11ea-8583-a4e2b2f1caf6.jpg)

and i don't want to see the check payment , write payment and COD on my app .
i just want to see the : K-net and cybersource payment methods 

thank you.

**Comment by vumanhsn97** [comment]
@majedqatousa 
You need to login before place your order

**Comment by majedqatousa** [comment]
@vumanhsn97  I am already logged in and  face the same problem ! !

**Comment by majedqatousa** [comment]
@vumanhsn97  any help ?

**Comment by vumanhsn97** [comment]
@majedqatousa 
It is working well. Try to remove your app in your device and run again
Thanks!

**Comment by majedqatousa** [comment]
@vumanhsn97 
i get i new problem in the same screen !! 
the problem is (
FormatException (FormatException: Unexpected character (at character 1)
Fatal error
^
![k](https://user-images.githubusercontent.com/44095809/93087248-f858f080-f6a0-11ea-8f2a-e200f23554ad.jpg)

)

**Comment by vumanhsn97** [comment]
@majedqatousa 
Can you send your resource code to inspireui.team@gmail.com? It is working well in my resource: https://streamable.com/57dz5i

**Comment by majedqatousa** [comment]
@vumanhsn97  done ! send resource code to inspireui.team@gmail.com

**Comment by majedqatousa** [comment]
@vumanhsn97  Thank you . 
it's working now .  but i need to transfer the user to the portal's payment page, how can this be done?

**Comment by vumanhsn97** [comment]
@majedqatousa 
Prestashop just support for COD payment method
Thanks!
