### ISSUE TITLE
Shipping and payment options issue (opencart)

### ISSUE THREAD

**Issue by demonic-guru** [inspireui/support#4884]
Hello, 
We are facing issue configuring Shipping and Payment system with App. Shipping options are enabled with website but facing issue with app. 

+ Product & version: Opencart 3.0.2.0
+ Screenshot issues (drag the file to attach here): 
![IMG-20200903-WA0010](https://user-images.githubusercontent.com/40889641/92297346-0ea5d480-ef5c-11ea-8b8d-366bb7d9f543.jpg)

**Comment by demonic-guru** [comment]
![Screenshot_20200905-105500_Chrome](https://user-images.githubusercontent.com/40889641/92298429-4b76c900-ef66-11ea-98c4-473f1b6eb8ab.jpg)

**Comment by demonic-guru** [comment]
Help me to solve this issue.

**Comment by demonic-guru** [comment]
Here ia the link which we are facing issue. https://www.indbrochicken.com/index.php?route=extension/mstore/shipping_address/states&countryId=IN

**Comment by minhtruong315** [comment]
Hi @demonic-guru please reinstall mstore extension and try again
[mstore.ocmod.zip](https://github.com/inspireui/support/files/5179035/mstore.ocmod.zip)

**Comment by demonic-guru** [comment]
Ok

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
