### ISSUE TITLE
Fluxstore Woocommerce [ Version 1.7.7 ] - Order Details Page No more Showing CANCEL and REFUND Button

### ISSUE THREAD

**Issue by swspro** [inspireui/support#4886]
Hi @minhcasi 

In the Previous Versions on **[Fluxstore Woocommerce Old Version]**  there was REFUND and CANCEL Button Options were AVAILABLE in the ORDER DETAIL Page. 
### Please refer to one of the OLD VERSION APP SCREEN SHOT

![WhatsApp Image 2020-09-05 at 12 39 42](https://user-images.githubusercontent.com/15525566/92300031-44a38280-ef75-11ea-9572-531a67d8c076.jpeg)

But now in the Latest Version of **FLUXSTORE WOOCOMMERCE 1.7.7.** the REFUND and CANCEL Button Option is NOT AVAILABLE  in the ORDER DETAIL PAGE. AS a RESULT of which USERS are not able to CANCEL ORDER nor REQUEST for REFUND.

### Please refer to the SCREEN SHOT.

![WhatsApp Image 2020-09-05 at 12 39 42 (1)](https://user-images.githubusercontent.com/15525566/92300048-70266d00-ef75-11ea-9fff-793684b7e6c5.jpeg)

Please suggest what to do.

Sam

**Comment by minhcasi** [comment]
try to enable this option to `true` 

<img width="981" alt="Screen Shot 2020-09-05 at 14 28 24" src="https://user-images.githubusercontent.com/1459805/92300317-10838e00-ef84-11ea-8415-1dd9f89da81f.png">
