### ISSUE TITLE
Fluxstore Woocommerce - Multiple Variation Product Default Price Setting Issue

### ISSUE THREAD

**Issue by swspro** [inspireui/support#4888]
Hi @minhcasi 

Here is another issue which we are facing when there is Multiple Variation in a PRODUCT

### 1 ) In the APP Homepage Screen the HIGHEST PRICE is always shown , and we want to show the minimum price 

Please refer the Website Link of the Product at **https://seafoods.co.in/product/catla-bhakura/**

And now Look at the APP HOMESCREEN Pricing listing of that product under **FRESH WATER FISH** >> **" CATLA-BHAKURA**" in the SCREENSHOT which is Showing **Rs.312/- .** 

**The Minimum Price is Rs.94/-**  https://seafoods.co.in/product/catla-bhakura/

![WhatsApp Image 2020-09-05 at 12 58 43](https://user-images.githubusercontent.com/15525566/92300685-6eab7380-ef7a-11ea-9e94-cd41e87003ce.jpeg)

### 2 ) In the ADMIN PANEL we have SET THE DEFAULT VARIATION to the MINIMUM which showing FINE on the WEBSITE but in the APP PRODUCT DETAIL PAGE its showing the DIFFERENT DEFAULT VARIATION.

**Please REFER to the SCREENSHOTS of ADMIN PANEL Product VARIATION SETTING **

![Screen Shot 2020-09-05 at 1 02 10 PM](https://user-images.githubusercontent.com/15525566/92300771-33f60b00-ef7b-11ea-9011-b6d6187cb587.png)

### Please REFER to the SCREENSHOT of WEBSITE DISPLAY which is DISPLAYING CORRECT

![Screen Shot 2020-09-05 at 1 01 53 PM](https://user-images.githubusercontent.com/15525566/92300796-6e5fa800-ef7b-11ea-956e-0bbd365a4e5b.png)

### Please REFER to the SCREENSHOT of the APP Same PRODUCT DETAIL PAGE which is DISPLAYING RANDOMLY or the HIGHEST PRICE VARIATION

![WhatsApp Image 2020-09-05 at 12 58 31](https://user-images.githubusercontent.com/15525566/92300822-a1a23700-ef7b-11ea-8d6d-3eb138d93fe5.jpeg)

Please suggest what to do.

Sam

**Comment by minhcasi** [comment]
Hi Sam, pls help to post your all comment into one open ticket #4841
