### ISSUE TITLE
Issue mentioned in #4616 still persists, not resolved

### ISSUE THREAD

**Issue by krdvijay** [inspireui/support#4889]
Regarding Internet Conncetivity
@minhcasi- Hi This issue is not resolved. giving errors on updating with new files provided
@minhtruong315- Hi, the code provided is giving another compilation error.

{
"resource": "/XXXX/FluxStore-woo-1.7.7/source/lib/services/index.dart",
"owner": "dart",
"code": {
"value": "undefined_identifier",
"target": {
"$mid": 1,
"external": "https://dart.dev/tools/diagnostic-messages#undefined_identifier",
"path": "/tools/diagnostic-messages",
"scheme": "https",
"authority": "dart.dev",
"fragment": "undefined_identifier"
}
},
"severity": 8,
"message": "Undefined name 'MyConnectivity'.\nTry correcting the name to one that is defined, or defining the name.",
"source": "dart",
"startLineNumber": 530,
"startColumn": 14,
"endLineNumber": 530,
"endColumn": 28,
"tags": []
}

**Comment by krdvijay** [comment]
Above error was appearing due to missing import in new file, got it fixed by myself. I will check the application for internet connectivity errors

**Comment by minhcasi** [comment]
@krdvijay - thank you for the quick response - let us know if you have any question
