### ISSUE TITLE
[MStore] Issue with index

### ISSUE THREAD

**Issue by DaviDawn** [inspireui/support#489]
**Mandatory Info (please complete the following information):**
 - Product: MStore
 - Your Purchased Code: ff572917-25b2-4bd6-809c-125bf5b11d60

**Describe the issues**
Hello everyone,

I've been trying to use MStore Pro with my Wordpress page, but anything goes the way I want.

I've install everything that needs and for now the App opens with my genymotion virtual device, but instantly it shows an error.

Does it have to be the MStore in the same server that is wordpress? Does it need MStore folder the Wordpress page with the all information? Needs the index? What should I do?

Do I need to create and index file? If I have to create it, which content does it need? I haven't found anything in the documentation, I've been using this -> https://docs.mstore.io/

I've reinstall even the operanting system, I'm using W10.

**Screenshots**

![errorIndex1](https://user-images.githubusercontent.com/38453878/55721604-0adaef00-5a04-11e9-9d72-5aebcb277d45.PNG)

![errorIndex2](https://user-images.githubusercontent.com/38453878/55726728-cbff6600-5a10-11e9-8208-4dc92cb8f323.PNG)

**Additional context**
Add any other detail logs about the problem here.

**Comment by luyx2412** [comment]
HI @DaviDawn Please use cebuilder to install MStore easier. https://docs.mstore.io/cebuilder-installing

Thanks

**Comment by DaviDawn** [comment]
I'm using too, but I have the same problem with CeBuilder ( ver 0.31.0 ) and by commands, always get the same error. Should I move an index.js or something into the folders scripts?

**Comment by DaviDawn** [comment]
@luyx2412 This IP -> 

![errorIndex3](https://user-images.githubusercontent.com/38453878/55792806-b72edb00-5ac1-11e9-8742-ff0babaf7665.PNG)

Isn't my server, where is the file that called it, can I change it? Can you give me the file the path of the file? 

Thank you.

**Comment by luyx2412** [comment]
Hi @DaviDawn Please follow the comment to fix the issue https://stackoverflow.com/a/52114667/6622971

Thanks

**Comment by DaviDawn** [comment]
It doesn't change the port, in the android emulator keeps running into the same port.

**Comment by luyx2412** [comment]
Hi @DaviDawn You do not need change port, still using the default port. But please check again your emulator with `adb devices` and run this script `adb reverse tcp:8081 tcp:8081 && react-native run-android` to when reinstall app. And make sure you closed all terminal or bundle running.

Thanks

**Comment by DaviDawn** [comment]
Hi @luyx2412 keep with the same problem.

**Comment by luyx2412** [comment]
Hi @DaviDawn Can you try this comment to fix the issue https://stackoverflow.com/a/45737998/6622971. I think the problem related window environment.

Thanks

**Comment by DaviDawn** [comment]
Hi @luyx2412 I've used the command that is on stackoverflow but got an error.

![errorIndex4](https://user-images.githubusercontent.com/38453878/56020078-94413880-5d06-11e9-8b13-d5d832928319.PNG)

**Comment by luyx2412** [comment]
Hi @DaviDawn You can follow the comment to fix the issue https://github.com/inspireui/support/issues/501

Thanks
