### ISSUE TITLE
template 7 multivendor is not available in multivendor fluxbuilder

### ISSUE THREAD

**Issue by nomicool** [inspireui/support#4891]
I tried fluxbuilder while creating template ID 7 in multivendor template is not available I need some customization in it but simple woocomerce this template is available how to get this.

**Comment by minhcasi** [comment]
@nomicool - you could copy the Json template from the woocommerce and copy to the JSON data https://tppr.me/hAwf7 to import for the vendor app.

Remind: pls help to post your all comments into one open ticket #4811
