### ISSUE TITLE
reset password option

### ISSUE THREAD

**Issue by alokmalewar** [inspireui/support#4892]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
- [ ] first issue
- [ ] second issue
- [ ] third issue

+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on https://verify.inspireui.com **

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@alokmalewar - as the comment from the config, you could use native screen if keep the URL blank (only support for Woocommerce API)

<img width="970" alt="Screen Shot 2020-09-06 at 09 53 20" src="https://user-images.githubusercontent.com/1459805/92317092-dddea180-f026-11ea-8a72-d75a9dec7b5c.png">

**Comment by minhcasi** [comment]
Let us know if you have any question - thank you!

**Comment by alokmalewar** [comment]
ok i am checking

**Comment by alokmalewar** [comment]
It is showing error like this
![WhatsApp Image 2020-09-07 at 12 44 58 PM](https://user-images.githubusercontent.com/69632534/92359072-40f43500-f108-11ea-8943-c4f0048d33bf.jpeg)

**Comment by alokmalewar** [comment]
How to change the color of the AppBar
![appbar](https://user-images.githubusercontent.com/69632534/92375772-35603880-f11f-11ea-8703-9f354ecb83e2.png)
