### ISSUE TITLE
How to avoid change product quantity from the cart 

### ISSUE THREAD

**Issue by bigjuju4fr** [inspireui/support#4893]
Hello,

i have some issues when ordering products from the apps. And i want to ask if it is possible to avoid changing product quantity in the last step before payment.
Please see the following screenshot:

![image](https://user-images.githubusercontent.com/69798792/92306083-ed111100-ef8c-11ea-871b-8abee17ec65f.png)

Is it possible to hide the field in the red circle?
Thanks

Best regards

**Comment by minhcasi** [comment]
@bigjuju4fr - you could customize any UI from the app by using the Inspector Tool - https://docs.inspireui.com/fluxstore/customization/#1-how-to-customize-any-ui-from-app - thank you!

**Comment by minhcasi** [comment]
Let us know if you have any question - thank you!

**Comment by bigjuju4fr** [comment]
Hello,

thank you for your reply. But i still need your help. I couldn't find how to avoid the change via the dropdown.
What i want to do is simple, i just want to avoid users to click on the dropdown arrow and change the quantity at this stage. Only the quantity should show. The only possibility to change the product quantity should be in the cart.
How to do that please?
Thank you again for the great app.

Best regards

**Comment by bigjuju4fr** [comment]
@minhcasi please re-open this issue. it's not resolve yet. Thank you.
