### ISSUE TITLE
Author name is not displaying on blog posts (FluxNews)

### ISSUE THREAD

**Issue by RomeoDar** [inspireui/support#4895]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
- [ i'm not able to fetch author name on blogs, kindly fix this bug. it's displaying null instead of author name ] 

+ Product & version: Fluxnews
+ Flutter (or React Native) version: 1.4.1 
+ Testing Device/Simulator: both
+ Screenshot issues (drag the file to attach here): 

![error](https://user-images.githubusercontent.com/52714884/92308578-0d09fa00-efb8-11ea-80f7-5d73b00c0fde.PNG)

**Comment by RomeoDar** [comment]
submit proof of purchasing the license on https://verify.inspireui.com ** (DONE)

**Comment by RomeoDar** [comment]
Project is send to hi@inspireui.com & support@inspireui.com with subject "Project for ticket #4895" kindly fix this issue

**Comment by minhcasi** [comment]
@dttrung26 - please help to investigate the issue

**Comment by RomeoDar** [comment]
@minhcasi  @dttrung26  plis response still waiting

**Comment by dttrung26** [comment]
Hi @RomeoDar , 
author name has been disabled for FluxNews in some previous versions. You must haven't update FluxNews with the latest version yet. However, we would fix this in FluxNews next patch. Thank you for reporting us about this issue. 
Have a nice day!

**Comment by dttrung26** [comment]
Fixed in next patch FluxNews.

**Comment by RomeoDar** [comment]
@dttrung26  did you mean its fixed ? can i've access to path ? or when will you released it ? @minhcasi
