### ISSUE TITLE
FLUTTER APP DOESNT WORK EVEN WITHOUT ANY CHANGES

### ISSUE THREAD

**Issue by rufw91** [inspireui/support#4898]
so i got the flutter template ish. How tf does it not work out of the box. I didnt even change jack. What racket are you playing here boys.

**Comment by minhcasi** [comment]
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support https://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!
