### ISSUE TITLE
some edits

### ISSUE THREAD

**Issue by ahmedseddiq-casheto** [inspireui/support#4899]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
- [ ] i want to edit product single page layout i search all docs but i don't know how like if i want to call something to appear on product single page
- [ ] i want to make reviews for product to be only for the one who buy the product or at least to make each customer just make one review on the product not unlimited like in the app
- [ ]i want to remove stores from category tab 
+ Product & version:fluxstore multivendor 1.77
+ Flutter (or React Native) version: flutter 1.2
+ Testing Device/Simulator: oppo a31/pixel 3
![POINTS](https://user-images.githubusercontent.com/66135124/92319309-d1eae380-f016-11ea-90a0-ac93f75af082.jpg)
![Screenshot_2020-09-04-18-09-20-23](https://user-images.githubusercontent.com/66135124/92319310-d31c1080-f016-11ea-8c63-60542a9d9290.jpg)

+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on https://verify.inspireui.com **

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@ahmedseddiq-casheto - pls try your best to customize the app UI by using the Inspector Tool - https://docs.inspireui.com/fluxstore/customization/

**Comment by ahmedseddiq-casheto** [comment]
@minhcasi and what about that {i want to make reviews for product to be only for the one who buy the product or at least to make each customer just make one review on the product not unlimited like in the app}

**Comment by ahmedseddiq-casheto** [comment]
@minhcasi i want to change category tab layout and remove stores and MAP sign as shown in attachment
![Screenshot_2020-09-04-18-09-20-23](https://user-images.githubusercontent.com/66135124/92329370-4d748100-f067-11ea-99d2-89a9554cc335.jpg)

**Comment by minhcasi** [comment]
@ahmedseddiq-casheto - the `limit reviews for only purchased product` is not available - but we will add this feature to our backlog for further investigation.

The category screen could be customize as your request by updating this file
<img width="1209" alt="Screen Shot 2020-09-07 at 09 25 23" src="https://user-images.githubusercontent.com/1459805/92342771-11373400-f0ec-11ea-8ff8-5a752e1d4fe2.png">

**Comment by ahmedseddiq-casheto** [comment]
@minhcasi  thnx so much for your answer and hope review updating next version , im not so good with programming can you tell me wt will be the code be like if i want to remove that containeer and just when i click on categories tab the only thing to be appear is categories without that above box please help me with that 


List<Category> categories = value.categories;

          return SafeArea(
            child: ['grid', 'column', 'sideMenu', 'subCategories']
                    .contains(widget.layout)
                ? Column(
                    children: <Widget>[
                      Expanded(
                        child: _isSelectedCategoriesTab
                            ? renderCategories(categories)
                            : StoreScreen(),
                      )
                    ],
                  )
                : !_isSelectedCategoriesTab
                    ? StoreScreen()
                    : ListView(
                        children: <Widget>[renderCategories(categories)],
                      ),
          );
        }),
      ),
    );
  }

**Comment by seventhsonmizo** [comment]
Follow

**Comment by minhcasi** [comment]
you could try this script

```
return SafeArea(
            child: ['grid', 'column', 'sideMenu', 'subCategories']
                    .contains(widget.layout)
                ? Column(
                    children: <Widget>[
                      Expanded(
                        child: renderCategories(categories),
                      )
                    ],
                  )
                :  ListView(
                        children: <Widget>[renderCategories(categories)],
                      ),
          );
```

**Comment by minhcasi** [comment]
Also remove this appBar - https://tppr.me/URyJx

**Comment by ahmedseddiq-casheto** [comment]
> Also remove this appBar - https://tppr.me/URyJx
> 
> > <img alt="" height="14" src="/favicon-32x32.png"> tppr.me**[Public](https://tppr.me/URyJx)**

i dont get that?

**Comment by ahmedseddiq-casheto** [comment]
> @minhcasi thnx so much for your answer and hope review updating next version , im not so good with programming can you tell me wt will be the code be like if i want to remove that containeer and just when i click on categories tab the only thing to be appear is categories without that above box please help me with that
> 
> List categories = value.categories;
> 
> ```
>       return SafeArea(
>         child: ['grid', 'column', 'sideMenu', 'subCategories']
>                 .contains(widget.layout)
>             ? Column(
>                 children: <Widget>[
>                   Expanded(
>                     child: _isSelectedCategoriesTab
>                         ? renderCategories(categories)
>                         : StoreScreen(),
>                   )
>                 ],
>               )
>             : !_isSelectedCategoriesTab
>                 ? StoreScreen()
>                 : ListView(
>                     children: <Widget>[renderCategories(categories)],
>                   ),
>       );
>     }),
>   ),
> );
> ```
> 
> }

thanks so much

**Comment by ahmedseddiq-casheto** [comment]
i got it thanks

**Comment by minhcasi** [comment]
We're glad that it help, please give us some feedback/rating to this page https://codecanyon.net/downloads  if the product is helpful for your business, we are working hard to update more awesome and powerful features on next coming version release. Let us know if you have any feedback. Thank you very much 😊

**Comment by ahmedseddiq-casheto** [comment]
i try th solution to hide appbar and categories list
and that code but there are problem missing libraries n i did wt u told me

import 'package:flutter/animation.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

import '../../vendor/store/store_screen.dart';
import '../../common/constants.dart';
import '../../generated/l10n.dart';
import '../../models/app.dart';
import '../../models/category/category.dart';
import '../../models/category/category_model.dart';
import '../../widgets/cardlist/index.dart';
import '../custom/smartchat.dart';
import 'card.dart';
import 'column.dart';
import 'grid_category.dart';
import 'side_menu.dart';
import 'sub.dart';

class CategoriesScreen extends StatefulWidget {
  final String layout;
  final List<dynamic> categories;
  final List<dynamic> images;
  final bool showChat;

  CategoriesScreen(
      {Key key, this.layout, this.categories, this.images, this.showChat})
      : super(key: key);

  @override
  State<StatefulWidget> createState() {
    return CategoriesScreenState();
  }
}

class CategoriesScreenState extends State<CategoriesScreen>
    with AutomaticKeepAliveClientMixin, SingleTickerProviderStateMixin {
  @override
  bool get wantKeepAlive => true;

  final FocusNode _focus = FocusNode();
  String searchText;
  var textController = TextEditingController();

  Animation<double> animation;
  AnimationController controller;
  bool _isSelectedCategoriesTab = false;

  @override
  void initState() {
    super.initState();
    controller = AnimationController(
        duration: const Duration(milliseconds: 300), vsync: this);
    animation = Tween<double>(begin: 0, end: 60).animate(controller);
    animation.addListener(() {
      setState(() {});
    });

    _focus.addListener(_onFocusChange);
  }

  void _onFocusChange() {
    if (_focus.hasFocus && animation.value == 0) {
      controller.forward();
    }
  }

  @override
  Widget build(BuildContext context) {
    super.build(context);

    final category = Provider.of<CategoryModel>(context);
    final bool showChat = widget.showChat ?? false;

    return Scaffold(
      appBar: PreferredSize(
        preferredSize: const Size.fromHeight(kToolbarHeight + 8),
      ),
      backgroundColor: Theme.of(context).backgroundColor,
      floatingActionButton: showChat
          ? SmartChat(
              margin: EdgeInsets.only(
                right:
                    Provider.of<AppModel>(context, listen: false).locale == 'ar'
                        ? 30.0
                        : 0.0,
              ),
            )
          : Container(),
      body: ListenableProvider.value(
        value: category,
        child: Consumer<CategoryModel>(builder: (context, value, child) {
          if (value.isLoading) {
            return kLoadingWidget(context);
          }

          if (value.categories == null) {
            return Container(
              width: double.infinity,
              height: double.infinity,
              alignment: Alignment.center,
              child: Text(S.of(context).dataEmpty),
            );
          }

          List<Category> categories = value.categories;

          return SafeArea(
             child: ['grid', 'column', 'sideMenu', 'subCategories']
                    .contains(widget.layout)
                ? Column(
                    children: <Widget>[
                      Expanded(
                        child: renderCategories(categories),
                      )
                    ],
                  )
                :  ListView(
                        children: <Widget>[renderCategories(categories)],
                      ),
          );
        }),
      ),
    );
  }

  Widget renderCategories(value) {
    switch (widget.layout) {
      case 'card':
        return CardCategories(value);
      case 'column':
        return ColumnCategories(value);
      case 'subCategories':
        return SubCategories(value);
      case 'sideMenu':
        return SideMenuCategories(value);
      case 'animation':
        return HorizonMenu(value);
      case 'grid':
        return GridCategory(
          value,
          icons: widget.images,
        );
      default:
        return HorizonMenu(value);
    }
  }

  @override
  void dispose() {
    controller.dispose();
    _focus.dispose();
    super.dispose();
  }
}
