### ISSUE TITLE
[Beonews Pro] Could not install the app on the device, startup failed

### ISSUE THREAD

**Issue by alexisttt** [inspireui/support#49]
[Beonews Pro]
Purchased Code: [3f684ec6-0043-4a19-b150-764a9f735121]

Hi. I have been trying to setup Beonews Pro. I followed the guide and done everything according to it. After i do run command react-native run-android. I got an error. Screenshot of error is bellow. Waiting for your help thanks 

**Screenshots**
![screenshot from 2018-11-26 14-10-51](https://user-images.githubusercontent.com/45356673/49081288-6f688f00-f257-11e8-96fb-7cb67ee3e0ce.png)

**Comment by alexisttt** [comment]
Yes. It is Ubuntu 16.04.5 LTS 64-bit

**Comment by luyx2412** [comment]
Hi @alexisttt Can you open Android studio to run your project which help fixing some issue import library. Thanks

**Comment by alexisttt** [comment]
Hi. I opened and ran the project in the Android Studio but nothing changed. I'm adding the screenshot bellow. 
Thanks again.

![screenshot from 2018-11-28 11-16-58](https://user-images.githubusercontent.com/45356673/49138204-a5f9e480-f2ff-11e8-892b-da45afbdc6ed.png)

**Comment by luyx2412** [comment]
Hi @alexisttt I think your problem look like https://stackoverflow.com/a/47236906/6622971 or https://github.com/invertase/react-native-firebase/issues/1107#issuecomment-391220255. It is wrong version which you need install in your OS. Thanks

**Comment by alexisttt** [comment]
Hi firstly thanks for your help intentions. But those things you suggested didn't work. But i solved the problem. 
I first deleted everything about beonews. Then purge and reinstall OpenJdk. Then extracted beonews from source again. Reinstall Node. With this steps i solved the problem. But then i got a new problem. [Exactly same problem of this. ](https://github.com/inspireui/support/issues/36) After i complete his instructions. App started to work. 
Thanks again.
