### ISSUE TITLE
[CeStore] profile and account page on website

### ISSUE THREAD

**Issue by deepakjain29** [inspireui/support#490]
**Required Info (please complete the following information):**
 - Product: [CeStore]
- Purchased Code: [4509e66c-d8d4-4aa7-ba43-18ca32aaa067]

**Describe the bug**
I have three queries
1. After logging in , we are not getting Account page and  profile of the customer.
2. customer cant check My orders or order history 
3. How to change the database URL ( Node API ) in Mobile APP 

**Additional context**
There is no file in our code with config.js specifically for APP

Please help
regards
Deepak

**Comment by deepakjain29** [comment]
Hi please help with the below query

How to change the database URL ( Node API ) in Mobile APP

Additional context
There is no file in our code with config.js specifically for APP

Please help
regards
Deepak

**Comment by minhtruong315** [comment]
Hi @deepakjain29 
Pls check this https://github.com/inspireui/support/issues/495 to change the database url.
Account page, profile page and my orders page are available in mobile app now. They are working well.  Can you take me screenshot?
