### ISSUE TITLE
Login/Registration not working in FluxStore mobile app

### ISSUE THREAD

**Issue by parimalpanchal90** [inspireui/support#4901]
Hello Team,

Following apis of mstore not working.
Getting this error. 
Error : Only authenticated user can access the rest api.

MStore Apis : 
1. Sign up
Example : url/wp-json/flutter_user/sign_up/?insecure=cool
2. Sign in
3. Facebook login
4. Google login
5. Sms login

I installed Wordpress, and WooCommerce inside. I made some changes with url, consumer key and consumer secret in config.js. Now, I can see the products but register and login part are broken.

Whole things are setup properly as inspireui documentation.

Here I attached the screenshot for Error.

![df50f9e5-dbaf-46fe-b05e-101164cc3615](https://user-images.githubusercontent.com/62424661/92321030-1fca1080-f044-11ea-9836-59b6b52a562e.jpg)

Thanks in advance.

**Comment by minhcasi** [comment]
@parimalpanchal90 - could you help to check if you have activated the License from mstore-api plugin - thank you

**Comment by parimalpanchal90** [comment]
@minhcasi I already filled form on [](http://verify.inspireui.com/). You can check on it.

**Comment by minhcasi** [comment]
@parimalpanchal90 - sorry i mean active the mstore-api plugin from your Wordpres site, by select the Mstore API plugin menu

**Comment by parimalpanchal90** [comment]
Yes @minhcasi , It's active.
You can verify through attached image.

![20200908_151101](https://user-images.githubusercontent.com/62424661/92460471-a2d69c80-f1e5-11ea-9a25-c2d0f9f6d808.jpg)

**Comment by minhcasi** [comment]
@parimalpanchal90 - pls confirm if you are using latest mstore-api - 2.9.4 ?

**Comment by parimalpanchal90** [comment]
Yes @minhcasi, it's latest version 2.9.4. You can verify through attached image.
![20200909_111619](https://user-images.githubusercontent.com/62424661/92559551-6e6aeb00-f28e-11ea-8d4e-2f96aea88a77.jpg)

**Comment by minhcasi** [comment]
@parimalpanchal90 - could you try to disable the some plugin from `json api` and `json api auth` as it could conflict with the mstore-api - thank you!

**Comment by parimalpanchal90** [comment]
Sure @minhcasi, I will check after to disable json api and json api auth plugins and let you know.

**Comment by parimalpanchal90** [comment]
Thanks @minhcasi, its working now.
I uninstalled mstore api plugin and again install it.
Also disable json api and json api auth plugins.

**Comment by parimalpanchal90** [comment]
Hello @minhcasi ,
Please help me about below things. 
I want to implement following functionalities in FluxStore app. 

1. I want to add City, Company name and Phone number fields in manual **registration** page.
2. I want to send **whatsapp message** to user for order details.

Thanks in advance

**Comment by jabirishaq** [comment]
hi, i have problem in sms verification and google login

applied following
1. debug key added in firebase console
2. signing key is also added in console
3. enabled both methods in authentication

error says not authorized to use firebase, invalid sha key, package name doesnot match.

please help me, i have lost a week solving this issue thanks

**Comment by minhcasi** [comment]
@parimalpanchal90 - please feel free to customize or add any feature that you love to have it on your app, this request is related to the customize that is not cover from our support scope

**Comment by minhcasi** [comment]
@jabirishaq - pls create a new ticket for you have purchased the product - thank you!

**Comment by parimalpanchal90** [comment]
> @parimalpanchal90 - please feel free to customize or add any feature that you love to have it on your app, this request is related to the customize that is not cover from our support scope

Okay @minhcasi , 
I will try to implement above things by other way.
Once again Thank you for your support and time. 👍

**Comment by parimalpanchal90** [comment]
Hello @minhcasi ,
In Fluxstore app, on reset password it will redirect to browser. 

I do not want to redirect browser.
I want reset password functionality in application without redirect on browser.

Please suggest me.
Thank you in advance
