### ISSUE TITLE
After Payment Successfull not Redirect to Payment page 

### ISSUE THREAD

**Issue by mrizwanmmc** [inspireui/support#4902]
hi,

After booking successfully app not redirect to the payment page any solution for this?
I am using Listeo - Directory & Listings With Booking Theme

Thank you :)

**Comment by minhcasi** [comment]
@mrizwanmmc - could you shave some screenshot or video issues to that we could understand more on your issues, pls share your website URL as well - thank you!

**Comment by mrizwanmmc** [comment]
![sc](https://user-images.githubusercontent.com/10098991/92369731-cda3f080-f112-11ea-9728-7b9dfae13779.jpg)

This is my website https://bmax.ca/

please see attached ... when someone book service successfully. the page needs to go on the payment page. where customers can pay service fees... hope you understand. Thank you

**Comment by minhcasi** [comment]
@mrizwanmmc - i got your point, the current release of Fluxlisting is not supported for Payment so that you could not use it - please try to customize this feature base on your requirement- thank you!
