### ISSUE TITLE
FLUXSTORE PRO - App not working on latest flutter installations

### ISSUE THREAD

**Issue by ItisAhsan** [inspireui/support#4904]
Details: 
Because every version of flutter_test from sdk depends on vector_math 2.1.0-nullsafety.2 and fstore depends on vector_math 2.0.8, flutter_test from sdk is forbidden.
So, because fstore depends on flutter_test any from sdk, version solving failed.
---- Log transcript ----
FINE: Pub 2.10.0-73.0.dev
MSG : Resolving dependencies...
SLVR: fact: fstore is 1.7.7+3001
SLVR: derived: fstore
SLVR: fact: fstore depends on inspireui from path
SLVR: fact: fstore depends on flutter any from sdk
SLVR: fact: fstore depends on http 0.12.2
SLVR: fact: fstore depends on html_unescape 1.0.1+3
SLVR: fact: fstore depends on provider 4.3.2
SLVR: fact: fstore depends on after_layout 1.0.7+2
SLVR: fact: fstore depends on font_awesome_flutter 8.8.1
SLVR: fact: fstore depends on vector_math 2.0.8
SLVR: fact: fstore depends on carousel_pro 1.0.0
SLVR: fact: fstore depends on flutter_widget_from_html 0.4.3
SLVR: fact: fstore depends on configurable_expansion_tile 1.0.0
SLVR: fact: fstore depends on timeago 2.0.26
SLVR: fact: fstore depends on share 0.6.4+3
SLVR: fact: fstore depends on validate 1.7.0
SLVR: fact: fstore depends on country_pickers 1.3.0
SLVR: fact: fstore depends on shared_preferences 0.5.8
SLVR: fact: fstore depends on firebase_messaging 6.0.16
SLVR: fact: fstore depends on firebase_analytics 5.0.16
SLVR: fact: fstore depends on transparent_image 1.0.0
SLVR: fact: fstore depends on pull_to_refresh 1.6.1
SLVR: fact: fstore depends on localstorage 3.0.2+5
SLVR: fact: fstore depends on notification_permissions 0.4.7
SLVR: fact: fstore depends on flare_splash_screen 3.0.1
SLVR: fact: fstore depends on rate_my_app 0.7.0
SLVR: fact: fstore depends on page_indicator 0.3.0
SLVR: fact: fstore depends on intro_slider 2.3.1
SLVR: fact: fstore depends on url_launcher 5.5.0
SLVR: fact: fstore depends on extended_image 1.1.0
SLVR: fact: fstore depends on firebase_core 0.4.5
SLVR: fact: fstore depends on firebase_auth 0.16.1
SLVR: fact: fstore depends on flutter_webview_plugin 0.3.11
SLVR: fact: fstore depends on connectivity 0.4.9
SLVR: fact: fstore depends on random_string 2.1.0
SLVR: fact: fstore depends on google_maps_flutter 0.5.30
SLVR: fact: fstore depends on cached_network_image 2.2.0+1
SLVR: fact: fstore depends on uuid 2.2.0
SLVR: fact: fstore depends on uni_links 0.4.0
SLVR: fact: fstore depends on flutter_staggered_grid_view 0.3.2
SLVR: fact: fstore depends on auto_size_text 2.1.0
SLVR: fact: fstore depends on flutter_swiper 1.1.6
SLVR: fact: fstore depends on flutter_widgets 0.1.12
SLVR: fact: fstore depends on video_player 0.10.11+2
SLVR: fact: fstore depends on flutter_spinkit 4.1.2+1
SLVR: fact: fstore depends on percent_indicator 2.1.5
SLVR: fact: fstore depends on animated_text_kit 2.2.0
SLVR: fact: fstore depends on wave 0.0.8
SLVR: fact: fstore depends on http_auth 0.3.0
SLVR: fact: fstore depends on firebase_admob 0.9.3+4
SLVR: fact: fstore depends on facebook_audience_network 0.7.0
SLVR: fact: fstore depends on pin_code_fields 4.0.0
SLVR: fact: fstore depends on flutter_facebook_login 3.0.0
SLVR: fact: fstore depends on webview_flutter 0.3.22+1
SLVR: fact: fstore depends on rubber 0.4.0
SLVR: fact: fstore depends on flutter_localizations any from sdk
SLVR: fact: fstore depends on custom_splash 0.0.2
SLVR: fact: fstore depends on apple_sign_in 0.1.0
SLVR: fact: fstore depends on google_sign_in 4.5.1
SLVR: fact: fstore depends on google_fonts 1.1.0
SLVR: fact: fstore depends on flutter_statusbarcolor 0.2.3
SLVR: fact: fstore depends on app_settings 4.0.2
SLVR: fact: fstore depends on animated_splash 1.0.0
SLVR: fact: fstore depends on firebase_database 3.1.6
SLVR: fact: fstore depends on event_bus 1.1.1
SLVR: fact: fstore depends on country_code_picker 1.4.0
SLVR: fact: fstore depends on flash 1.3.1
SLVR: fact: fstore depends on location 3.0.2
SLVR: fact: fstore depends on liquid_swipe 1.5.0
SLVR: fact: fstore depends on sticky_headers 0.1.8+1
SLVR: fact: fstore depends on onesignal_flutter 2.6.0
SLVR: fact: fstore depends on zoom_widget 0.1.3
SLVR: fact: fstore depends on awesome_card 1.1.0
SLVR: fact: fstore depends on flutter_html 1.0.2
SLVR: fact: fstore depends on universal_platform ^0.1.3
SLVR: fact: fstore depends on flutter_test any from sdk
SLVR: fact: fstore depends on flutter_launcher_icons 0.7.5
SLVR: fact: fstore depends on pedantic 1.8.0+1
SLVR: fact: fstore depends on mockito ^4.1.1
SLVR: fact: fstore depends on flutter_svg 0.18.0
SLVR:   selecting fstore
SLVR:   derived: flutter_svg 0.18.0
SLVR:   derived: mockito ^4.1.1
SLVR:   derived: pedantic 1.8.0+1
SLVR:   derived: flutter_launcher_icons 0.7.5
SLVR:   derived: flutter_test any from sdk
SLVR:   derived: universal_platform ^0.1.3
SLVR:   derived: flutter_html 1.0.2
SLVR:   derived: awesome_card 1.1.0
SLVR:   derived: zoom_widget 0.1.3
SLVR:   derived: onesignal_flutter 2.6.0
SLVR:   derived: sticky_headers 0.1.8+1
SLVR:   derived: liquid_swipe 1.5.0
SLVR:   derived: location 3.0.2
SLVR:   derived: flash 1.3.1
SLVR:   derived: country_code_picker 1.4.0
SLVR:   derived: event_bus 1.1.1
SLVR:   derived: firebase_database 3.1.6
SLVR:   derived: animated_splash 1.0.0
SLVR:   derived: app_settings 4.0.2
SLVR:   derived: flutter_statusbarcolor 0.2.3
SLVR:   derived: google_fonts 1.1.0
SLVR:   derived: google_sign_in 4.5.1
SLVR:   derived: apple_sign_in 0.1.0
SLVR:   derived: custom_splash 0.0.2
SLVR:   derived: flutter_localizations any from sdk
SLVR:   derived: rubber 0.4.0
SLVR:   derived: webview_flutter 0.3.22+1
SLVR:   derived: flutter_facebook_login 3.0.0
SLVR:   derived: pin_code_fields 4.0.0
SLVR:   derived: facebook_audience_network 0.7.0
SLVR:   derived: firebase_admob 0.9.3+4
SLVR:   derived: http_auth 0.3.0
SLVR:   derived: wave 0.0.8
SLVR:   derived: animated_text_kit 2.2.0
SLVR:   derived: percent_indicator 2.1.5
SLVR:   derived: flutter_spinkit 4.1.2+1
SLVR:   derived: video_player 0.10.11+2
SLVR:   derived: flutter_widgets 0.1.12
SLVR:   derived: flutter_swiper 1.1.6
SLVR:   derived: auto_size_text 2.1.0
SLVR:   derived: flutter_staggered_grid_view 0.3.2
SLVR:   derived: uni_links 0.4.0
SLVR:   derived: uuid 2.2.0
SLVR:   derived: cached_network_image 2.2.0+1
SLVR:   derived: google_maps_flutter 0.5.30
SLVR:   derived: random_string 2.1.0
SLVR:   derived: connectivity 0.4.9
SLVR:   derived: flutter_webview_plugin 0.3.11
SLVR:   derived: firebase_auth 0.16.1
SLVR:   derived: firebase_core 0.4.5
SLVR:   derived: extended_image 1.1.0
SLVR:   derived: url_launcher 5.5.0
SLVR:   derived: intro_slider 2.3.1
SLVR:   derived: page_indicator 0.3.0
SLVR:   derived: rate_my_app 0.7.0
SLVR:   derived: flare_splash_screen 3.0.1
SLVR:   derived: notification_permissions 0.4.7
SLVR:   derived: localstorage 3.0.2+5
SLVR:   derived: pull_to_refresh 1.6.1
SLVR:   derived: transparent_image 1.0.0
SLVR:   derived: firebase_analytics 5.0.16
SLVR:   derived: firebase_messaging 6.0.16
SLVR:   derived: shared_preferences 0.5.8
SLVR:   derived: country_pickers 1.3.0
SLVR:   derived: validate 1.7.0
SLVR:   derived: share 0.6.4+3
SLVR:   derived: timeago 2.0.26
SLVR:   derived: configurable_expansion_tile 1.0.0
SLVR:   derived: flutter_widget_from_html 0.4.3
SLVR:   derived: carousel_pro 1.0.0
SLVR:   derived: vector_math 2.0.8
SLVR:   derived: font_awesome_flutter 8.8.1
SLVR:   derived: after_layout 1.0.7+2
SLVR:   derived: provider 4.3.2
SLVR:   derived: html_unescape 1.0.1+3
SLVR:   derived: http 0.12.2
SLVR:   derived: flutter any from sdk
SLVR:   derived: inspireui from path
IO  : Get versions from https://pub.dartlang.org/api/packages/rate_my_app.
IO  : Get versions from https://pub.dartlang.org/api/packages/google_maps_flutter.
IO  : HTTP GET https://pub.dartlang.org/api/packages/rate_my_app
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: macos
    | X-Pub-Command: get
    | X-Pub-Session-ID: 44181ABB-2BC2-4DD4-A1EC-4B8791854BD1
    | X-Pub-Environment: flutter_bot:flutter_cli:get
    | X-Pub-Reason: direct
    | user-agent: Dart pub 2.10.0-73.0.dev
IO  : HTTP GET https://pub.dartlang.org/api/packages/google_maps_flutter
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: macos
    | X-Pub-Command: get
    | X-Pub-Session-ID: 44181ABB-2BC2-4DD4-A1EC-4B8791854BD1
    | X-Pub-Environment: flutter_bot:flutter_cli:get
    | X-Pub-Reason: direct
    | user-agent: Dart pub 2.10.0-73.0.dev
IO  : HTTP response 200 OK for GET https://pub.dartlang.org/api/packages/google_maps_flutter
    | took 0:00:00.916082
    | transfer-encoding: chunked
    | date: Wed, 02 Sep 2020 14:36:03 GMT
    | content-encoding: gzip
    | vary: Accept-Encoding
    | strict-transport-security: max-age=31536000; preload
    | via: 1.1 google
    | content-type: application/json; charset="utf-8"
    | x-frame-options: SAMEORIGIN
    | x-xss-protection: 1; mode=block
    | x-content-type-options: nosniff
    | server: dart:io with Shelf
IO  : Get versions from https://pub.dartlang.org/api/packages/flutter_plugin_android_lifecycle.
IO  : Get versions from https://pub.dartlang.org/api/packages/google_maps_flutter_platform_interface.
IO  : HTTP GET https://pub.dartlang.org/api/packages/flutter_plugin_android_lifecycle
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: macos
    | X-Pub-Command: get
    | X-Pub-Session-ID: 44181ABB-2BC2-4DD4-A1EC-4B8791854BD1
    | X-Pub-Environment: flutter_bot:flutter_cli:get
    | X-Pub-Reason: direct
    | user-agent: Dart pub 2.10.0-73.0.dev
IO  : HTTP GET https://pub.dartlang.org/api/packages/google_maps_flutter_platform_interface
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: macos
    | X-Pub-Command: get
    | X-Pub-Session-ID: 44181ABB-2BC2-4DD4-A1EC-4B8791854BD1
    | X-Pub-Environment: flutter_bot:flutter_cli:get
    | X-Pub-Reason: direct
    | user-agent: Dart pub 2.10.0-73.0.dev
IO  : HTTP response 200 OK for GET https://pub.dartlang.org/api/packages/rate_my_app
    | took 0:00:01.010667
    | transfer-encoding: chunked
    | date: Wed, 02 Sep 2020 14:36:03 GMT
    | content-encoding: gzip
    | vary: Accept-Encoding

**Comment by minhcasi** [comment]
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support https://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
@ItisAhsan - pls make sure to use the flutter stable version by running
```
flutter stable channel
flutter upgrade --force
```

**Comment by minhcasi** [comment]
Let us know your checking - thank you!
