### ISSUE TITLE
FluxStore license Mstore API - can't activate

### ISSUE THREAD

**Issue by codeho** [inspireui/support#4906]
I have removed the license from one url, but now i can't add it to a new url.
It still says 'your code is being used by "Old Site url"

But on the "Old site" config it shows no activation.

i have activated it in the mstore api plugin on the new site in wordpress.

(both, Old site, and new site are part of a multisite wordpress installation)

https://www.dropbox.com/s/b0vyy4xfmb3f4bl/Screenshot%202020-09-06%20at%2017.21.51.png?dl=0

https://www.dropbox.com/s/b0vyy4xfmb3f4bl/Screenshot%202020-09-06%20at%2017.21.51.png?dl=0

**Comment by minhcasi** [comment]
@codeho - sorry the plugin is only compatible with the single site activation if could not use for the multisite integration. 

You could try this solution from Fluxbuilder to reset the key - https://docs.inspireui.com/fluxbuilder/guide-to-use/#deactivate-the-purchase-code -

**Comment by codeho** [comment]
@minhcasi - thanks for the quick reply. i did use that solution to reset the key, and it looks like it did reset it, as i could add it to the sub-site in the wordpress plugin. 
But i can't seem to add it to the fluxbuilder config like you see in those screenshots.
Is there a way you could reset my purchase code somehow completely so i can start from scratch and see if that works?

**Comment by minhcasi** [comment]
@codeho - you could try to use the Fluxbuilder to reset the code - https://docs.inspireui.com/fluxbuilder/guide-to-use/#deactivate-the-purchase-code - or send a request to support@inspireui.com - thank you!

**Comment by minhcasi** [comment]
Let us know your checking - thank you!

**Comment by codeho** [comment]
will do. i'm checking. currently in talks with support.

**Comment by minhcasi** [comment]
moved the ticket to the email conversation. 

If you have any issues with the technical, feel free to re-open the ticket here - thank you!
