### ISSUE TITLE
It can not be installed MStored v4.0

### ISSUE THREAD

**Issue by Lopmar016** [inspireui/support#4908]
Detail Issues:  
* files of MStore
![arch](https://user-images.githubusercontent.com/70861539/92334810-4ea1b000-f05f-11ea-9a8f-8a98c7c5ac8e.PNG)

* Error executing "npm install" command, in MSTORE PRO
![Captura](https://user-images.githubusercontent.com/70861539/92334713-9aa02500-f05e-11ea-91f5-de90c50b94fa.PNG)

Product & version: MStored v4.0
Flutter (or React Native) version:  React Native
Testing Device/Simulator:Visual code, Android estudio

**Comment by minhcasi** [comment]
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support https://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by luyx2412** [comment]
Hi @Lopmar016 Please make sure your node version is 10.x.x. And please use yarn https://yarnpkg.com/ to install library instance of npm.

Thanks

**Comment by luyx2412** [comment]
Closed! Because no longer response.

P/S: Feel free to open new issue.

Thanks

**Comment by Lopmar016** [comment]
already install node version 10, now the error is presented in the emulator

![phone2](https://user-images.githubusercontent.com/70861539/93532071-445c9d00-f90e-11ea-9adc-af2543cc49cb.PNG)

*Product & version: MStore v4.0
*Flutter (or React Native) version: React Native
*Testing Device/Simulator: Genymotion
