### ISSUE TITLE
Vendor products / App products not showing.

### ISSUE THREAD

**Issue by sph1n0** [inspireui/support#4910]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
- [x] first issue
- [ ] second issue
- [ ] third issue

+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on https://verify.inspireui.com **

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by sph1n0** [comment]
I have an issue with your app i have tried but unfortunately I don’t have time to verify all your source code to find the problem, like the title says all my platform products does not show, everything else in working correctly except this bug.. flux builder scan not showing any errors flutter also .. I have tried to install the plugin that helps wp api and followed the instructions but it does not solve the problem..

**Comment by minhcasi** [comment]
@sph1n0 - could you help to share the screenshot so that i could understand more about the issues - thank you!

**Comment by sph1n0** [comment]
Here are the screenshots : 

**Home Page**

![SC1](https://user-images.githubusercontent.com/70876749/92395987-a2ada280-f0fa-11ea-9400-b11360eaf191.JPG)

**Store Product no showing**

![SC2](https://user-images.githubusercontent.com/70876749/92396052-bfe27100-f0fa-11ea-8345-aead7a57b9f5.JPG)

**Product count in categories are showing.**

![SC3](https://user-images.githubusercontent.com/70876749/92396112-d688c800-f0fa-11ea-9fb7-858bd16bd4af.JPG)

**But when you click**

![SC4](https://user-images.githubusercontent.com/70876749/92396166-f15b3c80-f0fa-11ea-8410-d9e920d94b2d.JPG)

**Comment by sph1n0** [comment]
> @minhcasi - Any update for this problem?
Thank you

**Comment by sph1n0** [comment]
@minhcasi -  I found the reason why the products doesn't show it's because of my website i'm currently using Redux when disabled everything works fine.. is there any quick hack to overcome this problem because my website relies on redux functions. thank you

**Comment by minhcasi** [comment]
@sph1n0 - do you mean the Redux Wordpress plugin? Could you share the root cause why enable the Redux cause image issue not loading? it's new with my understanding - thank you!

**Comment by sph1n0** [comment]
@minhcasi Yes redux wordpress I’m also confused why it will cause this problem because it has nothing to do with your app operations, i did further debuging and i found the issue is coming from another plugin that i use combined with redux it causes this problem its woocommerce my account well this plugin allows you to customize woocommerce my account page very fast. Now the products are showing but product images are very slow to load up I don’t why even if I regenerated the images ... thank you

**Comment by minhcasi** [comment]
@sph1n0 - you could try to use this tool to track the network response time - https://flutter.dev/docs/development/tools/devtools/network

if the response time is slow, try to config the hosting server or using CDN to support faster loading time.

**Comment by sph1n0** [comment]
@minhcasi - Well thank you for this tips well i will close the ticket because the problem is resolved thank you.
