### ISSUE TITLE
Firebase version solving failed

### ISSUE THREAD

**Issue by Numan11** [inspireui/support#4912]
![error](https://user-images.githubusercontent.com/30391994/92358329-c674e680-f102-11ea-8e81-c08b87f9b3d9.PNG)
Because firebase_admob 0.9.3+4 depends on firebase_core ^0.4.2+1 and no versions of firebase_admob match >0.9.3+4 <0.10.0, firebase_admob ^0.9.3+4 requires firebase_core ^0.4.2+1.
So, because fstore depends on both firebase_core ^0.5.0 and firebase_admob ^0.9.3+4, version solving failed.
pub get failed (1; So, because fstore depends on both firebase_core ^0.5.0 and firebase_admob ^0.9.3+4, version solving failed.)

i try everything but not solved so i'm not able to make apk file..

**Comment by minhcasi** [comment]
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support https://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by Numan11** [comment]
[ +117 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +61 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 216dee60c0cc9449f0b29bcf922974d612263e24
[        ] executing: [C:\src\flutter/] git tag --contains HEAD
[ +215 ms] Exit code 0 from: git tag --contains HEAD
[        ] 1.20.3
[  +10 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +38 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\src\flutter/] git ls-remote --get-url origin
[  +33 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +86 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref HEAD



please also check this when i try to run on physical device it's show me that error
[  +40 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +49 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +30 ms] executing: C:\Users\Numan\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +40 ms] List of devices attached
           0558325063000146       device product:X690B-GL model:Infinix_X690B device:Infinix-X690B transport_id:5
[   +6 ms] C:\Users\Numan\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0558325063000146 shell getprop
[  +73 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +75 ms] Using C:\src\flutter\.pub-cache for the pub cache.
[   +1 ms] executing: [E:\Breakout App\codecanyon-9VCMm2eP-fluxstore-shopify-the-best-flutter-ecommerce-app\fluxstore-shopify 1.7.7\source/] C:\src\flutter\bin\cache\dart-sdk\bin\pub.bat --verbosity=warning get --no-precompile
[+2183 ms] "flutter run" took 2,429ms.
[ +258 ms] ensureAnalyticsSent: 253ms
[   +3 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1

**Comment by Numan11** [comment]
i fill the form please check it

**Comment by Numan11** [comment]
plzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz help me

**Comment by minhcasi** [comment]
@Numan11 - could i know if you are using the latest Flutter Stable version? Please try to run 
```
flutter channel stable
flutter upgrade --force
```

Also follow some solution on this link https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

Make sure not upgrade the pubspec verison library that could cause the issue

**Comment by Numan11** [comment]
Flutter SDK not found. Define location with flutter.sdk in the local.properties file.  

above all errors if fix the issue and yes i not update public library ...... but this recent error give me problem 

and i used latest version of flutter with android 4.1

**Comment by Numan11** [comment]
![image](https://user-images.githubusercontent.com/30391994/92459570-4e7cee00-f1e0-11ea-91e7-8641aa9cdd76.png)

check this flutter sdk in local properties but i get error sdk not found in local properties

**Comment by minhcasi** [comment]
Let us know your checking sir

**Comment by Numan11** [comment]
@minhcasi  Thanks for your time i run your command know problem is solved .......... and please don't call me sir you are my teacher i'm not ... Almost 85% i reskin app but i face problem in regarding sale label in app  check this in  my website i put 50% off label 
but in app they show 49%   
![image](https://user-images.githubusercontent.com/30391994/92638561-e28baa00-f2f3-11ea-9121-cd3639a71981.png)

but in mobile app they show 49%  ...............  why this?

**Comment by minhcasi** [comment]
It could because your wesite is calculated base on ceiling percent? try this function https://api.flutter.dev/flutter/dart-core/double/ceil.html - on this file

<img width="982" alt="Screen Shot 2020-09-10 at 09 54 31" src="https://user-images.githubusercontent.com/1459805/92676393-a126e900-f34b-11ea-816b-a39dd0da8ccb.png">

**Comment by Numan11** [comment]
Hi ok i'll apply this method but tell me what you add and fix in  9 september release ... Their is also one big issue regarding check out page .... Method id was null when i click on check out page ......

**Comment by minhcasi** [comment]
new release 1.7.8 is not available on the release, we will upload it on next week

**Comment by Numan11** [comment]
but please give me a solution of check out page

**Comment by Numan11** [comment]
very humble request you please give me valid solution of this i added my app design on flux builder but when i import data in config file app only banner images when i click on other tabs they show no data also issue on cart page when i click on checkout they null error and sorry to say i have no more to wait for new release 
have a great day.

**Comment by Numan11** [comment]
i'm using shopify please send solution according to shopify not woo commerce sir ......  i can't find product_bottom view code

**Comment by Numan11** [comment]
![image](https://user-images.githubusercontent.com/30391994/92967966-9d05e300-f493-11ea-9cd8-2693ecab7d9c.png) 
this one ok or not ?

**Comment by Numan11** [comment]
![image](https://user-images.githubusercontent.com/30391994/92975993-f1fd2580-f4a2-11ea-99b4-c0e7eb78b314.png)
 this is not work

**Comment by minhcasi** [comment]
@Numan11 - are you sure the web is calculated correctly? Try with to replace `salePrice / regularPrice`

**Comment by Numan11** [comment]
web is 100% calculated correctly

**Comment by Numan11** [comment]
@minhcasi  please please give me actual solution i also stuck on check out page ........... but first i need to solve this bug

**Comment by Numan11** [comment]
can i send you my code please i want to solve  as soon as possible

**Comment by Numan11** [comment]
? But on checkout page it's still show 49%..............
Please tell me solution

**Comment by Numan11** [comment]
hello ?

**Comment by Numan11** [comment]
i'm also face 2 other errors 
google sign in 
![image](https://user-images.githubusercontent.com/30391994/93053589-74dbd700-f681-11ea-8dd7-a94693fba34c.png)

the second one on checkout page 
![image](https://user-images.githubusercontent.com/30391994/93053656-9341d280-f681-11ea-9b73-d425f9a94474.png)

**Comment by Numan11** [comment]
app speed is so slow.......

**Comment by minhcasi** [comment]
@Numan11 -
The social login is not supported on Fluxstore shopify app. As you know your technical question will not support with our support scope (https://inspireui.com/support-policies/) but we have tried out best to respond to you.

Btw, it's possible to process refund if you are not happy with our product.

**Comment by minhcasi** [comment]
@Numan11 - thank you for considering update the rating, I'm forward the ticket to the technical team for investigating and update you shortly

**Comment by Numan11** [comment]
@minhcasi  thanks to make priority tickets and i'm planning to 20 more regular license of flux store wordpress or shopify  and i also i know the support criteria i also sell items on envato market my app is complete ready for publish just to solve these two errors   1 (the getter id was null when i click on check out ) 2  ( on checkout page they show 49% )       and app speed ...

**Comment by Numan11** [comment]
@minhcasi finally i increase the app speed and it's doing perfect loading know 2 errors remain :)

**Comment by minhcasi** [comment]
@luyx2412 - please help with supporting on this high priority ticket   🥇

**Comment by luyx2412** [comment]
Hi @Numan11 Please fill the form http://verify.inspireui.com/ and upload your config, common folder. And please make sure your payment config like the screenshot.
![image](https://user-images.githubusercontent.com/8909619/93097439-c57a2100-f6cf-11ea-8dab-6f47738776f7.png)

Thanks

**Comment by Numan11** [comment]
@luyx2412 Thanks for your reply i already apply    (true) in page checkout ......... i submit the form please check

**Comment by luyx2412** [comment]
HI @Numan11 I just invited you to the latest repo Fluxshopify, please merge with your current code to fix the issue.

Thanks

**Comment by Numan11** [comment]
@luyx2412 i update all code files that you update but result same both errors are not solve i upload a video for you please check this video .... 

https://drive.google.com/file/d/1A5hiNOmD6h2mMBl97eZzf6xwHXD7YwEr/view?usp=sharing

**Comment by Numan11** [comment]
![image](https://user-images.githubusercontent.com/30391994/93121913-0f1e3800-f6df-11ea-9558-40d78e1e9202.png)
this my website checkout page look at this ............  i have a question i want to display SKU in image you can see and match with in app SKU option is not visible

**Comment by Numan11** [comment]
@luyx2412 please check this and also watch video and i share the link

**Comment by Numan11** [comment]
@luyx2412  
![image](https://user-images.githubusercontent.com/30391994/93179633-60fea680-f74f-11ea-9727-9c2bf394cfe2.png)

i find this code hope so problem 'll solve related to checkout ............ but i can't find the solution of above comment that i mention you

**Comment by Numan11** [comment]
@minhcasi no update

**Comment by Numan11** [comment]
humble request to both you please solve this error seriously i'm in stress ............................. i hope you 'll solve this two bugs 
please i request you

**Comment by Numan11** [comment]
@luyx2412 at least reply me sir

**Comment by minhcasi** [comment]
@Numan11 - we will get back you today - thanks

@luyx2412

**Comment by Numan11** [comment]
@minhcasi i'm still wait

**Comment by luyx2412** [comment]
HI @Numan11 Please send lib folder via inspireui.team@gmail.com. Let me investigate about the issue.

Thanks

**Comment by Numan11** [comment]
@luyx2412  please check email i send it ......... please solve my issue every time team send me different link fill this form again fill form i'm tired i'm also a human man please honestly solve this issue please please please please please........

**Comment by Numan11** [comment]
@luyx2412  any update ?

**Comment by Numan11** [comment]
please response

**Comment by minhcasi** [comment]
Hi @Numan11 - why did you close the ticket? We did not get your update our the source sending to verify your issue?

**Comment by Numan11** [comment]
@minhcasi  thanks for your reply hope so you are fine my issue is not solve why i close because you mention me on previous tickets github support is not available and send your support website link  and i create ticket on that website https://support.inspireui.com/help-center/tickets/37  i read your policy according realted to tickets so that's why i close this one 
@luyx2412 this member not help me on this issue if you have any other person please refer my case to that person ....................................... and i'm sorry about bad reviews because i have no choice  don't worry just for the attention i make because none of your team member reply me ........ just said again and fill form fill form fill form this is not a professional way to behave your customer ............... hope so today my issue 'll solve ..........  have a great day. i'm waiting your response

**Comment by Numan11** [comment]
i'm already in add gitlab but now someone remove from that project ....... :D 

![image](https://user-images.githubusercontent.com/30391994/93576651-8e985980-f9b4-11ea-9865-68c7c7a7029a.png)

**Comment by Numan11** [comment]
@minhcasi @luyx2412  sorry for everything i just solve my issue on checkout finally everything in app doing perfect job .....

one bug remain  
![image](https://user-images.githubusercontent.com/30391994/93664993-6aa84700-fa8c-11ea-8ab2-ba21c4ae0f60.png)

![image](https://user-images.githubusercontent.com/30391994/93665013-988d8b80-fa8c-11ea-8e12-e893bc359e35.png)

I APPLY ceil() method  but result is still same it's possible to hide label in app if not what solution of this 

again sorry for everything i'll buy 30 more license flux shopify store <3

**Comment by luyx2412** [comment]
Hi @Numan11 Thanks for your patient, can you move to the https://support.inspireui.com/. We will discuss about the issue easier. And i will close this issue.

Thanks

**Comment by Numan11** [comment]
@minhcasi @luyx2412  sorry to say re open this i solve the the issue on product card_views.dart       but when i click on the product details it's again show 49% as you know this is not good for  my customers i find the line of code on ('${(100 - double.parse(item.price) ~/ double.parse(item.regularPrice.toString()) * 100.5).toInt()} %',) i try every logic and delete this part of code not show red sale label but it's again show ...........

**Comment by Numan11** [comment]
@luyx2412  why you not response from last 4 days i'm wait even my problem not solve  and you close this ticket ............ 

please tell me pleaseeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee to much wait man
