### ISSUE TITLE
[FluxstoreMV] devices not compatible

### ISSUE THREAD

**Issue by 007asom** [inspireui/support#4914]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
- [ ] first issue
after upload it to google play, some devices not compatible. I can run the app from PC, but cannot download it from google play.

+ Product & version:
FluxstoreMV 1.7.6 it is same with 1.7.7
+ Flutter (or React Native) version: 
[√] Flutter (Channel stable, v1.17.5, on Microsoft
+ Testing Device/Simulator: 
[√] Android toolchain - develop for Android devices
    (Android SDK version 29.0.2)
[√] Android Studio (version 4.0)
flutter devices
1 connected device:

ANE LX1 • xxxxxxxxxxxxxxxxxxxx • android-arm64 • Android 9
(API 28)
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on https://verify.inspireui.com **

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@007asom - could i know if you are using this method to upload the app?

<img width="1188" alt="Screen Shot 2020-09-07 at 19 36 11" src="https://user-images.githubusercontent.com/1459805/92388387-65b8ce80-f141-11ea-912e-22aad22e18f9.png">


Please help to share your google play store so that we could help to test on our side

**Comment by 007asom** [comment]
I did the same steps in your docs " https://docs.inspireui.com/fluxstore/delivery-android/ " 
I build it with flutter build apk --split-per-abi
I got 3 files then upload it to google play.

about sharing google play store. Did you mean the app link?
https://play.google.com/store/apps/details?id=com.ezzemedia.pubgsouq.vendor

**Comment by minhtruong315** [comment]
@007asom you only need to run this command: flutter build apk

**Comment by 007asom** [comment]
> @007asom you only need to run this command: flutter build apk

thank you sir
