### ISSUE TITLE
It is showing error like this for reset password and How to change the color of the AppBar

### ISSUE THREAD

**Issue by alokmalewar** [inspireui/support#4915]
![WhatsApp Image 2020-09-07 at 12 44 58 PM](https://user-images.githubusercontent.com/69632534/92385375-6ba5b400-f12f-11ea-9568-56166fe1d57e.jpeg)
![appbar](https://user-images.githubusercontent.com/69632534/92385386-7102fe80-f12f-11ea-9fa3-a3808aca10ae.png)

**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
- [ ] first issue
- [ ] second issue
- [ ] third issue

+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on https://verify.inspireui.com **

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by alokmalewar** [comment]
new version of fluxbuilder  (1.07 and 1.08) are not properly working during taking image from the website it is just loading and not showing anything

**Comment by minhcasi** [comment]
@alokmalewar - the native forgot password may not work completely for some website, you could try to use the `forgetPassword` URL, example: "http://demo.mstore.io/wp-login.php?action=lostpassword"

Pls try to run the Troubleshooting from Fluxbuilder to see if it display any issue?

**Comment by alokmalewar** [comment]
and what about the appbar image color

**Comment by alokmalewar** [comment]
and why native password is not running for my website what is the issue

**Comment by minhcasi** [comment]
@alokmalewar - could i know if you have changed this color from Appbar of the setting screen?

<img width="1098" alt="Screen Shot 2020-09-09 at 11 19 54" src="https://user-images.githubusercontent.com/1459805/92553924-6448ec80-f28e-11ea-959a-d3c22fe5d52f.png">

We use this URL to reset password - https://tppr.me/zRVlE - it may fail on your site

**Comment by alokmalewar** [comment]
yes i changed it but it only changed the color of the text (settings) not the appbar

**Comment by minhcasi** [comment]
scroll up to change the app bar color

<img width="1047" alt="Screen Shot 2020-09-10 at 09 58 27" src="https://user-images.githubusercontent.com/1459805/92676623-2e6a3d80-f34c-11ea-961d-390469439a29.png">

**Comment by minhcasi** [comment]
Let us know if you have any questions - thank you!
