### ISSUE TITLE
FluxStore PRO: Show Cart & Wishlist Buttons in Horizontal Layout

### ISSUE THREAD

**Issue by IbrahimHd** [inspireui/support#4916]
FluxStore PRO 1.7.7

Hi,
I'm wondering why "cart" and "wishlist" buttons are not displayed in Horizontal Layout (twoColumn & Pinterest).  However, this really needed for better user experience and convenience.
Could you pls guide me how this can be done?

Thanks in advance.

**Comment by minhcasi** [comment]
you could customize by adding this config for cart `showCart: true` and `showHeart: true` for wishlist

<img width="1210" alt="Screen Shot 2020-09-08 at 15 47 23" src="https://user-images.githubusercontent.com/1459805/92454327-986ad180-f1ea-11ea-9f97-9e615171b602.png">

**Comment by dttrung26** [comment]
Hi @IbrahimHd , 
currently, we do not support for customizing services. However, if you in need of those designs, please take a look at [Flutter Inspector ](https://flutter.dev/docs/development/tools/devtools/inspector) to determine the location of widgets. Then, playing around with `/lib/widgets/product/heart_buton"` to customize add-to-wishlist icon, and `addToCart` function at `/lib/widgets/frameworks/product_variant_mixin.dart` to implement your own add to cart button.
Hope this helps.

**Comment by IbrahimHd** [comment]
Thank you @minhcasi for your support.

Unfortunately it doesn't work.
On the other hand, I'm trying to solve the issue of OVERFLOWED PIXELS, it still doesn't work even after applying: `height: height ?? width * 1.2,`.
My approch is to use `pinterest` layout but I need to show the cart (when inStock) and the wishlist icon.

Thanks in advance.

**Comment by minhcasi** [comment]
we have noted as new features request and add this option to the json config on the next release `1.7.8` - thank you!

**Comment by IbrahimHd** [comment]
Thank you @minhcasi for scheduling this for the next release.
In addition, hope you can find a solid solution for the OVERFLOWED PIXELS issue.
