### ISSUE TITLE
implementing UPI payments

### ISSUE THREAD

**Issue by destek-harshadapatil** [inspireui/support#4917]
Hello Team,
I am facing issues in payment gateway integration. I want to integrate UPI payment in multi-vendor application. It is working from back-end but payment does not processed in application. When we place any order from application it shows order placed but payment is on hold.
Please help me what should I do to integrate UPI payments.

_Originally posted by @destek-harshadapatil in https://github.com/inspireui/support/issues/4690#issuecomment-688302361_

**Comment by minhcasi** [comment]
@destek-harshadapatil - is this payment display on the Webview on your app?

**Comment by destek-harshadapatil** [comment]
Yes, The UPI payment method is showing in the application I will attache a screenshot of application for this.Where the UPI payment method displays but when we continue with it payment shows on hold. No deduction of  payment from account.
We have used Quick UPI plugin from backend for this feature. If other that this plugin can help please suggest so that the payment problem gets solved.

Thank You!
![Screenshot_20200908-145545](https://user-images.githubusercontent.com/62869560/92458826-8c2f4600-f1e3-11ea-9d6c-6904aa0a3711.jpg)
![Screenshot_20200908-145504](https://user-images.githubusercontent.com/62869560/92458830-8df90980-f1e3-11ea-9e9f-6b7d81eedb60.jpg)

**Comment by destek-harshadapatil** [comment]
And the 2nd major issue I am facing is location searching. I have done all the steps for google cloud platform and the location in map is also showing correctly but when I try to search it shows the google api key is incorrect. 
In attached screenshot you can see the google map location is correct but when I search it shows error.
What else I required to solve this?
Thank you!
![Screenshot_20200908-130209](https://user-images.githubusercontent.com/62869560/92459289-1f687b80-f1e4-11ea-8a08-d01c5d8b1ee2.jpg)

**Comment by minhcasi** [comment]
@destek-harshadapatil - you google map api key is not valid - pls try to create the new one https://cloud.google.com/maps-platform/.

**Comment by minhcasi** [comment]
You could also refer to this lib https://pub.dev/packages/google_maps_flutter

**Comment by destek-harshadapatil** [comment]
Ok I will refer the google map document.
But what should I do for UPI payment method ??

**Comment by destek-harshadapatil** [comment]
Ok I will refer the google map document. Thank You!
But what should I do for UPI payment method ??

**Comment by minhcasi** [comment]
you may try to use the Webview payment or use some plugin like https://pub.dev/packages/upi_pay
