### ISSUE TITLE
''Linker command failed with exit code...'' Error

### ISSUE THREAD

**Issue by ornekali** [inspireui/support#4918]
Hi, friends, I started to get this error when I said Product/Archive on xcode, can I ask you to help?
![IMG_7260](https://user-images.githubusercontent.com/69655669/92405140-aadb0180-f13d-11ea-83e1-7e6480124518.JPG)
![IMG_7261](https://user-images.githubusercontent.com/69655669/92405130-a6aee400-f13d-11ea-9fe7-2145e72c35c1.JPG)

**Comment by minhcasi** [comment]
@ornekali

- try to compare your `pubspec.yaml` and `Podfile` file is the same with the latest release Fluxstore 1.7.7
- also, try to run this follow some solutions on this link https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

**Comment by ornekali** [comment]
> @ornekali
> 
> * try to compare your `pubspec.yaml` and `Podfile` file is the same with the latest release Fluxstore 1.7.7
> * also, try to run this follow some solutions on this link https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/0aeb324a3445c618a67c0140da8216d28af304fa/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f696d616765732f6d6f64756c65732f67697374732f676973742d6f672d696d6167652e706e67"><img alt="" height="14" src="https://camo.githubusercontent.com/040b5519c6d1891329f5f6d3e511003657131cf2/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> Gist**[These are common issues on Flutter and solutions to fix](https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1)**These are common issues on Flutter and solutions to fix - Flutter Clean.md

Now he's made this mistake.

![IMG_7281](https://user-images.githubusercontent.com/69655669/92490305-87758c80-f1f9-11ea-94e3-b5bfd2a55901.JPG)

**Comment by ornekali** [comment]
Now he's made this mistake.

![IMG_7282](https://user-images.githubusercontent.com/69655669/92500463-d9241400-f205-11ea-86fe-5d2303c3a324.JPG)

**Comment by ornekali** [comment]
@minhcasi 
i e-mailed the work file, can you help me, if possible?

**Comment by minhcasi** [comment]
we will have a check and let you know - thanks

**Comment by ornekali** [comment]
> we will have a check and let you know - thanks

thank you very much, I look forward to your good news @minhcasi

**Comment by minhcasi** [comment]
@ornekali - i could not search your user `ornekali ` or title `4918` related to this ticket, what is your email address?

**Comment by ornekali** [comment]
> @ornekali - i could not search your user `ornekali ` or title `4918` related to this ticket, what is your email address?

aliornek@orf.ist
I sent the mail again

**Comment by minhcasi** [comment]
moved to email support
