### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by mo7amademad** [inspireui/support#492]
Hello I want ask how activate register with facebook and how to test chat with vender and customer ?! Support slider ?

In application no image is active look example
(https://user-images.githubusercontent.com/27162025/55799429-0d0f7d00-5ada-11e9-9d64-6608ee736571.jpg)
(https://user-images.githubusercontent.com/27162025/55799430-0d0f7d00-5ada-11e9-9e54-53da383da7ee.jpg)

**Comment by luyx2412** [comment]
HI @mo7amademad Please provide your purchase code and follow the template issue to track easier.

Thanks

**Comment by mo7amademad** [comment]
Item ID:
22278924

**Comment by luyx2412** [comment]
Closed! please provide your purchase code and create new issue follow the template.
