### ISSUE TITLE
Get some error in 'Profile options''

### ISSUE THREAD

**Issue by dibbo-ru** [inspireui/support#4920]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
- [ ] first issue
- [ ] second issue
- [ ] third issue

+ Product & version:1.4.3
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

![Untitxzcvzxvled 2](https://user-images.githubusercontent.com/19253603/92414473-29ec2c00-f176-11ea-9883-93fc8f7ed9b2.png)

**_Step 2 (require): submit proof of purchasing the license on https://verify.inspireui.com **

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by dibbo-ru** [comment]
How can I get the 'Add Listing' option through webview?

**Comment by minhcasi** [comment]
@dibbo-ru - you could add this url from your website 

<img width="1005" alt="Screen Shot 2020-09-08 at 15 55 32" src="https://user-images.githubusercontent.com/1459805/92455326-bc7ae280-f1eb-11ea-8483-8ff7521e27c1.png">

**Comment by dibbo-ru** [comment]
Can you resolve the error of screenshot?

**Comment by dibbo-ru** [comment]
flutter: Another exception was thrown: NoSuchMethodError: The method 'toLowerCase' was called on null.

**Comment by minhcasi** [comment]
@dibbo-ru - pls try to see where the error come from the detail log on android studio, it seems not related to the forget password?

**Comment by dibbo-ru** [comment]
<img width="938" alt="errora" src="https://user-images.githubusercontent.com/19253603/92723138-7445f680-f38a-11ea-887a-ba53e8cd89e8.png">
I have rebuild the fluxlisting default app again, same error is happening

**Comment by minhcasi** [comment]
@dibbo-ru - we could not reproduce this issue on the current build, could I know what the detail customize on your app?

**Comment by dibbo-ru** [comment]
How can i give you the customise file? Which files do you want?

**Comment by dibbo-ru** [comment]
And this is for happening only on IOS

**Comment by minhcasi** [comment]
@dibbo-ru - sorry i mean if you have customized the file that causes the issues, we will not support for checking.

Please help to try the fresh download package to see if it has the same issue - thank you!

**Comment by dibbo-ru** [comment]
I have rebuilt your fresh app but it is only happening for IOS. Android is okay.

**Comment by philipvu30** [comment]
Hi,

Please replace this [file](https://github.com/inspireui/support/files/5229492/settings.dart.zip) in lib/screens/settings.dart.
