### ISSUE TITLE
Widget header dark mode issue

### ISSUE THREAD

**Issue by jvsamoa** [inspireui/support#4921]
Hi I am using this widget but in my dark version is not displaying correctly, it's extremely white {
"title": "Bienvenidos a nuestra app",
"fontSize":19,
"showSearch":false,
"height":0.13,
"isSafeArea":true,
"layout":"header_text",
"padding":30
},

![image](https://user-images.githubusercontent.com/25646978/92420331-04a9ee80-f173-11ea-99a0-bb02bf56df91.png)  can you help me?

**Comment by jvsamoa** [comment]
Hi, additional is the second opportunity that I report this issue: My web checkout is not working correctly, I don´t need to use the native checkout because my web checkout had specific customization for Venezuela.

Please ASAP. In the 1.75 version was working correctly but not now.
![image](https://user-images.githubusercontent.com/25646978/92439620-77cf5700-f1ab-11ea-86e0-cef9e56369bf.png)

**Comment by minhcasi** [comment]
You could customize this file to assign the fixed color, example

<img width="993" alt="Screen Shot 2020-09-08 at 15 58 45" src="https://user-images.githubusercontent.com/1459805/92455670-2e532c00-f1ec-11ea-9137-d4522c06bdd5.png">

You could set `NativeOnePageCheckout: false` to disable the native payment checkout

**Comment by jvsamoa** [comment]
Hi, 

Yes, i set NativeOnePageCheckout: false and EnableOnePageCheckout as true, but my finalize purchase button says loading... and it doesn't redirect to my website, why?.

Another issue, my menu icon in the dark version is bad, I tried to change his color in 
buildDarkTheme -> appBarTheme -> iconTheme -> color but it's not working correctly.

![image](https://user-images.githubusercontent.com/25646978/92515029-3f636380-f213-11ea-89e8-c2a877dbb119.png)

![image](https://user-images.githubusercontent.com/25646978/92514867-f0b5c980-f212-11ea-9fef-07549d094075.png)


Please, we need your support, and thanks a lot.

**Comment by minhcasi** [comment]
- pls check the android studio comment to see if there is an error log when update NativeOnePageCheckout ?
- you could try to search the Statusbar and customize it color - https://tppr.me/oKCL2

**Comment by minhcasi** [comment]
Let us know if you have any more questions - thank you!

**Comment by jvsamoa** [comment]
Hi Team, all good for me...
This is my console log
A lot of good wishes!

I/flutter ( 5929): [2020-09-16 19:46:32.109379Z][Fluxstore][Cart] build
I/flutter ( 5929): [2020-09-16 19:46:37.102761Z][Fluxstore][wocommerce_api][16:46:37.102504] getAsync END [endPoint:coupons] url:coupons
E/flutter ( 5929): [ERROR:flutter/lib/ui/ui_dart_state.cc(171)] Unhandled Exception: NoSuchMethodError: The method '[]' was called on null.
E/flutter ( 5929): Receiver: null
E/flutter ( 5929): Tried calling: []("es")
E/flutter ( 5929): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
E/flutter ( 5929): #1      WooCommerce.getCheckoutUrl (package:fstore/services/woo_commerce.dart:1075:41)
E/flutter ( 5929): <asynchronous suspension>
E/flutter ( 5929): #2      Services.getCheckoutUrl (package:fstore/services/index.dart:371:23)
E/flutter ( 5929): #3      WooWidget.doCheckout (package:fstore/widgets/frameworks/woocommerce/index.dart:78:37)
E/flutter ( 5929): #4      _MyCartState.doCheckout (package:fstore/screens/cart/my_cart.dart:351:29)
E/flutter ( 5929): #5      _MyCartState.onCheckout (package:fstore/screens/cart/my_cart.dart:342:7)
E/flutter ( 5929): #6      _MyCartState.build.<anonymous closure>.<anonymous closure> (package:fstore/screens/cart/my_cart.dart:255:93)
E/flutter ( 5929): #7      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:993:19)
E/flutter ( 5929): #8      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1111:38)
E/flutter ( 5929): #9      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
E/flutter ( 5929): #10     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
E/flutter ( 5929): #11     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
E/flutter ( 5929): #12     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:222:7)
E/flutter ( 5929): #13     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:476:9)
E/flutter ( 5929): #14     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:77:12)
E/flutter ( 5929): #15     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
E/flutter ( 5929): #16     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
E/flutter ( 5929): #17     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
E/flutter ( 5929): #18     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
E/flutter ( 5929): #19     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:220:19)
E/flutter ( 5929): #20     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:200:22)
E/flutter ( 5929): #21     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:263:11)
E/flutter ( 5929): #22     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:157:7)
E/flutter ( 5929): #23     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:103:7)
E/flutter ( 5929): #24     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:87:7)
E/flutter ( 5929): #25     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter ( 5929): #26     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter ( 5929): #27     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter ( 5929): #28     _invoke1 (dart:ui/hooks.dart:265:10)
E/flutter ( 5929): #29     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)
E/flutter ( 5929):
