### ISSUE TITLE
Add listing 404 error.

### ISSUE THREAD

**Issue by silamutungi** [inspireui/support#4922]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
Getting this error when trying to navigate to Add listing from the settings page. Suspect it's a URL config issue.

+ Product & version:
Flexstore listing vs 1.4.2
+ Flutter (or React Native) version: 
flutter 1.20.3
+ Testing Device/Simulator: 
Android and iOS device
+ Screenshot issues (drag the file to attach here): 
![IMG_C8386A96C8E1-1](https://user-images.githubusercontent.com/7536714/92422587-c391ea00-f132-11ea-94ce-63ba364b25d2.jpeg)

**_Step 2 (require): submit proof of purchasing the license on https://verify.inspireui.com **

See ticket #4831

**Comment by minhcasi** [comment]
you could add this option to the config file and point to your site 

<img width="1111" alt="Screen Shot 2020-09-08 at 16 00 54" src="https://user-images.githubusercontent.com/1459805/92455937-7d995c80-f1ec-11ea-97e9-979da2660673.png">

pls help to keep one ticket open for your all comments #4831
