### ISSUE TITLE
RAVE Integration

### ISSUE THREAD

**Issue by ongaki8** [inspireui/support#4923]
1. Please help me integrate this payment to the APP. I have tried but I'm unable to. https://github.com/wilburt/rave_flutter

2. Is it possible to reduce the distance between two rows in the products section?

**Comment by minhcasi** [comment]
@ongaki8 - i'm sorry that this is a new customize feature that not include from our support scope - please help to try your best 👍

**Comment by ongaki8** [comment]
What about issue 2?
