### ISSUE TITLE
Fluxstore Woocommerce [ Version 1.7.7 ] : Rate the APP not Working

### ISSUE THREAD

**Issue by swspro** [inspireui/support#4924]
Dear @minhcasi , 

This is Subhadarsini from SWS PRO.

Here is one of the issue we facing in the latest version of  the app

We have followed the complete documentation to Rate the App in the Profile section  

**Rate the App** is not working in the latest version. In the old version its working.

![rate the app](https://user-images.githubusercontent.com/15525566/92446481-816cb500-f1d3-11ea-8b0e-4fad76c10948.jpeg)

Regards
Subhadarsini

**Comment by minhcasi** [comment]
@swspro - it's working with our testing, please help to double-check your setting, you could revert the previous version of the rating library 

remind: keep your all comment to one open ticket pls #4841 - thank you!
