### ISSUE TITLE
Products don't show

### ISSUE THREAD

**Issue by Cydo73** [inspireui/support#4926]
Hello, i purchased the multi vendor app, but my products do not show on the emulator. I have followed the instructions in the guidelines, by regenerating thumbnails and updating my source code, but i don't know why it isn't working. Please let me know on what i can do. Only the background images, logos, and banner images can show.

![Annotation 2020-09-08 103509](https://user-images.githubusercontent.com/69629505/92450099-ad803a00-f1c3-11ea-9fa6-eccd60c142c1.jpg)
![Annotation 2020-09-08 103559](https://user-images.githubusercontent.com/69629505/92450100-aeb16700-f1c3-11ea-9414-75ccda18553e.jpg)
![Annotation 2020-09-08 105539](https://user-images.githubusercontent.com/69629505/92450103-af49fd80-f1c3-11ea-819a-9af65c9cf669.jpg)
![Annotation 2020-09-08 105817](https://user-images.githubusercontent.com/69629505/92450107-b07b2a80-f1c3-11ea-8bb7-e25cc041c1ac.jpg)

**Comment by minhcasi** [comment]
@Cydo73 - could you give a try to test this issue by using the Fluxbuilder tool - http://fluxbuilder.com to see if happen the same issue?

**Comment by Cydo73** [comment]
Thank you for your quick response. I already used the Flux Builder tool.
The products show in the Flux Builder, but when I copy the code and paste
it into the Json file, everything else shows except the products.
That's the issue

**Comment by Hasnain741** [comment]
Same issue here......
![IMG-20200909-WA0002 1](https://user-images.githubusercontent.com/37085591/92546624-6f8b2080-f26c-11ea-9cd8-215c35cc5745.jpg)
 product showing in fluxBuilder but not in android device.

**Comment by Hasnain741** [comment]
@minhcasi please give solution for my problem.

**Comment by Cydo73** [comment]
Hello, I'd really appreciate it if you got back to me about this matter
Thank you

**Comment by Hasnain741** [comment]
Hello, @Cydo73

**Comment by Hasnain741** [comment]
i have problem with product loading in home screen

**Comment by Cydo73** [comment]
I have the same problem too.
Have you contacted other people who have solved it?

**Comment by Hasnain741** [comment]
No i just commented in your token.

**Comment by Cydo73** [comment]
Maybe we can try reaching out to people who purchased the app and is
working for them

**Comment by Hasnain741** [comment]
Can you find any solution?

**Comment by Hasnain741** [comment]
Ok your app is loading product on home screen in flux builder?

**Comment by minhcasi** [comment]
@Cydo73 - try to use the `Analysis Connection` tool on fluxbuilder to see if all good with your app?

**Comment by Hasnain741** [comment]
i can't get your point

**Comment by Hasnain741** [comment]
@minhcasi kindly provide solution for this.

**Comment by madilsharief** [comment]
> @Cydo73 - try to use the `Analysis Connection` tool on fluxbuilder to see if all good with your app?

I got same issue, i tried analysis connection tool on fluxbuilder too and in fluxbuilder everything works fine. But in real life we are not gona run app in fluxbuilder right? 

I am compiling code on Andorid Studio and app runs normal but when as other said products don't load. Men's Collection/Women's Collection show a loading text and thats it nothing happens. 

Same issue with category page, nothing loads. But if i give link in banner for category and click it, it loads. 

Would appreciate solution.

**Comment by minhcasi** [comment]
@Cydo73 @Hasnain741 - pls check this screen - https://tppr.me/9QqsR

@madilsharief - pls create a new ticket with a detail screenshot if you have purchased the product

**Comment by Hasnain741** [comment]
@minhcasi 
![Capture](https://user-images.githubusercontent.com/37085591/92857956-dea07a80-f40e-11ea-8848-385ecf45363d.PNG)
Result of screen you mentioned

**Comment by Cydo73** [comment]
Thank you for your feedback. I appreciate it. When I run an analysis
connection, all my checkpoints are success except for "pages connectivity "
I already ran the trouble shoot about 5 times, and the results are the
same.

**Comment by minhcasi** [comment]
the `pages connectivity` is related to the Post from WordPress that could not impact to the app - if you could show the product/category under the Review Data section from that screen that means the app connects with your site successful 👍

**Comment by Cydo73** [comment]
Thank you for your assistance, i really appreciate it. I just have a few
more fixes, that i believe you can help me with. I look forward to
hearing from you.
https://github.com/inspireui/support/issues/5016
Thank you!
