### ISSUE TITLE
Colors & Size disappear in cart

### ISSUE THREAD

**Issue by kermalk** [inspireui/support#4927]
+ Detail Issues: 
- [ ]  size and colors are disappearing in Items left in cart after few days
![WhatsApp Image 2020-09-08 at 2 22 41 PM](https://user-images.githubusercontent.com/62398663/92465094-2d67cd80-f1df-11ea-94a7-d386ed94afd3.jpeg)

**Comment by minhcasi** [comment]
@kermalk - pls post your all comment into one open ticket #4874
