### ISSUE TITLE
Shipping shows price without VAT

### ISSUE THREAD

**Issue by Trustedbrands** [inspireui/support#4929]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
- [ ] first issue
The price of shipping is displayed without VAT in the app.
![Screenshot_1599564440](https://user-images.githubusercontent.com/69647853/92470831-4c626180-f1d7-11ea-876f-47e3af7c6dc5.png)

- [ ] second issue
Can choose more quantity than we have in stock.

![InkedScreenshot_1599564608_LI](https://user-images.githubusercontent.com/69647853/92471365-238e9c00-f1d8-11ea-84e3-e51cc198eb26.jpg)

- [ ] third issue

+ Product & version: Woocommerce 1.7.7
+ Flutter (or React Native) version: Flutter
+ Testing Device/Simulator: Android
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on https://verify.inspireui.com **

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhtruong315** [comment]
@Trustedbrands can u send me common folder and admin account to login your website via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/4929

**Comment by Trustedbrands** [comment]
@minhtruong315 you will get it by email tomorrow!

**Comment by Trustedbrands** [comment]
@minhtruong315 You should now have received an email.

**Comment by minhtruong315** [comment]
I received. I will check and let you know the result

**Comment by minhtruong315** [comment]
Hi @Trustedbrands Your issues are fixed. it will be available in next release.

**Comment by Trustedbrands** [comment]
@minhtruong315 Thanks! When will you launch the next update?

**Comment by minhtruong315** [comment]
maybe this week

**Comment by minhcasi** [comment]
Greetings from InspireUI 🎉
To improve user experience during support, we are announcing that a new ticket support system is available on this link https://support.inspireui.com - please help to move your next comment on the new support system - thank you for your time!
