### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by vladmdx** [inspireui/support#4930]
Hello, I have an error wher try to build apk or do something else:

FAILURE: Build failed with an exception.

What went wrong: A problem occurred configuring root project ‘android’. > Could not resolve all artifacts for configuration ’:classpath’. > Could not find com.android.tools:r8:1.5.25. Searched in the following locations: – https://dl.google.com/dl/android/maven2/com/android/tools/r8/1.5.25/r8-1.5.25.pom – https://jcenter.bintray.com/com/android/tools/r8/1.5.25/r8-1.5.25.pom – http://storage.googleapis.com/r8-releases/raw/com/android/tools/r8/1.5.25/r8-1.5.25.pom Required by: project :
Try: Run with—stacktrace option to get the stack trace. Run with—info or—debug option to get more log output. Run with—scan to get full insights.
Get more help at https://help.gradle.org
BUILD FAILED in 3s Running Gradle task ‘assembleRelease’... Running Gradle task ‘assembleRelease’... Done 3.9s Gradle task assembleRelease failed with exit code 1

What can I do to fix it?

On codecanyon I am https://codecanyon.net/user/dencatton, so you can check my license.

screenshot:  https://ibb.co/VLVmHf1

**Comment by minhcasi** [comment]
@vladmdx - thank you for the question, pls check the following solutions:

- Please send us your result by running `flutter doctor`
- Double-check if you could run the example from Test Drive - https://flutter.dev/docs/get-started/test-drive - this help to check if you

**Comment by minhcasi** [comment]
Let us know your updating - thanks
