### ISSUE TITLE
Install Mstore extension on magento 2.3.5

### ISSUE THREAD

**Issue by hdakei** [inspireui/support#4931]
![Issue](https://i.ibb.co/YhhN4fL/Screenshot-20200908-182343.png)

+ Detail Issues: 
when I Compile in my Magento directory, I've one error that shows one class called from Display.php in   /srv/magento/public3/app/code/Mstore/PaymentResolver/Block/Display.php   that could not find Hyperpay\Extension\Block\Display', Would you solve this issue, please?

Thank you

Product & Version:1.7.7b
Flutter (or React Native) version: Flutter
Testing Device/Simulator: Android Simulator (API 29 Android 10)
My Magento version on local (Test) is 2.3.5 p1 and in our production, I'm using Magento 2.3.5 p2 (we already on test mod yet)

**Comment by minhcasi** [comment]
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support https://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
@minhtruong315 - please help to check the issue

**Comment by minhtruong315** [comment]
@hdakei can u send me hosting account via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/4931

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!

**Comment by hdakei** [comment]
Sorry for the late reply, I just send an email to truong@inspireui.com that included all information about my server, Should I open a new ticket for follow up this ticket?
