### ISSUE TITLE
some issues and bugs still not resolved from old versions

### ISSUE THREAD

**Issue by abedfatafta** [inspireui/support#4932]
**_Step 1 (require): describe detail issues & screenshots_**
- product card view  for variable product showing old price same as new price , file: product_card_view.dart line 176 - using wcfm woocommerce , and thats because woocommerce save the final price under price meta without having original ( you resolved it inside the product page ) 
![image](https://user-images.githubusercontent.com/16276919/92493215-eab4ee00-f1fc-11ea-9f74-0de1ad86c155.png)

- in variable product when customer add to cart without chosing variable it work and add to cart , so this is confusing it must ask him to chose a variable , as we are lost what the choice of the customer will be .... go to any variable product - click buy now without chosing variable its added :

- if the customer chose one variable and add to cart then chose another variable and add to cart - its record 2 product one variable (example i want to buy 2 t-shirt one small and one large , i chose small add to cart then i chose large add to cart in cart it show 2 small 

+ Product & version: 1.66 , 1.77 . latest on git 
+ Flutter (or React Native) version: Flutter
+ Testing Device/Simulator: Iphone 6 , mi note 7 , simulator nexus

+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on https://verify.inspireui.com **

Old ticket #4268

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by abedfatafta** [comment]
first bug  temporary solution : hook woocommerce api to return regular price for variable product .

**Comment by minhtruong315** [comment]
@abedfatafta please upload your source code to github invite me: minhtruong315@gmail.com
And send me admin account to login your website as well.
Thanks

**Comment by abedfatafta** [comment]
Tested on fork from your git without any modifications just connected to
our backend wcfm and they are the same





-- 
Regards

**Comment by minhtruong315** [comment]
@abedfatafta I need to check your config. Our website is showing well. pls send me the source code and admin account to check.
Thanks

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
