### ISSUE TITLE
fluxstore checkout error

### ISSUE THREAD

**Issue by alazar-aklilu** [inspireui/support#4934]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
- [ ] first issue
1. after editing the checkout fields using inspector tool, i get this error 
![photo_2020-09-09_00-11-24](https://user-images.githubusercontent.com/60713664/92528250-2073ca00-f231-11ea-96d3-0b3508b9c2c9.jpg)
- [ ] second issue
2. i asked if i can only view COD on payment methods and you told me to edit the payments.dart but i am very confused as to which part i have to edit 
- [ ] third issue
+ Product & version:
 1.7.7 fluxstore multivendor
+ Flutter (or React Native) version:
 flutter
+ Testing Device/Simulator: 
samsung galaxy s8+ 
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on https://verify.inspireui.com **

#3357 

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
1. Please try your best to fix the impact from your customization as it will not include from our support scope - pls refer to our support policies - https://inspireui.com/support-policies/ - thank you for your understanding. 

2. try to filter only COD from your code - https://tppr.me/K0Oxe 

```
var _paymentMethods = await _service.getPaymentMethods(
        address: address,
        shippingMethod: shippingMethod,
        token: token,
      );
      paymentMethods = _paymentMethods.where((item) => item.title == 'COD').toList();
```

**Comment by alazar-aklilu** [comment]
okay can you help me make state and city not required in the checkout fields as they are marked as required

**Comment by alazar-aklilu** [comment]
![Screenshot_20200909-161410](https://user-images.githubusercontent.com/60713664/92603174-ac303980-f2b7-11ea-8f05-cdb17b9680ff.jpg)

after editing thr payment_method.dart file. no payment method shows up on my checkout page

**Comment by minhcasi** [comment]
you need to check the item title may not `COD` on your site, you should try to debug to check the issues - thank you!

**Comment by alazar-aklilu** [comment]
okay i will check what about the required checkout fields, please help me

Sent from Yahoo Mail on Android 
 
  On Thu, 10 Sep 2020 at 11:39 am, Minh Pham<notifications@github.com> wrote:   


you need to check the item title may not COD on your site, you should try to debug to check the issues - thank you!

**Comment by minhcasi** [comment]
@alazar-aklilu - if you customize the checkout field, please make sure it is not broke the in params when posting new request to create new Order - https://woocommerce.github.io/woocommerce-rest-api-docs/#create-an-order

**Comment by minhcasi** [comment]
Let us know if you have any questions

**Comment by alazar-aklilu** [comment]
@minhcasi thank you, i have fixed the payment method issue, it was the title of COD as you said
