### ISSUE TITLE
In shipping when i select country india ( state shows wrong ) it shows other country states 

### ISSUE THREAD

**Issue by ssathamenterprises** [inspireui/support#4936]
In shipping when i select country india ( state shows wrong ) it shows other country states .

only this issue when i select india 

i attached proof of purchase image here
<img width="782" alt="proof of purchase" src="https://user-images.githubusercontent.com/68118999/92549910-f7812280-f28c-11ea-9c2a-df3791c6b5b9.PNG">

**Comment by ssathamenterprises** [comment]
https://drive.google.com/file/d/1AyN7gdBTdx62lnn_l2DQ6FRMhYl5bZDb/view?usp=sharing

here i share the video ( shows the state list wrong )

**Comment by minhcasi** [comment]
pls move your comment to one open ticket #4860
