### ISSUE TITLE
Không thể chạy được code

### ISSUE THREAD

**Issue by ducnm98** [inspireui/support#4937]
When I run flutter pub get code as description. It failed. And I can run the code exactly what I want
https://ibb.co/qmQCnwL
https://ibb.co/bbtms3m
https://ibb.co/8cF25zB
https://ibb.co/q7zkwT3

**Comment by minhcasi** [comment]
@ducnm98 try to use flutter channel stable
```
flutter channel stable
flutter upgrade --force
```

**Comment by ducnm98** [comment]
This is my htaccess file.
# BEGIN WordPress
# The directives (lines) between "BEGIN WordPress" and "END WordPress" are
# dynamically generated, and should only be modified via WordPress filters.
# Any changes to the directives between these markers will be overwritten.
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule ^(.*) - [E=HTTP_AUTHORIZATION:%1]
</IfModule>

# END WordPress

But when I run it got this error https://ibb.co/Bz2Bh06

**Comment by minhcasi** [comment]
@ducnm98 - it seems you have not activated the mstore-api License from Wordpress site

**Comment by minhcasi** [comment]
Let us know your checking
