### ISSUE TITLE
Fluxstore Pro - Address save option, Language based content change by config file Issue

### ISSUE THREAD

**Issue by masthan8** [inspireui/support#4938]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
1. Thanks for adding new fields for address, its really helpful. In that the apartment no field(company field in woocommerce backend), is not getting saved to database. Please check that. 
2. When I upload the updated config.json the changes gets reflected after clearing cache, but if the user changes the language from English to arabic, and then comes back again to arabic, the app is showing the old layout and not the updated layout, even if cache is cleared. The updated config is not working properly pls check this. Also update your document with how to updated layout for people with multi languages without updating the app manually. 

+ Product & version: Latest Fulxstore Pro

**_Step 2 (require): submit proof of purchasing the license on https://verify.inspireui.com **

Submitted

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@masthan8 - thank you for the feedback

- I've reported to the team to check the address issue
- The next release `1.7.8` will support multi config file caching to upload on mstore-api 👍

**Comment by minhcasi** [comment]
Please move new conversation to new Ticket Support http://support.inspireui.com - thank you!
