### ISSUE TITLE
[ListApp] RegionID not working

### ISSUE THREAD

**Issue by williamoconnorme** [inspireui/support#494]
- Product: ListApp
 - Your Purchased Code: Item Purchase Code:
2c0cab07-d2d3-4461-94ab-de84f438db97

**Describe the bug**
ListApp contains a line in listify.js for setting a regionId. This however does not work and I do not see any references to it in the code for version 1.6.1

      {
        component: listing,
        regionId: '71',
        paging: true,
        layout: Constants.Layout.banner,
      }

Using categoryListingId works for getting posts from the category ID that is set. I would like to get posts from a region ID that is set using: https://wordpress.org/plugins/wp-job-manager-locations/

I would presume custom code is needed for this as I don't see any references to regions except for regionID. Is this an incomplete feature or should this be working?

**Comment by iqmtgar** [comment]
I also did not work

RegionID not working

**Comment by thangvo9x** [comment]
Hi. We noted it for in the next release. Thanks for your VALUE feedback.

**Comment by williamoconnorme** [comment]
@thangvo9x I see 1.7 has been released recently. Is RegionID expected to be supported in the next release? Is there any timeline on when this will be released?
