### ISSUE TITLE
Redirect to home screen and Update Profile not saving

### ISSUE THREAD

**Issue by shirochan88** [inspireui/support#4940]
#1. How do I redirect user to the home screen after login?

I tried changing the route under _welcomeMessage() as below, but it raises the exception that - No Material widget found.

```
if (kLayoutWeb) {
  Navigator.of(context).pushReplacementNamed('/home-screen');
} else {
  Navigator.of(context).pushReplacementNamed('/home-screen');
}
```

#2. Saving "Update Profile" values do not save the values as well as the screen is shown empty after the update. User is signed in with a regular WooCommerce account.

+ Product & version: FluxStore 1.77 for WooCommerce
+ Flutter (or React Native) version: Flutter
+ Testing Device/Simulator: Android

**Comment by minhcasi** [comment]
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support https://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by shirochan88** [comment]
Support form with the requested purchase license has been submitted.

**Comment by shirochan88** [comment]
The support form has been submitted with requested document.




Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by minhcasi** [comment]
@shirochan88 - could you try to run `Navigator.pushReplacementNamed(context, "/home");`

**Comment by shirochan88** [comment]
Unfortunately, it does not take the user to the home screen.

I'm trying to login from Setting -> login. Post login, the screen stays on the Settings page.

I've run flutter clean prior running the code.

**Comment by shirochan88** [comment]
Could you please provide an update? We are on a timeline.

**Comment by simonpham** [comment]
Hi @shirochan88,

For navigate to Home after login from the menu, you can add this line under _welcomeMessage:

```
MainTabControlDelegate.getInstance().index = 0;
```

![image](https://user-images.githubusercontent.com/8846657/93057093-90ea7300-f697-11ea-8112-953011962611.png)

Do **NOT** change `'/home'` to `'/home-screen'`

Hope this can solve your issue. Good luck!

**Comment by simonpham** [comment]
For this problem

> #2. Saving "Update Profile" values do not save the values as well as the screen is shown empty after the update. User is signed in with a regular WooCommerce account.

I have checked and it did show empty after update. But it saves the values. We will fix empty problem and release it in the next version.

Thank you for your support!

**Comment by simonpham** [comment]
For now you can open `lib/models/user/user_model.dart` and make the changes as below:

```
    user.name = json['display_name'] ?? json['displayname'];
    user.email = json['user_email'] ?? json['email'];
    user.userUrl = json['user_url'] ?? json['url'];
    user.nicename = json['user_nicename'] ?? json['nicename'];
```

![image](https://user-images.githubusercontent.com/8846657/93058761-fdff0800-f699-11ea-9023-624169f15bd7.png)

**Comment by shirochan88** [comment]
@simonpham Thank you for your help! That worked!
