### ISSUE TITLE
Onboarding stuck

### ISSUE THREAD

**Issue by wisharabia** [inspireui/support#4942]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: Onboarding welcome screen is stuck and shows everytime the app opens

+ Product & version: Latest Version
+ Flutter (or React Native) version: Latest Version
+ Testing Device/Simulator: Simulator and real device
+ Screenshot issues (drag the file to attach here): 

![Screenshot_20200909_103546_com skinshop wisharabia](https://user-images.githubusercontent.com/68923516/92569018-b25af180-f288-11ea-9551-5fbeb141d587.jpg)

**_Step 2 (require): submit proof of purchasing the license on https://verify.inspireui.com **
Already did on ticket #4403

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by wisharabia** [comment]
Im also having the same issue with the font not changing on some menus such as this ticket
https://github.com/inspireui/support/issues/4447

i tried changing the font weight without luck so please help with this issue too

**Comment by dttrung26** [comment]
Hi @wisharabia , 
could you attach your `/lib/app_init.dart` here for OnBoarding issue checking?
Best

**Comment by wisharabia** [comment]
I will attach the app_init.dart. In the meantime can you let me know how to solve the font not changing issue similar to ticket 4447?

**Comment by minhcasi** [comment]
@wisharabia - you could check the font setting on this link https://docs.inspireui.com/fluxstore/multi-language/#multi-google-fonts

**Comment by wisharabia** [comment]
I did however the font Cairo doesnt change the appbar nor the settings font. I read the ticket i mentioned and it says you have to edit the weight of the font under styles.dart but that didnt work even after using a weight supported by the used google font 'Cairo'

**Comment by dttrung26** [comment]
Hi @wisharabia , 
please migrate your issues to our new support services at https://support.inspireui.com/help-center. So sorry for delaying your ticket sir.
have a nice day!
