### ISSUE TITLE
flutter: Exception: Sorry, you are not allowed to do that.

### ISSUE THREAD

**Issue by ducnm98** [inspireui/support#4943]
I Got this Error but don't know how to do
```
flutter: [2020-09-09 08:03:47.796147Z][Fluxstore]type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'List<dynamic>'
flutter: Exception: Sorry, you are not allowed to do that.
```

**Comment by dttrung26** [comment]
Hi @ducnm98 , 
please create 1 ticket only at https://github.com/inspireui/support/issues/4943 including all of your issues instead of creating multiple of them. 
Best.
