### ISSUE TITLE
Cached API error for largeCardHorizontalListItems

### ISSUE THREAD

**Issue by aliehanani** [inspireui/support#4944]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
- [ ] Images from website description do not show up in mobile app description, only text shows
- [ ] largeCardHorizontalListItems does not load when using API push.  Instead, displays "Error in type 'int' is not a subtype of type double. " Also, the color type for header_text layout stops functioning, via API push.
          FYI - the version of largeCardHorizontalListItems found at the following link was added, though, it does make the load 
          much faster, yet again does not load products when uploading API. Yes REST caches are cleared - 
          https://github.com/inspireui/support/issues/4635
- [ ] Google map auto populate puts state in wrong field - https://github.com/inspireui/support/issues/4021
- [ ] Is it possible to signup using social login (Google/Apple/Facebook) for "Register as Vender user"?

+ Product & version: Fluxstore Multi Vendor
+ Flutter (or React Native) version: 1.20.2
+ Testing Device/Simulator: Simulators - Pixel 3a XL API 30 & iPhone 11 Max
+ Screenshot issues (drag the file to attach here): 
<img width="445" alt="Screen Shot 2020-09-09 at 4 16 12 AM" src="https://user-images.githubusercontent.com/12172666/92573072-3eeabd00-f253-11ea-9417-3a5b2f58651e.png">

<img width="434" alt="Error via API for - largeCardHorizontalListItems" src="https://user-images.githubusercontent.com/12172666/92571874-a99af900-f251-11ea-9b1a-35b3586f8313.png">

<img width="446" alt="Screen Shot 2020-09-09 at 4 09 46 AM" src="https://user-images.githubusercontent.com/12172666/92572377-5aa19380-f252-11ea-99e0-32ed86c38230.png">

**_Step 2 (require): submit proof of purchasing the license on https://verify.inspireui.com **

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@aliehanani 

- Could you share the website URL of the product description so that we could have a check

- FYI - the version of largeCardHorizontalListItems found at the following link was added, though, it does make the load
much faster, yet again does not load products when uploading API.  -> pls share your related screenshot issue

- Google map will not use the state from the config, the state is only used for shipping address - pls share your related screenshot issue

- social registration for the vendor is not support

**Comment by aliehanani** [comment]
1. Could you share the website URL of the product description so that we could have a check
- This happens with all products, please review here - https://demo.nilebasket.com

2. FYI - the version of largeCardHorizontalListItems found at the following link was added, though, it does make the load
much faster, yet again does not load products when uploading API. -> pls share your related screenshot issue
- https://user-images.githubusercontent.com/12172666/92571874-a99af900-f251-11ea-9b1a-35b3586f8313.png

3. Google map will not use the state from the config, the state is only used for shipping address - pls share your related screenshot issue
- https://user-images.githubusercontent.com/12172666/92572377-5aa19380-f252-11ea-99e0-32ed86c38230.png

4. social registration for the vendor is not support
- Understood!

**Comment by aliehanani** [comment]
> @minhcasi
> 
> 1. Could you share the website URL of the product description so that we could have a check
> 
> * This happens with all products, please review here - https://demo.nilebasket.com
>   
>   * https://user-images.githubusercontent.com/12172666/92573072-3eeabd00-f253-11ea-9417-3a5b2f58651e.png
> 
> 1. FYI - the version of largeCardHorizontalListItems found at the following link was added, though, it does make the load
>    much faster, yet again does not load products when uploading API. -> pls share your related screenshot issue
> 
> * https://user-images.githubusercontent.com/12172666/92571874-a99af900-f251-11ea-9b1a-35b3586f8313.png
> 
> 1. Google map will not use the state from the config, the state is only used for shipping address - pls share your related screenshot issue
> 
> * https://user-images.githubusercontent.com/12172666/92572377-5aa19380-f252-11ea-99e0-32ed86c38230.png
> 
> 1. social registration for the vendor is not support
> 
> * Understood!
> 
> > <img alt="" width="48" src="/file/2020/03/vender_1-scaled.jpg"><img alt="" height="14" src="https://camo.githubusercontent.com/68f6396eaf28b665085a29623903769df4dcd86b/68747470733a2f2f64656d6f2e6e696c656261736b65742e636f6d2f66696c652f323031392f30392f66617669636f6e2d6e696c657472616e732e706e67"> Nile Basket**[NileBasket.com - African Grocery Delivery to Your Doorstep](https://demo.nilebasket.com/)**Wide selection of groceries, snacks, beverage, beauty, along with health and baby goods from across African regions.

@minhcasi
I discovered the issue with the product description images. It only works when built with page builder, as oppose to the original (text) editor.

**Comment by aliehanani** [comment]
@minhcasi

Please be advised that cached API error for largeCardHorizontalListItems persist, after replacing with the copy provided i [#4635 ](https://github.com/inspireui/support/issues/4635). I would also add that it was exactly the same as the one prior. Thank you in advance.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/12172666/92991347-427b7f80-f4b1-11ea-9503-85db4562cf8e.gif)

**Comment by minhtruong315** [comment]
@aliehanani can u upload your source code to github and invite me: minhtruong315@gmail.com
ping me when you invited.
Thanks

**Comment by aliehanani** [comment]
@minhtruong315 
@
Done, invite sent. Thank you in advance for your assistance.

**Comment by minhtruong315** [comment]
@aliehanani I see in the description "Mini Cakes" in this api.
```https://demo.nilebasket.com/wp-json/wc/v2/products/?status=publish&per_page=20&page=1&category=224&stock_status=instock&consumer_key=ck_d9bcb454ab939bf38b49bde6cbaeb349a869b123&consumer_secret=cs_a399ce621fdda9ff55f25c6c898f5471cf061f99
```
it has images. but the url doesnt work
```https://35.230.163.92/wp-content/uploads/2019/10/Mini-Cake-b-300x140.jpg```
Please check your website again.

**Comment by minhtruong315** [comment]
@aliehanani for largeCardHorizontalListItems issue. I see it's showing. how to reproduce that issue?
<img width="479" alt="Screen Shot 2020-09-13 at 8 24 47 AM" src="https://user-images.githubusercontent.com/10402500/93008065-c3627600-f59a-11ea-9a47-a29f1c98500c.png">

**Comment by aliehanani** [comment]
@minhtruong315 

Please try again, the config_en.json API has been added.

**Comment by aliehanani** [comment]
> @aliehanani I see in the description "Mini Cakes" in this api.
> 
> ```
> https://demo.nilebasket.com/wp-json/wc/v2/products/?status=publish&per_page=20&page=1&category=224&stock_status=instock&consumer_key=ck_d9bcb454ab939bf38b49bde6cbaeb349a869b123&consumer_secret=cs_a399ce621fdda9ff55f25c6c898f5471cf061f99
> ```
> 
> it has images. but the url doesnt work
> `https://35.230.163.92/wp-content/uploads/2019/10/Mini-Cake-b-300x140.jpg`
> Please check your website again. You can try to change https://35.230.163.92 to https://demo.nilebasket.com

@minhtruong315
Yeah, I noticed that...will update all the product descriptions using a page builder. Thank You

**Comment by minhtruong315** [comment]
> @minhtruong315
> 
> Please try again, the config_en.json API has been added.

send me config_en.json.

**Comment by aliehanani** [comment]
> > @minhtruong315
> > Please try again, the config_en.json API has been added.
> 
> send me config_en.json.

@minhtruong315
Please check your email for Subject line "Github - Cached API error for largeCardHorizontalListItems #4944"

**Comment by minhtruong315** [comment]
![Simulator Screen Shot - iPhone 11 - 2020-09-14 at 05 34 37](https://user-images.githubusercontent.com/10402500/93030281-ffa1df00-f64b-11ea-9a1e-b7836e45686b.png)
it's working well with your config_en.json file. can u record screen?

**Comment by aliehanani** [comment]
@minhtruong315 

I emailed you the full 30 seconds video, since GIF would not be able to capture all.

**Comment by minhtruong315** [comment]
@aliehanani give me your skype? I will contact you and check remotely

**Comment by aliehanani** [comment]
@minhtruong315 

Skype Name - pa_alie
Display Name - Hanani

**Comment by minhtruong315** [comment]
@aliehanani pls reply on the skype. thanks

**Comment by aliehanani** [comment]
@minhtruong315 

Please let me know if you'll be available in the next 2 hours?

**Comment by aliehanani** [comment]
@minhcasi @minhtruong315 

In the past week, I've been getting this new error, and unable to get past it. The app function return normally is arbitrary.

![SmartSelect_20200915-132138.jpg](https://user-images.githubusercontent.com/12172666/93521158-a2cd4f80-f8fd-11ea-9df1-5755695a26ba.jpg)

**Comment by minhtruong315** [comment]
supported via skype

**Comment by aliehanani** [comment]
Thanks again @minhtruong315 for the assistant. Will follow up on the new portal. Take care and appreciate your time.
