### ISSUE TITLE
Avoid product quantity change in the last section of the order process

### ISSUE THREAD

**Issue by bigjuju4fr** [inspireui/support#4945]
Hello,

@minhcasi you closed my previous ticket #4893 
But i still need your help. I couldn't find how to avoid the change via the dropdown.
What i want to do is simple, i just want to avoid users to click on the dropdown arrow and change the quantity at this stage. Only the quantity should show. The only possibility to change the product quantity should be in the cart.
How to do that please?
Thank you again for the great app.

![92306083-ed111100-ef8c-11ea-871b-8abee17ec65f](https://user-images.githubusercontent.com/69798792/92574172-0cf34e00-f287-11ea-878e-c784d06d2c68.png)

Thanks
Best regards

**Comment by minhcasi** [comment]
@bigjuju4fr - you could customize this file to add this dropdown on ShoppingCartRow widget

<img width="1029" alt="Screen Shot 2020-09-09 at 20 20 05" src="https://user-images.githubusercontent.com/1459805/92603725-dabf0c00-f2d9-11ea-9d7c-888b633f7117.png">

**Comment by bigjuju4fr** [comment]
Hi @minhcasi ,
i still can't follow you. Please what should i customize here? i don't want to add anything but from the review tab the user shouldn't have the possibility to change the quantity anymore. Please see my below screenshot, it's different from your image:
<img width="1086" alt="review" src="https://user-images.githubusercontent.com/69798792/92830299-6ff2fb00-f3d5-11ea-929a-a256124a65ab.png">

Please help.
Thanks

**Comment by minhcasi** [comment]
@bigjuju4fr - I mean you could customize the ShoppingCartRow widget, you could remove the quantity dropdown or replace it as Static Label (by using Text widget)

<img width="1076" alt="Screen Shot 2020-09-11 at 11 05 07" src="https://user-images.githubusercontent.com/1459805/92857294-a9038d80-f41e-11ea-95b3-c3cc1cdc0022.png">

**Comment by bigjuju4fr** [comment]
Hello,
please just tell me what to do. i still can't get it how to to do that? i tried many things but it doesnt work.

Best

**Comment by minhcasi** [comment]
@bigjuju4fr - if you could not customize, give us a time to submit this request to the team, we will add the option to disable the option on the next release.

Please help to move the conversation to the same open ticket #4967 - we will update the status there
Thank you!
