### ISSUE TITLE
Multi language issue

### ISSUE THREAD

**Issue by l3op** [inspireui/support#4947]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
Dear InspireUI, I faced an issue while setting up the multilingual in the app. In the advanced settings, I did changed the "isMultiLanguages" to true. 

![image](https://user-images.githubusercontent.com/12974004/92598882-2067de80-f2b2-11ea-93c4-a5930e865291.png)

We use a plugin in our e-commerce called "[qTranslate-X](https://wordpress.org/plugins/qtranslate-x/)" which help up to translate our web-page and the products in two different language. 

I was digging in the code and i noticed that when applying that option to true the url must use query mode '&lang=$lang'.

```
  if (lang != null && kAdvanceConfig["isMultiLanguages"]) {
    url += "&lang=$lang";
  }
```

Luckily, the "qTranslate-X" plugin help to set the url into query mode.

After doing all this i noticed the products and it's attribute in the app shown as a weird string. Like this 
**[:en]pink dress[:][:ar]فستان وردي[:]**
**[:en]Size[:][:ar]المقاس[:]**

So if is there any help or suggestion that would be great. Best regards

+ Product & version: FluxStore pro 1.7.7b
+ Flutter (or React Native) version: Flutter 1.20.3 • channel stable
+ Testing Device/Simulator: Device
+ Screenshot issues (drag the file to attach here): 

![Screenshot_20200909-151732_Marekat](https://user-images.githubusercontent.com/12974004/92600443-48584180-f2b4-11ea-8d91-16ef882a35a5.jpg)

**_Step 2 (require): submit proof of purchasing the license on https://verify.inspireui.com **
Submitted 

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@l3op - you could try to update the models class to parse these languages query string before populating into the UI, example write the wrapper-languages function to convert the string before assign value - https://tppr.me/zUUW9

**Comment by l3op** [comment]
@minhcasi Could you please give me an example?

**Comment by minhcasi** [comment]
example:

```
function convertLanguageName(string languague) {
   // you need to reference on the Wordpress plugin how to handle the convert name 
} 

....
name = convertLanguageName(parsedJson['name']);
...
```

**Comment by l3op** [comment]
@minhcasi Thank you for the suggestion.
 
Our team decide to change "qTranslate-X" plugin with another plugin which saves a lot of time. unfortunately, the new plugin it doesn't have the option to set the url in the query mode ( ?lang=en ). It use the Pre-Path Mode ( puts /en/ in front of URL).

Is there any solution for this?

**Comment by minhcasi** [comment]
try one of these plugins: polylang, Transposh, WPML

**Comment by l3op** [comment]
We are using Weglot Translate. We already pay for it 😅

**Comment by l3op** [comment]
> We are using Weglot Translate. We already pay for it 😅

Can we make it work with the app or not?

**Comment by minhcasi** [comment]
you could try to customize that plugin and enable `?lang=en` then it will work with the app

**Comment by l3op** [comment]
@minhcasi It's okay now. We used polylang plugin and everything is good now. Thanks for your support ❤
