### ISSUE TITLE
Exception: Currency should be a valid ISO currency code

### ISSUE THREAD

**Issue by Sviluppandosulweb** [inspireui/support#4948]
**_Step 1 (require): describe detail issues & screenshots_**
Hi,
I have two issues with Multivendor 1.7.7 that I need help with (I have uploaded common and config files on verify.inspireui.com for your review...):
1) Paypal iso code issue: when i try to pay with Paypal i have this error.
![Screenshot_1599661969](https://user-images.githubusercontent.com/71024948/92613998-d7b52300-f2bb-11ea-8a3a-20efe4575ff1.png)

2) Bank transfer issue: Payment webview doesn't support Guest Checkout
![Screenshot_1599662740](https://user-images.githubusercontent.com/71024948/92615632-9aea2b80-f2bd-11ea-983b-bf33cb0e49af.png)

+ Product & version: FluxStore Woocommerce 1.7.7
+ Flutter (or React Native) version: Flutter 1.20.2
+ Testing Device/Simulator: Android Pixel 3A

**_Step 2 (require): submit proof of purchasing the license on https://verify.inspireui.com **

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@Sviluppandosulweb - thank you for the rating. Please confirm your question on Fluxstore WooCommerce or Vendor product (as you have submitted the license for Woocommerce but the question is for vendor 😅)

@minhtruong315 - pls help to check the Payment issue

**Comment by minhtruong315** [comment]
@Sviluppandosulweb Paypal only supports some currencies. Please use these currencies. https://developer.paypal.com/docs/api/reference/currency-codes/
For payment webview. You  need to enable NativeOnePageCheckout to support Guest Checkout. You're using payment webview. so it requires to login

**Comment by Sviluppandosulweb** [comment]
> 
> 
> @Sviluppandosulweb Paypal only supports some currencies. Please use these currencies. https://developer.paypal.com/docs/api/reference/currency-codes/
> For payment webview. You need to enable NativeOnePageCheckout to support Guest Checkout. You're using payment webview. so it requires to login
> 
> > **[Currency Codes - PayPal Developer](https://developer.paypal.com/docs/api/reference/currency-codes/)**

but NativeOnePageCheckout is already active in my payments.dart and is iso code payment also in payments.dart? Because I have already entered the correct ISO

**Comment by minhtruong315** [comment]
@Sviluppandosulweb can u send me common folder?

**Comment by Sviluppandosulweb** [comment]
> 
> 
> @Sviluppandosulweb can u send me common folder?

yes.
[common.zip](https://github.com/inspireui/support/files/5207812/common.zip)

**Comment by minhtruong315** [comment]
Hi @Sviluppandosulweb change  DefaultCurrency in common/config/general.dart
```
"DefaultCurrency": {
    "symbol": "€",
    "decimalDigits": 2,
    "symbolBeforeTheNumber": true,
    "currency": "EUR"
  },
```

**Comment by Sviluppandosulweb** [comment]
> 
> 
> Hi @Sviluppandosulweb change DefaultCurrency in common/config/general.dart
> 
> ```
> "DefaultCurrency": {
>     "symbol": "€",
>     "decimalDigits": 2,
>     "symbolBeforeTheNumber": true,
>     "currency": "EUR"
>   },
> ```

ok thanks, but now i have this error:
![Screenshot_1599830454](https://user-images.githubusercontent.com/71024948/92930546-81262100-f442-11ea-87ff-7d0605fb6866.png)

**Comment by minhtruong315** [comment]
@Sviluppandosulweb can u record screen? I think product price, subtotal, shipping cost, discount is invalid format.

**Comment by Sviluppandosulweb** [comment]
Step by step
![Screenshot_1599897188](https://user-images.githubusercontent.com/71024948/92990610-11657400-f4de-11ea-977a-5f4001a8ff46.png)
![Screenshot_1599897169](https://user-images.githubusercontent.com/71024948/92990612-13c7ce00-f4de-11ea-83cc-a29af41be32c.png)
![Screenshot_1599897177](https://user-images.githubusercontent.com/71024948/92990613-14606480-f4de-11ea-95ea-289d418bd21b.png)
![Screenshot_1599897183](https://user-images.githubusercontent.com/71024948/92990614-14606480-f4de-11ea-8be1-abc836525bf5.png)

**Comment by minhtruong315** [comment]
@Sviluppandosulweb can u upload your source code to github then invite me: minhtruong315@gmail.com
Ping me when you invited.
Thanks

**Comment by Sviluppandosulweb** [comment]
> 
> 
> @Sviluppandosulweb can u upload your source code to github then invite me: [minhtruong315@gmail.com](mailto:minhtruong315@gmail.com)
> Ping me when you invited.
> Thanks

ok, i do it

**Comment by minhtruong315** [comment]
@Sviluppandosulweb Fixed. pls check again

**Comment by Sviluppandosulweb** [comment]
ok thanks!! Last issue Payment webview does not support Guest Checkout for wire transfer purchases

**Comment by minhtruong315** [comment]
fixed. pls pull the source code and check again

**Comment by Sviluppandosulweb** [comment]
Format Exception: Unexpected Character  (at charcater 1)

**Comment by minhtruong315** [comment]
Can u change your website url to subdomain instead of sub folder
```https://www.corsiarredatoredesigner.it/app``` to ```https://www.app.corsiarredatoredesigner.it```

**Comment by Sviluppandosulweb** [comment]
No, I can not.

**Comment by minhcasi** [comment]
@Sviluppandosulweb - the app will require subdomain or domain to integrate via Rest API - if you are using the subfolder then it will not work completely

**Comment by minhcasi** [comment]
Let us know if you have any questions and the solution is fixed the issue - thank you for your time!
