### ISSUE TITLE
Attributes aren't translated in the cart page

### ISSUE THREAD

**Issue by qozia3** [inspireui/support#4949]
hi there. please see attached photo.
attributes are translated else where but not on the cart page
<img width="344" alt="Screen Shot 2020-09-09 at 6 31 22 PM" src="https://user-images.githubusercontent.com/69852582/92620401-451c8000-f2cb-11ea-944d-fe40be297dca.png">

thank you

**Comment by minhcasi** [comment]
@qozia3 - pls help to check if you have translated the product attribute on this config file, it is used to translate the languages for an attribute which is not support from woocommerce API

<img width="1037" alt="Screen Shot 2020-09-10 at 08 39 14" src="https://user-images.githubusercontent.com/1459805/92671690-1ccf6880-f341-11ea-926e-d7fdf7497041.png">

**Comment by minhcasi** [comment]
Let us know your checking - thank you!
