### ISSUE TITLE
[Cestore] where to change the Database URL for Mobile App

### ISSUE THREAD

**Issue by deepakjain29** [inspireui/support#495]
Product: [CeStore]
Purchased Code: [4509e66c-d8d4-4aa7-ba43-18ca32aaa067]
Describe the bug
How to change the database URL ( Node API ) in Mobile APP to sync with our cloud server 
Additional context
There is no file in our code with config.js specifically for APP in Mobile code

Please help
regards
Deepak
javin.retails@gmail.com

**Comment by minhtruong315** [comment]
Hi @deepakjain29 
You can not change the database url from mobile app. The database url must to change in website source code. 
If you wanna change the database url, you can edit website/config/server.js file in website source code.
