### ISSUE TITLE
Author name returning null value

### ISSUE THREAD

**Issue by RomeoDar** [inspireui/support#4950]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: My issue of  #4895 is not solved yet

https://github.com/inspireui/support/issues/4895#issuecomment-688179335 he told that it's fixed in next patch i want to get access to that patch caz' it's not uploaded yet, i'm behind my schedule and it's keep delaying kindly add hdar001@gmail.com to gitlab latest repository for fluxnews

for verification of purchase code ( use this ticket  #4895 ) or reopen that previous ticket of mine

+ Product & version: fluxnews

**Comment by minhcasi** [comment]
Sent an invitation to your gitlab email, we will upgrade the patching on this week on gitlab and the new release will be ready later on  - thank you!

**Comment by RomeoDar** [comment]
still waiting you didn't updated the gitlab repository. it's only take 10 minutes to upload come on

**Comment by minhcasi** [comment]
@RomeoDar - sorry i will update you in minutes - thank you!

**Comment by minhcasi** [comment]
@RomeoDar - it's updated - please help to download the latest code on GitLab

Btw, we are migrating to new ticket support, please help to post your new comment to http://support.inspireui.com/ 

Thank you for your time!
