### ISSUE TITLE
NoSuchMethodError - the getter id was called on null - Fluxstore prestashop payment 

### ISSUE THREAD

**Issue by majedqatousa** [inspireui/support#4955]
+ Detail Issues: 
- [ ] first issue

#### error msg : - 
( NoSuchMethodError - the getter id was called on null )
Fluxstore prestashop v - 1.7.7 last v 
screen :- 

![119083879_694139297843610_5993683831446881718_n](https://user-images.githubusercontent.com/44095809/92679580-7760c880-f331-11ea-80de-f736e0a53191.jpg)

- [ ] 2nd issue
i don't want to see the check payment , write payment and COD on my app  . 
i just want to see the : K-net and cybersource 

thank you

**Comment by minhcasi** [comment]
@majedqatousa - please help to raise your all comments into one open ticket #4883 - thank you!
