### ISSUE TITLE
Could not find com.android.tools:r8:1.5.25.

### ISSUE THREAD

**Issue by rasnza** [inspireui/support#4956]
Could not find com.android.tools:r8:1.5.25.
Searched in the following locations:
  - https://dl.google.com/dl/android/maven2/com/android/tools/r8/1.5.25/r8-1.5.25.pom
  - https://jcenter.bintray.com/com/android/tools/r8/1.5.25/r8-1.5.25.pom
  - http://storage.googleapis.com/r8-releases/raw/com/android/tools/r8/1.5.25/r8-1.5.25.pom
Required by:
    project :

**Comment by minhcasi** [comment]
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support https://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
@rasnza - could i know if you could able to run the Test Drive successful - https://flutter.dev/docs/get-started/test-drive

Please share your detail result form `flutter doctor`

**Comment by rasnza** [comment]
https://snipboard.io/YWw2lk.jpg

**Comment by rasnza** [comment]
i upgraded flutter

**Comment by minhcasi** [comment]
@rasnza - could you able run the Test Drive example successful?

**Comment by rasnza** [comment]
No cached version of com.android.tools:r8:1.5.25 available for offline mode.
Disable Gradle 'offline mode' and sync project

i clicked on Disable Gradle

Could not find com.android.tools:r8:1.5.25.
Searched in the following locations:
  -
https://dl.google.com/dl/android/maven2/com/android/tools/r8/1.5.25/r8-1.5.25.pom
  - https://jcenter.bintray.com/com/android/tools/r8/1.5.25/r8-1.5.25.pom
  -
http://storage.googleapis.com/r8-releases/raw/com/android/tools/r8/1.5.25/r8-1.5.25.pom
Required by:
    project :

**Comment by minhcasi** [comment]
@rasnza - pls try with basic install flutter first - https://flutter.dev/docs/get-started/install

try to resolve the issues from `flutter doctor`

**Comment by rasnza** [comment]
same things ! ...  tried to run flutter doctor
updated my android studio and same error !

**Comment by rasnza** [comment]
same error i tried everything ? please reply

**Comment by minhcasi** [comment]
@rasnza - please try to check this solution, it seems is issues from Android Studio that missing `Android Tool` https://support.inspireui.com/help-center/articles/3/8/69/clean-flutter-cache#android-settings

**Comment by rasnza** [comment]
I tried that didnt fix anything 😞

**Comment by sgjesse** [comment]
HI, I work on the R8 team, and I can see two issues with using R8 version 1.5.25:
-  It is an old the version the current stable used in Android Studio 4.0 is version `2.0.x` and for Android Studio 4.1 it will be `2.1.x`.
- For releases from before November 22 2019 the R8 "maven repo" at http://storage.googleapis.com/r8-releases/raw/ only contains `.jar` files not `.pom` files. Starting from version 1.6.53 the `.pom` files are there as well. See https://r8-review.googlesource.com/c/r8/+/45893 and [issue 144182671](https://issuetracker.google.com/144182671) for more details.

For recent stable releases R8 is also available from the Google Maven repository, see https://maven.google.com/web/index.html#com.android.tools:r8.

I don't know anything about the actual use of R8 in this context, but using the latest stable version is always recommended.

**Comment by rasnza** [comment]
so what should i do now ?

**Comment by rasnza** [comment]
Hello you didnt reply ?
What should i do now to make it work ?

**Comment by sgjesse** [comment]
My comment was mainly background for the InspireUI team. As mentioned I don't know how R8 is unsed in InspireUI, so I cannot help on that. Maybe re-open this issue or file a new one with InspireUI.

**Comment by rasnza** [comment]
K thank you
