### ISSUE TITLE
Mstore API

### ISSUE THREAD

**Issue by HasanHuse** [inspireui/support#4958]
mstore_user: Error: Cannot find controller class 'json_api_mstore_user_controller' (filtered path: /home/customer/www/hasani17.sg-host.com/public_html/wp-content/plugins/mstore-api//controllers/MstoreUser.php).

![Screenshot_2020-09-10 JSON API Settings ‹ GreenCrate — WordPress](https://user-images.githubusercontent.com/11379885/92702274-6ed8b400-f36a-11ea-9752-5b93f2279fd4.png)

**Comment by minhcasi** [comment]
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support https://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by HasanHuse** [comment]
I submitted the form with all required info, please check and let me know.

**Comment by stien** [comment]
Hi, we might be having the same issue. I am updating the app and all of a sudden we are seeing this "json_api_mstore_user_controller" error. Any ideas?

**Comment by minhcasi** [comment]
@HasanHuse @stien - pls try to remove the `json api` plugin as the latest mstore-api will not depend on this plugin - thank you!

**Comment by HasanHuse** [comment]
I removed the Json Api and Json Api Auth plugin and setup the app as describe in the above link but products are not fetching in the app. Any suggestion?

**Comment by stien** [comment]
﻿Hi. I did that before I reached out. The error disappears, but nothing happens now. Animation Just spins for a Few seconds then nothing. 

Excuse any iPhone shorthand



Excuse any iPhone shorthand

**Comment by HasanHuse** [comment]
Issue resolved and now its working fine at me end.

@stien delete Json API plugins then validate the MStore with purchase code. Then you need to follow this https://docs.inspireui.com/mstore/wordpress-setting/.

Also make sure your website has valid purchased SSL certificate installed.

**Comment by stien** [comment]
﻿Ok. I will try that process. Our app has been on apple and google play for a year now. We didn’t make any updates that would have caused this. We only found out because were testing a planned update. 

I will try this and get back to you. Thank you. 

Excuse any iPhone shorthand



Excuse any iPhone shorthand

**Comment by minhcasi** [comment]
@stien - Let me ask my team to send your previous mstore-api with compatible with json API so that you don't need to release the app again, or if you have the backend of that plugin on please try to revert.

**Comment by minhcasi** [comment]
@HasanHuse - pls share the screenshot of the missing product issues so that i could raise to the team for fixing
