### ISSUE TITLE
Mobile Case model Checkout problem

### ISSUE THREAD

**Issue by surendranekkanti188** [inspireui/support#4959]
Step 1 (require): describe detail issues & screenshots
Detail Issues:
 Mobile case model changes while checking out.
Product & version:
Flutter (or React Native) version: 1.1.7
Testing Device/Simulator: Pixel 3A
Screenshot issues (drag the file to attach here):

Hi in mobile cases we have selected Apple Iphone 8 model, but in checkout page it is changing automatically to XIAOMI REDMI Y2. Please have a look, I think it's a bug. Waiting for solution.

![1](https://user-images.githubusercontent.com/69853255/92714704-643e0080-f311-11ea-9e66-43e6dac726c9.jpg)
![2](https://user-images.githubusercontent.com/69853255/92714719-6738f100-f311-11ea-926f-e813ad9c2c08.jpg)
![3](https://user-images.githubusercontent.com/69853255/92714724-6acc7800-f311-11ea-8a47-d06065513d35.jpg)

**Comment by surendranekkanti188** [comment]
waiting for your response.

**Comment by minhcasi** [comment]
@surendranekkanti188 - we have tested this issue and it is working fine on our side, could you share the admin login the consumse/secret key that you are using on the app to email inspireui.team@gmail.com - thank you!

**Comment by surendranekkanti188** [comment]
Hi i have sent my login credentials and keys too. Check your mail.

**Comment by simonpham** [comment]
Hi @surendranekkanti188,

I have checked with your latest consumer keys and also checked with your last sent common/config folders.
I cannot reproduce this issue.

Please uninstall the app from the devices, run `flutter clean`, then run the app again.
If the problem still exists, please run `flutter clean` and send your full project to `simon@inspireui.com`. I will check it.

Thank you!

**Comment by surendranekkanti188** [comment]
I did flutter clean but Problem not solved. I have sent project files your mail id. please have a look.

**Comment by simonpham** [comment]
Hi @surendranekkanti188,

I have checked and found a bug in our implementation which doesn't handle product which have more than 100 variations
Please copy the code of this method and replace with the one in `lib/services/woo_commerce.dart`
<details><summary>Click to show code

</summary>
<p>

```dart
  @override
  Future<List<ProductVariation>> getProductVariations(Product product,
      {lang = 'en'}) async {
    try {
      List<ProductVariation> list = [];
      int page = 1;

      while (true) {
        String endPoint =
            "products/${product.id}/variations?per_page=100&page=$page";
        if (kAdvanceConfig["isMultiLanguages"]) {
          endPoint += "&lang=$lang";
        }

        printLog("simon load $page $endPoint");
        var response = await wcApi.getAsync(endPoint);
        if (response is Map && isNotBlank(response["message"])) {
          throw Exception(response["message"]);
        } else {
          if (response is List && response.isEmpty) {
            /// No more data.
            break;
          }
          for (var item in response) {
            if (item['visible']) {
              list.add(ProductVariation.fromJson(item));
            }
          }

          /// Fetch next page.
          page++;
        }
      }

      return list;
    } catch (e) {
      //This error exception is about your Rest API is not config correctly so that not return the correct JSON format, please double check the document from this link https://docs.inspireui.com/fluxstore/woocommerce-setup/
      rethrow;
    }
  }
```

</p>
</details>

We will include this fix in a future version.
About the issue that the product variant disappears from the cart, please update to our latest FluxStore version which already fixed the issue.

Thank you for your support!

**Comment by surendranekkanti188** [comment]
Thank you problem solved.
