### ISSUE TITLE
[MStore] Default rtl issue

### ISSUE THREAD

**Issue by ElegantSoft** [inspireui/support#496]
MStore
8b86468a-13a0-49b3-afb2-68a30e59cb2f

I have set 
 DefaultCountry: {
    code: "ar",
    RTL: true,
    language: "Arabic",
    countryCode: "SA",
    hideCountryList: true, // when this option is try we will hide the country list from the checkout page, default select by the above 'countryCode'
  },

 Constants = {
  RTL: true, // default to set redux. Only use first time
  useReactotron: true,
  Language: "ar", // ar, en. Default to set redux. Only use first time

and the app still ltr and english 
when switch language it works fine 
but I need it to be rtl from the first time 
please help

**Comment by luyx2412** [comment]
HI @ElegantSoft When you changed default config file, please uninstall app and reinstall again to clear cache store.

Thanks

**Comment by ElegantSoft** [comment]
Hey
I already done that many times 
and after many tries I edit App.js 
 // set default Language for App
    Languages.setLanguage('ar');

    // Enable for mode RTL
    I18nManager.forceRTL(true);

And the rtl not working at the first time and when close and open app again it works
so the user should close and reopen app after install 

I  Submit this issue before and not get any solutions please help

**Comment by ElegantSoft** [comment]
Hey I found the solution 
in MainApplication.java
add 
public void onCreate() {
super.onCreate();
I18nUtil sharedI18nUtilInstance = I18nUtil.getInstance();
sharedI18nUtilInstance.forceRTL(this,true);
sharedI18nUtilInstance.allowRTL(this, true);
}
this will solve the problem 

MStore team you need to be more awareness and take time to improve the app thank you

**Comment by luyx2412** [comment]
Hi @ElegantSoft Thanks a lot your feedbacks and solution. Let we note and improve next version.

Thanks

**Comment by saeidAalizade** [comment]
> Hey I found the solution
> in MainApplication.java
> add
> public void onCreate() {
> super.onCreate();
> I18nUtil sharedI18nUtilInstance = I18nUtil.getInstance();
> sharedI18nUtilInstance.forceRTL(this,true);
> sharedI18nUtilInstance.allowRTL(this, true);
> }
> this will solve the problem
> 
> MStore team you need to be more awareness and take time to improve the app thank you

hi @ElegantSoft This problem is in ios How did you fix it?
