### ISSUE TITLE
Caching json files for non english languages

### ISSUE THREAD

**Issue by nucl123** [inspireui/support#4960]
Hi,
1. How can we add non english languages to caching on the server?
currently, if we setup translations in the local files like config_ar etc 
and enable caching, everything gets over written by main english config_en file,
once the app loads.Please suggest a solution.

2. Also please update if non cash on delivery payment gateway for prestashop app,
we had already purchased it too, but looking forward for a webview check out option

Best Regards

**Comment by minhcasi** [comment]
1. multi-languages file caching will be supported on next `1.7.8` (for woocommerce only)
2. the checkout payment webview on prestashop if not available on the current release, we will upgrade it in the future.

**Comment by nucl123** [comment]
Hi,
1. So, please let us know the solution / code snippet to prevent over writing the other languages json file, by English json file, when the caching is enabled, and expected release date of 1.7.8

2. Can you integrate a gateway as a paid service.

**Comment by minhcasi** [comment]
we will clarify detail on the changelog when releasing 1.7.8 on next week 👍 

sorry, we are not supporting for paid service at this time, thank you for your queries.

**Comment by minhcasi** [comment]
Please move new conversation to new Ticket Support http://support.inspireui.com - thank you!

**Comment by minhcasi** [comment]
Please move new conversation to new Ticket Support http://support.inspireui.com - thank you!
