### ISSUE TITLE
TapConfig configuration problem

### ISSUE THREAD

**Issue by MH-sabu** [inspireui/support#4961]
I am trying to implement Bangladeshi  sslcommerz payment gateway.

 But I do not understand how to configure tapconfig . Means what would be secret key , redirect url and payment method. Thanks
![WhatsApp Image 2020-09-10 at 9 39 17 PM](https://user-images.githubusercontent.com/14260461/92757835-ee3ca680-f3af-11ea-88c8-26a485bee981.jpeg)

**Comment by minhcasi** [comment]
you could get the secretKey from Tap Dashboard, pls read this guide https://www.tap.company/kw/en/developers

You could let the redirect URL as original

**Comment by MH-sabu** [comment]
Is there any other way to add sslcommerz( https://developer.sslcommerz.com/) , a Bangladeshi payment gateway. thanks @minhcasi

**Comment by minhcasi** [comment]
You could try with the Webview solution from the app
