### ISSUE TITLE
Apple Login Issue in FLuxstore Woocommerce

### ISSUE THREAD

**Issue by FaizalAndro** [inspireui/support#4962]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
- [ ] first issue: Apple Login Issue
- [ ] second issue
- [ ] third issue

+ Product & version: 1.7.7
+ Flutter (or React Native) version: Flutter
+ Testing Device/Simulator: Both
+ Screenshot issues (drag the file to attach here): 
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-09-11 at 01 10 41](https://user-images.githubusercontent.com/37078576/92794642-5ea5f080-f3cd-11ea-9bea-087f234c3dc2.png)

**_Step 2 (require): submit proof of purchasing the license on https://verify.inspireui.com **

Previous Ticket Number 4143

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@FaizalAndro - could i know if you have enabled this option on the Firebase - https://tppr.me/P6cwm ?

**Comment by FaizalAndro** [comment]
Yes I enabled already

**Comment by minhcasi** [comment]
it seems the exception from Firebase library, pls check the bug solution on this guide as well (it could cause by your apple id, make sure run on real device) - https://docs.inspireui.com/fluxstore/sign-in/#4-apple-sign-in

**Comment by FaizalAndro** [comment]
I tested it with both emulator and real device same error occured

**Comment by qozia3** [comment]
i have the same issue! i have done everything correctly

**Comment by qozia3** [comment]
when i use apple login i get this error message
<img width="1269" alt="Screen Shot 2020-09-13 at 8 05 24 PM" src="https://user-images.githubusercontent.com/69852582/93026426-8fc13380-f60e-11ea-9fed-c336210226a2.png">

**Comment by qozia3** [comment]
guys i found the solution.
go to firebase after doing all the stuff inspireui mentioned.

then create a new database.

change the rules to true for READ and WRITE to TRUE


thats it.



<img width="1613" alt="Screen Shot 2020-09-13 at 10 26 43 PM" src="https://user-images.githubusercontent.com/69852582/93026649-4b369780-f610-11ea-8f7e-e26d7938a9c1.png">

**Comment by FaizalAndro** [comment]
@qozia3 , Is Realtime database related to Apple Auth? Anyways I m using fluxstore woocomerce, I think in that there is no need to setup that

**Comment by qozia3** [comment]
> @qozia3 , Is Realtime database related to Apple Auth? Anyways I m using fluxstore woocomerce, I think in that there is no need to setup that

Yes Faisal. 
It's important to do what I wrote. 
I just fixed it now. 
Apple Auth is register in firebase database. 

Please enable Apple from firebase settings then create a database and set both read and right to true. 

After you do that It will work 👍 I have woocommerce too

**Comment by qozia3** [comment]
@minhcasi please include my solution in the offecial documentation.
I think after 30 days firebase will lock the firebase

**Comment by FaizalAndro** [comment]
> > @qozia3 , Is Realtime database related to Apple Auth? Anyways I m using fluxstore woocomerce, I think in that there is no need to setup that
> 
> Yes Faisal.
> It's important to do what I wrote.
> I had the same issue as you.
> I just fixed it now.
> Apple Auth info such as email and name is registered in the firebase database.
> 
> Please enable Apple from firebase settings under sign in methods then create a database and set both read and write to true.
> 
> After you do that It will work 👍 I have woocommerce too

Not working @minhcasi Please resolve this apple login issue. Thank you

**Comment by Golambal** [comment]
> guys i found the solution.
> go to firebase after doing all the stuff inspireui mentioned.
> 
> then create a new database.
> 
> change the rules to true for READ and WRITE to TRUE
> 
> thats it.
> 
> <img alt="Screen Shot 2020-09-13 at 10 26 43 PM" width="1613" src="https://user-images.githubusercontent.com/69852582/93026649-4b369780-f610-11ea-8f7e-e26d7938a9c1.png">

Thank you this worked for me

> guys i found the solution.
> go to firebase after doing all the stuff inspireui mentioned.
> 
> then create a new database.
> 
> change the rules to true for READ and WRITE to TRUE
> 
> thats it.
> 
> <img alt="Screen Shot 2020-09-13 at 10 26 43 PM" width="1613" src="https://user-images.githubusercontent.com/69852582/93026649-4b369780-f610-11ea-8f7e-e26d7938a9c1.png">

Thank you this worked!

**Comment by Golambal** [comment]
> > > @qozia3 , Is Realtime database related to Apple Auth? Anyways I m using fluxstore woocomerce, I think in that there is no need to setup that
> > 
> > 
> > Yes Faisal.
> > It's important to do what I wrote.
> > I had the same issue as you.
> > I just fixed it now.
> > Apple Auth info such as email and name is registered in the firebase database.
> > Please enable Apple from firebase settings under sign in methods then create a database and set both read and write to true.
> > After you do that It will work 👍 I have woocommerce too
> 
> Not working @minhcasi Please resolve this apple login issue. Thank you

 

> guys i found the solution.
> go to firebase after doing all the stuff inspireui mentioned.
> 
> then create a new database.
> 
> change the rules to true for READ and WRITE to TRUE
> 
> thats it.
> 
> <img alt="Screen Shot 2020-09-13 at 10 26 43 PM" width="1613" src="https://user-images.githubusercontent.com/69852582/93026649-4b369780-f610-11ea-8f7e-e26d7938a9c1.png">

Thank u This work good

**Comment by Golambal** [comment]
> > > @qozia3 , Is Realtime database related to Apple Auth? Anyways I m using fluxstore woocomerce, I think in that there is no need to setup that
> > 
> > 
> > Yes Faisal.
> > It's important to do what I wrote.
> > I had the same issue as you.
> > I just fixed it now.
> > Apple Auth info such as email and name is registered in the firebase database.
> > Please enable Apple from firebase settings under sign in methods then create a database and set both read and write to true.
> > After you do that It will work 👍 I have woocommerce too
> 
> Not working @minhcasi Please resolve this apple login issue. Thank you

This work for me. 
You must be bad programmer hahahhaah

**Comment by FaizalAndro** [comment]
Hi @minhcasi, Please resolve this Apple Login issue. It's been 4 days but didn't get any solution, I need to push app on app store. Help! Thank you

**Comment by minhcasi** [comment]
@FaizalAndro - you could try to revoke your Apple login on your iphone to test this feature

🐞Bug Login: revoke the account access on your iOS device if could not login on Fluxstore, by opening the Setting on iOS in your iPhone and tap on your name at the top, press Password & Security, then you could see list the Apps that using Apple ID, you can delete any of them to revoke access

Also try to update the Firebase Rule as suggest from qozia3

Try your best, Thank you!

**Comment by FaizalAndro** [comment]
Thanks revoke apple id resolve my issue, I have one more question regarding facebook login. Should I need to create two developer apps separately for setup android and ios FB login, if yes then I should need to create separate firebase specially for facebook login

**Comment by minhcasi** [comment]
you could create 1 facebook app and config for both ios+android, the same fore firebase (just one)

**Comment by FaizalAndro** [comment]
Hi @minhcasi , When I archive for upload app in app store. I m facing this error "ld: bitcode bundle could not be generated because '/Volumes/Macintosh HD - Data/source/ios/Flutter/Flutter.framework/Flutter' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file '/Volumes/Macintosh HD - Data/source/ios/Flutter/Flutter.framework/Flutter' for architecture armv7"

**Comment by minhcasi** [comment]
Please check to select the product Target - From `Build Settings > Enable Bitcode` to `No`

**Comment by FaizalAndro** [comment]
It already selected by default NO 
![Screenshot 2020-09-17 at 8 59 13 PM](https://user-images.githubusercontent.com/37078576/93492720-bd68ee00-f928-11ea-9a1c-1b6d371964ca.png)

**Comment by minhcasi** [comment]
try to check the onesignalNotification Target and Pods as well

**Comment by FaizalAndro** [comment]
I changed the target didn't work issue is in flutter webview...
![Screenshot 2020-09-18 at 11 56 24 AM](https://user-images.githubusercontent.com/37078576/93563698-0b700700-f9a6-11ea-84a7-aeed29618fbb.png)

**Comment by minhcasi** [comment]
You could try this solution to clean up the Pod cache - https://support.inspireui.com/help-center/articles/3/8/69/common-flutter-issues 

```
pod cache clean --all
pod repo update 
pod update
pod install
```

Note: we have this error in the past but fixed well by this solution. Please move your next comment to our new ticket support https://support.inspireui.com/ - thanks
