### ISSUE TITLE
Error When Build the app, Cannot Run

### ISSUE THREAD

**Issue by zahidahamed** [inspireui/support#4963]
m having the following error when run the app, i have updated everything as you guided, please help me to rid of this error

Invalid depfile: D:\buymobile android app\codecanyon-kcqZITR4-fluxstore-woocommerce-flutter-ecommerce-full-app\FluxStore-woo-1.7.7\source.dart_tool\flutter_build\be1b65a3fb32cde159db98579dd065fa\kernel_snapshot.d
Invalid depfile: D:\buymobile android app\codecanyon-kcqZITR4-fluxstore-woocommerce-flutter-ecommerce-full-app\FluxStore-woo-1.7.7\source.dart_tool\flutter_build\be1b65a3fb32cde159db98579dd065fa\kernel_snapshot.d
Error: Could not resolve the package 'firebase_admob' in 'package:firebase_admob/firebase_admob.dart'.
lib/models/advertisement.dart:2:8: Error: Not found: 'package:firebase_admob/firebase_admob.dart'
import 'package:firebase_admob/firebase_admob.dart';
^
lib/models/advertisement.dart:9:10: Error: Type 'InterstitialAd' not found.
static InterstitialAd _interstitialAd;
^^^^^^^^^^^^^^
lib/models/advertisement.dart:10:10: Error: Type 'BannerAd' not found.
static BannerAd _bannerAd;
^^^^^^^^
lib/models/advertisement.dart:11:10: Error: Type 'MobileAdTargetingInfo' not found.
static MobileAdTargetingInfo _targetingInfo;
^^^^^^^^^^^^^^^^^^^^^
lib/models/advertisement.dart:12:3: Error: Type 'BannerAd' not found.
BannerAd myBanner;
^^^^^^^^
lib/models/advertisement.dart:72:10: Error: Type 'BannerAd' not found.
static BannerAd createBannerAd() {
^^^^^^^^
lib/models/advertisement.dart:102:10: Error: Type 'InterstitialAd' not found.
static InterstitialAd createInterstitialAd() {
^^^^^^^^^^^^^^
lib/models/user/user_model.dart:13:1: Error: 'User' is imported from both 'package:firebase_auth/firebase_auth.dart' and 'package:fstore/models/user/user.dart'.
import 'user.dart';
^^^^
lib/screens/users/registration.dart:9:1: Error: 'User' is imported from both 'package:firebase_auth/firebase_auth.dart' and 'package:fstore/models/user/user.dart'.
import '../../models/user/user_model.dart';
^^^^
lib/models/advertisement.dart:9:10: Error: 'InterstitialAd' isn't a type.
static InterstitialAd _interstitialAd;
^^^^^^^^^^^^^^
lib/models/advertisement.dart:10:10: Error: 'BannerAd' isn't a type.
static BannerAd _bannerAd;
^^^^^^^^
lib/models/advertisement.dart:11:10: Error: 'MobileAdTargetingInfo' isn't a type.
static MobileAdTargetingInfo _targetingInfo;
^^^^^^^^^^^^^^^^^^^^^
lib/models/advertisement.dart:12:3: Error: 'BannerAd' isn't a type.
BannerAd myBanner;
^^^^^^^^
lib/models/advertisement.dart:52:7: Error: Getter not found: 'FirebaseAdMob'.
FirebaseAdMob.instance.initialize(
^^^^^^^^^^^^^
lib/models/advertisement.dart:55:30: Error: Method not found: 'MobileAdTargetingInfo'.
_targetingInfo = const MobileAdTargetingInfo(
^^^^^^^^^^^^^^^^^^^^^
lib/models/advertisement.dart:81:15: Error: Getter not found: 'AdSize'.
size: AdSize.smartBanner,
^^^^^^
lib/models/advertisement.dart:82:20: Error: 'MobileAdEvent' isn't a type.
listener: (MobileAdEvent event) {
^^^^^^^^^^^^^
lib/models/advertisement.dart:74:14: Error: Method not found: 'BannerAd'.
return BannerAd(
^^^^^^^^
lib/models/advertisement.dart:93:34: Error: Getter not found: 'AnchorType'.
_bannerAd.show(anchorType: AnchorType.bottom);
^^^^^^^^^^
lib/models/advertisement.dart:108:22: Error: 'MobileAdEvent' isn't a type.
listener: (MobileAdEvent event) {
^^^^^^^^^^^^^
lib/models/advertisement.dart:104:14: Error: Method not found: 'InterstitialAd'.
return InterstitialAd(
^^^^^^^^^^^^^^
lib/models/advertisement.dart:123:23: Error: Getter not found: 'AnchorType'.
anchorType: AnchorType.bottom,
^^^^^^^^^^
lib/models/advertisement.dart:138:7: Error: Getter not found: 'RewardedVideoAd'.
RewardedVideoAd.instance.load(
^^^^^^^^^^^^^^^
lib/models/advertisement.dart:145:15: Error: Getter not found: 'RewardedVideoAd'.
await RewardedVideoAd.instance.show();
^^^^^^^^^^^^^^^
lib/models/user/user_model.dart:112:73: Error: Too few positional arguments: 1 required, 0 given.
AuthCredential credential = FacebookAuthProvider.getCredential(
^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth_platform_interface-2.0.1/lib/src/providers/facebook_auth.dart:92:25: Context: Found this candidate, but the arguments don't match.
static AuthCredential getCredential(String token) {
^^^^^^^^^^^^^
lib/models/user/user_model.dart:183:18: Error: 'User' is imported from both 'package:firebase_auth/firebase_auth.dart' and 'package:fstore/models/user/user.dart'.
user = User.fromLocalJson(json);
^^^^
lib/tabbar.dart:183:43: Error: 'currentUser' isn't a function or method and can't be invoked.
final user = await _auth.currentUser();
^^^^...
lib/screens/users/login_sms/index.dart:143:51: Error: 'AuthException' isn't a type.
final PhoneVerificationFailed veriFailed = (AuthException exception) {
^^^^^^^^^^^^^
U
nhandled exception:
FileSystemException(uri=org-dartlang-untranslat
able-uri:package%3Afirebase_admob%2Ffirebase_admob.dart; message=StandardFileSystem only supports file:* and data:* URIs)
#0 StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:33:7)
#1 asFileUri (package:vm/kernel_f
ront_end.dart:659:37)

#2 writeDepfile (package:vm/kernel_front_end.dart:
853:21)

#3 FrontendCompiler.compile (package:frontend_server/frontend_server.dart:574:15)

#4 _FlutterFrontendCompiler.compile (package:flutter_frontend_serv
e
r/server.dart:43:22)
#5 starter (package:flutter_frontend_server/server.dart:182:27)
#6 main (file:///C:/b/s/w/ir/cache/builder/src/flutter/flutter_frontend
_server/bin/starter.dart:9:30)
#7 _startIsolate. (dart:isolate-patch/isolate_patch.dart:299:32)
#8
_RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

FAILURE: Build failed with an exception.

Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 896

What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.

Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

Get more help at https://help.gradle.org

BUILD FAILED in 2m 44s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by minhcasi** [comment]
@zahidahamed - could I know if you have clean up the cache - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1 and also run `flutter pub get` to update the library?

Pls make sure to use the latest flutter channel stable `flutter channel stable`
