### ISSUE TITLE
REST API problem

### ISSUE THREAD

**Issue by nugrohomagfi** [inspireui/support#4964]
Hallo! I bought Fluxstore woocommerce on august. And I have an issue in CK & CS REST API connectivity in fluxbuilder. I have put the key correctly and nothing happen. Then I change .htaccess file like in flux docs and nothing happen. Please help me. Thank you.

![Screen Shot 2020-09-11 at 14 12 24](https://user-images.githubusercontent.com/71120238/92881232-fc82d500-f438-11ea-9ba9-e3ec42426c28.png)

![Screen Shot 2020-09-11 at 14 12 38](https://user-images.githubusercontent.com/71120238/92881304-0d334b00-f439-11ea-859f-f1aa803e9904.png)

**Comment by minhcasi** [comment]
@nugrohomagfi - You have to authenticate to get responses from the WooCommerce REST API. Please check these solutions:

See: http://woocommerce.github.io/woocommerce-rest-api-docs/#authentication
and: https://github.com/woocommerce/woocommerce/wiki/Getting-started-with-the-REST-API

**Comment by surendranekkanti188** [comment]
Can you make a detailed video about this? it would be helpful.

**Comment by minhcasi** [comment]
@surendranekkanti188 - this API issue could cause by many reasons from your hosting, please give a try to reinstall WordPress sometime could be fixed - we will make video for this issue later - thank you!
