### ISSUE TITLE
Bug in the apps

### ISSUE THREAD

**Issue by bigjuju4fr** [inspireui/support#4967]
Hello,

i found a new bug in the apps. when ordering a single product, if you remove the product in the review tab, then there is no product to order but the apps still gives you the possibility to order a non existing product. please see the below screenshot:

<img width="418" alt="bug1" src="https://user-images.githubusercontent.com/69798792/92932063-ad42a180-f444-11ea-867e-2464138b8659.png">
<img width="418" alt="bug2" src="https://user-images.githubusercontent.com/69798792/92932067-ae73ce80-f444-11ea-8040-6461a500971e.png">
<img width="418" alt="bug3" src="https://user-images.githubusercontent.com/69798792/92932070-af0c6500-f444-11ea-9f8a-a56b4d82ba0d.png">
<img width="418" alt="bug4" src="https://user-images.githubusercontent.com/69798792/92932072-af0c6500-f444-11ea-8b54-0a1596bb3506.png">

How to avoid that? when there is no product available, no payment could be possible.
Please help.
Thanks.

Best

**Comment by minhcasi** [comment]
noted with investigating - thank you!

**Comment by minhtruong315** [comment]
Hi @bigjuju4fr We fixed this issue. it'll be available in next release.
But you will tell you how to fix it.
Open file screens/checkout/review.dart, find ```List<Widget> getProducts(CartModel model, BuildContext context)``` function, then remove onRemove and onChangeQuantity in ShoppingCartRow

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
