### ISSUE TITLE
Shipping and payment options issue (opencart)

### ISSUE THREAD

**Issue by digital0life** [inspireui/support#4969]
Hello,
Im facing issues configuring the Shipping and Payment in app. Shipping options are enabled with the website but facing issues with app.

no shipping appears.. i try to remove the extension and install it again but not work it give me as below 

{"success":1,"error":[],"data":{"error_warning":"Warning: No Shipping options are available. Please contact us<\/a> for assistance!","shipping_methods":[],"code":"","comment":""}}

Please advice

**Comment by digital0life** [comment]
Hello ..is there any update 

Opencart ver 3.0.3.6
App ver 1.7.4

**Comment by minhtruong315** [comment]
Hi @digital0life can u try to install this mstore extension? let me know the result
[mstore.ocmod.zip](https://github.com/inspireui/support/files/5212814/mstore.ocmod.zip)

**Comment by minhtruong315** [comment]
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!
