### ISSUE TITLE
[ListApp] WP Job Manager 1.32 Support

### ISSUE THREAD

**Issue by williamoconnorme** [inspireui/support#497]
**Required Info (please complete the following information):**
- Product: ListApp
- Your Purchased Code: Item Purchase Code:
2c0cab07-d2d3-4461-94ab-de84f438db97

**Describe the bug**
After upgrading from WP Job Manager 1.31.3 to 1.32.2, the rest routes to the job_listing endpoint no longer work

**Comment by williamoconnorme** [comment]
For anyone looking for a fix, I've found editing App/Services/WPAPI.js file 

You'll want to change the references to /job_listing to /job-listings

**Comment by iqmtgar** [comment]
Can you explain more please?
I apologize for a weak English
What can I write here? App/Services/WPAPI.js
now this >
import WordpressApi from './WordpressApi'
import { AppConfig } from '@common'

var Api = new WordpressApi({
  url: AppConfig.Website.url,
  logo: '',
})

export default Api

**Comment by williamoconnorme** [comment]
Below is my updated WPAPI.js file. I'm using ListApp version 1.6.1

```
/** @format */

import WPAPI from 'wpapi'
import { AppConfig, Constants, warn } from '@common'
var wpApi = new WPAPI({
  endpoint: AppConfig.Website.url + '/wp-json',
})

var namespace = 'wp/v2' // use the WP API namespace
var namespaceConfig = 'inspireui/v1' // use the WP API namespace
var namespaceListing = 'listing/v1' // use the WP API namespace
var namespaceGetTags = 'tags/v1' // use the WP API for get Tags
var namespaceSearch = 'search/v1' // use the WP API for get Tags
wpApi.getJobListing = wpApi.registerRoute(namespace, '/job-listings/(?P<id>)', {
  params: [
    'per_page',
    'page',
    'before',
    'after',
    'author',
    'include',
    'exclude',
    'job_listing_category',
    'job_listing_type',
    'region',
    'case27_job_listing_tags',
    'job_listing_region',
    'search',
    'limit',
    'status',
  ],
})

wpApi.getPhotos = wpApi.registerRoute(namespace, '/media/(?P<id>)', {
  params: ['per_page', 'page', 'status', 'media_type', 'mime_type'],
})

wpApi.getJobListingCategory = wpApi.registerRoute(
  namespace,
  '/job_listing_category/(?P<id>)',
  {
    params: ['per_page', 'page', 'status', 'parent', 'hide_empty'],
  }
)

wpApi.getRating = wpApi.registerRoute(namespace, '/getRating/(?P<id>)')

wpApi.posts = wpApi.registerRoute(namespace, '/posts/(?P<id>)', {
  params: [
    'search',
    'per_page',
    'page',
    'before',
    'after',
    'author',
    'include',
    'exclude',
    'categories',
    'status'
  ],
})

wpApi.getListingTool = wpApi.registerRoute(namespaceListing, '/job-listings', {
  params: ['per_page', 'status', 'page', 'type', 'limit'],
})

wpApi.getListingByTags = wpApi.registerRoute(namespaceGetTags, '/job-listings', {
  params: ['per_page', 'tag', 'page', 'limit'],
})

//for myListing link
wpApi.getCase27ListingTags = wpApi.registerRoute(
  namespaceListing,
  '/case27_job_listing_tags'
)
wpApi.getAllCategories = wpApi.registerRoute(
  namespace,
  '/job_listing_category',
  {
    params: ['hide_empty', 'per_page'],
  }
)
wpApi.getListingTypes = wpApi.registerRoute(namespace, '/case27_listing_type')
wpApi.getFilter = wpApi.registerRoute(namespaceSearch, '/job-listings', {
  params: [
    'search', // by keyword
    'page',
    'tags', //for myListing
    'categories',
    'type', //for myListing
    'regions', //for listify
    'typeListable', // for listable
    'limit',
    'status'
  ],
})

wpApi.getFilterNearest = wpApi.registerRoute(namespaceSearch, '/job_listing', {
  params: ['isGetLocate', 'lat', 'long'],
})
//for listify link
wpApi.getAllRegions = wpApi.registerRoute(namespace, '/job_listing_region')
//for listable
wpApi.getTypesListable = wpApi.registerRoute(namespace, '/job_listing_type')

wpApi.getConfig = wpApi.registerRoute(namespaceConfig, '/config')

export default wpApi

```

**Comment by iqmtgar** [comment]
sir Can you help me through teamviewer
please
please
please :)

**Comment by thangvo9x** [comment]
Hi. @williamoconnorme. Which templates are you using, plz? We saw our app has work with WP Job Manager 1.3

Hi. @iqmtgar  Please create a ticket if you need a support.

**Comment by williamoconnorme** [comment]
Hi @thangvo9x the template I am using is Listify 2.10.1 and WP Job Manager 1.13.2

Your demo site appears to be using WP Job Manager 1.29.3

http://listify.inspireui.com/wp-content/plugins/wp-job-manager/changelog.txt

**Comment by thangvo9x** [comment]
Hi @williamoconnorme . I update to latest version of WP Job Manager but our url for rest api has been job_listing.

**Comment by williamoconnorme** [comment]
I'm not quite sure why but the Listify Demo site from Astoundify and even my own site, have different routes. Please see the links below as an example:

Route exists: https://listify-demos.astoundify.com/classic/wp-json/wp/v2/job-listings

Route doesn't exist: https://listify-demos.astoundify.com/classic/wp-json/wp/v2/job_listing

Route Exists: http://listify.inspireui.com/wp-json/wp/v2/job_listing

Route doesn't exist: http://listify.inspireui.com/wp-json/wp/v2/job-listings
