### ISSUE TITLE
Unable to Login 

### ISSUE THREAD

**Issue by umargigani** [inspireui/support#4970]
So i Already raised issue when i was using opencart issue ID https://github.com/inspireui/support/issues/4066

We have now switched form Opencart to WooCommerce 

and i am facing login issue i tried everything
but when i try to login it says Username and password incorrect

But i created account from the app it gets login and  after i logout and try to login it says same issue
i disabled captche
disabled cache

same issue

![issue 1 woo](https://user-images.githubusercontent.com/22342007/92946558-75535280-f474-11ea-8b6f-6a2994db3389.png)

**Comment by minhcasi** [comment]
@umargigani - could i know if you have followed the guide to active the plugins on this document https://docs.inspireui.com/fluxstore/woocommerce-setup/ - thank you!

**Comment by minhcasi** [comment]
Also, try to check if your woocommerce Rest API is working fine by using fluxbuilder tool  - http://fluxbuilder.com/

**Comment by umargigani** [comment]
yes i followed every step ( i skip only product import step as i dont want any  demo products to be imported i already had full store )
reset i followed everything
have latest mstore api linked with my purchase code
yes all connections are working fine

same login issue with fluxbuilder

![connections](https://user-images.githubusercontent.com/22342007/92986114-1c1c0b00-f4d6-11ea-8b4f-943190fae158.png)
![same issue](https://user-images.githubusercontent.com/22342007/92986116-1cb4a180-f4d6-11ea-9fdf-eb29cb1a26b3.png)

**Comment by minhcasi** [comment]
@umargigani - could i know if you have installed opencart extension on your site?

**Comment by umargigani** [comment]
no we switched from opencart to woocommerce

**Comment by minhcasi** [comment]
@umargigani - please note that the login form Fluxstore will not work on the Fluxbuilder, but you could try to test from your simulator when running Fluxstore app

Let us know if you have any question

**Comment by umargigani** [comment]
yes i attached screenshots above its not working on emulator as well 
please read above messages sir 

I AM USING WOOCOMMERCE AND LOGIN IS NOT WORKING 

on emulator or on device

**Comment by minhcasi** [comment]
@umargigani - could you try to follow this guide to set the pre-config site on this link https://docs.inspireui.com/fluxstore/woocommerce-setup/#1-website-integration - we have set up all ready config that works well with the app - thanks

**Comment by umargigani** [comment]
yes i followed every step from the guide still not working i retried 2 -3 times everything was getting skiped as my store is completely pre configured

**Comment by umargigani** [comment]
any updates

**Comment by umargigani** [comment]
no support available ? its been 9 days

**Comment by minhcasi** [comment]
moved
