### ISSUE TITLE
iOS: UIWebView are no longer accepted - Deprecated API Usage

### ISSUE THREAD

**Issue by gunero** [inspireui/support#4971]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 

Can't upload the FluxNews iOS version, because the API is deprecated. Need to change it to WKWebView.

I searched for similar issues before, but couldn't find a definite answer.

+ Product & version: 1.4.1
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: iOS
+ Screenshot issues (drag the file to attach here): 

<img width="666" alt="Bildschirmfoto 2020-09-11 um 17 52 26" src="https://user-images.githubusercontent.com/66735847/92946980-b0935880-f457-11ea-89fb-067e0a741e93.png">

**_Step 2 (require): submit proof of purchasing the license on https://verify.inspireui.com **

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by gunero** [comment]
Just submitted the proof of purchasing. Looking forward to getting this issue fixed asap.

**Comment by minhcasi** [comment]
@gunero - pls try to update the latest Fluxnews `1.4.3` and use with latest Flutter Channel stable `1.20.x`

**Comment by gunero** [comment]
Hi, any other method? My app is already fully customized (colors, screens etc.) and updating to the new version would reset everything and basically I would have to start all over again.

**Comment by minhcasi** [comment]
@gunero - you could try to merage with the latest code by using this guide https://medium.com/@inspireui/how-to-upgrade-fluxstore-projects-by-using-git-cebde7489ea6
