### ISSUE TITLE
Ads management on FluxNews

### ISSUE THREAD

**Issue by Tatslamenace** [inspireui/support#4972]
**No documentation to set up properly the rules regarding ads**
Interstitial
Banner on page
Etc..

**Comment by minhcasi** [comment]
@Tatslamenace - we are working to update more detail for the document, please share which section you would like to upgrade so that we could explain more detail on the document - https://docs.inspireui.com/fluxnews

**Comment by dttrung26** [comment]
Hi @Tatslamenace ,
please double check our Advertisement Configuration Docs: https://support.inspireui.com/help-center/articles/11/13/33/admob-and-facebook-ads
Best!

**Comment by dttrung26** [comment]
If you have other issues, please refer our support services migration. 
I'm gonna close the ticket then.
