### ISSUE TITLE
Payment Page

### ISSUE THREAD

**Issue by hltyvz** [inspireui/support#4973]
I use the paytr payment method on my woocommerce website.

The payment screen does not work in the application. When I enter the card information and confirm it, there is no transaction.

Order tab does not open in Fluxbuilder. : https://ibb.co/1RC1q12
When I check the connection, there is no error.

When I do NativeOnePageCheckout true from the payments.dart file, my website comes to the screen with its full appearance and it is a very bad design and it requests the address information from the user again.

https://ibb.co/c2KYPgh
https://ibb.co/nmZgQ2y

https://ibb.co/PcXQ3hh If it is possible to receive payments on this screen, I want to activate it. Can you do this for me? If there is a fee, I will cover it.

**Comment by minhcasi** [comment]
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support https://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by hltyvz** [comment]
@minhcasi I filled the form

**Comment by minhcasi** [comment]
@hltyvz - thank you for the quick response - the fluxbuilder app could not test the payment features, this cart payment https://ibb.co/PcXQ3hh is only support on fluxstore shopify app.

could you try to set the `NativeOnePageCheckout: false` to see if the address could be fill in

**Comment by hltyvz** [comment]
I tried it the way you mentioned, but it is an app independent view and it doesn't look nice. Can you develop for my store for a fee?

**Comment by hltyvz** [comment]
@minhcasi I tried it the way you mentioned, but it is an app independent view and it doesn't look nice. Can you develop for my store for a fee?

**Comment by minhcasi** [comment]
@hltyvz - sorry we do not offer the installing or customize service at this time 😅

**Comment by minhcasi** [comment]
Let us know if you have any questions.

Btw, we also move to new ticket support, please give your next comment to https://support.isnpireui.com -thank you!
