### ISSUE TITLE
link homepage to page

### ISSUE THREAD

**Issue by ahmedseddiq-casheto** [inspireui/support#4974]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
- [ ] first issue
i want to link homepage to one of my pages so that be dynamic as to edit the following code to direct it 
{
  "HorizonLayout": [
    {
      "layout": "header_text",
      "fontSize": 25.0,
      "title": "If  you can dream it, \nYou can do it",
      "padding": 30.0,
      "showSearch": true,
      "isSafeArea": true
    },
    {
      "layout": "bannerImage",
      "isSlider": true,
      "design": "swiper",
      "radius": 20.0,
      "items": [
        {
          "category": 25,
          "image": "https://user-images.githubusercontent.com/1459805/62834035-2899b880-bc71-11e9-9ed8-4ce1790e0460.jpg",
          "padding": 0.0
        },
        {
          "category": 23,
          "image": "https://user-images.githubusercontent.com/1459805/62834034-2899b880-bc71-11e9-956b-64e6d0c35d46.jpg",
          "padding": 0.0
        },
        {
          "category": 26,
          "image": "https://user-images.githubusercontent.com/1459805/62834031-28012200-bc71-11e9-9980-f090df262343.jpg",
          "padding": 0.0
        },
        {
          "category": 27,
          "image": "https://user-images.githubusercontent.com/1459805/62834036-29324f00-bc71-11e9-9262-af0b8ceeba87.jpg",
          "padding": 0.0
        }
      ]
    },
    {
      "name": "Woman Collections",
      "layout": "simpleVerticalListItems"
    }
  ],
  "Setting": {
    "MainColor": "#3FC1BE",
    "ProductListLayout": "list"
  },
  "TabBar": [
    {
      "layout": "home",
      "icon": "assets/icons/tabs/icon-home.png"
    },
    {
      "layout": "category",
      "categoryLayout": "card",
      "icon": "assets/icons/tabs/icon-category.png"
    },
    {
      "layout": "search",
      "icon": "assets/icons/tabs/icon-search.png"
    },
    {
      "layout": "cart",
      "icon": "assets/icons/tabs/icon-cart2.png"
    },
    {
      "layout": "profile",
      "icon": "assets/icons/tabs/icon-user.png"
    }
  ]
}
- [ ] second issue
shipping price not show in check out 
![Attachment_1599834371](https://user-images.githubusercontent.com/66135124/92973085-ab4c0300-f483-11ea-9a2c-ec224f4f079b.jpeg)

- [ ] third issue
i want to remove other languages from language selection
![LANGUAG](https://user-images.githubusercontent.com/66135124/92973153-d3d3fd00-f483-11ea-8fdf-23074d4d732b.jpg)

+ Product & version:fluxstore multivendor 1.7.7 and flutter 1.27
+ Flutter (or React Native) version: flutter
+ Testing Device/Simulator: oppo a31
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on https://verify.inspireui.com **

![homeicon](https://user-images.githubusercontent.com/66135124/92972847-41cbf480-f483-11ea-9e5f-96c48a58ca21.png)

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
1. sorry i'm not sure to understand this 1st question

2. you could show the address `EnableAddress: true` to active the shipping - https://tppr.me/Y7dDB

3. try to read https://docs.inspireui.com/fluxstore/multi-language/#how-to-add-or-update-language

**Comment by ahmedseddiq-casheto** [comment]
Thnx for your answer 
For issue no.1 
I want to link home tab to view the following url
Www.casheto.com/store
As for example

**Comment by minhcasi** [comment]
@ahmedseddiq-casheto - try to add ` 'url': 'https://www.casheto.com/store' instead of using category

```
{
"layout": "bannerImage",
"isSlider": true,
"design": "swiper",
"radius": 20.0,
"items": [
   {
      'url': 'https://www.casheto.com/store',
       "image": "https://user-images.githubusercontent.com/1459805/62834035-2899b880-bc71-11e9-9ed8-4ce1790e0460.jpg",
      "padding": 0.0
},
```

**Comment by ahmedseddiq-casheto** [comment]
thnx bro but the shipping cost not appear in the order

**Comment by minhcasi** [comment]
try to refer to the default download package

**Comment by ahmedseddiq-casheto** [comment]
> try to refer to the default download fluxstore package

i dont get it wht u mean

**Comment by ahmedseddiq-casheto** [comment]
Hello is there any update about that(try to refer to the default download fluxstore package)) 
And have other question i want to add phone tab while sign up and remove sign up as vendor 
![2BA80171-F2CC-4FD0-AFF4-2C31CAE92021](https://user-images.githubusercontent.com/66135124/93109013-cf8e2680-f6b3-11ea-8aa8-445aec445102.jpeg)

**Comment by minhcasi** [comment]
@ahmedseddiq-casheto - sorry i mean refer to the default download package from Fluxstore, you could see the Shipping address from checkout, try to override the setting from fluxstore to your own, and check the difference.

You could use the Inspector tool to customize the any UI form the app - pls check out https://docs.inspireui.com/fluxstore/customization/#1-how-to-customize-any-ui-from-app
