### ISSUE TITLE
Show "Add To Cart" button in home and categories pages. #4269

### ISSUE THREAD

**Issue by el2adiii** [inspireui/support#4976]
Hello, Thank you for the great app!

How can I add "Add To Cart" Button on the shop loop and archive pages? To let people add items to cart instantly from the shop page.

Thank you

Previous verified Ticket: #4269

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@el2adiii - thank you for the question

Do you mean the add-to-cart on Home Screen or Category Screen, please share the screenshot which screens so that i could check with the team 

Very best!

**Comment by el2adiii** [comment]
@minhcasi thank you for your quick response.
Yes exactly! on home screen and category screens. Below is a screenshot of similar functionality:
![photo5971811404572898535](https://user-images.githubusercontent.com/24272642/92985124-0a277180-f4b0-11ea-9d50-9bd93ebb1059.jpg)

**Comment by minhcasi** [comment]
You could try to add the showCart option to these list as this feature is already supported on these list

<img width="1106" alt="Screen Shot 2020-09-13 at 09 32 25" src="https://user-images.githubusercontent.com/1459805/93008856-0a089e00-f5a4-11ea-915c-0d2ec9765bc4.png">

**Comment by el2adiii** [comment]
> You could try to add the showCart option to these list as this feature is already supported on these list
> 
> <img alt="Screen Shot 2020-09-13 at 09 32 25" width="1106" src="https://user-images.githubusercontent.com/1459805/93008856-0a089e00-f5a4-11ea-915c-0d2ec9765bc4.png">

Hi, thanks for you help!
Yes, it worked. But how can I add quantity boxes as well? (like the screenshot)

Thanks again!

**Comment by minhcasi** [comment]
@el2adiii - quantity box is not available - you could try to customize it 😅

**Comment by el2adiii** [comment]
Okay. Thank you :)
