### ISSUE TITLE
Error, does not start app MStore v4.0

### ISSUE THREAD

**Issue by Lopmar016** [inspireui/support#4978]
Does not start the app in the emulator
-executing the command react-native run android

![phone2](https://user-images.githubusercontent.com/70861539/92987865-6da3a600-f494-11ea-839f-f5fcbbbdbe32.PNG)

+ Product & version: MStore v4.0
+ Flutter (or React Native) version:  React Native
+ Testing Device/Simulator: Genymotion

**Comment by minhcasi** [comment]
Please raise your all comment into one open ticket #4908
