### ISSUE TITLE
I encountered a problem in the Webview in the input field I can’t insert special characters 

### ISSUE THREAD

**Issue by Lucatezuma** [inspireui/support#4979]
I have encountered a problem in the Webview, in the input field of the website I cannot insert special characters the keyboard always changes in the main characters. how can I solve this problem?

In annex the gif of the problem
Thank

![Webview](https://user-images.githubusercontent.com/47059435/92989937-2dfead80-f4d8-11ea-95c7-335b9b0efbaf.gif)

**Comment by minhcasi** [comment]
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support https://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by Lucatezuma** [comment]
I tried 100 times to fill in the form gives me an error. what are we doing?

**Comment by minhcasi** [comment]
@Lucatezuma - i'm sorry for the issues as it could be a google form access issue on your website, please help to post to http://support.inspireui.com - we are migrating to a new support system to improve the UX during support - please give a try and let us know
