### ISSUE TITLE
[ListApp] Back button icon is not working in recent listing category page 

### ISSUE THREAD

**Issue by Pavithran10** [inspireui/support#498]
**Required Info (please complete the following information):**
Product:[ListApp]
Version:1.6.1
Theme: MyListing

**Describe the bug**
In listapp application, in map screen tab inside sub list modules is avaiable in that recent list item page back button icon on the left top and the phone back button function also not working. 
regarding this issue I've attached the error video below.  

**Screenshots**
[errorapp.zip](https://github.com/inspireui/support/files/3063911/errorapp.zip)

**Comment by thangvo9x** [comment]
let me know your email. we've fix it.

**Comment by Pavithran10** [comment]
hi, you need my mail id.

**Comment by thangvo9x** [comment]
Yes
