### ISSUE TITLE
Why Reset Password option

### ISSUE THREAD

**Issue by alokmalewar** [inspireui/support#4980]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
- [ ] first issue
- [ ] second issue
- [ ] third issue

+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on https://verify.inspireui.com **

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@alokmalewar - could you explain more the screenshot of the forget password issue, what is your URL format password that you have used?

**Comment by alokmalewar** [comment]
"http://makeourstore.com/wp-login.php?action=lostpassword"

**Comment by alokmalewar** [comment]
![Screenshot_2020-09-13-09-06-49-150_com android chrome](https://user-images.githubusercontent.com/69632534/93009592-9f099800-f5a0-11ea-9e2b-ec7bcfb35114.jpg)
this is the error

**Comment by alokmalewar** [comment]
and if try native password it is showing this error
![92385375-6ba5b400-f12f-11ea-9568-56166fe1d57e](https://user-images.githubusercontent.com/69632534/93009628-e5f78d80-f5a0-11ea-9a80-18d4de10b585.jpeg)

**Comment by alokmalewar** [comment]
o

**Comment by alokmalewar** [comment]
it is mistakenly closed thats why i have reopen it

**Comment by alokmalewar** [comment]
Hello sir you are checking it or not

**Comment by alokmalewar** [comment]
Hello sir are you checking it or not

**Comment by minhcasi** [comment]
@alokmalewar - i'm not sure if it could be caused by your missing https config, please try to enable this option on your site and reconfigure the config.dart to `https`

**Comment by alokmalewar** [comment]
ok i will try that also

**Comment by alokmalewar** [comment]
when i try to login using google login and facebook this is the error it is showing and with sms login
![WhatsApp Image 2020-09-15 at 1 35 24 PM (1)](https://user-images.githubusercontent.com/69632534/93183389-8f34b400-f758-11ea-90aa-deb49bea4b4e.jpeg)
![WhatsApp Image 2020-09-15 at 1 35 24 PM](https://user-images.githubusercontent.com/69632534/93183394-9065e100-f758-11ea-8cb7-e9b8cad8912b.jpeg)

**Comment by alokmalewar** [comment]
there is no file provided by you as key-debug.properties for sha key generation and for facebookapp id and protocol name

**Comment by alokmalewar** [comment]
how to do that if in video it is showing to use the key-debug.properties for that

**Comment by alokmalewar** [comment]
Hello sir Please respond to my issues

**Comment by minhcasi** [comment]
Please follow strictly the official documentation ( https://medium.com/@inspireui/setup-google-login-for-flutter-apps-fedc58a490b8)

If fail please double-check these solutions:
1. In the beginning the main problem will face a lot of you is that you are getting the wrong SHA1 & SHA256 code! When you use this code for example: keytool -list -v -keystore C:\Users\MG\Desktop\test.jks -alias test it will show the current code not the code which the app build with, so I recorded a video for the full solution to fix that and the common problem will be caused by Facebook as well! Here's the video with English subtitle: https://www.youtube.com/watch?v=spC-CJzlno4 🎥 
2. The second problem, that Firebase doesn't support the old Google Play services on the phones, that means you need to update it by following these steps from your smartphone: Settings > Apps > Apps > Google Play services > App Details then check for updates - https://tppr.me/k9eEg For Huawei, I solved the problem by downloading the update manually from here: https://www.apkmirror.com/apk/google-inc/google-play-services/

**Comment by alokmalewar** [comment]
I have tried these steps but the problem exist

**Comment by alokmalewar** [comment]
and the file key-debug.properties is not available in source code

**Comment by alokmalewar** [comment]
i am getting sha key 1 from terminal because from project in android studio it is not giving any sha key 1 so both sha key are same or different and if different please tell a way to get sha key 1 from android studio

**Comment by minhcasi** [comment]
Please check this guide - https://support.inspireui.com/help-center/articles/3/9/24/3-common-questions#common-app-customize - "i've updated how to get the sha-1 key"

**Comment by alokmalewar** [comment]
Yes but there is no gradle menu  available in the newest android version

**Comment by minhcasi** [comment]
Pls check this screenshot 

![Android Studio_2020-09-18 10-34-25@2x](https://user-images.githubusercontent.com/1459805/93552470-b67ac380-f99a-11ea-91fd-444780292bc5.png)

**Comment by alokmalewar** [comment]
I want to know that i have use command gradlew signingReport and it is showing sha key and you are saying to find sha key by this method so i have to ask that the both sha key are same or different.

**Comment by alokmalewar** [comment]
Login with facebook is working now but login with google and sms are not working

**Comment by alokmalewar** [comment]
Sir Are You Checking It Or Not

**Comment by alokmalewar** [comment]
Sir Are You Checking It Or Not

**Comment by alokmalewar** [comment]
There is any solution to this or not

**Comment by alokmalewar** [comment]
> @alokmalewar - i'm not sure if it could be caused by your missing https config, please try to enable this option on your site and reconfigure the config.dart to `https`

Sir I have enable the https but then also reset password is showing same error

**Comment by alokmalewar** [comment]
Sir Are You Checking It Or Not

**Comment by minhcasi** [comment]
we have updated new guide on this link to fix the Google Login issue - https://support.inspireui.com/help-center/articles/3/25/15/social-login#7-common-login-issues 

Please move the new conversation to new Ticket Support http://support.inspireui.com - thank you!
