### ISSUE TITLE
[FluxNews] Facebook login issue

### ISSUE THREAD

**Issue by aldoyh** [inspireui/support#4981]
Hello,

I've tried my best to duplicate everything from the previous version and yet I'm still not able to make login with Facebook or Apple Sign to work, this is the error I get upon successful login with either Facebook or Apple.

Please help.

![Screenshot_1599904000](https://user-images.githubusercontent.com/5215449/92992943-12ef6600-f4f7-11ea-882c-7c89f8e08910.png)

**Comment by ducnm98** [comment]
I got the same error here

**Comment by minhcasi** [comment]
it seems the new bug from the flutter facebook lib - https://github.com/roughike/flutter_facebook_login/issues/238

**Comment by ducnm98** [comment]
Hello @minhcasi . I don't know how but when I test on debug mode everything is ok. But when release there are some bugs happen. I can't login by Google and Facebook also.

Facebook: https://imgur.com/DksuxLy
Google: https://imgur.com/Y4uY80G

I also add some config like this images https://imgur.com/4IkU0TR

**Comment by minhcasi** [comment]
@ducnm98 - you could try to test on the real device for these features - also try to update the Google Play Service to the latest version on your phone
