### ISSUE TITLE
depends on vector_math ^2.1.0 which doesn't match any versions, version solving failed.

### ISSUE THREAD

**Issue by dilshadkadavath** [inspireui/support#4982]
![image](https://user-images.githubusercontent.com/32771653/92993449-51911a80-f50f-11ea-9e3a-4836bd4f0fb2.png)

**Comment by minhcasi** [comment]
@dilshadkadavath - pls make sure to use flutter channel stable to run the project - ref: https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

**Comment by minhcasi** [comment]
Let us know if you have any question - thank you!
