### ISSUE TITLE
Error Domain=com.facebook.sdk.login Code=304 "(null)"

### ISSUE THREAD

**Issue by ducnm98** [inspireui/support#4984]
Hello. I got in stuck this error while login via Facebook. Error Domain=com.facebook.sdk.login Code=304 "(null)"
What should I do to fix it?

https://ibb.co/JsxCpDx
https://ibb.co/y6LCj6C

Not only that, but when running on Android I also got this

https://ibb.co/BjBDZP6

**Comment by minhcasi** [comment]
@ducnm98 - pls follow this guide and video carefully - https://medium.com/@inspireui/setup-facebook-login-for-flutter-apps-4e7bd031479d

**Comment by minhcasi** [comment]
you could also try the fresh example from this lib https://pub.dev/packages/flutter_facebook_login

**Comment by ducnm98** [comment]
Hello. I follow your instruction but still got error

**Comment by minhcasi** [comment]
let move this ticket to the same root cause on #4981
