### ISSUE TITLE
Button to open Categories Screen

### ISSUE THREAD

**Issue by IbrahimHd** [inspireui/support#4987]
Hi,

Please don't consider this as "customization", I'm just asking for a small hint on how to get it done.
I'm trying to add a "Go to Categories" button at the end of Home screen. It works but it doesn't take the defined categories layout, and it's repeated with each vertical layout (if there are more than 1).

1. The right place to put the code?  (I tried in `lib/widgets/home/vertical.dart` after `renderLayout(),` but it makes it repeated with every vertical layout)
2. Make the screen open with the already defined layout `"categoryLayout":"card"` but not the default one.

This is what I'm trying with:
```              
onPressed: () async {
   await Navigator.pushNamed(context, RouteList.category);
},
```

Thank you for your help.

**Comment by simonpham** [comment]
Hi @IbrahimHd,

Please try this below code to navigate to the category tab from Home screen:
```
MainTabControlDelegate.getInstance().changeTab("category");
```

To find the right place to put the code, please use Inspector Tool: https://www.youtube.com/watch?v=yGMt3Y20Zmg

Thank you for using our products!

**Comment by IbrahimHd** [comment]
Thanks you @simonpham
