### ISSUE TITLE
App login no longer functions

### ISSUE THREAD

**Issue by stien** [inspireui/support#4988]
App login no longer functions on our live app. 
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
- [1 ] login error on all login types

+ Product & version: 3.907
+  React Native version: 
+ Testing Device/Simulator: iphone x plus, android galaxy J2, simulators: iphone x plus, droid galaxy 3
+ Screenshot issues (drag the file to attach here): 

![Screen Shot 2020-09-12 at 1 49 16 PM](https://user-images.githubusercontent.com/231806/93003075-3a4b3080-f501-11ea-8745-210f366ab720.png)

**_Step 2 (require): submit proof of purchasing the license on https://verify.inspireui.com **

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support https://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
try to remove the `json api` and update to the latest `mstore-api` is not require json api

**Comment by minhcasi** [comment]
@stien - pls try to update your mstore-api to `2.9.5` that fix the json api issue - thank you!

**Comment by stien** [comment]
That didn't work. Do you have a migration doc, or a file change log to migrate to 4.0? There could be a solution in there somewhere.

**Comment by minhcasi** [comment]
@stien - you could try to manage your previous project via git, then override the new Mstore 4.0 to see the detail file change, you could use some tool like SourceTree to manage the source effectively. We suggest upgrading to the latest version to prevent UIWebview issues from Apple.

**Comment by stien** [comment]
Hello, I have migrated our app to 4.0. and updated the Mstore-API plugin to 2.9.5.  I still receive no response from logins from the app sim.  I really need your help.

**Comment by stien** [comment]
https://mdbsapi.daviserve.com/api/mstore_user/generate_auth_cookie/?second=120960000000&username=Stien3&password=l0gg3r51 is coming up 404. what should this call be?

**Comment by minhcasi** [comment]
@luyx2412 - please help to check this login issue

**Comment by stien** [comment]
this is the entire response:

{
  "type": "default",
  "status": 404,
  "ok": false,
  "headers": [
    [
      "server",
      "Apache"
    ],
    [
      "expires",
      "Wed, 11 Jan 1984 05:00:00 GMT"
    ],
    [
      "connection",
      "Keep-Alive"
    ],
    [
      "content-type",
      "text/html; charset=UTF-8"
    ],
    [
      "transfer-encoding",
      "Identity"
    ],
    [
      "date",
      "Wed, 16 Sep 2020 17:15:24 GMT"
    ],
    [
      "cache-control",
      "no-cache, must-revalidate, max-age=0"
    ],
    [
      "link",
      "<https://mdbsapi.daviserve.com/wp-json/>; rel=\"https://api.w.org/\""
    ],
    [
      "keep-alive",
      "timeout=5, max=98"
    ]
  ],
  "url": "https://mdbsapi.daviserve.com/api/mstore_user/generate_auth_cookie/?second=120960000000&username=Stien3&password=l0gg3r51",
  "bodyUsed": false,
  "_bodyInit": {
    "_data": {
      "size": 13739,
      "offset": 0,
      "blobId": "13B08375-D4B8-4AD2-A43C-63ECD092CD59",
      "type": "text/html",
      "name": "generate_auth_cookie.html",
      "__collector": {}
    }
  },
  "_bodyBlob": {
    "_data": {
      "size": 13739,
      "offset": 0,
      "blobId": "13B08375-D4B8-4AD2-A43C-63ECD092CD59",
      "type": "text/html",
      "name": "generate_auth_cookie.html",
      "__collector": {}
    }
  }
}

**Comment by stien** [comment]
Fixed it. Conflicting WPUserAPI.js files. Was using the 3.9.7 version, not 4.0

**Comment by stien** [comment]
I will close after completed testing. Thanks!

**Comment by minhcasi** [comment]
@stien - pls help to move to our new ticket support on the next comment - http://support.inspireui.com/ - thank you!
