### ISSUE TITLE
I can not install correctly. [ListApp]

### ISSUE THREAD

**Issue by damianlluch** [inspireui/support#499]
Mandatory Info (please complete the following information):

Product: [ListApp]
Your Purchased Code: [get from https://codecanyon.net/downloads]
b21e47a3-42d6-406d-9064-87a4ba0805f3
(we may not reply if you are not our customer)
Describe the issues

Hi, I'm going back to this project. That still does not work Previously, they told me that I should go to the "horizontallayout" property in config / MyListing.js.
Ok, but I'm going to that property and what do I have to do? I could be more specific.
The application is loading a main screen that is not the one on my site. In categories if I can see the categories of my website.
Also from the expo, the images are not seen. And the wrong location is loaded on the main screen.

Additional context
Add any other detail logs about the problem here.

**Comment by damianlluch** [comment]
????

**Comment by thangvo9x** [comment]
Hi. Can you share your AppConfig, plz? let me check help you.

**Comment by damianlluch** [comment]
Hi, I'm shared.

The demo application with London Maps is automatically remove when execute the project or is necessary remove manually?

[AppConfig.json.zip](https://github.com/inspireui/support/files/3084166/AppConfig.json.zip)

**Comment by thangvo9x** [comment]
please let me know your email.

**Comment by damianlluch** [comment]
damianclluch@gmail.com

**Comment by damianlluch** [comment]
Hi, thanks for sending me the project. I can not see images on the home page and how do I remove the home screen? My client does not want to see this.

**Comment by thangvo9x** [comment]
you can remove it App/Navigation/index.js and remove Home text

**Comment by damianlluch** [comment]
It is the second problem that closes and the problem continues, you have to wait for the customer's response to close any problem. If you close the problem again without a solution, I will ask for the refund of my money in CodeCanyon.

**Comment by damianlluch** [comment]
In the issue close for you says "you can remove it App/Navigation/index.js and remove Home text".
You can it more specific?

**Comment by damianlluch** [comment]
I can't see images in home app, logo and portrait image isn't my wordpress.
