### ISSUE TITLE
Error: "Could not find com.android.tools:r8:1.5.25."  

### ISSUE THREAD

**Issue by JokerZ01** [inspireui/support#4990]
- Product: FluxStore
- Testing Device/Simulator: Nexus 5, Android 8.0
 
- Issue: 
I followed the steps on the documentary, when I started the project it did not work.**

- This is the screenshot about the error:

![photo_2020-09-13_03-01-36](https://user-images.githubusercontent.com/19242572/93007108-79af6680-f56d-11ea-9482-f96b60bc160c.jpg)

- Error message is below:

Could not find com.android.tools:r8:1.5.25.
Searched in the following locations:
   https://dl.google.com/dl/android/maven2/com/android/tools/r8/1.5.25/r8-1.5.25.pom
   https://jcenter.bintray.com/com/android/tools/r8/1.5.25/r8-1.5.25.pom
   http://storage.googleapis.com/r8-releases/raw/com/android/tools/r8/1.5.25/r8-1.5.25.pom
Required by:
    project :

- Also, here it is the screenshot of test drive:

![photo_2020-09-13_03-03-22](https://user-images.githubusercontent.com/19242572/93007131-b24f4000-f56d-11ea-843d-9ed26613bfc0.jpg)

- Note: I filled the verify form. 

I'd like to thank you for your help.

**Comment by minhcasi** [comment]
@JokerZ01 - you need to open the source folder from fluxstore, instead of Android folder

**Comment by JokerZ01** [comment]
I opened it from FluxStore, but I have the same error:

![photo_2020-09-13_10-19-08](https://user-images.githubusercontent.com/19242572/93012650-b0f03880-f5aa-11ea-8112-01787b83c677.jpg)

**Comment by JokerZ01** [comment]
Did you see my new message? @minhcasi

**Comment by JokerZ01** [comment]
I really don't understand. If you don't help me, I can't continue the project. The solution you advised didn't work for me. So would you help  me? @minhcasi

**Comment by minhcasi** [comment]
@JokerZ01 - sorry for the late response, we have updated your comment on the new ticket support 😊

Please help to check and let us know if you have any issues, pls move to the new ticket support system, we will comment there (as i'm closing this ticket) 👍
