### ISSUE TITLE
Native checkout screen critical issue

### ISSUE THREAD

**Issue by krdvijay** [inspireui/support#4993]
Hi Team, Kindly provide fix for showing taxes on native checkout screen.

**Issue 1:**
Here is main issue being caused
**On checkout page:**
1. Product Price is shown **including taxes**
2. Discount is shown **excluding taxes**
3. **Taxes are not shown**
![app](https://user-images.githubusercontent.com/69688125/93025752-57295600-f61e-11ea-8520-75b133503faa.jpg)

**Observation:** Thus **Total** appears to be incorrect even though it is correct.
[Refer Screenshot]

**Issue 2:** On Order Details Page from Order History Shipping Amount is not showing causing issue to the user in calculating total.
[Refer Screen shot]
![issue2](https://user-images.githubusercontent.com/69688125/93026602-c30ebd00-f624-11ea-8981-37293540cc07.jpg)

I have already verified my purchase as part of previously raised tickets. So kindly help me get code fix for the same. Thank you.

Running latest code 1.7.7
woocom

**Comment by minhcasi** [comment]
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support https://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
Sorry we could not search your previous ticket ID - pls help to send it again

**Comment by krdvijay** [comment]
@minhcasi: I have submitted form to verify purchase again, kindly check it now.
 Previous ticket where i verified my purchase was #4616 .

You can refer either of above to purchase verification. Please provide a fix ASAP

**Comment by krdvijay** [comment]
@minhcasi- Pls help us getting this issue fixed.

**Comment by minhcasi** [comment]
@krdvijay - please also share the screenshot on your website for this checkout screen, what the correct total on this case?

@minhtruong315 - pls help to investigate the Tax issues on Coupon

**Comment by krdvijay** [comment]
@minhcasi @minhtruong315 : Here are screenshots for both Web and App
All issues are being caused due to unavailability of Tax on Screen
![issue1](https://user-images.githubusercontent.com/69688125/93195072-6fa48800-f766-11ea-8a12-ee6edf457d99.jpg)
![issue1 1](https://user-images.githubusercontent.com/69688125/93195095-759a6900-f766-11ea-8a35-7e7c74830d18.png)

Please check the issue and provide resolution.

**Comment by krdvijay** [comment]
@minhcasi - Issue been pending for long is anyone looking into it. Kindly provide a fix asap.

**Comment by minhcasi** [comment]
@krdvijay - the Tax on discount is a minor bug on the release, we need time to investigate and upgrade as this is complex features from both Api and App - thank you for your patience

**Comment by minhcasi** [comment]
Greetings from InspireUI 🎉
To improve user experience during support, we are announcing that a new ticket support system is available on this link https://support.inspireui.com - please help to move your next comment on the new support system - thank you for your time!
