### ISSUE TITLE
Publishing to Google Play Store

### ISSUE THREAD

**Issue by EricWaf** [inspireui/support#4995]
I have been editing my code and all has been well and now i am facing serious challenges when i try to publish it to google play store. I have no programming background but i have tried so much to follow your videos and even read other forums and it has been great up until this point where i have followed your video of 'Changing bundle ID using script' and i have failed to proceed because of certain errors.
+ Detail Issues: 
- Is the bundle ID something you just come up with or you get it from somewhere else. I was using 'com.heyloyalmobile.Heyloyal' but when i try to build gradle it says 'it has searched google play and could not find that host'. My project is called Heyloyal please help me on this App Bundle ID coz i really have no idea where it comes from. I also paid for Google play console.
- When i try to change working folder or any other field on the ''change-bundleid.conf'' i get an error when i run ''bash tools/change-bundleid.sh''

Please help me asap, i am way behind the launching date for my business.
![bandicam 2020-09-12 20-06-09-219](https://user-images.githubusercontent.com/71236727/93031509-091f4d00-f634-11ea-88d2-0921f7e7e136.jpg)
![bandicam 2020-09-12 20-06-00-535](https://user-images.githubusercontent.com/71236727/93031513-11778800-f634-11ea-9450-4827eea2ddcd.jpg)
![bandicam 2020-09-11 21-07-58-859](https://user-images.githubusercontent.com/71236727/93031514-1a685980-f634-11ea-930f-1dc714ca35a6.jpg)

**Comment by minhcasi** [comment]
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support https://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by EricWaf** [comment]
I have shared all you asked for. Thanks

**Comment by minhcasi** [comment]
@EricWaf - the script could be a bug on window as it is only available for Mac OS, pls try to change the bunddle manually by using this guide https://docs.inspireui.com/fluxstore/delivery-android/#12-change-the-app-bundle-id-package-name

**Comment by EricWaf** [comment]
Thanks for the response. I also have an issue with the Bundle ID. What I
don't understand is, do I have to get it from "Google Play Console" or I
just creat it on my own.
I wanted to use "com.heyloyalmobile.Heyloyal" but it was also giving me an
error.
In the Manifest.xmls file do I only change the bundle ID and nothing else
because I see areas with the "https://inspireui.com". Should this be
changed and if they are changed what will they be changed to?

**Comment by minhcasi** [comment]
@EricWaf - you could search the whole android folder and replace the inspire bundle with your own bundle ID - pls double-check our guide, there are some files you need to verify -  thank you!

**Comment by EricWaf** [comment]
Hello, I changed the banners on my "config.JSON" from android studio then
uploaded it to the "MStore API" of my backend and even regenerated
thumbnails but my app does not show the new banners.
How do you change the banners. What have i not done right. thanks
