### ISSUE TITLE
License Issue

### ISSUE THREAD

**Issue by rcarloscc** [inspireui/support#4996]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: I have purchase a license i add via fluxbuilder app its not going to be release so i want to use the license on an other project i do will publish

i try to deactivate this from fluxbuilder but was not able , talk to chat on we support they toll me to create a ticket 

+ Product & version: FluxStore 1.7.7
+ Flutter (or React Native) version: Flutter

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@rcarloscc - we have reset your purchase code, please try again 

Please email to support@inspireui.com Let us know if you have any issues regarding to the active License issue - thank you!
