### ISSUE TITLE
Flutter Woocomerce loading Slow & some functionality not working

### ISSUE THREAD

**Issue by kulbirmalhi** [inspireui/support#4997]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
- [App speed is very slow ] first issue
- [ Cart page keep loading i have using webview onepagecheckout ] second issue
- [Sign up & Sms login give error after putting otp number ] third issue
- [How we change introduction page title ] fourth issue
- [which config_xx.json file upload in mstore api plugin i have uploaded already config_en.json is it right] fifth issue

+ Product & version: Flux store pro for woocommerce
+ Flutter (or React Native) version:  1.7
+ Testing Device/Simulator: Mi A3
+ Screenshot issues (drag the file to attach here): 
![WhatsApp Image 2020-09-14 at 12 54 17 PM (1)](https://user-images.githubusercontent.com/40395066/93056181-b40e2600-f689-11ea-8798-728af38d6b23.jpeg)
![WhatsApp Image 2020-09-14 at 12 54 17 PM (2)](https://user-images.githubusercontent.com/40395066/93056187-b5d7e980-f689-11ea-9e28-addb228a8401.jpeg)
![WhatsApp Image 2020-09-14 at 12 54 17 PM](https://user-images.githubusercontent.com/40395066/93056189-b6708000-f689-11ea-8750-9ed9f0ab3d02.jpeg)

**_Step 2 (require): submit proof of purchasing the license on https://verify.inspireui.com **

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@kulbirmalhi - could i confirm you are using the latest Fluxstore 1.7.7 version?

I've tried to check the issue on the default fluxstore app but could not reproduce the issue - thank you!

**Comment by kulbirmalhi** [comment]
yes we have using latest version 1.7.7

**Comment by simonpham** [comment]
Hi @kulbirmalhi,

Can you run `flutter doctor -v` and send us a screenshot of the result.

Thank you!

**Comment by simonpham** [comment]
Hi @kulbirmalhi,

Regarding your concerns, please follow our documentation:

To optimize app performance: https://support.inspireui.com/help-center/articles/3/8/19/app-performance.

To change onboarding titles & images: https://support.inspireui.com/help-center/articles/3/8/10/common-features#7-onboarding-and-login-mode

For the second & third issues, please run `flutter clean`, zip your project folder then send it to me at simon@inspireui.com.
I will help you to check it.

Thank you!

**Comment by simonpham** [comment]
Hi @kulbirmalhi,

I have tried with your source code but cannot reproduce the issue.
Please help us run `flutter upgrade --force` to make sure you have the latest Flutter version and try again.

Thank you!
