### ISSUE TITLE
[MStore] Android Issue " Can't get data from server " 

### ISSUE THREAD

**Issue by OnlyDan** [inspireui/support#50]
**Required Info (please complete the following information):**
 - Product: Mstore
]
 - Your Purchased Code: [get from https://codecanyon.net/downloads]
 - You told me to post Here

**Describe the bug**
Android Issue " Can't get data from server " but runs perfectly fine on iOS? 
Ive installed all plugins, as you can read above, it runs fine on iOS but on android "Can't get data from server" 

**Screenshots**
N/A

**Comment by minhcasi** [comment]
Hi, could you share the whole screenshot please, it looks like your Android simulator could not get the website URL, please make sure the setting is LAN, instead of location

**Comment by OnlyDan** [comment]
@minhcasi 

https://serving.photos.photobox.com/2840174251db324c8a1234982268fabdf5a659d10ca4a63fff7125a348c99f000d488857.jpg
-
setting where is LAN instead of location? 

Thanks

**Comment by OnlyDan** [comment]
@luxy2412 
I can run a react-native project, the app runs I get no data from server.. why was the issue closed?

**Comment by luyx2412** [comment]
Hi @OnlyDan Please read the document to fix the issue, if the issue still exist. We will reopen again. Sorry about this problem
Thanks

**Comment by OnlyDan** [comment]
@luxy2412 
Please read what I wrote properly. 
The app runs on react native fine, I have ran react native projects before. That’s not the issue. 

The issue is I’m getting no data from server , it works fine with your mistore URL. but on multiple websites it doesn’t work. But my URL works on iOS, could you take a look into this? I’m connecting via https:// if this helps.

**Comment by luyx2412** [comment]
Hi @OnlyDan Can you provide me your Config.js file?. 
Thanks

**Comment by OnlyDan** [comment]
@luyx2412 https://www.dropbox.com/s/8ikvdtnuy5pazb8/Config.js?dl=0

Thanks.

**Comment by luyx2412** [comment]
Hi @OnlyDan I checked your Config. I need investigate more about this problem. You can quickly fix based on my code.

Replace this code to `src/store/configureStore.js`
```
/** @format */
import Reactotron from "reactotron-react-native";
import { applyMiddleware, compose, createStore } from "redux";
import thunk from "redux-thunk";
import reducers from "@redux";
import { Constants } from "@common";
import { connectConsoleToReactotron } from "@app/Omni";
import "./../../ReactotronConfig";

const middleware = [
  thunk,
  // more middleware
];

// const store = createStore(reducers, {}, applyMiddleware(...middleware));

const configureStore = () => {
  let store = null;
  if (__DEV__) {
    if (Constants.useReactotron) {
      store = Reactotron.createStore(
        reducers,
        {},
        applyMiddleware(...middleware)
      );
      connectConsoleToReactotron();
    } else {
      const composeEnhancers =
        window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ || compose;
      store = composeEnhancers(applyMiddleware(...middleware))(createStore)(
        reducers
      );

      if (module.hot) {
        // Enable Webpack hot module replacement for reducers
        module.hot.accept(reducers, () => {
          const nextRootReducer = reducers;
          store.replaceReducer(nextRootReducer);
        });
      }

      // show network react-native-debugger
      // only show on IOS, android bug
      // if (Platform.OS === "ios") {

      // }
    }
    global.XMLHttpRequest = global.originalXMLHttpRequest
      ? global.originalXMLHttpRequest
      : global.XMLHttpRequest;
    global.FormData = global.originalFormData
      ? global.originalFormData
      : global.FormData;
  } else {
    store = compose(applyMiddleware(...middleware))(createStore)(reducers);
  }
  return store;
};

export default configureStore();

```

Thanks

**Comment by OnlyDan** [comment]
@luyx2412 thanks, ill give this a shot and get back to you.

**Comment by OnlyDan** [comment]
@luyx2412 Same issue, the code above didnt fix.

**Comment by OnlyDan** [comment]
Issue was due to host, moved to a new host and it was working okay, you can close this topic.

**Comment by luyx2412** [comment]
Thanks @OnlyDan !
