### ISSUE TITLE
[MStore MV] many issues with the app

### ISSUE THREAD

**Issue by lotfinoluffy** [inspireui/support#500]
hi

first of all I had enough with the previous agent, not sure if reading the issues I mentioned, nor feeling that he really wanted to help
so please either fix these bugs or refund the purchase thank you

Product: MStore Multi vendor
Your Purchased Code: 00cdcfXX-e5XX-4046-XX21-e99XXb468368 (edited a bit)
(we may not reply if you are not our customer)
Describe the bug

rebuilder won't save the detail of my install at all
when I go trough and edit the appconfig trough atom, signed as a vendor, I can't post any product and even with the http://dokan.mstore.io/ install (user have the right to add products) and won't work even from your demo
have to click on return (clicking outside to get the next button or confirm) doesn't work, and then the next button is barely visible to click on it
images won't load (some do for the 3 products layout) from my install and take forever to load from the demo (images are served from wp cdn or wpmudev one
images on the payment or delivery methods are so big on the ipad
while using the eject command, and trying to build the app, I get error and build just fail
Screenshots

https://imgur.com/YNJpLGb
https://imgur.com/bZWsKXz
https://imgur.com/yYIkIaQ
https://imgur.com/0j7BERC
https://imgur.com/I4RaQHD
https://imgur.com/vwTQxrl
https://imgur.com/3W8wtYI
https://imgur.com/sWe8U2p
https://imgur.com/wdYwGbJ

Additional context
Add any other detail logs about the problem here.
If possible please share your config.js that use for the app setting

https://drive.google.com/open?id=1Nm1s-fqkCVNWjwJBRxyvGbdPJSouAKvq
https://drive.google.com/open?id=1G58PIYSxWCBWdE1W3A8ieuIKFh26xtHT

**Comment by minhcasi** [comment]
@lotfinoluffy noted - we will have a check on your sharing config and will let you know - thank you!

**Comment by thangvo9x** [comment]
Hi. We've check. Your source still work. u can let an email for sending.
Thanks

**Comment by thangvo9x** [comment]
You can reference more here for your server. 
https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-jwt-authentication/#auth_jwt

**Comment by lotfinoluffy** [comment]
what does it mean : "Your source still work. u can let an email for sending." ???
doesn't make any sense

did you check the config file and it should work or what !?!?!

**Comment by lotfinoluffy** [comment]
why is this closed without even given a proper reply !?

**Comment by minhcasi** [comment]
Hi there, as report from our team, there is the issue with your nginx server that could not compatible with this plugins - https://wordpress.org/plugins/jwt-authentication-for-wp-rest-api/ - hence it will not compatible with the app. If you could able to config it work correctly then the issue will be fixed, otherwise we could process the refund for you, thanks!

**Comment by lotfinoluffy** [comment]
Hi

There were many issues not just the one about adding products as a vendor, and I contacted you guys even before buying to tell you about some bugs that I found while trying the app from the spotui (not sure about the name) and it’s the same since
Also cebuilder can’t even save the config of the app so …

And support is just a hassle to be honest

Thank you
