### ISSUE TITLE
Magento2 Product Price not changing with Currency in Fluxstore Pro

### ISSUE THREAD

**Issue by shakeebrock** [inspireui/support#5000]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
- [ ] first issue
Dear Inspire UI, 
I am using Fluxstore pro to create an app with Magento2,
I have 2 currencies in my existing Magento2 Store, so i have added the both currencies here in Flux Store App
but when Changing Currency Price is same it is not converting with the currency change.
i.e.
If a product is USD 10 and then i change the currency, it is now CNY 10 
it should be 68.20 CNY

- [ ] second issue
I have a dynamic product, it is been created with an api from the vendor,
i want to add this product as a webview product in my app. It can be a product with only a link via a banner on the homepage, it is not necessary to have this product in any category view.

- [ ] third issue
i want to checkout with webview of my existing gateways.

+ Product & version: FluxStore-pro-1.7.7b
+ Flutter (or React Native) version: Flutter (Channel stable, 1.20.3, on Mac OS X 10.14.6
+ Testing Device/Simulator: Pixel 3a API 28
+ Screenshot issues (drag the file to attach here): 

![Screenshot 2020-09-14 at 3 41 57 PM](https://user-images.githubusercontent.com/36795645/93076527-e8411100-f6a0-11ea-9d06-5081bba6eed3.png)

![Screenshot 2020-09-14 at 3 41 27 PM](https://user-images.githubusercontent.com/36795645/93076533-ebd49800-f6a0-11ea-8baa-326c7f79e1a1.png)

**_Step 2 (require): submit proof of purchasing the license on https://verify.inspireui.com **

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhtruong315** [comment]
@shakeebrock for issue 1,3 it's not available in Fluxstore now. We will research and implement in the next release.
for issue 2, you can try to add this config in config_xx.json
```
{
      "layout": "bannerImage",
      "items": [{
        "url": "https://inspireui.com",
        "image": "https://user-images.githubusercontent.com/1459805/59846820-12672e80-938b-11e9-8fa6-b331b7db331d.png",
        "padding": 5.0
      }]
    },
```
Change url to product url
