### ISSUE TITLE
App don't show the regular price on a variable product (list products view)

### ISSUE THREAD

**Issue by pedraohenrique** [inspireui/support#5002]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: Hi there! We got this issue after add variable product with has a sale price. At the product list, the regular price and sale price are the same (sale). At the product screen, this is correct, with the regular price higher than sales price. How can we solve this problem?
- [ ] first issue
- [ ] second issue
- [ ] third issue

+ Product & version: Fluxstore WooCommerce - Flutter E-commerce Full App 
+ Flutter (or React Native) version: 1.20.3
+ Testing Device/Simulator: Apple and Android phones
+ Screenshot issues (drag the file to attach here): 
![IMG_6103](https://user-images.githubusercontent.com/26346358/93119370-13733280-f698-11ea-8a5d-90c797f29427.PNG)
![IMG_6107](https://user-images.githubusercontent.com/26346358/93119386-19691380-f698-11ea-8a27-a79ba7fba4a2.PNG)

**_Step 2 (require): submit proof of purchasing the license on https://verify.inspireui.com **

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by eraldix** [comment]
Same issue, waiting for solution.

**Comment by simonpham** [comment]
Hi @pedraohenrique @eraldix,

We have checked the sale price issue.
The woo-commerce API doesn't provide a regular price for on-sale products with product variations, so we have to hide the regular price in the future version of FluxStore.

You can wait for the next version or, you can hide it now by changing these below code from `lib/model/product/product.dart` as below:

<details>
<summary>Click to show</summary>
<p>

Remove this code:
```dart
      onSale = parsedJson["on_sale"];
```
Add this code:
```dart
      onSale = parsedJson["price"] != parsedJson["regular_price"] &&
          isNotBlank(parsedJson["regular_price"]) &&
          double.parse(parsedJson["regular_price"]) >
              double.parse(parsedJson["price"]);
```

The result will be like:
![image](https://user-images.githubusercontent.com/8846657/93416548-2ec88280-f8d0-11ea-8b0d-832673e3d259.png)

</p>
</details>
