### ISSUE TITLE
Display currency different from web

### ISSUE THREAD

**Issue by AmoMante** [inspireui/support#5003]
The currency showing on the app is USD but on my website, I am using GHS
Any help to change it?

**Comment by minhcasi** [comment]
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support https://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
Pls post your next question on http://support.inspireui.com/ - thank you!
