### ISSUE TITLE
Cannot Login (Mstore Expo)

### ISSUE THREAD

**Issue by sourav1191** [inspireui/support#5004]
Hi,
I recently bought the Mstore Expo version, but I am facing 2 issues:
1. Unable to Login, everything else looks fine with wordpress connectivity(products and all that)
2. Account Kit service has been removed by Facebook, any workaround for that?

Mstore Expo V 4.0.0
Expo V 3.25.1
Testing on Oneplus 6T(using Expo android app)
![WhatsApp Image 2020-09-15 at 1 53 28 AM](https://user-images.githubusercontent.com/70502399/93135226-a0010d80-f6f7-11ea-9dc9-f52ce908508f.jpeg)

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by sourav1191** [comment]
Hi, Do I need to create support ticket in the new link?

**Comment by minhcasi** [comment]
@sourav1191 - please help to update to latest mstore-api plugin and mstore-expo 4.0 that could fix the issue.

You could also raise the new ticket support to http://support.inspireui.com/ - thank you!

**Comment by sourav1191** [comment]
Still no change after updating the Mstore API, is it because I haven't set up facebook login yet?
![image](https://user-images.githubusercontent.com/70502399/93481284-05cddf00-f91c-11ea-98c7-a5fec53956a1.png)

**Comment by minhcasi** [comment]
Yes, you should use your own Facebook App to use the facebook login - thank you!

**Comment by sourav1191** [comment]
But I am not using Facebook login....I am using username and password to login.... it's getting stuck in some cycle looks like.... pls refer the screenshot

**Comment by sourav1191** [comment]
Hi Please provide me refund if you are not able to help me, it has been more than 4 days and you are not able fix the issue?

**Comment by luyx2412** [comment]
Hi @sourav1191 The screenshot issue is the warning, it is not related the facebook issue. So please make sure you config right way for facebook login. Please read the document about it https://github.com/facebook/react-native-fbsdk

Thanks

**Comment by sourav1191** [comment]
See, that's what I am saying, that I am not trying to login through Facebook, I am doing simple user id password login, then why it is the app stuck at this loading symbol after entering user id and password, it is not even throwing an error for wrong id and password just stuck at that loading circle rotating in the middle
![WhatsApp Image 2020-09-15 at 1 53 28 AM (1)](https://user-images.githubusercontent.com/70502399/93671307-82e58980-fabf-11ea-8e19-bad1d66631bf.jpeg)

**Comment by minhcasi** [comment]
Please help to move the new conversation to new Ticket Support http://support.inspireui.com (you could mention on this ticket history) - thank you!
