### ISSUE TITLE
Social Login on shopify version using Woocommerce.

### ISSUE THREAD

**Issue by Nachouru** [inspireui/support#5005]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
- [ ] Social login on shopify versions.
It's clearly pointing to a url thats not from shopify, 
https://dev-iki.myshopify.com/index.php?route=extension/mstore/account/socialLogin < this looks like the place to go for woocommerce.

+ Product & version: 1.7.7
+ Flutter (or React Native) version: Flutter
+ Testing Device/Simulator:  Sim/Device
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on https://verify.inspireui.com **

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@Nachouru - sorry i have check with the team and confirm the social login is not available on the current release for Fluxstore Shopify, you could only log in with the default Shopify email - thank you!

**Comment by Nachouru** [comment]
@minhcasi this is not how you advertise the product in codecanyon. Social login is part of the features and in no place it says otherwise. 

I have implemented the functionality myself. There are other functionalities that are broken, for example blogs. I hope you release a version that supports all that your product claims to do.

**Comment by minhcasi** [comment]
Yes sure, our team is working hard to add more feature on next release 🙂

**Comment by hamzachughtai** [comment]
Hey there @Nachouru Can you share how you implemented Social Login..?

**Comment by minhcasi** [comment]
Please help to move the new conversation to new Ticket Support http://support.inspireui.com - thank you!
