### ISSUE TITLE
Login and update profile messages

### ISSUE THREAD

**Issue by medsaadit** [inspireui/support#5007]
First updating the profile does not work at all.
![Screenshot_20200914-235618](https://user-images.githubusercontent.com/67774655/93164112-bbafe800-f6e6-11ea-8a62-713b53e2adf5.jpg)

Second: when you try to login and there is a problem with the login info, all you get is a debuging message instead of something like "wrong login information"
![Screenshot_20200914-235656](https://user-images.githubusercontent.com/67774655/93164234-11849000-f6e7-11ea-9568-6d48db8840d8.jpg)

Third bug : when you refresh blogs listing page it becomes empty.

Fourth bug :blogs text comes in one bulk paragraph no new lines no paragraphs ..(I think at least newlines and paragraphs should be preserved to make the text readable ) the same thing for product's descriptipn.

Honesty those bugs should have not existed in the first place if some proper testing was done. I am trying to configure the app to publish it two months ago and still can't get it done yet.
Please fix those issues.

Thank you

**Comment by minhcasi** [comment]
@medsaadit - pls help us to raise this new ticket to our new support ticket - http://support.inspireui.com/ - thank you for your time!

**Comment by medsaadit** [comment]
I don't see how I can submit an issue in your new support portal. that looks more like documentation portal.
Can you please either give me the direct link to create a support ticket or move this ticket there.

thanks

**Comment by medsaadit** [comment]
https://support.inspireui.com/help-center/tickets/20

**Comment by medsaadit** [comment]
Ticket created please check it and fix it ASAP. should I create a ticket
in fluxstore page on codecanyon's comment section as well?

**Comment by Numan11** [comment]
@medsaadit  your issue solve or not ? i'm also facing this method[]

**Comment by medsaadit** [comment]
Not yet ! Feel free to reopen another ticket so they know it's a global bug.
