### ISSUE TITLE
Account setting not working when you just signup and continue using the app

### ISSUE THREAD

**Issue by medsaadit** [inspireui/support#5008]
When you checkout then signup (new account) then proceed with the payment process ..etc  then you return to your account settings for example to see your order(s) or update/see account information, all fields look empty even you seem logged in but all fields are empty and also the order history page is empty the only way to fix it is to logout then login again which gonna be a frustration for the user.

Please fix it.

Thanks

**Comment by minhcasi** [comment]
@medsaadit - pls help us to raise this new ticket to our new support ticket - http://support.inspireui.com/ - thank you for your time!

**Comment by medsaadit** [comment]
https://support.inspireui.com/help-center/tickets/21
