### ISSUE TITLE
Magento2 API setup in Fluxstore Shopify

### ISSUE THREAD

**Issue by BinitaShah** [inspireui/support#5009]
Hello,

We are building E-commerce-Magento2 application in Flutter. For that we have purchased ‘Fluxstore Shopify’ template. See the link
https://codecanyon.net/item/fluxstore-shopify-the-best-flutter-ecommerce-app/25877299

But, when we checked https://docs.inspireui.com/fluxstore/magento-setup/ link for Magento2 setup we found that it is compatible with ‘Fluxstore Pro’ template. See the link
https://codecanyon.net/item/fluxstore-the-universal-woocommerce-magento-opencart-mobile-app-by-flutter-framework/24020929?irgwc=1&clickid=QgwWPPXoJxyORfPwUx0Mo3QWUkiXBLQMO3Miy00&iradid=275988&irpid=367585&iradtype=ONLINE_TRACKING_LINK&irmptype=mediapartner&mp_value1=&utm_campaign=af_impact_radius_367585&utm_medium=affiliate&utm_source=impact_radius

So we want to upgrade from ‘Fluxstore shopify’ to ‘Fluxstore Pro’. What is the procedure & payment options for the same? If you provide upgradation we are ready to pay difference.

Waiting for your reply.

**Comment by minhcasi** [comment]
@BinitaShah - you could purchase new Fluxstore Pro and send us the refund on your previous shopify version 👍 

Btw, we are moving to new ticket support, pls post your new comment on http://support.inspireui.com/
