### ISSUE TITLE
[MStore Pro] First build failed

### ISSUE THREAD

**Issue by binaryversion** [inspireui/support#501]
**Mandatory Info (please complete the following information):**
 - Product: [MStore Pro]
 - Your Purchased Code: 7332c4da-ce4b-4036-8cc9-c28b8132d2a0

**Describe the issues**
I bought MStore Expo & Pro, I needed to have OneSignal working on the APP.
After download and installation accordingly to the manual, and after solving the problems from the missing file "local.properties", and missing babel decorator packages, I have another error. I need help to make this APP work.

**Additional context**
MACOSX 10.14
![Screenshot_1555355538](https://user-images.githubusercontent.com/18722452/56159149-df37a600-5fbb-11e9-9dc3-2467b62cdb09.png)

**Comment by almalizy** [comment]
i got the same error at first then i used other way - build normal project with expo then after finshed and tested then copy only important files from mstorepro and copy dependeces and dev dependeces at package.json then npm install and it will work .

**Comment by binaryversion** [comment]
Doesn't work, I tried also with new version of CeBuilder v0.32.0 beta, doesn't save settings and crashes if I try to customize any of the items on the homescreen.
Please check this issue ASAP.

**Comment by almalizy** [comment]
be sure that you made update to yarn or npm with last version , i faced some error also and can,t see icons but after update yarn it solved

**Comment by binaryversion** [comment]
Everything updated same issue.

**Comment by almalizy** [comment]
as y know i am not the team customer service - but i try to help you cause i feel with your feeling cause i was been in your same issue 
so - can your copy errors log from terminal please 
may be i can help you

**Comment by binaryversion** [comment]
I appreciate your help.
npm 6.9.0
node v11.14.0
yarn 1.15.2
--------- Error on: expo start ---------
/Users/joaomartins/Documents/WORK_APP/EdgarGomes-3.7.2/node_modules/expo/AppEntry.js: Cannot find module 'babel-preset-react-native-stage-0/decorator-support' from '/Users/joaomartins/Documents/WORK_APP/EdgarGomes-3.7.2'

--- warning on: npm install ---
npm WARN rm not removing /Users/joaomartins/Documents/WORK_APP/EdgarGomes-3.7.2/node_modules/.bin/fa5-upgrade as it wasn't installed by /Users/joaomartins/Documents/WORK_APP/EdgarGomes-3.7.2/node_modules/react-native-vector-icons
npm WARN rm not removing /Users/joaomartins/Documents/WORK_APP/EdgarGomes-3.7.2/node_modules/.bin/generate-icon as it wasn't installed by /Users/joaomartins/Documents/WORK_APP/EdgarGomes-3.7.2/node_modules/react-native-vector-icons
npm WARN rm not removing /Users/joaomartins/Documents/WORK_APP/EdgarGomes-3.7.2/node_modules/.bin/sane as it wasn't installed by /Users/joaomartins/Documents/WORK_APP/EdgarGomes-3.7.2/node_modules/sane
npm WARN rm not removing /Users/joaomartins/Documents/WORK_APP/EdgarGomes-3.7.2/node_modules/.bin/semver as it wasn't installed by /Users/joaomartins/Documents/WORK_APP/EdgarGomes-3.7.2/node_modules/semver
npm WARN rm not removing /Users/joaomartins/Documents/WORK_APP/EdgarGomes-3.7.2/node_modules/.bin/regjsparser as it wasn't installed by /Users/joaomartins/Documents/WORK_APP/EdgarGomes-3.7.2/node_modules/regjsparser
npm WARN rm not removing /Users/joaomartins/Documents/WORK_APP/EdgarGomes-3.7.2/node_modules/.bin/json5 as it wasn't installed by /Users/joaomartins/Documents/WORK_APP/EdgarGomes-3.7.2/node_modules/json5
npm WARN rm not removing /Users/joaomartins/Documents/WORK_APP/EdgarGomes-3.7.2/node_modules/.bin/jsesc as it wasn't installed by /Users/joaomartins/Documents/WORK_APP/EdgarGomes-3.7.2/node_modules/jsesc
npm WARN rm not removing /Users/joaomartins/Documents/WORK_APP/EdgarGomes-3.7.2/node_modules/grpc/node_modules/.bin/node-pre-gyp as it wasn't installed by /Users/joaomartins/Documents/WORK_APP/EdgarGomes-3.7.2/node_modules/grpc/node_modules/node-pre-gyp
npm WARN rm not removing /Users/joaomartins/Documents/WORK_APP/EdgarGomes-3.7.2/node_modules/fsevents/node_modules/.bin/node-pre-gyp as it wasn't installed by /Users/joaomartins/Documents/WORK_APP/EdgarGomes-3.7.2/node_modules/fsevents/node_modules/node-pre-gyp
npm WARN rm not removing /Users/joaomartins/Documents/WORK_APP/EdgarGomes-3.7.2/node_modules/.bin/esparse as it wasn't installed by /Users/joaomartins/Documents/WORK_APP/EdgarGomes-3.7.2/node_modules/esprima
npm WARN rm not removing /Users/joaomartins/Documents/WORK_APP/EdgarGomes-3.7.2/node_modules/.bin/esvalidate as it wasn't installed by /Users/joaomartins/Documents/WORK_APP/EdgarGomes-3.7.2/node_modules/esprima
npm WARN rm not removing /Users/joaomartins/Documents/WORK_APP/EdgarGomes-3.7.2/node_modules/.bin/browserslist as it wasn't installed by /Users/joaomartins/Documents/WORK_APP/EdgarGomes-3.7.2/node_modules/browserslist
npm WARN rm not removing /Users/joaomartins/Documents/WORK_APP/EdgarGomes-3.7.2/node_modules/api-ecommerce/node_modules/grpc/node_modules/.bin/node-pre-gyp as it wasn't installed by /Users/joaomartins/Documents/WORK_APP/EdgarGomes-3.7.2/node_modules/api-ecommerce/node_modules/grpc/node_modules/node-pre-gyp

> fsevents@1.2.8 install /Users/joaomartins/Documents/WORK_APP/EdgarGomes-3.7.2/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download 
[fsevents] Success: "/Users/joaomartins/Documents/WORK_APP/EdgarGomes-3.7.2/node_modules/fsevents/lib/binding/Release/node-v67-darwin-x64/fse.node" is installed via remote

> grpc@1.18.0 install /Users/joaomartins/Documents/WORK_APP/EdgarGomes-3.7.2/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp WARN Using request for node-pre-gyp https download 
[grpc] Success: "/Users/joaomartins/Documents/WORK_APP/EdgarGomes-3.7.2/node_modules/grpc/src/node/extension_binary/node-v67-darwin-x64-unknown/grpc_node.node" is installed via remote

> styled-components@4.2.0 postinstall /Users/joaomartins/Documents/WORK_APP/EdgarGomes-3.7.2/node_modules/styled-components
> node ./scripts/postinstall.js || exit 0

Use styled-components at work? Consider supporting our development efforts at https://opencollective.com/styled-components
added 641 packages from 98 contributors, removed 306 packages, updated 1311 packages and audited 888572 packages in 29.827s
found 10 vulnerabilities (8 low, 2 moderate)

**Comment by binaryversion** [comment]
If I run again npm install:
npm WARN expo-google-sign-in@2.0.0 requires a peer of react-native@^0.55.4 but none is installed. You must install peer dependencies yourself.
npm WARN react-instantsearch-dom@5.4.0 requires a peer of react-dom@>= 15.3.0 < 17 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-reanimated@1.0.0-alpha.11 requires a peer of react@16.0.0-alpha.6 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-reanimated@1.0.0-alpha.11 requires a peer of react-native@^0.44.1 but none is installed. You must install peer dependencies yourself.
npm WARN styled-components@4.2.0 requires a peer of react-dom@>= 16.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN url-loader@1.1.2 requires a peer of webpack@^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.

audited 888572 packages in 10.973s
found 10 vulnerabilities (8 low, 2 moderate)

**Comment by almalizy** [comment]
no i got it 
for me i was had problem with expo and still had untill now with icons
after i used them tutorial it didn,t success with expo 
so
if y need expo please try to follow my steps
first setup other new project with expo
as y know ( expo-cli init your projectname )
then copy important files only from your mstore-expo file 
as src and app.js and config.js and package.json -but not all files 
then made npm install 
and expo start and it will be work fine 
also if y still had error setup yarn and use yarn

but if y want project only with pure react-native as it work with me 
just follow them instructure and will work fine

**Comment by binaryversion** [comment]
I will try, thank you.

**Comment by binaryversion** [comment]
Finally I found what is causing the issue.
When you unzip the project and change the directory you should copy the file over the command prompt.
There are some hidden files that are not copied and cause the problem.
