### ISSUE TITLE
Mstore Compile Error Refer to 4931

### ISSUE THREAD

**Issue by hdakei** [inspireui/support#5010]
Refer to reported issue #4931 on Github I have a problem with compile mstore in Magento as you said I sent my server information to your email, did you receive information? 

![Issue](https://i.ibb.co/YhhN4fL/Screenshot-20200908-182343.png)

+ Detail Issues: 
when I Compile in my Magento directory, I've one error that shows one class called from Display.php in   /srv/magento/public3/app/code/Mstore/PaymentResolver/Block/Display.php   that could not find Hyperpay\Extension\Block\Display', Would you solve this issue, please?

Thank you

Product & Version:1.7.7b
Flutter (or React Native) version: Flutter
Testing Device/Simulator: Android Simulator (API 29 Android 10)
My Magento version on local (Test) is 2.3.5 p1 and in our production, I'm using Magento 2.3.5 p2 (we already on test mod yet)

**Comment by minhcasi** [comment]
@hdakei - Please help us to raise this ticket to our new support ticket - http://support.inspireui.com - thank you for your time!
