### ISSUE TITLE
 Bug when entering the cart when an address has been added

### ISSUE THREAD

**Issue by jaime-hub** [inspireui/support#5012]
When I add an address and mark it as the default address, if I add a product to the cart and try to access the cart, I get an error. I leave a video with what happens...

+ Product & version: mstore-pro 4.0
+ Flutter (or React Native) version: React Native
+ Testing Device/Simulator: Android device
+ Screenshot issues (drag the file to attach here): 

Bug (vídeo): 
https://anonfiles.com/ddW9s5V6o4/bug_mp4

**_Step 2 (require): submit proof of purchasing the license on https://verify.inspireui.com **

I already opened a ticket on another occasion, you can check it, it's this: 

https://github.com/inspireui/support/issues/4038

**Comment by minhcasi** [comment]
@jaime-hub - pls help us to post this ticket to our new ticket support http://support.inspireui.com/
