### ISSUE TITLE
The login and Signup not working In Beonews

### ISSUE THREAD

**Issue by abhilashyadav04** [inspireui/support#5013]
**I am getting invalid login and password when trying to log in and when I try to signup nothing happens**

+ Product is Beonews 3.0.6

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
Please help us to post this ticket to our new ticket support http://support.inspireui.com - thank you!

**Comment by abhilashyadav04** [comment]
I can't see any option to add tickets on the new support channel
