### ISSUE TITLE
Banner Slider Image not loading image from assets

### ISSUE THREAD

**Issue by UsamaAltaf** [inspireui/support#5015]
I want to show images from assets not from url I don't know how to do it I tried all the methods but nothing 
![Capture](https://user-images.githubusercontent.com/48989371/93206066-3d008c80-f772-11ea-9188-7a79319b7515.PNG)

**Comment by minhcasi** [comment]
Please help us to post this ticket to our new ticket support http://support.inspireui.com - thank you!
