### ISSUE TITLE
Source Code and emulator don't reflect.

### ISSUE THREAD

**Issue by Cydo73** [inspireui/support#5016]
Hello there, i really like the work you have been doing, and appreciate the feedback i get from all of you. My application is almost done setting up, and a few more issues i just can't find my way around are standing in my way. Please let me know if you can find a solution for me.
1. I have written in my source code that i don't want texts to show under the category icons in the category field, but the texts show on the emulator and the look isn't very attractive. Let me know how to get rid of them please.
![shw txt](https://user-images.githubusercontent.com/69629505/93206665-70d3b600-f762-11ea-8e69-3f1dd0c35430.jpg)

2. I have written in my source code and fluxbuilder tool that i want my electronics and art collections section on my home feed to be "three columns". Nonetheless, they stay in "staggered", with the header image in the background whenever i scroll on the emulator. I have tried re-running and debugging, running flutter clean, but it just won't change. Please let me know how to combat this.
![elec](https://user-images.githubusercontent.com/69629505/93206681-77622d80-f762-11ea-8e5a-be2fc033361b.jpg)

3. I also have a problem with the logo in the login section. I followed the instructions on how to change the logo, but it still shows "Fluxstore" logo. Please let me know how i can deal with this issue. Thank you!
![login](https://user-images.githubusercontent.com/69629505/93206690-7a5d1e00-f762-11ea-8491-4b6cddb101f5.jpg)

**Comment by minhcasi** [comment]
Please help us to post this ticket to our new ticket support http://support.inspireui.com - thank you!
