### ISSUE TITLE
[ListApp] how to upload the android apk using keystore in expo ?

### ISSUE THREAD

**Issue by Pavithran10** [inspireui/support#502]
**We are looking for any contribution to improve the product features and quality, please let us know.**
hi, We are planning to release our android signing apk in goolge play console. But still now we are using expo build apk process only. But we are planned to release our own keystore process. so, how to get the keystore using expo to upload the apk in goolge play.

**Mandatory Info (please complete the following information):**
Product:[ListApp]
Version:1.6.1
Theme: MyListing
![Screenshot_1](https://user-images.githubusercontent.com/46148046/56187061-1d29de00-603f-11e9-82a9-e3d237246f21.png)

**Comment by thangvo9x** [comment]
Hi, You should let expo handle it all
OR you can process it. refer here 
https://docs.expo.io/versions/latest/distribution/building-standalone-apps/
Thanks

**Comment by Pavithran10** [comment]
yes, we only processed already check that docs but we don't know how to generate the own keystore into the project files.  **android -> app** project folder itself is not avaiable.
we generate keystore using keytool 
![Screenshot_2](https://user-images.githubusercontent.com/46148046/56199532-b7e3e600-605a-11e9-9ee7-53a972b16cf7.png)

**Comment by thangvo9x** [comment]
Hi. seems because the permissions on your pc. try set permission

**Comment by Pavithran10** [comment]
hi, what permission is need to provide on my pc.

**Comment by thangvo9x** [comment]
Hi. set perrmission for that folder/files. such as chmod command

**Comment by Pavithran10** [comment]
hi, how to remove/disable the introdata screen from the application.
