### ISSUE TITLE
Checkout issue + SKU not visible + sale label tag

### ISSUE THREAD

**Issue by Numan11** [inspireui/support#5022]
Hope so you are all fine i already said in previous tickets  my app is complete ready for production just stuck in 2 errors from last 5 days.

https://drive.google.com/file/d/1A5hiNOmD6h2mMBl97eZzf6xwHXD7YwEr/view

please watch this video 

issues checkout -> No such method the getter id was null 
issues  PRODUCT DETAIL PAGE -> SKU code not visible and in website sale tag is 50% but in app they show 49% please check your flutter builder for this problem

**Comment by minhcasi** [comment]
Please help us to post this ticket to our new ticket support http://support.inspireui.com - thank you!
