### ISSUE TITLE
Hyperpay\Extension\Block\Display' not found 

### ISSUE THREAD

**Issue by dev-hatsoff** [inspireui/support#5023]
sudo php bin/magento setup:di:compile
Compilation was started.
Repositories code generation... 1/8 [===>------------------------]  12% < 1 sec 78.5 MiBPHP Fatal error:  Class 'Hyperpay\Extension\Block\Display' not found in /var/www/html/megatech/app/code/Mstore/PaymentResolver/Block/Display.php on line 8

**Comment by minhcasi** [comment]
Please help us to post this ticket to our new ticket support http://support.inspireui.com - thank you!
