### ISSUE TITLE
what's the problem here?

### ISSUE THREAD

**Issue by metinemredonmez** [inspireui/support#5029]
We have moved to a new ticket support system, please post your new ticket on this link http://support.inspireui.com/

I couldn't solve this problem , my payment systems on the website and this error , I wonder if they can be related to each other , I constantly updated the same thing, I changed it, but there must be a way to do this, what should I do ?

1- ERROR 

![Ekran Resmi 2020-09-17 17 01 35](https://user-images.githubusercontent.com/54211029/93485053-4ffa9480-f90b-11ea-8044-8cb4391b2db8.png)

2- payment system general 

<img width="925" alt="Ekran Resmi 2020-09-17 17 26 56" src="https://user-images.githubusercontent.com/54211029/93484977-39543d80-f90b-11ea-9605-cf0efa9def29.png">
<img width="926" alt="Ekran Resmi 2020-09-17 17 27 04" src="https://user-images.githubusercontent.com/54211029/93484987-3ce7c480-f90b-11ea-9a17-73a29f488c3c.png">
<img width="920" alt="Ekran Resmi 2020-09-17 17 27 12" src="https://user-images.githubusercontent.com/54211029/93484995-3e18f180-f90b-11ea-91a6-946bd8abe2b8.png">

the problem is where do you think I should fix what??

**Comment by metinemredonmez** [comment]
and shipping method settings could I have made a mistake from here , maybe the problem is due to shipping ? Check please screenshots

![Ekran Resmi 2020-09-17 17 47 31](https://user-images.githubusercontent.com/54211029/93489213-e9c44080-f90f-11ea-927e-a74eace038e7.png)
<img width="924" alt="Ekran Resmi 2020-09-17 18 00 13" src="https://user-images.githubusercontent.com/54211029/93489216-eaf56d80-f90f-11ea-9991-a7f5965e2ea7.png">
<img width="962" alt="Ekran Resmi 2020-09-17 18 00 22" src="https://user-images.githubusercontent.com/54211029/93489223-ecbf3100-f90f-11ea-8956-dfe8e8ed2f14.png">
<img width="941" alt="Ekran Resmi 2020-09-17 18 00 37" src="https://user-images.githubusercontent.com/54211029/93489225-ed57c780-f90f-11ea-8bee-1b84dac473d6.png">
<img width="956" alt="Ekran Resmi 2020-09-17 18 00 53" src="https://user-images.githubusercontent.com/54211029/93489228-edf05e00-f90f-11ea-9db4-6e388cd70e6b.png">

**Comment by metinemredonmez** [comment]
<img width="1059" alt="Ekran Resmi 2020-09-17 21 23 40" src="https://user-images.githubusercontent.com/54211029/93511856-15552400-f92c-11ea-9515-0a7747b841a5.png">

**Comment by minhcasi** [comment]
We have moved to a new ticket support system, please post your new ticket on this link http://support.inspireui.com/
