### ISSUE TITLE
[ListPro] POST Tab issue

### ISSUE THREAD

**Issue by Poojakamble1317** [inspireui/support#503]
A. Refer to: https://gyazo.com/724c764538030b526da1665ddfb06ad6, in which 'POST' Tab is Deactivate

B. Refer to: https://listpro.now.sh/docs/getting-startedthe 'POST' tab is Activate. 
I am confused – should I use the setting “A” (Deactivate)  or, “B” (Activate)?

**Comment by thangvo9x** [comment]
Hi. Sorry for that problem . You should active POST tab . We'll update it right now.

**Comment by Poojakamble1317** [comment]
Thank you @thangvo9x
