### ISSUE TITLE
Error, does not start app MStore v4.0

### ISSUE THREAD

**Issue by Lopmar016** [inspireui/support#5030]
Does not start the app in the emulator
-executing the command react-native run android

![phone2](https://user-images.githubusercontent.com/70861539/93531752-c00a1a00-f90d-11ea-8f09-adee7b1e765b.PNG)

*Product & version: MStore v4.0
*Flutter (or React Native) version: React Native
*Testing Device/Simulator: Genymotion

**Comment by minhcasi** [comment]
We have moved to a new ticket support system, please post your new ticket on this link https://support.inspireui.com/
