### ISSUE TITLE
Blank product and categories screen; WooCommerce: FluxstoreMV 1.7.7

### ISSUE THREAD

**Issue by T3kken** [inspireui/support#5037]
Hi 
I am having issues! The app does not pull the products or categories. I get blank screens. I have tried to solve the issues but not getting anywhere. It has been a painful experience with your products.

Can you please help.

NB: I have tried you new ticketing system but does not save....the error is at the the top box on the form.

![Screenshot 2020-09-21 at 14 15 22](https://user-images.githubusercontent.com/20121759/93775830-cbfe2080-fc1a-11ea-81ec-7eed37e83737.png)

![Screenshot 2020-09-21 at 14 33 05](https://user-images.githubusercontent.com/20121759/93775860-d1f40180-fc1a-11ea-865a-3d3c8d96771b.png)

**Comment by minhcasi** [comment]
Duplicate of #5006

**Comment by T3kken** [comment]
FFS! you ticket system is not working!!!!!! 
Its very Frustrating that your app has so many problem yet the support is lacking!

![Capture](https://user-images.githubusercontent.com/20121759/93992122-126f8e80-fd85-11ea-81eb-c52050636d52.PNG)

**Comment by T3kken** [comment]
There is nothing to select.....I have used all known browsers.
