### ISSUE TITLE
Thumbnails are not appearing keeps loading 

### ISSUE THREAD

**Issue by nomicool** [inspireui/support#5040]
![Screenshot_1600768121](https://user-images.githubusercontent.com/25566185/93867717-e13e8200-fce2-11ea-887a-350c211d48d6.png)
even I have regenerated thumbnails on wordpress
We have moved to a new ticket support system, please post your new ticket on this link http://support.inspireui.com/

**Comment by minhcasi** [comment]
Duplicate of #5006

**Comment by nomicool** [comment]
man there is no solution on 5006 you are making it duplicate I can't figure out my solution on 5006
