### ISSUE TITLE
Crash when click an product in result of a search

### ISSUE THREAD

**Issue by Theappnow** [inspireui/support#5045]
Error case: When I click a product in home page, detail product screen show. After that, I return home page, and move to tab Category, click a item of categories displaying on screen, and after product list screen display, back to home page. Finally, I move to tab Search, search with a key word, in list result I click a item, crash occur.
Error log as below:

════════ Exception caught by scheduler library ═════════════════════════════════════════════════════
The following assertion was thrown during a scheduler callback:
There are multiple heroes that share the same tag within a subtree.

Within each subtree for which heroes are to be animated (i.e. a PageRoute subtree), each Hero must have a unique non-null tag.
In this case, multiple heroes had the following tag: <default FloatingActionButton tag>

Here is the subtree for one of the offending heroes: Hero
  tag: <default FloatingActionButton tag>
  state: _HeroState#ab088
When the exception was thrown, this was the stack: 
#0      Hero._allHeroesFor.inviteHero.<anonymous closure> (package:flutter/src/widgets/heroes.dart:268:11)
#1      Hero._allHeroesFor.inviteHero (package:flutter/src/widgets/heroes.dart:279:8)
#2      Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:298:21)
#3      SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5861:14)
#4      Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:311:15)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

However, I found reason of error. It's default hero tag, is null, use in multiple FloatingActionButton at SmartChat when load SmartChat in continuos progresses. (Here is searching progress and loading product detail progress)
Therefore, I resloved this error, by fix another herotag with another FloatingActionButton in another progress
Thanks.

**Comment by minhcasi** [comment]
Greetings from InspireUI 🎉
To improve user experience during support, we are announcing that a new ticket support system is available on this link https://support.inspireui.com - we will stop support on this Github ticket and migrate to a new system.
