### ISSUE TITLE
please fix fast and dont send me the same solutions from ticket  #4956 i tried everything it didnt work 

### ISSUE THREAD

**Issue by rasnza** [inspireui/support#5046]
We have moved to a new ticket support system, please post your new ticket on this link http://support.inspireui.com/
9/23/20
09:08	Gradle sync started

09:09	Gradle sync failed: Could not find com.android.tools:r8:1.5.25.
			Searched in the following locations:
			- https://dl.google.com/dl/android/maven2/com/android/tools/r8/1.5.25/r8-1.5.25.pom
			- https://jcenter.bintray.com/com/android/tools/r8/1.5.25/r8-1.5.25.pom
			- http://storage.googleapis.com/r8-releases/raw/com/android/tools/r8/1.5.25/r8-1.5.25.pom
			Required by:
			project :
			Consult IDE log for more details (Help | Show Log) (1 m 9 s 301 ms)

**Comment by minhcasi** [comment]
Greetings from InspireUI 🎉
To improve user experience during support, we are announcing that a new ticket support system is available on this link https://support.inspireui.com - we will stop support on this Github ticket and migrate to a new system.
