### ISSUE TITLE
Error while closing the App

### ISSUE THREAD

**Issue by minndfreakanime** [inspireui/support#5047]
Hi,

We are using static splash screen, while closing the app, we are getting the below error. Screenshot is also attached.
The source code and admin account is same as uploaded for issue#4913. Please check the issue at earliest. Please let us know if you want us to send the code again.

The following NoSuchMethodError was thrown building StaticSplashScreen(dirty, state: _StaticSplashScreenState#740bb):
The method 'startsWith' was called on null.
Receiver: null
Tried calling: startsWith("http")

The relevant error-causing widget was: 
  StaticSplashScreen file:///D:/Github%20repo/DoorDrop/source/lib/app_init.dart:174:18
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      _StaticSplashScreenState.build (package:fstore/widgets/common/static_splashscreen.dart:32:33)
#2      StatefulElement.build (package:flutter/src/widgets/framework.dart:4663:28)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4546:15)
#4      StatefulElement.performRebuild  #(package:flutter/src/widgets/framework.dart:4719:11)

![image](https://user-images.githubusercontent.com/20972844/93988988-fc72c580-fda6-11ea-8fcd-a285c4bd6708.png)

**Comment by metinemredonmez** [comment]
make the shipping section false from the General Settings, then it improves, they don't support it from here, I think they closed my ticket

**Comment by minhcasi** [comment]
Greetings from InspireUI 🎉
To improve user experience during support, we are announcing that a new ticket support system is available on this link https://support.inspireui.com - we will stop support on this Github ticket and migrate to a new system.
