### ISSUE TITLE
[Beonews] photo size in post 

### ISSUE THREAD

**Issue by hadi13** [inspireui/support#505]
Product: [Beonews]
Your Purchased Code: 2b7fa788-ea4d-4d1c-bb3a-4bf22a499783

Describe the issues
I have an issue with the images inside the posts, it looks like wider in app view

**Comment by luyx2412** [comment]
Hi @hadi13 Can you provide the screenshot about the image?

Thanks

**Comment by hadi13** [comment]
![attachment](https://user-images.githubusercontent.com/2642454/56266305-8d466b80-60f4-11e9-9b38-afa23df65ba6.png)
see how it looks like

**Comment by minhcasi** [comment]
this is the minor issue that we will update it later - thanks

In the meantime you can fix at the components/Webview/index.js - thanks

**Comment by minhcasi** [comment]
this is the minor issue that we will update it later - thanks

In the meantime you can fix at the components/Webview/index.js - thanks
