### ISSUE TITLE
[MStore] Installing step 2

### ISSUE THREAD

**Issue by Islamdiab** [inspireui/support#506]
**Mandatory Info (please complete the following information):**
 - Product: [MStore Pro]
 - Your Purchased Code: [ba2f4fb7-ae39-4d13-815c-c3d9cd06fa82]
(we may not reply if you are not our customer)

**Describe the issues**
While the installation wizard, I faced an issue in step 2 in the required plugin, I can't install them.

**Screenshots**
https://droppy.ijdcreatives.com/HYvggA1l

**Comment by luyx2412** [comment]
Hi @Islamdiab You can install it with manual.
- https://brew.sh/ (Homebrew)
- https://nodejs.org/en/ (NodeJS)
- https://yarnpkg.com/lang/en/ (Yarn)
- https://docs.expo.io/versions/v32.0.0/introduction/installation/ (Expo)

Thanks


<blockquote><img src="https://brew.sh/assets/img/homebrew-social-card.png" width="48" align="right"><div><img src="/assets/img/favicon.ico" height="14"> Homebrew</div><div><strong><a href="https://brew.sh/">Homebrew</a></strong></div><div>The missing package manager for macOS (or Linux).</div></blockquote>
<blockquote><img src="https://nodejs.org/static/images/logo-hexagon-card.png" width="48" align="right"><div><img src="/static/favicon.png" height="14"> Node.js</div><div><strong><a href="https://nodejs.org/en/">Node.js</a></strong></div><div>Node.js® is a JavaScript runtime built on Chrome's V8 JavaScript engine.</div></blockquote>
<blockquote><img src="https://yarnpkg.com/assets/og_image.png" width="48" align="right"><div><img src="/favicon.ico" height="14"> Yarn</div><div><strong><a href="https://yarnpkg.com/en/">Yarn</a></strong></div><div>Fast, reliable, and secure dependency management.</div></blockquote>
<blockquote><div><strong><a href="https://docs.expo.io/versions/v32.0.0/introduction/installation/">Installation - Expo Documentation</a></strong></div></blockquote>

**Comment by Islamdiab** [comment]
Thanks, it works fine, but I got another error while running IOS and Android, “cebuilder.sh” can’t be opened because Sandbox is not allowed to open documents in Terminal. any advice?

Screenshot: 
https://droppy.ijdcreatives.com/vhX5EHv5

**Comment by minhtruong315** [comment]
Hi @Islamdiab 
Can you share me teamviewer? I will help you check it.
Thanks

**Comment by Islamdiab** [comment]
1 471 569 030
q83h4v

**Comment by Islamdiab** [comment]
Hello

I am still waiting for your support!

**Comment by minhcasi** [comment]
@Islamdiab pls add this skype for note support for this ticket - skype: minhtruong315
Thank you!

**Comment by PRQAE** [comment]
@Islamdiab same problem

**Comment by minhcasi** [comment]
@PRQAE - please help to open a new ticket if it still not work - thank you!
