### ISSUE TITLE
[BeoNews] Android setup in beonews

### ISSUE THREAD

**Issue by hadi13** [inspireui/support#507]
Product: [Beonews]
Your Purchased Code: 2b7fa788-ea4d-4d1c-bb3a-4bf22a499783

Describe the issues
I have an issue with Android, if I setup using cebuilder and then run the app the metro packager is not running and app configuration is not setup and the app runs without any data !!

**Comment by minhcasi** [comment]
Hi, could you try with latest CeBuilder - https://inspireui.com - thanks

**Comment by hadi13** [comment]
i am trying using the latest version

**Comment by hadi13** [comment]
@minhcasi any solution!!! I am waiting for this to submit my app

**Comment by luyx2412** [comment]
HI @hadi13 Can you give me the screenshot about the issue?

Thanks

**Comment by hadi13** [comment]
see screenshots below, and even the metro packager is not running, even I have changed the website to my site and when I run the app it shows no data, as I did nothing

![1](https://user-images.githubusercontent.com/2642454/56340204-e75d3480-61b9-11e9-9cef-22346d05fef4.PNG)
![2](https://user-images.githubusercontent.com/2642454/56340205-e7f5cb00-61b9-11e9-9101-deb0eeb74d74.PNG)

**Comment by hadi13** [comment]
I am getting this now when I generate apk and run on my real device,
https://i.postimg.cc/D0kzg9hd/Screenshot-20190418-164102.jpg

but when I run on emulator it works fine

**Comment by luyx2412** [comment]
HI @hadi13 You can use real device with debug tool to check the issue. https://docs.mstore.io/api-and-project-structure#debug-app-with-reacttotron

Thanks

**Comment by hadi13** [comment]
still not figuring it out, the app works perfect on emulator and real devices lower than api 27, but on my device Galaxy s9+ is not working !!!

**Comment by hadi13** [comment]
still ignoring !!

**Comment by hadi13** [comment]
please guys, I need your support in this matter, the app works on all devices except the Android 9, I tried many things without luck

**Comment by hadi13** [comment]
I will pay for this, just fix the issue

**Comment by minhcasi** [comment]
We will check on android 9 and let you know, thanks
