### ISSUE TITLE
Send Node Modules

### ISSUE THREAD

**Issue by Pars1vaLl** [inspireui/support#508]
- Product:ListApp
 - Your Purchased Code: 85059e37-2ddd-478d-899b....

Howdy team,

Pease send me Node Modules. It misses some files while installing the package. Here is the screen of the issue: http://prntscr.com/ndkfk5

Here is my previous post: https://github.com/inspireui/support/issues/440

I have written to this emal: thang@beostore.io

Thanks:)

**Comment by Pars1vaLl** [comment]
> * Product:ListApp
> * Your Purchased Code: 85059e37-2ddd-478d-899b....
> 
>  Hi team,

Pease send me Node Modules. It misses some files while installing the package. Here is the screen of the issue: http://prntscr.com/ndkfk5

Here is my previous post: https://github.com/inspireui/support/issues/440#event-2261480552

**Comment by thangvo9x** [comment]
It's here 
https://we.tl/t-aEahzNOkEm
Thanks

**Comment by Pars1vaLl** [comment]
Hi,
 
It didn`t help. I replaced node_modules — it still occures error. I`m using Mylisting theme. Please help
 
Thanks
  
>Четверг, 18 апреля 2019, 14:20 +05:00 от Tony Vo <notifications@github.com>:
> 
>It's here
>https://we.tl/t-aEahzNOkEm
>Thanks
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread . 
 
 
--
unknown hero
