### ISSUE TITLE
[ListApp] Api.createcomment Response: Invalid cookie. Use 'generate_auth_cookie ' method in 

### ISSUE THREAD

**Issue by DNeelanshi** [inspireui/support#509]
**Required Info (please complete the following information):**
 - Product ListApp
I have purchased the code from https://codecanyon.net/item/listapp-listing-directory-mobile-app-by-react-native/21456447?s_rank=3

**Describe the bug**
Api create comment is giving response invalid cookie, use 'generate_auth_cookie' method.

**Screenshots**

**Additional context**
I am using the theme listable. While giving comment on any post the api is giving error of INVALID COOKIE. Please help.
![Screen Shot 2019-04-18 at 4 14 19 PM](https://user-images.githubusercontent.com/32795046/56355889-13e27200-61f5-11e9-823a-ed17e4dbecf3.png)

**Comment by DNeelanshi** [comment]
Please some one help.

**Comment by thangvo9x** [comment]
Hi guys. Thanks for your choice for our product. Let me know your AppConfig.json such as your backend info for checking, plz?

**Comment by DNeelanshi** [comment]
HY THANKS FOR REPLYING. YES I CAN SHARE MY APP CONFIG.JSON  .HERE IT IS:

{
  "Website": {
    "url": "http://innovativegeeks.gangtask.com/wowtrip/",
     "consumerKey": "ck_3becccaf5a7b570236e1f3411fe768f20b2df14c",
     "consumerSecret": "cs_ad1149a7f836ee8bc10256d9a874443838f084dd"
  },
  "Theme": "listable",
  "MainColor": {
    "tabbarTint": "#189AA2",
    "tabbarColor": "#D5D8DE",
    "mainColorTheme": "#189AA2",
    "tabbar": "#fff"
  }
}

**Comment by thangvo9x** [comment]
Hi guys. Do you have been your email for sending (the source code)? 
Thanks

**Comment by DNeelanshi** [comment]
> Hi guys. Do you have been your email for sending (the source code)?
> Thanks

yes, we can send you the source code of app. Please send your email id.

**Comment by DNeelanshi** [comment]
> Hi guys. Do you have been your email for sending (the source code)?
> Thanks

This functionality is not working even in the  code we have purchased, so please check the code of app you have for sale, and please try to help us out solving this issue.
thanks in advance

**Comment by DNeelanshi** [comment]
Hello, did you checked it @thangvo9x

**Comment by DNeelanshi** [comment]
> Hi guys. Do you have been your email for sending (the source code)?
> Thanks

Hello there, please check the source code of listapp 1.6.1 and help us out from this bug. We will be thankful.

**Comment by thangvo9x** [comment]
Hi. You should update to the latest version . We've a big update to v1.7. Thanks

**Comment by DNeelanshi** [comment]
> Hi. You should update to the latest version . We've a big update to v1.7. Thanks

Hello, thanks for your reply, but in new update, how can i give review and rating to the post?. I am unable to find the functionality on screen anymore.

**Comment by thangvo9x** [comment]
Huh? what do your mean? You must log in to review it.

**Comment by DNeelanshi** [comment]
> Huh? what does your mean? You must log in to review it.

Thanks for your reply. I have checked and compared the code and did the changes.But it is still giving me the same error that invalid cookie. I have find out that the file WPUserAPI.js  , there is a function of login 
" login: async (username, password) => 
  {
    const nonce = 'inspireui';
    const _url = `${url}/api/mstore_user/generate_auth_cookie/?second=${cookieLifeTime}&username=${username}&password=${password}${secure}&nonce=${nonce}`
    return await request(_url)
  },"
here the nonce has used which is "inspireui" and our app is now on our server. May be this is creating conflict in cookie generation.

Please take a look in issue , what should I use in nonce to make it work
thanks.
I shall be thankful

**Comment by thangvo9x** [comment]
Please share AppConfig.json for checking, I'll check and reply ASAP. Thanks

**Comment by DNeelanshi** [comment]
On Thursday, 25 April, 2019, 3:21:22 pm IST, Tony Vo <notifications@github.com> wrote:  
 
 
Please share AppConfig.json for checking, I'll check and reply ASAP. Thanks

**Comment by thangvo9x** [comment]
I tested with your config. 
this a video
https://gyazo.com/8846722630f4a83264b53f9482221635
Thanks
