### ISSUE TITLE
[CeStore] Admin panel web socket connection issue

### ISSUE THREAD

**Issue by kashifdg** [inspireui/support#510]
**Required Info (please complete the following information):**
 - Product: [CeStore]
 - Your Purchased Code: e08a2654-3932-4af5-820a-b7f6587421f5

**Describe the bug**
After deploying the app on a server i'm constantly getting the error of web socket connection failed, HTTP Authentication failed, no valid credentials available every few seconds. would really appreciate any help with this issue.

**Screenshots**
https://imgur.com/a/DYFai0J

**Additional context**
app-973cfca075b5406b0048.js:1 WebSocket connection to 'ws://cestoreapi.digitalgravity.ae/ws/dashboard?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzY29wZXMiOlsiYWRtaW4iXSwianRpIjoiNWIyYjFjZjc5MTIzYzA0MmJjNjFmNDQxIiwiZW1haWwiOiJrYXNoaWZAZGlnaXRhbGdyYXZpdHkuYWUiLCJpYXQiOjE1NTUzMjk0NjksImV4cCI6MTU5MTMyNTg2OX0.vB439a-FyGaodnOCQuAPavzf8RCzmCz0Gv0ZNQzzCh0' failed: HTTP Authentication failed; no valid credentials available
u @ app-973cfca075b5406b0048.js:1
t.connectToWebSocket @ app-973cfca075b5406b0048.js:1
(anonymous) @ app-973cfca075b5406b0048.js:1
i @ app-973cfca075b5406b0048.js:1
n @ app-973cfca075b5406b0048.js:1
(anonymous) @ app-973cfca075b5406b0048.js:1
(anonymous) @ app-973cfca075b5406b0048.js:1
app-973cfca075b5406b0048.js:1 WebSocket connection closed with code: 1006.

**Comment by minhtruong315** [comment]
Hi @kashifdg share me teamviewer?

**Comment by kashifdg** [comment]
sure please check skype

**Comment by minhtruong315** [comment]
https://github.com/cezerin/cezerin/tree/master/config
Please check production config
