### ISSUE TITLE
[ListApp] - I can not install correctly. 

### ISSUE THREAD

**Issue by damianlluch** [inspireui/support#511]
**Mandatory Info (please complete the following information):**
 - Product: [e.g. MStore, ListApp]
 - Your Purchased Code: [get from https://codecanyon.net/downloads]
(we may not reply if you are not our customer)

**Describe the issues**

**Screenshots**

**Additional context**

https://github.com/inspireui/support/issues/499

It is the second problem that closes and the problem continues, you have to wait for the customer's response to close any problem. If you close the problem again without a solution, I will ask for the refund of my money in CodeCanyon.

**Comment by damianlluch** [comment]
In the issue close for you says "you can remove it App/Navigation/index.js and remove Home text".
You can it more specific?

**Comment by damianlluch** [comment]
I can't see images in home app, logo and portrait image isn't my wordpress.

**Comment by thangvo9x** [comment]
Hi. The issues hold over 48hours from the previous comment, we'll remove it. Please read the guide on our channel support. We've only support installing and run your app, and this problem is out of scope our support . Hope you see. Thanks

**Comment by damianlluch** [comment]
Hello, really closes the problems on the same day as the last comment ... I reviewed 10 pages and discovered that more people have the same problems as me ... and I see that some people do not agree with your product.
On your Facebook it says "We will post a video tutorial ..." and people wait for your video.
Please answer my questions in the last comment if you are professional or do not respond if you continue with your attitude.

**Comment by minhcasi** [comment]
@damianlluch did you update the latest version with the video note include?

1. New - compatible with new Jobify template, demo site - http://jobify.inspireui.com
2. New - 10x values with new redesign UI homepage, please check detail document from https://docs.inspireui.com/listapp/theme/
3. Add - new document link https://docs.inspireui.com/listapp and we will keep improving it
4. Add - new video A-Z video guide - https://youtu.be/DhygvqSsAKs -  (will continues update)
5. Add - Whatsapp button at listing detail
6. Improve - performance and loading modal
7. Update - refactor for easier to connect more Listing template
8. Update - fix minor bug and UI improvement
9. Update - latest expo library and related libraries

Some missing image could cause by this issue & solution: https://github.com/inspireui/support/issues/1#issuecomment-469964000

Let us know if it does not work on your case then we will process the refund for you, thanks

**Comment by damianlluch** [comment]
HI @minhcasi
I try with your information and I update this issue tomorrow.
It's a answer appropriate for your clients.

thanks

**Comment by damianlluch** [comment]
I tried the new version, and on the home page of the application I can see better appearance, but when I click on the card, this error appears.

![image](https://user-images.githubusercontent.com/1463804/56864129-17c57f80-69bf-11e9-822e-5982973fb4b6.png)


![image](https://user-images.githubusercontent.com/1463804/56864017-d7193680-69bd-11e9-9fd7-05849b427d28.png)


How can the template be deleted with the text "Introduction to ListApp"?
In my WooCommerce (MyListing) the ListApp configuration appears. What is the configuration required in your plugin? I do not see any documentation with the correct configuration in this section.

Thank you!

**Comment by thangvo9x** [comment]
Hi. Try to replace below file at Components/Detail/ListingData/
p/s: change .txt -> .js 
[index.txt](https://github.com/inspireui/support/files/3136549/index.txt)
you can remove it in Config/MyListing.js find to key  "horizontalLayout"
<img width="548" alt="config" src="https://user-images.githubusercontent.com/23457178/57054224-63c53c80-6cbd-11e9-9564-baf0ccbb2af0.png">
you can config via CeBuilder App at https://inspireui.com/
Thanks

**Comment by damianlluch** [comment]
I always tried CeBuilder, and also only expo, and the result is not corrected.
I try now with your instructions.
I have changed the index.js file, but with MyListing.js on line 49, HorizontalLayout, the idea is to leave the variable empty, right?

example:

Horizontal design: [
]

**Comment by damianlluch** [comment]
In home App

![image](https://user-images.githubusercontent.com/1463804/57104976-edaaef00-6d29-11e9-8ab5-5368dba8a7f1.png)

**Comment by thangvo9x** [comment]
Hi.  You have only removed a row with the text "Introduce... ", NOT ALL in horizontalLayout key.
The error could be fixed by updating the plugin ListApp Mobile Manager to the latest version. Thanks

**Comment by damianlluch** [comment]
I follow your instructions, in categories tab I can access a page of client, but in home page app, when I click, I get the same error

![image](https://user-images.githubusercontent.com/1463804/57155382-96655700-6ddb-11e9-851d-2ee0dd32c3df.png)

For that are the bottoms of colors? How are configured?

![image](https://user-images.githubusercontent.com/1463804/57155274-52725200-6ddb-11e9-8319-5268918c6752.png)

**Comment by thangvo9x** [comment]
Try to replace seperate files below files
+ Replace this file at Components/Detail/ListingData/
[index.txt](https://github.com/inspireui/support/files/3143975/index.txt)
+ Replace this file at Container/Home/CategoryLinks/
[Item.txt](https://github.com/inspireui/support/files/3143976/Item.txt)
+ Replace this file at Container/Home/CategoryIcons/
[Item.txt](https://github.com/inspireui/support/files/3143977/Item.txt)
=> P/s : REMEMBER  change .txt -> .js
Thanks
