### ISSUE TITLE
[ListApp] Need more details about JWT Authentication

### ISSUE THREAD

**Issue by urasuji** [inspireui/support#512]
**Mandatory Info (please complete the following information):**
 - Product: ListApp
 - Your Purchased Code: 356e79dc-c9af-45f2-9b27-ef1b52ca6088

**Describe the issues**
App is not working properly

**Screenshots**
https://docs.inspireui.com/listapp/getting-started/
3. Setting Wordpress
!!!I need more details on this part!!!

**Additional context**
Exactly where on htaccess file should I add these codes?

RewriteEngine on
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule ^(.*) - [E=HTTP_AUTHORIZATION:%1]

Would you provide me an example htaccess file?

Also I found wp_block on Tools/Rest API Controller.
Should I keep it active?

Thank you,

**Comment by thangvo9x** [comment]
Hi. Thanks for the advice. The document is list detailed. 
RewriteEngine on
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule ^(.*) - [E=HTTP_AUTHORIZATION:%1]
=> IN this block <IfModule></IfModule>
SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1
=> OUT <IfModule></IfModule>
Thanks
