### ISSUE TITLE
Screen category MS Store

### ISSUE THREAD

**Issue by Jegufull** [inspireui/support#513]
**Required Info (please complete the following information):**
 - Product: [e.g. MStore, ListApp]
 - Your Purchased Code: [get from https://codecanyon.net/downloads]
(we may not reply if you are not our customer)

**Describe the bug**

**Screenshots**

**Additional context**
Add any other detail logs about the problem here.
If possible please share your config.js that use for the app setting

**Comment by Jegufull** [comment]
Product: [MStore-Pro]
Purchased Code: [36e9cfd7-96da-413e-b43f-83ef03bed15b]

With the last update of woocommerce, when doing the update of the database, in the screen of category no longer load the images of the categories, what can I do to solve it?

**Comment by Jegufull** [comment]
II made the downgrade of the woocomerce plugin to 3.5.8 so that it would work again, another thing I found is that it loads the names of the categories in reverse order (z-a on woocommerce 3.6.1).

The woocommerce 3.6.1 plugin is not as compatible with the app

**Comment by minhcasi** [comment]
Hi, there is not regenerate image method that uses for boost app performance, please help to check this guide - https://docs.inspireui.com/mstore/woo-setting/

**Comment by Jegufull** [comment]
It did not work, the problem is woocommerce version 3.6.X

**Comment by minhcasi** [comment]
Could you help to share your latest config file (common/index.js and the AppConfig.json)? We will help for debugging this issue, this may the issues from the website API - thanks

**Comment by Jegufull** [comment]
I attach the files, thanks for your help

[package.json.zip](https://github.com/inspireui/support/files/3119491/package.json.zip)
[Config.js.zip](https://github.com/inspireui/support/files/3119492/Config.js.zip)

**Comment by minhcasi** [comment]
Hi, sorry for the delay issues, we have tested your app config but could not replicate the issues, it seems you have managed to resolve the issue, could you share your solution to fix it. Thank you!

**Comment by Jegufull** [comment]
Hello, I did the woocommerce update to version 3.6.2 and it worked again, the problem was with the woocommerce plugin 3.6.0 and 3.6.1. Thanks for your help.

**Comment by minhcasi** [comment]
Thank you for your sharing :)
