### ISSUE TITLE
[MStore MV] not all vendors are shown - WCFM plugin

### ISSUE THREAD

**Issue by MrFaisal100** [inspireui/support#514]
**Required Info (please complete the following information):**
 - Product: [MStore MV]
 - Your Purchased Code: [bd25c21b-0cdc-49dc-9b41-42c9c9071557]

**Describe the bug**
I installed all the needed ext. 
My Marketplace is WCFM .. I noticed that the app does not show all the vendors in the vendor list only two .. does not retrieve the banners, names and addresses also .. I am not sure what to do to get all the list? (note: I did not do any changes in the backend

here is my app config

**Comment by MrFaisal100** [comment]
also I noticed the app is very slow
and the payment gateway did not work as described here 
https://docs.mstore.io/faq-and-troubleshooting 
first method redirect me to empty page
the second method I am using wordoress 5.1.1 and did not recognize the template and did not show up in the templete selector .. I am not sure if there are extra steps I should follow?

**Comment by minhcasi** [comment]
Hi, the first release of WCFM integration will not support for the Vendor List (as some limit of current WCFM API), you can disable the Vendor feature at the config file (at the bottom of the file).

It's ok with our testing for the app performance, could i know what is your OS device ? You many need to run the Re-generate image to optimize the app loading image, please follow this guide - https://docs.inspireui.com/mstore-mv/getting-started/

**Comment by minhcasi** [comment]
Btw, could you share your config file so that we could have a check the issues from your website - thanks

**Comment by MrFaisal100** [comment]
??

**Comment by thangvo9x** [comment]
Are u using WCFM? now vendorTab cannot get vendor, you can disable it in Config/index.js

**Comment by MrFaisal100** [comment]
I asked about the payment gateway its not working
the payment gateway did not work as described here
https://docs.mstore.io/faq-and-troubleshooting
first method redirect me to empty page
the second method I am using wordoress 5.1.1 and did not recognize the template and did not show up in the templete selector .. I am not sure if there are extra steps I should follow?

**Comment by thangvo9x** [comment]
Share with us your info backend. I'll config it help me on wordpress version 5.1.1

**Comment by MrFaisal100** [comment]
How to share it?

**Comment by MrFaisal100** [comment]
how to share it and what info you need exactly?

**Comment by thangvo9x** [comment]
Hi. you can share to our email  thang@inspireui.com

**Comment by MrFaisal100** [comment]
sent

**Comment by MrFaisal100** [comment]
its been 3 days and havent received a reply to my email yet

**Comment by minhcasi** [comment]
@MrFaisal100 - sorry for some delay as we have big holiday here with 5 days off

Please note that the WCFM vendor could be display as it is not support from the API, please disable the vendor list from the config.js - we are working on the API and will upgrade it on next version release, mark the ticket as enhancement - thanks

**Comment by MrFaisal100** [comment]
I am talking about the payment gateway issue mot the list of vendors

**Comment by MrFaisal100** [comment]
reminder

**Comment by minhcasi** [comment]
@MrFaisal100 we will check and get back you on tomorrow 

Sorry for some delay as the team is only holiday break (5 days off) and back on tomorrow. 

Thank you!

**Comment by thangvo9x** [comment]
Hi. I checked & configed on your Config, I create a new account & try checkout a product. result as below image.
<img width="1245" alt="checkout" src="https://user-images.githubusercontent.com/23457178/57054980-49419200-6cc2-11e9-99ba-d3387d3b6d04.png">
Hi. You can fix by go to Container/Cart/Payment and replace this file
[index.txt](https://github.com/inspireui/support/files/3136608/index.txt)
p/s: change .txt -> .js
Thanks

**Comment by MrFaisal100** [comment]
Thanks I will try it
