### ISSUE TITLE
[ListPro] TypeError: TypeError: undefined is not an object (for Ref. Link)

### ISSUE THREAD

**Issue by theAlinux** [inspireui/support#515]
for this => https://codecanyon.net/item/listpro-listing-directory-react-native-template/22645013/comments?page=6&filter=all#comment_21913917

`TypeError: TypeError: undefined is not an object (evaluating ‘post.totalRate’) This error is located at: in ColumnLayout (at PostLayout/index.js:60)`

its works at version 1.3.1, i got some datas but i get the error at v1.3.3

AppConfig.json
```
{
  "Website": {
    "url": "http://bestrestaurants.directory",
    "consumerKey": "ck_b6de8b6e8f******************************",
    "consumerSecret": "cs_c7439a0a81******************************"
  },
  "Theme": "restaurant",
  "MainColor": {
    "tabbarTint": "rgb(27, 229, 141)",
    "tabbarColor": "#D5D8DE",

    "mainColorTheme": "#D5D8DE",
    "tabbar": "#FFF"
  }
}
```

Restaurant.js
```
/** @format */

import Constants from '../Constants'
import Languages from '../Languages'

const {
  listing,
  categoryIcons,
  categoryShadow,
  categoryLinks,
  news
} = Constants.Components

export default {
  AppName: 'ListPro',

  // default language from the Languages.js file
  Language: 'en',

  /**
   * Step 1: Change your Wordpress & WooCommerce site URL - move to appConfig.jsos
   */

  /**
   * Step 2: config image and default layout post
   *      enable: false -> to load dynamic from the Wordpress by using the ListApp Manager plugin
   */
  Local: {
    enable: false,

    /**
     * The main layout app homepage
     *    1: Horizontal Layout which is loaded the below HorizonLayout
     *    2: Vertical Layout which is used below verticalLayout
     *    3: Mansory layout
     */
    homepageLayout: 1,

    verticalLayout: 2,

    /**
     * HorizonLayout: show the horizontal layout config, show as the default homepage
     *    - component: kind of components(listing, map, news)
     *    - features: the type id from Listing blog, from Admin site click Listing/Features/edit the type and get tags_id from the browser URL
     *    - categoryListingId: the category id
     *    - location: the location id
     *    - row: the number of row support on the list, default is one row
     *    - paging: blog per page from swiping, default is false
     *    - layout: support 8 kind of layouts: banner, twoColumn, threeColumn, threeColumnHigh, list, listRight, card, flexColumn
     *      (flexColumn is flexible column layout that you can config both width & height)
     * Banner: option to show the banner home page, default visible is true
     */

    BannerHeader: {
      image: require('@images/banner/banner3.jpg'),
      enable: true,
      large: false,
      showLeftMenu: false
    },
    horizontalLayout: [
      { 
        component: 'categoryLinks', 
        name: 'What can we help you find?',
      },
      
      {
        component: listing,
        name: 'Introducing ListApp Plus',
        description: 'A selection of homes verified for quality and design',

        imageBanner: require('@images/banner-hotel.png'),
        layout: Constants.Layout.bannerImage,
        height: 177,
        full: true,
        category: '27',
      },
      {
        component: listing,
        name: 'Features',
        description: 'Book activities led by local host on your next trip',
        layout: Constants.Layout.twoColumn,
        features: '17',
      },
      
      {
        component: 'admob',
      },
    ],

    VerticalLayout: {
      name: 'Recent experiences',
      layout: Constants.Layout.twoColumn,
    },



    menu: [
      {
        route: 'home',
        name: 'explore',
      },
      {
        route: 'setting',
        name: 'setting',
      },
      {
        route: 'customPage',
        params: {
          title: 'Contact',
          url: 'https://inspireui.com/about',
        },
        name: 'contact',
      },
      // {
      //   route: 'customPage',
      //   params: {
      //     id: 19951,
      //     title: 'About Us',
      //     url: '',
      //   },
      //   name: 'About Us',
      //   icon: 'assignment',
      // },
      {
        route: 'login',
        name: 'login',
      },
    ],
    general: {
      /**
       *    General config for the app
       *    Firebase: Config to store user Favorites location
       *    Facebook: config for Facebook ads
       *    AdMob: config for Admob ads
       */
      Firebase: {
        apiKey: 'AIzaSyAZ*************************',
        authDomain: 'beonew*********.firebaseio.com',
        databaseURL: 'https://beo*******f.firebaseio.com',
        storageBucket: 'beo*********.appspot.com',
        messagingSenderId: '10***********',
        readlaterTable: 'li********',
        //apiKey: 'AIzaSyC6_JIrg********************',
        //authDomain: 'lis********',
        //databaseURL: 'https://lis**********.firebaseio.com',
        //storageBucket: 'lis***********.appspot.com',
        //messagingSenderId: '91***********',
        //readlaterTable: 'lis*********',
      },
      Facebook: {
        visible: true,
        adPlacementID: '180982**************',
        logInID: '1809************',
        sizeAds: 'standard', // standard, large
      },
      AdMob: {
        visible: true,
        deviceID: 'pub-21***********',
        unitID: 'ca-app-pub-2101182*************',
        unitInterstitial: 'ca-app-pub-2101182**************',
        isShowInterstital: true,
      },
    },
  },

  /**
   * dynamic screen UserProfile screen menu
   */
  userProfileMenu: [
    {
      label: Languages.userProfilePrivacy,
      routeName: 'customPage',
      params: {
        id: 10941,
        title: Languages.userProfilePrivacy,
      },
    },
    {
      label: Languages.userProfileContact,
      routeName: 'customPage',
      params: {
        id: 10941,
        title: Languages.userProfileContact,
      },
    },
    {
      label: Languages.userProfileAbout,
      routeName: 'customPage',
      params: {
        url: 'http://inspireui.com',
      },
    },
  ],
}
```

**Comment by luyx2412** [comment]
HI @theAlinux Please provide your purchase code.

Thanks

**Comment by theAlinux** [comment]
> HI @theAlinux Please provide your purchase code.
> 
> Thanks

where? if you mean panel of the wordpress site, i did but i get same error

**Comment by thangvo9x** [comment]
Hi. you can find your purchase code here 
https://codecanyon.net/downloads
such as share AppConfig.json file in Common folder and info backend for checking, plz?
Thanks

**Comment by theAlinux** [comment]
> Hi. you can find your purchase code here
> https://codecanyon.net/downloads
> such as share AppConfig.json file in Common folder and info backend for checking, plz?
> Thanks
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/c5a18223816825ebf6c0fec648742882ecbb6a7b/68747470733a2f2f6173736574732e73686f7066726f6e742e656e7661746f2d7374617469632e636f6d2f696d616765732f6d6574612f6c6f676f732f636f646563616e796f6e2e706e67"><img alt="" height="14" src="https://camo.githubusercontent.com/c75d968dba11187d74e09644791494a4418ce2d8/68747470733a2f2f6173736574732e73686f7066726f6e742e656e7661746f2d7374617469632e636f6d2f69636f6e732f636f646563616e796f6e2e6e65742f66617669636f6e2e69636f"> CodeCanyon**[Buy Plugins & Code from CodeCanyon](https://codecanyon.net/)**Discover 28,674 Plugins, Code and Script for Bootstrap, Javascript, PHP, Wordpress, HTML5 and more. Save time, buy Code on CodeCanyon!

purchase code => 1dd628d2-bc70-452c-9c04-14ed31c4f5e1

**Comment by thangvo9x** [comment]
Please check your domain . read document guide and make sure they are work
<img width="732" alt="Screen Shot 2019-04-26 at 9 47 46 AM" src="https://user-images.githubusercontent.com/23457178/56780159-68df4300-6808-11e9-9871-34515e84a71f.png">
Thanks

**Comment by theAlinux** [comment]
i did but i get same error
![Simulator Screen Shot - iPhone Xʀ - 2019-04-27 at 09 58 59](https://user-images.githubusercontent.com/10341948/56852749-940c8400-6927-11e9-93dd-56d08e8231d7.png)

**Comment by chad-the-first** [comment]
I do have a similar problem, what's happening is that I'm getting the listing_data in a scrambled like in the picture:
![Sketch](https://user-images.githubusercontent.com/17035853/56921333-35cdd580-6ace-11e9-9922-462437ce28cb.png)

and that's why I'm getting undefined in the listing:
![Sketch1](https://user-images.githubusercontent.com/17035853/56921382-4ed68680-6ace-11e9-8033-e6526bb338b1.png)

Why am i getting the listing data this way and how to fix this problem??

**Comment by thangvo9x** [comment]
Please update to the latest the plugin 
you find here: https://wordpress.org/plugins/listapp-mobile-manager/
Thanks, let me know your result. Sorry for the delay the issue because the team is on holidays. 
Hope u see.

**Comment by theAlinux** [comment]
updated but error not change

**Comment by thangvo9x** [comment]
Send me your info hosting for checking, thang@inspireui.com Thanks
subject email is 515

**Comment by thangvo9x** [comment]
Hi. We sent an email to you. Please check. Thanks

**Comment by theAlinux** [comment]
hi, works thanks but don't get image thumbnail


![Ekran Alıntısı](https://user-images.githubusercontent.com/10341948/57179226-10511b00-6e84-11e9-9a0f-7de8e3db824c.PNG)




![Ekran Alıntısı2](https://user-images.githubusercontent.com/10341948/57179228-16df9280-6e84-11e9-9936-bb12a1e360b2.PNG)

**Comment by theAlinux** [comment]
also when i compile the app no error first but i have other compiles get same errors ( https://github.com/inspireui/support/issues/515#issuecomment-487302984 )
just i did these changed;
1- android and ios bundleIdentifier change
2- splash image change
3- set "enable: true" at Restaurants.js

**Comment by thangvo9x** [comment]
Hi. Give me your info admin for checking?

**Comment by theAlinux** [comment]
please, check your email

**Comment by thangvo9x** [comment]
Hi. Try again. I configured your website.

**Comment by theAlinux** [comment]
failed,  please, i want to solution asap


![Ekran Alıntısı](https://user-images.githubusercontent.com/10341948/57194541-c7b36380-6f50-11e9-9dcd-9c809ea11f0a.PNG)

**Comment by theAlinux** [comment]
hey , set "Local: enable: true" get data from wordpress site, works, why did it happen?

**Comment by thangvo9x** [comment]
Are your website on working? Yes. Local: true => Using Restaurant.js/Classic.js Or you can using CeBuilder.

**Comment by theAlinux** [comment]
yes, website is working. i used Restaurant.js, not CeBuilder
