### ISSUE TITLE
[Mstore] white area in the category products at the end.

### ISSUE THREAD

**Issue by mkashifrazzaq11** [inspireui/support#517]
**Required Info (please complete the following information):**
 - Product: [e.g. MStore, ListApp]
MStore Pro version
f8d919b7-3308-4d8c-a454-6b2685fbae9c
(we may not reply if you are not our customer)

**Describe the bug**
When i open every category i got white area at the end of last products,
i post the videos link with it you can watch the problem.

**Screenshots**
https://www.youtube.com/watch?v=v7YvGgWtNJ4
**Additional context**
Add any other detail logs about the problem here.
[common.zip](https://github.com/inspireui/support/files/3101550/common.zip)

**Comment by luyx2412** [comment]
Hi @mkashifrazzaq11 You meant the last product have big white space?

Thanks

**Comment by mkashifrazzaq11** [comment]
Please watch the videos for better understanding.

**Comment by luyx2412** [comment]
Hi @mkashifrazzaq11 I watched your video, but could not understand what you meant. Please clearly your meant.

Thanks

**Comment by mkashifrazzaq11** [comment]
As you watched in the video the unnecessary blank white area which is right after the last product named as (Ma-n0 cat food beef). I want this white area to be removed as soon as possible.

**Comment by luyx2412** [comment]
HI @mkashifrazzaq11 You can edit in `src/containers/Category/index.js` line `33` follow the image. Edit `paddingBottom` to fix the issue.
![image](https://user-images.githubusercontent.com/8909619/56631292-e70fde00-667e-11e9-87e2-943b0faa90f5.png)

Thanks

**Comment by mkashifrazzaq11** [comment]
I changed the value up and down but nothing happened.

**Comment by luyx2412** [comment]
Hi @mkashifrazzaq11 Please use `react-native-debugger` to debug element UI 
![image](https://user-images.githubusercontent.com/8909619/56705637-ee48f180-673b-11e9-9bd3-9931df4fb328.png)

https://github.com/jhen0409/react-native-debugger#react-native-debugger

Thanks
