### ISSUE TITLE
[Beonews Pro] The Rest API is not working correctly !

### ISSUE THREAD

**Issue by pramaanamlive** [inspireui/support#518]
**Mandatory Info (please complete the following information):**
 - Product: BeoNews Pro
 - Your Purchased Code: a06b2816-495d-4e90-aea5-a3826664995d

**Describe the issues**
In the CEBuilder, it is stating Rest Api is not working correctly!

**Screenshots**
![Screenshot 2019-04-22 at 5 05 26 AM](https://user-images.githubusercontent.com/49845943/56475644-97ce7f80-64bd-11e9-93a9-57ec1407e262.png)

**Comment by minhcasi** [comment]
Hi, could you try to config the Wordpress Plugin base on this guide - https://docs.inspireui.com/beonews/wordpress-setting/ - thanks

**Comment by pramaanamlive** [comment]
Yes done. Still have no idea whats wrong.
