### ISSUE TITLE
Listapp 1.7.0 issues

### ISSUE THREAD

**Issue by reconshield** [inspireui/support#519]
The new update is Awesome. new UI and Homepage is great. i think this is more stable.thanks to development team.
but i found 1 minor bugs.hopefully you guys can solve it

1) user cant post listing..after select image/contents.i getting server error...check attachment

![Simulator Screen Shot - iPhone X - 2019-04-22 at 15 59 19](https://user-images.githubusercontent.com/25501496/56490427-cb3df800-6517-11e9-9232-0f6f7331b1d7.png)

Awesome Work! Thanks...only found this minor issues!

**Comment by thangvo9x** [comment]
Hi. Can u share your AppConfig.json such as your admin to check them, plz ?

**Comment by reconshield** [comment]
can i have your email id?

**Comment by thangvo9x** [comment]
thang@inspireui.com

**Comment by thangvo9x** [comment]
/inspireui/support/issues/531
