### ISSUE TITLE
registration not work as vendor

### ISSUE THREAD

**Issue by alaradi2006** [inspireui/support#52]
**Mandatory Info (please complete the following information):**
 - Product: [e.g. MStore, ListApp]
 - Your Purchased Code: [get from https://codecanyon.net/downloads]
(we may not reply if you are not our customer)

**Describe the issues**
i build the apk with expo 
sign up process work well but signing up as customer or as vendor its the same will be as customer 
i cant access the vendor dashboard 
ho to fix it 
**Screenshots**

**Additional context**
Add any other detail logs about the problem here.

**Comment by minhcasi** [comment]
The Vendor dashboard is not supported from the app at the current version

**Comment by alaradi2006** [comment]
how its multivendor and nots supported they saulyee i can list product from the app

________________________________
