### ISSUE TITLE
[Beonews Pro] Clicking on post gives error

### ISSUE THREAD

**Issue by trappat** [inspireui/support#520]
**Required Info (please complete the following information):**
Product: BeoNews Pro
Your Purchased Code: bb904f63-d575-4586-9afd-b7d283e357ff
(we may not reply if you are not our customer)

**Describe the bug**
When clicking on a post, it gives this error

**Screenshots**
https://imgur.com/a/ceptFjk

**Comment by luyx2412** [comment]
HI @trappat Something was wrong with animation, can comment the code in line `98` follow the image to check again. 
![image](https://user-images.githubusercontent.com/8909619/56548695-ee65b780-65aa-11e9-89a4-997b6db10583.png)

Thanks
