### ISSUE TITLE
[Listapp] Whatsapp

### ISSUE THREAD

**Issue by reconshield** [inspireui/support#521]
How to set whatsapp no and use it in 1.7.0?

**Comment by luyx2412** [comment]
Hi @reconshield Sorry i could not understand what you meant. Can you describe specific?

Thanks

**Comment by reconshield** [comment]
I have add whatsapp no in new field. But its
Not call and when i click whatsapp icon no action. Its that whatsapp function call mobile no from default contact no or i need to create new field? 

My address also not display.

**Comment by thangvo9x** [comment]
Whatapps get from fields of that listing on your site. You must add a field to your listings.

**Comment by reconshield** [comment]
![Edit Listing Type ‹ Indiansbiz — WordPress](https://user-images.githubusercontent.com/25501496/56706575-12aacb00-6748-11e9-83d8-53fd5617854b.png)

i have create this field..and add whatsapp no too..but i cant use whatsapp button..action null..
any documentation how to solve this?

**Comment by thangvo9x** [comment]
Access to your theme, ex MyListing theme
follow the image
http://prntscr.com/ngj6j1
Thanks
