### ISSUE TITLE
[ListApp] how to remove the introdata pages

### ISSUE THREAD

**Issue by Pavithran10** [inspireui/support#522]
**Mandatory Info (please complete the following information):**
Product:[ListApp]
Version:1.6.1
Theme: MyListing

**Describe the issues**
how to remove/disable the introdata screen in the application

**Comment by thangvo9x** [comment]
Go to App/RootRouter.js and find this block to remove it 
<img width="286" alt="Screen Shot 2019-04-24 at 7 18 10 PM" src="https://user-images.githubusercontent.com/23457178/56658818-cae35f80-66c5-11e9-8677-539cec29ed55.png">
Thanks
