### ISSUE TITLE
[Beonews] Metro bundler is not building js files in android 

### ISSUE THREAD

**Issue by hadi13** [inspireui/support#523]
Product: [Beonews]
Your Purchased Code: 2b7fa788-ea4d-4d1c-bb3a-4bf22a499783

Describe the issues
I have a react native project and when I change the code in the JS files and run the app the Metro Bundler is not working! Metro bundler stuck like this tried to deleted android.index.js file in the assets and same !

https://i.stack.imgur.com/OLJcA.png

**Comment by luyx2412** [comment]
Hi @hadi13 Can you take the screenshot the issue?

Thanks
