### ISSUE TITLE
 [ListApp] 29 EUR subtitle

### ISSUE THREAD

**Issue by bobozd** [inspireui/support#524]
**Describe the issues**
Please send me instructions on how to remove 29EUR subtitle text added by the Listapp mobile app (not my listing Wordpress theme) on some listings. It appears on some listings component layout. Please let me know how to remove it from all.

![Screen Shot 2019-04-24 at 10 47 45](https://user-images.githubusercontent.com/28021993/56646356-afedfc80-667f-11e9-811a-66a795620167.png)

**Comment by thangvo9x** [comment]
Hi. you can remove this block as below image
<img width="495" alt="block" src="https://user-images.githubusercontent.com/23457178/56658634-4f81ae00-66c5-11e9-8741-7a39f50b5eff.png">
Thanks

**Comment by bobozd** [comment]
I remove it already by removing these lines of code, but after Listapp 1.7 update it appears again.
It seems it's hidden somewhere else in the code also.

**Comment by thangvo9x** [comment]
Yes, you can hidePrice at PostLayout/index.js 
remove all hidePrice property.

**Comment by minhcasi** [comment]
Closed ticket of #526 #527 #529

@bobozd pls update just one ticket for your all issues to prevent the messy from github board and help us focus to support your better - thanks

**Comment by thangvo9x** [comment]
https://github.com/inspireui/support/issues/533
