### ISSUE TITLE
[ListPro] Loading spinner 

### ISSUE THREAD

**Issue by chad-the-first** [inspireui/support#525]
**We are looking for any contribution to improve the product features and quality, please let us know.**
A clear and concise description of what the idea is. Ex. I would love to have this feature [...]

**Mandatory Info (please complete the following information):**
 - Product: [ListPro]

Is there a loading spinner that I can activate because it's really confusing when I switch between categories and I see the listings of the past one for like 2 seconds.

**Comment by thangvo9x** [comment]
Hi. I don't see your issue, Can you snapshot them, plz ?Thanks

**Comment by chad-the-first** [comment]
when I enter one category I get these listings:
![Sketch](https://user-images.githubusercontent.com/17035853/56661443-67980400-66aa-11e9-9bf1-5ec0c1545815.png)
but when I go back and enter another category I still see these listings for a few seconds until i get the result of  the new api response:
![Sketch1](https://user-images.githubusercontent.com/17035853/56661549-9f06b080-66aa-11e9-9660-3e22788b2aac.png)
when i get the result of the api the page refreshes and i see the listings that I should see:
![Sketch2](https://user-images.githubusercontent.com/17035853/56661584-b8a7f800-66aa-11e9-970e-93196ff211e6.png)

so what I asking is that is there a loading spinner that I can activate or add so that when I enter the other category I wont see the result of the old api?

**Comment by thangvo9x** [comment]
Try replace this file at Container/Category folder 
[index.txt](https://github.com/inspireui/support/files/3116071/index.txt)
p/s: change tag .txt -> .js 
Thanks

**Comment by chad-the-first** [comment]
i got this error:
![Sketch](https://user-images.githubusercontent.com/17035853/56753959-70650480-6794-11e9-9922-1a51435c554c.png)

**Comment by thangvo9x** [comment]
Hi. Do you have an update to the latest version, plz? 
Please remove node_modules and run yarn again.
Thanks

**Comment by chad-the-first** [comment]
it worked thx
