### ISSUE TITLE
[ListApp] Icons Color

### ISSUE THREAD

**Issue by bobozd** [inspireui/support#527]
From where I can change default green active icons color on the app bottom?

![Screen Shot 2019-04-24 at 14 40 47](https://user-images.githubusercontent.com/28021993/56660173-41209b80-669f-11e9-935f-14b755d8e780.png)

**Comment by bobozd** [comment]
left menu background color also ???

![Screen Shot 2019-04-24 at 14 47 12](https://user-images.githubusercontent.com/28021993/56660502-e9366480-669f-11e9-89ab-2792cbd371bc.png)

**Comment by bobozd** [comment]
also, how to change this red category font color ?

![Screen Shot 2019-04-24 at 15 26 45](https://user-images.githubusercontent.com/28021993/56663065-821bae80-66a5-11e9-87d9-72aa2c837bc3.png)

**Comment by thangvo9x** [comment]
> From where I can change default green active icons color on the app bottom?
> 
> ![Screen Shot 2019-04-24 at 14 40 47](https://user-images.githubusercontent.com/28021993/56660173-41209b80-669f-11e9-935f-14b755d8e780.png)

=> You can edit it navigation/index.js (attach image)
<img width="383" alt="issue1" src="https://user-images.githubusercontent.com/23457178/56705625-e1c49900-673b-11e9-8e0b-4d6767587ecb.png">

**Comment by thangvo9x** [comment]
> left menu background color also ???
> 
> ![Screen Shot 2019-04-24 at 14 47 12](https://user-images.githubusercontent.com/28021993/56660502-e9366480-669f-11e9-89ab-2792cbd371bc.png)

=> Edit it in Components/LeftMenu/style.js 
<img width="357" alt="Screen Shot 2019-04-25 at 9 26 56 AM" src="https://user-images.githubusercontent.com/23457178/56705720-5992c380-673c-11e9-955b-cf9f2f4d30f5.png">

**Comment by thangvo9x** [comment]
> also, how to change this red category font color ?
> 
> ![Screen Shot 2019-04-24 at 15 26 45](https://user-images.githubusercontent.com/28021993/56663065-821bae80-66a5-11e9-87d9-72aa2c837bc3.png)
=> When config in horizontalLayout has a property with name textColor. you could change it.

**Comment by bobozd** [comment]
thnx, I can't find line of code for changing last red CATEGORY fonts color? please point to file and code line. thnx.
