### ISSUE TITLE
[ListPro] TypeError: null is not an object (evaluating 't.better_featured_image.source_url')

### ISSUE THREAD

**Issue by theAlinux** [inspireui/support#528]
i get this error TypeError: null is not an object (evaluating 't.better_featured_image.source_url') at ios, already white screen at android, but i should first solve problem at ios

all config settings => https://github.com/inspireui/support/issues/515

**Comment by luyx2412** [comment]
Hi @theAlinux Please provide your purchase code.

Thanks

**Comment by thangvo9x** [comment]
https://github.com/inspireui/support/issues/515
