### ISSUE TITLE
[ListApp] Top Margin

### ISSUE THREAD

**Issue by bobozd** [inspireui/support#529]
How can I add more top-padding or top-margin on posts loaded from blog section of WP site.
Top status bar of android or iOS overlap with the header feature image of the post. screenshots attached. I wan't same margin as on left-rift sides to be applied on top also.

![android](https://user-images.githubusercontent.com/28021993/56682029-f61c7d80-66ca-11e9-8bc6-0104a46921d8.png)
![ios](https://user-images.githubusercontent.com/28021993/56682037-fc125e80-66ca-11e9-955a-d547a1909264.png)

**Comment by thangvo9x** [comment]
Hi. You can edit it Components/ParaSwiper/styles.js 
Thanks
