### ISSUE TITLE
how to change home layout color 

### ISSUE THREAD

**Issue by alaradi2006** [inspireui/support#53]
**Mandatory Info (please complete the following information):**
 - Product: [e.g. MStore, ListApp]
 - Your Purchased Code: [get from https://codecanyon.net/downloads]
(we may not reply if you are not our customer)

**Describe the issues**
theres 4 color but there sno description how to change the color for main menu
**Screenshots**

**Additional context**
Add any other detail logs about the problem here.

**Comment by minhcasi** [comment]
You can customize the common/color.js file - thanks
