### ISSUE TITLE
[ListApp] icons and app assets not showing

### ISSUE THREAD

**Issue by jacktheruck** [inspireui/support#530]
- Product: [ListApp]
 - Your Purchased Code: Ends with 77e8d638
(we may not reply if you are not our customer)

I've started working with your latest installing video and finished my site setup but when I try to build the app with expo this is the result >>

https://i.imgur.com/5inynnE.png

Icons that located on assets/images folder not showing.
I didn't edit any of your code except adding my site api info and as you can see there's a problem with the app assets.

I've disabled debugging mode from constant.js file.

**Comment by thangvo9x** [comment]
Hi.
IMPORTANT: update latest Expo 31 which could cause VERY SLOW at development mode (as you will get the "require cycle: " warning, please remove the IF block from node_modules/metro/src/lib/polyfills/require.js (https://gyazo.com/df9e8c80e88d51fed30807b0a369e7e1) - Or, select the build with PRODUCTION MODE to resolve the issues)

<blockquote><img src="https://i.gyazo.com/thumb/1200/df9e8c80e88d51fed30807b0a369e7e1-png.jpg" width="48" align="right"><div><img src="https://assets.gyazo.com/favicon.ico" height="14"> Gyazo</div><div><strong><a href="https://gyazo.com/df9e8c80e88d51fed30807b0a369e7e1">Gyazo</a></strong></div><div>&nbsp;</div></blockquote>
