### ISSUE TITLE
[Listapp] map location and gallery images not fetching in app.

### ISSUE THREAD

**Issue by Pavithran10** [inspireui/support#532]
**Required Info (please complete the following information):**
Product:[ListApp]
Version:1.6.1
Theme: MyListing

**Describe the bug**
hi, In Listapp map location and gallery images inside the list is not fetching. Last time also we reported this same issue you only solved this problem but that same problem is repeating again and this problem is come under in our wordpress site but where and why is the issue is occuring we don't know. 
This time we lauched the app into the playstore after that we faced this same kind of issue. We need the permanently solution for this problem ASAP. 
thanks

**Screenshots**
![issue1](https://user-images.githubusercontent.com/46148046/56711555-e6437e80-6748-11e9-8ddb-f956a8e09383.png)
![issue2](https://user-images.githubusercontent.com/46148046/56711561-eba0c900-6748-11e9-95a8-2891b250a9df.png)

**Comment by thangvo9x** [comment]
Do you try to run the plugin Regenerate Thumbnails? Can you share AppConfig.json for checking, plz?

**Comment by Pavithran10** [comment]
hi, I've attached the app.json file.
[prj.zip](https://github.com/inspireui/support/files/3115978/prj.zip)

**Comment by thangvo9x** [comment]
Hi. I checked and debug this error on your site.
<img width="1417" alt="Screen Shot 2019-04-26 at 9 43 11 AM" src="https://user-images.githubusercontent.com/23457178/56779999-c3c46a80-6807-11e9-8444-a96ca20bae4d.png">
Gallery Images are getiing normally
<img width="502" alt="Screen Shot 2019-04-26 at 9 42 57 AM" src="https://user-images.githubusercontent.com/23457178/56780008-c9ba4b80-6807-11e9-8bac-bfee428e4496.png">
Thanks

**Comment by Pavithran10** [comment]
hi, already our Listapp Manager is updated only we can't update anymore. 

![list1](https://user-images.githubusercontent.com/46148046/56785044-0e96b000-6811-11e9-9778-543c6ba77cb9.png)
![list2](https://user-images.githubusercontent.com/46148046/56785052-135b6400-6811-11e9-8a57-e96330e7ef2d.png)

**Comment by Pavithran10** [comment]
hi, and then I checked in **old version 1.6.1** and tested in **latest version 1.7.0** in that appconfig.json I've intergrated the site url, its shows error while clicking the list. In both version images not fetched.

![err](https://user-images.githubusercontent.com/46148046/56786258-042ae500-6816-11e9-9ad3-d0cb00a1cb77.png)

**Comment by thangvo9x** [comment]
Hi. Try to replace this file at Components/Detail/ListingData/ 
let me know your result.
[index.txt](https://github.com/inspireui/support/files/3123377/index.txt)
Thanks

**Comment by Pavithran10** [comment]
hi, sorry for the late reply I've replaced and checked that file index.js. but.still now images is not fetched. thanks

**Comment by Pavithran10** [comment]
hi, anybody is there two days left no one else can't reply for my issue.

**Comment by thangvo9x** [comment]
Try to update to the latest version the plugin https://wordpress.org/plugins/listapp-mobile-manager/
Let me know your result.
Thanks

**Comment by Pavithran10** [comment]
hi, I've downloaded the latest version listapp-mobile-manger plugin then updated in our wordpress admin. but still now it's not recovered the same problem is occuring. thanks

**Comment by thangvo9x** [comment]
Can you share AppConfig.json such as your info admin for checking, plz?
Thanks

**Comment by Pavithran10** [comment]
hi, I've attached our admin info details in below AppConfig.json file.
[prj.zip](https://github.com/inspireui/support/files/3137309/prj.zip)

**Comment by thangvo9x** [comment]
Hi. Gallery Images is fetching normal on your app? Ah Huh? 
<img width="502" alt="app" src="https://user-images.githubusercontent.com/23457178/57119669-30a2ac00-6d96-11e9-815d-ced1388ba955.png">
Thanks

**Comment by Pavithran10** [comment]
hi, Now in overall app all images is not visible.  
![img1](https://user-images.githubusercontent.com/46148046/57120895-ea4b4e00-6d91-11e9-9038-9319af604b60.png)
![img2](https://user-images.githubusercontent.com/46148046/57120910-ff27e180-6d91-11e9-9b85-a4e25f1a6ac9.png)
![img3](https://user-images.githubusercontent.com/46148046/57120924-0a7b0d00-6d92-11e9-8799-dd2032910f24.png)
![img4](https://user-images.githubusercontent.com/46148046/57120933-14047500-6d92-11e9-9702-3ddb2ca95564.png)
![img5](https://user-images.githubusercontent.com/46148046/57120939-1b2b8300-6d92-11e9-99ea-44d76c18e0a6.png)

**Comment by Pavithran10** [comment]
> Hi. Gallery Images is fetching normal on your app? Ah Huh?
> <img alt="app" width="502" src="https://user-images.githubusercontent.com/23457178/57119669-30a2ac00-6d96-11e9-815d-ced1388ba955.png">
> Thanks

Form your side how it's working tell the reason too. we know the reason for our reffers.  thanks

**Comment by thangvo9x** [comment]
Hi. Do you have run Regenerate Thumbnails plugins from Tools tab?
The new source is a different code than the old version. We're using cover image for display feature image. 
Thanks

**Comment by Pavithran10** [comment]
hi, already regenerate thumbnails plugin is activated only in tools tab.

I've attached the error pages before comment. you are seen our screenshot what problem we faceing **first gallery images only not fetched** now **overall cover images is not fetched** all are not visible in the app. please check that. thanks.

**Comment by thangvo9x** [comment]
Hi. Please check an email which sent to you.

**Comment by Pavithran10** [comment]
hi, you are config now in dancestudiyos project files using latest version. All the time you are config and changing the project files itself. Already we've launched **our app in old version 1.6.1 this version theme only our app dancestudiyos domain is running on live recently** . so that we can't able update this new version of source now . **so, please config our old version 1.6.1 project file.**

And then you config sended this **new dancestudiyos domain source also fetched only cover and gallery images problem is solved still now map location is not fetched in this new domain**.

Note:  Actually the **problem is comes under our wordpress admin site** please check our site creditional. but you are config our dancestudiyos domain in new version of project source.

**Comment by thangvo9x** [comment]
Hi. All Plugins are updated to serve for the latest version. Please update to the latest version. We can't support this old version. The new version is faster and improves the performance of your app. Thanks

**Comment by Pavithran10** [comment]
ok, Actually you are config and sended the source right in that also problem is not solved fully in that also map location not fetching. I think problem is not resolve still. so, please check our admin site creditional i've already attached your mail.

**Comment by thangvo9x** [comment]
1/ Related post cover images aren't fetched.
=> Replace this file at App/Components/PostLayout/ReadMore/
[index.txt](https://github.com/inspireui/support/files/3155428/index.txt)
and 
=> Replace this file at App/Components/PostLayout
[index.txt](https://github.com/inspireui/support/files/3155432/index.txt)
p/s: change .txt -> .js
2/ Review comment send button is not working.
=> Give me a user for check this. 
3. In category list tab gridview few images is not fetched. => Try access to that category and update category Banner Image.

**Comment by Pavithran10** [comment]
thanks, related and category grid images issues are solved. 

**2/ Review comment send button is not working.
=> Give me a user for check this means what I need to give**

**Comment by Pavithran10** [comment]
hi, still more issue is there want to resolve that also.
bug:
1.In app userprofile screen **navigation drawer option** is there for that option **icon is visible** to use. but in the home screen **drawer is working, icon is not visible.** 
2.In **related post and recents item** details **rating star** option is there but **rating doesn't work**.

![err4](https://user-images.githubusercontent.com/46148046/57356923-50b7de00-718f-11e9-95fd-1bf57aca299b.png)
![err5](https://user-images.githubusercontent.com/46148046/57356932-557c9200-718f-11e9-92d9-9c6d6fb11202.png)
![err6](https://user-images.githubusercontent.com/46148046/57357086-c15efa80-718f-11e9-8486-d9be3064b1d1.png)

**Comment by Pavithran10** [comment]
hi, Two days left no one can't reply now a days response is too later. so, please reply ASAP.

**Comment by thangvo9x** [comment]
Hi. 
1. We have an option to enable it.
go to MyListing. and find this section
<img width="846" alt="Screen Shot 2019-05-10 at 1 49 34 PM" src="https://user-images.githubusercontent.com/23457178/57508016-893fef00-732a-11e9-9b22-c87697364692.png">
2. Replace this file at Components/Rating/
[index.txt](https://github.com/inspireui/support/files/3165210/index.txt)
p/s:  .txt -> .js
Thanks

**Comment by Pavithran10** [comment]
hi, what about the review send button.
=> Give me a user for check this means what I need to give . you're sended this msg but i didn't understood.

**Comment by thangvo9x** [comment]
Hey. I want a user for test this. 
<img width="502" alt="Screen Shot 2019-05-13 at 9 45 33 AM" src="https://user-images.githubusercontent.com/23457178/57593045-e4105b00-7563-11e9-8801-f7ee545b6c79.png">
I can't create a user on your website because that function was disabled.
Please enable it. Thanks

**Comment by Pavithran10** [comment]
hi, I've enable that user register option now you can able to work. Please be carefully while changing anything in the website because last week only we updated latest version of app recently in googe play now it's on live. 
bugs: 
1. In the **review page comment option** is there in that **"send" button functionality** not working.
2. In **home screen phone back button** option is not working. such as **we can't close the app.**

thanks

**Comment by thangvo9x** [comment]
Hi. I checked on your AppConfig.json. Please check JWT Plugin on your website
<img width="516" alt="Screen Shot 2019-05-13 at 3 14 11 PM" src="https://user-images.githubusercontent.com/23457178/57605880-da055100-7591-11e9-9a67-838cae581bb2.png">
refer here: https://docs.inspireui.com/listapp/getting-started/#jwt-authentication
Thanks

**Comment by Pavithran10** [comment]
hi, this is error while affecting the send button in review page and then what changes want to do. I checked but can't understood clearly. thanks

**Comment by thangvo9x** [comment]
hi. It is mean. You must config JWT plugin for working correctly before. User must log in before do else.

**Comment by Pavithran10** [comment]
ok, I've the another issue also phone back is not working in home screen while we can't close the app. thanks

**Comment by thangvo9x** [comment]
HI. Could you share .htaccess file on your website? seem you config not correctly with JWT plugin.
Refer more: 
https://docs.inspireui.com/listapp/getting-started/#jwt-authentication

**Comment by Pavithran10** [comment]
hi, I've attach our htaccess file below please check.
[htaccess.docx](https://github.com/inspireui/support/files/3189967/htaccess.docx)

**Comment by thangvo9x** [comment]
Hi. Refer to our document guide and follow step by step.
your .htaccess
 
<img width="665" alt="Screen Shot 2019-05-17 at 2 30 00 PM" src="https://user-images.githubusercontent.com/23457178/57910819-59579500-78b0-11e9-8558-b7c4fa2629f5.png">
AND OUR DOCUMENT
<img width="965" alt="Screen Shot 2019-05-17 at 2 30 05 PM" src="https://user-images.githubusercontent.com/23457178/57910823-5a88c200-78b0-11e9-9059-e6abd0ca14ef.png">

Thanks
