### ISSUE TITLE
[ListApp] Issues

### ISSUE THREAD

**Issue by bobozd** [inspireui/support#533]
Hi I want to:
1. remove booking as I do not need it for now.
2. remove or make it functioning whatsApp icon, for now it's only icon without any function
3. change color of LOGIN and SIGNUP buttons.

![Screen Shot 2019-04-25 at 09 43 27](https://user-images.githubusercontent.com/28021993/56718943-10447300-6740-11e9-9f53-c0d11610dd3b.png)

![Screen Shot 2019-04-25 at 09 52 59](https://user-images.githubusercontent.com/28021993/56718923-0753a180-6740-11e9-8316-c0a84b319f12.png)

**Comment by bobozd** [comment]
screenshot
![Screen Shot 2019-04-25 at 09 43 27](https://user-images.githubusercontent.com/28021993/56718392-f22a4300-673e-11e9-9050-0e7670741d9c.png)

**Comment by thangvo9x** [comment]
1. remove booking as I do not need it for now.
=> We can enable/disable in Config/index.js with Booking property.
2. remove or make it functioning WhatsApp icon, for now, it's the only icon without any function
=> forward to Components/Detail/Footer.js 
and remove content in that function 
<img width="489" alt="Screen Shot 2019-04-25 at 3 26 31 PM" src="https://user-images.githubusercontent.com/23457178/56721177-8a8bec00-676e-11e9-85e7-cf5a53924e72.png">

3. change color of login and SIGNUP buttons.
=> go to Container/LogIn/styles.js 
textTab / activeTab property
Thanks

**Comment by bobozd** [comment]
thanks. everything works except 3. there is no any color for Login or Sign button.
![Screen Shot 2019-04-25 at 09 52 59](https://user-images.githubusercontent.com/28021993/56721732-c9f21280-6745-11e9-84a6-99d13b090cd5.png)

**Comment by bobozd** [comment]
Also please help me edit MyListing.js file single listing INFO section. I think it can be done with using default fields from MyListing theme and just insert it into KEY section in MyListing.js file but I don't know default fields used in mylistingtheme for this fields.

I would like to have:

-REGION           / Europe
- COUNTRY     / Croatia
- CITY               /Zadar 

currently I have:

    {
      section: 'Info',
      type: 'data',
      icon: Images.icons.iconTable,
      data: [
        {
          key: '_country',
          name: 'Country',
        },
        {
          key: '_rooms',
          name: 'Rooms',
        },
        {
          key: '_bathrooms',
          name: 'Bathrooms',
        },
        {
          key: '_beds',
          name: 'Beds',
        },
        {
          key: '_price-per-day',
          name: 'Price Per Day',
        },
        {
          key: '_job_duration',
          name: 'Job Duration',
          unit: 's',
        },
        {
          key: '_job_expires',
          name: 'Job Expire',
        },
      ],
    },

Please help me edit this section.

**Comment by bobozd** [comment]
5. I can't see where is the CHAT FUNCTION as you show it far in 1.4 version?
Can users chat with each other, is this function implemented as described?

![listapp](https://user-images.githubusercontent.com/28021993/56723214-d166eb00-6748-11e9-9659-6b329645fcbf.png)

**Comment by bobozd** [comment]
6. how can I decrease ZOOM LEVEL on map? I would like to have it zoomed out 30-40%

![Screen Shot 2019-04-25 at 10 57 43](https://user-images.githubusercontent.com/28021993/56723361-18ed7700-6749-11e9-9dd1-10262e705975.png)

**Comment by bobozd** [comment]
how to change RED text color for listing categories ?

![Screen Shot 2019-04-24 at 15 26 45](https://user-images.githubusercontent.com/28021993/56724337-15f38600-674b-11e9-980d-99a0f579ab91.png)

**Comment by bobozd** [comment]
8. I would like to put BACK ARROW icon little lower + maybe little to right
somehow it looks not in perfect place. what line of code and what file I need to edit?

thnx.

![Screen Shot 2019-04-25 at 11 47 16](https://user-images.githubusercontent.com/28021993/56727019-25290280-6750-11e9-82dc-812179cb0e0d.png)

**Comment by thangvo9x** [comment]
3. change color of login and SIGNUP buttons.
=> Change in Container/signIn/style.js
4. Also please help me edit MyListing.js file single listing INFO section. I think it can be done with using default fields from MyListing theme and just insert it into KEY section in MyListing.js file but I don't know default fields used in mylistingtheme for this fields.
=> access to yourdomain/wp-json/wp/v2/job_listing & find listing_data (all keys in it)
5. I can't see where is the CHAT FUNCTION as you show it far in 1.4 version?
Can users chat with each other, is this function implemented as described?
=> Tell me your issue ? 
6. how can I decrease ZOOM LEVEL on map? I would like to have it zoomed out 30-40%
=> go to Common/Config/index.js  & find to this area 
<img width="281" alt="Screen Shot 2019-04-26 at 9 09 25 AM" src="https://user-images.githubusercontent.com/23457178/56778949-033c8800-6803-11e9-8c6e-ed0e935517da.png">
7. how to change RED text color for listing categories?
=> edit at Components/PostLayout/YourLayout/styles.js 
8. I would like to put BACK ARROW icon little lower + maybe little to right
somehow it looks not in perfect place. what line of code and what file I need to edit?
=> edit at Components/Detail/Back/styles.js 
Thanks

**Comment by bobozd** [comment]
1. solved
2. solved
3. solved
4. thanks. it's impossible to find any key in my domain because it looks completely unreadable.
 ![Screen Shot 2019-04-26 at 10 29 33](https://user-images.githubusercontent.com/28021993/56794518-9929e000-680e-11e9-96fe-2211ae66c77b.png)
5. it's not my issue it's about missing functionality. in your marketing images (posted above - version 1.4) there is chat functionality. In my app I can't see any chat functionality with other members. Or am I doing something wrong. Please send me some screenshot where I can find chat icon to chat with other members. thnx.
6. solved
7. can't find any red color numbers in this folders. please specify exact line of code
8. solved

thanks for help. almost ready for publishing the app. excited :-)

**Comment by bobozd** [comment]
9. I want to add same top margin (or padding) for header feature image of posts from blog section.

![Screen Shot 2019-04-26 at 12 34 57](https://user-images.githubusercontent.com/28021993/56802257-dfd40600-681f-11e9-930b-84876b620152.png)

**Comment by thangvo9x** [comment]
4. thanks. it's impossible to find any key in my domain because it looks completely unreadable.
=> Try install the extensions of Google Chrome as JSON Viewer to easy for display
9. I want to add same top margin (or padding) for header feature image of posts from blog section.
=> go to Components/ParaSwiper/style.js edit style there.
Thanks

**Comment by bobozd** [comment]
I install JSONview chrome plugin and this is code it gives me on opening my domain.com/wp-json/wp/v2/job

{
code: "rest_no_route",
message: "No route was found matching the URL and request method",
data: {
status: 404
}
}

**Comment by thangvo9x** [comment]
Hi. domain.com/wp-json/wp/v2/job_listing NOT "job"
Thanks .

**Comment by bobozd** [comment]
still the same...

**Comment by thangvo9x** [comment]
Yup. You must have enabled it in Tools-> Rest API Controller -> Enable job_listing
Follow here step by step & checking: https://docs.inspireui.com/listapp/getting-started/
Thanks
