### ISSUE TITLE
erro at cestore app .need help please

### ISSUE THREAD

**Issue by almalizy** [inspireui/support#536]
Warning: Encountered two children with the same key, `%s`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.%s, h_2, 
    in RCTScrollContentView (at ScrollView.js:852)
    in RCTScrollView (at ScrollView.js:952)
    in ScrollView (at VirtualizedList.js:1062)
    in VirtualizedList (at FlatList.js:662)
    in FlatList (at HorizonList/index.js:89)
    in HorizonList (created by Connect(HorizonList))
    in Connect(HorizonList) (at createAnimatedComponent.js:153)
    in AnimatedComponent (at Home/index.js:49)
    in RCTView (at View.js:44)
    in Home (created by Connect(Home))
    in Connect(Home) (at HomeScreen.js:30)
    in HomeScreen (at SceneView.js:9)
    in SceneView (at StackViewLayout.js:483)
    in RCTView (at View.js:44)
    in AnimatedComponent (at screens.native.js:59)
    in Screen (at StackViewCard.js:42)
    in Card (at createPointerEventsContainer.js:26)
    in Container (at StackViewLayout.js:507)
    in RCTView (at View.js:44)
    in ScreenContainer (at StackViewLayout.js:401)
    in RCTView (at View.js:44)
    in StackViewLayout (at withOrientation.js:30)
    in withOrientation (at StackView.js:49)
    in RCTView (at View.js:44)
    in Transitioner (at StackView.js:19)
    in StackView (at createNavigator.js:57)
    in Navigator (at createKeyboardAwareNavigator.js:11)
    in KeyboardAwareNavigator (at createNavigationContainer.js:376)
    in NavigationContainer (at SceneView.js:9)
    in SceneView (at createTabNavigator.js:10)
    in RCTView (at View.js:44)
    in AnimatedComponent (at BottomNavigation.js:558)
    in RCTView (at View.js:44)
    in AnimatedComponent (at BottomNavigation.js:543)
    in RCTView (at View.js:44)
    in RCTView (at View.js:44)
    in BottomNavigation (at withTheme.js:75)
    in ThemeProvider (at withTheme.js:89)
    in withTheme(BottomNavigation) (at createMaterialBottomTabNavigator.js:25)
    in BottomNavigationView (at createTabNavigator.js:115)
    in NavigationView (at createNavigator.js:57)
    in Navigator (at createNavigationContainer.js:376)
    in NavigationContainer (at Router.js:58)
    in RCTView (at View.js:44)
    in RCTView (at View.js:44)
    in AnimatedComponent (at react-native-drawer/index.js:710)
    in RCTView (at View.js:44)
    in Drawer (at MenuScale.js:52)
    in MenuScale (created by Connect(MenuScale))
    in Connect(MenuScale) (at Router.js:44)
    in Router (created by Connect(Router))
    in Connect(Router) (at App.js:107)
    in PersistGate (at App.js:106)
    in Provider (at App.js:105)
    in App (at withExpoRoot.js:22)
    in RootErrorBoundary (at withExpoRoot.js:21)
    in ExpoRootComponent (at renderApplication.js:34)
    in RCTView (at View.js:44)
    in RCTView (at View.js:44)
    in AppContainer (at renderApplication.js:33)
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:619:8 in warningWithoutStack
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:7093:6 in warning
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:9257:12 in warnOnInvalidKey
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:9303:37 in reconcileChildrenArray
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:10319:6 in reconcileChildren
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:10734:4 in updateHostComponent
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:14091:21 in performUnitOfWork
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:14129:41 in workLoop
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:14226:15 in renderRoot
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:15193:17 in performWorkOnRoot
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:15090:24 in performWork
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:15047:14 in performSyncWork
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:14925:19 in requestWork
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:14711:16 in scheduleWork
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:7700:17 in enqueueSetState
- node_modules/react/cjs/react.development.js:364:31 in setState
- node_modules/react-redux/lib/components/connectAdvanced.js:222:24 in onStateChange
* [native code]:null in onStateChange
- node_modules/react-redux/lib/utils/Subscription.js:30:8 in notify
- node_modules/react-redux/lib/utils/Subscription.js:69:4 in notifyNestedSubs
* [native code]:null in notifyNestedSubs
- node_modules/react-redux/lib/components/connectAdvanced.js:219:10 in onStateChange
* [native code]:null in onStateChange
- node_modules/react-redux/lib/utils/Subscription.js:30:8 in notify
- node_modules/react-redux/lib/utils/Subscription.js:69:4 in notifyNestedSubs
* [native code]:null in notifyNestedSubs
- node_modules/react-redux/lib/components/connectAdvanced.js:219:10 in onStateChange
* [native code]:null in onStateChange
- node_modules/react-redux/lib/utils/Subscription.js:30:8 in notify
- node_modules/react-redux/lib/utils/Subscription.js:69:4 in notifyNestedSubs
* [native code]:null in notifyNestedSubs
- node_modules/react-redux/lib/components/connectAdvanced.js:219:10 in onStateChange
* [native code]:null in onStateChange
- node_modules/reactotron-redux/node_modules/redux/lib/createStore.js:186:14 in dispatch
- node_modules/reactotron-redux/dist/index.js:93:38 in dispatch
* src/redux/LayoutRedux.js:42:15 in <unknown>
- node_modules/promise/setimmediate/core.js:37:14 in tryCallOne
- node_modules/promise/setimmediate/core.js:123:25 in <unknown>
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:152:14 in _callTimer
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:200:17 in _callImmediatesPass
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:464:30 in callImmediates
* [native code]:null in callImmediates
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:320:6 in __callImmediates
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:135:6 in <unknown>
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:297:10 in __guard
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:134:17 in flushedQueue
* [native code]:null in flushedQueue
* [native code]:null in callFunctionReturnFlushedQueue

**Comment by minhtruong315** [comment]
Can you send me AppConfig.json file?

**Comment by almalizy** [comment]
here it is  AppConfig.json file 
{
  "Cezerin": {
    "url": "http://cestore.inspireui.com"
  },
  "HorizonLayout": [
    {
      "layout": 9,
      "category": "5b2c6674cdb2ff05c726740e"
    },
    {
      "name": "featureProducts",
      "image": "",
      "layout": 2,
      "category": "5b2c6659cdb2ff05c726740d"
    },
    {
      "name": "bagsCollections",
      "image": "",
      "layout": 2,
      "category": "5b2c6683cdb2ff05c726740f"
    },
    {
      "name": "womanBestSeller",
      "image": "",
      "layout": 8,
      "category": "5b2c6683cdb2ff05c726740f"
    },
    {
      "name": "manCollections",
      "image": "",
      "layout": 1,
      "category": "5b2c6674cdb2ff05c726740e"
    }
  ],
  "MainColor": "#0094EC"
}

**Comment by minhtruong315** [comment]
done
