### ISSUE TITLE
[MMV] Phone number issue

### ISSUE THREAD

**Issue by staylor1490** [inspireui/support#538]
- Product - MStore Multi Vendor - Complete React Native template for WooCommerce
- Purchase Key - f8f6c504-33b7-4927-be64-98037619da93

  Hi,

  I'm using the app template for my Dokan woocommerce multi vendor site and I have an issue with the app is not sending number in required format (see picture https://screenshotscdn.firefoxusercontent.com/images/ed6492dc-1fae-4733-b3a3-19857a9f441a.png). When I send number in required format notifications are working fine. But right now it is sending to phone number in this format, which isn't working. https://screenshotscdn.firefoxusercontent.com/images/adf603da-963f-4178-b1f6-0db705057bce.png.

Can you fix this? I sent my source code and config js in an email. 

Thanks!

Sean

**Comment by minhcasi** [comment]
Hi, you can update the format base on your need from file - containers/Cart/Delivery/index.js - search the TextInputMask

**Comment by staylor1490** [comment]
How do I update? and what do I update??
