### ISSUE TITLE
[MStore] Rest API aren't working with new Woocommerce update. 

### ISSUE THREAD

**Issue by sashaba** [inspireui/support#539]
**Required Info (please complete the following information):**
 - Product: MStore
 Hi support
so, its been 2 days since i updated to woocommerce 3.6.2 and can't fetch any product  since then, pages like contact, privacy policy are showing fine but woocommerce products and categories aren't. would you please help me figure out the issue. 
Thank you.

**Comment by sashaba** [comment]
I also change my WordPress theme to storefront. Is there any additional configuration when we change the website theme?

**Comment by sashaba** [comment]
So i just found out there is a conflict with WPML, i Rolled back to woocommerce previous version,  desactivated WPML and my products are back on the App. so there is a conflict with new releases of WPML, and Woocommerce with api-ecommerce.

**Comment by sashaba** [comment]
So to resolve my issue i had to Rollback to woocommerce 3.5.7.
 Everything is working fine for now. Can't update woocommerce till this issue is resolve.  
I don't know if the issue is with Woocommerce(latest version)  or with WPML(latest version) but i do know that api-ecommerce doesn't work anymore with both of them activated at the same time. 

I Hope you check and update the Rest API of the App to work with the latest release of woocommerce and WPML.

**Comment by luyx2412** [comment]
HI @sashaba Thanks for your information, let we check this issue.

Thanks

**Comment by minhcasi** [comment]
Hi, we have checked and update the mstore.io without problem Version 3.6.2, the issues could be from WPML, pls check and let us know if there is any issues - thank you!

**Comment by minhcasi** [comment]
could be related to WooCommerce 3.6.0 and 3.6.1 - similar to this ticket - https://github.com/inspireui/support/issues/513

**Comment by sashaba** [comment]
I updated again to 3.6.2 and the issue is back. So I’m rolling back to 5.3.7
As you said the conflict could be with WPML. I’ll wait until they update the plugin.
