### ISSUE TITLE
how to setup firebase chat 

### ISSUE THREAD

**Issue by alaradi2006** [inspireui/support#54]
**Mandatory Info (please complete the following information):**
 - Product: [e.g. MStore, ListApp]
 - Your Purchased Code: [get from https://codecanyon.net/downloads]
(we may not reply if you are not our customer)

**Describe the issues**
theres no guide for all this things 
how i will setpu firebase for mstore app 
**Screenshots**

**Additional context**
Add any other detail logs about the problem here.

**Comment by minhcasi** [comment]
you can refer to this document - https://docs.expo.io/versions/latest/guides/using-firebase#__next

**Comment by alaradi2006** [comment]
they didint mention how to setup chat for expo platform
even in youtibe theres for android studio which is diffrent please give me good guide

________________________________
