### ISSUE TITLE
[Listpro] There's no guide for too many things! 

### ISSUE THREAD

**Issue by egebese** [inspireui/support#540]
- Product: Listpro
 - Your Purchased Code: f62282cf-fe1f-447d-9c9d-1df9eeae993c

I added my language in languages.js, i can't see my language on settings page, how can i do it? 
I changed default language. Stil..

And i change layout on wordpress listapp wordpress plugin but it won't effect the app.

How can i edit facebook login in the app? I set the wordpress social login but i can't login with my facebook app. I change some facebook id but still same.

Also i couldn't find firebase setup docs. 

I'm waiting fast reply.

**Comment by minhcasi** [comment]
Thank you for your suggestion, we will add new documentation base on your feedback - thank you!

**Comment by egebese** [comment]
> Thank you for your suggestion, we will add new documentation base on your feedback - thank you!

thank you but, i want to relase the app? please tell me how exactly i do these???? i can't wait untill your update.

**Comment by thangvo9x** [comment]
Hi. After you add a new language in Languages.js then you must go to the Container/Setting/LangSwitch.js and add a new row as below image
<img width="445" alt="addnewlanguage" src="https://user-images.githubusercontent.com/23457178/57054496-28c40880-6cbf-11e9-880b-d6e1965bdb36.png">

You edit it Config/YOURTHEME.js find key as below image and replace it.
<img width="414" alt="fb" src="https://user-images.githubusercontent.com/23457178/57054532-514c0280-6cbf-11e9-946b-8c5a2aba946f.png">

If you have any issue. Please screenshot its help us.

**Comment by egebese** [comment]
When will documantation get updated? I am still waiting and I am bored. I need to publish my app but I can’t because of you. Very slow and bad support, very poor documantation. I am so close to rate 1/5 on codecanyon. 

I am losing my patience.

**Comment by minhcasi** [comment]
Hi, what is your issues so far? We did not get your feedback from the last response from the team.

 If you are not happy with the product, just kindly process the refund - thank you!

**Comment by egebese** [comment]
I couldn't find how to setup firebase.
I change the layout on listpro plugin but it doesn't effect the app.
I changed the facebook id but still it's login with default app.

**Comment by minhcasi** [comment]
Okay, i've reopened the ticket and the team will update you with the detail firebase / facebook on Monday, they are still in middle with the update, in the meantime you can refer to:
https://docs.expo.io/versions/latest/guides/using-firebase/#__next
https://docs.expo.io/versions/latest/sdk/facebook/#__next

We have some video for the push notification via Firebase but it is used for Listapp (that will be similar)  https://www.youtube.com/playlist?list=PLcF-HiQy-jOLg0O6d9uWhOqGhvvLfx6is

Regarding to the layout not effect, pls update your screenshot here - thanks
