### ISSUE TITLE
Mstore Shopify - Complete React Native template for e-commerce Standard License Inquiry 

### ISSUE THREAD

**Issue by WAGNERS28** [inspireui/support#542]
I just want to clarify that i can create both website, and mobile app for ios and android with Mstore Shopify - Complete React Native template for e-commerce ? Please clarify that this the demo for the 3 of them (i.e. website and mobile app)

In addition, i can use the Standard License when the said app is an ecommerce app where they will buy the products being sold in the app per license agreement. Please clarify too. Thanks.

, per standard license agreement: https://codecanyon.net/licenses/standard

Note to freelancers and creative agencies:
You may charge your client for your services to create an end product, even under the Regular License. But you can’t use one of our Standard Licenses on multiple clients or jobs. 

Demo iOS and Android app: http://bit.ly/2mHSuf7
(Login by Expo account: inspireui-demo / inspireui)

Shopify Demo: https://beostore.myshopify.com/collections/all
Email to support@beostore.io

**Comment by minhcasi** [comment]
Hi, you can purchase and use regular license to release app to Appstore & Google Play, but you could not use the app for reseller or sell the app as "installing service", or using the app for development services. It's ok for using the app the e-commerce business (sell other products) - thank you!
