### ISSUE TITLE
[Mstore] - Track Order done through App

### ISSUE THREAD

**Issue by anasAlsalol** [inspireui/support#544]
I would love to have this feature : 
01- Track Order done through App  from Admin Panel .

Currently when the purchase is made through the application "mstore mobile app" , the request can be viewed through the control panel in our website  "but can not distinguish requests made through the site or through the application" , so i need away to distinguish between order done by app and order done by website . 

02- Extend apply coupon to use Usage restriction like Minimum spend ,Maximum spend , Exclude categories etc .

when user try to apply coupon in app ( The app not implement any restriction ) restriction can be identified from wordpress website .

**Comment by minhcasi** [comment]
Hi, first please provide your purchase code 

And explain more detail & screenshot as we are not sure to understand your issues

Thank you!
