### ISSUE TITLE
[Listpro] undefined data

### ISSUE THREAD

**Issue by chad-the-first** [inspireui/support#546]
- Product: [Listpro]
 - Your Purchased Code: 65e47917-78fa-4b8e-97ec-80bf8345f72a

**Describe the bug**
I do have a problem, what's happening is that I'm getting the listing_data in a scrambled like in the picture:
![Sketch](https://user-images.githubusercontent.com/17035853/56948760-c8f02500-6b39-11e9-9afc-c8c29583cf4a.png)

and that's why I'm getting undefined in the listing:
![Sketch1](https://user-images.githubusercontent.com/17035853/56948771-d3aaba00-6b39-11e9-95b1-7c40b9372bb7.png)

Why am i getting the listing data this way and how to fix this problem??

**Comment by thangvo9x** [comment]
Hi, Do u have an update to the latest version such as the plugin ListApp Mobile Manager, plz?

**Comment by chad-the-first** [comment]
ok this problem was fixed thanks, but now I can't see the categories images as you can see in the picture:
![Sketch](https://user-images.githubusercontent.com/17035853/57063973-a42cb680-6ccd-11e9-9e31-00c8e1eb64a3.png)

the category has a banner image btw. how to fix this problem?

**Comment by thangvo9x** [comment]
Hi. Give me your info admin for checking

**Comment by thangvo9x** [comment]
I checked and the image of categories have appeared. Please check again. Thanks
