### ISSUE TITLE
[ListPro] No internet notification

### ISSUE THREAD

**Issue by chad-the-first** [inspireui/support#547]
- Product: [Listpro]
 - Your Purchased Code: 65e47917-78fa-4b8e-97ec-80bf8345f72a

**Describe the bug**
when I get no internet notification in the bottom of the screen, it doesn't go away when i reconnect to the internet, at the same time the works fine. 

how to fix this?

**Comment by thangvo9x** [comment]
Hi. We noted in the next release. In the current version, you must reload the app to get internet. 
Thanks for your valuable feedback.

**Comment by chad-the-first** [comment]
@thangvo9x  what do you mean by reload, because I close the app and open it again and it's still there.

**Comment by thangvo9x** [comment]
Hi. @chad-the-first. I checked the source of ListPro is working normally. 
Refer here: https://we.tl/t-cpFwnNcdQp
or remove it by going to RootRouter.js and remove <NetInfo />
<img width="171" alt="Screen Shot 2019-05-03 at 11 28 32 AM" src="https://user-images.githubusercontent.com/23457178/57119729-9a22ba80-6d96-11e9-8610-9411c1cc76e3.png">
Thanks
