### ISSUE TITLE
[ListPro] Categories list style

### ISSUE THREAD

**Issue by chad-the-first** [inspireui/support#548]
- Product: [ListPro]

How can I make the list not to show alphabetically but each category under it's parent category:

![Sketch2](https://user-images.githubusercontent.com/17035853/56958810-16798b80-6b54-11e9-97db-7e329a213099.png)

**Comment by thangvo9x** [comment]
Hi @chad-the-first. This problem, you must customize the code on your website & the mobile app. This is out of scope supporting, hope u see. Thanks
