### ISSUE TITLE
[MStore] ERROR CODE: 500

### ISSUE THREAD

**Issue by IvoKalu** [inspireui/support#549]
**Mandatory Info (please complete the following information):**
 - Product: [MStore]
 - Your Purchased Code: 41384711-598d-400d-9b04-1b414a388036]

**Describe the issues**
When I run the aplication I get this error from the app.

**Screenshots**
![Screenshot_20190425-232357_MStore Pro](https://user-images.githubusercontent.com/8544219/56991670-244d0200-6b90-11e9-852a-5cb0963eef39.jpg)
![Screenshot_20190425-232406_MStore Pro](https://user-images.githubusercontent.com/8544219/56991689-30d15a80-6b90-11e9-93cc-066524fb20cd.jpg)
![Screenshot_20190425-232418_MStore Pro](https://user-images.githubusercontent.com/8544219/56991715-42b2fd80-6b90-11e9-8850-19d93ab930ee.jpg)

**Additional context**
And I get this from the node cmd

> Error: Unable to resolve module `./index` from `C:\Users\Ivo Kalu\Desktop\mstore-3.7.2\mstore-pro\node_modules\react-native\scripts/.`: The module `./index` could not be found from `C:\Users\Ivo Kalu\Desktop\mstore-3.7.2\mstore-pro\node_modules\react-native\scripts/.`. Indeed, none of these files exist:
>   * `C:\Users\Ivo Kalu\Desktop\mstore-3.7.2\mstore-pro\node_modules\react-native\scripts\index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`
>   * `C:\Users\Ivo Kalu\Desktop\mstore-3.7.2\mstore-pro\node_modules\react-native\scripts\index\index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`
>     at ModuleResolver.resolveDependency (C:\Users\Ivo Kalu\Desktop\mstore-3.7.2\mstore-pro\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:163:15)
>     at ResolutionRequest.resolveDependency (C:\Users\Ivo Kalu\Desktop\mstore-3.7.2\mstore-pro\node_modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:52:18)
>     at DependencyGraph.resolveDependency (C:\Users\Ivo Kalu\Desktop\mstore-3.7.2\mstore-pro\node_modules\metro\src\node-haste\DependencyGraph.js:283:16)
>     at C:\Users\Ivo Kalu\Desktop\mstore-3.7.2\mstore-pro\node_modules\metro\src\lib\transformHelpers.js:261:42
>     at Server.<anonymous> (C:\Users\Ivo Kalu\Desktop\mstore-3.7.2\mstore-pro\node_modules\metro\src\Server.js:1038:41)
>     at Generator.next (<anonymous>)
>     at asyncGeneratorStep (C:\Users\Ivo Kalu\Desktop\mstore-3.7.2\mstore-pro\node_modules\metro\src\Server.js:99:24)
>     at _next (C:\Users\Ivo Kalu\Desktop\mstore-3.7.2\mstore-pro\node_modules\metro\src\Server.js:119:9)
> ::ffff:127.0.0.1 - - [30/Apr/2019:20:39:26 +0000] "GET /index.delta?platform=android&dev=true&minify=false HTTP/1.1" 500 - "-" "okhttp/3.12.1"

**Comment by minhcasi** [comment]
Related #427

Could we have a quick check if you manage to run the example project successful base on this guide - https://facebook.github.io/react-native/docs/getting-started - this guide is helpful for setup the basic installing for the app
