### ISSUE TITLE
[MStore] Sidemenu Item Hide 

### ISSUE THREAD

**Issue by davekedar** [inspireui/support#550]
- Product: MStore
 - Your Purchased Code: f9eaf46b-d573-484d-945f-4236e184eeaf

I have tried hiding "NEWS" from the side menu, I have done it from index.js from navigation folder but it is not getting hide. 

Please help

**Comment by thangvo9x** [comment]
Hi, Try to go to Config.js and find a key with name as below image

<img width="443" alt="key" src="https://user-images.githubusercontent.com/23457178/57060710-8c146180-6ce4-11e9-85d4-b986dab58b4b.png">
Thanks

**Comment by davekedar** [comment]
Thanks @thangvo9x
