### ISSUE TITLE
[MStore] How to install the Mstore Pro app?

### ISSUE THREAD

**Issue by Hi7am** [inspireui/support#551]
Hi Team,

I have followed the menu to install the application carefully, but I got lost....as it does not work when I follow to the steps.

> The menu I am reading on:

https://docs.mstore.io/cebuilder-installing

Step 1:

Installed the Cebuilder - Done

Step 2: 

Verifying the account - Done

Step 3:

Select the project download folder where content the package.json, and update the Website URL

FAILED!

![install 1](https://user-images.githubusercontent.com/50176761/57025852-eb359000-6c6a-11e9-9576-a0a0d7596af3.png)

I have downloaded the zip files from the codecanyon, when I unzipped the file, some of the files cannot be read....see the files names in the screenshot

![Mstore 1](https://user-images.githubusercontent.com/50176761/57025966-318aef00-6c6b-11e9-8cba-48936a5adcae.png)
![Mstore 2](https://user-images.githubusercontent.com/50176761/57025967-318aef00-6c6b-11e9-92e2-c663b503be9c.png)
![Mstore 3](https://user-images.githubusercontent.com/50176761/57025968-318aef00-6c6b-11e9-8cb5-ac8bc61fef32.png)
![Mstore 4](https://user-images.githubusercontent.com/50176761/57025969-32238580-6c6b-11e9-90c0-5625f8746449.png)
![Mstore 5](https://user-images.githubusercontent.com/50176761/57025970-32238580-6c6b-11e9-9009-b4ad345ee5fb.png)
![Mstore 6](https://user-images.githubusercontent.com/50176761/57025971-32bc1c00-6c6b-11e9-8883-f38dae77e5a7.png)
![Mstore 7](https://user-images.githubusercontent.com/50176761/57025973-32bc1c00-6c6b-11e9-8559-0785b2447523.png)

Please advise which menu I should follow to install the app. I value your feedback very much. Thank you!

Andy

**Comment by minhcasi** [comment]
Hi, you can open the folder mstore-pro or mstore-expo after extract the zip files

Is it possible to translate the China text as i could not read - thank you!
