### ISSUE TITLE
[MStore] about multi currency 

### ISSUE THREAD

**Issue by ramyragab1** [inspireui/support#552]
**Required Info (please complete the following information):**
 - Product: [MStore]
 - Your Purchased Code: 3898a434-a6f8-47cf-a49f-8990c76f4665

**Describe the bug**
i want to add multi currency and change currency product in app
how i do this ?

**Comment by ramyragab1** [comment]
i found bug when i make order 
order status completed not hold

**Comment by ramyragab1** [comment]
and price filter not working

**Comment by minhcasi** [comment]
@ramyragab1 - could you help to share the screenshots of the issues and also the config file (common/Appconfig.json and config.js file) - thank you!

**Comment by ramyragab1** [comment]
> and price filter not working

solved

**Comment by ramyragab1** [comment]
> @ramyragab1 - could you help to share the screenshots of the issues and also the config file (common/Appconfig.json and config.js file) - thank you!

co you test in your app and you found this bugs @minhcasi

**Comment by ramyragab1** [comment]
? @minhcasi

**Comment by minhcasi** [comment]
@Thanks @ramyragab1  - confirmed that this issue will be fixed on next version  3.8.0

You can also fix by updating this value to false - https://tppr.me/RbyYq - thanks

**Comment by ramyragab1** [comment]
thanks
