### ISSUE TITLE
[MMV] facebook-Lang-Currency-add to cart

### ISSUE THREAD

**Issue by osamasparky** [inspireui/support#554]
MVStore
Purchase code: da4e5510-501d-456f-9d1d-fbbcdd24f102

good day . Please please please dont't delay in answer .
1- i have just one Lang . i don't need any other . how to disable the eng.
2- The app currency in USD . My website In EGP . how to change currency on app .
3- where to add face book id for login .  not here https://docs.mstore.io/advance-customize-app/facebook-config.
4- how to change the app guide screen ( intro ) in the start .
5-when select a product . the add to cart button is disabled. i need to click on buy now.
how  .
6-i create a user on the website . i can't login from app .

**Comment by thangvo9x** [comment]
1- i have just one Lang . i don't need any other . how to disable the eng.
=> Disable it in Languages.js in common folder
2- The app currency in USD . My website In EGP . how to change currency on app .
=> you can edit in Config.js find a key "DefaultCountry" name.
3- where to add face book id for login . not here https://docs.mstore.io/advance-customize-app/facebook-config.
=> Config.js find a key with "appFacebookId" name.
4- how to change the app guide screen ( intro ) in the start .
=> Hi, you can go to src/Components/AppIntro.
5-when select a product . the add to cart button is disabled. i need to click on buy now.
how.
=> the button add to cart will be disabled when it were out of stock.
6-i create a user on the website . i can't login from app .
=> If you create a user on your website. You must change password that user before login it on your app.
Thanks

**Comment by osamasparky** [comment]
1.facebook login not work after i update . and when try login the close screen is too big can't close it .
2. when chose ar not changed . and when i delete all the en . and recompile the app not working .
3- add to cart still disable even i have stock .
4-after compiled the app . work for 2 times . after that it say can't get the data from sever . ( i have internet ) .
5.Cebuilder . when you click on deliver . it go to different directory not the directory which the app files in .
 i will send you the app on email .
