### ISSUE TITLE
[MStore] Cebuilder - Setup not saving up as i need them to be

### ISSUE THREAD

**Issue by leonardodiaz6cmarketing** [inspireui/support#557]
**Mandatory Info (please complete the following information):**
 - Product: Mstore 3.0
 - Your Purchased Code:  7ff6b1f8-6ab7-469d-be9b-f0ea71baa10a
(we may not reply if you are not our customer)

**Describe the issues**
Whil trying to save my setup it shows nothing, if i restart the CeBuilder the name and webpage arent the ones i need them to be, and neither the keys from the woocommerse

**Screenshots**

![image](https://user-images.githubusercontent.com/49452960/57163104-9870eb00-6dc6-11e9-94e5-f791a3ba10c2.png)

**Additional context**
Add any other detail logs about the problem here.

**Comment by minhcasi** [comment]
Hi, could you help to update the latest cebuilder 0.34 from this link - https://github.com/inspireui/cebuilder/releases
