### ISSUE TITLE
[MStore] Bug during scrolling posts

### ISSUE THREAD

**Issue by Brdnn** [inspireui/support#558]
**Required Info (please complete the following information):**
 - Product: [Mstore Pro]
 - Your Purchased Code: 6c0dea43-9137-4276-a120-343fa7d2bc8f
(we may not reply if you are not our customer)

**Describe the bug**
In news page, App will gone crazy in fetching new post after scrolling some posts and end up crashed. Attached video for better understanding for this bug.

**Screenshots**
https://boards.wetransfer.com/board/sjjcnnziwygwymabz20190504194421/latest

**Additional context**
/** @format */

import Images from "./Images";
import Constants from "./Constants";
import Icons from "./Icons";

export default {
  /**
   * Step 1: change to your website URL and the wooCommerce API consumeKey
   * Moved to AppConfig.json
   */

  /**
     Step 2: Setting Product Images
     - ProductSize: Explode the guide from: update the product display size: https://mstore.gitbooks.io/mstore-manual/content/chapter5.html
     The default config for ProductSize is disable due to some problem config for most of users.
     If you have success config it from the Wordpress site, please enable to speed up the app performance
     - HorizonLayout: Change the HomePage horizontal layout - https://mstore.gitbooks.io/mstore-manual/content/chapter6.html
       Update Oct 06 2018: add new type of categories
       NOTE: name is define value --> change field in Language.js
       Moved to AppConfig.json
     */
  ProductSize: {
    enable: false,
  },

  HomeCategories: [
    {
      name: "Appliances",
      category: 912,
      image: require("@images/categories_icon/ic_appliances.png"),
      colors: ["#000000","#FFFFFF"],
    },
    {
      category: 913,
      image: require("@images/categories_icon/ic_gadgets.png"),
      colors: ["#000000","#FFFFFF"],
    },
    {
      category: 914,
      image: require("@images/categories_icon/ic_home.png"),
      colors: ["#000000","#FFFFFF"],
    },
    {
      category: 917,
      image: require("@images/categories_icon/ic_kitchen.png"),
      colors: ["#000000","#FFFFFF"],
    },
    {
      category: 918,
      image: require("@images/categories_icon/ic_sports.png"),
      colors: ["#000000","#FFFFFF"],
    },
    {
      category: 919,
      image: require("@images/categories_icon/ic_pets.png"),
      colors: ["#000000","#FFFFFF"],
    },
    {
      category: 915,
      image: require("@images/categories_icon/ic_stationary.png"),
      colors: ["#000000","#FFFFFF"],
    },
    {
      category: 916,
      image: require("@images/categories_icon/ic_travel.png"),
      colors: ["#000000","#FFFFFF"],
    },
  ],
  /**
     step 3: Config image for the Payment Gateway
     Notes:
     - Only the image list here will be shown on the app but it should match with the key id from the WooCommerce Website config
     - It's flexible way to control list of your payment as well
     Ex. if you would like to show only cod then just put one cod image in the list
     * */
  Payments: {
    cod: require("@images/payment_logo/cash_on_delivery.png"),
    paypal: require("@images/payment_logo/PayPal.png"),
    stripe: require("@images/payment_logo/stripe.png"),
    billplz: require("@images/payment_logo/billplz.png"),
    bacs: require("@images/payment_logo/banktransfer.png"),
  },

  /**
     Step 4: Advance config:
     - showShipping: option to show the list of shipping method
     - showStatusBar: option to show the status bar, it always show iPhoneX
     - LogoImage: The header logo
     - LogoWithText: The Logo use for sign up form
     - LogoLoading: The loading icon logo
     - appFacebookId: The app facebook ID, use for Facebook login
     - CustomPages: Update the custom page which can be shown from the left side bar (Components/Drawer/index.js)
     - WebPages: This could be the id of your blog post or the full URL which point to any Webpage (responsive mobile is required on the web page)
     - CategoryListView: default layout for category (true/false)
     - intro: The on boarding intro slider for your app
     - menu: config for left menu side items (isMultiChild: This is new feature from 3.4.5 that show the sub products categories)
     * */
  shipping: {
    visible: false,
    zoneId: 2, // depend on your woocommerce
    time: {
      free_shipping: "4 - 7 Days",
      flat_rate: "1 - 4 Days",
      local_pickup: "1 - 4 Days",
    },
    
  },
  showStatusBar: true,
  LogoImage: require("@images/logo-main.png"),
  LogoWithText: require("@images/logo_with_text.png"),
  LogoLoading: require("@images/logo.png"),

  showAdmobAds: false,
  AdMob: {
    deviceID: "pub-2101182411274198",
    unitID: "ca-app-pub-2101182411274198/4100506392",
    unitInterstitial: "ca-app-pub-2101182411274198/8930161243",
    isShowInterstital: true,
  },
  appFacebookId: "1114416955326999",
  CustomPages: { contact_id: 10941 },

  intro: [
    {
      key: "page1",
      title: "7 Days Return",
      text:
        "Hassle free returns at zero cost",
      icon: "ios-cube-outline",
      colors: ["#ffffff", "#ffffff"],
    },
    {
      key: "page2",
      title: "Secure Payments",
      text:
        "Secured your transactions with verified payment gateways",
      icon: "ios-card-outline",
      colors: ["#ffffff", "#ffffff"],
    },
    {
      key: "page3",
      title: "Editors Picks",
      text: "A selection of items verified for quality and design",
      icon: "ios-thumbs-up-outline",
      colors: ["#ffffff", "#ffffff"],
    },
  ],

  /**
   * Config For Left Menu Side Drawer
   * @param goToScreen 3 Params (routeName, params, isReset = false)
   * BUG: Language can not change when set default value in Config.js ==> pass string to change Languages
   */
  menu: {
    // has child categories
    isMultiChild: true,
    // Unlogged
    listMenuUnlogged: [
      {
        text: "Login",
        routeName: "LoginScreen",
        params: {
          isLogout: false,
        },
        icon: Icons.MaterialCommunityIcons.SignIn,
      },
    ],
    // user logged in
    listMenuLogged: [
      {
        text: "Logout",
        routeName: "LoginScreen",
        params: {
          isLogout: true,
        },
        icon: Icons.MaterialCommunityIcons.SignOut,
      },
    ],
    // Default List
    listMenu: [
      {
        text: "Shop",
        routeName: "Home",
        icon: Icons.MaterialCommunityIcons.Home,
      },
      {
        text: "Editor Picks",
        routeName: "NewsScreen",
        icon: Icons.MaterialCommunityIcons.News,
      },
      // {
      //   text: "contactus",
      //   routeName: "CustomPage",
      //   params: {
      //     id: 10941,
      //     title: "contactus",
      //   },
      //   icon: Icons.MaterialCommunityIcons.Pin,
      // },
      // {
      //   text: "About",
      //   routeName: "CustomPage",
      //   params: {
      //     url: "https://sneapy.com",
      //   },
      //   icon: Icons.MaterialCommunityIcons.Email,
      // },
      // {
      //   text: "Setting",
      //   routeName: "SettingScreen",
      //   icon: Icons.MaterialCommunityIcons.Setting,
      // },
    ],
  },

  // define menu for profile tab
  ProfileSettings: [
    {
      label: "WishList",
      routeName: "WishListScreen",
    },
    {
      label: "MyOrder",
      routeName: "MyOrders",
    },
    {
      label: "Address",
      routeName: "Address",
    },
    {
      label: "Currency",
      isActionSheet: true,
    },
    // only support mstore pro
    //   {
    //     label: Languages.Languages,
    //     routeName: 'SettingScreen',
    //     value: language.lang,
    //   },
    // {
    //   label: "PushNotification",
    // },
    {
      label: "DarkTheme",
    },
    {
      label: "contactus",
      routeName: "CustomPage",
      params: {
        id: 508,
        title: "contactus",
      },
    },
    {
      label: "Privacy",
      routeName: "CustomPage",
      params: {
        url: "https://thegiftaway.com/private-policy/",
      },
    },
    {
      label: "termCondition",
      routeName: "CustomPage",
      params: {
        url: "https://thegiftaway.com/terms-conditions/",
      },
    },
    {
      label: "About",
      routeName: "CustomPage",
      params: {
        url: "https://thegiftaway.com/about-us/",
      },
    },
  ],

  // Layout select
  layouts: [
    {
      layout: Constants.Layout.card,
      image: Images.icons.iconCard,
      text: "cardView",
    },
    {
      layout: Constants.Layout.simple,
      image: Images.icons.iconRight,
      text: "simpleView",
    },
    {
      layout: Constants.Layout.twoColumn,
      image: Images.icons.iconColumn,
      text: "twoColumnView",
    },
    {
      layout: Constants.Layout.threeColumn,
      image: Images.icons.iconThree,
      text: "threeColumnView",
    },
    {
      layout: Constants.Layout.horizon,
      image: Images.icons.iconHorizal,
      text: "horizontal",
    },
    {
      layout: Constants.Layout.advance,
      image: Images.icons.iconAdvance,
      text: "advanceView",
    },
  ],

  // Default theme loading, this could able to change from the user profile (reserve feature)
  Theme: {
    isDark: false,
  },

  // new list category design
  CategoryListView: true,

  DefaultCurrency: {
    symbol: "RM",
    name: "Ringgit Malaysia",
    code: "MYR",
    name_plural: "Ringgit malaysia",
    decimal: ".",
    thousand: ",",
    precision: 2,
    format: "%s%v", // %s is the symbol and %v is the value
  },

  DefaultCountry: {
    code: "my",
    RTL: false,
    language: "English",
    countryCode: "MY",
    hideCountryList: false, // when this option is try we will hide the country list from the checkout page, default select by the above 'countryCode'
  },
  HideCartAndCheckout: false,

  /**
   * Config notification onesignal, only effect for the Pro version
   */
  // OneSignal: {
  //   appId: "43948a3d-da03-4e1a-aaf4-cb38f0d9ca51",
  // },
  /**
   * Login required
   */
  Login: {
    RequiredLogin: false, // required before using the app
    AnonymousCheckout: false, // required before checkout or checkout anonymous
  },

  Layout: {
    HideHomeLogo: false,
    HideLayoutModal: false
  }
};

**Comment by Brdnn** [comment]
Okay. I just fixed it with getItemLayout

**Comment by minhcasi** [comment]
Hi, we could not see the crashing on end of video. Could you help to share the common/AppConfig.json as well - thank you!

**Comment by minhcasi** [comment]
closed the issue as there is no response, please help to reopen it there is an issue - thank you!
