### ISSUE TITLE
[CeStore] Cestore can,t add new image from admin dashboard - uploaded but didn,t shown

### ISSUE THREAD

**Issue by almalizy** [inspireui/support#559]
Cestore can,t add new image from admin dashboard
 - uploaded but didn,t shown

i tried alot to add new images
i can only delete and upload 
but after that the new images didn,t shown
and if i keep one old image and add new images behind it then the old one duppled twices 

help me please

**Comment by minhcasi** [comment]
Hi, could you help to share your website account login so we could check the issues?

You can send to our support email support@inspireui.com - thank you!

**Comment by almalizy** [comment]
thanks for replay 
but i am still didn,t upload to the server untill now
ai am still using it at local host at my mac
but i can share my team viewer if y like to check 
thanks
waiting your replay

**Comment by minhcasi** [comment]
Okay i see, could you help to quick send the recording video of the issue? there may be an issue with the config that causes the bug, can you check the error log from the developer console from Chrome browser? Thanks

**Comment by almalizy** [comment]
- okay thanks
- before sharing video 
- I think the problem that the web working at your site API 
- not on my local API source
- cause any picture I can see if I followed its source
- 
- here is a picture show my case
- 
- https://www.4shared.com/photo/KUg3LhHifi/2019-05-07_13-35-19.html
- 
- so maybe if I change API to be on my local API 
- but i tried alot but didn,t scucess - if you had no minde to guid me, please 
- thanks

**Comment by almalizy** [comment]
also i can,t run api at localhost:3001 
it gived me message  Cannot GET /

help me please

**Comment by almalizy** [comment]
help, please !!!

**Comment by minhcasi** [comment]
Hi, could you help to follow this guide to setup your local database - https://docs.inspireui.com/cestore-web/initialize-mongodb/

Also, there is the step to run the node server from your local - pls check https://docs.inspireui.com/cestore-web/getting-started/

**Comment by almalizy** [comment]
i am already foloowed all that steps
and your friend (minhtruong315) helped me and login at my mac with team viewer and he checked that everything working fine

but i discovered later that problem
**that i can,t add new pictures at dashboard products**
also when i followed the image source 
i found it source is your site not my local 

also, i am already changed  config.js 
as image guide here
https://tppr.me/ZrQcz

but still the same problem 
server catch image from your web site API

not from localhost

**Comment by minhtruong315** [comment]
Hi @almalizy You need to update domain in admin panel. or you can open mongodb, then change domain in settings collection
