### ISSUE TITLE
i cant confirm order

### ISSUE THREAD

**Issue by alaradi2006** [inspireui/support#56]
**Mandatory Info (please complete the following information):**
 - Product: [e.g. MStore, ListApp]
 - Your Purchased Code: [get from https://codecanyon.net/downloads]
(we may not reply if you are not our customer)
a9c6782d-8c5d-4811-8c4a-2ccc9d6be005 mstore multivendor
**Describe the issues**
after adding prodcut to cart in last step to confirm order after clicking on confirm order its just loading and not confrim 
another issues payment gateway its only with cash on delivery
**Screenshots**

**Additional context**
Add any other detail logs about the problem here.

**Comment by samber91** [comment]
Hi, if you were able to fix your issue, please share with me at jb.ro.corp2018@gmail.com    . I'm having the same issue and i'm desperate in finding some answers. thanks

**Comment by alaradi2006** [comment]
which issue?

________________________________
