### ISSUE TITLE
[Mstore] Debuggin in Ubuntu

### ISSUE THREAD

**Issue by davekedar** [inspireui/support#561]
Required Info (please complete the following information):

Product: [MStore]
Your Purchased Code: f9eaf46b-d573-484d-945f-4236e184eeaf

I want to debugg the project but debugg js remotly is not working with this project please help

**Comment by minhcasi** [comment]
Hi, you can try with these tools
https://github.com/jhen0409/react-native-debugger
https://github.com/infinitered/reactotron/blob/master/docs/installing.md

**Comment by davekedar** [comment]
@minhcasi but the console.log is not getting printed nor I can see the api response please help how to get that

**Comment by davekedar** [comment]
@minhcasi kindly reopen unless it is solved
