### ISSUE TITLE
[MMV] Bug in dashboard for add product 

### ISSUE THREAD

**Issue by ykoussour** [inspireui/support#562]
Bug in dashboard vendor and how to add category in icon. For Multivendor

**Comment by thangvo9x** [comment]
Hi. Please provide us your purchase code such as Can u take screenshots for this problem, plz?

**Comment by ykoussour** [comment]
04b5ffdf-f41d-40c8-898e-1c3c1edf5245
HOW TO  ADD  CATIGORY IN  THIS ICON  AND  BUG IN  ADD  PRODUCT  IN  APP Do not write TITLE  AND DESCRIPTION  AND Do not ADD PRODUCT   
![PRUO](https://user-images.githubusercontent.com/50315197/57312337-d890e000-70dc-11e9-83f5-0d714c5d408d.PNG)

**Comment by thangvo9x** [comment]
Hi. To add a new categoy. You go to src/common/Config.js and find a key as
<img width="333" alt="Screen Shot 2019-05-08 at 9 17 00 AM" src="https://user-images.githubusercontent.com/23457178/57344610-1855d700-7172-11e9-818a-0f5d71f0fafb.png">
- Please screenshots the issue when you post a new listing. 
Thanks
