### ISSUE TITLE
[MStore] getting white screen when installing the Mstore CheckOut Plugin and API

### ISSUE THREAD

**Issue by janbildsoehansen** [inspireui/support#563]
**Mandatory Info (please complete the following information):**
 - Product:  MStore pro
 - Your Purchased Code: ccfa2581-4400-4528-9296-54b3ab2ad2cd
(we may not reply if you are not our customer)

**Describe the issues**
getting white screen when setting up the Mstore CheckOut Plugin and API
have setup the mstore-checckout-template.php

**Screenshots**
![57071800-d34a2480-6cdb-11e9-9b95-c7a142cbf7da](https://user-images.githubusercontent.com/31623630/57294435-f9026f80-70c7-11e9-9549-10f276798a58.png)

**Additional context**
Add any other detail logs about the problem here.

**Comment by minhcasi** [comment]
Hi, is it the same white screen when you process the payment via app? The web will be blank as itself because there is no param data, similar with our page - http://mstore.io/mstore-checkout/ 



<blockquote></blockquote>

**Comment by janbildsoehansen** [comment]
soo what about the online customers they cant pay for their products when i use your app thing with my website is what you are saying..?

**Comment by janbildsoehansen** [comment]
soo i need another website for my "online" customers..?

**Comment by minhcasi** [comment]
Hi, the link .../mstore-checkout/is only used for the mobile purpose, once user process payment on your website it will go through other URL from WooCommerce - so basically this is not an issue 

Let us know if you have any queries - thank you :)

**Comment by janbildsoehansen** [comment]
annd this Reactotron never start up
