### ISSUE TITLE
[BeoNews]  fixing errors last version

### ISSUE THREAD

**Issue by iqmtgar** [inspireui/support#564]
BeoNews Pro - React Native mobile app for Wordpress
--
Regular License
Purchase code: 1717b3f7-6421-485a-a18c-25912ff9a8b4

Hello, how are you ..
This is a problem encountered in the application
is there a solution ?

![2019-05-08_00h10_29](https://user-images.githubusercontent.com/33340985/57315355-14876d80-70fc-11e9-83fe-9968e7760e93.png)

**Comment by minhcasi** [comment]
Hi, could you help to share your config files that locate from the common folder (appConfig.json and config.js) - thanks
