### ISSUE TITLE
[BeoNews] I can't retrieve token

### ISSUE THREAD

**Issue by ali-sao** [inspireui/support#565]
Hello ,

I am suffering with WP JWT , whenever I request a token , the response is always : `[jwt_auth] empty_username`

I did everything required to get the JWT plugin working fine :

in wp-config.php :

```
define('JWT_AUTH_SECRET_KEY', 'MY_SUPER_PASSWORD');
define('JWT_AUTH_CORS_ENABLE', true);
in .htacess

RewriteEngine On
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule ^(.*) - [E=HTTP_AUTHORIZATION:%1]
SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1
```
The request structure is the same :
```

WordpressAPI.prototype.getJWTToken = function(username, password) {
  var requestUrl = this.url + "/wp-json/jwt-auth/v1/token/";
  var options = {
    method: "POST",
    headers: {
      Accept: "application/json",
      "Content-Type": "application/json"
    },
    withCredentials: false,
    body: JSON.stringify({ username, password })
  };
  return fetch(requestUrl, options).then(response => response.json());
};
```
What should I do ?

**Comment by minhcasi** [comment]
Hi, could you share your website here? We would like to check the URL - thanks

**Comment by ali-sao** [comment]
cheersAmman.com

**Comment by minhcasi** [comment]
Hi, sorry for the lated response - we have checked the jwt setting and it working fine, the problem could be your Wordpress setitng, could you try to check if this option is checked - https://docs.inspireui.com/beonews/wordpress-setting/#membership-registration

**Comment by ali-sao** [comment]
I've re-modified the .htacess file and it is working fine now . Thank you

**Comment by sol994** [comment]
could you please share your solution
