### ISSUE TITLE
[MStore] Shipping and payment gateway issue

### ISSUE THREAD

**Issue by xuanzi23** [inspireui/support#566]
**Required Info (please complete the following information):**
 - Product: MStore
 - Your Purchased Code: b39d1765-666a-450e-afcb-ea4a5b43dab4
(we may not reply if you are not our customer)

**Describe the bug**
1. My Woocommerce shipping setting got based on shipping zones. Is this MStore pro support Shipping zones settings? I test will success order , It is suppose to happen?

Beside that I have few question 
1. It is support ipay88 and molpay payment gateway?
2. This mstore pro support plug in "purchase with purchase"?

**Screenshots**
![Screen Shot 2019-05-08 at 4 24 25 PM](https://user-images.githubusercontent.com/19340910/57361044-24f82080-71ae-11e9-8f66-0c0eb63f6b73.png)
This is the setting I set in Woocommerce

**Comment by minhcasi** [comment]
Hi, sorry for lated response, the current feature is not supported for shipping zone setting, it's is default to the first zone with multi Flat rates

We have not tested on molpay and ipay88, please try to check from your side, if it works fine on the WooCommerce plugin then we think it could work well with the app.

The purchase with purchase it not support at current features

 - thank you!
