### ISSUE TITLE
[MStore] Shipping Charges is not working properly

### ISSUE THREAD

**Issue by Relimer-Technologies** [inspireui/support#567]
Mandatory Info (please complete the following information):

Product: [e.g. MStore, ListApp]
M Store Pro
Purchase Code: d98eb201-aba4-4c76-a0a1-cbd67415737d
Your Purchased Code: [get from https://codecanyon.net/downloads]
(we may not reply if you are not our customer)
Describe the issues
Hello,

Good Morning, I have purchased M Store Pro from Envato. I have done all the setup required... I have installed all of the required tools... I have a basic request for shipping charges... I have assigned Flat Rate as 450 and Free Shipping as 0 with the condition of Total amount to be greater than or equal to 25000... I am able to get both the shipping options during checkout but
the condition for Free Shipping is not fulfilled... I need the customer to avail free shipping only if they do 25000 or above value shopping but in the app, both the shipping are shown for any value of the cart.

![Screenshot](https://user-images.githubusercontent.com/47352123/57365957-b44c0680-71a3-11e9-8c62-bea1268098e2.jpeg)

Kindly help me out with this... Thank You

**Comment by Relimer-Technologies** [comment]
Hello, @minhcasi  Kindly reply to me soon.

**Comment by minhcasi** [comment]
Hi, do you mean to display the free shipping flat base on the total cost of the checkout ?

**Comment by Relimer-Technologies** [comment]
Hello, @minhcasi  I want the customer to get an automatic Free Shipping when he shops more than 25000 in the app. Please help me with this. Thank You

**Comment by minhcasi** [comment]
Hi, sorry as this is kind of specific customize so that we could only provide the solution to implement it:

Check from the Delivery component (inside the cart), and check the total cost from the ShouldComponentUpdate function if the total reach to 25000, then you can update the shipping state to the Free value 

Thanks!

**Comment by Relimer-Technologies** [comment]
Hello, @minhcasi  I am unable to find ShouldComponentUpdate function. Kindly help me out with this.

**Comment by naldekhel** [comment]
Am also interested in this solution and want to know where to find the ShouldComponentUpdate. I need to have the free shipping appears only when the customer reach XX amount in their cart.
