### ISSUE TITLE
[ListApp] User logging  out automatically everytime he close the app

### ISSUE THREAD

**Issue by DNeelanshi** [inspireui/support#569]
**Required Info (please complete the following information):**
Product ListApp
I have purchased the code from https://codecanyon.net/item/listapp-listing-directory-mobile-app-by-react-native/21456447?s_rank=3

**Describe the bug**
The user log out automatically everytime he normally closes the app. he needs to sign in again and again. Please help us to solve this issue.

**Screenshots**

**Additional context**
I am not using firebase in this app anymore. Thanks for solving issues earlier. please help us solving this auto sign out issue whenever user closes the app.

**Comment by thangvo9x** [comment]
Hi, Please share AppConfig.json for checking this issue. 
you can attach some screenshots for this issue. Thanks

**Comment by DNeelanshi** [comment]
> Hi, Please share AppConfig.json for checking this issue.
> you can attach some screenshots for this issue. Thanks


yes, i will mail you.with appconfig.json and a video showing the issue.

**Comment by DNeelanshi** [comment]
> Hi, Please share AppConfig.json for checking this issue.
> you can attach some screenshots for this issue. Thanks

{
  "Website": {
    "url": "http://innovativegeeks.gangtask.com/wowtrip/",
     "consumerKey": "ck_3becccaf5a7b570236e1f3411fe768f20b2df14c",
     "consumerSecret": "cs_ad1149a7f836ee8bc10256d9a874443838f084dd"
  },
  "Theme": "listable",
  "MainColor": {
    "tabbarTint": "#189AA2",
    "tabbarColor": "#D5D8DE",
    "mainColorTheme": "#189AA2",
    "tabbar": "#fff"
  }
}

**Comment by DNeelanshi** [comment]
Hello, did you got my mail with video.?

**Comment by DNeelanshi** [comment]
I need to solve this issue urgently. please help

**Comment by DNeelanshi** [comment]
> Hello, did you got my mail with video.?
here is the link to video.
https://drive.google.com/open?id=1XD-hz9PbUFlu1aE2EPS8oedtzlUUCalT

**Comment by thangvo9x** [comment]
Hi. We checked on your AppConfig. It has work normal. Do you have to eject the project?
https://we.tl/b-pR8q0tWNDQ

**Comment by DNeelanshi** [comment]
Hello, I don't understand what you said . I am not ejecting it now.

Sent from Yahoo Mail on Android 
 
  On Mon, 13 May 2019 at 10:03 AM, Tony Vo<notifications@github.com> wrote:   
Hi. We checked on your AppConfig. It has work normal. Do you have to eject the project?
https://we.tl/b-pR8q0tWNDQ

**Comment by DNeelanshi** [comment]
> Hi. We checked on your AppConfig. It has work normal. Do you have to eject the project?
> https://we.tl/b-pR8q0tWNDQ
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/1aeef7cb4909a5fd1a6328233b66639a2b923037/68747470733a2f2f6170692e77657472616e736665726d6f62696c652e636f6d2f76312f70726576696577732f7364366d6b706c31646832756466647a3632303139303531333034333130332f733430736c6a63786a377835727a6162643230313930353133303433313034">**[Checked.mov - Collect by WeTransfer](https://boards.wetransfer.com/board/sd6mkpl1dh2udfdz620190513043103/latest)**The best way to save, organize and share ideas from all your apps

PLease

**Comment by DNeelanshi** [comment]
> > Hi. We checked on your AppConfig. It has work normal. Do you have to eject the project?
> > https://we.tl/b-pR8q0tWNDQ
> > > <img alt="" width="48" src="https://camo.githubusercontent.com/1aeef7cb4909a5fd1a6328233b66639a2b923037/68747470733a2f2f6170692e77657472616e736665726d6f62696c652e636f6d2f76312f70726576696577732f7364366d6b706c31646832756466647a3632303139303531333034333130332f733430736c6a63786a377835727a6162643230313930353133303433313034">**[Checked.mov - Collect by WeTransfer](https://boards.wetransfer.com/board/sd6mkpl1dh2udfdz620190513043103/latest)**The best way to save, organize and share ideas from all your apps
> 
> PLease
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/1aeef7cb4909a5fd1a6328233b66639a2b923037/68747470733a2f2f6170692e77657472616e736665726d6f62696c652e636f6d2f76312f70726576696577732f7364366d6b706c31646832756466647a3632303139303531333034333130332f733430736c6a63786a377835727a6162643230313930353133303433313034">**[Checked.mov - Collect by WeTransfer](https://boards.wetransfer.com/board/sd6mkpl1dh2udfdz620190513043103/latest)**The best way to save, organize and share ideas from all your apps

Pleasehelp me and  let me know the logic behind user logging session? is it done by firebase or local storage or anything else, so that i can find out what is missing that user session is expiring everytime user close the app.I shall be really thankful to you.

**Comment by thangvo9x** [comment]
Yes. We use Local Storage to save data usage.

**Comment by DNeelanshi** [comment]
> Yes. We use Local Storage to save data usage.

Thanks for you answer, so if can tell me the files name, in which the code of user session is working. i can see the files and compare the code with code of your latest version, i can find the difference and issue.

**Comment by DNeelanshi** [comment]
> Yes. We use Local Storage to save data usage. you can edit it in App/Services/UserModal.js

okay i m checking it.

**Comment by DNeelanshi** [comment]
this is my App/Services/Usermodal.js file. I dont find any problem in this? Is there any other file which also can be need to check for user session functionality?


/** @format */

import React, { Component } from 'react'
import { AsyncStorage } from 'react-native'
import { Constants, Config } from '@common'
import { WooWorker } from 'api-ecommerce'
import Api from './Api'
import WPUserAPI from './WPUserAPI'
import firebaseApp from '@services/Firebase'
import * as firebase from 'firebase'
import { remove, findIndex } from 'lodash'

function UserModal() {
  if (!(this instanceof UserModal)) {
    return new UserModal()
  }
}

/**
 * Check the user login data is existing on the app
 * @returns {boolean}
 */
UserModal.prototype.isLogedIn = async function() {
  try {
    var value = await AsyncStorage.getItem(Constants.Key.user)

    // can also use this
    // AsyncStorage.getItem(Constants.Key.user).then((user_data_json) => {
    // 	let user_data = JSON.parse(user_data_json);
    // }
    return value !== null
  } catch (error) {
    // console.log('error isLogin', error);
  }
}


/**
 * create account with firebase
 * @param email
 * @param password
 * @param callBackFunc
 * @param onError
 */
UserModal.prototype.createWithFirebase = async function(
  email,
  password,
  callBackFunc,
  onError
) {
  try {
    firebaseApp
      .auth()
      .createUserWithEmailAndPassword(email, password)
      .then((userData) => {
        if (typeof callBackFunc === 'function') {
          callBackFunc()
        }
        return this.saveUser(userData, email)
      })
      .catch((error) => {
        if (typeof onError === 'function') {
          onError(error)
        }
      })
  } catch (error) {
    console.log(error)
  }
}

/**
 * Create the user login
 * @param email
 * @param password
 * @param callBackFunc
 */

//#1
UserModal.prototype.create = async function(
  email,
  password,
  name,
  callBackFunc,
  onError,
  isExisted
) {
  try {
    // existed on wordpress create with firebase
    if (isExisted) {
      // this.createWithFirebase(email, password, callBackFunc, onError)
    }
    // register on Wordpress site
    const wordpressRegisterd = await Api.register(email, password, name)
    if (
      typeof wordpressRegisterd.status !== 'undefined' &&
      wordpressRegisterd.status === 'ok'
    ) {
      if (Constants.firebaseEnable) {
        this.createWithFirebase(email, password, callBackFunc, onError)
      } else {
        this.saveUser(null, email)
        if (typeof callBackFunc === 'function') {
          callBackFunc()
        }
      }
    } else {
      onError(wordpressRegisterd)
    }
  } catch (error) {
    console.log(error)
  }
}

/**
 * login on both Wordpress and Firebase
 * @param email
 * @param password
 * @param callBackFunc
 */

//#2
UserModal.prototype.login = async function(
  email,
  password,
  callBackFunc,
  onError
) {
  try {
    const wordpressLoggined = await Api.getJWTToken(email, password)
    // console.log(['wplogined', wordpressLoggined])
    if (wordpressLoggined.token != undefined) {
      // const userInfo = await Api.getUserInfoByToken(wordpressLoggined.token)
      const userInfo = await WPUserAPI.login(email, password)
      const userExtraInfo = await WooWorker.getCustomerById(userInfo.user.id)
      // console.warn([userInfo, userExtraInfo])
      var user = {
        userId: userInfo.user.id,
        jwtToken: wordpressLoggined.token,
        cookie: userInfo.cookie,
        displayName: wordpressLoggined.user_display_name,
        email: wordpressLoggined.user_email,
        photoURL: '',
        ...userExtraInfo,
      }
      // console.log(user)
      var self = this
      // if enable user also save to Firebase
      if (Constants.firebaseEnable) {
        firebaseApp
          .auth()
          .signInWithEmailAndPassword(email, password)
          .then((response) => {
            user.uid = response.user.uid
            self.saveUser(
              user,
              email,
              password,
              userExtraInfo.billing,
              userExtraInfo.shipping
            )
            if (typeof callBackFunc == 'function') {
              callBackFunc()
            }
          })
          .catch((error) => {
            // if use not found on firebase, just create it for saving app data
            if (error.code === 'auth/user-not-found') {
              return this.create(
                email,
                password,
                null,
                callBackFunc,
                onError,
                true
              )
            }
            if (typeof onError === 'function') {
              onError(error)
            }
          })
      } else if (typeof callBackFunc === 'function') {
        this.saveUser(user, email)
        callBackFunc()
      }
    } else {
      if (typeof onError == 'function') {
        onError(wordpressLoggined)
      }
    }
  } catch (err) {
    onError(err)
  }
}

UserModal.prototype.loginFacebook = async function(accessToken) {
  return new Promise(async (resolve, reject) => {
    const auth = firebaseApp.auth()
    const credential = firebase.auth.FacebookAuthProvider.credential(
      accessToken
    )

    auth
      .signInAndRetrieveDataWithCredential(credential)
      .then(async (data) => {
        const json = await WPUserAPI.loginFacebook(accessToken)
        if (json === undefined || json.error) {
          reject(json.error)
        } else {
          let userInfo = await WooWorker.getCustomerById(json.wp_user_id)
          let userData = { ...userInfo, data, isLoginFB: true }
          let userEmail = data.user.email
          if (userEmail == null) {
            userEmail = `${data.user.uid}@facebook.com`
          }
          this.saveUser(userData, userEmail)
          resolve(userData)
        }
      })
      .catch((err) => reject(err))
  })
}

UserModal.prototype.loginGoogle = async function(input) {
  let auth = firebaseApp.auth()
  let credential = firebase.auth.GoogleAuthProvider.credential(input.idToken)
  let data = await auth
    .signInWithCredential(credential)
    .catch((err) => console.log(err))
  return this.saveUser(data, input.user.email)
}

/**
 * Save user data to offline
 * @param userData
 * @param email
 */
UserModal.prototype.saveUser = async function(
  userData,
  email,
  password = null,
  billing = null,
  shipping = null
) {
  try {
    await AsyncStorage.setItem(Constants.Key.email, email)
    if (typeof password != null) {
      userData.password = password
    }
    if (typeof billing != null) {
      userData.billing = billing
    }
    if (typeof shipping != null) {
      userData.shipping = shipping
    }
    await AsyncStorage.setItem(Constants.Key.user, JSON.stringify(userData))
  } catch (error) {
    console.error(['errSaveUser', error])
  }
}

/**
 * get read later user
 */
UserModal.prototype.getUser = async function() {
  let userData = await AsyncStorage.getItem(Constants.Key.user)
  console.warn(['getUser', userData])
  if (userData != null) {
    return JSON.parse(userData)
  } else {
    return null
  }
}

UserModal.prototype.getPosts = async function() {
  const userPosts = await AsyncStorage.getItem(Constants.Key.posts)

  var postData = []
  if (userPosts != null) {
    postData = JSON.parse(userPosts)
  }

  // if the offline data is null let check the online and sync back to the app
  if (postData.length == 0) {
    postData = await this.getFirebasePost()
    AsyncStorage.setItem(Constants.Key.posts, JSON.stringify(postData))
  }

  return postData
}

/**
 * Get the data from firebase
 * @returns {*|string|string}
 */
UserModal.prototype.getFirebasePost = async function() {
  const userData = await this.getUser()
  var postData = []

  if (typeof userData != 'undefined' && typeof userData.uid != 'undefined') {
    const data = await firebaseApp
      .database()
      .ref('/' + Config.Firebase.readlaterTable + '/' + userData.uid)
      .once('value')

    if (data.val() != null) {
      postData = data.val().post
    }
  } else {
    // console.log('can not get user data');
  }

  return postData
}

/**
 * Add the post to firebase
 * @param post
 */
UserModal.prototype.firebaseSync = async function(postData) {
  const userData = await this.getUser()

  if (typeof userData != 'undefined' && typeof userData.uid != 'undefined') {
    firebaseApp
      .database()
      .ref(Config.Firebase.readlaterTable)
      .child(userData.uid + '/post')
      .set(postData)
  }
}

/**
 * Save read later post and sync to firebase
 * @param post
 */
UserModal.prototype.savePost = async function(post, fnc) {
  if (typeof post == 'undefined' || post == null) {
    return
  }

  const userPosts = await AsyncStorage.getItem(Constants.Key.posts)
  var postData = []
  if (userPosts != null) {
    postData = JSON.parse(userPosts)
  }

  const indexPost = findIndex(postData, (data) => {
    return data.id == post.id
  })

  // not in the read later array yet
  if (indexPost == -1) {
    postData.push(post)

    // save to storage local
    await AsyncStorage.setItem(Constants.Key.posts, JSON.stringify(postData))

    if (typeof fnc == 'function') {
      fnc()
    }

    // sync to firebase
    this.firebaseSync(postData)
  }
  // console.log('save post', indexPost, post);
}

/**
 * remove read later post
 * @param post
 */
UserModal.prototype.removePost = async function(post, fnc) {
  const userPosts = await AsyncStorage.getItem(Constants.Key.posts)
  var postData = []
  if (userPosts != null) {
    postData = JSON.parse(userPosts)
  }
  var newPostData = remove(postData, (data) => {
    return data.id != post.id
  })

  AsyncStorage.setItem(Constants.Key.posts, JSON.stringify(newPostData))

  if (typeof fnc == 'function') {
    fnc()
  }
  // sync to firebase
  this.firebaseSync(newPostData)
}

/**
 * Remove all read later post
 */
UserModal.prototype.clearPosts = function(isSync) {
  // should remove online also
  if (typeof isSync != 'undefined') {
    this.firebaseSync(null)
  }
  // console.log(AsyncStorage.getItem(Constants.Key.posts));
  AsyncStorage.getItem(Constants.Key.posts).then((data) => {
    // console.log('data asyncStorage: ', data)
    if (data != null) {
      return AsyncStorage.multiRemove([Constants.Key.posts], (err) => {})
    }
  })
}

/**
 * Logout and delete all offline data
 */
UserModal.prototype.logOut = function() {
  AsyncStorage.getItem(Constants.Key.user).then((data) => {
    // console.log('data asyncStorage: ', data)
    if (data != null) {
      return AsyncStorage.multiRemove([Constants.Key.user], (err) => {})
    }
  })
}

export default UserModal

**Comment by thangvo9x** [comment]
Yes. We use AsyncStorage from React Native lib to save user data.
