### ISSUE TITLE
bug in chat 

### ISSUE THREAD

**Issue by alaradi2006** [inspireui/support#57]
**Required Info (please complete the following information):**
 - Product: [e.g. MStore, ListApp]
 - Your Purchased Code: [get from https://codecanyon.net/downloads]
(we may not reply if you are not our customer)
a9c6782d-8c5d-4811-8c4a-2ccc9d6be005 mstore multivendor
**Describe the bug**
if open i chat i cant go back to menu or to the app 
i have to shutdown the app to enter it again 
as the back option in upper parts all disappear
**Screenshots**

**Additional context**
Add any other detail logs about the problem here.
If possible please share your config.js that use for the app setting

**Comment by minhcasi** [comment]
Can you provide the screenshot of "as the back option in upper parts all disappear"

**Comment by alaradi2006** [comment]
see
i cant go back to app
if i press my phone button app will close

________________________________
