### ISSUE TITLE
Unable to install ListApp 1.7 on CeBuilder - Windows 

### ISSUE THREAD

**Issue by hgimasa** [inspireui/support#570]
**Mandatory Info (please complete the following information):**
 - Product: ListApp
 - Your Purchased Code: 04923267-a35d-4da9-a095-71038cd1f72c
\

**Describe the issues**
I'm unable to install ListApp version 1.7 project on CeBuilder. Error: Currently, CeBuilder hasn’t supported this project yet.

**Screenshots**

**Additional context**
Here is the error message : Currently, CeBuilder hasn’t supported this project yet.

**Comment by minhcasi** [comment]
Hi, we could not replicate this issue, could you take the whole screenshot - we guess you may open the wrong folder - please check some video guide here could be help - https://www.youtube.com/playlist?list=PLcF-HiQy-jOLg0O6d9uWhOqGhvvLfx6is
