### ISSUE TITLE
[ListPro] How I can Use the app witout Expo SdK without any errors when build on the android and ios ?

### ISSUE THREAD

**Issue by alex-zapalago** [inspireui/support#571]
I am want to use the react-native theme without the expo sdk, I have searched in blogs,and documentation and use the command expo eject both to react-native and expokit,but
when I will use the app both on the linux os and the mac os to build the app to android and ios systems,but there is some errors,it is possible to use all the theme made on the react native without expo sdk,because our company have tried to build the app with expo yours,
but the size of the ipa is too large it was over 150 mb is  too large,Help me !!
Dear,regards!!!

**Comment by thangvo9x** [comment]
Hi, Which product are you using? as provide us your purchase code. Thanks

**Comment by alex-zapalago** [comment]
I am using ListPro - Listing Directory React Native template

**Comment by alex-zapalago** [comment]
This is my your purchase code  394cc125-41eb-4a56-962a-c87409a56be3

**Comment by alex-zapalago** [comment]
This is my purchase code 394cc125-41eb-4a56-962a-c87409a56be3

**Comment by thangvo9x** [comment]
Hi. Do you have run "expo eject" or "expo --help" for help?

**Comment by alex-zapalago** [comment]
yes I have run expo eject,but follow the image

**Comment by alex-zapalago** [comment]
![expo](https://user-images.githubusercontent.com/50205170/57525074-19b50a00-7300-11e9-8614-43982db5d512.png)

**Comment by alex-zapalago** [comment]
If I eject the project,all this files in color blue are not worked fine after

**Comment by thangvo9x** [comment]
Hi. Try update expo-cli before run expo eject.

**Comment by alex-zapalago** [comment]
yes i do

**Comment by minhcasi** [comment]
note that we will check solution if add the cli version later - thanks

**Comment by minhcasi** [comment]
closed & move to backlogs
