### ISSUE TITLE
[MStore] I disabled the Home Screen Tab and Back button is not working.

### ISSUE THREAD

**Issue by mkashifrazzaq11** [inspireui/support#572]
**Required Info (please complete the following information):**
MStore
f8d919b7-3308-4d8c-a454-6b2685fbae9c

**Describe the bug**
I disabled the Home Screen Tab. User can find the products using Search Tab and Category Tab.
After the adding the product into the cart, the back Button is not working and it should go to the back screen where I added the product.

**Screenshots**

**Additional context**
Add any other detail logs about the problem here.
If possible please share your config.js that use for the app setting
[common.zip](https://github.com/inspireui/support/files/3159684/common.zip)

**Comment by minhcasi** [comment]
Hi, please help to customize the back button from the Product - pls refer to this guide - https://reactnavigation.org/docs/en/navigating.html#going-back - this is not a bug - thank you!
