### ISSUE TITLE
[MStore] Two Shipping method problem

### ISSUE THREAD

**Issue by mkashifrazzaq11** [inspireui/support#573]
**Required Info (please complete the following information):**
MStore
f8d919b7-3308-4d8c-a454-6b2685fbae9c

**Describe the bug**
My website has two shipping method, one is Free shipping and second is Flat rate. If Total amount is more then Rs. 999 the Free Shipping method apply otherwise Flat Rate apply. But this is not working in app. How can I do this without user selection?  

**Screenshots**

**Additional context**
[common.zip](https://github.com/inspireui/support/files/3159714/common.zip)

**Comment by minhcasi** [comment]
Hi, this is kind of your customize shipping condition, not a bug from the app.

First, you can disable the shipping and not allow the user to tap the shipping option.
Second, you can check the condition to assign the proper shipping value base on the total cost.

file locate: container/Cart/Delivery/index.js
screenshot: https://tppr.me/k1Clu

Hope this help, thanks
