### ISSUE TITLE
[Listapp] featured images not display after theme update

### ISSUE THREAD

**Issue by reconshield** [inspireui/support#574]
some of featured images not display after i update mylisting theme. my image size 300x300 / 300/600x600 /1024x1024 and i did generate image thumbnail tools also. i can see featured images in my listing. why this happen?

![Simulator Screen Shot - iPhone XR - 2019-05-09 at 09 51 03](https://user-images.githubusercontent.com/25501496/57429754-ffc3ea80-725f-11e9-97f6-eef2c312f482.png)

**Comment by thangvo9x** [comment]
https://github.com/inspireui/support/issues/560
