### ISSUE TITLE
[Mstore Pro] App Getting Crashed in Android Q and real device with Android 9

### ISSUE THREAD

**Issue by davekedar** [inspireui/support#576]
Required Info (please complete the following information):

Product: [MStore]
Your Purchased Code: f9eaf46b-d573-484d-945f-4236e184eeaf
The app is getting crashed while loading the home page, I can go upto home page but it is getting crashed at loading the products please help asap, there no other api are getting called after that

Please check this link for the screen capture
http://s000.tinyupload.com/?file_id=67490625812603552900

**Comment by davekedar** [comment]
it is very difficult when u have live app which gets crashed like this plz help asap

**Comment by davekedar** [comment]
this is the real applicaiton u can download and check in real device https://play.google.com/store/apps/details?id=in.applified.ecom

**Comment by davekedar** [comment]
![image](https://user-images.githubusercontent.com/11268363/57503828-8f74a200-730f-11e9-88aa-fee640b00af8.png)

**Comment by minhcasi** [comment]
Thank for reporting, confirm it's a bug on Android 9 - tested with my Samsung S9 - thanks

**Comment by minhcasi** [comment]
related - https://app.intercom.io/a/apps/xro9xnfd/inbox/inbox/2664005/conversations/21813139614

**Comment by minhcasi** [comment]
@davekedar - try to replace your all images to https will fix the issues 

There is also the config from common/Images.js should be changed to https as well - PlaceHolderURL: "https://mstore.io/wp-content/uploads/2017/07/placeholder.png",

**Comment by minhcasi** [comment]
<img width="701" alt="Screen Shot 2019-05-12 at 11 46 24 AM" src="https://user-images.githubusercontent.com/1459805/57577904-a3550b00-74ab-11e9-8ce2-348a0214fd3e.png">

**Comment by maulikvora** [comment]
@minhcasi can you tell us what changes we need to do to fix this issue of crash on Android 9? We have version 3.7.2 integrated and have made many customizations, so don't want to do those customizations again and just want to fix this issue.

thanks

**Comment by davekedar** [comment]
@maulikvora please change all url for home page image place holder to https://, I did the same and it is working perfectly. Kindly let me know if that doesn't work

**Comment by maulikvora** [comment]
Thanks @davekedar for quick response.
I will try that and let you know.
