### ISSUE TITLE
[MStore] Free Shipping Error and Currency Error

### ISSUE THREAD

**Issue by naldekhel** [inspireui/support#579]
**Required Info (please complete the following information):**
 - Product: [MStore]
 - Your Purchased Code: e5717440-ab94-463d-88b1-54f99f460276
(we may not reply if you are not our customer)

**Describe the bug**
Hi there, 

First of all, 
I only ship to certain countries and i have that set on my website. But in the app, in the shipping address, it shows all countries.
![shipping-to-certain-countries-issue](https://user-images.githubusercontent.com/4033049/57587921-6aea1700-7515-11e9-93d9-2a17fa9eddac.jpg)

2- I have set a free shipping to be used only with a free shipping coupon that would be added automatically when your cart is more than $500. However, when i used the app, the free shipping appears even if my cart is only $10. How can i configure that? 
![Free-Shipping-issue](https://user-images.githubusercontent.com/4033049/57587840-58bba900-7514-11e9-8d76-80d9446de5f2.jpg)

3- Also, i have different shipping methods for different parts of the world. For example Saudi Arabia has SMSA and ARAMEX shipping methods. But USA only has SMSA shipping method. The problem is whatever country i put, all shipping methods comes for all countries and all are the same price. 
![Countries-shipping-method-issue](https://user-images.githubusercontent.com/4033049/57587886-10e95180-7515-11e9-97a9-33bb4fdae977.jpg)

4- Another thing, the currency in my website is set as ر.س ( Saudi Arabian Riyal ) but in the app its showing ( $ ) i dont know why! 
![Currency-issue](https://user-images.githubusercontent.com/4033049/57587986-4c385000-7516-11e9-9918-5618b8b80bfc.jpg)

5- One last thing, does expo version support multilingual? 

Thanks

**Comment by minhcasi** [comment]
Hi, sorry the feature #1, #2, #3 are the advance feature that will be required your customization 

#4 - you can change it from the config.js file - set the default currency and country.

#5 - the expo is not support for multilingual at the moment 

Thank you!

**Comment by naldekhel** [comment]
How much is it to do these customization? 
Thanks

**Comment by minhcasi** [comment]
Hi, sorry we have not supported for the customize so far, please help to find some Developers help for your customize - thank you!
