### ISSUE TITLE
i changed the currency but product currency not changed

### ISSUE THREAD

**Issue by alaradi2006** [inspireui/support#58]
**Required Info (please complete the following information):**
 - Product: [e.g. MStore, ListApp]
 - Your Purchased Code: [get from https://codecanyon.net/downloads]
(we may not reply if you are not our customer)

**Describe the bug**
currency switcher not working 
i change the currency switcher from usd to another currency but product price not changing 
**Screenshots**

**Additional context**
Add any other detail logs about the problem here.
If possible please share your config.js that use for the app setting

**Comment by minhcasi** [comment]
try to clean the simulator cache will fixed the issue - thanks
