### ISSUE TITLE
Error when running the app on android

### ISSUE THREAD

**Issue by pramaanamlive** [inspireui/support#580]
**Mandatory Info (please complete the following information):**
- Product: BeoNews Pro
- Your Purchased Code: a06b2816-495d-4e90-aea5-a3826664995d

**Describe the issues**
Error when running the app on android

**Screenshots**
![Screenshot 2019-05-13 at 10 43 45 AM](https://user-images.githubusercontent.com/49845943/57592989-0efead00-756c-11e9-94b0-ae2b1765bfe6.png)

**Additional context**
> Task :app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1m 35s
124 actionable tasks: 1 executed, 123 up-to-date
error Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html
error Command failed: ./gradlew app:installDebug

**Comment by minhcasi** [comment]
The screenshot is quite blurred that we could not read it, could you help to upload it again.  Also try with the Cebuilder to see it can be fixed - https://inspireui.com - thank you!
