### ISSUE TITLE
[Cestore] Website installing error

### ISSUE THREAD

**Issue by s3665959** [inspireui/support#581]
**Mandatory Info (please complete the following information):**
 - Product: [cestore]
Item Purchase Code:
43fdac4f-37a3-4414-9687-c850d0******

i have follow your video CeStore - Website installing (ReactJS) at youtube. and
i got an error after in run : 
npm i 
npm run build 
npm start

the error show below :
`D:\cestore\CeStore-1.3.0\Source\web> npm i

> bcrypt@3.0.2 install D:\cestore\CeStore-1.3.0\Source\web\node_modules\bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
[bcrypt] Success: "D:\cestore\CeStore-1.3.0\Source\web\node_modules\bcrypt\lib\binding\bcrypt_lib.node" is installed via remote

> husky@0.14.3 install D:\cestore\CeStore-1.3.0\Source\web\node_modules\husky
> node ./bin/install.js

husky
setting up Git hooks
can't find .git directory, skipping Git hooks installation

> node-sass@4.9.4 install D:\cestore\CeStore-1.3.0\Source\web\node_modules\node-sass
> node scripts/install.js

Cached binary found at C:\Users\s3665959\AppData\Roaming\npm-cache\node-sass\4.9.4\win32-x64-57_binding.node

> node-sass@4.9.4 postinstall D:\cestore\CeStore-1.3.0\Source\web\node_modules\node-sass
> node scripts/build.js

Binary found at D:\cestore\CeStore-1.3.0\Source\web\node_modules\node-sass\vendor\win32-x64-57\binding.node
Testing binary
Binary is fine
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 1696 packages from 783 contributors in 133.344s
PS D:\cestore\CeStore-1.3.0\Source\web> npm run build

> cezerin@0.33.0 build D:\cestore\CeStore-1.3.0\Source\web
> npm run compile && npm run theme:build && npm run webpack:admin

> cezerin@0.33.0 compile D:\cestore\CeStore-1.3.0\Source\web
> babel src/store -d dist/store --presets react --plugins transform-class-

> cezerin@0.33.0 theme:build D:\cestore\CeStore-1.3.0\Source\web
> babel theme/src -d theme/dist --presets react --plugins transform-class-
webpack:store

> cezerin@0.33.0 webpack:store D:\cestore\CeStore-1.3.0\Source\web
> webpack --config webpack.config.store.js --mode production

Browserslist: caniuse-lite is outdated. Please run next command `npm updat
Browserslist: caniuse-lite is outdated. Please run next command `npm updatBrowserslist: caniuse-lite is outdated. Please run next command `npm updat
Browserslist: caniuse-lite is outdated. Please run next command `npm updatBrowserslist: caniuse-lite is outdated. Please run next command `npm updat
Browserslist: caniuse-lite is outdated. Please run next command `npm updatHash: 0b5ca7d86227f8e934a2
Version: webpack 4.23.1Time: 71275ms
Built at: 2019-05-13 16:23:49                                                       Asset       Size  C Names                  assets/css/bundle-5abb77617d1f37704ada.css   27.2 KiB                                              assets/index.html    1.7 KiB   ed]
                       assets/js/app-05e8385bba16625f7c3a.js    319 KiB   ed]  [big]  app
                     assets/js/theme-a4ef303467af77df7434.js    924 KiB   ed]  [big]  theme                                                assets/swB          [emitted]
assets\precache-manifest.2ec896540713879b2ed8fd590f3035da.js  259 bytes   ed]

> cezerin@0.33.0 webpack:admin D:\cestore\CeStore-1.3.0\Source\web
> webpack --config webpack.config.admin.js --mode production

Browserslist: caniuse-lite is outdated. Please run next command `npm update browserslist`
Browserslist: caniuse-lite is outdated. Please run next command `npm updatd `npm update caniuse-lite browserslist`
Browserslist: caniuse-lite is outdated. Please run next command `npm updatd `npm update caniuse-lite browserslist`
Browserslist: caniuse-lite is outdated. Please run next command `npm updatd `npm update caniuse-lite browserslist`
Browserslist: caniuse-lite is outdated. Please run next command `npm updatd `npm update caniuse-lite browserslist`
Browserslist: caniuse-lite is outdated. Please run next command `npm updatPS D:\cestore\CeStore-1.3.0\Source\web> npm start
Hash: 66eac3c3843a2a103f1a
> cezerin@0.33.0 start D:\cestore\CeStore-1.3.0\Source\web
> concurrently npm:start-*
Built at: 2019-05-13 16:25:28
[start-api]                                Asset      Size  Chunks        [start-api] > cezerin@0.33.0 start-api D:\cestore\CeStore-1.3.0\Source\web/css/bundle-5dc4d675beef490f5477.css  33.8 KiB       0  [emitt[start-api] > node -r esm src/api/server/index.js
[start-api] ssets/js/app-7c4559d5a8153882bd5a.js   999 KiB       0  [emitt[start-store] ]  [big]  app
[start-store] > cezerin@0.33.0 start-store D:\cestore\CeStore-   1  [emitt1.3.0\Source\web [big]  vendor
[start-store] > node -r esm dist/store/server/index.js KiB          [emitt
[start-store] ]
[start-store] info: Store running at http://localhost:3000
[start-api] info: API running at http://localhost:3001
[start-api] error: uncaughtException: database name must be a
string
[start-api] MongoError: database name must be a string
[start-api]     at Function.create (D:\cestore\CeStore-1.3.0\Source\web\node_modules\mongodb-core\lib\error.js:43:12)
[start-api]     at validateDatabaseName (D:\cestore\CeStore-1.3.0\Source\web\node_modules\mongodb\lib\operations\db_ops.js:696:22)
[start-api]     at new Db (D:\cestore\CeStore-1.3.0\Source\web\node_modules\mongodb\lib\db.js:180:3)
[start-api]     at MongoClient.db (D:\cestore\CeStore-1.3.0\Source\web\node_modules\mongodb\lib\mongo_client.js:268:14)
[start-api]     at MongoClient.connect (D:\cestore\CeStore-1.3.0\Source\web\src\api\server\lib\mongo.js:39:25)
[start-api]     at result (D:\cestore\CeStore-1.3.0\Source\web\node_modules\mongodb\lib\utils.js:414:17)
[start-api]     at executeCallback (D:\cestore\CeStore-1.3.0\Source\web\node_modules\mongodb\lib\utils.js:406:9)
[start-api]     at err (D:\cestore\CeStore-1.3.0\Source\web\node_modules\mongodb\lib\operations\mongo_client_ops.js:286:5)
[start-api]     at connectCallback (D:\cestore\CeStore-1.3.0\Source\web\node_modules\mongodb\lib\operations\mongo_client_ops.js:241:5)
[start-api]     at process.nextTick (D:\cestore\CeStore-1.3.0\Source\web\node_modules\mongodb\lib\operations\mongo_client_ops.js:463:7) {"error":{"driver":true,"name":"MongoError"},"stack":"MongoError: database name must be a string\n    at Function.create (D:\\cestore\\CeStore-1.3.0\\Source\\web\\node_modules\\mongodb-core\\lib\\error.js:43:12)\n    at validateDatabaseName (D:\\cestore\\CeStore-1.3.0\\Source\\web\\node_modules\\mongodb\\lib\\operations\\db_ops.js:696:22)\n    at new Db (D:\\cestore\\CeStore-1.3.0\\Source\\web\\node_modules\\mongodb\\lib\\db.js:180:3)\n    at MongoClient.db (D:\\cestore\\CeStore-1.3.0\\Source\\web\\node_modules\\mongodb\\lib\\mongo_client.js:268:14)\n    at MongoClient.connect (D:\\cestore\\CeStore-1.3.0\\Source\\web\\src\\api\\server\\lib\\mongo.js:39:25)\n
at result (D:\\cestore\\CeStore-1.3.0\\Source\\web\\node_modules\\mongodb\\lib\\utils.js:414:17)\n    at executeCallback (D:\\cestore\\CeStore-1.3.0\\Source\\web\\node_modules\\mongodb\\lib\\utils.js:406:9)\n    at err (D:\\cestore\\CeStore-1.3.0\\Source\\web\\node_modules\\mongodb\\lib\\operations\\mongo_client_ops.js:286:5)\n    at connectCallback (D:\\cestore\\CeStore-1.3.0\\Source\\web\\node_modules\\mongodb\\lib\\operations\\mongo_client_ops.js:241:5)\n    at process.nextTick (D:\\cestore\\CeStore-1.3.0\\Source\\web\\node_modules\\mongodb\\lib\\operations\\mongo_client_ops.js:463:7)","exception":true,"date":"Mon May 13 2019 16:26:17 GMT+0700 (SE Asia Standard Time)","process":{"pid":828,"uid":null,"gid":null,"cwd":"D:\\cestore\\CeStore-1.3.0\\Source\\web","execPath":"C:\\Program Files\\nodejs\\node.exe","version":"v8.11.4","argv":["C:\\Program Files\\nodejs\\node.exe","D:\\cestore\\CeStore-1.3.0\\Source\\web\\src\\api\\server\\index.js"],"memoryUsage":{"rss":147476480,"heapTotal":119558144,"heapUsed":99116192,"external":23246836}},"os":{"loadavg":[0,0,0],"uptime":6867.8113494},"trace":[{"column":12,"file":"D:\\cestore\\CeStore-1.3.0\\Source\\web\\node_modules\\mongodb-core\\lib\\error.js","function":"Function.create","line":43,"method":"create","native":false},{"column":22,"file":"D:\\cestore\\CeStore-1.3.0\\Source\\web\\node_modules\\mongodb\\lib\\operations\\db_ops.js","function":"validateDatabaseName","line":696,"method":null,"native":false},{"column":3,"file":"D:\\cestore\\CeStore-1.3.0\\Source\\web\\node_modules\\mongodb\\lib\\db.js","function":"new Db","line":180,"method":null,"native":false},{"column":14,"file":"D:\\cestore\\CeStore-1.3.0\\Source\\web\\node_modules\\mongodb\\lib\\mongo_client.js","function":"MongoClient.db","line":268,"method":"db","native":false},{"column":25,"file":"D:\\cestore\\CeStore-1.3.0\\Source\\web\\src\\api\\server\\lib\\mongo.js","function":"MongoClient.connect","line":39,"method":"connect","native":false},{"column":17,"file":"D:\\cestore\\CeStore-1.3.0\\Source\\web\\node_modules\\mongodb\\lib\\utils.js","function":"result","line":414,"method":null,"native":false},{"column":9,"file":"D:\\cestore\\CeStore-1.3.0\\Source\\web\\node_modules\\mongodb\\lib\\utils.js","function":"executeCallback","line":406,"method":null,"native":false},{"column":5,"file":"D:\\cestore\\CeStore-1.3.0\\Source\\web\\node_modules\\mongodb\\lib\\operations\\mongo_client_ops.js","function":"err","line":286,"method":null,"native":false},{"column":5,"file":"D:\\cestore\\CeStore-1.3.0\\Source\\web\\node_modules\\mongodb\\lib\\operations\\mongo_client_ops.js","function":"connectCallback","line":241,"method":null,"native":false},{"column":7,"file":"D:\\cestore\\CeStore-1.3.0\\Source\\web\\node_modules\\mongodb\\lib\\operations\\mongo_client_ops.js","function":"process.nextTick","line":463,"method":"nextTick","native":false}]}[start-api] npm ERR! code ELIFECYCLE[start-api] npm ERR! errno 1[start-api] npm ERR! cezerin@0.33.0 start-api: `node -r esm src/api/server/index.js`
[start-api] npm ERR! Exit status 1
[start-api] npm ERR![start-api] npm ERR! Failed at the cezerin@0.33.0 start-api script.[start-api] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[start-api]
[start-api] npm ERR! A complete log of this run can be found in:[start-api] npm ERR!     C:\Users\s3665959\AppData\Roaming\npm-cache\_logs\2019-05-13T09_26_17_552Z-debug.log
[start-api] npm run start-api exited with code 1
[start-store] error: Error on page rendering[start-store]   path: /[start-store]   error: FetchError: request to http://localhost:3001/api/v1/sitemap?enabled=true&path=%2F failed, reason: connect ECONNREFUSED 127.0.0.1:3001[start-store] error: FetchError: request to http://localhost:3001/api/v1/sitemap?enabled=true&path=%2F
failed, reason: connect ECONNREFUSED 127.0.0.1:3001
[start-store]     at ClientRequest.<anonymous> (D:\cestore\CeStore-1.3.0\Source\web\node_modules\cross-fetch\node_modules\node-fetch\lib\index.js:1393:11)
[start-store]     at emitOne (events.js:116:13)
[start-store]     at ClientRequest.emit (events.js:211:7)
[start-store]     at Socket.socketErrorListener (_http_client.js:387:9)
[start-store]     at emitOne (events.js:116:13)
[start-store]     at Socket.emit (events.js:211:7)
[start-store]     at emitErrorNT (internal/streams/destroy.js:64:8)
[start-store]     at _combinedTickCallback (internal/process/next_tick.js:138:11)
[start-store]     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
[start-store] (node:7532) UnhandledPromiseRejectionWarning: FetchError: request to http://localhost:3001/api/v1/settings? failed, reason: connect ECONNREFUSED 127.0.0.1:3001
[start-store]     at ClientRequest.<anonymous> (D:\cestore\CeStore-1.3.0\Source\web\node_modules\cross-fetch\node_modules\node-fetch\lib\index.js:1393:11)
[start-store]     at emitOne (events.js:116:13)
[start-store]     at ClientRequest.emit (events.js:211:7)
[start-store]     at Socket.socketErrorListener (_http_client.js:387:9)
[start-store]     at emitOne (events.js:116:13)
[start-store]     at Socket.emit (events.js:211:7)
[start-store]     at emitErrorNT (internal/streams/destroy.js:64:8)
[start-store]     at _combinedTickCallback (internal/process/next_tick.js:138:11)
[start-store]     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
[start-store] (node:7532) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[start-store] (node:7532) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[start-store] error: Error on page rendering
[start-store]   path: /
[start-store]   error: FetchError: request to http://localhost:3001/api/v1/sitemap?enabled=true&path=%2F failed, reason: connect ECONNREFUSED 127.0.0.1:3001
[start-store] error: FetchError: request to http://localhost:3001/api/v1/sitemap?enabled=true&path=%2F
failed, reason: connect ECONNREFUSED 127.0.0.1:3001
[start-store]     at ClientRequest.<anonymous> (D:\cestore\CeStore-1.3.0\Source\web\node_modules\cross-fetch\node_modules\node-fetch\lib\index.js:1393:11)
[start-store]     at emitOne (events.js:116:13)
[start-store]     at ClientRequest.emit (events.js:211:7)
[start-store]     at Socket.socketErrorListener (_http_client.js:387:9)
[start-store]     at emitOne (events.js:116:13)
[start-store]     at Socket.emit (events.js:211:7)
[start-store]     at emitErrorNT (internal/streams/destroy.js:64:8)
[start-store]     at _combinedTickCallback (internal/process/next_tick.js:138:11)
[start-store]     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
[start-store] error: Error on page rendering
[start-store]   path: /
[start-store]   error: FetchError: request to http://localhost:3001/api/v1/theme/placeholders? failed,
reason: connect ECONNREFUSED 127.0.0.1:3001
[start-store] error: FetchError: request to http://localhost:3001/api/v1/theme/placeholders? failed, reason: connect ECONNREFUSED 127.0.0.1:3001
[start-store]     at ClientRequest.<anonymous> (D:\cestore\CeStore-1.3.0\Source\web\node_modules\cross-fetch\node_modules\node-fetch\lib\index.js:1393:11)
[start-store]     at emitOne (events.js:116:13)
[start-store]     at ClientRequest.emit (events.js:211:7)
[start-store]     at Socket.socketErrorListener (_http_client.js:387:9)
[start-store]     at emitOne (events.js:116:13)
[start-store]     at Socket.emit (events.js:211:7)
[start-store]     at emitErrorNT (internal/streams/destroy.js:64:8)
[start-store]     at _combinedTickCallback (internal/process/next_tick.js:138:11)
[start-store]     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
[start-store] (node:7532) UnhandledPromiseRejectionWarning: FetchError: request to http://localhost:3001/api/v1/settings? failed, reason: connect ECONNREFUSED 127.0.0.1:3001
[start-store]     at ClientRequest.<anonymous> (D:\cestore\CeStore-1.3.0\Source\web\node_modules\cross-fetch\node_modules\node-fetch\lib\index.js:1393:11)
[start-store]     at emitOne (events.js:116:13)
[start-store]     at ClientRequest.emit (events.js:211:7)
[start-store]     at Socket.socketErrorListener (_http_client.js:387:9)
[start-store]     at emitOne (events.js:116:13)
[start-store]     at Socket.emit (events.js:211:7)
[start-store]     at emitErrorNT (internal/streams/destroy.js:64:8)
[start-store]     at _combinedTickCallback (internal/process/next_tick.js:138:11)
[start-store]     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
[start-store] (node:7532) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing insideof an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)`

**Comment by s3665959** [comment]
when i go to localhost:3000 
i got this message 
request to http://localhost:3001/api/v1/sitemap?enabled=true&path=%2F failed, reason: connect ECONNREFUSED 127.0.0.1:3001

**Comment by s3665959** [comment]
help, please !!!

**Comment by s3665959** [comment]
can you please teamviewer and fix it 
thank you

**Comment by minhcasi** [comment]
Hi, pls add this skype: minhtruong315 - we will help to support from 9am-4pm GMT+7 - thank you!

**Comment by minhtruong315** [comment]
done
