### ISSUE TITLE
[MStore Pro] Cant start android

### ISSUE THREAD

**Issue by naldekhel** [inspireui/support#582]
- Product: [MStore pro]
 - Your Purchased Code: e5717440-ab94-463d-88b1-54f99f460276

**Describe the issues**
I cant run and start android, it shows this error:

### **Please look at this video:**
https://www.dropbox.com/s/uiiye1z4lqu6h1l/2019-05-13%2019-39-48.mp4?dl=0

###############################################
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

info Starting JS server...
info Building and installing the app on the device (cd android && gradlew.bat app:installDebug)...

> Configure project :react-native-webview
:react-native-webview:reactNativeAndroidRoot C:\Users\Najm\Desktop\MstoreApp\mstore-pro\node_modules\react-native\android

> Configure project :react-native-onesignal
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
WARNING: Configuration 'testCompile' is obsolete and has been replaced with 'testImplementation'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

> Configure project :react-native-admob
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

> Task :app:compileDebugJavaWithJavac FAILED
C:\Users\Najm\Desktop\MstoreApp\mstore-pro\android\app\src\main\java\com\dukhanstore\app\MainActivity.java:23: error: cannot find symbol
        MainApplication.getCallbackManager().onActivityResult(requestCode, resultCode, data);
        ^
  symbol:   variable MainApplication
  location: class MainActivity
C:\Users\Najm\Desktop\MstoreApp\mstore-pro\android\app\src\main\java\com\dukhanstore\app\MainApplication.java:35: error: cannot find symbol
      return BuildConfig.DEBUG;
             ^
  symbol: variable BuildConfig
C:\Users\Najm\Desktop\MstoreApp\mstore-pro\android\app\src\main\java\com\dukhanstore\app\SplashActivity.java:11: error: cannot find symbol
            Intent intent = new Intent(SplashActivity.this, MainActivity.class);
                                                            ^
  symbol:   class MainActivity
  location: class SplashActivity
Note: C:\Users\Najm\Desktop\MstoreApp\mstore-pro\android\app\src\main\java\com\dukhanstore\app\MainApplication.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
3 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 8s
113 actionable tasks: 1 executed, 112 up-to-date
error Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html
error Command failed: gradlew.bat app:installDebug

**Comment by minhcasi** [comment]
Hi, this is the issue when you change the package name - pls follow this guide - https://docs.inspireui.com/mstore/delivery/

**Comment by naldekhel** [comment]
Hi,
I already did this and did my own keys and packages name.

I changed my mind am going to use the expo version.

But am facing 1 issue.

My website is using wpml. The main language is English and I have Arabic. I have configured the app to Arabic, and did rtl and all translation. The only issue I have is the products names are still in English, how can I make the app fetch the products in Arabic?

I tried https://mywebsite.com/?lang=ar but it wouldn’t connect to the app.

Any suggestions?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by naldekhel** [comment]
Never mind, it fetched all in Arabic. It was cache problem. 

Thanks

**Comment by naldekhel** [comment]
Never mind, it fetched all in Arabic. It was cache problem. 

Thanks
