### ISSUE TITLE
[ListApp] Icons

### ISSUE THREAD

**Issue by bobozd** [inspireui/support#583]
Hi,

I would like to add icons or images similar to your CategoryIcons component with code bellow
{
    component: categoryIcons,
    column: 4,
  },

BUT I want it as a ad place for our sponsors, so I want it as logo images with external link to thier webpages. How can I achieve this?

thanks.

![theme4](https://user-images.githubusercontent.com/28021993/57690465-feb90180-7641-11e9-981a-2f3404ec1c12.png)

**Comment by thangvo9x** [comment]
Hi. You can edit it Container/Home/CategoryIcons
Thanks

**Comment by bobozd** [comment]
so how can I change icon images and point to different URL address (websites of our sponsors) afte clicking on it?

**Comment by thangvo9x** [comment]
Hi. Go to Container/Home/CategoryIcons/Item.js end edit it. Thanks

**Comment by bobozd** [comment]
hi, i'm not programer.
I need help how to edit this file.
please send me the code for one icon that points to specific URL address on
press. I'll do the same for other icons.

thanks.

pet, 17. svi 2019. 04:43 Tony Vo <notifications@github.com> je napisao:

**Comment by thangvo9x** [comment]
Hi, this is out of scope supporting our team. Thanks
