### ISSUE TITLE
[MStore] Checkout error

### ISSUE THREAD

**Issue by naldekhel** [inspireui/support#584]
- Product: [MStore expo version]
 - Your Purchased Code: e5717440-ab94-463d-88b1-54f99f460276

**Describe the bug**
I have a error at checkout. I have made a mstore-checout page and i have moved the mstore-checkout-template.php to theme and wordpress root and made the page set to mstore-checkout-template. But still not working. 

Am using MStore Expo 3.8

**Screenshots**
![check-out-error](https://user-images.githubusercontent.com/4033049/57739577-ce627900-76bc-11e9-8998-f9db8ccd3663.png)

[Config.zip](https://github.com/inspireui/support/files/3180336/Config.zip)

**Comment by naldekhel** [comment]
Any solution to this?

**Comment by minhcasi** [comment]
Hi, could you help to share your AppConfig.json as well - we will help for debugging this issue - thanks

**Comment by naldekhel** [comment]
Attached
[AppConfig.zip](https://github.com/inspireui/support/files/3187048/AppConfig.zip)

**Comment by naldekhel** [comment]
Still no solution my friend.

**Comment by minhcasi** [comment]
can . you include the common/config.js as well?

Try to note your all issues to once ticket that help us focus on your issues? 

Closed as duplicate with #599 - we will response on this ticket - thanks
