### ISSUE TITLE
[cestore] cannot change or save anything at setting page

### ISSUE THREAD

**Issue by s3665959** [inspireui/support#585]
Product: [cestore]
Item Purchase Code:
43fdac4f-37a3-4414-9687-c850d0******

i cannot change or save any setting in http://localhost:3000/admin
also cannot add any product. 

help please 
thank you

**Comment by s3665959** [comment]
below is the console error :  
:3001/api/v1/settings?:1 Failed to load resource: the server responded with a status of 401 (Unauthorized)
smtp:1 Access to XMLHttpRequest at 'http://localhost:3001/api/v1/settings?' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
2:3001/api/v1/settings/email?:1 Failed to load resource: the server responded with a status of 401 (Unauthorized)
smtp:1 Access to XMLHttpRequest at 'http://localhost:3001/api/v1/settings/email?' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
content.js:5 --------init----------- http://localhost:3000/admin/settings/email/smtp
2:3001/api/v1/settings/email:1 Failed to load resource: the server responded with a status of 401 (Unauthorized)
smtp:1 Access to XMLHttpRequest at 'http://localhost:3001/api/v1/settings/email' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
2:3001/api/v1/settings/email:1 Failed to load resource: the server responded with a status of 401 (Unauthorized)
smtp:1 Access to XMLHttpRequest at 'http://localhost:3001/api/v1/settings/email' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
2:3001/api/v1/settings/email:1 Failed to load resource: the server responded with a status of 401 (Unauthorized)
smtp:1 Access to XMLHttpRequest at 'http://localhost:3001/api/v1/settings/email' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
2:3001/api/v1/settings/email?:1 Failed to load resource: the server responded with a status of 401 (Unauthorized)
:3000/admin/settings/email:1 Access to XMLHttpRequest at 'http://localhost:3001/api/v1/settings/email?' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
2:3001/api/v1/settings/email?:1 Failed to load resource: the server responded with a status of 401 (Unauthorized)
smtp:1 Access to XMLHttpRequest at 'http://localhost:3001/api/v1/settings/email?' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
app-7c4559d5a8153882bd5a.js:1 WebSocket connection to 'ws://localhost:3001/ws/dashboard?token=null' failed: WebSocket opening handshake timed out
u @ app-7c4559d5a8153882bd5a.js:1
app-7c4559d5a8153882bd5a.js:1 WebSocket connection closed with code: 1006.
app-7c4559d5a8153882bd5a.js:1 WebSocket connection to 'ws://localhost:3001/ws/dashboard?token=null' failed: WebSocket opening handshake timed out
u @ app-7c4559d5a8153882bd5a.js:1
app-7c4559d5a8153882bd5a.js:1 WebSocket connection closed with code: 1006.
app-7c4559d5a8153882bd5a.js:1 WebSocket connection to 'ws://localhost:3001/ws/dashboard?token=null' failed: WebSocket opening handshake timed out

**Comment by minhtruong315** [comment]
done
