### ISSUE TITLE
[ Cestore ] having problem with changing the header menu and logo

### ISSUE THREAD

**Issue by s3665959** [inspireui/support#586]
**Mandatory Info (please complete the following information):**
Product: [cestore]
Item Purchase Code:
43fdac4f-37a3-4414-9687-c850d0******

1. i am having problem with changing the header menu and logo.
i have tried to change the logo from http://localhost:3000/admin/settings/theme

![1557905473779](https://user-images.githubusercontent.com/42608262/57792662-bd237600-7769-11e9-8a70-f0817fc1cb90.jpg)

Also i have try to change the name in  theme/src/components/header/index.js
but nothing change, logo still show "cestore"

![image](https://user-images.githubusercontent.com/42608262/57792776-070c5c00-776a-11e9-9ba5-58489936631f.png)

2. how can i add more or change categories menu on the top left 
![image](https://user-images.githubusercontent.com/42608262/57793079-b0535200-776a-11e9-8fe0-12b39a1a8d91.png)

3. i have looked at the cezerin2 demo site they have a dropdown menu , also the hamburger menu. how can i add that into your Cestore 
![image](https://user-images.githubusercontent.com/42608262/57793453-8f3f3100-776b-11e9-835f-7c4f49274ea5.png)

![image](https://user-images.githubusercontent.com/42608262/57793474-99612f80-776b-11e9-8686-68473d49a5f9.png)

thank you.

**Comment by minhtruong315** [comment]
when you edit theme. You need to run "npm run theme:build" then run "npm start" again
