### ISSUE TITLE
M Store Pro Shipping Charges Wave Off after certain amount of cart value.

### ISSUE THREAD

**Issue by Relimer-Technologies** [inspireui/support#587]
Mandatory Info (please complete the following information):

Product: [e.g. MStore, ListApp]
M Store Pro
Purchase Code: d98eb201-aba4-4c76-a0a1-cbd67415737d
Your Purchased Code: [get from https://codecanyon.net/downloads]
(we may not reply if you are not our customer)
Describe the issues
Hello,

Good Morning, I have purchased M Store Pro from Envato. I have done all the setup required... I have installed all of the required tools... I have a basic request for shipping charges... I have assigned Flat Rate as 450 and Free Shipping as 0 with the condition of Total amount to be greater than or equal to 25000... I am able to get both the shipping options during checkout but
the condition for Free Shipping is not fulfilled... I need the customer to avail free shipping only if they do 25000 or above value shopping but in the app, both the shipping are shown for any value of the cart.

Kindly help me out with this... Thank You

**Comment by Relimer-Technologies** [comment]
I have already registered this issue in the following link below

https://github.com/inspireui/support/issues/567

I am unable to find the ShouldComponentUpdate function in Delivery Component (inside the Cart)

Kindly help me out with this.

Thank You

**Comment by naldekhel** [comment]
+1

**Comment by minhcasi** [comment]
Hi, this is example code that you can refer - https://tppr.me/1ledU 
File: container/Cart/Delivery/index.js

Sorry, as this feature is quite specific that not include from the support license so that we could give a solution to fix it, this is not a bug from the product.
- thanks

**Comment by naldekhel** [comment]
We know its not a bug, and we appreciate your help, but this is a very very important feature to have in the app. 

I did exactly like your code my friend. But free shipping still shows at the checkout

**Comment by Relimer-Technologies** [comment]
Hello, @minhcasi  I have tried your given solution. But it didn't work out. The Free Shipping is still displayed at the checkout. Please provide with the alternate solution as soon as possible. Thank You
