### ISSUE TITLE
[CeBuilder] unable to test app

### ISSUE THREAD

**Issue by anwark** [inspireui/support#588]
**Mandatory Info (please complete the following information):**
 - Product: ListPro
 - Your Purchased Code: ae03d146-d1ca-4017-85e6-98303d17fb33

**Describe the issues**
unable to run the build from CI builder 

**Screenshots**
https://www.screencast.com/t/ibve2hapxc

**Additional context**
Please help to run the build

**Comment by minhcasi** [comment]
Hi, could you try to update the latest Cebuilder 0.34 from this link - https://github.com/inspireui/cebuilder/releases

Then extract the Listpro package on C: hard drive and reinstall again 

Let us know your checking - thanks

**Comment by anwark** [comment]
I followed your instruction having this issue 
![choco](https://user-images.githubusercontent.com/109449/57894725-8c286b80-7865-11e9-8fb5-3d0fe7fc53fb.png)

**Comment by minhtruong315** [comment]
Can you add my skype: minhtruong315. I will help you check it via teamviewer

**Comment by minhtruong315** [comment]
Done

**Comment by anwark** [comment]
Thanks for your help

**Comment by minhcasi** [comment]
@anwark - let us know if you have any further question, please also help us to give the good rating & feedback to - https://codecanyon.net/downloads - appreciated for your help 👍
