### ISSUE TITLE
[ListApp] app does not connect with reactotron

### ISSUE THREAD

**Issue by Jeison12** [inspireui/support#59]
Product: ListApp
My Purchased Code: ccded53c-5f90-41ff-8c6a-fac4faae1017

app does not connect with reactotron

![captura de pantalla de 2018-11-27 22-55-17](https://user-images.githubusercontent.com/26725495/49128052-ce4df880-f297-11e8-8f3e-9bde7307b87b.png)

**Comment by thangvo9x** [comment]
You try switch to Development Mode ? such as in useReactotron : true in Constants.js
Thanks

**Comment by Jeison12** [comment]
useReactotron : true, debug: true, in the developer mode I choose the Debug JS Remotely option

When I start reactotron in the console it appears
![captura de pantalla de 2018-11-28 08-24-03](https://user-images.githubusercontent.com/26725495/49154906-a25a6380-f2e7-11e8-83df-e54e306eb6c9.png)

**Comment by Jeison12** [comment]
change the host and it worked
