### ISSUE TITLE
[MStore] Edit Featured product panel

### ISSUE THREAD

**Issue by sashaba** [inspireui/support#590]
Product: MStore Pro
Your Purchased Code:4bb2fd9b-4a08-4e19-9c74-fc95f51533e7

Hello support
Would you please help me out here. I’m trying to edit the size of the image container in the “Featured products”panel. 
Is the screen we go after we hit “see More” at home layout.

Please see image below.

Thank you
![DBA28EEF-63AB-4563-8516-EC064D9D76C3](https://user-images.githubusercontent.com/40736543/57873239-a1f14e80-77db-11e9-85b3-abb219271700.jpeg)

**Comment by sashaba** [comment]
![47FAB90C-41A6-47CF-80DD-C2415A1BEEF0](https://user-images.githubusercontent.com/40736543/57874641-0b269100-77df-11e9-9e81-c3c072dc8148.gif)

**Comment by sashaba** [comment]
![4CE9E039-C33C-4868-BDBE-55C8EDF31595](https://user-images.githubusercontent.com/40736543/57874774-5fca0c00-77df-11e9-81bf-5dfa05ae06df.gif)

**Comment by minhcasi** [comment]
Hi, pls edit the image style from Component/HorizonLayout/** 
Example: the file TwoColumn.js is for the 2 columns layout 

https://medium.com/@inspireui/new-mstore-3-8-with-sms-login-and-affiliate-support-4a97139e792f

**Comment by sashaba** [comment]
Hello @minhcasi 
Thank you. I will edit the file.
Thanks.
