### ISSUE TITLE
[Mstore] Promo active on website 

### ISSUE THREAD

**Issue by hakihosting** [inspireui/support#591]
Purchase code : ac9d522a-a783-4f9c-a882-7dc694488d5d

Hello , on website i have set a promo active 50 % so the final price of product is 15 € , normal price 30€

On the application the price is showing 30€  , normaly it must be 15 €

**Comment by minhcasi** [comment]
can you provide the detailed screenshot & config file 

⚠⚠⚠pls create one ticket for your all issue on next time, thanks
