### ISSUE TITLE
[Mstore Shopify] IOS & Android files not in download

### ISSUE THREAD

**Issue by zreaux** [inspireui/support#593]
**Mandatory Info (please complete the following information):**
 - Product: MStore
 - Your Purchased Code: 4fd19348-3592-452b-a100-8cb9dbd5f852

**Describe the issues**
When trying to install M store there was no ios files or android files

**Screenshots**
<img width="1440" alt="Screen Shot 2019-05-16 at 10 30 25 PM" src="https://user-images.githubusercontent.com/47990263/57899242-4bf7c780-782a-11e9-9179-8ccb2da5a09d.png">

**Additional context**

**Comment by minhcasi** [comment]
Hi, you can run via the Expo tools - https://expo.io/tools

Expo is the quick way to run the project as it will wrap the ios and android folder to Expo SDK for easy to maintain, you can still eject the product to ios and android by using expokit - https://docs.expo.io/versions/latest/expokit/eject/#__next
