### ISSUE TITLE
[MStore] RTL alignment and Arabic Search issue.

### ISSUE THREAD

**Issue by naldekhel** [inspireui/support#599]
Product: [MStore]
Your Purchased Code: e5717440-ab94-463d-88b1-54f99f460276

Hi there, 

There are so many bugs in the RTL and Arabic version, am going to devide it into 2 issues. 

### #1- The search in Arabic isn't working in the app. 
I tried searching in Arabic words and english, but its not working also. Please refer to this video:
https://www.dropbox.com/s/rxkoo1m7n1scpb4/search-issue.MP4?dl=0

### #2- There are a lot of RTL alignment that need to be adjusted. 
Please refer to the screenshots here:

A.
 ![1](https://user-images.githubusercontent.com/4033049/57968811-16f98b00-7978-11e9-819b-f46fda0059ef.png)

B. 
![2](https://user-images.githubusercontent.com/4033049/57968812-1fea5c80-7978-11e9-889c-077d69c22733.png)

C. 
![3](https://user-images.githubusercontent.com/4033049/57968815-25e03d80-7978-11e9-8318-af6a70f6bfb3.png)

D. 
![4](https://user-images.githubusercontent.com/4033049/57968816-2a0c5b00-7978-11e9-9391-a4ce14099711.png)

### These issues are in both versions Exp and Pro and both releases 3.7.2 and 3.8

Thanks

**Comment by minhcasi** [comment]
Noted for checking - thanks

Could you attach with your config file (AppConfig.json and common/index.js) file, please try to create one ticket for your all issue - thanks

**Comment by naldekhel** [comment]
[Config.zip](https://github.com/inspireui/support/files/3194946/Config.zip)
[Constants.zip](https://github.com/inspireui/support/files/3194947/Constants.zip)
[index.zip](https://github.com/inspireui/support/files/3194948/index.zip)
[AppConfig.zip](https://github.com/inspireui/support/files/3194949/AppConfig.zip)

**Comment by naldekhel** [comment]
### Order issue ( Oldest --> Newest ) on version 3.8:
https://www.dropbox.com/s/oyxuzwilb59ogn8/3.8%20Order%20is%20oldest%20to%20newest.mp4?dl=0

Then here you can see its showing **GOOD** in version 3.7.2 ( Newest --> Oldest ):
https://www.dropbox.com/s/yk8fzvuuckuas80/3.7.2%20Order%20is%20good.mp4?dl=0


### Here is the dark theme issue with version 3.8:
https://www.dropbox.com/s/9r2wklp3954it2a/3.8%20Dark%20theme%20issue.mp4?dl=0

**Comment by Brdnn** [comment]
I just check 3.8 also found out the product order is from oldest > newest instead of newest > oldest.

**Comment by naldekhel** [comment]
My friend still no solution for this #584 ??

**Comment by minhcasi** [comment]
@naldekhel - just confirm that there are no issues with the latest v3.8.x, please see the screenshot and video
- https://www.dropbox.com/s/cne7idvrgdj4206/screen.mov?dl=0
![Simulator Screen Shot - iPhone X - 2019-05-20 at 17 58 09](https://user-images.githubusercontent.com/1459805/58017580-c4140500-7b2a-11e9-8ed0-47b93afffb21.png)
![Simulator Screen Shot - iPhone X - 2019-05-20 at 17 58 25](https://user-images.githubusercontent.com/1459805/58017581-c4140500-7b2a-11e9-93e1-25cf392e5cb1.png)
![Simulator Screen Shot - iPhone X - 2019-05-20 at 17 59 27](https://user-images.githubusercontent.com/1459805/58017583-c4ac9b80-7b2a-11e9-8952-e759baa34273.png)
![Simulator Screen Shot - iPhone X - 2019-05-20 at 17 59 35](https://user-images.githubusercontent.com/1459805/58017584-c4ac9b80-7b2a-11e9-919b-bcb42c2500a0.png)

**Comment by naldekhel** [comment]
Thats weird! Could it be cache problem on my end? I mean my phone has saved the LTR setting and thats why its showing LTR but in RTL words? 

I will try to delete expo and download it again. 

Could you please take a look at the other issues, specially the checkout error! its very important!

**Comment by Brdnn** [comment]
Please help out the order bug oldest to newest instead of newest to oldest, I checked the constants.js is same with previous but not sure what cause this bug. Let me know if I can do a minor change to solve this issue. Thanks

**Comment by naldekhel** [comment]
no solution on the checkout error?

**Comment by minhcasi** [comment]
@naldekhel  you can use the reactotron to debug the return URL when process order - https://github.com/infinitered/reactotron/blob/master/docs/installing.md - there could be issue with your website config that cause the PHP exception from backend site - thanks

**Comment by naldekhel** [comment]
I couldn't understand how to install it or how to run it. Could you please explain to me.

**Comment by minhcasi** [comment]
just try to install and on your pc then it will be auto connect when run with the simulator (with debug mode) / screenshot - https://docs.inspireui.com/mstore/project-structure/#debug-app-with-reacttotron
