### ISSUE TITLE
[beonews] Android Build Error

### ISSUE THREAD

**Issue by mustafamsy** [inspireui/support#600]
Product: [BeoNews]
Your Purchased Code: 2a6e0632-d77f-4f7a-bb66-b1d5aa869ccd

I am getting the following error while building for Android

```
> Task :react-native-fbsdk:transformNativeLibsWithMergeJniLibsForRelease FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-fbsdk:transformNativeLibsWithMergeJniLibsForRelease'.
> java.io.EOFException
```

Build failed

**Comment by mustafamsy** [comment]
I have downloaded every single release with bugs every where. I have not been able to publish my apps. When will I be able to publish my apps to stores?! 
It is always no feedback or delayed feedbacks! and I've really lost my patience and I'm very disappointed with your support

**Comment by minhcasi** [comment]
Hi there, we will help to check the issue #596 and let you know, just note that it's not delay support as you have not provided enough information that we could help to check (missing URL website from your previous comment) - thanks

**Comment by minhcasi** [comment]
Hi, pls use latest Beonews 3.0.3 and try with following solution:
- remove the Android simulator and try with android 7->9
- go to android folder and run: ./gradlew clean   
- clean up the cache from root folder: watchman watch-del-all && react-native start --reset-cache

**Comment by mustafamsy** [comment]
Issue is resolved. Thanks
