### ISSUE TITLE
[Beonews] {Paid Edit Request} Modify PostDetail page

### ISSUE THREAD

**Issue by hadi13** [inspireui/support#601]
beonews app 
Item Purchase Code:
14cf2889-4560-4e19-98c2-5134c9e6d044

I want to modify the PostDetails page so it can load css also, and it loads same font color and size and all font features from wordpress post 
I will pay for this

**Comment by minhcasi** [comment]
could you share your website URL and some screenshot explain your idea, you can also send private to our email support@inspireui.com - thank you!
