### ISSUE TITLE
[Cestore] issue comming when accessing admin

### ISSUE THREAD

**Issue by nirajsavaliya94** [inspireui/support#603]
**Mandatory Info (please complete the following information):**
 - Product: [e.g. Cestore]
 - Your Purchased Code: [get from https://codecanyon.net/downloads]
dbe4de4f-01ca-4f96-a42f-fcd493be43de

**Additional context**
Access to XMLHttpRequest at 'http://localhost:3001/ajax/products?fields=path%2Cid%2Cname%2Ccategory_id%2Ccategory_name%2Csku%2Cimages%2Cenabled%2Cdiscontinued%2Cstock_status%2Cstock_quantity%2Cprice%2Con_sale%2Cregular_price%2Cattributes%2Ctags&limit=8&offset=0&search&sort=-date_updated' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.

**Comment by minhtruong315** [comment]
Hi @nirajsavaliya94 
You need to update something
in config/server.js, you have to set ```developerMode: true``` and ```storeBaseUrl: 'http://localhost:3000'```

**Comment by nirajsavaliya94** [comment]
It's only working fine for frontend.

when accessing http://localhost:3000/admin/ then getting below issue

(index):1 GET http://localhost:3001/api/v1/settings? 401 (Unauthorized)

Access to XMLHttpRequest at 'http://localhost:3001/api/v1/settings?' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
2(index):1 GET http://localhost:3001/api/v1/orders?cancelled=false&date_placed_min=2019-04-21T18%3A30%3A00.823Z&draft=false net::ERR_ABORTED 401 (Unauthorized)

WebSocket connection to 'ws://localhost:3001/ws/dashboard?token=null' failed: HTTP Authentication failed; no valid credentials available

**Comment by minhtruong315** [comment]
Hi @nirajsavaliya94 
in config/admin.js please set developerMode: true, you can go to admin, then change domain to http://localhost:3000 or you can edit domain in mongodb as well

**Comment by ahmadyousefdev** [comment]
> Hi @nirajsavaliya94
> You need to update something
> in config/server.js, you have to set `developerMode: true` and `storeBaseUrl: 'http://localhost:3000'`
> Then run `npm run build` and `npm start`

This should be added to the documentation.
---
Also, the developerMode in admin config is true and I still get `WebSocket connection to 'ws://localhost:3001/ws/dashboard?token=null' failed: HTTP Authentication failed; no valid credentials available` .. What should I do?
