### ISSUE TITLE
ListApp documentation link is broken

### ISSUE THREAD

**Issue by bfwi410a** [inspireui/support#604]
Dear support,
a few minutes ago i bought Listapp via CodeCanyon. The link for documentation and Ticket (https://docs.inspireui.com/listapp) does not work. Could you fix please?

Thx

![2019-05-19 14_25_55-Window](https://user-images.githubusercontent.com/1284361/57982169-14fbfe80-7a42-11e9-9154-a775b73a9cdb.png)

**Comment by thangvo9x** [comment]
Hi. @bfwi410a. We have got a hotfix for our document guide.
https://docs.inspireui.com/listapp/
Thanks
