### ISSUE TITLE
[MStore Opencart] Not Able to install via CeBuilder

### ISSUE THREAD

**Issue by trippynash** [inspireui/support#607]
- Product: Mstore Opencart
 - Your Purchased Code: 7da68b74-471e-46fa-b79a-134d254f9ec4
(we may not reply if you are not our customer)

While installing the App via CeBuilder, appconfig asks for secret Key as in the snapshot. i could not find any secret key for the API that I've installed in my Opencart 

![image](https://user-images.githubusercontent.com/46844686/58016855-64aef880-7b1c-11e9-95d2-2c9d778a669e.png)

Please help me with the secret Key.

**Comment by minhcasi** [comment]
Hi, pls make sure to open this folder - https://tppr.me/uKjkF - the folder that content the package.json

**Comment by trippynash** [comment]
I've opened the right folder as mentioned. I've checked the app config.js in which the only thing mentioned is the website name and there's no option for secret key in that. I'd be grateful if you could tell me where i can get the secret key. 

Is there any possibility of screen sharing. which would be great.

**Comment by minhtruong315** [comment]
Hi @trippynash I am updating CeBuilder, will send you update soon.

**Comment by trippynash** [comment]
Please update the CeBuilder as i need to deliver the demo to the client.

**Comment by minhcasi** [comment]
https://github.com/inspireui/cebuilder/releases - pls download latest 0.35 from this link

**Comment by trippynash** [comment]
Thanks for the help. Now it worked properly. I've to implement couple of modifications that is needed to be done in the app. 
Can you let me know where exactly the API calls are included. and if i need to make some other module then where are i need to add those pages.

**Comment by minhcasi** [comment]
Hi the API call are located from the services folder

Other modification can be custom from components and containers folder 

Thank you!
