### ISSUE TITLE
[ListApp] General question for xcode and android package

### ISSUE THREAD

**Issue by bfwi410a** [inspireui/support#609]
- Product: ListApp
 - Your Purchased Code: i don't want write public (if necessary, I send the purchased code by mail)
 - Want use your App with Listable

I tried to install CEBuilder on my MacBook Air. After login with purchased code first i setup project folder. Second i install required plugins. Homebrew OK, NodeJS OK, Yarn OK, but Expo install does not work. I install with "sudo su" but nevertheless setup had permission problems. I watched your videos but I will not be smart about that. This is a mix of different apps (ListApp, ProList App, MStore...) No video describe how to install development environment from scratch. When I bought the app, I figured I would buy a Xcode Project and an Android Project. Is there a way to get a finished xcode and android project which i can customize in xcode (for iOS) and Eclipse for android? If you do that as an additional service, i will pay for it.

Hope you can help.

**Comment by minhcasi** [comment]
Hi, just note that we will add the cli version with include both (ios and android folder) on next version release - thanks

**Comment by bfwi410a** [comment]
Ok, thx. Can you estimate when new version will be released?
