### ISSUE TITLE
[BeoNews] iOS App rejected from App Store

### ISSUE THREAD

**Issue by raulliubo** [inspireui/support#61]
Hello, I was able to build and upload my iOS App using your template. But the App got rejected. The violated guidelines are
Guideline 2.1 – Information Needed and 
Guideline 4.2 – Design – Minimum Functionality. 

In Guideline 2.1 there is one point: 4.3.0 – Are a duplicate of another app or are conspicuously similar to another app.

Is this because I’ve changed too little of the template code? How can I resolve this? Has anyone else also had this problem before? What should I do for Minimum Functionlity?

Thanks for any advice!

**Comment by minhcasi** [comment]
Hi the common problem is your app content, please make sure you update the data completely, image full resolution...

You can try to add my account to TestFlight for the review - minh@inspireui.com

Thank you!

**Comment by raulliubo** [comment]
Hi thanks for the reply. I've added you to my TestFlight. 
Any advice would be appreciated. Thanks!

**Comment by minhcasi** [comment]
Hi, my quick review of your custom app has the following issue:
- low feature image resolutions
- some text is not formatted correctly and mistyping
- blank category image
- Try to add more Banner to the homepage as it looks empty

![img_0788](https://user-images.githubusercontent.com/1459805/49214714-cc03af80-f3f9-11e8-94ab-8ec9c4d29a9d.PNG)
![img_0790](https://user-images.githubusercontent.com/1459805/49214715-cc9c4600-f3f9-11e8-8559-268d1460948a.PNG)
![img_0791](https://user-images.githubusercontent.com/1459805/49214716-cc9c4600-f3f9-11e8-877f-b1b7525fb0c6.PNG)
![img_0792](https://user-images.githubusercontent.com/1459805/49214717-cd34dc80-f3f9-11e8-8a8c-ccc5702e8057.PNG)

**Comment by raulliubo** [comment]
Thanks for the tips! I'll work on that!
