### ISSUE TITLE
project wont load via CeBuilder

### ISSUE THREAD

**Issue by aidan123A** [inspireui/support#610]
**Required Info (please complete the following information):**
 - Product: [e.g. CeBuilder v0.34.0  ListApp
 - Your Purchased Code: 84fdc19e-df1a-42c1-a55d-d7031f061413

**Describe the bug**
Open ceBuilder 
Observe update message displays then application opens 
Select set up
open project folder and select  source file: /Users/aidan/Desktop/ListApp 1.7.1/source
Observe the spinner keeps spinning and the project folder will **not** load 
**Screenshots**
<img width="428" alt="Screenshot 2019-05-20 at 20 36 28" src="https://user-images.githubusercontent.com/50780463/58047234-92f1ff80-7b3f-11e9-89f3-25a2e21d5dfc.png">

<img width="1026" alt="Screenshot 2019-05-20 at 20 38 21" src="https://user-images.githubusercontent.com/50780463/58047239-971e1d00-7b3f-11e9-8df6-e7c4bf72a506.png">

**Additional context**
Add any other detail logs about the problem here.
If possible please share your config.js that use for the app setting

**Comment by minhcasi** [comment]
Noted for checking, thank you!

**Comment by minhcasi** [comment]
Hi, please update to latest 0.35 to fix this issue - https://github.com/inspireui/cebuilder/releases - thank you!

**Comment by aidan123A** [comment]
Hi, I tried updating to 0.35 and it did not work

**Comment by aidan123A** [comment]
Please reopen the ticket

**Comment by minhcasi** [comment]
@minhtruong315  - pls help for this supporting - thank you!

**Comment by minhcasi** [comment]
@aidan123A  - are you still having this issue ?  https://user-images.githubusercontent.com/50780463/58047239-971e1d00-7b3f-11e9-8df6-e7c4bf72a506.png

**Comment by aidan123A** [comment]
@minhcasi  - yes i am

**Comment by minhcasi** [comment]
pls help to add skype: minhtruong315 - he will help to resolve this issue - thank you!

**Comment by aidan123A** [comment]
hi @minhcasi, i tried using skype and teamviewer with @minhtruong315  he was not able to solve the issue. please refund me

**Comment by minhtruong315** [comment]
You need to install android emulators. Then start it. and check it is available in adb. Then ping me
