### ISSUE TITLE
[Mstore expo] - All Image are not visible

### ISSUE THREAD

**Issue by santhosh2210** [inspireui/support#611]
- Product: [ MStore ]
Home page and categories image are visible to my app....i finished to all requirement plugins and appconfig.js....but still not visible to image...please help this bug... thank you
See the screenshot : 
![01 (1)](https://user-images.githubusercontent.com/32481586/58074660-6d0e3e80-7bc3-11e9-9f6e-9b98552c2667.jpeg)
![01 (2)](https://user-images.githubusercontent.com/32481586/58074661-6d0e3e80-7bc3-11e9-9fae-d914256facca.jpeg)

Config.js file 👍 
[common.zip](https://github.com/inspireui/support/files/3201160/common.zip)

**Comment by minhcasi** [comment]
HI, pls check the product display size config from - https://docs.inspireui.com/mstore/woo-setting/ - thanks

**Comment by santhosh2210** [comment]
Thank you
