### ISSUE TITLE
Still to fix in the version of 3.8.0

### ISSUE THREAD

**Issue by hakihosting** [inspireui/support#612]
Purchase code : ac9d522a-a783-4f9c-a882-7dc694488d5d

Hello i have installed the new version but i see , these errors still bug in the version : 3.8.0

 - When i insert a code promo in lower case it works ,but if i insert in Uppercase : CODE promo is invalid.

- Stock problem with variations synching
- MultiLanguage homepage not showing

**Comment by hakihosting** [comment]
![Simulator Screen Shot - iPhone XR - 2019-05-21 at 13 45 05](https://user-images.githubusercontent.com/47614045/58093406-bfa12800-7bce-11e9-8a26-ed60a0d8049c.png)

SMS LOGIN : fault

**Comment by minhcasi** [comment]
Hi, we could not replicate as the above issues, please try to explain as more detail with screenshot as possible.

The red screen issue could not reproduce as well, it looks like you have changed something that casue the broken - thanks

**Comment by hakihosting** [comment]
I JUST change de token client

**Comment by hakihosting** [comment]
I have found where is the problem
