### ISSUE TITLE
[MStore Pro] Negative stock on products with variation still not working in 3.8 version

### ISSUE THREAD

**Issue by IvoKalu** [inspireui/support#613]
**Required Info (please complete the following information):**
 - Product: [MStore Pro]
 - Your Purchased Code: [41384711-598d-400d-9b04-1b414a388036 ]

**Describe the bug**
We have been asking for a fix for the out of stock for variation for a while now. When I have a product with variation if one variation is out of stock my clients can still buy it from the store making the stock go negative even if you don’t allow back-order.
I followed all other gitub reports for fix but still not fixed.

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/8544219/58077596-cadf5e00-7ba4-11e9-87f0-f04471ab5db8.jpg)

**Additional context**
Add any other detail logs about the problem here.
If possible please share your config.js that use for the app setting

**Comment by minhcasi** [comment]
Could you attach your config files here (the files are located at common/config.js and common/appConfig.json) - thank you!

**Comment by IvoKalu** [comment]
Config.js
/** @format */

import Images from "./Images";
import Constants from "./Constants";
import Icons from "./Icons";

export default {
  /**
   * Step 1: change to your website URL and the wooCommerce API consumeKey
   * Moved to AppConfig.json
   */

  /**
     Step 2: Setting Product Images
     - ProductSize: Explode the guide from: update the product display size: https://mstore.gitbooks.io/mstore-manual/content/chapter5.html
     The default config for ProductSize is disable due to some problem config for most of users.
     If you have success config it from the Wordpress site, please enable to speed up the app performance
     - HorizonLayout: Change the HomePage horizontal layout - https://mstore.gitbooks.io/mstore-manual/content/chapter6.html
       Update Oct 06 2018: add new type of categories
       NOTE: name is define value --> change field in Language.js
       Moved to AppConfig.json
     */
  ProductSize: {
    enable: true,
  },

  HomeCategories: [
    {
      category: 34,
      image: require("@images/categories_icon/ic_shorts.png"),
      colors: ["#4facfe", "#00f2fe"],
    },
    {
      category: 41,
      image: require("@images/categories_icon/ic_tshirt.png"),
      colors: ["#43e97b", "#38f9d7"],
    },
    {
      category: 30,
      image: require("@images/categories_icon/ic_panties.png"),
      colors: ["#fa709a", "#fee140"],
    }/*,
    {
      category: 26,
      image: require("@images/categories_icon/ic_dress.png"),
      colors: ["#7F00FF", "#E100FF"],
    },
    {
      category: 24,
      image: require("@images/categories_icon/ic_glasses.png"),
      colors: ["#30cfd0", "#330867"],
    },
    {
      category: 211,
      image: require("@images/categories_icon/ic_socks.png"),
      colors: ["#c471f5", "#fa71cd"],
    }*/,
    {
      category: 32,
      image: require("@images/categories_icon/ic_shoes.png"),
      colors: ["#2af598", "#009efd"],
    }/*,
    {
      category: 210,
      image: require("@images/categories_icon/ic_woman_shoes.png"),
      colors: ["#f43b47", "#453a94"],
    }*/,
  ],
  /**
     step 3: Config image for the Payment Gateway
     Notes:
     - Only the image list here will be shown on the app but it should match with the key id from the WooCommerce Website config
     - It's flexible way to control list of your payment as well
     Ex. if you would like to show only cod then just put one cod image in the list
     * */
  Payments: {
    cod: require("@images/payment_logo/delivery.jpg"),
    paypal: require("@images/payment_logo/PayPal.png"),
    stripe: require("@images/payment_logo/stripe.png"),
  },

  /**
     Step 4: Advance config:
     - showShipping: option to show the list of shipping method
     - showStatusBar: option to show the status bar, it always show iPhoneX
     - LogoImage: The header logo
     - LogoWithText: The Logo use for sign up form
     - LogoLoading: The loading icon logo
     - appFacebookId: The app facebook ID, use for Facebook login
     - CustomPages: Update the custom page which can be shown from the left side bar (Components/Drawer/index.js)
     - WebPages: This could be the id of your blog post or the full URL which point to any Webpage (responsive mobile is required on the web page)
     - intro: The on boarding intro slider for your app
     - menu: config for left menu side items (isMultiChild: This is new feature from 3.4.5 that show the sub products categories)
     * */
  shipping: {
    visible: true,
    zoneId: 5, // depend on your woocommerce
    time: {
      free_shipping: "24-48 Horas",
      flat_rate: "24-48 Horas",
      local_pickup: "Das 10 as 17",
    },
  },
  showStatusBar: true,
  LogoImage: require("@images/logo-mai.png"),
  LogoWithText: require("@images/logo_with_tex.png"),
  LogoLoading: require("@images/log.png"),

  showAdmobAds: false,
  AdMob: {
    deviceID: "pub-2101182411274198",
    rewarded: "ca-app-pub-2101182411274198/5096259336",
    interstitial: "ca-app-pub-2101182411274198/8930161243",
    banner: "ca-app-pub-2101182411274198/4100506392",
  },
  appFacebookId: "887727264907581",
  CustomPages: { contact_id: 10941 },
  WebPages: { marketing: "https://bueshopping.com" },

  intro: [
    {
      key: "page1",
      title: "Benvindo a Bue Shopping",
      text: "Encontre as mais diversas marcas do mercado no conforto da sua casa.",
      icon: "ios-basket",
      colors: ["#0FF0B3", "#036ED9"],
    },
    {
      key: "page2",
      title: "Entrega rapida e segura",
      text: "Faça as suas compras e elas serão entregue com segurança e rapidez.",
      icon: "ios-card",
      colors: ["#13f1fc", "#0470dc"],
    },
    {
      key: "page3",
      title: "Alta Performance",
      text: "Economize seu tempo e compre produtos com facilidade.",
      icon: "ios-finger-print",
      colors: ["#b1ea4d", "#459522"],
    },
  ],

  /**
   * Config For Left Menu Side Drawer
   * @param goToScreen 3 Params (routeName, params, isReset = false)
   * BUG: Language can not change when set default value in Config.js ==> pass string to change Languages
   */
  menu: {
    // has child categories
    isMultiChild: true,
    // Unlogged
    listMenuUnlogged: [
      {
        text: "Login",
        routeName: "LoginScreen",
        params: {
          isLogout: false,
        },
        icon: Icons.MaterialCommunityIcons.SignIn,
      },
    ],
    // user logged in
    listMenuLogged: [
      {
        text: "Logout",
        routeName: "LoginScreen",
        params: {
          isLogout: true,
        },
        icon: Icons.MaterialCommunityIcons.SignOut,
      },
    ],
    // Default List
    listMenu: [
      {
        text: "Shop",
        routeName: "Home",
        icon: Icons.MaterialCommunityIcons.Home,
      },
      /*{
        text: "News",
        routeName: "NewsScreen",
        icon: Icons.MaterialCommunityIcons.News,
      },*/
      {
        text: "contactus",
        routeName: "CustomPage",
        params: {
          id: 10941,
          title: "contactus",
        },
        icon: Icons.MaterialCommunityIcons.Pin,
      },
      {
        text: "About",
        routeName: "CustomPage",
        params: {
          url: "https://bueshopping.com/privacy-policy/",
        },
        icon: Icons.MaterialCommunityIcons.Email,
      },
    ],
  },

  // define menu for profile tab
  ProfileSettings: [
    {
      label: "WishList",
      routeName: "WishListScreen",
    },
    {
      label: "MyOrder",
      routeName: "MyOrders",
    },
    {
      label: "Address",
      routeName: "Address",
    },
    /*{
      label: "Currency",
      isActionSheet: true,
    },*/
    // only support mstore pro
    {
      label: "Languages",
      routeName: "SettingScreen",
    },
    {
      label: "PushNotification",
    },
    {
      label: "DarkTheme",
    },
    {
      label: "contactus",
      routeName: "CustomPage",
      params: {
        id: 10941,
        title: "contactus",
      },
    },
    {
      label: "Privacy",
      routeName: "CustomPage",
      params: {
        url: "https://bueshopping.com/privacy-policy",
      },
    },
    {
      label: "termCondition",
      routeName: "CustomPage",
      params: {
        url: "https://bueshopping.com/privacy-policy",
      },
    },
    {
      label: "About",
      routeName: "CustomPage",
      params: {
        url: "https://bueshopping.com/privacy-policy",
      },
    },
  ],

  // Homepage Layout setting
  layouts: [
    {
      layout: Constants.Layout.card,
      image: Images.icons.iconCard,
      text: "cardView",
    },
    {
      layout: Constants.Layout.simple,
      image: Images.icons.iconRight,
      text: "simpleView",
    },
    {
      layout: Constants.Layout.twoColumn,
      image: Images.icons.iconColumn,
      text: "twoColumnView",
    },
    {
      layout: Constants.Layout.threeColumn,
      image: Images.icons.iconThree,
      text: "threeColumnView",
    },
    {
      layout: Constants.Layout.horizon,
      image: Images.icons.iconHorizal,
      text: "horizontal",
    },
    {
      layout: Constants.Layout.advance,
      image: Images.icons.iconAdvance,
      text: "advanceView",
    },
  ],

  // Default theme loading, this could able to change from the user profile (reserve feature)
  Theme: {
    isDark: false,
  },

  // new list category design
  CategoriesLayout: Constants.CategoriesLayout.card,

  // WARNING: Currently when you change DefaultCurrency, please uninstall your app and reinstall again. The redux saved store.
  DefaultCurrency: {
    symbol: "kz",
    name: "Kwanza",
    code: "AOA",
    name_plural: "Kwanzas",
    decimal: ".",
    thousand: ",",
    precision: 0,
    format: "%v%s", // %s is the symbol and %v is the value
  },

  DefaultCountry: {
    code: "en",
    RTL: false,
    language: "English",
    countryCode: "US",
    hideCountryList: false, // when this option is try we will hide the country list from the checkout page, default select by the above 'countryCode'
  },

  /**
   * Config notification onesignal, only effect for the Pro version
   */
  OneSignal: {
    appId: "7d072619-ad7b-4854-9371-1f037932e32d",
  },
  /**
   * Login required
   */
  Login: {
    RequiredLogin: false, // required before using the app
    AnonymousCheckout: false, // required before checkout or checkout anonymous
  },

  Layout: {
    HideHomeLogo: false,
    HideLayoutModal: false
  },

  Affiliate: { enable: false }
};

**Comment by IvoKalu** [comment]
AppConfig.js
{
  "WooCommerce": {
    "url": "https://bueshopping.com",
    "consumerKey": "ck_a36aec0bea20fdac2f4a03fbbcaa2dbb7296504c",
    "consumerSecret": "cs_d8b51cffd83b85faea28ba2b481e014ea9222f40"
  },
  "HorizonLayout": [
    {
      "layout": "bannerImage",
      "categoryOrTag": 40,
      "height": 118,
      "imageBanner": "http://s3-ap-southeast-1.amazonaws.com/mstore-bucket.io/wp-content/uploads/2019/02/25142018/collection.png",
      "category": 40
    },
    {
      "layout": "bannerSlider",
      "categoryOrTag": 39,
      "height": 118,
      "category": 30
    },
    {
      "layout": "circleCategory"
    },    
    {
      "name": "featureProducts",
      "image": "",
      "layout": "threeColumn",
      "categoryOrTag": 40,
      "category": 31
    },
    {
      "layout": "bannerImage",
      "categoryOrTag": 40,
      "height": 118,
      "imageBanner": "http://s3-ap-southeast-1.amazonaws.com/mstore-bucket.io/wp-content/uploads/2019/02/25142102/MAN-large.png",
      "category": 40
    },
    {
      "name": "bagsCollections",
      "image": "",
      "layout": "twoColumn",
      "category": 30
    },
    {
      "imageBanner": "http://s3-ap-southeast-1.amazonaws.com/mstore-bucket.io/wp-content/uploads/2019/02/25142145/woman-large.png",
      "layout": "bannerImage",
      "height": 118,
      "category": 40
    },
    {
      "name": "womanBestSeller",
      "image": "",
      "layout": "threeColumn",
      "categoryOrTag": 31,
      "category": 51
    },
    {
      "layout": "bannerImage",
      "categoryOrTag": 39,
      "height": 118,
      "imageBanner": "http://www.acd-angola.com/img/test.jpg",
      "category": 31
    },
    {
      "name": "manCollections",
      "image": "",
      "layout": "threeColumn"
    }
  ],
  "MainColor": "#3FC1BE"
}

**Comment by minhcasi** [comment]
Thanks, note with checking

**Comment by IvoKalu** [comment]
Any update on my issues??

**Comment by minhcasi** [comment]
Hi sorry for the late response, the team is still checking as they have many jobs - we will keep an update on this open ticket - thanks

**Comment by IvoKalu** [comment]
Any development on the issues I submitted??

**Comment by minhcasi** [comment]
Fix on latest 3.9.0 - please help to check again, thank you!

**Comment by IvoKalu** [comment]
Still not working. Thank you.

**Comment by ItisAhsan** [comment]
still not working.. even in 3.9.2
