### ISSUE TITLE
ios launch 

### ISSUE THREAD

**Issue by saeidAalizade** [inspireui/support#616]
Hi, I can not get out

Error: 

error Failed to build iOS project. We ran “xcodebuild” command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening mstore.xcworkspace

<img width="682" alt="Screen Shot 2019-05-22 at 2 33 18 AM" src="https://user-images.githubusercontent.com/41091634/58133799-15f78080-7c3a-11e9-976b-f0387b07c65a.png">

**Comment by minhcasi** [comment]
1. can you provide the purchased code
2. what is product related to this error?

Try to format the ticket as our providing template and create new ticket - thanks
