### ISSUE TITLE
control the application by plugin

### ISSUE THREAD

**Issue by iqmtgar** [inspireui/support#617]
ListApp - Listing Directory mobile app by React Native
Regular License
Purchase code: 6f853877-6ce8-4755-a68f-b7f87628c4e1

Hello, how are you ..
I can not control the application by plugin listapp manager

**Comment by minhcasi** [comment]
could you clarify more your issues with the screenshot Thanks

**Comment by iqmtgar** [comment]
now fix all 
but 
images not viewe 
https://6.top4top.net/p_1242pynwh1.jpg

**Comment by minhcasi** [comment]
@thangvo9x

**Comment by thangvo9x** [comment]
Hi, Try to this solution.
https://github.com/inspireui/support/issues/184#issuecomment-495125707

**Comment by iqmtgar** [comment]
my Tools.js

**Comment by iqmtgar** [comment]
There are a lot of problems
I can not book

**Comment by iqmtgar** [comment]
Can I send my information to you?
And create an application for me? apk only ?

**Comment by thangvo9x** [comment]
Try to replace this file at Common/
[Tools.txt](https://github.com/inspireui/support/files/3226065/Tools.txt)
p/s: Remember that change from .txt -> .js

**Comment by iqmtgar** [comment]
If the application contains errors
Why sell it?
I'm trying to run an application for seven days
Please help me with it

**Comment by iqmtgar** [comment]
https://4.top4top.net/p_1243twxfi1.jpeg
When you want to publish something

**Comment by thangvo9x** [comment]
Hi you can refer here https://docs.inspireui.com/listapp/troubleshooting/
