### ISSUE TITLE
listpro - ListApp Mobile Manager

### ISSUE THREAD

**Issue by adirtp** [inspireui/support#621]
Hi
after activating all plugin im getting:
Notice: Trying to get property 'name' of non-object in /home/glame/public_html/wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php on line 46

Notice: Trying to get property 'name' of non-object in /home/glame/public_html/wp-includes/rest-api/endpoints/class-wp-rest-terms-controller.php on line 62

thats caused by the ListApp Mobile Manager plugin (errors disappear after deactivating)

**Comment by minhcasi** [comment]
1. could you provide the purchase code
2. and send us more screenshot about the issues

Thanks
