### ISSUE TITLE
[Beonews] Content formating.... 

### ISSUE THREAD

**Issue by rxlp** [inspireui/support#622]
**Required Info (please complete the following information):**
 - Product:  BeoNew Pro
 - Your Purchased Code: 2a15b7b9-89be-4b20-ad85-db5f8e9791cd 

**Describe the bug**
Elements are not formatted correctly, see the screenshots below, the correct one and the rendered content from app.

**Screenshots**
![Simulator Screen Shot - iPhone X - 2019-05-21 at 23 15 51](https://user-images.githubusercontent.com/50889285/58131242-75479780-7c1e-11e9-9463-c6bb88b9b8dd.png)

![Simulator Screen Shot - iPhone X - 2019-05-21 at 23 16 09](https://user-images.githubusercontent.com/50889285/58131249-78db1e80-7c1e-11e9-96f2-a6bb5b4c0964.png)

**Comment by minhcasi** [comment]
Can you show the according to website URL of this content? Thanks

**Comment by rxlp** [comment]
url1: https://www.ricetteconarte.com/ricetta-pancake/ 
url2: https://www.ricetteconarte.com/strudel-di-mele/

**Comment by minhcasi** [comment]
Hi, you can try to add more format and css from the webview/index.js, it is using the render html component (https://github.com/archriss/react-native-render-html) to render the html, some css could be removed so that it will not display as same on your website.
