### ISSUE TITLE
[MStore Pro] Shipping charges is displayed at checkout

### ISSUE THREAD

**Issue by Relimer-Technologies** [inspireui/support#623]
Mandatory Info (please complete the following information):

Product: [e.g. MStore, ListApp]
M Store Pro
Purchase Code: d98eb201-aba4-4c76-a0a1-cbd67415737d
Your Purchased Code: [get from https://codecanyon.net/downloads]
(we may not reply if you are not our customer)
Describe the issues
Hello,

Good Morning, I have purchased M Store Pro from Envato. I have done all the setup required... I have installed all of the required tools... I have a basic request for shipping charges... I have assigned Flat Rate as 450 and Free Shipping as 0 with the condition of Total amount to be greater than or equal to 25000... I am able to get both the shipping options during checkout but
the condition for Free Shipping is not fulfilled... I need the customer to avail free shipping only if they do 25000 or above value shopping but in the app, both the shipping are shown for any value of the cart.

Kindly help me out with this... Thank You

**Comment by Relimer-Technologies** [comment]
I have already registered the issue in the following link below

https://github.com/inspireui/support/issues/587

I have tried the code given by you but the Shipping is displayed still at the checkout page. Please provide me with the alternate solution.

Kindly help me out with this.

Thank You

**Comment by minhcasi** [comment]
Hi, could you able to debug the app by using simple tool like Reactotron - https://github.com/infinitered/reactotron/blob/master/docs/installing.md - and figure out the problem as we don't have other better solution so far - thank you!
