### ISSUE TITLE
[Listapp] Cover Image issue

### ISSUE THREAD

**Issue by reconshield** [inspireui/support#624]
i cant view cover image/featured images .as i found..its not from wordpress setting, because i can view all cover image in listapp previous version. this cover image issue occur since we using 7.0.1 version and after update listapp manager plugin. something wrong with manager..pls advice

![57751161-6e4cf080-7717-11e9-8790-47b50f24be89](https://user-images.githubusercontent.com/25501496/58152052-13c70d80-7c9e-11e9-89e6-5f20a110fc9d.png)

**Comment by thangvo9x** [comment]
https://github.com/inspireui/support/issues/184#issuecomment-495125707

**Comment by reconshield** [comment]
after follow 184 solution..now i can see cover image..but now post/blog cover image is missing.. 

![Simulator Screen Shot - iPhone X - 2019-05-24 at 09 19 32](https://user-images.githubusercontent.com/25501496/58296187-3fb0d300-7e05-11e9-90c5-2e4dd5e476dd.png)
