### ISSUE TITLE
[MStore] error build iOS project

### ISSUE THREAD

**Issue by saeidAalizade** [inspireui/support#626]
purchased code :
153bb1ff-3f3e-41cd-a219-da061397aef5

product name : 
Mstore pro

Hi, I can not export ios app
Error : 
error Failed to build iOS project. We ran “xcodebuild” command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening mstore.xcworkspace

<img width="682" alt="Screen Shot 2019-05-22 at 2 33 18 AM" src="https://user-images.githubusercontent.com/41091634/58163717-b761ef00-7c99-11e9-9af3-1814842cc073.png">

**Comment by saeidAalizade** [comment]
why do not you answer?

**Comment by minhcasi** [comment]
Can you try to open the ios folder and run: pod install

Then open the workspace by using XCode to run the app again

**Comment by saeidAalizade** [comment]
i runinig "pod install" to terminal, but not run app ios 

Erorr : 
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening mstore.xcworkspace

**Comment by minhcasi** [comment]
Hi, sorry for the lated response - could you try to open the XCode after re-install the pod:
- Open the workspace
- Clean up the cache (command+shift+K) and run the app again

It's working fine with this solution with most of the cases - thanks
