### ISSUE TITLE
[MStore] Updating is a struggle -> include patching file

### ISSUE THREAD

**Issue by rxlp** [inspireui/support#627]
Every time is an update, I have to reconfigure all the product from the start, **updating is a struggle.** I have tried to merge current code with update but nothing seems to work.

**Why you don't offer any repository for people with purchase code?** We can pull on update and have a happy life.

thanks!

**Comment by minhcasi** [comment]
Thank for your suggestion, do you think provide .patch files file help for the update?

**Comment by rxlp** [comment]
patch with updated files seems at least less pain. Thanks for understanding.
My product btw is BeoNews.

**Comment by minhcasi** [comment]
Thanks, notes for including the patch file on next time (for Beonews)

**Comment by ItisAhsan** [comment]
Please do this for MStore also...updating is real struggle.
