### ISSUE TITLE
[ListApp] No images will be display

### ISSUE THREAD

**Issue by bfwi410a** [inspireui/support#628]
- Product: ListApp
 - Your Purchased Code: will not write public. If needed will send by mail

in whole app no images will display. I installed all plugins and regernate thumbnails in wordpress. What could it be? Hope you could help.

![Image-1](https://user-images.githubusercontent.com/1284361/58203180-d54f4400-7cd9-11e9-9ddd-e80d1a6af574.jpg)

**Comment by reconshield** [comment]
everyone facing the issue :(

**Comment by thangvo9x** [comment]
https://github.com/inspireui/support/issues/184#issuecomment-495125707

**Comment by reconshield** [comment]
perfect..working fine now..thanks

**Comment by bfwi410a** [comment]
Images in listings detail work but the resolution is very bad. No blog post images and no listing images on (first view -> view after app start) are displayed. See attached screenshots.

![IMG_7464](https://user-images.githubusercontent.com/1284361/58242207-aa530780-7d4e-11e9-9c7c-ca38961ebe30.PNG)
![IMG_7465](https://user-images.githubusercontent.com/1284361/58242209-aa530780-7d4e-11e9-8d69-f74111502b56.PNG)

**Comment by reconshield** [comment]
bfwi410a how u get address and twitter display in your listing? can guide me?

**Comment by bfwi410a** [comment]
@reconshield i use listable. Adress and Twitter will be display automaticly.

**Comment by bfwi410a** [comment]
@thangvo9x 

i do not know what I'm doing wrong. :-( I installed Better REST API Featured Images plugin and checked if API was extended by plugin. Yes, it is. I also installed Regenerate Thumbnails plugin and regenerated about 1700 pictures. Last i replaced the code from common/Tools.js with your code from Tools.txt. But no cover images will be display. Images in listings detail still work but the resolution is very bad.
Do you have any idea?

![2019-05-23 20_58_58-Window](https://user-images.githubusercontent.com/1284361/58279344-6b4ca280-7d9e-11e9-96cd-bbd659eb2af9.jpg)

![Image-1](https://user-images.githubusercontent.com/1284361/58279362-7a335500-7d9e-11e9-92ac-27137c6c3c93.jpg)

**Comment by reconshield** [comment]
after follow #184 (comment) solution..now i can see cover image..but now post/blog cover image is missing..

![Simulator Screen Shot - iPhone X - 2019-05-24 at 09 19 32](https://user-images.githubusercontent.com/25501496/58296227-6a9b2700-7e05-11e9-8dee-195b2672cd28.png)

**Comment by minhcasi** [comment]
@thangvo9x

**Comment by thangvo9x** [comment]
https://github.com/inspireui/support/issues/184#issuecomment-495125707

**Comment by reconshield** [comment]
yes.i follow #184.. Listing Cover image OK.. thanks.. but now.. post/blog featured image not working..

![Simulator Screen Shot - iPhone X - 2019-05-28 at 10 09 32](https://user-images.githubusercontent.com/25501496/58445964-6470b780-8131-11e9-9376-7bdbd209c392.png)

**Comment by minhcasi** [comment]
@reconshield - your customize category icons looks awesome, can you share your whole screenshot 👍

**Comment by reconshield** [comment]
yes.. but i got one issue :(.. the blog post featured image not display..other than that all ok..

![Simulator Screen Shot - iPhone X - 2019-05-28 at 10 20 39](https://user-images.githubusercontent.com/25501496/58446214-69823680-8132-11e9-9e46-c88b835b6032.png)
![Simulator Screen Shot - iPhone X - 2019-05-28 at 10 20 58](https://user-images.githubusercontent.com/25501496/58446218-6b4bfa00-8132-11e9-9a04-375a70c8f6b7.png)
![Simulator Screen Shot - iPhone X - 2019-05-28 at 10 09 32](https://user-images.githubusercontent.com/25501496/58446220-6e46ea80-8132-11e9-860a-311a3085e9a4.png)

**Comment by reconshield** [comment]
yes.. but i got one issue :(.. the blog post featured image not display..other than that all ok..pls advice

**Comment by thangvo9x** [comment]
Try to replace this file at App/common folder
[Tools.txt](https://github.com/inspireui/support/files/3226059/Tools.txt)
p/s: Remember that change from .txt -> .js
Thanks

**Comment by reconshield** [comment]
blog post working fine! thanks.. some of listing cover image not display..its was ok before this..not all listing cover image is missing just few.. i tried add new listing..cover image not display for new listing..


![Simulator Screen Shot - iPhone X - 2019-05-28 at 15 23 20](https://user-images.githubusercontent.com/25501496/58460483-538b6a80-8160-11e9-9f8d-841247822db1.png)

**Comment by reconshield** [comment]
Working fine ..thanks alot :)
