### ISSUE TITLE
[MStore] When i hit (Run Setup)

### ISSUE THREAD

**Issue by ahmedot** [inspireui/support#629]
**Required Info (please complete the following information):**
 - Product: [MStore]
 - Your Purchased Code: 2f517590-9c6c-44ff-8b9e-b734757be547
(we may not reply if you are not our customer)

**Describe the bug**
When i run CeBuilder and hit run setup i get this screen in the screenshot. 

**Screenshots**
https://imgur.com/VGfXPG9

**Additional context**
Add any other detail logs about the problem here.
If possible please share your config.js that use for the app setting

**Comment by LeonidMiller** [comment]
I have like this problem now to

**Comment by minhcasi** [comment]
Hi, did you try to install all the library on step 2, then try to restart the app if it can be help.

Also try with latest Cebuilder 0.35 - thanks

**Comment by ahmedot** [comment]
Where can i find the last version 0.35?

Sent from my iPhone

On May 23, 2019, at 4:46 PM, Minh Pham <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, did you try to install all the library on step 2, then try to restart the app if it can be help.

Also try with latest Cebuilder 0.35 - thanks

**Comment by bfwi410a** [comment]
version 0.35 you will find here: https://github.com/inspireui/cebuilder/releases

**Comment by LeonidMiller** [comment]
i was already install Cebuilder 0.35 and its problem with Cebuilder 0.35

**Comment by ahmedot** [comment]
Same problem still not solved.

i have updated to 0.35.

**Comment by minhtruong315** [comment]
hi @ahmedot can you add my skype: minhtruong315, I will help you check via teamviewer
