### ISSUE TITLE
[ListApp] - Console.log messages are not displayed in Reactotron

### ISSUE THREAD

**Issue by Jeison12** [inspireui/support#63]
Product: ListApp
My Purchased Code: ccded53c-5f90-41ff-8c6a-fac4faae1017

Console.log messages are not displayed in Reactotron

**Comment by thangvo9x** [comment]
Hi. Thanks for your choice to our product. 
It could be displayed with name DEBUG 
<img width="265" alt="debug" src="https://user-images.githubusercontent.com/23457178/49195606-59271400-f3ba-11e8-8763-baa5c23bce51.png">

**Comment by Jeison12** [comment]
Reactotron did not show me the DEBUG before, now it shows them. Thank you
