### ISSUE TITLE
[Mstore] Profile photo  in home page right top

### ISSUE THREAD

**Issue by santhosh2210** [inspireui/support#631]
- Product: [Mstore]

I want to display the my profile image on home top right side...
See the screenshot -> http://prntscr.com/nscv7r
please help to this functionality and reply quickly..
![WhatsApp Image 2019-05-23 at 6 16 42 PM](https://user-images.githubusercontent.com/32481586/58253981-62040b80-7d87-11e9-94ec-fddae51c2b8b.jpeg)

**Comment by santhosh2210** [comment]
Waiting for your support..!!!

**Comment by minhcasi** [comment]
You can customize this file - https://tppr.me/sLm4f
navigation/IconNav.js

**Comment by santhosh2210** [comment]
Hi minhcasi,
Already i find this file navigation/IconNav.js( HeaderHomeRight)..Now i will changed the profile code but i had lot error...so please change the code and give me...its very important for me...thanks for your reply..
