### ISSUE TITLE
LIST APP ( cannot booking in Listify Themes) Help Wanted

### ISSUE THREAD

**Issue by locald3v** [inspireui/support#632]
Hay mate, can you help me?  the booking button cannot function in listapp.  im use listify themes in my domain. thanks alot before.

**Comment by minhcasi** [comment]
can you share the detail screenshot 

Also your purchased code - thank you!

**Comment by locald3v** [comment]
this is purchase code : dd5dd7cd-1519-436d-891b-774f99e9dc58
ss booking not function 
![ss1](https://user-images.githubusercontent.com/49985026/58335982-057b1c00-7e6d-11e9-98ae-3417b01a6717.PNG)

can you help me?? if you want to check backend access. ill give you the access,
thanks alot before.

**Comment by minhcasi** [comment]
@thangvo9x - pls suggest a solution - thanks

**Comment by thangvo9x** [comment]
Hi. The latest version of Listify theme isn't support booking, you must customize it. This is out of scope from supporting.
Thanks for your choice of our product.

**Comment by locald3v** [comment]
Hii mate, whats version of listify theme is support booking? What theme and which version supports to be able to book from the mobile application, I have read the comments on the codecanyon, to set up the woocommerce plugin and I still can't book.
Thanks alot before. i hope you can give me a solution.

**Comment by locald3v** [comment]
can i make refund on codecanyon ???

**Comment by thangvo9x** [comment]
You can process a refund here 
https://themeforest.net/refund_requests/new

**Comment by locald3v** [comment]
I have make request refund on evanto.. Please approved. Thanks before 🙏
