### ISSUE TITLE
[Mstore] Layout Error not display all languages

### ISSUE THREAD

**Issue by hakihosting** [inspireui/support#634]
Purchase code : ac9d522a-a783-4f9c-a882-7dc694488d5d

Hello when i change the language in french , The layout of the cebuilder is correct but when i change to another language the layout dissipear.

https://streamable.com/w9wz6

Hello i have the API response :
http://chakcwear.com/wp-json/wc/v2/products/?oauth_consumer_key=ck_7c00db526a82083e44f94b07a80f7e41600e8235&oauth_nonce=qv8SdJq93CM9SJyEjdYQXKsfodQQzzh8&oauth_signature_method=HMAC-SHA256&oauth_timestamp=1553772698&oauth_version=1.0&per_page=10&page=1&purchasable=true&status=publish&category=89&lang=en&oauth_signature=v+pK/6xdKXZBzMb8ghiLP18clOxfoeHTj2TlZ37j4AQ=
Status Code
401
Method
GET
Duration (ms)
3210
code:woocommerce_rest_authentication_error
message:Invalid signature - provided signature does not match.
status:401

Hello yes there is three language on my website :  http://chakcwear.com/?lang=en

Yes , you can see by yourself go to www.chakcwear.com and go in to the three languages

**Comment by hakihosting** [comment]
Hello i have installed the new version but i see , these errors still bug in the version : 3.8.0

- When i insert a code promo in lower case it works ,but if i insert in Uppercase : CODE promo is invalid.

- Stock problem with variations synching

- MultiLanguage homepage not showing

**Comment by hakihosting** [comment]
I would like  to delete the date on the homepage 
![image](https://user-images.githubusercontent.com/47614045/58279958-f5493b00-7d9f-11e9-82a3-a1423c7e34a4.png)

**Comment by minhcasi** [comment]
can you zip the package and send to support@inspireui.com - we will help for checking the variations and language issue - it seems the code is not latest from 3.8.x

**Comment by hakihosting** [comment]
Hello , i send you by wetransfer thanks for your help

**Comment by minhcasi** [comment]
Thanks, just confirm we have got it, the team is checking and will let you know - thank you!

**Comment by hakihosting** [comment]
Ok thank you

**Comment by hakihosting** [comment]
hello do you have some news

**Comment by hakihosting** [comment]
??

**Comment by minhcasi** [comment]
Sorry for the lated response, we will get back on tomorrow - thanks

**Comment by hakihosting** [comment]
some news

**Comment by minhcasi** [comment]
Hi, could you help to re-upload the package again, our guys have download and fixed, but his laptop is having an issue and could not use? Sorry for the delay, we will update it shortly after you resent it again - thanks

**Comment by hakihosting** [comment]
Hello i send it again by wetransfer

**Comment by minhcasi** [comment]
Hi, could you help to remove node_module folder and resend the zip again, your current file take many hours for extracting

**Comment by hakihosting** [comment]
Hello send it again :)  Thanks

**Comment by hakihosting** [comment]
some news

**Comment by minhcasi** [comment]
- this is your changed that cause the coupon issue - https://tppr.me/sgvQH

- multi language working fine - https://tppr.me/K1FWD - you need to check the WMPL plugin to config for each languages

- product variant working fine - https://tppr.me/6nTL4

**Comment by hakihosting** [comment]
Hello : 

When i insert a code promo in lower case it works ,but if i insert in Uppercase : CODE promo is invalid.
Explication : If i have a code in woocomerce : mstore.  If i text in lowercase in the app => no problem 
but if i text in the app : MSTORE => i have a invalid coupon code  or it's the same text. 
I have made the change to accept the bot, so i resolved my issue with this change. 

Stock problem with variations synching
Ok variations works but stock variations not. On the website i have for a 
Product A : 
variation 1 (stock : 3) 
variation 2 (stock : 0) 

Or in the app , if you go to the product A , and click in the variation 1 : no problem you can buy this 
but if you click on the variation 2 , you can buy too . (there is an issue ) normaly the button must be OUT OF STOCK 


MultiLanguage homepage not showing
Please can you test with language : English and Néerlandais  : is not working

**Comment by hakihosting** [comment]
Some news p’ease

**Comment by hakihosting** [comment]
Some news ?

**Comment by hakihosting** [comment]
Hello it's possible to have some news or a response ?

**Comment by minhcasi** [comment]
Hi, we have updated latest 3.9.0 to fix the variant issues, please help to check on your site - thank you!
