### ISSUE TITLE
change text status order to arabic

### ISSUE THREAD

**Issue by saeidAalizade** [inspireui/support#635]
Product: [MStore]
Your Purchased Code: [153bb1ff-3f3e-41cd-a219-da061397aef5]
Describe the issues

how can I Changed texts?

pending
processing
onHold
completed
cancelled
refunded
failed
to status order
I want to change in Arabic
Example :
completed = منجز
cancelled = ألغيت
failed = فشل

**Comment by minhcasi** [comment]
maybe you need to add the hard-code as this status could not be changed from the woocommerce API.

Customize file: containers/MyOrders/OrderItem.js - thanks
