### ISSUE TITLE
[Mstore] how to change default currency

### ISSUE THREAD

**Issue by yudiaoey** [inspireui/support#636]
- Product: MStore
- Your Purchased Code: cf616a55-6586-4262-894d-42d437745d69

**Describe the issues**
Hello inspireUI, please help me to installing this product
- How to deactive multi currency and set IDR (Indonesia Rupiah) as default currency ?
- How to decrease font size at product list ?
- How to change background categories ? 
- can you provide me link for homepage setting ? i didn't see **_card_** setting in instaling guide link

**Screenshots**
![image](https://user-images.githubusercontent.com/50505266/58295557-13438980-7dfa-11e9-8143-707c4ebcd850.png)
![image](https://user-images.githubusercontent.com/50505266/58295617-6fa6a900-7dfa-11e9-88ae-96e6f9235b36.png)

**Comment by minhcasi** [comment]
HI,

1. the currency default can be change from the common/config.js file
2. edit the file from  components/HorizonLayout/**
3. Update the containers/Categories/index.js
4.  pls check the card setting from this guide - https://docs.inspireui.com/mstore/home-theme/
