### ISSUE TITLE
[Listapp] . How vendor post listing?

### ISSUE THREAD

**Issue by reconshield** [inspireui/support#64]
**ok..from your screenshot. i can see user panel tab clicked. and the last menu is push notification. which tab vendor have to click to post listing?**

![49146041-d491b280-f333-11e8-868c-4347d011f6c2](https://user-images.githubusercontent.com/25501496/49192197-fa12d080-f3b4-11e8-9102-90c1cd753466.png)

**Comment by thangvo9x** [comment]
Hi. Thanks for your value feedback. We'll research & rearrange UX for this.
Thanks
