### ISSUE TITLE
[ Mstore ] - Intro screen issue on full screen mobile( like a NOTE 7 Pro )

### ISSUE THREAD

**Issue by santhosh2210** [inspireui/support#642]
First three Intro screen issue on full screen mobile like note 7 pro...
Intro color are not full fill the bottom navigation in full screen mobile...so please tell us custom css in mstore app..

See the Screenshot -> http://prntscr.com/nt62dq

**Comment by minhcasi** [comment]
note for checking - thanks

**Comment by santhosh2210** [comment]
Issue 1:-  Address are not sync to wp site via facebook login
     Shipping address are storing the app....but not sync the wordpress site via facebook login.......
working fine via sign up....
See the screenshot -> http://prntscr.com/nudh2e
please find the error and reply fast

Issue 2:- Profile photo in home page right top
     I want to display the my profile image on home top right side...
minhcasi reply message - , you can navigate to the Profilescreen when click to that icon - example: https://tppr.me/C1Bsb
This code also use but not working...only display the empty screen...
See the screenshot -> http://prntscr.com/nu8tws
so please change the code and give me...its very important for me...thanks for your reply..

**Comment by santhosh2210** [comment]
Are you there???....waiting for your reply

**Comment by santhosh2210** [comment]
Issue 2:- Profile photo in home page right top
I want to display the my profile image on home top right side...
minhcasi reply message - , you can navigate to the Profilescreen when click to that icon - example: https://tppr.me/C1Bsb
This code also use but not working...only display the empty screen...
See the screenshot -> http://prntscr.com/nu8tws
so please change the code and give me...its very important for me...thanks for your reply..
