### ISSUE TITLE
[ Mstore ] - Profile photo in home page right top

### ISSUE THREAD

**Issue by santhosh2210** [inspireui/support#643]
I want to display the my profile image on home top right side...
Already i find this file navigation/IconNav.js( HeaderHomeRight)..Now i will changed the profile code but i had lot error...so please change the code and give me...its very important for me...thanks for your reply..

See the screenshot -> http://prntscr.com/nt62uw

**Comment by minhcasi** [comment]
hi, you can navigate to the Profilescreen when click to that icon - example: https://tppr.me/C1Bsb
