### ISSUE TITLE
[Cebuilder] - why support dont want help? i have problem with install

### ISSUE THREAD

**Issue by LeonidMiller** [inspireui/support#644]
My purchase code 68c3cc40-381d-4f7a-babd-db0f1305abef - 22 May 2019

---------

1. I was installed all libraries and Cebuilder cant install app mstore pro

![image](https://user-images.githubusercontent.com/34884740/58378410-e8913680-7f9b-11e9-99ec-bf7a85dfb42b.png)
![image](https://user-images.githubusercontent.com/34884740/58378411-f050db00-7f9b-11e9-9fe5-c7f45687527e.png)

**Comment by minhcasi** [comment]
Hi, can you translate the error log issue as i can read Russian - thanks

**Comment by LeonidMiller** [comment]
> Hi, can you translate the error log issue as i can't read Russian - thanks

![image](https://user-images.githubusercontent.com/34884740/58639620-fcbc9700-82ff-11e9-9fc9-7a3ca36eb7fb.png)

**Comment by minhcasi** [comment]
Hi, do you have time around today, we could help for the teamviewer to check your issue?

@vumanhsn97 - pls help for supporting

**Comment by vumanhsn97** [comment]
@minhcasi ok

**Comment by LeonidMiller** [comment]
> Hi, do you have time around today, we could help for the teamviewer to check your issue?
> 
> @vumanhsn97 - pls help for supporting

Yesi have time can you help? i was write to you in skype

**Comment by McRobby** [comment]
Please try the command "npm install -g react-native-cli"
Source: https://facebook.github.io/react-native/docs/getting-started.html
