### ISSUE TITLE
[my-product] - ListApp

### ISSUE THREAD

**Issue by freetimeforcash** [inspireui/support#645]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - Try to explain your all problems in one ticket, instead of creating multi tickets 

---------

1. My issue

2. Screenshots

3. Config files (optional)

**Comment by freetimeforcash** [comment]
1: My issue: Presently, my issue is that the listapp mobile manager plugin will not install. It is creating a fatal error when I try to install the app. 

2.
![listapp plugin cannot be installed](https://user-images.githubusercontent.com/34894468/58379817-c802b580-7f76-11e9-8b8a-d967789204b7.jpg)

I'm not sure if I attached the screenshot correctly so here is what the error message reads:

Fatal error: Cannot redeclare class Mobile_Detect in /home/mycitygu/public_html/wp-content/plugins/listapp-mobile-manager/templates/class-mobile-detect.php on line 29

I have seen this issue with others seeking help as well

**Comment by reconshield** [comment]
try uninstall / deactive all other plugins.then upload latest listapp mobile manager..its might help you.

* This Message from User not Admin
