### ISSUE TITLE
[mstore multi vendor] - 

### ISSUE THREAD

**Issue by leudy1521** [inspireui/support#646]
purchased code
5e5936bf-917f-4d3c-9ed9-a09b81106b1d 

---------

1. My issue
hello I have problems when publishing products from the app here I leave a screenshot, I installed all the wordpress plugins and still the error continues

2. Screenshots
![error](https://user-images.githubusercontent.com/51096495/58440203-c3eea900-80d8-11e9-9c19-bdf373859e3a.jpg)
![yyyy](https://user-images.githubusercontent.com/51096495/58440232-f13b5700-80d8-11e9-9ea9-43eb4e278bc3.jpg)

3. Config files (optional)

**Comment by thangvo9x** [comment]
Hi @leudy1521 . You can refer here
https://docs.inspireui.com/mstore-mv/troubleshooting/#wrong-segments--message-when-post-new-listing
Thanks

**Comment by leudy1521** [comment]
hello I have tried all the steps of the documentation and I am still given this error at the time of publishing products.

I have changed roles to users and the JWT API is well configured
![unnamed](https://user-images.githubusercontent.com/51096495/58494052-88a1b800-8174-11e9-815e-44dbec163f4d.jpg)

**Comment by thangvo9x** [comment]
Hi, you can refer here 
https://docs.inspireui.com/mstore-mv/troubleshooting/#sorry-this-user-is-not-scope-message-when-post-new-product
These problems are coming from causes here;
suggest 
1. Role editor has only posted a new listing.
2. plugin JWT with the .htaccess file.

**Comment by leudy1521** [comment]
![D1468A43-DB83-4108-9FE9-1CB7EB883D1E](https://user-images.githubusercontent.com/51096495/58546126-044b4580-8205-11e9-8984-5bc5f2a6d427.jpeg)
thank you very much I have solved the problem of uploading products from the app.  Now I have another problem is that when I close the app and reopen it I am disconnected from the server.

**Comment by leudy1521** [comment]
I have also had this problem with the app of mstore that has test on App Store

**Comment by thangvo9x** [comment]
HI. Go to src/Router.js find this block and remove it.
https://tppr.me/u9pL3

**Comment by leudy1521** [comment]
hello I have intendao with what you have told me and still not correct the error I can send you the code to correct the error

**Comment by leudy1521** [comment]
hello I've been talking about what you said and I still can not correct the error I can send you the code to correct it

**Comment by thangvo9x** [comment]
Hi. This is the file which will be replaced.
go to src folder.
[Router.txt](https://github.com/inspireui/support/files/3243260/Router.txt)
