### ISSUE TITLE
[ListApp] Crashing etc issues

### ISSUE THREAD

**Issue by Pars1vaLl** [inspireui/support#65]
**Mandatory Info (please complete the following information):**
 - Product: ListApp
 - Your Purchased Code: 85059e37-2ddd-478d-899b-6db006280782

**Describe the issues**
I use Mylisting theme. There are couple issues I would like to troubleshoot:
 1. App crashes when I try to open any listing:
[App-crashes](https://user-images.githubusercontent.com/45024483/49248728-38070780-f43c-11e8-8c79-10331496579d.png)
 2. Only small count of listings and categories are shown. I have more than 500 listings on site - there is only about 10 which shown in app. The same situation with categories.
 3. Mylisting theme sets custom cover to all listings without cover image. In ListApp all such listings are shown as blank cover.

Hope you`ll help me to solve this issues. Thanks:)

**Comment by thangvo9x** [comment]
Thanks for your choice. Can you share Config.js file? 
Thanks

**Comment by Pars1vaLl** [comment]
Hi, I have sent Config.js to this email: thang@beostore.io
Thakns

**Comment by Pars1vaLl** [comment]
Guuys, I am still waiting.
Thanks

**Comment by minhcasi** [comment]
@thangvo9x

**Comment by thangvo9x** [comment]
Hi, @Pars1vaLl , there're some problem i can't receive it. 
Please Share your Config.js file again. note: your issue, such as your email 
Thanks

**Comment by Pars1vaLl** [comment]
Hi @thangvo9x  , I have sent it again. Please check. 
Thanks:)

**Comment by Pars1vaLl** [comment]
Ok. I will respond soon. Thanks:)

**Comment by Pars1vaLl** [comment]
Hi @thangvo9x  unfortunatelly it didn`t work

**Comment by thangvo9x** [comment]
Can you tell me what is the problem ? I checked it. 
![screenshot](https://user-images.githubusercontent.com/23457178/49845850-12dea580-fdfb-11e8-884b-620e361edaa8.png)
![screenshot2](https://user-images.githubusercontent.com/23457178/49845851-12dea580-fdfb-11e8-9c50-9ee0b7c0db03.png)

**Comment by Pars1vaLl** [comment]
Hi @thangvo9x there is still not all the categories and listings are shown. 
![screenshot_1](https://user-images.githubusercontent.com/45024483/49868234-9f568b80-fe2e-11e8-938a-b922a0193d06.png)

**Comment by thangvo9x** [comment]
Category hasn't any listing then not displayed.

**Comment by Pars1vaLl** [comment]
@thangvo9x There is about 500 listings and no category without listings. You can check it here: [URL](https://diyor.tj/category/)
Thanks:)

**Comment by thangvo9x** [comment]
Hi. Follow your image. The category with name is http://prntscr.com/ltzzqh is only 1 location

**Comment by Pars1vaLl** [comment]
@thangvo9x  Oh, now I see how it works. So it shows subcategories not main categories. What if I want to show main categories - how can I do that?
And what about default cover image from site? It is blank it app.

I really greatly appreciate your help:)

**Comment by thangvo9x** [comment]
hi. You add per_page(100) into function fetchCategories() in Redux/actions/CategoryActions
Default cover image can be changed in Images.js in Common folder with name is imageBase.
Thanks
