### ISSUE TITLE
Scrolling bug on iPhone likes page

### ISSUE THREAD

**Issue by roymi** [inspireui/support#650]
A bug on iPhone where the “Likes” page scroll doesn’t work properly when there are less than about 5 liked posts... please check it... the issue is not seen on the emulator but only on the device itself, it can also be seen on “ceFoods” app from the App Store.
The issue can be reproduced just by adding 1 like post and try scrolling the page, it happens because of a header scroll issue - the screen is "shaking" for couple of seconds

**Comment by minhcasi** [comment]
Could you provide the following info:

1. your purchase code or screenshot comment to show you have purchased the product

2. the product is mentioned about, is it Beonew? Also attache the issue screenshots 

3. The version of iphone
