### ISSUE TITLE
[my-product] - MStore Pro checkout plugin breaks my WP site

### ISSUE THREAD

**Issue by gbatkhuyag** [inspireui/support#652]
1. My issue
 after installing mstore checkout plugin and activate it crushes my site.

2. Screenshots

3. Config files (optional)

**Comment by minhcasi** [comment]
@gbatkhuyag - pls attach the screenshot - thank you!

**Comment by gbatkhuyag** [comment]
![Screen Shot 2019-05-29 at 2 49 52 PM](https://user-images.githubusercontent.com/46191717/58535814-5e5a0400-8221-11e9-91d0-4eff55767217.png)
![Screen Shot 2019-05-29 at 2 50 42 PM](https://user-images.githubusercontent.com/46191717/58535833-65811200-8221-11e9-862e-ecb6ba774289.png)
![Screen Shot 2019-05-29 at 2 51 03 PM](https://user-images.githubusercontent.com/46191717/58535842-69ad2f80-8221-11e9-8079-8b6bd0f721c0.png)
![Screen Shot 2019-05-29 at 2 51 21 PM](https://user-images.githubusercontent.com/46191717/58535844-6d40b680-8221-11e9-9b2d-3fe25d58a718.png)

**Comment by minhcasi** [comment]
Hi, could you try to send the the detail log error from the web server side

you can try to enable the debug mode from the wp-config.php file from the Wordpress to see if it can be shown the detail error - thanks

**Comment by Nippler** [comment]
Hi there, I got the same error on my site.
Would you check my site as well? > Support team

**Comment by gbatkhuyag** [comment]
Hi There,

Would you please support on attached screenshot error?

Regards,
