### ISSUE TITLE
ListApp - Reviews cut off right side

### ISSUE THREAD

**Issue by bfwi410a** [inspireui/support#653]
Dear InspireUI,
for listings with reviews, the right side cut off. See this on iPhoneX, Huawai P Smart and Android Emulator (Nexus 5) See screenshot below. Could you fix?
regards

![2019-05-28 19_40_05-Window](https://user-images.githubusercontent.com/1284361/58499511-9eb57580-8180-11e9-8a37-d96ec08e4434.png)

**Comment by minhcasi** [comment]
note for updating, this could be a minor bug from the UI, could you mind to share your config file so that we could reproduce the issue 

 - thank you!

**Comment by bfwi410a** [comment]
Of course, which file do you need?

**Comment by thangvo9x** [comment]
Hi, the AppConfig.json file. Thanks

**Comment by thangvo9x** [comment]
Hi. Try this solution. Your issue will be resolved. 
https://github.com/WP-API/WP-API/issues/2578
Thanks

**Comment by bfwi410a** [comment]
@thangvo9x no, i have added a new custom field for listing content with plain text without VC shortcodes. In listing details and reviews are no vc. That's another problem.

In your Demo App "ListApp" on Appstore still the same issue.

![Image-1](https://user-images.githubusercontent.com/1284361/58613647-9a8b7400-82b6-11e9-9ab3-38545737c1ee.jpg)

**Comment by minhcasi** [comment]
@thangvo9x - we can upgrade the comment render by using the html-render component to resolve this problem

 - mark this ticket as 'feature request'

**Comment by minhcasi** [comment]
Related with #658
