### ISSUE TITLE
[mStore Pro] - Checkout Issue, trying to add CSS to template to fix it.

### ISSUE THREAD

**Issue by sashaba** [inspireui/support#654]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - Try to explain your all problems in one ticket, instead of creating multi tickets 

---------

1. My issue

Hello Support
So, I'm here again for checkout issues, the app is amazing, this is so far the best react native app I've seen until you get to the checkout screen. The checkout is really buggy. The checkout plugin need a lot of customization.
If you integrate just PayPal and Stripe as in-app checkout it will be amazing, many many many users will be satisfied. If someone needs a different payment method they can use the new affiliate featured.
So MY ISSUE IS: 
My website mobile header is interrupting the checkout( at least is what I think it is)
I'm trying to add some css to plugins > mstore-checkout>assets>*.css  to hide the mobile header at checkout but nothing works. I know I'm using the correct code because I'm using it on my other checkout plugin and it works perfectly fine. But for some reason the custom css added to the asset folder of the plugin isn't working.  Watch VIDEO BELOW.

2. Screenshots
Video attached below.

3. Config files (optional)
This is the css I'm trying to add.

#kad-mobile-banner-sticky-wrapper {
display: none;
}

Your Purchased Code:4bb2fd9b-4a08-4e19-9c74-fc95f51533e7

**Comment by sashaba** [comment]
`<div style="padding:177.78% 0 0 0;position:relative;"><iframe src="https://player.vimeo.com/video/338961619?autoplay=1&loop=1" style="position:absolute;top:0;left:0;width:100%;height:100%;" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe></div><script src="https://player.vimeo.com/api/player.js"></script>
<p><a href="https://vimeo.com/338961619">3711A688-D2B6-4559-BC3B-E5DB489262D1</a> from <a href="https://vimeo.com/user99060463">Sasha Bauer</a> on <a href="https://vimeo.com">Vimeo</a>.</p>`

**Comment by sashaba** [comment]
i Changed my wordpress theme and the issue persists. 
With Storefront theme the header doesn't bother but the page still flashing And won't complete checkout.

**Comment by minhcasi** [comment]
Hi @sashaba - we will have a check and keep an update - thank you!

**Comment by minhcasi** [comment]
Hi @sashaba - could you help to attache your config file (common/config.js and appconfig.json) here, our team try to reproduce from our 2 testing site but it's working fine on Android, it could be something related to your website, but we are not pretty sure, need to have some debugging - thanks

**Comment by sashaba** [comment]
Please find attached the requested files.
[AppConfig.json.txt](https://github.com/inspireui/support/files/3243366/AppConfig.json.txt)
[config.js.txt](https://github.com/inspireui/support/files/3243367/config.js.txt)

i added .txt extension to upload them here. i didnt know how to upload .Json files here.
Thank you.

**Comment by minhcasi** [comment]
Hi, our Mstore team have noted this issue is fixed, could you help to review and let me know, thank you!
