### ISSUE TITLE
[Listapp] - blog content not display 

### ISSUE THREAD

**Issue by reconshield** [inspireui/support#655]
after all update. now i cant view blog post contents. when click blog post its just display featured image and share button.**.no contents is displa**y..even not **load latest blog**. like when i delete blog post from wp admin panel.i still can see it in app. still after restart my app. this issue after we update latest file in app/common/Tools.js .. pls advice..

**Comment by bfwi410a** [comment]
In Tools.js Change Line 143

  static async getFontSizePostDetail() {
    const data = await AsyncStorage.getItem(
      Constants.storageName.settingFontSize
    )

to this 

static async getFontSizePostDetail() {
    const data = await AsyncStorage.getItem('@setting_fontSize')

**Comment by reconshield** [comment]
ohh great @bfwi410a ..working fine now..but..i still can see old blog post..its not refresh..i already delete that blog post from wordpress.. any idea on that?
