### ISSUE TITLE
[Listapp] Listing Submit - can not connect to server" error

### ISSUE THREAD

**Issue by reconshield** [inspireui/support#656]
when i try to Submit listing via listapp i get server connection error. i assign user role to Vendor. 
after add details. choose image..content and click summit button i get "**can not connect to server**" error. please advice.

![Simulator Screen Shot - iPhone X - 2019-05-29 at 14 41 10](https://user-images.githubusercontent.com/25501496/58535353-5b124880-8220-11e9-9d34-cdaafd066a49.png)

**Comment by thangvo9x** [comment]
You can refer here 
https://docs.inspireui.com/listapp/troubleshooting/
Hint: 
1. Check config JWT plugins at the .htaccess file
2. role when posting data or try logout and login

**Comment by reconshield** [comment]
i have follow all setiing .. this my .htaccess file and wpconfig file... but i get same error
note : when i post listing, i can see images in gallery... but no data as pending in listing list


# BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule ^(.*) - [E=HTTP_AUTHORIZATION:%1]
SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>

<IfModule mod_headers.c>
  Header set Access-Control-Allow-Origin "*"
</IfModule>
# END WordPress

wpconfig

<?php

define('AUTOSAVE_INTERVAL', 86400);

// ** MySQL settings - You can get this info from your web host ** //
/** The name of the database for WordPress */
define('DB_NAME', 'xxxxxx');

/** MySQL database username */
define('DB_USER', 'xxxxxxx');

/** MySQL database password */
define('DB_PASSWORD', 'xxxxxxx');

/** MySQL hostname */
define('DB_HOST', 'localhost');

/** Database Charset to use in creating database tables. */
define('DB_CHARSET', 'utf8');

/** The Database Collate type. Don't change this if in doubt. */
define('DB_COLLATE', '');

define('JWT_AUTH_SECRET_KEY', '/gk9&xI47Uh}Gnxk08?j|-VsC]p,(<S!n3%!- Exgl*26OAye@(k8~s;WX l*O;h');

define( 'WP_MEMORY_LIMIT', '256M' );

define('JWT_AUTH_CORS_ENABLE', true);
/**#@+
 * Authentication Unique Keys and Salts.
 * Change these to different unique phrases!
 * You can generate these using the {@link https://api.wordpress.org/secret-key/1.1/salt/ WordPress.org secret-key service}
 */
require('wp-salt.php');

$table_prefix  = 'wp_';

define('FS_METHOD','direct');
define('WPLANG', '');
define('FS_CHMOD_DIR', (0775 & ~ umask()));
define('FS_CHMOD_FILE', (0664 & ~ umask()));

define('WP_DEBUG', false);

/* That's all, stop editing! Happy blogging. */

/** Absolute path to the WordPress directory. */
if ( !defined('ABSPATH') )
        define('ABSPATH', dirname(__FILE__) . '/');

/** Sets up WordPress vars and included files. */
require_once(ABSPATH . 'wp-settings.php');

**Comment by thangvo9x** [comment]
Only editor/admin role was be posted a new listing.
the .htaccess file was fixed.
[htaccess.txt](https://github.com/inspireui/support/files/3236564/htaccess.txt)

**Comment by reconshield** [comment]
i have set user role to editor. refreshed logging. then i update .htaccess file... 
But im getting same error. " can not connect to server " .. pls advice..

**Comment by thangvo9x** [comment]
Hi. Could you share the AppConfig.json to me?

**Comment by reconshield** [comment]
[AppConfig.txt](https://github.com/inspireui/support/files/3239412/AppConfig.txt)

**Comment by reconshield** [comment]
User role assigned to editor
.htaccess file updated. But im getting same error :/
-- 


  If you have any enquiries, please do not hesitate to contact us. Thank
You!

   Best Regards,


Customer Service, Reconshield Network

Website: reconshield.com <https://www.reconshield.com>  |  Helpdesk:
sales@reconshield.com
<https://www.facebook.com/reconshield> <https://twitter.com/suthesan>
<https://www.instagram.com/suthesan>


Confidentiality Warning: This e-mail message may contain confidential,
proprietary
or legally privileged information. It should not be accessed by anyone who
is not the original intended recipient. If you have erroneously received
this message, please delete it immediately and notify the sender. You will
appreciate that e-mail transmission cannot be guaranteed to be secure or
error-free as its contents are susceptible to loss, damage, interception,
destruction, etc. Before opening any attachments please check them for
viruses and defects.

If you don't wish to receive emails from us reply back with "Leave Out".

*Kindly consider the environmental impact before printing this email.*

**Comment by thangvo9x** [comment]
Hi. @reconshield . Try update this plugin. i saw this problem on your website. 
https://github.com/inspireui/mstore/blob/master/plugins/json-api/json-api.php

**Comment by reconshield** [comment]
just replace json-api.php  .. php file ?

**Comment by reconshield** [comment]
Working fine..
