### ISSUE TITLE
[Mstore pro] - How can I change format phone checkout?

### ISSUE THREAD

**Issue by saeidAalizade** [inspireui/support#657]
purchased code :
153bb1ff-3f3e-41cd-a219-da061397aef5

product name :
Mstore pro

My issue:

hi support 
How can I change format phone checkout?
default : (99) 9999-9999
I want to be this way : 99999999999

**Comment by minhcasi** [comment]
Hi, you can replace the input mask by normal text input - pls check this screenshot - https://tppr.me/DMJs2

File: Containers/Cart/Delivery/index.js
