### ISSUE TITLE
Short solution for rendering Visual Composer Shortcodes

### ISSUE THREAD

**Issue by bfwi410a** [inspireui/support#658]
@minhcasi please add this in your documentation for other user which have same problem.

I had problems by using Visual Composer. Rest-Api does not render shortcodes and show them in app. To solve this problem do following:

Add this code block to your theme's function.php

`add_action( 'rest_api_init', function ()
{
   register_rest_field(
          //If you need, add more taxonomy to array. In my case it's "posts, pages and job listings". All you use VC.
          array('post','page','job_listing'),
          'content',
          array(
                 'get_callback'    => 'compasshb_do_shortcodes',
                 'update_callback' => null,
                 'schema'          => null,
          )
       );
});

function compasshb_do_shortcodes( $object, $field_name, $request )
{
   WPBMap::addAllMappedShortcodes();
   global $post;
   $post = get_post ($object['id']);
   $output['rendered'] = apply_filters( 'the_content', $post->post_content );
   return $output;
}`

**Comment by minhcasi** [comment]
@bfwi410a - appreciated for your sharing with detail solutions 😍

**Comment by minhcasi** [comment]
@thangvo9x - pls help to update the document

**Comment by thangvo9x** [comment]
Updated
