### ISSUE TITLE
[ListApp] - Help with ListApp Can´t even start

### ISSUE THREAD

**Issue by Nachbarsaft** [inspireui/support#66]
I´m really new to this and I try to follow your guide (https://inspireui.github.io/listapp/docs/quickstart) very closely. But I get this error, when I try to start a test project. What do I have to do? I´m stuck with Step one so far.

C:\Users\rschl>expo init
? Choose a project name: your-next-project
? Choose a template: expo-template-blank
[04:27:12] Extracting project files...
[04:27:13] Customizing project...
[04:27:13] Installing dependencies...
npm ERR! code ENOGIT
npm ERR! Error while executing:
npm ERR! undefined ls-remote -h -t ssh://git@github.com/expo/react-native-maps.git
npm ERR!
npm ERR! undefined
npm ERR! No git binary found in $PATH
npm ERR!
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rschl\AppData\Roaming\npm-cache\_logs\2018-11-30T03_27_30_340Z-debug.log
[04:27:30] Process exited with non-zero code: 1
[04:27:30] Set EXPO_DEBUG=true in your env to view the stack trace.

**Comment by Nachbarsaft** [comment]
I purchased MyList APp on Envato 29th/11 purchase code ends with: 49bc14f56289  (don´t want to publically post the whole number here)

**Comment by Nachbarsaft** [comment]
yes you can, just tell me how and when. Thank you!

**Comment by thangvo9x** [comment]
Hi. Good morning, Nachbarsaft. Do you have free, now ? send your teamview id to thang@beostore.io
Thanks.

**Comment by Nachbarsaft** [comment]
Ive sent you an email
thx!

**Comment by thangvo9x** [comment]
Hi. I didn't receive it . Resend it, please. 
Thanks

**Comment by Nachbarsaft** [comment]
This is what I sent :


Hi Thang,

sorry you texted me in the middle of the night last time. Can we agree on a fixed time to do this. It´s better to plan because of the time difference.

This is my Team Viewer ID: 1 120 419 603

Thank you!



________________________________
Von: thangvo9x <notifications@github.com>
Gesendet: Monday, December 10, 2018 5:36:35 AM
An: inspireui/support
Cc: Nachbarsaft; Author
Betreff: Re: [inspireui/support] [ListApp] - Help with ListApp Can´t even start (#66)


Hi. I didn't receive it . Resend it, please.
Thanks

**Comment by minhcasi** [comment]
Hi, @Nachbarsaft  please share your team viewer account to @thangvo9x email from 9:am-5pm GMT+7

Closed ticket to support via email, thanks

**Comment by Nachbarsaft** [comment]
Hello Thang, now I hope I have the Right Timing.

Here is my Team Viewer ID:

1 120 419 603

I would appreciate if you could help me.

Raphael

________________________________
Von: thangvo9x <notifications@github.com>
Gesendet: Monday, December 10, 2018 5:36:35 AM
An: inspireui/support
Cc: Nachbarsaft; Author
Betreff: Re: [inspireui/support] [ListApp] - Help with ListApp Can´t even start (#66)


Hi. I didn't receive it . Resend it, please.
Thanks
