### ISSUE TITLE
[Mstore Pro] - Can't make a build React Native Restart

### ISSUE THREAD

**Issue by davekedar** [inspireui/support#660]
![image](https://user-images.githubusercontent.com/11268363/58682126-004a2f80-838d-11e9-8028-be004021c958.png)

Purchased Code: f9eaf46b-d573-484d-945f-4236e184eeaf
versoin : 3.8.0

**Comment by minhcasi** [comment]
Hi, can you try with this script:

`yarn add react-native-restart
react-native link react-native-restart`
