### ISSUE TITLE
[ Mstore ] - Issue on intro,icon and sync

### ISSUE THREAD

**Issue by santhosh2210** [inspireui/support#661]
**Issue 1 :** Intro screen issue on full screen mobile( like a NOTE 7 Pro ) 
First three Intro screen issue on full screen mobile like note 7 pro...
Intro color are not full fill the bottom navigation in full screen mobile...so please tell us custom css in mstore app..
See the Screenshot -> http://prntscr.com/nt62dq

**Issue 2:-** Address are not sync to wp site via facebook login
Shipping address are storing the app....but not sync the wordpress site via facebook login.......
working fine via sign up....
See the screenshot -> http://prntscr.com/nudh2e
please find the error and reply fast

**Issue 3:-** Profile photo in home page right top
I want to display the my profile image on home top right side...
minhcasi reply message - , you can navigate to the Profilescreen when click to that icon - example: https://tppr.me/C1Bsb
This code also use but not working...only display the empty screen...
See the screenshot -> http://prntscr.com/nu8tws
so please change the code and give me...its very important for me...thanks for your reply..

**Comment by minhcasi** [comment]
noted for checking - thanks

**Comment by santhosh2210** [comment]
Very urgent for issue 3...
so please reply fast

**Comment by minhcasi** [comment]
Hi, can you send the zip of your source to our support email - support@inspireui.com - we will help to fix #3 for you

pls done share the zip file here

**Comment by santhosh2210** [comment]
Please check the your inbox...

**Comment by santhosh2210** [comment]
Are you there???...No one reply until today.....please solve

**Comment by minhcasi** [comment]
Hi, can you take the screenshot of your purchased product and let us know your username on Envato?

As the missing proving of our customer, we may not support - thanks
