### ISSUE TITLE
[List App] - Menu item with page id won't scroll

### ISSUE THREAD

**Issue by bfwi410a** [inspireui/support#662]
For left menu i use a menu item with page id from wordpress. Page will display but i can't scroll down to see the entire content. Could you explain how to do for scrolling content?

![2019-05-31-09_52_40-Window](https://user-images.githubusercontent.com/1284361/58690974-122ad300-838b-11e9-9e52-29ff7c265ef1.jpg)

**Comment by thangvo9x** [comment]
Hi. Please share the AppConfig.json for checking, plz?

**Comment by bfwi410a** [comment]
Here we go:

[AppConfig.zip](https://github.com/inspireui/support/files/3243560/AppConfig.zip)

**Comment by bfwi410a** [comment]
Any news?

**Comment by thangvo9x** [comment]
Hi try to replace this file at App/Containers/Custompage/
The issue went away.
p.s: Rememer that change from .txt -> .js
[index.txt](https://github.com/inspireui/support/files/3264397/index.txt)

Thanks

**Comment by bfwi410a** [comment]
It works, thx!

**Comment by bfwi410a** [comment]
It works, thx!
