### ISSUE TITLE
BeoNews Pro - Error 65

### ISSUE THREAD

**Issue by kalakgl** [inspireui/support#663]
In Pro edition, the run-ios fails: error Failed to build iOS project. We ran “xcodebuild” command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening beonews.xcodeproj
See attached screen shot.
<img width="1519" alt="Skærmbillede 2019-05-31 kl  14 45 57" src="https://user-images.githubusercontent.com/12363496/58721215-19fe6d80-83b3-11e9-9b8a-dfce8c0a5be6.png">

**Comment by minhcasi** [comment]
Hi, could you try to open the project from ios folder by using XCode and send us the detail log when click to red warning icon - thanks

**Comment by kalakgl** [comment]
Hi

Here is a screen shot:
[cid:image001.png@01D519EB.04937800]

Inuss. inuull. / Venlig Hilsen / Best Regards,
Ulrik Motzfeldt-Skovgaard


Fra: Minh Pham <notifications@github.com>
Svar til: inspireui/support <reply@reply.github.com>
Dato: lørdag den 1. juni 2019 kl. 09.23
Til: inspireui/support <support@noreply.github.com>
Cc: Ulrik Motzfeldt-Skovgaard <ulmo@qeqqata.gl>, Author <author@noreply.github.com>
Emne: Re: [inspireui/support] BeoNews Pro - Error 65 (#663)


Hi, could you try to open the project from ios folder by using XCode and send us the detail log when click to red warning icon - thanks

**Comment by kalakgl** [comment]
No news about this?

**Comment by minhcasi** [comment]
HI @kalakgl, sorry we could not see the attached screenshot above.

Btw, we are going to update the new version with latest RN and Expo on 1-2 days.
