### ISSUE TITLE
[MStore Pro] - Issues with Variable Products and their Variations

### ISSUE THREAD

**Issue by seherkdc** [inspireui/support#664]
**Product**: Mstore Pro v3.8.0

**Purchase Screenshot**: (We would not want to display the purchase code in public)
![mtore-liscence](https://user-images.githubusercontent.com/47523938/58722501-33c0a480-83f5-11e9-9b53-81687f3d8f8e.png)

**Issues:**

1. Variable Product gets added to cart **without** selecting a variation. (Ref Screenshots 1 & 2)

2. All _attributes_; irrespective of "_Used for Variation_" is selected or not; are being used as variations. (Ref Screenshots 1 & 3)

**Screenshots**: 
1. Variable Product with all attributes (No variations selected).
![Screenshot 1](https://user-images.githubusercontent.com/47523938/58723798-97000600-83f8-11e9-83f4-3cbe27fea555.png)

2. Variable product added to cart without any variations.
![Screenshot 2](https://user-images.githubusercontent.com/47523938/58723883-cca4ef00-83f8-11e9-8367-0c3acee65939.png)

3. Variations defined for the product in WooCommerce
![Screenshot 3](https://user-images.githubusercontent.com/47523938/58722829-150edd80-83f6-11e9-951d-737b740a40a3.png)

**Additional context**
Our purchased product is MStore pro but we're using the **mstore-expo** directory.
Kindly help us to resolve the issues.
Thank you!

@inspireui/team @minhcasi

**Comment by minhcasi** [comment]
Hi, could you help to attach the config file (appconfig.json and config.js from common folder), or send to our email support@inspireui.com - we will help for resolving this UI issue - thank you!

**Comment by seherkdc** [comment]
Hi @minhcasi,
I have sent both the files on support@inspireui.com.
Thank you for the quick response.

**Comment by seherkdc** [comment]
Hi @minhcasi,
Can you please integrate a dropdown select for the product variations?

**Comment by seherkdc** [comment]
Hi @minhcasi @concuacon 
Any update on my issue?

**Comment by minhcasi** [comment]
@seherkdc we will upgrade the product variants as the bottom sheet, this will include on next release in 1-2 weeks - thank you!

**Comment by seherkdc** [comment]
@minhcasi Appreciate your response. Eagerly awaiting your resolution at the earliest as the project has been stalled because of this. 

Hoping https://github.com/inspireui/support/issues/664#issuecomment-498135143 would also be considered in your resolution.

**Comment by seherkdc** [comment]
Hi @minhcasi 
Any update on the issue?

**Comment by minhcasi** [comment]
Hi, we will include this fix on next version release on this week, including with the latest RN and Expo - thanks

**Comment by minhcasi** [comment]
Hi, we have updated latest 3.9.0 to fix the variant issues, please help to check on your site - thank you!
