### ISSUE TITLE
[Listapp] Facebook login issue with 1.7.1 

### ISSUE THREAD

**Issue by reconshield** [inspireui/support#665]
i dont get any fb login issue in previous version .when using 1.7.1 log in using facebook i get this error...i **dont have** same email user in my wordpress user list. 

![Simulator Screen Shot - iPhone X - 2019-06-01 at 10 45 47](https://user-images.githubusercontent.com/25501496/58742910-e840e180-845a-11e9-958d-55527b5647ef.png)

**Comment by thangvo9x** [comment]
Hi. Check that user on your firebase app.
Thanks

**Comment by reconshield** [comment]
ohh ok..thanks..solved..thanks alot :)
