### ISSUE TITLE
[Mstore pro] how to i can changes content posts font?

### ISSUE THREAD

**Issue by saeidAalizade** [inspireui/support#667]
purchased code :
153bb1ff-3f3e-41cd-a219-da061397aef5

product name :
Mstore pro

My issue:
how to i can changes content posts font? 
I changed all fonts in app , But I can not change the content of the content

![screen](https://user-images.githubusercontent.com/41091634/58748051-9adb6900-8488-11e9-8ebc-e1d6d9cbb4a0.jpg)

**Comment by minhcasi** [comment]
Hi, you can customize the content style from components/webview/index.js
