### ISSUE TITLE
[Mstore pro] - I do not show shipping type 

### ISSUE THREAD

**Issue by saeidAalizade** [inspireui/support#668]
purchased code :
153bb1ff-3f3e-41cd-a219-da061397aef5
product name : Mstore pro

My issue:
hi support
I do not show shipping type in checkout page app ):
Where do you think I'm wrong?
The shipping type is defined in woocommerce

**Comment by minhcasi** [comment]
could you help to see if the shipping option is enabled - https://tppr.me/EIS1c - thank you -

**Comment by saeidAalizade** [comment]
> could you help to see if the shipping option is enabled - https://tppr.me/EIS1c - thank you -
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/e32bcf68f2dfc0a998a3223cd9b24cdbf3877309/68747470733a2f2f747070722e73332e616d617a6f6e6177732e636f6d2f75706c6f6164732f31373563343438353934313961643532653538303966666163663930306565302e706e67"><img alt="" height="14" src="/favicon-32x32.png"> tppr.me**[Public Screenshots - Code_2019-06-03 17-03-39](https://tppr.me/EIS1c)**

yes enabled

**Comment by minhcasi** [comment]
Hi, sorry for missing this issue, could you help to attach the config files here (common/appconfig.json and config.js)? 

This could relate to this issue - https://docs.inspireui.com/mstore/questions/#404-error-page-when-process-the-payment-
