### ISSUE TITLE
[MStore] - build apk error

### ISSUE THREAD

**Issue by tharicode** [inspireui/support#67]
**Required Info (please complete the following information):**
 - Product: [e.g. MStore, ListApp]
 - Your Purchased Code: [get from https://codecanyon.net/downloads]
(we may not reply if you are not our customer)

**Describe the bug**
i run my mstore project on android studio perfectly . but i build apk and run it in my phone and bluestack(in windows) .error massage coming below picture

**Screenshots**
![android](https://user-images.githubusercontent.com/45279029/49296980-9d600480-f4df-11e8-9052-4c1daf06547d.PNG)

**Comment by luyx2412** [comment]
Hi @tharicode Please follow the article to fix your issue https://stackoverflow.com/a/44476757/6622971.
Thanks
