### ISSUE TITLE
[Listapp] Bugs - page not refresh

### ISSUE THREAD

**Issue by reconshield** [inspireui/support#670]
After click blog post , click home button. then click categories..click listing..still can view previous blog post and not listing details. page not refresh and display listing. please advice on this.

**Comment by bfwi410a** [comment]
Same problem :-/

**Comment by bfwi410a** [comment]
Any news?

**Comment by thangvo9x** [comment]
Hi. Share the video for this problem

**Comment by reconshield** [comment]
1) When click listing OK..can view
2) When click Listing categories --> listing - No problem
3) when click Blog Post - No problem
4) When click Listing after view blog post, Listing not display.. blog post page is still display - Problem

Video : 
https://youtu.be/uoKPMgvcGmU

**Comment by bfwi410a** [comment]
I have a similiar problem. In left menu i have two custom page items with diferent page id's:

      {
        route: 'customPage',
        params: {
          id: 15287,
          title: 'Impressum',
        },
        name: 'impressum',
        icon: 'assignment',
      },
      {
        route: 'customPage',
        params: {
          id: 15303,
          title: 'Datenschutzerklärung',
        },
        name: 'datenschutz',
        icon: 'assignment',
      },

Both items shows same content until you restart the app. It may be missing a refresh? Please see attached Video. https://www.entwicklung1.de/RPReplay_Final1559977431.MP4

**Comment by thangvo9x** [comment]
@reconshield. I checked. It's work normally. Try to update to the latest version. Thanks

**Comment by masonPy3** [comment]
@thangvo9x 
I have also the same problem with the latest version :/

**Comment by reconshield** [comment]
@thangvo9x  @masonPy3 

i just download latest version and run it. all default setting.i not change anything. .listapp 1.7.1.. --> After Click Blog Post, Back Home..then click Listing, blog post is display not listing...

i have attached video recording. Simulator : Mac/iphone x.   pls advice..

https://youtu.be/dEiGIPJfSz4

**Comment by masonPy3** [comment]
@thangvo9x  @reconshield 
It's only on simulator, I checked yesterday on live version and it works fine..
I'm having the same problem only on simulator

**Comment by reconshield** [comment]
yes..correct..its working fine in live version.i just check using testflight...thanks @thangvo9x ..
