### ISSUE TITLE
[ListApp] Disable Booking Feature

### ISSUE THREAD

**Issue by masonPy3** [inspireui/support#672]
Hello, I want to disable Booking Feature because I don't want payment inside my app,
Instead, I would like users to contact on the phone instead of booking,
How can I do that?
Thanks

**Comment by reconshield** [comment]
go App/Common/Config/index.js

Line 30. from true change to false.

Booking: {
    enable: false,
  },

**Comment by thangvo9x** [comment]
> go App/Common/Config/index.js
> 
> Line 31. from true change to false.
> 
> Booking: {
> enable: false,
> },

Thanks @reconshield . @masonPy3 You can refer here.

**Comment by masonPy3** [comment]
Yeah saw it, sorry for not closing it..
