### ISSUE TITLE
ListApp - Some listings shows twice after "load more"

### ISSUE THREAD

**Issue by bfwi410a** [inspireui/support#673]
On first screen (explore) i show my paid premium listings in slider wich have type id = 3270.
      {
        component: listing,
        name: 'Premium Partner',
        types: '3270',
        layout: Constants.Layout.column,
      },

If you click on headline 'Premium Partner' you can see all premium listings. At once the view shows 10 listings. After load more (swipe up or down) next listings will be load. After that, some listings shows twice. See screenshot below. How to show correct amount of listings wthout double listings and is there any posibility to show an indicator that customer knows he can load more litings by swipe up or down? Another thought: How can i increase the value of 10 listings or posts to e.g. 50 at once?

![IMG_7635](https://user-images.githubusercontent.com/1284361/58800706-d2711f00-8608-11e9-842c-ea1bd6690bad.jpg)

**Comment by bfwi410a** [comment]
Any news?

**Comment by thangvo9x** [comment]
Please share AppConfig.json for checking

**Comment by bfwi410a** [comment]
Here we go: 
[AppConfig.zip](https://github.com/inspireui/support/files/3264904/AppConfig.zip)

**Comment by thangvo9x** [comment]
Have you been an update to the latest version of the app? 
I checked on your AppConfig. Try to test here. https://your-domain/wp-json/wp/v2/job_listing?_embed=true&job_listing_type=3270&page=2&per_page=10&status=publish
Notice to the param page..

**Comment by bfwi410a** [comment]
I think so.  I bought on 18 May 19 via codecanyon. Scince this date there is no new release, correct? Now i have created a new categorie for premium partners and use categorie id in stead of type id this works fine.
