### ISSUE TITLE
[ListApp] - typeId is NOT working with MyListing

### ISSUE THREAD

**Issue by michaelvicente** [inspireui/support#674]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - Try to explain your all problems in one ticket, instead of creating multi tickets 

---------

1. My issue

I want to show based on Listing Type but it is not working. I used typeId but no luck. See attached Screenshot.

2. Screenshots
<img width="1004" alt="Screen Shot 2019-06-03 at 10 16 14 PM" src="https://user-images.githubusercontent.com/3995963/58850806-3c131c80-864d-11e9-92c4-fb0fa88fc1c6.png">

3. Config files (optional)

[MyListing.txt](https://github.com/inspireui/support/files/3250483/MyListing.txt)

**Comment by thangvo9x** [comment]
Hi. Could you provide your purchase code & sharing your domain url?

**Comment by michaelvicente** [comment]
> Hi. Could you provide your purchase code & sharing your domain url?

Hi, where should I send these details? I don't want to share it here. Thanks!

**Comment by minhcasi** [comment]
noted, @thangvo9x pls help to support

**Comment by thangvo9x** [comment]
Please share your domain for checking?

**Comment by michaelvicente** [comment]
URL: http://bit.ly/wintercityapp

**Comment by thangvo9x** [comment]
Hi. Try to change from using typeId -> types. Thanks

**Comment by michaelvicente** [comment]
Hi @thangvo9x, I tried using Types but it doesn't work.

**Comment by minhcasi** [comment]
@michaelvicente  - could you share your whole config file (common/config.js and common/appConfig.json) - we will help to check the Type id on your site - thanks

**Comment by michaelvicente** [comment]
> @michaelvicente - could you share your whole config file (common/config.js and common/appConfig.json) - we will help to check the Type id on your site - thanks

Can I send it to your email?

**Comment by thangvo9x** [comment]
Hi bro, your problem is resolved?
