### ISSUE TITLE
[ListApp] Default RTL and Currency Sign

### ISSUE THREAD

**Issue by masonPy3** [inspireui/support#675]
Hello, how do I set RTL as default? because my rtl language is selected when I start the app but the style isn't.. only if I reselect the rtl language the style changes..
Also, How can I change my currency name to symbol? it writes ILS instead of the currency symbol..
Thanks

**Comment by masonPy3** [comment]
Plus where can I get the flag code?
http://prntscr.com/nxchxd
Thanks

**Comment by thangvo9x** [comment]
> Plus where can I get the flag code?
> http://prntscr.com/nxchxd
> Thanks
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/af52f57fe32f52acb2359b1e94a69b787cc910d1/68747470733a2f2f696d6167652e70726e747363722e636f6d2f696d6167652f6f374d397a5968665434614c5274754c6a6e41694a772e706e67">Lightshot**[Screenshot](https://prnt.sc/nxchxd)**Captured with Lightshot

you can change by coppying here : https://www.countryflags.com/en/

**Comment by thangvo9x** [comment]
> Hello, how do I set RTL as default? because my rtl language is selected when I start the app but the style isn't.. only if I reselect the rtl language the style changes..
> Also, How can I change my currency name to symbol? it writes ILS instead of the currency symbol..
> Thanks
You can set RTL at App/Common/Constants.js

**Comment by masonPy3** [comment]
1. How do I add it to the app?
2. Changed it to True in constants.js but still it ltr..
3. how can I change the symbol?
Thanks for the response :).

**Comment by masonPy3** [comment]
@thangvo9x  Solution for flag thing:
Go to https://emojipedia.org/ and copy the emoji code and paste.
About the RTL and Currency symbol, I haven't solved yet.

**Comment by thangvo9x** [comment]
You can set RTL at App/Common/Constants.js find key RTL => true, 
The currency will get automatically on your website.

**Comment by masonPy3** [comment]
@thangvo9x  Hi, I've Set it as RTL => true but still, it doesn't change.. :(

**Comment by thangvo9x** [comment]
Try to go to App/Common/Config/index.js 
Find this block Language property and change it to "ar".
Thanks

**Comment by masonPy3** [comment]
@thangvo9x 
I Removed Arabic and changed it to hebrew so my code is 'he',
I already changed it but it still not working mate :/
only if i switch languages it works..

**Comment by thangvo9x** [comment]
Oh this is a minor bug. We'll have an update in the next version. Thanks

**Comment by masonPy3** [comment]
@thangvo9x On live version it works, only on simulator it have problem..
