### ISSUE TITLE
[ListApp] - Chat and Settings Issues

### ISSUE THREAD

**Issue by masonPy3** [inspireui/support#677]
1. When entering chat section in settings i get user.data.user error (configed by guide)
2. My cart and booking sections are blanked after disabled it. I need it to disappear.
3. It shows new user like he uploads all listing.

Screenshots
1. http://prntscr.com/nxuuib
2. http://prntscr.com/nxuu4l
3. http://prntscr.com/nxuubd
3.1 https://prnt.sc/nxuswg

**Comment by masonPy3** [comment]
2. Fixed, edited Container\User\index.js

**Comment by thangvo9x** [comment]
Hi. Could u share AppConfig for checking?

**Comment by masonPy3** [comment]
@thangvo9x  Yes
https://pastebin.com/qsd15FXX

**Comment by masonPy3** [comment]
@thangvo9x  Can you see the hidden comment? I put it there

**Comment by thangvo9x** [comment]
Yup. I saw your comment such as I checked on your AppConfig file.
3. This is a bug. We'll update it in the next version.
1. Try to replace this file at Container/ChatList/
[index.txt](https://github.com/inspireui/support/files/3271193/index.txt)
P/s: Remember that change from .txt -> .js
Thanks

**Comment by masonPy3** [comment]
@thangvo9x works! Thanks!
and about the other the first one?

P.S - When you release update, can you mention with files you've changed? so we could compare it with our version? since we customized the template.
Thanks again

**Comment by masonPy3** [comment]
3. Works fine on live version. (not on simulator)
Thanks
