### ISSUE TITLE
[ListPro - Listing Directory React Native template] - Booking date error and Events not loading

### ISSUE THREAD

**Issue by roger-hope** [inspireui/support#679]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - Try to explain your all problems in one ticket, instead of creating multi tickets 

---------

1. My issue
Hi, Thanks for the good work on both the App and the Wordpress site. I purchased both, but now I am running into a few problems. It might be a simple backend setting, I don’t know yet. (1) In the App when testing it on Android through Expo, I receive an error when I click any date on the calendar for a booking. (2) In both the App and Wordpress, how do I activate the Events listing/component? When I create an event it is not displayed. I look forward to your response.

2. Screenshots
![Screenshot_errorIMG1_2019-06-05-21-57-48](https://user-images.githubusercontent.com/22624734/58987026-eb332d80-87de-11e9-83b9-5983e244eb30.jpg)
![Screenshot_errorIMG2_2019-06-05-21-58-25](https://user-images.githubusercontent.com/22624734/58987027-eb332d80-87de-11e9-9dac-8e34742502ee.jpg)

3. Config files (optional)
Website with the events page: a log file showing the error displayed. The content on the page is not displayed.
[Website_EventsEntryPage_blankError.log](https://github.com/inspireui/support/files/3258870/Website_EventsEntryPage_blankError.log)

**Comment by thangvo9x** [comment]
Hi. Could u share AppConfig for checking to this problem, plz?

**Comment by roger-hope** [comment]
Hi, Do you mean the "AppConfig.json" file located under "App/Common/"?

**Comment by roger-hope** [comment]
In my ticket I also ask why the events are not listed in both the app and wordpress site? How do I activate it or get it to work?

**Comment by thangvo9x** [comment]
Hi. Could you share AppConfig.json in App/Common folder for checking? 
You must have step by step these step.
https://docs.inspireui.com/listapp/quick-setup/
Thanks

**Comment by roger-hope** [comment]
Hi, Please don't close this ticket yet. Could you send me the Config file please. I followed all the steps. In the instructions you make reference to this: To test our app demo website, you can copy the content from App/Common/AppConfig_xxx.json and override the content of AppConfig.json
Example: the AppConfig_MyHome.json is the app demo for https://myhome.inspireui.com

The Restaurant and Classic config files contain this: 
{
    "Website": {
      "url": "http://restaurant.inspireui.com",
      "consumerKey": "ck_23d3372ffecbe925f07872c5261ddd78d1ea00d3",
      "consumerSecret": "cs_0b0ff89a8f8a231fe7351c1926fb8051095abf14"
    },
    "Theme": "restaurant",
    "MainColor": {
      "tabbarTint": "rgb(27, 229, 141)",
      "tabbarColor": "#D5D8DE",

      "mainColorTheme": "#D5D8DE",
      "tabbar": "#D5D8DE"
    }
}
