### ISSUE TITLE
Node Standard Library Error

### ISSUE THREAD

**Issue by EditCode** [inspireui/support#680]
Getting this error when running on expo client

The package at "node_modules/htmlparser2/lib/WritableStream.js" attempted to import the Node standard library module "buffer". It failed because React Native does not include the Node standard library. Read more at https://docs.expo.io/versions/latest/introduction/faq/#can-i-use-nodejs-packages-with-expo

**Comment by minhcasi** [comment]
1. could you take a screenshot of your purchased product
2. And also the screenshot of the whole screen of error logs
