### ISSUE TITLE
[mstore-multi-vendor] -  facebook login invalid scopes user_friends

### ISSUE THREAD

**Issue by selasegithub** [inspireui/support#682]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - Try to explain your all problems in one ticket, instead of creating multi tickets 

---------
Hi. 
1. My issue
Facebook login fails on the multivendor app with the following error per the screenshot.
I have followed all instructions to the letter by creating the app id account from facebook and entering all relevant details as directed.

I checked my facebook app permissions and made sure there is no request for user_friends permission pending

Everything works fine in the web app but not with the mstore multivendor app.
 
2. Screenshots
<img width="248" alt="Screen Shot 2019-06-06 at 15 24 27" src="https://user-images.githubusercontent.com/1086575/59051918-7cf17800-887d-11e9-8236-aa8c494e8767.png">
<img width="1061" alt="Screen Shot 2019-06-06 at 16 53 21" src="https://user-images.githubusercontent.com/1086575/59051919-7cf17800-887d-11e9-9d18-0835bfcf650c.png">

3. Config files (optional)

**Comment by thangvo9x** [comment]
Hi. You can check at Services/FacebookAPI.js. The app config will not need the permission 'user_friends'. The problem is coming from the facebook app. 
Hint: Try to replace with another facebook app.
Thanks

**Comment by selasegithub** [comment]
Hi Thang,
Is this not a case of the MStore app requesting for extra user permissions which aren't activated in facebook app?

**Comment by selasegithub** [comment]
Please see attached below a screenshot from https://docs.mstore.io/advance-customize-app/facebook-config on guide for setting up facebook login in.

If you look closely you would notice user-friends enabled as one of the approved items under login permissions.

Does this not seem to imply that user_friends permissions must be enabled for facebook login to work on MStore Multivendor app.

I'm guessing either that or id have to disable request for that permission from the Mstore app until after my app is complete for review by facebook.

Please do advice.
<img width="726" alt="Screen Shot 2019-06-07 at 11 12 54" src="https://user-images.githubusercontent.com/1086575/59100521-d1e0cd00-8915-11e9-843b-8d0904595244.png">


Thank you.

**Comment by thangvo9x** [comment]
Try to remove all user_friends related. Try to follow the link document guide as your screenshot.
