### ISSUE TITLE
[Mstore] - Stripe payment redirect issue

### ISSUE THREAD

**Issue by santhosh2210** [inspireui/support#683]
[Mstore] - Stripe payment redirect issue

I dont want redirect payment gateway page.......stripe payment transaction are successful in my order page....

[WhatsApp-Video-2019-06-07-at-12.10.01-PM.zip](https://github.com/inspireui/support/files/3264730/WhatsApp-Video-2019-06-07-at-12.10.01-PM.zip)

**Comment by santhosh2210** [comment]
Stripe Payment are not working...please reply

**Comment by minhcasi** [comment]
Hi, can you take the screenshot of your purchased product and let us know your username on Envato?

As the missing proving of our customer, we may not support - thanks
