### ISSUE TITLE
MStore Pro - wordpree plugin download

### ISSUE THREAD

**Issue by ittiwutw** [inspireui/support#684]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. I try to setup wordpress but I can't find "Mstore CheckOut Plugin and API" Plugin

**Comment by minhcasi** [comment]
pls download it from this link https://github.com/inspireui/mstore-checkout/blob/master/mstore-checkout.zip - thanks
