### ISSUE TITLE
[cestore] - Please approve Refund on Envanto

### ISSUE THREAD

**Issue by s3665959** [inspireui/support#685]
Product: [cestore]
Item Purchase Code:
43fdac4f-37a3-4414-9687-c850d0******

Refund request ID
76402c00-ffaa-4cdc-b2ab-1501c1c748a4

I would like to get a refund on cestore , alot of problem to install. I cannot get this cestore to work. Problem with new product feed. the document is unclear and incomplete.   Your supporter is not helping me . I have make request refund on envanto.
Please approve it
thank you @minhcasi

**Comment by minhcasi** [comment]
approved your request - thanks
