### ISSUE TITLE
ListApp iPhoneX view

### ISSUE THREAD

**Issue by bfwi410a** [inspireui/support#686]
Hi,
in Container "CustomPage", and "Login" there must be a margin top on iPhoneX. See screenshots below. Could explain how to fix please?
regards

**Comment by thangvo9x** [comment]
Could you share Appconfig and your static page id for checking?

**Comment by bfwi410a** [comment]
Thx, please use static page id 15287 or 15303.
[AppConfig.zip](https://github.com/inspireui/support/files/3272684/AppConfig.zip)

**Comment by thangvo9x** [comment]
Which phone do you check? i checked on your iPhone X. It's work normal. 
<img width="483" alt="Screen Shot 2019-06-11 at 10 36 08 AM" src="https://user-images.githubusercontent.com/23457178/59242212-e930fa80-8c34-11e9-93fb-9a8e08640bc8.png">

**Comment by bfwi410a** [comment]
I dont't know why. I try iOS iPhone X simulator and real iPhone X device. Is there any new version since codecanyon download on 20 May 19?

<img width="502" alt="Bildschirmfoto 2019-06-11 um 09 01 37" src="https://user-images.githubusercontent.com/1284361/59251026-1aa3c900-8c29-11e9-8f0b-889630a1b4fa.png">

![IMG_20190611_090714](https://user-images.githubusercontent.com/1284361/59251128-58085680-8c29-11e9-87cc-53434cbd0c40.jpg)

**Comment by thangvo9x** [comment]
No. We haven't any update for this app since May 20th

**Comment by bfwi410a** [comment]
I think it's a bug. In source\App\Common\Config\index.js change left menu style from overlay to smale. Now you can reproduce Bug:

  //LeftMenuStyle: Constants.LeftMenu.overlay,
  LeftMenuStyle: Constants.LeftMenu.smale,

Please update in next release.
