### ISSUE TITLE
[listapp] - Get the field Twitter 

### ISSUE THREAD

**Issue by hcwebadvies** [inspireui/support#688]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue
the address does not show on the listingdetails page. Also Twitter does not show. Also I would like to add the other social media from the MyListing Theme but only twitter is menioned in the listingdetails.js of Listapp

I am using the latest version of MyListing and also the latest version of Listapp

2. Screenshots
![address missing in detail listing](https://user-images.githubusercontent.com/51518320/59152148-a0175580-8a3e-11e9-8175-82e804e1f203.jpg)

3. My screenshot of the purchase product or my comment:
![proof of purchase](https://user-images.githubusercontent.com/51518320/59152175-79a5ea00-8a3f-11e9-9780-4fceb583edeb.png)

3. Config files (optional)
I suspect it is in this section of code from listingdetail.js:
        <View style={styles.boxInfo}>
          {location != '' && (
            <TouchableOpacity style={styles.row} onPress={this.openMap}>
              <Image style={styles.imageIcon} source={Images.icons.iconPin} />
              <Text style={styles.label}>{Languages.Address}</Text>
              <Text style={styles.text} numberOfLines={2}>
                {location}
              </Text>
            </TouchableOpacity>
          )}

          {post.job_hours != '' && (
            <View style={styles.row}>
              <Image style={styles.imageIcon} source={Images.icons.iconTime} />
              <Text style={styles.label}>{Languages.open}</Text>
              <Text style={styles.text}>
                {post.job_hours != '' &&
                  Tools.getDescription(post.job_hours, 400)}
              </Text>
            </View>
          )}

          {phone != '' && (
            <TouchableOpacity
              activeOpacity={0.9}
              onPress={() => this.openPhone(phone)}
              style={styles.row}>
              <Image style={styles.imageIcon} source={Images.icons.iconPhone} />
              <Text style={styles.label}>{Languages.tel}</Text>
              <Text style={styles.text}>{phone}</Text>
            </TouchableOpacity>
          )}

          <View style={styles.line} />

          {twitter != '' && (
            <TouchableOpacity
              activeOpacity={0.9}
              onPress={() => this.openTweet(twitter)}
              style={styles.row}>
              <Image style={styles.imageIcon} source={Images.icons.iconTweet} />
              <Text style={styles.label}>{Languages.twitter}</Text>
              <Text style={styles.text}>{twitter}</Text>
            </TouchableOpacity>
          )}

          {website != '' && (
            <TouchableOpacity
              activeOpacity={0.9}
              onPress={() => this.openWebsite(website)}
              style={styles.row}>
              <Image style={styles.imageIcon} source={Images.icons.iconWeb} />
              <Text style={styles.label}>{Languages.website}</Text>
              <Text style={styles.text}>{website}</Text>
            </TouchableOpacity>
          )}
        </View>

**Comment by minhcasi** [comment]
verified - https://tppr.me/EeHFK

**Comment by hcwebadvies** [comment]
Hi,

I got the address issue sorted out. In ListingDetail.js I changed:

const location = post.job_location
to:
const location = post.displayAddress

result:

![address shows correct](https://user-images.githubusercontent.com/51518320/59158333-0c369f80-8ab9-11e9-8b36-e53d202e670e.jpg)


still cannot get the twitter to show, but I noticed that the rest-api shows:

"
_social-networks | ""
-- | --
_links |  
0 |  
network | "Facebook"
url | "#"
1 |  
network | "Twitter"
url | "#"
"
I don't see where the app grabs that from MyListing.

regards,

Haime Croeze

**Comment by thangvo9x** [comment]
Could you share the AppConfig for checking?

**Comment by hcwebadvies** [comment]
Hi,

my website is https://www.akinosta.com (as stated in my appconfig.json). Do you need the consumer keys also?

Haime

**Comment by thangvo9x** [comment]
Try to replace this file at App/Theme/myListing/data
[Post.txt](https://github.com/inspireui/support/files/3271218/Post.txt)
P/s: Remember that change from .txt -> .js.
Thanks

**Comment by hcwebadvies** [comment]
Great, that works now. Only issue is that (same as e.g. Website) it should not show label on detail listing when it is empy. How do I achieve that?

![showing twitter label whilst no twitter account present](https://user-images.githubusercontent.com/51518320/59186904-57fa4f00-8b74-11e9-8762-0ea96ea66b8a.jpg)

**Comment by hcwebadvies** [comment]
Also, how to achieve the same for: Facebook, LinkedIn, Instagram?

**Comment by thangvo9x** [comment]
Hi. you can find this block and add more fields...
<img width="593" alt="Screen Shot 2019-06-10 at 4 47 45 PM" src="https://user-images.githubusercontent.com/23457178/59187362-7de91900-8b9f-11e9-9438-0315eaebdc44.png">
Thanks

**Comment by hcwebadvies** [comment]
yes, got it. I am guessing that this always results in true? meaning listing_data._links.length is always not 0? because the item.network is always filled in (Twitter).

Now the label is always shown on the detail listing, even if the item.url is empty

**Comment by thangvo9x** [comment]
Yup: You can change it by code.

**Comment by hcwebadvies** [comment]
Hi, any hint how to change the code to get it correct?

'listing_data._links.length != 0 && listing_data._links.map((item,index) => {item.network == 'Twitter' ? this.twitter = item.url : ''})'

this seems to cause this.twitter always to be item.url thus always to put label "Twitter" on listingdetail even if item.url is null

thank you in advance

**Comment by thangvo9x** [comment]
At the Rest API on your website. you can view what is the network of each that item.
ex.
<img width="346" alt="Screen Shot 2019-06-13 at 9 48 47 AM" src="https://user-images.githubusercontent.com/23457178/59400096-7785b780-8dc0-11e9-9013-fa2be8e5ef82.png">
Thanks
