### ISSUE TITLE
[ Mstore ] - Facebook login not working in TestFlight but working fine in expo 

### ISSUE THREAD

**Issue by santhoniral** [inspireui/support#689]
Envato Username : Manovee

Issue : Facebook login not working in Test Flight but working fine in expo 

please resolve this issue...its very urgent for me

thanks

**Comment by minhcasi** [comment]
can you share the screenshot issue, it could be some missing from your FB app setting, thanks

**Comment by minhcasi** [comment]
Duplicate of #690
