### ISSUE TITLE
[MStore] - shipping method config of Wordpress site

### ISSUE THREAD

**Issue by hammadhassan** [inspireui/support#69]
Product: [MStore]
Purchase Code: f20afe4a-778e-4089-bcb2-7ec1bb4ed49b

Can you help me to configure WordPress site's shipping method as shipping is not displaying in my app's delivery page.

Kindly Help.

Screenshot & config file is attached.  

[Config3.6.4.zip](https://github.com/inspireui/support/files/2634831/Config3.6.4.zip)

![image](https://user-images.githubusercontent.com/5791268/49312018-95668b80-f504-11e8-8927-7ed0b90ccf24.png)

Shipping is also visible in config file.
![image](https://user-images.githubusercontent.com/5791268/49312137-0443e480-f505-11e8-9594-e01463a6c4bb.png)

**Comment by minhcasi** [comment]
Could you share your admin login private to our support email as well - support@inspireui.com - we will help to have a look to the issue?

**Comment by hammadhassan** [comment]
I did email credentials earlier today.

Please guide me to fix this issue ASAP.

Thanks

**Comment by hammadhassan** [comment]
Please also try to reinstall mstore-checkout plugin as popup view is different as compare to default mstore config.

**Comment by luyx2412** [comment]
Hi @hammadhassan Please follow the image to quick fix the issue. `node_modules/api-ecommerce/src/WooCommerce/WooWorker.js` --> line 247 change `zoneId` `1` to `2`.
<img width="805" alt="screen shot 2018-12-03 at 2 15 34 pm" src="https://user-images.githubusercontent.com/8909619/49358737-51db6f80-f706-11e8-83fc-b19afe260242.png">

We will try update next version soon to fix the issue. 

Thanks

**Comment by hammadhassan** [comment]
Thanks. It's fix my issue.

Could you guys do me a favor & reinstall mstore-checkout plugin on my wordpress site so the checkout popup will be the same as on default config.

Thanks.

**Comment by hammadhassan** [comment]
1 more thing.

I did change the app name in package.json file but mstore still appears in the installation screen.

![image](https://user-images.githubusercontent.com/5791268/49400252-7dda0d80-f765-11e8-9a71-83f8d59859c6.png)


Please guide.

**Comment by minhcasi** [comment]
This is the source for download mstore-checkout - https://github.com/inspireui/mstore/tree/master/plugins/mstore-checkout

You can refer to the document to rename the app name - https://docs.mstore.io/advance-customize-app/change-the-package-name

**Comment by hammadhassan** [comment]
How should i set default country to Netherlands as checkout page keep showing does not ship to Netherlands.

![image](https://user-images.githubusercontent.com/5791268/49466725-94926a00-f822-11e8-886c-44bdc2652bf2.png)

Kindly Help

Config file country setting

 DefaultCountry: {
    code: 'nl',
    RTL: false, // em move config tu ben Constanst qua day de user ho de su dung
    language: 'Dutch',
    countryCode: "NL",
    hideCountryList: false// when this option is try we will hide the country list from the checkout page, default select by the above 'countryCode'
  },
