### ISSUE TITLE
[ Mstore ] - Issue on intro,icon and sync

### ISSUE THREAD

**Issue by santhoniral** [inspireui/support#690]
Envato Username : manovee

Issue 1 : Intro screen issue on full screen mobile( like a NOTE 7 Pro )
First three Intro screen issue on full screen mobile like note 7 pro...
Intro color are not full fill the bottom navigation in full screen mobile...so please tell us custom css in mstore app..
See the Screenshot -> http://prntscr.com/nt62dq

Issue 2:- Address are not sync to wp site via facebook login
Shipping address are storing the app....but not sync the wordpress site via facebook login.......
working fine via sign up....
See the screenshot -> http://prntscr.com/nudh2e
please find the error and reply fast

Issue 3:- Profile photo in home page right top
I want to display the my profile image on home top right side...
minhcasi reply message - , you can navigate to the Profilescreen when click to that icon - example: https://tppr.me/C1Bsb
This code also use but not working...only display the empty screen...
See the screenshot -> http://prntscr.com/nu8tws
so please change the code and give me...its very important for me...thanks for your reply..

**Comment by minhcasi** [comment]
could you help to take a screenshot of your purchased screen as we could not verify base on envato username - thanks

**Comment by santhoniral** [comment]
Please see the screenshot link...thanks

**Comment by santhoniral** [comment]
I will share the my purchase code only on your mail..not share the public forum...so please give me you email address.
http://prntscr.com/nt62dq
http://prntscr.com/nudh2e
http://prntscr.com/nu8tws

**Comment by santhoniral** [comment]
issue 4: Billing address not visible perfextly....alignment error

Screenshot -> 
![Screenshot_1](https://user-images.githubusercontent.com/32481586/59325466-ce2bbc80-8d00-11e9-9637-cbac4ec3d0db.png)


Error video -> [WhatsApp.zip](https://github.com/inspireui/support/files/3279681/WhatsApp.zip)

**Comment by santhoniral** [comment]
i shared to my purchase code on your mail address...so please check the your mail..thanks

**Comment by minhcasi** [comment]
Thank you, could you help to attach your config file as well (from common/appconfig.json and config.js), or zip your source again - we will help to check these issues.

Could you resend the email to support@inspireui.com - thank you!

**Comment by santhoniral** [comment]
please find the error and resolve 

[WhatsApp.zip](https://github.com/inspireui/support/files/3281122/WhatsApp.zip)

**Comment by santhoniral** [comment]
I am using iPhone Xs...Problem are coming in that type model

**Comment by santhoniral** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/32481586/59352282-e66dfc80-8d3d-11e9-8b39-6a102a9687f9.png)

**Comment by santhoniral** [comment]
Waiting for your reply...its very urgent

**Comment by minhcasi** [comment]
Hi, sorry for some delay but we have searched your email from the mailbox and could not verify your purchased -email: santhosh@niralcube.com 

Could you help to take the screenshot from this screen - https://codecanyon.net/downloads - thanks

**Comment by santhoniral** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/32481586/59483194-e5e27c80-8e89-11e9-8041-c4a5c5158dd2.png)
please see the screenshot and help to me

**Comment by santhoniral** [comment]
hellooooooooooooooooooooooo

**Comment by minhcasi** [comment]
Hi, we are checking and will include the fix on next version release on this week, including some latest update of RN & expo - thanks

**Comment by minhcasi** [comment]
Hi, we have updated latest 3.9.0 to fix the variant issues, please help to check on your site - thank you!
