### ISSUE TITLE
[eva-store] - How to detect previous screen showed from screen

### ISSUE THREAD

**Issue by guydoron** [inspireui/support#691]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue

Is there a way to detect the previous screen showed from within a screen container ?

2. Screenshots

3. My screenshot of the purchase product or my comment:

3. Config files (optional)

**Comment by minhcasi** [comment]
Hi, you can save the route to the Redux to manage the routing state, please refer to https://reactnavigation.org/docs/en/redux-integration.html#docsNav

**Comment by guydoron** [comment]
I see there is already exist in Navigation/index.js
I need to skip login screen after registration (autologin) and 
go to the last screen before login. i already autologin but can find the way to go back twice.
