### ISSUE TITLE
[MyListing] - Product Upload, Search, Map Products Loading Problems.

### ISSUE THREAD

**Issue by masonPy3** [inspireui/support#692]
After going live version (not simulator) many problems have been solved but also many problems have come up:

1. I'm unable to upload products when I try to upload I click next and it stucks.. nothing happens.. Also can I set it up they will upload pictures from camera also? so they will take a picture and upload it.

2. Search is not working at all, not only for hebrew (my language but also in english)

3. Map products are stuck on "Loading..." status.

2. Screenshots
1. http://prntscr.com/o0afhk

2. http://prntscr.com/o0afyp
2.1 http://prntscr.com/o0ag8x

3. http://prntscr.com/o0agje

Thanks in advance!

**Comment by thangvo9x** [comment]
Hi. You can refer our guide here https://docs.inspireui.com/listapp/troubleshooting/
1. You can change to use the camera for taking a photo.
2. Do you have a plugin with the name "WPML"? 
3. Share AppConfig for checking. 
4. ... You can't see the screenshots.
same as 5.6.7....

**Comment by masonPy3** [comment]
1. I'm not getting any error from uploading listing, it's just not letting me click "Next".
1.1 Where can I set it up?
2. No, but I'm using Loco Translation to translate plugins.. but the products written in Hebrew, no translation.
3. Will share in the next comment.

Screenshots:
1. https://i.imgur.com/w00x4SR.png
2. https://i.imgur.com/k6u1pS9.png
2.1 https://i.imgur.com/hIib9AM.png
3. https://i.imgur.com/boqhpXP.png

Thanks

**Comment by thangvo9x** [comment]
Hi. We haven't supported the Loco translate plugin
The image will be displayed when you run the plugin "Regenerate Thumbnails"
Thanks

**Comment by masonPy3** [comment]
@thangvo9x
Thanks!
So I'll change it to WPML.
Can you please answer the other questions please? I couldn't find the camera option and also I couldn't upload listing...

**Comment by thangvo9x** [comment]
You can change at Theme/MyListing/Container/PostNewListing/index.js 
refer here : https://docs.expo.io/versions/latest/sdk/imagepicker/#__next

**Comment by masonPy3** [comment]
@thangvo9x 
Thanks, but I'm still can't upload.. Sending AppConfig in next comment.
Thanks

**Comment by masonPy3** [comment]
https://pastebin.com/gqmhArHW
AppConfig

**Comment by masonPy3** [comment]
@thangvo9x 
After Regenerating Thumbnails the map listing still stuck on loading.. :/

**Comment by masonPy3** [comment]
P.S - Turned off Loco Tranlsation, the search still not works...

**Comment by thangvo9x** [comment]
Hi. Could you share the AppConfig.json to me?

**Comment by masonPy3** [comment]
@thangvo9x 
Ok, so few updates:

1. I've managed to add camera and gallery to upload product. 
**I've managed to click the Next button because the image was too big and I couldn't see the Renting Type on my viewport. But now after I'm clicking "Next" In order to upload a lisiting I get that error:**
https://imgur.com/j8BDuh3

2. I Removed Loco tranlsation but still the search not finding anything.
3. Map still stuck on Loading..

My AppConfig.js is in the off-topic comment,
Thanks

**Comment by masonPy3** [comment]
{
  "Website": {
    "url": "https://gesta.co.il",
    "consumerKey": "ck_98526d34a6c973a56f48bedd8f368856bdb53e87",
    "consumerSecret": "cs_508e24ddea9a604a0f1b8e5ed16358864bf9aeb0"
  },
  "Theme": "mylisting",
  "MainColor": {
    "tabbarTint": "#6334a6",
    "tabbarColor": "#D5D8DE",
    "mainColorTheme": "#6334a6",
    "tabbar": "#fff"
  }
}

**Comment by thangvo9x** [comment]
Hi. let me know your email. I'll send the source which was fixed.

**Comment by masonPy3** [comment]
@thangvo9x 
masonisrael.148@gmail.com
Thanks

**Comment by masonPy3** [comment]
@thangvo9x
Hi, why is it closed? I've send you email that the version you sent me not fixing the problem.. it adds new problem that I can't see thumbnails, thanks
