### ISSUE TITLE
[Listapp] - change listing size & my listing issue

### ISSUE THREAD

**Issue by reconshield** [inspireui/support#694]
1) i just want to know.how change listing size in categories. featured image too big. images from home is perfect. i tried check all codes.but hard to find..pls advice 

2) when new user register and login.can see all listing in user panel in my Listing link. suppose view only his view..previous  version was fine..

**Comment by thangvo9x** [comment]
1. You can go to container/categories/index.js 
find this block and change to any size you need.
<img width="316" alt="Screen Shot 2019-06-13 at 9 52 38 AM" src="https://user-images.githubusercontent.com/23457178/59400260-0db9dd80-8dc1-11e9-98f9-4a09cb8e3d7b.png">
2. This is a minor bug. We'll have a hot fix ASAP. thanks

**Comment by reconshield** [comment]
i changed to PostImage.small  but its looks same... :/
from Categories --> click categories name --> Listing List

**Comment by thangvo9x** [comment]
Try to replace this file at Common/Tools.js
p/s: remember that change from .js -> .txt 
[Tools.txt](https://github.com/inspireui/support/files/3299674/Tools.txt)


Checked 
<img width="497" alt="checked" src="https://user-images.githubusercontent.com/23457178/59651751-412bac00-91b5-11e9-9556-55f0229d59d1.png">

**Comment by reconshield** [comment]
still can see all listing in user panel ..for new user

**Comment by thangvo9x** [comment]
Huh? we're talking about Thumbnail image? Please confirm the previous ticket before you raise other tickets.

**Comment by reconshield** [comment]
@thangvo9x no. this ticket its about  

1) how change listing size in categories. featured image too big. images from home is perfect. i tried check all codes.but hard to find..pls advice

2) when new user register and login.can see all listing in user panel in my Listing link. suppose view only his view..previous version was fine..

**Comment by thangvo9x** [comment]
1. 

> Try to replace this file at Common/Tools.js
> p/s: remember that change from .js -> .txt
> [Tools.txt](https://github.com/inspireui/support/files/3299674/Tools.txt)
> 
> Checked
> <img alt="checked" width="497" src="https://user-images.githubusercontent.com/23457178/59651751-412bac00-91b5-11e9-9556-55f0229d59d1.png">

1. reference this.
2. This is a bug. we'll have an update soon. 
Thanks

**Comment by reconshield** [comment]
ok thanks..hopefully issue no 2 update soon.... Mr @thangvo9x .now my Listapp ready to publish :) ...thanks for wonderful product 

ps : for next release..if can let us know files name to update.when new release out..we still face same issue in new release..we have to replace all files again..thanks ( suggestion)
