### ISSUE TITLE
[Listapp] - Search box in iphone x

### ISSUE THREAD

**Issue by reconshield** [inspireui/support#695]
from Home screen , click Search, its go to search box, but this search box too closed and overlay. i test it in iphone x. pls advice

![WhatsApp Image 2019-06-12 at 2 45 03 PM](https://user-images.githubusercontent.com/25501496/59329132-bebc6b80-8d20-11e9-98ce-167731efc744.jpeg)

**Comment by thangvo9x** [comment]
Hi. Try to replace this file at Container/Search/
ps; Remember that change from .txt -> .js Thanks 
[index.txt](https://github.com/inspireui/support/files/3283922/index.txt)

**Comment by reconshield** [comment]
No @thangvo9x when replace file..its give error.. 
![Simulator Screen Shot - iPhone X - 2019-06-13 at 11 50 26](https://user-images.githubusercontent.com/25501496/59402556-77da7e80-8dd1-11e9-987d-019db55e59fb.png)

**Comment by thangvo9x** [comment]
Checked on your config. Which device did you check?
![Uploading Screen Shot 2019-06-18 at 10.41.03 AM.png…]()

**Comment by reconshield** [comment]
after today update to 1.7.2 ..its looks ok.. but i have issue with categories.. all categories is not called in home. categories link

![WhatsApp Image 2019-06-18 at 11 43 53 AM](https://user-images.githubusercontent.com/25501496/59651988-886a6a80-91be-11e9-9b1e-5a7e7fc587dd.jpeg)

**Comment by thangvo9x** [comment]
https://github.com/inspireui/support/issues/709
