### ISSUE TITLE
[beonews] - Error when i build android

### ISSUE THREAD

**Issue by ramyragab1** [inspireui/support#696]
1.  Error when i build android
see this screenshot
2. https://www.dropbox.com/s/puauh85u7g13dpl/Screen%20Shot%202019-06-12%20at%206.06.13%20PM.png?dl=0

3. My screenshot of the purchase product or my comment:  97f0836c-e11f-4c68-8295-862a7571a9ff

**Comment by minhcasi** [comment]
it seems the projects have been changed the name and do some customization that causes the issue, could you help to check to see if you config the project name correctly - https://docs.inspireui.com/mstore/delivery/

**Comment by ramyragab1** [comment]
after i recheck this steps 
this error show 
CONFIGURE SUCCESSFUL in 26s
ERROR: The minSdk version should not be declared in the android manifest file. You can move the version from the manifest to the defaultConfig in the build.gradle file.
Remove minSdkVersion and sync project
Affected Modules: app

WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
Affected Modules: react-native-admob, react-native-blur

WARNING: The targetSdk version should not be declared in the android manifest file. You can move the version from the manifest to the defaultConfig in the build.gradle file.
Remove targetSdkVersion and sync project
Affected Modules: app

**Comment by ramyragab1** [comment]
Hi App Show old posts 
can i fix this error

**Comment by minhcasi** [comment]
Hi @ramyragab1  - pls try to clean up the cache from the simulator to clean up the cache - select Hardware > "Erase All Content and Settings" in Simulator - thank you!
