### ISSUE TITLE
[ListApp] - Chatting and Push Notification

### ISSUE THREAD

**Issue by masonPy3** [inspireui/support#697]
1. I've read the FireBase Push notification is limited only for paid users, Since I've got this error from firebase:
"request to https://exp.host/--/api/v2/push/send failed"
And I've read that its because the push notifications are only for paid plans..

2. I've set the firebase up just like in guide and I still can't see the chat icon in my products... 

Thanks

**Comment by thangvo9x** [comment]
Hi. You should use OneSignal service for push notification. You can do it when you detach your app to the native version.
