### ISSUE TITLE
[list-app] - category search reloads app

### ISSUE THREAD

**Issue by hcwebadvies** [inspireui/support#698]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue

I have an issue with the Categories/Tags/Regions search.
- Clear All does not do anything
- Search button makes the app do a full reload to the homescreen

I have already searched in previous issues and tried by replacing the index.js but that did not work. Also I noticed that even though I am on the latest version of MyListing (2.1.5) I get an error on the endpoint mentioned in the WPAPI.js file (no route to /wp-json/wp/v2/job-categories, only to /wp-json/wp/v2/job_listing_category. I changed the endpoint in WPAPI.js but that does not work either. 

my website is on: https://www.akinosta.com

2. Screenshots

3. My screenshot of the purchase product or my comment:

3. Config files (optional)

**Comment by minhcasi** [comment]
noted for checking @thangvo9x

**Comment by thangvo9x** [comment]
Could you share the AppConfig.js file for checking? 
Firstly, you could try to replace this file at App/Components/TagSelect/
p/s: remember that changr from .txt tag -> .js tag

**Comment by hcwebadvies** [comment]
Great! It works now with this new index.js file! Thank you!
