### ISSUE TITLE
[BeoNews ] - BeoNews 

### ISSUE THREAD

**Issue by raiedahmed** [inspireui/support#699]
problem in Publishing app in google
Warning This release is not compliant with the Google Play 64-bit requirement

The following APKs or App Bundles are available to 64-bit devices, but they only have 32-bit native code: 1.

From August 1, 2019 all releases must be compliant with the Google Play 64-bit requirement.

Include 64-bit and 32-bit native code in your app. Use the Android App Bundle publishing format to automatically ensure that each device architecture receives only the native code it needs. This avoids increasing the overall size of your app. Learn More

1 message for APK 1

Unoptimized APK Warning:

This APK results in unused code and resources being sent to users. Your app could be smaller if you used the Android App Bundle. By not optimizing your app for device configurations, your app is larger to download and install on users’ devices than it needs to be. Larger apps see lower install success rates and take up storage on users’ devices.

Resolution:

Use the Android App Bundle to automatically optimize for device configurations, or manage it yourself with multiple APKs.

**Comment by minhcasi** [comment]
Hi, please update latest 3.0.4 with the Expo 0.33 to fix this build issue, you can refer to this blog - https://blog.expo.io/64-bit-support-and-android-app-bundles-fe0c6a28669 - thank you!
