### ISSUE TITLE
Facebook Login Issue in Pro & Expo version 3.6.2

### ISSUE THREAD

**Issue by hammadhassan** [inspireui/support#7]
I am unable to login to facebook in default config & with my customize config.

Page does refresh after login but not display profile icon in bottom.

Can you please help to fix this issue.

My app is pending due to this issue.

**Comment by minhcasi** [comment]
Hi, could you attach you config.js file, we are closed this ticket to support your same ticket on https://github.com/inspireui/support/issues/8

Please provide more information:
- Your purchased code

**Comment by hammadhassan** [comment]
Here is the code.
[ Purchase Code
f20afe4a-778e-4089-bcb2-7ec1bb4ed49b
]
Both config files are attached expo & pro versions.

Please check both issues & if you want facebook login to create app on developers console to check login please let me know.

I have already created an app on developer account & code is in config file.

I also have one more issue.

I configure my app & website according to Netherlands but when is try to test order using stripe they shows we are not shipping to Netherlands?

Please check this one as well & guide me to fix all these 3 issues.

Thanks.
[Config.zip](https://github.com/inspireui/support/files/2579666/Config.zip)
