### ISSUE TITLE
[Listapp] - Categories List Bugs

### ISSUE THREAD

**Issue by reconshield** [inspireui/support#700]
when click categories icon. all categories is listed. but when i **scroll it**.. give me error.. pls advice 

Video : https://youtu.be/Ht--U---ulI

![Simulator Screen Shot - iPhone X - 2019-06-13 at 09 31 08](https://user-images.githubusercontent.com/25501496/59400366-cc79fb80-8dc9-11e9-92f3-2ed59f99cc1c.png)

**Comment by git-palace** [comment]
This doesn't work

**Comment by git-palace** [comment]
![image](https://user-images.githubusercontent.com/25261362/61069689-b871eb80-a3c1-11e9-9ca6-8c4b05472684.png)
