### ISSUE TITLE
[ListPro]  TypeError: undefined is not an object (evaluating 'post.faqs.faq')

### ISSUE THREAD

**Issue by macox88** [inspireui/support#702]
I god this error on ListPro:

TypeError: undefined is not an object (evaluating 'post.faqs.faq')

This error is located at:
    in SectionData (at ListingDetail.js:150)
    in RCTView (at View.js:44)
    in RCTScrollContentView (at ScrollView.js:852)
    in RCTScrollView (at ScrollView.js:977)
    in ScrollView (at createAnimatedComponent.js:153)
    in AnimatedComponent (at ListingDetail.js:160)
    in RCTView (at View.js:44)
    in ListingDetail (created by Connect(ListingDetail))
    in Connect(ListingDetail) (at PostDetail/index.js:73)
    in RCTView (at View.js:44)
    in Handler (at PostDetail/index.js:114)
    in Index (created by Connect(Index))
    in Connect(Index) (at PostDetailScreen.js:40)
    in PostDetailScreen (at react-native-safe-area-view/index.js:374)
    in RCTView (at View.js:44)
    in AnimatedComponent (at react-native-safe-area-view/index.js:159)
    in SafeView (at withOrientation.js:54)
    in withOrientation (at react-native-safe-area-view/index.js:373)
    in withSafeArea (created by Connect(withSafeArea))
    in Connect(withSafeArea) (created by SceneView)
    in SceneView (at createTabNavigator.js:39)
    in RCTView (at View.js:44)
    in RCTView (at View.js:44)
    in ResourceSavingScene (at createBottomTabNavigator.js:113)
    in RCTView (at View.js:44)
    in ScreenContainer (at createBottomTabNavigator.js:103)
    in RCTView (at View.js:44)
    in TabNavigationView (at createTabNavigator.js:197)
    in NavigationView (created by Navigator)
    in Navigator (at createAppContainer.js:388)
    in NavigationContainer (at RootRouter.js:70)
    in RCTView (at View.js:44)
    in AnimatedComponent (at react-native-drawer/index.js:632)
    in RCTView (at View.js:44)
    in Drawer (at MenuOverlay.js:39)
    in MenuOverlay (created by Connect(MenuOverlay))
    in Connect(MenuOverlay) (at RootRouter.js:83)
    in RCTView (at View.js:44)
    in RootRouter (created by Connect(RootRouter))
    in Connect(RootRouter) (at App.js:217)
    in Provider (at App.js:216)
    in App (at react-native-safe-area-view/index.js:374)
    in RCTView (at View.js:44)
    in AnimatedComponent (at react-native-safe-area-view/index.js:159)
    in SafeView (at withOrientation.js:54)
    in withOrientation (at react-native-safe-area-view/index.js:373)
    in withSafeArea (at withExpoRoot.js:22)
    in RootErrorBoundary (at withExpoRoot.js:21)
    in ExpoRootComponent (at renderApplication.js:34)
    in RCTView (at View.js:44)
    in RCTView (at View.js:44)
    in RootSiblingsWrapper (at AppContainer.js:112)
    in RCTView (at View.js:44)
    in AppContainer (at renderApplication.js:33)

_renderFAQs
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fangela%2FDownloads%2FListPro%201.2.1%2Fsource%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:317388:30
<unknown>
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fangela%2FDownloads%2FListPro%201.2.1%2Fsource%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:317749:40
map
    [native code]:0
render
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fangela%2FDownloads%2FListPro%201.2.1%2Fsource%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:317711:28
finishClassComponent
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fangela%2FDownloads%2FListPro%201.2.1%2Fsource%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:17172:43
performUnitOfWork
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fangela%2FDownloads%2FListPro%201.2.1%2Fsource%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:19840:27
workLoop
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fangela%2FDownloads%2FListPro%201.2.1%2Fsource%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:19872:47
renderRoot
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fangela%2FDownloads%2FListPro%201.2.1%2Fsource%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:19935:21
performWorkOnRoot
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fangela%2FDownloads%2FListPro%201.2.1%2Fsource%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:20626:23
performWork
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fangela%2FDownloads%2FListPro%201.2.1%2Fsource%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:20550:30
performSyncWork
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fangela%2FDownloads%2FListPro%201.2.1%2Fsource%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:20525:20
batchedUpdates$1
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fangela%2FDownloads%2FListPro%201.2.1%2Fsource%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:20726:28
batchedUpdates
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fangela%2FDownloads%2FListPro%201.2.1%2Fsource%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:11800:37
_receiveRootNodeIDEvent
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fangela%2FDownloads%2FListPro%201.2.1%2Fsource%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:11857:23
receiveTouches
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fangela%2FDownloads%2FListPro%201.2.1%2Fsource%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:11887:34
__callFunction
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fangela%2FDownloads%2FListPro%201.2.1%2Fsource%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:3641:49
<unknown>
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fangela%2FDownloads%2FListPro%201.2.1%2Fsource%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:3414:31
__guard
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fangela%2FDownloads%2FListPro%201.2.1%2Fsource%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:3595:15
callFunctionReturnFlushedQueue
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fangela%2FDownloads%2FListPro%201.2.1%2Fsource%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:3413:21
callFunctionReturnFlushedQueue
    [native code]:0

Can you help me please?

**Comment by thangvo9x** [comment]
Try to replace this at App/Components/Detail/Section/
p/s: Remember that change from .txt -> .js 
Thanks 
[index.txt](https://github.com/inspireui/support/files/3289372/index.txt)

**Comment by macox88** [comment]
Hi thank you, now some listing give me this error. TypeError: undefined is not an object (evaluating 's.listing_data.lp_listingpro_options')

This error is located at:
    in b
    in RCTView
    in RCTScrollContentView
    in RCTScrollView
    in ScrollView
    in p
    in RCTView
    in f
    in Connect(f)
    in RCTView
    in h
    in b
    in Connect(b)
    in t
    in RCTView
    in p
    in s
    in u
    in p
    in Connect(p)
    in s
    in RCTView
    in RCTView
    in b
    in RCTView
    in s
    in RCTView
    in s
    in p
    in v
    in b
    in RCTView
    in p
    in RCTView
    in c
    in f
    in Connect(f)
    in RCTView
    in c
    in Connect(c)
    in l
    in f
    in RCTView
    in p
    in s
    in u
    in p
    in u
    in RCTView
    in RCTView
    in Unknown
    in RCTView
    in o

_renderDataType
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false&assetPlugin=%2FUsers%2Fangela%2FDownloads%2FListPro%201.2.1%2Fsource%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:1927:1671
<unknown>
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false&assetPlugin=%2FUsers%2Fangela%2FDownloads%2FListPro%201.2.1%2Fsource%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:1927:8865
map
    [native code]:0
value
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false&assetPlugin=%2FUsers%2Fangela%2FDownloads%2FListPro%201.2.1%2Fsource%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:1927:8749
ar
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false&assetPlugin=%2FUsers%2Fangela%2FDownloads%2FListPro%201.2.1%2Fsource%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:72:43965
Dr
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false&assetPlugin=%2FUsers%2Fangela%2FDownloads%2FListPro%201.2.1%2Fsource%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:72:57909
Or
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false&assetPlugin=%2FUsers%2Fangela%2FDownloads%2FListPro%201.2.1%2Fsource%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:72:58355
yi
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false&assetPlugin=%2FUsers%2Fangela%2FDownloads%2FListPro%201.2.1%2Fsource%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:72:63556
gi
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false&assetPlugin=%2FUsers%2Fangela%2FDownloads%2FListPro%201.2.1%2Fsource%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:72:63104
Ie
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false&assetPlugin=%2FUsers%2Fangela%2FDownloads%2FListPro%201.2.1%2Fsource%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:72:70029
Me
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false&assetPlugin=%2FUsers%2Fangela%2FDownloads%2FListPro%201.2.1%2Fsource%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:72:13717
De
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false&assetPlugin=%2FUsers%2Fangela%2FDownloads%2FListPro%201.2.1%2Fsource%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:72:13890
receiveTouches
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false&assetPlugin=%2FUsers%2Fangela%2FDownloads%2FListPro%201.2.1%2Fsource%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:72:14710
value
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false&assetPlugin=%2FUsers%2Fangela%2FDownloads%2FListPro%201.2.1%2Fsource%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:20:3369
<unknown>
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false&assetPlugin=%2FUsers%2Fangela%2FDownloads%2FListPro%201.2.1%2Fsource%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:20:851
value
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false&assetPlugin=%2FUsers%2Fangela%2FDownloads%2FListPro%201.2.1%2Fsource%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:20:2613
value
    AppEntry.bundle?platform=ios&dev=false&minify=true&hot=false&assetPlugin=%2FUsers%2Fangela%2FDownloads%2FListPro%201.2.1%2Fsource%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:20:823
value
    [native code]:0

**Comment by macox88** [comment]
Ok, when I insert images error don't come nomore! Searching not work, always return me nothing? Can you help me?

**Comment by thangvo9x** [comment]
hi guy. Share your AppConfig.json file for checking this problem?
