### ISSUE TITLE
[list-app] - add text to header in homepage 

### ISSUE THREAD

**Issue by hcwebadvies** [inspireui/support#703]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue

I am using the search component as the first homepage component instead of a banner. Also I have header visible. My question is how to add a text in the header? I would like to have the text "Akinosta" centered, bold, red in this header space.

2. Screenshots

![homepage without appname](https://user-images.githubusercontent.com/51518320/59508069-02dc7700-8ead-11e9-8c60-bef5346c00f1.jpg)

3. My screenshot of the purchase product or my comment:

3. Config files (optional)

**Comment by minhcasi** [comment]
verified purchased - https://tppr.me/kwTgv - @thangvo9x please help to suggest the solution - thank you!

**Comment by thangvo9x** [comment]
Hi guy. you can change that text by going to App/Container/Home/Header/index.js
Thanks. let me know if you change it.

**Comment by hcwebadvies** [comment]
Hi,

I already had that changed:

'        <View style={styles.header}>
          <Text style={styles.title}>
            {'Akinosta Aruba\nDiscover great places'}
          </Text>
          <Animated.Image
            style={[
              styles.image,
              {
                transform: [
                  {
                    scale: this.state.scaleAnimation,
                  },
                ],
              },
            ]}
            source={Config.Local.BannerHeader.image}
          />
          <StatusBar backgroundColor="blue" barStyle="light-content" />
        </View>'

but this code only fires if I have usebanner set to true. I am trying to get a topbar without using banner. I see that you seem to have a possibility for a logo but I cannot find where to set that.

Haime

**Comment by thangvo9x** [comment]
Oh. We have only get ToolBar component. If you need it. You must customize it. It's out of scope support. I hope.
