### ISSUE TITLE
[ListApp] Can't able to login because of an error message- mylisting theme

### ISSUE THREAD

**Issue by Pavithran10** [inspireui/support#704]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue
      hi, while login into the user account it display error **JSON parse error : unrecognized token '<**'  for this reason before occur we faced another error **JWT is not configurated properly,please contact admin** for this error we configure JWT authentication in htaccess file then, we faces the this error message please help to solve this issue ASAP. thanks.
2. Screenshots
![issue](https://user-images.githubusercontent.com/46148046/59508080-64f7a500-8eca-11e9-9532-bb472159bc37.png)

**Comment by thangvo9x** [comment]
Hi. Could you share AppConfig.json file for checking?

**Comment by Pavithran10** [comment]
hi, I've attached the json file below. thanks
[AppConfig.zip](https://github.com/inspireui/support/files/3295271/AppConfig.zip)

**Comment by thangvo9x** [comment]
Hi guy. I checked on your config file which was sent. The error went away when you fix the error comes from this link
https://www.dancestudiyos.com//wp-json/jwt-auth/v1/token
Thanks

**Comment by Pavithran10** [comment]
hi, we know that but how to clear that error and then now application content is not fetching inside the app.
User login issue is also not yet solved till now same error message is showing. thanks

**Comment by thangvo9x** [comment]
Hi guy. The link was told about it with clearly. Cause is your .htaccess file.
<img width="817" alt="Screen Shot 2019-06-18 at 5 34 46 PM" src="https://user-images.githubusercontent.com/23457178/59675390-60472f80-91ef-11e9-87db-d3a90064bdfc.png">
