### ISSUE TITLE
[list-app] - add custom field in post.js (theme mylisting)

### ISSUE THREAD

**Issue by hcwebadvies** [inspireui/support#705]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue

I have a custom field ( _reservation-url ) that is only valid for the restaurant listtype in my MyListing theme. I am trying to add it to the post.js but keep getting an error. I tried:

      this.reservation_url = listing_data._reservation-url
        ? listing_data._reservation-url
        : ''

I suspect I need a check if the field is present but I do not know how to add that. I tried also:

      this.reservation_url = typeof listing_data._reservation-url ! = 'undefined' &&
        listing_data._reservation-url ? listing_data._reservation-url
        : ''

Could you let me know how to add this? See also https://www.akinosta.com/wp-json/wp/v2/job_listing for the JSON output

2. Screenshots

3. My screenshot of the purchase product or my comment:

3. Config files (optional)
[Post.txt](https://github.com/inspireui/support/files/3293459/Post.txt)

**Comment by thangvo9x** [comment]
Hi. You configured incorrect. Please refer this link 
https://docs.inspireui.com/listapp/customization/#8-how-to-add-a-new-key-to-listing-detail

**Comment by hcwebadvies** [comment]
Hi,

I am actually trying something different:

in ListingDetail.js I added:

'  _handlePressButtonAsync = async () => {
     let result = await WebBrowser.openBrowserAsync('https://expo.io');
     this.setState({ result });
   }'

and also:

'		  <View style={styles.BookNowContainer}>
		    <TouchableOpacity
			  style={styles.BookNowBtn}
			  onPress={this._handlePressButtonAsync}
		    >
			  <Text style={styles.BookNowText}> BOOK NOW </Text>
		    </TouchableOpacity>
		  </View>'

I also added to post.js:

'this.reservation_url = listing_data._reservation-url
    ? listing_data._reservation-url
    : '''

In the handler I want to grab the reservation_url instead of "expo.io" ofcourse (constant reservation -> props?)

issue is that I need to have the button only show if reservation_url string > 0 because only certain listingtypes have that field (it does not appear in the json of other listing types) and also it is not always filled in even if available in the listing type (it is an optional field)

regards,

Haime

**Comment by thangvo9x** [comment]
Hi bro. should belisting_data['_reservation-url']
