### ISSUE TITLE
[ListPro] - Error when creating a new post

### ISSUE THREAD

**Issue by roger-hope** [inspireui/support#707]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue
When using the App (V.13.4) to create a new listing I receive the following error: "Error while updating property 'coordinate' of a vview managed by: AIRMapMarker null latitude".
I am not able to create a new listing.

2. Screenshots

3. My screenshot of the purchase product or my comment:
<img width="1023" alt="Screenshot 2019-06-17 at 20 14 38" src="https://user-images.githubusercontent.com/22624734/59626641-b14a1b80-913c-11e9-8a61-d1dd1cf0f297.png">

3. Config files (optional)

**Comment by thangvo9x** [comment]
Hi guy. Share the AppConfig.json file for checking?

**Comment by roger-hope** [comment]
[AppConfig.json.zip](https://github.com/inspireui/support/files/3302491/AppConfig.json.zip)

**Comment by thangvo9x** [comment]
Hi. Please check again or update to the latest version of the source.
Thanks
