### ISSUE TITLE
[ListPro] - Error when clicking selecting a date on the calendar for booking

### ISSUE THREAD

**Issue by roger-hope** [inspireui/support#708]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue
When using the App (V.13.4) to add a booking I receive the following error when selecting a date in the calendar: "TypeError: TypeError: undefined is not an object (evaluating '_common.Config.DateTimePicker.Locale') This error is located at: in DateTimePickerComp (at Calendar/index.js:61)"
I activated the booking feature for the App in the file: App/Common/Config/index.js

2. Screenshots
![Screenshot_errorIMG1_2019-06-05-21-57-48](https://user-images.githubusercontent.com/22624734/59627201-f28efb00-913d-11e9-89e9-7f89c460e67e.jpg)

3. My screenshot of the purchase product or my comment:
<img width="1023" alt="Screenshot 2019-06-17 at 20 14 38" src="https://user-images.githubusercontent.com/22624734/59627096-be1b3f00-913d-11e9-8edb-99f20ca0935c.png">

3. Config files (optional)

**Comment by thangvo9x** [comment]
Hi. Can you share the AppConfig.json file?

**Comment by thangvo9x** [comment]
Hi. Please try to update with this file below.
[index.txt](https://github.com/inspireui/support/files/3304257/index.txt)
Thanks.
