### ISSUE TITLE
[Listapp] - 1.7.2 Categories bugs

### ISSUE THREAD

**Issue by reconshield** [inspireui/support#709]
i just update 1.7.2 . i cant view listing categories from home and category list icon from bottom menu. pls help

![WhatsApp Image 2019-06-18 at 11 23 43 AM](https://user-images.githubusercontent.com/25501496/59651295-eba6cd80-91bb-11e9-9d25-88939d97f322.jpeg)
![WhatsApp Image 2019-06-18 at 11 23 44 AM](https://user-images.githubusercontent.com/25501496/59651299-ed709100-91bb-11e9-9da5-46ead73097be.jpeg)
![WhatsApp Image 2019-06-18 at 11 25 36 AM](https://user-images.githubusercontent.com/25501496/59651305-eea1be00-91bb-11e9-876b-ab73a0ba9341.jpeg)

**Comment by thangvo9x** [comment]
Please try to fix by going to App/Services/WPAPI find this block and remove job-categories.
<img width="552" alt="Screen Shot 2019-06-18 at 5 36 46 PM" src="https://user-images.githubusercontent.com/23457178/59675546-aac8ac00-91ef-11e9-9eb6-f00b17f6230e.png">
This error come from version of theme WordPress. the latest verion will use job-categories url instead job_listing_category as before.

**Comment by reconshield** [comment]
ok..solved..thanks alot @thangvo9x

**Comment by reconshield** [comment]
when i

**Comment by reconshield** [comment]
when i remove the complete block..its show error.. can send me  WPAPI file?

**Comment by thangvo9x** [comment]
HI. this here 
Remember the change tag of the file. @reconshield 
[WPAPI.txt](https://github.com/inspireui/support/files/3312660/WPAPI.txt)
Thanks

**Comment by reconshield** [comment]
thanks sir @thangvo9x working fine..great job!
