### ISSUE TITLE
[mstore multivendor] chat bugs 

### ISSUE THREAD

**Issue by alaradi2006** [inspireui/support#71]
**Required Info (please complete the following information):**
 - Product: mstore multivendor 1.1.2
 - Your Purchased Code: [get from https://codecanyon.net/downloads]
(we may not reply if you are not our customer)
a9c6782d-8c5d-4811-8c4a-2ccc9d6be005
**Describe the bug**
1-chat system after opening chat window i cant go back the only way to exit from chat window its by shutting down the app

2 if i send message from buyer account its working fine 
if i send message from vendor account , application will send the message and restart 

i test the app in many andorid galaxy note 5 and lenevo tablet both has last android versio 
**Screenshots**

**Additional context**
Add any other detail logs about the problem here.
If possible please share your config.js that use for the app setting

**Comment by alaradi2006** [comment]
check it 
as i check it in multiple android phone its the same thing 
for iphone i dont have it ,i didnt test it

**Comment by alaradi2006** [comment]
yes sure

**Comment by alaradi2006** [comment]
heres

**Comment by minhcasi** [comment]
Hi, you can send to this email (and also note with this ticket URL) - thang@beostore.io

**Comment by alaradi2006** [comment]
sent to chat agent minh

**Comment by thangvo9x** [comment]
Hi. I checked your site. Please install plugin Dokan -lite suchas Dokan pro. 
Thanks

**Comment by alaradi2006** [comment]
i have dokan pro in my site

________________________________

**Comment by alaradi2006** [comment]
everything work great 
except the chat part

**Comment by minhcasi** [comment]
@alaradi2006, could you clarify the detail of Chat issue - thanks
