### ISSUE TITLE
[Listapp] - 1.7.2 version  React Native version Mismatch error

### ISSUE THREAD

**Issue by reconshield** [inspireui/support#711]
im getting React Native version Mismatch error when running 1.7.2
----

Environment:
  OS: macOS High Sierra 10.13.6
  Node: 10.11.0
  Yarn: 1.16.0
  npm: 6.4.1
  Watchman: Not Found
  Xcode: Xcode 10.1 Build version 10B61
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  react: ^16.8.6 => 16.8.6
  react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8

![Simulator Screen Shot - iPhone X - 2019-06-18 at 16 27 25](https://user-images.githubusercontent.com/25501496/59666070-b2378780-91e6-11e9-86b9-bac1fa12daa3.png)
[package.json.txt](https://github.com/inspireui/support/files/3300534/package.json.txt)

**Comment by minhcasi** [comment]
Hi, this is not a bug, it's cache issue - try to remove the node module & expo app and reinstall again 

You can also check the detail from - https://blog.expo.io/expo-sdk-v33-0-0-is-now-available-52d1c99dfe4c - thanks

**Comment by masonPy3** [comment]
@minhcasi  Hi, I have the same problem, tried to reinstall both..

**Comment by reconshield** [comment]
MasonPy3 .. try latest version.. 1.7.3

**Comment by masonPy3** [comment]
@reconshield I'm on 1.7.3, it fixed your problem? I got it from 1.7.3

**Comment by reconshield** [comment]
Yes.. try remove cache ..

**Comment by masonPy3** [comment]
@reconshield how? tried to run yarn start -c
I also re-install the expo app
Thanks

**Comment by reconshield** [comment]
Did u remove node modules?

**Comment by masonPy3** [comment]
@reconshield yes

**Comment by masonPy3** [comment]
fixed. was version mismatch in app.js
Thanks
