### ISSUE TITLE
[ListApp] How to update?

### ISSUE THREAD

**Issue by masonPy3** [inspireui/support#712]
Hi, I've made many changes in my app in order to customize my theme and etc..
How can I update now the theme, or just know what files you've been updated so I'll compare with my own..
Thanks in advance.

**Comment by thangvo9x** [comment]
Hi. You can use the DiffMerge tool to compare the files.
If you update by manually. Those customize will be gone.

**Comment by masonPy3** [comment]
@thangvo9x
Diffmerge comparing one file only..
Is there a automatic way that won't lose my customization? I pretty sure many have this issue.. can you guys release a RAR or something with the updated files only so it will be easier to compare?
Thanks in advance

**Comment by masonPy3** [comment]
@thangvo9x Plus How do I update Expo?
Thanks

**Comment by thangvo9x** [comment]
You could refer here
https://docs.expo.io/versions/v33.0.0/workflow/upgrading-expo-sdk-walkthrough/#upgrade-from-sdk-32
Thanks
