### ISSUE TITLE
[ListApp] - image issue

### ISSUE THREAD

**Issue by RaptorHck** [inspireui/support#714]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue

Do not load the images in my application

2. Screenshots

![IMG_2659](https://user-images.githubusercontent.com/7127855/59704699-607d0600-91c2-11e9-94d4-5b20d8033f88.png)

![IMG_2661](https://user-images.githubusercontent.com/7127855/59704708-6672e700-91c2-11e9-8044-63a5c8ac726b.png)

3. My screenshot of the purchase product or my comment:

3. Config files (optional)
 AppConfig.json
{
  "Website": {
    "url": "http://localhost:8888/qponmexico",
    "consumerKey": "ck_dea33595faa8108d7e2fc06f80aeb3011cdb41e0",
    "consumerSecret": "cs_cdbce2499eb0f4598503e457506e5a47fce9d6f3"
  },
  "Theme": "restaurant",
  "MainColor": {
    "tabbarTint": "rgb(27, 229, 141)",
    "tabbarColor": "#D5D8DE",
    "mainColorTheme": "rgb(27, 229, 141)",
    "tabbar": "#FFF"
  }
}

.htacces

# BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /qponmexico/
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /qponmexico/index.php [L]
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule ^(.*) - [E=HTTP_AUTHORIZATION:%1]
SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1
</IfModule>

**Comment by minhcasi** [comment]
Hi, could you try to replace the URL http://localhost:8888/qponmexico with the virtual host (example: http://qpnmexico.local) on your local, as the format URL/xx will not work with the Rest API - thanks
