### ISSUE TITLE
Mstore Pro 3.8.0 - error while installing via npm install

### ISSUE THREAD

**Issue by harry-saputra** [inspireui/support#716]
envato user : harrysaputra
purchase code

My issue :

C:\reactnative\mstore-pro>npm install
npm WARN deprecated core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()

> grpc@1.20.0 install C:\reactnative\mstore-pro\node_modules\grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://node-precompiled-binaries.grpc.io/grpc/v1.20.0/node-v72-win32-x64-unknown.tar.gz
node-pre-gyp WARN Pre-built binaries not found for grpc@1.20.0 and node@12.4.0 (node-v72 ABI, unknown) (falling back to source compile with node-gyp)
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB4132: The tools version "2.0" is unrecognized. Available tools versions are "4.0".

**Comment by harry-saputra** [comment]
![image](https://user-images.githubusercontent.com/6844866/59853471-2155dd00-939b-11e9-9dc7-f8635a3f9106.png)

**Comment by minhcasi** [comment]
Hi, could you try to run with the example to see if it can be fixed - https://facebook.github.io/react-native/docs/getting-started.html. We are going to upgrade new version with latest RN and Expo in next couple of days - thank you!

**Comment by harry-saputra** [comment]
yes, i already done built the react native sample project, on emulator and physical devices using latest nodejs and python.
 
previously, m-store installation show error on python 3.7, so i downgrade to python 2.7.6 and another error appears, as you seen right now

**Comment by harry-saputra** [comment]
@minhcasi can i contact u via whatsapp / email?

**Comment by harry-saputra** [comment]
i am waiting the latest version, couple of days right? so it would be around 23 june. thanks

**Comment by minhcasi** [comment]
Hi, we have updated latest 3.9.0 to fix the variant issues, please help to check on your side, there are new build grade upgrade

Please reopen the ticket if it does not work - thank you!
