### ISSUE TITLE
[ListApp] - error red screen

### ISSUE THREAD

**Issue by phorumdm** [inspireui/support#717]
after build the app appear this error when open the app on mobile phone simulator http://fidesysmobile.com/audio/Screenshot_20190619-013149_Expo.jpg http://fidesysmobile.com/audio/Screenshot_20190619-013200_Expo.jpg
please send me a solution for this issue.
I send you by email to this adress  support@inspireui.com a link where you can download the source code for the app

**Comment by thangvo9x** [comment]
Hi bro. Try to replace this file at App/Container/Detail/
[index.txt](https://github.com/inspireui/support/files/3334029/index.txt)
Remember that change from .txt ->  .js
Thanks
