### ISSUE TITLE
[ Mstore ] - Icon and tabs are not visible after publish the play store

### ISSUE THREAD

**Issue by santhoniral** [inspireui/support#719]
Hi, App categories icon are not visible in home page and also not visible in tabs....
please solve this error, thanks
![WhatsApp Image 2019-06-21 at 9 59 16 AM (1)](https://user-images.githubusercontent.com/32481586/59897732-b7295080-940b-11e9-9dbc-c7cb730d392b.jpeg)
![WhatsApp Image 2019-06-21 at 9 59 16 AM](https://user-images.githubusercontent.com/32481586/59897733-b7c1e700-940b-11e9-876e-4416f96d7ac9.jpeg)

**Comment by santhoniral** [comment]
Billing address not visible perfectly....alignment error

![59654509-11c86f80-91b4-11e9-8f1d-f7f60eb4a64c](https://user-images.githubusercontent.com/32481586/59897964-99a8b680-940c-11e9-8aac-51182a764f76.png)

**Comment by santhoniral** [comment]
Facebook login not working in after play store ...but working fine in expo

![Screenshot_20190621-101611](https://user-images.githubusercontent.com/32481586/59898290-b5f92300-940d-11e9-8c53-6058910d6a97.jpg)

**Comment by minhcasi** [comment]
Hi, we have updated latest 3.9.0 to fix the variant issues, please help to check on your site - thank you!
