### ISSUE TITLE
[Listapp] POST LISTING ERROR AT END

### ISSUE THREAD

**Issue by reconshield** [inspireui/support#72]
- Product:  ListApp
 - Your Purchased Code: 23ee6c94-1eb8-4ffd-842f-7600d97f41d0

**> when i post listing. i get this error.why? here my screenshot.. "wrong numbers of segments"**

![simulator screen shot - iphone x - 2018-12-03 at 10 43 34](https://user-images.githubusercontent.com/25501496/49350547-598d1b00-f6ea-11e8-9062-1de9b6094e14.png)
1st screen : add image and choose package

![simulator screen shot - iphone x - 2018-12-03 at 10 44 18](https://user-images.githubusercontent.com/25501496/49350249-37df6400-f6e9-11e8-89e5-90c871e50769.png)
2nd Screen Add address

![simulator screen shot - iphone x - 2018-12-03 at 10 49 07](https://user-images.githubusercontent.com/25501496/49350363-a9b7ad80-f6e9-11e8-88b1-b0f2f89da797.png)
3rd screen add listing details

![simulator screen shot - iphone x - 2018-12-03 at 10 49 18](https://user-images.githubusercontent.com/25501496/49350458-07e49080-f6ea-11e8-9bf4-aa4a75101543.png)

Error message when summit

**Comment by thangvo9x** [comment]
Hi . We've checked your source. A new post listing was created on your site with name DEF. 
please test it. such as please update in the last version of product.
Thanks

**Comment by reconshield** [comment]
the latest version got so many bugs..which other users face it.. how u post listing? can create video? used my config file?
