### ISSUE TITLE
[MSTORE] -LOGO AND OTHER BUGS 

### ISSUE THREAD

**Issue by papaya1986** [inspireui/support#720]
Item Purchase Code:
408c44f3-fc98-4098-8cd6-41303adcbc65

Urgent 
1.remove space between logo and header home page.
Screenshot: https://ibb.co/P5HycGv
2.How to make logo center same like below picture.
screenshot: https://imgur.com/a/QSrDtZF
3.Extra space in product listing pages if there more then 10 products both android and IOS
Screen Shot : https://ibb.co/0276R6q

4.if we activate Dark mode left side menu /drawer is empty categories,user profile image, etc .

**Comment by papaya1986** [comment]
No update ?

**Comment by minhcasi** [comment]
Hi, we need more time to investigate and will include the fixing on next version - thanks

**Comment by minhcasi** [comment]
Hi, we have updated latest 3.9.0 to fix these issues, please help to check on your side, and reopen if it does not work - thank you!
