### ISSUE TITLE
[ListApp] - New release 1.7.2 with old errors

### ISSUE THREAD

**Issue by bfwi410a** [inspireui/support#721]
I'm really angry right now!

Why are the bugs discussed over several days not included in the new release 1.7.2? I can go through all my posts and manually change the errors posted here.
#686 
#693 
#673 
#628 
#662 
#658 
#653 (There is no solution for that. The problem should be solved with the new release. Unfortunately, the problem still exists.)

Why? You will always have the same discussion with other buyers who have the same problems. That does not have to be! Please do an update with fixed errors.

**Comment by thangvo9x** [comment]
Hi bro. could you brief your problem more detail for us?

**Comment by minhcasi** [comment]
Hi @bfwi410a kindly reopen one of these tickets if it does not work on your website

If you are still not happy, we could process the refund for you
 - thank you!
