### ISSUE TITLE
the rest api is not working correctly magento

### ISSUE THREAD

**Issue by hha00m** [inspireui/support#722]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue

2. Screenshots

3. My screenshot of the purchase product or my comment:

3. Config files (optional)

**Comment by hha00m** [comment]
I 've just bought magento store but when I tried to configure it I faced an issue the rest API is not working correctly.
Please any help

**Comment by minhcasi** [comment]
Hi, could you help to share the following info so that we could help:
- The screenshot issues
- Your website URL or the config file to link to your site (from common/appConfig.json and config.js) file

**Comment by hha00m** [comment]
<img width="1440" alt="Screenshot 2019-07-18 12 03 43" src="https://user-images.githubusercontent.com/9365644/61453158-57b05900-a955-11e9-8c81-eb008ec51925.png">

**Comment by hha00m** [comment]
please any help
