### ISSUE TITLE
[Listapp] - Google Play 64-bit 

### ISSUE THREAD

**Issue by reconshield** [inspireui/support#724]
Im using Listapp 1.7.2 .from version release note, inspireui note that latest update support 64Bit. but when i try upload apk file for internal test google play im getting this error.

This release is not compliant with the Google Play 64-bit requirement
The following APKs or App Bundles are available to 64-bit devices, but they only have 32-bit native code: 23.

**Comment by thangvo9x** [comment]
It's a warning when uploading the .apk file. Don't worry about it.

**Comment by reconshield** [comment]
ok..thanks @thangvo9x
