### ISSUE TITLE
Mstore multivendor

### ISSUE THREAD

**Issue by eddielthomas** [inspireui/support#725]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue
I am having an issue with the lineargradient expo component on Android.  It is saying that the endPoint has not been set, however, I have not modified any of the lineargradient components.
The code works for IOS but not Android.

Please see the screenshot.   

2. Screenshots
<img width="407" alt="Screen Shot 2019-06-24 at 10 38 26 PM" src="https://user-images.githubusercontent.com/714476/60065228-24213c80-96d1-11e9-9a9a-3b0816c08300.png">

3. My screenshot of the purchase product or my comment:
<img width="1440" alt="Screen Shot 2019-06-24 at 10 39 48 PM" src="https://user-images.githubusercontent.com/714476/60065209-1075d600-96d1-11e9-9e7b-bf0cfb2cac06.png">
3. Config files (optional)

**Comment by thangvo9x** [comment]
Hi. Please brief more detail about your issue. but I guess the problem is coming from "end" Props in LinearGradient. Thanks.
