### ISSUE TITLE
[ListApp] - Bookmark not showing any feature image

### ISSUE THREAD

**Issue by SuperXonic** [inspireui/support#726]
I think this is the bug in Bookmark Screen (Wishlist). It doesn't show any feature image after user click save bookmark. Could you help fix this? It's a good feature for user to save what they want.
Thank you!

![Screen Shot 2019-06-25 at 9 15 14 AM](https://user-images.githubusercontent.com/52225482/60145161-63de4600-97ef-11e9-8140-b76ec2aa37ba.png)

**Comment by reconshield** [comment]
@SuperXonic i faced same issue.but its working fine in real devices.

**Comment by SuperXonic** [comment]
@reconshield Thank you for your information but I downloaded ListApp From App Store it doesn't show Image Feature in Bookmark also. I think it a bug.

**Comment by reconshield** [comment]
i dont think so..mine working fine

**Comment by thangvo9x** [comment]
> @reconshield Thank you for your information but I downloaded ListApp From App Store it doesn't show Image Feature in Bookmark also. I think it a bug.

The listApp on the Store has been updating soon. Thanks. Wishlist with feature image is working fine. Please check feature Image on your website.
