### ISSUE TITLE
Android Build Error with M-Store pro

### ISSUE THREAD

**Issue by smilechaitu** [inspireui/support#727]
1. My issue:  when am trying to build Android app it gaven error to upgrade gradle to latest version so, I upgraded Gradle to 5.4.1 and now when I am tryied to build android app again after Gradle upgrade. it gives error as per this screenshot  here https://prnt.sc/o6pl00  in terminal.

Please some one help me . it's been more than 1 month I still could not publish my app. so, faster response is highly appreciated 

**my code from /mstore-pro/android/build.gradle as below:** 

// Top-level build file where you can add configuration options common to all sub-projects/modules.
// get the latest version from - https://developers.google.com/android/guides/setup
def googlePlayServicesVersion = '15.0.1'

buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 21
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.google.gms:google-services:3.0.0'
        classpath 'com.android.tools.build:gradle:3.4.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        google()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
     configurations.all {
             resolutionStrategy {
                //  force 'com.facebook.android:facebook-android-sdk:4.22.1'

                 // react-native-admob
                 force "com.google.android.gms:play-services-ads:$googlePlayServicesVersion"

                 // force "com.google.android.gms:play-services-base:$googlePlayServicesVersion"
                 // force "com.google.android.gms:play-services-maps:$googlePlayServicesVersion"

                 // react-native-onesignal
                 force "com.google.android.gms:play-services-gcm:$googlePlayServicesVersion"
                 force "com.google.android.gms:play-services-analytics:15.0.2"
                 force "com.google.android.gms:play-services-location:$googlePlayServicesVersion"

                 // react-native-google-sign-in
                 force "com.google.android.gms:play-services-auth:$googlePlayServicesVersion"
             }
         }
}

subprojects { subproject ->
    afterEvaluate{
        if((subproject.plugins.hasPlugin('android') || subproject.plugins.hasPlugin('android-library'))) {
            android {
                compileSdkVersion rootProject.ext.compileSdkVersion
                buildToolsVersion rootProject.ext.buildToolsVersion
            }
        }
    }
}

wrapper {
    gradleVersion = '5.4.1'
    distributionUrl = distributionUrl.replace("bin", "all")
}

**Comment by smilechaitu** [comment]
my screenshot of purchase https://prnt.sc/nz4lw6

**Comment by minhcasi** [comment]
Hi, we suggest not upgrade the grade as the request from the Android Studio as it will break the build, you can just try to run with the terminal: react-native run-android.

We will maintain the new version upgrade (react native, expo) and it will be updated soon - thanks

**Comment by smilechaitu** [comment]
Hi, Thanks for reply but I could not build even with old version and it was giving errors to upgrade Gradle that's why I upgraded.

for building I am using commands in terminal as below:

$ cd android
$ ./gradlew bundleRelease

so, please let me know as below:
1) Do I need to use some other commands to build with old version ?
2) When will be new version upgrade coming ?

**Comment by smilechaitu** [comment]
Hi,
    now I deleted old Gradle and reconfigured m-store pro as per your instructions file and I still get errors when I followed  in terminal. screenshot here https://prnt.sc/o7ofkm 
$ cd android
$ ./gradlew bundleRelease.

so, even with no upgrade I could not build App to publish in play store . please reply quick.

**Comment by smilechaitu** [comment]
hi, I also did fresh setup using your latest release which came yesterday and when tried nom install. it gives following error

npm WARN Invalid name: "MStore Pro"
npm WARN mstore-pro No description
npm WARN mstore-pro No repository field.
npm WARN mstore-pro No README data
npm WARN mstore-pro No license field.

up to date in 0.452s
found 0 vulnerabilities

**Comment by minhcasi** [comment]
Hi, first - try to redownload the nodejs 10.x from this page - https://nodejs.org

Then, go the folder mstore-pro try with this script and start the simulator to run again:
`watchman watch-del-all && rm -rf $TMPDIR/react-* && rm -rf node_modules/ && yarn cache clean && yarn install && yarn start -- --reset-cache`
