### ISSUE TITLE
[ListApp] - No paging from category links, thumbnails not showing and map search results not selectable

### ISSUE THREAD

**Issue by Xtraterestrial** [inspireui/support#728]
---------
Hi team, good work on the app, i have managed to build an apk but unfortunately there have been some bugs that I have not been able to overcome by myself. please have a look at these details and screenshots and help me fix the problems.

I am using Listable (https://themeforest.net/item/listable-a-friendly-directory-wordpress-theme/13398377) as my main theme.

**1. My First issue :** 

Hi team, My first issue is happening from the home screen and from the category screen

For the homescreen i have the app set up to show category links using this code :  
  {
    component: 'categoryLinks',
    name: 'What can we help you find?',
  },

When a category is selected the screen that shows the listings only displays 10 items, and cuts off the last 2, there is no paging for this section and i can not find where to add it, help would be appreciated. Screenshots are below to show my issue.

Screenshot 1 shows the menu i am referring to,

![InkedScreenshot_20190626_125445_com inspireui listapp_LI](https://user-images.githubusercontent.com/12083653/60171568-871aec80-9813-11e9-91e6-cb92c8f4baed.jpg)

Screenshot 2 shows the results page with max 10 listings showing and no paging. This is the same thing that happens if i select any category from the category screen also. I would like to have paging work in all areas:

![InkedScreenshot_20190626_125458_com inspireui listapp_LI](https://user-images.githubusercontent.com/12083653/60171637-a74aab80-9813-11e9-9715-7eca25ef50f0.jpg)

**2. My second issue :** 
The images in my listings are loading but none of the thumbnails are loading.

I have installed the plugin called regenerate thumbnails and run it, I have also tried to replace my tools.js file as recommended in the FAQ but this did not fix the problem.

I have added a featured image to some of the listings but no thumbnails load at all. Some help here is urgent please.
Screenshot for ref: 

![Screenshot_20190626_130339_com inspireui listapp](https://user-images.githubusercontent.com/12083653/60173851-5f7a5300-9818-11e9-9774-e40382433fd2.jpg)

**3. My third issue:** 
From the map screen, When I type some keywords the search suggestions that show up can not be selected and do not disappear unless the search word is removed

![InkedScreenshot_20190625_130131_com inspireui listapp_LI](https://user-images.githubusercontent.com/12083653/60172158-c1d15480-9814-11e9-895a-1aa8d1409c44.jpg)

Please advise me on how this can be fixed so when a search is done the user can select it and have the results from that area be displayed.

I will edit and update with my screenshot of the support comment just now.

EDIT : my purchase proof screenshot 
![Screenshot (45)](https://user-images.githubusercontent.com/12083653/60174072-e92a2080-9818-11e9-8e54-4090f41571f3.png)

**Comment by minhcasi** [comment]
Hi @Xtraterestrial  - your customize project looks great, could you share your config file so that we could help to check this issue, or send privately to our support email - support@inspireui.com 

@thangvo9x

**Comment by Xtraterestrial** [comment]
Hi @minhcasi , Thank you! You and the team have made it easy to customize. I have sent the files via email, let me know if you need any more details from me to be able to help with the problems

**Comment by thangvo9x** [comment]
Please share your domain ( AppConfig.json). Feature Image not display because the problem is coming from your website. try update the coverImage  / Feature Image thumbnails. Thanks

**Comment by Xtraterestrial** [comment]
@thangvo9x I have sent the appconfig file from my project, check the support email. Is this the correct one you want?

As for the feature image not displayed, i have tried to add a featured image from my website on different posts, ref the screenshot:

![Screenshot (47)_LI](https://user-images.githubusercontent.com/12083653/60270567-5f9e4f80-98f9-11e9-8ade-c4529688f44f.jpg)

This image still does not show on the app thumbnail

**Comment by Xtraterestrial** [comment]
Hello team, have you managed some progress? Is there some feedback for me?

**Comment by thangvo9x** [comment]
Try update Cover Image. Have you run the Regenerate Thumbnail plugin yet?

**Comment by Xtraterestrial** [comment]
Yes i have run the regenerate thumbnails plug in a few times, it did not work.

My posts do not have an option for cover image anywhere that i can see. I have switched to the classic editor and back to block editor but I only see featured image as an option. I have contacted the theme developers as well to ask their help.

What about the issue with paging and with the map???

**Comment by thangvo9x** [comment]
Could you share your AppConfig file?

**Comment by Xtraterestrial** [comment]
I have emailed you a copy of the file before, I will send a full copy of project to the support email. Im hoping we can find the issues ASAP as i am eager to lauch

**Comment by Xtraterestrial** [comment]
Hi @thangvo9x ,

I have got no communication at all!!

What is going on?

**Comment by thangvo9x** [comment]
Hi Try to replace this file at container/Category/ 
[index.txt](https://github.com/inspireui/support/files/3421462/index.txt)
change from .txt -> .js 
Thanks

**Comment by Xtraterestrial** [comment]
@thangvo9x I tried that file, Now when I select the category icon from the menu instead of showing me categories to choose from, it shows all listings. Unfortunately this is a step backward.


My main concern is getting the thumbnails to work! I can work on the rest myself and figure it out. But ive had no luck with fixing the thumbnails myself. Please have a look at the files I have sent and trace the problem

**Comment by thangvo9x** [comment]
Hi bro. Do you mean the thumbnail still not display?

**Comment by Xtraterestrial** [comment]
Yes they still do not display.

I saw there was an update today. I will try to rebuild and then tell you if anything has been fixed

**Comment by Xtraterestrial** [comment]
@thangvo9x 
The new update fixed the thumbnails. Thanks

New issue :

Paging is not working from home category now

**Comment by thangvo9x** [comment]
Yup. paging on the home page isn't working. It's because it has maybe crashed on the home screen. We will fix it in the next update. Thanks
