### ISSUE TITLE
[MSTORE - Multi Vendor] - Without Expo - Product Variations Not Working

### ISSUE THREAD

**Issue by lcassiol** [inspireui/support#729]
My purchase code is 4cd001fd-62ec-4131-86fa-b60cf647c215
- I'm using version 1.3.0 without EXPO from codecanyon

**My main problem** -  I created products with variations on my WP site and when I search for the product with variations in the application the variations do not appear.

**Few questions:**
- Is there any problem if I update Woocommerce or Dokan? is Mstore-Pro compatible with which versions?

The product with variation for test: 
https://emall12.xarx.rocks/loja/sleeve-linen-blend-caro-pane-shirt/

My app config:
"WooCommerce": {
    "url": "https://emall12.xarx.rocks",
    "consumerKey": "ck_c6072e23eceae4b97d58a105bc562a22b9bd252d",
    "consumerSecret": "cs_783ce3c15c9032557e6bff318e486a73430e7c91"
  },

**Comment by minhcasi** [comment]
Hi, we have upgraded latest 3.9 to fix these issues, could you help to check it again on your site - thank you!

**Comment by lcassiol** [comment]
What have you upgraded to version 3.9? The RN Mstore-Pro? The mstore-checkout plugin? Could you send me a link? Because in codecanyon the version is 1.3

**Comment by lcassiol** [comment]
Sorry I have made a mistake on issue title, My Problem is in Mstore Multi Vendor from this link
https://codecanyon.net/item/mstore-multi-vendor-complete-react-native-template-for-ecommerce/22278924
