### ISSUE TITLE
[ListApp] - error Couldn't find the binary git

### ISSUE THREAD

**Issue by daniloaqui** [inspireui/support#73]
**Mandatory Info (please complete the following information):**
 - Product: [e.g. MStore, ListApp]
 - Your Purchased Code: [get from https://codecanyon.net/downloads]
(we may not reply if you are not our customer)

**Describe the issues**

**Screenshots**

**Additional context**
Add any other detail logs about the problem here.

C:\luxou\Source>yarn install
yarn install v1.12.3
[1/4] Resolving packages...
error Couldn't find the binary git
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by minhcasi** [comment]
duplicate with - https://github.com/inspireui/support/issues/28

**Comment by serwadda** [comment]
I'm getting this same problem, i.e. "Couldn't find binary git" and this is for the react-native however the node modules folder referenced with #28 isn't available anymore. What could be the solution?
