### ISSUE TITLE
 Categories are empty

### ISSUE THREAD

**Issue by sorojon** [inspireui/support#730]
home page - 
![image](https://user-images.githubusercontent.com/38865341/60209354-21eee780-9863-11e9-8c12-523a8dba59dd.png)

category page
![image](https://user-images.githubusercontent.com/38865341/60209452-62e6fc00-9863-11e9-9b85-a0323f0b5da5.png)

**Comment by minhcasi** [comment]
Hi, please check this guide - https://docs.inspireui.com/listapp/theme/

Please provide your purchased screen to show us your purchase product, then reopen the ticket - thanks

**Comment by sorojon** [comment]
Thanks it helped
