### ISSUE TITLE
[Listapp] - Language switch bugs 1.7.2

### ISSUE THREAD

**Issue by reconshield** [inspireui/support#731]
1)when i switch language, its not call any language file contents. its display english only.. its in 1.7.2 version bugs.
no issue in previous version

2) i have 2 language. default is english and another one arabic... if switch to arabic..contents display right to left..how to make it like english... left to right?

**Comment by thangvo9x** [comment]
hi. Try to place this file at App/Components/Custom/
[Localization.txt](https://github.com/inspireui/support/files/3333921/Localization.txt)
change from .txt -> .js
2. change this file at Common folder - Languages file.
[Languages.txt](https://github.com/inspireui/support/files/3333936/Languages.txt)

**Comment by reconshield** [comment]
no..its still show English contents..
can check here : https://expo.io/@suthesan/indiansbiz

**Comment by thangvo9x** [comment]
![IMG_1062](https://user-images.githubusercontent.com/23457178/60783132-823f2c80-a173-11e9-9270-bce0d3e6181a.PNG)
HI. I can't access to your app. Share the Appconfig. I'll config and re-send to you.

**Comment by reconshield** [comment]
https://expo.io/@suthesan



-- 


  If you have any enquiries, please do not hesitate to contact us. Thank
You!

   Best Regards,


Customer Service, Reconshield Network

Website: reconshield.com <https://www.reconshield.com>  |  Helpdesk:
sales@reconshield.com
<https://www.facebook.com/reconshield> <https://twitter.com/suthesan>
<https://www.instagram.com/suthesan>


Confidentiality Warning: This e-mail message may contain confidential,
proprietary
or legally privileged information. It should not be accessed by anyone who
is not the original intended recipient. If you have erroneously received
this message, please delete it immediately and notify the sender. You will
appreciate that e-mail transmission cannot be guaranteed to be secure or
error-free as its contents are susceptible to loss, damage, interception,
destruction, etc. Before opening any attachments please check them for
viruses and defects.

If you don't wish to receive emails from us reply back with "Leave Out".

*Kindly consider the environmental impact before printing this email.*

**Comment by reconshield** [comment]
https://expo.io/@suthesan

**Comment by thangvo9x** [comment]
Hi @reconshield. Try to replace this file at App/RootRouter.js 
<img width="492" alt="Screen Shot 2019-07-11 at 2 56 03 PM" src="https://user-images.githubusercontent.com/23457178/61032625-026fc700-a3ec-11e9-8eb9-f159f3052826.png">
[Uploading RootRouter.txt…]()

Remember that change from .txt -> .js 
Thanks

**Comment by thangvo9x** [comment]
[RootRouter.txt](https://github.com/inspireui/support/files/3380847/RootRouter.txt)
