### ISSUE TITLE
[Mstore] - how to change the target api in expo project

### ISSUE THREAD

**Issue by santhoniral** [inspireui/support#732]
I got a error on target api level. when I upload the play store .

Screenshot -> https://user-images.githubusercontent.com/32481586/59737493-83b7bc00-927b-11e9-92d2-0280b8976edc.png

**Comment by santhoniral** [comment]
issue 2 : 
Facebook login not working in after play store ...but working fine in expo

Screenshot -> https://user-images.githubusercontent.com/32481586/59898290-b5f92300-940d-11e9-8c53-6058910d6a97.jpg

**Comment by minhcasi** [comment]
@santhoniral  - update to latest expo 3.9 will fix the fist issues 

The Facebook login should be updated to Live on your Developer Facebook App
