### ISSUE TITLE
M-Store Pro - Magento 2 - Paypal express checkout doesnt work

### ISSUE THREAD

**Issue by sodhanii** [inspireui/support#733]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue
PayPal express checkout doesn't work. Gives bad link error.›  

2. Screenshots

![Screen Shot 2019-06-28 at 1 19 15 PM](https://user-images.githubusercontent.com/47381386/60326482-5c619d00-99a7-11e9-8e0b-52f584322efa.png)

![Screen Shot 2019-06-28 at 1 18 52 PM](https://user-images.githubusercontent.com/47381386/60326502-671c3200-99a7-11e9-9955-14c5b7ab5680.png)

3. My screenshot of the purchase product or my comment:

3. Config files (optional)

**Comment by sodhanii** [comment]
License, etc.

<img width="641" alt="Screen Shot 2019-06-28 at 1 24 36 PM" src="https://user-images.githubusercontent.com/47381386/60326859-2244cb00-99a8-11e9-90da-0fdc3e4a72ab.png">
![Screen Shot 2019-06-28 at 1 24 28 PM](https://user-images.githubusercontent.com/47381386/60326860-22dd6180-99a8-11e9-9945-82758a37b3c7.png)

**Comment by sodhanii** [comment]
![Screen Shot 2019-06-28 at 1 24 28 PM](https://user-images.githubusercontent.com/47381386/60326884-325caa80-99a8-11e9-85c2-7ec1eb646199.png)

**Comment by minhcasi** [comment]
Note as upgrade feature on next version release

**Comment by minhcasi** [comment]
approved request
