### ISSUE TITLE
MStore Pro

### ISSUE THREAD

**Issue by tenkovroman** [inspireui/support#734]
<img width="557" alt="Снимок экрана 2019-06-28 в 18 32 48" src="https://user-images.githubusercontent.com/38020206/60345782-30f4a780-99d3-11e9-9c23-159760bc8c4a.png">
<img width="569" alt="Снимок экрана 2019-06-28 в 18 32 58" src="https://user-images.githubusercontent.com/38020206/60345783-30f4a780-99d3-11e9-8e2f-db7cc3bd5ce7.png">

**Comment by minhcasi** [comment]
Hi, please provide your purchase screenshot and reopen the ticket - thanks
