### ISSUE TITLE
[ListAPP] Login not working

### ISSUE THREAD

**Issue by avemnetworks** [inspireui/support#735]
Hello,

When trying to login from APP it shows following error

> No route was found matching the URL and request Method

what is causing this error? all other listings are fetching properly

**Comment by minhcasi** [comment]
Hi, please provide your purchase screenshot and reopen the ticket - thanks

**Comment by avemnetworks** [comment]
![purchase](https://user-images.githubusercontent.com/23519322/60390188-b456eb80-9aee-11e9-81f7-f690930ca129.png)
