### ISSUE TITLE
No publish in expo

### ISSUE THREAD

**Issue by RaptorHck** [inspireui/support#736]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue

- /Users/xxx/ListPro 1.3.4/source/assets/images/icons/*
Cannot read property 'forEach' of undefined

2. Screenshots

<img width="927" alt="Screen Shot 2019-06-28 at 6 52 37 PM" src="https://user-images.githubusercontent.com/7127855/60376641-f50f1180-99d5-11e9-9453-737c62733f80.png">

3. My screenshot of the purchase product or my comment:

3. Config files (optional)
{
  "expo": {
    "name": "ListPro",
    "description": "React Native app for Listing Directory, demo website: http://restaurant.inspireui.com",
    "slug": "listpro",
    "privacy": "public",
    "sdkVersion": "33.0.0",
    "version": "1.3.4",
    "orientation": "portrait",
    "primaryColor": "#fff",
    "icon": "./assets/icons/app-icon.png",
    "loading": {
      "icon": "./assets/icons/loading.png",
      "hideExponentText": false
    },
    "packagerOpts": {
      "assetExts": [
        "ttf",
        "mp4"
      ]
    },
    "assetBundlePatterns": [
      "assets/images/*",
      "assets/fonts/*",
      "assets/images/icons/*"
    ],
    "splash": {
      "image": "./assets/icons/loading.png",
      "resizeMode": "cover"
    },
    "ios": {
      "supportsTablet": true,
      "bundleIdentifier": "inspireui.listpro",
      "infoPlist": {
        "NSLocationWhenInUseUsageDescription": "Your current location will be displayed on the map and used for directions"
      },
      "loadJSInBackgroundExperimental": true,
      "buildNumber": "2"
    },
    "android": {
      "package": "inspireui.listpro",
      "versionCode": 4,
      "googleServicesFile": "./release/google-services.json"
    },
    "facebookAppId": "1809822172592320",
    "facebookDisplayName": "beoNews",
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "platforms": [
      "android",
      "ios"
    ]
  }
}

**Comment by minhcasi** [comment]
Hi, please provide your purchase screenshot and reopen the ticket - thanks

**Comment by RaptorHck** [comment]
<img width="771" alt="Screen Shot 2019-06-29 at 9 27 55 AM" src="https://user-images.githubusercontent.com/7127855/60385587-3b08bb80-9a50-11e9-8016-1c1d5618bb47.png">
