### ISSUE TITLE
[MMV] replace the welcome screen with the image

### ISSUE THREAD

**Issue by rianseven** [inspireui/support#737]
how can I replace the welcome screens with the image?

product: multivendor mstore
license: e1c19d73-87c3-4bee-afb4-9451b95dbc45

**Comment by rianseven** [comment]
Change the onboarding screen image

**Comment by rianseven** [comment]
hi how can i make it? Please help me

**Comment by thangvo9x** [comment]
You may change it in src/components/AppIntro/index.js
Thanks for your choice for our product.
