### ISSUE TITLE
[BeoNews] onesignal doesn't redirect to post

### ISSUE THREAD

**Issue by zziltong** [inspireui/support#738]
Product: Beonews pro

Your Purchased Code: 9f64a72f-f65c-4ecb-89ab-c109e7863821

When OneSignal push notification to mobile app, the app redirect to home page instead redirect to post.

I added this code in functions.php but onesignal doesn't redirect to post.

```
function onesignal_send_notification_filter($fields, $new_status, $old_status, $post)
{
    $fields['isAndroid'] = true;
    $fields['isIos'] = true;
    $fields['isAnyWeb'] = false;
    $fields['isChrome'] = false;
    $fields['data'] = array(
        "id" => $post->ID,
    );
    /* Unset the URL to prevent opening the browser when the notification is clicked */
    unset($fields['url']);
    return $fields;
}
add_filter('onesignal_send_notification', 'onesignal_send_notification_filter', 10, 4);

```

Thank you.

**Comment by minhcasi** [comment]
Hi, sorry for a lated response, we have noted this ticket for further investigating - thank you!

**Comment by ramyragab1** [comment]
+1 
i have same bug

**Comment by minhcasi** [comment]
Hi @zziltong @ramyragab1 try to debug your push message when creating new Post message, make sure it returns the additionalData as from RootRouter.js - https://tppr.me/pImlu - it works ok with our testing

You can check the detailed guide from - https://documentation.onesignal.com/docs/web-push-wordpress-faq#section-customizing-wordpress-plugin-behavior
