### ISSUE TITLE
[ListApp] - Step 2 - run the app

### ISSUE THREAD

**Issue by daniloaqui** [inspireui/support#74]
**Mandatory Info (please complete the following information):**
 - Product: [e.g. MStore, ListApp]
 - Your Purchased Code: [get from https://codecanyon.net/downloads]
(we may not reply if you are not our customer)

**Describe the issues**

**Screenshots**

**Additional context**
Step 2 - run the app
Extract the download package and go top project folder (where locate the package.json file), run following script

extract in the same folder from step 1, replace the files?

**Comment by minhcasi** [comment]
same root cause with https://github.com/inspireui/support/issues/73
