### ISSUE TITLE
When I try to create a new booking the app crashes

### ISSUE THREAD

**Issue by sorojon** [inspireui/support#741]
1.
![Screen Shot 2019-06-29 at 21 38 39](https://user-images.githubusercontent.com/38865341/60388252-77bbcd80-9ab7-11e9-9b6f-2b400d41aa53.png)
2.
![Screen Shot 2019-06-29 at 21 39 41](https://user-images.githubusercontent.com/38865341/60388256-7f7b7200-9ab7-11e9-8e85-b668791d1fab.png)
3.
![Screen Shot 2019-06-29 at 21 37 46](https://user-images.githubusercontent.com/38865341/60388258-87d3ad00-9ab7-11e9-9cd0-7d93b0e6e8f9.png)

**Comment by minhcasi** [comment]
Could you provide the screenshot of your purchased product then reopen the ticket - thank you!
