### ISSUE TITLE
[Listpro app] - categories images are not loaded

### ISSUE THREAD

**Issue by 0xsuid** [inspireui/support#743]
1.  ~~On Homepage categories (Category's list under banner) images are not loading~~

2. ~~screenshot - https://imgur.com/a/ovQeKEK~~

3. ~~Firebase notifications are also not working (I've added all config and the manually typed the code you've shown in video).~~

4. Where is the **code** you've shown in below video??
[Firebase Push notification config 1](https://www.youtube.com/watch?v=FVaYPe3S0OM&list=PLcF-HiQy-jOLg0O6d9uWhOqGhvvLfx6is&index=5&t=0s)
[Firebase Push notification config 2](https://www.youtube.com/watch?v=CSUZOXMqeAA&list=PLcF-HiQy-jOLg0O6d9uWhOqGhvvLfx6is&index=4&t=0s)

5. ~~**CHAT** is not working, when I click on chat button it shows pop up for review.~~

6. ~~Cant add new listing through your **android app** when I click on next it shows error (even in your demo app this is not working) : https://we.tl/t-UcUS6pB2iV~~

5. ~~Provide me your email so I can send you my purchase code.~~

**Comment by 0xsuid** [comment]
@minhcasi :ping_pong:

**Comment by minhcasi** [comment]
pls send to support@inspireui.com - thanks

**Comment by 0xsuid** [comment]
I've send an email.

**Comment by 0xsuid** [comment]
Any Update?? @minhcasi @thangvo9x

**Comment by 0xsuid** [comment]
It's been 3 days!!, are you guys even interested in providing support??? @minhcasi  @thangvo9x

**Comment by minhcasi** [comment]
Verified purchased, sorry as the team had some holiday trip - could you attach your config file here so we can have a quick check - thank you!

@thangvo9x

**Comment by 0xsuid** [comment]
Config File: https://thedesiworld.com/wp-content/uploads/2017/04/Config.zip 

@thangvo9x  @minhcasi

**Comment by 0xsuid** [comment]
Issue no. 5 is **most important** bug that needs to be resolved.

**Comment by thangvo9x** [comment]
TRy to replace this file at Container/Home/CategoryLinks/
P/s: remember that change from .txt -> .js 
[Item.txt](https://github.com/inspireui/support/files/3366974/Item.txt)

Thanks. I tested chat and post new listing work normal on your website.
this with post new listing case : you must Check config JWT plugin.
follow here: https://docs.inspireui.com/listpro/getting-started/#jwt-authentication
Thanks.

**Comment by 0xsuid** [comment]
That file has already .js extension and jwt is working as I have double checked it.

This issues are occuring on listpro's android application

**Comment by 0xsuid** [comment]
> 5\. Cant add new listing when click on next it shows error (even in your demo app this is not working) : https://we.tl/t-UcUS6pB2iV

Kindly check this on your demo application which is available in android playstore.

**Comment by 0xsuid** [comment]
Why There is no update on this????

@thangvo9x  @minhcasi

**Comment by 0xsuid** [comment]
Why everytime it takes 3 days to have one reply????

@thangvo9x @minhcasi

**Comment by thangvo9x** [comment]
Hi bro. Could you try to replace the file which was sent? and the image of the category will not display?

**Comment by 0xsuid** [comment]
> Hi bro. Could you try to replace the file which was sent? and the image of the category will not display?

Are you mad or in sleep while typing REPLY?????

Use Google translator if you are not able to understand ENGLISH @thangvo9x .

I SAID **Can't add new listing** through android app when click on next it shows error (**even in your demo app this is not working**) : https://we.tl/t-UcUS6pB2iV

**CHECK YOUR DEMO APP FIRST** : https://play.google.com/store/apps/details?id=inspireui.listpro&hl=en

IT IS NOT WORKING.

Which file you want me to replace now ??

**Comment by thangvo9x** [comment]
https://play.google.com/store/apps/details?id=inspireui.listpro&hl=en
Updated

**Comment by 0xsuid** [comment]
What did you updated?? I need to updated the same, kindly share details with me.

 @thangvo9x @minhcasi

**Comment by 0xsuid** [comment]
You didn't explained how you fixed that error :(

I did solved that without your help, for those who are wondering how to fix that error do the following:

**App\Components\MapView\Pick.js - Line:24**

```
      myPosition: {},
```

Replace **myPosition** with following:

```
      myPosition: {
        latitude: 0,
        longitude: 0
      },
```

**Comment by 0xsuid** [comment]
Now moving to issue no 5 - CHAT is not working, when I click on chat button it shows pop up for review in android application. @thangvo9x

**Comment by 0xsuid** [comment]
Hope that you will check issue of chat in android application today. @thangvo9x @minhcasi

**Comment by thangvo9x** [comment]
As this image. http://prntscr.com/of2ch3 this is a review function. NOT chat. The Chat function will be only displayed when you enter with the author is existing on your website and has post own user on that.

**Comment by 0xsuid** [comment]
Ahh, The icon for review is misleading.

Why is it required for users to have author role for adding new listing?

@thangvo9x

**Comment by thangvo9x** [comment]
Hi guy. You could config by following steps here 
https://www.youtube.com/playlist?list=PLcF-HiQy-jOLg0O6d9uWhOqGhvvLfx6is
user with author role. Because that is the security of the WordPress core.
Thanks

**Comment by 0xsuid** [comment]
@thangvo9x 

You didn't got my point, I was asking where is the code for firebase cloud function??

It is not provided in theme folder or anywhere.

**Comment by 0xsuid** [comment]
@thangvo9x @minhcasi 

You didn't got my point, I was asking where is the code for firebase cloud function??

It is not provided in theme folder or anywhere.

**Comment by macbethm** [comment]
Hi Oxsuid

Can you please help i cant view images on related posts, it seems ur familiar with this code
