### ISSUE TITLE
[MyListing] - Product Upload, Search, Map Products Loading Problems.

### ISSUE THREAD

**Issue by masonPy3** [inspireui/support#744]
** Don't know why you guys closed it, after @thangvo9x sent me the fixed version on email it didn't fixed my problem, it created new one that now I can't see tumbnails.
here is the old topic:
https://github.com/inspireui/support/issues/692
***

After going live version (not simulator) many problems have been solved but also many problems have come up:

1. I'm unable to upload products when I try to upload I click next and it stucks.. nothing happens.. Also can I set it up they will upload pictures from camera also? so they will take a picture and upload it.

2. Search is not working at all, not only for hebrew (my language but also in english)

3.  Map products are stuck on "Loading..." status.

4. After updating to the version @thangvo9x sent me I got new error the I don't see thumbnails.

    Screenshots

1. http://prntscr.com/o0afhk

2. http://prntscr.com/o0afyp
    2.1 http://prntscr.com/o0ag8x

3. http://prntscr.com/o0agje

Thanks in advance!

**Comment by thangvo9x** [comment]
Please tell me which platform you said. Could share your AppConfig and I'll check one more.

**Comment by masonPy3** [comment]
> 
> 
> Please tell me which platform you said. Could share your AppConfig and I'll check one more.

ListApp. I'll share it in my next comment.
Thanks

**Comment by masonPy3** [comment]
@thangvo9x 
AppConfig:
https://pastebin.com/H6KdZRwt

**Comment by thangvo9x** [comment]
Checked on your config. The error image not display. you must update your cover image each listing, upgrade to latest version of mylisting theme.
<img width="492" alt="3-mapsproduct" src="https://user-images.githubusercontent.com/23457178/61034162-f1748500-a3ee-11e9-87dd-aa5ebe410cc9.png">
Thanks.

**Comment by thangvo9x** [comment]
<img width="492" alt="Screen Shot 2019-07-11 at 3 18 11 PM" src="https://user-images.githubusercontent.com/23457178/61034239-1bc64280-a3ef-11e9-9261-384ce4c36bae.png">

**Comment by masonPy3** [comment]
@thangvo9x  Hi Thang, updated but still not working.
What version do you use? the one you sent me in gmail or the one you published?
Thanks
