### ISSUE TITLE
MStore - cebuilder issue

### ISSUE THREAD

**Issue by tenkovroman** [inspireui/support#745]
<img width="561" alt="Снимок экрана 2019-07-01 в 15 51 12" src="https://user-images.githubusercontent.com/38020206/60430981-13fce600-9c18-11e9-84a6-721ec1277ab5.png">
<img width="549" alt="Снимок экрана 2019-07-01 в 15 51 42" src="https://user-images.githubusercontent.com/38020206/60431000-20813e80-9c18-11e9-973e-a71d91a45fcf.png">

**Comment by minhcasi** [comment]
Hi, could you help to use the node js 10.x from downloading on this page - https://nodejs.org, then try with this script from the project folder:

yarn install
yarn start --reset-cache
react-native run-ios

**Comment by tenkovroman** [comment]
Did not help (((the problem remained
<img width="565" alt="Снимок экрана 2019-07-02 в 12 46 46" src="https://user-images.githubusercontent.com/38020206/60494028-752fc280-9cc7-11e9-98c0-491b99766203.png">

**Comment by tenkovroman** [comment]
Thanks for new version)))

**Comment by tenkovroman** [comment]
But any one problem
<img width="431" alt="Снимок экрана 2019-07-02 в 13 04 27" src="https://user-images.githubusercontent.com/38020206/60495385-1881d700-9cca-11e9-8b4f-774c85a7be4f.png">
<img width="427" alt="Снимок экрана 2019-07-02 в 13 04 31" src="https://user-images.githubusercontent.com/38020206/60495386-1a4b9a80-9cca-11e9-85ed-614d6881ddbc.png">

**Comment by minhcasi** [comment]
Hi, could you help to run the app via Cebuilder - https://inspireui.com - there are some automation script that could pass this issue - thanks

**Comment by tenkovroman** [comment]
<img width="771" alt="Снимок экрана 2019-07-05 в 12 20 56" src="https://user-images.githubusercontent.com/38020206/60705004-765b2c80-9f1f-11e9-88de-6b2437afa6e9.png">
<img width="732" alt="Снимок экрана 2019-07-05 в 12 21 07" src="https://user-images.githubusercontent.com/38020206/60705009-78bd8680-9f1f-11e9-9695-b036e2b45366.png">

**Comment by tenkovroman** [comment]
the project's customization does not open

**Comment by tenkovroman** [comment]
“Cebuilder.sh” cannot be opened because the Sandbox is not allowed to open documents in the Terminal. 
please help to fix it

**Comment by minhcasi** [comment]
Hi, i'm sorry for a lated response - could you help to download the latest 3.9.2 to fix the issue, if it still not work we could process the refund - thank you!

**Comment by MatiasHad** [comment]
The same thing happens to me and I have version 3.9.2
![Version3 9 2](https://user-images.githubusercontent.com/53048161/61595467-fc3cd000-abcd-11e9-8f4d-ba5c2278008a.png)

**Comment by minhcasi** [comment]
Hi, please download the latest 3.9.3 to fix this mstore-expo issue on cebuilder - thank you!
