### ISSUE TITLE
MStore Multi Vendor

### ISSUE THREAD

**Issue by Brown4d** [inspireui/support#746]
![error](https://user-images.githubusercontent.com/52418519/60447656-cf734980-9c1b-11e9-952f-847e7d8fbb8a.png)

hello i got the mstore multi vendor app and am trying to set it up with my site and keep getting dependency errors above. i succeeded in building the app but it wont install on my phone and i think it has to do with the errors above. 
![error2](https://user-images.githubusercontent.com/52418519/60447939-7ce65d00-9c1c-11e9-9da5-6b113de1720a.png)

**Comment by minhcasi** [comment]
Hi, could you provide the purchase product screenshot then reopen the ticket, thank you!
