### ISSUE TITLE
[ListApp] Login Not working

### ISSUE THREAD

**Issue by avemnetworks** [inspireui/support#747]
Reposting #735 can't reopen original one

here is purchased code 
https://user-images.githubusercontent.com/23519322/60390188-b456eb80-9aee-11e9-81f7-f690930ca129.png

Please help @minhcasi

**Comment by minhcasi** [comment]
Hi, the routing missing could cause by the in-complete config from Rest API, could you help to check this guide - https://docs.inspireui.com/listapp/getting-started/ - thank you!
