### ISSUE TITLE
[eva-store]- Wishlist screen not working

### ISSUE THREAD

**Issue by uzairahmedkhann** [inspireui/support#748]
In latest purchase, Wishlist screen shows error TypeError: undefined is not an object (evaluating ‘product.id’) 
---------
Screenshots
https://www.dropbox.com/s/a3op5wevc8vvkwq/IMG_2581.PNG?dl=0

**Comment by minhcasi** [comment]
Hi, could you help to take your purchase screenshot of this product - thank you!
