### ISSUE TITLE
BeoNews Pro (EXPO) - One Signal not connected

### ISSUE THREAD

**Issue by Blubagoo** [inspireui/support#749]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue

I have followed the steps provided among the numerous guides, and still am not seeing any users who are currently on my app or seeing any "Subscribed Users", monthly active users is always 0 even though im on the app. I also saw where for one signal to work it needs to be ejected. So i ran a build and installed the .apk file on a device and it still doesnt see any users. I also am unable to send a notification. 

2. Screenshots

I do not have any pictures as this is not a problem i can display in a picture.

3. My screenshot of the purchase product or my comment:

order id# 106193396

3. Config files (optional)

**Comment by minhcasi** [comment]
Hi, the expo version is not support for Onesignal, you can only use onesignal with the Mstore Pro (cli version) - thanks

**Comment by Blubagoo** [comment]
Then why does your documentation say otherwise?

https://docs.inspireui.com/faq/

**Comment by Blubagoo** [comment]
Also since I cant use expo i unzipped pro and tried to run it. I am getting the error

java.lang.SecurityException: Permission Denial: starting Intent
--

I have tried editing the androidmanifest.xml file as suggested and still the same error arises.

```<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.beonews"
    android:versionCode="1"
    android:versionName="1.0">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/> <!-- Approximate location - If you want to use promptLocation for letting OneSignal know the user location. -->
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/> <!--  Precise location If you want to use promptLocation for letting OneSignal know the user location. -->

    <uses-sdk
        android:minSdkVersion="16"
        android:targetSdkVersion="22" />

    <application
      android:name=".MainApplication"
      android:allowBackup="true"
      android:hardwareAccelerated="true"
      android:largeHeap="true"
      android:supportsRtl="true"
      android:label="@string/app_name"
      android:icon="@drawable/icon"
      android:theme="@style/SplashTheme">

      <activity
        android:launchMode="singleTop"
        android:name=".SplashActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:windowSoftInputMode="adjustResize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      <activity android:name=".MainActivity" android:exported="true">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
      <meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/facebook_app_id"/>
    </application>

</manifest>
```
