### ISSUE TITLE
[Beonews Pro] Charset Issue on custom pages

### ISSUE THREAD

**Issue by alexisttt** [inspireui/support#75]
[Beonews Pro]
Purchased Code: [3f684ec6-0043-4a19-b150-764a9f735121]

Hi. I have been trying to set up the app. It connects to my website posts and show the posts just fine. But in the contact and about us page the text are not displayed properly. I think it is a issue of charset. My website language is Turkish. You can see the problem in the screenshots. Thanks for your help.

in case you need 
my laptop os : Ubuntu 16.04.5 LTS 64-bit
My phone is Doogee s60 android 7.0

![photo_2018-12-04_12-54-23](https://user-images.githubusercontent.com/45356673/49433777-d3450780-f7c3-11e8-8727-d5115e746cac.jpg)
![photo_2018-12-04_12-54-36](https://user-images.githubusercontent.com/45356673/49433778-d3450780-f7c3-11e8-85b4-a43215cda4b3.jpg)
![photo_2018-12-04_12-54-39](https://user-images.githubusercontent.com/45356673/49433780-d3dd9e00-f7c3-11e8-9b05-3491913f0eae.jpg)
![photo_2018-12-04_12-54-41](https://user-images.githubusercontent.com/45356673/49433782-d4763480-f7c3-11e8-8f9f-c438b7a33948.jpg)

**Comment by luyx2412** [comment]
Hi @alexisttt Can you send me the Config.js file?
Thanks

**Comment by alexisttt** [comment]
Hi you can find the config.js bellow 

/** @format */

import Constants from './Constants'

export default {
  /**
   * There are so many choices from the marketplace mobile app, we thank you for choosing us and purchased the BeoNews products, please follow the step bellow to quickly set up your app
   * The detail document from: https://beonews.inspireui.com
   *
   * Step 1: Change your Wordpress site URL
   * Please make sure you have install all the Wordpress plugins - https://beonews.inspireui.com/step-2-installing-wordpress.html
   * On Mac OS, you need to create ~/Documents/FacebookSDK - https://beonews.inspireui.com/beonews-setup.html
   */
  URL: {
    root: 'https://firsatlar.28.com.tr',
  },

  /**
   * Step 2: config image and default layout post
   * HorizonLayout: show the horizontal layout config, show as the default homepage
   *    - Tags: the tag ids from Wordpress blog, it could be set as array [x, x...]
   *    - Categories: the category ids, , it could be set as array [x, x...]
   *    - row: the number of row support on the list, default is one row
   *    - paging: blog per page from swiping, default is false
   *    - layout: support 8 kind of layo Luts: banner, twoColumn, threeColumn, threeColumnHigh, list, listRight, card, flexColumn
   *      (flexColumn is flexible column layout that you can config both width & height)
   * Banner: option to show the banner home page, default visible is true
   * AdvanceLayout: mix layout config for AdvanceMode: card, column, list, banner, twoColumn, threeColumn, listRight
   */
  //
  HorizonLayout: [
    { tags: [11], paging: true, layout: Constants.Layout.banner },
    {
      name: 'Türkiye',
      categories: [2],
      layout: Constants.Layout.twoColumn,
    },
    {
      name: 'Avrupa',
      categories: [3],
      paging: true,
      row: 3,
      layout: Constants.Layout.list,
    },
    {
      name: 'Asya',
      categories: [4],
      layout: Constants.Layout.column,
    },
    {
      name: 'Kuzey Amerika',
      categories: [8],
      layout: Constants.Layout.flexColumn,
      width: 120,
      height: 250,
    },
    {
      name: 'Güney Amerika',
      categories: [9],
      paging: true,
      row: 3,
      layout: Constants.Layout.listRight,
    },
    {
      name: 'Okyanusya',
      categories: [10],
      paging: true,
      layout: Constants.Layout.card,
    },
    // {
    //   name: 'Afrika',
    //   categories: [10],
    //   paging: true,
    //   layout: Constants.Layout.card,
    // },
  ],
  Banner: {
    visible: true,
    sticky: true,
    tag: [10],
    categories: [4],
  },
  // The advance layout
  AdvanceLayout: [
    Constants.Layout.threeColumn,
    Constants.Layout.threeColumn,
    Constants.Layout.threeColumn,
    Constants.Layout.list,
    Constants.Layout.list,
    Constants.Layout.list,
    Constants.Layout.list,
    Constants.Layout.card,
    Constants.Layout.column,
    Constants.Layout.column,
  ],

  /**
   * Step 3: Advance config
   * CategoryVideo: config the category id for video page
   *
   * */
  // Category video id from the menu
  CategoryVideo: 34,

  imageCategories: {
    turkiye: require('@images/category/cate1.jpg'),
    avrupa: require('@images/category/cate2.jpg'),
    asya: require('@images/category/cate3.jpg'),
    kamerika: require('@images/category/cate5.jpg'),
    gamerika: require('@images/category/cate6.jpg'),
    okyanusya: require('@images/category/cate7.jpg'),
    'kids-menu': require('@images/category/cate8.jpg'),
    'quick-recipes': require('@images/category/cate9.jpg'),
    deserts: require('@images/category/cate10.jpg'),
    recipes: require('@images/category/cate11.jpg'),
    afrika: require('@images/category/cate12.jpg'),
    featured: require('@images/category/cate16.jpg'),
    all: require('@images/category/cate14.jpg'),
  },

  // Custom page from left menu side
  CustomPages: {
    contact_id: 71,
    aboutus_id: 73,
  },

  // config for Firebase, use to sync user data across device and favorite post
  Firebase: {
    apiKey: '1:35684462590:android:e278ea47784c452e',
    authDomain: 'yirmi-sekiz-1543399593216.firebaseapp.com',
    // databaseURL: 'https://beonews-ef22f.firebaseio.com',
    // storageBucket: 'beonews-ef22f.appspot.com',
    // messagingSenderId: '1008301626030',
    readlaterTable: 'list_readlater',
  },

  // config for log in by Facebook
  Facebook: {
    showAds: false,
    adPlacementID: '',
    logInID: '451470391924254',
    sizeAds: 'standard', // standard, large
  },

  // config for log in by Google
  // Google: {
  //   analyticId: 'UA-90561349-1',
  //   androidClientId:
  //     '338838704385-1om86241pq2qpg4qi677jb1ndo5jqfh2.apps.googleusercontent.com',
  //   iosClientId:
  //     '338838704385-1om86241pq2qpg4qi677jb1ndo5jqfh2.apps.googleusercontent.com',
  // },

  // config for log in by Admob
  AdMob: {
    visible: false,
    // deviceID: 'pub-2101182411274198',
    // unitID: 'ca-app-pub-2101182411274198/9145196933',
    // unitInterstitial: 'ca-app-pub-2101182411274198/7326078867',
    // isShowInterstital: true,
  },

  // tab animate
  tabBarAnimate: Constants.Animate.zoomIn,

  // config default for left menu
  LeftMenuStyle: Constants.LeftMenu.overlay,

  notification: {
    AppId: 'bfdd7a47-733c-440d-bf76-855a3bce8c5e',
    NewAppId: '88b0e176-5756-47b7-b061-aacea262421d',
  },

  OneSignal: {
    appId: 'bfdd7a47-733c-440d-bf76-855a3bce8c5e'
  },

  // update 18 May
  // showLayoutButton: Ability to show/hide the switch layout button at homescreen
  // homeLayout: default homeLayout UI: Constants.Layout.mansory, Constants.Layout.horizontal
  // showSwitchCategory: show the switch button on categories page
  showLayoutButton: true,
  homeLayout: Constants.Layout.horizontal,
  showSwitchCategory: true,

  // update 18 Sep
  showAppIntro: true,
  intro: [
    {
      title: 'Aramıza hoşgeldiniz | 28',
      description: 'Bildirimler ile en son fırsatlardan haberdar ol.',
      backgroundColor: '#D5E8ED',
      source: require('@images/lottie/loading.json'),
      button: "Başlayalım"
    }, {
      title: 'Kullanması Süper Kolay',
      description: 'Uygulamayı kullanmak süper kolay',
      backgroundColor: '#FFF',
      source: require('@images/lottie/check_animation.json'),
      button: "Sıradaki"
    }, {
      title: 'Anlık Bildirimler',
      description: 'En yeni fırsatlardan bildirimler ile ilk senin haberin olacak. Offline modda mevcut',
      backgroundColor: '#D6D7DD',
      source: require('@images/lottie/notification.json'),
      button: "Tamam"
    }
  ],
}

**Comment by alexisttt** [comment]
I look deep inside of the code but could not figure out how to translate a / two days ago or minutes phrase.  Also could you guide me to how to translate it? 
Many thanks

**Comment by luyx2412** [comment]
Hi @alexisttt 
I tested your Config.js file which working normal.
<img width="376" alt="screen shot 2018-12-06 at 10 37 22 am" src="https://user-images.githubusercontent.com/8909619/49559928-14175a80-f943-11e8-8059-aceaf8bb82bd.png">

And i didn't understand your question about translate a / two days ago or minutes which is post time. If it is post time ago, you can see `App/Container/PostDetail/PostDetail.js` in line 100 with code `<TimeAgo time={post.date} hideAgo /> ago`. You can edit in this line.

Thanks

**Comment by alexisttt** [comment]
Hi thanks for answer. App works fine with post. It shows exactly what ever we have. But when we click contact us and about us from left navigation we get pages with issues.

**Comment by luyx2412** [comment]
Hi @alexisttt Please remove app on your emulator and re-install again. I tested about us and contact us which work normal.
<img width="380" alt="screen shot 2018-12-07 at 9 36 28 am" src="https://user-images.githubusercontent.com/8909619/49624350-abdc7d80-fa03-11e8-8dc6-db95eaec11a8.png">
<img width="382" alt="screen shot 2018-12-07 at 9 35 16 am" src="https://user-images.githubusercontent.com/8909619/49624351-abdc7d80-fa03-11e8-8d20-6f4adcf2f1de.png">
Thanks

**Comment by alexisttt** [comment]
Hi.  Thanks for reply i have deleted and re-install the app to my phone but nothing changed. I still get the issue. Do you think is it because of the device?
Thanks

**Comment by luyx2412** [comment]
Hi @alexisttt 
Can you provide me your device information?
Thanks

**Comment by luyx2412** [comment]
Hi @alexisttt, i investigated your case and found the issue is related `font family`.  So in `App/Components/WebView/WebView.js` line 48. In source property please add `baseUrl: ''` look like the comment to fix the issue. And it is full source code file.

```
/** @format */

import React, { PureComponent } from 'react'
import PropTypes from 'prop-types'
import { WebView, Dimensions, Platform } from 'react-native'

const { width, scale } = Dimensions.get('window')
const newScale = Platform.OS == 'ios' ? scale : 1

export default class WebViewComponent extends PureComponent {
  static propTypes = {
    html: PropTypes.any,
  }

  constructor(props) {
    super(props)

    this.state = {
      webViewHeight: 600,
    }
  }

  updateHeight = (event) => {
    this.setState({ webViewHeight: parseInt(event.jsEvaluationValue) })
  }

  render() {
    const getHTML = () => {
      const html = this.props.html

      return `<html><head><style type="text/css">
				      body {
				        font: 14pt arial, sans-serif;
				        background: white;
				      }
				      a, h1, h2, h3, p, li, div {
				        font: 22px arial, sans-serif !important;
				      }
				      img {
				        height: auto;
				        width: ${(width - 15) * newScale}px
              }
				</style></head><body>${html}</body>`
    }

    return (
      <WebView
        source={{ html: getHTML(), baseUrl: '' }}
        injectedJavaScript="document.body.scrollHeight;"
        onNavigationStateChange={this.updateHeight}
        style={{
          height: 900,
          fontSize: 30,
        }}
      />
    )
  }
}
```
