### ISSUE TITLE
[Mstore] - Facebook login not working in after play store ...but working fine in expo 

### ISSUE THREAD

**Issue by santhoniral** [inspireui/support#750]
Facebook login not working in after play store ...but working fine in expo
please see the Screenshot -> https://user-images.githubusercontent.com/32481586/59898290-b5f92300-940d-11e9-8c53-6058910d6a97.jpg

The Facebook login aslo be updated to Live on my Developer Facebook App
![Screenshot_2](https://user-images.githubusercontent.com/32481586/60565780-77a32280-9d82-11e9-9b6f-d02b1083474c.png)

**Comment by santhoniral** [comment]
please reply fast...its very important for me...

**Comment by minhcasi** [comment]
can you debug the app to see the detail log after sign in by FB ?

**Comment by santhoniral** [comment]
how to debug the app?

**Comment by santhoniral** [comment]
screenshot -> https://user-images.githubusercontent.com/32481586/59898290-b5f92300-940d-11e9-8c53-6058910d6a97.jpg

login via facebbok

**Comment by minhcasi** [comment]
Hi, could I check if you have debugged to find out this issue?

**Comment by santhoniral** [comment]
how to check the debugged???

**Comment by minhcasi** [comment]
Hi, pls use reactotron - https://github.com/infinitered/reactotron/blob/master/docs/installing.md - it's already integrated with the app
