### ISSUE TITLE
 MStore Pro - Complete React Native

### ISSUE THREAD

**Issue by myamman** [inspireui/support#751]
. My issue
1- big space under products list need to be deleted
2- when enter category products list then enter same categorys from category tab the list duplicated
3- currency not changing 
4- payment cach on delivery not working
5- payment direct bank transfair not working
6- how to add photo to direct bank transfair 
7- cart not empty after logout 
8- on re-login the cart empty even it was has products befor logout 
screenshot : 
https://drive.google.com/open?id=1zFD5x3_b6kqGEkGxgWOOTH6kAahlLEnQ
3. My screenshot of the purchase product or my comment:
https://drive.google.com/open?id=1zFD5x3_b6kqGEkGxgWOOTH6kAahlLEnQ

**Comment by myamman** [comment]
any replay

**Comment by minhcasi** [comment]
Hi, could you check the latest 3.9.1 that have fixed the #1 & #2 issues.

We have forward other issues to the team for checking and will keep an update - thanks

**Comment by myamman** [comment]
> Hi, could you check the latest 3.9.1 that have fixed the #1 & #2 issues.
> 
> We have forward other issues to the team for checking and will keep an update - thanks

thanks for your replay , how many time you need  to fix all problem , because  Idont have enough time
thanks for you so much

**Comment by myamman** [comment]
no answer until now

**Comment by minhcasi** [comment]
3- currency not changing
4- payment cach on delivery not working
5- payment direct bank transfair not working
6- how to add photo to direct bank transfair
7- cart not empty after logout
8- on re-login the cart empty even it was has products befor logout
----
Hi, sorry for a lated response, this is the feedback from our team

3- as the currency switching relate to the exchange library so may remove this feature on next release
4-5- test and work fine, you can check our demo.
6- you can edit the config.js file to update the image link for the payment 
7.8- will fix on next version

So, your problem could be related to the checkout plugin, please help to check this solution - https://docs.inspireui.com/mstore/questions/#404-error-page-when-process-the-payment- - thank you!
