### ISSUE TITLE
[listapp]Category not working

### ISSUE THREAD

**Issue by kjagne** [inspireui/support#752]
Invariant Violation: Invariant Violation: [2813,"RCTImageView",{"height":"<<NaN>>","width":null,"transform":[{"translateY":"<<NaN>>"}]}] is not usable as a native method argument

This error is located at:
    in RCTImageView (at Image.android.js:254)
    in Image (at createAnimatedComponent.js:151)
    in AnimatedComponent (at ParallaxImage.js:97)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at ParallaxImage.js:92)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at TouchableOpacity.js:282)
    in TouchableOpacity (at ParallaxImage.js:109)
    in ParallaxImage (at Categories/index.js:86)
    in RCTView (at View.js:45)
    in View (at VirtualizedList.js:1762)
    in CellRenderer (at VirtualizedList.js:688)
    in RCTView (at View.js:45)
    in View (at ScrollView.js:976)
    in RCTScrollView (at ScrollView.js:1115)
    in ScrollView (at VirtualizedList.js:1081)
    in VirtualizedList (at FlatList.js:632)
    in FlatList (at ParallaxScrollViewComposition.js:59)
    in ParallaxScrollViewComposition (at Categories/index.js:137)
    in RCTView (at View.js:45)
    in View (at Categories/index.js:178)
    in Categories (created by Connect(Categories))
    in Connect(Categories) (at CategoriesScreen.js:17)
    in CategoriesScreen (at react-native-safe-area-view/index.js:365)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at react-native-safe-area-view/index.js:153)
    in SafeView (at withOrientation.js:54)
    in withOrientation (at react-native-safe-area-view/index.js:364)
    in withSafeArea (at SceneView.js:9)
    in SceneView (at StackViewLayout.tsx:888)
    in RCTView (at View.js:45)
    in View (at StackViewLayout.tsx:887)
    in RCTView (at View.js:45)
    in View (at StackViewLayout.tsx:886)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at StackViewCard.tsx:93)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at screens.native.js:59)
    in Screen (at StackViewCard.tsx:80)
    in Card (at createPointerEventsContainer.tsx:95)
    in Container (at StackViewLayout.tsx:971)
    in RCTView (at View.js:45)
    in View (at screens.native.js:83)
    in ScreenContainer (at StackViewLayout.tsx:383)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at StackViewLayout.tsx:379)
    in PanGestureHandler (at StackViewLayout.tsx:372)
    in StackViewLayout (at withOrientation.js:30)
    in withOrientation (at StackView.tsx:103)
    in RCTView (at View.js:45)
    in View (at Transitioner.tsx:267)
    in Transitioner (at StackView.tsx:40)
    in StackView (at createNavigator.js:61)
    in Navigator (at createKeyboardAwareNavigator.js:12)
    in KeyboardAwareNavigator (at SceneView.js:9)
    in SceneView (at createTabNavigator.js:39)
    in RCTView (at View.js:45)
    in View (at ResourceSavingScene.js:37)
    in RCTView (at View.js:45)
    in View (at ResourceSavingScene.js:26)
    in ResourceSavingScene (at createBottomTabNavigator.js:121)
    in RCTView (at View.js:45)
    in View (at screens.native.js:83)
    in ScreenContainer (at createBottomTabNavigator.js:111)
    in RCTView (at View.js:45)
    in View (at createBottomTabNavigator.js:110)
    in TabNavigationView (at createTabNavigator.js:197)
    in NavigationView (at createNavigator.js:61)
    in Navigator (at createAppContainer.js:429)
    in NavigationContainer (at RootRouter.js:82)
    in RCTView (at View.js:45)
    in View (at DrawerLayoutAndroid.android.js:198)
    in AndroidDrawerLayout (at DrawerLayoutAndroid.android.js:217)
    in DrawerLayoutAndroid (at MenuAndroid.js:35)
    in MenuAndroid (created by Connect(MenuAndroid))
    in Connect(MenuAndroid) (at RootRouter.js:86)
    in RCTView (at View.js:45)
    in View (at RootRouter.js:107)
    in RootRouter (created by Connect(RootRouter))
    in Connect(RootRouter) (at App.js:169)
    in Provider (at App.js:168)
    in App (at react-native-safe-area-view/index.js:365)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at react-native-safe-area-view/index.js:153)
    in SafeView (at withOrientation.js:54)
    in withOrientation (at react-native-safe-area-view/index.js:364)
    in withSafeArea (at withExpoRoot.js:20)
    in RootErrorBoundary (at withExpoRoot.js:19)
    in ExpoRootComponent (at renderApplication.js:35)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:98)
    in RCTView (at View.js:45)
    in View (at react-native-root-siblings/index.js:34)
    in RootSiblingsWrapper (at AppContainer.js:112)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:115)
    in AppContainer (at renderApplication.js:34)

This error is located at:
    in NavigationContainer (at RootRouter.js:82)
    in RCTView (at View.js:45)
    in View (at DrawerLayoutAndroid.android.js:198)
    in AndroidDrawerLayout (at DrawerLayoutAndroid.android.js:217)
    in DrawerLayoutAndroid (at MenuAndroid.js:35)
    in MenuAndroid (created by Connect(MenuAndroid))
    in Connect(MenuAndroid) (at RootRouter.js:86)
    in RCTView (at View.js:45)
    in View (at RootRouter.js:107)
    in RootRouter (created by Connect(RootRouter))
    in Connect(RootRouter) (at App.js:169)
    in Provider (at App.js:168)
    in App (at react-native-safe-area-view/index.js:365)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at react-native-safe-area-view/index.js:153)
    in SafeView (at withOrientation.js:54)
    in withOrientation (at react-native-safe-area-view/index.js:364)
    in withSafeArea (at withExpoRoot.js:20)
    in RootErrorBoundary (at withExpoRoot.js:19)
    in ExpoRootComponent (at renderApplication.js:35)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:98)
    in RCTView (at View.js:45)
    in View (at react-native-root-siblings/index.js:34)
    in RootSiblingsWrapper (at AppContainer.js:112)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:115)
    in AppContainer (at renderApplication.js:34)
enqueueNativeCall
    C:\Users\karaj\OneDrive\Desktop\LIstAPP\source\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:253:8
fn
    C:\Users\karaj\OneDrive\Desktop\LIstAPP\source\node_modules\react-native\Libraries\BatchedBridge\NativeModules.js:137:8
commitUpdate
    C:\Users\karaj\OneDrive\Desktop\LIstAPP\source\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:4216:6
commitWork
    C:\Users\karaj\OneDrive\Desktop\LIstAPP\source\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:15766:12
commitAllHostEffects
    C:\Users\karaj\OneDrive\Desktop\LIstAPP\source\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:16580:19
invokeGuardedCallbackImpl
    C:\Users\karaj\OneDrive\Desktop\LIstAPP\source\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:93:15
invokeGuardedCallback
    C:\Users\karaj\OneDrive\Desktop\LIstAPP\source\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:318:36
commitRoot
    C:\Users\karaj\OneDrive\Desktop\LIstAPP\source\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:16836:28
<unknown>
    C:\Users\karaj\OneDrive\Desktop\LIstAPP\source\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:18501:17
unstable_runWithPriority
    C:\Users\karaj\OneDrive\Desktop\LIstAPP\source\node_modules\scheduler\cjs\scheduler.development.js:255:23
completeRoot
    C:\Users\karaj\OneDrive\Desktop\LIstAPP\source\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:18499:4
performWorkOnRoot
    C:\Users\karaj\OneDrive\Desktop\LIstAPP\source\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:18427:21
performWork
    C:\Users\karaj\OneDrive\Desktop\LIstAPP\source\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:18324:24
performSyncWork
    C:\Users\karaj\OneDrive\Desktop\LIstAPP\source\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:18285:14
requestWork
    C:\Users\karaj\OneDrive\Desktop\LIstAPP\source\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:18169:19
scheduleWork
    C:\Users\karaj\OneDrive\Desktop\LIstAPP\source\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:17969:16
enqueueSetState
    C:\Users\karaj\OneDrive\Desktop\LIstAPP\source\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:6934:17
setState
    C:\Users\karaj\OneDrive\Desktop\LIstAPP\source\node_modules\react\cjs\react.development.js:335:31
handleMeasure
    C:\Users\karaj\OneDrive\Desktop\LIstAPP\source\App\Components\Custom\react-native-parallax\ParallaxImage.js:52:18
__invokeCallback
    C:\Users\karaj\OneDrive\Desktop\LIstAPP\source\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:414:4
<unknown>
    C:\Users\karaj\OneDrive\Desktop\LIstAPP\source\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:127:28
__guard
    C:\Users\karaj\OneDrive\Desktop\LIstAPP\source\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:314:10
invokeCallbackAndReturnFlushedQueue
    C:\Users\karaj\OneDrive\Desktop\LIstAPP\source\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:126:17

**Comment by minhcasi** [comment]
can you provide the purchase screenshot and explain the detailed step of the problem - thanks

**Comment by kjagne** [comment]
![Capture](https://user-images.githubusercontent.com/29099493/60680518-2fb3f680-9e7b-11e9-923b-9d0c8774bc18.PNG)

**Comment by kjagne** [comment]
When you click on the category icon it gives this type of error

**Comment by kjagne** [comment]
![Capture1](https://user-images.githubusercontent.com/29099493/60680637-976a4180-9e7b-11e9-8407-1c077cdbb384.PNG)

thats the category icon
