### ISSUE TITLE
unable to deploy to ios ERROR ITMS-90596: "Invalid Bundle.

### ISSUE THREAD

**Issue by huzefaid** [inspireui/support#753]
Package Summary:
 
1 package(s) were not uploaded because they had problems:
	/var/folders/rx/5vfk4qp96zg45s_9rs0941sw0000gn/T/4349B288-38B1-47F6-A2EF-91CE3D6AEC91/1471335457.itmsp - Error Messages:
		description length:8466981
		ERROR ITMS-90596: "Invalid Bundle. The asset catalog at 'Payload/ExpoKitApp.app/Assets.car' can't be processed. Rebuild your app, and all included extensions and frameworks, with the latest GM version of Xcode and resubmit."

**Comment by huzefaid** [comment]
had build ipa from cebuilder and uploaded with xcode application loader

**Comment by minhcasi** [comment]
Hi, could we know what is the product you have purchased? Thanks
