### ISSUE TITLE
[MStore Pro] - Not able to go to My Order screen if My Order is removed from bottom tab nav

### ISSUE THREAD

**Issue by phase06** [inspireui/support#754]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue
I removed the MyOrders from bottom tab navigation, but when i try to click My Orders from UserProfileScreen, it cannot goto My Orders screen
2. Screenshots

3. My screenshot of the purchase product or my comment:
<img width="617" alt="Screenshot 2019-07-04 at 1 02 28 AM" src="https://user-images.githubusercontent.com/18529796/60610906-9394db80-9df7-11e9-8a0e-f3cf7311b3cb.png">

3. Config files (optional)

**Comment by minhcasi** [comment]
Hi, you can try to hide the MyOrder from the tabbar.js, instead of removing it out the navigation that causes the missing routing - thanks

**Comment by phase06** [comment]
thanks for the info. its working now.
