### ISSUE TITLE
I'm getting this error when I try to run the app

### ISSUE THREAD

**Issue by olaos** [inspireui/support#755]
. Screenshots
https://imgur.com/PUo7AN5

**Comment by minhcasi** [comment]
Hi, could we know what is the product and your purchase screenshot - thank you!

**Comment by olaos** [comment]
BeoNews Pro - React Native mobile app for Wordpress
Item Purchase Code: cf27bce7-39a9-4a1b-8c52-5352159a9518

**Comment by olaos** [comment]
Why you closed this issue?
I need help.
