### ISSUE TITLE
mstore-pro

### ISSUE THREAD

**Issue by priyaghule173** [inspireui/support#756]
Hi team,
We are going through your MStore PRO code however we are facing little bit challenges with the flow of the code.
We wanted to customize the UI as per our needs but unable to do so.
I will be very grateful to you, if you can take out some time and explain the basic flow.
It will be good, if you have some document/video or can arrange 15-20 mins meeting which explains how to customize application UI.
This project is quite urgent and we need your help asap.

**Some images of the theme are not coming.Coming as a blank**

https://drive.google.com/drive/folders/1J2hGK82GhRyntIqP2BXiwJZ4QA93DXxZ?usp=sharing

**Comment by minhcasi** [comment]
Hi, you can attach your config file here so that we could check the issues.

Also, please help to provide your purchase product screenshot - thank you!

**Comment by priyaghule173** [comment]
screenshot of product purchased

![picturemessage_eytsq0gc vvb](https://user-images.githubusercontent.com/21154121/60698212-00999580-9f0c-11e9-87e2-c783a396029d.png)

config files

[Desktop.zip](https://github.com/inspireui/support/files/3361149/Desktop.zip)

can you please tell us if we want to customize one of the part then how to do that.There is no proper documentation for that

**Comment by minhcasi** [comment]
closed as support via email - priyapopatghule@gmail.com
