### ISSUE TITLE
[ListPro] Problem with single listing in App.

### ISSUE THREAD

**Issue by gianlucoso** [inspireui/support#758]
Hi. i build my app following your documentation and works fine in the first building (with http://restaurant.inspireui.com) but when i put my website (https://comprago.tk) the data read fine in the app but when i enter to a single listing my app crash and show this message, then reload JS build. Please i need help. thanks 

Item Purchase Code: 29c8e7a4-8029-461e-8041-4a8ec82f0c73

![IMG_2524](https://user-images.githubusercontent.com/14884807/60685510-cda6c180-9e79-11e9-8e8c-0064b4adb54a.jpg)
![IMG_2523](https://user-images.githubusercontent.com/14884807/60685511-cda6c180-9e79-11e9-8054-b6c102428396.jpg)

**Comment by thangvo9x** [comment]
Hi guy. Try to replace this file at App/Components/Detail/Section/
[index.txt](https://github.com/inspireui/support/files/3380860/index.txt)

Remember that change from .txt tag -> .js tag and let me know if you've resolved yet.
Thanks
