### ISSUE TITLE
[mstore-pro] - 

### ISSUE THREAD

**Issue by IvoKalu** [inspireui/support#759]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue
The app does not lock the screen vertically.
I changed the orientation on AndroidManifest and i tried all the fixes suggested but nothing works and the app looks really bad when you flip the phone horizontally. So please help us out here with a fix.
2. Screenshots
![Screenshot_20190705-110628_BueShopping](https://user-images.githubusercontent.com/8544219/60711473-eca26380-9f0c-11e9-89c1-b2d854d381a8.jpg)
3. My screenshot of the purchase product or my comment:
![mstore](https://user-images.githubusercontent.com/8544219/60711752-76523100-9f0d-11e9-93f9-f16624c585ea.png)

3. Config files (optional)

**Comment by minhcasi** [comment]
Hi, thank you for reporting, we've noted as feature upgrade for the fixing - thank you!

**Comment by minhcasi** [comment]
Hi, please use this library for locking the orientation - https://github.com/wonday/react-native-orientation-locker

the expo version could be locked by this setting - https://docs.expo.io/versions/latest/sdk/screen-orientation/

The team is investigating to adapt both orientations - thank you!
