### ISSUE TITLE
[MStore] - How to Change & set Default Country to Netherlands

### ISSUE THREAD

**Issue by hammadhassan** [inspireui/support#76]
How should i set default country to Netherlands as checkout page keep showing does not ship to Netherlands.

![image](https://user-images.githubusercontent.com/5791268/49466906-ffdc3c00-f822-11e8-95a9-778797971d5e.png)

Kindly Help

Config file country setting

DefaultCountry: {
code: 'nl',
RTL: false, // em move config tu ben Constanst qua day de user ho de su dung
language: 'Dutch',
countryCode: "NL",
hideCountryList: false// when this option is try we will hide the country list from the checkout page, default select by the above 'countryCode'
},

**Comment by hammadhassan** [comment]
I did select United States, United Kingdom & Vietnam from countryPicker but same text occurs in payment page that we do not ship to United States, United Kingdom & Vietnam.

Kindly guide me to fix this issue ASAP as my is pending due to this issue.

Thanks.

**Comment by luyx2412** [comment]
Hi @hammadhassan Can you provide your Config.js file?
Thanks

**Comment by hammadhassan** [comment]
Config file it attached.

Please try to fix this ASAP.

[Config3.6.4.zip](https://github.com/inspireui/support/files/2651855/Config3.6.4.zip)

**Comment by luyx2412** [comment]
Hi @hammadhassan Please mail your account wordpress to luyxtran264@gmail.com. I will check your admin site.
Thanks

**Comment by hammadhassan** [comment]
I sent you an email.

Please check & guide to fix it.

Thanks.

**Comment by luyx2412** [comment]
Ok @hammadhassan

**Comment by hammadhassan** [comment]
@luyx2412 is there any update to fix my issue?

**Comment by luyx2412** [comment]
Hi @hammadhassan i checked your Config and your website. I fixed `undefined` country will update next version, and with can not shipping to Netherland. We need investigating the issue.

Thanks

**Comment by hammadhassan** [comment]
@luyx2412 regarding to Netherlands. When i select different country it shows the same text as well.

When will you going to publish next version as my app is pending to publish.

**Comment by hammadhassan** [comment]
Could you also provide the updated config file to me so that i can also check it by myself.

**Comment by luyx2412** [comment]
Hi @hammadhassan 
In `src/containers/Home/index.js` replace with this code
```/**
 * Created by InspireUI on 19/02/2017.
 *
 * @format
 */

import React, { PureComponent } from "react";
import PropTypes from "prop-types";
import { View } from "react-native";
import { connect } from "react-redux";
import { Constants, withTheme } from "@common";
import { HorizonList, ModalLayout, PostList } from "@components";
import { isEmpty } from "lodash";

import styles from "./styles";

class Home extends PureComponent {
  static propTypes = {
    fetchAllCountries: PropTypes.func.isRequired,
    layoutHome: PropTypes.any,
    onViewProductScreen: PropTypes.func,
    onShowAll: PropTypes.func,
    showCategoriesScreen: PropTypes.func,
  };

  componentDidMount() {
    const { fetchAllCountries, isConnected, countries } = this.props;
    if (isConnected) {
      const { list } = countries;
      if (!list || isEmpty(list)) {
        fetchAllCountries();
      }
    }
  }

  render() {
    const {
      layoutHome,
      onViewProductScreen,
      showCategoriesScreen,
      onShowAll,
      theme: {
        colors: { background },
      },
    } = this.props;

    const isHorizontal = layoutHome === Constants.Layout.horizon;
    return (
      <View style={[styles.container, { backgroundColor: background }]}>
        {isHorizontal && (
          <HorizonList
            onShowAll={onShowAll}
            onViewProductScreen={onViewProductScreen}
            showCategoriesScreen={showCategoriesScreen}
          />
        )}
        {!isHorizontal && (
          <PostList onViewProductScreen={onViewProductScreen} />
        )}
        <ModalLayout />
      </View>
    );
  }
}

const mapStateToProps = ({ products, countries, netInfo }) => ({
  layoutHome: products.layoutHome,
  countries,
  isConnected: netInfo.isConnected,
});

function mergeProps(stateProps, dispatchProps, ownProps) {
  const { dispatch } = dispatchProps;
  const CountryRedux = require("@redux/CountryRedux");
  return {
    ...ownProps,
    ...stateProps,
    fetchAllCountries: () => CountryRedux.actions.fetchAllCountries(dispatch),
  };
}

export default withTheme(
  connect(
    mapStateToProps,
    undefined,
    mergeProps
  )(Home)
);```

This is fix `undefined` country, and in Config.js file please set `hideCountryList: true`

P/S: I will plan to update new version soon.

Thanks

**Comment by luyx2412** [comment]
Hi @hammadhassan Can you provide again your account wordpress. I will check your case.
Thanks

**Comment by hammadhassan** [comment]
You did not provide the solution & closed the case.

How i gonna publish my app if the shipping is not working?
