### ISSUE TITLE
[Mstore Multi Vendors] - The application is restarted when view Tab Categories, My Order

### ISSUE THREAD

**Issue by chuabip10** [inspireui/support#760]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue
- The Vendor tab only shows Customer, that is not a Vendor
- When switching the View interface, the application is restarted or error 
- Add products are defective, not filled in price and product name, JWT is not configurated properly
- See My Order, the application is restarted or error
2. Screenshots

3. My screenshot of the purchase product or my comment:
Purchase code: 2fba8b41-9f32-48f3-8b61-6c21e15d2a97
3. Config files (optional)
[AppConfig.txt](https://github.com/inspireui/support/files/3363638/AppConfig.txt)
[Config.txt](https://github.com/inspireui/support/files/3363639/Config.txt)

**Comment by thangvo9x** [comment]
Hi. Try to replace this file at src/Redux/actions/
Remember that change from .js -> .txt

[VendorRedux.txt](https://github.com/inspireui/support/files/3384722/VendorRedux.txt)
Thanks . let me know if it works.

**Comment by chuabip10** [comment]
Displayed the Vendor but still have the following errors
1. When switching the View interface, see Tab Category, see My Orderthe, application is restarted or error
2. Add products are defective, not filled in price and product name, JWT is not configurated properly
3. When customers buy from two different vendors, shipping costs only 1 but not 2
Please support the above issues, thank you

**Comment by chuabip10** [comment]
I have updated the latest version but still have 3 errors as above, please check and support me soon, thanks

**Comment by thangvo9x** [comment]
1. Try to replace this file at src/Containers/Category/index.js 
[index.txt](https://github.com/inspireui/support/files/3391469/index.txt)
p/s: remember that change from .txt tag -> .js tag 
2. - The error uploading is coming from config on your website. adding this code to .htaccess file 
<IfModule mod_headers.c>
​    Header set Access-Control-Allow-Origin "*"
</IfModule>
3. When customers buy from two different vendors, shipping costs only 1 but not 2 => Noted and We'll update in the next version.
