### ISSUE TITLE
[Mstore Multi Vendor] - Variable products not work

### ISSUE THREAD

**Issue by MuMiMaNz** [inspireui/support#762]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue
I was installed MV by react native cli (not expo) and setup Variable Products by Woocommerce. It doesn't work and not show Variant choice on app, but it work on MStore Pro (I bought both versions)

2. Screenshots
on MV version
<img width="1257" alt="Screen Shot 2562-07-06 at 14 58 43" src="https://user-images.githubusercontent.com/39735033/60753666-5fd8d200-a000-11e9-9f41-f1158578b51e.png">

on Pro version
<img width="1257" alt="Screen Shot 2562-07-06 at 15 13 49" src="https://user-images.githubusercontent.com/39735033/60753685-b6dea700-a000-11e9-9d07-ca2d2a45968b.png">

3. My screenshot of the purchase product or my comment:
my purchase code -

3a08073a-0523-4db3-90ac-79a65aab6e2d 
4d3bcd8d-966f-4d7a-8f26-60ba2dba2274

3. Config files (optional)
I don't do anything special in Config file

**Comment by thangvo9x** [comment]
Hi guy. Could you Share your AppConfig file for checking?
