### ISSUE TITLE
ERROR ITMS-90045: "Invalid Code Signing Entitlements & ERROR ITMS-90786: "Invalid Entitlement

### ISSUE THREAD

**Issue by mopilo** [inspireui/support#763]
1. My issue: I ran into this error while trying to upload to appstore.

ERROR ITMS-90045: "Invalid Code Signing Entitlements. Your application bundle's signature contains code signing entitlements that are not supported on iOS. Specifically, key 'com.apple.developer.user-fonts' in 'Payload/ExpoKitApp.app/ExpoKitApp' is not supported."

ERROR ITMS-90786: "Invalid Entitlement. Apps that contain the 'com.apple.developer.coremedia.hls.low-latency' entitlement must be built with the iOS 13.0 SDK or later."

2. Screenshots

<img width="938" alt="Screenshot 2019-07-06 at 12 40 26 AM" src="https://user-images.githubusercontent.com/7842458/60758307-cdd7c600-a00d-11e9-9974-1e6f285e3874.png">

**Comment by minhcasi** [comment]
Hi, could you show your purchased screenshot and user name from Envato then reopen the ticket ? - thank you for your understanding.

**Comment by mopilo** [comment]
<img width="938" alt="Screenshot 2019-07-08 at 1 31 44 PM" src="https://user-images.githubusercontent.com/7842458/60810330-c8e95280-a184-11e9-8c38-482e78f4de32.png">



Username: Jaymax001!
