### ISSUE TITLE
BeoNews Pro - Build Failed, (java.lang.ClassNotFoundException) 

### ISSUE THREAD

**Issue by Blubagoo** [inspireui/support#764]
---------

1. My issue
The build failed when trying to generate a signed apk. I believe it has something to do with the Android Studio update 3.4. I found an article that I think might help. 

https://stackoverflow.com/questions/55844077/findbugs-idea-classnotfoundexception-com-google-wireless-android-sdk-stats-int

2. Screenshots

https://oneopinion.me/wp-content/uploads/2019/07/AS-Error.png
https://oneopinion.me/wp-content/uploads/2019/07/AS-Error3.png
https://oneopinion.me/wp-content/uploads/2019/07/AS-Error2.png
https://oneopinion.me/wp-content/uploads/2019/07/AS-Error1.png

3. My screenshot of the purchase product or my comment:
item id 19186520
4. Config files (optional)

**Comment by minhcasi** [comment]
Hi, could I have a check if you changed the bundle ID? If yes please follow this guide to change the folder name as well - https://docs.inspireui.com/beonews/delivery/

**Comment by Blubagoo** [comment]
I have indeed changed the bundleID and the package names. Just an FYI your delivery page leaves out two crucial places to change the package name. The build will fail throwing three errors about class symbols if you do not change the package-name on the splashActivity.java and mainApplication.java

**Comment by Blubagoo** [comment]
Is there an update on this?

**Comment by minhcasi** [comment]
Hi, sorry for a lated response as I missed the notification from the email from this ticket, could you zip your customize project to our email support@inspireui.com - we will help to fix this issue - thanks

**Comment by Blubagoo** [comment]
Sure thing I will send that asap.

**Comment by Blubagoo** [comment]
What exactly are you asking me to zip? The whole project folder zips down to 300~ megabytes so it wont send via email?

**Comment by minhcasi** [comment]
Hi, you can upload to https://wetransfer.com/ and send us the link via email - thanks

**Comment by concuacon** [comment]
@Blubagoo  i fixed this issue and send to your mail, pls check mail

**Comment by Blubagoo** [comment]
This is NOT fixed. Still getting the same error.
