### ISSUE TITLE
[list-app] - Listify - Showing an article instead of a listing

### ISSUE THREAD

**Issue by gbhall99** [inspireui/support#765]
Hello,

When I follow the below process on the app, I am having an issue.
We have created the app called I Hear Wedding Bells from the play store: https://play.google.com/store/apps/details?id=za.co.ihearweddingbells.app&gl=ZA

Step 1: On the home page, scroll down to the Articles and view any article.
Step 2: Click the back button
Step 3: Click the search button in the bottom menu
Step 4: Choose any category in the scrolling category carousel
Step 5: Choose any listing from that category

Result: It shows me the article that I read in step 1
Expectation: It should have shown me the content of the listing that I selected

Please can you help to resolve this issue?

> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue

2. Screenshots

3. My screenshot of the purchase product or my comment:

3. Config files (optional)

**Comment by gbhall99** [comment]
https://codecanyon.net/item/listapp-listing-directory-mobile-app-by-react-native/21456447

**Comment by thangvo9x** [comment]
Try to replace this file at App/Container/PostDetail/
[index.txt](https://github.com/inspireui/support/files/3380875/index.txt)
change from .txt tag -> .js tag
Thanks
