### ISSUE TITLE
[ListApp] Listify -  The Map Search is showing unpublished listings

### ISSUE THREAD

**Issue by gbhall99** [inspireui/support#766]
Hello,

I am facing two issues on our ListApp app, published in the play store below:
https://play.google.com/store/apps/details?id=za.co.ihearweddingbells.app&gl=ZA

1) When searching on the map under the search section, I can see the listings come up at first, then an additional set of listings appears that are not yet approved listings.
How do I ensure that these listings do not appear in the maps section?

2) When I search for a suburb, for example: "Fairland, Randburg, South Africa" and select it. The menu dropdown showing the location search results does not disappear and makes the map section unusable. Are you able to assist with this bug?

https://codecanyon.net/item/listapp-listing-directory-mobile-app-by-react-native/21456447

Many thanks

> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue

2. Screenshots

3. My screenshot of the purchase product or my comment:

3. Config files (optional)

**Comment by thangvo9x** [comment]
https://github.com/inspireui/support/issues/765

**Comment by gbhall99** [comment]
Does 765 solve both of my problems?
