### ISSUE TITLE
[MStore-pro] - 'AccountKit/AccountKit.h' file not found

### ISSUE THREAD

**Issue by yosefasad** [inspireui/support#767]
Hello

I have a fresh installation for MSstore pro 3.9.1 ...nothing changed in the code...
-    build for Android working well. 
-    when doing the build for for IOS , I got this error

<img width="1440" alt="Screen Shot 1440-11-05 at 11 48 42 AM" src="https://user-images.githubusercontent.com/23431061/60798166-46a76100-a179-11e9-96c5-4cd47a3eb148.png">

`In file included from RNAccountKitViewController.h:1:
RNAccountKitAdvancedUIManager.h:1:9: fatal error: 'AccountKit/AccountKit.h' file not found
#import <AccountKit/AccountKit.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening mstore.xcworkspace

** BUILD FAILED **

The following commands produced analyzer issues:
	Analyze /Users/yosef/Desktop/mstore-3.9.1/mstore-pro/node_modules/react-native/ReactCommon/jsi/jsi.cpp normal x86_64
	Analyze /Users/yosef/Desktop/mstore-3.9.1/mstore-pro/node_modules/react-native/ReactCommon/yoga/yoga/Yoga.cpp normal x86_64
	Analyze Base/RCTModuleMethod.mm normal x86_64
(3 commands with analyzer issues)

The following build commands failed:
	CompileC /Users/yosef/Desktop/mstore-3.9.1/mstore-pro/ios/build/mstore/Build/Intermediates.noindex/RNAccountKit.build/Debug-iphonesimulator/RNAccountKit.build/Objects-normal/x86_64/RNAccountKitViewController.o RNAccountKitViewController.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
. Run CLI with --verbose flag for more details.
`

I tried to to change the built system to "legacy build system"  , clean and build again ... and did not work....
I tried this [solution](https://github.com/underscopeio/react-native-facebook-account-kit/issues/103#issuecomment-351670218)  and did not work as well 
Also this [solution](https://github.com/inspireui/support/issues/207#issuecomment-457902399) and did not work as well

How to solve this  issue ?

**Comment by minhcasi** [comment]
@yosefasad - could cause by a recent update from FacebookSDK, we have noted for checking and update with latest RN 60.0 for next release - thank you!

**Comment by minhcasi** [comment]
Hi, @yosefasad  - please use the latest 3.9.2 to fix this issue.

The new version to support 60 still hold on due to the messy change from RN that impact to other libraries so we are waiting next stable release from RN - thank you!

**Comment by yosefasad** [comment]
Hello 

I upgrade to 3.9.2  and still the issue exist... 

any suggestion to resolve it  ?

**Comment by concuacon** [comment]
@yosefasad 
Run: rm -rf node_modules/ && yarn cache clean && yarn 
Run: cd ios/ && rm -rf build/ &&  rm -rf Pods/ && rm -rf Podfile.lock && pod install && cd ../
Run: react-native run-ios
Hopes this helps!

**Comment by yosefasad** [comment]
@concuacon @minhcasi 

Thank you for your help ... but the issue still exist...not fixed yet

**Comment by concuacon** [comment]
@yosefasad 
i checked, it works.
Hmm, you try again
Run: rm -rf node_modules/ && yarn cache clean && yarn
Run: cd ios/ && rm -rf build/ && rm -rf Pods/ && rm -rf Podfile.lock && pod install && cd ../
Run: react-native run-ios
 and clear cache Xcode  **Command + shift + k** 
![Simulator Screen Shot - iPhone Xʀ - 2019-07-16 at 17 14 48](https://user-images.githubusercontent.com/11958061/61286586-5bc16700-a7ed-11e9-9928-a7578f657a09.png)
Podfile
<img width="986" alt="Screen Shot 2019-07-16 at 5 15 11 PM" src="https://user-images.githubusercontent.com/11958061/61286598-611eb180-a7ed-11e9-9689-0064cc0fd071.png">
Xcode 
<img width="1397" alt="Screen Shot 2019-07-16 at 5 22 48 PM" src="https://user-images.githubusercontent.com/11958061/61287134-6fb99880-a7ee-11e9-8a19-ccb5e3580af6.png">

**Comment by krunvaghela** [comment]
> @yosefasad
> i checked, it works.
> Hmm, you try again
> Run: rm -rf node_modules/ && yarn cache clean && yarn
> Run: cd ios/ && rm -rf build/ && rm -rf Pods/ && rm -rf Podfile.lock && pod install && cd ../
> Run: react-native run-ios
> and clear cache Xcode **Command + shift + k**
> ![Simulator Screen Shot - iPhone Xʀ - 2019-07-16 at 17 14 48](https://user-images.githubusercontent.com/11958061/61286586-5bc16700-a7ed-11e9-9928-a7578f657a09.png)
> Podfile
> <img alt="Screen Shot 2019-07-16 at 5 15 11 PM" width="986" src="https://user-images.githubusercontent.com/11958061/61286598-611eb180-a7ed-11e9-9689-0064cc0fd071.png">
> Xcode
> <img alt="Screen Shot 2019-07-16 at 5 22 48 PM" width="1397" src="https://user-images.githubusercontent.com/11958061/61287134-6fb99880-a7ee-11e9-8a19-ccb5e3580af6.png">

Thanks Its Worked :)

**Comment by concuacon** [comment]
@krunvaghela 
Glad that it helps you.
