### ISSUE TITLE
CeStore - Can't install in windows

### ISSUE THREAD

**Issue by TonyOchinang** [inspireui/support#769]
I’m new to this so bear with me please:

i have follow your video CeStore - Website installing (ReactJS) at youtube. and
i got an error after in run :
npm i
npm run build
npm star

1. I’m trying to run CeStore(web) locally but i’m getting ‘{error authorization token was found”} when opening ‘localhost:3001’.
2. Products are not displaying after importing sample data(mongodb_bk) 
3. How to login as admin to admin site?

**Comment by minhtruong315** [comment]
Hi @TonyOchinang 
- Go to config/admin.js and config/server.js. and add ```developerMode: true```
- You need to edit "domain" field in settings of mongodb. domain should be http://localhost:3000
- Run this command: ```npm run app:install```
<img width="743" alt="Screen Shot 2019-07-10 at 6 40 01 AM" src="https://user-images.githubusercontent.com/10402500/60930024-f1389480-a2dd-11e9-88d7-fb0f1407f515.png">

**Comment by TonyOchinang** [comment]
I've done all your instructions but i got the error below when running 'npm run app:install' inside the web folder (i'm using windows 10 laptop.

![csstore-error](https://user-images.githubusercontent.com/32132032/60940484-396fab00-a30e-11e9-9620-61103e704507.png)

**Comment by minhtruong315** [comment]
You try to delete node_modules folder, then run:
- npm install
- npm run build

**Comment by TonyOchinang** [comment]
tried the following in order:

1. delete 'node_modules' folder
2. npm install
3. npm run build
4. npm run app:install

but i'm still receiving the same error just like the screenshot above.

**Comment by minhtruong315** [comment]
1. delete 'node_modules' folder
2. npm install
3. npm run build
4. npm start
