### ISSUE TITLE
[ Mstore ] - Facebook login ios app is working fine in simulator, but not working after publishing on app store

### ISSUE THREAD

**Issue by santhoniral** [inspireui/support#770]
issue : Facebook login in ios app is working fine in simulator, but not working after publishing on app store

Screenshots-: https://user-images.githubusercontent.com/32481586/59898290-b5f92300-940d-11e9-8c53-6058910d6a97.jpg

**Comment by santhoniral** [comment]
i opened this issue 4 days ago but no response

**Comment by santhoniral** [comment]
No response for last 6 days...what happen???

**Comment by concuacon** [comment]
sorry for the delay, i'm checking this issue, i'll respond to you as soon as possible.

**Comment by santhoniral** [comment]
Okay please response quickly...thanks

**Comment by concuacon** [comment]
@santhoniral pls updating latest version 3.9.2 version solves this issue - thank you.
