### ISSUE TITLE
please i need your team install it to me i don't have any idea in code [my-product] - 

### ISSUE THREAD

**Issue by moustafaelwan** [inspireui/support#771]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue can't install

2. Screenshots no photo beacuse i don't have any idea in installing

3. My screenshot of the purchase product or my comment:

3. Config files (optional)

**Comment by minhcasi** [comment]
Hi, could you try with the Cebuilder could be easier to install - http://inspireui.com - thank you!

**Comment by moustafaelwan** [comment]
i try more but not helpful

please need some one install it to me

i can pay for it no problem

‫في الخميس، 11 يوليو 2019 في 3:44 ص تمت كتابة ما يلي بواسطة ‪Minh Pham‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by minhcasi** [comment]
Hi, could you help to share the screenshot issues so that the team could help for troubleshooting, we have not supported for installing services at the moment due to the team full of capacity, thank you for your understanding

**Comment by moustafaelwan** [comment]
Please sir when i click on build android this MSG in attached come to me
...!!!

‫في الاثنين، 15 يوليو 2019 في 3:08 م تمت كتابة ما يلي بواسطة ‪Minh Pham‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by minhcasi** [comment]
Hi, i could not see the message, pls upload it again - thanks

**Comment by moustafaelwan** [comment]
Attached.

‫في الخميس، 18 يوليو 2019 في 6:28 م تمت كتابة ما يلي بواسطة ‪Minh Pham‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by moustafaelwan** [comment]
.....

‫في الخميس، 18 يوليو 2019 في 6:29 م تمت كتابة ما يلي بواسطة ‪Moustafa
Elwan‬‏ <‪moustafaelwan989@gmail.com‬‏>:‬

**Comment by moustafaelwan** [comment]
why you not answer my emails

‫في الجمعة، 19 يوليو 2019 في 9:51 م تمت كتابة ما يلي بواسطة ‪Moustafa
Elwan‬‏ <‪moustafaelwan989@gmail.com‬‏>:‬

**Comment by minhcasi** [comment]
hi, we could not see the attache issue so far - https://tppr.me/k8dnB

You can try to use some cloud tool

**Comment by moustafaelwan** [comment]
ok i attached it there


‫في الاثنين، 22 يوليو 2019 في 1:50 م تمت كتابة ما يلي بواسطة ‪Minh Pham‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by minhcasi** [comment]
can not see btw, not sure if you are joking?
