### ISSUE TITLE
[mstore mv] - variations and checkout

### ISSUE THREAD

**Issue by carlosfallas** [inspireui/support#772]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue

- 1-

Hide attributes? We only use a color attribute as a variation **(img 01 , img 02)**
![img 01](https://user-images.githubusercontent.com/52757313/60992699-45596e00-a30a-11e9-8d40-ed109bcea55a.jpg)
![img 02](https://user-images.githubusercontent.com/52757313/60992698-45596e00-a30a-11e9-9086-7758f1152d84.jpg)

- 2- 

Variation attributes are not showing **(img 01,)**
![img 01](https://user-images.githubusercontent.com/52757313/60992699-45596e00-a30a-11e9-8d40-ed109bcea55a.jpg)
Woocoommerce config **(img 03,)**
![img 03](https://user-images.githubusercontent.com/52757313/60992697-45596e00-a30a-11e9-8c3e-5a23958e83a4.jpg)
 app config **( img 04)**
![img 04](https://user-images.githubusercontent.com/52757313/60992693-44284100-a30a-11e9-958e-c6b574a97ea1.jpg)

- 3-

404 error page when i try to process the payment, **(img 05)**
![img 05](https://user-images.githubusercontent.com/52757313/60992692-44284100-a30a-11e9-9eeb-985d19cb91ae.jpg)

- 4 

I try to following the solutions in this guide https://docs.inspireui.com/mstore/questions/
First solution:  I can´t save the page **(img 06)**
![img 06](https://user-images.githubusercontent.com/52757313/60992691-438faa80-a30a-11e9-9a26-3fd86ce0b29f.jpg)
Second solution: After save the page “mstore-checkout” correctly the app charge the woocommerce billing details in web-view and then page not found **(img 07)**
![img 07](https://user-images.githubusercontent.com/52757313/60992700-45596e00-a30a-11e9-949b-33cad68ca59e.jpg)
 

2. Screenshots

3. My screenshot of the purchase product or my comment:

![image](https://user-images.githubusercontent.com/52757313/60994312-83a45c80-a30d-11e9-94bf-9d0ec308b76b.png)

**Comment by thangvo9x** [comment]
Hi bro. How about your problem? Could you share AppConfig file for checking?
The problem cannot save a post on your website. could from your website version.
