### ISSUE TITLE
[ListPro] Installation - Step 2 - Couldn't find the binary git

### ISSUE THREAD

**Issue by uroosraza** [inspireui/support#774]
I have installed all the related plugins and when I press the start it gives me this error. I have gone to the link provided but it does not have any help related to this error.

![error](https://user-images.githubusercontent.com/52735336/61017618-3987ad80-a3d7-11e9-9c3e-833eb13e95a4.JPG)

**Comment by thangvo9x** [comment]
Hi bro. Somes tips for you : 
1. Try to update to the latest version of CeBuilder 
2. Update yarn to the latest, too.  Refer this link if still. 
https://github.com/yarnpkg/yarn/issues/2083

**Comment by uroosraza** [comment]
I have the latest version of CE Builder 0.35.0
also latest version of Yarn as per the screen shot 1.16

**Comment by thangvo9x** [comment]
This error maybe comes from install yarn not correctly. Try to check more on it.
https://yarnpkg.com/en/
