### ISSUE TITLE
[ListApp] IOS not working with google map navigate - Listapp

### ISSUE THREAD

**Issue by aymanshawky0001** [inspireui/support#775]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. Hello please direction on IOS not working with google map navigate

![Capture22](https://user-images.githubusercontent.com/49063159/61018266-15ec4500-a38e-11e9-970b-4a4b0f7aa956.PNG)

**Comment by aymanshawky0001** [comment]
hello any reply please

**Comment by thangvo9x** [comment]
Can you share AppConfig file for checking? What is the problem with your app? Please tell more detail. Thanks

**Comment by aymanshawky0001** [comment]
hello 
may you check this video screen shot please this is from your app version on Apple store
https://1drv.ms/v/s!Ai4L-RnZNqxAnzE48gb5Uj3virnr

sincerely

**Comment by thangvo9x** [comment]
Hi. Could you give me your purchase code? The problem is coming from that listing isn't location such as latitude and longitude. Thanks

**Comment by aymanshawky0001** [comment]
Hi
No I tried on all listing the navigate not working 
Purchased Code: [bdbfc344-e591-426d-8772-271220acdc47]

Thanks and best regards

**Comment by thangvo9x** [comment]
Can you share AppConfig file for checking?

**Comment by aymanshawky0001** [comment]
Hello
My friend this problem also in your Listapp application in your Apple store not on my app only please check your config app
Thanks

**Comment by thangvo9x** [comment]
Hi. ListApp is working on the old version. We'll have an update ASAP.

**Comment by aymanshawky0001** [comment]
still problem not solved

**Comment by minhcasi** [comment]
@aymanshawky0001 - reopen - could you clarify more about the issue? Does it have the same with current issue?

**Comment by aymanshawky0001** [comment]
Dear
Yes Everything in same previous issue
sincerely

**Comment by thangvo9x** [comment]
Please view here 
https://apps.apple.com/us/app/listapp-listing-app/id1474038142?ls=1

**Comment by aymanshawky0001** [comment]
Hello
Sorry still get direction and navigate not working on google map 
Thanks

**Comment by aymanshawky0001** [comment]
https://1drv.ms/v/s!Ai4L-RnZNqxAoVhVPUsob_kiFNO4
Please check this video

**Comment by thangvo9x** [comment]
Try to replace this file at Components/Detail/ListingData/
[index.txt](https://github.com/inspireui/support/files/3449697/index.txt)
Thanks

**Comment by aymanshawky0001** [comment]
Thanks is it working now
