### ISSUE TITLE
How to remove Appintro 

### ISSUE THREAD

**Issue by dickyjiang** [inspireui/support#776]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue

How to remove Onboarding ( Appintro) , right now if I removed (!this.pros.introStatus) return <Appintro />;

 I have to logout 2 times, and menu bar still appear bellow login screen

I'm using version 👍  3.7.1

2. Screenshots
(https://user-images.githubusercontent.com/11538459/61021525-1e637080-a3cc-11e9-9298-a1a05505cfa6.jpeg)

3. My screenshot of the purchase product or my comment:
![Screen Shot 2019-07-11 at 11 10 31](https://user-images.githubusercontent.com/11538459/61021646-89ad4280-a3cc-11e9-8846-3b02759632d3.png)

3. Config files (optional)

**Comment by minhcasi** [comment]
Hi, please help to sue the latest 3.9.2 for more stable. 

Remove the app intro by removing this line - https://tppr.me/45bBg

Thank you!

**Comment by dickyjiang** [comment]
Thank you,

will try it tonight
