### ISSUE TITLE
CEStore - admin site not working 

### ISSUE THREAD

**Issue by TonyOchinang** [inspireui/support#777]
The CEStore admin site is not displaying any sample date even after adding the test data (mongodb_bk) and the 'Add New Product' and 'Add New Category' button is not working.

![cestore-admin](https://user-images.githubusercontent.com/32132032/61028595-9db46c80-a3eb-11e9-8e44-adaa171f18d2.png)

**Comment by minhtruong315** [comment]
Can you open Developer Tools in chrome and refresh? Then send me screenshot
<img width="1409" alt="Screen Shot 2019-07-11 at 2 39 32 PM" src="https://user-images.githubusercontent.com/10402500/61031517-e0754500-a3e9-11e9-8916-39f0a8c1321d.png">
