### ISSUE TITLE
[ListApp] Categories doesn't work

### ISSUE THREAD

**Issue by git-palace** [inspireui/support#778]
When I visit categories, it shows me error.
![2019-07-11_09h53_02](https://user-images.githubusercontent.com/25261362/61070382-6df16e80-a3c3-11e9-9823-58e061f5a83e.png)

**Comment by git-palace** [comment]
same with this one.
https://github.com/inspireui/support/issues/752

**Comment by thangvo9x** [comment]
Hi bro. Try to replace this below file at App/Container/Categories/
P/S: remember that change from .txt -> .js 
[index.txt](https://github.com/inspireui/support/files/3384681/index.txt)
Thanks . let me know if it works.
