### ISSUE TITLE
[Fluxstore] registration issue

### ISSUE THREAD

**Issue by richardtrujillo** [inspireui/support#779]
Hello, I followed the steps to make everything work correctly and I found 2 errors. 1. when registering with names, email and password, I get this error … Exception: You must include username var in your request. 2. Trying to find if it was a configuration error, create a user from the administrator of wordpress and when logging in from the application it throws me this other error … Exception: Can not get user info.

**Comment by minhcasi** [comment]
Hi, this bug fix on the latest version, please help download from - https://codecanyon.net/downloads
