### ISSUE TITLE
dear how to add products woman collection,feature collection ; man collection work perfectly

### ISSUE THREAD

**Issue by tharicode** [inspireui/support#78]
**Required Info (please complete the following information):**
 - Product: [e.g. MStore, ListApp]
 - Your Purchased Code: [get from https://codecanyon.net/downloads]
(we may not reply if you are not our customer)

**Describe the bug**

**Screenshots**

**Additional context**
Add any other detail logs about the problem here.
If possible please share your config.js that use for the app setting

**Comment by minhcasi** [comment]
Can you provide more detail info:
- purchase code
- detail issue or screenshot

**Comment by tharicode** [comment]
purchase code : 8c003706-a28e-4be4-bf3f-c1dc86bfb7da
 issue : how to add product on feature products & bag collection .. ; man collection is work perfectly
![capture](https://user-images.githubusercontent.com/45279029/49562592-3492e500-f942-11e8-85b8-a823187fea75.PNG)
