### ISSUE TITLE
[Beonews] Release build not getting created in iOS

### ISSUE THREAD

**Issue by SA24** [inspireui/support#780]
Hello,

My client has already purchased latest version of code, i've been able to run it fine on device but when i'm trying to Archive the build then it says Distribute Content instead of Distribute App. I'm not able to release and show IPA to my client. PFA screenshots also.

![IMG-20190710-WA0016](https://user-images.githubusercontent.com/3120008/61108180-3fe15c80-a49f-11e9-80ab-ac72183dc038.jpg)
![IMG-20190710-WA0015](https://user-images.githubusercontent.com/3120008/61108188-48399780-a49f-11e9-9cfd-7aa9eca461ae.jpg)
![IMG-20190710-WA0014](https://user-images.githubusercontent.com/3120008/61108213-5a1b3a80-a49f-11e9-8c84-551e8aff84d6.jpg)

**Comment by minhcasi** [comment]
could i check if all the archive from edit schema is check ? https://tppr.me/GEzvD

**Comment by SA24** [comment]
Yes i've checked that and its good.

**Comment by SA24** [comment]
See below :

https://drive.google.com/file/d/1MCI262hOpDEoal8-DhDU5q02Z566aAfV/view?usp=drivesdk

**Comment by SA24** [comment]
Is there anything else you suggest that i need to check, all other builds archive fine for me apart from this very project?

**Comment by concuacon** [comment]
@SA24 S
Hello, i checked it...All you just need to do is change target version and re-archive.

<img width="1011" alt="Screen Shot 2019-07-16 at 7 25 51 PM" src="https://user-images.githubusercontent.com/11958061/61294232-8d432e00-a7ff-11e9-9ad8-c008c749c837.png">

**Comment by concuacon** [comment]
@SA24 
Hello, i checked it...All you just need to do is change target version and re-archive.
<img width="996" alt="Screen Shot 2019-07-16 at 7 31 47 PM" src="https://user-images.githubusercontent.com/11958061/61294674-8c5ecc00-a800-11e9-8c92-16d5fbbab5d4.png">

**Comment by SA24** [comment]
Ok i'll check that out and come back to you.

**Comment by concuacon** [comment]
@SA24 
Sorry, I checked again and found the error of library react-native-fast-image
As a workaround, downgrading react-native-fast-image to 5.4.2 completes successfully.
<img width="303" alt="Screen Shot 2019-07-16 at 10 49 22 PM" src="https://user-images.githubusercontent.com/11958061/61309505-8545b700-a81c-11e9-82a6-93ef514048d4.png">

**Comment by SA24** [comment]
Sure, i'll try that out.

**Comment by concuacon** [comment]
yes, i'm sure =))

**Comment by SA24** [comment]
I've tried that but result was still the same, earlier it was 6 then i changed to 5.4.2 but problem persists.

**Comment by concuacon** [comment]
Do you clean cache Xcode? 
You try clean cache Xcode **Command +Shift+K** , close all terminal active and remove node_modules/ && re-install (you can  run: rm -rf node_modules && yarn cache clean && yarn)
**result**
<img width="999" alt="Screen Shot 2019-07-17 at 10 02 03 AM" src="https://user-images.githubusercontent.com/11958061/61344030-01bab300-a87a-11e9-8c4a-475b011b65bb.png">

**Comment by SA24** [comment]
All things i've tried all night long as RN and iOS basics. Not sure where its going wrong. Can you let me know all your config. vesrions like node, npm, RN, iOS & xCode?

**Comment by concuacon** [comment]
My config 
node: 10.15.3
npm: 6.9.0
yarn: 1.13.0
RN: 0.59.8
Xcode: 10.2

**Comment by SA24** [comment]
Ok, Thanks. I'll try to match these and see if that works out.

**Comment by SA24** [comment]
Didn't work, anything else you suggest i should try?

**Comment by concuacon** [comment]
hmm, you can compress your source send to my email?
nguyentuan1707@gmail.com

**Comment by SA24** [comment]
Shared.

**Comment by ramyragab1** [comment]
i try all this and Didn't work also

**Comment by minhcasi** [comment]
Hi, please update latest 3.0.3 for the fixing - thanks
