### ISSUE TITLE
MStore Multi Vendor - Complete React Native template for WooCommerce - 

### ISSUE THREAD

**Issue by WEPPIES** [inspireui/support#781]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue
I followd this page: https://docs.inspireui.com/mstore-mv/quick-setup
But i don't get the installation fixed. 

I also watched this video, but no luck: https://youtu.be/04KGBT5DKxQ

2. Screenshots
<img width="1038" alt="Screenshot 2019-07-12 at 14 48 28" src="https://user-images.githubusercontent.com/52826047/61129414-a15ff600-a4b4-11e9-8bc9-d091402b274d.png">

3. My screenshot of the purchase product or my comment:
![Screenshot 2019-07-12 at 14 52 41](https://user-images.githubusercontent.com/52826047/61129448-b89ee380-a4b4-11e9-9b87-27f5af637aa4.png)

3. Config files (optional)

**Comment by thangvo9x** [comment]
Tell me what is your problem with it? Try to get the latest version of CeBuilder

**Comment by WEPPIES** [comment]
I told my problem in the this post. Didn’t you read it?

The version number is also visable. So you can see if i’m using a old version. I think not because i downloaded the same day. I added details in blue.

I think your response is disrespectful while I submitted my issue in accordance with your requirements.

**Comment by minhcasi** [comment]
@minhtruong315 - could you help to check the Cebuilder issue - thank you!

**Comment by minhtruong315** [comment]
Hi @WEPPIES Can you share me teamviewer, I will help you check it

**Comment by WEPPIES** [comment]
Hi,

When do you want to do this? I'm in different timezone then you i guess.

I'm at MET, GMT +1.

Like to hear.


Zijn er nog vragen? Laat het weten!



Met vriendelijke groet,







*T* 085 - 4010 249  |  *W* www.weppies.nl



WEPPIES.. Internet en Marketing - Online Succes <https://www.weppies.nl/>
Check onze BIER website: www.weppies.nl
WEPPIES.. uw internet en marketing partner voor groot online succes!
Van website tot social media beheer. Bezoek de website of bel: 085 - 4010
249.



Op do 18 jul. 2019 om 03:33 schreef minhtruong315 <notifications@github.com

**Comment by WEPPIES** [comment]
Hi, 

Why don't you respond on my message?
I thinks the support is real a disappointment.

The tool isn't working and you won't able the helping me..

**Comment by minhcasi** [comment]
@WEPPIES  - sorry for the issue as we missed your comment 

1. Could you quickly check if you could install the library manually "yarn, homebrew, expo" by following this guide - https://facebook.github.io/react-native/docs/getting-started.html, there is a known permission issue that prevents the Cebuilder process auto-install on some machine

2. Let try to check and if still not work we could process the refund for your - thanks

**Comment by WEPPIES** [comment]
Yes refund my purchase. I won't work.
