### ISSUE TITLE
[M Store MV] - Vendors Not Showing + Many issues

### ISSUE THREAD

**Issue by v3creatives** [inspireui/support#782]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

Hi,

My issues are...

1. I'm using WC Vendors Pro, and I am unable to see a list of Vendors when, I click Categories Tab.

2. No reviews are showing when you click review on a product.

3. When you click on the Vendor Tab on a product the App crashes

4. When I click on Advanced view on the homepage the app crashes

<img width="655" alt="Screenshot 2019-07-12 at 13 46 27" src="https://user-images.githubusercontent.com/52754640/61129811-20e9c700-a4ad-11e9-8a03-48c0bda128e1.png">
<img width="420" alt="Screenshot 2019-07-12 at 13 39 13" src="https://user-images.githubusercontent.com/52754640/61129812-21825d80-a4ad-11e9-885b-a30f516b5998.png">
<img width="425" alt="Screenshot 2019-07-12 at 13 35 23" src="https://user-images.githubusercontent.com/52754640/61129813-21825d80-a4ad-11e9-854f-b496d301c77d.png">
<img width="421" alt="Screenshot 2019-07-12 at 13 34 31" src="https://user-images.githubusercontent.com/52754640/61129814-21825d80-a4ad-11e9-8fe2-c6f20ee06576.png">
[AppConfig copy.txt](https://github.com/inspireui/support/files/3386492/AppConfig.copy.txt)

**Comment by thangvo9x** [comment]
Please provide full AppConfig help me with consumerKey and consumerSecret... Thanks

**Comment by v3creatives** [comment]
Hi,

I've emailed the AppConfig to support@inspireui.com

**Comment by thangvo9x** [comment]
1. I'm using WC Vendors Pro, and I am unable to see a list of Vendors when, I click Categories Tab.

2. No reviews are showing when you click review on a product.

3. When you click on the Vendor Tab on a product the App crashes

4. When I click on Advanced view on the homepage the app crashes
=> Solutions 
1.2.3 => Could you share an account for checking on your backend?
4. Try to replace this file at src/Components/PostLayout/
p/s: Remember that change from .txt -> .js  Thanks 
[index.txt](https://github.com/inspireui/support/files/3400535/index.txt)
Thanks

**Comment by v3creatives** [comment]
1.2.3. - Details have been emailed to you

4. Thanks, Advanced View works now.

**Comment by thangvo9x** [comment]
Hi bro. Which email have you sent? I haven't got it.

**Comment by v3creatives** [comment]
Sent to support@inspireui.com

**Comment by thangvo9x** [comment]
Try to replace this file at Components/ProductItem
change from .txt -> .js 
[index.txt](https://github.com/inspireui/support/files/3421476/index.txt)
and fix vendors tab 
replace this file at Services/CustomAPI
[CustomAPI.txt](https://github.com/inspireui/support/files/3421484/CustomAPI.txt)
Thanks

**Comment by v3creatives** [comment]
Hi, 

I updated both files and still have the following issues.

1. I am unable to see a list of Vendors when, I click Categories.
![No List of Vendor Screenshot](https://user-images.githubusercontent.com/52754640/61710757-40ed7600-ad4a-11e9-87eb-0483a4ebc69d.jpg)

2. No reviews are showing when you click review on a product.
![Product Review Tab Screenshot](https://user-images.githubusercontent.com/52754640/61710760-41860c80-ad4a-11e9-8941-6e53be1a6f40.jpg)

3. When you click on the Vendor Tab on a product the App crashes
![Product Vendor Tab Screenshot](https://user-images.githubusercontent.com/52754640/61710761-41860c80-ad4a-11e9-8c2a-bbecd7d56f56.jpg)

And Now since updating the App to version 1.3.1

4. When you search for an item the App crashes,
![Search Crashes App Screenshot](https://user-images.githubusercontent.com/52754640/61710758-41860c80-ad4a-11e9-8898-20aee4430746.jpg)

5. App is display product which have their woocommerce status set to "draft" and have not been published.
![Draft Product on App Screenshot](https://user-images.githubusercontent.com/52754640/61710886-9b86d200-ad4a-11e9-8d0c-0a98dba73d0d.jpg)

**Comment by thangvo9x** [comment]
Hi. I still can't see full consumerKey . Please attach again thang@inspireui.com 
Thanks

**Comment by v3creatives** [comment]
Hi,

It's been resent to thang@inspireui.com

**Comment by thangvo9x** [comment]
I install some plugin which were missed on your website.
![Simulator Screen Shot - iPhone 7 Plus - 2019-07-25 at 10 15 10](https://user-images.githubusercontent.com/23457178/61843219-1c69d900-aec5-11e9-933a-f27c0b7191f4.png)

**Comment by v3creatives** [comment]
Hi, 

The App still doesn't work since you added the new plugins.

I can see you added the following, were there anymore?

• WCFM - WooCommerce Frontend Manager
• WCFM - WooCommerce Multivendor Marketplace
• WCFM - WooCommerce Multivendor Marketplace - REST API

The above plugins you added have now been deleted. We are using WC Vendors Pro as mentioned above not WCFM

**Comment by thangvo9x** [comment]
Hi. These plugins will be used for supporting to list REST API. It's because The setting default hasn't been it.
https://wordpress.org/support/topic/wcvendors-rest-api/
Please active again these plugin for working.

**Comment by v3creatives** [comment]
Hi, 

I don’t understand?

We are using WC Vendors which you say your app works with. Now you say add WCFM plugins but we are not using WCFM and WCFM is not compatible with WC Vendors as you can only have one market place plugin running at a time. 

So do I need all 3 of the plugins to be activated or just the WCFM Rest API. 

Does this app not work properly with WC Vendors?

**Comment by v3creatives** [comment]
Hi Thang,

Any update, Have also sent you updated login and config details.

**Comment by thangvo9x** [comment]
Hi. Please enable those plugins for display list vendors on your app. 
The MMV is working as.
Those plugins have only provided to REST API for the app.

**Comment by v3creatives** [comment]
Hi,

I enabled the plugin and still have the following problems 

1. I am unable to see a list of Vendors when, I click Categories.
2. No reviews are showing when you click review on a product.
3. When you click on the Vendor Tab on a product the App crashes
4. When you search for an item the App crashes

5. 'WCFM' & 'WC vendors' do not work together as mentioned before and shown in the image below. Do I assume that the app does not work properly with 'WC Vendors' even though the product descriptions says it does? I should not have to activate another Marketplace plugin to make the app work.
<img width="1257" alt="Screenshot 2019-08-06 at 12 46 38" src="https://user-images.githubusercontent.com/52754640/62538484-d4df3780-b84a-11e9-9d02-6ccd2bf83941.png">

**Comment by thangvo9x** [comment]
Hi. 
1. I enabled list vendor on your website.
2. The review will not be displayed if it hasn't yet 
3. fix crash when clicking on VendorTab on a product.
4. Fixed.
5. Disabled the plugin WCFM.
+ REPLACE this file at components/VendorInfo/
[index.txt](https://github.com/inspireui/support/files/3479785/index.txt)
+ REPLACE this file at components/ExpandComponent to fix crash tab search
[index.txt](https://github.com/inspireui/support/files/3479789/index.txt)
Remember that change from .txt -> .js
Thanks

**Comment by v3creatives** [comment]
Hi Thang,

Thanks for the files, they helped stopped the app from crashing when you searched on tried to view the Vendors tab.

1. Still can not see Vendors when you select Vendors from the categories screen.

2. When you select Vendor on products page, no Vendor details are shown (store name or address), when hit details the app crashes.

3. No reviews are shown on app, can this not be fixed? Reviews don't show on your demo app  in the App store either.

4. If reviews can not be fixed can the tab be removed until it does work
