### ISSUE TITLE
[mstore-expo] syntax 'decorators-legacy' isn't currently enabled (22:1):

### ISSUE THREAD

**Issue by truongdaily** [inspireui/support#784]
syntax 'decorators-legacy' isn't currently enabled (22:1):
SyntaxError: xxxxxxxx/mstore-expo/src/Router.js: Support for the experimental syntax 'decorators-legacy' isn't currently enabled (22:1):

  20 | import { toast, closeDrawer } from "./Omni";
  21 | 
> 22 | @withTheme
     | ^
  23 | class Router extends React.PureComponent {
  24 |   state = {
  25 |     loading: true

**Comment by minhcasi** [comment]
Hi, please use the latest 3.9.2 to fix this issue, please make sure to run the same project from the download package, without coping to another folder that causes missing hidden file

- thank you!
