### ISSUE TITLE
[Mstore Pro] 3.9.1  Bannerimage is not showing in Android

### ISSUE THREAD

**Issue by yosefasad** [inspireui/support#786]
BannerImage is not showing in Android in a fresh installation of Mstore Pro 3.9.1  

I did the following 
yarn setup 
react-native link
react-native run-android 

Please check the screenshot

<img width="397" alt="Screen Shot 1440-11-10 at 10 59 24 PM" src="https://user-images.githubusercontent.com/23431061/61176050-d0648d80-a5c2-11e9-94c7-ad6922383cf4.png">

How to solve this issue`/

**Comment by minhcasi** [comment]
Hi, please update 3.9.2 for this fixing, the image link we put from the appconfig.json is missing from our S3 server so that i could not load the image - thank you!
