### ISSUE TITLE
[myListApp] - Can't Log in

### ISSUE THREAD

**Issue by kwsystems** [inspireui/support#788]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

Hi,
1. My issue
I am trying to log in but it doesnt work. If I create a New User it works and saved in Firebase but if I log out doesn't work.

2. Screenshots
https://www.dropbox.com/s/iew742d691iivgx/Screen%20Shot%202019-07-14%20at%209.35.42%20PM.png?dl=0

**Comment by thangvo9x** [comment]
Ah. This problem. You can find here
Maybe from config about your JWT plugin on your website.
https://docs.inspireui.com/listapp/getting-started/#jwt-authentication
