### ISSUE TITLE
[Mstore] - i can't order confirm how fix it 

### ISSUE THREAD

**Issue by tharicode** [inspireui/support#79]
**Required Info (please complete the following information):**
 - Product: mstore pro
 - Your Purchased Code: [get from https://codecanyon.net/downloads]
(we may not reply if you are not our customer)

**Describe the bug**

**Screenshots**

**Additional context**
Add any other detail logs about the problem here.
If possible please share your config.js that use for the app setting

**Comment by minhcasi** [comment]
Can you provide more detail info:
- purchase code
- detail issue or screenshot

**Comment by tharicode** [comment]
purchase code :  8c003706-a28e-4be4-bf3f-c1dc86bfb7da 

detail issue : i can't continue 'order confirm'  

![capture](https://user-images.githubusercontent.com/45279029/49558861-93e8f900-f932-11e8-8374-93f9845d1d5d.PNG)

 second issue : how to add product on feature products & bag collection .. ; man collection is work perfectly 

![capture](https://user-images.githubusercontent.com/45279029/49558980-0b1e8d00-f933-11e8-964d-d547dea2d673.PNG)

**Comment by tharicode** [comment]
ok dear 

[Config.zip](https://github.com/inspireui/support/files/2655675/Config.zip)

**Comment by luyx2412** [comment]
Hi i checked your Config.js file,

- First issue, please check your setting follow the document https://docs.mstore.io/basic-app-setting.
- Second issue Please check again your Category id which based on your website. Follow the document https://docs.mstore.io/advance-customize-app/customize-the-app-branding#example-showing-the-content-as-3-column-view

Thanks

**Comment by tharicode** [comment]
dear basic app settings document is right my project  settings but confirm
order not work yet
