### ISSUE TITLE
[EvaStore] - Multiple Variants

### ISSUE THREAD

**Issue by ogriffithjones** [inspireui/support#790]
My products aren't showing their variants within the application?

![image](https://user-images.githubusercontent.com/30992424/61261595-6c1a1780-a7d6-11e9-8046-c2d2185aad97.png)
On our site they show up as shown in the image above.

However when pulling them into the application it only shows this:
![image](https://user-images.githubusercontent.com/30992424/61261652-9370e480-a7d6-11e9-8678-3fbfe51e56c4.png)

**Comment by minhcasi** [comment]
Hi, could you take the screenshot of your purchased code + and share us your config file so that we could help to debug for this issue - thank you!

**Comment by ogriffithjones** [comment]
Not sure what you mean by purchased code but here is the Eva Store file that I purchased from you:
<img width="509" alt="image" src="https://user-images.githubusercontent.com/30992424/61358446-6c95d980-a8ce-11e9-89c5-45a35f40ef30.png">


[Config.js.zip](https://github.com/inspireui/support/files/3400798/Config.js.zip)
If you require the api key I am happy to send this though via an email or WeChat.

**Comment by minhcasi** [comment]
Hi, please send the config via email - support@inspireui.com - thank you!

**Comment by ogriffithjones** [comment]
I have sent that though

**Comment by minhtruong315** [comment]
Fixed.
