### ISSUE TITLE
[ListApp] - Facebook can't able to log in ios devices

### ISSUE THREAD

**Issue by Pavithran10** [inspireui/support#791]
1. My issue
      We faced one bugs while running in your app when reviewed on running on ios devices like (ipad) we can't able to login into facebook. its shows the error **implementation of fb login issue**.

2. Screenshots
![fb_issue](https://user-images.githubusercontent.com/46148046/61371656-e6b86500-a8b2-11e9-9a16-c979662f8a35.png)

**Comment by thangvo9x** [comment]
Huh. I saw. The problem is coming from setting on your Facebook App. Please check it before. Thanks

**Comment by Pavithran10** [comment]
thanks, i'll check and update further details.

**Comment by Pavithran10** [comment]
hi, I've a doubt how to update facebook sdk 5.0.1 in ios using react native. thanks

**Comment by thangvo9x** [comment]
You could update it in your Facebook App

**Comment by Pavithran10** [comment]
ok, we will check.
