### ISSUE TITLE
[mstore] - 

### ISSUE THREAD

**Issue by nowshid** [inspireui/support#792]
1. My issue: Not working the login system .its showing unverifieable nonce value use the get  noonce_core api method when i go to regestratin.and can not log in with my websites account it shows invalid user name/ or password.
. Its not connecting with my woocommerce system.but product and other things working properly .Prblem with the login system .
Next problem is to set uop the menu.in your app the menu support and faq terms condition are set up as mstore but i need mine .Cannot find how to do in your documentation 
 Please help soon its very disappointing.

**Comment by minhcasi** [comment]
Hi, could you share your config file here so we could help for debugging (file common/appconfig.json and common/config.js) - thanks

**Comment by nowshid** [comment]
{
  "WooCommerce": {
    "url": "https://uddoyon.com",
    "consumerKey": "ck_d0d091e58e8b3ee27318d830acc54123e8bc6b04",
    "consumerSecret": "cs_c4e486361f4229fdd48ced643c09f8ba1ae0daa7"
  },
  "HorizonLayout": [
    {
      "layout": "circleCategory"
    },
    {
      "layout": "bannerHigh",
      "categoryOrTag": 71,
      "category": 71
    },
    {
      "layout": "bannerImage",
      "categoryOrTag": 71,
      "height": 118,
      "imageBanner": "http://s3-ap-southeast-1.amazonaws.com/mstore-bucket.io/wp-content/uploads/2019/02/25142145/woman-large.png",
      "category": 71
    },
    {
      "layout": "bannerImage",
      "categoryOrTag": 103,
      "height": 118,
      "imageBanner": "http://s3-ap-southeast-1.amazonaws.com/mstore-bucket.io/wp-content/uploads/2019/02/25142102/MAN-large.png",
      "category": 103
    },
    {
      "name": "featureProducts",
      "image": "",
      "layout": "threeColumn",
      "categoryOrTag": 71,
      "category": 71
    },
    {
      "name": "bagsCollections",
      "image": "",
      "layout": "twoColumn",
      "categoryOrTag": 71,
      "category": 71
    },
    {
      "name": "blog",
      "layout": "twoColumn",
      "categoryOrTag": 76,
      "category": 76
    },
    {
      "layout": "threeColumn",
      "categoryOrTag": 71,
      "category": 71
    }
  ],
  "MainColor": "#f97c00"
}




Code of appconfig.json

**Comment by minhtruong315** [comment]
@nowshid Did you install mstore plugin in website?
