### ISSUE TITLE
[my-product] - Mstore MultiVendor

### ISSUE THREAD

**Issue by Peakabooo** [inspireui/support#793]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue
    1.) Vendor can not add a product - (Cannot connect to server) -screenshots
    2.) Error when going to settings. -screenshot
    3.) Contact us and about us is a blank page
    4.) When selecting a category from the category/vendors tab it shows and error -screenshots

2. Screenshots
![Screenshot_20190717-084228_Expo](https://user-images.githubusercontent.com/33591499/61390543-d6cb6180-a86f-11e9-8f79-ce02b2ee0b13.jpg)
![Screenshot_20190717-085037_Expo](https://user-images.githubusercontent.com/33591499/61390886-74bf2c00-a870-11e9-957a-3b04aedd4923.jpg)
![Screenshot_20190717-085052_Expo](https://user-images.githubusercontent.com/33591499/61390893-77218600-a870-11e9-9057-3db84ebafe6a.jpg)
![Screenshot_20190717-085102_Expo](https://user-images.githubusercontent.com/33591499/61390896-7983e000-a870-11e9-9467-2e7e3b52cdc4.jpg)
![Screenshot_20190717-090025_Expo](https://user-images.githubusercontent.com/33591499/61391640-fcf20100-a871-11e9-80b0-e7a1cc1a2b08.jpg)
![Screenshot_20190717-090038_Expo](https://user-images.githubusercontent.com/33591499/61391641-fe232e00-a871-11e9-83bb-6ccfd7105f8e.jpg)
![Screenshot_20190717-090053_Expo](https://user-images.githubusercontent.com/33591499/61391644-ff545b00-a871-11e9-9e4d-3426656e1e11.jpg)
![Screenshot_20190717-090254_Expo](https://user-images.githubusercontent.com/33591499/61391646-011e1e80-a872-11e9-8f78-40c2992ce4d4.jpg)

3. My screenshot of the purchase product or my comment:
<img width="960" alt="proof of purchase email" src="https://user-images.githubusercontent.com/33591499/61391767-42aec980-a872-11e9-8d2b-9721827770df.png">
<img width="960" alt="proof of purchase" src="https://user-images.githubusercontent.com/33591499/61391774-48a4aa80-a872-11e9-8f44-0c1427ec6fc7.png">

3. Config files (optional)

**Comment by thangvo9x** [comment]
Could you share AppConfig file for checking? Thanks

**Comment by Peakabooo** [comment]
[AppConfig.txt](https://github.com/inspireui/support/files/3404453/AppConfig.txt)

[Config.txt](https://github.com/inspireui/support/files/3404459/Config.txt)

**Comment by thangvo9x** [comment]
Hi. Solutions
1.) Vendor can not add a product - (Cannot connect to server) -screenshots
=> add this block to .htaccess file 
`<IfModule mod_headers.c>
​    Header set Access-Control-Allow-Origin "*"
</IfModule> `
and check do you config right to JWT plugin?
2.) Error when going to settings. -screenshot
=> Please check update to the latest version? I don't see anything in this case.
3.) Contact us and about us is a blank page
=> You must have to change it int Config/index.js  find this field name is ProfileSettings & label is "contactus". change it to id yours 
4.) When selecting a category from the category/vendors tab it shows and error -screenshots
=> Try to replace this file.
remember that change from .txt -> .js 
Thanks 
[index.txt](https://github.com/inspireui/support/files/3404637/index.txt)

**Comment by Peakabooo** [comment]
Unable to resolve "./ProductRow" from "src/common/index.js"

![Screenshot_20190717-225541_Expo](https://user-images.githubusercontent.com/33591499/61432798-572ca980-a8e6-11e9-96c9-7cb0f1e36409.jpg)
![Screenshot_20190717-225554_Expo](https://user-images.githubusercontent.com/33591499/61432802-585dd680-a8e6-11e9-941e-159c2516da71.jpg)
![Screenshot_20190717-225600_Expo](https://user-images.githubusercontent.com/33591499/61432803-598f0380-a8e6-11e9-814b-92479eafab60.jpg)
![Screenshot_20190717-225605_Expo](https://user-images.githubusercontent.com/33591499/61432807-5ac03080-a8e6-11e9-80b2-0ead330d36a2.jpg)

**Comment by thangvo9x** [comment]
Change file at src/Containers/Category/ folder 
Thanks

**Comment by Peakabooo** [comment]
Is someone going to help me?

**Comment by Peakabooo** [comment]
After playing around with settings now when a user is trying to post a new item getting an error message that they do not have permission to post. Still getting error when i select on the setting from the menue. Can someone please help me. I have been waiting for a few days.

**Comment by thangvo9x** [comment]
Hi. user must have with Editor role to publish. Thanks

**Comment by Peakabooo** [comment]
Closing this you did not assist with anything and i asked for a refund.
