### ISSUE TITLE
[EvaStore] - icons issue, and store url issue

### ISSUE THREAD

**Issue by Patricetimchia** [inspireui/support#794]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue

2. Screenshots

3. My screenshot of the purchase product or my comment:

3. Config files (optional)

1. I have a few issues:
   a) I changed url in config file but it still loads your store on there, not mine
   b) Icons dont show. I even changed tab bar visibility to true but still doesn't show
   c) I am unable to test on my iphonedevice

Video explaining more: https://drive.google.com/file/d/1nZ0mK5E-7BCfc-GtTo8zHfT-05qN5O5f/view?usp=sharing

![Screen Shot 2019-07-17 at 8 07 24 PM](https://user-images.githubusercontent.com/37600664/61421944-f3e34d00-a8ce-11e9-907b-daa27a063ef1.png)

**Comment by minhcasi** [comment]
noted for checking - thank you!

**Comment by Patricetimchia** [comment]
Please can you guys check this and give me a solution, please. Thanks.

**Comment by Patricetimchia** [comment]
Worst support ever. I need a refund, otherwise I will place a bad review. Found a better product with better support

**Comment by minhcasi** [comment]
you can submit on this link - https://help.market.envato.com/hc/en-us/articles/202821460-Can-I-Get-A-Refund- - thanks
