### ISSUE TITLE
BeoNews] - failed to iOS project.

### ISSUE THREAD

**Issue by zziltong** [inspireui/support#795]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue

error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening beonews.xcodeproj

2. Screenshots

![스크린샷 2019-07-18 오전 10 36 52](https://user-images.githubusercontent.com/48820418/61422751-09e12400-a948-11e9-87f0-e461bdcd918e.png)

3. My screenshot of the purchase product or my comment:

3. Config files (optional)

**Comment by concuacon** [comment]
@zziltong  You try:
- run: react-native unlink react-native-fbsdk
- remove reference RCTFBSDK.xcodeproj under folder Libraries, and config Embedded Binaries and Link Framework Libraries as:
<img width="1409" alt="Screen Shot 2019-07-19 at 4 02 41 PM" src="https://user-images.githubusercontent.com/11958061/61523606-e5b43e80-aa3e-11e9-991b-a510b84dab5a.png">
 
- change Podfile
<img width="898" alt="Screen Shot 2019-07-19 at 3 57 56 PM" src="https://user-images.githubusercontent.com/11958061/61523162-016b1500-aa3e-11e9-86be-b09a5ccc1e16.png">
- clear Pods/ and run pod install, 

Hope this can help you.

**Comment by concuacon** [comment]
@zziltong pls, download FacebookSDK.zip and unzip copy  to folder Documents/
https://drive.google.com/file/d/1zTRhm1bosE6dQ2HbQvphmA9mITC6SV1k/view?usp=sharing

**Comment by nb05** [comment]
facing same issue

**Comment by concuacon** [comment]
pls, send me your source to email nguyentuan1707@gmail.com, i'll check it.

**Comment by minhcasi** [comment]
Hi, please update latest 3.0.3 for the fixing - thank you!
