### ISSUE TITLE
Color Variants on MStore

### ISSUE THREAD

**Issue by MatiasHad** [inspireui/support#797]
I have loaded in WooCommerce products with variants, the sizes load them correctly but I could not see the colors despite loading them in Color.js even using colors already loaded with the same slug

Could you help me?

Thank you

**Comment by minhcasi** [comment]
Hi, could you attach your config file so that we could investigate the issue 

And also send us your verified purchased product from https://codecanyon.net/downloads - thank you!

**Comment by MatiasHad** [comment]
I was able to solve it

**Comment by minhcasi** [comment]
Thank you!
