### ISSUE TITLE
Thumbnail Issue in Pro Version 3.6.2

### ISSUE THREAD

**Issue by hammadhassan** [inspireui/support#8]
My thumbnails are not displaying in pro version but working fine in expo version.

In ProductSize object. when i change Boolean to true following error occurs in pro version. Screenshot is attached.

ProductSize: {
    enable: false / true,
}

![image](https://user-images.githubusercontent.com/5791268/48374218-fbba7400-e6e5-11e8-8c6d-cf6c6fcfd4e1.png)

Please check & advice.

**Comment by minhcasi** [comment]
Hi, could you attach the config.js file - thank you!

**Comment by hammadhassan** [comment]
Here is the code.
[ Purchase Code
f20afe4a-778e-4089-bcb2-7ec1bb4ed49b
]
Both config files are attached expo & pro versions.

Please check both issues & if you want facebook login to create app on developers console to check login please let me know.

I have already created an app on developer account & code is in config file.

I also have one more issue.

I configure my app & website according to Netherlands but when is try to test order using stripe they shows we are not shipping to Netherlands?

Please check this one as well & guide me to fix all these 3 issues.

Thanks.

[Config.zip](https://github.com/inspireui/support/files/2577994/Config.zip)

**Comment by hammadhassan** [comment]
Hey!

Thanks for your new update 3.6.3.

It fixed 2 of my issues. Facebook Login & Thumbnail issue.

But i still have 2 issues.

1) Unable to ship to Netherlands

I did configure my app & website according to Netherlands but when is try to test order using stripe they shows we are not shipping to Netherlands?

Screenshot is attached. It displayed text in dutch that we are not ship to Netherlands.

![checkout](https://user-images.githubusercontent.com/5791268/48576546-a7f29980-e936-11e8-83dd-a5740dd0c7d5.PNG)

2) Stripe Payment Layout

Stripe Payment page popup displaying different view from default config.

Screenshot is also attached.

![stripe](https://user-images.githubusercontent.com/5791268/48576652-ed16cb80-e936-11e8-9938-7d161240e225.PNG)

Kindly guide me to fix these issues.

**Comment by luyx2412** [comment]
Hi @hammadhassan Let me check and reply you soon. Thanks for your waiting.

**Comment by minhcasi** [comment]
@hammadhassan do you have any idea why copy our branding website Logo, it's clearly that illegal 

https://gyazo.com/7dd1e1800b5962a810fb9785a9491656

**Comment by hammadhassan** [comment]
> 
> 
> @hammadhassan do you have any idea why copy our branding website Logo, it's clearly that illegal
> 
> https://gyazo.com/7dd1e1800b5962a810fb9785a9491656

okay. I will remove it. Website is in testing mode. you don't have to worry. I will remove it & give screen shot to you.

Could you please help me to fix Country & stripe payment page layout issue.
