### ISSUE TITLE
[MStore] - issues AccountKit/AccountKit.h' file not found

### ISSUE THREAD

**Issue by hakihosting** [inspireui/support#800]
Purchase code : ac9d522a-a783-4f9c-a882-7dc694488d5d

Hello i have this error : 
/RNAccountKitAdvancedUIManager.h:1:9: 'AccountKit/AccountKit.h' file not found

**Comment by smilechaitu** [comment]
try updating latest version 3.9.2 version solves this issue.

**Comment by hakihosting** [comment]
Where i can download this version on codecanyon is 9.0.0

**Comment by minhcasi** [comment]
Hi, try to download the latest version from https://codecanyon.net/downloads then try with following solution: 

1. Copy the from the download package mstore-pro/scripts/FacebookSDK to the Documents folder
2. From the folder mstore-pro, run with this script:
yarn install
yarn start --reset-cache
react-native run-ios

**Comment by hakihosting** [comment]
Same problem

**Comment by concuacon** [comment]
@hakihosting  Have you upgraded to version 3.9.2 ?

**Comment by concuacon** [comment]
You try follow steps:

- Check Podfile:
<img width="898" alt="Screen Shot 2019-07-19 at 3 57 56 PM" src="https://user-images.githubusercontent.com/11958061/61526758-43e42000-aa45-11e9-9b04-3471623df4ae.png">

- Xcode config like:
<img width="1409" alt="Screen Shot 2019-07-19 at 4 02 41 PM" src="https://user-images.githubusercontent.com/11958061/61526826-64ac7580-aa45-11e9-849d-1b0aab8ead01.png">
<img width="749" alt="Screen Shot 2019-07-19 at 4 57 10 PM" src="https://user-images.githubusercontent.com/11958061/61527298-4c892600-aa46-11e9-93d3-534d06075fd2.png">


- Run: rm -rf node_modules/ && yarn cache clean && yarn && cd ios/ && rm -rf Pods/ && rm -rf Podfile.lock && pod install && cd .../ && yarn start --reset-cache  (if you use yarn)

- Run: rm -rf node_modules/ && npm cache clean && npm i && cd ios/ && rm -rf Pods/ && rm -rf Podfile.lock && pod install && cd .../ && react-native start --reset-cache (if you use npm)

**Comment by hakihosting** [comment]
Hello when i execute your command i have this : 
Fetching podspec for `yoga` from `../node_modules/react-native/ReactCommon/yoga`
[!] CocoaPods could not find compatible versions for pod "AccountKit":
  In Podfile:
    AccountKit

    RNAccountKit (from `../node_modules/react-native-facebook-account-kit/ios`) was resolved to 1.2.0, which depends on
      AccountKit (~> 5.0)

Specs satisfying the `AccountKit, AccountKit (~> 5.0)` dependency were found, but they required a higher minimum deployment target.

[!] Automatically assigning platform `ios` with version `9.0` on target `mstore` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

**Comment by hakihosting** [comment]
![image](https://user-images.githubusercontent.com/47614045/61544001-ce784f80-aa44-11e9-8dc3-bb12317145e5.png)

**Comment by hakihosting** [comment]
I think now it's better : 
Downloading dependencies
Installing AccountKit (5.0.1)
Installing Bolts (1.9.0)
Installing DoubleConversion (1.1.6)
Installing FBSDKCoreKit (5.2.3)
Installing FBSDKLoginKit (5.2.3)
Installing FBSDKShareKit (5.2.3)
Installing Folly (2018.10.22.00)
Installing Google-Mobile-Ads-SDK (7.37.0)
Installing RNAccountKit (1.2.0)
Installing React (0.59.8)
Installing boost-for-react-native (1.63.0)
Installing glog (0.3.5)
Installing react-native-fbsdk (0.8.0)
Installing yoga (0.59.8.React)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 19 dependencies from the Podfile and 14 total pods installed.

Just do a pod update

**Comment by hakihosting** [comment]
This error now :s 
ld: warning: directory not found for option '-L/Users/heyckelneji/Library/Developer/Xcode/DerivedData/mstore-gtgyevlzphvlerblzpncndcvaxkp/Build/Products/Debug-iphoneos/Bolts'
ld: warning: directory not found for option '-L/Users/heyckelneji/Library/Developer/Xcode/DerivedData/mstore-gtgyevlzphvlerblzpncndcvaxkp/Build/Products/Debug-iphoneos/DoubleConversion'
ld: warning: directory not found for option '-L/Users/heyckelneji/Library/Developer/Xcode/DerivedData/mstore-gtgyevlzphvlerblzpncndcvaxkp/Build/Products/Debug-iphoneos/FBSDKCoreKit'
ld: warning: directory not found for option '-L/Users/heyckelneji/Library/Developer/Xcode/DerivedData/mstore-gtgyevlzphvlerblzpncndcvaxkp/Build/Products/Debug-iphoneos/FBSDKLoginKit'
ld: warning: directory not found for option '-L/Users/heyckelneji/Library/Developer/Xcode/DerivedData/mstore-gtgyevlzphvlerblzpncndcvaxkp/Build/Products/Debug-iphoneos/FBSDKShareKit'
ld: warning: directory not found for option '-L/Users/heyckelneji/Library/Developer/Xcode/DerivedData/mstore-gtgyevlzphvlerblzpncndcvaxkp/Build/Products/Debug-iphoneos/Folly'
ld: warning: directory not found for option '-L/Users/heyckelneji/Library/Developer/Xcode/DerivedData/mstore-gtgyevlzphvlerblzpncndcvaxkp/Build/Products/Debug-iphoneos/RNAccountKit'
ld: warning: directory not found for option '-L/Users/heyckelneji/Library/Developer/Xcode/DerivedData/mstore-gtgyevlzphvlerblzpncndcvaxkp/Build/Products/Debug-iphoneos/React'
ld: warning: directory not found for option '-L/Users/heyckelneji/Library/Developer/Xcode/DerivedData/mstore-gtgyevlzphvlerblzpncndcvaxkp/Build/Products/Debug-iphoneos/glog'
ld: warning: directory not found for option '-L/Users/heyckelneji/Library/Developer/Xcode/DerivedData/mstore-gtgyevlzphvlerblzpncndcvaxkp/Build/Products/Debug-iphoneos/react-native-fbsdk'
ld: warning: directory not found for option '-L/Users/heyckelneji/Library/Developer/Xcode/DerivedData/mstore-gtgyevlzphvlerblzpncndcvaxkp/Build/Products/Debug-iphoneos/yoga'
ld: library not found for -lBolts
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by hakihosting** [comment]
![image](https://user-images.githubusercontent.com/47614045/61548401-eaccba00-aa4d-11e9-8b89-7f8aad4e6024.png)

**Comment by yosefasad** [comment]
@hakihosting @concuacon

Hi hakihosting .  

I had the same problem ...I solved by these steps 

1. change the build system to legacy build system 
2.  Open 'Build Settings', search 'Header Search Path'.
Double click next to 'Header Search Path', where other properties have a 'yes' or 'no'
Now add following to the "Header Search Path" (under Build Settings):
$(SRCROOT)/../node_modules/react-native/React
3. Follow  the steps  provided by @concuacon in [this post](https://github.com/inspireui/support/issues/767) 

Run: rm -rf node_modules/ && yarn cache clean && yarn
Run: cd ios/ && rm -rf build/ && rm -rf Pods/ && rm -rf Podfile.lock && pod install && cd ../
Run: react-native run-ios
and clear cache Xcode Command + shift + k

Thanks to @concuacon for his great help...

I hope this will help ...

**Comment by hakihosting** [comment]
Hello i do your solution now i have this 
![image](https://user-images.githubusercontent.com/47614045/61598334-772cd780-ac1c-11e9-9774-deedd011f332.png)

**Comment by yosefasad** [comment]
have you tried my solution on fresh installation of Mstore ?

**Comment by hakihosting** [comment]
now i try now on fresh installation

**Comment by hakihosting** [comment]
Hello , yes i do on fresh install now  : 

WriteAuxiliaryFile /Users/heyckelneji/Downloads/mstore-3.9.2\ 2/mstore-pro/ios/build/mstore/Build/Intermediates.noindex/RNAccountKit.build/Debug-iphonesimulator/RNAccountKit.build/Objects-normal/x86_64/RNAccountKit.LinkFileList (in target: RNAccountKit)
    cd /Users/heyckelneji/Downloads/mstore-3.9.2\ 2/mstore-pro/node_modules/react-native-facebook-account-kit/ios
    write-file /Users/heyckelneji/Downloads/mstore-3.9.2\ 2/mstore-pro/ios/build/mstore/Build/Intermediates.noindex/RNAccountKit.build/Debug-iphonesimulator/RNAccountKit.build/Objects-normal/x86_64/RNAccountKit.LinkFileList


error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening mstore.xcworkspace

** BUILD FAILED **


The following commands produced analyzer issues:
        Analyze /Users/heyckelneji/Downloads/mstore-3.9.2\ 2/mstore-pro/node_modules/react-native/ReactCommon/yoga/yoga/Yoga.cpp normal x86_64
        Analyze /Users/heyckelneji/Downloads/mstore-3.9.2\ 2/mstore-pro/node_modules/react-native/React/Base/RCTModuleMethod.mm normal x86_64
(2 commands with analyzer issues)

The following build commands failed:
        CompileC /Users/heyckelneji/Downloads/mstore-3.9.2\ 2/mstore-pro/ios/build/mstore/Build/Intermediates.noindex/RNAccountKit.build/Debug-iphonesimulator/RNAccountKit.build/Objects-normal/x86_64/RNAccountKit.o /Users/heyckelneji/Downloads/mstore-3.9.2\ 2/mstore-pro/node_modules/react-native-facebook-account-kit/ios/RNAccountKit.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

**Comment by yosefasad** [comment]
please try to clean and build from Xcode itself

**Comment by hakihosting** [comment]
same problem = 
![image](https://user-images.githubusercontent.com/47614045/61598646-2ff51580-ac21-11e9-8c4b-266320ce8e88.png)

**Comment by hakihosting** [comment]
![image](https://user-images.githubusercontent.com/47614045/61598849-210f6280-ac23-11e9-9be0-e28bf2526b4f.png)

**Comment by hakihosting** [comment]
![image](https://user-images.githubusercontent.com/47614045/61599016-ffaf7600-ac24-11e9-9eb6-f6c3e98bb817.png)

**Comment by concuacon** [comment]
@hakihosting pls check config your xcode the same
<img width="960" alt="Screen Shot 2019-07-22 at 10 58 20 AM" src="https://user-images.githubusercontent.com/11958061/61605445-b5071b80-ac6f-11e9-81f0-dcb071dca041.png">

<img width="642" alt="Screen Shot 2019-07-22 at 10 57 31 AM" src="https://user-images.githubusercontent.com/11958061/61605460-bfc1b080-ac6f-11e9-8aa1-9507eece8ead.png">

<img width="657" alt="Screen Shot 2019-07-22 at 10 57 22 AM" src="https://user-images.githubusercontent.com/11958061/61605466-c8b28200-ac6f-11e9-920d-951248899428.png">

- try again https://github.com/inspireui/support/issues/800#issuecomment-513171206

**Comment by hakihosting** [comment]
I follow your step and i find this : 
![image](https://user-images.githubusercontent.com/47614045/61615462-55f0d900-ac66-11e9-89f6-aaeb61c2ebe3.png)

**Comment by hakihosting** [comment]
My pod file : 
target 'mstore' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # Needed for debugging
    'RCTAnimation', # Needed for FlatList and animations running on native UI thread
    # Add any other subspecs you want to use in your project
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'Bolts',         '~> 1.9'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit' 
  pod 'Google-Mobile-Ads-SDK', '~> 7.37.0'
  pod 'AccountKit', '~> 5.0.1'
  pod 'RNAccountKit', :path => '../node_modules/react-native-facebook-account-kit/ios'

  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

end

**Comment by hakihosting** [comment]
i delete the folder and i try again with a fresh installation

**Comment by concuacon** [comment]
@hakihosting

> i delete the folder and i try again with a fresh installation

result?

**Comment by concuacon** [comment]
you try change Podfile the same this photo and re-install:
<img width="838" alt="Screen Shot 2019-07-22 at 4 18 46 PM" src="https://user-images.githubusercontent.com/11958061/61621095-6de34f80-ac9c-11e9-84b4-7805d750c662.png">

**Comment by hakihosting** [comment]
i try now

**Comment by hakihosting** [comment]
Same problem = 
![image](https://user-images.githubusercontent.com/47614045/61639274-77b88300-ac9b-11e9-8892-83956a381b38.png)

Podfile : 
target 'mstore' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # Needed for debugging
    'RCTAnimation', # Needed for FlatList and animations running on native UI thread
    # Add any other subspecs you want to use in your project
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'Bolts',         '~> 1.9'
  pod 'FBSDKCoreKit',         '~> 4.42.0'
  pod 'FBSDKLoginKit',         '~> 4.42.0'
  pod 'FBSDKShareKit' ,         '~> 4.42.0'
  pod 'Google-Mobile-Ads-SDK', '~> 7.37.0'
  pod 'AccountKit'
  pod 'RNAccountKit', :path => '../node_modules/react-native-facebook-account-kit/ios'

  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

end

**Comment by hakihosting** [comment]
maybe can we have a skype session or else ?

**Comment by concuacon** [comment]
@hakihosting   my skype id: pvtuan1707

**Comment by anastely** [comment]
Any update ?
