### ISSUE TITLE
How I Install Magento MStore React Native Package on Ubuntu Machine?

### ISSUE THREAD

**Issue by DEEPAKSINGHRAGHAV** [inspireui/support#801]
I purchased Magento Mstore  package.
I Install my magento 2 setup and all things are done.
But for app I'm going to use your theme package purchased from https://codecanyon.net/item/mstore-magento-the-complete-react-native-app-for-magento-2/23587085
After purchase I can't able to run sudo npm install or sudo npm run setup etc.

Help me resolve this.
On your youtube channel there is two options to install one for  windows and second for Mac, What about the linux users.

Do I need to install windows or buy mac machine for this setup?

**Comment by minhcasi** [comment]
Hi, you can refer to this guide to setup from library use for the Linux first - https://facebook.github.io/react-native/docs/getting-started.html

Then install app is the same by using "yarn install"

**Comment by vrdvishwas** [comment]
I've same issue.
Watched youtube videos and got CE Builder to activate purchased package.
I've purchased licence key.
But not know where to put in  which file? 
Without activation package on test run not showing any results.
Please help to activate this package and run it complete on linux machine.

**Comment by DEEPAKSINGHRAGHAV** [comment]
@minhcasi ,
Please open this ticket again.

According to the above reply, I've still the same issue.

I install using your help.
But unable to complete run.
