### ISSUE TITLE
[MStore Pro] - Variation not showing out of stock

### ISSUE THREAD

**Issue by ItisAhsan** [inspireui/support#802]
---------

Few variations of my products are out of stock.. but customer can still buy it from the app.. this is very embarrassing.. the product is out of stock and unable to buy from website but not from the app please help me fix the issue asap

I have attached screen shot of the product on website and on application.. I have update application to 3.9.2 but still the issue remains
![Screenshot_2019-07-19 Impression (black) Tens Shoes](https://user-images.githubusercontent.com/12572962/61541474-2751e300-aa59-11e9-8f33-d2d726159cee.png)
![WhatsApp Image 2019-07-19 at 7 08 25 PM](https://user-images.githubusercontent.com/12572962/61541499-389aef80-aa59-11e9-8728-8ac4d204cc13.jpeg)

**Comment by ItisAhsan** [comment]
![image](https://user-images.githubusercontent.com/12572962/61541712-962f3c00-aa59-11e9-833b-a626061ad83f.png)

**Comment by minhcasi** [comment]
@ItisAhsan could you mind attaching your config file here (the common/appconfig.json and config.js) files, or you can send it privately to our email - support@inspireui.com - thank you!

@concuacon - pls hep to check this issue

**Comment by ItisAhsan** [comment]
[common.zip](https://github.com/inspireui/support/files/3413659/common.zip)
here you go... please help.. it's urgent.

**Comment by ItisAhsan** [comment]
I have sent email please through wetransfer.... please check..

**Comment by ItisAhsan** [comment]
please help it's urgent

**Comment by minhcasi** [comment]
Okay, we are checking and will let you know - thanks

@concuacon

**Comment by ItisAhsan** [comment]
still waiting

**Comment by ItisAhsan** [comment]
hey there.. I'm still waiting for the response... please guys this is urgent.

**Comment by ItisAhsan** [comment]
Hey man... still waiting..

**Comment by minhcasi** [comment]
hi, just note that we are checking as this quite complex issue and we should restart the testing process - thanks

**Comment by ItisAhsan** [comment]
can you give me an estimated time? so I can tell my client? I'm facing a lot of embarrassment because of this...

**Comment by ItisAhsan** [comment]
Hi there... I'm still waiting.. please help

**Comment by minhcasi** [comment]
@concuacon

**Comment by ItisAhsan** [comment]
is this issue fixed on the latest version?

**Comment by ItisAhsan** [comment]
the issue still haven't been solved. please check email and please respond urgently
