### ISSUE TITLE
[beonews] - when i do archive in xcode app goto to other item 

### ISSUE THREAD

**Issue by ramyragab1** [inspireui/support#803]
---------
purchase product code: 97f0836c-e11f-4c68-8295-862a7571a9ff
1. when i do archive in xcode app goto to other item and cant uploda it to store

2. https://www.dropbox.com/s/rd0pf6q8p8g52rl/Screen%20Shot%202019-07-20%20at%209.17.41%20AM.png?dl=0

purchase product code: 97f0836c-e11f-4c68-8295-862a7571a9ff

**Comment by minhcasi** [comment]
Duplicate of #780 @concuacon

**Comment by ramyragab1** [comment]
Didn't work also

**Comment by minhcasi** [comment]
Pls download latest 3.0.4 to fix the issue - thank you!
