### ISSUE TITLE
Beonews - pro

### ISSUE THREAD

**Issue by nb05** [inspireui/support#805]
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening beonews.xcodeproj

** BUILD FAILED **

**Comment by nb05** [comment]
any update

**Comment by minhcasi** [comment]
1. could you verify the purchased by taking the screenshot from https://codecanyon.net/downloads

2. Try to attach the detailed screenshot, it seems you have missing config, please double-check from - http://docs.inspireui.com/beonews

**Comment by nb05** [comment]
useless reply do you think I will post without ordering, pls after 2 days getting this kind of reply

**Comment by nb05** [comment]
attached image
![Screen Shot 2019-07-24 at 1 07 23 AM](https://user-images.githubusercontent.com/14836289/61750986-85f7c380-adaf-11e9-94d6-b89984c6d4dc.png)

**Comment by minhcasi** [comment]
Hi, pls check one of following solution: 

1. Clean up the cache by this script:
watchman watch-del-all && rm -rf $TMPDIR/react-* && rm -rf node_modules/ && yarn cache clean && yarn install && yarn start -- --reset-cache

2. Open the XCode to clean up the cache: Ctrl + Command + K and restart the app again.

**Comment by minhcasi** [comment]
Hi, please let us know your checking, I'm closing this issue as there is no response - kindly reopen if it does not work - thank you!
