### ISSUE TITLE
i can't add new language to the app 

### ISSUE THREAD

**Issue by masaud96** [inspireui/support#806]
![3](https://user-images.githubusercontent.com/45623602/61588502-760c9380-aba5-11e9-9381-d07ed839b3e4.PNG)
![2](https://user-images.githubusercontent.com/45623602/61588504-760c9380-aba5-11e9-8878-dcceeb5e644c.PNG)

I try to follow the instructions on the website but when I do and add another language it stops working and crashes when I compile it.

**Comment by masaud96** [comment]
![1](https://user-images.githubusercontent.com/45623602/61588549-11056d80-aba6-11e9-8f42-e2acbe3f2992.PNG)

I use this code to add other language.

**Comment by minhcasi** [comment]
1. could you help to verify the purchased by taking the screenshot of your purchased product from - https://codecanyon.net/downloads - then reopen the ticket

2. Attache then issue screenshot and the config file from the common folder

Thank you!

**Comment by masaud96** [comment]
[image: 3.PNG]
[image: 1.PNG]
[image: 2.PNG]

i can't add new language to the app

hi

I upload the needed documents. and I hope you can help me to solve this
problem.
And if you can open the GitHub post.

Thank you.

**Comment by masaud96** [comment]
hi Inspireui/Support
I hope this email finds you well.
I have a question about how to change the font in the intro screen?

with regards

Ali Hasan

think up team
