### ISSUE TITLE
[my-product] - Build not creating

### ISSUE THREAD

**Issue by markoi3** [inspireui/support#807]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

I've installed all the required plugins, setup Wocommerce API keys but when I try to create a automatic build (android) on Delivery page in CeBuilder, I'm getting this error:
![error](https://user-images.githubusercontent.com/13971688/61588675-1069d880-aba0-11e9-83c4-216380dba259.png)

-My screenshot of the purchase product or my comment:
![FireShot Capture 151 - Downloads - CodeCanyon - codecanyon net](https://user-images.githubusercontent.com/13971688/61588684-2a0b2000-aba0-11e9-8b59-f44befc7d648.png)

**Comment by minhcasi** [comment]
Hi pls try to copy the project folder to C: hard drive will fix the issue - thank you!
