### ISSUE TITLE
[MMV] So many issues, this product looks unfinished

### ISSUE THREAD

**Issue by markoi3** [inspireui/support#808]
The Mstore App for WC Vendors is extremely clunky and has a lot of bugs. I bought it yesterday and I have to say that this product looks unfinished, where basic features are not working, yet they are advertised like they do work. Needless to say, I expect to receive a support to fix these bugs.

1) When vendor signs up through the app, in the Wordpress admin, they are not assigned a user role. User signed up through the app has "No role". WC Vendors assigns a user role "Vendor" to all the vendors. This is essential because they need to have a Vendor role in order to be able to publish products and to calculate and receive commission.

2) Products cannot be published. See the error below.
![Screenshot_20190721-130805_Expo](https://user-images.githubusercontent.com/13971688/61590675-1c17c800-abbd-11e9-8583-c9e26cfcc277.jpg)

3) "My products" list is empty even tough the vendor has many products.
![Screenshot_20190721-132214_Expo (1)](https://user-images.githubusercontent.com/13971688/61590716-7fa1f580-abbd-11e9-93cc-5fee2527e2d7.jpg)

4) Also, notice the wording "You don't have any orders"? That should say "You don't have any products yet".

5) I also don't understand why the "Shop" button is on the "My Product" page. This needs to be removed.

6) Cart page is not accessible:
![Screenshot_20190721-134725_Expo](https://user-images.githubusercontent.com/13971688/61590821-99900800-abbe-11e9-9232-f7a5c066ae12.jpg)

7) Share option on the product page is not working. When I try to share the link for the product - it is not copied - what only gets copied is the product title.

8) "My orders" list page is acting weird. First when I entered the page, there were no orders showing, blank. Next, I clicked on "back" arrow button in the header and then it showed me the current's vendors orders.

9) Product images are not showing.

Purchase screenshot:

![FireShot Capture 151 - Downloads - CodeCanyon - codecanyon net](https://user-images.githubusercontent.com/13971688/61590906-86316c80-abbf-11e9-86c0-0caa9d5630bf.png)

**Comment by thangvo9x** [comment]
1. When vendor signs up through the app, in the Wordpress admin, they are not assigned a user role. User signed up through the app has "No role". WC Vendors assigns a user role "Vendor" to all the vendors. This is essential because they need to have a Vendor role in order to be able to publish products and to calculate and receive commission.
=> Recorded but the user must have to Editor role to publish that product to the website.
2. Products cannot be published. See the error below. 
=> Check user role such as config JWT plugin on your website.
3. Also, notice the wording "You don't have any orders"? That should say "You don't have any products yet".
=> You could change it in Languages.js file.
4. I also don't understand why the "Shop" button is on the "My Product" page. This needs to be removed.
=> This button would encourage the user to buy more when redirecting back to the Shop page. This could increase the experience of the user.
5. Cart page is not accessible: 
=> Try to replace this file (Remember to change from .txt to .js tag).
[index.txt](https://github.com/inspireui/support/files/3416819/index.txt)
Could you share AppConfig to check? Thanks.

**Comment by markoi3** [comment]
1. I didn't quite understand - that means that app doesn't support WC Vendors system?

2. You mean JWT Authentication for WP REST API? Can you please explain what should I do?

5. Where is this index.js located? And where us AppConfig? I can only see ReactotronConfig in my **mstore-mv-expo** folder.

**Comment by markoi3** [comment]
And I would appreciate answers to other issues.

**Comment by markoi3** [comment]
This is the API log when I try to create a product:

![api log](https://user-images.githubusercontent.com/13971688/61655360-b9a6f080-acbe-11e9-98c2-8706ced0655f.png)

**Comment by thangvo9x** [comment]
> 1. I didn't quite understand - that means that app doesn't support WC Vendors system?
> 2. You mean JWT Authentication for WP REST API? Can you please explain what should I do?
> 3. Where is this index.js located? And where us AppConfig? I can only see ReactotronConfig in my **mstore-mv-expo** folder.

=> 1. No. Before add props to your AppConfig.js
    "isWCFM": true
put in WooCommerce property.
 Try to replace this file at containers/Categories/VendorTab.js
[VendorTab.txt](https://github.com/inspireui/support/files/3420813/VendorTab.txt)
and this file at Services/CustomAPI.js
[CustomAPI.txt](https://github.com/inspireui/support/files/3420821/CustomAPI.txt)
Rememerber that change from .txt -> .js tag. 
Thanks 
2. Yup. config the JWT Authentication 
=> Refer here https://wordpress.org/plugins/jwt-authentication-for-wp-rest-api/
3. put in Components/ProductRow/ 
Thanks. 
now, My Product isn't working with WC-lovers. We'll have an update ASAP.

**Comment by markoi3** [comment]
I attached my AppConfig:

```
{
  "WooCommerce": {
    "url": "https://gigrove.com",
    "useWCV": true,
    "isWCFM": true,
    "consumerKey": "ck_5c05ea5f9549ed5a6946385b1c505394d944887a",
    "consumerSecret": "cs_58e813f343cd8787384e3a06d6a4e273344f2f2a"
  },
  "HorizonLayout": [
    { "tag": 37, "layout": 10 },
    {
      "layout": 14,
      "tag": 83
    },
    {
      "name": "Feature Products",
      "featured": true,
      "image": "",
      "layout": 6
    },
    {
      "name": "On Sale Products",
      "onSale": true,
      "image": "",
      "layout": 2
    },
    {
      "name": "Decor Art",
      "category": 66,
      "image": "",
      "layout": 8
    },
    {
      "name": "Furniture",
      "category": 76,
      "image": "",
      "layout": 1
    }
  ],
  "MainColor": "#00BCD4"
})
```

- I've replaced the files at **contaniers/categories/vendotab.js** and **services/customapi.js**. 

2) I've installed the JWT auth plugin and configured it.

3) I've placed **index.js** in the **components/productrow**

The problem still persists - I can't publish products. 
I also tried disabling WCFM and the issue is still there. No products are being shown on "My products" page.

**Comment by markoi3** [comment]
Now the error is "Can't connect to a server". This is the response that I got:
![response](https://user-images.githubusercontent.com/13971688/61712427-97f94800-ad56-11e9-8268-d189c05646c8.png)

**Comment by thangvo9x** [comment]
Hi guy. Try to add this block to .htaccess file.
<IfModule mod_headers.c>
​    Header set Access-Control-Allow-Origin "*"
</IfModule>
Refer more here : https://wordpress.org/plugins/jwt-authentication-for-wp-rest-api/
Thanks

**Comment by markoi3** [comment]
It's not working, I'm getting the same error. Really frustrating.

**Comment by thangvo9x** [comment]
Share the AppConfig.json file for checking?

**Comment by markoi3** [comment]
I shared already -
```
{
  "WooCommerce": {
    "url": "https://gigrove.com",
    "useWCV": true,
    "isWCFM": true,
    "consumerKey": "ck_5c05ea5f9549ed5a6946385b1c505394d944887a",
    "consumerSecret": "cs_58e813f343cd8787384e3a06d6a4e273344f2f2a"
  },
  "HorizonLayout": [
    { "tag": 37, "layout": 10 },
    {
      "layout": 14,
      "tag": 83
    },
    {
      "name": "Feature Products",
      "featured": true,
      "image": "",
      "layout": 6
    },
    {
      "name": "On Sale Products",
      "onSale": true,
      "image": "",
      "layout": 2
    },
    {
      "name": "Decor Art",
      "category": 66,
      "image": "",
      "layout": 8
    },
    {
      "name": "Furniture",
      "category": 76,
      "image": "",
      "layout": 1
    }
  ],
  "MainColor": "#00BCD4"
})
```

**Comment by thangvo9x** [comment]
Could you share the account login to admin? You missed some plugins. as JWT isn't installed.
