### ISSUE TITLE
[Cestore] Project Installation and startup issue

### ISSUE THREAD

**Issue by rajqumar** [inspireui/support#81]
**Mandatory Info (please complete the following information):**
 - Product: [e.g. Cestore - Cezerin]
 - Your Purchased Code: 22706124

Inside Source/web folder
After yarn install
when I run app using yarn build and yarn start I get this

ERROR in ./node_modules/theme/dist/lib/apiClient.js
Module not found: Error: Can't resolve '../../../config/server' in '/var/codes/cestore/Source/web/node_modules/theme/dist/lib'
 @ ./node_modules/theme/dist/lib/apiClient.js 3:0-52 60:11-25
 @ ./node_modules/theme/dist/components/signUp/index.js
 @ ./node_modules/theme/dist/containers/shared.js
 @ ./node_modules/theme/dist/index.js
 @ multi theme

**Comment by minhtruong315** [comment]
Hi @rajqumar inside source/web folder, you can run "npm run app:install", then run npm start

**Comment by rajqumar** [comment]
> Hi @rajqumar inside source/web folder, you can run "npm run app:install", then run npm start

Thank you, it works

**Comment by fahmidev013** [comment]
what is the different of npm run build and npm run build:watch ?? i cant my app full functional work  especially chart menu contact and etc
