### ISSUE TITLE
[Listapp] - Language view setting / RTL

### ISSUE THREAD

**Issue by reconshield** [inspireui/support#810]
now i have 2 language in my app. default english and tamil. i used default arabic file and replace all contents...but when switch to arabic.its display right to left...how i can set arabic/new tamil to left to right reading? RTL

**Comment by thangvo9x** [comment]
hi. There's an option in Common/Constants.js with name is "RTL" 
Try to change it.

**Comment by reconshield** [comment]
yes..i change RTL to true..but its same...
