### ISSUE TITLE
[BeoNews] webview img resize tag isn't work

### ISSUE THREAD

**Issue by zziltong** [inspireui/support#811]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue

img: { resizeMode : 'contain' } isn't work
2. Screenshots

3. My screenshot of the purchase product or my comment:

3. Config files (optional)

**Comment by minhcasi** [comment]
HI, pls provide more detail screenshot so that we could know what is your issue - thanks
