### ISSUE TITLE
[mstore-pro] - Image and button is not visible

### ISSUE THREAD

**Issue by Pavithran10** [inspireui/support#812]
1. My issue
       1. In mstore-pro app in the add cart page **select the payment** option is there in that **first payment option image is not visible** after sets the correct image in exact location.
       2. In that same page one more issue **next button** is not visible but it's working. And then this issue occurs through out add cart modules pages.

2. Screenshots
![issue](https://user-images.githubusercontent.com/46148046/61610606-3f06b280-ac77-11e9-862c-701020c4fa05.jpg)
![issue2](https://user-images.githubusercontent.com/46148046/61610618-46c65700-ac77-11e9-99a6-22b0ba08e512.jpg)
![issue3](https://user-images.githubusercontent.com/46148046/61610636-4d54ce80-ac77-11e9-9443-263716023785.jpg)

**Comment by Pavithran10** [comment]
hi, anybody is there to help to solve this issue.

**Comment by minhcasi** [comment]
Hi @Pavithran10 - we could replicate the issue from our side, looks like your customization cause this issue?

The payment image could be updated from the config.js file 

Thanks

**Comment by Pavithran10** [comment]
hi, yeah I know that but i updated the first image already and also image is can't visible then second and third image also updated myself that images are visible what the problem I don't know.
then i reported one more issue to you yesterday **next button** is not visible. please report that issue too.
thanks.

**Comment by minhcasi** [comment]
Hi, we checked it working fine on latest 3.9.2 both ios and android, could you help to re-download as test again ? Thanks

**Comment by Pavithran10** [comment]
thanks we will check
