### ISSUE TITLE
MStore Pro - Complete React Native template for e-commerce

### ISSUE THREAD

**Issue by itspathanofficial** [inspireui/support#813]
1. My issue : i am not able to build android app with cebuilder, it is showing so much errors while building android app. it showing no ios identifier but i want to build app only for android why i ios identifier?

2. Screenshots : 
![ss](https://user-images.githubusercontent.com/34849884/61611440-665e7f00-ac79-11e9-8404-c437a83cfc0e.png)

3. My screenshot of the purchase product or my comment: 
![ss](https://user-images.githubusercontent.com/34849884/61611478-842be400-ac79-11e9-9ebd-8e9d99a29f59.png)

3. Config files (optional)

**Comment by minhcasi** [comment]
Noted for checking the Cebuilder issue 

@minhtruong315

**Comment by minhtruong315** [comment]
@itspathanofficial can you send me app.json file?

**Comment by itspathanofficial** [comment]
[mstore-expo.zip](https://github.com/inspireui/support/files/3437870/mstore-expo.zip)
[mstore-pro.zip](https://github.com/inspireui/support/files/3437871/mstore-pro.zip)
 both app.json files are attached, please reply asap i want to publish my app on play store.

**Comment by itspathanofficial** [comment]
I do not want to create any ios app so why this error message show every  time in CeBuilder?

Error: Problem validating fields in app.json. See https://docs.expo.io/versions/v33.0.0/workflow/configuration/
 • Field: ios.bundleIdentifier - 'ios.bundleIdentifier' should be a iOS bundle identifier notation unique name for your app. For example, host.exp.exponent, where exp.host is our domain and Expo is our app..
Couldn't publish because errors were found. (See logs above.) Please fix the errors and try again.

**Comment by minhcasi** [comment]
@minhtruong315

**Comment by minhcasi** [comment]
@itspathanofficial - could i confirm you are using the latest cebuilder 0.35 - https://github.com/inspireui/cebuilder/releases ?

**Comment by minhcasi** [comment]
Alos, download the latest 3.9.3 to fix the issue, confirm it is fixed - thank you!
