### ISSUE TITLE
[ListApp] Multi Language Picker

### ISSUE THREAD

**Issue by git-palace** [inspireui/support#814]
Where's multi language picker?
The change logs shows me there's multi language picker in the settings page.
Where is it? I can't see.

![2019-07-22_10h12_30](https://user-images.githubusercontent.com/25261362/61652968-07473d00-ac6e-11e9-8c29-c178c2a86fcf.png)

**Comment by thangvo9x** [comment]
In the left menu sidebar.

**Comment by git-palace** [comment]
Can you upload a screenshot?

**Comment by thangvo9x** [comment]
<img width="487" alt="Screen Shot 2019-07-23 at 5 22 32 PM" src="https://user-images.githubusercontent.com/23457178/61704680-77d58300-ad6e-11e9-8cf7-a09810b25531.png">


> Can you upload a screenshot?

**Comment by git-palace** [comment]
Can I add more languages there?

**Comment by thangvo9x** [comment]
Yup. Add your languages in Languages.js file 
and add more choice at Container/Setting/LangSwitch.js 
Thanks
