### ISSUE TITLE
[mstore-multivendor] - 

### ISSUE THREAD

**Issue by codingastronaut** [inspireui/support#815]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue
"cant get data from server" on mstore multivendor after install
![IMG_2482](https://user-images.githubusercontent.com/17095995/61674773-4b2d5700-aced-11e9-83e3-046059bea7c5.PNG)
![IMG_2483](https://user-images.githubusercontent.com/17095995/61674774-4bc5ed80-aced-11e9-9ce5-735409cb272f.PNG)

2. Screenshots

3. My screenshot of the purchase product or my comment:
![Screenshot 2019-07-23 at 01 56 05](https://user-images.githubusercontent.com/17095995/61674745-17eac800-aced-11e9-8df4-e4ddc09e6b5c.jpg)

3. Config files (optional)

[configs.zip](https://github.com/inspireui/support/files/3419621/configs.zip)

**Comment by codingastronaut** [comment]
![Screenshot 2019-07-23 at 02 01 54](https://user-images.githubusercontent.com/17095995/61674895-e1fa1380-aced-11e9-8b03-719b298739d3.jpg)

**Comment by thangvo9x** [comment]
Hi bro. You must have change correct on your category/tag to your website.
http://prntscr.com/oivbya
Thanks

**Comment by codingastronaut** [comment]
im confused, you need to explain more or add it in the documentation

**Comment by thangvo9x** [comment]
My mean. You must have map category on your website to the AppConfig.json file.
Ex: 
<img width="505" alt="Screen Shot 2019-07-24 at 3 11 19 PM" src="https://user-images.githubusercontent.com/23457178/61776480-4cfa3600-ae25-11e9-8961-4968be1d52f4.png">
Attached image. Refer please.

**Comment by codingastronaut** [comment]
![Screenshot 2019-07-24 at 11 32 45](https://user-images.githubusercontent.com/17095995/61787400-a18eb880-ae07-11e9-974e-fc99674bcd68.jpg)
![Screenshot 2019-07-24 at 11 32 57](https://user-images.githubusercontent.com/17095995/61787402-a2274f00-ae07-11e9-9be7-1f5e0106140a.jpg)
![Screenshot 2019-07-24 at 11 33 11](https://user-images.githubusercontent.com/17095995/61787403-a2274f00-ae07-11e9-8144-156fb92132ba.jpg)
ive done that, and im still having the same issues, could i just send you the admin details and my appconfig?

**Comment by thangvo9x** [comment]
Maybe the error has occurred on CeBuilder. Try to config by manual as previous mention (attached image).
