### ISSUE TITLE
[ListApp] TypeError: null is not an object (evaluating 'c.id')

### ISSUE THREAD

**Issue by menzer2015** [inspireui/support#82]
**Required Info (please complete the following information):**
 - Product: ListApp
 - Your Purchased Code:  1d8d4ae7-****-****-****-a869ce764483 
**Describe the bug**
TypeError: null is not an object (evaluating 'c.id')

This happens on a fresh install of your latest version 1.5.3b when you click to see the details page (listingDetails.js)

I have tired this on Windows and a Mac from fresh install no changes

The config is you default config, I have not made any changes, I just wanted to make sure it was working first before I started to make changes.

![030fade8-0c18-4fdb-8fa0-ae8ed18e1eae](https://user-images.githubusercontent.com/11790536/49590547-163de100-f964-11e8-9fc5-d6355b5c8c2b.jpg)

**Comment by menzer2015** [comment]
After trying to identify the issue, I found that by commenting out  isMyListing={this.isMyListing the page seems to work ok but I would like to know what issues I may have by commenting out this line, thanks. Also I am not sure this is a bug?

` <DetailFooter
                    {...this.props}
                    author={post.author}
                    onChat={onChat}
              //    isMyListing={this.isMyListing}
                />`

**Comment by thangvo9x** [comment]
Hi @menzer2015 . Share your Config.js file to email thang@beostore.io 
please note your issue - such as your email. We'll check & reply to you soon.
Thanks
