### ISSUE TITLE
cebilder not working

### ISSUE THREAD

**Issue by keerthipativinaykumar** [inspireui/support#823]
![SharedScreenshot](https://user-images.githubusercontent.com/35635533/61760335-cb84b280-ade8-11e9-8949-f520868fc01f.jpg)

like showing in image which I have attached its the problem for me to get work in how can I do for it

**Comment by keerthipativinaykumar** [comment]
any solutions..?????

**Comment by keerthipativinaykumar** [comment]
install all button also not working ....!

**Comment by vumanhsn97** [comment]
Windows users must have WSL enabled. You can follow the installation guide here. We recommend picking Ubuntu from the Windows Store. Be sure to launch Ubuntu at least once. After that, use an Admin powershell to run: Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux

Then the powersell will be active. Let us know your checking

**Comment by keerthipativinaykumar** [comment]
How can i enable WSL enable please send me all the details

**Comment by minhcasi** [comment]
Hi @keerthipativinaykumar - could you help to check the latest 3.9.3 - thank you!

**Comment by keerthipativinaykumar** [comment]
yes minhcasi I will check it but my problem is for cebuilder its showing powershell not exists but is is there and i'm also using it as well install all button from cebuilder also not working what can I do for it

**Comment by reshiDeveloper** [comment]
How can I install mstore plugin?

**Comment by minhcasi** [comment]
@reshiDeveloper - please download it from - https://github.com/inspireui/mstore-checkout

@keerthipativinaykumar - please also try to install manually base on recent guide on https://docs.inspireui.com/listapp/getting-started/
