### ISSUE TITLE
[Mstore] - How to remove the starting three intro screen

### ISSUE THREAD

**Issue by santhoniral** [inspireui/support#824]
Issue : I want to remove the starting three intro screen.....when open the app straightly to home scree...

screen shot : 
![Screenshot_1](https://user-images.githubusercontent.com/32481586/61773108-78732580-ae11-11e9-9c80-975ea7b5c8c0.png)

**Comment by santhoniral** [comment]
I want to directly redirect to home page without AppIntro.

**Comment by minhcasi** [comment]
pls remove this code - https://tppr.me/jr0TC - thanks
