### ISSUE TITLE
[MStore] - MStore Checkout's Bug

### ISSUE THREAD

**Issue by Nippler** [inspireui/support#825]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue

Cannot activate mstore-checkout plugin on my site.

> Fatal error: Cannot redeclare class Mobile_Detect in /home/local/mysite.com/public_html/wp-content/themes/shore/highgrade/Mobile_Detect.php on line 26
> The site is experiencing technical difficulties. Please check your site admin email inbox for instructions.

2. Screenshots
[https://ibb.co/mhXkqgN](url)

3. My screenshot of the purchase product or my comment:

https://ibb.co/QQx5XzB
If you need purchase code, I will leave as a private comment 

3. Config files (optional)

**Comment by minhcasi** [comment]
verified purchased.

Could you try with this latest mstore-checkout plugin - https://github.com/inspireui/mstore-checkout

**Comment by Nippler** [comment]
Hi, tried that version, but still have the same error message.

> Fatal error: Cannot redeclare class Mobile_Detect in /home/condo/mysite.com/public_html/wp-content/themes/shore/highgrade/Mobile_Detect.php on line 26
> The site is experiencing technical difficulties. Please check your site admin email inbox for instructions.

**Comment by Ahmed-Shaheen2** [comment]
there is a problem in fluxstore (integrated with woocommerce) in login function …. seems like the mstore_user api plugin miss the get_currentuserinfo function which is used in login function also the end point this function login requests is wrong. It’s ”/api/auth/get_currentuserinfo” and i think it should be ”/api/mstore_user/get_currentuserinfo”. Please this issue is urgent … need a quick solution please.

**Comment by minhcasi** [comment]
@Ahmed-Shaheen2 - pls try to install plugin "JSON API Auth" and activate it from the setting - https://tppr.me/kC0QB

**Comment by Nippler** [comment]
so.. how about my issue?

**Comment by minhcasi** [comment]
@Nippler - insert this line https://tppr.me/ncbU7

to /home/condo/mysite.com/public_html/wp-content/themes/shore/highgrade/Mobile_Detect.php will fix the issue - it uses to check if the class already exist, this is week coding skill on your theme

**Comment by Nippler** [comment]
Please don't close the issue so fast

**Comment by Ahmed-Shaheen2** [comment]
thank you i have installed the plugin you mentioned above, the login issue has been solved now.
Please add this requirement plugin "Json Api Auth" in the setup section in documentation.
another issue has encountered in registeration function in the android app. it returns the error in the image
![5b7d54d7-aa5a-4509-9acc-4c46fd4c6d38](https://user-images.githubusercontent.com/40732680/61877434-4afca980-aeef-11e9-85cf-5c90b45f6cd2.jpeg)

**Comment by Nippler** [comment]
Mr. Ahmed,

Could you please submit your own issue? I don't want to receive notification anymore.
Please do not leave comment on this thread anymore.

**Comment by Ahmed-Shaheen2** [comment]
So sorry Mr @Nippler. Just I thought at the first that it's the same issue as mine.
I have already submitted a nother ticket yesterday.
So sorry a bout this inconvenience.
Please accept my apologies.
