### ISSUE TITLE
[ListApp] - Some Bugs on Android App

### ISSUE THREAD

**Issue by Nippler** [inspireui/support#826]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue

On Android App

- Map doesn't follow listing's pin location.
- App crashes when tapping Category tab (iOS ver doesn't crash.)

On Both App(Android and iOS)
- Related posts on a listing page are same at any listings.
- Cannot filter listings on "Recent" section on both Apps.
- Keep loading on Regions section on Filter
***Some listing's thumbnail is still blank for some reason***

2. Screenshots

[https://ibb.co/dQQ60Xx]
[https://ibb.co/kQHfQgX]
[https://ibb.co/THPNKcG]
[https://ibb.co/d2VWYBG]

3. My screenshot of the purchase product or my comment:

[https://ibb.co/dQQ60Xx]

3. Config files (optional)

**Comment by minhcasi** [comment]
noted for checking @Nippler 

Please also get this patching for comparing the change - https://www.dropbox.com/s/ycf6b7xkt0hxae7/listapp-patch-1.7.3.diff?dl=0
