### ISSUE TITLE
Babel issue - decorators-legacy isn't currently enabled.

### ISSUE THREAD

**Issue by PaperjetStudios** [inspireui/support#827]
Hey there,

So I got the thing, installed and tried to run it with yarn. I get this error:

SyntaxError: /Users/tammaryn/Desktop/RushTushApp/src/components/LeftMenu/MenuOverlay.js: Support for the experimental syntax 'decorators-legacy' isn't currently enabled (11:1):

   9 | import { Drawer } from "@components";
  10 | 
> 11 | @withTheme

I know this can probably easily be fixed with setting up babel correctly - any tips on how? I see there's no .babelrc file so I dunno.

**Comment by minhcasi** [comment]
1. pls share your purchase product screenshot with your Envato username

2. Let us know which the product?
