### ISSUE TITLE
[listapp] back and call button bugs in 1.7.3

### ISSUE THREAD

**Issue by reconshield** [inspireui/support#829]
When test in simulator i can see back and call button but not when run it in devices. I check default listapp source file and run it.. its show same .. pls advice

![01B4C2AE-23FC-439A-B0FB-98DA78F725A6](https://user-images.githubusercontent.com/25501496/61843825-c9e1ea00-aecf-11e9-93cf-d37da8e28412.jpeg)

**Comment by thangvo9x** [comment]
Maybe cache on the real device. Try delete app and reinstall. @reconshield

**Comment by reconshield** [comment]
I have publish in google play and doing testing on android devices. Its not cache issue.. i tried new device for 1st time. Its same

**Comment by thangvo9x** [comment]
We tested on real devices. Try to double-check on your app.
https://we.tl/t-Of5tkVwcSi
Thanks

**Comment by reconshield** [comment]
Thanks sir.. ok now

**Comment by reconshield** [comment]
yes..i check with few devices..cant view. ..i tried change icon ..its same .u can check my app at 

https://play.google.com/store/apps/details?id=com.recopugal.my

**Comment by thangvo9x** [comment]
https://github.com/inspireui/support/issues/846
