### ISSUE TITLE
[Listapp] - Bugs in Listapp 1.7.3

### ISSUE THREAD

**Issue by reconshield** [inspireui/support#832]
Thanks for new update.Awesome.
but i found this bugs..
when click Mylisting from User Profile panel . i get this error..pls advice
![Simulator Screen Shot - iPhone X - 2019-07-25 at 18 40 01](https://user-images.githubusercontent.com/25501496/61868414-e9970380-af0b-11e9-9237-4f321bacc075.png)

**Comment by thangvo9x** [comment]
Please check again. I tested. Its works normal.

https://we.tl/t-5gzMaA1uvD

**Comment by reconshield** [comment]
i just update to latest version 1.7.3 ..i get above error... can send me .js file for mylisting page ? let me try replace it..

**Comment by reconshield** [comment]
ok..i found solution
