### ISSUE TITLE
[my-product] - MSTORE-MV

### ISSUE THREAD

**Issue by axedigital** [inspireui/support#833]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------
My Purchased Code: 7312b864-6504-4d5a-b98f-d8f4fa6e88da

1. My issue :
When I click on a category I have an error message in red.
See screenshot
https://imgur.com/a/UBNk6Pg

2. Screenshots:

3. My screenshot of the purchase product or my comment:
https://imgur.com/TmSa6r2
https://imgur.com/s7omAas

3. Config files (optional):
attached

[AppConfig.zip](https://github.com/inspireui/support/files/3431160/AppConfig.zip)

--------------------------

**Comment by minhcasi** [comment]
Hi, thank you for reporting, our team will investigate your config and let you know - thank you!

@thangvo9x

**Comment by thangvo9x** [comment]
Try to replace this file at containers/Category/
remember that change from .txt -> .js
[index.txt](https://github.com/inspireui/support/files/3440107/index.txt)

Thanks

**Comment by axedigital** [comment]
I looked but the index file is already in .js

**Comment by thangvo9x** [comment]
> I looked but the index file is already in .js
> And also I use the WCFM plugin for sellers you told me that at the next update it will have to be compatible with MSTORE-MV but the sellers section still does not work

I mean, first, replace the file index and change from .txt ->.js
Thanks

**Comment by axedigital** [comment]
please take the trouble to read the messages before answering.
I tell you there is no index.txt file in my folder but rather index.js

**Comment by thangvo9x** [comment]
You've got me wrong, sir. I didn't mean to tell you looking for the "index.js" file. Of course, it already exists. 
All you need to do is deleting the old "index.js" file, downloading my "index.txt" file then replace .txt to .js tag (because Github doesn't allow uploading directly file in .js tag). Please try again then let me know if it works. 
Have a nice day!

**Comment by axedigital** [comment]
I did it I changed the file with the one you gave me but I still had this error
![Capture d'écrans_20190730-111144](https://user-images.githubusercontent.com/53220194/62121327-a948d400-b2c3-11e9-81d9-0c94d99ca071.png)

**Comment by thangvo9x** [comment]
Try to replace this file at containers/Category/
[ProductRow.txt](https://github.com/inspireui/support/files/3455529/ProductRow.txt)
Change from .txt -> .js 
Thanks

**Comment by axedigital** [comment]
Hello, thank you for your answerI changed the file and the categories work correctly.
Please, I have one last thing for my application to be fine.
How to make the vendors appear? this part does not follow I use the WCFM plugin which you already said to have made it compatible with the script since the last update.

**Comment by thangvo9x** [comment]
There is some problem with your website. 
https://www.princessofsamarkand.com/wp-json/wcfmmp/v1/store-vendors#.
You should check it.

**Comment by axedigital** [comment]
Thank you for your reply.
Please, I saw the link but I do not understand what you want me to check

**Comment by thangvo9x** [comment]
hi bro.
<img width="1187" alt="Screen Shot 2019-08-03 at 1 59 52 PM" src="https://user-images.githubusercontent.com/23457178/62408700-fb0c9980-b5f6-11e9-96ff-971031a17b06.png">
The error was displayed on your website. 
See attach image.

**Comment by axedigital** [comment]
Firstly, I do not understand the error, you want me to do what? The marketplace works well on the website.
I am not a web developer like you

**Comment by minhcasi** [comment]
@axedigital - it seems there is an issue of the Rest API from this plugin https://ms.wordpress.org/plugins/wcfm-marketplace-rest-api/ - it could cause by some missing config from the website, as this is from the website problem we could not check from our side.

You can ask your developer to check, the correct return JSON will look like this example: http://wclovers.mstore.io/wp-json/wcfmmp/v1/store-vendors

**Comment by axedigital** [comment]
hi bro,
I just installed the plugin https://ms.wordpress.org/plugins/wcfm-marketplace-rest-api/
I do not know if there are any configurations to do. Stp can you look for me? it's just what I need for my app to be OK. it's been 3 weeks that I galley on it.
I am webmaster I master wordpress I made the site myself and I have no developer.
Here are the accesses of the site

URL: https://www.princessofsamarkand.com/wp-admin
username: admin
password: Morelmoneymaker @

**Comment by axedigital** [comment]
Is that kind of nastiness? I bought your script and I only had problems. You are not even fooled to answer me already a week ago. reply to my fucking ticket

**Comment by minhcasi** [comment]
@axedigital - just clarify that you have messed up your site and the Rest API support for this API does not work, check this link - https://www.princessofsamarkand.com/wp-json/wcfmmp/v1/store-vendors

The correct return json api will be liked this one - http://wclovers.mstore.io/wp-json/wcfmmp/v1/store-vendors

Try to check from your side as the 'master wordpress', If you could not use the app we could process the refund for you - thanks

**Comment by axedigital** [comment]
First of all I have the impression that you do not understand me well. I apologize for my English as I said I am French. Am using google tanslate to speak with you
I am not an expert wordpress, I will tell you I am a little wordpress.
Please, can you look at the error so that it returns the right values? I have no idea what it is.

The accesses of my site are
URL: https://www.princessofsamarkand.com/wp-admin
username: admin
password: Morelmoneymaker @
Yours truly

**Comment by axedigital** [comment]
It's OK for the plugin
https://www.princessofsamarkand.com/wp-json/wcfmmp/v1/store-vendors

**Comment by axedigital** [comment]
I contacted the support of WCFM and they solved the problem with the plugin as you can see on:
https://www.princessofsamarkand.com/wp-json/wcfmmp/v1/store-vendors

Please, I have a problem: Vendors are still not displayed in the app. See the screenshot.
and on the other hand, there is an error when I click on the tab "vendor" from a product.

**Comment by axedigital** [comment]
Please one last thing too. Translation does not work in my application

**Comment by thangvo9x** [comment]
Try to replace the content of this file.
[AppConfig.txt](https://github.com/inspireui/support/files/3508438/AppConfig.txt)

**Comment by axedigital** [comment]
Please I replaced it did not work. Same mistake on the vendors.
