### ISSUE TITLE
[ListApp] -  how to update lastest app targets API level ?

### ISSUE THREAD

**Issue by Pavithran10** [inspireui/support#834]
1. My issue
        hi, We submitting the apk file in the play store it shows some warnings. Its need to update latest app target API level now current version is too old then its need to change latest API level. Are you update this API level target in latest listapp product.
thanks.

2. Screenshots
![app_update](https://user-images.githubusercontent.com/46148046/61869729-fb6fab00-aef9-11e9-9b74-54522106b9db.PNG)

**Comment by minhcasi** [comment]
pls try with latest Listapp that support Expo 33 for fixing this target API - thanks
