### ISSUE TITLE
[MStore] - 

### ISSUE THREAD

**Issue by Nippler** [inspireui/support#835]
Now I got a new issue thanks to your advice :)
https://github.com/inspireui/support/issues/825#issuecomment-515003918

Please don't close the issue before I update.

> Parse error: syntax error, unexpected end of file in /home/condo/legomanila.com/public_html/wp-content/themes/shore/highgrade/Mobile_Detect.php on line 1218
> The site is experiencing technical difficulties. Please check your site admin email inbox for instructions.

**Comment by minhcasi** [comment]
add the "}" on end of the file
