### ISSUE TITLE
[msstore] - URL Not found in "pay" step and no "PayPal Checkout" icon

### ISSUE THREAD

**Issue by karlolopez** [inspireui/support#838]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue

Hi, I have two issues going on over "Pay" step. First I don't know how to add PayPal Checkout image to be displayed, and secondly when I hit "Next" in order to process payment, it opens a web view with the Wordpress site but with error on URL. See screenshots. Thanks.

2. Screenshots

![1](https://user-images.githubusercontent.com/12940686/61985279-1a3f7180-afce-11e9-9966-59772de6481a.jpeg)
![2](https://user-images.githubusercontent.com/12940686/61985280-1c093500-afce-11e9-871e-8c5e6d4ff933.jpeg)

3. My screenshot of the purchase product or my comment:

3. Config files (optional)

**Comment by minhcasi** [comment]
Hi, please help to check this solution to fix the 404 error issue when processing the checkout  - https://docs.inspireui.com/mstore/questions/#404-error-page-when-process-the-payment- 

Thank you!
