### ISSUE TITLE
[CeBuilder] - Packager is not running at http://192.168.1.4:19001

### ISSUE THREAD

**Issue by envatonly** [inspireui/support#839]
Hello team,

I'm trying to run the APP with the CEBUILDER and this error comes up. 

Thank you

**Comment by minhcasi** [comment]
Hi, please help to check with latest 3.9.3 - thank you!

**Comment by minhcasi** [comment]
Hi, could you help to take the screenshot issue, we have double check and could not find the issue, could you also let us know which the OS that you have tried 

Sorry for late response as we missed this ticket - thank you!

**Comment by reshiDeveloper** [comment]
How can I install mstore plugin?

**Comment by minhcasi** [comment]
Hi @reshiDeveloper - there is a link from the download - https://docs.inspireui.com/mstore/wordpress-setting/ - thanks
