### ISSUE TITLE
[LISTAPP 1.7.3] - Custom Taxonomies & Listing Type from MyListing

### ISSUE THREAD

**Issue by envatonly** [inspireui/support#840]
Hello team,

On the APP I can see only category related things. In my project using MyListing, I don't have categories but only CUSTOM TAXONOMIES. How to get rid of all the Category related things and replace them with Taxonomies? 

In addition to that How to add the Listing Types? (Bar, Shops, Gyms etc...)

What info do you need to provide in order to make the APP works as smooth as possible?

Thank you :)

**Comment by thangvo9x** [comment]
To work with them. You must change at services/WPAPI.js 
Thanks.
