### ISSUE TITLE
[ListApp] - Cannot open a listing page

### ISSUE THREAD

**Issue by Nippler** [inspireui/support#841]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue

Since I updated to the latest ver. I cannot open any listing page on Android.
(I tested on iOS ver. via expo, which works well, though)

2. Screenshots

`Invariant Violation: [11319,"RCTImageView",1,{"source":[{"uri":"https://mysite.com/wp-content/uploads/2019/07/画像-medium.jpg"}],"width":394,"height":"<<NaN>>","overflow":"hidden","marginTop":10,"marginBottom":10,"resizeMode":"contain"}] is not usable as a native method argument

This error is located at:
    in RCTImageView (at Image.ios.js:115)
    in Image (at WebView/index.js:63)
    in RCTView (at View.js:45)
    in View (at HTML.js:521)
    in HTML (at WebView/index.js:91)
    in Index (at ListingData/index.js:31)
    in RCTView (at View.js:45)
    in View (at ListingData/index.js:26)
    in RCTView (at View.js:45)
    in View (at ListingData/index.js:227)
    in ListingData (at ListingDetail.js:258)
    in RCTView (at View.js:45)
    in View (at ListingDetail.js:153)
    in RCTScrollContentView (at ScrollView.js:976)
    in RCTScrollView (at ScrollView.js:1115)
    in ScrollView (at createAnimatedComponent.js:151)
    in AnimatedComponent (at ListingDetail.js:276)
    in RCTView (at View.js:45)
    in View (at ListingDetail.js:275)
    in ListingDetail (created by ConnectFunction)
    in ConnectFunction (at PostDetail/index.js:69)
    in RCTView (at View.js:45)
    in View (at PostDetail/index.js:112)
    in Index (created by ConnectFunction)
    in ConnectFunction (at PostDetailScreen.js:40)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at react-native-safe-area-view/index.js:164)
    in SafeView (at withOrientation.js:54)
    in withOrientation (at PostDetailScreen.js:39)
    in PostDetailScreen (created by ConnectFunction)
    in ConnectFunction (at SceneView.js:9)
    in SceneView (at createTabNavigator.js:39)
    in RCTView (at View.js:45)
    in View (at ResourceSavingScene.js:37)
    in RCTView (at View.js:45)
    in View (at ResourceSavingScene.js:26)
    in ResourceSavingScene (at createBottomTabNavigator.js:121)
    in RCTView (at View.js:45)
    in View (at screens.native.js:83)
    in ScreenContainer (at createBottomTabNavigator.js:111)
    in RCTView (at View.js:45)
    in View (at createBottomTabNavigator.js:110)
    in TabNavigationView (at createTabNavigator.js:197)
    in NavigationView (at createNavigator.js:61)
    in Navigator (at createAppContainer.js:429)
    in NavigationContainer (at RootRouter.js:80)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at react-native-drawer/index.js:632)
    in RCTView (at View.js:45)
    in View (at react-native-drawer/index.js:619)
    in Drawer (at MenuOverlay.js:39)
    in MenuOverlay (created by ConnectFunction)
    in ConnectFunction (at RootRouter.js:93)
    in RCTView (at View.js:45)
    in View (at RootRouter.js:105)
    in RootRouter (created by ConnectFunction)
    in ConnectFunction (at App.js:167)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at react-native-safe-area-view/index.js:164)
    in SafeView (at withOrientation.js:54)
    in withOrientation (at App.js:164)
    in Provider (at App.js:163)
    in App (at withExpoRoot.js:20)
    in RootErrorBoundary (at withExpoRoot.js:19)
    in ExpoRootComponent (at renderApplication.js:35)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:98)
    in RCTView (at View.js:45)
    in View (at react-native-root-siblings/index.js:34)
    in RootSiblingsWrapper (at AppContainer.js:112)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:115)
    in AppContainer (at renderApplication.js:34)

enqueueNativeCall
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:3023:20
fn
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:2657:40
createInstance
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:11403:29
completeWork
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:18499:48
completeUnitOfWork
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:20658:44
performUnitOfWork
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:20821:36
workLoop
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:20831:47
renderRoot
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:20897:21
performWorkOnRoot
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:21635:23
performWork
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:21562:30
performSyncWork
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:21538:20
requestWork
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:21436:26
scheduleWork
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:21309:22
enqueueSetState
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:13562:23
setState
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:4985:37
componentWillMount$
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:289928:30
tryCatch
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:23488:23
invoke
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:23663:32
tryCatch
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:23488:23
invoke
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:23564:30
<unknown>
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:23574:21
tryCallOne
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:24780:16
<unknown>
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:24881:27
_callTimer
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:28163:17
_callImmediatesPass
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:28199:19
callImmediates
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:28418:33
__callImmediates
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:3093:35
<unknown>
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:2914:34
__guard
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:3076:15
flushedQueue
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:2913:21`

3. My screenshot of the purchase product or my comment:

[https://ibb.co/dQQ60Xx]

4. Config files (optional)

**Comment by thangvo9x** [comment]
Hi. could you share AppConfig file?

**Comment by Nippler** [comment]
HI,
I will Email AppConfig to hi@inspireui.com

Also, would you tell me how to fix this?
[https://ibb.co/FV6hCg5](url)

**Comment by thangvo9x** [comment]
Hi bro. Maybe the problem is coming from the image wasn't got

**Comment by Nippler** [comment]
>the image wasn't got

sorry, what do you mean?

Also, how can I fix this issue?
https://ibb.co/FV6hCg5

**Comment by thangvo9x** [comment]
I mean. Maybe the image of listing wasn't set.
That was just only a warning for APK file.  You could refer here
https://developer.android.com/topic/performance/reduce-apk-size
Thanks

**Comment by Nippler** [comment]
Is it mandatory?
Or
Do I have to follow the steps to publish app?

**Comment by thangvo9x** [comment]
No. it isn't.
I checked on your config. The issue went from the content of the listing.
Content of each listing has value invalid.

**Comment by Nippler** [comment]
Thank you,
What kinds of data are invalid?

**Comment by thangvo9x** [comment]
The content in your listings has some text/image error.
