### ISSUE TITLE
CEBuilder for MStore (woocommerce - dokan)

### ISSUE THREAD

**Issue by karanzen** [inspireui/support#842]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: Expo is not working on CEbuilder. On clicking on Install Tools also, not is actually happening. The customization tool is showing up, but on clicking on "+", to add new block. A blank screen is showing up with no options. 

2. Screenshots: https://prnt.sc/okp30t

3. My screenshot of the purchase product or my comment:I have authorized my purchase in CEBuilder. You can see in the screenshot. Therefore, I hope this is enough to authenticate my purchase.

3. Config files (optional)

**Comment by minhcasi** [comment]
Hi, sorry for lated response - could you help to install the expo via terminal with this script:

npm install expo-cli -g 

Then restart the cebuilder again to see if can be fixed - thank you!
