### ISSUE TITLE
[Listapp] - 1.7.3 category issue

### ISSUE THREAD

**Issue by reconshield** [inspireui/support#843]
when press category .. its not display that category list..i can see all listing... 
this was working fine in previous version..

**Comment by thangvo9x** [comment]
Could you share your AppConfig.json file. Thanks

**Comment by reconshield** [comment]
[AppConfig.txt](https://github.com/inspireui/support/files/3439059/AppConfig.txt)

**Comment by thangvo9x** [comment]
I saw your issue. two ways to fix them
1. You could update to the latest of theme myListing
2. you could update at redux/PostActions.js and find this function and remove this block IF, just only hold one.
https://prnt.sc/ola6y9
Thanks

**Comment by reconshield** [comment]
ok..thanks :)
