### ISSUE TITLE
[listapp] 1.7.3 bugs after publish to google play

### ISSUE THREAD

**Issue by reconshield** [inspireui/support#846]
after publish app in google play store i get this error. When click location map page. Working fine in simulator

![0EB692F9-0804-481D-A959-7A2BE72F86A3](https://user-images.githubusercontent.com/25501496/61994556-682ba680-b0ae-11e9-8cdd-774b5ce11eda.jpeg)

**Comment by thangvo9x** [comment]
You could refer here 
https://github.com/react-native-community/react-native-maps/blob/master/docs/installation.md
scroll to the section for android
Thanks

**Comment by reconshield** [comment]
i tried add API key to manifest file (android/app/src/main/AndroidManifest.xml)

its looks same. can help me with this? or better use old Listapp version?

**Comment by thangvo9x** [comment]
Such error was displayed on your app. You have just followed steps as the above link.

**Comment by theAlinux** [comment]
//app.json

```
"android": {
      "package": "com.best.restaurants.uk.gb",
      "versionCode": 6,
      "googleServicesFile": "./release/google-services.json",

       //added this line for error fixes and fixed
      "config": { "googleMaps": { "apiKey": "AIzaSyCHLHnlbp**********************" } }
    }
```
