### ISSUE TITLE
[Mstore] - Product Order in homepage new to old 

### ISSUE THREAD

**Issue by ataiwo473** [inspireui/support#847]
1. My issue
I having issue in getting my products to display in the order i want which is newest item to oldest item and i have check the _Constants.js_ to change it and still doest work any help will be appreciated

2. Screenshots
<img width="595" alt="Screen Shot 2019-07-27 at 1 45 09 PM" src="https://user-images.githubusercontent.com/17734413/61997856-d86a0600-b075-11e9-9731-e275fba755cc.png">

3. My screenshot of the purchase product or my comment:
<img width="1677" alt="Screen Shot 2019-07-27 at 1 47 21 PM" src="https://user-images.githubusercontent.com/17734413/61997841-ba040a80-b075-11e9-9390-35de116f2d14.png">
<img width="654" alt="Screen Shot 2019-07-27 at 1 48 59 PM" src="https://user-images.githubusercontent.com/17734413/61997845-c12b1880-b075-11e9-9d68-9a5b1ec6d983.png">

3. Config files (optional)
[common.zip](https://github.com/inspireui/support/files/3438450/common.zip)

**Comment by minhcasi** [comment]
Hi sorry for late response as i was at the holiday yesterday - could you help to share the screens of the wrong ordering, is it from the homepage or the category page? Thank you!

**Comment by ataiwo473** [comment]
Homepage order
<img width="418" alt="Screen Shot 2019-07-30 at 11 38 16 AM" src="https://user-images.githubusercontent.com/17734413/62143860-cfb84080-b2be-11e9-9428-0a6980332a5a.png">
that is the oldest 
we want it to show newest

**Comment by ataiwo473** [comment]
that the file
https://github.com/inspireui/support/files/3438450/common.zip

**Comment by minhcasi** [comment]
Thank you @ataiwo473 

 @concuacon - please help to check this order issue

**Comment by ataiwo473** [comment]
Please can I know the update on this issues

**Comment by minhcasi** [comment]
@ataiwo473 - please help to share your email here so that we could send the patching for your site - thank you!

@concuacon

**Comment by ataiwo473** [comment]
ataiwo473@gmail.com

**Comment by minhcasi** [comment]
HI @ataiwo473 - sorry for missing your idea here, we have fixed the issue by upgrade the api-commerce library.

Please help to change the package.json: api-ecommerce: 0.0.30

This will fix the issue, make sure your delete the node_module and install again, let us know your checking - thank you!

**Comment by concuacon** [comment]
@ataiwo473 
i fixed it, send u the patching of common folder
<img width="1327" alt="Screen Shot 2019-08-07 at 7 22 48 PM" src="https://user-images.githubusercontent.com/11958061/62622635-02120f80-b949-11e9-99bc-a76a015608a4.png">
<img width="293" alt="Screen Shot 2019-08-07 at 7 23 17 PM" src="https://user-images.githubusercontent.com/11958061/62622628-ff171f00-b948-11e9-9977-c7641c184210.png">
[common.zip](https://github.com/inspireui/support/files/3476943/common.zip)

**Comment by ataiwo473** [comment]
where do i modify that file?

**Comment by ataiwo473** [comment]
where do i modify that file?. i added the file u just sent and there was no
changes and i cant even find the "api-ecommerce": "^0.0.30", in any of the
files
