### ISSUE TITLE
MStore Pro - OAuth parameter in real device.

### ISSUE THREAD

**Issue by BhawinGothadiya** [inspireui/support#849]
Item Purchase Code:
5f83b448-2779-4787-aff7-338aa7a3da14

I have sent mail to you but no response since 4 days.

We also react native developer but, we can't config. your MStore product. Seriously, We have wasted 14+ days for setup this app only.

The app is run well in the emulator but in a real device, it's through OAuth error. Please check below screenshot.

![image](https://user-images.githubusercontent.com/4207794/62026172-e051b380-b1f7-11e9-9505-0cb1d8ff66cf.png)

**Comment by minhcasi** [comment]
Thank you for the detail, we will have a check and let you know.

Could you help to attache your new config file as well?  Please note that if your config to your local virtual website, make sure it can be reached from the device, otherwise it will display as the screenshot issue

**Comment by BhawinGothadiya** [comment]
That issue we have solved.

Now, We are facing another issue.

I can't generate an iOS app. I have used the latest version of code.

![image](https://user-images.githubusercontent.com/4207794/62595221-29da8680-b8fb-11e9-9886-8adde0856419.png)

**Comment by minhcasi** [comment]
Hi, you can try to check this option - https://tppr.me/4dD6C

**Comment by BhawinGothadiya** [comment]
Everything is fine now, only orders are not going through. 

Please check out below detail for more details on the issue. Also, it is not allowing to debug it, due to some the console issue.

Let me know if you need anything.


**First Scenario =>**
 1.MStore original code (mstore-pro)
2. After project setup, App is working with
 {
 "url": "https://mstore.io",
 "consumerKey": "ck_b7594bc4391db4b56c635fe6da1072a53ca4535a",
 "consumerSecret": "cs_980b9edb120e15bd2a8b668cacc734f7eca0ba40"
 }

3. Items added in the cart and login with SMS login, order was successful. All is working fine.
Second Scenario => Changes in project
 1. I find & replaced Project details in mstore-pro app folder with given details
 {
 "url": "jdtraders.in",
 "consumerKey": "ck_7a5389ea4fa7b005cac182b91e0895745aa2b625",
 "consumerSecret": "cs_7fb154e4384024378323cff4b42e11597341614f"
 }
 2. After creating it’s build, I can make changes in the product details. I tried by the changing a
products name and it reflects successfully. I guess woocommerce api’s are working.
3. Added product in cart and Login with SMS LOGIN and select India from countries list and phone
verified successful.
 
 4. Delivery Screen
![image](https://user-images.githubusercontent.com/4207794/62626693-91b5bf00-b945-11e9-8fe6-3c80bb0b1dd3.png)

 5. Payment Screen 
 Select Cash On Delivery and click on [Confirm Order] button
 Button showing [LOADING] for few seconds after that next screen do not appear, it stays on the
same page.

![image](https://user-images.githubusercontent.com/4207794/62626738-abef9d00-b945-11e9-8ce3-ece8c539613d.png)

![image](https://user-images.githubusercontent.com/4207794/62627001-2d472f80-b946-11e9-8172-d03260ba4787.png)
 
Confirm Order button text changes into Loading and then nothing happens. Text replaced by Confirm

Order and stays on the same page.

**Comment by minhcasi** [comment]
Hi, pls check this solution as it could be related - https://docs.inspireui.com/mstore/questions/#404-error-page-when-process-the-payment- - than you!
