### ISSUE TITLE
mstore multivendor how to setup onesignal

### ISSUE THREAD

**Issue by alaradi2006** [inspireui/support#85]
**Mandatory Info (please complete the following information):**
 - Product: [e.g. MStore, ListApp]
 - Your Purchased Code: [get from https://codecanyon.net/downloads]
(we may not reply if you are not our customer)

**Describe the issues**
how to setup onesignal push notification for mstore multivendor 
the doc it shows for mstore in android files
for mstore multivendor theres no android file 

**Screenshots**

**Additional context**
Add any other detail logs about the problem here.

**Comment by minhcasi** [comment]
Hi, you can follow this guide to eject/detach the expo project - https://blog.expo.io/expokit-might-not-be-so-scary-3c26769215fa

Then install this lib for onesignal - https://github.com/geektimecoil/react-native-onesignal
