### ISSUE TITLE
mstore

### ISSUE THREAD

**Issue by dougcodes** [inspireui/support#850]
Cannot compile for ios

HI,

I'm trying to compile the app for ios.

After I type react-native run-ios

I get the following error:

../x86_64/FBSDKAppEventsUtility.o FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/AppEvents/Internal/FBSDKAppEventsUtility.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

    at ChildProcess.buildProcess.on.code (/Users/username/Dropbox/Doug/Projects/kc-mobile/downloads/mstore-3.9.2/mstore-pro/node_modules/@react-native-community/cli/build/commands/runIOS/runIOS.js:231:16)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)

System info:

react-native info
info 
  React Native Environment Info:
    System:
      OS: macOS Sierra 10.12.6
      CPU: (4) x64 Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz
      Memory: 21.47 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.0 - /usr/local/opt/node@10/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/opt/node@10/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.2, macOS 10.13, tvOS 11.2, watchOS 4.2
      Android SDK:
        API Levels: 28, 29
        Build Tools: 28.0.3, 29.0.1
        System Images: android-29 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 9.2/9C40b - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.8 => 0.59.8 
    npmGlobalPackages:
      react-native-cli: 2.0.1

Print Screen:

![fb-problem](https://user-images.githubusercontent.com/3991248/62057320-a7f0ac00-b1dc-11e9-9d5b-cf209fbab912.png)

![fb-not-working](https://user-images.githubusercontent.com/3991248/62087182-1c980a80-b21e-11e9-96fc-1ddfc792a4be.png)

**Comment by dougcodes** [comment]
Followed steps here: https://github.com/inspireui/support/issues/800

Getting same as other person:

NAccountKitAdvancedUIManager.h:1:9: fatal error: 'AccountKit/AccountKit.h' file not found
#import <AccountKit/AccountKit.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~


error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening mstore.xcworkspace

2019-07-29 19:30:27.470 xcodebuild[9032:11575115] NOTE: Referenced project BVLinearGradient was written by a newer Xcode version (50) -- temporarily downgrading it (without modifying project file)
** BUILD FAILED **
he following commands produced analyzer issues:
	Analyze Base/RCTModuleMethod.mm
	Analyze Modules/RCTUIManager.m
(2 commands with analyzer issues)

**Comment by minhcasi** [comment]
noted, we will double-check and let you know - thank you!

**Comment by dougcodes** [comment]
@minhcasi - I tried this too:

Run: rm -rf node_modules/ && yarn cache clean && yarn && cd ios/ && rm -rf Pods/ && rm -rf Podfile.lock && pod install && cd .../ && yarn start --reset-cache (if you use yarn)

Run: rm -rf node_modules/ && npm cache clean && npm i && cd ios/ && rm -rf Pods/ && rm -rf Podfile.lock && pod install && cd .../ && react-native start --reset-cache (if you use npm)

Still not able to get it compiled:

RNAccountKitAdvancedUIManager.h:1:9: fatal error: 'AccountKit/AccountKit.h' file not found
#import <AccountKit/AccountKit.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~


error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening mstore.xcworkspace

2019-07-29 20:04:06.738 xcodebuild[19411:11686941] NOTE: Referenced project BVLinearGradient was written by a newer Xcode version (50) -- temporarily downgrading it (without modifying project file)
** BUILD FAILED **


The following commands produced analyzer issues:
	Analyze Base/RCTModuleMethod.mm
	Analyze Modules/RCTUIManager.m
(2 commands with analyzer issues)

The following build commands failed:
	CompileC /Users/blahblahblah/Dropbox/Blah/Projects/kc-mobile/mstore-3.9.2/mstore-pro/ios/build/mstore/Build/Intermediates.noindex/RNAccountKit.build/Debug-iphonesimulator/RNAccountKit.build/Objects-normal/x86_64/RNAccountKitAdvancedUIManager.o RNAccountKitAdvancedUIManager.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

**Comment by minhcasi** [comment]
Thank you, note - @concuacon

**Comment by dougcodes** [comment]
Can you send me new zip file with recommendation to fix this?

**Comment by minhcasi** [comment]
Hi @dougcodes  - we are going to update the new 3.9.3 with latest RN 0.60 to fix this issue - please help to download and let us know your checking - thank you!

**Comment by dougcodes** [comment]
@minhcasi  - I got it to work.  I had to upgrade xcode to version 10 and modify the podfile to use version 4.42 for facebook dependencies.

One other question, while going through the code, I'm not able to do "console.log()", is there something I need to do to get that to work?
