### ISSUE TITLE
[flux-store] - pagination error magento

### ISSUE THREAD

**Issue by agomaa** [inspireui/support#851]
When reached to end of product list page loading the same products again and append to the end of exiting list

**Comment by minhtruong315** [comment]
Hi @agomaa I will fix it in next release

**Comment by agomaa** [comment]
Could you send temporary fix , 
I could not wait till next relase

**Comment by minhcasi** [comment]
resolved

**Comment by Girg-Z** [comment]
Hi @minhcasi i have the same problem, how did you fix it?
