### ISSUE TITLE
#764

### ISSUE THREAD

**Issue by Blubagoo** [inspireui/support#852]
Please refer to issue 764 which was closed prematurely. The zipped file you sent back does not work. It's the exact same error.

**Comment by minhcasi** [comment]
Related to #764 

@Blubagoo - could you take the new screenshot of the issue please?

**Comment by minhcasi** [comment]
Hi @Blubagoo - please check the latest 3.9.3 to fix this issue - thank you!

**Comment by Blubagoo** [comment]
Hey how do i change the safe area background color? Shouldnt this be included in app we purchased?

**Comment by Blubagoo** [comment]
Also we have this issue where on ipad it is showing html tags

https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/68/c1/61/68c1618f-0b17-a839-1cf0-ad2395b3866a/pr_source.png/0x0ss.jpg

**Comment by minhcasi** [comment]
Hi, please try to wrap the description with the Tools.getDescription to remove the html charactor
