### ISSUE TITLE
MStore Pro - First build Failed AccountKit error

### ISSUE THREAD

**Issue by jakks-team** [inspireui/support#853]
1. My issue
I am unable to run the project I downloaded from Envato Market. I tried running with CeBuilder, but I'm getting RNAccountKitModule error as shown in screenshot below. I believe this is not your code's problem, but dependency problem. But can I get a solution on how to fix this?
Do I need to change anything at all to run the project for the first time?

2. Screenshots
![Screenshot_1](https://user-images.githubusercontent.com/47200595/62100693-efe70000-b2bc-11e9-97e9-9c94c10c686a.png)

3. My screenshot of the purchase product or my comment:
![purchase](https://user-images.githubusercontent.com/47200595/62100728-0b520b00-b2bd-11e9-990b-8583ffccc461.png)
![purchase code](https://user-images.githubusercontent.com/47200595/62100803-4f451000-b2bd-11e9-8506-3a6c1041ef72.png)

**Comment by minhcasi** [comment]
noted with checking - thank you!

@vumanhsn97

**Comment by jakks-team** [comment]
A rough hack that I did to fix the project at least running is :

1. open package.json and change the line "react-native-facebook-account-kit" version from 
`"react-native-facebook-account-kit": "^1.1.0",`
to
`"react-native-facebook-account-kit": "1.1.0",`
2. Then turns out I got another error
> Execution failed for task ':react-native-onesignal:mergeDebugJniLibFolders'.
> &gt; Failed to create directory 'D:\WooComm\mstore-pro\node_modules\react-native-onesignal\android\build\intermediates\incremental\mergeDebugJniLibFolders'

So, I run
`cd android && ./gradlew clean && cd .. && react-native run-android`

That **temporarily** fixed my problem and have the apps **at least** running. And I haven't even change anything yet.

**Comment by sackmotion** [comment]
I faced same issue and fixed following comments from : 

[link to similar issue](https://github.com/underscopeio/react-native-facebook-account-kit/issues/195)


**diff in latest version 3.92 is** : 

* **android/build.gradle**

```
diff --git a/android/build.gradle b/android/build.gradle
index 9869af19..7be498fe 100644
--- a/android/build.gradle
+++ b/android/build.gradle
@@ -9,6 +9,7 @@ buildscript {
         compileSdkVersion = 28
         targetSdkVersion = 28
         supportLibVersion = "28.0.0"
+        accountKitSdkVersion = "5.0.0"
     }
     repositories {
```

* **android/app/build.gradle**

```
diff --git a/android/app/build.gradle b/android/app/build.gradle
index 9babfac5..8c755214 100644
--- a/android/app/build.gradle
+++ b/android/app/build.gradle
@@ -178,7 +178,10 @@ dependencies {
     implementation project(':react-native-fbsdk')
     implementation project(':react-native-admob')
 
-    implementation 'com.facebook.android:facebook-android-sdk:[4,5)'
+    //implementation 'com.facebook.android:facebook-android-sdk:[4,5)'
+    // Fix
+    implementation 'com.facebook.android:account-kit-sdk:5.0.0'
+
     implementation 'com.android.support:design:27.1.0'
     implementation fileTree(dir: "libs", include: ["*.jar"])
     implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
```


Then i ran : 

`	 
cd android/ &&
./gradlew cleanBuildCache &&
./gradlew clean &&
cd .. &&
react-native run-android 
`

_Hope that helps , running here without side effects yet._

**Comment by minhcasi** [comment]
Hi, please try with latest 3.9.3 that compatible with latest React native 0.60, it's also fixed this issue - thank you!
