### ISSUE TITLE
Listpro - categories on homepage and archive shows &amp instead of &.

### ISSUE THREAD

**Issue by macbethm** [inspireui/support#854]
Hi

My Listpro does not decode the &amp, homepage and archive shows &amp instead of &. Please help

![category home (2)](https://user-images.githubusercontent.com/53470387/62118704-d21e9880-b2c6-11e9-8d90-8c59ff56d02f.jpg)
![Category home](https://user-images.githubusercontent.com/53470387/62118706-d2b72f00-b2c6-11e9-810b-6b0b6a2f3def.jpg)
![Product purchased](https://user-images.githubusercontent.com/53470387/62118707-d34fc580-b2c6-11e9-9d67-416be6edb681.jpg)

**Comment by minhcasi** [comment]
Hi, please help to wrap with Tools.getDescription - thank you

@thangvo9x  - note for the upgrade on next release

**Comment by macbethm** [comment]
Where should i put this code, please tell me in which file exactly and line

**Comment by thangvo9x** [comment]
go to Components/PostLayout/Column/index.js
find this block {Tools.getCategory(post.categories)} => 
{Tools.getCategory(Tools.formatText(post.categories))}
Try it now and let me know if it works.

**Comment by macbethm** [comment]
Same issue, I did not work

**Comment by thangvo9x** [comment]
Try to replace this file at containers/Home/CategoryLinks/
[Item.txt](https://github.com/inspireui/support/files/3454628/Item.txt)
Remember that change from .txt -> .js
Thanks

**Comment by macbethm** [comment]
I removed ('&amp') and put {lable}, On categorylinks issue is fixed but I still have same problem on RECENT EXPERIENCE listings, where should I edit and how

**Comment by thangvo9x** [comment]
Go to Common folder and replace this file Tools.js
[Tools.txt](https://github.com/inspireui/support/files/3460012/Tools.txt)
change .txt -> .js
Thanks

**Comment by macbethm** [comment]
Thanks alot it works. is there a way to show paid listings, and locations like on website?
