### ISSUE TITLE
[Fluxstore Pro] - Search Address error

### ISSUE THREAD

**Issue by ihsanberahim** [inspireui/support#855]
![image](https://user-images.githubusercontent.com/1956846/62177094-42382780-b376-11e9-9be9-28d30ccb3c28.png)

Reproduce steps:

1. Add to cart product
2. checkout
3. click 'search address'
4. Search something in the text input

https://codecanyon.net/item/fluxstore-the-universal-woocommerce-magento-opencart-mobile-app-by-flutter-framework/24020929

**Comment by minhtruong315** [comment]
Fixed.

**Comment by minhcasi** [comment]
This will be released on 1.3.6 on next 1-2 days - thank you!

**Comment by ihsanberahim** [comment]
Thanks.
