### ISSUE TITLE
Mstore - Unknown controller 'mstore user' 

### ISSUE THREAD

**Issue by ahmedot** [inspireui/support#857]
Item Purchase Code:
2f517590-9c6c-44ff-8b9e-b734757be547
---------

1. Unknown controller 'mstore user' 

2. Screenshots
![Screenshot_20190731-112955_Expo](https://user-images.githubusercontent.com/50944424/62192661-0eb1c900-b387-11e9-8dcb-945ae8933072.jpg)

**Comment by minhcasi** [comment]
please follow this guide and active mstore-checkout plugin - https://docs.inspireui.com/mstore/wordpress-setting/ - thank you!

**Comment by ahmedot** [comment]
I have done this, but also problem stay.

**Comment by ahmedot** [comment]
my problem not solved!

**Comment by minhcasi** [comment]
Hi, could i check if you have activated this setting as well - https://tppr.me/qdYog ?
