### ISSUE TITLE
[beonews] - change color

### ISSUE THREAD

**Issue by ramyragab1** [inspireui/support#858]
purchase product code: 97f0836c-e11f-4c68-8295-862a7571a9ff

i use "layout": 3 as list 
and i want to set tow background color for list view 
as this img 
https://www.dropbox.com/s/zjrlrhec1s9rlv2/WhatsApp%20Image%202019-07-31%20at%2010.38.22%20PM.jpeg?dl=0

**Comment by ramyragab1** [comment]
@minhcasi  mate can you help me :)

**Comment by minhcasi** [comment]
Hi, please try with this file - https://tppr.me/XaCg

**Comment by ramyragab1** [comment]
thanks mate 
this comment help me 
but i need 
color in list one and another color in list tow 
all list news show to color 
first background news in gray color 
second background in white color 
see 
https://www.dropbox.com/s/zjrlrhec1s9rlv2/WhatsApp%20Image%202019-07-31%20at%2010.38.22%20PM.jpeg?dl=0

and i want to change time days ago  to data 
see this img 
https://tppr.me/TySq0

**Comment by minhcasi** [comment]
Hi, you can custom the index.js which is located on the same folder "List", you can also create new style for this kind of layout

**Comment by ramyragab1** [comment]
@minhcasi  thanks 
can you help me :)

**Comment by ramyragab1** [comment]
and i want to change time days ago to data
see this img
https://tppr.me/TySq0

**Comment by minhcasi** [comment]
Hi, there is some example on this guide - https://github.com/DSchau/react-native-timeago- we use this lib to generate the time ago 

There is new better lib that you can replace it -  https://github.com/catamphetamine/react-time-ago

**Comment by ramyragab1** [comment]
thanks 
but this  lib not allow to show date in format dd/mm/yyy

**Comment by minhcasi** [comment]
Hi, just use the moment for format if you don't like to use the ago library, pls check https://momentjs.com/docs/#/displaying/format/
