### ISSUE TITLE
[CeBuilder 35.0] - Add item crashing CeBuilder app on Customizing MStorePro

### ISSUE THREAD

**Issue by jakks-team** [inspireui/support#859]
1. My issue
Customizing Home Layout using CeBuilder crashed when adding new item using the "Add" button.

2. Screenshots
Video instead of screenshot zipped below.
[BugVideo.zip](https://github.com/inspireui/support/files/3454973/BugVideo.zip)

3. My screenshot of the purchase product or my comment:
Refer to my other report #853 

3. Config files (optional)
I'm not sure what config files is required. Please point me to which files need to be uploaded here.

**Comment by minhcasi** [comment]
noted with checking, thank you!

@minhtruong315

**Comment by minhtruong315** [comment]
Fixed

**Comment by jakks-team** [comment]
It still isn't fixed for me.
Still experiencing this issue.

**Comment by minhcasi** [comment]
@jakks-team  - please note it is fixed and ongoing to package for the release, we will update the link on this ticket - thank you!

**Comment by jakks-team** [comment]
> @jakks-team - please note it is fixed and ongoing to package for the release, we will update the link on this ticket - thank you!

So, this is going to be fixed on CeBuilder 0.36.0?
Because I can only see CeBuilder 0.35.0 available for download.

If this is going to be on 0.36.0, I'll wait for it to be available for download, and close the ticket later.

Thanks.
