### ISSUE TITLE
[MStore Pro] - Can't run android

### ISSUE THREAD

**Issue by nadavdrewe** [inspireui/support#86]
Hi,

I bought this template from codecanyon:

MStore Pro - Complete React Native template for e-commerce
--
Regular License
Purchase code: 85fb2bc3-cfee-47a7-80b1-e5e2eb2a92c0

It won't run properly. After I run yarn, then react-native run-android I get:
![capture](https://user-images.githubusercontent.com/1905903/49689527-3ca57d00-fb1a-11e8-9e07-34aa21886147.PNG)

these packages don't link properly in android studio either:

![capture1](https://user-images.githubusercontent.com/1905903/49689557-b2a9e400-fb1a-11e8-988c-bce3a0c9f335.PNG)

Why not? 

Can you fix plz!!!

Expo version also broken: 

![capture3](https://user-images.githubusercontent.com/1905903/49689589-29df7800-fb1b-11e8-8ca5-04921d3069f4.PNG)

**Comment by luyx2412** [comment]
HI @nadavdrewe With Pro version, please open Android studio to build your project. Because the android studio will auto fix some issues.
- Expo version, Can you clean your project and re-install again. https://gist.github.com/jarretmoses/c2e4786fd342b3444f3bc6beff32098d

Thanks
