### ISSUE TITLE
[fluxtstore Pro] - opencart problem

### ISSUE THREAD

**Issue by mohmmadmoatz** [inspireui/support#862]
Hello ! i use the app and setup config to open cart but category its display all and not display as main category and its sub category

(http://trendsoo.com/image/screenshot1.jpg)
http://trendsoo.com/image/screenshot2.jpg

i want to display like this : http://trendsoo.com/image/Screenshot_10.jpg

(Main Category should i press it and give me the subcategory)

3. My screenshot of the purchase product or my comment: 

http://trendsoo.com/image/Screenshot_9.jpg

3. Config files (optional)

config.dart :

import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:fstore/common/constants.dart';

const HomeIconsCategories = [
  {
    "category": 28,
    "image": "assets/icons/categories/ic_tshirt.png",
    "colors": ["#3CC2BF", "#3CC2BF"],
  },
  {
    "category": 57,
    "image": "assets/icons/categories/ic_dress.png",
    "colors": ["#3E6AB5", "#3E6AB5"],
  },
  {
    "category": 33,
    "image": "assets/icons/categories/ic_shorts.png",
    "colors": ["#53A2CC", "#53A2CC"],
  },
  {
    "category": 20,
    "image": "assets/icons/categories/ic_glasses.png",
    "colors": ["#53688A", "#53688A"],
  },
  {
    "category": 27,
    "image": "assets/icons/categories/ic_tie.png",
    "colors": ["#43506A", "#43506A"],
  },
];

/// option to show the home category as the images, instead of icons, for "imageCategory" layout type
const HomeImagesCategory = [
  {
    "category": 28,
  },
  {
    "category": 25,
  },
  {
    "category": 20,
  },
  {
    "image": "assets/images/hci_restaurant.jpg",
    "name": "Restaurants",
    "description": "Top-rated eats",
  },
  {
    "image": "assets/images/hci_adventures.jpg",
    "name": "Adventures",
    "description": "Multi-day trips",
  },
];

const CategoriesListLayout = kCategoriesLayout.subCategories;

const Payments = {
  "paypal": "assets/icons/payment/paypal.png",
  "stripe": "assets/icons/payment/stripe.png",
  "razorpay": "assets/icons/payment/razorpay.png",
};

const DefaultCurrency = {"symbol": "\$", "decimalDigits": 2};

/// if it is true, user should login before using the app
const bool IsRequiredLogin = false;

/// use to config the product image height for the product detail
/// height=(percent * width-screen)
/// isHero: support hero animate
const kProductDetail = {
  "height": 1.2,
  "marginTop": 100,
  "isHero": false,
};

/// The Google API Key to support Pick up the Address automatically
/// We recommend to generate both ios and android to restrict by bundle app id
/// The download package is remove these keys, please use your own key
const kGoogleAPIKey = {
  "android": "",
  "ios": ""
};

const ProductVariantLayout = {
  "color": "color",
  "size": "box",
  "height": "option",
};
/// if it is true, user should login before using the app

/// The Google API Key to support Pick up the Address automatically
/// We recommend to generate both ios and android to restrict by bundle app id
/// The download package is remove these keys, please use your own key

const admob_id = "ca-app-pub-3940256099942544~3347511713";

/// use to config the product image height for the product detail
/// height=(percent * width-screen)
/// isHero: support hero animate
///

/// config for the chat app
const String adminEmail = "admininspireui@gmail.com";
const smartChat = [
  {'app': 'whatsapp://send?phone=8499999999', 'iconData': FontAwesomeIcons.whatsapp},
  {'app': 'https://m.me/csasonic2', 'iconData': FontAwesomeIcons.facebookMessenger},
  {'app': 'tel:8499999999', 'iconData': FontAwesomeIcons.phone},
  {'app': 'sms://8499999999', 'iconData': FontAwesomeIcons.sms}
];

/// the welcome screen data
List onBoardingData = [
  {
    "title": "Welcome to FluxStore",
    "image": "assets/images/fogg-delivery-1.png",
    "desc": "Fluxstore is on the way to serve you. "
  },
  {
    "title": "Connect Surrounding World",
    "image": "assets/images/fogg-uploading-1.png",
    "desc": "See all things happening around you just by a click in your phone. "
        "Fast, convenient and clean."
  },
  {
    "title": "Let's Get Started",
    "image": "fogg-order-completed.png",
    "desc": "Waiting no more, let's see what we get!"
  },
];

*****************************
config.json

{
    "server": {
        "type": "opencart",
        "url": "http://opencart-demo.mstore.io",
        "blog": "http://fluxstore.inspireui.com",
        "forgetPassword": "http://opencart-demo.mstore.io/index.php?route=account/forgotten"
    },
    "HorizonLayout": [
        {
            "layout": "logo"
        },
        {
            "layout": "iconCategory"
        },
        {
            "layout": "bannerImage",
            "isSlider": true,
            "items": [
                {
                    "product": 9237,
                    "image": "https://user-images.githubusercontent.com/1459805/59846818-12672e80-938b-11e9-8184-5f7bfe66f1a2.png",
                    "padding": 15.0
                },
                {
                    "category": 20,
                    "image": "https://user-images.githubusercontent.com/1459805/60091575-1f12ca80-976f-11e9-962c-bdccff60d143.png",
                    "padding": 15.0
                },
                {
                    "category": 18,
                    "image": "https://user-images.githubusercontent.com/1459805/60091808-a19b8a00-976f-11e9-9cc7-576ca05c2442.png",
                    "padding": 15.0
                }
            ]
        },
        {
            "layout": "bannerImage",
            "items": [
                {
                    "category": 25,
                    "image": "https://user-images.githubusercontent.com/1459805/59846820-12672e80-938b-11e9-8fa6-b331b7db331d.png",
                    "padding": 5.0
                }
            ]
        },
        {
            "layout": "bannerImage",
            "items": [
                {
                    "category": 57,
                    "image": "https://user-images.githubusercontent.com/1459805/59846823-12ffc500-938b-11e9-8d93-65ead3d6b1dd.png",
                    "padding": 5.0
                },
                {
                    "category": 24,
                    "image": "https://user-images.githubusercontent.com/1459805/59846824-12ffc500-938b-11e9-8d5a-fc42cb1b7658.png",
                    "padding": 5.0
                }
            ]
        },
        {
            "name": {
                "en": "Woman Collections",
                "ab": "مجموعات المرأة",
                "vi": "Bộ sưu tập cho phụ nữ"
            },
            "image": "",
            "layout": "threeColumn",
            "category": 20
        },
        {
            "name": {
                "en": "Man Collections",
                "ab": "مجموعات الرجل",
                "vi": "Bộ sưu tập cho đàn ông"
            },
            "image": "",
            "layout": "twoColumn",
            "category": 18
        },
        {
            "name": {
                "en": "Our Blog Posts",
                "ab": "بلوق وظائف",
                "vi": "Blog của chúng tôi"
            },
            "layout": "blog"
        },
        {
            "name": {
                "en": "Share your look",
                "ab": "مشاركة مظهرك",
                "vi": "Chia sẻ cái nhìn của bạn"
            },
            "layout": "instagram",
            "tag": "fashionmodel"
        }
    ],
    "Setting": {
        "MainColor": "#3FC1BE",
        "ProductListLayout": "list"
    }
}

**Comment by mohmmadmoatz** [comment]
![screenshot1](https://user-images.githubusercontent.com/34185983/62284555-7dad2180-b45c-11e9-88ae-de10b8ec4252.jpg)
![screenshot2](https://user-images.githubusercontent.com/34185983/62284556-7e45b800-b45c-11e9-9b80-e30d11bdc5ab.jpg)
![Screenshot_9](https://user-images.githubusercontent.com/34185983/62284582-8b62a700-b45c-11e9-98a2-9be3d7c2d50b.jpg)
![Screenshot_10](https://user-images.githubusercontent.com/34185983/62284583-8bfb3d80-b45c-11e9-96a8-a33214e5e261.jpg)

**Comment by minhcasi** [comment]
noted with checking, thank you!

@minhtruong315

**Comment by mohmmadmoatz** [comment]
i have another problem ..
http://opencart-demo.mstore.io/index.php?route=extension/mstore/payment_method
this api not work

**Comment by mohmmadmoatz** [comment]
and i have another problem 

  @override
  Future<List<ProductVariation>> getProductVariations(Product product) {
    // TODO: implement getProductVariations
    return null;
  }

this function return null ???

**Comment by minhtruong315** [comment]
product variations haven't supported in opencart yet. We will update it later.

**Comment by mohmmadmoatz** [comment]
@minhtruong315
I solved the first problem of category 
By edit the Mstore category controller

**Comment by minhtruong315** [comment]
Hi @mohmmadmoatz I updated category, it will be available in next update
