### ISSUE TITLE
[my-product] - beonews-pro

### ISSUE THREAD

**Issue by nb05** [inspireui/support#863]
info Found Xcode project beonews.xcodeproj
xcrun: error: unable to find utility "instruments", not a developer tool or in PATH
error Command failed: xcrun instruments -s
xcrun: error: unable to find utility "instruments", not a developer tool or in PATH
. Run CLI with --verbose flag for more details.

on the new update ? once run react-native run-ios

**Comment by amit81** [comment]
lottie-react-native:compileDebugJavaWithJavac FAILED
