### ISSUE TITLE
BuzzApp Uploading Theme on Wordpress Shows Error  style.css stylesheet file Missing

### ISSUE THREAD

**Issue by KIRANNAIR1** [inspireui/support#864]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------
Link : from where i purchased Theme : https://codecanyon.net/item/cenews-multipurpose-wordpress-react-native-app/22705946

1. I uploaded The BuzzApp Theme on my  Domain  through Wordpress Dashboard,
but it throws Error StyleSheet.css file missing.

Please give correct Zip File to Upload the BuzzApp on my Domain.

2. Screenshots

3. My screenshot of the purchase product or my comment:

3. Config files (optional)
![StyleSheet file missing](https://user-images.githubusercontent.com/7288469/62350134-6a16bf00-b51f-11e9-90d4-0c801953351b.PNG)

**Comment by minhcasi** [comment]
Hi, the BuzzApp is the react native framework it is not the Wordpress template, pls see detail about this framework - https://facebook.github.io/react-native/docs/getting-started.html

Or see the installing of the buzzapp from - https://docs.inspireui.com/buzzapp

**Comment by KIRANNAIR1** [comment]
Pls provide engineer . I am ready to Pay.

I struggling since 1 week .

**Comment by KIRANNAIR1** [comment]
1) Once we Change the Url, the App will fetch data from my URL Right ?
Since the URL is Blank  have no POst, Image, etc.... the APP will also
become blank.
In that case From where we should create  the post, & articles so that it
display on APP.

**Comment by minhtruong315** [comment]
Hi @KIRANNAIR1 
You need to add more posts in admin panel of wordpress website.

**Comment by KIRANNAIR1** [comment]
I Created Category & Post in Wordpress Dashboard, it reflects in APP on
Category Page & Flipboard Page.

How Do i populate Home Page TABS : "FOR YOU" & "TRENDING".

The Home Page Fetch Data from Post Or Category Or Page  Or Menu ?

CeBuilder is not working on My PC , So What is Alternate to CeBuilder.
Do i need to Change the Category ID in Source Code , If yes Then where
