### ISSUE TITLE
[MStore] - CeBuilder Error When Build

### ISSUE THREAD

**Issue by mryous** [inspireui/support#865]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------
Purchase Code : a2f2e25e-3f14-41d7-b759-4999af668ce7

1. Got error when build
`[4/4] Building fresh packages...
[1/5] ⡀ grpc
[-/5] ⡀ waiting...
[-/5] ⡀ waiting...
[-/5] ⡀ waiting...
error D:\...\...\mstore-multi-vendor-v1.3.1\mstore-mv-expo\node_modules\grpc: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build --library=static_library
Arguments:
Directory: D:\...\...\mstore-multi-vendor-v1.3.1\mstore-mv-expo\node_modules\grpc
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.12.0
node-pre-gyp info using node@12.4.0 | win32 | x64
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp info check checked for "D:\...\...\mstore-multi-vendor-v1.3.1\mstore-mv-expo\node_modules\grpc\src\node\extension_binary\node-v72-win32-x64-unknown\grpc_node.node" (not found)
node-pre-gyp http GET https://node-precompiled-binaries.grpc.io/grpc/v1.17.0/node-v72-win32-x64-unknown.tar.gz
node-pre-gyp http 404 https://node-precompiled-binaries.grpc.io/grpc/v1.17.0/node-v72-win32-x64-unknown.tar.gz
node-pre-gyp WARN Tried to download(404): https://node-precompiled-binaries.grpc.io/grpc/v1.17.0/node-v72-win32-x64-unknown.tar.gz
node-pre-gyp WARN Pre-built binaries not found for grpc@1.17.0 and node@12.4.0 (node-v72 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://node-precompiled-binaries.grpc.io/grpc/v1.17.0/node-v72-win32-x64-unknown.tar.gz
........` 

2. 
![image](https://user-images.githubusercontent.com/28628432/62350962-e4067280-b536-11e9-870d-898fb7a32632.png)

3. My screenshot of the purchase product or my comment:
![image](https://user-images.githubusercontent.com/28628432/62351124-43648280-b537-11e9-9ba4-b1dbcac13c5a.png)

**Comment by minhcasi** [comment]
Hi, could you help to download & install the node 10.x from this link - https://nodejs.org - then try to restart the installing again ?

**Comment by mryous** [comment]
now, The Rest API is not working correctly !

**Comment by mryous** [comment]
> now, The Rest API is not working correctly !

its working now, but when tap the setting button this happen
![image](https://user-images.githubusercontent.com/28628432/62420982-835d6e00-b6cd-11e9-9271-94e84a64ef82.png)

**Comment by mryous** [comment]
> > now, The Rest API is not working correctly !
> 
> its working now, but when tap the setting button this happen
> ![image](https://user-images.githubusercontent.com/28628432/62420982-835d6e00-b6cd-11e9-9271-94e84a64ef82.png)

how can i disable the setting menu?

**Comment by minhtruong315** [comment]
Hi @mryous You can edit in "src/navigation/index.js" to disable setting menu
