### ISSUE TITLE
[Listapp] listing page error after publish in google play

### ISSUE THREAD

**Issue by reconshield** [inspireui/support#866]
Latest update working great.. but i face this issue when open listing . Other than that listapp 1.7.3 working great. I dont get errors in ios .. only in android.. pls advice

![7F266DCC-9ABA-4CE8-BFFE-BE8EDDBC64A2](https://user-images.githubusercontent.com/25501496/62355997-b0314a00-b542-11e9-871e-9869a7660f94.jpeg)

**Comment by thangvo9x** [comment]
First, check your content is valid
Second. Share your screen video for checking faster.

**Comment by reconshield** [comment]
content is valid.i just replace post js file and its working fine..thanks
