### ISSUE TITLE
[fluxstore - pro] - support categories and products multilanguage

### ISSUE THREAD

**Issue by MarcHe124** [inspireui/support#868]
1. My issue
I like the product. It is nice and clean.

I just find the categories and products do not support multi-language for now. Do you have any suggestion on that? currently what I can think of is adding a language parameter in opencart.dart for all related api requests.

3. My screenshot of the purchase product or my comment:
Same question I put on codeyan:
<img width="788" alt="WX20190802-105849@2x" src="https://user-images.githubusercontent.com/12852794/62389502-d213d800-b514-11e9-8123-e07e2333c2fc.png">

**Comment by minhcasi** [comment]
fixed on release 1.4 - thank you!

**Comment by MarcHe124** [comment]
Thanks! can I know when roughly v1.4 will release?

**Comment by minhcasi** [comment]
Hi, we will release on this week - thank you!

**Comment by minhcasi** [comment]
Hi @MarcHe124 - sorry we though this issue from woocommerce (already fix on 1.4) but just realize your issue from the Opencart one.

We may release the support for Opencart on next 1.5 as this is big feature for Opencart while they do not support multi-language from the API, is there any language plugin/extension that you suggest?

**Comment by MarcHe124** [comment]
ah ok.  The language plugin you mean for API? I haven't looked at it yet. 

If it is not in near future, we may directly modify that api extension to support multi-language for our app.

thanks
