### ISSUE TITLE
mstore

### ISSUE THREAD

**Issue by abdalrhmanattia** [inspireui/support#869]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue
when i tray to run app muddle in android studio i get this errors 
* What went wrong:
Execution failed for task ':react-native-facebook-account-kit:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

i used latest version of app version of app 

![image](https://user-images.githubusercontent.com/49997361/62389949-6c9a0880-b561-11e9-80c1-0c210928f388.png)

**Comment by minhcasi** [comment]
Hi, please check following solution as this the cache issue:

- Download/extract the refresh and latest package of mstore 
- Go to the project folder, mstore-pro and run this script
```
yarn install
yarn start --reset-cache
react-native run-android (open the Android Simulator before running)
```

Let us know your checking, thank youi!

@vumanhsn97
