### ISSUE TITLE
[MStore] - issue one exporting andorid

### ISSUE THREAD

**Issue by kiamoz** [inspireui/support#87]
![screen shot 2018-12-07 at 3 34 13 am](https://user-images.githubusercontent.com/10494372/49694608-af5a3b00-fba2-11e8-969c-9a9d7e7497fa.jpg)

see attached please :(

**Comment by luyx2412** [comment]
Hi @kiamoz, Please install package with `yarn install`. I saw your attached which lack of the library `jsc-android`.

Thanks

**Comment by kiamoz** [comment]
thank you , please do not close this issue till I tell you the next status , thanks
