### ISSUE TITLE
[MSTORE MultiVendor] - Can't Upload Product

### ISSUE THREAD

**Issue by mikysetiawan** [inspireui/support#870]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. I get error when uploading product via apps, so after I install the JWT and follow the tutorial from here https://docs.inspireui.com/mstore-mv/getting-started/ to setting the jwt, like edit my .htaccess and edit my wp-config.php. I try to build it on emulator and it show error “Can not Connect to Server” and I already try build it on android and it give different error “This site is experiencing technical difficulties” did I missed something?

2. Screenshots
![image](https://user-images.githubusercontent.com/26665849/62390582-d8459b00-b58c-11e9-8601-0d4e984d4887.png)

3. My screenshot of the purchase product or my comment:
![image](https://user-images.githubusercontent.com/26665849/62390613-e72c4d80-b58c-11e9-8a5b-2d936504c20e.png)

4. Config files (optional)
[wp-config.txt](https://github.com/inspireui/support/files/3462490/wp-config.txt)

**Comment by thangvo9x** [comment]
You must have add those code to the .htaccess file, too.
Refer here 
https://wordpress.org/plugins/jwt-authentication-for-wp-rest-api/
Thanks

**Comment by mikysetiawan** [comment]
Add this?

RewriteEngine on
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule ^(.*) - [E=HTTP_AUTHORIZATION:%1]

But I already do that

**Comment by thangvo9x** [comment]
you must have add below code out of the block
`SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1`
or add this code for uploading Media When createing a new Post
`<IfModule mod_headers.c>
​    Header set Access-Control-Allow-Origin "*"
</IfModule>`

**Comment by reshiDeveloper** [comment]
Where  .htaccess file is located? In react native project?

**Comment by mikysetiawan** [comment]
I already add that to htaccess but still not working, any advice?

![image](https://user-images.githubusercontent.com/26665849/62440547-df320080-b77a-11e9-801b-5b0962a8559e.png)

**Comment by thangvo9x** [comment]
`
# BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule ^(.*) - [E=HTTP_AUTHORIZATION:%1]
</IfModule>
SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1
<IfModule mod_headers.c>
   Header set Access-Control-Allow-Origin "*"
</IfModule>

# END WordPress
`

**Comment by reshiDeveloper** [comment]
How can I install mstore plugin?

**Comment by thangvo9x** [comment]
Hi. update with this file
[htaccess-file.txt](https://github.com/inspireui/support/files/3474902/htaccess-file.txt)
Thanks
