### ISSUE TITLE
[CeBuilder] - not able to build android

### ISSUE THREAD

**Issue by itspathanofficial** [inspireui/support#871]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue
react native not building app, so much errors showing

log:
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

warn Package api-ecommerce has been ignored because it contains invalid configuration. Reason: Cannot find module 'api-ecommerce\package.json'
Require stack:
- C:\Users\itsme\Desktop\CodeCanyon\codecanyon-BE7KUczS-beostore-complete-react-native-template-for-ecommerce\mstore-3.9.3\mstore-pro\node_modules\react-native\node_modules\@react-native-community\cli\build\tools\config\resolveNodeModuleDir.js
- C:\Users\itsme\Desktop\CodeCanyon\codecanyon-BE7KUczS-beostore-complete-react-native-template-for-ecommerce\mstore-3.9.3\mstore-pro\node_modules\react-native\node_modules\@react-native-community\cli\build\tools\releaseChecker\index.js
- C:\Users\itsme\Desktop\CodeCanyon\codecanyon-BE7KUczS-beostore-complete-react-native-template-for-ecommerce\mstore-3.9.3\mstore-pro\node_modules\react-native\node_modules\@react-native-community\cli\build\commands\server\runServer.js
- C:\Users\itsme\Desktop\CodeCanyon\codecanyon-BE7KUczS-beostore-complete-react-native-template-for-ecommerce\mstore-3.9.3\mstore-pro\node_modules\react-native\node_modules\@react-native-community\cli\build\commands\server\server.js
- C:\Users\itsme\Desktop\CodeCanyon\codecanyon-BE7KUczS-beostore-complete-react-native-template-for-ecommerce\mstore-3.9.3\mstore-pro\node_modules\react-native\node_modules\@react-native-community\cli\build\commands\index.js
- C:\Users\itsme\Desktop\CodeCanyon\codecanyon-BE7KUczS-beostore-complete-react-native-template-for-ecommerce\mstore-3.9.3\mstore-pro\node_modules\react-native\node_modules\@react-native-community\cli\build\cliEntry.js
- C:\Users\itsme\Desktop\CodeCanyon\codecanyon-BE7KUczS-beostore-complete-react-native-template-for-ecommerce\mstore-3.9.3\mstore-pro\node_modules\react-native\node_modules\@react-native-community\cli\build\index.js
- C:\Users\itsme\Desktop\CodeCanyon\codecanyon-BE7KUczS-beostore-complete-react-native-template-for-ecommerce\mstore-3.9.3\mstore-pro\node_modules\react-native\cli.js
- C:\Users\itsme\AppData\Roaming\npm\node_modules\react-native-cli\index.js
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 998 file(s) to forward-jetify. Using 4 workers...
info Starting JS server...
info Installing the app...
Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':@react-native-community_async-storage'.
> SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at 'C:\Users\itsme\Desktop\CodeCanyon\codecanyon-BE7KUczS-beostore-complete-react-native-template-for-ecommerce\mstore-3.9.3\mstore-pro\android\local.properties'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9m 40s

error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':@react-native-community_async-storage'.
> SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at 'C:\Users\itsme\Desktop\CodeCanyon\codecanyon-BE7KUczS-beostore-complete-react-native-template-for-ecommerce\mstore-3.9.3\mstore-pro\android\local.properties'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9m 40s

    at checkExecSyncError (child_process.js:623:11)
    at execFileSync (child_process.js:641:15)
    at runOnAllDevices (C:\Users\itsme\Desktop\CodeCanyon\codecanyon-BE7KUczS-beostore-complete-react-native-template-for-ecommerce\mstore-3.9.3\mstore-pro\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:74:39)
    at buildAndRun (C:\Users\itsme\Desktop\CodeCanyon\codecanyon-BE7KUczS-beostore-complete-react-native-template-for-ecommerce\mstore-3.9.3\mstore-pro\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:158:41)
    at C:\Users\itsme\Desktop\CodeCanyon\codecanyon-BE7KUczS-beostore-complete-react-native-template-for-ecommerce\mstore-3.9.3\mstore-pro\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:125:12
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async Command.handleAction (C:\Users\itsme\Desktop\CodeCanyon\codecanyon-BE7KUczS-beostore-complete-react-native-template-for-ecommerce\mstore-3.9.3\mstore-pro\node_modules\react-native\node_modules\@react-native-community\cli\build\cliEntry.js:160:7)
PS C:\Users\itsme\Desktop\CodeCanyon\codecanyon-BE7KUczS-beostore-complete-react-native-template-for-ecommerce\mstore-3.9.3\mstore-pro>

2. Screenshots
![Untitled](https://user-images.githubusercontent.com/34849884/62408557-8894bd00-b5e8-11e9-8e50-1dccedc47ad5.png)

3. My screenshot of the purchase product or my comment:

3. Config files (optional)

**Comment by minhcasi** [comment]
Hi, could you open the mstore-pro\android\local.properties and change to your own android skd path, this could be the root cause on your pc - thanks

**Comment by itspathanofficial** [comment]
i am not able to find any 'local.properties' file in the location you said.
screenshot attached.

![Untitled](https://user-images.githubusercontent.com/34849884/62424746-f3490580-b687-11e9-9084-30e2415f0402.png)

**Comment by minhcasi** [comment]
Hi, you can create a new file and add the sdk.dir as this screenshot - https://tppr.me/lNzom

Check this solution for detail - https://stackoverflow.com/questions/32634352/react-native-android-build-failed-sdk-location-not-found

**Comment by itspathanofficial** [comment]
i have created that 'local.properties' file in mstore-pro folder according to the Stackoverflow but 
why this warning still occurs everytime i am trying to build app in PowerShell:

"warn Package api-ecommerce has been ignored because it contains invalid configuration. Reason: Cannot find module 'api-ecommerce\package.json"

![Untitled](https://user-images.githubusercontent.com/34849884/62438534-b5d28f80-b6fc-11e9-9ebb-b000f36d8f83.png)

**Comment by reshiDeveloper** [comment]
How can I install mstore plugin?

**Comment by itspathanofficial** [comment]
here you can see the plugin and same api key's last digits

Plugin: 
![plugin](https://user-images.githubusercontent.com/34849884/62593486-81c1bf00-b8f4-11e9-9625-26e46725def4.png)


API Keys: 

![api keys](https://user-images.githubusercontent.com/34849884/62593495-8d14ea80-b8f4-11e9-88c7-c650b01a57be.png)

**Comment by itspathanofficial** [comment]
> How can I install mstore plugin?

**Comment by itspathanofficial** [comment]
> > How can I install mstore plugin?
 you can see here:
https://docs.inspireui.com/mstore/wordpress-setting/

**Comment by minhcasi** [comment]
Please click the link mstore-checkout link from https://docs.inspireui.com/mstore/wordpress-setting/ and upload the zip plugin to your wordpress plugins 

and active mstore-checkout from setting menu - https://tppr.me/EzEm7

**Comment by sackmotion** [comment]
Looks that latest version is https://github.com/inspireui/mstore-checkout 1.1.6 instead of https://github.com/inspireui/mstore/tree/master/plugins/mstore-checkout 1.1.5 , please can you confirm and correct in docs ?

btw Great job !
Thanks!

**Comment by minhcasi** [comment]
Yes, thank you, this 1.1.6 is the latest version - https://github.com/inspireui/mstore-checkout - we will update new document shortly :)
