### ISSUE TITLE
[ListApp]: "Can not find server" message when adding listing 

### ISSUE THREAD

**Issue by serwadda** [inspireui/support#872]
Hello,
A user can successfully sign up, however they failed to add their listings thereafter. The add listing process fails at the last stage (Submit stage) with a message :"Can not find Server". Please see files and screenshot below. 
[MyListing.txt](https://github.com/inspireui/support/files/3463643/MyListing.txt)
![Screenshot_20190803-104841](https://user-images.githubusercontent.com/5629648/62410292-52007780-b5d3-11e9-94d7-402349abf335.png)

And below is the same message I posted for confirmation of my purchase:
![screenshot of purchase](https://user-images.githubusercontent.com/5629648/62410402-6a24c680-b5d4-11e9-80a8-7f6d0be06fd6.png)

Serwadda

**Comment by thangvo9x** [comment]
Hi. Could you share the AppConfig.json file for checking?

**Comment by serwadda** [comment]
Please find attached for your action:

[AppConfig.txt](https://github.com/inspireui/support/files/3466049/AppConfig.txt)

**Comment by serwadda** [comment]
Please find attached for your action
../Swithin Serwadda

**Comment by thangvo9x** [comment]
Hi. I checked on your config.
some notes for you 
1. theme is myListing, NOT mylisting
2. Re-install with this plugin
[json-api.zip](https://github.com/inspireui/support/files/3470106/json-api.zip)
Thanks

**Comment by serwadda** [comment]
Sorted...thanks
