### ISSUE TITLE
[BeoNews] Android Issue

### ISSUE THREAD

**Issue by zziltong** [inspireui/support#873]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue

Non-normal shutdown in google play console

2. Screenshots

![KakaoTalk_Photo_2019-08-04-11-05-00](https://user-images.githubusercontent.com/48820418/62418599-c0166e80-b6a7-11e9-9ee5-154588e28310.png)
![KakaoTalk_Photo_2019-08-04-11-05-06](https://user-images.githubusercontent.com/48820418/62418600-c0af0500-b6a7-11e9-88cf-8556d7237451.png)

3. My screenshot of the purchase product or my comment:

3. Config files (optional)

**Comment by minhcasi** [comment]
Hi, could you share your config files so that we could help for checking this issue, it seems the issues related to the data - thank you!

**Comment by zziltong** [comment]
> Hi, could you share your config files so that we could help for checking this issue, it seems the issues related to the data - thank you!

May I share my config files by e-mail?

**Comment by minhcasi** [comment]
Yes sure, please sent to support@inspireui.com - also note with this ticket support - thank you!

**Comment by concuacon** [comment]
Hello @zziltong  could you del the node_module and zip the source code, then sent to our email tuan@inspireui.com via https://wetransfer.com - i will help for checking this issue - thanks
