### ISSUE TITLE
[FluxStore Pro] - Can't import splashscreen.flr2d into the flare2d online platform

### ISSUE THREAD

**Issue by ihsanberahim** [inspireui/support#876]
Can't import splashscreen.flr2d into the flare2d online platform. So, how to modify it or you guys already share in the docs but i missed it?

My mission, just to change the text and the logo in the flare splashscreen.

**Comment by minhcasi** [comment]
Hi, use this option for the export - https://tppr.me/AKYOr

The flr2d will not work as it is content the project source 

Thanks

**Comment by ihsanberahim** [comment]
that is export function i know. but i ask how to modify the file `splashscreen.flr2d` you guys provided in the zip file?

**Comment by minhcasi** [comment]
Hi, try to create the Blank File on https://www.2dimensions.com and drag the .flr2d file into the Dashboard

**Comment by ihsanberahim** [comment]
It works! I tried before wrong way drag. Thanks for your guidance. Thanks.
