### ISSUE TITLE
[Fluxstore Pro] - Just purchased, Issue while debugging through Visual studio code

### ISSUE THREAD

**Issue by shafirmubarak** [inspireui/support#877]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue

I have just purchased the Fluxstore Pro app and I am unable to compile/ debug using visual studio code.  Please find the detailed log below - Kindly assist.

`Launching lib\main.dart on Android SDK built for x86 in debug mode...
* Error running Gradle:
ProcessException: Process "D:\Android\flutter_projects\codecanyon-ir0L3SjS-fluxstore-the-universal-woocommerce-magento-opencart-mobile-app-by-flutter-framework\FluxStore 1.3.5\source\android\gradlew.bat" exited abnormally:
Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details
Starting a Gradle Daemon, 1 stopped Daemon could not be reused, use --status for details

> Configure project :app
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
WARNING: API 'variant.getMergeAssets()' is obsolete and has been replaced with 'variant.getMergeAssetsProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getMergeAssets(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.
WARNING: API 'variantOutput.getProcessResources()' is obsolete and has been replaced with 'variantOutput.getProcessResourcesProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variantOutput.getProcessResources(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.

> Configure project :firebase_auth
         *********************************************************
WARNING: This version of cloud_firestore will break your Android build if it or its dependencies aren't compatible with AndroidX.
         See https://goo.gl/CP92wY for more information on the problem and how to fix it.
         This warning prints for all Android build failures. The real root cause of the error may be unrelated.
         *********************************************************

Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':firebase_auth'.
> Could not resolve all artifacts for configuration ':firebase_auth:classpath'.
   > Could not resolve org.jetbrains.kotlin:kotlin-reflect:1.3.20.
     Required by:
         project :firebase_auth > com.android.tools.build:gradle:3.3.1 > com.android.tools.lint:lint-gradle-api:26.3.1
         project :firebase_auth > com.android.tools.build:gradle:3.3.1 > com.android.tools.build:builder:3.3.1 > com.android.tools:sdk-common:26.3.1
      > Could not resolve org.jetbrains.kotlin:kotlin-reflect:1.3.20.
         > Could not get resource 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-reflect/1.3.20/kotlin-reflect-1.3.20.pom'.
            > Could not GET 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-reflect/1.3.20/kotlin-reflect-1.3.20.pom'. Received status code 504 from server: Gateway Time-out
   > Could not resolve org.jetbrains.kotlin:kotlin-stdlib:1.3.20.
     Required by:
         project :firebase_auth > com.android.tools.build:gradle:3.3.1 > org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.20
      > Skipped due to earlier error
   > Could not resolve org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.20.
     Required by:
         project :firebase_auth > com.android.tools.build:gradle:3.3.1 > org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.20
      > Skipped due to earlier error
   > Could not resolve org.jetbrains.kotlin:kotlin-stdlib:1.3.20.
     Required by:
         project :firebase_auth > com.android.tools.build:gradle:3.3.1 > com.android.tools.build.jetifier:jetifier-core:1.0.0-beta02
         project :firebase_auth > com.android.tools.build:gradle:3.3.1 > com.android.tools.build.jetifier:jetifier-processor:1.0.0-beta02
      > Skipped due to earlier error

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 14s
  Command: D:\Android\flutter_projects\codecanyon-ir0L3SjS-fluxstore-the-universal-woocommerce-magento-opencart-mobile-app-by-flutter-framework\FluxStore 1.3.5\source\android\gradlew.bat app:properties
Please review your Gradle project setup in the android/ folder.
Exited (sigterm)
`

2. Screenshots

3. My screenshot of the purchase product or my comment:
<img width="513" alt="Capture" src="https://user-images.githubusercontent.com/53738841/62444848-4d2af780-b77c-11e9-9fd9-8548d87d184d.PNG">

3. Config files (optional)

**Comment by minhtruong315** [comment]
Hi @shafirmubarak Please follow by these link

https://flutter.dev/docs/get-started/install/windows
https://flutter.dev/docs/get-started/editor?tab=vscode
