### ISSUE TITLE
fluxstore-woocommerce

### ISSUE THREAD

**Issue by peter2411** [inspireui/support#878]
1. My issue
while sign up via Email 
NoSuchMethodError: Class ‘User’ has no instance method .
" This problem exists even in your app on playstore ! "

2. Screenshots

https://prnt.sc/oojmtz 
https://prnt.sc/oojmn6

3. My screenshot of the purchase product or my comment:

https://prnt.sc/oojztq

**Comment by minhtruong315** [comment]
I fixed. It will be available in next release. Thanks
