### ISSUE TITLE
[Listapp] - 

### ISSUE THREAD

**Issue by mmubeennisar** [inspireui/support#879]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue
Image not uploading from app.
It shows 403 error that 
code:rest_cannot_create
message:Sorry, you are not allowed to create posts as this user.
I have done all the settings as they are mentioned in the doc
2. Screenshots

3. My screenshot of the purchase product or my comment:

3. Config files (optional)

**Comment by thangvo9x** [comment]
The problem went from config JWT Plugin on your website.
Refer here to uploading media 
https://docs.inspireui.com/listapp/getting-started/#jwt-authentication
Thanks

**Comment by thangvo9x** [comment]
The problem went from config JWT Plugin on your website.
Refer here to uploading media 
https://docs.inspireui.com/listapp/getting-started/#jwt-authentication
Thanks

**Comment by mmubeennisar** [comment]
I have already done that and tried that.

# BEGIN WordPress

<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule ^(.*) - [E=HTTP_AUTHORIZATION:%1]
</IfModule>

# END WordPress

**Comment by mmubeennisar** [comment]
![Screenshot 2019-08-06 at 12 09 42 PM](https://user-images.githubusercontent.com/28184542/62518486-1cfa5c00-b843-11e9-9991-8c51a41104be.png)
Attached the htaccess
Same issue

**Comment by thangvo9x** [comment]
adding this block & still not wokring. Sharing your AppConfig file for checking.
`SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1 
<IfModule mod_headers.c> 
Header set Access-Control-Allow-Origin "*" 
</IfModule>`

**Comment by mmubeennisar** [comment]
![Screenshot 2019-08-06 at 3 49 57 PM](https://user-images.githubusercontent.com/28184542/62534151-e7b13680-b861-11e9-967e-489f4ff90816.png)
<img width="1164" alt="Screenshot 2019-08-06 at 3 48 57 PM" src="https://user-images.githubusercontent.com/28184542/62534152-e7b13680-b861-11e9-8ad9-4dd31e020602.png">
<img width="867" alt="Screenshot 2019-08-06 at 3 48 48 PM" src="https://user-images.githubusercontent.com/28184542/62534153-e7b13680-b861-11e9-954b-f23a380b3bfe.png">
<img width="675" alt="Screenshot 2019-08-06 at 3 48 31 PM" src="https://user-images.githubusercontent.com/28184542/62534155-e849cd00-b861-11e9-97dc-51c261383c83.png">
<img width="562" alt="Screenshot 2019-08-06 at 3 48 23 PM" src="https://user-images.githubusercontent.com/28184542/62534156-e849cd00-b861-11e9-8085-552e076b17ef.png">

Also tried that, when i do that it gives 403 error please see.

AppConfig:
`{
  "Website": {
    "url": "http://listable.gamitica.com/",
    "consumerKey": "ck_c030b81f33278b440c10364b1f2916b4b92d1963",
    "consumerSecret": "cs_7b8fd48f01b86c0b8535147bcf5f5df9e3f8afc6"
  },
  "Theme": "listable",
  "MainColor": {
    "tabbarTint": "#00B2BC",
    "tabbarColor": "#D5D8DE",
    "mainColorTheme": "#00B2BC",
    "tabbar": "#fff"
  }
}`

**Comment by thangvo9x** [comment]
Hi bro. The use need Editor/Admin role to create a new post.

**Comment by mmubeennisar** [comment]
Thanks, that helped :)
