### ISSUE TITLE
[ListApp] Android problem

### ISSUE THREAD

**Issue by Mark0000008** [inspireui/support#88]
- Product: ListApp MyListing Version
 - Your Purchased Code: d4f87a9a-a6ea-400d-8dc6-3a9703872133

Hello, I have buyed the List App Template from CodeCanyon, I’m trying to build a project using the 1.4 version since the last version seem to not work at all, however I’m having issues with 1.4 too, in development mode, only on Android when i open a listing I get this error:

“Cannot add a child that doesn’t have a YogaNode to a parent without a measure function!(Trying to add a ‘RctRawText [text:]’ to RCTView’)”

I have tried to build the app with expo and on android I get another generic error when I open the installed APK, Uncaught Error: Module AppRegistry is not a registered callable module(calling runApplication)

I would REALLY appreciate any kind of help, I have a strict deadline and I can’t find a proper solution to the problem.
If you need more informations just let me know.

Thanks in advance for the reply.

**Comment by minhcasi** [comment]
Hi, could you help to share the config.js file here, we will help for debugging the issue - thank you!

**Comment by thangvo9x** [comment]
Hi. @Mark0000008 , Share your Config.js to email than@beostore.io help me, I'll check help you.

**Comment by Mark0000008** [comment]
Hello, just sent the config.js file to thang@beostore.io

Thanks a lot for now!

**Comment by Mark0000008** [comment]
Hello, did you received the file? Any news?

**Comment by thangvo9x** [comment]
Hi. I haven't been it yet. Please send it again. 
Thanks

**Comment by Mark0000008** [comment]
Sended again...

**Comment by Mark0000008** [comment]
However I really doubt that the problem is in the Config.js file, I have reasons to thing that the problem is in the ListingDetail.js file since the problem happen when I open a Listing, however replacing it with a modded version of ListingDetail.js from the new version of ListApp where there isn't this problem doesn't solve it either,  it's really frustrating since it seems that any version of this template have problems, the new version have a lot of bugs too: App crash when opening a Listing and Chat feature doesn't work, everything with a fresh install.
Really, really frustrating!

**Comment by thangvo9x** [comment]
hi. Please provide your info from config. You sended me the empty Config.js file.

**Comment by Mark0000008** [comment]
Hello, I've solved the error, There was a TouchableOpacity component in Components/Footer/index.js file that had multiple children, TouchableOpacity component should only have one children, if you need to put multiple child component, wrap it in a view component.

Anyway now I only have one problem, I don't know how to configure Facebook Login since there is no documentation about this, and with the standard configuration in a production build Facebook login throw an hash error.

**Comment by thangvo9x** [comment]
Hi. Thanks for your value feedback. To config Facebook Login, your can refer here : 
https://developers.facebook.com/apps/
Thanks
