### ISSUE TITLE
Mstore Homepage "BannerImage" layout not showing two images in a row

### ISSUE THREAD

**Issue by shweta-bavishi** [inspireui/support#880]
I want to display two images on a row in home page of my app. I have done the following configuration changes in AppConfig.json, and yet unable to see the expected result

![Screen Shot 2019-08-05 at 9 41 15 PM](https://user-images.githubusercontent.com/12051018/62478917-efbd9780-b7c9-11e9-9a44-ce7b60b55e73.png)

And here is how my homepage looks:

![Screen Shot 2019-08-05 at 9 37 59 PM](https://user-images.githubusercontent.com/12051018/62478946-0106a400-b7ca-11e9-8875-dfb06804ff9b.png)

**Comment by minhcasi** [comment]
Hi, could you use the example #2 from the example folder, it will look like this - https://docs.inspireui.com/mstore/home-theme/ - then replace your own image - thank you!

**Comment by shweta-bavishi** [comment]
I have used the same configurations. I have already attached my json object on the above image, which follows up the same format. Please let me know if any thing else needs to be added

**Comment by preetindersodhi** [comment]
I'm also having this issue. What is the solution?

**Comment by preetindersodhi** [comment]
What should be the size of the image? The URLs in "2-Banner Image.json" no longer work.

Here's the code:
 {
  "imageBanner": "URL-here",
  "column": 2,  
  "height": 100,
  "layout": "bannerImage", 
  "category": 38
},
    {
  "imageBanner": "URL-here",
  "column": 2,  
  "height": 100,
  "layout": "bannerImage", 
  "category": 38
},

Tried using different values of height. and removing the value as well. Still doesn't work.

 {
  "imageBanner": "URL-here",
  "column": 2,  
  "layout": "bannerImage", 
  "category": 38
},
    {
  "imageBanner": "URL-here",
  "column": 2,  
  "layout": "bannerImage", 
  "category": 38
},
