### ISSUE TITLE
Mstore- Search Not Working

### ISSUE THREAD

**Issue by shweta-bavishi** [inspireui/support#881]
While searching the product in the app, it auto-corrects, and moreover the screen is not displaying the result properly. Screen is continuously re-rendering itself. No configuration changes were done for search screen

![MstoreSearch](https://user-images.githubusercontent.com/12051018/62479886-1a105480-b7cc-11e9-9ba7-a16722d7a274.gif)

**Comment by minhcasi** [comment]
noted with checking, could you help to share your config files as well? Thanks

**Comment by shweta-bavishi** [comment]
Purchase Code: 31da4b2b-7899-4e0c-b4fe-82e73801c9d2
 
[Config.pdf](https://github.com/inspireui/support/files/3477841/Config.pdf)

**Comment by concuacon** [comment]
heloo @shweta-bavishi we are going to update the new 3.9.4 to fix this issue - please help to download and let us know your checking - thank you!

**Comment by minhcasi** [comment]
Release 3.9.4 for this fixing, please try to download again - thank you!
