### ISSUE TITLE
MSTORE PRO - Latest version - cannot compile

### ISSUE THREAD

**Issue by dougcodes** [inspireui/support#883]
Cannot compile latest version mstore

Version: 3.9.3

Steps:

cd into project
yarn
cd ios
rm Podfile.lock
rm -Rf Pods
rm -Rf build
pod install

-- Error --

Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 34 dependencies from the Podfile and 39 total pods installed.

[!] use_native_modules! skipped the react-native dependency 'react-native-admob'. No podspec file was found.
    - Check to see if there is an updated version that contains the necessary podspec file
    - Contact the library maintainers or send them a PR to add a podspec. The
    react-native-webview podspec is a good example of a package.json driven podspec. See
    https://github.com/react-native-community/react-native-webview/blob/master/react-native-webview.podspec
    - If necessary, you can disable autolinking for the dependency and link it manually. See
    https://github.com/react-native-community/cli/blob/master/docs/autolinking.md#how-can-i-disable-autolinking-for-unsupported-library

[!] A license was specified in podspec `RCTRestart` but the file does not exist - /Users/duser/Dropbox/Dg/Projects/keycave-mobile/downloads/mstore-3.9.3/mstore-pro/node_modules/react-native-restart/ios/LICENSE

[!] Unable to read the license file `LICENSE` for the spec `RCTRestart (0.0.12)`

[!] Unable to read the license file `LICENSE` for the spec `RCTRestart (0.0.12)`

[!] The `OneSignalNotificationServiceExtension [Debug]` target overrides the `HEADER_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-OneSignalNotificationServiceExtension/Pods-OneSignalNotificationServiceExtension.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `OneSignalNotificationServiceExtension [Release]` target overrides the `HEADER_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-OneSignalNotificationServiceExtension/Pods-OneSignalNotificationServiceExtension.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

-- Podfile --

platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'mstore' do
  # Pods for mstore
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/React'
  pod 'React-DevSupport', :path => '../node_modules/react-native/React'
  pod 'React-fishhook', :path => '../node_modules/react-native/Libraries/fishhook'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-RCTWebSocket', :path => '../node_modules/react-native/Libraries/WebSocket'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  target 'mstoreTests' do
    inherit! :search_paths
    # Pods for testing
  end

  use_native_modules!
end

target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignal', '>= 2.9.3', '< 3.0'
end

**Comment by minhcasi** [comment]
Thank you for the detail, we've noted and sent to the team for checking, thank you!

**Comment by concuacon** [comment]
Hello @dougcodes  could you del the node_module and zip the package, then sent to our email tuan@inspireui.com via https://wetransfer.com - i will help for checking this issue - thanks

**Comment by concuacon** [comment]
Hello @dougcodes  could you del the node_module and zip the source code, then sent to our email tuan@inspireui.com via https://wetransfer.com - i will help for checking this issue - thanks

**Comment by minhcasi** [comment]
Hi, pls update to latest 3.9.4 to fix this issue - let us know you checking

Just try these script from the download:
```
yarn install && yarn start --reset-cache
react-native run-ios
```

 thank you!
