### ISSUE TITLE
Expo SDK 

### ISSUE THREAD

**Issue by IamSMTS** [inspireui/support#884]
Hi

Download File from ThemeForest : MStore Multi Vendor - Complete React Native template for WooCommerce 
Item Purchase Code:
f976cc44-0258-4b5e-aff5-059f956d7749

..........
![WhatsApp Image 2019-08-06 at 13 34 59](https://user-images.githubusercontent.com/52594287/62526770-28ec1b00-b84f-11e9-82ed-489df6845188.jpeg)

To test the app without any interference, I wanted to test it, which showed the following error:
All work is done with a cebuilder.

What is the solution to this problem?

**Comment by minhcasi** [comment]
Hi could you try to open the project folder an run with this script first:
yarn install && yarn start
