### ISSUE TITLE
[MStore Magento] Cebuilder step1  setup

### ISSUE THREAD

**Issue by reshiDeveloper** [inspireui/support#886]
I have installed CeBuilder. But When I setup step 1 It is shown below error:

The Rest API is not working correctly ! 
How can I solve this problem?

I think that my access token isnt correct
this is token:  oibwhn2t9bx88pp7ivvb07td8nxvnr5y
url:  http://magento-demo.mstore.io

**Comment by minhcasi** [comment]
Hi @reshiDeveloper  - could you help to take a screenshot of your purchase product - thank you!
