### ISSUE TITLE
[ListApp] All Results limited to 10 including categories

### ISSUE THREAD

**Issue by menzer2015** [inspireui/support#89]
**Required Info (please complete the following information):**
 -  (MyListing)
 - Your Purchased Code: [get from https://codecanyon.net/downloads]
28ddad43-f990-****-****-2f5d67f12e4a (I have omitted some of my license code)

**Describe the bug**
All my results only display 10 items even though I have over 50 items in a category
Also in config I have selected to display all categories, but it only shows me 10 even though I scroll to the bottom of a list it does not load any more items nor does it have any pagination. 

I need both categories and items to be able to display all my items as a pagination please

I check debugger and CATEGORY_FETCH_SUCCESS also only shows 10 categories, I would have though there would be an option fetch a larger amount or at the very least there would be some kind of paging 

Please help

**Comment by menzer2015** [comment]
Sorry I put the wrong purchase code, I gave you the one for myListing Theme here is the correct ocde but partially edited 1d8d4ae7-7736-****-****-a869ce764483

**Comment by thangvo9x** [comment]
Hi. @menzer2015 . Try change this property
Categories: {
    showSub: false, // false if you want to show the categories with parent = 0 (level 1)
  },
change from showSub -> true
Thanks. let me know if it works.

**Comment by menzer2015** [comment]
Thanks for your suggestion, I did try this already and it only shows the first 10 categories in alphabetical order however I have 19 categories including subcategories

When I change to (showSub) -> false it shows the main 4 parent categories which is correct however I want to show all categories

I used Reactotron to see what was happening and CATEGORY_FETCH_SUCCESS only fetches 10 items and I assume it should fetch more but it's not so I am missing 9 categories..

Also this problem relates to my posts items it is only showing 10 items (I assume it should show more items or there should be a 'More' button when you scroll down to the end of the list but it doesn't)

I really appreaciate you getting back to me if you have any code that needs change please let me know as I would be happy to make the changes

PS: I notice this problem of you demo app also so I know this is not just my issue thanks

**Comment by thangvo9x** [comment]
Hi. send email to thang@beostore.io . I'll check help you

**Comment by thangvo9x** [comment]
You can add param is per_page(100) in function fetchCategories() in Redux/actions/CategoryActions
Thanks
