### ISSUE TITLE
[ListPro] - Custom Facebook login

### ISSUE THREAD

**Issue by theAlinux** [inspireui/support#891]
settings => #515 

i change to "logInID" in my-theme.js and "facebookAppId" in app.json, facebook settings this valid url 
![Ekran Alıntısı](https://user-images.githubusercontent.com/10341948/62640698-d2640700-b94a-11e9-85cb-30495c7746a8.PNG)

but get this error

`Given URL is not allowed by the Application configuration: One or more of the given URLs is not allowed by the App's settings. To use this URL you must add a valid native platform in your App's settings.`

fixed but now get this error

![Ekran Alıntısı](https://user-images.githubusercontent.com/10341948/62642433-61265300-b94e-11e9-8b95-b219d1212774.PNG)

**Comment by theAlinux** [comment]
@thangvo9x

**Comment by thangvo9x** [comment]
Do you have put in the firebase? You need to put in it.

**Comment by theAlinux** [comment]
i created firebase account, i created facebook app in firebase but i not found config settings, why i do it? is there something like tutorial?

**Comment by theAlinux** [comment]
added redirect url, fixed
