### ISSUE TITLE
[Listapp] - Not listed all

### ISSUE THREAD

**Issue by bobozd** [inspireui/support#892]
My issue is on homepage I click on one specific category (ID) and in next window in display only one listing item and in that category there is more listings for sure on wordpress site. Also on homescreen if I slide to right it displays it corectly there is 4 or more listings but when I click on category title (TOP ARCHVIZ COMAPNIES) it shows only one.

Video:
https://drive.google.com/file/d/1To4TZBQaikzttL2t9flIohHL_ypwWMnB/view?usp=sharing

Config files (optional)
[MyListing.js.zip](https://github.com/inspireui/support/files/3478555/MyListing.js.zip)

**Comment by thangvo9x** [comment]
Hi. You must have provided me the AppConfig to know about your domain.

**Comment by bobozd** [comment]
here it is
[AppConfig.json.zip](https://github.com/inspireui/support/files/3483031/AppConfig.json.zip)

**Comment by bobozd** [comment]
please solve the problem urgently

**Comment by thangvo9x** [comment]
Hi bro. You could try to replace this file at Components/HorizonList/
[styles.txt](https://github.com/inspireui/support/files/3490964/styles.txt)
Remember change from .txt tag -> .js tag because the github isn't uploading from .js tag. Hope you see. Thanks

**Comment by bobozd** [comment]
Thanks it works.

ANOTHER BUG:
Text in front of top hero image dissapear when you scroll to the top of the
home screem, and it pops up when you scroll down.
Please fix disappear when you are on th top of the screen.

VIDEO:
https://drive.google.com/file/d/1-1w_vw_ZivwjX4Fy3UHVzpL0LN_d_9tw/view?usp=sharing

**Comment by thangvo9x** [comment]
Hi. Replace this file at container/Home/Header/
change  from .txt to
[index.txt](https://github.com/inspireui/support/files/3495034/index.txt)
 .js tag 
Thanks

**Comment by bobozd** [comment]
hello,

now when I click on second footer icon on the bottom (location icons - search on map) application restarted and I got this screen in simulator. 
![Screen Shot 2019-08-15 at 14 11 02](https://user-images.githubusercontent.com/28021993/63093771-b83bb180-bf66-11e9-83cd-01852193ca39.png)
Previously I have unwanted 29EUR text that I removed following this thread:
https://github.com/inspireui/support/issues/524#issuecomment-486203173

what I missed?

**Comment by thangvo9x** [comment]
Hi bro. Please keep to your video screenshot for that problem to check. Thanks
