### ISSUE TITLE
FluxStore Woocommerce

### ISSUE THREAD

**Issue by jakkumarket** [inspireui/support#893]
Hello,

I am having a lot of trouble setting up Woocommerce with FluxStore. I've followed all of the instructions, however the lib folder does not populate everything which causes issues. I've tried manually adding the files, but then none of the imports can be found. Is there an easy fix to this?

**Comment by minhcasi** [comment]
Hi, could you help to provide some info below:

1. You screenshot purchase to verify the product from - https://codecanyon.net/downloads

2. Please send us the screenshot of the issue when you run the app from Android Studio.

3. Could you able to run this example from Flutter - https://flutter.dev/docs/get-started/test-drive ?
