### ISSUE TITLE
Publishing to channel ‘default’... Error: Problem validating asset fields in app.json. See https://docs.expo.io/ • Field: icon – cannot access file at ’./assets/icons/app.png’. • Field: splash.image – cannot access file at ’./assets/splash.png’. Couldn’t publish because errors were found. (See logs above.) Please fix the errors and try again.

### ISSUE THREAD

**Issue by joelycineas** [inspireui/support#894]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue

I am getting this error when i click on Build IOS On CE Builder Can You Please Check It Out

Publishing to channel ‘default’... Error: Problem validating asset fields in app.json. See https://docs.expo.io/ • Field: icon – cannot access file at ’./assets/icons/app.png’. • Field: splash.image – cannot access file at ’./assets/splash.png’. Couldn’t publish because errors were found. (See logs above.) Please fix the errors and try again.

2. Screenshots

3. My screenshot of the purchase product or my comment:

3. Config files (optional)

**Comment by theAlinux** [comment]
check this image file, is it exists => ./assets/icons/app.png and ./assets/splash.png

**Comment by joelycineas** [comment]
Thank you so much for the reply, but They do exist and I still constantly get errors.

**Comment by thangvo9x** [comment]
Hi. Check app.png and splash.png is valid. If it still is showing, the problem could the image is not valid.

**Comment by minhcasi** [comment]
@joelycineas - noted, could you try to share your image so that we could have a check or zip your whole project and share to our email support@inspireui.com - thank you!
