### ISSUE TITLE
[my-product] - mstore-expo

### ISSUE THREAD

**Issue by abdalrhmanattia** [inspireui/support#895]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue

cannot  new register user from app  but facebook register work 
i used last version of app working on expo version android 

2. Screenshots

![Untitled-2 png3](https://user-images.githubusercontent.com/49997361/62711168-da7a8000-b9f8-11e9-8ba7-776ce6861cd1.png)

3. My screenshot of the purchase product or my comment:

3. Config files (optional)

**Comment by minhcasi** [comment]
Hi, please double-check the list requite active plugin from this guide - https://docs.inspireui.com/mstore/wordpress-setting/ - also some extra config from wordpress - thank you!

**Comment by abdalrhmanattia** [comment]
i cheek every think an start every think for beginning put the same problem is still  
i think app still need developer skill can i apply refund plz

**Comment by minhcasi** [comment]
Hi, you can process on this link - https://shrtm.nu/XwHU - thanks
