### ISSUE TITLE
[my-product] - mstore-expo

### ISSUE THREAD

**Issue by abdalrhmanattia** [inspireui/support#896]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue
confirm order not work when I press the confirm order button the text appear on the button is changed to loading but again confirm order appear and order does not place
i used last version of app mstore-expo 
2. Screenshots

![Untitled Project44571e autosave](https://user-images.githubusercontent.com/49997361/62709958-b87ffe00-b9f6-11e9-8cc1-fac46ef9d636.gif)

3. My screenshot of the purchase product or my comment:

3. Config files (optional)

**Comment by minhcasi** [comment]
Hi, it seems the issue caused by modifying the Delivery Address that not enough require info to create the Order. Could you try to install this debug tools - https://github.com/infinitered/reactotron/blob/master/docs/installing.md - and see the detail log after tap the Order button ?

**Comment by leghost** [comment]
i’m facing an issue. i’m getting error when trying to set up the app with Android studio.

“org.gradle.execution.MultipleBuildFailures: Build completed with 1 failures. at org.gradle.initialization.DefaultGradleLauncher$ExecuteTasks.run(DefaultGradleLauncher.java:386) at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:301) at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:293) ..... ” this for the runing task in the building process

“error: cannot find symbol method setEnableInitialSmsButton(boolean) ” this one in the Java compiler

please have a look on it. Thanks


![image](https://user-images.githubusercontent.com/47028114/62832290-2103f080-bc2c-11e9-9d3e-0fa2a3a4bf2e.png)

**Comment by sackmotion** [comment]
leghost , your issues looks related to : 
https://github.com/underscopeio/react-native-facebook-account-kit/issues/195

is with 3.9.2 or below ? Upgrade to 3.9.3 , it's fixed there.

Good luck !

**Comment by abdalrhmanattia** [comment]
i think app still need developer skill can i apply refund plz
