### ISSUE TITLE
[Listapp] - setting category for post & making comment to be off by default

### ISSUE THREAD

**Issue by mmubeennisar** [inspireui/support#897]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue
I want to make set category for post & make commenting off by defauly
2. Screenshots
<img width="1002" alt="Screenshot 2019-08-08 at 7 30 29 PM" src="https://user-images.githubusercontent.com/28184542/62711870-3ce07a00-ba13-11e9-9bca-5751e4bcc435.png">

3. My screenshot of the purchase product or my comment:

3. Config files (optional)

**Comment by thangvo9x** [comment]
Hi. This is out of scope support but you must customize the plugin JSON-API. It will be affected on your website. Thanks.
