### ISSUE TITLE
[Fluxstore Pro] - Please address my issues

### ISSUE THREAD

**Issue by shafirmubarak** [inspireui/support#898]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue

I am facing the following issues - 
  1) While trying to register am getting the below error, screenshot attached. I see that another user has reported the same issue and you have mentioned it will be fixed in the next release. However we are going live soon, so any temporary fix (like suggesting me to edit the issue part of the code) you provide will be much appreciated  -

   2) By default, All COD order goes to completed status as soon as it is ordered.  However, we want it to be "Pending payment" and then once order delivered we will manually mark it as completed. Could you help with how to achieve this? 
I remember there was this same query in Mstore pro and the suggested solution was to set_paid to false. I tried that here and then the order never goes through and i get a failure message saying something wrong with the params. Kindly help with this.

2. Screenshots
![registration_error](https://user-images.githubusercontent.com/53738841/62718844-48886c80-ba24-11e9-9835-f8680da2a515.jpeg)

3. My screenshot of the purchase product or my comment:

![image](https://user-images.githubusercontent.com/53738841/62719472-b5503680-ba25-11e9-9431-89eaa053d11d.png)

3. Config files (optional)

**Comment by minhcasi** [comment]
Hi, thank you for reporting, we have fixed this issue, it will be updated new version on this weekend - thank you!

**Comment by shafirmubarak** [comment]
Thanks, Could you confirm if both of the issues highlighted above will be fixed in this weekend's release?

**Comment by minhcasi** [comment]
Hi, confirmed this is fixing, and we are uploading for delivery, it will be available on tomorrow - thank you !

**Comment by minhcasi** [comment]
Hi, please help to download the latest 1.4.0 for fixing the issue - thank you!
