### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by Pars1vaLl** [inspireui/support#9]
**Mandatory Info (please complete the following information):**
 - Product:  ListApp
 - Purchased Code: 85059e37-2ddd-478d-899b-6db006280782

**Describe the issues**
Hi!
Can`t run "yarn install" /"npm install" in console. I try to do it from ListApp directory. (First screen)
Expo cli can`t run an emulator in custom project, however I did everything as in docs. Or,maybe, there is some changes? If yes, could you please help me with start. It is about a week I am facing this issues. (Second Screen)

Thanks

**Screenshots**
[Screen](http://prntscr.com/li37wk)
[Screen_2](http://prntscr.com/li3a3l)

**Additional context**
2: Couldn't start project on Android: could not install *smartsocket* listener: cannot bind to 127.0.0.1:5037: Обычно разрешается только одно использ��вание адреса со��ета (протокол/сетевой адрес/порт). (10048)
could not read ok from ADB Server
* failed to start daemon *
error: cannot connect to daemon

**Comment by hammadhassan** [comment]
First install yarn & nodejs.

Then run `npm install -g react-native-cli`

**Comment by ZamsiteZambia** [comment]
Parsival0,

Have you tried the commands from the 'source' directory?

**Comment by Parsival0** [comment]
> Parsival0,
> 
> Have you tried the commands from the 'source' directory?

**Comment by Parsival0** [comment]
> Parsival0,
> 
> Have you tried the commands from the 'source' directory?

Hi. 
Yes, I`have tried, but have the same issue.  ![Issues](/images/logo.png)
Format: ![Screen](https://ru.files.fm/u/d3477bzz)
-------------------------------------------------------------------

**Comment by Parsival0** [comment]
Here are yarn logs:

Arguments: 
  C:\Program Files\nodejs\node.exe C:\Program Files\Yarn\bin\yarn.js init

PATH: 
  C:\Python27\;C:\Python27\Scripts;C:\ProgramData\Boxstarter;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\ProgramData\chocolatey\bin;C:\Program Files\Yarn\bin\;C:\Program Files\nodejs\;C:\Users\Dragornborn\AppData\Local\Yarn\bin;C:\Users\Dragornborn\AppData\Roaming\npm

Yarn version: 
  1.12.3

Node version: 
  11.1.0

Platform: 
  win32 ia32

Trace: 
  Error: canceled
      at Interface.<anonymous> (C:\Program Files\Yarn\lib\cli.js:125278:13)
      at Interface.emit (events.js:182:13)
      at Interface._ttyWrite (readline.js:793:16)
      at ReadStream.onkeypress (readline.js:178:10)
      at ReadStream.emit (events.js:182:13)
      at emitKeys (internal/readline.js:424:14)
      at emitKeys.next (<anonymous>)
      at ReadStream.onData (readline.js:1030:36)
      at ReadStream.emit (events.js:182:13)
      at addChunk (_stream_readable.js:283:12)

npm manifest: 
  {
    "name": "listapp",
    "version": "v1.5.1",
    "description": "ListApp",
    "author": "InspireUI",
    "private": true,
    "main": "node_modules/expo/AppEntry.js",
    "scripts": {
      "start": "expo start",
      "android": "expo start --android",
      "ios": "expo start --ios",
      "eject": "expo eject",
      "setup": "./scripts/setup.sh",
      "detach": "./scripts/detach.sh"
    },
    "dependencies": {
      "@appandflow/masonry-list": "^0.4.0",
      "api-ecommerce": "^0.0.16",
      "axios": "^0.18.0",
      "base-64": "^0.1.0",
      "create-react-class": "^15.6.2",
      "crypto-js": "^3.1.9-1",
      "currency-formatter": "^1.5.3",
      "emoji-utils": "^1.0.1",
      "expo": "^31.0.4",
      "expo-analytics": "^1.0.7",
      "firebase": "5.5.8",
      "hoist-non-react-statics": "^3.0.1",
      "html-entities": "^1.2.1",
      "lodash": "^4.17.4",
      "moment": "^2.19.1",
      "oauth-1.0a": "1.0.1",
      "prop-types": "^15.6.0",
      "react": "16.5.0",
      "react-native": "https://github.com/expo/react-native/archive/sdk-31.0.1.tar.gz",
      "react-native-animatable": "^1.2.4",
      "react-native-button": "^2.3.0",
      "react-native-calendars": "^1.21.0",
      "react-native-dates": "^2.0.4",
      "react-native-dropdownalert": "3.7.0",
      "react-native-gifted-chat": "^0.4.3",
      "react-native-image-carousel": "^0.4.4",
      "react-native-invertible-scroll-view": "^1.1.0",
      "react-native-keyboard-aware-scroll-view": "0.7.4",
      "react-native-map-link": "2.1.1",
      "react-native-modal-datetime-picker": "6.0.0",
      "react-native-modalbox": "^1.4.2",
      "react-native-onesignal": "3.2.8",
      "react-native-parallax": "^0.3.0",
      "react-native-progress-bar-animated": "^1.0.6",
      "react-native-render-html": "^3.5.0",
      "react-native-safe-area-view": "^0.11.0",
      "react-native-scrollable-tab-view": "0.10.0",
      "react-native-slider": "0.11.0",
      "react-native-snap-carousel": "3.7.5",
      "react-native-star-rating": "^1.1.0",
      "react-native-swipe-list-view": "^1.3.1",
      "react-native-swipeout": "^2.3.6",
      "react-native-swiper": "^1.5.13",
      "react-native-tag-select": "^2.0.0",
      "react-native-textinput-effects": "^0.4.2",
      "react-native-timeago": "^0.4.0",
      "react-navigation": "2.18.2",
      "react-redux": "5.1.0",
      "react-timer-mixin": "^0.13.3",
      "react-tween-state": "^0.1.5",
      "redux": "4.0.1",
      "redux-persist": "^5.6.5",
      "redux-thunk": "^2.2.0",
      "sanitize-html": "1.19.1",
      "sentry-expo": "1.10.0",
      "tcomb-form-native": "^0.6.20",
      "urijs": "^1.19.0",
      "url": "^0.11.0",
      "util": "0.11.1",
      "validate.js": "^0.12.0",
      "wpapi": "^1.1.2",
      "xdate": "^0.8.2"
    },
    "devDependencies": {
      "@babel/core": "^7.0.0",
      "@babel/preset-env": "^7.0.0",
      "babel-jest": "23.6.0",
      "babel-plugin-module-resolver": "^3.1.1",
      "babel-preset-expo": "^5.0.0",
      "babel-preset-react-native": "4.0.1",
      "path": "^0.12.7",
      "reactotron-react-native": "^2.1.0",
      "reactotron-redux": "^2.1.0"
    }
  }

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile

**Comment by Parsival0** [comment]
My logs. @luyx2412 and InsipreUi team, please help me to solve this problem.
[yarn-error.log](https://github.com/inspireui/support/files/2589695/yarn-error.log)

**Comment by minhcasi** [comment]
Hi @Pars1vaLl we have just found out this cause by the yarn issue on window OS which could not download the git URL, please try to reinstall the git and set the PATH environment then it will be fixed, please have a look to this issues:

https://github.com/yarnpkg/yarn/issues/3102
https://github.com/zeit/now-cli/issues/1661

Please reopen if you still could not fix the issue - thank you!

**Comment by jane207593** [comment]
When i want to run app using CeBuilder then before connecting app is disconnected!
and if i want to install npm packages always find this error.
![image](https://user-images.githubusercontent.com/47419219/52414156-5ad12e80-2b05-11e9-9319-6600ea8a3f9c.png)
![image](https://user-images.githubusercontent.com/47419219/52414425-172af480-2b06-11e9-939d-8b4a2ac37c7a.png)
![image](https://user-images.githubusercontent.com/47419219/52414509-5eb18080-2b06-11e9-879b-e74205aa84dc.png)
![image](https://user-images.githubusercontent.com/47419219/52414618-a506df80-2b06-11e9-89a8-72ef6c78db6a.png)
