### ISSUE TITLE
[Mstore Multi Vendor] - help changeing country and deafult currency

### ISSUE THREAD

**Issue by alaradi2006** [inspireui/support#90]
**Mandatory Info (please complete the following information):**
 - Product: [e.g. MStore, ListApp]
 - Your Purchased Code: [get from https://codecanyon.net/downloads]
(we may not reply if you are not our customer)

**Describe the issues**
i want to change deafult currency from usd to BHD 
and deafult country from us to bahrain 
**Screenshots**

**Additional context**
Add any other detail logs about the problem here.
DefaultCurrency: {
    symbol: "$",
    name: "US Dollar",
    code: "USD",
    name_plural: "US dollars",
    decimal: ".",
    thousand: ",",
    precision: 2,
    format: "%s%v", // %s is the symbol and %v is the value
  },
  DefaultCountry: {
    code: 'en',
    RTL: false, 
    language: 'English',
    countryCode: "US",

**Comment by alaradi2006** [comment]
i tried to change it but i got error in format and symbol 
i want to make deafult country bahrain 
deafult currency BHD

**Comment by luyx2412** [comment]
Hi @alaradi2006 Can you take the screenshot about symbol error?
Thanks

**Comment by minhcasi** [comment]
@luyx2412  related private info here - https://app.intercom.io/a/apps/xro9xnfd/inbox/inbox/2667041/conversations/19910216862

**Comment by luyx2412** [comment]
HI @alaradi2006, In your Config.js file. Please change the value `hideCountryList: true` to disable country list and set default country.
Thanks

**Comment by alaradi2006** [comment]
whats country code for bahrain

**Comment by alaradi2006** [comment]
how to change currency to my country bahrain

**Comment by luyx2412** [comment]
HI @alaradi2006 Please search google about your country code https://goo.gl/m2jjx6.
Thanks

**Comment by alaradi2006** [comment]
i know my country code but what tp but in config code for currency format and value

**Comment by alaradi2006** [comment]
format: "%s%v", // %s is the symbol and %v is the value
},

**Comment by luyx2412** [comment]
Hi @alaradi2006 You can read the document about currency and value in this article https://www.npmjs.com/package/currency-formatter#advanced-usage
Thanks

**Comment by alaradi2006** [comment]
another problem 
if i sign up as vendor in mobile app 
the registration became as subscriber in wordpress user list

**Comment by thangvo9x** [comment]
Hi. How are you ? Send help me your Config.js file . I'll check help you.

**Comment by alaradi2006** [comment]
give me your email will send it to you

**Comment by thangvo9x** [comment]
thang@beostore.io
Please note your issue such as marked important :)

**Comment by alaradi2006** [comment]
i tried to send you email i got this problem 

Your message wasn't delivered because the destination email system rejected your message for security or policy reasons. For example, the email address might only accept messages from certain senders, or it might not accept certain types of messages, like those larger than a specific size.

**Comment by minhcasi** [comment]
@alaradi2006 try to upload the js file to cloud (dropbox) or past it to gist

**Comment by alaradi2006** [comment]
can you give my skype account to add you as it will be more easy to fix the issues and send the files

**Comment by alaradi2006** [comment]
another problem
if i sign up as vendor in mobile app
the registration became as subscriber in wordpress user list



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
