### ISSUE TITLE
[ListPro] - uncaught error api key not found 

### ISSUE THREAD

**Issue by theAlinux** [inspireui/support#901]
//AppConfig
"url": "http://bestrestaurants.directory",
    "consumerKey": "ck_2b041d0b13d3ae4d883c******************",
    "consumerSecret": "cs_8dd2033fdbc3fbf58f27*******************"

//index.js
 Google: {
    mapApi: 'AIzaSyDQIbsz2wF*****************',
    searchCountry: 'gb',

ListPro version: 1.3.5

it has not AndroidManifest.xml file or i don't found

![Ekran Alıntısı](https://user-images.githubusercontent.com/10341948/62804456-0a5b7d80-baf6-11e9-9be8-49a30e009c32.PNG)

i created and used Geocoding api and places api but get this error???

**Comment by thangvo9x** [comment]
Hi. Where did was the error from, please describe more detail?

**Comment by theAlinux** [comment]
get this error after than i clicked Map icon, but only real device, not error emulator

**Comment by theAlinux** [comment]
//app.json

"android": {
      "package": "com.best.restaurants.uk.gb",
      "versionCode": 6,
      "googleServicesFile": "./release/google-services.json",

       //added this line for error fixes and fixed
      "config": { "googleMaps": { "apiKey": "AIzaSyCHLHnlbp**********************" } }
    }
