### ISSUE TITLE
[Fluxstore Pro] - Pre Sale questions

### ISSUE THREAD

**Issue by Pars1vaLl** [inspireui/support#902]
Hi team,

Fluxstore Pro looks great! We have some pre-sale questions, kindly ask you answer to them:

1. Can the price be related to size? F.e. there is a Shirt with 'S' size and it costs 10$. So when I choose 'XL' price changes to 15$. Is it possible to achieve this in without custom work?

2. What is your recommendations for hosting? Is it fine if we use Shared-hosting on Ubuntu? Does this App needs any specific requirements from hosting?

3. Do you  offer installation services? If yes, how much it will cost and will it include publishing to Google Play and App Store?

4. Is it possible to add "Payment on delivery" option?

Thanks=))

**Comment by minhcasi** [comment]
Hi, thank you for your questions

1. it's good news that this dynamic product variant is already supported on latest release 1.3 and some new bugfix on latest 1.4, this feature is the first available for Woocommerce, then we will update for Magento and Opencart later

2. we use 5usd/month on the Digital ocean for the demo and it still works very fast, so there is not required for the hosting, but some hosting for the Magento should be considered.

3. Yes, please share your detail to support@inspireui.com, we need to check the integration first.

4. There is already COD feature, Cash On Delivery
