### ISSUE TITLE
[ListPro] - Close Modal?

### ISSUE THREAD

**Issue by theAlinux** [inspireui/support#903]
Why does not close the login modal/window when a successful message returns?

**Comment by thangvo9x** [comment]
Could you share the Appconfig for checking?

**Comment by theAlinux** [comment]
//AppConfig

{
  "Website": {
    "url": "http://bestrestaurants.directory",
    "consumerKey": "ck_2b041d0b13d3ae4d883c83dfb7*************",
    "consumerSecret": "cs_8dd2033fdbc3fbf58f27780a3**************"
  },
  "Theme": "restaurant",
  "MainColor": {
    "tabbarTint": "rgb(27, 229, 141)",
    "tabbarColor": "#D5D8DE",

    "mainColorTheme": "rgb(27, 229, 141)",
    "tabbar": "#FFF"
  }
}

**Comment by theAlinux** [comment]
i am bored, do it please, i send login information to your email with app file
be dynamic with the same local settings, error-free, I've been dealing with it for a long time now
