### ISSUE TITLE
[BeoNews Pro - React Native mobile app for Wordpress] - Unable to load my site into the app

### ISSUE THREAD

**Issue by sgkalyans** [inspireui/support#904]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue
Unable to load my site into the app. Please see the attached screenshot.

Is there any updated documentation for the app ? I don't see any guide on explaining about the configuration of the app to change the layout, list of categories, etc.,

2. Screenshots
![image](https://user-images.githubusercontent.com/2780305/62819313-ff502e00-bb85-11e9-8cba-3ef6e4789224.png)

3. My screenshot of the purchase product or my comment:
![image](https://user-images.githubusercontent.com/2780305/62819325-2444a100-bb86-11e9-956f-159cd35ae09d.png)

3. Config files (optional)

**Comment by minhcasi** [comment]
Hi, could you help to check some require plugins for the app - https://docs.inspireui.com/beonews/wordpress-setting/ - thank you!

**Comment by sgkalyans** [comment]
I already have the required plugins.

Please note the following:
json-api - This plugin was closed on August 7, 2019 and is no longer available for download.

**Comment by sgkalyans** [comment]
And simple question, how to change the "BeoFoods" to my app name ? I'm reading codes and website but no information on this.

**Comment by minhcasi** [comment]
Hi, pls help to check this guide to change the app name - https://docs.inspireui.com/beonews/delivery/ -thank you!
