### ISSUE TITLE
[ListApp] Adding Listing does not show relevant fields

### ISSUE THREAD

**Issue by serwadda** [inspireui/support#905]
Hello, 
When adding listings I don't get the relevant options to select like Category and Region..I am able only to do the following: Select Listing type, Input Listing title, Add single listing image and Input listing detail.
I am not able to select the Categories and Regions. 
 Please help

**Comment by thangvo9x** [comment]
Could you share the AppConfig file for checking?

**Comment by serwadda** [comment]
Please find attached for your action

Thanks

**Comment by thangvo9x** [comment]
Ah huh? For adding them. You must have to customize it. Thanks

**Comment by serwadda** [comment]
I am completely new with React and React Native, but I can dig right in if you can offer some clues on the customization. I.e. a walkthrough on what to customize and where. Thanks

**Comment by thangvo9x** [comment]
You can go to containers folder at Theme/youtheme/PostNewListing/index.js
You can add more fields or do anything in the case.

**Comment by serwadda** [comment]
Thanks Tony..let me see what to do.
