### ISSUE TITLE
ListApp & ListPro

### ISSUE THREAD

**Issue by Suhaibaj** [inspireui/support#906]
Hi Team ,
i have a qustion about listApp and ListPro
Is it compatible with this template?
https://themeforest.net/item/food-guide-restaurant-food-and-drinks-directory-listing-wordpress-theme/17090002
And if you link it to a site based on this template
Will certain problems appear?

thanks,

**Comment by minhcasi** [comment]
Hi, it's not compatible with this template, but we will investigate the solution in next coming flutter project, if you are interested, we will keep an updated status - thank you!

**Comment by Suhaibaj** [comment]
What templates are compatible with it ?
