### ISSUE TITLE
[Mstore Multistore Vendor] Fresh Install

### ISSUE THREAD

**Issue by Pankti16** [inspireui/support#908]
1. Hello,
I am getting this error when I click on the category
CeBuilder version: 0.35.0
Multistore Vendor version: 1.3.1

2. 
![photo6188211364686833829](https://user-images.githubusercontent.com/28388925/62845045-0d679100-bce3-11e9-9100-2387e3bfd8ac.jpg)

3. purchase code: 002e8ddf-504e-4d29-970c-04716acb1734

3. 
[Config.zip](https://github.com/inspireui/support/files/3491001/Config.zip)

**Comment by thangvo9x** [comment]
Try to replace this file at containers/Category/
[index.txt](https://github.com/inspireui/support/files/3491269/index.txt)
 Because the github isn't allowed upload .js file. you should change to .js tag

**Comment by Pankti16** [comment]
Hello,
Thanks for your reply
it is giving me Unable to resolve "./ProductRow" from "src\containers\Categories\index.js" error.

**Comment by Pankti16** [comment]
Thanks for your reply
it is giving me Unable to resolve "./ProductRow" from
"src\containers\Categories\index.js" error.

**Comment by thangvo9x** [comment]
Hi bro. You missed. path must have Category in containers folder. NOT Categories.

**Comment by Pankti16** [comment]
Yeah, Sorry.
My bad. It fixed the issue.

Thanks

**Comment by Pankti16** [comment]
Yeah, Sorry.
My bad. It fixed the issue.

Thanks
