### ISSUE TITLE
[fluxstore] - Oops; flutter has exited unexpectedly.

### ISSUE THREAD

**Issue by AlaaKriedy** [inspireui/support#909]
I have this message when I run app 

Oops; flutter has exited unexpectedly.
Crash report written to F:\programer\codecanyon-WG8lwxQX-fluxstore-the-universal-woocommerce-magento-opencart-mobile-app-by-flutter-framework\FluxStore 1.3.5\source\flutter_12.log;
please let us know at https://github.com/flutter/flutter/issues.

FAILURE: Build failed with an exception.

* Where:
Script 'F:\flutter\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 665

* What went wrong:
Execution failed for task ':app:compileflutterBuildDebugX64'.
> Process 'command 'F:\flutter\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 53s
Finished with error: Gradle task assembleDebug failed with exit code 1

---------

and attach the log in attachment 
[flutter_12.log](https://github.com/inspireui/support/files/3492689/flutter_12.log)

**Comment by jakkumarket** [comment]
Having the same issue here for the most part

**Comment by minhcasi** [comment]
@AlaaKriedy @jakkumarket could I check if you are using the window 10?

**Comment by AlaaKriedy** [comment]
@minhcasi  , yes , I'm using windows 10

**Comment by jakkumarket** [comment]
Yes I'm using Windows 10 as well


-------- Original message --------

**Comment by minhcasi** [comment]
Hi, could you help to try with latest version 1.4.0

**Comment by jakkumarket** [comment]
@minhcasi How do we even update without overwriting everything?

**Comment by minhcasi** [comment]
Hi, there is also new 1.4.2 - please keep the update

There is not the good way so far, the usual method overrides the latest package with your modify code, and config - thank you!
