### ISSUE TITLE
[Listapp] - Generated apk through expo build command Crashes

### ISSUE THREAD

**Issue by kbroscbe123** [inspireui/support#910]
Hi,

1. Categories names are not displaying in home, when we use "category links" in app home
2. App crashes, while we click on individual listing (Generated apk)
please advise on the above issues

[AppConfig.json.zip](https://github.com/inspireui/support/files/3492851/AppConfig.json.zip)
[Config.zip](https://github.com/inspireui/support/files/3492853/Config.zip)
below is the link for my comment
http://tiny.cc/pb92az

Thanks

**Comment by kbroscbe123** [comment]
hello, I have been waiting for the past 2 days, no reply yet

**Comment by kbroscbe123** [comment]
hello, I am not getting any reply from your end

**Comment by minhcasi** [comment]
Hi @kbroscbe123 sorry for the late response, @thangvo9x  is checking the issue will get back you shortly - thank you!

**Comment by kbroscbe123** [comment]
okay, thanks. looking forward

**Comment by thangvo9x** [comment]
Could you screenshot for that problem help me?
Thanks

**Comment by kbroscbe123** [comment]
I am sending the apk link. issue is only with generated apk and it works well with expo client
https://mega.nz/#!hZN0kAJR!kOThxmR5oTdlqIjSA85cw9HcEBkSzkCm6apxJu6vz2E

**Comment by kbroscbe123** [comment]
below is the video describing the issues, it would be helpful for you
https://mega.nz/#!5I9C1KgY!IpXXANGYmLPPY9l45kN44TEDdqQeRZ7CVdvmEiuT-WY

**Comment by kbroscbe123** [comment]
hi, any chance to solve the issue. Thanks

**Comment by kbroscbe123** [comment]
Hi there, looking forward for the fix

**Comment by kbroscbe123** [comment]
I fixed the crash by adding google map api key to app.json.

**Comment by thangvo9x** [comment]
Thanks very much. Appreciate it.
