### ISSUE TITLE
[List-App] - this.props/fetchPayments is not a function and Listing not being displayed on Android

### ISSUE THREAD

**Issue by arjunchopra35** [inspireui/support#911]
1. My issue
I have two major issues.
1) I get the error this.props.fetchPayments is not a function when booking a service. The first screen works fine but after selecting date and time and clicking on next, I get this error

![Screen Shot 2019-08-13 at 3 17 52 AM](https://user-images.githubusercontent.com/19815604/62922321-1acf5a80-bd79-11e9-961a-a37fa66a3eb6.png)

2) The listing I have created is being displayed on Iphone emulator but not on android!
![Screen Shot 2019-08-13 at 3 20 31 AM](https://user-images.githubusercontent.com/19815604/62922430-59fdab80-bd79-11e9-90b4-59ef257b404b.png)

3. My screenshot of the purchase product or my comment:

![Screen Shot 2019-08-13 at 3 25 04 AM](https://user-images.githubusercontent.com/19815604/62922690-fd4ec080-bd79-11e9-861c-7c5f5abb4f08.png)

3. Config files (optional)

**Comment by arjunchopra35** [comment]
I would really appreciate some help here! It's been two days. Please let me know what files do you need from me to look into the issues!

**Comment by thangvo9x** [comment]
Hi. Could you share the AppConfig file for checking?
Thanks.

**Comment by arjunchopra35** [comment]
{
  "Website": {
    "url": "http://localhost:8888/goodlooks",
    "consumerKey": "ck_8b0523cd72cfd64346bd348abbf5bcd9c0f4826b",
    "consumerSecret": "cs_974dbe2c792946b7a7a4f4f63c3b051fdb61e8f1"
  },
  "Theme": "listable",
  "MainColor": {
    "tabbarTint": "#00B2BC",
    "tabbarColor": "#D5D8DE",
    "mainColorTheme": "#00B2BC",
    "tabbar": "#fff"
  }
}

**Comment by arjunchopra35** [comment]
<img width="1351" alt="Screen Shot 2019-08-15 at 3 32 59 AM" src="https://user-images.githubusercontent.com/19815604/63079822-69adf900-bf0d-11e9-90c4-6e4a67413348.png">
Do you need me to make it live on a server?

**Comment by thangvo9x** [comment]
Yup. I can't check on this your localhost.

**Comment by arjunchopra35** [comment]
I will make it live within 24 hours, reciprocate the issues and get back to you.
