### ISSUE TITLE
[my-product] - beonews-pro

### ISSUE THREAD

**Issue by amit81** [inspireui/support#912]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue : lottie-react-native:compileDebugJavaWithJavac FAILED

2. Screenshots

3. My screenshot of the purchase product or my comment:

3. Config files (optional)

**Comment by minhcasi** [comment]
Hi, could you help to take the screenshot of your purchased product, also send us the whole screenshot of this issue, thank you!

**Comment by amit81** [comment]
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

info Starting JS server...
info Building and installing the app on the device (cd android && gradlew.bat app:installDebug)...
Starting a Gradle Daemon, 1 busy and 1 incompatible and 1 stopped Daemons could not be reused, use --status for details

> Configure project :react-native-webview
:react-native-webview:reactNativeAndroidRoot C:\Users\Amit Sanghvi\Documents\Beo News\BeoNews.3.0.4\beonews-pro\node_modules\react-native\android

> Configure project :react-native-blur
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

> Configure project :react-native-admob
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

> Configure project :lottie-react-native
publishNonDefault is deprecated and has no effect anymore. All variants are now published.

> Task :react-native-admob:compileDebugJavaWithJavac
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
C:\Users\Amit Sanghvi\Documents\Beo News\BeoNews.3.0.4\beonews-pro\node_modules\react-native-admob\android\src\main\java\com\sbugert\rnadmob\RNAdMobBannerViewManager.java:3: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
C:\Users\Amit Sanghvi\Documents\Beo News\BeoNews.3.0.4\beonews-pro\node_modules\react-native-admob\android\src\main\java\com\sbugert\rnadmob\RNAdMobInterstitialAdModule.java:5: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
C:\Users\Amit Sanghvi\Documents\Beo News\BeoNews.3.0.4\beonews-pro\node_modules\react-native-admob\android\src\main\java\com\sbugert\rnadmob\RNAdMobRewardedVideoAdModule.java:5: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
C:\Users\Amit Sanghvi\Documents\Beo News\BeoNews.3.0.4\beonews-pro\node_modules\react-native-admob\android\src\main\java\com\sbugert\rnadmob\RNPublisherBannerViewManager.java:3: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
C:\Users\Amit Sanghvi\Documents\Beo News\BeoNews.3.0.4\beonews-pro\node_modules\react-native-admob\android\src\main\java\com\sbugert\rnadmob\RNAdMobBannerViewManager.java:146: error: cannot find symbol
  @Nullable
   ^
  symbol:   class Nullable
  location: class RNAdMobBannerViewManager
C:\Users\Amit Sanghvi\Documents\Beo News\BeoNews.3.0.4\beonews-pro\node_modules\react-native-admob\android\src\main\java\com\sbugert\rnadmob\RNAdMobInterstitialAdModule.java:82: error: cannot find symbol
  private void sendEvent(String eventName, @Nullable WritableMap params) {
                                            ^
  symbol:   class Nullable
  location: class RNAdMobInterstitialAdModule
C:\Users\Amit Sanghvi\Documents\Beo News\BeoNews.3.0.4\beonews-pro\node_modules\react-native-admob\android\src\main\java\com\sbugert\rnadmob\RNAdMobRewardedVideoAdModule.java:97: error: cannot find symbol
    private void sendEvent(String eventName, @Nullable WritableMap params) {
                                              ^
  symbol:   class Nullable
  location: class RNAdMobRewardedVideoAdModule
C:\Users\Amit Sanghvi\Documents\Beo News\BeoNews.3.0.4\beonews-pro\node_modules\react-native-admob\android\src\main\java\com\sbugert\rnadmob\RNPublisherBannerViewManager.java:149: error: cannot find symbol
  @Nullable
   ^
  symbol:   class Nullable
  location: class RNPublisherBannerViewManager
C:\Users\Amit Sanghvi\Documents\Beo News\BeoNews.3.0.4\beonews-pro\node_modules\react-native-admob\android\src\main\java\com\sbugert\rnadmob\RNAdMobRewardedVideoAdModule.java:20: error: RNAdMobRewardedVideoAdModule is not abstract and does not override abstract method onRewardedVideoCompleted() in RewardedVideoAdListener
public class RNAdMobRewardedVideoAdModule extends ReactContextBaseJavaModule implements RewardedVideoAdListener {
       ^
9 errors
3 warnings

>###  **Task :react-native-admob:compileDebugJavaWithJavac FAILED**

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-admob:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1m 39s
42 actionable tasks: 1 executed, 41 up-to-date
error Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html
error Command failed: gradlew.bat app:installDebug. Run CLI with --verbose flag for more details.
PS C:\Users\Amit Sanghvi\Documents\Beo News\BeoNews.3.0.4\beonews-pro>

**Comment by amit81** [comment]
**Task :react-native-admob:compileDebugJavaWithJavac FAILED**
![Screenshot (93)](https://user-images.githubusercontent.com/11808338/63252221-0ca79f80-c28d-11e9-8d57-6c8086b41445.png)

**Comment by amit81** [comment]
**Task :react-native-admob:compileDebugJavaWithJavac FAILED**
![Screenshot (94)](https://user-images.githubusercontent.com/11808338/63252361-4d071d80-c28d-11e9-84f8-a4a54dbc5322.png)

**Comment by amit81** [comment]
**Task :react-native-admob:compileDebugJavaWithJavac FAILED**
![beenewspur](https://user-images.githubusercontent.com/11808338/63252811-2dbcc000-c28e-11e9-9501-9eaf9eac1cce.JPG)

**Comment by minhcasi** [comment]
@amit81 - could you help to run the project manually with this script, from the project folder run:

yarn install && yarn start --reset-cache
react-native run-ios 
// or react-native run-android

Please try the virtual host instead of using localhost/wordpress ( as the api could fail return on this case, thank you)
