### ISSUE TITLE
[Fluxstore] Cambio el enlace de la imagen y no se visualiza en Horizontal Home Page

### ISSUE THREAD

**Issue by urphilita** [inspireui/support#913]
Realizando cambios en el archivo config.json tratando de establecer nuevas imágenes no se despliega nada en la app. Por favor solicito su gentil apoyo
![Screenshotinspireui fluxstore](https://user-images.githubusercontent.com/25040516/62957103-22672180-bdc2-11e9-8c6a-43c82cef4473.jpg)
![Captura de pantalla de 2019-08-13 12-02-27](https://user-images.githubusercontent.com/25040516/62957201-4fb3cf80-bdc2-11e9-96f3-f549628ef6f5.png)

**Comment by minhcasi** [comment]
Hi, it's working with our testing - https://tppr.me/znytp
