### ISSUE TITLE
[fluxtstore Pro] - support stripe and paypal pro payment

### ISSUE THREAD

**Issue by benyang2015** [inspireui/support#914]
1. I already buy the app source,how to support stripe payment and paypal pro payment? I'm use magento2.3.x

2. how to public the new version support stripe and paypal  if not support these payment now on version1.4

3. my online website sue stripe payment and paypal pro payment,now the app also need these payment

**Comment by minhcasi** [comment]
Hi, could you help to share the config file so that we could check the integration for this payment, we could update this feature in next release, current v1.4 is not supported for Paypal and Stripe on Magento - thank you!
