### ISSUE TITLE
[Listapp] - Categories loading time in home page

### ISSUE THREAD

**Issue by reconshield** [inspireui/support#915]
i succefully publish my app in google play. thanks to @minhcasi @thangvo9x.

but want ask some questions before let public use it..

1) after user download app from google play store..apps loading is good. my app 27mb.
    after splash screen, all the categories display in home page. categories name not display..its take sometime or we have to close app and open back , then can see all categories name.

check your documentation screenshot : https://docs.inspireui.com/static/61a06bc0948e7c7f199af0310385852e/22e61/theme1.png

* in 1st screenshoot after what can we help you find ..all categories boxes image display but not categories name..

any idea on this issue?

**Comment by theAlinux** [comment]
i not get all of categories from wordpress site
but
set "local enable: true" on Restaurant.js (your theme.js)
 there is 
```
{ 
     component: 'categoryLinks', 
     name: 'We help you find the best restaurants',
 },
```
in "horizontalLayout"

this link to HomeCategories in common/config/index.js
there are "category: categoryId", the categoryId change to listing category in url "tag_ID: number" from wordpress site

i hope you will understand

**Comment by reconshield** [comment]
I get all categories .. no problem.. i mean when launch app its not display categories name .. check listapp documetation image also same.. when we close app and open again.. its ok..

**Comment by theAlinux** [comment]
how do you get all of categories?

**Comment by reconshield** [comment]
Yes.. i get all no problem.. but issue is
1st time app load.. cant see.. have to close and open back.. its not good when i publish app to public.. they will think its blank... its api load slow something

**Comment by theAlinux** [comment]
also for system optimize, i can write "expo optimize" to console in project directory
