### ISSUE TITLE
[Mstore-Pro] two Bugs

### ISSUE THREAD

**Issue by alho00ot** [inspireui/support#919]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue
There are two bugs, I need your help to fix it. First one the app crashed when you try to swap the first picture in the opposite direction of BannerSlier layout for more than three times. The second issue, I have 14 products under bannerImage, when Click for the first time all product appears but if you back to the home page and click again on that banner it will show just 10 products.

2. Screenshots
First issue 
https://www.dropbox.com/s/6b8e9iuy4kbithj/Bad.mp4?dl=0

Second issue
https://www.dropbox.com/s/lf5mfo63o81hkby/bbad2.mp4?dl=0

3. My screenshot of the purchase product or my comment:

<img width="823" alt="Screen Shot 2019-08-14 at 5 37 50 PM" src="https://user-images.githubusercontent.com/5117891/63030327-caf8ac80-beba-11e9-86f1-c0dc832df8c3.png">

3. Config files (optional)

**Comment by minhcasi** [comment]
Hi, could you share your configs file as well? It's ok if you are using the default one - thank you!

**Comment by alho00ot** [comment]
plese find configs file
https://www.dropbox.com/s/d8aany4fkofdrho/AppConfig.json?dl=0

**Comment by minhcasi** [comment]
Thank you, we will have a check and let you know

@concuacon

**Comment by minhcasi** [comment]
@alho00ot - pls update latest 3.9.6 for the fixing - also replace the mstore-checkout with mstore-api - https://wordpress.org/plugins/mstore-api/

Let us know your checking and reopen the ticket if you still have an issues - thank you!
