### ISSUE TITLE
[Fluxstore] - Product Images not loading and errors on Product page

### ISSUE THREAD

**Issue by Isodie** [inspireui/support#921]
1. My issue - Images are not loading and there are errors on product page.

2. Screenshots - 
<img width="1440" alt="Screenshot 2019-08-14 at 11 09 28 PM" src="https://user-images.githubusercontent.com/14618403/63042911-b7643a80-bee8-11e9-8c31-ad2621c51759.png">
<img width="1440" alt="Screenshot 2019-08-14 at 11 09 06 PM" src="https://user-images.githubusercontent.com/14618403/63042912-b7fcd100-bee8-11e9-816f-d41c525ee0cf.png">
<img width="1440" alt="Screenshot 2019-08-14 at 11 08 53 PM" src="https://user-images.githubusercontent.com/14618403/63042914-b7fcd100-bee8-11e9-9a97-dbff9227a994.png">
<img width="1440" alt="Screenshot 2019-08-14 at 11 07 27 PM" src="https://user-images.githubusercontent.com/14618403/63042916-b7fcd100-bee8-11e9-90e4-b245f993558b.png">

3. My screenshot of the purchase product or my comment:
![Opera Snapshot_2019-08-14_224922_codecanyon net](https://user-images.githubusercontent.com/14618403/63043099-2346a300-bee9-11e9-8724-49beb676abf5.png)

3. Config files (optional)
/// Server config
const serverConfig = {
  "type": "woo",
  "url": "https://patelbrothers.fashion",
  "consumerKey": "ck_e208dfcf6bc2629ffce343cdeae0e90a47886cec",
  "consumerSecret": "cs_ffc365a1e5c49ed0fecf87c6c75bf845464f016a",
  "blog": "https://patelbrothers.fashion/",
  "forgetPassword": "https://patelbrothers.fashion//wp-login.php?action=lostpassword"
};

**Comment by minhtruong315** [comment]
Hi @Isodie We fixed. it will be available in next release.thanks
