### ISSUE TITLE
[mstore-pro] Node JS 10.x

### ISSUE THREAD

**Issue by leghost** [inspireui/support#922]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue
I can't set up the app. Error when running yarn install
2. Screenshots
![image](https://user-images.githubusercontent.com/47028114/63043815-3ba8c480-becd-11e9-86d1-81027ccce139.png)
![image](https://user-images.githubusercontent.com/47028114/63043826-42cfd280-becd-11e9-99c5-f9dd98fd574f.png)
![image](https://user-images.githubusercontent.com/47028114/63043869-5a0ec000-becd-11e9-8921-2dced0b55e2f.png)
![image](https://user-images.githubusercontent.com/47028114/63043906-6f83ea00-becd-11e9-86fa-7c367560fddd.png)

3. My screenshot of the purchase product or my comment:
![image](https://user-images.githubusercontent.com/47028114/63043948-862a4100-becd-11e9-85e3-f89b0ea57d16.png)

3. Config files (optional)

**Comment by minhcasi** [comment]
@concuacon - pls help for suggestion

**Comment by concuacon** [comment]
Hello @leghost you can downgrade node, npm & yarn version 
the same
<img width="586" alt="Screen Shot 2019-08-16 at 10 55 43 AM" src="https://user-images.githubusercontent.com/11958061/63142682-f0013280-c014-11e9-9462-32c151c69eee.png">

**Comment by sackmotion** [comment]
I had some problems building 3.9.2 with same kind of problems and was related to node version , once i downgrade to latest stable everything was smooth. Tested with 3.9.4b too

FYI running Mac OS High Sierra ( not windows , however try to get latest stable of node ).
node -v
v10.16.0
npm -v
6.9.0
yarn -v
1.17.3

https://nodejs.org/en/download/ , install Latest LTS Version: 10.16.3 (includes npm 6.9.0)

good luck !

**Comment by minhcasi** [comment]
Thank for your sharing @sackmotion - there is a known issue on Nodejs 12.x, it's working fine on node 10.x

**Comment by leghost** [comment]
Thanks it's ok for me now.

**Comment by leghost** [comment]
I just downgraded my componnents an it run fine now.
