### ISSUE TITLE
fluxstore-woocommerce v 1.4b error

### ISSUE THREAD

**Issue by peter2411** [inspireui/support#923]
1. My issue

i just downloaded the latest version 1.4 and run it without any edits!
i got this error when i try to login in the app with any login method , i can't see the user setting 

2. Screenshots

https://prnt.sc/osqxgd
https://prnt.sc/osqy25

3. My screenshot of the purchase product or my comment:

https://prnt.sc/osqzpb

**Comment by minhtruong315** [comment]
Hi @peter2411. we fixed this issue. it will be available in next release. Thanks

**Comment by peter2411** [comment]
unfortunately i can't wait until the next release , i don't have a lot of
blog posts the error will Very visible !
at least send the fix for me or tell me how to turn off the sliding feature
i have some experience with coding

**Comment by minhtruong315** [comment]
You can update initState function in lib/screens/settings.dart like this
<img width="641" alt="Screen Shot 2019-08-18 at 05 50 54" src="https://user-images.githubusercontent.com/10402500/63218067-45a41f00-c17c-11e9-83e0-1e3d496b8c6a.png">
