### ISSUE TITLE
[Listapp] - Categories Name loading time in homepage

### ISSUE THREAD

**Issue by reconshield** [inspireui/support#925]
i succefully publish my app in google play. thanks to @minhcasi @thangvo9x.

but want ask some questions before let public use it..

after user download app from google play store..apps loading is good. my app 27mb.
after splash screen, all the categories display in home page. categories name not display..its take sometime or we have to close app and open back , then can see all categories name. im using cloudways hosting.

any idea on this issue?

**Comment by thangvo9x** [comment]
maybe the problem is coming from your network. the network is slowly.

**Comment by reconshield** [comment]
If my network got issue then your documentation image also show same.. only image show.. not categories list.. your network and mine slow.. which network is better? Pls advice

https://docs.inspireui.com/static/61a06bc0948e7c7f199af0310385852e/22e61/theme1.png

**Comment by thangvo9x** [comment]
You could be using this plugin. 
http://mylisting.inspireui.com/wp-admin/options-general.php?page=webp_express_settings_page
I tried some listing on our website and they were loaded very fast.

**Comment by reconshield** [comment]
this one image optimazer plugin.. webp express plugin..
im facing issue on API call categories list in app.. images load fast in my app..no issue..

**Comment by thangvo9x** [comment]
Try to replace this file at Container/Home/Horizontal.js with below file
[Horizontal.txt](https://github.com/inspireui/support/files/3514072/Horizontal.txt)
Remember that change from .txt -> .js tag 
Thanks

**Comment by reconshield** [comment]
@thangvo9x  just tried..its same.. :(

**Comment by reconshield** [comment]
any update?

**Comment by thangvo9x** [comment]
Hi. I tried many many many times. Can't see your problem. The problem has only two directions
1. Mapping is valid in Config/index.js  with those categories id on your website.
2. Check url when fetch from listing categories at WPAPI.js in Services folder
in this block is correct.
<img width="352" alt="Screen Shot 2019-08-26 at 5 17 26 PM" src="https://user-images.githubusercontent.com/23457178/63683780-7859b180-c825-11e9-9762-aedac5c7285b.png">
Thanks
