### ISSUE TITLE
[FluxStore-Woocommerce] Lib files not populating

### ISSUE THREAD

**Issue by jakkumarket** [inspireui/support#926]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue

Whenever I start a new flutter project, it seems as though all of the files do not populate, specifically the lib folder.

2. Screenshots
https://imgur.com/nHtGq40

3. My screenshot of the purchase product or my comment:
https://imgur.com/JImeNuH
3. Config files (optional)

**Comment by minhcasi** [comment]
Hi, you just need to open the project folder from the download package, instead of creating new Flutter project - thanks
