### ISSUE TITLE
The following error for member login

### ISSUE THREAD

**Issue by sefayildirim** [inspireui/support#927]
(index):1 Access to XMLHttpRequest at ‘http://mydomain.com/wp-json/jwt-auth/v1/token' from origin ‘http://localhost:8081' has been blocked by CORS policy: Response to preflight request doesn’t pass access control check: It does not have HTTP ok status.

screenshot:  http://app.carsi1461.com/api/img/Ads%C4%B1z.png

**Comment by theAlinux** [comment]
check this => https://docs.inspireui.com/listapp/getting-started/#jwt-authentication

**Comment by sefayildirim** [comment]
Much obliged!
