### ISSUE TITLE
[Fluxstore] - Not rendering Image with .jpeg extension 

### ISSUE THREAD

**Issue by EffectiveOG** [inspireui/support#928]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue

The app is not rendering image with .jpeg extension meanwhile those with .jpg works fine
2. Screenshots
![Capture d’écran (12)](https://user-images.githubusercontent.com/33296809/63095544-6d6c6a80-bf63-11e9-8577-48f26056d0e4.png)
3. My screenshot of the purchase product or my comment:

3. Config files (optional)

**Comment by Isodie** [comment]
HI
I am having same issue.

**Comment by minhtruong315** [comment]
We fixed. it will be available in next release
