### ISSUE TITLE
mstore pro

### ISSUE THREAD

**Issue by mooidev** [inspireui/support#929]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue

Firstly, great work guys. This app is very cool! Please see my questions below:

1.1 I'm currently using the Payment Gateway PayFast (www.payfast.co.za). It seems to connect however when I go to complete the purchase, it loads the website instead of connecting to the payment gateway?

1.2 On the Sign Up page. Can I add an additional custom field? I would like to include an Employee Number on registration. 

2. Screenshots

3. My screenshot of the purchased product or my comment:

https://codecanyon.net/item/beostore-complete-react-native-template-for-ecommerce/17010642

3. Config files (optional)

**Comment by minhcasi** [comment]
Hi @mooidev  - thank you for your reporting.

1. The payment feature will load to process via WebView component, it's load the mstore-checkout  web form to support multi-payment, if you can see the webview same as when you process via Webview then it is run correctly. 

2. Yes you can add a new custom field and save to the wordpress database, require some customization

Thank you!

**Comment by mooidev** [comment]
Thank You. Do you some documentation on how to add the custom field?

Brad Corden
brad@mooidev.com
+27842888001

**Comment by minhcasi** [comment]
Hi, sorry for the late response on this ticket - we don't have documentation for this feature, but you can find "custom api wordpress"- there is a lot of guides.

The normal method is to add a new field to the return API, then it will easy to populate to the app.

Allow me to close this ticket and help to open the new one if you have any further issue - thank you 😊
