### ISSUE TITLE
ListPro - Contact me asap

### ISSUE THREAD

**Issue by shubhamt619** [inspireui/support#93]
**Required Info (please complete the following information):**
 - Product: ListPro
 - Your Purchased Code: db055d4e-cd4e-4411-b654-21589bab86a0
(we may not reply if you are not our customer)

**Describe the bug**
There are lots of bugs and lots of small points i would like to discuss with you.
Please send me an email with any of your following details like whatsapp no, skype id or anything on which we can chat instantly.

me@shubhams.in
shubhamt619@gmail.com

PLEASE REPLY ASAP

**Comment by thangvo9x** [comment]
Hi, Thanks for your choice. You can email to minh@inspireui.com.
Thanks
