### ISSUE TITLE
Mstore mv the products do not appear 

### ISSUE THREAD

**Issue by yazanhadid** [inspireui/support#930]
Halo ;  i do everythin on CeBuilder , every thin is work normal , just the produtcts do not appear  in the app ,  i  also can see all Category on  CeBuilder  .
this is my website www.ornina-moda.de 
![1](https://user-images.githubusercontent.com/50557319/63096798-21272780-bf6f-11e9-9624-920d2b388977.jpg)
![2](https://user-images.githubusercontent.com/50557319/63096799-21272780-bf6f-11e9-987a-c33ca8a76989.jpg)
![3](https://user-images.githubusercontent.com/50557319/63096800-21272780-bf6f-11e9-9163-dcf628845b86.jpg)
![4](https://user-images.githubusercontent.com/50557319/63096801-21bfbe00-bf6f-11e9-812c-47c1f2ef517d.jpg)

**Comment by thangvo9x** [comment]
Hi bro. Could you share full AppConfig.json file for checking?

**Comment by thangvo9x** [comment]
Hi bro. Could you share full AppConfig.json file for checking?

**Comment by yazanhadid** [comment]
hallo , i have contact with your college ((inspireui.intercom-mail.com)) schould i continue with or with your college ?
thanl you

**Comment by yazanhadid** [comment]
hallo , can you please give me an Email to send the File

**Comment by thangvo9x** [comment]
support@inspireui.com

**Comment by yazanhadid** [comment]
ok  i sent the files

**Comment by thangvo9x** [comment]
I got your website. But the AppConfig which was sent by the original version. More clearly, you can send us an account from your backend dashboard for checking. This purpose will get the consumer key from WooCommerce for getting those products.

**Comment by yazanhadid** [comment]
hallo , do you mean you need  an account from my wordpress Dashboard ?
this is an account
user ; mstore
pass : x$7p)5cBoX6ZJnlCg4Lc2VtZ
url : https://www.ornina-moda.de/ <https://www.ornina-moda.de/wp-admin/>
rasha

than you

‫في الاثنين، 19 أغسطس 2019 في 6:06 ص تمت كتابة ما يلي بواسطة ‪Tony Vo‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by thangvo9x** [comment]
Yup. I can't access to your link admin.
There's some issue on the plugin yours WPML.

**Comment by yazanhadid** [comment]
www.ornina-moda.de/rasha
This is the Admin Homepage

 Tony Vo <notifications@github.com>:

**Comment by yazanhadid** [comment]
?

**Comment by thangvo9x** [comment]
<img width="449" alt="Screen Shot 2019-08-27 at 10 52 08 AM" src="https://user-images.githubusercontent.com/23457178/63739788-c075e400-c8b8-11e9-889e-cb13a6b81c05.png">
What is our problem? You do make it mapping with correct category id. The App will get data from your site.
Thanks
