### ISSUE TITLE
Fluxstore Pro - Flutter E-commerce Full App

### ISSUE THREAD

**Issue by samik9** [inspireui/support#932]
Hello team, good day!
[config.txt](https://github.com/inspireui/support/files/3507309/config.txt)

1. Please fix the two lines of name of category, it should align center: https://d.pr/i/9V4lAj , also will be great that from JSON text size from category can be adjusted.

2. how can I regenerate images cause plugin is not working? https://d.pr/i/fzrrtpose the ticket if you could not prove as our customer.

3. Bug, the category layout “animation” shows nothing, the others work fine https://d.pr/i/dYxQGf .

4. sideMenu does not look nice when the category have 2 words, check: https://d.pr/i/ygVjab, also I got some strange error https://d.pr/i/CNELTi

5. How can i set up a custom payment method? how i can get the id of this gateway for const Payments = {.     ??

6. How can i change the title name of category here? https://d.pr/i/AdO4VF I dont see how, i think this is missing 
Config file: https://d.pr/f/MDzChL

**Comment by minhtruong315** [comment]
Hi @samik9 
1. fixed
2. I can't see the screenshot
3. I checked your config. But i can't reproduce this issue. Can you record video?
4. fixed
5. You can use postman to get payment method list.
http://bugambillia.com/wp-json/wc/v2/payment_gateways
 This api need Oauth 1.0. So you need to set Consumer Key and Consumer Secret
6. it is image. you can change image url in config.json

**Comment by samik9** [comment]
2. how can I regenerate images cause plugin is not working? Screenshot Fixed 👉 https://d.pr/i/fzrrtp


3.  This is the video you requested https://d.pr/v/X2BcLx   👉 also products does not load on homescreen neither

@minhcasi @minhtruong315
