### ISSUE TITLE
[Fluxstore Pro] - Please avoid upload these local development files

### ISSUE THREAD

**Issue by ihsanberahim** [inspireui/support#934]
This is a basic request. I don't want these file included in the provided zip:

1. `android/.gradle`
2. `ios/.symlinks`

![image](https://user-images.githubusercontent.com/1956846/63166633-970bbb80-c061-11e9-9626-c79537f4f767.png)

This mess me everytime i update my project or i just lazy to clean them myself again and again. Thanks ;)

**Comment by ihsanberahim** [comment]
`ios/Flutter/Generated.xcconfig`

![image](https://user-images.githubusercontent.com/1956846/63167983-72194780-c065-11e9-95d7-694b4e764a48.png)

**Comment by minhcasi** [comment]
@ihsanberahim - thank you very much for your feedback, I will update with the team to remove these files on future releases
