### ISSUE TITLE
[Fluxstore] Jsop-api plugin issue

### ISSUE THREAD

**Issue by Pars1vaLl** [inspireui/support#935]
Hi,

It is impossible to download Json-Api plugin for Fluxstore. Is there any workaround?

Thanks

**Comment by theAlinux** [comment]
i don't know what is mean for Fluxstore but plugins link => https://docs.inspireui.com/listpro/getting-started/#basic-plugins

**Comment by Pars1vaLl** [comment]
Json Api from this Documentation: https://docs.inspireui.com/fluxstore/getting-started/
and this plugin: https://wordpress.org/plugins/json-api/#description

**Comment by theAlinux** [comment]
yup

**Comment by minhcasi** [comment]
@Pars1vaLl - please download it from this link - https://github.com/PI-Media/json-api - the author will publish it again on Wordpress Plugins. 

Or use the one from the download package - https://tppr.me/NEbZj

**Comment by humazed** [comment]
@minhcasi I can't find the sources file in the downloaded zip file, I bought the WooCommerce only version

**Comment by minhcasi** [comment]
@humazed  - sorry our mistake when pack the woocommerce version, please help to download the Wordpress plugins on this link - https://www.dropbox.com/sh/6728oflugglr03p/AAD3q-jCxI_33PMjytNZ4zeSa?dl=0

**Comment by humazed** [comment]
@minhcasi thanks, also note this also fixes #943 when using the plugin from dropbox

**Comment by minhcasi** [comment]
Thank you @humazed - we are working on the Fluxstore product to upgrade it having more powerful features, please help to give some feedback/rating from the download page to encourage the team https://codecanyon.net/downloads - appreciated for your help 👍
