### ISSUE TITLE
[Fluxstore] - Problem with product details and categ section

### ISSUE THREAD

**Issue by EffectiveOG** [inspireui/support#936]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our produc

t (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue
Image detail showing some weird errors and categorie section
2. Screenshots

![Screenshot_1566038715](https://user-images.githubusercontent.com/33296809/63211129-1e514180-c0eb-11e9-9593-e30a6b249a49.png)

![Screenshot_1566038684](https://user-images.githubusercontent.com/33296809/63211131-1ee9d800-c0eb-11e9-8408-d5c4cdd2a8e5.png)

3. My screenshot of the purchase product or my comment:

3. Config files (optional)

**Comment by minhcasi** [comment]
Noted with checking, could you share the config files so that we could help for checking?

**Comment by minhtruong315** [comment]
@EffectiveOG pls send me config.dart and config.json via email: truong@inspireui.com

**Comment by minhtruong315** [comment]
Hi @EffectiveOG did you install wpml plugin in your website?

**Comment by EffectiveOG** [comment]
Hello yes by following the recommanded instructions on fluxstore documentation

Envoyé de mon iPhone

Le 23 août 2019 à 02:42, minhtruong315 <notifications@github.com<mailto:notifications@github.com>> a écrit :


Hi @EffectiveOG<https://github.com/EffectiveOG> did you install wpml plugin in your website?

**Comment by minhtruong315** [comment]
@EffectiveOG can you add my skype: minhtruong315. I will help you check via teamviewer
