### ISSUE TITLE
MStore Pro - circleCategory

### ISSUE THREAD

**Issue by myothura** [inspireui/support#937]
Hello, I would like to know how to map with circleCategory and how to change circleCategory icon. If you have the time please kindly explain me thanks.

This one is my - item buy date 2019-08-16 08:40:13 UTC

this one is last Purchase Code - afd17110d52c

**Comment by myothura** [comment]
i mean map wordpress category  with circleCategory and how to change circleCategory icon

**Comment by minhcasi** [comment]
@myothura - sorry for late response, the Wordpress Circle category is not ready to support from current MStore release, we have noted as further improvement - thank you!
