### ISSUE TITLE
[mstore pro] - start with banner slider not by date and logo

### ISSUE THREAD

**Issue by mohamedibrahim89** [inspireui/support#938]
1. My issue
need homepage for app start with banner and slider and need to deactive the logo and date in home
2. Screenshots
![InkedScreenshot_20190817-141834_Shopidom_LI](https://user-images.githubusercontent.com/35544603/63212482-6bdaa800-c105-11e9-8a5d-10a79c9a60b1.jpg)

**Comment by sackmotion** [comment]
@mohamedibrahim89 you can deactivate changing the code in file :

src/components/HorizonList/index.js , remove the complete View is a way.

```
-      <View style={styles.headerLogo}>
-        <Image source={Config.LogoImage} style={styles.logo} />
-        <Text style={[styles.headerDate, { color: text }]}>
-          {this.state.currentDate.toUpperCase()}
-        </Text>
-      </View> 
```

Hope that helps !

**Comment by concuacon** [comment]
Thanks @sackmotion, 
@mohamedibrahim89, have u fix it yet? You can follow @sackmotion suggest or remove line **ListHeaderComponent**
path: **src/components/HorizonList/index.js**
<img width="664" alt="Screen Shot 2019-08-27 at 4 56 45 PM" src="https://user-images.githubusercontent.com/11958061/63761732-db158080-c8eb-11e9-9c63-e8cc1e0e4fd9.png">
or edit line HideHomeLogo: false -> HideHomeLogo: true, path: **src/common/Config.js**
<img width="293" alt="Screen Shot 2019-08-27 at 4 59 59 PM" src="https://user-images.githubusercontent.com/11958061/63761964-347daf80-c8ec-11e9-8ce9-6785460c0d86.png">
