### ISSUE TITLE
BeoNews - video instructions no longer relevant

### ISSUE THREAD

**Issue by MyAgileWorld** [inspireui/support#94]
**Mandatory Info (please complete the following information):**
 - Product: Beonews Pro
 - Your Purchased Code: [get from https://codecanyon.net/downloads]

097ff434-0241-4e47-9272-36d0b6884355 | 097ff434-0241-4e47-9272-36d0b6884355 |  
-- | -- | --
097ff434-0241-4e47-9272-36d0b6884355

**Describe the issues**
The video you uploaded to help us with it is no longer relevant as expo does not offer XDE anymore. I am new to this whole thing and so I cannot proceed. I tried using npm but the app in Expo on my phone does not go past the splash screen for Beonews. 

I tried the Beonews Pro version but I got stuck on all sorts of errors during installation.

Here's my screenshots using the Expo version:
![beonews](https://user-images.githubusercontent.com/45817421/49863577-8337f780-fdf8-11e8-8445-be75a5ef249d.JPG)

![beonews2](https://user-images.githubusercontent.com/45817421/49863604-9054e680-fdf8-11e8-8ce6-395a8da4d811.JPG)

Please advise.

**Comment by minhcasi** [comment]
Thank you for notify, we are going to update new App Builder to help to install the Expo quickly without using the terminal, in the meantime please using the following script for the installing:
- npm install expo-cli -g 
- yarn install && expo start

**Comment by MyAgileWorld** [comment]
Hi there
Thanks for getting back to me. I tried the above and this is what I have:

![image](https://user-images.githubusercontent.com/45817421/49999484-e360a200-ff8e-11e8-8a59-5d9da1456558.png)

The above is my command prompt window after the Javascript Bundles reached 100%.

![image](https://user-images.githubusercontent.com/45817421/49999554-1014b980-ff8f-11e8-9d3f-b1ff33077736.png)

The above is the browser window that opened. As you can see, nothing happens after Javascript Bundles reaches 100%.

When I use QR code on my Android phone (Expo app) then all I see now is a blank white screen.


Please help!

**Comment by MyAgileWorld** [comment]
Can't you just modify video instructions so that I can use the Snack tool at Expo: https://expo.io/tools#snack

**Comment by MyAgileWorld** [comment]
Here's an update. I got this appear on my screen 30 minutes later:

![image](https://user-images.githubusercontent.com/45817421/50001927-5b7e9600-ff96-11e8-9a8b-8bc0b46c4cc6.png)

**Comment by minhcasi** [comment]
Hi, you can now use with Beonews expo with the CeBuilder from https://inspireui.com - thank you!
