### ISSUE TITLE
Fluxstore Pro 

### ISSUE THREAD

**Issue by samik9** [inspireui/support#942]
1. **Favorites does not save after logout.**
If I save a favorite I **log out** and **log in**, then the favorites are gone.  

2. **After Sign up, it ask name again when checking out.**
If i sign up using email, I will need to fill name, last name, and email, so far all good, but when I am going to make a purchase something, on checkout, the data for email, and names are not filled, it should fill automatically because I already gave this information on Sign up form. Also for SMS sign up and facebook sign up cases.  
I think the point is to avoid user fillig names, last names, email 2 times. 
By the way if I log out and login again,on checkout every field is blank, all data must be filled **again** , this should not happen.

3. **Request**:
User should be able to edit/update profile info, also the shipping addresses from the app

**Update**
**4**. When "EnableShipping": false, this happens, the user can see shipping when click go back
vide: https://d.pr/v/NJf8pt     issue #940

**Comment by minhcasi** [comment]
Noted with checking, thank you!

**Comment by minhcasi** [comment]
[ ]When "EnableShipping": false, this happens, the user can see shipping when click go back
vide: https://d.pr/v/NJf8pt

**Comment by minhcasi** [comment]
#940 

[ ]When "EnableShipping": false, this happens, the user can see shipping when click go back
vide: https://d.pr/v/NJf8pt

**Comment by minhtruong315** [comment]
@samik9 I fixed 1 and 2. it will be available in next release.
