### ISSUE TITLE
[Fluxstore] - MstoreUser is missing 

### ISSUE THREAD

**Issue by Pars1vaLl** [inspireui/support#943]
Hi guys,

I have asked to share URL to download JSON-api: https://github.com/inspireui/support/issues/935

You shared URL and I have download from Github, however there is no 'MstoreUser' in plugin settings as shown in your docs. Here is screenshot: http://prntscr.com/ou5e36

Thanks

**Comment by minhcasi** [comment]
Hi, pls confirm that this link we will work - https://github.com/inspireui/mstore-checkout

https://tppr.me/XTceS

**Comment by Pars1vaLl** [comment]
Hi,
I have downloaded plugin from this URL, however 'MStoreUser' is not visible. I have also changed the theme - it doesn`t help. What else can cause such issue?

Hope you help me as soon as possible. Thanks=)

**Comment by Pars1vaLl** [comment]
@minhcasi I have downloaded plugin from [URL](https://github.com/inspireui/support/issues/935#issuecomment-522981967). It is fine now. Thanks

**Comment by minhcasi** [comment]
Thank you @Pars1vaLl - we are working on the Fluxstore product to upgrade it has more powerful features, please help to give some feedback/rating from the download page to encourage the team https://codecanyon.net/downloads - appreciated for your help 👍
