### ISSUE TITLE
[Fluxstore] - Pinterest layout not working on Product list page

### ISSUE THREAD

**Issue by Isodie** [inspireui/support#944]
1. My issue - Pinterest layout not working on Product list page

2. Screenshots -

**I have set ProductListLayout to pinterest in config.json**
<img width="626" alt="Screenshot 2019-08-18 at 3 00 06 PM" src="https://user-images.githubusercontent.com/14618403/63222780-cb01f080-c1c9-11e9-8d0b-5bc3f8e916bd.png">

**"Women > Bags" Category  on home page with pinterest layout working.**
<img width="382" alt="Bags Category  on home page with pinterest layout" src="https://user-images.githubusercontent.com/14618403/63222782-cb9a8700-c1c9-11e9-8e82-9627d243b003.png">

**"Women > Bags" category on product page, pinterest layout not working.**
<img width="396" alt="Bag category on prodcut page " src="https://user-images.githubusercontent.com/14618403/63222783-cb9a8700-c1c9-11e9-9e4d-74d47c1cab9b.png">

3. My screenshot of the purchase product or my comment:
![Opera Snapshot_2019-08-14_224922_codecanyon net](https://user-images.githubusercontent.com/14618403/63222838-6b581500-c1ca-11e9-9c39-94a7d12323f5.png)

**Comment by minhcasi** [comment]
Note for upgrading this feature on next 1.5 - thanks

**Comment by minhtruong315** [comment]
Hi @Isodie I updated. it will be available in next release
