### ISSUE TITLE
[ListApp] - Error this.props.fetchPayments is not a function

### ISSUE THREAD

**Issue by Saadbadi** [inspireui/support#945]
Hi
    I get the error this.props.fetchPayments is not a function when booking from App. 
when i select service and select start time + End time and Click Next the error appear 
Note : The error appear IOS Real Device + IOS Simulater 
Thanks
 
1- ScreenShot of Error

3. My screenshot of  my comment:

3. Config files 

![Simulator Screen Shot - iPhone XR - 2019-08-18 at 16 54 34](https://user-images.githubusercontent.com/17745490/63229834-66688500-c20d-11e9-8fab-6da6a4155651.png)
<img width="620" alt="Screen Shot 2019-08-18 at 11 04 41 PM" src="https://user-images.githubusercontent.com/17745490/63229842-784a2800-c20d-11e9-8e2b-f9ae1f1743d0.png">

{
  "Website": {
    "url": "http://guide.akiyascripts.com",
    "consumerKey": "ck_f42048845fb4ce65c7b0b8f8a3165cec383b724b",
    "consumerSecret": "cs_fd015c4b11202735e8955e7e21423fbfb34f3624"
  },
  "Theme": "mylisting",
  "MainColor": {
    "tabbarTint": "#00B2BC",
    "tabbarColor": "#D5D8DE",
    "mainColorTheme": "#00B2BC",
    "tabbar": "#fff"
  }
}

**Comment by thangvo9x** [comment]
hi bro. Try to replace this file at Theme/myListing/Container/Cart/Payment/
[index.txt](https://github.com/inspireui/support/files/3514043/index.txt)
Change from .txt -> .js tag
Thanks

**Comment by Saadbadi** [comment]
Hi bro. 
thank you so much for your reply !
the problem solved but now when i fill the required Delivery info. and click next the payment method not appear (See the screenshot please)
![IMG_8505](https://user-images.githubusercontent.com/17745490/63246098-89755200-c26a-11e9-9b9e-df595aa0de5c.PNG)

and if i click on Confirm Order button this error message appear .

Thanks

**Comment by thangvo9x** [comment]
Could you share full AppConfig.json help me?

**Comment by Saadbadi** [comment]
This is my AppConfig.json
[AppConfig.txt](https://github.com/inspireui/support/files/3515409/AppConfig.txt)

**Comment by arjunchopra35** [comment]
I am facing the exact same issues! Thank you for the solutions

**Comment by arjunchopra35** [comment]
Any update guys?

**Comment by Saadbadi** [comment]
No update .
There is no solution and i am waiting from six days ago  !!!

**Comment by arjunchopra35** [comment]
The way I see it I think the code is not able to fetch any payment options at all. It could be either something with the REST API plugin on the website or something in the code!

**Comment by arjunchopra35** [comment]
@thangvo9x My proof of purchase and old thread https://github.com/inspireui/support/issues/911

**Comment by thangvo9x** [comment]
Try to replace the below file at Theme/myListing/Container/Cart/Payment/
P/s: remember the change from .txt -> .js tag 
and change theme in your AppConfig frrom "mylisting" -> "myListing"

**Comment by Saadbadi** [comment]
@thangvo9x @arjunchopra35  The same issue i can't choose payment method (No method display )
and i am already change that file in (Theme/myListing/Container/Cart/Payment/)

**Comment by arjunchopra35** [comment]
Any update @thangvo9x  It's been quite a while!

**Comment by arjunchopra35** [comment]
@thangvo9x  I figured out that the issue was due to the site being hosted at a shared server and some of the shared servers do not allow us to make the changes required for jwt authentication in the .htaccess file, thus the payment options API endpoint was returning a 403 error. " Authorization header malformed. ". I have not tried it at a private server yet but I hope hosting it on a private server and reconfiguring the site should solve the issue. Please let me know if that sounds about right? and any other advice you might have for me.

**Comment by thangvo9x** [comment]
Which server are you using?

**Comment by arjunchopra35** [comment]
GoDaddy shared Linux hosting

**Comment by arjunchopra35** [comment]
{
  "Website": {
    "url": "https://goodlooks.app",
    "consumerKey": "ck_6243129a4cee04396f0c68d3619254dced80243d",
    "consumerSecret": "cs_864236b32f7883892d970e7c2aaa8b8de1d033cd"
  },
  "Theme": "mylisting",
  "MainColor": {
    "tabbarTint": "#00B2BC",
    "tabbarColor": "#D5D8DE",
    "mainColorTheme": "#00B2BC",
    "tabbar": "#fff"
  }
}

**Comment by arjunchopra35** [comment]
same issue as -
https://github.com/inspireui/support/issues/945#issuecomment-522445211

**Comment by thangvo9x** [comment]
Could you share the account for login to your admin dashboard? Thanks

**Comment by arjunchopra35** [comment]
Username - mojojojo
password - mojojojo123

**Comment by thangvo9x** [comment]
Checked on your config. The app still works normally.

**Comment by thangvo9x** [comment]
<img width="451" alt="Screen Shot 2019-09-12 at 10 07 26 AM" src="https://user-images.githubusercontent.com/23457178/64751064-30d16600-d545-11e9-8a29-d092008de477.png">
<img width="451" alt="Screen Shot 2019-09-12 at 10 07 31 AM" src="https://user-images.githubusercontent.com/23457178/64751065-30d16600-d545-11e9-80fd-f42781b7c565.png">

**Comment by Saadbadi** [comment]
So where is the error ?? i can't see ( Pay with cash upon delivery ) also if i am using config of @arjunchopra35 
 
![IMG_8714](https://user-images.githubusercontent.com/17745490/64759654-7b9caf00-d540-11e9-8687-0b92a2a553af.PNG)

and i have another question please 
why in your screenshot the first stage is called ( My cart ) and in my side the first stage is called ( Booking ) is there any different in versions or another thing !!!

**Comment by arjunchopra35** [comment]
@thangvo9x  Can you share your app's code at acarjunchopra35@gmail.com
