### ISSUE TITLE
Fluxstore issues and feature requests

### ISSUE THREAD

**Issue by ghanchi2000** [inspireui/support#946]
1) we have over 1000 categories, in categories page it show blank category
(please check email for config file)
2) Also we want to change app name, package name and version how to change ?
3) We only ship to Pakistan, we want to remove zip code field, state field and auto select Pakistan as only selection
4) after click sign in with email in login page, there is no animation which lead to click multiple time
5) after login address is save on website no address is loaded from website
6) after adding multiple items in cart when we exit app, after return to app cart is empty, which is very much necessary feature, please fix this
7) please add guest checkout feature, so many time there is login issues and forget password takes time, we it will be great if guest checkout option is enabled
8) please add google login, as it is the most easy way to login
9) Please add support for deep linking
10) where to change facebook login app id ?

**Comment by ghanchi2000** [comment]
change package name 

C:\fluxstore\android\app\src\main\AndroidManifest.xml
C:\fluxstore\android\app\src\debug\AndroidManifest.xml
C:\fluxstore\android\app\src\profile\AndroidManifest.xml
C:\fluxstore\android\app\src\main\java\com\inspireui\fluxstore\MainActivity.java
C:\fluxstore\android\app\build.gradle
C:\fluxstore\android\app\google-services.json
C:\fluxstore\build\app\intermediates\merged_manifest\debug\AndroidManifest.xml
C:\fluxstore\build\app\intermediates\bundle_manifest\debug\processDebugManifest\bundle-manifest\AndroidManifest.xml
C:\fluxstore\build\app\intermediates\instant_app_manifest\debug\processDebugManifest\instant-app-manifest\AndroidManifest.xml
change folder name > C:\fluxstore\android\app\src\main\java\com
replace C:\fluxstore\android\app\google-services.json with your firebase file

**Comment by minhcasi** [comment]
@ghanchi2000 - could you help to share your config.dart so that we could help for checking the categories issue - thank you!

**Comment by ghanchi2000** [comment]
Please resolve category blank issue as soon as possible as i have to publish app in stores

**Comment by minhtruong315** [comment]
@ghanchi2000 
1. There is no category that has parent is 0, so you only can show these category types: sideMenu, column, subCategories.
3. You can edit in lib/screens/checkout/shipping_address.dart
10. Check this link https://developers.facebook.com/docs/facebook-login

**Comment by minhtruong315** [comment]
6. Updated

**Comment by minhtruong315** [comment]
4. Updated

**Comment by ghanchi2000** [comment]
There is no category that has parent is 0, so you only can show these category types: sideMenu, column, subCategories.

can you please explain what is parent 0 ?
We have over 1000 categories and 4 level of sub categories

**Comment by ghanchi2000** [comment]
category types: sideMenu, column, subCategories.
In above 3 categories only few categories are loading, not all categories are loading
 i need to load only top category and then sub category
please see my previous app category menu how its loading 
https://play.google.com/store/apps/details?id=com.shopperspk.webit
