### ISSUE TITLE
[FluxStore] - I/flutter (17760): Another exception was thrown: NoSuchMethodError: The getter 'isEmpty' was called on null.

### ISSUE THREAD

**Issue by jakkumarket** [inspireui/support#947]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue
Trying to view products, and I receive `I/flutter (17760): Another exception was thrown: NoSuchMethodError: The getter 'isEmpty' was called on null.` No pictures or anything show when trying to view products or the shop page in general.
2. Screenshots
No screenshot, but you may know it as the red screen with yellow text.
3. My screenshot of the purchase product or my comment:
https://imgur.com/JImeNuH
3. Config files (optional)

**Comment by minhcasi** [comment]
Could you try to replace this tools.dart to the common folder to see it can be fixed - https://www.dropbox.com/s/e3r5400k5aoize2/tools.dart?dl=0

Also, make sure you have set up this setting - https://docs.inspireui.com/fluxstore/woocommerce-setup/#setup-the-renerate-image-plugin

**Comment by jakkumarket** [comment]
Getting closer. Images still aren't showing, and when I click on the product, it says 

`I/flutter (24937): Another exception was thrown: NoSuchMethodError: The getter 'length' was called on null.`

**Comment by minhtruong315** [comment]
Hi @jakkumarket can you send me config.json and config.dart via email: truong@inspireui.com. I will help you check

**Comment by jakkumarket** [comment]
@minhtruong315 sent!

**Comment by minhtruong315** [comment]
Hi @jakkumarket I fixed this issue. you can replace lib/models/product.dart by this file
https://www.dropbox.com/s/fdwxtx7qyk5hjox/product.dart?dl=0

**Comment by jakkumarket** [comment]
Hi, product pages now show `NoSuchMethodError: The method 'toUpperCase' was called on null. Receiver: null Tried calling: toUpperCase()`

**Comment by jakkumarket** [comment]
@minhtruong315

**Comment by minhtruong315** [comment]
@jakkumarket can you take me screenshot?

**Comment by jakkumarket** [comment]
@minhtruong315 https://imgur.com/lP7w5fK
