### ISSUE TITLE
[ListPro] -  Component News 

### ISSUE THREAD

**Issue by RaptorHck** [inspireui/support#949]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue

I can't load the news component correctly,

When I configure the 'news' component in horizontalLayout it loads correctly but in VerticalLayout when pressing to see the information loaded in the listing component it loads the news information, when I should load information from the listing that was registered in the wordpress.

How can I correctly load this component without continuing to haggle the news information and mention me to the listing component information

2. Screenshots

![IMG_3403](https://user-images.githubusercontent.com/7127855/63287559-3efed000-c280-11e9-97b7-7d1deff78710.png)
![IMG_3404](https://user-images.githubusercontent.com/7127855/63287562-402ffd00-c280-11e9-9d72-540b6286dcb9.png)

3. My screenshot of the purchase product or my comment:

<img width="617" alt="Screen Shot 2019-08-19 at 12 53 56 PM" src="https://user-images.githubusercontent.com/7127855/63287641-74a3b900-c280-11e9-82eb-dbab732f10d1.png">

3. Config files (optional)

[config.txt](https://github.com/inspireui/support/files/3517054/config.txt)

Site: http://qponmexico.mx/

**Comment by thangvo9x** [comment]
Hi bro. You must have share the AppConfig.json file for checking

**Comment by thangvo9x** [comment]
Hi. Only using one of them. NOT both at the same time.

**Comment by thangvo9x** [comment]
This is a bug. We will have an update in the next version next month. Thanks
