### ISSUE TITLE
[Mstore Pro] Issues with the app

### ISSUE THREAD

**Issue by rshah92** [inspireui/support#95]
**Required Info (please complete the following information):**
 - Product: [MStore Pro]
 - Your Purchased Code: [1f3de2b4-0a91-47fd-a0d1-bddc02cd1150]

**Describe the bug**
It happened when setup of the app, can help check the screenshot i've attached? thank you

**Screenshots**
![99521184-4b2c-48de-96b0-b8cb3cf9a733](https://user-images.githubusercontent.com/45820236/49872104-05550a00-fe53-11e8-9e11-59449616c3e9.jpg)

**Additional context**
Please help check, thank you

**Comment by luyx2412** [comment]
Hi @rshah92 Please install `babel-preset-react-native` with `yarn add babel-preset-react-native` to fix your issue.

Thanks

**Comment by rshah92** [comment]
Hello, thanks the issues is solved but we currently facing new issues 
"cannot read property bindings of null"
![image](https://user-images.githubusercontent.com/45820236/49920428-2bc38580-fee5-11e8-849d-22e29d7992a9.png)
. Can you help check please? Thanks

**Comment by rshah92** [comment]
any news?

**Comment by luyx2412** [comment]
Hi @rshah92 Can you provide me your Config.js file to check the version library?
Thanks

**Comment by rshah92** [comment]
[Config.zip](https://github.com/inspireui/support/files/2678812/Config.zip)
[Config.zip](https://github.com/inspireui/support/files/2678815/Config.zip)

**Comment by minhcasi** [comment]
Dear @rshah92 i'm sorry for the delay response, this issue is caused by missing the .babelrc setting, please help to try running the project from the fresh download package, then it will work - let us know your checking and reopen the ticket if it is not worked - very best!

**Comment by rshah92** [comment]
Yes, its worked now thanks :)
