### ISSUE TITLE
[FluxStore-woocommerce] - issue with connection with my web 

### ISSUE THREAD

**Issue by EhapAlazerk11** [inspireui/support#950]
hello,
i am trying to connect fluxStore app with my website (WooCommerce) i follow the doc in the link
https://docs.inspireui.com/fluxstore/woocommerce-setup , but in doc setup they say change the 
server section in config.json but i do not find this part in the file,  but i find in config.dart section 
serverConfig the content must change with my custom web and consumerKey and consumerSecret when change it and run the app the do not find any category and also change the id with my own category id but still not work .

this screen for the app run 
1-this for category 

![20190819_181111_rmscr 1](https://user-images.githubusercontent.com/44509298/63287803-88b8dc00-c2bb-11e9-99d6-a5cdc162ea99.jpg)

2-this for home page she still load all time do not get data 

![20190819_181102_rmscr 1](https://user-images.githubusercontent.com/44509298/63287108-d0d6ff00-c2b9-11e9-81ce-5ee77203d38f.jpg)

this the config.json file -->

[config.json.txt](https://github.com/inspireui/support/files/3517039/config.json.txt)

this the config.dart file  -->

[config.dart.txt](https://github.com/inspireui/support/files/3517040/config.dart.txt)

this the screen for my comment: 

![screen](https://user-images.githubusercontent.com/44509298/63287673-2fe94380-c2bb-11e9-8c8b-5a2b4cbfc2d6.png)

**Comment by minhtruong315** [comment]
@EhapAlazerk11 I can not access your website: http://ksaprint.com/new

**Comment by EhapAlazerk11** [comment]
this issue solved but the data in list get text data and images don't show in home page must click to open details to show image in the document they said enable Reganerate thempuable for image different size I made this but the issue still don't work.

**Comment by minhtruong315** [comment]
But i can not access your website, how to check your issues?

**Comment by EhapAlazerk11** [comment]
This data to admin panel :
http://Ksaprints.com/new/wp-admin
User name : new
Password : newprints++1

**Comment by EhapAlazerk11** [comment]
@inspireui/support I send mail to this account with data you need to access to admin panel

**Comment by minhtruong315** [comment]
@EhapAlazerk11 Pls use this config
http://ksaprint.com/new
ck_850b1110c3cf129b1198a6d887b5db81a6537e22
cs_1d4c63c04d4871624bca98130bed6682ac002e2c

**Comment by minhtruong315** [comment]
@EhapAlazerk11 Your website can not generate thumbnail correctly. So you need to ignore showing image with thumbnail.
You can edit formatImage function in lib/common/tools.dart
```
static String formatImage(String url, [kSize size = kSize.medium]) {
    if (serverConfig["type"] == "woo") {
      String pathWithoutExt = p.withoutExtension(url);
      String ext = p.extension(url);
      String imageURL = url ?? kDefaultImage;
      return imageURL;
    } else {
      return url;
    }
  }
```

**Comment by EhapAlazerk11** [comment]
the change is work thanks but in category the background image do not show if it change from the app or from the api request 
![20190821_154130_rmscr 1](https://user-images.githubusercontent.com/44509298/63437119-3ea23880-c42a-11e9-935c-285ceaeb0c8d.jpg)

**Comment by minhtruong315** [comment]
@EhapAlazerk11 did you upload image for category in website?
