### ISSUE TITLE
Compatiblity with other Wordpress Plugins

### ISSUE THREAD

**Issue by MartinCastellon** [inspireui/support#951]
Hi. I use a plugin that provides one of the main functionalities to the project, which is to accumulate points for each purchase, and use them later to buy more products. The name of the plugin is MyCred. Is this template compatible with other wordpress plugins such as MyCred?

**Comment by minhcasi** [comment]
Hi, we are going to integrate with the WooCommerce Point & Reward https://woocommerce.com/products/woocommerce-points-and-rewards/ - on next version release of the Fluxstore Pro.

Other plugins will be consider like the Sumu, yith points and rewards 

How do you think about this integration? Is the MyCred better than other one ? - Thank  you!

**Comment by MartinCastellon** [comment]
What I like about MyCred is that it is open source and free. For a startup is a good option to start. Nevertheless, woocommerce points and rewards seems to be more reliable and has more configuration options that seem fun to play around with. WooPoints is required a premium price once, but gives you everything out of the box. Without needing to buy "add-ons" for this specific functionality. 

I would love to see this on your app template. Is there anyway that I can integrate this plugins with Fluxstore pro myseld. I am really new to flutter and dart.  But would love to try and learn in the process. By the way, when can this new release be coming up? I will purchase the template as soon as it is released :D

**Comment by minhcasi** [comment]
Thank you, confirm that the WooCommerce Point Reward will be available on next 1.5 - thank you!
