### ISSUE TITLE
[EvaStore] - Problem in Setup

### ISSUE THREAD

**Issue by davekedar** [inspireui/support#952]
I have recently purchased and can't get setup done as per the instruction 
f4a36d6d-6f68-46fd-98c3-234853b0affc

I have read the document and this the code snippet 
```
{
  "Shopify": {
    "url": "https://proj-jules-james.myshopify.com",
    "graphqlUrl": "https://proj-jules-james.myshopify.com/api/2019-07/graphql.json",
    "storeAccessToken": "5a3c93b0e9bc8d5abf63531fcd829b5d",
    "shopId": "18754399"
  }
}
```

Please help is there any thing else i have to change? and what is shopid?

**Comment by minhcasi** [comment]
Hi, looks like the graphURL is not correctly, please try with: https://proj-jules-james.myshopify.com/api/graphql

We will remove the shopId as it is using for the demo stuff. 

Thank you!

Document Ref: https://docs.inspireui.com/evastore/getting-started/

**Comment by davekedar** [comment]
still it is not working, can I get any help of installing graphql?

**Comment by minhcasi** [comment]
Hi, could you help to double-check this guide - https://help.shopify.com/en/api/storefront-api/getting-started

**Comment by kuttim** [comment]
@davekedar @minhcasi The graphql path needs to be /api/graphql so for you, the full path should be:     
    `"graphqlUrl": "https://proj-jules-james.myshopify.com/api/graphql",`
I had a digging in the docs too, the specific url that I've mentioned earlier returns 404 but it works, that's what I'm using as well.
You can get your shop id when you go to ```https://proj-jules-james.myshopify.com/admin/shop.json``` it returns a json object, which has your shop information, the one specific what you're looking for starts with: ```{"shop":{"id":xx,```

Hope this helps!

**Comment by davekedar** [comment]
I have done those changes

```
{
  "Shopify": {
    "url": "https://proj-jules-james.myshopify.com",
    "graphqlUrl": "https://proj-jules-james.myshopify.com/api/graphql",
    "storeAccessToken": "2cac76e1a5a2036570d8dc1b57f149bf",
    "shopId": "26676068445"
  }
}
```

this is the final version of my `appconfig.json`

but still I can't see products, it is loading products from demo site, not even layout change works

**Comment by kuttim** [comment]
@davekedar Can you show me your constants.js file? It is located under src/common

**Comment by davekedar** [comment]
```
/**
 * Created by InspireUI on 20/12/2016.
 *
 * @format
 */

import { Dimensions } from "react-native";

const Constants = {
  nameStore: "EvaStore",
  RTL: false, // default to set redux. Only use first time
  useReactotron: true,
  Language: "English", // Arabic, English. Default to set redux. Only use first time
  fontFamily: "Dosis",
  fontFamilyBold: "Dosis-Bold",
  fontHeader: "Baloo",
  fontHeaderAndroid: "Baloo",
  isDefaultStore: false,
  EmitCode: {
    Toast: "toast",
  },
  Dimension: {
    ScreenWidth(percent = 1) {
      return Dimensions.get("window").width * percent;
    },
    ScreenHeight(percent = 1) {
      return Dimensions.get("window").height * percent;
    },
  },

  LimitAddToCart: 100,
  ShowQuickCart: false, // show hide quick add to cart in product item

  PostImage: {
    small: "small",
    medium: "medium",
    medium_large: "medium_large",
    large: "large",
  },
  Layout: {
    card: 1,
    twoColumn: 2,
    simple: 3,
    list: 4,
    advance: 5,
    threeColumn: 6,
    horizon: 7,
    twoColumnHigh: 8,
    miniBanner: 9,
  },
  pagingLimit: 10,

  fontText: {
    size: 16,
  },
};

export default Constants;

```

**Comment by kuttim** [comment]
Change ```isDefaultStore``` from ```false``` to ```true``` and it should fix it.

**Comment by davekedar** [comment]
something happened after that, it goes black, means something is progressing, I am happy :)

**Comment by kuttim** [comment]
Keep us updated. 👍

**Comment by davekedar** [comment]
there is nothing at all in the document, and there are few places where it has written to integrate few things from wordpress, I don't know why

**Comment by kuttim** [comment]
The wordpress is for the custom links at your left sidebar, like the one that has title "About us"

**Comment by davekedar** [comment]
how to fetch categories? or collection and how to set the front page?

**Comment by kuttim** [comment]
It automatically fetches the products from your shopify.
You can create new collections on your shopify admin panel and it will reflect on your application as well.
What do you mean by front page? Elaborate.
Also you use discord?

**Comment by davekedar** [comment]
you mean this?

https://discordapp.com/

**Comment by kuttim** [comment]
@davekedar Yeah, so we don't clog up the comments.

**Comment by davekedar** [comment]
how can i add u in discord?

**Comment by kuttim** [comment]
![image](https://user-images.githubusercontent.com/41844956/63575078-dec6a180-c591-11e9-83ea-d5d18419ad48.png)
![image](https://user-images.githubusercontent.com/41844956/63575090-e8e8a000-c591-11e9-8964-8070ebe8ca91.png)
And once you click on it, it wants the username to add
Write: Mikk#6882

**Comment by davekedar** [comment]
this is still not working, where can i get the help? you don't have proper documentation for the same as well @minhcasi

**Comment by Jimmy430** [comment]
@kuttim hi, i also have problem to setup my store, after i changed the field "isDefaultStore" to true, there is nothing show in my landing page, how could i fix this?

**Comment by kuttim** [comment]
Are you using Discord or Slack?
Mikk
#6882

**Comment by Jimmy430** [comment]
hi @kuttim , have sent you invite from discord just now, my user ID is jimmy90321#2396
