### ISSUE TITLE
[Beonews] - Error Message. Please help.

### ISSUE THREAD

**Issue by kevlict** [inspireui/support#953]
I encounter this error message after integration

![unnamed](https://user-images.githubusercontent.com/54314498/63343061-abacc400-c37f-11e9-8683-b77162a8354c.jpg)

How can I Fix this?

Thanks!

**Comment by minhtruong315** [comment]
hi @kevlict send me your screenshot of the purchase product

**Comment by kevlict** [comment]
Hello

Please see here:


Kevin

「minhtruong315 <notifications@github.com>」在 2019年8月22日 週四，下午1:14 寫道：

**Comment by minhtruong315** [comment]
Dont see anything

**Comment by kevlict** [comment]
「minhtruong315 <notifications@github.com>」在 2019年8月22日 週四，下午1:14 寫道：

**Comment by minhtruong315** [comment]
<img width="657" alt="Screen Shot 2019-08-22 at 12 20 49" src="https://user-images.githubusercontent.com/10402500/63487939-4d92f480-c4d7-11e9-9f70-0a62b9be462c.png">

**Comment by kevlict** [comment]
Please find the attached.

Thanks
Kevin

**Comment by minhtruong315** [comment]
@kevlict pls send me video record

**Comment by kevlict** [comment]
Sure

Video
https://vimeo.com/355686086

Kevin
「minhtruong315
<notifications@github.com>」在 2019年8月23日 週五，上午11:26 寫道：

**Comment by kevlict** [comment]
@minhtruong315 how can i fix this?

**Comment by minhtruong315** [comment]
@kevlict Did you install these plugin?
https://docs.inspireui.com/beonews/wordpress-setting/

**Comment by kevlict** [comment]
Yes, all of them.

Kevin

「minhtruong315 <notifications@github.com>」在 2019年8月30日 週五，上午9:47 寫道：

**Comment by minhtruong315** [comment]
@kevlict can you send me AppConfig.json and config.js file via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/953

**Comment by minhtruong315** [comment]
![Simulator Screen Shot - iPhone X - 2019-09-04 at 19 13 48](https://user-images.githubusercontent.com/10402500/64253764-27923900-cf48-11e9-9541-d37cf08e8a96.png)
![Simulator Screen Shot - iPhone X - 2019-09-04 at 19 13 50](https://user-images.githubusercontent.com/10402500/64253765-282acf80-cf48-11e9-8475-56c2048f8c6c.png)
Your config is ok. did you update source code?

**Comment by kevlict** [comment]
Thank you very much!

Did you update source code recently?

Kevin

「minhtruong315 <notifications@github.com>」在 2019年9月4日 週三，下午8:14 寫道：

**Comment by minhtruong315** [comment]
No. i dont update anything. pls download latest source code and check again
