### ISSUE TITLE
[M-store pro] - Shipping methods and Coupons doesn't function same as Woocomerce

### ISSUE THREAD

**Issue by Gmlogy** [inspireui/support#954]
Mstore:
65ae6467-f067-450f-aa9d-6528a5ba0736
---------

1. My issue
My website has 2 Shipping methods, Flat rate and free shipping. my Woocommerce settings is flat rate for item(s) lower than 200$ and free for item(s) higher than 200$, it's works perfectly on website but when i do the same operation using the App the Woocommerce rules doesn't function same as the website, i don't know why but i know that i need to make changes on this file :
container/Cart/Delivery/index.js
My question is: please can you help me with the code that i will put /or change here container/Cart/Delivery/index.js to make the app works same as the website i can put the code myself i just need what i will put there, thank's in advance

2.My second issue
in my Woocommerce settings i have a rule that allows using a coupon for only one time, but in the app the user can use the same coupon for many times 
please how can i make this rule applied same as the website and which file i need to change the code within  

what is more important is the first Issue please i will waiting for your answer. thank's

**Comment by minhcasi** [comment]
Could you help to share your config file for further investigating?

@concuacon

**Comment by Gmlogy** [comment]
if you mean the config.js file in Common folder, here is it : 
https://www.mediafire.com/file/r8dwohu9t3q6i55/Config.js/file

**Comment by Gmlogy** [comment]
hello ??

**Comment by concuacon** [comment]
Hello @Gmlogy i'm checking this issue, can you attach more to me file AppConfig.json?

**Comment by Gmlogy** [comment]
[AppConfig.zip](https://github.com/inspireui/support/files/3551358/AppConfig.zip)
here is it, thanks

**Comment by concuacon** [comment]
Hello @Gmlogy please give me your email, i'll send to you source fixed.
Thank you,

**Comment by Gmlogy** [comment]
cherkamal4@gmail.com

**Comment by Gmlogy** [comment]
@concuacon Thank you so much, but still not working!

- in the app users can bypass the woocommerce rules just by choosing the other option for example :
someone buying items for 100$ in website he will be charging for delivery fees but in app he can choose manually the free delivery service(in website the system choose the action and apply delivery fees if a user buy something under 200$ / in application users choose the action and can bypass the woocommerce rules by buying something under 200$ and choosing the free service)
all what i want is that the app function same as the site not allowing users to bypass the rules (like a hack) 
- the same thing with coupons for example:
i made a coupon for one time use (in website users can use the coupon only one time, while in app users can use the same coupon for many time ( is also look like a hack that bypass Woocommerce rules)
thank's for your time and you help

**Comment by concuacon** [comment]
@Gmlogy i understood i would check it again.

**Comment by minhcasi** [comment]
@Gmlogy - as this is advance login for each store, we suggest to custom the feature's base on your business, we marked as the 'enhancement' feature for further upgrading, thank you!

**Comment by Gmlogy** [comment]
@minhcasi -I didn't understand well? before purchasing Mstore i saw in product features "Woocommerce full integration" for me this is not a full integration, i can't just publish an App that not function as my website. at least can i know whichthe responsible files that i will change the code within?

**Comment by minhcasi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Shipping methods and Coupons](https://trello.com/c/1zXCDfDd/8-shipping-methods-and-coupons)

**Comment by minhcasi** [comment]
we are closing the ticket and move this ticket 'request feature' to our Trello board for easier to keep track, review, and update, also keep a status update  - thank you!
