### ISSUE TITLE
[EvaStore] - Menu side

### ISSUE THREAD

**Issue by alaaeallam** [inspireui/support#955]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue
when I'm
![IOS](https://user-images.githubusercontent.com/10725570/63359192-9d08e180-c36c-11e9-982b-2ff973da0708.jpeg)
![Andriod](https://user-images.githubusercontent.com/10725570/63359200-a09c6880-c36c-11e9-8c23-73a8e6bfce5e.jpeg)
![Andriod](https://user-images.githubusercontent.com/10725570/63359215-a85c0d00-c36c-11e9-824e-0f3df7cfe02f.jpeg)

 changing the background color for the menu side bar, it changed on iPhone but not changed on Android 
2. Screenshots

3. My screenshot of the purchase product or my comment:

3. Config files (optional)

**Comment by minhtruong315** [comment]
@alaaeallam the menu side background based on primary color. if you want to change menu background, you need to change primary in common/Color.js. Then you must uninstall app, then install again. primary color only work when you open app the first
