### ISSUE TITLE
FLUXSTORE PRO

### ISSUE THREAD

**Issue by samik9** [inspireui/support#957]
**This is a request:**

Slider should move automatically and time must be set from json file

**Comment by samik9** [comment]
**Request 2**

- Support for gifs for banners on homescreen

- support for autoplay videos on product page

**Comment by minhcasi** [comment]
Thank you for your suggestion, we will investigate and update on next 1.5 release

**Comment by samik9** [comment]
**Request 3**

On icons for category will be nice an option to use this tipo of colorfull icons, at the moment is not posible cause color is overwriten by json config.  For example an option that says,
 "original color": true,

At the moment is there any solution i can use? @minhcasi 

![conjunto-iconos-cosmeticos_1284-13267](https://user-images.githubusercontent.com/50071744/63394932-99cf1f00-c387-11e9-8584-6e9650f1974d.jpg)

**Comment by minhcasi** [comment]
Support on latest release - thank you!
