### ISSUE TITLE
[BeoNews Pro] - Blank page when click "+" button on Customization

### ISSUE THREAD

**Issue by outlawcode** [inspireui/support#958]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue

Blank page when click "+" button on Customization on CeBuilder

2. Screenshots

3. My screenshot of the purchase product or my comment:

https://i.postimg.cc/pX8SpfGM/Screenshot-2019-08-21-at-2-37-18-PM.jpg

3. Config files (optional)

**Comment by minhtruong315** [comment]
@outlawcode can you send me your source code via email truong@inspireui.com

**Comment by outlawcode** [comment]
> @outlawcode can you send me your source code via email [truong@inspireui.com](mailto:truong@inspireui.com)

I haven't change anything yet. Its default source downloaded from codecanyon. 

Thank you!

**Comment by minhcasi** [comment]
@minhtruong315 - it could be the issue from CeBuilder

@outlawcode - pls try to run the project manually via the script "yarn install && yarn start" from the project folder

**Comment by outlawcode** [comment]
Still can not make it working from begin.
https://i.postimg.cc/CLw6rC1f/Screenshot-2019-08-27-at-7-57-04-PM.jpg
Please check asap.
Not able to running till bought it.

Vui lòng trợ giúp người Việt các bạn nhé. Không thể dùng được từ khi mua tới giờ.
Tôi muốn dùng công cụ Cebuilder vì có quảng cáo "không cần dùng tới code".

Xin cảm ơn!

**Comment by outlawcode** [comment]
Hey?

**Comment by outlawcode** [comment]
????

**Comment by minhtruong315** [comment]
Hi @outlawcode we will fix cebuilder, then send you update soon. thanks
