### ISSUE TITLE
[MStore Magento] - cebuilder issue

### ISSUE THREAD

**Issue by nmclibya** [inspireui/support#959]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue

hi 
when i tray to setup 1 i get error message The Rest API is not working correctly !
and when i go to customization i got other error MSG "the consumer isn't authorized to access %resources"
I still in the beginning , so the configuration file still the same.

2. Screenshots

![Capture](https://user-images.githubusercontent.com/54356166/63424003-c7f74200-c40d-11e9-8ecd-951ad823e0c7.PNG)
![Capture1](https://user-images.githubusercontent.com/54356166/63424004-c7f74200-c40d-11e9-94f2-99a26b610b09.PNG)
![Capture2](https://user-images.githubusercontent.com/54356166/63424005-c88fd880-c40d-11e9-9549-02602b73d70e.PNG)
![Capture3](https://user-images.githubusercontent.com/54356166/63424006-c88fd880-c40d-11e9-98a5-72fb58b977f7.PNG)

3. My screenshot of the purchase product or my comment:

3. Config files (optional)

**Comment by minhtruong315** [comment]
Hi @nmclibya Did you install Mstore extensions?

**Comment by nmclibya** [comment]
hi @minhtruong315  where i can fine the extensions? link to download pleas

**Comment by minhtruong315** [comment]
Hi @nmclibya https://www.dropbox.com/s/mrsdxwnqfgmpzbu/Mstore-magento.zip?dl=0
1. Rename Mstore-magento to Mstore folder.
2. Copy Mstore plugin folder to app/code folder
3. Run this command in website directory: php bin/magento setup:upgrade
