### ISSUE TITLE
[LISTAPP - 

### ISSUE THREAD

**Issue by hachikaru** [inspireui/support#960]
Since January i bought the listapp i have been trying since to set it up i have tried both manual and cebuilder guide still not getting any result please i need help urgently
THIS IS MY PURCHASE CODE : 45c7c7ac-5a00-40a2-af23-8111ef3e5d28

**Comment by theAlinux** [comment]
what is the problem?

**Comment by theAlinux** [comment]
can you share the screenshots?

**Comment by hachikaru** [comment]
OK I WILL SEND THE SCREENSHOOTS ASAP. THANKS FO YOUR QUICK RESPONSE
