### ISSUE TITLE
Image Banner - 2 columns - not showing in one row

### ISSUE THREAD

**Issue by preetindersodhi** [inspireui/support#961]
What should be the size of the image? The URLs in "2-Banner Image.json" no longer work.

Here's the code:
{
"imageBanner": "URL-here",
"column": 2,
"height": 100,
"layout": "bannerImage",
"category": 38
},
{
"imageBanner": "URL-here",
"column": 2,
"height": 100,
"layout": "bannerImage",
"category": 38
},

Tried using different values of height. and removing the value as well. Still doesn't work.

{
"imageBanner": "URL-here",
"column": 2,
"layout": "bannerImage",
"category": 38
},
{
"imageBanner": "URL-here",
"column": 2,
"layout": "bannerImage",
"category": 38
},

**Comment by minhcasi** [comment]
@concuacon

**Comment by minhcasi** [comment]
@preetindersodhi - could you help to share the real config file from your side ? Thanks

**Comment by preetindersodhi** [comment]
[AppConfig.zip](https://github.com/inspireui/support/files/3532863/AppConfig.zip)

**Comment by preetindersodhi** [comment]
APK: https://bit.ly/2Z5PrTo

**Comment by preetindersodhi** [comment]
Please respond.

**Comment by preetindersodhi** [comment]
Kindly respond, I'm waiting to launch the app, as soon as this issue is resolved.

**Comment by preetindersodhi** [comment]
@minhcasi @concuacon  Please help. This is a basic feature in your app, I'm using the same code you provided, it should be working.

**Comment by morehere** [comment]
I am also having same issue.
@preetindersodhi Did you get solution?

**Comment by preetindersodhi** [comment]
No help from app authors so far. Disappointed.

**Comment by concuacon** [comment]
Hello @preetindersodhi, sorry for the late reply, 
I fixed it and send you 2 file fixed to your app working 
in path: **src/components/HorizonLayout/BannerImage.js**
[BannerImage.js.zip](https://github.com/inspireui/support/files/3545370/BannerImage.js.zip)
in path: **src/components/HorizonList/styles.js**
[styles.js.zip](https://github.com/inspireui/support/files/3545375/styles.js.zip)

**Comment by concuacon** [comment]
we will update it at later version.

**Comment by preetindersodhi** [comment]
thanks a lot. :)

**Comment by preetindersodhi** [comment]
Check the landscape mode as well before you release the next version.
