### ISSUE TITLE
[Evastore] - 

### ISSUE THREAD

**Issue by kuttim** [inspireui/support#962]
1. My issue - Not being able showcase the products successfully, using latest LTS of node.

2. Screenshots https://i.imgur.com/1FYFNbx.jpg

3. My screenshot of the purchase product or my comment: https://codecanyon.net/comments/22674914

3. Config files (optional) Not much of configuration to show off, this is indentical that you have on codecanyon.

**Comment by minhcasi** [comment]
Hi, please try to re-install the node 10.x instead - https://nodejs.org

Pls also share your config file so that we could help to check

**Comment by kuttim** [comment]
The latest LTS is  10.x
There's no config to share, this is the default config that came with the project upon purchase.

**Comment by kuttim** [comment]
Seems like using v10.16.2 fixed it.
