### ISSUE TITLE
[FluxStore-woocommerce] still no update !

### ISSUE THREAD

**Issue by peter2411** [inspireui/support#963]
1. My issue

it’s wednesday , and still no update ! i got your message via email 3 days ago “we have fixed the issue and will update the patching on Monday – very best!” 

2. My screenshot of the purchase product or my comment:
https://prnt.sc/ovplww

**Comment by minhcasi** [comment]
Hi Peter, please download the latest 1.4.2 today, sorry for some delay as we skip the 1.4.1 to upgrade more bug fixed

Thank you for your patient.

**Comment by minhcasi** [comment]
v1.4.2 is available to updated

Please note there is a new v1.5 supper powerful feature is coming along - thank you!
