### ISSUE TITLE
Error: Not found: 'dart:ui'

### ISSUE THREAD

**Issue by amas2000** [inspireui/support#964]
I'm trying to run the app in AVD but I got this error. Please help me.

"C:\Program Files\Dart\dart-sdk\bin\dart.exe" --enable-asserts --enable-vm-service:64670 "C:\Users\amas2\Desktop\Projects\R&D\FluxStore\FluxStore 1.4.1\source\lib\main.dart"
Observatory listening on http://127.0.0.1:64670/b2L9Qplmv0A=/

lib/main.dart: Warning: Interpreting this as package URI, 'package:fstore/main.dart'.
file:///C:/src/flutter/packages/flutter/lib/src/material/animated_icons.dart:9:8: Error: Not found: 'dart:ui'
import 'dart:ui' as ui show Paint, Path, Canvas;
       ^
file:///C:/src/flutter/packages/flutter/lib/src/material/animated_icons.dart:10:8: Error: Not found: 'dart:ui'
import 'dart:ui' show lerpDouble;
       ^
file:///C:/src/flutter/packages/flutter/lib/src/material/app.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui' as ui;
       ^
file:///C:/src/flutter/packages/flutter/lib/src/material/app_bar_theme.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui' show lerpDouble;
       ^
file:///C:/src/flutter/packages/flutter/lib/src/material/arc.dart:6:8: Error: Not found: 'dart:ui'
import 'dart:ui' show lerpDouble;
       ^
file:///C:/src/flutter/packages/flutter/lib/src/material/bottom_app_bar_theme.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui' show lerpDouble;
       ^
file:///C:/src/flutter/packages/flutter/lib/src/material/bottom_sheet_theme.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui' show lerpDouble;
       ^
file:///C:/src/flutter/packages/flutter/lib/src/material/card_theme.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui' show lerpDouble;
       ^
file:///C:/src/flutter/packages/flutter/lib/src/material/chip_theme.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui' show lerpDouble;
       ^
file:///C:/src/flutter/packages/flutter/lib/src/material/colors.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui' show Color;
       ^

Process finished with exit code 254

**Comment by kuttim** [comment]
Not collaborator to this project but try [this](https://stackoverflow.com/questions/52483773/dartui1-error-not-found-dartui-flutter-dart)

**Comment by minhcasi** [comment]
@amas2000 pls try to reinstall the Flutter by using this guide - https://flutter.dev/docs/get-started/install

Also, make sure you pass the "Test Drive" guideline 

Thanks

**Comment by amas2000** [comment]
Hi,

Thank you both Kuttim and Minhcasi. Now, it works. It looks like the Flutter SDK path wasn't correct for some reasons. 

However, I got a new issue related to Gradle! See below message. Is that related to my system or it is a common problem?

**Finished with error: ProcessException: Process "C:\Users\amas2\Desktop\Projects\R&D\FluxStore\FluxStore 1.4.1\source\android\gradlew.bat" exited abnormally:
The system cannot find the path specified.
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
  Command: C:\Users\amas2\Desktop\Projects\R&D\FluxStore\FluxStore 1.4.1\source\android\gradlew.bat -v**

Please assist me in this. 

Thanks again.

**Comment by minhcasi** [comment]
Hi @amas2000 - could you follow by these link to check this issue?

https://flutter.dev/docs/get-started/install/windows
https://flutter.dev/docs/get-started/editor?tab=vscode
