### ISSUE TITLE
Fluxstore pro - products not visible in category page

### ISSUE THREAD

**Issue by tjain90** [inspireui/support#965]
On category product page it shows no product while on filter it has all the categories with no of products on right side.

I have provided access code from Magento 2.3 admin panel as mentioned in document.

**Comment by minhcasi** [comment]
Hi, could you help to share your config file so that we could help for checking - thank you!

**Comment by tjain90** [comment]
Here it is :
`import 'package:fstore/common/constants.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';


const serverConfig = {
  "type": "magento",
  "url": "https://www.indidecor.com",
  "accessToken": "ebXXXXXXXXXXXXXX9"
};

const CategoriesListLayout = kCategoriesLayout.card;

const Payments = {
  "paypal": "assets/icons/payment/paypal.png",
  "stripe": "assets/icons/payment/stripe.png",
  "razorpay": "assets/icons/payment/razorpay.png",
};


const kAdvanceConfig = {
  "DefaultCurrency": {"symbol": "\$", "decimalDigits": 2},
  "IsRequiredLogin": false,
  "GuestCheckout": true,
  "EnableShipping": false,
  "GridCount": 3,
  "DetailedBlogLayout": kBlogLayout.halfSizeImageType
};


/// The product variant config
const ProductVariantLayout = {
  "color": "color",
  "size": "box",
  "height": "option",
};


/// The Google API Key to support Pick up the Address automatically
/// We recommend to generate both ios and android to restrict by bundle app id
/// The download package is remove these keys, please use your own key
const kGoogleAPIKey = {
  "android": "your-google-api-key",
  "ios": "your-google-api-key"
};

/// use to config the product image height for the product detail
/// height=(percent * width-screen)
/// isHero: support hero animate
const kProductDetail = {
  "height": 0.5,
  "marginTop": 0,
  "isHero": false,
  "safeArea": false,
  "showVideo": true,
};

/// config for the chat app
const smartChat = [
  {'app': 'whatsapp://send?phone=84327433006', 'iconData': FontAwesomeIcons.whatsapp},
  {'app': 'tel:8499999999', 'iconData': FontAwesomeIcons.phone},
  {'app': 'sms://8499999999', 'iconData': FontAwesomeIcons.sms},
  {'app': 'firebase', 'iconData': FontAwesomeIcons.google},
  {'app': 'intercome', 'iconData': FontAwesomeIcons.intercom},
];
const String adminEmail = "admininspireui@gmail.com";
const kIntercomAPIKey = {
  'android': 'android_sdk-2c16c0e017a1e7b8d3b73b5a13a56b54cbf535c0',
  'ios': 'ios_sdk-33135e6653b055cec773b7903baff10efee94bc0',
  'appID': 'xro9xnfd'
};

/// the welcome screen data
List onBoardingData = [
  {
    "title": "Welcome to FluxStore",
    "image": "assets/images/fogg-delivery-1.png",
    "desc": "Fluxstore is on the way to serve you. "
  },
  {
    "title": "Connect Surrounding World",
    "image": "assets/images/fogg-uploading-1.png",
    "desc": "See all things happening around you just by a click in your phone. "
        "Fast, convenient and clean."
  },
  {
    "title": "Let's Get Started",
    "image": "fogg-order-completed.png",
    "desc": "Waiting no more, let's see what we get!"
  },
];`

**Comment by tjain90** [comment]
New Version is throwing woocommerce error even in Magento Config. So i am using order version. I have attached snapshot showing category is visible but no product on page.
![Screenshot_20190823-230411](https://user-images.githubusercontent.com/6376301/63612242-6dbbd400-c5fb-11e9-8536-ec04b1060a66.png)
![Screenshot_20190823-230419](https://user-images.githubusercontent.com/6376301/63612243-6e546a80-c5fb-11e9-9d16-d36821ae3059.png)

**Comment by minhcasi** [comment]
@minhtruong315

**Comment by minhcasi** [comment]
@tjain90 - could you help to send the accessToken to our private email support@inspireui.com - we could not check the issue without the keys - thank you!

**Comment by minhtruong315** [comment]
@tjain90 can you send me config.json and config.dart file via email truong@inspireui.com

**Comment by tjain90** [comment]
Email Sent. Kindly review.

**Comment by minhtruong315** [comment]
@tjain90 you haven't installed mstore plugin yet. Please install it.
- Copy Mstore plugin folder to app/code folder
- Run this command in website directory: php bin/magento setup:upgrade

**Comment by tjain90** [comment]
Hi,

I have installed mstore plugin as well but still no product is shown.

Also there was no additional setting tab in my Magento admin panel?

**Comment by minhtruong315** [comment]
@tjain90 can you resend config file? I dont see it in my inbox

**Comment by tjain90** [comment]
As asked earlier,

I have sent email with config files to truong@inspireui.com and
support@inspireui.com. can you please your email  so that I can send it to
you as well.

**Comment by tjain90** [comment]
Hi Team,

Any update on this ? I am sending again in case you have missed that.

Sent from Mail for Windows 10

**Comment by tjain90** [comment]
[common.zip](https://github.com/inspireui/support/files/3562379/common.zip)
Config Attached.

**Comment by minhcasi** [comment]
Thank you @tjain90 - we will have a check and let you know

@minhtruong315

**Comment by minhtruong315** [comment]
@tjain90 i check your config. it hasn't installed mstore plugin yet. Can you record video for reinstall mstore plugin?

**Comment by tjain90** [comment]
Can you confirm how can we check if it installed or not ? Do it will be
shown right side of Magento admin panel in the name of mstore ?

**Comment by tjain90** [comment]
Because I have resintalled it and cannot see anything in my admin panel

**Comment by minhtruong315** [comment]
it doesn't show in admin panel. 
- Copy Mstore plugin folder to app/code folder
- Run this command in website directory: php bin/magento setup:upgrade
Pls record screen these steps.

**Comment by tjain90** [comment]
Tried this steps multiple times. No success. Kindly Consider it on priority.
Here is the link of video i have created.
https://www.dropbox.com/sh/375o7688rfqwkvw/AABAI1L_Z7tD4aY0vntKHokva?dl=0

**Comment by minhtruong315** [comment]
<img width="537" alt="Screen Shot 2019-09-05 at 22 08 38" src="https://user-images.githubusercontent.com/10402500/64354487-be82f200-d029-11e9-92ff-02a562ff306c.png">
do you see Mstore plugin?

**Comment by tjain90** [comment]
Yes it is available . Please see snapshot attached. There is some other issue I guess 
![Screenshot_20190905-210216](https://user-images.githubusercontent.com/6376301/64356713-f6d20280-d020-11e9-91b0-bd05a15ae5f4.png)

**Comment by minhtruong315** [comment]
@tjain90 I see your Mstore plugin is so old. did you get the latest source? or you can give me your email, i will send it

**Comment by tjain90** [comment]
Yes please provide me at tjain90@gmail.com

**Comment by minhtruong315** [comment]
pls update Mstore plugin
