### ISSUE TITLE
Issue in Fluxpro 1.4.2

### ISSUE THREAD

**Issue by anandnathtiwari** [inspireui/support#967]
Please see the error detail and suggest
this issue raise when I compile fluxpro 1.4.2 in android studio

Launching lib\main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

Compiler message:
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_widgets-0.1.5/lib/src/visibility_detector/src/visibility_detector_layer.dart:277:18: Error: This expression has type 'void' and can't be used.
    return super.addToScene(builder, layerOffset);
                 ^
Compiler failed on C:\flutterproj\FluxStore 1.4.2\source\lib\main.dart

FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 765

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebugX86'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 43s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by minhtruong315** [comment]
@anandnathtiwari Did you follow by these step?
https://flutter.dev/docs/get-started/install/windows

**Comment by anandnathtiwari** [comment]
Yes,
previous version work. but 1.4.2 not.

**Comment by minhtruong315** [comment]
@anandnathtiwari can you add my skype: minhtruong315. i will help you check it via teamviewer

**Comment by anandnathtiwari** [comment]
I added your skype id. please help me.

**Comment by minhtruong315** [comment]
@anandnathtiwari i dont see. pls send me your skype

**Comment by anandnathtiwari** [comment]
anand.nath.tiwari

**Comment by minhtruong315** [comment]
<img width="467" alt="Screen Shot 2019-08-23 at 17 39 18" src="https://user-images.githubusercontent.com/10402500/63586971-f707e200-c5cc-11e9-82bd-46a37eb4e1f7.png">

**Comment by anandnathtiwari** [comment]
first one from top

**Comment by minhtruong315** [comment]
added

**Comment by minhtruong315** [comment]
@anandnathtiwari we will release next version next week. You can update it

**Comment by anandnathtiwari** [comment]
Ok
