### ISSUE TITLE
[EvaStore] Horizontal layout empty!

### ISSUE THREAD

**Issue by alisa140** [inspireui/support#968]
I’m trying to changed the homepage to Horizontal layout but not yet able to achieve this. I have followed the documentation and I’m able to retrieve my CollectionIDs from GraphiQL. However, when I run the app, homepage comes empty with no products at all. Could you please help with this problem.

[Config.js.zip](https://github.com/inspireui/support/files/3529764/Config.js.zip)
![Simulator Screen Shot - iPhone Xʀ - 2019-08-22 at 13 58 33](https://user-images.githubusercontent.com/20175601/63509836-cef18380-c4e5-11e9-8d53-7ae9e7f843b1.png)

**Comment by minhcasi** [comment]
@concuacon

**Comment by concuacon** [comment]
Hello @alisa140 we will have a check and let you know

**Comment by alisa140** [comment]
Thanks. Looking forward for your response.

**Comment by concuacon** [comment]
Hi @alisa140 i found solution, please download and copy this file follow path.
path: src/containers/HomeContainer/index.js
[index.js.zip](https://github.com/inspireui/support/files/3558733/index.js.zip)

**Comment by concuacon** [comment]
Hi @alisa140 i found solution, please download and copy this file follow path.
path: src/containers/HomeContainer/index.js
[Uploading index.js.zip…]()

**Comment by alisa140** [comment]
thanks. This file fixed the problem and now I can see the horizontal layout. the new problem now is: the products comes empty although Category IDs are correct. The display all product button work. I'm attaching relevant screenshots:
https://ibb.co/FDWKHhq
https://ibb.co/30Gd9Hs
https://ibb.co/ZW5Xymd

**Comment by nhblock** [comment]
@minhcasi I am experiencing the same issue as @alisa140. The horizontal layout shows blank product tiles in the HomeContainer, but they show up fine if you click through to the collections page and browse all products. This is a new issue in the last couple of days (it worked before)...

**Comment by concuacon** [comment]
Hello @alisa140 can you send me your email, i will send to new source to hot fix this issue and i'll update lastse version.

**Comment by alisa140** [comment]
here it is: alisa140@gmail.com

**Comment by concuacon** [comment]
@alisa140 i sent to you,

**Comment by nhblock** [comment]
@concuacon can you send to me as well? I sent you an email requesting the same hotfix.

**Comment by alisa140** [comment]
Thanks. Two things:

1- the price don't appear properly (see screenshot). There a world “- - infinity” appears after each product price.
