### ISSUE TITLE
Fluxstore error

### ISSUE THREAD

**Issue by ghanchi2000** [inspireui/support#969]
Running "flutter pub get" in source...                              2.4s
Launching lib\main.dart on moto g 7 power in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Built build\app\outputs\apk\debug\app-debug.apk.
I/Choreographer( 1926): Skipped 33 frames!  The application may be doing too much work on its main thread.
Syncing files to device moto g 7 power...
I/OpenGLRenderer( 1926): Initialized EGL, version 1.4
D/OpenGLRenderer( 1926): Swap behavior 2
I/flutter ( 1926): {id: 9356, name: Woo Logo, slug: woo-logo-2, permalink: http://demo.mstore.io/product/woo-logo-2/, date_created: 2013-06-07T18:12:55, date_created_gmt: 2013-06-07T11:12:55, date_modified: 2019-08-21T15:19:00, date_modified_gmt: 2019-08-21T08:19:00, type: simple, status: publish, featured: false, catalog_visibility: visible, description: <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.</p>
I/flutter ( 1926): , short_description: <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.</p>
I/flutter ( 1926): , sku: , price: 35, regular_price: 35, sale_price: , date_on_sale_from: null, date_on_sale_
I/flutter ( 1926): {id: 9356, name: Woo Logo, slug: woo-logo-2, permalink: http://demo.mstore.io/product/woo-logo-2/, date_created: 2013-06-07T18:12:55, date_created_gmt: 2013-06-07T11:12:55, date_modified: 2019-08-21T15:19:00, date_modified_gmt: 2019-08-21T08:19:00, type: simple, status: publish, featured: false, catalog_visibility: visible, description: <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.</p>
I/flutter ( 1926): , short_description: <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.</p>
I/flutter ( 1926): , sku: , price: 35, regular_price: 35, sale_price: , date_on_sale_from: null, date_on_sale_
I/flutter ( 1926): type 'String' is not a subtype of type 'int' of 'index'
I/flutter ( 1926): type 'String' is not a subtype of type 'int' of 'index'
I/flutter ( 1926): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 1926): The following assertion was thrown building UserScreen(dependencies: [InheritedProvider<UserModel>],
I/flutter ( 1926): state: _UserScreenState#53365):
I/flutter ( 1926): The default constructor of ListenableProvider/ChangeNotifierProvider
I/flutter ( 1926): must create a new, unused Listenable.
I/flutter ( 1926): 
I/flutter ( 1926): If you want to reuse an existing Listenable, use the second constructor:
I/flutter ( 1926): 
I/flutter ( 1926): - DO use ChangeNotifierProvider.value to provider an existing ChangeNotifier:
I/flutter ( 1926): 
I/flutter ( 1926): MyChangeNotifier variable;
I/flutter ( 1926): ChangeNotifierProvider.value(
I/flutter ( 1926):   value: variable,
I/flutter ( 1926):   child: ...
I/flutter ( 1926): )
I/flutter ( 1926): 
I/flutter ( 1926): - DON'T reuse an existing ChangeNotifier using the default constructor.
I/flutter ( 1926): 
I/flutter ( 1926): MyChangeNotifier variable;
I/flutter ( 1926): ChangeNotifierProvider(
I/flutter ( 1926):   builder: (_) => variable,
I/flutter ( 1926):   child: ...
I/flutter ( 1926): )
I/flutter ( 1926): 'package:provider/src/listenable_provider.dart':
I/flutter ( 1926): Failed assertion: line 136 pos 14: '!listenable.hasListeners'
I/flutter ( 1926): 
I/flutter ( 1926): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 1926): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 1926): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 1926):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter ( 1926): 
I/flutter ( 1926): When the exception was thrown, this was the stack:
I/flutter ( 1926): #2      __BuilderListenableDelegate&BuilderStateDelegate&_ListenableDelegateMixin.debugCheckIsNewlyCreatedListenable (package:provider/src/listenable_provider.dart:136:14)
I/flutter ( 1926): #3      _BuilderListenableDelegate.startListening (package:provider/src/listenable_provider.dart:124:12)
I/flutter ( 1926): #4      __BuilderListenableDelegate&BuilderStateDelegate&_ListenableDelegateMixin.initDelegate (package:provider/src/listenable_provider.dart:165:24)
I/flutter ( 1926): #5      _DelegateWidgetState._initDelegate (package:provider/src/delegate_widget.dart:118:21)
I/flutter ( 1926): #6      _DelegateWidgetState.initState (package:provider/src/delegate_widget.dart:110:5)
I/flutter ( 1926): #7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4033:58)
I/flutter ( 1926): #8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter ( 1926): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 1926): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 1926): #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 1926): #12     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 1926): #13     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter ( 1926): #14     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
I/flutter ( 1926): #15     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter ( 1926): #16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 1926): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 1926): #18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 1926): #19     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 1926): #20     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter ( 1926): #21     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter ( 1926): #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 1926): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 1926): #24     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5092:14)
I/flutter ( 1926): #25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 1926): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 1926): #27     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5092:14)
I/flutter ( 1926): #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 1926): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 1926): #30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 1926): #31     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 1926): #32     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter ( 1926): #33     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter ( 1926): #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 1926): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 1926): #36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 1926): #37     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 1926): #38     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter ( 1926): #39     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter ( 1926): #40     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:4279:11)
I/flutter ( 1926): #41     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 1926): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 1926): #43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 1926): #44     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 1926): #45     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter ( 1926): #46     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
I/flutter ( 1926): #47     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter ( 1926): #48     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 1926): #49     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 1926): #50     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 1926): #51     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 1926): #52     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter ( 1926): #53     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter ( 1926): #54     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 1926): #55     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 1926): #56     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:1181:36)
I/flutter ( 1926): #57     SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1166:20)
I/flutter ( 1926): #58     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2320:19)
I/flutter ( 1926): #59     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:1159:11)
I/flutter ( 1926): #60     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:354:23)
I/flutter ( 1926): #61     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1715:58)
I/flutter ( 1926): #62     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:796:15)
I/flutter ( 1926): #63     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1715:13)
I/flutter ( 1926): #64     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:343:5)
I/flutter ( 1926): #65     RenderSliverMultiBoxAdaptor.insertAndLayoutChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:489:5)
I/flutter ( 1926): #66     RenderSliverFixedExtentBoxAdaptor.performLayout (package:flutter/src/rendering/sliver_fixed_extent_list.dart:217:17)
I/flutter ( 1926): #67     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 1926): #68     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:406:13)
I/flutter ( 1926): #69     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1334:12)
I/flutter ( 1926): #70     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1252:20)
I/flutter ( 1926): #71     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1496:7)
I/flutter ( 1926): #72     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:765:18)
I/flutter ( 1926): #73     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:346:19)
I/flutter ( 1926): #74     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
I/flutter ( 1926): #75     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:285:5)
I/flutter ( 1926): #76     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1016:15)
I/flutter ( 1926): #77     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:958:9)
I/flutter ( 1926): #78     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:874:5)
I/flutter ( 1926): #82     _invoke (dart:ui/hooks.dart:236:10)
I/flutter ( 1926): #83     _drawFrame (dart:ui/hooks.dart:194:3)
I/flutter ( 1926): (elided 5 frames from class _AssertionError and package dart:async)
I/flutter ( 1926): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 1926): Another exception was thrown: The default constructor of ListenableProvider/ChangeNotifierProvider

**Comment by minhtruong315** [comment]
@ghanchi2000 can you send me config.json and config.dart via email truong@inspireui.com

**Comment by minhtruong315** [comment]
@ghanchi2000 we will release next version next week. You can update it
