### ISSUE TITLE
[ReactXS] ReactNativeBridgeEventPlugin error

### ISSUE THREAD

**Issue by imsam67** [inspireui/support#97]
**Mandatory Info (please complete the following information):**
 - Product: ReactXS React Native UIKit for Material Design 2.0
 - Your Purchased Code: 031c02bf-1fdb-46e5-94c4-dd370647e343 

**Describe the issues**
After the initial installation, as I try to run the app in Expo, I'm getting the following error:

> Unable to resolve "react-native/Libraries/Renderer/shims/ReactNativeBridgeEventPlugin" from "node_modules\react-native-chart-kit\node_modules\react-native-gesture-handler\GestureHandler.js"

**Screenshots**
![error](https://user-images.githubusercontent.com/15844030/49912751-2d476c00-fe59-11e8-8b66-ebd93cc49662.png)

**Comment by luyx2412** [comment]
HI @imsam67 Please remove your `node_modules` and re-install again. Or clean your project follow the article https://gist.github.com/jarretmoses/c2e4786fd342b3444f3bc6beff32098d to fix your issue.
Thanks

**Comment by imsam67** [comment]
First, removed the `node_modules` and then ran `npm install` but that didn't fix the issue. I then tried a few approaches to clean up the project as per the link you sent. Initially, that seemed to have made the issue worse but after running `npm install` a couple of more times, I'm not back to the original problem -- see below:
![error](https://user-images.githubusercontent.com/15844030/49965059-2288e780-feea-11e8-9167-7542a19a9de9.png)

Just to clarify it further, this is not happening initially when I run `npm start`. It happens only after I click:

> Run on Android device/emulator

Initially, I see that the emulator responds and shows some activity. But when it starts creating the JavaScript bundle, I get the error in the screen shot I posted.

**Comment by luyx2412** [comment]
Hi @imsam67 You can using with iOS simulator which is faster and better to see the UI. I will investigate your case, and please provide me your OS information.
Thanks

**Comment by wellmonge** [comment]
> **Mandatory Info (please complete the following information):**
> 
> * Product: ReactXS React Native UIKit for Material Design 2.0
> * Your Purchased Code: 031c02bf-1fdb-46e5-94c4-dd370647e343
> 
> **Describe the issues**
> After the initial installation, as I try to run the app in Expo, I'm getting the following error:
> 
> > Unable to resolve "react-native/Libraries/Renderer/shims/ReactNativeBridgeEventPlugin" from "node_modules\react-native-chart-kit\node_modules\react-native-gesture-handler\GestureHandler.js"
> 
> **Screenshots**
> ![error](https://user-images.githubusercontent.com/15844030/49912751-2d476c00-fe59-11e8-8b66-ebd93cc49662.png)

same here!

**Comment by micduffy** [comment]
I am also experiencing this error - I dont know why it was closed without resolution
