### ISSUE TITLE
Fluxstore pro 1.4.2 

### ISSUE THREAD

**Issue by samik9** [inspireui/support#970]
Got this error when going to checkout page, video here https://d.pr/v/FSsFPl

![Screenshot_1566520347](https://user-images.githubusercontent.com/50071744/63558701-95d00800-c513-11e9-8909-8001663512c5.png)

**Comment by minhtruong315** [comment]
@samik9 can you send me your source code via email truong@inspireui.com

**Comment by samik9** [comment]
@minhtruong315 email sent! 

Also same happen in other tabs in the app , check the gif bellow 

![ezgif-3-10dcfdcb240d](https://user-images.githubusercontent.com/50071744/63565636-54e5ec80-c52f-11e9-8515-490c5960da93.gif)

**Comment by minhtruong315** [comment]
https://www.dropbox.com/s/jssaubfwaj4cfki/Untitled.mov?dl=0
I checked your source code. it is working well. I can not reproduce your issues

**Comment by minhtruong315** [comment]
@samik9 can you remove simulator cache then test again?

**Comment by samik9** [comment]
I cleared chache, also tried with iOS simulator and got same isssue, this is actually very new in this version 1.4.2 cause all previews versions dont have this problem
![ezgif-3-42c4ff59417e](https://user-images.githubusercontent.com/50071744/63579130-8b376200-c557-11e9-8084-0040a584b791.gif)

**Comment by minhtruong315** [comment]
@samik9 add my skype: minhtruong315. i will help you check via teamviewer

**Comment by samik9** [comment]
@minhtruong315  your skype username does not show on skype, mine is : evilnoise@icloud.com

**Comment by minhtruong315** [comment]
done

**Comment by peter2411** [comment]
i have the same problem 
my purchase code :
8dbbf678-9549-4386-8a4e-91e526e40b3e

**Comment by samik9** [comment]
@peter2411 Bro please don’t share your purchase code in  a public page.  

Regards

**Comment by peter2411** [comment]
@samik9 
Well bro I have modified my comment , Have you got solve for the problem ?
