### ISSUE TITLE
Fluxstore Pro epayco and payulatam support

### ISSUE THREAD

**Issue by samik9** [inspireui/support#971]
Good day team, I noticed that you closed the ticket #941  but the issue is not really fixed.
CONFIG FILE: https://d.pr/f/FgmEq4

 On payment gateway When **“GuestCheckout”: false**, everything works well **BUT** when I click on ePayco to make the purchase, it takes me to the webview BUT it autoselect “cash on delivery” Video: https://d.pr/v/umUbIP

Now when **“GuestCheckout”: true**, on cofing.dart; the only screen a got in checkout is: Invalid authentication cookie. Please try to login again. Video: https://d.pr/v/tSBttS

**Comment by minhtruong315** [comment]
@samik9 Can you checkout in your website?

**Comment by samik9** [comment]
@minhtruong315 yeah, please check this video, on web, all works **perfect** with epayco and payulatam video: https://d.pr/v/V77ar9


https://gzo.io/buganbillia/tienda/

**Comment by minhtruong315** [comment]
@samik9 can you try to increase LimitRequestLine? then restart apache
https://stackoverflow.com/questions/2586339/how-to-increase-apache-2-uri-length-limit/32644323

**Comment by samik9** [comment]
The support on my hosting told me that they have gone ahead and increased it accordingly and restarted Apache.

**Comment by samik9** [comment]
Hi guys, any update on this?

**Comment by minhcasi** [comment]
Hi, sorry for the late response, we have double the issues on our site and could not find out the issue, we suspect it could cause by the data issue on your site. 

Could you try to debug from the website - /mstore-checkout/templates/mstore-checkout-template.php - try to debug this order value after getting the URL from the app side -  https://tppr.me/MVYw2 ?

**Comment by samik9** [comment]
i am sorry, i dont know how to do that, so far is not easy to run an external payment. My store is not close to be ready for production :/

**Comment by samik9** [comment]
The only way that make this to really work is only allow **epayco gatewa**y alone, if i let **cash on delivery** or more payment methods I will get all bugs mentioned above.
But of course I need to let the other methods available

**Comment by minhcasi** [comment]
@samik9 - is it possible to connect your site via FTP for debugging ?
