### ISSUE TITLE
[Fluxstore woocommerce] - (1.4.2) Errors , scrolling Jump, attributes related bug

### ISSUE THREAD

**Issue by Isodie** [inspireui/support#972]
Hi
I have listed 3 issues

1- **Having bugs on various pages.**
<img width="400" alt="Screenshot 2019-08-23 at 11 53 28 AM" src="https://user-images.githubusercontent.com/14618403/63572447-864ad080-c5a0-11e9-929d-5531ce74d631.png">
<img width="400" alt="Screenshot 2019-08-23 at 11 53 39 AM" src="https://user-images.githubusercontent.com/14618403/63572448-86e36700-c5a0-11e9-8095-661cbbb6049e.png">
<img width="405" alt="Screenshot 2019-08-23 at 11 53 48 AM" src="https://user-images.githubusercontent.com/14618403/63572449-86e36700-c5a0-11e9-9322-53d4d4227100.png">

2- **Scrolling jumps back up after going from product page**. See gif
![ezgif-4-0f10bef65ac3](https://user-images.githubusercontent.com/14618403/63572305-34a24600-c5a0-11e9-9cd0-0c79d170f8ba.gif)

3- **For simple product Attributes are shown as variable product**. See image
<img width="399" alt="Screenshot 2019-08-23 at 11 56 11 AM" src="https://user-images.githubusercontent.com/14618403/63572486-9b276400-c5a0-11e9-9d95-77387f21093d.png">

**Comment by peter2411** [comment]
me too . same error

**Comment by minhtruong315** [comment]
@Isodie we will release next version next week. You can update it
