### ISSUE TITLE
[ListApp] -  Error in the Home page and listing page

### ISSUE THREAD

**Issue by x028** [inspireui/support#973]
**Hello
Hope you have a good day 
I have some errors 
first one when I use The Seventh home page it shows me like this image**

![photo_2019-08-23_09-02-44](https://user-images.githubusercontent.com/45524078/63577592-62cf5800-c597-11e9-9513-64e0dfcfa16f.jpg)
**note I already add an image in Featured Image in WordPress post
and if I use any other home page it works fine!

the second problem in listing page when I use the Arabic language the tel and website should be on the right side not left** 

![photo_2019-08-23_09-09-31](https://user-images.githubusercontent.com/45524078/63577712-b5107900-c597-11e9-8d4b-845b4ff25cf1.jpg)

**the third problem in the categories page when I use the Arabic language it shows like this!** 

![photo_2019-08-23_09-07-13](https://user-images.githubusercontent.com/45524078/63577785-dcffdc80-c597-11e9-9b5f-c7ec8ebb0fb5.jpg)

**the fifth problem in listing page too, there are two sections missing** 

![er1](https://user-images.githubusercontent.com/45524078/63578135-8515a580-c598-11e9-938a-50076a068658.PNG)
![er2](https://user-images.githubusercontent.com/45524078/63578136-8515a580-c598-11e9-82f2-dd702d29a5c4.PNG)

**I should get this two-section in listing page but they are missing!

thanks**

**Comment by x028** [comment]
below the config file

[AppConfig.txt](https://github.com/inspireui/support/files/3533633/AppConfig.txt)

**Comment by thangvo9x** [comment]
1. Check you Renegrate Thumbnail plugin from your admin.
2. Try to replace these below file at Container/Detail/
Remember change from .txt tag -> .js tag
[ListingDetail.txt](https://github.com/inspireui/support/files/3544145/ListingDetail.txt)
[styles.txt](https://github.com/inspireui/support/files/3544146/styles.txt)
3. Work normally.
4 such as 5 (because I can't see the fourth). The App doesn't support this section. 
Thanks.

**Comment by x028** [comment]
1- I'm already checked that and checked again and the problem still!  

2- ok fix thanks 

3- no it's not working normally checked in two pc and the same problem. it works normally in the English language and when I change the language of the app to Arabic the problem show!   

4 and 5 so important how can you retrieve all the other section and for this two-section you can't? 

**thanks for your response**

**Comment by thangvo9x** [comment]
4 & 5 The App doesn't support to get this two-section now. I will get in the next version. Thanks

**Comment by x028** [comment]
what about the no. 1, 2 and 3 ?

**Comment by x028** [comment]
@minhcasi you should not make it closed sir :)
