### ISSUE TITLE
[my-product] - Xin giúp cài đặt Yarn và Expo

### ISSUE THREAD

**Issue by antontrantien** [inspireui/support#974]
Xin giúp cài đặt **Yarn** và **Expo** 
Tôi đã làm theo hướng dẫn và cài đặt nhưng kết quả ko cài được.
 **Yarn**
https://yarnpkg.com/lang/en/docs/install/#mac-stable
đã làm theo
**Expo** 
https://docs.expo.io/versions/latest/introduction/installation/
<img width="1436" alt="Expo" src="https://user-images.githubusercontent.com/54436202/63582405-36c9cc00-c5c3-11e9-9498-9874b862aad5.png">
<img width="1326" alt="MStore Pro" src="https://user-images.githubusercontent.com/54436202/63582406-37626280-c5c3-11e9-98eb-d6b88c394741.png">
<img width="1440" alt="Yarn" src="https://user-images.githubusercontent.com/54436202/63582407-37626280-c5c3-11e9-81c8-a20cc314d528.png">

Xin hướng dẫn giúp tôi. chân thành cảm ơn!

**Comment by concuacon** [comment]
@antontrantien, bạn gửi mình skype của bạn, trao đổi qua đó nhanh hơn.
