### ISSUE TITLE
Error loading the app

### ISSUE THREAD

**Issue by betterend** [inspireui/support#975]
Hi,

Kindly i have connected the Fluxstore and set woocomm key in config.da
![fluxstore](https://user-images.githubusercontent.com/34990153/63589995-a0de7300-c5bb-11e9-9a33-5830b756169f.jpg)
rt. i'm getting the attached error,

how can i fix it

**Comment by minhtruong315** [comment]
@betterend pls send me config.json and config.dart file via email: truong@inspireui.com
