### ISSUE TITLE
[my-product] - 

### ISSUE THREAD

**Issue by Pars1vaLl** [inspireui/support#976]
Hi,

I can`t start my IOS project. Getting errors all the time trying to run the App. Here are the screens.
![1](https://user-images.githubusercontent.com/45024483/63633079-9a9fd380-c65b-11e9-91dd-27eeb7814045.jpg)
![2](https://user-images.githubusercontent.com/45024483/63633088-b60ade80-c65b-11e9-8a8c-ebfd91041251.png)

Hope you will help as soon as possible. Thanks

**Comment by minhcasi** [comment]
Hi, could you help to check following solution:
1. try with Android Studio, and run the ios project from this tools.

2. try to run "flutter doctor" to check if there is any error

3. Make sure you run the Test Drive guideline successful - https://flutter.dev/docs/get-started/test-drive
