### ISSUE TITLE
[LISTAPP] - Listing Type ID

### ISSUE THREAD

**Issue by bobozd** [inspireui/support#977]
Hello,

As we already have in Listapp to include only specific Listings-Categories ID, to be visible inside Listapp, I waould like to be able also to display only specific LISTING TYPE from MyListing wordpress? Is is possible anyhow with ID's ?

Screen attached!
![listing_type](https://user-images.githubusercontent.com/28021993/63635689-82cd4d00-c665-11e9-85fe-2a9bb0a4be22.png)

**Comment by thangvo9x** [comment]
Now. The App doesn't have this function. Thanks for the question. We noted for the next release version.
