### ISSUE TITLE
TypeError: Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by kailash1805a** [inspireui/support#978]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue
I am getting this issue when i am calling get product api.
Please help me i am block from last 4 days.

TypeError: Cannot read property 'get' of undefined
    at _callee$ (WooWorker.js:37)
    at tryCatch (runtime.js:45)
    at Generator.invoke [as _invoke] (runtime.js:271)
    at Generator.prototype.<computed> [as next] (runtime.js:97)
    at tryCatch (runtime.js:45)
    at invoke (runtime.js:135)
    at runtime.js:170
    at tryCallTwo (core.js:45)
    at doResolve (core.js:200)
    at new Promise (core.js:66)
2. Screenshots
<img width="494" alt="Screenshot 2019-08-24 at 8 24 35 PM" src="https://user-images.githubusercontent.com/20530376/63639073-3574ce00-c6ad-11e9-86c6-7d629d1ed169.png">

3. My screenshot of the purchase product or my comment:

<img width="768" alt="Screenshot 2019-08-24 at 8 21 56 PM" src="https://user-images.githubusercontent.com/20530376/63639036-ec247e80-c6ac-11e9-9d58-f1d26c808229.png">

**Comment by minhcasi** [comment]
Hi, could you share the config files (comon/appconfig.json and config.js file), it seems there is an issue with your Wordpress setting?
