### ISSUE TITLE
fluxstore-woocommerce v 1.4.2 issue

### ISSUE THREAD

**Issue by peter2411** [inspireui/support#979]
1. My issue

i was expected that 1.4.2 version will fix my only issue "blog sliding error" , so i deleted the last versions , and i surprised by the issues of this version ,
from the begining of purchase your product i was only need a version without issues to use it and i waited alot of updates with
alot of time and still no real solve or real updated without issues !,

**all i need now is the last version "fluxstore-woocommerce v 1.4.1"
Because I deleted it for trust of the new version
i need it with only solve for "blog sliding error" no more . i don't need any new features , and 
i can't wait for the new update .
please send it to me via email

2 - My screenshot of the purchase product or my comment:

https://prnt.sc/ox539v

**Comment by minhcasi** [comment]
update via email - thanks
