### ISSUE TITLE
[MStore, ListApp] Chat

### ISSUE THREAD

**Issue by samber91** [inspireui/support#98]
**Mandatory Info (please complete the following information):**
 - Product: [e.g. MStore, ListApp]
 - Your Purchased Code: [get from https://codecanyon.net/downloads]
(we may not reply if you are not our customer)

**Describe the issues**

**Screenshots**

**Additional context**
Add any other detail logs about the problem here.

**Comment by samber91** [comment]
Hi. In the documentation, there is no mention of how we should configure the chat function. For a non developper like me, that will be great if i can have more explanation about how to set it up. 
Next question: i heard that people could not publish the app on app store. Is it true ? If yes what to do. 
Answer the 2 questions.
thanks

**Comment by samber91** [comment]
Purchase code : ad1ac976-3e34-4e40-a473-0985df712891

**Comment by minhcasi** [comment]
@samber91 Thank you for your question:
- We will update the document to explain more about chat feature, it is working on MyListing but could be an issue with other template. Basically it just about the config the Firebase to connect for store the chat message.

- There is no problem to publish the app on Appstore, you can see our demo app there - https://itunes.apple.com/us/app/listapp-listing-directory/id1355477469

**Comment by samber91** [comment]
Still need chat feature. Need a tutorial asap please. My business needs it
