### ISSUE TITLE
[MStore] - Change country and states into select

### ISSUE THREAD

**Issue by itsmefurzy** [inspireui/support#981]
I want to change country text from ID into country name Indonesian and then the states must select, now it is free text. I want to look like Website 
---------

1. My issue
I want to change country text from ID into country name Indonesian and then the states must select, now it is free text. I want to look like Website 

2. My screenshot of the purchase product or my comment:
http://prntscr.com/ox9hdl

**Comment by minhcasi** [comment]
Hi, it's possible to change the billing address base on your country state, it's required some reactjs knowledge to customize these features - thank you!
