### ISSUE TITLE
Mstore pro

### ISSUE THREAD

**Issue by leghost** [inspireui/support#983]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

I. My issue 1 pro version
Problem to set up Mstore pro Android Version using Angroid studio

1. Screenshots
![image](https://user-images.githubusercontent.com/47028114/63691352-3d4c8380-c80f-11e9-881a-db001cb89211.png)

2. My screenshot of the purchase product or my comment:
![image](https://user-images.githubusercontent.com/47028114/63691461-8997c380-c80f-11e9-8147-a3be5e80d1c4.png)

II. Issue 2 expo version

Ploblem on the expo app version in android. 
-Somes icons are not showing 
![WhatsApp Image 2019-08-26 at 15 23 06](https://user-images.githubusercontent.com/47028114/63694068-e39b8780-c815-11e9-8717-000da83c4960.jpeg)

-I can't compleate the checkout after created a checkout page. the compleate button put loading and nothing happen. 
![WhatsApp Image 2019-08-26 at 15 21 49](https://user-images.githubusercontent.com/47028114/63694056-ded6d380-c815-11e9-9bd3-d2bf86f5a8c1.jpeg)

-It's not possible to change currentcy in the expo app.

3. Config files (optional)

**Comment by mcdavri** [comment]
bruh for your first issue you can make sure your java sdk is installed and the path is to it is bashrc file then run npm install in your mstore pro folder, then open up the directory in a terminal and run npm start  and on a new tab in the terminal run react-native run-android p.s: make sure yhu have a good internet and an emulator up already first preferably genymotion

**Comment by leghost** [comment]
i ran a react native projet with this config , so i'm not sure that the problem comes from java sdk

**Comment by concuacon** [comment]
Hello @mcdavri, 
You can try the following steps:
For first issue: 

- remove node_modules/ folder, reinstall package: run yarn or npm install

- cd android/ && ./gradlew clean && cd ../

- open Android Studio refactor app to AndroidX and open comand line run react-native run-android.
Second issue: 

- Remove node_modules/ and reinstall

- Run app again.
