### ISSUE TITLE
[mstore pro] - 

### ISSUE THREAD

**Issue by mcdavri** [inspireui/support#984]
hello good day, i have a couple of issues i want to resolve and would like your assistance; 1) the categories section that lists a category of products i noticed the products list details overlaps don’t know how to resolve that or even change the layout 2) the shipping section i want to set a default shipping in the event the user does not select a shipping method because i noticed on the app a user can checkout without selecting a shipping method and that is not what we want now. 3) after creating a page mstore-checkout and also installing the necessary plugins i noticed my payment gateway paystack still doesn’t come up i get an empty checkout page 4) on the news section no images are displayed and clicking on a news throws back an error 5) when i run react-native run-android i get two instance of the application installed on my phone

screenshots to my issues 
https://pasteboard.co/IurFuLa.png : https://pasteboard.co/IurEWbO.png : https://pasteboard.co/IurExpq.png : https://pasteboard.co/IutoWau.png

my comment on the codecanyon
https://pasteboard.co/IuuUiJs.png

my website is:
ha.helpapp.com.ng
contact me via my email if yhu require the login details

config files:
[config files.zip](https://github.com/inspireui/support/files/3543806/config.files.zip)

**Comment by concuacon** [comment]
@mcdavri 
"the shipping section i want to set a default shipping in the event the user does not select a shipping method because i noticed on the app a user can checkout without selecting a shipping method and that is not what we want now" => pls show detail your request, i don't know u want set default shipping fee?  and give me your email i'll send new source after fixed.

**Comment by mcdavri** [comment]
okay my email is umohmcdave@gmail.com

**Comment by concuacon** [comment]
> Hello @mcdavri
> "the shipping section i want to set a default shipping in the event the user does not select a shipping method because i noticed on the app a user can checkout without selecting a shipping method and that is not what we want now" => pls show detail your request, i don't know u want set default shipping fee?
@mcdavri
