### ISSUE TITLE
Hi, There's bug on my app. 

### ISSUE THREAD

**Issue by yngwieduane** [inspireui/support#985]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue
I have this issue showing on my app, and also when im changing the images on the category its not working. please help.

2. Screenshots
![image](https://user-images.githubusercontent.com/18515128/63709356-c089cb80-c847-11e9-9481-3d5269a6f6bd.png)

3. My screenshot of the purchase product or my comment:
![image](https://user-images.githubusercontent.com/18515128/63709562-37bf5f80-c848-11e9-9d53-61e9aa1393ea.png)

3. Config files (optional)

**Comment by yngwieduane** [comment]
Hello?? please response to my concern please.

**Comment by minhcasi** [comment]
HI, please try to download the latest 1.4.3 that released on yesterday will be fixed this issue, thank you!
