### ISSUE TITLE
[BeoNews] - lots of Crashed and Admob not display

### ISSUE THREAD

**Issue by aeliusventure** [inspireui/support#987]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue
-Open the screens and scroll down and crashed.
-Open Screen and tap on relative screen and crashed
- Some time open the application then crashed

2. Screenshots
Unable capture crashed, I can share whole code if you need.
3. My screenshot of the purchase product or my comment:
![bug](https://user-images.githubusercontent.com/30139674/63762958-65a4b280-c8e1-11e9-971f-ff5babf2650f.jpg)

3. Config files (optional)

**Comment by minhcasi** [comment]
ok, please share your whole code to support@inspireui.com - pls note that we will not fix the code that already customizes the features as it is out of support scope.

Kindly changes your rating on our product for getting further support, it's not goodwill honestly.
