### ISSUE TITLE
[Fluxstore 1.4.2] - Can`t run Fluxstore on Android Emulator

### ISSUE THREAD

**Issue by Pars1vaLl** [inspireui/support#989]
Hi team,

I am struggling with launching Fluxstore on Android emulator. I tested emulator with default Flutter App - it works perfectly. However it doesn`t run when I try to launch Fluxstore. Here is the screen:
![Error](https://user-images.githubusercontent.com/45024483/63771793-43b32c00-c8f1-11e9-8ea4-751c65978d12.png)

Please help to solve this issue. Thanks)

**Comment by minhcasi** [comment]
Hi, could you help to take your screenshot purchased?

**Comment by Pars1vaLl** [comment]
Here it is. Hope you will help as soon as possible. 
![Screenshot_2](https://user-images.githubusercontent.com/45024483/63820143-9af0e500-c961-11e9-8005-114a7ac9e36b.png)

**Comment by minhtruong315** [comment]
@Pars1vaLl You can open pubspec.yaml file, then click Packages get to update dependency
<img width="1033" alt="Screen Shot 2019-08-28 at 11 19 47" src="https://user-images.githubusercontent.com/10402500/63825693-ed43fd00-c985-11e9-9dec-bf37f3f10c3d.png">
