### ISSUE TITLE
[CeStore] Problem with mongodb table and integrating module in webapp

### ISSUE THREAD

**Issue by fahmidev013** [inspireui/support#99]
**Mandatory Info (please complete the following information):**
 - Product: [CeStore]
 - Your Purchased Code: [d1e19c39-b9cb-4e82-XXXX-b02b9b222XXd]
(i may hid some of purchased code)

**Describe the issues**
I have follow all your step by step instruction to install and build web and API but...in the end... web is launched on localhost:3000 ..but the data is empty... and some page show page not found...how could be like that?

how to install the template data and table in proper way? the documentation is not user friendly..especially about mongodb. and generating template data.... really confusing...

and also contact page not show ..only page not dound...but localhost:3000 server has up...

please guide me through this instalation process... FYI im using npm run install at early...it should be fine, is nt... im wonder perhaps its just about integrating data and table between mongo and web app..

**Comment by minhtruong315** [comment]
Hi @fahmidev013 Did you see this video? https://www.dropbox.com/s/iac8xvuyotjl2sj/install_cestore_website.mov?dl=0

**Comment by fahmidev013** [comment]
> Hi @fahmidev013 Did you see this video? https://www.dropbox.com/s/iac8xvuyotjl2sj/install_cestore_website.mov?dl=0
> You need to install mongodb studio to import template data. https://studio3t.com/
> Let me know if you have any issues.
> Thanks

not yet,...
can i use MongoDB Compass  instead studio3t ?

**Comment by fahmidev013** [comment]
How is that?please tell me detail...i appreciate

**Comment by fahmidev013** [comment]
ok. ..i install 3T and now its working..but  there is some issue...

i cant checkout and finish transaction  like this..
![image](https://user-images.githubusercontent.com/43770763/50034637-70a80300-0030-11e9-9667-f3a6f3e650a2.png)

and validation is not working as well when i entered wrong format email  and etc..

any help?

**Comment by minhcasi** [comment]
Noted for next release improvement - thank you!
