### ISSUE TITLE
[beonews] - apple store crash

### ISSUE THREAD

**Issue by anatoliasystem** [inspireui/support#990]
Hello,

The application working properly with the simulator. working properly with the phone on the same wifi network. But, When you download application apple store, the application is opening waiting and closing.

Apple Store Application Link: https://apps.apple.com/tr/app/%C3%A7ar%C5%9F%C4%B1-1461/id1474621167?l=tr

Could you help?

**Comment by minhcasi** [comment]
Could you help to share your purchased screenshot from https://codecanyon.net/downloads?  thank you!

**Comment by anatoliasystem** [comment]
![app](https://user-images.githubusercontent.com/54587122/63834687-8cfd8d00-c97e-11e9-85ee-ed1f7b358715.jpg)

**Comment by anatoliasystem** [comment]
You did not answer?

**Comment by minhcasi** [comment]
We could not download your app on our country (US or VN store) so that could not have a check.

Could you try to install the Sentry to check the root cause of crashing on production app? https://sentry.io/welcome/
