### ISSUE TITLE
[Beonews] - TypeError

### ISSUE THREAD

**Issue by kevlict** [inspireui/support#991]
Hello, I encounter the problem when I start the app. The splash screen showed correctly.
I have install the BETTER REST API to my wordpress.
My blog is http://app.simplytastehk.com/app, you may test it with your app.

Screenshot:

![unnamed](https://user-images.githubusercontent.com/54314498/63782115-783cdd00-c91d-11e9-88fc-6765d22e2f97.jpg)

Thanks!

**Comment by minhcasi** [comment]
Please install this plugin will be fixed the issue - https://wordpress.org/plugins/better-rest-api-featured-images/

**Comment by kevlict** [comment]
hello.

Thank you.

However, I have installed this plugin but the problem still exists. Please kindly advise.

**Comment by kevlict** [comment]
> Please install this plugin will be fixed the issue - https://wordpress.org/plugins/better-rest-api-featured-images/
> 
> 
> WordPress.org
> Better REST API Featured Images
> Adds a top-level field with featured image data including available sizes and URLs to the post object returned by the REST API.

hello.

Thank you.

However, I have installed this plugin but the problem still exists. Please kindly advise.

**Comment by minhcasi** [comment]
@kevlict could you attache your config file from common/appconfig.json and config.json - we will have a check and let you know.

Also, take the screenshot of purchasing on this product to verify your purchased - thank you!
