### ISSUE TITLE
FluxStore-woo 1.4.2 -I/flutter (11227): Failed assertion: line 136 pos 14: '!listenable.hasListeners'

### ISSUE THREAD

**Issue by mo7ammedgaber** [inspireui/support#994]
i am download the template and build it and i have this error 
can u help me ??

D/mali_winsys(11227): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/mali_winsys(11227): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
E/BpSurfaceComposerClient(11227): Failed to transact (-1)
E/BpSurfaceComposerClient(11227): Failed to transact (-1)
W/InputMethodManager(11227): startInputReason = 1
Restarted application in ٦٬٧٦٦ms.
I/HwPhoneWindow(11227): updateLayoutParamsColor false mSpecialSet=true, mForcedNavigationBarColor=true, navigationBarColor=ff000000, mNavBarShow=false, mIsFloating=false
I/ViewRootImpl(11227): jank_removeInvalidNode all the node in jank list is out of time
V/AudioManager(11227): playSoundEffect   effectType: 0
V/AudioManager(11227): querySoundEffectsEnabled...
I/flutter (11227): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (11227): The following assertion was thrown building CategoriesScreen(dependencies:
I/flutter (11227): [InheritedProvider<CategoryModel>], state: CategoriesScreenState#31a30(ticker inactive)):
I/flutter (11227): The default constructor of ListenableProvider/ChangeNotifierProvider
I/flutter (11227): must create a new, unused Listenable.
I/flutter (11227): 
I/flutter (11227): If you want to reuse an existing Listenable, use the second constructor:
I/flutter (11227): 
I/flutter (11227): - DO use ChangeNotifierProvider.value to provider an existing ChangeNotifier:
I/flutter (11227): 
I/flutter (11227): MyChangeNotifier variable;
I/flutter (11227): ChangeNotifierProvider.value(
I/flutter (11227):   value: variable,
I/flutter (11227):   child: ...
I/flutter (11227): )
I/flutter (11227): 
I/flutter (11227): - DON'T reuse an existing ChangeNotifier using the default constructor.
I/flutter (11227): 
I/flutter (11227): MyChangeNotifier variable;
I/flutter (11227): ChangeNotifierProvider(
I/flutter (11227):   builder: (_) => variable,
I/flutter (11227):   child: ...
I/flutter (11227): )
I/flutter (11227): 'package:provider/src/listenable_provider.dart':
I/flutter (11227): Failed assertion: line 136 pos 14: '!listenable.hasListeners'
I/flutter (11227): 
I/flutter (11227): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (11227): more information in this error message to help you determine and fix the underlying cause.
![69318715_390597384866272_8176380587729223680_n](https://user-images.githubusercontent.com/54624558/63848056-672cb400-c98f-11e9-9546-d390ce9161c8.jpg)
![image](https://user-images.githubusercontent.com/54624558/63848160-96dbbc00-c98f-11e9-843f-7ef12c95b254.png)

**Comment by minhcasi** [comment]
Hi, confirmed this is fixed on v1.4.3 - thank you!

**Comment by mo7ammedgaber** [comment]
when i click build i have this error
C:\Users\ZaG\Desktop\FluxStore-woo 1.4.3\source: pub did not update .packages file (pubspec.yaml file has a newer timestamp)

**Comment by mo7ammedgaber** [comment]
now i download new version  
C:\Users\ZaG\Desktop\FluxStore-woo 1.4.3\source>flutter run
Running "flutter pub get" in source...                              ٢٫٩s
C:\Users\ZaG\Desktop\FluxStore-woo 1.4.3\source: pub did not update .packages file (pubspec.yaml file has a newer timestamp)

**Comment by minhtruong315** [comment]
https://www.youtube.com/watch?v=g-u6JPB36jg&list=PLcF-HiQy-jOJAD8btGgr_CHcUmYyN8GgY&index=3&t=0s

**Comment by mo7ammedgaber** [comment]
thanks

can u help me at this case
[image: image.png]

?

‫في الخميس، 29 أغسطس 2019 في 2:26 ص تمت كتابة ما يلي بواسطة
‪minhtruong315‬‏ <‪notifications@github.com‬‏>:‬

**Comment by minhtruong315** [comment]
@mo7ammedgaber i dont see image. pls send again

**Comment by mo7ammedgaber** [comment]
This error

**Comment by minhtruong315** [comment]
<img width="749" alt="Screen Shot 2019-08-30 at 08 42 45" src="https://user-images.githubusercontent.com/10402500/63987378-286b3b00-cb02-11e9-93ae-a87a3179859c.png">
I dont see image

**Comment by mo7ammedgaber** [comment]
Okay
I am ask u about sign up with sms i received code with whatsapp like
Use 430485 as your login code for FluxStore. (Account Kit by Facebook)

How change fluxstore with my store name?
And activeing login with Facebook
Thanks

**Comment by minhtruong315** [comment]
@mo7ammedgaber https://pub.dev/packages/flutter_facebook_login
pls follow by this document to config facebook login

**Comment by usman19977** [comment]
@mo7ammedgaber can u share the code ?

**Comment by minhcasi** [comment]
@usman19977 - could i check if you have purchased the product already ?

**Comment by mo7ammedgaber** [comment]
Yes iam already buy it by my email
Mo7ammedgaber@gmail.com
