### ISSUE TITLE
i am unable to setup the theme, could you please suggest the process

### ISSUE THREAD

**Issue by cisinindore** [inspireui/support#995]
i am unable to setup the theme, could you please suggest the process...
I had tried in different way, could you please explain step by step.

**Comment by minhcasi** [comment]
- could you share your license screenshot of the product of you have purchased? 
- Also, share us the detail issue so that we could help

Thank you!

**Comment by cisinindore** [comment]
I am getting below error:
![Screenshot from 2019-08-29 12-35-25](https://user-images.githubusercontent.com/14923648/63918065-94de2f80-ca59-11e9-9397-2f64b9ab682a.png)

**Comment by cisinindore** [comment]
We are using Ubuntu machine... Will it be work ?

**Comment by minhcasi** [comment]
sent via email
