### ISSUE TITLE
[Fluxstore] - help to update the app

### ISSUE THREAD

**Issue by Pars1vaLl** [inspireui/support#997]
Hi guys,

We have configured Fluxstore 1.4.2 and doesn`t want to configure 1.4.3 from zero. Could you please send changed files us OR let us know which files were changed in 1.4.3 version, so we could just replace that files with new ones and save some time. Here is purchase code: https://user-images.githubusercontent.com/45024483/63820143-9af0e500-c961-11e9-8005-114a7ac9e36b.png

Thank you=)

**Comment by minhcasi** [comment]
Hi, please use this patch file to check the diff - https://www.dropbox.com/s/uuiha2th3kgwgk5/1.4.3.patch?dl=0
