### ISSUE TITLE
Fluxstore WooCommerce Version: 1.4.3 , facebook login Error

### ISSUE THREAD

**Issue by peter2411** [inspireui/support#998]
1. My issue
Version: 1.4.3 , Error when try to login via facebook 

2. Screenshots
https://prnt.sc/oyxuw7

3. My screenshot of the purchase product or my comment:
https://prnt.sc/oyxvn7

**Comment by minhtruong315** [comment]
@peter2411 can you send me your source code via email: truong@inspireui.com?
